### ISSUE TITLE
How to hook into AppDomain.ProcessExit ?

### ISSUE THREAD

**Issue by ljw1004** [dotnet/corefx#10012]
In regular .NETFramework console apps, I can hook into `AppDomain.CurrentDomain.ProcessExit` event to be notified when the console app terminates.

This doesn't seem to be present in .NETCore. How else can my library get notified when the calling .NETCore console app terminates?

**Comment by jkotas** [comment]
The current solution is to subscribe to `AssemblyLoadContext.Default.Unloading` event.

**Comment by ljw1004** [comment]
Thank you.

That looks painful to use in a library that can work on both .NETFramework and .NETCore (nuget package System.Runtime.Loader depends on .net462).

I guess I might it in a NuGet which does bait-and-switch between .NETFramework using AppDomain and .NETCore using AssemblyLoadContext.

Or more likely, I'll use reflection to determine at runtime whether AppDomain.dll assembly is loaded, if not that then whether System.Runtime.Loader.dll assembly is loaded, if not that then fail.

**Comment by ljw1004** [comment]
For what it's worth, here below is my solution. Re-opening just so @gkhanna79 / @jkotas can take a glance. (please feel free to close it afterwards).

In a .NETFramework app, it safely assumes that `mscorlib` has already been loaded, and it uses reflection to pick up `AppDomain.CurrentDomain`.

In a .NETCore app, it *requires* that the caller has added a NuGet reference to `System.Runtime.Loader`, and has already done something to load that assembly (e.g. by declaring a variable of type `System.Runtime.Loader.AssemblyLoadContext`). Only if these requirements are met will it be able to use reflection to find what's needed.


From a .NETCore app I call it like this:
```cs
System.Runtime.Loader.AssemblyLoadContext dummy;
OnExit.Register(() => Console.WriteLine("OnExit"));
```

From a .NETFramework app I call it like this:
```cs
OnExit.Register(() => Console.WriteLine("OnExit"));
```

And this is the implementation of the Register function:
```cs
public class OnExit
{
    public static void Register(Action onExit)
    {
        var refs = Assembly.GetEntryAssembly().GetReferencedAssemblies();
        var mscorlib = refs.SingleOrDefault(r => r.Name == "mscorlib");
        var loader = refs.SingleOrDefault(r => r.Name == "System.Runtime.Loader");
        var runtime = refs.SingleOrDefault(r => r.Name == "System.Runtime");

        if (mscorlib != null)
        {
            var currentAppDomain = Assembly.Load(mscorlib).GetType("System.AppDomain").GetTypeInfo().GetProperty("CurrentDomain").GetValue(null, null);
            var processExitEvent = currentAppDomain.GetType().GetTypeInfo().GetEvent("ProcessExit");
            EventHandler lambda = (sender, e) => onExit();
            processExitEvent.AddEventHandler(currentAppDomain, lambda);
        }

        else if (loader != null)
        {
            var loadContextType = Assembly.Load(loader).GetType("System.Runtime.Loader.AssemblyLoadContext");
            var currentLoadContext = loadContextType.GetTypeInfo().GetProperty("Default").GetValue(null, null);
            var unloadingEvent = currentLoadContext.GetType().GetTypeInfo().GetEvent("Unloading");
            var delegateType = typeof(Action<>).MakeGenericType(loadContextType);
            Action<object> lambda = (context) => onExit();
            unloadingEvent.AddEventHandler(currentLoadContext, lambda.GetMethodInfo().CreateDelegate(delegateType, lambda.Target));
        }

        else if (runtime != null)
        {
            throw new Exception("Before calling this function, declare a variable of type 'System.Runtime.Loader.AssemblyLoadContext' from NuGet package 'System.Runtime.Loader'");
        }

        else
        {
            throw new Exception("Neither mscorlib nor System.Runtime.Loader is referenced");
        }

    }

}
```

**Comment by jkotas** [comment]
> In a .NETCore app, it requires that the caller has added a NuGet reference

It requires that the app entrypoint assembly (that may or may not be the caller of your method) has added reference to System.Runtime.Loader. Also, for .NETFramework it requires that the app entrypoint has reference to mscorlib (ie the app entrypoint assembly cannot be compiled as portable .exe).

A better way to do what you are trying to do is to call `Type.GetType(..., throwOnError: false);`.

**Comment by ljw1004** [comment]
Thanks @jkotas. I amended to to this:

```csharp
public static void OnExit(Action onExit)
{
    var assemblyLoadContextType = Type.GetType("System.Runtime.Loader.AssemblyLoadContext, System.Runtime.Loader");
    if (assemblyLoadContextType != null)
    {
        var currentLoadContext = assemblyLoadContextType.GetTypeInfo().GetProperty("Default").GetValue(null, null);
        var unloadingEvent = currentLoadContext.GetType().GetTypeInfo().GetEvent("Unloading");
        var delegateType = typeof(Action<>).MakeGenericType(assemblyLoadContextType);
        Action<object> lambda = (context) => onExit();
        unloadingEvent.AddEventHandler(currentLoadContext, lambda.GetMethodInfo().CreateDelegate(delegateType, lambda.Target));
        return;
    }

    var appDomainType = Type.GetType("System.AppDomain, mscorlib");
    if (appDomainType != null)
    {
        var currentAppDomain = appDomainType.GetTypeInfo().GetProperty("CurrentDomain").GetValue(null, null);
        var processExitEvent = currentAppDomain.GetType().GetTypeInfo().GetEvent("ProcessExit");
        EventHandler lambda = (sender, e) => onExit();
        processExitEvent.AddEventHandler(currentAppDomain, lambda);
        return;
        // Note that .NETCore has a private System.AppDomain which lacks the ProcessExit event.
        // That's why we test for AssemblyLoadContext first!
    }


    bool isNetCore = (Type.GetType("System.Object, System.Runtime") != null);
    if (isNetCore) throw new Exception("Before calling this function, declare a variable of type 'System.Runtime.Loader.AssemblyLoadContext' from NuGet package 'System.Runtime.Loader'");
    else throw new Exception("Neither mscorlib nor System.Runtime.Loader is referenced");

}
```

**Comment by gkhanna79** [comment]
You should account for missing assemblies (e.g. S.R.L is not present on Desktop) but otherwise, looks fine to me.

**Comment by GuardRex** [comment]
@ljw1004 Thanks for posting this. It works great. Because I need to leave `"warningsAsErrors": true`, and thus couldn't have an unused var, I did this to the `dummy`:
```c#
AssemblyLoadContext dummy = AssemblyLoadContext.Default;
```
Hope that makes sense. If there is a different/better way, please let me know.

**Comment by ljw1004** [comment]
@GuardRex - note that the updated solution [here](https://github.com/dotnet/corefx/issues/10012#issuecomment-232436326) doesn't need the dummy variable at all.

**Comment by rubberduck203** [comment]
For anyone stumbling across this, just handle the `Console.CancelKeyPress` event per [this thread](https://github.com/aspnet/Hosting/issues/870#issuecomment-257435212).

```csharp
Console.CancelKeyPress += (sender, e) => Console.WriteLine("Exiting");
```

I don't know if it handles `kill`, but it's likely you just want a clean shutdown if the user presses `ctrl+c`.

**Comment by kierenj** [comment]
I read somewhere that was the way to go again in .NET Core now, but I can't find the source any more.

Do we still want to use `AssemblyLoadContext`?

Any way to check this out or send a "nice" kill in Windows?  Been trying to check I have some solid code but can't get anything to pick up on a `taskkill /pid xxx`...

**Comment by nagytech** [comment]
@kierenj Starting with with .NET Core 2.0, you can use the `AppDomain.CurrentDomain.ProcessExit` hook.

https://apisof.net/catalog/System.AppDomain
