### ISSUE TITLE
AcceptAsync(SocketAsyncEventArgs e) return true and never call the method of SocketAsyncEventArgs.Completed

### ISSUE THREAD

**Issue by houlin** [dotnet/corefx#10010]
Im currently developing an window app. I would like to use AcceptAsync method. At the moment there appears to be a lot of messiness in the System.Net.Sockets . AcceptAsync(SocketAsyncEventArgs e) always return true and the method of Accept_Completed never be called.If there any come up with this problem and got the solution to it?

`private void ProcessAccept(SocketAsyncEventArgs e)`
`{`

    e.Completed +=new EventHandler<SocketAsyncEventArgs>(Accept_Completed);
    e.AcceptSocket = null;
    
    //acceptEvtArgs.AcceptSocket = null;
    bool waitFlag = listeningSocket.AcceptAsync(e);
    if (!waitFlag)
    { // operation completed synchronously
       Accept_Completed(null, e);
    }
`}`

**Comment by CIPop** [comment]
Is this the scenario that you are describing? https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/tests/FunctionalTests/AcceptAsync.cs

This test is passing on our CI and dev boxes.

Please add more details:
1. What OS, OS Version and S.N.Sockets version are you using?
2. What is the network configuration? 
3. What is the repro rate (100%, only under stress, etc)
4. Is this a CoreFX or Universal app?
5. Do you have traces for S.N.Sockets and System.Net? See: https://github.com/dotnet/corefx/blob/master/Documentation/debugging/windows-instructions.md

**Comment by houlin** [comment]
RE:
OS is windows10 ,OS Version  is 10.0.10586.
This is  a Universal app.
When I run the test, the line of “client.ConnectAsync(argsClient)” will throw an Exception：

```
		AddressFamily	InterNetwork	System.Net.Sockets.AddressFamily
		Available	0	int
		Blocking	true	bool
		Connected	false	bool
		DontFragment	true	bool
+		DualMode	'var2.DualMode' threw an exception of type 'System.NotSupportedException'	bool {System.NotSupportedException}
+		EnableBroadcast	'var2.EnableBroadcast' threw an exception of type 'System.Net.Sockets.SocketException'	bool {System.Net.Sockets.SocketException}
		ExclusiveAddressUse	false	bool
		IsBound	false	bool
+		LingerState	{System.Net.Sockets.LingerOption}	System.Net.Sockets.LingerOption
		LocalEndPoint	null	System.Net.EndPoint
+		MulticastLoopback	'var2.MulticastLoopback' threw an exception of type 'System.Net.Sockets.SocketException'	bool {System.Net.Sockets.SocketException}
```

The Error generated from here :

`
using (Socket client = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
{
`

    SocketAsyncEventArgs argsClient = new SocketAsyncEventArgs();
    argsClient.RemoteEndPoint = new IPEndPoint(IPAddress.Loopback, port);
    argsClient.Completed += OnConnectCompleted;
    argsClient.UserToken = completedClient;
    _client.ConnectAsync(argsClient);

    _log.WriteLine("IPv4 Client: Connecting.");
    Assert.True(completed.WaitOne(5000), "IPv4: Timed out while waiting for connection");
    var var2 = args.AcceptSocket;
    Assert.Equal<SocketError>(SocketError.Success, args.SocketError);
    Assert.NotNull(args.AcceptSocket);
    Assert.True(args.AcceptSocket.Connected, "IPv4 Accept Socket was not connected");
    Assert.NotNull(args.AcceptSocket.RemoteEndPoint);
    Assert.Equal(client.LocalEndPoint, args.AcceptSocket.RemoteEndPoint);
`}`

**Comment by CIPop** [comment]
@houlin I'm not exactly sure if I understood the problem.

I've tried a basic scenario in a UWP application. https://gist.github.com/CIPop/afe55e9fac60376d7ae734b7d590614b
To try this out, start with a C# Universal application and add the contents of the .partial files in the Gist.
