### ISSUE TITLE
Possible unnecessary Padding Oracle problems with UniversalCryptoDecryptor.cs

### ISSUE THREAD

**Issue by JonathanHenson** [dotnet/corefx#10021]
I noticed a manual padding implementation in here while I was helping someone debug some code. I'm no crypto expert, but I noticed variable timing on the padding verification, and possibly on the BlockCopy (depending on implementation) is it just a memcpy? Does this open you up to a padding oracle attack?

You mention that the platform (I'm assuming BCrypt, doesn't support padding in CBC mode for you), but it does. All you have to do is turn padding on on your last call to BCryptEncrypt and BCryptDecrypt. I recently had to deal with this and I've linked it. 

https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/utils/crypto/bcrypt/CryptoImpl.cpp#L654

**Comment by bartonjs** [comment]
Thank you, we're taking a look.

**Comment by blowdart** [comment]
Whilst we agree there’s a timing issue once you get to the decryption algorithms we’d expect you to have already validated the data and made a decision on whether it is trustworthy or not through standard practices such as an MAC covering both the IV and the encrypted data, or, when .NET Core support arrives, using an authenticated chaining mode.
 
As you’re aware this is a notoriously difficult problem to solve, and lots of research has taken place in this space over the years, generally pointing to MACs as the most common solution. For example [Reconsidering Generic Composition](https://rd.springer.com/chapter/10.1007/978-3-642-55220-5_15) by Chanathip Namprempre, Phillip Rogaway & Thomas Shrimpton discusses the problem space in great detail.
 
We are examining a more opinionated API to encryption which will do everything right for the majority of users who simply don’t realise how painful and full of traps cryptography is.
 
Thanks for bringing this to our attention.
