### ISSUE TITLE
EventSource for .Net Native does not consider properties for derived types of EventData

### ISSUE THREAD

**Issue by davmason** [dotnet/corefx#10028]
In StubEnvironment.cs, type.GetProperties is defined as type.GetTypeInfo().DeclaredProperties, which doesn't return the properties of any derived types. It should be type.GetRuntimeProperties which does.

**Comment by davmason** [comment]
Consider this program:

`    [EventData]
    public class BaseEventData
    {
        public int A { get; set; }
    }

    [EventData]
    public class DerivedEventData : BaseEventData
    {
        public string B { get; set; }
        public int C { get; set; }
    }

    public class LoudListener : EventListener

    {

        [ThreadStatic]
        public static EventWrittenEventArgs LastEvent;

        protected override void OnEventSourceCreated(EventSource eventSource)
        {
            base.OnEventSourceCreated(eventSource);
            EnableEvents(eventSource, EventLevel.LogAlways, (EventKeywords)0xffffffff);
        }

        protected override void OnEventWritten(EventWrittenEventArgs eventData)
        {
            LastEvent = eventData;

            Console.WriteLine(String.Format("Event {0} ", eventData.EventId));
            Console.WriteLine("Name = {0}", eventData.EventName);
            Console.WriteLine("MSG = {0}", eventData.Message);
            Console.WriteLine("Payload length = {0}", eventData.Payload?.Count);
            Console.WriteLine(String.Format(" ({0}).", eventData.Payload != null ? string.Join(", ", eventData.Payload) : ""));
        }

    }

    public class Program
    {
        public static void Main(string[] args)
        {
            using (LoudListener ll = new LoudListener())
            {
                using (EventSource es = new EventSource("Sample"))
                {
                    es.Write("sampleEvent", new DerivedEventData { A = 1, B = "a string", C = 10 });
                }
            }
        }
    }`

On desktop and .net core, it correctly prints the property A of the derived type, but in .Net Native it does not.

**Comment by karelz** [comment]
It should be fixed in the code now, we just need to catch the next ProjectN wave to ship it out (2.1)
