### ISSUE TITLE
Dns.GetHostEntryAsync() throws SocketException if called before any other Socket APIs

### ISSUE THREAD

**Issue by mikeharder** [dotnet/corefx#10024]
# Repro Steps
* dotnet new
* Replace the contents of `Main()` with the following:
```csharp
Console.WriteLine(System.Net.Dns.GetHostEntryAsync("127.0.0.1").Result.AddressList.Length);
```
* dotnet run
* App throws following exception:
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Either the application has not called WSAStartup,
or WSAStartup failed) ---> System.Net.Sockets.SocketException: Either the application has not called WSAStartup,
 or WSAStartup failed
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostEntryAsync>b__16_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction,
Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at ConsoleApplication.Program.Main(String[] args)
```
* Add the following before the call to `Dns.GetHostEntryAsync()`:
```csharp
new System.Net.Sockets.Socket(System.Net.Sockets.SocketType.Stream, System.Net.Sockets.ProtocolType.Tcp);
```
* App works correctly.

CC: @stephentoub

**Comment by stephentoub** [comment]
cc: @davidsh, @cipop

**Comment by CIPop** [comment]
Thanks @mikeharder for reporting this and @stephentoub for routing.

I'm able to repro. Looks like we've missed this test case as well as code path during the PAL split. Even if added, the test needs to run first to detect the issue.

I'm working on a fix and trying to enhance the tests to catch these issues in the future.

For a simpler workaround try calling `Dns.GetHostName()` before performing a reverse-lookup. Forward-lookup should properly initialize Winsock.

**Comment by stephentoub** [comment]
> Even if added, the test needs to run first to detect the issue
 
I suggest doing it out-of-process with the RemoteInvoke utility we have in the repo.

**Comment by CIPop** [comment]
>> Even if added, the test needs to run first to detect the issue

> I suggest doing it out-of-process with the RemoteInvoke utility we have in the repo.

Thanks @stephentoub. Would `RemoteInvoke` work in NetNative/UWP? I was thinking of creating a UnitTest.

**Comment by CIPop** [comment]
> Not sure. Probably not at the moment.

Thanks, I'll stick with a UnitTest for now to ensure that all `public` APIs call into the `EnsureSocketsAreInitialized`. I'll also try to add more tests to improve code coverage to the contract.
