### ISSUE TITLE
SqlConnection's BeginTransaction is slow in .net core 1.0 (up to 250ms)

### ISSUE THREAD

**Issue by pamanes** [dotnet/corefx#10061]
This code is very slow compared to the full .Net Framework (under 1ms), is this expected behavior?
_con is SqlConnection and _con_trans is SqlTransaction

```
try
{
    _con.Open();
    _con_trans = _con.BeginTransaction(IsolationLevel.ReadCommitted);
}
catch
{
    _con_trans = null;
    _con.Close();
    throw;
}
```

**Comment by joshfree** [comment]
@pamanes can you provide more information on the repro environment?  Which OS? Which DB and version?  Thanks

**Comment by saurabh500** [comment]
cc @tvrprasad @corivera

**Comment by pamanes** [comment]
This is on Windows 10, SQL Server 2008 R2

Overall net core 1.0 seems very slow compared to the full .NET Framework (4.5)

**Comment by ViktorHofer** [comment]
@saurabh500 Is this still an issue or do you think we can close that now with the netcoreapp20 codebase?

**Comment by saurabh500** [comment]
I looked at the issue and for 10 connections and a transaction open on each connection, I dont see any latencies as high as 250 ms. 

```
for(int i = 0 ; i < 10; i++ )
            {
                try
                {
                    SqlConnection conn = new SqlConnection(builder.ConnectionString);
                    conn.Open();
                    var init = Stopwatch.GetTimestamp();
                    var transaction = conn.BeginTransaction(IsolationLevel.ReadCommitted);
                    Console.WriteLine((Stopwatch.GetTimestamp() - init) + " ticks");
                    conn.Close();
                }
                catch(Exception e)
                {
                    Console.WriteLine("Error message: " + e.Message);
                }
            }

```
Results of `dotnet run ` 

```
21674 ticks
458 ticks
432 ticks
459 ticks
575 ticks
641 ticks
433 ticks
453 ticks
500 ticks
589 ticks

```

This is a high resolution stopwatch, and I see that the max time is taken for the first transaction which about 20000 ticks, i.e. 2 ms.

I cannot reproduce this performance problem. Closing the issue.
