### ISSUE TITLE
Add members that were added in Core to types of classic assemblies to the Compat surface area.

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#10073]
There are at least a couple of Compat surface areas that I have to update since we added some members to old types in Core.

**Comment by danmosemsft** [comment]
@joperezr Can you clarify what this means?

**Comment by joperezr** [comment]
Talked offline. Basically this Compat surface area is meant to be classic assemblies + .NetCore, today we only have the classic assemblies part.

**Comment by danmosemsft** [comment]
@weshaggard Wes if I understand right there is no particular urgency to this.

**Comment by weshaggard** [comment]
@danmosemsft correct this can wait until we actually get all the APIs added.

**Comment by danmosemsft** [comment]
@weshaggard Do these compat assemblies serve any purpose any more? We should build our mscorlib etc shims from the standard repo, not corefx.

**Comment by weshaggard** [comment]
We will still need to build them in corefx. There will be two sets of compat facades. One that will type-forwards to netstandard.dll and those can be in the standard repo, the other will be type-forwards to .NET Core refs and those will still need to be in corefx repo.

**Comment by danmosemsft** [comment]
These need to be rebuilt because they were based off MonoAndroid and should be probably based off Desktop. EXample TargetInvocationException derives from Exception in Mono but ApplicationException in Desktop. Assumption is that Desktop is the authority and we can get Mono changed if we discover some breaking difference. In fact as part of updating them we should diff them to see what differences there are.

**Comment by joperezr** [comment]
Will do, I'll go re-build these once we are done defining what will be exposed in netstandard2.0

**Comment by weshaggard** [comment]
@joperezr please chat with me before you do this work item as we need to make it consistent with what I'm using in netstandard.

**Comment by weshaggard** [comment]
This is taken care of by https://github.com/dotnet/corefx/pull/13565
