### ISSUE TITLE
Offset, Count and Primitive parsing.

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/corefx#10087]
The concept of `offset` and `count` is obviated when working with `Array` types however a majority of the core classes do not offer a suitable way to use only portions of an array.

This results is having to utilize various techniques just to do something trivial e.g. parse a boolean value from a string.

"This is a string and the bool value is false which is the opposite of true."

Currently with most primitive types there exists a `Parse` method which takes a `string` as a parameter.

`bool.Parse`, `bool.TryParse` etc.

These methods are great but I would really like them to be able to parse into a string given an offset and length.

i.e.

`bool.Parse(someString, startIndex, count)`

I believe this would help many parsing routines which currently either have to rely on unsafe code or otherwise to perform the same logic...

`BigInteger` also suffers from this deficiency among quite a few other classes.

**Comment by stephentoub** [comment]
The plan is to address this with `Span<T>` and `ReadOnlySpan<T>`:
https://github.com/dotnet/corefx/issues/13892
I'm going to close this issue and let that one track it.  Definitely something we want to do.
