### ISSUE TITLE
Faster and/or vectorized sin/cos

### ISSUE THREAD

**Issue by MikePopoloski** [dotnet/corefx#1008]
In certain types of applications, the extra precision and correctness afforded by Math.Sin() and Math.Cos() are not worth the performance penalty they impose. These applications are often already using primarily single precision floats for computations, and thus have to round trip through double to make use of these methods. I propose adding a FastMath or Mathf or similar set of methods for lower precision high performance implementations of these methods.

If it were not for the existence of System.Numerics.Vectors, I would advocate that these simply be an external library separate from the core framework, but since the vector math library ships Quaternion and Matrix support, I would vastly prefer that these types make use of the faster math operations for things like calculating rotations. My reasoning is that these types exist in the first place for people concerned with performance, and as it stands they're simply too slow compared to the alternatives for them to see much use.

For a practical anecdote, I recently wrote an OpenGL draw call stress test to determine CPU overhead and how many draw calls I can push from my .NET app. By far the biggest consumer of frame time was Sin and Cos inside the quaternion rotation method used to rotate the cubes I was rendering. Using a fully managed implementation of SinCos based on the venerable CEPHES library cut that time roughly in half. This could be further extended by vectorizing with SIMD, provided that the Vector types support a few more intrinsics such as shuffle.

I wouldn't mind doing this work if people think it would be useful. My main concern is that shipping System.Numerics.Vectors (quaternions and matrices) without these faster math routines will forever doom them to obscurity, since switching to reduced precision operations in the future would be a breaking change.

**Comment by CarolEidt** [comment]
I think these are great suggestions - both the idea of having lower-precision Math operators as well as utilizing them for the Quaternion and Matrix types, which in any case don't use double precision.  What would you propose as the accuracy expectation for such libraries?  Would you expect that their results be accurate to within some .5 or some small number of ULPs for Single (vs. Double)?  If you think that would meet performance expectations, then giving them a name that would convey that, e.g. SingleMath or Math32, might be a good approach.

Regarding shuffle, that is certainly something that we've considered, especially for the fixed vector types (e.g. Vector4) for which the API design is less challenging.  I worked on the design of the vector types, but my expertise and contributions are primarily in the JIT.  Once there is an API specification in place the JIT support for accelerating it as an intrinsic would be fairly straightforward.

**Comment by MikePopoloski** [comment]
My plan as far as accuracy goes is to run every possible float value through the function and record the difference against a (float)Math.Sin() call, both peak and rms. The algorithm I'm using is borrowed from CEPHES and they make it clear that accuracy is very good up until input angles of 2^13, where you get partial accuracy loss. Above 2^24 the result is essentially meaningless and they assert. This is probably fine though, since rotations of huge angles are already a bad idea and the existing Math.Sin and Math.Cos return pretty terrible results for them anyway, so I doubt anyone is relying on that.

I'll take a crack at rewriting the algorithm with SIMD to get an idea of how I'd like to use shuffle (and potentially any other intrinsics that are missing). That should help give a better idea of what the API could look like. If I can get the CoreCLR and CoreFx library building and working together I might even attempt to add the necessary support to the JIT. I did some SSE work for Mono back in the day so it should be fun to compare the codebases.

**Comment by CarolEidt** [comment]
That sounds great.  Let me know if you have any questions regarding the JIT support for the intrinsics.  As I say, I think it would be fairly straightforward - especially if you've got some experience in the area.

**Comment by terrajobst** [comment]
It seems this one needs a concrete proposal. @MikePopoloski, do you want to take a stab?

**Comment by mellinoe** [comment]
@MikePopoloski This is a pretty old issue, but do you still have any thoughts about how you would envision this being designed and exposed, from an API perspective?

**Comment by mellinoe** [comment]
If we can get a concrete proposal for this, I still think it's worth pursuing. I'm going to close it now. Please re-open this if you'd like to continue discussion of a concrete proposal.
