### ISSUE TITLE
Enable coverage for test code (required for Unit and PAL testing)

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#10090]
Currently `/p:Coverage=true` excludes Test code. This leaves production code within all Unit and PAL tests without code coverage.

A workaround is to to manually write a script to remove the `-filter:" -[*.Tests]*"` portion from OpenCover:

``` batchfile
call S:\c2\packages/OpenCover\4.6.519\tools\OpenCover.Console.exe -oldStyle -filter:"+[*]* -[xunit.*]*" -excludebyfile:"*\Common\src\System\SR.*" -nodefaultfilters -excludebyattribute:*.ExcludeFromCodeCoverage* -skipautoprops -hideskipped:All -threshold:1 -returntargetcode -register:user -target:CoreRun.exe -output:S:\c2\bin/tests/coverage\System.Net.NameResolution.Pal.Tests.coverage.xml -targetargs:"xunit.console.netcore.exe System.Net.NameResolution.Pal.Tests.dll  -xml testResults.xml -notrait Benchmark=true  -notrait category=failing -notrait category=nonwindowstests "

S:\c2\packages/ReportGenerator\2.4.3\tools\ReportGenerator.exe -targetdir:S:\c2\bin/tests/coverage\ -reporttypes:Html;Badges -reports:S:\c2\bin/tests/coverage\System.Net.NameResolution.Pal.Tests.coverage.xml
```

It would be great if we could have /p:CoverageAll to remove the Test code filter which in these cases is actually the production code directly referenced by the test project.

**Comment by weshaggard** [comment]
@stephentoub @danmosemsft is it this still an issue with our coverage builds?

**Comment by danmosemsft** [comment]
It currently has ` -filter:"+[System.Text.RegularExpressions]*" ` (eg for System.Text.RegularExpressions tests) ie it only includes coverage of the assembly under test not any product code compiled into the unit tests themselves.

If you add ` /p:Coverage=true` then you get just `-filter:"[*]*"` which gives lots of errors about missing sources for xunit itself and coverage for xunit. For some reason it's not giving coverage for the tests, but perhaps I'm missing a PDB.

Good enough.
