### ISSUE TITLE
Serialization Support 

### ISSUE THREAD

**Issue by narenkv** [dotnet/corefx#10116]
Does the Core 1.0 currently supports System.Runtime.Serialization like Serializable,SerializationFormatter attribute etc. 

We are in the process of upgrading 4.5.x to Core 1.0.

**Comment by stephentoub** [comment]
Not in 1.0.  BinaryFormatter is being added here: https://github.com/dotnet/corefx/pull/10088

**Comment by narenkv** [comment]
What is the process to pull the code and use in the projects please

**Comment by narenkv** [comment]
![img_2124](https://cloud.githubusercontent.com/assets/17287435/16945603/4fd2bf48-4dc3-11e6-81a6-b0d266bf9876.JPG)

any idea on this issue

**Comment by shmao** [comment]
Hi @narenkv , I couldn't read the message on the screenshot clearly. Can you please paste the message here?
