### ISSUE TITLE
Do tests exist at all for Comparer/EqualityComparer?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#10110]
#9379 would seem to imply we already have test coverage for those classes, but at the moment I can't see any such tests within the [System.Collections/tests](https://github.com/dotnet/corefx/tree/master/src/System.Collections/tests) dir...

cc @hughbe @GSPP @joshfree

**Comment by ianhays** [comment]
Looks like we don't. Closing this as a dup of #9379 / resolved partially via https://github.com/dotnet/corefx/pull/11074
