### ISSUE TITLE
The results of "==" and "Equals" should be consistent on TimeZoneInfo class

### ISSUE THREAD

**Issue by RickyLin** [dotnet/corefx#10114]
**Code:**

```csharp
TimeZoneInfo t1 = TimeZoneInfo.Local; // my "Local" is "China Standard Time"
TimeZoneInfo t2 = TimeZoneInfo.FindSystemTimeZoneById("China Standard Time");
Console.WriteLine("t1 == t2 ? " +  (t1 == t2)); 
Console.WriteLine("t1.Equals(t2) ? " + t1.Equals(t2));
```

**Expected**
```
t1 == t2 ? True
t1.Equals(t2) ? True
```

**Fact**
```
t1 == t2 ? False // <-- it should be True
t1.Equals(t2) ? True
```

I filed [an issue](https://github.com/dotnet/coreclr/issues/6292) about this in coreclr repo first. Then I was suggested to file the issue here.

I know the "==" and "Equals" are two different things, but I think most of the time, in a class, they should have the same results. However the "==" and "Equals" on `TimeZoneInfo` have different results. In mental mode, I think the TimeZoneInfo should be compared with its Id, just like what the overridden `Equals` method does. **The "==" should also be overloaded to have the same result as `Equals`.**

**Comment by tarekgh** [comment]
@RickyLin there are 2 design schools for defining the equality on the reference types. one school is recommending when overriding Equals or == operator, should override the other. i.e. Equals and == should be consistent. the other school prefer to have == perform object reference equality. I am inclining to the first school to have Equals and == consistent but unfortunately for TimeZoneInfo class which is released several years ago  didn't do that and changing that now will be a breaking change. I expect many apps already took dependency on such behavior which will make it difficult to change that now.

**Comment by tarekgh** [comment]
@RickyLin I am closing this issue but feel free to reply back or re-open if you have more feedback. Thanks,
