### ISSUE TITLE
Two vector test failures for Release builds using 64-bit CoreCLR

### ISSUE THREAD

**Issue by jhendrixMSFT** [dotnet/corefx#1011]
The following tests fail for release builds running with a 64-bit CoreCLR.

Vector2ReflectTest
Vector2ReflectTest1

Note that the tests pass for debug builds and debug or release under 32-bit CoreCLR.

**Comment by mellinoe** [comment]
I haven't seen any issues with these any longer,even running under 64-bit CLR. This must have been fixed at some point.
