### ISSUE TITLE
Add new Lazy<T>(T value) ctor to System.Runtime contract and add tests

### ISSUE THREAD

**Issue by justinvp** [dotnet/corefx#10127]
Now that the implementation of #2578 has been merged for CoreCLR (https://github.com/dotnet/coreclr/pull/6304) and CoreRT (https://github.com/dotnet/corert/pull/1538), the new API needs to be exposed in the [`System.Runtime`](https://github.com/dotnet/corefx/blob/4fccde2c42f7670ebd098513c09b30772f833e84/src/System.Runtime/ref/System.Runtime.cs#L1202) contract (and versioned as appropriate) and tests added.

**Comment by justinvp** [comment]
Do we need a separate issue tracking adding the new API to the full framework? Or would that be tracked internally by Microsoft? What about Mono/Xamarin?

**Comment by weshaggard** [comment]
@justinvp @terrajobst @danmosemsft @jkotas I just created a new api-needs-exposed label to mark corefx issues for new APIs that are implemented but not yet exposed.
