### ISSUE TITLE
Using .Net (C++/CLI) legacy code in Net Core

### ISSUE THREAD

**Issue by jitugeo** [dotnet/corefx#10124]
I have a problem of using native/CLR (C++/Cli dll) in netcore. we have a very huge code base for C++ functionality, so for using it in .Net we have created C++/Cli manged wrapper as dlls and it worked fine. Now we want to use them in Netcore MVC.  By putting the legacy dlls in nuget package I'm able to use them in NetCore framework targeting Net461. 

Now I have two problems 

1. As per document I can target two framework at same time by using import. for instance 
"frameworks": {
    "netstandard1.4": {
      "imports": [
        "net461"
      ],
But it get an compile time error "Can not find runtime target for framework '.NETStandard,Version=v1.4' compatible with one of the target runtimes: 'win7-x64'. Even after defining target platform 'x64' in project.json. 

2. if first point solution is not possible then how can i use my >net framwork 4.6 dll in netstandard1.x/netcoreapp1.0 ?

thank you,

**Comment by jasonwilliams200OK** [comment]
@jitugeo,
I think you need to add `"runtimes"` section or `"Microsoft.NETCore.Platforms": "1.0.1"` in your dependencies to quiet the compiler. :smile:
 But ... the whole point of .NET Core is to have your code cross-platform ready. By having `"imports": "net461"` (aka impersonate netstnadard1.4 as net461 in this project and all its dependencies..), it supremely defeats the purpose of net-core as net461 is not cross-platform. Usage of `"imports"` is a bad idea to begin with (doesn't matter what VS template is presenting, it's bad and may give you false sense of cross-paltform'ness etc. it's okay to use imports for certain portable profiles as some are really compatible with net-core but avoid wherever possible for separation of concerns). In short, C++/CLI is not supported in .NET Core as is.
IMO, you must rethink your code base and build pure native C/C++ library with C-API which builds cross-platform (Windows and Unix), then P/Invoke to get your manage code interact with foreign-functions (FFI). If there is alot of work involved to port code to Unix, you can create a shim/placeholder implementation for Unix and throw PlatformNotSupportedException until the time you achieve the binary compatibility with Unix. The same approach taken by CoreFX team: https://github.com/dotnet/corefx/tree/master/src/Native. This will unblock you and give your old code base a RAD touch! (and as a bonus, you could even switch the front-facing managed runtimes i.e. use ruby-ffi or v8/node.js rt to talk with your new C-API etc.) :wink:

**Comment by ericstj** [comment]
Good advice here by @jasonwilliams200OK.  

Error 1. is caused by some project trying to get a win7-x64 target section out of the lock file: if you wanted to make that go away you could either change your project configuration or add the 'win7-x64` section to `runtimes` section in your project.json.

Using imports is the hack to try to use net46 assets in a netcore application, but as @jasonwilliams200OK mentioned there are lots of problems with doing this.
