### ISSUE TITLE
System.Collections.NonGeneric failed to bind

### ISSUE THREAD

**Issue by WiliamGP** [dotnet/corefx#10133]
I'm developing an application UWP for Windows 10 Mobile, everything works fine in debug mode, but when I generate the application packages in release mode, the resources to globalization do not work and the visual studio reports the following warning attached below. I'm using the Microsoft.NETCore.UniversalWindowsPlataform in version 5.2.2. Is there any way to solve this problem? Regards

> ILTransform_0027: Assembly name 'System.Collections.NonGeneric' failed to bind.

**Comment by jkotas** [comment]
cc @MattWhilden

**Comment by MattWhilden** [comment]
Certainly something we'd be interested in taking a look into. Thanks for reaching out!

On my machine with VS Update 3, NETCore.UWP 5.2.2, System.Collections.NonGeneric 1.2 everything seems to build correctly. Can you send me a repro file using the instructions here? https://github.com/dotnet/core/blob/master/Documentation/ilcRepro.md.

**Comment by karelz** [comment]
It should work now, please feel free to reopen if it is not the case, thanks!
