### ISSUE TITLE
Accept HttpContent on any request method

### ISSUE THREAD

**Issue by MV10** [dotnet/corefx#10154]
Overloads are needed to support HttpContent on methods like GetAsync. The HTTP specification does not prohibit body-level content on any of the method types. They may not be commonly used but I am aware of REST services that require complex body content in GET requests (in one case, it describes a variety of search parameters).

**Comment by davidsh** [comment]
cc: @CIPop @stephentoub @himadrisarkar 

>The HTTP specification does not prohibit body-level content on any of the method types. 

This is not entirely true.  Some methods like TRACE do not allow request body content.

>Overloads are needed to support HttpContent on methods like GetAsync.

We already have a generic overload, `SendAsync` which can be used to send HTTP requests. And the `HttpRequestMessage` passed in can have a `.Content` object as well.  The overloads like `GetAsync` are convenience methods for the most used operations.

**Comment by MV10** [comment]
Fair enough.
