### ISSUE TITLE
On '@' and reserved words

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/corefx#10152]
Attempting to compile the following code:

```
static void @_(object someName)
        {
            object @someName = null;

            return;
        }
```

results in a compilation error:

> Error 79  A local variable named 'someName' cannot be declared in this scope because it would give a different meaning to 'someName', which is already used in a 'parent or current' scope to denote something else.

Additionally it seems that the `@` character is used as an `Escape` in some regard in the parser logic and thus it's appearance causes the character which follows to lose it's meaning as can be seen in the following example:

```
 static void @(object someName)
        {
            object @someName = null;

            return;
        }
```

Thanks for your time and consideration.

**Comment by stephentoub** [comment]
This issue was moved to dotnet/csharplang#446
