### ISSUE TITLE
local type alias

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/corefx#10150]
Currently class declarations do not allow nested type aliasing e.g.

`using MyTuple = System.Tuple<int, int>;` even within a namespace declaration...

This declaration must normally be at the top of a file and precede all other using statements such as `extern`.

I propose that this restriction be lessened such that to allow one to use such aliases within their definitions to avoid redundant typing.

The only way this can be achieved now is to separate each class into it's own file and definitions of the class which fulfill the rule of the compiler by using `partial` or by declaring their own type which represents the type layout desired [thus reducing the use of a perfectly good structure such as `Tuple` simply due to the anonymity associated with such structures.].

Thank you for your time and consideration.

**Comment by stephentoub** [comment]
This issue was moved to dotnet/csharplang#445
