### ISSUE TITLE
How to set .NET Core in #if statement for compilation

### ISSUE THREAD

**Issue by SerhiiS-in6k** [dotnet/corefx#10169]
Hi. I create multy framework project. I use something like this : 
```
      #if NET40
        Console.WriteLine("hello from net 4");
      #endif
```
But I cant find wildcard for .NET Core. I tried : 
```
       #if NETCOREAPP1.0
         Console.WriteLine("hello from net Core");
       #endif
```
but it is not valid statement.
Thanks.

**Comment by svick** [comment]
What you need is `#if NETCOREAPP1_0`. See [*How to Multitarget*](https://github.com/dotnet/core-docs/blob/master/docs/core/tutorials/libraries.md#how-to-multitarget) in the documentation (it does not mention `NETCOREAPP1_0` explicitly, but it shows the pattern).

**Comment by mellinoe** [comment]
Keep in mind you can also define your own set of compilation constants to be whatever you'd like for your various configurations. But like @svick's link shows, we do set some common/obvious ones for different target frameworks.

**Comment by weshaggard** [comment]
Sounds like this question is answered so closing. @SerhiiS-in6k feel free to ask any follow-up questions.
