### ISSUE TITLE
Handling System.Web to Core [best practices]

### ISSUE THREAD

**Issue by narenkv** [dotnet/corefx#10166]
Hello all,

Is there any best practices or steps or senarios which would help people to migrate from .NET 4.x.y versions. 

Responding this will help many people in the world :-)  

/Naren

**Comment by lextm** [comment]
Have you gone through these?

https://docs.asp.net/en/latest/migration/index.html

If not, you should. Issues or questions on those materials can be submitted to

https://github.com/aspnet/Docs/issues

**Comment by narenkv** [comment]
Hello Lextm

Yes, But it helps to one extent. however the alternatives and not clearly articulated. Example System.Web references how to handle is not given. May be a sample conversion project with bare minimal code is shared will be of great help

Also heading mentions the documentation is limited to .0.0-rc2 versions and updates are yet to come.

/Naren

**Comment by joshfree** [comment]
@muratg can you help route this to an asp.net repo?

**Comment by muratg** [comment]
This issue was moved to aspnet/Docs#1752
