### ISSUE TITLE
Update the XElement implementation in System.Xml.XDocument to include XmlSchemaProvider attribute once the packages are refreshed.

### ISSUE THREAD

**Issue by pallavit** [dotnet/corefx#1016]

**Comment by krwq** [comment]
@pallavit, You can add project to project reference now sine ReaderWriter is already on GH

**Comment by pallavit** [comment]
@krwq I will like to wait avoid adding project references to implementation and wait for the package to get updated instead.

**Comment by weshaggard** [comment]
I agree we should avoid the P2P references between the product libraries.

**Comment by pallavit** [comment]
The source has been updated.
