### ISSUE TITLE
Win 10 outerloop machines need to be upgraded to Server 2016 TP5

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#10177]
The current image we are using for the outer loop runs has expired and so the machines will reboot often.  We should move to TP5 (the latest Windows Server 2016 release) and also cut the Win10 machines over to the auto infrastructure stuff instead of having fixed machines.

**Comment by Priya91** [comment]
@ellismg Is this complete or is ther work to do ?

**Comment by ellismg** [comment]
@Priya91 Still work to do (I've been unable to make any further changes between now and when I wrote my comment last month).

**Comment by Priya91** [comment]
Fixed by @mmitche

**Comment by mmitche** [comment]
Thanks, I was looking for this work item.
