### ISSUE TITLE
Question: Multi-Target for NetStandard 2.0 and .NET 4.5 ?

### ISSUE THREAD

**Issue by MichaelKetting** [dotnet/corefx#10172]
Hello!

A couple of weeks ago, there was an announcement that most of the BCL will get ported to .NET Core, which is plain awesome. E.g. I should then be able to enable most of my extensive framework library (> 100 projects) for .NET Core. 

Now, for the question: These features will be delivered when targeting NetStandard 2.0, but I will still have a requirement to support .NET 4.5 in several of my libraries (granted, just 10-15 libraries, but still). Will it be possible to target .NET 4.5 and NetStandard 2.0 with the same build artifact, i.e. without needing to build twice? Before NetStandard, I could do this by adding multiple platform identifiers in my nuget path.

Best regards, Michael

**Comment by svick** [comment]
Are you talking about path like `portable-net45+wp80+win8+wpa81`? The whole point of .Net Standard is to avoid that mess, so, no, I don't think you will be able to use `portable-net45+netstandard2.0`.

**Comment by MichaelKetting** [comment]
Yeah, exactly that. Okay, good to know that it won't work as a single identifier. But will it be possible to use the same assembly with "net45" and "netstandard2.0" when it is compiled against .Net Standard 2.0? I guess the biggest problem would be to ensure that no .NET 4.6 API is being used...

**Comment by jasonwilliams200OK** [comment]
@MichaelKetting, you can have multi-targeting project.json like this: https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/project.json. That will produce the assemblies separately for each TxM. Starting from NetStandard, smaller version is compatible with higher version (but not vice versa). So `netstandard1.3` compatible assembly would work with `netstandard1.4` etc.. But that wouldn't work with net45, net40 etc. However, when you run `dotnet build` without specifying `-f` argument (to specify which framework to build for), it builds for all TxMs enlisted in the project.json manifest. Then `dotnet pack` will package all assemblies in a NuGet package. The consumer of the package will get the correct assembly based on their selected framework (which is the package manager's job: NuGet).

**Comment by MichaelKetting** [comment]
@jasonwilliams200OK Thanks for the info. At the moment, I'm in a wait-and-see position for how the csproj/msbuild integration is going to look like as I can't use the project.json / dotnet build stuff from within my build infrastructure without re-engineering basically my entire build system and finding solutions for the features that have been removed since nuspec.

I was hoping to avoid the dual-assembly approach since this this will have several implications in regards to complexity and testing and common usage scenarios, but I'm aware that I might have to go this route. 

What it basically comes down to is how to support the new platform while still maintaining the widest possible compatibility with the established and long-term-supported .NET 4.5 while not introducing any new complexity into your project and build system.

**Comment by Petermarcu** [comment]
The current plan is for .NET 4.6.1 to be the version of the .NET Framework that will map to .NET Standard 2.0. The are previous versions of the .NET Standard with less API's that will support 4.5. The reason for the choice of 4.6.1 is that there are many API's added since .NET 4.5 are already in the previous versions of the .NET Standard and we cannot remove them from a higher version of the .NET Standard. We want to make sure a library written for .NET Standard 1.3 for example to continue to work on .NET Standard 2.0.

Can you share what is driving you to continue to have to support 4.5?

**Comment by MichaelKetting** [comment]
@Petermarcu Sure, the driving reason is backwards compatibility while only needing to create a single assembly that can service .NET 4.5 (4.5.2) and everything that comes after. Right now, I'm doing multi-platform support for re-linq to support .NET 3.5, .NET 4.0, .NET 4.5, and .NET Standard so I can extrapolate the amount of effort it will require to set up a dual-platform support. I've got a couple other library projects that are hosted on NuGet and I don't want to just cut .NET 4.5 support simply because it makes it more convenient for me to maintain the library. And no, the dual-support effort isn't a deal-breaker for a couple of libraries, it's just work and complexity that I was trying to avoid.

Back when, before .NET Standard 2.0 was announced, I never expected to be able to bring those libraries to .NET Core since I use Type excessively as well as several other APIs of the BCL that are expected to make it to .NET Standard 2.0. And now, I have to decide which route is the better compromise, i.e. support the only the full Framework or open up and do the extra work to support also the .NET Core community, and of course, that's not really a decision at all in the end.

And in addition to my own predicament, there is the broader community aspect: I'm guessing .NET Standard opens up PCL support for lot of projects out there on NuGet. Unfortunately, it will also mean those projects will be moving to .NET 4.6 as a minimum platform requirement. I've run into this myself with an inhouse tool I'm developing that is depending on Microsoft.Cci. Cci switched to .NET Standard 1.6 simply because it was the latest and I had to form the repo and make a .NET 4.5 build because I still need to maintain that compatibility.

Come to think of it, I'm guessing that .NET Standard 2.0 will be a pretty hard cut for the .NET community, dividing the ecosystem into a before and an after. The best possible approach might be to discontinue support for .NET 4.5.2 in favor of the latest .NET 4.6.x in the near future, just like it was done with .NET 4.5.0 and .4.5.1 in favor of a consolidated .NET 4.5.2. Then at least, you could argo the need for an upgrade to your customers by quoting a higher power having intervened.

**Comment by davidfowl** [comment]
It would be a break in compat. There were a few APIs added in .netstandard 1.6 that shouldn't have been put in there. So it's a compromise since the APIs added definitely aren't in wide use. It was either that or make netstandard supper a future .NET Framework version making it useless for a while.

Cross compilation will never go away even with netstandard. You'll sometimes want to support multiple netstandard versions the same way you do with .net framework versions today.

**Comment by MichaelKetting** [comment]
> It would be a break in compat. 
Yep, that's the one.

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/standard #140](https://github.com/dotnet/standard/issues/140) via [**ZenHub**](https://www.zenhub.com/)
