### ISSUE TITLE
Consider adding Disposables

### ISSUE THREAD

**Issue by patricksadowski** [dotnet/corefx#1019]
[Reactive Extensions](https://github.com/Reactive-Extensions/Rx.NET/tree/master/Rx.NET/Source/System.Reactive.Core/Reactive/Disposables) and [System.Threading.Tasks.Dataflow](https://github.com/dotnet/corefx/blob/master/src/System.Threading.Tasks.Dataflow/src/Internal/ActionOnDispose.cs) are using their own internal Disposables. I don't know how many people have written similar APIs too. We also use our own disposables to run actions. This is very helpful for types implementing IObservable<T> and types used within a ```using```-statement.

I think CoreFX is the right place to offer a small common API for disposables. What are your thoughts?

**Comment by MattWhilden** [comment]
Can you expand on this a bit? I'm not familiar with this and there's probably a number of other folks here who would benefit from a high level explanation.

You may also consider creating a speclet for this as outlined here: https://github.com/dotnet/corefx/wiki/API-Review-Process

**Comment by patricksadowski** [comment]
Ok, I'll try. My english is not that good.
My indention was not to create a speclet but rather to collect common use-cases and discuss the value for Disposables in the framework. After that a speclet can be created. The main question is: Is there a need for Disposables so it can be used widely and remove redundant code? My opinion is that disposables are a good addition to the existing general types like generic tuples, generic event handler, ... with the goal to simplify the life of a developer.

Disposables are helpful to hide an Dispose-implementation to a caller. The caller doesn't need to know the concrete data type to dispose. Only the ability to dispose the object is important to the caller.
* Dataflow blocks can be unlinked by disposables. The decoupling mechanism is hidden to the caller.
* An observation of an object can be stopped by a disposable.
* The release logic of temporary/short-living objects can be hidden.

I think that these use-cases are present in many other libraries.

When you use Observables you always need a custom disposable object for unsubscription.
```csharp
class Observable : IObservable<double>
{
    IDisposable IObservable<double>.Subscribe(IObserver<double> observer)
    {
        // Create IDisposable with internal logic for unsubscription.
        return ???;
    }
}
```
Another example:
If you want to simplify try-finally statements you can use a using-statement. (I know a using-statement is 'converted' to an try-finally-statement. But the code is more readable and the usage is easier.)
```csharp
public void Paint(Graphics graphics)
{
    var container = graphics.BeginContainer();
    try
    {
        graphics.TextRenderingHint = TextRenderingHint.SingleBitPerPixelGridFit;
        // paint objects
    }
    finally
    {
        graphics.EndContainer(container);
    }
}
```
simplified to (Note: new extension method)
```csharp
public void Paint(Graphics graphics)
{
    using (graphics.Container())
    {
        graphics.TextRenderingHint = TextRenderingHint.SingleBitPerPixelGridFit;
        // paint objects
    }
}
public static IDisposable Container(this Graphics graphics)
{
    var container = graphics.BeginContainer();
    return ???; // custom disposable for call to EndContainer() needed
}
```
I look forward to other opinions.

**Comment by KrzysztofCwalina** [comment]
I agree that it would be very nice to have a library that helps people who want to implement observable APIs. Disposable is one of these things that could be simplified (as Patrick explains above). Another thing that I often hit when I implement observer/observable interfaces is that you need to store observers in a collection that needs to be concurrent, you needs to loop though it to notify all observers (while it's potentially mutated on a different thread). This could also be made much easier with a helper library. 

Having said that, I am not sure if such library belongs to the core. I have not though about it deeply enough. Patrick, maybe you should prototype it, and then we can decide what to do with it. BTW, if you'd like to use CoreFxLab repo for it, I'd be open to it.

**Comment by patricksadowski** [comment]
I agree that a helper library for observable APIs doesn't belong to corefx.
As the title says you should consider adding default implementations of IDisposable, please. Then my given examples could be simplified (no need for a custom class implementing IDisposable). Even Reactive Extensions and Dataflow would benefit from disposables.

I don't think I'm able to create a prototype for disposables in a reasonable time. The prototype has to meet common requirements and the requirements of Reactive Extensions and Dataflow. I lack information to accomplish this. I've updated the examples of my second comment using the disposables of DataFlow.

**Comment by KrzysztofCwalina** [comment]
Closing as this one not align with out priorities and there is no one to keep the ball rolling
