### ISSUE TITLE
Implement System.Threading.AsyncFlowControl

### ISSUE THREAD

**Issue by ioanacrant** [dotnet/corefx#10194]
From #10049

These methods rely on System.Threading.AsyncFlowControl and they should be added to the CAS stubs

```
M:System.Security.SecurityContext.SuppressFlow
M:System.Security.SecurityContext.SuppressFlowWindowsIdentity
```

@stephentoub @danmosemsft @ellismg @bartonjs

**Comment by danmosemsft** [comment]
Removing .NET Standard label as CAS will be an extension to it. We can do this later if we want to.

**Comment by danmosemsft** [comment]
In fact, I'm going to close the issue: we can treat CAS all together later.
