### ISSUE TITLE
Cleanup post Reflection Api Restoration debt.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#10202]
Just a reminder to myself about some opportunistic cleanup and perf tasks once we've gotten the big Reflection type hierarchy done.
- Remove all remaining AsType() calls. They're useless.
- IntrospectionExtensions.GetType(this Type)
  
  This no longer require any special knowledge of Reflection.Core
  so there's no need for it to pipe through that ReflectionAugments
  interface. Just implement it inline.
- Consider merging the rest of the ReflectionAugments callbacks into 
  ReflectionExecutionDomainCallback. Now that they all live happily in
  System.Private.CoreLib, there's no need for so many confusing channels.
- There's code (looking at you, Assignability.cs) that's probably doing 
  Type/TypeInfo conversions that are no longer necessary.
  Tighten some screws there.

**Comment by karelz** [comment]
@AtsushiKan's personal todo list which is mostly done.
