### ISSUE TITLE
MSBuild consistency in casing boolean properties

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#1022]
MSBuild properties are case sensitive.
The "false"/"true" vs "False"/"True"

What do we prefer?

It looks like we don't have any standards with this and I saw various places in the targets which mix two different casings even for the same properties.

I believe we should unify this

Examples:
src\System.Collections.Immutable\src\System.Collections.Immutable.csproj (lowercase):
```
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <Prefer32Bit>false</Prefer32Bit>
    <CodeAnalysisRuleSet>System.Collections.Immutable.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
```
and the same project in the bottom:
```
    <Compile Include="Strings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
```

src\dirs.targets: (Look at the IsTestProject property and CLSCompliant condition):
https://github.com/dotnet/corefx/blob/master/src/dir.targets#L94
```
 <PropertyGroup>
<IsTestProject Condition="'$(IsTestProject)'=='' And $(MSBuildProjectName.EndsWith('.Tests'))">True</IsTestProject>
<RunTestsForProject Condition="'$(RunTestsForProject)'=='' and '$(IsTestProject)'=='True'">True</RunTestsForProject>
<RunTestsForProject Condition="'$(SkipTests)'=='True'">False</RunTestsForProject>
<CLSCompliant Condition="'$(IsTestProject)'=='true'">false</CLSCompliant>
</PropertyGroup>
```

**Comment by nguerrera** [comment]
I like lowercase. Some of those are generated by VS and on different ways in different places. I would fix up the targets and props but leave the projects alone.

**Comment by weshaggard** [comment]
I also like lowercase but I've not seen and bugs causes by this (have you?) because I believe msbuild does case insensitive compares, it is just inconsistencies. I'm working on pulling a lot of these common targets into the build tools and as part of that I will try and clean up any of those casing issues as I do that work.

**Comment by ellismg** [comment]
+1 to lowercase from me.

**Comment by krwq** [comment]
I personally prefer uppercase although I put consistency over my personal opinion :)

**Comment by RichiCoder1** [comment]
:+1: for lower case, if only for consistency with how most people use booleans.

**Comment by StevenLiekens** [comment]
We should standardize on TRUE or FALSE.

**Comment by weshaggard** [comment]
I've made these conditions all consistently lower case with my build tools PR https://github.com/dotnet/buildtools/pull/106 which I will be bringing over into corefx repo.

**Comment by weshaggard** [comment]
I fixed all the places I found in the build tools targets. Please feel free to point out any places I might have missed.

**Comment by kzu** [comment]
FWIW MSBuild string comparison when dealing with booleans is *not* case sensitive.

"Test":

```
	<Target Name="Build">
		<Message Condition="'true' == 'True'" Importance="high" Text="true == True" />
		<Message Condition="'true' != 'True'" Importance="high" Text="true != True" />
	</Target>
```

You will see this output:

```
true == True
```
