### ISSUE TITLE
[dev/cms_unix] EnvelopedCms.Decrypt and EnvelopedCms.Encrypt don't support use of KeyAgreement certificates on Unix

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/corefx#10226]
Due to lack of support of OpenSSL to use certificates using DH or ECDH for encryption and decryption of enveloped messages, the current implementation doesn't support decrypting for recipients holding only KeyAgreement certificates or encrypting using one. As of now performing any of these operations throws a PlatformNotSupported exception.

The only way to work around this seems to be to manually parse the message to extract the encrypted content encryption key and use the appropriate API for the corresponding algorithm (DH or ECDH) to decrypt it and then use the key to decrypt the content blob.

**Comment by bartonjs** [comment]
While this is still true for managed approach, the managed approach won't support key agreement via EnvelopedCms unless we add support for (IFC) Diffie-Hellman to .NET.

Closing this now, and we can always revisit it if there's enough demand.
