### ISSUE TITLE
HttpClientHandler.AutomaticDecompression defaults to GZip|Deflate but not on documentation

### ISSUE THREAD

**Issue by joaope** [dotnet/corefx#10230]
`HttpClientHandler.AutomaticDecompression`'s [documentation](https://docs.microsoft.com/en-us/dotnet/core/api/system.net.http.httpclienthandler#System_Net_Http_HttpClientHandler_AutomaticDecompression) states that default value is `None` when [implementation](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Net/Http/HttpHandlerDefaults.cs#L15) says otherwise. 

Which one is correct?

**Comment by davidsh** [comment]
cc: @himadrisarkar @CIPop 

The implementation is correct.  The documentation is wrong.

**Comment by joshfree** [comment]
@davidsh @himadrisarkar the best course of action for updating the docs (API and conceptual) at https://docs.microsoft.com/en-us/dotnet right now is to file an issue @ https://github.com/dotnet/core-docs and a doc writer will make the change for you.

**Comment by himadrisarkar** [comment]
I have opened up the [documentation issue](https://github.com/dotnet/core-docs/issues/1054) to fix this.
