### ISSUE TITLE
Task.RunAsync that takes state?

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#10261]
None of the current Task.Run overloads accept state so either `Task.Factory.StartNew` with `.Unwrap()` still needs to be used or the state needs to be captured in a closure.

It would be good to have a Task.Run that also accepted a state parameter.

**Comment by stephentoub** [comment]
One of the goals of Task.Run was keeping things simple, with a relatively low number of overloads.  If you're talking about unwrap, presumably you're passing in a task-returning func, but for consistency we'd end up exposing state-based overloads for all of the various combinations, close to doubling them. Why is StartNew (or StartNew+Unwrap) insufficient?

**Comment by benaadams** [comment]
The use case might be better served by https://github.com/dotnet/corefx/issues/699; but the issue I normally have is when batching async to increase concurrency and reduce latency, e.g. distributed map+reduce or resource gathering (webapi or downloads). 

I write the code infrequently enough that I always go through the same discovery process, not quite remembering what I'd done previously.

I'll start with `Task.Run`, spend a little while on working out how to pass different parameters into each function. Then move to `.StartNew` as that takes parameters. Then spend a little while working out how to deal with `Task<Task<T>>` which isn't a problem with Task.Run, so add `.Unwrap()`. However, now allocations have increased.

Since allocations have increased, the closure comes back into the picture; however I don't want the closure over the loop variable as it will be the wrong value when the async function runs; which means calling a second function to return the function which creates the closure...

Now, I'm in a quandary as neither the closure nor the `.Unwrap` seems like a happy place and both seem quite a step change from queuing an async function to the threadpool that takes no parameters by just using `Task.Run`.

Maybe I'm missing a different approach?

**Comment by benaadams** [comment]
Changed to `Task.RunAsync` for taking async functions

**Comment by stephentoub** [comment]
> Then spend a little while working out how to deal with  Task<Task<T>>  which isn't a problem with Task.Run, so add  .Unwrap() . However, now allocations have increased.

Just because it's built in to Task.Run doesn't mean allocations don't increase.

**Comment by benaadams** [comment]
> Just because it's built in to Task.Run doesn't mean allocations don't increase.

But they do increase less

Task.Run
```csharp
private static async Task TaskRun()
{
    var batchTasks = new Task[2000];

    for (var i = 0; i < batchTasks.Length; i++)
    {
        batchTasks[i] = Task.Run(() => Task.Delay(1));
    }

    await Task.WhenAll(batchTasks);
}
```
![task-run](https://aoa.blob.core.windows.net/aspnet/TaskRun.png)

Task.Factory.StartNew+Unwrap
```csharp
private static async Task TaskStart()
{
    var batchTasks = new Task[2000];

    for (var i = 0; i < batchTasks.Length; i++)
    {
        batchTasks[i] = Task.Factory.StartNew(() => Task.Delay(1)).Unwrap();
    }

    await Task.WhenAll(batchTasks);
}
```
![task-start-new](https://aoa.blob.core.windows.net/aspnet/TaskStartNew.png)

System.Action I assume is an outlier as it can probably be dropped by converting lambda to delegate.

**Comment by stephentoub** [comment]
> But they do increase less

On desktop, they should be identical.  Are you seeing otherwise?

On core (which is what I assume you measured), they're a bit different, purely because the implementation of Unwrap (https://github.com/dotnet/corefx/blob/master/src/System.Threading.Tasks/src/System/Threading/Tasks/TaskExtensions.CoreCLR.cs) doesn't have access to the same UnwrapPromise used internally.  I expect that's a moment-in-time issue we can address, and I'd much rather address that than add eight new overloads of Task.Run.

**Comment by benaadams** [comment]
> > Maybe I'm missing a different approach?

> You can also use "await await ..." rather than "await ....Unwrap()".

Move the re-queuing into the `StartNew`, use await+await, and the queue as part of the state? 

Yes, that should solve it and likely be simpler. In which case this becomes a request for #699 so will close.

**Comment by stephentoub** [comment]
> Move the re-queuing into the  StartNew , use await+await, and the queue as part of the state? 

I'm missing some context.  What are you trying to accomplish?

**Comment by benaadams** [comment]
> I'm missing some context. What are you trying to accomplish?

Say have 1000 items to do, but want a max "on-wire" of 16; and as each one completes add another request until all are complete.

**Comment by stephentoub** [comment]
I see.  Yeah, you wouldn't want to use Task.Run / StartNew+Unwrap for each item, anyway.  It'd be better to create your 16 "workers" that would each pull the next item, invoke it, and await it, then rinse and repeat.
