### ISSUE TITLE
Can't install on Ubuntu16.04 xenial

### ISSUE THREAD

**Issue by AlexisColes** [dotnet/corefx#10295]
Trying to follow the getting started guide https://www.microsoft.com/net/core#ubuntu

When I run sudo **apt-get update** I get the following

alexis@UbDscTest1:~$ sudo apt-get update
Hit:1 http://gb.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://gb.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:3 http://gb.archive.ubuntu.com/ubuntu xenial-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu xenial-security InRelease
Ign:5 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial InRelease
Ign:6 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial Release
Ign:7 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main amd64 Packages
Ign:8 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main i386 Packages
Ign:9 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main all Packages
Ign:10 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main Translation-en_GB
Ign:11 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main Translation-en
Ign:7 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main amd64 Packages
Ign:8 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main i386 Packages
Ign:9 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main all Packages
Ign:10 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main Translation-en_GB
Ign:11 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main Translation-en
Ign:7 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main amd64 Packages
Ign:8 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main i386 Packages
Ign:9 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main all Packages
Ign:10 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main Translation-en_GB
Ign:11 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main Translation-en
Ign:7 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main amd64 Packages
Ign:8 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main i386 Packages
Ign:9 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main all Packages
Ign:10 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main Translation-en_GB
Ign:11 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main Translation-en
Ign:7 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main amd64 Packages
Ign:8 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main i386 Packages
Ign:9 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main all Packages
Ign:10 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main Translation-en_GB
Ign:11 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main Translation-en
Err:7 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main amd64 Packages
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Err:8 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main i386 Packages
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Ign:9 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main all Packages
Ign:10 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main Translation-en_GB
Ign:11 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main Translation-en
Reading package lists... Done
W: The repository 'https://apt-mo.trafficmanager.net/repos/dotnet-release xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://apt-mo.trafficmanager.net/repos/dotnet-release/dists/xenial/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
E: Failed to fetch https://apt-mo.trafficmanager.net/repos/dotnet-release/dists/xenial/main/binary-i386/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
E: Some index files failed to download. They have been ignored, or old ones used instead.

Then try running the **sudo apt-get install dotnet-dev-1.0.0-preview2-003121** and get the following:

alexis@UbDscTest1:~$ sudo apt-get install dotnet-dev-1.0.0-preview2-003121
[sudo] password for alexis:
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dotnet-dev-1.0.0-preview2-003121
E: Couldn't find any package by glob 'dotnet-dev-1.0.0-preview2-003121'
E: Couldn't find any package by regex 'dotnet-dev-1.0.0-preview2-003121'

Not quite sure what I have done wrong, please help.

**Comment by stephentoub** [comment]
Moved to dotnet/cli repo: https://github.com/dotnet/cli/issues/3936
