### ISSUE TITLE
[dev/cms_unix] Wrong key length when decoding EnvelopedCms in Linux encrypted with RC4 

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/corefx#10311]
When decoding an DER blob that represents envelopedData using EnvelopedCms.Decrypt incorrectly reports the encryption algorithm's key length to be 0 always instead of the one used to encrypt the message. 

This currently happens as there is a bug when setting the asn1 parameters in the call to OpenSSL to retrieve the key length.

**Comment by hoyosjs** [comment]
Looking further it looks like the same thing happens when there's a combination of RC4 over a CAPI certificate, where OpenSSL can't set the algorithm's parameters with the following error: "CMS routines:cms_EncryptedContent_init_bio:cipher parameter initialisation error"

**Comment by bartonjs** [comment]
This test was brought in to master via #27490, and is passing.  So we seem to be good here.
