### ISSUE TITLE
[dev/cms_unix] Encryption with variable keylength ciphers in EnvelopedCms for Linux not supported

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/corefx#10310]
Ciphers that support variable keylengths with the same OID currently only support encrypting with the default keylength as OpenSSL only allows to change these in the CTX, but the APIs for CMS_ContentInfo of type EnvelopedData for encryption only take the EVP_CIPHER pointer. There's a EVP_CIPHER_CTX_getcipher macro wich returns a pointer to its cipher, but that cipher still retains the default keylength regardless of the changes made to the CTX.

As of now the documented cases are RC2 and RC4 which when given a key length other than 0 or the default one will throw a PlatformNotSupportedException.

**Comment by bartonjs** [comment]
This is working with the new managed implementation.
