### ISSUE TITLE
Compilation netcoreapp1.0 with code which has Target Framework Monikers like #if !NETSTANDARD1_6

### ISSUE THREAD

**Issue by SerhiiS-in6k** [dotnet/corefx#10326]
I have problem with my project's dependency which has Target Framework Monikers like:  
"#if !NETSTANDARD1_6"
and when I compile for netcoreapp1.0 I have a compilation error, but netcoreapp1.0 support NETStanart1.6 , And I want to use this parts of the code in the app.
Thanks.

**Comment by svick** [comment]
[The same question on SO](http://stackoverflow.com/q/38584356/41071) (where I also answered).

**Comment by joshfree** [comment]
Thanks for posting the answer @svick.  @SerhiiS-in6k feel free to reactivate if there are more follow on questions.
