### ISSUE TITLE
XmlResolver not public

### ISSUE THREAD

**Issue by tim-xmlprime-com** [dotnet/corefx#10322]
I spent a little while trying to port XmlPrime (XQuery 3.0, XSLT 2.0) to .NET Core.

The change to make XmlResolver internal and the consequent removal of passing an XmlResolver via XmlReaderSettings is a blocking issue for us.  If I have understood the code correctly, XmlReader is now limited to resolving files on the local file system.

**Comment by sepidehMS** [comment]
Closing as I believe this is now fixed. Please feel free to reopen if your problem hasn't been solved.
