### ISSUE TITLE
Remove boilerplate from test projects

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#10335]
We should create some larger supports clauses to help reduce boiler-plate in our test projects.

EG: `coreFx.Test.net46` should include tuples not just for net46, but also for net461, net462, etc.  This is always the correct thing to do.

We should also create some convenience supports clauses that allow tests to say they should apply to all the frameworks that support a particular netstandard version.
EG: coreFx.Test.netstandard1.3 should include TFM/RID tuples for net46, netcore50, and netcoreap1.0 (as well as the future versions as stated above).
This allows a test that can run everywhere to have minimal boilerplate in the project.json.  Only if a test needs to hand-select frameworks does it need to use the more framework-granular clauses as mentioned above.

We should also have some simple docs that explain the purpose of frameworks and supports in our test project.json's.

/cc @ianhays

**Comment by danmosemsft** [comment]
@tarekgh trying to figure out whethere there's anything still worth tracking here. Santi is already changing tests to disregard specific NETFX versions. 

If not we can close.

**Comment by tarekgh** [comment]
This is not valid any more as we have changed the engineering system and now we are always testing the latest (netfx). @safern i scurrently working to clean up the test code from net4x and have only netfx. I am closing this one.

cc @weshaggard.
