### ISSUE TITLE
Dns.GetHostEntryAsync(IPAddress.None) succeeds on macOS

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#10345]
`await Dns.GetHostEntryAsync(IPAddress.None)` throws a SocketException on Windows, but doesn't on Unix.  I don't know if the right answer here is that the failing test should be made platform-specific for Windows (i.e. this is expected behavior on Unix) or whether there's a bug in the Unix implementation we need to fix so that this case also fails.

**Comment by Jiayili1** [comment]
Disabled test, reopen it.

**Comment by Jiayili1** [comment]
https://github.com/dotnet/corefx/blob/master/src/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs#L89

**Comment by stephentoub** [comment]
Updated: fails correctly on Windows and Linux, but doesn't on macOS.  Looks like it's simply an OS behavior.
