### ISSUE TITLE
Update Developer Wiki with new section on Code Coverage

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#1034]
The developer guide wiki (https://github.com/dotnet/corefx/wiki/Developer-Guide) should have a section on the code coverage system - including how to manually run the coverage build and generate a new report.

**Comment by mmitche** [comment]
Gracias

**Comment by joshfree** [comment]
de nada

**Comment by mmitche** [comment]
Updated

**Comment by joshfree** [comment]
Thanks @mmitche
