### ISSUE TITLE
Segmentation fault while running System.Runtime.Tests on CI

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#10375]
```
/mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_release_prtest/bin/tests/AnyOS.AnyCPU.Release/System.Runtime.Tests/netcoreapp1.0/RunTests.sh: line 290: 57218 Segmentation fault      (core dumped) ./corerun xunit.console.netcore.exe System.Runtime.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
```

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_release_prtest/1162/consoleFull

**Comment by adityamandaleeka** [comment]
It appears the VM has been reclaimed, so I can't access the dump that was generated. In the absence of any other information, I'm going to treat this as the same [issue that we're already investigating](https://github.com/dotnet/coreclr/issues/6283) where code in the JIT library occasionally segfaults on RedHat and CentOS with si_code 2 while accessing seemingly valid memory.

**Comment by adityamandaleeka** [comment]
See https://github.com/dotnet/coreclr/issues/6283#issuecomment-246041964

**Comment by karelz** [comment]
External issue tracked in https://github.com/dotnet/coreclr/issues/6283.
