### ISSUE TITLE
Update versioning documentation

### ISSUE THREAD

**Issue by maririos** [dotnet/corefx#10373]
With the distinction between `build-native` and `build-managed`, now the documentation is not reflecting the process to custom a version number.
For example, provide explanation about why using OfficialBuildID only affects build-managed and how the native binaries are generating their version according to it.

**Comment by weshaggard** [comment]
It is consistent between managed and native as we explicitly generate that native version stuff in our build-native scripts https://github.com/dotnet/corefx/blob/master/src/Native/build-native.cmd#L19.
