### ISSUE TITLE
BUILDTOOLS_OVERRIDE_RUNTIME should copy the PDB files from the CoreCLR output directory if available

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#10382]
When performing a build of CoreCLR, the PDBs are outputted in `bin/Product/OS.Arch.Configuration/PDB`, which is one subdirectory lower than where the binaries are placed (`bin/Product/OS.Arch.Configuration`). Unfortunately, these PDBs aren't automatically copied over like the binaries when settings `BUILDTOOLS_OVERRIDE_RUNTIME`, meaning you have to manually them over to get a better stack trace.

It would be nice if [this](https://github.com/dotnet/buildtools/blob/acf2600c88c93efd7ead8ba5365405dd417fc2a7/src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets#L109) had some additional logic to check for the existence of a `PDB/` directory beforehand and copy that over as well, since it would make things easier for people running tests on mscorlib.

cc @mellinoe @ellismg

**Comment by weshaggard** [comment]
Thanks for bringing up this issue @jamesqo. Instead of adding extra logic the copying I think I would much prefer we update the coreclr build to drop the pdb next to the dll instead. 

@gkhanna79 @jkotas do you guys know if there is any ready we don't drop the pdbs next to the output dll?

**Comment by jkotas** [comment]
Default cmake binaries layout. cmake drops PDBs into subdirectory by default.

**Comment by weshaggard** [comment]
This is an old infra piece to accomplish this now see https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md#testing-with-private-coreclr-bits.
