### ISSUE TITLE
[dev/cms_unix] Missing static tests in EnvelopedCms generated in a Unix system

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/corefx#10395]
Now that there is an implementation of EnvelopedCms for Unix platforms, the test suite is missing tests where a message is encrypted in a Unix platform and stored statically in a decryption test to make sure that cross platform decryption is possible (static Windows tests are already present in the suite).

Tests should include using the following symmetric algorithms:
- AES-128, AES-192, AES-256
- RC2 and RC4 (the only key length supported currently is 128 bits)
- DES
- 3DES

And should be encrypted using KeyTransfer certificates. There should be a test using each IssuerAndSerialNumer and SubjectKeyIdentifier as the identifiers for the recipient.

**Comment by bartonjs** [comment]
Some new fixed values tests were added from the managed implementation when it was being written.
