### ISSUE TITLE
Test failures for FileSystemWatcher on Ubuntu and OSX

### ISSUE THREAD

**Issue by jhendrixMSFT** [dotnet/corefx#10398]
In our official builds the following tests are failing, can you please investigate?

FileSystemWatcher_Directory_Changed_SymLink
FileSystemWatcher_Directory_Delete_SymLink
FileSystemWatcher_Directory_NotifyFilter_DirectoryName
FileSystemWatcher_File_Changed_SymLink

More information can be found in Mission Control.
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20160728.04/workItem/System.IO.FileSystem.Watcher.Tests

**Comment by mellinoe** [comment]
Ubuntu failure:

```
Unhandled Exception of type System.IO.IOException
Message:
System.IO.IOException : The configured user limit (128) on the number of inotify instances has been reached.
Stack Trace:
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.Tests.FileSystemWatcherTest.ExecuteAndVerifyEvents(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Boolean assertExpected, String[] expectedPaths)
   at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String[] expectedPaths, Int32 attempts)
   at System.IO.Tests.Directory_NotifyFilter_Tests.FileSystemWatcher_Directory_NotifyFilter_DirectoryName(NotifyFilters filter)
```

Isn't this just a machine configuration error? We might need to increase this limit.

**Comment by jhendrixMSFT** [comment]
Yes I think you're right.  I'll open a separate issue to increase the inotify instances on the Helix VMs.

**Comment by ianhays** [comment]
@jhendrixMSFT did you open a separate issue for the inotify instances? Looks like we're still getting failures because of that.

**Comment by jhendrixMSFT** [comment]
@ianhays Yes it's on the mseng board, I believe @MattGal is going to fix it.

**Comment by MattGal** [comment]
@ianhays  it's on my TODO list, should get to this this week and be in regular runs next week.

**Comment by ianhays** [comment]
resolved.

**Comment by MattGal** [comment]
@ianhays this should be fixed, looks like you've verified such.  Thanks!

**Comment by ianhays** [comment]
Thanks @MattGal! Did you increase the inotify limits on only the Ubuntu machines, or all of the Linux machines?

**Comment by MattGal** [comment]
@ianhays It should affect all Linux machines in .NET Helix, with the exception of the on-premises Performance testing machines (I don't control their setup).  From reading up this didn't seem to be any kind of a problem so I went for it.
