### ISSUE TITLE
[dev/cms_unix] EnvelopedCms doesn't support adding originator certificates in the encryption process

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/corefx#10409]
EnvelopedCms currently throws a platform not supported exception when trying to add originator certificates. Currently OpenSSL doesn't support adding certificates to a newly instantiated CMS_ContentInfo structure, only to one that's read from raw data. It's unviable to do it this way as we'd need a byte blob for each possible symmetric cipher or a parser that would do this.

**Comment by bartonjs** [comment]
Solved by the managed implementation of EnvelopedCms.
