### ISSUE TITLE
Test failures for System.Text.RegularExpressions on OSX

### ISSUE THREAD

**Issue by jhendrixMSFT** [dotnet/corefx#10400]
In our official builds the following tests are failing, can you please investigate?

RegexGroupTests.Groups

More information can be found on Mission Control.
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20160728.04/workItem/System.Text.RegularExpressions.Tests

**Comment by Priya91** [comment]
@jhendrixMSFT The mission control link is not loading the page.. I get a blank html render.

**Comment by jhendrixMSFT** [comment]
What browser are you using?  Are you able to sign in if you go to https;//mc.dot.net?

**Comment by Priya91** [comment]
Using chrome, seems like I am logged in, it shows my account on the right top corner.

**Comment by Priya91** [comment]
Signed out, and signed in.. now works

**Comment by Priya91** [comment]
Taking a look at the bug, this doesn't repro for me locally on my mac machine, the unicode char \u0069 is not correctly matched as lowercase latin i, while using ignorecase regex option. This is a globalization bug.

**Comment by tarekgh** [comment]
talked offline with @Priya91 and it looks in the failed machines maybe the current culture was set to Invariant which causing the test to fail. 

@Priya91 is going to let the test output the current culture to validate this assumption and then fix the test accordingly.

**Comment by Priya91** [comment]
This is fixed, not failing in mission control.
