### ISSUE TITLE
Build Fails on a dell machine (The remote server returned an error: (403) Forbidden.)

### ISSUE THREAD

**Issue by shrknt35** [dotnet/corefx#1041]
* I have downloaded the project as Zip.

Restoring build tools...
D:\Stuff\corefx-master (1)\corefx-master\dir.targets(49,5): error MSB4018: The "DownloadFile" task failed unexpectedly. [D:\Stuff\corefx-master (1)\corefx-master\build.proj]
D:\Stuff\corefx-master (1)\corefx-master\dir.targets(49,5): error MSB4018: System.Net.WebException: The remote server returned an error: (403) Forbidden. [D:\Stuff\corefx-master (1)\corefx-master\build.proj]
D:\Stuff\corefx-master (1)\corefx-master\dir.targets(49,5): error MSB4018:    at System.Net.WebClient.DownloadFile(Uri address, String fileName) [D:\Stuff\corefx-master (1)\corefx-master\build.proj]
D:\Stuff\corefx-master (1)\corefx-master\dir.targets(49,5): error MSB4018:    at System.Net.WebClient.DownloadFile(String address, String fileName) [D:\Stuff\corefx-master (1)\corefx-master\build.proj]
D:\Stuff\corefx-master (1)\corefx-master\dir.targets(49,5): error MSB4018:    at InlineCode.DownloadFile.Execute() in c:\Users\IC018479\AppData\Local\Temp\bnibng0b.0.cs:line 64 [D:\Stuff\corefx-master (1)\corefx-master\build.proj]
D:\Stuff\corefx-master (1)\corefx-master\dir.targets(49,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [D:\Stuff\corefx-master (1)\corefx-master\build.proj]
D:\Stuff\corefx-master (1)\corefx-master\dir.targets(49,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext() [D:\Stuff\corefx-master (1)\corefx-master\build.proj]

    0 Warning(s)
    1 Error(s)
Time Elapsed 00:00:00.48
Build Exit Code = 1

**Comment by joshfree** [comment]
Hi @shrknt35, 
You're getting an HTTP Error 403 (access denied / forbidden) while attempting to download https://www.nuget.org/nuget.exe, which is a pre-requisite for completing the build.

```
error MSB4018: System.Net.WebException: The remote server returned an error: (403) Forbidden. 
```

Are you still experiencing this issue or was it transient?

**Comment by shrknt35** [comment]
No, i am still having the same issue.

**Comment by joshfree** [comment]
You can try debugging this simplified repro.  I suspect it's a machine configuration issue such as a local firewall setting.  If we see this on our side or if we get more information we'll update this thread. --

```c#
using System;
using System.IO;
using System.Net;

class repro {
    private static void Main() {
        var uri = @"https://www.nuget.org/nuget.exe";
        var savedFile = Path.GetTempFileName();      
        Console.WriteLine("Downloading {0} to {1}", uri, savedFile);

        try {
            var client = new WebClient();
            client.DownloadFile(uri, savedFile);
            Console.WriteLine("success..");
        }
        catch (Exception e) {
            Console.WriteLine(e);
        }
    }
}
```

**Comment by shrknt35** [comment]
I have check it. There was problem with my proxy...
