### ISSUE TITLE
Self-discovery documentation in Build -?

### ISSUE THREAD

**Issue by maririos** [dotnet/corefx#10422]
Add documentation to the build command when using the argument `-?` on how to interact with the repo and not only providing information about the command per se.

**Comment by mellinoe** [comment]
Hey @maririos , are you still looking into this, or is it better tracked elsewhere, etc? I think there's other related issues in here and in buildtools.

**Comment by maririos** [comment]
Currently there is effort working on Run.exe but I'm not sure it includes this issue.
@MattGal could answer this more accurately

**Comment by mellinoe** [comment]
I'm marking this up for grabs, although I'm not sure we should write much in the message here, other than to look in the Documentation folder for more info.

**Comment by weshaggard** [comment]
This is not really on any radar. We are more likely to completely remove the run tool then to flush out this so closing.
