### ISSUE TITLE
Package versioning space

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#10427]
Before we ship 1.1 we need to figure out our versioning strategy for servicing. Currently we have only bumped up the patch versions in master but if we plan to ship servicing fixes from our release branches they will need space in the patch versioning to be able to ship updates.

Seems like we have a few options:

1.  Bump up minor versions in masters and save patch versions for servicing
2.  Bump up patch versions by some interval in master so we have some empty space for servicing
3.  Use the 4th version part for servicing. 

Picking the right interval for option 2 might be difficult and if we guess too low we might put ourselves in a corner. I don't know all the implications of option 3 because I'm not sure what packages will do in those cases. So unless I'm missing another option the only real option is 1. 

fyi - @leecow @joshfree @gkhanna79

**Comment by joshfree** [comment]
I prefer #1.  Can we bump the minor versions in master and dev/api for 1.1 and 1.2, respectively?

**Comment by ericstj** [comment]
The downside of #1 is that its inconsistent with semantic versioning.  Also if we reflect the same change in assembly versions that means *every* assembly breaks out of unification on desktop even if it has the same API.  We can't do that so we'd have to make the packages have a different version than the max of assembly versions they contain.

I think we should explore using the 4th part.  I believe NuGet does support 4-part versioning.

**Comment by leecow** [comment]
Version field changes need to respect semver. Keep in mind that we're not talking about servicing in historic sense. We need to enable our processes such that releases for supported versions can be shipped and the nature of the included changes generally determine what part of the version number is updated. A simple bug fix update would bump the patch field.

**Comment by gkhanna79** [comment]
I think there are two versioning aspects here:

1) Bumping the version of the assembly/file to be inline with Desktop unification - exploring the 4th part makes sense here since SemVer does not have the notion of the 4th part
2) Bumping the version of the package - Option 1 in @weshaggard proposal sound reasonable to me. @ericstj Why is the inconsistent with SemVer?

We should keep in mind that our roll-forward semantics are based upon the 3 part versioning of semver and only rolls forward based upon patch - there is no notion of 4th part.

**Comment by ericstj** [comment]
> Why is the inconsistent with SemVer?

Because minor version is supposed to communicate a change in API or features.  Many of the libraries will not change at all other than to rebuild so communicating a minor version change is not consistent with the actual change to that library.

**Comment by gkhanna79** [comment]
> Because minor version is supposed to communicate a change in API or features

Per http://semver.org/:

`MINOR version when you add functionality in a backwards-compatible manner`

I would expect that we are adding some new functionality in a backwards compatible manner, so it should be okay per semver to have M.N.App to have a minor version update, even if majority of the constituting packages remain the same version.

**Comment by ericstj** [comment]
The point is that we're not adding any functionality in many of these libraries, to start they all have the exact same source as what's in the servicing branch.  So versioning them all is a lie.

**Comment by ericstj** [comment]
This has been addressed with https://github.com/dotnet/corefx/pull/10971
