### ISSUE TITLE
Clean properties and documentation in config.json file

### ISSUE THREAD

**Issue by maririos** [dotnet/corefx#10421]
- Go through all the options in our config.json file and get them properly documented. For example the difference between `OSGroup`, `TargetOS` and `FilterToOsGroup`.
- Update documentation to use the proper properties according to the desire behavior

**Comment by mellinoe** [comment]
@maririos @MattGal Are either of you working on this, or is there anything more to do here?

**Comment by karelz** [comment]
@maririos @MattGal ping?

**Comment by MattGal** [comment]
I'm not currently working on this.   We're looking at reimagining what the contract looks like, so I think it'd be OK to close this issue for now;  there are many issues tracking improvement to the dev workflow.

**Comment by karelz** [comment]
Fine with me. @mellinoe feel free to reopen if you disagree.
