### ISSUE TITLE
Using Console.SetOut doesn't affect IsOutputRedirected

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/corefx#10428]
... similarly for Input and Error.

See : https://github.com/dotnet/corefx/blob/5e36ca02d2594f715da829aafaf7af2b554dfcdf/src/System.Console/src/System/ConsolePal.Unix.cs#L461-L467

The summary describes the behavior I expect which is checking `Console.Out` but the actual behavior is checking `STDOUT`

@stephentoub @ianhays

**Comment by ianhays** [comment]
IsOutputRedirected looks at the output/input/error handles themselves. SetOut doesn't affect those, so Is*Redirected is unaffected by SetOut/SetIn/SetError. SetOut only modifies the TextWriter that the Console operations call e.g. if you do a manual interop write to the stdout handle it will function the same regardless of what SetOut is set to.

The Unix behavior was made to mimic the Windows behavior in this regard.

**Comment by BrennanConroy** [comment]
Yeah I can see that. I'm saying its not great behavior, you are operating on the "Console" object when calling `SetOut` and `IsOutputRedirected` should reflect the "Console" objects internal state.

It would be great to have a way of seeing if `Console.Out` (and friends) is actually redirected from `STDOUT` without having to manually Pinvoke

**Comment by muratg** [comment]
:eyes:

**Comment by karelz** [comment]
We need formal API proposal.

**Comment by ianhays** [comment]
Does anyone want to take this and submit a formal API proposal with samples and use cases? If not, I'm going to close the issue as there hasn't been any movement in a while.

**Comment by muratg** [comment]
@BrennanConroy could you update the impact of this? (and what workaround did we use?)

@ianhays please do not close just yet. IIRC, an ASP.NET scenario was impacted with this...

**Comment by BrennanConroy** [comment]
We wanted a way to check if `Console.Out` was being redirected for logging to possibly remove ANSI Color Codes. I'm not sure if we still want to be able to do that @glennc

**Comment by glennc** [comment]
I think we are good to close this. At this point we have enough other mitigations to the root problems in place that it isn't important enough for us to try and make a change at this level of the stack.
