### ISSUE TITLE
New netstandard APIs

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#10426]
The below APIs have been added to netstandard1.6 reference assemblies post 1.0 release and they don't exist on the full .NET Framework yet. We either need to remove them temporarily or make them specific to netcoreapp before we ship 1.1. 
- Regex.Group.Name: https://github.com/dotnet/corefx/pull/9526 cc @Priya91
- UTF8 marshaling:  https://github.com/dotnet/corefx/pull/8607 cc @tijoytom  @yizhang82 
- ~~StreamContext: https://github.com/dotnet/corefx/pull/10036 cc @stephentoub~~

**Comment by weshaggard** [comment]
@ericstj these are the Regex and UTF8 APIs we were talking about.

**Comment by ericstj** [comment]
OK, I can make them so that they are "netcoreapp1.1" specific changes.  Technically the regex & serialization changes could work on netcoreapp1.0 since those aren't "split" packages and don't look like they depend on new types from split packages.  Would you like to do that?

**Comment by ericstj** [comment]
This has been fixed with https://github.com/dotnet/corefx/pull/11886.

**Comment by ericstj** [comment]
We need a similar change in master, leaving this open to track that.

**Comment by yizhang82** [comment]
@ericstj @weshaggard Tijoy is working on getting this into 4.6.3 and .NET native, will we be able to change it back to netstandard 1.6?

**Comment by ericstj** [comment]
Not 1.6 but potentially a future version.  We'd need to make sure other .NET implementations can support this (eg: Xamarin).

**Comment by ericstj** [comment]
> We need a similar change in master, leaving this open to track that.
That was actually being tracked with https://github.com/dotnet/corefx/issues/12307, which is now closed.
