### ISSUE TITLE
New Dev Workflow doesn't detect test failures and still succeeds the build

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#10430]
By just running build.cmd with the new workflow, if one or more test fails the build will still be marked as succeeded. When we first saw this we thought it only reproed on non-Windows, but I just got a repro on Windows as well.

![image](https://cloud.githubusercontent.com/assets/13854455/17259606/30d3ab1e-5581-11e6-8823-e8d1e73fe855.png)

@maririos

**Comment by maririos** [comment]
Msbuild is returning `ExitCode=0` so the Run Tool is printing Build Succeeded. 
I filed Issue Microsoft/msbuild#853 in the msbuild repo.

**Comment by maririos** [comment]
FYI: @Priya91

**Comment by weshaggard** [comment]
Can we try and work around this somehow until we can get an msbuild fix?

**Comment by maririos** [comment]
Yes, we could use the output from the `msbuild.err` file and according print the correct exit message and return the corresponding exit code
