### ISSUE TITLE
System.Diagnostics.Debug.SymbolReader API review

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#10437]
Review the System.Diagnostics.Debug.SymbolReader contract API.

In particular the type name seems wrong:
System.Diagnostics.Debug.SymbolReader.SymbolReader

We should not duplicate the type name in the namespace.

**Comment by mellinoe** [comment]
Having a `System.Diagnostics.Debug` namespace is also not ideal because of the `System.Diagnostics.Debug` class.

How about `System.Diagnostics.SymbolReader`?

**Comment by ericstj** [comment]
/cc @terrajobst 
That isn't the only thing to look at here.  Let's go through the proper review process.

**Comment by mikem8361** [comment]
So the namespace would be “System.Diagnostics” with the existing class name “SymbolReader”?

**Comment by ericstj** [comment]
@mikem8361 please see: http://aka.ms/api-review.

**Comment by weshaggard** [comment]
We also have https://github.com/dotnet/corefx/issues/8981 which was the original issue tracking the api.

**Comment by ericstj** [comment]
Crud I searched for that but didn't find it.  Closing this.
