### ISSUE TITLE
CI test crashes not being reported correctly

### ISSUE THREAD

**Issue by adityamandaleeka** [dotnet/corefx#10449]
While investigating why a potential codegen bug wasn't discovered in CoreFX Jenkins runs, I discovered that these tests were indeed crashing in outerloop runs, but the crashes were not being reported as failures.

For instance, [this job](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu14.04_release/105/) reports that there were no test failures, but if you go to the console output, you'll see that the System.Linq.Parallel.Tests actually segfaulted:

```
/mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu14.04_release/bin/tests/AnyOS.AnyCPU.Release/System.Linq.Parallel.Tests/netcoreapp1.0/RunTests.sh: line 288: 14092 Segmentation fault      (core dumped) ./corerun xunit.console.netcore.exe System.Linq.Parallel.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=IgnoreForCI -notrait category=failing -notrait category=nonlinuxtests
11:06:24   Finished running tests. End time=18:07:25. Return value was 139
```

Furthermore, based on [this table](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu14.04_release/105/testReport/), there's no record that these tests were even attempted.

**Comment by karelz** [comment]
@ellismg is that still the case? It is somewhat concerning.
/cc: @weshaggard @danmosemsft

**Comment by ellismg** [comment]
This appears to be fixed now.  I ran a test job that forced a crash in the runtime and the right thing happened:

```
17:23:18 /mnt/resource/j/workspace/dotnet_corefx/release_1.1.0/rhel7.2_debug_prtest/Tools/tests.targets(261,5): warning MSB3073: The command "/mnt/resource/j/workspace/dotnet_corefx/release_1.1.0/rhel7.2_debug_prtest/bin/tests/AnyOS.AnyCPU.Debug/System.Globalization.Tests/netcoreapp1.0/RunTests.sh /mnt/resource/j/workspace/dotnet_corefx/release_1.1.0/rhel7.2_debug_prtest/packages/" exited with code 134. [/mnt/resource/j/workspace/dotnet_corefx/release_1.1.0/rhel7.2_debug_prtest/src/System.Globalization/tests/System.Globalization.Tests.csproj]
17:23:18 
/mnt/resource/j/workspace/dotnet_corefx/release_1.1.0/rhel7.2_debug_prtest/Tools/tests.targets(270,5): error : One or more tests failed while running tests from 'System.Globalization.Tests' please check log for details! [/mnt/resource/j/workspace/dotnet_corefx/release_1.1.0/rhel7.2_debug_prtest/src/System.Globalization/tests/System.Globalization.Tests.csproj]
```

Jenkins correctly detected the above as a failure:

```
17:34:30 Command execution failed with exit code 1.
17:34:30 Build step 'Execute shell' marked build as failure
```

And correctly failed the job.
