### ISSUE TITLE
Microsoft.DotNet.TestHost.1.0.3-prerelease only targets 32-bit

### ISSUE THREAD

**Issue by leppie** [dotnet/corefx#1044]
Running tests on Window 7 64-bit fails due to `CoreRun.exe` being 64-bit and the TestHost dlls being 32-bit.

When setting the 32-bit flag on `xunit.console.netcore.exe` with `corflags.exe` and invoking it directly (iow without `corerun.exe`), the tests work again.

    > dumpbin /headers CoreRun.exe | find "machine"
            8664 machine (x64)

    > dumpbin /headers api-ms-win-core-console-l1-1-0.dll | find "machine"
             14C machine (x86)

**Comment by ebickle** [comment]
Having the same issue here. Running a complete build gives multiple errors of "CoreRun.exe - Application Error. The application was unable to start correctly (0xc000007b)."

Opening corerun.exe in Dependency Walker shows a mixture of x86 and x64 libraries being loaded into the same 64-bit process.

**Comment by weshaggard** [comment]
@AlexGhiondea I suspect this was caused by your recent changes could you please have a look?

**Comment by robbchar** [comment]
I'm hitting this too. Lemme know if I can get you more info.

**Comment by mmitche** [comment]
@weshaggard @AlexGhiondea I'm working on getting WIn7 coverage.  Azure doesn't usually host the client OS's.

**Comment by leppie** [comment]
Tedious workaround:

    cd src
    ..\packages\NuGet.exe install Microsoft.DotNet.TestHost -Prerelease -Version 1.0.2-prerelease

Now copy the files from `packages\Microsoft.DotNet.TestHost.1.0.2-prerelease\lib\aspnetcore50\` that have the same names as the ones in `packages\Microsoft.DotNet.CoreCLR.1.0.2-prerelease\lib\aspnetcore50\`.

Call `build.cmd`. Tests will run now.

**Comment by nguerrera** [comment]
This was fixed in #1083 by picking up newer packages that match x86 to x86. There is still more work to support x64, but with a consistent use of x86 bits, tests should run fine on all machines.

**Comment by bartonjs** [comment]
Merging in #1083 allowed me to successfully run build.cmd (including the unit test launching) on Windows Server 2012 (not R2) and Windows 7 (Client).

Furthermore things are working successfully with master up through cf664ea075339e24bb7e816e2de338d449d322a3 (the latest as of this message).

**Comment by leppie** [comment]
Thanks :)
