### ISSUE TITLE
Is Environment.ProcessorCount supposed to be cached?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#10484]
I noticed that #9851 which adds Environment to this repo seems to [cache `ProcessorCount`](https://github.com/dotnet/corefx/pull/9851/files#diff-f22c2c21bb8e123660fb98b76393bbebR157), whereas the 'old' implementation in CoreCLR [always seems](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Environment.cs#L550) to do a native call. Is this new implementation really correct?

For example, there is a class in CoreCLR, [`PlatformHelper`](https://github.com/dotnet/coreclr/blob/775003a4c72f0acc37eab84628fcef541533ba4e/src/mscorlib/src/System/Threading/SpinWait.cs#L295), with a static `ProcessorCount` property that is just a wrapper over `Environment.ProcessorCount` except that it only updates every 30 seconds. This would imply that 2 different invocations of the method could return different values, right?

Looking at the documentation [on MSDN](https://msdn.microsoft.com/en-us/library/system.environment.processorcount(v=vs.110).aspx) seems to confirm this:

> If the current machine contains multiple processor groups, this property returns the number of logical processors **that are available for use** by the common language runtime (CLR).

That seems to be saying that if there are logical processors on the machine not available to the CLR then they won't be included in the count, and later if they're made available they will be?

cc @stephentoub @jkotas

**Comment by stephentoub** [comment]
> Is Environment.ProcessorCount supposed to be cached?

Partially, yes.  You can see the CoreCLR implementation here:
https://github.com/dotnet/coreclr/blob/775003a4c72f0acc37eab84628fcef541533ba4e/src/classlibnative/bcltype/system.cpp#L389
That call to GetNumActiveProcessors returns a cached result.

But, the fallback that uses GetSystemInfo shouldn't be cached.  I'll fix that.

**Comment by jamesqo** [comment]
Closing this as the PR was merged. No idea why GitHub didn't do it automatically.
