### ISSUE TITLE
Server not resolving DNS, only accepts web service URL with IP

### ISSUE THREAD

**Issue by ethriel3695** [dotnet/corefx#10491]
We have an Ubuntu server set up for our .Net Core application and running Nginx.  Our web services URL works when we pass the IP address, but we get an error stating the DNS cannot be found or does not exist when passing the name of the server rather than the IP.  Can anyone provide insight on this issue please?

**Comment by ethriel3695** [comment]
I did some research and found Kestrel does not support hostname listening only IP binding.  Is there a workaround for this?

**Comment by ethriel3695** [comment]
After some further testing, we found the DNS resolve was timing out because it is taking over a minute and a half for the DNS to resolve.  Does anyone have insight on why this would happen? 
We were able to set an IIS server with no issues and it functions just fine, but when using Ubuntu with Nginx the DNS takes entirely too long to resolve.

**Comment by muratg** [comment]
@ethriel3695 Can you try ubuntu/nginx/node.js and see if that works?  to me it looks like a machine or nginx configuration issue, and I'm not sure if it's related to asp.net or .net core.

**Comment by davidsh** [comment]
Closing this issue for now.  Please update if there is new information regarding a possible bug in CoreFx.
