### ISSUE TITLE
Missing tests veryfing decryption contents of messages in EnvelopedCms

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/corefx#10515]
The current test suite doesn't have verifying that the contents of the decrypted message is the expected one for the following algorithms:
- Round Trips:
1. DES
2. AES-128, AES-192
3. RC2
4. RC4
- Windows generated static tests:
1. DES
2. RC2
3. RC4

**Comment by stephentoub** [comment]
@bartonjs, this can be closed now, right?

**Comment by bartonjs** [comment]
Yep, looks like this was done by https://github.com/dotnet/corefx/pull/27490.
