### ISSUE TITLE
CultureInfo's Payloads on CoreCLR and Desktop Not Compatible

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#10513]
PR #9014 attempted to make `System.Globalization.CultureInfo` serializable on CoreCLR. The issue is that the serialization payload generated on CoreCLR is not compatible with the one on Desktop, which caused a `CultureInfo` object cannot make a roundtrip between CoreCLR and full framework. This is due to the fact that `CultureInfo` uses different names for its fields across different platforms. 

`CultureInfo` should have consistent names for fields, which are being serialized on Desktop, across platforms, including full framework, CoreCLR, and NetNative.

https://github.com/dotnet/corefx/issues/8736 is blocked by this issue.

**Comment by tarekgh** [comment]
Ass discussed offline with @shmao we are not going to support the globalization classes DCS in the current time across-plat because the scope of the work is big while this is not blocking or requested features.
