### ISSUE TITLE
Marshal.ZeroFreeMemoryUTF8 doesn't exist

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#10511]
Looks like we didn't fully rename ZeroFreeMemoryUTF8 to ZeroFreeCoTaskMemUTF8. ZeroFreeMemoryUTF8  exists in the reference assembly but not the implementation.

Reference assemblies:
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs#L662
https://github.com/dotnet/coreclr/blob/99c0410601955552920079a7465c64e725814c2c/src/mscorlib/ref/mscorlib.cs

Change to rename in implementation:
https://github.com/dotnet/coreclr/commit/42929098cb110c62a2605cdf789239950e85dadf

**Comment by yizhang82** [comment]
@weshaggard Do we know why this isn't failing the build?

**Comment by weshaggard** [comment]
Because it is also incorrectly included in the mscorlib ref we use for build corefx (https://github.com/dotnet/coreclr/blob/99c0410601955552920079a7465c64e725814c2c/src/mscorlib/ref/mscorlib.cs) and that ref currently isn't validated on the coreclr side.

**Comment by yizhang82** [comment]
@weshaggard Thanks. Do we also have the check-if-ref-match-implementation thing in the build? We could check it against mscorlib implementation.

**Comment by weshaggard** [comment]
We have APICompat checks in our build but they are currently using the mscorlib reference assembly as the "implementation" which is out of sync with S.P.CoreLib right now with regards to this API. I will be working on making this error as part of our build once we make these libraries compile against S.P.CoreLib.

**Comment by yizhang82** [comment]
@weshaggard Sounds good. Thanks!

**Comment by tijoytom** [comment]
https://github.com/dotnet/corefx/issues/10511

**Comment by tijoytom** [comment]
https://github.com/dotnet/corefx/commit/7a22b935161f8b0e08c1c4088e44e44178b26042#diff-7a23a782f458d0508686dcf2b92c5820
