### ISSUE TITLE
How to skip build Windows_NT OS Group while building inside Linux.

### ISSUE THREAD

**Issue by parjong** [dotnet/corefx#10519]
It seems that Windows_NT binaries are built even with `-BuildAllOSGroups:False -FilterToOSGroup:Linux`:

```
$ ./build-managed.sh -binaries -SkipTests -OSGroup:Linux -TargetOS:Linux -BuildAllOSGroups:False -FilterToOSGroup:Linux
...
$ ls bin/
AnyOS.AnyCPU.Debug/  Linux.AnyCPU.Debug/  obj/  ref/  Unix.AnyCPU.Debug/  Windows_NT.AnyCPU.Debug/
```

Is there any other option to skip Windows_NT binaries?

**Comment by weshaggard** [comment]
Right now we always build all flavors of the product binaries because we need all of them in order to create the nuget packages.  So there isn't any way to filter the build in that way.

**Comment by mellinoe** [comment]
As @weshaggard mentioned, there's not a good way to do this right now, due to the way the build system is structured. We are working on an effort to overhaul large parts of the build system, and "skipping unnecessary builds" is a prime objective of the new system.
