### ISSUE TITLE
RegexGroup should provide a Name

### ISSUE THREAD

**Issue by ashmind** [dotnet/corefx#1051]
#### Background

Regex group can have names assigned to them (e.g. `(?<name>.+)`). Those names can be used in an indexer of `RegexGroupCollection`, however the `RegexGroup` objects themselves do not provide a `Name` property.

The names can be retrieved using `regex.GetGroupNames`, but it is not immediately obvious -- and I'm not sure it is even possible if static `Regex` method was used for matching.

To prove it is not obvious, see this [Regex: get the name of captured groups in C#](http://stackoverflow.com/questions/1381097/regex-get-the-name-of-captured-groups-in-c-sharp) which at the moment had 48 votes on question, and 66 on answer. There are a few similar questions as well.

#### API Design

```csharp
public class RegexGroup : ... {
    // ...
    public string Name { get; }
}
```

Note that for numbered groups this should return group index as string, for consistency with `Regex.GetGroupNames`.

#### Compatibility

At the moment I do not see any potential compatibility issues with adding a property.

**Comment by krwq** [comment]
Sounds like a reasonable idea to me. :+1:

**Comment by MgSam** [comment]
:+1: Funnily enough, this is the biggest missing feature I've run into in the BCL. You're encouraged to use the static `Regex` class for performance (caching) reasons, and yet if you do so you lose all access to the group names. 

I've had to work around this before by creating an extension method which uses reflection to inspect the private members of the Group class to get the group name. This obviously is an ugly, brittle solution that should be replaced by a real property in the BCL.

**Comment by Priya91** [comment]
Pushing into future branch on corefx.

**Comment by ashmind** [comment]
It's awesome that this got implemented, but I am confused about the process -- shouldn't it have gone through "Accepting PRs"? Or was it judged to be important enough to do internally without going through community?

(I'm asking because I considered working on it myself, but was waiting for "Accepting PRs" flag)

**Comment by Priya91** [comment]
@terrajobst : What's the process around this? I assumed, if it's assigned, then i can implement it?

**Comment by weshaggard** [comment]
@Priya91 yes we should try following the API Review process https://github.com/dotnet/corefx/wiki/API-Review-Process.
