### ISSUE TITLE
Consider merging DisplayFormatAttribute into DisplayAttribute

### ISSUE THREAD

**Issue by cervengoc** [dotnet/corefx#10526]
We use `DisplayFormatAttribute` heavily to provide annotations which can be consumed by several kind of controls like grids, text contents, etc.

The issue with this attribute is that it's not localizable.

In one of .NET's earlier versions the _legacy_ `DisplayName`, `Description`, and `Category` attributes have been merged into the new `DisplayAttribute`, so that they can be nicely localized. However, at that point for some reason, the `DisplayFormatAttribute` had been kept separately. 

It would be important to merge it into `DisplayAttribute` too, because it has at least two fields which are important to localize: 

```
public string DataFormatString { get; set; }
public string NullDisplayText { get; set; }
```

These should definitely be part of `DisplayAttribute` I think.

**Comment by ajcvickers** [comment]
@danroth27 @dougbu Do either of you know if it is by-design that DisplayAttribute does not have DataFormatString and NullDisplayText? It looks to me like DisplayAttribute is not designed to use these properties and therefore it would not be appropriate to add them, but I am hoping somebody else has some more context.

**Comment by dougbu** [comment]
In my opinion, `DataFormatString`, `NullDisplayText` and other `[DisplayFormat]` properties are better where they are. These properties are focused on the value of a field while `[Display]` properties are focused on what surrounds the field. (`Prompt` might cross the line but the rest are pretty clear.)

The alternative of adding `ResourceType` to `[DisplayFormat]` would be a significant breaking change. No code expects `DataFormatString` or `NullDisplayText` to ever change.

A `[DisplayFormatNew]` attribute in the `System.ComponentModel.DataAnnotations` namespace might be viable if there is sufficient interest.

#### History

I don't have the full history. The timing indicates `[Category]`, `[Description]` and `[DisplayName]` have been around forever (.NET 1.1). `[DisplayFormat]` was added in .NET 3.5; may have been when the `System.ComponentModel.DataAnnotations` namespace was created. `[Display]` came in .NET 4.0 and, yes, it probably was to replace / modernize the .NET 1.1 attributes in the "legacy" `System.ComponentModel` namespace.

**Comment by danroth27** [comment]
@Eilon

**Comment by cervengoc** [comment]
Thank you for your updates.

I agree with @dougbu that `DisplayFormat` properties indeed belong to a different place than `Display` properties, so I can fully accept this logic. However the biggest problem was for me the inability to localize the `DisplayFormat` properties.

At my current level of insight I can't see the breaking change what localizability would introduce in `DisplayFormatAttribute`, but I definitely believe you, so no need for further explanation.

Introducing a new `DisplayFormatNewAttribute` doesn't seem to be nice in my opinion either, but if there's no other chance, it would be OK.

**Comment by divega** [comment]
> The alternative of adding ResourceType to [DisplayFormat] would be a significant breaking change. No code expects DataFormatString or NullDisplayText to ever change.

@dougbu are you using the term "breaking change" in the sense that framework code that consumes data annotations such as would need to be updated in order to take advantage of new functionality or is there something specific that would actually crash or cause the display or garbled data or something worse? Also, what frameworks do you think would need to make adjustments, MVC5? Core MVC? (note that at the moment we are considering this for .NET Core; porting back to .NET Framework is something that we would consider later) 

If you are talking about frameworks not being able to take advantage of the feature, then what would be the difference between the work required to update such frameworks to recognize a new attribute and to adapt to a localizable version of `DisplayFormatAttribute`?

**Comment by dougbu** [comment]
@divega I'm thinking of all kinds of shipped packages that load customer code and handle data annotations on the loaded classes. ASP.NET MVC Core is one example. But, I would not be surprised if the number of impacted frameworks was quite high.

Note it isn't really about "taking advantage". The user's code and their `[DisplayFormat]` attributes using the new feature is **Just Fine:tm:** up until e.g. MVC core gets involved. Then, displayed formats will be constants despite changing locales.

**Comment by dougbu** [comment]
Ooops, hit return too soon.

The difference with a new attribute would be the lack of in-between state: .NET Core extensions either understand `[DisplayFormatMarkII]` or they don't.

**Comment by divega** [comment]
@dougbu thanks for clarifying. 

FWIW, a large portion of the issues we get it in DataAnnotations have this characteristic: the change to the DataAnnotation seems relatively easy, but we would need to go modify DataAnnotations-aware frameworks for the change to actually have any effect. 

> The difference with a new attribute would be the lack of in-between state: .NET Core extensions either understand [DisplayFormatMarkII] or they don't.

Makes sense, however I don't necessarily see a definitive reason to prefer the new attribute approach there. E.g. until MVC has proper supports the disappointment is similar. Assuming support can be added, having a single attribute for the long term is better than two.

**Comment by dougbu** [comment]
@divega has convinced me that we don't need an additional attribute just to support a locale-sensitive `NullDisplayText`. Also sounds like everyone is in agreement merging `[Display]` and `[DisplayFormat]` isn't the way to go.

`DataFormatString` is already as locale-sensitive as the chosen `IFormatProvider`. If you want to change the meaning of the `x` format specifier for an `int` (currently locale-insensitive hex) or add your own `q` format specifier for whatever type, implement `IFormatProvider`. Could even use resource lookups in that implementation.

My suggestion is to add a `NullDisplayResourceType` or `NullDisplayTextResourceType` property and `GetNullDisplayText()` method to `[DisplayFormat]`. The `NullDisplayText` property should have _exactly_ the same semantics it has today -- getter returns `null` or the most recently-set value. `GetNullDisplayText()` would return the `NullDisplayText` value unless `NullDisplayResourceType` was non-`null`. In that case, it would return the appropriate resource string. This mirrors how `[Display]` properties and methods work.

**Comment by lajones** [comment]
We would consider a PR for this if someone would like to provide one.

**Comment by Ermiar** [comment]
I would like to take a look to this issue if that is okay.
Just to be sure that I'm heading in the right direction: there is no need to add the future `GetNullDisplayText()` method elsewhere in the framework to be used right now, is that correct ?
Also there is no tests currently for `[DisplayFormat]` so I will use my PR to add some tests (for existing and added code).

**Comment by Ermiar** [comment]
@lajones I have code ready to address this issue. Can I submit my PR ?

**Comment by lajones** [comment]
@Ermiar Feel free to submit. @dougbu - you should probably review the PR.

**Comment by dougbu** [comment]
> you should probably review the PR

🆗

**Comment by Ermiar** [comment]
@lajones @dougbu Thanks for your feedback. PR created!

**Comment by ajcvickers** [comment]
Closing this as the change discussed above has been merged from a PR.
