### ISSUE TITLE
Debugging native/ c code in vs2015 .Net core RC2 .

### ISSUE THREAD

**Issue by PrashanthIBM** [dotnet/corefx#10524]
Hi,

I am using a .Net Core Console App using Visual Studio 2015 update 2 on windows machine. I am using a package "pack1"(managed code) in this console application which in turn calls native / c code dll. I am able to step into pack1 code, but i am not able to step into my native code.

Tried giving symbol path to native code pdb file , enabled native and managed code compatibility option,tried putting breakpoint into the native c source code directly, also tried to step into c code from managed code, but none of them seem to work.

Can some one please help me with this / point to any documentation ?

sample Project.json file :

{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true,
    "defines": [ "DEBUG" ]
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002702"
    },
    "pack1": "1.0.0.0"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  },
  "configurations": {    "debug": { 
    }
  }
}

Thanks and Regards,
Prashanth

**Comment by joshfree** [comment]
@tzwlai can you help route?

**Comment by tzwlai** [comment]
@caslan, could you help with this issue please?

**Comment by PrashanthIBM** [comment]
does any one as any idea about how to solve this issue ?.
I am really struck and appreciate the help ASAP.

**Comment by clrjunkie** [comment]
@PrashanthIBM 

Try this approach: https://github.com/aspnet/Tooling/issues/368

**Comment by PrashanthIBM** [comment]
@gregg-miskelly can you please help

**Comment by PrashanthIBM** [comment]
Any updates ?

**Comment by gregg-miskelly** [comment]
@PrashanthIBM: The .NET Core project system doesn't currently expose an option to do native-only debugging. So, like @clrjunkie said, you will need to do something similar to the approach I suggested in https://github.com/aspnet/Tooling/issues/368. Here are those steps tweaked for apps using dotnet.exe to host:

1. Right click on the solution, Add Existing Project
2. Open 'dotnet.exe'. This is normally installed to 'C:\Program Files\dotnet\dotnet.exe'.
3. You should now see another node in solution explorer for dotnet.exe. Right click it to bring up project properties:
    * Change the working directory to be what you want
    * Change the arguments to be the path to your built dll
6. Change the exe project to your startup project
7. RECOMENDED: Go to Tools->Options->Projects and Solutions->Build and Run, uncheck 'Only build startup projects and dependcies on Run'

@sayedihashimi it might be useful to add an option to the project system to enable this in the future.

**Comment by per-samuelsson** [comment]
@gregg-miskelly 

Really appreciate the time you spend here, trying to help out! But I *think* what @PrashanthIBM is asking for is a debugging experience where you could step (e.g. F11) from managed code into native code (and back). And what you describe here and in https://github.com/aspnet/Tooling/issues/368 is how to debug native code in a managed process, but in *isolation*.

If my assumptions are correct, I'm also trying just like @PrashanthIBM to find a way to accomplish this kind of mixed mode / interop debugging, but with no success.

I remember back in pre-dotnetcore era, VS would allow mixed mode debugging really early in the life of .NET Framework 1.0 (back in 2000), but that this was only supported for a long period of time (years) for 32-bit processes, not 64-bit ditos. And then this got fixed a few years ago, but now with dotnetcore, it seem not to be possible any longer.

The gain of mixed mode / interop debugging is of course to see a full stack, and be able to debug longer sequences without the hazzle of having to attach/detach separate debuggers for every transition. But maybe this is not at all supported for CoreCLR + native at this point?

**Comment by gregg-miskelly** [comment]
@per-samuelsson you are correct -- coreclr doesn't support x64 mixed mode debugging at the moment.
@tzwlai should we port this issue to CoreCLR and have it track enabling x64 mixed mode?

**Comment by per-samuelsson** [comment]
> @per-samuelsson you are correct -- coreclr doesn't support x64 mixed mode debugging at the moment.

Sad to hear. But thanks for giving a clear answer! :+1:

**Comment by danmosemsft** [comment]
@karelz perhaps this should be a feature request against the CLR debugging team, their issues are in coreclr right?

**Comment by karelz** [comment]
@noahfalk @lt72 do you track such request in coreclr repo?

**Comment by tarekgh** [comment]
Issue moved to [dotnet/coreclr #9919](https://github.com/dotnet/coreclr/issues/9919) via [**ZenHub**](https://www.zenhub.com/)
