### ISSUE TITLE
Question about database connection

### ISSUE THREAD

**Issue by zh-wowtv** [dotnet/corefx#10523]
I know MS Sql Server is only running in Windows platform. But if it's possible to run my web app in Linux and connect to my database in Windows?

I got an error message when I tried to use **SqlClient** in my application:

> Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotSupportedException: The keyword 'integrated security' is not supported on this platform.

**Comment by svick** [comment]
That sounds like connecting from Linux to SQL Server on Windows is supported, just not using integrated security. Can you connect to the database with a user name and password instead?

**Comment by saurabh500** [comment]
@zh-wowtv It is possible to connect to your database server running on Windows. However for Linux clients we don't support Integrated Security. There is work in progress to enable Integrated Security on Linux. 
You will need to enable Sql Authentication and login with a Sql username and password from Linux to connect to Sql Server on Windows. 
The issue tracking this capability is at https://github.com/dotnet/corefx/issues/4198

**Comment by zh-wowtv** [comment]
@saurabh500 Thanks for your explanation. I see. But I don't quite understand what the Integrated Security is. Any link about this?

**Comment by saurabh500** [comment]
@zh-wowtv In short Integrated Security is the method of authenticating client applications using the Active Directory with the server using Kerberos or NTLM.
This is guided by the Integrated Security config in the connection string. https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlconnectionstringbuilder.integratedsecurity(v=vs.110).aspx 

More about integrated security for Sql Server here  https://msdn.microsoft.com/en-us/library/bsz5788z.aspx

Let me know if I can answer any other questions.
