### ISSUE TITLE
CoreFx Build Native On Free BSD 10.1 Fails

### ISSUE THREAD

**Issue by ozankiraz** [dotnet/corefx#10533]
Hi,
I could build coreclr successfully, then tried to build corefx, but I had the following :

root@:~/dotnet/corefx # **uname -a**
FreeBSD  10.1-RELEASE FreeBSD 10.1-RELEASE #0 r274401: Tue Nov 11 21:02:49 UTC 2014     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

root@:~/dotnet/corefx # **./build-native.sh**
Unsupported OS 'FreeBSD' detected. Downloading ubuntu-x64 tools.
Installing dotnet cli...
Restoring BuildTools version 1.0.26-prerelease-00629-09...
ELF binary type "0" not known.
/root/dotnet/corefx/init-tools.sh: line 78: /root/dotnet/corefx/Tools/dotnetcli/dotnet: cannot execute binary file: Exec format error
ERROR: Could not restore build tools correctly. See '/root/dotnet/corefx/init-tools.log' for more details.
Initializing BuildTools...
/root/dotnet/corefx/init-tools.sh: line 84: /root/dotnet/corefx/packages/Microsoft.DotNet.BuildTools/1.0.26-prerelease-00629-09/lib/init-tools.sh: No such file or directory
ERROR: An error occured when trying to initialize the tools. Please check '/root/dotnet/corefx/init-tools.log' for more details.

root@:~/dotnet/corefx # **cat init-tools.log**
Running: /root/dotnet/corefx/init-tools.sh
Installing 'https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-002733/dotnet-dev-ubuntu-x64.1.0.0-preview2-002733.tar.gz' to '/root/dotnet/corefx/Tools/dotnetcli/dotnet.tar'
Running: /root/dotnet/corefx/Tools/dotnetcli/dotnet restore "/root/dotnet/corefx/Tools/1.0.26-prerelease-00629-09/project.json" --no-cache --packages /root/dotnet/corefx/packages --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
Running: /root/dotnet/corefx/packages/Microsoft.DotNet.BuildTools/1.0.26-prerelease-00629-09/lib/init-tools.sh /root/dotnet/corefx /root/dotnet/corefx/Tools/dotnetcli/dotnet /root/dotnet/corefx/Tools

**Comment by joshfree** [comment]
cc @mellinoe who is working on a doc for how to bootstrap a new distro for corefx, core-setup, and cli.

**Comment by joshfree** [comment]
related https://github.com/dotnet/corefx/issues/6770

**Comment by ozankiraz** [comment]
Hi,
Let me know if any more info or logs are needed.
Using BSD 10.1 Vmware image, python 2.7.9, cmake 3.7

**Comment by joperezr** [comment]
Hello @ozankiraz, thanks for logging this issue. The problem you are hitting is due to the recent changes on the dev-workflow made by @maririos, where the build-managed/build-native scripts are only fully supported on platforms where the .Net CLI is supported (unfortunately FreeBSD is not one of them). You might still be able to build the native binaries though, and this is by calling [src/Native/build-native.sh](https://github.com/dotnet/corefx/blob/master/src/Native/build-native.sh) script directly, but for this you will have to create a dummy file called `version.c` at corefx/bin/obj with the following contents:
```c
static char sccsid[] __attribute__((used)) = \"@(#)No version information produced\";
```

Let me know if that works out for you as a temp workaround, and we will let you know when we come up with a better support for this.

**Comment by mellinoe** [comment]
> but for this you will have to create a dummy file called version.c at corefx/bin/obj with the following contents:

We should fix whatever is making this necessary, it's pretty annoying. There is some "generateversion" parameter you are supposed to be able to supply, but I don't think it is working correctly.https://github.com/dotnet/corefx/blob/master/src/Native/build-native.sh#L15

**Comment by maririos** [comment]
The parameter `generateversion` is working and it is generating the `version.h` file, but for some reason cmake is not able to find it. 
I'll take a look as this happened after the change I did. I'll update when I have more information.

**Comment by ozankiraz** [comment]
I tried adding line to /bin/obj/version.c and run build native again didn't work :(
 I updated the branch since there are updates #10553 but it didn't work either

./build-native generateversion  didn't generate version.h under /bin/obj,
Actually bin didn't exist in the first place, probably its because compilation didn't started at all

I'll give updates in needed.
Sorry for my late resonses, those overtimes are killing me :(

root@:~/dotnet/corefx # cat init-tools.log                                      Running: /root/dotnet/corefx/init-tools.sh
Installing 'https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-002733/dotnet-dev-ubuntu-x64.1.0.0-preview2-002733.tar.gz' to '/root/dotnet/corefx/Tools/dotnetcli/dotnet.tar'
Running: /root/dotnet/corefx/Tools/dotnetcli/dotnet restore "/root/dotnet/corefx/Tools/1.0.26-prerelease-00629-09/project.json" --no-cache --packages /root/dotnet/corefx/packages --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
Running: /root/dotnet/corefx/packages/Microsoft.DotNet.BuildTools/1.0.26-prerelease-00629-09/lib/init-tools.sh /root/dotnet/corefx /root/dotnet/corefx/Tools/dotnetcli/dotnet /root/dotnet/corefx/Tools
root@:~/dotnet/corefx #

**Comment by mellinoe** [comment]
Are you running the script under src/Native? Running the root build script is not going to work, because FreeBSD is not an officially supported platform, so we don't have published packages for it yet, which the root build script needs. If you run `src/Native/build-native.sh x64 debug freebsd`, you should at the very least get different output.

**Comment by ozankiraz** [comment]
Oh, I'm sorry, I missed that part.
I'll try it when I get back home, probably it'll work :)
Thanks a lot!
