### ISSUE TITLE
Certificate validation when using cURLHandler should look at trusted user store

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/corefx#10534]
Currently, observation is that when using CurlHandler, we look only at the system's root certificate store for trusted CA certificates

We should also have the ability to look at the certs that are stored in ~/.dotnet/corefx/cryptography/x509certificates/*\* (i.e., the user certificate store) to determine whether an endpoint is trusted

Scenario: 
- Install a self-signed root certificate into the corefx user root store 
- Hit a https endpoint using the HttpClient which uses a server certificate signed by the self-signed root certificate 
- Observe that the request fails 
- Install the self-signed root certificate into the root store 
- Observe that the request passes now

**Comment by bartonjs** [comment]
That's.... supposed to be how it works.  Hmm.

**Comment by iamjasonp** [comment]
I'm crafting repro this, so don't look too hard into it yet. 

This was an observation using WCF, but thought I'd get this onto your radar earlier in case there was some known issue

**Comment by iamjasonp** [comment]
@bartonjs - repro here: https://gist.github.com/iamjasonp/f49e2359e4cc9e188f5809b9b3d851ee

**Comment by iamjasonp** [comment]
Perhaps it's related to #10801 ?

**Comment by karelz** [comment]
We think it works (#10801 was fixed). Please reopen if not.

**Comment by iamjasonp** [comment]
cc: @hongdai, putting this on your radar just in case you want to double check
