### ISSUE TITLE
System.Runtime.Serialization.Formatters has no performance tests yet is marked for perf run

### ISSUE THREAD

**Issue by karajas** [dotnet/corefx#10535]
System.Runtime.Serialization.Formatters includes the perf runner but currently does not have performance tests.

https://github.com/dotnet/corefx/blob/53204dc13d67e8266a0e9b88845d13220a69afda/src/System.Runtime.Serialization.Formatters/tests/System.Runtime.Serialization.Formatters.Tests.csproj#L11 

/cc @dsgouda

**Comment by dsgouda** [comment]
Fixed with commit https://github.com/dotnet/corefx/commit/b39944b8bad5d859ff1a5d9e64ec4cc23cfee142
