### ISSUE TITLE
System.Reflection.Metadata should expose a way to get the containing assembly for a given type.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#10549]
Given a type handle you should be able to easily get a handle to the containing assembly. This is required to compute the AssemblyQualifiedName of a type when you only have a type handle.

**Comment by tannergooding** [comment]
FYI. @tmat

**Comment by tmat** [comment]
There are already APIs to find the declaring assembly def/ref. We do not have APIs for getting display name from AssemblyDefinition or AssemblyReference. Perhaps we should add ```AssemblyName GetAssemblyName()``` to both, which can then be queried for display name. That way we avoid reimplementing tricky details of assembly name escaping etc.

**Comment by tmat** [comment]
Replaced by issue https://github.com/dotnet/corefx/issues/13295
