### ISSUE TITLE
ARM64: Microsoft.Win32.RegistryTests failing

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#10546]
```
21:18:59 Discovering: Microsoft.Win32.Registry.Tests
21:18:59 Discovered:  Microsoft.Win32.Registry.Tests
21:18:59 Starting:    Microsoft.Win32.Registry.Tests
21:18:59    Microsoft.Win32.RegistryTests.RegistryKey_CreateSubKey_str.NegativeTests [FAIL]
21:18:59       Assert.Throws() Failure
21:18:59       Expected: typeof(System.IO.IOException)
21:18:59       Actual:   (No exception was thrown)
21:18:59       Stack Trace:
21:18:59             at Microsoft.Win32.RegistryTests.RegistryKey_CreateSubKey_str.NegativeTests()
21:18:59    Microsoft.Win32.RegistryTests.RegistryKey_CreateSubKey_str_rkpc.NegativeTests [FAIL]
21:18:59       Assert.Throws() Failure
21:18:59       Expected: typeof(System.IO.IOException)
21:18:59       Actual:   (No exception was thrown)
21:18:59       Stack Trace:
21:18:59             at Microsoft.Win32.RegistryTests.RegistryKey_CreateSubKey_str_rkpc.NegativeTests()
21:18:59 Finished:    Microsoft.Win32.Registry.Tests
21:18:59 
21:18:59 === TEST EXECUTION SUMMARY ===
21:18:59    Microsoft.Win32.Registry.Tests  Total: 939, Errors: 0, Failed: 2, Skipped: 0, Time: 
```

**Comment by ianhays** [comment]
cc: @rahku, @kyulee1

**Comment by justinvp** [comment]
I'm seeing the same two test failures when running the tests locally on Windows 10 Anniversary Update (build 14393.51) x64.

**Comment by JeremyKuhne** [comment]
@ianhays - I've got multiple confirmations that this fails on Win10 Anniversary Update. It looks like the limitation may have been relaxed. Can you disable these if you can't get to them right away so we can get clean builds on Win10?

**Comment by alexperovich** [comment]
@ianhays is there any value in fixing these tests? What value do we get in testing that the windows limits haven't changed?

**Comment by ianhays** [comment]
If the limitation is no longer present, then the test shouldn't exist anymore. 

Even if the limitation was present, I agree that it isn't testing what we want it to. I'll push a PR removing them.

**Comment by danmosemsft** [comment]
@ianhays OK thne assigned to you

**Comment by ianhays** [comment]
Thanks Dan, I actually already removed these in https://github.com/dotnet/corefx/pull/18566, just forgot to link the issue :)
