### ISSUE TITLE
Missing stdout line while redirect process stdout

### ISSUE THREAD

**Issue by TingluoHuang** [dotnet/corefx#10550]
I make a console app that using Diagnostic.Process to call `/usr/bin/git` with argument `version`, then redirect STDOUT and STDERR to get the git version info.

However, i got empty string from STDOUT/STDERR of git version sometime.
In order to investigate, i made a console app that siting in a loop invoke `git version` until it get empty output from `git version`.
I also made a bash script that also invoke `git version` in a loop till it hit empty then exit, so i can figure out this is a git issue or dotnet core issue.

So far, the test bash script is able to run for hours without find `git version` return empty. However my dotnet core app sometime will get empty string on STDOUR redirect, which make me feel this is more like a dotnet core issue. 

here is the code of my console app that using Diagnostic.Process to invoke process and redirect STDOUT,
[gitversion.txt](https://github.com/dotnet/corefx/files/400242/gitversion.txt)

Can someone help me take a look, did i do something wrong in the code or it's a real issue with dotnet core?
I am able to repro on Ubuntu 14 and 16, not repro on windows, haven't try OSX since i don't have a Mac.

Thanks,

**Comment by TingluoHuang** [comment]
Any updates? i am continue hitting this issue.

**Comment by Priya91** [comment]
Upon investigating, the code is redirecting both standard input and output to the same object ```output```. When the error stream is written first to output the ```output.FirstOrDefault``` is null. Repeating the same program removing the Stderror to ```output``` doesn't produce the exception.

**Comment by TingluoHuang** [comment]
@Priya91 
it getversion() is return output.FirstOrDefault(o => !string.IsNullOrEmpty(o));
the first not null and empty string. when it repro, i am able to 3 empty string in the output list.

**Comment by Priya91** [comment]
@TingluoHuang 
I used the following code and ran for 10 mins on Ubuntu16.04, didn't hit the case on 2 null strings. Can you share more debugging info when the exception is hit

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            string res = null;
            while (res == null)
            {
                res = getversion();
                if (string.IsNullOrEmpty(res))
                {
                    break;
                }
                res = null;
            }
        }

        private static string getversion()
        {
            List<string> output = new List<string>();
            Process p = new Process();
            p.StartInfo.FileName = "/usr/bin/git";
            p.StartInfo.Arguments = "version";
            p.StartInfo.UseShellExecute = false;
            p.StartInfo.RedirectStandardOutput = true;
            p.StartInfo.RedirectStandardInput = true;
            p.StartInfo.CreateNoWindow = true;
            p.OutputDataReceived += new DataReceivedEventHandler((sender, e) =>
            {
                output.Add(e.Data);
            });

            p.Start();
            p.BeginOutputReadLine();
            p.WaitForExit();
            p.Dispose();

            Console.Write(output.Count+ " ");
            Console.WriteLine(string.Join(",", output));

            return output.FirstOrDefault(o => !string.IsNullOrEmpty(o));
        }
    }
}
```

**Comment by TingluoHuang** [comment]
@Priya91 Looks like a bug in my code, i need add lock around output.add().
