### ISSUE TITLE
Needs to refactor code for option 'restrict-proj' in run-test.sh

### ISSUE THREAD

**Issue by YongseopKim** [dotnet/corefx#10563]
run-test.sh accepts a parameter, regex for an option restrict-proj.
The regex is used as $TestSelection in run_test().

``` bash
# $1 is the path to the test folder
 run_test()
 {
   testProject=`basename $1`

   # Check for project restrictions

   if [[ ! $testProject =~ $TestSelection ]]; then
     echo "Skipping $testProject"
     exit 0
   fi  
  // ...
}
```

Above function, run_test() executes after run_all_tests().

``` bash
 # $1 is the name of the platform folder (e.g Unix.AnyCPU.Debug)
 run_all_tests()
 {
   for testFolder in "$CoreFxTests/$1/"*
   do  
      run_test $testFolder &
      pids="$pids $!"
      numberOfProcesses=$(($numberOfProcesses+1))
      if [ "$numberOfProcesses" -ge $maxProcesses ]; then
        wait_on_pids "$pids"
        numberOfProcesses=0
        pids=""
      fi  
   done

   # Wait on the last processes
   wait_on_pids "$pids"
   pids=""
 }
```

I think it's better that moving $TestSelection in run_test() into run_all_tests() and then using it with command 'find'.

I'd like to know your opinion.

**Comment by stephentoub** [comment]
@maririos, who should this be assigned to instead?

**Comment by maririos** [comment]
Yes, once we have someone else I'll reassign it.

**Comment by mellinoe** [comment]
I'm not sure it's interesting to invest in run-tests.sh anymore. Can we just close this and try to get everyone using the same build and test infrastructure?
