### ISSUE TITLE
Add benchmark suite for System.Linq.Expressions

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#10561]
I'm starting to look into some performance aspects of the expression tree interpreter and will need a `Performance` test project for it. An attempt to create it using a carbon copy from other projects with such a `Performance` project ran into some issues on referencing the `pkg`, so I'm adding an issue to track progress on this. If anyone with more awareness of the benchmark infrastructure could help out here, that'd be useful too.

**Comment by joshfree** [comment]
@schaabs @lt72

**Comment by stephentoub** [comment]
cc: @adamsitnik

**Comment by adamsitnik** [comment]
@danmosemsft should we move this issue to the performance repo?

**Comment by stephentoub** [comment]
@adamsitnik, yes please.  Looks like I don't have admin rights to the perf repo so the GitHub transfer issue link doesn't work for me on this.

**Comment by brianrob** [comment]
I don't even think we need to move the issue.  @bartdesmet you can add tests to https://github.com/dotnet/performance/tree/master/src/benchmarks/micro/corefx - just create a new directory called System.Linq.Expressions.  There are lots of examples here if you want to start with something pre-existing.

**Comment by stephentoub** [comment]
> I don't even think we need to move the issue

We should either close it or move it, as it's not relevant to the corefx repo anymore :)

**Comment by danmosemsft** [comment]
@brianrob I don't follow your reasoning 😸 The necessary change is in the dotnet/performance repo, as you point out. As a rule, we track work for repo X in repo X itself - otherwise things start getting confusing fast. I believe this issue should move to the perf repo.

**Comment by brianrob** [comment]
I guess what I'm saying is that there isn't an action we need to take in the performance repo, this issue essentially represents a question. The benchmarks can just be added to the performance repo.  If you want to move the issue, that's fine and then I can add my comment above and close it.  Alternatively, we can close it here now.

**Comment by danmosemsft** [comment]
Ah right thanks Brian. OK @adamsitnik sounds like you can move or close as you think best.

**Comment by adamsitnik** [comment]
it turns out that to transfer an issue between two repos you need to be admin for both. I am one for dotnet/performance but not for dotnet/corefx so I just created a new one: https://github.com/dotnet/performance/issues/388
