### ISSUE TITLE
[Add Test] T:System.Xml.Serialization.XmlSerializerFactory 

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#10570]

**Comment by shmao** [comment]
The API is added in netstandard2.0, see https://github.com/dotnet/standard/blob/master/netstandard/ref/System.Xml.cs

And PR #12017 is adding the API in CoreFx. We would need to add tests for the API.

**Comment by shmao** [comment]
@huanwu , can you please close the issue if we already have tests for the APIs? Thanks.

**Comment by huanwu** [comment]
Fix by #11363
