### ISSUE TITLE
[Add Test] T:System.Xml.Serialization.XmlSerializerAssemblyAttribute 

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#10574]

**Comment by shmao** [comment]
The API is added in netstandard2.0, see https://github.com/dotnet/standard/blob/master/netstandard/ref/System.Xml.cs

And PR #12017 is adding the API in CoreFx. We would need to add tests for the API.

**Comment by shmao** [comment]
A test for this was added by @huanwu with PR #13445.

**Comment by shmao** [comment]
@huanwu , can you please investigate the scenario of actually using this attribute? Does it make sense for us to support that scenario on NetCore. Thanks.

**Comment by huanwu** [comment]
The NetCore currently doesn't support this scenario.
