### ISSUE TITLE
[Add Test] T:System.Xml.Serialization.XmlSerializationWriter 

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#10577]
T:System.Xml.Serialization.XmlSerializationWriter
T:System.Xml.Serialization.XmlSerializationReader
T:System.Xml.Serialization.XmlSerializationGeneratedCode
T:System.Xml.Serialization.XmlSerializerImplementation

**Comment by weshaggard** [comment]
@shmao do you plan on doing all these API's one at a time? My assumption is no in which case I would suggest having one issue tracking the set of work you will be doing together as opposed to an issue per API.

**Comment by shmao** [comment]
@weshaggard  we divided the missing APIs into some small groups. Each issue here is for tracing a small set of APIs. For example, issue https://github.com/dotnet/corefx/issues/10572 and issue https://github.com/dotnet/corefx/issues/10579 both include several APIs. 

What do you think about this approach? Do you prefer we put all of them in one issue?

**Comment by weshaggard** [comment]
My preference would be to try and have one issue per PR of work you are going to submit.

**Comment by shmao** [comment]
Got it. Yeah, each of these issues was opened for tracking a PR of work.

**Comment by shmao** [comment]
The API is added in netstandard2.0, see https://github.com/dotnet/standard/blob/master/netstandard/ref/System.Xml.cs

And PR #12017 is adding the API in CoreFx. We would need to add tests for the API.

**Comment by masaeedu** [comment]
@shmao Which version of NETStandard.Library is this exposed in? The implicitly referenced NETStandard.Library for SDK version 2.0.0-alpha-004778 does not seem to have this.

**Comment by shmao** [comment]
@masaeedu The APIs are available in NetStandard2.0. I checked the latest [daily build](https://github.com/dotnet/core-setup#daily-builds). The APIs are available there.

**Comment by masaeedu** [comment]
@shmao I've set up a repro of the issue I'm seeing in `git@gitlab.com:masaeedu/netstandard2_wcf_problems.git`. Could you clone that and try to restore + build?

**Comment by shmao** [comment]
@masaeedu Sure. Can you share an Https Url to your repo with me? I had trouble accessing your repo using the Url above.

**Comment by shmao** [comment]
@masaeedu Sure. Can you please grant me permission to access your repo? I'm getting the following error,

> fatal: unable to access 'https://gitlab.com/masaeedu/netstandard2_wcf_problems.git/': The requested URL returned error: 403

**Comment by masaeedu** [comment]
Sorry, I'll check as soon as I'm back at my desk. Could you try visiting
https://gitlab.com/masaeedu/netstandard2_wcf_problems ?

**Comment by shmao** [comment]
I'm getting the same error as above. I'm no sure if I had access to the repo. FYI, My username on GitLab is maoxing330.

**Comment by masaeedu** [comment]
@shmao Alright, I'm pretty sure I've set the project permissions to as permissive as they can be, and have added you as a contributor just in case 😄. Thanks for your patience.

**Comment by shmao** [comment]
@masaeedu Cool. I confirmed I was able to clone the repo. Thanks :)  

I will try restore + build.

**Comment by shmao** [comment]
@masaeedu I tried building your app, but it failed with numerous errors. But I was able to follow the [instruction](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md) and create a new app and use one of the new added APIs. Here's the configuration in my csproj file,

```Xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeFrameworkVersion>2.0.0-beta-001486-00</RuntimeFrameworkVersion>
  </PropertyGroup>
</Project>
```

Then I put the following configuration into your app's csproj file and the build succeeded.

```Xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!--<TargetFramework>netstandard2.0</TargetFramework>
    <NetStandardImplicitPackageVersion>2.0.0-beta-25006-01</NetStandardImplicitPackageVersion>
    -->
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeFrameworkVersion>2.0.0-beta-001486-00</RuntimeFrameworkVersion>
  </PropertyGroup>
</Project>
```

**Comment by masaeedu** [comment]
@shmao Yes, it was exploding for me as well, I am trying to understand how to make it work. I am assuming you generated yours using `dotnet new`, whereas I generated mine using `dotnet new -t lib`. I need a .NET Standard class library project that I can reference in other projects (e.g. in a .NET 4.6.1 console application), so an executable targeting the `netcoreapp` runtime would not work.

**Comment by shmao** [comment]
The above config I used in your app csproj should build the app as an .dll (it did for me).
