### ISSUE TITLE
Add Windows 7 coverage to Jenkins / Outerloop runs

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#1058]
Currently build.cmd no longer passes on Windows 7 machines (see https://github.com/dotnet/corefx/issues/1044).  We should look into adding Win7 coverage to Jenkins to ensure we don't regress building or running tests on this platform.

**Comment by weshaggard** [comment]
@mmitche it would be great to get a Win7 build going so we can stop regressing those scenarios.

**Comment by mmitche** [comment]
@joshfree @weshaggard Martin Woodward is on the hook to figure out about getting Win7 into our Azure subscription.  I pinged him today.  If we don't have something soon I'll set up a non-VM CI machine early next week.

**Comment by martinwoodward** [comment]
I've put in the application to get an MSDN account but it'll not arrive until Wednesday at the earliest. Do you need me to set up a separate Windows 7 Enterprise SP1 machine under my personal subscription in the meantime?

**Comment by mmitche** [comment]
@martinwoodward we can wait.

**Comment by mmitche** [comment]
@martinwoodward DId this get resolved yet?

**Comment by martinwoodward** [comment]
Sorry folks - apparently it got stuck because I hadn't ordered it correctly. I just re-ordered and got confirmation it should come with-in 2 business days from now.

**Comment by eatdrinksleepcode** [comment]
Any update on this? I just pulled for this first time in a month or so and have 5 different test projects failing on Win7.

**Comment by joshfree** [comment]
closing this issue since @ellismg added automated win7 coverage to jenkins earlier this month

**Comment by weshaggard** [comment]
For completeness @ellismg can you point us to the Win7 jobs?

**Comment by stephentoub** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_outerloop_windows_win7_debug/

http://dotnet-ci.cloudapp.net/job/dotnet_corefx_outerloop_windows_win7_release/
