### ISSUE TITLE
Implement File.Replace() as a documented safe atomic API

### ISSUE THREAD

**Issue by binki** [dotnet/corefx#10583]
See the real framework.

```
namespace System.IO
{
    public static class File
    {
        public static void Replace(string source, string destination, string backup);
        public static void Replace(string source, string destination, string backup, bool ignoreMetadataErrors);
    }
}
```
## Implementation

On Windows this should directly delegate to the `ReplaceFile()` API which is [guaranteed atomic wrt `source` and `destination` by this wording of the win32 API](https://msdn.microsoft.com/en-us/library/windows/desktop/hh802690%28v=vs.85%29.aspx#applications_updating_a_single_file_with_document-like_data).

On POSIX (which, really, Windows should hurry up and start implementing… grr…), it should:
1. If `backup` is not `null`:
   1. `unlink(backup)`, ignoring `ENOENT` error but for other failures throw `IOException`.
   2. `link(destination, backup)` and if that fails throw `IOException`.
2. If `backup` is `null`
   1. `stat(destination)`, if `ENOENT` throw `IOException`.
3. `rename(source, destination)` and if that fails throw `IOException`.

This guarantees that the file at `destination` never ceases to exist even with program termination or power failure. The `backup` feature is best effort on POSIX any existing file is not guaranteed to be restored if the later steps fail. However, if `backup` is specified but does not exist, failure at a later step will not cause any data loss—it will just leave behind a second link to `destination` at the path `backup`. And a future call/retry would just wipe away and recreate this `backup`.

Example C for all but step 2 which I should fix: https://gist.github.com/binki/e40182e4098d9714a609918908c623b8 , see [related mono bug #43062 I also opened](https://bugzilla.xamarin.com/show_bug.cgi?id=43062).

**Comment by karelz** [comment]
@JeremyKuhne can you please provide guidance?

**Comment by JeremyKuhne** [comment]
I'm fine with the suggestion. Bringing the Unix implementation up to the Win32 level (we call ReplaceFile()) makes sense.

The current Unix code:
https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/UnixFileSystem.cs#L42

**Comment by binki** [comment]
Wow, the linked current implementation is scary-looking. Mono uses `rename()` at least, so it will never partially copy a file. Mono’s only fault is that it is possible for `destination` to cease to exist if the program is halted. I’m pretty sure that most people who call `System.IO.File.ReplaceFile()` do so *because* it’s the only way that .net exposes something like POSIX’s `rename()`…

(OK, it’s not quite that simple. To get something like POSIX’s `rename()`, you have to conditionally call either `File.Move()` if the destination doesn’t exist or `File.Replace()` if the destination exists (in fact, that’s another disparity between .net and the current corefx implementation—the current corefx implementation looks like it will run even if `destination` doesn’t exist prior to being called. Such an implementation will make it easy for unix users to write code that won’t run on Windows (which requires `destination` to exist when using `ReplaceFile()` IIRC))). Sorry, I haven’t had a chance to actually test out my criticisms, just reading the linked code ;-).

**Comment by stephentoub** [comment]
The implementation was only recently added as a quick-and-dirty placeholder. Please feel free to submit a PR to put something better in place.
