### ISSUE TITLE
System.Net.* Tests require special compilation rules because of System.Net.Internals

### ISSUE THREAD

**Issue by karajas** [dotnet/corefx#10600]
System.Net.\* Tests utilizes an internal namespace, System.Net.Internals. Certain NETStandard.Library dependencies like System.Net.Sockets need to be excluded from compile (they are a dependency of xunit rtm).

**Comment by karajas** [comment]
See discussion on https://github.com/dotnet/corefx/pull/10582. /cc @weshaggard

**Comment by karajas** [comment]
cc @davidsh @CIPop

**Comment by CIPop** [comment]
@karajas I've added some context in the original PR. Please add more detail on why this is happening now.

**Comment by karajas** [comment]
This error could not be pragma disabled, as it is an actual compile time error, this requires further restructuring of either the xunit dependencies or the System.Net.Internals namespace.

**Comment by mellinoe** [comment]
@karajas Are you still looking at this, and do we have a plan going forward or do we need more input on possible options?

**Comment by karajas** [comment]
No resolution at the moment, probably require more information as to what are the actual build dependencies.

**Comment by CIPop** [comment]
@karajas, closing this now since it's very old and I see XUnit working at this time.
Also, it sounds like a circular dependency issue: in general one shouldn't need to change production code to accommodate testing infrastructure.
