### ISSUE TITLE
Missing pointer-based overloads for System.Text.Encoder

### ISSUE THREAD

**Issue by roji** [dotnet/corefx#10618]
.NET Framework has had pointer-based overloads on System.Text.Encoder for quite a while (https://msdn.microsoft.com/en-us/library/system.text.encoder%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396). `Convert`, for example, allows efficiently writing a big string in chunks to byte buffers, etc.

Unfortunately these seem to be missing from .NET Core (https://docs.microsoft.com/en-us/dotnet/core/api/system.text.encoder). This is a big problem for programs that need efficient text operations.

**Comment by mellinoe** [comment]
I believe that adding these members back is tracked by https://github.com/dotnet/corefx/issues/9583

**Comment by roji** [comment]
@mellinoe you're right, I actually saw that issue but somehow missed the pointer overloads. Thanks.
