### ISSUE TITLE
class Stream/MemoryStream have not Close() method, why?

### ISSUE THREAD

**Issue by Microshaoft** [dotnet/corefx#10626]
class Stream/MemoryStream have not Close() method, why?

**Comment by jasonwilliams200OK** [comment]
#10038 added `Close()` method to `Stream` type.

**Comment by benaadams** [comment]
Was a duplication of Dispose() which you can use automatically via using
```csharp
using (var ms = new MemoryStream())
{
// ...
} // automatically Disposed(Closed) here
```
or directly call
```csharp
var ms = new MemoryStream();
// ...
ms.Dispose() // Closed here
```
It has been brought back for compat

**Comment by danmosemsft** [comment]
As @jasonwilliams200OK mentions above this came back on STream and thus MemoryStream - currently in the dev/api branch.
