### ISSUE TITLE
Support System.Xml.Schema.XmlSchema and Related APIs

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#10656]
In CoreCLR currently there is only a place-holder for XmlSchema type. 

https://github.com/dotnet/corefx/issues/10573 is being blocked by the issue.

**Comment by krwq** [comment]
System.Private.Xml is already here and includes schema. We still need System.Xml facade but we have some packaging issues to solve with that ( https://github.com/NuGet/Home/issues/3167 )

**Comment by danmosemsft** [comment]
@sepidehMS What actually remains here? If it's just the packaging of the ref assembly, please close.

**Comment by sepidehMS** [comment]
@shmao System.Xml.Schema is now available on master in System.Private.Xml. You can reference that until System.Xml facade becomes available as well.
Closing this for now.
