### ISSUE TITLE
3 Issues with NET Core Visual Studio Projects.

### ISSUE THREAD

**Issue by MelbourneDeveloper** [dotnet/corefx#10657]
Could someone please have a look at the issues I've mentioned here:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/0b8ed5a8-db75-4cbc-85dc-32621a6c749d/net-core-xproj-problems?forum=visualstudiogeneral

The first 2 problems I see as actual bugs. 1 is that conditional compilation symbols don't work in .NET Core projects. The second is that we can't exclude files from the project. This means that I can't get any of our existing code that compiles for Silverlight, NET, UWP to compile in .NET Core.

Also, there is a design flaw with Visual Studio projects that I don't think you can do anything about. All projects have a project.json which means that two projects can't share a folder. This isn't a big problem for csproj projects because we can link files in from anywhere. But, in xproj format, it totally screws everything up because we need to make physical copies of all the files - i.e. it makes it literally impossible to share code.

**Comment by MelbourneDeveloper** [comment]
I've logged the first issue with Microsoft Connect here:
https://connect.microsoft.com/VisualStudio/feedbackdetail/view/2983351/conditional-compilation-symbols-broken-in-net-core-projects

**Comment by joshfree** [comment]
I've moved this issue to https://github.com/dotnet/cli/issues/4022 for further discussion

**Comment by jasonwilliams200OK** [comment]
Also, @MelbourneDeveloper, the xproj are going away in favor of updated csproj in near future, which will have all the goodness of xproj and project.json (ability to black-listinstead of white-list every source file, new way of defining the post/pre build/publish events etc.). Under the hood, the new project system is coming: https://github.com/dotnet/roslyn-project-system. You can try it out today and provide feedback at https://github.com/dotnet/roslyn-project-system/issues. :)

Reference: https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/

**Comment by MelbourneDeveloper** [comment]
Had anyone looked at my issues? Will someone please acknowledge the issues?

**Comment by MelbourneDeveloper** [comment]
I'm petrified of the xproj format. 2 of the problems I've reported mean that we can't compile our code for .NET Core because of the xproj format. The last problem I mentioned means that we can't share code files across multiple platforms. I really hope that someone catches on to these problems before it is too late.

**Comment by MelbourneDeveloper** [comment]
I have logged one of my problems here:
https://github.com/aspnet/Tooling/issues/723
