### ISSUE TITLE
PERF: ImmutableArray<T>.Builder.Contains is inefficient

### ISSUE THREAD

**Issue by pharring** [dotnet/corefx#1066]
System.Collections.Immutable.RefAsValueType<T> is a struct that does not override Equals (or GetHashCode).

which means, when the default equality comparer is created, it'll use the generic object equality comparer. For structs, that means boxing. It also means the default ValueType.Equals implementation which is pretty bad.

This doesn't affect ImmutableArray, but it does affect the Builder. You hit this if you call .Contains or .IndexOf on a Builder (with the default EqualityComparer). What's interesting is that we special-case the code-path for using the default comparer and it's this code path that gets us into trouble. I believe we should just remove that clause. Here: [ImmutableArray`1+Builder.cs (517-520)] (https://github.com/dotnet/corefx/blob/7116584186f8f3a886616aaf8cb5d4a982c60e27/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray%601%2BBuilder.cs#L517-L520)

**Comment by pharring** [comment]
Here's the call-stack from Roslyn that hits this code path:

    Name                                                                                                                                                                               	Inc %
    mscorlib.ni!System.ValueType.Equals(System.Object)                                                                                                                                	  1.2
    + mscorlib!System.Collections.Generic.ObjectEqualityComparer`1[System.Collections.Immutable.RefAsValueType`1[System.__Canon]].IndexOf(!0[],!0,int32,int32)                         	  1.2
     + mscorlib!System.Array.IndexOf(!!0[],!!0,int32,int32)                                                                                                                            	  1.2
      + system.collections.immutable!System.Collections.Immutable.ImmutableArray`1+Builder[System.__Canon].IndexOf(!0,int32,int32,class System.Collections.Generic.IEqualityComparer`1)	  1.2
       + microsoft.codeanalysis.csharp!CSharpSemanticModel.AddReducedAndFilteredMethodGroupSymbol                                                                                      	  1.2

**Comment by pharring** [comment]
If you click through the implementation of Array.IndexOf, it ultimately calls the internal EqualityComaprer<T>.Default.IndexOf which does [precisely what you'd expect](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/EqualityComparer.cs#L94-L100). Nothing fancy.

**Comment by mikedn** [comment]
But how did RefAsValueType got into the picture? As far as I can tell the builder uses a `T[]`, not a `RefAsValueType<T>[]`: [ImmutableArray`1+Builder.cs:25](https://github.com/dotnet/corefx/blob/future/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray%601+Builder.cs#L25)

**Comment by stephentoub** [comment]
@pharring, is Roslyn using an older immutable collections library?  The builder was changed not to use RefAsValueType back in early December by @jaredpar: https://github.com/dotnet/corefx/commit/61f778dbaa2d0cc088004b8a277e5e48c5a8206e#diff-d65eea42153aaa3fdaa96c5c11585e70L25 .  From a cursory search, it looks like the only place a RefAsValueType is now used is within a Stack<RefAsValueType<T>>.

**Comment by sharwell** [comment]
The change in 61f778d will be included in the RC release of the immutable collections library, but was not part of the 1.0.32 release (Roslyn beta 2 release) or 1.0.33 release (Roslyn RC 1 release).

**Comment by pharring** [comment]
Ah, right you are. I've been using VS 2015 CTP 6 which includes version 1.0.33.
Thanks for the quick response.
