### ISSUE TITLE
System.Transactions - Add EventSource instead of using trace logging

### ISSUE THREAD

**Issue by dmetzgar** [dotnet/corefx#10678]
System.Transactions uses some very old code that writes via a custom XmlWriter to a trace file. This file does not appear to be consumed by any tools and is meant for people to read directly. This can be replaced with an EventSource, which has several advantages:
- does not require stopping the process to change config 
- events can be mixed with events from other providers so it's easier to debug
- no issues with log files getting too large and needing to be rolled over

**Comment by qizhanMS** [comment]
Finished.
