### ISSUE TITLE
Remove unnecessary P2P references relating to xml contracts

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#10688]
when merging #10672 , we introduced a lot of P2P references, since it was required for some libraries that depended on un-published packages. This issue is to track the work to remove all those.

**Comment by joperezr** [comment]
This are the csproj dependencies that were added:
F:\git\corefx\src\Common\tests\System\Xml\XmlCoreTest\XmlCoreTest.csproj has a P2P dependency to ModuleCore.csproj
F:\git\corefx\src\Common\tests\System\Xml\XmlCoreTest\XmlCoreTest.csproj has a P2P dependency to XmlDiff.csproj
F:\git\corefx\src\Common\tests\System\Xml\XmlCoreTest\XmlCoreTest.csproj has a P2P dependency to System.Xml.ReaderWriter.csproj
F:\git\corefx\src\Common\tests\System\Xml\XmlCoreTest\XmlCoreTest.csproj has a P2P dependency to System.Private.Xml.csproj
F:\git\corefx\src\Common\tests\System\Xml\XmlDiff\XmlDiff.csproj has a P2P dependency to ModuleCore.csproj
F:\git\corefx\src\Common\tests\System\Xml\XmlDiff\XmlDiff.csproj has a P2P dependency to System.Xml.ReaderWriter.csproj
F:\git\corefx\src\Common\tests\System\Xml\XmlDiff\XmlDiff.csproj has a P2P dependency to System.Private.Xml.csproj
F:\git\corefx\src\System.Private.Xml\tests\Readers\CharCheckingReader\System.Xml.RW.CharCheckingReader.Tests.csproj has a P2P dependency to ModuleCore.csproj
F:\git\corefx\src\System.Private.Xml\tests\Readers\CharCheckingReader\System.Xml.RW.CharCheckingReader.Tests.csproj has a P2P dependency to XmlCoreTest.csproj
F:\git\corefx\src\System.Private.Xml\tests\Readers\CharCheckingReader\System.Xml.RW.CharCheckingReader.Tests.csproj has a P2P dependency to System.Xml.RW.XmlReaderLib.csproj
F:\git\corefx\src\System.Private.Xml\tests\Readers\CustomReader\System.Xml.RW.CustomReader.Tests.csproj has a P2P dependency to ModuleCore.csproj
F:\git\corefx\src\System.Private.Xml\tests\Readers\CustomReader\System.Xml.RW.CustomReader.Tests.csproj has a P2P dependency to XmlCoreTest.csproj
F:\git\corefx\src\System.Private.Xml\tests\Readers\CustomReader\System.Xml.RW.CustomReader.Tests.csproj has a P2P dependency to System.Xml.RW.XmlReaderLib.csproj
F:\git\corefx\src\System.Private.Xml\tests\Readers\FactoryReader\System.Xml.RW.FactoryReader.Tests.csproj has a P2P dependency to ModuleCore.csproj
F:\git\corefx\src\System.Private.Xml\tests\Readers\FactoryReader\System.Xml.RW.FactoryReader.Tests.csproj has a P2P dependency to XmlCoreTest.csproj
F:\git\corefx\src\System.Private.Xml\tests\Readers\FactoryReader\System.Xml.RW.FactoryReader.Tests.csproj has a P2P dependency to System.Xml.RW.XmlReaderLib.csproj
F:\git\corefx\src\System.Private.Xml\tests\Readers\NameTable\System.Xml.RW.NameTable.Tests.csproj has a P2P dependency to ModuleCore.csproj
F:\git\corefx\src\System.Private.Xml\tests\Readers\NameTable\System.Xml.RW.NameTable.Tests.csproj has a P2P dependency to XmlCoreTest.csproj
F:\git\corefx\src\System.Private.Xml\tests\Readers\NameTable\System.Xml.RW.NameTable.Tests.csproj has a P2P dependency to System.Xml.RW.XmlReaderLib.csproj
F:\git\corefx\src\System.Private.Xml\tests\Readers\ReaderSettings\System.Xml.RW.ReaderSettings.Tests.csproj has a P2P dependency to BaseLibManaged.csproj
F:\git\corefx\src\System.Private.Xml\tests\Readers\ReaderSettings\System.Xml.RW.ReaderSettings.Tests.csproj has a P2P dependency to ModuleCore.csproj
F:\git\corefx\src\System.Private.Xml\tests\Readers\ReaderSettings\System.Xml.RW.ReaderSettings.Tests.csproj has a P2P dependency to XmlCoreTest.csproj
F:\git\corefx\src\System.Private.Xml\tests\Readers\ReaderSettings\System.Xml.RW.ReaderSettings.Tests.csproj has a P2P dependency to System.Xml.RW.XmlReaderLib.csproj
F:\git\corefx\src\System.Private.Xml\tests\Readers\SubtreeReader\System.Xml.RW.SubtreeReader.Tests.csproj has a P2P dependency to ModuleCore.csproj
F:\git\corefx\src\System.Private.Xml\tests\Readers\SubtreeReader\System.Xml.RW.SubtreeReader.Tests.csproj has a P2P dependency to XmlCoreTest.csproj
F:\git\corefx\src\System.Private.Xml\tests\Readers\SubtreeReader\System.Xml.RW.SubtreeReader.Tests.csproj has a P2P dependency to System.Xml.RW.XmlReaderLib.csproj
F:\git\corefx\src\System.Private.Xml\tests\Readers\WrappedReader\System.Xml.RW.WrappedReader.Tests.csproj has a P2P dependency to ModuleCore.csproj
F:\git\corefx\src\System.Private.Xml\tests\Readers\WrappedReader\System.Xml.RW.WrappedReader.Tests.csproj has a P2P dependency to XmlCoreTest.csproj
F:\git\corefx\src\System.Private.Xml\tests\Readers\WrappedReader\System.Xml.RW.WrappedReader.Tests.csproj has a P2P dependency to System.Xml.RW.XmlReaderLib.csproj
F:\git\corefx\src\System.Private.Xml\tests\Writers\RwFactory\System.Xml.RW.RwFactory.Tests.csproj has a P2P dependency to ModuleCore.csproj
F:\git\corefx\src\System.Private.Xml\tests\Writers\RwFactory\System.Xml.RW.RwFactory.Tests.csproj has a P2P dependency to XmlCoreTest.csproj
F:\git\corefx\src\System.Private.Xml\tests\Writers\RwFactory\System.Xml.RW.RwFactory.Tests.csproj has a P2P dependency to System.Private.Xml.Linq.csproj
F:\git\corefx\src\System.Private.Xml\tests\Writers\RwFactory\System.Xml.RW.RwFactory.Tests.csproj has a P2P dependency to System.Xml.ReaderWriter.csproj
F:\git\corefx\src\System.Private.Xml\tests\Writers\RwFactory\System.Xml.RW.RwFactory.Tests.csproj has a P2P dependency to System.Xml.XDocument.csproj
F:\git\corefx\src\System.Private.Xml\tests\Writers\XmlWriterApi\System.Xml.RW.XmlWriterApi.Tests.csproj has a P2P dependency to ModuleCore.csproj
F:\git\corefx\src\System.Private.Xml\tests\Writers\XmlWriterApi\System.Xml.RW.XmlWriterApi.Tests.csproj has a P2P dependency to XmlCoreTest.csproj
F:\git\corefx\src\System.Private.Xml\tests\XmlConvert\System.Xml.RW.XmlConvert.Tests.csproj has a P2P dependency to ModuleCore.csproj
F:\git\corefx\src\System.Private.Xml\tests\XmlConvert\System.Xml.RW.XmlConvert.Tests.csproj has a P2P dependency to XmlCoreTest.csproj
F:\git\corefx\src\System.Private.Xml\tests\XmlReaderLib\System.Xml.RW.XmlReaderLib.csproj has a P2P dependency to ModuleCore.csproj
F:\git\corefx\src\System.Private.Xml\tests\XmlReaderLib\System.Xml.RW.XmlReaderLib.csproj has a P2P dependency to XmlCoreTest.csproj
F:\git\corefx\src\System.Private.Xml\tests\XmlReaderLib\System.Xml.RW.XmlReaderLib.csproj has a P2P dependency to System.Xml.ReaderWriter.csproj
F:\git\corefx\src\System.Private.Xml\tests\XmlSerializer\System.Xml.XmlSerializer.Tests.csproj has a P2P dependency to System.Private.Xml.Linq.csproj
F:\git\corefx\src\System.Private.Xml\tests\XmlSerializer\System.Xml.XmlSerializer.Tests.csproj has a P2P dependency to System.Private.DataContractSerialization.csproj
F:\git\corefx\src\System.Private.Xml\tests\XmlSerializer\System.Xml.XmlSerializer.Tests.csproj has a P2P dependency to System.Runtime.Serialization.Primitives.csproj
F:\git\corefx\src\System.Private.Xml\tests\XmlSerializer\System.Xml.XmlSerializer.Tests.csproj has a P2P dependency to System.Xml.ReaderWriter.csproj
F:\git\corefx\src\System.Private.Xml\tests\XmlSerializer\System.Xml.XmlSerializer.Tests.csproj has a P2P dependency to System.Xml.XmlDocument.csproj
F:\git\corefx\src\System.Private.Xml\tests\XmlSerializer\System.Xml.XmlSerializer.Tests.csproj has a P2P dependency to System.Xml.XDocument.csproj
F:\git\corefx\src\System.Private.Xml\tests\XmlSerializer\Performance\System.Xml.XmlSerializer.Performance.Tests.csproj has a P2P dependency to System.Private.DataContractSerialization.csproj
F:\git\corefx\src\System.Private.Xml\tests\XmlSerializer\Performance\System.Xml.XmlSerializer.Performance.Tests.csproj has a P2P dependency to System.Private.Xml.Linq.csproj
F:\git\corefx\src\System.Private.Xml\tests\XmlSerializer\Performance\System.Xml.XmlSerializer.Performance.Tests.csproj has a P2P dependency to System.Xml.ReaderWriter.csproj
F:\git\corefx\src\System.Private.Xml\tests\XmlSerializer\Performance\System.Xml.XmlSerializer.Performance.Tests.csproj has a P2P dependency to System.Xml.XDocument.csproj
F:\git\corefx\src\System.Private.Xml\tests\XPath\XmlDocument\System.Xml.XPath.XmlDocument.Tests.csproj has a P2P dependency to System.Xml.ReaderWriter.csproj
F:\git\corefx\src\System.Private.Xml\tests\XPath\XmlDocument\System.Xml.XPath.XmlDocument.Tests.csproj has a P2P dependency to System.Xml.XmlDocument.csproj
F:\git\corefx\src\System.Private.Xml\tests\Xslt\XslCompiledTransformApi\System.Xml.Xsl.XslCompiledTransformApi.Tests.csproj has a P2P dependency to ModuleCore.csproj
F:\git\corefx\src\System.Private.Xml\tests\Xslt\XslCompiledTransformApi\System.Xml.Xsl.XslCompiledTransformApi.Tests.csproj has a P2P dependency to XmlCoreTest.csproj
F:\git\corefx\src\System.Private.Xml\tests\Xslt\XslCompiledTransformApi\System.Xml.Xsl.XslCompiledTransformApi.Tests.csproj has a P2P dependency to XmlDiff.csproj
F:\git\corefx\src\System.Private.Xml\tests\Xslt\XslCompiledTransformApi\System.Xml.Xsl.XslCompiledTransformApi.Tests.csproj has a P2P dependency to System.Xml.Xsl.XslTransformApi.Tests.csproj
F:\git\corefx\src\System.Private.Xml\tests\Xslt\XslCompiledTransformApi\System.Xml.Xsl.XslCompiledTransformApi.Tests.csproj has a P2P dependency to System.Xml.ReaderWriter.csproj
F:\git\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\XsltCompiler.Tests.csproj has a P2P dependency to ModuleCore.csproj
F:\git\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\XsltCompiler.Tests.csproj has a P2P dependency to XmlCoreTest.csproj
F:\git\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\XsltCompiler.Tests.csproj has a P2P dependency to XmlDiff.csproj
F:\git\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\XsltCompiler.Tests.csproj has a P2P dependency to System.Xml.ReaderWriter.csproj
F:\git\corefx\src\System.Private.Xml\tests\Xslt\XslTransformApi\System.Xml.Xsl.XslTransformApi.Tests.csproj has a P2P dependency to ModuleCore.csproj
F:\git\corefx\src\System.Private.Xml\tests\Xslt\XslTransformApi\System.Xml.Xsl.XslTransformApi.Tests.csproj has a P2P dependency to XmlCoreTest.csproj
F:\git\corefx\src\System.Private.Xml\tests\Xslt\XslTransformApi\System.Xml.Xsl.XslTransformApi.Tests.csproj has a P2P dependency to XmlDiff.csproj
F:\git\corefx\src\System.Private.Xml\tests\Xslt\XslTransformApi\System.Xml.Xsl.XslTransformApi.Tests.csproj has a P2P dependency to System.Xml.ReaderWriter.csproj
F:\git\corefx\src\System.Private.Xml\tests\Xslt\XsltScenarios\XsltScenarios.Tests.csproj has a P2P dependency to ModuleCore.csproj
F:\git\corefx\src\System.Private.Xml\tests\Xslt\XsltScenarios\XsltScenarios.Tests.csproj has a P2P dependency to XmlCoreTest.csproj
F:\git\corefx\src\System.Private.Xml\tests\Xslt\XsltScenarios\XsltScenarios.Tests.csproj has a P2P dependency to XmlDiff.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\events\System.Xml.Linq.Events.Tests.csproj has a P2P dependency to XDocument.Common.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\misc\System.Xml.Linq.Misc.Tests.csproj has a P2P dependency to XmlCoreTest.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\misc\System.Xml.Linq.Misc.Tests.csproj has a P2P dependency to XmlDiff.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\misc\System.Xml.Linq.Misc.Tests.csproj has a P2P dependency to XDocument.Common.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\misc\System.Xml.Linq.Misc.Tests.csproj has a P2P dependency to XDocument.Test.ModuleCore.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\Properties\System.Xml.Linq.Properties.Tests.csproj has a P2P dependency to XmlCoreTest.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\Properties\System.Xml.Linq.Properties.Tests.csproj has a P2P dependency to XmlDiff.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\Properties\System.Xml.Linq.Properties.Tests.csproj has a P2P dependency to XDocument.Common.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\Properties\System.Xml.Linq.Properties.Tests.csproj has a P2P dependency to XDocument.Test.ModuleCore.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\Streaming\System.Xml.Linq.Streaming.Tests.csproj has a P2P dependency to XmlDiff.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\Streaming\System.Xml.Linq.Streaming.Tests.csproj has a P2P dependency to XDocument.Common.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\TreeManipulation\System.Xml.Linq.TreeManipulation.Tests.csproj has a P2P dependency to ModuleCore.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\TreeManipulation\System.Xml.Linq.TreeManipulation.Tests.csproj has a P2P dependency to XmlCoreTest.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\TreeManipulation\System.Xml.Linq.TreeManipulation.Tests.csproj has a P2P dependency to XmlDiff.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\TreeManipulation\System.Xml.Linq.TreeManipulation.Tests.csproj has a P2P dependency to XDocument.Common.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\TreeManipulation\System.Xml.Linq.TreeManipulation.Tests.csproj has a P2P dependency to XDocument.Test.ModuleCore.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\XDocument.Common\XDocument.Common.csproj has a P2P dependency to XmlCoreTest.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\XDocument.Common\XDocument.Common.csproj has a P2P dependency to XmlDiff.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\XDocument.Common\XDocument.Common.csproj has a P2P dependency to XDocument.Test.ModuleCore.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\xNodeBuilder\System.Xml.Linq.xNodeBuilder.Tests.csproj has a P2P dependency to XmlCoreTest.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\xNodeBuilder\System.Xml.Linq.xNodeBuilder.Tests.csproj has a P2P dependency to XmlDiff.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\xNodeBuilder\System.Xml.Linq.xNodeBuilder.Tests.csproj has a P2P dependency to XDocument.Common.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\xNodeBuilder\System.Xml.Linq.xNodeBuilder.Tests.csproj has a P2P dependency to XDocument.Test.ModuleCore.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\xNodeReader\System.Xml.Linq.xNodeReader.Tests.csproj has a P2P dependency to XmlCoreTest.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\xNodeReader\System.Xml.Linq.xNodeReader.Tests.csproj has a P2P dependency to XmlDiff.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\xNodeReader\System.Xml.Linq.xNodeReader.Tests.csproj has a P2P dependency to XDocument.Common.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\xNodeReader\System.Xml.Linq.xNodeReader.Tests.csproj has a P2P dependency to XDocument.Test.ModuleCore.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\XPath\XDocument\System.Xml.XPath.XDocument.Tests.csproj has a P2P dependency to System.Xml.ReaderWriter.csproj
F:\git\corefx\src\System.Private.Xml.Linq\tests\XPath\XDocument\System.Xml.XPath.XDocument.Tests.csproj has a P2P dependency to System.Xml.XPath.XmlDocument.csproj
F:\git\corefx\src\System.Runtime.Serialization.Xml\ref\System.Runtime.Serialization.Xml.csproj has a P2P dependency to System.Xml.ReaderWriter.csproj
F:\git\corefx\src\System.Runtime.Serialization.Xml\src\System.Runtime.Serialization.Xml.csproj has a P2P dependency to System.Xml.ReaderWriter.csproj
F:\git\corefx\src\System.Runtime.Serialization.Xml\src\System.Runtime.Serialization.Xml.csproj has a P2P dependency to System.Xml.XmlDocument.csproj
F:\git\corefx\src\System.Runtime.Serialization.Xml\src\System.Runtime.Serialization.Xml.csproj has a P2P dependency to System.Private.Xml.csproj
F:\git\corefx\src\System.Runtime.Serialization.Xml\src\System.Runtime.Serialization.Xml.csproj has a P2P dependency to System.Private.DataContractSerialization.csproj
F:\git\corefx\src\System.Runtime.Serialization.Xml\tests\System.Runtime.Serialization.Xml.Tests.csproj has a P2P dependency to System.Xml.ReaderWriter.csproj
F:\git\corefx\src\System.Runtime.Serialization.Xml\tests\System.Runtime.Serialization.Xml.Tests.csproj has a P2P dependency to System.Xml.XDocument.csproj
F:\git\corefx\src\System.Runtime.Serialization.Xml\tests\System.Runtime.Serialization.Xml.Tests.csproj has a P2P dependency to System.Xml.XmlDocument.csproj
F:\git\corefx\src\System.Runtime.Serialization.Xml\tests\System.Runtime.Serialization.Xml.Tests.csproj has a P2P dependency to System.Private.Xml.csproj
F:\git\corefx\src\System.Runtime.Serialization.Xml\tests\System.Runtime.Serialization.Xml.Tests.csproj has a P2P dependency to System.Private.Xml.Linq.csproj
F:\git\corefx\src\System.Runtime.Serialization.Xml\tests\System.Runtime.Serialization.Xml.Tests.csproj has a P2P dependency to System.Private.DataContractSerialization.csproj
F:\git\corefx\src\System.Runtime.Serialization.Xml\tests\Performance\System.Runtime.Serialization.Xml.Performance.Tests.csproj has a P2P dependency to System.Private.DataContractSerialization.csproj
F:\git\corefx\src\System.Runtime.Serialization.Xml\tests\Performance\System.Runtime.Serialization.Xml.Performance.Tests.csproj has a P2P dependency to System.Xml.XmlSerializer.csproj
F:\git\corefx\src\System.Runtime.Serialization.Xml\tests\Performance\System.Runtime.Serialization.Xml.Performance.Tests.csproj has a P2P dependency to System.Xml.ReaderWriter.csproj
F:\git\corefx\src\System.Runtime.Serialization.Xml\tests\Performance\System.Runtime.Serialization.Xml.Performance.Tests.csproj has a P2P dependency to System.Xml.XDocument.csproj
F:\git\corefx\src\System.Runtime.Serialization.Xml\tests\Performance\System.Runtime.Serialization.Xml.Performance.Tests.csproj has a P2P dependency to System.Xml.XmlDocument.csproj
F:\git\corefx\src\System.Runtime.Serialization.Xml\tests\Performance\System.Runtime.Serialization.Xml.Performance.Tests.csproj has a P2P dependency to System.Private.Xml.csproj
F:\git\corefx\src\System.Runtime.Serialization.Xml\tests\Performance\System.Runtime.Serialization.Xml.Performance.Tests.csproj has a P2P dependency to System.Private.Xml.Linq.csproj
F:\git\corefx\src\System.Xml\ref\Compat\System.Xml.csproj has a P2P dependency to mscorlib.csproj
F:\git\corefx\src\System.Xml.Linq\ref\Compat\System.Xml.Linq.csproj has a P2P dependency to mscorlib.csproj
F:\git\corefx\src\System.Xml.ReaderWriter\src\System.Xml.ReaderWriter.csproj has a P2P dependency to System.Private.Xml.csproj
F:\git\corefx\src\System.Xml.Serialization\ref\Compat\System.Xml.Serialization.csproj has a P2P dependency to mscorlib.csproj
F:\git\corefx\src\System.Xml.Serialization\ref\Compat\System.Xml.Serialization.csproj has a P2P dependency to System.ServiceModel.csproj
F:\git\corefx\src\System.Xml.XDocument\src\System.Xml.XDocument.csproj has a P2P dependency to System.Private.Xml.Linq.csproj
F:\git\corefx\src\System.Xml.XDocument\src\System.Xml.XDocument.csproj has a P2P dependency to System.Private.Xml.csproj
F:\git\corefx\src\System.Xml.XmlDocument\src\System.Xml.XmlDocument.csproj has a P2P dependency to System.Private.Xml.csproj
F:\git\corefx\src\System.Xml.XmlSerializer\src\System.Xml.XmlSerializer.csproj has a P2P dependency to System.Xml.ReaderWriter.csproj
F:\git\corefx\src\System.Xml.XmlSerializer\src\System.Xml.XmlSerializer.csproj has a P2P dependency to System.Xml.XmlDocument.csproj
F:\git\corefx\src\System.Xml.XmlSerializer\src\System.Xml.XmlSerializer.csproj has a P2P dependency to System.Private.Xml.csproj
F:\git\corefx\src\System.Xml.XPath\src\System.Xml.XPath.csproj has a P2P dependency to System.Private.Xml.csproj
F:\git\corefx\src\System.Xml.XPath.XDocument\src\System.Xml.XPath.XDocument.csproj has a P2P dependency to System.Private.Xml.csproj
F:\git\corefx\src\System.Xml.XPath.XDocument\src\System.Xml.XPath.XDocument.csproj has a P2P dependency to System.Private.Xml.Linq.csproj
F:\git\corefx\src\System.Xml.XPath.XmlDocument\src\System.Xml.XPath.XmlDocument.csproj has a P2P dependency to System.Private.Xml.csproj
F:\git\corefx\src\System.Xml.XPath.XmlDocument\src\System.Xml.XPath.XmlDocument.csproj has a P2P dependency to System.Xml.ReaderWriter.csproj
F:\git\corefx\src\System.Xml.XPath.XmlDocument\src\System.Xml.XPath.XmlDocument.csproj has a P2P dependency to System.Xml.XmlDocument.csproj

**Comment by joperezr** [comment]
And these are the pkgproj references that were added:
F:\git\corefx\src\System.Private.Xml\tests\XmlSerializer\Performance\System.Xml.XmlSerializer.Performance.Tests.csproj has a P2P dependency to System.Runtime.Serialization.Primitives.pkgproj
F:\git\corefx\src\System.Runtime.Serialization.Xml\tests\System.Runtime.Serialization.Xml.Tests.csproj has a P2P dependency to System.Runtime.Serialization.Primitives.pkgproj
F:\git\corefx\src\System.Runtime.Serialization.Xml\tests\Performance\System.Runtime.Serialization.Xml.Performance.Tests.csproj has a P2P dependency to System.Runtime.Serialization.Primitives.pkgproj

**Comment by joperezr** [comment]
In order to be able to do this, we need to first expose all of the types that now live in System.Private.Xml through contracts.

**Comment by danmosemsft** [comment]
please also see #12144 as part of this

**Comment by joperezr** [comment]
@sepidehMS this is a very old workitem back from when we merged dev/xml branch into dev/api. I suppose all of these have been covered already by your Xml cleanups?

**Comment by sepidehMS** [comment]
@joperezr All Xml P2P references to csproj has already been removed. However, some Xml tests still reference the following:
```
XmlDiff.csproj
ModuleCore.csproj
XmlCoreTest.csproj
System.Xml.RW.XmlReaderLib.csproj
```
What should happen with these? There is no pkgproj

**Comment by joperezr** [comment]
I see, in that case I guess we can close this issue and leave those P2P for now since they are required. This was only meant to track workarounds caused by the merge. Thanks @sepidehMS !
