### ISSUE TITLE
Use dynamic function call with .NET core 1.0 RTM

### ISSUE THREAD

**Issue by SharpNoiZy** [dotnet/corefx#10686]
Hi,

I tried to do the following with .NET Core RTM:
this.AsDynamic().Apply(@event);
((dynamic)this).Apply(@event); <-- Or this syntax (Same meaning?!)

This didn't compile by default.
I found out how to solve it, with adding the dependency:
"Microsoft.CSharp": "4.0.1"

The project compiles, but if I look at the dependency list of it, it's huge!
It has 17 dependencies just for using dynamic (Just used once in the project at all) that's a high price.
Is there a "cheaper" dependency which I can add to use dynamic?
Maybe one or two of the 17?

Kind regards
Christian

**Comment by svick** [comment]
No, if you want to use `dynamic`, you will need `Microsoft.CSharp`.

Why is the number of dependencies an issue for you?

1. If your code is going to be used in a [portable application](https://docs.microsoft.com/en-us/dotnet/articles/core/app-types#portable-applications), all those dependencies are already going to be installed, so they won't cause any additional burden.
2. Even if it's going to be used in a [self-contained application](https://docs.microsoft.com/en-us/dotnet/articles/core/app-types#self-contained-application), then it's very likely the application is going to use many of those dependencies anyway (like `System.Collections` or `System.Linq`).
3. One of the goals of .Net Core was to split the monolithic .Net Framework into a number of small libraries. Having lots of dependencies is a natural consequence of that.

**Comment by SharpNoiZy** [comment]
@svick 
Point 3)
You can see it that way, but I think that also a reason for splitting into a number of small libraries, was that you don't have one big monolithic framework with a lot of functions you never use, don't you think?
And it feels to loose some of it lightweight if I add 17 libs just to use one keyword.
I fear to have at the end so many libs that it make from the size and "weight" factor no difference to take monolithic or .NET core, do you know what I mean?

**Comment by svick** [comment]
> You can see it that way, but I think that also a reason for splitting into a number of small libraries, was that you don't have one big monolithic framework with a lot of functions you never use, don't you think?

If you didn't use `dynamic`, you wouldn't need those libraries. But you are using it, so you have to include them. I think it's working the way it's supposed to.

> And it feels to loose some of it lightweight if I add 17 libs just to use one keyword.

`dynamic` is a pretty complicated keyword. Are you aware of what it does and how does it try to achieve high performance?

Which one of the 17 libs would you remove?

**Comment by karelz** [comment]
At the end of the day, it doesn't matter if there is 1 large binary or multiple small ones at compile time.
Application might want to choose to use shared framework or compile into single EXE (CoreRT) - that's  where size matters.
