### ISSUE TITLE
[ExcludeFromCodeCoverage] is marked as internal

### ISSUE THREAD

**Issue by cryogen** [dotnet/corefx#10685]
The ExcludeFromCodeCoverage attribute is marked as internal.  This is more than likely intended (It's also internal in the PCL) but it's public in all other versions of the .Net framework.

This attribute is as useful for user code as I'm sure it is in the framework's codebase.  Is there a particular design reason this was marked as internal?  Is there an alternative I'm not aware of?  If not, can it be made public?

**Comment by weshaggard** [comment]
Just a point in time issue. We will be exposing it as part of our push to add more APIs to .NET Core.
