### ISSUE TITLE
How to get DateTimeFormatInfo Time and Date separators?

### ISSUE THREAD

**Issue by nikibobi** [dotnet/corefx#10695]
In .NET there are `DateSeparator` and `TimeSeparator` properties, but I can't find them in .NET Core.
Were they removed or moved to a different class?
I need to make
```C#
string.Join(info.TimeSeparator, array);
```

**Comment by Clockwork-Muse** [comment]
...side note: it looks like you're doing manual time formatting.  Is there some reason you couldn't use the built-in stuff?

**Comment by nikibobi** [comment]
Yes because I'm using a different format with % that isn't supported by .NET and I need to output a format string like "%H %p %b" for example and place the separators there depending on the CultureInfo

**Comment by nikibobi** [comment]
I found that `DateSeparator`(and `TimeSeparator`) exist in coreclr source [here](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Globalization/DateTimeFormatInfo.cs/#L849) but I don't have Intellisence for them nor are they listed in the [documentation](https://docs.microsoft.com/en-us/dotnet/core/api/system.globalization.datetimeformatinfo#System_Globalization_DateTimeFormatInfo)
And when I try to compile I get
```
error CS1061: 'DateTimeFormatInfo' does not contain a definition for 'DateSeparator'
```
I'm using dotnet `1.0.0-preview2-003121` on Ubuntu 16.04
I really wonder what is the case here

**Comment by tarekgh** [comment]
@nikibobi we are in the process of exposing such properties. so it is matter of time to get these exposed. 

did you try to use ```/``` as the date separator? when formatting using / will replace it with the actual date separator.  for example, calling 

```
Console.WriteLine(DateTime.Now.ToString("MM/dd/yyyy", new CultureInfo("ug-CN")));
```

will produce 

```
08-16-2016
```

could you give it a try and let me know? note that the same apply with the time separator when using ```:```

**Comment by nikibobi** [comment]
Ok so for my needs I ended up using `DateTime.Now.ToString("/", info)` and that gives me what I need, but every time I have to call `DateTime.Now` for no reason and discard it. I'm looking forward to the properties being exposed. Thanks for the workaround tho!

**Comment by nikibobi** [comment]
Actually using only "/" or only ":" as a format throws exception, but using "/:" gives a correct result?! What gives?

**Comment by Clockwork-Muse** [comment]
... There's no reason to call `DateTime.Now` for this at all, you could use `DateTime.MaxValue`, which would avoid the reallocation each time.  You may also not need to get the separator "each time" anyways, since changing cultures in the middle of your process would probably have bad results on batched output.

My guess is the system is complaining that you have nothing but the separator, but it's a little hard to tell without the exception message.  Something maybe to look into.

For curiosity, could we get the current formatted string(s) you're trying to output (in both English and whatever language), plus what you've got working so far?

**Comment by tarekgh** [comment]
@nikibobi as @Clockwork-Muse mentioned you don't need to use DateTime.Now all the time as you don't really care about the date/time part values. 
if your goal is to produce a formatting string "%H %p %b" with inserting the date separator, you can still do that by call like the following:

```
            Console.WriteLine(DateTime.MinValue.ToString("'%H'/'%p'/'%b'", new CultureInfo("ug-CN")));
```
which will produce ```%H-%p-%b``` with the right date separator inserted as you wish.

**Comment by tarekgh** [comment]
Date and Time separator is now exposed on dev/api branch of corefx. 

https://github.com/dotnet/corefx/pull/11594
