### ISSUE TITLE
Add positive tests for FileStream begin/end

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#10698]

**Comment by JeremyKuhne** [comment]
#12035

**Comment by stephentoub** [comment]
@JeremyKuhne, @12035 added negative tests only, right?  What about actual functional tests?

**Comment by JeremyKuhne** [comment]
@stephentoub, @joperezr is going to set up the pattern for those in #10334. I'll keep this one open to track FileStream separately, which will be completed once that is done.

**Comment by ViktorHofer** [comment]
@JeremyKuhne @karelz High "up-for-grabs" potential?
