### ISSUE TITLE
Recommended way to determine when code is running on a FIPS compliant machine (desktop & coreclr)?

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/corefx#10694]
I'm currently working on a `SHA256.Create()` implementation that works on CoreCLR and net451 FIPS compliant machines. I'm currently using try catch statements to work around net451's invalid `SHA256.Create` behavior to determine FIPS compliance but was wondering if there was a better route that worked on both desktop and coreclr?

**Comment by bartonjs** [comment]
Not really.  The question itself is hard to describe on a non-Windows machine, and so the framework exposing it as either true or false is difficult, which is part of why the property doesn't exist.

If you know that you will only be executing on Windows machines, you can P/Invoke into [BCryptGetFipsAlgorithmMode](https://msdn.microsoft.com/en-us/library/windows/desktop/aa375460(v=vs.85).aspx).  While the function there is CNG, the same policy is used for CNG, CAPI, and .NET Framework.

**Comment by blowdart** [comment]
Well we really only care on Windows, as on Core (which includes non-Windows) it's all using the OS, and thus, if the OS is FIPS configured, it should just work.

**Comment by NTaylorMullen** [comment]
Will stick with try-catch approach then.

**Comment by bartonjs** [comment]
Glad to help :smile:.
