### ISSUE TITLE
Improve code coverage for System.Diagnostics.Process

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1070]
According to the current code coverage report, this library is only at ~53%. Our general goal is closer to 90%, though this will depend on the library. We should investigate to see whether the current coverage level is appropriate, and if not, improve our test suites to provide better coverage.

**Comment by pallavit** [comment]
@stephentoub Does the report mention the areas with low coverage? Please share the code coverage report. Thanks.

**Comment by stephentoub** [comment]
Yes.  It'll be included in the daily code coverage run once #1069 is checked in.  If you want to see the details before then, easiest way would be to just checkout the branch from the PR and do a code coverage run locally.

**Comment by stephentoub** [comment]
Pallavi, now that #1069 has been checked in, the code coverage information is available in the reports at http://dotnet-ci.cloudapp.net/job/dotnet_corefx_coverage_windows/lastBuild/Code_Coverage_Report/

**Comment by ssg** [comment]
@stephentoub System.Diagnostics.Process isn't in the report?

**Comment by stephentoub** [comment]
@ssg, if you look back a few days you'll see it.  It's been temporarily removed: https://github.com/dotnet/corefx/pull/1104

**Comment by ssg** [comment]
@stephentoub yes this link works: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_coverage_windows/67/Code_Coverage_Report/ thanks!

**Comment by stephentoub** [comment]
@ssg, great; glad you found it.

**Comment by Priya91** [comment]
Tests have been added to improve coverage. PerformanceCounterLib is not covered, as it requires multi machine test infrastructure. The ProcessThreadCollection and ProcessModuleCollection are not covered since it's only an implementation of ICollection.

PRs: #2513, #2421, #2417, #2404, #2311, #2283, #2262

**Comment by ssg** [comment]
Hi Lakshmi,

https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessModuleCollection.cs

The code for ProcessModuleCollection seems to be able to experience
regressions in the future regardless. "It's only an implementation of
ICollection" didn't seem a good justification for me. "Not a priorty" is
but not that.

Thanks,

Sedat

**Comment by stephentoub** [comment]
> PerformanceCounterLib is not covered, as it requires multi machine test infrastructure

Can we not use a machine name of "127.0.0.1" to access the local machine "remotely"?

> The ProcessThreadCollection and ProcessModuleCollection are not covered since it's only an implementation of ICollection

I agree with @ssg; we might say these are lower priority because, for example, they're very thin wrappers around a list, but there's still a custom implementation there to be tested.

**Comment by Priya91** [comment]
> Can we not use a machine name of "127.0.0.1" to access the local machine "remotely"?

apparently u can, we don't check if the ip address provided is current machine, only with computer name.

I'll add tests to the Collection class as well.
