### ISSUE TITLE
SSlProtocols.Ssl3 causing SslStream.AuthenticateAsClientAsync to throw System.NotSupportedException

### ISSUE THREAD

**Issue by kannanenator** [dotnet/corefx#10700]
System.Security.Authentication.SslProtocols.Ssl3 (and Ssl2 for that matter) appears to be not supported. Issue was noticed when trying to connect to MongoDb with default SslProtocols.

**Comment by blowdart** [comment]
SSL3 and SSL2 are considered irretrievably broken by the security community.

SSL 2.0 was deprecated (and indeed prohibited) in 2011 by RFC 6176.

SSL 3.0 was deprecated in June 2015 by RFC 7568.

Their exclusion is a design decision I'm afraid, and not one we're likely to roll back.

**Comment by kannanenator** [comment]
Thanks for the response. Sounds like I'll have to take up my issue with Mongo then.
