### ISSUE TITLE
System.Net test intermittent failures

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#10702]
few test cases are marked with `[ActiveIssue(10702)]`
(pending work - i need to have an issue number to mark it  :smile:)

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/dev_api/job/windows_nt_release_prtest/324/
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/dev_api/job/windows_nt_debug_prtest/329/

Happened in here: https://github.com/dotnet/corefx/pull/10693

**Comment by krwq** [comment]
Hey @ericeil could you take a look? It happened when merging xml PR but it doesn't seem like any of those have anything to do with XML.

**Comment by davidsh** [comment]
Closing this issue since the repro logs are no longer available.

**Comment by Jiayili1** [comment]
Disabled test, reopen it.

**Comment by Priya91** [comment]
The disabled test is a dupe of issue #9296.

**Comment by karelz** [comment]
@Priya91 can you please update the code to refer to the active issue? We do not want ActiveIssue on closed bugs in code.

**Comment by Priya91** [comment]
@karelz Yes I have a couple of other changes to go in as well, will consolidate and open a PR soon.

**Comment by karelz** [comment]
Perfect, thanks!
