### ISSUE TITLE
Building a corefx source or test project restores packages every time

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#10719]
Whenever I build a corefx source or test project that I've built before, the majority of the build time is spent in the "RestorePackages" target.

It seems that the build system doesn't recognise that I have already restored all the packages.
This increases build times significantly, and is unecessary.

Is this by design and unavoidable?

**Comment by hughbe** [comment]
Possibly related to #10666

**Comment by maririos** [comment]
It could be avoid if you pass the parameter `/p:RestoreDuringBuild=false`. It will skip the target `Restore packages`

**Comment by hughbe** [comment]
Ah awesome, thanks!

What about buildtools automatically realising nothing needs to be restored in the first place?

**Comment by maririos** [comment]
You mean when we call init-tools?

**Comment by hughbe** [comment]
When you run msbuild /T:BuildAndTest

**Comment by weshaggard** [comment]
Yes we definitely need to improve our package restore logic, including trying to avoid doing work if nothing has changed. There are some thoughts about how to approach this but we haven't had the cycles to focus on it yet.

**Comment by ericstj** [comment]
Indeed #10939 will fix this.  Restore target will still run but should be reduced to a few ms.

**Comment by hughbe** [comment]
Thank you! This has made it so much easier to build
