### ISSUE TITLE
System/Globalization IdnMapping, check if string is ASCII first before calling Interop?

### ISSUE THREAD

**Issue by ZestyBread** [dotnet/corefx#10720]
Hello, my name is Justin, current intern on the ASP.NET team. I noticed that calls to IdnMapping.GetAscii always called Interop.mincore.IdnToAscii, which can be a bit pricey because you are pinvoking. I was wondering if we could have a quick ASCII check (iterate through all characters and check the highest order bit) and only convert to puny code if it isn't ASCII? I currently implemented something similar in ASP.NET to avoid calling GetAscii, but it is more appropriate to be here.

Specifically:
https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Globalization/IdnMapping.cs#L72

**Comment by benaadams** [comment]
String has an internal [IsAscii()](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/String.cs#L3734) function which flags the string on first run (returns flag on subsequent runs) wonder if exposing that and using it would be helpful?

**Comment by benaadams** [comment]
Specially it calls the c++ function https://github.com/dotnet/coreclr/blob/master/src/classlibnative/bcltype/stringnative.cpp#L228-L249

**Comment by tarekgh** [comment]
I don't think using String.IsAscii is enough here as we need to check for some specific characters according to the conversion flags. we originally didn't do this optimization because this logic is done as part of the OS API. I think we can do such optimization but we need to understand we'll have to revisit this every time the standard change for whatever reason. our promise was getting the exact OS IDN behavior. 

@ZestyBread is this request such suggestion you see or you really ran into perf issue?

**Comment by ZestyBread** [comment]
We used a boolean lookup table for specific characters that are allowed to be in a hostname, you can do the same for the specific characters.
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Abstractions/Internal/HostStringHelper.cs
And
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Abstractions/HostString.cs#L120

https://github.com/aspnet/HttpAbstractions/pull/685 
was the original issue. These aren't perfect numbers, but we see a fairly significant improvement. 

Totally understand if you decide not to do it due to OS IDN behavior compliance.

**Comment by tarekgh** [comment]
Yah, I prefer to keep the OS compliance behavior for now till we find the perf is really issue. 

thanks @ZestyBread for your thoughts.
