### ISSUE TITLE
Why doesn't HttpResponseMessage.Headers contain the values within HttpResponseMessage.Content.Headers?

### ISSUE THREAD

**Issue by jchannon** [dotnet/corefx#10739]
Whilst using HttpClient today it took me 45 minutes to realise the Content headers are not in the HttpResponseMessage.Headers but exist elsewhere.  

I have no clue why it's designed like this but if I look at response.Headers I expect to see ALL headers.

**Comment by davidsh** [comment]
The design model is that we separate out entity-body ("Content") related headers into the .Content object (.Content.Headers) of the HttpResponseMessage.  transport related headers are in the HttpRequestMessage/HttpResponseMessage.

This is the same design as the .NET Framework (Desktop) API surface so it was inherited from that.

**Comment by jchannon** [comment]
I always used Restsharp until now and this seems an odd design. I make a
request and I get a response back. All I want is response.Headers to
contain ALL headers. Simple.

**Comment by davidsh** [comment]
Thank you for your feedback.  We've had this design since .NET 4.5 and it would be difficult to change it at this point for existing app developers.
