### ISSUE TITLE
[dev/api] Fix XmlSerializer tests for netcore50aot

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#10744]
Make sure the XmlSerializer tests compile and pass for `/p:TargetGroup=netcore50aot`

**EDIT**: Also make sure that we re-add the cross compilation for the implementation of XmlSerializer that was removed on 4833cbf3df34f63dddc2c0b9d254a62887964abe

**Comment by sepidehMS** [comment]
Done by https://github.com/dotnet/corefx/pull/11527
