### ISSUE TITLE
Proposal: leaveOpen constructor overload for CryptoStream

### ISSUE THREAD

**Issue by bbowyersmyth** [dotnet/corefx#1079]
A CryptoStream always closes the wrapped stream when it is disposed. This not ideal when using a MemoryStream or when another action needs to be taken on the result.

The workarounds are manually calling `FlushFinalBlock()` and then getting the MemoryStream bytes before disposing the CryptoStream, or using a custom stream that ignores the dispose call from CryptoStream. Neither are ideal and can be avoided with a "leaveOpen" option.

Implementation would be the same as DeflateStream, on `Dispose()` check if leaveOpen is true and don't close the internal stream.

    public CryptoStream(Stream stream, ICryptoTransform transform, CryptoStreamMode mode, bool leaveOpen)

I'm happy to do the change when System.Security.Cryptography.Encryption arrives.

**Comment by bbowyersmyth** [comment]
CryptoStream is now on Github

**Comment by terrajobst** [comment]
@bartonjs, what's your take on this?

**Comment by bartonjs** [comment]
@terrajobst I like it, and it matches what has come over the years to a lot of Stream-over-Stream constructors.

But since this is a type in full framework I'm not sure what our compatibility work windows are... certainly this could be done in the future branch.

**Comment by bartonjs** [comment]
# API proposal

Add a leaveOpen constructor to CryptoStream to allow the caller to maintain ownership post-Dispose.

```diff
    public partial class CryptoStream : System.IO.Stream, System.IDisposable
    {
        public CryptoStream(System.IO.Stream stream, System.Security.Cryptography.ICryptoTransform transform, System.Security.Cryptography.CryptoStreamMode mode) { }
+       public CryptoStream(System.IO.Stream stream, System.Security.Cryptography.ICryptoTransform transform, System.Security.Cryptography.CryptoStreamMode mode, bool leaveOpen) { }
        public override bool CanRead { get { return default(bool); } }
```

## Semantics

The existing constructor would defer to the new one with `leaveOpen: false` to maintain compatibility.

When constructed with `leaveOpen: true`, CryptoStream Dispose will not chain the call to Dispose to the underlying stream.
