### ISSUE TITLE
[.NET 4.6.3] Return parameters not considered in Attribute.GetParentDefinition(ParameterInfo)

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#10796]
Opening this to track integration into Netfx6.3 (the tags only work on corefx repo bugs.) Besides, I need a reminder to remove the ActiveIssue from the corefx regression test once the fix has wandered itself over into the packages.

Original issue: https://github.com/dotnet/coreclr/issues/6600
The commit that fixed it: https://github.com/dotnet/coreclr/pull/6745

**Comment by AlexGhiondea** [comment]
Closing this as a TFS bug has already been created for this.
