### ISSUE TITLE
Use ConditionalFact in Manual tests of SqlClient 

### ISSUE THREAD

**Issue by saurabh500** [dotnet/corefx#10800]
Based on the comment at https://github.com/dotnet/corefx/pull/10742#issuecomment-239888047 `ConditionalFact` can be used to conditionally execute the Xunit

This issue is being opened to track the change.

**Comment by saurabh500** [comment]
cc @Wraith2 In case you want fix the tests to use ConditionalFact instead of the custom attribute that SqlClient tests have.

**Comment by Wraith2** [comment]
Fix by removing the custom attributes? I can probably do that.

**Comment by saurabh500** [comment]
Yeah, remove the `CheckConnStrSetupFact` class completely and migrate all usages to `ConditionalFact`

**Comment by Wraith2** [comment]
Sure, assign it to me.
