### ISSUE TITLE
Enable full test runs for netcoreapp1.1

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#10804]
Enable full test runs for netcoreapp1.1 in master. Currently we can only run them locally.

Then we can merge this into dev/api and enable for that branch also.

assigning to @joperezr for now.

**Comment by joperezr** [comment]
As part of this work, we should also remove the workaround that was introduced in a few projects to remove .Net Core App 1.1 test moniker, for example, the one introduced in #11051

**Comment by joperezr** [comment]
Fixed by #11236
