### ISSUE TITLE
Use same compiler in all corefx builds

### ISSUE THREAD

**Issue by chcosta** [dotnet/corefx#10856]
In corefx, on windows, the default is still too use the shared compiler, you have to opt into using this Roslyn compiler via "UseSharedCompilation=false". On Linux, the default is to use this Rosslyn compiler.

All corefx builds should be using the same compiler so that available features across builds are identical.

https://github.com/dotnet/buildtools/pull/947

**Comment by mellinoe** [comment]
@chcosta Any update on this one?

**Comment by mellinoe** [comment]
I'm marking this up for grabs.

**Comment by wtgodbe** [comment]
I believe this has been resolved as of https://github.com/dotnet/corefx/pull/24076, @chcosta please reopen if I'm mistaken
