### ISSUE TITLE
System.Reflection.Emit incorrectly lists NETCore50 as supported

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#10860]
This problem has existed since the first release of the package.

You could never actually use this package on netcore50 because it depended on System.Reflection.Emit.ILGeneration which correctly **did not** support netcore50.

I need to add some additional knobs on package harvesting to clean this up.

**Comment by ericstj** [comment]
Moving to 1.2 this is just cleanup.

**Comment by karelz** [comment]
@ericstj what has to happen here? Is it something that @AtsushiKan @DnlHarvey should do?

**Comment by ericstj** [comment]
This is no longer an issue, we've deleted the package.

**Comment by ericstj** [comment]
Also @joperezr made sure it wouldn't be exposed https://github.com/dotnet/corefx/blob/afaaf450d1869992dcf4f51c627f16145cf9c974/src/System.Reflection.Emit/dir.props#L8

**Comment by karelz** [comment]
Great, thanks @ericstj and @joperezr!
