### ISSUE TITLE
Reference to XunitTraitsDiscoverers broken, unit tests don't run in Visual Studio

### ISSUE THREAD

**Issue by WilfriedB** [dotnet/corefx#1090]
After cloning corefx, I couldn't built any solution in Visual Studio because of "missing" files. They did build with Build.cmd though, and after that they also built in Visual Studio, but with a warning: ```The referenced component 'XunitTraitsDiscoverers' could not be found```. Also, the unit tests don't run, the error message is: ```no reference to xUnit.net```.

In the .csproj file there is a reference to XunitTraitsDiscoverers: ```<ProjectReference Include="$(CommonTestPath)\XunitTraitsDiscoverers\XunitTraitsDiscoverers.csproj">```. The project is in the source tree, at ```src\Common\tests\XunitTraitsDiscoverers```.

I suspect that the variable $(CommonTestPath) isn't set correctly, but I don't know why this is the case. Does anyone have an idea what's wrong here?

![brokenreferencexunit](https://cloud.githubusercontent.com/assets/4008699/6506643/f0a39440-c34c-11e4-8334-08267ea93f4c.png)

**Comment by Maxwe11** [comment]
duo #745

**Comment by nguerrera** [comment]
This is indeed tracked by #745. Closing duplicate.

**Comment by WilfriedB** [comment]
Well, I did read [https://github.com/dotnet/corefx/issues/745] before but somehow failed to realize that it is the same issue. Thanks for pointing out.
