### ISSUE TITLE
Implement TripleDES 128 bit key size

### ISSUE THREAD

**Issue by ndyrulz** [dotnet/corefx#10919]
The current TripleDES implementation only has 192 bit valid key size.

Use case : old crypting method uses a TripleDES of a MD5 of a string. The MD5 always returns a 16 byte value.

**Comment by bartonjs** [comment]
This is the same as #9966.  In the meantime you can apply the two-key extension locally:

```C#
byte[] fullKey = new byte[24];
Buffer.BlockCopy(shortKey, 0, fullKey, 0, 16);
Buffer.BlockCopy(shortKey, 0, fullKey, 16, 8);
```
