### ISSUE TITLE
ExtractToFile() max. extract size throws wrong error

### ISSUE THREAD

**Issue by neridonk** [dotnet/corefx#10923]
Im trying to extract multiple .bak files in .zip archives.
It all works fine If the files are under 2GB 
but when my .bak file is above 2GB it throws a

> "The archive entry was compressed using an unsupported compression method."

This is not right, I compressed them with the same methode of the 2GB< files

**Comment by stephentoub** [comment]
How did you create the .zip archives (i.e. what tool did you use)?  Was it with Windows Explorer?

cc: @ianhays

**Comment by ianhays** [comment]
Definitely sounds like https://github.com/dotnet/corefx/issues/9925.

**Comment by joshfree** [comment]
@ianhays can you please open a MSDN doc bug on this internally - so in the near term we can document the 2GB Deflate/Deflate64 issue until a solution is in place?
