### ISSUE TITLE
Clean the scripts build-managed and build-native using run.exe

### ISSUE THREAD

**Issue by maririos** [dotnet/corefx#10925]
Clean build-native.cmd/sh and build-managed.cmd/sh by adding properties to config.json file following the [dev workflow](https://github.com/dotnet/buildtools/blob/master/Documentation/Dev-workflow.md) guidelines.

**Comment by mellinoe** [comment]
@maririos Could you clarify what the work to be done here is? It looks like these are already wrappers over the "run tool", with the exception of `build-managed.sh`.

**Comment by maririos** [comment]
> with the exception of build-managed.sh

Yes, we need that one and 'src/native/build-native.cmd', 'src/native/build-native.sh'. They still have logic on them that we should try to reduce and use run.exe for that

**Comment by karelz** [comment]
@MattGal @maririos are you working on it? (it's assigned to you)
Do we still need it, given that we are pushing for getting rid of run.exe?

**Comment by MattGal** [comment]
@karelz Not actively working on this.  OK to close by me.

**Comment by karelz** [comment]
OK, thanks for confirmation. Closing for now.
@mellinoe feel free to reopen if you feel otherwise ...
