### ISSUE TITLE
Add IsolatedStorageFile.GetEnumerator()

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#10936]
`IsolatedStorageFile.GetEnumerator()` allows you to enumerate all stores for the current user.

[How to: Enumerate Stores for Isolated Storage](https://msdn.microsoft.com/en-us/library/c3dy613a(v=vs.110).aspx)

**Comment by JeremyKuhne** [comment]
Subtask of #9465

**Comment by JeremyKuhne** [comment]
Don't currently plan to implement this as it depends on serialization of System.Security objects.

**Comment by JeremyKuhne** [comment]
@weshaggard When you iterate existing stores you need to expose IsolatedStorage.*Identity which is serialized/deserialized from disk. Not really plausible without Security related classes- not sure how we want to reflect that in NetStandard decisions.

**Comment by Petermarcu** [comment]
Is this in netstandard 2.0 or a future milestone. We shouldn't have future and netstandard2.0 on any issues.

**Comment by weshaggard** [comment]
@JeremyKuhne I would just have this return known stores, or empty. I don't think we need to worry about the full enumeration that we do on desktop.

**Comment by JeremyKuhne** [comment]
@weshaggard I currently have it as PlatformNotSupported. There is no way to return known stores without serializing our identity types, which I didn't want to do as it would collide with desktop. I'm currently relying on the fact that desktop will serialize it's own identity for the given store- and we don't have access to those types.

**Comment by JeremyKuhne** [comment]
#12641 to track making this return empty, closing the more complicated scenario pending user feedback.
