### ISSUE TITLE
Add IsolatedStorageFile factory methods with Evidence dependencies

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#10935]
Need to implement the various `GetStore()` methods have direct or indirect dependencies on `System.Security.Policy.Evidence`.

This includes:

`GetStore(IsolatedStorageScope, Type, Type)`
`GetStore(IsolatedStorageScope, Object, Object)`
`GetStore(IsolatedStorageScope, Evidence, Type, Evidence, Type)`
`GetStore(IsolatedStorageScope, Type)`
`GetStore(IsolatedStorageScope, Object)`

These may not be possible without `System.Security.Policy.Evidence`.

See #10934 for the other factory methods.

**Comment by JeremyKuhne** [comment]
Subtask of #9465.

**Comment by JeremyKuhne** [comment]
Without System.Security this isn't useful to implement. If we get strong feedback we can consider possible workarounds.

**Comment by danmosemsft** [comment]
Per the discussions in
https://github.com/dotnet/corefx/pull/17471#pullrequestreview-28900471 
https://github.com/dotnet/corefx/pull/17471#pullrequestreview-28900773
https://github.com/dotnet/corefx/pull/17471#discussion_r107900563
some of these could be impolemented.

`public static IsolatedStorageFile GetStore(IsolatedStorageScope scope, Type domainEvidenceType, Type assemblyEvidenceType)` has several % usage in some corpora https://apisof.net/catalog/System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(IsolatedStorageScope,Type,Type)

**Comment by JeremyKuhne** [comment]
I'm going to say this is roughly a week- the existing code will have to be refactored somewhat to enable some of these methods. (Allowing for context switching back to this code, investigating legacy behavior and writing tests.)

**Comment by danmosemsft** [comment]
I don't think we have a week to do this right now.

**Comment by JeremyKuhne** [comment]
Closing as this isn't a common scenario.
