### ISSUE TITLE
Console.ReadKey does not wait

### ISSUE THREAD

**Issue by Thoemmeli** [dotnet/corefx#10950]
After verifying the .NET Framework documentation that the ReadKey method is supposed to wait, I observed .NET Core does not wait on Console.ReadKey but just run over it.

https://msdn.microsoft.com/en-us/library/x3h8xffw(v=vs.110).aspx
"The ReadKey method waits, that is, blocks on the thread issuing the ReadKey method, until a character or function key is pressed. A character or function key can be pressed in combination with one or more Alt, Ctrl, or Shift modifier keys. However, pressing a modifier key by itself will not cause the ReadKey method to return."

**Comment by stephentoub** [comment]
What OS?  Can you share a repro?

**Comment by Thoemmeli** [comment]
Sorry, false alarm. In the code I ran before there was a call to a Win32 function sending key input. That was obviously going to the keyboard buffer and when ReadKey was called, the key was already there.
Cheers
Thomas

**Comment by stephentoub** [comment]
Thanks for the update.
