### ISSUE TITLE
WinHttpHandler using HTTP/2 returns error with servers using push promise

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#10958]
While implementing PR #10948, we discovered that Windows winHTTP has some issues with HTTP/2 servers that use server push functionality (push promise).

Reference internal bug 8523801.

**Comment by non-standard** [comment]
Any updates?

**Comment by davidsh** [comment]
>Any updates?

Yes, the bug was in the OS platform (Windows) in the native WinHTTP component.  That bug has been fixed.  The fix is available if you are running on the latest Insider Preview of Windows 10.  That means a build beyond the Windows 10 Anniversary Update (build 14393).

I did not resolve this GitHub issue yet because I need to create a new test that validates against running on a recent Windows 10 build. 

If you look at the Windows 10 Insider Preview blog:
https://blogs.windows.com/blog/tag/windows-insider-program/#TPG8fTCzCk4ly8Oq.97

you'll see that the latest build if 15014.  That build will have the fix.  The fix was actually contained in build 14917 Insider Preview.

**Comment by non-standard** [comment]
I see that in build 15019 the System.Net.HttpClient using the WinHttpHandler from nuget is still unable to receive a server_push response.  Is there more to it than just the WinHTTP component?

**Comment by davidsh** [comment]
The bug that was fixed was the crash (exception thrown) when communicating with a server that advertised it supported server-push.  That exception was fixed.

However, full support for server-push is not implemented yet in the native WinHTTP component and, hence, not supported in WinHttpHandler / HttpClient in .NET Core.

**Comment by karelz** [comment]
Next step: We need the test to run only on Win10 special version+

**Comment by davidsh** [comment]
Closed via #17894.
