### ISSUE TITLE
Compat work to implement missing Globalization API for .NET Native and Unix

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#10961]
Tarek, please split as needed

**Comment by tarekgh** [comment]
thanks @danmosemsft.

**Comment by weshaggard** [comment]
This should track both .NET Native and the unix implementation we have inside coreclr repo (or feel free to split them if you like).

**Comment by tarekgh** [comment]
I am going to split this issue to other issues to be easy to track.

**Comment by danmosemsft** [comment]
@tarekgh does this duplicate other issues now, and can be closed?

**Comment by tarekgh** [comment]
@danmosemsft I am going to split this issue into more issues when I start working on supporting Linux and .Net Native. the other issues we have are tracking Windows work which I'll be able to resolve them after I finish writing the tests which I am currently doing.

**Comment by tarekgh** [comment]
Closing this as I have split it into more granular issues
