### ISSUE TITLE
Add missing member on ZipArchiveEntry

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#10969]
There is only one thing left missing in System.IO.Compression namespace.

`M:System.IO.Compression.ZipArchiveEntry.set_Archive(System.IO.Compression.ZipArchive)`

**Comment by hann013** [comment]
@danmosemsft From where are you seeing that the member is missing? Because the native desktop implementation only has a getter on the `Archive` property, and the mono implementation has a private setter.

**Comment by danmosemsft** [comment]
You're right. apicatalog is wrong. I'll ask Immo.
