### ISSUE TITLE
Exposing String.Compare(string, int, string, int, int, bool) in the contracts

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#10963]
Separated from #10571 as per @stephentoub's request

This function:

```cs
public class String
{
    public static int Compare(string strA, int indexA, string strB, int indexB, int length, bool ignoreCase);
}
```

is currently missing from [the contracts](https://github.com/dotnet/corefx/blob/dev/api/src/System.Runtime/ref/System.Runtime.cs#L1630), both in the dev/api and master branch. It should probably be exposed since there is already another, similar overload that is: `Compare(string, string, bool)`.

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/issues/10216
https://github.com/dotnet/corefx/issues/10066
