### ISSUE TITLE
HelloWorld broken on Linux due to recent changes

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#1097]
Somewhere between 2416d38 and 0e73355 we broke the ability to use the System.Console.dll we build and run hello world on Linux.  The run time asserts.  I believe we are trying to load an assembly which fails (but I am not sure what one) and then the runtime blows up trying to throw FileNotFoundException.

**Comment by ellismg** [comment]
This was a problem is the guide on how to build on Linux.  Since we pull down the facades over there by NuGet, the recent changes to move to 4.0.0.10 versions of some of the contracts caused us to not have the right facades on Linux.  I have updated the guide and confirmed everything is working.

**Comment by akoeplinger** [comment]
@ellismg the last section of the wiki still references the old versions, see https://github.com/dotnet/coreclr/issues/154#issuecomment-77533469
