### ISSUE TITLE
Potential optimizations for System.IO.Path

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#10973]
- [`CheckInvalidPathChars`](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/IO/PathInternal.cs#L19) is called as much as 1-3 times in most Path chars, however due to all of the exception-throwing code it doesn't look as if it's going to be inlined. SInce dotnet/coreclr#6103 was merged, it may be beneficial to separate the throwing logic out to encourage inlining, for example:

``` cs
internal static void CheckInvalidPathChars(string path)
{
    if (path == null)
        ThrowArgumentNullPath();

    if (PathInternal.HasIllegalCharacters(path))
        ThrowArgumentInvalidPathChars();
}
```
- StringBuilder's indexer is not inlined, so [this](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/IO/PathInternal.cs#L40) is very slow, although it does avoid allocations. It may be worth seeing how all of the method calls stack up against using `ToString` and indexing into that instead.
- [This](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/IO/PathInternal.Unix.cs#L78-L92) is definitely suboptimal; I don't think `StringBuilder.Append(char)` is inlined, and we could use a `char[]` instead since we know the max length of the buffer in advance.
- [Same here](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/IO/PathInternal.Windows.cs#L409-L437)
- [Same here](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/IO/Path.cs#L260-L285)
  - Maybe this could make use of `ArrayPool<char>.Shared.Rent`, instead of using `StringBuilder`?
- [Same here](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/IO/Path.Unix.cs#L110)

cc @JeremyKuhne

**Comment by JeremyKuhne** [comment]
> CheckInvalidPathChars is called as much as 1-3 times in most Path chars, 

Personally I'd like to remove the path char check- perhaps under an AppContext switch. It isn't that useful- on Unix it's just "no nulls".  Additionally it isn't technically correct for all Windows paths (notably pipes)- I skip it entirely with device paths because of this.

You may want to consider looking at how StringBuffer performs compared to StringBuilder since were already using it and it's cached.

**Comment by jamesqo** [comment]
@JeremyKuhne 

> Personally I'd like to remove the path char check- perhaps under an AppContext switch.

Regarding AppContext itself, what would be the overhead of using that? AFAICS it does [locking](https://github.com/dotnet/corefx/blob/master/src/System.AppContext/src/System/AppContext.cs#L64) which could be relatively expensive.

> You may want to consider looking at how StringBuffer performs compared to StringBuilder since were already using it and it's cached.

Seems like an interesting option. I'm going to hazard a guess that simply having a `new char[]` (even uncached) may be faster, since acquiring unmanaged memory (which appears to be what StringBuffer uses) is slow, and the cache uses [`Interlocked.Exchange`](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Runtime/InteropServices/SafeHeapHandleCache.cs#L43) which is also slow. I'll have to benchmark before I can say anything for sure though...

I think the best strategy would be to do something like `stackalloc char[...]` for small buffers, and then `ArrayPool<char>.Shared.Rent` for larger ones where the overhead of processing the array will be much larger than that of renting it.

**Comment by jamesqo** [comment]
@JeremyKuhne I found something unexpected after running 1m iterations of `Path.Combine` through PerfView... turns out the allocations/most of the things discussed in this thread were nowhere even *close* to being the bottleneck of the program. Instead, [this method](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/IO/PathInternal.Windows.cs#L193), which is called by `CheckInvalidPathChars` was taking up almost 60% of the time.

Proof:

![unexpected_results](https://cloud.githubusercontent.com/assets/9159214/18113680/a7da672e-6eff-11e6-8215-f13dd2a2d457.PNG)

The main bottleneck in `IndexOfAny` appears to be [this method](https://github.com/dotnet/coreclr/blob/master/src/classlibnative/bcltype/stringnative.cpp#L495), which initializes a bitmap of some sort to indicate whether a character is in the array. It grows in complexity for each char in the array, so due to the huge amount of invalid chars in Windows it's taking up a **lot** of time.

**Comment by JeremyKuhne** [comment]
> Regarding AppContext itself, what would be the overhead of using that? AFAICS it does locking which could be relatively expensive.

@jamesqo The desktop implementation uses Interlocked.Exchange. @AlexGhiondea, any plans to optimize AppContext?

Most of the characters are < (char)32. All of which are pretty unlikely. Outside of that you only have 4 chars. Walking through the string manually would likely give better results.

**Comment by AlexGhiondea** [comment]
AppContext does lock, but it should only take the lock once per app domain per switch. Once the value of the switch is retrieved, it is cached and no further locks are taken for retrieving the value.

@JeremyKuhne did you have an optimization in mind?

**Comment by danmosemsft** [comment]
@JeremyKuhne I moved this to Future as it does not seem necessary for 2.0

**Comment by stephentoub** [comment]
Much of this implementation has changed, e.g. IndexOfAny has changed its implementation completely, Path has been optimized in a variety of ways, etc.  To do anything here would require a complete re-investigation to see what the bottlenecks are and whether they actually matter.  As such, I'm closing this as inactionable. Please feel free to open a new issue if other real problems are found. Thanks.
