### ISSUE TITLE
Discussion: Add some form of ListExtensions, similar to linq Enumerable extensions

### ISSUE THREAD

**Issue by nvivo** [dotnet/corefx#1098]
This is a proposal based on to discussions in #461 and #494.

Currently, things like Sort, IndexOf, BinarySearch and other methods are implemented as part of the Array and List types twice. It's clear these methods are useful in other places, both .NET types and user implementations. Also, these methods usually operate in place, instead of generating a new list which allows for more optimized code in some situations.

There is also a proposal (#461) to add Shuffle method, but we cannot agree on where, because there is not a correct place for it today.

I'd like to propose a `System.Collections.Generic.ListExtensions` (or some other name) that would be a place to implement these generic extesnions in a similar way that System.Linq.Enumerable does for IEnumerables, but for `IList<T>`.

It would contain methods like:

* Sort
* Shuffle
* IndexOf
* BinarySearch

This would then become the default place for any algorithms optimized for in-place operations.

I agree some of these methods could operate even with `IReadOnlyCollection`, so the real name of the implementation is open for debate. Maybe we need multiple classes for ICollection/IReadOnlyCollection/IList, etc. 

Please note that this is not a concrete proposal, but things are getting lost in long discussions and I'd like to know from the team if this idea was already discussed internally, and if you want to do add these kind of things, so we could even propose new generic implementations over time in a better way.

**Comment by svick** [comment]
What would happen with the original `List`- and array-specific methods? Does it matter that having only `IList` methods would likely be less efficient?

**Comment by nvivo** [comment]
@svick, extension methods are used only if the class don't implement that same signature.

In a regular project, I would just remove them from Array and List and keep them as extensions. But I'm sure there are 500 reasons to not do that here and how there must be a lot of huge apps that *had* to use reflection to call "IndexOf" and can never be recompiled. There is a fundamental law in the universe that states these apps must exist.

As for the performance, there is no real difference between an instance method and a static method with an argument pointing to an instance. But I may be neglecting some optimizations that can be made in these core types. I don't think they need to be removed though.

**Comment by nvivo** [comment]
I'm closing this, as this is probably not going anywhere based on similar requests.
