### ISSUE TITLE
Console.Readline() doesn't respect disable console echo by 'stty -echo' on Ubuntu

### ISSUE THREAD

**Issue by TingluoHuang** [dotnet/corefx#10985]
I want my Console.Readline() doesn't print out what been read. (I am reading password from user input.)

On Windows, i can achieve by PInvoke SetConsoleMode() before calling Console.Readline() to disable console echo.

I try to do same thing on Ubuntu PInvoke tcsetattr() before Console.Readline(), however it seems like Console.Readline() doesn't respect Ubuntu console echo disable at all.

Here is what i verified On Ubuntu 16.
1. Dotnet new a helloworld console app, add `String read = Console.Readline();` after console.writeline(...)
2. In terminal type 'stty -echo' to disable console echo.
3. type 'Dotnet restore', 'dotnet run', as you can see, since we disable console echo, the dotnet restore and dotnet run you typed will not shows up.
4. When dotnet run start the helloworld app, it will print out HelloWorld! then wait for user input, however what you type now will shows on console.

**Comment by karelz** [comment]
We need someone debug it and find out which Linux settings we do not pay attention to.

**Comment by stephentoub** [comment]
Console.ReadLine disables echo but then manually writes to stdout what was typed.  This is necessary to approximate the same behavior of Console.ReadLine as on Windows.  If you want to achieve what you're asking for, you'll need to effectively write your own ReadLine by using Console.ReadKey (which is basically how ReadLine is implemented on Unix).
