### ISSUE TITLE
How to install corefx libraries/assemblies alongside the coreclr?

### ISSUE THREAD

**Issue by ayuckhulk** [dotnet/corefx#10990]
I am trying to debug a simple hello world app using `lldb` on Ubuntu 15.10 (arm hf) target. I have successfully cross compiled coreclr/corefx/llvm+lldb and I am able to run `corerun` and `lldb` binaries.
However, a can not find any useful information about how to properly install `corefx` build results alongside the `coreclr`.

`<...>/corefx/bin` directory contains folders for different OSes/archs:

```
drwxrwxr-x 236 i.kulaychuk i.kulaychuk 20480 авг 17 21:39 AnyOS.AnyCPU.Release
drwxrwxr-x  12 i.kulaychuk i.kulaychuk  4096 авг 17 21:33 Linux.AnyCPU.Release
drwxrwxr-x   3 i.kulaychuk i.kulaychuk  4096 авг 18 13:35 Linux.arm.Release
drwxrwxr-x   3 i.kulaychuk i.kulaychuk  4096 авг 17 20:57 Linux.x64.Release
drwxrwxr-x  10 i.kulaychuk i.kulaychuk  4096 авг 18 13:35 obj
drwxrwxr-x   6 i.kulaychuk i.kulaychuk  4096 авг 17 21:27 OSX.AnyCPU.Release
drwxrwxr-x   3 i.kulaychuk i.kulaychuk  4096 авг 17 21:43 packages
drwxrwxr-x 131 i.kulaychuk i.kulaychuk 12288 авг 17 21:30 ref
drwxrwxr-x   2 i.kulaychuk i.kulaychuk 28672 авг 17 21:43 TestDependencies
drwxrwxr-x   6 i.kulaychuk i.kulaychuk  4096 авг 17 21:33 tests
drwxrwxr-x  83 i.kulaychuk i.kulaychuk  4096 авг 17 21:36 Unix.AnyCPU.Release
drwxrwxr-x  63 i.kulaychuk i.kulaychuk  4096 авг 17 21:35 Windows_NT.AnyCPU.Release
```

What directories/dlls/so files should be copied to target `coreclr` folder in order for `lldb` (and `libsosplugin.so`) to work?
There are dlls with the same name (`bin/Unix.AnyCPU.Release/System.IO.FileSystem/System.IO.FileSystem.dll` and `bin/AnyOS.AnyCPU.Release/System.IO.FileSystem/net46/System.IO.FileSystem.dll`) so I am a little confused.

**Comment by ayuckhulk** [comment]
@Dmitri-Botcharnikov

**Comment by mellinoe** [comment]
Generally you will want everything that is not in a "framework" subdirectory. For example, `System.IO.FileSystem/net46` is the subdirectory for the `net46` framework, meaning the desktop framework ("Full CLR"). In our build system, binaries for CoreCLR are "the default", so we don't put them in a subdirectory. So, you want the binary from here: `bin/Unix.AnyCPU.Release/System.IO.FileSystem/System.IO.FileSystem.dll`. You should be able to apply the same logic to all of the other binaries as well. When using `corerun`, you should just copy them next to `coreclr.dll/so`.

@weshaggard, @maririos Do we have a build flag to use such that only CoreCLR binaries are built? I know we have one for `OSGroup`.

**Comment by weshaggard** [comment]
>@weshaggard, @maririos Do we have a build flag to use such that only CoreCLR binaries are built? I know we have one for OSGroup.

We don't currently. 

However as part of the work in our dev/api branch I create a project that you can run after a full build that will create a flat layout with all the files. I'm not sure of the current state in master but you can try going and building "layout/dir.proj" and then look under "bin/layout/runtime/netcoreapp1.0/win7-x64". If you need a different runtime then you would need to tweak the RID inside of layout/dir.proj for the netcoreapp1.0 framework.

**Comment by ayuckhulk** [comment]
OK, so for anyone interested here is some code that does the trick (Linux, arm):
```
#!/bin/bash

# From coreclr/tests/runtest.sh:create_core_overlay()

# Actually, this script is used inside docker container
workdir=/root

ARCH=arm
BUILD_TYPE=Debug

CORECLR_DIR="${workdir}/coreclr"
COREFX_DIR="${workdir}/corefx"

CORECLR_BIN="${CORECLR_DIR}/bin/Product/Linux.${ARCH}.${BUILD_TYPE}"
MSCORLIB="${CORECLR_DIR}/bin/Product/Linux.${ARCH}.${BUILD_TYPE}"

COREFX_ANYOS="${COREFX_DIR}/bin/AnyOS.AnyCPU.${BUILD_TYPE}"
COREFX_LINUX="${COREFX_DIR}/bin/Linux.AnyCPU.${BUILD_TYPE}"
COREFX_UNIX="${COREFX_DIR}/bin/Unix.AnyCPU.${BUILD_TYPE}"
COREFX_NATIVE="${COREFX_DIR}/bin/Linux.${ARCH}.${BUILD_TYPE}"

coreOverlayDir="${workdir}/overlay"

if [ -e "$coreOverlayDir" ]; then
    rm -f -r "$coreOverlayDir"
fi
mkdir $coreOverlayDir

for currDir in "${COREFX_LINUX}" "${COREFX_UNIX}" "${COREFX_ANYOS}"; do
    pushd $currDir > /dev/null
    for dirName in $(find . -iname '*.dll' \! -iwholename '*test*' \! -iwholename '*/ToolRuntime/*' \! -iwholename '*/RemoteExecutorConsoleApp/*' \! -iwholename '*/net*' \! -iwholename '*aot*' -exec dirname {} \; | uniq | sed 's/\.\/\(.*\)/\1/g'); do
        cp -n -v "$currDir/$dirName/$dirName.dll" "$coreOverlayDir/"
    done
    popd $currDur > /dev/null
done

cp -f -v "${COREFX_NATIVE}/Native/"*".so" "$coreOverlayDir/" 2>/dev/null
cp -f -v "${CORECLR_BIN}/"* "$coreOverlayDir/" 2> /dev/null
cp -f -v "${MSCORLIB}/mscorlib.dll" "$coreOverlayDir/"
```

I based the code on create_core_overlay function from `coreclr/tests/runtest.sh`. Hello world under `lldb` seems to work after this.

**Comment by weshaggard** [comment]
@ayuckhulk while that may work today (not sure if it actually is 100% correct), it is very fragile and the proper way to actually select the correct assets is via our nuget packages or the reports we use to build our packages (see https://github.com/dotnet/corefx/blob/dev/api/layout/dir.proj#L57).

**Comment by ayuckhulk** [comment]
@weshaggard I see that it's fragile but currently this way is used in coreclr tests on Linux.
Also, what is the correct way to build `layout/dir.proj`? Running `../Tools/msbuild.sh` in `layout` directory produces the following error:
```
...

  No assets found for 'System.Runtime.WindowsRuntime' applicable to '.NETCoreApp,Version=v1.0/win7-x64'.
  No assets found for 'System.Runtime.WindowsRuntime.UI.Xaml' applicable to '.NETCoreApp,Version=v1.0/win7-x64'.
/root/corefx/layout/dir.proj(70,5): error : Additional Directory /root/corefx/packages//runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR/1.0.4-beta-24419-04/runtimes/win7-x64/lib/netstandard1.0 doesn't exist
Done Building Project "/root/corefx/layout/dir.proj" (default targets) -- FAILED.

Build FAILED.

"/root/corefx/layout/dir.proj" (default target) (1) ->
(GetAssetsFromReports target) -> 
  /root/corefx/layout/dir.proj(70,5): error : Additional Directory /root/corefx/packages//runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR/1.0.4-beta-24419-04/runtimes/win7-x64/lib/netstandard1.0 doesn't exist

    0 Warning(s)
    1 Error(s)
```

**Comment by weshaggard** [comment]
>@weshaggard I see that it's fragile but currently this way is used in coreclr tests on Linux.

Yes I realize that and it has been broken many times and I've asked them to find a better way as well :)

Yes layout/dir.proj is also fragile but in a different way, which is that it isn't complete and only works for windows right now, I was just pointing it out as a better example to tweak to make work. 

I agree with you that this is something that we should try and have so I will try to spend some cycles on it, although it might be a little while as I've got a lot of other work on my plate right now.

**Comment by weshaggard** [comment]
After our recent engineering changes we now produce a flat layout folder with the full runtime and corefx bits in it under `bin\runtime\netcoreapp-*` example: `bin\runtime\netcorea-Linux-Debug-x64` that directory can be used for this purpose now.
