### ISSUE TITLE
StartInfo may return incorrect information for *running* processes.

### ISSUE THREAD

**Issue by pallavit** [dotnet/corefx#1100]
ProcessStartInfo.EnvironmentVariables gives an incorrect value for a *running* process. We fetch environment variables via the GetEnviornmentVariables which gives the information of the current process and not of the *running* process. Desktop also has the same behavior.

**Comment by eatdrinksleepcode** [comment]
What is the difference between the current process and the running process?

**Comment by weshaggard** [comment]
In this case by running process @pallvit is talking about another process that you get a Process object from and the current process is the process that is actually running :)

**Comment by davkean** [comment]
My proposal in this case, is to throw InvalidOperationException (with a good error message) when accessing the Process.StartInfo for Processes that you didn't start yourself. This will prevent people being confused by this behavior. 

I just saw another person confused by this internally:

> The problem is I always receives the “StartInfo” field of the Process as null and hence I don’t get the > “Arguments”. I am using “System.Diagnostics.Process” class. Does anyone know how to retrieve the > command line argument of the process if you know the processId?

**Comment by pallavit** [comment]
Fixed as part of https://github.com/dotnet/corefx/pull/1167.
