### ISSUE TITLE
Improve SelectMany behavior when the selector returns null

### ISSUE THREAD

**Issue by GSPP** [dotnet/corefx#11029]
[In the current version](https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/SelectMany.cs#L62) `Enumerable.SelectMany` experiences a `NullReferenceException` when `selector` returns `null`. This is undesirable because it's a confusing crash with a "forbidden" exception type in BCL code. This should be changed.

Example: `foreach(var item in new int[][] { new int[1], null }.SelectMany(x => x)) { }`

The safest approach would be to throw an exception that explains that the user has provided an invalid `selector` that does not obey the contract. Additionally, the [documentation](https://msdn.microsoft.com/en-us/library/bb534336%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) should state the requirement to not return `null`.

An alternative approach would be to treat `null` as an empty sequence. I'm not sure which solution is better. Sometimes, an empty sequence would be very convenient. Sometimes this would hide a bug. Also it's unclear that this can be done due to compatibility concerns. I think throwing a different exception type would be safe enough to take the change.

**Comment by stephentoub** [comment]
cc: @madstorgersen

**Comment by karelz** [comment]
We do not believe the value is worth the extra check (has small perf impact). We do not believe the scenario of passing `null` to `SelectMany` is that common in running applications.
We agree that it might be slightly better in development time, but that's about as much value as we can think of.
If you disagree, feel free to provide additional data.

**Comment by jnm2** [comment]
> Sometimes, an empty sequence would be very convenient. Sometimes this would hide a bug.

It's the hiding a bug part that matters most to me. If I'm _expecting_ null (which I think should be rare because null and empty list are not semantically similar from my perspective), I'd rather encode that via `.SelectMany(x => x ?? Enumerable.Empty<int>())`

**Comment by Thaina** [comment]
@jnm2 It would not convenient when the type is long

`.SelectMany(x => x ?? Enumerable.Empty<SomeLongTypeName>())`

`.SelectMany(x => x ?? Enumerable.Empty<KeyValuePair<string,SomeLongTypeName>>())`

I would want to have this feature supported. Or at least having extension method `EmptyIfNull` for convenient

```C#
public IEnumerable<T> EmptyIfNull<T>(this IEnumerable<T> collection) => collection ?? Enumerable.Empty<T>();
```

**Comment by jnm2** [comment]
@Thaina go for it. It only makes sense to add to the BCL if most people have this issue. Is there evidence of that?

**Comment by GSPP** [comment]
It is very, very rare for the BCL to take the stance that throwing a bad exception type is OK. I cannot think of a single other such case (they might exist).

**Comment by jnm2** [comment]
I know what you're saying, but I still think NRE is consistent and tolerating null is inconsistent with the rest of C#. Null and empty are not automatically semantically the same.

**Comment by Thaina** [comment]
I understand that we should not make breaking change so instead we should have new function for this behavior for convenient

maybe 'SelectFlatten' ?

I think this behavior is much more preferable than current selectmany

**Comment by GSPP** [comment]
I really wonder what code would depend on a NRE being thrown from a SelectMany. I would make the case to simply fix this. I think the perf loss from this null check would be very small and pale in comparison to other perf losses that are routinely accepted by LINQ to improve usability.

**Comment by danmosemsft** [comment]
@vsadov to see above comments.

**Comment by JonHanna** [comment]
With a boneheaded exception like NRE, if it comes from user-code then it isn't good code that depends on it but bad code; I prefer getting an NRE to incorrect but non-throwing behaviour. Are we sure this flattening is always the best thing to do?

**Comment by GSPP** [comment]
I would not advise flattening but rather throwing a non-boneheaded exception. The exception comes from BCL code, not from user code.
