### ISSUE TITLE
CompareAttribute throws TargetParameterCountException and ArgumentException

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#11025]
The following tests demonstrate the bugs, discovered in #10992 

```
[Fact]
public static void Property_HasIndexParameters_ThrowsParameterCountException()
{
    ValidationContext context = new ValidationContext(new CompareObject("a")) { DisplayName = "CurrentProperty" };
    CompareAttribute = new CompareAttribute("Item");
    Assert.Throws<TargetParameterCountException>(() => attribute.Validate("b", context));
}

[Fact]
public static void Property_SetOnly_ThrowsArgumentException()
{
    ValidationContext context = new ValidationContext(new CompareObject("a")) { DisplayName = "CurrentProperty" };
    CompareAttribute = new CompareAttribute("SetOnlyProperty");
    Assert.Throws<ArgumentException>(() => attribute.Validate("b", context));
}

private class CompareObject
{
    public string this[int index] { get { return "abc"; } set { } }
    public string SetOnlyProperty { set { } }
}
```

This is because the check [here](https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/CompareAttribute.cs#L70) for index parameters occurs **after** we call `PropertyInfo.GetValue` [here](https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/CompareAttribute.cs#L51)

We should also add a check to make sure we can read the property before calling `GetValue`.

In both these cases, we should instead return `false` for `IsValid`

/cc @stephentoub

**Comment by ajcvickers** [comment]
We can see the value in this, but it seems like quite an esoteric corner case. We would consider a pull request to make this change, but it is not something we are going to work on at this time.

**Comment by ajcvickers** [comment]
Assigning to @lajones who is processing the PR.
