### ISSUE TITLE
Expose serialization primitives on .NET Native 

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#11035]
Remove ApiCompatBaseline.netcore50aot.txt / ApiCompatBaseline.uap101aot.txt baselined errors once resolved, e.g. that CultureNotFoundException doesn't implement ISerializable in the implementation.
- src\System.Globalization\src\ApiCompatBaseline.uap101aot.txt
- src\System.Threading.Tasks\src\ApiCompatBaseline.uap101aot.txt
- etc.

**Comment by kouvel** [comment]
Edited to include some specific ApiCompat baseline files at are in the process of being added

**Comment by danmosemsft** [comment]
@stephentoub IIUC this boils down to "refresh baseline files when bringing .NET Native up to NS2.0". We don't need an issue for the latter, and the baseline update happens naturally either as part of the change or if overlooked soon after (eg with /p:baselineallapicompaterror=true).

So I'm not sure it's worth having this issue. What do you thinK?

**Comment by stephentoub** [comment]
Sounds find.
