### ISSUE TITLE
Coverage runs failing since ProcessTests changes

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1103]
@pallavit, since the recent ProcessTests cleanup changes got committed, all of our code coverage runs have hung.  They've all hit an AV exception, followed by what appears to be OpenCover hanging during its subsequent processing:

```
xUnit.net console test runner (32-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.
  
  Discovering: System.Diagnostics.Process.Tests
  Discovered:  System.Diagnostics.Process.Tests
  Starting:    System.Diagnostics.Process.Tests
  
  Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
     at System.AppDomain.SetupDomain(Boolean allowRedirects, String path, String configFile, String[] propertyNames, String[] propertyValues)
     System.Diagnostics.ProcessTests.ProcessTest.Process_HasExited [FAIL]
        Process_HasExited001 failed
        Stack Trace:
           d:\j\workspace\dotnet_corefx_coverage_windows\src\System.Diagnostics.Process\tests\System.Diagnostics.Process.Tests\ProcessTest.cs(178,0): at System.Diagnostics.ProcessTests.ProcessTest.Process_HasExited()
  Finished:    System.Diagnostics.Process.Tests
  
  === TEST EXECUTION SUMMARY ===
     System.Diagnostics.Process.Tests  Total: 34, Errors: 0, Failed: 1, Skipped: 0, Time: 120.241s
  Committing...
  Visited Classes 23 of 35 (65.71)
  Visited Methods 186 of 357 (52.1)
  Visited Points 1570 of 2998 (52.37)
  Visited Branches 515 of 1161 (44.36)
  
  ==== Alternative Results (includes all methods including those without corresponding source) ====
  Alternative Visited Classes 27 of 40 (67.5)
  Alternative Visited Methods 193 of 415 (46.51)
```

@sawilde, FYI.

**Comment by stephentoub** [comment]
(I've temporarily disabled code coverage for the Process tests until this is fixed.  I was able to repro the AV locally as well with just a few attempts.)

**Comment by sawilde** [comment]
Have these just started failing and if so do we know from when?

**Comment by stephentoub** [comment]
@sawilde, they just started failing end of last week.  We do two code coverage runs in the lab a day, once in the morning and once in the evening... they were green through to Thursday night, and then started failing Friday morning.  I suspect it had something to do with #1087, #1084, or some combination of the two.  The fact that it's AV'ing inside of SetupDomain makes me a bit suspicious of the code coverage tool, but we had a day of green runs after #1087; it wasn't until #1084 that things appear to have fallen apart, but it could of course just be a coincidence, or it could be some combination of these.

**Comment by pallavit** [comment]
Thanks Stephen. I will try to repro\investigate the crash locally.

**Comment by sawilde** [comment]
no worries I'll also have a look

**Comment by stephentoub** [comment]
Thanks, Shaun; appreciated.

**Comment by pallavit** [comment]
@sawilde Did you get a chance to look at it? I spend some time investigating with no concrete results :|

**Comment by sawilde** [comment]
I did and I commented on this related [thread](https://github.com/dotnet/corefx/pull/1111).

In summary - it looks like a race condition I could reduce the occurrence of the problem by playing with the value sent to Sleep. Or we can just block the profiler from instrumenting the extra process; it is not important to the coverage results AFAIK.

**Comment by stephentoub** [comment]
@sawilde, it's a race condition in the implementation of OpenCover?  I think I hear you saying that's the case and that since we don't know yet what the actual source of the race condition is and can't get a good repro that we should work around it for now as I'd initially planned to, by suppressing the flow of these environment variables to the child processes... is that correct?

**Comment by sawilde** [comment]
I am not sure where the race condition is but by adding delays to the tests seems to mitigate the issue - perhaps Openover is introducing a race condition into the test during the act of instrumenting the code and gathering results.

**Comment by pallavit** [comment]
@stephentoub Given the situation, I think we can enable the code coverage for System.Diagnostics.Process and remove the spawned process from the code coverage (the change that you had done earlier). Thoughts?

**Comment by stephentoub** [comment]
@pallavit, ok, I'll redo that fix.  I'll reassign this issue to me to take care of it.

**Comment by pallavit** [comment]
@stephentoub Thanks :)
