### ISSUE TITLE
Cannot reset DisplayName on ValidationContext

### ISSUE THREAD

**Issue by tuespetre** [dotnet/corefx#11044]
I do a lot of work with console applications and I like to use validation attributes and `IValidatableObject` to take advantage of framework-supplied validations rather than reinventing the wheel or using a third-party library.

When looping through an object's properties to validate them, I can set the context's `MemberName` property appropriately each run through, but any non-successful validation results may return a nonsensical message since the validators use the `DisplayName` property to format the message, and the `DisplayName` property getter caches its return value the first time it is used. In addition to this, the `DisplayName` property cannot be reset as the setter will throw an `ArgumentNullException`.

I could envision any of the following approaches to resolve this:
- Allow setting `DisplayName` to `null` or `""`
- Set the `_displayName` field to `null` whenever `MemberName`/`_memberName` are changed
- Offer a method like `Reset(bool clearItems = true)` to be a bit more explicit

**Comment by ajcvickers** [comment]
We can see the value of making this change, although it seems like using the data annotation in this way (mutating it for different members) is quite unusual. We are not going to work on this, but we would consider a PR for option 2--that is, fix the caching such that the display name is re-calulated if needed.

**Comment by tuespetre** [comment]
@ajcvickers it does seem weird. Even though it probably makes a 💩 of a difference for my use case, I was being allocation-conscious

**Comment by ajcvickers** [comment]
@tuespetre Oops. Looks like we broke stuff with the PR for this. There are two issues:
* Some MVC tests were relying on the old behavior. This is strange, but indicates how hard it is to make any kind of functional change without breaking somebody.
* Both properties can be set explicitly. Setting DisplayName first and then setting MemberName will make DisplayName null.

I have asked @lajones to revert this change. However, on discussion with @divega I think we would take a change to allow DisplayName to be explicitly set to null. This should not break any existing code but would allow you to use the class in the way you want by explicitly setting the DisplayName to null after changing the MemberName.

**Comment by tuespetre** [comment]
@ajcvickers cool, thanks for the update and sorry for the bump in the road :bow:

**Comment by divega** [comment]
@tuespetre are you planning to give this another try based on this:

>  I think we would take a change to allow DisplayName to be explicitly set to null. 

Otherwise I am not sure it is worth keeping this issue open.

**Comment by tuespetre** [comment]
@diveg I will plan on that; it will be likely after next week when I am able to get around to it.

**Comment by ajcvickers** [comment]
Closing this as it's not something we plan to implement. We would consider a PR (100% non-breaking) but keep in mind that any new functionality will deviate the behavior from the .NET Framework.
