### ISSUE TITLE
XML .Save() method missing option to use filename

### ISSUE THREAD

**Issue by ikelso** [dotnet/corefx#11045]
It seems that System.IO.Stream, System.IO.TextWriter, and System.Xml.XmlWriter are still options, but using string filename has been removed.

**Comment by danmosemsft** [comment]
@ikelso What type(s) are you looking for Save(filename) on? If it's XmlDocument, it's there now, but there's no reference assembly yet. This is part of the big bringback of API expected in 1.2.

**Comment by karelz** [comment]
@danmosemsft says it's done.
