### ISSUE TITLE
Update CLI version to support Ubuntu on Windows

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#11058]
Windows preview build 14905 now has enough kernel support to build/test CoreFx in the Ubuntu on Windows environment.  However, the CLI build we are using still has [the "execstack" issue](https://github.com/dotnet/coreclr/issues/4048), and so will not run on Ubuntu on Windows.  This was [fixed in the CoreCLR repo](https://github.com/dotnet/coreclr/pull/4257) in April, and current public CLI builds seem to have the fix.

Can we update the CLI version in CoreFx to include the fix for https://github.com/dotnet/coreclr/issues/4048?

**Comment by ericeil** [comment]
Just to be clear, I'm referring to the CLI that gets installed into the Tools directory.

**Comment by weshaggard** [comment]
@crummel @dagood are going to be updating the CLI to what we shipped in .NET Core 1.0 RTM. Is the fix included in that version?

**Comment by ericeil** [comment]
> Is the fix included in that version?

Yes, I think it is.

**Comment by ericeil** [comment]
Is there an ETA for getting this updated?

**Comment by dagood** [comment]
Getting buildtools on RTM shared framework is tracked by https://github.com/dotnet/buildtools/issues/954. It's been preempted repeatedly but I got a RTM buildtools running (doing a build on Windows) yesterday afternoon. I'm aiming for a PR this morning although there might be delays in making sure it's compatible across repos/platforms.

**Comment by ericeil** [comment]
#11387 seems to have enabled builds in Bash on Windows.
