### ISSUE TITLE
HttpClient.SendAsync null exception

### ISSUE THREAD

**Issue by stevejgordon** [dotnet/corefx#11063]
I am building an ASP.NET core web api which is using HttpClient from some custom middleware to call a service endpoint using SendAsync.

If the endpoint is available it works perfectly. If the endpoint is unavailable for any reason (wrong url for example) then I get back a null exception within my catch,

```
try
{
	var request = new HttpRequestMessage(HttpMethod.Get, "http://someurl.com");
	request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
	
	var response = await _httpClient.SendAsync(request).ConfigureAwait(false);

	if (response.IsSuccessStatusCode)
	{
		var payload = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
		var responseModel = JsonConvert.DeserializeObject<ResponseContainerModel>(payload);

		if (!string.IsNullOrEmpty(responseModel?.Result))
		{
			// do stuff
		}
	}
}
catch (Exception ex)
{
	// ex is null
}
```

**Comment by stevejgordon** [comment]
Added a simple ASP.NET core web api project to reproduce the issue - https://github.com/stevejgordon/HttpClientBug

**Comment by stevejgordon** [comment]
![image](https://cloud.githubusercontent.com/assets/3669103/17896212/a74f7596-6947-11e6-9f0a-667aca4e3302.png)

**Comment by davidsh** [comment]
Can you clarify what you mean by "null exception"?  The comment in your source code says "ex is null".  Is the exception object itself null?  What is the stack trace or other specific information.  Perhaps print out ex.ToString() ?  This will give us more information.

Is this project for Windows or Linux?

**Comment by davidsh** [comment]
So, I ran your project above.  If I leave the source code as-is, there is no error at all.  If I change the hostname from "localhost" to "localhostx" (which doesn't exist of course), I will get into the `catch` block.

I don't see a null exception.  I set a breakpoint on the `catch` line.  At that point, `ex` is null.  But step one line to the first opening brace and you will see a valid `ex` object:

![image](https://cloud.githubusercontent.com/assets/7684835/17901167/1da713c4-6917-11e6-89c5-6e4eced14ae7.png)

![image](https://cloud.githubusercontent.com/assets/7684835/17901185/318b19da-6917-11e6-96fe-74774d21766b.png)

**Comment by svick** [comment]
@davidsh Is this then an issue with the debugging experience? Maybe the debugger shouldn't let you place a breakpoint on the `catch` line, and show that `ex` is `null`?

**Comment by davidsh** [comment]
>Is this then an issue with the debugging experience? 

I think you will find this experience the same with .NET Framework (Desktop).  It is not a CoreFx issue, per se.

Feel free to submit feedback to the Visual Studio team.  You can use UserVoice or Connect for that.  Thx.

**Comment by stevejgordon** [comment]
@davidsh Many thanks for taking a look so quickly. If it's that simple I'm very sorry for wasting your time. I'll double check in my original codebase tomorrow as I was trying to assign ex to a logger message originally and that was blowing up for me.

I'm a bit curious with the CanceledException. Should HttpClient not give a web based exception to advise that the url was unavailable? Something so we can act based on it appropriately?

**Comment by davidsh** [comment]
>Should HttpClient not give a web based exception to advise that the url was unavailable?

The `TaskCanceledException` is occuring because in this particular failure case (DNS name not resolving), it is "timing out".  HttpClient has a default timeout.  So, that timeout is triggering first.  If the timeout was longer, then you would get a different error, probably an HttpRequestException with inner exception WinHttpException representing some DNS resolution failure.

Our error/exception story is not perfect right now with HttpClient, See #2384 for reference. We hope to improve it in the future.

**Comment by stevejgordon** [comment]
@davidsh Thanks for explaining. I can work with that if I do at least get the exception so I'll fire it up again tomorrow when I'm in the office. I appreciate the support. Will dig into the code-base a bit a learn some more about it all soon.

**Comment by stevejgordon** [comment]
Can I just also ask if the approach of registering the singleton HttpClient for use throughout the web api is reasonable? We'll be running this small restful service inside a Docker container. As well as this middleware it will call out to other endpoints to respond to requests so we want to be as fast and efficient as possible with our use of the client.

**Comment by davidsh** [comment]
>Can I just also ask if the approach of registering the singleton HttpClient for use throughout the web api is reasonable?

For best purpose, you should re-use existing HttpClient instance(s).  TCP connections are pooled and reused, for example, only when using the same HttpClient instance. So, where possible, reuse the HttpClient instance.
