### ISSUE TITLE
Port Remainder of TimeZoneInfo

### ISSUE THREAD

**Issue by hann013** [dotnet/corefx#11075]
There are some members in TimeZoneInfo that still need to be implemented, for they require a Linux implementation:

```
M:System.TimeZoneInfo.ConvertTimeBySystemTimeZoneId(System.DateTime,System.String)
M:System.TimeZoneInfo.ConvertTimeBySystemTimeZoneId(System.DateTime,System.String,System.String)
M:System.TimeZoneInfo.ConvertTimeBySystemTimeZoneId(System.DateTimeOffset,System.String)
```

**Comment by hann013** [comment]
cc @danmosemsft

**Comment by justinvp** [comment]
Could the Linux implementation of `TimeZone` be built on top of the existing `TimeZoneInfo` functionality?

**Comment by tarekgh** [comment]
@justinvp that I'll investigate when I come to this issue.

**Comment by tarekgh** [comment]
https://github.com/dotnet/coreclr/pull/8074
