### ISSUE TITLE
Official builds should place tags on what was built

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#1107]
We're eventually going to want to be able to answer the question of "what code was in build [whatever]?".  It seems the answer to this in git is tags.  As an example, https://github.com/torvalds/linux, click on the branches dropdown and change to the tabs tab.

Supporting documentation: http://git-scm.com/book/tr/v2/Git-Basics-Tagging

**Comment by akoeplinger** [comment]
FYI, the aspnet team also uses git tags and GitHub provides the ability to attach release notes to each tag, which makes this quite valuable: https://github.com/aspnet/XRE/releases

**Comment by sharwell** [comment]
It would be really nice to see which commit [System.Collections.Immutable 1.1.34-rc](https://www.nuget.org/packages/System.Collections.Immutable/1.1.34-rc) was built from, because I'd like to update [Rackspace.Collections.Immutable](https://www.nuget.org/packages/Rackspace.Collections.Immutable/1.1.33-beta) to match it.

**Comment by ellismg** [comment]
@nguerrera Can you easily answer @sharwell's question about what commit we used for the nuget package?

**Comment by jhendrixMSFT** [comment]
I believe it was 03105dc.

**Comment by jhendrixMSFT** [comment]
Hmm not sure how this became closed.

**Comment by nguerrera** [comment]
The rc builds of both immutable and metadata were made with master synced to 664ea075339e24bb7e816e2de338d449d322a3

Yes, there should be tags.

**Comment by weshaggard** [comment]
We do tags for releases but for any general official builds we just put sha's into the binary version info. So you can figure out what source code was used to build it.
