### ISSUE TITLE
Optimize Code using Enum.Parse 

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#11073]
ReflectionXmlSerializationReader uses Enum.Parse when deserializing enum values. Enum.Parse is VERY VERY slow. We will need to replace this with something better in the long run.

**Comment by justinvp** [comment]
> Enum.Parse is VERY VERY slow

Can `Enum.Parse` perf be improved?

**Comment by shmao** [comment]
@justinvp That's a good idea. I'll see if I can find any alternatives for Enum.Parse. If not, we can try to improve Enum.Parse.

**Comment by mconnew** [comment]
Enum.ToString() was improved in dotnet/coreclr#6645 so it might be worth spending the effort there to improve the parsing speed too.

**Comment by karelz** [comment]
Next steps: First verify it still makes sense to avoid Enum.Parse. If yes, implement it. If not, close the issue.

**Comment by TylerBrinkley** [comment]
I've just released version 1.0.0 of [Enums.NET](https://github.com/TylerBrinkley/Enums.NET), a high-performance type-safe .NET enum utility library.

On the .NET Framework it takes about 1/3 of the time to parse an enum member name compared to System.Enum.

Enums.NET is available on [NuGet](https://www.nuget.org/packages/Enums.NET/) and is compatible with .NET Standard 1.0+ as well as .NET Framework 2.0+.

**Comment by karelz** [comment]
Very cool @TylerBrinkley! Thanks for sharing the news.
Are there any improvements you think would be beneficial to move into CoreFX from your project? (compatibility, low impact on API surface)

**Comment by TylerBrinkley** [comment]
@karelz I've just created the proposal #15453 to move many of the improvements my library provides into CoreFX. I'd greatly appreciate any feedback.

**Comment by karelz** [comment]
Ah, I was wondering where it came from :). I let area owners to provide the feedback first. Thanks!
