### ISSUE TITLE
System.Diagnostics.ProcessThread.StartAddress reports incorrect address on Linux

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#11072]
We get the value of `ProcessThread.StartAddress` by looking at `/proc/[pid]/task/[tid]/stat`, parsing out the `startstack` field from that file.  However, this gives the address of the *stack*, not the ["...address of the function that the operating system called that started this thread."](https://msdn.microsoft.com/en-us/library/system.diagnostics.processthread.startaddress(v=vs.110).aspx)

It doesn't look to me like the value we need here is actually available on Linux or OSX.  From the test code, it looks like we already expect `null` on OSX.  Maybe we should change the Linux implementation to return `null` as well, or change both to throw `PlatformNotSupportedException`.

**Comment by ericeil** [comment]
Note that I found this by running the System.Diagnostics.Process tests on Ubuntu on Windows, which reports 'null' for this field in the 'stat' file.

**Comment by ericeil** [comment]
@stephentoub, do you have an opinion as to whether we should be returning `null` vs. throwing here?

**Comment by stephentoub** [comment]
I'd suggest IntPtr.Zero rather than throwing.  This is primary about gathering diagnostic information, and IntPtr.Zero is fairly obviously a sentinel, plus it's what we already do on OSX, and I think we'd want to avoid adding exceptions in code like this we've already shipped.

Good catch.
