### ISSUE TITLE
Files in use warning

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#11071]
Running in Posh-Git `.\build` I'm getting the following:

```
S:\c2\Tools\net45\roslyn\tools\Microsoft.CodeAnalysis.CSharp.dll - Access is denied.
S:\c2\Tools\net45\roslyn\tools\Microsoft.CodeAnalysis.dll - Access is denied.
S:\c2\Tools\net45\roslyn\tools\Microsoft.CodeAnalysis.VisualBasic.dll - Access is denied.
S:\c2\Tools\net45\roslyn\tools\Microsoft.DiaSymReader.Native.amd64.dll - Access is denied.
S:\c2\Tools\net45\roslyn\tools\System.Reflection.Metadata.dll - Access is denied.
S:\c2\Tools\net45\roslyn\tools\VBCSCompiler.exe - Access is denied.
S:\c2\Tools\net45\roslyn\tools - The process cannot access the file because it is being used by another process.
```

Did some investigation and found that the VBCSCompiler.exe is holding these:
```
S:\c2 [ssl ≡]> C:\sysint\handle.exe S:\c2\Tools\net45\roslyn\tools\Microsoft.CodeAnalysis.CSharp.dll

Handle v4.0
Copyright (C) 1997-2014 Mark Russinovich
Sysinternals - www.sysinternals.com

VBCSCompiler.exe   pid: 776    type: File           510: S:\c2\Tools\net45\roslyn\tools\Microsoft.CodeAnalysis.CSharp.dll
```

Killing the process makes everything work.
I may have stopped a build using Ctrl+C at some time prior to getting this.

@weshaggard @ellismg PTAL

**Comment by weshaggard** [comment]
I thought @maririos had done something to kill VBCSCompiler at one point.

**Comment by maririos** [comment]
>I thought @maririos had done something to kill VBCSCompiler at one point. 

Yes. Every time we run clean, we kill it. https://github.com/dotnet/corefx/blob/master/clean.cmd#L5
Before we had the option `clean -e` to only kill that process, but we removed it and now it is the default behavior everytime we want to clean something.

**Comment by CIPop** [comment]
Thanks @weshaggard @maririos! I'll give that a try next time.
