### ISSUE TITLE
Cannot debug System.IO.Compression under Visual Studio

### ISSUE THREAD

**Issue by qmfrederik** [dotnet/corefx#11087]
I'm trying to pinpoint what appears to be a bug in .NET Core, where the `Stream` returned for a `ZipEntry` is truncted by a couple of bytes in a very rare scenario.
The behavior is different from NetFX and the NetFX behavior seems to be the correct one.

I've done the following
- `git clone corefx`
- `init-tools.cmd`
- `build.cmd`

That builds the repo & the tests pass, so I'm pretty sure the checkout I have is in a consistent state.

Next, I 
- Open `src\System.IO.Compression\System.IO.Compression.sln` with Visual Studio 2015 Update 3 which also has the Windows 10 tools installed.
- Set the configuration to `Debug_Windows`
- Set `System.IO.Compression.Tests` as the Startup project
- Hit F5 to start debugging

At this point, the tests load correctly and I can set breakpoints and step through the test project.

However, for the `System.IO.Compression.dll` assembly itself, it seems that the test project takes the assembly from a NuGet package rather than the version which was just built by Visual Studio:
- In the Modules window, the timestamp for the `System.IO.Comrpession.dll` indicates it was built to days ago
- The symobls are not loaded, and when trying to load the symbols, the original path is set to `D:\A\_work\4\s\bin\obj\Windows_NT.AnyCPU.Release\System.IO.Compression\System.IO.Compression.pdb`, which looks like a build server path

So, I'm sure I've missed something that caused the test to run against a NuGet package instead of the `System.IO.Compression.dll` which I built locally, but I can't figure out what.

Any guidance? I read through the Developer Guide but couldn't find much

**Comment by ianhays** [comment]
It doesn't even compile for me:

```Could not locate compile assets for any of the frameworks .NETStandard,Version=v1.3	System.IO.Compression.Tests```

**Comment by mellinoe** [comment]
@ianhays  I see the same thing. I also now see an additional error after switching configurations a few times:

```
2>D:\OSS\corefx\Tools\packageresolve.targets(31,5): error MSB4018: The "IsRestoreRequired" task failed unexpectedly.
2>D:\OSS\corefx\Tools\packageresolve.targets(31,5): error MSB4018: System.MissingMethodException: Method not found: 'Void NuGet.Packaging.VersionFolderPathResolver..ctor(System.String)'.
2>D:\OSS\corefx\Tools\packageresolve.targets(31,5): error MSB4018:    at Microsoft.DotNet.Build.Tasks.IsRestoreRequired.Execute()
2>D:\OSS\corefx\Tools\packageresolve.targets(31,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2>D:\OSS\corefx\Tools\packageresolve.targets(31,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

as well as
```
2>D:\OSS\corefx\Tools\PackageLibs.targets(34,5): error : Could not locate compile assets for any of the frameworks .NETStandard,Version=v1.3
```
The first looks like a problem with running one of the tasks against full-MSBuild.

@karajas I think this might be more fallout from switching to pkgproj's for test references. Have you ever seen the above message? The project builds and tests fine from the command line, so something must be wrong with the some properties that VS is using from the `Windows_Debug` configuration.

**Comment by karajas** [comment]
This message above is a result of the pkg proj conversion but the F5 from VS was still not working prior to this I believe. I think @Priya91 has had some experience debugging this, but a workaround is still using command line at the moment.

**Comment by ViktorHofer** [comment]
The test project is successfully launching in debugging mode with v2.0.
