### ISSUE TITLE
[Proposal] SemaphoreSlim.TryAcquire

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#11084]
SemaphoreSlim could do with a non-blocking, non-waiting, non-allocating TryAcquire that returns false if not available.

e.g.

`bool TryAcquire(out int remaining)`

**Comment by stephentoub** [comment]
> non-blocking, non-waiting, non-allocating that returns false if not available

How is that different from Wait(0)?

**Comment by benaadams** [comment]
If you use it with `.WaitAsync()` and there are async waiters it will block? https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/SemaphoreSlim.cs#L363-L378 rather than failing fast.

**Comment by benaadams** [comment]
(Though that could be a bug?)

**Comment by stephentoub** [comment]
> and there are async waiters it will block?

No, it won't.  Do you have a repro that suggests it does?
```C#
using System;
using System.Threading;

class Program
{
    static void Main()
    {
        var s = new SemaphoreSlim(0);
        s.WaitAsync();
        s.WaitAsync();
        s.WaitAsync();
        Console.WriteLine(s.Wait(0));
        Console.WriteLine(s.WaitAsync(0).Result);
    }
}
```

**Comment by redknightlois** [comment]
@benadams no, based on the code it shouldn't block. It will create an awaiter anyways and  ```.WaitAsync(0)```.
@stephentoub there is still merit in the TryAcquire() addition. Almost no allocations would happen, and it will return faster as the ```.Wait()``` will not get promoted into a ```.WaitAsync(0)```.

**Comment by stephentoub** [comment]
> there is still merit in the TryAcquire() addition

I disagree.  I'd be fine with the Wait(0) path being optimized if there are key scenarios for doing so and opportunity to do so, but there's no fundamental reason a TryAcquire should be any faster than Wait(0).

**Comment by redknightlois** [comment]
If changing the semantic is allowed, its definitely better to skip the promotion and fail immediately to avoid the allocations. I dont know what implicancies that may have though.

**Comment by stephentoub** [comment]
How does it change the semantics? And what allocations are you referring to?

**Comment by redknightlois** [comment]
Given that the Wait(0) is not going to be promoted to an async waiter, there is no wait anymore and cancellation token allocation is useless. Also because you are going to stop early before being promoted into an async waiter, you dont allocate the waiter and you change how the semaphone works today (which I dont know what implicancies that may have), therefore from the outside there is a 'potential' change in the current semantics. If we even skip the SpinWait (would be kinda useless if you know you are going to fail anyways) there is certainly a huge difference in how it works today. 

Allocations: https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/SemaphoreSlim.cs#L321
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/SemaphoreSlim.cs#L366

**Comment by stephentoub** [comment]
> cancellation token allocation

There is no CancellationToken allocation today.  First, CancellationToken is a struct.  Second, registering with a default CancellationToken (which is what you have when you don't pass a token to Wait) is a nop.

> you dont allocate the waiter 

What waiter?  What's the specific type being allocated and where that you're concerned about?

**Comment by stephentoub** [comment]
> If we even skip the SpinWait 

By that argument, any change to performance is a change to semantics.  We're fine with such "semantic" changes.

**Comment by stephentoub** [comment]
FWIW, there are a few allocations that occur, but they're easily avoided just by adding a special case here for when the timeout is 0:
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/SemaphoreSlim.cs#L624

**Comment by redknightlois** [comment]
> By that argument, any change to performance is a change to semantics. We're fine with such "semantic" changes.
I am a little wary of changes in multithreaded code (being burned in the bad way).

> CancellationToken is a struct.
I didnt know that, I never looked closely to that code. Its good to know. 

> a special case here for when the timeout is 0.
Would achieve the same result, yes.

**Comment by benaadams** [comment]
Happy with that approach https://github.com/dotnet/coreclr/pull/6898
