### ISSUE TITLE
Add "CurrentBranch" to dependency verification to make dev/api merge cleaner

### ISSUE THREAD

**Issue by dagood** [dotnet/corefx#11098]
This tracks picking up the feature merged into buildtools with https://github.com/dotnet/buildtools/pull/978 that adds an auto-updated `CurrentBranch` property for each build info. It would make a merge from dev/api back into master cleaner. The idea behind it is described here: https://github.com/dotnet/corefx/pull/10970#discussion_r75404356.

I have to look into how this will practically affect the merge and how the change needs to flow in git for the best effect. It would be possible to do this as part of https://github.com/dotnet/corefx/pull/10970 but I'd rather not block on it.

/cc @weshaggard

**Comment by dagood** [comment]
To add a bit more detail about what this actually does: when merging `dev/api` back into `master`, there are two choices: keep `master`'s sha and build-info branch, or keep `dev/api`'s sha and build-info branch. The only feature this issue adds is that if the merger chooses to keep `dev/api`'s dependency, the next auto-upgrade will switch it back to `master`.

To clean up the inevitable merge conflict on the `*CurrentRef` value, I think we should put `*CurrentRef` and `*CurrentBranch` on the same line. Then, when there's a ref conflict, the merger's resolution has the ref and branch in sync. (Typically there won't be a conflict on the branch because it's only changed in the dev branch.) It's not good msbuild style, but it would make the merge simpler.

**Comment by weshaggard** [comment]
Wouldn't having them on 2 lines next to each other accomplish the same thing?

**Comment by dagood** [comment]
The merge conflict does technically span the two lines, but kdiff3 auto-resolves the second line to the changed `dev/api` and only makes me choose the sha to keep. So I guess it depends on whether or not the dev doing the merge is using a mergetool.

**Comment by danmosemsft** [comment]
@dagood is this still relevant now dev/api is gone?

**Comment by dagood** [comment]
It's still something that we can improve if we ever want branches like dev/api again. (Branches that have official builds and depend on their previous official build.) It's fairly minor and I've got other things on my plate so I'm unassigning it from myself for now.
