### ISSUE TITLE
Coreclr crash due to double freeing Openssl handles

### ISSUE THREAD

**Issue by bretambrose** [dotnet/corefx#11107]
Coreclr crashes due to a double Dispose of an openssl handle if the openssl function PKCS12_parse (called by Corefx's CryptoNative_Pkcs12Parse) returns false.

When Openssl's PKCS12_parse fails, it frees the handles that it allocated into *pkey and *cert.  But those output parameters do not get nulled by either Openssl or the corefx PAL shim and so the freed handles become valid managed handles.  When those managed handles get disposed it leads to a second call to free on them, crashing coreclr.

Repro: In theory it should be possible to write a test that exercises this, but you would need to come up with binary data that passes the initial call to d2i_PKCS12 but then fails in PKCS12_parse.  This is beyond my meager time, understanding, and abilities.  I encountered this issue when accidentally using a (crippled) version of Openssl that had rc2 support removed (./Configure no-rc2); in that case, PKCS12_parse would fail for all inputs, exposing the issue.

Proposed Solution: Add an else block to the success check in CryptoNative_Pkcs12Parse that pushes nullptr into both *pkey and *cert.

**Comment by bartonjs** [comment]
Is PKCS12_parse assigning them then deallocating the objects, or is this a case of the failure path being uninitialized memory?  (If the latter, the better fix is probably to explicitly null them out first, instead of in the else; that way we'll still prevent leaks if the failure path allocated)

**Comment by bretambrose** [comment]
If cert and pkey are non-null then PKCS12_parse assigns null into them at the top of the function:


    if (pkey)
        *pkey = NULL;
    if (cert)
        *cert = NULL;



On error, they are freed but not cleared:


    
    if (pkey)
        EVP_PKEY_free(*pkey);
    if (cert)
        X509_free(*cert);
    X509_free(x);
    sk_X509_pop_free(ocerts, X509_free);
    return 0;

**Comment by bartonjs** [comment]
@bretambrose Great, thanks for checking.  (Well, not "great", but "great that we know for sure")

**Comment by bretambrose** [comment]
I can make a pull request with a fix if you'd like.

**Comment by bartonjs** [comment]
@bretambrose That'd be great.  https://github.com/bretambrose/corefx/commit/ec8080d5ad014895db4443445a6cb37f2621b21b looks good to me; if you want to go ahead and create a PR off of that.
