### ISSUE TITLE
corefx helloworld

### ISSUE THREAD

**Issue by cheers00** [dotnet/corefx#1110]
Hi, I want to use corefx components and coreclr in my command line program. I started with corefxlab helloworld and I tried to add corefx from nuget manager. I was able to find corefx components but when I tried to install, I get the following error message. How do I overcome this?

```
Could not install package 'System.Globalization 4.0.10-beta-22231'. 
You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', 
but the package does not contain any assembly references or content files that are compatible 
with that framework. For more information, contact the package author.
```
Also, how do I install my private coreCLR and corefx components to my commandline program?

I am using VS 2015 CTP6.

Thanks

**Comment by KrzysztofCwalina** [comment]
The hello world demo does not yet support adding arbitrary other packages. We will try to fix it in the upcoming weeks.

**Comment by KrzysztofCwalina** [comment]
I moved the demo to new set of more reliable packages. 
See instructions at https://github.com/dotnet/corefxlab/wiki/.NET-Core-Console
Please used packages from the feed described on the wiki page. Also, the wiki page describes how to debug issues with this demo and missing packages.
Let me know if you still run into problems.
