### ISSUE TITLE
Several Corefx tests drop LD_LIBRARY_PATH from the environment when using RemoteInvoke

### ISSUE THREAD

**Issue by bretambrose** [dotnet/corefx#11103]
If running coreclr from within an environment where LD_LIBRARY_PATH is used to control how dependent native libraries are resolved (ie, using non-system versions of openssl, curl, icu, etc...), tests that clear the environment used by RemoteInvoke do not work properly because LD_LIBRARY_PATH is lost.

The affected tests are System.Globalization.Tests.CurrentCultureTests.CurrentCulture_BasedOnLangEnvVar and System.Globalization.Tests.CurrentCultureTests.CurrentCulture_DefaultWithNoLang

Potential solution: In addition to "HOME" also copy "LD_LIBRARY_PATH" into the remote environment.

**Comment by stephentoub** [comment]
Thanks, @bretambrose.  Your potential solution seems reasonable to me.  Please feel free to submit a PR for that.
