### ISSUE TITLE
While building the test project it throws CS5001 error when emitEntryPoint is set to true

### ISSUE THREAD

**Issue by msusur** [dotnet/corefx#11110]
I'm trying to migrate my existing project to .Net Core. I have two projects one is for the library and the other one is for tests. While building the tests project I receive "CS5001: Program does not contain a static 'Main' method suitable for an entry point". I have set the **buildOptions** and **emitEntryPoint** as well as **testRunner** values in the [project.json](https://github.com/msusur/Magpie-API/blob/dotnetcore-migration/tests/Magpie.Library.Tests/project.json). Can this be a bug? or if I'm missing something in the configuration, don't you think it should be more helpful with the error message?

My dot net version is 1.0.0-preview2-003121, you can check [this repo](https://github.com/msusur/Magpie-API/tree/dotnetcore-migration) to reproduce the issue.

**Comment by mellinoe** [comment]
`emitEntryPoint` means that your project DOES expose a `Main` method. For a test project, you don't want that.

**Comment by msusur** [comment]
Thanks @mellinoe I don't know how I missed this... It worked, cheers!
