### ISSUE TITLE
M:System.Security.Cryptography.HMACSHA1.#ctor(System.Byte[],System.Boolean)

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#11121]
Ignore boolean. Instructs implementation to use SHA1Managed, but we use a native HMAC implementation. Mark browseable.never.

'''
M:System.Security.Cryptography.HMACSHA1.#ctor(System.Byte[],System.Boolean)
'''

@bartonjs This is in 4% of the tier 1. Okay with bringing it?

**Comment by bartonjs** [comment]
Not thrilled; but if it's Browsable(Never) I'll just grunt and nod :smile:.

Since we won't actually have a managed implementation, the boolean should just be ignored.
