### ISSUE TITLE
ResourceManager IgnoreCase support on Core

### ISSUE THREAD

**Issue by Kurira** [dotnet/corefx#11141]
Are there any plans to support `IgnoreCase` property in `.Core` version of `ResourceManager`?
Current `.Core` implementation doesn't provide any API surface for doing case insensitive resource search.

Maybe someone knows a workaround for this?

**Comment by gkhanna79** [comment]
@ramarag Can you PTAL?

**Comment by danmosemsft** [comment]
It's there as of 90e2de3.
https://github.com/dotnet/corefx/blob/master/src/System.Resources.ResourceManager/ref/System.Resources.ResourceManager.cs#L64

**Comment by Kurira** [comment]
@danmosemsft where did it get added? I trying to use latest nuget
```JSON
"dependencies": {
    "System.Resources.ResourceManager": "4.3.0"
}
```

But it still doesn't contain the `IgnoreCase` and other properties.
