### ISSUE TITLE
Marshal.GetHRForException() always returns 0 on non-Windows platforms

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/corefx#11144]
Take this example program:

```
using System;
using System.IO;
using System.Runtime.InteropServices;

class Program
{
    public static void Main(string[] args)
    {
        Console.WriteLine("Value: " + Marshal.GetHRForException(new IOException("test message", 123456)));
    }
}
```

When run on Windows, it prints "Value: 123456". On OSX/Linux it prints "Value: 0".

0 seems like the wrong return value here since it'd indicate success. Mono currently returns -1 on platforms that don't support COM interop, but we're debating what to do on e.g. iOS since we need to add this method there for netstandard compliance: https://bugzilla.xamarin.com/show_bug.cgi?id=43646.

The problem is that some code like serilog is using this method (see [Xamarin Forum post](https://forums.xamarin.com/discussion/73925/targeting-netstandard-1-6-on-xamarin-ios-no-marshal-gethrforexception) and [GitHub](https://github.com/search?q=org%3Aserilog+GetHRForException&type=Code)) so throwing PlatformNotSupportedException (which we added for all these Marshal APIs right now on iOS) won't make that code work either which is why I'm thinking about just changing it to -1 as well there. But ideally we'd be consistent with .NET Core :)

Any reason why you're returning 0 instead of -1 or some other generic error code?

/cc @stephentoub 

Version:

```
$ dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

**Comment by stephentoub** [comment]
@janvorli, thoughts?

**Comment by akoeplinger** [comment]
@ghuntley @GraemeChristie fyi ^^. I don't think serilog should be relying on this API on non-Windows platforms like it currently does, it's pure luck that it works as is.

**Comment by jkotas** [comment]
Exception has HResult property. It should just return that on non-Windows platforms. It is what it (typically) returns on Windows.

Note that `Marshal.GetHRForException` on Windows also setups COM thread-local error info , so that COM can get details about the exception once the HRESULT is returned to it. `Marshal.GetHRForException` is meant to be called just before returning HRESULT to COM.

cc @yizhang82

**Comment by ghuntley** [comment]
oh good god; consume a logging library, end up discovering a BCL implementation issue in mono/corefx for System.Runtime.InteropServices/mscorlib.

Paging @nblumhardt to #11144 and https://bugzilla.xamarin.com/show_bug.cgi?id=43646


![giphy](https://cloud.githubusercontent.com/assets/127353/17998263/cb70792c-6bb6-11e6-8c53-756e3c6a0e19.gif)
