### ISSUE TITLE
Loading assemblies

### ISSUE THREAD

**Issue by pedro-ramirez-suarez** [dotnet/corefx#11157]
Hi,

I have tried in many ways to load an assembly at runtime from a console app, there are many responses to my problem :
https://www.google.com.mx/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=dotnet%20core%20load%20assembly%20from%20file 

But none works for me, it seems like the responses use an old version of .Net Core, I am using version 1.0.1 build cee57bf6c981237d80aa1631cfe83cb9ba329f12, many suggested solutions throw a file not found exception, I even tried coping the dll in many locations,  I am not sure how to properly load them, can you please point me in the right direction? I need to load a dll(a valid .net core dll) that is not part of my project at runtime, I need to do that so I am able to read the types defined in the assembly so I can generate some XML files based on the properties and attributes for that type, in .Net 4.x it's pretty straight forward.

Thanks.

**Comment by pedro-ramirez-suarez** [comment]
Well, I find a way, I need to do something like this:
`var aName = AssemblyLoadContext.GetAssemblyName(file.FullName);`
It works but the weird thing is that you need to add a package to use AssemblyLoadContext, that's weird.

**Comment by jasonwilliams200OK** [comment]
Same feeling here, all the dropped / changed methods around Reflection.Assembly is something which really need a doc with one-on-one substitute to reduce the "figuring out" time. Everyone is writing their own set of hacky shims / extensions to cater the .NET Core limitations.

\- my $0.02

**Comment by Fabian-Koenig** [comment]
if you want to load an assembly directly from a dll file you could use create a new class based on the AssemblyLoadContext class.

I did it like:

```
using System.Reflection;
using System.Runtime.Loader;

internal class AssemblyLoader : AssemblyLoadContext
{
    protected override Assembly Load(AssemblyName assemblyName)
    {
        // No implementation needed.
        return null;
    }
}

```
and use it like:

`var assembly = new AssemblyLoader().LoadFromAssemblyPath("MySql.Data.dll");`

**Comment by gkhanna79** [comment]
> all the dropped / changed methods around Reflection.Assembly is something which really need a doc with one-on-one substitute to reduce the "figuring out" time.

We are working to get this differences addressed and documented. Meanwhile, have you tried AssemblyLoadContext.Default.LoadFromAssemblyPath?

**Comment by kouvel** [comment]
#11655 covers addressing these differences for 1.2

**Comment by rahku** [comment]
we have added back Assembly.LoadFile to .net core which should now allow you to do above.
