### ISSUE TITLE
Missing overflow check in DateTime

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/corefx#1115]
While looking at some Mono unit tests that failed on ARM after DateTime was imported from MS referencesource, I think I found a place in DateTime that misses an overflow check:
https://github.com/dotnet/coreclr/blob/9edda94b8044ffa513ea366ca43cea8d029706e6/src/mscorlib/src/System/DateTime.cs#L345

This code path is easily triggered by `DateTime.Now.AddMilliseconds(1E100)` and results in an overflow when it's trying to cast to long.

**Comment by mburbea** [comment]
In unchecked, which is the default context this doesn't throw. It will turn the value into some very large negative number, which will safely be out of the range of milis to add.

**Comment by akoeplinger** [comment]
@mburbea yes I know, the problem is the result of the overflow is undefined and on Mono/ARM the value is -1 instead of the "very large negative number", so the if doesn't catch it.

**Comment by tarekgh** [comment]
Although it is kind of corner case scenario and we never got any complain about such issue but I can see it can bad if it happen as in ARM case mentioned by @akoeplinger
@ericstj I am seeing the app compat risk to fix this issue is low but I want to get your opinion on that.

**Comment by ericstj** [comment]
I'm worried about an existing application which noticed this behavior and worked around it.  So the workaround is to check for the overflow yourself and handle it.  Since the fix of throwing would actually break the workaround I'm inclined to not take the fix, or quirk it if we do.

**Comment by akoeplinger** [comment]
@ericstj If you're talking about the timer fix I linked above, that's unrelated to this issue :)

.NET amd64/x86 shouldn't be impacted, I haven't checked if phone is affected as well.

**Comment by tarekgh** [comment]
Eric was talking about DateTime.Add overflow. so considering the app compat risk fixing this in addition there is other places across the framework not counting for overflow, we intend to won't fix this one. consumer of this API still have the option to check for the overflow (or run the operation under checked mode). 
Thanks Alex for bringing this issue.

**Comment by akoeplinger** [comment]
Can you elaborate on the app compat risk? As far as I can see it, there shouldn't be any change in behavior if we check for overflow and throw the same ArgumentOutOfRangeException that is thrown right on the next line anyway.

**Comment by tarekgh** [comment]
As Eric mentioned, people can count on the overflow behavior so they can manually check for overflow and do whatever they like. in such cases they will not expect the exception. if we start throwing then this is a behavior change for them.
we saw people count on wrong behaviors before and react to that.

**Comment by tarekgh** [comment]
Alex, I am closing the issue here but feel free to contact me if you have any more questions or asks. thanks again.

**Comment by akoeplinger** [comment]
@tarekgh @ericstj Maybe I'm missing something obvious here, but I can't see the behavior change here.

Even if I build my app with overflow checking enabled, that doesn't extend into the framework libraries and it still throws an ArgumentOutOfRangeException on this line as expected: [DateTime.cs#L347](https://github.com/dotnet/coreclr/blob/9edda94b8044ffa513ea366ca43cea8d029706e6/src/mscorlib/src/System/DateTime.cs#L347) (cause on x64/x86 the value after the overflow is a large negative value, so it is < -MaxMillis).

What would be the behavior change if we simply do a check before like this:

```diff
- long millis = (long)(value * scale + (value >= 0? 0.5: -0.5)); 
+ double temp = (value * scale + (value >= 0? 0.5: -0.5));
+ if (temp > long.MaxValue || temp < long.MinValue)
+     throw new ArgumentOutOfRangeException("value", Environment.GetResourceString("ArgumentOutOfRange_AddValue")); 
+
+ long millis = (long)temp;
 if (millis <= -MaxMillis || millis >= MaxMillis)  
     throw new ArgumentOutOfRangeException("value", Environment.GetResourceString("ArgumentOutOfRange_AddValue")); 
```

Sorry if this is all obvious to you, but I'm trying to learn :)

**Comment by tarekgh** [comment]
we have 2 cases here, one case when the overflow result invalid value and the check 
 if (millis <= -MaxMillis || millis >= MaxMillis)  
will cause the method to throw. For this case the fix is not helping in anything because we'll throw anyway. 
the second case which is what you have mentioned in ARM, the overflow will occur but we'll not throw because the result of the overflow is in the valid range. and this is the case the users can be counting on and detecting the overflow is happened (by checking the resulted date) and then do something. in this scenario there is no exception get thrown. if we fix the overflow, we'll start to throw and that will be the behavior change I am talking about.

**Comment by akoeplinger** [comment]
> the second case which is what you have mentioned in ARM, the overflow will occur but we'll not throw because the result of the overflow is in the valid range. and this is the case the users can be counting on and detecting the overflow is happened (by checking the resulted date) and then do something

Is this really a scenario that seems worth keeping compat for? afaik the only consumer of .NET on ARM is Phone and Surface RT and I'd be very surprised if anyone relied on this behavior on those platforms only (as they surely test their apps on Desktop Framework on x86/x64 as well).

Additionally, maybe your implementation of the ARM runtime actually returns a large negative number as well, so the exception is thrown there anyway (I haven't checked yet)? If the latter is the case, would it then be acceptable to introduce a check as the behavior for your implementations wouldn't change?

**Comment by n8ohu** [comment]
@akoeplinger I would keep the behavior consistent across CPU architectures; we do have to consider the fact that Mono runs on ARM (I have it installed on a Raspberry Pi here for testing purposes) and one target of some applications I intend to write soon is Linux/ARM, either with "native" .NET or Mono.

**Comment by akoeplinger** [comment]
@n8ohu yes, this is exactly what this issue is about (currently the behavior is different on Mono/ARM) :)

**Comment by tarekgh** [comment]
@akoeplinger regarding if this issue unlikely to be noticed by people or created work around, we got surprised by similar cases before and the result was a broken app. as DateTime is a core type which is used a lot, any change there is considered a risk if we are not carefully evaluate it.

**Comment by akoeplinger** [comment]
@tarekgh I understand that breaking apps is a no-go. However, I just tested on Windows Phone 8.1 and your ARM implementation does indeed return a large negative number for the overflow, so it runs into the same exception.

Given that all your platforms/implementations are unaffected by this (and thus by any fix we put in here), do you think we can reopen this?

**Comment by tarekgh** [comment]
I have checked with some folks and said the overflow behavior is undefined so this means we cannot say always the overflow will go through the exception. 
second, if all overflow throwing today, this give a reason not to touch the code as not experiencing any issue with it. 
sorry we are really careful touching the core types except if we have strong reasons to do so as the code will be included in all shipping versions of the framework.

**Comment by akoeplinger** [comment]
I can understand the reluctance to change core types, but this just means you're embedding the assumption that something with an explicitly undefined behavior is actually behaving the same across every runtime implementation/platform out there which seems a bit less than ideal to me.

Personally I'm fine with fixing this in Mono's fork of the referencesource for now, but we should really document those cases (I know of at least one other spot) somewhere so that when a new implementation comes along they don't need to figure this out again.
