### ISSUE TITLE
Port TimeZone

### ISSUE THREAD

**Issue by hann013** [dotnet/corefx#11169]
TimeZone is already added into CoreCLR; however due to certain required Linux implementations and required dependencies (i.e. System.Globalization.DaylightTime), it was left out of CoreFx when completing #10074.

```
T:System.TimeZone
M:System.TimeZone.#ctor
P:System.TimeZone.CurrentTimeZone
M:System.TimeZone.get_CurrentTimeZone
P:System.TimeZone.DaylightName
M:System.TimeZone.get_DaylightName
P:System.TimeZone.StandardName
M:System.TimeZone.get_StandardName
M:System.TimeZone.GetDaylightChanges(System.Int32)
M:System.TimeZone.GetUtcOffset(System.DateTime)
M:System.TimeZone.IsDaylightSavingTime(System.DateTime)
M:System.TimeZone.IsDaylightSavingTime(System.DateTime,System.Globalization.DaylightTime)
M:System.TimeZone.ToLocalTime(System.DateTime)
M:System.TimeZone.ToUniversalTime(System.DateTime)
```

**Comment by hann013** [comment]
cc @danmosemsft: @ellismg and I decided it'd be better to leave out TimeZone for now, as it isn't possible to test without adding certain key members in, such as `P:System.TimeZone.CurrentTimeZone`, which can't currently be added in because we require a Linux implementation of `CurrentSystemTimeZone`.

**Comment by tarekgh** [comment]
@hann013 why we cannot write the test to run on Windows only? and we'll enable the test when getting Linux implementation.

**Comment by hann013** [comment]
@tarekgh `P:System.TimeZone.CurrentTimeZone` hasn't been added into CoreCLR yet because the Linux implementation is missing.

**Comment by tarekgh** [comment]
@hann013 I understand that. we can have empty stub for Linux and then create a test that runs on Windows only (as I understand Windows implementation is ready). doing that will allow us to start testing Windows implementation.

**Comment by tarekgh** [comment]
@hann013 forgot to tell, if you are running out of time you can leave it as it is and I'll come to it at some point.

**Comment by hann013** [comment]
@tarekgh that's probably a better idea as today's my last day :)

**Comment by tarekgh** [comment]
@hann013 thanks for all help you have provided and wish you success moving forward.
