### ISSUE TITLE
Where is RSAPKCS1SignatureFormatter ?

### ISSUE THREAD

**Issue by BTXAndy** [dotnet/corefx#11175]
Hi,
I'm trying to find information on where the RSAPKCS1SignatureFormatter class is in CoreFX or what it has been replaced with to be able to port some OAuth1 over to .NET Core. 
Any ideas?
Thanks

**Comment by bartonjs** [comment]
The *Formatters hierarchy did not get ported to CoreFX, bringing them over is tracked by #9990.

If you have
```C#
var formatter = new RSAPKCS1SignatureFormatter(rsa);
formatter.SetHashAlgorithm("SHA1");
byte[] signature = formatter.CreateSignature(dataHash);
```
you can replace it with
```C#
byte[] signature = rsa.SignHash(dataHash, HashAlgorithmName.SHA1, RSASignaturePadding.Pkcs1);
```

(Alternatively, in anticipation of RSAPKCS1SignatureFormatter's return, you could define your own class of that name, and that's how you would write CreateSignature.  HashAlgorithmName isn't an enum, you can wrap a variable with one, a la `new HashAlgorthmName(strName)`)

**Comment by BTXAndy** [comment]
Thanks! Will try that out.

**Comment by bartonjs** [comment]
Since we already have an issue tracking porting the class over, I'm going to go ahead and close this issue.  If something doesn't go well, you can still reply.  (Or if it all goes great and you want to reply, that works, too :smile:)
