### ISSUE TITLE
Failed assert in pal_symmetric.cpp

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#11177]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/3686/consoleText
```
Assertion failed: (algorithm == PAL_AlgorithmAES || operation == PAL_Algorithm3DES), function AppleCryptoNative_CryptorCreate, file /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/Native/Unix/System.Security.Cryptography.Native.Apple/pal_symmetric.cpp, line 54.
```

**Comment by bartonjs** [comment]
Oh, this one looks easy, the right half of the or looks at `operation` instead of `algorithm`.

But what's weird is that it didn't fail during the PR.
