### ISSUE TITLE
XDocument.Load - MethodAccessException

### ISSUE THREAD

**Issue by Angeall** [dotnet/corefx#11183]
Hello,

I have a very strange behaviour in my Xamarin.Droid app.

I use the following code to parse a simple xml soap envelope and to create a XDocument.

![capture](https://cloud.githubusercontent.com/assets/6820648/18009603/4ab1a9e0-6bad-11e6-900a-e499a1be2bc1.PNG)

The problem is that `XDocument.Parse(xmlString)` raises the following exception:

`Method 'System.Xml.XmlReader:get_DtdInfo ()' is inaccessible from method 'System.Xml.Linq.XContainer:ReadContentFrom (System.Xml.XmlReader,System.Xml.Linq.LoadOptions)'`

I believe this is an issue because the code is really simple, and the bug does not happen all the time.
Sometime the method works like a charm, and some other time, the method just fail repeatedly, until I relaunch the app.

I don't know if the problem is Xamarin.Droid related only.

It would be great to have some help about this!
Thanks in advance !

**Comment by stephentoub** [comment]
@Angeall, thanks for the bug report, but it sounds like this is about Mono rather than about .NET Core.  It'd be better to file a bug in Xamarin's bug tracking system: https://bugzilla.xamarin.com/index.cgi. Thakns.
