### ISSUE TITLE
Optimization: Win32FileStream should use the flags pattern

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#11186]
`Win32FileStream` currently has 6 bool fields in its internal layout: https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/Win32FileStream.cs#L50-L55

Assuming the best-case scenario, these have to take up at least 8 bytes, if the first four are packed in 1 int and the last two are packed in 1 int. (The next int field needs to be 4-byte aligned, so the next 2 bytes are ignored.)

If there is not a problem with different threads writing to different fields, we should consider packing all of them into 1 byte-or-int sized field. This will save us at least 1 int in memory.

**Comment by stephentoub** [comment]
With the current fields on FileStream, it wouldn't save any space on 64-bit, and would save at most 4 bytes on 32-bit.  And even if it did, not only is there the size of the FileStream object (which on 64-bit today is ~112 bytes), there's also the objects that get created with the FileStream (e.g. the underlying SafeFileHandle, not to mention the byte buffer), so the value of saving four bytes here is relatively small.  And while a small savings is still a savings, it'd be coming at the cost of extra instructions to parse out the relevant bit from the bit field for each of the Boolean values, so it wouldn't be a pure win.
