### ISSUE TITLE
build.cmd -UpdateInvalidPackageVersions no longer working

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#11189]
Trying to run this command now produces the error:
```
error MSB4057: The target "UpdateInvalidPackageVersions" does not exist in the project
```

**Comment by dagood** [comment]
This is now called `UpdateDependencies` (from the imported [VersionTools.targets](https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/VersionTools.targets)). I want to put this in as a Run command so it's discoverable, but I'd like to wait until there's a way to define non-repo-dependent commands in buildtools.

**Comment by stephentoub** [comment]
> This is now called UpdateDependencies

Good to know.  Thanks.

But the help still shows UpdateInvalidPackageVersions (I assume that's coming from here: https://github.com/dotnet/corefx/blob/17bb1fc07f09124d47235e742c2af3d5dfa75078/config.json#L219)
and the docs still refer to UpdateInvalidPackageVersions:
https://github.com/dotnet/corefx/blob/a6e95d3db3e002b589176a107f7cc79520e37de4/Documentation/project-docs/project-nuget-dependencies.md#L43

**Comment by dagood** [comment]
Ah, thanks, I didn't know that was in the config. I'll submit a PR to get rid of it and maybe discuss if it's actually reasonable for me to wait for "shared command" functionality.

Yeah, documentation of the new verification/update flow definitely needs to happen. I'm thinking that I'll point to a new doc I'll write in buildtools from corefx, coreclr, and wcf. I'll consider this issue tracking getting that written.
