### ISSUE TITLE
XmlTextReader and XmlTextWriter not exposed

### ISSUE THREAD

**Issue by matt-richardson** [dotnet/corefx#11196]
I just had to do some work to port `Microsoft.Web.Xdt` to .NET Core, and one of the big pain points was that [XmlTextReader](https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlTextReaderImpl.cs#L24) and [XmlTextWriter](https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/Common/src/System/Xml/XmlTextWriter.cs#L31) are marked internal and not exposed. I ended up having to copy 40+ files from `corefx` into my [project](https://github.com/OctopusDeploy/Octopus.Web.Xdt) (awesome that that was possible though!).

The second pain point was related to the CRLF/LF normalisation - the desktop version allows you to disable it, but the CoreCLR does not. However, the CoreCLR implementation is according to [spec](https://github.com/dotnet/corefx/pull/2154).

I see that XmlTextReader is [considered legacy](https://github.com/dotnet/corefx/issues/1595), but it is odd that the class is in corefx but not exposed.

Would you consider a PR to expose XmlTextReader and XmlTextWriter, and expose a new setting to enable or disable line ending normalisation?

**Comment by nil4** [comment]
@matt-richardson I converted XDT to .NET Core in this repository https://github.com/nil4/dotnet-transform-xdt (and the [Microsoft.DotNet.Xdt.Tools](https://www.nuget.org/packages/Microsoft.DotNet.Xdt.Tools/) NuGet package) without needing to copy external code. I stopped short of porting the unit tests, but it works well enough for all the projects I needed to use it. Hope it helps.

**Comment by matt-richardson** [comment]
@nil4 - I saw your project, but I found that it didn't handle whitespace preservation correctly. The original code goes to great lengths to ensure that it doesn't change formatting and we needed to keep that behaviour.

**Comment by sepidehMS** [comment]
@matt-richardson We are currently working on bringing back all System.Xml APIs and very likely it will happen with 1.2.0. In the meantime, please use the workaround if possible.

**Comment by sepidehMS** [comment]
I'm closing this as this is currently being worked on and is tracked by https://github.com/dotnet/corefx/issues/11888.

**Comment by VahidN** [comment]
An alternative solution using the current infrastructure:
```csharp
using XmlTextReader = System.Xml.XmlReader;

#if COREFX
            XmlTextReader xr = XmlReader.Create(stream, new XmlReaderSettings() { DtdProcessing = DtdProcessing.Prohibit, IgnoreWhitespace = true });
#else
            XmlTextReader xr = new XmlTextReader(stream);
            xr.ProhibitDtd = true;
            xr.WhitespaceHandling = WhitespaceHandling.None;
#endif
```
