### ISSUE TITLE
File watcher doesn't trigger all the time on Win 2008 R2

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/corefx#11195]
Sorry for the very vague repro but I don't have a consistent one.

We're seeing in some of our tests that rely on the file watcher that the watcher doesn't trigger all the times. It happens pretty rare but, especially on Win 2008 R2, it happens that the file change even doesn't trigger when we write to a file.

Because of that the test fails from time to time and we have to retry the write.

Is this a known issue?

**Comment by victorhurdugaci** [comment]
Even with retries, our tests still fail randomly. It looks like sometimes the FileWatcher doesn't trigger at all https://ci.appveyor.com/project/aspnetci/logging/build/1.0.924

**Comment by jasonwilliams200OK** [comment]
Perhaps you can use `S.T.ManualResetEvent` there like this:

```c#
bool configChanged = false;

using (ManualResetEvent manualResetEvent = new ManualResetEvent(false))
{
    File.WriteAllText(settingsFile, JsonConvert.SerializeObject(settingsFileContent));
    manualResetEvent.Reset();
    configChanged = configChangedEvent.WaitOne(DefaultTimeout);
}

Assert.True(configChanged);
```

e.g.
https://github.com/dotnet/corefx/blob/d0dc5fc/src/System.Threading/tests/ManualResetEventTests.cs#L75-L97

**Comment by victorhurdugaci** [comment]
The problem is not the event that we use. It's the fact that watcher event doesn't trigger.

**Comment by jasonwilliams200OK** [comment]
I have updated the code. This is an additional event on Threading which notifies other thread about any event. I believe this is worth a try.

**Comment by ianhays** [comment]
Are you watching specifically on a single type of event e.g. Changed/Deleted? What kind of timeout are you using? 

Some things that could potentially cause trouble:
- Modifying a file as well as the directory that is being watched
- Disabling the FSW right as an event occurs
- The Windows FSW code revolves around interop calls to the `ReadDirectoryChangesW` win32 function. If that function doesn't raise events, neither does .NET.
- The FSW internalbuffer is too small, causing events to be dropped if they queue up too fast.

It's generally recommended that if you need *precise* file watching you use a polling filesystemwatcher or a blend of the two. That can be a bit overkill in some scenarios and if that's the case then I recommend you start by increasing the [InternalBufferSize](https://msdn.microsoft.com/en-us/library/system.io.filesystemwatcher.internalbuffersize(v=vs.110).aspx) property.

**Comment by BrennanConroy** [comment]
We figured out what the issue was. We have a file being watched `configSettings.json` and use `File.WriteAllText(...)` to change it. The file watcher often triggers before the file has been fully written to and we were expecting the file to be finalized in our callbacks which causes issues.

**Comment by ianhays** [comment]
Thanks for the update @BrennanConroy. So this is good to close now?

**Comment by BrennanConroy** [comment]
Should be

**Comment by victorhurdugaci** [comment]
@ianhays I'm still curious, is that an expected behavior?
