### ISSUE TITLE
Hook Console.CancelKeyPress handler will cause several bugs

### ISSUE THREAD

**Issue by TingluoHuang** [dotnet/corefx#11199]
I paste the repro console app, it's just modified from 'dotnet new'
[Program.txt](https://github.com/dotnet/corefx/files/440175/Program.txt)
```C#
namespace ConsoleApplication
{
    public class Program
    {
        static CancellationTokenSource tokenSource = new CancellationTokenSource();
        public static void Main(string[] args)
        {
            Console.CancelKeyPress += Handler;
            Console.WriteLine("Hello World!");

            while (!tokenSource.IsCancellationRequested)
            {
                Thread.Sleep(1);
            }

            Console.WriteLine("END");
            string read = Console.ReadLine();
            Console.WriteLine($"You just typed: {read ?? string.Empty}");
        }

        public static void Handler(object sender, ConsoleCancelEventArgs arg)
        {
            arg.Cancel = true;
            Console.WriteLine();
            Console.WriteLine("Cancelling...");
            tokenSource.Cancel();
        }
    }
}
```
This app will throw IO exception on Ubuntu 16 when you press Ctrl-C, it throw on Console.Readline().
On windows, the app is able to run, but it will messed up my console when i press Ctrl-C and type something let the process exit.
Here is a screenshot:
![image](https://cloud.githubusercontent.com/assets/1750815/18021067/e8bf3b70-6bb2-11e6-96c9-5efc1997e59d.png)
It makes me feel my app haven't exit. :(

However, if i build this code in Full desktop dotnet 4.5, everything works fine just like what i expected.

**Comment by stephentoub** [comment]
My guess is that your ctrl-C is causing the dotnet executable to exit, leaving yours running.  Have you tried executing it directly, e.g. using dotnet publish rather than dotnet run?

**Comment by TingluoHuang** [comment]
@stephentoub you are right, run the app without dotnet run fix the problem. 
The following code behave different on Windows vs Ubuntu, on Windows, the console app will exit when press Ctrl-C, however, on Ubuntu it still block on ReadLine().
``` C#
namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.CancelKeyPress += Handler;
            Console.ReadLine("Hello World!");

            string read = Console.ReadLine();
            Console.WriteLine($"You just typed: {read ?? string.Empty}");
            Console.WriteLine("END");
        }

        public static void Handler(object sender, ConsoleCancelEventArgs arg)
        {
            arg.Cancel = true;
            Console.WriteLine();
            Console.WriteLine("Cancelling...");
        }
    }
}
```

**Comment by stephentoub** [comment]
A ctrl-C on Linux comes in as a SIGINT interrupt.  Signals interrupt syscalls (like read(…)), but we currently register our SIGINT signal handler with SA_RESTART, which means the OS will automatically restart the read after the signal, and from the caller’s perspective the read won’t wake up.  We could change that to remove the SA_RESTART and handle the restart ourselves, but there’s no great way to reliably determine which signal caused the EINTR failure in the read call, just that one did; that means we don’t have a good way of knowing whether to restart the read or not (and we can’t just assume that an EINTR is for ctrl-C, even if we use SA_RESTART on all other signal handler registrations, as other code in libraries we call could register handlers). So for now at least, this is the behavior.
