### ISSUE TITLE
`ParallelQuery.Zip(...).All(...)` hitting some elements twice

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#1120]
Either `ParallelQuery<T>.Zip(...)` is thread-unsafe / otherwise misbehaving for not-ordered input, or the enumerators it's calling are not.  The following query fails every time:

    ConcurrentDictionary<int, int> seen = new ConcurrentDictionary<int, int>();
    ParallelQuery<int> left = Enumerable.Range(0, 16).AsParallel();
    ParallelQuery<int> right = ParallelEnumerable.Range(8 * 2, 16);
    Assert.True(left.Zip(right, (x, y) => (x + y) / 2).All(z => seen.TryAdd(z, 0)));
    // The expected range is [8, 24)
    // Assert.True(seen.Keys.All(key => key >= 8 && key < 8 + 16));

(To see the internals, use this for the lambda: `z => { if (seen.TryAdd(z, 0)) return true; throw new Exception("" + z + "|" + seen.Keys.Aggregate("", (a, key) => a + ":" + key)); }`)

This happens when a `ParallelQuery` sourced from `Enumerable.Range(...).AsParallel()` occupies either the left or right side, sometimes when the right side is sourced via `Partitioner.Create(array).AsParallel()`, and rarely when the left side is  sourced via `Partitioner.Create(array).AsParallel()`.  
No query using solely `ParallelEnumerable.Range(...)` (that is, as both left and right operators) has yet had a problem, nor one using an array as a source (via `new[] {1, 2, 3}.AsParallel()`).

This behavior is present on the current consumer release, although it may be failing less often.
The reason I'm leaning towards hitting the same element twice, or somehow otherwise not threadsafe (as opposed to hitting elements out of order) is I'm getting results that look like this:

![zip](https://cloud.githubusercontent.com/assets/5569508/6594248/c430c768-c822-11e4-8b5f-37c97114d0ad.png)

This specific run is claiming that 18 and 15 are showing up as already processed.  The problem is, there isn't a leftover way to make 18 out of the elements remaining.  (Even if it is due to elements being out of sequence, that's still a problem, given the intent of `Zip`).  Also, using `ToArray()` returns the expected results (no duplicates).

I glanced through the code, but don't know the internals well enough to guess what might be wrong.  (Although `Shared` probably shouldn't be, as I don't think its declaration or use is threadsafe?)

**Comment by svick** [comment]
I don't understand. You're zipping *unordered* ranges [0,15] and [32,47], so why couldn't you get for example (0+46)/2 = 23 and (1+45)/2 = 23?

**Comment by Clockwork-Muse** [comment]
(Argh, that should have started as `8 * 2` - there wouldn't be a way to get `10` otherwise)

What `Zip` does (like `Take` and `Skip`, to an extent) is read from sources and match them by their index.  This doesn't actually guarantee _output_ ordering (which is what you'd get with `AsOrdered()`), just that the first element of the left query is matched to the first element of the right query.  I _think_ that's still happening here.
For the example in that screenshot, there was supposed to be no way to get a duplicate via incorrect ordering, although I'm now realizing there were more than I thought.  That's fine, I just got this run:

    20|:8:9:10:11:12:13:14:16:17:19:20
    14|:8:9:10:11:12:13:14:16:17:19:20

There is only one way to get `8` - when the left query spits out `0`, and the right `16`.  This means that the following run (`9`, `10`, `11`, `12`, `13`, `14`) has to be put together using their matched elements (can't move a step higher, because the lower step from the other side is already used).  Care to tell me which previously used number is being duplicated for the failing `14`?

**Comment by stephentoub** [comment]
@Clockwork-Muse, these are _unordered_ inputs.  Any element from the first could be zipped with any element from the second; effectively imagine that the first sequence was randomized and the second sequence was randomized and then they were zipped together.

**Comment by stephentoub** [comment]
I modified your example code to also store the inputs, just to help answer the question which values were getting zipped together.

```
using System;
using System.Collections.Concurrent;
using System.Linq;

class Program
{
    static void Main()
    {
        while (true)
        {
            var seen = new ConcurrentDictionary<int, string>();
            var left = Enumerable.Range(0, 16).AsParallel();
            var right = ParallelEnumerable.Range(8 * 2, 16);
            left.Zip(right, (x, y) => new { Result = (x + y) / 2, Components = x + " and " + y }).All(z =>
            {
                if (seen.TryAdd(z.Result, z.Components))
                    return true;
                throw new Exception(
                    Environment.NewLine +
                    z + Environment.NewLine + 
                    seen.Aggregate("", (total, cur) => total + Environment.NewLine + cur));
            });
        }
    }
}
```

I ran this a few times until I got one that could answer your question about 14:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Exception:
{ Result = 14, Components = 9 and 20 }

[10, 5 and 16]
[11, 6 and 17]
[12, 7 and 18]
[13, 0 and 27]
[14, 1 and 28]
[15, 2 and 29]
[16, 3 and 30]
[17, 4 and 31]
[18, 13 and 24]
[19, 14 and 25]
[20, 15 and 26]
```

**Comment by Clockwork-Muse** [comment]
@stephentoub  - Thanks for bringing me down a peg again.  Seems like I get a bit too excited on some of these, and need to spend a little more time checking.
I was kicking myself when I woke up this morning, realizing there were three ways to make 8 anyways.

I thought this violated the contract for `Zip` anyways?  That it'd nab elements by index even when unordered?  This was getting reinforced by the fact that output using `ToList()`, `ToArray()`, or via a `foreach` shows this behavior, nor for a `ParallelEnumerable` pair of inputs.

**Comment by stephentoub** [comment]
@Clockwork-Muse, sorry, I didn't mean to "bring you down a peg" :smile:  I appreciate the enthusiasm.  I think this just goes back to the same issue we talked about previously, around ParallelEnumerable.Range not providing ordered output as you were hoping for.  In any event, the right mental model for pretty much all of the operators in PLINQ is that unless you specify AsOrdered(), a randomizer will randomize the inputs.  It's possible that certain operators do better in their implementation, or that certain sources cause stronger / less random behaviors, but that's the core design: no guarantees about order unless you explicitly ask for ordering.

**Comment by Clockwork-Muse** [comment]
And here I'm always harping to people on SO about the lack of ordering in SQL!  I guess I have more tests to change.

**Comment by stephentoub** [comment]
:smile:

> I guess I have more tests to change.

If you're modifying existing PLINQ tests, let's make sure that if any happen to be relying on ordering and are passing that we still keep those as-is.  While such ordering may not be guaranteed, it's also possible folks could have taken a dependency on ordering in certain cases, and so if we already have tests for such things, we should keep them to know if we ever impact them.

**Comment by Clockwork-Muse** [comment]
...then I maybe don't have so many tests to change.



On Wed, Mar 11, 2015 at 3:26 PM -0700, "Stephen Toub" <notifications@github.com> wrote:
:smile:

> I guess I have more tests to change.

If you're modifying existing PLINQ tests, let's make sure that if any happen to be relying on ordering and are passing that we still keep those as-is.  While such ordering may not be guaranteed, it's also possible folks could have taken a dependency on ordering in certain cases, and so if we already have tests for such things, we should keep them to know if we ever impact them.

---
