### ISSUE TITLE
ConcurrentBag.Steal

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#11216]
ConcurrentBag.Steal [says](https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentBag.cs#L327)

>It enumerate all other threads in two passes first pass acquire the lock with TryEnter if succeeded

However, `TrySteal` doesn't use `TryEnter` but uses `lock` although `Steal` does make two passes.

This would either suggest it was meant to be different or was changed. Any reason why?

**Comment by stephentoub** [comment]
> or was changed

Yes, the comment looks wrong/stale.

> does make two passes

The comment at
https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentBag.cs#L361
appears to explain why.
