### ISSUE TITLE
Is GetCallingAssembly not coming to .NET Core ever?

### ISSUE THREAD

**Issue by ghost** [dotnet/corefx#11212]
This API was discussed and rejected last year in multiple issues. In the new compat work, is GetCallingAssembly  coming back?
It seems like there are some security concerns on Unix platform for this API, can they be worked out in a way to provide the consumer a limited and safe implementation?

log4net (https://github.com/apache/log4net, used in abundance in Azure service projects for example) for one heavily rely on this API, using compiler's [Caller Information](https://msdn.microsoft.com/en-us/library/hh534540.aspx) suggested at https://github.com/dotnet/corefx/issues/1784#issuecomment-115805990, is not a very straight-forward alternative in practice and requires a significant change in consumer land.

Please reconsider adding this API. Many thanks! :)

**Comment by danmosemsft** [comment]
This came back in b647c01 which is now in master. However, I understand that it will never be a reliable API. @jkotas can give more information if required.
