### ISSUE TITLE
Add HttpClient support for IDNA on systems where libcurl does not support IDNA itself

### ISSUE THREAD

**Issue by hsorbo** [dotnet/corefx#11213]
Im trying to fetch data from a norwegian idn-domain.
It works fine on windows but failes on os x

```
using System.Net.Http;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using(var c = new HttpClient())
            {
                c.GetStringAsync(@"http://allehjørnet.no").Wait();
            }
        }
    }
}
```

```
dotnet --version
1.0.0-preview2-003121
```

```
uname -a
Darwin Macarena.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
```

Ive tried saving the document in UTF8/UTF16LE/Windows1252 with the same result

Exception details output from `dotnet run`

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (An error occurred while sending the request.) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't resolve host name
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<GetContentAsync>d__32`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ConsoleApplication.Program.Main(String[] args)
```

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by stephentoub** [comment]
@hsorbo, if you set the CHARSET environment variable to "UTF-8" prior to running your repro, does that allow the call to succeed?

@ericeil, the URL we're passing to libcurl is being improperly recognized, and it fails to do proper IDN encoding:
```
CURLINFO_TEXT: Input domain encoded as `ANSI_X3.4-1968`
CURLINFO_TEXT: Failed to convert allehørnet.no to ACE; Could not convert string in locale encoding
```
If I set CHARSET to UTF-8 prior to invoking it, though, then it works:
```
CURLINFO_TEXT: Input domain encoded as `UTF-8`.
```
I'm wondering if there's something going wrong in our call(s) to configure libcurl (the same request made with the curl command line succeeds).  Hopefully it's something simple, but if we can't get it working via normal means, we may need to pass in a URL that's already been properly transformed, rather than using Uri.AbsoluteUri.

**Comment by hsorbo** [comment]
CHARSET="UTF-8" dosen't seem to help here. 
Also goofed around with LC_ALL/LANG, tried C and "en_US.UTF-8" without any effect.

Side note:
Im was not able to get `curl "http://allehjørnet.no"` to work at all with the mac bundled /usr/bin/curl (or wget for that matter). Brew installing with --with-libidn was the only way to get it working from command-line. (`brew install curl --with-libidn`). Other utf8 like www.❺➠.ws works fine though, both from command line and dotnet.

**Comment by stephentoub** [comment]
Hmm.  Prior to your brew installation, what was the output of ```curl --version```.  It didn't include ```IDN``` in the list of capabilities?  If not, that's definitely why this wasn't working for you, using a version of libcurl that doesn't support doing the translation.

@davidsh, @cipop, how does when get the equivalent of Uri.AbsoluteUri but with IdnHost instead of the normal Host?  None of the APIs I tried on Uri seem to produce that.  If there's no API for it, what's the correct way to assembly that from what is exposed?

**Comment by hsorbo** [comment]
```
➜  dotnetbug which curl
/usr/bin/curl

➜  dotnetbug curl --version
curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets 
```
The features on the brew does indeed show IDN in the Features-list
```
/usr/local/opt/curl/bin/curl --version
curl 7.49.1 (x86_64-apple-darwin15.6.0) libcurl/7.49.1 SecureTransport zlib/1.2.5 libidn/1.32
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: IDN IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets 
```

the brew curl is "slotted" and lives in /usr/local/opt and /usr/bin is read-only as per El Captians rootless-mode. I did try a `DYLD_INSERT_LIBRARIES` on dotnet to force a newer libcurl (from brew) but the result is still crash. Im pretty sure the new libraries are loded as crash report says:
Binary Images:
       0x1065b7000 -        0x1065d3ff3 +dotnet (0) <3D909F9D-70EC-3599-8378-D1E3D3F3C4C2> /usr/local/share/dotnet/dotnet
       0x1065e4000 -        0x106631fe3 +libcurl.dylib (0) <42A7D19B-9DF2-384C-BC3E-93CFBE3C384D> /usr/local/opt/curl/lib/libcurl.dylib
       0x106640000 -        0x10666dff7 +libidn.11.dylib (0) <E804AB55-8E54-332F-9B14-0B93A54DD3C5> /usr/local/opt/libidn/lib/libidn.11.dylib

Another observation. My stock /usr/lib/libcurl.4.dylib which System.Net.Http.Native.dylib does not seem to import idn.

```
➜  ~ otool -L /usr/lib/libcurl.4.dylib | grep -i idn | wc -l               
       0
➜  ~ otool -L /usr/local/opt/curl/lib/libcurl.4.dylib | grep -i idn | wc -l
       1
```

Im not sure if any of this is helpful. Let me know if you want more info

**Comment by CIPop** [comment]
> @davidsh, @cipop, how does one get the equivalent of Uri.AbsoluteUri but with IdnHost instead of the normal Host? None of the APIs I tried on Uri seem to produce that. If there's no API for it, what's the correct way to assembly that from what is exposed?

/cc: @himadrisarkar 

The `Uri` class is implementing the IRI RFC which is not HTTP compliant. The HTTP stack must convert the IRI to URI internally.
For that to work we would need a new API similar to [AbsoluteCanonicalUri](https://msdn.microsoft.com/en-us/windows.foundation.uri.absolutecanonicaluri).

**Comment by hsorbo** [comment]
Ive checked with two coworkers running OSX 10.11.6 (15G31) and it looks the same no imports of libidn in libcurl and no IDN in the Features list.

**Comment by stephentoub** [comment]
> The HTTP stack must convert the IRI to URI internally. For that to work we would need a new API similar to AbsoluteCanonicalUri.

Do we have code for that somewhere?

**Comment by stephentoub** [comment]
Thanks, @hsorbo. @ericeil, if it's common for libcurls to not be built with IDN support, we should probably do the translation in System.Net.Http instead.

**Comment by davidsh** [comment]
I want to add a few things to this discussion.

The use of "IRI" vs. "URI" is larger than the IDNA issue.  IRI encompasses the uses of non-ASCII characters in parts of the url such as path, query, etc. in addition to host name.

IDNA usually refers to the part of the IRI and related RFC's dealing with hostname encoding on the wire.  There are 2 ways in which non-ASCII characters in a DNS hostname can be encoded.  Punnycode or UTF-8.  The Internet at-large has embraced Punnycode.  But for Intranet scenarios especially on Microsoft networks (Windows), UTF-8 can be used as well.  

Long ago, System.Uri had another flag (not 'iriParsing flag) which controlled which encoding to use for hostnames.  That was deprecated in favor of having the OS control this. In fact, Windows OS lately has group policy and other controls to allow administrators control over various DNS zones to decide whether to use Punnycode or UTF-8.

So, in general, we have trended to letting the OS decide how to transmit on the wire the encoding for the host name.  And the DNS resolver APIs in the OS would translate back-and-forth.

In terms of how a URI is normalized itself, the official URI RFC says to always Punnycode for canonicalization.  So, in terms of doing that the actual System.Uri class, that is what we need to move toward.

**Comment by ericeil** [comment]
This seems very similar to https://github.com/dotnet/corefx/issues/9728, where SSL works, or not, depending on how libcurl is set up.  And given what @davidsh said:

> Windows OS lately has group policy and other controls to allow administrators control over...whether to use Punnycode or UTF-8...we have trended to letting the OS decide how to transmit on the wire the encoding for the host name.

...it seems like the consistent thing to do would be to leave it up to the admin, who gets to decide which libcurl support/features to enable.

Any feedback on that approach?

**Comment by stephentoub** [comment]
> it seems like the consistent thing to do would be to leave it up to the admin, who gets to decide which libcurl support/features to enable

But in either case, the Windows implementation "works" with these international URLs, right?  That doesn't appear to be the case here for unix... it seems pretty bad if out-of-the-box you can't access some sites.

> This seems very similar to #9728, where SSL works, or not, depending on how libcurl is set up

There's a key difference, though: that affects whether you can use certain more-advanced APIs on HttpClient.  This, however, affects whether you can use HttpClient at all with various web sites.
