### ISSUE TITLE
System.Net.Http test failures

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#11218]
A few Http tests unrelated to the change failed on Windows:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/3850/

System.Net.Http.Functional.Tests.PostScenarioTest.PostUsingContentLengthSemantics_Success(serverUri: http://corefx-net.cloudapp.net/Echo.ashx)
System.Net.Http.Functional.Tests.PostScenarioTest.PostUsingContentLengthSemantics_Success(serverUri: https://corefx-net.cloudapp.net/Echo.ashx)
System.Net.Http.Functional.Tests.HttpClientHandler_DefaultProxyCredentials_Test.ProxyExplicitlyProvided_DefaultCredentials_Ignored
System.Net.Http.Functional.Tests.HttpClientHandlerTest.PostAsync_CallMethod_StreamContent(remoteServer: https://corefx-net.cloudapp.net/VerifyUpload.ashx, content: [ByteArrayContent { Headers = [...] }], expectedData: [45, 45, 57, 56, 51, ...])
System.Net.Http.Functional.Tests.HttpClientHandlerTest.PostAsync_CallMethod_StreamContent(remoteServer: https://corefx-net.cloudapp.net/VerifyUpload.ashx, content: StreamContentWithSyncAsyncCopy { Headers = [] }, expectedData: [62, 23, 186, 150, 174, ...])
System.Net.Http.Functional.Tests.HttpClientHandlerTest.SendAsync_SendRequestUsingMethodToEchoServerWithContent_Success(method: "PUT", secureServer: False)
System.Net.Http.Functional.Tests.DiagnosticsTest.SendAsync_HttpTracingEnabled_Succeeds
System.Net.Tests.HttpWebRequestTest.GetResponseAsync_GetResponseStream_ExpectNotNull(remoteServer: https://corefx-net.cloudapp.net/Echo.ashx)

**Comment by davidsh** [comment]
These errors are all related:

"System.Net.Http.HttpRequestException : An error occurred while sending the request.\r\n---- System.Net.Http.WinHttpException : The operation timed out"

A lot of the HTTP tests talk with a real server hosted in Azure. It's possible that there was a network problem that happened when running the tests.

**Comment by tmat** [comment]
Why do they need to talk to a remote server and not a local server?

**Comment by davidsh** [comment]
cc: @CIPop 

>Why do they need to talk to a remote server and not a local server?

By "local" do you mean "loopback"?  Many of the tests use SSL and that requires a real zerver endpoint.  We do use loopback server for many of the tests, just not all of them.  We are working on ways to get the test server endpoints used in CI to be "closer" than the current Azure test endpoints.

The large number of failures that were recently experienced is more of an isolated event.

**Comment by tmat** [comment]
By local I mean on the same machine (different process).

**Comment by davidsh** [comment]
Mitigated with PR #11341 and future work part of issue #11345
