### ISSUE TITLE
Port S.Ref.StrongNameKeyPair

### ISSUE THREAD

**Issue by ghost** [dotnet/corefx#11225]
This type is used by MSBuild and disabled for xplat. Now that Microsoft.Build.Framework is available as an official NuGet package, some libs depending on MSBuild are being ported to .NET Core; lack of this type is a show-stopper in some cases. :(

cc @weshaggard, @AtsushiKan, https://github.com/dotnet/coreclr/pull/6614#issuecomment-243018075

**Comment by weshaggard** [comment]
@bartonjs any thoughts one whether or not we have enough Crypto to support this x-plat?

**Comment by jasonwilliams200OK** [comment]
@dsplaisted, I ported https://github.com/dsplaisted/strongnamer to netstandarad1.3. This is the only blocker. Basically this is the patch so far: https://gist.github.com/jasonwilliams200OK/181721c2fcd6dcf995440f2dfde1f0de -- Mono.Cecil (released just [now](https://www.nuget.org/packages/Mono.Cecil/) -> https://github.com/jbevain/cecil/pull/213#issuecomment-243164077) and Microsoft.Build.* are now published to NuGet.org with netstandard support

**Comment by AtsushiKan** [comment]
Can we get some clarity on whether the ask is just for StrongNameKeyPair (hopefully can be implemented as standlone), or also a request for AssemblyName.get_KeyPair as well? (which would mean jamming StrongNameKeyPair and whatever associated crypto comes with it) into the S.Private area?

It sounds like the former to me, but it would be good to get clarity.

**Comment by jasonwilliams200OK** [comment]
@AtsushiKan, for StrongNamer project, KeyPair getter is not required (might be blocking someone else but that can probably be worked out later once the related Cryptography APIs are available xplat).

**Comment by bartonjs** [comment]
@weshaggard Ignoring the potential question of layering (which Ati covered) think it's "named keys are very much tied to CAPI, and can't work x-plat; and the keypair blob form is probably transparently the CAPI form, so they'd need to reuse the CAPI <--> RSAParameters conversion logic; and otherwise it's fine".

**Comment by jasonwilliams200OK** [comment]
Is it a correct assessment that the dependency `Microsoft.Runtime.Hosting` is something non-portable in this implementation: https://github.com/dotnet/coreclr/blob/dbe6910/src/mscorlib/src/System/Reflection/StrongNameKeyPair.cs? I saw the usage of `System.Runtime.Hosting` elsewhere in the code, is `Microsoft.R.H` variant is somewhat different (and not available in open)?

**Comment by danmosemsft** [comment]
This is covered by https://github.com/dotnet/corefx/issues/11808. @kouvel please close if you agree.

**Comment by kouvel** [comment]
Yes this should be covered by #11808, closing

**Comment by weshaggard** [comment]
@kouvel we should make sure that what we do in #11808 actually provides a working version of StrongNameKeyPair because currently I don't think it is functional.

**Comment by alexdrl** [comment]
Any input on implementing S.R.StrongNameKeyPair? We are also trying to build StrongNamer in a .NET Standard MSBuild Task, but got into a PlatformNotSupported exception in this class in Linux.

I think that this class could possibly be implemented, as assemblies can be strong named when built on Linux.
