### ISSUE TITLE
Will chmod be public later?

### ISSUE THREAD

**Issue by Hzj-jie** [dotnet/corefx#1122]
Hi, I found the chmod function has been implemented in UnixFileSystem class as internal. Will it be public later. The scenario I am facing is, I will write a binary file from memory to the hard disk, and executing it. On Windows system, it works well, since I do not need to actively set 'exec' permission, but on Linux or Unix system, the default file permission is 'rw' instead of 'rwx'. On mono, I am using Mono.Unix.Native.Syscall.chmod. But on corefx, there is no such functionality.

**Comment by stephentoub** [comment]
@Hzj-jie, we don't currently have plans to make any of the DllImports public.  You can use your own if you like, though, e.g.
```C#
[DllImport("libc", SetLastError = true)]
private static extern int chmod(string path, int mode);
...

**Comment by stephentoub** [comment]
#312 has an ongoing discussion as well related to this.

**Comment by Hzj-jie** [comment]
Thank you.
