### ISSUE TITLE
Difference output  between Linux and Windows platforms

### ISSUE THREAD

**Issue by SerhiiS-in6k** [dotnet/corefx#11221]
Hello. This line 
``
string.Format("{0:G}", new DateTime(2015, 9, 14, 8, 30, 0))
``
On Linux return 
``
9/14/15 8:30:00 AM
``
On Windows 
``
9/14/2015 8:30:00 AM
``
I my case it is cause a problem because the tests are not passed between platform.

**Comment by SerhiiS-in6k** [comment]
You can check this simple example https://github.com/SerhiiS-in6k/DotNetCoreTest/blob/master/DotNetCoreConsoleApplication/Program.cs

**Comment by SerhiiS-in6k** [comment]
Expected format:
String.Format("{0:G}", dt);  // "3/9/2008 4:05:07 PM"  
Example
http://www.csharp-examples.net/string-format-datetime/

**Comment by SerhiiS-in6k** [comment]
Same problem with ToString("d") method

**Comment by Jupakabra** [comment]
Are your thread cultures the same on both environments?

**Comment by SerhiiS-in6k** [comment]
I think it doesn't matter because "{0:G}" pattern should return "3/9/2008 4:05:07 PM"

**Comment by Clockwork-Muse** [comment]
@SerhiiS-in6k - does matter, the formatting pattern [is culture aware](https://msdn.microsoft.com/en-us/library/az4se3k1(v=vs.110).aspx).

**Comment by SerhiiS-in6k** [comment]
I run
```       
 CultureInfo culture = CultureInfo.CurrentCulture;
 Console.WriteLine("The current culture is {0} [{1}]", culture.NativeName, culture.Name);
```
Output on both system(Linux and Windows) 
The current culture is English (United States) [en-US]

**Comment by SerhiiS-in6k** [comment]
Do you know the way to set culture info because of this code 
``
DateTime date1 = new DateTime(2008, 4, 10);                            
Console.WriteLine(date1.ToString("D", CultureInfo.CreateSpecificCulture("en-US")));
``
doesn't work with .Net Core

**Comment by svick** [comment]
@SerhiiS-in6k 

You can use [the `CultureInfo(string)` constructor](https://docs.microsoft.com/en-us/dotnet/core/api/system.globalization.cultureinfo#System_Globalization_CultureInfo__ctor_System_String_):

```c#
Console.WriteLine(date1.ToString("D", new CultureInfo("en-US")));
```

**Comment by stephentoub** [comment]
@steveharter or @tarekgh, could you take a look at this one?  I'm able to repro, and it does look like we're using the wrong format.

**Comment by tarekgh** [comment]
This is happening because the default short date for en-US (on Linux) is M/d/yy. the way determine the default short date is the code

https://github.com/dotnet/coreclr/blob/master/src/corefx/System.Globalization.Native/calendarData.cpp#L527

https://github.com/dotnet/coreclr/blob/master/src/corefx/System.Globalization.Native/calendarData.cpp#L281

the default short date pattern used is the first one returned from this enumeration and it looks that what ICU return for KShort

CC @eerhardt

**Comment by danmosemsft** [comment]
@tarekgh @eerhardt is there a bug here or action required? If not please close.

**Comment by tarekgh** [comment]
@SerhiiS-in6k it is expected to have differences between the OS's in general. I am closing this issue but if you disagree with the default short date format we are picking on Linux then please re-open the issue. I just want to make sure it is clear we expect different formats on different OS's. Thanks.

**Comment by effyteva** [comment]
Hi,
For anyone suffering from this issue, I've create a simple solution.
https://github.com/effyteva/Teva.Common.Cultures

**Comment by abakumov-v** [comment]
Hello.
I faced with same issue on .NET Core 2.2 and solved it with using the `CultureInfo.GetCultureInfo("en-us")` instead of `new CultureInfo("en-us")`.

More info:

1. I have this class:
```csharp
    public class DecimalToStringConverter : IConverter<decimal, string>
    {
        public string Convert(decimal value)
        {
            return value.ToString("F2", new CultureInfo("en-us"));
        }
    }
```
2. Also I have this unit tests:
```csharp
    public class DecimalToStringConverterTests
    {
        private readonly DecimalToStringConverter _testModule;

        public DecimalToStringConverterTests()
        {
            _testModule = new DecimalToStringConverter();
        }

        [Theory]
        [InlineData(1500, "1500.00")]
        [InlineData(1.5, "1.50")]
        [InlineData(1, "1.00")]
        [InlineData(0.123, "0.12")]
        public void Convert_ReturnCorrectConvertedValue(decimal value, string correctValueAsString)
        {
            // Arrange
            // Act
            var valueAsString = _testModule.Convert(value);
            // Assert
            Assert.Equal(correctValueAsString, valueAsString);
        }
    }
```
3. When I'm running this unit tests on my Win 10 PC then they passed.
4. But when this unit tests running on GitLab runner inside docker image (.net core 2.2 sdk alpine linux) then I'm found that this tests are failed:
```bash
Starting test execution, please wait...
[xUnit.net 00:00:03.22]     Tests.Unit.Models.Domain.Converters.DecimalToStringConverterTests.Convert_ReturnCorrectConvertedValue(value: 0.123, correctValueAsString: "0.12") [FAIL]
[xUnit.net 00:00:03.23]     Tests.Unit.Models.Domain.Converters.DecimalToStringConverterTests.Convert_ReturnCorrectConvertedValue(value: 1, correctValueAsString: "1.00") [FAIL]
[xUnit.net 00:00:03.23]     Tests.Unit.Models.Domain.Converters.DecimalToStringConverterTests.Convert_ReturnCorrectConvertedValue(value: 1.5, correctValueAsString: "1.50") [FAIL]
[xUnit.net 00:00:03.23]     Tests.Unit.Models.Domain.Converters.DecimalToStringConverterTests.Convert_ReturnCorrectConvertedValue(value: 1500, correctValueAsString: "1500.00") [FAIL]

Failed
Tests.Unit.Models.Domain.Converters.DecimalToStringConverterTests.Convert_ReturnCorrectConvertedValue(value: 0.123, correctValueAsString: "0.12")
Error Message:
 Assert.Equal() Failure
              ↓ (pos 4)
Expected: 0.12
Actual:   0.123
              ↑ (pos 4)
Stack Trace:
   at Tests.Unit.Models.Domain.Converters.DecimalToStringConverterTests.Convert_ReturnCorrectConvertedValue(Decimal value, String correctValueAsString) in /builds/products/Tests.Unit/Models/Domain/Converters/DecimalToStringConverterTests.cs:line 30

Failed
Tests.Unit.Models.Domain.Converters.DecimalToStringConverterTests.Convert_ReturnCorrectConvertedValue(value: 1, correctValueAsString: "1.00")
Error Message:
 Assert.Equal() Failure
              ↓ (pos 4)
Expected: 1.00
Actual:   1.000
              ↑ (pos 4)
Stack Trace:
   at Tests.Unit.Models.Domain.Converters.DecimalToStringConverterTests.Convert_ReturnCorrectConvertedValue(Decimal value, String correctValueAsString) in /builds/products/Tests.Unit/Models/Domain/Converters/DecimalToStringConverterTests.cs:line 30

Failed
Tests.Unit.Models.Domain.Converters.DecimalToStringConverterTests.Convert_ReturnCorrectConvertedValue(value: 1.5, correctValueAsString: "1.50")
Error Message:
 Assert.Equal() Failure
              ↓ (pos 4)
Expected: 1.50
Actual:   1.500
              ↑ (pos 4)
Stack Trace:
   at Tests.Unit.Models.Domain.Converters.DecimalToStringConverterTests.Convert_ReturnCorrectConvertedValue(Decimal value, String correctValueAsString) in /builds/products/Tests.Unit/Models/Domain/Converters/DecimalToStringConverterTests.cs:line 30

Failed
Tests.Unit.Models.Domain.Converters.DecimalToStringConverterTests.Convert_ReturnCorrectConvertedValue(value: 1500, correctValueAsString: "1500.00")
Error Message:
 Assert.Equal() Failure
                 ↓ (pos 7)
Expected: 1500.00
Actual:   1500.000
                 ↑ (pos 7)
Stack Trace:
   at Tests.Unit.Models.Domain.Converters.DecimalToStringConverterTests.Convert_ReturnCorrectConvertedValue(Decimal value, String correctValueAsString) in /builds/products/Tests.Unit/Models/Domain/Converters/DecimalToStringConverterTests.cs:line 30
```

When I'm replaced `new CultureInfo("en-us")` with `CultureInfo.GetCultureInfo("en-us")` then unit tests were passed.

**Comment by tarekgh** [comment]
@abakumov-v the difference between 

```C#
new CultureInfo(...)
```

and 

```C#
CultureInfo.GetCultureInfo(...) 
```

is GetCultureInfo created with turning off the user override while "new CultureInfo()" is created with user overrides is on. This means you have changed some settings on your machine. you may run `intl.cpl` then click on `Additional Settings` button to see the formats of the numbers there.

**Comment by Clockwork-Muse** [comment]
> `value.ToString("F2", new CultureInfo("en-us"));`

... how are you getting 3 decimal spaces out of this, anyways?

>`[InlineData(0.123, "0.12")]`

Note that the value `0.123` is actually **double** here, not decimal.  You should probably be initializing them with `0.123m` (note the trailing `m`, [which is the decimal literal specifier](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types#real-literals)).

> `new CultureInfo("en-us")`

Also note that the culture identifier string is wrong - [the country code should be capitalized](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo?view=netframework-4.8#culture-names-and-identifiers): `"en-US"`.  Although the casing will be ignored for methods in the relevant C# classes, it's still preferable to correct this.
