### ISSUE TITLE
Unify the CoreClr and aot System.Reflection.Extensions.dll partial facade.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#11222]
Steps:

- In the CoreRt repo, rename <a href="https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/Reflection/CustomAttributeExtensions.cs#L65">CustomAttributeExtensionsSoonToBe</a> to CustomAttributeExtensions. You'll also need to update references to it (<a href="https://github.com/dotnet/corert/blob/nmirror/src/System.Private.CoreLib/src/System/Reflection/LegacyCustomAttributeApis.cs#L20">here</a> and <a href="https://github.com/dotnet/corert/blob/nmirror/src/System.Private.Reflection.Core/src/System/Reflection/Runtime/General/LegacyCustomAttributeApis.cs#L25">here</a>) 
<b>Do not
   commit the rename itself at this step (tests will start failing with MissingMetadataExceptions
   because ILC doesn't expect to see two CustomAttributeExtension classes.)</b>
- Build a new version of the .Net Native targeting pack and publish to myget. 

- Wait for new targeting pack to appear on myget.

- Change the aot version of <a href="https://github.com/dotnet/corefx/blob/master/src/System.Runtime/src/System.Runtime.csproj">System.Runtime.dll</a> to

     - consume the new targeting pack.
     - TypeForward CustomAttributeExtensions to System.Private.Corelib
     - TypeForward BindingFlags to System.Private.Corelib.
     - TypeForward InterfaceMapping to System.Private.Corelib.
     - Implement the ReflectionRuntimeExtensions class at a thin layer (just copy over the <a href="https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Reflection/RuntimeReflectionExtensions.cs">CoreClr source code</a> verbatim.)
      
- Change the aot version of <a href="https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Extensions/src/System.Reflection.Extensions.csproj">S.R.Extensions.dll</a> to a pure facade that typeforwards 
     everything (ReflectionRuntimeExtensions, CustomAttributeExtensions and InterfaceMapping)
     to System.Runtime.

     Note that this is the exact same construction we want for CoreClr so this should get rid of the
     distinction between "aot" and "not-aot." All the internal machinery (CustomAttributeSearcher,
     CustomAttributeInheritanceRules should be mothballed.)

- Publish the new System.Runtime.dll and new S.Reflection.Extensions.dll to myget.

- Back to corert - consume the new S.Reflection.Extensions.dll and the new System.Runtime.dll and commit this and the CustomAttributeExtensionsSoonToBe rename in one delta.

**Comment by SedarG** [comment]
> Implement the ReflectionRuntimeExtensions class at a thin layer (just copy over the CoreClr source code verbatim.)

@AtsushiKan, why shall we have this class in S.Runtime? I'd pull that in o System.Private.CoreLib on CoreRT and have S.Runtime forward it to mscorlib and system.private.corelib for both CoreCLR and CoreRT respectively. Is there a reason to keep a wrapper in S.Runtime?

**Comment by AtsushiKan** [comment]
Well we don’t need it in Corelib and we’d like to keep the shared stuff as small as possible. It could probably be pulled out of CoreClr’s Corelib too.

Having said that, if I’m missing something major and it’s not extractable out of CoreClr’s corelib, I don’t have a major objection to putting in N’s Corelib too.

**Comment by SedarG** [comment]
I see. CoreCLR and CoreRT implementations are mostly similar. But there some differences. 
* [public static MethodInfo GetMethodInfo(this Delegate del)](https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Extensions/src/System/Reflection/RuntimeReflectionExtensions.cs#L114) is quite different. 
* CoreCLR implementation uses RuntimeType and RuntimeMethodInfo which doesn't exist in CoreRT.

Given these differences, keeping RuntimeReflectionExtensions close to as is sounds like the easiest thing to do.

**Comment by AtsushiKan** [comment]
For GetMethodInfo(this Delegate), just have it call Delegate::Method like the CoreClr version does. I’ve already restored that functionaliy in corert.

The “is RuntimeType/RuntimeMethodInfo” checks – hmm, well that’s annoying.

I wonder if we really need to keep those restrictions – now that we’ve brought all those underlying apis back, I don’t think there’s any purpose to those checks.

**Comment by SedarG** [comment]
Another question: current CoreRT implementation leverages an IEnumerable extension - AsNothingButIEnumerable-, which ensures that an untrusted caller cannot cast back to array or list. CoreCLR implementation doesn't do that. Blocking casting could be a breaking change for CoreCLR.  On the other hand it might be a legitimate breaking change. What's your guidance about it?

**Comment by AtsushiKan** [comment]
I think it’s fair to say our goals have changed 180 since those AsNothingButIEnumerable<> days. For a case like this, at least, I say drop the AsNothingButIEnumerable<> and return what CoreClr has always done.

**Comment by SedarG** [comment]
FYI, pending on 
* https://github.com/dotnet/buildtools/issues/1039 
* and Maestro subscriptions to get updated after switching to master
