### ISSUE TITLE
Binary Literal Formatting

### ISSUE THREAD

**Issue by shaggygi** [dotnet/corefx#11228]
Just adding this to this repo just in case.  Please see https://github.com/dotnet/roslyn/issues/215 for more details.

**Comment by stephentoub** [comment]
Thanks, @shaggygi.  Once we update the repo to use C# 7 features, we can start using binary literals where they're beneficial for readability/maintainability, but we don't plan to do a sweep through the code changing all possible uses to be binary literals.

**Comment by shaggygi** [comment]
Sounds good @stephentoub I was hoping to verify if there was already discussions to use string formatting like we can with hexadecimal.  This would be a good feature in the future as I had a few previous cases to process bits to string values.

**Comment by stephentoub** [comment]
@shaggygi, maybe I misunderstood what you were asking for.  Were you looking to be able to use the "0b01010101" notation in corefx code?  Or were you asking to be able to have methods like ToString on Int32, Int64, etc. return a string with that notation?

**Comment by shaggygi** [comment]
@stephentoub  I had originally asked a question in this issue dotnet/roslyn#215 if there was design discussions on how binary literals would be used with string interpolation and such.  Someone mentioned I should forward the question in CoreFx repo.

For example..  what would the format be for binary literals compared to using hexadecimal $"{value:X2}";

It would be nice to take a value of 0xBAC0 and quickly convert it to the bit pattern string of "1011101011000000".

**Comment by stephentoub** [comment]
The Convert class already has an overload of ToString that takes both a number and a base, so:
```Console.WriteLine(Convert.ToString(0xBAC0, 2));```
prints out:
```
1011101011000000
```

**Comment by shaggygi** [comment]
Oh, good.  This is nice to know!  Thx
