### ISSUE TITLE
Please publish new file naming convention for generic types

### ISSUE THREAD

**Issue by dsaf** [dotnet/corefx#11244]
Are backticks to be replaced with underscores now?

https://github.com/dotnet/corefx/commit/eef844ecd30ff2aff2f82d4b73baee356e7b0d08
https://github.com/dotnet/corefx/tree/master/src/System.Collections.Immutable/src/System/Collections/Immutable

The compiler and also Entity Framework still follow the current convention:

https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore/DbSet%60.cs

https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Syntax/SyntaxList%601.cs

Thank you.

**Comment by weshaggard** [comment]
We don't have any file naming convention and I'm not sure we need one. I'd be fine with people using backticks in filenames if it didn't cause any issues. Unfortunately it does cause some issues with our engineering system for producing symbol packages so we are going to block them for now.
