### ISSUE TITLE
Use .pkgproj references when using TestWithLocalLibraries

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#11257]
Today the `TestWithLocalLibraries` parameter has a faulty logic on how to pick the assets that are used to run tests on assemblies when the property is passed. Instead, we should use .pkgproj references to let nuget do the logic of selecting the right asset in every case.

related comment: https://github.com/dotnet/buildtools/pull/995#issuecomment-243517434

**Comment by mellinoe** [comment]
@joperezr Is this still an issue?

**Comment by joperezr** [comment]
We actually don't even use TestWithLocalLibraries in our pipebuilds anymore, so I guess we could close this one.
