### ISSUE TITLE
Port S.Web.HttpUtility

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#11262]
This is really separate to the rest of S.Web.dll, and it packaged into S.Web.Services.dll on Android. Here's the members:

```
T:System.Web.HttpUtility
M:System.Web.HttpUtility.ParseQueryString(System.String)
M:System.Web.HttpUtility.UrlEncode(System.String)
M:System.Web.HttpUtility.HtmlDecode(System.String)
M:System.Web.HttpUtility.UrlDecode(System.String)
M:System.Web.HttpUtility.HtmlAttributeEncode(System.String)
M:System.Web.HttpUtility.JavaScriptStringEncode(System.String)
M:System.Web.HttpUtility.HtmlEncode(System.String)
M:System.Web.HttpUtility.HtmlEncode(System.Object)
M:System.Web.HttpUtility.UrlEncode(System.String,System.Text.Encoding)
M:System.Web.HttpUtility.#ctor
M:System.Web.HttpUtility.HtmlAttributeEncode(System.String,System.IO.TextWriter)
M:System.Web.HttpUtility.HtmlDecode(System.String,System.IO.TextWriter)
M:System.Web.HttpUtility.HtmlEncode(System.String,System.IO.TextWriter)
M:System.Web.HttpUtility.JavaScriptStringEncode(System.String,System.Boolean)
M:System.Web.HttpUtility.ParseQueryString(System.String,System.Text.Encoding)
M:System.Web.HttpUtility.UrlDecode(System.Byte[],System.Int32,System.Int32,System.Text.Encoding)
M:System.Web.HttpUtility.UrlDecode(System.Byte[],System.Text.Encoding)
M:System.Web.HttpUtility.UrlDecode(System.String,System.Text.Encoding)
M:System.Web.HttpUtility.UrlDecodeToBytes(System.Byte[])
M:System.Web.HttpUtility.UrlDecodeToBytes(System.Byte[],System.Int32,System.Int32)
M:System.Web.HttpUtility.UrlDecodeToBytes(System.String)
M:System.Web.HttpUtility.UrlDecodeToBytes(System.String,System.Text.Encoding)
M:System.Web.HttpUtility.UrlEncode(System.Byte[])
M:System.Web.HttpUtility.UrlEncode(System.Byte[],System.Int32,System.Int32)
M:System.Web.HttpUtility.UrlEncodeToBytes(System.Byte[])
M:System.Web.HttpUtility.UrlEncodeToBytes(System.Byte[],System.Int32,System.Int32)
M:System.Web.HttpUtility.UrlEncodeToBytes(System.String)
M:System.Web.HttpUtility.UrlEncodeToBytes(System.String,System.Text.Encoding)
M:System.Web.HttpUtility.UrlEncodeUnicode(System.String)
M:System.Web.HttpUtility.UrlEncodeUnicodeToBytes(System.String)
M:System.Web.HttpUtility.UrlPathEncode(System.String)
```

Only the first 10 or so show up with usage in our corpus, but they get up to 20% usage in Xamarin apps.

@weshaggard Which contract should we put these on?

**Comment by davidsh** [comment]
This should really just be a fascade over the real implementation (WebUtility) which is now here:
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs#L641

This new class was created a while back when we were doing .NET Store Profile. It was done (at that time) to avoid bringing in System.Web.

```c#
namespace System.Net
{
    public static partial class WebUtility
    {
        public static string HtmlDecode(string value) { return default(string); }
        public static string HtmlEncode(string value) { return default(string); }
        public static string UrlDecode(string encodedValue) { return default(string); }
        public static byte[] UrlDecodeToBytes(byte[] encodedValue, int offset, int count) { return default(byte[]); }
        public static string UrlEncode(string value) { return default(string); }
        public static byte[] UrlEncodeToBytes(byte[] value, int offset, int count) { return default(byte[]); }
    }
}
```

**Comment by justinvp** [comment]
> This new class was created a while back when we were doing .NET Store Profile

Not that it really matters, but for the sake of historical accuracy... we added WebUtility in .NET 4 for the Client Profile since it didn't have System.Web, if I recall correctly 😉

**Comment by danmosemsft** [comment]
@davidsh Thanks for that pointer. That class does not have all the members eg ParseQueryString and JavaScriptStringEncode both seem to have usage. Should we grow the class in place?

**Comment by davidsh** [comment]
>Not that it really matters, but for the sake of historical accuracy... we added WebUtility in .NET 4 for the Client Profile since it didn't have System.Web, if I recall correctly :wink:

@justinvp Thx for the reminder of the history. I actually have the original emails from this topic 8+ years ago that I found in my database.

@danmosemsft In terms of whether to grow the `System.Net.WebUtility` class in addition to or instead of putting back the origin `System.Web.HttpUtility` class.......that is a question that folks like @terrajobst should weigh in on.

cc: @CIPop @himadrisarkar
