### ISSUE TITLE
ArgumentOutOfRangeException when combining Enumeration Flags in RegexOptions

### ISSUE THREAD

**Issue by caleblloyd** [dotnet/corefx#11270]
There seems to be a problem with combining RegexOptions in .NET Core.  Run the following 2-line console program:

```
var wordRegex = new Regex(@"[\w\#@]+", RegexOptions.Compiled | RegexOptions.ECMAScript);
System.Console.WriteLine(wordRegex.IsMatch("asdf"));
```

Produces the following run-time error:

```
Unhandled Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: options
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options)
   at FlagsAttrBug.Program.Main(String[] args)
```

[Documentation](https://docs.microsoft.com/en-us/dotnet/core/api/system.text.regularexpressions.regexoptions#System_Text_RegularExpressions_RegexOptions_ECMAScript) explicitly states that these two flags can be used together:

> Enables ECMAScript-compliant behavior for the expression. This value can be used only in conjunction with the IgnoreCase, Multiline, and Compiled values. The use of this value with any other values results in an exception.

This works fine in other versions of .NET Framework, for example it works fine in .NET Framework 3.5.

Version info:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
Version:            1.0.0-preview2-003121
Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
OS Name:     ubuntu
OS Version:  16.04
OS Platform: Linux
RID:         ubuntu.16.04-x64
```

**Comment by jasonwilliams200OK** [comment]
Comparing:

http://referencesource.microsoft.com/#System/regex/system/text/regularexpressions/Regex.cs,204

with:

https://github.com/dotnet/corefx/blob/6c5d560/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs#L151-L159

we are definitely missing `RegexOptions.Compiled` here.

**Comment by Priya91** [comment]
Yeah we should include this option there, although currently RegexOptions.Compiled is a no-op in .net core.

**Comment by nikitozz** [comment]
Create a PR: https://github.com/dotnet/corefx/pull/14269

**Comment by Priya91** [comment]
Thanks @nikitozz will merge when CI passes.
