### ISSUE TITLE
Factor Microsoft.CodeAnalysis.Differencing to a separate CoreFx nuget package

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#1127]
Roslyn implements a general tree diffing algorithm in Microsoft.CodeAnalysis.Workspaces.dll based on "Change Detection in Hierarchically Structured Information" by Sudarshan S. Chawathe, Anand Rajaraman, Hector Garcia-Molina, and Jennifer Widom (http://ilpubs.stanford.edu/115/1/1995-46.pdf) 

The implementation doesn't have any dependencies on Roslyn and can be factored out to a separate library.

**Comment by Maxwe11** [comment]
Why this should be in corefx?

**Comment by ellismg** [comment]
We think that pulling this sort of logic out of Roslyn if we can make it general purpose is a good idea.  Figuring out what repo it ends up living in is still an open question.  This is probably to small to be a stand alone git project, even though it would be in its own contract.

**Comment by tmat** [comment]
I think the repo could be something like "advanced algorithms & data structures". We have other stuff in Roslyn that could be general purpose (e.g. http://en.wikipedia.org/wiki/Bloom_filter).

**Comment by karelz** [comment]
It won't be part of corefx repo. It would be best to track it in Roslyn repo where the code lives today.
Discussed offline with @tmat, closing.
