### ISSUE TITLE
Building System.Private.Xml with TargetGroup=netcore50aot Failed

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#11274]
src\System.Private.Xml\src\System.Private.Xml.csproj does not build with /p:TargetGroup=netcore50aot.

The following command fails,
```
D:\OSS\corefx-1\corefx\src\System.Private.Xml\src>msbuild System.Private.Xml.csproj /p:TargetGroup=netcore50aot
```

**Comment by danmosemsft** [comment]
@shmao does this still repro for you? it seems to work for me

**Comment by shmao** [comment]
I confirm that this worked for me. Thanks, @danmosemsft . 

Closing the issue.

**Comment by shmao** [comment]
The issue probably was fixed by https://github.com/dotnet/corefx/pull/11527.
