### ISSUE TITLE
Publish build-info to projectk-tfs/release/1.1.0 when building 1.1.0 on TFS

### ISSUE THREAD

**Issue by dagood** [dotnet/corefx#11278]
Currently the versions repo structure is based on github branches, with [`projectk-tfs/master` and `projectk-tfs/release/1.0.0`](https://github.com/dotnet/versions/tree/master/build-info/dotnet/projectk-tfs). In reality these build-infos come from ProjectK and ProjectKRel.

Assumption: we will build any remaining TFS-side part of 1.1.0 using ProjectKRel.
If that's true, when it starts building 1.1.0 we should change where it posts its build info to `projectk-tfs/release/1.1.0`. We'll also need to change the CoreFX build-info dependency.

This will also apply to ProjectNRel. (Producing the NETNative targeting pack.)

Does this sound accurate to the branching plan, @weshaggard?

/cc @SedarG

**Comment by weshaggard** [comment]
Yes that sounds reasonable.

**Comment by dagood** [comment]
Closing. For 1.1.0, nothing is being built on TFS so this is not applicable.
