### ISSUE TITLE
Move `List<T>` and `EqualityComparer/Comparer<T>` to CoreLib

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#11284]

**Comment by jkotas** [comment]
@SedarG Could you please include these in work that you will be doing for #11222 and similar issues? Let me know if I can help.

**Comment by stephentoub** [comment]
(Just as a housekeeping note, for cases like List and EqualityComparer where the coreclr repo already contains the source being used for coreclr and corefx contains the source being used for corert, when we add these to corert let's please delete the corresponding source from corefx.)

**Comment by SedarG** [comment]
@jkotas @weshaggard , System.Collections is currently built against System.Runtime and it consumes ISet<T> from that library. Moving List<T>, Comparer<T>, EqualityComparer<T> down to CoreLib and have S.Collections forward those to CoreLib will conflict with S.Runtime. Resolving that conflict will be significant effort and ugly. I am thinking to move those types to S.Runtime, and have S.Runtime forward them to CoreLib. That's for all the configurations. Does it sound reasonable? Is there anything that I'm missing?

**Comment by weshaggard** [comment]
Another potential option is building System.Collections against System.Private.CoreLib? If that doesn't work we can entertain the idea of moving more things down, but I would like to review the full set of types first.

**Comment by SedarG** [comment]
> Another potential option is building System.Collections against System.Private.CoreLib

S.P.CoreLib doesn't suffice in replacing S.Runtime. `ISet<T>` is in [S.Runtime](https://github.com/dotnet/corefx/blob/master/src/System.Runtime/src/System.Runtime.csproj#L34)  and not in S.P.CoreLib. I either need to move `ISet<T>` down to S.P.CoreLib, or to S.Collections or move `List<T>`, `Comparer<T>` and `EqualityComparer<T>` to S.Runtime.

**Comment by jkotas** [comment]
> S.P.CoreLib doesn't suffice in replacing S.Runtime

You can build against both S.P.CoreLib and S.Runtime. It allows you to keep as much stuff as possible in S.Runtime, and move the rest down. It is done in number of projects. In fact, S.Collections does it for CoreCLR today - https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System.Collections.csproj#L21. You just need to enable this path for CoreRT as well.
