### ISSUE TITLE
Revisit System.Diagnostics.Tests.DebugTests to test Full framework implementation.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#11288]
The tests under System.Diagnostics.Tests.DebugTests in System.Diagnostics.Debug.Tests.dll are skipped for Net46 runs, as they use an internal field from System.Diagnostics.Debug implementation from .NET Core that's not available in Desktop implementation.

Desktop implementation source code is [here](https://referencesource.microsoft.com/#System/compmod/system/diagnostics/Debug.cs,632c6da37ce825df).

**Comment by karelz** [comment]
The Core-only API should be tracked with netfx-port-consider. If we approve it, it of course will come with these tests. @joperezr @Priya91 can you please confirm the Core-only API is tracked appropriately?

Closing as it has no impact on .NET Core.
