### ISSUE TITLE
Proposal: Add support for 'precompiled' inputs to String.IndexOfAny/LastIndexOfAny

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#11282]
## Background

`IndexOfAny` has to go through a string and see if any of the characters match one in a specified character array. Here is an example of how it could be implemented:

``` cs
public static int IndexOfAny(this string s, char[] anyOf)
{
    for (int i = 0; i < s.Length; i++)
    {
        for (int j = 0; j < anyOf.Length; j++)
        {
            if (s[i] == anyOf[j]) return i;
        }
    }

    return -1; // not found
}
```

This implementation can be extremely inefficient for larger arrays, however, since it requires making a pass over the array for every char in the string. So, the [current implementation](https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/String.Searching.cs#L98-L99) does a trick to speed this up. What it does is, before actually going through the string, it 'compiles' the char array down to a 256-bit long "probabilistic map." It takes each char and splits it into 2 bytes M and N, and sets the Mth and Nth bits of the map to indicate that those bytes are present in the array. When it wants to see if a char is in the array, it first checks if the 2 bytes corresponding to the char are set. Assuming there are no "collisions," (one char that steals bytes from 2 different chars, which will not happen for ASCII data), checking if the array contains a char is now O(1).
## Problem

This probabilistic map has to be re-compiled for every input array. Even if the exact same array is passed multiple times to `IndexOfAny`, which means the exact same bitmap will be generated, it will still have to re-initialize and fill out the same map every time. This can particularly hurt with large arrays; for example, I posted findings in [this issue](https://github.com/dotnet/corefx/issues/10973#issuecomment-243640020) that initializing this map was consuming **as much as 60% of CPU time** in `Path.Combine`, in spite of all of the other allocations going on in the method.
## Proposal: Pre-compiled Probabilistic Maps

I propose adding an API that would allow end-users to "precompile" the map before passing it in to `IndexOfAny` / `LastIndexOfAny`. If this is a frequently used function in their code, then this will undoubtedly result in performance gains since there is no "initialization" work to be done prior to processing the string. (Of course, people will still be free to use the `char[]`-based overload.)

Here is a prototype of what this API could look like:

``` cs
namespace System
{
    public class String
    {
        // Existing API
        public int IndexOfAny(char[] anyOf);
        public int IndexOfAny(char[] anyOf, int startIndex);
        public int IndexOfAny(char[] anyOf, int startIndex, int count);

        public int LastIndexOfAny(char[] anyOf);
        public int LastIndexOfAny(char[] anyOf, int startIndex);
        public int LastIndexOfAny(char[] anyOf, int startIndex, int count);

        // New API
        public int IndexOfAny(ProbabilisticMap anyOf);
        public int IndexOfAny(ProbabilisticMap anyOf, int startIndex);
        public int IndexOfAny(ProbabilisticMap anyOf, int startIndex, int count);

        public int LastIndexOfAny(ProbabilisticMap anyOf);
        public int LastIndexOfAny(ProbabilisticMap anyOf, int startIndex);
        public int LastIndexOfAny(ProbabilisticMap anyOf, int startIndex, int count);
    }
}

namespace System.Text
{
    public class ProbabilisticMap
    {
        public ProbabilisticMap(char[] anyOf); // All of the "compilation" work is done here
    }
}
```

`ProbabilisticMap` would internally hold references to the char array and the bitmap. These members would be accessible from the String functions, but not from end-user code. We would make a defensive copy of the `anyOf` array to prevent the map from changing if the user mutated the array after passing it to the constructor.
## Usage

Typical usage would involve caching the `ProbabilisticMap` in a static field and then passing it to `IndexOfAny` from a function. For example, here is how [this snippet](https://github.com/jamesqo/corefx/blob/1962d3f68e4d547cd1904f435e939c63b137cf1d/src/System.Private.Uri/src/System/Uri.cs#L1710-L1717) from `Uri.CheckForColonInFirstPathSegment` could be rewritten:

``` cs
private static readonly ProbabilisticMap s_pathDelimsMap =
    new ProbabilisticMap(new char[] { ':', '\\', '/', '?', '#' });

private static bool CheckForColonInFirstPathSegment(string uriString)
{
    int index = uriString.IndexOfAny(s_pathDelimsMap);

    return (index >= 0 && uriString[index] == ':');
}
```

What are your thoughts on this?

/cc @benaadams, @GSPP, @omariom

**Comment by jkotas** [comment]
I think this would be a good candidate for independent nuget package.

**Comment by GSPP** [comment]
This could be a more general API what allows to precompile a set of strings to find. For multi-char strings this could use an algorithm such as Boyer–Moore or Aho-Corasick (or better; this is the fist name that came to mind). It could optimize the single char case with this map idea. The same idea also helps repeated searches for a single string.

I have implemented such a thing and it often comes in handy. Searching for substrings is a very common thing to do and surprisingly expensive.

Being able to enumerate all match indexes and match lengths (can vary due to culture) is handy as well.

**Comment by svick** [comment]
If this is implemented, I don't think the type that holds the precompiled information should be called `ProbabilisticMap`, because that pretty much exposes implementation details by naming the algorithm used, thus more or less preventing the use of another precompilation algorithm in a future version or alternative implementation of corefx.

**Comment by AlexGhiondea** [comment]
I am not sure if the right place for this is in CoreCLR/FX. I think there is value in having this be a separate package so people who want / know how to use it can.

I am going to close this for now, but please reopen if you disagree with this.
