### ISSUE TITLE
Remove redundant internal type definitions that are now publically exposed elsewhere

### ISSUE THREAD

**Issue by kouvel** [dotnet/corefx#11299]
There are some internal type definitions under the Common directory, which are included into multiple projects. Those types are now publically exposed from System.Runtime or elsewhere. Remove the internal type definitions in favor of the public types.

This would involve retargeting any projects that were including the internal types to netstandard1.7, so that they can reference the public type.
- SafeHandleMinusOneIsInvalid
- SafeHandleZeroOrMinusOneIsInvalid
- SafeFileHandle

**Comment by joperezr** [comment]
@kouvel do we still need this for 2.0?

**Comment by kouvel** [comment]
It's cleanup work relevant to the ns2.0 work but not anything required for ns2.0

**Comment by joperezr** [comment]
ok, I'll remove the 2.0 milestone then. It is currently assigned to you, are you planning on working on it? If not, we should just add enough information in here and then flag it as up for grabs

**Comment by kouvel** [comment]
I don't think I will get to this any time soon, unassigned and marked

**Comment by karelz** [comment]
Should be easy to do - we may need to provide extra help with retargetting if needed.

**Comment by danmosemsft** [comment]
13f626390abb1876f6c27517c91ee71547ca8667 should resolve this
