### ISSUE TITLE
S.S.P missing Token property

### ISSUE THREAD

**Issue by ghost** [dotnet/corefx#11297]
As per http://referencesource.microsoft.com/#mscorlib/system/security/principal/windowsidentity.cs,ec5619fe4ea57a04, `WindowsIdentity.Token` can be defined in CoreFX as:

```c#
public virtual IntPtr Token => m_safeTokenHandle.DangerousGetHandle();
```

The current workaround for consumers is: `AccessToken.DangerousGetHandle()`.

**Comment by bartonjs** [comment]
This was fixed by https://github.com/dotnet/corefx/pull/11700
