### ISSUE TITLE
[WebSockets] If TCP connection closed without WebSocket close, ManagedWebSocket keeps returning 0-byte frames

### ISSUE THREAD

**Issue by anurse** [dotnet/corefx#11309]
**Overview:**

In some browsers and clients, it is possible to terminate the underlying TCP connection without a proper close handshake. In these cases, `ManagedWebSocket` begins interminably returning 0-byte frames from `ReceiveAsync`. This can be observed using a Safari browser, and running a SignalR sample as described here: https://github.com/aspnet/SignalR-Server/issues/202, but I've produced a candidate fix and a simpler repro (detailed below).

**Repro steps** (sorry they are a bit rough, but I needed to use the Node WebSocket client to simulate the things I'm seeing). The repro requires VS+.NET Core tools and Node JS (again, it was the easiest client I could use to exhibit the behavior reliably)

1. Clone https://github.com/aspnet/WebSockets, check out `anurse/websocket-repro` and open the SLN up in VS
2. Run `dotnet restore` in the repo root
3. Run `dotnet run` from the `samples\EchoApp` directory in the repo.
4. Check the output to verify the port number (it should be `5000`, but if not, just adjust the final step as necessary)
5. In another console window, clone https://gist.github.com/anurse/fe87ecf8aa01832a99dd247c64cb4595 (clone URL: https://gist.github.com/fe87ecf8aa01832a99dd247c64cb4595.git) somewhere and `cd` to it
6. Run `node main.js ws://localhost:5000`

**Expected results:**

```
ps1 # node main.js ws://localhost:5000
WebSocket Client Connected
Received: 'Hello, World'
echo-protocol Connection Closed
```

And the log output from the server shows an exception because the underlying stream was closed without a close handshake. This is OK, since the client intentionally terminates the connection abruptly. Though maybe an exception isn't the best way to communicate that, who knows :).

**Actual results:**

Non-stop output until Ctrl-C is pressed (a few times ;P):

```
Received: ''
Received: ''
Received: ''
Received: ''
Received: ''
Received: ''
Received: ''
Received: ''
Received: ''
Received: ''
Received: ''
Received: ''
Received: ''
Received: ''
Received: ''
Received: ''
Received: ''
Received: ''
Received: ''
Received: ''
Received: ''
```

Same on the server log

```
dbug: Echo[0]
      Received Frame Text: Len=0, Fin=True:
dbug: Echo[0]
      Sent Frame Text: Len=0, Fin=True:
dbug: Echo[0]
      Received Frame Text: Len=0, Fin=True:
dbug: Echo[0]
      Sent Frame Text: Len=0, Fin=True:
dbug: Echo[0]
      Received Frame Text: Len=0, Fin=True:
dbug: Echo[0]
      Sent Frame Text: Len=0, Fin=True:
dbug: Echo[0]
      Received Frame Text: Len=0, Fin=True:
dbug: Echo[0]
      Sent Frame Text: Len=0, Fin=True:
dbug: Echo[0]
      Received Frame Text: Len=0, Fin=True:
dbug: Echo[0]
      Sent Frame Text: Len=0, Fin=True:
```

What's happening is that the call to EnsureBufferContainsAsync at https://github.com/dotnet/corefx/blob/master/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/ManagedWebSocket.cs#L618 is reading zero bytes from the underlying stream (because it has closed, and is thus reporting end-of-stream as per the Stream contract). However, `throwOnPrematureClosure` is `false`, which causes an empty frame to be returned. This repeats indefinitely as the caller keeps trying to read new frames.

Changing `throwOnPrematureClosure` to `true` on this line **fixes the issue**, but I wasn't sure if this was safe to do since it seems intentional. I can send a PR to fix this if that sounds like the right fix. It doesn't seem too unsafe though, since if the stream closes, we should be returning some indication of that rather than an empty text frame.

/cc @stephentoub @Tratcher @moozzyk

**Comment by stephentoub** [comment]
Thanks, @anurse.  You can see in the comment two lines later that this was intentional:
https://github.com/dotnet/corefx/blob/master/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/ManagedWebSocket.cs#L621-L622
But that was based on my understanding of what the behavior was supposed to be.  If that understanding is incorrect and we're supposed to be throwing in this case, we can of course throw an exception rather than returning there.  What behavior does the Windows ClientWebSocket implementation in coreclr and desktop do in this case?  We should do whatever those do.

**Comment by Tratcher** [comment]
It should throw if it reaches the end of the stream before it receives a Close message.

**Comment by Tratcher** [comment]
Alternatively, return a Close message instead of a Text message.

**Comment by anurse** [comment]
Yeah, the big problem is that the socket is returning an empty message under a condition that will never ever change (i.e. the underlying Stream is at the end). As a result, it just spams the caller with empty messages. Returning a close message with a status code indicating that the connection was terminated might be more appropriate (and avoids "Exceptions-as-control-flow")

**Comment by stephentoub** [comment]
That's why I asked what the existing Windows implementations do.  We should try to match that.

**Comment by anurse** [comment]
It turns out that there is a Close Status code exactly for this: 1006 (https://tools.ietf.org/html/rfc6455#section-7.4.1). Unfortunately it isn't part of the WebSocketCloseStatus enum...

I can try to look in to what existing Windows implementations do from the "client" side when this happens.

**Comment by anurse** [comment]
The Windows ClientWebSocket throws a WebSocketException during the receive:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Net.WebSockets.WebSocketException: The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApp1.Program.<AsyncMain>d__1.MoveNext() in c:\users\anurse\documents\visual studio 2015\Projects\ConsoleApp1\src\ConsoleApp1\Program.cs:line 24
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at ConsoleApp1.Program.Main(String[] args) in c:\users\anurse\documents\visual studio 2015\Projects\ConsoleApp1\src\ConsoleApp1\Program.cs:line 13
```

**Comment by Tratcher** [comment]
returning a 1006 Close message would be preferred

**Comment by stephentoub** [comment]
For error cases like this, I would like to match the behavior we have on desktop and the behavior we have on coreclr already on Windows.  Sounds like that's an exception.  (It also seems a bit strange to me to manufacture a close frame and pretend that's what the receive received when there wasn't actually one.)

**Comment by benaadams** [comment]
The behavior on desktop does some really weird things.

It throws `COMException` with at least 3 different error codes, as well as WebSocketException and a few other different things. SignalR [has handling for COMException](https://github.com/aspnet/SignalR-Server/blob/11da2b7fff889eea84607beedd7b0a562a30facd/src/Microsoft.AspNetCore.SignalR.Server/WebSockets/WebSocketHandler.cs#L210-L230) and the "throw away the exception its a close" we used on Desktop was along these lines:

```csharp
private static bool ExpectedException(Exception e)
{
	if (e is ObjectDisposedException) return true;
	else if (e is OperationCanceledException) return true;
	else if (e is WebSocketException) return true;
	else if (e is HttpListenerException) return true;
	else
	{
		// Copied from SignalR
		var ce = e as COMException;
		if (ce != null)
		{
			switch ((uint)ce.ErrorCode)
			{
				// These are the three error codes we've seen in testing which can be caused by the TCP connection going away unexpectedly.
				case 0x800703e3:
				case 0x800704cd:
				case 0x80070026:
					return true;
			}
		}
	}
	return false;
}
```

```csharp
if (ExpectedException(e))
{
	Dispose();
	return;
}
if (e.InnerException != null && ExpectedException(e.InnerException))
{
	Dispose();
	return;
}
```

**Comment by benaadams** [comment]
Also the Exception thrown on various causes (TCP connection gone, not clean close etc) happen a lot - so it is a common case of control flow via exception handling - rather than a exceptional condition. :cry:

**Comment by stephentoub** [comment]
It may not be an ideal design, but we want the behavior of the same APIs to match as best as possible across OSes. And both desktop and coreclr on Windows are already in use. You disagree with the consistency desire? Does coreclr on Windows do something different here in this case?

**Comment by benaadams** [comment]
> You disagree with the consistency desire?

No, consistency is good.

> Does coreclr on Windows do something different here in this case?

I'm not sure what coreclr does. I was highlighting that full framework throws a wide range of errors and it would be nice if that wasn't replicated. However, it would probably be useful to detect the reason why it was closed if necessary.

**Comment by Tratcher** [comment]
The caller must handle both exceptions and close messages regardless, but which makes more sense to the user in this case. Nothing exceptional happened so why manufacture an exception? The socket was gracefully closed without a close frame and the spec says to return a close message.

**Comment by stephentoub** [comment]
> why manufacture an exception?

As I've said, my priority here is consistency across OSes.  I asked what the Windows implementation was doing, and was told it was throwing an exception for this case.  Is that not true on coreclr?

If it turns out the Windows coreclr implementation is returning a close message, then this implementation should, too.

If it turns out the Windows coreclr implementation is throwing, then this implementation should, too.  We're striving to reduce differences between platforms to ones we can't avoid, and a difference here is one we can avoid.

If it turns out the Windows coreclr implementation is throwing but you can convince @davidsh and @cipop that this is a bug to be fixed by instead returning a close message, then we can make both implementations return a close message.

**Comment by anurse** [comment]
Windows CoreCLR throws as well:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (The connection with the server was terminated abnormally) ---> System.Net.Http.WinHttpException: The connection with the server was terminated abnormally
   at System.Net.WebSockets.WinHttpWebSocket.InternalReceiveAsync(ArraySegment`1 buffer)
   at System.Net.WebSockets.WinHttpWebSocket.<ReceiveAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApp1.Program.<AsyncMain>d__1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at ConsoleApp1.Program.Main(String[] args)
```

I'll submit a PR to change the current behavior to throw in order to solve the immediate issue. We can examine other options separately.

**Comment by stephentoub** [comment]
Sounds good. Thanks.

**Comment by moozzyk** [comment]
:clap:
