### ISSUE TITLE
Reintroduce the use of Type.GetTypeCode in lieu of a custom implementation

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#11328]
It seems this member was reintroduced in https://github.com/dotnet/corefx/pull/6815. Can we take a dependency on it again for e.g. `TypeCode System.Dynamic.Utils.TypeExtensions.GetTypeCode(this Type)` instead of using `if` checks?

**Comment by bartdesmet** [comment]
When we do so, we can consider changing some code in `ILGen` to use `switch` rather than some `if` logic, e.g. in `EmitLoadValueIndirect`.

**Comment by VSadov** [comment]
Yes, we absolutely should use the actual API.

**Comment by bartdesmet** [comment]
It seems we still don't have access to `Type.GetTypeCode` when I try to use it.

**Comment by VSadov** [comment]
I think this was fixed in https://github.com/dotnet/corefx/pull/13325
