### ISSUE TITLE
Need EncryptedXml and supporting types in Core framework

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#1132]
This will likely depend on a large pile of other work, but I'd like to raise the issue.  In porting applications to use CoreCLR, I have run into the need for the [EncryptedXml class](https://msdn.microsoft.com/en-us/library/system.security.cryptography.xml.encryptedxml%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) more than once.  From looking around, there are various 3rd party encryption libraries that exist but this adds a cost to porting from 1st-party .NET  types.

Enabling EncryptedXml in the Core framework will also enable encrypted configuration files in ASP.NET 5 Core profile as well... currently the user must create their own implementation of an encrypted configuration on this platform.

**Comment by blowdart** [comment]
Added note, this would help enable WS-Fed middleware which people want.

**Comment by joshfree** [comment]
Moving this to 1.1.0

**Comment by karelz** [comment]
@danmosemsft @bartonjs is it part of netstandard2.0 work?

**Comment by bartonjs** [comment]
@karelz Probably not, since it's in System.Security.dll.

**Comment by danmosemsft** [comment]
@karelz it's not part of .NET Standard 2.0 because as @bartonjs points out System.Security.dll isn't, and the type isn't in Xamarin in some other assembly either.

https://apisof.net/catalog/System.Security.Cryptography.Xml.EncryptedXml says it's in Mono, but not Xamarin. I don't know why Xamarin doesn't include it.

**Comment by karelz** [comment]
It may require structural changes to original Desktop code.

**Comment by steveharter** [comment]
The initial code has just been merged.

**Comment by karelz** [comment]
The execution plan (and latest status) is in top-most post of issue #4278. If anyone wants to contribute, please let us know on the other issue.

**Comment by bartonjs** [comment]
#4278 ended up taking over for the entirety of the Cryptography.Xml namespace.  EncryptedXml should now be working.
