### ISSUE TITLE
Fix mapping table in our documentation

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#11321]
#11236 added some special target and itemgroups to dir.targets because the dotnet version that we have is not aware of the mapping between netcoreapp1.1 and netstandard1.7. Once we update the version of nuget that we use, then we should be able to remove this piece of code. This target is intended to track the work.

**Comment by davidsh** [comment]
What is "netstandard17"?  Isn't "netstandard16" mapping to .NET Framework 4.6.3 (vNext)?

So, then, what is netstandard17 exactly?

**Comment by joperezr** [comment]
No. Currently the mappings are:
- netstandard1.6 maps to netcoreapp1.0 and net462 (this is shipped)
- netstandard1.7 maps to netcoreapp1.1 and net463 (vnext)

That said, netstandard1.7 might change in the future, but that is what we are using currently in our dev/api branch

**Comment by davidsh** [comment]
>•netstandard1.6 maps to netcoreapp1.0 and net462 (this is shipped)

The documentation here says otherwise:
https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md

Can we fix the documentation?

**Comment by davidsh** [comment]
cc: @CIPop

**Comment by CIPop** [comment]
> No. Currently the mappings are:

>netstandard1.6 maps to netcoreapp1.0 and net462 (this is shipped)
>netstandard1.7 maps to netcoreapp1.1 and net463 (vnext)


@joperezr @ericstj Please either correct above or update the documentation at https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md:
/cc @weshaggard 

![image](https://cloud.githubusercontent.com/assets/8635911/18178208/49cba484-7032-11e6-88d8-28fc2dc85a91.png)

netstandard1.6 is 463
netstandard1.5 is 462 which contradicts above.

**Comment by joperezr** [comment]
The original issue was fixed since the workaround was removed, but I'll leave this open to track the updating of the mapping table in our docs.

**Comment by weshaggard** [comment]
@joperezr can you point me at the fix that removed the workaround?

**Comment by joperezr** [comment]
no, this was a different fix. Take a look at PR #11689, specifically at the changes made in dir.targets. Those were the ones I wanted to track with this issue, but they are already removed. Thanks for pointing me to the right versions table, should I just add a link from the page in corefx to go to the standard one, or would you rather have the content in both places?

**Comment by weshaggard** [comment]
A pointer would be good dotnet/standard repo would be best.

The hack that removed your workaround came from PR https://github.com/dotnet/corefx/pull/11763 which is still a hack that needs an issue tracking the proper fix. Perhaps another issue but we need one none-the-less.

**Comment by joperezr** [comment]
The mapping issue was fixed by @terrajobst when he forwarded the corefx documentation to netstandard in #13702

**Comment by joperezr** [comment]
Closing this one since this has been fixed. @weshaggard I opened #14070 to track removing the hack for copying nuget dlls

**Comment by CIPop** [comment]
@joperezr @weshaggard @terrajobst /cc @ericstj 😮 I can't find the table anymore. The code still contains a lot of TFMs. Is there a link to something new describing them?

From discussions with @karelz and @davidsh we are still going to have the various TFMs to identify if the lib is built for netcore or UWP, etc or if the TestTFM is targeting a particular platform or .Net Framework (net463).

**Comment by weshaggard** [comment]
The table is here https://github.com/dotnet/standard/blob/master/docs/versions.md

**Comment by CIPop** [comment]
Perfect! Thanks @weshaggard!
