### ISSUE TITLE
SortedList indexer implementation of IDictionary throws ArgumentNullException in Desktop

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#11324]
`SortedList<TKey,TValue>`, `IDictionary.this[object key]` throws ArgumentException when the key is not compatible with `TKey` 

On Desktop ArgumentNullException is thrown. ArgumentNullException is incorrect, as key is not null, ArgumentException is more suited. This is a behavior change, filing issue to track on what we want to do with these differences.

cc @terrajobst @weshaggard @stephentoub @danmosemsft

**Comment by weshaggard** [comment]
This doesn't really add enough value to really warrant the change from desktop so I we should just make .NET Core behave the same as .NET Framework.

**Comment by Priya91** [comment]
.NET Core Collections need to be cleaned up to throw ArgumentNullException in the specified cases in the issue description.

**Comment by robosek** [comment]
So when key is incompatible .NET Core Collections should throw ArgumentNullException instead of ArgumentException just like it is on Desktop ?

**Comment by Priya91** [comment]
> So when key is incompatible .NET Core Collections should throw ArgumentNullException instead of ArgumentException just like it is on Desktop ?

Yes, I don't think it's all of the collections, only generic SortedList IDictionary indexer implementation.

**Comment by karelz** [comment]
Fixed by above #12803
