### ISSUE TITLE
HttpClient Throws An Exception for Requests When the Resource Does Not Exist

### ISSUE THREAD

**Issue by StephenMP** [dotnet/corefx#11333]
**Issue**
When issuing a request using HttpClient to a Request-URI (resource) which does not exist, HttpClient throws an exception and does not handle gracefully. The exception is as follows:

```
{System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The server returned an invalid or unrecognized response
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()}
```

This leads to confusing behavior making it hard to test specific edge cases.

_NOTE_: This does NOT affect GET or HEAD as GET/HEAD requests return an OK (200) response which is documented in [Issue #11331](https://github.com/dotnet/corefx/issues/11331).

**Expected Behavior**
When running a request to a non-existent resource, HttpClient should NOT throw an exception, but rather, return a NotFound (404) response as the resource is not found.

**How to Reproduce**
Create a .NET Core Console App
Run the following code in Program.cs and notice that the above exception is thrown. Repeat using different request types other than HEAD or GET.
```
using System.Net.Http;

namespace ApiTester
{
    public class Program
    {
        public static void Main(string[] args)
        {
           using (var client = new HttpClient())
            {
                using (var request = new HttpRequestMessage(new HttpMethod("OPTIONS"), "http://www.this.resource.does/not/exit"))
                {
                    using (var response = client.SendAsync(request).Result)
                    {
                        var success = response.IsSuccessStatusCode;
                    }
                }
            }
        }
    }
}
```

**Comment by davidsh** [comment]
"http://www.this.resource.does/not/exit"
Can you clarify what you mean by "doesn't exist"? For example, if the server itself (DNS) doesn't exist and a TCP connection can't be made, then no HTTP response will ever come back from the server. You will get an exception.

If the server exists and just the pathname portion of the uri represents a resource that doesn't exist, it is up to the server to return a proper HTTP response status code. The client stack doesn't do that directly but simply returns what the server sends.

So, can you please clarify about the expectations around the uri itself and whether the server endpoint exists?

**Comment by davidsh** [comment]
cc: @stephentoub 

@StephenMP Hello, can you respond back with answers to the questions I asked?  At this point, we consider this issue as by-design as per my comments above.  Thanks!

**Comment by davidsh** [comment]
Please let us know if you are able to respond with answers to the above questions.  Thanks.

**Comment by StephenMP** [comment]
If the behavior expected is to throw an exception, that's fine. The is in relation to the previous issue I opened in which you receive a 200 response back on GET and DELETE requests. I wasn't sure which to post an issue on since the behavior between different request types is different.
