### ISSUE TITLE
HttpClient Returns Successful Status Code for HEAD or GET Request When the Resource Does Not Exist

### ISSUE THREAD

**Issue by StephenMP** [dotnet/corefx#11331]
**Issue**
When issuing a HEAD or GET request using HttpClient to a Request-URI (resource) which does not exist, the client returns an OK  (200) response.

This leads to edge cases where one may be trying to retrieve data from an external API and typed the resource incorrectly leading to an OK response, but no data. It also makes testing difficult due to unexpected behaviors.

**Expected Behavior**
HTTP Protocol specifies the following:

> 9.3 GET
> 
> **The GET method means retrieve whatever information (in the form of an entity) is identified by the Request-URI**. If the Request-URI refers to a data-producing process, it is the produced data which shall be returned as the entity in the response and not the source text of the process, unless that text happens to be the output of the process.
> ...
> 
> 9.4 HEAD
> 
> **The HEAD method is identical to GET except that the server MUST NOT return a message-body in the response**.
> ...

Thus, when running a HEAD or GET request to a non-existent resource, you should NOT receive an OK (200) response, but rather, a NotFound (404) as the resource does not exist (i.e. you cannot retrieve whatever information is available at a resource which does not exist).

**How to Reproduce**
Create a .NET Core Console App
Run the following code in Program.cs and notice that success is true and the response's status code is OK (200). Repeat using GET instead of HEAD and notice the same result.
```
using System.Net.Http;

namespace ApiTester
{
    public class Program
    {
        public static void Main(string[] args)
        {
           using (var client = new HttpClient())
            {
                using (var request = new HttpRequestMessage(new HttpMethod("HEAD"), "http://www.this.resource.does/not/exit"))
                {
                    using (var response = client.SendAsync(request).Result)
                    {
                        var success = response.IsSuccessStatusCode;
                    }
                }
            }
        }
    }
}
```

**Comment by davidsh** [comment]
```c#
"http://www.this.resource.does/not/exit"
```

Can you clarify what you mean by "doesn't exist"?  For example, if the server itself (DNS) doesn't exist and a TCP connection can't be made, then no HTTP response will ever come back from the server.  You will get an exception.

If the server exists and just the pathname portion of the uri represents a resource that doesn't exist, it is up to the server to return a proper HTTP response status code.  The client stack doesn't do that directly but simply returns what the server sends.

So, can you please clarify about the expectations around the uri itself and whether the server endpoint exists?

**Comment by davidsh** [comment]
cc: @stephentoub

@StephenMP Hello, can you respond back with answers to the questions I asked? At this point, we consider this issue as by-design as per my comments above. Thanks!

The other thing I want to mention is that you might be getting a 200 response back because your DNS services are intecepting DNS calls and returning 200 even though the DNS endpoint doesn't exist. This commonly occurs in consumer ISP connections unless disabled by the user.

**Comment by StephenMP** [comment]
My apologies on the delayed response; I've been busy.

Anyhow, the route "http://www.this.resource.does/not/exit" is a route which does not exist in the context that there is no domain "www.this.resource.does" and thus no server to handle the request. As per your comment:

> ...For example, if the server itself (DNS) doesn't exist and a TCP connection can't be made, then no HTTP response will ever come back from the server. You will get an exception.

I should be getting an exception, but I don't. I get a 200.

**Comment by davidsh** [comment]
If you are getting an HTTP response and not an exception, it is because the server sent a response.

This appears to be an issue with the ASP.NET server you are using and not an issue with the HttpClient itself.  HttpClient will not manufacture a response if one didn't come from the server.

I suggest you open an issue in the ASP.NET repo to have them investigate.

You could start with this repo: https://github.com/aspnet/Home

cc: @danroth27 might be able to assist.  His is the owner of ASP.NET.

**Comment by danroth27** [comment]
@StephenMP When I try the repro steps I get this exception (partial stack trace):

```
       InnerException: 
            HResult=-2147012889
            Message=The server name or address could not be resolved
            NativeErrorCode=12007
            Source=System.Private.CoreLib
            StackTrace:
                 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                 at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
                 at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
            InnerException: 
```

@davidsh Where is there any indication in this issue that ASP.NET is at all involved?

**Comment by StephenMP** [comment]
@danroth27 Interesting... I'm not at my home computer so I can't give my project.json for the above reproduction steps, but I can tell you that I just created a .NET Core Console App from the Visual Studio templates and ran the above code without any changes to the project loaded from the template. I have the most up-to-date SDK.

I originally found this issue when testing a proxy I wrote to interface with an API I wrote. I was testing edge cases for my proxy to ensure it could handle when the user gives an endpoint that doesn't exist. All requests other than GET and DELETE requests threw an exception as expected, but my tests for GET and DELETE failed because instead of an exception, I was getting 200s.

If you can't reproduce, I can check when I get home to see if I can still reproduce it. If not, then this is no longer an issue, if so, then it's still a problem.

@davidsh That's what I would think, but there is no server. It's being run from a .NET Core Console App and hitting a non-existent server. If I run the exact same code with any other request type that is not GET or DELETE, an exception is thrown.

**Comment by davidsh** [comment]
>I originally found this issue when testing a proxy I wrote to interface with an API I wrote. 

What proxy are you using?  It is quite possible that certain proxies will "create" an HTTP response even for endpoints that don't exist.  Does this repro without the proxy being involved?

**Comment by StephenMP** [comment]
It's my own proxy I wrote, so no, it's not just creating HTTP responses :) It's uses HTTP Client directly under the hood. It's inside of the proxy where I call HTTP client that I am seeing this odd behavior.
