### ISSUE TITLE
RegistyKey.CreateSubKey(string) not creating subkeys with write access by default on desktop.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#11332]
.NET Core implementation, uses the `RegistryKey.IsWritable()` method to check for write access on RegistryKey. `RegistryKey.IsWritable()` depends on `RegistryKey._state` set in `RegistryKey` ctor to writable by default for system keys.

Desktop implementation uses an extra `RegistryKey.checkmode` field of type `RegistryKeyPermissionCheck` to check for write access on `RegistryKey`. This field is set to a `RegistryKeyPermissionCheck.Default` upon accessing the system key property on `Registry`. And subsequent `RegistryKey.CreateSubKey` on system keys happens with instantiating `RegistryKey._state` with condition `this.checkmode == RegistryKeyPermissionCheck.ReadWriteSubKey`, hence, creating sub keys on the system keys with non-writable access.

cc @terrajobst @weshaggard @stephentoub @danmosemsft

**Comment by stephentoub** [comment]
Just so I understand, @Priya91, we believe this is a bug in desktop rather a bug in corefx?

**Comment by Priya91** [comment]
> Just so I understand, @Priya91, we believe this is a bug in desktop rather a bug in corefx?

Yeah, it's a bug in desktop..

**Comment by karelz** [comment]
@AlexGhiondea's tool will track it for Desktop porting (netfx-port-consider). Closing from .NET Core point of view.
