### ISSUE TITLE
A few System.Linq.Queryable.Tests issues on AOT

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#11343]
Four test failures:

```
System.Linq.Tests.QueryFromExpressionTests.ConditionalNotNotEqualAddPlusConstantNegateConstant
  System.PlatformNotSupportedException : UnsupportedExpressionType, UnaryPlus

System.Linq.Tests.QueryFromExpressionTests.ConditionalNotNotEqualAddCheckedPlusConstantNegateCheckedConstant
  System.PlatformNotSupportedException : UnsupportedExpressionType, UnaryPlus

System.Linq.Tests.ElementAtTests.IndexEqualsCount
  Assert.Equal() Failure
  Expected: index
  Actual:   ArgumentOutOfRange_Index

System.Linq.Tests.ElementAtTests.EmptyIndexZero
  Assert.Equal() Failure
  Expected: index
  Actual:   ArgumentOutOfRange_Index
```

**Comment by bartdesmet** [comment]
For the first two, I'm wondering whether we're running with older bits? This error was seen [here](https://dotnetjobresults.blob.core.windows.net/build-2d70131ea31f43da8a9aeedc8779543c//8da09671-6cb7-4328-b7bf-9d17338c0cfd/System.Linq.Queryable.Tests/testResults.xml?sv=2015-04-05&sr=c&sig=%2BZehEZi0mW8jhXnbGjerkNznQ72fBjb8J7hyTHt1ueo%3D&st=2016-09-01T14%3A53%3A28.0473114Z&se=2016-10-01T14%3A53%3A28.0473114Z&sp=r) for test that ran today on 9/1/2016. However, the exception looks like coming from the interpreter at `CompileUnaryExpression` where we added the case for `UnaryPlus` about a year ago in https://github.com/dotnet/corefx/commit/0948bcda709eaedff6a243bfe86cc8dd66ae752a.

**Comment by VSadov** [comment]
Yes, looks like a failure from very old bits. UnaryPlus is certainly supported.
One theory is that the test infrastructure does not know that we are testing Linq libraries themselves and pulls them from some kind of cache. 
If that is a case, perhaps there is a flag to suppress such behavior?

**Comment by VSadov** [comment]
Seems like a test issue where we AOT tests are running with ancient bits.   (UnaryPlaus is certainly implemented)

@bartdesmet  Do we need to keep this test around? Is it here to track the test issue in general?
