### ISSUE TITLE
ArgumentNullException contains an error message differently on windows and MacOS environment

### ISSUE THREAD

**Issue by mayconbeserra** [dotnet/corefx#11344]
Hi there, 

It seems the ArgumentNullException message is being thrown differently on Windows and MacOS.

To be honest, I don't know what it is correct, but it would be nice to have a standard.

**Environments:** 

Windows 10
MacOS: 10.11.6
.NET Core: 1.0.0-preview2-003121

**Steps of reproducing:**

1. Create a class;
2. Add a collection property;
3. Create a test;
4. Call "entity.Collection.Any()";

**Actual Result:**
Value cannot be null.\nParameter name: source

**Expected Result:**

The Argument Null Exception message should be the same as we have in a Windows environment.

Value cannot be null.\r\nParameter name: source

![argumentnullexception_output_screen](https://cloud.githubusercontent.com/assets/911493/18176458/0163f91e-7076-11e6-87f1-13c7327b0239.png)
![tests](https://cloud.githubusercontent.com/assets/911493/18176459/017ae17e-7076-11e6-8980-51d011d71a82.png)

**Comment by stephentoub** [comment]
It's the same message.  The message just has a  newline in it, and newlines are different on Windows and Unix, "\r\n" on the former and "\n" on the latter.
