### ISSUE TITLE
Re-enable more networking tests for innerloop

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#11345]
PR #11341 moved the majority of networking tests to outerloop due to infrastructure issues. This issue will track putting back tests as we strengthen the test infrastructure to allow more networking tests to run as innerloop.

**Comment by davidsh** [comment]
Tracking networking test reliability with #14519.

**Comment by ViktorHofer** [comment]
FtpWebRequestTests test class has plenty of methods which run on Outerloop and have a comment which pointed me here. Is this still an issue or should we try removing the Outerloop?

**Comment by davidsh** [comment]
Pls leave Outerloop as-is.  In general, networking tests which access a remote endpoint or even loopback still need to be outerloop for now.

**Comment by davidsh** [comment]
This issue probably shouldn't be marked 2.0 though.

@karelz Why is this issue 2.0?  At this point, we are not ready yet to move all networking tests to inner loop.

**Comment by davidsh** [comment]
>@karelz Why is this issue 2.0? At this point, we are not ready yet to move all networking tests to inner loop.

Oh. Never mind. I see that this issue is closed.  So, no action required.  Thx.

**Comment by karelz** [comment]
BTW: I set milestones on issues which are closed, so that it is easy to find out when they were fixed / resolved as won't fix, etc.
