### ISSUE TITLE
Failure in System.Collections.Specialized.Tests.GetItemObjTests in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1136]
MESSAGE:
Error, returned wrong item for lowercase key
+++++++++++++++++++
STACK TRACE:
at System.Collections.Specialized.Tests.GetItemObjTests.Test01() in d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Collections.Specialized\tests\HybridDictionary\GetItemObjTests.cs:line 362

**Comment by ianhays** [comment]
Oh man these tests are a nightmare. So I've narrowed down the problem here a bit and added a specific unit test for it.Adding to the HybridDictionary and then immediately getting from that HybridDictionary fails very rarely, so I added a loop around the part that is failing.

Adding "ItemX" (where X is the current iteration) and then getting that value returns some weird strings. The returned values have first 'i' characters with hex values of either 0x131 or 0x69. There doesn't seem to be any pattern or consistency in which indexes fail and which pass.

The test:
```
public const int MAX_LEN = 50;          // max length of random strings
private const int BIG_LENGTH = 100;

[Fact]
public void GetItem_CaseInsensitiveHD_HashTable()
{
    for (int p = 0; p < 10000; p++)
    {
        string[] valuesLong = new string[BIG_LENGTH];
        string[] keysLong = new string[BIG_LENGTH];

        for (int i = 0; i < BIG_LENGTH; i++)
        {
            valuesLong[i] = "Item" + i;
            keysLong[i] = "keY" + i;
        }

        HybridDictionary hd = new HybridDictionary(true);
        hd.Clear();
        for (int i = 0; i < valuesLong.Length; i++)
        {
            hd.Add(keysLong[i].ToLower(), valuesLong[i].ToLower());
            Assert.Equal(hd[keysLong[i].ToLower()], valuesLong[i].ToLower());
        }
    }
}
```

**Comment by ianhays** [comment]
I refactored the test further and can no longer replicate the bug.

New structure:
```
        private string[] TestValues(int length)
        {
            if (length == 5)
                return new string[]
               {
                    "",
                    " ",
                    "$%^#",
                    System.DateTime.Today.ToString(),
                    Int32.MaxValue.ToString()
                };

            string[] values = new string[length];
            for (int i = 0; i < length; i++)
                values[i] = "Item" + i;
            return values;
        }

        private string[] TestKeys(int length)
        {
            if (length == 5)
                return new string[]
                {
                    Int32.MaxValue.ToString(),
                    " ",
                    System.DateTime.Today.ToString(),
                    "",
                    "$%^#"
                };

            string[] keys = new string[length];
            for (int i = 0; i < length; i++)
                keys[i] = "keY" + i;
            return keys;
        }

        [Theory]
        [InlineData(5)]
        [InlineData(50)]
        [InlineData(100)]
        public void Add(int size)
        {
            for (int p = 0; p < 10000; p++)
            {
                string[] values = TestValues(size);
                string[] keys = TestKeys(size);

                HybridDictionary hd = new HybridDictionary(true);
                hd.Clear();
                for (int i = 0; i < size; i++)
                {
                    hd.Add(keys[i].ToLower(), values[i].ToLower());
                    Assert.Equal(hd[keys[i].ToLower()], values[i].ToLower());
                }
            }
        }

```

**Comment by stephentoub** [comment]
> The returned values have first 'i' characters with hex values of either 0x131 or 0x69. 

Those values make it seem like something might be going on with a Turkish culture (https://github.com/dotnet/coreclr/blob/master/src/corefx/System.Globalization.Native/casing.cpp). Is it possible some other test is somehow interfering with this one, something running concurrently, something leaving a culture set on the thread, etc.?

**Comment by ianhays** [comment]
Yeah and that would explain why I can't replicate the error: I turned off the big all-in-one test and started just running my Theory. I'll re-enable it and see what happens. The tests could really use a refurb so I may just do that while I'm at it.

**Comment by ianhays** [comment]
Good call. There are two tests that set the DefaultThreadCurrentCulture to Turkish. Pushing a fix now
