### ISSUE TITLE
.nuspec for System.Linq.Expressions has weird description

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#11361]
Nit, but the `<description>` tag has some commonly used types in there:
```
Commonly Used Types:
System.Linq.Expressions.Expression&lt;TDelegate&gt;
System.Linq.Expressions.Expression
System.Linq.Expressions.MemberExpression
System.Linq.Expressions.ExpressionVisitor
System.Linq.Expressions.MethodCallExpression
System.Linq.IQueryable&lt;T&gt;
System.Linq.IQueryable
System.Linq.Expressions.NewExpression
System.Linq.Expressions.ParameterExpression
System.Linq.Expressions.ConstantExpression
```
It seems the listing of *some* specific subtypes of `Expression` is a bit strange; users who leverage expression trees other than through compiler support are likely very well-aware of the plethora of subtypes. If we want to specify "commonly used types" here, I think a good more concise set of types would be:
```
System.Linq.IQueryable&lt;T&gt;
System.Linq.IQueryable
System.Linq.Expressions.Expression&lt;TDelegate&gt;
System.Linq.Expressions.Expression
System.Linq.Expressions.ExpressionVisitor
```
in the order of likelihood of users having seen them.

**Comment by weshaggard** [comment]
@bartdesmet feel free to submit a PR with the updated description.
