### ISSUE TITLE
FileStream needs overrides of Begin/EndXx

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#11373]
@JeremyKuhne, I just noticed that #10697 didn't actually add Begin/End overrides to FileStream... it added them to FileStreamBase.  FileStreamBase isn't the base type of FileStream, but rather the base for the inner per-platform streams it wraps.  That means that if someone calls FileStream.Begin/EndXx now, they're getting the base Stream's implementation, not FileStream's, and that's going to do the wrong thing in the case where the FileStream was constructed in async mode.

**Comment by JeremyKuhne** [comment]
Thanks- I'll get it.

**Comment by stephentoub** [comment]
@JeremyKuhne, why was this closed?  Was it fixed and I missed it?

**Comment by JeremyKuhne** [comment]
@stephentoub Mistake when moving stuff around zenhub boards

**Comment by ianhays** [comment]
resolved by @JeremyKuhne in https://github.com/dotnet/corefx/pull/11999
