### ISSUE TITLE
Implement AssemblyLoadContext.GetAllAssemblies

### ISSUE THREAD

**Issue by rahku** [dotnet/corefx#11371]

**Comment by AlexGhiondea** [comment]
@gkhanna79 @rahku is this something we are still planning to get in for 1.2?

**Comment by gkhanna79** [comment]
I believe this is complete (see https://github.com/dotnet/corefx/blob/277b781b6326e06716173132f68317ddc475f67d/src/System.Runtime.Extensions/src/System/AppDomain.cs#L234).

**Comment by AlexGhiondea** [comment]
@gkhanna79 I saw that, but that is about calling `GetLoadedAssemblies` where this issue is about `GetAllAssemblies`.

Maybe we are talking about the same thing and just the title of the issue needs to be updated?

**Comment by gkhanna79** [comment]
IIRC, @rahku likely named it differently but the goal was to have an API that allows one to enumerate the loaded assemblies, which is what `GetLoadAssemblies` does.

**Comment by AlexGhiondea** [comment]
@gkhanna79 in that case we are done with this issue! 😄
