### ISSUE TITLE
System.IO.Pipes tests are not running

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1139]
Doing ```msbuild /t:BuildAndTest``` from the System.IO.Pipes directory builds but does not run the tests.  And the output from the full CI runs shows the same: the tests are getting built but not executed.

**Comment by weshaggard** [comment]
They don't match the naming pattern convention of ending with ".Tests". Test projects only run if IsTestProject=true which is set to true if the project name ends with ".Tests" or that property is set explicitly in the project.

**Comment by stephentoub** [comment]
Sounds like something that should be fixed :smile:
