### ISSUE TITLE
A generic API for string-like objects

### ISSUE THREAD

**Issue by int19h** [dotnet/corefx#11391]
.NET is missing a convenient way to define a method that can take something "string-like" with minimal overhead. Most existing APIs just take `String`, meaning that callers need to call `ToString`, often creating full copies that are then used only to look at a few characters at the beginning. Some types that are commonly affected by this are `StringBuilder` and `Uri`.

This could be solved by adopting a common interface like `IString` for all these types, which could offer the same operations that `String` does; and implementing that interface on all standard types that have string as a public representation of any valid value. 

The closest existing equivalent is Java `CharSequence`.

**Comment by KrzysztofCwalina** [comment]
I am not a big fan of string abstraction (or in general abstractions for language primitives). Abstractions add complexity and performance overhead that often cannot be afforded int he very primitive types. 

But I do agree that there is a problem with ToString allocations. Take a look at https://github.com/dotnet/corefxlab/wiki/System.Text.Formatting for how we are exploring to fix that.

**Comment by AlexGhiondea** [comment]
I agree with @KrzysztofCwalina - I am not convinced we need the `IString` abstraction. 

The allocations that `StringBuilder` incurs should be solved by the new `StringFormatter` class.

Feel free to reopen if you have other scenarios where this would be useful.
