### ISSUE TITLE
System.ServiceProcess.ServiceController tests are not running

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1140]
As with #1139, the tests for System.ServiceProcess.ServiceController are building but not running, both in the lab and locally.

**Comment by weshaggard** [comment]
Those tests are explicitly disabled in the project:
    
    <RunTestsForProject>False</RunTestsForProject>

**Comment by stephentoub** [comment]
Ah, I missed the ```<RunTestsForProject>False</RunTestsForProject>```.  Will we be doing code coverage as part of running outer loop tests?  Or alternatively what's the plan for enabling code coverage of the library?

**Comment by weshaggard** [comment]
I'm not sure we have any particular plans yet. Right now we don't even have support for running these tests that require admin access as part of OuterLoop yet either.
