### ISSUE TITLE
Expression.ToString quirk with Power and ExclusiveOr

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#11415]
Nit, but both use the infix `^` symbol to print expressions. Note that `PowerAssign` uses `**=`, so it'd be logical for `Power` to use `**`. However, this has shipped like this since 4.0, so it'd be a breaking change to change.

Maybe the better thing to do here is to ship a proper (and extensible by `Extension` nodes) pretty printer for expressions, like I started doing over at https://github.com/bartdesmet/ExpressionFutures. Neither `ToString` nor `DebugView` are great today. The former has quirks and makes some nodes indistinguishable (besides the ones listed here, also the `Checked` variants have no syntactic presence) or uses weird operator names (some C#, some VB mixed in there); the latter stops recursion at certain nodes (such as `Try` and `Block`) and omits useful information (such as reflection info, or instance IDs for nodes that are matched by reference equality, such as `Label` and `Parameter`).

**Comment by bartdesmet** [comment]
Cool; there's definitely a lot of overlap, so we should figure out what can be absorbed. I'll add it to the list of things in this area to track. Thanks!

**Comment by VSadov** [comment]
Let's change to "**"

**Comment by bartdesmet** [comment]
Sounds good, will submit PR shortly.

**Comment by JonHanna** [comment]
Are changes to this generally considered breaking?

It seems to me this would be more consistent and less misleading (`&&=` suggests short-circuiting) if we did:

```
-    case ExpressionType.AndAlso:               op = "AndAlso";                   break;
-    case ExpressionType.OrElse:                op = "OrElse";                    break;
+    case ExpressionType.AndAlso:               op = "&&";                        break;
+    case ExpressionType.OrElse:                op = "||";                        break;

-    case ExpressionType.And:                   op = IsBool(node) ? "And" : "&";  break;
-    case ExpressionType.AndAssign:             op = IsBool(node) ? "&&=" : "&="; break;
-    case ExpressionType.Or:                    op = IsBool(node) ? "Or"  : "|";  break;
-    case ExpressionType.OrAssign:              op = IsBool(node) ? "||=" : "|="; break;
+    case ExpressionType.And:                   op = "&";                         break;
+    case ExpressionType.AndAssign:             op = "&=";                        break;
+    case ExpressionType.Or:                    op = "|";                         break;
+    case ExpressionType.OrAssign:              op = "|=";                        break;
```

But it's likely not worth causing a break if it would.
