### ISSUE TITLE
ReadOnlyCollectionBuilder<T> included in System.Linq.Expressions but not used

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#11414]
Shows up as dead code when analyzing code coverage as part of #11409. It's included from the `Common` folder and shared with `System.Dynamic.Runtime`. The only reference occurs in `ToReadOnly` in `CollectionExtensions` for a type check.

If this type is not shared in / referenced from a single assembly and two copies exist, the type check will never pass if the object is passed across assembly boundaries, thus breaking the no-cloning optimization for the collection. This is done in e.g. `ReferenceArgAssign` in `System.Dynamic.Runtime`:

``` csharp
private static Expression ReferenceArgAssign(Expression callArgs, Expression[] args)
{
    ReadOnlyCollectionBuilder<Expression> block = null;

    // omitted a bunch of code that will assign `block`

    if (block != null)
        return Expression.Block(block);
    else
        return Expression.Empty();
}
```

The `Block` factory method calls into `ToReadOnly` but the `as` check for `ReadOnlyCollectionBuilder<T>` won't pass due to the copy of the type existing in the two assemblies. Passing the result of calling `ToReadOnly` to the factory method here won't help either, because the same cloning of code applies to `TrueReadOnlyCollection<T>`, which is also checked for in `ToReadOnly` to avoid copying of the collection.

It seems that the right thing to do here is to keep one copy of the code in one assembly. Given that `System.Dynamic.Runtime` has a strong (by design) dependency on `System.Linq.Expressions`, the latter would be the best place to store these types. We'd need to have access to these types across assembly boundaries and likely don't want to make them public (though they may provide value to others, *) so `InternalsVisibleTo` is lurking around the corner. There's very little precedent for this on the `corefx` repo though, with the exception of some stuff in `System.Reflection` assemblies (besides for testing purposes).

If we decide that `InternalsVisibleTo` is appropriate here (@stephentoub, @VSadov), we can also de-duplicate the code for `ExpressionUtils` etc.

(*) The types that need to be accessed across assembly boundaries are:
- `System.Runtime.CompilerServices.ReadOnlyCollectionBuilder<T>` which implements `IList<T>`
- `System.Dynamic.Utils.CollectionExtensions` for its `ToReadOnly<T>` extension method

Note that we _shouldn't_ expose `TrueReadOnlyCollection<T>` publicly because only `ToReadOnly<T>` should be able to instantiate it and type check for it (in order to guarantee the "True" part). Luckily, most occurrences of this type occur in`System.Linq.Expressions`, with the exception of a shared `ExpressionUtils.ValidateArgumentTypes` method which is used across boundaries (but the chance of hitting the code path that instantiates the collection here is extremely unlikely; it requires a delegate whose `Invoke` method has an `Expression<>` type that requires quoting, causing a rewrite of the argument expression to introduce a `Quote` around it).

Still, it'd likely be better not to expose these types, and consider `InternalsVisibleTo` or keep the code duplication (and the adverse effects such as unnecessary cloning of collections).

**Comment by stephentoub** [comment]
I previously started addressing this in the dev/api branch:
https://github.com/dotnet/corefx/commit/c38eff56fa84a5cfb70ea475a2945b464f234319
If memory serves, the remaining piece of work is just to address the TODO I left there to update the line in the .csproj.

**Comment by bartdesmet** [comment]
Cool! There will be some follow-up work as far as I can tell. In particular, `TrueReadOnlyCollection<T>` is still cloned in both assemblies, and `System.Dynamic.Runtime` instantiates this type in several places:
* `DynamicMetaObjectBinder`
* `CallSite`
* `CallSiteBinder`
It passes the resulting collection to expression factories, which will call `ToReadOnly`, which on its turn will type check the collection against its copy of `TROC<T>`. The check will never pass, and the collection will be cloned.

One option would be to use the builder (living in `System.Linq.Expression.dll`) to construct the `TROC<T>` (and get rid of the copy of the type). It'd still add the allocation of the builder though, but will get rid of the cloning on the receiving end. Another option is to have cross-assembly visibility as discussed above.

**Comment by VSadov** [comment]
@bartdesmet  - is this still relevant after https://github.com/dotnet/corefx/pull/13194 ?

**Comment by bartdesmet** [comment]
Can be closed.
