### ISSUE TITLE
Proposal: Adding a way to convert Span to ReadOnlySpan

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#11450]
Pardon me if this is implemented and I simply overlooked it, but it appears to me there is no API yet to convert from a `Span<T>` to a `ReadOnlySpan<T>` in either coreclr/corefxlab, which means that people who have one of the former and want to pass it to a function accepting the latter will have to create a copy.

We should add an API (either an instance method `AsReadOnly`, or an implicit operator) for converting a Span to a ReadOnlySpan so people don't have to copy any data.

cc @jkotas, @KrzysztofCwalina

**Comment by benaadams** [comment]
Is an [implicit conversion in the corefxlabs version](https://github.com/dotnet/corefxlab/blob/master/src/System.Slices/System/ReadOnlySpan.cs#L136-L139)

**Comment by benaadams** [comment]
Looks like it is catered for https://github.com/dotnet/coreclr/issues/5857#issuecomment-243267066

**Comment by jamesqo** [comment]
Ah, ok. I was looking in `Span` for the operator. Looks like this can be closed then.
