### ISSUE TITLE
HttpClient throws an exception if the WWW-Authenticate header is missing

### ISSUE THREAD

**Issue by droyad** [dotnet/corefx#11456]
If the server returns a 401 response but does not supply a `WWW-Authenticate` header (in contravention to the RFC requirement), and exception is thrown just as in #11452, and this could be a special case of an unknown scheme.

HttpClient on .NET Framework does handle this scenario but returning the 401 to the caller, so I suggest the .NET Core implementation also handles it despite the server doing the wrong thing.

**Comment by davidsh** [comment]
Fixed with PR #11481.
