### ISSUE TITLE
Enumerable.Average should avoid divisions for length 1 collections

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#11457]
Floating point divisions, which occur whenever the / or % operators are used, have a very high latency compared to other instructions. For example in the instruction tables [here](http://www.agner.org/optimize/instruction_tables.pdf) you can see `fdiv(r)(p)` consistently have above-average latencies, reaching as much as 71 cycles for Atom processors (though they're more toned down for newer Intel processors). In [`Enumerable.Average`](https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Average.cs#L36) it's used even when the collection's length is 1; instead of doing that, we could just return the first item to avoid the expensive operation.

**Comment by VSadov** [comment]
This seems a micro optimization for a case that does not seem to be a likely bottleneck.

Considering that this is a trade of a division that we can skip in some cases for a branch that we should take always, it is unclear whether it is going to be profitable.
