### ISSUE TITLE
Move master to netcoreapp1.2

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#11468]
move everything in master from netcoreapp1.1 to netcoreapp1.2, because netcoreap1.1 is shipping earlier

**Comment by JeremyKuhne** [comment]
Need to enable multitargetting tests against 1.7 and 1.2- a partial solution is part of #11689. Updates to tests.targets and other common targets need to be made to allow TestTFM not to collide when used against different TargetGroups.

**Comment by danmosemsft** [comment]
This is done. @joperezr
