### ISSUE TITLE
CookieContainer.Add(Cookie cookie)

### ISSUE THREAD

**Issue by aliveli186** [dotnet/corefx#11464]
CookieContainer.Add(Cookie cookie) method is no longer accessible because it's accessibility was downgraded which causes incompatibility between other .net versions.
Is this intended or a mistake?

Other definitions (net461):
public void Add(Cookie cookie)

Existing definition (netstandard1.6):
internal void Add(Cookie cookie)

**Comment by davidsh** [comment]
>CookieContainer.Add(Cookie cookie) method is no longer accessible because it's accessibility was downgraded which causes incompatibility between other .net versions.

This API is present as a public API in the .NET Framework 4.x (Desktop).  It was "downgraded" (removed) as part of the original Windows Store .NET Profile that was introduced in Windows 8.0/8.1 timeframe. That trimmed down API surface was the basis for .NET Core 1.0.

We are working on adding back API surface for a future .NET Core release. This particular API will be among those that gets added back as a public API again.

**Comment by karelz** [comment]
@ericeil is it part of #12125?

**Comment by ericeil** [comment]
Yes, this is part of #12125.
