### ISSUE TITLE
File version of DataFlow assembly changed from 4.6 to 1.0 in latest release on NuGet

### ISSUE THREAD

**Issue by appel1** [dotnet/corefx#11462]
DataFlow 4.5.25 on NuGet has file version 4.6.23123.0 and DataFlow 4.6.0 has file version 1.0.24212.1. This breaks deployment using Windows Installer. Only files with a higher file version are replaced during upgrades. 

https://www.nuget.org/packages/System.Threading.Tasks.Dataflow/

**Comment by ericstj** [comment]
This was fixed with https://github.com/dotnet/corefx/pull/10306.  I've confirmed that fix is in 1.1.
