### ISSUE TITLE
More optimizations for LINQ methods

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#11467]
I've been raising a lot of issues about LINQ recently, so this is sort of an umbrella issue for all of the optimizations I think could be applied.
- `Enumerable.Cast` is one of those functions that has a 1:1 mapping, so it should forego `yield` and instead implement a custom iterator class. Things like `x.Cast<Customer>().ToArray()` are very common.
- In `OfType`, if `TResult` is object or the source enumerable is of type `IEnumerable<TResult>` *, we know that each is check will return true and therefore we will have a 1:1 mapping. We can forward to `CastIterator` for those cases and get special treatment for `ToArray`, `ToList`, etc.

\* I don't know how often this optimization will happen. Though it will incur no runtime cost since `typeof(T) == typeof(U)` is jitted away, it's not very common for someone to call `OfType<T>()` on something they _know_ is an `IEnumerable<T>`. The only places where I think it can happen are if they accept an `IEnumerable` and use `OfType` to convert it to a generic one, or their method has multiple type parameters and they want to convert an `IEnumerable<U>` to an `IEnumerable<T>` and someone calls their method with `Method<int, int>()`.
# 
- `Enumerable.Concat(...).ToArray()` is wasteful since it does not attempt to specialize if the underlying enumerables are `ICollections`. It should instead call `GetEnumerable` on everything, and then specialize for `ICollection`. (potentially `IIListProvider` as well if #11455 is implemented)
- It may be possible for the `Concat` iterators to implement certain `IPartition` methods as well. If the first/last collections are ILists/IPartitions, then `TryGetFirst` and `TryGetLast` could be implemented with relatively minimal overhead. (actually not in the case where you have a very long linked list of `Concat` iterators and you try to get the first item, but in that case calling `First()` would still be very slow anyway.)
# 
- [`LongCount`](https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Count.cs#L79) is not optimized for ICollection/IIListProvider?
# 
- `DefaultIfEmpty` should just return a cached iterator if the enumerable is empty. We should also introduce something like a `WrapperIterator<T>` class that just provides a view over an enumerable, and use that for the other case. I'm sure it could be useful in many other LINQ methods (for example, possibly `Skip(0)`).

**Comment by jamesqo** [comment]
I'm going to make this an umbrella issue for all further optimizations for LINQ, since I realize I've been raising a lot of those lately :)

**Comment by stephentoub** [comment]
With any query processing system, there are potentially an infinite number of optimizations that can be introduced to special case this or that pattern.  Each of those optimizations adds code and complexity.  Our goal should be to optimize the important ones, based on real use cases, as all such optimizations add cost for every other use, even if it's just in increased binary size, increased JIT time, etc., plus the on-going maintenance costs associated with the code for the additional special-casing.

**Comment by VSadov** [comment]
This does not seem to provide a unified issue or a strategy. I think the separate enhansements would be better served via entering individual issues.

**Comment by jamesqo** [comment]
@VSadov, yes. Sorry, I had forgotten to close this issue earlier. Also, I've learned that some of the statements here are incorrect, e.g. we cannot just return a cached iterator in `DefaultIfEmpty` because of lazy eval.
