### ISSUE TITLE
DefaultValueAttribute missing unsigned int / unsigned long constructor

### ISSUE THREAD

**Issue by jairbubbles** [dotnet/corefx#11465]
### Rationale and Usage

As has already been explained, using `DefaultValueAttribute` with one of the problematic types (unsigned integer types and `sbyte`) in C# ends up using a widening conversion and so the boxed `Value` ends up with an unexpected type. The proposal is to add constructor overloads so that the conversions don't happen and `Value` gets the expected type.

The usage stays the same as before, e.g. `[DefaultValue(UInt64.MaxValue)]`.

Doing this would be technically a source breaking change, since recompiling existing code would end up with a different type for the boxed `Value`. (Arguably, it would be a better type, but that doesn't change the fact that someone could rely on the old behavior.)

### Proposed API

```c#
public class DefaultValueAttribute : Attribute
{
    // existing constructor overloads:
    public DefaultValueAttribute(Type type, string value);
    public DefaultValueAttribute(char value);
    public DefaultValueAttribute(byte value);
    public DefaultValueAttribute(short value);
    public DefaultValueAttribute(int value);
    public DefaultValueAttribute(long value);
    public DefaultValueAttribute(float value);
    public DefaultValueAttribute(double value);
    public DefaultValueAttribute(bool value);
    public DefaultValueAttribute(string value);
    public DefaultValueAttribute(object value);

    // added constructor overloads:
    public DefaultValueAttribute(sbyte value);
    public DefaultValueAttribute(ushort value);
    public DefaultValueAttribute(uint value);
    public DefaultValueAttribute(ulong value);
}
```

## Original proposal

Most numeric types have their constructor but not the unsigned ones.

As a result, if you write that code:
`new DefaultValueAttribute(UInt64.MaxValue);`

The float constructor will be called as the compiler seems to avoid the constructor that needs boxing.

Removing all explicit constructor that takes numeric types solve the issue.

They all points to the same code that will box the value anyway:

```
/// <devdoc>
/// <para>Initializes a new instance of the <see cref='System.ComponentModel.DefaultValueAttribute'/> class using a Unicode
///    character.</para>
/// </devdoc>
public DefaultValueAttribute(char value) {
    this.value = value;
}
```

**Comment by AlexGhiondea** [comment]
I believe this has been resolved [now](https://github.com/dotnet/corefx/blob/9d0736e2abcfe7c82309cf33a57267a5e33fc8c9/src/System.Runtime/src/System/ComponentModel/DefaultValueAttribute.cs#L94)

**Comment by jairbubbles** [comment]
Not sure to see what has changed :-(

**Comment by AlexGhiondea** [comment]
Ah -- I misread the title. You are asking for unsigned int/ unsigned long overloads for the constructor.

**Comment by AlexGhiondea** [comment]
In that case we would need a formal API review for this.

**Comment by jairbubbles** [comment]
Yes I can sum it up with:
```csharp
bool uint64isafloat = new DefaultValueAttribute(UInt64.MaxValue).Value is float;
```
I don't think most people will think this is true.

As a side note, I don't understand why there are so many overload as they all box the value the same way. Why not keeping only `public DefaultValueAttribute(object value)` ?

**Comment by AlexGhiondea** [comment]
@jairbubbles not sure -- but at this point I am not sure we can do anything about it. We could change it to be generic, but if we want to keep the existing signature, you will still box when you are returning the value from the Value property (returning an object).

**Comment by svick** [comment]
@AlexGhiondea 

> We could change it to be generic

How? C# does not support generic attributes (https://github.com/dotnet/roslyn/issues/953) (or generic constructors, if that's what you meant).

I think adding overloads to the constructor for the types that cause confusing conversions is the right solution here.

**Comment by svick** [comment]
My API proposal speclet:

## Rationale and Usage

As has already been explained, using `DefaultValueAttribute` with one of the problematic types (unsigned integer types and `sbyte`) in C# ends up using a widening conversion and so the boxed `Value` ends up with an unexpected type. The proposal is to add constructor overloads so that the conversions don't happen and `Value` gets the expected type.

The usage stays the same as before, e.g. `[DefaultValue(UInt64.MaxValue)]`.

Doing this would be technically a source breaking change, since recompiling existing code would end up with a different type for the boxed `Value`. (Arguably, it would be a better type, but that doesn't change the fact that someone could rely on the old behavior.)

## Proposed API

```c#
public class DefaultValueAttribute : Attribute
{
    // existing constructor overloads:
    public DefaultValueAttribute(Type type, string value);
    public DefaultValueAttribute(char value);
    public DefaultValueAttribute(byte value);
    public DefaultValueAttribute(short value);
    public DefaultValueAttribute(int value);
    public DefaultValueAttribute(long value);
    public DefaultValueAttribute(float value);
    public DefaultValueAttribute(double value);
    public DefaultValueAttribute(bool value);
    public DefaultValueAttribute(string value);
    public DefaultValueAttribute(object value);

    // added constructor overloads:
    public DefaultValueAttribute(sbyte value);
    public DefaultValueAttribute(ushort value);
    public DefaultValueAttribute(uint value);
    public DefaultValueAttribute(ulong value);
}

**Comment by AlexGhiondea** [comment]
@svick thanks for the proposal. I have marked this as ready for review.

I missed the fact that the attribute cannot be generic. What we are getting with this change is that you will never get a widening conversion, meaning you will correctly be able to round-trip values with this attribute.

**Comment by jairbubbles** [comment]
@svick Thank you, this is very well summarized !
In our code base we defined our own DefaultValueAtribute in our namespace which inherits from DefaultValueAttribute to work around the issue. So I guess it will break compilation but it's a good feedback to tell us to remove the class :-D

**Comment by karelz** [comment]
API review: Approved.

BTW: I have updated @svick's spec on the top most post.

**Comment by AlexRadch** [comment]
@karelz I am working on PR for this.

**Comment by AlexRadch** [comment]
@karelz  Issue can be closed I think.

**Comment by karelz** [comment]
@AlexRadch in future, please include in your PR keywords for closing the issue: https://help.github.com/articles/closing-issues-via-commit-messages/
