### ISSUE TITLE
Merge dev/api into master

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#11469]
Check this first
* are there any tests disabled in dev/api that are not disabled in master. re-enable these or open an issue.
* check packages don't have broken dependencies, 
* check packages where the contract exists but the implementation is not complete yet because we are either using stubs or even worse we just have a apicompat baseline but the members don’t even exist in the implementation.

**Comment by danmosemsft** [comment]
Probably want to have the 1.1 branch first.

**Comment by joperezr** [comment]
Already made the big merge once. There are still a few PRs open against dev/api, so I'll wait for those to merge and then I'll do one last merge from dev/api to master and close dev/api.
PRs that are still open against dev/api are:
- [ ] #11526 by @JeremyKuhne 
- [ ] #11511 by @huanwu 
- [ ] #11490 by @JeremyKuhne
