### ISSUE TITLE
Rewrite benchmarksgame samples to optimize performance

### ISSUE THREAD

**Issue by Peperud** [dotnet/corefx#11473]
I realize this not just .NET Core issue. Or perhaps not perceived as an issue at all. 
But since a lot of work is done to improve performance...
The Java binary-trees program in the computer language benchmark game is almost 4 times faster than the C# .NET Core one. Even worst for the regex-dna test, though perhaps this is more of a regex library test. I'm not taking the benchmark game for something more than it is, but the difference gap is quite large here, perhaps something can be done...
[http://benchmarksgame.alioth.debian.org/u64q/performance.php?test=binarytrees](http://benchmarksgame.alioth.debian.org/u64q/performance.php?test=binarytrees)
[http://benchmarksgame.alioth.debian.org/u64q/performance.php?test=regexdna](http://benchmarksgame.alioth.debian.org/u64q/performance.php?test=regexdna)
-- fixed bad links

**Comment by whoisj** [comment]
@Peperud both links results in a 404 for me, please validate the links.

**Comment by benaadams** [comment]
Links work if copy pasted, have github.com/url -> 404 if followed directly

**Comment by Petermarcu** [comment]
@Peperud , this is definitely something that is interesting to look at. We've looked that these issues before, sometime better tuning in the C# code submitted for the test case gets the numbers better and sometimes it is something that needs to be fixed in the core implementation. Are you or anyone else interested in looking deeper at where the time is being spent and make a proposal for how to address it?

**Comment by svick** [comment]
What is suspicious is that there is a F# version (running on mono LLVM) that is significantly faster than any C# version (running on mono or .Net Core).

**Comment by stephentoub** [comment]
Quick perusal suggests the tests aren't doing the same thing between the C# and Java versions.  But even if they were apples-to-apples, configuration makes a big difference.  When I run the C# version with the server GC instead of the client GC, it runs 4x faster.

**Comment by mellinoe** [comment]
All of the top submissions for the binary tree game are using some sort of arena allocator or memory pool. Many of the top implementations use this [Apache memory pool](http://apr.apache.org/docs/apr/1.5/group__apr__pools.html). It's unlikely we could get a top score unless we did the same, I think. An easy way to improve the score would be to just PInvoke to the Apache library and see how much faster we get. At the very least, we need some sort of memory pool to be competitive.

Note that the rules for the game say you aren't allowed implement your own arena allocator or memory pool, but all of the top submissions are using one. Apparently it is okay as long as the code for that is external to your game submission. :confused:

**Comment by SunnyWar** [comment]
I suspect the binary tree code is spending most of it's time in the GC. To test this, I grabbed the c# and did a quick check. On my machine the average time was just over 15s. When I switched to the server GC the time was 6-7s.

**Comment by Peperud** [comment]
@mellinoe Not looking at any other naively compiled, not garbage collected languages. Java is the target to beat.
@stephentoub the Java and C# versions are pretty much the same (or at least were before I "polluted" the C# with naive attempt to add concurrency). 
But you're absolutely right about the server GC - it does make a huge difference.

**Comment by danmosemsft** [comment]
@brianrob @mellinoe I know we care about this -- what are we doing here if anything?
I've moved to future since I'm not aware that it's required for 2.0.

**Comment by mellinoe** [comment]
> I know we care about this -- what are we doing here if anything?

Should we care about this, given what I described above? We can certainly do lots of things to improve the score, but the best ways to do that would not have a measurably positive effect on the product itself, only the game submission.

**Comment by danmosemsft** [comment]
I see it being actively used in CoreCLR:
https://github.com/dotnet/coreclr/tree/master/tests/src/JIT/Performance/CodeQuality/BenchmarksGame

@valenis @brianrob @AndyAyersMS ?

**Comment by brianrob** [comment]
We're using it as a codegen benchmark in coreclr, which I see as something different than wanting to re-write the C# code.  I'm not actually clear of the benefit of re-writing this vs. using it as a benchmark to improve the runtime and JIT.  As @mellinoe points out, re-writing the test doesn't affect the product.  Is there another benefit to having an optimized version, or one that uses particular features that we want to track/optimize the performance of?

**Comment by AndyAyersMS** [comment]
There is some merit in ensuring that there are well-crafted versions of these tests available to show that one does not have to resort to crazy contortions to get competitive performance with .Net. 

To the extent that .Net falls short of that and lags other implementations there might be something to be learned.

But it's not clear to me that this sort of work belongs in CoreFx or in CoreCLR.

On the CoreCLR side we are using selected versions of the benchmark games tests more-or-less as-is to ensure the jit behavior is reasonable and does not regress.

**Comment by benaadams** [comment]
>  re-writing the test doesn't affect the product.

Like TechEmpower the results are often referred to; so it might not effect the product (unless discovery is made along the way); but it may effect the product use/adoption. You need "Marketing Perf Coders" 😉

**Comment by benaadams** [comment]
Also some of the implementations are really bad; or don't use features. Like the Mandelbrot test doesn't use Vectors; the Parallel tests have clear contention and should probably use Parallel with local var rather than dedicated created threads etc

**Comment by benaadams** [comment]
Forked to https://github.com/benaadams/BenchmarksGame as isn't really coreclr/fx

**Comment by Petermarcu** [comment]
@benaadams , I think this is great. We should see how good we can make it using the latest tools in our toolbox. Thanks for taking the lead!

**Comment by Petermarcu** [comment]
BTW, corefxlab may also be a fine home for this type of experiment and would align with other efforts going on there.

**Comment by brianrob** [comment]
@AndyAyersMS @benaadams makes sense to me.  @benaadams thanks for taking a stab at this.

**Comment by ViktorHofer** [comment]
We made some improvements in .NET Core and in the benchmarks to be at least on par with Java - in most cases we are faster. This is thanks to community contributions that optimized the benchmarks and also @tannergooding who introduced Vector in the Mandelbrot benchmark.

We are trying to improve certain scenarios drastically, e.g. Regex where we are clearly lacking behind competition.

**Comment by danmosemsft** [comment]
@Peperud @benaadams any interest in taking this further? It looks like we're ahead of Java in all scenarios now except Regex-redux (which @ViktorHofer is tackling) and k-nucleotide. This is with 2.0.3 not with latest bits. I am not sure what k-nucleotide needs to improve it.

We have obtained a machine that is a replica of the old Kentsfield hardware that the benchmark game uses. It has dramatically different performance characteristics to up to date hardware. We can try proposed changes on it, and also try 2.1 to compare.

**Comment by benaadams** [comment]
```
MAKE:
cp spectralnorm.csharpcore-3.csharpcore Program.cs
cp Include/csharpcore/tmp.csproj .
cp Include/csharpcore/runtimeconfig.template.json .
mkdir obj
cp Include/csharpcore/tmp.csproj.nuget.g.props ./obj
cp Include/csharpcore/tmp.csproj.nuget.g.targets ./obj
/usr/bin/dotnet build -c Release
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  tmp -> /home/dunham/benchmarksgame_quadcore/spectralnorm/tmp/bin/Release/netcoreapp2.0/tmp.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.55

6.11s to complete and log all make actions

COMMAND LINE:
/usr/bin/dotnet ./bin/Release/netcoreapp2.0/tmp.dll 5500
```

Wonder if there is any scope to crossgen and move the Jit timing out of the run time; or if R2R would hurt perf?

**Comment by danmosemsft** [comment]
We have no more updates to the benchmark code planned. We will take a look at k-nucleotide no doubt in future but this can be closed.

**Comment by benaadams** [comment]
Being able to specify a crossgen task in .csproj... though perhaps that's https://github.com/dotnet/cli/issues/1437

**Comment by danmosemsft** [comment]
Right. Looks like that's not in 2.1.
