### ISSUE TITLE
Update contribution guidelines

### ISSUE THREAD

**Issue by richlander** [dotnet/corefx#1147]
I deleted all of the managed code guidelines from the CoreCLR wiki. The guidance is to make changes in the CoreFX repo, so managed code guidelines seem inappropriate for the CoreCLR wiki. Also, since there are no C++-specific guidelines, it also looks odd.

The delete text is in Contribution-guidelines.md and is all there @ commit a4d01c7e207af58397e60269282a5634c0835766.

I could just add it, unless someone wants to take the opportunity to re-work the text at the same time.

**Comment by ellismg** [comment]
@richlander Is this in the wrong place?  The CoreFX wiki already has our managed code guidelines.  Did you mean to open this in CoreCLR?

**Comment by richlander** [comment]
This has all been resolved. It does look like I made the issue on the wrong wiki. Not sure how I managed that.
