### ISSUE TITLE
Add tests for DebugView on Expression

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#11495]
This is the next biggest black spot for code coverage in `System.Linq.Expressions`.

**Comment by stephentoub** [comment]
This might be useful:
https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Diagnostics/DebuggerAttributes.cs

You can see an example of it being used here:
https://github.com/dotnet/corefx/blob/0c5bf853e680ef401703c179ad3b065c49077929/src/Common/tests/System/Collections/DebugView.Tests.cs#L36

**Comment by bartdesmet** [comment]
Cool! I'll start by testing the textual output produced and move on to the attribute aspect of it beyond that.
