### ISSUE TITLE
Access is denied when use the System.Reflection.DispathProxy

### ISSUE THREAD

**Issue by shcemApp** [dotnet/corefx#11494]
HI 

I used the System.Reflection.DispatchProxy to dynamic a Interface,when use the DispatchProxy.Create<MyInterface,MyProxy>();get the Access is denied:'MyProxy',MyProxy is extend the DispatchProxy.

**Comment by svick** [comment]
Could you show your code that reproduces the error?

**Comment by karelz** [comment]
No repro details, closing. Feel free to reopen if you have more info.

**Comment by Mutuduxf** [comment]
I have catched the ex but not sure it is this issue.The demo repository is [here](https://github.com/Mutuduxf/DispatchProxyDemo).The file DynamicProxy.cs in the unit test project WebApiOnlyTest has a class like this
```csharp
private class InvokeProxy<T> : DispatchProxy
{
    private readonly Type _type;
    private static HttpClient _client;
    public InvokeProxy()
    {
        _type = typeof(T);
        _client = new HttpClient {BaseAddress = new Uri("http://localhost:5000/")};
        _client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
    }

    protected override object Invoke(MethodInfo targetMethod, object[] args)
    {
        var content = args.Any()
            ? new StringContent(JsonConvert.SerializeObject(args[0]), Encoding.UTF8, "application/json")
            : null;
        var responseForPost = _client.PostAsync($"/{_type.FullName}/{targetMethod.Name}", content);

        var result = responseForPost.Result.Content.ReadAsStringAsync().Result;

        return JsonConvert.DeserializeObject(result, targetMethod.ReturnType);
    }
}
```

but when i modify the InvokeProxy access modifier to "public" it will be OK.

**Comment by karelz** [comment]
Please file a new bug, typically we do not monitor old issues. Tips: Provide a minimal repro anyone can run. Post the exception call stack.
