### ISSUE TITLE
OSX Process.Start failing on non-rooted file name

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#11503]
I've been seeing this issue where executing a process with a non-rooted file name causes a `System.ComponentModel.Win32Exception : No such file or directory` failure.

Trace:

```
   at Interop.libproc.proc_pidpath(Int32 pid)
   at System.Diagnostics.Process.ResolvePath(String filename)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
```

The failures don't seem to have anything to do with what I'm trying to execute, since we never get further than calling proc_pidpath on the current process (`Interop.libproc.proc_pidpath(Interop.Sys.GetPid())`) in the `GetExePath` function called by `ResolvePath`. For context though, the error has been arising during [mc.dotnet](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20160907.03/workItem/System.IO.FileSystem.Watcher.Tests/analysis/xunit/System.IO.Tests.Directory_Changed_Tests~2FFileSystemWatcher_Directory_Changed_SymLink/log/0cdde726-02ae-403e-96ae-feb25609e83d) runs of symlink filesystemwatcher tests where `ln` is being called. The failures have been occurring intermittently,

**Comment by ianhays** [comment]
problem circumvented in FSW by https://github.com/dotnet/corefx/pull/11349

**Comment by Priya91** [comment]
@ianhays Can you provide a smaller repro..

**Comment by ianhays** [comment]
I haven't seen this issue occur anywhere in months. My original bug was due to some errors in FSW that I resolved. closing.
