### ISSUE TITLE
[CI] OSX builds are failing sometimes on the xunit post-build steps after successful build.

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#11520]
I've seen this a couple of times at least already, and I'm not sure what's causing it or why is it only happening on OSX machines. A sample build with this problem is: [http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/dev_api/job/osx_release_prtest/676/](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/dev_api/job/osx_release_prtest/676/)

Error message is: 
```
...
13:38:32 [xUnit] [INFO] - Converting '/Users/dotnet-bot/j/workspace/dotnet_corefx/dev_api/osx_release_prtest/bin/tests/Windows_NT.AnyCPU.Release/System.Runtime.Extensions.Performance.Tests/netcoreapp1.0/testResults.xml' .
13:57:15 
[xUnit] [ERROR] - The plugin hasn't been performed correctly: Problem on deletion
13:57:15 Build step 'Publish xUnit test result report' changed build result to FAILURE
...
```

**Comment by joperezr** [comment]
cc: @mmitche

**Comment by mmitche** [comment]
I think this is directly related to the network issues.

**Comment by stephentoub** [comment]
Yeah, we've hit this in spurts, and it seems to be bad today.  I'd previously opened https://github.com/dotnet/corefx/issues/9066 for this as well.

**Comment by joperezr** [comment]
I see, then I'll close this as a dupe of #9066
