### ISSUE TITLE
Why does Path.AltDirectorySeparatorChar return '/' on mac os and not '\'?

### ISSUE THREAD

**Issue by cdmihai** [dotnet/corefx#11529]
Both it and `Path.DirectorySeparatorChar` return `/` on mac. Why isn't the alt separator char `\`? As far as I know macs use slashes as path separators, not back-slashes. :)

I hit this when trying to split a path via `path.Split(Path.AltDirectorySeparatorChar, Path.DirectorySeparatorChar);` so I can catch cases where the path contains both separators. While this works on Windows (where separator and alt separator return `\` and `/`), it does not work on a mac where both separator properties return `/` (and thus not splitting on `\`). How can I accomplish this with .Net libraries (and not by hardcoding the actual slash characters)?

**Comment by cdrnet** [comment]
Since `\` is not a valid directory separator on Unix, it is not valid as *alternative* separator either. So imo it would be a bug if it would return `\`.

**Comment by stephentoub** [comment]
> Since \ is not a valid directory separator on Unix, it is not valid as alternative directory separator either. So imo it would be a bug if it would return \.

Exactly. There is no alternative, so we just return the same value.

**Comment by tdupont750** [comment]
This seems to also cause inconsistent behavior with System.IO.Path.GetFileName

**Code**
Console.WriteLine(System.IO.Path.GetFileName("/hello/world.txt"));
Console.WriteLine(System.IO.Path.GetFileName("\\hello\\world.txt"));

**Windows**
world.txt
world.txt

**Mac**
world.txt
\hello\world.txt

**Comment by danmosemsft** [comment]
@JeremyKuhne probably has history here, although I ima

**Comment by danmosemsft** [comment]
@tdupont750 can you please open a separate issue for that to see whether anything can/should be done.

**Comment by JeremyKuhne** [comment]
As mentioned above there is nothing we can do about the inconsistency. Win32 considers back slashes as directory separators, but the same isn't true for Unix. If you want to put the restriction in on your input data you need to do the transformation yourself (as MSBuild does).
