### ISSUE TITLE
Add optimized override of FileStream.CopyToAsync

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#11539]
Regardless of mode, we should be able to improve over the base implementation by:
- Potentially reusing the FileStream's buffer (if it has one) rather than creating a separate buffer
- Avoiding some per-Read argument validation checks

When the FileStream is in sync mode, we should further be able to improve over the base implementation by:
- Avoiding queueing a work item per Read

When the FileStream is in async mode, we should be able to improve over the base implementation by:
- Avoiding many of the per-read operation related costs, such as by registering once for cancellation rather than per operation, not creating a task per operation, etc.

**Comment by davidfowl** [comment]
😄 I approve this message
