### ISSUE TITLE
ResourceManager don't handle binary objects

### ISSUE THREAD

**Issue by joaoasrosa** [dotnet/corefx#11532]
ResourceManager don't handle binary objects.
In Visual Studio 2015 update 3 with .NET Standard 1.6, if we add a resource and then a bitmap we have errors regarding getting the object (GetObject method).
This needs API design.

**Comment by karelz** [comment]
This should be fixed in .NET Core 1.2 (as part of .NET Standard 2.0 effort - bringing parity of Framework to .NET Core).

**Comment by lextm** [comment]
Note that this is fixed by PR #11769.
