### ISSUE TITLE
Can`t add reference to System.XML 

### ISSUE THREAD

**Issue by jokerosky** [dotnet/corefx#11531]
I`ve created new solution for .net core (asp.net + class library) i need to add reference to System.XML but it fails with error, same time references to other libraries works well (for example System.Xml.Linq). I checked it on 3 different computers and got this error.

![image](https://cloud.githubusercontent.com/assets/6726130/18344350/187d0fa8-75e1-11e6-8164-bb65c6c40ffc.png)

**Comment by benaadams** [comment]
You need to either use the full framework System.XML and add to `frameworkAssemblies` e.g.
```json
"net452": {
  "frameworkAssemblies": {
	"System.Xml": {}
  }
}
```
Or to use the corefx you need to add the specific component you require as there is no System.XML and its is more modular. See: [System.Xml packages on nuget](https://www.nuget.org/packages?q=system.xml)

So for example if you want to use XmlDocument add a reference to [System.Xml.XmlDocument 4.0.1](https://www.nuget.org/packages/System.Xml.XmlDocument/)

**Comment by jokerosky** [comment]
oh, @benaadams  i found out what is wrong. I have added this direct links to framework assemblies, but it have not work, because of case sensitive name. The problem is in Visual Studio 2015, which adds System.XML instead of System.Xml. so it is not dotnet issue. 

Can someone from MS team add this issue to for VS guys and close this topic?

![image](https://cloud.githubusercontent.com/assets/6726130/18354368/82350242-760f-11e6-8bb3-648af8d75fa4.png)

**Comment by karelz** [comment]
@terrajobst any idea how/where in VS to route it?

**Comment by tarekgh** [comment]
Issue moved to [dotnet/sdk #931](https://github.com/dotnet/sdk/issues/931) via [**ZenHub**](https://www.zenhub.com/)
