### ISSUE TITLE
Ordering of ParallelEnumerable.GroupJoin and Join

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#1155]
This feels strange or bug-ish to me, but I'm not seeing anything either way in documentation.  The following:

```c#
ParallelQuery<int> left = Enumerable.Range(1, 4).AsParallel().AsOrdered();
ParallelQuery<int> right = Enumerable.Range(8, 32).AsParallel().AsOrdered();
foreach (Tuple<int, IEnumerable<int>> p in left.GroupJoin(right, x => x, y => y / 8, (k, g) => Tuple.Create(k, g)))
{
    Console.Write(p.Item1.ToString() + ":");
    foreach (int i in p.Item2)
    {
        Console.Write(i.ToString() + ",");
    }
    Console.WriteLine();
}
Console.Read();
```

... has output like this:
![groupjoin](https://cloud.githubusercontent.com/assets/5569508/6683955/d5efffe4-cccf-11e4-8958-4dfde0993f1d.jpg)
The first grouping is out of order, whereas I'm expecting even the grouped elements to be returned in order (which is what the non-parallel version does).  Strangely, of the multiple times I've run it, only the first run has ever been out of order.  Using `OrderBy` on the right query tends to result in other runs being disordered....

`Join` has similar problems to `GroupJoin`:

```c#
ParallelQuery<int> left = Enumerable.Range(1, 4).AsParallel().AsOrdered();
ParallelQuery<int> right = Enumerable.Range(8, 32).AsParallel().AsOrdered();
int prev = 0;
foreach (Tuple<int, int> p in left.Join(right, x => x, y => y / 8, (k, g) => Tuple.Create(k, g)))
{
    if (prev != p.Item1)
    {
        Console.WriteLine();
        Console.Write(p.Item1.ToString() + ":");
        prev = p.Item1;
    }
    Console.Write(p.Item2.ToString() + ",");
}
Console.Read();
```

... is producing output that looks like this:
![join](https://cloud.githubusercontent.com/assets/5569508/6684267/ee062632-ccd2-11e4-8363-679f7ed8dd0b.png)
...where every run is disordered.

This is the behavior of the current consumer release as well.

So is this "intended" behavior, and the documentation should be updated to warn people about the change from the sequential version (which explicitly states the ordering of the child elements is preserved), or is this an actual bug?

@stephentoub , @svick , any thoughts?

**Comment by AlfredoMS** [comment]
Indeed seems to be an issue, but only the first time this is executed. It might be a race condition worth of investigating deeper.

For now I found that a work around is to use ParallelEnumerable.Range instead of Enumerable.Range

**Comment by Clockwork-Muse** [comment]
@AlfredoMS - that's going to be the partitioning ParallelEnumerable.Range is "working" only because the source is trivially partitionable; the moment you have it do any real work (using Select or Where first, etc) that can go out the window (because it might be repartitioned).
Additionally, I'm not sure of how often the output of Range is used in the real world, as opposed to using a List or enumerated-only collection, so I'm not sure the 'workaround' is really applicable...

**Comment by karelz** [comment]
@alexperovich says: Likely race condition, tricky to track down and fix.

**Comment by jswolf19** [comment]
@karelz I think I've tracked down the issue... I'll try to get a working branch, and then I may need help on performance...

**Comment by jswolf19** [comment]
I'll take no response as a sign that no one else is working on this and dig in a little further.

With Join and only an ordered right input, I'm assuming that, as with [Concat,](https://github.com/dotnet/corefx/issues/1332#issuecomment-208352578) if only one input is ordered, then there is no defined ordering. However, I will preserve current ordering when only the left input is ordered.

I'm looking at GroupBy for some inspiration for how to handle ordered right data on GroupJoins. I plan to order the right data regardless of the ordered state of the left data.
