### ISSUE TITLE
Track System.Collections.Specialized tests update to latest netstandard1.3 implementation once 1.1 ships

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#11566]
related to #11544

**Comment by Priya91** [comment]
@karelz What's the timeline for getting stable packages from release/1.1.0 and how does it compare with netstandard2.0?

**Comment by karelz** [comment]
1.1.0 is separate branch now. I think we can go ahead on this one in master. It is not going to affect 1.1.0 branch.

**Comment by Priya91** [comment]
>  I think we can go ahead on this one in master

Master branch also tests all the configurations by setting ```/p:TargetGroup``` and ```/p:FilterToTestTFM``` properties to the desired configuration. Though the default is to run only netcoreapp1.1 tests, anyone can trigger a run to test other cases, in this ex, ```/p:TargetGroup=netstandard1.3``` and ```/p:FilterToTestTFM=netcoreapp1.0```. The package harvesting takes libs only from stable packages, so this change cannot be made in master until there is a RTM release from release/1.1.0

**Comment by karelz** [comment]
1.1.0 was released. Can we make the change now?

**Comment by Priya91** [comment]
Yes, it should be as simple as removing the xunit attributes that skips the test.

**Comment by Priya91** [comment]
fixed with #15559
