### ISSUE TITLE
Cleanup/optimize Random, remove use of % operator

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#11568]
Even formatted, the [source code for Random](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/Random.cs) is currently quite messy, and makes heavy use of the modulo operator by a non-power of 2 in the constructor. It looks like since what is being modulo'd is directly tied to a loop variable, we may be able to detect when it goes past 55, and if so just subtract 55. This will save us many expensive `idivs`.

**Comment by chrisaut** [comment]
Done, but in other repos as discussed in original PR. Think this can be closed.

https://github.com/dotnet/coreclr/pull/7156
https://github.com/dotnet/corert/pull/1840

**Comment by jamesqo** [comment]
@chrisaut Great! Thanks for fixing this.
