### ISSUE TITLE
Investigate optimizing DeflateStream.CopyToAsync

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#11571]
Currently it's not overridden and inherits the base implementation.  We may be able to improve on that to the point where it would be worth overriding, such as by avoiding repeatedly pinning and unpinning.

**Comment by ianhays** [comment]
completed by @stephentoub in https://github.com/dotnet/corefx/commit/73c954517c9fbdea29fe1884fb143cb6ab3af4ec

**Comment by stephentoub** [comment]
@davidfowl, were there additional changes you were looking at here?

**Comment by stephentoub** [comment]
I think there's more that can be done here.  Re-opening and assigning to myself.
