### ISSUE TITLE
Consider converting ValueTupleTests to use [Theory]

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#11579]
Currently I'm trying to make some changes to the ValueTuple hashing algorithm. [This](https://github.com/dotnet/corefx/blob/master/src/System.ValueTuple/tests/ValueTupleTests.cs#L987-L996) is a huge pain since xUnit needs to stop execution on the first `Assert` failure, so then it does not tell me what the actual hashes for the other tuples were.

We should consider converting these tests to `[Theory]` instead of `[Fact]` so it prints all of the expected/actual for the failed cases. Will be hugely convenient if the hashing algorithm is changed yet again after my upcoming PR (though that's unlikely).

**Comment by stephentoub** [comment]
For the specific example you linked to, how would you convert that to a [Theory]?  Each entry has a different number of arguments.  My expectation is that any such transformation would make the test harder to understand.

**Comment by jamesqo** [comment]
@stephentoub Whoops, you seem to be right; I had forgotten that the type of the tuple actually changes with every new parameter.
