### ISSUE TITLE
DriveInfo.DriveType reports "unknown" in Windows Subsystem for Linux

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#11570]
Running on Ubuntu in Windows Subsystem for Linux, on rs_prerelease build 14915, DriveInfo.DriveType reports "Unknown" for both the Linux file system (`/`, `/usr`, etc.) and mounted Windows drives (`/mnt/c`, etc).  I would expect it to report "fixed" for at least the Linux file system, and preferably the mounted Windows drives as well.

The `df -T` command reports file system names for these, so apparently there is some info available:

```
Filesystem     Type  1K-blocks      Used Available Use% Mounted on
rootfs         lxfs  498859004 167549372 331309632  34% /
data           lxfs  498859004 167549372 331309632  34% /data
cache          lxfs  498859004 167549372 331309632  34% /cache
mnt            lxfs  498859004 167549372 331309632  34% /mnt
none           tmpfs 498859004 167549372 331309632  34% /dev
none           tmpfs 498859004 167549372 331309632  34% /run
none           tmpfs 498859004 167549372 331309632  34% /run/lock
none           tmpfs 498859004 167549372 331309632  34% /run/shm
none           tmpfs 498859004 167549372 331309632  34% /run/user
none           drvfs 498859004 167549372 331309632  34% /mnt/c
```

(note that `/` is "lxfs" and `/mnt/c` is "drvfs."

This causes a failure in the DriveInfo tests (in `DriveInfoUnixTests.PropertiesOfValidDrive`).  I'll be conditionally disabling that test for now.

**Comment by sunilmut** [comment]
Thanks Eric for reporting this. We have opened a bug internally to track this.

**Comment by misenesi** [comment]
Discussed with Eric offline. The issues seems to be that the DriveInfo.DriveType doesn't recognize drvfs and lxfs.

**Comment by karelz** [comment]
It looks like we need another case in switch statement for these 2 file systems in `DriveInfo.DriveType`.

**Comment by weshaggard** [comment]
I hit this same test failure when running the tests in an ubuntu docker image on windows.
