### ISSUE TITLE
Consider adding something to the docs about /p:RestorePackages=false

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#11578]
I just found out that you can pass in `/p:RestorePackages=false` to skip restoring packages while building a project. I don't know how I lived without this switch; previously I would wait on average about ~2m to re-build a project even for simple changes, like syntax errors. Now it takes about ~15s. We should really, really consider adding something about this to the markdown docs so less patient people don't get frustrated building.

**Comment by mellinoe** [comment]
IMO, we should just switch the default behavior to NOT restore packages (it's a waste of time in most workflows, and make it either an optional switch, or make it a manual process.

**Comment by tarekgh** [comment]
we had soem engineering system changes which we are not restoring many packages and instead we build and use the source libraries. so this issue in not valid any more. Thanks.
