### ISSUE TITLE
Investigate optimizing BufferedStream.CopyToAsync

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#11572]
BufferedStream doesn't currently override CopyToAsync.  We should investigate doing so, as there may be opportunities for optimization.  For example, BufferedStream often contains a fairly large internal buffer, potentially larger than the one requested as an arg to CopyToAsync.  In that case, BufferedStream's internal buffer could be used instead of allocating a new one.

**Comment by maddin2016** [comment]
Hi @stephentoub, i'd like to see if i can help you. On which branch changes should be made. Master or dev?

**Comment by stephentoub** [comment]
@maddin2016, the master branch is good, thanks.

**Comment by karelz** [comment]
Stephen, I assume you are working on it ... assigned to you.

**Comment by stephentoub** [comment]
> @stephentoub I assume you are working on it

https://github.com/dotnet/corefx/pull/12507
