### ISSUE TITLE
System.Collections.NonGeneric.Tests - Intermittent test failure in merge build

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/corefx#1158]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_prtest/409/
----
Build #409 (Mar 16, 2015 12:10:28 PM)

PR #1133: Add System.Linq.Queryable S...
	No changes.
	
GitHub pull request #1133 of commit 0f60d399123ce4b4f2ec4d4e242837a5899467f7 automatically merged.

	Test Result (1 failure / +1)
Comparer_DefaultInvariant.ExecuteComparer_DefaultInvariant
	
Identified problems

Subproject build: dotnet_corefx_windows_debug_prtest (#404)

No identified problem

No problems were identified. If you know why this problem occurred, please add a suitable Cause for it.
----

From http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/404/console
----
 Create Hashtable using default settings
   : Error Err_8888yyy!  exc_general==
  Xunit.Sdk.EqualException: Assert.Equal() Failure
            Î“Ã¥Ã´ (pos 0)
  Expected: en-US
  Actual:   cs-CZ
            Î“Ã¥Ã¦ (pos 0)
     at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences)
     at Xunit.Assert.Equal(String expected, String actual)
     at Comparer_DefaultInvariant.runTest() in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Collections.NonGeneric\tests\Comparer\Comparer_DefaultInvariant.cs:line 52
  Fail! iCountErrors==1
     Comparer_DefaultInvariant.ExecuteComparer_DefaultInvariant [FAIL]
        Assert.True() Failure
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Collections.NonGeneric\tests\Comparer\Comparer_DefaultInvariant.cs(114,0): at Comparer_DefaultInvariant.ExecuteComparer_DefaultInvariant()

=== TEST EXECUTION SUMMARY ===
     System.Collections.NonGeneric.Tests  Total: 198, Errors: 0, Failed: 1, Skipped: 0, Time: 1.139s

**Comment by krwq** [comment]
Duplcate: #1504
Since I already provided more details and disabled the test in the other issue I'm closing this issue.
