### ISSUE TITLE
System.Diagnostics.Process.Tests - Intermittent test failure during build.cmd without any local changes

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/corefx#1159]
From msbuild.log:

----
12:46:12.176    69>RunTestsForProject: (TargetId:1705)
                        System.Diagnostics.ProcessTests.ProcessTest.Process_AsyncOutputStream [FAIL] (TaskId:1148)
                           Assert.Equal() Failure (TaskId:1148)
                                     Gåô (pos 0) (TaskId:1148)
                           Expected:  (TaskId:1148)
                           Actual:   ProcessTest_ConsoleApp.exe startedProcess-+-+-+ (TaskId:1148)
                                     Gåæ (pos 0) (TaskId:1148)
                           Stack Trace: (TaskId:1148)
                              f:\GitHub\corefx\src\System.Diagnostics.Process\tests\System.Diagnostics.Process.Tests\Process_StreamTests.cs(73,0): at System.Diagnostics.ProcessTests.ProcessTest.Process_AsyncOutputStream() (TaskId:1148)

12:46:12.176    69>RunTestsForProject: (TargetId:1705)
                     Finished:    System.Diagnostics.Process.Tests (TaskId:1148)
                      (TaskId:1148)
                     === TEST EXECUTION SUMMARY === (TaskId:1148)
                        System.Diagnostics.Process.Tests  Total: 34, Errors: 0, Failed: 1, Skipped: 0, Time: 6.382s (TaskId:1148)

----

Tests pass during the second execution of build.cmd

**Comment by ellismg** [comment]
I was seeing this locally as well on Windows 8.1 at home.

**Comment by pallavit** [comment]
I tried to repro this locally (win 8.1 as well) but could not get this to fail :|

**Comment by ellismg** [comment]
@pallavit I'll take a look tonight at home and see if I can understand what's different.

**Comment by pallavit** [comment]
Thanks @ellismg

**Comment by cnblogs-dudu** [comment]
Same failure.
```
 corerun.exe xunit.console.netcore.exe System.Diagnostics.Process.Tests.dll  -xml .\testResults.xml -notrait category=failing (TaskId:3528)
 xUnit.net console test runner (32-bit .NET Core) (TaskId:3528)
 Copyright (C) 2014 Outercurve Foundation. (TaskId:3528)
  (TaskId:3528)
 Discovering: System.Diagnostics.Process.Tests (TaskId:3528)
 Discovered:  System.Diagnostics.Process.Tests (TaskId:3528)
 Starting:    System.Diagnostics.Process.Tests (TaskId:3528)
    System.Diagnostics.ProcessTests.ProcessTest.Process_AsyncOutputStream [FAIL] (TaskId:3528)
       Assert.Equal() Failure (TaskId:3528)
                 â†?(pos 0) (TaskId:3528)
       Expected:  (TaskId:3528)
       Actual:   ProcessTest_ConsoleApp.exe startedProcessÂ·Â·Â· (TaskId:3528)
                 â†?(pos 0) (TaskId:3528)
       Stack Trace: (TaskId:3528)
          e:\Dev\GitHub\DotNet\corefx\src\System.Diagnostics.Process\tests\System.Diagnostics.Process.Tests\Process_StreamTests.cs(73,0): 
          at System.Diagnostics.ProcessTests.ProcessTest.Process_AsyncOutputStream() (TaskId:3528)
 Finished:    System.Diagnostics.Process.Tests (TaskId:3528)
  (TaskId:3528)
 === TEST EXECUTION SUMMARY === (TaskId:3528)
    System.Diagnostics.Process.Tests  Total: 34, Errors: 0, Failed: 1, Skipped: 0, Time: 2.522s (TaskId:3528)
20:39:37.546    67>E:\Dev\GitHub\DotNet\corefx\src\dir.targets(202,5): warning MSB3073: 
The command "corerun.exe xunit.console.netcore.exe System.Diagnostics.Process.Tests.dll  -xml .\testResults.xml -notrait category=failing" exited with code 1. 
[E:\Dev\GitHub\DotNet\corefx\src\System.Diagnostics.Process\tests\System.Diagnostics.Process.Tests\System.Diagnostics.Process.Tests.csproj]
```

**Comment by cnblogs-dudu** [comment]
Fixes `System.Diagnostics.ProcessTests.ProcessTest.Process_AsyncOutputStream [FAIL]` by changing the code page of console from 1252(ANSI - Latin I) to 65001(UTF-8) with `CHCP 650011` command.

**Comment by pallavit** [comment]
@cnblogs-dudu Not sure why would this cause intermittent failure?
Unfortunately I can't still repro it on my system. I will spend some time looking at it today. Worst case I will add some logging in the test to help identify the issue.

**Comment by ellismg** [comment]
I don't think the codepage is the issue.

My current suspicion is that there's a race where the process exits before we have finished the callback to push the stdout data into the string builder and so we end up with an empty string when we do our comparison, but I haven't dug into the implementation of the callbacks or WaitForExit yet.

Note that the arguments to Assert.Equal are passed backwards in the test, so in the log "expected" means "actual" and "actual" means "expected".

**Comment by pallavit** [comment]
> Note that the arguments to Assert.Equal are passed backwards in the test, so in the log "expected" means "actual" and "actual" means "expected".

Yes, I have a local fix to change this across process tests :). Should be out for PR soon.

**Comment by pallavit** [comment]
> My current suspicion is that there's a race where the process exits before we have finished the callback to push the stdout data into the string builder and so we end up with an empty string when we do our comparison, but I haven't dug into the implementation of the callbacks or WaitForExit yet.

Hmm. It is strange that we are seeing this only on output and not error , I would expect the code to be similar. I will take a look at the code as well. Thanks!

**Comment by cnblogs-dudu** [comment]
Added `p.StartInfo.StandardOutputEncoding = Encoding.UTF8;` into Process_AsyncOutputStream() and fixed warning MSB3073.
```
warning MSB3073: 
The command "corerun.exe xunit.console.netcore.exe System.Diagnostics.Process.Tests.dll  -xml .\testResults.xml -notrait category=failing" exited with code 1. 
[E:\Dev\GitHub\DotNet\corefx\src\System.Diagnostics.Process\tests\System.Diagnostics.Process.Tests\System.Diagnostics.Process.Tests.csproj]
```

**Comment by pallavit** [comment]
I am opportunistically closing this issue against https://github.com/dotnet/corefx/pull/1207 PR request. Please reopen an issue if you can still repro this.
