### ISSUE TITLE
Potential optimization: Using vectorization for Enumerable.Sum/Average

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#11599]
Some thoughts:
- If the input is an array, e.g. `int[]` in the case of `Sum(IEnumerable<int>)`, we could use vectorization to compute the sum, and maybe avoid range checks.
- If the input is an `ICollection` but not an array, we could rent an array from `ArrayPool<int>.Shared` and then call `CopyTo` on this array, and then go ahead with using vectorization. This will undoubtedly be slower for small collections, and it adds making another pass over the array + renting. However, it will still be faster than the enumerable version which makes 2 virtual method calls per-iteration, since only one virtual call, `CopyTo`, is made for the entire collection.

Unfortunately I don't know if the vectorization part is possible since `Sum` uses `checked` arithmetic. Checking if any of the numbers in the vector are negative from overflow, e.g. [here](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/String.Manipulation.cs#L151), will not work since it's possible that some of the ints in the array are negative.

**Comment by karelz** [comment]
We should get some data first -- How much it slows down small collections? Where is the breaking point? How much it can improve?

**Comment by karelz** [comment]
Closing as there is not convincing evidence, this would be a real benefit for all cases.
Feel free to reopen if/when you have new data.
