### ISSUE TITLE
Replace Contract.Requires with Debug.Assert

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#11596]
We have over 600 occurrences of Contract.Requires in corefx right now.  We don't use the contract rewriter, which means we don't build with CONTRACTS_FULL, which means all of these Contract.Requires are nops, even in debug builds.  That's a lot of verification we're missing.  We should convert all of these to be Debug.Assert (with the exception of some in tests, which should be converted to use xunit's Assert class), so that we're verifying the things we intended to verify.  If we ever decide to switch to using contracts, they can be switched back (or to using language syntax if that comes along), and it'll likely be minor compared to all of the other asserts we have that would likely be changed to some kind of contract call.

Contract.Ensures are a bit harder, but in many cases these could be converted to Debug.Asserts as well, just in different location(s) in the member.

**Comment by jamesqo** [comment]
Interesting, I had assumed that Requires/Ensures were still reflected in debug builds so I skimped on changing them in mscorlib. Maybe there should be an issue opened in CoreCLR too?

**Comment by stephentoub** [comment]
> Maybe there should be an issue opened in CoreCLR too?

I would leave them in coreclr as-is for now.

**Comment by benaadams** [comment]
#11600 covers the `Contract.Requires` in non-test 
Doesn't cover test to `Assert.` (there are some in the Immutable collections tests)
Doesn't cover `Contract.Ensures`

**Comment by jamesqo** [comment]
@stephentoub CONTRACTS_FULL is not defined in CoreCLR either, I believe. dotnet/coreclr#5454

**Comment by benaadams** [comment]
Some of the Contracts usings and references removals are prevented by the `[Pure]` attribute. Is this still of value?

**Comment by jamesqo** [comment]
@stephentoub Shouldn't this still be open? There are still a lot of calls to other `Contract` methods,  e.g. `Contract.Ensures`, in the immutable collections source. https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs#L58

**Comment by stephentoub** [comment]
> Shouldn't this still be open? There are still a lot of calls to other Contract methods, e.g. Contract.Ensures

There is no direct equivalent to Ensures on Debug, so this issue was specifically about Requires, which can be replaced by Assert.

**Comment by jamesqo** [comment]
> Whether we want to scrub out Ensures is really a separate question; I only mentioned it in the issue as an off-hand for context.

All `Ensures` code is also dead though, so if they're not replaced with asserts they should probably be deleted. Having them in the repo gives people a false sense of security that the postcondition is actually enforced.

> so this issue was specifically about Requires,

Fair enough, I will open a different issue to either replace/delete other `Contract` methods.
