### ISSUE TITLE
Intermittent: CaseInsensitiveHashCodeProviderTests.Default_GetHashCodeCompare failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#11598]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/dev_api/job/osx_debug_prtest/34/consoleText
```
     System.Collections.Tests.CaseInsensitiveHashCodeProviderTests.Default_GetHashCodeCompare(a: "hello", b: "HELLO", expected: True) [FAIL]
        Assert.Equal() Failure
        Expected: True
        Actual:   False
        Stack Trace:
              at System.Collections.Tests.CaseInsensitiveHashCodeProviderTests.Default_GetHashCodeCompare(Object a, Object b, Boolean expected)
```

**Comment by karelz** [comment]
@Priya91 can you please take a look?

**Comment by stephentoub** [comment]
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu14.04_debug_prtest/3/consoleText

**Comment by Priya91** [comment]
taking a look

**Comment by stephentoub** [comment]
Failed here on Ubuntu:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/703/

**Comment by ericeil** [comment]
Failed again on Ubuntu:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/811/

**Comment by stephentoub** [comment]
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_release_prtest/846/consoleText

**Comment by Priya91** [comment]
Not able to repro locally, and not enough data to figure out failing for Default or DefaultInvariant case. Either case, it looks like a bug in ```CompareInfo.GetHashCode```. Renabling the test to get line no on failure.

cc @tarekgh

**Comment by Priya91** [comment]
There were no reports of this test failure for the past week, hence closing issue.
