### ISSUE TITLE
System.Reflection.TypeExtensions.Tests has package restore errors on initial build

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#11604]
## Steps (on clean repo with newly initalized buildtools etc.):

1) Navigate to `src/Sytem.Reflection.TypeExtensions/tests`
2) Run `msbuild /T:BuildAndTest`
## Fix

The errors seem to be as a result of System.Reflection.TypeExtensions.dll not being found (see log).
The errors go away if I do the following before my steps to reproduce:
1) Navigate to `src/Sytem.Reflection.TypeExtensions/src/redist`
2) Run `msbuild`
## Notes

The VS project for System.Reflection.TypeExtensions also seems to have hundreds of errors relating to non existent methods in the `src` folder that clearly exist.
I also think this has something to do with the `src/redist` folder not present in most projects
## Log

[msbuild.txt](https://github.com/dotnet/corefx/files/466171/msbuild.txt)

**Comment by hughbe** [comment]
I also need to run `msbuild` in the source directory

**Comment by mellinoe** [comment]
Hey @hughbe , the structure of this project has changed since you filed this. It shouldn't repro anymore. Please re-open if you're still hitting problems.
