### ISSUE TITLE
Compat work for StringInfo class globalization APIs (for Linux)

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#11615]
Add missing implementation for the newly added APIs in net standard 1.7

**Comment by tarekgh** [comment]
https://github.com/dotnet/corefx/issues/10961

**Comment by arvopartet** [comment]
Has the StringInfo class API (for Linux) been made compatible? (in dotnet core 1.1 (for Linux (using VSC)) it misses a lot of methods mentioned on 
https://docs.microsoft.com/en-us/dotnet/api/?view=netcore-1.1&term=stringinfo
)

**Comment by tarekgh** [comment]
@arvopartet the APIs added in 2.0 so it is expected to be missing in 1.1
