### ISSUE TITLE
Port some missing threading types/members (Overlapped, etc.)

### ISSUE THREAD

**Issue by kouvel** [dotnet/corefx#11637]
- [x] M:System.Threading.ThreadPool.BindHandle(System.IntPtr)
- [ ] M:System.Threading.ThreadPool.UnsafeQueueNativeOverlapped(System.Threading.NativeOverlapped*)
- [ ] T:System.Threading.Overlapped
- [ ] M:System.Threading.Overlapped.#ctor
- [ ] M:System.Threading.Overlapped.#ctor(System.Int32,System.Int32,System.Int32,System.IAsyncResult)
- [ ] M:System.Threading.Overlapped.#ctor(System.Int32,System.Int32,System.IntPtr,System.IAsyncResult)
- [ ] P:System.Threading.Overlapped.AsyncResult
- [ ] P:System.Threading.Overlapped.EventHandle
- [ ] P:System.Threading.Overlapped.EventHandleIntPtr
- [ ] M:System.Threading.Overlapped.Free(System.Threading.NativeOverlapped*)
- [ ] M:System.Threading.Overlapped.get_AsyncResult
- [ ] M:System.Threading.Overlapped.get_EventHandle
- [ ] M:System.Threading.Overlapped.get_EventHandleIntPtr
- [ ] M:System.Threading.Overlapped.get_OffsetHigh
- [ ] M:System.Threading.Overlapped.get_OffsetLow
- [ ] P:System.Threading.Overlapped.OffsetHigh
- [ ] P:System.Threading.Overlapped.OffsetLow
- [ ] M:System.Threading.Overlapped.Pack(System.Threading.IOCompletionCallback)
- [ ] M:System.Threading.Overlapped.Pack(System.Threading.IOCompletionCallback,System.Object)
- [ ] M:System.Threading.Overlapped.set_AsyncResult(System.IAsyncResult)
- [ ] M:System.Threading.Overlapped.set_EventHandle(System.Int32)
- [ ] M:System.Threading.Overlapped.set_EventHandleIntPtr(System.IntPtr)
- [ ] M:System.Threading.Overlapped.set_OffsetHigh(System.Int32)
- [ ] M:System.Threading.Overlapped.set_OffsetLow(System.Int32)
- [ ] M:System.Threading.Overlapped.Unpack(System.Threading.NativeOverlapped*)
- [ ] M:System.Threading.Overlapped.UnsafePack(System.Threading.IOCompletionCallback)
- [ ] M:System.Threading.Overlapped.UnsafePack(System.Threading.IOCompletionCallback,System.Object)

**Comment by ramarag** [comment]
@jkotas it should be fine for me to add these Apis to System.Runtime ?

**Comment by jkotas** [comment]
`System.Threading.Overlapped` should go to `\corefx\src\System.Threading.Overlapped`
