### ISSUE TITLE
EncryptFile & DecryptFile not available on all Windows versions

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#11658]
These APIs (exposed through File and FileInfo) are entries into EFS functionality. WinRT doesn't expose these particular APIs directly, but has a `FileProtectionManager` class that provides access to EFS (Encrypt is the only currently supported entrypoint).

OneCore also does not expose EncryptFile\DecryptFile.

Need to follow through on the plausibility of using FileProtectionManager and potentially other entry points into EFS to expose this API in CoreFx on Windows.

**Comment by karelz** [comment]
We need to implement EncryptFile/DecryptFile using FileProtectionManager APIs.

**Comment by JeremyKuhne** [comment]
Triage: No customer demand. The existing Encrypt/Decrypt works with EFS, which isn't fully supported on file systems like ReFS. It is also discouraged- MS IT for example disables this in favor of BitLocker.
