### ISSUE TITLE
APIs not exposed from System.Reflection

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#11656]
The following is a list of Reflection APIs that are not going to be included in netstandard2.0
[This is only to keep track in case we decide to expose these later.]

```
M:System.Reflection.FieldInfo.GetValueDirect(System.TypedReference)
M:System.Reflection.FieldInfo.SetValueDirect(System.TypedReference,System.Object)
M:System.Reflection.MemberInfo.System.Runtime.InteropServices._MemberInfo.GetIDsOfNames(System.GUID,System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)
M:System.Reflection.MemberInfo.System.Runtime.InteropServices._MemberInfo.GetType
M:System.Reflection.MemberInfo.System.Runtime.InteropServices._MemberInfo.GetTypeInfo(System.UInt32,System.UInt32,System.IntPtr)
M:System.Reflection.MemberInfo.System.Runtime.InteropServices._MemberInfo.GetTypeInfo(System.UInt32)
M:System.Reflection.MemberInfo.System.Runtime.InteropServices._MemberInfo.Invoke(System.UInt32,System.GUID,System.UInt32,System.Int16,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)

M:System.Reflection.MethodBase.System.Runtime.InteropServices._MethodBase.get_IsAbstract
M:System.Reflection.MethodBase.System.Runtime.InteropServices._MethodBase.get_IsAssembly
M:System.Reflection.MethodBase.System.Runtime.InteropServices._MethodBase.get_IsConstructor
M:System.Reflection.MethodBase.System.Runtime.InteropServices._MethodBase.get_IsFamily
M:System.Reflection.MethodBase.System.Runtime.InteropServices._MethodBase.get_IsFamilyAndAssembly
M:System.Reflection.MethodBase.System.Runtime.InteropServices._MethodBase.get_IsFamilyOrAssembly
M:System.Reflection.MethodBase.System.Runtime.InteropServices._MethodBase.get_IsFinal
M:System.Reflection.MethodBase.System.Runtime.InteropServices._MethodBase.get_IsHideBySig
M:System.Reflection.MethodBase.System.Runtime.InteropServices._MethodBase.get_IsPrivate
M:System.Reflection.MethodBase.System.Runtime.InteropServices._MethodBase.get_IsPublic
M:System.Reflection.MethodBase.System.Runtime.InteropServices._MethodBase.get_IsSpecialName
M:System.Reflection.MethodBase.System.Runtime.InteropServices._MethodBase.get_IsStatic
M:System.Reflection.MethodBase.System.Runtime.InteropServices._MethodBase.get_IsVirtual
M:System.Reflection.MethodBase.System.Runtime.InteropServices._MethodBase.GetIDsOfNames(System.GUID,System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)
M:System.Reflection.MethodBase.System.Runtime.InteropServices._MethodBase.GetType
M:System.Reflection.MethodBase.System.Runtime.InteropServices._MethodBase.GetTypeInfo(System.UInt32,System.UInt32,System.IntPtr)
M:System.Reflection.MethodBase.System.Runtime.InteropServices._MethodBase.GetTypeInfoCount(System.UInt32)
M:System.Reflection.MethodBase.System.Runtime.InteropServices._MethodBase.Invoke(System.UInt32,System.GUID,System.UInt32,System.UInt16,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)
```

The following list we prefer not to expose, as they are either CAS-related APIs or have dependencies on also-not-exposed types from other contracts:
```
M:System.Reflection.Assembly.get_Evidence
M:System.Reflection.Assembly.get_IsFullyTrusted
M:System.Reflection.Assembly.Load(byte[],byte[],System.Security.Policy.Evidence)
M:System.Reflection.Assembly.Load(byte[],byte[],System.Security.SecurityContextSource)
M:System.Reflection.Assembly.Load(System.Reflection.AssemblyName,System.Security.Policy.Evidence)
M:System.Reflection.Assembly.Load(System.String,System.Security.Policy.Evidence)
M:System.Reflection.Assembly.LoadFrom(System.String,System.Security.Policy.Evidence)
M:System.Reflection.Assembly.LoadFrom(System.String,System.Security.Policy.Evidence,byte[],System.Configuration
M:System.Reflection.Assembly.LoadFile(System.String,System.Security.Policy.Evidence)
M:System.Reflection.Assembly.LoadWithPartialName(System.String,System.Security.Policy.Evidence)
M:System.Reflection.AssemblyName.get_KeyPair
M:System.Reflection.AssemblyName.set_KeyPair(System.Reflection.StrongNameKeyPair)
C:System.Reflection.StrongNameKeyPair
M:System.Reflection.Module.GetSignerCertificate
```

**Comment by danmosemsft** [comment]
@weshaggard @sepidehMS We are not keeping open any issues to track what's not in STandard 2.0. That's going to be tracked in the .NET Standard repo itself.

**Comment by danmosemsft** [comment]
@weshaggard why aren't these in standard?
```
M:System.Reflection.FieldInfo.GetValueDirect(System.TypedReference)
M:System.Reflection.FieldInfo.SetValueDirect(System.TypedReference,System.Object)
```

they have to be worked around. https://github.com/stephentoub/corefx/blob/ec1b5981ee35e246cbfa803bf6644b5a85d9c7e2/src/System.Runtime.Serialization.Formatters/src/System/TemporaryStubs.cs#L43

**Comment by danmosemsft** [comment]
@stephentoub

**Comment by weshaggard** [comment]
My understanding from @jkotas is that TypedReference is a concept that doesn't work in CoreCLR/CoreRT and were removed from the standard with similar things like ArgIterator. If that isn't the case and they actually do work then we can reconsider.

**Comment by jkotas** [comment]
Well, there are number of other useless types and methods in netstandard20 that do not work (e.g. always throw PNSE) in CoreCLR/CoreRT today.

TypedReference and ArgIterator were removed from netstandard20 because of they are rarely used, hard and expensive to implement in the runtime, and they do not even have a first class syntax in C#. I do not see a huge difference between including them in netstandard and implementing them as dummy types in .NET Core that just throw PNSE; or not including them. Either way, if somebody depends on them - they will have to rework their code to make it work on .NET Core.

**Comment by danmosemsft** [comment]
Per the discussion above then, this can remain outside of Standard, and we already haev a workaround linked above.

**Comment by mwpowellhtx** [comment]
Much to my chagrin, so 1) ``Type.Assembly`` has been deprecated and removed when I target ``netstandard1.6``, the migration path is ``GetTypeInfo(this Type)`` as per [issue](https://github.com/aspnet/dnx/issues/1229). And now 2) even this will be deprecated?

So, what, exactly, is the migration path then, when I want to run with something like ``typeof(object).Assembly``?

**Comment by jkotas** [comment]
`typeof(object).Assembly` is the way for netstandard2.0 and forward. If possible, target netstandard2.0, keep using `typeof(object).Assembly` like you have always did in .NET, and pretend that netstandard1.x never happened. We have realized that the deprecations of many APIs in netstandard1.x was a mistake.

**Comment by mwpowellhtx** [comment]
@jkotas I'm working in an assembly in which I must target ``netstandard1.6``, and apparently this is a breaking change from then. Talk about pulling the rug out. Come on folks!

**Comment by jkotas** [comment]
For netstandard1.x, just use the GetTypeInfo.

**Comment by mwpowellhtx** [comment]
@jkotas Allow me to ask the follow up question; the work I am doing is on an *Analyzer*, *Code Fix*, and ultimately, *Code Generator*, against ``CodeGeneration.Rosly``. Am I clear(ish) to target ``netstandard2.0`` in this instance, and as you suggested, forget ``netstandard1.x`` ever happened?

**Comment by jkotas** [comment]
It depends on whether you are ok with requiring .NET Framework 4.7.2+ or .NET Core 2.0+ for you analyzer.

**Comment by mwpowellhtx** [comment]
@jkotas Well, it depends, as far as I know, this would be a development dependency only. Not intended for delivery into a "run-time", per se. Only to serve the the target code base of the subscriber generating some very boilerplate code.
