### ISSUE TITLE
Readd ReflectionXmlSerializationReader and Writer back after dev/api merge

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#11686]
When merging dev/api branch to master in PR #11679 we had to temporarily remove this two classes since they were added on the XmlSerializer contract which now contains no implementation. All implementation cor that contract has moved down to System.Private.Xml. I tried adding these two classes to the System.Private.Xml but it wasn't straight forward (at least from a quick stab at it) since a lot of dependencies have moved. This issue is to track the work to add those back to System.Private.Xml.

cc: @shmao @stephentoub

**Comment by shmao** [comment]
cc: @huanwu @zhenlan

**Comment by shmao** [comment]
This is fixed by https://github.com/dotnet/corefx/pull/11924.
