### ISSUE TITLE
WinHttpRequestState memory leak when sending WinHttp requests from WinHttpHandler.

### ISSUE THREAD

**Issue by baal2000** [dotnet/corefx#11693]
Noticed during code review that there is a potential memory leak in `GCHandle` and `WinHttpRequestState` instances when `WinHttpHandler.InternalSendRequestAsync()` executed repeatedly from asynchronous `do/while` loop in `WinHttpHandler.StartRequest`. 

**Cause:** 
`WinHttpRequestState` may pin `WinHttpRequestState` instances multiple times due to missing `_operationHandle.IsAllocated` check around  `_operationHandle = GCHandle.Alloc(this)`:

```
        public void Pin()
        {
#if DEBUG
            Interlocked.Increment(ref s_dbg_pin);
#endif
            _operationHandle = GCHandle.Alloc(this);
        }
```

Maybe related to issue [#11674](https://github.com/dotnet/corefx/issues/11674)

**Comment by davidsh** [comment]
cc: @stephentoub 

@baal2000 Thanks for finding that bug!

**Comment by baal2000** [comment]
you are welcome.
