### ISSUE TITLE
Stream newStream = myRequest.GetRequestStream(); not working in ASP core

### ISSUE THREAD

**Issue by rsen253** [dotnet/corefx#11697]
Unable to solve myRequest.GetRequestStream() in ASp core and newStream.Write is also not available

**Comment by svick** [comment]
If you look at [the documentation for `WebRequest`](https://docs.microsoft.com/en-us/dotnet/core/api/system.net.webrequest), you'll notice that [it contains `GetRequestStreamAsync()`](https://docs.microsoft.com/en-us/dotnet/core/api/system.net.webrequest#System_Net_WebRequest_GetRequestStreamAsync), but not `GetRequestStream()`. So you'll have to use `Stream newStream = await myRequest.GetRequestStreamAsync();`.

As for [`Stream`](https://docs.microsoft.com/en-us/dotnet/core/api/system.io.stream), [it does contain `Write()`](https://docs.microsoft.com/en-us/dotnet/core/api/system.io.stream#System_IO_Stream_Write_System_Byte___System_Int32_System_Int32_), so I'm not sure what could the problem be there. If you still have that problem, could you show your code, along with the error you're getting?

**Comment by rsen253** [comment]
Ok got that . Thank you all
