### ISSUE TITLE
IEnumerator.Current does not throw after hitting the end of the collection.

### ISSUE THREAD

**Issue by alexperovich** [dotnet/corefx#1170]
This issue is in the `List<T>.Enumerator` class. When the collection is enumerated to then end and then modified, accessing `IEnumerator.Current` returns `default(T)` rather than throwing. According to the [documentation](https://msdn.microsoft.com/en-us/library/vstudio/system.collections.ienumerator.current%28v=vs.100%29.aspx) it should throw.

Simple Test case:

``` CSharp
var list = new List<int>{0,1};
var enumerator = ((IEnumerable)list).GetEnumerator();
while (enumerator.MoveNext()){}
list.Add(2);
Assert.Throws<InvalidOperationException>(() => enumerator.Current);
```

This test fails currently with `enumerator.Current` returning 0.

**Comment by Maxwe11** [comment]
MSDN:
>If changes are made to the collection, such as adding, modifying, or deleting elements, the enumerator is irrecoverably invalidated and the next call to MoveNext or Reset throws an InvalidOperationException. If the collection is modified between MoveNext and Current, Current returns the element that it is set to, even if the enumerator is already invalidated.

So why it should throw?

**Comment by alexperovich** [comment]
The enumerator has already hit the end of the collection. So current is set to an invalid element. It should throw because it is not set to a valid element.
There is a dissagreement between the segment you quoted and the following.
>Current also throws an exception if the last call to MoveNext returned false, which indicates the end of the collection.
My perspective is that Current has been set to a state that throws an exception. Modifying the collection shouldn't change that.

**Comment by KrzysztofCwalina** [comment]
This is a performance optimization. If we wanted Current to throw, we would have to do a check in get_Current. Such check would hurt performance in 99+% of cases where people use enumerators through foreach statement (which will never call Current past the end of the list). 

If you are arguing that we should fix the docs, then I tend to agree. If you are arguing that we should add the check, then I am not sure it's a good tradeoff. It will be a significant perf hit in some scenarios.

**Comment by alexperovich** [comment]
We should probably fix the docs. Though for non generic `IEnumerable` we already check that the enumerator is not in the bounds of the list, and the non generic `IEnumerator` will almost never be used in foreach loops unless the developer explicitly casts to `IEnumerable`

**Comment by ellismg** [comment]
Let's just do the documentation update.

**Comment by joshfree** [comment]
@rpetrusha could you follow up here?

**Comment by JonHanna** [comment]
Just found this after opening an issue requesting the same doc changes. I think the docs on when `IEnumerator<T>.Current` is undefined are fine, so copying those to `IEnumerator.Current` would be good.

**Comment by karelz** [comment]
@alexperovich @ianhays @safern can you please list the affected MSDN docs and suggest text change? Thanks!

@mairaw will be able to help us get the docs changed.

**Comment by alexperovich** [comment]
The affected docs are `IEnumerator.Current` (https://msdn.microsoft.com/en-us/library/system.collections.ienumerator.current(v=vs.110).aspx) and `IEnumerator<T>.Current` (https://msdn.microsoft.com/en-us/library/58e146b7(v=vs.110).aspx)

I believe the consensus was that the "Remarks" section of `IEnumerator<T>.Current` be copied to the same section in the docs for `IEnumerator.Current`. For consistency we may want to copy the summary and property value descriptions as well. The description for `IEnumerator.Current` (The current element in the collection.) is not entirely accurate.

**Comment by karelz** [comment]
Thanks.
@mairaw assigned to you - please let us know if you need more details or if it is not clear. Thank you!

**Comment by mairaw** [comment]
Thanks @karelz. I've made the updates to https://msdn.microsoft.com/en-US/library/khfze649(VS.110).aspx. Let me know if it looks ok and we can close this issue.

**Comment by safern** [comment]
Thanks @mairaw looks good :)
