### ISSUE TITLE
Seg fault in System.Drawing.Primitives.Tests on CentOS in CI

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#11718]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/dev_api/job/centos7.1_release_prtest/85/

Happened while testing #11688, but this is just adding a new Socket API, so it probably didn't cause this failure.

**Comment by stephentoub** [comment]
cc: @adityamandaleeka

**Comment by danmosemsft** [comment]
Not much can be done here without a dump or even console output. Sepideh is working to get the dump service working so maybe close this issue and a future hit will get a dump.

**Comment by alexperovich** [comment]
Closing as nothing can be done here. Reopen if we can get a dump or clean repro.
