### ISSUE TITLE
Port IndentedCodeWriter

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#11727]
This is the only part of System.CodeDOM currently in .NET Standard.

```
F:System.CodeDom.Compiler.IndentedTextWriter.DefaultTabString
M:System.CodeDom.Compiler.IndentedTextWriter.#ctor(System.IO.TextWriter)
M:System.CodeDom.Compiler.IndentedTextWriter.#ctor(System.IO.TextWriter,System.String)
P:System.CodeDom.Compiler.IndentedTextWriter.Indent
M:System.CodeDom.Compiler.IndentedTextWriter.get_Indent
M:System.CodeDom.Compiler.IndentedTextWriter.set_Indent(System.Int32)
P:System.CodeDom.Compiler.IndentedTextWriter.InnerWriter
M:System.CodeDom.Compiler.IndentedTextWriter.get_InnerWriter
M:System.CodeDom.Compiler.IndentedTextWriter.OutputTabs
M:System.CodeDom.Compiler.IndentedTextWriter.WriteLineNoTabs(System.String)
```

**Comment by stephentoub** [comment]
What assembly do we want this in?  I hadn't realized this was being ported, and I ended up doing so as part of a side project to bring System.CodeDom to corefx.  I can separate it out from that to satisfy this issue, I just need to know where to put it.

**Comment by joperezr** [comment]
I haven't started this one yet so don't know where it should go either. @weshaggard I don't see this in dotnet/standard repo yet, do we know where are we going to put it?

**Comment by weshaggard** [comment]
While the namespace is CodeDom it is really a text writer so we should just put it in System.IO with the other text writers.

**Comment by stephentoub** [comment]
Ok, I'll add it there.  Just need to separate it out of my project and I'll submit a PR.
