### ISSUE TITLE
CopyTo should be overriden in MemoryStream

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#11723]
I just made a change in CoreCLR (dotnet/coreclr#7131) that overrides `MemoryStream.CopyTo` since that method of Stream is now virtual. However it looks like since the copy of `MemoryStream` in here (which is used in corert) is separated from its parent which lives in [corert itself](https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/IO/Stream.cs), the compiler will not be able to override the method here since it is not yet virtual in the contracts. When it is, the changes from that PR should be ported here.

@stephentoub @jkotas

**Comment by jkotas** [comment]
There is delay in when the CoreRT System.Private.CoreLib that corefx builds against is updated - it is not as fast as for CoreCLR.

@jamesqo Thank you for opening the issue to track this! If you would like to, you can submit a PR with the change - it will be failing until the CoreLib update happens.

cc @SedarG

**Comment by jamesqo** [comment]
@jkotas I realized there is another thing, too-- the PR makes use of `ValidateCopyToArguments` which is an internal method on Stream. What should be done there?

Also, curious-- why do we have Stream in CoreRT but MemoryStream here?

**Comment by jkotas** [comment]
> What should be done there?

Duplicate the method, or create a shared copy under src\Common that can be used by any corefx stream implementation.

> why do we have Stream in CoreRT but MemoryStream here?

Stream is exchange type that a lot of API signatures use, thus it needs to be in the lowest level of the runtime. The concrete Stream implementations like MemoryStream can be in layer above.
