### ISSUE TITLE
AllowAutoRedirect is missing on HttpWebRequest

### ISSUE THREAD

**Issue by mythz** [dotnet/corefx#11738]
Please add the missing `AllowAutoRedirect` feature on [HttpWebRequest](https://github.com/dotnet/corefx/blob/master/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs) so we can support both existing .NET and new .NET Core code bases that uses this feature, thanks.

**Comment by davidsh** [comment]
cc: @CIPop @stephentoub 

This is already planned for 1.2.  All API surface area for HttpWebRequest will be added back to match .NET Framework (Desktop).

**Comment by davidsh** [comment]
Part of #11881
