### ISSUE TITLE
Expose CancellationToken For StreamContent

### ISSUE THREAD

**Issue by mglodack** [dotnet/corefx#11739]
Looks like `StreamContent` doesn't publicly expose a constructor with `CancellationToken` support.

https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/StreamContent.cs#L32

Is there any reason for not having that publicly exposed?

**Comment by stephentoub** [comment]
This is a dup of https://github.com/dotnet/corefx/issues/9071.

That ctor was only recently added as part of a bug fix:
https://github.com/dotnet/corefx/pull/9102

**Comment by davidsh** [comment]
Closing as dupe.
