### ISSUE TITLE
System.Runtime.Numerics.Tests fails on machine with decimal symbol differ from "."

### ISSUE THREAD

**Issue by Maxwe11** [dotnet/corefx#1174]
On machine with decimal symbol differ from "." (dot)

	  Discovering: System.Runtime.Numerics.Tests
	  Discovered:  System.Runtime.Numerics.Tests
	  Starting:    System.Runtime.Numerics.Tests
		 System.Numerics.Tests.ToStringTest.RunStandardFormatToStringTests [FAIL]
			Unexpected Exception:Xunit.Sdk.TrueException: Assert.True() Failure
			   at Xunit.Assert.True(Boolean condition)
			   at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, IFormatProvider provider, Boolean expectError, String expectedResult) in d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs:line 1343
			Stack Trace:
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(1352,0): at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, IFormatProvider provider, Boolean expectError, String expectedResult)
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(1301,0): at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, String expectedResult)
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(351,0): at System.Numerics.Tests.ToStringTest.RunStandardFormatToStringTests(Random random, String format, String negativeSign, Int32 percision, StringFormatter formatter)
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(90,0): at System.Numerics.Tests.ToStringTest.RunStandardFormatToStringTests()
		 System.Numerics.Tests.ToStringTest.RunCustomFormatDecimalPoint [FAIL]
			Unexpected Exception:Xunit.Sdk.TrueException: Assert.True() Failure
			   at Xunit.Assert.True(Boolean condition)
			   at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, IFormatProvider provider, Boolean expectError, String expectedResult) in d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs:line 1343
			Stack Trace:
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(1352,0): at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, IFormatProvider provider, Boolean expectError, String expectedResult)
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(1301,0): at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, String expectedResult)
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(397,0): at System.Numerics.Tests.ToStringTest.RunCustomFormatToStringTests(Random random, String format, String negativeSign, Int32 percision, StringFormatter formatter)
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(205,0): at System.Numerics.Tests.ToStringTest.RunCustomFormatDecimalPoint()
		 System.Numerics.Tests.ToStringTest.RunCustomFormatThousandsSeparator [FAIL]
			Unexpected Exception:Xunit.Sdk.TrueException: Assert.True() Failure
			   at Xunit.Assert.True(Boolean condition)
			   at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, IFormatProvider provider, Boolean expectError, String expectedResult) in d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs:line 1343
			Stack Trace:
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(1352,0): at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, IFormatProvider provider, Boolean expectError, String expectedResult)
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(1301,0): at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, String expectedResult)
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(397,0): at System.Numerics.Tests.ToStringTest.RunCustomFormatToStringTests(Random random, String format, String negativeSign, Int32 percision, StringFormatter formatter)
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(213,0): at System.Numerics.Tests.ToStringTest.RunCustomFormatThousandsSeparator()
		 System.Numerics.Tests.ToStringTest.RunCustomFormatNumberScaling [FAIL]
			Unexpected Exception:Xunit.Sdk.TrueException: Assert.True() Failure
			   at Xunit.Assert.True(Boolean condition)
			   at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, IFormatProvider provider, Boolean expectError, String expectedResult) in d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs:line 1343
			Stack Trace:
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(1352,0): at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, IFormatProvider provider, Boolean expectError, String expectedResult)
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(1301,0): at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, String expectedResult)
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(397,0): at System.Numerics.Tests.ToStringTest.RunCustomFormatToStringTests(Random random, String format, String negativeSign, Int32 percision, StringFormatter formatter)
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(223,0): at System.Numerics.Tests.ToStringTest.RunCustomFormatNumberScaling()
		 System.Numerics.Tests.ToStringTest.RunCustomFormatScientificNotation [FAIL]
			Unexpected Exception:Xunit.Sdk.TrueException: Assert.True() Failure
			   at Xunit.Assert.True(Boolean condition)
			   at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, IFormatProvider provider, Boolean expectError, String expectedResult) in d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs:line 1343
			Stack Trace:
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(1352,0): at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, IFormatProvider provider, Boolean expectError, String expectedResult)
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(1301,0): at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, String expectedResult)
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(397,0): at System.Numerics.Tests.ToStringTest.RunCustomFormatToStringTests(Random random, String format, String negativeSign, Int32 percision, StringFormatter formatter)
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(240,0): at System.Numerics.Tests.ToStringTest.RunCustomFormatScientificNotation()
		 System.Numerics.Tests.ToStringTest.RunCustomFormatLiterals [FAIL]
			Unexpected Exception:Xunit.Sdk.TrueException: Assert.True() Failure
			   at Xunit.Assert.True(Boolean condition)
			   at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, IFormatProvider provider, Boolean expectError, String expectedResult) in d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs:line 1343
			Stack Trace:
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(1352,0): at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, IFormatProvider provider, Boolean expectError, String expectedResult)
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(1301,0): at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, String expectedResult)
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(397,0): at System.Numerics.Tests.ToStringTest.RunCustomFormatToStringTests(Random random, String format, String negativeSign, Int32 percision, StringFormatter formatter)
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(275,0): at System.Numerics.Tests.ToStringTest.RunCustomFormatLiterals()
		 System.Numerics.Tests.ToStringTest.RunCustomFormatSeparator [FAIL]
			Unexpected Exception:Xunit.Sdk.TrueException: Assert.True() Failure
			   at Xunit.Assert.True(Boolean condition)
			   at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, IFormatProvider provider, Boolean expectError, String expectedResult) in d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs:line 1343
			Stack Trace:
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(1352,0): at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, IFormatProvider provider, Boolean expectError, String expectedResult)
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(1301,0): at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, String expectedResult)
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(397,0): at System.Numerics.Tests.ToStringTest.RunCustomFormatToStringTests(Random random, String format, String negativeSign, Int32 percision, StringFormatter formatter)
			   d:\Workspace\corefx\src\System.Runtime.Numerics\tests\BigInteger\BigIntegerToStringTests.cs(282,0): at System.Numerics.Tests.ToStringTest.RunCustomFormatSeparator()

/cc @hpshelton

**Comment by hpshelton** [comment]
I can repro this by setting the machine's region to "French (Canada)", but it goes back to at least fb8fb441b3e5414590b8d1af4ec5f52ca52c0dff, shortly after the initial commit to GitHub. It appears that the issue is usage of CurrentUICulture, which usages the application's culture, rather than CurrentCulture, which uses the machine's culture.

**Comment by Maxwe11** [comment]
@hpshelton thanks for investigation. At first look I didn't understand why it fails. Will try fix.

**Comment by hpshelton** [comment]
I can take this one - I already did a find/replace and verified the changes work on multiple languages, but I'll also add a test case to actually sanity test different cultures rather than just system one.

**Comment by Maxwe11** [comment]
@hpshelton okay, but note that test case against system culture should consider that decimal symbol with "friends" (date and time formats, etc) could be changed independently from culture.

**Comment by hpshelton** [comment]
Take a look at https://github.com/dotnet/corefx/pull/1206, and if you think more tests need to be added for custom cultures, let's discuss.
