### ISSUE TITLE
httpclient default proxy

### ISSUE THREAD

**Issue by Kuqd** [dotnet/corefx#11757]
Hello Guys,

Is there a way for httpclient to pick up the default system proxy like http_proxy on linux ? 

For now we are providing a the proxy manually to the httpclient, using the HttpClientHandler class.

Thank you !

**Comment by stephentoub** [comment]
> Is there a way for httpclient to pick up the default system proxy like http_proxy on linux ?

HttpClient on Linux should respect a proxy set in the http_proxy environment variable.  Are you seeing otherwise?

Or are you asking if there's an equivalent on Windows?

**Comment by Kuqd** [comment]
I'm actually seeing it, it's not respecting the proxy, I had to manually set it up.

**Comment by stephentoub** [comment]
> it's not respecting the proxy

How are you setting the environment variable?  Is it set before you launch the application, or are you setting it with Environment.SetEnvironmentVariable once the process has been launched?

You can see we have a test case for this here:
https://github.com/dotnet/corefx/blob/0d3ba29934def851fe35514bfe18ecd5f3b5791e/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.DefaultProxyCredentials.cs#L82

**Comment by Kuqd** [comment]
before I launch the application, I'm going to run more test and get back to you !

**Comment by stephentoub** [comment]
Thanks, @Kuqd.

**Comment by Kuqd** [comment]
I've set the env variable in the supervisor conf and now it's picked up, now I'm just wondering it we can set some bypass also ?

**Comment by stephentoub** [comment]
HttpClient relies on libcurl for such things, so it'll respect any such environment variables that libcurl respects.

**Comment by Kuqd** [comment]
ok thanks the doc says that it support no_proxy.

Thank you !
