### ISSUE TITLE
Reapply changes made to Xml libraries since the move to System.Private.Xml since they got lost in merge from dev/api

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#11768]
When we moved the implementation of Xml from the old contracts into System.Private.Xml, we lost the history since to git's point of view, they are two different files now. The problem is that this move happened in a different branch (dev/xml) so when we merged that back to dev/api and then to master, we lost all of the changes that were made in master after the move. This work item is to track the work that must be done to re-apply these changes back to the files now under System.Private.Xml.

cc: @weshaggard @danmosemsft @krwq @shmao

**Comment by danmosemsft** [comment]
Zhenlan and I discussed this and we agreed that Shin is the best person to fix up the merge issues with XML serialization. Assigning to @shmao. Thanks Shin!

@joperezr are there other issues outside of XML serialization? (src\System.Private.Xml\src\System\Xml\Serialization and src\System.Xml.XmlSerializer) If so, please break out into a new issue for us to take care of.

**Comment by danmosemsft** [comment]
@zhenlan for visibility.

**Comment by joperezr** [comment]
I believe that there are at least 7 libraries where we moved the implementation down to either System.Private.Xml or to System.Private.Xml.Linq. They are:
```
corefx\src\System.Xml.ReaderWriter\src\System.Xml.ReaderWriter.csproj
corefx\src\System.Xml.XDocument\src\System.Xml.XDocument.csproj
corefx\src\System.Xml.XmlDocument\src\System.Xml.XmlDocument.csproj
corefx\src\System.Xml.XmlSerializer\src\System.Xml.XmlSerializer.csproj
corefx\src\System.Xml.XPath\src\System.Xml.XPath.csproj
corefx\src\System.Xml.XPath.XDocument\src\System.Xml.XPath.XDocument.csproj
corefx\src\System.Xml.XPath.XmlDocument\src\System.Xml.XPath.XmlDocument.csproj
```

**Comment by joperezr** [comment]
we would need to track all changes made in those contracts in master prior to the merge, and make sure we apply them back. I agree where we should probably have a different issue tracking each of the different libraries.

**Comment by danmosemsft** [comment]
Alright, I broke a new issue out for the libraries other than XML serialization. https://github.com/dotnet/corefx/issues/11806
