### ISSUE TITLE
Source Breaking change in System.Runtime 4.1 with MemberInfo.GetCustomAttributes

### ISSUE THREAD

**Issue by alexperovich** [dotnet/corefx#11764]
When upgrading package versions of System.Runtime from 4.0 to 4.1 the following code will have errors on both lines when it compiled successfully before.
```C#
Attribute[] attrs1 = typeof(int).GetCustomAttributes(true).ToArray();
Attribute[] attrs2 = typeof(int).GetCustomAttributes(typeof(SerializableAttribute), true).ToArray();
```
This is caused by two new instance methods on MemberInfo that hide the extension methods in CustomAttributeExtensions. The new methods return `object[]` when the extension methods return `IEnumerable<Attribute>`

To maintain compatibility with desktop we cannot change the return type of the new members to match. We need to document the breaking change.

**Comment by alexperovich** [comment]
@weshaggard

**Comment by weshaggard** [comment]
Thanks for point this out. During some review we actually talked about this exact issue and I believe to workaround it we decided to make the versions on the actual types that return object[] array be explicit interface implementations.

@terrajobst what's your thought on this?

**Comment by alexperovich** [comment]
Would it work to remove the object[] overloads from the reference assembly and leave them in the implementation? That way assemblies built against them would see them at runtime but the compiler would not.

**Comment by weshaggard** [comment]
Marking as api-ready-for-review to discuss the nature of this breaking change.

**Comment by terrajobst** [comment]
There is no way to make both sides compatible: either we break the source code written against the .NET Framework style APIs or we break the source code written against the contracts. However, it'also a binary breaking change.

It seems the best approach is:

* Ensure source written against and binaries compiled against .NET Framework work with .NET Standard
* Ensure binaries compiled against the contracts work with .NET Standard

This will only break the source code written against the contracts, calling `GetCustomAttributes()` and expecting to get back an `IEnumerable<Attribute>`.
