### ISSUE TITLE
DotNetCore.1.0.1-SDK installation onto Windows 2008

### ISSUE THREAD

**Issue by malachib** [dotnet/corefx#11772]
DotNetCore.1.0.1-SDK.1.0.0.Preview2-003131-x64 specifically

Using Windows Server "6.0.6002".  Struggled to get an install as it couldn't acquire/install vs_redist.x64.exe, so I manually pulled it down from http://go.microsoft.com/fwlink/?LinkID=615460&amp;clcid=0x409 as per logs and the install the completed without complaint.

However, when attempting to start `dotnet --version` from command line, I get a dialog box claiming "The procedure entry point ResolveLocaleName could not be located in the dynamic link library KERNEL32.dll"

I was banking on running .NET Core on this specific server, now I am very worried I won't be able to.  Can anyone help?

**Comment by qmfrederik** [comment]
Have a look at https://github.com/dotnet/core/blob/master/roadmap.md#technology-roadmaps, Windows Server 2008 R2 is oldest version of Windows Server which is supported, which means you probably won't be able to run .NET Core on that server.

**Comment by malachib** [comment]
Thank you for the quick response. I will find a workaround then; any clues as to why vs_redist.x64.exe becomes a manual step?  I just installed on a Windows 2008 R2 server and the manual step was still required

**Comment by mikeharder** [comment]
@malachib: See https://github.com/dotnet/cli/issues/4190 for more explanation.

**Comment by tarekgh** [comment]
looks there is no action needed with this issue. closing it,
