### ISSUE TITLE
OutOfMemoryException in System.Numerics.Tests.logTest.RunLargeValueLogTests on Ubuntu

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#11771]
Running OuterLoop Ubuntu14.04 Debug in CI for #11765:
```
15:22:12      System.Numerics.Tests.logTest.RunLargeValueLogTests [FAIL]
15:22:12         System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
15:22:12         Stack Trace:
15:22:12               at System.Numerics.BigInteger.op_LeftShift(BigInteger value, Int32 shift)
15:22:12               at System.Numerics.Tests.logTest.LargeValueLogTests(Int32 startShift, Int32 bigShiftLoopLimit, Int32 smallShift, Int32 smallShiftLoopLimit)
15:22:12               at System.Numerics.Tests.logTest.RunLargeValueLogTests()
```

**Comment by ericeil** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu14.04_debug_prtest/9/

**Comment by karelz** [comment]
@mellinoe can you please take a look?

**Comment by mellinoe** [comment]
@karelz It looks like the machine ran out of memory. I'll look into lowering the size of the string data used in the future.

**Comment by mellinoe** [comment]
The tests ends up taking about 7 GB of memory on my machine, so we can probably lower that to avoid this in the future.

**Comment by danmosemsft** [comment]
@mellinoe could you take a look please as we are trying to get the test run clean. If you don't have time then please disable the test with this issue #.
