### ISSUE TITLE
Port remaining types/members in System.Net.Sockets

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#11788]
# Missing types
- [x] System.Net.Sockets.ProtocolFamily
- [x] System.Net.Sockets.SocketInformation
- [x] System.Net.Sockets.SocketInformationOptions
- [x] System.Net.Sockets.TransmitFileOptions

# Missing members
- [x] System.Net.Sockets.NetworkStream.#ctor
- [x] System.Net.Sockets.NetworkStream.#ctor
- [x] System.Net.Sockets.NetworkStream.BeginRead
- [x] System.Net.Sockets.NetworkStream.BeginWrite
- [x] System.Net.Sockets.NetworkStream.Close
- [x] System.Net.Sockets.NetworkStream.EndRead
- [x] System.Net.Sockets.NetworkStream.EndWrite
- [x] System.Net.Sockets.NetworkStream.get_Readable
- [x] System.Net.Sockets.NetworkStream.get_Socket
- [x] System.Net.Sockets.NetworkStream.get_Writeable
- [x] System.Net.Sockets.NetworkStream.set_Readable
- [x] System.Net.Sockets.NetworkStream.set_Writeable
- [x] System.Net.Sockets.Socket.#ctor
- [x] System.Net.Sockets.Socket.BeginAccept
- [x] System.Net.Sockets.Socket.BeginAccept
- [x] System.Net.Sockets.Socket.BeginAccept
- [x] System.Net.Sockets.Socket.BeginConnect
- [x] System.Net.Sockets.Socket.BeginConnect
- [x] System.Net.Sockets.Socket.BeginConnect
- [x] System.Net.Sockets.Socket.BeginConnect
- [x] System.Net.Sockets.Socket.BeginDisconnect
- [x] System.Net.Sockets.Socket.BeginReceive
- [x] System.Net.Sockets.Socket.BeginReceive
- [x] System.Net.Sockets.Socket.BeginReceive
- [x] System.Net.Sockets.Socket.BeginReceive
- [x] System.Net.Sockets.Socket.BeginReceiveFrom
- [x] System.Net.Sockets.Socket.BeginReceiveMessageFrom
- [x] System.Net.Sockets.Socket.BeginSend
- [x] System.Net.Sockets.Socket.BeginSend
- [x] System.Net.Sockets.Socket.BeginSend
- [x] System.Net.Sockets.Socket.BeginSend
- [ ] System.Net.Sockets.Socket.BeginSendFile
- [ ] System.Net.Sockets.Socket.BeginSendFile
- [x] System.Net.Sockets.Socket.BeginSendTo
- [x] System.Net.Sockets.Socket.Close
- [x] System.Net.Sockets.Socket.Close
- [x] System.Net.Sockets.Socket.Disconnect
- [x] System.Net.Sockets.Socket.DisconnectAsync
- [x] System.Net.Sockets.Socket.DuplicateAndClose
- [x] System.Net.Sockets.Socket.EndAccept
- [x] System.Net.Sockets.Socket.EndAccept
- [x] System.Net.Sockets.Socket.EndAccept
- [x] System.Net.Sockets.Socket.EndConnect
- [x] System.Net.Sockets.Socket.EndDisconnect
- [x] System.Net.Sockets.Socket.EndReceive
- [x] System.Net.Sockets.Socket.EndReceive
- [x] System.Net.Sockets.Socket.EndReceiveFrom
- [x] System.Net.Sockets.Socket.EndReceiveMessageFrom
- [x] System.Net.Sockets.Socket.EndSend
- [x] System.Net.Sockets.Socket.EndSend
- [x] System.Net.Sockets.Socket.EndSendFile
- [x] System.Net.Sockets.Socket.EndSendTo
- [x] System.Net.Sockets.Socket.get_Handle
- [x] System.Net.Sockets.Socket.get_SupportsIPv4
- [x] System.Net.Sockets.Socket.get_SupportsIPv6
- [x] System.Net.Sockets.Socket.get_UseOnlyOverlappedIO
- [ ] System.Net.Sockets.Socket.SendFile
- [ ] System.Net.Sockets.Socket.SendFile
- [x] System.Net.Sockets.Socket.set_UseOnlyOverlappedIO
- [x] System.Net.Sockets.SocketAsyncEventArgs.get_DisconnectReuseSocket
- [x] System.Net.Sockets.SocketAsyncEventArgs.set_DisconnectReuseSocket
- [ ] System.Net.Sockets.SocketException.#ctor
- [ ] System.Net.Sockets.SocketException.get_ErrorCode
- [x] System.Net.Sockets.TcpClient.#ctor
- [x] System.Net.Sockets.TcpClient.#ctor
- [x] System.Net.Sockets.TcpClient.BeginConnect
- [x] System.Net.Sockets.TcpClient.BeginConnect
- [x] System.Net.Sockets.TcpClient.BeginConnect
- [x] System.Net.Sockets.TcpClient.Close
- [x] System.Net.Sockets.TcpClient.Connect
- [x] System.Net.Sockets.TcpClient.Connect
- [x] System.Net.Sockets.TcpClient.Connect
- [x] System.Net.Sockets.TcpClient.Connect
- [x] System.Net.Sockets.TcpClient.EndConnect
- [x] System.Net.Sockets.TcpClient.get_Client
- [x] System.Net.Sockets.TcpClient.set_Client
- [x] System.Net.Sockets.TcpListener.#ctor
- [x] System.Net.Sockets.TcpListener.AcceptSocket
- [x] System.Net.Sockets.TcpListener.AcceptTcpClient
- [x] System.Net.Sockets.TcpListener.BeginAcceptSocket
- [x] System.Net.Sockets.TcpListener.BeginAcceptTcpClient
- [ ] System.Net.Sockets.TcpListener.Create
- [x] System.Net.Sockets.TcpListener.EndAcceptSocket
- [x] System.Net.Sockets.TcpListener.EndAcceptTcpClient
- [x] System.Net.Sockets.UdpClient.#ctor
- [ ] System.Net.Sockets.UdpClient.AllowNatTraversal
- [x] System.Net.Sockets.UdpClient.BeginReceive
- [x] System.Net.Sockets.UdpClient.BeginSend
- [x] System.Net.Sockets.UdpClient.BeginSend
- [x] System.Net.Sockets.UdpClient.BeginSend
- [x] System.Net.Sockets.UdpClient.Close
- [x] System.Net.Sockets.UdpClient.Connect
- [x] System.Net.Sockets.UdpClient.Connect
- [x] System.Net.Sockets.UdpClient.Connect
- [x] System.Net.Sockets.UdpClient.EndReceive
- [x] System.Net.Sockets.UdpClient.EndSend
- [x] System.Net.Sockets.UdpClient.get_Client
- [x] System.Net.Sockets.UdpClient.Receive
- [x] System.Net.Sockets.UdpClient.Send
- [x] System.Net.Sockets.UdpClient.Send
- [x] System.Net.Sockets.UdpClient.Send
- [x] System.Net.Sockets.UdpClient.SendAsync
- [x] System.Net.Sockets.UdpClient.set_Client

**Comment by stephentoub** [comment]
I'm renaming this to just System.Net.Sockets.  As of https://github.com/dotnet/corefx/pull/11694, I believe System.Net.WebSockets and System.Net.WebSockets.Client are done.  If I missed anything, it can be handled separately.

**Comment by ericeil** [comment]
Added checklist to track progress.  Most of the APM methods, plus the `Close` methods, were already added with #11765.

**Comment by ericeil** [comment]
Also missing:
```csharp
    public struct IPPacketInformation {
        public static bool operator ==(IPPacketInformation packetInformation1left, IPPacketInformation packetInformation2right);
        public static bool operator !=(IPPacketInformation packetInformation1left, IPPacketInformation packetInformation2right);
    }

    public enum SocketFlags {
        MaxIOVectorLength = 16,
    }
```

**Comment by ericeil** [comment]
Created separate issues to track the few remaining items.
