### ISSUE TITLE
Matrix4x4 - more useful public properties

### ISSUE THREAD

**Issue by EmptyKeys** [dotnet/corefx#118]
Forward, Backward, Up, Down, Left, Right public properties for Matrix4x4

**Comment by ellismg** [comment]
@EmptyKeys If you are still interested in this, can you take a stab at writing up a speclet for all the new methods you are proposing?  We can then start discussing the changes in earnest both on GitHub and eventually in an API review.

**Comment by mellinoe** [comment]
Before I close this, I'd like to echo what Matt said above. If you still feel strongly about this, then please open a new issue with a fleshed out speclet following our guidelines. And keep in mind the considerations around handedness, etc. above.
