### ISSUE TITLE
Port some missing remoting types/members

### ISSUE THREAD

**Issue by kouvel** [dotnet/corefx#11809]
- [x] T:System.ContextBoundObject
- [x] M:System.ContextBoundObject.#ctor
- [ ] T:System.ContextMarshalException
- [ ] M:System.ContextMarshalException.#ctor
- [ ] M:System.ContextMarshalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
- [ ] M:System.ContextMarshalException.#ctor(System.String)
- [ ] M:System.ContextMarshalException.#ctor(System.String,System.Exception)
- [ ] T:System.ContextStaticAttribute
- [ ] M:System.ContextStaticAttribute.#ctor
- [x] T:System.MarshalByRefObject
- [x] M:System.MarshalByRefObject.#ctor
~~- [x] M:System.MarshalByRefObject.CreateObjRef(System.Type)~~
- [x] M:System.MarshalByRefObject.GetLifetimeService
- [x] M:System.MarshalByRefObject.InitializeLifetimeService
- [x] M:System.MarshalByRefObject.MemberwiseClone(System.Boolean)

- [ ] T:System.Reflection.AssemblyNameProxy
- [ ] M:System.Reflection.AssemblyNameProxy.#ctor
- [ ] M:System.Reflection.AssemblyNameProxy.GetAssemblyName(System.String)

~~- [x] T:System.Runtime.Remoting.IChannelInfo~~
~~- [x] P:System.Runtime.Remoting.IChannelInfo.ChannelData~~
~~- [x] M:System.Runtime.Remoting.IChannelInfo.get_ChannelData~~
~~- [x] M:System.Runtime.Remoting.IChannelInfo.set_ChannelData(System.Object[])~~
~~- [x] T:System.Runtime.Remoting.IEnvoyInfo~~
~~- [x] P:System.Runtime.Remoting.IEnvoyInfo.EnvoySinks~~
~~- [x] M:System.Runtime.Remoting.IEnvoyInfo.get_EnvoySinks~~
~~- [x] M:System.Runtime.Remoting.IEnvoyInfo.set_EnvoySinks(System.Runtime.Remoting.Messaging.IMessageSink)~~
~~- [x] T:System.Runtime.Remoting.IRemotingTypeInfo~~
~~- [x] M:System.Runtime.Remoting.IRemotingTypeInfo.CanCastTo(System.Type,System.Object)~~
~~- [x] M:System.Runtime.Remoting.IRemotingTypeInfo.get_TypeName~~
~~- [x] M:System.Runtime.Remoting.IRemotingTypeInfo.set_TypeName(System.String)~~
~~- [x] P:System.Runtime.Remoting.IRemotingTypeInfo.TypeName~~
- [x] T:System.Runtime.Remoting.Messaging.Header
- [x] M:System.Runtime.Remoting.Messaging.Header.#ctor(System.String,System.Object)
- [x] M:System.Runtime.Remoting.Messaging.Header.#ctor(System.String,System.Object,System.Boolean)
- [x] M:System.Runtime.Remoting.Messaging.Header.#ctor(System.String,System.Object,System.Boolean,System.String)
- [x] F:System.Runtime.Remoting.Messaging.Header.HeaderNamespace
- [x] F:System.Runtime.Remoting.Messaging.Header.MustUnderstand
- [x] F:System.Runtime.Remoting.Messaging.Header.Name
- [x] F:System.Runtime.Remoting.Messaging.Header.Value
- [x] T:System.Runtime.Remoting.Messaging.HeaderHandler
- [x] M:System.Runtime.Remoting.Messaging.HeaderHandler.#ctor(System.Object,System.IntPtr)
- [x] M:System.Runtime.Remoting.Messaging.HeaderHandler.BeginInvoke(System.Runtime.Remoting.Messaging.Header[],System.AsyncCallback,System.Object)
- [x] M:System.Runtime.Remoting.Messaging.HeaderHandler.EndInvoke(System.IAsyncResult)
- [x] M:System.Runtime.Remoting.Messaging.HeaderHandler.Invoke(System.Runtime.Remoting.Messaging.Header[])
- [x] T:System.Runtime.Remoting.Messaging.IMessage
- [x] M:System.Runtime.Remoting.Messaging.IMessage.get_Properties
- [x] P:System.Runtime.Remoting.Messaging.IMessage.Properties

~~- [x] T:System.Runtime.Remoting.Messaging.IMessageCtrl~~
~~- [x] M:System.Runtime.Remoting.Messaging.IMessageCtrl.Cancel(System.Int32)~~
~~- [x] T:System.Runtime.Remoting.Messaging.IMessageSink~~
~~- [x] M:System.Runtime.Remoting.Messaging.IMessageSink.AsyncProcessMessage(System.Runtime.Remotin- [ ]g.Messaging.IMessage,System.Runtime.Remoting.Messaging.IMessageSink)~~
~~- [x] M:System.Runtime.Remoting.Messaging.IMessageSink.get_NextSink~~
~~- [x] P:System.Runtime.Remoting.Messaging.IMessageSink.NextSink~~
~~- [x] M:System.Runtime.Remoting.Messaging.IMessageSink.SyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage)~~
- [x] T:System.Runtime.Remoting.Messaging.IMethodCallMessage
- [x] M:System.Runtime.Remoting.Messaging.IMethodCallMessage.get_InArgCount
- [x] M:System.Runtime.Remoting.Messaging.IMethodCallMessage.get_InArgs
- [x] M:System.Runtime.Remoting.Messaging.IMethodCallMessage.GetInArg(System.Int32)
- [x] M:System.Runtime.Remoting.Messaging.IMethodCallMessage.GetInArgName(System.Int32)
- [x] P:System.Runtime.Remoting.Messaging.IMethodCallMessage.InArgCount
- [x] P:System.Runtime.Remoting.Messaging.IMethodCallMessage.InArgs
- [x] T:System.Runtime.Remoting.Messaging.IMethodMessage
- [x] P:System.Runtime.Remoting.Messaging.IMethodMessage.ArgCount
- [x] P:System.Runtime.Remoting.Messaging.IMethodMessage.Args
- [x] M:System.Runtime.Remoting.Messaging.IMethodMessage.get_ArgCount
- [x] M:System.Runtime.Remoting.Messaging.IMethodMessage.get_Args
- [x] M:System.Runtime.Remoting.Messaging.IMethodMessage.get_HasVarArgs
- [x] M:System.Runtime.Remoting.Messaging.IMethodMessage.get_LogicalCallContext
- [x] M:System.Runtime.Remoting.Messaging.IMethodMessage.get_MethodBase
- [x] M:System.Runtime.Remoting.Messaging.IMethodMessage.get_MethodName
- [x] M:System.Runtime.Remoting.Messaging.IMethodMessage.get_MethodSignature
- [x] M:System.Runtime.Remoting.Messaging.IMethodMessage.get_TypeName
- [x] M:System.Runtime.Remoting.Messaging.IMethodMessage.get_Uri
- [x] M:System.Runtime.Remoting.Messaging.IMethodMessage.GetArg(System.Int32)
- [x] M:System.Runtime.Remoting.Messaging.IMethodMessage.GetArgName(System.Int32)
- [x] P:System.Runtime.Remoting.Messaging.IMethodMessage.HasVarArgs
- [x] P:System.Runtime.Remoting.Messaging.IMethodMessage.LogicalCallContext
- [x] P:System.Runtime.Remoting.Messaging.IMethodMessage.MethodBase
- [x] P:System.Runtime.Remoting.Messaging.IMethodMessage.MethodName
- [x] P:System.Runtime.Remoting.Messaging.IMethodMessage.MethodSignature
- [x] P:System.Runtime.Remoting.Messaging.IMethodMessage.TypeName
- [x] P:System.Runtime.Remoting.Messaging.IMethodMessage.Uri
- [x] T:System.Runtime.Remoting.Messaging.IRemotingFormatter
- [x] M:System.Runtime.Remoting.Messaging.IRemotingFormatter.Deserialize(System.IO.Stream,System.Runtime.Remoting.Messaging.HeaderHandler)
- [x] M:System.Runtime.Remoting.Messaging.IRemotingFormatter.Serialize(System.IO.Stream,System.Object,System.Runtime.Remoting.Messaging.Header[])
- [ ] T:System.Runtime.Remoting.Messaging.LogicalCallContext
- [ ] M:System.Runtime.Remoting.Messaging.LogicalCallContext.Clone
- [ ] M:System.Runtime.Remoting.Messaging.LogicalCallContext.FreeNamedDataSlot(System.String)
- [ ] M:System.Runtime.Remoting.Messaging.LogicalCallContext.get_HasInfo
- [ ] M:System.Runtime.Remoting.Messaging.LogicalCallContext.GetData(System.String)
- [ ] M:System.Runtime.Remoting.Messaging.LogicalCallContext.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
- [ ] P:System.Runtime.Remoting.Messaging.LogicalCallContext.HasInfo
- [ ] M:System.Runtime.Remoting.Messaging.LogicalCallContext.SetData(System.String,System.Object)
~~- [x] T:System.Runtime.Remoting.ObjRef~~
~~- [x] M:System.Runtime.Remoting.ObjRef.#ctor~~
~~- [x] M:System.Runtime.Remoting.ObjRef.#ctor(System.MarshalByRefObject,System.Type)~~
~~- [x] M:System.Runtime.Remoting.ObjRef.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)~~
~~- [x] P:System.Runtime.Remoting.ObjRef.ChannelInfo~~
~~- [x] P:System.Runtime.Remoting.ObjRef.EnvoyInfo~~
~~- [x] M:System.Runtime.Remoting.ObjRef.get_ChannelInfo~~
~~- [x] M:System.Runtime.Remoting.ObjRef.get_EnvoyInfo~~
~~- [x] M:System.Runtime.Remoting.ObjRef.get_TypeInfo~~
~~- [x] M:System.Runtime.Remoting.ObjRef.get_URI~~
~~- [x] M:System.Runtime.Remoting.ObjRef.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)~~
~~- [x] M:System.Runtime.Remoting.ObjRef.GetRealObject(System.Runtime.Serialization.StreamingContext)
~~- [x] M:System.Runtime.Remoting.ObjRef.IsFromThisAppDomain~~
~~- [x] M:System.Runtime.Remoting.ObjRef.IsFromThisProcess~~
~~- [x] M:System.Runtime.Remoting.ObjRef.set_ChannelInfo(System.Runtime.Remoting.IChannelInfo)~~
~~- [x] M:System.Runtime.Remoting.ObjRef.set_EnvoyInfo(System.Runtime.Remoting.IEnvoyInfo)~~
~~- [x] M:System.Runtime.Remoting.ObjRef.set_TypeInfo(System.Runtime.Remoting.IRemotingTypeInfo)~~
~~- [x] M:System.Runtime.Remoting.ObjRef.set_URI(System.String)~~
~~- [x] P:System.Runtime.Remoting.ObjRef.TypeInfo
~~- [x] P:System.Runtime.Remoting.ObjRef.URI~~

**Comment by jkotas** [comment]
@ramarag 

- The transitive closure of MarshalByRefObject has to go into System.Runtime (https://github.com/dotnet/standard/pull/13/files), impl in corelib
- ContextBoundObject should to System.Runtime.Extensions, impl in corefx repo
- AssemblyNameProxy should be moved from System.Runtime to System.Runtime.Extensions (it belongs together with AppDomain, etc.)
- The transitive closure of IRemotingFormatter (https://github.com/dotnet/standard/pull/14/files) should go to System.Runtime.Serialization.Formatters, impl in corefx repo

**Comment by jkotas** [comment]
Let me know if any of this is not working out...

**Comment by ramarag** [comment]
@jkotas  the following types are not part of closure of the above APIs. Should i put them in System.Runtime.Extensions ?
System.Runtime.Remoting.Messaging.IMethodCallMessage
System.Runtime.Remoting.Messaging.IMethodMessage
System.Runtime.Remoting.LogicalContext
System.ContextStaticAttribute
System.ContextMarshalException

**Comment by jkotas** [comment]
> Should i put them in System.Runtime.Extensions ?

Sounds reasonable. Also, could you please move Header to System.Runtime.Exceptions as well? (Fix TODO at https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Serialization.Formatters/src/System/TemporaryStubs.cs#L97).

**Comment by ramarag** [comment]
@jkotas System.Runtime.Remoting.Messaging.Header forms part of the closure of IRemotingFormatter.
do i still it move to system.runtime.extensions from  System.Runtime.Serialization.Formatters?

**Comment by jkotas** [comment]
All `System.Runtime.Remoting.Messaging.*` should be together. You can either add all of it to `System.Runtime.Serialization.Formatters` or to `System.Runtime.Extensions`. Both options are fine with me, `System.Runtime.Extensions` options is probably slightly better.

@stephentoub @weshaggard Do you have an opinion?

**Comment by ramarag** [comment]
@jkotas @weshaggard  If MarshalByRefObject is be implemented in S.P.Corelib, should we remove 
 public virtual ObjRef CreateObjRef(Type requestedType) from the standard

As ObjRef pulls in a quite a bit of cruft that inturn would need to be pulled into  S.P.Corelib ?

**Comment by jkotas** [comment]
This was discussed in https://github.com/dotnet/standard/issues/7. According to https://github.com/dotnet/standard/pull/13/, it should be 5 interfaces and 1 class. Is it what you see as well?

I agree that the closure is not pretty and it feels very ad-hoc. It does not feel we are doing the right thing by including it.

@ramarag Could you please find out how many apps override MarshalByRefObject.CreateObjRef? If it is zero, I think we should reconsider.

**Comment by stephentoub** [comment]
> @stephentoub @weshaggard Do you have an opinion?

System.Runtime.Extensions seems fine to me.  As for CreateObjRef, IIRC it's practically never overridden; if the closure it brings in is really problematic, seems justifiable to leave it out.

**Comment by weshaggard** [comment]
>@ramarag Could you please find out how many apps override MarshalByRefObject.CreateObjRef? If it is zero, I think we should reconsider.

Even if the usage is zero in our data-sets we decided to keep those because otherwise there would be no way to implement them on top of netstandard. If we were going to remove that member and the closure we might as well remove MarshalByRefObject itself. I would prefer we just take that small closure of interfaces and put them in System.Runtime with MarshalByRefObject.

**Comment by jkotas** [comment]
> keep those because otherwise there would be no way to implement them on top of netstandard

If you want to use esoteric features like overriding CreateObjRef, you are very unlikely to be able to just compile against netstandard because of there will be too much other stuff missing to build a complete solution.

**Comment by weshaggard** [comment]
>If you want to use esoteric features like overriding CreateObjRef, you are very unlikely to be able to just compile against netstandard because of there will be too much other stuff missing to build a complete solution.

My assumption is that the majority of the other stuff (modulo AppDomain) can be implemented on top of netstandard. I also don't think adding those few interfaces which have no real implementation actually adds much. Xamarian has already done this work also.

**Comment by jkotas** [comment]
I expect that we are going to be adding new methods, including virtual methods, to the core library. Since netstandard will be behind or even never have those, you won't be able to compile against netstandard to use them either. Both two cases (never used legacy, and new stuff) can be on the same plan.

I agree that it does not a disaster to add these interfaces but it is still substantial number of methods.  I believe we are trying to be perfect in wrong way - it adds negative value.

**Comment by weshaggard** [comment]
>I believe we are trying to be perfect in wrong way - it adds negative value.

I think that is true in lots of places when we included APIs for compat purposes in netstandard. The general approach that we are still trying to hold to in netstandard however is to keep all members for any types we are including (with few exceptions like AppDomain and Marshal). So unless we are thinking of removing MarshalByRefObject completely, which I don't think we want, I would still push to keep the full closure. Looking at https://github.com/dotnet/standard/pull/13, the number of types/members isn't bad enough to really worry about. As far as I can tell there isn't even anything that needs to throw in that API set, we would simply not do any remoting.

**Comment by weshaggard** [comment]
After chatting with Jan we decided to go with option (2) in dotnet/standard#7, see commit https://github.com/dotnet/standard/commit/80799d92215df2fa0751c4a632def7379b0c5b3d for the APIs that have been removed for netstandard and thus can be removed from this work list.

@stephentoub @jkotas in the same light do we want to do the same thing for the other types in the "remoting" namespace we includes for BinaryFormatter? https://github.com/dotnet/standard/pull/14

If not then we can also just include those at a higher level where we are shipping BinaryFormatter which is System.Runtime.Serialization.Formatters.

**Comment by jkotas** [comment]
> @stephentoub @jkotas in the same light do we want to do the same thing for the other types in the "remoting" namespace we includes for BinaryFormatter

I think it would be a fine idea.

**Comment by ramarag** [comment]
@jkotas @stephentoub  Currently 
System.Runtime.Remoting.Messaging.Header
System.Runtime.Remoting.Messaging.HeaderHandler are used by BinaryFormatter

Should we be removing those methods of BinaryFormatter ?

**Comment by jkotas** [comment]
> Should we be removing those methods of BinaryFormatter ?

Yes - assuming https://github.com/dotnet/standard/issues/88 that I just opened goes through.
