### ISSUE TITLE
Use public Socket.Handle property from SafePipeHandle

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#11807]
#11800 added Socket.Handle back to the public API surface.  However, we currently have one place in the code where we'd like to use Handle and are getting it via reflection:

https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.IO.Pipes/src/Microsoft/Win32/SafeHandles/SafePipeHandle.Unix.cs#L34
We should fix that as well.

**Comment by karelz** [comment]
Fixed in PR #32649 (doesn't show as merged due to GitHub outage)
