### ISSUE TITLE
Add DSACertificateExtensions class

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#11802]
Did not add as part of the DSA work #4813, so creating a new issue to track that

**Comment by danmosemsft** [comment]
Not in NS2.0 as it didn't appear until 4.6.2.

**Comment by Petermarcu** [comment]
@steveharter , Dan removed the netstandard2.0 label because only things in 4.6.1 are in. Did you confirm that this was added in 4.6.1 and not 4.6.1? If not, we should remove the label.

**Comment by danmosemsft** [comment]
We do want to bring NS2.0 up to 4.6.3 now, so these are included. 

```
T:System.Security.Cryptography.X509Certificates.DSACertificateExtensions
M:System.Security.Cryptography.X509Certificates.DSACertificateExtensions.GetDSAPrivateKey(System.Security.Cryptography.X509Certificates.X509Certificate2)
M:System.Security.Cryptography.X509Certificates.DSACertificateExtensions.GetDSAPublicKey(System.Security.Cryptography.X509Certificates.X509Certificate2)
```

**Comment by danmosemsft** [comment]
Ignore my comment above. These are not part of NS2.0

**Comment by bartonjs** [comment]
This should be straightforward, copying the pattern from the RSACertificateExtensions class.

**Comment by matekm** [comment]
Hi @karelz @bartonjs - I would like to grab that ticket (if it's low priority as I can commit only 1-2hrs per week to work on that...).

**Comment by steveharter** [comment]
@matekm I assigned you the issue. Please also be sure to add tests. Thanks

**Comment by karelz** [comment]
@matekm just curious if you were able to make any progress ...

**Comment by karelz** [comment]
Unassigning ... @matekm does not have time to finish it now.
Anyone can grab the issue and finish it (feel free to reuse existing work in #14722).

**Comment by bartonjs** [comment]
Pulling this in for 2.0 so we don't have a mismatch between legacy PrivateKey property (can do DSA) and the new Get*PrivateKey methods (can't).

**Comment by bartonjs** [comment]
@danmosemsft @weshaggard Since this was in-scope and out-of-scope a couple of times for netstandard2.0 I thought I'd offer up that it's currently in PR to be present for netcoreapp, and it is present in net462.  I know that those aren't the only two stakeholders; but thought I'd make the data available to you.

**Comment by danmosemsft** [comment]
I can't remember why I wrote that it wasn't in scope. opened https://github.com/dotnet/standard/issues/239

**Comment by tintoy** [comment]
I remember removing a reference to `GetECDSAPublicKey` in f18d31725b8fdef8534d8015139a1acabcf7799f, although I don't remember seeing any call to `GetDSAPublicKey`. Does a call to `GetDSAPublicKey` need to be added into `Utils.GetAnyPublicKey` ([src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/Utils.cs](https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/Utils.cs))?

**Comment by bartonjs** [comment]
@tintoy Yep, which should let the DSA tests start passing :smile:

**Comment by tintoy** [comment]
K I can do that if you like

**Comment by tintoy** [comment]
I'll have a quick look at which tests were disabled due to missing DSA support.

**Comment by tintoy** [comment]
Actually, the only DSA-related tests in `System.Security.Cryptography.Xml` that are marked as `Skip` seem to be failing for unrelated reasons. I'll see what's what.
