### ISSUE TITLE
DateTime.Parse inconsistent with other platforms

### ISSUE THREAD

**Issue by troydai** [dotnet/corefx#1181]
Source: https://github.com/aspnet/dnx/issues/773

This passes in .NET 4.5 and Win 8 Store but fails on CoreCLR:

```
[Test]
public void FailingDateTimeParse()
{
    string text = "2000-12-15T22:11:03.055+23:30";

    DateTime oldDt;
    bool success = DateTime.TryParseExact(text, "yyyy-MM-ddTHH:mm:ss.FFFFFFFK", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind, out oldDt);

    Console.WriteLine("Success: " + success);
    Console.WriteLine("DateTime: " + oldDt);

    Assert.True(success);
}
```

Standalone repo: https://github.com/troydai/dnx-issue773/blob/master/dnx-issue773/Program.cs

@JamesNK

**Comment by tarekgh** [comment]
I'll take a look at this one.

**Comment by troydai** [comment]
Hi @tarekgh. Can you confirm this issue?

**Comment by tarekgh** [comment]
@troydai I'll get into this in the first chance. is it blocking? I was planning to look at it around tomorrow

**Comment by troydai** [comment]
@tarekgh it's not blocking but it comes from our customer, so it impacts their scenarios.

**Comment by tarekgh** [comment]
"2000-12-15T22:11:03.055+23:30" is not correct date as there is no TZ offset can be greater than 14:00 hours. unfortunately the desktop allowed such date but we cannot  change it for app compat reason. the behavior of CoreClr is the correct one
