### ISSUE TITLE
Unify implementation of WebUtility and HttpUtility

### ISSUE THREAD

**Issue by alexperovich** [dotnet/corefx#11811]
System.Net.WebUtility and System.Web.HttpUtility have very similar functionality. We should either augment the code in WebUtility to accept Encoding and expose new members, or share the implementation code between the 2 libraries.

**Comment by alexperovich** [comment]
@weshaggard

**Comment by karelz** [comment]
Next step: Review the code and assess feasibility.
Complexity: Medium

**Comment by davidsh** [comment]
Tracking now in issue #20795.
