### ISSUE TITLE
C# dynamic behaviour in ternary operators

### ISSUE THREAD

**Issue by varocarbas** [dotnet/corefx#11825]
Firstly, I want to highlight that I rarely use `dynamic`. On the other hand, I have relied a lot on `Option Strict Off` when using VB.NET. That is, I do feel comfortable when coding with low-to-no type checks and know what I should expect from these configurations.

I am currently writing a C# code which uses quite a few `dynamic` variables. This seems the best proceeding for easily managing a big number of similar enough types (i.e., numeric types). It has been behaving as expected, until I found what seems like a design flaw to me.

To understand my point, consider the following two functions:

```
private static double Test1()
{
    dynamic stringVal = "";

    return stringVal;
}

private static double Test2()
{
    dynamic stringVal = "";

    return
    (
        true ? stringVal : "string2"
    );
} 
```

Both of them compile fine despite being clearly wrong. In principle, these are precisely the kind of scenarios which justify the existence of `dynamic`. In any case, I see a notable difference between both cases:
- `Test1` seems fine to me. The compiler doesn't check the `stringVal` type because of being specifically instructed to not do so (i.e., declaring this variable as `dynamic`).
- `Test2` doesn't behave as I expect that a language like C# (always checking everything) should do. Unlikely what happens in the previous example, there is no need to check the `stringVal` type to know that this code is wrong. The type of the `dynamic` variable has to be either `string` (returned type error) or different than `string` (ternary operator error).

If I was using VB.NET with `Option Strict Off`, I wouldn't expect any type check (even though, some checks are certainly performed). On the other hand, I do expect C# to check each single bit. When using `dynamic`, I do expect the type of the given variable to not be checked, but also the remaining parts to continue behaving as usual. If I have an unfixably-wrong ternary operator, I would expect the code to not compile.  

In my opinion, this is a flaw in the `dynamic` implementation; not a bug because this has always been the case with this functionality (I tested it in VS 2012, VS 2015 and all the .NET versions since 4.0, when `dynamic` was introduced). In situations like a ternary operator, the most-restrictive option should always be the defining one (i.e., having one `string` member means that the output type can only be `string`). 

This might be considered as a breaking modification (someone, somewhere might eventually have considered the eventually of perhaps relying on...) what, according to some (quite bad) past experiences, means that there is virtually no chance of it being changed. I accept that.

**Comment by stephentoub** [comment]
@varocarbas, could you move this issue to the Roslyn repo?
https://github.com/dotnet/roslyn
The issue is about compiler behavior, and that repo contains the compiler.  Thanks.

**Comment by varocarbas** [comment]
@stephentoub Sure. Sorry about the mistake.

**Comment by stephentoub** [comment]
No problem. Thanks.
