### ISSUE TITLE
System.Timers.Tests.TimerTests.TestTimerStartAutoReset test failure in CI

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#11820]
See http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/283/

**Comment by bartdesmet** [comment]
These tests were added a few days ago in https://github.com/dotnet/corefx/commit/e94e7a4b9a6150890cb812dabf2835c958b8289f. @Priya91, can you have a look why this would fail repeatedly on OSX?

**Comment by stephentoub** [comment]
I'll fix this. There are several issues in the test, including a few race conditions. For some reason they're just more prominent on macOS.
