### ISSUE TITLE
SslStream disproportionately allocates

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#11826]
Switching from http 

![](https://aoa.blob.core.windows.net/aspnet/websocket-result-ssl-2.png)

to https goes via SslStream and causes the allocations to increase dramatically (new in red below)

![](https://aoa.blob.core.windows.net/aspnet/sslstream-3.png)

(The missing `int[]` allocation only happens at a higher load which I can't reach using Ssl)

Comparison is to WebSocketReceiveResult which already has over allocations https://github.com/dotnet/corefx/issues/4530

/cc @davidfowl @stephentoub @blowdart

**Comment by stephentoub** [comment]
@davidsh, curious why you assigned this to me? The specific profiling example is with websockets but the concern is about SslStream in general... the websockets implementation just uses SslStream.

**Comment by davidsh** [comment]
@stephentoub I saw the `System.Net.WebSockets.ManagedWebSockets` class on the stack and assumed that this issue is related to that codebase which is something you wrote/ported.

**Comment by davidsh** [comment]
cc: @cipop

**Comment by stephentoub** [comment]
@benaadams, I expect there's some low-hanging fruit here, if you want to take a look, too.

**Comment by benaadams** [comment]
I do also get stuttering at a much lower load when using SslStream; the only thing that looks related that seems like it make do any kind of blocking/resource consumption is `LazyAsyncResult`
  
![](https://aoa.blob.core.windows.net/aspnet/lazy-async-1.png)

However there's not a huge amount of time spent there; so is more likely to be much higher levels of GC. Still investigating.

**Comment by davidfowl** [comment]
@CIPop once you handle all of the low hanging fruit, a CopyToAsync implementation would be great 😄

**Comment by CIPop** [comment]
+ @himadrisarkar for scheduling.

Thanks for reporting @benaadams! Feel free to submit a PR if there is an obvious fix for SslStream. 

> [...] a CopyToAsync implementation would be great 

@davidfowl Please open a new tracking issue (a comment can be easy to miss in the future).

**Comment by stephentoub** [comment]
> @davidfowl Please open a new tracking issue (a comment can be easy to miss in the future).

I opened https://github.com/dotnet/corefx/issues/12037

**Comment by davidfowl** [comment]
@stephentoub Thanks
