### ISSUE TITLE
HtmlEncoder don't support Chinese

### ISSUE THREAD

**Issue by ChangweiZhang** [dotnet/corefx#11844]
Hi,
When we develop a website using ASP.NET Core, we find a issue that ASP.NET Core always made the title of html page a error  result in Chinese.
For example:

```
@{
    ViewBag.Title = "代码改变世界";
}
<title>@ViewBag.Title</title>
```

the result is 
![image](https://cloud.githubusercontent.com/assets/4610610/18612401/64b09974-7d8b-11e6-96b0-7ecabfd244f4.png) , but it should be "代码改变世界".

After we check your source code, we found that you used **UnicodeRanges.BasicLatin** init a singleton of  **HtmlEncoder**, not **UnicodeRanges.All**.

https://github.com/dotnet/corefx/blob/master/src/System.Text.Encodings.Web/src/System/Text/Encodings/Web/HtmlEncoder.cs

**Comment by ChangweiZhang** [comment]
So we make a ttemporarily solution:

services.AddSingleton(HtmlEncoder.Create(UnicodeRanges.All));

**Comment by stephentoub** [comment]
cc: @KrzysztofCwalina

**Comment by KrzysztofCwalina** [comment]
cc: @Eilon

**Comment by blowdart** [comment]
See https://docs.asp.net/en/latest/security/cross-site-scripting.html#customizing-the-encoders
