### ISSUE TITLE
Custom Select/Where implementations should be decoupled from Iterator

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#11840]
[EmptyPartition](https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Partition.cs#L51) should be override these methods to be nops, but can't since for one to customize these methods you have to [subclass Iterator](https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Iterator.cs#L45). Maybe it would be good to have an `IIterator<T>` interface which `Iterator<T>` implements, and then change `IIListProvider<T>` to inherit from `IIterator`.

cc @JonHanna

**Comment by JonHanna** [comment]
I pondered such overrides as the result is trivial, small and immutable (and in the case of Where can return itself), but I figured that they wouldn't be worth the cost of checking for. This would provide a means at minimal cost, assuming the cost of the interface use is little or nothing over the current virtual cost on Iterator. Otherwise I would rather not add even a tiny cost there, since Iterator would be by far the more common case, and any operation on EmptyPartition is inherently going to be relatively quick, anyway.

**Comment by jamesqo** [comment]
@JonHanna True; as you mention, putting the methods under an interface may add extra cost (I remember reading in coreclr that interface calls were slightly slower than virtual ones).

What if we just checked for reference equality to `EmptyPartition`, since there's only one instance anyways? Not quite as clean, but doesn't seem to add much cost for the branches penalized (at least, if the `Instance` field has already been initialized):

```cs
// Select.cs
IPartition<TSource> partition = source as IPartition<TSource>;
if (partition != null)
{
    return partition == EmptyPartition<TSource>.Instance ?
        EmptyPartition<TResult>.Instance :
        new SelectIPartitionIterator<TSource, TResult>(partition, selector);
}
```

> and any operation on EmptyPartition is inherently going to be relatively quick, anyway.

It may still be valuable for avoiding allocations if an empty partition is fed into a long chain of Select/Wheres, perhaps. e.g.

```cs
new[] { 1, 2, 3 }.Skip(3)
    // Each of these allocate 3 new iterators currently.
    .Select(...)
    .Where(...)
    .Select(...)
```

**Comment by JonHanna** [comment]
If there wasn't such an `EmptyPartition` yet then that would both instantiate the type and create the instance even though it might never be used. This could be creating quite a large number of such types and objects in a project that uses lots of different anonymous types with Linq. We aren't exactly shy about instantiating types in Linq, but it is avoided, and we generally gain more.

Even considering just the added cheap reference equality test, the relative rarity of `EmptyPartition` and the relative abundance of `Iterator` makes this seem like spending a thousand pennies to save a pound.

It's frustrating to leave unconsidered given how satisfyingly cheap such a `Where()` and `Select()` would be (and also that they'd have no reference to the previous enumerable object and hence play well with garbage collection), but the balance seems to me to be in favour of the status quo.

However, what about just making it inherit from `Iterator`? The downsides are obvious enough (and hence why I didn't do so when I created the type) but they aren't massive. Three wasted fields (two integers, one of the element type) isn't a massive cost and `GetEnumerator()` would work correctly as-if or could be made virtual. (I **think** that the fact that `GetEnumerator()` is already virtual at the CIL level means doing this won't add a cost, but I'm not sure).

It would make `EmptyPartition` less perfectly cheap, but I'd rather compromise on the performance of `EmptyPartition` than compromise anywhere else.

**Comment by jamesqo** [comment]
> However, what about just making it inherit from Iterator?

Sounds like a fine idea; 16 bytes doesn't seem like much for an object that will only be instantiated once. I'll make a PR when I get the chance & post perf results.

**Comment by JonHanna** [comment]
I'd be interested particularly in whether making `Iterator.GetEnumerator()` virtual has any cost. If it doesn't then `EmptyPartition.GetEnumerator()` can remain as is (apart from obviously becoming an `override`). If it does then `EmptyPartition` should be the one that takes the hit.

**Comment by jamesqo** [comment]
@JonHanna We might end up having to use interface anyway with https://github.com/dotnet/corefx/pull/14579, which introduces a new iterator base class.

**Comment by stephentoub** [comment]
This isn't really actionable.  If there's a particular optimization to be implemented, please feel free to submit a PR.
