### ISSUE TITLE
DisplayNameAttribute Is Not Able to Localise or Override

### ISSUE THREAD

**Issue by cihadsevim** [dotnet/corefx#11846]
I've been practicing on Asp.Net Core MVC recently. We were able to localize and globalise the ViewModel attributes before using below class and overriding. I've been looking for this solution over a week.

```c#
public class LocalizedDisplayNameAttribute : DisplayNameAttribute
{
    public LocalizedDisplayNameAttribute(string resourceId)
        : base(GetMessageFromResource(resourceId))
    {

    }

    private static string GetMessageFromResource(string resourceId)
    {
         return LanguageManager.Read(resourceId);
    }
}
```

My view model looks like

```c#
public class LoginViewModel
{
    [CustomRequiredAttribute("Email")]
    [LocalizedDisplayName("Email")]
    [EmailAddress]
    public string Email { get; set; }

    [LocalizedDisplayName("Password")]
    [CustomRequiredAttribute("Password")]
    [DataType(DataType.Password)]
    public string Password { get; set; }

    [Display(Name = "Remember me?")]
    public bool RememberMe { get; set; }
}
```

I copied the same LocalizedDisplay class and tried it on Asp.Net core but didn't work.

The problem is on view, **application prints field name** not the value from attribute.

**Comment by cihadsevim** [comment]
DisplayName Attribute doesn't work either

` [DisplayName("NameSurname")]
        public string name { get; set; }`

**Comment by cihadsevim** [comment]
Problem solved with asp.net core 1.0.1 pack.

`class DisplayNameDetailsProvider : IDisplayMetadataProvider
    {
        public void CreateDisplayMetadata(DisplayMetadataProviderContext context)
        {
            var displayAttribute = context.Attributes.OfType<DisplayNameAttribute>().FirstOrDefault();
            if (displayAttribute != null)
            {
                context.DisplayMetadata.DisplayName = () => displayAttribute.DisplayName;
            }
        }
    }`

And then register!

` services.AddMvc(options =>
            {
                options.ModelMetadataDetailsProviders.Add(new DisplayNameDetailsProvider());
            });`

**Comment by karelz** [comment]
Seems to be resolved -- the problem was not specific to Resources, but rather ASP.NET Core usage.
