### ISSUE TITLE
Port some missing GC types/members

### ISSUE THREAD

**Issue by kouvel** [dotnet/corefx#11866]
- [ ]  M:System.GC.CancelFullGCNotification
- [x] M:System.GC.Collect(System.Int32,System.GCCollectionMode,System.Boolean,System.Boolean)
- [x] M:System.GC.EndNoGCRegion
- [x] M:System.GC.GetGeneration(System.WeakReference)
- [ ] M:System.GC.RegisterForFullGCNotification(System.Int32,System.Int32)
- [x] M:System.GC.TryStartNoGCRegion(System.Int64)
- [x] M:System.GC.TryStartNoGCRegion(System.Int64,System.Boolean)
- [x] M:System.GC.TryStartNoGCRegion(System.Int64,System.Int64)
- [x] M:System.GC.TryStartNoGCRegion(System.Int64,System.Int64,System.Boolean)
- [ ] M:System.GC.WaitForFullGCApproach
- [ ] M:System.GC.WaitForFullGCApproach(System.Int32)
- [ ] M:System.GC.WaitForFullGCComplete
- [ ] M:System.GC.WaitForFullGCComplete(System.Int32)

- [x] T:System.GCNotificationStatus
- [x] F:System.GCNotificationStatus.Canceled
- [x] F:System.GCNotificationStatus.Failed
- [x] F:System.GCNotificationStatus.NotApplicable
- [x] F:System.GCNotificationStatus.Succeeded
- [x] F:System.GCNotificationStatus.Timeout
- [x] F:System.GCNotificationStatus.value__

**Comment by mattwarren** [comment]
It's good to know that more GC functionality will be available in CoreCLR, particularly `GC.TryStartNoGCRegion(..)`. I [spent some time looking at that API](http://mattwarren.org/2016/08/16/Preventing-dotNET-Garbage-Collections-with-the-TryStartNoGCRegion-API/), it's very useful.

**Comment by ramarag** [comment]
fixed by https://github.com/dotnet/corefx/commit/483ec7abc869a4128a0ff884e848592cac19ab8b
