### ISSUE TITLE
Implement System.Activator

### ISSUE THREAD

**Issue by rahku** [dotnet/corefx#11869]
public sealed partial class Activator 
     { 
         internal Activator() { } 
        public static object CreateInstance(System.Type type) { throw null; } 
         public static object CreateInstance(System.Type type, bool nonPublic) { throw null; } 
         public static object CreateInstance(System.Type type, params object[] args) { throw null; } 
         public static object CreateInstance(System.Type type, object[] args, object[] activationAttributes) { throw null; } 
         public static object CreateInstance(System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, object[] args, System.Globalization.CultureInfo culture) { throw null; } 
         public static object CreateInstance(System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, object[] args, System.Globalization.CultureInfo culture, object[] activationAttributes) { throw null; } 
         public static T CreateInstance<T>() { throw null; } 
}

**Comment by rahku** [comment]
CC @kouvel

**Comment by justinvp** [comment]
Since this class is `sealed`, has a private constructor, and all static methods, it's effectively a `static` class in C#. Could it be specified as `static` in the contract?

**Comment by kouvel** [comment]
It looks like the following are already exposed:

```
        public static object CreateInstance(System.Type type) { return default(object); }
        public static object CreateInstance(System.Type type, System.Boolean nonPublic) { return default(object); }
        public static object CreateInstance(System.Type type, params object[] args) { return default(object); }
        public static T CreateInstance<T>() { return default(T); }
```

https://github.com/dotnet/corefx/blob/master/src/System.Runtime/ref/System.Runtime.cs#L30

**Comment by rahku** [comment]
hmmm and already marked as static in contract. So only below three are remaining
     public static object CreateInstance(System.Type type, object[] args, object[] activationAttributes) { throw null; } 
     public static object CreateInstance(System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, object[] args, System.Globalization.CultureInfo culture) { throw null; } 
     public static object CreateInstance(System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, object[] args, System.Globalization.CultureInfo culture, object[] activationAttributes) { throw null; }

**Comment by kouvel** [comment]
Looks like it's static in the CoreFX contract, and sealed in the netstandard contract:
https://github.com/dotnet/standard/blob/master/netstandard/ref/mscorlib.appdomain.cs#L4

**Comment by rahku** [comment]
I think @weshaggard didn't pay that much attention. It should be fixed and marked as static in netstandard contract

**Comment by weshaggard** [comment]
Yes this one can be marked as static. It was this way because I seeded it from .NET 4.6.1 which has it as sealed with a non-public constructor.
