### ISSUE TITLE
Mark PlatformID.MacOSX obsolete?

### ISSUE THREAD

**Issue by justinvp** [dotnet/corefx#11878]
`Environment.OSVersion.Platform` returns `PlatformID.Unix` on macOS instead of `PlatformID.MacOSX`, which is consistent with Mono's behavior.

This is already confusing for Xamarin.Mac developers and I think it's going to be confusing for .NET Core developers as well.

(I wish we hadn't added `PlatformID.MacOSX` for Silverlight, and just used `PlatformID.Unix` like Mono.)

To help mitigate the confusion, should `PlatformID.MacOSX` be marked as obsolete, pointing developers to use `PlatformID.Unix` or `RuntimeInformation.IsOSPlatform(OSPlatform.OSX)` instead?

And/or hidden from intellisense?

cc: @terrajobst, @KrzysztofCwalina, @weshaggard, @stephentoub

For reference:

``` c#
    public enum PlatformID
    {
        Win32S = 0,
        Win32Windows = 1,
        Win32NT = 2,
        WinCE = 3,
        Unix = 4,
        Xbox = 5,
        MacOSX = 6
    }
```

**Comment by justinvp** [comment]
Another idea, although, not sure how breaking it would be: change the value of `MacOSX` to be the same as `Unix`?

**Comment by svick** [comment]
> Another idea, although, not sure how breaking it would be: change the value of MacOSX to be the same as Unix?

So, `Environment.OSVersion.Platform == PlatformID.MacOSX` would return `true` on Linux? I would find that very confusing.

**Comment by justinvp** [comment]
@svick, Good point. Scratch that idea.

**Comment by mellinoe** [comment]
If we're obsoleting anything, we should obsolete this whole enum. Aside from the stuff you already mentioned, the rest of the enum values make practically no sense (especially nowadays, but really ever), and are very limited in scope.

I don't think we should obsolete it, though. It's just there for compat; as such, we should probably avoid making any changes to it and should just direct people to more sensible abstractions.

**Comment by justinvp** [comment]
> should just direct people to more sensible abstractions

How do you direct people to the more sensible abstractions? Not everyone is going to read docs. Some developers are going to use `Environment.OSVersion.Platform == PlatformID.MacOSX` (given that `Environment.OSVersion.Platform` has existed in .NET forever), without realizing it won't work the way they expect.

**Comment by mellinoe** [comment]
If this was the original proposal:

> To help mitigate the confusion, should PlatformID.MacOSX be marked as obsolete, pointing developers to use PlatformID.Unix or RuntimeInformation.IsOSPlatform(OSPlatform.OSX) instead?

Then i'm just suggesting we should obsolete the entire enum instead, and put the suggestion there in the attribute message.

> Some developers are going to use Environment.OSVersion.Platform == PlatformID.MacOSX (given that Environment.OSVersion.Platform has existed in .NET forever), without realizing it won't work the way they expect.

Yes, this will be a problem with a lot of the API's we are bringing back; many of them won't or cannot be implemented identically across platforms, or have legacy baggage preventing them from being sensibly implemented. I assume we are working on some sort of strategy to help developers avoid those pitfalls, and this seems to fall into that sort of bucket.

**Comment by AlexGhiondea** [comment]
@mellinoe @justinvp maybe instead of obsoleting it maybe the compromise is to hide it from Intellisense? That way new apps won't see it and old apps would continue to work?

**Comment by jkotas** [comment]
This was fixed by https://github.com/dotnet/platform-compat/issues/29
