### ISSUE TITLE
Port FileWebRequest/Response

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#11882]
Build it on top of System.IO.File APIs (it's also great solution for x-plat).

**Comment by tsolarin** [comment]
@karelz will this involve a move of the `FileWebRequest`/`FileWebResponse` class to the `System.IO` namespace? i.e `System.IO.FileWebRequest`.

**Comment by stephentoub** [comment]
> will this involve a move of the  FileWebRequest / FileWebResponse  class to the  System.IO  namespace? i.e  System.IO.FileWebRequest .

No, the namespace will not change.

> Build it on top of System.IO.File APIs 

It's already built on FileStream. Nothing there needs to change.

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/corefx/pull/12091
