### ISSUE TITLE
Port WebProxy

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#11884]
Expect one hard API: URI->proxy mapping (calls into OS) -- likely not used widely, we shold just throw NotSupportedException.

**Comment by davidsh** [comment]
Place this in a separate contract System.Net.WebProxy for now.

**Comment by karelz** [comment]
@stephentoub can you please remind me what we decided about the hard API above? Do we throw, or just return nothing?
I remember you mentioned we could implement it on Linux/Mac in future by reading various known settings -- if we find a strong reason (feedback).

**Comment by stephentoub** [comment]
> can you please remind me what we decided about the hard API above? Do we throw, or just return nothing?

https://github.com/dotnet/corefx/blob/master/src/System.Net.WebProxy/src/System/Net/WebProxy.cs#L235
