### ISSUE TITLE
Re-enable clrcompression build with Zlib-Intel

### ISSUE THREAD

**Issue by bjjones** [dotnet/corefx#11893]
Due to a previous bug, CoreFX was changed to use the closed version of clrcompression instead of the optimized Zlib-Intel version. After a fix and more testing, I believe CoreFX should switch back to the Zlib-Intel build. 

I have done 24 hour looped deflate tests for the following:

- Canterbury Corpus
- Calgary Corpus
- a set of 10 4k .jpeg images
- The CLI preview3 binaries

By succesfully completing this longer and more varied testing, we should consider re-enabling the optimized build of Zlib.

https://github.com/dotnet/corefx/pull/9273
https://github.com/dotnet/corefx/issues/9290

Testing was completed after #11892

**Comment by bjjones** [comment]
@ianhays @stephentoub

**Comment by stephentoub** [comment]
@ianhays can correct me if I'm wrong, but I was under the impression we already reverted back to using Zlib-Intel in the official packages.

**Comment by bjjones** [comment]
I see, I was unaware of that change. @ianhays can go ahead and close this if that is the case.

**Comment by ianhays** [comment]
> I was under the impression we already reverted back to using Zlib-Intel in the official packages.

That is correct. I switched the build pipeline for x64 and x86 back to the zlib-intel build shortly after https://github.com/dotnet/corefx/pull/9273. Some brief discussion about it [here](https://github.com/dotnet/corefx/issues/9789#issuecomment-230590939)
