### ISSUE TITLE
System.Diagnostics.Process.Performance.Tests failed to start on CentOS in CI -- Linux kernel bug

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#11908]
From http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_release_prtest/397/

```
/mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_release_prtest/Tools/Microsoft.CSharp.Core.targets(67,5): error MSB6006: "/mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_release_prtest/Tools/dotnetcli/dotnet" exited with code 139. [/mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_release_prtest/src/System.Diagnostics.Process/tests/Performance/System.Diagnostics.Process.Performance.Tests.csproj]
```

Oddly, there's nothing else in the log about this test.  It doesn't seem to have even started.

**Comment by stephentoub** [comment]
Exit code 139 means seg fault.  This is almost certainly the same seg fault that @adityamandaleeka's been tracking on CentOS/RedHat.

**Comment by karelz** [comment]
@adityamandaleeka should we dupe it against something else?

**Comment by karelz** [comment]
Actually is the bug still valid?

**Comment by adityamandaleeka** [comment]
Here is the issue @stephentoub mentioned above: https://github.com/dotnet/coreclr/issues/6283

**Comment by karelz** [comment]
That bug is marked as Test-Issue, while this looks like product bug. What am I missing?

**Comment by adityamandaleeka** [comment]
@karelz That issue was tagged incorrectly. I just removed the test-issue tag. It's not a product bug either. The bug (which has been fixed) is in the Linux kernel itself. The fix will slowly propagate to all the distros we run on.

**Comment by karelz** [comment]
@adityamandaleeka thanks, that makes sense - I asked also on the dupe: Is there a way how to associate a segfault in CoreFX tests with this kernel bug?
I would like to make sure we do no blame all segfaults in CoreFX on kernel ;-)

**Comment by karelz** [comment]
Closing, as it is kernel bug, not something we can in .NET Core work around.
