### ISSUE TITLE
Need more testing of System.Net.Sockets.NetworkStream

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#11904]
We currently have very poor coverage of NetworkStream.  We should consider adding more tests in this area.

**Comment by ericeil** [comment]
From https://github.com/dotnet/corefx/pull/11902/files/4f26999bfd7535c02b83d55c542b5be7bf09d89c#r79676132:

> I remember we had testing for APM that got removed at some point. (Didn't look - maybe the code is still there?).
The tests should be in older versions of the repo and can easily be brought back (I believe they were in the System.Net.Sockets.Legacy folder.)

**Comment by karelz** [comment]
@danmosemsft @stephentoub can you please point us to code coverage data, so that we can check how bad the situation is? (and decide 2.0 vs. Future) Thanks!

**Comment by stephentoub** [comment]
https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/lastSuccessfulBuild/artifact/bin/tests/coverage/System.Net.Sockets_NetworkStream.htm

**Comment by karelz** [comment]
Thanks @stephentoub!

@geoffkizer is there anything that stands out for you as must-have coverage for 2.0?

Naively, I'd say basic functionality is covered. We don't have much negative test cases (which is ok for 2.0 IMO).
The only potentially methods are UnsafeBeginRead and UnsafeBeginWrite, but they seem to be dead code: https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=UnsafeBeginRead+UnsafeBeginWrite&type=Code.

**Comment by geoffkizer** [comment]
It would be good to have tests of the following:
ReadTimeout
WriteTimeout
DataAvailable
Connected
SetSocketTimeoutOption
Close(int timeout)

This stuff seems to be dead and should be removed:
PollRead
Poll
UnsafeBeginRead/Write

**Comment by karelz** [comment]
Thanks, let's keep the work listed by @geoffkizer as 2.0.
