### ISSUE TITLE
System.Array.LongLength and System.Array.GetLongLength are missing

### ISSUE THREAD

**Issue by surban** [dotnet/corefx#11926]
We need support for 64-bit arrays for scientific computing in .NET core.

Are there any plans to reintroduce those APIs?

**Comment by stephentoub** [comment]
These have already been added back for .NET Core 1.2:

**Comment by stephentoub** [comment]
As this has already been addressed from an API perspective to match what the .NET Framework has, I'm going to close the issue. Thanks.
