### ISSUE TITLE
Use of dynamic against a large number of types leads to OutOfMemoryException

### ISSUE THREAD

**Issue by hantu548** [dotnet/corefx#11934]
The application included below will rapidly consume available memory and if allowed to run long enough it will eventually crash with OutOfMemoryException ('Array dimensions exceeded supported range') while trying to resize the backing array of the dictionary used by Microsoft.CSharp.RuntimeBinder.Semantics.SYMTBL.InsertChildNoGrow.

In the example below the issue can be avoided by either removing the cast to 'dynamic' or by removing at least 9 of the items in the 'entities' array.

```
namespace DynamicTest
{
    public static class Program
    {
        public static void Main()
        {
            var entities = new object[]
            {
                new T01(),
                new T02(),
                new T03(),
                new T04(),
                new T05(),
                new T06(),
                new T07(),
                new T08(),
                new T09(),
                new T10(),
                new T11(),
                new T12(),
                new T13(),
                new T14(),
                new T15(),
                new T16(),
                new T17(),
                new T18(),
                new T19(),
                new T20()
            };

            var len = entities.Length;
            while (true)
            {
                for (var i = 0; i < len; i++)
                for (var j = 0; j < len; j++)
                    entities[i].Equals((dynamic)entities[j]);
            }
        }
    }

    public class T01 : object { }
    public class T02 : object { }
    public class T03 : object { }
    public class T04 : object { }
    public class T05 : object { }
    public class T06 : object { }
    public class T07 : object { }
    public class T08 : object { }
    public class T09 : object { }
    public class T10 : object { }
    public class T11 : object { }
    public class T12 : object { }
    public class T13 : object { }
    public class T14 : object { }
    public class T15 : object { }
    public class T16 : object { }
    public class T17 : object { }
    public class T18 : object { }
    public class T19 : object { }
    public class T20 : object { }
}
```

**Comment by karelz** [comment]
We need to find a root cause - should be able to get it our of debugger, monitoring allocated memory.

**Comment by JonHanna** [comment]
This is creating new `Scope` symbols and new locals within that, and adding them to the lookup. Since each `Scope` is new and there's no good way to detect the equality with the previous, the store continues to grow.

I **think** that scopes and their children are never retrieved again, so I **think** it may be safe to have `if (child is Scope || child.parent is Scope) return` on `InsertChildNoGrow` and hence the table won't keep growing, but I'm not sure.

**Comment by JonHanna** [comment]
http://stackoverflow.com/questions/41354549/memory-leak-when-using-callsite would seem to be caused by the same issue.

Incidentally, from the issue description above:
> In the example below the issue can be avoided by either removing the cast to 'dynamic' or by removing at least 9 of the items in the 'entities' array.

When I investigated this I found that it would still leak if you removed lots of items, just much more slowly.
