### ISSUE TITLE
Where to find a complete list of NuGet packages for corporate NuGet server

### ISSUE THREAD

**Issue by lextm** [dotnet/corefx#11935]
For corporations who block access to public feeds such as NuGet.org, they usually download packages and then host them on a private NuGet server. That approach works fine for a few years already.

Now .NET Core development relies even more on NuGet.org, and it involves tons of packages (both managed and native), which makes it very difficult for any outsiders to generate a complete list of required packages from scratch.

Thus, I'd like to ask if Microsoft can provide such a list (or at least show how such a list can be compiled from source code or any other public information). The necessary columns I can think of are below,

File: netcore1.0.0.txt

Package name | version       
---------------|------------
System            | 4.0.0
...

File: netcore1.0.1.txt

Package name | version       
---------------|------------
System            | 4.0.1
...

Then we can write custom scripts to download the packages from NuGet.org and then deploy to private NuGet server. Of course, if Microsoft can provide such a script, it would be highly appreciated.

**Comment by lextm** [comment]
I noticed that the `dotnet` can generate a local cache 
```
dotnet new                                                                                                                                                                            
Welcome to .NET Core!                                                                                                                                                                       
---------------------                                                                                                                                                                       
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.                                               
Telemetry                                                                                                                                                                                   
--------------                                                                                                                                                                              
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include commandline arguments. The data is collected by Microsoft and shared 
with the community.                                                                                                                                                                         
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.                                                                  
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.                                                                                                    
Configuring...                                                                                                                                                                              
-------------------                                                                                                                                                                         
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only hap
pen once.                                                                                                                                                                                   
Decompressing 100% 12843 ms                                                                                                                                                                 
Expanding 100% 77834 ms              
```
Does this cache contain all the necessary packages from Microsoft?

**Comment by svick** [comment]
All the packages that are part of .Net Core 1.0.1 are listed [here](https://github.com/dotnet/core/blob/master/release-notes/1.0/1.0.1-manifest.md). There doesn't seem to be a similar list for .Net Core 1.0.0, but it should be mostly straightforward to create that from the 1.0.1 version.

The package cache is populated from `nuGetPackagesArchive.lzma`, which is part of the .Net Core SDK. As far as I can tell, it contains packages from the Microsoft.NETCore.App and CoreCLR sections from the manifest I linked to above.

**Comment by karelz** [comment]
@weshaggard @ericstj do you know the answer?

**Comment by ericstj** [comment]
https://github.com/dotnet/versions is a good source for complete info.  For each repo we list out the packages it produces from various branches.  

@leecow do you have a package list markdown for 1.0?

The offline cache has everything you need for a portable app.  There are some .NET Core packages that aren't referenced by default and those wouldn't be in the offline cache, so if you want those you'll need to mirror them.

**Comment by leecow** [comment]
We didn't create a manifest.md for 1.0.0 but should probably do that. In the meantime svick's suggestion will work, ie, the Microsoft.NETCore.App and CoreCLR sections from the [1.0.1 manifest](https://github.com/dotnet/core/blob/master/release-notes/1.0/1.0.1-manifest.md) is the correct list of what dotnet unpacks. The 1.0.0 packages versions can be found in the location Eric mentions. Direct links to the files: [CoreCLR](https://github.com/dotnet/versions/blob/master/build-info/dotnet/coreclr/release/1.0.0/LKG_Packages.txt), [CoreFX](https://github.com/dotnet/versions/blob/master/build-info/dotnet/corefx/release/1.0.0/LKG_Packages.txt)

**Comment by karelz** [comment]
@leecow do you plan to create and publish the manifest.md?

**Comment by leecow** [comment]
[1.0 Manifest](https://github.com/dotnet/core/blob/master/release-notes/1.0/1.0.0-manifest.md) added. https://github.com/dotnet/core/pull/275 

/cc @karelz @lextm

**Comment by lextm** [comment]
Thanks. Very useful.
