### ISSUE TITLE
DbDataReader does not have Close method, even though it inherits from IDataReader

### ISSUE THREAD

**Issue by jaredmoo** [dotnet/corefx#11949]
I'm unable to compile code that calls or overrides `DbDataReader.Close()`. However `DbDataReader` inherits from `IDataReader`, which has a `.Close()`. method. What's even more baffling is that when I look at the source, [DbDataReader does indeed implement .Close()](https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/src/System/Data/Common/DbDataReader.cs#L288). 

Repro: 
1. In VS2015 create new .NET Core library
2. Add System.Data.Common v4.1.0 nuget reference
3. Add below code

I've uploaded the repro as a gist at https://gist.github.com/jaredmoo/52f76f513ceff6a1240bac30aa0152e3

```
using System;
using System.Data;
using System.Data.Common;

namespace DbDataReaderTest
{
    public class Class1
    {
        public static void DoSomethingInterface(IDataReader reader)
        {
            reader.Close();
        }

        public static void DoSomethingAbstractBase(DbDataReader reader)
        {
            reader.Close(); // error CS1061: 'DbDataReader' does not contain a definition for 'Close' and no extension method 'Close' accepting a first argument of type 'DbDataReader' could be found (are you missing a using directive or an assembly reference?) 
            DoSomethingInterface(reader); // confirmed, DbDataReader inherits IDataReader
        }
    }

    public abstract class MyDbDataReader : DbDataReader
    {
        public override void Close() // error CS0115: 'MyDbDataReader.Close()': no suitable method found to override
        {

        }
    }
}

```

**Comment by svick** [comment]
In the reference assembly for `System.Data.Common`, [`Close()` is an explicit interface implementation in `DbDataReader`](https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/ref/System.Data.Common.cs#L364). That means you can't call it directly (only if you cast the `DbDataReader` to `IDataReader`) and you can't `override` it. What you can do is to add your own implicit or explicit implementation for it:

```c#
public class Class1
{
    public static void DoSomethingInterface(IDataReader reader)
    {
        reader.Close();
    }

    public static void DoSomethingAbstractBase(DbDataReader reader)
    {
        ((IDataReader)reader).Close();
        DoSomethingInterface(reader);
    }
}

public abstract class MyDbDataReaderImplicit : DbDataReader, IDataReader // important
{
    public void Close()
    {
    }
}

public abstract class MyDbDataReaderExplicit : DbDataReader, IDataReader
{
    void IDataReader.Close()
    {
    }
}
```

Whether this is working as expected I'm not sure, but it makes sense for me for .Net Standard 1.x, where the general approach is "`Close()` does not exist, use `Dispose()` instead". The `Close()` here could not be removed, so it was hidden. I would expect .Net Standard 2.0 to expose the `Close()` as a `public virtual` method, for better compatibility with .Net Framework.

Also, [the documentation says that `Close()` is `public virtual`](https://docs.microsoft.com/en-us/dotnet/core/api/system.data.common.dbdatareader#System_Data_Common_DbDataReader_Close), which is wrong.

**Comment by jaredmoo** [comment]
I'm ok with Close() not existing, but the current situation is completely unintuitive and poorly documented when porting from NetFx code.

**Comment by jaredmoo** [comment]
What really threw me off is that the reference assembly is different from the source code and the documentation.

**Comment by karelz** [comment]
Do you have suggestion which docs to improve and how?

**Comment by svick** [comment]
@karelz [The API reference for `DbDataReader` shows `Close()` as `public virtual` method](https://docs.microsoft.com/en-us/dotnet/core/api/system.data.common.dbdatareader#System_Data_Common_DbDataReader_Close), when it's actually an explicit interface implementation.

Not sure how exactly to fix that, maybe changing the implementation (i.e. [`src`](https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/src/System/Data/Common/DbDataReader.cs#L288), not [`ref`](https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/ref/System.Data.Common.cs#L364)) to also be an explicit interface implementation would work, assuming it wouldn't be a breaking change.

**Comment by karelz** [comment]
@weshaggard do you know why we have discrepancy between [`src`](https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/src/System/Data/Common/DbDataReader.cs#L288) and [`ref`](https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/ref/System.Data.Common.cs#L364) of `DbDataReader.Close`?

**Comment by jaredmoo** [comment]
Docs that would have helped:

- Official API docs: https://docs.microsoft.com/en-us/dotnet/core/api/system.data.common.dbdatareader#System_Data_Common_DbDataReader_Close
- NetFx to NetCore migration guide that is google searchable with keywords "dbdatareader close .net core"

**Comment by weshaggard** [comment]
I don't have the context on this particular issue but in general we were preferring Dispose of Close, but in this case we couldn't remove Close completely because it was on the IDataReader interface so we just implemented it explicitly in ref (https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/ref/System.Data.Common.cs#L364). 

It is compatible to have it be explicit in the ref and implicit in the implementation we use that trick from time to time to hide members on the types. 

Given our new direction to be more compatibly I think we should update the ref to make the Close method implicit like the implementation.

**Comment by saurabh500** [comment]
The expectations from this issue is not clear.
The documentation pointed out by @jaredmoo lists `Close()` as explicit interface implementation. i.e. `IDataReader.Close()`
The NetStandard 2.0 will have Close() implemented by `DbDataReader` as well and the documentation should be updated with Netstandard 2.0 is out.

**Comment by jared-moore** [comment]
Apparently the docs have changed since this was filed, since the anchor in the link that I provided no longer exists - https://docs.microsoft.com/en-us/dotnet/core/api/system.data.common.dbdatareader#System_Data_Common_DbDataReader_Close 

The NetStandard 2.0 fix of having Close() implemented normally instead of explicitly is the best fix from my point of view.

Thanks!

**Comment by jaredmoo** [comment]
Apparently the docs have changed since this was filed, since the anchor in the link that I provided no longer exists - https://docs.microsoft.com/en-us/dotnet/core/api/system.data.common.dbdatareader#System_Data_Common_DbDataReader_Close 

The NetStandard 2.0 fix of having Close() implemented normally instead of explicitly is the best fix from my point of view.

Thanks!

**Comment by saurabh500** [comment]
@jaredmoo Thanks for the confirmation.
