### ISSUE TITLE
System.Data.SqlClient.SqlConnection.ChangePassword not implemented

### ISSUE THREAD

**Issue by MitchellSternke** [dotnet/corefx#11958]
It appears that the SqlConnection class does not have ChangePassword() as an available method. Without this, client applications cannot allow the user to change their password when it is detected that it has expired or needs to be changed. They must log on as a different user, or use a program supporting password change (such as SQL Server Management Studio).

**Comment by saurabh500** [comment]
Implemented by @joelbraun
