### ISSUE TITLE
To Verify the Next Release of Meta-package in UWP with Serialization Tests

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#11954]

**Comment by karelz** [comment]
@shmao I assume you will do the work, so assigning to you.

**Comment by huanwu** [comment]
Verified. All pass.
My project.json file:
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2",
    "System.Xml.XmlSerializer": "4.3.0-preview1-24527-03",
    "System.Private.DataContractSerialization": "4.3.0-preview1-24527-0",
    "System.Runtime.Serialization.Xml": "4.3.0-preview1-24530-04",
    "System.Runtime.Serialization.Json": "4.3.0-preview1-24527-03",
    "xunit.assert": "2.1.0",
    "System.Collections.NonGeneric": "4.0.1-rc4-24131-00"
