### ISSUE TITLE
WinHttpHandler could query individual headers instead of double buffering them in the managed address space

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#11979]
Currently, WinHttpHandler is double buffering instead of lazily extracting headers as they are requested by the application.

This is debatable and would need to be profiled. Lacking the necessary telemetry it's hard to understand if most apps really care about the headers or not. If not, this change should be made to avoid consuming both native-heap and managed-heap memory for the same information.

**Comment by karelz** [comment]
We should not have this problem with SocketsHttpHandler.
