### ISSUE TITLE
WinHttpHandler is allocating twice the required buffer for headers

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#11978]
GetResponseHeaderCharBufferLength is calling into WinHttpQueryHeaders which returns the buffer size in bytes not C# char which is 16bit wide.

We should allocate byte[] instead and extract the UTF8 encoded characters from the byte array.

**Comment by davidsh** [comment]
>GetResponseHeaderCharBufferLength is calling into WinHttpQueryHeaders which returns the buffer size in bytes not C# char which is 16bit wide.

Did you verify this by running code or reading the documentation on MSDN?  I'm wondering if there is any W vs. A WinHTTP API differences ?  For example, there are A versions of WinINet APIs vs. W versions. So maybe the buffer count is 16-bit chars in the W version of WinHTTP APIs.

**Comment by CIPop** [comment]
@davidsh Yes, the way I found this was comparing the handler code with the native perf baseline application that I'm writing (64bit target). 

https://msdn.microsoft.com/en-us/library/windows/desktop/aa384102(v=vs.85).aspx :

>lpdwBufferLength [in, out]
>Pointer to a value of type DWORD that specifies the length of the data buffer, __in bytes__. When the function returns, this parameter contains the pointer to a value that specifies the length of the information written to the buffer. When the function returns strings, the following rules apply.
>If the function succeeds, lpdwBufferLength specifies the length of the string, __in bytes, minus 2__ for the terminating null.
>If the function fails and ERROR_INSUFFICIENT_BUFFER is returned, lpdwBufferLength specifies the __number of bytes that the application must allocate to receive the string__.

**Comment by karelz** [comment]
Next step: Do the change and measure perf on a test case.
Should be trivial

**Comment by madsiberian** [comment]
Hello!

I want to fix this issue but I don't understand one thing about System.Net.Http.WinHttpHandler solution: why actual source code for the assembly is included in System.Net.Http.WinHttpHandler.Unit.Tests project and not in System.Net.Http.WinHttpHandler project?
Of course it is not related to the issue but if one does not understand basic layout of solution than it is better to not start making changes at all.
Could please someone help me?

**Comment by karelz** [comment]
There is only `WinHttpHandlerTest` class in [UnitTests file](https://github.com/dotnet/corefx/blob/a999d1094734b1ba7248d3e92e576f9fe4567f5b/src/System.Net.Http.WinHttpHandler/tests/UnitTests/WinHttpHandlerTest.cs).
The source code is in [WInHttpHandler.cs](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs)

Here's my [search](https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=%22public+class+WinHttpHandler%22&type=)

**Comment by karelz** [comment]
I sent you contribution invite, ping me when you accept, so that I can assign the issue to you.
See links on our main page to our contributor docs (under constructions) -- if there is anything missing, feel free to ask, and/or edit the docs with ideas and how-tos.

**Comment by madsiberian** [comment]
Thank you for quick reply!
Class placement is OK: it is in src/ folder. However, it is not referenced in the project that resides in src/ folder. Instead we find it in the project from tests/ folder:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http.WinHttpHandler/tests/UnitTests/System.Net.Http.WinHttpHandler.Unit.Tests.csproj#L91
That is what bothers me. Or I simply don't understand the idea.

**Comment by stephentoub** [comment]
The source is included via the https://github.com/dotnet/corefx/blob/master/src/System.Net.Http.WinHttpHandler/src/System.Net.Http.WinHttpHandler.msbuild file, which is then included both here https://github.com/dotnet/corefx/blob/master/src/System.Net.Http.WinHttpHandler/src/System.Net.Http.WinHttpHandler.csproj#L21 and here https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System.Net.Http.csproj#L153-L160.

**Comment by madsiberian** [comment]
Now I see it, thanks! Maybe VS solution explorer should display this kind of links...

**Comment by madsiberian** [comment]
Do I understand it correctly that only GetResponseHeaderCharBufferLength method should be updated? And GetResponseHeader & GetResponseHeader must be left intact?
Sorry for delay: I never used Perf before and have to learn it.

**Comment by karelz** [comment]
@CIPop @davidsh can you please advise?

**Comment by CIPop** [comment]
>> GetResponseHeaderCharBufferLength is calling into WinHttpQueryHeaders which returns the buffer size in bytes not C# char which is 16bit wide.
>> We should allocate byte[] instead and extract the UTF8 encoded characters from the byte array.

> Do I understand it correctly that only GetResponseHeaderCharBufferLength method should be updated? And GetResponseHeader & GetResponseHeader must be left intact?

@madsiberian thanks for your interest. Yes, I believe that's true: you'll need to first understand the Win32 API (see MSDN referred to in my [comment](https://github.com/dotnet/corefx/issues/11978#issuecomment-248983296)) then figure out where `char` (2-byte wide) is used instead of byte (1-byte wide). 

Running the outerloop tests on Windows should be sufficient to check that everything works as expected.

**Comment by madsiberian** [comment]
@CIPop But what if we allocate char[] buffer of a smaller size instead of switching to byte[] buffer?
As far as I understand, we only need to divide bufferLength returned by WinHttpQueryHeaders by sizeof(char).

**Comment by CIPop** [comment]
> char[] buffer of a smaller size instead of switching to byte[] buffer

(I don't remember much about this bug) What would be the advantage?

**Comment by madsiberian** [comment]
@CIPop After removing my changes and double-checking existing state of the code I realized that QueryHeaders already does exactly that -- divides bufferLengthInBytes by sizeof(char).
I am really sorry for turning my lack of attention into everyone's distraction. Let's start anew -- with questions that I should have asked before:
> We should allocate byte[] instead and extract the UTF8 encoded characters from the byte array.
1. Given that WinHttpQueryHeaders works with wchar array, why should we consider using utf-8? Doesn't it effectively match char[] array that we already use?
> GetResponseHeaderCharBufferLength is calling into WinHttpQueryHeaders which returns the buffer size in bytes not C# char which is 16bit wide.
2. Given that QueryHeaders already divides bufferLengthInBytes by sizeof(char), why do we have 'twice the required buffer' issue at all?

**Comment by CIPop** [comment]
> Given that WinHttpQueryHeaders works with wchar array, why should we consider using utf-8? Doesn't it effectively match char[] array that we already use?

You're right: we should then use char[] but correctly calculate the length as you originally proposed.

> Given that QueryHeaders already divides bufferLengthInBytes by sizeof(char), why do we have 'twice the required buffer' issue at all?

Have you tried to check the buffer length in a debugger? 
If it's the correct size, feel free to close the issue.

**Comment by madsiberian** [comment]
@CIPop Yes, it returns correct buffer length in debug session with fake Interop.

**Comment by madsiberian** [comment]
@karelz Could you please close the issue as @CIPop proposed?

**Comment by davidsh** [comment]
>Yes, it returns correct buffer length in debug session with fake Interop.

What does "fake Interop" mean?  Perhaps our mocking WinHTTP with our fake Interop is actually returning the wrong thing based on a set of wrong assumptions.

I would recommend you debug this using real interop (WinHTTP) and see what it returns.

**Comment by CIPop** [comment]
Based on @madsiberian's investigation and explanation I think the correct buffers are calculated. I'm closing the issue.

@madsiberian if the real-WinHTTP debugger session gives you a different buffer, please reopen / add a comment here.
