### ISSUE TITLE
WinHttp exception thrown when POST'ing to secure server thru authenticating proxy

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#11973]
This was discovered from a partner testing out Nano server using CoreFx components.

The following repro ends up throwing ERROR_WINHTTP_INCORRECT_HANDLE_STATE from the  `WinHttpRequestCallback.OnRequestSendingRequest` method when the following are true:

- POST'ing a request body to a secure (TLS/SSL) server
- Connecting thru an authenticating proxy
- Using a callback specified in the `HttpClientHandler.ServerCertificateCustomValidationCallback`

**Comment by epignosisx** [comment]
Based on this document:

https://github.com/dotnet/core/blob/master/release-notes/1.1/1.1-preview1-commits.md

 this issue is going in 1.1.0, but this issue is in milestone 1.2.0.

Which one is correct? We are  affected by this issue.

**Comment by davidsh** [comment]
>this issue is going in 1.1.0, but this issue is in milestone 1.2.0. Which one is correct? We are affected by this issue.

I've reset the issue Milestone to 1.1 to clarify that the bug was back-ported to the 1.1 branch after being fixed in current (1.2 branch).

**Comment by epignosisx** [comment]
Great, thanks!
