### ISSUE TITLE
Improve code coverage for System.Linq.Expressions

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1198]
According to the current code coverage report, this library is only at ~40%. Our general goal is closer to 90%, though this will depend on the library. We should investigate to see whether the current coverage level is appropriate, and if not, improve our test suites to provide better coverage.

**Comment by rafidka** [comment]
Since I am working on improving the coverage for System.Linq, can I get this one as well?

**Comment by stephentoub** [comment]
@rafidka, this library is fairly different, so I'd be surprised if there was a lot of reuse possible.  You're still interested?  I love the enthusiasm, but do you want to hold off until you're further along with System.Linq?

**Comment by rafidka** [comment]
Yeah, I know it is different actually, but since I have experience working on Compilers and Computer Algebra, I found this task interesting to work on.

I don't mind holding off until I make progress with System.Linq.

**Comment by stephentoub** [comment]
Thanks to the efforts of multiple folks, this is now at ~84%.
