### ISSUE TITLE
Proposal: Stack and Queue should implement ICollection<T>

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#11990]
## Background

`Stack` and `Queue` currently implement `ICollection` and `IReadOnlyCollection<T>`, but not the generic `ICollection<T>` interface. This means that they miss out on many valuable LINQ optimizations for such collections; [here](https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/SequenceEqual.cs#L37) [are](https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/AppendPrepend.cs#L192) a couple of examples. In fact, these optimizations are not even limited to LINQ; for example, making a copy of a Queue via

```cs
var queue = GetQueueOf<int>();
var copy = new Queue<int>(queue);
```

will be artificially slow, since [Queue's constructor](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/Queue.cs#L56-L63) calls `EnumerableHelpers.ToArray`, which goes down a slow path if the input is not an ICollection. Similarly, [here](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/List.cs#L705) is another such optimization in `List.InsertRange`.

## Proposal

We should explicitly implement the `ICollection<T>` interface on both of these classes. For any method that doesn't have very clear semantics, we can simply throw a `NotSupportedException` just like arrays do for certain `IList` methods.

```cs
namespace System.Collections.Generic
{
    public class Stack<T> : ICollection<T>, IEnumerable<T>, ICollection, IReadOnlyCollection<T>
    {
        bool ICollection<T>.IsReadOnly { get; }
        void ICollection<T>.Add(T item);
        bool ICollection<T>.Remove(T item);
    }

    public class Queue<T> : ICollection<T>, IEnumerable<T>, ICollection, IReadOnlyCollection<T>
    {
        bool ICollection<T>.IsReadOnly { get; }
        void ICollection<T>.Add(T item);
        bool ICollection<T>.Remove(T item);
    }
}
```

Some `ICollection` methods like `Count` and `CopyTo` are excluded since the collections already contain implementations of those methods.

### `Add` implementations

`Add` should just call `Enqueue` for Queue, but it is somewhat vague for Stack (the caller is probably assuming that the item is being added to the *end* of the collection). I suggest we throw a `NotSupportedException` rather than calling `Push`.

@justinvp @terrajobst

**Comment by svick** [comment]
The added methods don't seem like they would be a good fit for `Queue<T>` and `Stack<T>`, I think it was a deliberate decision not to implement `ICollection<T>` for them.

Couldn't the optimizations be written in terms of `IReadOnlyCollection<T>` in addition to (or instead of) `ICollection<T>`? Is the reason why they're not that casting for variant interfaces is more expensive? If that's the case, would it be possible to instead fix or work around that issue?

**Comment by jamesqo** [comment]
> The added methods don't seem like they would be a good fit for Queue\<T\> and Stack\<T\>

Why not? They are all explicitly-implemented. No one will ever see them unless they cast to `ICollection<T>`. The immutable collections implement both the regular and read-only interfaces, and IMO those types are even worse fits since they have to stub out all of the methods that mutate the collection.

> Couldn't the optimizations be written in terms of IReadOnlyCollection\<T\> in addition to (or instead of) ICollection\<T\>?

No. `IReadOnlyCollection<T>` only supports the `Count`. This is good for e.g. pre-allocating an array before copying over the items, but there's not much else you can do with it since you will still need to use `foreach` and virtual dispatch, not to mention allocate an enumerator. With `ICollections` you can call `CopyTo` which is an order of magnitude faster in comparison, since we only make 1 virtual call for the entirety of the collection.

**Comment by svick** [comment]
> Why not? They are all explicitly-implemented. No one will ever see them unless they cast to `ICollection<T>`. The immutable collections implement both the regular and read-only interfaces, and IMO those types are even worse fits since they have to stub out all of the methods that mutate the collection.

At least they implement the interface correctly. I don't think it's acceptable for `IsReadOnly` to return `false`, if `Add()` throws `NotSupportedException`.

And I don't think `Remove()` would be useful here either (if it was, it wouldn't be implemented explicitly).

> With `ICollection`s you can call `CopyTo` which is an order of magnitude faster in comparison, since we only make 1 virtual call for the entirety of the collection.

I didn't realize this was about `CopyTo`. Maybe it would make sense to create a new `ICopyableCollection<T>` interface and use that?

**Comment by karelz** [comment]
cc: @Priya91 @ianhays

**Comment by jamesqo** [comment]
> At least they implement the interface correctly. I don't think it's acceptable for IsReadOnly to return false, if Add() throws NotSupportedException.

Then we can simply have `IsReadOnly` return true. readonly-ness provides no guarantees about immutability anyway; for example, `Array.IsReadOnly` is true.

> And I don't think Remove() would be useful here either

That's why the methods are being explicitly implemented. We're not expecting people to use these new additions, just adding them for the sake of implementing an interface.

> I didn't realize this was about CopyTo. Maybe it would make sense to create a new ICopyableCollection\<T\> interface and use that?

IMO, `IReadOnlyCollection<T>` should simply have been 'done right' in the first place (no variance, has `CopyTo`, `Contains`, etc.). I think there are already enough collection interfaces; it's not a good idea to introduce yet another one people have to implement.

**Comment by Priya91** [comment]
@jamesqo Implementing ICollection over Stack and Queue doesn't go well conceptually with the definition of these data structures, like defining Add and Remove over push/pop or enqueue/dequeue. Moreover the suggested improvements do not seem worth over the cost of porting these changes over to Full Framework for app compat. It's not worth micro-optimizing code, can you provide more usage data on performance bottleneck due to this.. If this indeed is an issue, then maybe depending on the scenario consider using other collection types.

**Comment by jamesqo** [comment]
@Priya91 To address your arguments:

> Implementing ICollection over Stack and Queue doesn't go well conceptually with the definition of these data structures, like defining Add and Remove over push/pop or enqueue/dequeue.

We don't necessarily *have* to define Add over Push or Enqueue if we don't think the semantics match-- we can just throw a `NotSupportedException` from the method. (For example, arrays implement `IList<T>` but don't support adding, so they just throw a NSE.) We're just adding these methods for the sake of implementing ICollection.

> do not seem worth over the cost of porting these changes over to Full Framework for app compat.

Can you please help me understand compatibility issues would this cause?

> It's not worth micro-optimizing code, can you provide more usage data on performance bottleneck due to this.

I would say this is more than a 'micro-optimization'-- implementing `ICollection` can yield massive perf benefits for many LINQ methods. For example, in my recently merged PR #11492 there is upto a 40x speedup and 5x reduction in gen0 allocations when all inputs to `Concat` are ICollections (I posted the data in the description).

There are plenty more methods where `ICollection` is optimized for as well-- [`ToArray`](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Collections/Generic/EnumerableHelpers.cs#L19), `ToList`, `Append` / `Prepend`, etc.

**Comment by Priya91** [comment]
> We're just adding these methods for the sake of implementing ICollection.

That doesn't go well with the abstraction of these types, and not a great API design.

> Can you please help me understand compatibility issues would this cause?

We want to maintain API parity with .NET Core and Full Framework, so libraries can be made to target multiple app frameworks. So adding new apis to .NET Core means adding it to Full Framework.

> For example, in my recently merged PR #11492 there is upto a 40x speedup and 5x reduction in gen0 allocations when all inputs to Concat are ICollections.

I see the optimizations are made around Count property, and these types implement ICollection that has a ICollection.Count. What other apis in ICollection<T> that are useful in providing the optimizations?

**Comment by jamesqo** [comment]
@Priya91 

> That doesn't go well with the abstraction of these types, and not a great API design.

I disagree. Types like `Array` and the immutable collections do not support adding or removing, and yet they still implement `IList<T>` and `ICollection<T>`. This is valid since `ICollection<T>.IsReadOnly` returns false, so they are allowed to simply throw NotSupportedExceptions in their Add/Remove methods.

@terrajobst [wrote a blog post](https://blogs.msdn.microsoft.com/dotnet/2013/09/12/immutable-collections-are-now-rc/) on immutable collections back in 2013, and if you skip to "Implementing the mutable interfaces," he says

> It’s worth pointing out that this declaration does not have a correctness issue – you cannot mutate an instance of ImmutableList<T> by casting it to a mutable interface. For example, calling IList<T>.Add would throw NotSupportedException.

> The mutable interfaces always supported a read-only mode, which means that consumers can’t change the contents. This mode is exposed via ICollection.IsReadOnly, which all mutable interfaces inherit from. Thus, the concrete immutable collection types all implement the existing, mutable interfaces in a read-only fashion, which means that IsReadOnly returns true and all methods that would mutate the collection throw NotSupportedException.

Why not do the same for Stack and Queue?

> We want to maintain API parity with .NET Core and Full Framework, so libraries can be made to target multiple app frameworks. So adding new apis to .NET Core means adding it to Full Framework.

I see. However, given that this is only adding 3 (small) new methods and an additional interface in the class declaration, perhaps this should not be as hard to port as some other proposals?

> What other apis in ICollection<T> that are useful in providing the optimizations?

The most valuable member of `ICollection<T>` is not `Count`, actually, but `CopyTo`. For example, consider [`Enumerable.ToArray`](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Collections/Generic/EnumerableHelpers.cs#L27): Normally, using the `IEnumerable<T>` api, we would have to copy over the elements by 1) calling `GetEnumerator` (which is an allocation) and then 2) calling `MoveNext` and `Current` for each element in the enumerable, which means that if the sequence has N items then we make 2 * N virtual method calls.

However, with `CopyTo`, we only make a single virtual method call for the entire collection (to `CopyTo`), and let that take care of the copying. For collections like Stack or Queue, which are backed by arrays, this means that copying 1 element is now as fast as indexing into an array. This is what is providing the 40x speedups.

**Comment by karelz** [comment]
I am torn on this one. Your Immutable parallel sounds reasonable (at least to me). However, I am missing clear value of the work. You mentioned some potential wins in perf. Can you make them part of the proposal with more details? Are they on paths/patterns which are commonly used?

**Comment by karelz** [comment]
We discussed it briefly in API review. We all (incl. @weshaggard @terrajobst) agreed that the semantics of ICollection on Stack/Queue with IsReadOnly=true feels like a weird workaround (the collections are not read only after all). With IsReadOnly=false, the semantics is even more weird as discussed above.
The value of few perf optimizations (for not-so-commonly-used code patterns) does not seem to justify the 'weird' API.

@weshaggard suggested to consider getting most of the perf wins by using non-generic ICollection.Count.

As usual: If you think we missed anything important (esp. from the usage point of view), feel free to raise it.

**Comment by terrajobst** [comment]
@jamesqo 

> @terrajobst wrote a blog post on immutable collections back in 2013, and if you skip to "Implementing the mutable interfaces," he says

>> It’s worth pointing out that this declaration does not have a correctness issue – you cannot mutate an instance of ImmutableList by casting it to a mutable interface. For example, calling IList.Add would throw NotSupportedException.

>> The mutable interfaces always supported a read-only mode, which means that consumers can’t change the contents. This mode is exposed via ICollection.IsReadOnly, which all mutable interfaces inherit from. Thus, the concrete immutable collection types all implement the existing, mutable interfaces in a read-only fashion, which means that IsReadOnly returns true and all methods that would mutate the collection throw NotSupportedException.

> Why not do the same for Stack and Queue?

I don't think it makes sense for `Stack<T>` and `Queue<T>` because they are conceptually neither read-only nor collections you can add or remove from. They have a very specific contract for how data gets in and out.

Do you have any other scenarios besides copying where treating them as `ICollection`/`ICollection<T>` would be beneficial? I've used both stacks and queues quite a bit but I never had a scenario where I needed to pass them to a method taking a regular collection. The reason being that these data structures are mostly used inside a method for implementing specific algorithms -- they are rarely persisted in fields.

Of course, better perf is always good, but it seems this could be realized by specializing the constructors for `Stack<T>` and `Queue<T>`, no?

**Comment by jamesqo** [comment]
@terrajobst 

> I don't think it makes sense for `Stack<T>` and `Queue<T>` because they are conceptually neither read-only nor collections you can add or remove from.

The same would seem to apply to `Array`, yet [that is marked readonly](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Array.cs#L2805-L2807).

> Do you have any other scenarios besides copying where treating them as `ICollection` / `ICollection<T>` would be beneficial?

If you mean copying as in creating another `Queue` / `Stack` out of an existing one, and not copying in general, then yes. In addition to `ToArray` which I mentioned above, things like [`ToList`](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/List.cs#L87) or `Concat` are optimized to use `CopyTo` if the input is an `ICollection<T>`, which is an order of magnitude (maybe 7x) faster than using `foreach`.

> Of course, better perf is always good, but it seems this could be realized by specializing the constructors for `Stack<T>` and `Queue<T>`, no?

The extra type-casts would add significant cost for all non-Stacks and Queues.

**Comment by SamuelEnglard** [comment]
@jamesqo `Array` is read-only in that you cannot add or remove to it. Yes you can "add" and "remove" from `Stack<T>` and `Queue<T>` but "adding" and "removing" in context of them does not mean what the `ICollection<T>` interface implies.

> The extra type-casts would add significant cost for all non-Stacks and Queues.

I think the following constructors should solve issues you've shown without type-casting

```csharp
public class Stack<T>
{
    public Stack(ICollection<T> collection);
    public Stack(Stack<T> other);
}

public class Queue<T>
{
    public Queue(ICollection<T> collection);
    public Queue(Queue<T> other);
}

public class List<T>
{
    public List(Stack<T> stack);
    public List(Queue<T> queue);
}

public class Collection<T>
{
    public Collection(Stack<T> stack);
    public Collection(Queue<T> queue);
}
```
