### ISSUE TITLE
Evaluate dependency on S.S.Permissions and S.CodeDOM from System.Private.Xml

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#12000]
Not sure if there is already a tracking issue for this or not yet (if there is one please feel free to close). 

There is a ton of stubbed out APIs at https://github.com/dotnet/corefx/tree/master/src/System.Private.Xml/src/Workarounds which we need to eliminate and either remove by eliminating the dependencies or move to building against netstandard17 and using the new types we have exposed.

cc @danmosemsft @krwq

**Comment by sepidehMS** [comment]
Done by https://github.com/dotnet/corefx/pull/12194

**Comment by weshaggard** [comment]
I've left a number of more clean-up comments in https://github.com/dotnet/corefx/pull/12194 that I think we need to follow-up on, so re-opening this issue. Feel free to close again if you already have other issues tracking those things.

**Comment by danmosemsft** [comment]
@weshaggard Can you help me understand the problem with the dependency on CodeDOM? Isn't it okay for .NET Core's implementation of NS2.0 types to depend on non-NS2.0 types? Especially if it makes the implementation "better".

**Comment by weshaggard** [comment]
As we chatted CodeDom and CAS are 2 dependencies we need to better understand if we need them or not. However this particular issue is more about the other workaround code that exists in the XML project. We need to clean those up, I've left a number of comments pointing them out in https://github.com/dotnet/corefx/pull/12194
