### ISSUE TITLE
Introduce "virtual reference" concept

### ISSUE THREAD

**Issue by Opiumtm** [dotnet/corefx#12007]
There is `WeakReference<T>` class. It is a special case of concept which could be called "virtual reference".

Introduce `VirtualReference<T>` abstract class (signature is exact of `WeakReference<T>`)

``` C#
public abstract class VirtualReference<T> where T : class
{
    public abstract bool TryGetTarget(out T target);
}
```

and make WeakReference<T> implementation of this abstract class.

``` C#
public sealed class WeakReference<T> : VirtualReference<T> where T : class
{
    public override bool TryGetTarget(out T target)
    {
        ...
    }
}
```

This would generalize and provide common API for many kinds of object proxies, interop scenarios, reconstructable caches, lazy-allocated objects and so on.

**Comment by svick** [comment]
> This would generalize and provide common API for many kinds of object proxies, interop scenarios, reconstructable caches, lazy-allocated objects and so on.

I think it would help if you provided some specific examples where implementing `VirtualReference<T>` would make sense and also where operating on `VirtualReference<T>` would be useful.

**Comment by Opiumtm** [comment]
@svick 
It would make "proxy" concept more transparent, for example.
Virtual reference would become end point for a proxy which marshal calls across some boundary.
.NET Core as far as I know doesn't implement `RealProxy` and `MarshalByRef` and maybe for good, as dynamically generated proxies invoked some behind-the-scenes CLR magic to make illusion you are using object of exactly same type.

Maybe "virtual reference" concept should be reworked (it's a simple proposal based on existing `WeakReference<T>` signature). But it looks good enough to standardize proxy logic using interface as virtual reference type argument.

**Overall idea is to introduce standardized endpoint for reference which isn't regular CLR reference, but indeed is a reference in broad sense.** When reference target getter is invoked it would create proxy object just in time (or return cached proxy object having weak reference to it and recreate proxy as needed if cached weak reference became stale when no other object keep hard reference to proxy).

**Comment by AlexGhiondea** [comment]
As a next step we would need a formal API proposal that also contains use cases for this. @Opiumtm would you be interested in expanding on your proposal?

**Comment by jnm2** [comment]
You're talking about `WeakReference<T>`, `Lazy<T>`, `Proxy<T>`, maybe `CacheToken<T>`-- isn't `Func<T>` as good an abstraction of all of these as any?

**Comment by Opiumtm** [comment]
@jnm2 `Func<T>` isn't good abstraction as it is not class type but delegate type.
One of the motivation behind this proposal is to integrate "virtual references" into C# language later, if C# design team would do it.
C# operator `?.` is a primary candidate to support "virtual references" at language level.

**Comment by jnm2** [comment]
@Opiumtm designing a feature that no one needs yet because you might need it later is a bad idea. We'll certainly miss the real heart of the issue and down the road have to start from scratch or just live with hacks.

**Comment by AlexGhiondea** [comment]
@Opiumtm if we think this is something that the compiler team might be interested in using, then maybe we should file an issue on the Roslyn side for considering this feature.

**Comment by stephentoub** [comment]
> One of the motivation behind this proposal is to integrate "virtual references" into C# language later, if C# design team would do it.

If the goal is for a C# feature, this should really start as a language proposal in the csharplang repo.  Whatever types would be necessary to support it could grow out of that.

As is, I don't think this is actionable for corefx.

Thanks.
