### ISSUE TITLE
Enumerable.Contains ICollection optimization should go in a different overload

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#12033]
Here's the current source for `Enumerable.Contains`:

```cs
public static bool Contains<TSource>(this IEnumerable<TSource> source, TSource value)
{
    ICollection<TSource> collection = source as ICollection<TSource>;
    if (collection != null)
    {
        return collection.Contains(value);
    }

    return Contains(source, value, null);
}

public static bool Contains<TSource>(this IEnumerable<TSource> source, TSource value, IEqualityComparer<TSource> comparer)
{
    if (comparer == null)
    {
        comparer = EqualityComparer<TSource>.Default;
    }

    if (source == null)
    {
        throw Error.ArgumentNull(nameof(source));
    }

    foreach (TSource element in source)
    {
        if (comparer.Equals(element, value))
        {
            return true;
        }
    }

    return false;
}
```

as you can see, in the comparer-less overload, it checks if the source implements ICollection first and then calls `Contains` on that collection if so. However, this is not done in the overload that doesn't accept a comparer.

We may want to consider instead checking for ref equality to `EqualityComaprer<T>.Default` in the other overload, and then applying the ICollection optimizaion. This will potentially make code that calls `Contains` with a comparer, i.e. a custom data structure that accepts a comparer in its constructor, faster.

**Comment by ViIvanov** [comment]
Consider a case when we call an overload with comparer for a `HashSet<string>` initialized on the ignore-case comparer and specify a default comparer or null as a parameter. It should not call a `HashSet<>::Contains` method.

**Comment by stephentoub** [comment]
Yes, as @Vilvanov highlights, that is not an equivalent operation, and thus not a safe optimization. We can't know if the semantics of the ICollection.Contains implementation matches that of the explicitly-provided comparer.

**Comment by jamesqo** [comment]
@stephentoub @Vilvanov I see. Is there a rationale for having `Contains(value)` and `Contains(value, null)` behave differently for such collections that use their own comparer? Should we remove the ICollection optimization altogether?

**Comment by stephentoub** [comment]
> Should we remove the ICollection optimization altogether?

No, it's been this way since I believe the beginning of LINQ.

> Is there a rationale for having  Contains(value)  and  Contains(value, null)  behave differently

I can't speak to the original design, but in one case you're explicitly passing in a value and in another you're not; seems reasonable for them to have different behaviors.
