### ISSUE TITLE
Would it be possible to shrink the field size of LinkedList?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#12032]
Noticed that 0e62a60 added a new field to `LinkedList`, `_siInfo`, for serialization. Since that and SyncRoot are rarely used, perhaps they can be combined into a `StrongBox<SerializationInfo>` to shrink the size of LinkedList.

**Comment by karelz** [comment]
@Priya91 @ianhays any opinion on this one?

**Comment by Priya91** [comment]
the size of linked list is already fairly large, so saving one reference will not add much difference to the size and not worth the complexity.

**Comment by ianhays** [comment]
I agree with Priya here. I think if we add more of these seldom-used fields then we look into doing something like this, but for now I'd say it isn't worth the code complexity.
