### ISSUE TITLE
System.Reflection.Emit.DynamicILInfo

### ISSUE THREAD

**Issue by dudikeleti** [dotnet/corefx#12055]
I rely in my code on this type. Is it planned to include it? Currently in [.NET API Catalog](https://apisof.net/) it's not seem to exist in .NET Standard or .NET Core App.

Search for this in this repository does not give any hint.
- (Same issue with System.Reflection.MethodBody and Resolve methods on Module type, but I see they are include in .NET Standard 2.0)

**Comment by karelz** [comment]
@weshaggard @danmosemsft can you provide details here?

**Comment by danmosemsft** [comment]
We aren't planning to add Reflection.Emit to .NET Core at this time.

**Comment by dudikeleti** [comment]
@danmosemsft But there is others Reflection.Emit types that exist. DynamicMethod for example exist in System.Reflection.Emit.Lightweight assembly.

**Comment by weshaggard** [comment]
There is some basic support for Reflection.Emit in .NET Core today. We don't currently have plans to add any further support at this point, that may change in the future. 

I don't know enough about the space to provide information about DynamicILInfo, but perhaps @jkotas can help suggest some other possible ways to handle that.

**Comment by jkotas** [comment]
What are you using DynamicILInfo for?

**Comment by dudikeleti** [comment]
@jkotas I'm using it for set the code byte array of a DynamicMethod (I'm need to convert method to DynamicMethod).

As an aside, why DynamicMethod and emit opcodes are included and the DynamicILInfo not? Is it not just more form the same capabilities? There is something special that it can't be included? 
If not, it would be nice if it included.

BTW @Immo Landwerth wrote in [this post](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/):

> **Reflection Emit.** Reflection emit is reasonably self-contained and thus we plan on following the model as Registry, above. There are other APIs that logically depend on being able to emit code, such as the expression tree’s Compile method or the ability to compile regexes. In some cases we’ll emulate their behavior (e.g. interpreting expression trees instead of compiling them) while in other cases we’ll throw (e.g. when compiling regexes).

I wonder if its including DynamicILInfo also.

**Comment by jkotas** [comment]
There is no reasonable way in the currently available .NET Core RefEmit APIs to just set the IL for the method if you have it available. I agree that it would make sense to add DynamicILInfo. It is the core building block for power users - ILGenerator and friends are a convenience layer above it.

**Comment by karelz** [comment]
Next step: Design it and implement it. Potentially leverage Desktop code (it is also on ReferenceSource).

**Comment by jkotas** [comment]
> Next step: Design it and implement it. Potentially leverage Desktop code 

This code is in CoreCLR (https://github.com/dotnet/coreclr/blob/68f72dd2587c3365a9fe74d1991f93612c3bc62a/src/mscorlib/src/System/Reflection/Emit/DynamicILGenerator.cs#L925). It needs to be flipped back to public, exposed in contracts, and tests added.

**Comment by karelz** [comment]
Even better, marking as "up for grabs"

**Comment by stephentoub** [comment]
> It needs to be flipped back to public, exposed in contracts, and tests added.

In addition, the code in coreclr is missing a bunch of its members... those will need to be ported back from netfx as well, though it shouldn't be much more than copy/paste.

**Comment by maryamariyan** [comment]
Closed by https://github.com/dotnet/corefx/pull/34532
