### ISSUE TITLE
Running into "Could not locate runtime assets for any of the frameworks ..." frequently

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#12058]
Frequently when I try to build a test project with `/t:BuildAndTest`, I will run into an error message saying

```
Could not locate runtime assets for any of the frameworks .NETCoreApp,Version=1.0
```

I have tried rebasing and running MSBuild with `/t:RebuildAndTest`, in addition to following the instructions [here](https://github.com/dotnet/corefx/issues/11204#issuecomment-243498131) and running MSBuild on the depproj file. However I still get the same error from MSBuild, and I end up having to run `sync` again (which, AFAIK, is the only thing that fixes this) which takes half an hour and downloads probably a few GB's worth of packages.

What causes this error message? Is there a known workaround for it? Thanks.

**Comment by hughbe** [comment]
I've been getting this too recently. It went away, but Unhelpfully I have no idea what I did that fixed it. Without wanting to waste your time (takes 20/30mins), you could try restoring all packages?

**Comment by karelz** [comment]
@ericstj @weshaggard any idea how to troubleshoot such problems?

**Comment by ericstj** [comment]
That warning message indicates that the NuGetTargetMoniker specified in the csproj doesn't match the project.json.  

Typically that happens when someone forgets to update one or the other, or if the direct build of the project uses a different configuration that the builds traversal.

/cc @karajas

**Comment by ericstj** [comment]
(deleted previous comment, I misread the error) 
Which project are you getting this error for?

**Comment by hughbe** [comment]
I got this for System.Collections yesterday

**Comment by ericstj** [comment]
I suspect this is happening because folks are pulling out the old implementations from the live build and relying on harvesting for this and you haven't restored the baseline.  Next time you see it can you try:
```
cd <coreFxRoot>\pkg\Microsoft.Private.PackageBaseline
msbuild /t:RestorePackages
```

If this works I can make a build tools change to help make this happen automatically.

**Comment by hughbe** [comment]
@ericstj I've tried this out with System.Collections, and the project now builds and tests without errors

**Comment by jamesqo** [comment]
@ericstj Works for me too. The buildtools change would be great.

**Comment by ericstj** [comment]
I have an idea to fix it pretty simply: set ProjectJsonFile for pkgproj's to point to our baseline project.json.
