### ISSUE TITLE
Question: resolving NETStandard libraries to framework assemblies

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/corefx#12053]
When installing the package `NETStandard.Library` into a .Net Framework project (for example net46)
- Some packages install nothing. I saw `TypeForwardedToAttribute` for binary capability.
- Some packages set a reference to assembly in GAC. This is by using `frameworkAssembly` element of nuget.
- Some packages **do install an assembly**, but it already exists in the full Framework, such as `System.IO.Compression` and `System.Net.Http`. Why can't these be treated as well as the above-mentioned type?

And another question for type resolving:
IL records the definition assembly for every type. If a type is moved into another assembly, a `TypeForwardedToAttrubute` can be used for binary capability. But for some assemblies, for example `System.ObjectModel`, I haven't see it in GAC.
How can `[System.ObjectModel]System.ComponentModel.INotifyPropertyChanged` be resolved to `[System]System.ComponentModel.INotifyPropertyChanged`?

**Edited**:
- For `System.IO.Compression`, I see a `runtime` folder in the package. It seems that assembly installed to `net46` is the win runtime. But why only install a GAC assembly in `net45`?
- For `System.Console`, I see an assembly full of  `TypeForwardedToAttrubute`. But as said above, what's are the differences between `System.ObjectModel`?

**Comment by karelz** [comment]
cc: @weshaggard @ericstj

**Comment by ericstj** [comment]
For System.IO.Compression and Http those dlls contain additional fixes over the components that ship in the .NET framework.  The teams owning those components opted to deliver updates in the nuget packages to allow folks to request and get updates  for those components at a faster cadence than the ship cycle of the .NET framework.

Other assemblies (like System.ObjectModel) that already exist in the .NET Framework and have no additional API over the version in the .NET framework install nothing, but ensure that they are applicable and will install (to indicate that other packages depending on them have their dependency satisfied).  System.Object model is indeed in the GAC, you can see it here on a typical installation: `C:\windows\Microsoft.NET\assembly\GAC_MSIL\System.ObjectModel\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.ObjectModel.dll` and the build-time reference is here: `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ObjectModel.dll`

Assemblies which do not exist in the .NET Framework carry both their build-time and runtime facades in the package, eg: System.IO.FileSystem.

**Comment by huoyaoyuan** [comment]
Still a question: for `System.IO.Compression`, it installs just GAC assembly for .NET Framework 4.5, but an additional assembly for 4.6. The framework assembly in 4.6 should have more content than 4.5, right? So why the additional assembly is only installed in 4.6?

**Comment by ericstj** [comment]
> The framework assembly in 4.6 should have more content than 4.5

Initially it was created to ship some bugfixes for handling large files that weren't in the desktop framework, but no additional API AFAIK. 

>So why the additional assembly is only installed in 4.6?

We needed fixes in the desktop framework in .NET 4.6 to enable out-of-band libraries that replaced those already in the framework.

**Comment by ericstj** [comment]
Closing this for now since I believe this addressed the original question.  If you have more questions, please open a new issue.
