### ISSUE TITLE
where are 'Close()' and 'Handle' on System.Net.Sockets.Socket ?

### ISSUE THREAD

**Issue by ekflame** [dotnet/corefx#12060]
I'm porting my network class to .net core, but I can't find **Socket.Close() & Socket.Handle**. where are they? are they not necessary on .net core socket?

**Comment by davidsh** [comment]
.NET Core 1.0 did not have those System.Net.Socket APIs.

However, we did add them back:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/ref/System.Net.Sockets.cs#L182

https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/ref/System.Net.Sockets.cs#L226

They will be part of the .NET Core 1.2 release.

**Comment by genifycom** [comment]
Well that is completely useless!

That means it is not possible to create a DotNet Core 1.0 application on AWS lambda that uses sockets since it is impossible to close them!

DotNet Core 1.0 is an LTS version and need to be fixed!

**Comment by JonHanna** [comment]
@genifycom you can `Dispose()` it.

**Comment by genifycom** [comment]
So this will clean up all the resources?

**Comment by JonHanna** [comment]
Yup. `Close()` wraps some possible event stuff around using `Dipose()` for the actual socket closing anyway.
