### ISSUE TITLE
Error running `msbuild /T:BuildAndTest /P:Coverage=true`

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#12075]
```
cd src/System.Collections.NonGeneric/tests
msbuild /T:BuildAndTest /P:Coverage=true
```

![error](https://cloud.githubusercontent.com/assets/1275900/18844920/5023f3f6-8417-11e6-900a-8222d4db4614.png)

Tools are already initialized, also happens with System.Collections.Specialized, and I haven't checked others

**Comment by karelz** [comment]
Is it specific to Collections.NonGeneric tests?
cc: @Priya91 @ianhays

**Comment by hughbe** [comment]
I also get it for System.Collections.Specialized but not System.Json for example

**Comment by Priya91** [comment]
Am able to repro the failure on System.ComponentModel.TypeConverter as well, doesn't seem to be specific on collections.

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/issues/12927

**Comment by danmosemsft** [comment]
I meant to type: this seems to be tracked by the issue above.
