### ISSUE TITLE
Orderby fails silently -- LINQ

### ISSUE THREAD

**Issue by SherifRefaat** [dotnet/corefx#12078]
**Situation**:

This LINQ query will run on a DB table.

```
var query = from x in db.User
                   where x.Active == true
                   select x;
var resultList = query.OrderBy(x.SerialNumber, new SerialNumberComparer()) // SerialNumberComparer is IComparer<T>
                    .select(x => x)
                    .ToList();
```

The `resultList` will contain the data 'ordered by' the standard sort algorithm for that type -- which in this case is String.

**Argument**:

1- I understand that the logic / code of `SerialNumberComparer` can not be transferred to the any SQL engine or at least it is not something that universal in all SQL engines.

2- This behavior may be by design in fact I think it is probably by design.

3- With 1 being said, I do not demand any magical thing here, but at least I see this the `OrderBy(...)` extension should through exception or something more appropriate because I think this is not a good idea to just ignore the `new SerialNumberComparer()` argument and continue.

4- Is this specific to the LINQ provider implementation that my ORM implements to expose my database tables to LINQ?

Thanks.

**Comment by svick** [comment]
> Is this specific to the LINQ provider implementation that my ORM implements to expose my database tables to LINQ?

Yes. All LINQ does is to construct an expression tree that represents your query. It's up to the LINQ provider to decide how to handle it (and whether to handle it or give up with an exception).

What ORM are you using? I think you should ask them whether this is the expected behavior.

**Comment by SherifRefaat** [comment]
@svick I get that. But the point is still being that if they decided to ignore that parameter for this case, then the LINQ inheritance model or interface that instruct any implementation that override it will not be able to differentiate between a DB or In-Memory LINQ. To summarize here, if that overload of the OrderBy method is not going to 'EVER' work on DB then the idea of general LINQ interface to both DB and In-Memory LINQ is not right.

**Comment by svick** [comment]
> if that overload of the OrderBy method is not going to 'EVER' work on DB

I think it could work in some cases. A LINQ provider could evaluate the `comparer` parameter and compare it with a set of known comparers (like `StringComparer.Ordinal`) and generate query based on that.

I don't know if any real LINQ provider actually does that (I have checked EF Core, and that throws exception on such query). But it does work with `AsQueryable()`, so making the overload throw or even removing it completely would be a breaking change. Because of that, I don't think there's anything to do here.
