### ISSUE TITLE
Don't invoke virtual property setters inside the base constructor.

### ISSUE THREAD

**Issue by pscho-msft** [dotnet/corefx#12079]
This is related to the following issue which does not appear to have been fully addressed:
https://github.com/dotnet/corefx/pull/6829

We are still seeing the issue in the AuthenticatedAes class. Here is a partial call stack. Feel free to request additional information.

0000004b9864d960 00007ffce4a131e3 Security.Cryptography.AuthenticatedAesCng.set_Mode(System.Security.Cryptography.CipherMode)
0000004b9864d9a0 00007ffce4a1316a System.Security.Cryptography.SymmetricAlgorithm..ctor() [f:\dd\ndp\fxcore\Open\src\System.Security.Cryptography.Primitives\src\System\Security\Cryptography\SymmetricAlgorithm.cs @ 14]
0000004b9864d9d0 00007ffce4a1312b Security.Cryptography.AuthenticatedSymmetricAlgorithm..ctor()
0000004b9864da00 00007ffce4a130ab Security.Cryptography.AuthenticatedAes..ctor()
0000004b9864da30 00007ffce4a12eca Security.Cryptography.AuthenticatedAesCng..ctor(System.Security.Cryptography.CngProvider)
0000004b9864daf0 00007ffce4a12532 Microsoft.Windows.KpsCore.Crypto.Cng.AuthenticatedAes..ctor(Microsoft.Windows.KpsCore.Crypto.AuthenticatedAesMode, System.String)

**Comment by karelz** [comment]
@pscho-msft please provide a test case.

**Comment by bartonjs** [comment]
Addressed by #12800 (master) and #12869 (release/1.1.0). Don't know why it didn't get closed by GitHub... closing now.
