### ISSUE TITLE
Remove all KeepAllProjectReferences

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#12074]
Currently some projects are using KeepAllProjectReferences in their csproj. This needs to be cleaned out as it might hide some packaging issues in test passes.

**Comment by danmosemsft** [comment]
Talk to @joperezr for context on this.

**Comment by joperezr** [comment]
This was required at least while System.Private.Xml wasn't fully exposed through contracts, if that is not the case anymore, then we can probably remove it as long as we now have the correct set of dependencies for each test project. Basically, for this to work we need to make sure that no test project has a P2P reference to a csproj.

**Comment by sepidehMS** [comment]
Done by https://github.com/dotnet/corefx/pull/12874
