### ISSUE TITLE
Microsoft.Win32.RegistryTests Build FAILED.

### ISSUE THREAD

**Issue by key-value** [dotnet/corefx#1208]
15:59:34.460 59>RunTestsForProject: (TargetId:1070)
Microsoft.Win32.RegistryTests.RegistryKey_GetValue_str_obj_b.Test03 FAIL
Error Unexpected exception occured.... exception message...:Xunit.Sdk.FalseException: Error null return expected (TaskId:731)
at Xunit.Assert.False(Boolean condition, String userMessage) (TaskId:731)
at Microsoft.Win32.RegistryTests.RegistryKey_GetValue_str_obj_b.Test03() in f:\SvnCode\corefx\src\Microsoft.Win32.Registry\tests\RegistryKey\RegistryKey_GetValue_str_obj_b.cs:line 86 (TaskId:731)

**Comment by weshaggard** [comment]
@key-value the text you provided doesn't actually contain the errors from the test logs can you provide that information?

**Comment by key-value** [comment]
@weshaggard 

16:00:08.381    98>F:\SvnCode\corefx\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00018\lib\tests.targets(67,5): warning MSB3073: The command "corerun.exe xunit.console.netcore.exe System.Runtime.Serialization.Json.Tests.dll  -xml .\testResults.xml -notrait category=failing " exited with code 1. [F:\SvnCode\corefx\src\System.Runtime.Serialization.Json\tests\System.Runtime.Serialization.Json.Tests.csproj]
The previous error was converted to a warning because the task was called with ContinueOnError=true. (TaskId:1306)
Build continuing because "ContinueOnError" on the task "Exec" is set to "true". (TaskId:1306)
Done executing task "Exec" -- FAILED. (TaskId:1306)
Task "Error" (TaskId:1307)

16:00:08.381    98>F:\SvnCode\corefx\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00018\lib\tests.targets(67,5): warning MSB3073: The command "corerun.exe xunit.console.netcore.exe System.Runtime.Serialization.Json.Tests.dll  -xml .\testResults.xml -notrait category=failing " exited with code 1. [F:\SvnCode\corefx\src\System.Runtime.Serialization.Json\tests\System.Runtime.Serialization.Json.Tests.csproj]
The previous error was converted to a warning because the task was called with ContinueOnError=true. (TaskId:1306)
Build continuing because "ContinueOnError" on the task "Exec" is set to "true". (TaskId:1306)
Done executing task "Exec" -- FAILED. (TaskId:1306)
Task "Error" (TaskId:1307)

**Comment by key-value** [comment]
@weshaggard 
16:00:06.939    98>RunTestsForProject: (TargetId:1861)
                        DataContractJsonSerializerTests.DCJS_ContainsLinkedList [FAIL] (TaskId:1306)
                           System.FormatException : Input string was not in a correct format. (TaskId:1306)
                           Stack Trace: (TaskId:1306)
                                 at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args) (TaskId:1306)
                                 at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args) (TaskId:1306)
                                 at System.String.Format(IFormatProvider provider, String format, Object[] args) (TaskId:1306)
                                 at System.Diagnostics.Debug.WriteLine(String format, Object[] args) (TaskId:1306)
                              f:\SvnCode\corefx\src\Common\tests\System\Console.cs(12,0): at System.Console.WriteLine(String message, Object[] args) (TaskId:1306)
                              f:\SvnCode\corefx\src\System.Runtime.Serialization.Json\tests\DataContractJsonSerializer.cs(1290,0): at DataContractJsonSerializerTests.SerializeAndDeserialize[T](T value, String baseline, DataContractJsonSerializerSettings settings, Func`1 serializerFactory, Boolean skipStringCompare) (TaskId:1306)
                              f:\SvnCode\corefx\src\System.Runtime.Serialization.Json\tests\DataContractJsonSerializer.cs(1046,0): at DataContractJsonSerializerTests.DCJS_ContainsLinkedList() (TaskId:1306)
                     Finished:    System.Runtime.Serialization.Json.Tests (TaskId:1306)
                      (TaskId:1306)
                     === TEST EXECUTION SUMMARY === (TaskId:1306)
                        System.Runtime.Serialization.Json.Tests  Total: 74, Errors: 0, Failed: 1, Skipped: 0, Time: 0.779s (TaskId:1306)
16:00:08.381    98>F:\SvnCode\corefx\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00018\lib\tests.targets(67,5): warning MSB3073: The command "corerun.exe xunit.console.netcore.exe System.Runtime.Serialization.Json.Tests.dll  -xml .\testResults.xml -notrait category=failing " exited with code 1. [F:\SvnCode\corefx\src\System.Runtime.Serialization.Json\tests\System.Runtime.Serialization.Json.Tests.csproj]
                     The previous error was converted to a warning because the task was called with ContinueOnError=true. (TaskId:1306)
                     Build continuing because "ContinueOnError" on the task "Exec" is set to "true". (TaskId:1306)
                   Done executing task "Exec" -- FAILED. (TaskId:1306)
                   Task "Error" (TaskId:1307)

**Comment by key-value** [comment]
@weshaggard 
15:59:34.460    59>RunTestsForProject: (TargetId:1070)
                        Microsoft.Win32.RegistryTests.RegistryKey_GetValue_str_obj_b.Test03 [FAIL] (TaskId:731)
                           Error Unexpected exception occured.... exception message...:Xunit.Sdk.FalseException: Error null return expected (TaskId:731)
                              at Xunit.Assert.False(Boolean condition, String userMessage) (TaskId:731)
                              at Microsoft.Win32.RegistryTests.RegistryKey_GetValue_str_obj_b.Test03() in f:\SvnCode\corefx\src\Microsoft.Win32.Registry\tests\RegistryKey\RegistryKey_GetValue_str_obj_b.cs:line 86 (TaskId:731)

**Comment by weshaggard** [comment]
@khdang these look like potential serialization test failures can you have a look?

**Comment by khdang** [comment]
@key-value it looks like a few tests are failing in your build. I don't seem to get the failures with a clean build. Do you have special steps to repro this issue?

**Comment by key-value** [comment]
@khdang  I do not have special steps and with out any change.There are three Computer failure with the same error.

**Comment by cnblogs-dudu** [comment]
See #566

**Comment by khdang** [comment]
@key-value thanks for the information. I'll look at this issue #1247.

**Comment by khdang** [comment]
Failures in this issue are tracked in #566 and #1247.
