### ISSUE TITLE
Strange dependency behavior

### ISSUE THREAD

**Issue by ddobric** [dotnet/corefx#12085]
Hi all,

I have a library build for netstandard1.4, which corresponds to .NET 461.
Then I build a desktop console application with .NET 4.5 and added reference to named library.
All worked fine.

But, this should not work, because v4.5 should not be able to use netstandard1.4.  Previously this was not the case.
Is tat same new expected behavior?

Thanks

**Comment by mellinoe** [comment]
And how are you building/running your project? NuGet would prevent you from installing such a library into your console application, but that doesn't necessarily mean that you couldn't directly reference the assembly, build against it, and deploy some facades to make it work at runtime. And if your netstandard1.4 assembly didn't happen to use anything that wasn't available in .NET 4.5, then you might even be able to run against it successfully. There's always some subset of stuff in a framework that would be safe to use in a lower version of that framework, but it is also pretty easy to mess up, and things will blow up if you use an API that isn't available on the lower framework.

**Comment by ddobric** [comment]
I use VS and also command line (dotnet build) for build. I'm referencing assemblies directly, because currently it is not possible to add project reference to netcore libs directly from "desktop projects" (i.e.: console application, lib etc.)

So, if I understood You correctly, by using of direct references, there is no framework check, which was working previously?
I'm fine with this. Just wanted to know if this is by design or just temporary implementation. 

Thanks

**Comment by tarekgh** [comment]
> So, if I understood You correctly, by using of direct references, there is no framework check, which was working previously? I'm fine with this. Just wanted to know if this is by design or just temporary implementation.

Yes if you reference the library directly, then there is no check will be done but expect you may get some runtime failures.
