### ISSUE TITLE
System.Net.NameResolution.Tests occasionally fails in CI 

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#12084]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/647/consoleFull#126993540579fe3b83-f408-404c-b9e7-9207d232e5fc

14:48:58   Discovering: System.Net.NameResolution.Pal.Tests
14:48:58   Discovered:  System.Net.NameResolution.Functional.Tests
14:48:58   Starting:    System.Net.NameResolution.Functional.Tests
14:48:58   Discovered:  System.Net.NameResolution.Pal.Tests
14:48:58   Starting:    System.Net.NameResolution.Pal.Tests
14:48:58      System.Net.NameResolution.Tests.GetHostByAddressTest.DnsObsoleteGetHostByAddress_LoopbackString_ReturnsSameAsLoopbackIP [FAIL]
14:48:58         System.Diagnostics.Debug+DebugAssertException : Failed to detect InterNetwork protocol: NotSocket
14:48:58         
14:48:58            at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
14:48:58            at System.Environment.get_StackTrace()
14:48:58            at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
14:48:58            at System.Net.SocketProtocolSupportPal.IsProtocolSupported(AddressFamily af) in D:\j\workspace\windows_nt_de---4526f5ff\src\Common\src\System\Net\SocketProtocolSupportPal.Windows.cs:line 59
14:48:58            at System.Net.SocketProtocolSupportPal.EnsureInitialized() in D:\j\workspace\windows_nt_de---4526f5ff\src\Common\src\System\Net\SocketProtocolSupportPal.Windows.cs:line 49
14:48:58            at System.Net.SocketProtocolSupportPal.get_OSSupportsIPv6() in D:\j\workspace\windows_nt_de---4526f5ff\src\Common\src\System\Net\SocketProtocolSupportPal.Windows.cs:line 27
14:48:58            at System.Net.Dns.InternalGetHostByAddress(IPAddress address, Boolean includeIPv6) in D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.NameResolution\src\System\Net\DNS.cs:line 145
14:48:58            at System.Net.Dns.GetHostByAddress(String address) in D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.NameResolution\src\System\Net\DNS.cs:line 112
14:48:58            at System.Net.NameResolution.Tests.GetHostByAddressTest.DnsObsoleteGetHostByAddress_LoopbackString_ReturnsSameAsLoopbackIP() in D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.NameResolution\tests\FunctionalTests\GetHostByAddressTest.cs:line 24
14:48:58            at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
14:48:58            at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
14:48:58            at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
14:48:58            at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 147
14:48:58            at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 224
14:48:58            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
14:48:58            at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<InvokeTestMethodAsync>b__1()
14:48:58            at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__4.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
14:48:58            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
14:48:58            at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction)
14:48:58            at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__9.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
14:48:58            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
14:48:58            at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code)
14:48:58            at Xunit.Sdk.TestInvoker`1.<InvokeTestMethodAsync>d__46.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 208
14:48:58            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
14:48:58            at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance)
14:48:58            at Xunit.Sdk.TestInvoker`1.<<RunAsync>b__45_0>d.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 173
14:48:58            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
14:48:58            at Xunit.Sdk.TestInvoker`1.<RunAsync>b__45_0()
14:48:58            at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.core\Sdk\ExceptionAggregator.cs:line 107
14:48:58            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
14:48:58            at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
14:48:58            at Xunit.Sdk.XunitTestRunner.<InvokeTestAsync>d__4.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestRunner.cs:line 67
14:48:58            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
14:48:58            at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator)
14:48:58            at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.core\Sdk\ExceptionAggregator.cs:line 0
14:48:58            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
14:48:58            at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
14:48:58            at Xunit.Sdk.TestRunner`1.<RunAsync>d__43.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestRunner.cs:line 0
14:48:58            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
14:48:58            at Xunit.Sdk.TestRunner`1.RunAsync()
14:48:58            at Xunit.Sdk.TestCaseRunner`1.<RunAsync>d__19.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestCaseRunner.cs:line 82
14:48:58            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
14:48:58            at Xunit.Sdk.TestCaseRunner`1.RunAsync()
14:48:58            at Xunit.Sdk.XunitTestMethodRunner.RunTestCaseAsync(IXunitTestCase testCase) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestMethodRunner.cs:line 45
14:48:58            at Xunit.Sdk.TestMethodRunner`1.<RunTestCasesAsync>d__32.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestMethodRunner.cs:line 136
14:48:58            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
14:48:58            at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync()
14:48:58            at Xunit.Sdk.TestMethodRunner`1.<RunAsync>d__31.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestMethodRunner.cs:line 106
14:48:58            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
14:48:58            at Xunit.Sdk.TestMethodRunner`1.RunAsync()
14:48:58            at Xunit.Sdk.TestClassRunner`1.<RunTestMethodsAsync>d__38.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestClassRunner.cs:line 205
14:48:58            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
14:48:58            at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync()
14:48:58            at Xunit.Sdk.TestClassRunner`1.<RunAsync>d__37.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestClassRunner.cs:line 163
14:48:58            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
14:48:58            at Xunit.Sdk.TestClassRunner`1.RunAsync()
14:48:58            at Xunit.Sdk.TestCollectionRunner`1.<RunTestClassesAsync>d__28.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestCollectionRunner.cs:line 130
14:48:58            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
14:48:58            at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync()
14:48:58            at Xunit.Sdk.TestCollectionRunner`1.<RunAsync>d__27.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestCollectionRunner.cs:line 101
14:48:58            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
14:48:58            at Xunit.Sdk.TestCollectionRunner`1.RunAsync()
14:48:58            at Xunit.Sdk.XunitTestAssemblyRunner.<>c__DisplayClass14_2.<RunTestCollectionsAsync>b__3() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestAssemblyRunner.cs:line 179
14:48:58            at System.Threading.Tasks.Task`1.InnerInvoke()
14:48:58            at System.Threading.Tasks.Task.Execute()
14:48:58            at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
14:48:58            at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
14:48:58            at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
14:48:58            at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, Object state) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\MaxConcurrencySyncContext.cs:line 107
14:48:58            at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
14:48:58            at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\MaxConcurrencySyncContext.cs:line 89
14:48:58            at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__5_0(Object _) in C:\BuildAgent\work\cb37e9acf085d108\src\common\XunitWorkerThread.cs:line 37
14:48:58            at System.Threading.Tasks.Task.Execute()
14:48:58            at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
14:48:58            at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
14:48:58            at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
14:48:58            at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
14:48:58         Stack Trace:
14:48:58               at System.Diagnostics.Debug.WindowsDebugLogger.ShowAssertDialog(String stackTrace, String message, String detailMessage)
14:48:58            D:\j\workspace\windows_nt_de---4526f5ff\src\Common\src\System\Net\SocketProtocolSupportPal.Windows.cs(86,0): at System.Net.SocketProtocolSupportPal.IsProtocolSupported(AddressFamily af)
14:48:58            D:\j\workspace\windows_nt_de---4526f5ff\src\Common\src\System\Net\SocketProtocolSupportPal.Windows.cs(49,0): at System.Net.SocketProtocolSupportPal.EnsureInitialized()
14:48:58            D:\j\workspace\windows_nt_de---4526f5ff\src\Common\src\System\Net\SocketProtocolSupportPal.Windows.cs(27,0): at System.Net.SocketProtocolSupportPal.get_OSSupportsIPv6()
14:48:58            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.NameResolution\src\System\Net\DNS.cs(145,0): at System.Net.Dns.InternalGetHostByAddress(IPAddress address, Boolean includeIPv6)
14:48:58            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.NameResolution\src\System\Net\DNS.cs(112,0): at System.Net.Dns.GetHostByAddress(String address)
14:48:58            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.NameResolution\tests\FunctionalTests\GetHostByAddressTest.cs(24,0): at System.Net.NameResolution.Tests.GetHostByAddressTest.DnsObsoleteGetHostByAddress_LoopbackString_ReturnsSameAsLoopbackIP()
14:48:58   Finished:    System.Net.NameResolution.Pal.Tests
14:48:58   
14:48:58   === TEST EXECUTION SUMMARY ===
14:48:58      System.Net.NameResolution.Pal.Tests  Total: 14, Errors: 0, Failed: 0, Skipped: 0, Time: 0.503s
14:48:58   Finished running tests.  End time=14:50:49.31, Exit code = 0
14:48:59   System.Xml.RW.XmlReader.ReadContentAs.Tests -> D:\j\workspace\windows_nt_de---4526f5ff\bin\Windows_NT.AnyCPU.Debug\System.Xml.RW.XmlReader.ReadContentAs.Tests\System.Xml.RW.XmlReader.ReadContentAs.Tests.dll
14:49:00   System.Xml.RW.XmlSystemPathResolver.Tests -> D:\j\workspace\windows_nt_de---4526f5ff\bin\Windows_NT.AnyCPU.Debug\System.Xml.RW.XmlSystemPathResolver.Tests\System.Xml.RW.XmlSystemPathResolver.Tests.dll
14:49:00   System.Xml.RW.XmlReader.Tests -> D:\j\workspace\windows_nt_de---4526f5ff\bin\Windows_NT.AnyCPU.Debug\System.Xml.RW.XmlReader.Tests\System.Xml.RW.XmlReader.Tests.dll
14:49:01   System.Xml.RW.XmlWriter.Tests -> D:\j\workspace\windows_nt_de---4526f5ff\bin\Windows_NT.AnyCPU.Debug\System.Xml.RW.XmlWriter.Tests\System.Xml.RW.XmlWriter.Tests.dll
14:49:02   System.Net.Primitives.Functional.Tests -> D:\j\workspace\windows_nt_de---4526f5ff\bin\Windows_NT.AnyCPU.Debug\System.Net.Primitives.Functional.Tests\System.Net.Primitives.Functional.Tests.dll
14:49:02   Finished:    System.Net.NameResolution.Functional.Tests
14:49:02   
14:49:02   === TEST EXECUTION SUMMARY ===
14:49:02 D:\j\workspace\windows_nt_de---4526f5ff\Tools\tests.targets(261,5): warning :    System.Net.NameResolution.Functional.Tests  Total: 52, Errors: 0, Failed: 1, Skipped: 0, Time: 4.636s [D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.NameResolution\tests\FunctionalTests\System.Net.NameResolution.Functional.Tests.csproj]
14:49:02   Finished running tests.  End time=14:50:53.27, Exit code = 1
14:49:02 D:\j\workspace\windows_nt_de---4526f5ff\Tools\tests.targets(261,5): warning MSB3073: The command "D:\j\workspace\windows_nt_de---4526f5ff\bin/tests/Windows_NT.AnyCPU.Debug/System.Net.NameResolution.Functional.Tests/netcoreapp1.0/RunTests.cmd D:\j\workspace\windows_nt_de---4526f5ff\packages/" exited with code 1. [D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.NameResolution\tests\FunctionalTests\System.Net.NameResolution.Functional.Tests.csproj]
14:49:02 D:\j\workspace\windows_nt_de---4526f5ff\Tools\tests.targets(272,5): err

4526f5ff\src\System.Net.NameResolution\tests\FunctionalTests\GetHostByAddressTest.cs:line 24

**Comment by tarekgh** [comment]
CC @davidsh

**Comment by tarekgh** [comment]
CC @danmosemsft

**Comment by davidsh** [comment]
cc: @ericeil @stephentoub @CIPop

**Comment by stephentoub** [comment]
This should have just been fixed with https://github.com/dotnet/corefx/pull/12077.

**Comment by ericeil** [comment]
Yes, this was fixed with #12077.
