### ISSUE TITLE
Consider checking for IReadOnlyCollection in Enumerable.ToArray

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#12083]
It may be useful to check for `IReadOnlyCollection` in `Enumerable.ToArray` so we can presize the array before copying over the elements. Additionally, if source implements `IReadOnlyList` we can avoid the enumerator allocation and make only 1 as opposed to 2 virtual calls per iteration.

I do not think we should optimize for read-only collections in other parts of the LINQ codebase, since 1) it would add a lot more complexity and 2) casting to variant interfaces is slow (dotnet/coreclr#603), so enumerables that do not implement these interfaces will pay.

However, this particular case may be worthwhile, since it is such a hot codepath and the 2x virtual method calls per iteration will make the tradeoff immeasurable for larger lazy enumerables. This should definitely be considered once the related CoreCLR issue is fixed.

This will benefit collections like `Stack` and `Queue` which do not implement `ICollection<T>`. (At least, not until #11990 is accepted/rejected.)

**Comment by svick** [comment]
> if source implements `IReadOnlyList` we can avoid the enumerator allocation and make only 1 as opposed to 2 virtual calls per iteration

Not sure that's a good idea, since iterating using the indexer could be much slower than iterating using `IEnumerator<T>`. This could happen with custom collections similar to `ImmutableList<T>` (but not `ImmutableList<T>` specifically, since that also implements `ICollection<T>` and so `ToArray()` just calls `CopyTo()`).

**Comment by VSadov** [comment]
Right. Immutable collections are known to have relatively expensive indexers, so using indexer may not be a win.
Overall this might only be profitable when dotnet/coreclr#603 is fixed.

**Comment by karelz** [comment]
Blocked on dotnet/coreclr#603

**Comment by stephentoub** [comment]
This is a theory about a potential perf improvement to potentially investigate. There are many such things that could be looked at... we don't need issues tracking them. If someone finds a performance improvement somewhere and wants to submit a PR for it, that's welcome.
