### ISSUE TITLE
Where are the autogen properties in asp.net core localizers?

### ISSUE THREAD

**Issue by holgerleichsenring** [dotnet/corefx#12096]
There are some questions raised due to implementation of ILocalizer interface:

It's introduced like this via Dependency Injection (from docs):

    Route("api/[controller]")]
    public class AboutController : Controller
    {
        private readonly IStringLocalizer<AboutController> _localizer;

        public AboutController(IStringLocalizer<AboutController> localizer)
        {
            _localizer = localizer;
        }

        [HttpGet]
        public string Get()
        {
            return _localizer["About Title"];
        }
    }

These things have to be accomplished:

- IStringLocalizer has to be used with the type of the class specified as generic
- localizer instance has to be called with a string information

Some thoughts/questions about it:

 - Why is it necessary to have the type of the class defined for that interface? Looks like an IoC necessity to me.
 - Method _localizer[“default text”] is some kind of sub optimal because
 - The defaults actually should also be defined by professional translaters.
 - I don’t want to have magic strings flying around, especially no  string with punctation marks
 - In case that a string couldn’t be found I would like to be informed about it. This is pretty easy when using constant names like “TITLE_ABOUT” or “title_about” if you prefer lowercase names. In this way I can only obtain it when the language is different from default that it stays English.
 - Why do we loose the straight procedure with ResourceManager’s automatic generated code and their properties?

find blog entry about that topic [here](http://codingsoul.de/2016/09/26/where-are-the-autogen-properties-in-asp-net-core-localizers/).

**Comment by svick** [comment]
`IStringLocalizer<T>` is part of [the aspnet/Localization repo](https://github.com/aspnet/Localization), not corefx, so I think any questions about it belong there.

**Comment by holgerleichsenring** [comment]
then close the issue, will move it.
