### ISSUE TITLE
Create corefx.vssettings file for VS 2015 & VS 15

### ISSUE THREAD

**Issue by adrianknight89** [dotnet/corefx#12093]
Can [this](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md) be updated for VS 2015 & VS 15?

**Comment by tarekgh** [comment]
@adrianknight89 could you please explain more about the ask?

**Comment by adrianknight89** [comment]
> We have provided a Visual Studio 2013 vssettings file (corefx.vssettings) at the root of the corefx repository

I was looking for a similar file for VS 2015 & now 17.

**Comment by tarekgh** [comment]
@weshaggard any idea about that?

**Comment by weshaggard** [comment]
Not sure but @adrianknight89 do you know if the one we have works or not in VS 2015/17? I would expect they should continue to work.
