### ISSUE TITLE
Process test should assert that timeouts aren't happening on process WaitForExit calls

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#1211]
See https://github.com/dotnet/corefx/pull/1207 for the suggestion. Generally, we should start using: 

```C#
Assert.True(p.WaitForExit(WaitInMS));

Instead of just calling WaitForExit(WaitInMS) and allowing the test to pass even if it times out.

**Comment by akoeplinger** [comment]
What does the second `p.WaitForExit();` achieve here? If the first one finished in time the process exited anyway and if not we'll raise an exception because of the assert.

**Comment by Petermarcu** [comment]
The second wait WaitForExit() is only needed when you have async event handlers to allow them to ensure they complete. Its somewhat orthogonal to this issue. I'll remove that from the issue.

Sent from my Windows Phone
________________________________

**Comment by pallavit** [comment]
Fixed with https://github.com/dotnet/corefx/pull/1229
