### ISSUE TITLE
Does .Net Core has replacement for SynchronizedCollection<T> ?

### ISSUE THREAD

**Issue by milla** [dotnet/corefx#12122]
SynchronizedCollection<T> cannot be found in .net core.
Does netcore has replacement ?

Thanks, Elaine

**Comment by benaadams** [comment]
Do any of the collections in System.Collections.Concurrent meet your needs? They are much better than SynchronizedCollection https://msdn.microsoft.com/en-us/library/system.collections.concurrent.aspx

**Comment by karelz** [comment]
SynchronizedCollection is (full) .NET Framework 2.0 API. Concurrent collections were designed to replace it.
