### ISSUE TITLE
Port System.Net.EndpointPermission

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#12127]
```csharp
    public class EndpointPermission {
        public string Hostname { get; }
        public int Port { get; }
        public TransportType Transport { get; }
        public override bool Equals(object obj);
        public override int GetHashCode();
        public override string ToString();
    }
```

**Comment by geoffkizer** [comment]
This is no longer part of netstandard 2.0.

**Comment by stephentoub** [comment]
@weshaggard, @danmosemsft, what's our thinking on what goes into System.Security.Permissions?  Even if it's not in netstandard, should the type be added there?

**Comment by weshaggard** [comment]
>@weshaggard, @danmosemsft, what's our thinking on what goes into System.Security.Permissions? Even if it's not in netstandard, should the type be added there?

I would just put them all in S.S.Permissions if we feel we need them for compat.

**Comment by danmosemsft** [comment]
It doesn't seem to have usage so I think we can leave this one.
