### ISSUE TITLE
Switch the default TestTFM to be netcoreapp1.1 for all tests

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#12129]
Currently the default TestTFM is still netcoreapp1.0, and when you are running tests without passing `FilterToTestTFM` we will run tests for netcoreapp1.0 and netcoreapp1.1. Given that netcoreapp1.0 tests are a subset of netcoreapp1.1, it should be ok to moving all of the defaults to netcoreapp1.1 and just running those. This will involve some work on changing project.jsons supports clauses, Test builds files and general properties.

cc: @weshaggard @ericstj @karajas

**Comment by weshaggard** [comment]
As this I assume you are also going to remove the fallback which also causes the netcoreapp1.0 tests to run, as that is adding a bit of duplicated test runs.

I see you are hinting at it but just so it is clear this will include updating all the Test.builds file such that their default build configuration is for TestTFMs=netcoreapp1.1 and TargetGroup=netstandard1.7?

**Comment by joperezr** [comment]
> As this I assume you are also going to remove the fallback which also causes the netcoreapp1.0 tests to run, as that is adding a bit of duplicated test runs.

Yes I will remove netcoreapp1.0 tests to run by default.

> will include updating all the Test.builds file such that their default build configuration is for TestTFMs=netcoreapp1.1 and TargetGroup=netstandard1.7

Basically whenever there is a `<Project Include="<libarary>.Tests.csproj" />` line in a tests.builds file it will mean that NugetTargetMoniker should be netstandard1.7 and TestTFMs will be netcoreapp1.1. From now on, if you want a specific test project to run in netcoreapp1.0 you will need to add in on the TestTFMs property. Is that more or less what you were thinking?
