### ISSUE TITLE
Port System.Net.IWebProxyScript

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#12132]
```csharp
    public interface IWebProxyScript {
        void Close();
        bool Load(Uri scriptLocation, string script, Type helperType);
        string Run(string url, string host);
    }
```

**Comment by ericeil** [comment]
Not sure if this is actually used by anything in netstandard2.0.

**Comment by davidsh** [comment]
You can port this.  But it needs to be a no-op.  We deprecated this code a while ago. It doesn't even work in .NET Framework (Desktop).  There should not be any customers really using it anyways.  There is way we can run "script" (Javascript) PAC files anymore in .NET.
