### ISSUE TITLE
Rename System.Xml contract (currently System.Xml.ReaderWriter)

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#12145]
A lot of Xml APIs are in System.Xml.ReaderWriter, is that the right place and name for them?

**Comment by danmosemsft** [comment]
@weshaggard I don't think this is worth recording by itself- we need to think all up about whether we have the right set of contracts after we've done our API work.

**Comment by weshaggard** [comment]
@danmosemsft we do need to think about this all up but the reason I wanted an issue for it was to have the owner provide some suggestions for the naming based on the contents.
