### ISSUE TITLE
Port System.Net.WebUtility missing members

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#12142]
``` csharp
    public static class WebUtility {
        public static void HtmlDecode(string value, TextWriter output);
        public static void HtmlEncode(string value, TextWriter output);
    }
```

**Comment by geoffkizer** [comment]
Doing this would add a dependency from System.Runtime.Extensions (where WebUtility currently lives) to System.IO.

@weshaggard over to you to decide how to handle this.

**Comment by karelz** [comment]
@weshaggard can you please advise?

**Comment by karelz** [comment]
@geoffkizer @weshaggard did you get to any decision?

**Comment by weshaggard** [comment]
I'm still weighting options. We really have two options:

1. We exclude these from netstandard.
2. We have to pull down TextWriter down into System.Runtime.Extensions or System.Runtime. Which will mean we likely need to pull down all of the System.IO contract.

@jkotas @stephentoub @JeremyKuhne do you guys have any preferences? We are already going to pull down FileStream into System.Runtime so it may not be a big deal to pull down the System.IO and we may end up needing to do other FileSystem stuff like Directory.CreateDirectory based on it's light-up usage (see https://github.com/dotnet/corefx/issues/11151).

**Comment by jkotas** [comment]
> Pull down TextWriter down into System.Runtime.Extensions

This sounds most reasonable to me. (The other options are fine with me as well.)

**Comment by weshaggard** [comment]
OK I've filed issue https://github.com/dotnet/corefx/issues/13340 to move the System.IO types into System.Runtime.Extensions. Once that is complete this work item can be completed.

**Comment by weshaggard** [comment]
This issue should be unblocked now as System.IO types have been moved into System.Runtime.Extensions

**Comment by karelz** [comment]
@geoffkizer do you plan to finish it off?

**Comment by danmosemsft** [comment]
@safern this should be straightforward.
