### ISSUE TITLE
Add ComponentModel base classes where missing.

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#12154]
All these should derive from Component.

- [x] System.Timers.Timer
- [x] System.Net.WebClient
- [x] System.Net.NetworkInformation.Ping
- [x] System.ComponentModel.BackgroundWorker
- [x] System.IO.FileSystemWatcher
- [x] System.Diagnostics.Process
- [x] System.Diagnostics.ProcessModule
- [x] System.Diagnostics.ProcessThread

**Comment by stephentoub** [comment]
Interesting.  That's actually many fewer than I thought there'd be.  That's good :smile:
