### ISSUE TITLE
Code cleanup for System.ComponentModel.TypeConverter 

### ISSUE THREAD

**Issue by AlexGhiondea** [dotnet/corefx#12160]
There are a couple of clean-up items for the newly ported code inside System.ComponentModel.TypeConverter. These are captured from PR #12081 
- Remove explicit base() from constructor calls
- Replace explicitly implemented properties with auto-implemented properties when possible
- Simplify members and properties with 1 lines of code to expression bodied members: protected virtual bool CanRaiseEvents => true;
  *Switch over to the ?. operator in C# for null checking:

``` csharp
//From
EventHandler handler = (EventHandler)_events[s_eventDisposed];
if (handler != null) handler(this, EventArgs.Empty);
//To
((EventHandler)_events[s_eventDisposed])?.Invoke(this, EventArgs.Empty);

//From
ISite s = _site;
return s == null ? null : s.Container;
//To
public IContainer Container => _site?.Container;
```
- Switch to string interpolation instead of string concatenation
- Remove unnecessary initialization (ie. Bool foo = false)
- Replace empty arrays with Array.Empty<T>()
- Replace string literals with nameof wherever possible.
- Simplify event handler declarations when no custom code is required
- Introduce readonly modifier for sync objects.
- Replace nongeneric collections with generic collections
- Use foreach instead of manually writing the foreach logic.
- Cache the char[] into a static readonly field (ie. new char[] { '\' })
- Simplify the CultureInfoMapper code:

``` csharp
private static class CultureInfoMapper
{
    // Dictionary of CultureInfo.DisplayName, CultureInfo.Name for cultures that have changed DisplayName over releases.
    // This is to workaround an issue with CultureInfoConverter that serializes DisplayName (fixing it would introduce breaking changes).
    private static readonly Dictionary<string, string> s_cultureInfoNameMap = CreateMap();

    private static Dictionary<string, string> CreateMap()
    {
        const int Count = 274;
        var result = new Dictionary<string, string>(Count)
        {
            { "Afrikaans", "af" },
            ...
        };
        Debug.Assert(result.Count == Count);
        return result;
    }

    public static string GetCultureInfoName(string cultureInfoDisplayName)
    {
        string name;
        return s_cultureInfoNameMap.TryGetValue(cultureInfoDisplayName, out name) ?
            name :
            cultureInfoDisplayName;
    }
}
```

**Comment by bmeverett** [comment]
> Use foreach instead of manually writing the foreach logic. 


 Should foreach be changed to `.ForEach(x => code)` or what is the intent for this?

**Comment by AlexGhiondea** [comment]
@bmeverett I think there are cases where we call MoveNext and check Current instead of using the foreach statement.

**Comment by bmeverett** [comment]
@AlexGhiondea Thanks! 

One more thing as I'm finishing up theses changes, is converting nongeneric collections with generic. The referenced pull request says to change ArrayList to List<T> if not public. ArrayList looks like it's public and that piece of code where the comment was seems to no longer be there. Was there another place that should be converted to generics?

**Comment by AlexGhiondea** [comment]
@bmeverett thanks a lot for doing this!

I think what that meant was to only change ArrayList to a generic version in the implementation. If the ArrayList shows up in a public method signature then we cannot actually change it to a generic version.

@karelz can you add @bmeverett to the contributors list so we can assign this item to him?

**Comment by karelz** [comment]
Invitation sent

**Comment by bmeverett** [comment]
@karelz accepted

**Comment by bmeverett** [comment]
@AlexGhiondea not sure I'm entirely following, I get what you're saying but looking at some of the uses of ArrayList I'm not sure they could be converted. Could you maybe give me a quick example what you're looking for?

**Comment by AlexGhiondea** [comment]
@bmeverett here is an example: https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.ComponentModel.TypeConverter/src/System/ComponentModel/MemberDescriptor.cs#L100

We are using an ArrayList to store Attribute objects. Instead, we could replace the ArrayList with a List<Attribute>. Those are the kinds of things I had in mind.

There are cases where we can replace the implementation to use generic types but we would still have to convert them just before returning into (for example) an ArrayList.

Does that make sense?

**Comment by bmeverett** [comment]
@AlexGhiondea Yes! That makes sense! I'll see what I can do.
