### ISSUE TITLE
Re-enable usage of AppDomain.GetAssemblies in System.Private.Xml when it comes back

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#12173]
Refer to TODO in [QilXmlReader](https://github.com/dotnet/corefx/blob/25152c3eb1333087daf06b33c8706e78c958c44e/src/System.Private.Xml/src/System/Xml/Xsl/QIL/QilXmlReader.cs)

**Comment by danmosemsft** [comment]
Pending on https://github.com/dotnet/corefx/issues/9327

**Comment by sepidehMS** [comment]
Done by https://github.com/dotnet/corefx/pull/12609
