### ISSUE TITLE
Remove System.Security workarounds from System.Private.Xml

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#12174]
Remove SecurityRuleSet and SecurityRulesAttribute from System.Private.Xml workarounds. https://github.com/dotnet/corefx/pull/12046 is bringing them back.

**Comment by jkotas** [comment]
Everything that has to with these attributes should be deleted from System.Private.Xml. It has no affect and does not make sense on .NET Core.

**Comment by sepidehMS** [comment]
Removed usage of these attributes completely as part of pull request https://github.com/dotnet/corefx/pull/12194
