### ISSUE TITLE
Add actual switches for Xml Configuration properties

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#12172]
Do we leave properties defined in [LocalAppContextSwitches](https://github.com/dotnet/corefx/blob/9348997920c1ba782b45adb5e8ee9754149ab1e2/src/System.Private.Xml/src/Workarounds/LocalAppContextSwitches.cs) with default values, or do we enable users to switch their values?

**Comment by danmosemsft** [comment]
@rahku these are supposed to be set by the AppContext mechanism. Is that coming back for .NET Core? If so, we should change this code. If not, then this code is fine.

**Comment by jkotas** [comment]
The AppContext APIs for these switches are there (they actually shipped even in netcoreapp1.0).

cc @AlexGhiondea

**Comment by AlexGhiondea** [comment]
The default value for an AppContext switch (which is ```false```) should provide the user with the latest behavior for that piece of code.

If there is no concept of old vs new then the default value of the switch should enable the common scenario and allow people to opt-in to the different scenario by using the switch.

**Comment by sepidehMS** [comment]
Done by https://github.com/dotnet/corefx/pull/12609
