### ISSUE TITLE
Push System.IO.UnmanagedMemoryStream into corelib

### ISSUE THREAD

**Issue by alexperovich** [dotnet/corefx#12170]
Required by ResourceManager.GetStream

**Comment by stephentoub** [comment]
We've made both bug and performance fixes to UnmanagedMemoryStream in corefx.  I don't remember if coreclr has its own internal copy of UnmanagedMemoryStream, but if it does and that's what we're switching to use, let's make sure that the improvements from corefx make their way back to it as well.

**Comment by alexperovich** [comment]
I am going to diff the implementations and port the fixes. If we know specifically what the changes are that would be useful.

**Comment by stephentoub** [comment]
The history is here:
https://github.com/dotnet/corefx/commits/master/src/System.IO.UnmanagedMemoryStream/src/System/IO
but diffing is still a good idea, as @KrzysztofCwalina likely made some tweaks here and there as part of that initial porting/commit.

**Comment by alexperovich** [comment]
See dotnet/coreclr#7418

**Comment by KrzysztofCwalina** [comment]
>I am going to diff the implementations and port the fixes. If we know specifically what the changes are that would be useful.

Like the change to make Read read and Write write, as opposed to the other way? :-)
