### ISSUE TITLE
Add a ValueList type to Common to reduce allocations

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#12177]
It may be desirable to add a `ValueList<T>` type in Common to supplant usages of LowLevelList / List in hot paths. It would have exactly the same semantics as List, except it would be a mutable struct so no allocation for the list itself. Additionally, since this would be an internal type we could make other micro-optimizations e.g. `_syncRoot` field, `_version` only exists in debug (which also means `MoveNext` might be inlined), bounds checks in indexer are Debug.Asserts, etc.

This would help in places such as [here](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Collections/Generic/EnumerableHelpers.cs#L135), where we want a dynamically-grown array and don't want to manually write the resizing logic, but really want to minimize allocations.

**Comment by karelz** [comment]
@Priya91 @ianhays what do you think?

**Comment by jamesqo** [comment]
@karelz Sorry if I made it confusing in the title, however this is not an API proposal.
