### ISSUE TITLE
HttpClient.GetAsync fails with 302 with https if URI redirects

### ISSUE THREAD

**Issue by adityapatwardhan** [dotnet/corefx#12171]
The HttpClient.GetAsync fails the URI that is used is https and does a redirection. The status code returned is 302. 

**Repro:**

HttpClient client = new HttpClient();
client.GetAsync("https://go.microsoft.com/fwlink/?LinkID=623861&clcid=0x409") 

**The response is:**
Result                 : StatusCode: 302, ReasonPhrase: 'Moved Temporarily', Version: 1.1, Content:
                         System.Net.Http.StreamContent, Headers:
                         {
                           Cache-Control: no-cache
                           Connection: keep-alive
                           Date: Thu, 29 Sep 2016 00:32:32 GMT
                           Pragma: no-cache
                           Location: http://dtlgalleryint.cloudapp.net/api/v2/
                           Server: Microsoft-IIS/8.5
                           X-AspNetMvc-Version: 5.2
                           X-AspNet-Version: 4.0.30319
                           X-Powered-By: ASP.NET
                           Content-Length: 0
                           Expires: -1
                         }

**Note**
This works fine with a http:// uri.

**Comment by stephentoub** [comment]
This is by design.  Automatic redirect from https to http is disabled as a security precaution.

Windows:
https://github.com/dotnet/corefx/blob/def83b7b0745d5f6380d5f3a57c186d2260c2acf/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs#L1095

Unix:
https://github.com/dotnet/corefx/blob/ca0b35ca1173c056e4d6e1794b814beb80620fbe/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.EasyRequest.cs#L275-L278

**Comment by davidsh** [comment]
Yes, this is by-design. Please let us know if you have any further questions. Thx.

**Comment by adityapatwardhan** [comment]
Is there a work around? Ideally we want to use https uris.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by davidsh** [comment]
One workaround is to disable automatic redirection in HttpClient using this property:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/ref/System.Net.Http.cs#L81

Create a new HttpClient object by doing something like this:

```c#
var handler = new HttpClientHandler();
var client = new HttpClient();
handler.AllowAutoRedirect = false;
```

Then, handle the redirection response yourself, parsing out the `Location` header after doing the first request. Then create a new request to the new uri and submit it.

**Comment by jianyunt** [comment]
In some cases it is needed for us for the redirection, for example, fwlink.

**Comment by stephentoub** [comment]
> In some cases it is needed for us for the redirection, for example, fwlink.

Why are https fwlinks forwarding to http urls?

**Comment by stephentoub** [comment]
cc: @blowdart

**Comment by blowdart** [comment]
Because fwlinks never get updated, and folks add http links.

But yea, agree with by design.

**Comment by jianyunt** [comment]
I did not know it gets redirected to http. Then agreed by design.

**Comment by EncoderPtd** [comment]
@davidsh 

I agree. 
But how should i do if i'm using `HttpWebRequest`? I can't find any property like:
>var request = WebRequest.Create("https://...") as HttpWebRequest();
>request.AllowAutoRedirect = false;

(The .NetFramework has this property)

And i tried the `handler.AllowAutoRedirect = false;`   It doesn't work...and threw an Exception said:

> System.AggregateException: One or more errors occurred. (The remote server returned an error: (302) Found.) ---> System.Net.WebException: The remote server returned an error: (302) Found.
at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
at System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task1 promise, Boolean requiresSynchronization)
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
at NSHttpCommon.HttpAccess.GetResponse(Uri url, Boolean autoRedir, Stream stm, Dictionary2 headers) in D:\User\CoreProjects\CommonUtilities\src\HttpCommon\__Source\Http\HttpAcc\HttpAccess.cs:line 169 ---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (302) Found. at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) at System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task`1 promise, Boolean requiresSynchronization)<---


It's all ok when using .netframework or manually using TcpClient. 
This is what server returned:

>HTTP/1.1 302 Found
Server: nginx/1.9.10
Date: Tue, 11 Oct 2016 06:50:39 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
Location: http://...
P3P: CP="CAO PSA OUR"
Set-Cookie: xxx; EXPIRES=Fri, 02-Jan-2020 00:00:00 GMT; PATH=/; DOMAIN=yyy;
Set-Cookie: xxx; PATH=/; DOMAIN=yyy;

Thanks.
