### ISSUE TITLE
Improve test suite for System.CodeDom

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12179]
Code coverage could be increased significantly.  And we'd ideally avoid some of the existing duplication between the C# and VB generator tests (which represent the bulk of the current testing).

**Comment by Priya91** [comment]
Is this fixed in the linked merged PR, should we close this?

**Comment by stephentoub** [comment]
@hughbe did a good job adding a bunch of tests.  There's still more that can be done, but the coverage level is high enough that I don't think we need an issue tracking it anymore.
