### ISSUE TITLE
Xml has a dependency on System.Net.Requests

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#12184]
System.Xml.ReaderWriter contract has a dependency on RequestCachePolicy (https://github.com/dotnet/corefx/blob/master/src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs#L1126)

System.Private.Xml has a dependency on requests for ReuqestCachePolicy (https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System.Private.Xml.csproj#L17).
 
Xml also has an XmlDownloadManager which depends on HttpClient.

Should we move RequestCachePolicy into System.Net.Primitives? Or perhaps break this dependency another way?

@stephentoub @davidsh @CIPop

**Comment by stephentoub** [comment]
Seems reasonable to move it down (it was only just added to System.Net.Requests last week).  The public APIs are minimal, and any caching we may want to do in the future could still be done in System.Net.Requests.  I agree that's better than having System.Xml.* taking a dependency on System.Net.Requests.

**Comment by davidsh** [comment]
I'm ok with moving those to System.Net.Primitives.

**Comment by weshaggard** [comment]
Excellent lets use this issue to track moving those down. Who would be the best person to do that?

**Comment by stephentoub** [comment]
#12853 has been merged to move these types down into System.Net.Primitives.  We just need to remove the P2P references that were temporarily put in place.  That can be done once we get updated corefx packages in the repo.

**Comment by stephentoub** [comment]
The TODOs were removed in #13000
