### ISSUE TITLE
Implement ICloneable where missing

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#12199]
The following are not implementing ICloneable but according to Net Standard 2.0 they should:

- [x] System.Array.ArrayEnumerator
- [x] System.Array.SZArrayEnumerator
- [x] System.Collections.ArrayList
- [x] System.Collections.ArrayList.ArrayListEnumerator
- [x] System.Collections.ArrayList.ArrayListEnumeratorSimple
- [x] System.Collections.ArrayList.IListWrapper.IListWrapperEnumWrapper
- [x] System.Collections.BitArray
- [x] System.Collections.BitArray.BitArrayEnumeratorSimple
- [x] System.Collections.Hashtable
- [x] System.Collections.Hashtable.HashtableEnumerator
- [x] System.Collections.Queue
- [x] System.Collections.Queue.QueueEnumerator
- [x] System.Collections.SortedList
- [x] System.Collections.SortedList.SortedListEnumerator
- [x] System.Collections.Stack
- [x] System.Collections.Stack.StackEnumerator
- [x] System.ComponentModel.MaskedTextProvider
- [ ] System.Configuration.Assemblies.AssemblyHash
- [x] System.Delegate
- [x] System.Net.Http.Headers.AuthenticationHeaderValue
- [x] System.Net.Http.Headers.CacheControlHeaderValue
- [x] System.Net.Http.Headers.ContentDispositionHeaderValue
- [x] System.Net.Http.Headers.ContentRangeHeaderValue
- [x] System.Net.Http.Headers.EntityTagHeaderValue
- [x] System.Net.Http.Headers.MediaTypeHeaderValue
- [x] System.Net.Http.Headers.MediaTypeWithQualityHeaderValue
- [x] System.Net.Http.Headers.NameValueHeaderValue
- [x] System.Net.Http.Headers.NameValueWithParametersHeaderValue
- [x] System.Net.Http.Headers.ProductHeaderValue
- [x] System.Net.Http.Headers.ProductInfoHeaderValue
- [x] System.Net.Http.Headers.RangeConditionHeaderValue
- [x] System.Net.Http.Headers.RangeHeaderValue
- [x] System.Net.Http.Headers.RangeItemHeaderValue
- [x] System.Net.Http.Headers.RetryConditionHeaderValue
- [x] System.Net.Http.Headers.StringWithQualityHeaderValue
- [x] System.Net.Http.Headers.TransferCodingHeaderValue
- [x] System.Net.Http.Headers.TransferCodingWithQualityHeaderValue
- [x] System.Net.Http.Headers.ViaHeaderValue
- [x] System.Net.Http.Headers.WarningHeaderValue
- [x] System.OperatingSystem
- [ ] System.Runtime.Remoting.Messaging.CallContextRemotingData
- [ ] System.Runtime.Remoting.Messaging.CallContextSecurityData
- [ ] System.Runtime.Remoting.Messaging.LogicalCallContext
- [x] System.Runtime.Serialization.Formatters.Binary.IntSizedArray
- [x] System.Runtime.Serialization.Formatters.Binary.SizedArray
- [x] System.RuntimeType
- [x] System.Version
- [x] System.Xml.Schema.XmlAtomicValue
- [x] System.Xml.XPath.XPathNavigator
- [x] System.Xml.XPath.XPathNodeIterator
- [x] System.Xml.XmlNode
- [x] string

**Comment by stephentoub** [comment]
@danmosemsft, how was this list generated?  Some of the types in the list aren't public, and some of those already implement ICloneable, e.g. https://source.dot.net/#System.Runtime.Serialization.Formatters/System/Runtime/Serialization/Formatters/Binary/BinaryUtilClasses.cs,285

**Comment by danmosemsft** [comment]
By hand using ILSPY over netstandard.dll and our contracts, and windiff - apparently not accurately, sorry. Hmm.

**Comment by stephentoub** [comment]
After https://github.com/dotnet/corefx/pull/12888, the only remaining types in the list are ones that aren't exposed yet, so their ICloneable implementations should just be brought with them if/when they're generally exposed.
