### ISSUE TITLE
Investigate AuthenticationManager implementation

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12192]
This and supporting types are currently stubbed out, with members throwing not supported exceptions.  We need to investigate whether that's sufficient, whether a more robust form of stubbing is required (e.g. returning nop objects rather than throwing), or whether we need some minimally functional implementation for this legacy.

**Comment by morganbr** [comment]
If we choose to stub, we should ensure it doesn't appear that it's actually succeeding at authenticating requests. My preference would be that Authenticate and PreAuthenticate throw, but if they can't, they should return null (matching their, uh unique, contract).

**Comment by stephentoub** [comment]
> My preference would be that Authenticate and PreAuthenticate throw

This is how they're currently checked-in.  Let's leave it that way, and we can revisit it if/when we have a need. I'll close this now then.

**Comment by danmosemsft** [comment]
Reopening just to flag these are in NS2.0 and throwing PNSE. Triage, you may want to have this open even if post 2.0
We have 0% usage in our data.
