### ISSUE TITLE
Need a mechanism to be able to run dangerous Outerloop tests (that require machines to be recycled)

### ISSUE THREAD

**Issue by FiveTimesTheFun** [dotnet/corefx#1220]
Of the System.IO.FileSystem tests ported over, there were a couple that modified the current directory.  Some set the current directory directly, some used the CurrentDirectoryContext helper class.  Most of these instances were testing the behavior of APIs that acted on relative paths.  For example, CreateDirectory_DotDotAsPath_WhenCurrentDirectoryIsRoot_DoesNotThrow() in CreateDirectory.cs does what its title says.  This is a specific instance of the general problem of testing global process state.

**Comment by Chrisboh** [comment]
This is something we want to do but will not get to it before RTM.  Moving it to the future milestone.

**Comment by Priya91** [comment]
CI machines are recycled. Closing this issue.
