### ISSUE TITLE
Unexpected string in NumberFormatInfo.NumberGroupSeparator

### ISSUE THREAD

**Issue by osjoberg** [dotnet/corefx#12204]
I am testing som basic number formatting with CultureInfo. Any culture I have tested except en-US yields weird results for NumberGroupSeparator.

      public static void Main(string[] args)
      {            
          var culture = new CultureInfo("sv-SE");
          Console.WriteLine($"'{culture.NumberFormat.NumberGroupSeparator}'");
          Console.WriteLine(1000.ToString("N", culture));
      }

Expected output :
' '
1 000,00

Actual output:
'┬á'
1┬á000,00

**Comment by SamuelEnglard** [comment]
What's your System culture?

**Comment by osjoberg** [comment]
I am running English Windows 10 with Swedish regional settings in the control panel.

CultureInfo.CurrentCulture.Name is "sv-SE"

**Comment by osjoberg** [comment]
It seems to be a bigger problem than just "sv-SE" (used culture names are derived from "legacy" .NET CultureInfo.GetCultures(CultureTypes.AllCultures) / Windows 10).

        public static void Main(string[] args)
        {            
            var cultureNames = new[] { "", "aa", "aa-DJ", "aa-ER", "aa-ET", "af", "af-NA", "af-ZA", "agq", "agq-CM", "ak", "ak-GH", "am", "am-ET", "ar", "ar-001", "ar-AE", "ar-BH", "ar-DJ", "ar-DZ", "ar-EG", "ar-ER", "ar-IL", "ar-IQ", "ar-JO", "ar-KM", "ar-KW", "ar-LB", "ar-LY", "ar-MA", "ar-MR", "ar-OM", "ar-PS", "ar-QA", "ar-SA", "ar-SD", "ar-SO", "ar-SS", "ar-SY", "ar-TD", "ar-TN", "ar-YE", "arn", "arn-CL", "as", "as-IN", "asa", "asa-TZ", "ast", "ast-ES", "az", "az-Cyrl", "az-Cyrl-AZ", "az-Latn", "az-Latn-AZ", "ba", "ba-RU", "bas", "bas-CM", "be", "be-BY", "bem", "bem-ZM", "bez", "bez-TZ", "bg", "bg-BG", "bin", "bin-NG", "bm", "bm-Latn", "bm-Latn-ML", "bn", "bn-BD", "bn-IN", "bo", "bo-CN", "bo-IN", "br", "br-FR", "brx", "brx-IN", "bs", "bs-Cyrl", "bs-Cyrl-BA", "bs-Latn", "bs-Latn-BA", "byn", "byn-ER", "ca", "ca-AD", "ca-ES", "ca-ES-valencia", "ca-FR", "ca-IT", "ce", "ce-RU", "cgg", "cgg-UG", "chr", "chr-Cher", "chr-Cher-US", "co", "co-FR", "cs", "cs-CZ", "cu", "cu-RU", "cy", "cy-GB", "da", "da-DK", "da-GL", "dav", "dav-KE", "de", "de-AT", "de-BE", "de-CH", "de-DE", "de-LI", "de-LU", "dje", "dje-NE", "dsb", "dsb-DE", "dua", "dua-CM", "dv", "dv-MV", "dyo", "dyo-SN", "dz", "dz-BT", "ebu", "ebu-KE", "ee", "ee-GH", "ee-TG", "el", "el-CY", "el-GR", "en", "en-001", "en-029", "en-150", "en-AG", "en-AI", "en-AS", "en-AT", "en-AU", "en-BB", "en-BE", "en-BI", "en-BM", "en-BS", "en-BW", "en-BZ", "en-CA", "en-CC", "en-CH", "en-CK", "en-CM", "en-CX", "en-CY", "en-DE", "en-DK", "en-DM", "en-ER", "en-FI", "en-FJ", "en-FK", "en-FM", "en-GB", "en-GD", "en-GG", "en-GH", "en-GI", "en-GM", "en-GU", "en-GY", "en-HK", "en-ID", "en-IE", "en-IL", "en-IM", "en-IN", "en-IO", "en-JE", "en-JM", "en-KE", "en-KI", "en-KN", "en-KY", "en-LC", "en-LR", "en-LS", "en-MG", "en-MH", "en-MO", "en-MP", "en-MS", "en-MT", "en-MU", "en-MW", "en-MY", "en-NA", "en-NF", "en-NG", "en-NL", "en-NR", "en-NU", "en-NZ", "en-PG", "en-PH", "en-PK", "en-PN", "en-PR", "en-PW", "en-RW", "en-SB", "en-SC", "en-SD", "en-SE", "en-SG", "en-SH", "en-SI", "en-SL", "en-SS", "en-SX", "en-SZ", "en-TC", "en-TK", "en-TO", "en-TT", "en-TV", "en-TZ", "en-UG", "en-UM", "en-US", "en-VC", "en-VG", "en-VI", "en-VU", "en-WS", "en-ZA", "en-ZM", "en-ZW", "eo", "eo-001", "es", "es-419", "es-AR", "es-BO", "es-CL", "es-CO", "es-CR", "es-CU", "es-DO", "es-EC", "es-ES", "es-GQ", "es-GT", "es-HN", "es-MX", "es-NI", "es-PA", "es-PE", "es-PH", "es-PR", "es-PY", "es-SV", "es-US", "es-UY", "es-VE", "et", "et-EE", "eu", "eu-ES", "ewo", "ewo-CM", "fa", "fa-IR", "ff", "ff-CM", "ff-GN", "ff-Latn", "ff-Latn-SN", "ff-MR", "ff-NG", "fi", "fi-FI", "fil", "fil-PH", "fo", "fo-DK", "fo-FO", "fr", "fr-029", "fr-BE", "fr-BF", "fr-BI", "fr-BJ", "fr-BL", "fr-CA", "fr-CD", "fr-CF", "fr-CG", "fr-CH", "fr-CI", "fr-CM", "fr-DJ", "fr-DZ", "fr-FR", "fr-GA", "fr-GF", "fr-GN", "fr-GP", "fr-GQ", "fr-HT", "fr-KM", "fr-LU", "fr-MA", "fr-MC", "fr-MF", "fr-MG", "fr-ML", "fr-MQ", "fr-MR", "fr-MU", "fr-NC", "fr-NE", "fr-PF", "fr-PM", "fr-RE", "fr-RW", "fr-SC", "fr-SN", "fr-SY", "fr-TD", "fr-TG", "fr-TN", "fr-VU", "fr-WF", "fr-YT", "fur", "fur-IT", "fy", "fy-NL", "ga", "ga-IE", "gd", "gd-GB", "gl", "gl-ES", "gn", "gn-PY", "gsw", "gsw-CH", "gsw-FR", "gsw-LI", "gu", "gu-IN", "guz", "guz-KE", "gv", "gv-IM", "ha", "ha-Latn", "ha-Latn-GH", "ha-Latn-NE", "ha-Latn-NG", "haw", "haw-US", "he", "he-IL", "hi", "hi-IN", "hr", "hr-BA", "hr-HR", "hsb", "hsb-DE", "hu", "hu-HU", "hy", "hy-AM", "ia", "ia-001", "ia-FR", "ibb", "ibb-NG", "id", "id-ID", "ig", "ig-NG", "ii", "ii-CN", "is", "is-IS", "it", "it-CH", "it-IT", "it-SM", "iu", "iu-Cans", "iu-Cans-CA", "iu-Latn", "iu-Latn-CA", "ja", "ja-JP", "jgo", "jgo-CM", "jmc", "jmc-TZ", "jv", "jv-Java", "jv-Java-ID", "jv-Latn", "jv-Latn-ID", "ka", "ka-GE", "kab", "kab-DZ", "kam", "kam-KE", "kde", "kde-TZ", "kea", "kea-CV", "khq", "khq-ML", "ki", "ki-KE", "kk", "kk-KZ", "kkj", "kkj-CM", "kl", "kl-GL", "kln", "kln-KE", "km", "km-KH", "kn", "kn-IN", "ko", "ko-KP", "ko-KR", "kok", "kok-IN", "kr", "kr-NG", "ks", "ks-Arab", "ks-Arab-IN", "ks-Deva", "ks-Deva-IN", "ksb", "ksb-TZ", "ksf", "ksf-CM", "ksh", "ksh-DE", "ku", "ku-Arab", "ku-Arab-IQ", "ku-Arab-IR", "kw", "kw-GB", "ky", "ky-KG", "la", "la-001", "lag", "lag-TZ", "lb", "lb-LU", "lg", "lg-UG", "lkt", "lkt-US", "ln", "ln-AO", "ln-CD", "ln-CF", "ln-CG", "lo", "lo-LA", "lrc", "lrc-IQ", "lrc-IR", "lt", "lt-LT", "lu", "lu-CD", "luo", "luo-KE", "luy", "luy-KE", "lv", "lv-LV", "mas", "mas-KE", "mas-TZ", "mer", "mer-KE", "mfe", "mfe-MU", "mg", "mg-MG", "mgh", "mgh-MZ", "mgo", "mgo-CM", "mi", "mi-NZ", "mk", "mk-MK", "ml", "ml-IN", "mn", "mn-Cyrl", "mn-MN", "mn-Mong", "mn-Mong-CN", "mn-Mong-MN", "mni", "mni-IN", "moh", "moh-CA", "mr", "mr-IN", "ms", "ms-BN", "ms-MY", "ms-SG", "mt", "mt-MT", "mua", "mua-CM", "my", "my-MM", "mzn", "mzn-IR", "naq", "naq-NA", "nb", "nb-NO", "nb-SJ", "nd", "nd-ZW", "ne", "ne-IN", "ne-NP", "nl", "nl-AW", "nl-BE", "nl-BQ", "nl-CW", "nl-NL", "nl-SR", "nl-SX", "nmg", "nmg-CM", "nn", "nn-NO", "nnh", "nnh-CM", "no", "nqo", "nqo-GN", "nr", "nr-ZA", "nso", "nso-ZA", "nus", "nus-SS", "nyn", "nyn-UG", "oc", "oc-FR", "om", "om-ET", "om-KE", "or", "or-IN", "os", "os-GE", "os-RU", "pa", "pa-Arab", "pa-Arab-PK", "pa-IN", "pap", "pap-029", "pl", "pl-PL", "prg", "prg-001", "prs", "prs-AF", "ps", "ps-AF", "pt", "pt-AO", "pt-BR", "pt-CV", "pt-GW", "pt-MO", "pt-MZ", "pt-PT", "pt-ST", "pt-TL", "quc", "quc-Latn", "quc-Latn-GT", "quz", "quz-BO", "quz-EC", "quz-PE", "rm", "rm-CH", "rn", "rn-BI", "ro", "ro-MD", "ro-RO", "rof", "rof-TZ", "ru", "ru-BY", "ru-KG", "ru-KZ", "ru-MD", "ru-RU", "ru-UA", "rw", "rw-RW", "rwk", "rwk-TZ", "sa", "sa-IN", "sah", "sah-RU", "saq", "saq-KE", "sbp", "sbp-TZ", "sd", "sd-Arab", "sd-Arab-PK", "sd-Deva", "sd-Deva-IN", "se", "se-FI", "se-NO", "se-SE", "seh", "seh-MZ", "ses", "ses-ML", "sg", "sg-CF", "shi", "shi-Latn", "shi-Latn-MA", "shi-Tfng", "shi-Tfng-MA", "si", "si-LK", "sk", "sk-SK", "sl", "sl-SI", "sma", "sma-NO", "sma-SE", "smj", "smj-NO", "smj-SE", "smn", "smn-FI", "sms", "sms-FI", "sn", "sn-Latn", "sn-Latn-ZW", "so", "so-DJ", "so-ET", "so-KE", "so-SO", "sq", "sq-AL", "sq-MK", "sq-XK", "sr", "sr-Cyrl", "sr-Cyrl-BA", "sr-Cyrl-ME", "sr-Cyrl-RS", "sr-Cyrl-XK", "sr-Latn", "sr-Latn-BA", "sr-Latn-ME", "sr-Latn-RS", "sr-Latn-XK", "ss", "ss-SZ", "ss-ZA", "ssy", "ssy-ER", "st", "st-LS", "st-ZA", "sv", "sv-AX", "sv-FI", "sv-SE", "sw", "sw-CD", "sw-KE", "sw-TZ", "sw-UG", "syr", "syr-SY", "ta", "ta-IN", "ta-LK", "ta-MY", "ta-SG", "te", "te-IN", "teo", "teo-KE", "teo-UG", "tg", "tg-Cyrl", "tg-Cyrl-TJ", "th", "th-TH", "ti", "ti-ER", "ti-ET", "tig", "tig-ER", "tk", "tk-TM", "tn", "tn-BW", "tn-ZA", "to", "to-TO", "tr", "tr-CY", "tr-TR", "ts", "ts-ZA", "tt", "tt-RU", "twq", "twq-NE", "tzm", "tzm-Arab", "tzm-Arab-MA", "tzm-Latn", "tzm-Latn-DZ", "tzm-Latn-MA", "tzm-Tfng", "tzm-Tfng-MA", "ug", "ug-CN", "uk", "uk-UA", "ur", "ur-IN", "ur-PK", "uz", "uz-Arab", "uz-Arab-AF", "uz-Cyrl", "uz-Cyrl-UZ", "uz-Latn", "uz-Latn-UZ", "vai", "vai-Latn", "vai-Latn-LR", "vai-Vaii", "vai-Vaii-LR", "ve", "ve-ZA", "vi", "vi-VN", "vo", "vo-001", "vun", "vun-TZ", "wae", "wae-CH", "wal", "wal-ET", "wo", "wo-SN", "xh", "xh-ZA", "xog", "xog-UG", "yav", "yav-CM", "yi", "yi-001", "yo", "yo-BJ", "yo-NG", "zgh", "zgh-Tfng", "zgh-Tfng-MA", "zh", "zh-CN", "zh-Hans", "zh-Hans-HK", "zh-Hans-MO", "zh-Hant", "zh-HK", "zh-MO", "zh-SG", "zh-TW", "zu", "zu-ZA" };

            var group = cultureNames
                .Select(cultureName => new CultureInfo(cultureName))
                .GroupBy(cultureInfo => cultureInfo.NumberFormat.NumberGroupSeparator)
                .Select(g => $"'{g.Key}': " + string.Join(",", g));
            

            foreach (var g in group)
            {                
                Console.WriteLine(g);
            }
        }

Output is strange NumberGroupSeparator for a quite a few languages. 

'┬á': af,af-NA,af-ZA,agq,agq-CM,az-Cyrl,az-Cyrl-AZ,ba,ba-RU,bas,bas-CM,be,be-BY,bg,bg-BG,br,br-FR,co,co-FR,cs,cs-CZ,cu,cu-RU,de-AT,dje,dje-NE,dua,dua-CM,dyo,dyo-SN,en-FI,en-SE,en-ZA,eo,eo-001,es-CR,et,et-EE,ewo,ewo-CM,ff,ff-CM,ff-GN,ff-Latn,ff-Latn-SN,ff-MR,fi,fi-FI,fr,fr-029,fr-BF,fr-BI,fr-BJ,fr-BL,fr-CA,fr-CD,fr-CF,fr-CG,fr-CH,fr-CI,fr-CM,fr-DJ,fr-DZ,fr-FR,fr-GA,fr-GF,fr-GN,fr-GP,fr-GQ,fr-HT,fr-KM,fr-MC,fr-MF,fr-MG,fr-ML,fr-MQ,fr-MR,fr-MU,fr-NC,fr-NE,fr-PF,fr-PM,fr-RE,fr-RW,fr-SC,fr-SN,fr-SY,fr-TD,fr-TG,fr-TN,fr-VU,fr-WF,fr-YT,gsw-FR,hu,hu-HU,ka,ka-GE,kab,kab-DZ,kea,kea-CV,khq,khq-ML,kk,kk-KZ,ksf,ksf-CM,ksh,ksh-DE,ky,ky-KG,lb,lb-LU,lt,lt-LT,lv,lv-LV,mfe,mfe-MU,nb,nb-NO,nb-SJ,nl-BE,nmg,nmg-CM,nn,nn-NO,no,nr,nr-ZA,nso,nso-ZA,oc,oc-FR,os,os-GE,os-RU,pl,pl-PL,prg,prg-001,pt-AO,pt-CV,pt-GW,pt-MO,pt-MZ,pt-PT,pt-ST,pt-TL,ru,ru-BY,ru-KG,ru-KZ,ru-MD,ru-RU,ru-UA,sah,sah-RU,se,se-FI,se-NO,se-SE,ses,ses-ML,shi,shi-Latn,shi-Latn-MA,shi-Tfng,shi-Tfng-MA,sk,sk-SK,sma,sma-NO,sma-SE,smj,smj-NO,smj-SE,smn,smn-FI,sms,sms-FI,sq,sq-AL,sq-MK,sq-XK,ss,ss-SZ,ss-ZA,st,st-LS,st-ZA,sv,sv-AX,sv-FI,sv-SE,tg,tg-Cyrl,tg-Cyrl-TJ,tk,tk-TM,tn,tn-BW,tn-ZA,ts,ts-ZA,tt,tt-RU,twq,twq-NE,tzm,tzm-Arab,tzm-Arab-MA,tzm-Latn,tzm-Latn-DZ,tzm-Latn-MA,tzm-Tfng,tzm-Tfng-MA,uk,uk-UA,uz,uz-Cyrl,uz-Cyrl-UZ,uz-Latn,uz-Latn-UZ,ve,ve-ZA,wo,wo-SN,xh,xh-ZA,yav,yav-CM,zgh,zgh-Tfng,zgh-Tfng-MA

Also i get
'ÔÇÖ': gsw,gsw-CH,gsw-LI,rm,rm-CH,wae,wae-CH,wal,wal-ET which in "legacy" .NET / Windows 10 is '’'.

**Comment by svick** [comment]
I think this is a duplicate of https://github.com/dotnet/corefx/issues/10054.

In short, to fix this either change the encoding of the console to UTF-8 (using `chcp 65001`) or add a dependency to `System.Text.Encoding.CodePages` to your project.json and add `Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);` at the start of your application.

**Comment by osjoberg** [comment]
@svick thank you, you are right, the character is non-breaking space which makes sense.
