### ISSUE TITLE
HttpClient + certificate specified throws if certificate is cloned in Linux

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/corefx#12214]
Given the following setup: 

* Website (in this case, IIS hosted) requires client certificates to be specified for accessing an endpoint
* .NET Core app specifies a client certificate and makes a request in the following manner

```csharp
            // assume certColl is an X509CertificateCollection obtained by using X509Store.Find
            // Scenario 1: 
            // var clientCert = certcoll[0];                               // Scenario works in Linux and Windows 
            // Scenario 2: 
            // var clientCert = new X509Certificate2(certcoll[0].Handle);  // Scenario works in Windows only; fails in Linux 

            HttpClientHandler handler = new HttpClientHandler();
            handler.ClientCertificates.Add(clientCert);
            var httpClient = new HttpClient(handler);
            response = httpClient.GetAsync("https://some-server/ClientCertificateRequired/").GetAwaiter().GetResult();
```

For these scenarios: 

| | Find certificate from X509Store and use directly | Find certificate and clone |
|---|---|---|
| Windows | ✔ Succeeds  | ✔ Succeeds |
| Ubuntu14.04 | ✔ Succeeds | ✖ Fails with CurlException |

The failing stack in Linux is: 

```
Unhandled Exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Failure when receiving data from the peer
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApplication.Program.Main(String[] args)

```

Repro app is here: https://gist.github.com/iamjasonp/b05da61cb1a30d36b0892915600d36d3

**Comment by bartonjs** [comment]
@iamjasonp 

```C#
var clientCert = new X509Certificate2(certcoll[0].Handle); 
```

That doesn't work on Linux.  There's not one IntPtr which contains both the public and private key; so clientCert.HasPrivateKey will be false; causing your connection to fail to bind.

X509CertificateCollection2.Find already duplicates the cert, why do you need to duplicate it again?

**Comment by iamjasonp** [comment]
We do a clone because we also have the ability for someone to provide us the certificate directly. 

We want to avoid the case where someone provides us with the certificate and, because they think they own the certificate disposal, they dispose and cause issues when using the very

**Comment by bartonjs** [comment]
The safe but somewhat hacky looking way that exists right now is

```C#
X509Certificate2Collection coll = new X509Certificate2Collection(cert);
X509Certificate2Collection copyColl = coll.Find(X509FindType.FindByThumbprint, cert.Thumbprint, false);
X509Certificate2 copy = copyColl[0];
```

It's a bit silly looking, but will keep the private key around.  The copy constructor is coming back as part of netstandard20; and it'll do the right thing.

**Comment by iamjasonp** [comment]
Oof, that's kinda painful, having to work around code that we expect to be fixed in netstandard2.0...

**Comment by bartonjs** [comment]
> that's kinda painful, having to work around code that we expect to be fixed in netstandard2.0...

Just to be clear on this:  `new X509Certificate2(IntPtr)` won't ever work right on Linux (if you expected the private key to be available... for public-only it's fine).  `new X509Certificate2(X509Certificate)` will work correctly.

**Comment by iamjasonp** [comment]
Ack - good to know. I think it should be no problem for WCF to convert to the copy constructor. What were the differences between using the copy ctor and using the Handle in desktop?

**Comment by bartonjs** [comment]
I was going to say "ArgumentNullException vs NullReferenceException if the cert is null", but
http://referencesource.microsoft.com/#mscorlib/system/security/cryptography/x509certificates/x509certificate.cs,176 seems to slightly disagree, though.  The copy constructor causes the SafeHandle to finalize because neither copy is willing to accept ownership.

@morganbr: Is there any visible effect of what the copy ctor is doing vs what the IntPtr ctor does that you can think of?  It seems like we could make the copy ctor just do DuplicateCertContext as well and make life happy...

**Comment by bartonjs** [comment]
Since this was a limitation of the underlying platform (OpenSSL X509 objects don't have private key info, unlike Win32 CERT_CONTEXT) and there's a workaround; I'm closing the issue.

**Comment by iamjasonp** [comment]
Bug for copy ctor addition: https://github.com/dotnet/corefx/pull/12240
