### ISSUE TITLE
Consider renaming/splitting System.ComponentModel.TypeConverter

### ISSUE THREAD

**Issue by AlexGhiondea** [dotnet/corefx#12215]
The work to port the additional ComponentModel types put all of them in the System.ComponentModel.TypeConverter assembly/contract.

Since there are more concepts in that assembly than TypeConverter we should consider either renaming this assembly/contract or split the contract into separate pieces.

Here are some of the things inside the assembly:
- TypeConverter types
- Designer support types
- Helper types/classes

**Comment by karelz** [comment]
@AlexGhiondea says there is no particular reason to do it. Closing.
