### ISSUE TITLE
Allocating parallel loop slower in core than desktop

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#12217]
Certain CoreFX Task operations/scheduling appears to be slower compared to .Net Desktop for certain workloads and machine configurations.

Repro: https://github.com/CIPop/perf/tree/master/ThreadPerf/src
Instructions: https://github.com/CIPop/perf/blob/master/README.md

Initial Perfmon hot-path analysis shows important timing differences on the `TaskReplicator`, `ThreadPoolWorkQueue.Dispatch()` and `intermediateThreadProc` code path.
### Results

In summary, the differences are bigger when the number of CPUs increases and can reach up to ~70% decrease in performance for a 16 core box.
For the A1 case, an up to 19% performance _increase_ was observed for CoreFX.

![image](https://cloud.githubusercontent.com/assets/8635911/18977396/ca04b512-866e-11e6-91e4-da7613683c50.png)

**16Core Dev machine**

```
.Net Desktop 4.6.2:
(0): 00:00:03.6069321
(1): 00:00:03.5532334
(2): 00:00:03.5792650
.Net Core:
(0): 00:00:05.7018041
(1): 00:00:06.4660423
(2): 00:00:06.2088087
.Net Core is  71.0311631138344 % slower (incl. process creation overheads).
```

**Azure A4 machine**

```
.Net Desktop 4.6.2:
(0): 00:00:10.3151684
(1): 00:00:10.6153461
(2): 00:00:10.8002867
.Net Core:
(0): 00:00:12.7079665
(1): 00:00:13.2266033
(2): 00:00:13.1223560
.Net Core is  23.5348989000614 % slower (incl. process creation overheads).
```

**Azure DS2 machine**

```
.Net Desktop 4.6.2:
(0): 00:00:06.8964238
(1): 00:00:07.0116513
(2): 00:00:06.7201754
.Net Core:
(0): 00:00:07.0788306
(1): 00:00:06.6521635
(2): 00:00:06.9412770
.Net Core is  0.44823964489224 % slower (incl. process creation overheads).
```

**Azure A1 machine**

```
.Net Desktop 4.6.2:
(0): 00:00:20.7025224
(1): 00:00:20.7083212
(2): 00:00:20.9549189
.Net Core:
(0): 00:00:17.7732198
(1): 00:00:16.4779742
(2): 00:00:16.9521813
.Net Core is  -17.2535449554775 % slower (incl. process creation overheads).
```

**Comment by benaadams** [comment]
@CIPop I have the following batch of tests which you may wish to run for comparisions: https://github.com/benaadams/ThreadPoolTaskTesting

**Comment by CIPop** [comment]
Wow, I wasn't aware of that investigation. That's really cool @benaadams! 
Would it be easy to compare the results with a baseline such as .Net Desktop?

**Comment by benaadams** [comment]
I assume just need to add a `net462` in the project.json?

I probably should get it to output csv or something too...

**Comment by benaadams** [comment]
Other thing to check is what happens when you bump the min threads in Core
```
set COMPlus_ThreadPool_ForceMinWorkerThreads=32
```

**Comment by CIPop** [comment]
No changes are needed: the comparison is not between Core projects but an actual .Net Desktop console app and a Core app. It doesn't output to csv, yet. Feel free to submit PRs to my branch.
The run instructions are exactly those in the README.md in the root of my enlistment: .\build.ps1 once followed by .\run.ps1 (runs the test 3 times for each).

The graph above was made by running the tests on multiple Azure and Dev boxes and the results would need to be gathered from all boxes - I don't have a solution for that yet either.

> what happens when you bump the min threads 

Nothing much on my 12 core box (also corrected above: the result is for 1 socket, 6 cores, 12 logical not 16 logical).

```
S:\perf\ThreadPerf\src [master ≡]> .\run.ps1
.Net Desktop 4.6.2:
(0): 00:00:03.6308145
(1): 00:00:03.5843749
(2): 00:00:03.6219840
.Net Core:
(0): 00:00:05.8306708
(1): 00:00:06.2922156
(2): 00:00:07.0459062
.Net Core is  76.8918770606791 % slower (incl. process creation overheads).
S:\perf\ThreadPerf\src [master ≡]> set COMPlus_ThreadPool_ForceMinWorkerThreads=32
S:\perf\ThreadPerf\src [master ≡]> .\run.ps1
.Net Desktop 4.6.2:
(0): 00:00:03.6121460
(1): 00:00:03.6045982
(2): 00:00:03.7740922
.Net Core:
(0): 00:00:05.7259386
(1): 00:00:05.6176809
(2): 00:00:05.3964804
.Net Core is  52.9208299678666 % slower (incl. process creation overheads).
S:\perf\ThreadPerf\src [master ≡]> .\run.ps1
.Net Desktop 4.6.2:
(0): 00:00:03.6736228
(1): 00:00:03.6099018
(2): 00:00:03.5741057
.Net Core:
(0): 00:00:05.8734370
(1): 00:00:06.4101777
(2): 00:00:06.5454996
.Net Core is  73.5213246001284 % slower (incl. process creation overheads).
```

**Comment by benaadams** [comment]
> the result is for 1 socket, 6 cores, 12 logical 

Oh, interesting! 

For my test suite I was getting degradation for HT on some of the tests vs a less powerful non-HT machine; but not for all - mostly when the actions were queued to the global queue; rather than the thread local queues.

**Comment by stephentoub** [comment]
@CIPop, thanks for looking into this and sharing results.  Are you sure this is measuring what you think it's measuring?

The test you shared is calling this Run method in the body of a Parallel.For:
```C#
        public async Task Run()
        {
            for (int i = 0; i < IterationPerTask; i++)
            {
                await DoNoWork();
                await DoNoWork();
                await DoNoWork();
                await DoNoWork();
                await DoNoWork();
                await DoNoWork();
                await DoNoWork();
            }
        }

        public Task<object> DoNoWork()
        {
            return Task.FromResult<object>(null);
        } 
```
That's not actually scheduling any tasks or even accessing the thread pool at all: a call to Run will complete synchronously after allocating 7,000 task objects.

So effectively each iteration of the Parallel.For allocates 7,000 objects synchronously and then creates a single task continuation that's queued immediately. I do see that your example runs slower on core than on desktop, but I don't think it has anything to do with Task.  When I look at a trace after letting this run for a few minutes, I see almost 90% of the time spent in allocation/GC, and that's just on a dual-core; as the thread count increases, so too does the time spent in allocation/GC.  Further, when I change one line in your repro from `return Task.FromResult<object>(null);`` to `return Task.CompletedTask;`, which just avoids that single allocation, I see the repro run at least an order of magnitude faster, and run measurably faster on core than on desktop.

Even if there was an issue here related to threading, I somewhat doubt it'd be a difference in either the thread pool or tasks.  The implementation of both of those is almost exactly the same on core on Windows as it is in desktop, other than recent performance improvements we've made for 2.0, e.g. around reducing overhead in the thread pool's queue.  However, the Parallel.For implementation does have some differences between desktop and core, so if there were an issue in that aspect of the repro, I would first look there.  But, I'm not seeing anything in the traces that suggest it's Parallel.For.

I do see the thread count increasing more in the core run than in the desktop run.  I suspect there's some kind of negative feedback loop happening here between the thread pool and GC, e.g. GC is taking longer, causing each iteration of the Parallel.For to take longer, which causes more threads to be introduced to alleviate what's viewed as starvation, which causes GC to take longer, which causes each iteration of the Parallel.For to take longer, which causes more threads to be introduced to alleviate what's viewed as starvation, which causes GC to take longer... and so on.  If I change the Parallel.For call to limit the number of threads it's allowed to use (e.g. `new ParallelOptions { MaxDegreeOfConcurrency = 4 }`), then things also run much quicker, which helps to validate this hypothesis.

cc: @Maoni0, @swgillespie, @kouvel

**Comment by CIPop** [comment]
Thanks @stephentoub! 

> Are you sure this is measuring what you think it's measuring?

Not really as I have not investigated this in depth. Together with Eric, we made the simplest assumption based on the fact that the code was using Tasks/ThreadPool and the issue was accentuated on a high CPU-count machine. 

> If I change the Parallel.For call to limit the number of threads it's allowed to use (e.g. new ParallelOptions { MaxDegreeOfConcurrency = 4 }), then things also run much quicker, which helps to validate this hypothesis.

One more thing to try would be to run a perf test for the GC alone (no threads or tasks) and compare with .Net Framework. I would assume that the differences would be less obvious (assuming that the thread overheads are >> GC's perf decrease from Desktop).

**Comment by stephentoub** [comment]
I believe I found the simple one-line root cause for this specific repro.  Will submit a fix.
