### ISSUE TITLE
Expose AppDomain.CurrentDomain.GetAssemblies

### ISSUE THREAD

**Issue by AlexGhiondea** [dotnet/corefx#12211]
The following are needed in System.ComponentModel.TypeConverter.

AppDomain.CurrentDomain.GetAssemblies
AppDomain.CurrentDomain.SetupInformation.LicenseFile

**Comment by AlexGhiondea** [comment]
AppDomain.CurrentDomain.GetAssemblies
AppDomain.CurrentDomain.SetupInformation.LicenseFile

**Comment by jkotas** [comment]
`AppDomain.CurrentDomain.SetupInformation.LicenseFile` is not coming back. You should assume that it is always null.

**Comment by AlexGhiondea** [comment]
Thanks @jkotas.

**Comment by danmosemsft** [comment]
@rahku is bringing back GetAssemblies as part of https://github.com/dotnet/corefx/issues/9327.
