### ISSUE TITLE
Track System.Security.Cryptography.X509Certificates ns 1.6 update for 1.1.0 release

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#12235]
Several tests in System.Security.Cryptography.X509Certificates.Tests require code added in 1.1.0 (to System.Security.Cryptography.X509Certificates) which has not yet pushed to ns1.6. They should be re-enabled once ns1.6 is updated with 1.1.0 bits

**Comment by karelz** [comment]
@steveharter is it part of 1.1.0 release?

**Comment by steveharter** [comment]
Not sure yet. I am actively researching this to ensure that something didn't break unexpectedly. It wasn't discovered until my project changes caused the netcoreapp 1.0 tests to use the official 1.0 bits for testing.

**Comment by steveharter** [comment]
The tests affected are
        public static void TestKey_BrainpoolP160r1()
        public static void TestKey_ECDsabrainpool_PublicKey(byte[] curveData, byte[] notUsed)
        public static void TestECDsaPublicKey_BrainpoolP160r1_ValidatesSignature(byte[] curveData, byte[] existingSignature)
        public static void TestKey_BrainpoolP160r1()

**Comment by steveharter** [comment]
Link to PR: https://github.com/dotnet/corefx/pull/12240

@bartonjs fyi

The cause of the test failures running in netcoreapp1.0\ns1.6 was the 4.1 version of S.S.C.X509Certificate (v1.0 corefx) being used instead of 4.1.1 (v1.1) again because 4.1.1 is not yet in public nuget yet and not yet associated with ns1.6.

The older assembly version does not include the following (which the tests depend on):
(PropsTests) https://github.com/dotnet/corefx/commit/05477609766814fa4e5c567dcd5afe48e144ef45#diff-cbf92b351a9c693d1ec8000a0037d887
(BrainPool* tests) https://github.com/dotnet/corefx/commit/3debb53396c688ae4111df3222282cd9537b7760#diff-d2fdab3a9339be78b1237fbabc93cb28

**Comment by karelz** [comment]
@steveharter do we need to port it to 1.1.0 release branch?

**Comment by steveharter** [comment]
@karelz no the two links reference code that has existed for months, so it is already in 1.1.0. The issue is that 1.1.0 is not public yet (in nuget)
