### ISSUE TITLE
Intermittent: CaseInsensitiveComparerTests.Default_Compare_TurkishI failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12242]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/865/consoleText
```
     System.Collections.Tests.CaseInsensitiveComparerTests.Default_Compare_TurkishI [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   1
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\System.Collections.NonGeneric\tests\CaseInsentiveComparerTests.cs(203,0): at System.Collections.Tests.CaseInsensitiveComparerTests.Default_Compare_TurkishI()
```

**Comment by ianhays** [comment]
Looks like these tests are allowed to run in parallel. They are all setting the default culture, so it's potentially likely that we could be modifying the culture after checking `culture.Name == "tr-TR"` in this test. It's unlikely - but possible - to fail intermittently because of that.

**Comment by stephentoub** [comment]
They're setting the culture for the process or for the current thread? The former should be done out of proc via remote invoke.

**Comment by ianhays** [comment]
>They're setting the culture for the process or for the current thread? 

The process:
```
CultureInfo.DefaultThreadCurrentCulture = culture;
CultureInfo.DefaultThreadCurrentUICulture = culture;
```

**Comment by stephentoub** [comment]
Ah, then yeah, that's almost certainly the culprit :smile:
