### ISSUE TITLE
Complete S.R.ConstrainedExecution namespace

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#12255]
Just two missing types, both attributes.

```
T:System.Runtime.ConstrainedExecution.PrePrepareMethodAttribute
T:System.Runtime.ConstrainedExecution.ReliabilityContractAttribute
```

**Comment by joperezr** [comment]
`T:System.Runtime.ConstrainedExecution.ReliabilityContractAttribute` seems to be done already, so we only need to add the other one.
