### ISSUE TITLE
CI Timeout during FileSystemWatcher tests

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#12252]
This built for ~35 mins then began running tests. Test logging stops after ~10 mins. Eventually the run times out, apparently during the FileSystemWatcher tests

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_release_prtest/882/consoleFull#147575877179494335-f7bd-47d0-8771-8661e00c2db2 

I'm not sure why it throws `System.DllNotFoundException: Unable to load DLL 'KERNEL32.DLL':` that may just be an artefact of how things are being torn down, but the logging seems to clearly be from `System.IO.FileSystem.Watcher.Tests.csproj`.

**Comment by danmosemsft** [comment]
@ianhays are there any known hangs in these tests?
/cc @karelz

**Comment by danmosemsft** [comment]
Another possibility: the FSW tests were just next to start, and as an artefact of how the build is being terminated they were briefly started then quickly terminated. This is consistent with there being no message indicating they were started before the termination.

**Comment by ianhays** [comment]
>@ianhays are there any known hangs in these tests?

Not that I've ever seen.

Looking at the link, the logs show the FSW tests finishing:
```
12:47:47   Finished:    System.IO.FileSystem.Watcher.Tests
12:47:47   
12:47:47   === TEST EXECUTION SUMMARY ===
12:47:47      System.IO.FileSystem.Watcher.Tests  Total: 202, Errors: 0, Failed: 0, Skipped: 0, 
```

So the DLL failure is occurring after that for some reason.

**Comment by karelz** [comment]
We couldn't repro. We need hang dumps -- I will create infra bug.
