### ISSUE TITLE
Two members missing from BinaryFormatter

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#12254]
```
M:System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.DeserializeMethodResponse(System.IO.Stream,System.Runtime.Remoting.Messaging.HeaderHandler,System.Runtime.Remoting.Messaging.IMethodCallMessage)
M:System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.UnsafeDeserializeMethodResponse(System.IO.Stream,System.Runtime.Remoting.Messaging.HeaderHandler,System.Runtime.Remoting.Messaging.IMethodCallMessage)
```

@stephentoub did you intentionally omit these two?

**Comment by stephentoub** [comment]
> @stephentoub did you intentionally omit these two?

They rely on unavailable remoting types.  If System.Runtime.Remoting.Messaging.HeaderHandler and System.Runtime.Remoting.Messaging.IMethodCallMessage are coming back, then we can add these as well.

**Comment by danmosemsft** [comment]
Ah right. Those are coming back in https://github.com/dotnet/corefx/issues/11809.

**Comment by shmao** [comment]
@ramarag, assigning the issue to you as you are working on #11809.

**Comment by ramarag** [comment]
We are not adding these, see discussion on https://github.com/dotnet/corefx/issues/11809#issuecomment-253126440
