### ISSUE TITLE
Complete System.Diagnostics namespace

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#12260]
These types are either missing or incomplete.

- [x] T:System.Diagnostics.CorrelationManager
- [x] T:System.Diagnostics.DebuggerStepperBoundaryAttribute
- [x] T:System.Diagnostics.DebuggerVisualizerAttribute
- [x] T:System.Diagnostics.MonitoringDescriptionAttribute
- [x] T:System.Diagnostics.Process
- [x] T:System.Diagnostics.ProcessModule
- [x] T:System.Diagnostics.ProcessModuleCollection
- [x] T:System.Diagnostics.ProcessThread
- [x] T:System.Diagnostics.ProcessThreadCollection
- [x] T:System.Diagnostics.ProcessWindowStyle
- [x] T:System.Diagnostics.StackFrame
- [x] T:System.Diagnostics.StackTrace
- [x] T:System.Diagnostics.SwitchAttribute
- [x] T:System.Diagnostics.SwitchLevelAttribute
- [x] T:System.Diagnostics.TraceListener

Some of these will need to throw PNSE, eg., many of the missing members of Process.

**Comment by weshaggard** [comment]
I suggest this issue be split up as it has a number of different tasks. Process, Tracing, StackTrace being three of the specific areas.

**Comment by 304NotModified** [comment]
What does checked and unchecked mean in the start post?

**Comment by AlexGhiondea** [comment]
@304NotModified I am not sure what you mean. Could you give me a link to what you were asking about?

**Comment by 304NotModified** [comment]
https://github.com/dotnet/corefx/issues/12260#issue-180414140i s using check boxes. If the check box had been checked, then it's already implemented (in a branch?)?

**Comment by AlexGhiondea** [comment]
Yes -- if there is check it means the types / members have been added.

**Comment by 304NotModified** [comment]
In which Branch? Master?

**Comment by weshaggard** [comment]
Yes this work is in the master branch.

**Comment by AlexGhiondea** [comment]
Re-opening because Process is still not complete.

**Comment by AlexGhiondea** [comment]
Closing this as all the types listed here have been ported.

**Comment by huangsam** [comment]
Was curious if there's still an effort made for porting the `Eventing` namespace over to C# - I noticed that it does not exist using `dotnet run` and created a SO post over here: https://stackoverflow.com/questions/46915998/eventing-namespace-does-not-exist-in-system-diagnostics-in-net-core-and-mon
