### ISSUE TITLE
Running tests from Visual Studio insists on copying old product binaries

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#12275]
I'm not exactly sure on the steps to consistently repro this, but what I'm seeing is this, for the `System.Linq.Expressions` project:
- Running `msbuild` from the command line drops the privately built product binary into `bin\tests\AnyOS.AnyCPU.Debug\System.Linq.Expressions.Tests\netcoreapp1.0`
- Subsequently running the test project from Visual Studio, with the above location as the working directory, triggers a build and it copies an older file to the folder above
- The test runner fails to load the binary

I'll try to dig a little deeper to figure out where it copies the stale file from. There's no consistent workaround; I mostly try to manually copy files into the output folder while hoping that pressing F5 in Visual Studio doesn't cause it to get overwritten.

**Comment by stephentoub** [comment]
cc: @weshaggard, @mattgal

**Comment by tarekgh** [comment]
@bartdesmet is this still happening?

**Comment by weshaggard** [comment]
I don't think this is an issue any longer after our recent engineering changes.
