### ISSUE TITLE
Add setter to CanWrite property in MemoryStream

### ISSUE THREAD

**Issue by SunnyWar** [dotnet/corefx#12289]
In many network and database uses a MemoryStream is used to populate a stream of bytes. After the stream is filled another stream has to be created in order to return on that is read-only. The inability to set the CanWrite property in a MemoryStream object results in unnecessary allocations and inefficiencies

Rationale and Usage
-------------------------------------
In, DbDataReader.cs the GetStream method illustrated the need. Buffered data is read and appended to a stream, which is then returned.  In this code in CoreFx System.Data.Common the choice is to allocate and populate _another_ MemoryStream.
`virtual public Stream GetStream(int ordinal)
 {
        using (MemoryStream bufferStream = new MemoryStream())
        {
              /// ... populates the stream
              return new MemoryStream(bufferStream.ToArray(), false);
        }
}
`
If the CanWrite were setter the above example would be:
`virtual public Stream GetStream(int ordinal)
 {
        using (MemoryStream bufferStream = new MemoryStream())
        {
              /// ... populates the stream
              bufferStream.CanWrite = false;
              return bufferStream;
        }
}
`
The code is simpler, easier to read, reduces allocations, and runs faster.

Proposed API
------------------------------------
For MemoryStream class change
public override bool CanWrite { get; }
to
public override bool CanWrite { get; set; }

Open Questions
----------------------------

- Should this change apply to the Stream class instead?

**Comment by jamesqo** [comment]
Is this even possible? I think in C# if a base class has a virtual or abstract property that only has get/set, and you override it adding another accessor, you'll get an error from the compiler.

**Comment by SunnyWar** [comment]
@jamesqo you are right. I'll modify the description to indicate the Stream must have a setter.

**Comment by SunnyWar** [comment]
@jamesqo ah....hmmm.   So this is a problem and the way around it is to add a setter to the base class BUT,  adding the setter to Stream means that everyone in the world that has inherited from Stream will be broken. I don't see anyway to get around this.

I'm sad but I will close this proposal.
