### ISSUE TITLE
HashSetEqualityComparer is not marked as Serializable

### ISSUE THREAD

**Issue by unshorn** [dotnet/corefx#12281]
On .NET 4.6 HashSetEqualityComparer is marked as Serializable.

https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/HashSetEqualityComparer.cs

compared to:

http://referencesource.microsoft.com/#System.Core/System/Collections/Generic/HashSetEqualityComparer.cs,b81a34218101efe7,references

Thank you.

**Comment by ianhays** [comment]
Hmm. I thought I removed this class. I guess we added it back for netstandard2.0.

Looks like it should be serializable.

**Comment by ianhays** [comment]
fyi: @Stephentoub @Priya91
