### ISSUE TITLE
Expose IDictionary members on ExpandoObject

### ISSUE THREAD

**Issue by robertmclaws** [dotnet/corefx#12286]
## Scope

Make it easier to check the makeup of a particular `ExpandoObject` by exposing some of the currently private `IDictionary` members.
## Rationale

`ExpandoObject` has some great methods built in to help you get the values of the dynamic members of the object. But what if you want to check the object's definition? [According to this solution](http://stackoverflow.com/a/2839629/403765), the best way is to cast to `IDictionary`, so you can call `ContainsKey(string key)`. However, ExpandoObject already HAS the ContainsKey method, it's just internal. So exposing it, and possibly some other methods, would let you key the Keys without having to cast every time.
## Usage

[Setting `ContainsKey` to public](https://github.com/dotnet/corefx/blob/master/src/System.Dynamic.Runtime/src/System/Dynamic/ExpandoObject.cs#L647) would allow for the following pseudocode:

``` cs
void DynamicTest(ExpandoObject expando)
{
    if (expando.ContainsKey("DoSomething"))
    {
        Console.WriteLine("We've got one!");
    }
}

var test1 = new ExpandoObject();
test.DoSomething = "Get some!";
DynamicTest(test1);

var test2 = new ExpandoObject();
test.DoSomethingElse = "Get lost!";
DynamicTest(test2);
```

This type of capability would be very useful when parsing CVS files or other web services when you don't know what the schema will be ahead of time.
## Implementation

All that would be needed is to take the IDictionary members that are assumed private due to lack of an access keyword, and make them public.
## Obstacles

None that I can forsee.

**Comment by svick** [comment]
Would this affect how `ExpandoObject` behaves as `dynamic`? If it did, then the behavior of this code would change:

```c#
dynamic eo = new ExpandoObject();

try
{
	eo.ContainsKey("");
}
catch (RuntimeBinderException)
{
	Func<string, bool> containsKey = s => true;
	eo.ContainsKey = containsKey;
}

Console.WriteLine(eo.ContainsKey("foo"));
```

Admittedly, it's a fairly convoluted example and it's quite possible nobody ever wrote code like this.

**Comment by robertmclaws** [comment]
This is a good point, it is a possibility. Not sure how that would play out.

**Comment by karelz** [comment]
Casting to IDictionary unblocks people to achieve their goal. Exposing members on the type would be a breaking change (name collisions). The value is not worth the breaking change.
