### ISSUE TITLE
Should we check source.Count every time SelectListPartitionIterator.MoveNext is called?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#12283]
Currently, we check `source.Count` every time we iterate through a `SelectListPartitionIterator`: https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Select.cs#L713.

Presumably, this is so that if we update the `IList` in question while we are iterating the sequence returned by Skip/Take, we will still run the selector on the elements added. For example:

```cs
List<int> ids = GetCustomerIds();
foreach (var c in ids.Select(i => Customer.From(i)).Skip(5))
{
    if (c.HasChildren)
    {
        ids.AddRange(c.ChildrenIds); // we will pass over these in the foreach loop
    }
}
```

However, this will do a dead stop the moment we modify the source list:

```cs
foreach (int id in ids.Select(i => Customer.From(i))) // no .Skip(5)
{
    if (c.HasChildren)
    {
        // Instead of indexing into the list, we're getting it's enumerator here
        // AddRange mutates ids._version, which causes the enumerator's MoveNext to return false
        ids.AddRange(c.ChildrenIds);
    }
}
```

My question is, should adding stuff to the list while enumerating from `Skip` be a supported scenario? It seems like [during RC1](https://github.com/dotnet/corefx/blob/release/1.0.0-rc1/src/System.Linq/src/System/Linq/Enumerable.cs#L832-L848) we would just stop during `Select(...).Take` if the source was modified during enumeration, so it's very unlikely people are going to depend on this change.

Perhaps we should just cache the count when the first `MoveNext` is called, e.g.

```cs
private int _count;

public override bool MoveNext()
{
    switch (_state)
    {
        case 1:
            _count = _source.Count;
            _state = 2;
            goto case 2;
        case 2:
            if (_index <= _maxIndexInclusive && _index < _count)
            {
                ...
            }
    }
}
```

This will still not match the original behavior of stopping once the source is modified. However, it will be faster than the current behavior, which enumerates the entire list taking into account any modifications that have occurred even after the first `MoveNext`, since we are now caching `_count`. (Additionally, it will still preserve behavior in cases where the list is mutated after `Skip` is called, but before it's actually iterated.)

@stephentoub, @VSadov, @JonHanna

**Comment by VSadov** [comment]
I think the Cont check is for a case if the list somehow got shorter while iterating - so that we would not cause OutOfRange exception.

**Comment by jamesqo** [comment]
@VSadov Makes sense-- we would not want to throw exceptions on what were previously valid codepaths. Looks like I'll be closing this then.
