### ISSUE TITLE
Convert.DBNull != DBNull.Value

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12292]
System.Convert.DBNull needs to return DBNull.Value.  DBNull needs to be type-forwarded down to and exposed from System.Runtime, otherwise the two different DBNull types don't have the same type identity.  Convert.IsDBNull also fails to correctly identify DBNull.Value, and TypeCode.DBNull is missing.

cc: @weshaggard, @danmosemsft

**Comment by weshaggard** [comment]
Yes it needs to be moved down into System.Runtime.

**Comment by sepidehMS** [comment]
Done by https://github.com/dotnet/corefx/pull/12514
