### ISSUE TITLE
Consider combining ImmutableExtensions w/ EnumerableHelpers

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#12298]
[ImmutableExtensions](https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableExtensions.cs) contains many similar methods to `EnumerableHelpers` in Common. We should take a look at combining the two.

**edit:** Changed the title to 'Consider...' I realized there is some code specific to System.Collections.Immutable in that file.

**Comment by stephentoub** [comment]
> I realized there is some code specific to System.Collections.Immutable in that file.

I don't see value here in making such a change. If it happens organically as part of other changes, fine. But there is so much additional functionality here, it would be a negative to just add that code to the other file, as then other assemblies would be including it unnecessarily.

**Comment by jamesqo** [comment]
@stephentoub I see your point, I can close this issue.

> I also don't believe we need or want issues tracking such things, unless we're sure we want to do it and it's just a matter of who and when. Otherwise it just adds noise to the already extensive issues list.

Noted. I'll try to be more conservative opening issues from now on.

**Comment by stephentoub** [comment]
Thanks :)
