### ISSUE TITLE
Packages on nuget.org are missing Git sha / TFS ID

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/corefx#12294]
It seems this regressed, e.g. [System.Collections 4.0.11](https://www.nuget.org/packages/System.Collections/4.0.11) doesn't have the Git/TFS information embedded, while [System.Collections 4.0.11-rc2-24027](https://www.nuget.org/packages/System.Collections/4.0.11-rc2-24027) did:

![image](https://cloud.githubusercontent.com/assets/1376924/19022129/edf960bc-88d0-11e6-9b2c-f96e52f0d834.png)

vs.

![image](https://cloud.githubusercontent.com/assets/1376924/19022133/f8ae6444-88d0-11e6-957c-e8666adbf867.png)

**Comment by karelz** [comment]
@ericstj @weshaggard  is it expected?

**Comment by ericstj** [comment]
The hooks were present in the package build, but the hookup was not done when CoreFx moved from TFS to VSO builds.  I've known about it for a while, but assumed it was intentional.  @markwilkie @chcosta can you comment?

**Comment by chcosta** [comment]
The infrastructure is in place, but the priority on this hasn't been as high as it probably should be.  The current plan is to include a "version.txt" file in our packages instead of including the information in the package description.

https://github.com/dotnet/buildtools/pull/849/files

I'll try to get this updated in CoreFx this sprint.

**Comment by karelz** [comment]
Do we need it for 1.1?

**Comment by chcosta** [comment]
If there are other fixes going in for 1.1, then I think that adding this will provide real value.  If no other changes are going in for 1.1, then we could just publish this information somewhere.

**Comment by karelz** [comment]
I think we will have bunch of 1.1 fixes.

**Comment by chcosta** [comment]
For release 1.1, the commit sha is available in the assembly informational version (on Windows).   Later releases now include commit information in each package as a .txt file.
