### ISSUE TITLE
ImmutableArray.LastIndexOf(T) does not inline

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#12296]
Found during testing that this method does not inline: https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.cs#L384

Bizarrely, its neighbor `LastIndexOf(T, int)` does although it intuitively appears larger. I suspect is has to do something w/ the fact `self.Length` is being accessed multiple times in the first overload.

**Comment by stephentoub** [comment]
Why are we opening issues for whether a particular method inlines?

**Comment by jamesqo** [comment]
@stephentoub Apologies, I'll close this.

**Comment by stephentoub** [comment]
Thanks. It's fine to open issues about  real performance problems, and fixing particular cases of non-inlining may help solve some such problems, but whether a particular method inlines is not in and of itself a perf problem. There are good reasons the compiler doesn't just inline everything.
