### ISSUE TITLE
Port System.Security.Cryptography.SignatureDescription

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#12302]
public class SignatureDescription

Depends on CryptoConfig.CreateFromName(string)

```
M.SignatureDescription.#ctor
M.SignatureDescription.#ctor(System.Security.SecurityElement)
P.SignatureDescription.DeformatterAlgorithm
P.SignatureDescription.DigestAlgorithm
P.SignatureDescription.FormatterAlgorithm
P.SignatureDescription.KeyAlgorithm
M.SignatureDescription.CreateDeformatter(System.Security.Cryptography.AsymmetricAlgorithm)
M.SignatureDescription.CreateDigest
M.SignatureDescription.CreateFormatter(System.Security.Cryptography.AsymmetricAlgorithm)
```

**Comment by steveharter** [comment]
Depends on CryptoConfig (https://github.com/dotnet/corefx/issues/12327). CryptoConfig changes and tests should be modified as appropriate (to include SignatureDescription)

**Comment by ianhays** [comment]
@steveharter looks like this should go in the System.Security.Cryptography.Algorithms assembly, yes?

**Comment by steveharter** [comment]
Yes - S.S.C.Algorithms

**Comment by ianhays** [comment]
What would you suggest I do about the lack of the SHA(X)Cng types? To be specific, they're being used as the `DigestAlgorithm`s for `RSAPKCS1SHA1SignatureDescription` and friends.

It looks like I can create a dummy `Sha(X)Cng) type in Security.Cng and have it wrap around `CngAlgorithm.Sha(X)`. Does that seem reasonable? I would use those properties directly, but CngAlgorithm doesn't inherit from HashAlgorithm so I cannot.

**Comment by steveharter** [comment]
We shouldn't have to add RSAPKCS1SignatureDescription (not part of ns2.0)

**Comment by ianhays** [comment]
Oh. Well I did way too much for this issue then. I'll pare it down and push a PR shortly.
