### ISSUE TITLE
Port System.Security.Cryptography.HMAC.BlockSizeValue

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#12316]
Default value is 64. Must also ensure any other HMAC-derived classes including
HMACSHA1 (64)
HMACSHA256 (64)
HMACSHA384 (128)
HMACSHA512 (128)

```
protected int BlockSizeValue
{
    get {}
    set {}        
}       
```

Value should flow down to provider, and appropriate tests written for that.

**Comment by bartonjs** [comment]
Aes, DES, RC2, Rijndael, and TripleDES aren't HMAC algorithms...
