### ISSUE TITLE
xUnit console runner should not use locally built assemblies while running

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#12329]
If you change a piece of code to behave incorrectly that the xUnit console runner happens to use, then instead of reporting test failures the console runner might not work correctly. For example, I once messed up `Path.Combine` so that the runner had problems finding the test assembly, so I had to mentally go through the code and see what was wrong.

Another time, I messed up `Buffer.MemoryCopy`, but _only_ for unaligned data, so I had no idea what was wrong when I pasted the code into a console application. I ended up having to put `Console.WriteLine` in the MemoryCopy code (which was complex because WriteLine uses that function) to see what was going on.

It would be nice if the assemblies the test runner runs on are separated from the versions that are being tested, so it's easier to change commonly-used functions.

cc @hughbe

**Comment by jkotas** [comment]
This is what tests in CoreCLR repo are for. The corefx tests assume that the basic runtime is not completely broken - I think it is a reasonable assumption to make.

**Comment by jamesqo** [comment]
@jkotas This also happens when you make changes to stuff in corefx. For example, I was recently changing stuff in Enumerable and I hit [this](https://github.com/dotnet/corefx/pull/12343/files#diff-d8b3be41edbd1e2e3c65380665467a2dL159) assert causing the runner to hang.

**Comment by Clockwork-Muse** [comment]
@jkotas - There's also a couple of oddballs where you can get a class from either the runtime or corefx.
`System.Collections.BitArray`, for example, is pulled from corefx if the runtime is AOT (iirc), otherwise it pulls it from the runtime.

**Comment by jkotas** [comment]
> oddballs where you can get a class from either the runtime or corefx

There are gradually getting cleaning ups, e.g. #12268 is change related to this. I do not think it is root cause for this issue - this issue will still be present even once all of these are cleaned up.
