### ISSUE TITLE
Port additional System.Security.Cryptography.RandomNumberGenerator members

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#12323]
Dependency: CryptoConfig

Add the following members
````
M:RandomNumberGenerator.Create(System.String)
    Requires CryptoConfig
M:RandomNumberGenerator.GetBytes(System.Byte[],System.Int32,System.Int32)
M:RandomNumberGenerator.GetNonZeroBytes(System.Byte[])
    Strips off zeros; does not require native call
````

**Comment by morganbr** [comment]
I believe GetNonZeroBytes was omitted due to concerns about usage being insecure -- if you're asking for cryptographically secure bytes, you shouldn't be skewing their distribution. Is there a compelling reason to re-add it?

**Comment by anurse** [comment]
big +1 for `GetBytes(byte[], int, int)`, without it we have to allocate extra memory to hold the random value :(

**Comment by danmosemsft** [comment]
@morganbr Same reasoning as for much of the other API we're adding -- to be compatible with desktop and Xamarin so libraries can be reused. There are very few exceptions, generally for technologies we don't plan to bring over like remoting. We aren't making judgements about the usefulness or advisability of using an API.

**Comment by steveharter** [comment]
On GetNonZeroBytes - working with Jeremy to ensure we use the 'correct' version of the implementation as there is two ways it is implemented, with one being correct.
