### ISSUE TITLE
Consider removing netcore50 from the list of TFMs actively targeted by the System.Net.Sockets build

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#12331]
See discussion here: https://github.com/dotnet/corefx/pull/12249#pullrequestreview-2423298

Should we remove the netcore50 build of System.Net.Sockets?  Should we wait until we're building for "UAP10.1," whatever/whenever that is?

**Comment by CIPop** [comment]
In UWP System.Net.Sockets we have a few #ifdefs to avoid build issues with an older Stream dependency.
This item is tracking the work required to take dependency on the new System.IO contract and remove the #ifdef build hacks.

**Comment by caesar1995** [comment]
I think this issue has been solved by #16704. @davidsh @CIPop could you please confirm?

**Comment by davidsh** [comment]
>I think this issue has been solved 

Yes, this issue can be closed now.
