### ISSUE TITLE
Assembly.CreateInstance undocumented

### ISSUE THREAD

**Issue by breyed** [dotnet/corefx#12341]
In .NET 4.5, `Assembly.CreateInstance` returned null if the the type could not be found. Is this still true or is an exception thrown instead? Given how many changes to reflection are part of .NET Core, there's no way to know other than trial or error or looking through the source code. Both of these options do poorly for productivity. The lack of such basic information in the XML comments that drive the IntelliSense and F12 metadata is a major omission. More concerning is the release process that allowed .NET Core to be labeled as version 1.0 fully stable, production ready, without essential documentation. A systematic review and backfilling of missing documentation would save a world of developers untold time and be well worth the effort.

**Comment by karelz** [comment]
I see [proper documentation](https://docs.microsoft.com/en-us/dotnet/core/api/system.reflection.assembly#System_Reflection_Assembly_CreateInstance_System_String_) for .NET Core, explicitly calling out null if type could not be found.
Why do you think it is missing?

**Comment by breyed** [comment]
Oooh, that is nice documentation. :-) Perhaps it's just a tooling issue. That documentation doesn't show up in Visual Studio. In VS2015, IntelliSense shows nothing. Here's what shows up if you choose "Go To Definition" on `CreateInstsance`:

````C#
#region Assembly System.Reflection, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// C:\Users\username\.nuget\packages\System.Reflection\4.1.0\ref\netstandard1.5\System.Reflection.dll
#endregion

    ...

		public static string CreateQualifiedName(string assemblyName, string typeName);
		public static Assembly GetEntryAssembly();
		//
		// Summary:
		//     Loads an assembly given its System.Reflection.AssemblyName.
		//
		// Parameters:
		//   assemblyRef:
		//     The object that describes the assembly to be loaded.
		//
		// Returns:
		//     The loaded assembly.
		//
		// Exceptions:
		//   T:System.ArgumentNullException:
		//     assemblyRef is null.
		//
		//   T:System.IO.FileNotFoundException:
		//     assemblyRef is not found.
		//
		//   T:System.IO.FileLoadException:
		//     In the .NET for Windows Store apps or the Portable Class Library, catch the base
		//     class exception, System.IO.IOException, instead.A file that was found could not
		//     be loaded.
		//
		//   T:System.BadImageFormatException:
		//     assemblyRef is not a valid assembly. -or-Version 2.0 or later of the common language
		//     runtime is currently loaded and assemblyRef was compiled with a later version.
		public static Assembly Load(AssemblyName assemblyRef);
		public object CreateInstance(string typeName);
		public object CreateInstance(string typeName, bool ignoreCase);
````

Notice how `Load` has documentation, but other methods like `GetEntryAssembly` and `CreateInstance` have nothing. This is what led me to believe there was no documentation for many of those methods.

**Comment by karelz** [comment]
@terrajobst do you if .NET Core docs are supposed to show up in VS IntelliSense?
Also I wonder why the "Go To definition" comments are different from the [docs](https://docs.microsoft.com/en-us/dotnet/core/api/system.reflection.assembly#System_Reflection_Assembly_CreateInstance_System_String_) -- @weshaggard ?

**Comment by hughbe** [comment]
@karelz there may already be some, but any plans to let us contribute to the docs? Via GitHub perhaps?

**Comment by karelz** [comment]
Good question -- @terrajobst @weshaggard would that be technically possible?

**Comment by terrajobst** [comment]
@ericstj @weshaggard are we still including IntelliSense .xml files with our packages?

**Comment by ericstj** [comment]
Yeah, but I believe we're just picking up a snapshot from TFS.

**Comment by karelz** [comment]
Would it make sense to pick up the live .xml files from build?

**Comment by ericstj** [comment]
We do for brand-new libraries that were never in desktop, but right now the live docs in source are much smaller than the authored docs (from TFS).  The authored docs have all the existing info from the types in desktop and include localization.  For most of our types where we are just exposing stuff from desktop its probably the right thing to do to pull from existing docs.  There's likely some additional work that needs to be done to make this more dynamic, but we should definitely not throw out the existing docs.

**Comment by karelz** [comment]
I see. Unfortunately if we pick only the old docs, we won't be able to improve them (at least not in the open).
It would be great to have the ability to pick specific docs from live build -- the process would be: Migrate docs from old system + consume them from CoreFX live build + improve them in CoreFX.
Would that be technically possible? (e.g. would we lose the ability to localize docs)

cc: @mairaw @danmosemsft

**Comment by mairaw** [comment]
Yes, something like that is in the works @karelz, it's just that is not on CoreFX. We've tried the solution to import the current docs as /// comments to CoreFX in the past, but unfortunately we wouldn't be able to change all source files, especially legacy code and mscorlib, so we ended up trying to find new alternatives. So, what we'll do is to migrate the docs from the old system to http://github.com/dotnet/core-docs using a new format, they'll be open source, we'll be able to generate new IntelliSense files from that similar to the way we do for the Framework today and Loc team will be able to localize that content. Other teams however, like ASP.NET Core, will be able to generate their API docs completely from source because they don't have the same complications as .NET does.

**Comment by mairaw** [comment]
@ericstj you mentioned localization before. So, do we ship localized IntelliSense files with our packages? I'm not sure how this works for .NET Core and NuGet packages.

Also, if you guys can send me an email with the location of the files currently being used, I could try to compare with what we're using to generate the docs site. Perhaps we could update some of the files with the latest content?

/cc @nobuko

**Comment by ericstj** [comment]
Yes, to localized IntelliSense.  They are in culture-specific subfolders next to the reference assemblies inside the packages.

You can see the full set inside this package:
https://dotnet.myget.org/F/dotnet-core/api/v2/package/Microsoft.Private.Intellisense/1.0.0-rc4-24220-00

Download it and rename to zip to get all the XML.  /cc @weshaggard
