### ISSUE TITLE
Consider to add two new Public API in System.IO.BufferedStream

### ISSUE THREAD

**Issue by luqunl** [dotnet/corefx#12356]
public Stream UnderlyingStream { 
         [Pure] 
         get { return _stream; } 
} 
 
public Int32 BufferSize { 
         [Pure] 
         get { return _bufferSize; } 
 } 

In System.Runtime.WindowsRuntime, it need to access these two properties/fields.
 For Desktop/CoreCLR, these two properties in BufferedStream are internal but they have FriendAccessAllowed Attribute.
 For CoreRT, the wrapper in System.Runtime.WindowsRuntime\src\System\IO\BufferedStreamWrapper.cs is to wrapper a BufferedStream and expose these two properties.

If System.IO.BufferedStream can expose these two properties publically, it is easy for System.Runtime.WindowsRuntime to access these properties.

**Comment by karelz** [comment]
@JeremyKuhne, @ianhays  can you please check with @jkotas and @luqunl about the API and if it is ready for review?

**Comment by ianhays** [comment]
These seem fine.  It's not the first time I've seen a request to publicize _bufferSize.

 As @weshaggard said, these will need to be netcoreapp specific.

**Comment by weshaggard** [comment]
It is fine to expose these a public.

**Comment by jkotas** [comment]
I will take care of adding these.
