### ISSUE TITLE
HttpContentMultipartExtensions in .NET Core

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/corefx#12352]
The [`HttpContentMultipartExtensions`](https://msdn.microsoft.com/en-us/library/hh835439%28v=vs.108%29.aspx) were available in .NET Framework to parse multipart http responses. Is there anything similar available in .NET Core or plans to bring them to .NET Standard?

**Comment by davidsh** [comment]
Those extensions are not part of the .NET Framework itself.  Rather, they are a downloadable package authored in part by the ASP.NET team.

@danroth27 Can you comment on this?  Are the "HttpContentMultipartExtensions" library still available and will it work with .NET Core?

**Comment by danroth27** [comment]
@Eilon We do plan to release an update to the [Microsoft.AspNet.WebApi.Client](https://www.nuget.org/packages/microsoft.aspnet.webapi.client) package to support .NET Core. We just haven't gotten to it yet.

**Comment by davidsh** [comment]
closing issue since question has been answered.

**Comment by AKlaus** [comment]
@twsouthwick, there seems to be a workaround to use Microsoft.AspNet.WebApi.Client in .NET Core - https://stackoverflow.com/a/45048960/968003

**Comment by maracuja-juice** [comment]
@danroth27 Has this been done yet?

**Comment by danroth27** [comment]
@maracuja-juice Yes, you can get the updated package on nuget.

**Comment by niklasholm** [comment]
That is excellent @danroth27 but how is this [not mentioned in the documentation](https://docs.microsoft.com/en-us/dotnet/api/index?term=HttpContentMultipartExtensions)? I searched forever before finding this. It's much more convenient than [MultipartReader](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.webutilities.multipartreader?view=aspnetcore-2.2).

**Comment by danroth27** [comment]
@niklasholm It ships in a a standalone package, so it doesn't currently show up in the API explorer. 

@rrelyea It sure would be nice if there was a way to easily search for APIs on NuGet!
