### ISSUE TITLE
Port System.Security.Cryptography.HMACSHA384/512.ProduceLegacyHmacValues

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#12364]
This enables a .NET 2.0 (pre-SP1) bug compatibility mode. Since we no longer have a managed implementation of HMAC we can't make this work in core so we will throw PNSE

System.Security.Cryptography.HMACSHA384.ProduceLegacyHmacValues
System.Security.Cryptography.HMACSHA512.ProduceLegacyHmacValues

**Comment by danmosemsft** [comment]
Taking this as it's quick.
