### ISSUE TITLE
Remove if-defs from System.ComponentModel.TypeCoverter

### ISSUE THREAD

**Issue by AlexGhiondea** [dotnet/corefx#12386]
When originally porting the TC code a lot of it was if-def-ed out because not all of the types required were available.

Since we have brought back more APIs, we can go ahead and bring back that code as well.

Look for: 
- [x]  FEATURE_INSTANCEDESCRIPTOR
- [x]  FEATURE_EDITORATTRIBUTE
- [x]  FEATURE_GETMETHOD_WITHTYPES
- [x]  FEATURE_ICOMPONENTCHANGESERVICE
- [x]  FEATURE_CHECKOUTEXCEPTION
- [x]  FEATURE_AMBIENTVALUE
- [x]  FEATURE_COMPONENT_CHANGE_SERVICE
- [x]  FEATURE_PROPERTY_CHANGED_EVENT_HANDLER 
- [x]  FEATURE_EDITOR
- [x]  FEATURE_EDITORATTRIBUTE
- [x]  FEATURE_NESTED_SITE
- [x]  FEATURE_MEMBERINFO_REFLECTEDTYPE

Note: not all of those can actually be brought back.

**Comment by Petermarcu** [comment]
Adding to 1.2 since its tagged with netstandard2.0. If not for netstandard 2.0, it can go back to no milestone.
