### ISSUE TITLE
The type name used in System.Runtime.WindowsRuntime.dll doesn't meet the corefx coding style

### ISSUE THREAD

**Issue by luqunl** [dotnet/corefx#12384]
The corefx coding style is to use language keywords instead of BCL types, so  Int32 ,  Int64 ,  Byte ,  String , etc. should be  int ,  long ,  byte ,  string , etc.

see src\System.Runtime.WindowsRuntime\src\System\IO\NetFxToWinRtStreamAdapter.cs,
src\System.Runtime.WindowsRuntime\src\System\IO\WindowsRuntimeStorageExtensions.cs,
src\System.Runtime.WindowsRuntime\src\System\IO\WindowsRuntimeStreamExtensions.cs,
src\System.Runtime.WindowsRuntime\src\System\IO\WinRtIOHelper.cs

**Comment by AlexGhiondea** [comment]
This seems like a straight forward change -- replace all the framework types in the files listed above with their C# language equivalents.

**Comment by sboulema** [comment]
Just before I wanted to submit my first corefx PR, I noticed this issue goes against the contributing guidelines:

> DO NOT send PRs for style changes. For example, do not send PRs that are focused on changing usage of Int32 to int. 
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/contributing.md

Code changes for this issue are here: https://github.com/sboulema/corefx/commit/9a743d8a9af90abd6a200c9bb7d0e75199c68eed

**Comment by stephentoub** [comment]
This was done across all of coreclr and corefx awhile back.
