### ISSUE TITLE
ConsoleKeyInfo.GetHashCode generates identical hashes for common keys

### ISSUE THREAD

**Issue by lzybkr** [dotnet/corefx#12380]
`ConsoleKeyInfo.GetHashCode` does not use the `_key` field when computing the hash.

It is common for `_keyChar` to have identical values for different keys - some notable examples: `F1`-`F12` and many `Ctrl+<non-letter>` sequences all generate `0` for `KeyChar`.

**Comment by stephentoub** [comment]
This would be a trivial change. @weshaggard, do we have any compatibility concerns around changing the algorithm in GetHashCode?  I assume the answer is no, as we've taken PRs that do it elsewhere.

**Comment by weshaggard** [comment]
I think updating this is reasonable and shouldn't be much of a compat issue.
