### ISSUE TITLE
Directory.Move doesn't throw for existing on Unix

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#12396]
Discovered while testing for IsolatedStorage. Move should throw an exception if there is a file/directory in the specified destination.

**Comment by stephentoub** [comment]
We have tests for this which run and pass on Unix, e.g.
https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/tests/Directory/Move.cs#L44-L49
How is what these tests are doing differ from the scenario you're hitting?
cc: @ianhays

**Comment by Petermarcu** [comment]
@JeremyKuhne , this is probably more interesting for 1.2 at this point unless its a regression from 1.0.

**Comment by karelz** [comment]
@JeremyKuhne is it a regression against 1.0? If not, please change the milestone to Future/1.2.

**Comment by JeremyKuhne** [comment]
@stephentoub That test copies onto itself, which there is a specific code path for. The failure is copying over another existing directory.

I'll move it to 1.2 as we shipped this way in 1.0.

**Comment by vcsjones** [comment]
I took a look at this, I think there is a little more nuance to it.

In Ubuntu 16.04-x64, an `IOException` is thrown if the directories are not empty. For example, this will throw:

```
Directory.CreateDirectory("a");
Directory.CreateDirectory("b");
File.WriteAllText("a/hi.txt", "a/hi.txt");
File.WriteAllText("b/bye.txt", "b/bye.txt");
Directory.Move("a", "b");
```

If the b\ path is empty (the destination), then an exception is not thrown. This behavior is also consistent with Mac.

Windows is different. Windows will throw even if "a" and "b" are empty.

**Comment by vcsjones** [comment]
Same problem as #2460 but for directories.
