### ISSUE TITLE
[Expose] To Add ISafeSerializationData/SafeSerializationEventArgs 

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#12408]
The following APIs exist in NetStandard 2.0 but are missing from NetCore. We should put them in System.Runtime where Exception lives.

T:System.Runtime.Serialization.ISafeSerializationData
T:System.Runtime.Serialization.SafeSerializationEventArgs

**Comment by zhenlan** [comment]
Hi @stephentoub, you ported most other serialization APIs that were in mscorlib on full .NET. You probably have better context where they should land in .NET Core. Would you mind to take this one as well? Thanks!

**Comment by stephentoub** [comment]
Seems like they have to be exposed from System.Runtime, as Exception.SerializeObjectState references the SafeSerializationEventArgs type, and SafeSerializationEventArgs exposes the AddSerializedState method that accepts an ISafeSerializationData, which means both of these types need to be reachable from Exception, which is in System.Runtime.  This is assuming we plan to expose that SerializeObjectState event, which it looks like we do: https://github.com/dotnet/standard/blob/master/netstandard/ref/mscorlib.cs#L2009
cc: @weshaggard

**Comment by weshaggard** [comment]
@ramarag is actually working on exposing these in S.Private.CoreLib already.

**Comment by zhenlan** [comment]
Cool. Should this be assigned to @ramarag? Will this be done by end of next month (including tests)?
cc: @danmosemsft

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/issues/12405 covers SeralizeObjectState and it's assigned to @ramarag 
@weshaggard you mention 'these' but I'm not sure what other relevant API he's exposing?

@zhenlan you guys own these types so it probably makes sense for you to add them but if you don't have cycles you can leave it unassigned and someone else will grab it...

**Comment by weshaggard** [comment]
>@weshaggard you mention 'these' but I'm not sure what other relevant API he's exposing?

I've seen a code review about adding Exception.SerializeObjectState but I didn't dig deeply to see if it included this full closure of types. I do think they would all need to be where Exception lives though so if @ramarag isn't doing them he should probably pick up the remainder.

**Comment by AlexGhiondea** [comment]
@weshaggard that was my PR that I had opened. 
However, it required changes to the CoreCLR that @ramarag was already working on so I close mine until the other PR is ready. 
@ramarag can you confirm your changes also cover these types?

**Comment by ramarag** [comment]
Yes i am working on this. My first change has already made to corefx [https://github.com/dotnet/coreclr/commit/bc382fd9ef27b9d200045cc030cf09b7bf547173]. But i was under wrong impression of coolness of bclrewriter tool. [ The tool created an empty ISafeSerializationData interface].

I have the fix for ISafeSerializationData in PR at https://github.com/dotnet/coreclr/pull/7754/commits/0bd8f2a02da9092919592231c5bb170f72181864
