### ISSUE TITLE
MemoryMappedFile test failures on Win 7

### ISSUE THREAD

**Issue by eatdrinksleepcode** [dotnet/corefx#1240]
#1179 (92ebda3212c05c1f8b972c84be5012d581938311) introduced a failure in all three MemoryMappedFile test projects on Windows 7:

> ERROR, Loc111: Unexpected exception, System.EntryPointNotFoundException: Unable to find an entry point named 'CreateFileMappingW' in DLL 'api-ms-win-core-memory-l1-1-1.dll'.
   at Interop.mincore.CreateFileMapping(IntPtr hFile, SECURITY_ATTRIBUTES& lpFileMappingAttributes, Int32 flProtect, Int32 dwMaximumSizeHigh, Int32 dwMaximumSizeLow, String lpName)

**Comment by eatdrinksleepcode** [comment]
The target DLL for this entry point was changed from "api-ms-win-core-memory-l1-1-0.dll" to "api-ms-win-core-memory-l1-1-1.dll". The latter is only present in Windows 8.

**Comment by Maxwe11** [comment]
Seems fixed by #1246

**Comment by pallavit** [comment]
As @Maxwe11 pointed out this should be fixed now. Please sync to the latest changes and let me know if you still see any issues.
