### ISSUE TITLE
Package Microsoft.AspNetCore.StaticFiles 1.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0)

### ISSUE THREAD

**Issue by ashwinkambli** [dotnet/corefx#12402]
I have VS 2015 Professional installed on my box. I have Core 1.0.1 SDK 1.0.0 Preview 2-003131 (x64) and the Core 1.0.1 - VS 2015 Tooling Preview 2 installed as well:
![image](https://cloud.githubusercontent.com/assets/20649904/19134205/739f1b48-8b11-11e6-9e22-7b975b4eedeb.png)

Here is my project.json file: 
{
  "dependencies": {
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.EntityFrameworkCore.InMemory": "1.0.1",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.AspNetCore.WebSockets.Server": "0.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Chutzpah": "4.2.4",
    "Microsoft.NETCore.App": "1.0.1"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": "portable-net45+win8+dnxcore50"
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config",
      "project.json"
    ],
    "exclude": [
      "wwwroot/app/*_/_.spec.*",
      "wwwroot/chutzpah.json",
      "wwwroot/testSetup.js"
    ]
  },

  "scripts": {
    "prepublish": "npm install",
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}

But, everytime I load the solution, or "Restore Packages" I always end up with this error: 
`Errors in D:\Angular 2\Ng2Demo\Ng2Demo.xproj
    Package Microsoft.AspNetCore.StaticFiles 1.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.AspNetCore.StaticFiles 1.0.0 supports:
      - net451 (.NETFramework,Version=v4.5.1)
      - netstandard1.3 (.NETStandard,Version=v1.3)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.`

**Comment by karelz** [comment]
@ericstj can you please comment/route it?

**Comment by ericstj** [comment]
That should be supported.  This statement looks erroneous:
`is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.AspNetCore.StaticFiles 1.0.0 supports: - net451 (.NETFramework,Version=v4.5.1) - netstandard1.3 (.NETStandard,Version=v1.3)`
netstandard1.3 is compatible with netcoreapp1.0.  /cc @emgarten 

Can you check what version of the NuGet extension is installed with Visual Studio?  This should appear in the help -> about menu.

The appropriate repo for this issue would likely be either https://github.com/aspnet/home if the package has an issue or https://github.com/nuget/home if the problem is with nuget.

**Comment by ashwinkambli** [comment]
I had NuGet Package Manager 3.5.0 earlier. I re-installed that package, and now my NuGet Package manager is 3.4.4 (I don't understand how it went back one full minor version): 

![image](https://cloud.githubusercontent.com/assets/20649904/19165961/b2ab69e6-8bba-11e6-9d87-fa27f42687db.png)

But, that still did not resolve the issue.

**Comment by Petermarcu** [comment]
@Eilon @emgarten , should we move this issue to where the package lives or do you want to track as a NuGet issue?

**Comment by Eilon** [comment]
@Petermarcu I don't think this is a problem with the package, is it?

**Comment by ericstj** [comment]
I think its a NuGet issue.  NuGet is giving a bogus error.  It appears to have read the correct info from the package, but it isn't honoring the compatibility mappings between netcoreapp1.0 > netstandard1.6 ( including netstandard1.3). /cc @robrelea

**Comment by Eilon** [comment]
@ericstj it's @rrelyea 😄

**Comment by emgarten** [comment]
This does look like a NuGet issue, the package framework should be compatible here. It looks like there may be other issues causing it to fail the compatibility check.

**Comment by ashwinkambli** [comment]
I am glad that his has been narrowed down to NuGet. But, like I mentioned earlier, re-installing the NuGet package (to 3.4.4) did not resolve this issue. Is there anything I can do to help troubleshoot?

**Comment by ericstj** [comment]
@ashwinkambli if you're still experiencing this issue on the latest NuGet can you open the issue in https://github.com/nuget/home?
