### ISSUE TITLE
SslStream segfault when X509Certificate2 constructed

### ISSUE THREAD

**Issue by halter73** [dotnet/corefx#12412]
The following program segfaults (apparently in SslStream.AuthenticateAsClientAsync), but only if the first line `new X509Certificate2("testCert.pfx", "testPassword");` is present. Feel free to to copy testCert.pfx from https://github.com/aspnet/KestrelHttpServer/tree/dev/samples/SampleApp.

This repros on windows with Microsoft.NETCore.App 1.1.0-preview1-001090-00, but not 1.0.1.

    > dotnet run
    Project ConsoleApp2 (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
    HttpClient request succeeded!
    Starting AuthenticateAsClientAsync.
    > $lastexitcode
    -1073741819

![image](https://cloud.githubusercontent.com/assets/54385/19137402/5625a0e8-8b28-11e6-92f1-fa1d24b9cc42.png)

### NuGet.config

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <packageSources>
        <add key="AspNetCore" value="https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json" />
        <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
      </packageSources>
    </configuration>

### project.json

    {
      "version": "1.0.0-*",
      "buildOptions": {
        "emitEntryPoint": true
      },

      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0-preview1-001090-00"
        }
      },

      "frameworks": {
        "netcoreapp1.0": {
          "imports": "dnxcore50"
        }
      }
    }

### Program.cs
```c#
using System;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Net.Security;
using System.Net.Sockets;
using System.Security.Authentication;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;

namespace ConsoleApp2
{
    public class Program
    {
        public static void Main(string[] args)
        {
            new X509Certificate2("testCert.pfx", "testPassword");

            using (var client = new HttpClient())
            {
                client.GetStringAsync("https://github.com").Wait();
                Console.WriteLine("HttpClient request succeeded!");
            }

            GetStreamAsync(new Uri("https://github.com"), validateCertificate: true).Wait();
            Console.WriteLine("Getting SslStream succeeded!");
        }

        private static async Task<Stream> GetStreamAsync(Uri requestUri, bool validateCertificate)
        {
            var socket = await GetSocketAsync(requestUri);
            Stream stream = new NetworkStream(socket, ownsSocket: true);

            if (requestUri.Scheme.Equals("https", StringComparison.OrdinalIgnoreCase))
            {
                var sslStream = new SslStream(stream, leaveInnerStreamOpen: false, userCertificateValidationCallback:
                    validateCertificate ? null : (RemoteCertificateValidationCallback)((a, b, c, d) => true));
                Console.WriteLine("Starting AuthenticateAsClientAsync.");
                try
                {
                    await sslStream.AuthenticateAsClientAsync(requestUri.Host, clientCertificates: null,
                        enabledSslProtocols: SslProtocols.Tls11 | SslProtocols.Tls12,
                        checkCertificateRevocation: validateCertificate);
                }
                finally
                {
                    Console.WriteLine("AuthenticateAsClientAsync Completed.");
                }

                return sslStream;
            }
            else
            {
                return stream;
            }
        }

        private static async Task<Socket> GetSocketAsync(Uri requestUri)
        {
            var tcs = new TaskCompletionSource<Socket>();

            var socketArgs = new SocketAsyncEventArgs();
            socketArgs.RemoteEndPoint = new DnsEndPoint(requestUri.DnsSafeHost, requestUri.Port);
            socketArgs.Completed += (s, e) => tcs.TrySetResult(e.ConnectSocket);

            // Must use static ConnectAsync(), since instance Connect() does not support DNS names on OSX/Linux.
            if (Socket.ConnectAsync(SocketType.Stream, ProtocolType.Tcp, socketArgs))
            {
                await tcs.Task;
            }

            var socket = socketArgs.ConnectSocket;

            if (socket == null)
            {
                throw new SocketException((int)socketArgs.SocketError);
            }
            else
            {
                return socket;
            }
        }
    }
}
```

**Comment by davidsh** [comment]
What operating system is this happening on?  Windows? Linux?

**Comment by stephentoub** [comment]
> What operating system is this happening on? Windows? Linux?

> This repros on windows with Microsoft.NETCore.App 1.1.0-preview1-001090-00, but not 1.0.1

**Comment by davidsh** [comment]
@bartonjs you may want to look at this first since the trigger for this is `X509Certificate2` object.  And looking at this repro code, I don't see how this object is even used anywhere in the repro code.  So, that tells me that it is likely a finalizer issue with `x509Certificate2` object.

**Comment by halter73** [comment]
This repros on Windows 10 and Win Server 2012 at least. Not on debian 8.2.

I don't think the issue is with `x509Certificate2` specifically. If you replace `GetStreamAsync(new Uri("https://github.com"), validateCertificate: true).Wait();` with `GC.Collect(); GC.WaitForPendingFinalizers();`, you won't see the segfault.

**Comment by pranavkm** [comment]
Slightly related, on Ubuntu 14.04 and OSX, the CI test run fails with this:

```
System.TypeInitializationException : The type initializer for 'Crypto' threw an exception.
---- System.TypeInitializationException : The type initializer for 'CryptoInitializer' threw an exception.
-------- System.DllNotFoundException : Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.Crypto.BioNewFile(String filename, String mode)
   at Internal.Cryptography.Pal.CertificatePal.FromFile(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at Microsoft.AspNetCore.Hosting.KestrelServerOptionsHttpsExtensions.UseHttps(KestrelServerOptions options, String fileName, String password)
   at Microsoft.Extensions.Options.OptionsCache`1.CreateOptions()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer..ctor(IOptions`1 options, IApplicationLifetime applicationLifetime, ILoggerFactory loggerFactory)
```

**Comment by muratg** [comment]
:eyes:

**Comment by gkhanna79** [comment]
@bartonjs PTAL at this 1.1.0 Preview blocking issue.

CC @leecow

**Comment by stephentoub** [comment]
Reassigning to @JohnChen0, as it looks like this may be a crossgen issue.

**Comment by halter73** [comment]
@pranavkm I think the `System.DllNotFoundException : Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl'` you're seeing on mac and linux is unrelated to the AV. It appears to be caused by a mismatch between NETStandard.Library 1.6.1-* and Microsoft.NETCore.App 1.0.0-* that currently exists in the Kestrel repo.

We'll update the Kestrel repo to depend on Microsoft.NETCore.App 1.1.0-* once the AV is fixed on windows.

**Comment by stephentoub** [comment]
As an aside, a workaround is to avoid using the crossgen'd binaries, e.g. in the project.json removing the ```"type": "platform"``` and adding the relevant runtimes:
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },
 
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.1.0-preview1-001090-00"
    }
  },
 
  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  },
 
  "runtimes": {
    "win10-x64": {}
  } 
}
```

**Comment by JohnChen0** [comment]
The issue is in the handing of generic dictionary overflow inside Ready-to-Run images. The code sometime mistake a Ready-to-Run signature blob for a regular signature blob. Since these two types of signature blobs have different formats, this can cause problems. I'm looking for a way to fix it.

**Comment by gkhanna79** [comment]
@JohnChen0 When did this regress?

CC @jkotas

**Comment by JohnChen0** [comment]
The code triggering the crash existed in 1.0 RTM, though I haven't confirmed if I can get the same crash in 1.0. We now include more generic types in R2R images, and can potentially make this crash more likely.

As a quick workaround, setting the following environment variable should prevent this particular crash: `set COMPlus_ReadyToRunExcludeList=System.Security.Cryptography.X509Certificates`.

**Comment by halter73** [comment]
This issue appears to be resolved in Microsoft.NETCore.App 1.1.0-preview1-001100-00.

**Comment by Porges** [comment]
I'm seeing an access violation in .NET Core 1.1 inside `SslStream.AuthenticateAsClientAsync`. Setting the `COMPlus_ReadyToRunExcludeList` environment variable fixes it. Should I report this as a separate bug?

**Comment by gkhanna79** [comment]
@Porges The general is already fixed (see https://github.com/dotnet/coreclr/issues/8148) and will be part of our 1.1.1 release.

**Comment by Porges** [comment]
@gkhanna79 Thanks 👍
