### ISSUE TITLE
Trying to bind a date to DateTime object in a model

### ISSUE THREAD

**Issue by sero323** [dotnet/corefx#12423]
I am trying to POST a date like this "10/05/2016" (using ajax) to a DateTime object in a model. All the objects are binding except the DateTime objects. As you can see in the screen shot, the string value is coming through but the DateTime object is showing 01/01/0001. I'm running VS Code on my mac with the C# extensions. The crazy thing is that running the same code on Visual Studios on windows binds the DateTime objects correctly. Any suggestions?
![debug_output](https://cloud.githubusercontent.com/assets/22666128/19165893/6ef77118-8bba-11e6-9af1-ba8ef16f6e66.png)

Here's the excerpt of the web api POST method.
```c#
[HttpPost]
public IActionResult Post([FromBody] SomeModel model)
{...}
```

**Comment by svick** [comment]
First, I think this question does not belong here. ASP.NET MVC model binding is implemented in [aspnet/Mvc](https://github.com/aspnet/Mvc), so that would be the best place to ask.

Now, as far as I can tell, model binding for `DateTime`, uses `DateTimeConverter`, which uses `DateTime.Parse()` with culture settings. Because those settings can vary, I think the right way is to use the culture-neutral ISO date format, e.g. `2016-10-05`, which I think should work everywhere.

**Comment by sero323** [comment]
I have tried the `yyyy-MM-dd` format and even changed the date to the iso format date using `.toISOString()` which produces something like `2016-10-06T20:04:56.035Z`. I have also added the culture settings to Startup.cs like so...
```c#
public void ConfigureServices(IServiceCollection services)
        {                
            services.Configure<RequestLocalizationOptions>(
                options =>
                    {
                        var supportedCultures = new List<CultureInfo>
                        {
                            new CultureInfo("en-US"),
                        };
 
                        options.DefaultRequestCulture = new RequestCulture(culture: "en-US", uiCulture: "en-US");
                        options.SupportedCultures = supportedCultures;
                        options.SupportedUICultures = supportedCultures;
                    });
            ....
        }
```

**Comment by sero323** [comment]
Found the solution...for some reason when I declare my DateTime object in the model, it won't bind if I user DateTime?, I also tried Nullable<DateTime> and that didn't work either. but a plain DateTime object works. Interesting...
