### ISSUE TITLE
S.R.CS.Unsafe: Add IntPtr overloads to Add/Subtract or AddByteOffset/SubstractByteOffset for refs

### ISSUE THREAD

**Issue by nietras** [dotnet/corefx#12445]
As discussed in https://github.com/dotnet/corefxlab/pull/796 we need to have overloads for adding/subtracting `IntPtr` from refs. A couple of different API proposals were discussed.

**A**: Add overloads with same meaning as before i.e. `elementOffset`
```csharp
static ref T Add<T>(ref T source, IntPtr elementOffset);
static ref T Subtract<T>(ref T source, IntPtr elementOffset);
```

**B**: Add overloads with different meaning as before i.e. `byteOffset` since we using `IntPtr`
```csharp
static ref T Add<T>(ref T source, IntPtr byteOffset);
static ref T Subtract<T>(ref T source, IntPtr byteOffset);
```

**C**: Add new methods with `ByteOffset` suffix
```csharp
static ref T AddByteOffset<T>(ref T source, IntPtr byteOffset);
static ref T SubtractByteOffset<T>(ref T source, IntPtr byteOffset);
```

I am in favor of **A** since it follows current syntax and it is least confusing. If you want to do byte offset on some ref you then need to call `AsRef` first.

If we can decide on the new API I will try to add it after https://github.com/dotnet/corefx/pull/12443 has been approved/merged if it is deemed ok.

@jkotas @davidfowl @KrzysztofCwalina @benaadams @jamesqo @omariom

**Comment by jkotas** [comment]
What about doing both A and C?

**Comment by nietras** [comment]
> both A and C?

I can live with that, but **C** does not add any new functionality, it would just be for convenience, that is to reduce typing for the users of the API, so in other words it could be viewed as superfluous.

**Comment by jkotas** [comment]
I think the redundancy is justifiable in this case. It makes significant difference in readability in the situation I needed it for:

```
ref T p2 = ref Unsafe.AddByteOffset(ref p, byteOffset);
vs.
ref T p2 = ref Unsafe.As<byte, T>(ref Unsafe.Add(ref Unsafe.As<T, byte>(ref p), byteOffset));
```

And AddByteOffset makes the JIT work much less: inlining one method vs. inlining 3 methods and getting rid of extra multiplication. It probably works in simple cases, but there are cliffs where the optimizations would not kick in as expected for sure.

**Comment by nietras** [comment]
> inlining one method vs. inlining 3 methods and getting rid of extra multiplication

I agree, `Subtract` is also superfluous viewed in the same light, so I am fine with adding both 👍.

Another question then, would there be any reason for adding support for `UIntPtr` also?

**Comment by jkotas** [comment]
> support for `UIntPtr` also

If it makes a difference for the kind of code that you are writing using Unsafe, I would not be opposed to it.

**Comment by nietras** [comment]
No not really, more wondering if would be easier to add them while I was adding the others, anyway made a pull request.
