### ISSUE TITLE
Add QueueUserWorkItem for local threadpool queues

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#12442]
`ThreadPool.QueueUserWorkItem` always queues to the global queue; however it would be good to have the option to be able to queue to the current threadpool thread's local queue when a threadpool thread queues extra work items.
## Rationale and Usage
- Reduced contention on the global queue when many threads are queuing
- Potentially hotter more local data when the queuing work item completes
- Take advantage of threadpool's task stealing
- (i.e. Similar to Task's rational for doing it for child Tasks)
## Proposed API

``` csharp
public static class ThreadPool
{
    // public static void QueueUserWorkItem(WaitCallback callBack, bool preferLocal);
    public static void QueueUserWorkItem(WaitCallback callBack, Object state, bool preferLocal);
}
```
## Details
- Exposing a parameter that threadpool already accepts interally

**Comment by svick** [comment]
So, it would be the same as `TaskFactory.StartNew` with `TaskScheduler.Default`, except without the overhead of allocating a `Task`?

Also, the existing overloads of `QueueUserWorkItem` do return `bool`, but it's useless (because it will never return `false`). So maybe favor simplicity over consistency here and make the return type `void`?

**Comment by benaadams** [comment]
What a very strange return value
> true if the method is successfully queued; NotSupportedException is thrown if the work item could not be queued.

**Comment by svick** [comment]
@benaadams That looks like some kind of historical artifact.

[.Net 2.0](https://msdn.microsoft.com/en-us/library/kbf0f1ct(v=vs.80).aspx):

> true if the method is successfully queued; otherwise, false. 

[.Net 3.0](https://msdn.microsoft.com/en-us/library/kbf0f1ct(v=vs.85).aspx):

> true if the method is successfully queued; OutOfMemoryException is thrown if the work item could not be queued. 

[.Net 3.5](https://msdn.microsoft.com/en-us/library/kbf0f1ct(v=vs.90).aspx):

> true if the method is successfully queued; NotSupportedException is thrown if the work item is not queued.

**Comment by benaadams** [comment]
@svick Or more specifically in [`QueueUserWorkItemHelper`](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/ThreadPool.cs#L1659-L1696) call enqnue with the `false` parameter rather than `true`

```
ThreadPoolGlobals.workQueue.Enqueue(tpcallBack, false); 
```
rather than
```
ThreadPoolGlobals.workQueue.Enqueue(tpcallBack, true);
````

**Comment by danmosemsft** [comment]
@kouvel, @alexperovich what remains here to get to API review?

**Comment by karelz** [comment]
API review: We are fine with the API, we just don't like the word `Local` as it leaks implementation.
Can you please brainstorm more options?
We discussed `preferFairness` - unfortunately the default is true, which doesn't align with existing API. Other ideas: optimizeThroughput, optimize, etc.

**Comment by benaadams** [comment]
`preferSameThread`?

**Comment by benaadams** [comment]
`preferSameThread`?

Updated

**Comment by karelz** [comment]
@stephentoub @terrajobst @weshaggard @bartonjs @mellinoe thoughts?
Sounds reasonable to me - saying Local without calling LocalQueue :)

**Comment by bartonjs** [comment]
`preferSameThread` seems reasonable to me, but I'll defer to @stephentoub. (So long as the name makes sense to Steve and `false` is the same as the existing overload, I'm content)

**Comment by stephentoub** [comment]
`preferSameThread` is still potentially tied to this implementation.  For example, imagine in the future we decided not to have one queue per thread but rather one queue per set of threads.  Though I do like `preferSameThread` better than `preferLocal`.

How about `preferAffinity`?  false matches the existing overloads, it's sufficiently vague as to accommodate a variety of implementations, but it still has a reasonable meaning... maybe?

**Comment by benaadams** [comment]
Like it, but may be thought of too specifically as preferring as same core? 

How about `preferSameAffinity` keeps vagueness as "whatever that other thing was"?

**Comment by stephentoub** [comment]
What other thing?  That might be too vague ;)

`preferIsolation` or `preferIsolated`?
`avoidContention`?

Or... maybe I'm being too literal with the original proposal. `preferLocal` might not be referring to the thing we actually call the `local queue`, but rather could just mean "prefer putting this somewhere close to me", like someone shopping for locally-source produce, or "honey, do you want to go on a trip this weekend? nah, let's just stay local."

So... I withdraw my objection to `preferLocal`.

**Comment by benaadams** [comment]
Local numa node 😉

**Comment by benaadams** [comment]
Local numa node 😉 

`preferLocal` rather than `perferLocalQueue` probably works then?

**Comment by stephentoub** [comment]
> preferLocal rather than perferLocalQueue probably works then?

Right, leaving it vague... just generally as "local" as the system can / wants to muster.

**Comment by karelz** [comment]
OK, marking it as approved - given that @stephentoub was raising most of the concerns about naming and he is now fine with the original.
@bartonjs @terrajobst @weshaggard please shout out if you disagree.

**Comment by karelz** [comment]
@benaadams do you plan to grab it? (not pushing, just asking if we need to put more details into "next steps")

**Comment by benaadams** [comment]
@stephentoub reversing this suggesting and following what Task does; would this be better?

```csharp
public static class ThreadPool
{
    public static void QueueUserWorkItem(WaitCallback callBack, bool preferFairness);
    public static void QueueUserWorkItem(WaitCallback callBack, Object state, bool preferFairness);
}
```

**Comment by stephentoub** [comment]
> inverting this suggestion and following what Task does with TaskCreationOptions; would this be better?

The concern with this was that it means the existing overloads effectively have a default value of true for the Boolean argument, and there's a strong preference amongst the API review team for the default value to be false.

**Comment by tmds** [comment]
Interesting proposal.

Does the existing forceGlobal: false find a local thread in case it isn't called from a ThreadPool Thread? Or does it become global in that case?
For the proposed preferLocal, I guess it should try to find a 'local' ThreadPool Thread even when not called from a ThreadPool Thread?
Why is there a preference from the API review team to default preferLocal to false?

**Comment by stephentoub** [comment]
> Does the existing forceGlobal: false find a local thread in case it isn't called from a ThreadPool Thread?

No.

> Or does it become global in that case?

Yes

> For the proposed preferLocal, I guess it should try to find a 'local' ThreadPool Thread even when not called from a ThreadPool Thread?

No. The thread-safety of work-stealing queues depends on the fact that the only thread adding to them is the one that owns them. No other thread can queue or push into one at either end.

> Why is there a preference from the API review team to default preferLocal to false?

The preference is for parameters to have their default value, which is false for a Boolean. @terrajobst or @weshaggard could elaborate on why.

**Comment by tmds** [comment]
I imagined one use case would be numa aware threadpools. Eg going from kestrel libuv thread to a threadpool on the same numa node.

**Comment by stephentoub** [comment]
Were you asking how things work today or how they could work in the future?  Today the thread pool uses work-stealing queues.  If we wanted to support queues with a 1:N relationship with threads, e.g. one queue per NUMA node, that would require a different queue implementation.  And the `preferLocal` naming still works with that possibility in the future.

**Comment by tmds** [comment]
Today and future :)
For a NUMA queue implementation, the name would still be good. For that implementation, perhaps true would be a better default.

**Comment by stephentoub** [comment]
> For that implementation, perhaps true would be a better default.

I don't know what that means. ThreadPool.QueueUserWorkItem(delegate) already means "go to the global queue".  No matter what we do in the future, that won't change.  If you then switch to the overload that takes a Boolean, there is no default, you have to explicitly pick a value to pass.

**Comment by tmds** [comment]
I was thinking for the numa implementation there would be a global, per numa and per thread queue and preferLocal would switch between the global and per numa queue. But there would probably not be a global queue and preferLocal would switch between the per numa and per thread queue. So defaulting to false makes sense indeed.

**Comment by stephentoub** [comment]
> public static void QueueUserWorkItem(WaitCallback callBack, bool preferLocal);

Adding this overload would be a breaking change for an existing call like:
```C#
ThreadPool.QueueUserWorkItem(b => Use((bool)b), true);
```
as previously the `true` would have been passed to the callback, but now `true` will be treated as the `preferLocal` argument and null will be passed to the callback.  Given that and this is an advanced method and it's fine for such methods to have longer overloads, I'm only adding the longer one.

**Comment by benaadams** [comment]
Commented out api that would clash
