### ISSUE TITLE
Remove SNI workaround when we have a new TFS build

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#12450]
https://github.com/dotnet/corefx/pull/12376/commits/c7ba063079560f0a6c1057a62da51a4ef53de629

We should remove this once we get a new TFS build. /cc @stephentoub

**Comment by mellinoe** [comment]
@ericstj Could you update this with more details? The linked commit got wiped out at some point.

**Comment by ericstj** [comment]
This one: https://github.com/dotnet/corefx/pull/12376/commits/8bee74ced4c22992824d671305c228bef94b497e

Though it might be moot.  I think the SNI packages are staying 4.3.0 so long as they are building from TFS.

**Comment by ericstj** [comment]
Currently TFS is frozen at 4.3.0 so this is moot.  I'd expect @saurabh500 to update these references as part of the work to refactor the SNI build.
