### ISSUE TITLE
Expose new apis in AppContext for netcoreapp1.1

### ISSUE THREAD

**Issue by rahku** [dotnet/corefx#12456]
```
    public static event System.UnhandledExceptionEventHandler UnhandledException { add { } remove { } }
    public static event System.EventHandler<System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs> FirstChanceException { add { } remove { } }
    public static event System.EventHandler ProcessExit { add { } remove { } }
    public static void SetData(string name, object data) { }
```

**Comment by rahku** [comment]
Implementation already exists in corelib.

**Comment by rahku** [comment]
Tests are present at https://github.com/rahku/corefx/tree/appContextNewApis

**Comment by karelz** [comment]
@rahku is it part of netstandard2.0 work?

**Comment by weshaggard** [comment]
>@rahku is it part of netstandard2.0 work?

No

The new APIs look good. We will also need to include the handlers `UnhandledExceptionEventHandler` and `FirstChanceExceptionEventArgs` in the same contract as System.AppContext which I believe is currently System.Runtime.

**Comment by AlexRadch** [comment]
@karelz I am working on this PR

**Comment by danmosemsft** [comment]
@weshaggard we have these on AppDomain now, right? So this can be closed?

**Comment by weshaggard** [comment]
Yes these are done.
