### ISSUE TITLE
Add back SocketFlags.MaxIOVectorLength

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#12464]
```csharp
    public enum SocketFlags {
        MaxIOVectorLength = 16,
    }
```

**Comment by alecont** [comment]
uhm... looking at corefx\src\System.Net.Sockets\src\System\Net\Sockets\SocketFlags.cs I see this comment:

        // This is defined in the .NET Framework and isn't being ported to CoreFx
        // since it is Windows specific. However, leave this enum value reserved
        // to prevent future numbering conflicts.
        // MaxIOVectorLength = 0x0010

checking with @davidsh

**Comment by CIPop** [comment]
@alecont This is required for XPlat parity. Given that the API is present in Xamarin (https://developer.xamarin.com/api/field/System.Net.Sockets.SocketFlags.MaxIOVectorLength/) we should add it back here too.

**Comment by geoffkizer** [comment]
This will be removed from netstandard 2.0.

See here: https://github.com/dotnet/standard/issues/82
