### ISSUE TITLE
Exceptions don't properly round trip StackTrace through binary formatter occasionally.

### ISSUE THREAD

**Issue by alexperovich** [dotnet/corefx#12467]
When running tests the MissingSatelliteAssemblyException fails to round trip StackTrace. The original file line number and the round-tripped line number don't match. The System.Resources.ResourceManager tests project has the failing test.

The exception properly round trips when the VS CoreClr debugger is attached.

**Comment by alexperovich** [comment]
This has happened twice more in with completely different exceptions.

SafeArrayRankMismatchException:
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/2084/
InvalidComObjectException:
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/2104/

**Comment by mikem8361** [comment]
Fix by PR https://github.com/dotnet/coreclr/pull/7856

**Comment by stephentoub** [comment]
Several tests are disabled due to this that will need to be turned back on once the fix is pulled in.

**Comment by mikem8361** [comment]
Can you re-enable them, Stephen?

**Comment by stephentoub** [comment]
> Can you re-enable them, Stephen?

Sure, once we pick up a new coreclr that has your fix.
