### ISSUE TITLE
TestNuGetRuntimeId should be derived from TestTFM & machine running on

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#12465]
Currently it looks like we set the TestNuGetRuntimeId in a bunch of different places for different reasons, none of which really make sense.

The purpose of a RuntimeID is to describe the platform that an application is running on.   For many target frameworks they've only been designed to accept a finite set of RIDs.

I think the right model for this would be, given a TestTFM, select from the available RIDs which one best matches the current machine.

/cc @weshaggard @karajas @mellinoe

**Comment by tarekgh** [comment]
@ericstj I am closing this as I don't think it is valid anymore. please reopen if you think otherwise.
