### ISSUE TITLE
Add back Socket.SetIPProtectionLevel and UdpClient.AllowNatTraversal

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#12462]
```csharp
    public class Socket : IDisposable {
        public void SetIPProtectionLevel(IPProtectionLevel level);
    }
    public class UdpClient : IDisposable {
        public void AllowNatTraversal(bool allowed);
    }
```

(Was tracked by #11788)

**Comment by geoffkizer** [comment]
These map to a Windows-specific socket option.

Interestingly, we seem to allow you to try to set this option via SetSocketOption on non-Windows platforms.  Presumably it fails, however (or at least doesn't do what you want it to).

@stephentoub How should we handle this?  We can make them no-ops on non-Windows platforms, or we can make them throw.  I do think it's odd that we let you set the socket option regardless.

**Comment by geoffkizer** [comment]
cc @davidsh @cipop @ericeil

**Comment by stephentoub** [comment]
> How should we handle this?

If the options are actually supposed to do something, and the behavior is meaningful and observable, and we can't achieve it on Unix, we should throw on Unix.

**Comment by geoffkizer** [comment]
There's also a TcpListener.AllowNatTraversal that I assume we want also.
