### ISSUE TITLE
Detect a better default for TestNugetRuntimeId when not set

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#12461]
The logic [here](https://github.com/dotnet/corefx/blob/71de1aac5cf3e5dc87714ae0cc829e1fa98f7c5d/dir.props#L267) was reasonable when we only supported ubuntu.14.04-x64, but we support many more distros now.  For folks that invoke MSBuild.exe directly, we should have a task in buildtools that provides a better default (e.g. reads /etc/os-release and computes a RID).

**Comment by Petermarcu** [comment]
@ellismg , is there an issue in the buildtools repo to track adding this?

**Comment by ellismg** [comment]
@Petermarcu No.  I was going to use this one to track it, since this was the place we did this.

**Comment by mellinoe** [comment]
Done
