### ISSUE TITLE
Serialization tests fail

### ISSUE THREAD

**Issue by Maxwe11** [dotnet/corefx#1247]
DataContractSerializerTests.DCS_ContainsLinkedList [FAIL]
			System.Exception : Test failed for input : SerializationTypes.ContainsLinkedList
			Stack Trace:
			   d:\Workspace\corefx\src\System.Runtime.Serialization.Xml\tests\DataContractSerializer.cs(1717,0): at DataContractSerializerTests.SerializeAndDeserialize[T](T value, String baseline, DataContractSerializerSettings settings, Func`1 serializerFactory)
			   d:\Workspace\corefx\src\System.Runtime.Serialization.Xml\tests\DataContractSerializer.cs(1113,0): at DataContractSerializerTests.DCS_ContainsLinkedList()
	  Starting:    System.Xml.XPath.XmlDocument.Tests
	  Finished:    System.Runtime.Serialization.Xml.Tests
	  
	  === TEST EXECUTION SUMMARY ===
		 System.Runtime.Serialization.Xml.Tests  Total: 97, Errors: 0, Failed: 1, Skipped: 0, Time: 1,906s

=====================================
		 DataContractJsonSerializerTests.DCJS_ContainsLinkedList [FAIL]
			System.FormatException : Input string was not in a correct format.
			Stack Trace:
				  at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
				  at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
				  at System.String.Format(IFormatProvider provider, String format, Object[] args)
				  at System.Diagnostics.Debug.WriteLine(String format, Object[] args)
			   d:\Workspace\corefx\src\Common\tests\System\Console.cs(12,0): at System.Console.WriteLine(String message, Object[] args)
			   d:\Workspace\corefx\src\System.Runtime.Serialization.Json\tests\DataContractJsonSerializer.cs(1291,0): at DataContractJsonSerializerTests.SerializeAndDeserialize[T](T value, String baseline, DataContractJsonSerializerSettings settings, Func`1 serializerFactory, Boolean skipStringCompare)
			   d:\Workspace\corefx\src\System.Runtime.Serialization.Json\tests\DataContractJsonSerializer.cs(1047,0): at DataContractJsonSerializerTests.DCJS_ContainsLinkedList()
	  xUnit.net console test runner (32-bit .NET Core)
	  Copyright (C) 2014 Outercurve Foundation.
	  
	  Discovering: System.Xml.XPath.Tests
	  Finished:    System.Runtime.Serialization.Json.Tests
	  
	  === TEST EXECUTION SUMMARY ===
		 System.Runtime.Serialization.Json.Tests  Total: 74, Errors: 0, Failed: 1, Skipped: 0, Time: 1,477s

/cc @khdang

**Comment by Maxwe11** [comment]
test added in #1235 also fail

		 DataContractSerializerTests.DCS_BaseClassAndDerivedClassWithSameProperty [FAIL]
			System.ArgumentOutOfRangeException : The UTC time represented when the offset is applied must be between year 0 and 10,000.
			Parameter name: offset
			Stack Trace:
				  at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
				  at System.DateTimeOffset..ctor(DateTime dateTime, TimeSpan offset)
				  at System.Xml.Schema.XsdDateTime.op_Implicit(XsdDateTime xdt)
				  at System.Xml.XmlConvert.ToDateTimeOffset(String s)
			   d:\Workspace\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlReaderDelegator.cs(387,0): at System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsDateTime()
				  at ReadDerivedClassWithSamePropertyFromXml(XmlReaderDelegator , XmlObjectSerializerReadContext , XmlDictionaryString[] , XmlDictionaryString[] )
			   d:\Workspace\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\ClassDataContract.cs(485,0): at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
			   d:\Workspace\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerReadContext.cs(520,0): at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
			   d:\Workspace\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerReadContext.cs(187,0): at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, DataContract& dataContract)
			   d:\Workspace\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerReadContext.cs(123,0): at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
			   d:\Workspace\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\DataContractSerializer.cs(420,0): at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
			   d:\Workspace\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializer.cs(282,0): at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
			   d:\Workspace\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializer.cs(273,0): at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName)
			   d:\Workspace\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializer.cs(236,0): at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(XmlDictionaryReader reader)
			   d:\Workspace\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializer.cs(225,0): at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(Stream stream)
			   d:\Workspace\corefx\src\System.Runtime.Serialization.Xml\tests\DataContractSerializer.cs(1747,0): at DataContractSerializerTests.SerializeAndDeserialize[T](T value, String baseline, DataContractSerializerSettings settings, Func`1 serializerFactory)
			   d:\Workspace\corefx\src\System.Runtime.Serialization.Xml\tests\DataContractSerializer.cs(1113,0): at DataContractSerializerTests.DCS_BaseClassAndDerivedClassWithSameProperty()

**Comment by khdang** [comment]
@Maxwe11 Thanks for the information. Did you run the DCS_BaseClassAndDerivedClassWithSameProperty test in your native timezone (not changing system clock to another time zone)?

**Comment by Maxwe11** [comment]
I've used native timezone
