### ISSUE TITLE
Lots of XML tests are not being run in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12483]
You can see in the log at http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug/30/consoleText , for example, that even though XML tests like System.Xml.RW.XmlSystemPathResolver.Tests get compiled, they never get executed.  At least one bug I'm aware of is not getting flagged as a result.
cc: @sepidehMS

**Comment by stephentoub** [comment]
Also, a bunch of the test projects are pulling in System.Private.Xml from the published packages rather than the live bits.

**Comment by danmosemsft** [comment]
Fixed by https://github.com/dotnet/buildtools/pull/1119  ?

**Comment by sepidehMS** [comment]
> Also, a bunch of the test projects are pulling in System.Private.Xml from the published packages rather than the live bits.

@stephentoub Is [System.Xml.RW.XmlWriter.Tests](https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/tests/XmlWriter/System.Xml.RW.XmlWriter.Tests.csproj) one of them? Since these test projects are targetting `netstandard1.3`, I figured it's going to grab the package from package harvesting anyway and we don't need to reference pkgproj. Isn't that the case?

**Comment by stephentoub** [comment]
> Since these test projects are targetting netstandard1.3, I figured it's going to grab the package from package harvesting anyway and we don't need to reference pkgproj. Isn't that the case?

If it is the case, we should fix that as we want our tests for Xyz project to be testing the latest Xyz project, otherwise any changes we make won't be tested until they're published into a new package.
cc: @weshaggard

**Comment by weshaggard** [comment]
cc @joperezr 

While it is correct that when running these in netstandard1.3 configuration they will run against the asset harvested from the last stable package. However these tests should be running in multiple configurations, both the netstandard1.3 and netstandard1.7 configurations at a minimum, to ensure we test the live builds.

**Comment by joperezr** [comment]
@weshaggard agreed, that is what @sepidehMS is fixing in #12742

**Comment by sepidehMS** [comment]
Done by https://github.com/dotnet/corefx/pull/12742
