### ISSUE TITLE
GetCurrentMethod replacement in .NetCore

### ISSUE THREAD

**Issue by rnagpal** [dotnet/corefx#12496]
I’m having trouble converting the call to GetCurrentMethod below to .NET Core compatible syntax. Can someone help?

This is a static method in a static class.

internal static IQueryable<TResult> AsSQL<TSource, TResult>(
            this IOrderedQueryable<TSource> source,
            SqlQuerySpec querySpec)
        {
            if (querySpec == null)
            {
                throw new ArgumentNullException("querySpec");
            }
            if (string.IsNullOrEmpty(querySpec.QueryText))
            {
                throw new ArgumentException("querySpec.QueryText");
            }
            return source.Provider.CreateQuery<TResult>(Expression.Call(null, ((MethodInfo)MethodBase.GetCurrentMethod()).MakeGenericMethod(
                new Type[]
                {
                    typeof(TSource),
                    typeof(TResult)
                }), new Expression[]
                {
                    source.Expression,
                    Expression.Constant(querySpec)
                }));
        }

**Comment by rnagpal** [comment]
Any updates on this one?

**Comment by jkotas** [comment]
This method was added back as part of .NET Standard 2.0 project: https://github.com/dotnet/corefx/blob/master/src/System.Runtime/ref/System.Runtime.cs#L5377.

You can read more about .NET Standard 2.0 at https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/

If you cannot wait for .NET Standard 2.0, you can lookup the method by name, or use a creative GetMethodInfoOf construct based on Linq expressions (see https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=GetMethodInfoOf).

**Comment by rnagpal** [comment]
@jkotas Thanks for the pointer!

**Comment by agatlin** [comment]
@jkotas, The provided link for GetMethodInfoOf does not appear to be active. I have been unable to locate other information on this method. Could you possibly point me to an example? Many thanks.

**Comment by svick** [comment]
@agatlin Thanks to the wonders of git, you can [time travel](https://stackoverflow.com/a/6990682/41071) back to 2016 to find that [the method](https://github.com/dotnet/corefx/blob/b5016b1/src/System.Linq.Queryable/src/System/Linq/Queryable.cs#L1983-L1987) was just:

```c#
private static MethodInfo GetMethodInfoOf<T>(Expression<Func<T>> expression)
{
    var body = (MethodCallExpression)expression.Body;
    return body.Method;
}
```

It was used e.g. like this:

```c#
GetMethodInfoOf(() => Queryable.Aggregate(
    default(IQueryable<TSource>), default(Expression<Func<TSource, TSource, TSource>>)))
````
