### ISSUE TITLE
Unable to incrementally test .NET Core application

### ISSUE THREAD

**Issue by rnagpal** [dotnet/corefx#12494]
I'm working on a .NET Standard 1.6 assembly and referencing it in a .NET Core 1.0 Console App via Manage Nuget packages.. under the References mode.

I've observed that as I make fixes in my assembly, I uninstall the currently referenced nuget package from the .NET Core App project and install the updated nugget package, it somehow used the old assembly/pdb as I'm unable to debug the source by putting breakpoints(since the source code has changed) and also the new change is not reflected. 

I've found that if now I bump up the version in the project.json of my assembly by changing the "version" property, I'm able to see the updated functionality and also debug the source.

I've even tried "clean solution" for my .NET Core App and then install the new package but it doesn't helps.

Anyone can tell me what's wrong here?

**Comment by Jupakabra** [comment]
You need to delete nuget package from the cache, most likely located in `<user>/.nuget/packages`.

**Comment by rnagpal** [comment]
@Jupakabra Thanks! That worked!
