### ISSUE TITLE
Build error in SUSE 11 SP3

### ISSUE THREAD

**Issue by RimashMohomed** [dotnet/corefx#12501]
When i try to build in 
`Linux sles11-sp3 3.0.101-0.15-default #1 SMP Wed Jan 22 15:49:03 UTC 2014 (5c01f4e) x86_64 x86_64 x86_64 GNU/Linux`

 corefx gives below error

`corefx/src/Native/Unix/System.Native/pal_io.cpp:135:37: error: use of undeclared identifier 'IN_EXCL_UNLINK'; did you mean 'PAL_IN_EXCL_UNLINK'?
static_assert(PAL_IN_EXCL_UNLINK == IN_EXCL_UNLINK, "");
^~~~~~
PAL_IN_EXCL_UNLINK
corefx/src/Native/Unix/System.Native/pal_io.h:281:5: note: 'PAL_IN_EXCL_UNLINK' declared here
PAL_IN_EXCL_UNLINK = 0x04000000,`

**Comment by karelz** [comment]
We didn't respond for a long time on this issue, very sorry for that :( (finishing triage of all repo).
Is it still a problem for you?

**Comment by RimashMohomed** [comment]
@karelz couldn't test back on latest release.

**Comment by karelz** [comment]
@RimashMohomed is it ok to close then? (or did I misunderstand your answer?)

**Comment by RimashMohomed** [comment]
@karelz what i mean was that i couldn't build the latest corefx on suse 11. So problem may exist and i am not sure about the issue. Other than that really need this issue solved and looking to build on suse 11

**Comment by karelz** [comment]
@mellinoe can you help here please?

**Comment by mellinoe** [comment]
@RimashMohomed SUSE 11 is not one of our officially-supported distros, as far as I know. It would help to know what you're trying to accomplish. Getting a full product working end-to-end (including coreclr, core-setup, and cli) will be very involved and very difficult on an unsupported distro. This is getting easier and more streamlined in the 2.0 release, but it's not quite "there" yet.
Here's a couple things you can try now:

* Grab the latest "portable Linux" version from https://github.com/dotnet/cli and see if that works.
* Try to build the native components in "portable" mode yourself, by running `src/Native/build-native.sh portable`

Does that help?

**Comment by RimashMohomed** [comment]
@mellinoe by Only building the native components in "portable" mode in suse 11, can i compile a C# program into native ?

**Comment by mellinoe** [comment]
@RimashMohomed No, the "full product" is what you need in order to do that, and it is much more complicated than just building the native components of corefx. We have an effort to enable "build from source" which will make it much easier to do by-hand, but we are still working on that, and it won't be done for a little while. For the time being I would recommend trying the "portable Linux" version from the repo I linked.

**Comment by weshaggard** [comment]
@RimashMohomed if the portable linux assets don't work for you then I suggest following the instructions in the docs https://github.com/dotnet/source-build/pull/227 and building natively for this unsupported OS.
