### ISSUE TITLE
Move HttpVersion to System.Net.Primitives

### ISSUE THREAD

**Issue by tijoytom** [dotnet/corefx#12510]
HttpVersion is privately copied in `System.Net.Http` and `System.Net.Http.WinHttpHandler`. Moving it to lower-level contract will unify all these private copies.

Note: Private copy in `Common` has two additional values in it. They are not in .NET 4.6 and Xamarin, so we can't add them in public netstandard2.0 contract.

More details in: https://github.com/dotnet/corefx/pull/12347#discussion_r81843383

**Comment by karelz** [comment]
@tijoytom what is the value/benefit? (please edit original text)

**Comment by tijoytom** [comment]
@karelz Please refer the link ,it has detailed discussion about why it's good to have it in S.N.Primitives.. I i don't know how to link the exact comment in a PR

**Comment by justinvp** [comment]
https://github.com/dotnet/corefx/pull/12347#discussion_r81843383

**Comment by karelz** [comment]
@tijoytom what is the impact if we do not do it in 1.2? It sounds like we will create unnecessary compatibility burden. Wouldn't it be more desirable to address it as part of netstandard2.0?

cc: @ericeil

**Comment by davidsh** [comment]
>@tijoytom what is the impact if we do not do it in 1.2? It sounds like we will create unnecessary compatibility burden. Wouldn't it be more desirable to address it as part of netstandard2.0?

Isn't .NET Core 1.2 == "netstandard20" ?  That is what we have been assuming.

This should be done as part of the "add back lots of APIs" work for netstandard20.  And that activity is what is happening in the [master] branch.

**Comment by karelz** [comment]
I thought so, marking as such. @tijoytom can you please fix it? Thanks!

**Comment by karelz** [comment]
@davidsh netstandard2.0 should imply 1.2. It is the key (and largest) feature in 1.2.

**Comment by tijoytom** [comment]
@davidsh @CIPop @stephentoub 

Note: Private copy in Common has two additional values in it. They are not in .NET 4.6 and Xamarin, so we can't add them in public netstandard2.0 contract.

So we do not want to expose the new Version2.0  , what's the standard way to handle this .What am doing now is split  the class across two source files and conditionally include if it's 1.7 .

**Comment by CIPop** [comment]
@tijoytom I believe that you need to add #if netcoreapp11 around the new API. I wasn't successful so far in making tests work (but I was able to produce multiple ref and implementation binaries).
@weshaggard recommended System.Runtime.Extensions as example.

**Comment by tijoytom** [comment]
Fixed by https://github.com/dotnet/corefx/pull/13226
