### ISSUE TITLE
Replace custom date-parsing (HttpDateParse.cs) with DateTime.Parse

### ISSUE THREAD

**Issue by tijoytom** [dotnet/corefx#12513]
Need to make sure DateTime.Parse handle all the cases HttpDateParse deal with .. 

https://github.com/dotnet/corefx/pull/12347/files/7fe03ad63fbe79d791228319e16e0f1910f4d06d#diff-93d09013382d2a05606b12516b65ea11

**Comment by karelz** [comment]
Next step: Validate if it is doable and create proposal for changes. Be careful about `DateTime.Parse` compat - we can't break it. If it is necessary, we might need to give up on this enhancement.
