### ISSUE TITLE
Authentication for System.Net.Mail does not impersonate for SystemNetworkCredential

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#12529]
WindowsIdentity.Impersonate is not available in .NET Core, this is a deviation from Desktop.

Refer to desktop code [here](https://referencesource.microsoft.com/#System/net/System/Net/mail/smtpconnection.cs,481)

**Comment by karelz** [comment]
@stephentoub thinks the member will come back. We should be able to use it.
@Priya91 can you please confirm?

**Comment by Priya91** [comment]
> @Priya91 can you please confirm?

Confirm what ?

**Comment by karelz** [comment]
That we can use it ...

**Comment by Priya91** [comment]
@weshaggard The WindowsIdentity type is under extensions in [dotnet/standard](https://github.com/dotnet/standard/blob/e3e48e4e1e396381807eb255cf1f2150e73ce430/extensions/windowsidentity/windowsidentity.cs#L216). Does that mean it's not included for netstandard2.0?

**Comment by weshaggard** [comment]
WindowsIdentity is not part of .NET Standard 2.0. It will be an extension library on top of .NET Standard 2.0. I don't believe we are currently tracking any work to update our current WindowsIdentity extension library with new APIs.

**Comment by Priya91** [comment]
@karelz The API is not available for netstandard2.0, so closing this issue.

**Comment by karelz** [comment]
Thanks!
cc: @CIPop @davidsh
