### ISSUE TITLE
Capturing Identity context in async smtp call doesn't check if the credential is in cache.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#12526]
This check depends on a call to an internal member in `CredentialCache` called `CredentialCache.IsDefaultInCache`, which is not available in .NETCore. Need a way to simulate this behavior.

Desktop reference [here](https://referencesource.microsoft.com/#System/net/System/Net/mail/SmtpClient.cs,627)

**Comment by justinvp** [comment]
The commit that removed the internal `IsDefaultInCache` property is: https://github.com/dotnet/corefx/commit/7dc31aba7399e3f3ba0d92c97dc306782732ee21. It'd be relatively easy to add back, but it's internal, so the only way to call it from System.Net.Mail would be to use a hack like reflection.

In lieu of adding a new public API, there is a slower way to determine whether the default is in the cache from System.Net.Mail by calling current public APIs. Something like:

```c#
public static class CredentialCacheExtensions
{
    public static bool IsDefaultInCache(this CredentialCache cache)
    {
        Debug.Assert(cache != null);

        NetworkCredential defaultCredential = CredentialCache.DefaultNetworkCredentials;

        foreach (NetworkCredential credential in cache)
        {
            if (ReferenceEquals(credential, defaultCredential))
            {
                return true;
            }
        }

        return false;
    }
}
```

The downside is this has some enumerator allocations and has to search through the entire cache.

**Comment by karelz** [comment]
@Priya91 can you look into @justinvp's workaround?

**Comment by Priya91** [comment]
I had searched desktop reference source, and this property was also used in ```HttpWebRequest```, and this gets passed to ```ContextAwareResult```. ```HttpWebRequest``` in corefx now doesn't use ```ContextAwareResult``` instead uses Task and TPL extensions. Mail surface area doesn't have any Begin,End methods, hence making SendAsync, SendMailAsync to c# ```async```, ```await```, should eliminate need for ```IsDefaultInCache```. 

@davidsh @CIPop What do you guys propose we do here?

**Comment by CIPop** [comment]
@Priya91 What is the difference in behavior between .Net Desktop and .Net Core (current implementation, if we don't perform this check)?

**Comment by Priya91** [comment]
If the credential is found in cache then the identity is also captured when capturing the execution context returning from async call back to the user. This is enabled only on Windows. It updates the ```WindowsIdentity``` object in the result by calling ```GetCurrent``` for retrieving current window user object.

**Comment by Priya91** [comment]
I'm working on this

**Comment by Priya91** [comment]
Going down the path of using Task instead of AsyncResult seems too expensive for the issue, given that there are multiple layers of async calls down to Tcp connection. @justinvp's solutions seems feasible here. Looked at ```IsDefaultInCache``` implementation and this counter is increased/decreased whenever ```SystemNetworkCredential``` is added to the ```CredentialCache```. So checking if ```SystemNetworkCredential``` is found in cache should mimic the property behavior.
