### ISSUE TITLE
Add support to drop mails to IIS pickup directory if IIS is running on Windows

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#12538]
Currently .NET Core throws ```NotSupportedException``` for this, since the Desktop implementation depends on COM Interop. Needs investigation whether this feature is worth having in .NET Core and if so how to implement on Windows.

**Comment by karelz** [comment]
Doesn't work x-plat, Xamarin doesn't support it. Let's close it.
If there is need later we can reopen / create new issue.
