### ISSUE TITLE
Enhance performance of System.Net.Mail by pooling open TcpClient connections.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#12536]
Desktop code used ```ServicePointManager``` to provide this, since .NET Core doesn't support ```ServicePointManager```, we need a way to keep ```TcpClient``` connections open and use existing ones for same connections.

**Comment by karelz** [comment]
We are now focusing on compatibility. It is not clear if the perf will be so bad that the API is unusable.
Closing now. If we get more feedback later, we can re-evaluate.
