### ISSUE TITLE
Remove P2P reference from System.Runtime.Serialization.Formatters

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#12531]
As part of changing MulticastDelegate's interfaces, we needed to add a temporary P2P reference from System.Runtime.Serialization.Formatters to System.Runtime, so this should be removed once the package versions are updated.

line: https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Serialization.Formatters/src/System.Runtime.Serialization.Formatters.csproj#L67-L68

**Comment by karelz** [comment]
@joperezr is it part of netsandard2.0?

**Comment by joperezr** [comment]
yes, sorry I didn't add the labels
