### ISSUE TITLE
Bring Ntlm, Negotiate and Digest authentication modules to .NET Core System.Net.Mail.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#12535]
`System.Net.Mail` uses the Negotiate, Ntlm and Digest authentication protocols to try validate the credentials if the server supports it. These authentication modules depend on `NTAuthentication` internal type in `System.Net.Security`. This issue is to figure out a way to port these to .NET Core, to have newer implementation not depending on Security internal types or expose necessary new APIs on Security to consume in other assemblies.

**Comment by Priya91** [comment]
I'm working on this

**Comment by Jiayili1** [comment]
Disabled test, reopen it.

**Comment by CIPop** [comment]
@Priya91, @karelz Is this a test issue or a missing feature?

**Comment by karelz** [comment]
Looks like missing feature to me ... @Priya91 can you please confirm and mark it appropriately?

**Comment by Priya91** [comment]
This can be closed now, resolved in pr #16450. Github didn't close this.

**Comment by karelz** [comment]
@Priya91 the PR you referred (#16450) just enables some tests.
Does it mean that the things called out in top post about porting to .NET Core were done in another PR?

**Comment by Priya91** [comment]
Yes, I had put these NTAuth files in a common location, and used them instead of reflecting to Security lib. This was done long back, and hence the issue was closed. Refer PR #13292 referenced in the issue above. It got reopened because the tracking test was pointing to this issue, which is fixed in the #16450 PR.

**Comment by karelz** [comment]
Now it makes sense, thanks!
