### ISSUE TITLE
[Feature request] Low-level API for HashAlgorithm

### ISSUE THREAD

**Issue by Cologler** [dotnet/corefx#12547]
Here are all public API for HashAlgorithm class in .Net core:

``` cs
public byte[] ComputeHash(byte[] buffer)
public byte[] ComputeHash(byte[] buffer, int offset, int count)
public byte[] ComputeHash(Stream inputStream)
```

For some reason, I cannot provide a whole input stream (only multi buffer).

**Comment by karelz** [comment]
Can you please clarify what you mean? What exactly doesn't work / you would like to see added?

**Comment by Cologler** [comment]
When I read a http stream (not support seek), I need to compute sha1 and md5 in same time.

I don't want to cache the stream in local.

**Comment by karelz** [comment]
Sample code would clarify it better. I am still not 100% clear on what you mean.

Guessing: If you need to pass stream content (which cannot seek) into 2 calls, you will have to cache it first. I don't see a way around that.

**Comment by Cologler** [comment]
If `HashCore` and `CaptureHashCodeAndReinitialize` is public, then I can write some code like:

```
while ((bytesRead = inputStream.Read(buffer, 0, buffer.Length)) > 0)
{
    sha1.HashCore(buffer, 0, bytesRead);
    md5.HashCore(buffer, 0, bytesRead);
}
sha1Value = sha1.CaptureHashCodeAndReinitialize();
md5Value = md5.CaptureHashCodeAndReinitialize();
```

[Source of `HashAlgorithm`](https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/HashAlgorithm.cs).

**Comment by Tornhoof** [comment]
You could use the iterative api:
TransformBlock and TransformFinalBlock.

**Comment by Cologler** [comment]
Here are the api in Asp.Net core:

![picpick-20161013-023037-001](https://cloud.githubusercontent.com/assets/10906962/19322786/00ef4906-90ed-11e6-86f8-222ec9426de0.png)

@_@ !!!

**Comment by Cologler** [comment]
Seem the source is .Net Framework (not .Net core)?

**Comment by Tornhoof** [comment]
Ah, then they already added Transform(Final)Block in the effort to get .net core api compatible to the full one, as you see in your link to the current source. So, looks like your wish will be in the version of .net core targeting .net Standard 2.0
