### ISSUE TITLE
DeflateStream buffer reuse

### ISSUE THREAD

**Issue by Tratcher** [dotnet/corefx#12549]
The `DeflateStream(Stream stream, CompressionLevel compressionLevel, bool leaveOpen)` constructor allocates an 8KB `byte[]` buffer for each instance. ASP.NET Core has response compression middleware that needs a new stream per response, so this memory allocation adds up very quickly.

Possible improvements:
A) Internally pooling the buffers
B) Allowing the buffer to be provided in the constructor so the caller can pool.

Note any API changes would need to be exposed on the GZipStream wrapper as well.

**Comment by davidfowl** [comment]
Related #11571 
/cc @stephentoub

**Comment by karelz** [comment]
@ianhays can you take a look?
