### ISSUE TITLE
Remove SystemException from Common when it's supported in UWP

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#12550]
Refers to System.SystemException under src\Common\src\System

**Comment by AlexGhiondea** [comment]
@sepidehMS is there specific work that we need to do when UWP support comes online to remove it, or would it happen as part of the UWP work?

**Comment by sepidehMS** [comment]
The only change needed for this is to remove the file from Common directory and also remove it from any `csproj `that uses it (currently just one).

**Comment by danmosemsft** [comment]
Not sure I follow this -- why would UWP make the implementation in CoreFX redundant? I thought it would use it.

**Comment by sepidehMS** [comment]
@danmosemsft Right now, System.SystemException is not available for UWP. That's why I added a stub for it for now. Once it is available on UWP we need to remove this stub and that's what this issue is tracking.

**Comment by karelz** [comment]
@sepidehMS should it be assigned to you? (i.e. are you actively working on it?)

**Comment by sepidehMS** [comment]
@karelz Yes, I'm about to merge PR https://github.com/dotnet/corefx/pull/12351 to resolve this.

**Comment by jkotas** [comment]
Fixed by https://github.com/dotnet/corefx/pull/14659
