### ISSUE TITLE
Create Win7 CI build

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#1255]
We currently have a number of folks that are still working on Win7 which we support and we keep breaking things from time to time. We need to get a CI build/test for Win7.

**Comment by eatdrinksleepcode** [comment]
+1

**Comment by ellismg** [comment]
Dupe of #1058?

**Comment by weshaggard** [comment]
Yes it is a duplicate (I did try to find a preexisting one but failed to find the right key words). I will assign 1058 to @mmitche
