### ISSUE TITLE
How folder `tests` should be structured

### ISSUE THREAD

**Issue by Maxwe11** [dotnet/corefx#1257]
There is some inconsistency with how test projects structured in theirs `tests` folders.
Most common case is:

    tests\
        test_project_1.csproj
        test_1.cs
        test_2.cs

in case of multiple test projects (e.g. MemoryMappedFiles):

    tests\
        test_project_1.csproj
        test_project_2.csproj
        test_folder_1\
            test_1.cs
            test_2.cs
        test_folder_2\
            test_1.cs
            test_2.cs

However some projects structured like (e.g XDocument)

    tests\
        test_project_1\
            test_1.cs
            test_2.cs
            test_project_1.csproj
        test_project_2\
            test_1.cs
            test_2.cs
            test_project_2.csproj

**Comment by weshaggard** [comment]
I don't think we have called out this structure explicitly anywhere but I would expect either the first case or the last case I don't personally like case 2, as I think the csproj file should be in the directory that contains the source code. The only time we have the potential for multiple csproj files in the same directory is if we need to split up the same set of sources/tests on some pivot like OS or something like similar.

**Comment by krwq** [comment]
I honestly think it doesn't matter as you open the solution anyway and that information is transparent.

**Comment by ellismg** [comment]
FWIW, I do a bunch of work via msbuild from the command line, so having a single csproj in a folder is helpful, as I don't need to specify what project to build.

**Comment by eatdrinksleepcode** [comment]
+1 @ellismg

**Comment by krwq** [comment]
@ellismg, good point, completely agree :+1:

**Comment by ellismg** [comment]
Let's go with option 3 for cases where we have multiple tests.  I will update the wiki with the new guidance
