### ISSUE TITLE
NullReferenceException instead of Argument[Null]Exception in FileIOPermission constructor in 4.6.2

### ISSUE THREAD

**Issue by onyxmaster** [dotnet/corefx#12584]
Compare the [FileIOPermission in 4.6.2](https://github.com/Microsoft/referencesource/blob/1acafe20a789a55daa17aac6bb47d1b0ec04519f/mscorlib/system/security/permissions/fileiopermission.cs#L550) and [FileIOPermission in 4.6.1](https://github.com/Microsoft/referencesource/blob/e458f8df6ded689323d4bd1a2a725ad32668aaec/mscorlib/system/security/permissions/fileiopermission.cs#L543) -- they obviously changed the illegal path checks, so the [contract](https://msdn.microsoft.com/en-US/library/h05w5es7(v=vs.110).aspx) of the FileIOPermission constructor throwing ArgumentException on invalid path is broken.
This leads to some [nasty stuff](http://stackoverflow.com/a/40000774/2917948).

The simple repro would be this:

```
using System;
using System.Security.Permissions;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            new FileIOPermission(FileIOPermissionAccess.PathDiscovery, (string)null);
        }
        catch (ArgumentException)
        {
        }
    }
}
```

**Comment by karelz** [comment]
@JeremyKuhne @ianhays is it worth fixing?

**Comment by stephentoub** [comment]
@karelz, it sounds like we made a breaking change in desktop from 4.6.1 to 4.6.2.

**Comment by onyxmaster** [comment]
I met this problem when building old [ASP.NET MVC](https://github.com/ASP-NET-MVC/aspnetwebstack) -- it no longer passes tests on 4.6.2. In any case NRE vs ANE seems like it might break existing code (I linked fresh SO question in the issue).

**Comment by karelz** [comment]
That sounds unpleasant. Sadly, when these things happen, there is no easy/clear solution -- we can't fix 4.6.2, fixing future version means there is compat burden against 4.6.2, and portable libraries will have to handle both cases anyway if they want to work on 4.6.1 & 4.6.2 without cross-compiling.
Usually the best option is to leave it be (if there is simple workaround - like in this case), unless it has huge impact on large number of customers (which it doesn't seem to be the case here).

Either way, CoreFX repo can't help to address full .NET Framework "Desktop" bugs, closing here.

**Comment by stephentoub** [comment]
> closing here

@karelz, can you provide guidance on where folks should report such issues?

**Comment by karelz** [comment]
> @karelz, can you provide guidance on where folks should report such issues?

If the issue has significant impact on customers, then any way that gets to us is good/sufficient (CoreFX github, StackOverflow, Microsoft Connect, etc.).

**Comment by stephentoub** [comment]
> If the issue has significant impact on customers, then any way that gets to us is good/sufficient (CoreFX github, StackOverflow, Microsoft Connect, etc.).

But then we close the corefx issue because it's not relevant to corefx?  How are we tracking this issue for desktop?

**Comment by karelz** [comment]
Tracking for Desktop makes sense only if the impact is significant. Using Microsoft Connect is best in such case -- the issue would need to have quite a few votes to pop.
