### ISSUE TITLE
High frequencey Ping trough Unix RawSockets gives false positives

### ISSUE THREAD

**Issue by ttzankov** [dotnet/corefx#12580]
Due to the way the echor-request/echo-reposne matching is implemented using thread id in \System.Net.Ping\src\System\Net\NetworkInformation\Ping.Unix.cs  - SendIcmpEchoRequestOverRawSocket , when a program sends high number of Ping requests to the same host or group of hosts, late ICMP responses and/or responses from other pings sent from the same thread id is generating false positives. To avoid this, the source IP on echo-response packets should be verified against the echo-request address.  Additionally the generation of identity values should be changed or sequence field should be used in addition (as in windows implementation) to generate truly random identification information.

**Comment by karelz** [comment]
I think Ping was introduced by @stephentoub recently ...

**Comment by stephentoub** [comment]
> I think Ping was introduced by @stephentoub recently ...

No, we shipped it in 1.0.  @mellinoe provided the Unix implementation.

**Comment by mellinoe** [comment]
Here's what Mono does for the ping identifier:

https://github.com/mono/mono/blob/8994ce8a09a101e7965a820ed7dc148d9685f89f/mcs/class/System/System.Net.NetworkInformation/Ping.cs#L118

```CSharp
		public Ping ()
		{
			// Generate a new random 16 bit identifier for every ping
			RNGCryptoServiceProvider rng = new RNGCryptoServiceProvider ();
			byte [] randomIdentifier = new byte [2];
			rng.GetBytes (randomIdentifier);
			identifier = (ushort)(randomIdentifier [0] + (randomIdentifier [1] << 8));
		}
```

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/pull/12616
