### ISSUE TITLE
S.R.CS.Unsafe: Add `IntPtr ByteOffset<L, R>(ref L left, ref R right)`

### ISSUE THREAD

**Issue by nietras** [dotnet/corefx#12593]
As discussed in https://github.com/dotnet/corefxlab/pull/796#issuecomment-253138362 add: 
```csharp
IntPtr ByteOffset<T>(ref T left, ref T right);
```
to the `Unsafe` class. Things to discuss for this addition:
 * Naming
 * Generic parameters, one or two? One, as this will only allow users to compute the offset between same types and, thus, limits the possibility of finding offsets that could cause alignment issues, see https://github.com/dotnet/corefx/issues/12593#issuecomment-253305078, e.g. for offset between `ref byte` and `ref double`. If an offset between two different types are needed this can be done by explicitly converting one of the `ref`s to the same type as the other e.g.
```csharp
ref byte b1 = ...;
ref double d1 = ...;
IntPtr byteOffset = ref Unsafe.ByteOffset(ref Unsafe.As<double, byte>(ref d1), ref b1);
```
 * Return type, do we imagine we need several versions with different return types, that could influence naming?
 * Parameter naming and order?

@jkotas @mellinoe @jamesqo @benaadams @omariom @davidfowl 

When we decide I could give a shot at adding this too to `Unsafe`.

**Update 1**: Changed proposal to have only one generic argument.

**Comment by jamesqo** [comment]
> Generic parameters, one or two?

I would think we should have 1 generic parameter. Having 2 would increase the possibility someone makes an accident (which is very dangerous with this class). If someone really wants to get the distance between 2 differently-typed refs they can always convert both sides to pointers, no?

**Comment by jkotas** [comment]
> I would think we should have 1 generic parameter

I agree.

**Comment by nietras** [comment]
> wants to get the distance between 2 differently-typed refs they can always convert both sides to pointers, no?

This requires pinning, which I don't think is good. 

> I would think we should have 1 generic parameter

I think it is a unnecessary restriction, this is `Unsafe` we can do lots of very dangerous things with it and other methods, why limit this method?

I'm not sure I can give a good example for usage here but this would open up some possibilities of evaluating stack space, member layout, etc. all in a way that does not require pinning. Perhaps it can be done in other ways, but limiting to one type seems rather restrictive or limited to an array use case. Aren't there other use cases?

**Comment by jkotas** [comment]
> This requires pinning, which I don't think is good. 

It does not require pinning. It just requires you to type extra `ref Unsafe.As<..,...>( )` to make it clear that it is what you really want.

**Comment by nietras** [comment]
> It does not require pinning. It just requires you to type extra ref Unsafe.As<..,...>( )

Was referring to "pointers", but yes it can be done via `As`, of course. I understand that getting offsets that might change alignment can cause problems, but is that reason enough to limit this methods signature and make it more cumbersome? 

Anyway, I can live with the `As` it shouldn't have perf consequences as far as I can tell, and we can settle for 1 generic type if you think this is best.

**Comment by jamesqo** [comment]
Since we already have `SubtractByteOffset` and `AddByteOffset`, I think `ByteOffset` sounds like a reasonable name. We also have to think about the parameter naming though.

tagging @mikedn

**Comment by jkotas** [comment]
@nietras Could you please the update the proposal at the top to have just generic arg, and maybe add a sentence that summarizes the rationale (with a link to the discussion for full context)? I would like FXDC to take a quick look at the naming.

**Comment by nietras** [comment]
>  update the proposal at the top to have just one generic arg

@jkotas done, let me know if the changes are ok.

> FXDC

Can I ask what this means? :)

>  think about the parameter naming though

@jamesqo yes and parameter ordering, of course. I thought of many different possibilities of which some are:
```csharp
IntPtr ByteOffset<T>(ref T from, ref T to); // result = to - from
IntPtr ByteOffset<T>(ref T to, ref T from); // result = to - from
IntPtr ByteOffset<T>(ref T begin, ref T end); // result = end - begin
IntPtr ByteOffset<T>(ref T target, ref T origin); // result = target - origin
IntPtr ByteOffset<T>(ref T origin, ref T target); // result = target - origin
```
Of these I think `IntPtr ByteOffset<T>(ref T from, ref T to);` reads the best i.e. byte offset from to. But it is also counterintuitive if one thinks of this primarily as a subtraction.

**Comment by jkotas** [comment]
Look good. Thanks.

> FXDC 

It is the group of people reviewing the API designs (more details https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md)

**Comment by terrajobst** [comment]
We (FXDC) just took a look. We'd prefer this version:

`IntPtr ByteOffset<T>(ref T origin, ref T target);`

**Comment by jkotas** [comment]
Thanks. 

Just a thought: Would `IntPtr GetByteOffset<T>(ref T origin, ref T target);` look better than just ByteOffset?

**Comment by nietras** [comment]
Thanks, I like it better without "Get" simply because it is more succinct
and... less java-like, ha! :-)

I can try make a PR for this end of this week.
