### ISSUE TITLE
Use ArrayBuilder in more places

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#12590]
I just rebased to latest master and ran grep to see some of the places we're using `List<T>` as a local variable. Here are the results I got: https://gist.github.com/jamesqo/467f10b7523380b9fca7b9e66c020e3f It would seem lots of these places, i.e. [System.Diagnostics.Process](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessManager.Linux.cs#L30), could easily use `ArrayBuilder` instead if the List isn't passed in/out of the function.

**Comment by robosek** [comment]
I’ve started to investigate this document with private collections of generic List type. Up for now, there are some places simillar to your example with [System.Diagnostics.Process](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessManager.Linux.cs#L30). In this example there is a List of type ProcessInfo initialized with default capacity equals to the length of process id array. New ProcessInfo objects are added to this list only if some condition is true, so when we replace this list with an array of length of process id array we could return some null values in our result array. Actually, we don't know the final length of array during initialization. Is this good approach? Please correct me, if I am mistaken.

**Comment by Petermarcu** [comment]
@danmosemsft , should we start labelling things like this with a performance label so we can search for these types of things? Its a common theme of many of the up for grabs issues.

**Comment by WinCPP** [comment]
@karelz @jamesqo Is this something that I can contribute in? Thanks.

**Comment by danmosemsft** [comment]
@stephentoub is such a substitution always a no-brainer, or are there caveats/measurements needed?

**Comment by stephentoub** [comment]
I'm going to close this.  It's not really actionable as-is.
