### ISSUE TITLE
LowLevelStack should not be necessary in TermInfo.cs

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#12591]
I noticed that there is a `LowLevelStack` class present in TermInfo.cs because, according to a comment, System.Console does not reference System.Collections: https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System/TermInfo.cs#L948

Seeing that `List<T>` is being used in the same file, maybe this is no longer true and the class can be removed.

**Comment by stephentoub** [comment]
Thanks. Yes, this should be removable now.  I believe it's a holdover from the early days of getting System.Console working on Unix.
