### ISSUE TITLE
Developer instructions for OSX are out of date with respect to OpenSSL

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#12608]
When following the developer instructions for OS X, I get to this step but get an error:
brew link --force openssl
Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib

Leading eventually to:

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.CryptoInitializer.EnsureOpen

This is my first modern mac ever in my office that I'm trying to actually use so some help would be appreciated!

**Comment by lextm** [comment]
The latest openssl steps can be found at https://www.microsoft.com/net/core#macos 

Of course someone should correct the steps here.

**Comment by karelz** [comment]
@MattGal where did you find the 'bad' instructions here?
@steveharter can you please help update the docs? (cc: @bartonjs)

**Comment by MattGal** [comment]
@karelz, specifically it's https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/Documentation/building/unix-instructions.md#L33 

I will try lextm's instructions shortly... I just am not familiar with the environment enough to follow the instructions in the brew error message.

**Comment by bartonjs** [comment]
Weird, I thought I sent this this morning, but apparently not.

https://github.com/dotnet/coreclr/blob/3acc1bf985e7bf4c038df1c68ac5c941954eafca/Documentation/building/osx-instructions.md#openssl is up to date.  Apparently we have a redundant copy in corefx that needs to be updated.  Thanks for pointing it out.

**Comment by karelz** [comment]
Do you plan to delete the CoreFX stale version and just link the one in CoreCLR repo?

**Comment by MattGal** [comment]
Thanks @bartonjs !  The previous instructions actually didn't help, so I really appreciate the redirection.

**Comment by mellinoe** [comment]
@MattGal Did you mean that the instructions here (https://www.microsoft.com/net/core#macos) did not work? If so, we should definitely try to fix that, since it's the main download portal.

**Comment by MattGal** [comment]
@mellinoe  Yes, they don't work for **building** corefx, but they may work fine for using it, which is what that portal seems to be for.

**Comment by mellinoe** [comment]
Ah, that is a good point. As long as they work for running stuff then there's no problem.

**Comment by MattGal** [comment]
Quick update... I tried the instructions from CoreCLR and get different errors, but still can't just call build.sh:

-- Configuring incomplete, errors occurred!
See also "/Users/mattgal/git/corefx/bin/obj/OSX.x64.Debug/Native/CMakeFiles/CMakeOutput.log".
See also "/Users/mattgal/git/corefx/bin/obj/OSX.x64.Debug/Native/CMakeFiles/CMakeError.log".
Failed to generate native component build project!
CMake Error at /usr/local/Cellar/cmake/3.6.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.6.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.6.2/share/cmake/Modules/FindOpenSSL.cmake:380 (find_package_handle_standard_args)
  System.Security.Cryptography.Native/CMakeLists.txt:15 (find_package)

**Comment by bartonjs** [comment]
@MattGal What branch are you building?  You need the change from https://github.com/dotnet/corefx/pull/12022, which is only in master.

**Comment by MattGal** [comment]
@bartonjs I'm trying this in master every time.  I tried the exact instructions off the head of master this morning and am getting the identical error above currently.

**Comment by bartonjs** [comment]
Okay, a housecall to MattGal's office showed that the problem was he didn't have pkgconfig, which makes cmake's find_package do only basic guesswork.

It probably doesn't make sense to have the OpenSSL dependency instructions in coreclr anymore; so I'll move them to corefx and merge in the "you need cmake (and pkgconfig)" portions from coreclr, too.
