### ISSUE TITLE
Adding an unique identifier for DbConnection

### ISSUE THREAD

**Issue by fitzchak** [dotnet/corefx#12615]
I purpose to add an unique identifier for DbConnection which will help support for tooling around the DbConnection, as the EntityFrameworkProfiler.

As of now, there is no way to associate a unique id with the connection. 

The `ClientConnectionId` of [SqlConnection](https://referencesource.microsoft.com/#System.Data/System/Data/SqlClient/SqlConnection.cs,667) is not what we ask as this is not unique for the connection itself.

So the purposing is simple, adding this to DbConnection:

private Guid identifier = Guid.NewGuid();

It can be private and we can access it with reflection, if making it public is problematic.

**Comment by nil4** [comment]
Wouldn't a [`ConditionalWeakTable<DbConnection, YourAssociatedData>`](https://msdn.microsoft.com/en-us/library/dd287757.aspx#Anchor_4) work for your use case?

**Comment by fitzchak** [comment]
@nil4 it will, but we want to avoid using it as ConditionalWeakTable is using locks and this will slow down the applications of our users.

**Comment by fitzchak** [comment]
Our product is (EntityFrameworkProfiler)[https://www.hibernatingrhinos.com/products/efprof]. The user is using it by calling EntityFrameworkProfiler.Initialize() by the very beginning of their application. In order to add support for Entity Framework Core v1.0 we track connections using the tracing infrastructure and adding just the ConnectionId to the connection will help us associate commands to the connection without slowing down the user application because of the locks in ConditionalWeakTable.

**Comment by saurabh500** [comment]
@fitzchak This problem can be extrapolated to any object and adding a guid to DbConnection will not solve this issue completely. 
A private guid seems like a very platform specific solution and hard to maintain
.Net core may implement it but other frameworks based on netstandard may not add this private guid. 

You can use `ObjectIDGenerator` to generate an Id for DbConnection.
@stephentoub @terrajobst  do you have any recommendations to make in this case ?

**Comment by fitzchak** [comment]
@saurabh500 We do need it just in .net core, as we have already support for the standard EntityFramework which uses the regular .net.

**Comment by saurabh500** [comment]
@fitzchak I am not in favor of adding a private members whose values will be accessed via reflection. Such code is not maintainable. 
I recommend using `ObjectIDGenerator` in these scenarios.

**Comment by fitzchak** [comment]
@saurabh500 I understand this very much.
In our use case ObjectIDGenerator won't help much as it isn't thread safe.
But we will use ConditionalWeakTable.

Note that I do think that a public ID should be exposed here as we show this connection in all the commends and other traces related to the connection (as the transactions) but there is no a build it way to identify the connection. Think about logging this... a unique connection ID is needed here.
