### ISSUE TITLE
System.Collections references non-shipping targetGroup for System.Runtime

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#12626]
I noticed today that System.Collections references a "netstandard1.7" targetgroup config of System.Runtime.
https://github.com/dotnet/corefx/blob/9eaf364b8ca8180bace20aab188b1efe6a55835f/src/System.Collections/src/System.Collections.csproj#L23

That's actually the default, and since S.R.builds doesn't contain a netstandard1.7 config we don't actually ship this dll.  We should remove targetgroup from the reference in System.Collections.

The TargetGroup/OSGroup settings on project references are really a huge pitfall.  We should try to clean these up.

/cc @weshaggard

**Comment by karelz** [comment]
Does it have to happen in 1.2? What's the implication if it doesn't? (i.e. is it a cleanup vs. must-fix bug)

**Comment by ericstj** [comment]
@karelz this will likely get addressed with our project reference refactoring for corefx as part of 1.2.

**Comment by karelz** [comment]
Do we have a tracking issue we could dupe this one against then?

**Comment by mellinoe** [comment]
I think this is going to be a moot point once we switch to our new build system. I'm going to close it as we probably won't bother fixing any issues like this in the old system when the new one is around the corner.
