### ISSUE TITLE
Investigate benefits of optimizing Enumerable.Cast for non-generic ICollections

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#12629]
Although `Enumerable.Cast` accepts a non-generic enumerable which are rare nowadays, it's used fairly often with generic enumerables in which the user knows that all of the objects are of a derived type. We should investigate to see if it is worthwhile optimizing the function for ICollections, e.g. the size of the array/list in `ToArray` / `ToList` can be predetermined.

Discussion moved from #12042

**Comment by jamesqo** [comment]
@VSadov, in response to one of your questions from the other thread

> If we really want to optimize behavior of Cast iterator and the way it composes with other operators, perhaps we should consider implementing IPartition, not just IIListProvider?

Implementing IPartition could be breaking for Cast followed by Skip / ElementAt / Last, since we may skip over an item that would have thrown an exception when we attempted to cast it. For example, consider

```cs
var objects = new object[] { 1, "string" };
foreach (string s in objects.Cast<string>().Skip(1)) ;
```

**Comment by VSadov** [comment]
@jamesqo - would this also be applicable to generic enumerables?  (like when downcasting from base to derived)
Is there a way to measure the effects of the improvement in the context of common scenarios?

**Comment by jamesqo** [comment]
> would this also be applicable to generic enumerables? (like when downcasting from base to derived)

Yes, this is applicable for generic enumerables. The collection type has to implement non-generic `ICollection` though, luckily that's common for most of the BCL containers such as List/Queue/ImmutableArray et al.

> Is there a way to measure the effects of the improvement in the context of common scenarios?

Yes, I can write a test app with enumerables of different types/sizes/etc. when the time comes & post perf results.

**Comment by karelz** [comment]
Next step: Collect perf data showing that this is worth it.

**Comment by stephentoub** [comment]
This is a theory about a potential perf improvement to potentially investigate. There are many such things that could be looked at... we don't need issues tracking them. If someone finds a performance improvement somewhere and wants to submit a PR for it, that's welcome.
