### ISSUE TITLE
Empty resx files cause ResourceManager to throw exception

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/corefx#12632]
If you create a resx without any resources in it then try a `ResourceManager.GetString` call that would have to consult that resx it will throw a `BadImageFormatException` with the message "Corrupt .resources file. Unable to read resources from this file because of invalid header information. Try regenerating the .resources file.".
## Expected Behavior

I would expect the ResourceManager to just not find any resources in there (meaning a MissingManifestResourceException), or at least give a more specific error message.
## Actual Behavior

A `BadImageFormatException` is thrown with an uninformative error message.

**Comment by danmosemsft** [comment]
I'm a bit confursed about the repro here. If I build a resx that is valid but has no resources, in desktop GetString returns null. 

The only place I see the message above in CoreFX is BadImageFormat_ResourcesHeaderCorrupted which doesn't seem to be used. 

Incidentally @alexperovich in a quick glance, src\System.Resources.ResourceManager\src\System\Resources\ResourceManager.cs seems to be much less complete than the one in desktop, which ultimately returns null here I think: http://index/#mscorlib/system/resources/runtimeresourceset.cs,8237526a2c744be5

**Comment by ryanbrandenburg** [comment]
Strange, I get that error message on both desktop and Core. I've made a repro app [here](https://github.com/ryanbrandenburg/EmptyResourceTestApp), do you get the described behavior when running that?

**Comment by ramarag** [comment]
@ryanbrandenburg this issue actually is because or a bug in resource generation by cli.
The bug seems to be fixed in the latest build of cli [ The one with csproj and based on msbuild] https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/Latest/dotnet-win-x86.latest.zip

I am not sure if this will be fixed in the cli that used to be  work with  project.json
@piotrpMSFT  can you comment on this ?

**Comment by ramarag** [comment]
@danmosemsft the behavior you are talking about only occurs if the neutral culture resources are available.

more info on the current behavior at https://msdn.microsoft.com/en-us/library/system.resources.missingmanifestresourceexception(v=vs.110).aspx#Anchor_6

**Comment by ryanbrandenburg** [comment]
Thanks @ramarag!
