### ISSUE TITLE
[Impl] Port Implementation of System.Xml.XmlMtomReader/XmlMtomWriter 

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#12638]

**Comment by karelz** [comment]
@shmao is it for netstandard2.0? In such cases we do not use "api-needs-work" label.

**Comment by shmao** [comment]
@karelz Thanks for fixing the label. Yes, this is for netstandard2.0. The API has been exposed in NetCore. But the implementation code has not been ported yet. We wanted to use the issue for tracking porting the implementation and adding test coverage for the API. What's the right label we should use in this case?

**Comment by karelz** [comment]
netstandard2.0 label is sufficient. NS2.0 is special project enough, that we do not need to capture more nuances of various work items via additional labels - it would be just unnecessary bureaucracy IMO.
api-* labels are meant mainly for APIs which need to go through API review (not this case).

**Comment by shmao** [comment]
Got it. Thanks for the guidelines, @karelz .

**Comment by shmao** [comment]
@mconnew suggested to remove IXmlMtomReaderInitializer/IXmlMtomWriterInitializer from NetStandard2.0 since WCF would not support MtomReader/Writer.

**Comment by karelz** [comment]
Please work with @weshaggard on decisions what is / is not in netstandard2.0.
cc: @danmosemsft

**Comment by weshaggard** [comment]
Removing is something we could entertain but we would need to look at some data and ensure these don't break other APIs that are part of the standard. If you would like to do that please file and issue on dotnet\standard with the full API list and supporting data.

**Comment by karelz** [comment]
It would be also good to understand the motivation. Xamarin considered the API useful to take. What is the value of not having it in standard?

**Comment by shmao** [comment]
WCF is the only consumer of this MTOM encoder. As WCF is not going to support MTOM on NetCore, having these APIs in Core doesn't provide actual value.

@mconnew , do you want to chime in here?

**Comment by mconnew** [comment]
If you check the documentation for [XmlDictionaryWriter.CreateMtomWriter](https://msdn.microsoft.com/en-us/library/system.xml.xmldictionarywriter.createmtomwriter(v=vs.110).aspx) on msdn, under remarks it says: 
> MTOM allows users to optimize the transmission of raw binary data within SOAP messages. 

It's only use is with SOAP message and only used by WCF. MTOM isn't supported by WCF in .Net core, and to add support would require a major rewrite in order to support it as our Http transport has changed significantly due to migrating across to HttpClient from HttpWebRequest.  
WCF isn't a part of the .Net Standard api's even though Xamarin has many WCF api's available. Although these api's are part of an assembly which is part of .Net Standard, they go along with WCF which isn't.

**Comment by karelz** [comment]
Sounds good to me. Please work with @weshaggard on final decision.

**Comment by danmosemsft** [comment]
Decision should be logged in https://github.com/dotnet/standard issue

**Comment by zhenlan** [comment]
@shmao can you please open issue in dotnet/standard repo so folks can make final decision if these MTOM APIs should be removed from NS 2.0.?

**Comment by shmao** [comment]
Opened https://github.com/dotnet/standard/issues/78 for tracking this. @zhenlan

**Comment by danmosemsft** [comment]
Seems Wes will remove these.

**Comment by danmosemsft** [comment]
Didn't mean to close.

**Comment by shmao** [comment]
Sounds good. I will remove them from NetCore.

**Comment by felipecaputo** [comment]
Hi there,

I know this is an old issue, but Mtom feature is quite important to us, and I'ld like to know if it need just the Reader and Writer or there is more to do to support Mtom in .net core 2.0.

If not I would love to help to get this done!

**Comment by shmao** [comment]
@felipecaputo can you please share some sample code with us for how you used the Mtom feature in your application?

**Comment by johntobia** [comment]
I realize this is an old thread, but this is important to my company also.  It's one of our only blockers moving to .NET Core.  We have a document management platform that returns large documents using MTOM.  We have successfully written a wrapper using the XmlMtomReader class (and all other related / needed classes).  We really just need XmlMtomReader and XmlMtomWriter ported to .NET Core.  I realize that the WCF stuff is more involved, but we have also already converted that part to use HttpClient.

**Comment by felipecaputo** [comment]
Hi @shmao sorry for taking more than a year to notice your reply, but we use it to transfer large documents to a lawsuite webservice

        protected void configurarServico()
        {
            BasicHttpBinding bind = new BasicHttpBinding();
            EndpointAddress endpoint = new EndpointAddress(Endpoint);

            bind.MessageEncoding = WSMessageEncoding.Mtom;
            bind.Name = "ServicoMPHttpBinding";
            bind.AllowCookies = true;
            bind.MaxReceivedMessageSize = int.MaxValue;
            bind.SendTimeout = TimeSpan.FromMinutes(30);
            bind.ReceiveTimeout = TimeSpan.FromMinutes(30);
    }

The imported WSDL was imported as bellow:

        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> peticionarIntermediariaMTOMAsync(string in0, byte[] in1);

And the code that calls the webservice:

            var task = this.servico.peticionarIntermediariaAsync(xml, obterDocumentoBase64(documentos));
            task.Wait();
            return task.Result;
