### ISSUE TITLE
System.Xml.ReaderWriter encoding test failure

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#1263]
The test failed on @Maxwe11 's machine but did pass on mine. I saw similar issue appearing from time to time on some remote machines but could never repro locally.

@Maxwe11 provided with following info:
OS: Win 8.1 64-bit
Culture: uk-UA

```
  Discovering: System.Xml.RW.XmlWriter.Tests
  Discovered:  System.Xml.RW.XmlWriter.Tests
  Starting:    System.Xml.RW.XmlWriter.Tests
     XmlWriterTests.WriteWithEncoding [FAIL]
        Assert.Equal() Failure
                                    (pos 17)
        Expected: <orderID>1-456-ab&#x661;</orderID><orderID>2-36-00a&#x1000תתת
        Actual:   <orderID>1-456-ab\n</orderID><orderID>2-36-00a&#x10000;&#x1תתת
                                    (pos 17)
        Stack Trace:
           d:\corefx-krwq\src\System.Xml.ReaderWriter\tests\XmlWriter\WriteWithEncoding.cs(36,0): at XmlWriterTests.WriteWithEncoding()
  Finished:    System.Xml.RW.XmlWriter.Tests
```

**Comment by krwq** [comment]
I wasn't able to repro after changing locale on my computer (intl.cpl -> Format and Administrative tabs)

**Comment by Maxwe11** [comment]
It fails from time to time, not all the time (I've checked it with enabled test).

**Comment by akoeplinger** [comment]
fwiw, I've seen this as well here when I quickly tried it, but it just happened once and even running the test in a `while(true)` for some minutes didn't repro it again...

**Comment by krwq** [comment]
Did you try to run it in different threads in `while(true)`? It might be some race condition. I just changed my locale again and will play around with this test a little bit more

**Comment by krwq** [comment]
Ok, found the issue.

In System.Text.Encoding.CodePages inside:
`src\System.Text.Encoding.CodePages\src\System\Text\SBCSCodePageEncoding.cs`

we do (method LoadManagedCodePage):
```csharp
byte* pNativeMemory = GetNativeMemory(65536 * 1 + 256 * 2 + 4 + iExtraBytes);
```
Is assumind that memory should be initialized with zeros and it is not since the method is using Marshal.AllocHGlobal which doesn't guarantee that.

After initializing it to zeros I didn't get the same problem again and I'm already running it for a while.

It might not be the issue but it does resolve this problem.

+ @tarekgh to verify if that is the problem.

**Comment by tarekgh** [comment]
Thanks Krzysztof. I am pretty sure this was the issue and we should be fine after fixing it.

**Comment by krwq** [comment]
@Maxwe11 & @akoeplinger , could you test if you are having any failures after merging this locally:
https://github.com/dotnet/corefx/pull/1493 ?

**Comment by akoeplinger** [comment]
@krwq I tried it and it passed (but I couldn't reliably repro before, so may not be meaningful). The fix looks good to me.

**Comment by krwq** [comment]
I previously reproed by literally:
```
:a
corerun xunit.console.netcore.exe System.Xml.RW.XmlWriter.Tests.dll
goto a
```
and modifying a test so it does something like:
```
bool restart = false;
do
{
  // test code
  // if (failed)
  // restart = true
}
while (restart);
```
so once I get a failure I can attach a debugger at any time (it repros per exe run and not per test run)

**Comment by akoeplinger** [comment]
@krwq thanks for the pointer, I was able to reliably repro it now before the fix and not after, so looks good :+1:

**Comment by Maxwe11** [comment]
:+1:
