### ISSUE TITLE
Improve "dynamic" performance

### ISSUE THREAD

**Issue by Opiumtm** [dotnet/corefx#12643]
`dynamic` feature today have extremely awful performance.
Dynamic typing in .NET languages (C#, VB) isn't used much, mostly because of intolerable slow performance and some bugs in implementation (there are memory leaks in dynamics, for example).

Some third-party libraries provide fast reflection based on IL emit at runtime to have fast access to object members. Even standard reflection API provide means to create fast delegates to invoke at runtime:
[MethodInfo.CreateDelegate](https://msdn.microsoft.com/en-us/library/hh194376%28v=vs.110%29.aspx)

Performance measurement of `dynamic` reveal that it doesn't cache delegates and indeed is very unoptimized. [MethodInfo.CreateDelegate](https://msdn.microsoft.com/en-us/library/hh194376%28v=vs.110%29.aspx) provide performance almost as fast as direct call to a method (there is some performance penalty on delegate creation, but invocation of created delegate is almost free - so it can created on first invoke and then can be cached). `dynamic` is very much slower on subsequent method calls, although it can cache method invokes using `CreateDelegate`. Same performance improvements should be applied on other `dynamic` features. Dynamic method invocation is just an example of how it should be improved.

**Comment by svick** [comment]
> there are memory leaks in dynamics, for example

Could you point out where exactly are the memory leaks? Are there issues for them?

> Performance measurement of `dynamic` reveal that it doesn't cache delegates and indeed is very unoptimized.

Could you share those measurements (including the measured code)?

**Comment by Opiumtm** [comment]
@svick Here are benchmarks:
https://github.com/Opiumtm/CodeExamples/tree/master/ReflectionBenchmark

Benchmark results (UWP .NET Core Release x64). It **isn't** compiled using .NET Native toolchain.
```
Scenario set "Dynamic calls"
=======================================================
.NET direct call: run count = 100000000, totalTime(ms) = 375, time per run(microsec) = 0.0038
Interface cast call: run count = 100000000, totalTime(ms) = 812, time per run(microsec) = 0.0081, % to baseline = 216.53%
Reflection invoke call: run count = 1000000, totalTime(ms) = 1281, time per run(microsec) = 1.2810, % to baseline = 34160.00%
Reflection cached delegate invoke call: run count = 100000000, totalTime(ms) = 469, time per run(microsec) = 0.0047, % to baseline = 125.07%
Dynamic invoke call: run count = 1000000, totalTime(ms) = 5469, time per run(microsec) = 5.4690, % to baseline = 145840.00%
Switch dispatch call: run count = 1000000, totalTime(ms) = 32, time per run(microsec) = 0.0320, % to baseline = 853.33%
Dictionary dispatch call: run count = 1000000, totalTime(ms) = 172, time per run(microsec) = 0.1720, % to baseline = 4586.67%
```

Most interesting results here are (for a case we're talking about):
```
.NET direct call: run count = 100000000, totalTime(ms) = 375, time per run(microsec) = 0.0038
Dynamic invoke call: run count = 1000000, totalTime(ms) = 5469, time per run(microsec) = 5.4690, % to baseline = 145840.00%
Reflection cached delegate invoke call: run count = 100000000, totalTime(ms) = 469, time per run(microsec) = 0.0047, % to baseline = 125.07%
```

"Dynamic" call scenario is:
```C#
    /// <summary>
    /// Dynamic call scenario.
    /// </summary>
    public sealed class DynamicCallScenario : IScenario
    {
        public string ScenarioName => "Dynamic invoke call";

        public async Task<BenchmarkResult> DoBenchmark()
        {
            var task = Task.Factory.StartNew(RunBenchmark);
            return await task;
        }

        private BenchmarkResult RunBenchmark()
        {
            dynamic callable = new CallableClass();
            var ticks1 = Environment.TickCount;
            for (var i = 0; i < Consts.RunCount; i++)
            {
                CallDynamic(callable, i);
            }
            var ticks2 = Environment.TickCount;
            return new BenchmarkResult() { RunCount = Consts.RunCount, Milliseconds = ticks2 - ticks1 };
        }

        private void CallDynamic(dynamic callableObj, int i)
        {
            callableObj.Run();
            callableObj.RunWithArgs(i, "");
        }
    }
```

Reflection cached delegate scenario is:
```C#
    /// <summary>
    /// Reflection delegate call scenario.
    /// </summary>
    public sealed class ReflectionDelegateCallScenario : IScenario
    {
        public string ScenarioName => "Reflection cached delegate invoke call";

        public async Task<BenchmarkResult> DoBenchmark()
        {
            var task = Task.Factory.StartNew(RunBenchmark);
            return await task;
        }

        private BenchmarkResult RunBenchmark()
        {
            ICallableInterface callable = new CallableClass();
            var ticks1 = Environment.TickCount;
            Func<int> cache1 = null;
            Func<int, string, int> cache2 = null;

            for (var i = 0; i < Consts.RunCount * 100; i++)
            {
                CallReflection(callable, i, ref cache1, ref cache2);
            }
            var ticks2 = Environment.TickCount;
            return new BenchmarkResult() { RunCount = Consts.RunCount*100, Milliseconds = ticks2 - ticks1 };
        }

        private static readonly TypeInfo InterfaceTypeInfo = typeof(ICallableInterface).GetTypeInfo();

        private static readonly MethodInfo RunTypeInfo = InterfaceTypeInfo.GetDeclaredMethod(nameof(ICallableInterface.Run));

        private static readonly MethodInfo RunWithArgsTypeInfo = InterfaceTypeInfo.GetDeclaredMethod(nameof(ICallableInterface.RunWithArgs));

        private void CallReflection(object callableObj, int i, ref Func<int> cache1, ref Func<int, string, int> cache2)
        {
            if (cache1 == null)
            {
                cache1 = RunTypeInfo.CreateDelegate(typeof (Func<int>), callableObj) as Func<int>;
            }
            if (cache2 == null)
            {
                cache2 = RunWithArgsTypeInfo.CreateDelegate(typeof(Func<int, string, int>), callableObj) as Func<int, string, int>;
            }
            cache1();
            cache2(i, "");
        }
    }
```

Basline plain .NET method invoke, time per run(microsec) = 0.0038
Invoke of a method at `dynamic` variable, time per run(microsec) = 5.4690, **% to baseline = 145840.00%**
Cached reflection delegate invoke (create delegate from MethodInfo and then cache it), time per run(microsec) = 0.0047, % to baseline = 125.07%

So, as you can see, create delegate from MethodInfo is only 25% slower. Invoke method from `dynamic` is hugely slower, intolerably slow!

**Comment by Opiumtm** [comment]
@svick 
And same test compiled using .NET Native toolchain

```
Scenario set "Dynamic calls"
=======================================================
.NET direct call: run count = 100000000, totalTime(ms) = 203, time per run(microsec) = 0.0020
Reflection cached delegate invoke call: run count = 100000000, totalTime(ms) = 578, time per run(microsec) = 0.0058, % to baseline = 284.73%
Dynamic invoke call: run count = 1000000, totalTime(ms) = 10578, time per run(microsec) = 10.5780, % to baseline = 521083.74%
```

On .NET Native `dynamic` performs even worse.

**Comment by karelz** [comment]
We are fine to take targeted perf improvements in the area which do not break existing code -- please file separate issues for those.
However, doing a major surgery on the code base would be super-hard / impossible to do in a compatible way. It is not worth the trouble.
Closing this issue as it tries to track either the large surgery we do not want, or multiple small things - file them either separately as issues or submit (small) PRs, but make sure prior to submitting (small) PR things are compatible, otherwise PRs will be rejected.

Also note that the code coverage of the area is not great, we might need to block accepting PRs on better code coverage first.
