### ISSUE TITLE
SocketAsyncEventArgs allocates unnecessary SafeHandles

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12659]
Every operation on a SocketAsyncEventArgs ends up allocating a SafeNativeOverlapped SafeHandle:
https://github.com/dotnet/corefx/blob/2117bae3a6c9736033e6d1659821ff3a1069920b/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Windows.cs#L160

This is adding a significant amount of overhead to networking operations that are trying to be optimized via SocketAsyncEventArgs, e.g. in a benchmark that downloads from a localhost server 100MB via ReceiveAsync calls on a SocketAsyncEventArgs instance, we end up allocating almost 20K SafeNativeOverlapped instances for over 800KB of memory!

These SafeHandles are just being stored into a field on the SocketAsyncEventArgs.  Rather than allocating a SafeHandle for each, there are a variety of options, such as making the SocketAsyncEventArgs itself finalizable, or reusing the same SafeHandle and just replacing the pointer it guards.

cc: @davidsh, @cipop, @ericeil

**Comment by davidfowl** [comment]
Wow
