### ISSUE TITLE
Add uap10.1 configuration to System.Diagnostics.Tracing

### ISSUE THREAD

**Issue by SedarG** [dotnet/corefx#12652]
Related with #12013

**Comment by SedarG** [comment]
This is currently blocked because S.D.Tracing can't be built even targeting netcore50aot. 
https://github.com/dotnet/corefx/commit/7ed55c8e4114770f0705b82d856d97d08568de2a and https://github.com/dotnet/corefx/commit/0521ba9f809de30e4d8325b3833b4a9ae0ab50d8 brought some codepaths that weren't in netcore50aot before to be included now, and the new code paths are causing build errors.

i.e. System.Diagnostics.Tracing.EventProvider doesn't expose GetSessionID in https://www.nuget.org/api/v2/package/runtime.aot.System.Diagnostics.Tracing/4.0.20, however it's currently being included in netcore50aot because [this change] (https://github.com/dotnet/corefx/commit/7ed55c8e4114770f0705b82d856d97d08568de2a#diff-6297202ae90c801849f5f3671c122363L35) removes `#if ES_SESSION_INFO || FEATURE_ACTIVITYSAMPLING`, which was previously preventing that block from getting compiled in netcore50aot. and now it's yielding to various build errors.

@davmason , could you please take a look. I need your help in resolving the netcore50aot issue. Once it's done, I can continue with the changes to add uap101 configuration.

**Comment by joperezr** [comment]
Master today has both a configuration for uap and one for uapaot now, so this should be unblocked.

**Comment by brianrob** [comment]
System.Diagnostics.Tracing is now implemented in System.Private.CoreLib.
