### ISSUE TITLE
Add tests for new String.Join overloads

### ISSUE THREAD

**Issue by AlexGhiondea** [dotnet/corefx#12655]
Once dotnet/coreclr/pull/7621 makes its way over to CoreFx, we need to add tests for the new APIs.

**Comment by hughbe** [comment]
I'll take this once we update the core CLR dependencies here

**Comment by AlexGhiondea** [comment]
@hughbe that is great! I assigned the issue to you!

**Comment by AlexGhiondea** [comment]
@hughbe, it looks like @jamesqo has taken over that work and filed https://github.com/dotnet/coreclr/pull/7942 for it.

**Comment by AlexGhiondea** [comment]
@jamesqo, @hughbe  let me know if any of you are planning to add tests in CoreFx side for this.

**Comment by hughbe** [comment]
Yeah I agreed with James he'd implement and test

**Comment by AlexGhiondea** [comment]
@hughbe and @jamesqo  thank you! :)

**Comment by AlexRadch** [comment]
I am working on this PR

**Comment by karelz** [comment]
@AlexGhiondea isn't it tracking same thing as #5552?

**Comment by AlexRadch** [comment]
@karelz Yes. It is the same thing

**Comment by karelz** [comment]
Closing as dupe of #5552.
