### ISSUE TITLE
Machine wide IsolatedStorage stores don't have same access rights on Unix 

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#12660]
Common app data has an underlying issue #12628. If we're able to come up with a workable solution we should look at getting rights set up for [Unix](https://github.com/dotnet/corefx/blob/master/src/System.IO.IsolatedStorage/src/System/IO/IsolatedStorage/Helper.Win32.Unix.cs#L52).

Note that the current implementation is up to the bar of the current Mono implementation for machine stores. Additionally note that we don't have a public way to set rights yet on Unix. Some tracking issues: #3186, #9225

**Comment by mellinoe** [comment]
Don't we use a machine-wide storage location in some parts of crypto? Perhaps I'm mis-remembering that part. @bartonjs

**Comment by JeremyKuhne** [comment]
The parent issue (#12628) discusses the rights that need to be set and we've been doing that with P/Invoke elsewhere in the libraries.

**Comment by JeremyKuhne** [comment]
Duplicate of #12628
