### ISSUE TITLE
Avoid byte[] allocations once IPAddress.Address is back

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12662]
#12658 is adding back IPAddress.Address.  Various parts of the code end up allocating a byte[] to work around the lack of IPAddress.Address in the public surface area, e.g.

https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/Common/src/System/Net/SocketAddress.cs#L110-L116
Once the packages have been updated with this property, we should fix those locations appropriately to avoid the unnecessary allocations.

**Comment by stephentoub** [comment]
I fixed a few of these already, e.g. https://github.com/dotnet/corefx/pull/16495, but there are still a handful more to be addressed.

**Comment by WinCPP** [comment]
@karelz I think I can work on this one as well...

**Comment by karelz** [comment]
Assigned to you @WinCPP.

**Comment by WinCPP** [comment]
@stephentoub I'm still getting the warning in intellisense. Looks like the packages have not been updated...? So should I do the changes using pragma warning disable + restore, just as you have done in #16495 or, should this issue be deferred until we have the packages in...?

```C#
"This property has been deprecated. It is address family dependent. Please use IPAddress.Equals method to perform comparisons. http://go.microsoft.com/fwlink/?linkid=14202"
```
Also, I think I see only two places to fix in CoreFx repo. Hope I am not missing something here... Thanks.

**Comment by stephentoub** [comment]
> I'm still getting the warning in intellisense. Looks like the packages have not been updated...? 

The "obsolete" warning?  The member was added back, but it's still marked as obsolete.  So places where we use it, we'll need to use pragmas to suppress the warning.

**Comment by WinCPP** [comment]
@stephentoub yeah the obsolete warning... ok. I thought my code base didn't have recent packages which was giving me the warnings. Will add the suppression lines. Thanks.
