### ISSUE TITLE
Add missing ISerializable

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#12669]
The following should implement ISerializable per NS2.0, but in .NET Core they do not:

- [ ] System.ApplicationIdentity
- [x] System.ComponentModel.Win32Exception
- [x] System.Exception
- [x] System.IO.DriveInfo
- [x] System.IO.FileSystemInfo
- [x] System.IntPtr
- [x] System.Net.CookieException
- [x] System.Net.HttpWebRequest
- [x] System.Net.HttpWebResponse
- [x] System.Net.ProtocolViolationException
- [x] System.Net.WebException
- [ ] System.Net.WebHeaderCollection
- [x] System.OperatingSystem
- [ ] System.Runtime.Remoting.Messaging.LogicalCallContext
- [ ] System.Runtime.Remoting.Messaging.MethodCall
- [ ] System.Runtime.Remoting.Messaging.MethodResponse
- [x] System.Security.Cryptography.X509Certificates.X509Certificate
- [x] System.Text.StringBuilder
- [ ] System.Threading.ExecutionContext
- [x] System.UIntPtr

**Comment by danmosemsft** [comment]
@AlexGhiondea fyi.. some of these types we haven't ported yet, so it's more about the ones we already have, like StringBuilder. Maybe a good task for the new hire.

**Comment by stephentoub** [comment]
This is essentially done now.  Of all of those remaining, all but one haven't been ported at all, so when they are, their serialization implementation should be brought along for the ride.  That just leaves WebHeaderCollection, which will be handled as part of finishing https://github.com/dotnet/corefx/issues/12725.
