### ISSUE TITLE
Will there be X509Certificate2.Verify method?

### ISSUE THREAD

**Issue by hlubovac** [dotnet/corefx#12661]
Referring to https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Certificate2.cs#L12

Compared to .NET 4, this method is missing; see: https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.x509certificate2.verify(v=vs.110).aspx

Thanks.

**Comment by karelz** [comment]
@steveharter @bartonjs is it part of netstandard2.0?

**Comment by hlubovac** [comment]
I don't know if this is equivalent (or even entirely correct), but in the meantime I found that this works:

           X509Certificate2 certificate = ...

            var chain = new X509Chain();
            chain.ChainPolicy.RevocationFlag = X509RevocationFlag.EntireChain;
            chain.ChainPolicy.RevocationMode = X509RevocationMode.Offline;
            chain.ChainPolicy.VerificationFlags =
                X509VerificationFlags.IgnoreCtlSignerRevocationUnknown |
                X509VerificationFlags.IgnoreRootRevocationUnknown |
                X509VerificationFlags.IgnoreEndRevocationUnknown |
                X509VerificationFlags.IgnoreCertificateAuthorityRevocationUnknown |
                X509VerificationFlags.IgnoreCtlNotTimeValid;

            bool valid = chain.Build(certificate);

**Comment by steveharter** [comment]
Yes, the Verify will be added via #12295. Thanks
