### ISSUE TITLE
Cleanup <NoWarn>0436</NoWarn> from all .csproj files

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#12678]
This warning suppression is needed because of duplicated implementations between coreclr and corefx. We should clean them up - remove (or hide via model.xml) the conflicting implementation in System.Private.CoreLib.

**Comment by jkotas** [comment]
@rahku Could you please take a look at it when you get a chance? A lot of them are coming from duplicate AppDomain, etc. types in System.Runtime.Extensions.

**Comment by jkotas** [comment]
This should fix https://github.com/dotnet/corefx/issues/5540 as well.

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/issues/12850

**Comment by danmosemsft** [comment]
@rahku are you planning to do this? Is this important for 2.0? As far as I can see it's not (but we should do it)

If it is important for 2.0 and you plan to do it please move back.

**Comment by jkotas** [comment]
We need to make sure that there are no duplicate public types between System.Private.CoreLib and CoreFX. It is important for 2.0.0 because:
- Past experience tells us that the duplication can be hiding bugs
- We have promised Roslyn team to clean this up for 2.0 to C# scripting work well

**Comment by jkotas** [comment]
This is blocked by https://github.com/dotnet/coreclr/issues/8937. Once it is fixed, I will be happy to take care of if nobody else can. There is not that much left to do.

**Comment by rahku** [comment]
Jan I will take care of this next week. Sorry for the delay

**Comment by rahku** [comment]
List of public types in corefx which are duplicate in corelib
--------------
f:\temp\System.ComponentModel.TypeConverter.dll:
Timer 

f:\temp\Microsoft.CSharp.dll:
Binder 

f:\temp\System.Threading.dll:
CountdownEvent 

f:\temp\Microsoft.Diagnostics.Tracing.TraceEvent.dll:
SuppressUnmanagedCodeSecurityAttribute 
AllowReversePInvokeCallsAttribute 
EntryPointNotFoundException 
ApplicationException 

f:\temp\System.Collections.NonGeneric.dll:
CollectionBase 

f:\temp\System.Collections.dll:
StructuralComparisons 

f:\temp\System.Runtime.Extensions.dll:
Environment 

f:\temp\System.Reflection.Metadata.dll:
AssemblyHashAlgorithm 

f:\temp\System.ComponentModel.dll:
IServiceProvider 

f:\temp\System.DirectoryServices.Protocols.dll:
SearchOption 
SortKey 

f:\temp\System.Diagnostics.Process.dll:
ThreadState 

f:\temp\System.IO.FileSystem.dll:
SearchOption 

f:\temp\System.Runtime.dll:
RuntimeReflectionExtensions 
SpecialNameAttribute 

f:\temp\System.ObjectModel.dll:
KeyedCollection`2 
ReadOnlyDictionary`2 

f:\temp\System.Reflection.TypeExtensions.dll:
AssemblyExtensions 

f:\temp\System.Runtime.CompilerServices.VisualC.dll:
CompilerMarshalOverride 

f:\temp\System.Runtime.Serialization.Formatters.dll:
FormatterServices 

f:\temp\System.Security.Permissions.dll:
SecurityState 

f:\temp\System.ServiceProcess.ServiceController.dll:
TimeoutException 

f:\temp\System.Threading.Thread.dll:
Thread 
ThreadAbortException 

f:\temp\xunit.abstractions.dll:
ITypeInfo

**Comment by jkotas** [comment]
> Timer

They are in difference namespaces (System.Threading.Timer vs. System.Timers.Timer), so this one is by design. 

> xunit.abstractions.dll

Outside our control - nothing to do.

**Comment by rahku** [comment]
yeah i filtering those out...should have updated list soon

**Comment by rahku** [comment]
List of public types in corefx which have duplicates in corelib
--------------------
f:\temp\System.Threading.dll:
CountdownEvent 

f:\temp\Microsoft.Diagnostics.Tracing.TraceEvent.dll:
SuppressUnmanagedCodeSecurityAttribute 
AllowReversePInvokeCallsAttribute 
EntryPointNotFoundException 
ApplicationException 

f:\temp\System.Collections.NonGeneric.dll:
CollectionBase 

f:\temp\System.Collections.dll:
StructuralComparisons 

f:\temp\System.Runtime.Extensions.dll:
Environment 

f:\temp\System.Reflection.Metadata.dll:
AssemblyHashAlgorithm 

f:\temp\System.ComponentModel.dll:
IServiceProvider 

f:\temp\System.IO.FileSystem.dll:
SearchOption 

f:\temp\System.Runtime.dll:
RuntimeReflectionExtensions 
SpecialNameAttribute 

f:\temp\System.ObjectModel.dll:
KeyedCollection`2 
ReadOnlyDictionary`2 

f:\temp\System.Runtime.CompilerServices.VisualC.dll:
CompilerMarshalOverride 

f:\temp\System.Runtime.Serialization.Formatters.dll:
FormatterServices 

f:\temp\System.Security.Permissions.dll:
SecurityState 

f:\temp\System.Threading.Thread.dll:
Thread 
ThreadAbortException

**Comment by rahku** [comment]
ignoring duplicates in Microsoft.Diagnostics.Tracing.TraceEvent.dll. This is not a corefx dll.
AssemblyHashAlgorithm in System.Reflection.Metadata.dll is not part of reference/contract dll. And is in a different namespace. So ignoring that as well.

**Comment by rahku** [comment]
Rest all the above types have been made internal or removed from corelib
