### ISSUE TITLE
Make Decimal.GetBits(decimal d, byte[])

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#12673]
@davidfowl commented on [Sat Sep 17 2016](https://github.com/dotnet/coreclr/issues/7247)

Would make it easier to write data to an existing buffer that way.

**Comment by karelz** [comment]
We need formal API proposal now.

**Comment by jkotas** [comment]
Dup of https://github.com/dotnet/corefx/issues/12672
