### ISSUE TITLE
.NET Core for web

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/corefx#1267]
Hello everyone!

I'm a C# dev, and I'm also one of those who invested long time in Silverlight and XAML, and shipped gorgeous apps with it. Mostly LoB applications.

As the plugin era is over, and with the death of Silverlight, JS got great glory back again.
Silverlight and RIA services and controls (can you believe that trend is gone!?), and the app development in C#-XAML (will refer to it as CX), cross-platform apps we had in WPF, WinRT, and especially Silverlight (OOB, RIA services!!, member?), is now all history, and developing cross-platform apps is not out-the-box at all, if you wanna use C# and XAML (yeah, I know about Xamarin, you surely can't call it out the box).
HTML, CSS and JS are hard-coded languages by nature. They will always suck. Nothing will ever make it even close to the CX match.

But now, that .NET core was open-sourced, a .NET core version for JS-enabled systems, i.e. web-browsers is now really an option, with the aid of TypeScript.

And there are two parts to it.
 - The availability of the .NET Core (at least the client-library that was supplied with SL - as a beginning).
 - An engine that compiles XAML to appropriate HTML5+CSS3, and that's on top and works with the JS BCL.

Both these tools have been worked on, in many projects, but no project target this goal: Make C# and XAML available for web applications.
In the JS to .NET field, there are [JSIL](https://github.com/sq/JSIL) and [NetJs](https://github.com/praeclarum/Netjs) among others.
And in the XAML field, there is the awesome [Fayde](https://github.com/wsick/Fayde) project, that converts XAML to HTML5 and CSS3, but in the other hand uses TypeScript as the backing language.

Please share your ideas here or on [this](https://github.com/CXeverywhere/CXeverywhere) repo. I'm curious whether people have interest in this.

**Comment by ellismg** [comment]
I think this conversation may be a better fit for the [.NET Foundation Forums](http://forums.dotnetfoundation.org/).

**Comment by ellismg** [comment]
I'm going to close this issue.  We'd rather not track these long lead efforts as issues in CoreFX, especially in cases where we don't ourselves driving the work.

I think your repo or the .NET Foundation Forums are better places for folks that are passionate about this scenario to figure out a long term plan and execute on it.

**Comment by weitzhandler** [comment]
@ellismg agreed thanks.

**Comment by weitzhandler** [comment]
@ellismg Agreed.

[Here](http://forums.dotnetfoundation.org/t/net-core-web/1007?u=shimmy) is the post, thanks.
