### ISSUE TITLE
Investigate using List.ConvertAll for SelectListIterator.ToList

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#12686]
This code: https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Select.cs#L330

Could probably use the little-known [`List.ConvertAll`](https://msdn.microsoft.com/en-us/library/73fe8cwf%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) api instead, which basically does the exact same thing as `list.Select(...).ToList()` except it [indexes directly into the backing array](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/List.cs#L345) instead of using `Add` and sets _size at the end, which is likely faster since `Add` currently isn't inlined.

A drawback, however, is that the method accepts a `Converter<T, TOutput>` instead of a Func, so unless there's a way from one delegate type to another which I'm not aware of we may have to pay for an additional allocation.

**Comment by karelz** [comment]
cc: @VSadov

**Comment by VSadov** [comment]
@jamesqo - do you want to take care of this? 
Do you think it is possible/profitable optimization considering that you cannot directly pass the func?

**Comment by jamesqo** [comment]
@VSadov, have thought about this some more. Since we have to wrap the func in another func, there will be an extra layer of indirection per method call which will outweigh Add being inlined. Plus, we have to allocate a closure to make this work. Perhaps this can be revisited if `ConvertAll(Func<...>)` is added in the future, but for now I'm closing.
