### ISSUE TITLE
Investigate preallocating space for ICollections/IIListProvider in SelectEnumerableIterator methods

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#12702]
SelectEnumerableIterator's `IIListProvider` implementation, e.g. `ToArray`, `ToList`, etc. should attempt to preallocate space if the source is an ICollection or IIListProvider. We check before falling back to that iterator if the input is an IList or IPartition, but not if it's one of the parent interfaces.

**edit:** Adding 'investigate' b/c I'm not sure how common a non-IList ICollection is, or a non-IPartition IIListProvider is. In addition, this may penalize (even if slightly) if the source is neither of those.

**Comment by karelz** [comment]
cc: @VSadov

**Comment by VSadov** [comment]
Might not be hard to implement, but need to be sure there is a noticeable positive impact in common scenarios.

**Comment by stephentoub** [comment]
This is a theory about a potential perf improvement to potentially investigate.  There are many such things that could be looked at... we don't need issues tracking them.  If someone finds a performance improvement somewhere and wants to submit a PR for it, that's welcome.
