### ISSUE TITLE
Creating new X509Certificate2 instance crashes CLR in Azure AppServices environment

### ISSUE THREAD

**Issue by pakrym** [dotnet/corefx#12704]
**Issue:**
Creating instance of X509Certificate2 using ctor(sting, string) overload causes CLR to crash without exception being printed and exit code `-1073740940`. Reproduces only in Azure AppServices environment.

**Repro steps:**

Publish or `dotnet run` project from https://github.com/pakrym/cert-crash-repro in Azure AppServices environment.

**Expected:** 
Prints "Hello world!"

**Actual:**
Application crashes without exception or any other output.
`$LastExitCode == -1073740940`

**Comment by benaadams** [comment]
Related? https://github.com/dotnet/corefx/issues/12412

**Comment by davidebbo** [comment]
The error is not Core specific, as the same core blows up the same way in a regular Console app on Azure Web App. It appears to be a [sandbox](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox) rejection, but at this point I don't know what.

I suggest closing this issue and instead starting thread on [Web App forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview).

**Comment by karelz** [comment]
@bartonjs do you agree with @davidebbo?

**Comment by bartonjs** [comment]
@karelz If a NetFx application fails in the same way then yeah, I'd say it has something more to do with Azure than us.  The NetFx code for that codepath hasn't changed in a long, long time.

**Comment by muratg** [comment]
:eyes:

**Comment by karelz** [comment]
Closing per discussion above.

**Comment by davidebbo** [comment]
Tracked by https://social.msdn.microsoft.com/Forums/en-US/54618916-1953-44cd-b426-14ab1caa59d2/creating-new-x509certificate2-instance-crashes-clr-in-azure-appservices-environment?forum=windowsazurewebsitespreview
