### ISSUE TITLE
CodeNamespaceImportCollection.Add(null) throws NullReferenceException instead of ArgumentNullException

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#12713]
See the following test:
```csharp
[Fact]
public void Add_Null_ThrowsNullReferenceException()
{
    var collection = new CodeNamespaceImportCollection();
    Assert.Throws<NullReferenceException>(() => collection.Add(null));
}
```

Should this be fixed to throw an ArgumentNullException, in order to be consistent with other CodeDom collections?
Is there a backcompt concern?

@stephentoub

**Comment by karelz** [comment]
What is the consistent behavior you propose?
In general this is IMO border line between compat vs. consistency of APIs ("beautiful APIs"). CodeDom is not super-widely used IMO, yet it may be one more thing where the platforms differ (deaths by thousands paper cuts) ...
cc: @Priya91

**Comment by hughbe** [comment]
> What is the consistent behavior you propose?

Out of the 17 or so collections in System.CodeDom, this is the only collection that doesn't throw an NRE

**Comment by Priya91** [comment]
We will leave the exception as is. Recently .NET Core collections was deviated from Desktop into throwing different exceptions, and we now have a bug #11324  to make the exceptions thrown be the same as in Desktop. This behavior deviates from Desktop behavior and we won't break compatibility here.
