### ISSUE TITLE
Add overload for case insensitive string Replace

### ISSUE THREAD

**Issue by ChrisEelmaa** [dotnet/corefx#1271]
# Introduction

`String` does not provide `Replace` method for case-insensitive replacements, but only for case-sensitive replacements. 
# Rationale and usage

The idea here is to make programmers life easier & move closer to API consistency. 

It is fairly common scenario where you have user inserted data that has some kind of place-holders (tokens), that later have to be replaced by some templating system. 

Current solutions in the internet involve using regex class for this trivial task. 

```c#
var userTemplateData = "Hello there. Time now is %currenttime%";
var evaluatedData = Regex.Replace(
                      userTemplateData, 
                      "%CurrentTime%", 
                       DateTime.Now.ToString(),
                       RegexOptions.IgnoreCase);

// evaluatedData = "Hello there. Time now is 01/04/2015 14:37";
```

This approach is horrible: 
1) not readable
2) often times not correct, as pattern has to be run through `Regex.Escape` before.
3) most likely slow(er)

After the necessary change is added, we can do:

```c#
var evaluatedData = userTemplateData.Replace(
                                         "%CurrentTime%", 
                                          DateTime.Now.ToString(),
                                           StringComparison.InvariantCultureIgnoreCase);
```

How common would the usage of this be? I would **speculate** that every programmer in their career will hit the lack of case-insensitive replacement in framework at least once. I can't say much more, expect provide some StackOverflow links below in Details section.

I did quick search through the code-base I am new to, and found around ~30 case-insensitive `Regex.Replace` usages. 
# Proposed API

```c#
public sealed class String : ...
{
    ....

    // these two methods are provided for framework consistency
    // trying to follow the StartsWith/EndsWith
    public string Replace(string oldValue, string newValue, StringComparison comparison);
    public string Replace(string oldValue, string newValue, bool ignoreCase, CultureInfo culture);

    public string Replace(char oldValue, char newValue, CompareOptions options);


    ....
}
```
# Details

Namespace: **System**
Type: **System.String**
Assembly: **System.Runtime.dll**

I'd love to see the current `string.Replace` [CoreClr implementation](https://github.com/dotnet/coreclr/blob/cbf46fb0b6a0b209ed1caf4a680910b383e68cba/src/classlibnative/bcltype/stringnative.cpp#L835) pulled out from CoreClr, and implemented 100% in the `String.cs`:

   This would help to:
- avoid code-duplication
- make it more transparent (programmers can take look at the implementation) 
- unit-test a little less, as they share both common functionality for `Replace(..., StringComparison.Ordinal);`

Alternatively, we could also modify the existing `CoreClr` implementation to deal with `StringComparison`. Or, just rewrite everything from zero.
# Links to explore

http://stackoverflow.com/questions/244531/is-there-an-alternative-to-string-replace-that-is-case-insensitive

http://stackoverflow.com/questions/6275980/string-replace-by-ignoring-case

http://weblogs.asp.net/jongalloway/71188
# Updates
- Edited this description to make it more of a **speclet**, based on the discussion below and the proposed API Review process.
- Feedback to @tarekgh. Added my opinion about how often this functionality would be used

I'd be willing to work on this :3

**Comment by ellismg** [comment]
If we are to do this, I would not want the implementation to be written in terms of regular expressions.  Instead, I would imagine a solution around something like calls to ```IndexOf```.

We should also discuss the factoring around this.  Could we implement this via an extension method in a higher level contract?

**Comment by ChrisEelmaa** [comment]
There is also one idea to consider; is it possible to reuse String.cs existing `Replace` method? As of right now, `String.Replace()` will call internally CoreClr's `ReplaceString`  (https://github.com/dotnet/coreclr/blob/cbf46fb0b6a0b209ed1caf4a680910b383e68cba/src/classlibnative/bcltype/stringnative.cpp).

If we could port that code (`ReplaceString`)  to String.cs instead, we could just modify it to also accept `StringComparer`, and make both overloads call the underlying one. 

The idea of this is to avoid duplicating the code, make it more transparent what's going on. The only reason I suspect it's implemented in CoreClr might be performance, but I believe  that JIT will be able to produce code that matches the speed. Either way, something to consider.

**Comment by ellismg** [comment]
@ChrisEelmaa mind flushing this out as a speclet and we can take it through API review?

**Comment by tarekgh** [comment]
ReplaceString is not well written to handle the cultural aware strings. yes we can take it and modify it but I would say just writing the new method and using IndexOf/LastIndexOf would be better I think. Also I believe we need to search from the beginning of the string and not from the end as ReplaceString is doing. but anyway this is details we can get into later.

my question now, do we have any idea how often need to use such functionality? I know it is useful and will be welcomed by the community but I want to know if really a lot of people will use. I am asking to know if such functionality need to be in the core library or can be in other non core library as extension method

**Comment by ChrisEelmaa** [comment]
@ellismg, @tarekgh : updated to speclet.

**Comment by terrajobst** [comment]
We [reviewed this issue today](https://github.com/dotnet/apireviews/tree/master/2015-04-28-misc#1271-add-overload-for-case-insensitive-string-replace). It looks good as proposed.

**Comment by tarekgh** [comment]
@ChrisEelmaa are you still interested to work on this one?

**Comment by karelz** [comment]
This will be somewhat involved implementation.

**Comment by AlexRadch** [comment]
To correctly implement Replace methods by using IndexOf,  we should implement CompareInfo.IndexOf methods that return not only index one string in other but return length one string in other as additional info also. 
Now CompareInfo.IndexOf methods return only index but length in original string can be different from length of value string. So we know where value string is begin in original string but do not know where value string is ended in original string.
I do not understand how to get that length now.

**Comment by karelz** [comment]
Yeah, it looks rather involved and tricky ...
cc: @krwq

**Comment by AlexRadch** [comment]
I suggest extend CompareInfo.IndexOf methods by return not only start index but length or end index also.

**Comment by karelz** [comment]
[CompareInfo.IndexOf](https://github.com/dotnet/coreclr/blob/98b795e2a7d76c0d854084add431d362394e9800/src/mscorlib/corefx/System/Globalization/CompareInfo.cs#L706) is virtual method on public type, which can be inherited, its virtual methods can be overridden. How will you deal with that?

**Comment by tarekgh** [comment]
I think @AlexRadch idea is good by adding overloading method/s for IndexOf family which can return the length of the string in addition to the index position. after that we can implement easily the requested APIs in this issue

**Comment by tarekgh** [comment]
one other note, to progress with this issue we can implement CompareInfo.IndexOf internally which can return the length of the searched string which we can use to implement the Replace methods. we can try later to expose CompareInfo.IndexOf if needed.

@AlexRadch are you willing to help in the implementation? let me know and I can arrange with you what need to be done here.

**Comment by ChrisEelmaa** [comment]
I can take this

**Comment by karelz** [comment]
Assigned to you ...

**Comment by ChrisEelmaa** [comment]
before doing any real work,
I need to understand what is the plan when going on-forward.

Taking a look at CompareInfo.cs reveals that there are multiple files:

```
C:\src\git\coreclr\src\mscorlib\corefx\System\Globalization\CompareInfo.cs
C:\src\git\coreclr\src\mscorlib\corefx\System\Globalization\CompareInfo.Windows.cs
C:\src\git\coreclr\src\mscorlib\corefx\System\Globalization\CompareInfo.Unix.cs
```

and

`C:\src\git\coreclr\src\mscorlib\src\System\Globalization\CompareInfo.cs`

the corefx\ one does not seem to be valid at this point, for example, when I try to look for "FindStringOrdinal" there is no actual interop defined for it. 

Am I going to implement it in` mscorlib\src\System\Globalization\CompareInfo.cs`? Or are you guys moving away from this?

**Comment by tarekgh** [comment]
the code in C:\src\git\coreclr\src\mscorlib\src\ is mainly the code runs on Windows. 
the code C:\src\git\coreclr\src\mscorlib\corefx\System\Globalization is the code mainly runs for Linux. 

the file like C:\src\git\coreclr\src\mscorlib\corefx\System\Globalization\CompareInfo.Windows.cs is not really used in codeclr but we keep it there because we keep the code in sync with corert repo which mainly for .net native. 

if your additions is OS independent, then we should add it and let all compilations (for Windows and Linux) share it. if you are going to have any OS dependent code, then for Windows specific you'll need to add the implementation in C:\src\git\coreclr\src\mscorlib\src\ and fo rLinux you add the implementation to  C:\src\git\coreclr\src\mscorlib\corefx\

I think we'll leave with the current split for awhile till we consolidate both Windows and Linux implementation at some point.

**Comment by karelz** [comment]
@ChrisEelmaa are you still working on the issue?

**Comment by ChrisEelmaa** [comment]
I did take pretty deep look in this previously, and we'd have to modify the internal C++ code to expose what is needed (the length), and in some cases, the length is not even there.

happy to do this, but it could get tricky. I wonder if better path is to pull the IndexOf implementation out from C++ side to C# (so it would be semi-platform independent), and then change that instead (if that's the plan anyways)?.

**Comment by tarekgh** [comment]
> happy to do this, but it could get tricky. I wonder if better path is to pull the IndexOf implementation out from C++ side to C# (so it would be semi-platform independent), and then change that instead (if that's the plan anyways)?.

we call the OS for the IndexOf functionality. for example on Windows we call FindNLSStringEx to do the Index of operation https://msdn.microsoft.com/en-us/library/windows/desktop/dd318059(v=vs.85).aspx. when we call this OS APIs we ignore the parameter pcchFound which give us the desired length. so we'll need to use this parameter and propagate it to the managed side and use it. we'll need to look at the Linux OS calls too to try to do the same.

**Comment by ChrisEelmaa** [comment]
okay I've made some progress on this, but kind of stuck now. I exposed the pcchFound for windows, and also wrote the Replace method which leverages the new internal IndexOf.

1) I wrote platform agnostic "Replace" method which can be shared on every platform(Windows, Linux, OSX), but not sure how to share it (if it's even possible), or should I duplicate it?

2) I can't seem to find a place where to write tests for this. I see some of the projects in "C:\src\git\coreclr\tests\src\CoreMangLib\cti\system\string", but none of them are referred by AllTestsProjects.sln. So this is probably not the right place, probably coreFX project then.

I am not entirely sure what the workflow here would be. I assume: I will add all the required methods to String as indicated in the original post.

After that is done, I shall build coreCLR, copy all DLLS to coreFX, and add new tests to coreFX (https://github.com/dotnet/coreclr/blob/master/Documentation/building/testing-with-corefx.md), and the file where to add tests: C:\src\git\corefx\src\System.Runtime\tests\System\StringTests.cs. That's all I need to do in coreFX (or do I actually need to set up some kind of binding redirects?)

I then will validate that all the tests run on my computer, and do the same thing for Linux. Is OSX also being worked on?

3) I am not sure how shall I send the pull request, as I need to modify two repos. Do I make one pull request about coreCLR, and another about coreFX? How will the PR flow look like?

**Comment by tarekgh** [comment]
> I wrote platform agnostic "Replace" method which can be shared on every platform(Windows, Linux, OSX), but not sure how to share it (if it's even possible), or should I duplicate it?

Put the implementation in its own cs file under \mscorlib\src\system\Globalization folder and then include the file in the project by add it entry in the file https://github.com/dotnet/coreclr/blob/master/src/mscorlib/mscorlib.shared.sources.props


> I can't seem to find a place where to write tests for this. I see some of the projects in "C:\src\git\coreclr\tests\src\CoreMangLib\cti\system\string", but none of them are referred by AllTestsProjects.sln. So this is probably not the right place, probably coreFX project then.

usually when you have the implementation ready we add the tests in the corefx repo. this is done after we enable the new APIs in the contracts in the corefx repo. you may add a small test in coreclr repo for your initial test by mimic one of the tests projects there (e.g. coreclr\tests\src\CoreMangLib\system\text\encoding) and then later when we merge the changes and build the packages we can enable the contracts and add tests in corefx repo. we can talk about that when you are done in coreclr repo.

> I am not sure how shall I send the pull request, as I need to modify two repos. Do I make one pull request about coreCLR, and another about coreFX? How will the PR flow look like?

don't get concerned about the corefx changes before finishing the coreclr changes. we always do that in 2 steps. just get coreclr changes ready and send a PR on coreclr repo (after your initial testing) and then we merge and build the changes we can start the corefx changes and will have another PR in that repo. I can help you in the process. 

Please let me know if you have any question at any time. I'll be happy to help in that. 

did you have a chance to look at the Linux part too? 

Thanks for your help here.

**Comment by ChrisEelmaa** [comment]
okay, almost there. I added implementation for the Linux part as well. The only problem remains, I haven't had chance to test anything at all, so it's quite theoretical currently.

I created small test (mimicing coreclr\tests\src\CoreMangLib\system\text\encoding)) that uses the new overloads, however if I try to compile it through msbuild, I get:

> "C:\src\git\coreclr\tests\src\CoreMangLib\cti\system\string\StringReplace3.csproj" (default target) (1) ->
> (CoreCompile target) ->
>   stringreplace3.cs(55,71): error CS1501: No overload for method 'Replace' takes 3 arguments [C:\src\git\coreclr\tests\
> src\CoreMangLib\cti\system\string\StringReplace3.csproj]


my new methods are not picked up. any ideas?

**Comment by tarekgh** [comment]
could you try adding the following element to your project

```Xml
<ReferenceLocalMscorlib>true</ReferenceLocalMscorlib>
```

if you already have it please make sure its value is true.

here is a project example doing that

https://github.com/dotnet/coreclr/blob/master/tests/src/baseservices/compilerservices/FixedAddressValueType/FixedAddressValueType.csproj#L16

you may look at the PR https://github.com/dotnet/coreclr/pull/7181/files to see how addign APIs in coreclr is done in general

thanks again for your effort

**Comment by ChrisEelmaa** [comment]
thanks,

had to enable that flag, and add the overloads to ref/mscorlib.cs as well.

I've created PR at https://github.com/dotnet/coreclr/pull/9316
unfortunately it didn't link PR with this issue, as they are in different repository.

that said, I am now a bit stuck. I've made all the tests pass on the windows, and it seems nice. However, on Linux the tests fail. I am running on OSX, so I had chance to take a closer look. Basically what is happening is that the usearch_getMatchedLength (https://github.com/dotnet/coreclr/pull/9316/files#diff-8d0c7a067ed30b7fc00899e3c0345111) seems to report outrageous results.

For example if I ask IndexOf("My short string", "short") it'll tell me something crazy like the length of the match is 36 characters. That doesn't make sense, because the whole length of the string is 15 characters.

any ideas?

**Comment by tarekgh** [comment]
@ChrisEelmaa I saw you mentioned before 

```
that said, I am now a bit stuck. I've made all the tests pass on the windows, and it seems nice. However, on Linux the tests fail. I am running on OSX, so I had chance to take a closer look. Basically what is happening is that the usearch_getMatchedLength (https://github.com/dotnet/coreclr/pull/9316/files#diff-8d0c7a067ed30b7fc00899e3c0345111) seems to report outrageous results.
For example if I ask IndexOf("My short string", "short") it'll tell me something crazy like the length of the match is 36 characters. That doesn't make sense, because the whole length of the string is 15 characters.
any ideas?

```

and then you have removed this comment. does this mean you were able to test it on OSX successfully? or you still have issues on OSX?

**Comment by tarekgh** [comment]
@ChrisEelmaa I have added some comments to the PR. thanks again for getting this ready for the review.

**Comment by ChrisEelmaa** [comment]
Yeah, Linux/OSX is working nicely, it was just small bug with ordinal strings that I didn't notice (nothing to do with usearch).

I'll  try to reply/fix to PR comments in few days.

**Comment by tarekgh** [comment]
@ChrisEelmaa did you have a chance to look at comments? just wondering if you need any help from our side. Thanks.

**Comment by ChrisEelmaa** [comment]
I addressed the feedback, I believe I understood everything. Tests pass, and I rebased with the latest state.

**Comment by danmosemsft** [comment]
@ChrisEelmaa @tarekgh did we forget to expose this in CoreFX? I don't see it there, wihch means this API cannot be used.

@hughbe in case he feels like adding an API to String (an opportunity that doens't come around often!)

**Comment by hughbe** [comment]
I'll take a look!

**Comment by hughbe** [comment]
Found a couple of bugs with the implementation. Looks like ordinal ignore case comparison is broken, and so is replacing the empty string. I'll investigate a coreclr fix
```cs
[Fact]
public void Replace_IgnoreCase()
{
    // Nope: "abc"
    Assert.Equal("def", "abc".Replace("ABC", "def", StringComparison.OrdinalIgnoreCase));

    // Fine: "def"
    Assert.Equal("def", "abc".Replace("ABC", "def", StringComparison.InvariantCultureIgnoreCase));
    Assert.Equal("def", "abc".Replace("ABC", "def", StringComparison.CurrentCultureIgnoreCase));
}

[Fact]
public void Replace_EmptyNewValue()
{
    // Nope: OutOfMemoryException
    Assert.Equal("abc", "abc".Replace("", "def", StringComparison.CurrentCulture));
    Assert.Equal("abc", "abc".Replace("", "def", StringComparison.CurrentCultureIgnoreCase));
    Assert.Equal("abc", "abc".Replace("", "def", StringComparison.InvariantCulture));
    Assert.Equal("abc", "abc".Replace("", "def", StringComparison.InvariantCultureIgnoreCase));
    Assert.Equal("abc", "abc".Replace("", "def", StringComparison.Ordinal));
    Assert.Equal("abc", "abc".Replace("", "def", StringComparison.OrdinalIgnoreCase));
}
```

**Comment by hughbe** [comment]
Another odd case with ordinal ignore case, I think... maybe @tarekgh could comment on this one, my understanding was that ordinal compares code units, so this "abc\u00AD" can never equal "abc"
```cs
[Fact]
public void StartsWithHyphen()
{
    // Nope: "def"
    Assert.Equal("abc", "abc".Replace("abc\u00AD", "def"));
}
```

**Comment by karelz** [comment]
@hughbe when you find problems with the API, can you please file them as bugs and link them from here? I want to make sure we mark them as 2.0, given we're shipping the API in 2.0 for the first time.
Thanks!

And big thanks for finishing it off!

**Comment by danmosemsft** [comment]
Nice work @hughbe and catching those bugs. Glad I asked you.

**Comment by tarekgh** [comment]
> Another odd case with ordinal ignore case, I think... maybe @tarekgh could comment on this one, my understanding was that ordinal compares code units, so "abc\u00AD" can never equal "abc"

the correct behavior is 

```C#
Assert.Equal("abc", "abc".Replace("abc\u00AD", "def"));
```

should be true. this operation done as ordinal comparison and the string shouldn't find "abc\u00AD" at all to replace.. if this is not happening then we have a bug. could you send more details around this case?
