### ISSUE TITLE
System.Net.* test configurations need updating

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#12735]
Right now the System.Net.Security (and I'm assuming other System.Net.\* tests have the same issue) tests configurations only support netstandard1.7 which will block them from running tests in other configurations.

We should probably keep the netstandard1.3 configurations so we can still run these tests for uap. We also need to add a netcoreapp1.1 build configuration to get the new sslstreamalert tests running (see https://github.com/dotnet/corefx/pull/12733). While taking a quick look at why these tests didn't fail in CI, it is because the take a dependency on the csproj (https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/tests/FunctionalTests/System.Net.Security.Tests.csproj#L145) instead of the pkgproj like they should. 

cc @CIPop @davidsh

**Comment by CIPop** [comment]
I believe I've fixed this with #13075. 
Please re-open with details if more work needs to be done.
