### ISSUE TITLE
Duplicate resource strings in System.Net.Mail 

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#12738]
``` xml
<data name="SmtpMailboxBusy" xml:space="preserve">
    <value>Mailbox unavailable.</value>
</data>
<data name="SmtpMailboxUnavailable" xml:space="preserve">
    <value>Mailbox unavailable.</value>
</data>
```

This bug exists on Full Framework as well.

**Comment by Priya91** [comment]
cc @CIPop Can you take a look.

**Comment by davidsh** [comment]
My guess is that this is a bug and that for SmtpMailboxBusy, the string should really say "Mailbox busy."

**Comment by CIPop** [comment]
Verified that this is the same in Desktop. 
@Priya91 @karelz @davidsh My recommendation is to leave these as-is to avoid any app-compat issues.

**Comment by Priya91** [comment]
As per @CIPop recommendation, closing the issue.
