### ISSUE TITLE
Incoherent CultureInfo in different machines

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#12748]
@IlBaffo commented on [Thu Sep 29 2016](https://github.com/dotnet/coreclr/issues/7415)

Hi,
I have noticed that, creating a specific CultureInfo with "zh-Hant-\*", will be returned a culture with parent "CHS" (should be CHT) and creating a CultureInfo with "zh-Hans-\*" returns a culture with the DateTimeFormats in Traditional Chinese instead of Simplified.

Steps to reproduce:

- Create a console app (target any framework > 4.5.0, I don't know if lower versions have the problem)
- Paste this code:

```
class Program
{
    static void Main(string[] args)
    {
        System.Console.WriteLine(System.Environment.Version.ToString());
        System.Console.WriteLine("zh-Hant-CN");
        System.Console.WriteLine("Parent Name is: " + System.Globalization.CultureInfo.CreateSpecificCulture("zh-Hant-CN").Parent.Name);
        System.Console.WriteLine("Parent LCID is: " + System.Globalization.CultureInfo.CreateSpecificCulture("zh-Hant-CN").Parent.EnglishName);
        System.Console.WriteLine("Parent LCID is: " + System.Globalization.CultureInfo.CreateSpecificCulture("zh-Hant-CN").Parent.LCID);
        System.Console.WriteLine("zh-Hans-CN");
        System.Console.WriteLine("Parent Name is: " + System.Globalization.CultureInfo.CreateSpecificCulture("zh-Hans-CN").Parent.Name);
        System.Console.WriteLine("Parent Name is: " + System.Globalization.CultureInfo.CreateSpecificCulture("zh-Hans-CN").Parent.EnglishName);
        System.Console.WriteLine("Parent LCID is: " + System.Globalization.CultureInfo.CreateSpecificCulture("zh-Hans-CN").Parent.LCID);

        System.Console.WriteLine("Same culture: " + System.Globalization.CultureInfo.CreateSpecificCulture("zh-Hant-CN")
           .Equals(System.Globalization.CultureInfo.CreateSpecificCulture("zh-Hans-CN")).ToString()
        );
        System.Console.ReadKey();
    }
}
```
- Run the compiled EXE (Any Cpu, Debug) on a Windows machine except Windows 10 (Windows Server 20012 R2 in my case) with the latest framework (4.6.2) and the latest updates installed.

The output of the program will be (wrong?):
```
4.0.30319.42000
zh-Hant-CN
Parent Name is: zh-CHS
Parent LCID is: Chinese (Simplified) Legacy
Parent LCID is: 4
zh-Hans-CN
Parent Name is: zh-CHS
Parent Name is: Chinese (Simplified) Legacy
Parent LCID is: 4
Same culture: True
```

On Windows 10 though the output is as expected:
```
4.0.30319.42000
zh-Hant-CN
Parent Name is: zh-CHT
Parent LCID is: Chinese (Traditional) Legacy
Parent LCID is: 31748
zh-Hans-CN
Parent Name is: zh-CHS
Parent Name is: Chinese (Simplified) Legacy
Parent LCID is: 4
Same culture: False
```

Additionally, when creating the language "zh-Hans-CN" (Simplified) the Traditional Month Names (and other names) are used, so if you run this code you will get 'Same culture: true' in Windows < 10:
```
System.Console.WriteLine("Same culture: " + System.Globalization.CultureInfo.CreateSpecificCulture("zh-Hant-CN").Equals(System.Globalization.CultureInfo.CreateSpecificCulture("zh-Hans-CN")).ToString());
```

I hope this is not the wrong repository because I have found here the source code of the class:
https://github.com/dotnet/coreclr/blob/74967f89e0f43e156cf23cd88840e1f0fc94f997/src/mscorlib/src/System/Globalization/CultureInfo.cs#L584

Thank you.

**Comment by stephentoub** [comment]
cc: @tarekgh

**Comment by tarekgh** [comment]
The framework depends on the underlying OS to get the globalization and culture data. 

here is the differences in OS behavior which get reflected on the framwork:

```Windows 10:```
- it support the culture zh-Hant-CN
- when calling CreateSpecificCulture("zh-Hant-CN") will give zh-Hant-CN culture and will has the parent zh-Hant
- zh-Hans-CN is not supported when calling CreateSpecificCulture("zh-Hans-CN") will give zh-CN culture and will has the parent zh-CHS (simplified)

```Server 2012 R2:```
- it doesn't support the culture zh-Hant-CN
- when calling CreateSpecificCulture("zh-Hant-CN") will give zh-CN culture and will has the parent zh-CHS
- zh-Hans-CN is not supported either and when calling CreateSpecificCulture("zh-Hans-CN") will give zh-CN culture too and will has the parent zh-CHS (simplified)

when the OS doesn't support specific culture and you ask to create some culture from it using CreateSpecificCulture, the OS will give you the closest culture to what you have requested and it is not guaranteed to get the culture you intended to have.

if you disagree with the behavior, please report it to Windows team through Windows Insider channel.

**Comment by IlBaffo** [comment]
Hi, I do not disagree with the policy of letting to the OS provide the data, specially because the calendar Day/Month names are wrong.
What I found confusing, if not problematic, was that:

1. there is no warning about this behavior in the documentation (or at least I didn't find it) or in the method intellisense
2. there is not way of manually fixing the CultureInfo instance because some properties are readonly/internal (we usually set the culture in the thread to pass it down the stack)
3. there are already explicit special cases in the code to handle those cultures differently (ie: https://github.com/dotnet/coreclr/blob/74967f89e0f43e156cf23cd88840e1f0fc94f997/src/mscorlib/src/System/Globalization/CultureInfo.cs#L1046 https://github.com/dotnet/coreclr/blob/74967f89e0f43e156cf23cd88840e1f0fc94f997/src/mscorlib/src/System/Globalization/CultureInfo.cs#L1791)

As for the insider report, I don't think it will be worth to post and wait for a Windows Server 2008R2 patch :(
