### ISSUE TITLE
Improve "dynamic" performance

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#12747]
@Opiumtm commented on [Fri Oct 14 2016](https://github.com/dotnet/coreclr/issues/7618)

`dynamic` feature today have extremely awful performance.
Dynamic typing in .NET languages (C#, VB) isn't used much, mostly because of intolerable slow performance and some bugs in implementation (there are memory leaks in dynamics, for example).

Some third-party libraries provide fast reflection based on IL emit at runtime to have fast access to object members. Even standard reflection API provide means to create fast delegates to invoke at runtime:
[MethodInfo.CreateDelegate](https://msdn.microsoft.com/en-us/library/hh194376%28v=vs.110%29.aspx)

Performance measurement of `dynamic` reveal that it doesn't cache delegates and indeed is very unoptimized. [MethodInfo.CreateDelegate](https://msdn.microsoft.com/en-us/library/hh194376%28v=vs.110%29.aspx) provide performance almost as fast as direct call to a method (there is some performance penalty on delegate creation, but invocation of created delegate is almost free - so it can created on first invoke and then can be cached). `dynamic` is very much slower on subsequent method calls, although it can cache method invokes using `CreateDelegate`. Same performance improvements should be applied on other `dynamic` features. Dynamic method invocation is just an example of how it should be improved.
---

@mikedn commented on [Fri Oct 14 2016](https://github.com/dotnet/coreclr/issues/7618#issuecomment-253782788)

How exactly is this related to coreclr? The entire dynamic implementation is in Microsoft.CSharp, a corefx project.
---

@danmosemsft commented on [Mon Oct 17 2016](https://github.com/dotnet/coreclr/issues/7618#issuecomment-254402736)

Moving to corefx.

**Comment by mburbea** [comment]
isnt this a dupe of #12643 ?

**Comment by danmosemsft** [comment]
It is a dupe, thanks
