### ISSUE TITLE
DataTableReadWriteXmlTest.TestReadXml failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12753]
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/1754/consoleText

```
System.Data.Tests.DataTableReadWriteXmlTest.TestReadXml [FAIL]
        Assert.Equal() Failure
                                         ↓ (pos 375)
        Expected: ···:element name="Main" msdata:Prefix="">\n            <xs:comple···
        Actual:   ···:element name="Main">\n            <xs:complexType>\n          ···
                                         ↑ (pos 375)
        Stack Trace:
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Data.Common/tests/System/Data/DataTableReadWriteXmlTest.cs(364,0): at System.Data.Tests.DataTableReadWriteXmlTest.TestReadXml()
```

I've only seen this fail once, on OSX.  It looks like we expected a node to contain an empty prefix attribute, and instead it wasn't there at all.  This is one of the ported Mono DataSet tests.

**Comment by bartdesmet** [comment]
Also occurred here: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx_release_prtest/2337

**Comment by stephentoub** [comment]
Similar failure in a different test here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx_release_prtest/2399/consoleText
```
System.Data.Tests.DataSetTest.WriteXmlSchema4 [FAIL]
        Assert.Equal() Failure
                                         ↓ (pos 253)
        Expected: ···CurrentLocale="true" msdata:EnforceConstraints="True">\n    <x···
        Actual:   ···CurrentLocale="true">\n    <xs:complexType>\n      <xs:choice m···
                                         ↑ (pos 253)
        Stack Trace:
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_release_prtest/src/System.Data.Common/tests/System/Data/DataSetTest.cs(1218,0): at System.Data.Tests.DataSetTest.WriteXmlSchema4()
```
@saurabh500, these are the mono tests, so I know you're unfamiliar with them.  But any insights as to why most of the time an msdata attribute is getting added, but then every once in a while it goes missing (and causes these string comparison failures)?  Is there some non-determinism somewhere in the implementation?

**Comment by saurabh500** [comment]
@stephentoub  I am not familiar with the Xml serialization code for DataSet and DataTable. 
This will need debugging. The `EnforceConstraint` property of DataSet is not being modified in the tests and its default return val is `true` 

I think this may have something to do with the conversion of DataSet to XML in xmlsaver.cs

**Comment by stephentoub** [comment]
> The EnforceConstraint property of DataSet is not being modified in the tests and its default return val is true

Turns out the test has its equals arguments reversed (what's marked as "expected" is actually what happened, and what's marked as "actual" is what the test was expecting), so the output actually contained ```msdata:EnforceConstraints="True"``` but the test wasn't expecting it.  The vast majority of the time this passes.

**Comment by stephentoub** [comment]
After taking a look at the DataSet/xmlsaver code, I suspect there's a race condition or the like somewhere in the PropertyDescriptor infrastructure that System.Data.Common is relying on.

**Comment by stephentoub** [comment]
I'm fairly certain this is being caused by https://github.com/dotnet/corefx/issues/13215.
