### ISSUE TITLE
Building corefx on Linux adds src\src dir to nupkgs

### ISSUE THREAD

**Issue by omajid** [dotnet/corefx#12758]
If I build corefx (commit 9688ddbb62c04189cac4c4a) on RHEL, some of the nupkgs produced include unexpected `src\src` directories in their root.

For example: 

```
$ unzip -l System.Runtime.Loader.4.0.0.nupkg 
Archive:  System.Runtime.Loader.4.0.0.nupkg
Length      Date    Time    Name
---------  ---------- -----   ----
    511  10-17-2016 12:20   _rels/.rels
    1705  10-17-2016 12:20   System.Runtime.Loader.nuspec
    9323  10-17-2016 12:20   dotnet_library_license.txt
    1587  10-17-2016 12:20   ThirdPartyNotices.txt
        0  10-17-2016 12:20   lib/net462/_._
    5632  10-17-2016 12:20   lib/netstandard1.5/System.Runtime.Loader.dll
    6656  10-17-2016 12:20   ref/netstandard1.5/System.Runtime.Loader.dll
    1794  10-17-2016 12:20   ref/netstandard1.5/System.Runtime.Loader.xml
    1794  10-17-2016 12:20   ref/netstandard1.5/de/System.Runtime.Loader.xml
    1794  10-17-2016 12:20   ref/netstandard1.5/es/System.Runtime.Loader.xml
    1794  10-17-2016 12:20   ref/netstandard1.5/fr/System.Runtime.Loader.xml
    1794  10-17-2016 12:20   ref/netstandard1.5/it/System.Runtime.Loader.xml
    1794  10-17-2016 12:20   ref/netstandard1.5/ja/System.Runtime.Loader.xml
    1794  10-17-2016 12:20   ref/netstandard1.5/ko/System.Runtime.Loader.xml
    1794  10-17-2016 12:20   ref/netstandard1.5/ru/System.Runtime.Loader.xml
    1794  10-17-2016 12:20   ref/netstandard1.5/zh-hans/System.Runtime.Loader.xml
    1794  10-17-2016 12:20   ref/netstandard1.5/zh-hant/System.Runtime.Loader.xml
    2803  10-17-2016 12:20   src%5Csrc/System.Runtime.Loader/ref/System.Runtime.Loader.cs
    704  10-17-2016 12:20   [Content_Types].xml
    830  10-17-2016 12:20   package/services/metadata/core-properties/d53d159faf2a41ba8918c8a2c680a616.psmdcp
---------                     -------
    47691                     20 files
```

That `src%5Csrc` file is unexpected.

If this nupkg gets included into a cli build, `dotnet` will cache various `.cs` files into `~/.nuget`. If someone does a `cd ~ && dotnet new && dotnet restore && dotnet build` they get thousands of unexpected warnings and errors.

As a workaround, changing the `\` to `/` at https://github.com/dotnet/buildtools/blob/29b79c7a72ff03e8ab526f5663b99ce6fb2d58fe/src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/PackageLibs.targets#L182 fixes this issue (at least on RHEL).

**Comment by omajid** [comment]
cc @ellismg (who helped me find the issue and the workaround)

**Comment by karelz** [comment]
@ellismg any idea where to route the problem?

**Comment by ellismg** [comment]
@karelz I was looking into this with Davis and I think we'll need to make some fix in buildtools ultimately.  I assigned this issue to myself.  The workaround fixes the packages when built on Linux but impacts the windows build, so we can't take it as is.

I've assigned the issue to myself.

**Comment by mellinoe** [comment]
@ellismg Was this fixed by https://github.com/dotnet/buildtools/issues/1150? We should be consuming that here in corefx at this point.

**Comment by ellismg** [comment]
Yes, it was.
