### ISSUE TITLE
Incremental build prevents tests from being run when changing traits

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#1275]
When you run tests for any project like:
msbuild /t:BuildAndTest AnyTestProject.Tests.csproj
tests are successfully run.

When you specify property to its default value exactly the same should happen:
msbuild /t:BuildAndTest /p:RunTestsWithCategories=InnerLoop AnyTestProject.Tests.csproj
but no tests are run

I nailed down the issue to this (tests.targets):
```xml
  <Target Name="RunTestsForProject"
          AfterTargets="DiscoverTestInputs"
          Inputs="@(RunTestsForProjectInputs)"
          Outputs="$(TestPath)%(TestTargetFramework.Folder)\$(TestsSuccessfulSemaphore);$(TestPath)%(TestTargetFramework.Folder)\$(XunitResultsFileName)"
          Condition="'$(TestDisabled)'!='true'">
```

removing:
```
          Inputs="@(RunTestsForProjectInputs)"
          Outputs="$(TestPath)%
```
does fix the issue although removes the idea of that change.

The tests should be also run when any of these items or properties is changed:
- RunWithTraits
- RunWithoutTraits
- TestDisabled

**Comment by eatdrinksleepcode** [comment]
I think we can use the semaphore file to work around this. I will look into it.

**Comment by weshaggard** [comment]
Yes @eatdrinksleepcode I think we can probably use the traits in part of the semaphore file name.

**Comment by eatdrinksleepcode** [comment]
Am I correct that these three properties (RunWithTraits, RunWithoutTraits, TestDisabled) are mutually exclusive?

**Comment by weshaggard** [comment]
RunWithTraits and RunWithoutTraits are mutually exclusive but TestDisabled is not necessary. TestDisabled can be set explicitly or computed based on the traits and categories of a test project.
