### ISSUE TITLE
XsdDataContractExporterTest Fail

### ISSUE THREAD

**Issue by huanwu** [dotnet/corefx#12772]
Throw null reference exception when call the following code
 XsdDataContractExporter exporter = new XsdDataContractExporter();
exporter.CanExport(typeof(Employee));

This is because DataContractSet returns null (XsdDataContractExporter.cs). The code was commented.
DataContractSet DataContractSet
        {
            get
            {
                //if (dataContractSet == null)
                //{
                //    dataContractSet = new DataContractSet((Options == null) ? null : Options.GetSurrogate());
                //}
                return _dataContractSet;
            }
        }

**Comment by karelz** [comment]
GetSurrogate is not coming over - it has been decided.
This test should not be ported over.

@huanwu can you please delete the test if it is just disabled with ActiveIssue. Then please close the bug.
