### ISSUE TITLE
Split ServicePointManager into a separate contract

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#12774]
Related: https://github.com/dotnet/standard/issues/72 

 - [x] Create new System.Net.ServicePoint contract and move sources
 - [x] Remove the `CertificatePolicy` and `ICertificatePolicy` Obsoleted API s
 - [x] Add back `SmtpClient.ServicePoint`
 - [x] Change System.Net.Requests contract to depend on System.Net.ServicePoint contract
 - [x] Change System.Net.Mail contract to depend on System.Net.ServicePoint contract

**Comment by Priya91** [comment]
@CIPop It should also include tracking checking for Server certificate revocation, using the ```ServicePointManager.CheckCertificateRevocationList``` in ```TlsStream.AuthenticateAsClient``` and ```TlsStream.BeginAuthenticateAsClient``` used by ```SmtpClient``` and ```FtpWebRequest```
