### ISSUE TITLE
Create implementation of HandleCount on Unix

### ISSUE THREAD

**Issue by AlexGhiondea** [dotnet/corefx#12793]
Once https://github.com/dotnet/corefx/pull/12765 is checked in, create the Unix implementation for HandleCount.

**Comment by AlexGhiondea** [comment]
For example, we should be able to get the number of open file descriptors in the process, which is similar in concept to a handle.

**Comment by stephentoub** [comment]
On Linux we can get this by enumerating the contents of ```/proc/self/fd```.  That's relatively expensive, though, so we'd want to do it only on demand I think.
