### ISSUE TITLE
SmtpClient: EvenSources should either have a GUID attribute or have the GUID documented

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#12808]
- [ ] Add/Document the GUID within the source-file that defines it (EmailEventSource).
 - [ ] Document the GUID at https://github.com/dotnet/corefx/blob/master/Documentation/debugging/windows-instructions.md#traces

**Comment by vancem** [comment]
The GUID for any particular EventSource can be determined by calling the 'Guid' API on the EventSource.  It is stable (it will never change until the EventSource name is changed).     

More conveniently, you can use a tool like PerfView or WPA to determine the Guid for the EventSource (Ask it to turn on the EventSource using the *NAME syntax and see what Guid it produced).   

Alternatively you could log an issue with the logman command to support the *NAME syntax.   

Doing this for Microsoft-System-Net-Mail produces the GUID 42c8027b-f048-58d2-537d-a4a9d5ee7038

**Comment by CIPop** [comment]
Thanks @vancem for confirming that there is no tool distributed with Windows that would support *Name. 
I've logged a Feedback Hub suggestion for the next version of Windows. Even if support will be added in future OS versions, the log capture technique not requiring additional tools (such as PerfView or WPA) should work on older Windows versions where CoreFX is supported as well. 

Given this, we should at least add documentation/comments for the GUID above.

**Comment by vancem** [comment]
What exactly is the change that you want?

**Comment by CIPop** [comment]
> What exactly is the change that you want?

Just wanted to understand this part:

>Alternatively, present a way to capture traces without installing or copy-ing additional tools.

Since that was answered, I've removed the assignment and updated the details above.
