### ISSUE TITLE
Bring remaining System.Text members to netstandard2.0

### ISSUE THREAD

**Issue by AlexGhiondea** [dotnet/corefx#12816]
```
M:System.Text.UnicodeEncoding.GetByteCount(System.Char*,System.Int32)
M:System.Text.UnicodeEncoding.GetBytes(System.Char*,System.Int32,System.Byte*,System.Int32)
M:System.Text.UnicodeEncoding.GetCharCount(System.Byte*,System.Int32)
M:System.Text.UnicodeEncoding.GetChars(System.Byte*,System.Int32,System.Char*,System.Int32)
```

**Comment by tarekgh** [comment]
@AlexGhiondea 

These APIs are already there, please look at the following test which is calling these APIs

https://github.com/dotnet/corefx/blob/master/src/System.Text.Encoding/tests/UnicodeEncoding/UnicodeEncoding.netstandard1.7.cs

Note that these APIs are defined in the base Encoding class contract so UnicodeEncoding is getting them from there.
or you mean we need to explicitly mention these in the System.Text.Encoding.Extensions?
