### ISSUE TITLE
Array.ConvertAll not available in Core 5.0

### ISSUE THREAD

**Issue by gmj06** [dotnet/corefx#12821]
Hi All,

I was trying to convert string[] to int[] using Array.ConvertAll, which is giving me an error as following

'Array' does not contain the definition for 'ConvertAll'  under Core 5.0

Please Suggest

**Comment by mellinoe** [comment]
We are adding this back in a future release, but it's not available right now.

On the other hand, it's an extremely trivial function to implement:

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Array.cs#L1014
```CSharp
public static TOutput[] ConvertAll<TInput, TOutput>(TInput[] array, Converter<TInput,TOutput> converter)
{
    // Validation ...

    TOutput[] newArray = new TOutput[array.Length];
    for( int i = 0; i< array.Length; i++) {
        newArray[i] = converter(array[i]);
    }
    return newArray;
}
```

Feel free to use that implementation if you'd like.

**Comment by gmj06** [comment]
@mellinoe Thank you so much for sharing the information

I have seen couple of implementation as below 
#if DNX451 
   //Implementation
#endif
#if DNXCORE50
   //Implementation
#endif

So, I was curious to know new implementation in Core 5.0

**Comment by neil0609** [comment]
or you can use int[] intArray = stringArray.Select(int.Parse).ToArray();
