### ISSUE TITLE
CreateMtomReaderWriterTest fail

### ISSUE THREAD

**Issue by huanwu** [dotnet/corefx#12840]
Test fail because all member in XmlMtomReader and XmlMtomWriter class are not implemented.

**Comment by shmao** [comment]
I will remove the tests as the types have been removed from NetStandard2.0.

**Comment by shmao** [comment]
I rethought the issue. As the method, CreateMtomWriter, is still in NetStandard2.0, I'd prefer to keep the test as is for tracking XmlDictionaryWriter.CreateMtomWriter throwing PNSE. As we agreed to let the method throw PNSE for 1.2.0, I'm moving the bug to future.

/cc: @zhenlan @huanwu

**Comment by karelz** [comment]
We should delete the test or test just for PNSE.
