### ISSUE TITLE
Test coverage for `System.Math` and `System.MathF` should be expanded.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#12855]
Currently the test coverage for `System.Math` and `System.MathF` is fairly sparse, to say the least.

It should be expanded, at the very least, with the same set of tests that cover the native implementations in the CoreCLR PAL layer (which has a minimum of 20 tests per API and ensures that the interesting inputs are covered).

As part of this work, the tests should also be converted to use the `[Theory]` attribute.

**Comment by AlexGhiondea** [comment]
Anyone interested in taking this on?

**Comment by vcsjones** [comment]
@AlexGhiondea If you want to assign it to me, I can work on this.

**Comment by AlexGhiondea** [comment]
@karelz could you add @vcsjones to the contributor list?

**Comment by karelz** [comment]
Done, ping us here when you accept, then we can assign.

**Comment by vcsjones** [comment]
@karelz done.

**Comment by karelz** [comment]
@vcsjones just curious if you're still working on it ...

**Comment by vcsjones** [comment]
@karelz Ah! Sorry this one fell off my radar. Yes I will get a PR in very soon.

**Comment by karelz** [comment]
Great, no rush. I'm happy my nagging was useful at least once :) (to catch something accidentally dropped ;))

**Comment by tannergooding** [comment]
@vcsjones, are you still working on this? If not, I'm done with the other `System.MathF` bugs I had self-assigned and can start on this again.

**Comment by karelz** [comment]
2.5 months no progress, I think it is safe to assume @vcsjones didn't have much time so far - feel free to grab it @tannergooding.

**Comment by vcsjones** [comment]
Yes - I apologize. ☹️

**Comment by tannergooding** [comment]
@vcsjones, I do the same thing sometimes (as happened when I created the bug in October up until today, when I actually had some time again 😄)

**Comment by karelz** [comment]
Agreed, things happen, no worries @vcsjones ;-)
