### ISSUE TITLE
We should dynamicaly link into uCRT

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/corefx#12858]
And only statically link the CRT startup code.

**Comment by karelz** [comment]
@gkhanna79 what is the value of such change?

**Comment by gkhanna79** [comment]
We wont have the servicing burden of CRT, which will be taken care off by the OS.

**Comment by karelz** [comment]
That makes sense. Is there a list of CoreFX components that have dependency on uCRT? (I guess only a bunch of native components ...)
Isn't there overlap with CoreCLR dependency on uCRT?

**Comment by ianhays** [comment]
@gkhanna79 which lib is the "CRT startup code"?

Right now we statically link all libraries for Debug builds, but only statically link 2/3 for Release.

**Debug:**
Static: libcmtd.lib, libvcruntime.lib, libucrt.lib

**Release:**
Static: libcmtd.lib, libvcruntime.lib
dynamic: ucrt.lib

**Comment by gkhanna79** [comment]
> libcmtd.lib, libvcruntime.lib

These constitute the startup and general initialization code.

**Comment by alexperovich** [comment]
@gkhanna79 is there anything to do here then? It looks like we already dynamic link to uCRT.

**Comment by gkhanna79** [comment]
@ianhays should comment if he did any work for this?

**Comment by ianhays** [comment]
@gkhanna79 We were already dynamically linking to the ucrt and statically linking to the startup code. Is there anything else missing?

**Comment by gkhanna79** [comment]
Not that I am aware of. If everything is in place, please feel free to close the issue.



Thanks,
Gaurav


-------- Original message --------
