### ISSUE TITLE
Porting bug in System.CodeDom.CodeDomProvider for non existent languages and extensions

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#12868]
Opening, as I will submit a fix after #12867 is merged.

## NetFx
`CodeDomProvider.IsDefinedLanguage("no-such-language")`
returns `false`

## NetCore
`CodeDomProvider.IsDefinedLanguage("no-such-language")`
throws `KeyNotFoundException`

This is because we can't use `System.Configuration`

/cc @stephentoub

**Comment by hughbe** [comment]
Note: `IsDefinedLanguage` is not the only place this error propagates:
- IsDefinedLanguage (should return false)
- GetLanguageFromExtension (should throw System.Configuration.ConfigurationErrorsException)
- IsDefinedExtension (should return false)
- CreateProvider (should throw System.Configuration.ConfigurationErrorsException)

**Comment by karelz** [comment]
cc: @Priya91

**Comment by Priya91** [comment]
@hughbe Good catch! We should fix .NET Core to match Desktop behavior. What's the current behavior in .NET Core for cases where Desktop is throwing ``` System.Configuration.ConfigurationErrorsException```? Since ```Configuration``` is not exposed for netstandard2.0, we should keep .NET Core behavior as is for now for such cases.

**Comment by hughbe** [comment]
The current behaviour is throwing a `KeyNotFoundException`. However, if you look [here](https://github.com/dotnet/corefx/blob/master/src/System.CodeDom/src/System/CodeDom/Compiler/CodeDomProvider.cs#L211) then it seems that we've defined a private exception to throw in this case. 

Perhaps @stephentoub could clarify what the best course of action is (keep the KeyNotFoundException or use the private exception you added when porting)

I'm gonna submit a PR shortly
