### ISSUE TITLE
Consider the AOT case for APIs that not supported on all platforms.

### ISSUE THREAD

**Issue by AlexGhiondea** [dotnet/corefx#12861]
https://github.com/dotnet/corefx/pull/12765

**Comment by tarekgh** [comment]
@AlexGhiondea do you think you'll get this done in 2.0.0?

**Comment by karelz** [comment]
Will this be part of NS2.0 for UWP work? If yes, let's put it into 2.1 milestone.

**Comment by tarekgh** [comment]
I don't this AOT is UWP work but @AlexGhiondea can confirm.
