### ISSUE TITLE
Override the synchronous Stream.CopyTo for other Streams

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#12860]
Since `Stream.CopyTo` is now virtual, we should investigate overriding it for other Streams under `netcoreapp1.1`. For example, the ones in which @stephentoub suggested overriding the async version, like #12037 and #11573, could be candidates, although I'm not familiar with their implementation details. `FileStream` seems it could certainly benefit from overriding, since you can [see a `Buffer.BlockCopy` call](https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/FileStream.Win32.cs#L633) to the user-provided array. Same for `BufferedStream`.

Dependent upon #12598

**Comment by karelz** [comment]
Can you create a list of such streams?

**Comment by karelz** [comment]
cc @JeremyKuhne @ianhays

**Comment by karelz** [comment]
@jamesqo please let us know if you're working on it ...
