### ISSUE TITLE
xunit.console.corerun.exe choosing wrong .dll

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#1286]
xunit.console.corerun.exe doesn't use the complete folder path when running against a .dll

The command `corerun.exe xunit.console.netcore.exe System.Linq.Parallel.Tests.dll` (run from, say, `/bin/tests/Windows_NT.AnyCPU.Debug/System.Linq.Parallel.Tests/aspnetcore50`, where VS-built files _used_ to get placed...) runs against the .dll in the same folder.
The command `corerun.exe xunit.console.netcore.exe ../../../../Windows_NT.AnyCPU.Debug/System.Linq.Parallel.Tests/System.Linq.Parallel.Tests.dll` (where VS-built files are now being placed) checks that the specified file exists... and then runs against the .dll in the source folder.

The various msbuild commands/switches aren't affected, because the process copies over to the original folder for testing, but this isn't happening when building from VS.
I'll keep looking for other potential ways to run tests from the command line, but right now I'm a bit stuck.  Running stuff as part of the build is a bit too long for me - I'm not changing a library (mostly), I'm writing the tests (so I'm really only interested in running the tests I just wrote, not everything else).

As a side note, do we have any ETA on removing the xunit fork/running individual tests from VS?  Especially in the test window?  Last time I tried I couldn't run tests inside VS (via Ctrl+F5) - they weren't being discovered...

**Comment by weshaggard** [comment]
@eatdrinksleepcode I suspect this may be caused by the move on where you are running the CopyTestsToTestDirectory target.

**Comment by eatdrinksleepcode** [comment]
Will take a look.

**Comment by eatdrinksleepcode** [comment]
@Clockwork-Muse, can you clarify what scenario this is actually breaking? Is it building from VS and then running tests from the command line?

**Comment by Clockwork-Muse** [comment]
@eatdrinksleepcode - yes.
I think I'm more concerned with the fact that it end up looking at/for two different files (specified directory vs origin directory) than having to build from the command line.
Not having an easy way to run individual tests is annoying, though.  It increases cycle time for code-build-test quite a bit.

**Comment by Clockwork-Muse** [comment]
@eatdrinksleepcode , @weshaggard 

I haven't been able to find a way to get this working otherwise, I'm assuming that we're still waiting for corefx to pick up updated build tools...
Do we have an ETA for that?

As a side note, the barrier to testing seems artificially inflated for this project: 
 - no individual test run from IDE (and assuming build tools haven't been updated yet, currently runs against a different version than that compiled by the IDE...ouch), 
 - test debug runs all tests (b/c previous)
 - build+test script doesn't take parameters (not vanilla xunit ones, should I be trying something else?)
 - build-only script doesn't copy things over in prep for testing (only with testing script)

Is this something I should create an issue for?  Is any plan to change this dependent on the release of VS2015?  Or is my install just borked a little?

**Comment by eatdrinksleepcode** [comment]
@Clockwork-Muse 

> ...I'm assuming that we're still waiting for corefx to pick up updated build tools...

Correct. GitHub closed this issue because I marked the PR in BuildTools as fixing it, but it won't really be fixed until CoreFX picks up a new BuildTools package. I don't know on what frequency that happens; I believe publishing BuildTools is currently a manual step.

> build+test script doesn't take parameters (not vanilla xunit ones, should I be trying something else?)

You can pass xunit parameters to the build by setting the XunitOptions property:

```
msbuild /t:Test "/p:XunitOptions=-class Test.ComponentModelTests"
```

The wiki needs to be updated with this information.

> build-only script doesn't copy things over in prep for testing (only with testing script)

If the previous issues were resolved, would this still be an issue? I'm not sure why you would need to do this. However, if there is a compelling need, the CopyTestToTestDirectory target could be made independently runnable.

**Comment by Clockwork-Muse** [comment]
@eatdrinksleepcode - 
Thanks so much, that really helps.

Yeah, once the updated build tools are picked up that last one is less of an issue.  I'm just more curious about why the need to copy everything around like that.  Especially because each "source" test project ends up with the same copy of everything, as opposed to everything in one folder (or even no copying, but I'm assuming it only looks in the current folder to resolve references by default?).

**Comment by eatdrinksleepcode** [comment]
Yes, I would like to reduce the need for copying as well, but it is currently necessary (as you noted, dependencies are loaded from the same location as the test assembly). I have a couple of ideas on how to reduce or possibly eliminate that need, not only to reduce the amount of work done during a testing cycle, but also to reduce the required disk space. I am going to file an issue in BuildTools to track that, but I probably won't be able to get to it myself soon.
