### ISSUE TITLE
FileStream needs re-implemented for UAP10.1

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#12878]
`FileStream` is moving down to `System.Private.CoreLib`. The nested, multiplexing WinRT implementation we shipped with netcore5.0 needs re-implemented.

It isn't straightforward as we don't cross-compile CoreLib and the WinRT PAL lives in CoreFX. Some discussion around this has already taken place in PR #12809.

@jkotas, @ericstj, @ianhays

**Comment by danmosemsft** [comment]
Covered by https://github.com/dotnet/corefx/issues/15284
