### ISSUE TITLE
CI failure in NetworkAvailabilityChangedTests.NetworkAvailabilityChanged_JustRemove_Success

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#12886]
See https://ci.dot.net/job/dotnet_corefx/job/master/job/centos7.1_debug_prtest/2043/ for more details.

**Comment by stephentoub** [comment]
```
System.Net.NetworkInformation.Tests.NetworkAvailabilityChangedTests.NetworkAvailabilityChanged_JustRemove_Success [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
  Finished running tests. End time=08:35:49. Return value was 0
        Stack Trace:
              at System.Net.NetworkInformation.NetworkChange.remove_NetworkAvailabilityChanged(NetworkAvailabilityChangedEventHandler value)
```

**Comment by stephentoub** [comment]
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/centos7.1_debug_prtest/2097/consoleText

**Comment by stephentoub** [comment]
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/centos7.1_debug_prtest/2099/

**Comment by stephentoub** [comment]
(@karelz, FWIW, I think we should hold off on adding a "test bug" label until we know something isn't a product bug... in this case, it is a product bug)

**Comment by karelz** [comment]
> we should hold off on adding a "test bug" label until we know something isn't a product bug

I agree for areas which already went through initial catch-up triage, where we treat new test failures as P0-ish work items.
System.Net is not in that bucket yet and there is lots of debt in test failures investigations. During the catch-up triage we typically use label:"test bug" && milestone:1.2.0 to mark the debt and intent to investigate/address it for next release (1.2.0). From that perspective the "test bug" is helping with the triage. Not too much, so I don't mind skipping it for System.Net if you think it causes more trouble than value. The key point is that System.Net tests need some focused attention to dig itself out of the test failures debt and to be on top of new issues as P0-ish.
