### ISSUE TITLE
Bring remaining System.Data.SqlClient.SqlBulkCopy members

### ISSUE THREAD

**Issue by pdeligia** [dotnet/corefx#12887]
There are missing APIs from `System.Data.SqlClient.SqlBulkCopy` as seen in https://github.com/dotnet/standard/blob/bcf714ee4d6086d898fb7357972ae2827120ae7d/platforms/xamarin.ios/System.Data.cs#L2752, such as:

``` csharp
public void WriteToServer(System.Data.DataRow[] rows) { }
public void WriteToServer(System.Data.DataTable table) { }
public void WriteToServer(System.Data.DataTable table, System.Data.DataRowState rowState) { }
```

It would be great if these could become available.

**Comment by karelz** [comment]
cc @stephentoub - any thoughts?

**Comment by stephentoub** [comment]
> cc @stephentoub - any thoughts?

This is a question for @saurabh500.

**Comment by karelz** [comment]
cc: @weshaggard to comment on general netstandard2.0 guidance

**Comment by danmosemsft** [comment]
SqlBulkCopy is not in .NET standard 2.0 as it's SQL Server specific. The decision whether to add more to SqlBulkCopy is @saurabh500 's

**Comment by saurabh500** [comment]
@danmosemsft Are the APIs mentioned here used widely in Xamarin / Mono apps ?

**Comment by danmosemsft** [comment]
@saurabh500 Not according to our data.

**Comment by smosek** [comment]
Is there an easy workaround (writing a command with many insert statements is not what I consider easy)?
Would very much like to see this added.

**Comment by saurabh500** [comment]
Fixed with https://github.com/dotnet/corefx/pull/16884
