### ISSUE TITLE
Implement IEquatable on ImmutableCollection implementations

### ISSUE THREAD

**Issue by bordoley** [dotnet/corefx#1290]
Would it be possible to implement IEquatable on the concrete implementations of ImmutableStack etc. The benefit of this is that it allows the use of ImmutableCollections as hashkeys etc. It would also bring the immutable collections in line with their F# counterparts FSharpList, etc.

**Comment by KrzysztofCwalina** [comment]
I think Equals/GetHashCode,Compare should have O(1) complexity. Otherwise such APIs can become performance traps.

**Comment by ellismg** [comment]
When we first designed these types, we had IEquatable implemented.  However, during design reviews, feedback like @KrzysztofCwalina's pushed us to remove these interfaces.

We'd like to keep them off unless there was a super compelling reason to have value equality over stacks and other collections.  As is, we are worried about it being a pit of failure.

**Comment by sharwell** [comment]
This is what `IEqualityComparer<T>` is for, and it's widely supported by hash-based data structures in .NET.
