### ISSUE TITLE
IXmlTextReaderInitializerTest fail

### ISSUE THREAD

**Issue by huanwu** [dotnet/corefx#12902]
Throw InvaidCastException when call the following code, which works on desktop version.  
XmlDictionaryWriter textWriter = XmlDictionaryWriter.CreateTextWriter(stream, Encoding.UTF8, false);
IXmlTextWriterInitializer writerInitializer = (IXmlTextWriterInitializer)textWriter;

**Comment by shmao** [comment]
This was fixed by #13891. @huanwu, can you please update the actual cost for the issue? Thanks.
