### ISSUE TITLE
Add Option type

### ISSUE THREAD

**Issue by bordoley** [dotnet/corefx#1291]
C# lacks type safe semantics to express an optional value. This results in APIs which return null in order to express the lack of a result value. The negative impacts of null pointers are well documented, and an alternative already exists in F# in the form of FSharpOption. It would be useful to extend the BCL to natively support an Option type, preferably in a compatible fashion with the existing F# option type.

**Comment by Maxwe11** [comment]
dup #538

**Comment by bordoley** [comment]
resolving sorry i missed that one.
