### ISSUE TITLE
Microsoft.DiaSymReader.Native.x86.dll ends up in nuget package

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#12913]
Microsoft.DiaSymReader.Native 1.4.0 includes a .props file as included below. This includes a condition `!Exists('project.json') AND !Exists('$(MSBuildProjectName).project.json')`. The deprecation of project.json means that when users upgrade from a project.json build system to a MSBuild system (and thus deletes project.json), this .props file will include Microsoft.DiaSymReader.Native.{arch}.dll as 'content' in all projects using the .NET Core SDK.

Example: 
dotnet build3 on a netcoreapp will copy the file to the output directory

```
_CopyOutOfDateSourceItemsToOutputDirectory:
  Copying file from "C:\Users\namc\.nuget\packages\microsoft.diasymreader.native\1.4.0\runtimes\win\native\Microsoft.DiaSymReader.Native.x86.dll" to "bin\Debug\netcoreapp1.0\Microsoft.DiaSymReader.Native.x86.dll".
  Copying file from "C:\Users\namc\.nuget\packages\microsoft.diasymreader.native\1.4.0\runtimes\win\native\Microsoft.DiaSymReader.Native.amd64.dll" to "bin\Debug\netcoreapp1.0\Microsoft.DiaSymReader.Native.amd64.dll".
```

The extra file in the output directory may be harmless for "dotnet run", but it's still wrong for .NET Core projects which resolve native assets from the nuget cache.

**The worse problem is "dotnet pack3"**, which includes all 'content' items. This means Microsoft.DiaSymReader.Native.x86.dll and Microsoft.DiaSymReader.Native.amd64.dll will end up in the nuget package of anyone performing "dotnet pack3" on a csproj that uses Microsoft.NETCore.App.  

The offending props file, from .nuget\packages\microsoft.diasymreader.native\1.4.0\build\microsoft.diasymreader.native.props

``` xml
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Condition="!Exists('project.json') AND !Exists('$(MSBuildProjectName).project.json')">
    <Content Include="$(MSBuildThisFileDirectory)\..\runtimes\win\native\Microsoft.DiaSymReader.Native.x86.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
    <Content Include="$(MSBuildThisFileDirectory)\..\runtimes\win\native\Microsoft.DiaSymReader.Native.amd64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
  </ItemGroup>
</Project>
```

cc @emgarten @piotrpMSFT

**Comment by ericstj** [comment]
This isn't a CoreFx package, please open in https://github.com/dotnet/roslyn/issues

**Comment by joperezr** [comment]
thanks @ericstj I'll move this issue over to roslyn repo.

**Comment by joperezr** [comment]
Issue moved to [dotnet/roslyn #15137](https://github.com/dotnet/roslyn/issues/15137) via [**ZenHub**](https://www.zenhub.com/)
