### ISSUE TITLE
Code coverage is broken

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12927]
As can be seen in the latest report, it's only providing coverage for a single assembly out of 143 built.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/code_coverage_windows/Code_Coverage_Report/

It's at least partially related to https://github.com/dotnet/buildtools/issues/1144, but I expect there are issues beyond that, as when that issue was opened, the code coverage report was showing coverage for more than just one assembly.

cc: @karelz, @weshaggard, @MattGal, @mmitche

**Comment by crummel** [comment]
> No results, this could be for a number of reasons. The most common reasons are:
> 1) missing PDBs for the assemblies that match the filter please review the output file and refer to the Usage guide (Usage.rtf) about filters.
> 2) the profiler may not be registered correctly, please refer to the Usage guide and the -register switch.

The way we're using -register and filtering haven't changed, it seems like the PDBs might be the primary problem.  Our last good run before https://github.com/dotnet/buildtools/issues/1144 was filed was [http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/code_coverage_windows/38/Code_Coverage_Report/](#38), which has 90 assemblies reporting.  If @MattGal doesn't have time I can take a look.

**Comment by stephentoub** [comment]
> which has 90 assemblies reporting

I believe the real number should be closer to 110 or so, so even that 90 number was after some libs were already missing their PDBs (that's when we filed https://github.com/dotnet/buildtools/issues/1144).

> it seems like the PDBs might be the primary problem

Yeah, I expect that's the cause.  While there are a variety of PDB-related issues it could be, normally this happens when the PDB isn't deployed to the same directory as the associated .dll.

> If @MattGal doesn't have time I can take a look.

Thanks, @crummel!

**Comment by roncain** [comment]
For the record, [WCF](https://github.com/dotnet/wcf) just synced with CoreFx to have the current buildtools and is having the same issue.  We see the same warnings about PDBs, and all the intermediate coverage XML files look like this:

```
<?xml version="1.0" encoding="utf-8"?>
<CoverageSession xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="0" minCyclomaticComplexity="0" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0" />
  <Modules />
</CoverageSession>
```

/cc: @stephentoub @MattGal @crummel

**Comment by danmosemsft** [comment]
@crummel any update on this one?

**Comment by roncain** [comment]
This is getting to be a critical issue for WCF because we need to do coverage analysis during this current sprint.  If this gets fixed, could I ask someone to notify us of the build tools updates we need to make?

/cc: @crummel @danmosemsft

**Comment by crummel** [comment]
@danmosemsft @roncain PR https://github.com/dotnet/buildtools/issues/1205 fixes this issue, I'll let you know when it gets merged so you can take the new version of buildtools.

**Comment by crummel** [comment]
@roncain @danmosemsft @stephentoub Created PR https://github.com/dotnet/wcf/pull/1648 for WCF and https://github.com/dotnet/corefx/pull/13477 for CoreFx.

**Comment by crummel** [comment]
Fixed in https://github.com/dotnet/corefx/pull/13477.
