### ISSUE TITLE
Type.GetRuntimeMethod returns wrong method

### ISSUE THREAD

**Issue by ili** [dotnet/corefx#12921]
```cs
	    [Test]
	    public void GetRuntimeMethodTest()
	    {
		    var type = typeof(Int64?);
		    var paremeterType = typeof(int);

		    var method = type.GetRuntimeMethod("op_Implicit", new[] {paremeterType});

		    Assert.AreEqual(paremeterType, method.GetParameters()[0].ParameterType);
	    }
```

in this case `GetRuntimeMethod` returns method with `Int64` parameter, while I'm looking for `Int32`

**Comment by stephentoub** [comment]
@ili, on ```Nullable<T>```, there is only one defined ```op_Implicit``` method:
https://source.dot.net/#System.Private.CoreLib/src/System/Nullable.cs,78
```C#
public static implicit operator Nullable<T>(T value) {
    return new Nullable<T>(value);
}
```
Since in your example ```T``` == ```Int64```, the only op_Implicit method is one that takes an Int64.

**Comment by ili** [comment]
@safern but I'm looking method, with parameter type `Int32`!, `null` should be returned, because there are no method taking `Int32` 
This is according to MSDN: https://msdn.microsoft.com/en-us/library/system.reflection.runtimereflectionextensions.getruntimemethod(v=vs.110).aspx

I do refer that `GetRuntimeMethod` would return me method with name & parameters I'm looking for, and it returns me "something"?

**Comment by stephentoub** [comment]
> null should be returned, because there are no method taking Int32

Int32 is implicitly extended up to Int64.  If you changed ```var paremeterType = typeof(int);``` to ```var paremeterType = typeof(DateTime);``` for example, then it would return null.

**Comment by ili** [comment]
@stephentoub thanks for your reply

`op_Implicit` is used to make a convert avoiding boxing, this is a real code used:
```cs
		static Expression GetOperator(Type from, Type to, Expression p)
		{
			var op =
				to.GetMethodEx("op_Implicit", from) ??
				to.GetMethodEx("op_Explicit", from);

			return op != null ? Expression.Convert(p, to, op) : null;
		}
```

so when I'm getting method taking `Int64` as parameter a do have an exception on ` Expression.Convert(p, to, op)` because `to` is `Int32`

**Comment by stephentoub** [comment]
> do have an exception

It's possible there's a problem with Expression.Convert, but I'm having a bit of trouble following the example, e.g. I'm not sure what your ```from```, ```to```, and ```p``` arguments are.  If the real concern here is with Expression.Convert's behavior, can you open a separate issue for that?  If you can supply a short self-contained repro (e.g. a Main method that exhibits the unexpected exception), that'd be helpful.

**Comment by ili** [comment]
@stephentoub I'll try to do it today or tomorrow

**Comment by stephentoub** [comment]
> I'll try to do it today or tomorrow

Thanks, @ili.

**Comment by ili** [comment]
@stephentoub please see #12950 for `Expression.Convert` issue test
