### ISSUE TITLE
TestGetAsciiWithDot failing on several OSes

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12934]
@Clockwork-Muse, @tarekgh 

https://ci.dot.net/job/dotnet_corefx/job/master/job/opensuse42.1_release/384/
https://ci.dot.net/job/dotnet_corefx/job/master/job/opensuse42.1_debug/388/
```
     System.Globalization.Tests.IdnMappingGetAsciiTests.TestGetAsciiWithDot [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentException)
        Actual:   (No exception was thrown)
```

https://ci.dot.net/job/dotnet_corefx/job/master/job/fedora23_debug/449/
https://ci.dot.net/job/dotnet_corefx/job/master/job/fedora23_release/450/
```
System.ArgumentException : Decoded string is not a valid IDN name.
        Parameter name: unicode
        Stack Trace:
              at System.Globalization.IdnMapping.GetAsciiCore(Char* unicode, Int32 count)
              at System.Globalization.IdnMapping.GetAscii(String unicode, Int32 index, Int32 count)
              at System.Globalization.IdnMapping.GetAscii(String unicode, Int32 index)
              at System.Globalization.IdnMapping.GetAscii(String unicode)
           /mnt/resource/j/workspace/dotnet_corefx/master/fedora23_debug/src/System.Globalization.Extensions/tests/IdnMapping/IdnMappingGetAsciiTests.cs(101,0): at System.Globalization.Tests.IdnMappingGetAsciiTests.TestGetAsciiWithDot()
```

I'll refer to my comment on the original PR:
https://github.com/dotnet/corefx/pull/12783#discussion_r84326703
This is exactly the kind of wheel-spinning I wanted to avoid.  I would have preferred if the test remained as it was.

**Comment by Clockwork-Muse** [comment]
@stephentoub - although we've discovered that the behavior of OpenSUSE has changed.

... For the Linux platforms in the original tests, what was the gain?  It feels like the test was saying "this call might fail, it might succeed, we don't really care, or know, or track it...".  Well, it does ensure that the call either fails with a specific exception, or returns the original string, which is important, it's just that having the test not notice when the behavior changes (and this seems like a big change) feels worrisome.

(Not saying we couldn't go back to it, although I'd probably pull Windows/OSX out to their test, to be more explicit there)

**Comment by stephentoub** [comment]
> although we've discovered that the behavior of OpenSUSE has changed

Doesn't that further contribute to the notion that this is unspecified behavior on Linux, so trying to pin it down will just cause us continued grief?

> what was the gain?

What you stated: "it does ensure that the call either fails with a specific exception, or returns the original string, which is important"

> this seems like a big change

I don't know much about this particular test, but just from looking at it quickly, it seems like it fails in the majority of places (on Windows, on OSX, on most Linux distros), and only just happens to work on a few others.  It's much more important that we have tests that catch when something that works everywhere stops working, rather than having tests that catch when something that doesn't work starts working.

**Comment by tarekgh** [comment]
I agree with @stephentoub to revert the change done in this test cases to be resilient to the different platforms. I'll try to do this to unblock the CI

**Comment by tarekgh** [comment]
https://github.com/dotnet/corefx/pull/12957

**Comment by tarekgh** [comment]
This should be fixed now by the linked PR. Thanks.
