### ISSUE TITLE
Consider making the echo test servers able to not pickup websocket data.

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#12932]
I've been trying to tighten a couple of WebSocket tests (specifically that [multiple outstanding `SendAsync` calls  throws an exception](https://github.com/dotnet/corefx/blob/master/src/System.Net.WebSockets.Client/tests/SendReceiveTest.cs#L85)), but ended up running into a problem:
The internal, lower-level buffering means the data gets picked up, regardless of the delay in the server `Receive`ing the data.  
That is, in this:

```c#
await cws.SendAsync(
               WebSocketData.GetBufferFromText(".delay5sec"),
               WebSocketMessageType.Text,
               true,
               CancellationToken.None);

DateTime snd = DateTime.UtcNow;
await cws.SendAsync( // second send
              WebSocketData.GetBufferFromText("send buffer"),
              WebSocketMessageType.Text,
              true,
              CancellationToken.None);
TimeSpan sndTime = DateTime.UtcNow - snd;
DateTime rcv = DateTime.UtcNow;
await cws.ReceiveAsync(WebSocketData.GetBufferFromText("receive buffer"), CancellationToken.None);
TimeSpan rcvTime = DateTime.UtcNow - rcv;
```

... the second send completes almost instantaneously, while the receive delays 5 seconds.  I need the opposite - that the _send_ delays 5 seconds, then the subsequent receive completes instantly.

Note that my current assumption is that there's an underlying task on the server accepting reads even if the actual process is delayed for the 5 seconds, and thus I'm assuming we need a way to delay at a lower/outer level.  If I'm wrong (like, if the data may also be buffered on the sender side, and thus not something the test may be able to handle), please educate me.

**Comment by davidsh** [comment]
cc: @CIPop @stephentoub 

The "echo servers" are something that my team owns and we host it on corefx-net.cloudapp.net. It is not something that is completely open source at this point.  The code exists in a separate repo and it requires us to update the server.

**Comment by CIPop** [comment]
> The code exists in a separate repo and it requires us to update the server.

@davidsh @Clockwork-Muse Actually, the code is in this repo and scripts are available to deploy it on your own VMs: https://github.com/dotnet/corefx/tree/master/src/Common/tests/System/Net/Prerequisites

This is still work in progress (e.g. we don't have automatic deployment) but I can help updating the server after you've tested it locally.

**Comment by CIPop** [comment]
@Clockwork-Muse please feel free to contribute to the multi-machine effort. I have since added deployment scripts and tested the environment on 3 VMs. See the readme at: https://github.com/dotnet/corefx/tree/master/src/Common/tests/System/Net/Prerequisites

After testing out your change, we would be able to update the public server-side as well.

**Comment by stephentoub** [comment]
We have a loopback server for web sockets now, which allows tests to be written that control both sides of the pipe and how fast or slow they respond.
