### ISSUE TITLE
Xamarin form using OPC UA Client SDK fails to Session Connect

### ISSUE THREAD

**Issue by CarlCrol** [dotnet/corefx#12948]
Working on creating a Xamarin.form Android App using Xamarin.form fails to Session.Connect. throws an error connection refused. Is the SDK supports Xamarin.forms?
Is there samples on how to use the .net core sdk in xamarin forms?

**Comment by karelz** [comment]
@weshaggard don't we need NS2.0 APIs (Xamarin compat) to support Xamarin forms?

cc: @danmosemsft

**Comment by weshaggard** [comment]
>@weshaggard don't we need NS2.0 APIs (Xamarin compat) to support Xamarin forms?

I suspect that isn't enough. @akoeplinger are you aware of anyone working on enabling Xamarin forms on top of .NET Core?

**Comment by akoeplinger** [comment]
That'd be a question for @rmarinho

**Comment by rmarinho** [comment]
We are planning a move to NS.. but still working the details out since UWP support for 2.0 is behind schedule. 
At the time we could only move to NS1.4 so we could support UWP and others. 
That said it should be compliant using the PCL shim package on your NS project no?

**Comment by CarlCrol** [comment]
Confused on the answers so opc ua sdk will still not work on xamarin.android right?

**Comment by karelz** [comment]
Xamarin Forms are not yet supported on .NET Core.

I don't know what UPC UA SDK exactly is (doesn't seem to be part of Xamarin) -- you might want to reach out to the project owners & maintainers.

**Comment by tarekgh** [comment]
closing the issue here and @rmarinho may be able to help answering the Xamarin questions.
