### ISSUE TITLE
New System.Net.Requests tests are in a mis-matching namespace

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#12953]
@geoffkizer 
I noticed with the new FTP tests that their namespace is System.Net.Tests:
https://github.com/dotnet/corefx/blob/d324c82ec8ada48d690eb65381606c93989e9654/src/System.Net.Requests/tests/FtpWebRequestTest.cs#L13 

Ideally this should be  System.Net.Requests.Tests as later on it makes it much easier to follow test results back to their test assembly.

**Comment by geoffkizer** [comment]
I think I was following FileWebRequestTest.cs here.  I'll go through and clean these all up.

**Comment by stephentoub** [comment]
> Ideally this should be System.Net.Requests.Tests as later on it makes it much easier to follow test results back to their test assembly.

This goes against the guidelines we have for the repo.  A test for class Namespace.Class should be in Namespace.Tests.  It sounds like @geoffkizer has it set up correctly.

**Comment by MattGal** [comment]
I stand corrected;  I still think it's confusing and made it hard to find my way backwards on test failures.

**Comment by stephentoub** [comment]
Here's the relevant issue: https://github.com/dotnet/corefx/issues/2898.  You can see a lot of work has gone into conforming to this.  If we want to revisit it, we should discuss it on that issue before making any changes to move away from it.

**Comment by MattGal** [comment]
No, I'm fine leaving things as-is especially if they're actually consistent.  I was simply checking out a test failure for "System.Net.Tests.FtpWebRequestTest" and find it frustrating there's no assembly anywhere named System.Net.Tests.dll.  The name of the assembly is how work items in .NET Helix are listed, so I just had to do the extra lookup step to realize this would be in System.Net.Requests.Tests.

**Comment by geoffkizer** [comment]
What's the FtpWebRequestTest failure you're seeing?

**Comment by Clockwork-Muse** [comment]
@MattGal - We essentially have that issue anyways, since some of the regular source namespaces don't match the folder namespace.
