### ISSUE TITLE
Expression.Convet System.InvalidOperationException

### ISSUE THREAD

**Issue by ili** [dotnet/corefx#12950]
This test sample 

``` cs
        [Test]
        public void ConvertTest()
        {
            var from = typeof(Int64?);
            var to = typeof(int);
            var p = Expression.Constant((Int64?)101);

            var method = from.GetRuntimeMethod("op_Implicit", new[] {to});

            var expression = Expression.Convert(p, to, method);
        }
```

falls with exception

```
System.InvalidOperationException : The operands for operator 'Convert' do not match the parameters of method 'op_Implicit'.
   at System.Linq.Expressions.Expression.GetMethodBasedCoercionOperator(ExpressionType unaryType, Expression operand, Type convertToType, MethodInfo method)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)
   at Tests.NetCore.ReflectionTests.ConvertTest() in F:\job\linq2db\Tests\Tests.NetCore\ReflectionTests.cs:line 51
```

**Comment by stephentoub** [comment]
cc: @bartdesmet, @VSadov

**Comment by zabulus** [comment]
This fails also on .NET Desktop.
I'm not sure what are you trying to achieve but exception seems legitimate. 
You are trying convert ```Int64?``` constant to ```int``` using method with following declaration:
```Nullable<Int64>op_Implicit(Int64 value)```
Following runs successfully:
```
            var from = typeof(Int64?);
            var to = typeof(int);
            var to2 = typeof(Int64?);
            var p = Expression.Constant((Int64?)101);

            var method = from.GetRuntimeMethod("op_Implicit", new[] { to });

            var expression = Expression.Convert(p, to2, method); // <--- to replaced with to2
```

**Comment by ili** [comment]
@zabulus yes, you are right, about  .Net Desktop, I'v done test too, an it fails... 

speaking about the goal  - is to build convert expression from one type to another (so `p` is just an expression returning value with `from` type). So the idea is to find if `from` type defines implicit convert to `to` type, and use it if possible

**Comment by JonHanna** [comment]
`Convert(p, to)` will already find an available `op_Implicit` if it exists. It will though also use `op_Explicit` if it exists instead, built-in conversions when applicable, and lifted conversions when applicable.

Is there a reason why you want to not use some of those possible conversions if they are the only forms available?

As is:

```C#
Expression.Convert(Expression.Constant((Int64)101, typeof(Int64?)), typeof(int)) // evaluates to 101 (Int32)
Expression.Convert(Expression.Constant((Int64)null, typeof(Int64?)), typeof(int)) // invalid operation on evaluation, because it's trying to coerce null into non-nullable type.
Expression.Convert(Expression.Constant(Int64.MaxValue, typeof(Int64?)), typeof(int)) // evaluates to -1
Expression.ConvertChecked(Expression.Constant(Int64.MaxValue, typeof(Int64?)), typeof(int)) // overflow exception on evaluation
```

Do you need something beyond that?

BTW, `Expression.Constant((Int64?)101)` isn't of `Int64?` type, because an `Int64` and an `Int64?` that isn't null both box to `Int64` so in trying to detect the type the `Constant()` method will decide the type is `Int64`. If you need an `Int64?` constant you have to explicitly set the type: `Expression.Constant((Int64?)101, typeof(Int64?))` or `Expression.Constant(101L, typeof(long?))` etc.

**Comment by ili** [comment]
We are building universal convert expression (it is the part of `IDataReader` to object mapping). So we can define source and destination types only in runtime. So looking for `op_Implicit` and `op_Explicit` is only one of the steps. 

And it's really strange that we haven't faced with this issue before, as mentioned above it is the same on previous .net versions

Speaking about the test, it is just to demonstrate the issue, in real world we do not have constant expressions.

**Comment by JonHanna** [comment]
Again though, if you want to create a conversion expression between types at runtime, then why not just use `Convert(typedExpression, convertToType)` and let the factory decide which approach (built-in conversions, implicit operator, explicit operator) is available, if any.

To consider you're starting point of having a typed value `p` (that we can set to `Expression.Constant(101L, typeof(long?))` for the sake of example) and you want to cast it to a given type `to` then `Expression.Convert(p, to)` will work.

Even when hunting for `op_Implicit` or `op_Explicit` is the right approach, it's the approach that the `Convert` method will take itself.

Meanwhile, it may not be the right approach. With the example of casting a nullable 64-bit integer to a non-nullable 32-bit integer, as in the original post, the method used by `Convert` is a call to the `Value` property followed by the `conv.i4` CIL instruction.

**Comment by ili** [comment]
Thanks, I'll think about it :)

**Comment by ili** [comment]
@

**Comment by ili** [comment]
@JonHanna may be you can advice me, how can I check that `Convert` expression would be called without exception?

**Comment by JonHanna** [comment]
If I wanted to know that, without triggering an exception, I'd duplicate the all of the checks that `Convert` itself does and see if it would hit a case where it throws.

TBH, I'd probably start of by just `try`ing and seeing if it threw as the easiest thing to code quickly, and then go to be effort of duplicating its checks if there were a lot of impossible conversions being hit and it had a performance impact. Below a certain percentage of impossible conversions though then assuming you want to use the expression when it could be made it'd be cheaper to take the hit from the occasional throw than it would be to double up on the work done by the `Convert` method.

**Comment by JonHanna** [comment]
In any case, tracing through how the method works for different possible types will likely be informative: https://github.com/dotnet/corefx/blob/master/src/System.Linq.Expressions/src/System/Linq/Expressions/UnaryExpression.cs#L747

**Comment by ili** [comment]
@JonHanna thanks a lot for your help!
