### ISSUE TITLE
Failure in InvalidComObjectExceptionTests.SerializationRoundTrip

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#12979]
See [here](https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/2098/testReport/junit/System.Runtime.InteropServices.Tests/InvalidComObjectExceptionTests/SerializationRoundTrip):

```
MESSAGE:
Assert.Equal() Failure\r\n ↓ (pos 266)\r\nExpected: ···tterHelpers.cs:line 31\r\nActual: ···tterHelpers.cs:line 26\r\n ↑ (pos 266)
+++++++++++++++++++
STACK TRACE:
at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterHelpers.AssertRoundtrips[T](T expected, Func`2[] additionalGetters) in D:\j\workspace\windows_nt_de---4526f5ff\src\Common\tests\System\Runtime\Serialization\Formatters\BinaryFormatterHelpers.cs:line 39 at System.Runtime.InteropServices.Tests.InvalidComObjectExceptionTests.SerializationRoundTrip() in D:\j\workspace\windows_nt_de---4526f5ff\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServices\InvalidComObjectExceptionTests.cs:line 18
```

**Comment by bartdesmet** [comment]
Seems like the serialized exception data contains the stack trace and line offsets are different.

**Comment by bartdesmet** [comment]
More such errors @ https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/2094/

**Comment by stephentoub** [comment]
And others:
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/2133/consoleText
```
System.Runtime.InteropServices.Tests.MarshalDirectiveExceptionTests.SerializationRoundTrip [FAIL]
        Assert.Equal() Failure
                                         ↓ (pos 294)
        Expected: ···tterHelpers.cs:line 31
        Actual:   ···tterHelpers.cs:line 26
                                         ↑ (pos 294)
        Stack Trace:
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/Common/tests/System/Runtime/Serialization/Formatters/BinaryFormatterHelpers.cs(39,0): at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterHelpers.AssertRoundtrips[T](T expected, Func`2[] additionalGetters)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/MarshalDirectiveExceptionTests.cs(18,0): at System.Runtime.InteropServices.Tests.MarshalDirectiveExceptionTests.SerializationRoundTrip()
     System.Runtime.InteropServices.Tests.InvalidOleVariantTypeExceptionTests.SerializationRoundTrip [FAIL]
        Assert.Equal() Failure
                                         ↓ (pos 294)
        Expected: ···tterHelpers.cs:line 31
        Actual:   ···tterHelpers.cs:line 26
                                         ↑ (pos 294)
        Stack Trace:
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/Common/tests/System/Runtime/Serialization/Formatters/BinaryFormatterHelpers.cs(39,0): at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterHelpers.AssertRoundtrips[T](T expected, Func`2[] additionalGetters)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/InvalidOleVariantTypeExceptionTests.cs(18,0): at System.Runtime.InteropServices.Tests.InvalidOleVariantTypeExceptionTests.SerializationRoundTrip()
```
This only just started, yet the code for BinaryFormatter hasn't changed in a long time; I also don't believe we took a coreclr update when most of them happened.  It also appears to be happening sporadically across different exception types and different OSes, but all of the ones I've seen have been in the System.Runtime.InteropServices.Tests test suite.

**Comment by stephentoub** [comment]
@jkotas, we use this BinaryFormatterHelper.AssertRoundtrips function:

to serialize and deserialize lots of different exception types in corefx, e.g.
https://github.com/dotnet/corefx/blob/c5abd4a0b4c299cb49098f7ebd33ff22e3914568/src/System.Runtime.Serialization.Formatters/tests/BinaryFormatterTests.cs#L387
https://github.com/dotnet/corefx/blob/2117bae3a6c9736033e6d1659821ff3a1069920b/src/System.Text.RegularExpressions/tests/Regex.Serialization.cs#L49
https://github.com/dotnet/corefx/blob/2172d3f9c324ac8add4f34a44597911049e58092/src/Microsoft.Win32.Primitives/tests/Win32Exception.netstandard1.7.cs#L28
and we've never seen a problem.

But in the last day, we've seen these failures in the tests in System.Runtime.InteropServices.Tests:
https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=SerializationRoundTrip
Any idea what might be special about these particular exception types that could cause them to exhibit this problem sporadically?

**Comment by jkotas** [comment]
This is dup of https://github.com/dotnet/corefx/issues/12467. @alexperovich and @mikem8361 are looking into it.

I suspect that it is caused by PDB reading failing intermittently and the failure being ignored (the PDB reading is under a big catch block).
