### ISSUE TITLE
Cannot instantiate System.Net.Http.HttpClientHandler on OS X with new package

### ISSUE THREAD

**Issue by vors** [dotnet/corefx#12983]
## Repro

Create a simple project on OS X with System.Net.Http.HttpClientHandler

project.json

``` json
{
    "name": "test",
    "version": "1.0.0-*",

    "buildOptions": {
        "emitEntryPoint": true
    },

    "frameworks": {
        "netcoreapp1.0": {
            "dependencies": {
                "System.Net.Http": "4.3.0-preview1-24530-04",
                "Microsoft.NETCore.App": "1.1.0-preview1-001100-00"
            }
        }
    },

    "runtimes": {
        "osx.10.11-x64": { }
    }
}

```

Program.cs

``` csharp
using System;

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("Hello World! " + new System.Net.Http.HttpClientHandler());
    }
}
```

Use `dotnet run` to run the program.
## Expected

`Hello World!System.Net.Http.HttpClientHandler`
## Actual

Ctor exception

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Http' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.CryptoInitializer.EnsureOpenSslInitialized()
   at Interop.CryptoInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.CryptoInitializer.Initialize()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.HttpInitializer.Initialize()
   at Interop.Http..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at Program.Main(String[] args) in /Users/vors/dev/dotnet-http-bug-test/Program.cs:line 7
```
## Environment

OS X 10.11.6 x64

dotnet cli tool

```
PS /Users/vors/dev/dotnet-http-bug-test> dotnet --info                                                                                       
.NET Command Line Tools (1.0.0-preview3-003857)

Product Information:
 Version:            1.0.0-preview3-003857
 Commit SHA-1 hash:  060762090d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

**Comment by karelz** [comment]
@bartonjs looks like OpenSSL can't be loaded, can you please help troubleshoot here?
cc: @steveharter

**Comment by vors** [comment]
I actually was able to fix the problem with patching dylib for openssl:
https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#openssl

**Comment by vors** [comment]
Sorry, the patching helped for the older lib (4.1.0), but not the the preview3 one

```json
{
    "name": "test",
    "version": "1.0.0-*",

    "buildOptions": {
        "emitEntryPoint": true
    },

    "frameworks": {
        "netcoreapp1.0": {
            "dependencies": {
                "System.Net.Http": "4.1.0",
                "Microsoft.NETCore.App": "1.0.0"
            }
        }
    },

    "runtimes": {
        "osx.10.11-x64": { }
    }
}
```

^^^ here patching openssl works fine

**Comment by bartonjs** [comment]
@vors have you added the symlinks as documented on https://www.microsoft.com/net/core#macos?

```sh
$ ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
$ ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
```

You may need to `mkdir /usr/local/lib` first.

**Comment by vors** [comment]
Right, so about that. If I add these symlinks everything works. Meanwhile, that would mean that we are asking all customers (not only devs) to do the same. `brew` stopped support this scenario because it opens a [security vulnerability](http://stackoverflow.com/questions/38670295/brew-refusing-to-link-openssl). Our approach was to patch the rpath with `install_name_tool` in the dylibs directly:

```
find ~/.nuget -name System.Security.Cryptography.Native.dylib | xargs sudo install_name_tool -add_rpath /usr/local/opt/openssl/lib
find ~/.nuget -name System.Net.Http.Native.dylib | xargs sudo install_name_tool -change /usr/lib/libcurl.4.dylib /usr/local/opt/curl/lib/libcurl.4.dylib
```

This way, we can avoid creating a system-wide security problem and localize the lookup only to dotnet assemblies.
For some reason, it doesn't work anymore, when we switched from 4.1.0 to 4.3.0-preview1-24530-04
Can you, please help me understand this new behavior?

**Comment by bartonjs** [comment]
@vors Symlinking in the libraries with the version numbers does not create a security vulnerability.  The problems come from the headers being in /usr/local/include and the unversioned forwarder being in /usr/lib; because the compiler uses the new headers while the linker mates against the old library.

Since we only pull in the version-stamped assets there's no vulnerability, otherwise we wouldn't have it as our official installation instructions.

**Comment by vors** [comment]
Thank you for the clarification!
We would still want to avoid creating symlinks because it complicates the installation instructions for customers. It's ok for devs, but not for users.
Changing rpath should be possible and seems cleaner.

**Comment by bartonjs** [comment]
@vors The problem with the rpath approach is that a) MacPorts installs to a different location than Homebrew, so MacPorts users need a different rpath (and different symlinks, but they've to date not made as much of a fuss) and b) Homebrew even supports having a different path (and Homebrew users making use of that feature know enough to rewrite our instructions to suit their needs).

Our medium term plan is to not have a (default) OpenSSL dependency on macOS, #9394 tracks that work.  (The dependency will still be there for anyone who specifically calls out OpenSSL, but absent someone writing `new RSAOpenSsl()` it wouldn't be the case)

Our installer should actually be creating the symlinks now, I thought, at least if OpenSSL is already present in the default location.  @blackdwarf: we (you) did that change, right?

**Comment by blackdwarf** [comment]
@bartonjs yep, I did.

**Comment by bartonjs** [comment]
Since this looks a little bit like a now-fixed packaging bug, and a little bit like a missing prereq, and the original opener has said that things were working for him, I'm going to go ahead and close this.
