### ISSUE TITLE
Socket tests are not running in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12994]
As evidenced by this PR, which added a failing innerloop and outerloop test, yet all legs passed.
https://github.com/dotnet/corefx/pull/12988

You can see in the log, for example this one on Windows at https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/2117/consoleText, that System.Net.Sockets.Tests gets built:
```
  System.Net.Sockets.Tests -> D:\j\workspace\windows_nt_de---4526f5ff\bin\Windows_NT.AnyCPU.Debug\System.Net.Sockets.Tests\System.Net.Sockets.Tests.dll
```
but that's the only reference to the suite in the whole log... it's never executed.

I don't know if there are other suites like this, nor do I know how long it's been this way, but it's concerning.

cc: @davidsh, @cipop, @ericeil, @geoffkizer, @weshaggard

**Comment by weshaggard** [comment]
@joperezr is planning to write a tool to inspect which test build configurations are running and which are being ignored to try and help with this type of issue.
