### ISSUE TITLE
ValueTuple should support mscorlib-based PCL in 1.1 release

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#13001]
We made a fix to add a build of ValueTuple that works on mscorlib-based frameworks (net 4.0 and silverlight) as requested by ML / F#.  We need to port this to the 1.1 branch so that it releases with the first stable release of the ValueTuple package.

/cc @jcouv @KevinRansom

**Comment by karelz** [comment]
Fixed in PR #12823
