### ISSUE TITLE
Move Microsoft.NetCore.Portable.Compatibility package to assets to CoreFX

### ISSUE THREAD

**Issue by SedarG** [dotnet/corefx#13020]
This package gets invalidated as we move types around. One example is, System.Runtime.CompilerServices.IsConst, which moved out of System.Private.Corelib into System.Runtime. mscorlib in the Compatibility package still has a typeforward to System.Private.CoreLib, which is causing issues on .Net Native scenarios.

**Comment by weshaggard** [comment]
The shims are now being produced (https://github.com/dotnet/corefx/blob/master/src/shims/shims.proj). They are only included in the Microsoft.NETCore.App package currently but we will also need to add them to the UWP package once we do that work.
