### ISSUE TITLE
[ARM/CI] CI cannot find arm-hardfp rootfs image

### ISSUE THREAD

**Issue by wateret** [dotnet/corefx#13033]
The CI job linuxarmemulator_hardfp_cross_debug fails.

The error message is:

```
22:33:07 + ./scripts/arm32_ci_script.sh --emulatorPath=/opt/linux-arm-emulator --mountPath=/opt/linux-arm-emulator-root --buildConfig=debug --verbose
22:33:08 ERROR: Path specified in --emulatorPath does not have the rootfs
22:33:08 The script is exited. Cleaning environment..
```

Which means that CI does not have `/opt/linux-arm-emulator/platform/rootfs-u1404.ext4` but I already sent this file to CI.

@jashook Could you please check?

**Comment by jashook** [comment]
@wateret this is a weird issue. I see the emulator path when creating vm manually; however, cannot see it from the machines jenkins is imaging. @mmitche I can sync up with you on this when you are free.

**Comment by wateret** [comment]
@jashook @mmitche @RussKeldorph  Could you please take a look?

**Comment by mmitche** [comment]
@jashook What was the azure image that was used?

**Comment by wateret** [comment]
It is good now. Closing.
