### ISSUE TITLE
XmlConvertTests.XmlConvertTests.ToTypeTests failing in outerloop

### ISSUE THREAD

**Issue by mmitche** [dotnet/corefx#1303]
MESSAGE:
Assert.Equal() Failure Expected: 0 Actual: 1
+++++++++++++++++++
STACK TRACE:
at XmlConvertTests.XmlConvertTests.RunTestCase(CTestBase testCase) in d:\j\workspace\dotnet_corefx_outerloop\src\System.Xml.ReaderWriter\tests\XmlConvert\XmlConvertTests.cs:line 208 at XmlConvertTests.XmlConvertTests.ToTypeTests() in d:\j\workspace\dotnet_corefx_outerloop\src\System.Xml.ReaderWriter\tests\XmlConvert\XmlConvertTests.cs:line 57

**Comment by krwq** [comment]
@mmitche @JeremyKuhne I'm unable to repro, could you provide me with some more details about the failure? (What machine/culture/os are you running on)

**Comment by mmitche** [comment]
That was on 2012 R2,. en-us.  Jeremy disabled the test, so make sure you reenable:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx_outerloop/394/testReport/

**Comment by JeremyKuhne** [comment]
Note that I didn't disable it, for some reason it is tagging me from a sync on my own fork.

**Comment by mmitche** [comment]
This no longer repros at all.

**Comment by stephentoub** [comment]
I re-enabled the test, and it reproed in the very next outerloop run:
```
07:01:13   Expected: 2002-12-30T23:15:55.1+00:00
07:01:13   Actual  : 2002-12-30T23:15:55.1Z
07:01:13   	ToString(DateTime) - valid cases
07:01:13   unexpected exception happened:datetime
07:01:13      at OLEDB.Test.ModuleCore.CError.Compare(Object actual, Object expected, String message) in d:\j\workspace\outerloop_win---c2e2123a\src\Common\tests\System\Xml\ModuleCore\cerror.cs:line 224
07:01:13      at System.Xml.Tests.ToTypeTests.ToType40() in d:\j\workspace\outerloop_win---c2e2123a\src\System.Xml.ReaderWriter\tests\XmlConvert\ToTypeTests.cs:line 608
07:01:13      at OLEDB.Test.ModuleCore.CVariation.Execute() in d:\j\workspace\outerloop_win---c2e2123a\src\Common\tests\System\Xml\ModuleCore\cvariation.cs:line 75
07:01:13      at OLEDB.Test.ModuleCore.CTestCase.Execute() in d:\j\workspace\outerloop_win---c2e2123a\src\Common\tests\System\Xml\ModuleCore\ctestcase.cs:line 70
07:01:13   	 FAILED
```

**Comment by stephentoub** [comment]
Is this related to https://github.com/dotnet/corefx/pull/6981?
