### ISSUE TITLE
WebUtility.HtmlDecode does not decode all HTML5 character entities

### ISSUE THREAD

**Issue by devatwork** [dotnet/corefx#13036]
The current character entity replace dictionary used inside WebUtility uses the entity set as defined in HTML4, see https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/Net/WebUtility.cs#L757.

However, the HTML5 spec defines additional entities, see https://www.w3.org/TR/html5/syntax.html#named-character-references.

I'm willing to send a PR to include the new named character references, if this that would be an acceptable change to the behavior of WebUtility.HtmlDecode. Any specific guidance with respect to making this change? Are there specific areas that need to be addressed?

**Comment by karelz** [comment]
Sounds like reasonable thing to do. @davidsh @CIPop any suggestions?

**Comment by karelz** [comment]
Feel free to submit a PR.
Guidance:
* We should avoid breaking compat -- i.e. do not change existing 'wrong' code (if you find any). Such changes should be discussed explicitly upfront.
* Add test coverage

**Comment by karelz** [comment]
Continued design discussion from the PR https://github.com/dotnet/corefx/pull/13152#issuecomment-258709914:
@DamianEdwards do you have suggestion how to go from here?

The safe route is to introduce just yet-another class for HTML5 only.

**Comment by karelz** [comment]
@DamianEdwards ping?

**Comment by karelz** [comment]
Triage: Very little interest in last 3 years (just 2 upvotes). Let's close it. If it has higher demand, we can reconsider.
