### ISSUE TITLE
Release the Microsoft.Experimental.Collections.MultiValueDictionary

### ISSUE THREAD

**Issue by dsaf** [dotnet/corefx#1306]
As far as I understand it is pretty much implemented, yet there were no updates for over 7 month and it is still alpha.

https://www.nuget.org/packages/Microsoft.Experimental.Collections

http://blogs.msdn.com/b/dotnet/archive/2014/08/05/multidictionary-becomes-multivaluedictionary.aspx

PS: is there a better GitHub repository to post it in?

**Comment by FiveTimesTheFun** [comment]
Thanks @dsaf - I was thinking about this recently.  I was thinking about putting it first in https://github.com/dotnet/corefxlab until it became RTM quality.

**Comment by KrzysztofCwalina** [comment]
Yeah, seems like corefxlab would be a great place for this.

**Comment by sharwell** [comment]
So this is like `ILookup<TKey, TValue>`, except that it can be modified?

**Comment by dsaf** [comment]
Roslyn guys had to implement one themselves it seems:

https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/InternalUtilities/MultiDictionary.cs

**Comment by codekaizen** [comment]
Who owns the code for this and can commit it to corefxlab?

**Comment by ianhays** [comment]
Sorry for the delay; it's been real busy around here! I just pushed a PR https://github.com/dotnet/corefxlab/pull/370 to get this into CorefxLab where we can continue iterating on it until it's ready for CoreFX. For now it is in it's own assembly: System.Collections.Generic.MultiValueDictionary. I tested it with some console apps running on the core framework and it works as expected.
