### ISSUE TITLE
ReflectionOnly Mode not Supporting ISerializable

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#13071]
PR https://github.com/dotnet/corefx/pull/13068 enabled DCS/DCJS to serialize ISerializable types. We still need to make changes to enable reflection based serialization to support ISerializable. The following test in System.Runtime.Serialization.Xml.ReflectionOnly.Tests are failing,

```
DataContractJsonSerializerTests.DCJS_MyISerializableType
DataContractSerializerTests.DCS_ExceptionObject
DataContractSerializerTests.DCS_InnerExceptionMesageWithSpecialChars
DataContractSerializerTests.DCS_ExceptionMesageWithSpecialChars
DataContractSerializerTests.DCS_ArgumentExceptionObject
DataContractSerializerTests.DCS_MyISerializableType
```

To fix this, take a look at PR https://github.com/dotnet/corefx/pull/13068 first, and changes probably need to be made in the following files,
```
ReflectionXmlFormatReader.cs
ReflectionXmlFormatWriter.cs
ReflectionJsonFormatReader.cs
ReflectionJsonFormatWriter.cs
```

**Comment by karelz** [comment]
Next step: Get it under debugger and find out what's wrong.
