### ISSUE TITLE
Add netcoreapp1.1 test configurations for System.Private.Xml.Linq projects

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#13085]
The following projects don't currently have a netcoreapp1.1 configuration which means that they are not being tested as part of CI. I tried adding it but a bunch of tests failed, so I left them as is for now, but this issue is to track the fixing of those tests and the addition of the netcoreapp1.1 configurations.

```
XsltScenarios.Tests.csproj
System.Xml.Linq.Events.Tests.csproj
System.Xml.Linq.Properties.Tests.csproj
System.Xml.Linq.Streaming.Tests.csproj
System.Xml.Linq.xNodeBuilder.Tests.csproj
System.Xml.Linq.xNodeReader.Tests.csproj
```

cc: @krwq @sepidehMS @danmosemsft

**Comment by sepidehMS** [comment]
Done by https://github.com/dotnet/corefx/pull/13197
