### ISSUE TITLE
Compatiblity Issue of Serializing Custom Exceptions

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#13099]
Opened the issue per @mconnew 's comments in PR #13068 on removing `ExceptionDataContract`,

> I presume this was removed because exceptions are now ISerializable? If that's the case, then this might be a breaking change. Someone targeting an earlier version of .Net Standard won't have ISerializable available so won't have a serialization constructor. What will happen if they now try to deserialize a previously serialized derived exception while running on the newer version? Will they have different behavior?

**Comment by danmosemsft** [comment]
@weshaggard what is our compat level for cross-version binary serialization? I'm not aware that we attempt to test it. I understand we don't plan to support cross-framework.

**Comment by weshaggard** [comment]
I'm not sure we have stated our version-to-version serialization expectations. Perhaps @zhenlan or @stephentoub who implemented binary serialization for core would know.

**Comment by shmao** [comment]
Sorry for any confusion caused by the issue. The issue is not related to binary serialization. The compatibility issue is with DataContractSerializer (DCS) who has different behaviors when serializing exception types before/after PR #13068. After the fix, DCS requires exception types implement the following constructor,

```
ctor(SerializationInfo, StreamingContext)
```

**Comment by shmao** [comment]
We discussed this issue offline. We didn't see a good solution to avoid the breaking change. We wanted to get rid of `ExceptionDataContract` as it was just a temporary workaround for serializing Exception types when `System.Runtime.Serialization.ISerializable` was not available on NetCore. `ExceptionDataContract` could serialize only a few fields of Exceptions and the payload was not compatible with full framework's. We didn't want to continue to support such behavior.

This breaking change would impact users who have custom Exception types that do not have a constructor with the following signature,

`ctor(SerializationInfo, StreamingContext)`

For users who have Exception types like this and are serializing the types today and want to migrate to NetCore 2.0, they would need to implement the above constructor for the Exception types.

/cc: @zhenlan @mconnew @karelz
