### ISSUE TITLE
FxCop: System.Net.Sockets.Socket rethrows caught exceptions without using the rethrow statement

### ISSUE THREAD

**Issue by alexperovich** [dotnet/corefx#13108]
This came from running FxCop analyzers on corefx. Reproduce steps found [here](https://gist.github.com/alexperovich/eabc4e9053ee8aca5bcda8caa379ea87).

"E:\corefx\src\src.builds" (default target) (1) ->
"E:\corefx\src\System.Net.Sockets\src\System.Net.Sockets.builds" (Build target) (258) ->
"E:\corefx\src\System.Net.Sockets\src\System.Net.Sockets.csproj" (Build target) (259) ->
  System\Net\Sockets\Socket.cs(4632,17): error CA2200: Re-throwing caught exception changes stack information. [E:\corefx\src\System.Net.Sockets\src\System.Net.Sockets.csproj]
  System\Net\Sockets\Socket.cs(4756,21): error CA2200: Re-throwing caught exception changes stack information. [E:\corefx\src\System.Net.Sockets\src\System.Net.Sockets.csproj]
  System\Net\Sockets\Socket.cs(4884,17): error CA2200: Re-throwing caught exception changes stack information. [E:\corefx\src\System.Net.Sockets\src\System.Net.Sockets.csproj]
  System\Net\Sockets\Socket.cs(4943,17): error CA2200: Re-throwing caught exception changes stack information. [E:\corefx\src\System.Net.Sockets\src\System.Net.Sockets.csproj]
  System\Net\Sockets\Socket.cs(5020,17): error CA2200: Re-throwing caught exception changes stack information. [E:\corefx\src\System.Net.Sockets\src\System.Net.Sockets.csproj]
  System\Net\Sockets\Socket.cs(5098,17): error CA2200: Re-throwing caught exception changes stack information. [E:\corefx\src\System.Net.Sockets\src\System.Net.Sockets.csproj]
  System\Net\Sockets\Socket.cs(5156,17): error CA2200: Re-throwing caught exception changes stack information. [E:\corefx\src\System.Net.Sockets\src\System.Net.Sockets.csproj]
  System\Net\Sockets\Socket.cs(5298,17): error CA2200: Re-throwing caught exception changes stack information. [E:\corefx\src\System.Net.Sockets\src\System.Net.Sockets.csproj]

**Comment by karelz** [comment]
What is context/source of this bug? Some tool?

**Comment by alexperovich** [comment]
FxCop roslyn analyzers. I have added steps to reproduce in the issue.
