### ISSUE TITLE
FxCop: 4 System.Xml types rethrow caught exceptions without using the rethrow statement.

### ISSUE THREAD

**Issue by alexperovich** [dotnet/corefx#13106]
This came from running FxCop analyzers on corefx. Reproduce steps found [here](https://gist.github.com/alexperovich/eabc4e9053ee8aca5bcda8caa379ea87).

"E:\corefx\src\src.builds" (default target) (1) ->
"E:\corefx\src\System.Private.Xml.Linq\src\System.Private.Xml.Linq.builds" (Build target) (294) ->
"E:\corefx\src\System.Private.Xml.Linq\src\System.Private.Xml.Linq.csproj" (Build target) (295) ->
"E:\corefx\src\System.Private.Xml\src\System.Private.Xml.csproj" (default target) (296) ->
  System\Xml\Xsl\Xslt\Scripts.cs(347,21): error CA2200: Re-throwing caught exception changes stack information. [E:\corefx\src\System.Private.Xml\src\System.Private.Xml.csproj]
  System\Xml\Schema\CompiledidEntityConstraint.cs(59,17): error CA2200: Re-throwing caught exception changes stack information. [E:\corefx\src\System.Private.Xml\src\System.Private.Xml.csproj]
  System\Xml\Schema\CompiledidEntityConstraint.cs(73,21): error CA2200: Re-throwing caught exception changes stack information. [E:\corefx\src\System.Private.Xml\src\System.Private.Xml.csproj]
  System\Xml\Schema\DataTypeImplementation.cs(3915,17): error CA2200: Re-throwing caught exception changes stack information. [E:\corefx\src\System.Private.Xml\src\System.Private.Xml.csproj]
  System\Xml\Schema\DataTypeImplementation.cs(3828,17): error CA2200: Re-throwing caught exception changes stack information. [E:\corefx\src\System.Private.Xml\src\System.Private.Xml.csproj]
  System\Xml\Schema\DataTypeImplementation.cs(3871,17): error CA2200: Re-throwing caught exception changes stack information. [E:\corefx\src\System.Private.Xml\src\System.Private.Xml.csproj]
  System\Xml\Schema\DataTypeImplementation.cs(3972,17): error CA2200: Re-throwing caught exception changes stack information. [E:\corefx\src\System.Private.Xml\src\System.Private.Xml.csproj]
  System\Xml\Schema\XmlSchema.cs(131,21): error CA2200: Re-throwing caught exception changes stack information. [E:\corefx\src\System.Private.Xml\src\System.Private.Xml.csproj]

**Comment by karelz** [comment]
What is the source/context of this bug?

**Comment by alexperovich** [comment]
FxCop roslyn analyzers. I have added steps to reproduce in the issue.

**Comment by karelz** [comment]
@sepidehMS @krwq can you please take a look? We should fix it sooner rather than later.

**Comment by karelz** [comment]
cc: @danmosemsft
