### ISSUE TITLE
FxCop: System.Text.Encodings.Web.TextEncoderSettings calls virtual methods in constructors

### ISSUE THREAD

**Issue by alexperovich** [dotnet/corefx#13100]
This came from running FxCop analyzers on corefx. Reproduce steps found [here](https://gist.github.com/alexperovich/eabc4e9053ee8aca5bcda8caa379ea87).

The TextEncoderSettings type calls virtual methods in several of its constructors. This will not work if the class is overridden.

"E:\corefx\src\src.builds" (default target) (1) ->
"E:\corefx\src\System.Text.Encodings.Web\src\System.Text.Encodings.Web.builds" (Build target) (439) ->
"E:\corefx\src\System.Text.Encodings.Web\src\System.Text.Encodings.Web.csproj" (Build target) (440) ->
  System\Text\Encodings\Web\TextEncoderSettings.cs(32,13): error CA2214: Do not call overridable methods in constructors [E:\corefx\src\System.Text.Encodings.Web\src\System.Text.Encodings.Web.csproj]
  System\Text\Encodings\Web\TextEncoderSettings.cs(32,29): error CA2214: Do not call overridable methods in constructors [E:\corefx\src\System.Text.Encodings.Web\src\System.Text.Encodings.Web.csproj]
  System\Text\Encodings\Web\TextEncoderSettings.cs(46,13): error CA2214: Do not call overridable methods in constructors [E:\corefx\src\System.Text.Encodings.Web\src\System.Text.Encodings.Web.csproj]

**Comment by karelz** [comment]
What is the source/context of this bug?

**Comment by alexperovich** [comment]
FxCop roslyn analyzers. I have added steps to reproduce in the issue.

**Comment by karelz** [comment]
@tarekgh can you please take a look? We should fix it sooner rather than later.

cc: @danmosemsft

**Comment by tarekgh** [comment]
@KrzysztofCwalina used to be the owner of Web encoding. could you please have a look?

**Comment by tarekgh** [comment]
talked offline with @KrzysztofCwalina and he is going to look at this later as it is not urgent issue.

**Comment by danmosemsft** [comment]
@krwq is the actual primary owner of System.Text now. I agree this is not urgent.

**Comment by KrzysztofCwalina** [comment]
The ctors call TextEncoderSettings.GetAllowedCodePoints and AllowRanges. Making the methods non-virtual or removing calls to these methods from the existing ctors would be a breaking change at this point. Because of this, I think we should just leave code as-is.
