### ISSUE TITLE
FxCop: 3 types in System.Security.Permissions have incorrect or missing serialization constructors

### ISSUE THREAD

**Issue by alexperovich** [dotnet/corefx#13103]
This came from running FxCop analyzers on corefx. Reproduce steps found [here](https://gist.github.com/alexperovich/eabc4e9053ee8aca5bcda8caa379ea87).

"E:\corefx\src\src.builds" (default target) (1) ->
"E:\corefx\src\System.Security.Permissions\src\System.Security.Permissions.builds" (Build target) (415) ->
"E:\corefx\src\System.Security.Permissions\src\System.Security.Permissions.csproj" (Build target) (416) ->
  System\Security\XmlSyntaxException.cs(17,18): error CA2229: Declare serialization constructor for sealed type XmlSyntaxException as private [E:\corefx\src\System.Security.Permissions\src\System.Security.Permissions.csproj]
  System\Security\Policy\Hash.cs(11,33): error CA2229: Serializable type Hash doesn't have a serialization constructor [E:\corefx\src\System.Security.Permissions\src\System.Security.Permissions.csproj]
  System\Security\Policy\HashMembershipCondition.cs(11,33): error CA2229: Serializable type HashMembershipCondition doesn't have a serialization constructor [E:\corefx\src\System.Security.Permissions\src\System.Security.Permissions.csproj]

**Comment by karelz** [comment]
@steveharter can you please take a look?

**Comment by danmosemsft** [comment]
All 3 of these are valid issues.
