### ISSUE TITLE
[uap101aot] FxCop: 2 System.IO types have incorrect serialization constructors

### ISSUE THREAD

**Issue by alexperovich** [dotnet/corefx#13105]
This came from running FxCop analyzers on corefx. Reproduce steps found [here](https://gist.github.com/alexperovich/eabc4e9053ee8aca5bcda8caa379ea87).

"E:\corefx\src\src.builds" (default target) (1) ->
"E:\corefx\src\System.Runtime.WindowsRuntime\src\System.Runtime.WindowsRuntime.builds" (Build target) (377) ->
"E:\corefx\src\System.Runtime.WindowsRuntime\src\System.Runtime.WindowsRuntime.csproj" (Build target) (378:2) ->
"E:\corefx\src\System.IO\src\System.IO.csproj" (default target) (116:7) ->
  System\IO\InvalidDataException.cs(27,18): error CA2229: Declare serialization constructor for sealed type InvalidDataException as private [E:\corefx\src\System.IO\src\System.IO.csproj]
  System\IO\EndOfStreamException.cs(10,18): error CA2229: Serializable type EndOfStreamException doesn't have a serialization constructor [E:\corefx\src\System.IO\src\System.IO.csproj]

**Comment by karelz** [comment]
@JeremyKuhne @ianhays can you please take a look? We should fix it sooner rather than later.

cc: @danmosemsft

**Comment by stephentoub** [comment]
@alexperovich, what build did you run FxCop on to produce these warnings?  The EndOfStreamException.cs one is about a file only included in the uap101aot build: https://github.com/dotnet/corefx/blob/master/src/System.IO/src/System/IO/EndOfStreamException.cs

**Comment by alexperovich** [comment]
I ran this on commit beb24dbe1b9dd63e8fbf8fdfe2d5ca6afd9d2429.

**Comment by stephentoub** [comment]
> I ran this on commit 

Sorry, I meant on what version of the binary?  It seems like this is getting run on the uap101aot binary, rather than on one that runs on coreclr.

**Comment by alexperovich** [comment]
This wasn't run on any binary, This is the FxCop roslyn analyzers. by msbuilding https://github.com/dotnet/corefx/blob/master/src/src.builds

**Comment by stephentoub** [comment]
> This wasn't run on any binary, This is the FxCop roslyn analyzers. by msbuilding https://github.com/dotnet/corefx/blob/master/src/src.builds

Ok, then the source configuration that was being built.  My ultimate point is that we shouldn't be focused on the uap101aot configuration right now.

**Comment by alexperovich** [comment]
Both configurations in S.R.WindowsRuntime.builds were built, so uap101aot and standard.

**Comment by stephentoub** [comment]
> Both configurations in S.R.WindowsRuntime.builds were built, so uap101aot and standard.

Yes, and this warning would have only occurred in uap101aot, as this file is only compiled into that build.

**Comment by ViktorHofer** [comment]
These aren't serializable anymore. Closing.
