### ISSUE TITLE
FxCop: 2 System.Security.Principal types have serialization constructors with incorrect accessibility

### ISSUE THREAD

**Issue by alexperovich** [dotnet/corefx#13102]
This came from running FxCop analyzers on corefx. Reproduce steps found [here](https://gist.github.com/alexperovich/eabc4e9053ee8aca5bcda8caa379ea87).

"E:\corefx\src\src.builds" (default target) (1) ->
"E:\corefx\src\System.Security.Principal.Windows\src\System.Security.Principal.Windows.builds" (Build target) (418) ->
"E:\corefx\src\System.Security.Principal.Windows\src\System.Security.Principal.Windows.csproj" (Build target) (419) ->
  System\Security\Principal\IdentityNotMappedException.cs(35,18): error CA2229: Declare serialization constructor for sealed type IdentityNotMappedException as private [E:\corefx\src\System.Security.Principal.Windows\src\System.Security.Principal.Windows.csproj]
  System\Security\Principal\WindowsIdentity.cs(239,16): error CA2229: Declare serialization constructor for unsealed type WindowsIdentity as protected [E:\corefx\src\System.Security.Principal.Windows\src\System.Security.Principal.Windows.csproj]

**Comment by karelz** [comment]
@alexperovich can you please clarify context/source of this bug? (I don't think it is build break, probably some tool output?)

**Comment by alexperovich** [comment]
FxCop roslyn analyzers. I have added steps to reproduce in the issue.

**Comment by karelz** [comment]
@bartonjs @steveharter can you please take a look? We should fix it sooner rather than later.

**Comment by stephentoub** [comment]
> FxCop roslyn analyzers

@alexperovich, a good number of these FxCop warnings (in this and other issues) are suggesting changing already shipped APIs that we can't/shouldn't change.  For example, this issue is recommending changing ```public WindowsIdentity(SerializationInfo info, StreamingContext context)``` to be protected, but that would be a breaking change.

**Comment by danmosemsft** [comment]
Breaking change.

**Comment by alexperovich** [comment]
I will add suppressions to this then.

**Comment by stephentoub** [comment]
Thanks, @alexperovich.  The WindowsIdentity one should be suppressed.  The IdentityNotMappedException one can just be changed from internal to private rather than suppressing it.
