### ISSUE TITLE
FxCop: X509Certificate needs to either be sealed or declare its serialization constructor as protected

### ISSUE THREAD

**Issue by alexperovich** [dotnet/corefx#13104]
This came from running FxCop analyzers on corefx. Reproduce steps found [here](https://gist.github.com/alexperovich/eabc4e9053ee8aca5bcda8caa379ea87).

"E:\corefx\src\src.builds" (default target) (1) ->
"E:\corefx\src\System.Security.Cryptography.X509Certificates\src\System.Security.Cryptography.X509Certificates.builds" (Build target) (412) ->
"E:\corefx\src\System.Security.Cryptography.X509Certificates\src\System.Security.Cryptography.X509Certificates.csproj" (Build target) (413) ->
  System\Security\Cryptography\X509Certificates\X509Certificate.cs(84,16): error CA2229: Declare serialization constructor for unsealed type X509Certificate as protected [E:\corefx\src\System.Security.Cryptography.X509Certificates\src\System.Security.Cryptography.X509Certificates.csproj]

**Comment by karelz** [comment]
Is it netstandard2.0? Or what is the context/source of this bug?

**Comment by alexperovich** [comment]
FxCop roslyn analyzers. I have added steps to reproduce in the issue.

**Comment by karelz** [comment]
@bartonjs @steveharter can you please take a look? We should fix it sooner rather than later.

**Comment by danmosemsft** [comment]
This already shipped as public. Breaking change. https://msdn.microsoft.com/en-us/library/e053d5fw(v=vs.110).aspx

**Comment by alexperovich** [comment]
I will add suppressions.
