### ISSUE TITLE
Can't get System.Security.Cryptography.OpenSsl by nuget Install

### ISSUE THREAD

**Issue by YongseopKim** [dotnet/corefx#13116]
I can't get System.Security.Cryptography.OpenSsl by 'nuget.exe Install' since a few days.

```
yons.kim@s017:~/data/corefx$ mono nuget.exe Install -Pre -ExcludeVersion -Source `pwd`/bin/packages/Release/ -OutputDirectory interim/coreapp/ System.Security.Cryptography.OpenSsl
Feeds used:
  /home/yons.kim/data/corefx/bin/packages/Release/

Attempting to gather dependency information for package 'System.Security.Cryptography.OpenSsl.4.4.0-beta-24726-0' with respect to project 'interim/coreapp/', targeting 'Any,Version=v0.0'
Attempting to resolve dependencies for package 'System.Security.Cryptography.OpenSsl.4.4.0-beta-24726-0' with DependencyBehavior 'Lowest'
Unable to resolve dependency 'runtime.alpine.3.4.3-x64.runtime.native.System.Security.Cryptography'. Source(s) used: 'nuget.org'.
  Unable to resolve dependency 'runtime.alpine.3.4.3-x64.runtime.native.System.Security.Cryptography'. Source(s) used: 'nuget.org'.
```

Anybody knows how to solve this problem?

**Comment by danmosemsft** [comment]
@bartonjs

**Comment by bartonjs** [comment]
@YongseopKim Do you only get an error for `runtime.alpine`, or are there several others?  And I'm guessing that your nuget install fails from local builds but (would) succeed from dotnet.myget.org?

@ericstj Is this a "need to build partial packages" thing?

**Comment by ericstj** [comment]
@bartonjs it looks like it.  @YongseopKim is building the package locally then trying to extract it with dependencies.

This would happen because it now has direct dependencies on the x-plat packages.  You can produce those by building:
msbuild /data/corefx/src/Native/pkg/runtime.native.System.Security.Cryptography.OpenSsl/runtime.native.System.Security.Cryptography.OpenSsl.builds /p:AllowPartialPackages=true

That should build all those packages as empty if you haven't built the binaries.

**Comment by YongseopKim** [comment]
> Do you only get an error for runtime.alpine, or are there several others? And I'm guessing that your nuget install fails from local builds but (would) succeed from dotnet.myget.org?

@bartonjs, @ericstj  I get only an error for runtime.alpine and your guessing is right.

I'm trying the way that you answered.

> `msbuild /data/corefx/src/Native/pkg/runtime.native.System.Security.Cryptography.OpenSsl/runtime.native.System.Security.Cryptography.OpenSsl.builds /p:AllowPartialPackages=true`

I can get following files as a result.

```
yons.kim@s017:~/data/github/corefx/bin/packages/Release$ ls -l --sort=time
total 59812
drwxrwxr-x  2 yons.kim yons.kim   20480 10월 31 12:58 reports
-rwxrw-r--  1 yons.kim yons.kim    7753 10월 31 12:58 runtime.alpine.3.4.3-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.4.0-beta-24726-0.nupkg
drwxrwxr-x 31 yons.kim yons.kim   36864 10월 31 12:58 specs
-rwxrw-r--  1 yons.kim yons.kim    7758 10월 31 12:58 runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.4.0-beta-24726-0.nupkg
-rwxrw-r--  1 yons.kim yons.kim    7758 10월 31 12:58 runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.4.0-beta-24726-0.nupkg
-rwxrw-r--  1 yons.kim yons.kim    7743 10월 31 12:58 runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.4.0-beta-24726-0.nupkg
-rwxrw-r--  1 yons.kim yons.kim    7754 10월 31 12:58 runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.4.0-beta-24726-0.nupkg
-rwxrw-r--  1 yons.kim yons.kim    7755 10월 31 12:58 runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.4.0-beta-24726-0.nupkg
-rwxrw-r--  1 yons.kim yons.kim    7754 10월 31 12:58 runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.4.0-beta-24726-0.nupkg
-rwxrw-r--  1 yons.kim yons.kim    7736 10월 31 12:58 runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.4.0-beta-24726-0.nupkg
-rwxrw-r--  1 yons.kim yons.kim    7737 10월 31 12:58 runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.4.0-beta-24726-0.nupkg
-rwxrw-r--  1 yons.kim yons.kim    7730 10월 31 12:58 runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.4.0-beta-24726-0.nupkg
-rwxrw-r--  1 yons.kim yons.kim    7718 10월 31 12:58 runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.4.0-beta-24726-0.nupkg
-rwxrw-r--  1 yons.kim yons.kim    7671 10월 31 12:58 runtime.native.System.Security.Cryptography.OpenSsl.4.4.0-beta-24726-0.nupkg
...
-rwxrw-r--  1 yons.kim yons.kim   89075 10월 28 16:41 System.Security.Cryptography.OpenSsl.4.4.0-beta-24726-0.nupkg
...
```

However, I can't solve the problem until now.
```
yons.kim@s017:~/data/github/corefx/bin/packages/Release$ mono nuget.exe Install -Pre -ExcludeVersion -Source `pwd` -OutputDirectory ~/data/github/corefx/interim/coreapp/ System.Security.Cryptography.OpenSsl
Feeds used:
  /home/yons.kim/data/github/corefx/bin/packages/Release

Attempting to gather dependency information for package 'System.Security.Cryptography.OpenSsl.4.4.0-beta-24726-0' with respect to project '/home/yons.kim/data/github/corefx/interim/coreapp/', targeting 'Any,Version=v0.0'
Attempting to resolve dependencies for package 'System.Security.Cryptography.OpenSsl.4.4.0-beta-24726-0' with DependencyBehavior 'Lowest'
Unable to resolve dependency 'runtime.alpine.3.4.3-x64.runtime.native.System.Security.Cryptography'. Source(s) used: 'nuget.org'.
  Unable to resolve dependency 'runtime.alpine.3.4.3-x64.runtime.native.System.Security.Cryptography'. Source(s) used: 'nuget.org'.
```

(Source code isn't changed.)

**Comment by YongseopKim** [comment]
And I don't understand why I have to put the option, AllowPartialPackages because I just build managed corefx locally while not changing the latest code(surely including files for build). A few days ago, I could get the package without any additional commands like AllowPartialPackages. The current situation is expressing that I should add some commands for extracting System.Security.Cryptography.OpenSsl.

Any info or material to understand what you mentioned?
> This would happen because it now has direct dependencies on the x-plat packages.

**Comment by ericstj** [comment]
https://github.com/dotnet/corefx/commit/2821f8e47cdee84551e663d84291d8c97e4367bb made these packages direct dependencies from the shim package so that building applications without a `runtime` specified in `project.json` would install the updates to the shim libraries.

**Comment by bartonjs** [comment]
The answer to the original "how do I work around this?" is

```
msbuild /data/corefx/src/Native/pkg/runtime.native.System.Security.Cryptography.OpenSsl/runtime.native.System.Security.Cryptography.OpenSsl.builds /p:AllowPartialPackages=true
```

Things may continue to evolve in this space in master as some pieces of packaging shift around for future versions.

**Comment by YongseopKim** [comment]
I write to leave information.
Now my problem is solved. The reason why 'nuget install' was failed is that of usage for wrong nuget command. I didn't touch NuGet.Config at all. After adding local package source, it works.
If someone faces one problem like this, consider modifying the NuGet.Config file.
