### ISSUE TITLE
UWP test runner does not allow resolving external paths

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#13121]
There are UWP test failures on Helix which are failing due to not being able to resolve external paths. (Please re-enable tests labelled with ActiveIssue when this is fixed)

**Comment by tijoytom** [comment]
@sepidehMS 
Which  external path is it trying to resolve? is this something that we can avoid?

**Comment by sepidehMS** [comment]
Fixed in https://github.com/dotnet/corefx/pull/21247
