### ISSUE TITLE
Port: DateTime.ToString(“o”) allocates 32 objects

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#13130]
This is a tracking issue to consider porting this PR to .NET Framework. 

https://github.com/dotnet/coreclr/pull/7836

**Comment by Petermarcu** [comment]
@AlexGhiondea , did I file this right to get it tracked?

**Comment by AlexGhiondea** [comment]
@Petermarcu yes.

**Comment by karelz** [comment]
Now it is tracked by @AlexGhiondea's tool, we do not need this bug opened anymore.
