### ISSUE TITLE
FileInfo: get_LastWritTime test fail

### ISSUE THREAD

**Issue by Maxwe11** [dotnet/corefx#1313]
EXEC : warning : (runTest, d:\corefx\src\System.IO.FileSystem\tests\FileInfo\get_LastWriteTime.cs, 100) Eror_f984f! LastWriteTime is way off [D:\corefx\src\System.IO.FileSystem\tests\System.IO.FileSystem.Tests.csproj]
	  FAiL! get_LastWriteTime.cs ,iCountErrors==1
		 FileInfo_get_LastWriteTime.runTest [FAIL]
			Assert.Equal() Failure
			Expected: 0
			Actual:   1
			Stack Trace:
			   d:\corefx\src\System.IO.FileSystem\tests\FileInfo\get_LastWriteTime.cs(126,0): at FileInfo_get_LastWriteTime.runTest()

**Comment by mmitche** [comment]
Also seen at: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_outerloop/lastFailedBuild/testReport/junit/(root)/FileSystemWatcher_4000_Tests/FileSystemWatcher_Changed_LastWrite_File/

**Comment by ericstj** [comment]
@FiveTimesTheFun  feel free to pick this up if you can since you added this failing test.
