### ISSUE TITLE
System.Diagnostics.Process.GetProcessById fails to retrieve process on Linux

### ISSUE THREAD

**Issue by nzubair** [dotnet/corefx#13135]
This was originally raised an issue on PowerShell repo under PowerShell/PowerShell#1851. When not running under sudo, `Get-Process -Id <number>` fails to get the process. This only happens if the target process is not owned by the current user.

After some digging, it seems like it's related to how `ProcessManager.Unix.cs` tries to figure out if the given process is running or not. It does so by trying to issue a `Kill` command against the process:

[System/Diagnostics/ProcessManager.Unix.cs](https://github.com/dotnet/corefx/blob/421407e7831356f7f28f48b35da9e58b43e0d6f2/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessManager.Unix.cs#L26-L31)

```
        public static bool IsProcessRunning(int processId)
        {
            // kill with signal==0 means to not actually send a signal.
            // If we get back 0, the process is still alive.
            return 0 == Interop.Sys.Kill(processId, Interop.Sys.Signals.None);
        }
```
As opposed to `ProcessManager.Windows.cs`, which looks up the given processId in an array of processIds for currently running processes.

I think it's running into permission issues because non-privileged users cannot signal processes not owned by themselves. `man 2 kill` actually describes the required permissions [kill(2)](https://linux.die.net/man/2/kill) / [Kill Permissions](https://www.gnu.org/software/libc/manual/html_node/Permission-for-kill.html#Permission-for-kill)

```
 If sig is 0, then no signal is sent, but error checking is still performed; this can be used to check for  the
 existence of a process ID or process group ID.

 For a process to have permission to send a signal it must either be privileged (under Linux: have the CAP_KILL
 capability), or the real or effective user ID of the sending process must equal the real or saved  set-user-ID
 of  the target process.  In the case of SIGCONT it suffices when the sending and receiving processes belong to
 the same session.  (Historically, the rules were different; see NOTES.)

....

Linux notes
 Across  different  kernel  versions,  Linux  has  enforced different rules for the permissions required for an
 unprivileged process to send a signal to another process.  In kernels 1.0 to 1.2.2, a signal could be sent  if
 the effective user ID of the sender matched effective user ID of the target, or the real user ID of the sender
 matched the real user ID of the target.  From kernel 1.2.3 until 1.3.77, a signal could be sent if the  effec‐
 tive  user  ID  of  the sender matched either the real or effective user ID of the target.  The current rules,
 which conform to POSIX.1-2001, were adopted in kernel 1.3.78.
```

### Environment
```
nasir:~/proctest$ ~/.dotnet/dotnet --info
.NET Command Line Tools (1.0.0-preview3-003842)

Product Information:
 Version:            1.0.0-preview3-003842
 Commit SHA-1 hash:  3ae14ab618

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
```

Also tested on Ubuntu 16.04, with `dotnet-dev-1.0.0-preview2-003131`

### Current Process list
```
nasir:~/proctest$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0  2432 ?        00:00:00 /init
nasir        2     1  0  2432 ?        00:00:02 /bin/bash
root      2209     2  0  2432 ?        00:00:00 sudo bash
root      2210  2209  0  2432 ?        00:00:00 bash
nasir     2480     2  0  2432 ?        00:00:00 ps -ef
```

### Testcode
```
using System;
using System.Diagnostics;

class Program
{
    static void Main(string[] args)
    {
        if(args.Length != 1) { Console.WriteLine("no input"); return; }

        try
        {
                int pid = Int32.Parse(args[0]);
                Process p = Process.GetProcessById(pid);
                Console.WriteLine("PID: {0} Name: {1}", p.Id, p.ProcessName);
        }
        catch(Exception ex)
        {
                Console.WriteLine(ex);
        }
    }
}
```

### Results

Running against own process, expected results.
```
nasir:~/proctest$ ~/.dotnet/dotnet run 2
Project proctest (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
PID: 2 Name: bash
```

Running against one of root's processes, exception.
```
nasir:~/proctest$ ~/.dotnet/dotnet run 2210
Project proctest (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
System.ArgumentException: Process with an Id of 2210 is not running.
   at System.Diagnostics.Process.GetProcessById(Int32 processId, String machineName)
   at System.Diagnostics.Process.GetProcessById(Int32 processId)
   at Program.Main(String[] args) in /home/nasir/proctest/Program.cs:line 13
```

Running against the same root's process, now with sudo. 
```
nasir:~/proctest$ sudo !!
sudo ~/.dotnet/dotnet run 2210
[sudo] password for nasir:
Project proctest (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
PID: 2210 Name: bash
```

### Expected Results

Process.GetProcessById() should return the process information even for process running for other users. 
This is the expected behavior of utilities such as `ps`

```
nasir:~/proctest$ ps -f 1
UID        PID  PPID  C STIME TTY      STAT   TIME CMD
root         1     0  0  2432 ?        Ss     0:00 /init
```

Furthermore, `Process.GetProcesses()` has no problem pulling up information on all processes currently running on the system.

**Comment by karelz** [comment]
cc: @Priya91

**Comment by Priya91** [comment]
@nzubair Refer #13147

**Comment by nzubair** [comment]
Thanks for the quick fix.  

Just curious, why use `kill` to see if processes are running, Instead of finding it among the running processes, similar to what Windows ProcessManager does?

**Comment by Priya91** [comment]
> Just curious, why use kill to see if processes are running, Instead of finding it among the running processes, similar to what Windows ProcessManager does?

On Unix, we prefer to use POSIX compliant APIs if available. kill signal=0 is the preferred way to check if a process is alive. Enumerating the whole /proc filesystem to check if a process with pid is still running is a roundabout way and more work.
