### ISSUE TITLE
Regression: Comparer_DefaultInvariant.ExecuteComparer_DefaultInvariant

### ISSUE THREAD

**Issue by mmitche** [dotnet/corefx#1314]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release/lastFailedBuild/testReport/junit/(root)/Comparer_DefaultInvariant/ExecuteComparer_DefaultInvariant/

MESSAGE:
Assert.True() Failure
+++++++++++++++++++
STACK TRACE:
at Comparer_DefaultInvariant.ExecuteComparer_DefaultInvariant() in d:\j\workspace\dotnet_corefx_windows_release\src\System.Collections.NonGeneric\tests\Comparer\Comparer_DefaultInvariant.cs:line 114

**Comment by ellismg** [comment]
I expect that this is due to races in the tests.  Hashtable tests also muck with this shared property and if run concurrently, you will run into issues.

We should either not run these in parallel or stop using shared mutable state.

**Comment by mmitche** [comment]
I thought we already disable parallelism for these...?  @stephentoub

**Comment by stephentoub** [comment]
I don't see any attributes in that test project that would cause parallelism to be disabled, though it sounds like it should be until the tests can be fixed.

**Comment by krwq** [comment]
Duplcate: https://github.com/dotnet/corefx/issues/1504
Since I already provided more details in the other one I'm closing this issue.
