### ISSUE TITLE
How to use locally compiled corefx?

### ISSUE THREAD

**Issue by nzubair** [dotnet/corefx#13154]
Apologies if this is something very basic and I've missed some obvious documentation.

I have cloned and successfully built the corefx repo locally on a Ubuntu machine, following the directions from [Developer Guide](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md). 

At this point, I'm at a loss on how actually I can build an app using the framework I just compiled? I've tried using `dotnet restore` with `--source` option but that didn't seem to work.

**Comment by fitzchak** [comment]
I may have a related issue on Windows: https://github.com/dotnet/corefx/issues/13159

**Comment by karelz** [comment]
@joperezr @weshaggard do you know who can help here?
cc: @danmosemsft

**Comment by weshaggard** [comment]
Unfortunately to build an app there isn't a great way to do that with corefx alone as it requires other things from other repo's like coreclr and core-setup. The closest instructions we have are at https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/UsingYourBuild.md but even those have rough edges.

This is one area we have plans to improve but there is a lot of work to get there.

**Comment by nzubair** [comment]
That's a starting point. Thank you for the link. I'll give it a shot and see how far I get. :)

**Comment by karelz** [comment]
Seems to be resolved for now ...
