### ISSUE TITLE
Globalization Formatting Tests need to cover more input scenarios

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#13170]
Noticed this when working on the DateTime and DateTimeOffset code. Most test just test max value and not important other cases.

It may be a good idea to have a theory with a variety of inputs would be best. It should be evaluated for all these tests, not just this format. Min value, Max value, combined with 0, min and max offsets. Now, and some interesting hard coded dates that exercise things in the middle. That should be the data set we feed into all the parsing code.

See https://github.com/dotnet/corefx/pull/13165 for an example where a test is being added but its still only barely exercising the code.

**Comment by hughbe** [comment]
I might take a look when I've got more time. Just a couple of questions:
- These tests belong in System.Runtime right?
- How culture sensitive are these tests? I'd hate to write tests that only work on en-GB and explode on different cultures!

**Comment by danmosemsft** [comment]
Yes these tests would go with the implementation in System.Runtime. @tarekgh is an authority on globalization questions.

**Comment by Petermarcu** [comment]
@hughbe , I added a couple concrete example here: https://github.com/dotnet/corefx/pull/13180

Some are more culture sensitive than others but even ignoring that, getting more coverage with specific data for the invariant culture case would be useful. There is also plenty of cleanup opportunity in these tests to reduce duplication if you are so inclined.

**Comment by tarekgh** [comment]
@hughbe the tests #13180 that @Petermarcu adding mainly covering 'o', 'O', 'R' and 'r' cases which really kind of culture insensitive but in general I agree with you to add more specific culture sensitive tests. would you be interested in that?

**Comment by tarekgh** [comment]
@Petermarcu is there is anything need to be done here or can we close this issue?

**Comment by Petermarcu** [comment]
There is a lot more to do. I only added coverage for the two formatting cases I was changing.

**Comment by karelz** [comment]
This does not look like must have in 1.2 (@tarekgh says), moving to Future.

**Comment by stephentoub** [comment]
We've added a lot of additional testing here as part of several PRs to improve the performance of these methods.
