### ISSUE TITLE
Make DoWorkEventArgs derive from CancelEventArgs

### ISSUE THREAD

**Issue by AlexGhiondea** [dotnet/corefx#13177]
This will require the move of CancelEventArgs from System.ComponentModel to System.ComponentModel.Primitives.

**Comment by ckuhn203** [comment]
Some context for anyone stumbling across this and wondering "why", `DoWorkEventArgs` derives from `CancelEventArgs` in the last version of .Net framework. 

https://msdn.microsoft.com/en-us/library/system.componentmodel.doworkeventargs(v=vs.110).aspx

**Comment by safern** [comment]
Why should `CancelEventArgs` should be moved to `System.ComponentModel.Primitives` if `DoWorkEventArgs` is in namespace `System.ComponentModel` ?

Here is the [source code](https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.EventBasedAsync/src/System/ComponentModel/DoWorkEvent.cs#L5)
@AlexGhiondea

**Comment by AlexGhiondea** [comment]
Because 'CancelEventArgs' should be the base class of the 'DoWorkEventArgs'. 

And 'CancelEventArgs' is in a contract that you cannot reference from the project that has 'DoWorkEventArgs'.
