### ISSUE TITLE
HttpClientHandlerTest.Proxy_BypassFalse_GetRequestGoesThroughCustomProxy failed in CI

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#13188]
Failed in PR #13181

System.Net.Http.Functional.Tests.HttpClientHandlerTest.Proxy_BypassFalse_GetRequestGoesThroughCustomProxy(creds: null, wrapCredsInCache: False)

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug_prtest/89/

System.AggregateException : One or more errors occurred. (Object reference not set to an instance of an object.) (An error occurred while sending the request.) (One or more errors occurred. (An error occurred while sending the request.))\r\n---- System.NullReferenceException : Object reference not set to an instance of an object.\r\n---- System.Net.Http.HttpRequestException : An error occurred while sending the request.\r\n-------- System.Net.Http.WinHttpException : The operation has been canceled\r\n---- System.AggregateException : One or more errors occurred. (An error occurred while sending the request.)\r\n-------- System.Net.Http.HttpRequestException : An error occurred while sending the request.\r\n------------ System.Net.Http.WinHttpException : The operation has been canceled

**Comment by Priya91** [comment]
This hasn't failed in CI, and not able to repro locally. Closing the issue as log not available. Please reopen if test fails.

**Comment by CIPop** [comment]
Related to #19701.
