### ISSUE TITLE
System.Linq.Parallel queries not always running in Parallel

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#1320]
`System.Linq.Parallel` queries (consistently) don't always run in parallel by default (not forcing parallelism), if `ElementAt(...)` or `ElementAtOrDefault(...)` is called (especially on unordered collections).  

Calling `First()` _does_ run things in parallel, so I didn't think it was a performance optimization.

Take, for example, `Where`: `unorderedQuery.Where(e => e.SomeCheck()).ElementAt(8)`.  
Now, I'm not expecting an unordered source to return me the actual 8th element, so it can return the first one it comes across (doesn't need to do much work), but I'd expect at least the `Where(...)` to be run in parallel.  Nope!  This is happening even if the collection mostly/completely **fails** the check (ie, one or zero elements returned), when it has to look at just about every element.  Also, the non-default version throws an error if it doesn't have however many elements, so it at least has to _count_ them...
Interestingly, adding `OrderBy(...)` causes it to run in parallel.  

Other non-parallel cases:

 - `SelectMany` (not `Select`, though...)
 - `AsOrdered` + `Select` + `Concat(Enumerable.Range(0, 1024).AsParallel().AsOrdered())` (actually, the unordered version doesn't run in parallel either.  I'm using the `Select` as part of the check for the parallelization, but am assuming it's not the actual problem).

A minimal example test:

    [Fact]
    public static void SpecificElement()
    {
        ParVerifier verifier = new ParVerifier();
        int element = ParallelEnumerable.Range(0, 1024).Where(x => verifier.Verify(x) < 0).ElementAt(64);
        Assert.True(verifier.Passed);
    }

    // A class that checks whether the Verify method got called from at least two threads.
    // The first call to Verify() blocks. If another call to Verify() occurs prior to the timeout
    // then we know that Verify() is getting called from multiple threads.
    public class ParVerifier
    {
        private int _counter = 0;
        private bool _passed = false;
        private const int TIMEOUT_LIMIT = 100;

        internal int Verify(int x)
        {
            lock (this)
            {
                _counter++;
                if (_counter == 1)
                {
                    if (Monitor.Wait(this, TIMEOUT_LIMIT))
                    {
                        _passed = true;
                    }
                }
                else if (_counter == 2)
                {
                    Monitor.Pulse(this);
                }
            }
            return x;
        }

        internal bool Passed
        {
                get { return _passed; }
        }
    }

(this is only slightly tweaked from `PlinqModesTests.cs`.  If I'm doing something wrong in this test I'd appreciate knowing about it, but this looked good to me....)

**Comment by stephentoub** [comment]
@Clockwork-Muse, thanks.  Before we investigate further, have you read http://blogs.msdn.com/b/pfxteam/archive/2011/11/11/10235999.aspx ?  In particular, it calls out ElementAt as an operator that forces fallback to sequential.

**Comment by Clockwork-Muse** [comment]
Oy, no, I didn't know about that.  Guess that explains it.
Looks like I have a test to change.
