### ISSUE TITLE
Enable S.R.Serialization.Xml and S.R.Serialization.Json Tests on Uap 10.1

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#13202]
We need to properly condition the test code and/or projects as well to make sure they still build and work on older versions. We currently are not able to run these tests against uwp because it doesn't support netstandard1.7 yet.

**Comment by karelz** [comment]
This will require larger repo-wide effort to use master test assets on lower .NET Standard versions (1.6 and lower).
