### ISSUE TITLE
UWP app consuming 1.1 packages fails WACK for CLRCompression on x64

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#13214]
Copied from https://github.com/aspnet/EntityFramework/issues/6905

The aot clrcompression build is supposed to be redistributed from 1.0 while the non-aot build is being built live.  When this change was made, the incorrect RID was used for x64-aot, causing the non-aot build to be picked up, which fails the WACK.

The fix here is to correctly list the RID as win10-**x64**-aot.

**Comment by karelz** [comment]
@ericstj @weshaggard will .NET Native customers automatically pick up the 1.1 libraries via UWP Meta package NuGet update?
Or does it affect "only" customers who explicitly grab 1.1 binaries into .NET Native project?

**Comment by ericstj** [comment]
It's happening from folks who pick up the 1.1 packages either directly or indirectly (eg from an EntityFramework package that references the 1.1 packages).

This is a must fix, we'd service for this, just like we serviced for similar problems in 1.0.

**Comment by ericstj** [comment]
I double checked if there were any other similar instances where folks were doing "external" build shenanigans and couldn't find any other cases.

**Comment by ericstj** [comment]
Another consideration: this one could be fixed through repackaging if you want to avoid a rebuild.

**Comment by karelz** [comment]
Thanks for the fix @ericstj!
cc: @gkhanna79

**Comment by gkhanna79** [comment]
CC @leecow @Petermarcu

**Comment by KalpeshChheda** [comment]
Hi @ericstj I am facing same issue with my app
on Windows App Certification Kit - Test Results

Binary analyzer
Error Found: The binary analyzer test detected the following errors:
File C:\Program Files\windowsapps\myapp.app_1.1.29.0_x86__d0tm94ngvvywp\clrcompression.dll has failed the AppContainerCheck check.
File C:\Program Files\windowsapps\myapp.app_1.1.29.0_x86__d0tm94ngvvywp\clrjit.dll has failed the AppContainerCheck check.

I am using windows 10 SDK 17134. I can find any solution. Below are the packages used in this app.

<ItemGroup>
    <PackageReference Include="Acr.UserDialogs">
      <Version>6.5.1</Version>
    </PackageReference>
    <PackageReference Include="CarouselView.FormsPlugin">
      <Version>5.2.0</Version>
    </PackageReference>
    <PackageReference Include="CommonServiceLocator">
      <Version>2.0.3</Version>
    </PackageReference>
    <PackageReference Include="LiteDB">
      <Version>4.1.2</Version>
    </PackageReference>
    <PackageReference Include="Microcharts.Forms">
      <Version>0.8.3-pre</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter.Analytics">
      <Version>1.5.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter.Crashes">
      <Version>1.5.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNet.SignalR.Client">
      <Version>2.2.3</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Net.Http">
      <Version>2.2.29</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform">
      <Version>6.1.5</Version>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json">
      <Version>10.0.3</Version>
    </PackageReference>
    <PackageReference Include="NotificationsExtensions.Win10">
      <Version>14332.0.2</Version>
    </PackageReference>
    <PackageReference Include="Plugin.AudioRecorder">
      <Version>0.8.0</Version>
    </PackageReference>
    <PackageReference Include="Plugin.MediaManager">
      <Version>0.4.5</Version>
    </PackageReference>
    <PackageReference Include="Plugin.Share">
      <Version>7.1.1</Version>
    </PackageReference>
    <PackageReference Include="Prism.Core">
      <Version>7.1.0.135-pre</Version>
    </PackageReference>
    <PackageReference Include="Prism.Forms">
      <Version>7.1.0.135-pre</Version>
    </PackageReference>
    <PackageReference Include="Prism.Unity.Forms">
      <Version>7.1.0.135-pre</Version>
    </PackageReference>
    <PackageReference Include="Rg.Plugins.Popup">
      <Version>1.1.4.158-pre</Version>
    </PackageReference>
    <PackageReference Include="SkiaSharp">
      <Version>1.60.0</Version>
    </PackageReference>
    <PackageReference Include="SkiaSharp.Views">
      <Version>1.60.0</Version>
    </PackageReference>
    <PackageReference Include="SkiaSharp.Views.Forms">
      <Version>1.60.0</Version>
    </PackageReference>
    <PackageReference Include="Splat">
      <Version>2.0.0</Version>
    </PackageReference>
    <PackageReference Include="sqlite-net-pcl">
      <Version>1.4.118</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugin.DeviceInfo">
      <Version>3.1.0</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugin.FilePicker">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugin.Geolocator">
      <Version>4.2.0</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugin.Media">
      <Version>3.1.3</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugins.Settings">
      <Version>3.1.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.FFImageLoading.Forms">
      <Version>2.3.4</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Forms">
      <Version>3.1.0.469394-pre1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Forms.Maps">
      <Version>2.5.0.280555</Version>
    </PackageReference>

**Comment by ericstj** [comment]
It’s not clear this is the same issue. Can you open a new issue with repro steps and attach the project.assets.json file?

**Comment by KalpeshChheda** [comment]
Created new issue https://github.com/dotnet/corefx/issues/30594
