### ISSUE TITLE
Implement System.Runtime.InteropServices on UAP10.1 - NETNative

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#13218]
Baselines have been created to suppress API compat warnings for InteropServices on UAP10.1.  Those need to be removed (include `-ignoreMissingTypes` setting) once implementing the missing API in NETNative.

**Comment by karelz** [comment]
This will be part of .NET Native NS2.0 push. CLosing for now, no point in tracking it one by one at this moment.
