### ISSUE TITLE
Add Copy from ref T1 to ref T2 on System.Runtime.CompilerServices.Unsafe (Api)

### ISSUE THREAD

**Issue by xoofx** [dotnet/corefx#13216]
Hi,

I would like to introduce a new public method for `System.Runtime.CompilerServices.Unsafe`

Basically a method that allows to do something like:
```csharp
public static void Write<TDest, TSrc>(ref TDest dest, ref TSrc src)
{
    dest = src;
}
```
that would translate to:

```csharp
.method public hidebysig static void Write<TDest, TSrc> (!!TDest& dest, !!TSrc& src) cil managed 
{
	.maxstack 2
	IL_0000: ldarg.0
	IL_0001: ldarg.1
	IL_0002: cpobj !!TSrc
	IL_0007: ret
} 
```

The usage scenario is to be able to efficiently copy a blittable data of type `TSrc` to a destination of type `TDest`, where we know that `TDest` has enough space to store `TSrc`. This method generates optimal code for such a case and is particularly useful for writing efficient value copy/writer.

If this is ok, I can make a PR.
Thanks!

**Comment by jkotas** [comment]
I do not think methods hiding unsafe casts are a good idea.

Why can't you use `Unsafe.As`?

**Comment by xoofx** [comment]
> I do not think methods hiding unsafe casts are a good idea.

But, that's why it is unsafe, no? 😅 Every methods in unsafe are not a good idea if you use them without knowing what they do (e.g copy from a void* to a managed object for example).

`As<>` is not working because it is casting from object, while I'm working with value types.

I typically want to copy blittable valuetypes (e.g under for example 8 bytes) to a managed generic storage variable (e.g `long` field), no matter what are the types.

To achieve somewhat something similar today, I have to use something like this:

```` 
fixed (var* pDest = &valueDest)
{
    Unsafe.Write(pDest, ref valueSrc);
}
```

The problem is the following code is generating a fixed statement that is a lot more costly to manipulate the data. It generates the un-optimal code:

```
                fixed (void* pValue = &valueHolder.AsBool)
00007FFB03D76530 48 83 EC 08          sub         rsp,8  
00007FFB03D76534 33 C0                xor         eax,eax  
00007FFB03D76536 48 89 04 24          mov         qword ptr [rsp],rax  
00007FFB03D7653A 4C 89 04 24          mov         qword ptr [rsp],r8  
                {
                    Unsafe.Write(pValue, value);
00007FFB03D7653E 49 8B C0             mov         rax,r8  
00007FFB03D76541 89 10                mov         dword ptr [rax],edx  
00007FFB03D76543 33 C0                xor         eax,eax  
00007FFB03D76545 48 89 04 24          mov         qword ptr [rsp],rax  
00007FFB03D76549 48 83 C4 08          add         rsp,8  
00007FFB03D7654D C3                   ret  
```

but with the `Write<TDest, TSrc>` above, I'm able to shrink down this code to the following optimal code:

```
00007FFB03D47F40 41 89 10             mov         dword ptr [r8],edx  
00007FFB03D47F43 C3                   ret  
```

This is saving lots of unnecessary roundtrip to the stack, and it is as optimal as writing `dest = src`

**Comment by jkotas** [comment]
If you use C# 7 ref locals and returns, you can get the same result with `Unsafe.As`.

**Comment by xoofx** [comment]
Oh, Yes with C# 7 ref locals indeed, I'm still not using it... so ok, I will keep my unsafe code on my side until I can use ref locals. No problem.
