### ISSUE TITLE
Add Linux implementation for modifying SortKey in System.Xml.Xsl.Runtime.XmlCollation

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#13236]
As SortKey is different on Linux and Windows, System.Xml.Xsl.Runtime.XmlCollation.CreateSortKey needs to be implemented differently for Linux.

**Comment by sepidehMS** [comment]
@tarekgh I did some investigation and found out there are two ways to set `UpperFirst=true` in XmlSortKey:

1. Passing a collation Uri to the public method `XmlQueryRuntime.CreateCollation(string)` which contains upperfirst=1 (For which the doc says: _This API supports the product infrastructure and is not intended to be used directly from your code._)

2. Having a `xsl:sort` instruction in an input XSL which has the attribute case-order="upper-first" like the following:
```
...
 <xsl:template match="books">
    <xsl:apply-templates>
      <xsl:sort select="title" case-order="upper-first" />
    </xsl:apply-templates>
  </xsl:template>
...
```

Considering this, what are your thoughts on whether this should be supported on Linux or not? I'm not sure how complicated it is to implement the Linux version.

cc: @danmosemsft

**Comment by tarekgh** [comment]
looking at the doc of XmlQueryRuntime.CreateCollation https://msdn.microsoft.com/en-us/library/system.xml.xsl.runtime.xmlqueryruntime.createcollation(v=vs.110).aspx it says

```
This API supports the product infrastructure and is not intended to be used directly from your code.
```

so it is not really used by apps. but when looking at the Xsl specs looks this is something used and might be necessary to support. here is some link describing the options there 

https://www.tutorialspoint.com/xslt/xslt_sort.htm

do you know what is our code in Windows does for lower-first too?

to support this in Linux we have to do some more investigation as I don't know exactly how we can do it on Linux.
