### ISSUE TITLE
BufferManager (from System.ServiceModel.Channels) not available?

### ISSUE THREAD

**Issue by eliezedeck** [dotnet/corefx#13261]
I'm trying to use that class, but it doesn't appear to be available for use. I can see it in the API: https://docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.buffermanager#System_ServiceModel_Channels_BufferManager

How and what do I do in order to make use of this feature?

Thank you.

**Comment by justinvp** [comment]
`BufferManager` is part of WCF.

https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/BufferManager.cs

It should be available in the [System.ServiceModel.Primitives](https://www.nuget.org/packages/System.ServiceModel.Primitives) package, based on the documentation you linked to.

**Comment by eliezedeck** [comment]
Thanks @justinvp. That **worked**!

Closing the issue.
