### ISSUE TITLE
 ParameterInfo objects are not guaranteed to be unique. 

### ISSUE THREAD

**Issue by dotnetjunkie** [dotnet/corefx#13265]
After spending many hours tracking down [this bug](https://github.com/simpleinjector/SimpleInjector/issues/323) in Simple Injector, I came to the conclusion that:

 - `System.Type` instances are guaranteed to be unique within a single AppDomain.
 - `System.MemberBase` instances are guaranteed to be unique within a single AppDomain.
 - `System.ParameterInfo` instances are ***not*** guaranteed to be unique.

When looking at the source code for `System.Type`, `System.Type.GetMembers()` and related methods it becomes clear that for each type there will be at most one `System.Type` instance and for each type member, there will be at most one `MemberBase` instance. For some weird reason however, this doesn't hold for `ParameterInfo` instances. When looking at `ConstructorInfo.GetParameters()` we can see that the creation of `ParameterInfo` objects is not protected by a lock and multiple concurrent threads can cause multiple `ParameterInfo` instances to be published for the same 'physical' parameter.

I think this is a bug, or at least this is a design quirk, because developers will typically assume all reflection types to be unique within a single app domain.

**Comment by karelz** [comment]
cc: @AtsushiKan

**Comment by svick** [comment]
Related: https://github.com/dotnet/corefx/issues/8130, which I think implies this is by design.

**Comment by karelz** [comment]
This is instance of the bigger issue #8130.
