### ISSUE TITLE
Consider no compression for tiny responses

### ISSUE THREAD

**Issue by joshlang** [dotnet/corefx#13286]
Minor performance tweak...

A 1-byte response of type "text/plain" will get intercepted and gzip'ed.  The overhead of compressing a tiny response takes up CPU and likely extra bandwidth.

Sample middleware:

```
app.Run(c =>
{
  c.Response.Headers["Content-Type"] = "text/plain";
  return c.Response.Body.WriteAsync(new byte[] { 65 }, 0, 1);
});
```

This gets transmitted as 'chunked' transfer encoding (even if I set c.Response.Headers["Content-Length"] = "1";) and it gets compressed using gzip

It doesn't happen if the content-type is "application/octet-stream".

Consider disabling compression for responses under a certain size (200 bytes, 500 bytes, 800 bytes, everyone seems to have a different recommendation)

**Comment by karelz** [comment]
Which type do you have in mind? Isn't it by a chance from ASP.NET?

**Comment by joshlang** [comment]
I don't understand what you mean by "which type".

To clarify, I think that the HTTP response for a single byte response should NOT be content-encoded using gzip.  I think it should have no compression at all.

**Comment by karelz** [comment]
Which class do you use? I wonder if it is part of corefx repo ...
Just to clarify: Do you use .NET Core?

**Comment by joshlang** [comment]
.NET Core 1.0.1

**Comment by benaadams** [comment]
You might want to submit the issue to aspnet rather than dotnet https://github.com/aspnet/Home/issues

What is doing your compression? Is it IIS or have you added the ResponseCompression middleware for it? If you you might want to submit the issue to the https://github.com/aspnet/BasicMiddleware repository specifically.

**Comment by joshlang** [comment]
Ahhhhhhhhhh, my bad, sorry for the interruption.  I'll close this issue now and take it to the proper aspnet home (thought I was there - I'm new :D)
