### ISSUE TITLE
SafeAccessTokenHandle needs to move to System.Runtime

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#13291]
SafeAccessTokenHandle which is included in netstandard2.0 is currently defined in System.Security.Principal.Windows which isn't part of netstandard2.0. We need to move it down into an assembly that is part of netstandard. Majority of the other handle types are in System.Runtime so I suggest we just include this one there as well.

**Comment by ianhays** [comment]
> Majority of the other handle types are in System.Runtime so I suggest we just include this one there as well.

They're exposed in System.Runtime but implemented in coreclr.  It looks like [we've already got a version of SafeAccessTokenHandle there](https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/src/mscorlib/src/System/Security/SafeSecurityHandles.cs#L15) - can we just expose it and use that?

**Comment by weshaggard** [comment]
If the one in CoreLib is actually exposed and used then we could type-forward it there if not it shouldn't be a big deal to implement it in System.Runtime directly. Either way it should be moved into System.Runtime ref.

**Comment by ianhays** [comment]
Opened an issue to remove this type from standard and assigned it to @weshaggard: https://github.com/dotnet/standard/issues/104.
