### ISSUE TITLE
Support for Long File Paths (260+ characters) with System.IO APIs

### ISSUE THREAD

**Issue by BrainSlugs83** [dotnet/corefx#13294]
This is also a bug with the current (non-core) version of the .NET Framework -- and it would be nice if it could be passed on to both teams, but it affects everything that uses System.IO (and it has some really gnarly consequences with tools like the Azure emulator, Xamarin, etc.)

Right now anything done with the System.IO file system APIs on a Windows machine will fail if the path to the files accessed is longer than 260 characters. -- It will throw a `System.IO.PathTooLongException`.

Since `System.String` in .NET is not subject to buffer overruns, etc., those APIs should be updated to call the newer system APIs which support longer file names.  (No reason for new methods, or signatures, etc. -- this is a bug in the current framework; these methods should just be fixed to work and not throw that exception.)

If this bug is fixed (in the main version of .NET as well), so many headaches will go away for me that it's not even funny.

**Comment by karelz** [comment]
#645 added long file path support to .NET Core. I think it is also part of .full NET Framework (don't know which version exactly). I know there have been several pushes towards that goal in last couple of years.
cc: @JeremyKuhne

**Comment by JeremyKuhne** [comment]
@BrainSlugs83 We do support long paths in System.IO from 4.6.2 and up. I have a series of [blog posts](https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10) on how things work with Windows 10 and what we've enabled (`\\?\` for example) on other versions of the OS.

**Comment by JeremyKuhne** [comment]
Closing the issue. If you have any other questions please ask.

**Comment by BrainSlugs83** [comment]
Hmmm... this seems like a lot of extra work for something that should really just be fixed transparently. -- What I'm hearing is that for applications that you don't have the source to (or that have a signed manifest, etc.), there's basically no way for a user to enable this fix. -- (Which is a pretty transparent and harmless fix.)

To me, this seems like pretty much the opposite approach Microsoft has taken in the past with compatibility support (i.e. applications run with legacy compatibility turned off by default, and users have to specifically enable compatibility mode if they need the legacy behavior for something).

There are lots of broken applications in the wild that would benefit from a way to have this fix turned on by default (including lots of Microsoft provided developer tools -- some which may not be getting another version in the future -- heck, lots of normal project types refuse to build with long paths, TFS Power Tools don't work right, and the Azure emulator for Web Roles projects will just completely fail to run your project without any kind of meaningful error message...).

I mean, considering that the bug is actually pretty high impact, the strategy of releasing this as a dark fix that's behind a bunch of gates (including upgrading to .NET 4.6.2 which isn't an option for everyone) doesn't make a lot of sense to me.
 
Also burying this fix behind so many gates basically means that even most **new** applications will still suffer from this long outstanding issue. -- It would be nice to see the following things implemented:

1. The app manifest gate should be removed -- or at least have a workaround -- this way power users will at least be able to apply the other settings manually to applications in the wild (i.e. you can't edit a signed manifest -- but you can totally edit or create blah.exe.config -- and we do that already to inject DLL version redirects, and such -- but you can't edit the manifest without resigning it -- don't get me wrong -- editing the app.config for closed source apps is still really painful, but in the past, it's been the difference between shipping code and not [I'm looking at you, signalR.exe!] -- if only app.config settings were required then it would at least be possible to *ENABLE* this fix for broken applications at that point).

2. New Projects should have the fix turned on by default. (i.e. the settings should be added to the default app.config.) -- There's no reason new software should be developed with legacy mode limitations turned on by default. -- Turning on legacy / compatibility hacks should be something that developers have to opt-in to, not something they have to manually opt-out of (and especially not where the opt-out process is such black magic).

**Comment by karelz** [comment]
[Jeremy's blog post](https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/) already states:
- The app config is fully editable by power users already. What do you see missing?
- New projects (on .NET 4.6.2+) get the new behavior by default.

**Comment by JeremyKuhne** [comment]
As @karelz stated, targeting 4.6.2 or higher will get you the new behavior by default. This is our normal way of introducing new features. You can opt into anything without recompiling by tweaking the app config for a particular exe _or_ (not recommended) by editing the machine.config.

As far as Windows is concerned they didn't turn their support on without hoops due to missing OS support (cmd doesn't work with long paths, for example). Expect that part to change as they close some of the basic gaps.
