### ISSUE TITLE
Parallel.Linq.Distinct not returning first element equal element in ordered queries.

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#1330]
Parallel.Linq.Distinct doen't return the first "equal" element in ordered queries.

Take, for example, the following set: `{0, 1, 2, 3, 4, 5, 6, 7}` - and use a comparator that says everything `mod 4` is identical (so, `0` is the same as `4`, `1` and `5`, etc).  I'm somewhat expecting to get `{0, 1, 2, 3}`, but I don't - any of the 'later' identical values can be returned.

For those of you contending that "They're identical, it doesn't matter", which I somewhat thought too, I'm basing this on comments internal to the [Distinct operator](https://github.com/dotnet/corefx/blob/master/src/System.Linq.Parallel/src/System/Linq/Parallel/QueryOperators/Unary/DistinctQueryOperator.cs#L238-L251):

```
238  // For each element, we track the smallest order key for that element that we saw so far 
239  TKey oldEntry; 
240 
241  Wrapper<TInputOutput> wrappedElem = new Wrapper<TInputOutput>((TInputOutput)elem.First); 
242 
243  // If this is the first occurrence of this element, or the order key is lower than all keys we saw previously, 
244  // update the order key for this element. 
245  if (!_hashLookup.TryGetValue(wrappedElem, out oldEntry) || _keyComparer.Compare(orderKey, oldEntry) < 0) 
246  { 
247      // For each "elem" value, we store the smallest key, and the element value that had that key. 
248      // Note that even though two element values are "equal" according to the EqualityComparer, 
249      // we still cannot choose arbitrarily which of the two to yield. 
250      _hashLookup[wrappedElem] = orderKey; 
251  }
```

The [ordering page](https://msdn.microsoft.com/en-us/library/vstudio/dd460677(v=vs.110).aspx) just says these operators return "ordered" results given an ordered source, which is technically still happening - so long as there was an element in that original position, that or an equal one is returned in that position.  
Vanilla LINQ actually says `Distinct` returns _unordered_ results, but I'm guessing they really meant "we didn't use `OrderBy` to make things easier for us", especially as all the examples (and the way the operator is implemented) show that it retains the ordering of the original source (and how the other set operators behave - `Except` doesn't mention ordering, `Intersect` explicitly mentions the original order is retained, and `Union` mostly implies the original order is retained).

So... which is correct? Should the actual-first equal element be returned (as I'm expecting), or that's a stronger guarantee than we need (and any equal item can be returned in its place)?

Example reproduction code (may fail to fail):

```
using System;
using System.Collections.Generic;
using System.Linq;
using Xunit;

namespace Test
{
    public class Example
    {
        [Fact]
        public static void DistinctExample()
        {
            ParallelQuery<int> original = ParallelEnumerable.Range(0, 24).AsOrdered();
            int seen = 0;
            Assert.All(original.Distinct(new ModularCongruenceComparer(4)), i => Assert.Equal(seen++, i));
            Assert.Equal(4, seen);
        }

        private class ModularCongruenceComparer : IEqualityComparer<int>
        {
            private int _mod;

            public ModularCongruenceComparer(int mod)
            {
                _mod = Math.Max(1, mod);
            }

            private int leastPositiveResidue(int x)
            {
                return ((x % _mod) + _mod) % _mod;
            }

            public bool Equals(int x, int y)
            {
                return leastPositiveResidue(x) == leastPositiveResidue(y);
            }

            public int GetHashCode(int x)
            {
                return leastPositiveResidue(x).GetHashCode();
            }

            public int GetHashCode(object obj)
            {
                return GetHashCode((int)obj);
            }
        }
    }
}
```

**Comment by stephentoub** [comment]
> Should the actual-first equal element be returned (as I'm expecting), or that's a stronger guarantee than we need (and any equal item can be returned in its place)?

I believe it's a stronger guarantee than is needed and that the implementation is fine as-is.  Thanks for the detailed description, though!
