### ISSUE TITLE
ConcurrentDictionary.GetOrAdd documentation not quite correct

### ISSUE THREAD

**Issue by epa** [dotnet/corefx#13308]
In `ConcurrentDictionary`, the overload of `GetOrAdd` taking a function as argument says that it returns 'either the existing value for the key if the key is already in the dictionary, or the new value for the key'.  But this is not the whole story.  There are in fact three cases:

1. The key is already in the dictionary.  Then the existing value is returned.
2. The key is not in the dictionary; the function `valueFactory` is called and generates a value.  But then on rechecking, some other thread has inserted a value for that key in the meantime.  In this case, the other thread's value is the one returned.  The value returned by `valueFactory` is discarded.
3. The key is not in the dictionary; `valueFactory` is called; it's still not there, so the new value is inserted and returned.

It needs to be a bit clearer that `valueFactory` can end up being called but its return value is not the final one returned.

**Comment by stephentoub** [comment]
The remarks section states:
```
If you call GetOrAdd simultaneously on different threads, addValueFactory may be called multiple times, but its key/value pair might not be added to the dictionary for every call.
```

**Comment by epa** [comment]
Ah thanks, I didn't spot that - but I still feel that where concurrency issues are concerned, better to spell out all the possibilities as explicitly as possible.  The remark does not make it clear that the value returned from `GetOrAdd` might not be the one returned by `valueFactory`, even if `valueFactory` was called.

**Comment by Priya91** [comment]
cc @mairaw

**Comment by mairaw** [comment]
We can get the docs improved. Can you assign issues to me here? Or does this issue needs to be moved to https://github.com/dotnet/docs?

**Comment by Priya91** [comment]
Assigned the issue to you. Thanks!

**Comment by ianhays** [comment]
@mairaw have you been able to take a look at this?

**Comment by mairaw** [comment]
Same as the other one @ianhays. All the issues assigned to me at the moment are all in my backlog until I finish my priorities for the upcoming releases.

**Comment by ianhays** [comment]
Gotcha, thanks for the update :)

**Comment by mairaw** [comment]
Issue moved to [dotnet/docs #1940](https://github.com/dotnet/docs/issues/1940) via [**ZenHub**](https://www.zenhub.com/)
