### ISSUE TITLE
Parallel.Linq.Union not completely ordered

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#1331]
...or perhaps this is just a documentation issue (insufficient specification):

`Union` is a binary operator, and as such takes two `ParallelQuery`s.  When dealing with ordered queries, only the portion coming from an ordered source is returned ordered.  
That is:

    ParallelEnumerable.Range(0, 8).AsOrdered().Union(ParallelEnumerable.Range(8, 8))

...returns the first 8 elements (`{0, 1, 2, 3, 4, 5, 6, 7}`) in order, and the last 8 elements in whatever order it pleases, and the opposite:

    ParallelEnumerable.Range(0, 8).Union(ParallelEnumerable.Range(8, 8).AsOrdered())

... returns the first 8 elements in whatever order it pleases, and the last 8 elements in order (`{8, 9, 10, 11, 12, 13, 14, 15}`).
(note that in either case, left will _always_ come before right when either is ordered)

The [ordering page](https://msdn.microsoft.com/en-us/library/vstudio/dd460677(v=vs.110).aspx) merely specifies that passing an ordered source returns ordered results, which is unhelpful.  
Vanilla LINQ returns elements completely in order by default, although this would be more an effect of the optimization.  
LINQ to SQL wouldn't necessarily return elements in order **at all**, even if both sources were ordered - the SQL clause `UNION` is free to ignore ordering from subqueries when getting the distinct set.

So what's the correct behavior here?  If either source is ordered, output is ordered for both?  Only the portion coming from an ordered source should be ordered (current behavior)?  
(Or 3- If either is unordered, neither is ordered)

**Comment by AlfredoMS** [comment]
I think this is just a documentation issue. It does mention that Union produces ordered results when input is actually ordered. In your examples only have of the input was ordered. so I think the current behavior is correct.
