### ISSUE TITLE
Parts of the System.Security.Cryptography.* namespace missing in package: dotnet-dev-1.0.0-preview2.1-003155

### ISSUE THREAD

**Issue by m4x1202** [dotnet/corefx#13310]
I installed the dotnet-dev-1.0.0-preview2.1-003155 package on ubuntu:16.04 but it seems that parts of the System.Security.Cryptography.* namespace are missing. Thus i get a
`System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.` exception.
The docker container microsoft/dotnet:1.0.0-preview2.1-sdk however contains the missing parts of the namespace.
Is this an issue or am i doing something wrong?

**Comment by m4x1202** [comment]
This behavior unfortunately did not change with the current release: dotnet-dev-1.0.0-preview2.1-003177

**Comment by bartonjs** [comment]
@m4x1202 Do you have a full stack trace? Nothing in new builds should be looking for that library (it was replaced).  Your project.json will likely also be interesting.

**Comment by m4x1202** [comment]
@bartonjs thanks for your reply. This would be the full stack trace: ```Unhandled Exception: System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.CryptoInitializer.EnsureOpenSslInitialized()
   at Interop.CryptoInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.CryptoInitializer.Initialize()
   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.X509Duplicate(IntPtr handle)
   at Internal.Cryptography.Pal.CertificatePal.FromHandle(IntPtr handle)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(IntPtr handle)
   at System.Net.Http.CurlHandler.SslProvider.VerifyCertChain(IntPtr storeCtxPtr, IntPtr curlPtr)
   at Interop.Http.MultiPerform(SafeCurlMultiHandle multiHandle)
   at System.Net.Http.CurlHandler.MultiAgent.WorkerBodyLoop()```

Also when i try to find the namespace: `find / -name "System.Security.Cryptography.Native*"
/usr/share/dotnet/shared/Microsoft.NETCore.App/1.1.0/System.Security.Cryptography.Native.OpenSsl.so`
Nothing shows up

**Comment by bartonjs** [comment]
@m4x1202 Only finding System.Security.Cryptography.Native.OpenSsl.so makes sense, because we switched to it.  Do you have a local copy of System.Security.Cryptography.X509Certificates, or are you loading the one from the shared framework?

You could use strace to find out where it's coming from:

```
jbarton@jsb-ubuntu2:~/test$ strace -e lstat dotnet run 2>&1 | grep X509C
lstat("/usr/share/dotnet/shared/Microsoft.NETCore.App/1.1.0/System.Security.Cryptography.X509Certificates.dll", {st_mode=S_IFREG|0644, st_size=356352, ...}) = 0
```

(or without filtering to just lstat)

```
jbarton@jsb-ubuntu2:~/test$ strace dotnet run 2>&1 | grep X509C
stat("/usr/share/dotnet/shared/Microsoft.NETCore.App/1.1.0/System.Security.Cryptography.X509Certificates.dll", {st_mode=S_IFREG|0644, st_size=356352, ...}) = 0
lstat("/usr/share/dotnet/shared/Microsoft.NETCore.App/1.1.0/System.Security.Cryptography.X509Certificates.dll", {st_mode=S_IFREG|0644, st_size=356352, ...}) = 0
stat("/home/jbarton/.nuget/packages/System.Security.Cryptography.X509Certificates/4.3.0", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
stat("/home/jbarton/.nuget/packages/System.Security.Cryptography.X509Certificates/4.3.0", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
stat("/home/jbarton/.nuget/packages/System.Security.Cryptography.X509Certificates/4.3.0", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
```

**Comment by m4x1202** [comment]
@bartonjs sry this took a little.
I basically checked my setup again and with the help of your clarification i was able to get my docker image working.
I assume that when i first tested my server with netcore 1.1.0, I failed to fully uninstall the 1.1.0 preview (dotnet-dev-1.0.0-preview2.1-003155) and therefore still got the Exception with 1.1.0 (probably missed to remove some dependencies).
With a fresh installation of netcore 1.1.0 my server started just fine.
Ty for your help, really appreciate it.

**Comment by bartonjs** [comment]
@m4x1202 Glad you were able to get it worked out!
