### ISSUE TITLE
Double buffers to overlap reads and writes on CopyToAsync

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#13322]
Considering the current implementation of `CopyToAsync`:

```C#
byte[] buffer = new byte[bufferSize]; // or from ArrayPool<byte> but eliding for sake of discussion.
while (true)
{
    int bytesRead = await ReadAsync(buffer, 0, buffer.Length, cancellationToken).ConfigureAwait(false);
    if (bytesRead == 0) break;
    await destination.WriteAsync(buffer, 0, bytesRead, cancellationToken).ConfigureAwait(false);
}
```

The approach is obvious enough, read some octets, then write them, then repeat.

Potentially though the source stream could be read from while the destination stream was written to:

```C#
byte[] buffer0 = new byte[bufferSize];
byte[] buffer1 = new byte[bufferSize];
Task writeTask0;
Task writeTask1 = null;
int read0 = await ReadAsync(buffer0, 0, buffer0.Length, cancellationToken).ConfigureAwait(false);
if (read0 != 0)
{
    while (true)
    {
        writeTask0 = destination.WriteAsync(buffer0, 0, read0, cancellationToken).ConfigureAwait(false);
        int read1 = await ReadAsync(buffer1, 0, buffer1.Length, cancellationToken).ConfigureAwait(false);
        if (read1 == 0)
        {
            break;
        }

        await writeTask0;
        writeTask1 = destination.WriteAsync(buffer1, 0, read1, cancellationToken).ConfigureAwait(false);
        read0 = await ReadAsync(buffer0, 0, buffer0.Length, cancellationToken).ConfigureAwait(false);
        if (read0 == 0)
        {
            break;
        }

        await writeTask1;
    }

    if (!writeTask0.IsCompleted)
    {
        await writeTask0;
    }
    else if (writeTask1 != null)
    {
        await writeTask1;
    }
}
```

Maybe I'm missing something, or maybe the extra heap space isn't worth it, but would this be a viable improvement?

**Comment by stephentoub** [comment]
Thanks, @JonHanna.  We've considered this in the past, as it does have obvious benefits.  However, it introduces concurrency where there wasn't any before, which also leads to interesting failure conditions where operations may be in flight when another fails, or both may fail, etc., which can lead to both reliability problems as well as programming model issues (e.g. propagating both failures in an AggregateException?).  It also increases the resource consumption for a single operation, not only doing multiple I/O operations concurrently but also even just the need for two buffers, and even if they come from a pool, there is still a limit to what's pooled, so in the limit this means we're still going to be allocating more buffers.  All in all, we've not seen sufficient evidence to warrant adding this complexity and cost in real apps. (I seem to remember @benaadams opening a similar issue at one point, but I can't find it now.)

**Comment by benaadams** [comment]
@stephentoub https://github.com/dotnet/corefx/pull/5954#r52127427 😄
