### ISSUE TITLE
Parallel.Linq.Concat not consistent with ordered input

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#1332]
`Parallel.Linq.Concat` isn't behaving consistently when given ordered input sources.

As `Concat` is a binary operator, two sources may be supplied.  The inconsistency surfaces depending on which, and how, operand is ordered.

If both **or** either (only the left or the right) is ordered via `AsOrdered()`, the entire output is ordered.
If the left operator is ordered via any of the `OrderBy(...)` operators (`OrderBy`, `OrderByDescending`, `ThenBy`, `ThenByDescending`), the entire output is ordered.
If the _right_ operator is ordered via any of the `OrderBy(...)` operators, only the _left_ output is ordered (as by `AsOrdered()`), and the right is returned in a non-deterministic order.  

It only seems to do this with right sources constructed via `Enumerable.Range(...).AsParallel()` and `Partitioner.Create(...).AsParallel()`.  Using a `List` is safe (eg, `Enumerable.Range(...).ToList().AsParallel()`), however the output of LINQ is not: `list.Select(x => x).AsParallel()` can return unordered output.
How the left operand is constructed appears to have no effect.

This is also the behavior of the current consumer release.

Example program:

    static void Main(string[] args)
    {
        int leftSize = 8;
        int rightSize = 8;

         ParallelQuery<int> query = ParallelEnumerable.Range(0, leftSize)
                                .Concat(Enumerable.Range(0, rightSize).AsParallel().OrderBy(x => x));

        foreach (int i in query)
        {
            Console.Write(i + "|");
        }
        Console.ReadLine();
    }

(This is a bit of a Heisenbug - expect it to generate completely ordered output on occasion.  It's possible that it does this for all input types, and I just haven't seen it yet, although I consider this unlikely)

The [ordering page](https://msdn.microsoft.com/en-us/library/vstudio/dd460677(v=vs.110).aspx) states that ordered input to `Concat` results in ordered output, and unordered input results in unordered output, but it isn't clear what happens when you have one of each.  At minimum, the output actually observed is disturbing on first encounter.

`Zip` appears to operate similar to how I anticipate `Concat` operating - if either input is ordered, the entire output is ordered, regardless of source.

**Comment by Clockwork-Muse** [comment]
But wait, there's more!

It turns out that neither array-sourced or `ParallelEnumerable.Range(...)`-sourced queries are safe after all (or `List`-sourced, either).  It turns out that it doesn't run the `OrderBy` on the inner query, if the outer query doesn't have some form of ordering on it (`OrderBy`, `AsOrdered`, whatever).  Instead, you get the equivalent of `AsOrdered` on those sources.

That is, `ParallelEnumerable.Range(0, 4).Concat(ParallelEnumerable.Range(4, 4).OrderBy(x => -x))` will return the ordered range `{0, 1, 2, 3, 4, 5, 6, 7}`, and **not** `{0, 1, 2, 3, 7, 6, 5, 4}` as I'm expecting.
(whether this is because the entire output is supposed to be unordered I don't know, but it's clearly doing something it shouldn't be).

`Zip` is unaffected by this.  I'm assuming this part of the issue is also part of the current consumer release issue.

Now I have to figure out how I'm going to expand the tests _more_ for this library.  
("You get reverse ordering! And you!  Reverse ordering for everybody!")

**Comment by AlfredoMS** [comment]
> The ordering page states that ordered input to Concat results in ordered output, and unordered input results in unordered output, but it isn't clear what happens when you have one of each. At minimum, the output actually observed is disturbing on first encounter.

Sound like by design it was not specified.

@stephentoub do you think this is an actual bug, or just the nature of ParallelEnumarators?

**Comment by stephentoub** [comment]
If one of the inputs to concat isn't ordered, then by definition all of the input is not ordered.  The specified guarantees only apply when all of the inputs are ordered.  If the current implementation happens to do better than that in some circumstances, it's purely a side effect of an implementation detail.
