### ISSUE TITLE
Missing types while attempting to port a library with native dependency

### ISSUE THREAD

**Issue by Kukkimonsuta** [dotnet/corefx#1333]
I'm playing with library with a native dependency (LibGit2Sharp) and attempting to port it over to core clr, however aside from some minor issues I'm having trouble locating following types:

```
System.Runtime.ConstrainedExecution.CriticalFinalizerObject
System.Runtime.ConstrainedExecution.ReliabilityContract
System.Runtime.ConstrainedExecution.Consistency
System.Runtime.ConstrainedExecution.Cer
```
```
System.Runtime.InteropServices.ICustomMarshaler
System.Runtime.InteropServices.UnmanagedType.CustomMarshaller (enum value)
```
```
System.SerializableAttribute
System.Runtime.Serialization.SerializationInfo
```

I haven't found any mention of those in https://github.com/dotnet/corefx-progress nor http://packagesearch.azurewebsites.net/ , so I'd like to ask whether these are going to be included, are no longer needed (do they have an alternative?) or whether I'm missing something and they are already available.

Thank you

**Comment by terrajobst** [comment]
Thanks @Kukkimonsuta. These are good question. Would you mind splitting this into three issues?

1. Support for CERs
2. Support for ICustomMarshaller
3. Support for binary serialization

This way, we can track and assign corresponding owners more easily.

**Comment by Kukkimonsuta** [comment]
Done. Funny thing, that I always complain about people putting multiple things together into single ticket and now I'm apparently doing the same.. :expressionless:
