### ISSUE TITLE
 Dns.GetHostAddressesAsync(Dns.GetHostName()) not working on centos7

### ISSUE THREAD

**Issue by IKende** [dotnet/corefx#13346]
using  Dns.GetHostAddressesAsync(Dns.GetHostName()) can't load local ip address on centos 7 system

**Comment by karelz** [comment]
@Priya91 says this is dupe - please find it.

**Comment by Priya91** [comment]
@IKende What is the exact error you get? Refer this issue #13309

**Comment by Priya91** [comment]
Closing due to lack of further information to proceed.
