### ISSUE TITLE
XsdDataContractExporter.DataContractSet always returns null

### ISSUE THREAD

**Issue by huanwu** [dotnet/corefx#13355]
The following code in DataContractSet is commented. So XsdDataContractExporter.Export will always fail because of NullReferenceException
        DataContractSet DataContractSet
        {
            get
            {
                //if (dataContractSet == null)
                //{
                //    dataContractSet = new DataContractSet((Options == null) ? null : Options.GetSurrogate());
                //}
                return _dataContractSet;
            }
        }

**Comment by karelz** [comment]
Dupe of #12772 (GetSurrogate is the common theme there)
