### ISSUE TITLE
Collections should have extensions to compute order statistic

### ISSUE THREAD

**Issue by pkothare** [dotnet/corefx#1336]
`System.Linq` has extensions implemented for computing the minimum and maximum. 

Example:

``` C#
var a = new int[] {100, 300, 200, 400};
WriteLine(a.Max()); // prints 400
WriteLine(a.Min()); // prints 100
```

While these are useful values when dealing with collections, they are merely special cases of nth order statistics. More often than not, people are also interested in a specific cases. For example, when querying the collection in the sample code above, the question may be posed, what is the 3rd smallest item in the array?

The naive implementation would be to sort the array and print the 3rd item in it. However, there are selection algorithms that can do this more efficiently, without the need to actually invoke a sort method on the array. A method should be implemented in line with the `Min` and `Max` extension methods to accomplish this. The API should be a simple as:

``` C#
WriteLine(a.NthSmallestElement(3)) // should print 300
WriteLine(a.NthSmallestElement(1)) // should print 100
WriteLine(a.NthSmallestElement(a.Length)) // should print 400
```

The method name may differ based on further discussion. I chose the name based on C++ references that I had seen earlier.

**Comment by terrajobst** [comment]
@theoy, can you make sure this gets triaged?

**Comment by karelz** [comment]
We need formal API proposal

**Comment by JonHanna** [comment]
> The naive implementation would be to sort the array and print the 3rd item in it.

The combination `.OrderBy(x => x).ElementAt(2)` would find the third element using Hoare's quickselect algorithm. The pivot strategy is simple median, which is indeed naïve. I thought of experimenting with random, median-of-three, etc. and even made a start at it, but got distracted by other things. It'd be worth looking at.

**Comment by jnm2** [comment]
I also find tremendous usage of my `public static T MaxBy<T, TSort>(this IEnumerable<T> enumerable, Func<T, TSort> sortSelector, IComparer<TSort> sortComparer = null)`. I wonder if having overloads that take a sort selector like OrderBy would be a good addition to this proposal?

**Comment by karelz** [comment]
Unless it is directly related to these APIs, I would suggest to keep it in separate issue.

**Comment by jnm2** [comment]
@karelz To clarify, I'm suggesting that this proposal considers:

```c#
a.NthSmallestElement(3)
a.NthSmallestElement(3, _ => _.SortValue)
```

**Comment by karelz** [comment]
In the last post you suggested adding `MaxBy`. How does that fit?
Either way, we still need [formal API proposal](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md). It is also best way to clarify what exactly is asked for and why.

**Comment by jnm2** [comment]
@karelz `NthSmallestElement(0)` is `Min()` and `NthLargestElement(0)` is `Max()`. My point was that I haven't found `Max` to be half as useful as `MaxBy`, so I would expect that `NthSmallestElement(n)` would not be half so useful as `NthSmallestElement(n, sortSelector)`. 
`MaxBy` would be great too, but I'd have to start a proposal for that.

**Comment by jnm2** [comment]
Separate point: `ElementAt` is 0-based but it looks like `NthSmallestElement` is proposed to be 1-based. What are the consequences of choosing 0 or 1?

**Comment by karelz** [comment]
> I would expect that `NthSmallestElement(n)` would not be half so useful as `NthSmallestElement(n, sortSelector)`

Now I see your point. It makes sense to keep them together as they are very related APIs.

> `ElementAt` is 0-based but it looks like `NthSmallestElement` is proposed to be 1-based. What are the consequences of choosing 0 or 1?

Very good question - I would expect the proposal to suggest solution here, providing arguments why.

**Comment by JonHanna** [comment]
One question is whether the IQueryable version of this immediately return `.OrderBy(…).ElementAt(n - 1)`, or directly represent an `NthSmallest` operation. The latter has the advantage that a provider could more directly support it, but the former would allow for backwards compatibility.

**Comment by jnm2** [comment]
> One question is whether the IQueryable version of this immediately return `.OrderBy(…).ElementAt(n - 1)`, or directly represent an `NthSmallest` operation. The latter has the advantage that a provider could more directly support it, but the former would allow for backwards compatibility.

I would hope it would do whatever `Max` does today.

**Comment by JonHanna** [comment]
The tactic `Max` uses is to be in `Queryable` from the time it was first created, so that anyone writing a query provider knows about it, and knows to implement it unless that's impossible for some reason.

**Comment by jnm2** [comment]
For example, I would not expect `NthSmallest` to work until Entity Framework knows about it. It's not unusual for BCL extension methods to be unsupported by EF.
I'd prefer the semantics to be preserved. `.OrderBy(…).ElementAt(n - 1)` has polyfilling going for it but has neither semantics nor perf on it's side.

Separate note: I'm really not in love with the name `NthSmallestElement`. Off the top of my head I don't know any place I would use it either, so from my vantage point it'd just be extra names in IEnumerable intellisense.

**Comment by JonHanna** [comment]
On the other hand, it's unlikely that any provider is likely to do anything other than the same as it would with `.OrderBy(…).ElementAt(n - 1)` (for that matter, with IEnumerable it's going to be pretty much the same as that anyway, except for one object allocation). If providers aren't going to find some extra benefit then that is likely the way to go.

I'm sceptical if there's any need for this for similar reasons. The initial comment said:

>The naive implementation would be to sort the array and print the 3rd item in it. However, there are selection algorithms that can do this more efficiently, without the need to actually invoke a sort method on the array.

And at the time of writing, `.OrderBy(…).ElementAt(n - 1)` would have sorted the array and then found the 3rd item, whereas now it uses a selection algorithm (or just spins through and finds the minimum order if `n` happens to be 1).

**Comment by pkothare** [comment]
@JonHanna, I'm just curious, is the current process of selection still subject to n^2 worst case time complexity?

**Comment by JonHanna** [comment]
It is, except for the indices of 0 or Count - 1; they're guaranteed linear time.

I've thought about randomising the pivots, but not experimented with it. For one thing I've honestly no idea how fast the PRNG is and hence whether it would have an appreciable downside in some cases.

Ideas? (If the idea in this issue was pursued, it would be necessary to consider it there, to).

**Comment by svick** [comment]
@jnm2 

> `MaxBy` would be great too, but I'd have to start a proposal for that.

There already is one: https://github.com/dotnet/corefx/issues/2146.

**Comment by pkothare** [comment]
> ElementAt  is 0-based but it looks like  NthSmallestElement  is proposed to be 1-based. What are the consequences of choosing 0 or 1?

The justification here to use 1 based instead of 0 based arguments for the method, is because of the semantics of language. For example, given the following array:

`var a = new int[] {100, 200, 300, 400};`

we can characterize 300 in the following way:

- It is the 3rd element in the array
- It has index value of 2
- It is the 3rd smallest value in the array

If the proposed naming convention `NthSmallestElement()` is used, it would be incorrect to use a parameter based on index value. Imagine `NthSmallestElement(2)` returning 300. This would cause so much confusion based on the characterization stated above.

Conversely, a better naming convention instead of `NthSmallestElement` can be propsed that accepts an index value as an argument.

@JonHanna , the more I think about it, the more I realize that the invocation of `OrderBy(...).ElementAt(...)` does not signal to a developer consuming the API that they are trying to calculate the nth order statistic. It's true that as a consequence of optimization that it does indeed end up invoking a selection algorithm. I feel like the implementation of `NthSmallestElement` should be first addressed independently of  `OrderBy` and `ElementAt`. If at a later point they do happen to converge that's great. Also the 3 median / me

I also agree with @jnm2, the use of `NthSmallestElement<TSource, TKey>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector)` provides a lot of flexibility.

**Comment by jnm2** [comment]
Given https://github.com/dotnet/corefx/issues/2146, we might want `NthSmallestElementBy` for consistency. Also, I make good use of the `IComparer<TKey>` at times!

**Comment by karelz** [comment]
The more I think about these APIs, the less I am convinced that they are widely used/valuable for us to include them in BCL. Maybe they should be part of external library, e.g. together with specialized sort algorithms (#2252)?

**Comment by terrajobst** [comment]
I agree with @karelz. This feels incredibly specialized.

**Comment by pkothare** [comment]
I agree with @karelz to a certain extent. However, on the flip side, pure statistics are also starting to play a larger role in the realm of computing and becoming more mainstream(everything from building dashboards and collecting metrics to machine learning). 

This proposition stemmed from a need to analyze relatively large in memory datasets that were created using BCL generic collections. The question then becomes why were BCL collections used and not some 3rd party library that has the capability to compute the necessary order statistics? I would say why not? There is already such rich API exposed for set operations in BCL, and the adoption is by default required when working with .NET. Furthermore, `Min`, `Max`, `Count` and `Average` are already exposed as methods, so then why not `Median`?

If the nth order statistic were implemented, it would then open the door to calculating other statistically relevant values like the median, upper quartile, lower quartile, inter quartile range, without much further effort.

While optimization is part of the problem, I don't think it is the primary problem. For me, the fundamental issue is completeness of the API. Using `OrderBy` and `ElementAt` chained together does not necessarily express the same motive as `NthOrderStatistic` (found a better name for it).

I would like to hear more about your opinions on this.

**Comment by JonHanna** [comment]
> If the nth order statistic were implemented, it would then open the door to calculating other statistically relevant values like the median, upper quartile, lower quartile, inter quartile range, without much further effort.

I like the idea of a `Statistics` class providing for many of these, separate to Linq (though perhaps with overloads for `IQueryable` so that it would play nicely with Linq providers). Added to `Enumerable` and `Queryable` `NthOrder` does seem rather specialised, but `Statistics.NthOrder` seem an obvious method.

**Comment by karelz** [comment]
@pkothare I agree that statistics are useful in general. The point is that adding just one more is not going to make us much more "complete" in BCL. We should probably have also standard deviation, etc. All those things would be best added in a separate class, ideally in separate library. They can be extension methods for ease of use. They will be used by folks who care about these things more than just about the basics.

> Using `OrderBy` and `ElementAt` chained together does not necessarily express the same motive as `NthOrderStatistic` (found a better name for it).

Personally, I don't see a difference between those 2 approaches.

**Comment by pkothare** [comment]
Understood. Is a formal API proposal still in order or should this issue be closed and reopened under a different repo?

**Comment by karelz** [comment]
Yes, we should close the issue - looks like no one will push back strongly. If I am wrong, then we can reopen again.
There is no other appropriate repo I know about -- I would expect someone to create a new library or contribute to an existing one.
