### ISSUE TITLE
Add a new public Slim NTAuthentication type to support various authentication protocols.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#13364]
System.Net.Mail is using an internal type NTAuthentication from System.Net.Security to implement NTLM, GSSAPI and Digest protocols for credential authentication. Currently I’m using reflection to get to these types, but this is not a reliable permanent solution. We have similar issues around authentication in HttpListener as well.

In both cases, we need to send a response string back to the server, which is obtained by sending the challenge from server through the protocol.
Currently there are 2 obstacles
1.	NTAuthentication.GetOutgoingBlob/GetContextToken/GetOutoingDigestBlob API is internal
2.	NTAuthentication type does not have API to choose from available protocols it supports

I can see 2 options:
Option 1: Make NTAuthentication type public and add to it new APIs for choosing authentication protocol.
Cons: NTAuthentication is large beast and it has lots of dependencies. It hasn’t been designed to be public API.

Option 2: Create new ‘SlimAuthentication’ type which is independent of server protocols (has no context whether smtp, ftp, web, etc) and implements various authentication protocols like NTLM, GSSAPI, Digest, Login (these currently exist in NTAuthentication).

One thing to keep in mind, we might want to add support for newer protocols like XOAUTH2, OAUTH2 which seems to be a popular choice in many smtp servers like google, Comcast, yahoo, outlook.live, office365, etc, to this new type, hence the design should be extensible.

cc @davidsh @CIPop @weshaggard @ericeil @geoffkizer @karelz

**Comment by atanasa** [comment]
Why is this closed? I couldn't find either of option 1 and 2 being currently implemented.

**Comment by karelz** [comment]
@Priya91's change above (#13821) did option 3 - making the code shared (via Common) across assemblies (technically there are multiple copies). While not ideal, it will give us time to focus on proper solution and API shape in option 2, instead of rushing through API now or exposing API we do not want long-term in option 1.

**Comment by Priya91** [comment]
The immediate problem to support authentication in Mail and HttpListener was simply solved using the easiest and less time consuming solution of sharing files. I still have it in my backlog to design a server protocol independent authentication APIs that can be used more generically. Haven't had time to come up with an API proposal, it's in my backlog :)

**Comment by CIPop** [comment]
> I still have it in my backlog to design a server protocol independent authentication APIs that can be used more generically

Isn't [AuthenticationManager ](https://msdn.microsoft.com/en-us/library/system.net.authenticationmanager(v=vs.110).aspx) already exposing such an API?

**Comment by Priya91** [comment]
AuthenticationManager is tied to a WebRequest, it's not reusable, say if i am writing a new smtp server.

**Comment by karelz** [comment]
@Priya91 did you file an issue to track the new API proposal?

**Comment by Priya91** [comment]
> @Priya91 did you file an issue to track the new API proposal?

Not yet, need time to investigate scenarios and design a speclet.

**Comment by karelz** [comment]
Just file an issue describing the idea / purpose, without too much details (1-2 lines is enough). It will be easier to reference :)
