### ISSUE TITLE
IFragmentCapableXmlDictionaryWriter not implemented by XmlBaseWriter

### ISSUE THREAD

**Issue by huanwu** [dotnet/corefx#13375]
IFragmentCapableXmlDictionaryWriter is not implemented by any class.  In desktop, it is implemented by XmlBaseWriter.

Our code:
internal abstract class XmlBaseWriter : XmlDictionaryWriter
{...}

Code in desktop.
abstract class XmlBaseWriter : XmlDictionaryWriter, IFragmentCapableXmlDictionaryWriter
{...}

**Comment by karelz** [comment]
Should it be netstandard2.0?

**Comment by huanwu** [comment]
@karelz yes, added the tag.

**Comment by danmosemsft** [comment]
Not public surface area.

**Comment by shmao** [comment]
We agreed not going to make XmlBaseWriter to implement this interface. We will do that when it's needed. 

@huanwu , Can you please delete the related tests for this?
