### ISSUE TITLE
Expose types/members in contract assemblies

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#13372]
Most implementations exist, but they are not present in contract/reference + testing

### Remaining APIs - TODO:

T:System.Net.TransportType -- https://github.com/dotnet/corefx/issues/14106

M:System.Net.Security.NegotiateStream.Dispose(System.Boolean) https://github.com/dotnet/corefx/issues/14107

M:System.Net.Security.SslStream.Dispose(System.Boolean) https://github.com/dotnet/corefx/issues/14107

F:System.Net.Sockets.AddressFamily.Max --https://github.com/dotnet/corefx/issues/14106

```c#
    public class WebHeaderCollection : NameValueCollection, IEnumerable, ISerializable {
        public void Set(HttpRequestHeader header, string value);
        public void Set(HttpResponseHeader header, string value);
        public override void Set(string name, string value);
    }
``` 
above is https://github.com/dotnet/corefx/issues/14108

- `IDisposable` on `public class FtpWebResponse : WebResponse, IDisposable` https://github.com/dotnet/corefx/issues/14107

### Tracked externally
- #13900 - HttpWebRequest and HttpWebResonse
- #13901 - HttpListener*
- #12460 - Socket
- #12134 - NetworkCredential

### Finished APIs
#13357
* `M:System.Net.HttpWebRequest.EndGetRequestStream(System.IAsyncResult,System.Net.TransportContext@)`

#13354
* `M:System.Net.HttpWebResponse.Close`
* `M:System.Net.HttpWebResponse.set_Cookies(System.Net.CookieCollection)`

#13377
* `T:System.Net.FtpStatusCode`
* `M:System.Net.FtpWebRequest.set_Headers(System.Net.WebHeaderCollection)`
* `P:System.Net.FtpWebResponse.BannerMessage`
* `P:System.Net.FtpWebResponse.ExitMessage`
* `P:System.Net.FtpWebResponse.LastModified`
* `P:System.Net.FtpWebResponse.StatusCode`
* `P:System.Net.FtpWebResponse.StatusDescription`
* `P:System.Net.FtpWebResponse.WelcomeMessage`

**Comment by danmosemsft** [comment]
@CIPop  These too are implemented but not yet exposed:
```


    public class HttpListenerTimeoutManager {
        public TimeSpan DrainEntityBody { get; set; }
        public TimeSpan EntityBody { get; set; }
        public TimeSpan HeaderWait { get; set; }
        public TimeSpan IdleConnection { get; set; }
        public long MinSendBytesPerSecond { get; set; }
        public TimeSpan RequestQueue { get; set; }
    }

    public class HttpListenerException : Win32Exception {
        protected HttpListenerException(SerializationInfo serializationInfo, StreamingContext streamingContext);
        public override int ErrorCode { get; }
    }

    public sealed class HttpListener : IDisposable {
        public ServiceNameCollection DefaultServiceNames { get; }
        public ExtendedProtectionPolicy ExtendedProtectionPolicy { get; set; }
        public HttpListener.ExtendedProtectionSelector ExtendedProtectionSelectorDelegate { get; set; }
        public HttpListenerTimeoutManager TimeoutManager { get; }
        public delegate ExtendedProtectionPolicy ExtendedProtectionSelector(HttpListenerRequest request);
    }

    public sealed class HttpListenerContext {
        public Task<HttpListenerWebSocketContext> AcceptWebSocketAsync(string subProtocol, TimeSpan keepAliveInterval);
    }

```

**Comment by danmosemsft** [comment]
One more 
```
    public class WebHeaderCollection : NameValueCollection, IEnumerable, ISerializable {
        public void Set(HttpRequestHeader header, string value);
        public void Set(HttpResponseHeader header, string value);
        public override void Set(string name, string value);
    }
```

@karelz  fyi.

**Comment by CIPop** [comment]
Other difference @karelz @danmosemsft FYI:

Missing EditorBrowsableAttribute. I can see this within NetFX code:

```

    public sealed class HttpListenerContext {
         [System.ComponentModel.EditorBrowsableAttribute((System.ComponentModel.EditorBrowsableState)(1))]
          public System.Threading.Tasks.Task<System.Net.WebSockets.HttpListenerWebSocketContext> AcceptWebSocketAsync(string subProtocol, int receiveBufferSize, System.TimeSpan keepAliveInterval, System.ArraySegment<byte> internalBuffer) { throw null; }
    }
```

**Comment by CIPop** [comment]
Another one @karelz @danmosemsft FYI:

Internal within Standard, private in CoreFX:

```
     public partial class HttpListenerWebSocketContext : System.Net.WebSockets.WebSocketContext
      {
 -        private HttpListenerWebSocketContext() { }
 +        internal HttpListenerWebSocketContext() { }

```

**Comment by CIPop** [comment]
@weshaggard @karelz @danmosemsft 
/cc @stephentoub 

I see a lot of cases where in the netstandard/ref the classes are `partial` but in corefx they are not:

```
namespace System.Net.Mime
  {
 -    public class ContentDisposition
 +    public partial class ContentDisposition
```

**Comment by CIPop** [comment]
`NetworkChange` is `static` in netstandard but not in CoreFX:

```
-    public partial class NetworkChange
 +    public static partial class NetworkChange
```

**Comment by CIPop** [comment]
`FileWebRequest` has some extra members:
* The internal ctor.
* Nit: The serialization ctor is also adding the derivation within the ref file (probably not hurting but doesn't seem necessary).

```
+    public partial class FileWebRequest : System.Net.WebRequest, System.Runtime.Serialization.ISerializable
      {
 -        internal FileWebRequest() { }
 -        [Obsolete("Serialization is obsoleted for this type. http://go.microsoft.com/fwlink/?linkid=14202")]
 -        protected FileWebRequest(System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext) : base(serializationInfo, streamingContext) { }
 +        [System.ObsoleteAttribute("Serialization is obsoleted for this type. http://go.microsoft.com/fwlink/?linkid=14202")]
 +        protected FileWebRequest(System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext) { }
```

**Comment by CIPop** [comment]
FtpWebResponse should be disposable (checked NetFX as well) but it's not currently in CoreFX:

```
-    public class FtpWebResponse : WebResponse
 +    public partial class FtpWebResponse : System.Net.WebResponse, System.IDisposable
```

**Comment by danmosemsft** [comment]
> NetworkChange is static in netstandard but not in CoreFX. 

Should not be breaking I think.

> I see a lot of cases where in the netstandard/ref the classes are partial but in corefx they are not

Only a source breaking change.

>Internal within Standard, private in CoreFX

I suspect the tool that generated standard uses the internal constructors as a placeholder to tell the compiler that there is no public parameterless constructor on the type. `private` works just as well for this purpose.

>FtpWebResponse should be disposable

I already noted this higher up.

**Comment by CIPop** [comment]
FtpWebResponse defines the overriden ContentType API within the ref in CoreFX although the original NetFX implementation or netstandard doesn't:

```
-        public override string ContentType { get { throw null; } }
```

**Comment by CIPop** [comment]
>> FtpWebResponse should be disposable

>I already noted this higher up.

Sorry, missed that one.

**Comment by CIPop** [comment]
HttpWebRequest is not marked as Serializable:

```
-    public partial class HttpWebRequest : System.Net.WebRequest
+    public partial class HttpWebRequest : System.Net.WebRequest, System.Runtime.Serialization.ISerializable
```

**Comment by karelz** [comment]
BTW: We are reusing this issue to discuss tons of things, while useful in general, it is extremely hard to track. Please do not forget to update the top post with things that still need to happen as part of this issue. Feel free to submit PR addressing just subsets of the problems.

**Comment by danmosemsft** [comment]
> FtpWebResponse defines the overriden ContentType API within the ref in CoreFX although the original NetFX implementation or netstandard doesn't

This probably doesn't matter. I believe the presence of overrides is irrelevant to binary compatibility. If they are missing from the implementation that is sometimes a bug in the implementation: porting overlooked part of the code and did not notice because apicompat will not complain.

> HttpWebRequest is not marked as Serializable

I'm not sure what you're diffing here. I believe least one of the partial classes in the ref, and in the impl, need to have ISerializable, but not necessarily both.

**Comment by CIPop** [comment]
>> HttpWebRequest is not marked as Serializable

> I'm not sure what you're diffing here. I believe least one of the partial classes in the ref, and in the impl, need to have ISerializable, but not necessarily both.

@danmosemsft I'm diffing between netstandard/ref and corefx/**ref. I'm seeing that within the /ref folder, HttpWebRequest is not marked as ISerializable:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Requests/ref/System.Net.Requests.cs#L126

At the same time, I see FileWebRequest is ISerializable within the ref:  
https://github.com/dotnet/corefx/blob/master/src/System.Net.Requests/ref/System.Net.Requests.cs#L36

**Comment by danmosemsft** [comment]
ISerializable needs to be in the ref so compiler sees it.

**Comment by CIPop** [comment]
```
-    public partial class HttpWebResponse : System.Net.WebResponse
 +    public partial class HttpWebResponse : System.Net.WebResponse, System.Runtime.Serialization.ISerializable
```

**Comment by CIPop** [comment]
`HttpWebResponse` has a public ctor (no ObsoleteAttribute) in CoreFX which was obsoleted in NetFX and is not part of netstandard:

```
+    public partial class HttpWebResponse : System.Net.WebResponse, System.Runtime.Serialization.ISerializable
      {
 -        public HttpWebResponse() { }
```

**Comment by stephentoub** [comment]
> -    public partial class HttpWebResponse : System.Net.WebResponse
> +    public partial class HttpWebResponse : System.Net.WebResponse, System.Runtime.Serialization.ISerializable

It's probably good to fix to make things consistent, but technically I don't think it's actually required, since WebResponse itself implements ISerializable

**Comment by CIPop** [comment]
Sockets defines two overrides in the ref (not part of netstandard):
```
-        public override System.Threading.Tasks.Task<int> ReadAsync(byte[] buffer, int offset, int size, System.Threading.CancellationToken cancellationToken) { throw null; }
-        public override System.Threading.Tasks.Task WriteAsync(byte[] buffer, int offset, int size, System.Threading.CancellationToken cancellationToken) { throw null; }
```

**Comment by CIPop** [comment]
WebClient:

Nit: Internal ctors have arguments:
```
-        internal DownloadDataCompletedEventArgs(byte[] result, System.Exception exception, bool cancelled, object userToken) : base(exception, cancelled, userToken) { }
 +        internal DownloadDataCompletedEventArgs() : base(null, false, null) { }

(...)
```

Extra obsolete APIs not present anymore in netstandard:

```
-        [System.Obsolete("This API supports the .NET Framework infrastructure and is not intended to be used directly from your code.", true)]
 -        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
 -        public bool AllowReadStreamBuffering { get { throw null; } set { } }
 -        [System.Obsolete("This API supports the .NET Framework infrastructure and is not intended to be used directly from your code.", true)]
 -        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
 -        public bool AllowWriteStreamBuffering { get { throw null; } set { } }
-        [System.Obsolete("This API supports the .NET Framework infrastructure and is not intended to be used directly from your code.", true)]
 -        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
 -        public event System.Net.WriteStreamClosedEventHandler WriteStreamClosed { add { } remove { } }
-        [System.Obsolete("This API supports the .NET Framework infrastructure and is not intended to be used directly from your code.", true)]
 -        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
 -        protected virtual void OnWriteStreamClosed(System.Net.WriteStreamClosedEventArgs e) { }
-    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
 -    public class WriteStreamClosedEventArgs : System.EventArgs
 -    {
 -        [System.Obsolete("This API supports the .NET Framework infrastructure and is not intended to be used directly from your code.", true)]
 -        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
 -        public WriteStreamClosedEventArgs() { }
 -        [System.Obsolete("This API supports the .NET Framework infrastructure and is not intended to be used directly from your code.", true)]
 -        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
 -        public System.Exception Error { get { throw null; } }
 -    }
 -    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
 -    public delegate void WriteStreamClosedEventHandler(object sender, System.Net.WriteStreamClosedEventArgs e);
```

**Comment by CIPop** [comment]
WebHeaderCollection implements IEnumerable only in CoreFX:

```
-    public partial class WebHeaderCollection : System.Collections.Specialized.NameValueCollection,
 -                                               System.Collections.IEnumerable, System.Runtime.Serialization.ISerializable
 +    public partial class WebHeaderCollection : System.Collections.Specialized.NameValueCollection, System.Runtime.Serialization.ISerializable
```

**Comment by CIPop** [comment]
@weshaggard @danmosemsft @karelz 
/cc @terrajobst @ericstj @davidsh 

I've added all the results of my diff between netstandard/ref and corefx/**/ref. I've checked that we have tracking issues for all remaining differences.
PTAL. After we take a decision on each of the issues and a change is necessary, please update the description of this issue.

**Comment by karelz** [comment]
@danmosemsft can you please help us identify which items are meaningful and should be followed up on?

**Comment by weshaggard** [comment]
This is a pretty long thread with multiple issues (I helped answer a number of related questions for @danmosemsft offline), let me know if you guys need any further clarification from me.

**Comment by danmosemsft** [comment]
@CIPop @karelz I've gone through every comment above and either noted why it's okay or opened an issue. The list at the top is updated. I'm now going to close this issue as it's not necessary any more.

**Comment by karelz** [comment]
Thanks @danmosemsft!
