### ISSUE TITLE
[System.Linq] Small optimization for RepeatIterator<>::ToArray

### ISSUE THREAD

**Issue by ViIvanov** [dotnet/corefx#13388]
Hello!

Now RepeatIterator<>::ToArray implemented as (https://github.com/dotnet/corefx/blob/8a99c59d8599179694497a00fc636e37c6da72dd/src/System.Linq/src/System/Linq/Repeat.cs#L67):
```cs
            public TResult[] ToArray()
            {
                TResult[] array = new TResult[_count];
                if (_current != null)
                {
                    for (int i = 0; i != array.Length; ++i)
                    {
                        array[i] = _current;
                    }
                }

                return array;
            }
```
`_current` is field from base type Iterator<> and has a type TResult.

Looks like we can compare it with `default(TResult)` instead of `null` here:
```cs
                TResult[] array = new TResult[_count];
                if (_current != null)
                {…
```
because we do not need fill an array with default values.

**Comment by JonHanna** [comment]
That would be nice but unless we had `where TResult : class` (which we wouldn't want), we'll get CS0019 on the equality comparison not being allowed. Having `_current != null` cover the case where the value is both a reference type and null is the best we can do in skipping the loop.

**Comment by JonHanna** [comment]
(Incidentally, it's worth noting that the jitter skips the code for the always-false test with value types, so at least it's not adding a pointless check.)

**Comment by ViIvanov** [comment]
@JonHanna Thanks, sorry, I forgotten about this limitation: we can not use ` != default(TResult)` when `TResult` is generic type without constraints.

**Comment by JonHanna** [comment]
I think the meaning of `! =` and `==` being different in relation to generic parameters catches everyone out sometimes.
