### ISSUE TITLE
CentOS PR legs failing with buildtools restore error

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#13395]
```
Restoring BuildTools version 1.0.27-prerelease-01002-04...
Failed to create prime the NuGet cache. restore failed with: 1
ERROR: Could not restore build tools correctly. See '/mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/init-tools.log' for more details.1
Initializing BuildTools...
/mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/init-tools.sh: line 148: /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/packages/Microsoft.DotNet.BuildTools/1.0.27-prerelease-01002-04/lib/init-tools.sh: No such file or directory
```
cc: @mmitche, @weshaggard, any ideas what's going on?  These same to be failing consistently across all PRs in corefx for the last few hours.

**Comment by weshaggard** [comment]
No idea. Do we have the sync.log from any machine that ran this? I don't know what the error "Failed to create prime the NuGet cache. restore failed with: 1" means. @ericstj  have you seen the CLI fail to initialize its cache?

**Comment by ericstj** [comment]
I have seen this before, @livarcocc may know more about it.

I would recommend we just set DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true to avoid this step altogether.

**Comment by mmitche** [comment]
This is happening because the dotnet-bot account is getting deleted (replaced with dotnet-bot2) and it's orphaning files in /tmp, which the build process is unable to overwrite.

**Comment by ericstj** [comment]
@mmitche is the fix here just to delete the machines that are failing?

**Comment by mmitche** [comment]
@ericstj Yeah, just need to fix the startup logic again

**Comment by stephentoub** [comment]
> Yeah, just need to fix the startup logic again

@mmitche, did this get updated?  Wondering if the legs can be re-enabled and this can be closed.

**Comment by mmitche** [comment]
@stephentoub Reverted.  SHould be good now.
