### ISSUE TITLE
Linux ARM Emulator SoftFP builds are failing frequently

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#13394]
This is causing lots of PRs to have failed legs.
```
./scripts/arm32_ci_script.sh: line 170: /opt/linux-arm-emulator-root/dotnet/setenv/setenv_incpath.sh: No such file or directory
```

**Comment by danmosemsft** [comment]
@wateret @sjsinju you changed arm32_ci_script.sh last -- that doesn't mean you have anything to do with this failure, but you're already more familiar with this than I am. Do you have any insight into this issue?
@mmitche

**Comment by wateret** [comment]
@danmosemsft I checked it and it turns out HardFP and SoftFP use the same directory for mounting their rootfs. That's why it crashes sometimes. I will fix shortly.

**Comment by stephentoub** [comment]
Reopening... after #13461, the legs are still failing, they're just failing with a different error:
```
+ mount_emulator
+ '[' '!' -d /opt/linux-arm-emulator-root/arm-softfp ']'
+ sudo mkdir -p /opt/linux-arm-emulator-root/arm-softfp
+ set +x
+ sudo mount /opt/linux-arm-emulator/platform/rootfs-t30.ext4 /opt/linux-arm-emulator-root/arm-softfp
mount: according to mtab /opt/linux-arm-emulator/platform/rootfs-t30.ext4 is already mounted on /opt/linux-arm-emulator-root/arm-softfp as loop
The script is exited. Cleaning environment..
```

**Comment by wtgodbe** [comment]
Looks like these are much more reliable now, closing.
