### ISSUE TITLE
[Question] Trying out the new corefx

### ISSUE THREAD

**Issue by Luo-Liang** [dotnet/corefx#13409]
Hi I'm running to an error trying out the new corefx in my project. I am especially interested in the FirstChanceException under System.AppDomain class

I first followed instruction for building the new CoreCLR: https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/UsingYourBuild.md

I then downloaded and compile CoreFX.

I then set my .nugget config to add the following two keys:

    <add key="Local Core CLR" value ="C:\Users\liangluo\Downloads\coreclr\bin\Product\Windows_NT.x64.Debug\.nuget\pkg"/>
    <add key="Local Core FX" value="C:\Users\liangluo\Downloads\corefx\bin\packages\Release"/>

Now I have the following short project.json
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.Runtime.CoreCLR": "1.2.0-beta-24702-0"
      }
    }
  },
  "runtimes": {
    "win10-x64": {}
  },
  "dependencies": {
    "System.Runtime.Extensions": "4.4.0-beta-24702-01"
  }
}
```
Now when I restore the package and run the program it says:

    Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040 (FUSION_E_REF_DEF_MISMATCH))

I do not know why it's searching for the 4.2.0.0 version of assembly. I felt like I'm making obvious mistakes, but I cannot find any tutorial that tells me how to. Please kindly correct me or point me to how to fix it, or let me know if there is an easier way for me to use the FirstChanceException handler in System.AppDomain.

Thanks a lot!

**Comment by karelz** [comment]
@weshaggard @ericstj can you please help route the question?

**Comment by ericstj** [comment]
This is happening because the latest CoreFx packages depend on a newer NuGet that is being used.   What version of NuGet/DotNET-CLI are you using to restore the project file?

**Comment by karelz** [comment]
@ericstj what kind of error patterns should I expect in such cases? Any bogus-looking Fusion-style FileLoadException on CoreFX DLLs?

**Comment by ericstj** [comment]
Yeah, that's a good indicator.  Usually that means one library got the latest impl but another didn't.  In this case it would happen because S.R.E has a netcoreapp1.1-specific assembly that compiles against S.R which has a netstandard1.7 specific assembly.  If you restore with an old NuGet that doesn't know netstandard1.7 is compatible with netcoreapp1.1 you'd get this error.

**Comment by Luo-Liang** [comment]
Hey! Thanks for responding. I think I'm using the default NuGet/DotNET-CLI because I didn't do anything to CLI afaik. Can I update my CLI using NUGET? or Do I need to grab the source code and compile myself as well?

Thanks!

**Comment by weshaggard** [comment]
You can get the latest CLI versions from the CLI builds at https://github.com/dotnet/cli, see the links there.

**Comment by kierenj** [comment]
@ericstj Thanks for your comment re netstandard1.7 above.  I don't want to hijack, but I'm having real troubles here. Could I just confirm - I'm on nightlies for EF Core - if that has dependencies which have bene switched to netstandard1.7, that would mean a very recent version of the SDK would be needed to build?  Newer than `1.0.0-preview4-004233`, which is the latest on Azure App Services?

**Comment by weshaggard** [comment]
Directions on consuming our latest bits can be found at https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md.
