### ISSUE TITLE
Error CS0246 referencing System.StackOverflowException and dotnet.exe crashes without an exception being caught

### ISSUE THREAD

**Issue by ericwj** [dotnet/corefx#13407]
What should I do to reference `System.StackOverFlowException`?

I have use to catch `StackOverflowException`, since I am writing code that would rely on the compiler doing tail call optimization. However, trying to catch `System.StackOverFlowException`, I am presented with `CS0246`. I tried to explicitly include some packages, but that was probably futile in concept, since the class should be part of the `Microsoft.NETCore.App` dependency I am using (v1.0.1).

I'm sure it's possible as I'm seeing it being referenced in [corefx/src/System.Runtime/tests/System/StackOverflowExceptionTests.cs](https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Runtime/tests/System/StackOverflowExceptionTests.cs). However, that repo is notoriously difficult to dissect - the test project for example doesn't have a project.json...

Yet, there is another issue, being that even if I write a simple test using Xunit and use this line:
```csharp
Assert.ThrowsAny<Exception>(() => TailCall());
```
Whatson will kick in reporting that 

> dotnet has stopped working

and obviously, that is very unfortunate and useless.

Reproduce by running:
```bat
mkdir dotnetnew
code dotnetnew
```

Paste
```csharp
using System;

namespace ConsoleApplication
{
    public class Program
    {
        public static int TailCall(int i) {
            if (i == int.MaxValue) return i;
            i++;
            return TailCall(i);
        }
        public static void Main(string[] args)
        {
            try {
                Console.WriteLine(TailCall(0));
            } catch (Exception ex) {
                Console.WriteLine($"{ex.GetType().Name}");
            }
        }
    }
}
```
This code works:
```
PS C:\dotnetnew> dotnet run -c Release
Project dotnetnew (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling dotnetnew for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.1238355


2147483647
```

But not always:

```
dotnet run
```

> dotnet has stopped working

Replace `Exception` with `StackOverflowException`.
```
dotnet build
```

**\dotnetnew\Program.cs(11,27): error CS0246: The type or namespace name 'StackOverFlowException' could not be found (are you missing a using directive or an assembly reference?)**

**Comment by karelz** [comment]
You seem to have bad casing in StackOverflowException in your error message. Could that be the reason?
The tests seem to be able to reference it just fine.

**Comment by ericwj** [comment]
Except I didn't type it in the first place - I only did when Ctrl+Space wouldn't find anything.
![StackOverflowException](https://gfu6gw-sn3302.files.1drv.com/y3pkIfRKL_uHZpqgOxSC6M_SJUr2qv6UnnhJaPJvHxxCWAQ1k5BszMPR1-jFpNZBndA-g11NnWKoTucyjQjxiFzmda2yI9lWuUE_x1rUXqvXsOi9T6dLvknezBfZyfh5-mjigFy9xtwai3orfuQ1jUq5w/StackOverflowException.png?psid=1)

**Comment by karelz** [comment]
The type does not exist in .NET Core 1.0 nor 1.1 (about to be released). It will be part of our next release - 1.2 (currently scheduled for Spring 2017 - see [milestones](https://github.com/dotnet/corefx/milestones)).
The type was added into our dev/api branch in PR #10699.

**Comment by ericwj** [comment]
Oké then I can stop looking ;) Thanks!

**Comment by masums** [comment]
Is there have any way to detect  System.StackOverflowException ( Which code segments are causing that? ) and prevent app crash at DotNet Core 2.0 or above?

**Comment by karelz** [comment]
Let's not highjack old bugs for related questions. If you need to debug it, get a dump and analyze the callstack - it will tell you more.
There's also general info on the topic: https://stackoverflow.com/questions/1599219/c-sharp-catch-a-stack-overflow-exception
