### ISSUE TITLE
Tuple.IStructuralComparable/Equatable throws NRE

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#13410]
The following tests demonstrates this.
```
[Fact]
public void IStructuralEquatable_Equals_NullEqualityComparer_ThrowsNullReferenceException()
{
    IStructuralEquatable structuralEquatable = Tuple.Create(1);
    Assert.Throws<NullReferenceException>(() => structuralEquatable.Equals(Tuple.Create(1), null));
}

[Fact]
public void IStructuralEquatable_GetHashCode_NullEqualityComparer_ThrowsNullReferenceException()
{
    IStructuralEquatable structuralEquatable = Tuple.Create(1);
    Assert.Throws<NullReferenceException>(() => structuralEquatable.GetHashCode(null));
}

[Fact]
public void IStructuralComparable_CompareTo_NullEqualityComparer_ThrowsNullReferenceException()
{
    IStructuralComparable structuralComparable = Tuple.Create(1);
    Assert.Throws<NullReferenceException>(() => structuralComparable.CompareTo(Tuple.Create(1), null));
}
```

I can send in a PR fixing this to throw ArgumentNullException, but there might be breaking change so I'll let you guys approve it before I go wasting my time ;)

**Comment by karelz** [comment]
What's the value of changing NullRefEx to ArgNullEx? Is it "just" cleanliness/purity or is there more to it?

If it is just cleanliness, I would prefer consistency with other platforms (Full .NET Framework, Xamarin) over it. Is the same NullRefEx behavior observed on full .NET and Xamarin?

cc: @stephentoub @weshaggard @terrajobst, any compat guidance here?

**Comment by hughbe** [comment]
Should've mentioned - Netfx also throws an NRE, hence my apprehension. 

In general, NREs are bad (according to the Microsoft api design guidelines) as the error message is unclear and people expect ANEs, and get confused if an NRE is thrown.

That said, there are compat issues here, so I wanted to bring up a discussion

**Comment by karelz** [comment]
Thanks for confirmation. Any idea what Xamarin does?

**Comment by hughbe** [comment]
Same behaviour as fx and core according to the mono source code

**Comment by terrajobst** [comment]
I agree with @hughbe, NREs are bad if non-user code is top of the call stack as this is indicative of a bug in the implementation of said method. ANE indicates that the top of the call stack refuses to accept the supplied arguments. In very narrow circumstances we've allowed this behavior (usually for performance critical code where any checking was deemed unacceptable).

That being said, if that's the behavior .NET Framework has, we need to preserve it for compat. We could quirk it, but the value gain seems low. Diverging in .NET Code would be possible, but I agree with @karelz -- consistency trumps cleanliness on a one side only.

**Comment by hughbe** [comment]
As I thought - its worth documenting this (at least via some tests), so I'll submit them and close this issue

**Comment by hughbe** [comment]
Also, NREs are thrown for Array and ValueTuple too. I know Array is locked down due to compat, but is it the same with ValueTuple, considering its a c# 7 feature which hasn't been released yet

**Comment by karelz** [comment]
Let's spin off a new bug to track ValueType. We may still have a chance to fix it there.

Adding the tests sounds like a good idea (with comment "compat" with Full Framework/Mono)

**Comment by hughbe** [comment]
Also - ImmutableArray **also** throws NRE for a null comparer!

I'm not proposing a behaviour change, but documenting it here for the tests I'm about to push

**Comment by terrajobst** [comment]
@hughbe 

> Also - `ImmutableArray` **also** throws NRE for a null comparer!

That's the example I had in mind when I wrote earlier

> In very narrow circumstances we've allowed this behavior (usually for performance critical code where any checking was deemed unacceptable).

**Comment by hughbe** [comment]
@terrajobst 

> In very narrow circumstances we've allowed this behavior (usually for performance critical code where any checking was deemed unacceptable).

Seems like if you need to go against API design practices, even for perf, you're doing things wrong, but I understand that in the real world compromises do have to be made!

**Comment by hughbe** [comment]
Is this worth revisiting in the new precedent of fixing NREs to ANEs? Also I don't think this is performance critical right?
