### ISSUE TITLE
WorkingSet size in Linux

### ISSUE THREAD

**Issue by ayende** [dotnet/corefx#13423]
Unless I miss something significant, this is a bug:

https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessManager.Linux.cs#L120

rss is the number of _pages_, but WorkingSet is the number of _bytes_.

**Comment by stephentoub** [comment]
I believe you're correct, and this value should be multiplied by Environment.SystemPageSize.

**Comment by ayende** [comment]
Also need to check WorkingSet64 there, no?

**Comment by Priya91** [comment]
@ayende Would you like to submit the fix?
