### ISSUE TITLE
OpenCover won't cover C# source code

### ISSUE THREAD

**Issue by AdamOrHd123** [dotnet/corefx#13421]
Hi,
I have a problem where C# code is not being covered.
In contrast, C++ code is being covered.
In the output file there are a lot of tags indicating with an attribute of skippedDueTo="MissingPdb"
The command-line I use is as follows:
C:\Projects\opencover.4.5.3207>OpenCover.Console.exe -target:"C:\Projects\Accura
cy_With_Pdb\Accuracy\Accuracy.exe" -targetdir:"C:\Projects\Accuracy_With_Pdb\Acc
uracy" -output:"C:\Projects\Coverity\coverage-20161106_164706\Accuracy_CodeCove
rage.xml" -register:user -targetargs:"C:\Projects\Accuracy_With_Pdb\Accuracy\Acc
uracy.pdb /noshadow"

**Comment by stephentoub** [comment]
Seems like this is actually an issue for OpenCover and should be opened instead in the OpenCover repo?
https://github.com/opencover/opencover

**Comment by AdamOrHd123** [comment]
Hi Stephen,
Thanks for the input.
I placed a new issue at https://github.com/OpenCover/opencover/issues/637

Regards.

**Comment by stephentoub** [comment]
Thanks.
