### ISSUE TITLE
Committing certain data results in infinite loop inside System.Data.SqlClient.TdsParserStateObject.cs

### ISSUE THREAD

**Issue by brandonagr** [dotnet/corefx#13439]
I am running a service that is migrating terabytes of data (rows consist of a few uniqueidentifier columns and a varbinary column), I have run into a situation where System.Data.SqlClient will enter into an infinite loop on certain datasets (cpu spinning, making no progress, always at the same point in dataset, reproducible on multiple machines)

After stepping through the .net source I believe the cause of the infinite loop is TdsParserStateObject.WritePacket returning null because the first bytes that are in the byte[] _outBuff happen to exactly equal 7,992 when BitConverter.ToInt32(_outBuff, _outputHeaderLen) is called. 

https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/TdsParserStateObject.cs#L3248

![writepacket_randomdatamatchingconditional](https://cloud.githubusercontent.com/assets/338022/20076695/0d20a4c4-a4ff-11e6-8807-a977f9915f8b.png)

WritePacket returning null and doing nothing causes the do while loop in TdsParserStateObject.WriteByteArray to spin forever, as it will get into state of _outBuff.Length == _outBytesUsed, so remainder is 0, since len -= remainder; is the update to the loop condition variable, it will spin forever in this loop.

**Comment by brandonagr** [comment]
Looking more closely at _outBuff, the first 8 bytes are part of a header, when I hit this bug the buffer equals to

_outBuff[0]
3
_outBuff[1]
4
_outBuff[2]
31
_outBuff[3]
64
_outBuff[4]
0
_outBuff[5]
0
_outBuff[6]
0
_outBuff[7]
0

_outBuff[0] = _outputMessageType;         // Message Type
_outBuff[1] = status;
_outBuff[2] = (byte)(_outBytesUsed >> 8); // length - upper byte
_outBuff[3] = (byte)(_outBytesUsed&0xff); // length - lower byte
_outBuff[4] = 0;                          // channel
_outBuff[5] = 0;
_outBuff[6] = packetNumber;               // packet
_outBuff[7] = 0;                          // window

_outputMessageType is TdsEnums.MT_RPC = 3;    // Remote procedure call
status is from TdsEnums.ST_BATCH;
[2] and [3] set from 8000 = 7936 + 64

So it's any time a packet that is part of a batch and calling a stored procedure and the previous packet call was 8000 bytes in size, it will hit this bug

**Comment by saurabh500** [comment]
@brandonagr What OS are you using for your client? Windows or Ubuntu ?

**Comment by saurabh500** [comment]
cc @corivera

**Comment by brandonagr** [comment]
Windows 8.1 Enterprise, .NET Framework 4.6.1

**Comment by saurabh500** [comment]
@brandonagr Thanks for reporting the issue and we will look into it. 
If the app is running on .Net 4.6.1, the fix will be delivered with the net framework update. 

It won't be available via .Net Core runtime. 

Also is there a way to get a standalone repro for this issue?

**Comment by brandonagr** [comment]
I'm working on creating a small repro, currently it happens in the middle of committing a multi gigabyte set of data (user defined table type being passed as table value parameter to sproc) on row 6,754,534

**Comment by saurabh500** [comment]
@brandonagr Thank you. We will continue to look into this as well.

**Comment by brandonagr** [comment]
Created an easy to reproduce example here: https://github.com/brandonagr/InfiniteLoopInSystemDataRepro

Shows that it is the bytes 56, 31, 0, 0 appearing in _outBuff 8-11 after the packet overflows from 255 to 0 that causes the issue.

**Comment by saurabh500** [comment]
@brandonagr Thanks

I acknowledge the repro. I can reproduce the issue on both .Net Framework and .Net core.

**Comment by saurabh500** [comment]
We need to investigate this further. Moving this to future.

**Comment by Wraith2** [comment]
I have a fix for this but i'm not sure how to structure the test. I need to be able to start a thread which I know is going to hit an infinite loop I can't cancel out of. I can't Thread.Abort on core, any ideas?
