### ISSUE TITLE
Add Windows 32 bit to test build

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#13448]
We are currently not testing 32 bit. (Which we support on Windows)

We need to enable this for the test build. Separately we should enable it for CI -- @mmitche what is involved to do that, once the test build is going?

/cc @karelz @weshaggard

**Comment by mmitche** [comment]
This is an explicit 32-bit targeting build, host, or otherwise?

**Comment by danmosemsft** [comment]
@mmitche if you mean should the OS be 32 bit, I don't think that's necessary.

**Comment by mmitche** [comment]
Right that's what I figured.  I assumed it was 32-bit targeted MSIL?
Anyways, once you get the right commands in the build scripts then you can just alter the netci job definition to add the builds.
