### ISSUE TITLE
Remove PlatformNotSupportedException from NetCore50 System.Console Color properties

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#13457]
This pull request: https://github.com/dotnet/corefx/pull/12984 regressed behavior for setting console color on netcore50 versions of System.Console.  These properties now throw a System.PlatformNotSupportedException.  

There is no desire to work around this in Xunit.Console.NetCore so netcore50 tests are broken for this reason until this is fixed.  It's quite possible for code one is indirectly calling (and may not have control over) to call these APIs, and without being allowed to call these without crashing some code may be unusable.

@weshaggard  @SedarG

**Comment by karelz** [comment]
@ianhays can you please take a look at the regression?

**Comment by ianhays** [comment]
This is resolved by https://github.com/dotnet/corefx/pull/13758
