### ISSUE TITLE
System.Data.SqlClient.SqlBuffer.get_Int32() cannot read from "tinyint" column

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/corefx#13469]
Because of boxing here's what happens when you have a `tinyint` column and attempt to map it to `Int32` member:
1. `SqlBuffer.get_Int32()` is called
2. `SqlBuffer.get_Int32()` sees that "storage type" is not `StorageType.Int32`, so it calls `get_Value()`
3. `get_Value()` checks "storage type" again and calls `get_Byte()`
4. `get_Byte()` returns a value of type `Byte`
5.  control gets back to `get_Value()` and it returns `Byte` boxed as `Object`
6.  control gets back to `get_Int32()` and it casts `Object` which contains a boxed `Byte` into `Int32` and the cast fails with `InvalidCastException`.

Which basically means that you cannot read a narrow range int type column into a wider range type datatype. It makes no sense.

I guess I can fix this - just enum all "smaller" types in each `get_SomeIntegerType()` and retrieve proper data. Would such fix be desired?

**Comment by saurabh500** [comment]
@Dmitry-Me Do you have a repro for this?

**Comment by Dmitry-Me** [comment]
@saurabh500 Yes, here's a short piece of code:

      Byte byteVal = 10; // this is what get_Byte() reads
      object byteValObj = byteVal; // this is how get_Value() boxes the value
      Int32 intVal = (Int32)byteValObj; // this is how to_Int32() fails to cast

**Comment by saurabh500** [comment]
@Dmitry-Me The SqlClient API which can cause the `InvalidCastException` to throw for the use case you have defined is `SqlDataReader.GetInt32` 
https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqldatareader.getint32(v=vs.110).aspx

The documentation states that the exception is expected if `The specified cast is not valid.` 

Let me know if you have any other use case which can  cause this exception to throw.

**Comment by Dmitry-Me** [comment]
@saurabh500 Yes, it does what the documentation says but it still makes no sense.

Also the code is written as if the conversion was intended but is underimplemented. Code that intended to only allow specific types would do something like this:

    if( storageType == expectedType )
        return storedData.appropriateMember;
    throw new InvalidCastException();

but instead of explicitly throwing an exception it calls `get_Value()` and then casts and this just complicates the codebase

    if( storageType == expectedType )
        return storedData.appropriateMember;
    return (Int32)Value;
