### ISSUE TITLE
.NET Core always create files with execute permission on Linux

### ISSUE THREAD

**Issue by xplicit** [dotnet/corefx#13465]
OS: Ubuntu 16.04
.NET Core version: 1.0.0-preview2-1-003155

Steps to reproduce:
type  `dotnet new` then add following text into `Program.cs`

```csharp
using System;
using System.IO;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
	    File.WriteAllText("test.txt", "123123");
        }
    }
}
```

then type `dotnet restore && dotnet run && ls -al`

You will see that all files: `Program.cs`, `project.json`, `project.lock.json` and `test.txt` have got executable bit, which should not be there.

**Comment by stephentoub** [comment]
This is a dup of https://github.com/dotnet/corefx/issues/13342.  The behavior was changed with https://github.com/dotnet/coreclr/pull/7995.
