### ISSUE TITLE
Modify webproxy tests to handle platform specific difference.

### ISSUE THREAD

**Issue by parjong** [dotnet/corefx#13464]
In Ubuntu 14.04 (x86_64), ``System.Net.WebProxy.Tests`` inner test failed as follows:
```
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.
Discovering: System.Net.WebProxy.Tests
Discovered:  System.Net.WebProxy.Tests
Starting:    System.Net.WebProxy.Tests
   System.Net.Tests.WebProxyTest.BypassOnLocal_MatchesExpected(destination: http://127.0.0.1/, isLocal: True) [FAIL]
      Assert.False() Failure
      Expected: False
      Actual:   True
      Stack Trace:
         /home/parjong/projects/dotnet/corefx/src/System.Net.WebProxy/tests/WebProxyTest.cs(184,0): at System.Net.Tests.WebProxyTest.BypassOnLocal_MatchesExpected(Uri destination, Boolean isLocal)
Finished:    System.Net.WebProxy.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.WebProxy.Tests  Total: 25, Errors: 0, Failed: 1, Skipped: 0, Time: 4.050s
```

**Comment by parjong** [comment]
I found the followings while digging this issue:
 - ``(new Uri(http://127.0.0.1)).IsLoopback`` returns true.
 - The current implementation of ``IsBypassed`` always returns true if the given uri is loopback:
```
        public bool IsBypassed(Uri host)
        {
            if (host == null)
            {
                throw new ArgumentNullException(nameof(host));
            }

            return
                Address == null ||
                host.IsLoopback ||
                (BypassProxyOnLocal && IsLocal(host)) ||
                IsMatchInBypassList(host);
        }
```
Either method ``IsBypassed`` or ``BypassOnLocal_MatchesExpected`` seems to be wrong, but unfortunately I couldn't find any specification.  @dotnet/corefx-contrib Could you let me know which one is correct?

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by CIPop** [comment]
+1 Repro on both Ubuntu 16.04.1 LTS and 14.04.

**Comment by stephentoub** [comment]
It's interesting that it's apparently passing in CI

**Comment by CIPop** [comment]
@stephentoub The test has a hard dependency on the machine configuration / Ubuntu and seems to be a bit different from the .Net Desktop test. There are three issues leading to the problem:

* Machine/OS specific: Ubuntu has an `/etc/hosts` entry associating `127.0.1.1` with the machine hostname.

This article explains the config a bit: http://askubuntu.com/questions/754213/what-is-difference-between-localhost-address-127-0-0-1-and-127-0-1-1
>For a system with a permanent IP address, that permanent IP address should be used here instead of 127.0.1.1.
>
>127.0.1.1 host_name

Some devs will hit this as their machines are going to be configured with DHCP. Most likely the CI boxes have fixed IP addresses, missing this entry.

* #13301 - The test is written differently from .Net Desktop where we're doing
```C#
IPAddress[] addresses = Dns.GetHostAddresses(String.Empty);
```

I've tried this on Windows and it works, never returning a hosts entry. (I've added one similar  to Ubuntu.)
Trying this on Ubuntu will throw the error in #13301.

* There is a behavior difference (probably a bug) in how `GetHostEntryAsync` works:

```
            foreach (IPAddress address in Dns.GetHostEntryAsync(Dns.GetHostName()).GetAwaiter().GetResult().AddressList)
            {
                Console.WriteLine(address);
            }
```
will never return `hosts` entries on Windows. 
It has an odd behavior on Ubuntu: if the hosts entry exists, it returns that single entry (127.0.1.1). If the hosts entry doesn't exist, it will return the IP obtained via DHCP, on eth0.

Note for others hitting the issue: commenting out the following line will make the test pass:
in `/etc/hosts`
```
127.0.0.1       localhost
#127.0.1.1       myhost1               <------

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by Priya91** [comment]
Given that gethostentryasync depends on native os apis getaddrinfo, gethostbyname and .NET just wraps those results. I don't think there's a bug in .NET to be fixed here, given the inherent platform differences. Closing the issue, please reopen if you think .NET should behave differently than OS apis.

**Comment by stephentoub** [comment]
I think the test needs to be fixed.

**Comment by Priya91** [comment]
Next steps: Rewrite test to handle the difference.

**Comment by krwq** [comment]
I've just seen this exact failure locally

**Comment by seanshpark** [comment]
I've added some message to
`public static void BypassOnLocal_MatchesExpected(Uri destination, bool isLocal)`
like
```
+            Console.WriteLine(">>> destination AbsolutePath {0}", destination.AbsolutePath);
+            Console.WriteLine(">>> destination AbsoluteUri {0}", destination.AbsoluteUri);
+            Console.WriteLine(">>> destination Authority {0}", destination.Authority);
             Assert.False(new WebProxy(proxyUri, false).IsBypassed(destination));
```
and got fail with 255.255.255.255
```
>>> destination AbsolutePath /
>>> destination AbsoluteUri http://nodotinhostname/
>>> destination Authority nodotinhostname
>>> destination AbsolutePath /
>>> destination AbsoluteUri http://9f2c5bd9b1334788a4d5a36013f80022/
>>> destination Authority 9f2c5bd9b1334788a4d5a36013f80022
>>> destination AbsolutePath /
>>> destination AbsoluteUri http://127.0.0.1/
>>> destination Authority 127.0.0.1
>>> destination AbsolutePath /
>>> destination AbsoluteUri http://6dec3fe10421452e98aced50690bf858.com/
>>> destination Authority 6dec3fe10421452e98aced50690bf858.com
>>> destination AbsolutePath /
>>> destination AbsoluteUri http://255.255.255.255/
>>> destination Authority 255.255.255.255
   System.Net.Tests.WebProxyTest.BypassOnLocal_MatchesExpected(destination: http://127.0.0.1/, isLocal: True) [FAIL]
      Assert.False() Failure
      Expected: False
      Actual:   True
      Stack Trace:
            at System.Net.Tests.WebProxyTest.BypassOnLocal_MatchesExpected(Uri destination, Boolean isLocal)
Finished:    System.Net.WebProxy.Tests
```

Anyone know about this?

**Comment by seanshpark** [comment]
> Next steps: Rewrite test to handle the difference.

@Priya91, can you please share your status or rewrite plan?

**Comment by seanshpark** [comment]
I'v found what's related with this failure. 
```
   System.Net.Tests.WebProxyTest.BypassOnLocal_MatchesExpected(destination: http://127.0.0.1/, isLocal: True) [FAIL]
      Assert.False() Failure
      Expected: False
      Actual:   True
```
1) need host name in `/etc/hostname` file (most have this), for example if it's `mylinuxbox`
   ```
    mylinuxbox
   ```
2) need localhost and host name with IP in `/etc/hosts` file
   ```
   127.0.0.1 localhost.localdomain localhost
   192.168.0.2 mylinuxbox
   ```
my device didn't have `192.168.0.2 mylinuxbox` line.

**Comment by karelz** [comment]
Triage: Would be nice to have the tests more resilient, but it does not seem anyone is motivated to make it happen. CI passes.
If we see spike in future, we can reconsider.
