### ISSUE TITLE
Support for ICustomMarshaler

### ISSUE THREAD

**Issue by Kukkimonsuta** [dotnet/corefx#1346]
Split from #1333 

Recorded uses in (3rd party) libraries:
- [LibGit2Sharp](https://github.com/libgit2/libgit2sharp/search?utf8=%E2%9C%93&q=ICustomMarshaler&type=Code)
- Mono.Posix see #94

**Comment by cwensley** [comment]
I'd also like to see this done to implement a CoreCLR version of MonoMac (;

**Comment by jasonwilliams200OK** [comment]
Isn't `ICustomMarshaler` already available since Jan 2015 via https://github.com/dotnet/coreclr/blob/4cf8a6b/src/mscorlib/src/System/Runtime/InteropServices/ICustomMarshaler.cs?

**Comment by cwensley** [comment]
@jasonwilliams200OK, yes but it's not public: https://github.com/dotnet/coreclr/blob/4cf8a6b082d9bb1789facd996d8265d3908757b2/src/mscorlib/model.xml#L10158

**Comment by jasonwilliams200OK** [comment]
Oh you are right. So should this issue be moved to CoreCLR repo, where it stands better chance to attract some reception? :smile:

**Comment by weshaggard** [comment]
cc @yizhang82

**Comment by joshfree** [comment]
@yizhang82 @jkotas

**Comment by cwensley** [comment]
I see that the ICustomMarshaler has issues with compatibility based on the comments in PR dotnet/coreclr#1768 , though I'm not sure why..  

Is there going to be any sort of replacement or alternate way to go about doing custom marshalling?  Without this, MonoMac bindings would be pretty much unusable as all bound api's would require IntPtr's instead of allowing for wrapped objects.

**Comment by benpye** [comment]
I would like to echo my desire for this feature. This causes significant issues especially when you have delegates being called with custom types. Whilst most methods can be wrapped, a delegate called causes a significant issue. It is possible to wrap these too but it's a lot of work. I have hit this issue more commonly when dealing with UTF8 strings on Windows, traditionally a custom marshaller has been used, and works quite transparently. The lack of this feature makes this far more work to implement. 

An example where this has been a problem: https://github.com/flibitijibibo/SDL2-CS/pull/93

**Comment by danmosemsft** [comment]
@yizhang82 I see this present in .NET Core now. Is there further work here?

**Comment by yizhang82** [comment]
Thanks @danmosemsft It's support in .NET Core now. I'm closing this one.
