### ISSUE TITLE
Support for binary serialization

### ISSUE THREAD

**Issue by Kukkimonsuta** [dotnet/corefx#1347]
Split from #1333 

Turns out binary serialization is not really needed in my case as it's used only on exceptions, but it would still be nice to know whether it's coming back or whether it is depreciated.

**Comment by weshaggard** [comment]
@Kukkimonsuta There are no plans to support binary serialization in .NET Core. The serialization team is pushing more towards DataContract Serialization and other open source projects like Json.Net as the serialization technologies of choice.

**Comment by grahamehorner** [comment]
could Json.NET BSON serialization be an option? or should just allow a developer to dependency inject a serializer/formatter similar to ASP.NET 5

**Comment by joshfree** [comment]
@zhenlan can you comment please

**Comment by boades** [comment]
> it's used only on exceptions
> There are no plans to support binary serialization in .NET Core.

So it means that code like 
protected MyException(SerializationInfo info, StreamingContext context) : base(info, context) { }

can be removed as obsolete?

**Comment by zhenlan** [comment]
Hi @boades, thinking you may be interested to review issue #6564 that has latest discussion about binary serialization and exception.

**Comment by boades** [comment]
Hi @zhenlan, thanks for the link.

**Comment by danmosemsft** [comment]
This was added for 1.2
