### ISSUE TITLE
Move Path class down to CoreLib

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#13487]
For 2 main reasons: perf and stability

We already have a copy of a significant chunk of code that went in with long path support. The code in CoreLib isn't as up-to-date or complete as what we currently have in CoreFX (partially because we were trying to maintain source compatibility with desktop and partially we were only enable AppDomain bring up). This wasn't a big deal when all we had was AppDomain in play, but now that we're moving additional IO classes down we're exposing ourselves to breaks. (Either by missing fixes or missing differing behavior as the code in CoreLib uses the PAL.)

While we could just share the code a little more completely there are additional issues around caching. Normalizing paths on Windows would benefit from having a single instance of the code- particularly as the same paths tend to get normalized repeatedly in succession. Having a single buffer cache will avoid some (potentially a lot of) buffer resizing.

@ianhays, @stephentoub, @weshaggard, @jkotas

**Comment by stephentoub** [comment]
For reference, this is a profile I shared with Jeremy showing a fair amount of allocation coming from this at startup:
![image](https://cloud.githubusercontent.com/assets/2642209/20114660/21947a06-a5c3-11e6-9631-1a7e97eb407a.png)

**Comment by JeremyKuhne** [comment]
Moved
