### ISSUE TITLE
Port System.Configuration

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#13481]
Proposal is to port S.Configuration to Core (not part of .NET Standard) for use by user code -- not by the framework itself.

Note: this doesn't represent a commitment from us to port it to .NET Core -- it's simply a place for comments/discussion.

**Comment by danmosemsft** [comment]
Jeremy is investigating.

**Comment by danmosemsft** [comment]
@JeremyKuhne for folks benefit could you give a brief summary of what you have working so far, and where you expect to take this to for 2.0.

**Comment by JeremyKuhne** [comment]
The System.Configuration library is ported, with the following caveats:

- System.Security and limited trust related pieces were stripped
- Test writing is in progress

The intent is to prioritize application usage and consumption of System.Configuration. AppSettings and custom app data stored via System.Configuration. In theory most things should work (even now), but that needs to be proved out via tests (which I'm writing and checking in as fast as I can).

Feedback and real-world scenarios are always welcome and will help prioritize test writing / additional work items.

**Comment by karelz** [comment]
Are we ready to close the issue now that we have it in 2.0?

**Comment by JeremyKuhne** [comment]
Closing this one- our initial work is done. I've created a future task for improving the test coverage.
