### ISSUE TITLE
System.Configuration is missing

### ISSUE THREAD

**Issue by karldodd** [dotnet/corefx#1348]
Hi corefx team,

If I am right, classes under System.Configuration namespace are missing. I know asp.net 5 introduces some new json-based configuration mechanism but the old xml-based configurations are still widely used. Moving System.Configuraiton to corefx will benefit a lot of legacy code.

Kind regards,
Karl

**Comment by holytshirt** [comment]
Hello corefx team, is this namespace coming over, or should we be looking to implement reading from config and custom configuration sections differently?

**Comment by Eilon** [comment]
Hi folks, this is Eilon from the ASP.NET team. There are no current plans to bring the `System.Configuration` types to corefx.

The new [`Microsoft.Extensions.Configuration`](https://github.com/aspnet/Configuration/) is a great alternative way to have structured, layered, testable, DI-friendly configuration data and settings, including many built-in config sources, such as: command line args, environment variables, INI files, JSON files, XML files, and per-machine user secrets.

Though it's not intended as an exact replacement for `System.Configuration`, it does provide a lightweight, yet powerful way of reading configuration data.

The new library also includes functionality for binding configuration data to strongly-typed POCO objects.
