### ISSUE TITLE
ReleaseNotes link results in 404

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#13493]
The 1.1 release notes link points to https://go.microsoft.com/fwlink/?LinkID=799421 per https://github.com/dotnet/corefx/issues/8758#issuecomment-221048601, but that link is currently broken.

@leecow owns this link, can you please update as appropriate.

/cc @gkhanna79

**Comment by leecow** [comment]
Link target updated to https://github.com/dotnet/core/blob/master/release-notes/1.1/1.1.0-preview1.md.
