### ISSUE TITLE
Memory statistics and portable interop.

### ISSUE THREAD

**Issue by svdh2** [dotnet/corefx#13538]
Is there a way to get free memory statistics?

I am interested in getting for example free pages available to know if my app should cache more things in memory or not.

Up until now, with mono I did detect the OS info and based on that I did custom inter op for each supported system. This had the nice property that I need to release only one binary and only one tool chain to maintain.

For not the only solution I see in .NetCore's current state, is to write a custom library in C with a version for each type of supported OS and than make a custom build for each OS.

I feel this is a common problem that will be duplicated many times. And having the option to have a c# library that adapts to the os is a nice solution for simple problems as it does not require to set up a compile chain for each supported OS. So incorporating that mechanism in the CLR would be nice.

**Comment by svick** [comment]
Why can't you use the solution you use on mono also on .Net Core?

**Comment by svdh2** [comment]
Because I have no OS information to know what functions I can p/invoke.

I could try each p/invoke untill I find one that does not fail, but this is still ugly and many people will need this functionality.

**Comment by karelz** [comment]
How would the API look like?

**Comment by svdh2** [comment]
So there are two things that implemented in the CLR could help.

- figuring out which OS we are running. I have seen discussion about implementing  Environment.OSVersion and return an enum or a string. I would return a object OSType. OSType would be  extended for each port of the CLR as the port will be machine OS specific and the implementor will be the most knowledgeable to implement it.
 the Hierarchy would look like:
`
  abstract class OSType{
     virtual processMem(MemVisitor vis){
           vis.processMemoryMinNotAvailable();
     }
  }

  abstract class Windows : OSType{}

  abstract class WindowsServer : Windows{}

  class WindowsServer2015 : WindowsServer{
  }

  abstract class MacOS: OSType{}

  class Yosemite : MacOS{}

 `

- On top of that we need some information from the OS. Those could be code via interfaces.
  There might a hierachy of classes present in all the CLR with at the root the features common to all OS and the refinements of it giving to more specific features that are available in that OS.

`
public class OSMemoryInfoMinimal{
   public int memoryLoad;

}

public class WindowsOSMemoryInfo : OSMemoryInfoMinimal{
        public ulong totalPhys{get;}
        public ulong availPhys{get;}
        public ulong totalPageFile{get;}
        public ulong availPageFile{get;}
        public ulong totalVirtual{get;}
        public ulong availVirtual{get;}
        public ulong availExtendedVirtual{get;}
}
`

you could the let the client software access it via a visitor pattern with a system of fallbacks from most specialized information available to the least.

`class MemVisitor{
  virtual void processMemoryWindowInfo(WindowsOSMemoryInfo info){
     this.processMemoryMinInfo((OSMemoryInfoMinimal) info);
   }

  virtual void processMemoryMinInfo(OSMemoryInfoMinimal info){
    this.processMemoryMinNotAvailable();
  }
  virtual void processMemoryMinNotAvailable(){
  }
}`

The user could get the info with code like this

`ulong availVirtual;

environment.OS.processMem(
   new MemVisitor{
        processMemoryWindowInfo= new function(WindowsOSMemoryInfo info){
              availVirtual=info.availVirtual;
        }
        processMemoryMinNotAvailable= new function(){
              availVirtual=0;
        }
   });`

**Comment by svick** [comment]
> figuring out which OS we are running.

There's already an API for that: [`RuntimeInformation.IsOSPlatform`](https://docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.runtimeinformation#System_Runtime_InteropServices_RuntimeInformation_IsOSPlatform_System_Runtime_InteropServices_OSPlatform_) and other members of `RuntimeInformation`.

> On top of that we need some information from the OS. Those could be code via interfaces.
There might a hierachy of classes present in all the CLR with at the root the features common to all OS and the refinements of it giving to more specific features that are available in that OS.

That design looks overcomplicated to me. For example, making the return type nullable and returning `null` when the information is not available would work just as well and would be much simpler.

**Comment by AlexGhiondea** [comment]
@svdh2 does the API that @svick pointed out work for your scenario?

**Comment by karelz** [comment]
Closing. If there is more evidence that the existing API is insufficient, feel free to reopen. Or open a new issue to enhance the existing API (preferred).
