### ISSUE TITLE
RuntimeOps.Expando* methods missing?

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#13541]
We have code like this:

```csharp
typeof(RuntimeOps).GetMethod("ExpandoTryDeleteValue")
```

in `ExpandoObject.cs` in `System.Linq.Expressions`, but these methods do not exist.

**Comment by JonHanna** [comment]
Likewise `ExpandoTryGetValue` and `ExpandoTrySetValue`.

Perhaps omitted because they're obsolete and only being accessed through `GetMethod()` meant the seemed save to leave out?

**Comment by JonHanna** [comment]
And a few more like `ExpandoPromoteClass` and so on, too.

**Comment by JonHanna** [comment]
It seems the github bot does not recognise "This addresses issue #13541" the same way it would "Fixes #13541" or "Closes #13541" :)
This issue should was fixed by #13595 and should be closed.
