### ISSUE TITLE
SemaphoreSlim fairness: waiting threads are not first-in-first-out

### ISSUE THREAD

**Issue by v-yadli** [dotnet/corefx#13584]
Repro:
```
            SemaphoreSlim sem = new SemaphoreSlim(0);
            //__run_in_threads is a simple wrapper that spawn threads and join them.
            __run_in_threads(
                //Thread 1
                () =>
                {
                    sem.Wait();
                    sem.Release();
                },
                //Thread 2
                () =>
                {
                    sem.Release();
                    sem.Wait();
                });
```
Expected:
Thread 1 blocks on wait;
Thread 2 releases signal;
Thread 1 receives signal;
Thread 2 blocks on wait;
Thread 1 releases signal;
Thread 2 receives signal;
Thread 1 & 2 end;

Actual:
Deadlock; I checked with windbg, it seems that thread 1 has exited but thread 2 is still waiting for the signal, which means that thread 1 did not successfully release the signal.
Replace `SemaphoreSlim` with `Semaphore` and the problem is gone.

**Comment by stephentoub** [comment]
Please share the code for __run_in_threads

**Comment by stephentoub** [comment]
Actually, the repro is flawed. If thread2 runs first, it'll release and then wait on the semaphore successfully. Then when thread1 runs, it'll block forever waiting on the semaphore.

**Comment by v-yadli** [comment]
@stephentoub Thanks for the quick reply!
`__run_in_threads` sequentially starts the thread procedures and then join them.
For demonstration of the problem, I added some delay between thread starts:
```
        static void __run_in_threads(params ThreadStart[] actions)
        {
            List<Thread> threads = actions.Select(_ => new Thread(_)).ToList();
            Console.WriteLine("Starting threads");
            threads.ForEach(_ => { _.Start(); Thread.Sleep(1000); });
            Console.WriteLine("Joining threads");
            threads.ForEach(_ => _.Join());
        }
```
I get what you mean. Yes in this way it does not produce a 'deadlock'.
However, given that thread 1 is already running (because of the delay), when thread 2 releases the signal, thread 1 should be already waiting. But thread 2 still takes the signal immediately afterwards.

This does not repro 100% but still frequently. Is this by-design?

**Comment by stephentoub** [comment]
> However, given that thread 1 is already running (because of the delay), when thread 2 releases the signal, thread 1 should be already waiting. But thread 2 still takes the signal immediately afterwards. This does not repro 100% but still frequently.  Is this by-design?

Most of the synchronization primitives in .NET, including SemaphoreSlim and Monitor (which SemaphoreSlim is implemented with), by design aren't "fair", as fairness leads to problems like lock convoys.  As a result, there's no guarantee that a thread waiting for a semaphore will be released by another thread that releases it and then immediately waits for it... it's quite possible that second thread will both release it and obtain it before the other thread gets it.

**Comment by v-yadli** [comment]
Understood. Thank you for the explanation. 👍 
Updating the title of this issue because it is not deadlock issue.
