### ISSUE TITLE
Please add System.Drawing.StringAlignment to System.Drawing.Primitives

### ISSUE THREAD

**Issue by devinfluencer** [dotnet/corefx#13583]
Using this for alignment of objects inside a rectangle.
-Thomas

**Comment by karelz** [comment]
Do you have API proposal?

**Comment by stephentoub** [comment]
@karelz, he's not asking for a new API, he's asking for https://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/Advanced/StringAlignment.cs,20 to be brought to corefx.

**Comment by karelz** [comment]
Thanks, I let @alexperovich comment on complexity / triage of the issue.

**Comment by t-sch** [comment]
Thanks

**Comment by alexperovich** [comment]
Simply porting the enum `System.Drawing.StringAlignment` is easy. Its an enumeration with 3 members.

That being said I don't think this is worth doing unless we port features in `System.Drawing` that use this enum.
@weshaggard thoughts?

**Comment by t-sch** [comment]
We are using this enum in our code to control similar things as System.Drawing but we didn't want to reinvent the wheel. Now we are porting portions of our code and wouldn't want to create a proprietary copy...

**Comment by karelz** [comment]
@t-sch do you plan to use the enum in a NuGet library and its public API surface?
Or is it needed only as implementation detail of your library or application?

**Comment by devinfluencer** [comment]
Only internal.

**Comment by karelz** [comment]
@t-sch, in that case I would suggest to use a copy of the enum for now. It doesn't make sense to bring just 1 enum without its usage, unless there is benefit for libraries (if we see more evidence of that benefit, we can reconsider/reprioritize).

Until then, we should treat the issue as @alexperovich suggested - port the enum and methods which use it.

**Comment by danmosemsft** [comment]
We discussed this and don't think it's worth adding the struct unless and until we add APIs that use it. Thanks for the suggestion...
