### ISSUE TITLE
Intermittent failure in get_LastWriteTime.cs

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#1358]
This class has failed multiple times today.

MESSAGE:
Assert.Equal() Failure Expected: 0 Actual: 1
+++++++++++++++++++
STACK TRACE:
at FileInfo_get_LastWriteTime.runTest() in d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.IO.FileSystem\tests\FileInfo\get_LastWriteTime.cs:line 126

**Comment by stephentoub** [comment]
Just adding the relevant log details from the CI run:
```
 6694.879
EXEC : warning : (runTest, d:\j\workspace\dotnet_corefx_windows_debug\src\System.IO.FileSystem\tests\FileInfo\get_LastWriteTime.cs, 100) Eror_f984f! LastWriteTime is way off 
```

**Comment by Maxwe11** [comment]
dup #1313

**Comment by stephentoub** [comment]
Closing as dup
