### ISSUE TITLE
"windows.winmd" is lower-case in our Microsoft.TargetingPack.Private.WinRT package

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#13599]
Related: #8899 

ApiCompat is unable to resolve references to the "Windows" assembly, because the binary in our targeting pack is lower-case. Since we created this targeting pack, we could just rename the file in it and publish a new version. In the meantime, I'm going to disable ApiCompat on the projects affected.

**Comment by ericstj** [comment]
I fixed this and pushed a new version of Microsoft.TargetingPack.Private.WinRT.  You should be able to update to 1.0.3 to get the fix.

**Comment by mellinoe** [comment]
Thanks, @ericstj
