### ISSUE TITLE
Add 32-bit version of tests that were disabled

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#13592]
PR #13572 marked a few tests to be 64-bit only, given that the assumptions they make were only meant for 64-bit runs. This workitem is to track the addition of 32-bit version of those tests.

**Comment by karelz** [comment]
@joperezr please file 2 issues - only 1 area path per issue is strongly encouraged.

**Comment by karelz** [comment]
@joperezr can you please file 2 issues?

**Comment by joperezr** [comment]
Done. Closing this in favor of the newly opened ones.

**Comment by karelz** [comment]
Thank you!
