### ISSUE TITLE
Running `sync -p` on a clean machine installs DNVM & adds it to PATH?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#13598]
I accidentally corrupted my laptop two days ago, and was forced to do a clean install of Windows and re-clone corefx. When I ran `sync -p` for the first time on a fresh clone of the repo, here is the output I got:

```cmd
C:\Users\james\Code\git\corefx>sync -p
Installing .NET Version Manager to C:\Users\james\.dnx\bin
Creating destination folder 'C:\Users\james\.dnx\bin' ...
Installing 'dnvm.ps1' to 'C:\Users\james\.dnx\bin' ...
Installing 'dnvm.cmd' to 'C:\Users\james\.dnx\bin' ...
Adding C:\Users\james\.dnx\bin to Process PATH
Adding C:\Users\james\.dnx\bin to User PATH
Adding C:\Users\james\.dnx to Process DNX_HOME
Adding C:\Users\james\.dnx to User DNX_HOME
Installing dotnet cli...
Restoring BuildTools version 1.0.27-prerelease-01002-02...
Initializing BuildTools...
```

And indeed, when I check my home directory there appears to be a newly created `.dnx` directory, which contains dnvm under a subfolder: http://imgur.com/a/LrmZt

Since dnx was ditched after RC1, it looks like this should no longer be done? Why don't we skip straight to installing the dotnet cli?

**Comment by ellismg** [comment]
Probably due to the logic in VsDevCmd.bat which our scripts run (this is part of Visual Studio and sets up a "developer command prompt")

That script has this logic (on my machine, anyway):

```batch
@rem Run dnvm.cmd setup if it exists
@if not exist "%USERPROFILE%\.dnx" (
    @if exist "%ProgramFiles%\Microsoft DNX\Dnvm\dnvm.cmd" @call "%ProgramFiles%\Microsoft DNX\Dnvm\dnvm.cmd" setup
)
```

**Comment by ellismg** [comment]
I'm not really sure what we'll be able to do about, FWIW.

**Comment by mellinoe** [comment]
Yeah, this is just part of the VS "developer command prompt" script. We don't actually use any of that stuff.

**Comment by jamesqo** [comment]
Ah, I see. So the issue is coming from Visual Studio, rather than corefx. Bummer, hopefully it'll be fixed in the next major VS release.
