### ISSUE TITLE
Strong name validation is failing for certain analyzer assemblies with a fresh build.

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#13601]
I re-cloned corefx on a clean install of Windows, ran `sync -p`, and then ran `msbuild /t:RebuildAndTest` for the System.Linq tests. That resulted in an error message from MSBuild saying that csc couldn't verify certain analyzer assemblies: [here](https://gist.github.com/jamesqo/f07b669ee436367c46baa594760a0c67) is the log. The output when I also pass in `/v:detailed` can be found [here](https://gist.github.com/jamesqo/cc6dc7bbe105818ffafb95aaa025fa96).

**Comment by mellinoe** [comment]
@alexperovich  Ever seen this?

**Comment by alexperovich** [comment]
I haven't seen this.

**Comment by mellinoe** [comment]
@jamesqo Hm, I'm not seeing this, and I have a fairly fresh machine here. Could you let me know if this is still occurring for you, and if so, maybe the following info as well:

* Windows version
* Visual Studio version(s) you have installed
* Which developer command prompt you are using (i.e. what MSBuild version is used)

**Comment by mellinoe** [comment]
@jamesqo Still repro'ing this?

**Comment by ViktorHofer** [comment]
Closing for age.
