### ISSUE TITLE
Can DispatchProxy provide Task<object> InvokeAsync abstract method!

### ISSUE THREAD

**Issue by gencebay** [dotnet/corefx#13609]
Currently using it as HttpDispatchProxy and consuming APIs via API Contracts - Interfaces with HttpClient. As you know HttpClient provides async methods to reduce IO bound operation (async / await) as well but I could not found a proper way to call httpClient.SendAsync method from DispatchProxy implemented Invoke method.

**Comment by davidsh** [comment]
Can you please attach some sample code that describes your scenario?  I'm not sure where the `DispatchProxy` class is defined.

**Comment by gencebay** [comment]
Sure, here you are!
https://gist.github.com/gencebay/4164df17aec31c91c272492efb0a3edc

**Comment by davidsh** [comment]
Thanks for posting the code snippet:

```c#
    // Would be nice 
    private async Task<ResponseContext> InternalInvokeAsync(RequestContext requestContext) 
    {
        var httpRequestMessage = Factory.CreateHttpRequest(requestContext);
        var response = await Factory.HttpClient.SendAsync(httpRequestMessage);
        return response.ToResponseContext;
    }
```

This question is really about the features/functionality of ASP.NET and WebAPI and not .NET Core HttpClient.  So, can you please open a question in https://github.com/aspnet/home?  Thanks.

cc: @danroth27

**Comment by gencebay** [comment]
Hello again! Here you are what I'm trying to do with the DispatchProxy as DispatchProxyAsync. (have modified to async usage)
You can check or review from here! [NetCoreStack.DispatchProxyAsync] (Maybe we can merge)(https://github.com/NetCoreStack/DispatchProxyAsync)
Thanks.
