### ISSUE TITLE
Reconsider port to core approach for System.Net.HttpListener

### ISSUE THREAD

**Issue by clrjunkie** [dotnet/corefx#13610]
See discussion below at:

System.Net.HttpListener #13502

**Comment by karelz** [comment]
@clrjunkie I don't quite understand what you want to reconsider / propose.

As @stephentoub said, HttpListener is compatibility only API to make easier transition of full .NET Framework code to .NET Core. Nothing more. There are no plans to evolve it in any way. We will likely reject any API improvements on this class, we may accept some super-safe, easy-to-review and easy-to-reason-about bug fixes, but that's about it.

Also, it is not an interface, but implementation class -- as such I don't know how Kestrel could "implement it". Either way, such discussion belongs to Kestrel/ASP.NET Core repos.

**Comment by clrjunkie** [comment]
@karelz I’m not talking about C# interfaces I’m talking about “Interfaces” as in *API*.

Instead of investing time in refactoring and testing Full .NET FW HttpListener codeI urge you to strongly consider to program an adapter class named “HttpListener” having the same *API* (e.g interface) as in the full .NET FW in order to convert from HttpListener API to “Kestrel” API 

The fact that “kestrel” is developed in another department doesn’t mean it makes sense to duplicate http server implementation  efforts, regardless of scope,  but rather consolidate your efforts by having one implementation.

**Comment by karelz** [comment]
> I’m not talking about C# interfaces I’m talking about “Interfaces” as in API.

That makes much more sense.

> Instead of investing time in refactoring and testing Full .NET FW HttpListener code I urge you to strongly consider to program an adapter class named “HttpListener” having the same API (e.g interface) as in the full .NET FW in order to convert from HttpListener API to “Kestrel” API

Did you consider the fact that such approach is much more costly and most likely will never be highly compatible? Which is actually the primary goal of HttpListener (customers' code just works).
If you know how to implement it in highly compatible way, we will be more than happy to take your contribution ...
We didn't believe it would be a successful path compatibility wise (there would be a large bug tail at minimum) and we believed the overall cost would be much, much larger than "just" porting the existing implementations from Desktop and Mono/Xamarin.

> The fact that “kestrel” is developed in another department doesn’t mean it makes sense to duplicate http server implementation efforts, regardless of scope, but rather consolidate your efforts by having one implementation.

Should be answered by the text above -- it is not about duplication, artificial department boundaries, etc., but about compatible behavior, something our customers expect. Again, if you think you have better technical solution satisfying all the requirements (incl. compatibility), we will be more than happy to take it.

**Comment by clrjunkie** [comment]
HttpListener in the full .NET FW – on Windows – is simply an OO abstraction over the Win32 Http API

I have no idea how or if it was implemented by Mono/Xarmin but there is no equivalent Http API on linux (which was why kestrel was developed in the first place) so given your assessment I’m assuming Mono/Xarmin implemented HttpListener over sockets which would make the port even worse since now you need to support more web servers…

I don’t buy the “this is for compat only” or “this is for non-production scenarios” .. both meaningless from an engineering stand point. 

Can I use it or not?? 

I suggest you further investigate this area to understand the true cost of your approach.

**Comment by clrjunkie** [comment]
#13187

**Comment by stephentoub** [comment]
@clrjunkie, HttpListener is not an implementation or API surface area we plan to invest in for the future.  We recommend that kestrel and the technologies the ASP.NET folks are heavily investing in be used for that.  They have no plans to layer those technologies on top of HttpListener, nor do they have plans to expose the exact HttpListener surface area; if you have questions or concerns about why, you can ask in those repos.

Our main goal with bringing HttpListener to corefx is simply to enable existing code that runs on Windows on the .NET Framework to migrate to .NET Core.  The implementation in corefx for Windows will be just as good as the one in the .NET Framework.  Even so, we recommend that as part of or after migrating, folks look to move off of HttpListener and on to those other technologies, which are better (reliability, performance, etc.), and which are being significantly improved further moving forward.  As @karelz outlined, we are focusing here on compatibility, meaning we're basically just taking the desktop implementation and making it work in the corefx environment with minimal changes, along with any little cleanups here and there that are low-risk. We will also be bringing over the Mono implementation to enable the surface area to run on Unix, but that will have the same reliability level as the implementation in Mono, further increasing our recommendation to move to the other stacks.  We do not plan to put HttpListener on top of kestrel, for a variety of reasons, including that it would be a complete rewrite (which is more investment than just getting the .NET Framework and Mono codebases to run successfully in corefx), it would have varied behaviors and not be the same level of compatibility as we desire for something that's intended to be primarily about compatibility, and it would introduce non-trivial layering issues, with a component of corefx building on top of a component that builds on top of corefx.

Thank you for the feedback.  I hear what you're saying, and I understand there are alternative approaches; we have evaluated them, and we do not plan to change this direction.  All of this is open source, so if you disagree with the direction, you are welcome to change the implementation for your own needs in your own fork.  And as @karelz stated, if you have reliable and compatible changes you'd like to contribute back, we'd welcome PRs.

**Comment by clrjunkie** [comment]
@stephentoub 

>Even so, we recommend that as part of or after migrating, folks look to move off of HttpListener and on to those other technologies, which are better (reliability, performance, etc.), and which are being significantly improved further moving forward.

Even so AFAIK kestrel doesn't expose a public API or should I say an API for the public so what exactly is the migration path for server applications built on the HttpListener API?

**Comment by stephentoub** [comment]
> what exactly is the migration path for server applications built on the HttpListener API?

Server applications built on HttpListener are running today on either the .NET Framework on Windows or on Mono.  In either case, the HttpListener-based portions of those applications should continue to "just work" at the same level of reliability and performance as they do today, because the HttpListener implementation will essentially be the same as it is in the .NET Framework on Windows or on Mono (for Unix).  Once the application is up-and-running on .NET Core, it would be advantageous to then move it to a better performing and more reliable stack that is getting lots of investment, e.g. ASP.NET on kestrel.

**Comment by clrjunkie** [comment]
@stephentoub Sorry, that neither answers my question or addresses kestrel current state. 
If I have existing server application(s) written against HttpListener API and your telling to rewrite against some new technology because otherwise it would cost you a fortune to develop a compatibility layer, then you should make sure it doesn't cost a fortune for me.. 

Plain and simple: What is the alternative API for HttpListener?

Do you really expect people to rewrite their custom servers to fit the new ASP.NET application model with all it's abstractions where ASP.NET application model was not required to begin with? Is that the migration path?

**Comment by stephentoub** [comment]
> Sorry, that neither answers my question

@clrjunkie, I am genuinely confused about how my response didn't answer your question.

Scenario:
You have an app that runs on the .NET Framework today on Windows that uses HttpListener.  You want to migrate your app to work on .NET Core on Windows and have it run the same as it does on .NET Framework on Windows.  It works.

Scenario:
You have an app that runs on Mono today on Unix that uses HttpListener.  You want to migrate your app to work on .NET Core on Unix and have it run the same as it does on Mono on Unix.  It works.

Is your scenario different than one of those, because in both of those cases, the plan we've outlined addresses that primarily.

> Plain and simple: What is the alternative API for HttpListener?

If you want the same level of reliability and performance that you have with HttpListener on Windows with the .NET Framework, or if you want the same level of reliability and performance that you have with HttpListener on Unix with Mono, then the alternative is that you don't need an alternative... just keep using HttpListener.  The whole point of this is to provide a compatible implementation with .NET Core so that it "just works" as it has... i.e. the whole point is exactly to help migrate code.

If you then want to significantly improve performance/reliability beyond what's available with HttpListener today, you should move to the stack where effort is being invested, where competitive, production scenarios are a key focus area, as we have no plans to make additional investments in those regards in HttpListener.

**Comment by clrjunkie** [comment]
@stephentoub
>If you then want to significantly improve performance/reliability beyond what's available with HttpListener today, you should move to the stack where effort is being invested, where competitive, production scenarios are a key focus area, as we have no plans to make additional investments in those regards in HttpListener.

How?? There is no low level HTTP public API in the stack where effort is being invested which is equivalent to HttpListener’s API but rather all sorts of abstractions like middlewares, filters and what not...I don't want to bring these into my code! (But I do want the perf investments and protocol maintenance from kestrel - thats why I told you should program an adapter class - can’t be clearer then that)

**Comment by stephentoub** [comment]
> thats why I told you should program an adapter class - can’t be clearer than that

I've already stated multiple times multiple reasons why we're not planning to rewrite the HttpListener implementation in corefx on top of kestrel (besides the fact that many of the perf improvements now and in the future come from API-level differences), e.g. compatibility, layering, etc.  An adapter that provides that HttpListener surface area on top of kestrel would be a fine thing for you or someone else to write and post for others to benefit from in some other GitHub repo.

At this point, I believe we're going in circles, and either talking past each other or simply at odds and we'll need to agree to disagree.  Thanks.

**Comment by clrjunkie** [comment]
>I've already stated multiple times multiple reasons why we're not planning to rewrite the HttpListener implementation in corefx on top of kestrel

But you’re not willing to debate them which I believe is a loss.

>An adapter that provides that HttpListener surface area on top of kestrel would be a fine thing for you or someone else to write and post for others to benefit from in some other GitHub repo.

This whole approach of “If you think you can do a better job, do it yourself” is fundamentally flawed because:

1) I know I can do it myself. The issue here is not if I’m allowed to do so. I'm not asking for any permissions.
 
2) You already have man resources  allocated for this task (substantial I figure from the open issues) and it looks like it's is in a preliminary stage. The whole point of this issue is to reevaluate the path taken against a concrete suggestion.

>At this point, I believe we're going in circles, and either talking past each other or simply at odds 

As far as I’m concerned I’m talking to you not past you. It’s unfortunate that we cannot hold a technical debate on the pros and cons of either approach. It’s not like I’m advocating for something that has no merit – code reuse is generally considered a good thing. Furthermore, you pointed out some valid issues like build across repos which definitely requires further discussion but at the same time I believe your missing out on other key compatibility scenarios such as: what if I want to run my Server on both Windows and Linux like in Java? How can you assure HttpListener compatibility across platforms when the underlying implementation is radically so different? Furthermore, I don’t share your confidence that things will "just work" at the same level of reliability and performance as they do today especially on *nix environments. I mean sure it’s low risk on Windows since the bulk of the Http Server is implemented by Windows and HttpListener is basically an OO Adapter to the Win32 Http API, but moving an entire Http Server code base from Mono/Xarmin to CoreCLR looks like a completely different challenge because key .NET dependencies where rewritten in .NET Core starting with the System.Net.Sockets implementation and API Surface… Are you planning to bring in the Mono Sockets Implementation as well?

Lastly, whether HttpListener API is the right Http contract to layer ASP.NET Abstractions is indeed a different issue and can only be debated when compared to an alternative (which I see none at this point) but that doesn’t mean that an HttpListener Adapter for kestrel can’t co-exists parallel to ASP.NET Core Stack… 

No problem being at odds :) Thanks.

**Comment by danmosemsft** [comment]
Closing based on the discussion above.
