### ISSUE TITLE
[HttpListener] Add more test coverage for System.Net.HttpListener.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#13618]

**Comment by karelz** [comment]
We triaged this one out into Future, because HttpListener is mainly compat API.

Estimate: 2w
Technical debt: not all tests were ported when the HttpListener component was ported. Requires multi-machine infrastructure design and work, not included in the estimate (+ ~4w).

**Comment by hughbe** [comment]
@karelz see #17980.

I started adding tests for this one out of my own curiosity investigating the HTTP stack (before this was moved to future).

It looks like there are some subtle bugs not covered by tests. Obviously adding tests for this one is a big task - we need some more coverage for 2.0 though.

**Comment by karelz** [comment]
`HttpListener` is compat API - i.e. it's goal is to achieve parity on the most used features with Desktop. We do not plan to evolve compat APIs, or improve their perf. Even to the point of - we will likely not take risky or complex contributions in the implementation (or API surface). If customers want high-performance, scalable, modern APIs for Http server, we recommend to use Kestrel.

From that perspective, having full test coverage or bug-by-bug compatibility is something we would like to have, but realistically, we won't be able to invest into it in 2.0 timeframe (there's just too many higher priority non-compat APIs to focus on).

If you're interested in the space, we will be very happy to take more tests contributions, and take bug fixes contributions which make the API more compatible. We will be happy to answer questions and provide guidance if you need it. However, we won't be likely able to invest proactively in it ourselves before 2.0 ships. We may change our mind in future, based on customer feedback, additional evidence, etc.
Makes sense?

**Comment by karelz** [comment]
Triage: Generic + we had new tests from @hughbe in the space, so we may be covered.
We will review code coverage by end of 5.0 and if it pops up, we can re-evaluate.
