### ISSUE TITLE
DNS client and custom DNS queries

### ISSUE THREAD

**Issue by MichaCo** [dotnet/corefx#13613]
Hi,
I was looking for this for some time now and it seems either the feature is hiding pretty well or is missing.

System.Net has basic name resolution and network information now. But what about a DNS client which can query any kind of DNS server?

I'm currently trying to implement services with the new aspnet core stack. One common scenario with Microservices is service discovery. And one common solution for this is to use DNS.

An example would be to query the consul DNS endpoint for service discovery. And this is not really easily doable today.

There are certain implementations available for the .NET world, but those are pretty basic and mostly not maintained repositories and/or they are not supporting netstandart.

Are there any plans to add something like that? Or, if I'm just missing something, any hint? 
Thanks a lot!

**Comment by karelz** [comment]
cc: @davidsh @CIPop

**Comment by CIPop** [comment]
@MichaCo Your observation is correct. We have split out the System.Net.NameResolution contract to give us the ability to extend our existing library and offer more advanced name resolution functionality like the scenarios you mentioned.

It would be great if you could create a feature request issue by giving us a few examples of how you think the APIs should look like as well as pointing out the RFCs involved for reference. You may also propose new APIs and their implementations following our [process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md).

**Comment by MichaCo** [comment]
@CIPop  thanks! I submitted my proposal, hf reading that wall of text ;)

**Comment by CIPop** [comment]
@MichaCo Thanks! I like 👍 .
