### ISSUE TITLE
HandleCollections should have an indexer

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/corefx#13624]
I have a use case where I need to index into methods and fields on a `TypeDefinition`. `FieldDefinitionHandleCollection` and `MethodDefinitionHandleCollection` don't have an indexer, so the only option seems to be to get an enumerator and call `GetNext()` method *N* times to get *N*th member.

`GenericParameterHandleCollection` or `GenericParameterConstraintHandleCollection` already have an indexer. This seems like an API inconsistency. Unless there's a particular reason why the other `HandleCollections` can't have it, the indexer should be added to all of them. We can make them implement `IReadOnlyList<T>` while we're at it too.

**Comment by MichalStrehovsky** [comment]
Cc @tmat @nguerrera

**Comment by tmat** [comment]
It's by design. The APIs in System.Reflection.Metadata do not make an assumption that it is possible to efficiently index into member lists. You can use MetadataTokens.FieldDefinitionHandle(int rowNumber) from Ecma335 namespace to get a handle fro ma row number.

**Comment by MichalStrehovsky** [comment]
> The APIs in System.Reflection.Metadata do not make an assumption that it is possible to efficiently index into member lists

If the concern is portability to other formats (such as the .NET Native metadata format), we already have a problem there for `GenericParameterHandleCollection` and `GenericParameterConstraintHandleCollection` that do expose the indexer and there's no way to efficiently implement it in the .NET Native format.

If this is going to be resolved by design, is there a way to get to the row numbers ranges for a specific type? Everything that looks remotely useful is marked internal.

**Comment by tmat** [comment]
Parameters and generic parameters have semantic sequence number no matter what the encoding in metadata is. Members do not. A token/row number for members is an implementation detail. 

Could you explain your scenario in more detail? What are you trying to achieve?

**Comment by MichalStrehovsky** [comment]
This is for the CoreRT type system. We have [a method](https://github.com/dotnet/corert/blob/77d17f08abfe27d43760b2321376a99fdb5a00fb/src/Common/src/TypeSystem/Ecma/EcmaType.cs#L358-L365) on the object representing a type that enumerates the type system objects representing fields. The current implementation is horribly inefficient and I'm trying to see if I can make it work with a struct enumerator.

The problem is that we have to support multiple metadata formats and I can't hardcode S.R.Metadata's enumerator in the struct enumerator to-be. I can put a int-sized cookie in it though. The int-sized cookie could be the ordinal number of the field or something else that will let me quickly get to the field metadata.

**Comment by tmat** [comment]
Why not use FieldDefinitionHandle for such a cookie?

**Comment by tmat** [comment]
Why not have an immutable array of MethodDescs on the type and just return it? It can be initialized lazily. That's how Roslyn does it.

**Comment by MichalStrehovsky** [comment]
> Why not have an immutable array of MethodDescs on the type and just return it?

Those come with a different set of tradeoffs. A change to struct enumerators is a net improvement. But allocating a cached immutable array impacts working set.

I would keep that as a plan B if switching to struct iterators still didn't have good enough performance characteristics. The CoreRT type system doesn't cache much to keep the footprint minimal. We might have to tweak that policy, but at this point there's a lot of overhead (such as the current design of `GetMethods()`) that makes these kinds of measurements difficult.

**Comment by tmat** [comment]
You don't cache the allocated MethodDescs?

**Comment by MichalStrehovsky** [comment]
Those are cached. Not caching those would be a waste.

**Comment by tmat** [comment]
If they are already cached are you worried about the additional overhead of the array itself? That's 4B per member. If that's a problem, perhaps the array can be a Slice into an array of the members used by the cache, or something like that.

**Comment by MichalStrehovsky** [comment]
Yes, my concern was about the extra arrays (one for fields, one for methods), plus two extra pointers in the class representing a type.

Our cache is currently a dictionary from token to the MethodDesc. I guess I could look into overhauling that to have a way to get a contiguous region of memory, but a way to index into metadata would still be less invasive :).

**Comment by tmat** [comment]
It doesn't need to be 2 arrays. You can have just one storing all members. Fields can be stored first and then methods, or something like that.
BTW, looking into EcmaType, why is _typeDefinition needed? It can be retrieved given a reader and a handle.

**Comment by tmat** [comment]
Retrieving TypeDefinition is cheap unless WinRT projections are involved. If you don't have projections enabled it's basically a no-op.

**Comment by tmat** [comment]
Another savings could be achieved by using UTF8 string for the names. The reader has now API to get a pointer to the UTF8 String stream for given StringHandle.

**Comment by tmat** [comment]
The collections don't expose indexers by design.
