### ISSUE TITLE
.NET Core should have a System.Drawing.Primitives Contract with core Types from System.Drawing.

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#1363]
Based on analysis, these types are commonly used even outside Image processing scenarios. We should factor them out to allow for greater code reuse and portability on .NET Core.

•	Color
•	KnownColor
•	Point
•	PointF
•	Rectangle
•	RectangleF
•	Size
•	SizeF

**Comment by Kukkimonsuta** [comment]
I don't think KnownColor should be included since it is system dependant and most values have no meaning under console only environments.

**Comment by mellinoe** [comment]
I would also agree that KnownColor, and also all of the static "named" colors on the Color struct should probably be eliminated. We can always have some sort of helper library that has a "Colors" class with a bunch of pre-defined colors in it.

**Comment by Priya91** [comment]
From our internal discussion:
We decided to go with WPF types over System.Drawing ones, however, these WPF types use doubles for their coordinate system, the extra precision over floats is never necessary and floats can be used for SIMD. For now, we will implement these types with float, and add integer versions later, if they are needed. The proposal is to create the following new types under System.Numerics
- Color
- Rectangle
- Size
- Point

Api Review to follow shortly internally.

**Comment by mikedn** [comment]
> however, these WPF types use doubles for their coordinate system, the extra precision over floats is never necessary and floats can be used for SIMD

Not to say I'm against using floats but I'm not quite sure what this has to do SIMD. Is it because a double based Rectangle would require 2 SSE registers instead of one?

> Api Review to follow shortly internally

Why not create a speclet on GitHub first so the community can provide feedback?

**Comment by patricksadowski** [comment]
+1 for a speclet. I have some thoughts about color (RGB, HSV, HSL) and namespace (why System.Numerics and not System.Drawing.Primitives?)

**Comment by Marfusios** [comment]
Same as patricksadowski , Color type under System.Numerics it's a little weird

**Comment by Priya91** [comment]
> Not to say I'm against using floats but I'm not quite sure what this has to do SIMD. Is it because a double based Rectangle would require 2 SSE registers instead of one?

By SIMD, the .NET implementation of Vector and other SIMD related types in System.Numerics.Vectors is based on floats, hence using the same primitive type for these types as well. For example a color with rgb can be represented as a Vector3. 

> Same as patricksadowski , Color type under System.Numerics it's a little weird

A color is RGB, or RGBA which can be represented as Vector3, Vector4. The Color type here will not have any named colors, but vector functions like Lerp, Multiply. It is to be treated as a numeric. 
But that said, there was a concern raised that existing graphic applications that use System.Numerics and other .NET namespaces (especially Windows.UI) that have these types defined, will now have to resolve conflict of which namespace this type is from. System.Numerics may not be the right way, and we may have to use a new namespace like System.Drawing.Primitives. I will add this concern in the API review.

**Comment by Priya91** [comment]
Closing this issue, and tracking with #1563.
