### ISSUE TITLE
Fast append or insert StringBuilder into other StringBuilder

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/corefx#13639]
Hello,
I think for fast strings processing, StringBuilder should have fast methods to append and insert other StringBuilder.

Now when I gather string from many parts, I gather each part into separated StrindBuilder (for example in different threads for speed) and then when I gather all parts to one StringBuilder, the standard library made many copy operations to convert each StringBuilder to string and then to copy each string to StringBuilder chunks. It is bad because after each part is appended to final StringBuilder, it is no longer used or changed, it is just collected by garbage. So it would be great just append chunks from one StringBulder to other without copy them two times.

So to fast append second StringBuilder to first StringBuilder, it can just append chunks from second to first. After that it can set CopyOnChange flag in common chunks of first and second StringBuilders. Later if CopyOnChange chunk should be changed (very rare unusual case) it should be duplicated before changing.

**Comment by danmosemsft** [comment]
Append is already tracked by https://github.com/dotnet/corefx/issues/4928. Perhaps you would like to pick up ownership of that issue and write an [API proposal](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md)? It should not be long or complicated. Then we can review the API, and if approved, someone can implement it - potentially you if you like.

As for Insert you can roll it into one or write up a separate API proposal for that.

If you agree please close this issue...
