### ISSUE TITLE
[ARM/Linux] Error during cross building for arm32

### ISSUE THREAD

**Issue by hseok-oh** [dotnet/corefx#13640]
Build environment: x64 Ubuntu 14.04 
Build target: arm32
commit: ece35f9
Build option: release, skiptests, enable outloop

error log in msbuild.log

```
  1266>/nfs/rbp3/corefx/layout/layout.proj(74,5): error MSB3030: Could not copy the file "/nfs/rbp3/corefx/bin/Windows_NT.x64.Release/Native_aot/clrcompression.dll" because it was not found.
.....
       "/nfs/rbp3/corefx/build.proj" (default target) (1) ->
       "/nfs/rbp3/corefx/layout/dir.proj" (Build target) (1263) ->
       "/nfs/rbp3/corefx/layout/layout.proj" (Build target) (1266) ->
       (GetAssetsFromReports target) ->
         /nfs/rbp3/corefx/layout/layout.proj(74,5): error MSB3030: Could not copy the file "/nfs/rbp3/corefx/bin/Windows_NT.x64.Release/Native_aot/clrcompression.dll" because it was not found.
    10 Warning(s)
    1 Error(s)
```

I've get error, but can use build results in corefx/bin directory.

**Comment by vcsjones** [comment]
Same problem.

**Comment by vcsjones** [comment]
@ericstj is this your area of expertise?

**Comment by ericstj** [comment]
This was @weshaggard's change.  Wes, why is the layout.proj trying to build windows layouts on a mac machine? https://github.com/dotnet/corefx/blob/master/layout/layout.proj#L21

**Comment by weshaggard** [comment]
Yes I will take a look. 

>Interestingly, the build servers show the same error, but continue the build, anyway. 

The builds are hitting another error (https://github.com/dotnet/buildtools/issues/1224) which is why they are not correctly failing in these cases. It is safe to ignore for now these errors for now.

**Comment by vcsjones** [comment]
>It is safe to ignore for now these errors for now.

OK. I was hitting an unrelated build error which lead me to believe this was blocking me.

**Comment by weshaggard** [comment]
@joperezr is disabling this project from building temporarily (https://github.com/dotnet/corefx/pull/13651/files/3878be1f7f72232775a089345539ba882c2e7eb1..fd662f31278cbb44eea393b0a631f3c512d796a3)  until I can get it properly fixed.
