### ISSUE TITLE
Add a Prompt method for System.Console that accepts an output message.

### ISSUE THREAD

**Issue by glennblock** [dotnet/corefx#1367]
A very common pattern in a Console application is to collect input from the user. Generally preceding this is a message informing the user what they should enter. Today this results in a pattern of `Console.WriteLine("...")` followed by `Console.ReadLine()`.

A `Prompt` method which accepts a string, would consolidate this to a single line of code.

I've come across this zillions (obvious lie) of times over the years of working with .NET, including this evening as I was creating a console app.

I've created a [gist](https://gist.github.com/glennblock/cf2236b5edfaceb18240) that shows real code that I was writing for a sample. The gist also shows how the code would look with the `Prompt` method. It's important to note, that I'd be writing similar code over and over in this app.

I am happy to take this work and submit it as a PR, if it is perceived as making sense. I am also happy to be told that I am doing it wrong and there is an easier way :-)

# Proposal
New `Prompt`  method on `System.Console` which accepts a prompt which is outputted before the input is captured.

# Justification
Reduces the need for redundant (and for some non-intuitive) code for a common scenario in Console Apps.

# Design (with a rough imp)

```csharp
public static string Prompt(string message) {
  Console.Write(message); //one can pass a newline in message.
  return Console.ReadLine();
}
```

Thanks!

**Comment by satish860** [comment]
+1 This will be helpful . But the method Name can ReadLineWithMessage() may be good ..

**Comment by glennblock** [comment]
@satish860 wouldn't it be obvious by the name? Maybe change the `message` param to `outputMessage` to make it more clear?

**Comment by kangaroo** [comment]
@glennblock For what its worth, I started writing a comment similar to @satish860 but backed away.  My concern was API confusion.  I'm not 100% convinced on it, but felt I should throw my vote of uncertainty in considering someone else put it out there :)

**Comment by kangaroo** [comment]
@glennblock Also, I think a param name change could help significantly for those who use intellisense (but thats not 100% of people) -- that said instead of outputMessage, perhaps promptMessage?

**Comment by zabulus** [comment]
What if I don't need to write new line after prompt, instead read user input in the same line?
```
public static string ReadLine(this Console console, string message) {
  console.Write(message);
  console.Write(" ");
  return console.ReadLine();
}
```
It would need another extension method. 
I think Console class has good API, that allows every user to create his own extension methods fits for his project.

**Comment by glennblock** [comment]
@zabulus great point. But that could easily be addressed by having the new `ReadLine` do `Console.Write` instead of `Console.WriteLine`. Then if one wants to add the CRLF they just do that in the string they have passed.

**Comment by glennblock** [comment]
@kangaroo sure or just `prompt`. It is a string so it should be obvious it is writing out a message.

**Comment by kangaroo** [comment]
@glennblock Like I said, I was on the fence and don't feel strongly one way or the other about this one, I just had an initial reaction that aligned with @satish860 so I figured it was worth calling out.

**Comment by glennblock** [comment]
Well just found one problem with this. `Console` is a static type. This means it cannot be an extension method, it must be on the type.

**Comment by zabulus** [comment]
I think adding such method to API is a little mixing of concerning. User formats his string himself and places CRLF in places he wants. 
API serve for this well as it is. 
You always can create ConsoleEx static class which adds all functionality you want.

**Comment by glennblock** [comment]
@zabulus One could add their own static class. That being said, I've probably had to do this hundreds of times over the years. I am sure I am not the only one. Having an overload that handles this, doesn't prevent using the standard methods, it is a convenience method.

In terms of separation of concerns, you can argue that for almost any convenience method. ;-)

**Comment by glennblock** [comment]
OK thinking about this more, how about the method is called `Prompt`

**Comment by trayburn** [comment]
I like the name `Prompt` for the name.  I am curious if it ignores the possibility Color changes (for prompt text, for example) but basic functionality I see the win and support it.

**Comment by ericlaw1979** [comment]
It'd be especially excellent if it allowed arrow-key navigation around the input area. That way app could propose a response (e.g. a default filename) and the user could edit it.

**Comment by terrajobst** [comment]
So here is what I heard:

```diff
 namespace System {
     public sealed class Console {
+        public static string ReadLine(string prompt);
     }
 }
```
This looks reasonable to me. I don't even mind the prompt. Considering that there is only one other overload that doesn't take a string, I think the confusion can easily be solved via IntelliSense.

@ericlaw1979:

> It'd be especially excellent if it allowed arrow-key navigation around the input area. 

That wouldn't be a bad idea but I think that should be a general feature of `ReadLine` and not specific to this overload. It should be a separate issue altogether, actually.

@weshaggard @KrzysztofCwalina Any concerns around this proposal?

**Comment by KrzysztofCwalina** [comment]
@terrajobst, I don't feel super strongly either way. I don't think this API adds great value, but the addition is realtivelly simple so I am ok with it. One thing we should decide is if we use WriteLine or Write to write the prompt. WriteLine would be more convenient in more cases, and Write would be more flexible (can serve as WriteLine and Write). Also, should we have an overload that takes format string and params object[]?

**Comment by terrajobst** [comment]
We've discussed this today and the concern is that:

1. The API doesn't add a lot of value.
2. There are plenty of various (password prompts, reading on the same line or the next line).

We feel that we want to lead these policies to the consumer of the `Console` class.
