### ISSUE TITLE
readonly on two Formatter fields does not match NS2.0

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#13689]
These two fields were marked `readonly` in Core, but were not `readonly` in the full Framework, and thus not in Standard. Adding readonly to a protected/public field is a breaking change so we should probably revert this.

```
namespace System.Runtime.Serialization {
    public abstract class Formatter : IFormatter {
        protected readonly Queue m_objectQueue;
        protected readonly ObjectIDGenerator m_idGenerator;
    }
```

@shmao @zhenlan

**Comment by stephentoub** [comment]
I probably did that as part of porting it to core.  I'll fix it.
