### ISSUE TITLE
Oversights in X509Certificates namespace 

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#13687]
Small omissions from X509Certificates ns. 

`X509CertificateCollection` needs to derive from `CollectionBase`
`X509CertificateCollection.X509CertificateEnumerator` needs to be `new` ie 
```
public new X509CertificateCollection.X509CertificateEnumerator GetEnumerator();
```

Also this method is missing.
``` 
   public class X509Chain : IDisposable {
        public static X509Chain Create();
    }
```

/cc @steveharter

**Comment by steveharter** [comment]
For X509Chain.Create just return new X509Chain() and ignore CryptoConfig

**Comment by danmosemsft** [comment]
Take care with https://github.com/dotnet/corefx/pull/2824
