### ISSUE TITLE
Span: Restore Span<T>[index] return type to "ref T" and remove Span<T>.GetItem()

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#13681]

**Comment by joshfree** [comment]
@VSadov @KrzysztofCwalina

**Comment by davidfowl** [comment]
@joshfree I think we should do this now that we have csproj everywhere.

**Comment by Petermarcu** [comment]
Hi all, as you can see from the link Jan just gave, this change has broken folks trying to use ASP.NET on 2.0. Is this a critical fix or one we can back out until the breaking change can be coordinated?

**Comment by davidfowl** [comment]
This can be closed.
