### ISSUE TITLE
Missing RuntimeHelpers.Equals

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#13692]
This guy got overlooked

```
namespace System.Runtime.CompilerServices {
    public static class RuntimeHelpers {
        public static new bool Equals(object o1, object o2);
    }
}
```

**Comment by jamesqo** [comment]
Sorry, just curious: what exactly is the difference between this & a simple `ReferenceEquals`? Is there a scenario where they will return differing values? I've known for a long time that the default `object.Equals` calls this, but I wasn't able to figure it out.

**Comment by danmosemsft** [comment]
@jamesqo I actually don't know, since it appears to [call through](https://github.com/dotnet/coreclr/blob/3baf3a71dfa8a1504efd54973fe7ae5aedef0e13/src/vm/ecalllist.h#L1856) to `object.Equals`
@jkotas will know the history.

**Comment by jkotas** [comment]
There is difference for boxed valuetypes - `RuntimeHelpers.Equals` compares the content, not the boxed reference:

```
var a = (object)1;
var b = (object)1;

Object.ReferenceEquals(a, b); // false
RuntimeHelpers.Equals(a, b); // true
```

**Comment by jamesqo** [comment]
@jkotas Ah, I see. Doesn't `ValueTuple` override `Equals` anyway, though?

**Comment by jkotas** [comment]
This has nothing to do with ValueTuple.

**Comment by jamesqo** [comment]
@jkotas, sorry. I meant ValueType.

**Comment by jnm2** [comment]
Yes yes yes! I've wanted this for so long!
I was just talking about needing this the other day. Here's a practical example. https://github.com/dotnet/corefx/issues/13831#issuecomment-262018673

**Comment by jnm2** [comment]
Can this be ported to desktop framework please?

**Comment by jkotas** [comment]
This method was in .NET Framework for last 15+ years. There is nothing to port.

Note that RuntimeHelpers.Equals is somewhat broken API. It can return false negatives. For example if the valuetype layout has holes and the actual value came from interop, these holes can have random content and thus RuntimeHelpers.Equals can return false even for values that are equal. Similar problem exists if the valuetype implementation has fields that can do not matter in some cases.

**Comment by jnm2** [comment]
@jkotas Oh my! How did I possibly miss that? 😳 Thank you.
