### ISSUE TITLE
Specialize ImmutableArray.InsertRange for arrays.

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#13695]
I made an optimization in #13158 to make `ImmutableArray.InsertRange` for well-known collections, including arrays, lists, and `ImmutableArrays`. Unfortunately, the optimization for arrays had to be reverted. For context, see https://github.com/dotnet/corefx/pull/13158#discussion_r86702932

There are a few possible workarounds for this:

1) Use a for-loop, which will be less efficient than `Array.Copy`.
2) Check that the `T[]` is really of type `T[]` by testing `array.GetType() == typeof(T[])` beforehand, and use `Array.Copy` if so, or else fall back to a for-loop.
3) Just use `Array.Copy`, and break the existing scenario.

I personally think option 3 is reasonable. It's technically a breaking change, e.g. the test app I posted in my comment would no longer work:

```cs
class Program
{
    static void Main(string[] args)
    {
        int[] ints = new[] { 1, 2, 3 };
        uint[] uints = (uint[])(object)ints;

        var immutableUints = ImmutableArray.Create(new[] { 1u, 2u, 3u });
        immutableUints.AddRange(uints); // Works now; with changes, will throw ArrayTypeMismatchException
    }
}
```

But considering that today `ImmutableArray.Create((uint[])(object)new[] { 1, 2, 3 })` also throws an exception, indicating these types of arrays are not really supported, it seems reasonable to make this change.

cc @AArnott

**Comment by jamesqo** [comment]
Note: if #13816 is fixed, this will be a non-issue and the optimization can simply be applied again.

**Comment by AArnott** [comment]
Even if #13816 is fixed, that will only be for future runtimes, I presume. Since System.Collections.Immutable.dll runs on older runtimes, I don't know what we could make an optimization that takes a dependency on a newer runtime.

**Comment by jamesqo** [comment]
cc @jkotas; if the behavior of `Array.Copy` is fixed, will it be ported back to desktop so we can make this optimization?

@AArnott If it isn't backported, one possible solution would be to use the new [`RuntimeInformation`](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.InteropServices.RuntimeInformation/src/System/Runtime/InteropServices/RuntimeInformation/RuntimeInformation.cs) API to check if we're running on coreclr, and only then employ the optimization.

**Comment by jkotas** [comment]
> will it be ported back to desktop so we can make this optimization?

Maybe, eventually. Note however that it will likely take a very long time until System.Collections.Immutable.dll is not supported on existing runtimes.

>  use the new RuntimeInformation API 

This has similar problem. Immutable collections works all the way to Netstandard1.0. RuntimeInformation is not NS 1.0.

**Comment by AArnott** [comment]
Thanks, @jkotas. Then I think if we make this optimization, it should be the careful one described in the issue description that assumes `Array.Copy`'s current behavior.

**Comment by ianhays** [comment]
I agree with @AArnott, we should be careful here and not break any scenarios if we can avoid it.

@jamesqo were you still planning on working on this issue?

**Comment by jamesqo** [comment]
@ianhays This was already fixed, actually: https://github.com/dotnet/corefx/pull/15296/files#diff-1b253343143020c47f05f28a4aeaad5aR127 It can be closed. Thanks for pinging me on this.
