### ISSUE TITLE
Windows NT Debug CI Builds failing

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#13727]
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [D:\j\workspace\windows_nt_de---4526f5ff\src\System.ServiceProcess.ServiceController\tests\System.ServiceProcess.ServiceController.TestNativeService\System.ServiceProcess.ServiceController.TestNativeService.vcxproj]

https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/247/
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/241/
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/248/

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/pull/13733
