### ISSUE TITLE
Move API lists to buildtools repo

### ISSUE THREAD

**Issue by JohnChen0** [dotnet/corefx#13738]
PR #13440 added two new API list files in the top-level directory of this repo. These two files should be moved to the buildtools repo eventually.

**Comment by karelz** [comment]
@JohnChen0 do you plan to address this issue?
Why did we introduce them in corefx repo when they belong somewhere else?

**Comment by JohnChen0** [comment]
Yes, I plan to address this issue. The reason to temporarily add the lists to corefx repo was to avoid long wait before merging PR #13440, as changes in buildtools repo will take longer to be tested and propagated.

**Comment by karelz** [comment]
OK, assuming you're working on it now, I'll assign it to you and mark as bug.
Please check [simplified triage rules](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified)

**Comment by JohnChen0** [comment]
Fixed with #14474.
