### ISSUE TITLE
Build for x86 on Windows runs tests using 64-bit runtime

### ISSUE THREAD

**Issue by JohnChen0** [dotnet/corefx#13739]
After running `build -buildArch=x86` on Windows, the build script created `bin\tests\AnyOS.x86.Debug` and `bin\tests\Windows_NT.x86.Debug` directories. However, 64-bit `coreclr.dll` and `corerun.exe` were copied into these directories, so the tests were actually run with 64-bit runtime.

**Comment by danmosemsft** [comment]
@joperezr

**Comment by joperezr** [comment]
This is a known issue and actually I'm currently working now on fixing it. @JohnChen0 in the mean time, you can workaround it by also passing `TestNugetRuntimeId` like: `build.cmd -buildArch=x86 -TestNugetRuntimeId=win7-x86`

**Comment by JohnChen0** [comment]
@joperezr Thanks for the update and workaround.
