### ISSUE TITLE
[ARM/CI] Need to install some packages for arm-hardfp cross build

### ISSUE THREAD

**Issue by wateret** [dotnet/corefx#13749]
The HardFP build fails with:
```
02:56:56   /usr/bin/ld: unrecognised emulation mode: armelf_linux_eabi
02:56:56 
02:56:56   Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 i386linux elf_l1om
02:56:56   elf_k1om i386pep i386pe
02:56:56 
02:56:56   clang: error: linker command failed with exit code 1 (use -v to see
02:56:56   invocation)
02:56:56 
```

Probably the package `binutils-arm-linux-gnueabihf` is missing.
To work for it, I may need a remote access to cloned CI machine.

**Comment by wateret** [comment]
I found out what we need for arm-hardfp CI here #13581. [success log](https://ci.dot.net/job/dotnet_corefx/job/master/job/linuxarmemulator_hardfp_cross_debug_prtest/3/)
However it may not be a good idea to install pacakges and make symbolic links in the CI script cause it is enough to apply these operations only once.
Could you tell me which would be better? @mmitche @jashook

**Comment by hqueue** [comment]
@wateret@karelz Can we close this issue ? It seems that  https://github.com/dotnet/corefx/pull/15900 is merged by now we can cross-build corefx for arm(hardfp) inside a docker image.
