### ISSUE TITLE
Upgarding nuget package of .NETCoreApp breaks debugging

### ISSUE THREAD

**Issue by arielbh** [dotnet/corefx#13753]
Creating a new console .NET core application:
After upgrading the .NET Core App package.
Getting this errors when building:
tNet.Common.Targets(262,5): error : Can not find runtime target for framework '
1>.NETCoreApp,Version=v1.0' compatible with one of the target runtimes: 'win10-x6
1>4, win81-x64, win8-x64, win7-x64'. Possible causes:
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.Do
1>tNet.Common.Targets(262,5): error : 1. The project has not been restored or res
1>tore failed - run `dotnet restore`
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.Do
1>tNet.Common.Targets(262,5): error : 2. The project does not list one of 'win10-
1>x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section.
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.Do
1>tNet.Common.Targets(262,5): error : 3. You may be trying to publish a library,
1>which is not supported. Use `dotnet pack` to distribute libraries.

Workaround:
Altering the project.json to include type="platform" fixed the issue.

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    },

**Comment by rrelyea** [comment]
Try doing this same thing with nuget.tools.vsix 3.5rtm installed for vs 2015. I believe that fixes the loss of metadata on upgrade.
Current .net core tools preview2 chain installed 3.5b2

**Comment by karelz** [comment]
@ericstj @weshaggard @mellinoe is it something we can address in corefx or does it belong somewhere else?

**Comment by weshaggard** [comment]
Similar to @rrelyea I suspect this is a tooling issue so there isn't anything in corefx that would address it.

**Comment by karelz** [comment]
Closing for now then.
