### ISSUE TITLE
Enable System.IO.Compression to use zlib on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1375]
The Unix compilation of System.IO.Compression is using the managed deflater implementation.  We want to switch it to using the zlib implementation (at least by default; we could consider having the managed implementation as a fallback if zlib isn't installed).

**Comment by nathanaeljones** [comment]
Any reason System.IO.Compression isn't on referencesource?

**Comment by akoeplinger** [comment]
@nathanaeljones It is: https://github.com/Microsoft/referencesource/tree/master/System/sys/system/IO/compression

**Comment by nathanaeljones** [comment]
Ah, I was using `ZipArchive` as my search term. Any reason ZipArchive & friends are missing?

**Comment by akoeplinger** [comment]
Good question, I don't know :)
