### ISSUE TITLE
Need some improvement for TimeSpan

### ISSUE THREAD

**Issue by huanwu** [dotnet/corefx#13766]
There're two main areas.
Support the DefaultValue attribute.
Follow the similar pattern as the DateTime.

**Comment by Clockwork-Muse** [comment]
@huanwu - what do you mean by
>Follow the similar pattern as the DateTime.  

?

**Comment by huanwu** [comment]
@Clockwork-Muse I mean make the code style, format of TimeSpan similar as DateTime.

**Comment by shmao** [comment]
@huanwu what's the issue we are tracking here? Do we want to fix this for NS2.0?

**Comment by huanwu** [comment]
@shmao We supported the TimeSpan in the desktop but differs a little. e.g. The core doesn't support DefaultValue attribute.

**Comment by shmao** [comment]
@huanwu did https://github.com/dotnet/corefx/pull/18761 fix this issue?

**Comment by huanwu** [comment]
@shmao #18761 solve the first one. We probably can close this issue.

**Comment by shmao** [comment]
Sounds good. Closing the issue.
