### ISSUE TITLE
ValueTuple should no longer use EqualityComparer.Default for hashing.

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#13774]
As of dotnet/coreclr#7895, `GetHashCode()` on an enum no longer boxes the enum. So, there are no advantages of using `EqualityComparer<T>.Default.GetHashCode(obj)` over `obj?.GetHashCode() ?? 0`. So all of the [code in `ValueTuple`](https://github.com/dotnet/corefx/blob/master/src/System.ValueTuple/src/System/ValueTuple/ValueTuple.cs#L1919) which calls `EqualityComparer<T>.Default` should just use the latter version instead.

<s>@karelz, can you please mark this as 'grabbed by community'? Also, there's no need to cc anyone as I'll submit a PR for this within a day or two and tag the relevant people. Thanks.</s>

**Comment by stephentoub** [comment]
Is this ValueTuple code only used on platforms that have that coreclr fix?

**Comment by jamesqo** [comment]
@stephentoub, @MichalStrehovsky just mentioned something about this in https://github.com/dotnet/coreclr/issues/8143#issuecomment-261388963. I'm not sure if the code is only used on the platforms with the fix, but if it isn't, then I guess I'll have to wait a few months.

**Comment by karelz** [comment]
Given that it is technically blocked - it may be for years rather than months, I would rather close it and bring the idea back once we can actually can change it ...

**Comment by AlexGhiondea** [comment]
@jamesqo as @karelz mentioned getting the underlying change in all the platforms will take a long time. I am going to close the issue for now and we can open a new one once it becomes feasible to do this.
