### ISSUE TITLE
Add IEnumerable<KeyValuePair<TKey, TValue>> variants to Dictionary's .ctors

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#1378]
We should consider adding constructors to `Dictionary<TKey, TValue>` which allow building a Dictionary from an IEnumerable of KeyValueParis.
## Rationale and Usage

Given an `IEnumerable<KeyValuePair<TKey, TValue>>` there's no simple way to construct a dictionary, around it.  Instead you have to do something like:

``` csharp
var dict = new Dictionary<TKey, TValue>();
foreach (KeyValuePair<TKey, TValue> kvp in enum)
{
    dict.Add(kvp.Key, kvp.Value);
}
```

or

``` csharp
var dict = enumerable.ToDictionary(kvp => kvp.Key, kvp => kvp.Value);
```

`ConcurrentDictionary<TKey, TValue>` already provides such .ctors.  This is especially useful in the case where you want to make a copy of an `IReadOnlyDictionary<TKey, TValue>`
## Proposed API

``` csharp
  public class Dictionary<TKey, TValue> : ICollection, ICollection<KeyValuePair<TKey, TValue>>, IDictionary, IDictionary<TKey, TValue>, IEnumerable, IEnumerable<KeyValuePair<TKey, TValue>>, IReadOnlyCollection<KeyValuePair<TKey, TValue>>, IReadOnlyDictionary<TKey, TValue> {

    // New .ctors
    public Dictionary(IEnumerable<KeyValuePair<TKey, TValue>> enumerable);
    public Dictionary(IEnumerable<KeyValuePair<TKey, TValue>> enumerable, IEqualityComparer<TKey> comparer);


    // Existing .ctors
    public Dictionary();
    public Dictionary(IDictionary<TKey, TValue> dictionary);
    public Dictionary(IDictionary<TKey, TValue> dictionary, IEqualityComparer<TKey> comparer);
    public Dictionary(IEqualityComparer<TKey> comparer);
    public Dictionary(int capacity);
    public Dictionary(int capacity, IEqualityComparer<TKey> comparer);

     // Remaining members removed for brevity.
  }
```

See some additional discussion on this issue is at dotnet/coreclr#680

**Comment by sharwell** [comment]
You should also include this as a viable workaround for comparison:

```csharp
var dict = enumerable.ToDictionary(kvp => kvp.Key, kvp => kvp.Value);
```

**Comment by ellismg** [comment]
@sharwell Thanks!

**Comment by terrajobst** [comment]
We [reviewed this issue today](https://github.com/dotnet/apireviews/tree/master/2015-04-28-misc#1378-add-ienumerablekeyvaluepairtkey-tvalue-variants-to-dictionarys-ctors). It looks good as proposed.

**Comment by ellismg** [comment]
We'll need to wait for the code for the types to make it's way to github before doing this.

**Comment by matekm** [comment]
Hi guys,

I would like to take contribute some time for corefx and this issue looks nice as an introductory task. Will it be ok if I pick it up?

**Comment by karelz** [comment]
Sure, go ahead, I will assign it to you when your names shows up in contributors. In the meantime it's assigned to me.

cc: @Priya91 @ianhays

**Comment by matekm** [comment]
@karelz accepted the invite. Thanks!

**Comment by matekm** [comment]
Hi @karelz 

I had a time today to dive into this but I hit some minor wall.

When I add a IEnumerable constructor to src\System\Collections\Generic\Dictionary.cs and then try to test it in src\System.Collections\tests\Generic\Dictionary\Dictionary.Generic.Tests.cs I have a compilation error:


```
"C:\Development\dotnetopensource\src\System.Collections\tests\System.Collections.Tests.builds" (default target) (1) ->
"C:\Development\dotnetopensource\src\System.Collections\tests\System.Collections.Tests.csproj" (Build target) (2:4) ->
  Generic\Dictionary\Dictionary.Generic.Tests.cs(87,80): error CS1503: Argument 1: cannot convert from 'System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<TKey, TValue>>' to 'System.Collections.Generic.IDictionary<TKey, TValue>' [C:\Development\dotnetopensource\src\System.Collections\tests\System.Collections.Tests.csproj]
```

it just does not see the added constructor. From build logs I see:

`Resolved compile assets from .NETStandard,Version=v1.3: C:\Development\dotnetopensource\packages/System.Collections\4.0.11\ref\netstandard1.3\System.Collections.dll;C:\Development\dotnetopensource\packages/System.Diagnostics.Debug\4.0.11\ref\netstandard1.3\System.Diagnostics.Debug.dll`

so, as far as I understand, test use a dll from 'packages/System.Collections\4.0.11\ref\netstandard1.3\System.Collections.dll' which obviously don't have a new constructor.

Am I missing something? did I made a mistake on one of the build step? I would expect that test will refer to dll that was builded from the src/ directory.

btw: during the work I also modified the ref/System.Collections.cs - I added the constructors there. Is that correct?

**Comment by karelz** [comment]
@ianhays @Priya91 can you please help here?

The existing tests target netstandard1.3. You should not change that test project, but add a new one targeting netcorapp1.2 (which is where you add the API) -- some background: https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/adding-api-guidelines.md
Disclaimer: All my knowledge is theoretical so far, so I might be wrong. cc: @weshaggard

**Comment by karelz** [comment]
@matekm did you unassign the issue from yourself? (there's a known GitHub problem that changes are attributed to the OpenedBy person, so I can't say who did it)

Please unassign yourself only if you don't plan to work on it at all anymore. If you are just stuck, keep it assigned to yourself while you're getting help ...

**Comment by matekm** [comment]
@karelz thanks for pointing to the docs. Shame I missed them! And no, I didn't unassigned myself from that issue. Still want to work on it (yet I don't see an option to reassign it to me)!

**Comment by karelz** [comment]
Hmmm, something kicked you out of the contributors list :( ... I wonder if that's yet another sign of GitHub acting up today.
I'll add you again.

**Comment by matekm** [comment]
accepted again.

**Comment by karelz** [comment]
BTW: I pinged GitHub to find out what/why happened.

**Comment by Priya91** [comment]
> btw: during the work I also modified the ref/System.Collections.cs - I added the constructors there. Is that correct?

Yes that's correct. @matekm The api you are adding is very specific to netcoreapp1.1, and the tests have to be marked to be run only for netcoreapp1.1 profile. checkout how the ```Queue.Generic.Tests.netcoreapp1.1cs``` file is included in the test csproj. You should put your tests in a new file and include it only for netcoreapp1.1 profile in test csproj. And in your ref\System,Collections.cs file, you have to include the new apis under ifdef on netcoreapp11 build constant like [here](https://github.com/dotnet/corefx/blob/master/src/System.Collections/ref/System.Collections.cs#L374)

**Comment by matekm** [comment]
@Priya91 thanks, that helped me move forward. but now I have a ApiCompat errors:

```
:\Development\dotnetopensource\src\System.Collections\src\System.Collections.csproj" (default target) (1) ->
(ValidateApiCompatForSrc target) -> 
  C:\Development\dotnetopensource\Tools\ApiCompat.targets(68,5): error : MembersMustExist : Member 'System.Collections.Generic.Dictionary<TKey, TValue>..ctor(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<TKey, TValue>>)' does not exist in the implementation but it does exist in the contract. [C:\Development\dotnetopensource\src\System.Collections\src\System.Collections.csproj]
  C:\Development\dotnetopensource\Tools\ApiCompat.targets(68,5): error : MembersMustExist : Member 'System.Collections.Generic.Dictionary<TKey, TValue>..ctor(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<TKey, TValue>>, System.Collections.Generic.IEqualityComparer<TKey>)' does not exist in the implementation but it does exist in the contract. [C:\Development\dotnetopensource\src\System.Collections\src\System.Collections.csproj]
  C:\Development\dotnetopensource\Tools\ApiCompat.targets(82,5): error : ApiCompat failed for 'C:\Development\dotnetopensource\bin\AnyOS.AnyCPU.Debug\System.Collections\System.Collections.dll' [C:\Development\dotnetopensource\src\System.Collections\src\System.Collections.csproj]
```
any hints?

I compared my changes with a commit that introduced netcoreapp1.1 API (HashSet constructors and Queue methods) and I can't see any missing bits.

**Comment by Priya91** [comment]
@matekm For which configuration are the api-compat errors occuring? Can you share your working branch, it'll be easier to diagnose, not enough data in the pasted error..

**Comment by matekm** [comment]
@Priya91 

the branch is here: https://github.com/dotnet/corefx/compare/master...matekm:1378_dictionary_ienumerable_ctor

and the commit with all the changes is here:

https://github.com/matekm/corefx/commit/8baa4ab78282dbe1ea75c4d722025077f6d576a4

**Comment by weshaggard** [comment]
The Dictionary class you updated is only used in the uap10.1 build configuration https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System.Collections.csproj#L76. For netcoreapp1.1 the Dictionary implementation is actually in System.Private.CoreLib in the coreclr repo, https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/Dictionary.cs. That will need to be updated first before you can update the reference assembly in corefx.

**Comment by danmosemsft** [comment]
No longer up for grabs, @matekm has it.

**Comment by matekm** [comment]
@danmosemsft @Priya91 code was commited to coreclr,  should the dependency be updated manually or dotnet-bot will pick that up?

**Comment by danmosemsft** [comment]
I believe https://github.com/dotnet/corefx/pull/13802 needs to merge.

**Comment by matekm** [comment]
just a quick update because I was silent for 7 days. I am still interested in fixing that issue. Just didn't found any time previous week to do it. Hopefully will find some time this week!

**Comment by karelz** [comment]
Thanks for the update @matekm!

**Comment by ianhays** [comment]
resolved by @matekm in https://github.com/dotnet/corefx/pull/14656
