### ISSUE TITLE
CGI error in azure when using HttpClient with ServerCertificateCustomValidationCallback in Azure

### ISSUE THREAD

**Issue by ajtowf** [dotnet/corefx#13794]
Can't post to an API using client certificate with custom certificate validation from my backend when upgradring to netcore 1.1. This works absolutely fine locally and it works when posting to an https endpoint that has a cert signed by a trusted CA. Worth mentioning is that this worked with the 1.1 preview. Now I get this once deployed to azure:

    The specified CGI application encountered an error and the server terminated the process.

The code:

    X509Certificate2 cert = ... read from store
    var handler = new HttpClientHandler();
    handler.ClientCertificates.Add(cert);
    handler.ServerCertificateCustomValidationCallback += (message, certificate2, arg3, arg4) => true;

    var httpClient = new HttpClient(handler);
    await httpClient.PostAsync(theUrl, theContent);

Then it just dies, nothing in the logs. Any ideas?

**Comment by ajtowf** [comment]
## Update

The following works:

    var clientHandler = new HttpClientHandler();
    var httpClient = new HttpClient(clientHandler);
    await httpClient.PostAsync("https://httpbin.org/post", new StringContent(string.Empty));

But this fails:

    var clientHandler = new HttpClientHandler();
    clientHandler.ServerCertificateCustomValidationCallback += (message, certificate2, arg3, arg4) => true;
    var httpClient = new HttpClient(clientHandler);
    await httpClient.PostAsync("https://httpbin.org/post", new StringContent(string.Empty));

So the client cert seems not to be the issue, but as soon as I add a delegate to ServerCertificateCustomValidationCallback the app crashes with "The specified CGI application encountered an error and the server terminated the process."

Very easy to reproduce, I'm deploying to a completely new azure website as well so there is nothing left from previous releases.

**Comment by ajtowf** [comment]
## Update 2

So I've isolated the problem to if I read a certificate from the cert store and then register a delegate for validating the certificate the app crashes.

    using (var certStore = new X509Store(StoreName.My, StoreLocation.CurrentUser))
    {
        certStore.Open(OpenFlags.ReadOnly);
        var certCollection = certStore.Certificates.Find(X509FindType.FindByThumbprint, "<thumb>", false);
        certificate = certCollection[0];                
     }

I don't even have to use the certificate, it's enough to read it from the store. And yes the cert is loaded, I can debug it, everything looks fine. Am I missing something fundamental here?

**Comment by stephentoub** [comment]
@ajtowf, thanks for the report. Do you know what OS this is?  And is it actually crashing, or is an exception getting thrown that you could catch and share the details of?

cc: @bartonjs

**Comment by ajtowf** [comment]
Since the CGI program crashed this isn't something that can be catched, doesn't matter if I wrap it in try/catch. Anyways what I ended up doing was to load the file from disk instead of reading it from the store. That will do for now, I'll close this bug. Cheers!

**Comment by ajtowf** [comment]
Sorry forgot to answer your question, it's windows locally, but it works on locally, the problem occurred when deployed to azure website.

**Comment by stephentoub** [comment]
Thanks, @ajtowf.  I reopened it because if the code is actually crashing (e.g. an AV, seg fault, etc.), that's something we'd want to investigate.

**Comment by bartonjs** [comment]
* Windows
* .NET Core 1.1
* Crashes after reading a cert from the store, but not from a file

Sounds like an R2R bug under investigation: https://github.com/dotnet/coreclr/issues/8148

If anyone agrees we can probably close this one

**Comment by stephentoub** [comment]
Thanks, Jeremy.  Sounds like the same issue.  We can close this one.
