### ISSUE TITLE
Two interop methods missed

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#13808]
These are in standard but didn't make it into https://github.com/dotnet/corefx/pull/13479.

```
namespace System.Runtime.InteropServices {
    public static class Marshal {
        public static string PtrToStringAuto(IntPtr ptr, int len);
    }
```

**Comment by shrah** [comment]
https://github.com/dotnet/corefx/pull/13811

**Comment by kouvel** [comment]
Moved `Marshal.CleanupUnusedObjectsInCurrentContext` to issue #11638, that is covered by PR #13722. @shrah, you have use this issue for your PR.

**Comment by shrah** [comment]
Merged https://github.com/dotnet/corefx/pull/13811
