### ISSUE TITLE
Proposal: Make it easier to use StringComparison & StringComparer with GetHashCode.

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#13800]
## Proposed API

1. Add API to convert a `StringComparison` to a `StringComparer`, to avoid bunch of switch-statements in user code (see 'Motivation' section below).
2. Add `string.GetHashCode(StringComparison)` API, to make it easier/more discoverable to get the culture-dependent, case-insensitive, etc. hash of a string. Currently, you have to do `StringComparer.XXX.GetHashCode(str)`, which is verbose & hard to find.

```c#
public class StringComparer
{
    public static StringComparer FromComparison(StringComparison comparisonType);
}

public sealed class String
{
    public int GetHashCode(StringComparison comparisonType);
}
```

### Motivation

If someone has a variable comparison they don't have to do a bunch of switch-cases (we'll do them instead):

```c#
    public static StringComparer FromComparison(StringComparison comparisonType)
    {
        switch (comparisonType)
        {
            case StringComparison.Ordinal:
                return StringComparer.Ordinal;
            case StringComparison.OrdinalIgnoreCase:
                return StringComparer.OrdinalIgnoreCase;
                ...
        }
    }
```

For more background: See @stephentoub's suggestion in https://github.com/dotnet/corefx/issues/8034#issuecomment-261519913

cc @justinvp @Elion

**Comment by svick** [comment]
How is `StringComparer.Ordinal.GetHashCode(str)` more verbose than `str.GetHashCode(StringComparison.Ordinal)`, when it's 2 characters shorter?

**Comment by justinvp** [comment]
> How is StringComparer.Ordinal.GetHashCode(str) more verbose than str.GetHashCode(StringComparison.Ordinal), when it's 2 characters shorter?

I think it's more about discoverability. Not everyone knows that you can use `StringComparer` to get a hash code. I've seen a bunch of uses of `text.ToLowerInvariant().GetHashCode()` when `StringComparer.OrdinalIgnoreCase.GetHashCode(text)` would have been better.

**Comment by JonHanna** [comment]
To be honest, I do know that you can use `StringComparer` that way, and I still forget sometime and go through a case transform.

**Comment by jamesqo** [comment]
@svick Another thing to mention is that `str.GetHashCode(StringComparison.Ordinal)` has less dots, so you have to hit Enter less in VS.

**Comment by svick** [comment]
@jamesqo I count 2 dots in `StringComparer.Ordinal.GetHashCode(str)` and 2 dots in `str.GetHashCode(StringComparison.Ordinal)`. 😉

**Comment by jamesqo** [comment]
@svick Sorry, my logic was faulty yesterday :smile: I was trying to say that, with an instance method, once you type `GetHashCode(` VS will detect that the method accepts an enum & will offer autocomplete for `StringComparison`. Whereas, with the current scenario, you need to type at least up to `StringC` before VS guesses `StringComparer`, otherwise you need to move the selection down.

Anyway, @justinvp's argument is the more important one. Regardless if one version is 2 characters shorter, it needs to be easier for a newbie to discover how to do these things by looking at the methods on `String`, instead of scouring the whole `System` namespace.

**Comment by jnm2** [comment]
Is there any reason that it shouldn't be better to encourage people to be hanging onto `IComparer<string>` in the first place rather than `StringComparison`?

**Comment by jamesqo** [comment]
@jnm2 I see your point. If we accepted an `IEqualityComparer<string>`, however, it would not help with discoverability since people would have no way of knowing to plug in a `StringComparer`.

**Comment by jnm2** [comment]
@jamesqo `<see cref="StringComparer"/>`?

**Comment by jamesqo** [comment]
@jnm2 An XML doc comment does not help much-- some people might not read it. Besides, if you already have a `StringComparer` you can do `_yourComparer.GetHashCode(str)` whereas that is not the case with `StringComparison` (with this proposal, you'd need to write `StringComparer.FromComparison(_comparison).GetHashCode(str)` which is kinda verbose).

**Comment by AlexGhiondea** [comment]
@jamesqo I think this makes sense. Marking ready for review.

**Comment by karelz** [comment]
FYI: Top post reformatted to match "formal API proposal" form - it is easier to read and comprehend in reviews.

**Comment by terrajobst** [comment]
Looks good as proposed.

**Comment by AlexRadch** [comment]
@karelz I am working on this issue.

**Comment by karelz** [comment]
We still need tests

**Comment by karelz** [comment]
The PR #14623 seems to be abandoned. Unassinging the issue - it is "up for grabs" again, available for anyone to pick it up and finish it.

**Comment by karelz** [comment]
@MikevanDongen I am sent you contributor invite - once you accept, we can assign this issue to you.
In future, please ping issues when you grab them, so that others know as well. Thank you!

**Comment by danmosemsft** [comment]
@karelz @MikevanDongen this issue also tracks exposing `String.GetHashCode(StringComparison comparisonType);` from CoreCLR, which I see was implemented. @MikevanDongen do you plan to put up another PR to expose that one?

/cc @stephentoub re unexposed API.

**Comment by MikevanDongen** [comment]
I don't mind doing so (later this week).

-------- Original Message --------

**Comment by danmosemsft** [comment]
@MikevanDongen this API is approved to go in so long as the PR is committed before 5/10 when we fork off. After that it would need shiproom ok which might not happen. Just let us know if you don't think you'll be able to get to it soon enough and maybe we can find someone. Thanks :)

@karelz

**Comment by karelz** [comment]
Let's keep it unassigned, until someone grabs that up. Whoever picks it up, please comment here .... first commenter wins the issue ;-)

**Comment by danmosemsft** [comment]
Maybe @hughbe would like the honor of creating a method on String...

**Comment by jnm2** [comment]
What's left to do, add String.GetHashCode to `src\System.Runtime\ref\System.Runtime.cs` and put tests on it in `src\System.Runtime\tests`?

**Comment by jnm2** [comment]
I can't find StringComparer in `src\System.Runtime\ref\System.Runtime.cs`. Where is that exposed?

**Comment by jnm2** [comment]
<s>I can't find StringComparer in `src\System.Runtime\ref\System.Runtime.cs`. Where is that exposed?</s>

[Found it.](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs#L896)

**Comment by jnm2** [comment]
Almost done writing tests, so I guess I'll take this. :-p

**Comment by jnm2** [comment]
https://github.com/dotnet/corefx/pull/19443

**Comment by karelz** [comment]
Thanks @jnm2!

**Comment by hughbe** [comment]
Thanks for taking this on! Although dan suggested I give it a go I wouldn't be able to find time before ZBB so it's awesome to see
