### ISSUE TITLE
System.IO.File.Copy() provides an incorrect error message when destination directory does not exist

### ISSUE THREAD

**Issue by jhclark** [dotnet/corefx#13806]
**Problem:** System.IO.File.Copy() provides an incorrect error message when destination directory does not exist
**Proposed solution:** Edit https://github.com/dotnet/corefx/blob/c55435befeb372707558a5c441b3c64bf243948f/src/Common/src/System/IO/Win32Marshal.cs#L61 to check whether it's the source or dest path that doesn't exist when creating an error message.

**Problem description from colleague's email**

My debugging moment of the day today was brought to me by a bad .NET exception message.  Running the following code which copies an existing file into a dir that doesn’t exist:

var src = @"c:\Exists\train.log";
var dest = @"c:\DoesntExist\train.log";
File.Copy(src, dest, true);

And you get a nice error message out:

DirectoryNotFoundException: Could not find a part of the path 'c:\Exists\train.log'.

Hey, what the who?  Changing dest to an actual path works like a champ. (Note that if you hit an access denied on the dest, the exception text is correct.)

***Investigation into source code***

I believe the exception was thrown from here:

https://github.com/dotnet/corefx/blob/c55435befeb372707558a5c441b3c64bf243948f/src/System.IO.FileSystem/src/System/IO/Win32FileSystem.cs#L19

And generated by this win32 to exception converter:

https://github.com/dotnet/corefx/blob/c55435befeb372707558a5c441b3c64bf243948f/src/Common/src/System/IO/Win32Marshal.cs#L61

The problem appears to be that the win32 error code doesn’t distinguish between src and tgt paths not existing, and the exception generator assumes it’s the source. Oops.

**Comment by ianhays** [comment]
Thanks for finding this, @jhclark! I'm marking this as "up for grabs", so you (or anyone else) feel free to work on it :)

It would probably be a good idea to add a test to [File.Copy](https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/tests/File/Copy.cs) for this case, as well.

**Comment by reaction1989** [comment]
I tried to reproduce that wrong Exception but i could not
``` C#
 public static void Main(string[] args)
        {
            try
            {
                File.Copy(@"C:\Temp\a.txt", @"C:\Temp\NotExistent\a.txt", true);
            }
            catch(Exception e)
            {
                Console.WriteLine(e);
            }

        }
```
And the output is the following:

> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Temp\NotExistent\a.txt'.
   at System.IO.Win32FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at ConsoleApplication.Program.Main(String[] args) in C:\Source\consoletest\Program.cs:line 13


@jhclark I was trying to reproduce it with .net core 1.1 Which version were you using?

**Comment by ianhays** [comment]
I looked into this more in depth. We make a best-effort to determine whether the source of destination path was the one that produced the error, but in some circumstances we cannot without fail say which is the incorrect one. In that case, the source path is the one passed to the exception generator. That's why the repro in the comment above failed but the OP hit the issue.

I'm closing this, as the comment [here](https://github.com/dotnet/corefx/blob/c55435befeb372707558a5c441b3c64bf243948f/src/System.IO.FileSystem/src/System/IO/Win32FileSystem.cs#L36) addresses the issue well already. Although it's not perfect, it's a good solution for most cases. Anyone feel free to reopen this issue if you have a better solution in mind.
