### ISSUE TITLE
System.Net.Security.SslStream error on AuthenticateAsClientAsync

### ISSUE THREAD

**Issue by bottomup** [dotnet/corefx#13814]
Since the upgrade from ASP.NET Core 1.0.1 to 1.1.0, my application breaks on AuthenticateAsClientAsync, which is used in MailKit.SmtpClient.Connect by @jstedfast 

The only feedback the appication gives is 
An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in System.Windows.ni.dll

I'm connecting to smtp.sendgrid.net

**Comment by blowdart** [comment]
@bartonjs ?

**Comment by bartonjs** [comment]
@bottomup A TargetInvocationException frequently has an inner exception to go with it.  do you have a full exception report, including any inner exception(s)?

**Comment by bottomup** [comment]
Unfortunately not very useful. The innerexception is this:
System.ExecutionEngineException was unhandled
Message: An unhandled exception of type 'System.ExecutionEngineException' occurred in System.Private.CoreLib.ni.dll

**Comment by bartonjs** [comment]
Ah, then I think you've run into dotnet/coreclr#8148. As a way to confirm you can change your debugger launch settings to set the  COMPlus_ReadyToRunExcludeList  enviornment variable to  System.Security.Cryptography.X509Certificates . If the exception(s) go away then that's the culprit.

**Comment by bottomup** [comment]
@bartonjs this indeed 'fixed' the problem! I guess this will be addressed in the 1.2.0 milestone?

**Comment by bottomup** [comment]
@bartonjs however the problem persists when deploying to Azure, any idea where I can force that behavior there?

**Comment by bottomup** [comment]
@bartonjs found it in Azure, and this also solved the issue there. Thanks for the suggestion.

**Comment by janaks09** [comment]
@bottomup  How did you fixed that on Azure? I am unable to make it work on Azure.

**Comment by bottomup** [comment]
@janaks09 in the application settings of your app service, add the following:
Key: COMPlus_ReadyToRunExcludeList
Value: System.Security.Cryptography.X509Certificates

**Comment by janaks09** [comment]
@bottomup tried that but it still throws CGI error

`The specified CGI application encountered an error and the server terminated the process.`

**Comment by bottomup** [comment]
@janaks09 then I guess you probably are experiencing some different issue, the error is very general and could even be an out-of-memory exception

**Comment by janaks09** [comment]
@bottomup ya could be. I will check that. Thanks

**Comment by joezen777** [comment]
Link for anyone wondering how to add the environment variables to IIS. http://stackoverflow.com/questions/31049152/publish-to-iis-setting-environment-variable/36836533#36836533
