### ISSUE TITLE
100% CPU load

### ISSUE THREAD

**Issue by dvdobrovolskiy** [dotnet/corefx#13837]
After upgrade to 1.1.0 I have an issue then dotnet process start to load CPU on 100%. I have a pretty standard several application where and had no problem but not from time to time it goes in 100% and hangs whole server.

After killing dot net it starts again and works pretty normal. Also this issue is happened when I (nobody) do not web apps. When I work with this webapps all pretty normal but then I do not touch them for several hours it starts loading CPU

**Comment by karelz** [comment]
You will need to enable CPU profiler to find out where the time is spent.

**Comment by dvdobrovolskiy** [comment]
Easy to say. machine is almost unavailable then it happens. Will try.

**Comment by karelz** [comment]
Enable sampling production profiling prior to the issue (e.g. [PerfView](https://channel9.msdn.com/Series/PerfView-Tutorial) on Windows).
It should be fairly simple and it is useful skill to gain. It is also the only way to find out details systematically.

cc: @vancem @brianrob

**Comment by dvdobrovolskiy** [comment]
Giving up. Rolling back to 1.0.1

Problem happens only on production server and blocks it completely. I barely can kill dotnet process.

**Comment by karelz** [comment]
Can you profile your test environment and compare 1.0.1 vs. 1.1.0?

**Comment by karelz** [comment]
Also, if you want to increase the chance that the problem is gone in 1.2 and future releases, then we will need to know what regressed (i.e. you need to profile your environment). When you have more data, please reopen the issue.

**Comment by dvdobrovolskiy** [comment]
1.0.1 Works fine. Published 1.1.0 to Virtual machine and also fine. Some nasty combination of my production server and new feature in 1.1.0 I believe. I unfortunately limited in experiment on a production server in which server goes 100% load. 

Will clone in and test in near future

**Comment by karelz** [comment]
@brianrob @vancem can you please help with production-level settings of PerfView to collect perf trace?

**Comment by danmosemsft** [comment]
If it's Windows server then [Azure Service Profiler](https://www.azureserviceprofiler.com/) may be convenient.

**Comment by vancem** [comment]
Fundamentally, we need data when things go bad.   As @danmosemsft indicates, on Windows you can use Service Profiler.   Also on Windows you can use PerfView if you log onto the machine.    see 
     https://blogs.msdn.microsoft.com/vancem/2016/11/02/performance-analysis-on-net-core-applications-with-perfview-on-windows/ 
   
On Linux you can also collect profiling data using the Linux 'Perf' tool  
    https://blogs.msdn.microsoft.com/vancem/2016/10/07/collecting-performance-data-on-linux-using-perfcollect-and-perfview/ 

But fundamentally we need some data to figure out just what is consuming the time in order to have any shot at fixing it.
