### ISSUE TITLE
New System.Math decimal versions

### ISSUE THREAD

**Issue by varocarbas** [dotnet/corefx#13834]
First thing to note is that I already submitted [another issue](https://github.com/dotnet/corefx/issues/6308) on similar lines, which was reviewed and (not completely) rejected. I have taken all that feedback into account to make this new proposal, which only consists in the following inclusions:

```C#
public const decimal PI_dec = 3.1415926535897932384626433832m;
public const decimal E_dec = 2.7182818284590452353602874713m;   
public decimal Pow(decimal x, decimal y); 
public decimal Sqrt(decimal d);
```

The algorithms of the new `Pow`/`Sqrt` overloads are expected to exclusively rely on the `decimal` type (i.e., no conversion to/from `double`/`float` at any point).  In fact, I have recently finished the first version of an open source library (NumberParser) precisely including two methods fulfilling that requirement. Note that, additionally to [its properly-commented C# source code](https://github.com/varocarbas/FlexibleParser/tree/master/all_code/NumberParser/Source), I also wrote [detailed explanations about the implementation of those two methods](https://varocarbas.com/fractional_exponentiation). I am even planning to write much more explanations about this whole code within the short term. 

Anyone can use this library and test the aforementioned methods (```Math2.PowDecimal```/```Math2.SqrtDecimal```) to get a feeling of what the proposed new overloads might deliver.  In any case, the following ideas should be clear:
- These methods rely on a custom class (```Number```), whose main goal is allowing to deal with very big ranges of values. It is certainly much less efficient than the native ```decimal```/```double``` types.
- In case of deciding to go ahead with this proposal and additionally to perform the aforementioned adaptation, I am also planning to further optimise these algorithms. Nevertheless and even in the best scenario, the new ```decimal``` version is likely to be slower than the ```double``` one (perhaps also in case that it would also include the corresponding conversions from/to ```decimal```, although I am still not sure about this). Its strongest point will be accuracy, rather than speed.
- The current version of this approach accounts only for the first 25 decimal digits of the exponent (note that the `decimal` type can deal with up to 28). In principle, I don’t see this as a problem, although I look forward to your opinions on this front.

In summary, the new overloads are expected to avoid the floating-point/limited-precision problems associated with converting from/to ```double```; to deliver accurate results (up to `5e-28m`) not constrained by simplifications/floating-point restrictions.

As highlighted in the review of my previous proposal, there is a backwards-compatibility problem associated with adding these new overloads without any further modification: calls relying on implicitly convertible types will stop working. For example: ```System.Math.Pow(1, 10) ``` (i.e., two ```int``` variables implicitly converted to ```double```) works fine now, but will not work after just adding the proposed ```decimal``` overload. There are two ways to address this problem:
- Including additional overloads with all the implicitly convertible types, consisting in simple calls to the `double` ones. For example:
```C#
public static double Pow(int x, int y)
{
    return Pow((double)x, (double)y);
}
```
- Adding two new methods rather than overloads to existing ones (e.g., ```PowExact```/```SqrtExact```).

In principle, the first alternative seems better, although it would imply accounting for a quite relevant number of scenarios (e.g., `Pow(int x, int y)`, `Pow(int x, long y)`, `Pow(int x, ulong y)`, etc.).

**Comment by karelz** [comment]
The first option (adding overloads with `int`) would bloat to all types (`short`, `long`, etc.), right? ... That's kinda ugly.
The second option of using different names is really weird.

Overall we believe that `Math` class is pretty crowded already. We had to add `MathF` recently.
Maybe we should just wait for your library to pick up some interest (which will also validate your assumption that 25 digits is enough). If there is growing interest in `decimal` arithmetic, we can consider adding it into BCL later ...

**Comment by varocarbas** [comment]
> validate your assumption that 25 digits is enough

Note that I am talking about the exponent, that it is pretty close to the `decimal` limit (28) and that the current `double` based approach plainly ignores everything after the 15th decimal position (getting so far isn't even required because some digits before that point are already wrong in most of scenarios). As said, I don't see this as a problem (although the current version is a bit too slow and some improvements there seem required).

> your library to pick up some interest

By bearing in mind my promotional approach (= none), this library is very unlikely to trigger a big interest. Note that the whole point of it (and FlexibleParser, where it is included) is showing my programming skills to a knowledgeable and keen-on-properly-analysing-the-code-and-presumably-small audience. I wouldn't mind a high number of people plainly using it, but I will certainly not do any effort to provoke such a reality to become true.

In any case, I understand your position and wouldn't find any problem with you deleting this issue.

**Comment by varocarbas** [comment]
@karelz 
> validate your assumption that 25 digits is enough

Note that I am talking about the exponent, that it is pretty close to the `decimal` limit (28) and that the current `double` based approach plainly ignores everything after the 15th decimal position (getting so far isn't even required because some digits before that point are already wrong in most of scenarios). As said, I don't see this as a problem (although the current version is a bit too slow and some improvements there seem required).

> your library to pick up some interest

By bearing in mind my promotional approach (= none), this library is very unlikely to trigger a big interest. Note that the whole point of it (and FlexibleParser, where it is included) is showing my programming skills to a knowledgeable and keen-on-properly-analysing-the-code-and-presumably-small audience. I wouldn't mind a high number of people plainly using it, but I will certainly not do any effort to provoke such a reality to become true.

In any case, I understand your position and wouldn't find any problem with you deleting this issue.

**Comment by karelz** [comment]
> this library is very unlikely to trigger a big interest

I think that if the APIs are truly needed, then it has a chance to trigger interest, or at least alternative libraries solving similar problem will spin off. Either way, it is a good way to test the waters if the API is needed enough to justify its addition to CoreFX.

Closing per discussion above.
