### ISSUE TITLE
InstalledUICultureTest fail if Windows language is changed

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/corefx#13832]
I have Windows 10 (non english) after I changed it language to  English (USA) and restart it, my Windows  UI interface changed to english.

After that `System.Globalization.Tests.CultureInfoMiscTests.InstalledUICultureTest` in `corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\XsltCompiler.Tests.csproj` project failed.

I think this test is wrong because it will fail if window language is changed after installation.
```cs
Assert.Equal(CultureInfo.CurrentUICulture, CultureInfo.InstalledUICulture);
```

**Comment by danmosemsft** [comment]
@AlexRadch you're welcome to submit a PR if you get to it before @sepidehMS does.

**Comment by AlexRadch** [comment]
@danmosemsft I do not know how to fix this test. It should check than `current thread  UI culture` is equal to `current user UI culture`. Now it checks that `current thread UI culture` is equal to `windows system UI culture` with can be different from `current user UI culture` if user changed language after windows installation. On one computer different users can have different language settings.

Now standard library (and dotNet Framework) does not have method to get `current user UI culture`. But have property `DefaultThreadCurrentUICulture`, may be this  property should be used in test instead of `InstalledUICulture`.

**Comment by danmosemsft** [comment]
@tarekgh

**Comment by AlexRadch** [comment]
I think we should add UserUICulture property into CultureInfo class.
UserUICulture should be like InstalledUICulture but return culture not for GetSystemDefaultUILanguage but for GetUserDefaultUILanguage.

**Comment by AlexRadch** [comment]
I made PR https://github.com/dotnet/coreclr/pull/8276 in coreclr to resolve this issue.

**Comment by svick** [comment]
@AlexRadch That's not how it works. If you want to propose adding a new API to .Net Core, you need to go through [the API review process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md), which means first writing an issue containing "speclet" of the proposed API in this repo (even if it's "just" changing some `internal` methods to `public`).

(And then actually making the change is more complicated than just changing the code.)

**Comment by tarekgh** [comment]
I am seeing System.Globalization.Tests.CultureInfoMiscTests.InstalledUICultureTest is in System.Globalization\tests\CultureInfo tests and not in fx\src\System.Private.Xml\tests\Xslt\XsltCompiler\XsltCompiler.Tests.csproj. 

I'll take care with this test.

I have closed the PR in coreclr because as @svick mentioned if you propose a new API, it has to go through the mentioned process.

why you think exposing UserDefaultCulture is useful? could you please tell what is your scenario need this? note that this will not make any sense in the UWP apps at all because of the app model of WinRT.
