### ISSUE TITLE
System.Security.Cryptography.Algorithms.Tests fail ExpectedSignature_SHA1_384 test

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/corefx#13849]
On my Windows 2012 server `System.Security.Cryptography.Algorithms.Tests` project fail `ExpectedSignature_SHA1_384` test with exception `Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Requested operation is not supported`.

**Comment by karelz** [comment]
If the tests are not supported on particular platform, then either they should be disabled on the platform, or they should expect PlatformNotSupport exception on the platform.
@bartonjs @steveharter any guidance here?

**Comment by bartonjs** [comment]
Described in #13850, and the same fix will fix both.  Closing as dupe.
