### ISSUE TITLE
Improve AsyncLocal throughput and memory usage (port to Desktop)

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#13856]
Consider porting https://github.com/dotnet/coreclr/pull/8216 and https://github.com/dotnet/coreclr/commit/9bc06f7e534a1989911d795528737d767c2b408d to Desktop

**Comment by karelz** [comment]
@AlexGhiondea can we close it right away? (i.e. does your tooling work on Closed issues) Or do we have to wait for your tooling to kick in?

**Comment by ericstj** [comment]
Should also look at https://github.com/dotnet/coreclr/commit/9bc06f7e534a1989911d795528737d767c2b408d.  Both are relevant to folks using AsyncLocal on desktop.

**Comment by AlexGhiondea** [comment]
@karelz the tool looks at all issues, regarding of state and creates the tracking bugs. We can close this.

**Comment by karelz** [comment]
Perfect, thanks for confirmation. Will try to remember it for future :)
