### ISSUE TITLE
System.Security.Cryptography.Cng.Tests fails two tests

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/corefx#13850]
On my Windows 2012 server `System.Security.Cryptography.Cng.Tests` project fails two tests: `ExpectedSignature_SHA1_384` and `RSACng_Ctor_UnusualKeysize_384` with the same exception `Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Requested operation is not supported`.

**Comment by vcsjones** [comment]
Can you show the output of `RuntimeInformation.OSDescription` in your environment?

RSA-384 isn't supported on all platforms, so the test tries to ignore the failure if it things your platform doesn't support RSA-384 by examining `RuntimeInformation.OSDescription`. I suspect perhaps your output is different or localized.

**Comment by AlexRadch** [comment]
@vcsjones I think Windows Server 2012 have "Windows 6.2" as OSDescription and Windows Server 2012 R2 have have "Windows 6.3" as OSDescription. I will check it exactly tomorrow at work.

**Comment by karelz** [comment]
If the tests are not supported on particular platform, then either they should be disabled on the platform, or they should expect the PlatformNotSupport exception on the platform.
@bartonjs @steveharter any guidance here?

**Comment by bartonjs** [comment]
We currently say it has expected failure on Windows 7, and expected pass on Windows 8.1 (2012 R2).  It's possible we don't have Windows 8 (2012) in our CI matrix, so we've never noticed the failure.

It just means that https://github.com/dotnet/corefx/blob/681d85aa63891a63be928d29667cd3fc0f6c966c/src/System.Security.Cryptography.Cng/tests/RSACngProvider.cs#L27-L33 needs to also detect Windows 8 / Server 2012 as a "false" case.

**Comment by karelz** [comment]
Should be simple to fix - @AlexRadch do you want to grab it?

**Comment by AlexRadch** [comment]
I made PR https://github.com/dotnet/corefx/pull/13883 for this issue
