### ISSUE TITLE
Add methods to StringBuilder to append ReadOnlySpan<char>

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#13869]
## Background

It seems logical that we should support appending `Span<char>` and `ReadOnlySpan<char>` to a StringBuilder, since the point of both data types is to reduce allocations. The only way to do this with the current APIs is to loop through the span one char at a time and call Append on each of them, which is pretty slow.

## Proposed API

```cs
namespace System.Text
{
    public sealed class StringBuilder
    {
        // Span is implicitly convertible to ReadOnlySpan
        public StringBuilder Append(ReadOnlySpan<char> value);
    }
}
```

cc @jkotas, @KrzysztofCwalina, @justinvp

**Comment by jkotas** [comment]
We would need to move Span to System.Runtime contract to make this work.

Enhancing existing types with Span overloads is in the grand plan, but it is probably too early for it at this point.

**Comment by jamesqo** [comment]
@jkotas I see. I'll keep this proposal open for when `StringBuilder` is able to reference `Span`, then.

**Comment by karelz** [comment]
Wouldn't it be better to track a larger issue with all/most of the APIs extensions we want?
Tracking one offs does not seem to be very effective ...

**Comment by karelz** [comment]
Tracking it in general issue (see above) - closing this one
