### ISSUE TITLE
Add Transactional support file sytem.

### ISSUE THREAD

**Issue by kronic** [dotnet/corefx#13884]
Add transactional support for files and directories;

**Comment by ianhays** [comment]
@kronic please take a look at our [Api Review Process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md) to get an idea of the process for adding new API. Generally we look for a detailed post with the proposed API, use cases, and some examples of the desired functionality to stir up discussion. You can look at [some of our approved API to use as a guide](https://github.com/dotnet/corefx/issues?q=is%3Aissue+label%3Aapi-approved+is%3Aopen).

I'm closing this issue for now. Feel free to re-open it with the above.
