### ISSUE TITLE
Where is dotnet-bot commands documentation?

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/corefx#13882]
I want rerun tests for PR but can not find dotnet-bot command for this.
Where is dotnet-bot commands description?

**Comment by danmosemsft** [comment]
@dotnet-bot help

**Comment by danmosemsft** [comment]
Well, that's supposed to print help. Meantime, the trick is to do `@dotnet-bot` followed by `test` followed by the leg name copy and pasted eg `Innerloop OSX Debug Build and Test`. Or to retest everything miss the leg.

**Comment by danmosemsft** [comment]
@mmitche the help command didn't work

**Comment by JonHanna** [comment]
I think @dotnet-bot help only works in PRs as it delegates helping people in issues to the human contributors.

**Comment by mmitche** [comment]
@danmosemsft Yeah it only tracks PRs.

**Comment by karelz** [comment]
And we should have it documented in our contribution guide ... I'll take care of that in my larger sweep of the docs next month.

**Comment by AlexRadch** [comment]
@karelz It will be nice if https://github.com/dotnet-botpage will have link on dotnet-bot commands description also.

**Comment by karelz** [comment]
Which link? The you posted above is inaccessible. How does a new contributor find out about the page?

**Comment by AlexRadch** [comment]
@karelz dotnet-bot page https://github.com/dotnet-bot have a link to dotnet blog http://blogs.msdn.com/b/dotnet/.
I suggest to add link to dotnet-bot commands description.

**Comment by JonHanna** [comment]
You can also find it by clicking on @dotnet-bot whenever they are mentioned

**Comment by MarcoRossignoli** [comment]
found this helpful link https://github.com/Microsoft/ChakraCore/wiki/Jenkins-CI-Checks
