### ISSUE TITLE
Consider making ImmutableArray<T>.SyncRoot throw NotSupportedException

### ISSUE THREAD

**Issue by sharwell** [dotnet/corefx#1390]
Currently `ImmutableArray<T>` (a value type) returns `this` in its implementation of `ICollection.SyncRoot`. I believe a more appropriate implementation would be to throw `NotSupportedException`, a behavior which would match the collections in `System.Collections.Concurrent`.

**Comment by stephentoub** [comment]
I agree, the current implementation is not a good place to be.  And if I'm reading it correctly, the comment in the implementation justifying it also looks wrong, e.g. this
```C#
ICollection c = (ICollection)ImmutableArray.Create(1, 2, 3);
Console.WriteLine(Object.ReferenceEquals(c.SyncRoot, c.SyncRoot));
```
will print out false, even though the array is only being boxed once (the comment seems to indicate that once the array is boxed, its SyncRoot will return that boxed object).

While array itself is immutable, folks use SyncRoots to protect more than just mutations to the collection itself, but if anyone tries that with ImmutableArray's SyncRoot, they're going to silently introduce race conditions into their program, as every lock site will end up locking on a different instance.

And from the various alternatives (returning null, throwing a NotSupportedException, returning the underlying array, storing an extra field just to maintain a SyncRoot object, etc.), I agree with @sharwell that throwing NotSupportedException is the best option.

@terrajobst?  @AArnott?

**Comment by AArnott** [comment]
Agreed
