### ISSUE TITLE
Span: Add Span<T>.Clear()

### ISSUE THREAD

**Issue by nietras** [dotnet/corefx#13915]
As discussed in https://github.com/dotnet/corefx/issues/13427 we would like to add a `Clear()` method to `Span<T>` to make span the goto place for safe and fast memory operations.

### Rationale and Usage
Provide a safe yet fast way of clearing (settings memory to zero) for any type of contiguous memory; managed or unmanaged.

```csharp
var span = new Span<T>(array, 3, 10);
span.Clear();
```

### Proposed API
Add a single method `Clear()` to the existing `Span<T>` API e.g.:
```csharp
public class Span<T>
{
     public void Clear();
}
```

### Details
For reference free value types this can forward directly to `Unsafe.InitBlock`, see https://github.com/dotnet/corefx/issues/13427, but should otherwise try to be optimal, so this function can be used as the reference implementation for all such usages in .NET. That's the vision at least, in my mind.

### Open Questions
Open question is whether the `InitBlock` should be generic to match Span usage, or `Span<T>` should handle forwarding to a `ref byte` version of this.

@jkotas @omariom @benaadams @karelz @jamesqo @davidfowl

**Comment by jkotas** [comment]
> This will forward directly to `Unsafe.InitBlock`

It cannot just forward to `Unsafe.InitBlock` for types that contain GC references. The GC requires the pointers to be cleared atomically and InitBlock does not make this guarantee. It makes for a super hard to trace down crashes in the background GC. We have been there - somebody spent like a month of their life to trace it down. But this is implementation detail... .

**Comment by omariom** [comment]
> Open question is whether the InitBlock should be generic to match Span usage, or Span<T> should handle forwarding to a ref byte version of this.

Will it be filling  with `default(T)`? Another question is alignment as  unaligned Spans are legal.

**Comment by jkotas** [comment]
@KrzysztofCwalina @terrajobst  @AtsushiKan This should be no-brainer API addition to Span. Could you please review?

**Comment by jkotas** [comment]
> Will it be filling with `default(T)` ?

Yes. It will do the exactly same thing as `Array.Clear`, except for Span.

**Comment by jkotas** [comment]
>  unaligned Spans are legal

Unaligned Spans are gray area. They are not explicitly prohibited, but they are non-portable. E.g. they will only work on platforms like x86/x64 that allow misaligned access.

**Comment by omariom** [comment]
I mean the scenario when  `NonPortableCast` and the `ctor` taking a pointer used to create unaligned spans which then passed to  safe consumers. Shouldn't  `Clear` call `InitBlockUnaligned` then (if `T` is blittable)?

**Comment by AtsushiKan** [comment]
>This should be no-brainer API addition to Span. Could you please review?

Sounds good to me.

**Comment by jkotas** [comment]
> Shouldn't Clear call InitBlockUnaligned then (if T is blittable)?

No. It would pessimize the 99+% case for no good reason.

**Comment by jamesqo** [comment]
@jkotas, maybe it would be a good idea to provide a `ClearUnaligned` method or `UnalignedClear`, then? I think reinterpreting binary data (e.g. casting `Span<byte>` to `Span<T>`, where T is some bigger primitive type) is pretty a pretty common scenario for apps that e.g. read in binary files.

Also: maybe it should work with unaligned by default? `Clear` and `AlignedClear`?

**Comment by jkotas** [comment]
> Maybe it would be a good idea to provide a ClearUnaligned method or UnalignedClear, then?

This is equivalent to casting your Span<T> to Span<byte> and calling a clear on it. I do not think it is worth having a convenience method for it.

> reinterpreting binary data (e.g. casting Span<byte> to Span<T>, where T is some bigger primitive type)

This pattern is generally non-portable because of alignment requirements of different platforms. The NonPortableCast makes it possible if you know what to do to avoiding the land mines.

**Comment by jkotas** [comment]
> reinterpreting binary data

I expect that we are going to have methods like these to make reinterpreting of the binary data (in particular, binary data coming from the wire) fast and portable: 

```
static T Read<T>(this ref ReadOnlySpan<byte> span);

static Int16 ReadInt16BigEndian(this ref ReadOnlySpan<byte>);
static Int16 ReadInt16LittleEndian(this ref ReadOnlySpan<byte>);
static Int32 ReadInt32BigEndian(this ref ReadOnlySpan<byte>);
static Int32 ReadInt32LittleEndian(this ref ReadOnlySpan<byte>);
...
```

and similar for writes.

**Comment by nietras** [comment]
> It cannot just forward to Unsafe.InitBlock for types that contain GC references.

@jkotas Of course not, I didn't think so either, but since you wrote "should be thin wrappers over cpblk/initblk IL instructions", I though hey Jan knows better perhaps the JIT can do some tricks 🎱 but probably more it was me interpreting "thin" incorrectly, and phrasing the text wrong :), I tried to correct the proposal text accordingly. Perhaps a little too detailed...

> do the exactly same thing as Array.Clear, except for Span.

I would hope `Array.Clear` could forward to the Span implementation, so we can get this consolidated. Depending on perf, of course.

> Unaligned Spans are gray area. They are not explicitly prohibited, but they are non-portable.

With regard to alignment I think there are two things to consider here. The wording for `initblk` is "initblk assumes that the starting address is aligned to the natural size of the machine." so one thing is that the address must be 4 or 8 bytes aligned, for 32- or 64-bit, respectively. 

The next thing is that the natural alignment of a given type `T`, e.g. `double` should be aligned on 8. I would assume `Clear()` needs to handle this appropriately for each type, such that for e.g. `byte` it will **have** to use `InitBlockUnaligned`. Since there can be no assumed alignment of byte spans. Similar for all value types with a natural alignment less than the natural size of the machine. Is there any way to get the alignment of used defined value types e.g. `Bgr` consisting of 3 bytes?

> This pattern is generally non-portable because of alignment requirements of different platforms. The NonPortableCast makes it possible

I agree with this, that is no need for `ClearUnaligned`, this can be handled via the more cumbersome cast.

>  expect that we are going to have methods like these to make reinterpreting of the binary data

So `SpanExtensions`?

**Comment by jkotas** [comment]
> So `SpanExtensions`?

Right. Experimented with in corefxlab https://github.com/dotnet/corefxlab/blob/master/src/System.Slices/System/SpanExtensions_binary.cs#L46

**Comment by jkotas** [comment]
FXDC: proposal LGTM

**Comment by terrajobst** [comment]
Looks good as proposed.

**Comment by karelz** [comment]
Any takers?

**Comment by nietras** [comment]
If you don't mind waiting I can give it a shot after doing new Unsafe
methods, and Span. CopyTo changes, if no one else is doing the latter. It's
related to the Unsafe adds.

**Comment by karelz** [comment]
Sure, just ping the issue when you're ready to pick it up ...

**Comment by karelz** [comment]
Assigned to you for simplicity - if you don't get to it for a week or more, I hope we will find out and ping you :)

**Comment by nietras** [comment]
@karelz if ok with you I will wait until https://github.com/dotnet/corefx/pull/13848 has been approved and committed before doing this, since the implementation I want to do relies on this.

**Comment by karelz** [comment]
Makes sense, thank for update!
