### ISSUE TITLE
FileLoadException when trying to run tests for a different TestTFM

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#13911]
I followed the directions [here](https://github.com/dotnet/corefx/blob/0300e2c42e3ce96240e05daff6f6c5a5e03081a6/Documentation/project-docs/developer-guide.md#running-tests-in-a-different-tfm) and tried running the tests for System.IO on desktop by executing `msbuild /p:TestTFM=net46 /t:RebuildAndTest` in System.IO\tests. Unfortunately, I get the following output when I try to do so:

```
  Executing in C:\Users\james\Code\git\corefx\bin\tests\AnyOS.AnyCPU.Debug\System.IO.Tests\default.net46\
  Hard linking dependent files...
  Finished linking needed files, moving to running tests.
  Running tests... Start time: 23:21:56.24
  Command(s):
  call xunit.console.exe System.IO.Tests.dll  -noshadow  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnet46tests  -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests
  xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
  System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
  Finished running tests.  End time=23:22:19.28, Exit code = 1
```

The same error occurs when the TestTFM is net462. Interestingly, however, I get different errors when running for net463: https://gist.github.com/jamesqo/0b2093b4841a4897e997d9bcf1be8dd9 (Ctrl + F and type "[FAIL]" to see them). It looks like System.Runtime is loading ok in that case, but some other assemblies such as System.Linq are not.

**Comment by danmosemsft** [comment]
This is https://github.com/dotnet/buildtools/issues/1092 and @karajas is working on that. @karajas what is the workaround -- create an .exe.config file for corerun? Could you explain for @jamesqo ?

@ianhays

**Comment by mellinoe** [comment]
We've overhauled the test infrastructure since this, so it's no longer applicable.
