### ISSUE TITLE
ARM: ZLibException when working with GZipStream (System.IO.Compression.ZipFile 4.3.0)

### ISSUE THREAD

**Issue by tipa** [dotnet/corefx#13914]
In my UWP app, I am using the NuGet packages `Microsoft.Data.Sqlite 1.1.0` and `Microsoft.EntityFrameworkCore.Sqlite 1.1.0`, both requiring the package `System.IO.Compression.ZipFile 4.3.0` .

When using a GZipStream in my app, I get a `System.IO.Compression.ZLibException ("The underlying compression routine could not be loaded correctly.")`. InnerException: `Unable to load DLL 'clrcompression.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)`.
Happens on mobile (ARM) only!

This is how I am using the stream:
```
 using (GZipStream stream = new GZipStream(compressedStream, CompressionMode.Compress, true))
 {
       await fileStream.CopyToAsync(stream);
 }
```

Problem can be reproduced by installing the `System.IO.Compression.ZipFile 4.3.0` package only.

**Comment by karelz** [comment]
Which UWP version do you use?

**Comment by tipa** [comment]
I am targeting `Windows 10 Build 14393` and use `Microsoft.NETCore.UniversalWindowsPlatform 5.2.2`.
There is no error when using `System.IO.Compression.ZipFile 4.0.1`.

**Comment by karelz** [comment]
@ericstj @ianhays can you please help here?

**Comment by ianhays** [comment]
@tipa are you building for Debug or Release? Could you also share your RID for ARM e.g. `win10-arm`.

**Comment by tipa** [comment]
Problem seems to happen for Debug only. RID should be `win10-arm` (I am running the app on a Lumia 930).
This is how my project.json looks, in case it helps:
```
{
  "dependencies": {
    "HockeySDK.UWP": "4.1.5",
    "Microsoft.Data.Sqlite": "1.1.0",
    "Microsoft.EntityFrameworkCore.Sqlite": "1.1.0",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2",
    "Microsoft.OneDriveSDK": "2.0.6",
    "Microsoft.OneDriveSDK.Authentication": "1.0.8",
    "NotificationsExtensions.Win10": "14332.0.2",
    "Syncfusion.DocIO.UWP46": "14.4.0.15"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

**Comment by ianhays** [comment]
>Problem seems to happen for Debug only. 

This is probably because the `Release` package `win10-arm-aot` has the Appx clrcompression that is for UWP. When building as Debug you are getting the `win8-arm` package which does not have the Appx clrcompression.dll. 

>This is how my project.json looks, in case it helps:

That does help, thanks. Would you mind posting your project.lock.json as well? That should confirm the issue you're seeing is a result of the above.

**Comment by tipa** [comment]
So is it expected behavior that I cannot test my app in debug mode? 
Here's me [project.lock.json.zip](https://github.com/dotnet/corefx/files/634860/project.lock.json.zip)

**Comment by ianhays** [comment]
>So is it expected behavior that I cannot test my app in debug mode?

The non-appx version should still be usable in Debug, it should just fail WACK. I took a look at your lock.json and it looks fine. Can you confirm whether your published app in `Debug` actually has a clrcompression.dll present?

from your project.lock.json for win10-arm:
```
    "UAP,Version=v10.0/win10-arm": {
      "runtime.win8-arm.runtime.native.System.IO.Compression/4.3.0": {
        "native": {
          "runtimes/win8-arm/native/clrcompression.dll": {}
        }
      },
    }
```

from your project.lock.json for win10-arm-aot
```
    "UAP,Version=v10.0/win10-arm-aot": {
      "runtime.win10-arm-aot.runtime.native.System.IO.Compression/4.0.1": {
        "compile": {
          "runtimes/win10-arm-aot/lib/netcore50/_._": {}
        },
        "runtime": {
          "runtimes/win10-arm-aot/lib/netcore50/clrcompression.dll": {}
        }
      },
    }
```

cc: @ericstj

**Comment by ericstj** [comment]
> The non-appx version should still be usable in Debug, it should just fail WACK

That's correct and by design.  I'd also expect a different error code if loader was rejecting the DLL.  The exception had ERROR_MOD_NOT_FOUND.  This points to me to the dll being missing from the appx package as @ianhays mentions.

**Comment by tipa** [comment]
It turned out that after deleting the `bin` and `obj` folders and a complete rebuild everything works fine now. Seems like the app still used the old packages or didnt find the new one (or however that works, I don't know the details...).
Thanks for your help and sorry for bothering you!

**Comment by ianhays** [comment]
No worries @tipa, glad you were able to figure it out :)

**Comment by Ran-QUAN** [comment]
@ianhays  Hi, this issue can still be reproduced by simply referencing `System.IO.Compression 4.3.0` in a blank UWP app project and use some api of it, like `new DeflateStream(...`

When testing on an arm device with Debug configuration, `ZLibException` will be thrown. Could anyone do some further testing about it?

Here is a project that reproduces this issue. 
[SystemIOCompressionUWPError.zip](https://github.com/dotnet/corefx/files/762050/SystemIOCompressionUWPError.zip)

**Comment by groege** [comment]
Same here, please help (I'm using ZipArchive)

**Comment by groege** [comment]
Why is there: runtime.**win10-arm-aot**.runtime.native.System.IO.Compression in version 4.01, but the runtime.**win10-arm**.runtime.native.System.IO.Compression  is still in prerelease 4.01-rc2-24027
Seems to me there should be a runtime.**win10-arm**.runtime.native.System.IO.Compression with a sable 4.01 that is used when native toolchain is disabled, allowing for debugging...

**Comment by ianhays** [comment]
@groege the win10-arm package isn't updated any longer and it should not be used. You want either the win8-arm or win10-arm-aot packages instead. Take a look at the project.lock.json code I linked earlier in this thread for what the correct usage should look like.

@Ran-QUAN did you try what tipa did and do a full clean? If so, is there a clrcompression.dll in your bin folder? What is the version in your project.json? Did you try updating to the latest versions?

**Comment by Ran-QUAN** [comment]
@ianhays 

Yes, clean build didn't fix the problem. Even creating a new UWP project didn't fix it.

clrcompression.dll is copied to the `bin\ARM\Debug` folder. And I also checked the deployment log, it was copied into the layout.

Here is my project.json

```json
{
  "dependencies": {
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2",
    "System.IO.Compression": "4.3.0"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

Version 4.1.0 has no problem, I got the error when upgrading ef core SQLite to version 1.1, which references System.IO.Compression 4.3.0

I also tried different computer and VS 2017 RC4, didn't help. Device I'm using is Lumia 650.

**Comment by groege** [comment]
Same here -> I'm referencing 4.3.0 because of EF Core 1.1

**Comment by ianhays** [comment]
@Ran-QUAN Could you try changing your runtimes section to:
```
  "runtimes": {
    "win8-arm": {},
    "win10-arm-aot": {},
    "win7-x86": {},
    "win10-x86-aot": {},
    "win7-x64": {},
    "win10-x64-aot": {}
  }
```

and see if that resolves your issue. It sounds like both you and @groege are getting old versions of the win10-* packages. Are you using the myget feed or the nuget feed for your packages?

**Comment by Ran-QUAN** [comment]
@ianhays I'm using nuget feed.

> @Ran-QUAN Could you try changing your runtimes section to:
  ```
  "runtimes": {
    "win8-arm": {},
    "win10-arm-aot": {},
    "win7-x86": {},
    "win10-x86-aot": {},
    "win7-x64": {},
    "win10-x64-aot": {}
  }
  ```

Removing `win10-arm` from project.json will fail the package restore with the following error:

`Error	Your project.json doesn't list 'win10-arm' as a targeted runtime. You should add '"win10-arm": { }' inside your "runtimes" section in your project.json, and then re-run NuGet restore.`

**Comment by tipa** [comment]
I see this is still making problems to some of you, so I thought I might add some observations of mine:

- The problem does only occur on Mobile and the current public  build 14393

- It is not happening on Desktop or on the current Insider Mobile build 15031

@Ran-QUAN @groege do you have same experiences? Maybe we can save Ian and the others from some headache and just wait for the Creators Update to go live ;)

**Comment by groege** [comment]
Yes I'm using build 10.0.14393.693

**Comment by pdeliot** [comment]
I've also facing knightmare with Systel.IO.Compression.

I've recently ported all my portable assemblies to Standard 1.1 and 1.3. 
This enabling me to use them with .NET Core and Universal 8.1 (Desktop and Mobile).

It's working with w10 desktop Debug... 8.1 Desktop and Mobile... but failling with missing compression dependencies  undes Mobile Debug or any Realase :-(
 
Already tested many things (including forcing 4.0.1 downgrade or cleaning all obj and bin...) with improvment...

**Comment by dmitrymal** [comment]
Has this been resolved or is there a workaround? 

I am also getting similar errors in the Debug mode. It appears the errors only happen in the emulator (I don't have an ARM device to test). 
I don't get an error in the Release mode or on the Desktop

When I get an error, here is the Debug output related to the error:

Exception thrown: 'System.DllNotFoundException' in System.IO.Compression.dll
Exception thrown: 'System.IO.Compression.ZLibException' in System.IO.Compression.dll

System.IO.Compression.ZLibException: The underlying compression routine could not be loaded correctly. ---> 
System.DllNotFoundException: Unable to load DLL 'clrcompression.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Interop.zlib.deflateInit2_(Byte* stream, Int32 level, Int32 method, Int32 windowBits, Int32 memLevel, Int32 strategy, Byte* version, Int32 stream_size)
   at Interop.zlib.DeflateInit2_(ZStream& stream, CompressionLevel level, CompressionMethod method, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
   at System.IO.Compression.ZLibNative.ZLibStreamHandle.DeflateInit2_(CompressionLevel level, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
   at System.IO.Compression.Deflater.DeflateInit(CompressionLevel compressionLevel, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
   --- End of inner exception stack trace ---
   at System.IO.Compression.Deflater.DeflateInit(CompressionLevel compressionLevel, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
   at System.IO.Compression.Deflater..ctor(CompressionLevel compressionLevel, Int32 windowBits)
   at System.IO.Compression.DeflateStream.InitializeDeflater(Stream stream, Boolean leaveOpen, Int32 windowBits, CompressionLevel compressionLevel)
   at System.IO.Compression.DeflateStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen, Int32 windowBits)
   at Microsoft.HockeyApp.Services.HttpClientTransmission.CreateCompressedStream(Stream stream)
   at Microsoft.HockeyApp.Extensibility.Implementation.JsonSerializer.Serialize(IEnumerable`1 telemetryItems, Boolean compress)
   at Microsoft.HockeyApp.Channel.FlushManager.Flush()
   at Microsoft.HockeyApp.Channel.PersistenceChannel.Flush()
   at Microsoft.HockeyApp.HockeyClient.Flush()

My setup:

VS2015 Update 3

"HockeySDK.UWP": "4.1.6",
"Microsoft.Data.Sqlite": "1.1.1",
"Microsoft.NETCore.UniversalWindowsPlatform": "5.2.3",

As suggested, I tried clean builds, tried to downgrade Sqlite": "1.1.1" to Sqlite": "1.0.0" (I am not using EF). Nothing helps

Any suggestions?

**Comment by ianhays** [comment]
This issue is the same one described in the comments in https://github.com/dotnet/corefx/issues/9743.

The problem you all are facing is that the clrcompression being packaged for Debug is one that imports from kernel32. This causes errors when testing on a device with a OneCore OS that doesn't support kernel32. You don't get errors for Release because the Release clrcompression imports from the APIsets.

A workaround would be to directly reference the runtime clrcompression package that contains the APISets-imported clrcompression:

```
  "dependencies": {
    "runtime.win8-arm.runtime.native.System.IO.Compression":  "4.0.1"
```

I've got a [fix for this merged in the 1.1 servicing branch](https://github.com/dotnet/corefx/pull/20019), but it hasn't shipped yet. cc: @weshaggard

**Comment by xavier-rigau** [comment]
Still happening without the workaround. Has anybody got a DEBUG version working without the workaround?

**Comment by xavier-rigau** [comment]
Why is this bug still closed if is still happening?
