### ISSUE TITLE
SecurityProtocolType Ssl3 should be marked as obsolete

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#13922]
Similar to obsolete members in `SslProtcols`.

@davidsh @karelz @blowdart PTAL

**Comment by blowdart** [comment]
But then we break serialization should someone want to serialize it. Which I'm ok with, but lots of other people aren't :(

**Comment by karelz** [comment]
How common is serialization? At minimum, it should pass through ddcc group.

**Comment by CIPop** [comment]
> But then we break serialization should someone want to serialize it. Which I'm ok with, but lots of other people aren't :(

Serialization won't be broken if the change is made in the `ref` folder only.

**Comment by karelz** [comment]
@weshaggard do we take ref-only changes?

**Comment by CIPop** [comment]
@karelz for details, please refer to https://github.com/dotnet/corefx/pull/13745

**Comment by weshaggard** [comment]
>@weshaggard do we take ref-only changes?

Yes we do sometimes make Ref only changes like adding obsolete or browser hidden.

**Comment by karelz** [comment]
We should reuse our soon-to-be-defined Obsolete/Deprecate story.

**Comment by davidsh** [comment]
@karelz 
>We should reuse our soon-to-be-defined Obsolete/Deprecate story.

Can you clarify what this is and where it is documented?  I don't understand what code changes/annotations we should be making for this issue.

**Comment by karelz** [comment]
It is only in early design discussions. It won't make it into 2.0.

Can we / should we obsolete this particular member the traditional way?

**Comment by davidsh** [comment]
>It is only in early design discussions. It won't make it into 2.0.
Can we / should we obsolete this particular member the traditional way?

The "traditional way" was to simply add the annotation to both ref and implementation.  But that will potentially break serialization as noted above.

>But then we break serialization should someone want to serialize it. Which I'm ok with, but lots of other people aren't :(

The only other thing we can try is to only deprecate it in the 'ref'.  Wes commented on that:

>Yes we do sometimes make Ref only changes like adding obsolete or browser hidden.

Adding 'obsolete' to even the 'ref' will cause compiler errors since it is a warning and some people will set the compiler flags to "treat warnings as errors".

Using 'browser hidden" attribute is less risky.  It simply hides it from intellisense.  So, it doesn't make it 'obsolete' but sort of makes it 'discouraged'.

**Comment by CIPop** [comment]
@davidsh @karelz 

> OK, in that case we should track it for Future, when the Obsolete/Deprecated tooling lights up, we can add it there.

The ObsoleteAttribute was already shipped twice (in 1.0 and 1.1) w/o any known issues so far: https://github.com/dotnet/corefx/blob/release/1.0.0/src/System.Net.Primitives/ref/System.Net.Primitives.cs#L417

That said, it's not part of the Standard for some reason: https://github.com/dotnet/standard/blob/master/netstandard/ref/System.cs#L8002 

@davidsh @karelz @weshaggard I think that whatever decision we take, there should be symmetry between the two enums in the 2.0 release.

**Comment by karelz** [comment]
@CIPop don't forget that .NET Standard has much wider reach and impact than .NET Core 1.x. The fact we didn't get feedback in .NET Core 1.x is encouraging, but not sufficient argument.

**Comment by CIPop** [comment]
@karelz I agree but I still think that symmetry is required in this case. There are three choices:

1. Add Obsolete to `enum SecurityProtocolType` for Ssl2/3
2. Remove the Obsolete on the System.Net.Primitives `enum SslProtcols` Ssl2/3
3. Do nothing and break symmetry with the risk of creating some confusion (SecurityProtocolType Ssl2/3 is OK to use but SslProtocols Ssl2/3 is not).

I still think that option 1, while having moderate risk, is the right one to signal developers that they are using Ssl2/3 which is not secure.

**Comment by karelz** [comment]
I didn't realize there is inconsistency already baked in.
@weshaggard I am also leaning towards (1) in .NET Standard 2.0 as well ... thoughts?

**Comment by weshaggard** [comment]
Even if we go with 1 we would still have to add the obsolete attribute to .NET Framework as well if we want full consistency. In doing that we do have the potential serialization risk.

That said I'm not opposed to adding the obsolete attribute to the ref in .NET Standard. If that is what you want then please file an issue on dotnet/standard repo with the information to put in the obsolete message (or submit a PR).

**Comment by karelz** [comment]
Good point @weshaggard. I view inconsistency between platforms a bit lighter than inconsistency inside the same platform.
Also if we change .NET Core (which we IMO should), we should be able to change also .NET Standard IMO - it is the modern common API surface.
I'd say let's do it!

**Comment by CIPop** [comment]
> Even if we go with 1 we would still have to add the obsolete attribute to .NET Framework

I'm planning as soon as build/tooling will allow me to change only the ref to ensure build-time warnings only. (In Framework we extract the refs from the assemblies automatically while in Core we have the separate ref folder.)

> I'd say let's do it!

Moving to 2.0 and will pick-up Friday or next week. Feel free to change back to Future if further discussion ends up disagreeing.

**Comment by weshaggard** [comment]
>I'm planning as soon as build/tooling will allow me to change only the ref to ensure build-time warnings only. (In Framework we extract the refs from the assemblies automatically while in Core we have the separate ref folder.)

Yes I understand this is how the .NET Framework tooling works and I don't see us funding work to change that anytime soon.
