### ISSUE TITLE
Expose a cached StringBuilder

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#13924]
We use `StringBuilderCache` to improve performance for short-lived usages of `StringBuilder`. Numerous other codebases have copied this. I want to suggest that we: (1) expose `StringBuilderCache` and/or (2) expose a cached `StringBuilder` on `StringBuilder`.

### New Member Option A
Aligns with `StringBuilderCache`, although I prefer to flip the ordering of the words for `GetStringAndRelease`- it makes more sense from a discovery perspective.

``` diff
namespace System.Text
{
  public sealed class StringBuilder
  {
+    public static StringBuilder Acquire(int capacity);
+    public static void Release(StringBuilder sb);
+    public static string ReleaseAndGetString(StringBuilder sb);
  }
}
```

### New Member Option B
Aligns with `ArrayPool` terminology.

``` diff
namespace System.Text
{
  public sealed class StringBuilder
  {
+    public static StringBuilder Rent(int capacity);
+    public static void Return(StringBuilder sb);
+    public static string ReturnAndGetString(StringBuilder sb);
  }
}
```

### Expose StringBuilderCache Option

``` diff
namespace System.Text
{
+  public static class StringBuilderCache
+  {
+    public static StringBuilder Acquire(int capacity);
+    public static void Release(StringBuilder sb);
+    public static string ReleaseAndGetString(StringBuilder sb);
+  }
}
```

**Comment by JeremyKuhne** [comment]
@vancem, @jkotas, @stephentoub

**Comment by jkotas** [comment]
I do not think we should expose this. The StringBuilderCache has bad properties: it only works for small strings, it is one per thread and stays allocated forever.

We should be snapping to ArrayPool for any kind of similar pooling. Discussed in https://github.com/dotnet/corefx/pull/13875#issuecomment-262293493.

If we need to make the string formatting cheaper, we should create an small internal helper type like the one I have described in #13875 that works on top of ArrayPool.

Eventually, the public API for this should be addressed by low-allocation formatters being developer in corefxlab.

**Comment by JeremyKuhne** [comment]
> I do not think we should expose this.

I'm more concerned with the current "need" for it and numerous copies than exactly how we solve it. :) There are two main questions I have with your suggestion:

1. How do we normalize this with `StringBuilder` as far a usage cases? Does this one become "StringBuilder2.0"?
2. What is the P/Invoke story with an ArrayPool based builder? Use char[] in your signatures? I _believe_ that arrays of blittable types pin when marshalled??

> Eventually, the public API for this should be addressed by low-allocation formatters being developer in corefxlab.

Any links to those?

**Comment by jkotas** [comment]
> Does this one become "StringBuilder2.0"?

Number of types in the classic .NET surface were designed for rapid application development of enterprise apps. They are not as fast and lean as we would like them to be. We have ad-hoc developed leaner alternatives for internal corefx use. Here is leaner `List<T>` alternative for example: https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Collections/Generic/ArrayBuilder.cs#L10. PooledStringBuilder that I have proposed would be another one of these.

We do want to make them public .NET Core APIs, but it needs to happen with extra thought going into it - to make sure that it is something that we are happy with, not just an incremental improvement that we will want to redo again. It is what the current effort in corefxlab is basically about.

> What is the P/Invoke story with an ArrayPool based builder? Use char[] in your signatures?

Yes. Or `char*`. Depends on the situation.

> Any links to those?

https://github.com/dotnet/corefxlab/blob/master/docs/roadmap.md

This falls into the parsing/formatting APIs bucket. Work in progress here: https://github.com/dotnet/corefxlab/tree/master/src/System.Text.Primitives

**Comment by jamesqo** [comment]
👍 I think focusing on a new formatting API would be better than trying to make up for `StringBuilder`'s deficiencies via caching them.

**Comment by AlexGhiondea** [comment]
I am going to close this issue for now.

Please feel free to reactivate if you have other use cases for adding this new API.
