### ISSUE TITLE
Add Fedora 25 to CI / RID Graph / Packages 

### ISSUE THREAD

**Issue by randomvariable** [dotnet/corefx#13937]
https://fedoraproject.org/wiki/Releases

https://hub.docker.com/_/fedora/

**Comment by mellinoe** [comment]
@karelz @danmosemsft Could you guys comment on our packaging plans going forward?

**Comment by danmosemsft** [comment]
Question best for @weshaggard

**Comment by weshaggard** [comment]
We plan on adding Fedora 25 to our support matrix, including CI/RID/Packages. We are thinking we will actually use our PortableLinux native implementations for Fedora (and other distros) in our .NET Core 2.0 release.

**Comment by mellinoe** [comment]
AFAIK, the RID's are already in here. I'm not clear on whether you are saying we are going to have fedora.25-x64 packages, specifically, or if we will support Fedora 25 via the portable linux binaries. I strongly prefer the latter and I think that was our stated goal in the past.

**Comment by weshaggard** [comment]
The goal will be to support Fedora 25 with the portable linux binaries and not have Fedora 25 specific packages.

**Comment by mellinoe** [comment]
Sounds great. In that case, I think this issue is more-or-less covered. There are RIDs for Fedora 25 if folks want to use them, and we have portable linux binaries building already.
