### ISSUE TITLE
Move Get/SetEnvironmentVariable to CoreLib

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#13931]
Due to the lack of thread safety with environment variables on Unix the values are cached in the CoreFX [implementation]( https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/Environment.Unix.cs#L19).

This causes `Path.GetTempPath()` and anything else that tries to get an environment variable in CoreLib to not have the up-to-date values. See the failing tests in https://github.com/dotnet/corefx/pull/13920.

We should move the implementation to Internal.Runtime.Augments so we have one source of truth.

**Comment by JeremyKuhne** [comment]
@jkotas Any issues with doing this?

cc: @ianhays, @stephentoub

**Comment by jkotas** [comment]
Sounds reasonable to me.

**Comment by jkotas** [comment]
The Windows-only overloads that write to registry may still stay in corefx.

**Comment by AlexGhiondea** [comment]
@JeremyKuhne we marked this for 1.2 -- let me know if you disagree.

**Comment by danmosemsft** [comment]
@JeremyKuhne does more remain here? I think you nentioned a change in the PAL.

**Comment by JeremyKuhne** [comment]
#14425
