### ISSUE TITLE
Make CultureInfo properties UserDefaultCulture and UserDefaultUICulture public

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/corefx#13940]
`CultureInfo` currently implement `InstalledUICulture`,  `UserDefaultCulture` and `UserDefaultUICulture` properties.  `InstalledUICulture` property is public, but `UserDefaultCulture` and `UserDefaultUICulture` properties are internal.  `UserDefaultCulture` and `UserDefaultUICulture` properties **will be very helpful to get current user cultures**. So I suggest make UserDefaultCulture and UserDefaultUICulture properties public.

# Rationale and Usage
Get current user cultures. Using system culture instead of current user culture is bad because each user on Windows can have different culture settings.

Now if thread culture was changed, we can not get culture for current user. Also if `DefaultThreadCurrentCulture` is changed we can not set it back to current user culture.

# Proposed API
```cs
public class CultureInfo 
{
    public static CultureInfo UserDefaultCulture;
    public static CultureInfo UserDefaultUICulture;
}
```

**Comment by tarekgh** [comment]
@AlexRadch could you please clarify the scenarios you need to expose these properties for? I have a concern that we have too many culture properties already exposed and can be confused to expose more without clear scenario or app requesting it. also exposing these properties will not make sense for UWP apps.

**Comment by AlexRadch** [comment]
@karelz Now application don't know culture  of current user. I think it is useful in multi language applications.  Also this methods are already exists as internal because framework cannot work correct without that information. But why it should hide it from applications? What reason?

**Comment by tarekgh** [comment]
@AlexRadch the framework is not hiding anything nor the point is we have the implementation and not exposing it. the point is what the scenario people need to know that.

to explain more, if the application didn't override the current culture in the thread, the thread will have the default user culture registered on the system. so the application can get this value. if the current culture get overridden, this means it is overridden for a good reason (from the application) which means the application decided that and shouldn't use the default user culture which is registered on the system. 
The other point is WinRT (UWP apps) work differently and not really using the user default culture and instead it uses whatever culture defined or derived by WinRT.

As I mentioned before, the problem I am seeing to expose more such properties is we already have exposed different properties dealing with the default/current cultures and it is easy to get the consumer of CultureInfo class confused. exposing such properties will increase this confusion and I am not really seeing any real benefit doing that as I didn't get any real app scenario need it in.

**Comment by tarekgh** [comment]
I am closing this request, please feel free to reply back or reopen if you think you need to discuss it more. Thanks.
