### ISSUE TITLE
UDP Socket using SocketAsyncEventArgs garbage collects nearly every second

### ISSUE THREAD

**Issue by scionwest** [dotnet/corefx#14008]
I've written a small UDP server with the .Net Core `SocketAsyncEventArgs` implementation, of Sockets. When the server runs, I can see the garbage collection run in the Visual Studio Diagnostics tooling. It runs almost non-stop. Yet when I take Heap snapshots, I don't see hardly any allocations. I fetch my `byte[]` buffers from an `ArrayPool<byte>` and I fetch my `SocketAsyncEventArgs` instances from a custom object pool. I have however seen this same behavior when fetching them from another `ArrayPool<SocketAsyncEventArgs>` instead. In theory, when looking at my code, there should be virtually zero allocations happening, except for what ever the Socket instance is doing.

This is a screenshot of the Diagnostics tooling in Visual Studio showing the garbage collections happening. You can see I'm not allocating anything new in the Heap that would warrent that kind of activity.

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/5FwLr.png

I pulled the server and object pooling code out and into a reproducible example project.

## ObjectPool<T>

Calling `ObjectPool<T>.Rent<T>()` will give you back an instance from the pool. If no instance exists, it will create one using either `System.Reflection.Activator` or a custom `Func<T>` delegate provided, and give it back to you. When you are done, you call `ObjectPool<T>.Return(T);` to place the instance back into the pool for recycling. 
```c#
public class ObjectPool<TObject>
{
    private int maxPoolSize;
    private SpinLock poolLock;
    private Dictionary<Type, Stack<TObject>> poolCache;
    private Func<TObject> factory;

    public ObjectPool(int poolSize)
    {
        this.maxPoolSize = poolSize;
        this.poolLock = new SpinLock(false);
        this.poolCache = new Dictionary<Type, Stack<TObject>>();
    }

    public ObjectPool(int poolSize, Func<TObject> factory) : this(poolSize)
    {
        this.factory = factory;
    }

    public T Rent<T>() where T : TObject
        => (T)this.Rent(typeof(T));

    public TObject Rent(Type type)
    {
        bool lockTaken = false;
        Stack<TObject> cachedCollection;
        this.poolLock.Enter(ref lockTaken);

        try
        {
            if (!this.poolCache.TryGetValue(type, out cachedCollection))
            {
                cachedCollection = new Stack<TObject>();
                this.poolCache.Add(type, cachedCollection);
            }
        }
        finally
        {
            if (lockTaken)
            {
                this.poolLock.Exit(false);
            }
        }

        if (cachedCollection.Count > 0)
        {
            TObject instance = cachedCollection.Pop();
            if (instance != null)
                return instance;
        }

        // New instances don't need to be prepared for re-use, so we just return it.
        if (this.factory == null)
        {
            return (TObject)Activator.CreateInstance(type);
        }
        else
        {
            return this.factory();
        }
    }

    public void Return(TObject instanceObject)
    {
        Stack<TObject> cachedCollection = null;
        Type type = typeof(TObject);

        bool lockTaken = false;
        this.poolLock.Enter(ref lockTaken);
        try
        {
            if (!this.poolCache.TryGetValue(type, out cachedCollection))
            {
                cachedCollection = new Stack<TObject>();
                this.poolCache.Add(type, cachedCollection);
            }

            if (cachedCollection.Count >= this.maxPoolSize)
            {
                return;
            }

            cachedCollection.Push(instanceObject);
        }
        finally
        {
            if (lockTaken)
            {
                this.poolLock.Exit(false);
            }
        }
    }
}
```

## Server

The server can be started by invoking `Server.Start()`. The server uses the new, in Core, `ArrayPool<T>` Type to fetch `byte[]` buffer arrays. It also uses my `ObjectPool<T>` Type to fetch `SocketAsyncEventArgs` instances so it can avoid allocating. Note that in the example I'm not overwriting (cleaning up) the buffer contents as they come and go from the pool, mostly because that code wasn't needed to demonstrate my issue.

```c#
public class Server
{
    private ArrayPool<byte> socketBufferPool;
    private ObjectPool<SocketAsyncEventArgs> socketEventArgsPool;

    private Socket listeningSocket;
    private IPEndPoint readEndPoint;
    private IPEndPoint writeEndPoint;

    public Server(IPAddress serverIPAddress, int serverPort, int clientPort)
    {
        this.readEndPoint = new IPEndPoint(IPAddress.Any, clientPort);
        this.writeEndPoint = new IPEndPoint(serverIPAddress, serverPort);

        // Create our object pool, letting it use us as the Factory for creating and setting up new SocketAsyncEventArgs.
        this.socketEventArgsPool = new ObjectPool<SocketAsyncEventArgs>(10, this.ConfigureSocketEventArgs);
        this.socketBufferPool = ArrayPool<byte>.Create(256, 100);
    }

    public void Start()
    {
        this.listeningSocket = new Socket(this.writeEndPoint.AddressFamily, SocketType.Dgram, ProtocolType.Udp);
        this.listeningSocket.Bind(this.writeEndPoint);
        SocketAsyncEventArgs readArgs = this.socketEventArgsPool.Rent<SocketAsyncEventArgs>();
        this.listeningSocket.ReceiveFromAsync(readArgs);

        while (true)
        {
        }
    }

    private void ReceivedSocketEvent(object sender, SocketAsyncEventArgs e)
    {
        // Rent a new Socket event arg right away and start listening for more packets.
        SocketAsyncEventArgs eventArgs = this.socketEventArgsPool.Rent<SocketAsyncEventArgs>();
        this.listeningSocket.ReceiveFromAsync(eventArgs);
        this.socketEventArgsPool.Return(e);
    }

    private SocketAsyncEventArgs ConfigureSocketEventArgs()
    {
        byte[] buffer = this.socketBufferPool.Rent(256);
        var eventArg = new SocketAsyncEventArgs();
        eventArg = new SocketAsyncEventArgs();
        eventArg.Completed += new EventHandler<SocketAsyncEventArgs>(this.ReceivedSocketEvent);
        eventArg.SetBuffer(buffer, 0, 256);
        eventArg.RemoteEndPoint = this.readEndPoint;

        return eventArg;
    }
}
```

## Program: Server-side

This just creates an instance of the Server, provides it with the IP address and ports needed to run, and then starts it.

```c#
class Program
{

    static void Main(string[] args)
    {
        Console.WriteLine("Starting server");
        var ip = new IPAddress(new byte[] { 10, 0, 1, 6 });
        var server = new Server(ip, 11000, 11100);
        server.Start();
    }
}
```

## Program: Client-side

This app just opens a Socket on a different port and sends a bunch of datagrams to the server. If I just use a straight `while(true)` I see a massive amount of GC purges on the server side. If I place a `Task.Delay(1).Wait();` within the while loop, I didn't see any during a 3 minute run. Whereas without the `Task.Delay(1).Wait()` I see a GC almost every second. I understand that adding that delay slows down the number of messages sent to the server significantly, but I wanted to share in the event that it helps.

```c#
class Program
{
    static byte[] serverAddress = new byte[] { 10, 0, 1, 6 };

    static void Main(string[] args)
    {
        var clientSocket = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);

        // Start listening/sending
        EndPoint remoteEndPoint = new IPEndPoint(new IPAddress(serverAddress), 11000);
        while (true)
        {
            SendDatagram(clientSocket, remoteEndPoint, "Hello World!");
            //Task.Delay(1).Wait();
        }
    }

    static void SendDatagram(Socket clientSocket, EndPoint remoteEndPoint, string message)
    {
        byte[] msg = Encoding.ASCII.GetBytes("This is a test");
        clientSocket.BeginSendTo(
            msg,
            0,
            msg.Length,
            SocketFlags.None,
            remoteEndPoint,
            new AsyncCallback(SendCompleted),
            clientSocket);
    }

    private static void SendCompleted(IAsyncResult result)
    {
        Socket socket = (Socket)result.AsyncState;
        socket.EndSendTo(result);
    }
}
```

So the challenge I'm having is figuring out what is causing the GC calls. I see that the Diagnostic tooling says I'm using 17mb of ram, but when I run it outside of the IDE (debug build) it consumes about 3mb. I assume the bulk of the ram consumption is debugger related in the Diagnostic tooling. Could the debugger be causing the GC collections? Is there a means for me to track that outside of the debugger, or determine what objects are being collected? When I take the heap snapshots, the object count never changes, so there's no real way for me to tell from them what is happening.

I ran this for 5 minutes, sending 14 million datagrams to the server. The ram usage and the heap size hardly budged. The GC collections continued though.

This is reproducible on a File->New->NetStandard Console Project in Visual Studio 2017.

## dotnet --info
```
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

## dotnet --version
1.0.0-preview3-004056

**Comment by karelz** [comment]
Did you try to analyze the allocated memory with [PerfView](https://channel9.msdn.com/Series/PerfView-Tutorial)?

**Comment by scionwest** [comment]
I will do that now

**Comment by scionwest** [comment]
I'm not 100% sure what I should be looking at to be honest. Since this isn't a memory leak, it's hard to tell from doing a diff between a couple different Heap dumps. That coupled with my limited experience in exploring dumps in general makes the data a bit foggy for me.

- [Heap Dump 1: Baseline](http://imgur.com/7qPEvuG)
  - Taken prior to any datagrams being sent to the server.
- [Heap Dump 2: Diff from baseline](http://imgur.com/yUuqZGe)
  - Taken after receiving approx. 1.2 million datagrams over 60 seconds.
- [Heap Dump 3: Diff from Heap Dump 2](http://imgur.com/gBIacO8)
  - Taken after receiving approx. 3.5 million datagrams overr 120 seconds.
- [Album for easy viewing](http://imgur.com/a/eiVG3)

The biggest change I could see was the `SafeNativeOverlapped` count increasing. Does PerfView know that the actual reference was changed, so it can tell that 5,000 aren't the same 5,000 as before? I'm wondering because VS '17 doesn't show the Heap changing much, but PerfView shows a lot of object count changes.

**Comment by scionwest** [comment]
Looking at the Socket source, it looks like you guys are re-using the `SafeNativeOverlapped` handle if the Socket hasn't changed. Still kind of digging through the source a bit to see if anything stands out. Not sure why I'd be seeing so many instances being created over the life-time of the server running when I'm using the same socket for all incoming datagrams.

**Comment by Drawaes** [comment]
https://github.com/dotnet/corefx/pull/12664

Was it not fixed in this... there was a fix specifically for SafeNativeOverlapped being reused.

**Comment by scionwest** [comment]
Ah, so it looks like it was - and in #12659. This didn't make it into 1.1 did it?

**Comment by karelz** [comment]
Nope, that one did not make it to 1.1.

**Comment by scionwest** [comment]
Ok, im trying to get the daily build wired up for use. If I can't get that working then I'll just wait for the next release. I assume it'll be in 1.2?

**Comment by danmosemsft** [comment]
@scionwest yes, this will be in 1.2.

**Comment by danmosemsft** [comment]
Seems like we're covered so closing
