### ISSUE TITLE
Upgrade C# compiler to C# 7

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#14028]
I found out from https://github.com/dotnet/corefx/issues/13427#issuecomment-258941132 that C# 7 can now be used in corefx. However, trying to use C# 7 features does not appear to work locally; for example, this code snippet I inserted

```cs
            if (TryMove(out T[] array))
            {
                return array;
            }
```

appears to result in a syntax error from the compiler:

```
  C:\Users\james\Code\git\corefx\src\Common\src\System\Collections\Generic\LargeArrayBuilder.cs(146,31): error CS0443: Syntax error; value expected [C:\Users\james\Code\git\corefx\src\System.Linq\src\System.Linq.csproj]
  C:\Users\james\Code\git\corefx\src\Common\src\System\Collections\Generic\LargeArrayBuilder.cs(146,33): error CS1003: Syntax error, ',' expected [C:\Users\james\Code\git\corefx\src\System.Linq\src\System.Linq.csproj]
```

This was after doing a `git clean -xdf` and then `sync -p` to restore everything again. Is this expected to happen? If so, is there a way to build corefx with C# 7? (I thought the new compiler from the `Tools\` directory would be used, not the one installed on the machine.)

If it's relevant: I installed VS 2017 RC the other day and can use new language features from the IDE. However, the `csc` in my PATH (from `%PROGRAMFILES(x86)%\MSBuild\14.0\Bin`) says it's version 1.3.1 and can only handle up to C# 6.

**Comment by jkotas** [comment]
The repo builds 2.0.0-beta3 compilers. 2.0.0-beta3 does not have all C# 7 features.

I had PR to update to  2.0.0-beta5 a while ago (https://github.com/dotnet/buildtools/pull/1175), but it run into bugs in Roslyn packaging. I guess it is time to try again with  2.0.0-rc.

**Comment by mellinoe** [comment]
We've updated.
