### ISSUE TITLE
System.Net.Sockets.Socket Accept() method throws System.ArgumentException on Linux instead of SocketException when no connection to accept

### ISSUE THREAD

**Issue by avertes** [dotnet/corefx#14037]
On Windows, when using System.Net.Sockets.Socket accepting connections with Accept() method and no more connections are in queue a SocketException is thrown.

However, when same code is run on Linux, a System.ArgumentException is thrown instead.

Net Core documentation does not list ArgumentException as possible Exception. Net Core documentation does not specify what Accept throws when no requests are queued. However, .Net framework documentation states: "If you call this method using a non-blocking Socket, and no connection requests are queued, Accept throws a SocketException."

**Comment by stephentoub** [comment]
Thanks. Could you share a minimal repro that highlights the difference?

**Comment by avertes** [comment]
Hi. 

This repro just listens to port 12345 and accepts all connections. Writes "." to console when ever it hears and accepts one. Works fine on Windows. Dies on Linux immediately after first connection has arrived.

`using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Sockets;

namespace AcceptBugRepro
{
    public class Program
    {
        static void Main(string[] args)
        {
            int port = 12345;
            int backlog = 5;

            var connections = new List<Socket>();

            // create the socket
            Socket listenSocket = new Socket(AddressFamily.InterNetwork,
                            SocketType.Stream,ProtocolType.Tcp);

            IPEndPoint ep = new IPEndPoint(IPAddress.Loopback, port);
            listenSocket.Bind(ep);
            listenSocket.Blocking = false;

            // start listening
            listenSocket.Listen(backlog);

            while (true) //Loop waiting for connection(s)
            {
                var ls = new List<Socket> { listenSocket };
                Socket.Select(ls, null, null, 1000000);
                if (ls.Count>0)
                {
                    while (true)    //Read all requests in queue
                    {
                        try
                        {
                            var newConnection = listenSocket.Accept();
                            connections.Add(newConnection);
                            Console.Write(".");
                        } catch (SocketException)
                        {
                            //No more requests in queue
                            break;
                        }
                    }
                }
            }
        }
    }
}
`

**Comment by stephentoub** [comment]
@avertes, thanks for the repro.

@geoffkizer, could you take a look?

**Comment by geoffkizer** [comment]
fix is in PR #15261
