### ISSUE TITLE
WinRT API DateModified not copied and can't create folders inside some folders

### ISSUE THREAD

**Issue by massimocode** [dotnet/corefx#14048]
Hi

I'm not sure if this is the correct repository to be raising this issue. Please let me know where I should raise it if it isn't.

I'm using the Windows.Devices, Windows.Foundation and Windows.Storage libraries to write a WinRT application that will sync some files from a PC to a Windows Phone. See here (https://github.com/massimocode/windows-phone-music-sync).

However, I've noticed some annoying behaviour, as follows:
1) If I drag and drop a file onto my phone using Windows Explorer, the original file's DateModified is written to the phone. If I copy the same file using WinRT's StorageFile.CopyAsync method, the DateModified is not copied over and it seems to use the current time as the DateModified. I've tried updating the "System.DateModified" property manually after the file is copied and I get an error saying the property is read only.
2) Using Windows Explorer, I can create folders inside the phone's Music folder (which is marked as Read Only). However, using StorageFolder.CreateFolderAsync I get an error saying:
```
System.Runtime.InteropServices.COMException: Unspecified error
Cannot create items within this StorageFolder. This could be encountered if the folder was obtained by creating a query using grouping options.
```
Interestingly, I can copy files to the Music folder using the API (using the StorageFile.CopyAsync method), I just can't create folders.

Thanks guys

**Comment by karelz** [comment]
These are questions about WinRT API - nothing related to .NET or .NET Core, closing.
I don't know what is the official channel for those questions :(

@MattWhilden @richlander any idea where to route WinRT API bugs / questions.

**Comment by massimocode** [comment]
@MattWhilden  @richlander hey sorry do you have any idea where I should raise this issue?
