### ISSUE TITLE
HttpWebRequest and HttpWebResponse serialization

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#14068]
Both of these types have serialization documented as being obsoleted in NetFX. 
The current behavior in NetFX: `HttpWebRequest` will fail deserialization (internal property not serializable):
`System.Runtime.Serialization.SerializationException : Type 'System.Net.WebRequest+WebProxyWrapper' in Assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' is not marked as serializable.`

`HttpWebResponse` will pass a simple round-trip test that is currently failing in Core.

@weshaggard @danmosemsft @karelz PTAL
/cc @stephentoub @davidsh

**Comment by karelz** [comment]
@danmosemsft @weshaggard what's your advise on Serialization attributes? Can we drop them from .NET Standard when they are Obsolete in Desktop?

**Comment by danmosemsft** [comment]
The API must be there, including [Obsolete]. Possibly we could not support the actual functionality (ie throw) but generally we should.

What needs to happen
1) Paste in the [Obsolete] attributes from Desktop onto both types' ref and implementation. [Example](http://index/?query=httpWebRequest&rightProject=System&file=%5BRepoRoot%5D%5CNDP%5Cfx%5Csrc%5Cnet%5CSystem%5CNet%5CHttpWebRequest.cs&line=5229)
2) Fix the serialization and ideally add a test. If forced, make it throw instead but it's probably easy to fix, just copy desktop.

**Comment by Jiayili1** [comment]
Disabled test, reopen it.

**Comment by Jiayili1** [comment]
https://github.com/dotnet/corefx/blob/master/src/System.Net.Requests/tests/HttpRequestResponseSerializationTest.cs#L15

**Comment by karelz** [comment]
@danmosemsft how does the test removal fix the problem? You mentioned different things in your earlier reply ...

**Comment by danmosemsft** [comment]
@karelz we already decided to not support serialization and I made it throw and added a test. When I did that I overlooked this test that wants to verify it works. This test will never pass so I deleted it here.

**Comment by karelz** [comment]
@danmosemsft thanks!
