### ISSUE TITLE
Default construction of TextWriterTraceListener

### ISSUE THREAD

**Issue by Maxwe11** [dotnet/corefx#1407]
public TextWriterTraceListener()

[msdn](https://msdn.microsoft.com/en-us/library/9hhycxf3(v=vs.110).aspx) says that:
>This constructor uses the TextWriter stream as the recipient of the tracing or debugging output. **Its Name is initialized to "TextWriter".**

but it's not true. [The default is an empty string ("").](https://msdn.microsoft.com/en-us/library/system.diagnostics.tracelistener.name(v=vs.110).aspx)

**Comment by mellinoe** [comment]
Hm, the documentation does say that, but the page for "Name" itself actually says that "" is the default:

>A name for this TraceListener. The default is an empty string ("").

Also, I believe this is consistent with our desktop behavior, where the field is left uninitialized (null), but the property returns "" in that case.

**Comment by Maxwe11** [comment]
>Also, I believe this is consistent with our desktop behavior, where the field is left uninitialized (null), but the property returns "" in that case.

Exactly. Documentation for default constructor should be fixed.

**Comment by stephentoub** [comment]
@rpetrusha, sounds like we need some doc tweaks to TextWriterTraceListener.

**Comment by mellinoe** [comment]
Sorry, I completely misinterpreted what you wrote originally. Yeah, we should fix that. Unfortunately, we don't really have direct control over the msdn articles. @rpetrusha, how do we go about getting this fixed?

**Comment by rpetrusha** [comment]
I've fixed it. The revised version now appears at https://msdn.microsoft.com/en-US/library/9hhycxf3(VS.110).aspx.

**Comment by Maxwe11** [comment]
@rpetrusha nice, closing.
