### ISSUE TITLE
Cleanup System.Private.Xml tests

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#14071]
Remove commented-out tests, remove or fix skipped tests, etc.

**Comment by danmosemsft** [comment]
+netstandard 2.0 label for removing dead tests and removing or fixing skipped tests. That is part of the debt of bringing over System.Xml types and making sure they are all working well.

General test improvements/consolidation/additions are not netstandard 2.0 work and can be done at an arbitrary time and should be tracked separately.
