### ISSUE TITLE
Restore Dynamic APIs on Expression

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#14077]
Now that `System.Dynamic.Runtime` has been removed, should the `Dynamic` factory methods on `Expression` come back? They are currently hiding under the `ExpressionExtension` internal class.

Also, what's the plan for the visitors? Right now, we have `DynamicExpressionVisitor` with `VisitDynamic` but we lack the method on the `ExpressionVisitor` base type. Should this be restored as well?

**Comment by stephentoub** [comment]
@bartdesmet, it looks like this has been addressed for 2.0.  Can you confirm?

**Comment by VSadov** [comment]
Dynamic API on Expression has been added back.
ExpressionVisitor also has VisitDynamic

I think this has been addressed
