### ISSUE TITLE
Remove hack of copying NuGet dlls to get latest mappings

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#14070]
In order to get the latest nuget mappings, we decided to substitute the version of NuGet that comes inside of the CLI which today we do with [these lines](https://github.com/dotnet/corefx/blob/master/init-tools.cmd#L72-L78). We should remove that hack and figure out a way of getting latest mappings differently.

**Comment by weshaggard** [comment]
@mellinoe did this when moving to the msbuild based CLI.
