### ISSUE TITLE
Add HasAtLeast<TSource>(this IEnumerable<TSource>, int)

### ISSUE THREAD

**Issue by SamuelEnglard** [dotnet/corefx#14078]
## Motivation

When working with sequences of just `IEnumerable<T>` calling `Count()` can be very expensive if `Count()` is forced to enumerate through the whole sequence. When checking if a sequence has X elements or more calling `Count()` is not just expensive but wasteful. 

## Proposal

```diff
namespace System.Linq
{
    public static class Enumerable
    {
+       /// <summary>
+       ///     Returns if a sequence has at least a certain amount of elements.
+       /// </summary>
+       /// <typeparam name="TSource">The type of elements of <paramref name="source"/>.</typeparam>
+       /// <param name="source">An <see cref="IEnumerable{T}"/> to check the length of.</param>
+       /// <param name="atLeast">The minimum amount of items that <paramref name="source"/> should have.</param>
+       /// <returns><see langword="true"/> if <paramref name="source"/> has at least <paramref name="atLeast"/> elements. <see langword="false"/> otherwise.</returns>
+       /// <exception cref="ArgumentNullException"><paramref name="source"/> is <see langword="null"/>.</exception>
+       /// <exception cref="ArgumentOutOfRangeException"><paramref name="atLeast"/> must be zero or greater.</exception>
+       public static bool HasAtLeast<TSource>(this IEnumerable<TSource> source, int atLeast);
    }
}
```

**Comment by karelz** [comment]
It can be rewritten using as `Skip(atLeast).Any()`.
Personally I don't think it is worth a new API method - we do not want to bloat the list to unusable thing.
If it is popular API/wrapper, then I might be ok with it, but I don't think it is ...

**Comment by SamuelEnglard** [comment]
I admittedly had not thought of that! I'll leave it open in case anyone else comes up with reasons to keep it.

**Comment by karelz** [comment]
I would suggest to close it. If someone has evidence this is indeed useful, just comment here and we can reopen it.

**Comment by stephentoub** [comment]
> It can be rewritten as Skip(atLeast).Any(). Personally I don't think it is worth a new API method - we do not want to bloat the list to unusable thing. If it is popular API/wrapper, then I might be ok with it, but I don't think it is

I agree it's not worth adding another API, though it may make https://github.com/dotnet/corefx/issues/2327#issuecomment-263578679 more impactful to do.
