### ISSUE TITLE
Add System.Threading reference to System.Linq for Mono mcs

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/corefx#1408]
Mono's mcs compiler implements `yield` internally using `System.Threading.Interlocked`. This causes a compilation error on mcs when the `System.Threading` contract isn't referenced.

I've sent PRs in the past to add that reference (https://github.com/dotnet/corefx/pull/951, https://github.com/dotnet/corefx/pull/774, https://github.com/dotnet/corefx/pull/328, etc.) to projects that needed it and got the feedback that this is OK as long as it only affects unit test projects.

However, `System.Linq` is now the first library where this occurs in the actual product assembly, so I want to discuss what the best approach is. Can we simply add that reference? I talked to @marek-safar who maintains mcs and he prefers to keep the existing implementation.

/cc @stephentoub @weshaggard

**Comment by weshaggard** [comment]
I think it is acceptable to add the reference to System.Threading for System.Linq. 

cc @VSadov

**Comment by VSadov** [comment]
Adding a reference seems ok. I am a bit curious how MCS uses it.
It may be interesting to note that Roslyn CSC has similar requirement for events. Or at least used to have - we contemplated a fallback strategy for cases where CMPXCH is not available, buy I do not remember if we actually implemented it.

**Comment by akoeplinger** [comment]
Cool, I'll prepare a PR for adding the reference tomorrow :)

@VSadov this is roughly what mcs generates:

``` csharp
IEnumerator<object> IEnumerable<object>.IEnumerable<object>.GetEnumerator()
{
    if (Interlocked.CompareExchange(ref this.$PC, 0, -2) == -2)
        return (IEnumerator<object>) this;
    return (IEnumerator<object>) new MyClass.<MyTest>c__Iterator0();
}
```

vs. Roslyn:

``` csharp
IEnumerator<object> IEnumerable<object>.GetEnumerator()
{
    MyClass.<MyTest>d__0 myTestD0;
    if (Environment.CurrentManagedThreadId == this.<>l__initialThreadId && this.<>1__state == -2)
    {
        this.<>1__state = 0;
        myTestD0 = this;
    }
    else
    {
        myTestD0 = new MyClass.<MyTest>d__0(0);
        myTestD0.<>4__this = this.<>4__this;
    }
    return (IEnumerator<object>) myTestD0;
}
```

**Comment by VSadov** [comment]
Interesting. Many years ago CSC also had GetEnumerator codegen like that, but then it was changed to use CurrentManagedThreadId since that was found to be faster. 
CurrentManagedThreadId is a JIT intrinsic on CLR/Windows - it fetches the native thread ID directly via FP register and in the targeted singlethreaded scenario is a fairly cheap operation. However, it makes me think whether it is not too much of a platform-specific assumption.

**Comment by stephentoub** [comment]
> Cool, I'll prepare a PR for adding the reference tomorrow :)

@akoeplinger, I may have missed the PR.  Is this still active?

Thanks!

**Comment by akoeplinger** [comment]
Sorry, I missed updating this. The recent move to newer contract libs and project.json broke my ability to sanity check on Mono due to some bugs in mcs. I'll follow up when those are fixed and close this issue since I got my answer :)

**Comment by stephentoub** [comment]
Ok, thanks :)
