### ISSUE TITLE
rhel rid should not include a minor. rhel-7.2-x64 should be rhel-7-x64

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#14089]
Just like Debian (https://github.com/dotnet/corefx/issues/6170), minor releases are point releases. The minor should not be part of the rid.

**Comment by karelz** [comment]
cc: @janvorli

**Comment by janvorli** [comment]
cc: @mellinoe, @Petermarcu

**Comment by ellismg** [comment]
`/etc/os-release` includes the minor version in `VERSION_ID`.  The RID is constructed by the tooling using this value.

This is unlike both Debian and CentOS where they minor versions don't rev `VERSION_ID`.

**Comment by ellismg** [comment]
Note that we **do** have a rhel.7-x64) RID, which is the parent of RHEL 7.0, RHEL 7.1 and RHEL 7.2 (and future RHEL 7.X versions).

I would prefer not to bake special knowledge of RHEL's versioning scheme into the tooling (e.g to normalize them all to rhel.7-x64, like we do in some of our scripts).

**Comment by tmds** [comment]
Are there artifacts in corefx/coreclr built that target a minor version? Or do all of them target the generic rhel.7?

**Comment by svick** [comment]
@tmds Looking at [.Net Core packages on MyGet](https://dotnet.myget.org/gallery/dotnet-core) (enter "runtime.rhel" into the search field), it seems to me that all target `rhel.7`.

**Comment by ellismg** [comment]
@svick is correct.  All CoreFX, Core-Setup and CoreCLR assets are packaged for "rhel.7-x64".

**Comment by ellismg** [comment]
Given that we author our assets under the "generic" rhel.7-x64 RID and use the runtime.json graph to share these assets across RHEL minor versions and the fact that RHEL itself exposes the minor versions via `/etc/os-release`, I'm going to close this.

**Comment by tmds** [comment]
@ellismg 
If I'd create an issue for someone to change /etc/os-release on rhel providing .NET Core implementation as a rationale, but I doubt it will change.

Looking at the docs: https://github.com/dotnet/docs/blob/master/docs/core/rid-catalog.md there isn't a mention of the rhel.7-x64 rid. CentOS has the same semantics as rhel, but there is no minor.

Q: if I have a rhel 7.2 with .NET Core 1.0 installed and I upgrade my system to rhel 7.3. At this point, the RID has changed to an RID unknown to .NET Core 1.0. Will the tooling know rhel 7.3 is a specialized version of rhel 7? Or doesn't it need this info?

**Comment by ellismg** [comment]
> Q: if I have a rhel 7.2 with .NET Core 1.0 installed and I upgrade my system to rhel 7.3. At this point, the RID has changed to an RID unknown to .NET Core 1.0. Will the tooling know rhel 7.3 is a specialized version of rhel 7? Or doesn't it need this info?

@gkhanna79 can correct me if I'm wrong, but the runtime itself will continue to believe it's running on RHEL 7.2 (which is what it was built for).

The tooling would not know RHEL 7.3 was a specialized version of RHEL, you would only need this information in cases where you wanted to publish your application standalone.  In this case, you could override the tooling to pretend you were on RHEL 7.2 (this is the same as cross publishing for RHEL 7.2 from Ubuntu or Windows or whatever).

We normally augment the runtime graph after releases, so the next point version of the FTS and LTS would be taught to know about RHEL 7.3 and that it falls back to 7.2.

**Comment by gkhanna79** [comment]
> the runtime itself will continue to believe it's running on RHEL 7.2 (which is what it was built for).

This is correct. Specifically, it is the host and the not the runtime (coreclr.dll).

**Comment by tmds** [comment]
@ellismg @gkhanna79 exposing rid the minor is causing a first casualty: https://github.com/dotnet/cli/pull/5255/files

I grepped through much of the dotnet repos. This pattern is everywhere: after reading os-release, the minor is stripped from rhel. This is not a surprise, since the minor itself does nothing meaningful. coreclr and corefx are the exception where the minor is not stripped out but relies on the runtime.json which must be manually kept up-to-date (https://github.com/dotnet/corefx/commit/68c03688188cb2fd8adbfd12cadc5c6f30f99b43).

If we remove the minor from the start, there can't be issues from people using it. Scripts/programs will work on all minors or none. We can't get in this case where it is only working on some.

A small modification to these scripts is needed:
- coreclr/build.sh
- corefx/src/Native/build-native.sh

\CC @omajid @gpiercey

**Comment by omajid** [comment]
I obviously agree with just using the major RHEL version (`7`) as the identifier instead of the complete `VERSION_ID` (`7.2` or `7.3`). RHEL 7.x releases are basically bugfix releases. They may add features, but compatibility is a big goal - so users should find it mostly transparent. Treating each RHEL 7.x release as a separate version is like treating macOS 10.12 as being different from 10.12.1.

I agree that extracting the major version and handling it as a special case is adding complexity, but compared to the churn that we might expect for each 7.x release (not to mention timing, where some RHEL 7.x versions won't work), extracting-and-handling the major version might be easier and just a one-time fix.

**Comment by gpiercey** [comment]
I've made the script changes that @tmds mentioned in my local workspace and I'm in the process of building now so if it all works out fine, and the tests pass, I'll submit a PR.
