### ISSUE TITLE
Bring back TypedReference

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#14088]
TypedReference has not been very useful type so far, with non-trivial implementation cost, and that is why we have decided to not include it in .NET Standard.

However, the recent discussion #14021 revealed that it is a good building block for new high-performance reflection APIs that avoid boxing and address other reflection limitations. We should consider bringing it back.

The steps are:
1. Bring TypedReference back (to .NET Standard 2.0?)
2. Add methods to TypedReference that make it useful (e.g. use generic methods as a first class replacement for the undocumented C# `__refvalue` and similar keywords)
3. Add high-performance reflection APIs that avoid boxing (see #14021 for discussion)

This issue is tracking the first step.

**Comment by jkotas** [comment]
cc @Esidar @bartdesmet @MichalStrehovsky @davidwrighton

**Comment by karelz** [comment]
@weshaggard @danmosemsft any thoughts?

**Comment by danmosemsft** [comment]
I have no objection (I imagine the cost of (2) and (3) is the main consideration)

I'm not sure why we'd put it in Standard -- it may be present in other platforms, but it's used for (1) __arglist that is not necessarily present (https://github.com/dotnet/standard/commit/6e3ad1) and (2) these new functions which won't be present.

**Comment by weshaggard** [comment]
I also don't have any concerns as it is primarily a runtime/codegen/language feature then it is a library feature. If we did add it to .NET Standard 2.0 as @danmosemsft points out it can only contain the APIs that already exist in the full .NET framework.

**Comment by Thaina** [comment]
Could we also consider `return ref` in C# next version?

**Comment by jkotas** [comment]
@Thaina I am not sure what you mean. ref returns are part of C# 7. https://github.com/dotnet/roslyn/issues/118. Check the readme in Roslyn on how to get latest builds of C# 7 to give it a try. Also, any questions about this feature would be best asked in the Roslyn repo.

**Comment by Thaina** [comment]
@jkotas I thought you was mention this thread to me at dotnet/coreclr#8877

What I mean is reflection `GetValue` should be generic and could return ref

**Comment by terrajobst** [comment]
We can certainly expose `TypedReference` in .NET Standard, but the new methods mentioned in @jkotas' point (2) will have to wait until we can rev the standard again.

**Comment by jkotas** [comment]
I do not think we need to rush it to .NET Standard 2.0. It is good enough if we add it to netcoreapp first - together with the other APIs that will make it actually useful.

**Comment by terrajobst** [comment]
The API was already approved and it's already added to .NET Standard and .NET Core.
