### ISSUE TITLE
[WinHttp] WebSocket.ReceiveAsync throws internal exception type WinHttpException

### ISSUE THREAD

**Issue by dlstucki** [dotnet/corefx#14103]
When the remote side of the conversation closes the connection abruptly while a WinHttpWebSocket is receiving the Exception thrown is a WinHttpException.  That type is internal and therefore users cannot "catch" that specific type.  Also, it's likely a different exception type would occur on non-windows platforms and it should be consistent in order to allow writing code that works similarly across all platforms.

```
System.Net.Http.WinHttpException: The connection with the server was terminated abnormally
   at System.Net.WebSockets.WinHttpWebSocket.InternalReceiveAsync(ArraySegment`1 buffer)
   at System.Net.WebSockets.WinHttpWebSocket.<ReceiveAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Relay.WebSocketStream.<ReadAsync>d__33.MoveNext()
```

Build used:
%USERPROFILE%\.nuget\packages\System.Net.WebSockets.Client\4.3.0\runtimes\win\lib\netstandard1.3\System.Net.WebSockets.Client.dll
AssemblyVersion: 4.0.1.0
AssemblyFileVersion: 4.6.24705.01
AssemblyInformationalVersion: 4.6.24705.01. Commit Hash: 4d1af962ca0fede10beb01d197367c2f90e92c97
Timestamp: 11/4/2016 8:38 PM

**Comment by dstuckims** [comment]
The same scenario throws WebSocketException in .NET 4.5.

**Comment by davidsh** [comment]
@CIPop I think the best fix here would be to match app-compat and throw the `WebSocketException` and place the `WinHttpException` as an inner exception.

**Comment by georgiosd** [comment]
@davidsh actually this is not true. Looks like `HttpClientHandler.SendAsync` will also throw a rogue `WinHttpException`

**Comment by CIPop** [comment]
> Looks like HttpClientHandler.SendAsync will also throw a rogue WinHttpException

Thanks @georgiosd, we are aware of this. The proposal above is to switch that to what .Net Framework does and throw a HttpRequestException instead.

**Comment by CIPop** [comment]
We're considering larger architectural changes for WebSockets in 2.1.0 that may also address this issue.

**Comment by karelz** [comment]
This will be addressed by moving to managed WebSockets implementation in #9503.
