### ISSUE TITLE
Ensure that all System.Net tests are running against NetFX

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#14101]
Ensure that all System.Net Functional tests run against both Core and NetFX.

/cc @karelz @davidsh

**Comment by karelz** [comment]
@tarekgh works on infra to run all .NET Core tests on Desktop.

**Comment by tarekgh** [comment]
the infra-structure is there now. The tests may need some tweaks and @safern is already looking at that.

**Comment by karelz** [comment]
Great, FYI - @Priya91 @CIPop @davidsh @geoffkizer
