### ISSUE TITLE
XmlWriter stable build missing "Path" parameter in "Create" method

### ISSUE THREAD

**Issue by Coruscate5** [dotnet/corefx#14105]
Not sure exactly what's going on here, but in my current .NET Core project, I can't seem to use the following: 

`XmlWriter.Create(filepath, xmlwritersettings);`

The create method with that signature doesn't exist in my assembly version (4.3.0 stable). However, the method shows up in the reference code - what am I missing?

**Comment by svick** [comment]
[That overload](https://apisof.net/catalog/System.Xml.XmlWriter.Create(String,XmlWriterSettings)) does not exist in .Net Standard 1.x/.Net Core 1.0. It will exist in .Net Standard 2.0/.Net Core 1.2, which is probably why you see it in the source code.

**Comment by karelz** [comment]
It's available in daily builds: https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Private.Xml/src/System/Xml/Core/XmlWriter.cs#L666-L673

**Comment by Coruscate5** [comment]
Thanks - the XmlWriter create method using MemoryStream was fine for now, but the link to the daily/"dev" builds was helpful.
