### ISSUE TITLE
Missing SQL error code 40020, 40143, 40166, and 40540 for retry.

### ISSUE THREAD

**Issue by takekazuomi** [dotnet/corefx#14118]
About SQL Database transient error code. Reference source and corefx are are different.

Reference source
https://referencesource.microsoft.com/#System.Data/System/Data/SqlClient/SqlInternalConnectionTds.cs,457

corefx
https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlInternalConnectionTds.cs#L115

The cause is the following commit.
https://github.com/dotnet/corefx/commit/e48f6bda60018b5c3fdeefd446a67e8488b295d0

I can't found any discussion about this commit. Is it correct change ?

**Comment by danmosemsft** [comment]
@michaelaird

**Comment by vcsjones** [comment]
The discussion on the changes and reasoning starts here https://github.com/aspnet/EntityFramework/issues/237#issuecomment-167926784

**Comment by takekazuomi** [comment]
Thank you very much.
I understood the previous discussion.

Close this because it is an unnecessary Issue.
