### ISSUE TITLE
FileSystem tests leave temporary files/directories behind

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1412]
The System.IO.FileSystem tests do not fully clean up after themselves.  Here's the garbage left behind after I just did a successful run of those tests:
```
0eo3v51i.ogq
32nolsz2.r4s
dkriwxyi.tmp
FSEnumeratorTest
GetFileSystemEntries_str_str_TestDir
GetFiles_str_str_test_TestDir
gpkyxkxw.ife
ozi4vtk0.zqb
pbovqtu0.kpw
qpzuye3n.r1j
sa1uvib4.dtw
tn0gt1if.a5d   tn0gt1if.a5d
uc0dzyqf.u5h
udon0itw.mqx
ugmatydr.3eo
xj4wtgwp.ajj
ze4qacvk.fr3
```

**Comment by bpschoch** [comment]
What would be the recommended way to remove the files? IDispose.Dispose method?  Then do a if file.exists on each one and remove it?

**Comment by Maxwe11** [comment]
@bpschoch yeah, consider using (existing helper FileSystemTest class)[https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/tests/FileSystemTest.cs]
