### ISSUE TITLE
MSDN BigInteger.Equals(object) documentation is confusing.

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#14140]
The documentation for `BigInteger.Equals(object)` [claims that](https://msdn.microsoft.com/en-us/library/dd268233(v=vs.110).aspx#Syntax):

>If the obj parameter is not a BigInteger value, but it is a data type for which an implicit conversion is defined, the Equals(Object) method converts obj to a BigInteger value before it performs the comparison. 

... however, this doesn't initially appear to be what happens, given this test passes:
```
[Fact]
public static void NotEqualTests()
{
    Assert.False(BigInteger.Zero.Equals((object)0));
}
```

The documentation then goes on to use this example code:
```
const long LIGHT_YEAR = 5878625373183;

BigInteger altairDistance = 17 * LIGHT_YEAR;
BigInteger epsilonIndiDistance = 12 * LIGHT_YEAR;
BigInteger ursaeMajoris47Distance = 46 * LIGHT_YEAR;
long tauCetiDistance = 12 * LIGHT_YEAR;
ulong procyon2Distance = 12 * LIGHT_YEAR;
object wolf424ABDistance = 14 * LIGHT_YEAR;

Console.WriteLine("Approx. equal distances from Epsilon Indi to:");
Console.WriteLine("   Altair: {0}", epsilonIndiDistance.Equals(altairDistance));
Console.WriteLine("   Ursae Majoris 47: {0}", epsilonIndiDistance.Equals(ursaeMajoris47Distance));
Console.WriteLine("   TauCeti: {0}", epsilonIndiDistance.Equals(tauCetiDistance));
Console.WriteLine("   Procyon 2: {0}", epsilonIndiDistance.Equals(procyon2Distance));
Console.WriteLine("   Wolf 424 AB: {0}", epsilonIndiDistance.Equals(wolf424ABDistance));
```
... wherein `Equals(object)` isn't used at all, but only the relevant overloads.  They call out that's what they're doing, but of course it doesn't answer the apparent question of "yes, but what about _this_ method?".  I see where they were going with this, but I'm not sure it reads correctly.

**Comment by karelz** [comment]
cc @mairaw

**Comment by mairaw** [comment]
Thanks @karelz. @rpetrusha can you take a look at this documentation feedback for BigInteger?

**Comment by rpetrusha** [comment]
@Clockwork-Muse Thanks for opening this issue. The documentation is in error. No implicit conversion is performed, and the return value section should read, "**true** if the *obj* argument is a `BigInteger` object and its value is equal to the value of the current `BigInteger` instance; otherwise, **false**." And the example is misleading, since the final method call returns **false** for a reason other than the equality of values.
We'll revise the text and replace the example, and add a link here to the corrected content.

**Comment by rpetrusha** [comment]
@Clockwork-Muse We've updated the documentation for the [BigInteger.Equals(Object)](https://msdn.microsoft.com/en-US/library/dd268233(VS.110).aspx) overload on MSDN and replaced the example with one that calls the correct overload.

**Comment by karelz** [comment]
Thanks for fast turnaround @rpetrusha!
Closing as it seems to be addressed.

cc: @danmosemsft
