### ISSUE TITLE
ImmutableList<T> (and Builder) IList.Contains, IndexOf, Remove methods throw instead of return -1 given unexpected argument types

### ISSUE THREAD

**Issue by MihaMarkic** [dotnet/corefx#1414]
A bit longer story

http://blog.rthand.com/post/2015/04/10/A-hidden-bug-in-Windows-Stores-ComboBox.aspx

Basically a Windows Store (8.1 and 10 at least) ComboBox first tries ComboBoxItem against its ItemsSource IList.IndexOf and if that gracefully fails (returns -1) then it tries with the actual type. This works with normal List<T> because this guy returns -1 when an incompatible type is used, where ImmutableList<T> throws an exception (doesn't do any check actually) and ComboBox doesn't understand that very well.
To make it worse ComboBox doesn't perform this stunt immediately but only after a while (when one scrolles some of its items).

Now, I'd say that this is ComboBox' fault but who knows.

**Comment by mikedn** [comment]
> Now, I'd say that this is ComboBox' fault but who knows.

The [documentation](https://msdn.microsoft.com/en-us/library/system.collections.ilist.indexof(v=vs.110).aspx) of `IList.IndexOf` doesn't mention any exceptions but that's not very relevant as neither `IList.Add` mentions the possibility of an `ArgumentException` yet `List<T>.IList.Add` has no choice but to throw. 

The [documentation](https://msdn.microsoft.com/en-us/library/bb352278(v=vs.110).aspx) of `List<T>.IList.IndexOf` claims that an `ArgumentException` is thrown if the item is of the wrong type but the actual [implementation](http://referencesource.microsoft.com/#mscorlib/system/collections/generic/list.cs,662) never does this.

It's a bit of a mess but I'm tempted to say that the `List<T>.IList.IndexOf` behavior is correct despite the documentation and that `ImmutableList<T>.IList.IndexOf` behaves incorrectly.

**Comment by MihaMarkic** [comment]
Yeah. Most probably is a gray area. OTOH WPF ComboBox doesn't have these problems.

**Comment by Aevitas** [comment]
If the WPF combo box doesn't exhibit the same behaviour when using the exact same `ImmutableList`, I'm inclined to say this isn't a problem with `ImmutableList<T>`, but with the platform's specific implementation of the ComboBox instead.

**Comment by AArnott** [comment]
The docs for [`IList.IndexOf`](https://msdn.microsoft.com/en-us/library/system.collections.ilist.indexof(v=vs.110).aspx) says it calls `object.Equals(object)` on each value in the collection. So assuming these never throw an exception, neither should `IList.IndexOf` just because the type isn't what was expected. So it sounds like we should alter `ImmutableList.IList.IndexOf` behavior to conform.

**Comment by AArnott** [comment]
This applies to more than `IndexOf`. The `IList.Contains(object)` and `IList.Remove(object)` methods have the same problem. I'll fix them altogether.
