### ISSUE TITLE
Installer for .net core 1.1.0 hanging

### ISSUE THREAD

**Issue by genericrandom** [dotnet/corefx#14159]
I'm trying to install version 1.1, but the installer seems to freeze indefinitely right at the beginning.  When I terminate the installer form the task manager, the log dump seems to say that the process stops at 
[215C:0C90][2016-12-01T23:19:06]i012: Connected to elevated engine. 
before hitting the error.  I'm already running this as administrator as well.

![initializing](https://cloud.githubusercontent.com/assets/24309130/20823466/2f431088-b822-11e6-95ed-d0b0140a410f.png)

**Comment by karelz** [comment]
Please file it in https://github.com/dotnet/core-setup repo.

cc: @schellap @gkhanna79

**Comment by gkhanna79** [comment]
This installer comes from CLI. Please file an issue in https://github.com/dotnet/cli.

CC @livarcocc @piotrpMSFT
