### ISSUE TITLE
Provide API for Console window size changed event

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#14152]
API:
Could be an event like CancelKeyPress
or a value returned by ReadKey.

Threading:
Run as part of call to Read

Implementation:
Unix: SIGWINCH
Windows: SetConsoleMode ENABLE_WINDOW_INPUT

**Comment by karelz** [comment]
Do you have [API proposal](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md) in mind?

**Comment by jnm2** [comment]
As long as it's synchronous! This might help me finally get status lines working in spite of Windows 10's text reflowing: https://stackoverflow.com/questions/34210216.

**Comment by tmds** [comment]
## Proposed API

### Proposal 1: emit event
```C#
public static class Console
{
    public static event EventHandler WindowSizeChanged;
}
```

example:

```C#
public class Program
{
    public static void Main(string[] args)
    {
        Console.WindowSizeChanged += OnWindowSizeChanged;
        while (true)
        {
            Console.ReadKey(intercept: true); // Read* methods emit WindowSizeChanged event
        }
    }

    private static void OnWindowSizeChanged(object sender, EventArgs e)
    {
        Console.CursorTop = 0;
        Console.CursorLeft = 0;
        Console.WriteLine($"Window size is {Console.WindowWidth}x{Console.WindowHeight}");
    }
}
```

### Proposal 2: return as Key

```C#
public static class Console
{
    public static bool DetectWindowResize;
}
public enum ConsoleKey
{
    ...
    WindowResized
}
```

example:

```C#
public class Program
{
    public static void Main(string[] args)
    {
        Console.DetectWindowResize = true;
        while (true)
        {
            var consoleKeyInfo = Console.ReadKey(intercept: true);
            if (consoleKeyInfo.Key == ConsoleKey.WindowResized)
            {
                Console.CursorTop = 0;
                Console.CursorLeft = 0;
                Console.WriteLine($"Window size is {Console.WindowWidth}x{Console.WindowHeight}");
            }
        }
    }
}
```

## Notes

- The rationale for triggering the event as part of the Read (both proposals) is because both the Read and the event are reasons to to update the UI.
- An explicit action (e.g. proposal 1: subscribe to event, proposal 2: set property to true) allows to avoid a performance penalty when the user is not interested in resize events. It can also be used to throw PlatformNotSupportedException.

**Comment by tmds** [comment]
@karelz is this okay as an API proposal?

**Comment by karelz** [comment]
@ianhays is the expert on Console - he should comment and do first-level API review.

**Comment by ianhays** [comment]
Either of these API look good to me. The first is probably more intuitive, though only triggering on a read seems like a potential "gotcha" if people aren't expecting it.

Some questions/thoughts off the top of my head:
- I haven't seen many (any?) requests for this API before. Do you have some example use cases of when it would be valuable to have?
- Do the platform-specific API's you mentioned in the OP behave similarly? 
- Do the API's trigger at the end of the resize or at the beginning? Since resizing a window can be a continuous process, are there potential issues in having the event trigger at either end of the resize process?

**Comment by karelz** [comment]
I would love to see "motivation and usage" section which is simple to understand even for folks who (like me) don't have any background for these APIs in native code/other platforms and possibly don't know the patterns for other similar APIs (CancelKeyPress). Answering @ianhays's questions lead to that as well IMO.

**Comment by tmds** [comment]
> Either of these API look good to me. The first is probably more intuitive, though only triggering on a read seems like a potential "gotcha" if people aren't expecting it.

I also think the first proposal is more intuitive. However, the Window API (see next answer) is closer to the second proposal and also ncursues is also using the second API. All-tough less intuitive at first, it may be the better option.

> I haven't seen many (any?) requests for this API before. Do you have some example use cases of when it would be valuable to have?

The use case is creating TUI (text user interface) application, these are GUI applications on the console. For these application it is desirable to rearrange the content based on the available visible space, like reflowing text or reposition UI elements. For example, your console editor does this when resizing the terminal window.

> Do the platform-specific API's you mentioned in the OP behave similarly?

No. On Windows it looks like this can be returned by the read call. On Linux this is a signal.

> Do the API's trigger at the end of the resize or at the beginning? Since resizing a window can be a continuous process, are there potential issues in having the event trigger at either end of the resize process?

Right. The operating system is responsible for providing 'enough' events.

**Comment by ianhays** [comment]
The proposal and use cases seem reasonable to me. Let's nail down which API we want, then take it to API review. A sample implementation, tests or code using the API would be helpful to get the ball rolling as well.

**Comment by stephentoub** [comment]
I like:
```
public static event EventHandler WindowSizeChanged;
```
but I don't understand the suggested rationale for explicitly invoking the event when reading.  If someone wants to invoke their code/callback when they read, they can do so explicitly; we shouldn't artificially raise the WindowsSizeChanged event if we have no reason to believe that the window size has changed.

**Comment by karelz** [comment]
@tmds @joperezr @ianhays what is left to make the API ready for review? There was ask for sample code - @tmds is it something you could put together?

**Comment by tmds** [comment]
@karelz when I created the issue I thought if would be interesting to have this to make more fancy console applications. Since I didn't get request for this and the activity on this issue is low, I'm not looking into it. Did you get a request for this? Or are you checking up on open issues? If you want to close this due to lack of progress, that is ok for me.

**Comment by karelz** [comment]
I was just checking on older API suggestions. Closing for now due to low interest.
