### ISSUE TITLE
Process raises Exited events even when EnableRaisingEvents = false

### ISSUE THREAD

**Issue by mbinette91** [dotnet/corefx#14157]
(as discussed in in PR #11998)

The documentation should be updated to reflect that EnableRaisingEvents=false offers no guarantee that Exited events will not be raised. [context: depends on the state of a private flag (_exited) and properties you query might still trigger events]

Some interesting passages to update:

**Process.EnableRaisingEvents Property**
 
> Gets or sets whether the Exited event should be raised when the process terminates.

> true if the Exited event should be raised when the associated process is terminated (through either an exit or a call to Kill); otherwise, false. The default is false.

> The EnableRaisingEvents property indicates whether the component should be notified when the operating system has shut down a process. 

> When an associated process exits after being shut down by the operating system either through a normal or abnormal termination, the operating system notifies each process component to which the process was associated, as long as the component's EnableRaisingEvents value is **true**.

> Setting EnableRaisingEvents to false saves system resources.

**Comment by mbinette91** [comment]
@Priya91 Sorry for the delay in creating the issue :)

**Comment by karelz** [comment]
Can you please suggest the updated [MSDN docs](https://msdn.microsoft.com/en-us/library/system.diagnostics.process.enableraisingevents(v=vs.110).aspx) text?

cc: @mairaw

**Comment by mbinette91** [comment]
Suggested modifications in **bold**.

>true if the Exited event should be raised when the associated process is terminated (through either an exit or a call to Kill); otherwise, false. The default is false. **Note that the Exited event might still be raised even if this value is false.**

>The EnableRaisingEvents property **suggests** whether the component should be notified when the operating system has shut down a process.

>When an associated process exits after being shut down by the operating system either through a normal or abnormal termination, the operating system notifies each process component to which the process was associated ~as long as~ **if** the component's EnableRaisingEvents value is true **(and possibly also when it's false)**. 
[OK, I give up on this one, no matter how I try to word it, it sounds bad]

>Setting EnableRaisingEvents to false **can** save~s~ system resources.

**Comment by Priya91** [comment]
Thanks @mbinette91

**Comment by mairaw** [comment]
Issue moved to [dotnet/docs #1938](https://github.com/dotnet/docs/issues/1938) via [**ZenHub**](https://www.zenhub.com/)
