### ISSUE TITLE
Profiling tools on linux

### ISSUE THREAD

**Issue by agoretsky** [dotnet/corefx#14162]
Is there any tools to take memory dump and see objects of running .NET Core app on linux? I have memory leak problem on linux, but on windows everything is ok, so I can't use dotMemory. 
Which tools do corefx/coreclr teams use to profile apps on linux?

**Comment by karelz** [comment]
We recommend [PerfCollect](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/linux-performance-tracing.md) with PerfView (Windows only)

Blog post: https://blogs.msdn.microsoft.com/vancem/2016/10/07/collecting-performance-data-on-linux-using-perfcollect-and-perfview/

**Comment by jamiegs** [comment]
I know this is old but I'm trying to find a solution for this also. The original question was asking for memory dump info, but the suggested solution seems to be focused on CPU profiling.

**Comment by karelz** [comment]
You can do memory investigations via PerfCollection & PerfView on Linux -- @brianrob @vancem should be able to confirm.
