### ISSUE TITLE
All Win7 runs failing

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#14165]
Lots of errors like:
```
error MSB4018: The "GetTargetMachineInfo" task failed unexpectedly. [D:\j\workspace\outerloop_win---b280fd23\src\System.Net.Requests\src\System.Net.Requests.csproj]
error MSB4018: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B) [D:\j\workspace\outerloop_win---b280fd23\src\System.Net.Requests\src\System.Net.Requests.csproj]
error MSB4018:    at Interop.mincore.GetNativeSystemInfo(SYSTEM_INFO& lpSystemInfo) [D:\j\workspace\outerloop_win---b280fd23\src\System.Net.Requests\src\System.Net.Requests.csproj]
error MSB4018:    at System.Runtime.InteropServices.RuntimeInformation.get_OSArchitecture() [D:\j\workspace\outerloop_win---b280fd23\src\System.Net.Requests\src\System.Net.Requests.csproj]
error MSB4018:    at Microsoft.DotNet.Build.Tasks.GetTargetMachineInfo.Execute() [D:\j\workspace\outerloop_win---b280fd23\src\System.Net.Requests\src\System.Net.Requests.csproj]
error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [D:\j\workspace\outerloop_win---b280fd23\src\System.Net.Requests\src\System.Net.Requests.csproj]
error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [D:\j\workspace\outerloop_win---b280fd23\src\System.Net.Requests\src\System.Net.Requests.csproj]
```

**Comment by weshaggard** [comment]
@JohnChen0  @AlexGhiondea do you guys think this might be related to https://github.com/dotnet/corefx/issues/13566?

**Comment by JohnChen0** [comment]
This appears to be the same issue as #13566. Which version of CoreFX was used when the these failures were observed? #13566 should have been fixed by PR #13440.

**Comment by stephentoub** [comment]
It's been failing every build for the last few weeks:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_debug/

**Comment by JohnChen0** [comment]
Since the call stack in the failure mentioned `Interop.mincore.GetNativeSystemInfo`, it was definitely using an old build of CoreFX. After PR #13440, `Interop.mincore.GetNativeSystemInfo` no longer exists and has been replaced by `Interop.Kernel32.GetNativeSystemInfo`. It appears that during the build process, the build tools was still using an old version of CoreFX. Upgrading it to use a more recent version of CoreFX should fix the failures.

**Comment by weshaggard** [comment]
@dleeapho @markwilkie looks like we either need to update the CLI or fix it such that the api-sets are correctly pulled so the Win7 builds work.

**Comment by dagood** [comment]
Upgrading the CLI we use to pick up a newer CoreFX sounds reasonable, so I'm working on that.
/cc @crummel

**Comment by weshaggard** [comment]
Note that it might not be as easy as that because the @JohnChen0 changes to removed dependencies on api-sets is a very recent change and I don't know if we should be updating our tools to depend on that new of a corefx prerelease.

**Comment by dagood** [comment]
I've set up a Win7 x64 VM, but I haven't been able to repro. I stuck this into `build.proj` and it ran fine:

```
<Message Importance="High" Text="A $(TargetArch)" />
<Message Importance="High" Text="A $(TargetOS)" />
<GetTargetMachineInfo>
      <Output Condition="'$(TargetArch)'==''" TaskParameter="TargetArch" PropertyName="TargetArch" />
      <Output Condition="'$(TargetOS)'==''" TaskParameter="TargetOS" PropertyName="TargetOS" />
</GetTargetMachineInfo>
<Message Importance="High" Text="B $(TargetArch)" />
<Message Importance="High" Text="B $(TargetOS)" />
```
```
A
A
B x64
B Windows_NT
```

I did see, though, that `System.Runtime.InteropServices.RuntimeInformation` is from tool-runtime's `NETStandard.Library` dependency, and doesn't seem to be in the CLI's shared framework, so I don't know if upgrading CLI will do any good.

Since I don't have a repro, I'm not sure if upgrading `NETStandard.Library` or the `RuntimeInformation` package in tool-runtime/project.json will help, but it seems like the way to go to get a newer dll.

**Comment by weshaggard** [comment]
Update the CLI won't fix this. I think there are two options.

1. We make sure we include the api-set forwarders in the buildtools closure when running on win7.
2. We update just the RuntimeInformation package which no longer needs the forwarders.

I would go with option (2) which is what you have a PR up for now assuming its package closure doesn't cause any other issues.

**Comment by dagood** [comment]
My buildtools fix got merged in with https://github.com/dotnet/corefx/pull/14500, and the linked win7 Jenkins build got test failures rather than a build failure: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_debug/39/. Does that mean this issue is fixed? More to check?

**Comment by weshaggard** [comment]
I think that qualifies as fixing this issue. We should file other issues for the test failures. Thanks @dagood.
