### ISSUE TITLE
Get a rough idea of the size of a BigInteger

### ISSUE THREAD

**Issue by verybadcat** [dotnet/corefx#14178]
It would be terrific if there were a fast API for getting a rough idea of the absolute value of a BigInteger, say to within a factor of a billion or so. Something like the size of the private _bits array would be fine.

This is useful for calculator apps and the like, as you want to be able to tell if an operation will definitely overflow before attempting it.

**Comment by karelz** [comment]
If the application has a limit - what's wrong with asking the app to hard code the limit and compare the BigInteger with it before performing operations, etc.?

**Comment by Clockwork-Muse** [comment]
Indeed.  You're normally going to run out of screen space first - `BigInteger` can happily and easily give you a number with ~20k digits (~8kB?), and that's nowhere near the limits.  You could have a number, in theory, up to 2GB of ints, but in practice you're not going to be able to allocate the necessary contiguous array long before that.
Even then, limits due to the results of operations have ways to sneak up on you - remember, there's a `Pow` method...

**Comment by verybadcat** [comment]
Consider the Pow function. You are going to get into trouble if the exponent times the log of the base is too big. There is not actually a way to test that with hard-coded values, unless you are willing to keep a lot of them. And for large bases, actually taking the log is both slow and unnecessary. A rough idea of the size is plenty of info in such cases. If the size is small, you can go ahead and take the log, and it will be quick.

For product, you will get into trouble if the sum of the numbers of digits is too big. That's actually less troubling than the Pow case; you may just be willing to take the product, then drop it if it's too big.

For functions like Comb (or Choose, or whatever you want to call it), it is yet another computation . . .

**Comment by verybadcat** [comment]
The Pow case is by far the most important. If you don't want to expose the size of the bits array, a function like Pow(x, y, overflowPastThisManyBinaryDigits) would handle it. But you'd still need a way to return "overflow".

**Comment by verybadcat** [comment]
Yet another option would be a fast BigInteger.Log2 function. I'm not sure why the time to compute BigInteger.Log(someBigNumber, 2) is so much longer than Math.Log(someDouble, 2). But it definitely is.

**Comment by karelz** [comment]
Let's say your app has `limit` for numbers it can display / wants to deal with. For addition, multiplication, you just test the result as you said. For `pow`, you want to prevent the expensive calculation (disclaimer: I didn't check that it is truly so expensive, I am relying on your info and assuming the digits might easily grow uncontrollably) -- so basically you want to check `x^y < limit`, which is `y < log_x(limit)`.
Computing `log_x(limit)` should be fast enough for UI app like Calculator.

> I'm not sure why the time to compute BigInteger.Log(someBigNumber, 2) is so much longer than Math.Log(someDouble, 2)

`log_2(double)` will be fast as it uses FPU instruction. [`BigInteger.Log`](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Numerics/src/System/Numerics/BigInteger.cs#L686) has some code, but still pretty straightforward.

**Comment by Clockwork-Muse** [comment]
To clarify - my remarks were not meant to be an endorsement of this idea, but speculation that intrinsic limitations of the situation (such as displayed digits in a calculator)  will show up long before the size of `BigInteger` becomes an issue.   `Math.Pow(2, 65536)` results a number with 20k digits, but takes almost no time to calculate (although this is probably helped by the fact that it's a power of two).  Even doing it as a string of multiplication appears to complete instantly.

**Comment by karelz** [comment]
Looks like the problem can be easily solved without new API.
Please let us know if you strongly disagree.

**Comment by verybadcat** [comment]
The user might be doing a summation, for example, where they take a lot of powers. It could also happen in a graph, though powers in graphs are frequently not of integer type. I've attached a test case for this. The problem comes when the base is large. I don't know why BigInteger.Log(x, 2) takes so long when x is large, as you should only need to look at the number of bits and the most significant 64 bits or so, but it does. 

For a sum with small base, I got 479ms doing a dummied - up check without using a log, and 500ms when using the log. That's clearly acceptable.

BUT if the base got larger (and dividing the number of terms by 10), I saw 147ms using the dummied-up log-free check, but 309ms using the log. IMO, that's not acceptable, though you may think otherwise.

It may be that the real answer to my issue is to speed up BigInteger.Log(x, 2) for large x.

[BigIntegerPowerTimingTests.zip](https://github.com/dotnet/corefx/files/637841/BigIntegerPowerTimingTests.zip)

**Comment by verybadcat** [comment]
Looking at your note again -- part of what you are thinking is that it's always OK to just take the power? I'd disagree. Consider that (10^100+1)^20 might be fine, but something like (10^10000+1)^20 could hang a small device. And if it doesn't, a few more iterations of adding 1 and taking the 20th power surely would.

**Comment by karelz** [comment]
What kind of perf framework did you use? https://github.com/dotnet/BenchmarkDotNet

**Comment by verybadcat** [comment]
None. It's just an NUnit test combined with a self-contained version of my Power function, and a #define to take the log of the base or use a constant value. 80 lines in all. I ran it in the middle of my usual test run. VS reports the time for each test.

The results are consistent with other checks I've done, showing that BigInteger.Log(x, 2) takes increasing amounts of time as x gets large, e.g. in Xamarin Studio on my Mac.

Now that I think about it, I'm realizing it would have made more sense to use your current sources, rather than built-in System.Numerics as I've been doing. Also I should let the "constant" vary as it would in real cases. 

I'll take a look at benchmark.net.
