### ISSUE TITLE
Proposal: string.Join with a default separator

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#14193]
## Background

When you want to dump the contents of multiple collections to the console, it can be very cumbersome to have to repeatedly write `Console.WriteLine(string.Join(", ", collection))` and type `", ", ` each time.

## Proposal

We should consider adding an overload of `string.Join` that accepts no separator and joins with `' '`. It would be analagous to how, today, `str.Trim()` is equivalent to calling `str.Trim(s_allWhiteSpaceChars)`.

```cs
namespace System
{
    public sealed class String
    {
        public static string Join(params string[] value);
        public static string Join(params object[] values);
        public static string Join<T>(IEnumerable<T> values);
    }
}

// Usage:
Console.WriteLine(string.Join(col)); // Quickly dump `col`
```

## Implementation

```cs
public static string Join(params string[] value) => Join(' ', value);

public static string Join(params object[] values) => Join(' ', values);

public static string Join<T>(IEnumerable<T> values) => Join(' ', values);
```

## Notes

This was originally a proposal for adding instance join overloads to `String`, but seeing as we already have 12 overloads I figured that wasn't such a great idea.

cc @justinvp @AlexGhiondea @svick

**Comment by justinvp** [comment]
I'm not sure it's worth adding any new overloads for this. There are already a lot and adding more will increase the cognitive load for users when looking at the list of overloads in intellisense/documentation and trying to decide which one to use. Trim didn't require additional overloads to support its default.

**Comment by JonHanna** [comment]
How much of a default is `' '`? The fact that the example given at the start of the post is something else (`", "`) adds to my doubts on that. Certainly I don't think it's as much a wide-ranging default as whitespace is for `Trim`.

**Comment by AlexGhiondea** [comment]
I agree. I am not seeing a lot of advantages to having this API in Core.

**Comment by svick** [comment]
I thought some data might be useful here, so I looked at 1000 most recently updated small C# GitHub repos, looking for `string.Join` calls where the first parameter is a literal. The results:

| | count |
|---|---|
| total | 2470 |
| `","` | 612 |
| `", "` | 571 |
| `" "` | 260 |
| `"&"` | 182 |
| `";"` | 149 |
| `""` | 102 |
| `"\n"` | 98 |
| `"; "` | 57 |
| `"|"` | 52 |
| `"_"` | 43 |

Based on this sample, I would conclude that comma and comma+space are almost tied, so there is no clear choice of default between the two. Though it probably shouldn't be space.

**Comment by AlexGhiondea** [comment]
Thanks @svick for the search! While it might be useful to have a parameter-less method for this, it does not look like there is a clear default that we can use for this.

**Comment by stefan-schweiger** [comment]
@jamesqo while I think it's not a good idea to add a default separator to core, if it's to cumbersome for you personally, you could just use something like this:

```
public static string ToString<T>(this IEnumerable<T> source, string separator)
{
    return string.Join(separator, source);
}

public static string ToString<T>(this IEnumerable<T> source, string separator)
{
    return source.ToString(",");
}
```
