### ISSUE TITLE
Vector2 and Vector3 Projection

### ISSUE THREAD

**Issue by rtlayzell** [dotnet/corefx#142]
The current source includes public static methods for reflection of a vector about a unit vector normal but the underlying vector projection is also useful by itself.

Proposing:

```C#
public static Vector2 Project(Vector2 vector, Vector2 component) { ... }
//...
public static Vector3 Project(Vector3 vector, Vector3 component) { ... }
```
I'll wait for feed back before trying to submit a pull request.

**Comment by ellismg** [comment]
@rtlayzell Do you mind fleshing the above APIs out a little bit?  It's hard for me to understand exactly what you want?  An outline of the API review process is [here](https://github.com/dotnet/corefx/wiki/API-Review-Process#steps).

**Comment by joshfree** [comment]
I'm closing this request from last November; feel free to reactivate it when the additional info @ellismg asked for is ready.  Thank you
