### ISSUE TITLE
ConcurrentQueue<T> doesn't reuse segments

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#14207]
ConcurrentQueue<T> allocates a new Segment for every 32 elements, which means that every T added has space allocated for it, just in chunks.

**Comment by benaadams** [comment]
ye olde ABA problem? Do you see solution that could also be back ported to Threadpool?

**Comment by stephentoub** [comment]
> ye olde ABA problem?

No, I'm implementing a different solution that's not subject to it (assuming I do it correctly).

> Do you see solution that could also be back ported to Threadpool?

Back ported to where?  You mean the global queue?  If I'm successful, maybe.

**Comment by omariom** [comment]
That's going to be interesting!
