### ISSUE TITLE
publishing self contained apps hang indefinitly on web api projects

### ISSUE THREAD

**Issue by PaybackMan** [dotnet/corefx#14209]
This is a consistent problem for me. Happens when trying to publish from VS or cli. Only one framework in use ( "win10-x64" ) . Have not tried yet with other framework monikers

**Comment by karelz** [comment]
Does it happen on more than one machine?
@piotrpMSFT can you please help route it?

**Comment by piotrpMSFT** [comment]
Hard to route just yet. Would be great to get a /v:diag trace of the publish operation. I believe Web Api goes through a special publish path @mlorbetske would know about, but it may be in the default Publish in CLI...

**Comment by mellinoe** [comment]
@PaybackMan We will need more information about this for it to be actionable. Please re-open if you have are still experiencing this problem and are able to provide more info.
