### ISSUE TITLE
Running build.sh fails on Linux kernel 4.6.x

### ISSUE THREAD

**Issue by naamunds** [dotnet/corefx#14215]
Due to https://github.com/dotnet/coreclr/issues/6016, running build.sh fails on Linux kernel 4.6.x.  (See also https://github.com/dotnet/cli/issues/3681).

> Installing dotnet cli...
> Restoring BuildTools version 1.0.27-prerelease-01029-01...
> ./init-tools.sh: line 169: 31125 Segmentation fault      (core dumped)

I was able to work around this locally by back-leveling the version in DotnetCLIVersion.txt from the current `1.0.0-preview3-003223` to `1.0.0-preview2-003131` and accordingly updating the __DOTNET_LOCATION variable in init-tools.sh:
`__DOTNET_LOCATION="https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/${__DOTNET_TOOLS_VERSION}/${__DOTNET_PKG}.${__DOTNET_TOOLS_VERSION}.tar.gz"`

@dagood Was the primary reason for updating to 1.0.0-preview3-003223 in #11387 to add support for Ubuntu on Windows?  Would 1.0.0-preview2-003131 include that support?

Alternatively, the CoreCLR issue is also fixed in the latest preview3 and preview2.1, but it is not trivial to uptake either of those.  Preview3 now uses MSBuild instead of project.json, but the buildtools project that init-tools restores is specified as a project.json.  Preview2.1 uses the 1.1 shared framework, but buildtools currently depends on the 1.0 shared framework.

/cc @dleeapho @ellismg

**Comment by dagood** [comment]
The first reason was to get buildtools on an RTM shared framework, but Ubuntu on Windows support was something we wanted to make sure it addressed. Judging by dates, that CLI might have the fix, but as far as I know, testing it out would involve either trying it on a machine or searching through sources to figure out if the version of CoreCLR the CLI build used has the fix. @ericeil Do you have a good way to tell if Ubuntu on Windows works for a CLI?

`preview3-003223` also has bootstraps/support for Fedora 24 and Alpine that `preview2-003131` doesn't.

Technically there is `dotnet restore-projectjson` in `preview4-004189` (example--it's what I had laying around) that we might be able to use, but I don't know the intent of that command.

/cc @mellinoe (some more bootstrapping might be needed)

**Comment by mellinoe** [comment]
@dagood Can't we use the preview2.1 build? It is running on top of the 1.1 shared framework so I think we would need to change the tool deps.json files in buildtools. But it supports all the new distros, minus Alpine, and should have the 4.6 kernel fix. And we can just re-upload Alpine's because it's a fake bootstrap version anyways.

**Comment by mellinoe** [comment]
Oops, just realized preview2.1 was mentioned originally. I'm pretty sure the only work is literally just find/replacing the strings in those deps.json files.

**Comment by dagood** [comment]
Good to hear that sounds reasonable, my main concern there was other platform support or other things that may have changed between 2, 3, and 2.1. (Things like the NuGet capitalization breaking change.) I haven't had time yet to actually try it out and see.

**Comment by dagood** [comment]
@mellinoe https://github.com/dotnet/buildtools/pull/1286 is coming through, which uses shared framework 1.1.0 to let corefx/coreclr change to preview2.1. To keep Alpine support, which CLI version are you saying we should reupload?

**Comment by dagood** [comment]
A CoreFX official build has completed since https://github.com/dotnet/corefx/pull/14933 was merged, which updated CLI to one that has the 4.6.x fix. Closing as resolved.
