### ISSUE TITLE
System.Collections.sln fails to build in VS unless built from the command-line first

### ISSUE THREAD

**Issue by naamunds** [dotnet/corefx#14211]
## Steps to reproduce the issue
1.  Delete the "bin" directory from your local repo.
2.  Open src\System.Collections\System.Collections.sln in Visual Studio 2015.
3.  Build the solution in VS.

## Expected behavior
The build succeeds.

## Actual behavior
The build fails with several errors like `error CS0006: Metadata file 'C:\Repos\corefx\bin\Windows_NT.AnyCPU.Debug\System.Diagnostics.Debug\System.Diagnostics.Debug.dll' could not be found`

Here's the complete output:

> 1>------ Build started: Project: System.Collections (src\System.Collections), Configuration: Debug Any CPU ------
> 2>------ Build started: Project: System.Collections (ref\System.Collections), Configuration: Debug Any CPU ------
> 3>------ Build started: Project: System.Collections.Tests, Configuration: Debug Any CPU ------
> 4>------ Build started: Project: System.Collections.Performance.Tests, Configuration: Debug Any CPU ------
> 1>CSC : error CS0006: Metadata file 'C:\Repos\corefx\bin\Windows_NT.AnyCPU.Debug\System.Diagnostics.Debug\System.Diagnostics.Debug.dll' could not be found
> 1>CSC : error CS0006: Metadata file 'C:\Repos\corefx\bin\AnyOS.AnyCPU.Debug\System.Runtime\netstandard1.7\System.Runtime.dll' could not be found
> 2>  System.Collections -> C:\Repos\corefx\bin\ref\System.Collections\4.1.0.0\System.Collections.dll
> 4>C:\Repos\corefx\Tools\sign.targets(70,5): error : C:\Repos\corefx\bin/obj/ref/System.Collections/4.1.0.0/System.Collections.dll: I/O error reading or writing PE file: The process cannot access the file 'C:\Repos\corefx\bin\obj\ref\System.Collections\4.1.0.0\System.Collections.dll' because it is being used by another process.
> 4>  System.Collections -> C:\Repos\corefx\bin\ref\System.Collections\4.1.0.0\netstandard1.7\System.Collections.dll
> 4>  System.Collections -> C:\Repos\corefx\bin\AnyOS.AnyCPU.Debug\System.Collections\net463\System.Collections.dll
> 4>CSC : error CS0006: Metadata file 'C:\Repos\corefx\bin\Windows_NT.AnyCPU.Debug\System.Diagnostics.Debug\System.Diagnostics.Debug.dll' could not be found
> 4>CSC : error CS0006: Metadata file 'C:\Repos\corefx\bin\AnyOS.AnyCPU.Debug\System.Runtime\netstandard1.7\System.Runtime.dll' could not be found
> 4>CSC : error CS0006: Metadata file 'C:\Repos\corefx\bin\AnyOS.AnyCPU.Debug\System.Resources.ResourceManager\uap101aot\System.Resources.ResourceManager.dll' could not be found
> 4>CSC : error CS0006: Metadata file 'C:\Repos\corefx\bin\AnyOS.AnyCPU.Debug\System.Runtime\uap101aot\System.Runtime.dll' could not be found
> 4>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3962,5): error MSB3030: Could not copy the file "C:\Repos\corefx\bin\AnyOS.AnyCPU.Debug\System.Collections\System.Collections.dll" because it was not found.
> 3>  System.Diagnostics.Debug -> C:\Repos\corefx\bin\ref\System.Diagnostics.Debug\4.1.0.0\System.Diagnostics.Debug.dll
> 3>  System.Diagnostics.Debug -> C:\Repos\corefx\bin\Windows_NT.AnyCPU.Debug\System.Diagnostics.Debug\net463\System.Diagnostics.Debug.dll
> 3>  System.Diagnostics.Debug -> C:\Repos\corefx\bin\Windows_NT.AnyCPU.Debug\System.Diagnostics.Debug\System.Diagnostics.Debug.dll
> 3>  System.Diagnostics.Debug -> C:\Repos\corefx\bin\Unix.AnyCPU.Debug\System.Diagnostics.Debug\System.Diagnostics.Debug.dll
> 3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3962,5): error MSB3030: Could not copy the file "C:\Repos\corefx\bin\AnyOS.AnyCPU.Debug\System.Collections\System.Collections.dll" because it was not found.
> ========== Build: 1 succeeded, 3 failed, 0 up-to-date, 0 skipped ==========

## Workaround
Build the test project from the command-line: `msbuild src\System.Collections\tests\System.Collections.Tests.csproj`.  Then building from VS works.

**Comment by mellinoe** [comment]
Lots of things have been overhauled since this was filed. Note that you do need to run `build.cmd` once from the command-line before building any projects in corefx.
