### ISSUE TITLE
Question regarding System.Reflection.Metadata

### ISSUE THREAD

**Issue by jonathanbyrne** [dotnet/corefx#14219]
In the past, if I needed reflection data for an assembly but did not want it in the main AppDomain, I would load it into a temporary AppDomain which would only exist until I extracted the desired reflection information.  With no AppDomains in .NET Core, my understanding is that System.Reflection.Metadata is recommended for this type of scenario.

I imagine that System.Reflection.Metadata was implemented with structs and handles to improve performance for low level operations.  While that decision makes sense, it means the API is a lot more difficult to use compared to normal reflection.

Is there a reason an easier to use API wasn't implemented as a wrapper around the structs?  I implemented one myself after looking all over for an alternative and I'm hoping I didn't spend the last two days reinventing the wheel.

https://github.com/Byrne-Labs/Metadata-DOM
https://nuget.org/packages/ByrneLabs.Commons.MetadataDom

**Comment by svick** [comment]
Have you considered using [Cecil](https://github.com/jbevain/cecil)? It does not load assemblies into your AppDomain and I believe its API is easier to use than S.R.Metadata.

**Comment by tmat** [comment]
As you said the API provided by System.Reflection.Metadata is designed to be fast and consume as little memory as possible. We agree it would be nice to build an object model on top of this low-level APIs. We think it would be desirable for such API to have the shape of System.Reflection API (Assembly, Module, Type, TypeInfo, MethodInfo, etc.) for the reader part and System.Reflection.Emit API (AssemblyBuilder, ModuleBuilder, etc.) for the writer. We've had other priorities however, so it hasn't happened yet. 

In general, we believe there will be multiple models built on top of the low-level one, each tailored to the specific needs of the code that needs it.  For example, in Roslyn we expose metadata thru ISymbol interfaces. For code that currently works against System.Reflection object model it would be advantageous to keep working against the same API that just has a different implementation. You might need a different shape as well.

**Comment by tmat** [comment]
As @svick points out using Cecil is also an option.
