### ISSUE TITLE
microsoft.netcore.targets has incorrect RID for clrcompression AOT

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#14212]
In runtime.json for the latest microsoft.netcore.targets, we have:
```
    "win10-amd64-aot": {
      "runtime.native.System.IO.Compression": {
        "runtime.win10-x64-aot.runtime.native.System.IO.Compression": "4.1.1-beta-24418-00"
      }
    },
```

when we should have:
```
    "win10-x64-aot": {
      "runtime.native.System.IO.Compression": {
        "runtime.win10-x64-aot.runtime.native.System.IO.Compression": "4.1.1-beta-24418-00"
      }
    },
```

@ericstj @shrah

**Comment by ericstj** [comment]
Are you sure?  If I look at the runtime.json in https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.NETCore.Targets/1.2.0-beta-24721-02 it looks correct.

**Comment by ianhays** [comment]
Ah, yeah, I was getting version `4.3.0-beta-24429-02`. Version `1.2.0-beta-*` is correct.

@shrah what version of `Microsoft.Netcore.Targets` do you have?

**Comment by ericstj** [comment]
I'll delete those incorrectly versioned copies.

**Comment by ianhays** [comment]
Thanks Eric.  @shrah was getting an older version.

**Comment by ericstj** [comment]
They should all be gone now.
