### ISSUE TITLE
Add Xamarin support to System.ValueTuple package

### ISSUE THREAD

**Issue by marek-safar** [dotnet/corefx#14235]
It does not support Xamarin as of version 4.3.0.

We'd like to provide platform specific assemblies which forward types to existing types Xamarin products have in mscorlib (same scenario as in .NET vNext)

cc @weshaggard @akoeplinger

**Comment by weshaggard** [comment]
cc @jcouv @ericstj

**Comment by ericstj** [comment]
Makes sense.  To clarify: it **does** support Xamarin today in the same way that it supports desktop and .NETCore: it should use the netstandard1.0 assembly.  

In the future it sounds like you'd like to put those types inbox in mscorlib, similarly to how some future version of desktop will include them.  When you do that you will break folks using the existing SDKs and the latest package due to type conflicts, so we'll want to coordinate the change so that both of us can do it at the same time.  It's a shame Xamarin can't encode framework API in the TFM, otherwise we'd have a bit more flexibility here.

What's your timeline for putting them inbox?

**Comment by jcouv** [comment]
Marek already added code and test for mscorlib/xamarin (mono/mono@0a515cf)
Last I heard, it will be part of Xamarin Cycle10 release which is expected to be in line with VS Jan/Feb release.

Linking to https://github.com/dotnet/roslyn/issues/13177 (umbrella issue for adding ValueTuple).

**Comment by marek-safar** [comment]
As @jcouv wrote. It'll be included in the next release we call internally Cycle10 which does not have set date yet. We are previewing Cycle9 at the moment.

**Comment by AlexGhiondea** [comment]
It sounds like this will be in the next release of Xamarin.

**Comment by mellinoe** [comment]
It sounds like there is packaging work to do on our end, though, right?

**Comment by AlexGhiondea** [comment]
@mellinoe @ericstj @joperezr  are the placeholders that we have today enough?

**Comment by joperezr** [comment]
We are already calling out `$(AllXamarinFrameworks)` [here](https://github.com/dotnet/corefx/blob/master/src/System.ValueTuple/pkg/System.ValueTuple.pkgproj#L7) so I believe that should be enough on our side. @ericstj is that correct?

**Comment by ericstj** [comment]
No, we'll need to put placeholders in the package.  Currently it has none and expects the PCL to apply on all those frameworks.

@marek-safar can you confirm you will be shipping a System.ValueTuple.dll facade in Xamarin?  If so then we just need to add placeholders to ensure that the PCL doesn't apply.

**Comment by marek-safar** [comment]
@ericstj yes we are going to ship this Facade in upcoming releases.

**Comment by ericstj** [comment]
Ok, any other new file additions to your inbox set of assemblies with package overlap?  We can do one pass to update everything.

**Comment by marek-safar** [comment]
Not at the moment but I don't know if there are other .net vNext APIs currently distributed as nugets

**Comment by AlexGhiondea** [comment]
@joperezr @ericstj it sounds like we understand what needs to be done here. 

Do we want to have a single issue tracking multiple placeholder additions, or will this be a one-off change?

**Comment by ericstj** [comment]
Let's let this track just Value tuple.  @marek-safar we're in the middle of a big package refactoring that should be done by end of year.  At that point let's touch base again and review the final package set in NETCore vNext.

**Comment by marek-safar** [comment]
Any update on this? There is still no correct nuget available for Xamarin TFM.
Will the updated version also contain enhancements from CoreFX/CoreCLR ValueTuple ?

cc @mhutch

**Comment by jcouv** [comment]
@ericstj @AlexGhiondea Any update?

**Comment by ericstj** [comment]
Let's try to ship this change with release slated for https://github.com/dotnet/corefx/pull/16119.

**Comment by borgdylan** [comment]
Mono has this inbox leading to the inbox copy getting picked up when compiling. All build products end up broken on .Net desktop if using valuetuple.

**Comment by jcouv** [comment]
@ericstj I somehow lost track of this. Are we still going to release the mono inbox change from 1.1 branch? Or does this wait and get bundled with upcoming 2.0?

**Comment by weshaggard** [comment]
This will be part of the upcoming 1.1 servicing.

**Comment by trampster** [comment]
I just ran into this issue in Xamarin for android. If I add the System.ValueTuple nuget package, the add finishes without error but no project reference is added to System.ValueTuple but there is a entry in my packages.config. 

There is a folder in the nuget package called MonoAndroid10 with an empty file called _._ 

If I manually add a reference to the .net standard dll then it fails with errors saying I need System.ValueTuple

Whats the work around?

**Comment by ericstj** [comment]
The package is meant to provide **nothing** for Xamarin frameworks.  ValueTuple comes from the framework itself.  Make sure you're using the latest version of the Xamarin SDK.  /cc @marek-safar

**Comment by danmosemsft** [comment]
> This will be part of the upcoming 1.1 servicing.

@weshaggard is this change already in release/1.1.0? If not who would own creating a PR?

**Comment by weshaggard** [comment]
@danmosemsft this already shipped in the 4.3.1 version of the package and the 4.4.0 version as well.

**Comment by danmosemsft** [comment]
@weshaggard so if I undrestand right we don't know of anything more we need to do.

**Comment by weshaggard** [comment]
Correct. This work is done.

**Comment by Kryptos-FR** [comment]
I have an issue with a project library that is compiled to different platform depending on the configuration chosen.

On .Net app (e.g. Desktop), I added the NuGet package for ValueTuple and thus it also added a reference in the .csproj. It compiles fine. But when I switch to Android, then it fails to compile with
> The type 'ValueTuple<T1>' exists in both 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'

I can't remove the reference because then it will fail on other platforms.

Wasn't type forwarding supposed to take care of this scenario?

**Comment by weshaggard** [comment]
@marek-safar @akoeplinger might know more but assuming the TFM is MonoAndroid then there shouldn't be any types defined in System.ValueTuple because we expect it to come from the platform (at least in our latest packages 4.3.1 and 4.4.0.

**Comment by marek-safar** [comment]
@Kryptos-FR I don't know how you do "switch to Android" but nuget system does not allow you to do copy deployment across different platforms. You have to build on each platform to get right set of dependent libraries.

**Comment by ahsonkhan** [comment]
> Correct. This work is done.

Based on that, closing the issue. Please feel free to re-open if I am mistaken.
