### ISSUE TITLE
How can I use SignedXML

### ISSUE THREAD

**Issue by Jaedson33** [dotnet/corefx#14252]
I need to use that class to sign a xml, but I don't know how to do it.
Can you help me?

**Comment by krwq** [comment]
@Jaedson33 - I normally advice just taking a look at the tests but I can't seem to find any here. Second option is always to look at the documentation: https://msdn.microsoft.com/en-us/library/ms229745(v=vs.110).aspx

@bartonjs - Jeremy do you know where the tests for SignedXml class are?
This is giving no results: https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=SignedXml

**Comment by bartonjs** [comment]
SignedXml doesn't exist in .NET Core yet.  Issue #4278 tracks that work.

**Comment by night-king** [comment]
https://www.nuget.org/packages/System.Security.Cryptography.Xml/4.4.0-preview1-25305-02
