### ISSUE TITLE
Need to implement AppContext.BaseDirectory on .NET Core

### ISSUE THREAD

**Issue by FiveTimesTheFun** [dotnet/corefx#1427]
The AppContext.BaseDirectory property is documented on MSDN (https://msdn.microsoft.com/en-us/library/system.appcontext.basedirectory(v=vs.110).aspx)

"Gets the pathname of the base directory that the assembly resolver uses to probe for assemblies."

When running in an appcontainer, we use the WinRT API Package.InstalledLocation

https://msdn.microsoft.com/en-us/library/windows/apps/xaml/windows.applicationmodel.package.installedlocation.aspx?cs-save-lang=1&cs-lang=csharp

When running on the .NET Framework 4.6 we delegate to AppDomain.CurrentDomain.BaseDirectory, which delegates to its copy of AppDomainSetup which has a BaseDirectory property.

In CoreCLR, the host gives the "APP_PATHS" property when creating the initial appdomain:
https://github.com/dotnet/coreclr/blob/master/src/coreclr/hosts/corerun/corerun.cpp#L484
The host also specifies "APP_NI_PATHS", which is a list of paths of native images.

APP_PATHS is a list of paths.  I propose that in .NET Core, we return the first path given as APP_PATHS to coreclr.

**Comment by akoeplinger** [comment]
Is there a reason for closing this?
