### ISSUE TITLE
ISupportInitialize and IDesignerHost should be in System.ComponentModel.Primitives

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#14275]
/cc @ianhays @weshaggard @safern 

This is causing FileSystem.Watcher to bring in TypeConverter which is not a dependency we want to have.

**Comment by weshaggard** [comment]
Yes TypeConverter should be a leave node library and shouldn't have any incoming dependencies from other corefx libraries. If we find any others we need to break them as well.

**Comment by safern** [comment]
Ok, sounds good. I'll take this issue.

**Comment by safern** [comment]
IDesignerHost is bringing TypeConverter as well to FileSystem.Watcher so we should move that interface to S.CM.Primitives... will go ahead and open an issue on that

**Comment by weshaggard** [comment]
I would just go ahead and add it to this issue as well.
