### ISSUE TITLE
X509Certificate2.PrivateKey should not return ECDsa

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#14283]
In https://github.com/dotnet/corefx/issues/8491#issuecomment-261338229 I observed that our current (unreleased) plan to do RSA ?? DSA ?? ECDSA only works because we don't support other ECC algorithms.

An ECC cert is ambiguous for use, it can be any of (currently)
* ECDSA
* ECDH
* ECMQV

And probably (but not explicitly)
* ECIES
* EdDSA
* ECQV

If a user requests ECDSA we can give it to them (provided the algorithm and KU agree), but we can't know that ECDSA is "more right" than ECDH (which is not yet supported in corefx, but is in netfx (though not via a certificate)) for a certificate with no KeyUsage extension.  Or that ECDSA is "more right" than EdDSA (not currently supported at all).

Allowing ECDSA now creates a potential compat problem for the future, so we should be restricted to RSA and DSA for now (which is all netfx supports) and we can revisit this later with more thoughtfulness.

(Also applies to PublicKey.Key)

**Comment by bartonjs** [comment]
(One solution to this could be to create an "ECC" object which has ExportParameters and has some mechanism of being converted to other algorithm-based instantiations.

**Comment by karelz** [comment]
@AlexGhiondea the mirror in TFS has this bug opened ([299653](https://devdiv.visualstudio.com/DevDiv/_workitems?id=299653&triage=true&fullScreen=true&_a=edit)). Do you know why? There's no netfx-port-consider in this bug ... tooling hiccup?
