### ISSUE TITLE
create nupkg of ubuntu.16.04-xxx rid on ubuntu 14.04/x64 

### ISSUE THREAD

**Issue by chunseoklee** [dotnet/corefx#14298]
I am working on "Update CoreFX to generate nuget packages of CoreFX" on https://github.com/dotnet/core-setup/issues/725
With https://github.com/chunseoklee/corefx/commit/320ca7d42839a33350807ea0f18a401edcf794dc, `$ ./build-managed.sh -package` seems to produce proper nupkg of ubuntu.14.04-arm rid. However, I cannot figure out how to produce ubuntu.16.04-arm nupkg. 
Is there any way to create ubuntu.16.04-arm on ubuntu14.04/x64 host ?

p.s.  during packaging(`$ ./build-managed.sh -package`) the following error occurs. In this case, ubuntu14.04-arm nupkg is missing something ? 

52>/home/twoflower/dev/corefx/Tools/Packaging.targets(1096,5): error : PackageIndex from /home/twoflower/dev/corefx/pkg/Microsoft.Private.PackageBaseline/packageIndex.json is missing an entry for package runtime.ubuntu.14.04-arm.runtime.native.System.Security.Cryptography.  Please run /t:UpdatePackageIndex on this project to commit an update. [/home/twoflower/dev/corefx/src/Native/pkg/runtime.native.System.Security.Cryptography/ubuntu/14.04/runtime.native.System.Security.Cryptography.pkgproj]
    52>Done Building Project "/home/twoflower/dev/corefx/src/Native/pkg/runtime.native.System.Security.Cryptography/ubuntu/14.04/runtime.native.System.Security.Cryptography.pkgproj" (BuildAndTest target(s)) -- FAILED.

**Comment by chunseoklee** [comment]
cc @gkhanna79

**Comment by gkhanna79** [comment]
@chunseoklee How did you initialize the rootfs?

**Comment by chunseoklee** [comment]
For ubuntu-14.04-arm, I used `$ cross/build-rootfs.sh arm`.
I didn't try ubuntu-16.XX rootfs yet.

**Comment by gkhanna79** [comment]
You should try `build-rootfs.sh arm xenial` to build for 16.04.

**Comment by chunseoklee** [comment]
@gkhanna79 You mean that `./build-managed -packages` with xenial-based native arm binary(corefx/bin/Linux.arm.Debug) would create ubuntu.16.04-arm nupkg ? 
If it is true, build script extracts os-release info of rootfs during packaging ?

**Comment by gkhanna79** [comment]
> build script extracts os-release info of rootfs during packaging

Correct.
