### ISSUE TITLE
Microsoft.VisualBasic resource inclusion

### ISSUE THREAD

**Issue by bbowyersmyth** [dotnet/corefx#14299]
Just doing a `msbuild /t:clean;build` from the src\Microsoft.VisualBasic folder and the compile constant DEBUGRESOURCES doesn't get written to the bin\obj\AnyOS.AnyCPU.Debug\Microsoft.VisualBasic\defines.rsp file.

This shows as the bin\obj\AnyOS.AnyCPU.Debug\Microsoft.VisualBasic\SR.vb file being compiled without fallbacks in debug mode.

**Comment by danmosemsft** [comment]
Sounds like build issue

**Comment by karelz** [comment]
Then it's Infra (@danmosemsft only one area label please ;-))

**Comment by tarekgh** [comment]
just a comment for who is going to look at this issue:

looks we are passing the DEBUGRESOURCES defined constant as expected to 

```
DefineConstants = ,DEBUG,TRACE,LATEBINDING=True;DEBUGRESOURCES;SIGNED

```

but it looks when creating the defines.rsp used with vbc.exe, it doesn't use teh property DefineConstants and instead it used FinalDefineConstants

```
FinalDefineConstants = CONFIG="Debug",_MyType="Empty",PLATFORM="AnyCPU",,DEBUG,TRACE,LATEBINDING=True
```

the fix could be next to the line 
```
    <DefineConstants Condition="'$(ConfigurationGroup)' == 'Debug'">$(DefineConstants);DEBUGRESOURCES</DefineConstants>

```

add another line:

```
    <FinalDefineConstants Condition="'$(ConfigurationGroup)' == 'Debug'">$(FinalDefineConstants),DEBUGRESOURCES</FinalDefineConstants>

```

**Comment by bbowyersmyth** [comment]
@tarekgh Also I think DEBUGRESOURCES and SIGNED need to be comma delimited for VB. Not sure if that plays into this at all.

**Comment by tarekgh** [comment]
@bbowyersmyth that is a good point. looks this is working with C# but not VB. do you want give it a try? I mean in your local corefx\Tools\resources.targets fix the semicolon to comma and try to build again Microsoft.VisualBasic. if this fix it, you can submit PR in buildtools repo. Thanks.

**Comment by karelz** [comment]
BTW: If we confirm it is in buildtools, we should move it there (unless we do the fix right away).

**Comment by tarekgh** [comment]
Issue moved to [dotnet/buildtools #1256](https://github.com/dotnet/buildtools/issues/1256) via [**ZenHub**](https://www.zenhub.com/)

**Comment by tarekgh** [comment]
Yes I moved it to buildtools repo
