### ISSUE TITLE
Question: Microsoft.VisualBasic functions port

### ISSUE THREAD

**Issue by bbowyersmyth** [dotnet/corefx#14300]
I have some ex-VB assemblies that still call into some of the old legacy VB helper functions. Do you mind if I port some of that surface area to core?

Specifically:
Strings.Right
Strings.Left
Strings.Mid
Strings.Replace
DateAndTime.DateDiff
Information.IsDate
Information.IsNumeric

**Comment by stephentoub** [comment]
@weshaggard, @danmosemsft, was there any discussion about including Microsoft.VisualBasic in netstandard?  Regardless, any reason we wouldn't want the full set of APIs from it available in core?

**Comment by weshaggard** [comment]
There was a discussion about it being part of netstandard and we decided to keep it on top of netstandard for now. However that doesn't mean we shouldn't include more APIs in core for it. We have to be a little careful as there are a lot of the "My" APIs in VB that require dependencies that aren't in core, but if the dependencies are present then I don't know of any reason we shouldn't include them.

**Comment by bbowyersmyth** [comment]
Agreed, it should not be part of netstandard.

I realise that this is not going to be a priority for many people so I'm happy to do the port. The reference source is not available so I would need to be sent that. Alternatively, with your approval, I can work from the MSIL. Either way is fine by me.

We can start with the top level namespace and go from there if there's any interest.

**Comment by danmosemsft** [comment]
@VSadov, @OmarTawfik you own this namespace. What are your thoughts about porting these?

**Comment by iainnicol** [comment]
I would volunteer to assist @bbowyersmyth in porting some of the Microsoft.VisualBasic assembly, to work on top of netstandard.

However, I would prefer to work from MIT Reference Source (à la #8808) and not MSIL.

Politely pinging @VSadov, @OmarTawfik.

**Comment by AdamSpeight2008** [comment]
Personally I would want use to port over the legacy functionality to .net core. Let .net core be a "pure" .net implementation.

**Comment by bbowyersmyth** [comment]
@AnthonyDGreen I'm dependent on them now purely because they were already being used. I can certainly move them over to be using BCL functions. It just requires some effort as they are not one-for-one replacements. For example `Left` can take a length longer than the string and it will just return the string instead of giving an error like `Substring` will.
I'm ok if the call is to leave them in the past.

**Comment by danmosemsft** [comment]
This is tracked in https://github.com/dotnet/corefx/issues/31181

**Comment by bimonsubio1984** [comment]
Hello,

You can find a ported version here:
https://ufile.io/nyzye

Some Windows specific stuff is missing.

**Comment by bimonsubio1984** [comment]
https://github.com/bimonsubio1984/CommonCore/tree/master/Ported.VisualBasic
