### ISSUE TITLE
error CS1061: 'Type' does not contain a definition for 'Assembly' and no extension method 'Assembly' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?) 

### ISSUE THREAD

**Issue by Umplify** [dotnet/corefx#14305]
When adding a 'Resource' to an .NET Standard 1.6 Assembly in Visual Studio 2017 RC, the compiler throws an error message per the subject line. The issue is within the C# code behind generated automatically after adding the resource file.

**Comment by danmosemsft** [comment]
@karelz this is tooling, not sure where it should go

**Comment by karelz** [comment]
It looks like a problem in VS 2017 RC template - not even related to .NET Core.
@Umplify can you please file it via VS feedback (Report a problem in the right top corner)? That way it will get to the right folks right away.
