### ISSUE TITLE
Is OpenAsync really synchronous in DbConnection?

### ISSUE THREAD

**Issue by txdv** [dotnet/corefx#14307]
I was looking at the [DbConnection OpenAsync](https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/src/System/Data/Common/DbConnection.cs#L122) code and realized that it is just wrapper around a blocking call which returns a finished task and is therefor not really useful in async code, because calling the task alone without awaiting already blocks it.

Is there a reason why this it is not a Task.Run(() => Open()), which would make it a bit more useful?

**Comment by JonHanna** [comment]
Then it would be an asynchronous wrapper around something that is really synchronous, which isn't much more useful (and indeed quite wasteful).

**Comment by benaadams** [comment]
Its a virtual method that is then hopefully overridden by implementer (for example in [SQLClient OpenAsync](https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlConnection.cs#L808-L817)); but provides an initial implementation for clients that only have Open defined (for example historic ones that were written pre-async)

**Comment by txdv** [comment]
@benaadams So I guess this is on the provider to be implemented?

I feel that a simple Task.Run(() => SyncVersion()) would already be better, but I guess I will just implemented one myself. The problem I see with this that I will basically implemented the same thing over multiple files. 

I guess this is a non issue then and works as intended.
