### ISSUE TITLE
LowLevelConcurrentQueue not used?

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#14310]
The internal LowLevelConcurrentQueue in 

[corefx/src/System.Threading/src/System/Collections/Concurrent/LowLevelConcurrentQueue.cs](https://github.com/dotnet/corefx/blob/master/src/System.Threading/src/System/Collections/Concurrent/LowLevelConcurrentQueue.cs)

Doesn't appear to be used anywhere; should it be removed?

/cc @stephentoub

**Comment by stephentoub** [comment]
If it's no longer used anywhere (i.e. if you can delete the file and everything in the repo still compiles successfully), we should definitely delete it.
