### ISSUE TITLE
System.Threading.Tasks.Dataflow.ConcurrentQueue

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#14311]
System.Threading.Tasks.Dataflow [references System.Collections.Concurrent in NetStandard 1.1](https://github.com/dotnet/corefx/blob/master/src/System.Threading.Tasks.Dataflow/src/project.json#L20-L37)

Should the [Dataflow.ConcurrentQueue](https://github.com/dotnet/corefx/blob/master/src/System.Threading.Tasks.Dataflow/src/Internal/ConcurrentQueue.cs) be put behind a `#if !netstandard11` so it only exists in NetStandard 1.0 and uses System.Collections.Concurrent's implementation otherwise?

/cc @stephentoub

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/blob/master/src/System.Threading.Tasks.Dataflow/src/System.Threading.Tasks.Dataflow.csproj#L52-L55
