### ISSUE TITLE
TimeZoneInfo.AdjustmentRule should override Equals

### ISSUE THREAD

**Issue by justinvp** [dotnet/corefx#14313]
`TimeZoneInfo.AdjustmentRule` [implements `IEquatable<T>`](https://github.com/dotnet/coreclr/blob/c28e5e8ff02744dc1e1cc1fa9b2563d24e643f9b/src/mscorlib/src/System/TimeZoneInfo.cs#L4573) and [overrides `GetHashCode`](https://github.com/dotnet/coreclr/blob/c28e5e8ff02744dc1e1cc1fa9b2563d24e643f9b/src/mscorlib/src/System/TimeZoneInfo.cs#L4587) but doesn't override `Equals(object)`.

**Comment by tarekgh** [comment]
@justinvp we have many cases in other classes doing the same. Equals always treated as ObjectReference equality. I am not sure if this is worth to change now as this can have inconsistency with the desktop and app compat risk.

**Comment by justinvp** [comment]
@tarekgh, I'm guessing the lack of `Equals(object)` was a mistake, but I agree, it's probably not worth the compat risk to change now. Closing.
