### ISSUE TITLE
HttpClient/CurlHandler CPU goes up after exception and does not come back

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#14319]
@rvfernandes commented on [Tue Dec 06 2016](https://github.com/dotnet/coreclr/issues/8478)

I made a small router in .Net Core and noticed that some machines from one hour to the other had a cpu jump. When this happens the CPU stays high, although the application responds without problems. I have noticed that this happens when I have a large number of exceptions of type (System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: The read operation failed, see inner exception. ---> System.Net.Http.CurlException: Transferred a partial file).

My system runs on .Net Core with docker.

**Comment by danmosemsft** [comment]
@davidsh @CIPop

**Comment by davidsh** [comment]
cc: @stephentoub This is happening on Linux

**Comment by stephentoub** [comment]
@rvfernandes, is it possible for you to share a repro?

**Comment by stephentoub** [comment]
>  I have noticed that this happens when I have a large number of exceptions

@rvfernandes, can you clarify this comment as well?  Do you mean that you legitimately get a bunch of exceptions and that then seems to cause the CPU spike, or do you mean that as a result of the CPU spike you start seeing lots of exceptions?

**Comment by rvfernandes** [comment]
@stephentoub   CPU spikes after the exceptions and stays above normal until the server is reset.

**Comment by stephentoub** [comment]
@rvfernandes, are you still hitting this issue?  Can you provide more details (e.g. OS, .NET Core version, etc.)?  I'm unable to repro the problem you're seeing.  I wrote a little app to attempt to:
```C#
using System;
using System.Net;
using System.Net.Http;
using System.Net.Sockets;
using System.Text;
using System.Threading.Tasks;

class Program
{
    static void Main() => MainAsync().GetAwaiter().GetResult();
    static async Task MainAsync()
    {
        using (var client = new HttpClient())
        using (var listener = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
        {
            listener.Bind(new IPEndPoint(IPAddress.Loopback, 0));
            listener.Listen(1);
            int port = ((IPEndPoint)listener.LocalEndPoint).Port;

            for (int i = 0; i < 1000; i++)
            {
                Task<string> s = client.GetStringAsync("http://127.0.0.1:" + port);
                using (Socket server = await listener.AcceptAsync())
                {
                    byte[] data = Encoding.UTF8.GetBytes(
                        "HTTP/1.1 200 OK\r\n" +
                        "Content-Length: 138\r\n" +
                        "\r\n" +
                        "Not enough data");
                    await server.SendAsync(new ArraySegment<byte>(data), SocketFlags.None);
                    server.Shutdown(SocketShutdown.Send);
                }

                try { await s; } catch (Exception e) { Console.WriteLine(e); }
            }

            Console.WriteLine("....waiting....");
            Console.ReadLine();
        }
    }
}
```
and CPU goes up while requests are failing, but then goes back down to idle once the requests have completed.  Do you see otherwise?

If you're able to reproduce, are you able to attach a debugger while it's stuck in its CPU 100% state to see where it is?  Are you able to take a profiling trace to see where it's spending its time?

**Comment by stephentoub** [comment]
@rvfernandes, I've not been able to reproduce this, and I haven't heard back from you about it.  I'm going to close the issue for now.  We can reopen if/when necessary. Thanks.
