### ISSUE TITLE
Array.IsReadOnly should return true for empty arrays

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#14324]
@DerpMcDerp commented on [Wed Aug 10 2016](https://github.com/dotnet/coreclr/issues/6692)

i.e. Array.cs should have this:

``` C#
    // Is this Array read-only?
    public bool IsReadOnly
    { get { return this.Length == 0; } }
```

instead of this:

``` C#
    // Is this Array read-only?
    public bool IsReadOnly
    { get { return false; } }
```

Note: the above change breaks code which does something like:

``` C#
    Contract.Requires(!list.IsReadOnly, "list should be writable")

    for (int i = 0; i < list.Count; ++i) {
        list[i] = whatever;
    }
```

Which was an incorrectly specified invariant anyway.

---

@hughbe commented on [Thu Aug 11 2016](https://github.com/dotnet/coreclr/issues/6692#issuecomment-239111140)

I hate to be a killjoy @DerpMcDerp, but this probably has too many breaking change implications. I assume that a new implementation would consider this, but the baggage of the past has to be taken into account

---

@denis-dbm commented on [Thu Aug 11 2016](https://github.com/dotnet/coreclr/issues/6692#issuecomment-239152465)

IsReadOnly is just inherited from IList interface, isn't? There is real use of this property for array type?

I think the property should return false always.

---

@ghost commented on [Thu Aug 11 2016](https://github.com/dotnet/coreclr/issues/6692#issuecomment-239187291)

BTW, how does `this.Length == 0;` convey the message that collection is read-only? It should explicitly be either true (for `ReadOnlyCollection` types) or false (for non-`ReadOnlyCollection` types) because that would assert an artificial limitation on Add/Remove/Indexer methods. Or am I missing something?

Probably having `IsFixedSize` in addition to `IsReadOnly` would somehow mitigate the confusions around the area as @jskeet pointed out: http://stackoverflow.com/a/26475514

---

@danmosemsft commented on [Thu Dec 08 2016](https://github.com/dotnet/coreclr/issues/6692#issuecomment-265819168)

Per [issues guidance](https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/IssuesFeedbackEngagement.md) 
> If in the managed code log it in the CoreFX repo even if the code is in this CoreCLR repo (ie., in mscorlib/System.Private.Corelib). The reason for this is we sometimes move managed types between the two and it makes sense to keep all the issues together.

**Comment by AlexGhiondea** [comment]
I am not sure if this is a break that we would like to take.

I am going to close this issue but please feel free to re-open if you have more data around the impact this would have on existing code.
