### ISSUE TITLE
Reduce allocations in String.Split

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#14323]
@jamesqo commented on [Mon Nov 07 2016](https://github.com/dotnet/coreclr/issues/8034)

Now that `ArrayPool` is in the coreclr repo, it may be worth trying to use `stackalloc` for the int table required by `Split` if the length of the string is small enough, otherwise using `ArrayPool<int>` to rent the tables.

I have been building [a prototype](https://github.com/dotnet/coreclr/compare/master...jamesqo:better-split?expand=1) to implement this over the last day or so; however, it's turning out much more complex than I expected. I can't even run the corefx tests since the xUnit runner chokes before it gets to them (probably due to something wrong in my changes) ☹️ Once I finish, however, I'll open a PR for this. In the meantime, I'm opening this issue to track this in case I can't finish.

---

@Maoni0 commented on [Tue Nov 08 2016](https://github.com/dotnet/coreclr/issues/8034#issuecomment-259256797)

@swgillespie could you please take a look at the prototype @jamesqo did?

---

@swgillespie commented on [Wed Nov 16 2016](https://github.com/dotnet/coreclr/issues/8034#issuecomment-261109666)

From an allocation perspective this all looks reasonable and good to me. I'm wondering if we can use a Span instead of char\* and length pair for the separator array, though? I see that it's used in MakeSeparatorList but I don't think I see any uses in there that prevent a Span from being used in its place, which would prevent a pin.

---

@jamesqo commented on [Wed Nov 16 2016](https://github.com/dotnet/coreclr/issues/8034#issuecomment-261130838)

@swgillespie Good point, I didn't think of using `Span` for this. I'll update the code to use it before submitting a PR. Thanks!

---

**Comment by fujiy** [comment]
@jamesqo are you working on it?

**Comment by jamesqo** [comment]
@fujiy, No.

**Comment by stephentoub** [comment]
This is likely worth doing in some fashion, but there are some known perf issues getting in the way currently (e.g. zero-initialization costs of the stackalloc'd memory).  Here's a simple example of what this could look like, using stackalloc for sufficiently small strings:
https://github.com/stephentoub/coreclr/commit/500978f61c236d840f68281ef290c389dd3f0d27

**Comment by danmosemsft** [comment]
@fujiy any interest in taking a look?

**Comment by fujiy** [comment]
Hi @danmosemsft, I won't be able to do it for the foreseeable future

**Comment by danmosemsft** [comment]
This seems a dupe of https://github.com/dotnet/coreclr/pull/15435 https://github.com/dotnet/coreclr/issues/6136
