### ISSUE TITLE
Code Guidelines Question: Is removing a transparent override a breaking change.

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#14327]
Given:

    public SomeType override SomeMethod() => base.SomeMethod();

Is it considered too breaking to remove this, and let calling code access the base directly, due to there being changes observable through reflection, or is such a removal okay?

Or coming at it another way. If it had been:

    public SomeType override SomeMethod() => DoSomethingInadvisable();

And changing to not have the override fixed the problem, would that removal be fine, or would it have to remain and call the base?

**Comment by danmosemsft** [comment]
We consider adding/removing overrides to be non-breaking

https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md#members

**Comment by JonHanna** [comment]
Why is it I can read a document five times, and each time miss the bit I'm looking for? 

Thanks.
