### ISSUE TITLE
netTcp WCF clients fail with update to 1.1

### ISSUE THREAD

**Issue by MikeInBA** [dotnet/corefx#14329]
I have an asp.net core controller that has a repo that uses a netTcp WCF client to call in to a WCF service.  I used SecurityMode.Transport and TcpClientCredentialType.Certificate.  For the client (that is hosted by the asp.net core controller), I read the certificate thumbprint out of my appsettings.json.

This setup worked fine when my Microsoft.NETCore.App version was 1.0.1, but as soon as I change my dependency in project.json to 1.1 all my WCF calls fail with:

> An unhandled exception of type 'System.ExecutionEngineException' occurred in System.Private.CoreLib.ni.dll

this only happens when the credential type is set to Certificate.  Windows and None security modes work without issue.

**Comment by karelz** [comment]
Do you have a small repro (ideally without ASP.NET and WCF, just CoreFX libraries ...).

**Comment by tarekgh** [comment]
@MikeInBA would be nice to attach a repro as @karelz mentioned in addition to the stack trace if possible. thank you.

**Comment by MikeInBA** [comment]
Here is a zip with a vs 2015 sln:  https://1drv.ms/u/s!ArX3JWLeEgybh6U-naphYg21dQ8k7Q

There is no stack trace after I click "Ok" on this screen: https://1drv.ms/i/s!ArX3JWLeEgybh6U_6J3VEGqYoulrBg

the Call Stack window just shows [External Code]

**Comment by MikeInBA** [comment]
@karelz have you seen this before?  Is there a change I am missing?

**Comment by karelz** [comment]
Post a stack trace as txt, not as picture (that's not helpful)
Try to avoid [External Code](http://stackoverflow.com/questions/654696/how-to-debug-external-class-library-projects-in-visual-studio).

**Comment by MikeInBA** [comment]
@karelz 
`System.Private.CoreLib.ni.dll!System.RuntimeType.CreateInstanceSlow(bool publicOnly, bool skipCheckThis, bool fillCache, ref System.Threading.StackCrawlMark stackMark)	
 	System.Private.CoreLib.ni.dll!System.Activator.CreateInstance<Internal.Cryptography.Pal.Native.SafeLocalAllocHandle>()	
 	System.Security.Cryptography.X509Certificates.dll!Internal.Cryptography.Pal.Native.SafePointerHandle<Internal.Cryptography.Pal.Native.SafeLocalAllocHandle>.get_InvalidHandle.AnonymousMethod__4_0()	
 	System.Security.Cryptography.X509Certificates.dll!Microsoft.Win32.SafeHandles.SafeHandleCache<Internal.Cryptography.Pal.Native.SafeLocalAllocHandle>.GetInvalidHandle(System.Func<Internal.Cryptography.Pal.Native.SafeLocalAllocHandle> invalidHandleFactory)	
 	System.Security.Cryptography.X509Certificates.dll!Internal.Cryptography.Pal.Native.SafePointerHandle<Internal.Cryptography.Pal.Native.SafeLocalAllocHandle>.InvalidHandle.get()	
 	System.Security.Cryptography.X509Certificates.dll!Internal.Cryptography.Pal.Native.Helpers.ToLpstrArray(System.Security.Cryptography.OidCollection oids, out int numOids)	
 	System.Security.Cryptography.X509Certificates.dll!Internal.Cryptography.Pal.ChainPal.BuildChain(bool useMachineContext, Internal.Cryptography.ICertificatePal cert, System.Security.Cryptography.X509Certificates.X509Certificate2Collection extraStore, System.Security.Cryptography.OidCollection applicationPolicy, System.Security.Cryptography.OidCollection certificatePolicy, System.Security.Cryptography.X509Certificates.X509RevocationMode revocationMode, System.Security.Cryptography.X509Certificates.X509RevocationFlag revocationFlag, System.DateTime verificationTime, System.TimeSpan timeout)	
 	System.Security.Cryptography.X509Certificates.dll!System.Security.Cryptography.X509Certificates.X509Chain.Build(System.Security.Cryptography.X509Certificates.X509Certificate2 certificate)	
 	System.Net.Security.dll!System.Net.CertificateValidationPal.VerifyCertificateProperties(System.Security.Cryptography.X509Certificates.X509Chain chain, System.Security.Cryptography.X509Certificates.X509Certificate2 remoteCertificate, bool checkCertName, bool isServer, string hostName)	
 	System.Net.Security.dll!System.Net.Security.SecureChannel.VerifyRemoteCertificate(System.Net.Security.RemoteCertValidationCallback remoteCertValidationCallback)	
 	System.Net.Security.dll!System.Net.Security.SslState.CompleteHandshake()	
 	System.Net.Security.dll!System.Net.Security.SslState.CheckCompletionBeforeNextReceive(System.Net.Security.ProtocolToken message, System.Net.AsyncProtocolRequest asyncRequest)	
 	System.Net.Security.dll!System.Net.Security.SslState.StartSendBlob(byte[] incoming, int count, System.Net.AsyncProtocolRequest asyncRequest)	
 	System.Net.Security.dll!System.Net.Security.SslState.ProcessReceivedBlob(byte[] buffer, int count, System.Net.AsyncProtocolRequest asyncRequest)	
 	System.Net.Security.dll!System.Net.Security.SslState.ReadFrameCallback(System.Net.AsyncProtocolRequest asyncRequest)	
 	System.Net.Security.dll!System.Net.AsyncProtocolRequest.CompleteRequest(int result)	
 	System.Net.Security.dll!System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(int bytes)	
 	System.Net.Security.dll!System.Net.FixedSizeReader.ReadCallback(System.IAsyncResult transportResult)	
 	System.Net.Security.dll!System.Threading.Tasks.TaskToApm.InvokeCallbackWhenTaskCompletes.AnonymousMethod__0()	
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()	
 	System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	
 	System.Private.CoreLib.ni.dll!System.Threading.Tasks.AwaitTaskContinuation.RunCallback(System.Threading.ContextCallback callback, object state, ref System.Threading.Tasks.Task currentTask)	
 	System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.FinishContinuations()	
 	System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task<int>.TrySetResult(int result)	
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<int>.SetResult(int result)	
 	System.Private.ServiceModel.dll!System.ServiceModel.Channels.ConnectionStream.ReadAsync(byte[] buffer, int offset, int count, System.Threading.CancellationToken cancellationToken)	
 	System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.RunWithDefaultContext()	
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0()	
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()	
 	System.Private.CoreLib.ni.dll!System.Threading.Tasks.AwaitTaskContinuation.ExecuteWorkItemHelper()	
 	System.Private.CoreLib.ni.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	`

**Comment by tarekgh** [comment]
CC @bartonjs

**Comment by tarekgh** [comment]
```
System.Private.CoreLib.ni.dll!System.RuntimeType.CreateInstanceSlow(bool publicOnly, bool skipCheckThis, bool fillCache, ref System.Threading.StackCrawlMark stackMark)	
 	System.Private.CoreLib.ni.dll!System.Activator.CreateInstance<Internal.Cryptography.Pal.Native.SafeLocalAllocHandle>()	
 	System.Security.Cryptography.X509Certificates.dll!Internal.Cryptography.Pal.Native.SafePointerHandle<Internal.Cryptography.Pal.Native.SafeLocalAllocHandle>.get_InvalidHandle.AnonymousMethod__4_0()	
 	System.Security.Cryptography.X509Certificates.dll!Microsoft.Win32.SafeHandles.SafeHandleCache<Internal.Cryptography.Pal.Native.SafeLocalAllocHandle>.GetInvalidHandle(System.Func<Internal.Cryptography.Pal.Native.SafeLocalAllocHandle> invalidHandleFactory)	
 	System.Security.Cryptography.X509Certificates.dll!Internal.Cryptography.Pal.Native.SafePointerHandle<Internal.Cryptography.Pal.Native.SafeLocalAllocHandle>.InvalidHandle.get()	
 	System.Security.Cryptography.X509Certificates.dll!Internal.Cryptography.Pal.Native.Helpers.ToLpstrArray(System.Security.Cryptography.OidCollection oids, out int numOids)	
 	System.Security.Cryptography.X509Certificates.dll!Internal.Cryptography.Pal.ChainPal.BuildChain(bool useMachineContext, Internal.Cryptography.ICertificatePal cert, System.Security.Cryptography.X509Certificates.X509Certificate2Collection extraStore, System.Security.Cryptography.OidCollection applicationPolicy, System.Security.Cryptography.OidCollection certificatePolicy, System.Security.Cryptography.X509Certificates.X509RevocationMode revocationMode, System.Security.Cryptography.X509Certificates.X509RevocationFlag revocationFlag, System.DateTime verificationTime, System.TimeSpan timeout)	
 	System.Security.Cryptography.X509Certificates.dll!System.Security.Cryptography.X509Certificates.X509Chain.Build(System.Security.Cryptography.X509Certificates.X509Certificate2 certificate)	
 	System.Net.Security.dll!System.Net.CertificateValidationPal.VerifyCertificateProperties(System.Security.Cryptography.X509Certificates.X509Chain chain, System.Security.Cryptography.X509Certificates.X509Certificate2 remoteCertificate, bool checkCertName, bool isServer, string hostName)	
 	System.Net.Security.dll!System.Net.Security.SecureChannel.VerifyRemoteCertificate(System.Net.Security.RemoteCertValidationCallback remoteCertValidationCallback)	
 	System.Net.Security.dll!System.Net.Security.SslState.CompleteHandshake()	
 	System.Net.Security.dll!System.Net.Security.SslState.CheckCompletionBeforeNextReceive(System.Net.Security.ProtocolToken message, System.Net.AsyncProtocolRequest asyncRequest)	
 	System.Net.Security.dll!System.Net.Security.SslState.StartSendBlob(byte[] incoming, int count, System.Net.AsyncProtocolRequest asyncRequest)	
 	System.Net.Security.dll!System.Net.Security.SslState.ProcessReceivedBlob(byte[] buffer, int count, System.Net.AsyncProtocolRequest asyncRequest)	
 	System.Net.Security.dll!System.Net.Security.SslState.ReadFrameCallback(System.Net.AsyncProtocolRequest asyncRequest)	
 	System.Net.Security.dll!System.Net.AsyncProtocolRequest.CompleteRequest(int result)	
 	System.Net.Security.dll!System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(int bytes)	
 	System.Net.Security.dll!System.Net.FixedSizeReader.ReadCallback(System.IAsyncResult transportResult)	
 	System.Net.Security.dll!System.Threading.Tasks.TaskToApm.InvokeCallbackWhenTaskCompletes.AnonymousMethod__0()	
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()	
 	System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	
 	System.Private.CoreLib.ni.dll!System.Threading.Tasks.AwaitTaskContinuation.RunCallback(System.Threading.ContextCallback callback, object state, ref System.Threading.Tasks.Task currentTask)	
 	System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.FinishContinuations()	
 	System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task<int>.TrySetResult(int result)	
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<int>.SetResult(int result)	
 	System.Private.ServiceModel.dll!System.ServiceModel.Channels.ConnectionStream.ReadAsync(byte[] buffer, int offset, int count, System.Threading.CancellationToken cancellationToken)	
 	System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.RunWithDefaultContext()	
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0()	
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()	
 	System.Private.CoreLib.ni.dll!System.Threading.Tasks.AwaitTaskContinuation.ExecuteWorkItemHelper()	
 	System.Private.CoreLib.ni.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	

```

**Comment by bartonjs** [comment]
This is https://github.com/dotnet/coreclr/issues/8148.  https://github.com/dotnet/corefx/issues/13814#issuecomment-261644867 mentions a diagnostic confirmation step (which happens to be a temporary workaround).

**Comment by karelz** [comment]
FYI: Also documented as known 1.1 issue here: https://github.com/dotnet/core/blob/master/release-notes/1.1/1.1-known-issues.md#systemexecutionengineexception-in-systemsecuritycryptographyx509cerificatesdll-on-windows
