### ISSUE TITLE
SemaphoreSlim can throw an ArgumentNullException during a cancel

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#14320]
@rchiodo commented on [Thu Nov 17 2016](https://github.com/dotnet/coreclr/issues/8177)

I'm using a BlockingCollection<ConcurrentQueue> and a call to TryTake(out value, timeout, cancelToken) will crash with an ArgumentNullException during a cancel. 

It looks to me like SemaphoreSlim is not handling cancel after it's been disposed.

The callstack of the crash is like so:

  at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at System.Threading.SemaphoreSlim.CancellationTokenCanceledEventHandler(Object obj)

---

@rchiodo commented on [Thu Nov 17 2016](https://github.com/dotnet/coreclr/issues/8177#issuecomment-261329150)

In the debugger, the m_lockObj is null:

 private static void CancellationTokenCanceledEventHandler(object obj)
        {
            SemaphoreSlim semaphore = obj as SemaphoreSlim;
            Contract.Assert(semaphore != null, "Expected a SemaphoreSlim");
            lock (semaphore.m_lockObj)
            {
                Monitor.PulseAll(semaphore.m_lockObj); //wake up all waiters.
            }
        }

---

@stephentoub commented on [Thu Nov 17 2016](https://github.com/dotnet/coreclr/issues/8177#issuecomment-261330272)

@rchiodo, it sounds like something in your code disposed the BlockingCollection while it was still being used?

---

@rchiodo commented on [Thu Nov 17 2016](https://github.com/dotnet/coreclr/issues/8177#issuecomment-261331678)

Yes. It looks like the canceltoken has a registered callback that disposes the BlockingCollection. 

Shouldn't the semaphoreslim be throwing an ObjectDisposedException in this case?

---

@danmosemsft commented on [Thu Dec 08 2016](https://github.com/dotnet/coreclr/issues/8177#issuecomment-265812623)

Per [issues guidance](https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/IssuesFeedbackEngagement.md) 
> If in the managed code log it in the CoreFX repo even if the code is in this CoreCLR repo (ie., in mscorlib/System.Private.Corelib). The reason for this is we sometimes move managed types between the two and it makes sense to keep all the issues together.

**Comment by stephentoub** [comment]
> Shouldn't the semaphoreslim be throwing an ObjectDisposedException in this case?

A call to CheckDisposed could potentially be added to the beginning of CancellationTokenCanceledEventHandler, but even with that it's not a guarantee that an ODE will be thrown: race conditions abound.  These checks and throwing ObjectDisposedException aren't really meant to catch all improper use after dispose, just to highlight the common cases.  To get the stack you're getting, the SemaphoreSlim is being Dispose'd while a Wait is in progress, which isn't suppored (these objects, including BlockingCollection, should only be disposed of when they're no longer being used), and we can't add enough checks everywhere to turn all of these misuses into ODEs.

**Comment by rchiodo** [comment]
Sounds fine to me.
