### ISSUE TITLE
Optimization: UTF8Encoding methods can probably be made faster/refactored

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#14325]
@jamesqo commented on [Tue Aug 16 2016](https://github.com/dotnet/coreclr/issues/6759)

Currently the UTF8Encoding methods are kind of a mess, and they read [ints at a time](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Text/UTF8Encoding.cs#L457-L458) rather than longs, so they're not taking full advantage of 64-bit platforms. Additionally strings have an `IsAscii()` flag [cached in the syncblk](https://github.com/dotnet/coreclr/blob/master/src/classlibnative/bcltype/stringnative.cpp#L234) that we may be able to make use of, since that will essentially let us skip any checks for non-ASCII data during the loop and make `GetByteCount` O(1).

Other ideas for optimization:
- Haven't proven it but I'm 99% sure that [Encoding.UTF8](https://github.com/dotnet/coreclr/blob/57b3450f4d232cd53d3b9a0f6566806d73fa4156/src/mscorlib/src/System/Text/Encoding.cs#L1519-L1524) will not be inlined, it does 3 volatile accesses and initialization? (the constructor is more likely to be inlined) This is going to harm the typical use case for people who don't cache the result, like this:

``` cs
var bytes = Encoding.UTF8.GetBytes(str);
bytes[0] = 0xff;
str = Encoding.UTF8.GetString(bytes); // second method call to get_UTF8
```

We should attempt to instead do something similar to [ArrayPool.Shared](https://github.com/dotnet/corefx/blob/master/src/System.Buffers/src/System/Buffers/ArrayPool.cs#L39-L43) where the one-time init logic is separated out into a new method.
- Right now the virtual methods exposed in the API call another virtual method to do the heavy lifting. Maybe it would be worth duplicating some of the logic to avoid double virtual dispatch?
- [Loop code size](https://github.com/dotnet/coreclr/blob/57b3450f4d232cd53d3b9a0f6566806d73fa4156/src/mscorlib/src/System/Text/UTF8Encoding.cs#L456-L497) is kinda big, which can be bad for the loop buffer. The logic to handle non-ASCII chars should be moved to outside the loop.

---

@jkotas commented on [Tue Aug 16 2016](https://github.com/dotnet/coreclr/issues/6759#issuecomment-240155067)

> that Encoding.UTF8 will not be inlined

Agree. It would be nice to move the encoding singletons to the encoding classes where they belong, and initialize them in the static constructor of their respective class. This way the lazy initialization can be done using the more efficient static constructor trigger.

> Right now the virtual methods exposed

The options on what you can do about this are limited because of the encoding methods are not sealed.

> logic to handle non-ASCII chars should be moved to outside the loop

These kind of basic block movements are best left to profile guided optimizations - we do not have them hooked up to .NET Core yet, They are hooked up to full framework. You can read more about them here: https://msdn.microsoft.com/en-us/library/hh873180(v=vs.110).aspx

---

@jkotas commented on [Tue Aug 16 2016](https://github.com/dotnet/coreclr/issues/6759#issuecomment-240155533)

cc @KrzysztofCwalina Krzysztof has been looking into the performance issues around encoding as well.

---

@redknightlois commented on [Thu Aug 18 2016](https://github.com/dotnet/coreclr/issues/6759#issuecomment-240736472)

@jkotas A bit off-topic. Is the profile guided optimization going to be supported at the JIT level (without having to generate a native file)?

---

@jkotas commented on [Thu Aug 18 2016](https://github.com/dotnet/coreclr/issues/6759#issuecomment-240809700)

@redknightlois It may be worth an up-for-grabs issue. I do not think anybody is looking into it right now, but it should not be too hard for somebody to make it happen - all crucial parts are there today.

---

@danmosemsft commented on [Thu Dec 08 2016](https://github.com/dotnet/coreclr/issues/6759#issuecomment-265819239)

Per [issues guidance](https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/IssuesFeedbackEngagement.md) 
> If in the managed code log it in the CoreFX repo even if the code is in this CoreCLR repo (ie., in mscorlib/System.Private.Corelib). The reason for this is we sometimes move managed types between the two and it makes sense to keep all the issues together.

**Comment by GrabYourPitchforks** [comment]
FYI, I started addressing some of this in https://github.com/dotnet/corefxlab/pull/1881.

**Comment by GrabYourPitchforks** [comment]
Fixed in https://github.com/dotnet/coreclr/pull/21948.
