### ISSUE TITLE
Add String.Trim overloads that take a single char and string separator

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#14337]
## Proposed API
```c#
public sealed class String
{
    // Proposed
    public string Trim(char trimChar);
    public string TrimStart(char trimChar);
    public string TrimEnd(char trimChar);

    // Existing
    public string Trim();
    public string Trim(params char[] trimChars);
    public string TrimStart(params char[] trimChars);
    public string TrimEnd(params char[] trimChars);
}
```

## Motivation
Avoid unnecessary array allocations when you want to trim based on a single char.
- Similar to / consistent with recently approved #1513 `String.Split(char, ...)` and #5552 `String.Join(char, ...)`.

-------------------------------------------------

## Original discussion in CoreCLR repo

@Snesha commented on [Wed Oct 21 2015](https://github.com/dotnet/coreclr/issues/1826)

Complement String.Split additions for single char and string separator (https://github.com/dotnet/corefx/issues/1513). 

Proposed new APIs
public string[] Trim(char);
public string[] Trim(string);

CC @ellismg - any others? Or will these cover the complement?

---

@ellismg commented on [Thu Oct 22 2015](https://github.com/dotnet/coreclr/issues/1826#issuecomment-150398557)

I would not do Trim(string) (it's not clear to me what the semantics are) and do TrimEnd(char) and TrimStart(char) instead.  It feels like all three methods could use a common core.

---

@Snesha commented on [Tue Oct 27 2015](https://github.com/dotnet/coreclr/issues/1826#issuecomment-151571232)

TrimEnd(char) and TrimStart(char) are the new assignments. 

---

@ellismg commented on [Thu Oct 29 2015](https://github.com/dotnet/coreclr/issues/1826#issuecomment-152101611)

We have some internal folks looking into this.  Thanks everyone!

---

@danmosemsft commented on [Thu Dec 08 2016](https://github.com/dotnet/coreclr/issues/1826#issuecomment-265879193)

API request - moving to CoreFX .

**Comment by joperezr** [comment]
We would need a formal Api Proposal for in order to take this to review.

cc: @Snesha @ellismg

**Comment by joperezr** [comment]
@ellismg is this any different than #1513

**Comment by ellismg** [comment]
This is for Trim and not Split.

**Comment by justinvp** [comment]
Can we mark this ready for review?

Proposal:

```c#
public sealed class String
{
    // Proposed
    public string Trim(char trimChar);
    public string TrimStart(char trimChar);
    public string TrimEnd(char trimChar);

    // Existing
    public string Trim();
    public string Trim(params char[] trimChars);
    public string TrimStart(params char[] trimChars);
    public string TrimEnd(params char[] trimChars);
}
```

cc: @karelz

**Comment by karelz** [comment]
@justinvp what is motivation for the API additions? (quick read of the above doesn't answer it)

**Comment by justinvp** [comment]
The motivation is the same as #1513 (`String.Split`) and #5552 (`String.Join`): Avoids unnecessary array allocations when you want to trim based on a single char, and makes `String.Trim/TrimStart/TrimEnd` align with the similar recent single char additions to `String.Split` and `String.Join`.

**Comment by karelz** [comment]
Thanks, top post updated with your proposal & motivation.

**Comment by joperezr** [comment]
cc: @terrajobst can we add this to the agenda for next review?

**Comment by karelz** [comment]
API review meetings always start with a query of "api-ready-for-review" label. Nothing else is needed to put it on the agenda.

**Comment by joperezr** [comment]
@karelz thx, good to know.

**Comment by terrajobst** [comment]
Assuming the behavior is the same as calling the existing APIs with a an array of size one, these APIs look  good as proposed.

**Comment by justinvp** [comment]
FYI, I went ahead and grabbed this.

**Comment by danmosemsft** [comment]
Sounds good @justinvp !
