### ISSUE TITLE
[FileSystem] ValidFileOptions test failure

### ISSUE THREAD

**Issue by Maxwe11** [dotnet/corefx#1434]
[from CI](http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/849/console)

	Discovering: System.IO.FileSystem.Tests
	  Discovered:  System.IO.FileSystem.Tests
	  Starting:    System.IO.FileSystem.Tests
	  <Laks_jvhht23u>
	  .
		 System.IO.FileSystem.Tests.FileStream_ctor_str_fm_fa_fs_buffer_fo.ValidFileOptions [FAIL]
			System.UnauthorizedAccessException : Access to the path 'd:\j\workspace\dotnet_corefx_windows_release_prtest\bin\tests\Windows_NT.AnyCPU.Release\System.IO.FileSystem.Tests\dnxcore50\FileStream_ctor_str_fm_fa_fs_buffer_fo\ValidFileOptions_33' is denied.
			Stack Trace:
			   d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.IO.FileSystem\src\System\IO\Win32FileStream.cs(149,0): at System.IO.Win32FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs)
			   d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs(433,0): at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
			   d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.IO.FileSystem\src\System\IO\FileStream.cs(101,0): at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
			   d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.IO.FileSystem\tests\FileStream\ctor_str_fm_fa_fs_buffer_fo.cs(19,0): at System.IO.FileSystem.Tests.FileStream_ctor_str_fm_fa_fs_buffer_fo.CreateFileStream(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
			   d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.IO.FileSystem\tests\FileStream\ctor_str_fm_fa_fs_buffer_fo.cs(33,0): at System.IO.FileSystem.Tests.FileStream_ctor_str_fm_fa_fs_buffer_fo.ValidFileOptions()
	  Finished:    System.IO.FileSystem.Tests
	  
	  === TEST EXECUTION SUMMARY ===
		 System.IO.FileSystem.Tests  Total: 560, Errors: 0, Failed: 1, Skipped: 0, Time: 1.910s

**Comment by stephentoub** [comment]
This is consistently causing builds to fail.

**Comment by hpshelton** [comment]
Despite the fact that `GetTestFilePath` claims to generate a file path unique for each of its callers, it does not since there are multiple tests that call `GetTestFilePath` within a loop of some sort, which would lead to identical file paths being generated in the current implementation. This is likely causing collisions between files with the same name but various file modes or access handles.

**Comment by hpshelton** [comment]
The following seems to be sufficient to assign a unique suffix to every path generated by `GetTestFilePath`, but I'm not sure about the recommended method for adding a reference to System.Collections.Concurrent to the project since there doesn't seem to be documented guidance anywhere on the wiki. Let me know the right approach and I can submit a PR or it's probably faster for someone who knows to just copy/paste this code.
 
```
private static ConcurrentDictionary<string, int> UniqueSuffixes = new ConcurrentDictionary<string, int>();
public string GetTestFilePath([CallerMemberName]string fileName = null, [CallerLineNumber] int lineNumber = 0)
{
    string key = fileName + lineNumber;
    UniqueSuffixes.AddOrUpdate(key, 0, (k,v) => v + 1);

    return Path.Combine(TestDirectory, String.Format("{0}_{1}_{2}", fileName ?? "testFile", lineNumber, UniqueSuffixes[key]));
}
```

**Comment by stephentoub** [comment]
@ianhays, I expect this will go away with all of your cleanups around file naming and temporary files.

**Comment by ianhays** [comment]
I left the default GetTestFilePath() behavior the same - I never needed to call it inside of loops in my tests and it served my needs well.

With that said, this issue can be easily solved by adding an overload to GetTestFilePath that takes an int representing the iteration of the loop e.g.
```
int i = 0;
foreach (var f in fs)
    GetTestFilePath(i++);
```
That will solve the same name issues that appear to be arising without messing with any existing calls to the original GetTestFilePath

Alternatively, we could change GetTestFilePath() to use guids, but I'd prefer the file names remain static and not be randomly generated wherever possible. A ConcurrentDictionary would work as well, but I'd be worried about scalability and I think it would be a bit overkill.

I'll search out other instances of GetTestFilePath() being called in a loop and put up a PR today.
