### ISSUE TITLE
Improve code coverage for System.IO.FileSystem.AccessControl (0%)

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#14352]
We have almost [zero test coverage](https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem.AccessControl/tests/FileSystemAclExtensionsTests.cs) so our [code coverage is essentially zero](https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/Code_Coverage_Report/)

**Comment by karelz** [comment]
Grabbed by @the-dwyer (I will reassign once @the-dwyer accepts the collaborator invitation).

**Comment by karelz** [comment]
Fixed by #15375

**Comment by the-dwyer** [comment]
Hi.  I accepted the collaborator invitation.  I will give you a heads up when I grab work in the future.  Thanks, Michael

**Comment by karelz** [comment]
Thanks!
