### ISSUE TITLE
[AWS Linux][unsupported] X509Certificate2 fails on AWS Linux

### ISSUE THREAD

**Issue by darbio** [dotnet/corefx#14356]
How do I load a X509certificate on netcore?

The code:

`var x509Certificate2 = new X509Certificate2("certificatePair.pfx");`

Fails with the following exception when run on AWS Linux:

> {
>   "errorType": "LambdaException",
>   "errorMessage": "An exception was thrown when the constructor for type 'Lambda.Handlers.WebApiHandler' was invoked. Check inner exception for more details.",
>   "cause": {
>     "errorType": "TargetInvocationException",
>     "errorMessage": "Exception has been thrown by the target of an invocation.",
>     "stackTrace": [
>       "at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)",
>       "at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)",
>       "at System.Activator.CreateInstance(Type type, Boolean nonPublic)",
>       "at System.Activator.CreateInstance(Type type)"
>     ],
>     "cause": {
>       "errorType": "MissingMethodException",
>       "errorMessage": ".ctor",
>       "stackTrace": [
>         "at Interop.Crypto.Pkcs12Parse(SafePkcs12Handle p12, String pass, SafeEvpPKeyHandle& pkey, SafeX509Handle& cert, SafeX509StackHandle& ca)",
>         "at Internal.Cryptography.Pal.OpenSslPkcs12Reader.Decrypt(String password)",
>         "at Internal.Cryptography.Pal.PkcsFormatReader.TryReadPkcs12(OpenSslPkcs12Reader pfx, String password, Boolean single, ICertificatePal& readPal, List`1& readCerts)",
>         "at Internal.Cryptography.Pal.PkcsFormatReader.TryReadPkcs12(SafeBioHandle bio, String password, Boolean single, ICertificatePal& readPal, List`1& readCerts)",
>         "at Internal.Cryptography.Pal.CertificatePal.FromBio(SafeBioHandle bio, String password)",
>         "at Internal.Cryptography.Pal.CertificatePal.FromFile(String fileName, String password, X509KeyStorageFlags keyStorageFlags)",
>         "at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)",
>         "at Bunkr.RestApi.Startup.ConfigureServices(IServiceCollection services)",
>         "--- End of stack trace from previous location where exception was thrown ---",
>         "at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
>         "at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)",
>         "at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()",
>         "at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()",
>         "at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()",
>         "at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder)",
>         "at Lambda.Handlers.WebApiHandler..ctor()"
>       ]
>     }
>   }
> }

The code calling this:

https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/OpenSslPkcs12Reader.cs

**Comment by bartonjs** [comment]
It seems like you're missing either the native shim (System.Security.Cryptography.Native.OpenSsl.so) or maybe openssl (libcrypto.so.1.0.0 and libssl.so.1.0.0).

How did you get .NET onto the machine?

**Comment by darbio** [comment]
It's on AWS Lambda in their new C# functions. They're just using AWS Linux behind the scenes. 

Not sure how they loaded .Net. 

Is there a way to include the shim?

**Comment by bartonjs** [comment]
@darbio I don't know.  AWS Linux isn't a distro that we officially support (I didn't know it had dotnet available).  You might need to start with AWS if you're experiencing problems on a component they provide.

**Comment by darbio** [comment]
Thanks @bartonjs - dotnet works on AWS linux.

AWS announced last week at re:invent that they officially support C# on lambda:
https://aws.amazon.com/blogs/compute/announcing-c-sharp-support-for-aws-lambda/

For context, I've asked the question at:
https://forums.aws.amazon.com/thread.jspa?messageID=755578&#755578

**Comment by hvanbakel** [comment]
@darbio This seems to be related to importing an unsupported nuget package. I ran into the same issue when I had:
https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.JwtBearer/1.1.3
installed. However, I ran into a different exception when installing:
https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.JwtBearer/1.0.5

The difference here is in the dependencies:
1.1.3 depends on NETStandard.Library (>= 1.6.1) which I believe is why AWS fails.

**Comment by bartonjs** [comment]
Given that AWS now supports .NET Core 2.1 (https://aws.amazon.com/blogs/developer/aws-lambda-net-core-2-1-support-released/), and there aren't a lot of similar reports, whatever intermediate problem there was in AWS Lambda setup has seemingly been worked out.
