### ISSUE TITLE
CurrentDomain.GetAssemblies() functionality. 

### ISSUE THREAD

**Issue by alexpantyukhin** [dotnet/corefx#14359]
Hi! I know that this question was already discussed (https://github.com/dotnet/corefx/issues/1784#issuecomment-184409082) but unfortunally there was no direct question how to do it or some workaround. This is very needed functionality.

**Comment by karelz** [comment]
The API is back and will ship in 1.2: https://github.com/dotnet/corefx/blob/277b781b6326e06716173132f68317ddc475f67d/src/System.Runtime.Extensions/src/System/AppDomain.cs#L234

In the meantime, you can use AssemblyLoadContext.GetLoadedAssemblies().

**Comment by alexpantyukhin** [comment]
Thanks a lot!

**Comment by DivenLee** [comment]
Hello, I have the same needs. Did not find the method AssemblyLoadContext.GetLoadedAssemblies (), this method is derived from where? @karelz @alexpantyukhin

**Comment by karelz** [comment]
@DivenLee where did you look for the API? It is part of not-yet-shipped version 2.0 (see [roadmap](https://github.com/dotnet/core/blob/master/roadmap.md#ship-dates)).

**Comment by DivenLee** [comment]
Oh no, I thought it was a version 1.2 of API, and I really hope that 2 will come out soon. Thank you for telling me this. Thanks
