### ISSUE TITLE
Remove [Obsolete] from System.TimeZone?

### ISSUE THREAD

**Issue by justinvp** [dotnet/corefx#14365]
.NET Core used to only expose the newer `System.TimeZoneInfo`, but recently exposed the older `System.TimeZone` (#10074).

In .NET Core, `System.TimeZone` is currently marked as `[Obsolete]` in the [corelib implementation](https://github.com/dotnet/coreclr/blob/7d17af2deeca2af47bec4fab01f8c7e23ae3f5a8/src/mscorlib/src/System/TimeZone.cs#L30-L32) (under `FEATURE_CORECLR` ifdef), [netcore ref](https://github.com/dotnet/corefx/blob/021de2e711d8ae2c20e7a6270838611b2fdaa6b3/src/System.Runtime/ref/System.Runtime.cs#L2218), and [netstandard ref](https://github.com/dotnet/standard/blob/ab2921b4838e1c514077292f93338f275fff52cb/netstandard/ref/mscorlib.cs#L3234), however, it's **not** obsolete in the full framework.

I think `[Obsolete]` should be removed from `System.TimeZone` in .NET Core and .NET Standard, to match the full framework.

If I'm remembering correctly, the only reason `TimeZone` is obsolete in the mscorlib implementation for `FEATURE_CORECLR` is because we only wanted to expose `TimeZoneInfo` in Silverlight, and marking `TimeZone` obsolete internally helped prevent accidental internal callers inside mscorlib. Having it obsolete was only an internal implementation detail for CoreCLR. But now that it is being exposed publicly by design in .NET Core, I don't think it should be obsolete in the contracts or implementation. It should match the full framework.

cc: @weshaggard, @terrajobst, @tarekgh, @danmosemsft

**Comment by justinvp** [comment]
cc: @danmosemsft

**Comment by tarekgh** [comment]
We need to keep Obsolete because we don't want any new code to use this class and instead o use TimeZoneInfo. TimeZone is really not good choice to use and we have exposed it only because we want to cover the same service area for Xamarin. I am not seeing any problem to have this discrepancy with the desktop. 

Thanks.

**Comment by justinvp** [comment]
Then why isn't it marked Obsolete in the full framework? Are we obsoleting other "deprecated" APIs that are being exposed to cover Xamarin surface area?

**Comment by tarekgh** [comment]
> Then why isn't it marked Obsolete in the full framework?

we can consider marking it as Obsolete on the desktop. it is just not a priority item for the desktop as we don't see many new code is using it. 

> Are we obsoleting other "deprecated" APIs that are being exposed to cover Xamarin surface area?
I don't have the list but I think it make sense to do so.
