### ISSUE TITLE
Move ImmutableArray<T> and interfaces it implements to System.Runtime

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#14369]
These are all exchange types and should be useable anywhere on the stack.

**Comment by mellinoe** [comment]
> should be useable anywhere on the stack

Should it be in System.Private.CoreLib, then?

**Comment by karelz** [comment]
@weshaggard how do you look at it from layering point of view?

**Comment by weshaggard** [comment]
Form a layering prospective these are likely fine but we actually need an API proposal for exactly what we want to move. We also have to think about what does looks like for desktop.

**Comment by weshaggard** [comment]
cc @terrajobst

**Comment by nguerrera** [comment]
To answer @mellinoe's question, after discussion with @davidwrighton, it needs to be in System.Private.CoreLib.

**Comment by karelz** [comment]
@weshaggard is the target assembly sufficient for API proposal? Or do you/we need more?

**Comment by terrajobst** [comment]
@karelz 

I'd like to see:

* List of affected types
* Reference Assembly
* Implementation Assembly

**Comment by karelz** [comment]
Thinking about it more, this will have non-trivial impact on our packaging -- the type will be in Private.CorLib on .NET Core, yet it will be part of ImmutableCollection package on Desktop.
What is the value of this work?

At minimum it requires very good end-to-end proposal and thinking of the impact on ImmutableCollection NuGet package, our testing matrix and ability to ship that package (esp. on Desktop).

**Comment by davidwrighton** [comment]
So the reason I'm involved here is my desire to use System.Reflection.Metadata in the CoreRT runtime (which implies that it can essentially only depend on things that are in System.Private.CoreLib in the current system. I definitely believe we need to understand the costs here, as there are other ways to bring in the S.R.M code than simply to push all of the dependencies down into System.Private.CoreLib. The biggest concern I see is the impact on desktop, but I don't really have a good idea of the costs of performing these moves. I should have an ability to make some comment on the importance of my work and the dependency I'm adding on the S.R.M codebase by end of January.

**Comment by safern** [comment]
So do we still want this to happen or other people still needs it? Moving it down could be a nightmare so if we could avoid that would be nice.

**Comment by jkotas** [comment]
It should not be needed after https://github.com/dotnet/corefx/pull/15526. Also, #15526 highlighted the bad dependencies of the current implementation that make it hard to move down.

**Comment by safern** [comment]
Thanks for the update @jkotas, then I will go ahead and close the issue since this is not longer needed, if for some reason we need it in the future we could reopen.
