### ISSUE TITLE
could not run unit test if dependency library reference System.Security.Cryptography.Algorithms

### ISSUE THREAD

**Issue by h82258652** [dotnet/corefx#14368]
I have a class library which target .net standard 1.3.
And I use the MD5 class to hash the string.
```C#
    public static class HashHelper
    {
        public static string GetStringMD5(string str)
        {
            using (var md5 = MD5.Create())
            {
                var bytes = md5.ComputeHash(Encoding.UTF8.GetBytes(str));
                return BitConverter.ToString(bytes).Replace("-", "");
            }
        }
    }
```

But when I run the unit test, it throw System.IO.FileLoadException to me.
![qq 20161209233211](https://cloud.githubusercontent.com/assets/5144550/21054665/82396f92-be69-11e6-9610-5148462aa7a5.png)
even my unit test project install System.Security.Cryptography.Algorithms package.

I upload the demo here:
https://github.com/h82258652/NetCoreSystemSecurityCryptographyAlgorithmsCanNotUnitTest

Environment:
**OS:** Win10 14393 x64
**Unit Test Project:** .net framework 4.6.2
**Library:** .net standard 1.3
**Visual Studio:** 2015 Enterprise update 3

**Comment by karelz** [comment]
Is it problem on .NET Framewok 4.6.2 or on .NET Core?

Note: In general we do not track .NET Framework bugs on GitHub.

**Comment by karelz** [comment]
@bartonjs have you seen it before?

**Comment by bartonjs** [comment]
Looks like the library is building against netstandard and the tests are building against 4.6.2.  The facades should take care of this.

But it's not something that I've specifically seen, no.

**Comment by karelz** [comment]
@ericstj do you know who could help with this type of feedback on VS + .NET Framework?

**Comment by h82258652** [comment]
@karelz I think it's on .NET Framework 4.6.2. I try to use a UWP unit test project to run, it works.

**Comment by karelz** [comment]
This repo is about .NET Core, which is different stack than UWP / .NET Framework 4.6.2.
I will close the issue here.

@ericstj can you advise where to follow up on the issue? @h82258652 you can try to report the problem via VS Feedback ("Report Problem" in the right top corner)

**Comment by h82258652** [comment]
@karelz thanks for response.

**Comment by weshaggard** [comment]
@h82258652 That missing library is a library that should come from your package references as it isn't something that currently ships inbox on .NET Framework. Looking at your solution file it appears you are using packages.config for your .NET Framework unit test project. I would suggest switching to Project.json and adding the package reference there and I would expect that should correctly get the binary from the System.Security.Cryptography.Algorithms package to allow it to work.

**Comment by h82258652** [comment]
@weshaggard thanks for response, is there a tool convert packages.config to project.json?

**Comment by weshaggard** [comment]
I don't know but from a quick search I found https://github.com/NuGet/Home/wiki/Converting-a-csproj-from-package.config-to-project.json which might help you.

**Comment by h82258652** [comment]
@weshaggard thanks a lot.
