### ISSUE TITLE
Why is the class HttpStatusDescription internal ?

### ISSUE THREAD

**Issue by StefH** [dotnet/corefx#14374]
I was wondering why this class is made **internal** ?

Because I want to use this class to get a description from an HttpStatusCode ?

**Update + Reminder to myself**
I need this for this project : https://github.com/vtortola/WebSocketListener/blob/master/vtortola.WebSockets/Http/HttpStatusDescription.cs

**Comment by davidsh** [comment]
It's possible that we could mark this type as public.  But that is basically an API change to the public API surface.

Please look at the API proposal process:
https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/adding-api-guidelines.md

and feel free to submit a detailed proposal.

**Comment by StefH** [comment]
Hello @davidsh.

I've read that document, however I don't know what the exact steps would be for me.

Isn't it easier if you create an item on the backlog and that I can fill in why / how I would like to see this change ?

**Comment by davidsh** [comment]
cc: @karelz 

>Isn't it easier if you create an item on the backlog and that 

It will be a while before we can ever get to this. due to all the work we're currently doing  I've marked the item "up for grabs".  That allows the dev community such as yourself to contribute.

**Comment by karelz** [comment]
@StefH 
GitHub issues are our only backlog for .NET Core. Future milestone means we do not know if/when we will get to it.

If it is indeed just making the type public, then the API proposal work should be fairly simple. Just follow the API process doc - esp. the API proposal link. If it is still not clear, let me know.

**Comment by karelz** [comment]
Triage: 3 years old API proposal without being picked up by anyone and only 1 upvote. Not worth it at this time, closing.
We can reopen if there is more interest from additional customers / scenarios.
