### ISSUE TITLE
DNX breaks on Windows 7

### ISSUE THREAD

**Issue by eatdrinksleepcode** [dotnet/corefx#1438]
The build currently fails on Windows 7 during RestorePackages:

"c:\Users\danelson\Projects\Personal\dotnet\corefx\packages/dnx-coreclr-win-x86.1.0.0-beta5-11562\bin\dnu.cmd" restore --packages "c:\Users\danelson\Projects\Personal\dotnet\corefx\packages" "c:\Users\danelson\Projects\Personal\dotnet\corefx\src\System.ComponentModel\src/project.json"
System.EntryPointNotFoundException: Unable to find an entry point named 'GetVersion' in DLL 'api-ms-win-core-sysinfo-l1-2-
1'.
   at Microsoft.Framework.Runtime.NativeMethods.GetVersion_ApiSet()
   at Microsoft.Framework.Runtime.NativeMethods.GetVersion()
   at Microsoft.Framework.Runtime.NativeMethods.get_OSVersion()
   at Microsoft.Framework.Runtime.RuntimeEnvironment..ctor()
   at dnx.host.Bootstrapper.RunAsync(List`1 args)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)

I cannot pinpoint exactly when this broke because some of the DNX packages have disappeared from the MyGet feeds (e.g. 'dnx-clr-win-x86' version '1.0.0-beta5-11482').

**Comment by richlander** [comment]
Tangentially related, we don't have CI on Windows 7 right now. That's about to change.

**Comment by Eilon** [comment]
I think some Win7 stuff was indeed recently broken. @victorhurdugaci do you perhaps know what was broken, and/or ETA for a fix? Was it a CoreCLR issue or a DNX issue?

**Comment by ellismg** [comment]
(This is due to Eric's recent change to start using project.json for dependencies, which means we run dnu restore as part of the build).

**Comment by victorhurdugaci** [comment]
Should be fixed by https://github.com/aspnet/dnx/commit/cb3b40a872b4bc23c87d5c9982d4349f0382d43c
Update to the latest DNX

**Comment by ellismg** [comment]
Thanks, I will push a change through.
