### ISSUE TITLE
Improve code coverage for data contract serializers

### ISSUE THREAD

**Issue by khdang** [dotnet/corefx#1440]
Improve code coverage for DataContractSerializer and DataContractJsonSerializer

**Comment by zhenlan** [comment]
We can take a look of code coverage report and identify the areas that need more coverage.

**Comment by jguady** [comment]
This one looks like its been a long time coming. @danmosemsft 
Anything I should know about this one before I get started?

**Comment by shmao** [comment]
We ported many tests from full framework to corefx. The current test coverage for System.Runtime.Serialization.* is 84%.
