### ISSUE TITLE
Missing LINQ tests that validate correct number of iterations, delegate invocations, etc.

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#14419]
We're missing LINQ tests that validate that the input source enumerables are iterated no more than once, that delegates are invoked the correct number of times, etc.

**Comment by JonHanna** [comment]
GMTA. Already on it.

**Comment by stephentoub** [comment]
:) thanks!

**Comment by JonHanna** [comment]
And I've already got https://github.com/dotnet/corefx/pull/14306/files#diff-9d474ffffa0fc3771430e6ea15377aa2R458 ready to bring into it.

**Comment by JonHanna** [comment]
Okay, with that PR we've got never iterating more than once tested reasonably thoroughly.

Counts of delegate invocations is a bit more complicated in both ease of measuring and differences across different cases. It's also IMO somewhere where an observable change could perhaps be justified (though having tests flag it would still be worth doing; the count increasing should pretty much rule something out, the count decreasing might be argued for but wouldn't be a "simple" optimisation that could be just be submitted without discussion, so catching it sneaking in unnoticed would be great).

I'll take a look at that in a couple of days if nobody else has, but if anyone else has an interest in the meantime, I'm not licking that cookie, so feel free.

**Comment by stephentoub** [comment]
Not worth proactively adding more testing here.
