### ISSUE TITLE
Environment.GetEnvironmentVariables() should give back DictionaryEntry, not KeyValuePair

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#14417]
A recent change regressed Environment.GetEnvironmentVariables().  Its IEnumerable enumerator is supposed to yield ```DictionaryEntry``` items, but it's now yielding ```KeyValuePair<string,string>```.

cc: @JeremyKuhne

**Comment by Jiayili1** [comment]
Added "disabled-test" label

**Comment by Jiayili1** [comment]
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs#L186

**Comment by karelz** [comment]
@Jiayili1 FYI: removing the second area path.
