### ISSUE TITLE
Support plan for Digit separators in corefx

### ISSUE THREAD

**Issue by tanaka-takayoshi** [dotnet/corefx#14410]
Related to the roslyn issue https://github.com/dotnet/roslyn/issues/216, do you have any plan to support Digit separators in int.Parse, Conver.ToInt32, and other methods?

**Comment by karelz** [comment]
No plans at this moment. Do you have a proposal?
Is the Rolsyn change done deal? Which version will it be implemented in?

**Comment by AlexGhiondea** [comment]
It looks like we would need a formal API proposal for this.

**Comment by tanaka-takayoshi** [comment]
At present, It is only necessary for me to confirm there're no plans to support this.

```cs
//will be supported by Roslyn
var int i = 1234_5678;
var long l = 0x_dead_beaf;

//no plans to support?
Convert.ToInt32("1234_5678");
Convert.ToInt32("0xdead_beaf");
```

However, I'd like to hear other opinions.

**Comment by AlexGhiondea** [comment]
@tanaka-takayoshi as @karelz mentioned, we currently don't have any plans to support this.

We would like to consider this, but we would also want to make sure we follow the same pattern Roslyn is using.

Is this something you would be interested in pursuing?
