### ISSUE TITLE
[infrastructure] "GetTargetFrameworkProperties" does not exist in the project.

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#14423]
I have been running into the following issue very frequently over the past week or so:

```
Build FAILED.

"C:\Users\james\Code\git\corefx\src\System.Runtime\tests\System.Runtime.Tests.csproj" (RebuildAndTest target) (1) ->
"C:\Users\james\Code\git\corefx\src\System.Runtime\pkg\System.Runtime.pkgproj" (GetTargetFrameworkProperties target) (5) ->
  C:\Users\james\Code\git\corefx\src\System.Runtime\pkg\System.Runtime.pkgproj : error MSB4057: The target "GetTargetFrameworkProperties" does not exist in the project.


"C:\Users\james\Code\git\corefx\src\System.Runtime\tests\System.Runtime.Tests.csproj" (RebuildAndTest target) (1) ->
"C:\Users\james\Code\git\corefx\src\System.Private.Uri\pkg\System.Private.Uri.pkgproj" (GetTargetFrameworkProperties target) (6) ->
  C:\Users\james\Code\git\corefx\src\System.Private.Uri\pkg\System.Private.Uri.pkgproj : error MSB4057: The target "GetTargetFrameworkProperties" does not exist in the project.

...
```

Typically, I'll have no trouble running `msbuild /t:RebuildAndTest` on a project, but I will get one of these messages after the console runner finishes. ([example][1]) However, sometimes the build will simply fail (the tests won't even run) and 5 or more of these messages will pop up. The example above was what happened after I tried it under `src\System.Runtime\tests`.

I have made a gist that includes both the normal and `/v:detailed` output for the last-mentioned scenario: https://gist.github.com/jamesqo/55beb150ace9a290dde7b18c9f204f91#file-systemruntime-detailedlog (You can find `SystemRuntime-Log`, the normal-verbosity log, at the bottom.)

[1]: https://gist.github.com/jamesqo/55beb150ace9a290dde7b18c9f204f91#file-systemlinq-log

**Comment by karelz** [comment]
@mellinoe it is blocking @jamesqo in making progress on his contributions ... can you please provide any help here?

**Comment by mellinoe** [comment]
I've never seen this myself. Maybe it has something to do with the version of MSBuild you are using? I have only tried building corefx with MSBuild 14.0, and I believe we do the same in all of our CI runs.

Is there some pattern as to which projects are failing like this for you?

**Comment by karelz** [comment]
@jamesqo are you using any special version of msbuild? If yes, can you try 'standard' one ... just to narrow down where the problem is ...

**Comment by jamesqo** [comment]
@mellinoe Thanks for responding; I installed VS 2017 a while ago, so I am using MSBuild 15.0. I will try using MSBuild 14.0 tomorrow or so and see if everything works out.

**Comment by jamesqo** [comment]
It worked. Thanks for helping out!
