### ISSUE TITLE
Seg fault in X509Certificates tests

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#14432]
We've been seeing a seg fault happen in the X509Certificates tests with some regular frequency of late, e.g.
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx_release_prtest/1220/consoleText
https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu14.04_release_prtest/1313/consoleText
https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu14.04_release_prtest/1311/consoleText

I realize it's hard to diagnose without a dump, but we need to track it, regardless.

**Comment by JonHanna** [comment]
https://ci.dot.net/job/dotnet_corefx/job/master/job/centos7.1_release_prtest/1333/

**Comment by stephentoub** [comment]
https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu14.04_release_prtest/1338/

**Comment by JonHanna** [comment]
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx_release_prtest/1285/

**Comment by steveharter** [comment]
Only the last link still had data; osx_release
````
  /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_release_prtest/bin/tests/Unix.AnyCPU.Release/System.Security.Cryptography.X509Certificates.Tests/default.netcoreapp1.1/RunTests.sh: line 295: 21280 Segmentation fault: 11  (core dumped) ./corerun xunit.console.netcore.exe System.Security.Cryptography.X509Certificates.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonosxtests
````

**Comment by danmosemsft** [comment]
@sepidehMS please look out for a dumpfile for this onealso.

**Comment by JonHanna** [comment]
https://ci.dot.net/job/dotnet_corefx/job/master/job/centos7.1_release_prtest/2264/consoleFull#20242849304b7730ef-150b-4be7-a00f-82ba6c50792b

```
  /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_release_prtest/bin/Unix.AnyCPU.Release/System.Security.Cryptography.X509Certificates.Tests/netcoreapp/RunTests.sh: line 80: 24844 Segmentation fault      (core dumped) $RUNTIME_PATH/dotnet $EXECUTION_DIR/xunit.console.netcore.exe System.Security.Cryptography.X509Certificates.Tests.dll -noshadow -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests

**Comment by danmosemsft** [comment]
@steveharter @stephentoub does it make sense to close htis? No report for 2 months.
