### ISSUE TITLE
How free blocked assemblies in MEF2 (System.Composition 1.0.31) in .NET Core

### ISSUE THREAD

**Issue by HamedFathi** [dotnet/corefx#14433]
I wrote some codes :
```c#
    public interface IPlugin
    {
        string Name { get; set; }
    }
```
**ClassLibrary1.dll**
```c#
    public class Class1 : IPlugin
    {
        public string Name { get; set; } = "Hamed Fathi";
    }
```
and a Console :
```c#
    public static void Main(string[] args)
    {
        var dir = @"PLUGIN DIRECTORY PATH";
    
        //Load Assemblies
        var files = Directory.EnumerateFiles(dir, "*.dll", SearchOption.TopDirectoryOnly);
        var assemblies = new List<Assembly>();
        foreach (var file in files)
            assemblies.Add(AssemblyLoadContext.Default.LoadFromAssemblyPath(file));
    
        //MEF2
        var conventions = new ConventionBuilder();
        conventions
            .ForTypesDerivedFrom<IPlugin>()
            .Export<IPlugin>()
            .Shared();
        var configuration = new ContainerConfiguration()
            .WithAssemblies(assemblies, conventions);
        var container = configuration.CreateContainer();
        var plugins = container.GetExports<IPlugin>().ToList();
    
        Console.ReadKey();
    }
```
I want to use FileSystemWatcher for watching any changes in plugin's folder so I should can change/delete/rename/create any dlls.

so When I load assemblies based on above code I can not change/delete any dll in plugin's folder. (blocked assemblies)
![untitled](https://cloud.githubusercontent.com/assets/8418700/21082935/09786408-bffb-11e6-9b9c-ff0d0b70f383.png)

In .NET Framework I could use AppDomain and ShadowFolder for creating separated context and free assemblies.

Is there anyway to manipulate dlls when loaded by MEF2 ?

**Comment by Joe4evr** [comment]
Most likely not. There's no way to do multiple AppDomains in a single process with .NET Core because that concept exists only on Windows. If you're only going to run this on Windows machines, then target full .NET Framework as you did previously and use AppDomains to your heart's content.

**Comment by HamedFathi** [comment]
@Joe4evr , of course I try a way with loading dlls as stream (byte[]) so it works when the dll have not any dependencies but this way have 2 problems
1. Dependencies
2. Stream size and load all into memory

but this way help working with dlls without problem because no one was blocked !
```
public class AssemblyLoader : AssemblyLoadContext
{
    protected override System.Reflection.Assembly Load(AssemblyName assemblyName)
    {
        var deps = DependencyContext.Default;
        var res = deps.CompileLibraries.Where(d => d.Name.Contains(assemblyName.Name)).ToList();
        var assembly = System.Reflection.Assembly.Load(new AssemblyName(res.First().Name));
        return assembly;
    }
}

// My way for non blocking loading but have problem with dependencies
var asl = new AssemblyLoader();
var stream = new FileStream(dll, FileMode.Open);
using (stream)
{
    var data = new byte[stream.Length];
    stream.Read(data, 0, data.Length);
    var asm = asl.LoadFromStream(new MemoryStream(data));
    assemblies2.Add(asm);
}

```

**Comment by mellinoe** [comment]
I have a system to solve something similar (ish) in a project of mine. When I load "plugin assemblies", I copy the file to a separate (read-only) directory and load it from there. Essentially (although a bit simplified):

```C#
        private Assembly CopyAndLoad(string assembly)
        {
            string tempPath = Path.GetTempFileName();
            File.Copy(assembly, tempPath, true);
            return _loadContext.LoadFromAssemblyPath(tempPath);
        }
...
    public class EngineLoadContext : AssemblyLoadContext
    {
...
        protected override Assembly Load(AssemblyName assemblyName)
        {
            return Assembly.Load(assemblyName);
        }
    }
```

It sounds like you also want to support renaming, deleting, and reloading assemblies, which is probably going to be quite a bit trickier. I support reloading plugins, but only all-at-once. I don't use a `FileSystemWatcher` and do it on the fly, or anything like that. When I reload the plugin assemblies, I serialize all of the relevant state (essentially all object that could be referencing plugin state, create a new `AssemblyLoadContext`, reload all of the assemblies, and then deserialize the data.

**Comment by HamedFathi** [comment]
@mellinoe , Thanks for your answer.
I have 2 questions

1. I tested your code with Exception !!!!
```
    public class EngineLoadContext : AssemblyLoadContext
    {
        protected override Assembly Load(AssemblyName assemblyName)
        {
            throw new Exception(""); // BREAKPOINT HERE
        }
    }
```

I set a breakpoint in Load() and I called _loadContext.LoadFromAssemblyPath() but breakpoint did not fire !!! Why ? seems override the method does not effect !!!!
I believe I should override Load() method with new functionaly for CopyAndLoad Am I right ?

2. Consider I Copy whole dlls in another directory but How Can I remove/dispose/unload them from current AssemblyLoadContext ? because I want to reload changed assemblies not all directory (create a new directory for all new and old assemblies and create new AssemblyLoadContext for them so I need file based solution). Until a assembly locked by process I should copy and copy and copy directory so When can I free my hard disk from unused dlls ?

**Comment by mellinoe** [comment]
Right, unloading of assemblies is not supported right now, although it has been requested in the past and and is on our radar for eventual support.

>I want to reload changed assemblies not all directory

I don't have a good answer for that.

@gkhanna79 What would you recommend for this scenario?

**Comment by HamedFathi** [comment]
@mellinoe,  Microsoft support be support disposing context or unloading specific assembly from context for unblocking current dlls. AssemblyLoadContext should have some Unload methods/Options !!!
Thanks

**Comment by gkhanna79** [comment]
>  set a breakpoint in Load() and I called _loadContext.LoadFromAssemblyPath() but breakpoint did not fire !!! Why ? seems override the method does not effect !!!!

The breakpoint will be hit when static assembly references (i.e. assemblies referenced in manifest of the assembly being loaded OR when doing Assembly.Load) are resolved.

As @mellinoe mentioned, we do not have collectible load contexts yet. For your scenario, I would suggest that you do the following:

1) Load assemblies in a different LoadContext than Default - this is because once an assembly is loaded in a load context, you cannot load a another version of the same assembly in it.

2) when you have to load an assembly, read it first into a byte[] and then use LoadFromStream to load the assembly from the byte[]. 

3) When you see an new assembly, create a new LoadContext instance to load it in due to (1) above.

We will be looking into the collectible load contexts soon but until then, there is no way to unload a loaded assembly.

**Comment by HamedFathi** [comment]
@gkhanna79 

Ok thanks

**Comment by HamedFathi** [comment]
@gkhanna79 

I tried export types with MEF2 but have problem 
```
    public class Test : IClass
    {
        public Test()
        {
            Console.WriteLine("Hello : " + new Calculator().Add(6, 7));
        }
    }
    public class Calculator
    {
        public int Add(int a, int b)
        {
            return a + b;
        }
    }
    public interface IClass
    {
    }

public static void Main(string[] args)
        {
            var context = new CustomLoadContext();
            var assemblies = new List<Assembly>();
            var files = Directory.EnumerateFiles(@"PLUGIN FOLDER", "*.dll", SearchOption.AllDirectories);
            foreach (var file in files)
            {
                FileStream stream = new FileStream(file, FileMode.Open, FileAccess.Read);
                using (stream)
                {
                    byte[] data = new byte[stream.Length];
                    stream.Read(data, 0, data.Length);
                    var ass = context.LoadFromStream(new MemoryStream(data));
                    assemblies.Add(ass);
                }
            }

            var conventions = new ConventionBuilder();
            conventions
                .ForTypesDerivedFrom<IClass>()
                .Export<IClass>()
                .Shared();
            var configuration = new ContainerConfiguration()
                .WithAssemblies(assemblies);
            var container = configuration.CreateContainer();
            var types = container.GetExports<IClass>(); // ALWAYS NULL

            Console.ReadKey();
        }
```

types valirable always null Why ? whereas if I use AssemblyLoadContext.Default.LoadFromAssemblyPath() for loading assemblies MEF2 can load types without problem.

Can you guide me How can I using MEF2 when load assemblies by stream ?

**Comment by gkhanna79** [comment]
I am not familiar with MEF implementation to determine why `GetExports<IClass>` is returning null. What happens if you run the following code in the same context as the loaded assemblies?

```
var conventions = new ConventionBuilder();
            conventions
                .ForTypesDerivedFrom<IClass>()
                .Export<IClass>()
                .Shared();
            var configuration = new ContainerConfiguration()
                .WithAssemblies(assemblies);
            var container = configuration.CreateContainer();
            var types = container.GetExports<IClass>(); // ALWAYS NULL
```

**Comment by HamedFathi** [comment]
@gkhanna79  

I am so sorry, That is my fault, I should pass conventions variable as .WithAssemblies() parameter.
MEF2 works with this scenario.

Thanks for your help and guidance.
