### ISSUE TITLE
Error when running the CoreFX tests: 'The "GetTargetMachineInfo" task failed unexpectedly'.

### ISSUE THREAD

**Issue by varocarbas** [dotnet/corefx#14430]
After cloning the last CoreFX version (via Visual Studio or git) and running `build.cmd` (by also running `clean.cmd` before or not), I get various errors in the command prompt. Then, I am not able to execute some tests; not sure if all of them, but at least the ones in `System.Linq` and `Common`. Every time, I get the same error:

> The "GetTargetMachineInfo" task failed unexpectedly.

None of the aforementioned solutions contains a direct reference to `GetTargetMachineInfo` in their codes, not one which might be found by doing a global search.

I use Windows 7 SP 1 and Visual Studio 2015 Update 3. Some months ago, I was able to run all the tests without any problem; not sure if this was happening still with Windows 7 or with my previous OS (Windows 10).

**Comment by JonHanna** [comment]
I think you might be suffering from the same thing as is causing #14165.

**Comment by varocarbas** [comment]
@JonHanna And what do you suggest? A collective suicide or assassination? LOL. 

Thanks. I see lots of things going on there. I will take a calmed look at it at some point.

**Comment by JonHanna** [comment]
The good news is that since it seems you're being hurt by a known issue that is being looked into already, hopefully either https://github.com/dotnet/buildtools/pull/1249 or some other fix will be in soon and the problem will be solved.

**Comment by varocarbas** [comment]
@JonHanna  Sure, no problem. Actually, I have created this issue mostly to give more visibility to the this error and, eventually, help to fix it. I am not especially concerned about all this as far as I use CoreFX only eventuality (when having an idea for a new issue/PR, what happens at pretty random times).

**Comment by stephentoub** [comment]
Thanks. Dup of https://github.com/dotnet/corefx/issues/14165.

**Comment by varocarbas** [comment]
@terrajobst 
(Sorry for answering you from a different issue, but this is one of the drawbacks of locking an issue before getting an answer :))

>You're clearly passionate and enthusiastic about numerics

I am passionate about my work (= software development). Also I am quite honest and direct (don't need blind supporters or any other kind of additional advantage). I trust in my knowledge, my principles and always wanting something which is good for me and for others (never pursue egoist goals). All these features seem to be kind of weird in this community and I am sorry about it; I would never try to impose my views (even in case of being completely sure that they are objectively better).

>  I sense that you're upset ... they don't like you or your proposal ... can be quite frustrating

Sorry to correct you, but all these are misinterpretations of my words and expectations. I plainly accept anything. I don't even remember the last time I got (seriously) angry about anything. I don't even know what frustration is. I am very confident and am extremely sure about what I want and how I want to get it. If I see what seems an acceptable way to accomplish what I want, I would try it (always by accepting whatever the rules are there). Although I do certainly prefer to succeed, also accept failure mainly because of being completely aware about the extreme difficulty of getting all what I want exactly as I want it (failing 999 times and succeeding just 1 would be incredibly good news). For some people, getting the final goal is extremely important, even all what matters. Perhaps they have never failed and have always got what they wanted (or they thought they did). These people are usually very scared of failure or rejection (even though and ironically, they might have never experienced any of this) and find problems to understand why other people (like me) can fail many times; they don't understand that the process, the means, how everything is done at each point is all what matters, a prize in itself. People like me pride themselves of HOW get things (or what they have NEVER and WILL NEVER do under absolutely any circumstance). If I cannot get whatever goal by doing things as I think that I should, that goal would become unappealing. The process of trying/failing, being disappointed by people (their misunderstandings, their fears, their hopes which will never happen, etc.) and seeing how things gradually change but very slowly is certainly hard and really tiring. But when your whole personality is based upon such a hard reality, you don't feel frustration or angriness, only acceptation. Some people's lives are more difficult than others' and these difficulties can consist in anything (e.g., less means, less opportunities or, perhaps, very-difficult-to-accomplish expectations). People accepting themselves (what they are and what they want) rarely feel anger or frustration. I do fully accept myself.

> I have very little tolerance for ad hominem attacks

Undoubtedly, that closed issue lost its track completely (like others in which I have participated here). I also understand what this community wants and that some aspects of my attitude don't fit well here (more about this in the point below). But I am afraid that I cannot take all the fault for what I have been just a part; and not precisely the triggering part. I do certainly react in a way which isn't too compatible with the expectations here (and in quite a few other places) and do take full responsibility for that (what, BTW, I don't regret in most of the cases; when I do regret it, I would expressly apologise to that person), but this is all: REact. I am never the one starting. I am never the one with a hidden/dishonest/unfair intention. But I am the one whose ideas are very clear and who doesn't need to be patient or tolerant with what knows how will end (I have been really patient and tolerant in the past). So, I think that you (or others before you, in similar situations) are being quite unfair by exclusively blaming me; even though I was just one part, the part being clear, honest and who didn't start anything. Only because I use a format (e.g., aggressive expressions) with which you don't agree, you are ignoring all the underlying problems, everyone's actions/intentions and just censoring the easiest target (= me).

> If you want to be successful in our community you need to change your attitude

I am afraid that I will not change my attitude at all; in fact, my attitude will become every second more "my-ish". I do regret each single generous concession which I have made to appearance-based concerns. I only mean and aim what is best for the most (and am always ready to update my approach by taking honest and objectively better options in); anyone not willing to adequately understand, but to eminently focus on more or less secondary issues, like the way which I use to transmit my ideas, doesn't deserve my worries.
As a conclusion of the previous paragraph, I guess that the idea of "I don't want to be successful here" should be clear. I certainly tried to adapt to your proceedings because of assuming that it was a set of superficial requirements which, once overcome, would allow me to reach people/concerns/situations truly relevant to me. Apparently, I was wrong and the surface was also the final goal. No. I don't belong here, you cannot give me what I am looking for and I will never deliver what you want. I fully accept this reality (+ I am very happy with the acquired knowledge) and hopefully you will also see it in this way. 

Sorry about this a-bit-long reply, but it should help you (and others) to understand my position and why I am not intending to participate here again (I might submit some PRs, but certainly not a new issue). Please, don't misunderstand my opinion about all of you and your work (you can read it [here](https://varocarbas.com/open_net/general_impression/), under "OVER-8-MONTH-LATER UPDATE").
