### ISSUE TITLE
Move EditorBrowsableAttribute to Private.CorLib

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#14447]
We have multiple cases where we need to hide methods in Private.CorLib from IntelliSense:
- `Deconstruct` method on `KeyValuePair<TKey,TValue>` and `DictionaryEntry` - #13746
  - We can work around by shipping the method as Extension method
- `Span<T>` methods `Equals` and `GetHashCode` - https://github.com/dotnet/coreclr/pull/8583#issuecomment-266245506
  - No workaround

There is a risk that we won't be able to move the Attribute to mscorlib on Desktop (similar to fallout from moving `ExtensionAttribute` down - see https://github.com/dotnet/corefx/issues/13746#issuecomment-265829858)
Desktop options:
1. Deal with the impact of the type being moved in Desktop (compat fallout).
2. Don't attribute the methods on Desktop p i.e. they will be visible to IntelliSense on Desktop.
     - Question for @weshaggard: The attribute matters only for ref. What if the attribute is there in .NET Standard and in Desktop ref, but left out in Desktop implementation? Is that an option?
3. Don't port these methods to Desktop - i.e. they can't be part of .NET Standard.
4. Provide the methods as extension methods on Desktop - i.e. they can't be part of .NET Standard.

**Comment by weshaggard** [comment]
>Question for @weshaggard: The attribute matters only for ref. What if the attribute is there in .NET Standard and in Desktop ref, but left out in Desktop implementation? Is that an option?

These attributes are only needed in the reference assemblies and for .NET Core those are independently authored so we could just put them in the ref because EditerBrowsable lives in System.Runtime which is the lowest level ref. For desktop however they are not independently created so it would still need to be moved to mscorlib if we wanted to even use them for types in mscorlib's reference assembly.

**Comment by jkotas** [comment]
IMHO, there is not much to review from API addition point of view. Whether a type lives in CoreLib or System.Runtime is internal implementation detail in .NET Core...

**Comment by karelz** [comment]
@jkotas I'd like to discuss the impact on Desktop and our options ... I agree it is not quite API review :)

**Comment by AlexGhiondea** [comment]
@karelz is issue tracking the work needed for Desktop? Because on Core, as @weshaggard mentioned, that attribute is exposed via the System.Runtime contract.

**Comment by karelz** [comment]
It's tracking 2 things:
1. Discussion in API review that this is the pattern we want and are ok with.
2. Add the attribute on the particular APIs in .NET Core.

**Comment by jkotas** [comment]
This came up again during the review of https://github.com/dotnet/coreclr/pull/8695.

I have submitted PR to move it: https://github.com/dotnet/coreclr/pull/8703

**Comment by jamesqo** [comment]
Should this be closed?

**Comment by jkotas** [comment]
Not yet - there is follow up corefx change that needs to be done.

**Comment by karelz** [comment]
Don't we need any changes in CoreFX?

**Comment by karelz** [comment]
@jkotas can you remind me where we are with this issue?

**Comment by jkotas** [comment]
This is fixed now.
