### ISSUE TITLE
System.Net.Http 4.3.0 oob conflicts with framework assembly with target net462

### ISSUE THREAD

**Issue by cortex93** [dotnet/corefx#14445]
Hi,

These are the steps to reproduce the issue :
- Create a classic desktop library project in 462
- Add a nuget package "Microsoft.AspNetCore.Authentication" version "1.1.0"
=> This package targets both .NETFramework4.5.1 and .NETStandard1.3 with a dependency on NETStandard.Library 1.6.1 and has a framework assembly dependency on System.Net.Http for 4.5.1
```
<frameworkAssemblies>
      <frameworkAssembly assemblyName="System.Net.Http" targetFramework=".NETFramework4.5.1" />
    </frameworkAssemblies>
```
=> NETStandard.Library 1.6.1 has a dependency on System.Net.Http 4.3.0 for target NETStandard1.3
- In Class1.cs, add public static HttpClient client = new HttpClient(); // should bind to version 4.1.1.0
- nuget pack the csproj (using nuget latest version 3.5.0 rtm or 3.6.0)

- Create a core console app project targerting net462
- Reference the newly created package
- In Program.cs, add Console.WriteLine(ClassLibrary2.Class1.client.GetType().FullName);
- Run
- An exception FileNotFoundException is thrown about "System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"

From what I understand, all binaries should be using System.Net.Http 4.3.0 with a binding redirect from framework version.

project.lock.json shows that System.Net.Http is resolved from frameworkAssemblies 
```
".NETFramework,Version=v4.6.2": {
      "ClassLibrary2/1.0.0": {
        "type": "package",
        "dependencies": {
          "Microsoft.AspNetCore.Authentication": "1.1.0"
        },
        "compile": {
          "lib/net462/ClassLibrary2.dll": {}
        },
        "runtime": {
          "lib/net462/ClassLibrary2.dll": {}
        }
      },
      "Microsoft.AspNetCore.Authentication/1.1.0": {
        "type": "package",
        "dependencies": {
          "Microsoft.AspNetCore.DataProtection": "1.1.0",
          "Microsoft.AspNetCore.Http": "1.1.0",
          "Microsoft.AspNetCore.Http.Extensions": "1.1.0",
          "Microsoft.Extensions.Logging.Abstractions": "1.1.0",
          "Microsoft.Extensions.Options": "1.1.0",
          "Microsoft.Extensions.WebEncoders": "1.1.0",
          "NETStandard.Library": "1.6.1"
        },
        "frameworkAssemblies": [
          "System.Net.Http"
        ],
```

If I create another classic desktop 462 project, add System.Net.Http 4.3.0 and reference this project from the core console app. Then, project.lock.json is the same, but System.Net.Http 4.1.1.0 is copied to bin directory and a binding redirect is correctly generated as expected.

```
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="4.0.0.0" newVersion="4.1.1.0" />
      </dependentAssembly>
```

If you remove this last reference from project.json, rebuilding the project leave the binding redirect and assembly. Clean do not empty the bin directory and you must empty it manually to have the issue again. This leds to situation where you think it works while it will not when built from scratch.

```
Microsoft .NET Core Shared Framework Host
  Version  : 1.1.0
  Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86
```

and

```
"sdk": {
    "version": "1.0.0-preview2-1-003177"
  }
```

I don't understand why the framework assembly is chosen over the oob version.

Sample repo : https://github.com/cortex93/TestNetHttpRef

**Comment by karelz** [comment]
@ericstj can you please advise here on packaging?

**Comment by ericstj** [comment]
This is a CLI bug.  Please open in the dotnet/cli repo.  I believe it is the same as https://github.com/dotnet/cli/issues/4896 so reuse that one if it looks the same.  /cc @piotrpMSFT
