### ISSUE TITLE
System.Xml.EncodingStreamWrapper calls Flush on a read stream when being disposed

### ISSUE THREAD

**Issue by mconnew** [dotnet/corefx#14454]
EncodingStreamWrapper has two constructors, one for wrapping a stream for reading, and one for wrapping a stream for writing. When constructor a wrapper using the read constructor, the field _isReading is set to true (it's set to false when writing). In the Dispose(bool disposing) method, Flush is called on the wrapped stream regardless of whether the stream is only used for reading or not. If the wrapped stream doesn't implement Flush (and throws) because it's a read-only stream, this causes the Dispose() call to also throw. EncodingStreamWrapper should only call Flush if used to wrap a stream for writing.

**Comment by sepidehMS** [comment]
@shmao, @zhenlan could you please take a look?

**Comment by shmao** [comment]
Thanks, @sepidehMS . We will look into this.
