### ISSUE TITLE
Update corefx build configurations for Fedora 24 and 25

### ISSUE THREAD

**Issue by gpiercey** [dotnet/corefx#14469]
With Fedora 23 EOL on Dec 20, 2016 the corefx build configurations should be updated to support source builds on Fedora 24 and 25. 

release/1.1.0:
- seems to have build configuration for Fedora 24 but it is not mentioned in README.md
- needs a build configuration for Fedora 25
- build & test status in README.md should include Fedora 24 and 25 instead of 23.

release/1.0.0:
- needs build configurations for Fedora 24 and 25
- build & test status in README.md should include Fedora 24 and 25 instead of 23.

**Comment by karelz** [comment]
@mellinoe opinions?

**Comment by mellinoe** [comment]
These are release ("servicing") branches, so we won't be adding large new features to them, like support for a new distro. In the future, distro support and the build process around them will be less rigidly-defined.

As for whether we should continue to build for and support Fedora 23 after its EOL, I guess that's a bigger question about our servicing support for OS's which aren't maintained anymore. It's a broader question than just Fedora (e.g. Ubuntu 16.10 will go out of support in July). @karelz How do you think we should handle this?

**Comment by gpiercey** [comment]
I am mostly concerned with build support for current distros (Fedora 24, 25 and RHEL 7) in the 1.0.x and 1.1.x (or  1.2.x/2.0.x) release streams as we go forward. It looks like build support for RHEL 7 is in place but the support for Fedora seems to be a little outdated. 

I don't know what the timeline looks like for this new build process but if it is not immanent can we consider adding support for current distros for the next corefx releases using the mechanism that is currently in place?

**Comment by karelz** [comment]
The new build process is now in progress (dev/eng branch). The plan is to have it light up in master branch in early January.
Adding support for additional distros (or their versions) without the new build process is extremely costly (think 1-2 weeks per distro). As such we do not plan to go that route unless absolutely necessary.

**Comment by gpiercey** [comment]
January is not far away so I'll take a look at the dev/eng branch. Is it far enough along for me to start using the new build process? Are there any docs available for it yet?

**Comment by karelz** [comment]
I don't think it is ready for usage yet. You can peek at the docs changed in the branch ... (vertical build)

**Comment by weshaggard** [comment]
As part of our 2.0 ship matrix we will be adding support for Fedora 25.

**Comment by omajid** [comment]
@weshaggard, not sure what your timelines are, but Fedora 26 is expected to release in June: https://fedoraproject.org/wiki/Releases/26/Schedule. It might be a good idea to target that. Last year .NET Core 1.0 and Fedora 24 were released a few days of each other and 1.0 didn't support 24.

**Comment by weshaggard** [comment]
Fedora 26 is on our list to watch but it isn't clear yet whether that will happen in our 2.0 timeframe.

**Comment by mellinoe** [comment]
To clarify, we expect that Fedora 25 will be supported by our "Portable Linux" binaries in .NET Core 2.0. We are not going to be producing any Fedora 25-specific stuff in corefx, so I don't believe there is any particular work to be done for this here in corefx. We have an internal work item filed to ensure that we have test coverage on Fedora 25.

**Comment by y2kiah** [comment]
Those of us running F25 or F26 can run dotnet core just fine inside a vagrant box, but I want to develop using VS Code installed on my host OS. This scenario still doesn't work since Code cannot resolve the package locations, and everything is just red squigglies. How can I "fake" it so that VS Code on the fedora host can resolve installed packages, while having the actual compiles binaries inside the vagrant box? I've tried just copying the .nuget path into my home to no avail.

**Comment by karelz** [comment]
@y2kiah I am not sure what we can do in CoreFX about that. This issue is/was about our internal infrastructure - i.e. ensuring we produce bit which can be installed on F25/F26 at all.
Your question is likely more suitable for VSCode repo - can you please ask there?

If you find out anything that we, CoreFX/.NET Core team, should change to enable the VSCode scenario, please let us know.
