### ISSUE TITLE
ManagedWebSocket HTTP scenarios implementation

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#14480]
Tracking the implementation of the following items:

- [ ] ClientWebSocketOptions.UseDefaultCredentials
- [ ] ClientWebSocketOptions.Credentials
- [ ] ClientWebSocketOptions.Proxy
- [ ] ClientWebSocketOptions._sendBufferSize

**Comment by karelz** [comment]
Dupe of #5120
