### ISSUE TITLE
Span: DangerousCreate should avoid argument validation

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#14486]
For Span/ReadOnlySpan DangerousCreate method, should we remove the following test cases to increase performance:
* SpanTests - DangerousCreateNullObject
* SpanTests - DangerousCreateBadLength
* ReadOnlySpanTests - DangerousCreateNullObject
* ReadOnlySpanTests - DangerousCreateBadLength

It was suggested that the Fast and Slow Span implementations should not do the check/throw on null object or negative lengths to speed up creation of the instance of Span/ReadOnlySpan.

That is, these checks should be removed:
```C#
        public static ReadOnlySpan<T> DangerousCreate(object obj, ref T objectData, int length)
        {
            if (obj == null)
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.obj);
            if (length < 0)
                ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.length);
```

Should they be removed?

**Comment by AlexGhiondea** [comment]
@KrzysztofCwalina is this something you are working on?

**Comment by karelz** [comment]
@KrzysztofCwalina ping?

**Comment by ahsonkhan** [comment]
Next step: Do the work highlighted in the original issue post. Should be simple to fix.

**Essentially remove the checks in the below methods and the corresponding tests:**

https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/Span.cs#L139
https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/ReadOnlySpan.cs#L139

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Span.cs#L147
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/ReadOnlySpan.cs#L130

**Comment by WinCPP** [comment]
@karelz @ahsonkhan May I work on this?

**Comment by ahsonkhan** [comment]
Go for it :)

**Comment by WinCPP** [comment]
Thanks! Working on this.

**Comment by WinCPP** [comment]
@ahsonkhan @jkotas I have created above two PRs for the comment update...
