### ISSUE TITLE
ExcludeFromCodeCoverageAttribute cannot be applied to assemblies

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#14488]
We have added `ExcludeFromCodeCoverageAttribute` back into our public API's as part of the .NET Standard 2.0 work. We've been using a local version of this attribute in many of our test assemblies in order to control what shows up in our code coverage reports. The public version we are now exposing does not allow the attribute to be applied to assemblies, so our test assemblies cannot use the public version of the attribute. Test assemblies can continue using the internal version of the attribute, but then we get ambiguity warnings from the compiler, which we need to suppress.

We could potentially just allow the .NET Core version of the attribute to be applied to assemblies, even though the .NET Framework version doesn't allow it.

@weshaggard

**Comment by JonHanna** [comment]
> We could potentially just allow the .NET Core version of the attribute to be applied to assemblies

That would have potential uses for other users, as an alternative means of excluding the test projects themselves from coverage.

Alternatively, since the rule is `-excludebyattribute:*.ExcludeFromCodeCoverage*` then something like `ExcludeFromCodeCoverageAssemblyAttribute` should also be excluded from coverage and need not be exposed.

**Comment by mellinoe** [comment]
> Alternatively, since the rule is -excludebyattribute:*.ExcludeFromCodeCoverage* then something like ExcludeFromCodeCoverageAssemblyAttribute should also be excluded from coverage and need not be exposed.

Good point. I wasn't sure how we were actually getting the coverage tools to recognize that attribute. I assumed it was hardcoded in some way to the .NET framework type name. But if we control that, we can just call our internal type something different.

**Comment by JonHanna** [comment]
I've done similar for projects I had compiling different versions for frameworks 3.5 and 4.0. For the 4.0 build I used the framework's type, but since it didn't exist in 3.5 I had my own internal attribute, and since the exclusion is by name, it works fine.

**Comment by weshaggard** [comment]
I'd be fine using another attribute type for this. cc @stephentoub

**Comment by rodchenkov** [comment]
Can you please confirm that in next release ExcludeFromCodeCoverageAttribute will be available for any developer?

Here in documentation https://msdn.microsoft.com/en-us/library/jj159530.aspx I can see that ^System\.Diagnostics\.CodeAnalysis.ExcludeFromCodeCoverageAttribute$ is used for ignore in code coverage but I can use it as it is marked as sealed.

Thank you!

**Comment by JonHanna** [comment]
@rodchenkov in the meantime, you can use a different script to match a different attribute or with the common match of `*.ExcludeFromCodeCoverage*` just create your own with a matching name.

**Comment by danmosemsft** [comment]
@rodchenkov yes, it will be available in .NET Core 2.0, which is the upcoming shipping version. (Albeit - not legal to apply to assemblies, as mentioned above)

**Comment by rodchenkov** [comment]
@JonHanna @danmosemsft thank you!

**Comment by abatishchev** [comment]
Why not make it public, or better extend the existing one?

**Comment by danmosemsft** [comment]
I'm guessing that since we didn't need it for our own purposes it was sufficient to just port a-is and so the original proposal got a bit lost.

@weshaggard what was the concern you had about @mellinoe 's proposal?

It would make it easy to create a library that would not load on desktop., however a new attribute would be no different, and the compiler would flag this when you targeted desktop.

**Comment by mellinoe** [comment]
I never intended for this to turn into a public API proposal, really. We already have a new attribute that we are using locally in corefx. If someone has need of this as a general-use API, then i think they should file a separate API proposal through the regular process.

**Comment by danmosemsft** [comment]
As above

**Comment by abatishchev** [comment]
Please don't close it. Let's (re-)address it instead:

- Make `[ExcludeFromCodeCoverageAttribute]` applicable to assemblies

or

- Make `[ExcludeFromCodeCoverageAssemblyAttribute]` public.

Neither one would be a breaking change.

**Comment by JonHanna** [comment]
I would see making the current attribute applicable to assemblies as sensible, though it should probably go through a new issue as an API change.

**Comment by danmosemsft** [comment]
@abatishchev thanks for the suggestion... for clarity please open an API proposal separately.

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md
