### ISSUE TITLE
Dead link in framework guidlines

### ISSUE THREAD

**Issue by ubershmekel** [dotnet/corefx#1448]
At the bottom of https://github.com/dotnet/corefx/wiki/Framework-Design-Guidelines-Digest there's a link to http://code.msdn.microsoft.com/codeanalysis which redirects and says "The Archive Gallery has been retired."

**Comment by weshaggard** [comment]
cc @terrajobst

**Comment by ghuntley** [comment]
This should probably point to https://msdn.microsoft.com/en-us/library/bb429476(v=vs.80).aspx
