### ISSUE TITLE
Question: How to use ZipArchive in aspnet core

### ISSUE THREAD

**Issue by wjzhou** [dotnet/corefx#14485]
I try to generate zip file on the fly though ZipArchive in an aspnet core program.

In various places, ZipArchive access the base stream's Position property, which throw NotImplementedException in the aspnet core's FrameResponseStream.

For now, I have to wrap the FrameResponseStream in yet another wrap and implement the Position property.

Is there a better way to handle that? Thank you.

I think it is easy to trace these position inside the ZipArchive instead of depend on external base stream's Position property

**Comment by jnm2** [comment]
https://github.com/dotnet/corefx/pull/12682

**Comment by ianhays** [comment]
@wjzhou this was fixed recently in ZipArchive so we track Position with a wrapper stream in ZipArchive. You probably need to update your version of Sys.IO.Compression.

 closing as duplicate/resolved of https://github.com/dotnet/corefx/pull/12682.
