### ISSUE TITLE
Time to revisit need to register code pages provider?

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#14496]
I'm working on localization of dotnet/cli itself and I hit an issue where csc on .NET Core on Windows can give me garbled text if I'm on a non English machine with corresponding satellite assemblies present. 

The root cause is https://github.com/dotnet/corefx/issues/10054. I'm going to have to ensure that msbuild, cli, and roslyn all call Encoding.RegisterProvider(CodePagesEncodingProvider.Instance) before outputting anything to the console in non-English locales.

I'm concerned that this pain point for .NET Core on Windows is not worth the benefit of making the code page data "optional". I say optional in quotes because the shared framework carries System.Text.Encoding.CodePages.dll and if I publish a standalone .NET Core app with our tools and the usual steps, System.Text.Encoding.CodePages is copied in to my app folder. Is anyone actually getting the benefit of not having System.Text.Encoding.CodePages?

Given the high likelihood of System.Text.Encoding.CodePages.dll being present in practice, could System.Console light-up on it somehow? i.e. If it's there next to System.Console.dll, then use it regardless of whether register has been called whenever the console code page is not UTF8  and text outside ASCII range is written?

@terrajobst @tarekgh @karelz 

FYI @piotrpMSFT @cdmihai @jaredpar

**Comment by tarekgh** [comment]
@nguerrera in Linux, the default encoding in console is UTF8 so in main stream cases you wouldn't experience this in Linux. on Windows, Windows team currently working hard to get the console working seamlessly with UTF8 too and eventually this will be the default encoding. 

I understand your point but I am really hoping at one day people will not care about codepages encoding at all and Unicode will be everywhere. my understanding is CLI and Roslyn handling that already. 
I am not pushing back on the request, I am just trying to explain what we need to achieve in long term. 

will try to talk to more people and get more input to decide what to do. thanks for raising the issue,

**Comment by nguerrera** [comment]
> Windows team currently working hard to get the console working seamlessly with UTF8 too and eventually this will be the default encoding.

I will cry tears of joy when the Windows console defaults to UTF8. In the meantime, though, let's do the best we can for today's Windows reality. ;)


> my understanding is CLI and Roslyn handling that already.

The CLI does. Roslyn still has a bug open on it: dotnet/roslyn#10875. I also had to file one against msbuild: dotnet/msbuild#1477

**Comment by tarekgh** [comment]
discussed the issue offline with nick and other folks and we are going to add some support in the Console to handle the encoding without bringing the whole encoding data and code. we'll just have a wrapper around Windows encoding APIs and hook it to the Console.

I'll try to work on this next week or so.

**Comment by mellinoe** [comment]
> if I publish a standalone .NET Core app with our tools and the usual steps, System.Text.Encoding.CodePages is copied in to my app folder

That's not really true; or it shouldn't be, at least. My standalone projects don't include that assembly, for example, because they don't reference the package. We are going to regress this (and a lot of other similar stuff) with the new packaging unless we implement dependency trimming in the tooling.

**Comment by nguerrera** [comment]
@mellinoe Sorry, I misspoke (or at least exaggerated). If you reference individual packages, it works fine with latest csproj-based tooling. However, if Microsoft.NETCore.App is referenced (which we encourage in docs and give you upon dotnet new or file new project) then the code page package is pulled in. Is this any different from prior tooling? I think there's still an issue: either we need better docs on how to trim manually or we need automatic trimming of some kind.

**Comment by mellinoe** [comment]
> Is this any different from prior tooling?

No, that's absolutely correct. I was actually thinking of our "new" packaging, for .NET Core 2.0. We are going to be removing all of the individual component nuget packages in favor of one giant one. Unless we have automatic (or manually-guided) dependency trimming in the tooling, then there really will be no way to "modularly" publish your application, e.g. opt out from CodePages.dll or whatever else. They will always be published, like you mentioned.

**Comment by nguerrera** [comment]
This brings up some other issues even with current packaging vs small-as-possible standalone apps. I'll open a new issue about that as its orthogonal to this.

I'm happy we found a solution that makes Console just work without the large data. As I said offline, that's a good place to land because there's a big difference between these:

* Encoding.GetEncoding(850) -> “System.NotSupportedException: No data is available for encoding 850. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
 
* Console.WriteLine("Comment ça va?") -> Comment ├ºa va?
 
The first one tells me exactly what my problem is while the second one silently behaves incorrectly.

**Comment by tarekgh** [comment]
This should be fixed now by the linked PR.

**Comment by nguerrera** [comment]
👏 

Thanks!
