### ISSUE TITLE
After upgrading NetStandard.Library from 1.6.0 to 1.6.1, getting FileLoadException.

### ISSUE THREAD

**Issue by awcullen** [dotnet/corefx#14495]
After upgrading my library's  dependency on NetStandard.Library from 1.6.0 to 1.61, my unit tests fail: 
System.IO.FileLoadException: Could not load file or assembly 'System.Net.Sockets, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.

My library's json:
{
  "supports": {},
  "dependencies": {
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.NETCore.Portable.Compatibility": "1.0.1",
    "NETStandard.Library": "1.6.1",
    "Portable.BouncyCastle": "1.8.1.2",
    "StyleCop.Analyzers": "1.0.0",
    "System.Threading.Tasks.Dataflow": "4.7.0"
  },
  "frameworks": {
    "netstandard1.3": {}
  }
}

My unit test's json:
{
  "dependencies": {},
  "frameworks": {
    ".NETFramework,Version=v4.6.1": {}
  },
  "runtimes": {
    "win": {},
    "win-x86": {},
    "win-x64": {},
    "win-arm": {}
  }
}

The full project is at https://github.com/convertersystems/opc-ua-client.

thanks, Andrew

ps: Projects that use this library from a package work just fine. It's just the solution's unit tests with a problem.

**Comment by karelz** [comment]
@weshaggard what is NetStandard 1.6.1?

@awcullen do you have minimal repro?

**Comment by weshaggard** [comment]
@ericstj have you seen this issue? It sounds sort of familiar but I don't remember it hitting in the context of desktop.

**Comment by weshaggard** [comment]
@awcullen do you know which library has the reference to System.Net.Sockets 4.1.0.0?

**Comment by ericstj** [comment]
Sounds like a downgraded package.  Did you see any warnings from NuGet after making the upgrade of that package in the library?  I'll clone your repo and try it out.

**Comment by ericstj** [comment]
No package downgrade.  This is happening because the test assembly isn't generating binding redirects.  You'd hit the same issue if one of your dependencies used a different version of any of your dependencies (eg: BouncyCastle, JSON.Net, etc).

Add the following properties to your test CSProj:
```xml
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
```

Here's the issue on MSBuild tracking this:
https://github.com/Microsoft/msbuild/issues/1310

**Comment by tarekgh** [comment]
closing the issue by @ericstj workaround. @awcullen please feel free to reopen the issue if the problem still happening. Thanks.
