### ISSUE TITLE
Vertical build from source cleanup tasks

### ISSUE THREAD

**Issue by chcosta** [dotnet/corefx#14492]
Post PR (https://github.com/dotnet/corefx/pull/14171) cleanup tasks
- [x] Enable building System.Private.Xml.Linq
- [x] Enable building System.Runtime.Serialization.Formatters
- [x] Enable building System.Threading.Overlapped
- [x] Eliminate duplication between src\ref.builds, src\src.builds and GatherProjectsForVerticalBuild in buildvertical.targets
- [x] eliminate duplication in buildvertical.props
- [x] Fix Property / Item names and general code cleanup in buildvertical.targets
- [x] Output binaries to spec location
- [x] Properly derive BuildConfiguration (currently hard-coded to `netcoreapp1.1-$(OS)`
- [ ] System.runtime.InteropServices.RuntimeInformation, investigate the GeneratePlatformNotSupportedAssembly Condition which I've temporarily disabled
- [x] Enable building System.Runtime.CompilerServices.Unsafe.ilproj
- [x] Move TargetsOS properties into Configurations.props?
- [x] Cleanup all the duplicated definitions for AnnotateProjectsWithConfiguration (currently in buildvertical.targets, dir.targets, dir.traversal.targets)
- [ ] Programmatically determine References for Unix
- [x] Ignored references to System.Threading.Overlapped and System.Runtime.Serialization.Formatters in Microsoft.Private.CoreFx.NetCoreApp package, re-enable after building those references again.
- [x] ref\System.Runtime.Extensions configurations are currently set to netstandard1.7 because netcoreapp1.1 was failing to build, fix the build and add netcoreapp1.1 to the configurations.

**Comment by weshaggard** [comment]
lets please add remove buildvertical.targets to the list and fold it into our other common targets in build tools.

**Comment by weshaggard** [comment]
@chcosta how many of these are still applicable?

**Comment by chcosta** [comment]
I think that all of these have been addressed or are no longer applicable.
