### ISSUE TITLE
Add IsEmpty property to ArraySegment<T>

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/corefx#14502]
ArraySegment  can be created as empty by using `default(ArraySegment<T>)` or using `ArraySegment<T>.Empty` property. If we try execute any operation on such segment then it will throw invalid operation exception. To protect from calling such operations I suggest to add `IsEmpty` property to `ArraySegment`. Also most operation do nothing if segment has zero length. And user code can use `IsEmpty` property to improve performance for empty segment.  As additional, structures `Span` and `ReadOnlySpan` have `IsEmpty` properties already.

```cs
namespace System
{
    public struct ArraySegment<T>
    {
        public bool IsEmpty => Count == 0;
    }
}
```

**Comment by ianhays** [comment]
Could you post some code examples of what is difficult to do now that would be simpler with `IsEmpty`?

**Comment by safern** [comment]
Since nobody else has commented in this issue and we didn't get any code examples on what is difficult to do with what we've got now we are going to close it.
