### ISSUE TITLE
Packages threw exception '[Error 267] The directory name is invalid' & '[Error 2] The system cannot find the file specified'

### ISSUE THREAD

**Issue by jiangzeng** [dotnet/corefx#14503]
No results generated.

For win8 & win7: [Error 267] The directory name is invalid' 
```
2016-12-14 03:11:58,546: WARNING: proc(37): run_and_log_output: Could not find C:\dotnetbuild\work\6e004e14-ed1e-4b54-97ec-08d5c930039a\Work\7beb0736-c746-4508-9354-7277b7be03a8\Unzip\RunTests.cmd on disk.  Execution may fail.
2016-12-14 03:11:58,551: ERROR: logs(86): _log_uncaught_exception: Unhandled error: [Error 2] The system cannot find the file specified
['  File "C:\\dotnetbuild\\work\\6e004e14-ed1e-4b54-97ec-08d5c930039a\\Payload\\RunnerScripts\\scriptrunner\\scriptrunner.py", line 91, in <module>\n    sys.exit(main())\n', '  File "C:\\dotnetbuild\\work\\6e004e14-ed1e-4b54-97ec-08d5c930039a\\Payload\\RunnerScripts\\scriptrunner\\scriptrunner.py", line 87, in main\n    return command_main(_main, [\'script=\'], args)\n', '  File "C:\\dotnetbuild\\scripts\\helix\\cmdline.py", line 47, in command_main\n    return main_method(settings, optlist, args)\n', '  File "C:\\dotnetbuild\\work\\6e004e14-ed1e-4b54-97ec-08d5c930039a\\Payload\\RunnerScripts\\scriptrunner\\scriptrunner.py", line 44, in _main\n    env=None\n', '  File "C:\\dotnetbuild\\scripts\\helix\\proc.py", line 46, in run_and_log_output\n    shell=False)\n', '  File "C:\\Python\\lib\\subprocess.py", line 710, in __init__\n    errread, errwrite)\n', '  File "C:\\Python\\lib\\subprocess.py", line 958, in _execute_child\n    startupinfo)\n']
2016-12-14 03:11:58,555: INFO: azure_storage(199): _upload: Uploading single blob: '4e0759f44fa245fc84ec7861ab2fe091.log'
2016-12-14 03:11:59,009: INFO: saferequests(90): request_with_retry: Response complete with status code '201'

```

For win10: [Error 2] The system cannot find the file specified
```
2016-12-14 03:18:59,398: WARNING: proc(37): run_and_log_output: Could not find C:\dotnetbuild\work\d15e87c1-82b1-40b9-a105-2832e5527c53\Work\53280074-1a02-42e9-896a-59d31484f86e\Unzip\RunTests.cmd on disk.  Execution may fail.
2016-12-14 03:18:59,398: ERROR: logs(86): _log_uncaught_exception: Unhandled error: [Error 2] The system cannot find the file specified
['  File "C:\\dotnetbuild\\work\\d15e87c1-82b1-40b9-a105-2832e5527c53\\Payload\\RunnerScripts\\scriptrunner\\scriptrunner.py", line 91, in <module>\n    sys.exit(main())\n', '  File "C:\\dotnetbuild\\work\\d15e87c1-82b1-40b9-a105-2832e5527c53\\Payload\\RunnerScripts\\scriptrunner\\scriptrunner.py", line 87, in main\n    return command_main(_main, [\'script=\'], args)\n', '  File "C:\\dotnetbuild\\scripts\\helix\\cmdline.py", line 47, in command_main\n    return main_method(settings, optlist, args)\n', '  File "C:\\dotnetbuild\\work\\d15e87c1-82b1-40b9-a105-2832e5527c53\\Payload\\RunnerScripts\\scriptrunner\\scriptrunner.py", line 44, in _main\n    env=None\n', '  File "C:\\dotnetbuild\\scripts\\helix\\proc.py", line 46, in run_and_log_output\n    shell=False)\n', '  File "C:\\Python\\lib\\subprocess.py", line 710, in __init__\n    errread, errwrite)\n', '  File "C:\\Python\\lib\\subprocess.py", line 958, in _execute_child\n    startupinfo)\n']
2016-12-14 03:18:59,398: INFO: azure_storage(199): _upload: Uploading single blob: 'f7e71ee5ee4f4089bfeffc987e84636d.log'

```

Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20161214.01/workItem/Packages

Build : Master - 20161214.01 (Core Tests)
Failing configurations: Win81, Win7 & Win10

**Comment by karelz** [comment]
@mellinoe can you please route it?

**Comment by mellinoe** [comment]
This looks like a Helix issue (something is going wrong in the python scripts). Maybe someone on the Helix team can identify the problem. It might just be some sort of intermittent connectivity or disk space issue?

**Comment by danmosemsft** [comment]
@MattGal who's the right person to look at this test failure?

**Comment by MattGal** [comment]
This isn't a test failure, it's an infra bug.  An extra Packages.zip is now getting created that is treated like a test, but since it contains no scripts or tests.  

I filed https://github.com/dotnet/core-eng/issues/253 to track this.  I suspect it's related to recent work @karajas

**Comment by MattGal** [comment]
Update:  I spent some time looking at this this morning, and I see the problem.  Not sure how this only turned up recently, but back in August, @ianhays added duplicated msbuild targets to corefx's build.proj from buildtools:

 https://github.com/dotnet/corefx/commit/2674f14a0cf854ae265e6ee74061641425d01e1b

Which puts the extra unnecessary packages.zip in an incorrect place (it should not be in a TFM specific folder as it could easily contain files from more than one TFM) and causes this problem.

We should remove this from build.proj and instead depend on the version from CloudTest.targets, modifying that if needed to support whatever reason Ian decided to duplicate the build content.

**Comment by ianhays** [comment]
Yup, that one is mine alright. I recall facing some issues in CloudTests where package generation was tied into something azure-y that I didn't want to do, so I opted to copy the zip generation rather than move a bunch of stuff around in CloudTests. 

A little bit of context here: the ARM64 test build builds the source and the tests for everything with `ArchiveTests=true`, then builds a packages.zip with all the packages from the DependencyList, then zips the packages and the test folders and sends them to a lab machine to unzip and call RunTests for each library.

The simplest, fastest solution here would be to modify the copied targets in build.proj to be conditionally included on `Platform==ARM64` and fix the placement of the zip. The more correct but potentially more time consuming solution is to make it use CloudTests and modify CloudTests as needed.

The ARM64 test build is broken right now anyways which I'm looking into (`Unable to resolve version` on test project.json), so I'll work on the CloudTests thing simultaneously.

**Comment by MattGal** [comment]
Thanks @ianhays .  I'd love to hear about what parts of it you had difficulty excluding (I have some guesses) and get a work item or two tracking fixing CloudTest.targets to be able to do what it already does plus what you need.  It may just be simpler to split it into 2+ files and import those files from the uber CloudTest.targets.

It's not blocking anyone so no huge rush, but if you could make things conditional on platform as noted whenever you fix the ARM test build, that will clean up the spurious test failures for now.
