### ISSUE TITLE
Make TimeZoneInfo.AdjustmentRule.BaseUtcOffsetDelta public

### ISSUE THREAD

**Issue by mj1856** [dotnet/corefx#1450]
I would like to propose that `TimeZoneInfo.AdjustmentRule.BaseUtcOffsetDelta` be marked `public` instead of `internal`.  This can be seen [here](https://github.com/dotnet/coreclr/blob/d46b09d4dfc8e25d7e61a9994f89720cf01b5086/src/mscorlib/src/System/TimeZoneInfo.cs#L3754).

There are several reasons:

- The `AdjustmentRule` class is loaded from registry information, loosely matching the `_REG_TZI_FORMAT` structure.  (See [this article](http://blogs.msdn.com/b/bclteam/archive/2007/06/07/exploring-windows-time-zones-with-system-timezoneinfo-josh-free.aspx)).
-  The whole reason this property was added ([KB3012229](https://support.microsoft.com/en-us/kb/3012229)) is such that the data from the registry can be better reflected in this class.  Specifically, the `_REG_TZI_FORMAT.Bias` value can change from year to year, so `AdjustmentRule.BasUtcOffsetDelta` was created to track the delta between the year-to-year bias and the default bias for the time zone.
- There's no good reason (IMHO) to keep this internal.  Doing so means that the full functionality of the `AdjustmentRule` class can really only be used when populated by the framework itself.  It also makes understanding the way that the framework populates the class difficult, as all fields are exposed through public properties *except* this one.
- It creates problems for those trying to use it in other scenarios.  See Example 2 in Jon Skeet's post [Backward Compatibility Pain](http://codeblog.jonskeet.uk/2015/03/02/backward-compatibility-pain/).

Additionally, there needs to be some public way to create an `AdjustmentRule` that has a value for this property.  Either the existing `CreateAdjustmentRule` factory method should be made public, or a parameter could be added to the existing constructor, or another constructor could be added.

Thanks for your consideration.

**Comment by mj1856** [comment]
@tarekgh - your thoughts please. :smile:

**Comment by tarekgh** [comment]
@Matt what you have proposed make sense for current implementation. the question I am thinking in which I didn't investigate yet is, at some point we need to switch to use IANA data, does the current types will still make sense? I mean type like AdjustmentRule still make sense for instance. It may still be valid but I am not sure yet. 

other point is we'll not be able to expose this for current releases but we can do it in the future repos.

I'll mark this item as API add request and we can track adding the API. please let me know your thoughts too.

**Comment by tarekgh** [comment]
by the way, I was trying to expose this API when we add it but couldn't as it was added in the servicing release

**Comment by mj1856** [comment]
Thanks.

I have mixed feelings on about supporting IANA time zones in `TimeZoneInfo`.   Sure - they're better (IMHO) than Windows zones on many levels.  But there's a lot of legacy code out there that expects `TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time")` to work.

Are you suggesting that the story for `TimeZoneInfo` in CoreCLR on OSX & Linux would be that you can call `TimeZoneInfo.FindSystemTimeZoneById("America/New_York")`?   If so - what purpose would that serve?  Those using the existing IDs would still not have a working solution, and there's already good OSS support in [Noda Time](http://nodatime.org) (and others) for working with IANA time zones across all platforms.

That aside - could it work?  Perhaps.  I'd be concerned that `AdjustmentRule` might be too limited to support all of the edge cases of the IANA zones.  It's modeled differently, in that it has a pair of DST start and end for each rule.  IANA zones might have an odd number of transitions that don't fit well into that structure.   There are also links/aliases to consider, and one would need CLDR data to populate `DisplayName`, `StandardName`, and `DaylightName`.  Plus you have the localization issue (since those don't participate in `CurrentUICulture`).  There's a lot to work out there - many separate changes, and I'm not sure that it would be worthwhile.

It might make more sense just to leave the current API surface alone, and enable Linux and OSX via a mapping layer.  Feed the IANA data from the OS through [CLDR mappings](http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml), to populate `TimeZoneInfo` with the same type of data it would have traditionally taken from the Windows registry.

Or you could just bundle and distribute the Windows data.  But that might get messy with regard to updates.

**Comment by mj1856** [comment]
I guess the big question is, what is more important? Legacy compatibility, or feature enhancements?  For many things, I'll all about feature enhancements. But in this particular regard, I think the expectation would be for compatibility.

**Comment by tarekgh** [comment]
My thinking is if we can keep the compatibility and support  the new data in same time that will be perfect. As I mentioned before I didn't investigate that yet but this is what I am currently thinking. 
so we can support both Windows and IANA zone names and we'll depend on IANA data for calculations and try to move away from using Windows registry data. this can help giving better calculation results especially for historical data and in same time will make TimeZoneInfo work across platforms without any problem

**Comment by mj1856** [comment]
I'd love that in general.  The devil is in the details of course. :wink: 

When you're ready, let's open another issue to talk through the points.  I think this issue can move forward separately.  Thanks.

**Comment by tarekgh** [comment]
Yes this issue is marked as ready for API review. we'll just wait a little bit till this review get scheduled

**Comment by terrajobst** [comment]
We [reviewed this issue today](https://github.com/dotnet/apireviews/tree/master/2015-04-28-misc#1450-make-timezoneinfoadjustmentrulebaseutcoffsetdelta-public). We believe part of it is ready but the creation of `AdjustmentRules` is currently out-of-scope for .NET Core. If that's important to you, you should file a separate issue. Please see the notes for more details.

**Comment by mj1856** [comment]
Thanks for reviewing this issue.   I've watched the review video, and would like to clarify a few points:

- Yes, I work at Microsoft, for AzureCAT p&p.  I'm also a Pluralsight author ([Date and Time Fundamentals](http://www.pluralsight.com/courses/date-time-fundamentals)), and a contributor to both [Noda Time](http://nodatime.org/) and [moment.js](http://momentjs.com/).  I'm also one of the top ranked answers about timezones and datetime questions StackOverflow.  I've helped numerous other teams at Microsoft, and I know these particular APIs *very* well.  I'd be happy to stop by and talk to any of you about time zones and date/time issues at your convenience.

- It is incorrect that you can't create custom time zones or adjustment rules.  This functionality is available via the methods:

  - `TimeZoneInfo.CreateCustomTimeZone` | [MSDN](https://msdn.microsoft.com/en-us/library/system.timezoneinfo.createcustomtimezone.aspx) | [CoreCLR](https://github.com/dotnet/coreclr/blob/39c5df949fa58a8c4c1766c55d8975fe6d0bf3b0/src/mscorlib/src/System/TimeZoneInfo.cs#L1231-L1237)
 - `TimeZoneInfo.AdjustmentRule.CreateAdjustmentRule` | [MSDN](https://msdn.microsoft.com/en-us/library/system.timezoneinfo.adjustmentrule.createadjustmentrule.aspx) | [CoreCLR](https://github.com/dotnet/coreclr/blob/39c5df949fa58a8c4c1766c55d8975fe6d0bf3b0/src/mscorlib/src/System/TimeZoneInfo.cs#L3798-L3803)

- The original intent of the issue was actually *not* on creating custom adjustment rule, but rather being able to *fully* read the adjustment rules created by the framework.  If I load a time zone with `TimeZoneInfo.FindSystemTimeZoneById("Russia Standard Time")`, that zone contains base information and adjustment rules loaded from the Windows registry, and those adjustment rules have different DST offsets from year to year.   Currently, there's no direct way to access that information.

  The workarounds are either 1) use reflection to get at the private field, 2) examine the serialization output from `ToSerializedString`, or 3) to convert certain values from UTC to local time and examine the result.  None of these are ideal.

- Despite the intent being on *reading* the framework-created adjustment rules, it would still be important to support creating them as well.  Since it's *currently* possible to create custom adjustment rules, it is rather odd that the framework can create them in such a way that offers more functionality than the public factory methods.

- I agree that it would be better to expose the actual UTC offset from year to year as a fixed value in the adjustment rule, but since adjustment rules *can* be constructed with `CreateAdjustmentRule`, and an adjustment rule is completely detached from the time zone during the construction process, then that would mean that the implementation would have to change.  The adjustment rule would not be able to just store the delta in a field.  It would have to store the full offset for the period defined over that rule.

  I think this would be preferred, as it would more closely align an adjustment rule with the registry data.   It's just a lot more work than simply exposing the current internal field.  If it's agreed that this is the preferred implementation, I will start on a PR.

**Comment by tarekgh** [comment]
@mj1856 to clarify, creating custom TZ is not exposed in the contracts that can be used in coreclr. I know the code is there but you cannot call it except if you want to reference the implementation assembly directly. this is why we said it is exposed for desktop only.

I think the approval for exposing the adjustment rule UTC offset is satisfying the ask for this issue. if we need to support custom TZ we can take this as separate issue. 

The implementation  of the exposure will need to be done in the future repo. I'll try to get back to you later with more details so you can do it there if you are interested in doing it. 

Thanks, 
Tarek

**Comment by mj1856** [comment]
Sure.  One question though - how can I tell what is exposed and what is not?  Is that somewhere in CoreFX?  Or is that in the coming new repo?   Sorry, but it's a bit confusing how these separations work.

**Comment by tarekgh** [comment]
@mj1856 here is the branch we need to do the work there https://github.com/dotnet/corefx/tree/future when you have finish coding, submit the PR against this branch and not against the master. 
Thanks

**Comment by mj1856** [comment]
Sorry to get caught up in the logistics, but I still don't understand how I the separation works.  I see `TimeZoneInfo.cs` only in CoreCLR, shouldn't the PR be made there?

**Comment by tarekgh** [comment]
good point. I forgot it is in the coreclr. let me check if we need to have a future branch for coreclr too.

**Comment by mj1856** [comment]
Chatting with @eerhardt about this and related things, I now realize that `AdjustmentRule` isn't exposed *at all* in .NET Core.  He's working on what to do about Linux time zone support, and there could be some changes required.  Therefore, I think it's prudent to wait and do this later, or as part of his effort.   Doing it now wouldn't help anything, and might lock us into a design that doesn't hold up with the rest of the changes.

**Comment by tarekgh** [comment]
I agree with @mj1856 on not rushing exposing this (or the adjustment rules) before having long term plan for TZI. we can use the issue #2465 to track getting the long term plan figured out
