### ISSUE TITLE
Span: Create Span from IntPtr

### ISSUE THREAD

**Issue by ektrah** [dotnet/corefx#14507]
(ReadOnly)Span\<T> is designed so that it can point to native memory. So far, native memory is typically represented by a SafeHandle (e.g., SafeMemoryMappedViewHandle) or an IntPtr (e.g., as returned by Marshal.AllocHGlobal). It will probably a common use case to create a (ReadOnly)Span\<byte> from these.

*Proposal:*

Add a constructor overload that accepts an IntPtr and a length:

```diff
  public struct Span<T>
  {
+     public Span(IntPtr pointer, int length) { ... }

  public struct ReadOnlySpan<T>
  {
+     public ReadOnlySpan(IntPtr pointer, int length) { ... }
```

*Example Usage 1:*

```csharp
int length = 4096;
SafeHandle handle = VirtualAlloc(IntPtr.Zero, new IntPtr(length), 0x3000, 0x04);

bool addedRef = false;
try
{
    handle.DangerousAddRef(ref addedRef);
    MyMethod(new Span<byte>(handle.DangerousGetHandle(), length));
}
finally
{
    if (addedRef)
    {
        handle.DangerousRelease();
    }
}
```

*Example Usage 2:*

```csharp
int length = 512;

IntPtr hglobal = Marshal.AllocHGlobal(length);
try
{
    MyMethod(new Span<byte>(hglobal, length));
}
finally
{
    Marshal.FreeHGlobal(hglobal);
}
```

There is currently a constructor overload that accepts a void* and a length, and an IntPtr can of course easily be converted to a void* using the IntPtr.ToPointer method. However, this requires `<AllowUnsafeBlocks>true</AllowUnsafeBlocks>` and is the only instance in the API surface where an `unsafe` code block is required. It would be nice if spans could be used without `unsafe` code blocks. IMHO requiring `unsafe` when working with native memory doesn't really make things safer since there are already methods like Marshal.ReadInt32 that can be used to read or write arbitrary native memory through an IntPtr.

**Comment by omariom** [comment]
Creating spans from unmanaged memory is inherently unsafe operation. And what is unsafe should  stay `unsafe`.

**Comment by ektrah** [comment]
Unmanaged memory itself is inherently unsafe.

I think it's a good idea that unsafe code literally contains the word "unsafe". However, it is not the case that an IntPtr by itself is safe and creating a Span from it is unsafe. *Everything* that involves an IntPtr is unsafe. So, in addition to the words "unsafe" and "Dangerous", the appearance of the word "IntPtr" is an indication that an operation involving it is potentially unsafe. I don't think the cast to `void*` is necessary to make that clear, given the large number of methods in corefx that accept an IntPtr and that don't require an `unsafe` code block or have the word "Dangerous" in their name.

**Comment by morganbr** [comment]
Having direct handling for SafeHandles might also be good so users don't need to get the DangerousAddRef/DangerousReleaseRef pattern in example 1 correct. I wonder if it's even worth having Span's lifetime semantics keep the SafeHandle alive correctly.

**Comment by jkotas** [comment]
Allowing a safe `SafeBuffer` -> `Span` conversion sounds pretty reasonable. It is no different from a safe `Memory<T>` -> `Span<T>` conversion. The exact pattern for it is still being discussed. Once the design for it is settled, it should naturally extend to `SafeBuffer` -> `Span` conversion as well.

However, we are unlikely going to add a Span constructor that takes IntPtr as a pointer. `void*` is highly preferred for all new APIs that take unsafe pointers. Yes, it means that you have to have an extra cast to `(void*)` when interoperating with existing code that uses IntPtr for unsafe pointers.

cc @KrzysztofCwalina

**Comment by morganbr** [comment]
@jkotas SafeBuffer also sounds somewhat interesting since it even comes with a length, but it's much less common than SafeHandle+length. I'd love to see some kind of support for both.

**Comment by AlexGhiondea** [comment]
I am going to close this since it does not look like we would like to take this API.
