### ISSUE TITLE
Clean-up the batch restore and project.json generation stuff

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#14513]
We removed the batch restore and project.json generation targets from build.proj (https://github.com/dotnet/corefx/pull/14476) but we have some more clean-up to do. In particular we need to clean-up config.json. We also have a bunch of stuff in BuildTools in this area that we should go in and clean out.

cc @chchosta @karajas

**Comment by joperezr** [comment]
I can go ahead and do this cleanup at least on corefx side. Does it make sense still to keep a sync.cmd/sh anymore? I'm looking at the supported aliases and Values and it doesn't seem that they will be used at all, but perhaps you intend to repurpose the script?

**Comment by weshaggard** [comment]
I've been debating whether or not to keep sync but I think I would like to keep it for now and just have it build the external path and so folks can pull all the external dependencies as a pre-step as necessary.

**Comment by joperezr** [comment]
sounds good, I'll take care of it
