### ISSUE TITLE
Linq Cast<T> does not call cast overloads

### ISSUE THREAD

**Issue by ScottKaye** [dotnet/corefx#14511]
Consider the following classes:

```cs
public class A
{
	public int Va { get; set; }

	public static implicit operator B(A a)
	{
		return new B { Vb = (long)a.Va };
	}
}

public class B
{
	public long Vb { get; set; }
}
```

Class `A` has an overload to convert `A` into `B`.

Now imagine we have a collection of `A`:

```cs
var list = new List<A>()
{
	new A { Va = 1 },
	new A { Va = 2 }
};
```

If we wanted to cast this list to `B`, one would assume to use `list.Cast<B>().ToList()`.  However, we are met with `InvalidCastException: Unable to cast object of type 'A' to type 'B'.`

It seems that the source of this error is [from here](https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Cast.cs#L51) where `CastIterator` iterates over each item as `object`.  By changing this to `dynamic`, `.Cast<TResult>()` works as expected with overloaded operators.

Is this an acceptable PR to make, or is there a reason behind using `object` where `dynamic` would appear to provide more functionality?

**Comment by JonHanna** [comment]
Well consider the difference in what those two things are. By way of comparison a comparable one-item cast method `static TResult DoCast<TResult>(object obj) => (TResult)obj;` compiles to:

```CIL
ldarg.0     
unbox.any   UserQuery.TResult
ret
```
While a one-item cast method `static TResult DoCast<TResult>(dynamic obj) => (TResult)obj;` compiles to:

```CIL
ldsfld      UserQuery+<>o__1<>.<>p__0
brtrue.s    IL_002C
ldc.i4.s    10 
ldtoken     UserQuery.TResult
call        System.Type.GetTypeFromHandle
ldtoken     UserQuery
call        System.Type.GetTypeFromHandle
call        Microsoft.CSharp.RuntimeBinder.Binder.Convert
call        System.Runtime.CompilerServices.CallSite<System.Func<System.Runtime.CompilerServices.CallSite,System.Object,>>.Create
stsfld      UserQuery+<>o__1<>.<>p__0
ldsfld      UserQuery+<>o__1<>.<>p__0
ldfld       System.Runtime.CompilerServices.CallSite<System.Func<System.Runtime.CompilerServices.CallSite,System.Object,>>.Target
ldsfld      UserQuery+<>o__1<>.<>p__0
ldarg.0     
callvirt    System.Func<System.Runtime.CompilerServices.CallSite,System.Object,>.Invoke
ret   
```

If you were using a form of C# without `dynamic` you could rewrite it as:

```C#
static TResult DoCast(object obj)
{
	var callSite = CallSite<Func<CallSite, object, TResult>>.Create(
	    Binder.Convert(
	    	CSharpBinderFlags.InvokeSimpleName | CSharpBinderFlags.BinaryOperationLogical, typeof(TResult),
        	typeof(WhateverClassThisIsIn)));
	return callSite.Target.Invoke(callSite, obj);
}
```

We might be able to keep the `CallSite` between each cast (in fact the CIL above does grab a memoised callsite when it can) but we still don't want to go through that `Invoke` for every single cast in any of the cases where Linq's `Cast` method currently works.

I'm also not very sure changing the specified behaviour so much wouldn't be breaking (I'm quite sure as generally changing a case that always throws an exception to a case that does something useful won't break much, but I'm not 100% there isn't a case where this doesn't have a behaviour impact beyond that).

The method you describe is very different in both behaviour and impact. Maybe there's a place for a separate `DynamicCast<TResult>()` method that behaves this way.

**Comment by JonHanna** [comment]
Though I wouldn't use such a dynamic cast in the example given, I'd use Select there.

**Comment by stephentoub** [comment]
Thanks for the suggestion, but I don't believe we have an appetite to use `dynamic` inside of LINQ.
