### ISSUE TITLE
EntryPointNotFoundException on .NET Core on Linux

### ISSUE THREAD

**Issue by rottor12** [dotnet/corefx#14510]
I want to prepare a wrapper library for a 3rd party library on linux

I've created 2 simple functions, and from another C++ program they execute without a problem

also .. I've tried to use system library (libc) and it works without issues:

[System.Runtime.InteropServices.DllImport("libc")]
public static extern int puts(string str);

puts("some test string"); // <- this works

however, when I try to use my 2 simple function from my wrapper library, I'm getting EntryPointNotFoundException exception

here is the code:

[System.Runtime.InteropServices.DllImport("mywrapper")]
public static extern void TestFunc1();
[System.Runtime.InteropServices.DllImport("mywrapper")]
public static extern string TestFunc2();

Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'TestFunc1' in DLL 'mywrapper'.

the library is found, and from C++ these two functions just work
also ... a DLLImport puts(const char *) works in .NET Core

only my library has this problem

any ideas ?

**Comment by karelz** [comment]
cc: @janvorli

**Comment by janvorli** [comment]
@rottor12 do you have extern "C" on your functions? If not, their names would be mangled.

**Comment by rottor12** [comment]
@janvorli I was missing extern "C" before method signatures, but .. after the change to extern "C", and ldconfig, I'm still getting the same error

**Comment by janvorli** [comment]
@rottor12 could you please run `objdump -T mywrapper.so` and paste here the results?

**Comment by rottor12** [comment]
I had another copy of an old library in the .NET Core project, and that is why the error still persisted

once I removed it (so it could load a version from /usr/lib64) it run the first function correctly, the second produced an error, but that I'll handle on my own

big thanks for your help !!

**Comment by janvorli** [comment]
Great, I am glad to hear that!
