### ISSUE TITLE
Q: why is ValueTuple IsLayoutSequential false

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#14518]
e.g. typeof(ValueTuple<int,string>).GetTypeInfo().IsLayoutSequential returns false

Looking at the ValueTuple.cs code, I can't figure out why it isn't returning true.

**Comment by vcsjones** [comment]
They are explicitly marked as `Auto`, not `Sequential`:

https://github.com/dotnet/corefx/blob/fd15ab1de03a4431e0ead9ff10e1bf53e2ae4bb7/src/System.ValueTuple/src/System/ValueTuple/ValueTuple.cs#L431

So this lets the CLR decide what the layout kind will be. I would expect `IsAutoLayout` to return true.

**Comment by tmds** [comment]
Thx @vcsjones. Only looked at ValueTuple and ValueTuple\<T1> which don't have the attribute...
