### ISSUE TITLE
Facades need packaged.

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#14528]
`System.dll` and others aren't currently part of the packages.

@weshaggard, @ericstj

**Comment by karelz** [comment]
What's the impact? It sounds like must-have for 2.0 ...

**Comment by JeremyKuhne** [comment]
It is critical for running existing code and important for our own reflection needs. Came across this specifically because of System.Configuration implementation work I'm doing. I need to implicitly load types (via Type.GetType) that used to live in System.dll.

**Comment by jkotas** [comment]
Yes, it is must have 2.0. Related issues:

https://github.com/dotnet/corefx/issues/13020
https://github.com/dotnet/coreclr/issues/7607

**Comment by weshaggard** [comment]
Yes we are definitely planning to ship these shims for 2.0.

**Comment by ericstj** [comment]
Ditto, this is planned.  This is just an issue tracking that plan so that folks can `ActiveIssue` tests against it.

In addition to including them, we actually need to build them first...   Including them is trivial and will happen in dev/eng.

**Comment by weshaggard** [comment]
The shims are now being produced (https://github.com/dotnet/corefx/blob/master/src/shims/shims.proj). They are only included in the Microsoft.NETCore.App package currently.
