### ISSUE TITLE
Enable OOB / netstandard-based packages in dev/eng

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#14520]
We've disabled all the package builds.  We need to re-enable them once we decide on the workflow for building their contents.

**Comment by weshaggard** [comment]
Also clean out all the ones we don't plan to ship any more.

**Comment by weshaggard** [comment]
@ericstj I believe this is now fixed. Is there any further follow-up work here?

**Comment by ericstj** [comment]
Yep, fixed.
