### ISSUE TITLE
Span: Fix array variance checks in slow Span

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#14533]
Related to PR #14262 where the test got removed.

- The test should be renamed to something like CtorVariantArrayType since the type is not wrong.
- The test should confirm that the operation is succeeding, i.e. a ReadOnlySpan instance gets created successfully rather than checking that the method fails and throws.

https://github.com/dotnet/corefx/pull/14262#discussion_r92521521

**Comment by jkotas** [comment]
Also, fix the implementation of the slow span to not throw exception in this case...

**Comment by karelz** [comment]
Next step: Do the work highlighted in the top post by @ahsonkhan .
Should be simple (1h work).

**Comment by jkotas** [comment]
This is not just a test issue. The primary issue here is that the array variance checks are done incorrectly in the slow Span.

**Comment by jkotas** [comment]
It is not complex.

**Comment by shiftylogic** [comment]
PR Submitted (#17361)
