### ISSUE TITLE
PInvoke for empty function takes over 300 usec - is it normal ?

### ISSUE THREAD

**Issue by rottor12** [dotnet/corefx#14567]
extern "C" void TestEmptyFunc()
{
}

[DllImport("wrapperlib.so", EntryPoint = "TestEmptyFunc", ExactSpelling = true)]
public static extern void TestEmptyFunc();

I've measured the time it takes to execute this empty function from .NET Core, and it turns out it takes some considerable time - over 300 usec

Before Empty func 18:23:22.320623
After Empty func 18:23:22.320944

is it normal ?

**Comment by karelz** [comment]
Did you warm up the scenario first? (to avoid including JIT time)
Which perf framework did you use?
  - https://github.com/dotnet/BenchmarkDotNet
  - https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/performance-tests.md
  - [MeasureIt](https://blogs.msdn.microsoft.com/vancem/2009/02/06/measureit-update-tool-for-doing-microbenchmarks-for-net/) (probably needs adaptation to .NET Core)

**Comment by AndyAyersMS** [comment]
There are some subtle aspects to measuring pinvoke overhead. See for instance the discussion in dotnet/coreclr#2373. 

I recently made changes in the jit to allow inline pinvoke more broadly. If you have seen performance regress over time I'd be interested in looking more deeply.

**Comment by rottor12** [comment]
ok, so after the weekend I've re-run this code and now the time it takes is about 15-30 us (microsecs)

however, it is still a considerable time if you want to run the same function in a loop

I've tried running the same code on RHEL, and I got the same results:

^Before Empty func 16:43:03.992065
^After Empty func 16:43:03.996325
^Before Empty func 16:43:03.996344
^After Empty func 16:43:03.996356
^Before Empty func 16:43:03.996368
^After Empty func 16:43:03.996382

I'm running this function 3 times to ensure warmup

it takes about 14 us now, still .. it is nowhere near 20ns that @AndyAyersMS mentions

am I doing sth wrong ? or it is what I should expect ?

**Comment by AndyAyersMS** [comment]
@rottor12 For some reason your recent reply is not showing up here. Anyways you say you are still seeing slow times even with warmups. Here's a program I used to test overhead.
```
using System;
using System.Runtime.InteropServices;
using System.Diagnostics;

public class Bench
{
   [DllImport("wrapperlib.so", EntryPoint = "TestEmptyFunc", ExactSpelling = true)]
   public static extern void TestEmptyFunc();

   static int Iterations = 10 * 1000 * 1000;

   public static void Main(string[] args)
   {
      if (args.Length > 0)
      {
           Iterations = Int32.Parse(args[0]);
      }

      Console.WriteLine("Running {0} Iterations", Iterations);

      TestEmptyFunc();

      Stopwatch s = Stopwatch.StartNew();

      for (int i = 0; i < Iterations; i++)
      {
  	TestEmptyFunc();
      }

      Console.WriteLine("TestEmptyFunc: {0} ns/call", 1e6 * ((double) s.ElapsedMilliseconds / Iterations));
   }
}
```
Running this on Ubuntu 14.04 with the .NetCore 1.1 download, I get results like:
```
Running 10000000 Iterations
TestEmptyFunc: 4.1 ns/call
```

**Comment by AndyAyersMS** [comment]
@rottor12 when you get a chance, can you run the sample code above and report your results?

**Comment by rottor12** [comment]
@AndyAyersMS Hi Andy

sorry for not replying earlier

it turns out some kernel modification which I was not aware of was making this problem

on normal Linux all works fine

thanks for your help
