### ISSUE TITLE
Failures in TextWriter and StreamWriter to handle null inputs to WriteLineAsync

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#14563]
If null is passed to `TextWriter.WriteLineAsync(char[])` it will produce no effect. By analogy to the non-async method it should write a newline as if `TextWriter.WriteLineAsync()` had been called.

If null is passed to `StreamWriter.WriteLineAsync(string)` it will throw a `NullReferenceException` or fail an assertion in Debug. Likewise it should behave as if `StreamWriter.WriteLine()` had been called.

**Comment by JonHanna** [comment]
See https://github.com/dotnet/coreclr/issues/8661for an analogous (but not quite identical) issue in coreclr.

**Comment by ianhays** [comment]
I'm somewhat cautious of issues like this. On one hand, the behavior is clearly inconsistent. On the other hand, it's established behavior that has been present for years and has the potential to cause breaks to people upgrading to .net core expecting the current behavior.

In the past I've zealously merged a few minor issues like this and had to undo them later in the name of compat. To avoid having to do that again, we should examine the use cases that are inhibited by the currently inconsistent behavior and determine whether it is worth fixing at the expense of a "breaking change". 

For example, when I google `StreamWriter.WriteLineAsync nullreferenceexception` the first result is this post and the subsequent results are for other issues or unrelated entirely. This suggests to me that this isn't an issue that is commonly hit or commonly unexpected, so I'm more concerned about the compat cost of fixing it.

**Comment by JonHanna** [comment]
Not commonly hit I get, though I'd say it's commonly unexpected in that I think people who've been using these classes synchronously would expect the behaviour this PR brings.

It's also hard to see how someone could have a dependency on the NRE. (A dependency on the no-op on null `char[]` also seems unlikely, but not so much as on the NRE).

**Comment by ianhays** [comment]
>Not commonly hit I get, though I'd say it's commonly unexpected in that I think people who've been using these classes synchronously would expect the behaviour this PR brings.
>It's also hard to see how someone could have a dependency on the NRE. (A dependency on the no-op on null char[] also seems unlikely, but not so much as on the NRE).

Oh I'm sure someone somewhere relies on the current behavior.  The question is whether the number of people expecting your more correct behavior outnumber the number of people inconvenienced by a change to the existing behavior. The former is easily enumerable by a google search, but the latter we'll likely only be able determine after making the change and listening for reactions.

Personally my vote is to fix it because I'm a sucker for consistency between similar APIs, but I'd like more opinions first.

**Comment by JonHanna** [comment]
In terms of the break risk of the fact that this throws NRE and desktop and the coreclr version both throw ANE is an issue in itself. To the extent that someone could depend on the exception they could be depending on the ANE rather than the NRE.

**Comment by ianhays** [comment]
>In terms of the break risk of the fact that this throws NRE and desktop and the coreclr version both throw ANE is an issue in itself. To the extent that someone could depend on the exception they could be depending on the ANE rather than the NRE.

Good point. Lets fix this. The docs say that `If the value is null, only a line terminator is written` and mention nothing about either an ANE or a NRE, so if we don't fix this then we'll have to update the docs.

**Comment by JonHanna** [comment]
The `TextWriter.WriteLineAsync(char[])` case is the trickier. Obviously I'm in favour of the change if I've a PR that does it, but it is more feasible that it would break someone. It's still contrary to the docs, inconsistent with non-async (which is almost a "softly breaking change" so to speak)  and inconsistent in a base where derived classes could perhaps act as per the spec and as such I think it should be fixed, but it's not as easy a call as the ANE/NRE one.

**Comment by ianhays** [comment]
cc: @AlexGhiondea as the discussion in coreclr for TextWriter should have the same resolution as the one in corefx.
