### ISSUE TITLE
Span: Enable back the fast span tests after GC correctness work is complete

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#14574]
Related to PR #14262 where the tests for fast span were disabled because the GC correctness work has not been done for fast span yet.
https://github.com/dotnet/corefx/pull/14262#issuecomment-267164311

Waiting for issue [#5851](https://github.com/dotnet/coreclr/issues/5851) to be resolved, specifically, JIT - Correctness – proper GC reporting of the special byref field, to re-enable the tests for fast span.

**Comment by AlexGhiondea** [comment]
@ahsonkhan is this something you are going to work on?

**Comment by ahsonkhan** [comment]
Currently, no. The work depends on completion of issue #5851, specifically, JIT - Correctness – proper GC reporting of the special byref field.

**Comment by kouvel** [comment]
It doesn't look those tests are disabled currently

**Comment by ahsonkhan** [comment]
The test was enabled back in PR #16093
