### ISSUE TITLE
Add Configurations for reference libraries

### ISSUE THREAD

**Issue by chcosta** [dotnet/corefx#14580]
Some of the reference libraries require configurations (System.Runtime and System.Runtime.Extensions, for example).  Add configurations for those libraries and remove builds files from ref library projects.

**Comment by weshaggard** [comment]
We should add BuildConfigurations for all reference assemblies even if they are just netcoreapp.

**Comment by weshaggard** [comment]
I know we were thinking to not add these but the more I think about this the more I think we will need these in order to correctly handle all the build configurations correctly.

**Comment by weshaggard** [comment]
The ref's now have configurations.
