### ISSUE TITLE
Clean-up all projects of dead properties

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#14584]
Similar to what we did for the test projects we cleaned up a bunch of dead properties (i.e. Configuration, NugetTargetFramework, etc) we should clean-up the rest of the projects under ref and src similarly. We should also clean-up things like TargetingPackReference now which aren't used.

**Comment by weshaggard** [comment]
@joperezr do you still have your little tool that cleaned up the test projects? If so would you mind running it across all the projects?

**Comment by joperezr** [comment]
I think I still have it and if not it's pretty easy to write, so sure, I'll take care of this.

**Comment by karelz** [comment]
Not must have for 2.0

**Comment by weshaggard** [comment]
Closing as these have either been cleaned up already or will be when we move to SDK style projects.
