### ISSUE TITLE
Clean-up binplacing targets

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#14588]
We need to remove binplacing.targets and merge a more complete bin-placing logic somewhere into the build tools targets (perhaps FrameworkTargeting.targets). We will likely need to have a build task to produce the set of directories to binplace to. I've got a start of some of that work at https://github.com/weshaggard/corefx/tree/BinPlacingTask.

**Comment by mellinoe** [comment]
@weshaggard Do you have some concrete ideas for this? I can pick this up if we have specific ideas about how to improve. I know this was filed a while back and a lot has changed since then, so we might not feel that anything needs to be done anymore.

**Comment by weshaggard** [comment]
@ericstj has cleaned up a lot of it over time but I would still like for us to minimally like to delete binplacing.targets and merge it into one of other targets that will go to BuildTools (perhaps FrameworkTargeting.targets). 

@ericstj is there anything else you would like to see cleaned up here?

**Comment by ericstj** [comment]
Targets should be merged in BuildTools but the BinPlaceConfiguration items should live in the consuming repo, along with repo/config-specific settings like IsUAP, IsNetCoreApp, etc.  

I suspect there is a better way to handle ref/lib paths rather than tacking them onto a single item but that's not an essential fix.

**Comment by weshaggard** [comment]
>Targets should be merged in BuildTools but the BinPlaceConfiguration items should live in the consuming repo, along with repo/config-specific settings like IsUAP, IsNetCoreApp, etc.

OK we should have those somewhere else then, likely dir.props.

**Comment by ericstj** [comment]
Yeah, or some dedicated props file.  I don't like how dir.props is a dumping ground.  Seems like we should split it up a bit and put the split props in a subfolder.

**Comment by weshaggard** [comment]
Fair I'd be OK with it being split but I would prefer that we move all but dir.props out of the root directory.

**Comment by karelz** [comment]
Moving to Future per discussion with @mellinoe

**Comment by weshaggard** [comment]
We need to do the build tools split before 2.0 otherwise we will be in a pretty bad place for servicing our 2.0 tools.

**Comment by mellinoe** [comment]
I'll try to tackle the things mentioned above, most likely just the top-priority stuff to get this back into buildtools. Further refactoring could be done once it is cleanly merged back into buildtools.
