### ISSUE TITLE
[dev/eng] CI is not catching all compilation failures

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#14581]
There's two projects that are failing to build on Ubuntu (at least, probably all Linux's although I didn't check), but they aren't getting caught by CI for some reason.

https://ci.dot.net/job/dotnet_corefx/job/dev_eng/job/ubuntu14.04_debug_prtest/144/consoleText

> System/Net/NetworkInformation/UnixIPInterfaceProperties.cs(7,14): error CS0234: The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?) [/mnt/j/workspace/dotnet_corefx/dev_eng/ubuntu14.04_debug_prtest/src/System.Net.NetworkInformation/src/System.Net.NetworkInformation.csproj]
> System/IO/FileSystemWatcher.Linux.cs(860,26): error CS0246: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?) [/mnt/j/workspace/dotnet_corefx/dev_eng/ubuntu14.04_debug_prtest/src/System.IO.FileSystem.Watcher/src/System.IO.FileSystem.Watcher.csproj]

I can fix the compilation errors, but I'm not sure why CI isn't catching this in general.

@weshaggard @chcosta @joperezr

**Comment by chcosta** [comment]
I saw these same failures on OSX, but didn't catch them on Linux.  I'll submit a fix for this.  I'll also look into why failures are not being caught.

**Comment by mellinoe** [comment]
I have a fix actually, so don't worry about that. We should try to figure out why CI doesn't catch it though.

**Comment by mellinoe** [comment]
There were a few PR's related to this, but it's all fixed now.
