### ISSUE TITLE
Add BuildConfigurations for test projects

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#14582]
We need to convert all the test builds files to BuildConfigurations. 

@joperezr please share what you have for @mellinoe

**Comment by joperezr** [comment]
What I have is here: https://github.com/joperezr/corefx/tree/BuildTests

It only created BuildConfigurations manually to those test projects that required it in order for them to build. All of the rest will need to get generated from @chcosta 's tool

**Comment by joperezr** [comment]
This was fixed by #14663

**Comment by weshaggard** [comment]
@joperezr Do we know if the configurations are correct? I suspect we still have more tweaking to do on the configurations, but we can uses other issues to track that.

**Comment by joperezr** [comment]
Agreed, I believe we'll find a bunch of configs that need some tweeks, but I thought the purpose of this issue was more to track the original creation of those props files.
