### ISSUE TITLE
dnx.exe ocassionally hangs on mac during package restore

### ISSUE THREAD

**Issue by mmitche** [dotnet/corefx#1459]
Seeing occasional hangs in dnx.exe when running package restore, specifically on mac.

http://dotnet-ci.cloudapp.net/job/dotnet_corefx_mac_debug/160/console

**Comment by mmitche** [comment]
Sorry, this is on windows building for mac.

**Comment by ericstj** [comment]
@mmitche where can I get logs?  I see console spew but need a log to see where it was hanging.

**Comment by mmitche** [comment]
Is more interesting info printed somewhere (like the msbuild log)?  In this case, dnx.exe just sat there and had be killed while running this command:

""d:\j\workspace\dotnet_corefx_mac_debug\packages/dnx-coreclr-win-x86.1.0.0-beta5-11580\bin\dnu.cmd" restore --packages "d:\j\workspace\dotnet_corefx_mac_debug\packages" "d:\j\workspace\dotnet_corefx_mac_debug\src\Microsoft.CSharp\src/project.json"" exited with code 1.

**Comment by ericstj** [comment]
Yes: msbuild log.  All of the DNX console spew should be in the log.

**Comment by mmitche** [comment]
Okay I modified the job so that msbuild.log always gets pulled off the machine, but last failed run still existed. i'm grabbing the log now and finding a good place to put it.

**Comment by ericstj** [comment]
//cc &@lodejard @pranavkm

**Comment by mmitche** [comment]
I'm told this is fixed in any build after 1.0.0-beta6-12032
