### ISSUE TITLE
Building in VS doesn't affect the startup binary

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#1460]
Either the project is never built or the output directory is different than:
bin\tests\Windows_NT.AnyCPU.Debug\TESTPROJECT\dnxcore50

I also believe it is required to use build first.

This prevents to use "Set us StartUp project" and running easily from VS.

Also if the project is OuterLoop even msbuild /t:BuildAndRun doesn't update the binaries (you need to specifically do /p:RunTestsWithCategories=OuterLoop)

**Comment by nguerrera** [comment]
I am tracking a fix to this with https://github.com/dotnet/buildtools/issues/181

**Comment by stephentoub** [comment]
@nguerrera, what's blocking closing this, just getting an updated buildtools into corefx?

**Comment by nguerrera** [comment]
@stephentoub Correct. That is all that remains.

**Comment by nguerrera** [comment]
cc @JeremyKuhne who is updating the buildtools.

**Comment by JeremyKuhne** [comment]
The new buildtools is published (v57), now just need to consume it. (Change dir.props and the .nuget packages.*.config files)

**Comment by stephentoub** [comment]
Closing now that the latest build tools (v58) have been brought in to corefx.  F5 on test projects works again.  Woo hoo!  Thanks.
