### ISSUE TITLE
Cannot build from clean checkout

### ISSUE THREAD

**Issue by citizenmatt** [dotnet/corefx#1461]
If I perform a clean checkout, and run the `build.cmd` file, I get a ton of errors complaining that `Type or namespace name "Fact" could not be found (are you missing a using directive or an assembly reference?)`.

I've tried building with both the VS2013 and VS2015 command prompts, with the same results. I've followed the steps in the [Developer Guide](https://github.com/dotnet/corefx/wiki/Developer-Guide) but they essentially say - run `build.cmd`.

Is something broken, or is the Developer Guide page not up to date?

**Comment by krwq** [comment]
Do you have the newest VS 2013 updates?

Looks like xunit (and perhaps other) package(s) didn't get restored.

Do you get any warnings in the beginning before you start getting errors?

Could you attach you build log? (or upload it somewhere) You can find it under: <Your repo path>\msbuild.log

I'm currently building after cleaning nuget cache and it works fine here. It looks like it might be some unusual configuration on your machine.

**Comment by citizenmatt** [comment]
Yeah, I'm all up to date with VS2013 (apart from some Azure stuff). I've [uploaded msbuild.log here](http://1drv.ms/1K36WlK).

Just before seeing errors, I get this warning:

    Unable to resolve the assets of xunit.core.netcore: Couldn't find a matching group

**Comment by krwq** [comment]
I don't seem to be able to access the log, one drive is loading indefinitely

**Comment by krwq** [comment]
I believe this might be related to your problem: https://github.com/dotnet/corefx/pull/1416

**Comment by citizenmatt** [comment]
Oops. Perhaps I closed the laptop before it finished uploading. I've taken a look at that issue, and can't see anything that's helpful. I'm at a bit of a loss to know how to start investigating this - it looks like the failing test .csproj files are referencing packages.config, but nothing else - there are no references to any of the packages that they're supposed to be referencing. Is that right?

**Comment by citizenmatt** [comment]
Ah, found it. It's an issue with the build tools not working when Xamarin is installed. See #449.
