### ISSUE TITLE
Microsoft.DiaSymReader.Native folder ends up in project using new CSPROJ after upgrading to Microsoft.NETCore.App/1.1.0

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/corefx#14627]
See dotnet/roslyn#15859

This will need to be included in 1.1.1 such that Microsoft.NETCore.App brings in the updated Microsoft.DiaSymReader.Native once it's fixed.

**Comment by DamianEdwards** [comment]
@terrajobst Can you make sure this ends up wherever it has to get this resolved for 1.1.1 please?

**Comment by karelz** [comment]
@ericstj @mellinoe any guess who should take first look?

**Comment by gkhanna79** [comment]
@tmat Should update https://github.com/dotnet/core-setup/blob/release/1.1.0/pkg/projects/Microsoft.NETCore.App/project.json#L42 to reference the intended version of the package.

**Comment by karelz** [comment]
@tmat are you the right person to do that?

**Comment by DamianEdwards** [comment]
This increases the size of published ASP.NET Core apps by over 2 MBs with the CSPROJ-based tooling.

**Comment by karelz** [comment]
@tmat ping ... this is blocking ASP.NET team.

**Comment by tmat** [comment]
Do we need a release version of Microsoft.DiaSymReader.Native package? When is it needed? 1.5.0 won't be available until after Dev15 RTM build is done. I can create 1.4.1 with the fixed .props file, if needed. 
BTW, I do not own code in the dotnet/core-setup repo, so I'm not sure why does it need to be me who updates the version number.

**Comment by gkhanna79** [comment]
> I do not own code in the dotnet/core-setup repo, so I'm not sure why does it need to be me who updates the version number

Various folks own components in that repo - and the own versions referenced in Microsoft.NEtCore.App as well. Please go ahead and submit a PR for this and send a note to shiproom since this is going to be in 1.1.x servicing release.

CC @leecow

**Comment by weshaggard** [comment]
This was done with https://github.com/dotnet/core-setup/pull/1424.
