### ISSUE TITLE
Ensure that the Reflection tests don't rely on magic numbers to get bad token ids.

### ISSUE THREAD

**Issue by AlexGhiondea** [dotnet/corefx#14625]
In our tests we are relying on the fact that a given token number, when 1000 is added to it, it becomes an invalid token

https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/Reflection/ModuleTests.cs#L186

That is a fragile logic as we can see in https://github.com/dotnet/corefx/pull/14431.

**Comment by karelz** [comment]
It caused enough troubles that we should try to fix it in 2.0 to avoid similar troubles in future.

**Comment by karelz** [comment]
@AlexGhiondea what is the solution? Bump it to 10K? Or did you have something more sophisticated in mind?

**Comment by alexperovich** [comment]
@karelz I think the right solution here is just to remove the case. We already have 2 invalid tokens.
