### ISSUE TITLE
How to build wiki page should provide workaround for Xamarin

### ISSUE THREAD

**Issue by citizenmatt** [dotnet/corefx#1465]
The [Developer Guide wiki page](https://github.com/dotnet/corefx/wiki/Developer-Guide) should mention #449, which prevents a clean checkout from building when Xamarin is installed. It should also mention the workaround, which is to delete, move or rename the `Xamarin.*.xml` files from the `SupportedFolders` folder in `%ProgramFiles%\ReferenceAssemblies\.NetPortable`.

**Comment by ellismg** [comment]
I added another item in the notes section and linked to your workaround.  Thanks!
