### ISSUE TITLE
[dev/eng] ref projects are not really building in parallel on Unix

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#14671]
I'm not sure what's causing this, but it looks like the ref projects are effectively being built sequentially outside of Windows. This is causing the build to take a very long time compared to Windows. My 8-core Ubuntu machine has only one core being utilized during the ref build, even though there are tons of MSBuild processes active. It looks like the src build is handling this a bit better (faster and more CPU utilization), but I'm not sure it's as good as Windows there either. It still seems slower to me.

Is this a problem with MSBuild?

@weshaggard @ericstj @chcosta @joperezr @karajas

**Comment by mellinoe** [comment]
Running the build again on my 8-core Ubuntu machine, I think the src build is fine. `htop` shows CPU utilization of ~1.1 during the ref build and ~16 during the src build, and the src build is clearly producing assemblies in parallel.

**Comment by ericstj** [comment]
Perhaps it is due to ProjectReferences?  You can check the diag output of the msbuild task invocation from the ref.builds to see if it is trying to build it in parallel.  You can also run msbuild /m ref.builds on it outside of the full build to see if anything is different.  If both show the same serialization and that is not present on Windows then its likely an msbuild issue.

**Comment by joperezr** [comment]
@mellinoe did you figure out why was this happening? If the problem is ProjectReferences as @ericstj suggests, then I would imagine this should repro in Windows, right?

**Comment by mellinoe** [comment]
I haven't figured out why this is happening. Trying .NET Core MSBuild on Windows should give some hints, maybe.

**Comment by mellinoe** [comment]
based on a /ds log, they are building in parallel just fine. There are still some performance differences which are more-or-less understood at this point. We've tackled some of them and there are more to be tackled still.
