### ISSUE TITLE
SqlException: A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 35 - An internal exception was caught)

### ISSUE THREAD

**Issue by leshin** [dotnet/corefx#14680]
Platform : Linux Centos
Runtime : docker from microsoft/aspnetcore:1.1.0
System.Data.SqlClient, Version=4.1.0.0
DefaultConnection: "Data Source=xxx;Initial Catalog=Account;Persist Security Info=True;User ID=sa;Password=xxx"

__But not appear on Windows__

TestSql1 is ok.
```c#
        public async Task<IActionResult> TestSql1([FromServices]DbContextOptions<ApplicationDbContext> options)
        {
            using (var con = new SqlConnection(options.FindExtension<Microsoft.EntityFrameworkCore.Infrastructure.Internal.SqlServerOptionsExtension>().ConnectionString))
            {
                await con.OpenAsync();
                using (var cmd = new SqlCommand())
                {
                    cmd.CommandText = "select * from PhoneCodes;";
                    cmd.Connection = con;
                    using (var reader = await cmd.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            _logger.LogInformation(reader[0].ToString() + "\t");
                        }
                    }
                }
            }
            return Content("ok");
        }
```

TestSql2 is failed
```c#
        public async Task<IActionResult> TestSql2([FromServices]DbContextOptions<ApplicationDbContext> options)
        {
            using (var con = new SqlConnection(options.FindExtension<Microsoft.EntityFrameworkCore.Infrastructure.Internal.SqlServerOptionsExtension>().ConnectionString))
            {
                await con.OpenAsync();
                using (var cmd = new SqlCommand())
                {
                    var userNameOrEmailOrPhoneNumber = "deviceone";
                    cmd.CommandText = "SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[ConcurrencyStamp], [u].[Email], [u].[EmailConfirmed], [u].[HeadUrl], [u].[LastActiveIP], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PerfectedAccountInfo], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[Prefix], [u].[PromoteCode], [u].[RegisterIP], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[Type], [u].[TypeAuthenticated], [u].[UserName] FROM [AspNetUsers] AS [u] WHERE (([u].[UserName] = '" + userNameOrEmailOrPhoneNumber + "') OR ([u].[Email] = '" + userNameOrEmailOrPhoneNumber + "')) OR ([u].[PhoneNumber] = '" + userNameOrEmailOrPhoneNumber + "')";
                    cmd.Connection = con;
                    using (var reader = await cmd.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            _logger.LogInformation(reader[0].ToString() + "\t");
                        }
                    }
                }
            }
            return Content("ok");
        }
```

deviceone.account.web_1  |       Executing action method DeviceOne.Account.Web.Controllers.HomeController.TestSql2 (DeviceOne.Account.Web) with arguments (Microsoft.EntityFrameworkCore.DbContextOptions`1[DeviceOne.Account.Web.Data.ApplicationDbContext]) - ModelState is Valid
deviceone.account.web_1  | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
deviceone.account.web_1  |       Request finished in 20151.2156ms 500 text/html; charset=utf-8
deviceone.account.web_1  | info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
deviceone.account.web_1  |       Executed action DeviceOne.Account.Web.Controllers.HomeController.TestSql2 (DeviceOne.Account.Web) in 18978.5508ms
deviceone.account.web_1  | fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
deviceone.account.web_1  |       An unhandled exception has occurred while executing the request
deviceone.account.web_1  | System.Data.SqlClient.SqlException: A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
deviceone.account.web_1  |    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
deviceone.account.web_1  |    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
deviceone.account.web_1  |    --- End of inner exception stack trace ---
deviceone.account.web_1  |    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
deviceone.account.web_1  |    at System.Net.Sockets.NetworkStream.<>c.<ReadAsync>b__58_1(IAsyncResult iar)
deviceone.account.web_1  |    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
deviceone.account.web_1  |    --- End of inner exception stack trace ---
deviceone.account.web_1  |    at System.Data.SqlClient.SqlCommand.EndExecuteReader(IAsyncResult asyncResult)
deviceone.account.web_1  |    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
deviceone.account.web_1  |    at DeviceOne.Account.Web.Controllers.HomeController.<TestSql2>d__8.MoveNext() in /root/Account/src/DeviceOne.Account.Web/Controllers/HomeController.cs:line 84
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
deviceone.account.web_1  |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
deviceone.account.web_1  |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
deviceone.account.web_1  |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
deviceone.account.web_1  |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
deviceone.account.web_1  |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
deviceone.account.web_1  |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
deviceone.account.web_1  |    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
deviceone.account.web_1  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
deviceone.account.web_1  |    at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationMiddleware.<Invoke>d__6.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
deviceone.account.web_1  |    at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
deviceone.account.web_1  |    at IdentityServer4.Hosting.FederatedSignOutMiddleware.<Invoke>d__6.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
deviceone.account.web_1  |    at IdentityServer4.Hosting.AuthenticationMiddleware.<Invoke>d__2.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
deviceone.account.web_1  |    at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
deviceone.account.web_1  |    at IdentityServer4.Hosting.BaseUrlMiddleware.<Invoke>d__2.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
deviceone.account.web_1  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
deviceone.account.web_1  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
deviceone.account.web_1  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
deviceone.account.web_1  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
deviceone.account.web_1  |    at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
deviceone.account.web_1  |    at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__5.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
deviceone.account.web_1  |    at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
deviceone.account.web_1  | --- End of stack trace from previous location where exception was thrown ---
deviceone.account.web_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
deviceone.account.web_1  |    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
deviceone.account.web_1  |    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
deviceone.account.web_1  | ClientConnectionId:72c97f70-9df8-4533-8d2b-9987a0e53675

**Comment by saurabh500** [comment]
@leshin  Is this intermittent or consistent? It seems like the TCP handshake itself didn't go through.

**Comment by saurabh500** [comment]
Can you try to see if the TCP connection to the sql server port works from Docker? 
e.g. 
`netcat -v -z <IPAddressOfSqlServer> <port number> `

**Comment by leshin** [comment]
@saurabh500 It's consistent. But TestSql1 is successful.

**Comment by leshin** [comment]
It's ok on Ubuntu.

**Comment by arthurvaverko** [comment]
Im running on the default port 1433.
when I execute a simple query against the DB all works well.
but when I try to run a stored procedure .. like this:

``` c#
    DataTable result = null;
    
    SqlCommand command = new SqlCommand();
    command.CommandType = System.Data.CommandType.StoredProcedure;
    command.CommandText = procedureNameWithDbVersionPrefix;
    command.CommandTimeout = m_nTimeout;
    foreach (string item in m_Parameters.Keys)
    {
        command.Parameters.Add(new SqlParameter(item, m_Parameters[item]));
    }
    string sConn = GetConnectionString();
    using (SqlConnection con = new SqlConnection(sConn))
    {
        try
        {
            con.Open();
            command.Connection = con;
    
            SqlQueryInfo queryInfo = Utils.GetSqlDataMonitor(command);
            using (KMonitor km = new KMonitor(KLogMonitor.Events.eEvent.EVENT_DATABASE, null, null, null, null) { Database = queryInfo.Database, QueryType = queryInfo.QueryType, Table = queryInfo.Table, IsWritable = (m_bIsWritable || Utils.UseWritable).ToString() })
            {
                using (SqlDataReader reader = command.ExecuteReader())
                {
                    if (reader.HasRows)
                    {
                        result = new DataTable();
                        result.Load(reader);
                    }
                }
            }
    
            con.Close();
        }
        catch (Exception ex)
        {
            string sMes = "While running : '" + procedureNameWithDbVersionPrefix + "'\r\n Exception occurred: " + ex.Message;
            log.Error(sMes, ex);
            return null;
        }
    }
```

I'm getting this exception only on Linux system. running on windows all works well..
actually event running inside a Linux based docker on windows all works well .. :\

```
    ERROR 2019-04-23 06:49:53,933 (33) class:ODBCWrapper.StoredProcedure topic:null method:UpdateBulkUpload server:c931619e64e0 ip:null reqid:35a07e86-933a-4f0c-93ec-3428e4d92687 partner:203 action:null uid:770357 msg:While running : '__522v0__UpdateBulkUpload'
     Exception occurred: A transport-level error has occurred when sending the request to the server. (provider: TCP Provider, error: 35 - An internal exception was caught)
    System.Data.SqlClient.SqlException (0x80131904): A transport-level error has occurred when sending the request to the server. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.IO.IOException: Unable to write data to the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
       at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
       --- End of inner exception stack trace ---
       at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
       at System.Data.SqlClient.SNI.SNITCPHandle.Send(SNIPacket packet)
       at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
       at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
       at System.Data.SqlClient.TdsParserStateObject.SNIWritePacket(Object packet, UInt32& sniError, Boolean canAccumulate, Boolean callerHasConnectionLock)
       at System.Data.SqlClient.TdsParserStateObject.WriteSni(Boolean canAccumulate)
       at System.Data.SqlClient.TdsParserStateObject.WritePacket(Byte flushMode, Boolean canAccumulate)
       at System.Data.SqlClient.TdsParserStateObject.ExecuteFlush()
       at System.Data.SqlClient.TdsParser.TdsExecuteRPC(_SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
       at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
       at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
       at System.Data.SqlClient.SqlCommand.ExecuteReader()
       at ODBCWrapper.StoredProcedure.Execute(Boolean shouldGoToSlave) in /src/Core/ODBCWrapper/StoredProcedure.cs:line 130
```
