### ISSUE TITLE
can't join Multicast group on Linux - no IGMP ADD_MEMBERSHIP report visible in Wireshark

### ISSUE THREAD

**Issue by rottor12** [dotnet/corefx#14684]
I'm having trouble joining mcast group on Linux

I'm using the following code:

```
Socket sock = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
sock.Bind(new IPEndPoint("<LOCAL_NIC_IP>", MulticastGroupPort));
sock.SetSocketOption(SocketOptionLevel.IP, SocketOptionName.AddMembership, new MulticastOption(IPAddress.Parse("<MULTICAST_GROUP_IP>")));

```

but I can't see any ADD_MEMBERSHIP report in WireShark
and of course I'm not receiving any data

I've tried various combinations of above, but with no success

is it possible to receive data from multicast group without using UdpClient ?

**Comment by rottor12** [comment]
cc: @stephentoub @ericeil

**Comment by Priya91** [comment]
@rottor12 Can you check if firewall is not blocking the MulticastGroupPort? Is this reproing still?

**Comment by karelz** [comment]
No answer, closing
