### ISSUE TITLE
Consider adding .editorconfig

### ISSUE THREAD

**Issue by tintoy** [dotnet/corefx#14700]
Hi.

I'm in the process of getting my first PR approved, and although I have read the contribution / code-style guidelines I was nevertheless occasionally tripped up by my default editor settings (e.g. tabs vs spaces).

It might be useful to add a [.editorconfig](http://editorconfig.org/) to the repository that specifies the project's formatting style. Most editors and IDEs either already respect this file or have a plugin available that respects it. I believe VS.Next has native support for it.

**Comment by am11** [comment]
It's already present at repo's root: https://github.com/dotnet/corefx/blob/master/.editorconfig

**Comment by tintoy** [comment]
Ok, now I feel very stupid. I was sure I'd gone looking for it but now I've looked again and there it is.

Never mind, carry on :)
