### ISSUE TITLE
Allow KeyedCollection Derived Class to Provide Different Implementation of IDictionary

### ISSUE THREAD

**Issue by rvhuang** [dotnet/corefx#14708]
Title says it all. Since [Dictionary](https://msdn.microsoft.com/en-us/library/ms132468.aspx) property only specifies the interface [IDictionary(TKey, TValue)](https://msdn.microsoft.com/en-us/library/s4ys34ea.aspx) instead of actual class, it could be good if derived class is allowed to provide its own dictionary implementation by overriding a method.

**Comment by karelz** [comment]
We need formal API proposal (incl. motivation, usage examples and overall value - how many real-world projects would use it and why)

**Comment by safern** [comment]
Since we didn't get any response on this one and/or an API proposal we are going to go ahead and close it. If someone wants to bring it up, just comment and we can reopen.
