### ISSUE TITLE
CoreFX way to get the NetBIOS Machine Name?

### ISSUE THREAD

**Issue by GuardRex** [dotnet/corefx#1471]
Not available/working:
```
Environment.MachineName
System.Net.Dns.GetHostName()
System.Windows.Forms.SystemInformation.ComputerName
System.Environment.GetEnvironmentVariable("COMPUTERNAME")
```
How can I get the machine name?

**Comment by GuardRex** [comment]
Nevermind ...
```
System.Environment.GetEnvironmentVariable("COMPUTERNAME")
```
Works! I had a configuration issue that prevented my getting the computer name.

**Comment by akoeplinger** [comment]
Just as a note: this is a Windows-specific environment variable and won't work cross-platform.
