### ISSUE TITLE
ServiceDescriptor can through attributes registration?

### ISSUE THREAD

**Issue by maxzhang1985** [dotnet/corefx#14721]
such as ` [ServiceDescriptor(typeof(IUser),ServiceLifetime.Transient)]`

**Comment by karelz** [comment]
Are you asking if it is possible today? Or proposing a new API?

[ServiceDescription](https://apisof.net/catalog/System.ServiceModel.Description.ServiceDescription) is not part of .NET Core -- for full .NET Framework issues, please use different feedback channels: https://github.com/dotnet/corefx#how-to-engage-contribute-and-provide-feedback
