### ISSUE TITLE
Need the instruction about how to integrate corefx changes with my application.

### ISSUE THREAD

**Issue by tloo** [dotnet/corefx#14735]
I have made some changes in corefx and build it.
Now I have another .Net Core application which wants to use the changes I made in corefx.
How to achieve that? Need some instructions. Thanks a lot!

**Comment by ViktorHofer** [comment]
Documented in https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md#more-advanced-scenario---using-your-local-corefx-build
