### ISSUE TITLE
Don't handle exceptions when raising Unloading and ProcessExit events

### ISSUE THREAD

**Issue by kouvel** [dotnet/corefx#14747]
The desktop behavior is to catch exceptions from each callback invocation and have the `UnhandledException` event be raised for each exception. Regardless of exceptions, all callbacks are still invoked.

The desired behavior is that exceptions are not caught. `AppDomain.ProcessExit` and `AssemblyLoadContext.Unloading` are typically raised from the finalizer thread, so an unhandled exception from any handler is expected to crash the process.

**Comment by kouvel** [comment]
@cakine

**Comment by kouvel** [comment]
Upon further discussion, we decided it would make sense for exceptions during these events to propagate and be treated like any other unhandled exception.

**Comment by stephentoub** [comment]
@kouvel, it's not clear to me from the comments: can this be closed, or if not, what's the current behavior and what's the desired behavior?

**Comment by kouvel** [comment]
I have updated the title and description inline to reflect the current desired behavior.

**Comment by stephentoub** [comment]
Thanks
