### ISSUE TITLE
CoreFX Primer

### ISSUE THREAD

**Issue by richlander** [dotnet/corefx#1474]
I'm writing a [.NET Primer](https://github.com/dotnet/coreclr/pull/725) in the CoreCLR repo that has a strong bias to the runtime features. I'd like to start one that has a strong bias to the framework libraries. It makes sense for it to live in this repo. Naturally, there would be cross-linking between the two.
- Good idea?
- What should this primer be called?

I don't want to call one ".NET Core Runtime Primer" and then other ".NET Core Framework Primer". The primer I'm working on right now is the primer for the fundamentals of .NET generally, in an ECMA 335 sense. It's intended to be equally meaningful for Mono. The CoreFX Primer, on the other hand, would be specific to this implementation, so we could reasonable call it the ".NET Core Framework Primer".

/cc @Petermarcu 

FYI: This topic would move the corefx primer: https://github.com/dotnet/coreclr/blob/dotnet-primer/Documentation/framework-libraries.md.

**Comment by Petermarcu** [comment]
Great Idea!
"Book of the Framework"?

**Comment by richlander** [comment]
A definite option. It's a question of whether it should mimic the "Book of the Runtime", which focusses on how the develop the runtime, or ".NET Primer", which focusses on what the features are for and how to use them. Both are good ideas, but we should avoid mixing them together. Thoughts?

**Comment by shahid-pk** [comment]
:+1:  for  ".NET Core Framework Primer" 
I think it should live in this repository because most people would prefer docs in one place.

**Comment by richlander** [comment]
I like ".NET Core Framework Primer". That's what I'm going to start with.
