### ISSUE TITLE
RequiredAttribute ErrorMessage and DefaultErrorMessage null by default

### ISSUE THREAD

**Issue by vladimirlapacek** [dotnet/corefx#14748]
The `ErrorMessage` and `DefaultErrorMessage` properties are used by `ValidationAttributeAdapter<TAttribute>.GetErrorMessage` to obtain the localized error message. As the properties are null by default, another mechanism is used and the localization works inconsistently. `EmailAddressAttribute`, on the other hand, has the `DefaultErrorMessage` property set by default. Please make `RequiredAttribute` have the `DefaultErrorMessage` set as well.

**Comment by ajcvickers** [comment]
Some attributes have a default error message, some do not. This is by-design--there are attributes for which there is no reasonable default. While it can be argued that RequiredAttribute could have a default error message, doing so would be a breaking change for applications that depend on it being null in any conditional. Also, unless we made every data annotation have a default error message (which is by-design not the case), making RequiredAttribute have it does not get any closer to treating every data annotation in the same way. Therefore, we don't think that this is a change we would make or take a PR for.
