### ISSUE TITLE
Passing dynamic arg to indexer property of a generic type implementing a derived interface throws

### ISSUE THREAD

**Issue by Eilon** [dotnet/corefx#14752]
Yes, that's a mouthful, but it's the simplest way I've been able to reproduce this! There seems to be a limitation (bug?) in RuntimeBinder when it tries to call an indexed property on an interface through a "derived" interface. It appears that the RuntimeBinder doesn't see the indexed property of the "base" interface and throws an exception:

```
Unhandled Exception: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot apply indexing with [] to an expression of type 'ConsoleApplication1.IFakeStringLocalizer2'
 at CallSite.Target(Closure, CallSite, IFakeStringLocalizer2, Object)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0, T1, TRet](CallSite site, T0 arg0, T1 arg1)
 at ConsoleApplication1.Program.Main(String[] args) in Program.cs:line 17
```

Long story short, here's the simplest code I've been able to make that reproduces the problem. It's very subtle and I've made a note wherever there are critical parts of the code.

```c#
namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            // The *declared* type of this variable is IMPORTANT. Change it to the concrete type and it works
            IFakeStringLocalizer2 s = new FakeStringLocalizer<int>();

            dynamic d = new object();

            // This next line of code throws at runtime:
            //Unhandled Exception: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot apply indexing with [] to an expression of type 'ConsoleApplication1.IFakeStringLocalizer2'
            // at CallSite.Target(Closure, CallSite, IFakeStringLocalizer2, Object)
            // at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0, T1, TRet](CallSite site, T0 arg0, T1 arg1)
            // at ConsoleApplication1.Program.Main(String[] args) in Program.cs:line 17
            var x = s[d];
        }
    }

    // The generic type here DOES seem to matter.
    public class FakeStringLocalizer<T> : IFakeStringLocalizer2
    {
        public int this[int b] { get { return -1; } }
    }

    // This extra interface DOES seem to matter.
    public interface IFakeStringLocalizer2 : IFakeStringLocalizer
    {
    }

    public interface IFakeStringLocalizer
    {
        // Return type and indexer arg type don't matter here
        int this[int b] { get; }
    }
}
```

Originally filed here: https://github.com/aspnet/Localization/issues/308

**Comment by JonHanna** [comment]
The example given here should still fail with the same exception type, though probably a different message, as `dynamic d = new object();` means it's not of a type that could be used in that call, even if static.

The bug still happens with `dynamic d = 3;` though.

**Comment by VSadov** [comment]
Is this behavior different between .NET and Core FX?

**Comment by JonHanna** [comment]
No, can reproduce on desktop too

**Comment by JonHanna** [comment]
> `// The generic type here DOES seem to matter.`

Try again and you'll see it doesn't.

The problem is that in searching for methods and for types there is one place where the code expects `GetMembers` to include inherited non-overridden members, which it doesn't for interfaces, and two places that expects walking `BaseType` to expose the whole inheritance chain, which again it doesn't for interfaces.

**Comment by Eilon** [comment]
@JonHanna you are some kind of genius!

**Comment by JonHanna** [comment]
@Eilon "Given enough eyeballs, all bugs are shallow." If I was really that much of a genius I would have found it in April ;)

**Comment by JonHanna** [comment]
Maybe this should be considered for porting. https://stackoverflow.com/q/51240596/400547 is someone hitting the same bug against netfx.
