### ISSUE TITLE
Regex constructor throws NullReferenceException and OutOfMemoryException

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/corefx#1476]
Following line of code throws NullReferenceException:
Regex regex = new Regex("(?(?i))");

And following line of code throws OutOfMemoryException:
Regex regex = new Regex(" (?(?i))");

Both patterns are if constructs where expression "?i" contains quantifier following nothing. 
There seems to a problem with "i" letter or any other letter that is an inline character for a particular option (i, m, n, s, x). 
If you change "i" with "a" (not an inline character), ArgumentException is thrown as expected.

Both patterns are invalid so according to the .NET documentation, both lines should throw ArgumentException.
This behaviour is especially unpleasant in case of "regex tester" application (such as http://regexator.net) which tries to continually evaluate user input as regex pattern.

This behaviour has been tested in .NET 4.0, 4.5 and 4.6, all with the same results.

**Comment by joshfree** [comment]
It looks like the parser is letting this sneak through https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexParser.cs#L682-L687
