### ISSUE TITLE
DbConnection.Dispose() stopped calling DbConnection.Close() in DataSet commit

### ISSUE THREAD

**Issue by divega** [dotnet/corefx#14760]
The behavior changed in https://github.com/dotnet/corefx/commit/7888677b3c53596085c2fa53860d9a0519eeecfd#diff-d7bff8835e6985ab9107a59a282e1a60L153 which made `DbConnection` inherit the `Dispose()` implementation from `Component`. It triggered a failure in an EF Core test (see https://github.com/aspnet/EntityFramework/pull/7323).

I am creating this issue so that the SqlClient team has a chance to figure out if this change is intentional.

**Comment by divega** [comment]
Trying to figure out how things were supposed to work, I found that in the reference code at https://github.com/Microsoft/referencesource/blob/master/System.Data/System/Data/ProviderBase/DbConnectionHelper.cs#L202 `Dispose()` calls `Close()` if `disposing == true`, but DbConnectionHelper.cs seems to be just template code and the actual connection classes such as `SqlConnection` don't do this, or at least I couldn't figure out how this happens by just reading the code.

BTW there is also a private `DiposeMe()` method in `SqlConnection` (both in the reference code and in the .NET Core versions) that seems at first glance seem to be dead code.

**Comment by danmosemsft** [comment]
@saurabh500 @stephentoub (since change above mentioned)

**Comment by saurabh500** [comment]
In the code at 
https://github.com/Microsoft/referencesource/blob/master/System.Data/System/Data/ProviderBase/DbConnectionHelper.cs#L202
the namespace and Class names are transformed during build time of NetFx to give them appropriate names based on the provider they are compiled for. 
This above may need to incorporated in the SqlClient code in .Net Core.

**Comment by saurabh500** [comment]
@stephentoub @terrajobst 
In .Net Core 1.0 and 1.1 the `DbConnection.Dispose()` calls `DbConnection.Close()` in the base implementation. 
However with the merge of the ADO.Net base classes, there is a change in the way the default implementation of `Dispose()` in `DbConnection` behaves. The `Dispose()` in `DbConnection` comes from Component which doesn't call `DbConnection.Close() `

This causes backward incompatibility between the consumers operating on .Net Core 1.1 and .Net Core 2.0 and is a breaking change.

What is the expected guideline in this case? Stick to NetFx behavior or to make sure that there is no breaking changes between .Net Core 1.1 and .Net Core 2.0 ? 

In this case I think its important to make sure that the behavior between .Net Core versions do not break and the `Dispose()` method from the .Net Core 1.1 should be provided by overriding the `Dispose` from `Component` in `DbConnection`

**Comment by stephentoub** [comment]
@weshaggard, have we encountered this case before, and if so, what did we decide?  Essentially for .NET Core 2.0, we can choose to either be compatible with .NET Core 1.x or with .NET Framework.

**Comment by weshaggard** [comment]
We haven't really hit this yet. However I would error on the side of being compatible with .NET Framework over .NET Core 1.0/1.1.

**Comment by danmosemsft** [comment]
I agree, but consider using AppContext to offer a way to go back to the 1.1 behavior.

**Comment by divega** [comment]
@saurabh500 I am still a bit surprised to hear that disposing the connection on .NET Framework did not close it. Is it the case that this was not implemented in the base `DbConnection` but it had to be implemented in each derived/provider specific implementation?

**Comment by saurabh500** [comment]
@divega 
>> Is it the case that this was not implemented in the base DbConnection but it had to be implemented in each derived/provider specific implementation?

Yes. 

In .Net Core Dispose() started calling Close(). The Dispose from SqlClient was removed to benefit from the behavior of the base class. 
That's why you see the difference you have mentioned in https://github.com/dotnet/corefx/issues/14760#issuecomment-269575962

**Comment by divega** [comment]
@bricelam do you consider this a duplicate of https://github.com/dotnet/corefx/issues/2249 or are they different?

**Comment by divega** [comment]
@saurabh500 from our discussion yesterday, I believe the behavior is correct and this can closed.

**Comment by danmosemsft** [comment]
@saurabh500 can we close this?

**Comment by saurabh500** [comment]
@danmosemsft @divega Yes we can close this.
