### ISSUE TITLE
OS signal support

### ISSUE THREAD

**Issue by lfarnell** [dotnet/corefx#14799]
With the recent explosion of running applications inside containers, it seems like .NET should have support for trapping OS signals sent to applications running on Linux, macOS and Windows.

Docker for instance sends a SIGTERM to an application before sending SIGKILL to kill the container. Trapping these signals so we can gracefully shutdown containers and other applications would be nice.

**Comment by stephentoub** [comment]
> Docker for instance sends a SIGTERM to an application before sending SIGKILL to kill the container. 

SIGTERM is supposed to cause the AssemblyLoadContext.Unloading event to be raised for exactly this reason.  Apparently it's not happening, though: https://github.com/dotnet/coreclr/issues/7394

**Comment by lfarnell** [comment]
@terrajobst @stephentoub Based on https://github.com/dotnet/coreclr/issues/7394, should this issue be closed as a duplicate?

**Comment by stephentoub** [comment]
Thanks, @lfarnell. Sure, let's close this one in favor of that.

**Comment by donatasm** [comment]
Up until that any work arounds on this? I mean graceful shutdown for at least inside docker container for a dotnet core app.
