### ISSUE TITLE
Request: Adding DebuggerDisplay/DebuggerTypeProxy to Grouping and Lookup

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#14790]
The current experience when seeing an `IGrouping<TKey, TElement>` returned from Linq in debug view is not the best:

![groupingdebug](https://cloud.githubusercontent.com/assets/9159214/21580324/1b843c60-cfbb-11e6-879f-b3ade4f1c384.PNG)

Maybe we should add `DebuggerTypeProxy` / `DebuggerDisplay` attributes to `Grouping` so that it's easier to navigate in debug? This is a semi-API proposal since it'll be seen by end-users, so I'll spell out the display format/property names I'm thinking of:

```cs
[DebuggerDisplay("Key = {Key}")]
[DebuggerTypeProxy(typeof(GroupingDebuggerProxy<,>))]
public class Grouping<TKey, TElement> : IGrouping<TKey, TElement>, IList<TElement> { ... }

internal sealed class GroupingDebuggerProxy<TKey, TElement>
{
    public TKey Key { get; }

    // The name of this property needs to alphabetically follow "Key" so it
    // shows up last when the Grouping is expanded.
    // It also doesn't matter because users will never see it, as it's RootHidden.
    [DebuggerBrowsable(DebuggerBrowsableState.RootHidden)]
    public TElement[] Z { get; }
}
```

cc @JonHanna @VSadov

**Comment by JonHanna** [comment]
Not sure how much of an API issue this would be considered, but this seems sensible and useful.

**Comment by jamesqo** [comment]
@JonHanna I also think we could do this for `Lookup<,>` too. Neither `Grouping` nor `Lookup` are lazily loaded, so there should be no risk of the debugger mutating state when it enumerates them.
