### ISSUE TITLE
Investigate caching single-element ImmutableArrays

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#14802]
Since ImmutableArrays are immutable, we can cache them without any fear of the end-user modifying the array. We should investigate doing this for `ImmutableArray.Create(T)` for common inputs.

If this is done, here are some things to keep in mind:

- Which inputs are common
  - Java caches boxed integers from -128 to 127
  - Should we cache one-element `null` arrays for reference types?
- How much overhead this will have for code that doesn't benefit
- Whether we should do this for other methods on `ImmutableArray`
  - e.g. `Remove` when our length is 2, `Replace` when our length is 1, etc.

**Comment by stephentoub** [comment]
What drove you to open this issue? Do you have an example from Roslyn where this would make a meaningful difference?

**Comment by jamesqo** [comment]
@stephentoub I added "Investigate" to the title because I wasn't 100% sure this is something I planned to do (I saw earlier you had done something similar with https://github.com/dotnet/corefx/issues/12037). I have not done any investigation yet, but I opened this because `Create(T)` is a common way to create an ImmutableArray. I'll close this and open a PR if/when I find this makes a signficant impact.

**Comment by stephentoub** [comment]
Thanks. In the case of that linked issue, I know there are improvements to be made that will have a meaningful impact, having seen the relevant costs in traces of real usage. The question there is more about feasibility of implementation and investigating how best to do it.

**Comment by jamesqo** [comment]
@stephentoub Thanks for clarifying.
