### ISSUE TITLE
TypeCode internal

### ISSUE THREAD

**Issue by Mpdreamz** [dotnet/corefx#1480]
TypeCode is now internal

https://github.com/dotnet/corefx/blob/ac3094710bc8a90acca4e7f1285c2447b85ac5d3/src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/TypeCode.cs#L6

where as it wasn't before:

https://msdn.microsoft.com/en-us/library/system.typecode%28v=vs.110%29.aspx

Any chance of making this public again?

**Comment by svick** [comment]
Could you explain why do you want to make it public?

**Comment by weshaggard** [comment]
While there does appear to be an internal TypeCode (cc @khdang something to look at) we have actually exposed TypeCode publicly already in our latest version of System.Runtime. We decided to expose it along with ICovertible and various Convert overloads that use it. 

@Mpdreamz what are you using that you don't see it it available?

**Comment by weshaggard** [comment]
Given that this is already public I'm closing this issue.@mpdreamz if you have further questions please feel free to add them to the issue.
