### ISSUE TITLE
ConcurrentDictionary: add ContainsValue()

### ISSUE THREAD

**Issue by tkrotoff** [dotnet/corefx#14815]
System.Collections.Generic.Dictionary features [`ContainsValue()`](https://github.com/dotnet/corefx/blob/v1.1.0/src/System.Collections/src/System/Collections/Generic/Dictionary.cs#L218).
Would be nice to have the same method for [ConcurrentDictionary](https://github.com/dotnet/corefx/blob/v1.1.0/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs).

**Comment by jnm2** [comment]
Interesting, what's a typical use case?

**Comment by danmosemsft** [comment]
This would need an api proposal written up eg like https://github.com/dotnet/corefx/issues/12509

**Comment by tkrotoff** [comment]
> Interesting, what's a typical use case?

Same as [`Dictionary.ContainsValue()`](https://msdn.microsoft.com/en-us/library/a63811ah(v=vs.110).aspx), [`Hashtable.ContainsValue()`](https://msdn.microsoft.com/en-us/library/system.collections.hashtable.containsvalue(v=vs.110).aspx), [`StringDictionary.ContainsValue()`](https://msdn.microsoft.com/en-us/library/system.collections.specialized.stringdictionary.containsvalue(v=vs.110).aspx), [`SortedDictionary.ContainsValue()`](https://msdn.microsoft.com/en-us/library/1e4d7b8s(v=vs.110).aspx)

> This would need an api proposal

This reverts to the question: why `Dictionary.ContainsValue()` was introduced in the first place? (I don't have the answer, only guesses).

Without `ContainsValue()` you can still write:
```C#
Dictionary<string, int> dict = new Dictionary<string, int>();
dict.Add("cat", 2);
dict.Add("dog", 1);
bool exists1 = dict.Values.Contains(1); // ConcurrentDictionary.Values.Contains() works
bool exists2 = dict.ContainsValue(2); // Not available with ConcurrentDictionary 
```

**Comment by jnm2** [comment]
> >   Interesting, what's a typical use case?
>
> Same as Dictionary.ContainsValue(), Hashtable.ContainsValue(), StringDictionary.ContainsValue(), SortedDictionary.ContainsValue()

So it's not something you actually needed in a real scenario, just an inconsistency between the APIs that caught your eye? Note that `ContainsValue` is not a central dictionary usage scenario (see [`IDictionary<,>`](https://msdn.microsoft.com/en-us/library/s4ys34ea.aspx)).

The reason I ask is that `ConcurrentDictionary` is unique from the others in that you use it as a synchronization primitive, needing thread safety and high performance. Are you looking for a convenience shorthand for typing `concurrentDictionary.Values.Contains`, or do you have performance goals in mind which `concurrentDictionary.Values.Contains` does not meet?

**Comment by jnm2** [comment]
If a convenience shorthand is what you need, this is one solution:
```c#
public static bool ContainsValue<TKey, TValue>(this IDictionary<TKey, TValue> dict, TValue value)
    => dict.Values.Contains(value);
```

**Comment by safern** [comment]
`ConcurrentDictionary` has several different things that `Dictionary` doesn't have. So just for consistency we think it is not worth adding this API when this can be done just by `dictionary.Values.Contains(value)` and it would only change to `dictionary.ContainsValue(value)`. Being said that we're going to close it.
