### ISSUE TITLE
Issues in SslStream.WriteAsync

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#14824]
Tracks addressing feedback in https://github.com/dotnet/corefx/pull/14771 added after the PR was already merged.  Some of the issues noted look like they could be potentially significant.

cc: @benaadams, @cipop

**Comment by benaadams** [comment]
@stephentoub are you looking at this? 

I can revisit but not for a week and a few days as am currently prepping a product release.

**Comment by stephentoub** [comment]
I think in the meantime we need to rollback the changes.  As far as I can tell, they are invalid / can lead to corruption in the face of re-handshakes, amongst the other issues I noted.

**Comment by benaadams** [comment]
Rolling back will break the aspnet CI build; though its probably the correct starting point

/cc @cesarbs

**Comment by benaadams** [comment]
Rolling back will break the aspnet CI build as it causes https on Kestrel to deadlock. Though its probably the correct starting point to reimplement.

/cc @cesarbs

**Comment by stephentoub** [comment]
> Rolling back will break the aspnet CI build as it causes https on Kestrel to immediately deadlock

It can be rolled back at the same time as changing the calls to BeginRead/Write to instead use Read/WriteAsync on the underlying stream, essentially mirroring what was done in 1.1.

**Comment by benaadams** [comment]
Will make a PR for that shortly

**Comment by stephentoub** [comment]
> Will make a PR for that shortly

Already in the process of doing so...

**Comment by benaadams** [comment]
Already in the process of doing so... 😄
