### ISSUE TITLE
ApiSet dlls still used from native code

### ISSUE THREAD

**Issue by xoofx** [dotnet/corefx#14846]
According to the PR #13440, it was supposed to remove usage of apiset DLL but checking on a recent local build, `clrcompression.dll` typically imports `api-ms-win-crt-runtime-l1-1-0.dll` and `api-ms-win-crt-heap-l1-1-0.dll`

We should probably remove using these DLLs there too.

**Comment by karelz** [comment]
Dupe of #14728
