### ISSUE TITLE
EnumerateWithSymLinkToDirectory test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#14842]
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/ubuntu14.04_release_prtest/50/consoleText
```
ln: failed to create symbolic link ‘/tmp/Directory_SetCurrentDirectory_SymLink_aqwlk5gn.co5/SetToPathContainingSymLink_53/2axwsu1e.4gg/qpehdv1o.3pd’: No such file or directory
     System.IO.Tests.DirectoryInfo_EnumDir_Str.EnumerateWithSymLinkToDirectory [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
              at System.IO.Tests.Directory_GetDirectories_str.EnumerateWithSymLinkToDirectory()
```

**Comment by danmosemsft** [comment]
@JeremyKuhne

**Comment by JeremyKuhne** [comment]
@stephentoub Has this come up multiple times?

**Comment by stephentoub** [comment]
> Has this come up multiple times?

Don't know; I just hit it in a PR and opened the issue for it.

**Comment by JeremyKuhne** [comment]
Thanks, I'll try and track down if this is something more than a fluke. Do our CI runs happen as sudo?

**Comment by danmosemsft** [comment]
@mmitche for Jeremy's questiona bove

**Comment by mmitche** [comment]
@JeremyKuhne No.  Some configurations do have the sudo enabled (the -outer ones), but the root process is still not run as sudo.  This is to avoid leaking sudo requirements into our tests without us knowing.

**Comment by danmosemsft** [comment]
@JeremyKuhne this has only happened once, 2 months ago. do you want to close?
