### ISSUE TITLE
XLinqTests.TreeManipulationTests.LoadFromStreamSanity failing all outerloop runs

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#14856]
The LoadOptionsLI and XE_LoadOptionsLI "variations" are now failing.

**Comment by danmosemsft** [comment]
@krwq why are so many of the XLINQ tests marked [OuterLoop] (which prevented CI from catching this)?

In this case I belive it's this test

```
        [OuterLoop]
        public static void LoadFromStreamSanity()
```

but there are 63 [OuterLoop] tests in XLINQ, mainly in System.Private.Xml.Linq\tests\TreeManipulation\TreeManipulationTests.cs. Is there a good reason?

@sepidehMS

**Comment by stephentoub** [comment]
> @krwq why are so many of the XLINQ tests marked [OuterLoop] (which prevented CI from catching this)?

FYI, I already opened #14855 for this.

**Comment by danmosemsft** [comment]
Oop, yes I just saw.

**Comment by stephentoub** [comment]
@sepidehMS, you marked this as "test bug"... do you know it's a bug in the test?  Seems like the test was passing until changes were made to the implementation.

**Comment by sepidehMS** [comment]
> @sepidehMS, you marked this as "test bug"
I meant to mark it as "bug". I must have miss-clicked.

**Comment by stephentoub** [comment]
Ok, thanks.
