### ISSUE TITLE
Many XML tests are outerloop... why?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#14855]
Lots of the XML test projects are outerloop.  Why?  It'd be great to a) consolidate them into fewer test projects, and b) make most or all of them innerloop, unless there's a really good reason to keep them outer.

**Comment by danmosemsft** [comment]
@krwq @sepidehMS

**Comment by sepidehMS** [comment]
The reason for them being OuterLoop is that these tests are still using the old test structure and were never properly modified to Xunit structure. I will assign some time to break these bundles into separate tests.

**Comment by danmosemsft** [comment]
These are passing and running (albeit not in CI) and we're not churning Xml much right now so I don't think it's particularly urgent to refactor them. Milestone= future.
