### ISSUE TITLE
StreamOperationAsyncResult throws System.NullReferenceException when being finalized by the GC

### ISSUE THREAD

**Issue by ofirmakmal** [dotnet/corefx#14850]
We have an issue where something after disposing a stream, we are getting an exception that is raised from the Finalizer thread, where the only method in the call stack is:
`System.Runtime.WindowsRuntime.dll!System.IO.StreamOperationAsyncResult.CancelStreamOperation
`
Inside this method, there is a check if the callback was invoked, and if not it's calling `_asyncStreamOperation.Close();`

The code of the finalizer is the following:
`
  ~StreamOperationAsyncResult() 
       
        {
            // This finalisation is not critical, but we can still make an effort to notify the underlying WinRT stream
            // that we are not any longer interested in the results:
            CancelStreamOperation();
        }
`

And the CancelStreamOperation method:
`
        internal bool CancelStreamOperation()
 
      {
            if (_callbackInvoked)
                return false;
            _asyncStreamOperation.Cancel();
            return true;
        }`

The only line that could cause the this method to throw NullReferenceException is the call to the Cancel method of _asyncStreamOperation, so the only fix that should be done is checking if _asyncStreamOperation null beforehand.
`            _asyncStreamOperation?.Cancel();`

Exception:
System.NullReferenceException was unhandled
Message: An unhandled exception of type 'System.NullReferenceException' occurred in System.Runtime.WindowsRuntime.dll
Additional information: Object reference not set to an instance of an object.

Current thread that throws the exception:
Not Flagged	>	5980	2	Worker Thread	**GC Finalizer** Thread	System.Runtime.WindowsRuntime.dll!System.IO.**StreamOperationAsyncResult.CancelStreamOperation**	Highest
 	 	 	 	 	 	[External Code]

**Comment by ofirmakmal** [comment]
I've create a PR for fixing this issue at:
https://github.com/dotnet/corefx/pull/14851

**Comment by karelz** [comment]
Were you able to reproduce the problem in a targeted (stress) test?

**Comment by danmosemsft** [comment]
Seems this was fixed, correct?
