### ISSUE TITLE
AssemblyInfo for ref assemblies should not use AllowPartiallyTrustedCallersAttribute

### ISSUE THREAD

**Issue by jcouv** [dotnet/corefx#14868]
While working on adding ref assemblies for `System.ValueTuple` (PR https://github.com/dotnet/corefx/pull/14786) I ran into this problem with the `portable-net40+sl4+win8+wp8` TargetGroup (which uses a PCL profile).
From discussion with @ericstj and @weshaggard, it sounds like the `_AssemblyInfo.cs` file should not use `AllowPartiallyTrustedCallersAttribute` in the first place.

I'm using a workaround to unblock my PR. This issue is meant to track the follow-up.

```C#
using System;
using System.Reflection;
[assembly:System.Security.AllowPartiallyTrustedCallers]
[assembly:System.Runtime.CompilerServices.ReferenceAssembly]
[assembly:System.Reflection.AssemblyFlags((System.Reflection.AssemblyNameFlags)0x70)]
[assembly:AssemblyTitle("System.ValueTuple")]
[assembly:AssemblyDescription("System.ValueTuple")]
[assembly:AssemblyDefaultAlias("System.ValueTuple")]
[assembly:AssemblyCompany("Microsoft Corporation")]
[assembly:AssemblyProduct("Microsoft\x00ae .NET Framework")]
[assembly:AssemblyCopyright("\x00a9 Microsoft Corporation.  All rights reserved.")]
[assembly:AssemblyVersion("4.0.2.0")]
[assembly:AssemblyFileVersion("4.6.24902.0")]
[assembly:AssemblyInformationalVersion(@"4.6.24902.0 built by: jcouv-JCOUVDEV. Commit Hash: 0f771c8a9a11b54e1f3feed43772a9fc7f6da983")]
[assembly:CLSCompliant(true)]
[assembly:System.Reflection.AssemblyMetadata(".NETFrameworkAssembly", "")]
[assembly:System.Reflection.AssemblyMetadata("Serviceable", "True")]
```
from `C:\repos\corefx\bin\obj\ref\System.ValueTuple\4.0.2.0\portable-net40+sl4+win8+wp8\_AssemblyInfo.cs`

**Comment by weshaggard** [comment]
Issue moved to [dotnet/buildtools #1398](https://github.com/dotnet/buildtools/issues/1398) via [**ZenHub**](https://www.zenhub.com/)
