### ISSUE TITLE
corefx should not depend on CRT dlls (on Windows desktop)

### ISSUE THREAD

**Issue by xoofx** [dotnet/corefx#14865]
Followup of #14846 and the undergoing work with #14728, most of the runtime is going to use plain legacy OS functions which will make a self contained app quite portable.

But there is still native components like `clrcompression.dll` that imports `api-ms-win-crt-runtime-l1-1-0.dll` and `api-ms-win-crt-heap-l1-1-0.dll`, making corefx dependent on an installed C runtime just for a few functions imported...

This lead to problems like  ["dll missing from your computer"](https://github.com/dotnet/cli/issues/5201) which is also [infamously popular for many other applications](https://www.google.com/search?q=missing+api-ms-win-crt-runtime-l1-1-0.dll)

These native dlls are probably the last dlls in a repo that have a dependency to the CRT... removing these dependencies would make a self contained dotnetcore app runnable almost on any Windows OS.

I can make a PR about this if you agree with the changes.

**Comment by karelz** [comment]
Is clrcompression.dll the only DLL with dynamic CRT across corefx and coreclr repos?

I thought there is a difference between static and dynamic CRT linking in the heaps created -- one shared (dynamic) vs. one per DLL (static). If there is only couple of DLLs with dynamic CRT, then it probably isn't impactful difference ...

cc: @ianhays @gkhanna79 @JohnChen0

**Comment by gkhanna79** [comment]
All our native components (coreclr, jit, etc) rely on uCRT on Windows and this is by design as we intend to rely on a OS component that will be maintained centrally.

**Comment by xoofx** [comment]
wow, in fact it is when I looked at debug DLL for coreclr that I didn't find the CRT runtime... but checking on release DLL and they are all there 😞

**Comment by gkhanna79** [comment]
Debug builds are, by design, statically linked since they are not expected to be distributed and there are no debug versions of the CRT binaries that can be distributed.

For Release build, we dynamically link to the release version of the CRT binaries and hence, the imports.

**Comment by gkhanna79** [comment]
https://docs.microsoft.com/en-us/dotnet/articles/core/windows-prerequisites calls out that VC++ 2015 redist needs to be installed as that will get the uCRT dependencies inplace.

**Comment by xoofx** [comment]
>  calls out that VC++ 2015 redist needs to be installed as that will get the uCRT dependencies inplace.

well, that's an unfortunate practice for a language runtime... but ok, fair enough for the "design decision" , as I can recompile coreclr+corefx with static linking, it will be possible to redistribute an application without uCRT dependencies...

I will maybe send a PR to allow this configuration by a switch/define if it is not already the case.

**Comment by akoeplinger** [comment]
Does app-local deployment of the uCRT work?

From https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt :

>6. _Updated September 11, 2015:_  App-local deployment of the Universal CRT is supported.  To obtain the binaries for app-local deployment, install the Windows Software Development Kit (SDK) for Windows 10.  The binaries will be installed to C:\Program Files (x86)\Windows Kits\10\Redist\ucrt.  You will need to copy all of the DLLs with your app (note that the set of DLLs are necessary is different on different versions of Windows, so you must include all of the DLLs in order for your program to run on all supported versions of Windows).
