### ISSUE TITLE
Can't build corefx on Linux Mint 18.1

### ISSUE THREAD

**Issue by matekm** [dotnet/corefx#14874]
Hi,

I tried to build corefx on Linux Mint 18.1 and got following error:

> Installing dotnet cli...
> Restoring BuildTools version 1.0.27-prerelease-01121-01...
> Initializing BuildTools...
> Can not find runtime target for framework '.NETCoreApp,Version=v1.0' compatible with one of the target runtimes: 'linuxmint.18.1-x64'. Possible causes:
> 1. The project has not been restored or restore failed - run `dotnet restore`
> 2. The project does not list one of 'linuxmint.18.1-x64' in the 'runtimes' section.
> 3. You may be trying to publish a library, which is not supported. Use `dotnet pack` to distribute libraries.
> ERROR: An error occured when trying to initialize the tools. Please check '/home/matekm/corefx/init-tools.log' for more details.1

Last command seen in  init-tools.log is:
`
Running: /home/matekm/corefx/Tools/dotnetcli/dotnet publish "/home/matekm/corefx/packages/Microsoft.DotNet.BuildTools/1.0.27-prerelease-01121-01/lib/tool-runtime/project.json" -f netcoreapp1.0 -r linuxmint.18.1-x64 -o /home/matekm/corefx/Tools
`

In pkg/Microsoft.NETCore.Platforms/runtime.json I see some entries for linuxmint18, so I would assume corefx is supported for Mint.

What am I doing wrong?

**Comment by mellinoe** [comment]
Linux Mint is supposed to be binary-compatible with Ubuntu 16.04. This should be doable by modifying the  `init-tools` logic to take that into account. e.g. if `linux.mint.18.1` is encountered, treat it the same as `ubuntu.16.04`.

**Comment by wtgodbe** [comment]
Closing as abandoned, @matekm please re-open if you're still having issues
