### ISSUE TITLE
DataContractResolver doesn't work on UWP

### ISSUE THREAD

**Issue by huanwu** [dotnet/corefx#14879]
The UWP App crashes in release mode when using the DataContractResolver in DataContractSerializer.

**Comment by danmosemsft** [comment]
UWP=2.1

**Comment by shmao** [comment]
@huanwu All of the tests using DataContractResolver passed on UWP. Can you please give this another try?

**Comment by huanwu** [comment]
We can close this bug since the DataContractResolver tests pass on UWP. We have another issue to track the failure on wcf https://github.com/dotnet/wcf/issues/1708.  Need verify the WCF scenario once WCF UWP run works.
