### ISSUE TITLE
Microsoft.Win32.Registry.dll version in ref doesn't match the one in nupkg

### ISSUE THREAD

**Issue by tloo** [dotnet/corefx#14875]
When I build Microsoft.Win32.Registry, it will generate "4.0.1.0". But when I build the package, it is using "4.0.0.0", which doesn't have my changes!
Could someone help to explain how does it happen? And where does "4.0.0.0" come from?

**Comment by karelz** [comment]
There can be multiple versions of the assembly in the NuGet package. Can you check all of them and confirm that none of the DLLs in your built package is the one with your changes?

**Comment by tloo** [comment]
Only the one in Microsoft.Win32.Registry.4.3.0\runtimes\win\lib\netstandard1.3 contains my changes, the others doesn't.
Here is the list inside the nupkg.
C:\Users\ttian\Desktop\Microsoft.Win32.Registry.4.3.0>dir /s /b Microsoft.Win32.Registry.dll
C:\Users\ttian\Desktop\Microsoft.Win32.Registry.4.3.0\lib\net46\Microsoft.Win32.Registry.dll
C:\Users\ttian\Desktop\Microsoft.Win32.Registry.4.3.0\ref\net46\Microsoft.Win32.Registry.dll
C:\Users\ttian\Desktop\Microsoft.Win32.Registry.4.3.0\ref\netstandard1.3\Microsoft.Win32.Registry.dll
C:\Users\ttian\Desktop\Microsoft.Win32.Registry.4.3.0\runtimes\unix\lib\netstandard1.3\Microsoft.Win32.Registry.dll
C:\Users\ttian\Desktop\Microsoft.Win32.Registry.4.3.0\runtimes\win\lib\net46\Microsoft.Win32.Registry.dll
C:\Users\ttian\Desktop\Microsoft.Win32.Registry.4.3.0\runtimes\win\lib\netstandard1.3\Microsoft.Win32.Registry.dll

**Comment by karelz** [comment]
What kind of project do you intend to use the NuGet package in? Desktop app? .NET Core app? .NET Standard library?
@sepidehMS @ericstj do you know how the NuGet resolution works in this case?

**Comment by tloo** [comment]
.NET Core app.

**Comment by karelz** [comment]
@tloo are you adding new APIs or just making fixes?
If you're adding new APIs, please be aware that the API surface has to be first approved (see [API review process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md)).

**Comment by tloo** [comment]
@ericstj I don't quite understand, I added one new API in those two files:
[https://github.com/dotnet/corefx/blob/master/src/Microsoft.Win32.Registry/ref/Microsoft.Win32.Registry.cs](Microsoft.Win32.Registry.cs)
[https://github.com/dotnet/corefx/blob/c55435befeb372707558a5c441b3c64bf243948f/src/Microsoft.Win32.Registry/src/Microsoft/Win32/RegistryKey.cs](RegistryKey.cs)
How could I expose it to my app?

@karelz We don't have any plan to commit the changes, that's used only for our project.

**Comment by tloo** [comment]
@ericstj Great! Adding <Preserve>true</Preserve> works! Thanks a lot! This has confused me for one week!
But I still have two questions:
1. How could I add custom label in nupkg, for example:
Microsoft.Win32.Registry.4.3.0-aa-0.nupkg
   It seems change <PreReleaseLabel>aa</PreReleaseLabel> in Packaging.props doesn't help.
2. I'm using this command 
   dotnet restore --packages .\packages
   to save the packages to my local folder instead of the default one (C:\Users\ttian\.nuget\packages).
   But how could I build and publish with my local packages?
   It seems that the build and publish command doesn't have --packages option.

**Comment by sepidehMS** [comment]
@tloo Is your question still valid?

**Comment by ericstj** [comment]
I'll try to answer these questions.
1. Changing PreReleaseLabel is the right thing to do.  Let me know if this still doesn't work.
2. See this issue for the workaround: https://github.com/dotnet/cli/issues/2712.

Additionally, you'll want to make sure that you use build -allConfigurations in the latest CoreFx in order to build the packages.

**Comment by sepidehMS** [comment]
Thanks @ericstj!

**Comment by sepidehMS** [comment]
Questions seem to be answered, so closing. @tloo please re-open otherwise.
