### ISSUE TITLE
Consider supporting OSX 10.10 (Yosemite)

### ISSUE THREAD

**Issue by thezim** [dotnet/corefx#14885]
Per [7731](https://github.com/dotnet/corefx/issues/7731) is was stated that:

> 10.11 is our current minimum supported version of OS X. Older releases 10.9.x and 10.10.x are in limited "Security updates and printer drivers only" support from Apple.

I can vouch that 10.10 does regularly receive security and application updates. The official NET Core install package even allows installation on 10.10. I'm not sure why 10.10 isn't supported unless it is build system issue.

```
    OneDrive:

      Version: 17.3.6720
      Source: 3rd Party
      Install Date: 12/16/16, 8:59 PM

    LastPass:

      Version: 3.18.0
      Source: 3rd Party
      Install Date: 12/16/16, 8:59 PM

    Gatekeeper Configuration Data:

      Version: 107
      Source: Apple
      Install Date: 12/17/16, 8:53 AM

    Security Update 2016-007:

      Version: 10.10.5
      Source: Apple
      Install Date: 12/21/16, 4:01 AM

    OneDrive:

      Version: 17.3.6724
      Source: 3rd Party
      Install Date: 12/25/16, 4:45 PM
```

**Comment by karelz** [comment]
What is the value of supporting OSX 10.10? (how many products/customers cannot upgrade to 10.11 and why)
Do you expect official full support on 10.10?

**Comment by thezim** [comment]
Requirements for 10.11 are [here](https://support.apple.com/kb/sp728?locale=en_US). Not all hardware is supported. I don't have numbers outside of myself.

Powershell will not support 10.10 because corefx does not. This is what lead me here. I understand that 10.10 is 2 versions old but so is Windows 7 which is supported.

What is official full support?

**Comment by karelz** [comment]
Official support means we have daily builds, test runs, infrastructure with HW, perf, stress lab and people monitoring all that and also all OS version specifics implemented in code. So we're talking man-months/years of work + lots of costly HW (currently we're using all Mac HW we have at nearly 100%). On top of that it means we won't be able to deliver other features or (Linux) platforms - the opportunity cost.
Moreover, 10.10 will likely be unsupported in September 2017 (extrapolating dates of 10.8 and 10.9 releases and their end of support).
Unless there is large user base / customer need, I don't expect we will invest into official support.

BTW: Windows 7 has extended support until 2020 (I think it is also good approximation for Windows Server 2008 R2 - not 100% sure though).

I have learned today that we originally started with 10.10 support and then upgraded to 10.11 as the project took longer to get to v1. We may have done some changes in the code base to accommodate 10.11 differences. If you're interested, you may be able to track them down or just try to build against 10.10 and see what works ...

I would suggest to close this issue, unless you want to use it for community driven effort to stand up 10.10 support in which case I am fine keeping it open ...

**Comment by thezim** [comment]
I totally understand about the time and resource requirements. I'm fine with closing this then.
