### ISSUE TITLE
Wrong named tests in System.Xml.XmlDocument

### ISSUE THREAD

**Issue by patricksadowski** [dotnet/corefx#149]
- The files NodeChangingTests.cs, NodeChangedTests.cs, NodeInsertingTests.cs and NodeInsertedTests.cs contain test cases called "RemoveEventHandler". No test uses a "Remove"-event. Maybe a Copy&Paste mistake from file NodeRemovedTests.cs.
- The files NodeChangingTests.cs and NodeChangedTests.cs contain test cases called "RemoveNode" but testing a change of a node.

**Comment by krwq** [comment]
Looking at the NodeChangingTests.cs & NodeChangedTests.cs & NodeInsertingTests.cs and I can see that they do remove the event handler
```
        [Fact]
        public static void RemoveEventHandler()
        {
            var xmlDocument = new XmlDocument();
            xmlDocument.LoadXml(@"<root> <elem1>text1</elem1> <elem2>text2</elem2> </root>");

            XmlNodeChangedEventHandler handler = (s, e) => Assert.True(false, "Handler should have been removed");
            xmlDocument.NodeChanging += handler;
            xmlDocument.NodeChanging -= handler;

            xmlDocument.DocumentElement.FirstChild.InnerText = "newvalue";
        }
```

For the other thing I started a PR: https://github.com/dotnet/corefx/pull/561
