### ISSUE TITLE
Is it possible to read System.Type from an appsettings.json file in a .net core application

### ISSUE THREAD

**Issue by AnithaLingam** [dotnet/corefx#14924]
In my project i need to read the System.Type setting from appsettings.jason..but not able to read please look in to this .

Here is my code:
appsettings.jason:
  "LogKafkaFactoryConfiguration": {
      "type": "SPGMI.Logging.NetCore.Kafka.Configuration.LogRdKafkaClientFactory, SPGMI.Logging.NetCore"
    },

I want to read type and pass to below method..below code in .Net 452
_clientfactory = System.Activator.CreateInstance(LogConfiguration.GetInstance().Client.type) as IFactory<AbstractKafkaClient>;

Samething needs to be odne .net core..

**Comment by karelz** [comment]
I think appsettings.json is ASP.NET Core concept - in which case I would suggest to ask on their repos.

**Comment by tarekgh** [comment]
please post your question on https://github.com/aspnet. I am closing the issue here but feel free to re-open if you think it should stay here. thanks.
