### ISSUE TITLE
API Proposal: Add check for StateChange event subscribers to DbConnection

### ISSUE THREAD

**Issue by roji** [dotnet/corefx#14934]
# The problem

ADO.NET providers are supposed to call `DbConnection.OnStateChange` on connection state changes. The problem is that this design forces the allocation of the StateChangeEventArgs parameter regardless of whether there are subscribers to StateChange or not. In an effort to reduce heap allocations, it would be good if implementing providers could have a way of checking whether there are subscribers or not before allocating and calling `DbConnection.OnStateChange`.

# Proposal

Add a protected, non-virtual method called `StateChangeHasSubscribers` to `DbConnection`, returning a bool. Implementing providers would have the option of calling it, and skipping `OnStateChange` if false is returned.

**Comment by jnm2** [comment]
What makes DbConnection.OnStateChange different in this way from the loads of other `EventArgs`-taking `On*` methods in other classes? In what scenarios will this make a measurable difference?

**Comment by roji** [comment]
@jnm2 I'm not aware of all cases where events are fired within corefx, but depending on the scenario it seems like a worthy optimization to eliminate the unneeded allocation. One important point if that providers extending DbConnection typically use pooling, which means that open and close operations are extremely light and involve no I/O whatsoever. This makes the weight of the allocation somewhat more problematic.

The specific provider I'm working on, Npgsql, is nearly zero-allocation on pooled open/close, with this event being the source of a lot of needless heap churn.

**Comment by roji** [comment]
I just realized that `StateChangeEventArgs` doesn't actually reference the connection the generated it (the sender), allowing instances to simply be cached... This means that this issue isn't very important.
