### ISSUE TITLE
build-managed.cmd -packages doesn't work in release/1.1.0

### ISSUE THREAD

**Issue by tloo** [dotnet/corefx#14946]
I download both 
tags: v1.1.0
and 
branch: release/1.1.0

But in  release/1.1.0 
build-managed.cmd -packages doesn't work.
Is tag v1.1.0 the correct tag for correct release 1.1.0?

**Comment by weshaggard** [comment]
@tloo in our release branches we intentionally filter the packages that build. See https://github.com/dotnet/corefx/commit/25c1e724f4c8f332d73613960798b2e40ee513f8. You can set BuildAllPackages=true if you want to build them.

**Comment by tloo** [comment]
@weshaggard thanks! Where can I set BuildAllPackages=true? Can I set it through command line?
I tried "build-managed.cmd -packages -ExtraParameters BuildAllPackages=true", but it doesn't work.
Should I change packages.builds?

**Comment by tloo** [comment]
@weshaggard after setting BuildAllPackage to true in packages.builds, it works! Thanks!
One more question: How could I make <PreReleaseLabel> being added in the nupkg?
<PreReleaseLabel>preview1</PreReleaseLabel>

**Comment by weshaggard** [comment]
You can pass it at the command line via `-- /p:BuildAllPackages=true`. I'm not sure I understand your other question but I'm guessing you are asking how can you change the prerelease moniker and if so you want to update the version and it will automatically use the moniker. See https://github.com/dotnet/corefx/pull/13097 where we marked the particular package versions as stable which is how we determine whether or not to add the prerelease label or not.

**Comment by tloo** [comment]
@karelz After changing the version, build-manage -packages will fail

>    130>C:\Users\ttian\work\corefx-release-1.1.0\corefx-release-1.1.0\Tools\Packaging.targets(1077,5): error : System.Collections.Specialized should support API version 4.0.2.0 on .NETStandard,Version=v1.3 but System.Collections.Specialized/ref/netstandard1.3/System.Collections.Specialized.dll was found to support 4.0.1.0. [C:\Users\ttian\work\corefx-release-1.1.0\corefx-release-1.1.0\src\System.Collections.Specialized\pkg\System.Collections.Specialized.pkgproj]


> C:\Users\ttian\work\corefx-release-1.1.0\corefx-release-1.1.0\pkg\NETStandard.Library\NETStandard.Library.pkgproj]
> C:\Users\ttian\work\corefx-release-1.1.0\corefx-release-1.1.0\Tools\Packaging.targets(1165,5): error :    at Microsoft.DotNet.Build.Tasks.Packaging.NuGetPack.Pack(String nuspecPath, Func`2 nuspecPropertyProvider, Boolean packSymbols) [C:\Users\ttian\work\corefx-release-1.1.0\corefx-release-1.1.0\pkg\NETStandard.Library\NETStandard.Library.pkgproj]
> 

I have attached the build log.
[msbuild.err.txt](https://github.com/dotnet/corefx/files/696364/msbuild.err.txt)

**Comment by weshaggard** [comment]
cc @ericstj  who might be able to help as well.

@tloo can you point me at a branch with the changes you made so I can see what you changed?

**Comment by tloo** [comment]
@weshaggard Sure, I'm using corefx-release-1.1.0, changed this file: Packaging.props.
Changed PackageVersion from 4.3.0 to 4.3.1
` <PackageVersion Condition="'$(PackageVersion)' == ''">4.3.1</PackageVersion>`

**Comment by weshaggard** [comment]
@tloo were you able to figure out your issue here?

**Comment by tloo** [comment]
@weshaggard we have decided not to change corefx directly. We will use some working around solution. Thanks for the following up.
