### ISSUE TITLE
Build-managed from a clean enlistment fails

### ISSUE THREAD

**Issue by chcosta** [dotnet/corefx#14940]
You cannot run build-managed.cmd from a clean enlistment without your build failing.  build-managed.cmd now includes the build packages step which requires native binaries.  This may be a point of consternation for devs.

**Comment by mellinoe** [comment]
Should we pull out the package build from build-managed, then? It doesn't actually make sense for it to be part of the "managed" build if it needs the native components, too.

**Comment by weshaggard** [comment]
cc @ericstj 
I think it is fine to make it optional and we can always pass BuildPackage=true from build.cmd to get all these if we still want that.
