### ISSUE TITLE
"System.Security.Claims" compatible with .NET 4.5.1?

### ISSUE THREAD

**Issue by fubar-coder** [dotnet/corefx#14967]
Is it possible to make the System.Security.Claims package compatible with .NET 4.5.1? Is it different from the implementation of .NET 4.5.1 or was there another reason why its nuget package only supports netstandard1.3 and net46?

**Comment by karelz** [comment]
If it depends on crypto, then it needs 4.6 at minimum. The easiest thing is to try to compile it against net451 and see what fails.

BTW: 4.5.1 is [out of support](https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/) for a year.

**Comment by danmosemsft** [comment]
@fubar-coder haven't heard back so i'm going to close .. feel free to reopen if needed
