### ISSUE TITLE
Remove silent boxing/make exceptions consistent in ImmutableArray

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#14961]
Tracking issue for changes to the source of `ImmutableArray` to be made after the test changes in #14798. All of these will be fixed in a subsequent PR.

- [ ] Remove silent boxing in `Remove` / `Replace`
  - Relevant lines: [`Replace`](https://github.com/jamesqo/corefx/blob/38b28ed31c9a6620fbbfd6c3822bc1a2ea6c3c9f/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.cs#L731-L734), [`Remove`](https://github.com/jamesqo/corefx/blob/38b28ed31c9a6620fbbfd6c3822bc1a2ea6c3c9f/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.cs#L771)
  - There exists no `IndexOf(T, IEqualityComparer<T>)` method on ImmutableArray, so it is boxed to an IImmutableList and the ImmutableList extension method is called
  - These should be trivial to fix (just pass in `0` and `self.Length`)
- [ ] Make exceptions thrown by `RemoveRange` / `Remove` consistent
  - Relevant diffs: https://github.com/dotnet/corefx/pull/14798/files#diff-5c35677b4c2163f273b62555ee2cc97bR731, https://github.com/dotnet/corefx/pull/14798/files#diff-5c35677b4c2163f273b62555ee2cc97bR797

**Comment by karelz** [comment]
@jamesqo can you provide more details on the inconsistent exceptions? (I didn't get it from the linked PRs)
What is the compat impact of such change? If there is compat risk, we should understand the value (it may be worth splitting up that part into its own issue if we expect a discussion around it).

**Comment by jamesqo** [comment]
@karelz See [here](https://github.com/dotnet/corefx/pull/14798#discussion_r94341057). There is little to no compat risk because the type of exception is changed only when two things are invalid; the `index` must be negative and the array must be a default instance.
