### ISSUE TITLE
Multilanguage with .net core

### ISSUE THREAD

**Issue by binoypatel** [dotnet/corefx#14998]
This issue is related to [https://github.com/dotnet/standard/issues/152](https://github.com/dotnet/standard/issues/152), as requested by karelz, I have opened a new issue to corefx. 

Please check [https://github.com/binoypatel/NetCore.Localization](https://github.com/binoypatel/NetCore.Localization) example, this is hello-world style application with 11 lines of code.

I have tested this issue with and confirmed that it is still not working:
Microsoft.Net Core 1.1.0 - SDK 1.0.0 Preview 2.1-003177
Microsoft .NET Core 1.0.1 VS 2015 Tooling Preview 2

Thanks,
Binoy

**Comment by onovotny** [comment]
Hi @binoypatel can you please try the .NET Core one with VS 2017? I know there are some bugs with `project.json` and satellite assemblies that I came across with `Humanizer`. Moving to `csproj` in VS 2017 should resolve those; can you verify for your case?

**Comment by tarekgh** [comment]
CC @ramarag

**Comment by onovotny** [comment]
I think this bug is a manifestation of this bug: https://github.com/dotnet/cli/issues/3396

**Comment by tarekgh** [comment]
most likely you are right @onovotny 
I'll let @ramarag confirm that and close the issue here if this is the case.
Thanks.

**Comment by binoypatel** [comment]
@onovotny , @tarekgh , tested with VS2017 RC1 and confirmed working. My question is now should I move my production application to VS2017 or continue working with VS2015 until VS2017 RTMed?

Kind regards,
Binoy
