### ISSUE TITLE
Consider making NegotiateStreamPal and related APIs in Common a reusable component

### ISSUE THREAD

**Issue by saurabh500** [dotnet/corefx#15012]
System.Data.SqlClient needs to use the GSSAPIs to interact with the Kerberos tokens to authenticate Sql Server users on .Net Core on Linux and macOS

System.Net.Mail has a dependency on the Interop Classes in Common folder, e.g. https://github.com/dotnet/corefx/blob/fd15ab1de03a4431e0ead9ff10e1bf53e2ae4bb7/src/System.Net.Mail/src/System.Net.Mail.csproj#L148

Can the Common\System\Net\Security\* and related files be made a component (a Nuget package) which can be reused by SqlClient, System.Net.Security and System.Net.Mail? 

This will allow the consumers to consume a single package instead of including the platform specific files for compilation in the project files.

Alternatively, can APIs be added to interact with GSS-APIs using .Net Core so that the managed version of System.Data.SqlClient be truly portable without taking platform specific dependencies? 

SqlClient mainly needs to use AcquireCredentialHandle and InitializeSecurityContext APIs to make the feature work for Managed SNI. 

cc @stephentoub @YoungGah

**Comment by karelz** [comment]
@Priya91 suggested creating a proper Authentication API. We just didn't have time to fund it yet. I can't find the issue filed ...

I don't think the code in Common folder is ready to be public API.

**Comment by Priya91** [comment]
The proposal to extract it out was tracked in #13364, we didn't end up with exposing those internal auth types public, because they are not well designed to be application protocol layer agnostic. Some APIs are tied to specific class of applications like webrequest, mail, http, etc. And hurrying to expose it without proper thought will be irreversible to delete these APIs. So for now, we solve this by compiling these bits in the libraries itself. 

It would be really beneficial to design a good auth API. Will file an issue with the proposal.

**Comment by saurabh500** [comment]
Thanks @Priya91 
Can you open an issue to track this API with a couple lines, even if it is to be funded in future as recommended by @karelz in https://github.com/dotnet/corefx/issues/13364#issuecomment-265560539 ? 
I can subscribe to it.

**Comment by saurabh500** [comment]
Alternatively, can a self contained Nuget package be created which can be consumed by .Net Core, like System.Net.Security.Native ?

**Comment by Priya91** [comment]
> Alternatively, can a self contained Nuget package be created which can be consumed by .Net Core

Creating a nuget package implies releasing new API.. Anyone can take dependency on it, and we can't make them go back :)

**Comment by saurabh500** [comment]
I was suggesting more from the point of view of having a Nuget package for consumption for Core like the System.Net.Security.Native and sni.dll do. They are nuget packages and come with a note that they are not meant to be consumed outside .Net Core. The difference is that they are Native packages and I was recommending a C# nuget package. I agree that it exposes a bunch of APIs which .Net Core consumes but I am not recommending that the APIs be exposed as official APIs. 

If someone adds them to their project, it's done at their risk.

**Comment by karelz** [comment]
The problem is that the package will be in dependency graph of apps. Intellisense will just offer the namespaces. Unless we name the namespace something like DontEverUseThisUnsupportedTemporaryNamespace.
Is including the sources really that painful? While not ideal, I think it is reasonable workaround ...

**Comment by Priya91** [comment]
@saurabh500 You could follow the System.Net.Mail [commit](https://github.com/dotnet/corefx/commit/140305bf508db47c3bc23df182d549b9a37792cc#diff-11c574debebea72f325e933a77957490), to get the dependent files instead of reworking again.

**Comment by saurabh500** [comment]
Including the sources leads to a bunch of redundancies include adding the Common strings to resx files which are needed by the Common code. 
We are looking at adding the Integrated Auth APIs to our SNI implementation which works on Unix and Mac. We want to keep our managed implementation platform agnostic, and so that SqlClient can work on any platform which supports the complete .Net Core surface area. Not having these APIs is the only issue, which keeps the managed version of System.Data.SqlClient have any platform specific dependencies. 

@Priya91 We have a prototype implementation of Integrated Auth by including the files in our Csproj the way System.Net.Mail had done after you had moved the needed code out of System.Net.Security.
We are relying on NegotiateStreamPal to accomplish this.

**Comment by karelz** [comment]
Thanks @saurabh500 for your explanation, I think I understand your motivation now.
I think that exposing temporary public APIs is just too ugly & risky workaround to achieve your goal. I would rather prefer to invest into proper public Authentication API (which likely means to use Common code for now).

**Comment by saurabh500** [comment]
@karelz I agree. Based on what you mentioned about the tooling, the overall dev experience with tooling can be messed up. 
I will follow the work on #15017
