### ISSUE TITLE
Proposal: Runtime Feature Testing

### ISSUE THREAD

**Issue by prasannavl** [dotnet/corefx#1501]
### The Problem: 

Detection of .NET Runtime has never been reliable. One could either using Reflection to drill into the version info, look at the Environment and so on. This SO question http://stackoverflow.com/questions/8517159/how-to-detect-at-runtime-that-net-version-4-5-currently-running-your-code/8543850#8543850, and its answer gives an idea of the better approaches to do. But there is no one constant way to do it.

### The Solution:

Introduce a runtime feature class, which does feature testing. And this is also a place where external libraries loaded can add their own feature-set, so version testing is essentially not required at all. You test for the feature you need, and proceed ahead based on that. 

```c#
namespace System.Diagnostics

public static class Features
{
public static bool IsAvailable(string feature);

// Checks if the executing assembly name is prefixed first, or else throws, ensuring that
// only the correct assemblies add them. (There is of course reflection if tricking is
// indeed the developer's intention).

public static void AddFeature(string feature); 

public static void RemoveFeature(string feature);
public static IEnumerable<string> GetAllFeatures();

public event Action<string, FeatureChangeAction> FeatureChanged; 

public enum FeatureChangeAction {
Added, Removed,
}

public static class InternalFeatures
{
public const string ReflectionContext = "mscorlib.net45refl"
}

}

```

Implementation of this could just be a simple dictionary. This avoids the need to know what to look for for each feature, and provides a consistency in checking for features.

**Comment by krwq** [comment]
I think this should be on https://github.com/dotnet/coreclr
Also I'm not how would you use this. If you can fallback to other behavior when feature doesn't exist why not always use that behavior?

**Comment by prasannavl** [comment]
@krwq, This seems like a very simple and trivial library. In fact, this could even easily be an external library, but without the consistency an internal one would create. I didn't think this really has anything to do with the CLR, that's why I posted it here. 

And with regards to fallback, I'd like to think we call them as `fallback` for a reason.

**Comment by weshaggard** [comment]
@prasannavl your current proposal seems to somewhat align with [AppContext](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/AppContext/AppContext.cs) which @AlexGhiondea owns so he can probably help see if the scenarios align or if it is worth another API.

**Comment by mellinoe** [comment]
Could you give some example usages (with code)? It's not clear to me how you would use this, i.e. what "features" would you query for, what do you do with that information, etc. in ways that cannot be accomplished currently.

**Comment by bpschoch** [comment]
Not sure if this is what the author had in mind, but one problem I see as the library gets ported to various platforms, not all its capabilities are always available.  For example the System.IO.Pipes library supports byte mode messaging and message mode which is supported in the windows world but not in the unix world (only supports byte mode).  An app using the library has no ability to know that the feature is missing until it actually makes an api call to try to use that functionality and gets an exception thrown.  (there are other features not support in the unix world for pipes including being able to determine number of servers and input/output buffer sizes.

So the questions is, how does either an app or developer determine how portable the library is?

Via a documentation matrix table of sorts? (probably)

Some sort of api that can query capabilities? (maybe)

Also an other angle on this.  Is the purpose of the library to provide a maximal uniform experience of  all functionality across all platforms?  Or does the library bind as much as possible to the underlying platform?  For example, unix pipes don't support message boundaries but windows does.  Message boundaries could be simulated on the unix platform by prefixing message lengths in the byte stream but doing this makes it incompatible with interacting with non-net library unix app.  What is the proper philosophy?

Comments?

**Comment by AlexGhiondea** [comment]
AppContext should help with this and is, in fact, fairly close to this.

AppContext provides 2 APIs:
```csharp
void SetSwitch(string name, bool value)
bool TryGetSwitch(string name, out bool value)
```
These APIs allow apps to set/get values of a switch and make runtime decisions based on these. We use this in the framework to provide back-compat behavior for APIs. 
The way this works is that the library queries for the value of a switch. 
 - If the value comes back as false, it provides the latest behavior for the API. If the 
 - If the value is true then it provides the previous behavior for that API.

For Desktop framework we have a list of switches that are enabled *by default* for a given version of the framework. 
These defaults can be overwritten allowing apps that do not target the latest version to pick and choose which behaviors they want to enable.

To answer @bpschoch comment, one can imagine having a different set of defaults for Windows/Unix to control which behaviors are supported.

I am not saying that is the right way to handle that. Ideally an implementation of a contract should work the same regardless of where it is running. Where that is not possible, AppContext *might* be a good way to detect this.

@prasannavl does AppContext seem like it would address your scenario?

**Comment by prasannavl** [comment]
Sorry for the late reply. And yes, I just glanced through the AppContext, and I believe that should take care of my all the intentions mentioned in this issue.

@AlexGhiondea, thanks for the brief and clearing up on the intent of AppContext. I think this issue no longer needs to remain open. Curious to see what else is going to be a part of AppContext though, since the name is quite generic implying a composition of more.
