### ISSUE TITLE
Adding System.Configuration

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#15040]
Desktop types in the `System.Configuration` namespace have been ported from 4.6. On desktop the types lived in both `System.dll` and `System.Configuration.dll` (originally they all lived in System). The goals in the port:

- Enable users getting/setting data from configuration files
- Port as much relevant code as realistically possible
- Avoid unnecessarily breaking existing usage of the System.Configuration APIs

The vast majority of the existing code was ported with the following caveats:

- `ConfigurationPermission` wasn't ported due to System.Security dependencies
- All limited trust related code was either trimmed or made no-op
- Integration with platform and web configuration was stubbed out (some internal callbacks to deal with cyclical dependencies)

#### Issue One
We need to pick a new name for the assembly to avoid conflicting with desktop. Proposal is `System.Configuration.ConfigurationManager.dll` as that is the main entry point for the configuration system.

#### Issue Two
In general configuration types are generated through reflection. Types are defined in the configuration files- a number of the built in types depend on `machine.config` defining them to be instantiated correctly. As we currently don't ship a `machine.config` we provide an implicit in-memory file if the machine.config location (which is relative to the platform root) doesn't exist **and** the user hasn't explicitly provided a location.

We provide all definitions that reference types specifically in the `System.Configuration` namespace. `System.Web.Configuration` and other assembly data isn't currently included. Unlike the standard `machine.config` we aren't explicit about the version or strong name:

``` xml
<configuration>
    <configSections>
        <section name='appSettings' type='System.Configuration.AppSettingsSection, System.Configuration' restartOnExternalChanges='false' requirePermission='false'/>
        <section name='connectionStrings' type='System.Configuration.ConnectionStringsSection, System.Configuration' requirePermission='false'/>
        <section name='mscorlib' type='System.Configuration.IgnoreSection, System.Configuration' allowLocation='false'/>
        <section name='runtime' type='System.Configuration.IgnoreSection, System.Configuration' allowLocation='false'/>
        <section name='assemblyBinding' type='System.Configuration.IgnoreSection, System.Configuration' allowLocation='false'/>
        <section name='satelliteassemblies' type='System.Configuration.IgnoreSection, System.Configuration' allowLocation='false'/>
        <section name='startup' type='System.Configuration.IgnoreSection, System.Configuration' allowLocation='false'/>
    </configSections>
    <configProtectedData defaultProvider='RsaProtectedConfigurationProvider'>
        <providers>
            <add name = 'RsaProtectedConfigurationProvider' type='System.Configuration.RsaProtectedConfigurationProvider,System.Configuration' description='Uses RsaCryptoServiceProvider to encrypt and decrypt' keyContainerName='NetFrameworkConfigurationKey' cspProviderName='' useMachineContainer='true' useOAEP='false'/>
            <add name = 'DataProtectionConfigurationProvider' type='System.Configuration.DpapiProtectedConfigurationProvider,System.Configuration' description='Uses CryptProtectData and CryptUnProtectData Windows APIs to encrypt and decrypt' useMachineProtection='true' keyEntropy=''/>
        </providers>
    </configProtectedData>
    <connectionStrings>
        <add name = 'LocalSqlServer' connectionString='data source=.\SQLEXPRESS;Integrated Security=SSPI;AttachDBFilename=|DataDirectory|aspnetdb.mdf;User Instance=true' providerName='System.Data.SqlClient'/>
    </connectionStrings>
</configuration>
```

The goal here is to minimize the need to either include a machine config with your app or define said types in your own config files. (Note that having multiple instances of a section definition is not allowed.)

This is the current implementation and POR- we just need to understand and agree on it.

#### Issue Three

`System.UriIdnScope` was only ever exposed in `System.Configuration`. I've included in this assembly as we haven't exposed it yet and it really should have been defined in `System.Configuration` to begin with.

**Comment by terrajobst** [comment]
We know that Xamarin has excluded configuration to help with AOT. It seems the current design is:

1. `System.Configuration.ConfigurationManager` depends on a large number of assemblies. 
2. We don't plan on depending `System.Configuration.ConfigurationManager` in .NET Core, we purely provide it for consumers

That seems fine. That simply means that customers who depend on it might not get a very trimmed output, but the ability of the framework to be trimmed is (generally) unaffected.

**Comment by JeremyKuhne** [comment]
Assembly rename is in.
