### ISSUE TITLE
Remove TypeConverter dependency from System.Data.Common

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#15045]
Currently System.Data.Common depends on System.ComponentModel.TypeConverter which we should break. TypeConverter is a higher level assembly with lots of dependencies which we don't want to pull in with System.Data.Common. If we need type converters for System.Data.Common we can move implement them or add the mappings for them in S.CM.TypeConverter directly.

**Comment by stephentoub** [comment]
This is a huge dependency; try removing it, and you'll get ~600 errors.  Some of it is in implementation, some of it is in API.

**Comment by weshaggard** [comment]
From a quick look it seems as though it is a couple TypeConverters and a mapping attribute. I would propose we move the TypeConverters to S.CM.TypeConverter and the mapping can also be added to the mapping list in S.CM.TypeConverter. So that would invert the dependency which is what we have done in other cases as well like S.Drawing.Primitives.

**Comment by ViktorHofer** [comment]
These are the types that are referenced by System.Data.Common:

```
TypeConverterAttribute
TypeConverter
ITypeDescriptorContext
ListBindableAttribute
ListBindable
SettingsBindableAttributeAttribute
SettingsBindableAttribute
RecommendedAsConfigurableAttribute
RecommendedAsConfigurable
ICustomTypeDescriptor
PropertyDescriptorCollection
AttributeCollection
PropertyDescriptor
EventDescriptor
EventDescriptorCollection
DefaultPropertyAttribute
DefaultProperty
DefaultEventAttribute
DefaultEvent
CollectionChangeEventHandler
CollectionChangeEventArgs
ExpandableObjectConverter
ToolboxItemAttribute
ToolboxItem
DesignTimeVisibleAttribute
DesignTimeVisible
MarshalByValueComponent
IDataErrorInfo
IListSource
ISupportInitializeNotification
ReferenceConverter
IBindingListView
ListChangedEventArgs
TypeConverterAttributeAttribute
IBindingList
ListSortDirection
ListChangedEventHandler
ListSortDescriptionCollection
ListChangedType
StandardValuesCollection
StringConverter
InstanceDescriptor
```

**Comment by weshaggard** [comment]
@ViktorHofer how did you get that list? I would suggest removing the dependency and then compiling. I really hope System.Data.Common doesn't use thing like ToolboxItem, unless that is really the attribute. If these are just for the attributes then I think we can safely remove the attribute applications. 

And for the other TypeConverter stuff we should remove any TypeConverters that exist in System.Data.Common and if we do need them for something they should be moved into System.ComponentModel.TypeConverters instead.

**Comment by danmosemsft** [comment]
@weshaggard is this still necessary for 2.0? it seems like just cleanup, these both will ship in the same package.

**Comment by ViktorHofer** [comment]
> @ViktorHofer how did you get that list?
What is the ignore file for? If it is just to add comments?

I will answer both your questions here. Dan and I made that list to distinguish between what is still is a TODO for 2.0 in `ApiCompatBaseline.netcoreapp.netfx461.txt` and what is intentionally skipped (`ApiCompatBaseline.netcoreapp.netfx461.ignore.txt`). I wrote a little 30-liner diff util which then produces a file (I call it by convention `ApiCompatBaseline.netcoreapp.netfx461.remaining.txt`) which shows the remaining work for 2.0 to align with netfx.

**Comment by ViktorHofer** [comment]
@weshaggard I did a regex over all 590 errors which are showing up when removing the dependency.

**Comment by weshaggard** [comment]
@danmosemsft I agree both of these will be in the shared framework this is still a very terrible dependency to have for folks that want to trim their application as TypeConverter library depends on tons of stuff and I would prefer to invert this dependency so that people using Data don't have to pay the TypeConverter cost.

**Comment by weshaggard** [comment]
While I don't think it blocks 2.0 it is something I would like to see fixed for 2.0

**Comment by ViktorHofer** [comment]
Seems reasonable to me. I'll  take it.

@weshaggard let us chat offline today or tomorrow so that I fully understand what needs to be done.

**Comment by danmosemsft** [comment]
@ViktorHofer please investigate the cost first. If this is costly we may need to rethink the priority

**Comment by ViktorHofer** [comment]
> And for the other TypeConverter stuff we should remove any TypeConverters that exist in System.Data.Common and if we do need them for something they should be moved into System.ComponentModel.TypeConverters instead.

You mean we also remove all TypeConverter Attributes from the types? Example in DataColumn.cs:
```
/// <summary>
        /// Gets or sets the default value for the column when creating new rows.
        /// </summary>
        [TypeConverter(typeof(DefaultValueTypeConverter))]
        public object DefaultValue
```
Wouldn't that break the expected behavior? Type converting wouldn't be possible then?

> I really hope System.Data.Common doesn't use thing like ToolboxItem, unless that is really the attribute. If these are just for the attributes then I think we can safely remove the attribute applications.

![image](https://cloud.githubusercontent.com/assets/7412651/25180662/1a60190e-250f-11e7-975b-2a3058d5b94e.png)

**Comment by weshaggard** [comment]
>Wouldn't that break the expected behavior? Type converting wouldn't be possible then?

Yes we should remove them here and move them into https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs#L102 if we feel the are needed. I would suggest only doing that reactively if we find they are needed.

>In that case it is the attribute. What about the DesignTimeAttribute? There are several attributes where I'm not sure if simply removing them is what we really want.

Those attributes are only interesting to VS designers for WinForms which we do not support in .NET Core (at least not at this point), so we can just remove them.

**Comment by ViktorHofer** [comment]
@danmosemsft  I just looked into it again and think the cost is VERY high.

**Comment by ViktorHofer** [comment]
@weshaggard had you already time to look into it? as this would be a pretty large code change I'm not sure if we should still tackle 2.0 for it?

**Comment by weshaggard** [comment]
This slipped off my radar. I would still like to at least look at it for 2.0. I will assign to myself to it shows on my list, and try to take a look at it in the next week.

**Comment by weshaggard** [comment]
OK I took a closer look at this dependency unfortunately it isn't as clean as I would have liked. While I could have probably cleaned out the attributes usage in the implementation the real trouble is the ICustomTypeDescriptor interface which is implemented by a number of types in System.Data.Common. I cannot easily break that dependency as those interface implementations are also part of netstandard so we cannot remove them without removing them from netstandard as well which I don't want to do at this point. I really wish I had taking a deeper look at this a couple months ago and then I would have ripped it apart but at this point I don't think there is a lot we can do.

In the future we may need to break some of the dependencies here to avoid System.Data.Common pulling in TypeConverter and its full closure, but for now we are just going to have to live with it. System.Data.Common already has a pretty large closure anyway.
