### ISSUE TITLE
CurlHandler calls HttpContent.ReadAsStreamAsync - doesn't this mean request bodies are always buffered?

### ISSUE THREAD

**Issue by tintoy** [dotnet/corefx#15096]
While tracking down some odd behaviour with HttpClient on OSX (request body always seems to be buffered, unlike response body) I noticed that `CurlHandler` calls `HttpContent.ReadAsStreamAsync` rather than `CopyToAsync`:

https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.MultiAgent.cs#L1167

Am I correct in my assumption that this means the request body will always be buffered before sending? From what I understand, `CopyToAsync` will copy the stream without buffering if possible, but `ReadAsStreamAsync` will load the stream into a buffer first and return a stream over that buffer.

Looking at the code I can see why it's been done that way but it means that, unlike the Windows implementation, uploads of really large files may cause problems.

**Comment by tintoy** [comment]
(I ran into this, specifically, when trying to send `StreamContent` in the request body)

**Comment by davidsh** [comment]
cc: @stephentoub 

`HttpContent.ReadAsStreamAsync` does not buffer anything.  It simply returns a Stream representing that HttpContent object.

**Comment by tintoy** [comment]
Here's the code that was causing problems:

https://github.com/tintoy/AWTY/blob/development/v1.0/test/AWTY.Http.IntegrationTests/ProgressHandlerTests.cs#L104

When I use a `MemoryStream` and `StreamContent`, the content's data is always read in a single pass (buffer exactly the same size as the content, no matter how large it is).

But when I use a [class](https://github.com/tintoy/AWTY/blob/development/v1.0/test/AWTY.Http.IntegrationTests/DumbMemoryStream.cs) derived from `MemoryStream` and a [simple](https://github.com/tintoy/AWTY/blob/development/v1.0/test/AWTY.Http.IntegrationTests/StreamingRequestContent.cs) `HttpContent` implementation, it does read it in several passes.

The server is a real server, BTW, not the standard test server - I'm trying to test with actual network streaming.

It's entirely possible I've got this all completely wrong, but I've been scratching my head over this behaviour for a couple of days now and figured it was time to ask someone who actually knows what the correct behaviour is supposed to be :)

**Comment by tintoy** [comment]
Interestingly, `HttpContent.CopyToAsync` will attempt to buffer the content:

https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpContent.cs#L279

But `StreamContent` doesn't (can't?) override this, so how does it avoid being buffered when using `CopyToAsync`?

**Comment by davidsh** [comment]
As you seeing this behavior when you use this HttpContent as a requestBody to POST?  It sounds like this is a requestBody issue.

It is possible that the implementation of CurlhHandler is buffer'ing the requestBody content.  But that would be an implementation detail of this handler and not a design issue, per se, with HttpContent.

@stephentoub would be the best person to answer this question.

**Comment by tintoy** [comment]
Yep, that's correct - it works just fine when I'm reading a stream representing the response body, but not when sending a stream request body.

Yes, I suspect that may be the case (issue is with `CurlHandler` not `HttpContent`) but I can't be certain (after looking at a problem for long enough, I'm no longer sure of anything).

**Comment by tintoy** [comment]
I've tried passing an instrumented `Stream` implementation to `StreamContent`, BTW, that's how I tracked the issue this far. Just overrode `Read` and `Write` methods to dump the buffer size and count.

**Comment by tintoy** [comment]
Ok, so I believe I've fixed the problem, but I'm not sure I understand _why_:

https://github.com/tintoy/AWTY/commit/21789912f9074a8424c82ec75e34430c42f69d18#diff-274b91af93396a16f4cdf8de3e5ed44cR149

The issue (I think) is that `HttpContent.CopyToAsync` doesn't specify a buffer size, and so by default the entire content stream written to my progress stream with a single call to `Write`. This seems odd to me, because `StreamContent` has a default buffer size of 4096, which is much smaller than the buffer I actually get when being written to.

If I call `_innerContent.CopyToAsync`, the entire thing is written in one go (even if it's 50MB). If I call `_innerContent.ReadAsStreamAsync(stream)` and then `innerStream.CopyToAsync(stream)` then it's copied in chunks (which is what I'd expect).

**Comment by tintoy** [comment]
Oh, and it's still all written in one go if I use a `MemoryStream`, but not if I use a class derived from `MemoryStream`. I can understand that, though - it's not a real-world use case.

**Comment by stephentoub** [comment]
MemoryStream.CopyToAsync is optimized to avoid needing to allocate an intermediate buffer for the copy; instead it just hands out its internal array in a single WriteAsync call:
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/MemoryStream.cs#L461

If you derive from MemoryStream, you don't get this optimization, because MemoryStream doesn't know whether the derived implementation has overridden Read/ReadAsync to do something special, and thus defers to the default implementation of CopyToAsync, which allocates an intermediate buffer, and repeatedly reads into it from the MemoryStream and write it out to the destination stream:
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/MemoryStream.cs#L440-L445

**Comment by tintoy** [comment]
Cheers, that makes sense.

As far as the `CurlHandler` thing goes, _is_ there meant to be any difference in semantics between `HttpContent.GetStreamAsync().CopyToAsync()` and `HttpContent.CopyToAsync()`? The docs don't really say either way, but I think it might make a difference if `CopyToAsync` is just a convenience method or something else...

**Comment by stephentoub** [comment]
There are some subtle differences.  I'm not sure if there's spelled out anywhere in docs; @davidsh would know.

**Comment by davidsh** [comment]
>As far as the CurlHandler thing goes, is there meant to be any difference in semantics between HttpContent.GetStreamAsync().CopyToAsync() and HttpContent.CopyToAsync()? The docs don't really say either way, but I think it might make a difference if CopyToAsync is just a convenience method or something else...

The end result of calling either is that the HttpContent object is copied (written out to) a destination stream.

However, in most cases and depending on the actual derived `HttpContent` class, calling `HttpContent.CopyToAsync` is going to be more efficient than calling `HttpContent.GetStreamAsync().CopyToAsync()`

In the latter case, it needs to do a stream-to-stream copy.  And depending on the actual stream itself, could be costly as it needs to read some bytes at a time from one stream and write them out to the destination stream.

However, with `HttpContent.CopyToAsync`, the semantics are simply to write the entire content object to a destination stream.  That means that for contents that are really buffers themselves, it can do it via a single write call to the destination stream.

**Comment by tintoy** [comment]
Ok, that makes sense. I'm closing this issue then, because I'm pretty sure I understand why I was seeing the behaviour described.

Thanks for taking the time to write such a detailed explanation - it's been very helpful :)
