### ISSUE TITLE
Move stuff from Tools-Override into BuildTools

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#15092]
As part of the dev/eng work we changed a lot of targets in BuildTools and put them under Tools-Override as well as created a custom CoreFxTools task. All of these need to be moved to BuildTools.

**Comment by joperezr** [comment]
Along with this, we should also remove the current workarounds that we have in place on build.sh and sync.sh that are working around an issue of assembly loading by building the CoreFx.Tools task library as a pre-step. Once this are moved to buildtools on this issue, we should clean up that code from both build.sh and sync.sh

**Comment by weshaggard** [comment]
@dleeapho I think it would be best to work with someone on your team to manage the transition of all the dev/eng work we did in corefx into BuildTools. I recommend we do a major version change of BuildTools at that time which will also force us to figure out a servicing plan for BuildTools. @dleeapho how would you like to track this work?

**Comment by dleeapho** [comment]
@weshaggard Agree. I logged [https://github.com/dotnet/core-eng/issues/502](https://github.com/dotnet/core-eng/issues/502) to track the work on our end.

**Comment by danmosemsft** [comment]
@dleeapho is this still in plan for 2.0 (ZBB 5/10)?

**Comment by dleeapho** [comment]
@danmosemsft I don't think we can get it done by then unless we shift priorities.

**Comment by danmosemsft** [comment]
I'm fine with that, it's just cleanup. Moved to Future.

**Comment by weshaggard** [comment]
I disagree with moving this to future. We will be servicing 2.0 for a long time to come and so at a minimum we need to survey what we have here to ensure we aren't setting ourselves up for trouble once we enter servicing.

**Comment by weshaggard** [comment]
Majority of this is complete with BuildTools PR https://github.com/dotnet/buildtools/pull/1460 and CoreFx PR https://github.com/dotnet/corefx/pull/19007. There is still more clean-up I would like to see happen but I will file individual issues in BuildTools to track those.

**Comment by weshaggard** [comment]
I'm tracking other clean-up items with https://github.com/dotnet/buildtools/issues?q=is%3Aissue+is%3Aopen+label%3A%22BuildTools+Consolidation%22.
