### ISSUE TITLE
Paths with bad colons don't throw ArgumentException

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#15098]
On desktop paths like `C::` would throw `ArgumentException`. In CoreFX we're currently throwing `NotSupportedException`.  (See tests in System.IO.FileSystem.)

The Path class in CoreCLR needs updated.

**Comment by ViktorHofer** [comment]
I'm going to take that issue.

**Comment by danmosemsft** [comment]
@ViktorHofer great. Please include test/s!

**Comment by JeremyKuhne** [comment]
I'll be checking in #15100 today- you'll just need to remove the Issue from the tests once CoreCLR is updated and it is pulled into CoreFX.  To run tests against desktop you need to do this:

```
msbuild System.IO.FileSystem.Tests.builds /t:BuildAndTest /p:FilterToTestTFM=net46
```

Tests should work both with and without the FilterToTestTFM. Note that there are still a few more desktop failures in FileSystem.Tests. Some exceptions not being thrown exactly the same. If you are interested you can try and fix them.  If not, that's ok. (There are some that just aren't providing the argument name on desktop, those should probably just be conditioned appropriately.)

**Comment by ViktorHofer** [comment]
Starting today and hope to finish before TechReady 👨‍💻

**Comment by ianhays** [comment]
@ViktorHofer did you end up making any progress on this issue?

**Comment by ViktorHofer** [comment]
@ianhays Hey Ian, unfortunately not yet. Feb was pretty tough. But now I have dedicated time for this. I need to fix a Prism build issue and after that I will look into that issue again. I will let you know by the end of this week!

**Comment by ViktorHofer** [comment]
@JeremyKuhne Am I missing something or aren't there any tests yet for the Path class? I see the two tests which are flagged with this issue:
- WindowsPathWithIllegalColons (System.IO.FileSystem.Tests.File.Move.cs)
- PathWithInvalidColons_ThrowsArgumentException (System.IO.FileSystem.Tests.Directory.CreateDirectory.cs)

but I don't see any files which are testing the Path class in coreclr mscorlib directly. Just wanna make sure not to oversee anything

**Comment by ianhays** [comment]
@ViktorHofer There are Path tests; they live in [System.Runtime.Extensions](https://github.com/dotnet/corefx/tree/master/src/System.Runtime.Extensions/tests/System/IO). Those tests are testing the Path class that we get from mscorlib.

**Comment by JeremyKuhne** [comment]
This was an unfortunate oversight on my part. :( I actually updated desktop to throw NotSupported in 4.6.2 and above. Tests weren't running against the 4.6.2 TFM. We should probably update tests to make sure we're checking the TFM when running on desktop.

**Comment by ViktorHofer** [comment]
@ianhays thanks for pointing out!
@JeremyKuhne don't bother!

How should we continue now? Of course we need to rewrite the tests and remove the issues from it. That should be a quick fix. Where do we change the TFM for the tests?

I'm willing to fix the tests.

**Comment by ViktorHofer** [comment]
> Tests should work both with and without the FilterToTestTFM. Note that there are still a few more desktop failures in FileSystem.Tests. Some exceptions not being thrown exactly the same. If you are interested you can try and fix them. If not, that's ok. (There are some that just aren't providing the argument name on desktop, those should probably just be conditioned appropriately.)

@JeremyKuhne I can't find any failing tests. As you posted that in January. I'm currently looking through if there are any tests annotated with [Issue] which are already resolved (and already found one).
