### ISSUE TITLE
No waiting on SemaphoreSlim

### ISSUE THREAD

**Issue by denisz1** [dotnet/corefx#15106]
For `SemaphoreSlim`, there are `semaphore.Wait()`, `semaphore.Wait(int)`, `semaphore.WaitAsync()`, etc. methods.

Sometimes it is necessary *to try* obtain the semaphore, *but if it is unavailable then not to wait*. This is a real use case, as evident by the number of StackOverflow posts related to it.

So: `semaphore.Wait(0)` or `semaphore.WaitAsync(0)` or `semaphore.Wait(TimeSpan.Zero)`, etc.

But that is undocumented. If this behavior is allowed, as I assume it is, please document it in the method notes. Until such time we cannot rely on this behavior.

**Comment by stephentoub** [comment]
Wait/WaitAsync with a zero timeout will complete synchronously, either with a value of true if the semaphore could be acquired or a value of false if it would require waiting.  This is supported.  The docs could be improved to explicitly state this, but changing the behavior to anything else would break a bunch of code, including code in corefx itself.
cc: @mairaw

**Comment by benaadams** [comment]
The behaviour is correct (see: https://github.com/dotnet/coreclr/pull/6898)

Are you suggesting a new api `TryWait(...)` and `TryWaitAsync(...)` to indicate it has a return? (Which would just map to `Wait(...)` and `WaitAsync(...)`)

**Comment by stephentoub** [comment]
> Are you suggesting a new api 

I believe he's just asking that the "completes synchronously and quickly" behavior be documented for an input of 0.

**Comment by karelz** [comment]
If you can send me link to the docs which need to change and provide the new wording, I can ask docs team to make the changes.
@denisz1 would that be acceptable resolution of your issue?

**Comment by denisz1** [comment]
@stephentoub @benaadams @karelz No code change is necessary.

My point is that if it's not documented then we are not relying on formal behavior, but on "side effects". So you could one day decide to change the behavior, and that would break our system.

For wording, I think I saw something similar in `Semaphore` or `WaitHandle`? Otherwise something really really simple... it already states what milliseconds of `-1`, and `>0` do, so just add a one liner for the `=0` option.

**Comment by JonHanna** [comment]
I think the current behaviour is pretty much entailed by what is documented—a wait for zero milliseconds is no wait—but it wouldn't hurt to have it spelled out more explicitly. As well as making it clearer, it being pointed out could be somebody's "a ha! that's what I need!" moment.

**Comment by denisz1** [comment]
@JonHanna Maybe I'm not looking at the same docs as you, but it doesn't mention the zero case where I'm looking? Regardless, this is BCL stuff, so I agree with you that it should be "explicit".

**Comment by karelz** [comment]
Can you guys each please link docs you're looking at? Ideally also suggest the wording change.
It will be easier to discuss it from there ...

**Comment by denisz1** [comment]
[For `Semaphore`](https://msdn.microsoft.com/en-us/library/cc190477(v=vs.110).aspx#Remarks) it says: *If timeout is zero, the method does not block. It tests the state of the wait handle and returns immediately.*

[For `SemaphoreSlim.WaitAsync`](https://msdn.microsoft.com/en-us/library/hh462740(v=vs.110).aspx#Syntax) and [`SemaphoreSlim.Wait`](https://msdn.microsoft.com/en-us/library/dd289488(v=vs.110).aspx#Syntax) it should say something very similar (or identical?) There are a number of overloads, so they should all have the same wording.

**Comment by karelz** [comment]
I personally prefer the original wording - IMO it is clearer. I had to think about what does it mean "semaphore is unavailable" ... it sounds like "handle is closed" or something.

I am curious if [`WaitAsync(0)`](https://msdn.microsoft.com/en-us/library/hh462740(v=vs.110).aspx#Syntax) call basically makes the call asynchronous. Is it worth calling out? (more for clarification and explanation what it does)

**Comment by stephentoub** [comment]
> I am curious if WaitAsync(0) call basically makes the call synchronous. 

See the first sentence of my first reply above.

**Comment by karelz** [comment]
Ah, missed that. And I see that you already looped in @mairaw ... thanks!

**Comment by mairaw** [comment]
Can you guys please assign this to me? I'll review the bugs assigned to me here once I work through the backlog of items I have for the release. Thanks!

**Comment by karelz** [comment]
@mairaw you don't have rights to modify issues? Let me fix that ...

**Comment by mairaw** [comment]
Nope @karelz. Thanks!

**Comment by karelz** [comment]
Now you do :)
Please check our [triage rules](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified) - I guess [2] will have exception for documentation bugs which can be fixed only by your team ;-)

**Comment by mairaw** [comment]
Issue moved to [dotnet/docs #1936](https://github.com/dotnet/docs/issues/1936) via [**ZenHub**](https://www.zenhub.com/)

**Comment by karelz** [comment]
Thanks! Appreciate your help with docs!
