### ISSUE TITLE
Conflict-Resolution: NETCore.App is not winning over fat packages for copy-local

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#15110]
In 1.0/1.1 NETCore.App was composed of a mix of fat packages and split packages.

In 2.0 NETCore.App is one big split package.

This means that for a portable app using the shared framework it may see copy-local assets from 1.0/1.1 without seeing any of the newer 2.0 SharedFramework assets to cancel them out.

1. One solution is to make NETCore.App carry metadata (via a generated props file) that lists all the runtime files it represents.  These can be fed into conflict resolution as an independent item.

2. Another solution would be to make MSBuild aware of the contents of the shared framework directly and use these for conflict resolution.

I'm thinking to do 1 since it doesn't involve "searching" for the shared framework.  @eerhardt did you do something similar in publish?  How are you handling filtering now that type/platform doesn't exist.  Seems like a similar problem.

/cc @weshaggard @terrajobst

**Comment by ericstj** [comment]
For 1 I propose the following.

HandlePackageConflicts accepts an item as ExternalCopyLocal.  These items will have metadata for AssemblyVersion, FileVersion, NuGetPackageId, NuGetPackageVersion.  HandlePackageConflicts will first load these items into conflict map for copy local before doing other conflict detection.  When examining these for conflicts we'll skip the exists check.

NETCore.App will generate a props file during build that contains these items for the files that make up the shared framework across all RIDs.

**Comment by eerhardt** [comment]
>  @eerhardt did you do something similar in publish? How are you handling filtering now that type/platform doesn't exist. Seems like a similar problem.

`type: platform` is now specified by an MSBuild property:  `MicrosoftNETPlatformLibrary`, which specifies which library should be treated as the "platform" library.
See https://github.com/dotnet/sdk/blob/a237ed6ee95d3c8438635c13fed12cbccd79da7d/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.targets#L226-L241

Publish looks for this library, and if it finds it, excludes any assets coming from underneath that library.  https://github.com/dotnet/sdk/blob/a237ed6ee95d3c8438635c13fed12cbccd79da7d/src/Tasks/Microsoft.NET.Build.Tasks/ProjectContext.cs#L42-L45

**Comment by ericstj** [comment]
Ah, I see.  Indeed it is very close to the NuGet behavior as it is doing a graph walk of package dependencies  by package ID and excluding those that have been upgraded.  That won't help us here.

Do you have any opinon about option 1 vs 2?  For 2 we'd need some way to determine the path to the shared framework, then we'd pass in all the files in that folder as ExternalCopyLocal and consider them for conflicts.  I'd only consider option 2 if the SDK somewhere already needed to find the shared framework, or if folks thought we had a very stable way of calculating the path. /cc @schellap

**Comment by ericstj** [comment]
> I'd only consider option 2 if the SDK somewhere already needed to find the shared framework

As far as I can tell it does not.

> or if folks thought we had a very stable way of calculating the path

I looked into how the shared framework is located.
First off, it's not garunteed to be there on build which is problematic if we depend on it for build output.  It could mean different results if you have shared framework vs not.  
Second, it's actually determined by which dotnet is on the path https://github.com/dotnet/cli/blob/c50aeb318ed9afed731640033f571e8dd1915e15/src/dotnet/commands/dotnet-run/RunCommand.cs#L87.  So 'dotnet run' examines the project for "RunCommand", which has a default value of dotnet/dotnet.exe.  That will then be invoked and process will find the first one on the path.  So if we relied on this we'd need to do a %path% probe.
https://github.com/dotnet/sdk/issues/20 aims to fix this.  If it were fixed we could use that logic to locate the shared framework.

That said, I think the fact that the shared framework is not garunteed to be present is the deal breaker for me that tips the scales in favor of option 1.  @eerhardt / @terrajobst / @weshaggard  thoughts?

**Comment by weshaggard** [comment]
I agree we shouldn't depend on the shared framework on the box, so I don't like option 2. The thing I don't like about option 1 is we need to know about the contents of all the RID split packages in the identity package which seems unfortunate. If we can figure out a good way to scope and maintain the list in option 1 then I think I could get behind that option.

**Comment by eerhardt** [comment]
Agreed that if possible, we shouldn't rely on the shared framework being installed on the box. @rainersigwald informed me that MSBuild has its own installer, so people can build on build servers.  So if someone ever tried using that MSBuild, the shared framework wouldn't be installed.

**Comment by ericstj** [comment]
@weshaggard I think I can do that.

**Comment by ericstj** [comment]
This was fixed with https://github.com/dotnet/core-setup/commit/a2d19c1921275219fb9322df2dc585195ff0ba12
