### ISSUE TITLE
Remove properties not relevant to code formatting from corefx.vssettings

### ISSUE THREAD

**Issue by davkean** [dotnet/corefx#1511]
Looks like we have a few properties that are unrelated to formatting in corefx.vssettings such as:

```
<PropertyValue name="HighlightReferences">0</PropertyValue>
<PropertyValue name="ProgressDialogDelaySeconds">2</PropertyValue>
```
We should remove them so that only C# formatting settings are in that file.

**Comment by bigodera** [comment]
Hey David.

I'm new here, sorry if I'm asking something that should be asked elsewhere.
Is there an easy way of knowing if the property is related to formatting? I tried to deduce it by reading them, but some names are tricky to me.

Thanks.

**Comment by jasonmalinowski** [comment]
It looks like all the formatting options take the form of names like "Formatting_*", "Indent_*", "NewLines_*", "Space_*", and "Wrapping_". If you're curious, you can look [https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/CSharp/Impl/Options/AutomationObject.cs](at the automation object) which is what maps between the legacy names and our underlying option structures.

**Comment by bigodera** [comment]
Thank you @jasonmalinowski, I'll dig into it.
