### ISSUE TITLE
Make System.Console throw the same Exception on netcore as the full framework

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#15114]
The desktop throw IOException on the follwoing calls:

```C#
        Assert.Throws<IOException>(() => Console.WindowWidth = 0);
        Assert.Throws<IOException>(() => Console.WindowHeight = 0);
```
while netcore throw ArgumentOutOfRangeException

```C#
        Assert.Throws<ArgumentOutOfRangeException>("value", () => Console.WindowWidth = 0);
        Assert.Throws<ArgumentOutOfRangeException>("value", () => Console.WindowHeight = 0);
```
please have a look at the PR #15095 for more info

**Comment by ianhays** [comment]
Full framework throws an ArgumentOutOfRangeException also. I'm not sure why the tests are asserting otherwise. 

[Reference Source](https://referencesource.microsoft.com/#mscorlib/system/console.cs,4474c08a54143211)

I also tested it on .net 4.6 and got an AOoRE.

So the work here is actually to just remove the fullnet specific test.

**Comment by ianhays** [comment]
Looks like we messed up the paramname when we did the switch to nameof in netcore, so thats why the AOoRE test was failing on desktop. Fix coming in a minute.

**Comment by tarekgh** [comment]
@ianhays looks there is something messing here. please loo at 
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170108.02/workItem/System.Console.Tests/analysis/xunit/WindowAndCursorProps~2FWindowWidth_WindowHeight_InvalidSize

the logs shows

```
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.Console.get_WindowHeight()
   at System.Console.set_WindowWidth(Int32 value)
   at WindowAndCursorProps.<>c.<WindowWidth_WindowHeight_InvalidSize>b__2_0() in D:\A\_work\64\s\corefx\src\System.Console\tests\WindowAndCursorProps.cs:line 36
```

**Comment by tarekgh** [comment]
also look at the source 

http://index/?query=System.Console.GetBufferInfo&rightProject=mscorlib&file=system%5Cconsole.cs&line=973

it throws IOException

**Comment by ianhays** [comment]
Thanks Tarek. ```the handle is invalid``` is a different failure entirely and is not the expected result of setting WindowWidth/WindowHeight to 0.

>also look at the source
>it throws IOException

It shouldn't be getting to that point though. It should stop at the check in [SetWindowSize](https://referencesource.microsoft.com/#mscorlib/system/console.cs,4474c08a54143211) where we check against the 0 input.

**Comment by ianhays** [comment]
I fired up a Console app with this and got an ArgumentOutOfRangeException.

I see where it's failing, but getting the `WindowHeight` shouldn't be throwing an IOException for this test. It is hiding what we're actually testing. I'm not too familiar with how we run these tests against the full framework - is the Console redirected?

**Comment by tarekgh** [comment]
from the stack looks the WindowHeight is the one throwing. so it looks the console window somehow was missed up.

**Comment by ianhays** [comment]
>from the stack looks the WindowHeight is the one throwing. so it looks the console window somehow was missed up.

Yeah. The Setter calls the getter which fails from an IOException before the value being set gets a chance to hit the SetWindowSize check for valid input.

**Comment by tarekgh** [comment]
as you said the console handle was invalid so the question why the handle got invalid during the test?

**Comment by tarekgh** [comment]
actually the handle should be valid. it looks what is failed in the pinvoke call

GetConsoleScreenBufferInfo
