### ISSUE TITLE
Test Failure: System.IO.Tests.Directory_SetCurrentDirectory.SetToValidOtherDirectory

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#15127]
Encountered this random failure in an unrelated PR under Centos

dotnet_corefx/master/centos7.1_release_prtest 2060 	centos71-20160929-f983f0 	01/11 04:35 PM 	steveharter 	15072

MESSAGE: Assert.Equal() Failure
Expected: 42
Actual: 255
STACK TRACE: at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() in
/mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_release_prtest/src/Common/tests/System/Diagnostics/RemoteExecutorTestBase.cs:line 164

**Comment by danmosemsft** [comment]
```
            RemoteInvoke(() =>
            {
                Directory.SetCurrentDirectory(TestDirectory);
                // On OSX, the temp directory /tmp/ is a symlink to /private/tmp, so setting the current
                // directory to a symlinked path will result in GetCurrentDirectory returning the absolute
                // path that followed the symlink.
                if (!RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
                {
                    Assert.Equal(TestDirectory, Directory.GetCurrentDirectory());
                }
                return SuccessExitCode; // =42, but returning 255
            }).Dispose();
```

It's not clear what the return code 255 means. Apparently on linux, it is an invalid code.

**Comment by danmosemsft** [comment]
I'm going to call this unactionable. If it happens repeatedly, we can consider logging or trying to repro locally.
@JeremyKuhne @ianhays fyi.

**Comment by dagood** [comment]
Seemed to repro on OSX release/1.1.0 in https://github.com/dotnet/corefx/pull/15634: https://ci.dot.net/job/dotnet_corefx/job/release_1.1.0/job/osx_debug_prtest/195/testReport/junit/System.IO.Tests/Directory_SetCurrentDirectory/SetToValidOtherDirectory/
