### ISSUE TITLE
dotnet build on NFS: Access to the path '.SDKVersion' is denied.

### ISSUE THREAD

**Issue by couven92** [dotnet/corefx#15120]
Re-issue of https://github.com/dotnet/cli/issues/4227

# Problem

The following problem occurs when attempting to build a dotnet project in Ubuntu when the project to build is located on a network file system.

When I run `dotnet build -f netstandard1.6` on any project, `dotnet build` returns the following output:

```
Project projectname (.NETStandard,Version=v1.6) will be compiled because expected outputs are missing
Compiling projectname for .NETStandard,Version=v1.6
Access to the path '/mnt/users/username/Documents/Source/projectsolution/src/projectname/obj/Debug/netstandard1.6/.SDKVersion' is denied.
```

However, when I run `ls -lah` with the path shown above, it shows me that the file is accessible (at least for me):

```
-rwxr--r-- 1 username usergroup 0 sep.  22 11:31 /mnt/users/username/Documents/Source/projectsolution/src/projectname/obj/Debug/netstandard1.6/.SDKVersion*
```

I am also able to open, edit and delete the file in the file explorer, with `gedit`, with `vim` or other usual tools.

Running `chmod a+rwx` on the file, so that all access right are granted does also not solve the problem.

In this case the project files are located on a NFS file system that is mounted in ubuntu. Any other program like `vim` or `git` that create dotfiles (files that start with `.`) work fine.
# Workaround

If I supply a path in `/tmp` with the `-b` option, the build runs successfully.
# Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-003555)

Product Information:
 Version:            1.0.0-preview3-003555
 Commit SHA-1 hash:  a2b861e4c8

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
```

@kosak gives a good debug startin point in https://github.com/dotnet/cli/issues/4227#issuecomment-253938255

**Comment by ianhays** [comment]
We call flock in the Unix PAL on opening of a FileStream, but we don't throw any errors if the flock fails in this manner.

[Here's the lock code where we only throw an exception if we get EWOULDBLOCK](https://github.com/dotnet/coreclr/blob/7faacd90b77514c4a07ba74fd221d0d968f89135/src/mscorlib/corefx/System/IO/FileStream.Unix.cs#L74). Since @kosak wasn't receiving an EWOULDBLOCK, it seems likely the issue is elsewhere.

Does the error from `dotnet` occur on every instance or only sometimes? Does it occur after doing a clean?

**Comment by ianhays** [comment]
We also call flock on [the handle release](https://github.com/dotnet/coreclr/blob/81c42cecca5e1b0b802d4df980280750d2e1419e/src/mscorlib/corefx/Microsoft/Win32/SafeHandles/SafeFileHandle.Unix.cs#L95), but we don't throw on error there for any errno.

**Comment by couven92** [comment]
I haven't tested this extensively (since I sit in Windows most of the time), but I can try compiling every single dotnet project I have and see what happens...

**Comment by ianhays** [comment]
@couven92 any update here? Were you able to determine the cause of your issues?

**Comment by couven92** [comment]
With the new SDK (version `1.0.1`) it looks like it works now...

**Comment by kosak** [comment]
Great news! Many thanks to whoever fixed this!

**Comment by ianhays** [comment]
Glad you guys got it working. Cheers.

**Comment by karelz** [comment]
@ianhays did we change anything in CoreFX? If not, then likely CLI made some fix impacting the scenario ...
