### ISSUE TITLE
System.Collections.Immutable and APTCA/SecurityTransparentAttribute

### ISSUE THREAD

**Issue by mkosieradzki** [dotnet/corefx#1512]
If possible please add one of attributes forcing assembly to be Security Transparent (AllowPartiallyTrustedCallersAttribute or SecurityTransparentAttribute).

This will help using this library in some quite uncommon partial trust scenarios.

**Comment by morganbr** [comment]
As I mentioned in #3293, making it transparent sounds reasonable to me.
