### ISSUE TITLE
Cannot run tests against specific desktop TFMs

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#15136]
You can specify a [particular config file](https://github.com/xunit/xunit/blob/master/src/xunit.console/CommandLine.cs#L116) with the xunit console runner. When we run against a particular TFM we should be generating the right config so the appropriate compat switches (quirks) are set.

**Comment by JeremyKuhne** [comment]
@joperezr, @alexghi, @tarekgh

**Comment by davidsh** [comment]
This will be required in order to properly test against .NET Framework (Desktop).  Desktop code, for example, has different quirked behavior depending on the TFM.   See #15145

**Comment by weshaggard** [comment]
cc @safern

**Comment by ViktorHofer** [comment]
Closing for age. Please reopen if you think we still need to address this.
