### ISSUE TITLE
Add String.Split overloads that take a single char and string separator

### ISSUE THREAD

**Issue by justinvp** [dotnet/corefx#1513]
It's extremely common to split a string based on a single `char` or `string` separator, yet `String.Split` only offers overloads that accept an array of separators. The `params char[] separator` overload is particularly insidious as the `params` usage often results in a large number of unnecessary `char[]` heap allocations, unbeknownst to the developer.

## Rationale and Usage

[Stack Exchange ran into this](http://blog.marcgravell.com/2013/11/allocaction-allocation-allocation.html) (significant number of separator arrays in memory) and submitted a [pull request](https://aspnetwebstack.codeplex.com/SourceControl/network/forks/marcgravell/outputcachecleanup/contribution/7201) to ASP.NET MVC to cache `String.Split` separator arrays inside the ASP.NET MVC codebase.

They ended up with the following:

```c#
namespace System.Web.Mvc
{
    internal static class StringSplits
    {
        // note array contents not technically read-only; just... don't edit them!
        internal static readonly char[]
            Period = new[] { '.' },
            Comma = new[] { ',' };
    }
}
```

With uses of `string.Split('.')` and `string.Split(',')` replaced with `string.Split(StringSplits.Period)` and `string.Split(StringSplits.Comma)` to avoid the `char[]` allocations.

It'd be awesome if `String.Split` offered overloads that accepted a single separator to avoid this.

## Proposed API

```c#
public partial class String
{
    // Proposed methods
    public string[] Split(char separator, StringSplitOptions options = StringSplitOptions.None);
    public string[] Split(char separator, int count, StringSplitOptions options = StringSplitOptions.None);
    public string[] Split(string separator, StringSplitOptions options = StringSplitOptions.None);
    public string[] Split(string separator, int count, StringSplitOptions options = StringSplitOptions.None);

    // Existing methods
    public string[] Split(params char[] separator);
    public string[] Split(char[] separator, int count);
    public string[] Split(char[] separator, StringSplitOptions options);
    public string[] Split(char[] separator, int count, StringSplitOptions options);
    public string[] Split(string[] separator, StringSplitOptions options);
    public string[] Split(string[] separator, int count, StringSplitOptions options);
}
```

## Notes

We had wanted to add `public string[] Split(string separator)`, but this breaks source compatibility with uses of `Split(null)`, which is documented to split based on white space, because it makes the call ambiguous between `Split(char[])` and `Split(string)`.

I won't go into it here as it's really a separate feature request, but it would also be worth considering new `Split` methods that return a `struct` collection of `StringSpan`/`StringSegment` structs (in lieu of internal runtime span/substring magic) to avoid the resulting `string[]` allocation (and substring allocations, unless needed).

I'd be happy to contribute an implementation and tests.

**Comment by ellismg** [comment]
> I won't go into it here as it's really a separate feature request, but it would also be worth considering new `Split` methods that return a `struct` collection of `StringSpan`/`StringSegment` structs (in lieu of internal runtime span/substring magic) to avoid the resulting `string[]` allocation (and substring allocations, unless needed).

Please open an issue on this.  We have been talking about it from time to time internally (and I've done a fair amount of thinking and prototyping) but we should open the discussion up.  There are lots of interesting issues to consider.

**Comment by ellismg** [comment]
I think this would be a great addition to the framework.

**Comment by svick** [comment]
Depending on if and how [slices](dotnet/roslyn#120) are implemented, that `StringSpan` version might not be necessary, I think.

**Comment by weshaggard** [comment]
@justinvp I think these are some reasonable asks and I think the discussion should happen here in the corefx repo regardless of whether we end up putting these directly on string in the coreclr repo or not.

I also like the other idea of a generally more efficient string split that uses structs and agree that it should be a separate issue but it is worth mentioning here and considering it along with these to have a more holistic look at our different split options. 

One question I wonder about this is do you have any numbers that show how much of an improvement something like this might have? Knowing that split is really bad about allocations is the actual params array really going to show as much of an improvement in the overall amount of allocations that occur or will it just be a tiny improvement and switching to the struct split is ultimately what people should do to get the performance they need. In other words is the params array 1 of 20 allocations or 1 of 2 allocations in this code. I suspect it depends on the number of items that end up in the split string array but it is worth thinking about.

**Comment by mattwarren** [comment]
+1 from me. 

I like the general trend I see of new work in .NET. There seems to be a converted effort to ensure there are as few allocations as possible (i.e. stuff like this https://github.com/dotnet/corefxlab/wiki)

**Comment by pharring** [comment]
string.Split is an awful allocation hog and I've learned to avoid it. Not only the params char[] args and the obvious returned array, but the implementation allocates an int[] for all the split locations.
Often, string.Split is unnecessary. Iteration with string.IndexOf is allocation free and, if you really need substrings, well those allocations are unavoidable.

I think an alternative API which returns a struct-based enumerator of spans would be ideal - similar to the note in the proposal. It would encourage people to think more of "parsing" and less about "splitting".

**Comment by krwq** [comment]
While I agree on a single character overload, the string overload is not obvious to me. I.e.: What is the expected result of "aaabaaabaaa".Split("aa")? ["", "ab", "ab", "a"] or rather ["a", "b", "ab", "a"]?

**Comment by mgravell** [comment]
What @pharring says here makes a lot  of sense - especially with the immutability of strings making it trivially repeatable; a custom struct iterator would be *virtually* free (until, of  course, someone uses LINQ on it, causing it to box - but hey; we can't have everything).

**Comment by pharring** [comment]
@krwq the matching rules for the string overload would be the same as they are today with the char[] version. The string is just an alternative way of packaging the set of separator chars. Repeated chars are ignored.

**Comment by krwq** [comment]
@pharring, in this case I don't think this API is a good idea. In my opinion it is gonna be confusing with splitting a string by separator which is string. I'd rather have slow API which intentions are clear. Can we expose some non allocating API which gives you ImmutableArray<char> from string which will have a char[] underneath which we can consume without new allocations? Besides we usually call Split quite rarely so what's the point on saving few nanoseconds/bytes per instance?

**Comment by davkean** [comment]
@krwq I don't understand your concern, this proposal does not add any new features to String.Split. As @pharring mentioned, this is just a way to avoid the initial allocation of passing the separators to String.Split.

Introducing a new non-allocating String.Split is a great idea that we've talked about a lot in the past, however, it should be treated separably to this proposal and not as an "either or".

**Comment by ellismg** [comment]
@pharring @krwq I would assume the string versions would just be aliases for the string[] versions.  In this case:

```csharp
"aaabaaabaaa".Split("aa")
```

behaves the same way as

```csharp
"aaabaaabaaa".Split(new string[] { "aa" }, StringSplitOptions.None)
```

So you would get:

```csharp
"", "ab" , "ab", "a"
```

**Comment by eatdrinksleepcode** [comment]
I think what @krwq is saying is that if the method call is "Split(String separator)", it is not clear whether the separator is a single multi-character separator or a collection of single-character separators expressed as a string.

I agree that this would be confusing and would prefer that it not be included. Despite the fact that String implements IEnumerable<Char>, I can't think of another API that treats a string as a collection of characters in this way.

**Comment by ellismg** [comment]
> I think what @krwq is saying is that if the method call is "Split(String separator)", it is not clear whether the separator is a single multi-character separator or a collection of single-character separators expressed as a string.

I would have expected that most folks would assume that 

```csharp
"this, is, a, string, with some spaces".Split(", ");
```

is going to give you back

```csharp
"this", "is", "a", "string", "with some spaces"
```

and not

```csharp
"this", "", "is", "", "a", "", "string", "", "with", "some", "spaces"
```

I could maybe buy the argument if we didn't have any existing overloads of Split that took strings, but we already have clear semantics for how to split using one or more strings as a splitter.

**Comment by eatdrinksleepcode** [comment]
@ellismg I agree with your interpretation, but @pharring's explanation seems to indicate otherwise.

**Comment by pharring** [comment]
I'm no authority. I was just trying to interpret the proposal and reply to krwq. To be honest, I didn't even realize we already had the string[] overloads (shows how much I avoid string.Split in the first place).

**Comment by terrajobst** [comment]
We [reviewed this issue today](https://github.com/dotnet/apireviews/tree/master/2015-04-28-misc#1513-add-stringsplit-overloads-that-take-a-single-char-and-string-separator). It looks good as proposed.

**Comment by ellismg** [comment]
@justinvp This is all yours.  Tagging as "Grabbed by community"

**Comment by davkean** [comment]
Justin, I'd look what we did with String.Format and [ParamsArray](https://github.com/dotnet/coreclr/blob/cbf46fb0b6a0b209ed1caf4a680910b383e68cba/src/mscorlib/src/System/ParamsArray.cs) to generically handle a single element and an array without requiring to write the algorithm twice. In the meeting we also talked about looking to see how common it was (I'll pull the data) to handle 2 - 3 separators, in which we could consider special casing them as well.

**Comment by justinvp** [comment]
FYI, I added an initial PR for a single char and string separator here: dotnet/coreclr/pull/895

I didn't include overloads for 2-3 separators in the PR. However, I did take a quick look at the current uses of `Split` at http://referencesource.microsoft.com. I didn't gather actual numbers, but it looks like a single `char` separator is by far the most common, with a good number of 2-3 separators. If we want overloads for the 2-3 separators cases, I can update the PR.

**Comment by weshaggard** [comment]
Keeping this issue open to track exposing the APIs and removing the extension methods in the tests (https://github.com/dotnet/corefx/blob/22835e2e02839ca8856327232c6153b64ec5675a/src/System.Runtime/tests/System/String.SplitTests.cs#L10).

**Comment by justinvp** [comment]
@weshaggard, should this issue be tagged with api-needs-exposed?

**Comment by weshaggard** [comment]
yes tagged.

**Comment by weshaggard** [comment]
@justinvp after your change mirrored internally we found that one of your new overloads caused a source compat issue. In particular we had code that called `s.Split(null)` which is documented to split based on white space. However now with your new `Split(string separator)` overload that causes an ambiguous reference with 'Split(params char[])` overload. We are going to have to fix this in some way.

**Comment by justinvp** [comment]
That's unfortunate: I suggest the following fix:

Get rid of this new overload:

```c#
public string[] Split(string separator);
```

That would leave us with:

```c#
public sealed class String : ...
{
    // Proposed methods
    public string[] Split(char separator);
    public string[] Split(char separator, StringSplitOptions options);
    public string[] Split(char separator, int count, StringSplitOptions options);
    public string[] Split(string separator, StringSplitOptions options);
    public string[] Split(string separator, int count, StringSplitOptions options);

    // Existing methods
    public string[] Split(params char[] separator);
    public string[] Split(char[] separator, int count);
    public string[] Split(char[] separator, StringSplitOptions options);
    public string[] Split(char[] separator, int count, StringSplitOptions options);
    public string[] Split(string[] separator, StringSplitOptions options);
    public string[] Split(string[] separator, int count, StringSplitOptions options);

    ...
}
```

If that looks good to you, I'll submit a fix to CoreCLR and then update the CoreFX tests.

**Comment by terrajobst** [comment]
I think that's the best option. Sadly, this was also one most useful overloads!

**Comment by justinvp** [comment]
https://github.com/dotnet/coreclr/pull/6928

**Comment by svick** [comment]
Would it make sense to use some sort of trickery to bring the `string` overload back without breaking compatibility?

The option that comes to mind is to use optional parameter. Specifically, change:

```c#
public string[] Split(string separator, StringSplitOptions options);
```

into:

```c#
public string[] Split(string separator, StringSplitOptions options = StringSplitOptions.None);
```

This way, `s.Split(null)` would still call the `char[]` overload (maintaining compatibility), and `s.Split(someString)` would also work (and would actually compile into `s.Split(someString, StringSplitOptions.None)`.

**Comment by weshaggard** [comment]
@svick that is an interesting idea. I would need to verify if that actually works but if it does I like it.

**Comment by terrajobst** [comment]
I'd be surprised if it does; the compiler doesn't not which overload existed before...

**Comment by svick** [comment]
@terrajobst It's not about that. When you write `s.Split(null)` and the compiler has the following two overloads to choose from:

```c#
public string[] Split(params char[] separator);
public string[] Split(string separator, StringSplitOptions options = StringSplitOptions.None);
```

Then it will choose the `char[]` overload, because of [this rule](https://github.com/ljw1004/csharpspec/blob/gh-pages/expressions.md#better-function-member):

> if all parameters of `Mp` have a corresponding argument whereas default arguments need to be substituted for at least one optional parameter in `Mq` then `Mp` is better than `Mq`.

**Comment by justinvp** [comment]
@svick interesting idea. Does it work in VB? F#? (Are there any other CLR languages we care about?)

**Comment by svick** [comment]
@justinvp Based on a quick test, it does seem to work in VB and F#.

Interestingly, VB does not report ambiguity error (and chooses the `char[]` overload) even with the original code (i.e. without the optional parameter), not sure why (haven't checked the spec).

**Comment by justinvp** [comment]
@weshaggard, @terrajobst,

Should we go with @svick's optional parameter idea? If yes, that leaves us with:

```c#
// Proposed methods
public string[] Split(char separator);
public string[] Split(char separator, StringSplitOptions options);
public string[] Split(char separator, int count, StringSplitOptions options);
public string[] Split(string separator, StringSplitOptions options = StringSplitOptions.None);
public string[] Split(string separator, int count, StringSplitOptions options);
```

A) For consistency between `string` and `char`, should we make the new single `char` overload use an optional parameter as well? e.g.:

```c#
// Proposed methods
public string[] Split(char separator, StringSplitOptions options = StringSplitOptions.None);
public string[] Split(char separator, int count, StringSplitOptions options);
public string[] Split(string separator, StringSplitOptions options = StringSplitOptions.None);
public string[] Split(string separator, int count, StringSplitOptions options);
```

B) If yes to A, should we also make `options` optional in the overloads with the `count` parameter? e.g.:

```c#
// Proposed methods
public string[] Split(char separator, StringSplitOptions options = StringSplitOptions.None);
public string[] Split(char separator, int count, StringSplitOptions options = StringSplitOptions.None);
public string[] Split(string separator, StringSplitOptions options = StringSplitOptions.None);
public string[] Split(string separator, int count, StringSplitOptions options = StringSplitOptions.None);
```

C) If yes to B, should we make `count` optional and collapse the overloads? e.g.:

```c#
// Proposed methods
public string[] Split(char separator, int count = int.MaxValue, StringSplitOptions options = StringSplitOptions.None);
public string[] Split(string separator, int count = int.MaxValue, StringSplitOptions options = StringSplitOptions.None);
```

Personally, I think C goes a bit too far with the optionals. I prefer B because B more closely aligns with the existing `Split` methods where you can call `Split(sep, options)` without having to specify the `options` param name (e.g. `Split(sep, options: options)`), which is what you'd have to do if we went with C.

Here's what B looks like with the existing methods:

```c#
// Proposed methods
public string[] Split(char separator, StringSplitOptions options = StringSplitOptions.None);
public string[] Split(char separator, int count, StringSplitOptions options = StringSplitOptions.None);
public string[] Split(string separator, StringSplitOptions options = StringSplitOptions.None);
public string[] Split(string separator, int count, StringSplitOptions options = StringSplitOptions.None);

// Existing methods
public string[] Split(params char[] separator);
public string[] Split(char[] separator, int count);
public string[] Split(char[] separator, StringSplitOptions options);
public string[] Split(char[] separator, int count, StringSplitOptions options);
public string[] Split(string[] separator, StringSplitOptions options);
public string[] Split(string[] separator, int count, StringSplitOptions options);
```

B+) Which begs the question... Would it be possible to modify the existing `string[]` methods to make `options` optional? It'd be a compatible change, right? e.g.:

```c#
// Proposed methods
public string[] Split(char separator, StringSplitOptions options = StringSplitOptions.None);
public string[] Split(char separator, int count, StringSplitOptions options = StringSplitOptions.None);
public string[] Split(string separator, StringSplitOptions options = StringSplitOptions.None);
public string[] Split(string separator, int count, StringSplitOptions options = StringSplitOptions.None);

// Modified existing methods
public string[] Split(string[] separator, StringSplitOptions options = StringSplitOptions.None);
public string[] Split(string[] separator, int count, StringSplitOptions options = StringSplitOptions.None);

// Existing methods
public string[] Split(params char[] separator);
public string[] Split(char[] separator, int count);
public string[] Split(char[] separator, StringSplitOptions options);
public string[] Split(char[] separator, int count, StringSplitOptions options);
```

B+ would making calling `Split` consistent across the board. You'd be able to call `Split(new string[] { "1", "2" })` without having to specify `options`, just like you can already call `Split(new char[] { '1', '2' })` without having to specify `options`, and just like how you'll be able to call the new `Split("1")` and `Split('1')` methods without having to specify `options`. The same goes for calling `Split` with `count` without having to specify `options`.

**Comment by weshaggard** [comment]
That is a lot of options to consider. I marked this as api-ready-for-review so it will show up in our triage query again and we will review at our next review meeting (usually every Tuesday morning).

**Comment by terrajobst** [comment]
We've decided to go with option B. Technically, that means calls like this:

```
Split(null, StringSplitOptions.None)
```

are still ambiguous, but we accept that because that's already the case for the API shape as it was shipped.

**Comment by justinvp** [comment]
Thanks, Immo. CoreCLR PR here: https://github.com/dotnet/coreclr/pull/7175

**Comment by karelz** [comment]
What's remaining to close it?

**Comment by justinvp** [comment]
Hi Karel! Long time no see 😃. I opened #12495 to expose these in netcoreapp1.1. Once that's merged, I think we can close this, assuming it doesn't need to stay open to track adding to the desktop framework and mono.

**Comment by karelz** [comment]
Hey Justin, good to see you here :).
Thanks for your changes. We can close it with your PR. Porting to other platforms will be taken care of by the netfx-port-consider tag.
