### ISSUE TITLE
Fix projects that have be renamed to .disabled

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#15148]
@mellinoe @joperezr as part of the bring-up it looks like you guys renamed some projects to ".disabled" We need to work on re-enabling those. 

I found the following from a quick search:

```
mscorlib.WinRT-Facade.csproj.disabled
System.Net.Http.Rtc.csproj.disabled
System.Numerics.Vectors.WindowsRuntime.csproj.disabled
XsltScenarios.Tests.csproj.disabled
System.Runtime.WindowsRuntime.csproj.disabled
System.Runtime.WindowsRuntime.UI.Xaml.csproj.disabled
```

**Comment by weshaggard** [comment]
@sepidehMS Do you know what the deal is with corefx/src/System.Private.Xml/tests/Xslt/XsltScenarios/XsltScenarios.Tests.csproj.disabled? Should that test project be deleted or fixed?

**Comment by sepidehMS** [comment]
@weshaggard This test project used to embed a pre-generated dll when it was on Desktop. For that reason, we never actually ported these tests to Core. If we want to fix it, we would have to basically re-write the tests to not use a dll. So, we can delete this and have the work done as part of https://github.com/dotnet/corefx/issues/16336.

**Comment by weshaggard** [comment]
@sepidehMS Thanks. I will delete this project which doesn't have any files that work as part of my clean-up of the .disabled files. Feel free to add it or another project back when you work on the xml tests.

**Comment by joperezr** [comment]
I did re-enable a bunch of these when I added the uap and uapaot verticals back, just as an FYI.

**Comment by weshaggard** [comment]
I just deleted the xsltScenarios.Tests.csproj.disabled and I removed the mscorlib.WinRt.Facade project earlier. So there are no more .disabled projects so closing this issue.
