### ISSUE TITLE
openSUSE 13.2 builds time out frequently.

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#15151]
While I was looking at some other stuff, I noticed that it looks like the runs of openSUSE 13.2 hang from time to time when running tests.  See https://ci.dot.net/job/dotnet_corefx/job/master/job/opensuse13.2_release/.  Some jobs complete but others timeout (and then the logic to kill everything makes it look like MSBuild is failing).

It isn't 100% reproducible, as some builds do complete without issue.  I can't see when this started (the history doesn't go back far enough to see when this started).

**Comment by weshaggard** [comment]
We no longer do these builds.
