### ISSUE TITLE
Running into proxy issues with init-tools & build-managed

### ISSUE THREAD

**Issue by peterwurzinger** [dotnet/corefx#15160]
Hi!

The precondition is, that I'm sitting in a cooperate network with some kind of proxy/firewall - combination dropping all traffic not routed through it. Authentication method is Windows/NTLM (i guess..?).
I cloned the repository yesterday and tried to build it but did not get far with that. In my opinion there are (as far as I can tell) two sources leading to a similar problem:

1) While executing `init-tools` for the first time i ran into proxy issues while downloading the .zip-file containing the current CLI/dotnet.exe. I could work around this by enriching the download-call in the `init-tools.cmd `- file with some proxy-parameter-love.

2) Later in the build process when calling `build-managed`, the target "VerifyDependencies" from Tools/Microsoft.DotNet.Build.Tasks.dll (called from VersionTools.targets) uses a WebClient without any proxy parameters. Result is a System.Net.WebException "(407) Proxy authentication required".

`build-native `worked fine btw! (Or at least did not show up with some fancy red errors ^^)

Is working behind a Proxy not supported at all or did I do something wrong/missed a point?

Thanks!
Peter

**Comment by karelz** [comment]
@mellinoe @weshaggard any idea?

**Comment by weshaggard** [comment]
These both sound like good things for us to fix. Init-tools could be fixed in the repo and the VerifyDependencies needs to be fixed in our BuildTools repo.

**Comment by jlanng** [comment]
Hi @karelz, I can look at this.

I'd expect HTTP_PROXY / HTTPS_PROXY environment variables to be respected by the build process.  Would that work?

**Comment by weshaggard** [comment]
I don't know about those environment variables but I would hope we don't need them. We fixed part of this issue in the past with https://github.com/dotnet/corefx/pull/1798 but we have regressed it in the a few places so we should try to update the places in init-tools.cmd and the VerifyDependencies task to make sure we setting up the default proxy and passing the credentials.

**Comment by jlanng** [comment]
Those two seem to be the standard cross-platform means of overriding the default proxy config.  Anyone who uses NPM or Git in this sort of environment would have them set.  Perhaps this is more of a future refinement.

At present buildtools, corefx and coreclr won't build from behind a proxy (I haven't checked any others).

I think the root problem is that there's no  standard piece of code for downloading files.  Sometimes we use WebClient, sometimes it's Invoke-WebRequest, and in places there's also retry with back-off.  Would it make sense to have one PS script for downloading a file that can be referenced from everywhere?

**Comment by weshaggard** [comment]
>I think the root problem is that there's no standard piece of code for downloading files.

Agreed.

>Would it make sense to have one PS script for downloading a file that can be referenced from everywhere?

Unfortunately we don't want to use a PS script anywhere we download something. In fact the only place we want to use a PS script is to get our initial toolset. Everything else should be using C# code in our msbuild task libraries. In our task libraries though we could have a common one and then one-and-only-one PS script that downloads stuff.

**Comment by jlanng** [comment]
OK so I worked backwards, and the problem goes all the way to dotnet-install.ps1 in CLI.  This file is often grabbed and run directly, so I can see how a local fix there is appropriate. I've submitted a PR for that [here](https://github.com/dotnet/cli/pull/6563)

The next one is the BuildTools build itself, which from run.ps1 calls Invoke-WebRequest to download bootstrap.ps1 from the the buildtools HEAD.  This prevents it from working behind a corporate proxy.  Just so I understand, are you saying it should call an MSBuild task locally from within run.ps1, or should run.ps1 be reworked to an msbuild script. Or am I misunderstanding?

As an aside - do you know why run.ps1 downloads bootstrap.ps1 from HEAD? Surely builds should be repeatable with the same result for any given commit?

Cheers

**Comment by weshaggard** [comment]
> Just so I understand, are you saying it should call an MSBuild task locally from within run.ps1, or should run.ps1 be reworked to an msbuild script? 

No the PS scripts cannot directly call msbuild. However the PS scripts should only be downloading the initial set of tools (i.e. the CLI/SDK). However anything that downloads stuff as part of our tools should be doing it via an msbuild task. 

Now the difference between init-tools.cmd and run.ps1. The BuildTools repo itself is using a newer set of bootstrapping scripts that we are testing which does the downloading via run.ps1 and bootstrap.ps1. Were as corefx is still doing that in init-tools. We will eventually move corefx to a similar bootstrap.ps1 model but that won't happen for a little while. Feel free to submit PR's to both set of scripts. 

@jlanng thanks for taking an interest and helping update these scripts.

**Comment by wtgodbe** [comment]
This is redundant with the run tool & init-tools going away soon, closing.
