### ISSUE TITLE
Need easier way to find out where dotnet host is

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#15168]
Today I very frequently cd into the test execution directory and use corerun from that directory to run xunit.console.netcore.exe and the tests library. With the changes in dev/eng, the test folder no longer contains corerun or any other host, which means I need to know where the host is I should use to achieve the same thing.  How do I do this?

cc: @weshaggard, @karajas

**Comment by karajas** [comment]
Currently the host is installed in Tools/testdotnetcli (defined in dir.props) so hopefully the idea is whenever you want a version of the host you have it in the Tools directory (either the one used to restore and the one to test) . Do you think it makes sense to have a "where host" command in the run tool or something similar? The RunTests.cmd command prints out where the host is when run.

**Comment by stephentoub** [comment]
Yes, some way to just get the full path to the location would be helpful. Thanks.

**Comment by weshaggard** [comment]
Do you just want to document the full path or do you want a wrapper script that will run it with a shorter command?

**Comment by stephentoub** [comment]
I'd be fine if there was an easy way for it to just give me the full path.  Often I actually want to muck with stuff in that directory, e.g. overwrite some of the .dlls with other ones before I run a command.

**Comment by weshaggard** [comment]
Don't you get that from the console output when you do a `msbuild /t:rebuildandtest` that is what I generally use to find where tests are running from.

**Comment by stephentoub** [comment]
Sorry, I got conversations confused.  It's not just the host I care about.  It's also where the other binaries for the platform are coming from.  So I need the host, and yeah, that is output by doing "msbuild /t:rebuildandtest", though I need to hunt for it in the spew of output that gets generated (and also run the tests).  But the path to where the binaries are coming from (e.g. ```C:\Users\stoub\Source\Repos\corefx\Tools\testdotnetcli\shared\Microsoft.NETCore.App\9.9.9```) is nowhere to be found in that output, and often I want to overwrite some of those binaries before I run tests.

**Comment by karajas** [comment]
The files in the shared framework are currently hardlinked to the bin dir that corresponds to the build configuration that you are trying to run for. I am working now will just hardlink the entire directory instead of individual files. I'll make sure to double check the rebuildandtest scenario for a single library.

**Comment by weshaggard** [comment]
Here is what I see  in the output for what is running. 
```
 D:\git\corefx\bin/Windows_NT.AnyCPU.Debug/System.Threading.Overlapped.Tests/netstandard//RunTests.cmd D:\git\corefx\bin/runtime/netcoreapp-Windows_NT-Debug-x64/
 Using D:\git\corefx\bin\runtime\netcoreapp-Windows_NT-Debug-x64\ as the test runtime folder.
 Executing in D:\git\corefx\bin\Windows_NT.AnyCPU.Debug\System.Threading.Overlapped.Tests\netstandard\
 Running tests... Start time: 15:36:32.45
 Command(s):
 call D:\git\corefx\Tools/testdotnetcli\dotnet.exe D:\git\corefx\bin/Windows_NT.AnyCPU.Debug/System.Threading.Overlapped.Tests/netstandard/\xunit.console.netcore.exe System.Threading.Overlapped.Tests.dll  -noshadow  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests  -notrait category=OuterLoop -notrait category=fail
```

While it isn't direct you can see that the argument that is passed to RunTests.cmd is the path of the shared runtime which is the part that is interesting. My hope is that folks will eventually learn which shared runtime folder to go manually update if they want to change things. The nice thing is that it is only one folder now instead of every test folder.

**Comment by mellinoe** [comment]
> and often I want to overwrite some of those binaries before I run tests.

Just in case you didn't know (and for others consuming these new changes), the tests all share a single runtime directory, with a single set of binaries. They aren't duplicated into an isolated test directory now, so any changes you make to those binaries will affect the other tests, and I think you'll need to re-run the original source build to recover the files, unless I misunderstood where and how we are hard-linking these files around.

As an aside, and I think I mentioned this to you last week, @karajas , but I think we should move the "testdotnetcli" folder into `bin`, personally. It makes more sense (at least to me) for it to be there.

**Comment by stephentoub** [comment]
> you can see that the argument that is passed to RunTests.cmd is the path of the shared runtime which is the part that is interesting

I don't understand; how do I get from ```c:\users\stoub\Source\Repos\corefx\bin/runtime/netcoreapp-Windows_NT-Debug-x64/``` to ```C:\Users\stoub\Source\Repos\corefx\Tools\testdotnetcli\shared\Microsoft.NETCore.App\9.9.9```?

> My hope is that folks will eventually learn which shared runtime folder to go manually update if they want to change things

Not sure how I learn that without being told it.

> The nice thing is that it is only one folder now instead of every test folder.

FWIW, for my use cases, that's actually a downside.  99% of the time I'm working on a single library and only want to experiment with changes as they impact a single library; I could delete and replace binaries in its execution directory, and to go back to a clean slate I could msbuild /t:rebuildandtest just that set of tests.  Now my changes are effectively global for corefx until I git clean -xdf and build.cmd everything again.

**Comment by mellinoe** [comment]
@stephentoub I agree that it's a big downside for that scenario. Do you think it would be valuable to have something like a `SelfContainedTest` flag that you could use to essentially emulate the old behavior, e.g. everything in one folder?

**Comment by stephentoub** [comment]
> Do you think it would be valuable to have something like a SelfContainedTest flag that you could use to essentially emulate the old behavior, e.g. copy and run everything from one isolated folder?

I would definitely use that.

**Comment by weshaggard** [comment]
>I don't understand; how do I get from c:\users\stoub\Source\Repos\corefx\bin/runtime/netcoreapp-Windows_NT-Debug-x64/ to C:\Users\stoub\Source\Repos\corefx\Tools\testdotnetcli\shared\Microsoft.NETCore.App\9.9.9?

Those are essentially the same directory as they are hard-linked together. You don't really even need to care about the second one.

I think it is worth filing an issue to have an option for producing a self-contained test output.

**Comment by weshaggard** [comment]
@mellinoe you mentioned that you were working on a way to create a self-contained tests output is that something you are still looking at?

**Comment by mellinoe** [comment]
@weshaggard I'm not looking at it right now.

**Comment by ViktorHofer** [comment]
@stephentoub is this something you still want to have? I will close this for now as in the testhost folder you now have a minimal dotnet.exe which invokes CoreRun from the shared folder inside the testhost folder.
