### ISSUE TITLE
Unable to rebuildandtest a test project after build.cmd

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#15167]
From the root of my repo, I do:
```
                git clean -xdf
                git fetch --all
                git checkout upstream/dev/eng
                build.cmd
                cd src\System.Linq\tests
                msbuild /t:rebuildandtest
```
Everything works fine until that last step.  When I try to do the msbuild /t:rebuildandtest, it fails while trying to start running the tests.  I'm forced to do a build-tests.cmd first and then this works.

cc: @weshaggard, @karajas

**Comment by karajas** [comment]
At the moment, this is because I added the dotnet test host as a pre test traversal build step. I can look into making it a post product build step. Does this make more sense?

**Comment by weshaggard** [comment]
I think I would like the dotnetclitest setup to happen as part of the external directory build after we get the host, and add the hard-link to the runtime folder. Then as a prestep to running any test generate the deps file.
