### ISSUE TITLE
Building and running tests not working in VS

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#15166]
@karajas it would appear after our changes building and running tests in VS isn't working. At least not for System.Threading.Tasks.Extensions.Tests.

**Comment by karajas** [comment]
The VS PR hasn't gone in, will push on this.

**Comment by JeremyKuhne** [comment]
@karajas Is the VS PR you're talking about #15182?  You can currently build, but you can't F5 to run the tests.

**Comment by JeremyKuhne** [comment]
Start in the test project has

```
%RUNTIME_PATH%\dotnet.exe
```

And the command line args are

```
%EXECUTION_DIR%\xunit.console.netcore.exe System.Configuration.ConfigurationManager.Tests.dll  -noshadow  -xml testResults.xml -notrait Benchmark=true -notrait 
```

Working directory

```
P:\repos\corefx\bin/AnyOS.AnyCPU.Debug/System.Configuration.ConfigurationManager.Tests/netstandard/
```

**Comment by karajas** [comment]
What configuration are you building for?

**Comment by JeremyKuhne** [comment]
netstandard-Debug. %RUNTIME_PATH%\dotnet.exe doesn't exist.

**Comment by weshaggard** [comment]
You need to run build-tests at least once until we get https://github.com/dotnet/corefx/issues/15167 fixed. But F5 should  work fine in VS now.

**Comment by JeremyKuhne** [comment]
Ok, I'll try that and close this one if I get this to work.

**Comment by JeremyKuhne** [comment]
Still complains about `%RUNTIME_PATH%\dotnet.exe doesn't exist.` I don't see this environment variable set anywhere...

**Comment by weshaggard** [comment]
Where do you see `%RUNTIME_PATH%` at? It should not be in the VS debug dialog. It is only in the RunTests.cmd script itself.

**Comment by JeremyKuhne** [comment]
It is in the dialog.

**Comment by weshaggard** [comment]
Looks like it was regressed with @mellinoe change https://github.com/dotnet/corefx/commit/febe1f61c0dc28b3e91e95895892e53111293d0c.

**Comment by mellinoe** [comment]
The VS command line options should be using absolute paths, it would seem, rather than the env-relative ones we need elsewhere.

**Comment by JeremyKuhne** [comment]
I'm about to put up a PR.

**Comment by karajas** [comment]
We could make VS run RunTests.cmd instead

**Comment by JeremyKuhne** [comment]
All I really care is that settings get picked up appropriately without having to define them in multiple places. :) (Well, and that you only run the tests for the current project.)

**Comment by weshaggard** [comment]
>We could make VS run RunTests.cmd instead

While I would like that it doesn't work as you have to give VS an executable and so you would need to give in cmd.exe and then when you debug you are debugging cmd.exe and not the test code.

**Comment by weshaggard** [comment]
This is fixed.
