### ISSUE TITLE
Desktop targeting pack: Add ValueTuple type forward to mscorlib for Desktop

### ISSUE THREAD

**Issue by jcouv** [dotnet/corefx#15175]
From discussion with Wes, once the first version of desktop with ValueTuple ships, the targeting pack for that framework needs to be updated with those bits and a typeforward can be added for that target group (I'm not sure the exact string/moniker that will be).

**Comment by karelz** [comment]
@weshaggard how best to track it? Which release cycle is it tied to? Desktop or .NET Core?
Does the targeting pack live in CoreFX repo or in Desktop source code base? Or is it part of .NET Standard?

**Comment by weshaggard** [comment]
If this is about adding the facade into the desktop targeting pack that that ships from the internal desktop builds. If this is about adding the facade the the ValueTuple package then that ships from corefx.

**Comment by jcouv** [comment]
FYI @terrajobst. This is the issue to add type forwards to desktop 4.7. 
From our discussion this morning, it sounds like this should happen as soon as desktop 4.7 is shipped and the ValueTuple nuget package should be updated asap after that (ie. not wait for next official release wave from coreFX).

**Comment by AlexGhiondea** [comment]
@jcouv I am still not clear where the change would need to happen.

Is it inside the Full .NET code base or here?

If it is inside the Full .NET I suggest creating a bug in the internal bug tracking system and closing this issue.

**Comment by jcouv** [comment]
@AlexGhiondea Some notes from our discussion:
A new moniker and targeting pack will be created in CoreFX. A new slice will be defined in the ValueTuple package for that moniker, and that slice will type-forward to the mscorlib implementation of ValueTuple (but not ITuple, which will be in a later version of desktop).

I captured the matrix of the ValueTuple package in the [umbrella issue](https://github.com/dotnet/roslyn/issues/13177).

**Comment by jcouv** [comment]
Could someone link to the work item for adding the new targeting pack in corefx repo? I'm assuming that is planned to do shortly.

**Comment by jcouv** [comment]
Alex published the pre-release [targeting pack](https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.TargetingPack.NETFramework.v4.7) so I am unblocked. I'll fix this early next week.
