### ISSUE TITLE
SqlClient / MultiSubnetFailover / Linux / 1.1.0 (Part II - Not Working)

### ISSUE THREAD

**Issue by jamesgibbs100** [dotnet/corefx#15194]
@corivera @saurabh500 @karelz 

Gents : I am opening another issue as I cannot reopen the original : #14978

Largely, I think I spoke to soon as deploying with the port number fix into our UAT environment FAILED.

In order to help understand what was going on I captured two TCPDUMP traces as I performed a simple Open on the SqlConnection object.

One container running on HOST01 fails, whilst another running on HOST02 succeeds.

The only difference i can see is the order in which DNS returns the primary and secondary - as discussed in #14978 where HOST01 returns the secondary first (this is the failing one) and HOST02 returns the primary. Of course the order shouldn't matter with MSN enabled which it is.

From looking at the traces - it doesn't appear that MSN is working at all on Linux - I do not see a parallel invocation of the open socket that I was expecting. Rather it appears to just take the first IP address and try to connect to that.

I'm happy to share the traces - only perhaps over something less public ?)

I'm also happy to perform any other kind of testing that would help us get to a resolution.

The setup is the same as before, only now with port specified (1433).

Framework : .NET App 1.1.0
Library : System.Data.SqlClient - 4.3.0
Container Base : Linux Ubuntu 14.04.5

Thanks in advance
James

**Comment by karelz** [comment]
Interesting, I thought that whomever creates an issue can also reopen it if it is closed. Anyway, in future feel free to reply on closed issue and we will reopen it on your behalf ... for this particular case we can track your question / troubles in this one.

**Comment by saurabh500** [comment]
@jamesgibbs100 I have reopened the original issue.
Can you put these details in the original issue and close this one? We may not be able to  look at this issue before next week. 
Also you can mail the whereabouts of the tcp dump to my GitHub email id. Does that work?

**Comment by jamesgibbs100** [comment]
Not really seeing your github email id - is it just saurabh500@github.com ?

**Comment by saurabh500** [comment]
Saurabh DOT singh AT microsoft.com

**Comment by karelz** [comment]
BTW: @saurabh500 you can update your GitHub profile to make your email public for cases like this ;-) (see my profile for example)

**Comment by saurabh500** [comment]
@karelz I did that after James told me he can't see my email . :) Thank you.
