### ISSUE TITLE
Allow null HttpResponseMessage in HttpClient.SendAsync?

### ISSUE THREAD

**Issue by tmenier** [dotnet/corefx#15191]
I understand that making this change could quite possibly have far-reaching implications, so I guess at the very least I'd like to start a discussion and understand why it is the way it is.

Currently [`HttpClient.SendAsync`](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClient.cs#L392) checks that the returned `HttpResponseMessage` is not null and throws an `InvalidOperationException` if it is. (Specifically [here](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClient.cs#L444-L447) and [here](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClient.cs#L476-L479).) I question why that check is necessary. It seems valid to want to implement a custom `HttpMessageHandler` that returns a null response in specific scenarios and not consider it an error condition. But with this behavior in `HttpClient`, you're basically forced to implement that flow through exception handling upstream.

I'm curious to get the team's thoughts on this. Thanks!

**Comment by mikedn** [comment]
> It seems valid to want to implement a custom HttpMessageHandler that returns a null response in specific scenarios and not consider it an error condition.

Any real world examples?

**Comment by tmenier** [comment]
I maintain a library that basically wraps a fluent interface around HttpClient and provides a few other goodies. One is the ability to configure error handling globally, as described [here](http://tmenier.github.io/Flurl/configuration/). A [bug](https://github.com/tmenier/Flurl/issues/159) was recently discovered that really came down to a bad assumption on my part that returning a null `HttpResponseMessage` from a handler was valid. I can certainly work around it, but it led me to question the design decision. Thanks.

**Comment by davidsh** [comment]
It is a fundamental design principle that the handler's SendAsync() method for HttpClient always return a non-null HttpResponseMessage.  That design is part of the original design for HttpClient when we built the API for .NET 4.5.  It would be a breaking change to alter that principle.

**Comment by davidsh** [comment]
As discussed, it is by-design behavior of this design.  The .NET Framework and .NET Core share this common design that handlers can not return NULL HttpResponseMessage objects.
