### ISSUE TITLE
Add Cookie Property to System.Net.Http.Headers

### ISSUE THREAD

**Issue by deinok** [dotnet/corefx#15209]
Add a Cookie property at System.Net.Http.Headers.HttpRequestHeaders
Add a Set-Cookie property at System.Net.Http.Headers.HttpResponseHeaders

This will help the access of the Cookies and its manipulation. For example

`responseHeader.Set-Cookie.Add(new Cookie("nameCookie","valueCookie"))`

**Comment by davidsh** [comment]
We have had this request before.  The object model for cookies with HttpClient is to use the CookieContainer object.

While there is an object model for `Cookie` itself, it doesn't map the same to the request header 'Cookie' vs. the response header 'Set-Cookie'.

The ASP.NET WebAPI team has looked at this before in their version of the Web APIs.  If you would like to propose a set of new APIs, you might want to examine what they did in their work.  We also would need to figure out how using these new APIs would work w.r.t. the CookieContainer object in the handlers such as `HttpClientHandler`.

cc: @danroth27 @Tratcher

**Comment by davidsh** [comment]
Ref: Issue #1611 for previous discussion on this.

See API proposal/review process:
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md

**Comment by deinok** [comment]
In the issue you are referencing, you wrote: 
"By the way, aren't the raw response headers (strings) already available in the HttpResponseMessage.Headers? If so, it sounds like the requirement is to have a strongly typed object model for the 'Set-Cookie' header itself."
That's exacly what im asking.

I have checked the source code of `HttpRequestHeaders` and `HttpResponseHeaders` and seems like all cookies are saved in `_headerStore` .

So we can create a Property that Parses that cookie string and convert it to a CookieCollection, to help developers deal with recovering cookies of Responses and setting new cookies in Request

**Comment by deinok** [comment]
Also, HttpHeader should implement IDictionary<string,IEnumerable<string>>
That will adding headers that dont have a property
`requestHeader["API-HEADER"]="myApiKey"`

**Comment by deinok** [comment]
@davidsh Where should i submit the API proposal?

**Comment by davidsh** [comment]
>Where should i submit the API proposal?

This repo is where API proposals should be submitted.  Please review the link above as well review closed issues of prior API proposals to give you an idea of creating the proposal and the review process, etc.

**Comment by Priya91** [comment]
@deinok You can refer to API proposal process [here](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md)

**Comment by karelz** [comment]
The API proposal was filed in separate issue #15591, closing.

Note: In future, let's add proposals as replies to the ongoing Design Discussion, no need to create "dupes".
