### ISSUE TITLE
How to specify network adapter which HttpClient must use?

### ISSUE THREAD

**Issue by Vicher** [dotnet/corefx#15208]
At .NET Framework it can be done by HttpWebRequest.ServicePoint.BindIPEndPointDelegate.

Can't find anything about that. It's currently impossible?

**Comment by davidsh** [comment]
This is not possible in either .NET Framework or .NET Core implementations of `HttpWebRequest`.

And, FYI, `ServicePoint.BindIPEndPointDelegate` is not implemented in .NET Core. It is only implemented in .NET Framework.

**Comment by Vicher** [comment]
Any plans to add this feature?

**Comment by davidsh** [comment]
There are no plans to add this.  it would be difficult since it would require changes to various OS layer stacks to provide enumeration of adapters as well as APIs to pass a specific adapter down to the TCP connection logic of various HTTP stacks.

**Comment by Priya91** [comment]
@Vicher Closing the issue per @davidsh comment.
