### ISSUE TITLE
corefx not using coreclr version defined in dependencies.props

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#15219]
As of my opening this issue, the dependencies.props file specifies:
```
<CoreClrExpectedPrerelease>beta-24916-02</CoreClrExpectedPrerelease>
```
but tests are being run using an older CoreCLR, version beta-24904-03.  This means we're not picking up changes from coreclr, and the auto-updates being generated aren't having the desired effect.
cc: @weshaggard

**Comment by danmosemsft** [comment]
As of now, tests in CoreFX seem to be running on CoreCLR from 03da007 from Jan 17th (it comes out of C:\git\corefx.dan\Tools\testdotnetcli\shared\Microsoft.NETCore.App\9.9.9\System.Private.CoreLib.dll).
