### ISSUE TITLE
WinHttpHandler throws "Could not load file or assembly 'System.IO.Compression'"

### ISSUE THREAD

**Issue by PawelGerr** [dotnet/corefx#15224]
WinHttpHandler throws an error when using it in xproj targeting net46. Other constellations like targetting netcoreapp or having a csproj work fine.

## Error
```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.Compression, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
   at System.Net.Http.WinHttpResponseParser.CreateResponseMessage(WinHttpRequestState state, Boolean doManualDecompressionCheck)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CompressionTest.Program.<GetValue>d__1.MoveNext() in C:\Sources\CompressionTest\Program.cs:line 21
```

### project.json
```
{
	"version": "1.0.0-*",
	"buildOptions": {
		"emitEntryPoint": true
	},

	"dependencies": {
		"System.Net.Http": "4.3.0",
		"System.Net.Http.WinHttpHandler": "4.3.0"
	},

	"frameworks": {
		"net46": {
			"frameworkAssemblies": {
				"System.Runtime": "",
				"System.Threading.Tasks": ""
			}
		}
	},

	"runtimes": {
		"win10-x64": {}
	}
}
```

### Program.cs
```c#
public class Program
{
    public static void Main(string[] args)
    {
		using(var client = new HttpClient(new WinHttpHandler()))
		using(var response = client.GetAsync("http://www.google.de").Result)
		{
		}
	}
}
```

**Comment by davidsh** [comment]
@PawelGerr What tooling are you using to create the xproj?  Visual Studio or command line tools?  Can you provide a little more detail so that we can set up a repro?

**Comment by PawelGerr** [comment]
I'm using Visual Studio Professional 2015 (14.0.25431.01 Update 3) for setting up xproj-projects.
VS-Template: Templates -> .NET Core -> Console Application (.NET Core)

System:
* Win 10 x64
* i7-4870HQ @2,5 GHz
* 16 GB RAM

The whole VS solution can be downloaded from https://www.dropbox.com/s/bz4f77ms7bzbwz0/WinHttpHandlerRepro.zip 

After reboot I'm getting a new exception but my colleague still gets the one from my first post.

Exception after reboot:
```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The operation timed out
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WinHttpHandlerRepro.Program.<DoRequest>d__1.MoveNext() in C:\Sources\Tests\WinHttpHandlerRepro\Program.cs:line 21
```

**Comment by davidsh** [comment]
[WinHttpHandlerRepro.zip](https://github.com/dotnet/corefx/files/714669/WinHttpHandlerRepro.zip)

**Comment by davidsh** [comment]
Thanks for providing a complete Visual Studio solution.  I was able to use the solution and rebuild it.  But when I hit F5, I get this error:

![image](https://cloud.githubusercontent.com/assets/7684835/22077303/77a58386-dd68-11e6-87c7-46bf75bd741d.png)

This .NET Core profile/template that you used only produces a DLL and not EXE. It looks like it is using the old ASP.NET 5 Core profile and not the latest ASP.NET Core 1.x profile/template.

**Comment by davidsh** [comment]
Also, when I use your repro steps above to create a new Visual Studio Solution:

>VS-Template: Templates -> .NET Core -> Console Application (.NET Core)

I get a different project.json that is defined against the RTM 'netcoreapp1.0' moniker.

```c#
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.1"
    },
    "System.Net.Http": "4.3.0",
    "System.Net.Http.WinHttpHandler": "4.3.0"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}
```

I think the problem is that you are using a pre-release version of the .NET Core template.

**Comment by PawelGerr** [comment]
Me and my colleague are able to start the project with F5 without any problems.
Regarding project.json, I changed this file so that it looks like in my 1st post.

Try to build the project via command line: `dotnet restore` , `dotnet publish --configuration Release`

Or use the exe that I get when executing `dotnet publish --configuration Release`: https://www.dropbox.com/s/ihshy2lh878uf07/WinHttpHandlerRepro-publish.zip

JFYI: with `dotnet --version` I get `1.0.0-preview2-1-003177`

**Comment by davidsh** [comment]
I think the difference in my ability to repro it and yours is a difference in various pre-release tools both commandline and Visual Studio installed on our respective dev machines.  So, it will be difficult to troublshoot this.

However, looking at the ZIP file of the WinHttpHandlerRepro-publish that you posted, it is very clear why you are getting a FileIOException about missing System.IO.Compression.dll.  The reason is that DLL is required but yet is not in the list of assemblies in that ZIP file:

![image](https://cloud.githubusercontent.com/assets/7684835/22078112/c7a6bef6-dd6b-11e6-9b7d-fae694f90ff5.png)

This is most likely a NuGet package dependency problem of some kind.  It doesn't seem to happen when a create a new project using the latest Visual Studio tooling. So, I think this is a problem with dotnet CLI tooling of some kind.

cc: @ericstj

**Comment by PawelGerr** [comment]
@davidsh What tooling are you using?

**Comment by ericstj** [comment]
Tooling bug.  
System.Net.Http.WinHttpHandler depends on System.IO.Compression:
http://www.nuget.org/api/v2/package/System.Net.Http.WinHttpHandler/4.3.0
(extract, inspect nuspec)
```

      <group targetFramework=".NETFramework4.6">
        <dependency id="Microsoft.Win32.Primitives" version="4.3.0" exclude="Compile" />
        <dependency id="System.Diagnostics.DiagnosticSource" version="4.3.0" exclude="Compile" />
        <dependency id="System.IO.Compression" version="4.3.0" exclude="Compile" />
        <dependency id="System.Security.Cryptography.X509Certificates" version="4.3.0" />
      </group>
```

System.IO.Compression has a net46 assembly in it.
http://www.nuget.org/api/v2/package/System.IO.Compression/4.3.0
(extract, inspect contents)
```
lib/net46/System.IO.Compression.dll
```

Try a newer dotnet CLI, if it still repros file a bug in http://github.com/dotnet/sdk.  /cc @dsplaisted @cdmihai

**Comment by PawelGerr** [comment]
There is one newer version "1.0.0-rc4-004530" (https://github.com/dotnet/cli) but it is msbuild-based and (as I know) for that I need VS 2017.
Is there another newer version that works with xproj?

**Comment by davidsh** [comment]
>@davidsh What tooling are you using?

In terms of Visual Studio tooling, I am using Visual Studio 2015 with Update 3.

And I still don't understand the repro here.  When you create a new .NET Core application, the project.json file should contain 'netcoreapp1.0' references.  It doesn't have 'net46' references in it.  That is usually only for when you build a library (DLL) that needs to be used across multiple scenarios such as netcoreapp, .NET Framework app, etc.

As I mentioned earlier, when I use VS tooling and create a new .NET Core app, I don't see this missing System.IO.Compression.dll.

**Comment by PawelGerr** [comment]
> That is usually only for when you build a library (DLL) that needs to be used across multiple scenarios such as netcoreapp, .NET Framework app, etc.
That's the case. I have a lib that supports both netstandard and net46. Furthermore, I have 2 executable projects, 1 netcoreapp-only project and 1 net46-only project, referencing the lib. Netcoreapp works without problems, net46 doesn't.

I tried to keep the repro as minimal as possible thats why I changed the project.json the way it is.
WinHttpHandler works as expected having netcoreapp thas why I removed it from "frameworks" because there is no need to look into working example.

**Comment by davidsh** [comment]
>I tried to keep the repro as minimal as possible thats why I changed the project.json the way it is.

I think making that manual change to the project.json creates an unsupported configuration.

Can you re-craft the repro scenario with instructions for re-creating it from scratch (i.e. steps in Visual Studio etc.?  That would allow us to investigate it and keep it mapped to supported scenarios.

**Comment by PawelGerr** [comment]
@davidsh @ericstj 
It really is a tooling/nuget problem. As soon as I add `NETStandard.Library` to `dependencies` then everything works as expected.

```
{
	"version": "1.0.0-*",
	"buildOptions": {
		"emitEntryPoint": true
	},

	"dependencies": {
		"NETStandard.Library": "1.6.1",
		"System.Net.Http.WinHttpHandler": "4.3.0"
	},

	"frameworks": {
		"net46": {}
	},

	"runtimes": {
		"win10-x64": {}
	}
}
```

**Comment by davidsh** [comment]
>It really is a tooling/nuget problem. As soon as I add NETStandard.Library to dependencies then everything works as expected.

As a recommendation, if you are building a library to be used by different types of apps/services, etc., it's recommended that you build the library and simply depend on NETStandard.Library.  Then add more things as needed.  By defining your library as dependending on NETStandard, you are automatically making it compatible with everything including 'net46'.  That's because NETStandard 1.6, for example, supports 'net46' as part of the standard.

It would be useful at this point for this bug to be closed and for you open up a new bug in  http://github.com/dotnet/sdk.  It's also possible that committing the use of NETStandard.LIbrary in the dependencies might not be considered a supported scenario and might be required as part of authoring a library.  But that discussion would best be had in the sdk repo.
