### ISSUE TITLE
Don't copy files just for packaging

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#15220]
I suspect this is due to the binplacing behavior.  /cc @weshaggard @chcosta @mellinoe

**Comment by chcosta** [comment]
I agree, I believe this is because we are binplacing binaries to various locations for consumption (like bin\(TargetFramework)\pkg). We first binplace binaries from a source location, then we sign the files in that source location, so we never get the signed binaries.

**Comment by ericstj** [comment]
I was thinking it might make more sense rather than to binplace just to write a file list.  We don't actually need the package layout as real files.  That would let us transfer more state, like the source files needed for the symbol packages.

**Comment by weshaggard** [comment]
@ericstj correct me if I'm wrong but I think you fixed this recently.

**Comment by ericstj** [comment]
Yeah, I worked around it by hard-linking.  I still think we should replace the package inclusion with file lists rather than copies.

**Comment by weshaggard** [comment]
@ericstj I believe you have completed this work already, correct?

**Comment by ericstj** [comment]
Yep.  It is done.
