### ISSUE TITLE
Make ValueTuple* binary serializable

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#15229]
We generally don’t want to add more types to be binary serializable in the framework, due to complexities and the fragility that it causes across version boundaries (remember that binary serialization has to be backward- and forward compatible). That being said, for `ValueTuple` we can likely convince ourselves that the serialization behavior is fixed and mostly a function of the types you instantiate the tuple with. It seems a resonable assumption to say that `ValueTuple<T1, ..., TN>` to be serializable if `T1`-`TN` are serializable.

Not being binary serializable also makes it harder (and more fragile) for existing code to switch from `Tuple` to `ValueTuple`.

**Comment by tarekgh** [comment]
CC @jcouv

**Comment by karelz** [comment]
API review: Approved.

**Comment by karelz** [comment]
@jcouv can you please do it? We need to change also Desktop.

**Comment by jcouv** [comment]
@karelz I'll stop by your office tomorrow to discuss and confirm.

**Comment by karelz** [comment]
@terrajobst will know more. I was just typing without too much context :)
But feel free to stop by and say hi ;-)

**Comment by jcouv** [comment]
Fixed in desktop, coreclr and corert. I think mono will pick this up automatically.
FYI @marek-safar just in case.
