### ISSUE TITLE
On Linux Win32Exception thrown by Process have incorrect error number

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#15234]
`Process.Unix.cs` calls:
```
int errno = Interop.Sys.Kill(_processId, Interop.Sys.Signals.SIGKILL);
int errno = Interop.Sys.GetPriority(Interop.Sys.PriorityWhich.PRIO_PROCESS, _processId, out pri);
```
which are implemented as
```
return kill(pid, signal);
return getpriority(which, who);
```
These functions return -1 on error. They should return errno:
```
return SystemNative_ConvertErrorPlatformToPal(errno);
```

**Comment by karelz** [comment]
@yizhang82 is the error code handled by interop?

**Comment by stephentoub** [comment]
> is the error code handled by interop?

No

> These functions return -1 on error. They should return errno

@tmds, no, that's not the pattern used for these functions.  The managed call sites check for -1 and then check errno using a platform-agnostic mechanism.  I don't see a bug here; is there a particular call site you're concerned about?

**Comment by stephentoub** [comment]
> I don't see a bug here

Actually, I take that back, I do see one, e.g.
https://github.com/dotnet/corefx/blob/912cba3675a15718515417e7e9b46504c0303fbc/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs#L59
```
throw new Win32Exception(errno); 
```
should be:
```
throw new Win32Exception();
```
There may be some other places as well.

**Comment by tmds** [comment]
@stephentoub Interesting. This means properties exposing error codes on Win32Exception are platform specific?

**Comment by stephentoub** [comment]
> This means properties exposing error codes on Win32Exception are platform specific?

Yes

**Comment by tmds** [comment]
> Yes, e.g. NativeErrorCode is the native error code.

And so is `ErrorCode` and `HResult`.

**Comment by stephentoub** [comment]
> And so is ErrorCode and HResult.

No, the base implementation of ExternalException.ErrorCode just returns HResult, and HResult is set by SetErrorCode, not by the error passed to the Win32Exception ctor.
