### ISSUE TITLE
Missing this in RegistryAclExtensions extension methods

### ISSUE THREAD

**Issue by marek-safar** [dotnet/corefx#15242]
https://github.com/dotnet/corefx/blob/fdc332530a2ec9aca582a6d88f95aaba9660070b/src/Microsoft.Win32.Registry.AccessControl/src/Microsoft/Win32/RegistryAclExtensions.net46.cs

There is also missing null argument check

**Comment by karelz** [comment]
Did we ship these APIs this way before? If yes, we might have app compat concerns to delete them / change their signature ... @sepidehMS?

**Comment by jkotas** [comment]
It is mismatch between the reference assembly and the desktop implementation: 

The reference assembly and .NET Core implementation has it https://github.com/dotnet/corefx/blob/fdc332530a2ec9aca582a6d88f95aaba9660070b/src/Microsoft.Win32.Registry.AccessControl/ref/Microsoft.Win32.Registry.AccessControl.cs#L14, but it is missing in the desktop implementation. We should fix the desktop implementation to match. It should be a breaking change as long as everybody compiles against reference assemblies.

**Comment by danmosemsft** [comment]
@ViktorHofer want to grab this?

**Comment by ViktorHofer** [comment]
@jkotas What is the purpose of these extension methods? They are calling exactly the same methods in the RegistryKey class.

**Comment by jkotas** [comment]
These methods are collateral damage from the times where we tried to do a very fine grained layering of the framework surface. The extension methods like this were one of the tricks used to break cycles in the layering.

The fine grainer layering of the framework surface is gone for the most part, so these methods do have a great purpose anymore. They exist for backward compatibility only.

**Comment by ViktorHofer** [comment]
Thank you Jan! Backwards Compatibility is a strong argument. As I guess this is new in core / wasn't correctly implemented before, wouldn't it make sense to get rid off it now and for all?

**Comment by karelz** [comment]
If it shipped in .NET Core 1.0 or 1.1, then it is compat against that :(

**Comment by karelz** [comment]
If it is new in 2.0, then we can still correct our mistakes.

**Comment by ViktorHofer** [comment]
It already shipped with 1.0: https://github.com/dotnet/corefx/blob/release/1.0.0/src/Microsoft.Win32.Registry.AccessControl/ref/Microsoft.Win32.Registry.AccessControl.cs

In both 1.0 and 1.1 the net46 implementation is missing the "this"...
