### ISSUE TITLE
Missing this in FileSystemAclExtensions method extensions

### ISSUE THREAD

**Issue by marek-safar** [dotnet/corefx#15243]
only `GetAccessControl` has it

https://github.com/dotnet/corefx/blob/fdc332530a2ec9aca582a6d88f95aaba9660070b/src/System.IO.FileSystem.AccessControl/src/System/IO/FileSystemAclExtensions.net46.cs

**Comment by karelz** [comment]
Did we ship the API this way before? If yes, we may have app compat problem ...

**Comment by jkotas** [comment]
Mismatch between the reference assembly and the desktop implementation. We should fix the desktop implementation to match.

**Comment by ianhays** [comment]
Note that this is only in the net46 version of this file. [The one included in the netcore build](https://github.com/dotnet/corefx/blob/fdc332530a2ec9aca582a6d88f95aaba9660070b/src/System.IO.FileSystem.AccessControl/src/System/IO/FileSystemAclExtensions.cs) has `this` on all members (as it should), so there isn't any compat worry.

That said, we should fic it.
