### ISSUE TITLE
Building clean shows modified src\shims\ApiCompatBaseline.netfx461.txt file

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#15254]
When I build clean, I now get a modified file:
![image](https://cloud.githubusercontent.com/assets/7684835/22039086/ad95e17c-dcb2-11e6-89ff-04db8d4ce82f.png)

perhaps the .gitignore needs to be updated now?

**Comment by weshaggard** [comment]
That file shouldn't be gitignored. This file will get updated when ever someone adds or removes APIs that affect the compat with net461. See comments in https://github.com/dotnet/corefx/pull/15238#pullrequestreview-17054441 where I've asked for that file to be added to the PR. The current difference is a result of an earlier merged PR that added those APIs in that diff. 

So there isn't anything to do for this issue beyond making sure folks look at for it and include it when they make changes that impact it.
