### ISSUE TITLE
Fix syntax highlighting issue due to dev/eng

### ISSUE THREAD

**Issue by karajas** [dotnet/corefx#15253]
/cc @weshaggard

**Comment by karajas** [comment]
Current theory is design time build isn't included refs allocated by targetingpacks.props. Will condition a new ItemGroup with DesignTimeBuild=true

https://github.com/dotnet/roslyn-project-system/blob/master/docs/design-time-builds.md#diagnosing-design-time-builds

**Comment by weshaggard** [comment]
No longer an issue.
