### ISSUE TITLE
Rename System.Transactions assembly in .NET Core

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#15259]
We cannot use the assembly name System.Transactions because that assembly already exist in the full .NET framework. We need to come up with another name and rename it before we try to ship this assembly.

**Comment by jimcarley** [comment]
I like System.Transactions.Local.

**Comment by weshaggard** [comment]
Sounds reasonable to me I tagged with api-ready-for-review to get other FXDC member opinions.

**Comment by stephentoub** [comment]
> I like System.Transactions.Local

Does that suggest that any support for distributed transactions would be in another, higher-level assembly?

**Comment by jimcarley** [comment]
Yes. In my current vision for support of distributed transactions, we would add some abstract base classes to System.Transactions.Local and then have a new assembly, like System.Transactions.MSDTC, that will have implementations for those base classes along with the supporting code to talk to MSDTC on Windows. And somebody could write a separate assembly, like System.Transactions.DistributedOnLinux, that would use some other distributed transaction coordinator that runs on Linux. Without another assembly that has classes that derive from these new "distributed" abstract base classes in System.Transactions.Local, distributed transactions would not be supported, just like today.

**Comment by stephentoub** [comment]
Sounds good.

**Comment by karelz** [comment]
API review:
Order of preference - @jimcarley and team, please choose
1. `System.Transactions.Ambient`
2. `System.Transactions.Local`

**Comment by dmetzgar** [comment]
@karelz Our team is in agreement on System.Transactions.Local

**Comment by dmetzgar** [comment]
@weshaggard @karelz if we change the assembly name, does that also change the package name?

**Comment by karelz** [comment]
I don't think so - I let @weshaggard confirm for sure.

**Comment by weshaggard** [comment]
Just changing the assembly name will not update the package name but this name change does apply to both the package and the assembly so you should rename both of them.

**Comment by qizhanMS** [comment]
Previously we encountered version mismatch when we were trying to use the package. Do you think the version issue was gone?

**Comment by weshaggard** [comment]
@qizhanMS I need more information to help answer that question.

**Comment by karelz** [comment]
@qizhanMS is it fixed by #16444?

Note: You can use [GitHub auto closing](https://help.github.com/articles/closing-issues-via-commit-messages/) if you add "Fixes <issue_reference>" into your PR description.

**Comment by weshaggard** [comment]
Yes this is fixed by #16444
