### ISSUE TITLE
Port TplEventSource fix to desktop

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#15269]
https://github.com/dotnet/coreclr/pull/8942
cc: @AlexGhiondea

**Comment by karelz** [comment]
@AlexGhiondea as soon as it is mirrored in TFS, can you please close the issue?

**Comment by AlexGhiondea** [comment]
The issue does not have to be open for the tool to pick it up :).

**Comment by karelz** [comment]
Thanks!
I keep forgetting that it works on closed issues, and then I want to make sure it doesn't get lost, so I ask :flushed:
