### ISSUE TITLE
SpanTests.ClearLongerThanUintMaxValueBytes failing in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#15279]
e.g.
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug/69/
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_release/69/
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_release/70/
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_release/71/
```
System.SpanTests.SpanTests.ClearLongerThanUintMaxValueBytes [FAIL]
        System.OutOfMemoryException : Array dimensions exceeded supported range.
        Stack Trace:
           D:\j\workspace\outerloop_win---bf7c4efa\src\System.Memory\tests\Span\Clear.cs(205,0): at System.SpanTests.SpanTests.ClearLongerThanUintMaxValueBytes()
```

**Comment by danmosemsft** [comment]
@nietras I see you added this test. Do you have any context on this error?

**Comment by jkotas** [comment]
This tests depends on https://github.com/dotnet/coreclr/pull/8853 to pass. The error message suggests that it is running on older CoreCLR that does not contain this change.

**Comment by jkotas** [comment]
Dup of https://github.com/dotnet/corefx/issues/15219?

**Comment by nietras** [comment]
Perhaps this might be related to the build warning (clean build from new clone of master), although this is regarding an assembly:
```
"E:\oss\corefx\build.proj" (default target) (1) ->
    "E:\oss\corefx\src\Tools\CoreFx.Tools\CoreFx.Tools.csproj" (default target) (2) ->
       (ResolveAssemblyReferences target) -> 
         C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): 
warning MSB3277: Found conflicts between different versions of the same dependent assembly 
that could not be resolved.  These reference conflicts are listed in the build log when 
log verbosity is set to detailed. [E:\oss\corefx\src\Tools\CoreFx.Tools\CoreFx.Tools.csproj]
```
This happens on restore command:
```
"E:\oss\corefx\Tools/dotnetcli/dotnet.exe" restore --no-cache --packages "E:\oss\corefx\packages" --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://www.nuget.org/api/v2/ "E:\oss\corefx\src\Tools\CoreFx.Tools/project.json"
```

**Comment by danmosemsft** [comment]
As of now, tests in CoreFX seem to be running on CoreCLR from 03da007 from Jan 17th (it comes out of C:\git\corefx.dan\Tools\testdotnetcli\shared\Microsoft.NETCore.App\9.9.9\System.Private.CoreLib.dll). That should contain 163983e. 

Also, this passes on my machine. @stephentoub does it fail locally for you?

**Comment by joperezr** [comment]
@stephentoub have you seen this failure again? if not then perhaps it was the verion of coreclr that we were using and we can just close this.

**Comment by nietras** [comment]
Also see https://github.com/dotnet/corefx/pull/15434 although test should work with correct coreclr and enough memory.

**Comment by stephentoub** [comment]
Right, it was suppressed in #15434.  We can close.
