### ISSUE TITLE
build-native.sh followed by build-managed.sh doesn't work

### ISSUE THREAD

**Issue by omajid** [dotnet/corefx#15274]
I am hitting errors building corefx on RHEL:

    $ cat /etc/os-release
    NAME="Red Hat Enterprise Linux Workstation"
    VERSION="7.3 (Maipo)"
    ID="rhel"
    ID_LIKE="fedora"
    VERSION_ID="7.3"
    PRETTY_NAME="Employee SKU"
    ANSI_COLOR="0;31"
    CPE_NAME="cpe:/o:redhat:enterprise_linux:7.3:GA:workstation"
    HOME_URL="https://www.redhat.com/"
    BUG_REPORT_URL="https://bugzilla.redhat.com/"
    
    REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
    REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
    REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
    REDHAT_SUPPORT_PRODUCT_VERSION="7.3"

    $ git branch -v
    * master 8ddccab Fix exception when parsing HTTP/2 status line (#15203)
    $ ./buid-managed.sh
     <lots of ouptut>
      /home/omajid/corefx/packages/xunit.runner.utility/2.2.0-beta2-build3300/lib/netstandard1.1/xunit.runner.utility.dotnet.dll (xunit.runner.utility.2.2.0-beta2-build3300) -> xunit.runner.utility.dotnet.dll
      /home/omajid/corefx/packages/xunit.runner.utility/2.2.0-beta2-build3300/lib/netstandard1.1/xunit.runner.utility.dotnet.pdb (xunit.runner.utility.2.2.0-beta2-build3300) -> xunit.runner.utility.dotnet.pdb

    /home/omajid/corefx/Tools/Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [/home/omajid/corefx/src/Tools/CoreFx.Tools/CoreFx.Tools.csproj]
    /home/omajid/corefx/src/Tools/GenerateProps/GenerateProps.proj(15,5): error MSB4062: The "GenerateConfigurationProps" task could not be loaded from the assembly /home/omajid/corefx/Tools/CoreFx.Tools.dll. Could not load file or assembly 'CoreFx.Tools, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
    /home/omajid/corefx/src/Tools/GenerateProps/GenerateProps.proj(15,5): error MSB4062:  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
    /home/omajid/corefx/Tools/depProj.targets(79,5): error : Error no assets were resolved from NuGet packages. [/home/omajid/corefx/external/coreclr/coreclr.depproj]

Anyone have any ideas about this? Any pointers to what the issue may be?

**Comment by omajid** [comment]
I get a little further using `./build-managed.sh -SkipTests -BuildTests`:

      System.Runtime.InteropServices.RuntimeInformation -> /home/omajid/corefx/bin/Unix.AnyCPU.Debug/System.Runtime.InteropServices.RuntimeInformation/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll
      System.Security.Cryptography.X509Certificates -> /home/omajid/corefx/bin/Unix.AnyCPU.Debug/System.Security.Cryptography.X509Certificates/netcoreapp/System.Security.Cryptography.X509Certificates.dll
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error : Error when creating nuget lib package from /home/omajid/corefx/bin/packages/Debug/specs/runtime.rhel.7-x64.Microsoft.Private.CoreFx.NETCoreApp.nuspec. System.IO.DirectoryNotFoun
    dException: Could not find a part of the path '/home/omajid/corefx/bin/Linux.x64.Debug/native'. [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at System.IO.UnixFileSystem.FileSystemEnumerable`1.OpenDirectory(String fullPath) [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCor
    eApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at System.IO.UnixFileSystem.FileSystemEnumerable`1.Enumerate() [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at System.IO.UnixFileSystem.FileSystemEnumerable`1..ctor(String userPath, String searchPattern, SearchOption searchOption, SearchTarget searchTarget, Func`3 translateResult) 
    [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at System.IO.UnixFileSystem.EnumeratePaths(String path, String searchPattern, SearchOption searchOption, SearchTarget searchTarget) [/home/omajid/corefx/pkg/Microsoft.Private
    .CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searc
    hOption) [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption) [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.C
    oreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at NuGet.Common.PathResolver.PerformWildcardSearch(String basePath, String searchPath, Boolean includeEmptyDirectories, String& normalizedBasePath) [/home/omajid/corefx/pkg/M
    icrosoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at NuGet.Packaging.PackageBuilder.ResolveSearchPattern(String basePath, String searchPath, String targetPath, Boolean includeEmptyDirectories) [/home/omajid/corefx/pkg/Micros
    oft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude) [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Mi
    crosoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files) [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NE
    TCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at Microsoft.DotNet.Build.Tasks.Packaging.NuGetPack.Pack(String nuspecPath, Func`2 nuspecPropertyProvider, Boolean packSymbols) [/home/omajid/corefx/pkg/Microsoft.Private.Cor
    eFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error : Error when creating nuget symbol package from /home/omajid/corefx/bin/packages/Debug/specs/runtime.rhel.7-x64.Microsoft.Private.CoreFx.NETCoreApp.nuspec. System.IO.DirectoryNotF
    oundException: Could not find a part of the path '/home/omajid/corefx/bin/Linux.x64.Debug/native'. [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at System.IO.UnixFileSystem.FileSystemEnumerable`1.OpenDirectory(String fullPath) [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCor
    eApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at System.IO.UnixFileSystem.FileSystemEnumerable`1.Enumerate() [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at System.IO.UnixFileSystem.FileSystemEnumerable`1..ctor(String userPath, String searchPattern, SearchOption searchOption, SearchTarget searchTarget, Func`3 translateResult) 
    [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    .CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searc
    hOption) [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption) [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.C
    oreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at NuGet.Common.PathResolver.PerformWildcardSearch(String basePath, String searchPath, Boolean includeEmptyDirectories, String& normalizedBasePath) [/home/omajid/corefx/pkg/M
    icrosoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at NuGet.Packaging.PackageBuilder.ResolveSearchPattern(String basePath, String searchPath, String targetPath, Boolean includeEmptyDirectories) [/home/omajid/corefx/pkg/Micros
    oft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude) [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Mi
    crosoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files) [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NE
    TCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at Microsoft.DotNet.Build.Tasks.Packaging.NuGetPack.Pack(String nuspecPath, Func`2 nuspecPropertyProvider, Boolean packSymbols) [/home/omajid/corefx/pkg/Microsoft.Private.Cor
    eFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
      Installing Microsoft.NETCore.Platforms 2.0.0-beta-24918-0.
      Microsoft.NETCore.Platforms -> /home/omajid/corefx/bin/packages/Debug/specs/Microsoft.NETCore.Platforms.nuspec
    
    /home/omajid/corefx/Tools/Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the
     build log when log verbosity is set to detailed. [/home/omajid/corefx/src/Tools/CoreFx.Tools/CoreFx.Tools.csproj]
    /home/omajid/corefx/src/System.Configuration.ConfigurationManager/src/Resources/Strings.resx : warning MSB3568: Duplicate resource name "Config_base_unrecognized_element" is not allowed, ignored. [/home/omajid/corefx/src/System.Configurat
    ion.ConfigurationManager/src/System.Configuration.ConfigurationManager.csproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error : Error when creating nuget lib package from /home/omajid/corefx/bin/packages/Debug/specs/runtime.rhel.7-x64.Microsoft.Private.CoreFx.NETCoreApp.nuspec. System.IO.DirectoryNotFoun
    dException: Could not find a part of the path '/home/omajid/corefx/bin/Linux.x64.Debug/native'. [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at System.IO.UnixFileSystem.FileSystemEnumerable`1.OpenDirectory(String fullPath) [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCor
    eApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at System.IO.UnixFileSystem.FileSystemEnumerable`1.Enumerate() [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at System.IO.UnixFileSystem.FileSystemEnumerable`1..ctor(String userPath, String searchPattern, SearchOption searchOption, SearchTarget searchTarget, Func`3 translateResult) 
    [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at System.IO.UnixFileSystem.EnumeratePaths(String path, String searchPattern, SearchOption searchOption, SearchTarget searchTarget) [/home/omajid/corefx/pkg/Microsoft.Private
    .CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searc
    hOption) [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption) [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.C
    oreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at NuGet.Common.PathResolver.PerformWildcardSearch(String basePath, String searchPath, Boolean includeEmptyDirectories, String& normalizedBasePath) [/home/omajid/corefx/pkg/M
    icrosoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at NuGet.Packaging.PackageBuilder.ResolveSearchPattern(String basePath, String searchPath, String targetPath, Boolean includeEmptyDirectories) [/home/omajid/corefx/pkg/Micros
    oft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude) [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Mi
    crosoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files) [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NE
    TCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at Microsoft.DotNet.Build.Tasks.Packaging.NuGetPack.Pack(String nuspecPath, Func`2 nuspecPropertyProvider, Boolean packSymbols) [/home/omajid/corefx/pkg/Microsoft.Private.Cor
    eFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error : Error when creating nuget symbol package from /home/omajid/corefx/bin/packages/Debug/specs/runtime.rhel.7-x64.Microsoft.Private.CoreFx.NETCoreApp.nuspec. System.IO.DirectoryNotF
    oundException: Could not find a part of the path '/home/omajid/corefx/bin/Linux.x64.Debug/native'. [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at System.IO.UnixFileSystem.FileSystemEnumerable`1.OpenDirectory(String fullPath) [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCor
    eApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at System.IO.UnixFileSystem.FileSystemEnumerable`1.Enumerate() [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at System.IO.UnixFileSystem.FileSystemEnumerable`1..ctor(String userPath, String searchPattern, SearchOption searchOption, SearchTarget searchTarget, Func`3 translateResult) 
    [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at System.IO.UnixFileSystem.EnumeratePaths(String path, String searchPattern, SearchOption searchOption, SearchTarget searchTarget) [/home/omajid/corefx/pkg/Microsoft.Private
    .CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searc
    hOption) [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption) [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.C
    oreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at NuGet.Common.PathResolver.PerformWildcardSearch(String basePath, String searchPath, Boolean includeEmptyDirectories, String& normalizedBasePath) [/home/omajid/corefx/pkg/M
    icrosoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at NuGet.Packaging.PackageBuilder.ResolveSearchPattern(String basePath, String searchPath, String targetPath, Boolean includeEmptyDirectories) [/home/omajid/corefx/pkg/Micros
    oft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude) [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Mi
    crosoft.Private.CoreFx.NETCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files) [/home/omajid/corefx/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NE
    TCoreApp.pkgproj]
    /home/omajid/corefx/Tools/Packaging.targets(1198,5): error :    at Microsoft.DotNet.Build.Tasks.Packaging.NuGetPack.Pack(String nuspecPath, Func`2 nuspecPropertyProvider, Boolean packSymbols) [/home/omajid/corefx/pkg/Microsoft.Private.Cor
    eFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    Command execution failed with exit code 1.

**Comment by weshaggard** [comment]
@ericstj @joperezr did we ever get to the bottom of the build task loading issue yet?

@omajid what do you git if you just do a build.sh?

**Comment by omajid** [comment]
Hm.. a `build.sh` works. But a `build-native.sh` followed by `build-managed.sh` doesn't.

**Comment by ericstj** [comment]
When you did `build-native.sh` followed by `build-managed.sh` what was in the `/home/omajid/corefx/bin/Linux.x64.Debug/native` folder? If it's missing can you check to see where `build-native.sh` actually put the binaries?

**Comment by omajid** [comment]
After running `./build-native.sh`:

    [omajid@localhost corefx]$ ls bin/Linux.x64.Debug/native/
    System.IO.Compression.Native.so
    System.Native.a
    System.Native.so
    System.Net.Http.Native.so
    System.Net.Security.Native.so
    System.Security.Cryptography.Native.OpenSsl.so
    System.Security.Cryptography.Native.so

No change in the contents of that dir after running `./build-managed.sh`. I do see additional files (such as `bin/obj/Linux.AnyCPU.Debug/CoreFx.Tools/CoreFx.Tools.dll`) after doing `./build-managed.sh` but not in `bin/Linux.x64.Debug/native`.

**Comment by omajid** [comment]
Sorry for the noise. I guess this is a known issue. As `build.sh` says, the following works:

1. `./build-native.sh`
2. `./Tools/msbuild.sh src/Tools/CoreFx.Tools/CoreFx.Tools.csproj /v:m /m`
3. `./build-managed.sh` 

`./build.sh` does step 2 to work around a bug. See https://github.com/dotnet/corefx/commit/05d190de1ecf5d023ab0d288fa95ea751d2325af.

Is there any chance the underlying bug will be fixed?

**Comment by weshaggard** [comment]
@joperezr  do we have issue tracking the real fix for 05d190d?

**Comment by joperezr** [comment]
I don't think so. @ericstj and I believe that the issue was on the CLI's new assembly loading logic, but the error might as well be somewhere else, so we didn't yet have enough info to log an issue of why do we think this is happening.

**Comment by weshaggard** [comment]
CoreFxTools.csproj no longer exists in corefx so this shouldn't be applicable any longer.
