### ISSUE TITLE
System.Net.Sockets.Async.Performance tests crashing

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#15278]
@geoffkizer, it looks like this test library has very recently started crashing... I suspect it's related to your recent synchronous completion changes. e.g.
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug/71/
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug/70/
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_rhel7.2_debug/73/
Can you take a look?

**Comment by geoffkizer** [comment]
Yes, already looking.
