### ISSUE TITLE
When to  add support for running dotnet core on raspberrypi's os  raspbian?

### ISSUE THREAD

**Issue by maikebing** [dotnet/corefx#15275]
http://www.raspbian.org/

**Comment by leonpw** [comment]
Or running on ARM at all?

**Comment by maikebing** [comment]
dotnet core  supported  Debian 8, while raspbian is based on Debian 8,  it's  has more advantages!

**Comment by wtgodbe** [comment]
Closing this for now, feel free to re-open if we get some more traction on Raspbian.
