### ISSUE TITLE
Assembly in CoreRT has APIs that depend on FileStream

### ISSUE THREAD

**Issue by DnlHarvey** [dotnet/corefx#15284]
Just a note so we get a heads up when we can bring over those APIs

**Comment by JeremyKuhne** [comment]
Path was moved already https://github.com/dotnet/corert/pull/2438 by @jkotas. With that moved, FileStream should be able to be moved fairly easily I think- at least with basic Win32 support (no brokering for Pictures, etc.).

**Comment by jkotas** [comment]
I have moved Win32 filestream as well (https://github.com/dotnet/corert/pull/2428), but it is only enabled in CoreRT/Win32 build. Enabling it in ProjectN/UWP build requires figuring out what to do about the brokering support.

**Comment by JeremyKuhne** [comment]
@jkotas Can we enable it in SPCL without the brokering to allow filling out the API?

**Comment by jkotas** [comment]
It may be possible - as long as whoever is doing that makes sure that it does not put everything on the floor.

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/issues/21025 covers the CoreFX API's. This is to do similar work for FileStream.

**Comment by JeremyKuhne** [comment]
Just have brokering left to do here. Waiting on Windows changes.
