### ISSUE TITLE
test projects configured as netstandard should compile against netstandard targeting pack

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#15298]
Tests are always compiling against the build configuration ref and never netstandard. See https://github.com/dotnet/corefx/blob/5bd6dea77374feccbc859d4a771f9fff7e973d86/targetingpacks.props#L20 and https://github.com/dotnet/corefx/blob/5bd6dea77374feccbc859d4a771f9fff7e973d86/Tools-Override/FrameworkTargeting.targets#L5

**Comment by mellinoe** [comment]
These build against the `netstandard` binaries now.
