### ISSUE TITLE
MSBuild says dlls are being used by another process when invoking build-tests

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#15301]
I have just rebased after the announcement in https://github.com/dotnet/corefx/issues/15135 and run `clean --all`, `build`, and `build-tests`. During `build-tests` this error pops up when MSBuild tries to copy files from `bin\runtime` to `Tools\testdotnetcli\shared\Microsoft.NETCore.App\9.9.9`:

```
C:\Users\james\Code\git\corefx\Tools\ConstructSharedFx.targets(41,5): warning MSB3026: Could not copy "C:\Users\james\C
ode\git\corefx\bin/runtime/netcoreapp-Windows_NT-Debug-x64/\apphost.exe" to "C:\Users\james\Code\git\corefx\Tools/testd
otnetcli\shared\Microsoft.NETCore.App\9.9.9\apphost.exe". Beginning retry 1 in 1000ms. The process cannot access the fi
le 'C:\Users\james\Code\git\corefx\Tools/testdotnetcli\shared\Microsoft.NETCore.App\9.9.9\apphost.exe' because it is be
ing used by another process. [C:\Users\james\Code\git\corefx\src\tests.builds]
```

This happens for every file in `bin\runtime`; the full log is [here](https://gist.github.com/jamesqo/d63af78cfd2363f5a9d90dd714a782a2). (I had to quit the process because it was taking too long, so the log does not include every file in the directory.)

I've tried killing VBCSCompiler.exe and restarting my desktop, but it still happens.

**Comment by danmosemsft** [comment]
This would tell us what is holding it. https://technet.microsoft.com/en-us/sysinternals/handle.aspx

**Comment by weshaggard** [comment]
cc @karajas 

do you have any dotnet.exe process alive?

**Comment by jamesqo** [comment]
@danmosemsft I did try using Process Monitor to look at the path before, and nothing came up. I could have done something wrong though (I had just downloaded the program).

**Comment by jamesqo** [comment]
@danmosemsft Nvm, I thought that Handle was a GUI app like Process Monitor, didn't realize it was actually a command-line program. Here's the output of `handle Tools\`:

```
C:\Users\james\Downloads\Handle>handle corefx\Tools

Nthandle v4.1 - Handle viewer
Copyright (C) 1997-2016 Mark Russinovich
Sysinternals - www.sysinternals.com

devenv.exe         pid: 8688   type: File          1634: C:\Users\james\Code\git\corefx\Tools\net45\Microsoft.DotNet.Build.Tasks.dll
devenv.exe         pid: 8688   type: File          1664: C:\Users\james\Code\git\corefx\Tools\net45\roslyn\tools\Microsoft.Build.Tasks.CodeAnalysis.dll
devenv.exe         pid: 8688   type: File          1694: C:\Users\james\Code\git\corefx\Tools\net45\NuGet.Frameworks.dll
devenv.exe         pid: 8688   type: File          16D0: C:\Users\james\Code\git\corefx\Tools\net45\Microsoft.DotNet.Build.Tasks.Packaging.dll
```

**Comment by mellinoe** [comment]
Can you close Visual Studio and see if that helps?

**Comment by jamesqo** [comment]
@mellinoe Just edited my question at the bottom after you commented. I just closed VS and verified that `handle` no longer said `devenv` was using the assemblies, but it still happens.

**Comment by weshaggard** [comment]
@jamesqo are you still hitting this issue?

**Comment by jamesqo** [comment]
@weshaggard Nope, not anymore. I can close this.

**Comment by XCJAlves** [comment]
Hi @jamesqo  - what was the solution to your problem? I am having the same type issue, the gulp task could not run successfully because it says:

C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Deploy\Microsoft.Web.Publishing.Deploy.FileSystem.targets(96,5): error : Copying file obj\Debug\Package\PackageTmp\bin\Sitecore.Mvc.dll to C:\Web\wwwroot\MyCompany\\Website\bin\Sitecore.Mvc.dll failed. The process cannot access the file 'C:\Web\wwwroot\MyCompany\\Website\bin\Sitecore.Mvc.dll' because it is being used by another process. [C:\XCentium\Projects\MyCompany\src\Foundation\Theming\code\MyCompany.Foundation.Theming.csproj]

**Comment by akuryan** [comment]
Me as well facing same issue - "error MSB3554: Cannot write to the output file ".resources". The process cannot access the file '.resources' because it is being used by another process."

**Comment by danmosemsft** [comment]
@akuryan what are you building? This issue is about building this repo itsrlf. It would be better to open a new issue as this is closed.

**Comment by paivaandeerson** [comment]
I don't know why but I fixed this issue using argument verbosity normal level  `-v n`
