### ISSUE TITLE
Feature: Stack.TryPeek and TryPop

### ISSUE THREAD

**Issue by epa** [dotnet/corefx#15322]
The `Stack<T>` class should add methods `bool TryPeek(out T value)` and `bool TryPop(out T value)`.

In ordinary usage, these would only be a small improvement in clarity (and perhaps, marginally, in performance) compared to manually checking `Count()` and then calling `Peek()` or `Pop()`.  But they would be very useful to have to make the interface closer to that of `ConcurrentStack`.  Then if you write code with `ConcurrentStack` but later realize that the extra synchronization provided by that class isn't needed, you will be able to change the code to plain `Stack` without rewriting.

**Comment by karelz** [comment]
It is already part of .NET Core -- added in #12047 on 2016/9/29

**Comment by karelz** [comment]
See the API discussion here: https://github.com/dotnet/corefx/issues/4316#issuecomment-245036426
