### ISSUE TITLE
Tuple in List<T> Creates Extra Values

### ISSUE THREAD

**Issue by RandyBuchholz** [dotnet/corefx#15320]
### Issue
When I create a list of tuples it is adding additional items to the list. These aren't showing in the list, only the debugger.

### Example
```
public List<(string label, ProjectStrategy.Services route, Type message)> Services { get; set; }
	= new List<(string label, ProjectStrategy.Services route, Type message)> {
	(label: "Edit", route: ProjectStrategy.Services.EditStrategy, message: typeof(ProjectEditViewModel)),
	(label: "Find", route: ProjectStrategy.Services.FindProject, message: typeof(ProjectIdentityViewData)),
	(label: "List", route: ProjectStrategy.Services.ListProjects, message: typeof(void)),
	(label: "New", route: ProjectStrategy.Services.NewStrategy, message: typeof(void)),
	(label: "View", route: ProjectStrategy.Services.ViewStrategy, message: typeof(ProjectIdentityViewData))
};
```
In the debugger, it shows a list containing eight values, though the count says five.

![image](https://cloud.githubusercontent.com/assets/13967891/22112489/b7ef3692-de28-11e6-86e7-39b47d41c4f0.png)

**Comment by stephentoub** [comment]
You're seeing the underlying array used by the list, which may be larger than the actual number of entries stored in the list.

**Comment by RandyBuchholz** [comment]
Ah, should have known that.
