### ISSUE TITLE
Proposal: Add Sort(...) extension methods for Span<T>

### ISSUE THREAD

**Issue by nietras** [dotnet/corefx#15329]
Currently, there is no way to sort native or fixed memory (e.g. coming from a pointer) in .NET, this proposal intends to fix that by adding sorting extension methods to `Span<T>`, but also proposes some different overloads than seen on `Array` to allow for inlined comparisons via the possibility to use value type comparers.

### Proposed API
Add a set of `Sort` extension methods to `Span<T>` in `SpanExtensions`:
```csharp
public static class SpanExtensions
{
     public static void Sort<T>(this Span<T> span);

     public static void Sort<T, TComparer>(this Span<T> span, TComparer comparer) 
        where TComparer : IComparer<T>;

     public static void Sort<T>(this Span<T> span, System.Comparison<T> comparison);
     
     public static void Sort<TKey, TValue>(this Span<TKey> keys, Span<TValue> items);

     public static void Sort<TKey, TValue, TComparer>(this Span<TKey> keys, 
        Span<TValue> items, TComparer comparer) 
        where TComparer : IComparer<TKey>;
        
     public static void Sort<TKey, TValue>(this Span<TKey> keys, 
        Span<TValue> items, System.Comparison<TKey> comparison);
}
```

### Rationale and Usage
Provide a safe yet fast way of sorting of any type of contiguous memory; managed or unmanaged.

#### Sorting Native Memory
```csharp
var span = new Span<int>(ptr, length);
span.Sort(); // Sort elements in native memory
```
#### Sorting with Inlineable Comparer
```csharp
struct ReverseComparer : IComparer<int>
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public int Compare(int a, int b)
    {
        if (a == b) { return 0; }
        if (a > b) { return -1; }
        return 1;
    }
}

Span<int> span = GetSomeSpan();
// Sort elements, in reverse order with inlined Compare,
// without heap allocation for comparer
span.Sort(new ReverseComparer()); 
```
#### Sorting based on Lambda
```csharp
Span<int> span = GetSomeSpan();
// Sort elements, in reverse order with lambda/delegate
span.Sort((a, b) => a == b ? 0 : (a > b ? -1 : 1)); 
```

#### Sorting Compound Type
```csharp
struct Compound
{
    public float FeatureValue;
    public int FeatureIndex;
    public object Payload;
}

struct InlineableFeatureValueComparer : IComparer<Compound>
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public int Compare(Compound a, Compound b)
    {
        if (a.FeatureValue == b.FeatureValue) { return 0; }
        if (a.FeatureValue < b.FeatureValue) { return -1; }
        return 1;
    }
}

var span = new Span<Compound>();

span.Sort();

// Inlineable struct comparer
var comparer = new InlineableFeatureValueComparer();
span.Sort(comparer);

// Lambda comparer
span.Sort((a, b) => a.FeatureValue == b.FeatureValue ? 0 : 
    (a.FeatureValue < b.FeatureValue ? -1 : 1));
```

The argumentation for adding this is:
 * To increase the efficiency of code doing sorting and prevent people from reinventing the wheel.
 * Allow performance optimizations depending on memory type and contents.
 * Allow sorting on contiguous memory of any kind.

#### Use Cases
In almost any domain where a high volume of data is processed with sorting being one operation and memory management (e.g. memory recycling, buffer pooling, native memory) is a must to achieve high performance with minimal latency, these sorts would be useful. Example domains are database engines (think indexing), computer vision, artificial intelligence etc.

A concrete example could be in the training of Random Forests some methods employ feature sorting (with indeces) to find decision boundaries on. This involves a lot of data and data that can originate from unmanaged memory.

### Open Questions
An important question regarding this proposal is whether the pattern with generic parameter `TComparer` (e.g. constrained to `where TComparer : IComparer<T>`) is a pattern that can be approved. This pattern allows for inlineable comparers at the cost of increased code size, if no value type comparers are used, there should be no difference. This pattern is also used in the proposal for `BinarySearch` in https://github.com/dotnet/corefx/issues/15818

The API relies on being able to depend upon `System.Collections.Generic`, could this be an issue?

@karelz @jkotas @jamesqo 

### Updates
UPDATE 1: Change API to be defined as extension methods.
UPDATE 2: Add compounded type usage.
UPDATE 3: Add link to BinarySearch and point on the pattern used.

### Existing Sort APIs
A non-exhaustive list of existing sorting APIs is given below for comparison.

#### `Array.Sort` Static Methods
Found in [ref/System.Runtime.cs](https://github.com/dotnet/corefx/blob/master/src/System.Runtime/ref/System.Runtime.cs)

```csharp
public static void Sort(System.Array array) { }
public static void Sort(System.Array keys, System.Array items) { }
public static void Sort(System.Array keys, System.Array items, System.Collections.IComparer comparer) { }
public static void Sort(System.Array keys, System.Array items, int index, int length) { }
public static void Sort(System.Array keys, System.Array items, int index, int length, System.Collections.IComparer comparer) { }
public static void Sort(System.Array array, System.Collections.IComparer comparer) { }
public static void Sort(System.Array array, int index, int length) { }
public static void Sort(System.Array array, int index, int length, System.Collections.IComparer comparer) { }
public static void Sort<T>(T[] array) { }
public static void Sort<T>(T[] array, System.Collections.Generic.IComparer<T> comparer) { }
public static void Sort<T>(T[] array, System.Comparison<T> comparison) { }
public static void Sort<T>(T[] array, int index, int length) { }
public static void Sort<T>(T[] array, int index, int length, System.Collections.Generic.IComparer<T> comparer) { }
public static void Sort<TKey, TValue>(TKey[] keys, TValue[] items) { }
public static void Sort<TKey, TValue>(TKey[] keys, TValue[] items, System.Collections.Generic.IComparer<TKey> comparer) { }
public static void Sort<TKey, TValue>(TKey[] keys, TValue[] items, int index, int length) { }
public static void Sort<TKey, TValue>(TKey[] keys, TValue[] items, int index, int length, System.Collections.Generic.IComparer<TKey> comparer) { }
```

#### `List<T>.Sort` Member Methods
Found in [ref/System.Collections.cs](https://github.com/dotnet/corefx/blob/master/src/System.Collections/ref/System.Collections.cs)

```csharp
public partial class List<T> : System.Collections.Generic.ICollection<T>, System.Collections.Generic.IEnumerable<T>, System.Collections.Generic.IList<T>, System.Collections.Generic.IReadOnlyCollection<T>, System.Collections.Generic.IReadOnlyList<T>, System.Collections.ICollection, System.Collections.IEnumerable, System.Collections.IList
{
    public void Sort() { }
    public void Sort(System.Collections.Generic.IComparer<T> comparer) { }
    public void Sort(System.Comparison<T> comparison) { }
    public void Sort(int index, int count, System.Collections.Generic.IComparer<T> comparer) { }
}
```

#### LINQ `OrderBy` Extension Methods
Found in [ref/System.Linq.cs](https://github.com/dotnet/corefx/blob/master/src/System.Linq/ref/System.Linq.cs)

```csharp
public static System.Linq.IOrderedEnumerable<TSource> OrderBy<TSource, TKey>(this System.Collections.Generic.IEnumerable<TSource> source, System.Func<TSource, TKey> keySelector) { throw null; }
public static System.Linq.IOrderedEnumerable<TSource> OrderBy<TSource, TKey>(this System.Collections.Generic.IEnumerable<TSource> source, System.Func<TSource, TKey> keySelector, System.Collections.Generic.IComparer<TKey> comparer) { throw null; }
public static System.Linq.IOrderedEnumerable<TSource> OrderByDescending<TSource, TKey>(this System.Collections.Generic.IEnumerable<TSource> source, System.Func<TSource, TKey> keySelector) { throw null; }
public static System.Linq.IOrderedEnumerable<TSource> OrderByDescending<TSource, TKey>(this System.Collections.Generic.IEnumerable<TSource> source, System.Func<TSource, TKey> keySelector, System.Collections.Generic.IComparer<TKey> comparer) { throw null; }
```

**Comment by jkotas** [comment]
> Or perhaps as extension methods.

These should be extension methods. They are in same category as the other similar methods being added: https://github.com/dotnet/corefx/pull/13854

cc @KrzysztofCwalina

**Comment by nietras** [comment]
> These should be extension methods.

Ok, would this not mean any optimizations specific to native/managed memory would not be possible as directly as when they are members? Not sure it has such big a relevance since sorting can be done on `ref`s, but not everything is possible with `ref`s as with pointers. Anyway, if you think this should not be an issue I will update the proposal.

**Comment by nietras** [comment]
Another concern, is generic type inference which in C# is not always working so well with many generic parameters... not that I can think of a specific case for the proposed API though, but in the face of implicit conversions or similar it is often lacking.

**Comment by jamesqo** [comment]
@nietras IMHO, I don't know if this is really a needed API. What scenarios are there in which someone would want to sort a Span? It's mostly going to be used to hold byte/char buffers, where sorting won't make much sense. Also, things like equality comparers are high-level and don't really fit in with low-level constructs like `Span`.

**Comment by nietras** [comment]
> What scenarios are there in which someone would want to sort a Span?

@jamesqo plenty! 😃 Ranging from database engines, computer vision to artificial intelligence. In the latter cases, the types will also range fully from `byte` to `double`. And in these fields memory recycling, buffer pooling is paramount to archieving reliable performance. And performance in general important so inlining the compare is important too.

> things like equality comparers are high-level

Not sure I get that, but is the issue with the "default" comparers needed for `Sort()` without parameters? I could live with removing the overloads that do not take a `TComparer` if that is the concern?

**Comment by svick** [comment]
```c#
public void Sort<TKey, TValue, TComparer>(this Span<TKey> keys, Span<TValue> items, TComparer comparer) where TComparer : IComparer<T>;
public void Sort<TKey, TValue>(this Span<TKey> keys, Span<TValue> items, System.Comparison<T> comparison); // Convenience overload
```

Nitpick: the `T`s in the two lines above should be `TKey`:

```c#
public void Sort<TKey, TValue, TComparer>(this Span<TKey> keys, Span<TValue> items, TComparer comparer) where TComparer : IComparer<TKey>;
public void Sort<TKey, TValue>(this Span<TKey> keys, Span<TValue> items, System.Comparison<TKey> comparison); // Convenience overload
```

**Comment by nietras** [comment]
@svick thanks I also forgot `static`

**Comment by jamesqo** [comment]
@nietras 

> Ranging from database engines, computer vision to artificial intelligence. In the latter cases, the types will also range fully from byte to double. And in these fields memory recycling, buffer pooling is paramount to archieving reliable performance. And performance in general important so inlining the compare is important too.

Do you have a concrete example where a sort function would be needed, though? I think the 95% use case for this API would be passing around byte buffers/char buffers. In those scenarios, sorting isn't a function that would be needed, and would only be more API bloat.

> Not sure I get that, but is the issue with the "default" comparers needed for Sort() without parameters? I could live with removing the overloads that do not take a TComparer if that is the concern?

The issue, actually, is with the overloads with the comparers. Making them generic on the type of the comparer won't improve perf because everyone passes around comparers as `IEqualityComparer<T>`. So you will still have virtual calls.

**Comment by nietras** [comment]
> concrete example where a sort function would be needed, though?

@jamesqo I tried giving a more concrete in the proposal regarding machine learning.

> 95% use case for this API would be passing around byte buffers/char buffers

If .NET Core and `Span<T>` only target audience is web server developers, where shuffling bytes to/from text/chars, then perhaps you are right. But IMHO it is a very limited target audience and misses the fact that in a cloud/mobile first world that is going to be infused with artificial intelligence everywhere, handling massive amounts of data/measurements is a must. This includes all data types, `byte` to `double`. Pure sales talk, uff 🙄 

> because everyone passes around comparers as IEqualityComparer<T>

I don't and never have. 😉 Passing comparers around is not something we do and it does not have any impact on the design of this API. It still works as a "non-generic" API and if it is only used with reference type comparers there will be no code bloat or anything. So I do not see the downside here, the overloads are there for convenience and flexibility just as with the existing APIs incl. `Array.Sort` the implementation can forward to the same single implementation, for example. However, by having the possibility for using a value type comparer we allow developers that need the perf and understand that this will cause code to be generated specifically for that case to do what they need. No virtual calls. In the domain of numerical processing that is what we need.

**Comment by KrzysztofCwalina** [comment]
We could do Sort<TComparer>(TComparer comparer) where TComparer : IComparer<T>. This would be devirtualized.

**Comment by jamesqo** [comment]
@KrzysztofCwalina It will not unless you pass in a custom struct comparer. For example, `Sort(Comparer<T>.Default)` will have TComparer == `Comparer<T>` and you will be making virtual calls to `Comparer<T>.Compare`.

**Comment by jamesqo** [comment]
There is another thing too-- I don't think the overloads accepting `TComparer` will even compile. [See here.](http://tryroslyn.azurewebsites.net/#b:master/f:r/K4Zwlgdg5gBAygTxAFwKYFsDcAoUlaIoYB0AwgPYA2lqAxsmORCMQOKoSoBOYtOe0eEjTpiAGUgBHHNgAOwAEaVeMWpQCGIEDFIwA3thhGY8pSoBu5MABMYAWQA8AFQA0MJwFEIwdN3VLUAD4ACk9vXy5/GhhUAEoYAHcAC25Udy8fPwCYAC4YAEkMiKjUZ0DDYwNjGABfCqN6k0VlWhhLGxgAOWDYxqrq4ztgoqyaYgAldWhUYIAGN1nY2JxquurG0xa2q1sAeR6+xurHSGQ3QvDR0tPAkJHIgImpqBn5mEXlxrqaoA) I ran into this issue a few months ago when I was trying to use generics in a similar fashion.

**Comment by nietras** [comment]
>  I don't think the overloads accepting TComparer will even compile

Yes, it does 😄 Check out [Sort Extensions examples](http://tryroslyn.azurewebsites.net/#b:master/f:r/K4Zwlgdg5gBAygTxAFwKYFsDcAoUlaIoYB0AwgPYA2lqAxsmORCMQOKoSoBOYtOe0eEjTpiAJWAQG6VGXLoADmBpc43AG69UIHNggBDGSAX7aqIUXTYA3thj2YC4ACNKvGCi7B68ExAA8ACoAfHYO1jAAvthh9k6u7ij6DLQwtJT6ICC++hAAogAeaMyMzLEwtg5Vji5uqUkpMOrkYAAm8ORcyEHBABTIABZg2XB+PR5+AJTlVRHRMw7xdR7Iye7NbR1dQQA0MIEUivpc3H2DwzkBIRO5ewfyJidcaQ/H3NPVnwDuA9zm90cnjAAFwwACSh0e3B6C3scxinzitUSq0aG3acE63RC/SGIzG12MtwsIjkgOGTHGtFePBATA+iPhsJqCXqqPWLQxWKCAGlUAg7gA1fSUYCoM54y68/nBGAAa35ID2o1yQWFovFMDAIhADM+TMRLOWDQ5m0x20CfIF+3VYrukLeXAlFxVVytsoVSB2zIcrrVIrFsu1GCV+wdQOpgPePvsPz+YZp3BB4PD0MtMuZBsRSxRa1S6K22KtQoD4txLoJ7vliu9ht9BNtmuD6FDhFJ4YpbplL3JdIgeuq8Kq8yqObZebSGSyMAAqiB9FBUOVKojPN5kDAxKh1NwQKhU89QRDE1x/JBkKFDSu6zAANoAWVQg3IrTBikovUfz9f74A8goGCYFgAEEoCgE4sjAHcwQgNwIHwSYAF0YyRVktSkGBU16c8YH0PYcOcAcrxQ6owAAMxgXp9BgABeGiYEIioYBOZBgC4CAYAABkwKISKqcjKOo2VGIiFi2I4gBaABGHjohvT4xPYmAZJIuTERHbNkXHNFOXgfAaFdXoiPCEj1GOG4OPozgvilc8+kmXR5Is4hzWQIzHPkgB6TzwVgyBUH0VxzDXHxIyhLhTPMk4dy4PcD1omBrM3bdd33E93JIokIBcrFemi1KDwchEvJ8gAZQxnFaaiwsdTK/ByrpeiovZGJo2VqLohiYAAfi45MqJgYSepgaTkykyYisNDTPjHFYJwLQIvnIV0QCMzNIueT1sis1AbL9OyMqcsznmbbbEt2qVWnIWoy0m+StoatzTqKkjvN8uCAqClYvFCk8NuYlLYrSqNnh2mytxiuL0rum8Htc7CdT2fKgcKjzYcVR6EZDPZmoYyZaPa2j6OcYbOP6oSut60bQXGmHqjU+xokiIA=) with the following code:

```csharp
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace System
{
    public struct Span<T> { }

    public static class SpanExtensions
    {
        public static void Sort<T>(this Span<T> span)
        { }

        public static void Sort<T, TComparer>(this Span<T> span, TComparer comparer)
           where TComparer : IComparer<T>
        { }

        public static void Sort<T>(this Span<T> span, System.Comparison<T> comparison)
        { }

        public static void Sort<TKey, TValue>(this Span<TKey> keys, Span<TValue> items)
        { }

        public static void Sort<TKey, TValue, TComparer>(this Span<TKey> keys,
           Span<TValue> items, TComparer comparer)
           where TComparer : IComparer<TKey>
        { }

        public static void Sort<TKey, TValue>(this Span<TKey> keys,
           Span<TValue> items, System.Comparison<TKey> comparison)
        { }
    }

    public static class Usage
    {
        struct ReverseComparer : IComparer<int>
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public int Compare(int a, int b)
            {
                if (a == b) { return 0; }
                if (a > b) { return -1; }
                return 1;
            }
        }

        public static void SingleSpan()
        {
            var span = new Span<int>();

            span.Sort();

            // Inlineable struct comparer
            var reverseComparer = new ReverseComparer();
            span.Sort(reverseComparer);

            // Lambda comparer
            span.Sort((a, b) => a == b ? 0 : (a > b ? -1 : 1));
        }

        public static void TwoSpans()
        {
            var keys = new Span<int>();
            var items = new Span<double>();
            keys.Sort(items);

            // Inlineable struct comparer
            var reverseComparer = new ReverseComparer();
            keys.Sort(items, reverseComparer);

            keys.Sort(items, (a, b) => a == b ? 0 : (a > b ? -1 : 1));
        }
    }
}
```
This compiles fine, `ReverseComparer` will be inlined. If people use `Comparer<T>.Default` the behaviour is the same as for `Array.Sort` and I see no issue with that, i.e. it will use it as `IComparer<T>` and there will be a virtual call. If necessary we can do some of the same checks that I think happen in `Array.Sort` to check if it is default comparer e.g. for `int` then use optimized int sort. Just as the non-generic `Array.Sort`does.

**Comment by joperezr** [comment]
@KrzysztofCwalina is this ready for review?

**Comment by nietras** [comment]
@joperezr since @KrzysztofCwalina hasn't replied, I think it is ready for review.

**Comment by KrzysztofCwalina** [comment]
which one is the final proposal? The APIs at the top of this issue?

**Comment by nietras** [comment]
Yes, the extension methods.

**Comment by jkotas** [comment]
Related proposal: https://github.com/dotnet/corefx/issues/15818

**Comment by terrajobst** [comment]
The scenario and proposed overloads all make sense. Minor issue: the one that takes two spans (keys and items) should call the items `values` as that's what array did. So it should be:

```C#
public static class SpanExtensions
{
     public static void Sort<TKey, TValue>(this Span<TKey> keys, Span<TValue> values);
     public static void Sort<TKey, TValue, TComparer>(this Span<TKey> keys,  Span<TValue> values, TComparer comparer)  where TComparer : IComparer<TKey>;        
     public static void Sort<TKey, TValue>(this Span<TKey> keys,  Span<TValue> values, System.Comparison<TKey> comparison);
}
```

We should discuss the extension method pattern for span holistically -- I don't think that this a good idea for our customers. It introduces a somewhat weird type (`SpanHelpers`) we no additional benefit. What is the reason these should be extension methods?

**Comment by karelz** [comment]
Approved and up-for-grabs, anyone wants to take it? @nietras?

**Comment by nietras** [comment]
> should call the items values 

@terrajobst if you look at the `ref` sources I included at the bottom of the proposal, these are in fact called `items`, this is where I took it from. E.g.:
```csharp
public static void Sort<TKey, TValue>(TKey[] keys, TValue[] items) { }
```
 Are there conflicting names, or are the ref sources not correct?

> We should discuss the extension method pattern for span holistically -- I don't think that this a good idea for our customers. 

The original proposal was for member methods, but I guess there are some implementation issues related to fast/slow span. @jkotas should answer that. I would have preferred member methods too.

**Comment by terrajobst** [comment]
@nietras 

You're correct. I looked at apisof.net but apparently I suck at reading because it's called `items` there as well. Never mind then; `items` it is :-)

**Comment by nietras** [comment]
> Approved and up-for-grabs, anyone wants to take it? @nietras?

@karelz I would love to to do this. I even had this idea to base this on "Multi-Pivot Quicksort: Theory and Experiments" (or newer e.g. "comparison-optimal dual-pivot quicksort algorithms" see http://itu.dk/people/maau/additional/2016_vortrag_arco_QS.pdf) using a multi-pivot quick-sort algorithm (point being it is more important to have fewer cache misses than comparisons). 

But given the scope of this, testing alone, perf etc., I do not think I will have time to do this within a reasonable time frame. No doubt, it would also be best to simply port the existing sort code and tests to `SpanExtensions`. If I get time and no one has started this, I will let you know.

**Comment by nietras** [comment]
> Approved and up-for-grabs, anyone wants to take it? @nietras?

@karelz I would love to to do this. I even had this idea to base this on "Multi-Pivot Quicksort: Theory and Experiments" (or newer e.g. "comparison-optimal dual-pivot quicksort algorithms" see http://itu.dk/people/maau/additional/2016_vortrag_arco_QS.pdf) using a multi-pivot quick-sort algorithm (point being it is more important to have fewer cache misses than comparisons). 

But given the scope of this, testing alone, perf etc., I do not think I will have time to do this within a reasonable time frame. No doubt, it would also be best to simply port the existing sort code and tests to `SpanExtensions`. If I get time and no one has started this, I will let you know.

**Comment by karelz** [comment]
Sounds good, let's see if anyone else wants to help with the work in the meantime ...

**Comment by nietras** [comment]
@karelz you can assign this to me if you like. I will start working on this tentatively, it will probably take some time, due to the writing tests mostly I think. First goal is simply porting the existing Array.Sort code with some minor modifications.

**Comment by LYP951018** [comment]
And then we could just use `Span<T>.Sort` as implementation for `Array` and `List<T>`?

**Comment by GrabYourPitchforks** [comment]
@nietras How are things going with this? We recently forked for 2.1-preview1, but there may still be time to get this in for the next preview. If you find yourself pressed for time, no worries, let us know and we can reassign. Thanks! :)

**Comment by nietras** [comment]
> How are things going with this?

@GrabYourPitchforks things are progressing fine. I have ported all the code, basic tests pass, but I'm still trying to iron out some perf issues after I consolidated code to have both with and without items in one code base. Before that perf was on par or even better than coreclr even for the C++ optimized types.

The code can actually be found at https://github.com/DotNetCross/Sorting/blob/span-sort/src/DotNetCross.Sorting/SpanSortHelpers.cs I am working on it in that repo. Any feedback is welcomed.

I'll try to make a preminary PR for this soon, I need some feedback anyway. Especially regarding testing etc.

It would be great if this could be part of next preview.

> And then we could just use Span<T>.Sort as implementation for Array and List<T>?

@LYP951018 that question is a bit tricky due to how the coreclr and corefx code is structured. `Array.Sort` is part of coreclr for example. Someone else might be better at answering whether in the future it might be possible to use this version for all sorts.

**Comment by jkotas** [comment]
> consolidated code to have both with and without items in one code base

I do not think you need to do that. It is fine to have two copies - one without and one with items.

**Comment by nietras** [comment]
> I do not think you need to do that. It is fine to have two copies - one without and one with items.

@jkotas I thought it would be less maintenance and with some `typeof == typeof` tricks without perf issues. But yes I may have to revert those changes then. It just means a lot of duplicated code. It's almost 1000 lines, and it also impacts type specializations I have done.

**Comment by thorgeirk11** [comment]
Are there any workarounds to apply sorting on a Span<T> without having to copy it to an array?  

This is so ugly:
`			
var ohNoAnArray = awesomeSpan.ToArray();
Array.Sort(ohNoAnArray, (p1, p2) => p1.CompareTo(p2)));
ohNoAnArray.CopyTo(awesomeSpan);
`

**Comment by nietras** [comment]
@thorgeirk11 this proposal of course addresses this, unfortunately my PRs (https://github.com/dotnet/corefx/pull/26859 and https://github.com/dotnet/coreclr/pull/16986) for adding these got rejected/closed. Does not seem to have been added by anyone else after.

However, the implementation works and all tests pass of this, the main issue was around security I think. In https://github.com/dotnetcross/sorting the same implementation can be found. I have not had time to finalize this and make it available in a nuget package though, as a complement to the -- hopefully at some point -- implementation of this proposal in .NET Core proper.

**Comment by shartte** [comment]
Regarding use cases:
Maybe I am misunderstanding this, but I was trying to stackalloc a Span of simple structs, then sort it, but this seems impossible to do without this issue being solved. Is that correct?

Example (which doesn't compile):
```
struct BoneAttachment {
  int Bone;
  float Weight;

  private sealed class WeightRelationalComparer : IComparer<BoneAttachment>
  {
    public int Compare(BoneAttachment x, BoneAttachment y)
    {
      return y.Weight.CompareTo(x.Weight);
    }
  }

  public static IComparer<BoneAttachment> WeightComparer { get; } = new WeightRelationalComparer();
}

Span<BoneAttachment> attachments = stackalloc BoneAttachment[16];
// ... fill with data
attachments.Sort(BoneAttachment.WeightComparer); // <--- This doesn't exist
```

**Comment by nietras** [comment]
@shartte yes only when this proposal has been implemented will you be able to do that.

I did a PR for this in https://github.com/dotnet/corefx/pull/26859 but this was rejected.

In https://github.com/DotNetCross/Sorting I have this in separate source form but haven't had time to clean this up and package as a nuget package for general use.

**Comment by EamonNerbonne** [comment]
If people are still waiting for things like this; I wrote a nuget package that's similar in spirit: https://github.com/EamonNerbonne/anoprsst.  However, I didn't try to keep the API similar to Array.Sort since I was aiming to avoid perf-pitfals (i.e. no virtual calls, ever).  In particular that means you can do `someSpan.SortIComparableUsing().Sort()` but that's constrained to sorting `structs` only, otherwise you need to use `someSpan.SortUsing(new MyOrdering()).Sort()` with a struct ordering.  The serial implementation appears to outperform Array.Sort in all cases, sometimes by a large margin; and for large arrays it uses parallel quick sort for further speedup.

**Comment by stephentoub** [comment]
Completed in https://github.com/dotnet/corefx/pull/42443
