### ISSUE TITLE
Update the adding APIs guide

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#15323]
We need to update https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/adding-api-guidelines.md based on the new engineering changes.

**Comment by ViktorHofer** [comment]
@weshaggard still todo?

**Comment by weshaggard** [comment]
Yes I suspect we need some updates here. I suspect we need updates for most of our docs.

**Comment by ViktorHofer** [comment]
Fixed with https://github.com/dotnet/corefx/commit/f75d8e8d9cb48abe623cf43f649fc49b6b8435d8
