### ISSUE TITLE
System.IO.IsolatedStroage brings System.IO.FileSystem.AccessControl into NETCore.App

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#15337]
See https://github.com/dotnet/corefx/pull/15313#pullrequestreview-17504675

It's undesireable to have this in NETCore.App.  Consider copying the code used System.IO.FileSystem.AccessControl instead.

/cc @weshaggard

**Comment by ViktorHofer** [comment]
It's basically this code which requires System.IO.FileSystem.AccessControl: https://github.com/dotnet/corefx/blob/master/src/System.IO.IsolatedStorage/src/System/IO/IsolatedStorage/Helper.Win32.Unix.cs#L72-L97

AccessControl does not contain a lot source files and it all sticks together. Is it still planned to remove the dependency to System.IO.FileSystem.AccessControl for NETCore.App? If yes, should it be done by moving all files into common and linking them in System.IO.IsolatedStorage? What's exactly the reason that System.IO.FileSystem.AccessControl shouldn't be in NETCore.App?

**Comment by JeremyKuhne** [comment]
> What's exactly the reason that System.IO.FileSystem.AccessControl shouldn't be in NETCore.App?

@weshaggard, @ericstj, can you clarify?

**Comment by weshaggard** [comment]
All of the ACL libraries are intended to be extensions on top of .NET Standard and ship as individual nuget packages for folks that want them. We should try to avoid pulling these dependencies in the the shared framework if we can.

Do we really need to care about setting specific permissions to the directories we create? It is already inconsistent across platforms (as it we only do it on windows), so I'm wondering if it is worth it at all.

**Comment by JeremyKuhne** [comment]
> Do we really need to care about setting specific permissions to the directories we create?

The root folder is shared with the desktop implementation, which ACLs in this way.

**Comment by weshaggard** [comment]
Does that break desktop if we happen to be the one that creates it and doesn't ACL? Also should we consider using a different root folder from desktop to isolate from the other platforms/application types?

**Comment by JeremyKuhne** [comment]
> Does that break desktop if we happen to be the one that creates it and doesn't ACL?

Most likely. Real world may never hit the case where the default ACL isn't enough, but that is probably wishful thinking.

>  Also should we consider using a different root folder from desktop to isolate from the other platforms/application types?

That would prevent loading existing data when running against CoreCLR. The idea is that if folks are using IsoStorage with a given identity for sharing data that it will still work. Think of a specific library running on multiple apps and platforms at the same time.

**Comment by ViktorHofer** [comment]
@weshaggard any plans how to go forward with this issue? Either bring the ACL package into netcoreapp for Windows or link the ACL source in IsolatedStorage. Other options possible?

**Comment by weshaggard** [comment]
When I chatted with @JeremyKuhne about this he said he was going to take a look and if it was easy enough he would just pull in minimal code to set the ACL's but if not then we will just keep the dependency for netcoreapp.

**Comment by ViktorHofer** [comment]
Alright. The last time I looked into the ACL source, it seemed like everything is glue together. I suspect that the minimum code base is like 80% of the lib. But I will also take another look into it.

**Comment by JeremyKuhne** [comment]
Discussed this with @ianhays, we're getting too close to the end of 2.0 to make a change here of this nature. Pushing out so we can try looking at a targeted direct P/Invoke option.

**Comment by ViktorHofer** [comment]
I agree. The change shouldn't be done that close to 2.0

**Comment by ViktorHofer** [comment]
@ericstj If we still want S.I.FileSystem.AccessControl out of NetCoreApp we should start early for the next milestone (2.1) to think about it.

**Comment by ericstj** [comment]
Nothing's changed about the desire to remove this since I opened the issue. We should still reserve the right to remove impl-only assemblies in 2.1, we did it in the past.

@wesgaggard may have an opinion.

You might want to look into just directly p-invoking to CreateDirectory with a security descriptor since you only care about applying the ACL when you create the directory and I bet you can get away with a constant SDDL string, or just port the native code [mentioned in the comment](https://github.com/dotnet/corefx/blob/3c71b7c0e7bb784e48a092d5c8a5ce05251a3606/src/System.IO.IsolatedStorage/src/System/IO/IsolatedStorage/Helper.Win32.cs#L21).

**Comment by ViktorHofer** [comment]
cc @weshaggard as his handle was misspelled above.

**Comment by weshaggard** [comment]
AccessControls definitely one of those dependencies I would like to avoid in the core framework libraries so if we can break this dependency without compromising too much we should do it.

**Comment by JeremyKuhne** [comment]
We've had this in NetCoreApp for multiple versions now, probably not worth removing it at this point.
