### ISSUE TITLE
Ensure we run UAP pinvoke checks regardless of TargetGroup

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#15339]
Previously we'd only check pinvokes if a library specifically targeted UAP.  That would miss the case where a netstandard build would be applicable.

We should change this to run whenever the buildvertical is UAP.  EG: _bc_TargetGroup == uap || _bc_TargetGroup == uapaot.

**Comment by danmosemsft** [comment]
related https://github.com/dotnet/corefx/issues/15303

**Comment by weshaggard** [comment]
@danmosemsft did you handle this with your PR?

**Comment by danmosemsft** [comment]
Yes, by defining UWPCompatible and triggering off that.

**Comment by ericstj** [comment]
Seems like that requires too much manual opt-out.  Any netstandard config would be treated as UWP compatible unless someone opts the project out of it.  We have a better way of doing this.  If you look at how we binplace we calculate if a current configuration is "best" for a given configuration.  We could piggy-back on that logic for enabling UWP.

**Comment by ericstj** [comment]
I'm ok with treating this as an improvement rather than anything blocking 2.x.

**Comment by danmosemsft** [comment]
We're good for now, and in a "fail safe" mode (one must opt out)

**Comment by joperezr** [comment]
mm I'm not sure what's left here, shouldn't it be done already? (done as in we are checking pinvoke on all assemblies and have baselined the errors.)

**Comment by ericstj** [comment]
> that requires too much manual opt-out.

All those baselines become noise and it makes it so no-one pays attention to the failures.  We can determine the right place to run based on other data that's already available: consider that we already know when something is actually part of UAP based on the binplacing logic.

**Comment by wtgodbe** [comment]
@ericstj is there anything still to do here?

**Comment by ViktorHofer** [comment]
Closing as we probably don't want to do this anymore. Feel free to reopen if you disagree.
