### ISSUE TITLE
Span: Win7 Outer Loop test failures in System.SpanTests.SpanTests.ClearNativeLongerThanUintMaxValueBytes

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#15348]
Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_release/lastFailedBuild/consoleText

Message:
~~~
System.OutOfMemoryException : Insufficient memory to continue the execution of the program.
~~~

Stack Trace:
~~~
at System.Runtime.InteropServices.Marshal.AllocHGlobal(IntPtr cb)
           D:\j\workspace\outerloop_win---75d58f69\src\System.Memory\tests\Span\Clear.cs(240,0): at System.SpanTests.SpanTests.ClearNativeLongerThanUintMaxValueBytes()
~~~

Configuration:
OuterLoop_Windows7_release (build#72)

**Comment by danmosemsft** [comment]
@AtsushiKan @KrzysztofCwalina who is the right person to look at this? ie, who is the primary contact for Span.

**Comment by AtsushiKan** [comment]
cc @nietras who added the test. 

Tests that allocate 8Gb memory blocks as test data should probably guard against OOMExceptions and skip the test if it happens...

**Comment by nietras** [comment]
@AtsushiKan yeah that is probably a good idea, it is a pretty hefty test. Didn't know what the policy was regarding this. Would you then assert inconclusive, or simply let the test pass?

**Comment by AtsushiKan** [comment]
I think we have to let the test pass. You could print out a message to the console but it's not clear anyone would monitor it. As long as the allocation occurs often enough, I think we're getting sufficient test coverage for this particular scenario.
