### ISSUE TITLE
System.Reflection.MetadataReader incorrectly decodes signatures with multiple optional modifiers

### ISSUE THREAD

**Issue by mjrousos** [dotnet/corefx#1535]
The metadata reader's signature decoder fails to correctly decode signatures with multiple optional modifiers, often resulting in errant BadFormatExceptions.

For example, the following signature will be encoded as 05-03-20-45-20-69-08-0F-03-09-0F-20-55-03, which the metadata reader is unable to decode:

`.method assembly static pinvokeimpl(/* No map */) 
      vararg int32 modopt([mscorlib]System.Runtime.CompilerServices.IsLong)
      modopt([mscorlib]System.Runtime.CompilerServices.CallConvCdecl) 
  StringCchPrintfW(char* A_0,
                              uint32 A_1,
                              char modopt([mscorlib]System.Runtime.CompilerServices.IsConst)* A_2) 
`.

**Actual behavior** While reading the double-modopt on the return type, the metadata reader erroneously also consumes the first parameter. Because of this, it reads off the end of the blob and throws an incorrect BadImageFormatException.

**Expected behavior** This is a valid signature and should be decoded as follows:
`05`
`03	Parameter count`
`20	modopt // Begin return type`
`45	CallConvCDecl`
`20	modopt`
`69	IsLong`
`08	Int32	`
`0F	ByRef // Begin param 1`
`03	char`
`09	UInt32 // Begin param 2`
`0F	ByRef // Begin param 3`
`20	modopt`
`55	IsConst`
`03	char`

**Comment by mjrousos** [comment]
I'm taking a look at fixing this. 

The bad code is somewhere in \src\System.Reflection.Metadata\src\System\Reflection\Metadata\Decoding\SignatureDecoder.cs, in DecodeMethodSignature.

**Comment by mjrousos** [comment]
Found the issue; running tests on my fix and composing PR...

**Comment by nguerrera** [comment]
Fixed by #1543
