### ISSUE TITLE
[Question] Comments with <SecurityKernel ..> in corefx

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#15374]
There are a bunch of XML doc-like comments with `<SecurityKernel ..>` throughout the repo. See here: https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=SecurityKernel&type=Code I stumbled across an unsafe method in `SortedSet` that was marked with it over [here](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/SortedSet.cs#L1745). Would it be OK to delete these?

**Comment by danmosemsft** [comment]
@karelz what do we currently recommend for code documentation? I don't see this covered in https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md.

**Comment by jkotas** [comment]
` <SecurityKernel ..>` comments are left overs from early version of security transparent/critical code annotations. They can be removed.

**Comment by tarekgh** [comment]
we need then to scan and delete all code under SecurityKernel

**Comment by WinCPP** [comment]
Hi,

This appears to be isolated piece of work and a pretty straightforward task of cleaning up? If my understanding is correct, can I take this up. Being new, it will help me get familiar with code base and processes.

**Comment by karelz** [comment]
Yes, this should be fairly straightforward. I sent you invite for collaborator, let me know when you accept and I can assign it to you ...

**Comment by WinCPP** [comment]
@karelz accepted the invite. Thank you.

**Comment by WinCPP** [comment]
I have done the changes, but I am not able to figure out from developer docs, what to do next i.e. file a review, etc.. Kindly advise.

Also I see that "outer loop" automated tests are failing on few platforms while they are passing on others. I am a bit confused as this was just removal of some code which was already commented... Trying to figure that out what is happening...

**Comment by karelz** [comment]
When you have changes (strong recommendation: in a branch), submit PR on GitHub.
Area owners will review. Don't merge master until the very end. Just react to feedback in your branch (pushes automatically update PR on GitHub).

Both inner and outer loop tests should pass in general. We ask contributors to run inner loop before submitting PR and relevant Outer loop subsets. In this case, I would skip local outer loop test run entirely - it is unlikely you are going to cause any problems, the more in outer loop.
Outer loop tests still contain some unreliable tests :( - we are working through them (e.g. Networking tests reliability is actively worked on).

**Comment by WinCPP** [comment]
@karelz Thanks for the direction, learnt the process while working on this issue. Local inner loop execution was successful. Have created a pull request and will wait for review feedback.

**Comment by karelz** [comment]
Great, thanks for helping out!

If you're interested in more contributions to CoreFX, I would recommend to grab some ['up for grabs' issues](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aopen%20label%3A%22up%20for%20grabs%22%20-label%3Aapi-needs-work) (which are not API proposals)
The most valuable/impactful things are:
1. [2.0.0 (next release) up for grabs](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aopen%20label%3A%22up%20for%20grabs%22%20milestone%3A2.0.0) issues
2. [wishlist](https://github.com/dotnet/corefx/labels/wishlist) issues
3. [simple](https://github.com/dotnet/corefx/labels/simple) issues for newbie contributors (not applied too much yet - we just started experimenting with the label recently)

**Comment by WinCPP** [comment]
@karelz thank you for helping out with the process and stuff, I have good idea about it now. I enjoyed contributing and will look into the above mentioned labels and grab something!

**Comment by jamesqo** [comment]
@WinCPP I see you have submitted a PR to fix this and it was merged. In the future, please put "Fixes #<issue number>" in the description of the PR when submitting a patch that fixes an issue. For example, you could have put "Fixes #15374" in your PR description. That way, GitHub auto-closes that issue once the PR is merged.

**Comment by karelz** [comment]
Thanks for catching it @jamesqo!

**Comment by WinCPP** [comment]
@jamesqo Thank you, got it. Henceforth I'll do this way in the PR:

Title:  "Fixes #<issue_number> - <abstract for the fix>"
Description (comments): "Fixes #<IssueNumber>. <Details>.

I thought just mentioning the issue number in title and description automatically links up.
