### ISSUE TITLE
Fix the System.Diagnostics.Process tests on OS X

### ISSUE THREAD

**Issue by sokket** [dotnet/corefx#1538]
Some System.Diagnostics.Process tests are failing on OS X; root cause the failures and fix whatever is breaking

**Comment by jasonwilliams200OK** [comment]
It seems like an exception is being thrown here: https://github.com/dotnet/corefx/blob/9e6fa8788aacb333c50158bdecfee13ce58fb05c/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessManager.OSX.cs#L63 (`t.key` is either too small or too large).
The Linux counterpart is completely different: https://github.com/dotnet/corefx/blob/9e6fa8788aacb333c50158bdecfee13ce58fb05c/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessManager.OSX.cs#L63

Is there a reason that method (`CreateProcessInfo`) is marked `unsafe` in OSX, but not Linux?

**Comment by sokket** [comment]
There are a few issues I need to sort out in the OS X implementation of the Process class. I'll go back and remember why I marked it as unsafe; I'll also be sure to add you to the PR for feedback when I send it out :)

**Comment by speed2048** [comment]
Any updates to this issue?

**Comment by sokket** [comment]
Not quite yet...this is on my to-do list and should be getting to this soon :) sorry for the delay!

**Comment by stephentoub** [comment]
@sokket, #2185 is an update to this issue :wink:

**Comment by sokket** [comment]
Just saw that; that's what I get for taking 1 vacation day, the PR email was buried!

**Comment by stephentoub** [comment]
Yeah, let that be a lesson to you :wink: Hehe.
