### ISSUE TITLE
Replace or Remove Internal ExcludeFromCodeCoverageAttribute?

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#15387]
We now have two versions of `System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute`, the [publicly exposed version available to client code](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Tools/src/System/Diagnostics/CodeAnalysis/ExcludeFromCodeCoverageAttribute.cs) and the [internal version used through directly including the file](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Diagnostics/CodeAnalysis/ExcludeFromCodeCoverageAttribute.cs).

Potentially the two could cause ambiguity. They also differ in two ways.
1. The internal version can be applied to assemblies. `ExcludeFromCodeCoverageAssemblyAttribute` was introduced to explicitly fit this purpose and reduce incompatibility of use.
2. The internal version is marked as `[Conditional("DEBUG")]`, reducing bloat in release assemblies.

There are four things that can be done with this:
1. Leave things as they are. Pro: Don't fix what ain't broke. Con: Potential for ambiguity.
2. Remove the internal version, update to use the public version. Pro: Simple. Dogfooding. Con: Will bloat the release assemblies with attributes that aren't useful in release.
3. As above, but also change the public version to be `[Conditional("DEBUG")]`. Pro: As above and also reduce size of client release assemblies. Con: API change. While coverage of release builds is always likely to be strange, it may be still be used by someone and the effect undesirable.
4. Merge the internal version with `ExcludeFromCodeCoverageAssemblyAttribute` into a single `ExcludeFromCodeCoverageInternalAttribute` and use it consistently throughout. Pro: No bloat. No conflict with public API. Con: Not dogfooding. Introduces a difference in how we code corefx and how other projects are coded. Likely to be missed by new contributors, (or just anyone who didn't see this issue) who would expect to use `ExcludeFromCodeCoverageAttribute` as usual.

**Comment by karelz** [comment]
cc @danmosemsft @stephentoub @weshaggard

The size bloat is IMO negligible - it is per assembly attribute (so <50B), but may add AssemblyRef.
If adding the AssemblyRef doesn't cause troubles in layering, etc., I would vote for [2] -- remove the internal version. Otherwise [4] is reasonable option.

Re [3] (API change) - that would be potentially too breaking (and I think divergence from Desktop / .NET Standard). I would not do that.

**Comment by weshaggard** [comment]
I wouldn't go with option [3] because that might break other scenarios. I think I would go with option [2] and update the public version of this attribute to allow it to be applied to assemblies as well and just remove our internal version.

**Comment by JonHanna** [comment]
The assembly part isn't a problem, the uses on assemblies have all been replaced with a different attribute so the remaining uses of the internal version are compatible with the public version. The question is whether there's a remaining potential for either code-level ambiguity or developer-level confusion in there the remaining uses of an internal type with the same full name as a public type.

**Comment by weshaggard** [comment]
If we are using the internal version the same as we would the public version then that is even a stronger case to me to remove the internal version. I don't think the conditional on debug adds enough value to have the duplicated definition.

**Comment by danmosemsft** [comment]
We don't even use this attribute right now as far as I can see so there shouldn't be any bloat. I would go with [2]

**Comment by terrajobst** [comment]
Agree with @karelz and @weshaggard. Code bloat is negligible but having the attribute in release can make it easier for components that want to simplify their customer's life.

**Comment by JonHanna** [comment]
There's about a hundred or so cases. I think [2] is the winner for sure. I'll submit a PR to do this later today.

**Comment by karelz** [comment]
Thanks @JonHanna!

**Comment by tmat** [comment]
Updating the public version to be applicable on assembly level would be useful. For the purpose of Live Unit Testing we have added a property to .csproj to make it possible for users to exclude the entire project (assembly) from code coverage. If the attribute is available on assembly level future versions of test tools could recognize it.

**Comment by JonHanna** [comment]
@tmat someone who wants that can do the same as was done with `ExcludeFromCodeCoverageAssemblyAttribute` here. That said I do think it would be a good extension of the current API (despite it making my recent efforts pointless :smile:)

**Comment by tmat** [comment]
@JonHanna Yes, but it's not a "first class" solution. Defining internal attributes that collide with public ones leads to issues. Also tool vendors will likely be reluctant to check for the attribute on assembly level unless it's a proper public API.

**Comment by JonHanna** [comment]
API change issue time?
