### ISSUE TITLE
EPPlus.Core incompatible with .NETFramework,Version=v4.5.2.

### ISSUE THREAD

**Issue by wisam84** [dotnet/corefx#15388]
i want to user EPPlus.Core  put when i install it i receive error 
One or more packages are incompatible with .NETFramework,Version=v4.5.2.

my project.json:

"dependencies": {
    "BundlerMinifier.Core": "2.2.306",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.Extensions.CommandLineUtils": "1.0.0",
    "Microsoft.AspNetCore.Mvc.ViewFeatures": "1.1.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore.Design": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.Relational": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
    "Microsoft.VisualStudio.Web.CodeGeneration": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": "1.0.0-preview2-final",
    "Microsoft.jQuery.Unobtrusive.Ajax": "3.2.3",
    "Microsoft.AspNetCore.Mvc.Core": "1.1.0",
    "Sakura.AspNetCore.Mvc.PagedList": "2.0.11",
    "Sakura.AspNetCore.PagedList": "2.0.1",
    "Sakura.AspNetCore.Mvc.TagHelpers": "1.2.1",
    "SendGrid.NetCore": "1.0.0-rtm-00002",
    "EPPlus.Core": "1.2.0"
  },
  "frameworks": {
    "net452": {}
  },
  "netcoreapp1.0": {
    "imports": [ "portable-net451+win8" ],
    "buildOptions": {
      "emitEntryPoint": true
    },
    "dependencies": {
      "Microsoft.NETCore.App": {
        "type": "platform",
        "version": "1.0.0-*"
      }
    }
  },
  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },
  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  },
  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.Extensions.SecretManager.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8"
      ]
    },
    "BundlerMinifier.Core": {
      "version": "2.1.258",
      "imports": [ "portable-net45+win8+wp8+wpa81" ]
    }
  }

**Comment by karelz** [comment]
@ericstj any advice here? Or should we direct the question to EPPlus / EPPlus.Core owners?

**Comment by ericstj** [comment]
The EPPlus.Core package supports netstandard1.3.  NETStandard1.3 is supported by .NET 4.6, not .NET 4.5.2.  See https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.3.md.  You can retarget your application to net46 or ask the EPPlus.Core owners to make a version that supports netstandard1.2 or cross-compiles for net452.

**Comment by wisam84** [comment]
thank you I retarget  my app to net46 and its work
