### ISSUE TITLE
Add Sybsystem.WindowsBootApplication enum value

### ISSUE THREAD

**Issue by michaelcfanning** [dotnet/corefx#15390]
The value is being emitted in current Windows EFI binaries. We should add to SRM Subsytem enum.

### Proposal

```C#
enum Subsystem
{
   ...
   WindowsBootApplication = 16
}
```

### Details

The value is documented in Windows docs:

IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION
16	Boot application.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms680339(v=vs.85).aspx

**Comment by danmosemsft** [comment]
Does this belong in the coreCLR repo? I'm not sure what SRM is.

**Comment by michaelcfanning** [comment]
This is a problem report for the System.Reflection.Metadata portable executable reading code.

**Comment by michaelcfanning** [comment]
Relevant enum is in PEFileFlags.

https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEFileFlags.cs

**Comment by tmat** [comment]
Let's call this value ```WindowsBootApplication```

**Comment by tmat** [comment]
@terrajobst @weshaggard New public enum value.

**Comment by karelz** [comment]
@tmat please follow the [API review process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md) - please update the top post with structured API proposal (see [example](https://github.com/dotnet/corefx/issues/271)) - API shape, motivation, use cases.

**Comment by tmat** [comment]
@karelz This is just a new enum value. I though we agreed on light process for trivial changes like this.

**Comment by karelz** [comment]
@tmat lightweight is reasonable, but please keep in mind the time of all folks who have to read this, Get the context from several replies, etc.
Yes, we could eventually piece it together, but if everyone did that, we would wastes hours doing just that. Imagine yourself in our place ... going through ~10 API reviews in areas you don't have nearly any background ;-) Wouldn't you want a short story telling the point? (couple of sentences)

**Comment by tmat** [comment]
@karelz OK, I have cleaned up this issue.

**Comment by karelz** [comment]
Thanks! Now it is pretty clear (even to me) just from the top post.

**Comment by karelz** [comment]
BTW: You don't need to ping folks for API review - just the label is enough, we always look at the entire query api-ready-for-review. And we try to finish at least few simple ones in each session.

**Comment by tmat** [comment]
@karelz OK. Thanks

**Comment by karelz** [comment]
@tmat feedback (from the room) for future: Please provide as well namespace / assembly, so that we don't have to look it up.

**Comment by karelz** [comment]
API review: Approved (it is Metadata.Reader existing enum)

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/pull/16509

**Comment by karelz** [comment]
Thanks for your contribution @reaction1989!
