### ISSUE TITLE
OuterLoop_Windows10_release: Test "System.Numerics.Tests.divremTest.RunDivRemTests" failed with "System.Exception"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#15395]
Failed test: System.Numerics.Tests.divremTest.RunDivRemTests

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_release/77/

Message: 
~~~
System.Exception : VerifyDivRemString failed: make 92 125 192 198 117 183 180 87 56 15 18 178 228 7 181 238 94 7 185 165 233 141 178 201 200 177 252 196 42 81 206 148 34 113 177 endmake make 102 173 213 220 61 239 134 134 176 47 135 119 32 155 128 132 229 113 135 207 203 246 253 195 187 239 44 230 64 125 144 endmake bDivRem Xunit.Sdk.EqualException: Assert.Equal() Failure
        Expected: 0
        Actual:   31122745322556859589923417330907291586
~~~

Stack Trace:
~~~
at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\EqualityAsserts.cs:line 35
           at System.Numerics.Tests.StackCalc.VerifyOutParameter() in D:\j\workspace\outerloop_win---6835b088\src\System.Runtime.Numerics\tests\BigInteger\stackcalculator.cs:line 252
           at System.Numerics.Tests.divremTest.VerifyDivRemString(String opstring) in D:\j\workspace\outerloop_win---6835b088\src\System.Runtime.Numerics\tests\BigInteger\divrem.cs:line 187
        ---- Assert.Equal() Failure
        Expected: 0
        Actual:   31122745322556859589923417330907291586
~~~

Configuration:
OuterLoop_Windows10_release (build#77)

**Comment by danmosemsft** [comment]
@mellinoe we're in luck the logging I added in https://github.com/dotnet/corefx/issues/7806 has borne fruit. Thoughts?

**Comment by danmosemsft** [comment]
Note there at least 2 failure modes based on the "Actual", as seen in #7806. One of the failures, on Ubuntu, had the same "Actual" as this Windows one. Which means apparently it's not an OS specific issue so ?hopefully not a code gen issue.

**Comment by axelheer** [comment]
The `VerifyOutParameter` asserts using `MyBigIntImp.outParam`, which is a static property. Thus, we can have a race condition within `VerifyOutParameter`, which sets `MyBigIntImp.outParam` to `0` after the assert too. But I don't know how much the tests run in parallel (`VerifyOutParameter` is only in use by `divremTest`)...

But the output doesn't make sense anyway, since the correct result should be `-197022403284930656083953483303206635131998865544744656916521675032349004442`.

I just copied `StackCalc` and `MyBigIntImp` to an empty .NET Core 1.1 project and added:

    var opstring = "make 92 125 192 198 117 183 180 87 56 15 18 178 228 7 181 238 94 7 185 165 233 141 178 201 200 177 252 196 42 81 206 148 34 113 177 endmake make 102 173 213 220 61 239 134 134 176 47 135 119 32 155 128 132 229 113 135 207 203 246 253 195 187 239 44 230 64 125 144 endmake bDivRem";

    var calc = new StackCalc(opstring);
    while (calc.DoNextOperation())
    {
            var sn = calc.snCalc.Peek();
            var my = calc.myCalc.Peek();

            Console.WriteLine("Peek: {0} vs. {1}", sn, my);
            Console.WriteLine("Out: {0} vs. {1}", calc._snOut, MyBigIntImp.outParam);

            Assert.Equal(sn, my);
            calc.VerifyOutParameter();
    }

**Comment by danmosemsft** [comment]
@mellinoe thoughts?

**Comment by mellinoe** [comment]
@Jiayili1 You have linked to the "lastFailedBuild" of this test configuration, so I don't think the link is valid anymore; it doesn't show the test failures for this issue. I believe this is the run that failed: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_release/77/

**Comment by mellinoe** [comment]
> The VerifyOutParameter asserts using MyBigIntImp.outParam, which is a static property. Thus, we can have a race condition within VerifyOutParameter, which sets MyBigIntImp.outParam to 0 after the assert too. But I don't know how much the tests run in parallel (VerifyOutParameter is only in use by divremTest)...

Although this whole thing is a bit crazy, I don't think there's a direct problem here because test cases within the same class shouldn't be running in parallel, and, like you said, this field is only ever touched in the `divremTest` class.

**Comment by mellinoe** [comment]
> But the output doesn't make sense anyway, since the correct result should be -197022403284930656083953483303206635131998865544744656916521675032349004442.

I repeated your experiment and that looks accurate to me as well.

**Comment by Jiayili1** [comment]
@mellinoe Thanks for the right link, I have updated the link in the details.

**Comment by danmosemsft** [comment]
@mellinoe this failed again, broke the Win10 debug run. What's the next step here?

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_debug/lastCompletedBuild/testReport/System.Numerics.Tests/divremTest/RunDivRemTests/ 

```
MESSAGE:
System.Exception : VerifyDivRemString failed: make 189 121 48 40 223 48 126 202 192 27 166 202 4 236 166 102 118 28 193 39 174 200 167 188 202 44 211 174 246 176 125 111 209 85 34 98 145 4 24 246 46 54 52 158 176 204 19 132 94 208 57 68 208 29 49 245 210 116 94 178 92 208 211 15 157 55 249 174 202 67 212 114 4 endmake make 249 120 148 8 11 253 25 79 79 38 119 57 158 179 36 44 144 29 166 102 153 93 98 36 1 121 211 100 186 26 251 198 64 6 36 185 97 201 104 96 153 endmake bDivRem Xunit.Sdk.EqualException: Assert.Equal() Failure\r\nExpected: 0\r\nActual: 31122745322556859589923417330907291586\r\n at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in C:\\BuildAgent\\work\\cb37e9acf085d108\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 35\r\n at Xunit.Assert.Equal[T](T expected, T actual) in C:\\BuildAgent\\work\\cb37e9acf085d108\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 20\r\n at System.Numerics.Tests.StackCalc.VerifyOutParameter() in D:\\j\\workspace\\outerloop_win---097a300f\\src\\System.Runtime.Numerics\\tests\\BigInteger\\stackcalculator.cs:line 250\r\n at System.Numerics.Tests.divremTest.VerifyDivRemString(String opstring) in D:\\j\\workspace\\outerloop_win---097a300f\\src\\System.Runtime.Numerics\\tests\\BigInteger\\divrem.cs:line 190\r\n---- Assert.Equal() Failure\r\nExpected: 0\r\nActual: 31122745322556859589923417330907291586
+++++++++++++++++++
STACK TRACE:
at System.Numerics.Tests.divremTest.VerifyDivRemString(String opstring) in D:\j\workspace\outerloop_win---097a300f\src\System.Runtime.Numerics\tests\BigInteger\divrem.cs:line 196 at System.Numerics.Tests.divremTest.RunDivRemTests() in D:\j\workspace\outerloop_win---097a300f\src\System.Runtime.Numerics\tests\BigInteger\divrem.cs:line 129 ----- Inner Stack Trace ----- at System.Numerics.Tests.StackCalc.VerifyOutParameter() in D:\j\workspace\outerloop_win---097a300f\src\System.Runtime.Numerics\tests\BigInteger\stackcalculator.cs:line 250 at System.Numerics.Tests.divremTest.VerifyDivRemString(String opstring) in D:\j\workspace\outerloop_win---097a300f\src\System.Runtime.Numerics\tests\BigInteger\divrem.cs:line 190
```

**Comment by Clockwork-Muse** [comment]
@danmosemsft - Are we assuming it's just a problem in the tests, and cleanup/updating it for a more "correct" approach would solve the problem?  I have some prelim work I did a while back, but haven't had a chance to work on it recently.  Or is it that we probably have an issue in the actual class?

**Comment by danmosemsft** [comment]
I don't know. Worst case it's a code gen issue. @mellinoe can say something more useful.

**Comment by mellinoe** [comment]
I don't have anything incredibly useful yet, as I haven't investigated very deeply. The investigation I did above mirrored what @axelheer had found: the inputs/outputs from the test logging don't line up with what I saw when I ran the code manually in a console application, and I wasn't able to otherwise reproduce the problem. I'm also fearing that it is a codegen problem.

**Comment by Jiayili1** [comment]
Failed again on build 20170322.02, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170322.02/workItem/System.Runtime.Numerics.Tests/analysis/xunit/System.Numerics.Tests.divremTest~2FRunDivRemTests

**Comment by Jiayili1** [comment]
Failed again here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_debug/141/testReport/System.Numerics.Tests/divremTest/RunDivRemTests/

**Comment by karelz** [comment]
@mellinoe did you make any progress on this one?
If it is a bad CodeGen, we might need to focus on it earlier to avoid last minute fire-drills.

**Comment by mellinoe** [comment]
No, no progress on this one.

**Comment by karelz** [comment]
Can you please prioritize it - it is one of the riskier ones ... and it might take time to chase down actionable info.

**Comment by mellinoe** [comment]
I'll try again to get a repro for this today.

**Comment by karelz** [comment]
Great, thanks!

**Comment by mellinoe** [comment]
I was able to get a few repros by running all of the System.Runtime.Numerics tests in parallel for several thousand iterations. All of the input data was different for the failures, and the same input data does not produce failures on subsequent attempts. I've created a test case which uses a set of input data which caused a failure and it is not causing failures when run in parallel by itself.

So I really suspect that this is something codegen-related or otherwise separate from the test logic itself.

**Comment by karelz** [comment]
@mellinoe do you plan to investigate it further?
We can ask stress-gurus to look at the dumps or repro otherwise ...

**Comment by danmosemsft** [comment]
May be time to bring in code gen folks. I imagine they have some approaches they use eg enable some test flags

**Comment by mellinoe** [comment]
I've looked at things a bit more, and I think I'm going to reverse what I said before about the shared static field: it is a problem. That public static field isn't being read anywhere other than the divrem tests, but it is written to in at least one other case: https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Numerics/tests/BigInteger/Driver.cs#L180.

That is in a different test class, so it will be run in parallel with the divrem tests. This can cause the static field to get stomped over in the middle of divrem test cases. I'm going to turn off test parallelization and see if the issue repros.

**Comment by mellinoe** [comment]
By the way, that test case I linked to is an outer loop test. It looks like we've only seen this issue in outer loop runs, so that matches up with what I'm suspecting.

**Comment by mellinoe** [comment]
https://github.com/dotnet/corefx/issues/17501 will fix this.
