### ISSUE TITLE
Lots of failures while open .sln files in VS

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#15401]
I tried to open the System.Net.Primitives.sln file in VS.  I get ~40 errors about projects failing to load, the actual src .csproj ends up not loading so the source isn't editable, and the solution explorer is messed up with regards to what folders contains what projects.
cc: @weshaggard

**Comment by weshaggard** [comment]
@karajas can you please have a look.

**Comment by weshaggard** [comment]
@stephentoub I didn't open every solution file but I did build them all from the command line so I expect the should work now after https://github.com/dotnet/corefx/pull/15738. Please let me know if you see otherwise.

**Comment by stephentoub** [comment]
Thanks, Wes!  I'll let you know if I run into this in other places.
