### ISSUE TITLE
OuterLoop_Win7_Debug: "WellKnownSidTypeTests" failed: need to disable tests when not a domain user

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#15421]
Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_debug/lastFailedBuild/consoleText

Failed test: WellKnownSidTypeTests.CanCreateSecurityIdentifierFromWellKnownSidType

Message:
~~~
System.ArgumentNullException : The domainSid parameter must be specified for creating well-known SID of type AccountPolicyAdminsSid.
        Parameter name: domainSid
~~~

Stack Trace:
~~~
D:\j\workspace\outerloop_win---b280fd23\src\System.Security.Principal.Windows\src\System\Security\Principal\SID.cs(628,0): at System.Security.Principal.SecurityIdentifier..ctor(WellKnownSidType sidType, SecurityIdentifier domainSid)
           D:\j\workspace\outerloop_win---b280fd23\src\System.Security.Principal.Windows\tests\WellKnownSidTypeTests.cs(114,0): at WellKnownSidTypeTests.CanCreateSecurityIdentifierFromWellKnownSidType(WellKnownSidType sidType)
~~~

Message:
~~~
System.ArgumentException : The parameter is incorrect
        Parameter name: sidType/domainSid
~~~

Stack Trace:
~~~
D:\j\workspace\outerloop_win---b280fd23\src\System.Security.Principal.Windows\src\System\Security\Principal\SID.cs(662,0): at System.Security.Principal.SecurityIdentifier..ctor(WellKnownSidType sidType, SecurityIdentifier domainSid)
           D:\j\workspace\outerloop_win---b280fd23\src\System.Security.Principal.Windows\tests\WellKnownSidTypeTests.cs(114,0): at WellKnownSidTypeTests.CanCreateSecurityIdentifierFromWellKnownSidType(WellKnownSidType sidType)
~~~

Configuration:
OuterLoop_Windows7_debug (build#75)

**Comment by danmosemsft** [comment]
Two distinct failues. For the first one, it's because `WindowsIdentity.GetCurrent().Owner.AccountDomainSid;` is returning null. That comes from Win32 `GetWindowsAccountDomainSid` and one way that can give null is on `ERROR_NON_ACCOUNT_SID` which means ` The security identifier provided is not from an account domain`. Could it be the machine did not join the domain successfully?

**Comment by Jiayili1** [comment]
This issue is repro on build 20170125.02, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170125.02/workItem/System.Security.Principal.Windows.Tests/analysis/xunit/WellKnownSidTypeTests~2FCanCreateSecurityIdentifierFromWellKnownSidType(sidType:%20AccountAdministratorSid)

Message:
~~~
System.ArgumentNullException : The domainSid parameter must be specified for creating well-known SID of type AccountAdministratorSid.\r\nParameter name: domainSid
~~~

Stack Trace:
~~~
  at System.Security.Principal.SecurityIdentifier..ctor(WellKnownSidType sidType, SecurityIdentifier domainSid)
   at WellKnownSidTypeTests.CanCreateSecurityIdentifierFromWellKnownSidType(WellKnownSidType sidType)
~~~

Failed Configurations:
Windows.10.Amd64

**Comment by steveharter** [comment]
I will debug locally on win7 in a few minutes and report back

**Comment by steveharter** [comment]
I was able to repro the failures on both win10 and win7 when I run the tests as local Administrator, which makes sense as that is not a domain account. When I run as myself, the tests pass. Do we run as different users based on test platform \ infra?

**Comment by weshaggard** [comment]
Yes this is the same issue as https://github.com/dotnet/corefx/issues/15436. We need to disable these for running under admin or get the account a different way.
