### ISSUE TITLE
AsyncLocal has a different behaviour than CallContext

### ISSUE THREAD

**Issue by fitzchak** [dotnet/corefx#15423]
See this question on StackOverflow:
http://stackoverflow.com/questions/41825375/why-asynclocal-is-different-from-callcontext

In the bellow code I expected the value of AsyncLocal to be unique per thread as the documentation says it should behave and as CallContext behaves.

https://gist.github.com/fitzchak/de6af938a4bd3c5fb683bca594734e9f

**Comment by benaadams** [comment]
You thinking of `ThreadLocal`? AsyncLocal can flow across threads as it says

> Because the task-based asynchronous programming model tends to abstract the use of threads, AsyncLocal<T> instances can be used to **persist data across threads**.

**Comment by fitzchak** [comment]
Yes, I indeed wanted to use ThreadLocal, but was mistaken do to posts like:
http://stackoverflow.com/questions/31707362/how-do-the-semantics-of-asynclocal-differ-from-the-logical-call-context
Thanks!
