### ISSUE TITLE
Use bootstrap.ps1/sh instead of init-tools.cmd/sh

### ISSUE THREAD

**Issue by dagood** [dotnet/corefx#15427]
Right now, CoreFX uses `init-tools.cmd` and `init-tools.sh` to restore and set up BuildTools. There is a new BuildTools setup flow that CLI and BuildTools use called bootstrap that allows significantly more code sharing by directly downloading a BuildTools script which handles further steps.

This reduces the complexity in CoreFX itself and reduces the chance the BuildTools init flow diverges from other repositories' (like CoreCLR's). The bootstrap flow is also easier to improve, because the improvements only need to be done in one place rather than being ported across many repos. See https://github.com/dotnet/buildtools/issues/558.

Living list of things that should be fixed before CoreFX adoption (feel free to edit):

 * Make script download repeatable. Currently it downloads the latest in a branch, but a commit hash should be used. This is the case for the bootstrap.ps1/sh download and the dotnet-install.ps1/sh download inside the bootstrap script. https://github.com/dotnet/buildtools/issues/1225
 * A change in CLI version but not BuildTools doesn't re-init the `Tools` directory. https://github.com/dotnet/buildtools/issues/1192

Any other known issues pre-CoreFX adoption, @weshaggard @crummel ?

/cc @ellismg @dleeapho @markwilkie

**Comment by jkotas** [comment]
> allows significantly more code sharing 

Can you quantify significantly more code sharing? As far as I can tell, this allows sharing of ~150 lines in `init-tools.*` script that are not shared today at the cost of more fragile and harder to debug system.

**Comment by dagood** [comment]
Here's what's in a few repos right now:

| repo | cmd | sh | total lines |
| --- | --- | --- | --- |
corefx | 86 | 172 | 258
coreclr | 90 | 168 | 258
wcf | 83 | 169 | 252

I agree that this is more fragile, but I think sharing code would actually make it easier to maintain better debugging capability.

Your comment gave me the idea that we *could* inline the bootstrap script into each repo using the auto-upgrade system... might be worth considering to cut that script download dependency but keep sharing and maintainability.

**Comment by weshaggard** [comment]
>Your comment gave me the idea that we could inline the bootstrap script into each repo using the auto-upgrade system... might be worth considering to cut that script download dependency but keep sharing and maintainability.

I do think that idea is worth investigating further. If we can eliminate the manual maintenance cost then I have less concern with the duplication.

**Comment by weshaggard** [comment]
If we do still have a downloadable script we also need to figure out the correct end-point to download it from (in particular a secure end-point) as well as try and figure out a workflow if there are networking outages.

**Comment by dagood** [comment]
About auto-upgrading a checked-in bootstrap script: the new work is straightforward. We just need a new type of upgrader in VersionTools that can look at build-info to find out the last-built BuildTools SHA and download the current bootstrap scripts.

That leaves that idea with dependencies on known TODOs. Setting up BuildTools to publish to dotnet/versions is in the current sprint, but publishing the commit SHAs is backlogged. In CoreFX, the commit SHA is baked into the package--we could add that to BuildTools to give the upgrader a workaround path to find the SHA. (dotnet/versions BuildTools version -> download package -> examine file inside package.)

I realized that since bootstrap uses dotnet-install from CLI, we would also need to inline/upgrade that. Not sure if 4 vs. 2 inlined script files is a problem. I'm also not sure if programmatically finding last-build CLI SHA is solved yet or not.

---

A thought on keeping downloads, but making them reliable: we could start publishing the scripts during BuildTools+CLI builds to versioned locations in a blob store we control. For offline scenarios, we can make it easy to point to a disk location. This would also let the product share the BuildTools package version as the stable pointer to the scripts, rather than commit SHA. If CLI can't maintain the install files in this way, the BuildTools build could fetch and upload the current dotnet-install script alongside where it puts bootstrap.

**Comment by weshaggard** [comment]
The more I think about this the more I like the idea of an auto-updating script over requiring every clone or build to hit the network each time to pull down a script. The more networking we can eliminate from our normal builds the better. 

Davis can you add a something to the engineering backlog to add the necessary support for publishing files that can be consume directly in other repo's via an "update" command.

**Comment by ViktorHofer** [comment]
Outdated in favor of arcade and removal of buildtools.
