### ISSUE TITLE
ApiCompatBaseline files are being regenerated differently outside Windows

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#15445]
When I build on Ubuntu 16.04, two ApiCompatBaseline.txt files are being regenerated, but they aren't when I build on Windows (or presumably when anyone builds on Windows). Here is the diff that gets created:

https://github.com/mellinoe/corefx/commit/d874d888467bc6eaf0389cc9d6b6957227ce0d80

It looks like the elements are being written in a different order. On top of that, there does seem to be some inconsistency [related to the signing key](https://github.com/mellinoe/corefx/commit/d874d888467bc6eaf0389cc9d6b6957227ce0d80#diff-0caf4b2ecb4243f5ded14afbef2d9754R1) used for System.IO.Compression.ZipFile? 

@weshaggard

**Comment by akoeplinger** [comment]
I noticed a similar issue when running GenAPI.exe on OSX, it generates API signatures in a different order. Maybe the same underlying problem?

**Comment by mellinoe** [comment]
That does sound related, and both of these tools (ApiCompat/GenAPI) use functionality from the same library if I'm not mistaken.

**Comment by weshaggard** [comment]
>DEFAULT_APPNAME Warning: 0 : Found 'System.IO.Compression.ZipFile' with PublicKeyToken 'b03f5f7f11d50a3a' instead of 'b77a5c561934e089'.

That looks a real issue. We must not be using the ECMA (b77) key on the linux builds for that library.

The other diffs seems more likely caused by the IL metadata in the assemblies they are reading. Could one of you guys take a look at the output binary to see if the IL order seems to be different between windows and linux in a similar manor. At this point my best guess is that csc is outputing the IL in a different order for some reason.

**Comment by mellinoe** [comment]
> That looks a real issue. We must not be using the ECMA (b77) key on the linux builds for that library.

See #15479

**Comment by akoeplinger** [comment]
@weshaggard I diffed the assemblies compiled on OSX and Windows and they are identical. Looks like an issue with how GenAPI or the underlying metadata reader processes the assemblies.

**Comment by akoeplinger** [comment]
I found out the root cause, see https://github.com/dotnet/corefx/issues/15825

PR to fix in buildtools: https://github.com/dotnet/buildtools/pull/1320
