### ISSUE TITLE
ApiPort: consider other output formats in addition to xlsx

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/corefx#1545]
Right now, the [ApiPort](http://www.microsoft.com/en-us/download/details.aspx?id=42678) tool only outputs xlsx.

It'd be nice if it'd also output XML and JSON (for feeding into other tools). @richlander told me it already outputs HTML for use inside VS, so hooking that up to the console version might be nice as well.

**Comment by weshaggard** [comment]
I believe it also supports a csv output as well but this is a feature request for some of the ApiPort folks @MattGal @twsouthwick

**Comment by mjrousos** [comment]
Yes, internally it already outputs to xlsx and json. We're working on getting these (and other changes) made public in an ApiPort-specific repo (as well as pushed live at the link @akoeplinger mentioned).

**Comment by twsouthwick** [comment]
Yes, this is already available. Please update to the newest drop. Outputs for excel, html, and json are supported - if another format is desired, please submit a PR with an implementation of `Microsoft.Fx.Portability.IReportWriter` at http://GitHub.com/Microsoft/dotnet-apiport.
