### ISSUE TITLE
Complex.Asin gives bad values for extreme arguments

### ISSUE THREAD

**Issue by dcwuser** [dotnet/corefx#15455]
For all Complex values z in the representable range, the value of asin(z) lies in the representable range. For example for large real m ~ Double.MaxValue, asin(m) ~ \pi / 2 + \ln (2 m) i ~ 1.5708 + 710.476 i. (The sign of the imaginary part may change depending on the phase convention, but the magnitude shouldn't.) But the Complex.Asin method returns NaNs for these arguments, and indeed for more arguments with |z| > Sqrt(Math.Double), presumably because of internal overflow when calculating z * z. Complex.Acos similiarly gives unnecessary NaNs for large arguments. These methods should be fixed so as to give accurate results over the entire representable range.

**Comment by krwq** [comment]
Reopening because following test case is still disabled:
```
System.Runtime.Numerics/tests/ComplexTests.cs:443:        [ActiveIssue(15455)]
```

**Comment by krwq** [comment]
cc: @ViktorHofer @danmosemsft
