### ISSUE TITLE
Are constant-folding and checks in Microsoft.CSharp.RuntimeBinder useful.

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#15467]
#15464 notes a bug in the constant-folding RuntimeBinder does, but considering that with the code emitted by the C# compiler when used with `dynamic` such checks and folding would already be done prior to the dynamic binding, is this constant-folding useful? Is the cost of checking if they can be applied when binding worth the benefit gained when running? Would it be better to just always evaluate at runtime?

One downside I can definitely see to removing them is the difference in exceptions thrown, but if that currently isn't correct anyway, it's not that big a loss.

**Comment by JonHanna** [comment]
One disadvantage in not having constant-folding is that there are expressions that are treated differently compile-time to runtime, like `unchecked(int.MinValue / 1)`. But that doesn't work as per compile-time C# right now either, so not that big a loss either?

**Comment by JonHanna** [comment]
There's enough bugs in this that I'm doubtful that anything is making any use of it.

In favour of keeping it and fixing it is that it *could* be used in the future, (if you don't build it, they won't come). Even then though it won't be fully equivalent to folding by a compiler as it can only be done with a single operation, e.g. `3 + 4 + 2` can only be folded to `7 + 2` not to `9`.

**Comment by VSadov** [comment]
need to think/experiment about this.

On one side the bider does generate instance restrictions for rules when arguments are literals, so it intentionally tries to specialize on the values (not just types). I wonder how often this works and how large the benefits are for constant-folded operations. 
I.E.  if it specializes `i + 0` to `{<int>, <int, 0>}` and folds it to be just `i`, then it needs to check that the second argument is `0` in that rule. Is that even faster?

I also see limitations on the folding applicability. 

Can you even hit `unchecked(int.MinValue / 1)` bug via use of `dynamic` ?

**Comment by JonHanna** [comment]
The only difference that can be hit through `dynamic` AFAICT is that `someDynamic / 0` should throw `RuntimeBinderException` but throws `DivideByZeroException`. It would be easy enough to fix that while also removing the rest of the constant folding, though ironically it is for the same reason the one bit in #15537 that could break someone.

**Comment by JonHanna** [comment]
> I wonder how often this works and how large the benefits are for constant-folded operations.

Not at all. In #15537 I only tried to fix the constant binding that was already attempted, and apart from the empty `IsDivByZero` it only affects folding of operations with two constant operands.

**Comment by VSadov** [comment]
As I see documentation for parts of C# dynamic binder like https://msdn.microsoft.com/en-us/library/microsoft.csharp.runtimebinder.csharpargumentinfo(v=vs.110).aspx  do not recommend using them directly from code. And I doubt anyone does, unless trying to mimic C# compiler.

On the C# compiler side, considering that `const dynamic` can only have a value of `null`, not `1` or `0`, I do not see how constant folding is actually reachable. Unless someone does it intentionally via the APIs, for which the only documentation is the one that says "do not use".

Anything that can be folded should be folded at compile time and nothing can be folded at dynamic bind-time.

I start feeling that all this constant-folding deal in the runtime binder should be just removed. 
I wonder if anything, besides the code that directly tests the folding, will be affected at all.

**Comment by VSadov** [comment]
Basically, I think we should keep/fix the folding only if it is reachable through `dynamic` and I cannot find how to do that.

**Comment by JonHanna** [comment]
> I wonder if anything, besides the code that directly tests the folding, will be affected at all.

We don't even have any of that. It was in adding some that I realised it was quite buggy.

>  I do not see how constant folding is actually reachable

It's not for two constants. A dynamic expression with one dynamic and once constant or literal is easily enough done, but that doesn't affect folding. It *does* affect the handling of division by constant zero, though that's the one thing that could be a breaking change to fix.
