### ISSUE TITLE
Microsoft.CSharp.RuntimeBinder constant folding incorrect in several ways

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#15464]
Given:

```C#
var x = CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.Constant, null);
var y = CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.Constant, null);
var binder = Microsoft.CSharp.RuntimeBinder.Binder.BinaryOperation(CSharpBinderFlags.None, ExpressionType.Divide, GetType(), new[] {x, y});
var callsite = CallSite<Func<CallSite, object, object, object>>.Create(binder);
callsite.Target(callsite, 8, 0);
```

We would expect the last line to throw a `RuntimeBinderException` due to the divide by constant zero.

Instead it throws `OverflowException` (in debug it throws an assertion failure). Of the other integer types, `uint`, `long` and `ulong` will all throw a `DivideByZeroException` while all the others throw `OverflowException`.

**Comment by karelz** [comment]
Any compat concerns?

**Comment by JonHanna** [comment]
I'm not sure. I'm wondering (out loud over at #15467) if this would be hit outside of someone actively testing it. While that removes the risk of fixing it, it also removes the point and maybe runtime binding should be precisely that; runtime treatment only with no equivalent to compile-time constant folding.

In the meantime, more bugs found are:

1. A dynamic call equivalent to `unchecked(int.MinValue / 1)` throws, while the equivalent compile-time expression gives `int.MinValue` (but runtime throws, but the standard allows it to do either. It's not the clearest case.
2. All checked arithmetic on 64-bit integers (signed or unsigned) are treated as unchecked.

There may yet be more to find.

**Comment by JonHanna** [comment]
3. Equivalent to `unchecked(-int.MinValue)` throws. Should fold to `int.MinValue`

**Comment by JonHanna** [comment]
4. Modulo of zero produces zero for `int` or any type promoted to `int` for arithmetic. `uint`, `ulong` and `long` has a `DivideByZeroException` instead of `RuntimeBinderException`

**Comment by JonHanna** [comment]
5. Any negative constant of 32-bits or less throws! (3. above is a subset of this).

I think this one strongly suggests that nothing is actively making use of this feature of runtime binding, if nobody has complained yet. So compat risks are gone, but the argument that the feature just be removed is likewise increased.
