### ISSUE TITLE
Helper scripts

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#1547]
I'd like to propose to add some scripts into the root folder:
- build.cmd - build projects, do not run any tests (we already have it although it runs inner loop tests)
- runtests.cmd - build projects and run inner loop tests (except active issues)
- runalltests.cmd - build projects and run inner and outer loop tests (except active issues)

**Comment by mellinoe** [comment]
Perhaps we could combine the last two? Internally our Runtests script just runs everything under a given folder, which could be everything depending on which folder you supply

**Comment by krwq** [comment]
But then what is the purpose of inner loop if we always run all of them

**Comment by Priya91** [comment]
This could be a solution to the larger issue discussed here #1477. Linking these.

**Comment by stephentoub** [comment]
@krwq / @Priya91, can we close this if it's part of #1477?
