### ISSUE TITLE
EPPlus Exoprt to excel Issue!

### ISSUE THREAD

**Issue by wisam84** [dotnet/corefx#15471]
#I user EPPlus for export data to excel and i got this when run the project

> TypeLoadException: Could not load type 'System.StringExtensions' from assembly 'CoreCompat.System.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c0a7ed9c2333b592'.
OfficeOpenXml.Packaging.ZipPackage.PartExists(Uri partUri)
OfficeOpenXml.ExcelWorkbook.CreateWorkbookXml(XmlNamespaceManager namespaceManager)
OfficeOpenXml.ExcelWorkbook..ctor(ExcelPackage package, XmlNamespaceManager namespaceManager)
OfficeOpenXml.ExcelPackage.get_Workbook()
OfficeOpenXml.ExcelPackage.CreateBlankWb()
OfficeOpenXml.ExcelPackage.ConstructNewFile(string password)
HelpSearch.Controllers.AdminController.Reports(string DepName) in AdminController.cs
+            using (ExcelPackage package = new ExcelPackage(file))

**Comment by karelz** [comment]
Which version of .NET Framework do you use?
Why do you think it is not EPPlus problem?

**Comment by wisam84** [comment]
I am use 4.6
this is my project.json:

> {
  "title": "Help Search Application",
  "description": "wisam J.S. Ali",
  "userSecretsId": "aspnet-HelpSearch-5ef61293-9310-4435-ab62-e09b58d5f5c3",

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },
  "dependencies": {
    "BundlerMinifier.Core": "2.2.306",
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.2",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.Extensions.CommandLineUtils": "1.0.0",
    "Microsoft.AspNetCore.Mvc.ViewFeatures": "1.1.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore.Design": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.Relational": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
    "Microsoft.VisualStudio.Web.CodeGeneration": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "System-Web-Helpers.dll": "1.0.0",
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": "1.0.0-preview2-final",
    "Microsoft.jQuery.Unobtrusive.Ajax": "3.2.3",
    "Microsoft.AspNetCore.Mvc.Core": "1.1.0",
    "Sakura.AspNetCore.Mvc.PagedList": "2.0.11",
    "Sakura.AspNetCore.PagedList": "2.0.1",
    "Sakura.AspNetCore.Mvc.TagHelpers": "1.2.1",
    "SendGrid.NetCore": "1.0.0-rtm-00002",
    "EPPlus.Core": "1.2.0",
    "CoreCompat.System.Drawing": "1.0.0-beta006",
    "System.Reflection": "4.0.10",
    "NETStandard.Library": "1.6.1"
  },
  "frameworks": {
    "net46": {}
  },
  "netcoreapp1.0": {
    "dependencies": {
      "Microsoft.NETCore.App": {
        "version": "1.1.0",
        "type": "platform"
      }
    },
    "imports": [
      "portable-net45+wp80+win8+wpa81+dnxcore50",
      "portable-net451+win8"
    ]
  },
  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },
  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  },
  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.Extensions.SecretManager.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8"
      ]
    }
  }

> }

**Comment by karelz** [comment]
@ericstj any advice/direction?

**Comment by ericstj** [comment]
`CoreCompat.System.Drawing` isn't one of our assemblies.

It looks like the type ref is coming from https://www.nuget.org/packages/EPPlus.Core/
And the expected (missing) type def is comping from https://www.nuget.org/packages/CoreCompat.System.Drawing/

If I crack open the CoreCompat.System.Drawing package I see it has two builds:
lib/net45 & lib/netstandard1.3.

If I diff the contents of the net45 implementation and the netstandard1.3 implementation I see that net45 is missing a lot of the types that are in the netstandard1.3 implementation:
![image](https://cloud.githubusercontent.com/assets/8918108/22312169/a2afac3e-e30b-11e6-9c96-7fbb526d1b7a.png)

Since the net45 implementation is always preferred by NuGet over netstandard this is what causes the issue.  The problem should be reported to the owners of the CoreCompat.System.Drawing package.  If they want the netstandard1.3 implementation to apply on net46 then they should copy that to the net46 folder.  Otherwise if they want the net45 implementation to apply they should make sure to add the missing types.
