### ISSUE TITLE
ValueTuple should type-forward to System.Runtime instead of System.Private.CoreLib

### ISSUE THREAD

**Issue by jcouv** [dotnet/corefx#15475]
From discussion with @terrajobst, it looks like the type forwards I recently introduced for target group = "netcoreapp1.1" (PR https://github.com/dotnet/corefx/pull/14786) are incorrect. They point to `System.Private.CoreLib` instead of `System.Runtime`. 
While this works at runtime, it is incorrect at compile-time, because the compiler does not see `System.Private.CoreLib` and so cannot unify on its implementation.

FYI @weshaggard @tarekgh

**Comment by weshaggard** [comment]
The reference assembly for System.ValueTuple is type-forwarding to System.Runtime as far as I can tell so compile-time with that ref should be fine. As for the implementation you could type-forward that to either System.Runtime or System.Private.CoreLib but given a choice you should forward it to System.Runtime as that gives it more flexibility.

**Comment by jcouv** [comment]
I went back to look at the package. We probably looked at the binary in `lib` instead of `ref`.
The one in `ref` indeed looks correct (type forwards to `System.Runtime`).
Closing the issue.

**Comment by jcouv** [comment]
This was done after all (as part of Eric's cleanup https://github.com/dotnet/corefx/commit/17fdb439c50f4aa66a99f9b5549e9db923331e40#diff-a4bc1bc0e27259ab3f915dc79b8f36a4 )
