### ISSUE TITLE
build for netfx or netstandard targets does not work

### ISSUE THREAD

**Issue by lmolkova** [dotnet/corefx#15482]
I'm trying to build clean master against netfx target with
`build -TargetGroup=netfx`
It fails with many errors in System.ValueTuple and stops after that.

It also happens with netstandard target, but builds successfully for netcoreapp.
Is it supposed to work?

[msbuild.log.zip](https://github.com/dotnet/corefx/files/730931/msbuild.log.zip)

**Comment by weshaggard** [comment]
Yes this is a known gap right now, @tarekgh  is looking into this scenario. I believe we are tracking this work with https://github.com/dotnet/corefx/issues/14911 so closing this issue.
