### ISSUE TITLE
VS .sln files do not use the solution folders any longer. 

### ISSUE THREAD

**Issue by billwert** [dotnet/corefx#15487]
Opening .sln files in VS now have all the projects in a flat list at the root of the solution, not in the solution folders:
![image](https://cloud.githubusercontent.com/assets/4523120/22311892/64a1dec2-e30a-11e6-8980-cf114056e9fb.png)

Rolling back to before [f6ab339 ](https://github.com/dotnet/corefx/commit/f6ab339) puts things to back as I expect them.

cc: @karajas

**Comment by billwert** [comment]
Ah, I just noticed @stephentoub touched on this in #15401. @karajas you can close this if you want or keep it open since it isn't clear to me if there are two issues or not.

**Comment by weshaggard** [comment]
After https://github.com/dotnet/corefx/pull/15738 the solutions use the solution folders.
