### ISSUE TITLE
Add support for uap to ConfigurationManager

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#15515]
When trying to set up the vertical build for uap, I ran into the case where System.Configuration.ConfigurationManager can't build for UAP anymore because it added two dependencies that today aren't supported on UAP: `System.CodeDom` and `System.Net.WebClient`. From an initial look, it seems that the WebClient assembly could potentially be supported on UAP as well, but that is not true for CodeDom. We found out that the dependency to CodeDom is only for the `TempFileCollection` type, and we validated that if that type was moved down to Common then the dependency could be broken.

cc: @weshaggard @JeremyKuhne @ericstj

**Comment by JeremyKuhne** [comment]
I'll move it today.

**Comment by ericstj** [comment]
@weshaggard I wonder if there is a better home for "TempFileCollection" seems a little odd for that type to live in CodeDom.  Has CodeDom had an API review?

**Comment by JeremyKuhne** [comment]
Yeah, it is a bit unfortunate placement. https://msdn.microsoft.com/en-us/library/system.codedom.compiler.tempfilecollection.aspx

**Comment by ericstj** [comment]
Yeah, namespace wise for sure, but we could put it in a different assembly.  We've done so for other stuff.  https://github.com/dotnet/corefx/blob/d99742ff04672f1838c6e6f3ceadd201461ec573/src/System.Runtime/ref/System.Runtime.cs#L3513

Would like @weshaggard to weigh in since it'd have NETStandard implications.

**Comment by weshaggard** [comment]
We haven't had an API review for CodeDom. I don't know much about TempFileCollection but if it isn't related to CodeDom (outside of namespace) then we could move it into one of the file system libraries.

**Comment by ericstj** [comment]
If we move it to FileSystem are we making any commitment to it being in a future version of NETStandard?

**Comment by weshaggard** [comment]
Not necessarily, but we should probably consider adding it.

**Comment by joperezr** [comment]
seems like this one is done so I'm closing it.
