### ISSUE TITLE
EmptyIfNull Extension Method: For Avoiding Annoying  NullReferenceException

### ISSUE THREAD

**Issue by joycsc** [dotnet/corefx#1553]
*System.NullReferenceException: Object reference not set to an instance of an object.*

One of the most common exceptions that has been thrown from .net based applications, possibly trillion times since .NET Framework being used for first time.  

You can get an idea [here] (http://stackoverflow.com/questions/4660142/what-is-a-nullreferenceexception-and-how-do-i-fix-it) about the experiences in developer community on this issue (specially when it is explicitly not expected):

For instance the following lines of code will cause a NullReferenceException.

``` C#
object obj = null;
Console.WriteLine(obj.ToString()); 
```

The above code caused the NullReferenceException, because the object ‘obj’ is null, and it’s reference is being used to call it’s instance method.

While in the above example the cause of NullReferenceException is easy catch, most of the cases the respective developer doesn’t have any idea how or when the victim object became null. 

One of the recommended resolutions to solve this problem is to perform a null value check, before using the object and consider one of the following approach:

(1) A custom exception can be thrown with more details of the error, so that the user or the developer can take appropriate action to correct the error.

``` C#
object obj = null;
if (obj == null)
 throw new InvalidOperationException("Required object is null.");
```
(2) Or simply use the object when it is not null.

``` C#
object obj = null;
if (obj != null)
  Console.WriteLine(obj.ToString());
```
For the 2nd case as mentioned above, the intension of the usage of object is clear, that is it’s optional and it’s OK to proceed to the next part of code, even it doesn’t contain any instance. The null check of optional object can produce cluttered code when the object contains a bit complex graph, like as below:

``` C#
            Person p = new Person
            {
                Name = "Ashraf Alam",
                Address = new Address {AddressLine = "Ony Microsoft Way", City = "Seattle", Country = "USA"}
            };

            if (p != null && p.Name != null && p.Address != null && p.Address.AddressLine != null &&
                p.Address.City != null && p.Address.Country != null)
                Console.WriteLine("Full address of {0} is {1} {2} {3}", p.Name.ToLower(),
                    p.Address.AddressLine.ToLower(), p.Address.City.ToLower(), p.Address.Country.ToLower());
```

## Proposed Extension Methods
For the scenarios, when it’s acceptable that relevant object can have no instance, one (or more) extension method that creates an instance automatically when it is null, enables safe usage of its instance members without explicit check for null reference.

Here 2 extension methods are provided, the first one is for objects with default constructor and second one for string. 

**The final implementation should support constructors with different set of parameters, along with possible support for preferred dependency injection containers.**

``` C#
    public static class ExtensionMethods
    {
        public static T EmptyIfNull<T>(this T obj) where T : new()
        {
            if (obj == null) return new T();

            return obj;
        }

        public static string EmptyIfNull(this string str)
        {
            if (str == null) return string.Empty;

            return str;
        }
    }
```

#### Sample Use of the Proposed Extension Methods

Instead of the explicit null check as provided below:

``` C#
object obj = null;
if (obj != null)
  Console.WriteLine(obj.ToString());
```
We can use a possible null object safely, with the extension method EmptyIfNull
``` C#
            object obj = null;
            Console.WriteLine(obj.EmptyIfNull().ToString());
```

If approved, I want to implement these extension methods.

**Comment by svick** [comment]
I have several misgivings about this:

1. Does this actually improve a common issue? For the address case, I would probably expect that you want to write all you know, instead of e.g. not writing anything if you don't know the country
2. You can already use `??` for this. E.g. instead of `obj.EmptyIfNull().ToString()` you can write `(obj ?? new object()).ToString()`, which is not much longer, but is much clearer.
3. The notion of "empty object" can be tricky, especially if you want to support calling different constructors. Maybe another name would be better, but then again, `??` is hard to beat.

**Comment by HaloFour** [comment]
The idea of creating a temporary instance just to avoid an NRE sounds pretty horrid.  You're probably much better served through the new null-propagation operators due in C# 6.0 and VB.NET 2015:

```cs
object obj = null;
Console.WriteLine(obj?.ToString());
```
