### ISSUE TITLE
System.Linq.Expressions.Tests.CompilerTests.CompileDeepTree_NoStackOverflowFast causing BCL assert in System.Threading.Thread

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/corefx#15533]
Specifically, corelib is unhappy with [this](https://github.com/dotnet/corefx/blob/88d8bbf7dbf5869b7f239737779e75295e43ef95/src/System.Linq.Expressions/tests/CompilerTests.cs#L45) line.  Per [this](https://github.com/dotnet/coreclr/blob/a928a37a1503871b5da5c80f74fe54b9f937ddc3/src/mscorlib/src/System/Threading/Thread.cs#L431) line, CoreCLR only supports the default stack size.

Whether this should be asserted or handled via exception is a dotnet/coreclr#9158.

**Comment by JonHanna** [comment]
Also, that test certainly seemed to be doing what it should when it was put in, in that it triggered the stack-overflow handling faster than the outerloop equivalent that uses the default stack. Is that assertion bogus?
