### ISSUE TITLE
System.Diagnostics.DebuggerStepThroughAttribute should be available on properties

### ISSUE THREAD

**Issue by SetTrend** [dotnet/corefx#15542]
During my debugging sessions I don't want to accidentally step into some casting-only properties I have created.

This is particularly true for getter-only properties which simply encapsulate some object mapper's GetService() calls.

Can we have the `System.Diagnostics.DebuggerStepThroughAttribute` (and similar attributes in vicinity) work on properties, please?

**Comment by krwq** [comment]
Hi @SetTrend 

I just tested this and this scenario works correctly.

Are you sure you are applying the attribute correctly? (custom attributes for properties might be slightly confusing - you might want to add a suggestion for simplified syntax on dotnet/roslyn)

Here is what I'm doing (tested with VS 2017 RC)
```csharp
using System;
using System.Diagnostics;

class Program
{
    static string _test;
    static string Test
    {
        [DebuggerStepThrough]
        get
        {
            Console.WriteLine("get");
            return _test;
        }
        [DebuggerStepThrough]
        set
        {
            Console.WriteLine("set");
            _test = value;
        }
    }
    static void Main(string[] args)
    {
        Test = "sdf";
        Console.WriteLine(Test);//DebuggerStepThrough
    }
}
```

also you might want to check the setting: Options->Debugging->Step over properties and operators (Managed only)

**Comment by SetTrend** [comment]
Interesting ... I'm back at the office on Tuesday. Please let me check. I'll get back immediately then.

**Comment by SetTrend** [comment]
OK, the problem actually exists with getter-only properties using a Lambda expression, like this one:

`T GetService<T> => ...`

You cannot apply the `[DebuggerStepThrough]` attribute to these kind of properties, which becomes annoying due to the sheer simplicity of this kind of properties.

**Comment by svick** [comment]
Maybe it would make sense to support applying `[DebuggerStepThrough]` directly to properties (and events?)? The debugger would then step through all accessors of that property.

**Comment by joperezr** [comment]
I don't really see a lot of value on making this attribute work on properties just because of the lambda getter case. I will close this issue for now, but please feel free to reopen if you come up with more examples where this would be useful.
