### ISSUE TITLE
Remove test attributes only necessary for running on older CoreFX versions

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#15555]
Remove these
`[SkipOnTargetFramework(TargetFrameworkMonikers.Netcoreapp1_0]`
`[SkipOnTargetFramework(TargetFrameworkMonikers.Netcoreapp1_1]`

We do not have plans to run the CoreFX tests against older versions of .NET Core so these are unnecessary and we should remove them all.

We still need the versionless one `[SkipOnTargetFramework(TargetFrameworkMonikers.Netcoreapp)]` where a test only passes on Desktop

**Comment by JonHanna** [comment]
`System.Tests.StringTests.Join_ObjectArray_WithNullIssue` fails in CI if `[SkipOnTargetFramework(TargetFrameworkMonikers.Netcoreapp1_1]` is removed.

**Comment by weshaggard** [comment]
@JonHanna some of the tests like those might need to be changed to use the version-less one as in it should have been `[SkipOnTargetFramework(TargetFrameworkMonikers.Netcoreapp)] `.

**Comment by JonHanna** [comment]
Ah that makes sense. It's the only one set for skipping that target, so maybe it got missed in a previous sweep for that.

**Comment by danmosemsft** [comment]
Do you want to replace that last one  `[SkipOnTargetFramework(TargetFrameworkMonikers.Netcoreapp1_1)]` so we can close this?

**Comment by JonHanna** [comment]
Yep. Chores got in the way of doing it sooner.

**Comment by danmosemsft** [comment]
Thanks @JonHanna !
