### ISSUE TITLE
HostingEnvironment.MapPath Behaves differently in VS 2017 (different MSBuild) than in VS 2015

### ISSUE THREAD

**Issue by skyhoshi** [dotnet/corefx#15550]
Both sessions in DEBUG of a ASP.NET API Project running .NET Framework 4.6.1. 

Method in Question: HostingEnvironment.MapPath("~");
We were running the method inside the WebApiConfig.cs class (Class name is the same without the .cs) under the method "Public static void Register(HttpConfiguration config)" Method.

Expected Output (as in VS 2015): 
"Root:\path\to\folder\" (without quotes)

Result in VS 2017: 
"Root:\Path\To\Folder" (without Quotes)

Build is treating this differently for some reason. and by upgrading to the RC, this breaks our code.

**Comment by karelz** [comment]
`HostingEnvironment` is ASP.NET class - if it is about ASP.NET Core, please look at ASP.NET Core repo.
