### ISSUE TITLE
API Proposal: Adding public ArrayBuilder<T>

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#15573]
## Background

It's very common to use a `List<T>` as a local variable, `Add` to it a couple of times, and throw away the list after the method is finished. Doing so incurs heap allocations, not only for the backing vector for the list, but also for the `List<T>` itself since it is a class. It would be great to have a struct alternative to `List<T>` to reduce unnecessary allocations.

## Proposal

We should add the `ArrayBuilder<T>` struct:

```c#
public struct ArrayBuilder<T> : IList<T>, IReadOnlyList<T>
{
    public ArrayBuilder();
    public ArrayBuilder(IEnumerable<T> items);

    public int Capacity { get; }
    public int Count { get; }
    public ref T this[int index] { get; }

    public void Add(T item);
    public void AddRange(IEnumerable<T> items);
    public void Clear();
    public void Contains(T item);
    public void CopyTo(T[] array);
    public void CopyTo(T[] array, int arrayIndex);
    public void CopyTo(int index, T[] array, int arrayIndex, int count);
    public Enumerator GetEnumerator();
    public int IndexOf(T item);
    public void Insert(int index, T item);
    public bool Remove(T item);
    public void RemoveAt(int index);
    public T[] ToArray(); // Resets the ArrayBuilder after it's called.
    public ArraySegment<T> ToArraySegment(); // Does not copy, resets the ArrayBuilder after it's called.
    public void UncheckedAdd(T item); // Assumes there is enough room in the backing array.

    bool ICollection<T>.IsReadOnly { get; }

    IEnumerator<T> IEnumerable<T>.GetEnumerator();
    IEnumerator IEnumerable.GetEnumerator();

    public struct Enumerator : IEnumerator<T>
    {
        public T Current { get; }
        public void Dispose();
        public bool MoveNext();

        void IEnumerator.Reset();
    }
}
```

## Notes

- Because C# does not support parameterless struct constructors, we won't be able to set the underlying array to an empty one when the `ArrayBuilder` is first created, so we'll have to incur [an extra null check](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Collections/Generic/ArrayBuilder.cs#L38) on every `Add` where List does not.
  - The alternatives would be to have a factory method `ArrayBuilder.Create<T>()`, or forcing the user to pass in a dummy parameter to the constructor, so we could do initialization work. However, it seems better to incur the check than to sacrifice the user experience. And if parameterless struct constructors are enabled in the future then we can remove it without breaking anything.

- The builder will use the exact same buffer sizes as `List<T>` (0, 4, 8, ...) to make it a no-brainer to switch from List to ArrayBuilder in local variables.

- `UncheckedAdd` will be similar to `Add`, but won't check if there's more room in the array. If there isn't, it will generate an `IndexOutOfRangeException`. See [implementation](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Collections/Generic/ArrayBuilder.cs#L118)

- `ToArray` will reset the ArrayBuilder after it's called. The reason is we can employ an optimization where if the count of the builder is equal to its' capacity, we just hand back the underlying array and don't do any copying. However, this could cause issues if the same array is handed back twice, and modified by both callers. To prevent these errors we will reset the ArrayBuilder back to its initial state after one call.
  - In the [current implementation](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Collections/Generic/ArrayBuilder.cs#L102) we take a different approach and invalidate the builder instead of resetting it after `ToArray` is called. However, I'm deciding not to go with that approach because then we will have another state we have to account for in every method.

- This is primarily meant to be used for scenarios when the size of the array is small. Sometime later (after some discussion has ensued here but before the API is approved), I will publish a separate proposal on [`LargeArrayBuilder<T>`](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Collections/Generic/LargeArrayBuilder.cs) which uses a separate buffering strategy that reduces allocations by 1/3.

**Comment by jnm2** [comment]
I was just going to ask about what you pointed out in the LargeArrayBuilder. How large does the final array have to be before it's more efficient internally for a `StringBuilder`-like approach to be taken? If we build small strings that way, why not small arrays?

**Comment by jamesqo** [comment]
@jnm2 

> How large does the final array have to be before it's more efficient internally for a StringBuilder-like approach to be taken?

There isn't a strict limit, but in the [current implementation](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Collections/Generic/LargeArrayBuilder.cs#L58) of `LargeArrayBuilder` we switch to buffer-chunking after 8 elements, which is typically around 64 bytes since T is usually a reference type.

> If we build small strings that way, why not small arrays?

`StringBuilder` stores strings contiguously up to 16 characters: https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Text/StringBuilder.cs#L90 Only upwards of 16 does it store characters non-contiguously. For small arrays, the cost of storing the previous array is going to outweigh the gain of not having to copy it.

**Comment by karelz** [comment]
How is it different from `ArrayList`?

**Comment by jamesqo** [comment]
@karelz `ArrayList` is non-generic.

**Comment by stephentoub** [comment]
Primarily it's a generic struct.

**Comment by omariom** [comment]
Is it a builder or a collection?

**Comment by jamesqo** [comment]
@omariom It is both-- it can be enumerated in its own right and used to build arrays. Aside from it being a struct, its' semantics are very similar to that of existing mutable collection types.

**Comment by omariom** [comment]
I think people will start using it as a less allocaty `List<T>`.

**Comment by jkotas** [comment]
I think adding this type as .NET Core framework type is problematic:

- Struct builders have usability issues for broad consumption because of it is NoCopy struct, but there is no way to express NoCopy structs in C#.
- Once you add the error handling to make it "good" framework type, half of the performance benefit will be gone. Folks who need the lean and mean implementation would not want to use it anyway.
- There are a lot of rarely used methods that make the type more expensive than necessary. For example, I would not want the enumerator to be there for my uses.

I think that the best thing to do with these is to distribute them as source nuget packages and let folks who need them include the right subset of sources for the given case as internal implementation detail, with any tweaks they wish. Not that different pattern from src\Common corefx directory.

**Comment by jamesqo** [comment]
@jkotas I haven't gotten around to responding to you for some time. However, I do agree with most of your points. It does seem like it wouldn't be that hard for someone to make his/her own dynamic array struct that has way less bloat from not implementing IList. Additionally the value this type adds (no pun intended) is small because there is only 1 allocation avoided at the beginning, and that's it (in constrast to changing the way the items themselves are stored, which would make the memory savings much larger).

I think I'll close this proposal in favor of a new one based on [`LargeArrayBuilder<T>`](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Collections/Generic/LargeArrayBuilder.cs#L55).
