### ISSUE TITLE
LINQ's Buffer ctor requires Count/CopyTo results be consistent

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1561]
LINQ's internal Buffer, which is used in operations like ToArray, OrderBy, Reverse, etc., assumes that if the input ```IEnumerable<T>``` implements ```ICollection<T>```, then CopyTo will be guaranteed to copy the number of items returned previously by Count:

https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Enumerable.cs#L3087-L3093
```C#
int count = 0;
ICollection<TElement> collection = source as ICollection<TElement>;
if (collection != null)
{
    count = collection.Count;
    if (count > 0)
    {
        items = new TElement[count];
        collection.CopyTo(items, 0);
    }
}
else
{
    foreach (TElement item in source)
    {
        if (items == null)
        {
            items = new TElement[4];
        }
        else if (items.Length == count)
        {
            TElement[] newItems = ArrayT<TElement>.Resize(items, checked(count * 2), count);
            items = newItems;
        }
        items[count] = item;
        count++;
    }
}
```

This is problematic for any collection that fails this guarantee, e.g. by design the concurrent collections (```ConcurrentQueue<T>```, ```ConcurrentDictionary<TKey, TValue>```, etc.) may have their number of elements change between the call to Count and CopyTo if elements were added or removed concurrently.

We could address this in the implementation of Buffer by avoiding the use of CopyTo, e.g.
```C#
int count = 4;
ICollection<TElement> collection = source as ICollection<TElement>;
if (collection != null)
{
    int tmpCount = collection.Count;
    if (tmpCount > 0)
        count = tmpCount;
}
foreach (TElement item in source)
{
    if (items == null)
    {
        items = new TElement[count];
    }
    else if (items.Length == count)
    {
        TElement[] newItems = ArrayT<TElement>.Resize(items, checked(count * 2), count);
        items = newItems;
    }
    items[count] = item;
    count++;
}
```

This turns Count into an estimate rather than a guarantee, avoiding the problem.  However, it has the downside of having a (potentially) less efficient copy mechanism for other ```ICollection<T>``` implementations, including an ```IEnumerator<T>``` allocation used in the foreach.  That said, it's not clear to me how often we hit the "fast" CopyTo path anyway; many collection types have their own ToArray method, so if the LINQ method is being used, it's likely because there are other LINQ operators in the middle, e.g. ```collection.Where(...).Select(...).ToArray()```, in which case the optimization will not apply.

A few possible options:
1. We say that concurrent collections may not be used concurrently with LINQ operations.  Developers may of course already be doing this, and since you can pass concurrent collections around as ```IEnumerable<T>```, the developer may not even know they're using concurrent collections but may silently either get corrupted data (e.g. the count drops after allocating the array, leaving default elements at the end of the array) or exceptions (e.g. CopyTo tries to copy more elements than the array can hold).
2. We make the above change, such that we no longer require the Count == CopyTo size guarantee, potentially special casing some known types like ```List<T>```, ```Collection<T>```, etc. and some known other situations, e.g. IsReadOnly returning true.
3. We special-case the known-problematic cases in the framework, namely the Concurrent* collections, and do the second option above just for those.  We could add a marker interface or something to more easily identify them, which would also allow other collections to opt-out of such things as well.
4. "something really cool that I don't even know about"

Thoughts?

**Comment by stephentoub** [comment]
cc: @VSadov

**Comment by VSadov** [comment]
So far the 3rd option with a marker interface seems the most appropriate, mostly because it does not penalize the majority which is regular (not concurrent) collections.

**Comment by svick** [comment]
> 2\. We make the above change, such that we no longer require the Count == CopyTo size guarantee, potentially special casing […] some known other situations, e.g. IsReadOnly returning true.

I don't think that would be safe. If you wrap `ConcurrentDictionary<K, V>` in a `ReadOnlyDictionary<K, V>`, then the result is an `ICollection<KeyValuePair<K, V>>`, whose `IsReadOnly` returns `true`, but [is not safe with the current implementation of `ToList()`](https://gist.github.com/svick/8c2696222800aa031450).

This makes option 3 also not 100 % safe, unless `ReadOnlyDictionary` was also marked as one of the problematic cases.

**Comment by stephentoub** [comment]
> I don't think that would be safe.

You're referring just to the IsReadOnly part, right?  Not to the rest of 2?

**Comment by svick** [comment]
@stephentoub Yeah, that's what I meant.

**Comment by stephentoub** [comment]
Ok, yeah, makes sense.  I added the IsReadOnly as an additional potential option, but I guess it depends on how far down the rabbit hole we want to protect against.

**Comment by stas-sultanov** [comment]
option 4
How about to add `T[] ToArray()` method to `ICollection<T>` so concurrent collections will implement it and guaranty that collection will not be changed before the method completes.

**Comment by svick** [comment]
@stas-sultanov You can't add a method to an interface without breaking compatibility. I.e. every type that currently implements `ICollection<T>` would break. (At least unless [Virtual extension methods](https://github.com/dotnet/roslyn/issues/258) are added.)

**Comment by stephentoub** [comment]
It also would only help ToArray and not the other methods that use this, like OrderBy.

**Comment by ikopylov** [comment]
> How about to add T[] ToArray() method to ICollection\<T\> so concurrent collections will implement it and guaranty that collection will not be changed before the method completes.

As I can see, this is the best option. But since it would break compatibility, an additional interface with this method should solve the problem.

> It also would only help ToArray and not the other methods that use this, like OrderBy.

It would speed-up ```Buffer<T>``` construction. And ```OrderBy``` rely on the ```Buffer<T>```, so it will help in this case too.

Furthermore, if ```WhereArrayIterator```, ```WhereListIterator``` and some other internal iterators implement that new interface with ```ToArray``` method, then we'll get boost in many other scenarios. 
Especially in that one: ```array.Where().Select().ToArray()```.  

If the newly added interface is not implemented on the source collection, then the ```ICollection<T>.Count``` can be used as the initial size for the array inside ```Buffer<T>```.

> LINQ's internal Buffer, which is used in operations like ToArray, OrderBy, Reverse, etc., assumes that if the input IEnumerable<T> implements ICollection<T>, then CopyTo will be guaranteed to copy the number of items returned previously by Count

The same assumption is also used in the constructor of ```List<T>``` which called from LINQ ```ToList```. So the fix should affect that implementation too.

**Comment by MarcinJuraszek** [comment]
Any decisions on this one? I'm happy to code the fix if we agree on which one it should be.

I personally like this one best:

> .3. We special-case the known-problematic cases in the framework, namely the Concurrent* collections, and do the second option above just for those. We could add a marker interface or something to more easily identify them, which would also allow other collections to opt-out of such things as well.

**Comment by hackcraft** [comment]
> 1. We say that concurrent collections may not be used concurrently with LINQ operations.

I always assumed that if I was to try to use Linq with an unbuffered concurrent collection, that it could go badly.

**Comment by stas-sultanov** [comment]
Well i've been thinking about this issue recently and found that
Concurrent Collections should not work with lique at all.
It appears that concurrent collections should not implement IEnumerable.

**Comment by VSadov** [comment]
I think the only reasonable solution is "1" - "do not use LINQ over concurrently mutating data".

Note this is not an outright ban on using LINQ with concurrent collections. It is just that collections must be in a quiescent state when LINQ is used.

Scenario when LINQ is applied to a collection that is being actively mutated is bound to result in a racey and inconsistent behavior.
