### ISSUE TITLE
build-managed -release fails when trying to nuget pack Microsoft.Private.CoreFx.NETCoreApp

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#15612]
The full log can be found here: https://gist.github.com/jamesqo/2151360517bd4e16981a8d90153bbc48 I've never run into this issue with a debug build yet.

**Comment by karelz** [comment]
cc @weshaggard @mellinoe

**Comment by weshaggard** [comment]
@jamesqo this isn't unique to release it happens when you call build-managed by itself. See https://github.com/dotnet/corefx/issues/14940. We need to clean that up a little but to fix it I would suggest calling build.cmd -release to ensure the native bits are also built.

**Comment by jamesqo** [comment]
@weshaggard Thanks for the advice. I see that `build -release` is calling msbuild with `/p:ConfigurationGroup=Debug` though.

```
C:\Users\james\Code\git\corefx>build -release
Tools are already initialized.
Running: C:\Users\james\Code\git\corefx\src\Native\build-native.cmd   x64  Release  Windows_NT  --numproc 4    toolSetDir=c:\tools\clr
Tools are already initialized.
Running: C:\Users\james\Code\git\corefx\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false /l:BinClashLogger,Tools\net45\Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log
/p:ConfigurationGroup=Debug /p:GenerateNativeVersionInfo=true  /flp:v=normal  /flp2:warningsonly;logfile=msbuild.wrn  /flp3:errorsonly;logfile=msbuild.err  C:\Users\james\Code\git\corefx\src\Native\..\../build.proj /t:GenerateVersionHeader
^^^ Here
Command execution succeeded.
Commencing build of native components
```

Same for `build-native`. It seems like only `build-managed` is paying attention to the -release switch?

**Comment by weshaggard** [comment]
@jamesqo That command is just to generate our version headers which doesn't really matter if it is Debug or Release. It might be a good idea to pass along the data here https://github.com/dotnet/corefx/blob/master/src/Native/build-native.cmd#L19 but it isn't really necessary. 

Let me know if you cannot successfully build with build -release but all our official builds and CI builds do build correctly with that option.
