### ISSUE TITLE
bypass SSL validation on Unbuntu

### ISSUE THREAD

**Issue by VenkateshSrini** [dotnet/corefx#15623]
Our client has an on premise hosting of Cloud foundry that runs using a self signed certificate. We are developing MicroServices for him in ASP.NET Core. During this we need to make HTTP calls for which we are using HttpClient. 

•Is there way I can bypass the SSL validation check in SSL client for Ubuntu( I know it can be done for windows)?

**Comment by stephentoub** [comment]
You can set your HttpClientHandler's ServerCertificateCustomValidationCallback delegate to provide whatever validation you want, including just returning true for every certificate.  We do this in a bunch of our own tests, e.g. https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ServerCertificates.cs#L54.

**Comment by VenkateshSrini** [comment]
Does this work on Ubuntu also. Please clarify ? Which version of System.NET.HTTP should I use?

**Comment by stephentoub** [comment]
> Does this work on Ubuntu also

Yes, as long as the libcurl you're using is OpenSSL-based.

> Which version of System.NET.HTTP should I use?

All of the released .NET Core versions have this support.

**Comment by VenkateshSrini** [comment]
Hi Stephen,
As you can see that I will be hosting this in CloudFoundry. So please help me by letting know if I have to package any version of libcurl library also a dependency during code publishing?

**Comment by VenkateshSrini** [comment]
Thanks it is working
