### ISSUE TITLE
XDocument Save() with Filename

### ISSUE THREAD

**Issue by akcorp2003** [dotnet/corefx#15630]
Are there plans to add the filename to XDocument Save() method? 

In the .NET Framework API, you can pass in a string as an argument and you can save it that way. However, in the .NET Core implementation, you can't do that.

**Comment by danmosemsft** [comment]
It's added: https://github.com/dotnet/corefx/blob/master/src/System.Xml.XDocument/ref/System.Xml.XDocument.cs#L193
However it's not shipped -- this will be in the upcoming 2.0 release.
