### ISSUE TITLE
File.GetLastWriteTime inconsistencies.

### ISSUE THREAD

**Issue by quoctruong** [dotnet/corefx#15633]
On Windows, File.GetLastWriteTime does not throw an error if the file does not exist. On Linux, however, this function throws an error.

**Comment by danmosemsft** [comment]
That seems like it should be fixed.

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/issues/1728

**Comment by ianhays** [comment]
I took this issue to a design review forever ago and sentiment was strong that the Linux versions should throw. So, it is definitely a purposeful difference in behavior. 

This is a dupe of #1728, so we should reopen and continue discussion there if we want to change the behavior to match Windows.

**Comment by ianhays** [comment]
FWIW, my vote is/was consistency between platforms. Since the overall sentiment on compat has changed since #1728, it's possible we may want to make them the same now.
