### ISSUE TITLE
./build.sh -? is not helpful

### ISSUE THREAD

**Issue by marek-safar** [dotnet/corefx#15656]
./build.sh -?
```
There are new changes on how we build. Use this script only for generic
build instructions that apply for both build native and build managed.
Otherwise:

Before                Now
build.sh native      build-native.sh
build.sh managed     build-managed.sh

For more information: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md
----------------------------------------------------------------------------


Tools are already initialized
Error: Object reference not set to an instance of an object.    at Microsoft.DotNet.Execute.Setup.FormatSetting(String option, String value, String type, String toolName)
   at Microsoft.DotNet.Execute.Setup.BuildParametersForCommand(Dictionary`2 commandParameters, String toolName)
   at Microsoft.DotNet.Execute.Setup.BuildCommand(String commandSelectedByUser, List`1 parametersSelectedByUser, Dictionary`2 parameters)
   at Microsoft.DotNet.Execute.Setup.GetHelpCommand(String commandName, String alias)
   at Microsoft.Fx.CommandLine.CommandLineParser.GetHelp(Int32 maxLineWidth, String parameterSetName, Boolean displayGlobalQualifiers)
   at Microsoft.Fx.CommandLine.CommandLineParser.<>c.<ParseForConsoleApplication>b__0_0(CommandLineParser parser)
   at Microsoft.Fx.CommandLine.CommandLineParser.Parse(Action`1 parseBody, Action`1 helpHandler, Action`2 errorHandler, Setup setupContent, String[] args)
   at Microsoft.Fx.CommandLine.CommandLineParser.ParseForConsoleApplication(Action`1 parseBody, String[] args, Setup setupContent)
   at Microsoft.DotNet.Execute.Executor.DefineParameters(String[] args, Setup setupInformation)
```

**Comment by willdean** [comment]
This is a dup of #15609 - it's already fixed.

**Comment by karelz** [comment]
We just need to propagate the buildtools into CoreFX. @danmosemsft @weshaggard @mellinoe are you tracking the update?

**Comment by weshaggard** [comment]
>@danmosemsft @weshaggard @mellinoe are you tracking the update?

No. BuildTools updates are done on demand by the person that wants to get a fix they made in BuildTools into corefx.

**Comment by karelz** [comment]
Should we kick off one now that we have fix to '-?', or do you want to wait for more value before we update?

**Comment by weshaggard** [comment]
I have not concerns with someone submitting an update.

**Comment by karelz** [comment]
The key question is: Is the value (of not NullRef and potentially show more content) significant enough to warrant doing it just for this issue?

**Comment by weshaggard** [comment]
I'd say it probably is enough value. I don't know when we last updated BuildTools but I like keeping corefx updated as much as possible.

**Comment by willdean** [comment]
I'm a nobody, with no valid opinion on this, but I'll express it anyway:   The same bug's been filed twice in the last 24-ish hours, and new users of the build system fall over it straight away, because they're told to run `build -?` ("Our dev workflow has changed! Use -? for help in the new options we have and how to pass parameters now.") and that promptly crashes.

If nothing else, it's a dismal first impression, though I'm sure the effect of the bug is absolutely zero to people who are already working on the project.

**Comment by danmosemsft** [comment]
@safern could you please create a PR today to update build tools?

**Comment by safern** [comment]
@danmosemsft yes will do so!

**Comment by danmosemsft** [comment]
@willdean you're not a nobody :) and you're quite right.

**Comment by mellinoe** [comment]
@weshaggard Are we ready to pull in a new buildtools, given all of the overrides we are doing here? I'm not sure how many conflicting changes have been made over in the buildtools repo.

**Comment by danmosemsft** [comment]
In the last week, though? We updated a week ago
https://github.com/dotnet/corefx/commits/master/BuildToolsVersion.txt

**Comment by mellinoe** [comment]
In that case, never mind! 😄 I thought we had been holding off on updates since the dev/eng stuff went into master. It should be fine as long as nobody's making conflicting changes in buildtools.

**Comment by safern** [comment]
Fixed, we just updated the buildtools version on #15662

**Comment by karelz** [comment]
Great, thanks!
