### ISSUE TITLE
System.String should be consistent with taking StringComparison arguments

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#1565]
Every method on `System.String` that compares strings should take a `StringComparison` argument. An example where that's not the case is, `String.Contains`. We should to a holistic pass to make sure we don't miss others.

**Comment by ellismg** [comment]
We should also ensure that the `CompareInfo` class exposes relevant methods, for folks that want to use a non-invariant, linguistic comparison.

**Comment by terrajobst** [comment]
Moving to future as it doesn't make the RTM bar.

**Comment by karelz** [comment]
We need formal API proposal

**Comment by gsfreema** [comment]
Is it possible to start small with a task such as this?  I was doing a code review at work and saw someone calling `s1.ToLower().Contains(s2)` and was surprised that there wasn't a version that takes the `StringComparison` enum.

The implementation for such a function could be as simple as
`return s1.IndexOf(s2, StringComparison.OrdinalIgnoreCase) != -1;`.

Would this form of String.Contains be something worthy of going into the framework, or would it be expected that people write their own extension methods for these specific cases?  If you need an API proposal, would you need it for something as broad as "all string comparison functions need to accept StringComparison" or could it be something like "String.Contains needs to an overload accepting StringComparison?"

**Comment by gsfreema** [comment]
Actually, I just say that this was added to `String.Searching.cs`.  Perhaps that work needs to be linked to this issue so it can eventually be closed.

**Comment by karelz** [comment]
See [formal API review](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md) - we need someone to do a sweep and find out what else is missing, then propose API.

**Comment by danmosemsft** [comment]
As noted above, the work here is to create an API proposal. We could get the new API into .NET Standard 2.1 if it is defined and approved.

**Comment by danmosemsft** [comment]
@terrajobst do you want to create the proposal since this is something you'd like to get into NS21?

**Comment by terrajobst** [comment]
Looks like we're now consistent:

```C#
Contains(Char);
Contains(Char, StringComparison);
Contains(String);
Contains(String, StringComparison);
```

I looked at the other methods and with respect to `StringComparison` nothing sticks out. And with respect to .NET Standard, the overloads taking `StringComparison` got added in https://github.com/dotnet/standard/pull/823.
