### ISSUE TITLE
netstandard tests aren't currently running

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#15667]
Any test projects that have both a netcoreapp and netstandard build configuration is only ever running the tests for netcoreapp. So any tests that are conditioned for netstandard only are not currently being ran. System.Runtime (https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System.Runtime.Tests.csproj) is an example of such a project. 

We need to decide whether or not we should run all compatible configurations for a given vertical or only run the most specific configuration for the vertical and make sure it correctly aggregates all the tests.

One drawback to doing only the one configuration is we want have any tests built against netstandard and running in the context of that vertical.

cc @ericstj @joperezr @tarekgh @mellinoe

**Comment by wtgodbe** [comment]
Closing as dup of https://github.com/dotnet/corefx/issues/30729
