### ISSUE TITLE
Adding a newline to an XML document using XDocument

### ISSUE THREAD

**Issue by akcorp2003** [dotnet/corefx#15660]
I was wondering if someone can add the functionality to add an empty line to an XML file (or if the functionality already exists and I couldn't find it on the internet...). 

I tried doing `xelement.element("elementname").Add(Environment.newline)` but it just screws up the formatting of the document.

If I do that, this is what the XML file looks like (truncated for clarity): 

```
<!-- Retrieve profiles from di1 sandbox --><target name="retrieve_di1_profiles"><sf:retrieve username="${di1.username}" password="${di1.password}" serverurl="${di1.serverurl}" maxPoll="${sf.maxPoll}" retrieveTarget="retrieveProfiles" unpackaged="retrieveProfiles/package.xml" /></target>
<!-- Deploy profiles to di1 --><target name="deploy_di1_profiles"><antcall target="retrieve_di1" /><sf:deploy username="${di1.username}" password="${di1.password}" serverurl="${di1.serverurl}" maxPoll="${sf.maxPoll}" deployRoot="deployProfiles" rollbackOnError="true" checkOnly="false" /></target>
<!-- Undeploy from di1 --><target name="undeploy_di1"><antcall target="retrieve_di1" /><sf:deploy username="${di1.username}" password="${di1.password}" serverurl="${di1.serverurl}" maxPoll="${sf.maxPoll}" deployRoot="removecodepkg" /></target>
<!-- Test deploy to di1 --><target name="deploy_di1"><antcall target="retrieve_di1" /><sf:deploy username="${di1.username}" password="${di1.password}" serverurl="${di1.serverurl}" maxPoll="${sf.maxPoll}" deployRoot="deployProfiles" rollbackOnError="true" checkOnly="false" /></target>
```

**Comment by sepidehMS** [comment]
@akcorp2003 If you can use `XmlDocument` instaed, you will be able to add new lines in elements without messing the format of the document using `CreateWhitespace` like [this](https://msdn.microsoft.com/en-us/library/system.xml.xmldocument.createwhitespace(v=vs.110).aspx).

If that doesn't solve your problem, please give more details on where you need the new line to be inserted and how you are using `XDocument` to do that. Thanks.

**Comment by akcorp2003** [comment]
@sepidehMS I believe that is what I want. However, how do I do that with the apis in XDocument?

To put it concretely, I hope that I can create an XML file using just XDocument resulting in:

    <project name="Salesforce Ant tasks" default="deploy_my" basedir="." xmlns:sf="antlib:com.salesforce">
    
        
    <taskdef uri="antlib:com.salesforce" classpath="lib/ant-salesforce.jar" />
  
      <property file="../build.properties" />
      <property file="../metadata.properties" />
      <property environment="env" />
      <tstamp>
          <format property="run.time" pattern="yyyyMMddHHmm" unit="hour" />
      </tstamp>

      
    </project>


Something like this where there are spaces in between "sections." This is for readability. So something like the example you provided in XmlDocument but with XDocument, that would be awesome.

**Comment by sepidehMS** [comment]
@akcorp2003 I don't think `XDocument` has this functionality. I'm not sure, but it might be a bug in XDocument. It needs further investigation. In the meantime, is there a reason you cannot use `XmlDocument` instead? If that's the case, a post-process on the xml document would help you workaround this.

**Comment by akcorp2003** [comment]
I can use XmlDocument with no problem. This would just be a nice feature to have for XDocument.

**Comment by krwq** [comment]
Closing this since workaround exists and currently does not seem we will fix it. Please upvote and comment if you agree that we should add similar API to XDocument.
