### ISSUE TITLE
Re-enable reflection only tests

### ISSUE THREAD

**Issue by rahku** [dotnet/corefx#15673]

**Comment by rahku** [comment]
Disabling tests as they will start to fail due to changes in coreclr repo. Will re-enable once coreclr dependencies are updated

**Comment by karelz** [comment]
@rahku it would be nice to provide reference to the "changes in coreclr" you refer to.

**Comment by rahku** [comment]
this is no longer needed

**Comment by karelz** [comment]
@rahku what do you mean by that it is not needed?
