### ISSUE TITLE
Missing DataSetSchemaImporterExtension implementation

### ISSUE THREAD

**Issue by marek-safar** [dotnet/corefx#15682]
CoreFX is missing implementation of [DataSetSchemaImporterExtension](https://msdn.microsoft.com/en-us/library/system.data.datasetschemaimporterextension(v=vs.110).aspx) which is available since .net 2.0 and not obsolete but missing in CoreFX.

cc: @karelz @egorbo

**Comment by karelz** [comment]
@weshaggard @stephentoub @saurabh500 @YoungGah can you please comment why we left it out from Data porting?

**Comment by stephentoub** [comment]
IIRC, because SchemaImporterExtension doesn't exist in CoreFx, either.

**Comment by stephentoub** [comment]
Can this be closed?  Or is all of the schema importer stuff going to come back?

**Comment by karelz** [comment]
@weshaggard @danmosemsft can you please comment? How did we decide what's in and what's out for Data?

**Comment by danmosemsft** [comment]
@zhenlan should comment on why we don't have SchemaImporterExtension.

**Comment by karelz** [comment]
Clarification for my future self: `System.Data.DataSetSchemaImporterExtension` depends on `System.Xml.Serialization.Advanced.SchemaImporterExtension`

**Comment by zhenlan** [comment]
Looks like `System.Xml.Serialization.Advanced.SchemaImporterExtension` has dependency on CodeDom. Maybe that's the reason it is not included in netstandard?

The `SchemaImporterExtension` can be found at [standard/extensions/codedom/codedom.cs](standard/extensions/codedom/codedom.cs ). Not sure what's that for. @weshaggard made the change and may have more context.

cc: @shmao

**Comment by weshaggard** [comment]
Things under the extensions folder in the standard repo are not part of the standard but can potentially be provided as extensions on top of the standard. There is no commitment that it will ever happen though. 

The extension folder is mostly for my test validation when refactoring the standard.

**Comment by zhenlan** [comment]
Thanks for the clarification @weshaggard. I think this issue can be closed now unless we change mind to bring CodeDom to NS2.0.

**Comment by stephentoub** [comment]
Is there anything that would prevent it from being in .NET Core 2.0 even if not in NS 2.0?

**Comment by weshaggard** [comment]
Nothing that would technically block it but it would pull CodeDom and its closure into the shared framework which I would prefer to avoid.
