### ISSUE TITLE
Question: style guide for abbreviations

### ISSUE THREAD

**Issue by dermeister0** [dotnet/corefx#15686]
I noticed that EntityFramework does not follow the Microsoft guideline:
[Capitalization Conventions](https://msdn.microsoft.com/en-us/library/ms229043(v=vs.110).aspx)

> A special case is made for two-letter acronyms in which both letters are capitalized, as shown in the following identifier:
> IOStream

DbSet, DbContext should be written as DBSet, DBContext. Examples: [IDataRecord.IsDBNull](https://msdn.microsoft.com/en-us/library/system.data.idatarecord.isdbnull(v=vs.110).aspx), [System.DBNull](https://msdn.microsoft.com/en-us/library/system.dbnull(v=vs.110).aspx).

Another example:

```c#
    public static partial class EF
```

It should be written as Ef, if another guidelines are used.

However, I did not find any info that Microsoft team has changed the capitalization rules. The document has no any description about it:
https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md

Can you clarify ASP.NET team position about 2-letter acronyms?

[StyleCop](https://github.com/StyleCop/StyleCop) and [CodeFormatter](https://github.com/dotnet/codeformatter) have no special rules for this case.

SonarQube has a wrong rule [S101](https://sonarqube.com/coding_rules#rule_key=csharpsquid%3AS101):

>  warning S101: Rename class "RabbitMQTest" to match camel case naming rules, consider using "RabbitMqTest".

**Comment by karelz** [comment]
ASP.NET incl. EF are in different repos: https://github.com/aspnet
CoreFX coding style is only for CoreFX repo AFAIK, although I expect it won't be so different from ASP.NET coding style.

Closing for now, let me know if you still have questions about CoreFX coding guidelines, we can reopen.
