### ISSUE TITLE
Get rid of System.IO.Compression OOB - .NET Standard 2.0 should forward to Desktop Framework

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#15693]
The cost of shipping OOB for Desktop is very high and we have burned ourselves (System.Net.Http). Let's make sure we do not accidentally run into the same problems here as well.

cc: @ianhays @weshaggard

**Comment by ianhays** [comment]
cc: @ericstj

**Comment by mellinoe** [comment]
Presumably this was done to introduce new functionality or fix bugs, etc. Are we going to regress any of that?

**Comment by karelz** [comment]
@weshaggard mentioned we "just" fixed bugs. And yes, we are going to regress that, consciously.

**Comment by ianhays** [comment]
We'll also be removing [support for zips using deflate64](https://github.com/dotnet/corefx/issues/9925) that was added in https://github.com/dotnet/corefx/pull/11264.

**Comment by karelz** [comment]
Did it add any new APIs? Or "just" extend behavior of existing ones?

**Comment by ianhays** [comment]
It extended the functionality of existing APIs.

**Comment by karelz** [comment]
Thanks for confirmation. Despite that I still believe we should rather make the change in .NET Standard 2.0.

**Comment by ianhays** [comment]
I agree.
