### ISSUE TITLE
System.Net.Sockets solution file is broken

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#15702]
If I try to open it in VS, I don't see the System.Net.Sockets.csproj in src -- just the ref and test projects.

If I try to build it from the command line, it doesn't actually build System.Net.Sockets.csproj.

**Comment by mellinoe** [comment]
The solution files are currently broken, unfortunately; it's a known issue. @weshaggard 

Beside that, though, I wouldn't recommend building the solution files from the command-line anyways; it's never been something that we've tested or has reliably worked in the past.

**Comment by weshaggard** [comment]
This is fixed with https://github.com/dotnet/corefx/pull/15738.
