### ISSUE TITLE
Remove restriction in System.Memory configuration.props that builds for Windows only 

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#15703]
From PR #15569
https://github.com/dotnet/corefx/pull/15569#discussion_r98976731

From **kouvel**:
>  Since it looks like you're also enabling CoreCLR's span with this change, could you please also remove the restriction in Configuration.props that builds for Windows only? This would work fine I think:
```xml
    <BuildConfigurations>
      netcoreapp;
    </BuildConfigurations>
```
> And can remove any windows-specific stuff in the csproj.

From **mellinoe**:
> This is an "artificial" restriction that needs to be kept for now. This library relies on System.Runtime.CompilerServices.Unsafe, which cannot be built outside of Windows right now.

From **kouvel**:
> Is it possible to use CoreLib's Unsafe implementation instead? Maybe it would require making it public in CoreLib (but without a contract in CoreFX), which seems reasonable, as that's what we did for RuntimeThread as well.

From **jkotas**:
> Having the exact same public type it multiple different assemblies tends to cause problems. If we wanted to use the CoreLib Unsafe here, it should be fine but we need to:
> - Give CoreLib Unsafe different name or namespace, e.g. Internal.Runtime.CompilerServices (I think this option is better)
     or 
> - Fill CoreLib Unsafe to have all methods that S.R.CS.Unsafe has, and turn S.R.CS.Unsafe into façade for netcoreapp20

**Comment by mellinoe** [comment]
I'm going to try to chase down https://github.com/dotnet/buildtools/issues/1301 again, once I finish my current work items. That's what is blocking System.Runtime.CompilerServices.Unsafe from building outside Windows.

**Comment by weshaggard** [comment]
@mellinoe I believe this is done now correct?

**Comment by mellinoe** [comment]
Done.
