### ISSUE TITLE
Is there a function to copy directories?

### ISSUE THREAD

**Issue by akcorp2003** [dotnet/corefx#15708]
Currently, the `Directory` class contains a `Move()` method. However, the class does not possess a way to copy directories from one location to another. If a user wants to copy directories, he/she would have to write their own method to create a directory in the new location and call `File.Copy()` for each file in the source directory.

## Rationale and Usage

The `File` class has both `Copy()` and `Move()` methods; however, the `Directory` class only has a `Move()`. Conceptually, a file and a directory are very similar: you can move or copy either of them across your file system. There are many users who [desire](https://stackoverflow.com/questions/627504/what-is-the-best-way-to-recursively-copy-contents-in-c) this feature and there is also an instructive [MSDN article](https://msdn.microsoft.com/en-us/library/bb762914(v=vs.110).aspx) outlining how to copy directories. 

It will be very convenient for users to simply call a `Copy()` method such as,

```csharp
string SourceDirectory = @"C:\sourcefolder";
string DestinationDirectory = @"C:\destinationfolder";
Directory.Copy(SourceDirectory, DestinationDirectory);
```

Further, users will only need to pass in a string without needing to create `DirectoryInfo` so that the parameters are easy to use.

## Proposed API

```csharp
public void Copy(string sourceDirName, string destDirName)
{
     DirectoryInfo sourceDirectory = new DirectoryInfo(sourceDirName);
     DirectoryInfo destinationDirectory = new DirectoryInfo(destDirName);
     if (!Directory.Exists(target.FullName))
     {
        Directory.CreateDirectory(target.FullName);
     }

     //copy all the files into the new directory
     foreach (FileInfo file in sourceDirectory.GetFiles())
     {
         file.CopyTo(Path.Combine(target.ToString(), file.Name), true);
     }

     //copy all the sub directories using recursion
     foreach (DirectoryInfo subDirectory in sourceDirectory.GetDirectories())
     {
         DirectoryInfo nextTargetDir = destinationDirectory.CreateSubdirectory(subDirectory.Name);
         Directory.Copy(subDirectory.FullName, nextTargetDir.FullName);
     }
}
```

**Comment by danmosemsft** [comment]
As far as I know no (there's a ?cleaner way at the bottom [here](http://stackoverflow.com/questions/627504/what-is-the-best-way-to-recursively-copy-contents-in-c)). 

You can propose an API for this if you want:
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md

**Comment by danmosemsft** [comment]
@akcorp2003 going through old issues -- any interest in writing up a proposal (update top comment) like the example linked to in the review process linked above?

**Comment by akcorp2003** [comment]
@danmosemsft I totally forgot that I made this issue! Yeah! I have interest in writing something up. I've never contributed to a significant open source project before. So is the process for me to fork this repo, build it, write my changes, and submit a pull request? I've taken a look at the API Review process so I kinda know what to expect.

**Comment by danmosemsft** [comment]
@akcorp2003 we have a formal process (once we have an API we have to support it for X years so we have to think it through) which is basically what is in the markdown document linked above. So the first thing is to tidy up the proposal to be roughly like this example https://github.com/dotnet/corefx/issues/271 
When you've done that, area owner will give you feedback. If they think it is worth adding, they will tag it api-ready-for-review. Then it goes to review board ideally in a week or two after. If they okay it, it is up for implementatoin, by you if you like, or someone else. Or it could be rejected. But first step is write it up.
Call me up by name if you get stuck.

**Comment by akcorp2003** [comment]
@danmosemsft Great! I should be able to write something up then in a week or so. Thanks for outlining the process!

**Comment by akcorp2003** [comment]
@danmosemsft I cleaned up my first comment to look more like a proposal. What do you think?

**Comment by ashmind** [comment]
(disclaimer: I'm not in the corefx team, just interested in the potential API as a user)

Awesome that this is progressing!
Some thoughts:

1. There is `DirectoryInfo.MoveTo`, so I think having `DirectoryInfo.CopyTo` (in addition to `Directory.Copy`) would be a good idea.

2. Should there be a way to filter which files are copied? Can't be done for the move, but copy is going to iterate anyway.

3. I assume there is no special treatment for junctions? Probably not required, but good to confirm.

4. It feels kind of useful to be able to override individual file copy (e.g. copy as hardlinks, or copy some extras such as ACLs) -- but I can see it might make API too complex.

5. What happens if the copy fails? Is there any way to retry without repeating the whole copy (it's fine if not, might be unnecessary complexity)? What information is included in the exception (as a user I would definitely like to see which file it failed on)?

6. Would there be a benefit in having an Async version?

**Comment by akcorp2003** [comment]
@ashmind 
1. I agree! `DirectoryInfo.CopyTo` would be a great complement if `Directory.CopyTo` gets added to the API. It would be even better as it would only need one parameter for a user to pass into.
2. Would that add unnecessary complexity if a user simply wants to copy some files? Further, we are using this on the `Directory` class and if we're going to call a copy on a directory, it makes sense to copy the entire thing. That being said, I can definitely see how this would be a nice feature.
5. If the copy fails, wouldn't the method `FileInfo.CopyTo` throw an exception?

**Comment by JeremyKuhne** [comment]
API shape needs good. The proposed implementation is obviously just a draft and the final implementation would need parameter validation and as per our other API's would need `GetFullPath` to normalize the inputs.

**Comment by terrajobst** [comment]
We generally have avoided IO APIs with complex policy (such as, cancellation, error handling, recovery, permissions etc). The API shape would work, but we're concerned about the complexity in implementation and don't think it's worth it.
