### ISSUE TITLE
Add TextWriter.Write(string value, int index, int count) overload

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefx#1571]
TextWriter has an overload for writing a segment of a char array with this Write overload: void Write(char[] buffer, int index, int count)

But TextWriter doesn't have an overload for writing a segment of a string, e.g.: void Write(string value, int index, int count)

This means that in cases where you have a segment of a string that you want to write you either need to either substring and pass that value to Write(string) or copy the string to a char array and then use the char array segement overload.

It would be a new virtual method but the default implementation could simply call the current Write(char[] buffer, int index, int count) overload.

The main problem I see with adding Write(string, int, int) is there is a Write(string, object, object) overload that does string formatting that would be hidden. Avoid with different name?

Example of having to having to use the Write(char[] buffer, int index, int count) overload where a string overload would simplify code and improve performance: https://github.com/JamesNK/Newtonsoft.Json/blob/6a22345e28006d74c25e353b6235bc5222bab821/Src/Newtonsoft.Json/Utilities/JavaScriptUtils.cs#L220-L228

**Comment by bbowyersmyth** [comment]
HttpWriter has a specific `public void WriteString(string s, int index, int count)` to solve this problem.
If the same was added to the base TextWriter would that also be classed as a breaking change?

**Comment by JamesNK** [comment]
The default virtual implementation on TextWriter could just copy the string segment to a char array and call Write(char[] buffer, int index, int count). It wouldn't be a breaking change.

**Comment by JamesNK** [comment]
Actually did you mean if TextWriter added WriteString, would that break HttpWriter? I'm pretty sure the method on HttpWriter would just hide the virtual method. HttpWriter wouldn't be able to change its method to an override however.

**Comment by bbowyersmyth** [comment]
Yep that's I meant.
It is unfortunate that `Write(string, object)` wasn't named WriteFormat as with the new name there will be some minor user confusion between:

`Write(string)`
`WriteString(string, int, int)`

But I agree you shouldn't need to do a substring to write a string segment.

**Comment by ellismg** [comment]
I think this is a reasonable addition.  We are trying to figure out what "no-allocation" substring APIs look like, but until we have a holistic design (ideally one that allows us to unify char[] and substring type codepaths) it's probably a good idea to do targeted work where we can get a large bang for the buck.

@KrzysztofCwalina What do you think about this?

**Comment by KrzysztofCwalina** [comment]
I agree, it would be a great addition. The Write/WriteString problem is nasty. I think it's pretty bad that we would endup with Write(string), but WriteString(string, int, int). 
Also, I assume we would do the same addition to WriteLine, WriteAsync, and WriteLineAsync, which would mean lots of new "String" methods. 
Maybe we should just wait till we have a real representation of a substring?

**Comment by karelz** [comment]
Please create formal API proposal.

**Comment by stephentoub** [comment]
TextWriter now has `Write(ReadOnlySpan<char:>)`, which covers this (e.g. `Write(value.AsSpan(index, count))` without copying or allocating.  Given that, I don't think we need to add this overload and I'm going to close it, but please feel free to re-open if you disagree.
