### ISSUE TITLE
Provide Precise UtcNow using Stopwatch. 

### ISSUE THREAD

**Issue by vancem** [dotnet/corefx#15739]
As part general logging infrastructure, it is useful to have timestamps.  DateTime (using UTC) is a fine way of doing this, (it has 100nsec resolution) however DateTime.UtcNow has poor resolution (16msec).    We need a way of getting DateTimes that is more precise.

It is very straightforward to implement this using System.Diagnostics.Stopwatch.   Thus we recommend adding the following API to it

```c#
class System.Diagnostics.Stopwatch {
     // Computes a more precise UtcNow time.  
      static DateTime UtcNow { get; } 
}
```

The implementation simply fetches 'DateTIme.UtcNow' and the current stopwatch tick count and uses that to compute the DateTIme when stopwatch ticks started.    You can then use a call to Stopwatch.GetTimeStamp() and this start time to compute UtcNow (the current time).   

I considered putting this API in DateTIme, but decided against it because
1. The implementation naturally depends on Stopwatch.
2. Users of Stopwatch are the natural clients of this API.   
3. We would end up with UtcNow and UtcNowPrecise, which feels a bit ugly.   
4. DateTime lives in CoreCLR which complicates the implementation if we put it there.  The dependencies don't work out.  
  
@terrajobst @lmolkova

**Comment by jkotas** [comment]
> You can then use a call to Stopwatch.GetTimeStamp() and this start time to compute UtcNow (the current time).

Isn't this implementation going to drift over time (e.g. when the system time is getting adjusted)?

Have you considered implementing it by calling `GetSystemTimePreciseAsFileTime` instead? As side-effect, it would avoid the need to have active Stopwatch instance to get current UtcTime.

**Comment by drieseng** [comment]
https://github.com/dotnet/coreclr/issues/5061

**Comment by drieseng** [comment]
Using ```GetSystemTimePreciseAsFileTime```  for ```DateTime.UtcNow``` is already being discussed here: https://github.com/dotnet/coreclr/issues/5061.

**Comment by terrajobst** [comment]
Before we add a new API, we'd like to understand:

* Why wouldn't we make the existing one more precise? Presumably, the API is "fast" either way, but the difference would register when called in hot loop. For folks that do call the API in a hot loop, wouldn't the precision matter anyway?
* `Stopwatch` is our place for high-precision measurement, but it doesn't seem likely that folks would search here.
* Do we need a high-precision `DateTimeOffset` API as well?

**Comment by vancem** [comment]
This thread should be put on hold until  issue #5061 is decided, as it resolves this issue raised here.  

To answer @terrajobst question, I don't think we need a DateTimeOffset variation because this is UTC (thus always a particular time zone), and we want it to be as simple and fast as possible (it really is for timestamping).
