### ISSUE TITLE
Library author wants to target netstandard and work with packages.config with LTS

### ISSUE THREAD

**Issue by onovotny** [dotnet/corefx#15735]
This bug needs to be back ported to NETStandard.Library -- 1.6.0.1 -- and remain in the LTS that works everywhere.

The issue was fixed here https://github.com/dotnet/corefx/issues/10445, but only is available in FTS.

This means that 1.6.0 is broken here.

@ericstj

**Comment by ericstj** [comment]
We need to look at bringing this fix into 1.0 servicing and providing library authors with a meta-package that keeps them on the rails for building libraries that stay on LTS and work everywhere.  The RuntimeInformation bug was blocking folks from using the package in packages.config based projects.

/cc @leecow @karelz

**Comment by karelz** [comment]
@weshaggard can you help while @ericstj is OOF?
@leecow how much time we have for 1.0 servicing?

**Comment by onovotny** [comment]
When I talked to @ericstj before he went OOF, he mentioned he'd try to prep a branch with the changes? Not sure if he got to it or where it is....

**Comment by leecow** [comment]
@karelz the window is closed at 6pm tonight for the March release. We should talk first thing in the morning if this is a must-have. 

/cc @gkhanna79

**Comment by onovotny** [comment]
@leecow IMO this is a must have because it's causing active pain for package.config users with netstandard1.1 PCL profiles....and that's going to be many people initially. What's "worse" is that 1.6.1 fixes it but has the bad side-effect re LTS/FTS with .NET Core. It *shouldn't* but it does.

**Comment by leecow** [comment]
Thanks for the additional information @onovotny. Very important.

**Comment by karelz** [comment]
cc @terrajobst @Petermarcu @danmosemsft - blocking 1.0.x release.

Probably stupid question (sorry, packaging is still new to me :(): What exactly is the scenario which does break today? (I looked at the referenced issue, but couldn't put it together, again sorry if it is stupid question)

**Comment by onovotny** [comment]
Here's the scenario:

User with netstandard 1.1-level legacy PCL project (Profile 111, 151, etc), with a packages.config file (everyone today), adds a NuGet reference to a netstandard 1.1 package. That package has a dependency on NETStandard.Library 1.6.0 because they've been told to (and the tooling does it for them).

Now install of that package fails for that PCL user because the RuntimeInformation package did not have anything in the `\lib\netstandard1.1` directory. Instead, it used a NuGet v3 feature (`\runtimes\netstandard1.1\...`) for it. The result is that it works fine with Project.json but not with packages.config.

This affects Xamarin users in particular as many of the default templates use PCL 111 or 151 for common code. Thus if they try to use any other package that transitively brings in netstandard.library 1.6.0, the nuget install fails. It does affect more than just Xamarin users -- really anyone who uses a netstandard1.1 compatible PCL profile.

**Comment by karelz** [comment]
Thanks @onovotny for your explanation! I also chatted a bit with @weshaggard and here's summary (please correct me if I am wrong):
* .NET Core 1.0 (meta-package 1.6.0, LTS) - System.Runtime.InteropServices.RuntimeInformation 4.0.0 package has a (packaging) bug - customer impact described in https://github.com/dotnet/corefx/issues/15735#issuecomment-278642111
* .NET Core 1.1 (meta-package 1.6.1, FTS) shipped 4.3.0 RuntimeInformation package which addressed the problem for FTS (see #10445) and also delivered other bug fixes
* **Asks:**
  1. Ship 4.0.1 RuntimeInformation package that addresses the packaging bug also for LTS (.NET Core 1.0).
  2. Ship meta-package 1.6.0.1 which includes the 4.0.1 RuntimeInformation package.
      * Concern: We never shipped any meta-package with just 4th version number difference - there is a risk some tooling or end-to-end scenarios will not work properly. We need to test it properly before releasing.

Given all the information, we do not consider it release (1.0.4) blocking (we are in escrow mode) - removing the label.
We should track it for next 1.0.x version.

**Comment by onovotny** [comment]
That is the summary, thanks @karelz. Hopefully this can hit Update 1 and the next release as soon as possible....

**Comment by onovotny** [comment]
That is the summary, thanks @karelz. Hopefully this can hit Update 1 and the next release as soon as possible....

**Comment by onovotny** [comment]
As part of this update, the changes in https://github.com/dotnet/standard/pull/215 should be incorporated as well to alleviate customer pain and reduce the "why is it pulling in so many packages" freak-out people get.

**Comment by ericstj** [comment]
One alternative I'd like folks to consider that doesn't involve 4-part versions:
1. Do RuntimeInformation change in 1.0.
2. In 1.1 branch change NETStandard.Library to ref LTS packages for netstandard1.*, and netcoreapp1.0.  For netcoreapp1.1 reference FTS packages.
3. Trim dependencies on platforms with inbox impl.
4. Ship NETStandard.Library 1.6.2.

I think this is a better story for everyone, the downsides are that targeting netstandard1.x will bring in additional older packages.  There's also a potentially breaking change if folks were relying on NETStandard.Library bringing in the LTS version of the package.

**Comment by weshaggard** [comment]
That seems like a reasonable strategy to me. We could even consider doing (1) in the 1.1.0 branch and rebaselining that package.

**Comment by jkotas** [comment]
Anything left to do here?
