### ISSUE TITLE
Remove __BlockReflectionAttribute from pure facades

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#15741]
For libraries that are pure facades we should avoid injecting the __BlockReflectionAttribute (https://github.com/dotnet/corefx/blob/ddadb906e40ed97cba9f9c58ad2f5642e0d91b50/dir.props#L78).

The reason we should block it for pure facades is because we have detection logic that breaks when there are any type defs including the internal one we inject for __BlockReflectionAttribute so we should disable it for those facades.

**Comment by danmosemsft** [comment]
@weshaggard because that condition rotted, we're not doing it at all now. What shoudl the condition be?

**Comment by danmosemsft** [comment]
Not working at all right now: https://github.com/dotnet/corefx/issues/16022

**Comment by weshaggard** [comment]
@danmosemsft this is a slightly different issue from #16022. This is about the facades and that issue is just about Microsoft.CSharp.

**Comment by weshaggard** [comment]
Putting in UWP6.1 milestone as this issue is only applicable to UWP.

**Comment by joshfree** [comment]
@weshaggard do you want to look into this for UWP 6.1?

**Comment by weshaggard** [comment]
While I'm happy to consult I'm not in a great position to test it out so would prefer someone working on UWP work to pick it up.
