### ISSUE TITLE
Clean up sequencing of targets that change ProjectReferences

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#15744]
We have a few places where we change ProjectReferences.

AnnotateProjectReference in buildvertical.targets
ResolveMatchingContract in resolvecontract.targets
AddRuntimeProjectReference in referenceFromRuntime.targets
MarkReferencePrivateFalse in FrameworkTargeting.targets

I think the squence should be
ResolveMatchingContract | AddRuntimeProjectReference > MarkReferencePrivateFalse  | AnnotateProjectReference > AssignProjectConfiguration 

The `|` indicates they can happen in any order.  The `>` indicates they must happen before the following targets.

We should determine a way to do that with minimal coupling between the targets.

**Comment by weshaggard** [comment]
As an added note when doing a `/t:rebuild` on an individual project that has ReferenceFromRuntime references it will fail because the projects will not get rebuilt.

**Comment by weshaggard** [comment]
Fixed with #15917
