### ISSUE TITLE
Add Odbc and SQLite OS deps to CI

### ISSUE THREAD

**Issue by tinchou** [dotnet/corefx#15776]
I'm working on [porting System.Data.Odbc](https://github.com/dotnet/corefx/pull/15646). I talked to a couple of people and we decided on writing some integration tests that would hit a SQLite database. Main reasons: easy to set up and cross-platform.

For things to work, I need two pieces:

* An Odbc library
* A SQLite Odbc Driver

On Windows:

* We use `odbc32.dll`, which is probably already installed in our CI
* I tested this using http://www.ch-werner.de/sqliteodbc/ driver

On Linux (Ubuntu 16.04):

* I tested this using `unixodbc` from the official repositories
* I tested this using `libsqliteodbc` from the official repositories

On OSX: haven't tested yet.

Tests are skipped at the moment so my PR passes the CI check, but it would be nice to enable them after we get this in. Otherwise, I'll leave a note for devs on how to run this manually, but we'd have this library untested.

ping @divega @anpete @saurabh500 @eerhardt @weshaggard @danmosemsft

**Comment by karelz** [comment]
cc @mellinoe

**Comment by mellinoe** [comment]
We'll need to consider what we can use outside of Ubuntu, as well, preferably on all of the distros we support.

**Comment by tinchou** [comment]
Our library only depends on odbc being present *at runtime* (and unixODBC
is available everywhere non Windows). Then the native library handles the
connection to the driver transparently, be it SQLite or any other.

Now for the test *to run in CI*, we do need odbc and a SQLite driver.

Regarding support in other platforms:

* I'm trying to find a Mac for testing on Monday
* I can spin up some docker containers for testing in our other supported
distros and check the required libraries are in every official repository,
but in any case it'd be the user responsibility to get those libraries

Thanks!

**Comment by tinchou** [comment]
Note on unixODBC: our own new and shiny ODBC Drivers for SQL Server on Linux and Mac rely on it https://mspoweruser.com/odbc-driver-13-1-linux-mac-released/

**Comment by tinchou** [comment]
@chcosta I've read you maintain https://github.com/dotnet/corefx/tree/master/buildpipeline, so maybe you can help us out.

I've been running docker locally to test these changes, and it seems I only need two extra packages for everything to work in Linux. The only minor hiccup I can see is that libsqliteodbc is missing from Debian Jessie, but it's available on Wheezy, Stretch and Sid: https://packages.debian.org/wheezy/libsqliteodbc.

For OSX, I need those two packages + the following configuration in `/usr/local/opt/unixodbc/etc/odbcinst.ini`:

```ini
[SQLite3]
Description = SQLite3 ODBC Driver
Driver      = /usr/local/opt/sqliteodbc/lib/libsqlite3odbc.so
Setup       = /usr/local/opt/sqliteodbc/lib/libsqlite3odbc.so
```

@saurabh500 suggested we might need Legal to approve `PInvok`ing into unixODBC, but I think it'd be great if we had a PR ready to merge for when we get confirmation.

Thanks!

**Comment by chcosta** [comment]
@dleeapho should be able to help with docker / machine configuration requirements.

**Comment by dleeapho** [comment]
@MichaelSimons can you work with @tinchou on Docker / machine config? Thx.

**Comment by MichaelSimons** [comment]
@mmitche Can you work with @tinchou to get the appropriate CI machines configured.
@tinchou I can work with you to get the Docker images updated as needed for the official builds.

**Comment by mmitche** [comment]
@MichaelSimons @tinchou Yea.

**Comment by tinchou** [comment]
cc @divega @danmosemsft 

Today we discussed with @Chrisboh about the fact that some distros ship very old versions of unixodbc (such Ubuntu 14.04 with `unixodbc:2.2.14` from Nov 19, 2008).

We need at least version 2.3.1, since it's the first one that ships the `libodbc.so.2` binary. Falling back to older versions is an option, but they're very old and I think we shouldn't be targetting them.

The options I can think of are:

1. Drop support for older versions. I've been told .NET Core 2.0 might have a different support matrix, so this might be a good option. @Petermarcu do you have any input about this?
2. Fall back to older versions of unixodbc, with the risk of facing bugs
3. Add unixodbc to the feeds we use to distribute .NET Core (e.g. https://packages.microsoft.com/ubuntu/14.04/prod)
4. Get in touch with the SQL Server team and use their feeds. They ship a custom version of unixodbc as can be seen here: https://docs.microsoft.com/en-us/sql/connect/odbc/linux/installing-the-microsoft-odbc-driver-for-sql-server-on-linux

Then, regardless of what we do, we also need to discuss about the user experience and documentation on how to get started with `System.Data.Odbc`. There will always be manual steps, as people will always need to install the database-specific drivers. But depending on which distro and version you're using, how you get unixodbc might be different.

**Comment by danmosemsft** [comment]
I believe we're going to rely on testing locally for now.
