### ISSUE TITLE
HttpPrefixes

### ISSUE THREAD

**Issue by gregoryyoung** [dotnet/corefx#1577]
So http prefixes ... Its an IIS specific API that makes zero sense when IIS is no longer present. I know this code hasn't come over yet code wise  but I figured I would create an issue for it for discussion about what may happen.

As an example I want to:

Bind to 192.168.1.101 : 1111
Allow an elastic ip with a round robin dns to be used.

In mono as example this will cause it to bind *:1111 and allow which is totally not what I wanted, there is no good way in the current api of actually specifying. 

I can specify 192.168.1.101:1111/ just fine. What happens when I as well specify myroundrobindns:1111/? Do I mean that I want to allow this host header or to bind to this interface? This is where the problem starts.... What if I only specified the myroundrobindns:1111? Then it would make sense to bind all or give me an error (without IIS). But this behaviour makes it impossible to do the above (common use case).

There are literally dozens of derpy little gotchas like this (and no good way of working around them) due to how the api is laid out and not wanting to break compatibility with msclr. 

Whats the plan for CoreFX?

Thoughts?

Greg

**Comment by SidharthNabar** [comment]
@davidfowl @Tratcher - Since HttpListener is not in plan for .NET Core and is being replaced by WebListener, it would be good to understand the plan for WebListener and prefixes API

**Comment by gregoryyoung** [comment]
Can I get a link to the plans on "WebListener"?

**Comment by Tratcher** [comment]
@gregoryyoung Come over to https://github.com/aspnet/home/ to discuss http servers.

We're working on three: 1) IIS integrated, 2) WebListener for services (windows only), and 3) Kestrel for cross-platform. It sounds like you're asking about cross-platform. Here is the recent discussion we had around binding for Kestrel: https://github.com/aspnet/KestrelHttpServer/issues/98#issuecomment-121390683

**Comment by gregoryyoung** [comment]
Thanks will check.

On Tuesday, July 28, 2015, Chris R <notifications@github.com> wrote:

> @gregoryyoung <https://github.com/gregoryyoung> Come over to
> https://github.com/aspnet/home/ to discuss http servers.
>
> We're working on three: 1) IIS integrated, 2) WebListener for services
> (windows only), and 3) Kestrel for cross-platform. It sounds like you're
> asking about cross-platform. Here is the recent discussion we had around
> binding for Kestrel: aspnet/KestrelHttpServer#98 (comment)
> <https://github.com/aspnet/KestrelHttpServer/issues/98#issuecomment-121390683>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dotnet/corefx/issues/1577#issuecomment-125678186>.
>


-- 
Studying for the Turing test

**Comment by CIPop** [comment]
@SidharthNabar Sounds like this is not a corefx issue given that we have no plans on adding support for HTTP.SYS/IIS.

@gregoryyoung Please follow-up at the link @Tratcher shared above and re-open the issue there. Hopefully there is a way to integrate across accounts rather than asking you to re-open... unfortunately I'm new to GitHub so I have no idea how to do that.
