### ISSUE TITLE
SslStream_StreamToStream_ClientInitiatedCloseNotify_Ok  failed

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#15785]
failed in #15782

     System.Net.Security.Tests.SslStreamAlertsTest.SslStream_StreamToStream_ClientInitiatedCloseNotify_Ok [FAIL]
        System.ComponentModel.Win32Exception : The credentials supplied to the package were not recognized
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\Common\src\Interop\Windows\sspicli\SSPIWrapper.cs(167,0): at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED scc)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SslStreamPal.Windows.cs(407,0): at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED secureCredential)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SslStreamPal.Windows.cs(131,0): at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SecureChannel.cs(676,0): at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SecureChannel.cs(783,0): at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SecureChannel.cs(706,0): at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SslState.cs(767,0): at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SslState.cs(983,0): at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SslState.cs(1145,0): at System.Net.Security.SslState.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SslState.cs(731,0): at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
              at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           D:\j\workspace\windows_nt_re---37265eab\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs(19,0): at System.Threading.Tasks.TaskTimeoutExtensions.<TimeoutAfter>d__0.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\tests\FunctionalTests\SslStreamAlertsTest.cs(111,0): at System.Net.Security.Tests.SslStreamAlertsTest.<SslStream_StreamToStream_ClientInitiatedCloseNotify_Ok>d__4.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by karelz** [comment]
cc @steveharter @Priya91 @ianhays

**Comment by ianhays** [comment]
Tracking in https://github.com/dotnet/corefx/issues/14519.

This issue is of the same class as #8744, #12683, #12706, and #12728 - duplicate issues failing because of an intermittent error (credentials package not recognized) that occurs in several NetSecurity tests.

I'm about to re-enable all of these tests in https://github.com/dotnet/corefx/pull/15952 to try to get some better data on the circumstances under which they fail, because I can't get them to do so on a local machine at all.

**Comment by ianhays** [comment]
Tracking this failure in #16516. Please comment there with any failure reports instead of re-opening this issue.
