### ISSUE TITLE
Developer Guide refers to retired xUnit component

### ISSUE THREAD

**Issue by jaredpar** [dotnet/corefx#158]
The xUnit team recently retired the Visual Studio test runner extension.  It is no longer present on the gallery and there is no fallback location to install it from.  The developer guide still references this extension and hence is unactiionable to developers.  

The runner is now shipped as the NuGet package `xunit.runner.visualstudio`.  This needs to be installed directly on libraries that load in Visual Studio and contain xUnit tests.  

Reference: http://xunit.github.io/docs/running-v1-tests-in-vs.html

**Comment by ellismg** [comment]
This is fixed.
