### ISSUE TITLE
Delete desktop BinaryCompatibility settings from System.Private.Xml

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#15809]
https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/Core/BinaryCompatibility.cs

This code does private reflection against desktop mscorlib and read full framework registry keys; none of which works well for .NET Core.

We should either delete it (preferred); or replace it with .NET Core compatible quirk if it is important to keep it.

As side-effect, this will also get rid of dependency on System.Private.Xml on Microsoft.Win32.Registry.

**Comment by weshaggard** [comment]
I'd prefer we remove it completely as well.
