### ISSUE TITLE
Code coverage report does not match tests

### ISSUE THREAD

**Issue by FireAlkazar** [dotnet/corefx#15817]
I'm working on System.Configuration code coverage #15554 and a little bit stuck with coverage report.

**Problem description**
There is a test, that covers exception catch and throw in method, but both local and CI code coverage reports show, that the lines of method code are not covered.

**Details**
[Test for System.Configuration.TypeUtil](https://github.com/dotnet/corefx/blob/a8dce7c1c905e994c9519e0f26b0497832942a10/src/System.Configuration.ConfigurationManager/tests/System/Configuration/TypeUtilTests.cs#L48)
[TypeUtil line, that works for test](https://github.com/dotnet/corefx/blob/a8dce7c1c905e994c9519e0f26b0497832942a10/src/System.Configuration.ConfigurationManager/src/System/Configuration/TypeUtil.cs#L115)
[Code Coverage Report](https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/Code_Coverage_Report/), navigate to `System.Configuration.TypeUtil`, click `GetType(System.String,System.Boolean)` method to see code coverage. 

I've checked that this line is reached by changing exception to `ArgumentException("hahaha")` in method and test, but the report still shows no coverage. Test works fine.
![image](https://cloud.githubusercontent.com/assets/936356/22625428/a0ee9eb0-eba7-11e6-8f72-9edf02419b4a.png)
![image](https://cloud.githubusercontent.com/assets/936356/22625516/3cbbbdd0-ebaa-11e6-9f0b-7ce20768ef18.png)

cc @karelz @JeremyKuhne @danmosemsft @dhoehna

**Comment by stephentoub** [comment]
It's showing as not covered because that code isn't covered: the System.Configuration.ConfigurationManager.Tests project is including the TypeUtil.cs file from the src into the tests project, so the code that's getting executed here is the copy in the tests project, not in the actual library:
https://github.com/dotnet/corefx/blob/master/src/System.Configuration.ConfigurationManager/tests/System.Configuration.ConfigurationManager.Tests.csproj#L27-L29

**Comment by FireAlkazar** [comment]
@stephentoub thank you, that explains  the case. So, we can't relay on report, that estimates coverage.

**Comment by stephentoub** [comment]
> thank you, that explains the case. So, we can't relay on report, that estimates coverage.

IMHO, we should change the test project to not include this code, and then write tests that exercise this code in the product via the public entrypoints.
