### ISSUE TITLE
Span: Add BinarySearch(...) extension methods for ReadOnlySpan<T> (and Span<T>)

### ISSUE THREAD

**Issue by nietras** [dotnet/corefx#15818]
Currently, there is no way to binary search in sorted native or fixed memory (e.g. coming from a pointer) in .NET, this proposal intends to fix that by adding binary search extension methods to `ReadOnlySpan<T>` (and currently also `Span<T>` due to type inference issues), but also proposes some different overloads than seen on `Array` to allow for inlined comparisons via the possibility to use value type comparables and comparers.

### Proposed API
Add a set of `BinarySearch` extension methods for `ReadOnlySpan<T>` and `Span<T>` in `SpanExtensions`:
```csharp
    public static class SpanExtensions
    {
        // Convenience overload
        public static int BinarySearch<T>(
            this ReadOnlySpan<T> span, IComparable<T> comparable) 
        { return BinarySearch<T, IComparable<T>>(span, comparable); }

        public static int BinarySearch<T, TComparable>(
            this ReadOnlySpan<T> span, TComparable comparable) 
            where TComparable : IComparable<T> 
        { throw null; }

        public static int BinarySearch<T, TComparer>(
            this ReadOnlySpan<T> span, T value, TComparer comparer) 
            where TComparer : IComparer<T>
        { throw null; }

        // NOTE: Due to the less-than-ideal generic type inference 
        //       in the face of implicit conversions,
        //       we need the overloads taking Span<T>. 
        //       These simply forward to ReadOnlySpanExtensions.

        // Convenience overload
        public static int BinarySearch<T>(
            this Span<T> span, IComparable<T> comparable) 
        { return BinarySearch<T, IComparable<T>>(span, comparable); }

        public static int BinarySearch<T, TComparable>(
            this Span<T> span, TComparable comparable) 
            where TComparable : IComparable<T> 
        { return BinarySearch<T, TComparable>((ReadOnlySpan<T>)span, comparable); }

        public static int BinarySearch<T, TComparer>(
            this Span<T> span, T value, TComparer comparer) 
            where TComparer : IComparer<T>
        { return BinarySearch((ReadOnlySpan<T>)span, value, comparer); }
    }
```

### Rationale and Usage
Provide a safe yet fast way of binary searching of any type of contiguous memory; managed or unmanaged.

```csharp
public static class UsageForInt
{
    struct InlineableComparer : IComparer<int>
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public int Compare(int a, int b)
        {
            if (a == b) { return 0; }
            if (a < b) { return -1; }
            return 1;
        }
    }

    struct InlineableComparable : IComparable<int>
    {
        int m_value;
        
        public InlineableComparable(int value)
        {
            m_value = value;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public int CompareTo(int other)
        {
            if (m_value == other) { return 0; }
            if (m_value < other) { return -1; }
            return 1;
        }
    }

    public static void SpanBinarySearch()
    {
        var span = new Span<int>();

        //span.Sort();

        int valueToFind = 42;

        // Direct value
        var index = span.BinarySearch(valueToFind);

        // Inlineable struct comparer
        var comparer = new InlineableComparer();
        index = span.BinarySearch(valueToFind, comparer);

        // Inlineable struct comparable
        var comparable = new InlineableComparable(valueToFind);
        index = span.BinarySearch(comparable);
    }

    public static void ReadOnlySpanBinarySearch()
    {
        ReadOnlySpan<int> span = new Span<int>();

        //span.Sort();

        int valueToFind = 42;

        // Direct value
        var index = span.BinarySearch(valueToFind);

        // Inlineable struct comparer
        var comparer = new InlineableComparer();
        index = span.BinarySearch(valueToFind, comparer);

        // Inlineable struct comparable
        var comparable = new InlineableComparable(valueToFind);
        index = span.BinarySearch(comparable);
    }
}

public static class UsageForCompound
{
    struct Compound
    {
        public float FeatureValue;
        public int FeatureIndex;
        public object Payload;
    }

    struct InlineableFeatureValueComparer : IComparer<Compound>
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public int Compare(Compound a, Compound b)
        {
            if (a.FeatureValue == b.FeatureValue) { return 0; }
            if (a.FeatureValue < b.FeatureValue) { return -1; }
            return 1;
        }
    }

    struct InlineableFeatureComparable : IComparable<Compound>
    {
        readonly float m_featureValue;
        
        public InlineableFeatureComparable(float featureValue)
        {
            m_featureValue = featureValue;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public int CompareTo(Compound other)
        {
            if (m_featureValue == other.FeatureIndex) { return 0; }
            if (m_featureValue < other.FeatureIndex) { return -1; }
            return 1;
        }
    }

    public static void SpanBinarySearch()
    {
        var span = new Span<Compound>();

        //span.Sort(new InlineableFeatureValueComparer());

        float featureValueToFind = 1.234f;

        // Inlineable struct comparer
        var comparer = new InlineableFeatureValueComparer();
        // Less than ideal for compound, which is reason for comparable overload
        var compound = new Compound(){ FeatureValue = featureValueToFind };
        var index = span.BinarySearch(compound, comparer);

        // Inlineable struct comparable (easier to use for compounded type)
        var comparable = new InlineableFeatureComparable(featureValueToFind);
        index = span.BinarySearch(comparable);
    }

    public static void ReadOnlySpanBinarySearch()
    {
        ReadOnlySpan<Compound> span = new Span<Compound>();

        //span.Sort(new InlineableFeatureValueComparer());

        float featureValueToFind = 1.234f;

        // Inlineable struct comparer
        var comparer = new InlineableFeatureValueComparer();
        // Less than ideal for compound, which is reason for comparable overload
        var compound = new Compound(){ FeatureValue = featureValueToFind };
        var index = span.BinarySearch(compound, comparer);

        // Inlineable struct comparable (easier to use for compounded type)
        var comparable = new InlineableFeatureComparable(featureValueToFind);
        index = span.BinarySearch(comparable);
    }
}
```

The argumentation for adding this is:
 * To increase the efficiency of code doing binary searching and prevent people from reinventing the wheel.
 * Allow binary searching on contiguous memory of any kind.

### Open Questions
An important question regarding this proposal is whether the pattern with generic parameter `TComparer` (e.g. constrained to `where TComparer : IComparer<T>`) or `TComparable` (constrained to `where TComparable : IComparable<T>`) is a pattern that can be approved. This pattern allows for inlineable comparables/comparers at the cost of increased code size, if no value type comparables/comparers are used, there should be no difference. This pattern is also used in the proposal for `Sort` in https://github.com/dotnet/corefx/issues/15329, that has been approved.

Another open question is whether the overload taking `IComparable<T>` is necessary.

The API relies on being able to depend upon `System.Collections.Generic`, could this be an issue?

@karelz @jkotas @KrzysztofCwalina @jamesqo

### Updates
UPDATE 1: Add link to Sort and point on the pattern used.
UPDATE 2: Add IComparable<T> overloads for convenience as suggested by @jkotas
UPDATE 3: Combine all extensions into `SpanExtensions`.

### Existing Sort APIs
A non-exhaustive list of existing binary search APIs is given below for comparison.

#### `Array.BinarySearch` Static Methods
Found in [ref/System.Runtime.cs](https://github.com/dotnet/corefx/blob/master/src/System.Runtime/ref/System.Runtime.cs)

```csharp
public static int BinarySearch(System.Array array, int index, int length, object value) { throw null; }
public static int BinarySearch(System.Array array, int index, int length, object value, System.Collections.IComparer comparer) { throw null; }
public static int BinarySearch(System.Array array, object value) { throw null; }
public static int BinarySearch(System.Array array, object value, System.Collections.IComparer comparer) { throw null; }
public static int BinarySearch<T>(T[] array, T value) { throw null; }
public static int BinarySearch<T>(T[] array, T value, System.Collections.Generic.IComparer<T> comparer) { throw null; }
public static int BinarySearch<T>(T[] array, int index, int length, T value) { throw null; }
public static int BinarySearch<T>(T[] array, int index, int length, T value, System.Collections.Generic.IComparer<T> comparer) { throw null; }
```

#### `List<T>.BinarySearch` Member Methods
Found in [ref/System.Collections.cs](https://github.com/dotnet/corefx/blob/master/src/System.Collections/ref/System.Collections.cs)

```csharp
public partial class List<T> : System.Collections.Generic.ICollection<T>, System.Collections.Generic.IEnumerable<T>, System.Collections.Generic.IList<T>, System.Collections.Generic.IReadOnlyCollection<T>, System.Collections.Generic.IReadOnlyList<T>, System.Collections.ICollection, System.Collections.IEnumerable, System.Collections.IList
{
    public int BinarySearch(T item) { throw null; }
    public int BinarySearch(T item, System.Collections.Generic.IComparer<T> comparer) { throw null; }
    public int BinarySearch(int index, int count, T item, System.Collections.Generic.IComparer<T> comparer) { throw null; }
}
```

**Comment by jamesqo** [comment]
Shouldn't this go along with the `Sort` proposal? Binary search is one of the main reasons `Sort` is useful, IMO they should either be both accepted or both rejected.

**Comment by nietras** [comment]
No, I don't think they are necessarily co-dependent in both ways. If
`BinarySearch ` does not make it, it should not exclude `Sort`. However,
the other way around does make less sense, admittedly. But sorting has
other purposes than searching. Is there any benefit in combining them?

**Comment by jkotas** [comment]
Sort and BinarySearch are co-dependent in the sense that they should follow the same patterns. Either both should be on the `TComparer : IComparer<T>` plan; or both should be on the classic `IComparer<T>` plan.

**Comment by nietras** [comment]
Yes, definitely. The main thing is whether this pattern can be accepted for
Span. I can update the proposals with links to each other and some comments
about this. I don't want to necessarily merge the two since I think they
are both pretty long, and would like to keep them focused. If you'd rather
have them in one, let me know though.

**Comment by KrzysztofCwalina** [comment]
I think we should add Sort and BinarySearch. We are combining SpanExtensions and ReadOnlySpanExtensions into one type, and so the methods would go there. 

@nietras, are you just proposing this feature, or you are willing to submit a PR?

**Comment by jkotas** [comment]
@KrzysztofCwalina What do you think about the `TComparer : IComparer<T>` plan that allows the comparer to be inlined vs. the classic `IComparer<T>` plan that calls the comparer via indirection.

**Comment by KrzysztofCwalina** [comment]
I think we need to get it inlined. Otherwise the reusable routine would be usless for many scenarios.

**Comment by nietras** [comment]
@krzysztofcwalina for now just proposing, as I also say in https://github.com/dotnet/corefx/issues/15329#issuecomment-278292780 I would love to add, but not much time currently.

**Comment by jkotas** [comment]
> I think we need to get it inlined.

Agree. So I think we should have both flavors - both `TComparer : IComparer<T>` one and the classic `IComparer<T>` ones. The classic ones should be implemented as thin wrapper over `TComparer : IComparer<T>`.

**Comment by nietras** [comment]
> both TComparer : IComparer<T> one and the classic IComparer<T> one

I have added this to the proposal.

@karelz I think this is ready for API review, if no one objects.

**Comment by karelz** [comment]
@KrzysztofCwalina @jkotas if you agree, please change api-needs-work label to api-ready-for-review

**Comment by KrzysztofCwalina** [comment]
Before I mark it as ready for review, could we move all the extension methods to SpanExtensions?

**Comment by jamesqo** [comment]
Just noticed this, but @nietras' proposal also includes these methods

```cs
        public static int BinarySearch<T>(this ReadOnlySpan<T> span, IComparable<T> comparable) 
        { return BinarySearch<T, IComparable<T>>(span, comparable); }

        public static int BinarySearch<T, TComparable>(
            this ReadOnlySpan<T> span, TComparable comparable) 
            where TComparable : IComparable<T> 
        { throw null; }
```

Should it be `IComparer<T>` and not `IComparable<T>`? Is there a case for someone wanting to pass in a `TComparable : IComparable<T>` where TComparable != T?

**Comment by jkotas** [comment]
Some of the current extension methods are low-level - need access to other runtime details. We have the low-level ones on non-generic Span right and the pure algorithms on SpanExtensions right now: https://github.com/dotnet/corefx/blob/master/src/System.Memory/ref/System.Memory.cs#L75

We can get rid of the non-generic Span for the low-level ones if we add forwarding implementations instead.

**Comment by nietras** [comment]
> move all the extension methods to SpanExtensions?

Done.

> Is there a case for someone wanting to pass in a TComparable : IComparable<T> where TComparable != T?

Yes, I give an example of this in the proposal, see `UsageForCompound`. I have had many use cases like this, and that otherwise involves having to make a ctor on a type, that is only used for sorting, which makes it possible to make a type with incorrect state. 

Sorting compounded types on a property of this, and searching for it by this property alone is a much needed addition. And there is no apparent downside to this. My whole reason for making these proposals is to finally open these methods up for more involved use cases.

> can get rid of the non-generic Span

Yeah, I never understood why this non-generic `static class Span` existed, perhaps for the `string` slicing since these are not in fact extensions on `Span<T>` but rather `string`. But I definitely think these should be moved to `SpanExtensions` unless there is some reason for this I have not thought of.

**Comment by terrajobst** [comment]
Looks good as proposed.

Just a quick question: we have both, generic version for the comparer and a non-generic version. Are we sure that this doesn't result in funkiness with overload resolution where the developer has to explicitly specify the generic type?

**Comment by nietras** [comment]
> Looks good as proposed.

Great 😃 

> generic version for the comparer and a non-generic version. Are we sure that this doesn't result in funkiness with overload resolution

@terrajobst in https://github.com/nietras/dotnet-proposals/blob/master/span-binarysearch-src/Program.cs you could see code that compiles, and as far as I can tell there are no issues. The `IComparable<T>` is superfluous though, but seems like it would be nice to have for user discovery. You can clone and try it out if you like.

**Comment by jkotas** [comment]
This will make the API less efficient for small valuetypes like bytes or ints. I think we need a general rules  about use of `in` for new APIs.

**Comment by nietras** [comment]
> will make the API less efficient for small valuetypes like bytes or ints

@jkotas I thought the JIT could decide on whether to pass by reference or value based on type, i.e. type size, and choose the best strategy. Of course, that would not be the case for interop etc. If that is not the case, you are probably right...

**Comment by jkotas** [comment]
Yes, the JIT does that already on x64 and arm64 - this optimization is builtin into the default calling convention on all modern platforms.

**Comment by nietras** [comment]
> this optimization is builtin into the default calling convention on all modern platforms.

Yeah ok, then it doesn't make much sense to alter this. 👍

**Comment by nietras** [comment]
Given this, I am a little perplexed by the example given for using `in` in https://docs.microsoft.com/en-us/dotnet/csharp/reference-semantics-with-value-types:
```csharp
private static double CalculateDistance(in Point3D point1, in Point3D point2)
{
    double xDifference = point1.X - point2.X;
    double yDifference = point1.Y - point2.Y;
    double zDifference = point1.Z - point2.Z;

    return Math.Sqrt(xDifference * xDifference + yDifference * yDifference + zDifference * zDifference);
}
```
if the JIT already passes this by `ref`, what would the benefit be here in that case? Only thing is you cannot change the `in` parameters inside the method I assume... which you could if passed by value alone, but with no effect outside the method.

I could also ask whether `in` actually forces the JIT to pass by reference no matter what, as this is what I would assume, given the comment about this making the API less efficient for small types... but then I only see a point in using `in` if you really need a `ref` so you can do `ref` arithmetic or if you want to force using a `ref` no matter what since you know better than the JIT or are perhaps targetting x86.

**Comment by mikedn** [comment]
There seems to be a bit of confusion here. Yes, many calling conventions pass large values by reference anyway. But the by value semantics needs to be respected and most of the time that requires passing a reference to a copy of the original value. That prevents the callee from changing the original values and potential issues arising from the original value changing while the callee is using it (in the same or a separate thread).

So, there is value in passing large values by using `ref` (be it `readonly` or not). 

Unfortunately this applies only to large values, for anything else passing using `ref` is a potential deoptimization. Passing a local variable by reference implies taking its address and that tends to block compiler optimizations (at a minimum the variable needs to be stored in memory since you can't take the address of a register). Similarly, passing an array element by reference implies taking its address and that may requires a helper call to deal with the pesky array covariance issue.

**Comment by ahsonkhan** [comment]
Completed in https://github.com/dotnet/corefx/pull/24479
