### ISSUE TITLE
Delete desktop BinaryCompatibility settings from System.DirectoryServices

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#15810]
https://github.com/dotnet/corefx/blob/master/src/System.DirectoryServices/src/System/DirectoryServices/BinaryCompatibility.cs

This code does private reflection against desktop mscorlib and read full framework registry keys; none of which works well for .NET Core.

We should either delete it (preferred); or replace it with .NET Core compatible quirk if it is important to keep it.

As side-effect, this will also get rid of dependency of System.DirectoryServices on Microsoft.Win32.Registry.

**Comment by karelz** [comment]
cc @tquerec

**Comment by ViktorHofer** [comment]
BinaryCompatibility is being used in System.DirectoryServices.SortOption.cs:34: https://github.com/dotnet/corefx/blob/master/src/System.DirectoryServices/src/System/DirectoryServices/SortOption.cs#L34.

There are also a few comments in System.Diagnostics.Tracing.EventSource about BinaryCompatibility but I can't find any other references.

**Comment by ViktorHofer** [comment]
cc: @danmosemsft @weshaggard

**Comment by jkotas** [comment]
> So I guess we need to rewrite the >=netfx453 check 

You should just delete this check. We are not proactively maintaining bug-for-bug compatibility with desktop.

**Comment by danmosemsft** [comment]
Looks like the whole BinaryCompatibility can go then.
