### ISSUE TITLE
XML test libs included in coverage report

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/corefx#1582]
I looked at the coverage report and noticed that a bunch of XML test libs are included:

![image](https://cloud.githubusercontent.com/assets/1376924/7392228/d392bf42-ee86-11e4-8254-db6d5ee5e20f.png)

Those are dragging the overall coverage down and should be excluded from coverage.

/cc @krwq

**Comment by stephentoub** [comment]
Yes.  The next version of OpenCover will make it easy for us to exclude these test-only assemblies:
https://github.com/OpenCover/opencover/issues/295

**Comment by stephentoub** [comment]
(We could do this with naming exclusions today, but that would require us to overhaul the naming of all of these assemblies.  While that's arguably something we should do anyway, I didn't want to do it purely for the purposes of a more representative code coverage number.)

**Comment by akoeplinger** [comment]
Ah, didn't know opencover doesn't support this yet, let's wait for the next version then :)

**Comment by stephentoub** [comment]
:)
