### ISSUE TITLE
Code Coverage docs are outdated

### ISSUE THREAD

**Issue by fujiy** [dotnet/corefx#15829]
I'm trying to extract the coverage report for List class, but I couldn't follow the steps in https://github.com/dotnet/corefx/blob/master/Documentation/building/code-coverage.md#user-content-code-coverage-with-mscorlib-code

Some paths doesn't exist anymore and I'm not sure if the steps are still the same after https://github.com/dotnet/corefx/issues/15135 (Announcement: Engineering changes for corefx)

Thanks

**Comment by fujiy** [comment]
@arcs001

**Comment by stephentoub** [comment]
Yeah, looks like those docs are out-of-date.  You can follow the steps at:
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md#testing-with-private-coreclr-bits
to patch your corefx build with your locally built runtime, and then you should be able to see the coverage for List, e.g. if you follow those steps, and then in the System.Collections\tests directory do:
```msbuild /t:rebuildandtest /p:Coverage=true /p:CodeCoverageAssemblies="System.Private.CoreLib"```
cc: @danmosemsft

**Comment by fujiy** [comment]
Thanks @stephentoub. It worked.

@arcs001. I followed the following steps:

CoreFX
build -release
build-tests -release -skiptests

CoreCLR:
build release skiptests

Follow these instructions: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md#testing-with-private-coreclr-bits

Execute the following command at C:\Users\fepessot\Source\corefx\src\System.Collections\tests:

msbuild /t:rebuildandtest /p:Coverage=true /p:CodeCoverageAssemblies="System.Private.CoreLib" /p:ConfigurationGroup=Release
