### ISSUE TITLE
There is no test result generated under "System.Security.AccessControl.Tests.CommonSecurityDescriptor_CreateFromRawSecurityDescriptorTestC.../TestCreateFromRawSecurityDescriptor"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#15833]
On build 20170204.01, under test: System.Security.AccessControl.Tests.CommonSecurityDescriptor_CreateFromRawSecurityDescriptorTestC.../TestCreateFromRawSecurityDescriptor 

There isn't the test result generated.

Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170204.01/workItem/System.Security.AccessControl.Tests/analysis/xunit/System.Security.AccessControl.Tests.CommonSecurityDescriptor_CreateFromRawSecurityDescriptorTestC...~2FTestCreateFromRawSecurityDescriptor

**Comment by danmosemsft** [comment]
I think this is covered by https://github.com/dotnet/corefx/issues/15041
