### ISSUE TITLE
At what point is tools/testdotnetcli supposed to be populated

### ISSUE THREAD

**Issue by willdean** [dotnet/corefx#15845]
As a newcomer to the project, I am failing to get tests to build or run, because of failures to find dotnet.exe in tools/testdotnetcli.   (The directory doesn't exist at all)

`build.cmd` seems to run fine, but there is no "testdotnetcli" directory created in tools.

I am unclear what by process this directory is supposed to be built - `build-tests.cmd` seems to get off to a good start and does a load of compiling, but after a minute or so starts to fail with errors about tools/testdotnetcli missing.

To give me a clue about where to start to dig into this, could anyone point me to where testdotnetcli should be created (is it in build or in build-test, for example)?  There are umpteen references to "testdotnetcli" in issues here, but it mostly seems to in log outputs, and I can't find anything describing my problem.

At the point that build-tests starts to fail, its output looks like:

```
 System.Xml.RW.NameTable.Tests -> N:\will\corefx\bin\Windows_NT.AnyCPU.Debug\System.Xml.RW.NameTable.Tests\netcoreapp\
  System.Xml.RW.NameTable.Tests.dll
  System.Xml.RW.SubtreeReader.Tests -> N:\will\corefx\bin\Windows_NT.AnyCPU.Debug\System.Xml.RW.SubtreeReader.Tests\net
  coreapp\System.Xml.RW.SubtreeReader.Tests.dll
  System.Xml.RW.WrappedReader.Tests -> N:\will\corefx\bin\Windows_NT.AnyCPU.Debug\System.Xml.RW.WrappedReader.Tests\net
  coreapp\System.Xml.RW.WrappedReader.Tests.dll
  Using N:\will\corefx\Tools\testdotnetcli as the test runtime folder.
  Using N:\will\corefx\Tools\testdotnetcli as the test runtime folder.
  Using N:\will\corefx\Tools\testdotnetcli as the test runtime folder.
  Executing in N:\will\corefx\bin\AnyOS.AnyCPU.Debug\Microsoft.VisualBasic.Tests\netstandard\
  Running tests... Start time:  8:40:29.07
  Command(s):
  call N:\will\corefx\Tools\testdotnetcli\dotnet.exe xunit.console.netcore.exe Microsoft.VisualBasic.Tests.dll  -xml te
  stResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests  -notrait category=OuterLoop -notrait c
  ategory=failing -notrait category=nonwindowstests
  The system cannot find the path specified.
  Using N:\will\corefx\Tools\testdotnetcli as the test runtime folder.
  Finished running tests.  End time= 8:40:29.08, Exit code = 1
  Executing in N:\will\corefx\bin\AnyOS.AnyCPU.Debug\Microsoft.CSharp.Tests\netstandard\
  Executing in N:\will\corefx\bin\AnyOS.AnyCPU.Debug\System.AppContext.Tests\netstandard\
  Running tests... Start time:  8:40:29.07
  Command(s):
  Executing in N:\will\corefx\bin\AnyOS.AnyCPU.Debug\Microsoft.Win32.Primitives.Tests\netstandard\
  Using N:\will\corefx\Tools\testdotnetcli as the test runtime folder.
  Running tests... Start time:  8:40:29.09
  Executing in N:\will\corefx\bin\Windows_NT.AnyCPU.Debug\Common.Tests\netstandard\
  call N:\will\corefx\Tools\testdotnetcli\dotnet.exe xunit.console.netcore.exe System.AppContext.Tests.dll  -xml testRe
  sults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests  -notrait category=OuterLoop -notrait categ
  ory=failing -notrait category=nonwindowstests
  Running tests... Start time:  8:40:29.09
  Command(s):
  The system cannot find the path specified.
  call N:\will\corefx\Tools\testdotnetcli\dotnet.exe xunit.console.netcore.exe Common.Tests.dll  -xml testResults.xml -
  notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests  -notrait category=OuterLoop -notrait category=failing
   -notrait category=nonwindowstests
  Finished running tests.  End time= 8:40:29.08, Exit code = 1
  Command(s):
  The system cannot find the path specified.
  Using N:\will\corefx\Tools\testdotnetcli as the test runtime folder.
  Finished running tests.  End time= 8:40:29.09, Exit code = 1
  call N:\will\corefx\Tools\testdotnetcli\dotnet.exe xunit.console.netcore.exe Microsoft.CSharp.Tests.dll  -xml testRes
  ults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests  -notrait category=OuterLoop -notrait catego
  ry=failing -notrait category=nonwindowstests
  Running tests... Start time:  8:40:29.08
  Using N:\will\corefx\Tools\testdotnetcli as the test runtime folder.
  The system cannot find the path specified.
  Executing in N:\will\corefx\bin\AnyOS.AnyCPU.Debug\System.Buffers.Tests\netstandard\
  Running tests... Start time:  8:40:29.10
  Command(s):
N:\will\corefx\Tools\tests.targets(210,5): warning MSB3073: The command "N:\will\corefx\bin/AnyOS.AnyCPU.Debug/System.A
ppContext.Tests/netstandard//RunTests.cmd N:\will\corefx\Tools/testdotnetcli" exited with code 1. [N:\will\corefx\src\S
ystem.AppContext\tests\System.AppContext.Tests.csproj]
  Using N:\will\corefx\Tools\testdotnetcli as the test runtime folder.
  Finished running tests.  End time= 8:40:29.10, Exit code = 1
  call N:\will\corefx\Tools\testdotnetcli\dotnet.exe xunit.console.netcore.exe System.Buffers.Tests.dll  -xml testResul
  ts.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests  -notrait category=OuterLoop -notrait category

```

**Comment by mellinoe** [comment]
@willdean That folder should be initialized by the target in [this file](https://github.com/dotnet/corefx/blob/master/Tools-Override/ConstructSharedFx.targets). It should be run as part of `build-tests.cmd`, because it is imported in [src/tests.builds](https://github.com/dotnet/corefx/blob/master/src/tests.builds).

Can you clean out your Tools directory entirely and re-run the build? It's possible you've gotten into a bad state and cleaning everything out may help.

**Comment by willdean** [comment]
@mellinoe Thanks for that - removing \tools and rebuilding it hasn't made any difference - I'll investigate that target file and why it's not being run successfully.

**Comment by willdean** [comment]
OK, I think I might have got this going again now thanks to help from @mellinoe - I had to delete constructsharedfxcomplete.sem in \bin\obj in order to trigger the `ConstructTestingHost` to run again.

I have no idea how I arrived at this point of corruption, but this trap feels like somewhat of a bug, or at least it's rather unexpected behaviour for a built system.   If testdotnetcli is a dependency for most/all the tests, then the code which generates that dep should probably be testing for something at that location, rather than a semaphore file in another, broadly unrelated, directory.  

Is there something fundamental which stops constructsharedfxcomplete.sem being in the tools\testdotnetcli directory, and if so should I file an issue/pr (!) on that?

**Comment by mellinoe** [comment]
> I have no idea how I arrived at this point of corruption, but this trap feels like somewhat of a bug, or at least it's rather unexpected behaviour for a build system

Yes, it should never happen during normal situations. That semaphore file is created [at the end of the target I linked](https://github.com/dotnet/corefx/blob/master/Tools-Override/ConstructSharedFx.targets#L56), so if it exists, that means the test folder should already exist.

**Comment by willdean** [comment]
@mellinoe I think the issue is that if one has ill-advisedly 'cleaned up' the tools directory, most of it gets rebuilt for you automatically, but the testdotnetcli folder doesn't get rebuilt because its semaphore is in a different place.  I don't suppose it matters in the larger scheme of things though.

**Comment by mellinoe** [comment]
@willdean That's actually a good point. Generally I clean both the `bin` and `Tools` directories so I've probably dodged this issue, but it does seem broken. Personally I think we should move the whole "testdotnetcli" under the bin directory in the first place.

**Comment by willdean** [comment]
@mellinoe Wherever it goes, MHO is that the semaphore file (if that really is the best way to detect it) should be with it.
