### ISSUE TITLE
#if netstandard17 check in System.Collection.Tests are not being run

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#15849]
Steps to reproduce:
- `build.cmd`
- `build-tests.cmd`
- `cd src/System.Collections/tests`
- `msbuild /T:BuildAndTest`

E.g. change a test here (https://github.com/dotnet/corefx/blob/1d4d1d8b00f09a8198a4e402ad91b48a85a59036/src/System.Collections/tests/BitArray/BitArray_CtorTests.cs#L227) to:
```c#
        [Fact]
        public static void Clone_LongLength_Works()
        {
            BitArray bitArray = new BitArray(int.MaxValue - 30);
            BitArray clone = (BitArray)bitArray.Clone();

            Assert.Equal(bitArray.Length, clone.Length);
            throw new InvalidOperationException();        
        }
```

I'd expect an IOE to be thrown, menaing the test ran, but it didn't. Also, in CI coverage, branches aren't getting hit that these tests do.

Might be related to recent dev/eng changes

**Comment by karelz** [comment]
@mellinoe @weshaggard are they supposed to work with the new infra?

**Comment by weshaggard** [comment]
Currently our test builds/runs only run the netcoreapp configurations and so we aren't yet building and running the netstandard configurations. We have https://github.com/dotnet/corefx/issues/15667 tracking that.

**Comment by danmosemsft** [comment]
Ouch. I didn't realize (or had forgotten) this. Meantime is it reasonable to check in without #if netstandard17? The only effect being test may fail on desktop?

Also should we be replacing netstandard17 define with netstandard? I'm guessing not, since we will need to filter desktop tests later so they don't include "netstandard21" until they support it.

But presumably netstandard17 define should be replaced with netstandard20.

@joperezr

**Comment by weshaggard** [comment]
We are trying to move most things to the version-less TFM's which I think we can do for this case as well. 

We still need to make a decision of whether or not we want all concrete platforms (i.e. netcoreapp, netfx, uap, etc) to be the union of all the tests in a project including the netstandard tests that apply to that platform or if we want netstandard configuration to be mutually exclusive and just do the extra netstandard build and run on each concrete platform. Depending on which approach we decide there that will guide us in how we want to #ifdef these tests.

**Comment by danmosemsft** [comment]
Need an issue for the versionless define? that should be easy at least.

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/issues/16042

**Comment by jkotas** [comment]
I have just run the System.Runtime tests that are in the netstandard and thus not being run by default, and got a pile of failures - some of them looked like regressions.

Can we please get this fixed asap? We are running blind and accumulating dept.

What is the purpose the netstandard ifdefs and conditions anyway? It does not make sense to me now that we have netcoreapp. Can we just delete all of them?
