### ISSUE TITLE
Workflow on an individual library broken

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#15847]
If I make a change to src (e.g. src\System.Collections.Concurrent\src) and do "msbuild /t:rebuild", then switch to the tests and try to re-compile/run them with "msbuild /t:rebuildandtest", I get an error like:
```
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Ref
  erence assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058) ---> System.BadIma
  geFormatException: Cannot load a reference assembly for execution.
```
The only way I've found to recover is to do a full build.cmd/build-tests.cmd from the root.

cc: @weshaggard

**Comment by weshaggard** [comment]
I will take a look.

**Comment by weshaggard** [comment]
This is another instance of https://github.com/dotnet/corefx/issues/15744. I will spend some time to try and fix this today.

**Comment by stephentoub** [comment]
Thanks, Wes.
