### ISSUE TITLE
Ubuntu 16.04 outerloop debug - System.Diagnostics.Tests.ProcessWaitingTests.WaitChain failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#15844]
Failed test: System.Diagnostics.Tests.ProcessWaitingTests.WaitChain 
Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu16.04_debug/92/consoleText

Message:
~~~
System.Diagnostics.Tests.ProcessWaitingTests.WaitChain [FAIL]
        Assert.Equal() Failure
        Expected: 42
        Actual:   145
~~~

Stack Trace:
~~~
/mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu16.04_debug/src/System.Diagnostics.Process/tests/ProcessWaitingTests.cs(190,0): at System.Diagnostics.Tests.ProcessWaitingTests.WaitChain()
~~~

Configuration:
OuterLoop_Ubuntu16.04_debug (build#92)

**Comment by Jiayili1** [comment]
This issue is repro on InnerLoop_Fedora24_debug ([build#990](https://ci.dot.net/job/dotnet_corefx/job/master/job/fedora24_debug/990/consoleText)).

Message:
~~~
System.Diagnostics.Tests.ProcessWaitingTests.WaitChain [FAIL]
        Assert.Equal() Failure
        Expected: 42
        Actual:   145
~~~

Stack Trace:
~~~
 /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/src/System.Diagnostics.Process/tests/ProcessWaitingTests.cs(190,0): at System.Diagnostics.Tests.ProcessWaitingTests.WaitChain()
~~~

**Comment by danmosemsft** [comment]
@Priya91

**Comment by Jiayili1** [comment]
This issue is repro on InnerLoop_Fedora24_release (build#995), detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/fedora24_release/995/testReport/System.Diagnostics.Tests/ProcessWaitingTests/WaitChain/

**Comment by danmosemsft** [comment]
@Priya91 can we disable on Fedora?

**Comment by stephentoub** [comment]
The exit code suggests the process is crashing having received a SIGCHLD signal, which should not have that effect.

**Comment by danmosemsft** [comment]
@stephentoub how did you get from 145 to SIGCHLD? In the Linux headers I have, it's 17.

**Comment by stephentoub** [comment]
Subtract 128 from the exit code to get the signal number.

**Comment by Jiayili1** [comment]
The following test "System.Diagnostics.Tests.ProcessWaitingTests.SingleProcess_EnableRaisingEvents_CorrectExitCode(exitCode: 0) " failed with Xunit.Sdk.EqualException.

Failed on: OuterLoop_Fedora23_release ([build#118](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_fedora23_release/118/testReport/)), detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_fedora23_release/118/testReport/System.Diagnostics.Tests/ProcessWaitingTests/SingleProcess_EnableRaisingEvents_CorrectExitCode_exitCode__0_/

Message:
~~~
Assert.Equal() Failure\nExpected: 0\nActual: 145
~~~

Stack trace:
~~~
at System.Diagnostics.Tests.ProcessWaitingTests.<SingleProcess_EnableRaisingEvents_CorrectExitCode>d__6.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_release/src/System.Diagnostics.Process/tests/ProcessWaitingTests.cs:line 120 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
~~~

**Comment by danmosemsft** [comment]
@Priya91 this broke Fedora 24 again. Can we fix or disable on Fedora?

https://ci.dot.net/job/dotnet_corefx/job/master/job/fedora24_debug/lastCompletedBuild/testReport/System.Diagnostics.Tests/ProcessWaitingTests/SingleProcess_EnableRaisingEvents_CorrectExitCode_exitCode__0_/

**Comment by Priya91** [comment]
This tests seems to break linux builds, disabling for linux.

**Comment by Priya91** [comment]
@ianhays is helping out with process failures..

**Comment by ianhays** [comment]
Getting a fedora machine running now so I can repro these.

**Comment by ianhays** [comment]
I'm tracking this failure in https://github.com/dotnet/corefx/issues/16688. Please do not re-open this issue, but instead post any failures in that issue.

The RemoteExecutorConsoleApp isn't available on some fedora runs and it's causing this failure.
