### ISSUE TITLE
Code coverage not updating after modifying source files

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#15850]
Steps to reproduce:
- `build.cmd` / `build-tests.cmd`
- Open a source project and modify a source file
- `build.cmd`
- Navigate to the corresponding test project and run `msbuild /T:BuildAndTest /P:Coverage=true`

Observe that the underlying source file has changed, but the coverage hasn't.

See this screenshot
![repro](https://cloud.githubusercontent.com/assets/1275900/22647655/5e3251bc-eca5-11e6-9f86-c31e99107847.png)

This makes it pretty hard to add coverage targeted tests

**Comment by JonHanna** [comment]
How about if you `msbuild` the source project instead of `build.cmd`? I've been doing that just because it's quicker, and haven't had this problem.

**Comment by stephentoub** [comment]
@weshaggard, is this related to the other issues you're investigating?

**Comment by weshaggard** [comment]
@hughbe for your step 3 are you calling build.cmd from the root again or you just building the individual src library? And are you doing it after you modify source code of the project?

Just to call it out doing a BuildAndTest on a test project no longer causes the src library to build so it has to be built before you can expect changes to manifest in the test run. 

One potential approach here is to build the sln file from the command line which has the correct set of projects that are interesting for a library. (although from my testing earlier that doesn't support the BuildAndTest target, I might look into that if that is something that folks are interesting in doing).

>@weshaggard, is this related to the other issues you're investigating?

Based on what was said I don't think it is related but it could indirectly be related. The other issue I'm digging into is "Rebuild" isn't getting the correct references setup which in some cases corrupts the output and in other cases causes build breaks. I have it root caused but I'm still trying to figure out the best fix.

**Comment by stephentoub** [comment]
@hughbe, are you still seeing a problem here?

**Comment by hughbe** [comment]
This looks fixed. Thanks @stephentoub
