### ISSUE TITLE
HttpClient decodes encoded Url?

### ISSUE THREAD

**Issue by jooooel** [dotnet/corefx#15865]
I'm trying to figure out some inconsistencies in how `HttpClient` handles URLs.

I have the following test code:

```C#
public async Task TestHttpClient()
{
    var baseUrl = "https://api.twitter.com/1.1/search/tweets.json";
    //var query = "(cafe OR boulangerie)";
    var query = "(café OR boulangerie)";

    var url = baseUrl + $"?q={Uri.EscapeDataString(query)}";

    var httpClient = new HttpClient();
    var response = await httpClient.GetAsync(url);

    await response.Content.ReadAsStringAsync();
}
```

The code won't actually work, since we need authentication and other stuff for Twitter searches. But it demonstrates my problem.

The variable `url` will have the following value: `https://api.twitter.com/1.1/search/tweets.json?q=%28caf%C3%A9%20OR%20boulangerie%29`

However, looking at the request in Fiddler, I can see that what is actually sent is: `https://api.twitter.com/1.1/search/tweets.json?q=(caf%C3%A9%20OR%20boulangerie)`

So all of a sudden, the parentheses are no longer encoded. This matters in my case, because I use the encoded query string to calculate a signature that I use to authenticate against twitter. So my signature will have percent encoded parentheses and the request won't, so Twitter throws an error and tells me the authentication fails.

What is interesting is that if I send the query with a regular e instead of é then the parentheses are encoded in the request! Like this: `https://api.twitter.com/1.1/search/tweets.json?q=%28cafe%20OR%20boulangerie%29`

I suppose this is some kind of bug with `HttpClient`? Can I work around this somehow?

**Comment by JonHanna** [comment]
It certainly seems strange to decode (validly) the first and not the latter. I don't have much of an idea as to which, if either, is against the spec, but as a work-around would you be able to use:

```C#
string uriForAuth = new Uri("https://api.twitter.com/1.1/search/tweets.json?q=%28caf%C3%A9%20OR%20boulangerie%29").AbsoluteUri;
```

for your authentication stage? Creating a `Uri` and looking at the `AbsoluteUri` property has the same behaviour as you describe, so you'd be able to create a signature that matches the URI that will be used.

**Comment by jooooel** [comment]
@JonHanna Thank you! Works like a charm :)

**Comment by Priya91** [comment]
> Thank you! Works like a charm :)

The string with the unicode char is an IRI - Internationalized Resource Identifier. When getting converted to URI (Only US-ASCII chars), the following chars are not escaped:

```
1. Letters a through z and A through Z
2. Digits 0 through 9
3. Hyphen (-), underscore (_), period (.), exclamation point (!), tilde (~), asterisk (*), apostrophe('), parentheses ('(' and ')') and hash mark (#)
4. Semicolon (;), forward slash (/), question mark (?), colon (:), at sign (@), ampersand (&), equals sign (=), plus sign (+), dollar sign ($), comma (,), square brackets ('[' and ']'), and percent sign (%)
```

You can read about it in [RFC3987](https://www.ietf.org/rfc/rfc3987.txt)

It works as expected.
