### ISSUE TITLE
Resurrect CoreFX Validation on Nano

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/corefx#15884]
Needs to be enabled, at minimum, in CI. For completeness (as we do for supported platforms), it needs to be enabled in Helix as well.

**Comment by gkhanna79** [comment]
From @Priya91:

 - If you look at the run-tests.cmd, it is a simple for loop of the output test folder, invoking xunit on each folder. This folder structure has changed quite a lot depending on what platform-OS is built, and this script hasn’t been updated when the build infrastructure changed in corefx. 

- Nano is not being tested on Helix. Nano is only being tested in Jenkins CI, and as you can see, it’s been failing for the past few months. And it wasn’t a priority to get it fixed, there were multiple issues tracking that. #15280,  #9975, #7434, #7433

-> Update to latest Nano VMs

CC @karelz @Petermarcu @danmosemsft @Chrisboh @markwilkie

**Comment by stephentoub** [comment]
This is a dup of https://github.com/dotnet/corefx/issues/15280

**Comment by danmosemsft** [comment]
Dupe.
