### ISSUE TITLE
System.Reflection.MetadataReader does not handle extremely large string heaps properly

### ISSUE THREAD

**Issue by mjrousos** [dotnet/corefx#1588]
Unlike the user string heap, it's possible to have a managed assembly with a (non-user) string heap with tokens (indexes) greater than 3 bytes.

In such cases, the metadata reader fails to get strings (such as the assembly name, usually, since it tends to be towards the end of the table) because calls like AssemblyDefinition.GetName call into Block.PeekReference and StringHandle.FromIndex, both of which assert that string handles should have indexes no larger than 24 bits.

**Comment by mjrousos** [comment]
Even if I remove the checks that assert string tokens should only be 24-bits, things don't work right for these large string heap offsets because StringHandle automatically attaches a string token type when creating a handle from an index (even though I don't see the string token type when I look at the string heap in ildasm) and then, later, when the token type is removed when looking up the string, the token type is misinterpreted as a WinRT string (because of the extra bit in the high bits from the large index) and the wrong index is looked up.

In general, the StringHandle type seems to have assumptions about how string handles (not user string handles) are constructed that don't line up with what I'm seeing in ildasm when looking at an assembly with a very large number of strings.

**Comment by mjrousos** [comment]
This is tricky to fix because of the way it's baked into the metadata reader, but one option might be to add a new field to 'Handle' that stores the 'Heap type' that the token comes from. This new field would be used to store any 'token types' larger than UserString. Then, when getting a TokenType from a Handle, that field would be checked first and only if it indicated that the token came from a table would the current value & TokenTypeMask code path be used to determine the token type.

**Comment by twsouthwick** [comment]
This seems to be tracked by #1238

**Comment by mjrousos** [comment]
Ah, so it is. Thanks, Taylor. I looked through existing issues briefly, but didn't match that one based off of its title.

I'll close this since it's a dup.
