### ISSUE TITLE
Change "#if NET_NATIVE" to "#if uapaot" in S.P.DataContractSerialization 

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#15892]
We need make changes to the following compilation directives,

1.  Remove USE_REFEMIT as we do not use it.
2. Change NET_NATIVE to uapaot

**Comment by jkotas** [comment]
We will also want to have AOT friendly builds for Console CoreRT apps. They are not called uapaot. I do not think it is a good idea to use `#if uapaot` for AOT friendly build.

Unless you can come up with a better, I think that `NET_NATIVE` is just fine.

**Comment by karelz** [comment]
cc @weshaggard

**Comment by weshaggard** [comment]
We have been trying to root out all the NET_NATIVE defines (see https://github.com/dotnet/corefx/issues/5315) and update them to follow our guidelines https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/project-guidelines.md#define-naming-convention which are generally driven by the configuration they are unique to or a FEATURE if they are more tied to something not specific to a configuration. I didn't look too closely at the code in this case so I'm not sure which case it is but I would like to move away from NET_NATIVE.

**Comment by jkotas** [comment]
`FEATURE_FULL_AOT` ?

**Comment by weshaggard** [comment]
FEATURE_FULL_AOT would be fine if that is what best describes the code being ifdef'ed.

**Comment by shmao** [comment]
This was fixed by #16704
