### ISSUE TITLE
Proposal: Protobuild for managing cross-platform builds

### ISSUE THREAD

**Issue by hach-que** [dotnet/corefx#159]
With .NET Core intending to support multiple platforms in the near future, there will need to be some way of managing cross-platform code for the core libraries.  I’d like to propose the usage of Protobuild for this purpose.  (Disclosure: I’m the author of Protobuild)

[Protobuild](http://protobuild.org/) is a cross-platform project generation tool.  It works by taking a set of project definition files, and produces C# projects suitable for targeting different platforms, which can then be built with MSBuild for producing platform-specific assemblies.  It supports changing the behaviour of code with #ifdef constructs, or by including and excluding files from a project based on their platform.

Protobuild itself requires no installation and resides as a single 124kb executable at the root of the repository.  To generate projects, users can double-click on the executable, or on Mac and Linux run “mono Protobuild.exe”.

It is currently most prominently used by MonoGame, which uses it to manage targeting 10 or so different platforms, along with the different project configurations they each require.  Examples of MonoGame’s project definitions are [the cross-platform Pipeline tool](https://github.com/mono/MonoGame/blob/develop/Build/Projects/Pipeline.definition), [the MonoGame library itself](https://github.com/mono/MonoGame/blob/develop/Build/Projects/MonoGame.Framework.definition) and [the references it has on external libraries](https://github.com/mono/MonoGame/blob/develop/Build/Projects/FrameworkReferences.definition).

**Comment by ellismg** [comment]
Thus far our strategy is to use CMake in cases where we need to build native components cross platform and MSBuild for our managed components.  Thus far we've taken an approach of hand authoring MSbuild files which use the OS property for cases where we have to something platform specific.  If we end up outgrowing this approach, we'll definitely look at Protobuild (what've you've come up with looks pretty cool!), but for now we are happy with what we have.
