### ISSUE TITLE
Extend DateTime/TimeSpan with chronic-like functionality

### ISSUE THREAD

**Issue by SirCmpwn** [dotnet/corefx#1590]
Context: [Chronic](https://github.com/mojombo/chronic) is a Ruby library for parsing date/times in natural language.

It's currently possible with .NET to parse a DateTime that's in a specific format, but not a DateTime like "in three hours" or "next Saturday at half past noon".

## Rationale and Usage

Parsing natural language time strings is a difficult task that is well beyond the scope of most projects that leverage .NET. However, it is a useful task that enables humans to convey times to computers more easily. This makes it a good candidate for inclusion in the standard library - difficult and out of scope for the consumers of the standard library. This is useful for things like calendar software, particularly when combined with speech-to-text software.

The usage for this feature may look something like this, nice and simple:

```csharp
DateTime timeA = DateTime.ParseNatural("may 1st 2015");
DateTime timeB = DateTime.ParseNatural("tuesday", past=true);
DateTime timeC = DateTime.ParseNatural("tuesday", DateTime.Now.AddDays(10));
```

## Proposed API

```csharp
public struct DateTime
{
    // ...

    public static DateTime ParseNatural(string phrase, bool past=false);
    public static DateTime ParseNatural(string phrase, DateTime now, bool past=false);
    public static DateTime ParseNatural(string phrase, CultureInfo culture, bool past=false);
    public static DateTime ParseNatural(string phrase, DateTime now, CultureInfo culture, bool past=false);

    // ...
}
```

## Details

* There is an open source (MIT licensed) port of Chronic to .NET [here](https://github.com/robertwilczynski/nChronic). We may be able to include it wholesale, use parts of its code, or simply draw inspiration from it.
* The inclusion of locale support may substantially increase the complexity of this feature.
* There is no support described here for recurring events ("every other friday") or a range of time ("noon till six"). This is probably out of scope but a particularly enthusiastic contributor may feel otherwise.

**Comment by mj1856** [comment]
I'd like to offer an opinion.

I agree that natural language parsing can be a fun and useful feature for an application, but I disagree that it should be part of the core framework.  There are other items related to date/time such as #700, (being worked on independently [here](https://github.com/mj1856/corefx-dateandtime)) that would fit the framework, but natural language parsing is not one of those type of things (IMHO).

It's awesome that Chronic is ported to .NET, and I'm sure those that want this functionality could use that library without any changes to the framework.  Adding it to the framework doesn't light up any functionality for the framework itself, or things that depend only on the framework.

**Comment by eatdrinksleepcode** [comment]
"This makes it a good candidate for inclusion in the standard library - difficult and out of scope for the consumers of the standard library."

While this is true, there is a more important criterion for inclusion in the standard library: very broad applicability. I don't believe that this feature meets that bar. Most applications don't need natural language date parsing.

**Comment by ellismg** [comment]
From experience, DateTime parsing is something that is always fragile for us.  The interaction of culture data with our fuzzy logic can produce surprising results and trying to fix issues in the logic often ends up breaking other cases.  Expanding the set of valid inputs to something even more free form feels like something that is going to be very hard to do well.  If we only had to support English, maybe it would be a tractable problem, but if we did this we would need to include other locales to make it feel like a first class member of the core.
 
It's great that there's community driven projects out there that want to build this sorts of things, but this really feels like something that's out of scope for .NET Core.

@tarekgh Can make the final call, but my vote would be that we don't pursue this.  Interested parties can pick up something like Chronic.

**Comment by tarekgh** [comment]
I agree with @ellismg, @eatdrinksleepcode  and @mj1856 regarding that. as Matt Ellis mentioned the parsing is always fragile and never satisfied all people especially when used with different cultures. I am pretty sure there will be issues with other cultures which will be hard to support.

As suggested in this thread, it is better to have this functionality in a stand alone library in nuget but I don't think this should be part of the framework core. 

by that I am going to close this issue and let's know if you have any question about it. we still can support you if you decide to implement this in its own library. 

Thanks for brining this issue

.
