### ISSUE TITLE
Dns.GetHostEntry("IPv6_string") does not work anymore in Linux environment.

### ISSUE THREAD

**Issue by geleems** [dotnet/corefx#15926]
Now `IPHostEntry hostEntry = Dns.GetHostEntry("IPv6_address");` failed, and does not work anymore in Linux, while the same code works perfectly in Windows.
```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : No such device or address
Stack Trace:
/home/REDMOND/gelee/Projects/CoreFx/src/System.Net.NameResolution/src/System/Net/DNS.cs(178,0): at System.Net.Dns.InternalGetHostByAddress(IPAddress address, Boolean includeIPv6)
/home/REDMOND/gelee/Projects/CoreFx/src/System.Net.NameResolution/src/System/Net/DNS.cs(470,0): at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
```
@saurabh500 @corivera

**Comment by Priya91** [comment]
@geleems It is probably because your device does not have reverse DNS lookup configured for your IP. You can check if you're able to resolve the ipaddress using the below command on the terminal. And copy the output here.

```host <ip-address>```

**Comment by geleems** [comment]
@Priya91 This is the result of the command:
```
a.7.f.9.a.8.0.c.4.f.c.f.5.b.4.6.5.2.0.1.0.f.0.0.8.9.8.4.1.0.0.2.ip6.arpa domain name pointer gelee-vm-win10.redmond.corp.microsoft.com.
```
It seems it began to work from yesterday again, I did not change any setting though.
I think it is more about machine configuration issue. Thanks!

**Comment by Priya91** [comment]
> It seems it began to work from yesterday again

Must be that your network administrator made changes. Thanks for verifying.
