### ISSUE TITLE
Add mixed Complex/double arithmetic operators to Complex

### ISSUE THREAD

**Issue by dcwuser** [dotnet/corefx#15927]
There are implicit casts from double -> Complex, so it's currently possible to write e.g. 2.5 * z for Complex z,  but in addition to the cast, this costs 6 flops for a Complex * Complex multiply, while it's possible to implement a double * Complex multiply directly in 2 flops.

For a single multiplication, a 4 flop additional cost is trivial. But in large operations on Complex matrices, where Complex arithmetic operations occur in rapid succession within tight O(N^3) loops, this can cut the overall time for a Complex matrix operation from 3 hours to 1 hour.

The operations to implement are as follows:

```C#
public struct Complex {

    // Mixed double/Complex multiplication 6 flops -> 2 flops
    public static Complex operator* (double a, Complex b)
    public static Complex operator* (Complex a, double b)

    // Complex / double division 9 flops -> 2 flops
    // This is the largest efficiency gain.
    public static Complex operator/ (Complex a, double b)

    // double / Complex division  9 flops -> 6 flops
    // This is the least worthwhile and could be skipped.
    public static Complex operator/ (double a, Complex b)

    // Mixed double/Complex addition 2 flops -> 1 flop
    public static Complex operator+ (double a, Complex b)
    public static Complex operator+ (Complex a, double b)

    // Mixed double/Complex subtraction 2 flops -> 1 flop
    public static Complex operator- (double a, Complex b)
    public static Complex operator- (Complex a, double b)

    // Also 7- 8 static helper methods Multiply, Divide, Add, Subtract
    public static Complex Add (double left, Complex right)
    public static Complex Add(Complex left, double right)
    public static Complex Subtract(double left, Complex right)
    public static Complex Subtract(Complex left, double right)
    public static Complex Multiply(double left, Complex right)
    public static Complex Multiply(Complex left, double right)
    public static Complex Divide(Complex left, double right)
}
```

The implementations are straightforward, with the the exception of double / Complex, which faces the same cancellation and overflow issues as Complex / Complex.

**Comment by jamesqo** [comment]
Sounds like a good idea. I noticed this myself when going over the Complex source. We would have to be careful to ensure behavior stays the same though, since existing code will start using it when compiled against the new API surface.

**Comment by dcwuser** [comment]
@jamesqo: Agreed. One good way to address this concern would be to add tests not just that mixed arithmetic gives right answers, but also that those answers are exactly the same as when double input is upcast to Complex. I am cautiously optimistic that this will work itself out, because although floating point arithmetic suffers from non-associativity and CPU dependency and other such "jitter" for arbitrary values, when one of the values is zero it all becomes much more strictly predictable.

**Comment by dcwuser** [comment]
@danmosemsft, @mellinoe: What do I need to do to move this proposal forward? This seems pretty uncontroversial, there are no decisions to make about API naming or placement, and the risks are clearly identified and controllable.

**Comment by mellinoe** [comment]
Sorry for the delay. I think this sounds reasonable.

@weshaggard @ericstj Are there any other compatibility concerns we have when adding methods like this? Code which previously bound to the (Complex, Complex) overloads (through an implicit conversion) will now bind to these new, more specific overloads. Are we okay with this as long as the results are identical?

**Comment by ericstj** [comment]
Identical results and independently target-able are requirements.  We've gotten ourselves into trouble before when adding overloads and automatically depending on the new API, but that was more of a problem with patching and desktop.  Given we ship everything here as a complete set for .NETCoreApp I think we're OK adding them.

**Comment by weshaggard** [comment]
>but that was more of a problem with patching and desktop

We have to make the assumption these APIs will also come to desktop so we cannot make changes where that will be incompatible either. However I think we are also fine on that front with these changes, assuming the functionality is identical.

**Comment by dcwuser** [comment]
I have code that shows this works and passes consistency tests in my branch at https://github.com/dcwuser/corefx/tree/complexoverloads1. I won't submit as a PR yet, first because it hasn't been through API approval and second because I'm not convinced my test organization is right. But anyone who wants a basic picture is welcome to look.

**Comment by mellinoe** [comment]
@dcwuser That looks reasonable to me, if a little complicated. I'll mark this as "ready for review" and we can review that more in depth later.

**Comment by weshaggard** [comment]
ApiReview: Aproved

- Looks good and we believe compat will be OK but please ensure we have good test coverage to ensure they produce identical answers.
- Please include `double / Complex` for completeness.

**Comment by danmosemsft** [comment]
@dcwuser would you like me to assign this to you?

**Comment by dcwuser** [comment]
@danmosemsft: Yes

**Comment by kant2002** [comment]
@karelz please assign me to this issue

**Comment by danmosemsft** [comment]
@dcwuser can provide guidance on this probably..
