### ISSUE TITLE
Test failures in System.ComponentModel.Tests.CultureInfoConverterTest.ConvertFrom_String and System.ComponentModel.Tests.CultureInfoConverterTest.ConvertFrom_String_InvalidCulture

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#15931]
These tests are currently disabled with label [ActiveIssue(11611)](https://github.com/dotnet/corefx/issues/11611), although the issue has been closed. If you enable the tests, they would still fail on Linux.

```
System.ComponentModel.Tests.CultureInfoConverterTest.ConvertFrom_String [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentException)
        Actual:   (No exception was thrown)
        Stack Trace:
           /home/sekho/Desktop/corefx/src/System.ComponentModel.TypeConverter/tests/CultureInfoConverterTests.cs(61,0): at System.ComponentModel.Tests.CultureInfoConverterTest.ConvertFrom_String()
     System.ComponentModel.Tests.CultureInfoConverterTest.ConvertFrom_String_InvalidCulture [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentException)
        Actual:   (No exception was thrown)
        Stack Trace:
           /home/sekho/Desktop/corefx/src/System.ComponentModel.TypeConverter/tests/CultureInfoConverterTests.cs(81,0): at System.ComponentModel.Tests.CultureInfoConverterTest.ConvertFrom_String_InvalidCulture()
  Finished:    System.ComponentModel.TypeConverter.Tests
```

**Comment by danmosemsft** [comment]
@safern

**Comment by safern** [comment]
@tarekgh I see you addressed issue #11611 in PRs dotnet/coreclr#7713 and #12971. Probably you missed this disabled test when enabling the other ones disabled by that issue. Could you please take a look?

**Comment by tarekgh** [comment]
@safern 
I had no idea about these tests and never was in my radar. I am not sure even if these failing related to my changes. looks @AlexGhiondea disabled the tests till we support the missing globalization properties and I believe we never run these tests on Linux before.

I'll try to take a look and let you know.

**Comment by safern** [comment]
Thanks @tarekgh let me know if you can find something so if not I can take a look or wait to see if @AlexGhiondea knows something about this!

**Comment by AlexGhiondea** [comment]
I remember disabling these a long time ago ... since the ComponentModel was brought up before we had full support for globalization.
