### ISSUE TITLE
Figure out a strategy for generating test shared framework deps file

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#15937]
https://github.com/weshaggard/corefx/blob/c67cb8a80fe2449e59e023ed481e977ffe8ced8b/src/src.builds#L20

Today we build the deps json file as a post step to building all the src projects and we rely on having a previous deps.json file to generate the new one. Maintaining the deps.json is likely going to be error prone so ideally we would eliminate it completely but if we cannot we should at least look into generating it from scratch and having it be updated whenever we binplace something to the shared framework directory.

cc @karajas 

@gkhanna79 Do we have any plans to enable a scenario where we can use a shared framework without requiring a deps.json file?

**Comment by gkhanna79** [comment]
Not without changing the entire appmodel @weshaggard. The portable app activation relies on deps.json to be present for the host to consume.

**Comment by karajas** [comment]
We can get rid of the current way we generate the deps.json file. The only reason I was using it was to pull the versions out of the assemblies to fake a package version. In the netstandard2.0 since everything is flat we can probably just list a fake Microsoft.NETCore.App package version and things should work.

**Comment by weshaggard** [comment]
@karajas we still need to list all the libraries in the deps file.

**Comment by karajas** [comment]
is there anything besides the standard that tells us what's in the shared framework and what's not?

**Comment by weshaggard** [comment]
For the purposes of our testing work here everything we build in corefx is in the shared framework.

**Comment by wtgodbe** [comment]
Looks like we don't do this anymore, closing
