### ISSUE TITLE
SerialPort in core doesn't support certain char encodings

### ISSUE THREAD

**Issue by willdean** [dotnet/corefx#15949]
Posting this to allow us to ActiveIssue some encoding tests - we're failing on:

* Custom encoding 1047
* System.Text.Encoding.GetEncoding(50220) (Japanese JIS)
* System.Text.Encoding.GetEncoding(57006) (ISCIIAssemese)

I'm not clear if this is a Core or a SerialPort limitation.

**Comment by justinvp** [comment]
What are the failures? Note that the code pages have been moved to a separate component (System.Text.Encoding.CodePages) for Core...

The following code needs to run before `Encoding.GetEncoding` will be able to find them:

```c#
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
```

**Comment by willdean** [comment]
@justinvp Thanks for this - the RegisterProvider fixes the two GetEncoding issues.

I'll debug the other one a bit further and see what's going on, I hadn't appreciated it was different.  It's creating an instance of `System.Text.Encoding` with code page 1047 - the creation's OK but something chokes later.

**Comment by willdean** [comment]
OK, I've got a grip on this now, and I'm afraid it's one for @JeremyKuhne again, sorry.

The test `Encoding.Encoding_Custom` is failing because it's expecting that a custom encoding will be rejected with an `ArgumentException`, but instead what happens is that the custom encoding is accepted but then fails later (it was never expecting to be used).

This is because of a change in 2a4846c to the way encodings are enforced in the `Encoding` property - I'm not really clear on why this was made, so I don't want to change it back - I guess it's do so with the fact that they don't all originate in the same assembly now, so that test is flawed.

There are no functional tests within the rest of the suite for custom encodings, so I think we should be careful about permitting them.

**Comment by JeremyKuhne** [comment]
Yeah, the block wasn't possible as it was. Didn't think it was that important to try and match the behavior- would rather have it as a comment that it is untested/unsupported.

I'm open to adding back the block if we have strong consensus for it. In any case we should probably open an issue so someone can take this on if they want (validating custom encoding).

**Comment by willdean** [comment]
I am inclined to think that nobody in human history has ever passed a custom code page to a SerialPort object anyway, so it's probably all completely irrelevant.  Should I Ieave the test with an ActiveIssue on it, or should I just delete it?

**Comment by JeremyKuhne** [comment]
Delete it is my call.
