### ISSUE TITLE
[Bug] Double-evaluation of selector in SelectMany

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#15942]
I found out my changes from https://github.com/dotnet/corefx/pull/14675 introduced a double-evaluation of a selector in `SelectMany.ToArray`: https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/SelectMany.cs#L245 This will be fixed shortly in an upcoming PR, but I am opening a tracking issue just in case I forget or that PR gets closed.

**Comment by stephentoub** [comment]
Thanks, @jamesqo. I thought we'd added tests to help avoid such bugs... I guessed we missed some cases. It'd be great to get a more thorough set for this. cc: @JonHanna

**Comment by JonHanna** [comment]
You put forward the idea of having tests that both guarded against double evaluation of enumerables and against changes to how often delegates where called. At the time you said that I was already working on the first part of that, and submitted a PR saying I'd look at the other part "soon". Soon has yet to happen.

**Comment by stephentoub** [comment]
Ah, gotcha, I misremembered. Thanks!

**Comment by JonHanna** [comment]
Or you remembered my saying "soon" too well. It's definitely something we should have, but ensuring it has coverage would be a bit tricky. Maybe a trait could help there.
