### ISSUE TITLE
System.IO.IsolatedStorage shouldn't depend on AccessControl for UAP

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#15968]
Today IsolatedStorage depends on two AccessControl libraries for netcoreapp and uap. While this is ok in netcoreapp, AccessControl isn't available on UAP so we should break that dependency and create a new uap specific configuration of IsolatedStorage that doesn't depend on them.

cc: @JeremyKuhne

**Comment by JeremyKuhne** [comment]
@weshaggard We have an AccessControl for Unix that throws PNSE. Would it make sense to do the same for UAP?

**Comment by weshaggard** [comment]
Similar to https://github.com/dotnet/corefx/issues/15337 I would prefer we break this dependency for NETCoreApp and UAP.

**Comment by JeremyKuhne** [comment]
Ok, thanks

**Comment by joperezr** [comment]
Hey @JeremyKuhne I believe this is done right?

**Comment by JeremyKuhne** [comment]
@joperezr Yeah, you did it by creating a UAP build and conditioning out the library, which wasn't actually used for UAP.

**Comment by joperezr** [comment]
I see, closing this then.
