### ISSUE TITLE
Running CoreFx tests from VS is broken

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#1597]
I’m using TestDriven.NET.
1)  Right-click on a test method and selecting “Run Test” works well for System.Reflection.Metadata tests. Good.
2)  Right-click on a test class or a test file reports an error in output:
The target type doesn't contain tests from a known test framework or a 'Main' method.
3)  Right-click on a test method and selecting “Test with … Debugger” freezes VS.

Test Explorer doesn’t show any tests even after full solution build.

Trying to set the test project as a startup project and F5 it.

Error:
“The working directory does not exist: 'C:\FX0\bin\tests\Windows_NT.AnyCPU.Debug\System.Reflection.Metadata.Tests\dnxcore50'.”

Seems like building the entire CoreFx repo fixes this issue (although I’m not quite sure). In any case I don’t want to build the entire repo to run a single test.

Couldn’t get F5 work from Dev12 VS, yet the project is Dev12 VS. With Dev14 I was able to debug the test.

**Comment by krwq** [comment]
I think it might be related: https://github.com/dotnet/corefx/issues/1460

**Comment by tmat** [comment]
@krwq Yes, seems like the F5 scenario issues are related to #1460.

Another problem is that the test references are populated by some magic from packages.config file and TestDriven.NET can't find the xunit reference.

**Comment by mellinoe** [comment]
I think this just isn't implemented yet. We have a sort of F5 hack in place, but building the project (or hitting F5) doesn't actually produce/construct the directory structure for tests. All of that work is done by our test targets, which aren't involved there. And I don't think debugging CoreCLR is going to be supported from Dev12 at all; only Dev14, unfortunately.

> Seems like building the entire CoreFx repo fixes this issue (although I’m not quite sure)

I think it's because the full build produces the test directories and runs the tests in all of them, so when you open in VS and hit F5, the test directory already exists. I would bet that re-building the product/tests doesn't actually re-populate the test directory, only the binaries directory.

I don't know how TestDriven.NET works, but I highly doubt it will just work given the nature of our projects and product.

**Comment by mellinoe** [comment]
In my opinion, we should invest in a VS test explorer plugin. That would probably provide the best experience in VS, and be closer to what people are used to. We have an internal one, but it may need to be modified heavily (and probably stripped down) to be useful for CoreFx.

**Comment by tmat** [comment]
@mellinoe Investing into test infrastructure is critical. I don't see how anybody can be productive writing and debugging unit tests with the current setup.

**Comment by tmat** [comment]
@krwq BTW, using F5 on a test project to debug a particular test is far from ideal. F5 runs all the tests, so it takes long, exceptions from other tests how up, breakpoints are hit by other tests, etc.

**Comment by krwq** [comment]
To debug one test I currently add this to a test I'm investigating:
[Trait("myunique", "test")]
and then change the startup command to:
`corerun .... mytest.dll -trait myunique=test`

Also you can build a single test using:
msbuild /t:BuildAndTest csprojfile.csproj

It is kind of annoying though and I agree we should invest time to be able to run from VS.

**Comment by stephentoub** [comment]
@nguerrera, does your buildtools fix address this as well such that this can be closed once we get updated buildtools in corefx?

**Comment by nguerrera** [comment]
@stephentoub It addresses the F5 part, but I think @tmat was also asking for debugging individual tests, test explorer suport, etc. etc. i.e. proper VS integration. I badly want that too. :) I think @FiveTimesTheFun looked into it at one point. I don't know if we have another issue tracking that. If not, I'd leave this open.

**Comment by tmat** [comment]
@stephentoub @nguerrera We are working on it and are close to having something that works at least to some extent. You'll be able to run and debug individual tests or a selection of tests from VS. For now we are able to host the tests run from VS on Desktop CLR. We figured out how to make TestDriven.NET work that way. We don't have a solution for running tests from VS on CoreCLR yet since TestDriven.NET doesn't support it. We'd need a different test runner.

**Comment by tmat** [comment]
@stephentoub @nguerrera  In other words -- we are going to have a solution that mimics the workaround I made here earlier but without the need of extra solution checked into the source tree. You'll be able to run tests form command line on CoreCLR and from VS on Desktop FX.

**Comment by stephentoub** [comment]
Great.  Thanks for the updates.  Will leave this open.

**Comment by nguerrera** [comment]
Keep in mind that for many corefx libraries, running on desktop is problematic: will unify to GAC and not see your changes or will potentially lead to duplicated types, etc. The latter would be addressable once we have the full package build including desktop facades in this repo. The former would require updating the machine-wide desktop CLR to get all tests to pass as new API are added, etc.

**Comment by tmat** [comment]
@nguerrera I know it's not ideal, but at least something (e.g. Metadata, Immutable, etc) is gonna work. I'm building a separate test runner that uses CoreCLR. But for us it's not a priority, so I can't spend to much time on it. I'd be happy to share :)

**Comment by nguerrera** [comment]
Agreed. I mainly wanted to set expectations for folks reading this. Please do share any progress on CoreCLR runner. Perhaps some other folks on our team or in the community can help. :)

**Comment by karelz** [comment]
We support running tests from VS. We may still need to file issues to run specific test from VS -- it should go to buildtools repo (it's common for all repos, not CoreFX specific).
