### ISSUE TITLE
Issue with system.net.networkinformation.ping.send() with a low timeout

### ISSUE THREAD

**Issue by happysysadm** [dotnet/corefx#15989]
It appears as when I use .NET [system.net.networkinformation.ping.send()](https://github.com/dotnet/corefx/blob/master/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.Windows.cs) function with a low timeout, like less than 100ms, it will return an answer even if the time is higher than the timeout I have set:

```
[System.Net.NetworkInformation.Ping]::new().Send('www.google.co.uk',1)
Status : Success
Address : 2a00:1450:400b:c00::5e
RoundtripTime : 58
Options :
Buffer : {97, 98, 99, 100...}
```

Is the iphelper API able to handle low ping thresholds correctly when called from IcmpSendEcho2?

**Comment by karelz** [comment]
That sounds more like a question about the underlying platform (Windows) API than about .NET, right?

**Comment by happysysadm** [comment]
@karelz I am unsure of where the problem is. But as a matter of fact when I use that .NET method I don't get what I would expect. You reckon I am approaching it wrong? Thanks

**Comment by karelz** [comment]
I am not questioning your approach - just reacting to what you wrote: You noticed .NET Core uses Windows API, so the limitations are likely coming from it ...
Did you get chance to test the Windows API directly (PInvoke or C++ app)?

**Comment by happysysadm** [comment]
@karelz thanks for your feedback. I haven't had the occasion to test anything else apart from trying to pinging with the -w option (which is used to set the timeout in milliseconds to wait for each reply) and got the same behavior:

```
ping srv01 -w 1

Pinging srv01.st.com [10.93.30.114] with 32 bytes of data:

Reply from 10.93.30.114: bytes=32 time=200ms TTL=118
Reply from 10.93.30.114: bytes=32 time=190ms TTL=118
Reply from 10.93.30.114: bytes=32 time=197ms TTL=118
Reply from 10.93.30.114: bytes=32 time=190ms TTL=118

Ping statistics for 10.93.30.114:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 190ms, Maximum = 200ms, Average = 194ms
```

Since the problem resides probably in the underlying API, does anybody know how to open an issue in the right place?

**Comment by karelz** [comment]
OK, closing here then.
I don't know if Windows team has any direct feedback on API bugs and feature requests. You can use Microsoft Support (paid channel).
