### ISSUE TITLE
[Proposal] Stack.Swap to simultaneously pop/push an element

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#15982]
## Description

I have found it's often necessary to replace the top element of a stack with a new one. Currently, that's done like this:

```cs
T oldElement = _stack.Pop();
_stack.Push(newElement);
```

This issue proposes adding a new API, `Swap`, that pops and pushes in one go:

```cs
T oldElement = _stack.Swap(newElement);
```

## Proposal

```cs
namespace System.Collections.Generic
{
    public class Stack<T>
    {
        public T Swap(T newItem);
    }
}
```

## Remarks

- In addition to lowering LOC, this API would likely increase performance when replacing Pop/Push because there would be fewer method calls and the elimination of [some redundant checks/writes](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/Stack.cs#L249-L254) to the stack (e.g. `_size` wouldn't have to be changed).

- Alternative names I could think of: `Exchange`, `ReplaceTop`, `ChangeTop`, `SwapTop`

- If people think this is a good idea, I will include an API for `ImmutableStack<T>` in this proposal too.

**Comment by stephentoub** [comment]
I'm personally not seeing enough value here.  For situations where I have needed something along these lines, the new value I'm pushing is very often based on the value that's popped (or more than one), which this wouldn't support.  And even if there are scenarios that would benefit from this, I think there's value in having a simple set of composable operations (e.g. Push and Pop) rather than one or more combinations of them, unless there's a *really* compelling performance argument, i.e. there's a meaningful scenario this significantly improves (not just a microbenchmark).

**Comment by jamesqo** [comment]
> I'm personally not seeing enough value here. For situations where I have needed something along these lines, the new value I'm pushing is very often based on the value that's popped (or more than one), which this wouldn't support.

That's a good point. I was about to point out that `Peek` would let you do this, e.g. `stack.Swap(1 + stack.Peek())` but at that point it becomes no more convenient than writing `stack.Push(1 + stack.Pop())`. I guess what I've proposed would only benefit people not using the old value in the replacement value, and having to put `Pop` on a separate line.

> And even if there are scenarios that would benefit from this, I think there's value in having a simple set of composable operations (e.g. Push and Pop) rather than one or more combinations of them that would need to be named, explained, documented, etc., unless there's a really compelling performance argument, i.e. there's a meaningful scenario this significantly improves (not just a microbenchmark).

OK, fair enough. This was more of a convenience method for me, actually, than a perf-motivated proposal.
