### ISSUE TITLE
Threadpool Min/Max ThreadCount Configuration

### ISSUE THREAD

**Issue by deVaXz** [dotnet/corefx#15990]
I am porting a .net 4.5 windows application to a .net core application targeting docker. Since i have a massive usage of the System.Threading.Tasks namespace, which is obvious based on the System.Threading.ThreadPool's min/max thread configuration, I was looking for an replacement for the following APIs
- System.Threading.ThreadPool.SetMinThreads(int, int) and 
- System.Threading.ThreadPool.SetMaxThreads(int, int)

since they no longer exists.

Well, it seems to be no managed-code configuration for these values in netcore. I found out that there should be some hard configuration values in the enviroment (See: https://github.com/dotnet/cli/issues/889 and https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/clr-configuration-knobs.md), but I was not able to find an example how or where I can configure them.

[Edit]At least I can go without the SetMinThreads-API, but not without the SetMaxThreads[/Edit]

Thanks in advance! :)

**Comment by karelz** [comment]
The APIs will be part of .NET Core 2.0 and .NET Standard 2.0 - see [apisof.net](https://apisof.net/catalog/System.Threading.ThreadPool.SetMinThreads(Int32,Int32))

**Comment by deVaXz** [comment]
So if i understand correctly, the threadpool's threadcount is currently hardcoded or at least not accessible?  If there is no workaround for it, I have to wait for the release of 2.0

**Comment by karelz** [comment]
I let area owners to comment - @kouvel and @alexperovich.

**Comment by kouvel** [comment]
Before 2.0, you can use environment variables or configure the values in the app's runtime config file.
set COMPlus_ThreadPool_ForceMinWorkerThreads=10
set COMPlus_ThreadPool_ForceMaxWorkerThreads=100
https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/specs/runtime-configuration-file.md

The default min is the number of logical processors on the system, and the default max is 32K (the max possible value that will be accepted)

**Comment by deVaXz** [comment]
Thank you :) It was this information i was lacking

> runtimeOptions Section (.runtimeconfig.json)
> This` section is copied verbatim from an identical section in the input project.json file
