### ISSUE TITLE
SqlConnection.ClearAllPools not working when running on Linux

### ISSUE THREAD

**Issue by feiyun0112** [dotnet/corefx#16025]
You can repeat this issue by steps:

create new Asp.Net Core WebApi Project in VS2015

add Nuget package

`"System.Data.SqlClient": "4.3.0"`

write codes in ValuesController

```
// GET api/values
[HttpGet]
public IEnumerable<string> Get()
{
    using (var connection = new SqlConnection("Server=ip;Database=db;User Id=user;Password=pass;"))
    {
        connection.Open();
        var cmd = new SqlCommand("...", connection);
        cmd.ExecuteNonQuery();
    }

    return new string[] { "value1", "value2" };
}
// GET api/values/5
[HttpGet("{id}")]
public string Get(int id)
{
    SqlConnection.ClearAllPools();
    return "value";
}

```
run "dotnet publish" and upload files to ubuntu 16.04 server

build docker image use this Dockerfile, and run this image

```
FROM microsoft/dotnet:1.0.3-runtime

COPY . /app

WORKDIR /app

EXPOSE 5000

ENV ASPNETCORE_URLS="http://*:5000"

ENTRYPOINT ["dotnet", "WebApplication1.dll"]

```
call this webapi by muilti threads

```
public static void Main(string[] args)
    {
        var tasks = new Task[10];
        for (var i = 0; i < tasks.Length; i++)
        {
            tasks[i] = new Task(()=>
            {                    
                //call http://ip:5000/api/values                    
            });
            tasks[i].Start();
        }

        Task.WaitAll(tasks);
        Console.WriteLine("OK");
        Console.ReadLine();
    }
```

after test many times, then run “sp_who2” in Sql server, you can see many sleeping connections for db

**then you call "http://ip:5000/api/values/1", webapi will execute _SqlConnection.ClearAllPools()_ method, but run “sp_who2” in Sql server, you can see those sleeping connections not close**

SqlConnection.ClearAllPools() works when webapi running on windows, I have tested dotnet runtime 1.0.3 and 1.1.0.

**Comment by feiyun0112** [comment]
"System.Data.SqlClient": "4.3.0"

**Comment by donatasm** [comment]
Any workarounds up until it's fixed?
