### ISSUE TITLE
Add inner and outer loop testing explanation to Developer Guide

### ISSUE THREAD

**Issue by richlander** [dotnet/corefx#1603]

**Comment by MattWhilden** [comment]
The contribution guide is also lacking in test guidance. Might be worthwhile to take care of both in one fell swoop.

**Comment by weshaggard** [comment]
My hope is as we start to settle on our testing infrastructure scenarios and requirements in https://github.com/dotnet/corefx/issues/1477 we would add that to the developer guide.

**Comment by hughbe** [comment]
I think this has been fixed by #7549 so can be closed

**Comment by joperezr** [comment]
yup, this old issue seems to be done now.
