### ISSUE TITLE
Improve Uri.UnescapeDataString codepath -> UriHelper.UnescapeString

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#16040]
After doing an investigation on some performance traces collected from some mvc aspnet applications scenarios we found that a considerable amount of `char[]` objects were allocated on the GC Heap which are coming from `Uri.UnescapeDataString` codepath that is calling `UriHelper.UnescapeString` ([source code](https://github.com/dotnet/corefx/blob/master/src/System.Private.Uri/src/System/UriExt.cs#L521)) which receives a `char[]` as the destination of the unescaped string and then creating a string from that `char[]`.

I know it would be a big change but we could probably consider using the sourceString that is already allocated or using a `PooledStringBuilder` which uses an `ArrayPool` for the buffer cache as explained here:

* https://github.com/dotnet/corefx/pull/13875#issuecomment-262293493

/cc @danmosemsft @jkotas @stephentoub

**Comment by danmosemsft** [comment]
Concretely in the MVC scenario captured, UnescapeDataString is 1% of CPU time and 1.5% of strings (which doesn't sound like much but there's a lot of strings in this scenario). There really doesn't seem like a great reason to make a char[] and certainly not to make a new string out of it given probably most times the result will be the same as the input.

**Comment by safern** [comment]
Currently working on this

**Comment by karelz** [comment]
Flipping back to "up for grabs"
Next steps: Pick up #16456 and finish it.
Complexity: Medium

**Comment by safern** [comment]
Just FYI: I had an implementation proposal but as we had other priorities now I stopped pursuing that but I did see improvements. Here is the PR whit my proposal: https://github.com/dotnet/corefx/pull/16456

**Comment by stephentoub** [comment]
See https://github.com/dotnet/corefx/issues/22569#issuecomment-377836840 and https://github.com/stephentoub/corefx/commit/c28e627792ae0d8a43a72a87c9ffd737401821b4, which also covers these code paths.

**Comment by jkotalik** [comment]
In Kestrel, we have a class which does path normalization, which has similar concerns to Unescaping. May give some inspiration for ways to improve the perf of UnescapeDataString: https://github.com/aspnet/AspNetCore/blob/master/src/Servers/Kestrel/Core/src/Internal/Http/PathNormalizer.cs
