### ISSUE TITLE
Single project build failing for platform-specific projects

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#16044]
Running an msbuild on a single source csproj for a project that does not have a platform-agnostic implementation is currently failing.

Example:
```
PS D:\git\corefx [Master]> msbuild src/System.Console/src/System.Console.csproj
...  
System\Console.cs(26,24): error CS0246: The type or namespace name 'ConsolePal' could not be found (are you missing a using directive or an assembly reference?) [D:\git\corefx\src\system.console
\src\System.Console.csproj]
```

Also fails for: System.IO.Compression, System.IO.FileSystem.
Does not fail for: System.Runtime, System.Collections

It looks like this is because the msbuild is trying to build the project for netstandard AnyOS even though it isn't supported or listed in the Configurations.props file. These are all projects that have platform-specific configs listed e.g.
```
    <BuildConfigurations>
      netcoreapp-Unix;
      netcoreapp-Windows_NT;
      uap-Windows_NT;
    </BuildConfigurations>
```

cc: @mellinoe @weshaggard

**Comment by weshaggard** [comment]
This works for me. @ianhays when is the last time you did a full clean `clean.cmd --all`? I know there have been a number of build changes that requires the tools to be cleaned out and recreated.

**Comment by ianhays** [comment]
>when is the last time you did a full clean clean.cmd --all? 

About an hour ago. @mellinoe repro'd it as well on his machine for System.IO.FileSystem at least.

**Comment by weshaggard** [comment]
OK let me do a full sync, clean, build and see I can repro it with recent changes but I'm only about a 4 hours old right now. 

Can you tell me what the value of Configuration and BuildConfiguration is from your log?

**Comment by ianhays** [comment]
I do get this questionable warning:
 ```
Line 15:   D:\git\corefx\src\System.Console\src\System.Console.csproj ConfigurationErrorMessage: Could not find a value for TargetGroup from Configuration 'Debug'.
```

**Comment by weshaggard** [comment]
I just did a pull of latest and a full clean and a build.cmd and then I can build the individual projects just fine. 

>ConfigurationErrorMessage: Could not find a value for TargetGroup from Configuration 'Debug'.

That seems to indicate something isn't correct as Configuration should not be set to Debug. Can you try and see where that is getting set to Debug at?

**Comment by ianhays** [comment]
It's something weird with powershell. I opened up a new window and building works fine in that one, but still fails in the already-open window.

**Comment by ianhays** [comment]
I'll add that to my things to try in the future when seeing weird behavior. Thanks for taking a look.

**Comment by weshaggard** [comment]
I use Powershell as my primary command shell and it works fine. It must just be something in that environment, perhaps Configuration was set as an environment variable.

**Comment by ianhays** [comment]
@mellinoe just suggest that as well and you're both correct. I was building Core-Setup build.cmd in the same window which sets the "Configuration" environment variable and that was causing my issues when moving back to building corefx. Looks like a build failure in my core-setup prevented the Configuration from being unset.
