### ISSUE TITLE
Android cross-build fails if "rt" library is not removed from CMake configuration

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#16043]
@qmfrederik This might be an issue with the way I've run the cross-build commands, but I figured I'd file this issue anyways. When I run the Android cross build after creating the Android rootfs, I get an error related to the `HAVE_MKSTEMP` check failing, when it should be passing (according to the PR's I followed, at least). It fails because the linker is trying to pass `-lrt`, which doesn't seem to be working on Android. If I remove this line then everything works, and the build succeeds: https://github.com/dotnet/corefx/blob/master/src/Native/Unix/configure.cmake#L295. This seems to line up with what I am reading about online regarding Android builds.

**Comment by qmfrederik** [comment]
@mellinoe Thanks! That was an oversight on my side, #16065 should fix it.
