### ISSUE TITLE
SerialPort test unicode source did not come in cleanly from netfx

### ISSUE THREAD

**Issue by willdean** [dotnet/corefx#16050]
One for @JeremyKuhne again I'm afraid.

There is a big unicode string in  `SerialPortRegressions.VerifyReadExisting` which has come in from legacy as a load of question marks.

If you wouldn't mind attaching the orginal utf-8 or however it was originally, then I'll sort out making it all into \u's or a char array or something.

This is the final failing test in the loopback config :-)

**Comment by JeremyKuhne** [comment]
@willdean The source was this way as far back as I could find it. :( Can you come up with an equivalent test?

**Comment by willdean** [comment]
@JeremyKuhne Thanks for checking - I don't know what's being tested here, really!  Clearly there was some regression in the past something to do with UTF8, and this test was added as a result of that problem.

If there were comments in original code or anything in version control which pointed to an internal bug report then I might be able to reconstruct something based on the description of the problem, but otherwise I guess we should just delete it.

**Comment by JeremyKuhne** [comment]
I can't find any clues and I can't figure it out either, so I'm totally fine with deleting it.

**Comment by krwq** [comment]
I'm fixing this issue in this PR: https://github.com/dotnet/corefx/pull/33027/files#diff-773a9e01da688a99d805eb327e4b7012R22

**Comment by JeremyKuhne** [comment]
Closing as @krwq's pr was merged. https://github.com/dotnet/corefx/pull/33027/files#diff-773a9e01da688a99d805eb327e4b7012R22
