### ISSUE TITLE
PartitionerStatic.SharedLong Value seems to be missing "volatile" modifier

### ISSUE THREAD

**Issue by coderb** [dotnet/corefx#16067]
I haven't analysed the code, but superficially it seems as though there is a "volatile" modifer missing from the Value field of class SharedLong in:

corefx/src/System.Collections.Concurrent/src/System/Collections/Concurrent/PartitionerStatic.cs

**Comment by stephentoub** [comment]
Why? Unless there's a specific case of concern, this issue isn't actionable. All uses appear to either be under a lock, with Interlocked, with Volatile, or in a non-shared context.

**Comment by stephentoub** [comment]
@coderb, I'm closing this.  If you have a more specific concern, please feel free to re-open.
