### ISSUE TITLE
*.builds files for tests

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#16081]
The tests still have both Configurations.props files and  *.builds files.

@weshaggard Do we need both? Should we delete the *.builds files?

**Comment by weshaggard** [comment]
No this is on the list of things to get cleaned-up we just didn't have a tracking issue for it. We can use this issue. 

We should delete all the *.builds files that are in the library directories, we still use them for the root traversal builds.

**Comment by weshaggard** [comment]
Removed these in #16212
