### ISSUE TITLE
Fold or rename *.netstandard.cs files

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#16082]
They do not need to be separate files and the .netstandard suffix on them is just confusing because of they do not have anything netstandard-specific in them. They contain tests for APIs added on top of netstandard1.6 in the early days of netstandard2.0 project.

See https://github.com/dotnet/corefx/pull/16072

**Comment by karelz** [comment]
cc: @danmosemsft

**Comment by JonHanna** [comment]
There's at least a few that aren't tests. I assume we'd want to fold those too?

**Comment by jkotas** [comment]
Yes - fixed the title.
