### ISSUE TITLE
Please expose all Array static method as extension method

### ISSUE THREAD

**Issue by Thaina** [dotnet/corefx#16084]
There are a bunch of static function in `Array` class that should just be extension method

Like `Find` and `IndexOf`

Using extension method is more natural and also familiar with js

**Comment by karelz** [comment]
For compatibility with Desktop .NET Framework and Xamarin we cannot remove the static methods.
.NET/C# should not just blindly copy patterns used in outer languages like JS. If such concepts make sense in .NET/C# land, we need proper reasoning on its own.

Adding extension methods might be useful if it improves discoverability of the API ... can you please share more details, pros/cons, usage examples, etc.? You can check [API proposal process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md).

**Comment by Thaina** [comment]
I don't think we need to remove old static api. Instead, we just have extension class wrap those static api

Like this

```C#
class Ext
{
    public static int IndexOf<T>(this T[] array,T item)
    {
}
}
```

**Comment by karelz** [comment]
OK, not removing existing APIs is good.
Can you please update top post with API proposal. Please include all methods you propose to add - it will simplify the discussion.

**Comment by Thaina** [comment]
@karelz Well, that's hard. Because there are so many function in [Array class](https://msdn.microsoft.com/en-us/library/system.array(v=vs.110).aspx) that should just be wrapped

I think I could better write the implementation code if there is a file I could write to
Because it is just this

```C#
class ArrayExt
{
    public static void Clear<T>(this T[] array) => Array.Clear(array);
    public static int IndexOf<T>(this T[] array,T item) => Array.IndexOf(array,item);
    public static T Find<T>(this T[] array,Predicate<T> predicate) => Array.Find(array,predicate);
    public static int FindIndex<T>(this T[] array,Predicate<T> predicate) => Array.FindIndex(array,predicate);
    // etc etc etc
}
```

But I don't know what name that extension class should have or where I should put that file in corefx. Could you guide me?

**Comment by karelz** [comment]
@Thaina we will need full list of methods. But maybe you can wait for area owners to first comment on it though (if they don't like it, it would be waste of time).
Suggestion: You can avoid the implementation part, it will be easier to read.

For each extension method, you will also have to think through any potential collision with already existing methods (e.g. on Linq).

Regarding the class name -- I don't know the answer myself. You can do some research on existing extension classes in CoreFX. In the worst case it can be finalized during API review.

**Comment by AlexGhiondea** [comment]
@Thaina I think we need a formal API proposal that will describe the reasons behind adding those extension methods as well as calling out all of the methods that you are considering creating wrappers for.

**Comment by Thaina** [comment]
@AlexGhiondea I think it was obvious to see that it really is for convenient. We could do all functionality of `Array` class without mentioning it and don't need to put `using System` on top of the file, this also help avoid class name collision (Like in unity `Object` class)

For example

```C#
// Instead of
using System;

int i = Array.IndexOf(array,value);
Array.Clear(array);
// We could
array.IndexOf(value);
array.Clear();
```

**Comment by stephentoub** [comment]
The fact that there's no API proposal because there are so many methods highlights why we're not going to do this: it's a ton of work and additional surface area for little gain, and anyone desiring the extension syntax could write those extensions themselves, and even put them in a library on nuget for anyone else to use as well.  Thanks for the suggestion, though.
