### ISSUE TITLE
Unable to build.cmd while offline

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#16097]
I did a full build.cmd successfully and then disconnected.  When I tried to build.cmd again, even with using -RestoreDuringBuild=false, I got errors that prevented the build from succeeding:
```
EXEC : error : Unable to load the service index for source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json. [C:\Users\stoub\Source\repos\corefx\external\runtime\runtime.depproj]
EXEC : error : An error occurred while sending the request. [C:\Users\stoub\Source\repos\corefx\external\runtime\runtime.depproj]
EXEC : error : The server name or address could not be resolved [C:\Users\stoub\Source\repos\corefx\external\runtime\runtime.depproj]
C:\Users\stoub\Source\repos\corefx\Tools\packageresolve.targets(35,5): error MSB3073: The command ""C:\Users\stoub\Source\repos\corefx\Tools/dotnetcli/dotnet.exe" restore --no-cache --packages "C:\Users\stoub\Source\repos\corefx\packages"
--source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://api.nuget.org/v3/index.json "C:\Users\stoub\Source\repos\corefx\bin/obj/Windows_NT
.AnyCPU.Debug/runtime/netcoreapp/Windows_NT-x64/project.json"" exited with code 1. [C:\Users\stoub\Source\repos\corefx\external\runtime\runtime.depproj]
```

**Comment by karelz** [comment]
That's pretty bad. @weshaggard can you please look into it?

**Comment by weshaggard** [comment]
Yes we should look into making sure the offline mode works correctly. 

Ideally after calling sync.cmd or one call to build.cmd you should be able to fully work offline, assuming you didn't clean.

**Comment by danmosemsft** [comment]
Who owns this @weshaggard ?

**Comment by karelz** [comment]
@weshaggard I think the line should be "sync.cmd" and I can go offline even for first "build.cmd".
In general: build.cmd should not even attempt to touch the network if I ran sync.cmd before that.

**Comment by weshaggard** [comment]
>Who owns this @weshaggard ?

I'm not entirely sure who would be the owner the engineering system for corefx is kind of team owned. I will look into fixing this. 


>In general: build.cmd should not even attempt to touch the network if I ran sync.cmd before that.

It should amount to the same thing and should be incremental. We don't want to require folks to call sync.cmd all the time so we encapsulate that in a call to build.cmd if it hasn't been called. So a call to build.cmd or sync.cmd should setup subsequent calls to build.cmd to work offline.

**Comment by weshaggard** [comment]
@stephentoub I was actually able to run build.cmd first time online and then the second time unplugged from the network which worked fine. 

I did hit an issue where I couldn't build and individual library via "rebuild" because the auto ProjectReferences to things under external caused a restore to happen. I've fixed that with https://github.com/dotnet/corefx/pull/16210. 

Can you please give this a try and let me know if it works for you or not?

**Comment by weshaggard** [comment]
I'm going to assume this is fixed. If you still have issues please reactivate.
