### ISSUE TITLE
OuterLoop_Win7_debug: Test under "Legacy.SerialStream" failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#16099]
Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_debug/95/consoleText

Configuration: OuterLoop_Windows7_debug (build#95)

Message:
~~~
Legacy.SerialStream.WriteByte_Generic.SuccessiveReadTimeout [FAIL]
        ERROR!!!: The write method timedout in 0 expected 1054 percentage difference: 1
        Expected: True
        Actual:   False
~~~

Stack Trace:
~~~
D:\j\workspace\outerloop_win---b280fd23\src\System.IO.Ports\tests\Legacy\Support\PortsTest.cs(24,0): at System.IO.PortsTests.PortsTest.Fail(String format, Object[] args)
           D:\j\workspace\outerloop_win---b280fd23\src\System.IO.Ports\tests\Legacy\SerialStream\WriteByte_Generic.cs(452,0): at Legacy.SerialStream.WriteByte_Generic.VerifyTimeout(SerialPort com)
           D:\j\workspace\outerloop_win---b280fd23\src\System.IO.Ports\tests\Legacy\SerialStream\WriteByte_Generic.cs(117,0): at Legacy.SerialStream.WriteByte_Generic.SuccessiveReadTimeout()
~~~

Failed tests:
WriteByte_Generic/SuccessiveReadTimeout
WriteByte_Generic/BytesToWriteSuccessive
WriteTimeout_Property/WriteTimeout_750_WriteByte  
WriteTimeout_Property/WriteTimeout_750_Write_byte_int_int 
Write_byte_int_int_Generic/BytesToWriteSuccessive
Write_byte_int_int_Generic/SuccessiveWriteTimeout

**Comment by Jiayili1** [comment]
This issue is also repro on following configurations:
1.	OuterLoop_Windows7_debug (build#95)
2.	OuterLoop_Windows7_release (build#95)
3.	OuterLoop_Windows8.1_debug (build#98)
4.	OuterLoop_Windows8.1_release (build#95)
5.	OuterLoop_Windows10_debug (build#91)
6.	OuterLoop_Windows10_release (build#97)

**Comment by danmosemsft** [comment]
@Jiayili1 I think @willdean may have fixed or disabled this now? Please close if appropriate

**Comment by Jiayili1** [comment]
@danmosemsft I will check it on the new build, thanks Dan.

**Comment by Jiayili1** [comment]
This issue doesn't repro, so remove "blocking-clean-ci", and closed this issue.
