### ISSUE TITLE
System.Diagnostics.Debug.Tests does not build on Linux

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#1609]
System.Diagnostics.Debug.Tests currently fails trying to resolve types against System.Runtime. It is disabled in dir.props.

**Comment by jasonwilliams200OK** [comment]
@JeremyKuhne, @Djuffin, this seems to be fixed, removed from props and builds on Unix:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/opensuse13.2_debug_tst/757/testReport/System.Diagnostics.Tests/DebugTests/

Should this issue be closed and the note about it under https://github.com/dotnet/corefx/blob/f2b8d97/Documentation/building/unix-instructions.md#known-issues be removed?

**Comment by jasonwilliams200OK** [comment]
> Djuffin was unassigned by jasonwilliams200OK 22 seconds ago

??? :open_mouth: 

@mellinoe, @stephentoub any ideas how did this happen? I swear I just posted a comment.. :smile:

**Comment by noahfalk** [comment]
Djuffin went to work on a new project a while back fyi. I assigned the issue to @JeremyKuhne in case he'd like to confirm everything is resolved for himself.
