### ISSUE TITLE
Proposal: Intorduce a new auto-property DOSHeader to file System/Reflection/PortableExecutable/PEHeaders.cs

### ISSUE THREAD

**Issue by sohail** [dotnet/corefx#161]
We've PEHeader and CoffHeader properties class PEHeaders(namespace System.Reflection.PortableExecutable), which return the instances of their respective classes, I propose a new property by the name of DOSHeader which will return the DOS header and DOS stub.

**Comment by tmat** [comment]
What information are you looking for? MSDOS header doesn't seem to have anything interesting in it. It's essentially just a constant.

**Comment by nguerrera** [comment]
This was associated with PR #162 , which is closed. So I'm closing this as well. As I said on the PR, if there is a scenario we're missing, we can consider re-opening it, but I agree with @tmat, it doesn't seem useful.
