### ISSUE TITLE
Namespaces for test classes

### ISSUE THREAD

**Issue by willdean** [dotnet/corefx#16105]
Is there any guidance for namespacing tests?

The `SerialPort` tests which I currently seem to be herding are in a mixture of the root namespace (!) which is where they fell, in `Legacy.SerialStream` which is where I moved a bunch of them because they clashed with the root lot and that was what Resharper did for me automatically, and in `System.IO.PortsTests`, which is where @JeremyKuhne put an example test for us (note no dot between Ports and Tests).

Looking at the tests results on the CI I see things like:

```
System.Drawing.Primitives.Tests
System.Drawing.Primitives.Test
System.Drawing.PrimitivesTests
```

Which makes me a bit unsure what we should be aiming for, and I couldn't find it written down anywhere.  What's best here?

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/issues/2898

**Comment by willdean** [comment]
@stephentoub Thanks - Looks like everything which could ever be said on the subject has already been said...  I'll close this.
