### ISSUE TITLE
System.Diagnostics.FileVersionInfo.Tests.csproj does not build on Linux

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#1610]
The OpenSourceSign target complains about System.Diagnostics.FileVersionInfo.TestAssembly.dll not being delay signed. It is currently disabled in dir.props.

**Comment by akoeplinger** [comment]
Is this still an issue on your end? I enabled it in dir.props and it built fine on Linux here.

**Comment by JeremyKuhne** [comment]
Not seeing it either. Putting up a PR to remove it...

**Comment by JeremyKuhne** [comment]
#2132
