### ISSUE TITLE
OuterLoop_Win7_debug: tests under "Legacy.SerialStream.WriteTimeout_Property" failed with "Xunit.Sdk.ThrowsException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#16100]
Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_debug/95/consoleText

Configuration: OuterLoop_Windows7_debug (build#95)

Message:
~~~
Assert.Throws() Failure
        Expected: typeof(System.TimeoutException)
        Actual:   (No exception was thrown)
~~~

Stack Trace:
~~~
D:\j\workspace\outerloop_win---b280fd23\src\System.IO.Ports\tests\Legacy\SerialStream\WriteTimeout.cs(265,0): at Legacy.SerialStream.WriteTimeout_Property.SuccessiveWriteTimeoutNoData_WriteByte()
~~~

Failed tests:
WriteTimeout_Property/SuccessiveWriteTimeoutNoData_WriteByte 
WriteTimeout_Property/SuccessiveWriteTimeoutNoData_Write_byte_int_int

**Comment by Jiayili1** [comment]
This issue is also repro on following configurations:
1.OuterLoop_Windows7_debug (build#95)
2.OuterLoop_Windows7_release (build#95)
3.OuterLoop_Windows8.1_debug (build#98)
4.OuterLoop_Windows8.1_release (build#95)
5.OuterLoop_Windows10_debug (build#91)
6.OuterLoop_Windows10_release (build#97)

**Comment by danmosemsft** [comment]
@Jiayili1 I think @willdean may have fixed or disabled this now? Please close if appropriate

**Comment by Jiayili1** [comment]
This issue doesn't repro, so remove "blocking-clean-ci", and closed this issue.
