### ISSUE TITLE
 HttpResponseHeader should have a Cookies property

### ISSUE THREAD

**Issue by ohameiri** [dotnet/corefx#1611]
Hello,
The HttpResponseHeader class (found at https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Headers/HttpResponseHeaders.cs ) doesn't seem to include a standard and pretty trivial header, the Cookies header.

Furthermore, as suggested by http://www.asp.net/web-api/overview/advanced/http-cookies, we should use the HttpResponseHeadersExtensions, found at https://aspnetwebstack.codeplex.com/SourceControl/latest#src/System.Net.Http.Formatting/HttpResponseHeadersExtensions.cs , however, as you can see in the code (and in the CookieHeaderValue class) - there's no way to configure default values, e.g. HttpOnly or Secured.

In a regular ASP.NET website we can set the default values in web.config, but since ASP.NET WebAPI doesn't rely on that, there's no way, even in the WebAPI configuration registering method to set such values.

Part from creating my own extension to add cookies with default values, I would suggest adding support for cookies in the HttpResponseHeaders class and having the option to set default values in registration time.

Thank you very much.

**Comment by weshaggard** [comment]
cc @davidsh

**Comment by SidharthNabar** [comment]
Hi @ohameiri - what is the scenario you are thinking of for this additional header? Today, we use the CookieContainer object for the client to check which cookies were sent by the server in an HTTP response. 

Also, the effort for open-sourcing System.Net.Http dev and test sources is still ongoing - we are not yet at the point where we are taking additional API surface requests. But its good to have the discussion anyway about whether we do need an additional header.

Thanks,
Sid

**Comment by ohameiri** [comment]
Hello @SidharthNabar and thank you for your response.

We are building an AngularJS app which is communicating directly with the WebAPI, no MVC middleware. For security considerations, we often need to add cookies which the app will use when needed (e.g. a somewhat complex CSRF double submit cookie). Nevertheless, cookies are a trivial part of HTTP and should be supported at the core.

Am I able to contribute a patch to add this support? will it be considered to be committed?

Again, thank you for the response, I will keep track on the issue.

**Comment by SidharthNabar** [comment]
@ohameiri - From the info you have provided, it seems you are implementing the server role (sending HTTP responses to clients). Can you confirm?

In that case, you will need the "Set-Cookie" header, and not the "Cookie" header (the Cookie header is added by the client on the request message). Also, HttpClient and related classes are designed mainly for implementing the client role, not the server role. For server role, please see ASP.NET 5 and HttpContext.Response.Cookies property.

Coming to HttpClient, in .NET 4.5.x and before, the behavior was that the client stack would see the "Set-Cookie" header on the response, extract the cookie and put it in the container. It would then strip off the header from the response message before returning it to the HttpClient call. In our new, core CLR-based implementations (.NET native and ASP.NET 5) of HttpClient, we do not strip off the header. So if you look at the Headers collection of the HttpResponseMessage, the Set-Cookie header should be there. You are right - in the future, we could consider adding a strong type to represent this header. 

As I mentioned in my earlier response, we are not yet at the stage where we are taking API additions to the HttpClient API. But you can definitely submit a PR, and it will go through the standard API review process for dotnet/corefx once we open up for API additions to System.Net.Http.

Thanks!
Sid

**Comment by ohameiri** [comment]
@SidharthNabar - Yes, I am talking about the "Set-Cookie" which is the standard response (what I have been talking about), and as you can also see in https://github.com/Microsoft/referencesource/blob/master/System.Web/HttpResponse.cs, the property name is "Cookies", not "SetCookies", because that's what we're talking about (as a property). I wouldn't expect a client to send a "Set-Cookie" and a server to use it.

I am not talking about HttpClient, but about HttpResponseHeader in System.Net.Http on the WebAPI response. Any implementation I will build would simply strip a lot of the code in System.Web response and cookie classes and putting it in the System.Net namespace. For clarification - the HttpContext.Response.Cookies is not part of the WebAPI response, they are in different namespaces.

An example of something I'm doing in WebAPI: A filter for the requests\response, which inherits System.Web.Http.Filters.ActionFilterAttribute has the OnActionExecuting virtual method which takes the System.Web.Http.Controllers.HttpActionContext class as a parameter. However, that class only has a System.Net.Http.HttpResponseMessage to which I should apply my headers. It is different from the System.Web.HttpResponse in regular ASP.NET sites and does not have the Cookies property ("Set-Cookie" header) which I am talking about.

Again, thank you very much for your responses.

**Comment by Tratcher** [comment]
@ohameiri This is all being addressed in ASP.NET 5 (https://github.com/aspnet/home).  WebApi has been merged back into MVC and now uses the Microsoft.AspNet.Http.HttpContext object model instead of System.Net.Http.HttpResponseMessage. Response cookies are first class and we are working on a way to set default values for HttpOnly and Secured.

Separately, there is a plan to add strongly typed Cookie and Set-Cookie header parsers and properties to System.Net.Http to fill this gap, but we don't have the work scheduled yet, and it won't include support for default values for HttpOnly and Secured.

**Comment by karelz** [comment]
Triage: There is already a way to get cookies from CookieContainer. We don't see strong reason to add yet another way how to get to it.
If there is strong interest and evidence we missed, we are willing to reconsider. Closing for now.

**Comment by Tratcher** [comment]
CookieContainer is difficult to work with on a per-request basis as you only have access to the HttpClientHandler/CookieContainer when you first create the HttpClient instance, not when you're sending requests or processing responses, unless you manually flow the container along with the client. You may not even have access to the handler/container if another component created the HttpClient instance and passed it to you.

We do a lot of testing where we need to set cookies directly on a request and look at the cookies on a specific response. Formatting request cookies manually isn't hard, but parsing response cookies is a lot of work. It would be helpful if Set-Cookie was a first class strongly typed response header. We wrote our own to fill this gap: https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Net.Http.Headers/SetCookieHeaderValue.cs

**Comment by davidsh** [comment]
Thanks for the feedback and use case.  Feel free to submit a new issue with detailed API proposal and/or PR for changes.  

By the way, aren't the raw response headers (strings) already available in the HttpResponseMessage.Headers?  If so, it sounds like the requirement is to have a strongly typed object model for the 'Set-Cookie' header itself.
