### ISSUE TITLE
ExpandoClass summary worded incorrectly/ambiguously?

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/corefx#16116]
There seems to be some room for interpretation in this summary:
```cs
    /// <summary>
    /// Represents a dynamically assigned class.  Expando objects which share the same
    /// members will share the same class.  Classes are dynamically assigned as the
    /// expando object gains members.
    /// </summary>
```
https://github.com/dotnet/corefx/blob/ec2a6190efa743ab600317f44d757433e44e859b/src/System.Linq.Expressions/src/System/Dynamic/ExpandoClass.cs#L9

Specifically:

> Expando objects which share the same members will share the same class

How does this work? I don't see any static caching of ExpandoClass going on in either _transitions or ExpandoObject's internal structures like ExpandoData.

Or is what is meant something more like, they (should) result in the same type of instance e.g. the same sort of data/hashcode/etc is contained for an ExpandoObject that shares the same members.

**Comment by JonHanna** [comment]
They have the same *class* as a general OOP concept. This take on the concept of *class* is not the same as the static C# take that the `class` keyword provides (where an object can't change class, and two distinct classes could have identical members) but is a different approach to the general OOP concept. (Or if your own views on OOP don't allow a class to behave like that, it still fits within the definitions covered by the English-language word *class* < Latin *classis*).

An `ExpandoClass` object represents this, just as the `Uri` class represents a URI an so on, and likewise just as two separate instances of the `Uri` class can represent the same URI so two instances of the `ExpandoClass` class can represent the same class in this sense.

So there need not be static caching for this to hold.

That said, there is static caching in that with `Empty` as the common externally-accessible starting point and `_transitions` being searched before new allocations, two `ExpandoObject`s given the same members in can have the same `ExpandoClass` instance. This won't happen if they get their members in a different order, or if intermediate classes were collected in the meantime, but it can reduce allocations.
