### ISSUE TITLE
System.Data.SqlClient.SqlParameter Precision and Scale do not work via the abstract API

### ISSUE THREAD

**Issue by mgravell** [dotnet/corefx#1612]
Package from dnxcore50 via

    "System.Data.SqlClient": "4.0.0-beta-*",

This works:

    SqlParameter p = ...
    p.Precision = 10;
    p.Scale = 5;

However, if instead we use the abstract base class (like most tools will be):

    SqlParameter p = ...
    DbParameter d = p;
    d.Precision = 10;
    d.Scale = 5;

then all of `p.Precision`, `p.Scale`, `d.Precision`, `d.Scale` **remain at 0**, and consequently do not work correctly.

The abstract API's `Scale` and `Precision` (and any other associated members) should mirror the concrete type's equivalent.

This code is not in corefx yet, so I cannot fix it :(

**Comment by FransBouma** [comment]
+1, this obviously needs fixing. One way to get these errors ironed out at the corefx side is to only use DB generic code in your tests, Microsoft, not an intermediate build of SqlClient, as that will lead to problems like this (and has lead to problems in the past, in numerous occasions).

**Comment by mgravell** [comment]
@Frans well, you'd need both: it is also important that it works via the concrete API :)

**Comment by FransBouma** [comment]
True, it's just odd they have storage for precision/scale at the SqlClient level, as the precision / scale and other shared values across the board should be stored at the base class level, IMHO (and overrides of the setters to make type decisions perhaps)

Also odd: that they didn't borrow code from .NET full for this class (so it would have worked), as this code has already been written years ago!

**Comment by mgravell** [comment]
Yeah, checking the IL, the problem is a re-declare rather than an override; base is:

    public virtual byte Scale
    {
        get
        {
             return 0;
         }
        set
        {
        }
    }
 
with the concrete type having:

    public byte Scale
    {
        get
        {
            return this.ScaleInternal;
        }
        set
        {
            this.ScaleInternal = value;
        }
    }

Looks like just a missing `override`, although I wonder if the base method should actually be `abstract`

**Comment by FransBouma** [comment]
I don't think the base member should be abstract, it should be virtual, but the value should be stored in the base class: the overriding class should override the setter to be able to do bookkeeping, but that's it, as precision/scale and other parameter specifics are not really different in context from provider to provider (i.e. precision 10 is precision 10).

But if there's no code in the virtual member now, then indeed it should be abstract (it's the same in the reference source btw: https://github.com/Microsoft/referencesource/blob/master/System.Data/System/Data/Common/DBParameter.cs

**Comment by mgravell** [comment]
Ahah! So that's how the old code works: because it re-implements the
interface using implicit implementation for those members, and the old base
implementation casts to the interface, so will get the top version.

**Comment by FransBouma** [comment]
Yeah I think they missed a cast indeed. It's a bizarre design however, I really don't know why it is this way, as Precision has this, but other properties are abstract, and aren't this way. It looks like it's been changed ad-hoc to meet some scenario at some point. 

Also, why is this source not on github but inside MS' quarters? Isn't the point they're making that they're developing things out in the open? Anyway, let's hope MS is going to fix this before RTM...

**Comment by joshfree** [comment]
@saurabh500 @YoungGah

**Comment by NickCraver** [comment]
Any update on this @YoungGah  @saurabh500? I'd love to uncomment these broken units tests over here in Dapper :)

**Comment by AlgorithmsAreCool** [comment]
So, this looks like a pretty straight forward fix. If nobody has gotten to it, would it be ok if i submitted a pull request for it? I'd like to help out if i could.

**Comment by saurabh500** [comment]
@AlgorithmsAreCool Contributions are welcome. 
Please go ahead.

**Comment by saurabh500** [comment]
Merged in #4902 from @AlgorithmsAreCool after validations.
