### ISSUE TITLE
Failures in .HttpClientHandlerTest.GetAsync_AllowAutoRedirectTrue_RetainsOriginalFragmentIfAppropriate

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16133]
Turning our Win7 badge read. @Priya91 could you please fix or disable today to get back to green.

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_release/lastCompletedBuild/testReport/

   ```
System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_AllowAutoRedirectTrue_RetainsOriginalFragmentIfAppropriate(origFragment: \"#origFragment\", redirFragment: \"\", expectedFragment: \"#origFragment\", useRelativeRedirect: False)	
 System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_AllowAutoRedirectTrue_RetainsOriginalFragmentIfAppropriate(origFragment: \"\", redirFragment: \"#redirFragment\", expectedFragment: \"#redirFragment\", useRelativeRedirect: False)	
 System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_AllowAutoRedirectTrue_RetainsOriginalFragmentIfAppropriate(origFragment: \"\", redirFragment: \"#redirFragment\", expectedFragment: \"#redirFragment\", useRelativeRedirect: True)	
 System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_AllowAutoRedirectTrue_RetainsOriginalFragmentIfAppropriate(origFragment: \"#origFragment\", redirFragment: \"#redirFragment\", expectedFragment: \"#redirFragment\", useRelativeRedirect: False)	
 System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_AllowAutoRedirectTrue_RetainsOriginalFragmentIfAppropriate(origFragment: \"#origFragment\", redirFragment: \"#redirFragment\", expectedFragment: \"#redirFragment\", useRelativeRedirect: True)	
```

**Comment by danmosemsft** [comment]
@Priya91 @steveharter

**Comment by steveharter** [comment]
@sepidehMS it appears  System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_AllowAutoRedirectTrue_RetainsOriginalFragmentIfAppropriate is now failing on win7. 

Can you please add back the [PlatformSpecific] and log appropriate 'win7' bug. Thanks.

Per issue https://github.com/dotnet/corefx/pull/15932

````
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_debug/98/#showFailuresLink
System.Net.Http.HttpRequestException : An error occurred while sending the request.\r\n---- System.Net.Http.WinHttpException : The data is invalid

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_debug/97/#showFailuresLink
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_debug/96/#showFailuresLink
````

**Comment by steveharter** [comment]
I didn't see that Priya already disabled the tests, so we should be good except for the new issue regarding Win7

**Comment by Priya91** [comment]
This test is disabled for win7, so removing blocking-clean-ci.

**Comment by sepidehMS** [comment]
@steveharter I removed the PlatformSpecific label after looking at this test's history and also the APIs it calls and to me it didn't seem like it should be specific to Unix. Do you mean this should never run on Windows and I missed something?

**Comment by steveharter** [comment]
@sepidehMS the change to remove the label caused Win7 jobs to fail, so we needed to add that label back at least for Win7. @Priya91 did that already, and I didn't know that until after I added my comment. 

Note that the Win7 runs do not run automatically for PRs, so that job has to be manually started. 

If there is not already an issue to fix this for Win7, please create the issue (as you already created issues for similar cases)

**Comment by sepidehMS** [comment]
Created new issue https://github.com/dotnet/corefx/issues/16272. Closing this one.
