### ISSUE TITLE
System.Data.SqlClient does not allow enum parameters values (it does in .NET)

### ISSUE THREAD

**Issue by mgravell** [dotnet/corefx#1613]
Is this an expected break?

For example:

        using (var cmd = connection.CreateCommand())
        {
            cmd.CommandText = "select @foo";
            cmd.Parameters.AddWithValue("@foo", AnEnum.B);
            object value = cmd.ExecuteScalar();
            AnEnum val = (AnEnum)value; // cheeky unbox behavior
            val.IsEqualTo(AnEnum.B);
        }

        enum AnEnum
        {
            A = 2,
            B = 1
        }

In .NET this works fine; in CoreCLR this breaks on the `ExecuteScalar()` call, reporting an `ArgumentException` with text:

> No mapping exists from object type AnEnum to a known managed provider native type.

**Comment by joshfree** [comment]
@saurabh500 @YoungGah

**Comment by NickCraver** [comment]
Any update on this? Noticed it again while porting our unit tests for the latest round of CoreCLR updates.

**Comment by saurabh500** [comment]
Looking into this @NickCraver

**Comment by mgravell** [comment]
The key thing that is different is the `DbType` behavior; in .NET it is ok without this being set explicity; in the current core builds, it needs to be set to work:

        [Fact]
        public void AdoNetEnumValue()
        {
            using (var cmd = connection.CreateCommand())
            {
                cmd.CommandText = "select @foo";
                var p = cmd.CreateParameter();
                p.ParameterName = "@foo";
                p.DbType = DbType.Int32; // comment me out to see fail
                p.Value = AnEnum.B;         
                cmd.Parameters.Add(p);
                object value = cmd.ExecuteScalar();
                AnEnum val = (AnEnum)value;
                val.IsEqualTo(AnEnum.B);
            }
        }
        enum AnEnum
        {
            A = 2,
            B = 1
        }

**Comment by kpboyle1** [comment]
My most recent portability report (using the November, 2015 rc1 bytes) shows incompatibility in the following SqlClient libraries:  System.Data.DataRowVersion
System.Data.SqlClient.SqlCommand
System.Data.SqlClient.SqlConnection
System.Data.SqlClient.SqlDataReader
System.Data.SqlClient.SqlParameter
System.Data.SqlClient.SqlParameterCollection
System.Data.SqlDbType
System.Data.SqlTypes.SqlBytes
System.Data.SqlTypes.SqlString
System.Data.SqlTypes.SqlXml
Unless I'm missing a new nugget package for SqlClient, a lot more than just enum parameters are incompatible. I use these libraries for fast data list retrieval from stored procedures (and Entity Framework for everything else). I'll periodically revisit this issue on this GitHub section. Thanks.

**Comment by kkurni** [comment]
@kpboyle1 I don't think this is related issue.
This issue is a bug where the validation doesn't detect the type of underlying value.

RC2, will have more APIs compare to RC1. There will still be incompatibility but the goal is deliver cleaner APIs. Each incompatibility should have an alternative or better way to do it.
Here is some reference how to build libraries compatible with .NET Platform.
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/support-dotnet-core-instructions.md

Please raise on different issue, if you think there is important APIs that is important to have which is not available.

**Comment by saurabh500** [comment]
@kkurni can we close this issue with your PR ?
