### ISSUE TITLE
Investigate using Unsafe to circumvent covariant array typechecks in ToArray

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#16138]
During a recent PR I tried changing [this](https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Concat.cs#L467) to hold references to the collections directly instead of holding the index of each collection, which I had originally done to keep the size of the builder to a minimum. It seems like the benefits extended past just memory usage, though-- changing the builder to an `ArrayBuilder<IEnumerable<TSource>>` incurs 3x more time just to store each collection in the array than all of the interface typecasts.

![arraystorecheck](https://cloud.githubusercontent.com/assets/9159214/22914846/05413522-f241-11e6-82b0-255de16ded62.PNG)

For that reason maybe we should consider using `Unsafe` in [LargeArrayBuilder](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Collections/Generic/LargeArrayBuilder.cs#L154), which is used by `Enumerable.ToArray`, to circumvent the typechecking if this turns out to have a significant enough impact. With so many other virtual method calls/typecasts going on around that method, I was really surprised to see that array stores were taking up more than 18% of the time.

/cc @benaadams

**Comment by benaadams** [comment]
Also have a look at RefAsValueType
https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/RefAsValueType.cs#L11

**Comment by jamesqo** [comment]
@benaadams Yes, I am aware of that type. The only problem is that these are the arrays that are returned to the user so they have to be of type `TSource[]`.

**Comment by jkotas** [comment]
We should wait for Span to become more stable. Span will allow you to circumvent covariant array checks as well, without writing tricky unsafe code.

**Comment by jamesqo** [comment]
@jkotas `Span<T>` can only be stored on the stack though, so it cannot be a field of the builder type... plus, it could take a long time to mature.

**Comment by jkotas** [comment]
Well, I am not a fan of type unsafe code spreading in something like Linq. People will get it wrong and it sets a bad example.

Fixing https://github.com/dotnet/coreclr/issues/603 should make these type checks very cheap. We should look at it first.

If even the cheap type check is a problem, we may look into adding a non-variant array helper type that allows you to hoist the covariant check, without compromising type safety. Similar to what RefAsValueType does, except that the array would be of the right type. Something like:

```
struct NonVariantArray<T>
{
    // Does exact type check (similar to Span<T> constructors)
    public NonVariantArray(T[] array);

    // Allocates array of given size. Does not have any type checks.
    public NonVariantArray(int length);

    public T this[int index]
    {
        // Getter forwards to regular array getter
        get;
        // Setter is implemented using runtime magic that avoids covariance check
        set;
    }

    public T[] UnderlyingArray
    {
       get;
    }
};
```

**Comment by benaadams** [comment]
> If even the cheap type check is a problem, we may look into adding a non-variant array helper type that allows you to hoist the covariant check, without compromising type safety. 

That would be amazing 😄 To go further, I wonder if it could be expressed as an attribute?

```csharp
[InvariantArray]
private T[] _array;
```
Though might be leaky when taking function local copies to work on; or assignment/return of whole array?

**Comment by jkotas** [comment]
Right, the attribute would turn this into ad-hoc language feature.

**Comment by benaadams** [comment]
Helper would be good too; I assume `List<T>` is nonvariant as are its interfaces so `List<T>.Add` and `T this[int index]` could make use of it in coreclr; even if the type itself would take longer and require api review?

**Comment by JonHanna** [comment]
Possibly a fix to #13816 would make this irrelevant by reducing the need for some of the checks (though possibly it would actually complicate the checks, it's hard to predict a hypothetical change).

**Comment by jkotas** [comment]
> `List<T>`

Agree, `List<T>` may be a fine place to experiment with this.

> fix to #13816

This fix has neglible performance effect.

**Comment by jamesqo** [comment]
> Agree, `List<T>` may be a fine place to experiment with this.

@jkotas Is that possible using the current Unsafe APIs? AFAICT there is no way using the current Unsafe/JitHelpers classes... `Write(AsPointer(ref array[index]), value)` does not work because the array can get moved around between AsPointer/Write. `Unsafe.Add(ref JitHelpers.GetArrayData(array), index) = value` (which is done by Span) does not circumvent it because it returns a `ref T` which has to be checked before being assigned.

**Comment by jkotas** [comment]
Right, there is no great way to do it using the current Unsafe/JitHelpers - there would need to be new ones invented for this purpose.

**Comment by jkotas** [comment]
BTW: My point about looking at dotnet/coreclr#603 first still holds. I believe that fixing dotnet/coreclr#603 is more valuable than introducing non-variant array wrapper because of nothing needs to be rewritten to get the benefit.
