### ISSUE TITLE
Add support for handling UNIX signals

### ISSUE THREAD

**Issue by robertmircea** [dotnet/corefx#1614]
Please add support for handling UNIX signals (e.g. TERM, KILL, INTERRUPT) in .Net coreclr apps. One of the possible usages for .Net running on Linux/Mac would be to build headless server apps (daemons) which need to behave like true *nix "citizens".

For reference: Mono has support for this feature in Mono.Unix APIs.

**Comment by stephentoub** [comment]
Good request. This is being tracked by https://github.com/dotnet/corefx/issues/3188.
