### ISSUE TITLE
ExecutionEngineException when using SslStream

### ISSUE THREAD

**Issue by ayende** [dotnet/corefx#16146]
```
Unhandled exception at 0x00007FF8901CDE20 (coreclr.dll) in dotnet.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

If there is a handler for this exception, the program may be safely continued.
```

See the reproduction here:
https://gist.github.com/ayende/ba61b7d21065c0db8df6a905902ed1b3

Get the files, then run:

* dotnet restore
* dotnet run

The program will crash immediately on trying to do SSL authentication.
Note that if I change this line:

https://gist.github.com/ayende/ba61b7d21065c0db8df6a905902ed1b3#file-project-json-L10

To `      "version": "1.0.1"` it works as expected.

If running this inside the debugger, I get:

```
An unhandled exception of type 'System.ExecutionEngineException' occurred in System.Private.CoreLib.ni.dll
```

And the error seems to be from here:

![image](https://cloud.githubusercontent.com/assets/116915/22938180/a728c8da-f2e3-11e6-948f-bd93403acb39.png)

**Comment by Priya91** [comment]
Looking at the callstack the AV is happening while trying to build the certificate. @bartonjs Any ideas if this is the same as #13814?

@ayende if it's the same issue, you can try the workaround specified in the issue #13814

**Comment by bartonjs** [comment]
Yep. https://github.com/dotnet/core/blob/master/release-notes/1.1/1.1-known-issues.md#systemexecutionengineexception-in-systemsecuritycryptographyx509cerificatesdll-on-windows

(The workaround is the last item on that page, which is where the anchor points... but browsers + big windows + small text = ambiguous visual reference)
