### ISSUE TITLE
Add System.Diagnostics.Activity.RootId property

### ISSUE THREAD

**Issue by lmolkova** [dotnet/corefx#16155]
# Motivation
System.Diagnostics.Activity.Id is unique identifier which may be used to filter logs related to particular activity.
Id has hierarchical structure: /root-id.id1.id2.id2 and generated when activity starts internally.

Root node of id (root-id) is common for all activities involved in operation processing, so logging systems may filter logs with Id prefix. However some logging systems may not support prefix-based queries or it may be quite expensive to run them.

The standard approach to correlate logs is to write some correlation-id with every record. We expect many customers may want to add such correlation-Id to the Activity.Baggage; which would be redundant since root-id serves the same purpose.

We want to provide property to expose root-id and avoid unnecessary baggage usage.

# API proposal 
```C#
public partial class Activity
{
     public string RootId {get; private set}
}
```

# Usage
```C#
void OnIncomingRequest(DiagnoticListener httpListener,  HttpRequest request)
{
   if (httpListener.IsEnabled("Http_In") )
   {
       Activity activity = new Activity("Http_In");
       activity.SetParentId(request.Headers["Request-Id"]);
       if (httpListener.IsEnabled("Http_In", request, activity) )
       { 
            httpListener.StartActivity(activity);
       }
  }
}
...

//client code
DiagnosticListener.AllListeners.Subscribe(delegate (DiagnosticListener listener)
{
   if (listener.Name == "Microsoft.AspNetCore")
   {
       listener.Subscribe(delegate (KeyValuePair<string, object> value)
       {
           // In this demo we simply log to the console what things are happening. 
           Console.WriteLine("Event: {0}  Current ID {1} RootID {2}", 
               value.Key, {Activity.Current.Id} {Activity.Current.RootId});
        });
    }
}
```
//cc @vancem

**Comment by karelz** [comment]
@vancem please flip it to api-ready-for-review if you're ok with the proposal, motivation, etc.
cc @valenis

**Comment by vancem** [comment]
This is arguably a convenience routine (it just does string manipulation on the 'ID' property.    However it does make the concept of a RootID more discoverable, and that is the value of having it (more than one customer wanted it).

**Comment by vancem** [comment]
@terrajobst  - this is a minor addition to the API.   Please include anyone who may be interested.   We would like to move forward reasonably quickly.  

To be clear, I want this API.

**Comment by terrajobst** [comment]
Looks good.

For the record, @KrzysztofCwalina doesn't like the name of the type, but hey, he was on the original review :-)
