### ISSUE TITLE
[Win32.Registry] Subkey nesting level

### ISSUE THREAD

**Issue by Maxwe11** [dotnet/corefx#1615]
The following test succeeds under corefx but fails under .NET 4.5.

    const int maxNestedLevel = 508;
    string exceedsNestedSubkeyName = string.Join(@"\", Enumerable.Repeat("a", maxNestedLevel));
    Assert.Throws<IOException>(() => Registry.CurrentUser.CreateSubKey(exceedsNestedSubkeyName));

Actual limit in .NET 4.5 is 509
Actual limit in corefx is 508
According to msdn limit is 510 (https://msdn.microsoft.com/en-us/library/ad51f2dx(v=vs.110).aspx)

**Comment by stephentoub** [comment]
I took a look at this, and there does _not_ appear to be a difference between the desktop and corefx implementations.  Both of them pass when there are 509 parts to the name and fail when there are 510 parts to the name (and there is no length verification being done in the managed code in either implementation, leaving that purely to the OS).  I believe the confusion may stem from the fact that in the corefx tests, the key off of which the subkey is being created is already nested, thus it's not exactly the same as the snippet shown here.  It does look like the MSDN docs are misleading around whether a failure will occur at >= or just > 510.  I'm submitting a PR to clean up the test slightly.
