### ISSUE TITLE
bug: Vector<long> extracting components with a literal leads to incorrect code gen.

### ISSUE THREAD

**Issue by mburbea** [dotnet/corefx#1616]
It appears that if you try to retrieve components of a `Vector<T>` with a constant something wrong is occurring and an incorrect code is generated.
This does not happen when extracting to an array, or when you use a variable (like say through a for-loop). This only happens when you extract literal components.

Here is a simple reproduction.  This happened in VS2015 RC
```csharp

        static bool TestLiterals(Vector<long> vl)
        {
            var v = vl[0];
            var v1 = vl[1];
            var v2 = vl[2];
            var v3 = vl[3];
            return v != 0 || v1 != 0 || v2 != 0 || v3 != 0;
            
        }
        static bool TestLoop(Vector<long> vl)
        {
            for(int i=0; i < Vector<long>.Count; i++)
            {
                var v = vl[i];
                if (v != 0) return true;
            }
            return false;
        }
        static void Main(string[] args)
        {
            var array = new long[4] { 0, 0, 0, 1 };
            var vector = new Vector<long>(array);
            Console.WriteLine(Vector<long>.Count);
            Console.WriteLine(TestLiterals(vector));
            Console.WriteLine(TestLoop(vector));
        }
```
On my i5 broadwell chip it printed:
```
4
False
True
```
This is very much the wrong result. The correct answer should be:
```
4
True
True
```
It's pretty easy to see that both methods should yield the same result. Here is the assembly of the `testliteral` And the error becomes obvious.
```
**00007FFB1E086E20  vmovupd     ymm0,ymmword ptr [rcx]  
00007FFB1E086E25  vmovd       rax,xmm0  **
**00007FFB1E086E2A  vmovupd     ymm0,ymmword ptr [rcx]  
00007FFB1E086E2F  vmovaps     ymm1,ymm0  
00007FFB1E086E34  vpsrldq     ymm1,ymm1,8  
00007FFB1E086E3A  vmovd       rdx,xmm1  **
00007FFB1E086E3F  vmovupd     ymm0,ymmword ptr [rcx]  
00007FFB1E086E44  vmovaps     ymm1,ymm0  
00007FFB1E086E49  vpsrldq     ymm1,ymm1,10h  
00007FFB1E086E4F  vmovd       r8,xmm1  
00007FFB1E086E54  vmovupd     ymm0,ymmword ptr [rcx]  
00007FFB1E086E59  vmovaps     ymm1,ymm0  
00007FFB1E086E5E  vpsrldq     ymm1,ymm1,18h  
00007FFB1E086E64  vmovd       rcx,xmm1  
00007FFB1E086E69  or          rax,rdx  
00007FFB1E086E6C  or          rax,r8  
00007FFB1E086E6F  test        rax,rax  
00007FFB1E086E72  jne         00007FFB1E086E7E  
```
The input vector is in `ymm0` and it is using `ymm1` as its scratch buffer, first copying and then shifting the register by the offset but is trying to pull the component out of `xmm1`!

It appears that the compiler while having some concept of AVX registers, is still confused.

**Comment by mellinoe** [comment]
Could you take a look, @caroleidt ?

**Comment by mburbea** [comment]
Actually, I'm wrong it appears that `ymm0` and `xmm0` mean the same thing on the AVX implementation. *However*, the call to reading it as `xmm0` cause it to zero out the top 128bit (second line of assembly). If I were to rewrite the method as 

```csharp
        static bool TestLiterals(Vector<long> vl)
        {
            var v3 = vl[3];
            var v2 = vl[2];
            var v1 = vl[1];
            var v = vl[0];
            return v != 0 || v1 != 0 || v2 != 0 || v3 != 0;
        }
```
Then everything will work. This is bizarre behavior though.

**Comment by CarolEidt** [comment]
This bug was fixed post-RC - though I'm not sure why the second example would work.  The bug was due to the fact that the vpsrldq instruction operates separately on the two halves of the ymm register - so the upper half must be first extracted to a lower half (xmm) register.  You can see the code for this here: https://github.com/dotnet/coreclr/blob/master/src/jit/simdcodegenxarch.cpp in the method CodeGen::genSIMDIntrinsicGetItem(GenTreeSIMD* simdNode).

**Comment by joshfree** [comment]
I'm closing out this bug since it is fixed in beta7 (which shipped in September) according to @CarolEidt 's comment above; http://blogs.msdn.com/b/webdev/archive/2015/09/02/announcing-availability-of-asp-net-5-beta7.aspx

@mburbea feel free to reactivate if there are still any issues
