### ISSUE TITLE
Move DataSet & DataAdapter out of System.Data.Common

### ISSUE THREAD

**Issue by bricelam** [dotnet/corefx#16165]
It feels like in .NET Standard 1.7/2.0 that `System.Data.Common` is growing beyond just what's required to implement a basic ADO.NET provider.

Talking with @divega, it seems that features like `DataSet` and `DataAdapter` could be split out into a separate contract like `System.Data.DataSet`.

APIs like `DbConnection.GetSchema()` and `DbDataReader.GetSchemaTable()` are a little tricky because they return `DataTable`, but they could be handled with extension methods like the existing `DbDataReaderExtensions` and marker interface `IDbColumnSchemaGenerator`.

cc @roji

**Comment by divega** [comment]
Met with @terrajobst and @bricelam today to discuss this. It seems that `GetSchema()` and `GetSchemaTable()` is the main reason we cannot split `DataSet` from the `System.Data.Common` implementation. New ADO.NET providers are however free to not implement `DataAdapter` and skip support for `DataSet`.

This is won't fix.
