### ISSUE TITLE
Correct behavior of System.Configuration.LocalFileSettingsProvider GetPropertyValues method

### ISSUE THREAD

**Issue by FireAlkazar** [dotnet/corefx#16162]
**Problem description**
Unexpected exception while writing tests for `System.Configuration.LocalFileSettingsProvider` (#15554)

**Details**  
[This line of code](https://github.com/dotnet/corefx/blob/a8dce7c1c905e994c9519e0f26b0497832942a10/src/System.Configuration.ConfigurationManager/src/System/Configuration/LocalFileSettingsProvider.cs#L103) uses `SettingsPropertyValue` constructor and later [this value is added to collection](https://github.com/dotnet/corefx/blob/a8dce7c1c905e994c9519e0f26b0497832942a10/src/System.Configuration.ConfigurationManager/src/System/Configuration/LocalFileSettingsProvider.cs#L167).
The collection of type `SettingsPropertyValueCollection` has a hashtable inside and `SettingsPropertyValue.Name` is used as a key. But `Name` has `null` value and method throws:
```
System.ArgumentNullException: Key cannot be null.
Parameter name: key
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.Hashtable.Add(Object key, Object value)
   at System.Configuration.SettingsPropertyValueCollection.Add(SettingsPropertyValue property)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.ConfigurationTests.LocalFileSettingsProviderTests.GetPropertyValuesTest()  
```
[By this line of code and a comment above](https://github.com/dotnet/corefx/blob/a8dce7c1c905e994c9519e0f26b0497832942a10/src/System.Configuration.ConfigurationManager/src/System/Configuration/LocalFileSettingsProvider.cs#L163), I assume not throwing is a correct behavior.
Also I have found, that before corefx [the Name property was filled automatically after constructor work](https://referencesource.microsoft.com/#system/sys/system/configuration/SettingsPropertyValue.cs,25).

My test looks like this:
```c#
[Fact]
public void GetPropertiesValuesTest()
{
	var settingsContext = new SettingsContext();
	settingsContext["GroupName"] = "GroupNameFoo";
	settingsContext["SettingsKey"] = "SettingsKeyFoo";
	var settingsProperty = new SettingsProperty("PropertyName");
	settingsProperty.Attributes.Add(typeof(UserScopedSettingAttribute), new UserScopedSettingAttribute());
	var settingsPropertyCollection = new SettingsPropertyCollection
	{
		settingsProperty
	};
	var localFileSettingsProvider = new LocalFileSettingsProvider();

	SettingsPropertyValueCollection settingsPropertyValueCollection = localFileSettingsProvider.GetPropertyValues(settingsContext, settingsPropertyCollection);

	Assert.Equal(1, settingsPropertyValueCollection.Count);
	Assert.Equal(null, settingsPropertyValueCollection["PropertyName"].PropertyValue);
}
```  
**Question**
Is throwing a correct behavior or not? What should be test expectation?

cc @JeremyKuhne @dhoehna

**Comment by JeremyKuhne** [comment]
Behavior should match Desktop (4.6.x) generally. This didn't throw there, it shouldn't throw here.

Go ahead and fix the code. Fyi, we should have the ability to directly run the tests against desktop again in the next week or so.

**Comment by karelz** [comment]
@JeremyKuhne can you please add the triage labels as we discussed?
