### ISSUE TITLE
Socket Close sets socket to non-blocking instead of blocking

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#16179]
Socket.cs has a comment at: https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L4847
```
// Go to blocking mode.
```
and the implementation is
```
errorCode = SocketPal.SetBlocking(_handle, false, out willBlock);
```

I don't think Linux supports a non-blocking close, so it won't affect the behavior there. Perhaps it will cause bugs on other platforms, Windows in particular.

**Comment by karelz** [comment]
@tmds what's the concern? Do you have a repro which fails on Windows?

**Comment by tmds** [comment]
@karelz no repro, the comments says: 'blocking' while the code does: 'non-blocking'. Only one can be correct.

**Comment by Priya91** [comment]
@tmds Is the concern here to change the code comment?

**Comment by tmds** [comment]
@davidsh @CIPop @Priya91 
The reference source
```
int nonBlockCmd = 0;
errorCode = UnsafeNclNativeMethods.OSSOCK.ioctlsocket(
                            m_Handle,
                            IoctlSocketConstants.FIONBIO,
                            ref nonBlockCmd);
```
FINBIO doc

> The *argp parameter is a pointer to an unsigned long value. Set *argp to a nonzero value if the nonblocking mode should be enabled, or zero if the nonblocking mode should be disabled. When a socket is created, it operates in blocking mode by default (nonblocking mode is disabled). This is consistent with BSD sockets.


the parameter is set to zero, so the nonblocking mode should be disabled => blocking

**Comment by tmds** [comment]
@davidsh @CIPop @Priya91 can someone take a peek at this? It shouldn't take long to figure out if this is a bug or not. Then we can close the issue.

**Comment by tmds** [comment]
@davidsh @CIPop @Priya91 I see this issue is still open.

When calling Socket.Dispose on a non-blocking Socket:
- .NET Framework: the non-blocking socket is set to 'blocking'
- .NET Core: the non-blocking Socket is set to 'non-blocking'

**Comment by davidsh** [comment]
cc: @stephentoub @karelz

**Comment by Priya91** [comment]
@tmds it's still not clear to me what the ask is here, is this a difference in comment in .NET Core and .NET Framework, or has the code behavior changed from .NET framework to .NET Core? Since you've already looked into this please clarify, to help speed this up.

**Comment by tmds** [comment]
**.NET Core:**

https://github.com/dotnet/corefx/blob/27a43b38f3f599e43d8bf845f6eb0f351da762e2/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L4657-L4663

comment says: // Go to blocking mode. 
code does: SetBlocking(false)

**.NET 4.7:**

https://github.com/Microsoft/referencesource/blob/7de0d30c7c5ef56ab60fee41fcdb50005d24979a/System/net/System/Net/Sockets/Socket.cs#L6225-L6234

comment says: // Go to blocking mode.
code does: FIONBIO=0, // zero if the nonblocking mode should be disabled.

**Comment by tmds** [comment]
@Priya91 from the referenced code and comments
I think
```
 errorCode = SocketPal.SetBlocking(_handle, false, out willBlock); 
```
should be
```
 errorCode = SocketPal.SetBlocking(_handle, true, out willBlock); 
```

**Comment by Priya91** [comment]
Ok, this helps, the .net core behavior is different from .net framework. @davidsh Can you please take a look?

**Comment by karelz** [comment]
@davidsh can you please answer the question above? So that we can close the issue ;) Thanks!

**Comment by davidsh** [comment]
.NET Framework always uses "blocking" for Close().  But that is also related to how someone might set the Socket.LingerState options (i.e. wait until the kernel flushes pending data on the wire). 

https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.lingerstate?view=netframework-4.7#System_Net_Sockets_Socket_LingerState

But in general, the .NET Framework behavior is to set it to blocking for Close.

https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.close?view=netframework-4.7#System_Net_Sockets_Socket_Close

>If you need to call Close without first calling Shutdown, you can ensure that data queued for outgoing transmission will be sent by setting the DontLingerSocket option to false and specifying a non-zero time-out interval. Close will then block until this data is sent or until the specified time-out expires. If you set DontLinger to false and specify a zero time-out interval, Close releases the connection and automatically discards outgoing queued data.

In general, Close() should block.  But the amount of time spent in blocking is dependent on the LingerState setting.

.NET Core should match .NET Framework behavior.  If it doesn't, we should consider it a bug.

**Comment by tmds** [comment]
Closing due to age.

**Comment by weltkante** [comment]
Why was this closed even though it is clearly a bug, marked as such, and was planned for future release?
