### ISSUE TITLE
Standalone packages built from CoreFX should depend on NetStandard.Library and Microsoft.NetCore.App

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#16177]
Seems like CoreFX is still using granular package references for dependencies in both netstandard1.1 and netcoreapp2.0. Why is that? Here's an example of System.Memory:

![image](https://cloud.githubusercontent.com/assets/95136/22962800/1a6e908e-f304-11e6-8d14-d02e49988d22.png)

/cc @weshaggard @ericstj @Petermarcu

**Comment by ericstj** [comment]
That work isn't done yet.  This package was a one off package produced by @mellinoe to unblock some work.

FWIW the only thing that will cahnge for this package is that .NETCoreApp 2.0 will lose the System.Runtime reference.

Were you also expecting NS1.0 to change?  /cc @terrajobst

**Comment by davidfowl** [comment]
@ericstj Both should be changed. We should follow our own guidance here (use the NetStandard.Library package instead of granular references).

**Comment by ericstj** [comment]
@davidfowl I believe the guidance is to not reference NETStandard.Library at all and let it be implicit on the frameworks that support it.  That change is for everything supporting ns2.0 and later.

We could make the NS1.x assets use NETStandard.Library package reference, but that has not been part of the POR as of yet.   @terrajobst and company would need to agree to this and spec it out with respect to desired version of references which packages get the replaced reference, etc.

**Comment by davidfowl** [comment]
>@davidfowl I believe the guidance is to not reference NETStandard.Library at all and let it be implicit on the frameworks that support it. That change is for everything supporting ns2.0 and later.

AFAIK that's the case for projects but not packages produced by projects that target ns 2.0. Those packages I assume also need to work down level so I don't see the package reference going away. Targeting NetStandard.Library 2.0 (the package) still lets you target older netstandard TFMs and there's no implicit references on old project systems (unless we don't care, but I think we do as that's part of the promise).

> We could make the NS1.x assets use NETStandard.Library package reference, but that has not been part of the POR as of yet. @terrajobst and company would need to agree to this and spec it out with respect to desired version of references which packages get the replaced reference, etc.

We need to do this as *everyone* is doing it and it is currently the guidance. Use the library not granular references.

**Comment by weshaggard** [comment]
@ericstj I believe this is done now correct?

**Comment by ericstj** [comment]
Yeah, where we can.  I had to undo it in a few places where packages were part of the implementation closure of NS.L and couldn't introduce a cycle.
