### ISSUE TITLE
[arm32/CI] host packages are not yet available for armel

### ISSUE THREAD

**Issue by hqueue** [dotnet/corefx#16175]
We can not use `-buildArch` and `-RuntimeOS` for armel when building managed code, because armel host packages are not yet available.

For example, we can build managed code for ubuntu.16.04-arm with following options.
`./build-managed.sh -Release -buildArch=arm -RuntimeOS=ubuntu.16.04`

But we can't build for tizen.4.0.0-armel yet, so we build managed code with following workaround command witch restore x64 host packages instead of armel host packages.
`./build-managed.sh -Release`

We use the workaround command for arm32 CI for armel too. (in PR #15900)
Therefore when armel host packages are published, we have to update arm32 CI script for armel to use standard options.

Related issue is tracked at #16174.

@gkhanna79 @jyoungyun

**Comment by weshaggard** [comment]
@hqueue @jyoungyun is this still tracking for ZBB 5/10?

**Comment by jyoungyun** [comment]
After uploading coreclr nupkgs into myget feed, `-buildArch` and `-RuntimeOS` option is avaliable for armel build. So this issue can be closed.

@hqueue Please close this issue.
