### ISSUE TITLE
[arm32/Linux] Remove workaround to prevent armel package restore

### ISSUE THREAD

**Issue by hqueue** [dotnet/corefx#16174]
In PR #16139, we restore packages for x64 (instead of armel), since armel host packages are not yet available (CoreFX has a cyclic dependency on upstack repo for this).

Once Core-Setup publishes packages for Host for Linux Armel (arm32), #16139 should be reverted.

There is a same issue for arm (#15519) which can be closed by now.

Related issue for arm32 CI (Issue #16175): We have to update ARM CI script in #15900 to use standard options for armel to specify architecture when building CoreFX for armel. 

CC @gkhanna79 @weshaggard @ericstj @hqueue @jyoungyun @hseok-oh

**Comment by karelz** [comment]
@hqueue would it be ok to push it to Future milestone, so that we have better idea what we have to ZBB on 5/10? Or do you use the milestone for your own tracking? Thanks!

**Comment by hqueue** [comment]
> @hqueue would it be ok to push it to Future milestone, so that we have better idea what we have to ZBB on 5/10? Or do you use the milestone for your own tracking? Thanks!

@karelz I think `armel` also have same schedule for the release, i.e. May 10, and it is being prepared.

@gkhanna79 @jyoungyun What do you think of it ?

**Comment by gkhanna79** [comment]
If we are tracking armel for 5/10, I think it is fine to keep it in 2.0 as we are doing for anything targeted for that milestone.

**Comment by jyoungyun** [comment]
@karelz @gkhanna79 @hqueue I'm trying to build armel nupkg and if all tizen runtime nupkg are uploaded to myget server, we don't have no workaround code. I will ping again after finishing my job.

**Comment by gkhanna79** [comment]
@jyoungyun Thanks for the update.

**Comment by weshaggard** [comment]
@hqueue @jyoungyun is this still tracking for ZBB 5/10?

**Comment by jyoungyun** [comment]
All workaround code for armel is not necessary and the related codes are already removed at all. So this issue can be closed.
@hqueue Please close this issue.

**Comment by hqueue** [comment]
@jyoungyun Sure :)

Closing this issue, becuase the work around is removed and not necessary anymore.
