### ISSUE TITLE
Missing DbProviderFactory::CreatePermission public method

### ISSUE THREAD

**Issue by EgorBo** [dotnet/corefx#16184]
DbProviderFactory used to have 

`public virtual CodeAccessPermission CreatePermission(PermissionState state)`

now it doesn't: https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/src/System/Data/Common/DbProviderFactory.cs

However, OdbcFactory still have it:
https://github.com/dotnet/corefx/blob/master/src/System.Data.Odbc/src/System/Data/Odbc/OdbcFactory.cs#L51

/cc @marek-safar

**Comment by stephentoub** [comment]
It was removed from Common to remove the dependency on permissions. cc: @weshaggard

The Odbc port is still a work in progress. The code in corefx is effectively a non-functional code dump from reference source at this point.

**Comment by stephentoub** [comment]
Since this was an intentional removal, I believe the issue can be closed.  Please re-open if that's not the case.
