### ISSUE TITLE
Events not fired on inkcanvas after changing InputDeviceTypes

### ISSUE THREAD

**Issue by delahermosa** [dotnet/corefx#16185]
I'm using an inkCanvas in a UWP application, when I change the property InputDeviceTypes events like PointerExited or PointerMoved are not fired anymore, it's a bug or shall I subscribe to different events?

Thanks in advance.

**Comment by danmosemsft** [comment]
@terrajobst do you know where to log issues against XAML?

**Comment by tarekgh** [comment]
@yizhang82 @joshfree do you know who can help with this issue from XAML? Thanks.

**Comment by joshfree** [comment]
@lutzroeder would know

**Comment by tarekgh** [comment]
@lutzroeder could you please help with this one?

**Comment by delahermosa** [comment]
No one can help? 😭

**Comment by tarekgh** [comment]
@lutzroeder please help with this issue.

**Comment by tarekgh** [comment]
@delahermosa sorry for the delay. we'll get back to you soon.

**Comment by walkerduhon** [comment]
@delahermosa Can you tell us more about what you are seeing?  The expected behavior depends on how InkPresenter.InputDeviceTypes is set, what type of input is occurring, and what UIElement you are expecting to receive the Pointer events and how it relates in the XAML tree to the InkCanvas.

**Comment by karelz** [comment]
@walkerduhon is there a better place to move the question/discussion? (forums, other bug db, etc.)

**Comment by stephentoub** [comment]
Closing, as it hasn't received a response in over two years, and the topic isn't actually relevant to this repo.
