### ISSUE TITLE
ServicePointManager in dotnet 1.0.0-preview2-1-003177

### ISSUE THREAD

**Issue by agcos** [dotnet/corefx#16181]
In which assembly can I find `ServicePointManager`?

**Comment by zabulus** [comment]
It's in netstandart 2.0: https://apisof.net/catalog/System.Net.ServicePointManager

**Comment by agcos** [comment]
Thanks @zabulus.

So, does that mean I should be using **.NET Core 1.0.0-preview2-1-003177** and the **.NET Standard 2.0** in my ASP.NET Core application. I am developing in VS Code on macOS and trying to follow [this](https://docs.microsoft.com/en-us/aspnet/core/tutorials/your-first-mac-aspnet) tutorial.

**Comment by karelz** [comment]
.NET Standard 2.0 will be implemented by .NET Core 2.0, which didn't ship yet. You can used daily builds, but it is not RTW quality.
