### ISSUE TITLE
net46 referencing netstandard1.3: 'Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0'

### ISSUE THREAD

**Issue by discostu105** [dotnet/corefx#16206]
Ran into a strange problem and isolated it to the following:

 * ConsoleApp (.NET 4.6, old csproj)
 * ClassLib (netstandard1.3, new csproj)
 * ClassLib uses `System.IO.File`
 * ConsoleApp references ClassLib

When executed, this exception flies: `System.IO.FileNotFoundException: 'Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'
`

Repro:
ConsoleApp:
```
using System;

namespace ConsoleApp6 {
	class Program {
		static void Main(string[] args) {
			Console.WriteLine("hello");
			ClassLibrary1.Class1.CreateFile();
			Console.WriteLine("world");
		}
	}
}
```
ClassLib:
```
using System.IO;

namespace ClassLibrary1 {
	public static class Class1 {
		public static void CreateFile() {
			var f = File.Create("ugl.txt");
		}
	}
}
```
ClassLib: (csproj):
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.3</TargetFramework>
  </PropertyGroup>

</Project>
```

**Comment by discostu105** [comment]
btw: something similar has been reported here: https://github.com/aspnet/EntityFramework/issues/6831 and https://github.com/aspnet/Hosting/issues/801

**Comment by weshaggard** [comment]
@discostu105 can you add a reference to NETStandard.Library package to your net46 console application? It is needed to get the System.IO.FileSystem assembly that is missing.

**Comment by discostu105** [comment]
@weshaggard great, that solved my problem. thanks for super-fast response!

just for the record: when doing the ConsoleApp in the new csproj format (still net46), it did work without adding a reference.

**Comment by weshaggard** [comment]
>when doing the ConsoleApp in the new csproj format (still net46), it did work without adding a reference.

Yes in the new project system we are able to flow the NETStandard.Library package reference automatically so you don't need to do in manually but in the old system the manual referencing is still needed.

**Comment by dkent600** [comment]
adding a reference to NETStandard.Library doesn't work for me.  The problem may be slightly different.  The exception looks like this:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "CheckFileSystemCaseSensitive" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at TypeScript.Tasks.CheckFileSystemCaseSensitive.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

and double-clicking on the exception message takes one to these lines in `Microsoft.TypeScript.targets`:

```
<Target Name="CheckFileSystemCaseSensitive">
    <CheckFileSystemCaseSensitive
       MSBuildThisFileFullPath="$(MSBuildThisFileFullPath)" >
      <Output TaskParameter="IsFileSystemCaseSensitive"  PropertyName="IsFileSystemCaseSensitive" />
    </CheckFileSystemCaseSensitive>
  </Target>
```

where it says that "MSBuildThisFileFullPath is not defined".
