### ISSUE TITLE
Cleanup types duplicated between CoreCLR and CoreFX

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16229]
The following types are implemented in BOTH CoreFX and CoreCLR (corelib).

Generally a type doesn't need to be duplicated. If it has to be in corelib (because other types in corelib need it) it can be removed from CoreFX. 

(Exception, where only a small piece of the type is actually needed in corelib, it can be convenient to leave the full implemention in Corefx - it shares for free and easier to work on there. However the corelib copy should be renamed to avoid confusion (eg Internal prefix))

Need to go through these and de-dupe/rename as appropriate. Note implementations will have diverged so the copies need to be reconciled first. Eg., BitConverter implementations are quite similar, but reformatted and not quite identical implementation.

```

    public static class BitConverter
    public static class Environment
    public interface IServiceProvider
    public abstract class CollectionBase : ICollection, IEnumerable, IList
    public static class StructuralComparisons
    public abstract class KeyedCollection<TKey, TItem> : Collection<TItem>
    public class ReadOnlyDictionary<TKey, TValue> : ICollection, ICollection<KeyValuePair<TKey, TValue>>, IDictionary, IDictionary<TKey, TValue>, IEnumerable, IEnumerable<KeyValuePair<TKey, TValue>>, IReadOnlyCollection<KeyValuePair<TKey, TValue>>, IReadOnlyDictionary<TKey, TValue>
    public enum SearchOption
    public static class RuntimeReflectionExtensions
    public static class CompilerMarshalOverride
    public sealed class SpecialNameAttribute : Attribute
    public static class FormatterServices
    public abstract class SecurityState
public class CountdownEvent : IDisposable
    public sealed class ThreadAbortException : SystemException
   
```

**Comment by danmosemsft** [comment]
Environment is also special.

**Comment by danmosemsft** [comment]
These don't seem even used in corelib so removing should be a no-brainer

```
  public interface IServiceProvider
    public abstract class CollectionBase : ICollection, IEnumerable, IList
    public static class StructuralComparisons
    public static class RuntimeReflectionExtensions
    public static class CompilerMarshalOverride
    public sealed class SpecialNameAttribute : Attribute
public class CountdownEvent : IDisposable
```

**Comment by danmosemsft** [comment]
I'll do the easy ones above.

**Comment by tarekgh** [comment]
@danmosemsft I have moved this to the future milestone as I am not seeing has to be in 2.0. you still welcome to fix it from now :-)

**Comment by danmosemsft** [comment]
Mostly removed by 14207f4d68ec9d16ad88b424bc60c452a30742aa.

Remaining of interest
```
    public static class BitConverter   
 public class ReadOnlyDictionary<TKey, TValue> 
    public enum SearchOption
    public static class FormatterServices
    public abstract class SecurityState
    public sealed class ThreadAbortException : SystemException
   ```

**Comment by danmosemsft** [comment]
Threadabort: https://github.com/dotnet/coreclr/pull/10648

**Comment by danmosemsft** [comment]
SearchOptoin is just a coincidence.

**Comment by jkotas** [comment]
- `BitConverter` - moved to CoreLib earlier for other reasons. Not a problem anymore

- `ReadOnlyDictionary` - should be easy to remove

- `FormatterServices` - people frequently got to this via private reflection (search github - one example from many https://github.com/carlosmunozrodriguez/Minicloner/blob/9e1ce162966b04a62d553f9aebec75703e7ced3d/src/Minicloner/FormatterServices.cs#L12) to workaround the missing API in .NET Core 1.0. We may want to keep this around to ease 1.0 -> 2.0 migration. Add comment about this. Also, can delete everything else from FormatterServices except the GetUninitializedObject method.

- `ThreadAbortException` - Move from corefx to corelib

**Comment by jkotas** [comment]
ThreadAbortException should be fixed for 2.0

**Comment by danmosemsft** [comment]
For `ReadOnlyDictionary` it seems only used on `internal IReadOnlyDictionary<K, V> GetView<K, V>()`. Can that simply be removed? I do'nt know if it's relied on by some interop infrastructure in some way.

**Comment by jkotas** [comment]
> `ReadOnlyDictionary` it seems only used on internal `IReadOnlyDictionary<K, V> GetView<K, V>()`

Hmmm, I have somehow missed this one. It cannot be removed - it is needed by interop. So we can either keep it as is and live with the dup, or move ReadOnlyDictionary to CoreLib.

**Comment by danmosemsft** [comment]
This seems low priority I'll leave it and leave this issue open.

**Comment by tarekgh** [comment]
@danmosemsft could you please mark the issue as Future again when fixing the stuff that need to go in v2?

**Comment by danmosemsft** [comment]
@tarekgh thanks, I agree there's nothing must have for 2.0 here.

**Comment by weshaggard** [comment]
FYI ThreadAbortException currently exists in CoreLib and System.Threading.Thread. I think it should be removed from System.Threading.Thread in corefx now.

**Comment by weshaggard** [comment]
@ericstj should we add support to your VerifyDuplicateTypes (https://github.com/dotnet/corefx/blob/master/pkg/frameworkPackage.targets#L129) target to take System.Private.CoreLib.dll into consideration?

**Comment by tarekgh** [comment]
CC @kouvel for System.Threading.Thread

**Comment by jkotas** [comment]
> I think it should be removed from System.Threading.Thread in corefx now.

Agree: https://github.com/dotnet/corefx/pull/20659

> @ericstj should we add support to your VerifyDuplicateTypes 

Yes, it would be useful

**Comment by stephentoub** [comment]
This is now stale.  Lots of stuff has moved around, been deleted, consolidated, etc.
