### ISSUE TITLE
All Tests failing

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#16223]
> Failure to restore a package: Unable to resolve 'coveralls.io (>= 1.4.0)' for '.NETStandard,Version=v2.0'. [/mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/external/test-runtime/XUnit.Runtime.depproj]

Example: https://github.com/dotnet/corefx/pull/16222

**Comment by hqueue** [comment]
I also experienced same failure now on Ubuntu 14.04-x64.
It can be reproduce when run `./build-managed.sh -release` with newly cloned latest corefx.

I found that last working corefx has `packages/coveralls.io` directory which was restored during build, but I can't restore it with the latest corefx (ee5acbafbafb1128026a96afac3508f494b857e8).

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/pull/16224

**Comment by danmosemsft** [comment]
myget up again.
