### ISSUE TITLE
System.Diagnostics.Tests.ProcessTests.Process_StartTest fail in CI

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#16235]
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/3528/

```
     System.Diagnostics.Tests.ProcessTests.Process_StartTest [FAIL]
13:55:16         System.ComponentModel.Win32Exception : Access is denied
13:55:16         Stack Trace:
13:55:16            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Windows.cs(96,0): at System.Diagnostics.Process.Kill()
13:55:16            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Diagnostics.Process\tests\ProcessTests.netstandard.cs(197,0): at 
```

**Comment by danmosemsft** [comment]
@priya91

**Comment by Priya91** [comment]
Not able to repro this failure, not sure why access is denied is thrown for killing a process. Will try to repro in loop.

**Comment by tarekgh** [comment]
Long ago I heard sometimes when trying to kill the process right after creating it may fail with access denied. Also may be the running machine could have antivirus software acting in the failed case.

**Comment by ViktorHofer** [comment]
> If the call to the Kill method is made while the process is currently terminating, a Win32Exception is thrown for Access Denied.

From http://msdn.microsoft.com/en-us/library/system.diagnostics.process.kill.aspx. Maybe also related.
