### ISSUE TITLE
ZLib fails to load in CI, causing test failures.

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#1623]
I think this may be specific to dci-win-fbld-8.  Look at these failures:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release/438/
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release/437/
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release/432/

We get a BadImageFormatException while trying to load ZLib.

/cc @FiveTimesTheFun @mmitche

**Comment by mmitche** [comment]
Odd.  I'll check it out.

**Comment by mmitche** [comment]
I think we're good now.  Machine has been wiped and redone.
