### ISSUE TITLE
Feature request: integrate PluralizationService in .NET

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/corefx#16257]
Hi,

The [.NET reference source](https://github.com/Microsoft/referencesource) repo, contains the [PluralizationService](https://github.com/Microsoft/referencesource/tree/master/System.Data.Entity.Design/System/Data/Entity/Design/PluralizationService) used by the EF to pluralize class names etc.

Could we see the pluralization service as part of the .NET?
Is there a NuGet package for the .NET reference source?

**Comment by karelz** [comment]
If you want it to be part of EF, please follow up on EF repo: https://github.com/aspnet/EntityFramework
If you want some specific capabilities to brought down to CoreFX, please describe which - don't assume any prior knowledge in the space.

**Comment by weitzhandler** [comment]
Hi,
The `PluralizationService`, is as its name implies, a service that pluralizes or singularizes words.
It consists of a base class that can be implemented in any language, and an implemented class that supports pluralization/singularization in the English language.

Since this service is a very useful service that is already implemented and tested by Microsoft, it would be nice if anyone can facilitate of it.
So my suggestion is it should be brought in the .NET family probably under `System.Text` or some other related namespace.

**Comment by karelz** [comment]
Hmmm, that's an interesting functionality. Why do you think it belongs into BCL? It sounds like very narrow use case. Maybe external NuGet package or EF itself would be better fit ...

**Comment by weitzhandler** [comment]
> Maybe external NuGet package

The idea is it shouldn't be tied to EF at all. However an external NuGet sounds fair, but it would be nice if it becomes official.

**Comment by tarekgh** [comment]
> The idea is it shouldn't be tied to EF at all. However an external NuGet sounds fair, but it would be nice if it becomes official in the .NET repo

why you think so? there are a tons of features that is nice to exist but it doesn't have to be in the .net core. I think what @karelz suggested is more reasonable here.

**Comment by tarekgh** [comment]
I am closing this issue here but feel free to reopen it if you disagree. we can still support you if you need any help with the design as needed. thanks for bringing the issue.
