### ISSUE TITLE
All tests on build 20170217.01 failed to generate the test results

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#16255]
Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170216.03

Most of the tests failed on Debian.82, Fedora.23, OSX.1011, Redhat.72, Ubuntu.1404, Ubuntu.1610, Win10 & SUSE.428.

**Comment by karelz** [comment]
cc @danmosemsft

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/pull/16271
