### ISSUE TITLE
Performance tests erroring out

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#16258]
...or perhaps the instructions are out of date, or I'm missing something (again...).

Attempting to run performance tests is failing with the following error:
```
G:\corefx\src\System.Collections\tests>msbuild /t:build,test /p:configurationgroup=Release /p:osgroup=Windows_NT /p:performance=true

Build FAILED.

"G:\corefx\src\System.Collections\tests\System.Collections.Tests.csproj" (build;test target) (1) ->
(GenerateTestExecutionScripts target) ->
  G:\corefx\Tools\tests.targets(213,5): error MSB4018: The "GenerateTestExecutionScripts" task failed unexpe
ctedly.\r [G:\corefx\src\System.Collections\tests\System.Collections.Tests.csproj]
G:\corefx\Tools\tests.targets(213,5): error MSB4018: System.InvalidOperationException: Please provide at lea
st one test command To execute via the TestCommands property.\r [G:\corefx\src\System.Collections\tests\Syst
em.Collections.Tests.csproj]
G:\corefx\Tools\tests.targets(213,5): error MSB4018:    at Microsoft.DotNet.Build.Tasks.GenerateTestExecutio
nScripts.Execute()\r [G:\corefx\src\System.Collections\tests\System.Collections.Tests.csproj]
G:\corefx\Tools\tests.targets(213,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microso
ft.Build.BackEnd.ITaskExecutionHost.Execute()\r [G:\corefx\src\System.Collections\tests\System.Collections.T
ests.csproj]
G:\corefx\Tools\tests.targets(213,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInsta
ntiatedTask>d__26.MoveNext() [G:\corefx\src\System.Collections\tests\System.Collections.Tests.csproj]
```

(this is occurring on at least this and `System.Threading.Tasks` performance tests, so I'm assuming it's a symptom of a larger problem).
Note that I've built both libraries and tests, in both debug and release (and I feel like the fact I have to do so initially from the project root is a slight infrastructure wart, but hopefully it'll get better...).

**Comment by karelz** [comment]
cc @DrewScoggins @valenis

**Comment by DrewScoggins** [comment]
We are currently in the midst of bringing the performance tests back up.  You can track the progress of the PR [here](https://github.com/dotnet/corefx/pull/15767).  As it currently stands I do not believe that running performance tests works locally.

**Comment by Clockwork-Muse** [comment]
I can get them to run, now it's just the instructions that are out-of-date.
See #9257
