### ISSUE TITLE
RSA.SignData() does not work on Linux

### ISSUE THREAD

**Issue by xplicit** [dotnet/corefx#16260]
I try to sign and verify binary data with RSA CryptoProvider. When I do this on Windows all works as expected, if I do this on Linux signature verification fails. If I sign data on Windows and then verify it on linux then verification works too, so the issue belongs to `SignData()` on Linux
Here is the sample. Is there a workaround to avoid this verification fail?

Linux OS: Ubuntu 16.04
dotnet --version
1.0.0-preview2-1-003177

Program.cs
```cs
using System;
using System.IO;
using System.Security.Cryptography;
using System.Xml;

namespace ConsoleApplication
{
    public class Program
    {
        static readonly RSASignaturePadding padding = RSASignaturePadding.Pkcs1;

        public static void Main(string[] args)
        {
            string pubKey = "<RSAKeyValue><Modulus>wKQuLluF0Lvl5YadBO5DZZXb/IaFVnROgstq1jcOTwbX+xHfmsEf6mr914EHCUvy2qDMJP4YDvxOaGlRBCcxLdRQ34eyqfFLyHu6kvFIngTqkHB8ZyqY4VBme7LRltI6447eqlMGaT6qYevmusVUI57/YBOZ72EObTW6fc285cdainCL54Kv/4C6AjTvgWgX/cv3Nov0nrjbWxFpTiqvBH4uFj6BVpK9n1gD+p/+HaL5LyQY5cgsvCw0s6othnXpw7hpFBlkGWlWudZswRs6+X6aZiBYiNi8jey+SmKq9AjSZO++gGdHbjuRfACt8BcHZx1/8P3YC93NWopXI4V8QQ==</Modulus><Exponent>AQAB</Exponent></RSAKeyValue>";
            string privateKey = "<RSAKeyValue><Modulus>wKQuLluF0Lvl5YadBO5DZZXb/IaFVnROgstq1jcOTwbX+xHfmsEf6mr914EHCUvy2qDMJP4YDvxOaGlRBCcxLdRQ34eyqfFLyHu6kvFIngTqkHB8ZyqY4VBme7LRltI6447eqlMGaT6qYevmusVUI57/YBOZ72EObTW6fc285cdainCL54Kv/4C6AjTvgWgX/cv3Nov0nrjbWxFpTiqvBH4uFj6BVpK9n1gD+p/+HaL5LyQY5cgsvCw0s6othnXpw7hpFBlkGWlWudZswRs6+X6aZiBYiNi8jey+SmKq9AjSZO++gGdHbjuRfACt8BcHZx1/8P3YC93NWopXI4V8QQ==</Modulus><Exponent>AQAB</Exponent><P>7hztVniqA8ef8fQkB0a1Nwd9FnMhdKskamRAk3sDISqWa4HSXx3thxXHGx/DWAgWUWB+nxunsG+rcEkTttT64KLcF39dCzQ2Nk8ObBc6B0rBcRHTQKWaFJRy/mleQ28gzp+FBvVGLXE9UZu26Ksh6no8NCTJJgHGt0XvtaJUDZ8=</P><Q>zxzNdpnbjewotKK2VXXPKlv2N/E7K1ijSTs0Lavm0aw2ccEbec0iTLIJBzyTt6QbM5GT8k9BROytpo0WxF99KRiX9zoezb6D2Wsf0a1tvOsy9ZsFa4HCgzsmNICu9dxEMpsppEr7bnw1NUfCBoJtxyNmA9zL33xItja+Mk3Mah8=</Q><DP>Tgckr0VzUTHFdCAw/kFpeNL3ZrfrqrO6hzK7Bpk0+VVfXXN5YLoJ8E5upLDP7rUXuysH01PYq7SsVWtdDnjUjXBQ91JBRz6g1UMq0rj5xxH0Of1BYNnjmALdfAlDXo24Dn2vtgwCJzoIggmo8q3Bu3i66ct0LwQ9/ijo2HiNWrk=</DP><DQ>xzpLoqTKADGFzo0enAKhb3va02Fnq4CuQcmDndNYS6U/EhnSFk5vihtQd/ebmPFxgR+uk04N2QFa4XWiyu+X9CpGNHliHEQBjOlxSD9t6mbNNFkU05+UvqvtSl/m7XYe3BdJ7VJ7noI4pLIMQDrC4uZ4QYrpSmfBghYSy0zvL70=</DQ><InverseQ>wKQuLluF0Lvl5YadBO5DZZXb/IaFVnROgstq1jcOTwbX+xHfmsEf6mr914EHCUvy2qDMJP4YDvxOaGlRBCcxLdRQ34eyqfFLyHu6kvFIngTqkHB8ZyqY4VBme7LRltI6447eqlMGaT6qYevmusVUI57/YBOZ72EObTW6fc285cdainCL54Kv/4C6AjTvgWgX/cv3Nov0nrjbWxFpTiqvBH4uFj6BVpK9n1gD+p/+HaL5LyQY5cgsvCw0s6othnXpw7hpFBlkGWlWudZswRs6+X6aZiBYiNi8jey+SmKq9AjSZO++gGdHbjuRfACt8BcHZx1/8P3YC93NWopXI4V8QQ==</InverseQ><D>wKQuLluF0Lvl5YadBO5DZZXb/IaFVnROgstq1jcOTwbX+xHfmsEf6mr914EHCUvy2qDMJP4YDvxOaGlRBCcxLdRQ34eyqfFLyHu6kvFIngTqkHB8ZyqY4VBme7LRltI6447eqlMGaT6qYevmusVUI57/YBOZ72EObTW6fc285cdainCL54Kv/4C6AjTvgWgX/cv3Nov0nrjbWxFpTiqvBH4uFj6BVpK9n1gD+p/+HaL5LyQY5cgsvCw0s6othnXpw7hpFBlkGWlWudZswRs6+X6aZiBYiNi8jey+SmKq9AjSZO++gGdHbjuRfACt8BcHZx1/8P3YC93NWopXI4V8QQ==</D></RSAKeyValue>";

            var pub = ExtractFromXml(pubKey);
            var priv = ExtractFromXml(privateKey);

            //byte[] signature = File.ReadAllBytes("signature.bin");
            //byte[] content = File.ReadAllBytes("content.bin");
            var content = new byte[3] {1,2,3};
            
            var signature = Authenticate(content, priv);
            bool result = Verify(content, signature, pub);

            Console.WriteLine("verify={0}", result);
        }

        public static bool Verify(byte[] dataToVerify, byte[] signature, RSAParameters publicKey)
        {
            using (var rsa = RSA.Create())
            {
                rsa.KeySize = 2048;
                rsa.ImportParameters(publicKey);
                var verified = rsa.VerifyData(dataToVerify, signature, HashAlgorithmName.SHA256, padding);
                return verified;
            }
        }

        public static byte[] Authenticate(byte[] dataToSign, RSAParameters privateKey)
        {
            using (var rsa = RSA.Create())
            {
                rsa.KeySize = 2048;
                rsa.ImportParameters(privateKey);

                var signature = rsa.SignData(dataToSign, HashAlgorithmName.SHA256, padding);

                return signature;
            }
        }

        public static RSAParameters ExtractFromXml(string xml)
        {
            var csp = new RSAParameters();
            using (var reader = XmlReader.Create(new StringReader(xml)))
            {
                while (reader.Read())
                {
                    if (reader.NodeType != XmlNodeType.Element)
                        continue;

                    var elName = reader.Name;
                    if (elName == "RSAKeyValue")
                        continue;

                    do {
                        reader.Read();
                    } while (reader.NodeType != XmlNodeType.Text && reader.NodeType != XmlNodeType.EndElement);

                    if (reader.NodeType == XmlNodeType.EndElement)
                        continue;

                    var value = reader.Value;
                    switch (elName)
                    {
                        case "Modulus":
                            csp.Modulus = Convert.FromBase64String(value);
                            break;
                        case "Exponent":
                            csp.Exponent = Convert.FromBase64String(value);
                            break;
                        case "P":
                            csp.P = Convert.FromBase64String(value);
                            break;
                        case "Q":
                            csp.Q = Convert.FromBase64String(value);
                            break;
                        case "DP":
                            csp.DP = Convert.FromBase64String(value);
                            break;
                        case "DQ":
                            csp.DQ = Convert.FromBase64String(value);
                            break;
                        case "InverseQ":
                            csp.InverseQ = Convert.FromBase64String(value);
                            break;
                        case "D":
                            csp.D = Convert.FromBase64String(value);
                            break;
                    }
                }

                return csp;
            }
        }
    }
}
```

project.json

```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": { },
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0"
        }
      },
      "imports": "dnxcore50"
    }
  }
}
```

**Comment by bartonjs** [comment]
Your `InverseQ` value is incorrect.

A) `InverseQ` is supposed to be less than `P`.  Your `InverseQ` value is twice as long as `P`.
B) `(Q * InverseQ) % P` should be 1.  Yours is 0.

`tCiWIg9XI/dfdsdLlvQac7xISCQmxLS6WRCoECqC/gab/FJPKy2ZKJs6pJBJmE7yuVA8YihbKyKhuSVhr5/Fi954mrDIFxP+WbUbOQwCX55sfp2xzHUDwCH4U0sgm8RFhhPwTnRpwYyx2vEa2uv3T5m2KqkbEwFveEK4x+ivh2o=` seems to be the correct value for InverseQ for this (P, Q, E) triplet.

With the correct value for `InverseQ` your code now works.

Windows CNG seems to recalculate DP, DQ, and InverseQ (and D) based off of the (P, Q, E) triplet; effectively ignoring any bad input.  OpenSSL has more faith in the user-provided data.  So bad data in => bad data out.

**Comment by xplicit** [comment]
Thanks, it was `Modulus` instead of `InverseQ` and `D` in serialized key, and now it works on both platforms. But shouldn't be there some kind of `ArgumentException` about invalid data, or at least the same output behavior both on Windows and Linux platform? In my opinion the same platform-independent code should work or should fail together for all target platforms. It's difficult to diagnose the cause of the issue when code works on one platform and fails on other, because you can't be sure if you code is right or wrong and have to be changed.

**Comment by bartonjs** [comment]
@xplicit Well, it's difficult.  As a general rule we don't add exceptions to existing codepaths.

Your initial serialized key works on Windows.  It probably works on .NET Framework.  So you could have had this key in your code for quite a while (or a bad key generator/serializer in your code for quite a while).  Now you get the next version of .NET Core and it starts reporting it as invalid.  That tends to upset people.

So the next choice we have is to recompute the parameters ourselves.  This isn't "hard", but it's not computationally cheap.  Maybe we only want to recompute them when they're "wrong".  Okay, so we have to do the not-cheap work of detecting it's wrong, then the not-cheap work of recomputing it.  If we'd been doing this for `d` and we chose the `phi` implementation then we'd take a CNG-generated `d`, recompute it, and then CNG would re-re-compute it.  That's a lot of work for no gain.

The last point there was that really, since we're not doing the RSA math, we're not prepared to make judgment calls on the quality of the key.  Maybe there's a new PKCS#1 v2.5 which has found a new lower bound for `dP` and the next version of OpenSSL or Windows CNG uses that in keygen.  Is it really our place to say that it's "wrong"?

I do feel your pain, though.  If there's an epidemic of bad serialized keys out there maybe we'll need to close the platform gap. But for now I don't think that this will make it past the breaking change bar.

(I'm assuming here that your serialized key errors came from a hand-editing problem (including bad copy/paste).  If that's not the case, please let me know.)

**Comment by xplicit** [comment]
@bartonjs FYI the issue had come from wrong implementation of `ToXmlString` and `FromXmlString` methods. .NET Core does not have these methods and we had to reimplement it to transfer existing .NET codebase to .NET Core. In that custom implementation `Modulus` was wrongly exported instead of `InverseQ`, but this have been worked on windows for a while until the moment when we run the same code on Linux platform.

The purpose of the code is generating JWT tokens (put it there for googling if someone have similar problem)
