### ISSUE TITLE
Can a compiler warning/error be added for unused immutable results?

### ISSUE THREAD

**Issue by StingyJack** [dotnet/corefx#16263]
I was trying to add Using directives to a compilation unit, and eventually got it right after a few days of
looking elsewhere in my code for the problem before discovering the actual trouble spot.

An example for illustration...
```
var ccu = classDecl.SyntaxTree.GetCompilationUnitRoot();
ccu.Usings.AddRange(usingsForThisCompilationUnit); // original attempt
//ccu.Usings.Count = 0

foreach (var u in usingsForThisCompilationUnit)
{
    ccu.Usings.Add(u); // not that either - 2 days later
//ccu.Usings.Count = 0

    ccu.AddUsings(u); // that doesn't work
//ccu.Usings.Count = 0

    ccu.AddUsings(SyntaxFactory.UsingDirective(u.Name)); // not this either
//ccu.Usings.Count = 0

    ccu.WithUsings(new SyntaxList<UsingDirectiveSyntax> {u}); // R# hints this may be a problem
//ccu.Usings.Count = 0
    
    // Stumbling on that R# hint led me to the right path.
    ccu = ccu.WithUsings(new SyntaxList<UsingDirectiveSyntax> { u }); //wait, this doesnt work 
    // either. Not sure if its because not using SyntaxFactory or not. I was happy to be free
    // from frustration at that point.
//ccu.Usings.Count = 0

   ccu = ccu.AddUsings(SyntaxFactory.UsingDirective(u.Name).NormalizeWhitespace());
//ccu.Usings.Count = 1 (it added!!)
}
```
Can we get a compiler warning or error when a new immutable result isnt immediately used in assignment or parameter? 

Can these immutable objects be tagged as such (name, attribute, etc) without having to RTFM or source step? 

Why are there Add() and With() members on an object that is immutable (though not named as such)?

With and add apparently don't do the same thing, yet they are equivalent additive ideas. "This and That"
is the same as "This with That" - you still end up with both. What is the intended difference?

**Comment by benaadams** [comment]
Not sure what types they are; are they readonly structs?

So this issue? (e.g. calling method on readonly struct copies the struct before the call to prevent modification) 
https://codeblog.jonskeet.uk/2014/07/16/micro-optimization-the-surprising-inefficiency-of-readonly-fields/

**Comment by StingyJack** [comment]
The type is [CompilationUnitSyntax](http://www.coderesx.com/roslyn/html/3FB4C78A.htm), and the problem is not really about efficiency of algorithim or struct/class/readonly, but rather "all these things dont work and give no indication they wont, but you can try to use them anyway". 

All those attempts to add usings didnt actually add them - the .Usings.Count remained 0.

If the .Usings property were an ImmutableList or a ReadOnlyCollection, it would be some clue. Likewise if CompilationUnitSyntax had .NewWith() or .CreateWith() instead of With(), otherwise this "gotcha" Is unclear.

**Comment by benaadams** [comment]
Might want to raise it in https://github.com/dotnet/roslyn as its both the compiler that would warn; and the location of the types?

**Comment by danmosemsft** [comment]
I'm going to resolve this as it seems the roslyn repo is the right place. good luck.
