### ISSUE TITLE
SerialPort:  Incomplete BeginX operations prevent timely close/reopen

### ISSUE THREAD

**Issue by willdean** [dotnet/corefx#16261]
There is a long-standing problem in the `SerialPort` interface which has survived the migration to Core.  This delays the closing/disposing of a `SerialPort` which has incomplete `BeginRead/BeginWrite` operations on it.  

This often manifests itself as an inability to open a port immediately after closing it.

Within Core this has given rise to issue #16055 - that issue contains some content from an MS-internal bug database which is useful reference.

Ideally we would fix this at some point, as time-related close-then-reopen failures cause pain in real-life and don't do much good to the reputation of `SerialPort`.  Can be left as up-for-grabs for the moment as I don't really know what's involved in a fix.

**Comment by krwq** [comment]
@willdean do you perhaps still remember the context on this?
Do you mean that Dispose takes a while to finish because it waits for BeginRead/BeginWrite and it waits until the operations complete instead of cancelling them or that Dispose completed but pending operations are still happening and are causing some issues?

**Comment by willdean** [comment]
@krwq I don't think I ever understood it properly, certainly not enough to propose a proper fix.   #16055 does have some quotes from old internal MS bug databases which are about the best context there is.

As far as I remember the issue is that if you close a port while async I/O is pending, then the close takes a while to actually complete properly (i.e. all the way down through the stack) although the Dispose completes immediately.   This is a problem if you immediately try to reopen the port, because the reopen fails.

So it's the second of your two cases.

**Comment by krwq** [comment]
@willdean I believe this should work correctly on Linux after my PR is merged (I got code handling that) but will be testing those scenarios (and cases when someone physically plugs out the cable) more later in case there are some issues I missed.

**Comment by JeremyKuhne** [comment]
It appears that @krwq fixed this, closing.
