### ISSUE TITLE
Intermittent test failure with beta-25015-04 CoreCLR update

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/corefx#16279]
Looks like something in this update is causing an intermittent failure in System.Collections.Generic.Tests.ComparerTests.NullableOfIComparableComparisonsShouldTryToCallLeftHandCompareToFirst.

It will occasionally fail with System.EntryPointNotFoundException. 

This was initially seen on OSX/CentOS but will also happen on Windows.

beta-25014-04 is last known good CoreCLR.

See discussion in #16252.

**Comment by AndyAyersMS** [comment]
Looks like this is caused by dotnet/coreclr#9485. @sivarv can you take a look? We may want to back this change out if the problem/fix is not obvious, since we're falling behind getting coreclr updates into corefx.

To reproduce:

Pull the changes from #16252, build retail corefx. (Below assumes repo is c:\repos\corefx)
Sync your coreclr to master at F686B5F and build CHK

Drop the chk clrjit.dll into the c:\repos\corefx\bin\testhost\netcoreapp-Windows_NT-Release-x64\shared\Microsoft.NETCore.App\9.9.9 directory.

cd to c:\repos\corefx\bin\AnyOS.AnyCPU.Release\System.Collections.Tests\netcoreapp

then run

C:\repos\corefx\bin\testhost\netcoreapp-Windows_NT-Release-x64\\dotnet.exe xunit.console.netcore.exe System.Collections.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests  -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests

This will fail roughly 50% of the time for the buggy clrjit.dll. Issue was usually a corrupted objref in a VSD.

You might try enabling GC stress and cutting down the amount of code to run (eg adding -method System.Collections.Generic.Tests.ComparerTests.NullableOfIComparableComparisonsShouldTryToCallLeftHandCompareToFirst to the above). I didn't have the patience to let that finish.

**Comment by AndyAyersMS** [comment]
PR to undo the impacting change at dotnet/coreclr#9667.

**Comment by sivarv** [comment]
Backed out struct promotion change that was causing intermittent failure. 
https://github.com/dotnet/coreclr/pull/9667
