### ISSUE TITLE
[Feedback] Can not update to .NETCore 1.1.0 after upgrading to Microsoft.NETCore.UniversalWindowsPlatform v5.3.0

### ISSUE THREAD

**Issue by rrelyea** [dotnet/corefx#16275]
Internal bug 385268 & vsfeedback issue 806440
Create UWP project with VS2015 and upgrade UWP package to v5.2.2 Open project in VS2017 RC3 - RC4. Open Manage NuGet packages for solution and check available updates. Microsoft.NETCore.Runtime.CoreCLR v1.1.0 is listed as package available for update. Trying to update fails with error message:
GET https://api.nuget.org/v3/registration1-gz/microsoft.netcore.jit/index.json
OK https://api.nuget.org/v3/registration1-gz/microsoft.netcore.jit/index.json 661ms
Restoring packages for E:\src\tools{Project path and Name}\project.json...
GET https://api.nuget.org/v3-flatcontainer/runtime.win8-arm.microsoft.netcore.jit/index.json
NotFound https://api.nuget.org/v3-flatcontainer/runtime.win8-arm.microsoft.netcore.jit/index.json 533ms
Unable to resolve 'runtime.win8-arm.Microsoft.NETCore.Jit (>= 1.1.0)' for 'UAP,Version=v10.0 (win10-arm)'.
Unable to resolve 'runtime.win8-arm.Microsoft.NETCore.Jit (>= 1.1.0)' for 'UAP,Version=v10.0 (win10-arm-aot)'.
it seems that win7-x86 and win7-x64 versions are available on nuget while arm version of assembly is available only as a preview package

Copied from: https://github.com/NuGet/Home/issues/4643

**Comment by rrelyea** [comment]
@jainaashish (nuget team) found: runtime.win8-arm.microsoft.netcore.jit package isn't available on NuGet.org which is why this update failed. DotNet team needs to look into this and publish this package.

@ericstj

**Comment by karelz** [comment]
Does not look like CoreFX issue, rather like a problem in tooling - @davkean @eerhardt can you please advise where to route it?
cc: @danmosemsft

**Comment by davkean** [comment]
@karelz CoreFX own these packages and the uploading of them.

**Comment by tarekgh** [comment]
@ericstj do you know what is the issue here?

**Comment by ericstj** [comment]
This is actually a coreclr issue and should be moved to that repo. @gkhanna79.

The same issue was hit in 1.0.x that package was hardcoded to use the 1.0.2 packages built out of TFS.

I suspect that the same fix hasn't been made to 1.1.0 and the ARM build of JIT packages is still missing.

In the meantime, don't upgrade CoreCLR or JIT packages.  Just keep the ones brought in by the UWP meta-package.

**Comment by tarekgh** [comment]
Issue moved to [dotnet/coreclr #9694](https://github.com/dotnet/coreclr/issues/9694) via [**ZenHub**](https://www.zenhub.com/)
