### ISSUE TITLE
will target platforms be restricted by the platform compatibility of the CICD environment?

### ISSUE THREAD

**Issue by ghuntley** [dotnet/corefx#1627]
For now and for the foreseeable future the portteam is not blocked in any way by the CICD as focus is on just FreeBSD which fortunately runs really well on Azure. In the past week there have discussions (both corefx/coreclr) about the _possibility_ of targeting platforms which would be incompatible with the current environment:`

- NetBSD, OpenBSD, DragonFlyBSD @  https://github.com/dotnet/corefx/issues/1625 
- Solaris/OpenIndiana/SmartOS @  https://github.com/dotnet/coreclr/issues/803
- AmigaOS @ https://github.com/dotnet/coreclr/issues/917

Q: If teams were to form around these platforms how would the CICD environment/MSFT adapt? 

FYI OpenBSD/DragonFlyBSD/Solaris/OpenIndiana/SmartOS work quite well in vmware environment(s).

edit: issue has been refactored based upon feedback from josteink /akoeplinger

**Comment by josteink** [comment]
My honest opinion is that in the terms of project priority this clearly is a "nice to have", not a "must have".

Currently neither of those platforms have a proven build, nor a team backing them. Lacking CI-infrastructure is not what is hindering progress for these potential ports.

I'm not opposed to increased CI-capabilities and support, but I'd just like to focus the limited energy I/we have on things which currently has a clear path forwards, and instead of addressing things which isn't yet a problem.

Or am I being too negative? I'm honestly not trying to, and not trying to dissuade other ports from being made either. I just don't see the need for this *yet*.

**Comment by ghuntley** [comment]
>Currently neither of those platforms have a proven build, nor a team backing them. Lacking CI-infrastructure is not what is hindering progress for these potential ports. I'd just like to focus the limited energy I/we have on things which currently has a clear path forwards, and instead of addressing things which isn't yet a problem.

Completely agreed. I'm thinking extended _future_ once FreeBSD becomes an afterthought - "of course it runs on FreeBSD!".

The purpose of this issue is to publically track that the CICD environment will limit the available target platforms for corefx/coreclr and determine if/how this restriction will be handled when initivetable someone wants to port to AmigaOS (yes, requested a couple minutes ago - see https://github.com/dotnet/coreclr/issues/917 )

**Comment by akoeplinger** [comment]
I don't think there's anything in the current Jenkins CI environment that blocks these platforms, the fact that they're not available on Azure shouldn't be an issue as the same applies to Mac OSX (afaik they just hooked up some Mac Pro machines that sit in the MS office).

**Comment by ghuntley** [comment]
@akoeplinger excellent point re: osx - was wondering how this was being handled. I'm working off an (what looks like to be a potentially incorrect assumption) that infrastructure by MSFT is azure or nothing.
 no != azure means

**Comment by mmitche** [comment]
Yep, we're not restricting platforms by what we have in Azure.  Furthermore, we do expect to have non-azure assets even for platforms supported in Azure.  I fully expect we will do at least some benchmarking on real hardware.

As you said, the Mac OSX machines today are not hosted in Azure.

**Comment by ghuntley** [comment]
:hotsprings: thanks for the clarification @mmitche
