### ISSUE TITLE
Proposal: LazyInitializer.EnsureInitialized<T>(ref T target, ref object syncLock, Func<T> valueFactory)

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#16274]
### Background

System.Threading.LazyInitializer has several EnsureInitialized overloads that make it safe and easy to lazily initialize a field, e.g.
```C#
private static SomethingExpensive s_expensive;
public static SomethingExpensive Expensive => LazyInitializer.EnsureInitialized(ref s_expensive, () => SomethingExpensive());
```

It has several overloads, that can be split into two groups:
- Optimistic concurrency
- Pessimistic concurrency

```C#
public static class LazyInitializer
{
    // Optimistic
    public static T EnsureInitialized<T>(ref T target) where T : class;
    public static T EnsureInitialized<T>(ref T target, System.Func<T> valueFactory) where T : class;

    // Pessimistic
    public static T EnsureInitialized<T>(ref T target, ref bool initialized, ref object syncLock);
    public static T EnsureInitialized<T>(ref T target, ref bool initialized, ref object syncLock, System.Func<T> valueFactory);
}
```

The optimistic concurrency overloads don't use locks, only interlockeds.  This means you don't need a separate lock object and the first access can be faster, but in a contended initialization situation, you may end up with multiple objects getting created (only one of them will be published/used).

The pessimistic concurrency overloads do use locks, with a double-checked locking pattern.  This means you can be guaranteed to only have one object instantiated in the case of contention, but you also need a separate lock object.

For the pessimistic overloads, all of them work with any T, regardless of whether it's a value type or a reference type, and thus in addition to accepting an object, they also require passing a reference to a bool, which indicates whether the field has been initialized or not.  That's great for value types, but often for reference types that additional Boolean field is unnecessary, as whether it's been initialized is covered by whether the field is null or not.

### Proposal:

We should add the following overload:
```C#
public static T EnsureInitialized<T>(ref T target, ref object syncLock, System.Func<T> valueFactory) where T : class;
```
(the same as one of the existing pessimistic overloads, but without the ref bool, and with a class constraint on T)

This will allow EnsureInitialized to be used in situations where you're using a ref type, want double-checked locking, and don't want/need to have an extra bool field to track initialization, since that can be done via null/non-null of the target field itself.

**Comment by terrajobst** [comment]
Looks good as proposed.

**Comment by WinCPP** [comment]
Came across this while going through 'up for grabs'. Curiosity question: Will there also be a valueFactory-less overload for cases that have heavy lifting default constructor?

```C#
public static T EnsureInitialized<T>(ref T target, ref object syncLock) where T : class;
```

Thanks.

**Comment by stephentoub** [comment]
> Will there also be a valueFactory-less overload for cases that have heavy lifting default constructor?

I don't personally think there's enough value in that, but I don't have a strong preference.

**Comment by karelz** [comment]
Assigning to @WinCPP as he expressed interest to work on it.

**Comment by WinCPP** [comment]
@stephentoub, @karelz Looking at the corefx code structure for System.Threading.LazyInitializer, it looks like actual implementation exists in coreclr repository and corefx class is a facade / forwarder. Is this correct? If yes, then please let me know the process for an approval to add code to coreclr; I think I will need an issue # over there too? I have an implementation this issue in a branch on my fork of coreclr repository [here](https://github.com/WinCPP/coreclr/commit/3f5ae3b81245a3d06f1c79f024968b8ccae671f2).

Between it looks like there are no test cases for LazyInitializer either in coreclr or corefx...

Appreciate your inputs.

**Comment by WinCPP** [comment]
Between, I was able to figure out the way to consume my local changes to coreclr, into corefx by following the steps mentioned by @danmosemsft at following [link](https://github.com/dotnet/corefx/issues/14730#issuecomment-269444567). Except that 'BatchRestorePackages' target didn't work; looks like doesn't exist anymore? But I got the local coreclr packages pulled in using following, after moving Microsoft.NETCore.Runtime.CoreCLR and runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR out of the way in the corefx\packages folder.

```
msbuild /p:OverridePackageSource=D:\coreclr\bin\Product\Windows_NT.x64.Release\.nuget\pkg
```

Hope this is correct way.

**Comment by stephentoub** [comment]
> Looking at the corefx code structure for System.Threading.LazyInitializer, it looks like actual implementation exists in coreclr repository and corefx class is a facade / forwarder. Is this correct?

Correct

> then please let me know the process for an approval to add code to CoreCLR

There is no separate approval needed from an API perspective.  The API review process done in corefx is about the API surfaced, regardless of whether the implementation is in coreclr or corefx.

> Between it looks like there are no test cases for LazyInitializer either in coreclr or corefx

There are, e.g.
https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/LazyTests.cs#L412
though they're currently in the System.Runtime.Tests project rather than the System.Threading.Tests project.  At some point we'll want to move them, just hasn't happened yet.

> I was able to figure out the way to consume my local changes to CoreCLR

Those instructions are out-of-date.  The correct ones are here:
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md#testing-with-private-coreclr-bits

**Comment by WinCPP** [comment]
> Those instructions are out-of-date. The correct ones are here:

I followed the above steps. However, as I mentioned previously, VS IDE still refers to the LazyInitializer.cs meta data source generated from netstandard.dll which doesn't have the new overload. This file has following header

```C#
#region Assembly netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
// D:\corefx\bin\ref\netstandard\netstandard.dll
#endregion
```
Which is why I was wondering if dotnet/standard also needs to be rebuilt because that github project appears to be building all the forwarding dlls? Please advise.

**Comment by WinCPP** [comment]
Sorry. Please ignore above comment. Seems like the System.Runtime.Tests project has different references than System.Threading.Test. Meta data generated in former is correct, the latter one which I was using for new tests seems to have incorrect references. I will move my test cases to System.Runtime.Tests. Thanks!

**Comment by stephentoub** [comment]
> However, as I mentioned previously, VS IDE still refers to the LazyInitializer.cs meta data source generated from netstandard.dll which doesn't have the new overload

What if you build from the command-line?  Did you properly update the ref for System.Threading and rebuild the ref?

**Comment by WinCPP** [comment]
I had posted below comment but felt something is still wrong.. hence deleted it.

"Sorry. Please ignore above comment. Seems like the System.Runtime.Tests project has different references than System.Threading.Test. Meta data generated in former is correct, the latter one which I was using for new tests seems to have incorrect references. I will move my test cases to System.Runtime.Tests."

The overload appears in metadata, but somehow it doesn't show "where T : class" at end of it. I am trying to figure it out. I think I will clean build coreclr followed by corefx. Look like my sandboxes have got utterly messed up.

**Comment by WinCPP** [comment]
Finally... I am able to use the new overload. Actually I had missed writing "where T : class" on the corresponding overload in the corefx facade of LazyInitializer. Now everything is linking up using the steps shared by you... Thanks a tonne!

**Comment by WinCPP** [comment]
@stephentoub I have code ready but following test cases are failing. 

```
System.IO.MemoryMappedFiles.Tests.MemoryMappedViewStreamTests.AllowFinalization
System.Diagnostics.TraceSourceTests.SwitchClassTests.PruneTest
System.Tests.GCTests.KeepAlive

System.Tests.BitConverterTests.StartIndexPlusNeededLengthTooLong
System.Threading.Tasks.Tests.CancellationTokenTests.Bug720327_DeregisterFromWithinACallbackIsSafe_SyncContextTest
```

First three appear to have been addressed in pull request #16454. While I'm digging into the last two failures (which don't appear to be related to my code change), I just wanted to check if they are known issues.

Thanks,
Mandar

**Comment by stephentoub** [comment]
I suggest sync'ing your repo and rebasing your changes on top of the latest.  It sounds like you're missing a revert of some changes.

**Comment by WinCPP** [comment]
@stephentoub It worked. Resyncing coreclr followed by corefx worked. I'm initiating PRs in both repos.
