### ISSUE TITLE
Support OpenSSL 1.1

### ISSUE THREAD

**Issue by omajid** [dotnet/corefx#16296]
[OpenSSL 1.1.0 was released](https://www.openssl.org/news/openssl-1.1.0-notes.html) in August 2016. Various distributions are starting to switch to it now:

- [Arch](https://lists.archlinux.org/pipermail/arch-dev-public/2017-January/028673.html)
- [Debian](https://wiki.debian.org/OpenSSL-1.1)
- [Fedora](https://fedoraproject.org/wiki/Changes/OpenSSL110)

OpenSSL 1.1.0 breaks both API and ABI. There's a large list of APIs that were removed. Most structs were made opaque. As a result .NET Core in general and CoreFx in particular fails to build or run there.

There's an incomplete list of API changes and porting tips available at [the OpenSSL Wiki](https://wiki.openssl.org/index.php/1.1_API_Changes).

**Comment by omajid** [comment]
As an example, the first set of errors look like this:

    /builddir/build/BUILD/dotnetcore-1.1.0/core-bootstrap/tools/dotnet-bootstrap/fedora.26-x64-dotnet/src/corefx/src/Native/Unix/System.Security.Cryptography.Native/openssl.cpp:102:21: error: member access into incomplete type 'X509' (aka 'x509_st')
        if (x509 && x509->cert_info && x509->cert_info->validity)
                        ^
    /usr/include/openssl/ossl_typ.h:119:16: note: forward declaration of 'x509_st'
    typedef struct x509_st X509;
                   ^

**Comment by bartonjs** [comment]
Already open as https://github.com/dotnet/corefx/issues/9855
