### ISSUE TITLE
Several SQLClient tests failed in Jenkins

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16291]
Various OS eg https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_rhel7.2_debug/lastCompletedBuild/testReport/

```
 System.Data.SqlClient.Tests.ExceptionTest.ExceptionTests	1.3 sec	1
 System.Data.SqlClient.Tests.ExceptionTest.IndependentConnectionExceptionTestOpenConnection	2 ms	1
 System.Data.SqlClient.Tests.TcpDefaultForAzureTest.AzureNoProtocolConnectionTest	1 sec	1
 System.Data.SqlClient.Tests.TcpDefaultForAzureTest.NonAzureTcpConnectionTest	0.83 sec	1
 System.Data.SqlClient.Tests.TcpDefaultForAzureTest.NonAzureNoProtocolConnectionTestOnUnix	0.72 sec	1
 System.Data.SqlClient.Tests.TcpDefaultForAzureTest.AzureTcpConnectionTest	0.72 sec	1
```

Looks connection related 
```
MESSAGE:
Assert.True() Failure\nExpected: True\nActual: False
+++++++++++++++++++
STACK TRACE:
at System.Data.SqlClient.Tests.TcpDefaultForAzureTest.AzureNoProtocolConnectionTest() in /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu14.04_debug/src/System.Data.SqlClient/tests/FunctionalTests/TcpDefaultForAzureTest.cs:line 78
```

```
MESSAGE:
Assert.Contains() Failure\nNot found: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections.\nIn value: (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
+++++++++++++++++++
STACK TRACE:
at System.Data.SqlClient.Tests.ExceptionTest.VerifyConnectionFailure[TException](Action connectAction, String expectedExceptionMessage, Func`2 exVerifier) in /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu16.10_debug/src/System.Data.SqlClient/tests/FunctionalTests/ExceptionTest.cs:line 96 at System.Data.SqlClient.Tests.ExceptionTest.ExceptionTests() in /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu16.10_debug/src/System.Data.SqlClient/tests/FunctionalTests/ExceptionTest.cs:line 31
```

is a test server down? Or client issue?

@saurabh500

**Comment by saurabh500** [comment]
These expect a failure and provide a result based on the exception message. They don't expect a server.

**Comment by saurabh500** [comment]
Looking into it. The tests were marked OuterLoop with the comment that it takes long time for the tests to run on some network.

**Comment by saurabh500** [comment]
@danmosemsft How do I check when the failures started happening? And also how do I check for correlation of results on other OS ?

**Comment by danmosemsft** [comment]
I don't have handy right now the general guide to looking at test history in Jenkins, but right now many of the red badges on the main page https://github.com/dotnet/corefx are hitting this. If you go to one of those, click "back to project" on the left, or use the breadcrumbs near the top to get to the actual build (login in top right may help) you can click on 'history' on the left to see the build history. Yo ucan click on each to see why it failed if it did. This is pretty slow though and I can tell you I haven't seen this before.

Also relevant is what changes went in since last time. The one I'm looking at only lists this change
Remove dead string resources (#16284) (commit: 6b4423f) (detail / githubweb)
That's actually by me, so if there's any possibility it's somehow me, let me know and I'll take a look. It didn't look like a string load issue though.

**Comment by danmosemsft** [comment]
Ah, this seems to get history for a test:

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_rhel7.2_debug/lastCompletedBuild/testReport/System.Data.SqlClient.Tests/ExceptionTest/ExceptionTests/history/

So slow - I think the server may be parsing XML on the fly.

**Comment by danmosemsft** [comment]
Yes, they all just now started failing. That makes it likely it's me - but hard to see how. 

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_rhel7.2_debug/lastCompletedBuild/testReport/junit/System.Data.SqlClient.Tests/TcpDefaultForAzureTest/AzureNoProtocolConnectionTest/history/

**Comment by saurabh500** [comment]
I am looking at https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_rhel7.2_debug/106/
This was run at Feb 17, 2017 11:10:39 PM 

Are the timestampts UTC or PT ? 

If it is PT, then the change should have been in 106 as well and it should have failed, but didn't

**Comment by saurabh500** [comment]
I didnt realize that the Jenkins page is showing the changes as well. Clearly the Strings change is not there.

**Comment by danmosemsft** [comment]
Can you repro it locally? If so does it repro without 6b4423?

Or I can take a look.

**Comment by saurabh500** [comment]
The change to System.Data.SqlClient was 
Remove 'using Res = System.SR'. As it requires SR to be in System and in (commit: edcedfb) (detail / githubweb)

Tested by 105 https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_rhel7.2_debug/105/

**Comment by saurabh500** [comment]
It will take me sometime to get into my dev machine to repro this. If you have your dev environment ready, then please go for it. Otherwise I will get to it when I get a chance.

**Comment by danmosemsft** [comment]
I'll try

**Comment by danmosemsft** [comment]
Yes, it's me. I didn't see this `SR.GetResourceString(Enum.GetName(typeof(SniContext)` looks up an enumeration by name in the resx. I'll fix.

Sorry for the noise.

**Comment by stephentoub** [comment]
How did it pass CI?

**Comment by saurabh500** [comment]
OuterLoop test failed. The Exceptions related tests of SqlClient were moved to OuterLoop because they were taking time to fail. 
Is OuterLoop run in CI ?

**Comment by saurabh500** [comment]
From what I know OuterLoop tests are run periodically and not with every PR.

**Comment by saurabh500** [comment]
I have opened https://github.com/dotnet/corefx/issues/16293 to investigate moving the SqlClient Exception tests to Inner Loop

**Comment by stephentoub** [comment]
Right, they're run once a day by default and then on demand. In the future we should explicitly run Outerloop on sweeping changes like the resources removal. Good lesson for the future.

**Comment by danmosemsft** [comment]
Yes, my bad: I had forgotten it was possible to do. I did check it in on Friday, and checked the first Outerloop run in the morning.

**Comment by stephentoub** [comment]
We've all broken things like this :)

**Comment by saurabh500** [comment]
SqlClient has non-conventinoal logic to retrieve strings to translate errors coming from Native SNI. In the end I am just glad that the tests caught this issue. :)

**Comment by danmosemsft** [comment]
OK, PR up. There may be some other break somewhere, I"ll keep an eye out. There were such a huge number of dead strings, I think it's worth the churn.
