### ISSUE TITLE
Add priority queue to generic collections

### ISSUE THREAD

**Issue by Antigroup** [dotnet/corefx#163]
I see the generic collections haven't been incorporating into this project yet, but when that happens, I'd like to contribute a priority queue to the library. It's a pretty commonly used data structure and I'm surprised there isn't one in there already.

What I've got is based on a flat binary heap and either uses items that implement IComparable or takes an IComparer.

**Comment by colombod** [comment]
I totally like @karldodd suggestion, would love to contribute!

**Comment by ebickle** [comment]
Absolutely agree. I have my own person implementation of a priority queue in C#, if we want to use it as a starting point. This is a data structure that's been sorely needed for a long time.

'Priority queue' is the traditional name for the data structure, but if you look at the existing naming conventions for collections in .NET they use more user-friendly names. Perhaps SortedQueue<T>, to match SortedDictionary<TKey, TValue> and SortedSet<T>?

My current API looks a bit like this:
` 
public class PriorityQueue<T>
{
    public PriorityQueue();
    public PriorityQueue(Comparison<T>);
    public PriorityQueue(IComparer<T>);
    public PriorityQueue(IEnumerable<T>);
    public PriorityQueue(IEnumerable<T>, Comparison<T>);
    public PriorityQueue(IEnumerable<T>, IComparer<T>);
    public bool IsEmpty { get; }
    public int Count { get; }
    public void Enqueue(T item);
    public T Dequeue();
    public T Peek();
    public void CopyTo(T[] array, int index);
    public T[] ToArray();
} 
`

**Comment by stephentoub** [comment]
Closing to consolidate with same feature being requested in detail in #574

**Comment by hickford** [comment]
Data structures are the fundamental primitives of algorithm design. It's important for the standard library to have fast reliable well-documented implementations. Otherwise developers waste time reinventing the wheel. 

.NET is desperately missing a priority queue, please add one.

**Comment by colombod** [comment]
I think priority queue are implemented in top of the sorted collection.
