### ISSUE TITLE
Remove unnecessary use of `GetTypeInfo()` in Linq/Expressions/Dynamic, etc..

### ISSUE THREAD

**Issue by VSadov** [dotnet/corefx#16305]
Possibly a dupe.

`GetTypeInfo` patterns like `someType.GetTypeInfo().IsValueType`  were added to workaround initially reduced API surface of `System.Type`.

I think we have most of those APIs back on `System.Type` and it is likely more efficient to call them directly. 
(need to confirm, but it is unlikely that calling via `Sysyem.Type` cost more since as last resort it could just use GetTypeInfo internally, although it is doubtful).

**Comment by JonHanna** [comment]
I'll happily take this issue, especially since I'm likely to have clashing PRs with someone doing this as far as two of the projects listed go, though I'll start with double-checking in case there is some advantage to keeping this as is, first.

**Comment by JonHanna** [comment]
Yeah, there doesn't seem to be any case where going through it gains anything, except the few cases where it's completely necessary. There are a few where it being necessary isn't 100% clear (is it always safe to replace `GetTypeInfo().ImplementedInterfaces` with `GetInterfaces`? I think so but being unsure I'm inclined to leave things as is).

**Comment by JonHanna** [comment]
System.Linq only uses it in tests. They may as well be left as is.

**Comment by jkotas** [comment]
> Is it always safe to replace GetTypeInfo().ImplementedInterfaces with GetInterfaces? 

Check the implementation of the methods to get the answer: https://github.com/dotnet/coreclr/blob/80c30e7dfbe00ab30bb86ba2c0f883130766643e/src/mscorlib/src/System/Reflection/TypeInfo.cs#L181. As you can see, ImplementedInterfaces is a dumb forwarder to GetInterfaces, so it is safe to replace.

**Comment by jkotas** [comment]
#8576 #8577 #8578 #8579 are about similar type cleanup.

**Comment by JonHanna** [comment]
I did check that, but since the method is virtual, it could be overridden. I can't find anything doing so, but absence of evidence and all that.

**Comment by jkotas** [comment]
>  I did check that, but since the method is virtual, it could be overridden

I do not think you need to worry about functional differences. The two methods are meant to return same set.

There may be performance difference: `ImplementedInterfaces` returns enumerable, and so it can be potentially implemented more efficiently. It is not the case in CoreCLR; but it is the case in CoreRT. I would keep the calls to `ImplementedInterfaces` as is for performance reasons.

**Comment by JonHanna** [comment]
The two PRs also mean there's no longer any cases where it's being called a few times in quick succession, which I wanted to clean up one way or another anyway, so the couple of remaining calls aren't a big deal in comparison.

**Comment by JonHanna** [comment]
I jumped on this as the projects listed were those I'm particularly interested in, but the same matter applies elsewhere, and my as well be done more completely.

**Comment by JonHanna** [comment]
Incidentally @VSadov when I was double-checking on the performance impact as I said I would above, the most common case would be for the type to inherit from `TypeInfo` and return itself anyway, so the impact isn't severe (it isn't allocating) but it is still in favour of dropping the call (it is still extra work to get the result, not very likely to be inlined due to the virtual nature, and there's no way for the `TypeInfo` to have some more optimal path since it's the same path). There may be counter-examples, but if there are they won't be as common.

**Comment by karelz** [comment]
@VSadov please use only one area path - see [triage rules](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified)

**Comment by jkotas** [comment]
@karelz So how do you mark issues that apply to multiple area paths?

**Comment by karelz** [comment]
@jkotas If there are truly multiple, we either move it to area-Meta or create multiple bugs. Multiple area paths are more often a mistake than a purpose and lead to unclear responsibilities/follow ups.

**Comment by JonHanna** [comment]
area-Meta is probably the most appropriate, since it is a very cross-cutting case.

**Comment by karelz** [comment]
@JonHanna ok, I see you're working on it, so I will assign it to you.
Thanks for keeping PRs per area/assembly - it is easier to review!

**Comment by JonHanna** [comment]
While I may have missed one somewhere, it seems like all the remaining uses are either:

1. In a project that may be used where `GetTypeInfo` isn't available.
2. A test.
3. Actually making use of the extra members `TypeInfo` provides.
4. Actually `TypeInfo`!

So I think this can be closed now.

**Comment by karelz** [comment]
Closing per @JonHanna's investigation above.

**Comment by roydukkey** [comment]
Just out of curiosity how do solutions compile these changes against netstandard1.4?
