### ISSUE TITLE
[armel][Tizen] Enable CoreFX Pipeline build support for Linux for armel (Tizen)

### ISSUE THREAD

**Issue by hqueue** [dotnet/corefx#16335]
Enable CoreFX Pipeline build support for Linux for armel (Tizen) and publish packages

@gkhanna79 Please assign this to yourself as you requested, because I don't have permission :)

**Comment by weshaggard** [comment]
@hqueue @gkhanna79 is this work done?

**Comment by gkhanna79** [comment]
@jyoungyun is working on it.

**Comment by gkhanna79** [comment]
@jyoungyun Please let me know when this can be closed.

**Comment by jyoungyun** [comment]
@gkhanna79 I don't want to close this issue because I think this is still in progress. But we have a lot of similar issues so if you want to manage them as one, I agree closing other issues.

**Comment by gkhanna79** [comment]
@jyoungyun Can we use https://github.com/dotnet/core-setup/issues/1566 as the main issue to track the bring up of Tizen build/packaging infra?

**Comment by jyoungyun** [comment]
@gkhanna79 Sure :) @hqueue Please close this issue. We will manage the pipeline issue by using dotnet/core-setup#1566.

**Comment by gkhanna79** [comment]
Closing per the discussion above.
