### ISSUE TITLE
Improve code coverage for System.Private.Xml (49.7%)

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16336]
There are ~950 types in here, mostly in the System.Xml namespace. Some have good coverage, many not.

We should reach 80-90% coverage on this.

This is a great opportunity for an external contribution.

https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/Code_Coverage_Report/

**Comment by danmosemsft** [comment]
System.Xml is so huge this might be better broken up into smaller bite size chunks.

**Comment by sepidehMS** [comment]
Closing this.

Broken down to:
https://github.com/dotnet/corefx/issues/16646
https://github.com/dotnet/corefx/issues/16649
https://github.com/dotnet/corefx/issues/16650
https://github.com/dotnet/corefx/issues/16680
https://github.com/dotnet/corefx/issues/16683
