### ISSUE TITLE
Proposal: GCHandle.IsPinned(object)

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#16347]
When writing code that uses unsafe code, APIs like Marshal.UnsafeAddrOfPinnedArrayElement, etc., it's often desirable to be able to assert that the object in question is in fact pinned.  I'd like to see an API that would allow that to be done:
```C#
public struct GCHandle
{
    public static bool IsPinned(object value);
    ...
}
```
Similar to how Monitor.IsEntered is mainly intended to be used in Debug.Asserts, this could then be used in Debug.Asserts as well, e.g.
```C#
Debug.Assert(GCHandle.IsPinned(arr));
IntPtr arrPtr = Marshal.UnsafeAddrOfPinnedArrayElement(arr, 0);
... // pass arrPtr to P/Invoke
```

My understanding is the runtime doesn't currently track enough information to make such a look-up fast, but that's ok for the debug-only purposes for which it is intended.  The runtime could do whatever parts of a GC scan are necessary to determine whether the object is pinned, worst case doing a full GC.

**Comment by willdean** [comment]
This sounds like a great idea to me - who could object to such information being easily available, and it would be great if marshalling services could enforce pinning obligations explicitly.

It does seem to me that if this really did require a GC to find out the information then we would have a situation where a debug build would always GC immediately before marshalled calls which have been protected with these asserts.  This would have the side effect that it would then be much *less* likely to GC *during* the call.   

Could this possibly conceal latent problems with pinning/marshalling which would then only show up during release builds, where the GC was more random?   I guess once all pinning requirements are policed with asserts then there won't be any GC-related bugs during marshalled calls, but it's perhaps worth thinking about.

**Comment by jkotas** [comment]
> that's ok for the debug-only purposes for which it is intended. 

How slow is still ok? Is it ok if this API takes up to 1 ms and stops all threads executing managed code?

I have doubts that this is a good API to have. If you are writing code that has too complex pinning and want to have asserts for it, you can always create your own debug-only hashtable that keeps track of what you have pinned.

**Comment by stephentoub** [comment]
> you can always create your own debug-only hashtable that keeps track of what you have pinned.

You can, at the expense of additional complexity in your own code, e.g.
```C#
fixed (byte* ptr = arr)
{
    ... // use ptr
}
```
becomes either:
```C#
TrackPinning.Add(arr); // annotated as Conditional(DEBUG)
try
{
    fixed (byte* ptr = arr)
    {
        ... // use ptr
    }
}
finally
{
    TrackPinning.Remove(arr); // Conditional(DEBUG)
}
```
or to try to slim it down:
```C#
using (TrackPinning.Add(arr))
{
    fixed (byte* ptr = arr)
    {
        ... // use ptr
    }
}
```
but then Add can't be Conditional(DEBUG), and either way you're relying on the compilers to remove a bunch of cruft for you.  It also won't help between components unless you expose your tracking table between them.

**Comment by danmosemsft** [comment]
Even if it's too slow even for an assert, might it be useful for debugging purposes, in #if FALSE normally?

**Comment by joperezr** [comment]
@stephentoub do you want to add anything more to the proposal or would you like to take this to review?

**Comment by stephentoub** [comment]
I don't have anything to add to the API request.  There's the separate matter of whether there's a good implementation for it.

**Comment by stephentoub** [comment]
With concerns about the implementation and with MemoryHandle similar support that'll cover a common case, I'm closing this for now.
