### ISSUE TITLE
Small bug in JsonObject.Parse

### ISSUE THREAD

**Issue by kunalbabre** [dotnet/corefx#1634]
I came across small issue while trying to use JsonObject.Parse. It Parses the example below even though its not valid json. 

I am using JsonValue.0.6.0\lib\40\Microsoft.Json.dll

```c#
 var jsonString = "{\"title\":\"A\"}{\"title\":\"B\"}";
            
            try
            {
                var obj = JsonObject.Parse(jsonString);
                if (obj != null)
                {
                    //Valid Json do something with it
                    
                }
            }
            catch (FormatException)
            {
                //Invalid Json show error to user 
            }

```

**Comment by svick** [comment]
Are you talking about [`Windows.Data.Json.JsonObject.Parse`](https://msdn.microsoft.com/en-us/library/windows/apps/xaml/windows.data.json.jsonobject.parse.aspx)? I don't think that's part of corefx, so the bug report doesn't belong here.

**Comment by kunalbabre** [comment]
I found it while using System.Json.JsonValue not sure if it belongs to corefx

**Comment by stephentoub** [comment]
@kunalbabre, are you using Silverlight?  Or Mono?  I believe that type is from Silverlight, and isn't actually available in either the .NET Framework 4.5/4.6 nor in CoreFX.  You might consider switching frameworks to another one, such as Json.NET: http://www.newtonsoft.com/json

**Comment by kunalbabre** [comment]
@stephentoub thanks for the suggestion I did actually switched the framework and that solved the issue. I am not using Silverlight Or Mono however documentation below suggest its part of .NET Framework 4.5 [JsonValue.Parse Method] (https://msdn.microsoft.com/en-gb/library/system.json.jsonvalue.parse(v=vs.110).aspx)

Happy to close issue, just wanted to check just in case.

**Comment by stephentoub** [comment]
Looks like it's a package you got from NuGet that is no longer available (http://www.nuget.org/packages/JsonValue), and the docs you linked to suggest they were preview only.  I think it's safe to close this.  Thanks, anyway.

**Comment by kunalbabre** [comment]
Many thanks for looking @stephentoub

**Comment by Petermarcu** [comment]
I'll also follow up and see if we can just get that page removed...
