### ISSUE TITLE
System.Reflection.Metadata throws on big-endian archs

### ISSUE THREAD

**Issue by marek-safar** [dotnet/corefx#16354]
There is an explicit check in System.Reflection.Metadata which blocks Roslyn from working on big endian architectures. Can this be removed/fixed?

https://github.com/dotnet/corefx/blob/c97b6dfa7fa8cb29b12121bc5532597ab1409bb6/src/System.Reflection.Metadata/src/System/Reflection/Metadata/MetadataReader.cs#L91

**Comment by stephentoub** [comment]
cc: @tmat, @nguerrera

**Comment by tmat** [comment]
@marek-safar Not easily. Quite a bit of the reader relies on little-endian operations for perf reasons. What big-endian architectures do you need to support?

**Comment by tmat** [comment]
If we supported big-endian I think we would need to multi-target thru #ifdefs.

**Comment by nguerrera** [comment]
We should avoid ifdefs for this. It will complicate a lot of things, especially packaging. Wouldn't the native code gen could spot the constant expression BitConverter.IsLittleEndian and optimize accordingly?

**Comment by tmat** [comment]
@nguerrera True, if we confirm the code gen eliminates it then I have no issue.

**Comment by stephentoub** [comment]
> Wouldn't the native code gen spot the constant expression BitConverter.IsLittleEndian and optimize accordingly?

Likely by the JIT.  Unlikely by an AOT solution.

**Comment by tmat** [comment]
@stephentoub AOT doesn't do target platform specific optimizations?

**Comment by stephentoub** [comment]
> AOT doesn't do target platform specific optimizations?

How would it know when the code is generated at compile time what the static cctor is going to assign to the Boolean field at run time?

**Comment by tmat** [comment]
I'd expect this property to be treated as an "intrinsic".

**Comment by tmat** [comment]
As should IntPtr.Size be, for example.

**Comment by stephentoub** [comment]
> I'd expect this property to be treated as an "intrinsic".

Sure, if work were done in the compiler to make this work, then of course.  To my knowledge that's not the case today, e.g. I don't believe BitConverter.IsLittleEndian is recognized as an intrinsic by crossgen.

**Comment by jkotas** [comment]
> As should IntPtr.Size be, for example.

`IntPtr.Size` is property that returns constants, and so it "just works". `BitConverter.IsLittleEndian` is static readonly field, not property. static readonly fields require special work to get optimized out completely.

**Comment by tmat** [comment]
I see.

**Comment by marek-safar** [comment]
We support s390x and this is blocking us from using Roslyn compiler on all Mono platforms. Further, I don't think that missing `IsLittleEndian` intrinsic should be blocker to fix this issue.

**Comment by tmat** [comment]
@marek-safar Since the Desktop JIT won't optimize the conditional code away it would regress Roslyn perf on .NET Framework to add little-endian checks. So I'm afraid we will need to use #if def, which makes this messy :(.

**Comment by tmat** [comment]
Besides, we don't have any test infrastructure for big-endian platforms. So the cost is pretty steep at this point.

**Comment by jkotas** [comment]
>I'm afraid we will need to use #if def

You really only need the ifdef in one place around a property that everything else will use, so the code would not look that messy.

So what the plan for this would be? Build two versions: one for desktop that is hardcoded to little endian; and portable one that can be used everywhere else and works on big-endian machines?

> any test infrastructure for big-endian platforms

I would expect that the Mono team would take care of testing this.

**Comment by tmat** [comment]
The code itself won't be messy, it's the build and packaging I am more worried about. We don't ship two different sets of Roslyn binaries for desktop and portable. 

Roslyn might also have some code that assumes little endian architecture. Probably not that perf sensitive though, but still would need to be tested.

**Comment by marek-safar** [comment]
I agree the packaging would be very painful which is why I suggested to avoid the ifdef. I think you are overestimating impact of inlining this field in Roslyn context.

The packaging is messy already because there is no portable version of Roslyn nuget (issue filed some time ago) and every project uses Desktop version but even if we make Roslyn netstandard based we'd still need platform independent System.Reflection.Metadata because nuget does not have concept of little/big endian to embed different endian specific versions of same assembly.

**Comment by jkotas** [comment]
https://github.com/dotnet/corefx/tree/dev/bigendian

**Comment by marek-safar** [comment]
@jkotas @tmat Is there easy way to build desktop compatible version from the source code (version compatible with System.Runtime 4.0.0.0) ?

**Comment by jkotas** [comment]
@ericstj What is the right way to build `netstandard1.1` configuration of System.Reflection.Metadata?

I have tried following https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/project-guidelines.md and run `msbuild /p:BuildConfiguration=netstandard1.1` in src\System.Reflection.Metadata\src. I got a ton of errors about missing System.Runtime, etc.

**Comment by ericstj** [comment]
The thing we document is to do a single build first specifying `-allConfigurations`.

The material thing this does is a build of external for all configurations, so if you wanted something shorter for this case in particular you could do `msbuild external/dir.proj /t:BuildAllConfigurations`.  And a slightly more general case is that then the same for ref.builds, which are needed if you have any references to libraries that currently build in corefx.

**Comment by marek-safar** [comment]
@ericstj Unfortunatelly `-allConfigurations` build does not work either. It fails with
```
corefx/Tools/partialfacades.task.targets(70,5): error : Errors were encountered when generating facade(s). [corefx/src/System.Runtime.InteropServices.WindowsRuntime/src/System.Runtime.InteropServices.WindowsRuntime.csproj]
```

**Comment by jkotas** [comment]
@ericstj Note that Marek is building on Mac. I have run it on my Mac and got the same failure.

**Comment by ericstj** [comment]
That's gotten far enough that you should be able to run msbuild /t:BuildAllConfigurations on the src project you care about and it will build all the configurations (or just build the one you want with /p:BuildConfiguration=netstandard1.1)

The reason for that failure is likely because the wrong System.Private.Corelib is being used to generate that facade.  I'll look into it with https://github.com/dotnet/corefx/issues/16532.

**Comment by krwq** [comment]
@ericstj what's the status on this? can this be closed?

**Comment by jkotas** [comment]
Fixed by https://github.com/dotnet/corefx/pull/16583
