### ISSUE TITLE
System.Memory tests target wrong assembly

### ISSUE THREAD

**Issue by dennisdietrich** [dotnet/corefx#16358]
System.Memory tests target System.Private.CoreLib instead of System.Memory when a type is defined in both assemblies which produces incorrect test results and blocks the creation of new unit tests (e.g. for #16298).

Adding
```csharp
var type = typeof(SpanExtensions);
Console.WriteLine($"Type {type} defined in {type.Assembly.FullName} loaded from {type.Assembly.Location}");

type = typeof(Span<>);
Console.WriteLine($"Type {type} defined in {type.Assembly.FullName} loaded from {type.Assembly.Location}");
```
to a test produces the following output:
```
Type System.SpanExtensions defined in System.Memory, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a loaded from R:\corefx\bin\testhost\netcoreapp-Windows_NT-Debug-x64\shared\Microsoft.NETCore.App\9.9.9\System.Memory.dll
Type System.Span`1[T] defined in System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e loaded from R:\corefx\bin\testhost\netcoreapp-Windows_NT-Debug-x64\shared\Microsoft.NETCore.App\9.9.9\System.Private.CoreLib.ni.dll
```

**Comment by danmosemsft** [comment]
Is this as intended? In the sources csproj:

```
    <IsPartialFacadeAssembly Condition="'$(TargetGroup)' == 'netcoreapp' OR '$(TargetGroup)' == 'uap'">true</IsPartialFacadeAssembly>
...
  <ItemGroup Condition="'$(IsPartialFacadeAssembly)' != 'true'">
    <Compile Include="System\ReadOnlySpan.cs" />
    <Compile Include="System\Span.cs" />
    <Compile Include="System\SpanHelpers.cs" />
    <Compile Include="System\Pinnable.cs" />
  </ItemGroup>
```

What this means is that when building for netcoreapp (which is the default) it will defer (via type forwards) to the implementations in CoreCLR. When those aren't available (eg when building to ship out of band?) it compiles in the implementation in src.

When building src and running tests, the build is netcoreapp so you're seeing this. If yo'ure trying to test a change you made to the copy in src, you need to build as a different configuration (targetgroup). @joperezr what would that be in this case -- netstandard1.0? And if so what would the #if be that @dennisdietrich would wrap the test code in?

**Comment by dennisdietrich** [comment]
@danmosemsft So, are you saying that what I'm seeing when running locally does not happen on the CI machines?

**Comment by danmosemsft** [comment]
The CI and outerloop runs run in various configurations, beyond what you get locally when running with default parameters. So they should test both ways, and we distinguish the tests with #if. What I don't understand is the questins I had above for Joe. That would also tell us what you have to pass to the build to make it use the local copy of Span.

**Comment by joperezr** [comment]
> If yo'ure trying to test a change you made to the copy in src, you need to build as a different configuration (targetgroup). @joperezr what would that be in this case -- netstandard1.0?

Today, we are building 4 different targetGroups for System.Memory which are: netcoreapp, uap, netstandard and netstandard1.0. Two of those configurations will use the Span.cs that lives in corefx(netstandard and netstandard1.0) and the other two will typeforward to coreclr. If you want to build for those targetGroups locally, you can just call `msbuild src\System.Memory\src\System.Memory.csproj /p:TargetGroup=netstandard` and that should build you the right assembly.

**Comment by dennisdietrich** [comment]
@joperezr Thanks for the explanation! And never mind this issue.

**Comment by dennisdietrich** [comment]
@joperezr I'm keeping this issue closed but I need some more assistance getting this to work. So, when I execute ```msbuild System.Memory.Tests.csproj /t:RebuildAndTest /p:TargetGroup=netstandard``` it won't run any tests:
```
CopyFilesToOutputDirectory:
  Copying file from "R:\corefx\bin/obj/AnyOS.AnyCPU.Debug/System.Memory.Tests/netstandard/System.Memory.Tests.dll" to "R:\corefx\bin/AnyOS.AnyCPU.Debug/System.Memory.Tests/netstandard/System.Memory.Tests.dll".
  System.Memory.Tests -> R:\corefx\bin\AnyOS.AnyCPU.Debug\System.Memory.Tests\netstandard\System.Memory.Tests.dll
  Copying file from "R:\corefx\bin/obj/AnyOS.AnyCPU.Debug/System.Memory.Tests/netstandard/System.Memory.Tests.pdb" to "R:\corefx\bin/AnyOS.AnyCPU.Debug/System.Memory.Tests/netstandard/System.Memory.Tests.pdb".
CheckTestPlatforms:
  Skipping tests in System.Memory.Tests because there is no configuration compatible with the current BuildConfiguration.
GenerateTestExecutionScripts:
  Generating R:\corefx\bin//TestDependencies/System.Memory.Tests-.dependencylist.txt
  Test Command lines = call %RUNTIME_PATH%\dotnet.exe xunit.console.netcore.exe System.Memory.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests  -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests
  Wrote Windows-compatible test execution script to R:\corefx\bin/AnyOS.AnyCPU.Debug/System.Memory.Tests/netstandard//RunTests.cmd
Done Building Project "R:\corefx\src\System.Memory\tests\System.Memory.Tests.csproj" (RebuildAndTest target(s)).
```

**Comment by joperezr** [comment]
> So, when I execute msbuild System.Memory.Tests.csproj /t:RebuildAndTest /p:TargetGroup=netstandard it won't run any tests

There are two things going on here. One is that the test project [only has a netcoreapp configuration](https://github.com/dotnet/corefx/blob/master/src/System.Memory/tests/Configurations.props#L5), so we don't have a netstandard one. The second problem, is that even if it did have a netstandard configuration, we haven't finished configuring the tests to run as netstandard or against netstandard yet. However, you could potentially have a workaround locally by commenting out [these two lines](https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/Configurations.props#L7-L8) to force the implementation to build the netstandard library for netcoreapp, building the tree by calling `build.cmd` again, and running the tests against netcoreapp using the following command: `msbuild System.Memory.Tests.csproj /t:RebuildAndTest`

Sadly that's probably your best bet now if you want to run the tests against the netstandard configuration, but we are working on trying to enable your other scenario so that you can call the command you mentioned and get the expected results.

**Comment by dennisdietrich** [comment]
@joperezr Thanks, that did the trick!
