### ISSUE TITLE
Console.KeyAvailable echoes typed key on Linux and macOS

### ISSUE THREAD

**Issue by daviwil** [dotnet/corefx#16352]
I've been using `Console.KeyAvailable` to implement an async `ReadKey` method that waits until a key is available before calling `Console.ReadKey(true)`.  This has been working well on Windows but it breaks down on *NIX because the `Console.KeyAvailable` property causes the typed key to be echoed.  This happens before I have a chance to call `ReadKey` specifying that I don't want it to echo the typed key.

Is this a bug?  If not, is there some way I can tell the console implementation to not echo keys when `KeyAvailable` is used?

/cc @stephentoub

**Comment by stephentoub** [comment]
> This has been working well on Windows but it breaks down on *NIX because the Console.KeyAvailable property causes the typed key to be echoed

KeyAvailable doesn't actually cause the key to be echoed: unlike on Windows where keys aren't echoed until they're consumed, on Unix they're echoed immediately when typed, even before they're consumed.  The only way we have to suppress that is to move the terminal into a no-echo mode, which we do for something like Console.ReadLine, but for an API called at random times like KeyAvailable, we have no place to put the terminal into no-echo mode prior to the user typing.  The only time we could potentially do that would be when the app (or Console potentially) is initialized, but then other things go awry, such as an app you Process.Start essentially inheriting this no-echo mode.  The only solution I'm aware of is to P/Invoke to manually put the terminal into the no-echo mode you need.

**Comment by ianhays** [comment]
>The only time we could potentially do that would be when the app (or Console potentially) is initialized, but then other things go awry, such as an app you Process.Start essentially inheriting this no-echo mode. The only solution I'm aware of is to P/Invoke to manually put the terminal into the no-echo mode you need and then undo it when you're done with that mode.

Forcing it to no-echo for the whole process after initialization seems potentially dangerous as I doubt people will be expecting it. I think that's a behavior I'd rather leave up to the programmer and not force it to be done automatically (or whenever Console is used for the first time).

>The only solution I'm aware of is to P/Invoke to manually put the terminal into the no-echo mode you need and then undo it when you're done with that mode.

So, yeah, that.

**Comment by daviwil** [comment]
Is there an example anywhere of P/Invoking that call?  I see this P/Invoke signature:

https://github.com/dotnet/corefx/blob/ec2a6190efa743ab600317f44d757433e44e859b/src/Common/src/Interop/Unix/System.Native/Interop.ReadStdinUnbuffered.cs#L15

Would it be enough to just copy that?

**Comment by ianhays** [comment]
@daviwil that is a pinvoke to our interop library [here](https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/Native/Unix/System.Native/pal_console.cpp#L109) (where there are also some comments related to this discussion we're having) where we call the actual Unix APIs. You could call pinvoke into our library or pinvoke to the Unix API's that it calls, either way should work assuming you've access to the SystemNative files from your app.

**Comment by stephentoub** [comment]
> You could call pinvoke into our library 

Keep in mind that this is effectively a private function; it just happens to be across a dll boundary and we use a P/Invoke to get to it.  There are no guarantees that this function will continue to exist or exist with the same behavior, as with any private member.  You could certainly P/Invoke to it to prototype against it, but I would recommend not depending on it for production use.

Does your app have any native code?  My recommendation would be to add a similar implementation to your native code and P/Invoke to that.

**Comment by ianhays** [comment]
I'm closing this as it isn't something we would want to modify in CoreFX.

**Comment by rkeithhill** [comment]
This is a bummer for apps where you'd rather not block on ReadKey().  How about adding a ReadKeyAsync() method then?

**Comment by terrajobst** [comment]
@rkeithhill 

Might be reasonable. Please file a separate issue for that.
