### ISSUE TITLE
System.Security.Cryptography.Hashing.Algorithms cannot resolve System.Text.Encoding and System.Threading.Tasks ?

### ISSUE THREAD

**Issue by Bartmax** [dotnet/corefx#1635]
Using beta5 TFMs : dnx451 and dnxcore50

and this is my project.json dependencies:

```
  "dependencies": {
    "BioBook.Data": "1.0.0-*",
    "HtmlMinifier.MiddleWare": "1.0.0-beta5-1000",
    "Microsoft.AspNet.Authentication": "1.0.0-beta5-*",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-beta5-*",
    "Microsoft.AspNet.Diagnostics": "1.0.0-beta5-*",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-beta5-*",
    "Microsoft.AspNet.Hosting": "1.0.0-beta5-*",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta5-*",
    "Microsoft.AspNet.Mvc": "6.0.0-beta5-*",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta5-*",
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta5-*",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta5-*",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta5-*",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta5-*",
    "Microsoft.DataAnnotations": "1.0.0-beta1-*",
    "Microsoft.Framework.CodeGenerators.Mvc": "1.0.0-beta5-*",
    "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-beta5-*",
    "Microsoft.Framework.DependencyInjection": "1.0.0-beta5-*"
  },
  "frameworks": {
    "dnx451": {
      "frameworkAssemblies": {
      }
    },
    "dnxcore50": {
      "dependencies": {

      }
    }
  },
```

When building it returns 2 errors
```
Error		Dependency System.Text.Encoding >= 4.0.0-beta-22830 could not be resolved
Error		Dependency System.Threading.Tasks >= 4.0.0-beta-22830 could not be resolved
```

If I remove Microsoft.AspNet.Mvc.TagHelpers, the error goes away.

Looking at dnu list --details I found that tag helpers doesn't have a dependency for those packages but System.Security.Cryptography.Hashing.Algorithms looks like it has. (it think that package is not open source yet, because a) can't find it. b) https://github.com/dotnet/corefx/issues/836 )

Also, removing Microsoft.AspNet.Mvc.TagHelpers but adding System.Security.Cryptography.Hashing.Algorithms triggers the same errors.

If I explicit add those packages as dependencies the errors goes away
like this:

```
  "dependencies": {
    "System.Text.Encoding": "4.0.10-beta-22830",
    "System.Threading.Tasks": "4.0.10-beta-22830",
    ... 
  },
```

**Note:** I was asked on jabbr.net if I had a Compiler/Preprocess folder with uncommented directives. I do have that folder with one file `RazorPreCompilation.cs` but the code inside that file is commented. Also removing the folder does not fixes the build errors.

Not sure what else I can do/look at but if you need anything else just let me know.

**Comment by ericstj** [comment]
This is a known issue with the packages on the https://www.myget.org/F/aspnetvnext feed.  Those are still using an old process that doesn't include implementation dependencies.  The new packages are showing up on https://www.myget.org/F/dotnet-core and shouldn't have this problem.  /cc @davidfowl

**Comment by joshfree** [comment]
@bartonjs

**Comment by bartonjs** [comment]
@Bartmax Things have substantially changed since this was opened; have things gotten better now, or do you still see problems in our package hierarchies?

**Comment by Bartmax** [comment]
@bartonjs everything's good! thanks.

**Comment by bartonjs** [comment]
@Bartmax Glad to hear it :smile:.
