### ISSUE TITLE
Update repo packageIndexes when we ship releases

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#16363]
We need a process for committing updates to the packageIndexes in various repros when we ship new releases.

corefx/master and standard/master need updates from corefx/release/1.0.0 and corefx/release/1.1.0.  corefx/release/1.1.0 needs updates from corefx/release/1.0.0.

Perhaps this is something maestro can do?

/cc @dagood @chcosta

**Comment by dagood** [comment]
It seems reasonable to me to use Maestro for this. To make sure it's clear, are you talking about having Maestro detect when `release/1.0.0/pkg/.../packageIndexes.json` changes and set off a build that creates a PR to change `master/pkg/.../packageIndexes.json`?

**Comment by danmosemsft** [comment]
@mellinoe @ericstj marked this blocking-release and you made it future. can you fix one way or another

**Comment by ericstj** [comment]
If we don't have an automated way to do it we should at least manually do it, so I want to keep this in 2.0.0 milestone.

**Comment by danmosemsft** [comment]
@ericstj if it's necessary to release, it's milestone 2.0 but I marked post ZBB.

Are you doing this - the manual work? I want to assign someone...

**Comment by ericstj** [comment]
I'll do it, but it cannot be done until we have a stable build of packages.

**Comment by karelz** [comment]
This is old bug, which was supposed to be addressed in 2.0.0. I assume it is not tracking anything actionable at this point, closing.
Feel free to reopen if I am wrong (ideally with more appropriate milestone).
