### ISSUE TITLE
Make System.Reflection.Metadata writer's table sorting stable again

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#16383]
Adding tracking issue for https://github.com/dotnet/corefx/pull/15366#discussion_r101688962

Indeed, there should be tests added because this is easy to miss (as I did in the WIP commit that became part of @davidwrighton's PR).

@tmat Will this break Roslyn's determinism as-is?

**Comment by tmat** [comment]
I think it's about correctness, not determinism. In cases when a table is supposed to be sorted by column A and then by column B.
