### ISSUE TITLE
Support Dedicated Administrator Connection in SqlClient

### ISSUE THREAD

**Issue by sanagama** [dotnet/corefx#16396]
Repro:
1. install SQL Server. I installed SQL Server vNext CTP 1.3 on Ubuntu 16.10 for this repro.
2. enable remote admin connections for your SQL Server per [MSDN documentation](https://msdn.microsoft.com/en-us/library/ms190468.aspx)
3. unzip [dactest.zip](https://github.com/dotnet/corefx/files/795340/dactest.zip) on a computer with .NET Core installed. Again, I used Ubuntu 16.10 for this repro.
4. update username & password in Program.cs as appropriate
5. run: dotnet restore
6. run: dotnet run

Result: receive the exception below:

System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 8 - Protocol not supported)

**Comment by geleems** [comment]
DAC support was added to SqlClient. The PR was https://github.com/dotnet/corefx/pull/18044
