### ISSUE TITLE
missing System.Security.Claims

### ISSUE THREAD

**Issue by HornerGrahame** [dotnet/corefx#1640]
The corefx seem to be missing the System.Security.Claims which will prevent implementation of claim base security on corefx developments; is there any plans to bring this namespace into the corefx to allow support for claims identity?

**Comment by akoeplinger** [comment]
It is listed as "Coming" on [corefx-progress](https://github.com/dotnet/corefx-progress/blob/master/src-diff/README.md).

**Comment by stephentoub** [comment]
It's also already available via NuGet packages as part of .NET Core; as @akoeplinger cites, it's just not open sourced yet.
