### ISSUE TITLE
System.Memory tests don't run on Linux

### ISSUE THREAD

**Issue by dennisdietrich** [dotnet/corefx#16403]
Repo: Run ```../../../Tools/msbuild.sh System.Memory.Tests.csproj /t:RebuildAndTest``` on Linux (e.g. Ubuntu 16.04 LTS)
Expected: System.Memory tests to run
Actual:
```
CheckTestPlatforms:
  Skipping tests in System.Memory.Tests because there is no configuration compatible with the current BuildConfiguration.
GenerateTestExecutionScripts:
  Generating /home/dennisdietrich/Repos/corefx/bin/TestDependencies/System.Memory.Tests-.dependencylist.txt
  Test Command lines = $RUNTIME_PATH/dotnet xunit.console.netcore.exe System.Memory.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests  -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
  Wrote .sh test execution script to /home/dennisdietrich/Repos/corefx/bin/AnyOS.AnyCPU.Debug/System.Memory.Tests/netcoreapp/RunTests.sh
Done Building Project "/home/dennisdietrich/Repos/corefx/src/System.Memory/tests/System.Memory.Tests.csproj" (RebuildAndTest target(s)).
```

**Comment by weshaggard** [comment]
We recently did some work to enable the building of System.Memory on non-windows (see https://github.com/dotnet/corefx/pull/16244) but looks like we missed re-configuring the tests. Can you try  removing the `-Windows_NT` from https://github.com/dotnet/corefx/blob/master/src/System.Memory/tests/Configurations.props#L5 and see if that gets you further?

**Comment by dennisdietrich** [comment]
@weshaggard Thanks. Yes, that gets me further. However, about half of the tests fail. Example:
```
System.SpanTests.SpanTests.IndexOfSequenceNoMatch [FAIL]
   System.IO.FileNotFoundException : Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

   Stack Trace:
         at System.SpanHelpers.IndexOf[T](T& searchSpace, Int32 searchSpaceLength, T& value, Int32 valueLength)
         at System.SpanExtensions.IndexOf[T](Span`1 span, ReadOnlySpan`1 value)
      /home/dennisdietrich/Repos/corefx/src/System.Memory/tests/Span/IndexOfSequence.T.cs(43,0): at System.SpanTests.SpanTests.IndexOfSequenceNoMatch()
```

**Comment by mellinoe** [comment]
Yeah, that part is expected, and it's actually why we disabled the build for now. Some parts of the code rely on `Unsafe`, and that library is disabled outside of Windows because of an issue with ilasm. The ilasm issue has already been fixed, actually, so it's just a matter of time before we can turn all of it back on and remove all the hacks.

**Comment by ahsonkhan** [comment]
> The ilasm issue has already been fixed, actually, so it's just a matter of time before we can turn all of it back on and remove all the hacks.

@mellinoe, is there an issue tracking this separately?

**Comment by mellinoe** [comment]
It's actually already fixed. These tests should be running everywhere now.
