### ISSUE TITLE
Cannot find SslStream in System.Net.Security 4.3.0

### ISSUE THREAD

**Issue by hgupta9** [dotnet/corefx#16404]
I've added the following to my project.json:

> "System.Net.Security": "4.3.0.0"

And yet I get this error on compile.

> SslStream does not exist in the namespace System.Net.Security 

 What am I doing wrong?

To reproduce this please download the [FluentFTP repo ](https://github.com/hgupta9/FluentFTP/)and open this xproj to build for .NET core. The error occurs on [this line](https://github.com/hgupta9/FluentFTP/blob/master/FluentFTP/FtpSocketStream.cs#L200).

**Comment by karelz** [comment]
@hgupta9 the API will be part of .NET Core 2.0. System.Net.Security 4.3.0 was part of .NET Core 1.1.

Check out history: https://github.com/dotnet/corefx/blob/5ccb1e47a8fe954c67026a577af99cb51166e68b/src/System.Net.Security/src/System/Net/Security/SslStream.cs#L36

**Comment by hgupta9** [comment]
So how long do I have to wait for .NET Core 2.0 to be released?

**Comment by hgupta9** [comment]
As per the [roadmap](https://github.com/dotnet/core/blob/master/roadmap.md) SslStream will only be available in beta by Q2 2017 and finally by Q3 2017.
