### ISSUE TITLE
Test System.Diagnostics.Tests.ProcessTests.TestProcessStartTime failed with "Xunit.Sdk.EqualException" in 1.	OuterLoop_Fedora23_release

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#16400]
Configuration: OuterLoop_Fedora23_release ([Build#112](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_fedora23_release/112/testReport/)), Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_fedora23_release/112/testReport/System.Diagnostics.Tests/ProcessTests/TestProcessStartTime/

Message:
~~~
Assert.Equal() Failure\nExpected: 42\nActual: 145
~~~

Stack Trace:
~~~
/mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_release/src/Common/tests/System/Diagnostics/RemoteExecutorTestBase.cs(170,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_release/src/System.Diagnostics.Process/tests/ProcessTests.cs(417,0): at System.Diagnostics.Tests.ProcessTests.TestProcessStartTime()
~~~

**Comment by danmosemsft** [comment]
145 = another SIGCHLD

**Comment by danmosemsft** [comment]
Broke Fedora run.

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_fedora23_release/lastCompletedBuild/testReport/System.Diagnostics.Tests/ProcessTests/TestProcessStartTime/

**Comment by ianhays** [comment]
I'm tracking this failure in https://github.com/dotnet/corefx/issues/16688. Please do not re-open this issue, but instead post any failures in that issue.

The RemoteExecutorConsoleApp isn't available on some fedora runs and it's causing this failure.
