### ISSUE TITLE
Please add portable apps in System.ComponentModel.Annotations package

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/corefx#16402]
Hi,

I'm working on a portable app (Droid, iOS and UWP), and I'm trying to add the package [System.ComponentModel.Annotations](https://www.nuget.org/packages/System.ComponentModel.Annotations).

Apparently, .NET Portable is not supported by that package.

Please add .NET Portable as a target in the System.ComponentModel.Annotations package.

<a href="https://github.com/PrismLibrary/Prism/issues/683"/>

**Comment by ajcvickers** [comment]
@weshaggard We believe that the plan here is that everything more to net standard, which means that we should not make this change. Can you confirm?

**Comment by weitzhandler** [comment]
1. Is DataAnnotations part of netstandard?
2. I thought this repo is for those targets outside the .NET that lacks annotations support, so why not support them all?
3. IValidatableObject?

**Comment by weshaggard** [comment]
@ajcvickers there isn't anything that would block adding a portable version to the System.ComponentModel.Annotations nuget package (assuming it can build against the portable profile). 

DataAnnotations is not part of .NET Standard but does build on top of .NET Standard so it can be consumed via a .NET Standard Library project. 

@ajcvickers as for adding additional APIs that can definitely be done but we should avoid adding an new APIs that don't exist in .NET Framework as that will cause some interesting issues given that this assembly identity ships inbox on .NET Framework.

**Comment by divega** [comment]
> there isn't anything that would block adding a portable version to the System.ComponentModel.Annotations nuget package (assuming it can build against the portable profile).

@weshaggard If I understand correctly, you are saying it would be technically feasible. I believe the question is more about the value of doing anything to support portable given that the platforms mentioned in the initial post (Xamarin and UWP) have .NET Standard support.

**Comment by weshaggard** [comment]
Correct. I leave that up to you guys to decide if there is a scenario you feel needs it.

**Comment by danmosemsft** [comment]
@divega could you set milestone?

**Comment by divega** [comment]
Marking this appropriately so that we don't miss it in the next triage. 

This issue has been looked at before in triage but we wanted to investigate more what it would encompass. My recommendation at this point is to close, since the .NET Standard 2 should cover the desired platforms in timeframe that is not too distant from when the next version of this package will be released.

**Comment by weitzhandler** [comment]
I've set the PCL profile to 44 (I only need UWP, Droid and iOS), now `DataAnnotations` is available in the PCL. I'm closing this issue because I don't find any personal interest on it. Feel free to open anyone.
