### ISSUE TITLE
corefx fails on Arch Linux: Not registered task DownloadFile

### ISSUE THREAD

**Issue by catalin-hritcu** [dotnet/corefx#1641]
I'm not sure whether corefx is supposed to work on Linux at this point, and I have no clue how to build this anyway. Still running `xbuild` in the top directory produces this.
```
[hritcu@detained corefx]$ xbuild
XBuild Engine Version 12.0
Mono, Version 3.12.1.0
Copyright (C) 2005-2013 Various Mono authors

Build started 5/6/2015 2:42:54 PM.
__________________________________________________
Project "/home/hritcu/Temp/corefx/build.proj" (default target(s)):
	Target _RestoreBuildTools:
		Restoring build tools...
: error : Error initializing task DownloadFile: Not registered task DownloadFile.
		Build FAILED.
		Errors:
		/home/hritcu/Temp/corefx/build.proj (default targets) ->
		/home/hritcu/Temp/corefx/dir.targets (_RestoreBuildTools target) ->
			: error : Error initializing task DownloadFile: Not registered task DownloadFile.
			 0 Warning(s)
			 1 Error(s)
		Time Elapsed 00:00:00.0923120
```

**Comment by akoeplinger** [comment]
Compiling with Mono's xbuild is not supported yet. There is ongoing work to make it compile with the open-sourced MSBuild: https://github.com/dotnet/corefx/pull/1601.

**Comment by catalin-hritcu** [comment]
Thanks for the information. I've now also tried to install things with MSBuild, but I still get tons of errors. I think I'll wait until the whole process is stable and documented.

**Comment by JeremyKuhne** [comment]
@akoeplinger Is there a prescribed way to tell if you're running under xbuild in a target?

**Comment by akoeplinger** [comment]
@JeremyKuhne not in a nice way, but a lot of variables contain `xbuild` which you could check for:

> MSBuildBinPath = /usr/lib/mono/xbuild/12.0/bin
MSBuildExtensionsPath = /usr/lib/mono/xbuild
MSBuildExtensionsPath32 = /usr/lib/mono/xbuild
MSBuildExtensionsPath64 = /usr/lib/mono/xbuild
