### ISSUE TITLE
A StringComparision for Alpha-Numeric sort should be added.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#16415]
All the sorting methods we have today are not sensitive to consecutive numeric values. As a result, you tend to get values that are sorted similarly to the following:
* Name1
* Name10
* Name2
* Name3
* Name4
* Name5
* Name6
* Name7
* Name8
* Name9

I propose a new StringComparison pair be added `AlphaNumeric` and `AlphaNumericIgnoreCase`. This would properly weigh consecutive numeric values to produce a sort order similar to the following:
* Name1
* Name2
* Name3
* Name4
* Name5
* Name6
* Name7
* Name8
* Name9
* Name10

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/395?

**Comment by tannergooding** [comment]
Yup. I just didn't search the right terms.
