### ISSUE TITLE
System.IO.FileSystem isn't building correctly for uap

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#16422]
The uap configuration is using the Win32 code paths because EnsureWinRT isn't set to true. We either need to make the WinRT code path build again or remove it if we are going to move it to Win32. 

cc @JeremyKuhne @joperezr

**Comment by JeremyKuhne** [comment]
I'm bringing FileStream up in CoreLib- when that is done I'll make sure the other bits are working here.

**Comment by weshaggard** [comment]
Just remove the explicit setting of EnableWinRT=false in the project https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System.IO.FileSystem.csproj#L13 and fix up the uap build.

**Comment by danmosemsft** [comment]
once fixed please also change this condition in the project in 3 places
`'$(UWPCompatible)' == 'true'">` to `'$(TargetGroup)' == 'uap'`
