### ISSUE TITLE
Memory leak in System.Data.Common.DbCommand

### ISSUE THREAD

**Issue by saarixx** [dotnet/corefx#16439]
DbCommand has memory leaks in ExecuteNonQueryAsync and ExecuteDbDataReaderAsync methods. They dispose CancellationTokenRegistration in "catch" instead of "finally" block:

```c#
    public virtual Task<int> ExecuteNonQueryAsync(CancellationToken cancellationToken)
    {
      if (cancellationToken.IsCancellationRequested)
        return ADP.CreatedTaskWithCancellation<int>();
      CancellationTokenRegistration tokenRegistration = new CancellationTokenRegistration();
      if (cancellationToken.CanBeCanceled)
        tokenRegistration = cancellationToken.Register(new Action(this.CancelIgnoreFailure));
      try
      {
        return Task.FromResult<int>(this.ExecuteNonQuery());
      }
      catch (Exception ex)
      {
        tokenRegistration.Dispose();
        return ADP.CreatedTaskWithException<int>(ex);
      }
    }
```

but must be:

```c#
    public virtual Task<int> ExecuteNonQueryAsync(CancellationToken cancellationToken)
    {
      if (cancellationToken.IsCancellationRequested)
        return ADP.CreatedTaskWithCancellation<int>();
      CancellationTokenRegistration tokenRegistration = new CancellationTokenRegistration();
      if (cancellationToken.CanBeCanceled)
        tokenRegistration = cancellationToken.Register(new Action(this.CancelIgnoreFailure));
      try
      {
        return Task.FromResult<int>(this.ExecuteNonQuery());
      }
      catch (Exception ex)
      {
        return ADP.CreatedTaskWithException<int>(ex);
      }
      finally
      {
          tokenRegistration.Dispose();
      }
    }
```

**Comment by karelz** [comment]
Did you consider submitting PR with the change?

Code reference: https://github.com/dotnet/corefx/blob/c5c75db7c00047d603522fd6e21f350099e09bbb/src/System.Data.Common/src/System/Data/Common/DbCommand.cs#L138-L142

**Comment by stephentoub** [comment]
Already submitted a fix in #16442

**Comment by maxcherednik** [comment]
How does the backporting work? Are there plans to fix it in the old .net?

**Comment by karelz** [comment]
@maxcherednik which "old .net" do you have in mind? The bug fix is in .NET Core since 2.0.

**Comment by maxcherednik** [comment]
@karelz I mean this: https://github.com/Microsoft/referencesource/blob/3b1eaf5203992df69de44c783a3eda37d3d4cd10/System.Data/System/Data/Common/DBCommand.cs#L213

**Comment by karelz** [comment]
That is .NET Framework. If there is enough business impact on customers without reasonable workaround, it could be potentially fixed there. It depends on benefit vs. risk.

**Comment by maxcherednik** [comment]
@karelz hm, that's exactly what I am interested in. I was just wondering how it is working here - so we spotted the issue here, fixed it, all good, but is anyone going to report/fix it there?

**Comment by karelz** [comment]
@maxcherednik if it is impacting your .NET Framework apps significantly where you cannot workaround the limitations, then I would suggest to report it with the impact description.

**Comment by maxcherednik** [comment]
@karelz thank you. Reported it here: https://developercommunity.visualstudio.com/content/problem/272072/memory-leak-in-systemdatacommondbcommand.html

**Comment by karelz** [comment]
@maxcherednik if you don't want the issue to be closed as "does not meet the bar", I would suggest to put there detailed description how it significantly impacts your apps and how there is no workaround.
