### ISSUE TITLE
[API Proposal] Debug.Assert overloads taking bool?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#16448]
## Motivation

For me, it's very frequent to assert something is non-null in a `Debug.Assert`. It is also frequent for me to verify some properties about that thing after asserting it is non-null. For example, if one wants to do a typical validation of array/index/count parameters, you would do

```cs
Foo<T>(T[] array, int index, int count)
{
    Debug.Assert(array != null);
    Debug.Assert(index >= 0 && count >= 0);
    Debug.Assert(array.Length - index >= count);
}
```

Here, we are first asserting the array is non-null and then asserting that there's enough room for `count` using the array's `Length` property. Usually, I like to take advantage of null-conditionals to condense these kinds of asserts:

```cs
Foo<T>(T[] array, int index, int count)
{
    Debug.Assert(index >= 0 && count >= 0);
    Debug.Assert(array?.Length - index >= count);
}
```

This works because `>=` in the second assert does a lifted comparison and returns false if the left side is `null`. Its result is a `bool`, which can be passed to `Debug.Assert` with no problems. In the following example, however, the assert fails to compile:

```cs
void ReadingOperation(Stream stream)
{
    Debug.Assert(stream?.CanRead);
}
```

`stream?.CanRead` returns a `bool?`, which `Debug.Assert` does not know how to handle. This means the user has to have two asserts, one for asserting the stream is non-null and another for asserting it `CanRead`.

## Proposal

Add overloads of `Debug.Assert` accepting a `bool?`. `null` values will be treated as `false`.

```cs
namespace System.Diagnostics
{
    public static class Debug
    {
        [Conditional("DEBUG")] public static void Assert(bool? condition);
        [Conditional("DEBUG")] public static void Assert(bool? condition, string message);
        [Conditional("DEBUG")] public static void Assert(bool? condition, string message, string detailMessage);
        [Conditional("DEBUG")] public static void Assert(bool? condition, string message, string detailMessageFormat, params object[] args);
    }
}
```

I don't know what the last two overloads do since I've never used them before, but I added them for the sake of completion. If they have to be removed from the proposal that's fine with me.

## Implementation

```cs
[Conditional("DEBUG")]
public static void Assert(bool? condition) => Assert(condition.GetValueOrDefault());
```

## Additional notes

xUnit already has `Assert.True` and `Assert.False` overloads that take nullable booleans. See here: https://github.com/xunit/assert.xunit/blob/master/BooleanAsserts.cs#L70

**Comment by jamesqo** [comment]
[Another place where this would help:](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/SortedSet.cs#L702)

```cs
Debug.Assert(Node.IsNonNullRed(parent));
```

Could be changed to

```cs
Debug.Assert(parent?.IsRed);
```

**Comment by am11** [comment]
We can use iff (aka XNOR) for this purpose: `Debug.Assert(parent?.IsRed == true);`.

However, would be nice to have straight-forward `bool?` overload, so I +1'd. :)

**Comment by jamesqo** [comment]
@joperezr I found from [here](https://github.com/dotnet/corefx/blob/0fc0d79b1ffa13d7d865762219d7a6925ce878c7/Documentation/project-docs/issue-guide.md) that you are the area owner for Diagnostics; do you think this API is ready for review?

**Comment by joperezr** [comment]
I'll flag this as ready for review to see what @terrajobst and folks think of this, but personally I kind of feel that there would not be enough value of adding it given that there are other alternatives of doing this.

**Comment by jamesqo** [comment]
@joperezr Thank you for marking this as ready for review.

> but personally I kind of feel that there would not be enough value of adding it given that there are other alternatives of doing this.

It's true that there are other ways of doing this, but I use this method pretty frequently so I feel that concision is key here. It's not like `Debug.Assert` is a method people call at just one place in their code; they have it in multiple places, and a very common assert is to check for null. Adding these overloads will improve the experience for all those places that check for null.

**Comment by karelz** [comment]
API review: We believe that many folks will want `null` to be `false` and many will want `true`. As such, we don't think we should hardcode the default.

API rejected.

Workarounds: `Debug.Assert(stream?.CanSeek ?? false)` or `Debug.Assert(stream != null && stream.CanSeek)`

**Comment by jamesqo** [comment]
@karelz What's a situation where someone would think null is true?

**Comment by karelz** [comment]
What about this: 
* `Debug.Assert(array == null || array.Length > index);` 
* `Debug.Assert(options == null || options.IsValid());`
