### ISSUE TITLE
Error in StreamSocketListener

### ISSUE THREAD

**Issue by Jaedson33** [dotnet/corefx#16468]
The StreamSocketListener isn't running in background.
When that will be solved?

**Comment by davidsh** [comment]
>The StreamSocketListener isn't running in background.

What do you mean by "background"?  What sort of project is this and what platform?  Windows or Linux?

ASP.NET Core, Windows UWP (Store App), Desktop app (.NET Framework) ?

**Comment by stephentoub** [comment]
(I assume it's referring to this UWP type:
https://docs.microsoft.com/en-us/uwp/api/windows.networking.sockets.streamsocketlistener )

**Comment by karelz** [comment]
@Jaedson33 can you share more details about what you mean by "isn't running in background"?
Better repro description (e.g. code snippet) would be appreciated.

**Comment by Jaedson33** [comment]
Here's the code of the background task:
`public async void Run(IBackgroundTaskInstance taskInstance)
{
    var deferral = taskInstance.GetDeferral();
    var detalhes = taskInstance.TriggerDetails as SocketActivityTriggerDetails;
    if (detalhes.SocketInformation.SocketKind == SocketActivityKind.StreamSocketListener)
    {
        try
        {
            var list = detalhes.SocketInformation.StreamSocketListener;
            await list.CancelIOAsync();
            list.TransferOwnership(socketId);
        }
        catch (Exception e)
        {
            throw;
        }
    }
    deferral.Complete();
}
`
And I'm givind System.InvalidOperationException.

**Comment by Jaedson33** [comment]
So can you help me? 😰

**Comment by davidsh** [comment]
This CoreFx repo supports .NET Core APIs and library packages.  Specific WinRT APIs such as Windows.Networking.* are not supported here.

You can ask questions here for WinRT APIs:

https://social.msdn.microsoft.com/Forums/en-US/home

**Comment by Jaedson33** [comment]
Ok ☹ I asked here because there was no answer.

**Comment by karelz** [comment]
Closing as this is external. WinRT APIs are not tracked here.
