### ISSUE TITLE
Possible .NET Core bug?

### ISSUE THREAD

**Issue by brunoklein99** [dotnet/corefx#16469]
The dependencies referencing scope in .NET Core is behaving different than .NET 4.5. For instance, the following projects:

http://i.imgur.com/eEVq3dx.jpg

They are referenced as such:

ClassLibrary1 -> ClassLibrary2 -> ClassLibrary3

So, prior to .NET Core any `public` class within `ClassLibrary2` should be accessible from `ClassLibrary1` but any class within `ClassLibrary3` should not be accessible from `ClassLibrary1`. Since it doesn't directly reference `ClassLibrary3`.

But with .NET Core I can compile this:

```c#
    using ClassLibrary2;
    using ClassLibrary3;
    
    namespace ClassLibrary1
    {
        public class Class1
        {
            public Class1()
            {
                var a = new Class2();//as expected
                var b = new Class3();//what?
            }
        }
    }
```

Is this a bug?

**Comment by mellinoe** [comment]
This is probably a better question for the folks over at https://github.com/dotnet/sdk. I think we've made project references transitive by default recently. It's supposed to make things simpler, although it may have inadvertently caused some confusion in this case.

**Comment by karelz** [comment]
Closing as external per above comment.
