### ISSUE TITLE
API Proposal: Named Multiply and Divide on type TimeSpan

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#16476]
#7175 proposes, and dotnet/coreclr#9804 and #16475 provide `/` and `*` operators for `TimeSpan`.

For all previous operators on `TimeSpan` the policy of [CA2225](https://msdn.microsoft.com/en-us/library/ms182355.aspx) was followed by having named alternative methods for the operation, allowing languages which did not honour operator overloading to use the same functionality. This should be done for the new operators as well.

```C#
namespace System
{
    public struct TimeSpan
    {
        public TimeSpan Multiply(double factor);
        public TimeSpan Divide(double divisor);
        public double Divide(TimeSpan ts);
    }
}
```

Functionally these methods should behave identically to the operators dotnet/coreclr#9804 adds.

**Comment by svick** [comment]
> allowing languages which did not honour operator overloading to use the same functionality

What languages are those? Is it worth adding non-essential functionality just for them, considering it will unnecessarily increase the API surface for the languages that support overloading those operators?

CA2225 seems to have been introduced in .Net 2.0, [when VB.NET apparently didn't support operator overloading](https://msdn.microsoft.com/en-us/library/ms182355(v=vs.80).aspx). I'm not sure it's still relevant today.

**Comment by JonHanna** [comment]
> What languages are those?

The CLS says languages don't have to support operator overloading, so potentially any new CLS-compliant language. (I've seen it suggested that not having such a method isn't CLS compliant in itself, though I can't find such a rule scanning through the CLS rules, so maybe not).

> increase the API surface

One of the downsides of increased API surface is the cognitive impact, but inconsistencies within one are as bad in that regard as more methods. The above occurred to me when implementing `/` and `*` and realising I was introducing an inconsistency.

**Comment by terrajobst** [comment]
Makes sense. We must have missed that in the review.

**Comment by karelz** [comment]
Should be fairly simple to do - up for grabs. Any takers?

**Comment by JonHanna** [comment]
I'll take it. It'll make the work I did on the operators feel more completed ☺

**Comment by karelz** [comment]
Great, thanks!
