### ISSUE TITLE
Expose Hex/Char utilities from System.Text.Encoders.Web as public APIs (on some type)

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefx#1647]
See:
src/System.Text.Encodings.Web/src/System/Text/Encodings/Web/HexUtil.cs

**Comment by karelz** [comment]
@KrzysztofCwalina what is the value of the refactoring? How will customers / our code benefit?

**Comment by KrzysztofCwalina** [comment]
This code is or will be duplicated in other libraries if it's not refactored.

**Comment by karelz** [comment]
I don't quite follow. Can you please provide a bit more detail?
Is it implementation refactoring or API surface refactoring?

**Comment by KrzysztofCwalina** [comment]
The component has internal APIs that could/should be made public, e.g. GetScalarValueFromUtf16, GetUtf8RepresentationForScalarValue. These are general purpose routines that are duplicated in, for example, some of the corfxlab work we are doing.

And so it's implementation refactoring, not API refactoring as these things are not APIs (yet).

**Comment by karelz** [comment]
I see your point now - I misunderstood the title.
In that case we need formal API proposal.

**Comment by AlexGhiondea** [comment]
@KrzysztofCwalina @karelz I am going to track this work under this issue: https://github.com/dotnet/corefx/issues/10013
