### ISSUE TITLE
S.R.CS.Unsafe: Add ReadUnaligned<T> and WriteUnaligned<T>

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#16479]
It is fairly common to read and write unaligned pointers in low-level code. There is no good way to do it today. The options are:

- Slow code that reads one byte at a time
- Non-portable code. Example: https://github.com/dotnet/corefxlab/pull/1251#discussion_r103063503
- Ugly ifdefs or conditional execution. Example: https://github.com/dotnet/coreclr/blob/68f72dd2587c3365a9fe74d1991f93612c3bc62a/src/mscorlib/src/System/IO/UnmanagedMemoryAccessor.cs#L195

This proposal is to add APIs that make it easy to write low-level code that reads and writes from unaligned pointers. 

```c#
public static class Unsafe
{
    public static T ReadUnaligned<T>(void* source);
    public static T ReadUnaligned<T>(ref byte source);
    public static void WriteUnaligned<T>(void* destination, T value);
    public static void WriteUnaligned<T>(ref byte destination, T value);
}
```

It is fairly natural extension of `Unsafe` class. There are existing `Read<T>` and `Write<T>` methods, as well as methods with `Unaligned` suffix.

**Comment by jkotas** [comment]
cc @KrzysztofCwalina

**Comment by mikedn** [comment]
Feel free to assign to me once it passes API review.

**Comment by jakobbotsch** [comment]
Should two `ref byte` overloads also be added for the aligned `Read/Write` APIs?
```
public static class Unsafe
{
    public static T Read<T>(ref byte source);
    public static void Write<T>(ref byte destination, T value);
}
```

**Comment by terrajobst** [comment]
Looks good as proposed.

**Comment by karelz** [comment]
@mikedn ping me when you accept the invitation - I will be able to assign it to you then (GitHub limitation).

**Comment by karelz** [comment]
@jkotas any thoughts on Read/Write overloads? If it is useful, we should move it into separate issue.

**Comment by jkotas** [comment]
I do not think that the (aligned) Read/Write overloads that take ref are useful. If you have aligned `ref T`, you can just read from it directly - no need to have a helper method for it.

**Comment by mikedn** [comment]
@karelz Hmm? I already have issues assigned to me in coreclr, is there something different about corefx?

**Comment by karelz** [comment]
@mikedn sadly, it is per-repo setting (general GitHub behavior, not our choice).

**Comment by jkotas** [comment]
@karelz Is there a good reason why we are not using the dotnet-community groups to manage this? 

That's how we have been doing it coreclr so that we do not have to add everybody per repo. Check https://github.com/dotnet/coreclr/settings/collaboration vs. https://github.com/dotnet/corefx/settings/collaboration .

**Comment by jakobbotsch** [comment]
@jkotas I suppose you mean by using `As`? The overloads would accept `ref byte`, not `ref T`.

**Comment by mikedn** [comment]
@jakobbotsch If you have `ref byte` you can get yourself a `ref T` via `As<byte, T>` and then you don't need any `Read` method. 

And the existing `Read` method is kind of pointless as if you have `void*` then you can use `AsRef<T>` to get a `ref T` you can read from. And when dealing with large value types `AsRef<T>` is possible more efficient because it avoid creating a copy that the JIT may or may not optimize out.
