### ISSUE TITLE
Add expected behavior about user-unhandled errors when running the tests projects in visual studio

### ISSUE THREAD

**Issue by dhoehna** [dotnet/corefx#16483]
# problem
If you run the System.Configuration.ConfigurationManager tests project in visual studio, you will get an error that an error happened in the System.Configuration.ConfigurationManager dll and was not handled by the user.  After two weeks of working with the coreex staff, I found out that this was expected behavior

# solution
There are two solutions
 1. Include that a user needs to either continue when these errors happen, or to disable breaking when an error happens that is user-unhandled.
 2. Add documentation stating that this is expected behavior.

**Comment by ViktorHofer** [comment]
That should be fixed with the recent test changes and the use of VS2019.
