### ISSUE TITLE
System.Diagnostics.Tests.ProcessTests.TestExitTime failed with "TestExitTime is incorrect" on Windows 8.1

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#16489]
Failed test: System.Diagnostics.Tests.ProcessTests.TestExitTime

Configuration: OuterLoop_Windows8.1_debug ([build#115](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug/115/testReport/)).

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug/115/testReport/System.Diagnostics.Tests/ProcessTests/TestExitTime/

Message:
~~~
TestExitTime is incorrect.\r\nExpected: True\r\nActual: False
~~~

Stack Trace:
~~~
at System.Diagnostics.Tests.ProcessTests.TestExitTime() in D:\j\workspace\outerloop_win---bf7c4efa\src\System.Diagnostics.Process\tests\ProcessTests.cs:line 172
~~~

**Comment by joperezr** [comment]
+1 on hit count on [this build](https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/3878/)

**Comment by danmosemsft** [comment]
Windows in both cases. 

```
            DateTime timeBeforeProcessStart = DateTime.UtcNow;
...
            Assert.True(p.WaitForExit(WaitInMS));
            Assert.True(p.ExitTime.ToUniversalTime() >= timeBeforeProcessStart, "TestExitTime is incorrect.");
```

This needs logging added for the two times. @sepidehMS could you real quick add that as I guess @Priya91 has networking test failures to look at?

**Comment by sepidehMS** [comment]
Logging added

**Comment by danmosemsft** [comment]
we caught a fish

https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/3900/consoleText

```
     System.Diagnostics.Tests.ProcessTests.TestExitTime [FAIL]
        TestExitTime is incorrect. TimeBeforeStart=2/28/2017 2:08:18 AM, ExitTime=2/27/2017 6:08:18 PM, ExitTimeUniversal=2/28/2017 2:08:18 AM
        Expected: True
```

Well 2/28/2017 2:08:18 AM >= 2/28/2017 2:08:18 AM so perhaps we need to log the actual ticks.

**Comment by Priya91** [comment]
Thanks @sepidehMS

**Comment by danmosemsft** [comment]
Ian see above I added moer logging. Waiting for next fish.

**Comment by saurabh500** [comment]
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/4000/ 

```
MESSAGE:
TestExitTime is incorrect. TimeBeforeStart 3/2/2017 12:36:40 AM Ticks=636240118007754699, ExitTime=3/1/2017 4:36:40 PM, Ticks=636239830007616500, ExitTimeUniversal 3/2/2017 12:36:40 AM Ticks=636240118007616500, NowUniversal 3/2/2017 12:36:40 AM Ticks=636239830007771376\r\nExpected: True\r\nActual: False
+++++++++++++++++++
STACK TRACE:
at System.Diagnostics.Tests.ProcessTests.TestExitTime() in D:\j\workspace\windows_nt_de---4526f5ff\src\System.Diagnostics.Process\tests\ProcessTests.cs:line 173

```

**Comment by stephentoub** [comment]
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/4038/consoleText
```
System.Diagnostics.Tests.ProcessTests.TestExitTime [FAIL]
        TestExitTime is incorrect. TimeBeforeStart 3/2/2017 3:19:00 PM Ticks=636240647402067596, ExitTime=3/2/2017 7:19:00 AM, Ticks=636240359402016187, ExitTimeUniversal 3/2/2017 3:19:00 PM Ticks=636240647402016187, NowUniversal 3/2/2017 3:19:00 PM Ticks=636240359402150646
        Expected: True
        Actual:   False
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\System.Diagnostics.Process\tests\ProcessTests.cs(179,0): at System.Diagnostics.Tests.ProcessTests.TestExitTime()
```

**Comment by stephentoub** [comment]
(I think it's likely this only started failing recently because we recently made DateTime.UtcNow more precise, so if the test was expecting multiple calls to DateTime.UtcNow in rapid success to produce the exact same result, those flawed expectations may now be more visible.)

**Comment by ianhays** [comment]
>multiple calls to DateTime.UtcNow in rapid succession to produce the exact same result, those flawed expectations may now be more visible

That'll do it, yeah. I'll push a fix so we this test stops breaking things.
