### ISSUE TITLE
InnerLoop_Fedora24_Debug: Test "System.Diagnostics.Tests.ProcessStreamReadTests.TestSyncErrorStream" failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#16488]
Failed test: System.Diagnostics.Tests.ProcessStreamReadTests.TestSyncErrorStream 

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/fedora24_debug/1140/consoleText

Configuration: InnerLoop_Fedora24_Debug ([build#1140](https://ci.dot.net/job/dotnet_corefx/job/master/job/fedora24_debug/1140/testReport/))

Message:
~~~
System.Diagnostics.Tests.ProcessStreamReadTests.TestSyncErrorStream [FAIL]
        Assert.Equal() Failure
                  ↓ (pos 0)
        Expected: RemoteExecutorConsoleApp.exe started erro···
        Actual:   Did you mean to run dotnet SDK commands? ···
                  ↑ (pos 0)
~~~

Stack Trace:
~~~
/mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/src/System.Diagnostics.Process/tests/ProcessStreamReadTests.cs(23,0): at System.Diagnostics.Tests.ProcessStreamReadTests.TestSyncErrorStream()
~~~

**Comment by Jiayili1** [comment]
This issue is repro, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/fedora24_debug/1151/testReport/System.Diagnostics.Tests/ProcessStreamReadTests/TestSyncErrorStream/

**Comment by danmosemsft** [comment]
@ianhays were you taking these ones?

**Comment by ianhays** [comment]
>@ianhays were you taking these ones?

Yeah I'll take a look. I missed this one since it was mislabeled.

**Comment by ianhays** [comment]
I'm tracking this failure in https://github.com/dotnet/corefx/issues/16688. Please do not re-open this issue, but instead post any failures in that issue.

The RemoteExecutorConsoleApp isn't available on some fedora runs and it's causing this failure.
