### ISSUE TITLE
Validating a DiagnosticSource/Activity based 3rd party tracer and an OpenTracing bridge

### ISSUE THREAD

**Issue by cwe1ss** [dotnet/corefx#16491]
I'm trying to figure out how the new `Activity` API should be used in a tracer (e.g. Application Insights) or in an OpenTracing bridge. 

@lmolkova @vancem It would be great if you could provide your feedback here. Maybe it results in some insights for the current API.

I will start with some basic questions and I will add further questions once I have a better understanding, if that's ok for you.

### Executing code on Start and Stop for *all* activities
I think a tracer should be unaware of actual operation names like "Http_In" etc. Instead, the tracer should have a mode where it automatically picks up *all* activities. Of course, it will be useful to also allow users to filter these events (white-list or black-list).

IIUC, the current hooks for this are the `[OperationName].Start` and `[OperationName].Stop` DiagnosticSource events as described in [Subscribe to DiagnosticSource](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md#subscribe-to-diagnosticsource).

Since `OperationName` is dynamic, I don't see an easy way to get *all* activities. Would I have to do something like the following to e.g. send all finished activities to a different system?
```csharp
DiagnosticListener.AllListeners.Subscribe(delegate (DiagnosticListener listener)
{
    listener.Subscribe(delegate (KeyValuePair<string, object> value)
    {
        if (
            // StopActivity writes an event with the suffix "Stop"
            value.Key.EndsWith("Stop", StringComparison.Ordinal) 
            // However, there could also be other events that use this suffix
            // so we have to check if there's an activity
            && Activity.Current != null
            // There could also be "*.Stop" events while the activity is running
            && Activity.Current.Duration != TimeSpan.Zero)
        {
            // send stopped activity to external system
        }
    });
}
```
However, since there's no longer a filter outside of `Subscribe`, this would enable *all* diagnostic listener categories, wouldn't it? Also, the string comparison for the "Stop"-suffix etc seems a bit odd.

If the intend is to always have the category white-list, where/how should this be implemented in your opinion to keep the tracer (e.g. Application Insights) unaware of actual instrumentations?

### Using globally unique activity IDs
Tracing systems need unique IDs to distinguish traces/activities. The Activity API defines a way to [set a custom root ID](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md#root-id) through `SetParentId(string)`. If this API is not used, a simple int counter is used - which obviously isn't guaranteed to be unique across machines.

IIUC, tracers are supposed to call `SetParentId` in `[OperationName].Start` events, right? Child activities however will then get add local increment IDs as suffixes to this parent ID without any way to change it. IIUC, this has several problems:
* To call `SetParentId` on all activities, the tracer again has to listen to *all* `*.Start` events which might not be possible right now without enabling *all* diagnostic listener categories (see previous point)
* Tracers might not be able to handle the format of child activities. They might e.g. always require random `long` values.
* Child activities on different servers might get the same ID. Example: A server request generated a root ID of `123`. It then executes 2 child requests which are handled by different servers in a farm. If the local counter happens to be the same (e.g. on application startup), both would get the same child ID of "123.1".

**Comment by vancem** [comment]
@cwe1ss -   To respond to your questions:   

I don't properly understand your first question.     You seem to want to filter out things that are not start and stop events, which of course you can do, but it is unclear why.   I would expect tracers that are intended to be ignorant of the actual events being logged to log everything (filters return true) or to 'pass the buck' and allow its users to specify filtering criteria).    But lets assume you do only want to uniformly only log the 'Stop' events (which seems like a useful 'minimal'), then I would use test for the 'Stop' suffix as you indicate.    Note that if users don't follow the convention of suffixing with Stop when they are stopping their activity but that is really broken instrumentation code.   People should not be doing that (and the APIs encourage correct usage).    

(Note that in your example above you filter after the event was created (that is when Write() was called).  You can also use the 'Subscribe' that is passed a additional filter predicate and place the logic in there to avoid the overhead of creating the event if you don't care about it. 

On your second question:  Root ids are intended to be globally unique.   The current default root ID uses a machine name and a 'random' number generated from a tick count to make such an ID.   It is intended to be sufficient (The SetParentId is really only intended to be used when you are getting your parent 'of the network' from say a HTTP request).  

Arguably the current default mechanism is not sufficiently unique.    We will fix this.

**Comment by lmolkova** [comment]
@cwe1ss 

We expect every kind of Activity to have specific DiagnosticSource. Tracer should listen to all sources interesting for an application: Http, AspNetCore, etc...

* Start/Stop events have different payload for different kinds if activities: for Http outgoing requests it is  HttpRequest(Resonse)Message; for ASP.NET Core it will probably be HttpContext, etc... Generic listener would not be able to efficiently use payload object and would need to be aware of all kinds of activities anyway
* Note that there is a source-specific filtering done with `IsEnabled(string, object, object)` which also makes listener specific to particular activity type

**Comment by cwe1ss** [comment]
Thank you very much for your responses!

**Regarding my first question (subscribing to all activities):**

@lmolkova 
> Start/Stop events have different payload for different kinds if activities: for Http outgoing requests it is HttpRequest(Resonse)Message; for ASP.NET Core it will probably be HttpContext, etc... Generic listener would not be able to efficiently use payload object and would need to be aware of all kinds of activities anyway

I don't understand how this could possibly work if there's no separation between instrumentation code and tracer code. 

Let's say the following things are instrumented with the Activity API: Incoming ASP.NET requests, outgoing HTTP requests (HttpClient), outgoing SQL calls (SqlClient), outgoing calls to Azure DocumentDB, outgoing calls to Azure Service Bus. Some of these are in the .NET framework (HttpClient, SqlClient), the others are in separate libraries. Outgoing and incoming HTTP calls require header propagation (to continue a trace), the DB calls are probably just important for timing.

I might also have my own instrumentation code in my internal closed-source payment library to trace calls to e.g. an external payment provider (It might be a parent Activity of an underlying HTTP request).

A tracer library like Application Insights has a simple requirement: it wants to send all of these activities to its backend to display a full trace. 

To me this means that the Application Insights Client Library can't know about all the different instrumentations that exist - neither by DLL reference nor by using something like [aspnet/EventNotification](https://github.com/aspnet/EventNotification) or not even just a list of event name strings.

------

In OpenTracing, the separation between instrumentation code and tracer code is clear:
* Instrumentation code (e.g. an outgoing SQL call) create a `Span` (Activity) and adds all the information (it believes might be interesting for tracers) as tags - e.g. destination server, SQL command string, ...
* Tracer code only depends on `Span`. It could read the tags, but most of the time it just forwards them to a backend system for further processing.
* The most important tags are standardized to allow tracers to execute logic based on them.

This system has the advantage that the tracer library is completely unaware of specific instrumentations and it can handle all existing and future instrumentations. But of course, this system has the drawback, that it doesn't allow tracers to access the actual object (e.g. `HttpRequestMessage` for outgoing calls or `HttpContext` for incoming requests). It therefore can't add additional information that's not been added as a tag.

If the new Activity API doesn't have the same goal than I'm clearly misunderstanding it. If a tracer would need to implement logic for each instrumentation, what would be the point in having the Activity type anyway? There wouldn't be much difference to the currently used simple Start/Stop DiagnosticSource events.

**Comment by lmolkova** [comment]
Regarding the Activity API:
* It formalizes context for any type of operation
* It is globally accessible, so whenever you decide to log something (not necessarily in scope of start/stop), you have Activity.Current available

I understand your concern that every tracer should be aware of all kinds of activities.
If we expected tens or hundreds of different activity sources, it would become a problem. However now we are talking about < 10 well-known sources. 
As you mentioned, having single source for all activities does not give us flexibility to separately configure sources (that brings sampling and filtering so reduces performance overhead) or use complex payload (that allows us not to guess which information is useful for logging, so reduces unnecessary logging verbosity)

**Comment by cwe1ss** [comment]
**Regarding IDs:**

Duplicate root IDs are just one problem. I'm more concerned about the format of the ID and the possible cross machine overlaps due to incrementing numbers. 

I'll try to explain the problem with incrementing numbers with a different example:

* I have a web API with two instances on different machines
* I use nginx as a load balancer. It is configured to auto-retry timeouts or failed requests.
* My request is instrumented with an existing `Request-Id` of `/123/45`.
* nginx forwards the request to my first instance. My service (which has just been started) will use [appendSuffix](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L317) to create the new ID `/123/45/I-1`.
* The request fails for whatever reason. Nginx will resend the request - this time it ends up on my second machine.
* my service on my second machine also just processes its first request so it also ends up with the ID `/123/45/I-1`.

I'm not sure if I've interpreted the current code correctly (I didn't test it) so maybe my example is wrong and this case can't happen. 

-----

Regarding the format: let's say my tracer would like to process these activities. However, my tracing system uses Guids as IDs and I can't (or don't want to) change that. How should I get e.g. from your incoming Request-ID to my ID?

**Comment by cwe1ss** [comment]
> If we expected tens or hundreds of different activity sources, it would become a problem. However now we are talking about < 10 well-known sources.

Is RavenDb, MSMQ, Event Hubs, Service Bus, DocumentDB, RabbitMQ, MongoDB, Cassandra, Azure Search, Azure Table Storage, Azure Blob Storage, Redis, NCache, ... on that list? Is my mentioned custom payment API from my internal library on that list? :)

**Comment by lmolkova** [comment]
> Is RavenDb, MSMQ, Event Hubs, Service Bus, DocumentDB, RabbitMQ, MongoDB, Cassandra, Azure Search, Azure Table Storage, Azure Blob Storage, Redis, NCache, ... on that list?

Most of them have REST API and could be handled as HTTP outgoing requests. 

For others, I agree we should consider supporting common simple source in tracers. Then it will be up to particular instrumentation to either use custom source and make sure every tracer supports it or use default one with no perks.

**Comment by cwe1ss** [comment]
PS: Sorry for my negative view on this. I'm just really afraid that this thing won't be as useful as it should/could be or even ends up counter productive - especially because it's such a central part of the .NET framework and there probably won't be much space for change once this has shipped. 

While I fully agree that OpenTracing could do much better in some areas (e.g. wire format), it also does extremely well in other areas. Distributed systems could contain many different systems that might change very frequently. You can't build something as fundamental as the Span/Activity type under the assumption that there are less than 10 usages. IMO if this is done correctly, there are easily *hundreds* of use cases.

I'm still not sure if I'm understanding your intend with this new type. To me it currently looks a bit like you try to take 30% from OpenTracing and expect to still get 100% of the features.

**Comment by lmolkova** [comment]
> * I have a web API with two instances on different machines
> * I use nginx as a load balancer. It is configured to auto-retry timeouts or failed requests.
My request is instrumented with an existing Request-Id of /123/45.
> * nginx forwards the request to my first instance. My service (which has just been started) will use appendSuffix to create the new ID /123/45/I-1.

Note, that in `I-1` 1 is number of request received by this instance. 

> * The request fails for whatever reason. Nginx will resend the request - this time it ends up on my second machine.
my service on my second machine also just processes its first request so it also ends up with the ID /123/45/I-1.

So, it may be true only if this request is first on both instances. Which definitely may happen, but the probability of it is low. I mentioned this problem in #16500

**Comment by vancem** [comment]
@cwe1ss  with regard to listening to everything:   DiagnosticSource supports this.   That  is what the DiagnosticListener.AllListeners is for.  This is basically a subscription to susbscriptions.  When you subscribe to it you get a callback every time a DiagnosticSource gets created.   Thus you get the opportunity to decide if you want to subscribe to it or not.    Thus it is super-easy to subscribe to 'everything'.  

Basically from nothing (just knowing that DiagnosticSource Exists and access to reflection) you can subscribe and parse every event that uses a diagnostic source.

 Please ignore references to the number of expected DiagnosticSources.   If you can construct a problem that AllListeners does not address, we want to know about it. 

On Duplicate IDS: The IDs that are generated look like

/MYMachine-353223342-2

Where MyMachine is a machine name but 353223342 is a number that is effectively a unique ID for that machine (it is just a random timestamp), and 2 is a counter for the number of IDs generated on that machine so far.    All children of this ID add a suffix to this and thus are just as unique.  

Thus the root ID is to a reasonable approximation globally unique.    I don't believe your example will not cause a collision.

But if it does, the solution we will fix it so that root ids are globally unique.

**Comment by cwe1ss** [comment]
> Most of them have REST API and could be handled as HTTP outgoing requests.

True, but *completely* insufficient IMO. All of these systems have additional data (e.g. queue names, ...) that should be sent as tags or similar. However, the HTTP request is downstream so they can't add it to that. That's why all of them should create their own Activity (e.g. "ServiceBus_Out") before the HTTP handler creates its child Activity ("Http_Out").

**Comment by benaadams** [comment]
Seed with a fairly accurate DateTime.UtcNow.Ticks? (Rather than previous or desktop incarnation); then the ids will be generally always be increasing between restarts; and two machine processes are unlikely to start at the same tick?

**Comment by cwe1ss** [comment]
@vancem 
> @cwe1ss with regard to listening to everything: DiagnosticSource supports this. That is what the DiagnosticListener.AllListeners is for. This is basically a subscription to susbscriptions. When you subscribe to it you get a callback every time a DiagnosticSource gets created. Thus you get the opportunity to decide if you want to subscribe to it or not. Thus it is super-easy to subscribe to 'everything'.

My question/concern goes the opposite way: I was worried that if I subscribe to all categories, suddenly *EVERY* `IsEnabled` check in every component would return true. But if I understood correctly, putting the name check into the second `predicate` parameter solves this, right?

**Comment by vancem** [comment]
@cwe1ss  Yes, you can filter by event name using the two argument Subscribe API.    Do you still have a concern?   

On the concern about coupling:  I now see that you are concerned that DiagnosticSource sends things like HttpRequestMessage (that can't be serialized), to the subscriber.  Your concern seems to be how you serialize it. 

This touches on an important distinction between DiagnosticSource and most other loggers in that DiagnosticSource was created specifically to insure that the in-process case is handled well can can act as a building block for the out of process (serialization) case.    

As you note, there needs to be some code that decides what of the DiagnosticSource data should actually be serialized.     This is EXACTLY the problem we ran into when making the DiagnosticSource to EventSource bridge.  which passes DiagnosticSource information in a generic way to EventSource (which assumes you will serialize the messages).  

The solution was two-fold
     1) By default, any payload fields that are serializable are in fact serialized.    Thus at the logging site if you pass a integer or a string, by default that will be passed over the bridge to the EventSource.   We have not done this yet, but the idea would be that you can pass both the HttpRequestMessage AND say the URL in the payload.   The URL being a string will be serialized by the Bridge.    We expect that fields that EVERYONE wants will be done this way.  
     2) There is a specification that allows clients to specify what fields they want at the time they turn the bridge on for a particular DiagnosticSource.  

See https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource.cs for the implementation and detailed comments on how to use it.  There are also tests that can act as samples  

Thus either the source, or the target can decide something is interesting.   You can add more information 'after the fact' 

Note that rather than re-implement the bridge, I would suggest simply connecting to the EventSource (which now does the serialization for you).   

Note that all of this is roughly independent of Activities.

**Comment by lmolkova** [comment]
> Regarding the format: let's say my tracer would like to process these activities. However, my tracing system uses Guids as IDs and I can't (or don't want to) change that. How should I get e.g. from your incoming Request-ID to my ID?

You can still generate Guid and add it as tag. 
However it depends on what scenarios you have for the Id. If you want to send parent-guid-id with outgoing request, it becomes tricky: if you put your-guid-id into the baggage, it will be propagated to all downstream services and API does not let you change baggage.
Could you please share complete scenario?

**Comment by cwe1ss** [comment]
> @cwe1ss Yes, you can filter by event name using the two argument Subscribe API. Do you still have a concern?

No, this is fine - thank you! I'm not yet sure though, if this is the best way to fulfill the requirement "give me all finished activities". It steel feels a bit wobbly because one is not forced to go through `DiagnosticSource.StopActivity`. There would be no chance to get an activity that has been finished with a simple call to `Activity.Stop` (which updates Activity.Current though) . I think it would be nicer/more obvious, if both - the DiagnosticSource event and the static Activity.Current - would be managed by `StartActivity` and `StopActivity`. But I guess that's just a detail and failure to use it correctly is just a programming error.

**Comment by cwe1ss** [comment]
@lmolkova 
> Could you please share complete scenario?

* My imaginary tracer Trac0r uses 2 Guids as identifiers: TraceID (the whole distributed trace), ActivityID (a single unit in a distributed trace).
* When an Activity is started without a parent, it creates a new TraceID. All subsequent activities must re-use the same TraceID.
* The TraceID and the ActivityID must be propagated on outgoing HTTP calls
* The server will use these values when a new Span is started to associate the parent and the trace

Problems/questions:

* Given my assumption/hope that a tracer shouldn't know about instrumentation, how can I hook into the outgoing call and add my fields? Do I have to subscribe to all "*.Start" events and add both as baggage?
* While the TraceID is probably fine as baggage, the ActivityID is problematic because baggage is propagated to all subsequent activities and this ID changes with every Activity.
* If I use my own ActivityID as baggage, there's a small unnecessary overhead for the now unnecessary original ActivityID generation.

The existing ActivityID algorithm/format still seems a bit weird/random to me. Was it done this way to keep it closer to the ActivityIDs from ETW? Is this used in any production tracer? What's the value in concatenating IDs? Showing the correlation between activities should be the job of the actual tracing system IMO.
Wouldn't it be much easier to use a random 128bit number? I don't have much experience either but I think that a few tracers (e.g. zipkin) move there now.

I think, ideally it should be possible to completely overwrite the ActivityID. This way each system could use its own format. This might be problematic in terms of wire format encoding but this is probably easier to agree upon than the algorithm.

**Comment by cwe1ss** [comment]
@vancem 
> As you note, there needs to be some code that decides what of the DiagnosticSource data should actually be serialized. This is EXACTLY the problem we ran into when making the DiagnosticSource to EventSource bridge. which passes DiagnosticSource information in a generic way to EventSource (which assumes you will serialize the messages).

Yes, I think we're now on the same page. 😄 The big question is, who knows which fields should be sent to the tracing system - the instrumentation code or the tracer?! 
If you let the instrumentation code decide the tags, there will be no coupling but the tracer can't add stuff. If you let the tracer decide, it must know about the instrumentation and the type.

I think in most cases the instrumentation code knows best and there's not much need for a tracer to change it. I think this is true for systems like Redis, queuing systems, SQL, ... Probably most outgoing calls that don't require context propagation.

HTTP might be the special case here because there's so much metadata in HTTP headers. But even here it would be quite easy for USERS to intercept this and add any additional fields as tags in their own middleware/handler. Or the tracer could use some reflection magic to get additional fields.

Again, I see massive potential for this API! I think it's important to have a good story for the simple case in which the tracer shouldn't know about the instrumentation. Instead, the instrumentation code should add a sensible set of default tags. Fiddling around with the DiagnosticSource payload objects should be an advanced scenario IMO.

I will try to come up with some more pseudo code tomorrow to make sure I understand your feedback correctly. 

Thanks for taking so much time to make distributed diagnostics in .NET a first class citizen!!!

**Comment by vancem** [comment]
@cwe1ss  As you say in the common case, the instrumentation code can provide fine defaults.   Note that DiagnosticSource was created exactly for the case where this did not work (we have in-process loggers that wanted access to  potentially everything (e.g. headers, even the payload, context ...).   We did not want to instrument twice, and realized that instrumentation sites could log both the simple serializable things as well as the complex objects that allow full access).  This gets us both requirements.   It also allows a 'safety valve' where additional data can be fetched even if the instrumentation site was not prescient enough to include it.

**Comment by lmolkova** [comment]
@cwe1ss 
Regarding Id generation:

I believe you want to generate Activity (Span) Id and propagate it because tracers declare some format for the Id (like Zipkin does). And unfortunately there are some services that require different formats: e.g. guid. 
We want to support any *incoming* Id format, so you can set ParentId received from upstream service to whatever you want.
Hierarchical structure makes Id more useful: in fact you have TraceId, ParentId and ActivityId in one place so you don't even need to propagate all of them separately. It is similar to [Correlation Vector](https://osgwiki.com/wiki/CorrelationVector).

Hierarchical Ids also make our instrumentation incompatible with zipkin tracer or any other tracer that require Id to have some strict format. And we want to support them, so we need a story to let tracers specify format or provide generation rules if default format does not work for them.
We also want to provide end-to-end solution, where we can be sure that Ids are unique and sane.

Returning back to you scenario:
* TraceId should be provided when incoming request is received or parent operations starts in corresponding Start event. If there is no parent operation, outgoing requests will not be instrumented.
* You can provide ParentId to Activity, it will be used to generate Activity.Id that will be propagated. There is no way currently to change generation algorithm and we should think how we can support it

**Comment by cwe1ss** [comment]
I tried to come up with more pseudo-code for a tracer-integration. Here's the updated code:
```csharp
var includeList = new List<string>(); // Populated from cfg
var excludeList = new List<string>(); // Populated from cfg

DiagnosticListener.AllListeners.Subscribe(delegate (DiagnosticListener listener)
{
    // White-/Blacklisting events based on listenerNames (e.g. "System.Net.Http")

    if (includeList.Count > 0 && !includeList.Contains(listener.Name))
        return;

    if (excludeList.Count > 0 && excludeList.Contains(listener.Name))
        return;

    // The subscription should only trigger when an activity is started or stopped.
    // Since these events are just regular DiagnosticSource events, we need a way to differentiate
    // activity events from all other events.
    // Since DiagnosticSource.[Start|Stop]Activity will raise events named "<OperationName>.[Start|Stop]"
    // we can use this convention to find them.
    // However, nothing stops someone from writing non-activity events that also end with "Start" or "Stop"
    // so we still have to check if we are within a running activity.

    Predicate<string> isEnabled = eventName =>
    {
        return Activity.Current != null && (eventName.EndsWith(".Start") || eventName.EndsWith(".Stop"));
    };

    // The actual subscription
    var observer = new AnonymousObserver<KeyValuePair<string, object>>(evt =>
    {
        string eventName = evt.Key;
        object payload = evt.Value;
        Activity activity = Activity.Current;

        // TODO: The isEnabled check is still pretty weak because someone could trigger a non-activity event 
        // called "Foo.Start" while an activity is running, so we need some way to make sure we execute
        // the following code just once per Activity.
        // It would be much better if "activity" could be extracted from the payload.

        if (eventName.EndsWith(".Start"))
        {
            // Stuff that should happen for every activity that is started.

            // TODOs:
            // * Set IDs etc (e.g. TraceID, ActivityID, ...) based on tracer rules
            // * Set other baggage information (e.g. sampling)
            // * Set global tags
            // * Use some reflection magic to set tags for some defined events based on the payload
        }
        else if (eventName.EndsWith(".Stop"))
        {
            // Stuff that should happen for every activity that is stopped.

            // An activity-like Stop-event was raised but the underlying activity
            // hasn't been stopped yet so someone must have used the API wrong
            // so again there's nothing we can do.
            // TODO: This check doesn't work yet - see comments below.
            if (activity.Duration == TimeSpan.Zero)
                return;
            
            // TODOs:
            // * Send activity to the tracer API
        }
    });

    listener.Subscribe(observer, isEnabled);
```

Questions/concerns/issues:
* Does this isEnabled filter now ensure that `IsEnabled(listenerName) == false` for all non-activity DiagnosticSource events? (to ensure there's no performance impact for unrelated listeners)
* I don't like the relation between the events and the static `Activity.Current` accessor. This feels a bit wobbly and requires some weird checks. It would be a lot easier if the actual activity instance would be passed as an argument to the event. How about creating a wrapper type for "args" that holds the activity instance and all additional user-defined args? This would completely remove the need to access Activity.Current.
* I think there's an issue with "[DiagnosticSource.StopActivity](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceActivity.cs#L41)": The event is raised before `activity.Stop` is called. For this reason, event subscribers can't access the `Duration` property because it is still empty. IMO this is another perfect example why setting the static Activity.Current property within the activity instance is wrong. This should be done in StartActivity/StopActivity IMO. (1: activity.Stop(); 2: WriteEvent(); 3: update Activity.Current).

**Comment by lmolkova** [comment]
``` C#
Predicate<string> isEnabled = eventName =>
    {
        return Activity.Current != null && (eventName.EndsWith(".Start") || eventName.EndsWith(".Stop"));
    };
```
1. Listener should not check for Activity.Current. First of all, producer (e.g. ASP.NET) may be the first one that creates any Activity, so this check may turn off any possible instrumentation.
Some producers (e.g. System.Net.Http) will have the logic to check that Current != null as an indicator of instrumented operation.

2. Producers may call new IsEnabled(string name, object arg1, object arg2). In this case predicate may or may not take additional arguments into account.
Sample case is an System.Net.Http provider: it calls IsEnabled("System.Net.Http.Activity", request). If simple Predicate<string> is provided, DiagnosticListener omits additional arguments. Listener may provide predicate that filters out requests e.g. based on the URI.

So, some sources like System.Net.Http and AspNetCore may need specific listeners that are aware of IsEnabled semantics for advanced scenarios.
Also note, that if there are 2 listeners with different IsEnabled callbacks, then event is fired if at least one of IsEnabled returns true. 

> I don't like the relation between the events and the static Activity.Current accessor

The reason for static Activity.Current is that it must be accessible outside of Start and Stop events to let logger or app use it everywhere.

- "incoming request start" {Id=123} //logged in Activity.Start
- "log message in the controller" {Id=123} //logged somewhere in app code
- "incoming request stop" {Id=123}//logged in Activity.Stop

Alternatively we require users to pass Activity instance as an argument in all function calls.

>The event is raised before activity.Stop is called. For this reason, event subscribers can't access the Duration property because it is still empty. 

Producers need to call SetEndTime before calling StopActivity or Activity.Stop.
Stop actually means that activity is popped from Activity.Current stack and no longer Current. It is not related to the fact that operation is completed.  Indeed the naming could be better and usage pattern is complicated.

**Comment by cwe1ss** [comment]
> Listener should not check for Activity.Current. First of all, producer (e.g. ASP.NET) may be the first one that creates any Activity, so this check may turn off any possible instrumentation.

Good point!

> The reason for static Activity.Current is that it must be accessible outside of Start and Stop events to let logger or app use it everywhere.

Yes, that's ok from a producers/user side. I'm only talking about the subscribers side. It would be A LOT nicer if the actual Activity instance would be passed to the event as an argument. Again, I propose a simple wrapper type. This would also have the benefit tha subscribers could check that type to differentiate actual events from non-Activity events that coincidentally happen to have a ".Stop" suffix.

> Producers need to call SetEndTime before calling StopActivity or Activity.Stop.

The can but they don't have to so this is a very error-prone contract IMO. Actually, given the fact that DateTime.UtcNow will return more precise results shortly, I don't see a reason why SetEndTime should be called any longer?!

**Comment by lmolkova** [comment]
> Yes, that's ok from a producers/user side. I'm only talking about the subscribers side. It would be A LOT nicer if the actual Activity instance would be passed to the event as an argument. Again, I propose a simple wrapper type. This would also have the benefit tha subscribers could check that type to differentiate actual events from non-Activity events that coincidentally happen to have a ".Stop" suffix.

Subscriber then will have 2 ways to access Activity: from Activity.Current and from event payload. Considering that first one is more efficient and easy to do, I would expect subscribers to just use the first way. 
I would also prefer to provide more deterministic way to distinguish Activity events from any other *.Start and *.Stop events.

> I don't see a reason why SetEndTime should be called any longer?!
This is a good point. We should instead provide more durable DiagnosticSource.StopActivity(Activity, DateTime) overload that will set end time before Write. 
We would also need Activity.Stop(DateTime).

**Comment by cwe1ss** [comment]
> I would also prefer to provide more deterministic way to distinguish Activity events from any other *.Start and *.Stop events.

I'm open to whatever makes sure that it's definitely an activity event. Just relying on the convention that no one should use *.Start/*.Stop in non-activity events seems insufficient to me.


> This is a good point. We should instead provide more durable DiagnosticSource.StopActivity(Activity, DateTime) overload that will set end time before Write.
We would also need Activity.Stop(DateTime).

+1! Would be a lot more logical IMO! How about the Start/SetStartTime case? Would be great if there was a corresponding Start overload instead of the SetStartTime method, right?!

**Comment by vancem** [comment]
> Producers need to call SetEndTime before calling StopActivity or Activity.Stop.

That was certainly not my understanding that SetEndTIme would be called explicitly, and I *think* we agree that you should not have to (you only have to in the RARE case that the end time that is different the time the 'Stop' API is called.     I agree that there is but where the DiagnosticSource subscriber does not see a set duration.    I propose adding the following code to 'StopActivity()

            if (activity.Duration == TimeSpan.Zero)
                activity.SetEndTime(DateTime.UtcNow);

Analogously, SetStartTime is only useful if you want to override the start time used BEFORE you call Start() (otherwise it simply uses Now).    This is how things work today, and this was the original intent of the APIs.  

> Yes, that's ok from a producers/user side. I'm only talking about the subscribers side. It would be A LOT nicer if the actual Activity instance would be passed to the event as an argument. Again, I propose a simple wrapper type.

While that makes things easy on the consumption side, it complicates the generation side.  Presumably you want the Write (or Start or Stop) to add this to the payload, but it has already been given an object payload, and there is no easy way to add a field to it.   It can 'wrap' it but what does that accomplish besides allocating another object that will just have to be unwrapped (it also requires a new generic type for each kind of payload object and other inefficiencies.   

But more to the point, it is not clear to me why having the subscriber access Activity.Current is so bad.   Sure passing it as an argument is more discoverable, but that is the only value that I can see (what am I missing?)

Finally, it is not clear to me why the subscriber code should care about start and stop events particularly.    The idea is that start and stops are not particularly special, they just happen to be the first and last events in a particular activity (and indeed many systems will turn off the start because the system already does what is needed). 

We are really not trying to make a super-flexible system that lets you simulate another logging system in ours.   We are trying to provide the 'minimum contract' that allow useful end-to-end correlation and interoperate with other systems that provide that minimum contract. 

By the way the minimum contract is roughly
     Activities have unique IDs
     Activities know their parents. 

Now we go further and say our ID are hierarchical, but we can interoperate with systems that don't do that.   IF they want to treat our ID as simply a unique thing, or hash it into a GUID so it looks like their other IDs, they are free to do that.   Indeed we do the opposite (taking their ID and making hierarchical IDs out of it (but appending to it).     We hope (believe) that if everyone follows this minimum standard (and ideally uses the same names in HTTP fields), then we can all play together well.    It does assume that we meet in the middle (each of us make our systems a flexible enough to interoperate with systems that also have this minimum standard and flexibility).

**Comment by cwe1ss** [comment]
>  I propose adding the following code to 'StopActivity()

Not as simple/nice as the StartActivity/StopActivity overloads but I could live with it.

> But more to the point, it is not clear to me why having the subscriber access Activity.Current is so bad. Sure passing it as an argument is more discoverable, but that is the only value that I can see (what am I missing?)

I want to ensure that I'm in an activity event, that's all! And just comparing the string name suffix seems weak to me. Imagine I'm an an ASP.NET core request (so Activity.Current is set) and someone manually calls a DiagnosticSource.Write event with the name "Foo.Start" - but it's just a normal event and doesn't start a new Activity. This would trigger my Start logic again because I can't differentiate the event. Having the wrapper type argument would have been an easy way for that - but yes, it requires an additional allocation. So whatever else works is fine for me.

As a programmer I'm having a hard time to rely on a string convention in a system that could be used by so many people.

> Finally, it is not clear to me why the subscriber code should care about start and stop events particularly.

Because in Start I have access to the payload and in Stop I don't. Also, I must set the ParentID and baggage in the Start event because it's propagated to child events. And I need the Stop event to send the Activity to my tracer API.

Has there been any actual implementation feedback from the Application Insights guys? They should have raised similar concerns unless I'm still seriously misunderstanding this API. 😕

**Comment by cwe1ss** [comment]
Edit: Sorry, I would have access to the payload in Stop as well (assuming implementors pass it as well) but I still need the Start logic at least for the baggage. And even if I wouldn't need it, what sense would it make to have this event if I couldn't reliably use it?!

**Comment by vancem** [comment]
> Because in Start I have access to the payload and in Stop I don't. Also, I must set the ParentID and baggage in the Start event because it's propagated to child events. And I need the Stop event to send the Activity to my tracer API.

As you determined, you have access to the payload (and baggage and tags) everywhere (in ALL events, there is nothing special about starts and stops).     But I want to make sure we have an understanding that you DON'T need to set the parent ID in the start (that is what System.Activity does).   The idea is that all you have to do as a Subscriber is decide what events you want and send them on to your target.    

It is true that you can also put things in baggage, but we have done something wrong if this is not RARE (basically at the 'top level' of what you want traced), and even there you should not need it most of the time (All you need to do is to create an activity.  We always generate and propagate the ID properly and you don't need to do anything).   

Finally the goal of this round of implementation is to stand up a end-to-end implementation.   As you point out, there are lots of details that have to work out and they can be resolved in many different ways.   We like to think that the details will work out, but if they don't the point of doing this sooner rather than later is to discover things like that and correct them.  

We like to believe that mostly logging systems don't need to do much except turn the system on (by enabling a diagnosticSource that calls DiagnosticSource.StartActivity().

**Comment by cwe1ss** [comment]
> The idea is that all you have to do as a Subscriber is decide what events you want and send them on to your target.

:smile: I think that's the fundamental line where we just don't understand each other's use case. It seems to me that you have the PerfView whitelist approach in mind (tracing a fixed list of well known events) and I'm always talking about a general tracer which just logs all activities that exist - without knowing their names (but obviously with ways to apply filters). 

I'm not sure I can explain my scenario in any other way than I've done here and in previous comments so I'll just leave it to that for now. I'll wait for the Application Insights team (or someone else) to build their integration - I hope this will show that I just didn't unterstand this well enough. Sorry for taking up so much of your time.

**Comment by cwe1ss** [comment]
Seeing what's going on in https://github.com/aspnet/Hosting/pull/964 increases my concerns with this API even more. It seems like it currently does a lot of things different than what's recommended in your guideline document. Even if this (hopefully) will be resolved by the time it will get merged, I'm still wondering how other people - who are not under your supervision - should get this right in their own systems.

TBH I didn't want to rant again but I'm just really frustrated because I don't understand why we have such different views on this. The API is very hard to use (for instrumentation and subscription) and it still completely fails the IMO most basic and most important use case which I've tried to emphasize many times: "Send EVERY activity to the tracer". (Favor sampling over less detailed traces)

And even if you would get every activity in a generic way, there's basically no value in it because the current instrumentations don't set any tags by default. If other libraries (e.g. Message Bus libraries) follow this pattern, a tracer has to write code for 10s of instrumentations which just doesn't make sense and doesn't scale.

I'm really sorry for ranting that much! This topic is just very important to me and I really want to see it succeed. 

Would it be possible to have the guys who will implement the Application Insights tracer comment their plan here (or even a link to some code if it already exists)? I really would like to hear the opinion of someone else who will write subscription code.

**Comment by cwe1ss** [comment]
I raised my concerns so I'll close this.
