### ISSUE TITLE
Review the uniqueness of Activity ID in System.Diagnostics.Activity

### ISSUE THREAD

**Issue by vancem** [dotnet/corefx#16500]
Currently we generate an ID by creating a 'unique ID for a process' (see s_uniqPrefix in the code) and then appending a process wide number (that increments) each time a number is used.  

There is a wrap around problem (if you allocate more than 4 billion IDs) 

The s_uniqPrefix is also not perfect as it uses the us granularity tick count to create a 'random' number.   There certainly COULD be collisions if there were multiple processes on the same machine using activities and they both fetched their very first ID at the same time.  

There is also an issue when you create a ID from a ParentID coming from another system.   Currently we simply append a process-wide sequence number to the ParentID, but if this happens on two different machines there can be a collision.    Adding a machine-random number would avoid this. 

These are all very rare events, but if we can find cheap ways of making this better we should do so.

**Comment by stephentoub** [comment]
> The s_uniqPrefix is also not perfect as it uses the us granularity tick count to create a 'random' number

Where is this being done?  Random in coreclr is no longer seeded by default in its ctor by Environment.TickCount.

**Comment by vancem** [comment]
The code is in 

https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.Id.MachineName.cs

It is just calling Stopwatch.GetTickCount.

**Comment by lmolkova** [comment]
Another problem mentioned by @cwe1ss in #16491:
When ParentId is provided, Id suffix is number of requests received by this instance. E.g. if first request ever received by the service fails and retry is handled by another instance, both tries will have the same Id.
Again, the probability of this is quite low.

**Comment by vancem** [comment]
I think a simple mitigation to the ParentId problem is to randomize the start location of the ID that is tacked the ParentID.   Thus two separate machines will have only a 1 / 4GIG likelihood of collision.

**Comment by vancem** [comment]
We implemented the randomized start suggested above.   We may still wish to tweek this, but we have the ability to do so.  I think this is good enough now to close this issue.
