### ISSUE TITLE
System.Diagnostics.Tests.ProcessTests.TestProcessOnRemoteMachineWindows failure

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#16510]
System.Diagnostics.Tests.ProcessTests.TestProcessOnRemoteMachineWindows will fail if the machine that it is running on has inaccessible performance counter. We should move this test to outer loop, or make it robust against dirty environment.

```
        System.Diagnostics.Tests.ProcessTests.TestProcessOnRemoteMachineWindows [FAIL]
        System.InvalidOperationException : Couldn't connect to remote machine.
           ---- System.InvalidOperationException : Couldn't get process information from performance counter.
           -------- System.InvalidOperationException : Cannot load Counter Name data because an invalid index 'RemoteFX Synth3D VSC VM Transport Channel' was read from the registry.
           Stack Trace:
              X:\dev\coreclr\corefx\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(521,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
              X:\dev\coreclr\corefx\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(521,0): at System.Diagnostics.NtProcessManager.GetProcessInfos(String machineName, Boolean isRemoteMachine)
              X:\dev\coreclr\corefx\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(266,0): at System.Diagnostics.NtProcessManager.GetProcessIds(String machineName, Boolean isRemoteMachine)
              X:\dev\coreclr\corefx\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(69,0): at System.Diagnostics.ProcessManager.GetProcessIds(String machineName)
              X:\dev\coreclr\corefx\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(30,0): at System.Diagnostics.ProcessManager.IsProcessRunning(Int32 processId, String machineName)
```

**Comment by jkotas** [comment]
@pkukol has been running into this.

**Comment by Priya91** [comment]
We can handle this exception and pass the test for this case.

**Comment by danmosemsft** [comment]
@Priya91 handle what where? if the test catches InvalidOperationException it seems it could happen from "could not connect" which presumably we want to cause the test to fail.

if you have a proposed change, vendor folk could help make it.

**Comment by Priya91** [comment]
@danmosemsft The test is only run if the performance counter is enabled on the machine, the particular error reported by jan is that the performance counter registry key is corrupted on the machine, and hence we throw in code [here](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/PerformanceCounterLib.cs#L264). Hence, this is not a product bug, so we should wrap the test in try catch block, and ignore Invalid exception..

**Comment by danmosemsft** [comment]
Right but if the test catches that wouldn't it also catch these
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessManager.Windows.cs#L543
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessManager.Windows.cs#L518

**Comment by Priya91** [comment]
Right, we can probably check for this particular case by parsing the exception string or some other way to pinpoint this error..

**Comment by karelz** [comment]
Next step: Change the test as described [above](https://github.com/dotnet/corefx/issues/16510#issuecomment-288839373) - pass it in such case. Verify it works in both scenarios - when you have access and when you don't.

Should be easy (the "tricky" part will be to reproduce the dirty environment).

**Comment by danmosemsft** [comment]
Fixed by https://github.com/dotnet/corefx/pull/18457
