### ISSUE TITLE
Add code to reset s_currentImpersonatedToken in WindowsIdentity

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#1651]
See method RunImpersonatedInternal in src/system.security.principal.windows/src/system/security/principal/windowsidentity.cs.

In initial commit feedback it was suggested we need to add to reset to its original value in a finally {} block.

**Comment by stephentoub** [comment]
I re-reviewed this and realized it's fine as is.  The value is never read except immediately after it's set into the AsyncLocal, so we don't need to be concerned about code elsewhere seeing the previously set value.
