### ISSUE TITLE
SerialPort: Close blocked while write blocked in NETFX

### ISSUE THREAD

**Issue by jcurl** [dotnet/corefx#16529]
See this comment:
https://github.com/dotnet/corefx/issues/984#issuecomment-283058494

The SerialPort will block forever on Close(), while write blocked. Write blocked usually occurs during hardware flow control on the serial port where the remote side is causing the flow control. That is, while the remote side has indicated that sending is not possible so that Write() is blocked, Close() will block forever. 

A test case that shows this behaviour is:

```c#
// NOTE: This test is expected to fail or block forever on Windows.
[Test]
[Timeout(4000)]
public void SerialPortDisposedWhenBlocked()
{
    byte[] buffer = new byte[1024];

    using (SerialPort serialSource = new SerialPort(c_SourcePort, 115200, Parity.None, 8, StopBits.One))
    using (SerialPort serialDest = new SerialPort(c_DestPort, 115200, Parity.None, 8, StopBits.One)) {
        serialSource.Open();
        serialDest.Open();

        serialDest.RtsEnable = false;

        new Thread(
            () => {
                Thread.Sleep(2000);
                Console.WriteLine("Disposing serialSource");
                 // It appears that the MSDN .NET implementation blocks here, never
                // to return as we're blocked on another thread.
                serialSource.Dispose();
                Console.WriteLine("Disposed serialSource");
            }
        ).Start();

        int bufferCount = 1024 * 1024;
        while (bufferCount > 0) {
            serialSource.Write(buffer, 0, buffer.Length);
            bufferCount -= buffer.Length;
            Console.WriteLine("{0}", bufferCount);
        }
    }
}
```

To test you will need real hardware that supports hardware flow control (e.g. a cable that also has RTS/CTS correctly wired), not just a simple three-wire cable. For example, this is reproducible on 2 USB FTDI chipsets with a NULL-Modem cable between that connects the RTS/CTS from each port to the other port.

It works by telling the source port to send data, usually it will block within the first 2 seconds due to internal OS buffers. Then it becomes write blocked. The thread running in the background simulates another thread that might be trying to close or dispose the program and calls Close/Dispose on a different thread. Unfortunately, that thread will also block forever.

**Comment by danmosemsft** [comment]
@willdean

**Comment by willdean** [comment]
@jcurl I've had a play with this, and it seems to me that the only reason it hangs is that there's no `WriteTimeout` set on the port. If you set a `WriteTimeout` it appears to work OK:  the `Dispose` waits while there's a pending write, but as soon as the write completes (with a timeout), the Dispose completes OK.

I'm not sure if it's documented whether or not `Close/Dispose` is suppose to cancel all pending operations, but if it's not then I guess waiting for them to complete before closing is a legitimate choice on the part of the original creators.   It's not like this problem:  http://stackoverflow.com/questions/3523812 which is a driver bug (incomplete IRPs prevent an application closing)

Here's my test code, in the style of the existing tests, in case you spot a difference.

```
        [ActiveIssue(16529)]
        [OuterLoop]
        [ConditionalFact(nameof(HasOneSerialPort), nameof(HasHardwareFlowControl))]
        public void ClosePortWhileBlockedWriteIsPending()
        {
            using (SerialPort com = new SerialPort(TCSupport.LocalMachineSerialInfo.FirstAvailablePortName))
            {
                com.Open();
                com.Handshake = Handshake.RequestToSend;
                com.WriteTimeout = 10000;

                // Schedule a task to close the 
                Task task = Task.Delay(2000).ContinueWith(t =>
                {
                    com.Dispose();
                });

                try
                {
                    var writeBuffer = new byte[TCSupport.MinimumBlockingByteCount];
                    com.Write(writeBuffer, 0, writeBuffer.Length);
                }
                catch (TimeoutException)
                {
                    // Real serial.sys ports will throw TimeoutException when the Write fails
                    // FTDI USB ports just seem to complete the write after the timeout period
                }

                TCSupport.WaitForTaskCompletion(task);
            }
        }
```

**Comment by willdean** [comment]
Looking at the `SerialPort` source, when you dispose a port it calls `Flush` which in turn calls the Win32 function `FlushFileBuffers` - this function is doing what it's supposed to, which is to get everything written, and if it's waiting for hardware flow control with an infinite timeout, it just waits.

I'm afraid that I understand this issue properly then I don't really think this is a bug.  If you didn't want to rely on timeouts you could call `DiscardOutBuffer` on the port before disposing it - there is then of course a potential race there where a blocking write starts between the `DiscardOutBuffer` and the `Dispose`.

**Comment by jcurl** [comment]
Dispose() and Close() on the SerialPort behave the same. Take the Socket.Close(), that will abort an existing blocking Write() with an exception ObjectDisposedException.

On the otherhand, now reading the manual and using your analysis, it explains *why* it blocks permanently and what someone should do about it.

Calling this method closes the SerialPort object and clears both the receive and transmit buffers.

Not very consistent though with other stream based implementations, like Socket.Close(). That will cause the blocking Write() to abort and raise an exception. Other Stream() methods indicate the only way to abort an ongoing write is dispose of it (how else do you abort a BeginWrite() in .NET 4.0?).

I agree to close it, changing behaviour may not sit well with already written code.
