### ISSUE TITLE
Address possible race conditions in System.Security.Principal.Windows tests

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#1652]
See src/system.security.principal.Windows/tests/WindowsIdentityTests.cs

Initial commit feedback was: "Could this not be problematic / prone to race conditions if the safe handle gets finalized concurrent with usage of logonToken (no AddRef/Releasing is being done to prevent that)?"

**Comment by AlexGhiondea** [comment]
This looks like a good place for someone to start getting familiarized with working on .NET Core.

**Comment by MattGal** [comment]
True, but I'm not sure this race condition ever actually has been hit in real test execution so it may be theoretical only.

**Comment by AlexGhiondea** [comment]
@MattGal so this is just based on code inspection?

**Comment by MattGal** [comment]
@AlexGhiondea Code inspection by whoever did the PR review 1.5 years ago yes.

**Comment by AlexGhiondea** [comment]
It looks like the issue in question is happening [here](https://github.com/dotnet/corefx/blob/master/src/System.Security.Principal.Windows/tests/WindowsIdentityTests.cs#L26).

Basically, we do this:
```csharp
IntPtr logonToken = WindowsIdentity.GetCurrent().AccessToken.DangerousGetHandle();
```

And maybe we should do this:
```csharp
bool addSucceeded = false;
var token = WindowsIdentity.GetCurrent().AccessToken;
IntPtr logonToken;
try
{
    token.DangerousAddRef(ref addSucceeded);
    Assert.True(addSucceeded);
    logonToken = token.DangerousGetHandle();
}
finally
{
    if (addSucceeded)
    {
       token.DangerousRelease();
    }
}
```
/cc @stephentoub as he added that comment originally.

**Comment by stephentoub** [comment]
> maybe we should do this

That's the right general idea, but the release shouldn't happen until after the token is no longer needed, e.g.
```C#
bool gotRef = false;
try
{
    token.DangerousAddRef(ref gotRef);
    IntPtr logonToken = token.DangerousGetHandle();
    ... // use logonToken here
}
finally
{
    if (gotRef) token.DangerousRelease();
}
```

**Comment by AlexGhiondea** [comment]
@stephentoub ah -- yes -- the code to use the token would go where you suggested 😄

**Comment by AlexGhiondea** [comment]
Next steps: Actually implementing this. This is trivial and a very simple way to get started with our code base.

**Comment by stephentoub** [comment]
Closed by https://github.com/dotnet/corefx/pull/17529
