### ISSUE TITLE
System.Reflection.Emit doesn't define a default constructor

### ISSUE THREAD

**Issue by sebaFlame** [dotnet/corefx#16526]
```c#
AssemblyName asmName = new AssemblyName("ConsoleApplication.Dynamic");
AssemblyBuilder asmBuilder = AssemblyBuilder.DefineDynamicAssembly(asmName, AssemblyBuilderAccess.Run);
ModuleBuilder moduleBuilder = asmBuilder.DefineDynamicModule(asmName.Name);
TypeBuilder typeBuilder = moduleBuilder.DefineType("TestClass", TypeAttributes.Public);
ConstructorBuilder constructorBuilder = typeBuilder.DefineDefaultConstructor(MethodAttributes.Public);
Type type = typeBuilder.CreateTypeInfo().GetType();
object obj = Activator.CreateInstance(type);
```
last line gives this exception: **Unhandled Exception: System.MissingMethodException: No parameterless constructor defined for this object.**
The call to typeBuilder.DefineDefaultConstructor should not be necessary.
Using cli 1.0.0-preview2-003131 with "System.Reflection.Emit": "4.0.1"

**Comment by JonHanna** [comment]
```C#
Type type = typeBuilder.CreateTypeInfo().GetType();
```

This line is in error. The `GetType()` called is the same `GetType()` that every object has that returns the type of the actual object it is called on, which is to say the type of the actual result of `CreateTypeInfo()`.

That line should be:

```C#
Type type = typeBuilder.CreateTypeInfo().AsType();
```

In which case this should work both with and without the call to `DefineDefaultConstructor`.

**Comment by sebaFlame** [comment]
Now works as expected. Thank you for the info.
