### ISSUE TITLE
Ubuntu 16.10 CI runs failing

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#16530]
These appear to be the first failing builds:
https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu16.10_debug/1095/
https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu16.10_release/1098/
which suggests one of these changes is the culprit:
```
Changes 
Add Narrow, Widen, and Conversion methods to System.Numerics.Vectors. (commit: 2f69e67) (detail / githubweb)
Add ConditionalFacts to GenericVectorTests.tt so that they are not (commit: 95f40b2) (detail / githubweb)
Fix issues related to the debug overflow checking we added. (commit: 79766d2) (detail / githubweb)
Update buildtools and re-enable projects disabled due to Unix ilasm (commit: 29029cf) (detail / githubweb)
```

**Comment by danmosemsft** [comment]
@mellinoe these are all your commits. Do you have a 16.10 VM lying around?

**Comment by mellinoe** [comment]
Should be fixed now.

**Comment by karelz** [comment]
@mellinoe Out of curiosity, how did it get through CI? Are we missing some coverage?

**Comment by stephentoub** [comment]
> Out of curiosity, how did it get through CI? Are we missing some coverage?

We don't have Ubuntu 16.10 legs in CI.

**Comment by karelz** [comment]
OK, that makes sense then.
