### ISSUE TITLE
Test failure: System.Net.Security tests failing with "Authentication failed because the remote party has closed the transport stream"

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#16534]
There is a group of tests that are failing intermittently with the error ```System.IO.IOException : Authentication failed because the remote party has closed the transport stream.```. I'm tracking their failures in this issue as they are likely due to the same underlying issue.

The following tests have failed at some point with this error:
- [ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_MismatchProtocols_Fails(serverProtocol: Tls12, clientProtocol: Tls11](https://github.com/dotnet/corefx/issues/16968)
- [ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_EachClientUnsupportedProtocol_Fail](https://github.com/dotnet/corefx/issues/10909)
- [ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_AllServerAllClient_Success](https://github.com/dotnet/corefx/issues/14177)
- ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_IndividualServerVsAllClientSupportedProtocols_Success(serverProtocol: Tls11) 
- ClientDefaultEncryptionTest.ClientDefaultEncryption_ServerAllowNoEncryption_ConnectWithEncryption
- [ServerNoEncryptionTest.ServerNoEncryption_ClientAllowNoEncryption_ConnectWithNoEncryption failed.](https://github.com/dotnet/corefx/issues/9130)
- [ServerNoEncryptionTest.ServerNoEncryption_ClientNoEncryption_ConnectWithNoEncryption](https://github.com/dotnet/corefx/issues/11624)
- ServerAllowNoEncryptionTest.ServerAllowNoEncryption_ClientNoEncryption_ConnectWithNoEncryption
- [ServerAllowNoEncryptionTest.ServerAllowNoEncryption_ClientRequireEncryption_ConnectWithEncryption](https://github.com/dotnet/corefx/issues/14504)

None of these test failures are reproducible on local machines regardless of the number of runs executed, which suggests the issue lies in either the infrastructure or interference from other tests run alongside these. They only fail on Windows.

It might be helpful to get another pair of eyes on this to see if anything stands out. As it is, I've been unable to narrow the symptoms down to any definitive problem and @steveharter and my's attempts to reproduce failures have been fruitless. I'll be disabling this entire group of tests to regain stability until we can get more information on their source. They are possibly related to https://github.com/dotnet/corefx/issues/16516.

**Comment by ianhays** [comment]
I'm fairly certain these are from the same root cause as #16516. The failures only occur when the server SSLProtocol being used is `SslProtocols.Tls11` or `SslProtocols.Tls12 | SslProtocols.Tls11 | SslProtocols.Tls`. It does not fail for `SslProtocols.Tls12` or `SslProtocols.Tls`.

This is also true for several of the tests in #16516 with the exception of those that do not set an SSlProtocol explicitly. In those cases, our code uses `SslProtocols.None'.

**Comment by ianhays** [comment]
@davidsh @steveharter any obvious reason why a Server with `SslProtocols = SsslProtocols.Tls11` would cause intermittent failures like this on Windows?

**Comment by stephentoub** [comment]
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/4035/consoleText
```
System.Net.Security.Tests.ServerAllowNoEncryptionTest.ServerAllowNoEncryption_ClientRequireEncryption_ConnectWithEncryption [FAIL]
        System.IO.IOException : Authentication failed because the remote party has closed the transport stream.
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SslState.cs(894,0): at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SslState.cs(1115,0): at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\src\System\Net\Security\SslState.cs(731,0): at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
              at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\tests\FunctionalTests\ServerAllowNoEncryptionTest.cs(46,0): at System.Net.Security.Tests.ServerAllowNoEncryptionTest.<ServerAllowNoEncryption_ClientRequireEncryption_ConnectWithEncryption>d__3.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by steveharter** [comment]
@ianhays it appears the issues only occur in win7\nt, so I'd recommend spending time on a repro around those tests on win7\nt.

On potential cause, one item of note is I believe tls11 is not enabled by default there. I see that tls11 is enabled here WinHttpHandler.SetSessionHandleTlsOptions (via SetWinHttpOption WINHTTP_OPTION_SECURE_PROTOCOLS) https://github.com/dotnet/corefx/blob/52bab6669b5cdf90161fc5d1b71c3d9a0f3854eb/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs#L912. However we do not also do that in SetRequestHandleOptions which I think could be necessary in a callback case.

**Comment by ianhays** [comment]
@steveharter they fail on all Windows, not just win7.

**Comment by davidsh** [comment]
>On potential cause, one item of note is I believe tls11 is not enabled by default on win7\nt. I see that tls11 is enabled here WinHttpHandler.SetSessionHandleTlsOptions (via SetWinHttpOption WINHTTP_OPTION_SECURE_PROTOCOLS) https://github.com/dotnet/corefx/blob/52bab6669b5cdf90161fc5d1b71c3d9a0f3854eb/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs#L912. However we do not also do that in SetRequestHandleOptions which I think could be necessary in a callback case.

That code is for WinHttpHandler and the System.Net.Http classes.  It has nothing to do with SslStream and System.Net.Security.

**Comment by steveharter** [comment]
@ianhays I looked at the recent jdash failures and the ones referencing tls in the signature, which were all on win7\nt:
http://jdash.azurewebsites.net/builds/test?name=System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_AllClientVsIndividualServerSupportedProtocols_Success%28serverProtocol%3A%20Tls11%29&viewName=dotnet_corefx&pr=False&limit=1000&startDate=2017-02-04
http://jdash.azurewebsites.net/builds/test?name=System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_EachSupportedProtocol_Success%28protocol%3A%20Tls11%29&viewName=dotnet_corefx&pr=False&limit=1000&startDate=2017-02-04
http://jdash.azurewebsites.net/builds/test?name=System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_IndividualServerVsAllClientSupportedProtocols_Success%28serverProtocol%3A%20Tls11%29&viewName=dotnet_corefx&pr=False&limit=1000&startDate=2017-02-04
http://jdash.azurewebsites.net/builds/test?name=System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_MismatchProtocols_Fails%28serverProtocol%3A%20Tls%2C%20clientProtocol%3A%20Tls11%2C%20expectedException%3A%20typeof%28System.Security.Authentication.AuthenticationException%29%29&viewName=dotnet_corefx&pr=False&limit=1000&startDate=2017-02-04

**Comment by ianhays** [comment]
@steveharter I followed those links and they showed several non-win7 failures.

Here is one on win10: https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_win10_debug/34/testReport/junit/System.Net.Security.Tests/ServerAsyncAuthenticateTest/ServerAsyncAuthenticate_AllClientVsIndividualServerSupportedProtocols_Success_serverProtocol__Tls11_/

and another:
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release/1257/testReport/junit/System.Net.Security.Tests/ServerAsyncAuthenticateTest/ServerAsyncAuthenticate_AllClientVsIndividualServerSupportedProtocols_Success_serverProtocol__Tls11_/

**Comment by steveharter** [comment]
It still seems like ~90% of the failures are from win7\_nt, so I would focus on that at least for getting a repro.

FYI the first link is from release branch (which is still a concern)
The second link is win_nt.

**Comment by Jiayili1** [comment]
Failed again on build 20170310.01, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170310.01/workItem/System.Net.Security.Tests/analysis/xunit/System.Net.Security.Tests.ServerAllowNoEncryptionTest~2FServerAllowNoEncryption_ClientNoEncryption_ConnectWithNoEncryption

**Comment by steveharter** [comment]
I came across similar failure in GetAsync_AllowedSSLVersion_Succeeds on Win2008 offline CI machine when running repeatedly, although with the error "An error occurred while sending the request.", not "authentication failed because the remote party has closed the transport stream". 

That test has not been disabled yet.
```
   System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.GetAsync_AllowedSSLVersion_Succeeds(acceptedProtocol: Tls11, requestOnlyThisProtocol: True) [FAIL]
      System.Net.Http.HttpRequestException : An error occurred while sending the request.
      ---- System.Net.Http.WinHttpException : The operation has been canceled
      Stack Trace:
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
            at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.<>c__DisplayClass4_0.<<GetAsync_AllowedSSLVersion_Succeeds>b__0>d.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass3_0.<CreateServerAsync>b__0(Task t)
            at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
            at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.<GetAsync_AllowedSSLVersion_Succeeds>d__4.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         ----- Inner Stack Trace -----
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
            at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
```

**Comment by steveharter** [comment]
No repro of original issue ("Authentication failed because the remote party has closed the transport stream.") after re-enabling the tests and running in loop 5,000 times on Windows 10 and 2008r2 (what we call 'win7' in the badges).

**Comment by mellinoe** [comment]
I hit this in one of my PR's, although the test case is not listed:

`System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_ServerRequireEncryption_ConnectWithEncryption`

```
12:52:41         System.IO.IOException : Authentication failed because the remote party has closed the transport stream.
12:52:41         Stack Trace:
12:52:41            D:\j\workspace\windows_nt_re---69ec86af\src\System.Net.Security\src\System\Net\Security\SslState.cs(891,0): at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
12:52:41            D:\j\workspace\windows_nt_re---69ec86af\src\System.Net.Security\src\System\Net\Security\SslState.cs(1112,0): at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
```

https://ci.dot.net/job/dotnet_corefx/job/release_2.0.0/job/windows_nt_release_prtest/27/consoleText

**Comment by CIPop** [comment]
This doesn't appear to be related to #16516. The commonality here appears to be that all of the tests are using actual network calls instead of `VirtualNetwork`.

**Comment by karelz** [comment]
Triage: We do not think this is going to impact customers.
Likely some issues around OS networking stack and our interaction with it.

**Comment by CIPop** [comment]
This report: https://github.com/dotnet/corefx/issues/16534#issuecomment-294515487 is related to #19701.

**Comment by Jiayili1** [comment]
Following tests failed with same issue:
System.Net.Security.Tests.ClientAsyncAuthenticateTest/ClientAsyncAuthenticate_AllServerAllClient_Success 
System.Net.Security.Tests.ClientAsyncAuthenticateTest/ClientAsyncAuthenticate_AllServerVsIndividualClientSupportedProtocols_Success
System.Net.Security.Tests.ClientAsyncAuthenticateTest/ClientAsyncAuthenticate_EachSupportedProtocol_Success
System.Net.Security.Tests.ClientAsyncAuthenticateTest/ClientAsyncAuthenticate_IndividualServerVsAllClientSupportedProtocols_Success
System.Net.Security.Tests.ClientAsyncAuthenticateTest/ClientAsyncAuthenticate_MismatchProtocols_Fails
System.Net.Security.Tests.ClientAsyncAuthenticateTest/ClientAsyncAuthenticate_ServerRequireEncryption_ConnectWithEncryption 

Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170626.01/workItem/System.Net.Security.Tests/analysis/xunit/System.Net.Security.Tests.ClientAsyncAuthenticateTest~2FClientAsyncAuthenticate_AllServerAllClient_Success

**Comment by Jiayili1** [comment]
failed again in CI: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_release/168/testReport/System.Net.Security.Tests/TransportContextTest/TransportContext_ConnectToServerWithSsl_GetExpectedChannelBindings/
