### ISSUE TITLE
[Question] MinValue and MaxValue. 

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/corefx#16540]
This is going to read like a dumb question, but I need confirmation.
Are the `.MinValue` and `.MaxValue` of the types that specify there bit width. eg Int32 going to change?

If never then I / we, can in same test cases use the text `2147483647`, rather than `Int32.MaxValue.ToString`

**Comment by JonHanna** [comment]
Changing them would require a lot of very deep changes throughout the entirety of .NET for every implementation. I think it's safe to say they'll change.

It's easier to mistype `2147483647` than `int.MaxValue` though, and not a compiler error if you do, so I wouldn't favour `"2147483647"` over `int.MaxValue.ToString()` in a test and in non-test code only in a hot path.

**Comment by AdamSpeight2008** [comment]
@JonHanna  Even if the result string is now a compile-time constant?

**Comment by JonHanna** [comment]
That's the reason I would do it in a hot path.

Outside of that, it's a subjective matter (there are plenty of things I do favour all of the time where others might favour something else as more readable or less prone to letting typos compile, so I'm in no position to be dogmatic). 

In tests I'd be more strongly in favour of the call to `MaxValue` again though, as in tests speed is less important and clarity of what is happening all the more important.

**Comment by JonHanna** [comment]
Incidentally, while it won't go all the way to creating compile-time literal strings, Roslyn is aware of `int.MaxValue` so when used as a number then it's exactly the same as using `2147483647` or `0x7FFFFFFF`, rather than compiled as a call to a static field, so there's no downside in such cases.

**Comment by mellinoe** [comment]
The `MaxValue` members are constants, not static fields. There is no way that these values could ever change, so it's not something that needs to be considered.

**Comment by danmosemsft** [comment]
I think this is answered.

**Comment by JonHanna** [comment]
>  constants, not static fields
Yes. Pardon the thinko above.

**Comment by AdamSpeight2008** [comment]
@JonHanna  `Int.MaxValue` isn't being used for numerical value, but it's textual representation of that numerical value.
