### ISSUE TITLE
Include System.Security.Cryptography.Xml in corefx-packaging

### ISSUE THREAD

**Issue by peterwurzinger** [dotnet/corefx#16558]
In advance, this is less an issue than more a question/request for help.
We are currently [working](https://github.com/dotnet/corefx/issues/4278) on porting the S.S.C.Xml-Lib to .NET-Core. For my bachelor thesis project I already need this library very soon - a nightly/experimental/pre-alpha/whatever - build is perfectly fine though.
My question now is, what are the steps to include the project in the corefx packaging process? I did some hands-on and research but did not get far with it. Is there some kind of checklist for this? If not, could someone explain it to me so that I can include it by myself?

I'm asking because I don't expect the package to be available on myget in time.

Best wishes
Peter

**Comment by krwq** [comment]
There are couple of options you have (I assume you have some local project which needs to use crypto-xml):
- dirty way: create a new project (dotnet new - choose library), copy crypto-xml source files into that and simply refererence csproj
- cleaner way: rename *.pkgproj.disabled in in the crypto-xml folder to *.pkgproj and build, I believe this should create a nupkg somewhere in the output. In your project create a nuget.config which sets local package source to the folder with nupkg. Here is the test which does exactly this: https://github.com/dotnet/cli/blob/35547e69e979def405ff75f45d6bcb21ac23a982/test/dotnet.Tests/PackagedCommandTests.cs#L144 and here is example nuget.config https://github.com/dotnet/cli/blob/rel/1.0.0/TestAssets/NonRestoredTestProjects/ToolWithRandomPackageName/AppWithDepOnTool/NuGet.Config (go folder up to see the project which the test is operating on)

If you got any

**Comment by karelz** [comment]
@peterwurzinger why do you need NuGet package? Isn't privately-built DLL enough for your project? NuGet is IMO most valuable when you expect others to consume the work - i.e. one should shoot for stable / high-quality, etc.
(just trying to understand your motivation)

**Comment by peterwurzinger** [comment]
@krwq Thanks a lot for your advices! Unfortunately, there is no file named S.S.C.Xml.pkgproj.disabled which I could rename to get it working. Have you got another idea? Is there maybe some misconfigurationin the .pkgproj-file?

@karelz I may be wrong, but in shorter past I tried to reference a *.dll in a .NET Core library Project and it said, that '[bla] only NuGet references allowed in this version [bla]'.

**Comment by krwq** [comment]
@peterwurzinger - you might wanna do `git pull` and check under src/System.Security.Cryptography.Xml/pkg/ (I've renamed it a day or two ago)

**Comment by peterwurzinger** [comment]
@krwq Well, yeah, that explains it - sorry for that ^^
After renaming the file I did
`clean`
`sync`
`build`
and to make sure
`build-managed -packages`

Unfortunately renaming the file didn't include it in any package built.
But when I navigate into src/S.S.C.Xml/pkg and run `msbuild` it creates a System.Security.Cryptography.Xml...nupkg under bin/packages/Debug

Just for clarification: **Should** the DLL be included in a runtime-package (like runtime.win7.x64.Microsoft.Private.CoreFx....nupkg)? Or am I completely mislead on this and a seperate NuGet package for this library is just intended?

**Comment by karelz** [comment]
@peterwurzinger did you try to create Library wrapper which just copies the binary into the output? That should IMO work around the limitation. (disclaimer: I didn't try it myself)

**Comment by krwq** [comment]
@peterwurzinger if there is no platform specific code then I believe you don't need platform specific nuget packages 😄 Let me know if you had success referencing nupkg

**Comment by peterwurzinger** [comment]
@karelz No didn't try this, but I guess it's fine to use the NuGet package as is - just like @krwq mentioned. 
I'll use a private repository from my machine and remove it when it's no longer needed

**Comment by CornedBee** [comment]
Tried the clean way, but I get version conflicts all over. Our app is a netcoreapp1.0, so package restore complains because it's not compatible (the created package is netcoreapp2.0).

If I modify our app to be netcoreapp2.0, package restore works, but compilation fails with a version incompatibility in some System package (might have been System.Runtime). Looks a bit like I'd have to transitively update all dependencies as well, or at least modify the Microsoft.NetCore.App dependency (but I can't find any newer version than 1.1 on NuGet).

**Comment by peterwurzinger** [comment]
@CornedBee I tried the same thing today and came slightly further.
You will only be able to reference netstandard2-libs from a netstandard2-lib or a netcoreapp2-application - at least that's the way I unterstood it. You won't be able to build it in VS though - see [this](http://stackoverflow.com/questions/42446729/netcoreapp2-0-with-netstandard2-0). If you run `dotnet build` and/or `dotnet run` in the project directory, it will work just fine - or at least it did for me.

So I ended up with a netcoreapp2-application referencing a netstandard2-library, but am only able to build it from cmd :-(

**Comment by krwq** [comment]
@peterwurzinger which version of VS are you using (if 2017 could you check the build number in about window?) - I will check if this is something we should be already supporting

**Comment by peterwurzinger** [comment]
@krwq It's VS2017 RC, which I downloaded ~2 days ago. Unfortunately I won't be able to check the build Nr before Monday, but may have time to try to reproduce the problem on another machine with fresh binaries of VS17.

**Comment by peterwurzinger** [comment]
@krwq The full build number is
VisualStudio/15.0.0-RC.4+26206.0

**Comment by krwq** [comment]
This is already happening, closing
