### ISSUE TITLE
FileLoadException - Microsoft.Win32.Primitives when using WinHttpHandler

### ISSUE THREAD

**Issue by mkosieradzki** [dotnet/corefx#16560]
On .NET 4.6:
WinHttpHandler 4.4.0-24913-01 (4.0.2.0) depends on Microsoft.Win32.Primitives (4.0.1.0)
whilie
Microsoft.Win32.Primitives 4.4.0-24913-01 contains Microsoft.Win32.Primitives  (4.0.2.0)

This causes issues when binding redirects are not specified. Is this by design?

Consider following code running on Kestrel with IIS Express in VS2017 RC
```c#
app.Run(async ctx =>
{
    await new HttpClient(new WinHttpHandler()).GetAsync("https://example.com");
});
```
It throws FileLoadException.

**Comment by karelz** [comment]
The latest package does not have the dependency anymore: https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Net.Http.WinHttpHandler/4.4.0-beta-25027-01

Your version has it: 4.4.0-beta-24913-01

Maybe it was some point-in-time packaging bug? cc @ericstj @mellinoe

**Comment by mkosieradzki** [comment]
@karelz Thanks a lot! In https://dotnet.myget.org/feed/aspnetcore-ci-dev/ it is still in 24913 that's what made me confused.

**Comment by karelz** [comment]
OK, closing then. Let me know if you need more info/help.
