### ISSUE TITLE
Warnings should not be errors when building single test project

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#16565]
When doing development it is normal to temporarily place exception in the middle of the code to investigate issue. Treating warnings as errors causes really annoying workflow that you also need to comment out stuff below it (because of "Unreachable code detected"). This is completely valid to do as part of the full build but super annoying when building single project

**Comment by stephentoub** [comment]
FWIW, I disagree.  We should continue to treat warnings as errors, even when building individual projects.  If you'd like to suppress that locally, you can, either with pragmas or with NoWarn for specific warnings in the csproj, etc.

**Comment by danmosemsft** [comment]
Or you can set env variable TreatWarningsAsErrors=false or pass /p:TreatWarningsAsErrors=false etc.  HTH

**Comment by krwq** [comment]
@danmosemsft Thank you! I didn't know msbuild picks up environmental variables as properties!

**Comment by danmosemsft** [comment]
Yes historical trivia, a lot of HP machines once came preconfigured with an environment variable named "Platform"....
