### ISSUE TITLE
System.Data facade has a lot of bogus global stuff that should be removed

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#16571]
GenFacades isn't clearing out the global module references from the assembly when it rewrites it. We should remove those to eliminate bogus type and member references.

**Comment by mellinoe** [comment]
@weshaggard I'm not really sure what's involved with this. Could you give more info?

**Comment by weshaggard** [comment]
If you open up System.Data facade with ildasm you will see a bunch of global methods in there, I think something managed C++ uses. We need to have GenFacacdes clear out whatever stores that stuff as part of rewriting the binary. Without that we end up with a bunch of bogus type references that cause tools to have issues reading this binary.

**Comment by ericstj** [comment]
What if instead of re-writing the contract assembly we always create a new assembly with only the identity information from the contract?  That way we wouldn't preserve this garbage from the desktop reference assembly.

**Comment by mellinoe** [comment]
Yes, I was assuming we were already doing something like @ericstj said. I don't think it makes sense to shoehorn this stuff into GenFacades when we could easily just build a new assembly without any problems.

**Comment by weshaggard** [comment]
>Yes, I was assuming we were already doing something like @ericstj said. I don't think it makes sense to shoehorn this stuff into GenFacades when we could easily just build a new assembly without any problems.

I don't consider it shoehorn'ing as it was how genfacades was designed. It is only a matter of clearing one more set of stuff from the Assembly model to fix this. If you switch to generating the entire assembly from scratch there will be a bunch of potential issues that crop up that will need to be tested and dealt with. We started with the contract or partial facade intentionally so we didn't have to pass a ton of extra stuff to genfacades like, assembly version, build numbers, public key tokens, etc. Essentially any assembly level metadata will have to be passed in which we would then need to duplicate how we build our assemblyInfo.cs file and replicate it via properties into genfacades.

**Comment by ericstj** [comment]
Isn't the stuff we are using today wrong though?  The fact that this bug exists means that the cruft from the desktop assembly is being persisted rather than the meaningful stuff from the corefx build.

**Comment by weshaggard** [comment]
We already strip most things out (https://github.com/dotnet/buildtools/blob/master/src/GenFacades/GenFacades.Core/GenFacades.cs#L647) we are just missing the stripping out of the global module methods that the managed C++ compiler outputs. We haven't hit this case yet because we haven't done this generation from any managed C++ compiled assemblies until now.

**Comment by ericstj** [comment]
There are plenty of module refs in System.dll as well (from pinvokes I presume) that aren't being stripped, but I guess we didn't notice those either?

**Comment by weshaggard** [comment]
I don't see any global module level functions in our system.dll facade. Perhaps we are talking about different things. At any rate if there is other unnecessary garbage we should clean it out as well. The System.Data one came up because we end up with bogus Type/Member references in these global properties when doing analysis on facade which we don't even need so we should clean them out.

**Comment by mellinoe** [comment]
https://github.com/dotnet/buildtools/pull/1401

**Comment by weshaggard** [comment]
Thanks @mellinoe
