### ISSUE TITLE
Suggestion. Add bluetooth support

### ISSUE THREAD

**Issue by IngemarSkelander** [dotnet/corefx#16572]
It would be great to have support for pairing and IO with bluetooth devices for .net core.
It is perhaps a bit of a niche, but since self hosting is so easy in asp.net core I think more people than myself would be interested in communicating with BT devices from our self hosted web api's.

There is the 32feet bluetooth library, but it does not seem to be very active nowadays.

**Comment by karelz** [comment]
This is a great idea for independent NuGet package.
I don't believe it fits the scope of CoreFX repo though - it should not be part of the platform, but rather built on top of the platform.

Did you consider following up with 32feet authors if they take contributions or plan to move to GitHub?

**Comment by ianhays** [comment]
I agree with @karelz here. Bluetooth support is really more something that should be a separate package; it doesn't really fit under the "core" libraries. I do think it would be great to have an active, functional package for it on Nuget.
