### ISSUE TITLE
System.Threading.Tasks.Dataflow.Tests.DataflowBlockExtensionsTests.TestNullTarget_CompletionNoCaching failed with "Xunit.Sdk.EqualException" in CI

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#16599]
Configuration: OuterLoop_Fedora23_debug ([build#117](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_fedora23_debug/117/testReport/)).

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_fedora23_debug/117/consoleText

Message:
~~~
System.Threading.Tasks.Dataflow.Tests.DataflowBlockExtensionsTests.TestNullTarget_CompletionNoCaching [FAIL]
        Assert.False() Failure
        Expected: False
        Actual:   True
~~~

Stack Trace:
~~~
/mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_debug/src/System.Threading.Tasks.Dataflow/tests/Dataflow/DataflowBlockExtensionTests.cs(134,0): at System.Threading.Tasks.Dataflow.Tests.DataflowBlockExtensionsTests.TestNullTarget_CompletionNoCaching()
~~~

**Comment by Jiayili1** [comment]
Happened here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_opensuse42.1_debug/lastCompletedBuild/testReport/System.Threading.Tasks.Dataflow.Tests/DataflowBlockExtensionsTests/TestNullTarget_CompletionNoCaching/

**Comment by stephentoub** [comment]
Already fixed by https://github.com/dotnet/corefx/pull/16595
