### ISSUE TITLE
Investigate if we can build System.Security.Cryptography.Xml against netstandard

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#16594]
ref: https://github.com/tintoy/corefx/commit/eaa78efb30d3581ae871015cf9be637e6deb36c3
```diff
 <Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
   <PropertyGroup>
     <BuildConfigurations>
-      netstandard;
+      netcoreapp;
+      uap;
     </BuildConfigurations>
   </PropertyGroup>
-</Project>
+</Project>
```

Check if uap is appropriate and if it is not missing anything

cc: @danmosemsft @joperezr

**Comment by krwq** [comment]
I believe we should be trying to build using netstandard but it is ok to to netcoreapp+uap for now

**Comment by joperezr** [comment]
if we can build against netstandard, then that would be the prefered way, so that other contracts/libraries that build against netstandard can use this.

**Comment by krwq** [comment]
I believe we can't change it for now. We depend on couple of other libraries which have similar configurations and they don't build using netstandard.

**Comment by weshaggard** [comment]
>I believe we can't change it for now. We depend on couple of other libraries which have similar configurations and they don't build using netstandard.

Such as?

**Comment by krwq** [comment]
@weshaggard I was just updating my previous post to add that. Here they are:
- System.Runtime
- System.Runtime.Extensions
- System.Security.Cryptography.Algorithms

**Comment by krwq** [comment]
@weshaggard I'll look into that after we get product into better state for current configurations.

**Comment by weshaggard** [comment]
You shouldn't be directly referencing any of those if you target netstandard.dll they are included. Once you get to looking into this more I'd be interested in any issues you have building against netstandard.

**Comment by krwq** [comment]
Changing to future. This will stay netcoreapp+uap for 2.0. Close this issue if we decide that we don't want to change it in the future

**Comment by karelz** [comment]
After a discussion we decided to:
Build against .NET Standard 2.0. Create facade for Desktop (also includes Mono), so that the inbox one is picked up. Work happens in #19189.

It will impact/limitation on our ability to add new APIs in the API surface. If it is API we want eventually in Desktop (which may be none), we can take it and eventually port.
For more future-looking APIs, we will suggest to create separate package (which does not have exchange types with Desktop) and add them there.

**Comment by krwq** [comment]
@karelz FYI

**Comment by karelz** [comment]
I've noticed, it's great, thanks!
Did we change our plans or is it the same thing we discussed in Wes's office?

**Comment by krwq** [comment]
@karelz - we have found some problems with uap and netstandard - if we don't care about uap until 5/10 then everything else is as discussed:
- desktop has facade
- retarget to netstandard

additionally we had to remove few SHA2 related consts fields from the contract because they are not on netfx < 4.6.2 yet - added documentation in the wiki for that

**Comment by karelz** [comment]
Can we please have another discussion? I want to understand the plan 100%.
Packaging has high-risk of biting us back later. I want to be crystal clear on the plan -- your ""problems with ... netstandard" make me nervous.
