### ISSUE TITLE
System.Net.NetworkInformation.Functional.Tests test suite hung in CI on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#16602]
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu14.04_debug_prtest/91/consoleText
I unfortunately don't have more info than that they hung, and the build was aborted after waiting for 2 hours.
cc: @mellinoe

**Comment by karelz** [comment]
cc @steveharter @Priya91 @ianhays

**Comment by mellinoe** [comment]
Related to this in any way? https://github.com/dotnet/corefx/pull/16544 @ianhays

**Comment by ianhays** [comment]
@mellinoe That PR was in the System.Net.Ping test suite. It shouldn't make a difference to the NetworkInformation tests.

**Comment by ianhays** [comment]
kinda weird it's in the System.Net.NetworkInformation test namespace though.

**Comment by mellinoe** [comment]
Oops, my mistake. Yeah, they are all part of the same namespace. I certainly haven't made any changes here in a very long time, although I know other folks are still trying to stabilize the networking tests.

**Comment by stephentoub** [comment]
Hung again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/5174/

**Comment by karelz** [comment]
Low frequency so far, moving it to Future.

**Comment by steveharter** [comment]
Note offline CI machines do hang very rarely hang when running repeatedly; I will update here with the tests that were running at the time of the hang when I have that information.

**Comment by danmosemsft** [comment]
AGain https://ci.dot.net/job/dotnet_corefx/job/release_2.0.0/job/ubuntu14.04_release_prtest/234/console

ubuntu14.04_release

We are sorely missing a good way to investigate such hangs. We don't get dumps.

**Comment by stephentoub** [comment]
I believe this issue was addressed.  We can re-open if it happens again.
