### ISSUE TITLE
BuildConfiguration is ignored in src subfolders

### ISSUE THREAD

**Issue by marek-safar** [dotnet/corefx#16601]
When building using `C:\temp\corefx-dev\src\System.Reflection.Metadata>msbuild /p:BuildConfiguration=netstandard1.1` BuildConfiguration is ignored and netcoreapp version is built instead.

**Comment by danmosemsft** [comment]
@joperezr known?

**Comment by weshaggard** [comment]
To build netstandard1.1 configuration you should pass it as `/p:TargetGroup=netstandard1.1`.  I need to update some of the docs https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/project-guidelines.md#options-for-building as they aren't up to date.

Also note you will need to done a `build.cmd -allConfigurations` before you can build this specific configuration.

**Comment by marek-safar** [comment]
I just used what eric told https://github.com/dotnet/corefx/issues/16354#issuecomment-283113631 it also work from top level folder correctly

**Comment by weshaggard** [comment]
cc @ericstj 

I just noticed it looks like you are building the solution from root library folder which might actually have some issues I will have a look at that.

Does it work if you do that same thing from `C:\temp\corefx-dev\src\System.Reflection.Metadata\src` if not does passing TargetGroup work?

**Comment by marek-safar** [comment]
`/p:TargetGroup=netstandard1.1` still builds netcoreapp plus it fails with extra errors like

`CSC : error CS0006: Metadata file 'C:\temp\corefx-dev\bin/runtime/netstandard1.1-Windows_NT-Debug-x64/xunit.core.dll' could not be found [C:\temp\corefx-dev\src\System.Reflection.Metadata\tests\System.Reflection.Metadata.Tests.csproj]

**Comment by weshaggard** [comment]
Did you do the build from the src directory? You cannot pass those parameters to the solution files.

**Comment by mellinoe** [comment]
That error might indicate that the `netstandard1.1` targeting pack isn't built yet. `msbuild external/dir.proj /p:BuildAllConfigurations=true` would fix that.

**Comment by weshaggard** [comment]
>CSC : error CS0006: Metadata file 'C:\temp\corefx-dev\bin/runtime/netstandard1.1-Windows_NT-Debug-x64/xunit.core.dll' could not be found [C:\temp\corefx-dev\src\System.Reflection.Metadata\tests\System.Reflection.Metadata.Tests.csproj]

That indicates that the test project doesn't have a netstandard1.1 configuration so it doesn't build correctly. This is a result of using TargetGroup on the solution as opposed to the individual projects. If all you want is to build the netstandard1.1 version of System.Reflection.Metadata then you need to build in the `src\System.Reflection.Metadata\src` directory.

**Comment by mellinoe** [comment]
I think the main problem here was running `msbuild` on the solution file rather than a project file. If you're still hitting problems please let us know and we can try to give further help.
