### ISSUE TITLE
System.Tests.GCTests.GetAllocatedBytesForCurrentThread failed in CI

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#16606]
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/4033/testReport/junit/System.Tests/GCTests/GetAllocatedBytesForCurrentThread_size__100000_/

```
Allocated too little: start: 71693312 end: 71693312 size: 100000\r\nExpected: True\r\nActual: False
+++++++++++++++++++
STACK TRACE:
at System.Tests.GCTests.GetAllocatedBytesForCurrentThread(Int32 size) in D:\j\workspace\windows_nt_de---4526f5ff\src\System.Runtime\tests\System\GCTests.netcoreapp.cs:line 23
```

**Comment by danmosemsft** [comment]
@swgillespie

**Comment by swgillespie** [comment]
@danmosemsft Do you know how many procs the CI machines like this one have?

**Comment by danmosemsft** [comment]
No but I know someone who does @mmitche

**Comment by mmitche** [comment]
@swgillespie @danmosemsft 4 cores

**Comment by swgillespie** [comment]
@mmitche thanks!

**Comment by swgillespie** [comment]
@jkotas @Maoni0 Sort-of related - what is this API supposed to do when not using allocation contexts? This test always fails on my single-proc machine.

**Comment by Maoni0** [comment]
we could make it so that it checks for the # of processors and if it's 1 then don't run the test. 'cause this API is supposed to be reporting the thread's allocations.

**Comment by swgillespie** [comment]
Those are orthogonal concerns, though - you can still have multiple threads running on a single proc. I'd expect (as a developer using this API) based on the name and the API review thread that this API would work regardless of the processor topology. Should we be throwing an exception or something if we're not using allocation contexts?

**Comment by jkotas** [comment]
I do not think we should be throwing exception. We should return 0 if the allocation contexts are not supported. Is it the case today, or are we just returning some random number?

**Comment by swgillespie** [comment]
We're returning 0, yes.

**Comment by Maoni0** [comment]
you can have multiple threads running on a single proc, which is preciously the reason why I wouldn't want to support getting alloc bytes (if you only have one thread running, then it's easy - you can get accurate alloc bytes cheaply. with multiple threads you can get switched out when you read the alloc bytes from the global alloc context  which means you can be reading an inaccurate value). 

as a diagnostics API that's supposed to be very fast I would just choose to document this on msdn.

**Comment by jkotas** [comment]
So we should fix the test to accept constant 0 as a valid answer. However, it won't fix the issue that this bug is about because of the size was not zero in the log.

**Comment by swgillespie** [comment]
> as a diagnostics API that's supposed to be very fast I would just choose to document this on msdn.

Ok! My concern was that it's very unclear to developers not familiar with GC internals to understand /why/ we can't get accurate alloc bytes cheaply. 

>  However, it won't fix the issue that this bug is about because of the size was not zero in the log.

Yeah, the test is a different scenario, the CI machine has 4 procs.

**Comment by joperezr** [comment]
@swgillespie are you still working on getting this test fixed?

**Comment by saurabh500** [comment]
Another failure at https://ci.dot.net/job/dotnet_corefx/job/master/job/centos7.1_debug_prtest/4383/testReport/junit/System.Tests/GCTests/GetAllocatedBytesForCurrentThread_size__100000_/

**Comment by swgillespie** [comment]
@joperezr Taking a look today.

**Comment by AlexGhiondea** [comment]
@swgillespie I see a change was made in this area -- do we still need to do anything here?

**Comment by swgillespie** [comment]
@AlexGhiondea I think we can close this issue for now, it should be fixed by https://github.com/dotnet/coreclr/pull/10162 and https://github.com/dotnet/coreclr/pull/10284. If it still fails, we can re-open it.

**Comment by Maoni0** [comment]
this was fixed by 10284. 10162 does not affect this test.
