### ISSUE TITLE
NetworkStream.CopyToAsync/ReadAsync completing successfully on Unix when Socket disposed during call

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#16611]
On Windows this passes. On Unix sometimes the operation completes successfully without an exception being thrown.
```c#
Task copyTask = stream.CopyToAsync(new MemoryStream());
stream.Dispose();
await Assert.ThrowsAsync<IOException>(() => copyTask);
```

**Comment by stephentoub** [comment]
I spent some time digging into this.  The problem appears to be due to a difference in `shutdown` behavior between Windows and Unix: on Windows, calling Shutdown(Both) doesn't trigger the operation's completion, and then calling Dispose causes the operation to fail as OperationAborted.  On Unix, calling just Dispose() also causes the operation to fail as OperationAborted, but calling Shutdown(Both) causes the operation to complete immediately as Success.

@geoffkizer, does this sound like a fundamental OS difference, or does this sound like some issue in our shim / event-handling implementation?  I'm assuming the former, as our shutdown path here is very simple, on both Windows and Unix basically just calling the OS' `shutdown`.

**Comment by geoffkizer** [comment]
It must be a fundamental OS difference.  That said, I'm surprised that shutdown(both) doesn't trigger the operation's completion on Windows.  Strange.

It makes me wonder what happens when you do something like this:

```
Task copyTask = stream.CopyToAsync(new MemoryStream());
stream.Shutdown(ShutdownMode.Both);
await copyTask;
```

Naively, I would expect this to succeed.

From above, it sounds like this would succeed on Linux (maybe? or just sometimes?), and hang on Windows.

**Comment by stephentoub** [comment]
> Naively, I would expect this to succeed.

I expected that, too.  But this hangs on Windows:
```C#
using System;
using System.Net;
using System.Net.Sockets;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    static void Main()
    {
        using (var listener = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
        using (var client = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
        {
            listener.Bind(new IPEndPoint(IPAddress.Loopback, 0));
            listener.Listen(1);

            Task<Socket> s = Task.Run(() => listener.Accept());
            client.Connect(listener.LocalEndPoint);
            using (Socket server = s.Result)
            {
                Console.WriteLine("Connected");

                var mres = new ManualResetEventSlim();
                var saea = new SocketAsyncEventArgs();
                saea.SetBuffer(new byte[1], 0, 1);
                saea.Completed += delegate { mres.Set(); };
                if (!client.ReceiveAsync(saea)) mres.Set();

                Console.WriteLine("Shutting down client");
                client.Shutdown(SocketShutdown.Both);
                //client.Dispose();

                Console.WriteLine("Waiting");
                mres.Wait();

                Console.WriteLine("Receive completed");
            }
        }
    }
}
```
If you uncomment the Dispose, it then completes as you'd expect.  This is true on both desktop and core.

The same code always completes on Linux.  The variability on Linux is that the Dispose (closing the socket) will cause the receive to complete with an error, whereas the shutdown causes it to complete as a successful read, and there's a race condition... so if you just issue the shutdown, it'll always complete successfully, but if you issue the dispose after the shutdown, then it may sometimes complete the read successfully and may sometimes complete it with an error, based on timing.

**Comment by stephentoub** [comment]
cc: @davidsh, @cipop in case they know why this is the Windows behavior or whether there's something to be done about it

**Comment by geoffkizer** [comment]
The Windows behavior seems unfortunate.  I think we could cause the outstanding IO requests to complete if we called CancelIoEx.  This seems like better behavior than what we are doing currently.

The Linux behavior seems like arguably a bug.  Either we should consistently succeed or consistently throw OperationAborted.

**Comment by stephentoub** [comment]
> The Linux behavior seems like arguably a bug. Either we should consistently succeed or consistently throw OperationAborted.

We consistently succeed if you use shutdown.  We consistently fail with OperationAborted if you use Dispose.  If you use shutdown and then Dispose immediately after, that's when you get the inconsistency, as you introduce a race, with the completion of the operation racing with disposal.  Obviously I'd prefer for it not to be racy, and if there's an easy and cheap solution, great, let's do it, but if you're shutting down / disposing of the socket while there are active operations in flight, you're kind of asking for trouble anyway, and at the very least you shouldn't care about the results of those operations.

**Comment by stephentoub** [comment]
> The Windows behavior seems unfortunate. I think we could cause the outstanding IO requests to complete if we called CancelIoEx. This seems like better behavior than what we are doing currently.

@davidsh or @cipop should comment on that.

**Comment by geoffkizer** [comment]
@stephentoub Yeah, seems reasonable.

Does the same behavior happen with sync operations?

**Comment by stephentoub** [comment]
> Does the same behavior happen with sync operations?

Yes.  This also hangs on Windows on desktop and core, and completes on Linux:
```C#
using System;
using System.Net;
using System.Net.Sockets;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    static void Main()
    {
        using (var listener = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
        using (var client = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
        {
            listener.Bind(new IPEndPoint(IPAddress.Loopback, 0));
            listener.Listen(1);

            Task<Socket> s = Task.Run(() => listener.Accept());
            client.Connect(listener.LocalEndPoint);
            using (Socket server = s.Result)
            {
                Console.WriteLine("Connected");

                Task t = Task.Run(() => client.Receive(new byte[1]));
                Thread.Sleep(1000); // give the task time to start the receive

                Console.WriteLine("Shutting down client");
                client.Shutdown(SocketShutdown.Both);
                client.Dispose();

                Console.WriteLine("Waiting");
                ((IAsyncResult)t).AsyncWaitHandle.WaitOne();

                Console.WriteLine("Receive completed");
            }
        }
    }
}
```
