### ISSUE TITLE
Failure in System.Net.Http.Functional.Tests/DiagnosticsTest/SendAsync_ExpectedDiagnosticCancelledLogging/

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16610]
Broken out of https://github.com/dotnet/corefx/issues/16430

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_debug/109/testReport/System.Net.Http.Functional.Tests/DiagnosticsTest/SendAsync_ExpectedDiagnosticCancelledLogging/

**Comment by karelz** [comment]
cc @steveharter @Priya91 @ianhays

**Comment by Priya91** [comment]
```
MESSAGE:
Timed out after 60000ms waiting for remote process 5512\r\nExpected: True\r\nActual: False
+++++++++++++++++++
STACK TRACE:
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() in D:\j\workspace\outerloop_win---097a300f\src\Common\tests\System\Diagnostics\RemoteExecutorTestBase.cs:line 176 at System.Net.Http.Functional.Tests.DiagnosticsTest.SendAsync_ExpectedDiagnosticCancelledLogging() in D:\j\workspace\outerloop_win---097a300f\src\System.Net.Http\tests\FunctionalTests\DiagnosticsTests.cs:line 234
```

**Comment by Priya91** [comment]
Not able to repro locally.

**Comment by Jiayili1** [comment]
This issue is repro on: OuterLoop_WIndows10_debug ([build#122](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_debug/122/testReport/))

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_debug/lastCompletedBuild/testReport/System.Net.Http.Functional.Tests/DiagnosticsTest/SendAsync_ExpectedDiagnosticCancelledLogging/

**Comment by karelz** [comment]
@Priya91 OneNote updated with another hit

**Comment by Jiayili1** [comment]
The following test: System.Net.Http.Functional.Tests.DiagnosticsTest/SendAsync_ExpectedDiagnosticCancelledActivityLogging 
 failed with the same issue

Message:
~~~
Timed out after 60000ms waiting for remote process 3496\r\nExpected: True\r\nActual:   False
~~~

Stack Trace:
~~~
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
   at System.Net.Http.Functional.Tests.DiagnosticsTest.SendAsync_ExpectedDiagnosticCancelledActivityLogging()
~~~

Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170328.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.DiagnosticsTest~2FSendAsync_ExpectedDiagnosticCancelledActivityLogging

**Comment by Jiayili1** [comment]
Failed again here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_release/141/testReport/System.Net.Http.Functional.Tests/DiagnosticsTest/SendAsync_ExpectedDiagnosticCancelledActivityLogging/

**Comment by karelz** [comment]
@steveharter bumping priority to P2 in OneNote due to frequency of failures (1/week)

**Comment by steveharter** [comment]
When running the tests in loop on a CI machine, this test failure is common (verified on both Win7 and Win10)

**Comment by Jiayili1** [comment]
Failed again here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win10_debug/1/testReport/System.Net.Http.Functional.Tests/DiagnosticsTest/SendAsync_ExpectedDiagnosticCancelledActivityLogging/

**Comment by Jiayili1** [comment]
This issue is repro on portable core tests: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170407.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.DiagnosticsTest~2FSendAsync_ExpectedDiagnosticCancelledActivityLogging

**Comment by steveharter** [comment]
I was able to repro this on 2008 machines running repeatedly.
```
   System.Net.Http.Functional.Tests.DiagnosticsTest.SendAsync_ExpectedDiagnosticCancelledActivityLogging [FAIL]
      Timed out after 60000ms waiting for remote process 912
      Expected: True
      Actual:   False
      Stack Trace:
            at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
            at System.Net.Http.Functional.Tests.DiagnosticsTest.SendAsync_ExpectedDiagnosticCancelledActivityLogging()
```
