### ISSUE TITLE
Port source for FileVersionInfo test binaries

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#16613]
We don't have source for ```NativeLibrary.dll``` or ```SecondNativeLibrary.dll``` available anywhere. I wasn't able to find it in the TFS maze, but it wouldn’t be difficult to rewrite them if we can’t find the source and decide we need the ability to rebuild them.

They don't need to be included in the build, but they need some sort of instructions to build or a batch script alongside the sources so we can rebuild them easily in the future when needed. They should probably go to https://github.com/dotnet/corefx-testdata

**Comment by karelz** [comment]
What are the libraries for? Are they part of tests?

**Comment by ianhays** [comment]
Yes, they're used in the System.Diagnostics.FileVersionInfo tests.

**Comment by karelz** [comment]
"test enhancement" then :) ... given that we do not know the original source internally, should we even remove the "port-to-core", describe what they should do and mark it as "up for grabs"?

**Comment by ianhays** [comment]
Yeah, the work-item here is to write new sources for a native binary to https://github.com/dotnet/corefx-testdata that when built using a script (which also needs to be written) produces binaries that can be used interchangeably with those currently in the System.Diagnostics.FileVersionInfo tests.

**Comment by danmosemsft** [comment]
Not sure why this is 2.0 @weshaggard

**Comment by attilah** [comment]
I've recreated all the 3 binaries, currently as a VS2017 solution, all the tests are passing, but not sure how would you like to have it included here? How you're building vcxprojs, etc.

I just found [System.ServiceProcess.ServiceController.TestNativeService.vcxproj](https://github.com/dotnet/corefx/blob/62212cca900081173fce70991c3a0b30393994a3/src/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.TestNativeService/System.ServiceProcess.ServiceController.TestNativeService.vcxproj) as a possible example, would that vcxproj used as a template work for your build process?

**Comment by karelz** [comment]
Thanks @attilah - assigned to you!
I let @ianhays provide details.

**Comment by attilah** [comment]
@karelz, I submitted the fix, but obviously it fails to build for *nix, I think we need some magic tricks (settings) to exclude those from building for *nix, I don't have that knowledge about how this works in corefx (yet) ;-) 99% is there :-)

**Comment by karelz** [comment]
Got it. I am actually not sure if @ianhays didn't suggest to move the source code to corefx-testdata ... let's wait for him to reply ...

**Comment by ianhays** [comment]
These are tiny enough that I'm fine with leaving them in CoreFX. It's way less work having them build with CoreFX. 

I like using corefx-testdata because I like the separation, but it isn't practical to push a new package of Corefx-testdata for a few source files.

**Comment by weshaggard** [comment]
I'm fine with these remaining in corefx as well, but I just added feedback in the PR to probably not build them live so that we can actually run these tests on all platforms.

**Comment by karelz** [comment]
Moving back to up-for-grabs as @attilah doesn't currently have time to finish it.
Anyone interested in picking it up? Just let us know and feel free to build on top of @attilah's PR #16711.

**Comment by alexperovich** [comment]
I will pick this up.
