### ISSUE TITLE
using pool for buffer in HashAlgorithm

### ISSUE THREAD

**Issue by heejaechang** [dotnet/corefx#16622]
this creates new 4K buffer every time computing hash

https://github.com/dotnet/corefx/blob/e9ecf74d845476540f40fa8fdc62c53ebf048519/src/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/HashAlgorithm.cs#L78

which is probably fine when creating hash for 1 or 2 values. but when creating large numbers of hashes that adds up quite quickly.

one of examples of those cases will be C# compiler compiling that need to create SHA1 hashes for all source files and many more for pdb and other identifies. 

pooling that buffer seems easy allocation win.

**Comment by danmosemsft** [comment]
Presumably such code should be sure to pass the "clear" flag when it returns the rented buffer. It's off by default.

**Comment by heejaechang** [comment]
buffer I am talking about is local to the method, never given out to users.

**Comment by danmosemsft** [comment]
I was talking about https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Buffers/src/System/Buffers/ArrayPool.cs

Do you mean keeping a static 4KB allocation permanently after the first call to this API?

**Comment by heejaechang** [comment]
no, I didn't know about the ArrayPool. that looks like good one to use to reduce allocations.

**Comment by heejaechang** [comment]
related issue in devdiv - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/279424 opened by devdiv perf team.

**Comment by danmosemsft** [comment]
Does the code in the dev issue (Roslyn in VS context) run on Core? If not fixing this would not help, of course.

We'd accept a PR, any interest? :)

**Comment by heejaechang** [comment]
that particular code path might not actually, but compiler do call this method as much as that code path for checksum as well. and compiler do run in core, so I believe still valid.

**Comment by heejaechang** [comment]
@danmosemsft what should need to be changed for desktop .net fx?

**Comment by danmosemsft** [comment]
We have a relatively high bar for desktop changes at the moment. They go through a quite different process, and shiproom. If it's a VS request, that adds weight. I would take it offline with @AlexGhiondea who can speak to the process for desktop. This issue can remain open for a potential corefx change.

**Comment by bartonjs** [comment]
Changing to a pooled buffer seems reasonable, but since this is currently the same behavior as netfx I don't think that we need to commit to this for 2.0.  (PRs are always welcome).
