### ISSUE TITLE
OverflowException when casting int to short

### ISSUE THREAD

**Issue by corivera** [dotnet/corefx#16635]
The following code succeeds when running a test app created via "dotnet new", but fails when running in our System.Data tests on the latest version of CoreFx. Similar code was succeeding in SqlClient at least 2 weeks ago, but has been causing test failures recently.

            int value = 0xff << 8;
            short shortValue = (short)value;

This gets thrown on the line for the cast to a short:
System.OverflowException : Arithmetic operation resulted in an overflow.

@saurabh500 @stephentoub

**Comment by corivera** [comment]
Failing casts in SqlClient:
https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlBuffer.cs#L1092
https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/TdsParser.cs#L1558

**Comment by corivera** [comment]
@danmosemsft

**Comment by saurabh500** [comment]
@danmosemsft @stephentoub Can you help get the right folks on this? 
The tests in Manual tests for SqlClient which we execute while changing the code were running fine until 2 weeks ago, started failing. We don't know the exact point of this regression right now. 
These tests have been working well for over a year.

**Comment by danmosemsft** [comment]
This should have fixed it.
https://github.com/dotnet/corefx/pull/16620
