### ISSUE TITLE
Investigate Issues with DCS/DCJS Reflection-based Serialization on Uapaot

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#16645]
Upon the completion of #16644, we'd like to investigate if Reflection-based Serialization for DCS/DCJS work on Uapaot.

**Comment by karelz** [comment]
@shmao I added labels & milestone on your behalf, please review them.

**Comment by shmao** [comment]
I am done with my investigation on the remaining DCS/DCJS test failures in ReflectionOnly mode on uapaot. The remaining test failures basically fall into the following 3 categories,

1. DCS cannot serialize Exception types on UWP because of https://github.com/dotnet/corefx/issues/19585
2. DCS cannot serialize struct types because of  #19665. This is being tracked by https://github.com/dotnet/corefx/issues/19663.
3. DCS cannot serialize System [Serializable] types because reflection on System types' private members are blocked.
