### ISSUE TITLE
Run DCS/DCJS Tests in CoreFx against uapaot.

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#16644]
Running tests against uapaot is not supported. The task is to make our DCS/DCJS test projects build and run against uapaot.

**Comment by karelz** [comment]
@shmao I added "test enhancement" and milestone:2.1.0 on your behalf

**Comment by shmao** [comment]
This is done. A few issues have been addressed to unblock the build of the test. Here's a couple,

https://github.com/dotnet/corefx/issues/16692
https://github.com/dotnet/corefx/issues/16772
