### ISSUE TITLE
System.Reflection.Metadata fails to read offset of DataDirectories spanning across multiple sections

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#1664]
If an assembly contains any DataDirectory which is in more than one section we throw "System.BadImageFormatException : Section too small.". While I agree we should not have any assemblies like that we unfortunately already shipped one which has this issue.

I believe we can still calculate the offset without checking ranges (or we can check the global range only)

Example can be found here:
https://github.com/krwq/corefx/tree/pereaderdatadir

This is basically:
```csharp
using (FileStream fs = new FileStream(@"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.JScript.dll", FileMode.Open, FileAccess.Read, FileShare.ReadWrite | FileShare.Delete))
{
    using (PEReader reader = new PEReader(fs, PEStreamOptions.LeaveOpen | PEStreamOptions.PrefetchEntireImage | PEStreamOptions.PrefetchMetadata))
    {
        int offset;
        if (reader.PEHeaders.TryGetDirectoryOffset(reader.PEHeaders.PEHeader.CertificateTableDirectory, out offset))
        {

        }
    }
}
```

**Comment by nguerrera** [comment]
cc @tmat

**Comment by krwq** [comment]
I believe that removing this should fix this bug:
https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEHeaders.cs#L307-L310
