### ISSUE TITLE
Investigate Issues with DCS/DCJS Serializing ISerializable on Uapaot

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#16647]
Upon the completion of #16644, we'd like to investigate if DCS/DCJS can serialize ISerializable types on Uapaot.

**Comment by karelz** [comment]
@shmao I updated labels & milestone on your behalf, please verify my changes.

**Comment by shmao** [comment]
DCS and DCJS now are able to serialize `ISerializable` types on UWP. Serializing Exception types still failed on UWP due to https://github.com/dotnet/corefx/issues/19585
