### ISSUE TITLE
Make Microsoft.CSharp use the coding style more like the rest of corefx

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#16664]
I've already done some changes along these lines, though mostly when there was another benefit (if often a pretty tiny optimisation if considered solely as such).

Having been ported from C++ code has left its mark in some strange constructs, unconventional names, Get/Set method pairs instead of (or as well as) properties, etc. I don't know about anyone else, but I think I would have found the fixes at #15397 and #16085 a lot quicker than I did if the code more closely followed common C# conventions.

This issue is to track changes to make the coding style more usual, which I intend to do in earnest once I've finished #8081 as my current long-burner issue. I intend to do so incrementally as one massive PR would be a nightmare to review.

This also gives anyone who can think of a good reason for leaving alone somewhere to say so. In particular, I'm assuming that dead code (there are some entirely dead types in there) originates from the static compiler it was ported from having cases that don't arise with dynamic code. Can someone confirm this, rather than there being another reason  — e.g. some code wasn't ported from the desktop version — and hence a reason to leave that dead code in there?

**Comment by krwq** [comment]
@JonHanna https://github.com/dotnet/codeformatter should fix most of the issues in an instant

**Comment by JonHanna** [comment]
That's definitely going to be used, but it doesn't deal with some of the things I'm thinking of. It won't do any of the first ("clean-up") part of #16663 and given:

```C#
internal sealed class EXPRRETURN : EXPRSTMT
{
    // Return object is optional because of void returns.
    private EXPR OptionalObject;
    public EXPR GetOptionalObject() { return OptionalObject; }
    public void SetOptionalObject(EXPR value) { OptionalObject = value; }
}
```

It will produce:

```C#
internal sealed class EXPRRETURN : EXPRSTMT
{
    // Return object is optional because of void returns.
    private EXPR _optionalObject;
    public EXPR GetOptionalObject() { return _optionalObject; }
    public void SetOptionalObject(EXPR value) { _optionalObject = value; }
}
```

Whereas I think that would be better as:

```C#
internal sealed class ExprReturn : ExprStatement
{
    // Return object is optional because of void returns.
    public Expr OptionalObject { get; set; }
}
```

(Or possibly a readonly property that is set by a constructor, if that would work).

**Comment by krwq** [comment]
@JonHanna - would it be possible to write rules for that? It would be nice to get CodeFormatter more up to date and at the same time do some useful refactoring

**Comment by JonHanna** [comment]
Certainly the more that can be automated the better, though having `GetXXX()`/`SetXXX()` pairs is pretty rare when something isn't ported from another language, so it may not be very useful generally.

Having members differentiated only by case which are sometimes functional duplicates of each other (so one can go and the references updated) and sometimes not isn't going to be very amenable to fully automated change because the correct change depends on a bit of human judgement. It seems (though maybe there was an error on my part) that such cases get left alone in that the rules want to change the case of at least one member, but then realise that can't be safely done.

**Comment by stephentoub** [comment]
A bunch of work was already done here.  Folks are welcome to clean things up further, but I'm going to close the issue as we no longer need one tracking potential clean up here.
