### ISSUE TITLE
 CSharpCodeGenerator outputs sealed override methods as virtual

### ISSUE THREAD

**Issue by jimmyjudas** [dotnet/corefx#16662]
CSharpCodeGenerator will output a method with Attributes of `Public`, `Final` and `Override` as a virtual method. I guess it should be output as a sealed override method

```c#
[Test]
public void SealedOverride()
{
    using (CSharpCodeProvider provider = new CSharpCodeProvider())
    {
        CodeMemberMethod method = new CodeMemberMethod
        {
            Name = "TestMethod",
            Attributes = MemberAttributes.Public 
                         | MemberAttributes.Final 
                         | MemberAttributes.Override,
            ReturnType = new CodeTypeReference(typeof(string))
        };

        using (var writer = new StringWriter())
        {
            provider.GenerateCodeFromMember(method, writer, new CodeGeneratorOptions());
            string output = writer.ToString().Replace("\r\n", string.Empty);
            Assert.AreEqual(output, "public sealed override string TestMethod() {}");
            //Actually outputs "public virtual string TestMethod() {}"
        }
    }
}
```

**Comment by JonHanna** [comment]
Could this just be because `override` isn't valid unless it actually is a method in a base to override (CS0115) and it's avoiding outputting code that violates that rule?

**Comment by JonHanna** [comment]
Likewise CS0238 would then be a sensible reason for not including `sealed` in the output.

**Comment by svick** [comment]
As far as I can tell, this behavior is very confusing, but correct. [The documentation for `MemberAttributes`](https://msdn.microsoft.com/en-us/library/system.codedom.memberattributes(v=vs.110).aspx) says:

> There is no **Virtual** member attribute. A member is declared virtual by setting its member access to Public (`property1.Attributes = MemberAttributes.Public`) without specifying it as Final. The absence of the Final flag makes a member **virtual** in C# (`public virtual`), **overrideable** in Visual Basic (`Public Overrideable`). To avoid declaring the member as **virtual** or **overrideable**, set both the Public and Final flags in the Attributes property.

So, `MemberAttributes.Final` means "not `virtual`", it does not mean `sealed`.

Looking at [the code](https://referencesource.microsoft.com/#System/compmod/microsoft/csharp/csharpcodeprovider.cs,60cbfd6d2ea91076), this all looks deliberate, not like a bug.

Considering that CodeDOM is legacy code and that changing this would be a breaking change, I wouldn't expect it to change.

**Comment by jimmyjudas** [comment]
@JonHanna My example does miss out the base class and method, you're right. But we get the same behaviour in legitimate actual class hierarchy, plus removing the Final flag in my example does output an override method. But it was a good thing to point out regardless!

**Comment by jimmyjudas** [comment]
@svick The code could also be interpreted as someone not having considered the sealed override possibility in the first place :) But I certainly see your point about breaking changes. Thanks for looking at it anyway.
