### ISSUE TITLE
RemoteExecutorConsoleApp not restoring on some Fedora test runs

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#16688]
The `RemoteExecutorConsoleApp.exe` that is used in the `System.Diagnostics.Process` tests is either missing or can't be accessed on some Fedora test runs. It happens infrequently, but enough to cause these failures:
- https://github.com/dotnet/corefx/issues/16488
- https://github.com/dotnet/corefx/issues/16400
- https://github.com/dotnet/corefx/issues/15844

FYI @stephentoub @Priya91

**Comment by stephentoub** [comment]
@ianhays, interesting. Are you saying that all of those exit code 145s happen when the forked process fails to find or open the remote executor exe?

**Comment by ianhays** [comment]
Yup. I grabbed a fedora VM and ran the tests without the Remote*exe in the directory and reproduced the above 3 failures.

**Comment by ianhays** [comment]
I'm getting all of the failures at once though when I do that, whereas in the above failures they are only one at a time. Maybe there's some interference or something that is blocking off the exe from being used in a test and dotnet is failing because of it?

**Comment by Jiayili1** [comment]
15844 is repro, failed again: https://ci.dot.net/job/dotnet_corefx/job/master/job/fedora23_release/1290/testReport/System.Diagnostics.Tests/ProcessWaitingTests/SingleProcess_EnableRaisingEvents_CorrectExitCode_exitCode__0_/

**Comment by stephentoub** [comment]
Another case here:
https://github.com/dotnet/corefx/issues/17180

**Comment by danmosemsft** [comment]
HandleCountChanges failed again. @ianhays what do you recommend as the next step?

**Comment by Jiayili1** [comment]
Another case here: #17180 

Failed test: System.Diagnostics.Tests.ProcessTests.HandleCountChanges

~~~
MESSAGE:
Assert.Equal() Failure\nExpected: 42\nActual: 145
+++++++++++++++++++
STACK TRACE:
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora24_release/src/Common/tests/System/Diagnostics/RemoteExecutorTestBase.cs:line 170
~~~

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_fedora24_release/132/testReport/System.Diagnostics.Tests/ProcessTests/HandleCountChanges/

**Comment by danmosemsft** [comment]
@ianhays now you're back could you give an update? sevearl tests hitting this.

**Comment by ianhays** [comment]
Yes, this is on my short list. 

I expect we can add a line or two in the RemoteExecutorTestBase to check for the existence/accessibility of the Remote\*exe before starting the process. Alternatively, we can fail gracefully or retry if the Remote\*exe failed to start with this particular error code.

Either of those solutions would be a cure for the symptom, but not necessarily for the disease. I still don't know why the Remote\*exe app would be missing or unavailable intermittently. Maybe one of the tests that uses the RemoteExecutorTestBase is doing something weird, or maybe the RemoteExecutorTestBase locks against the Remote\*Exe at such a time that it would cause another Remote*Base to fail to start the Remote\*Exe. Probably something else, some oddity around Fedora of which I'm not yet aware. I'm going to look into it more before pushing any band-aid fixes, so any other brainstorming ideas are welcome.

**Comment by ianhays** [comment]
The first failure of this type occurred on February 6th. It fails roughly once a week, so I looked at the changes in the history of these tests and the runner in the 2 weeks before that first failure. There are two commits that meet that criteria:

- [Remove versioned configuration from test projects (#15879)](https://github.com/dotnet/corefx/commit/62212cca900081173fce70991c3a0b30393994a3)
- [Enable compiling the test projects against the configuration (#15743)](https://github.com/dotnet/corefx/commit/e79912f8b77bc22abfd85e94b74c06e5d99e8381)

Of those two, it is likely that the [commit enabling configuration builds for test projects](https://github.com/dotnet/corefx/commit/e79912f8b77bc22abfd85e94b74c06e5d99e8381) brought about the failures. Unfortunately that doesn't really help us narrow down the cause of the failures any beyond knowing that it's possible that netstandard13 as the build config passed and netstandard doesn't.

**Comment by Priya91** [comment]
@ianhays Could it be the case that the number of open descriptors on the file is exceeded, hence the process is not able to open the remote exe? Also, if it's the case of infrastructure changes, then shouldn't the failure happen consistenly, with the file missing after building the libs..

**Comment by ianhays** [comment]
> Could it be the case that the number of open descriptors on the file is exceeded, hence the process is not able to open the remote exe? 

Does a file have an associated max number of descriptors that can be open on it? I know there are system and user open fd limits, but I wasn't aware of per-file limits. That could explain it.

>Also, if it's the case of infrastructure changes, then shouldn't the failure happen consistenly, with the file missing after building the libs.

You're right, I don't think it's an infrastructure problem because then all of the tests would be failing, not just one or two intermittently. Something more subtle is happening here.

**Comment by ianhays** [comment]
The last recorded instance of a test failing in this manner was on 4/21. With the additional logging provided by #18868 that specifies whether this is (probably) an issue with the Remote*exe being unavailable, I feel comfortable pushing this back to Future at least until we get another failure to see if #18868 is hit.

The alternative would be to go ahead and add a retry mechanism to the current File.Exists check on the Remote*exe with a short waiting period before checking again. I'd really prefer to not do that until we see that check actually being hit though.

**Comment by stephentoub** [comment]
Failed here with the additional logging:
https://ci.dot.net/job/dotnet_corefx/job/master/job/fedora24_debug/2513/consoleText
https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Diagnostics/RemoteExecutorTestBase.cs#L175
```
     System.Diagnostics.Tests.ProcessTests.TestExitTime [FAIL]
        System.IO.IOException : RemoteExecutorConsoleApp test app isn't present in the test runtime directory.
        Stack Trace:
  Starting:    System.Globalization.Tests
           /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/src/Common/tests/System/Diagnostics/RemoteExecutorTestBase.cs(177,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvoke(MethodInfo method, String[] args, RemoteInvokeOptions options)
           /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/src/Common/tests/System/Diagnostics/RemoteExecutorTestBase.cs(42,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvoke(Func`1 method, RemoteInvokeOptions options)
           /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/src/System.Diagnostics.Process/tests/ProcessTestBase.cs(44,0): at System.Diagnostics.Tests.ProcessTestBase.CreateProcess(Func`1 method)
           /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/src/System.Diagnostics.Process/tests/ProcessTestBase.cs(64,0): at System.Diagnostics.Tests.ProcessTestBase.CreateProcessLong()
           /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/src/System.Diagnostics.Process/tests/ProcessTests.cs(177,0): at System.Diagnostics.Tests.ProcessTests.TestExitTime()
```

**Comment by ianhays** [comment]
Well there we have it. Took long enough.

So what we do think then, should we loop around the `Exists` check on the `Remote*Exe` and hope that it's available at a later time? That may not completely resolve these errors we're seeing as the exe could still go missing between the File.Exists check and the invocation.

**Comment by stephentoub** [comment]
It's not clear to me whether this lack of existing represents a failure to copy/link the file or a race condition that it's not there.  If it's the former, retrying wouldn't really help.  If it's the latter, it might be. @MattGal, do you know why the file wouldn't be there once in a while (and apparently only on Fedora)?

**Comment by MattGal** [comment]
@stephentoub I have not seen this specific mode of failure before.  In most cases, missing files are the result of a package restore issue, but that wouldn't explain the sporadic nature of the problem described.  

From looking at the logs, the remote executor is in the Helix Correlation payload ("present in the test runtime directory.") so if something somehow deleted this file but not the zip it came in, this sort of problem could manifest.  I will investigate and get back shortly.

**Comment by MattGal** [comment]
My mistake, this is a Jenkins-y thing, disregard previous comment.  @mmitche should be looped to help investigate.

**Comment by danmosemsft** [comment]
@ianhays  I haven't seen this since, I wonder if it "fixed itself" and we should close this meantime?

**Comment by ianhays** [comment]
I'm fine with that :) If it fails again it should be obviously due to this issue because of the logging, so no harm in closing this issue until we see it again.
