### ISSUE TITLE
build -? should explain potential parameter values

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16694]
@danmosemsft commented on [Fri Mar 03 2017](https://github.com/dotnet/buildtools/issues/1366)

`build -?` lists what the parameters do but not the values for them. EG.,

```
[-framework]              Sets target framework for native build configuration which is used for copying to the common shared runtime folder.
```

This doesn't tell me what I want to know which is, how to build for UAP (for example). What I need to know is `build.cmd -framework:uap`   or `-framework:uapaot`

This is in https://github.com/dotnet/corefx/blob/8b7f07d22575aad4b90afbe65df05bd23e5d60be/Documentation/coding-guidelines/project-guidelines.md  but it's referred to as `TargetGroup` in that documentation. EXternal contributors won't be able to figure this out.

---

@danmosemsft commented on [Fri Mar 03 2017](https://github.com/dotnet/buildtools/issues/1366#issuecomment-284054932)

@joperezr 

---

@joperezr commented on [Fri Mar 03 2017](https://github.com/dotnet/buildtools/issues/1366#issuecomment-284073327)

This issue should be moved to corefx instead, since the right place to fix it is [here](https://github.com/dotnet/corefx/blob/master/config.json#L284-L288)

---

@weshaggard commented on [Fri Mar 03 2017](https://github.com/dotnet/buildtools/issues/1366#issuecomment-284093718)

Ideally this information would be pulled from https://github.com/dotnet/corefx/blob/master/config.json#L6.

**Comment by ViktorHofer** [comment]
We should be able to do that now in the build.ps1 and build.sh script under /eng but probably need to duplicate the descriptions as we already do for the commands.

**Comment by ViktorHofer** [comment]
Fixed.
