### ISSUE TITLE
Serialization Tests Failed on UAPAOT due to RuntimeHelpers.GetUninitializedObject Missing

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#16692]
Many of serialization tests are failing on uapaot due to the following exception,

> System.MissingMethodException : Method '**RuntimeHelpers.GetUninitializedObject(Type)**' was not included in compilation, but was referenced in FormatterServices.GetUninitializedObject(Type). There may have been a missing assembly.

According to [ApiCompatBaseline.uapaot.txt](https://github.com/dotnet/corefx/blob/45ecf2a1ef245433d544aa88b8b69ba26b368288/src/System.Runtime/src/ApiCompatBaseline.uapaot.txt#L195), the method seems not implemented by corelib. We need to implement the method to unblock the serialization tests on uapaot.

**Comment by MichalStrehovsky** [comment]
Cc @morganbr

**Comment by morganbr** [comment]
This is checked into ProjectN TFS now. I believe that will sync over to CoreFX Sunday night or Monday morning.
