### ISSUE TITLE
API to get DSA signature length

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#16690]
DSA signature length seems to be 40 + value depending on ASN1 encoding. Is there some consistent API where we could check that? On Desktop it seems to always be 40 bytes but on .NET Core we seem to be creating 64 byte length signatures (could be a bug on .NET Core too).

Related test:
System.Security.Cryptography.Xml: SignedXmlTest.AsymmetricDSASignature

**Comment by karelz** [comment]
@krwq can you please fill issue type and milestone?

**Comment by bartonjs** [comment]
On Desktop we default to 1024-bit DSA, which follows FIPS 186-2.

On CoreFx we use 2048-bit DSA, following FIPS 186-3, on the systems that support it.

In general, you shouldn't care what the size the signature is, the crypto libraries will do that for you.  I'm not sure that there are real use cases for knowing what the expected size would be.

The smallest answer is 40 bytes for the output of DSA::SignData, which uses the IEEE P1363 format.  If the particular application (like SignedXml) uses the ASN format it'll *probably* be bigger.  IEEE P1363 encodes leading zeroes, ASN doesn't.  So, technically speaking, `30 06 02 01 00 02 01 00` is a valid DSA (ASN/DER) signature of any size Q.

**Comment by krwq** [comment]
@bartonjs I can see at least couple of use cases - i.e. if you were signing some binary blocks and wanted to inject a signature somewhere in the middle you need to leave some space for it and you need to know how much. I'll leave this issue for you to decide if we want this or not.

**Comment by bartonjs** [comment]
Well, the answer on that is to call dsa.SignData(), which gives back a new array, and that's the IEEE P1363 signature length.  If you need it in ASN/DER you'd need to translate it, at which point you'd know the size.

If we had "sign into this spot" it might make more sense, but the ASN length can't be known a priori.

I'm going to go ahead and close this; but if there's a strong need and someone wants to design an API for it, it's easy enough to reactivate.

**Comment by karelz** [comment]
@krwq please check [simplified triage rules](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified) - only 1 issue type label ;-)
