### ISSUE TITLE
CultureInfo.GetCultures missing in .NET Core

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/corefx#1669]
We're currently building out the support for language resources and i18n/l10n in ASP.NET 5/DNX and we're wondering why there doesn't appear to be a way to retrieve a list of all available cultures in .NET Core. Right now it appears our only option for determining if a culture string is valid is to attempt to create a `CultureInfo` object from it using the `CultureInfo(string name)` ctor, and catching the resulting `CultureNotFoundException` if it's indeed invalid. This feels sub-optimal.

**Comment by tarekgh** [comment]
As the framework depends on the OS for getting the cultures, the OS's is moving to the model any BCP-47 culture name become valid even the OS is not supporting it. for instance, Windows 10 is supporting any well formed culture name even the OS don't have real data for such culture. for example, if trying to create a culture "xx-XXXX" in Windows 10 it will succeed. 
considering that, it doesn't make sense to have culture enumeration as any set we return doesn't mean these are the only supported cultures. 
looking at your issue, you workaround is acceptable. if really want to have more better way, we can consider something like CultureInfo.TryGetCulture() but as I said previously moving forward almost any culture will be valid.

**Comment by DamianEdwards** [comment]
I see. Do you know if we're also updating the resx tooling in msbuild and VS to work like this too? Right now it seems that VS detects when a resx file or other embedded file is named with a valid culture name as a suffix and acts appropriately (creates a generates Resources.cs, embeds the files in satellite assemblies, etc.).

Will there be a way to determine if a given CultureInfo object had its values populated from a known OS culture vs. it being allowed just because its name was BCP-47 compliant? Also, what are the plans for how this will work on .NET Core for Linux and OSX?

**Comment by tarekgh** [comment]
> I see. Do you know if we're also updating the resx tooling in msbuild and VS to work like this too? Right now it seems that VS detects when a resx file or other embedded file is named with a valid culture name as a suffix and acts appropriately (creates a generates Resources.cs, embeds the files in satellite assemblies, etc.).

I am not aware of any updates in this area but my understanding is resource handling depends on the success of creating a culture.

> Will there be a way to determine if a given CultureInfo object had its values populated from a known OS culture vs. it being allowed just because its name was BCP-47 compliant?

Currently there is no specific way but I am wondering why need to detect that? the whole idea of having any BCP-47 name is to work seamlessly without worrying of existing such culture. 

> Also, what are the plans for how this will work on .NET Core for Linux and OSX?

My understanding is some of Linux based systems already does what Windows 10 is doing which is provide a culture for any BCP-47. for the systems don't do that, it'll work as Windows 8 which is culture creation will throw for any culture the OS cannot create. so wrapping culture creation inside try-catch block will still be the way to detect that. if we are really find this is a scenario many people will run into, we can consider provide TryCreateCulture or so to avoid the exception.

**Comment by DamianEdwards** [comment]
Here is what I've done to essentially recreate on .NET Core what .NET Framework did for us previously with regards to caching instances of `CultureInfo` and handling the exception cases gracefully. Assuming this is inline with your thoughts I think we can stick with this approach.

https://github.com/aspnet/Localization/blob/dev/src/Microsoft.AspNet.Localization/Internal/CultureInfoCache.cs

**Comment by tarekgh** [comment]
yes this looks good to me.

Let me know if I can close the issue or you have any more questions.
Thanks for bringing this issue.

**Comment by DamianEdwards** [comment]
@tarekgh in thinking about this some more this presents some challenges for us in server scenarios, as caching based on user input is a no-go. We want a great experience OOTB but without a known list of cultures ahead of time this isn't really possible and we need to cache (the perf overhead of `CultureInfo` on the server is just too large). We're currently considering generating the list ahead of time using .full NET Framework APIs on Windows and shipping that in its own package for our scenarios but wanted your input.

https://github.com/aspnet/Localization/issues/6

**Comment by tarekgh** [comment]
Do you have the choice of detecting you are running on Windows and then PInvoke to the API EnumSystemLocalesEx

https://msdn.microsoft.com/en-us/library/windows/desktop/dd317829(v=vs.85).aspx

this can help getting the set from Windows at runtime and should work on different versions of Windows.

**Comment by DamianEdwards** [comment]
Seems like the sort of thing .NET should do for me though, no? And we'd still need to have a solution for Linux & OSX.

**Comment by tarekgh** [comment]
As I mentioned before returning this list will not make sense if somebody later try to create a culture not in this list and the creation succeed. this is why the enumeration in general doesn't make sense.

**Comment by DamianEdwards** [comment]
But isn't that exactly the situation of .NET Framework on Windows 10? I don't see the issue personally assuming the APIs are documented as such: One gives the list of known cultures, the other allows creation of any.

**Comment by tarekgh** [comment]
if you think forward, in the future the behavior will be as Windows 10 behavior. enumeration will be useless functionality.

**Comment by DamianEdwards** [comment]
But the existing API will still work on Windows 10, correct? Returning a list of known cultures. This serves an important purpose in server scenarios to provide a default limit on the possible number of cultures that can be created as a result of user data in incoming requests. The alternative is to force the application to explicit list the cultures it wants to support, which isn't a great experience. Allowing any culture at all is just too slow when you're dealing with server loads.

**Comment by tarekgh** [comment]
We'll keep the existing API for the app compatibility for the desktop and not exposing it in coreclr for the reasons mentioned in this thread. 
could you elaborate more on the server scenario? if we are in the world every culture is supported, why need to limit the set to this server? how we handle the client-server interop scenarios at that time? 

The server can still decide what set of cultures want to limit and can do it but we shouldn't limit that in the framework or the OS

**Comment by DamianEdwards** [comment]
The limit is required for performance reasons. The server feature automatically sets the culture of a request based on data sent with it, e.g. in the Accept-Language header, in a user preference cookie, etc. Creating `CultureInfo` is slow, which is why I'm assuming the framework previously provided APIs to access cached versions of them. In our testing, creating new `CultureInfo` on each request is multiple of orders of magnitude slower than using cached versions. However we can't have an unbounded cache based on user input (unbound memory growth). Previously (in System.Web) this was fine as the list of cultures supported was provided by the OS. With cultures now essentially infinite, it seems we can't reproduce the existing behavior by relying on the framework. We have to manually ship a list of cultures with the server pieces in order to keep it both unbounded *and* functional out of the box, without extra work on the app author's part (specifying the list of cultures to use manually).

**Comment by akoeplinger** [comment]
@DamianEdwards Sorry for shamelessly jumping in here, but can't you just use a cache for the last 100 recently used cultures? Or better, if `CultureInfo` is too slow then imho it should be fixed rather than creating band-aids at the app level.

**Comment by tarekgh** [comment]
what happen when limiting to specific list and getting a request with a valid culture not in this list? this is the scenario I am worried of. looks you need a cache anyway and can recycle the cache if it grow wildly.

**Comment by tarekgh** [comment]
@akoeplinger I think it is reasonable to think in optimizing the culture creation. today we initialize all culture properties in front. we can optimize to make it lazy initialize but this may have some performance implication when accessing such properties

**Comment by DamianEdwards** [comment]
@akoeplinger unfortunately that leaves the server open to have the cache populated with "bogus" cultures by an unfriendly user.

@tarekgh if you limit then that's the limit. Any culture requested by the client not in that list will not be honored. We can certainly look at a more complex cache (weak map, ring buffer, trimming, etc.) but we're just exploring the change right now.

**Comment by tarekgh** [comment]
@DamianEdwards well, it will look weird if user request has valid data and get rejected by the server. I think as long as you can create the culture it has to be honored as valid one. I would still recommend having internal cache for now and limit its size. in general case I am not expecting this cache will grow. I think it does only in the DOS attack scenario

**Comment by DamianEdwards** [comment]
@tarekgh "valid data" is contextual based on the app. Sending the server a valid yet unknown culture string will have little effect on the response as an unknown culture doesn't get any meaningful format data anyway.

As we're a server framework we have to worry about the DOS attack scenario. It's just part of the requirements.

Our intent was to have this work similar to how it does today in System.Web, but it seems that simply won't be possible by relying solely on framework APIs.

We'll keep exploring based on the APIs that .NET Core give us. Thanks.

**Comment by glen-84** [comment]
This doesn't make any sense to me. If the OS and/or framework does not have any data for a culture, why should constructing a CultureInfo object succeed? The success implies that the framework knows about this culture and can provide the correct number formatting, etc. information for it.

For example, let's say that the culture "xx-XXXX" is valid, but unknown to the OS/framework. It uses a number format like "1-000.25", however since this information is not available on the system, the number will not be formatted correctly for the given culture (I assume it uses some default formatting). This is just *wrong*.

The constructor should throw an exception (as it does now I think?), as there is no point in creating an object that does not provide the correct data.

Also, the framework should supply a list of supported cultures for the OS on which it is running. This is also useful if you want to provide a drop-down menu for users or administrators to select a culture to be used for localizing a website.

Please reconsider your decision.

**Comment by cdrnet** [comment]
@glen-84 CultureInfo reflects what the user configured that culture to look like and is not something you can rely upon being the same on each machine. Most users will never change this, but Microsoft also keeps changing the defaults (e.g. the default decimal point of de-CH was changed/broken in recent updates, so I have to fix it manually on every machine I use).

**Comment by nil4** [comment]
@cdrnet You may find [the `CultureInfo` constructor that accepts a `useUserOverride` parameter](https://msdn.microsoft.com/en-us/library/7h898a16%28v=vs.110%29.aspx) useful to avoid user customizations in server applications.

**Comment by cdrnet** [comment]
@nil4 ah right, thanks!

**Comment by glen-84** [comment]
@cdrnet,

That doesn't change anything. My point is, if I do:

```
var culture = new CultureInfo("xx-XXXX");
```

... then I expect that this object knows how to format numbers, currency, etc. for the specified culture. If we need to be able to construct CultureInfo objects for unsupported cultures, then a new constructor should be added with a signature like:

```
public CultureInfo(string name, bool custom); // Create a custom CultureInfo object.
```

This would not require the data to be available from the OS/framework.

BTW, couldn't you fix your issue in code? Something like this:

```
if (Thread.CurrentThread.CurrentCulture.Name == "de-CH")
{
    Thread.CurrentThread.CurrentCulture.NumberFormat.NumberDecimalSeparator = "."; // Or whatever the correct separator is.
}
```

**Comment by tarekgh** [comment]
@glen-84 @cdrnet it looks there is a confusion here that I want to clarify. the framework just do whatever the underlying OS does. basically the framework ask the OS for the culture data and if the OS give the data then we succeed the culture creation. 

In Windows 10 (and I can see some Linux based OS's) it can create a culture even if the OS not fully has the culture data. basically it try to get the data from the closed cultures (considering the language and the region of the requested culture). so this is OS decision and not framework decision. 
if the culture creation succeeded then the full culture functionality is supported. the numbers, date, time, currency...formatting will work. no special API needed to construct or use this culture.

If the framework try to give different behavior than the underlying the OS that can cause confusion and problem if there is any app depends on the interop scenario (I mean the culture is supported in the OS and not in the framework or vice versa).

**Comment by glen-84** [comment]
@tarekgh So what does Win10 return if you request culture data for a completely unknown culture, where both the region and the language are unknown, like "xx-XX"?

**Comment by tarekgh** [comment]
@glen-84 most likely it'll get the data from the invariant culture

**Comment by glen-84** [comment]
@tarekgh With no indication of failure?

Am I the only one that thinks that this is insane? You ask for XX and you get YY without any warning that the culture information is not at all what you asked for?

**Comment by tarekgh** [comment]
@glen-84 you can send your feedback to Windows team (look at the following link for more info).
http://windows.microsoft.com/en-us/windows/preview-updates-feedback-pc

We'll pass the feedback to them too.

**Comment by glen-84** [comment]
Thanks @tarekgh, I have just done so.

It would be great if you could do the same, as I'm sure that feedback from a Microsoft team would be more highly prioritized. :smile:

**Comment by tarekgh** [comment]
@glen-84 thanks for your feedback. I already did too.
