### ISSUE TITLE
Do more sgen tests

### ISSUE THREAD

**Issue by huanwu** [dotnet/corefx#16697]
Use the existing XmlSerializer tests to verify the generated c# code.

**Comment by zhenlan** [comment]
We would add tests in the test project for Sgen later.

**Comment by karelz** [comment]
@zhenlan do you want to file a new issue or just move this one to Future?

**Comment by zhenlan** [comment]
We will file new issues. This one was only meant for ad-hoc testing. Next, we will add automated tests.

**Comment by karelz** [comment]
Cool, thanks!
