### ISSUE TITLE
Stop producing S.S.C.Xml package until it's ready.

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#16708]
Apparently we need to move the `.pkgbuild` file out of the way until we're ready for it to be uploading for real.  (After test coverage is high enough).

**Comment by bartonjs** [comment]
@krwq You wanna jump on this one?

**Comment by krwq** [comment]
@bartonjs, I thought renaming pkgproj to pkgproj.disabled fixed it already, are you sure we are still producing packages?

**Comment by bartonjs** [comment]
@krwq Oh, was it already done? I just hadn't seen an issue, and no one spoke up on email.  If it's already done go ahead and close this.

**Comment by krwq** [comment]
yes: https://github.com/dotnet/corefx/pull/16538
I think we can close it then :wink:
