### ISSUE TITLE
EnvVars Dictionary as IDictionary passed to Linq morphs Enumerator

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#16713]
Dictionary Enumerator is a bit weird as it can be two types; depending on what interface it is accessed on

Environment variables can also return a `HashSet` which is why it needs `DictionaryEntry` rather than `KeyValuePair`

Previously this code would work fine [aspnet/Configuration](https://github.com/aspnet/Configuration/blob/dev/src/Microsoft.Extensions.Configuration.EnvironmentVariables/EnvironmentVariablesConfigurationProvider.cs#L49-L63)
```csharp
internal void Load(IDictionary envVariables)
{
    Data = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

    var filteredEnvVariables = envVariables
        .Cast<DictionaryEntry>() // Errors
        .SelectMany(AzureEnvToAppEnv)
        .Where(entry => ((string)entry.Key).StartsWith(_prefix, StringComparison.OrdinalIgnoreCase));

    foreach (var envVariable in filteredEnvVariables)
    {
        var key = ((string)envVariable.Key).Substring(_prefix.Length);
        Data[key] = (string)envVariable.Value;
    }
}
```
However trying to use it with latest netcoreapp errors as follows
```
Unable to cast object of type 
'System.Collections.Generic.KeyValuePair`2[System.String,System.String]' 
to type 'System.Collections.DictionaryEntry'.
```

```
Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.KeyValuePair`2[System.String,System.String]' to type 'System.Collections.DictionaryEntry'.
   at System.Linq.Enumerable.<CastIterator>d__35`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__159`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.Load(IDictionary envVariables)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder..ctor()
   at LargeResponseApp.Startup.Main(String[] args)
```
Not sure if is typeforwarding issue (e.g. don't have everything in sync); 2.0 api changes, jit change, Linq optimization, eviorment vars change etc

/cc @JonHanna @stephentoub @muratg @divega

**Comment by stephentoub** [comment]
Looks like https://github.com/dotnet/corefx/issues/14417
@JeremyKuhne, can we get this fixed soon to unblock the ASP.NET issue?

**Comment by stephentoub** [comment]
@benaadams, I think there may be a configuration issue in your set up.  Is it possible you're binding directly against the Environment type in System.Private.CoreLib, rather than against the Environment type in System.Runtime.Extensions?

**Comment by benaadams** [comment]
@stephentoub it is possible (maybe even likely); am building standalone, then copying over corefx testhost; then copying over coreclr product (else I get a whole bunch of other issues trying to use the coreclr jit)

**Comment by stephentoub** [comment]
@benaadams, I'm going to close this.  It really seems like there's something going wrong with whatever Frankenbuild set up you've got.  We have multiple tests now for this situation, and they're all passing.  Please let us know if you've gotten to the bottom of it, if this continues to be a problem for you, etc.

**Comment by benaadams** [comment]
Watching to see what nuget and csproj settings the aspnet team goes for for 2.0. Hopefully copy pasting will resolve 😁 

Having a win some, loose some experience with type forwarding atm
