### ISSUE TITLE
Invalid ArraySegments in buffer lists not properly validated on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#16715]
On Windows, the array segments in buffer lists when passed to send/receive/etc. are validated to ensure that the arrays in those segments are not null, that the bounds are valid, etc.  This validation is not being done on Unix.

**Comment by geoffkizer** [comment]
Is this worth doing?

**Comment by stephentoub** [comment]
I don't know, but I spent some of today writing more tests for sockets, and this popped, so I opened the issue, deactivated the test on unix, and we can decide.

**Comment by geoffkizer** [comment]
Sounds good.

**Comment by stephentoub** [comment]
We need to fix this for 2.0.  Misuse can result in invalid data getting manipulated in unsafe code.
