### ISSUE TITLE
discussion: Why is LinkedList<T> implemented as a circular list?

### ISSUE THREAD

**Issue by mikehaas763** [dotnet/corefx#1672]
I brought this question up in the gitter.im room and was directed here.

>I'm very curious to the design decisions if anyone has any clue. Why is System.Collections.Generic.LinkedList implemented as **circular** doubly-linked list but LinkedListNode.Next and .Previous explicitly prevent the circular access from happening?

To clarify, I'm not wondering why it's a doubly-linked list I'm wondering why it's a circular list. My suspicions are that it helps with performance and helps to keep the code cleaner by not needing to keep track of the tail separately.

**Comment by KrzysztofCwalina** [comment]
It's to avoid null checks in many methods, e.g. InternalInsertNodeBefore

**Comment by stephentoub** [comment]
@mikehaas763, does this answer your question such that the issue can be closed?

**Comment by mikehaas763** [comment]
Yes it was. Thanks for the response.
