### ISSUE TITLE
Span<T> == null throws ArgumentNullException

### ISSUE THREAD

**Issue by fujiy** [dotnet/corefx#16730]
I know it doesn't make sense to compare it to null since it is a struct. But it is allowed since we have a implicit cast operator that get called, op_Implicit(T[] array).

And that operator throws the exceptions when calling the constructor:

```c#
    public static implicit operator Span<T>(T[] array)
    {
        return new Span<T>(array);
    }

    public Span(T[] array)
    {
        if (array == null)
        {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.array);
        }
```

Repro:
```c#
    int[] src = { 1, 2, 3 };
    Span<int> srcSpan = new Span<int>(src);
    var t = srcSpan == null;
```

at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
at System.Span`1.op_Implicit(T[] array)
at ConsoleApp1.Program.Main(String[] args)

**Comment by KrzysztofCwalina** [comment]
@jaredpar, this is a bit strange. Is there anything we can do about it?

**Comment by jaredpar** [comment]
CC @gafter who can discuss the best pattern to use here.

**Comment by KrzysztofCwalina** [comment]
@gafter, any pointers?

**Comment by ahsonkhan** [comment]
ping @gafter

**Comment by gafter** [comment]
I suggest adding
``` c#
    [Obsolete("Incorrect equality test; Span<T> is a value type", true)]
    public static bool operator ==(Span<T> left, T[] right) => true;
    [Obsolete("Incorrect equality test; Span<T> is a value type", true)]
    public static bool operator !=(Span<T> left, T[] right) => false;
```

**Comment by ahsonkhan** [comment]
This PR fixes the issue (by adding a null check to the implicit cast): https://github.com/dotnet/corefx/pull/25257

> I suggest adding

Should we still add those equality overloads?

**Comment by gafter** [comment]
> Should we still add those equality overloads?

I don't think so. However, it is slightly strange that you can convert a null `T[]` to a `Span<T>` by the conversion but not by construction.
