### ISSUE TITLE
Socket.Select / Read and Socket.Handle

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/corefx#16744]
@samirparekh commented on [Thu Sep 29 2016](https://github.com/dotnet/coreclr/issues/7413)

Hi, we have an application which we intend to port to .NETCore. This application is a latency sensitive application and it requires to monitor >100 sockets for incoming (high frequency) financial market data.

I have gone throught the implementation of Socket.Select for windows and Linux (from the available source code).

It seems like for Linux the framework allocates a stack based pointer list (in case when the provided socket list length is < 80) else on the heap. Surprising enough the same approach could have benefited wider group of windows users.

Moreover in my case where i can not go for allocating an array of >100 sockets , in my previous implementation I had a pre-allocated array/list of socket pointers/handles and reused it through the process lifecycle(thus eleminating the performance penalty imposed by GC in case of constantly re-allocating IntPtr arrays).

It seems like in the current code base it is no longer possible to get an IntPtr / handle to a socket which makes the above code optimization impossible.

May I request you (in the interest of broader community) to rethink the various scenarios and advice the possible cource of action.

Thanks

---

@gkhanna79 commented on [Sat Mar 04 2017](https://github.com/dotnet/coreclr/issues/7413#issuecomment-284203728)

CC @brianrob 

---

@stephentoub commented on [Sun Mar 05 2017](https://github.com/dotnet/coreclr/issues/7413#issuecomment-284225067)

This issue should really be in CoreFx.

> It seems like for Linux the framework allocates a stack based pointer list (in case when the provided socket list length is < 80) else on the heap. Surprising enough the same approach could have benefited wider group of windows users.

Yes, that should be doable for Windows as well (cc: @geoffkizer).  You're welcome to submit a PR to CoreFx to address that.

> It seems like in the current code base it is no longer possible to get an IntPtr / handle to a socket which makes the above code optimization impossible.

Socket.Handle has been exposed.  It's not available in .NET Core 1.x, but is in .NET Core 2.0.

**Comment by danmosemsft** [comment]
@samirparekh  are you interested in making such a PR as suggested above?

**Comment by wfurt** [comment]
Since `Socket.Handle` is exposed now, should we close this? It may not be elegant but it should allow special handling if need to.  Unless you think we _should_ do this @stephentoub

**Comment by stephentoub** [comment]
The stackalloc optimization was addressed by https://github.com/dotnet/corefx/pull/30485, and Socket.Handle is exposed, so this can be closed.
