### ISSUE TITLE
Test: System.Dynamic.Runtime.Tests.Conformance.dynamic.context.indexer.genclass.DynamicCSharpRunTest() failed

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#16747]
Create a new issue for the following method:
[Fact(Skip = "870811")]
        public static void DynamicCSharpRunTest()
        {
            Assert.Equal(0, MainMethod());
        }
under: src\System.Dynamic.Runtime\tests\Dynamic.Context\Conformance.dynamic.context.indexer.genclass.cs

Detail: https://github.com/dotnet/corefx/blob/master/src/System.Dynamic.Runtime/tests/Dynamic.Context/Conformance.dynamic.context.indexer.genclass.cs#L899

**Comment by danmosemsft** [comment]
Issue tracking disabled test
