### ISSUE TITLE
Test disabled with "Fails on desktop and core: 'Unable to cast object of type 'System.UInt32[][*]' to type 'System.Object[]'"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#16753]
Test: Roundtrip_ArrayContainingArrayAtNonZeroLowerBound() under corefx\src\System.Runtime.Serialization.Formatters\tests\BinaryFormatterTests.cs

[ActiveIssue("Fails on desktop and core: 'Unable to cast object of type 'System.UInt32[][*]' to type 'System.Object[]'")]

Detail: https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Serialization.Formatters/tests/BinaryFormatterTests.cs#L750

**Comment by joperezr** [comment]
cc: @stephentoub (original author of the test)
