### ISSUE TITLE
Change [ActiveIssue("PerformanceTest")] to a new github issue

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#16754]
[ActiveIssue("PerformanceTest")]

Tests under: corefx\src\System.Runtime.Numerics\tests\BigInteger\PerformanceTests.cs

Details:
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Numerics/tests/BigInteger/PerformanceTests.cs#L24
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Numerics/tests/BigInteger/PerformanceTests.cs#L38
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Numerics/tests/BigInteger/PerformanceTests.cs#52
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Numerics/tests/BigInteger/PerformanceTests.cs#66
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Numerics/tests/BigInteger/PerformanceTests.cs#80
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Numerics/tests/BigInteger/PerformanceTests.cs#94
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Numerics/tests/BigInteger/PerformanceTests.cs#108
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Numerics/tests/BigInteger/PerformanceTests.cs#122

**Comment by danmosemsft** [comment]
We don't need these, my bad. See your PR.
