### ISSUE TITLE
Test under: System.Linq.Tests with ActiveIssue("Valid test but too intensive to enable even in OuterLoop")

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#16750]
[ActiveIssue("Valid test but too intensive to enable even in OuterLoop")]

Details:
https://github.com/dotnet/corefx/blob/master/src/System.Linq/tests/SelectManyTests.cs#L216
https://github.com/dotnet/corefx/blob/master/src/System.Linq/tests/SelectTests.cs#L143
https://github.com/dotnet/corefx/blob/master/src/System.Linq/tests/SkipWhileTests.cs#L146
https://github.com/dotnet/corefx/blob/master/src/System.Linq/tests/TakeWhileTests.cs#L121
https://github.com/dotnet/corefx/blob/master/src/System.Linq/tests/ToArrayTests.cs#L131
https://github.com/dotnet/corefx/blob/master/src/System.Linq/tests/WhereTests.cs#L1001

**Comment by danmosemsft** [comment]
Not needed, see PR comment
