### ISSUE TITLE
Tests under System.Linq.Parallel.tests with ActiveIssue("Cancellation token not shared")

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#16751]
[ActiveIssue("Cancellation token not shared")]

Details: https://github.com/dotnet/corefx/blob/master/src/System.Linq.Parallel/tests/QueryOperators/SequenceEqualTests.cs#L172
https://github.com/dotnet/corefx/blob/master/src/System.Linq.Parallel/tests/QueryOperators/SequenceEqualTests.cs#L186

**Comment by danmosemsft** [comment]
Tracking issue for disabled tests.

**Comment by stephentoub** [comment]
I believe we can just delete these tests.
