### ISSUE TITLE
Failing test: System.Net.Sockets.Tests.SocketAsyncEventArgsTest.CancelConnectAsync_StaticConnect_CancelsInProgressConnect

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#16765]
New test added on 3\4. https://github.com/dotnet/corefx/commit/3805927a19b961850c1c6429d6f8a8b6f1fbd4fa#diff-e1fb5b4a4127d23e848c28f23edf72a2

Appears to be random, as it passes on other runs.

@stephentoub it is failing here. The async connection request may complete by this line: 
>>     Assert.True(Socket.ConnectAsync(SocketType.Stream, ProtocolType.Tcp, connectSaea)); 

Failures:
Test Case: dotnet_corefx/master/debian8.4_release 1208 	deb84-20170214-f64b50 	03/06 02:44 AM
dotnet_corefx/master/debian8.4_debug 1210 	deb84-20170214-56eea0 	03/06 01:37 PM
dotnet_corefx/master/ubuntu14.04_release 1349 	ubuntu1404-20160211-1-4b2f60 	03/06 02:44 AM

Detail:
```
debian8.4_debug
System.Net.Sockets.Tests.SocketAsyncEventArgsTest.CancelConnectAsync_StaticConnect_CancelsInProgressConnect (from (empty)) 
Failing for the past 1 build (Since #1210 ) 
Took 22 ms.


Stacktrace
MESSAGE:
Assert.False() Failure\nExpected: False\nActual: True
+++++++++++++++++++
STACK TRACE:
at System.Net.Sockets.Tests.SocketAsyncEventArgsTest.CancelConnectAsync_StaticConnect_CancelsInProgressConnect() in /mnt/resource/j/workspace/dotnet_corefx/master/debian8.4_debug/src/System.Net.Sockets/tests/FunctionalTests/SocketAsyncEventArgsTest.cs:line 315
```

**Comment by stephentoub** [comment]
> The async connection request may complete by this line:

Hmm. @steveharter, any idea how this would happen?  The server hasn't issued a Listen nor an Accept, so how could this be completing?  Obviously something is going wrong, as the test is sporadically failing, but I'm currently failing to see what.

**Comment by karelz** [comment]
cc @Priya91 @ianhays

**Comment by steveharter** [comment]
Also adding related test: System.Net.Sockets.Tests.SocketAsyncEventArgsTest.CancelConnectAsync_InstanceConnect_CancelsInProgressConnect
since it also fails on Unix
```
dotnet_corefx/master/fedora23_release 1260 	fedora23-20160622-11b7d0 	03/06 07:50 PM
dotnet_corefx/master/opensuse13.2_release 1262 	suse132-20160315-285070 	03/07 12:16 AM
```

Perhaps this is an issue with other tests that use IPAddress.Any (0.0.0.0)?

**Comment by stephentoub** [comment]
> System.Net.Sockets.Tests.SocketAsyncEventArgsTest.CancelConnectAsync_InstanceConnect_CancelsInProgressConnect

Yeah, I disabled that this morning against this issue as well, as I assume it's the same underlying problem.

**Comment by steveharter** [comment]
@stephentoub can you take another look at this please?

I suggest adding some diagnostics such as checking if socket.Connected == true after the ConnectAsync().

If that diagnostics shows the socket is not connected then another error value occurred within ConnectAsync as pending=true will be true only if that exact error is returned:
            bool pending = (socketError == SocketError.IOPending);

**Comment by stephentoub** [comment]
> Perhaps this is an issue with other tests that are listening to IPAddress.Any (0.0.0.0)?

@steveharter, if that's the case, do you have any ideas / plans for how to systematically address such tests across the codebase?

**Comment by steveharter** [comment]
>>  Perhaps this is an issue with other tests that are listening to IPAddress.Any (0.0.0.0)?

> @steveharter, if that's the case, do you have any ideas / plans for how to systematically address such tests across the codebase?

Just a hunch assuming there's interference from other tests, specifically the "dual mode" tests such as AcceptV4BoundToAnyV4_Success(). Sooner or later I assume some tests will fail if they assume .Any will only look at localhost (127.0.0.0) as it could grab that port off of some other network interface. I think those tests should be removed \ replace with IPAddress.Loopback or .IpV6Loopback as appropriate. I haven't created an issue for that yet as I haven't yet tried to repro that case.

**Comment by stephentoub** [comment]
Closing for now with https://github.com/dotnet/corefx/pull/17584.  We can reopen if/when it repros again.

**Comment by karelz** [comment]
Marking as test issue
