### ISSUE TITLE
System.Environment rejects env variable values acceptable to the OS

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16766]
In https://github.com/dotnet/coreclr/issues/9793 an environment variable already set in the OS caused an ArgumentException when MSBuild tried to set it because the length of the value was over 32KB. (CI apparently passes the change description in an environment variable)

We should accept any environment variable that's acceptable to the OS. Apparently on Windows Server 2012 (this run) over 32KB is acceptable. Rather than check the length we should perhaps let Windows return an error.

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Environment.cs#L45
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Environment.cs#L843

**Comment by stephentoub** [comment]
Seems like a good thing to change.  We have other similar cases we've discussed, where previously .NET was trying to enforce limits that should simply have been left to the OS to validate, e.g. https://github.com/dotnet/corefx/issues/3740

**Comment by danmosemsft** [comment]
Particularly since apparently we're enforcing it on Unix also, where there's [apparently no particular limit](http://stackoverflow.com/questions/1078031/what-is-the-maximum-size-of-an-environment-variable-value)

**Comment by stephentoub** [comment]
> where there's apparently no particular limit

On Unix we don't actually call setenv; we just keep a cache in memory.  So there's even less of a limit ;)

**Comment by karelz** [comment]
This should be fairly simple. Check the new error code/exception - we might need to make it compatible with today's exception (find out what the new one is on Windows/Linux/Mac and discuss the plan here)

**Comment by karelz** [comment]
@JeremyKuhne I unassigned you, as I don't think you are working on it ... please change it if it was incorrect.

**Comment by JeremyKuhne** [comment]
I'm about to go through these- had to fix the registry issues first.

**Comment by yvanin** [comment]
> Check the new error code/exception - we might need to make it compatible with today's exception (find out what the new one is on Windows/Linux/Mac and discuss the plan here)

ERROR_NO_SYSTEM_RESOURCES (0x5AA) is thrown on Windows 8.1 when using a string of size 2,147,483,520 bytes

**Comment by karelz** [comment]
I think there is limitation of 4GB large object in GC heap. That would translate to 2G UTF16 string.

**Comment by yvanin** [comment]
Exactly 2GB and larger throws OutOfMemory exception in the string constructor in .NET.
Slightly less works in .NET but trips up SetEnvironmentVariable in kernel32.dll.

And it looks like other OSes would throw [ERROR_NOT_ENOUGH_MEMORY](https://github.com/dotnet/coreclr/blob/3bf3915549eaa3c475f9dd899d9a6265dcde9908/src/pal/src/misc/environ.cpp#L662-L669).

Should ERROR_NO_SYSTEM_RESOURCES and ERROR_NOT_ENOUGH_MEMORY be translated into ArgumentException to keep compatibility?

**Comment by danmosemsft** [comment]
@yvanin If we're changing the limit from 32KB to 2GB it seems reasonable to me to change from ArgumentException to OutOfMemoryException. Whatever it is ideally it would be the same on all platforms. What does Mono do?

Do you have any interest in  a PR?

**Comment by yvanin** [comment]
Mono doesn't check for the length but throws unrelated NullReferenceException when using a 2GB string in Environment.SetEnvironmentVariable.

**Comment by yvanin** [comment]
I can take this issue.
To confirm, the approach would be to remove the length check and throw System.OutOfMemoryException when last Win32 error is ERROR_NO_SYSTEM_RESOURCES or ERROR_NOT_ENOUGH_MEMORY.
Does that look right?

**Comment by danmosemsft** [comment]
@yvanin missed this. If you're still interested -- yes I think so.
