### ISSUE TITLE
Fix test projects that are failing ILC step when trying to run uapaot tests.

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#16764]
We were able to succesfully send the right payloads to Helix which helped us trying to ilc all of the tests projects, in order to be able to tell which ones are failing that step. The full list of the test projects that are failing are:
 - [ ] System.Collections.Tests
 - [x] System.Data.SqlClient.Tests
 - [x] System.IO.FileSystem.Tests
 - [x] System.IO.MemoryMappedFiles.Tests
 - [x] System.Net.Http.Functional.Tests
 - [x] System.Net.Mail.Functional.Tests
 - [x] System.Net.Requests.Tests
 - [x] System.Net.Security.Tests
 - [x] System.Net.WebClient.Tests
 - [x] System.Private.Uri.Unit.Tests
 - [x] System.Runtime.Extensions.Tests
 - [x] System.Runtime.Serialization.Formatters.Tests
 - [x] System.Runtime.Serialization.Json.Performance.Tests
 - [x] System.Runtime.Serialization.Json.ReflectionOnly.Tests
 - [x] System.Runtime.Serialization.Json.Tests
 - [x] System.Runtime.Serialization.Xml.Performance.Tests
 - [x] System.Runtime.Serialization.Xml.ReflectionOnly.Tests
 - [x] System.Runtime.Serialization.Xml.Tests
 - [x] System.Runtime.Tests
 - [x] System.Security.AccessControl.Tests
 - [x] System.Threading.ThreadPool.Tests
 - [x] System.Xml.Linq.Properties.Tests
 - [ ] System.Xml.XmlSerializer.ReflectionOnly.Tests
 - [ ] System.Xml.XmlSerializer.Tests

cc: @weshaggard @MattGal

**Comment by MattGal** [comment]
Great work @joperezr!  I'm actually surprised by how short this list is, although of course things will get worse at runtime.

**Comment by safern** [comment]
@joperezr this could be closed now right?

**Comment by joperezr** [comment]
right, this is done.
