### ISSUE TITLE
Regression in SortedSet::Max

### ISSUE THREAD

**Issue by marek-safar** [dotnet/corefx#16760]
introduced in https://github.com/dotnet/corefx/pull/11968

```c#
using System;
using System.Collections.Generic;

class X
{
	public static void Main ()
	{

		var set = new SortedSet<int> { 1, 3, 5, 7, 9 };
		var view = set.GetViewBetween (4, 8);

		Console.WriteLine (view.Max); // Prints 9 instead of 7
	}
}
```

**Comment by stephentoub** [comment]
cc: @mjp41, @ianhays

**Comment by stephentoub** [comment]
> What is the time line for needing the fix?

Relatively soon :)

> There look like there are three possible fixes

Let's do whichever strikes a decent balance between not being too much worse on perf and minimizing the chance of further regression.  Sounds like that's 2?
