### ISSUE TITLE
S.R.InteropServices.RuntimeInformation.FrameworkDescription throws in UWP release

### ISSUE THREAD

**Issue by zabulus** [dotnet/corefx#16769]
Exception message: RFLCT_Ambiguous.
I think cause is here:
https://github.com/dotnet/corefx/blob/9e693eed46efd17f39090de336ee82d318edbbec/src/System.Runtime.InteropServices.RuntimeInformation/src/System/Runtime/InteropServices/RuntimeInformation/RuntimeInformation.cs#L28
```GetCustomAttribute(typeof(AssemblyFileVersionAttribute))``` could return several attributes.

Workaround: 
If I use following or similar code, exception not occurs:
```
typeof(object).GetTypeInfo().Assembly.GetCustomAttributes(typeof(AssemblyFileVersionAttribute)).OfType<AssemblyFileVersionAttribute>().FirstOrDefault(); 
```

**Comment by MichalStrehovsky** [comment]
Sounds related to custom attribute duplication seen with .NET Native in azure/autorest#1542

**Comment by MichalStrehovsky** [comment]
This is a .NET Native bug that can be worked around by disabling the shared library feature. To work around:

1. Edit the .csproj for your app and add the following property: `<UseDotNetNativeSharedAssemblyFrameworkPackage>false</UseDotNetNativeSharedAssemblyFrameworkPackage>`. This disables the [shared framework](https://blogs.msdn.microsoft.com/dotnet/2015/09/28/whats-new-for-net-and-uwp-in-win10-tools-1-1/) feature: as a consequence, the compilation in Release mode will take longer and your app will be bigger.
2. Rebuild your app

**Comment by tijoytom** [comment]
This is fixed "VSO 392708"
