### ISSUE TITLE
ToTitleCase does not correctly titlecase Dutch words starting with IJ

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#16770]
@warrantyvoids commented on [Mon Mar 06 2017](https://github.com/dotnet/coreclr/issues/9981)

The current TextInfo.ToTitleCase() Locale specific function does not correctly titlecase Dutch words starting with IJ as specified by the Unicode Standard, introductory text of paragraph 3.13. 
• Titlecasing of IJ at the start of words in Dutch

An example of this would be ToTitleCase("ijzeren eigenschappen") -> "IJzeren Eigenschappen", although it currently leads to "Ijzeren Eigenschappen".

**Comment by reaction1989** [comment]
@tarekgh why was this moved to corefx? The implementation is in coreclr, or am i wrong?

**Comment by rionmonster** [comment]
I'll be glad to try and work on this one. I've been eager to jump into an up-for-grabs issue and this one certainly seems manageable.

**Comment by tarekgh** [comment]
> why was this moved to corefx? The implementation is in coreclr, or am i wrong?

The contracts of the APIs are in corefx. for issues like this one we would like to track it here to tie it to specific release. but in general we can still track this on the coreclr repo as it is not urgent to get it fix in the next release.

**Comment by tarekgh** [comment]
@rionmonster feel free to submit a PR and we'll comment on the PR. thanks for willing to help with this issue. I see you have sent email and I'll try to reply you soon.
