### ISSUE TITLE
System.Security.Cryptography.Xml KeyInfoTest.ImportKeyNode is failing

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#16779]
This test is passing on full .NET but is failing on CoreFX - we need to verify what has happened. Also verify that test was properly ported from Mono as it could be some simple typo

```csharp
   System.Security.Cryptography.Xml.Tests.KeyInfoTest.ImportKeyNode [FAIL]
      System.Security.Cryptography.CryptographicException : An error occurred parsing the key components
      ---- Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : The parameter is incorrect
      Stack Trace:
            at System.Security.Cryptography.Xml.DSAKeyValue.LoadXml(XmlElement value)
            at System.Security.Cryptography.Xml.KeyInfo.LoadXml(XmlElement value)
            at System.Security.Cryptography.Xml.Tests.KeyInfoTest.ImportKeyNode()
         ----- Inner Stack Trace -----
            at System.Security.Cryptography.CngKeyLite.ImportKeyBlob(String blobType, Byte[] keyBlob)
            at System.Security.Cryptography.DSAImplementation.DSACng.ImportKeyBlob(Byte[] rsaBlob, Boolean includePrivate)
            at System.Security.Cryptography.DSAImplementation.DSACng.ImportParameters(DSAParameters parameters)
            at System.Security.Cryptography.Xml.DSAKeyValue.LoadXml(XmlElement value)
```

likely also related failure:
```csharp
     System.Security.Cryptography.Xml.Tests.DSAKeyValueTest.LoadXml [FAIL]
        Assert.NotNull() Failure
        Stack Trace:
           /home/krwq/work/corefx/src/System.Security.Cryptography.Xml/tests/DSAKeyValueTest.cs(113,0): at System.Security.Cryptography.Xml.Tests.DSAKeyValueTest.LoadXml()
```

cc: @tintoy @anthonylangsworth @peterwurzinger

**Comment by peterwurzinger** [comment]
@krwq This seems like it is related to  my implementation of DSAKeyValue.LoadXml if I'm not completely mistaken.

**Comment by krwq** [comment]
@peterwurzinger - any pointers which could help investigate the failure? Do you perhaps know if this is a test issue or a product bug?

**Comment by krwq** [comment]
@peterwurzinger I've added another test failure which is likely related - PTAL if that is correct

**Comment by peterwurzinger** [comment]
Well I think I can have a look todays morning (9:12AM for me atm) and will try to investigate this. What looks kind of weird is, that it's passing on corefx but failing on full framework builds.

**Comment by krwq** [comment]
@peterwurzinger - thank you a lot for picking this up! For sanity check I recommend to rerun it on full fx in case I accidentally did something wrong. I was running many tests on Desktop so errors are completely possible.

**Comment by peterwurzinger** [comment]
@krwq can you please show me the concrete command to run tests against Desktop configuration?

**Comment by peterwurzinger** [comment]
@krwq Just a small update:
I found a way to fix this issue. If I remove the "PGenCounter", "Seed" and "J" - elements from the KeyValue-XML, it's actually working. I'll check which element(s) are the real cause for this and why their presence causes such a mess. But for now I'm gonna go to sleep.

cc @tintoy @anthonylangsworth

**Comment by peterwurzinger** [comment]
I got a new update @krwq 
The exception arises from the depths of `DSA.Cng`. To make it short: A lot of unsafe code, `SafeHandles`, passing byte-arrays as parameters,... I can't go any deeper than that. What gets returned from CNG-Hell is an "Wrong parameter" - error.

I tried to feed this with various parameter combinations, and this is what I found out:
1a) The original test was failing - obviously
1b) I removed the `<Seed/>` and `<PgenCounter/>` elements from the given DSA-XML. It actually **works** fine, no exception on this one.
2a) I created a key with DSA.Create and copied the BASE64-values from there into a manually built Key-XML. Those included the `<Seed/>` `<PgenCounter/>` elements, the test was **failing** again.
2b) I removed the `<Seed/>` and `<PgenCounter/>` elements from the newly created DSA-XML. Again no exception on this one, it **works**.
3) I copied the DSA-Key from `DSAKeyValueTest.LoadXml`, which also _does include_ the `<Seed/>` and `<PgenCounter/>` elements. **To my fascination this test run also succeeded**

So we got 5 different scenarios, which do **not** come up with a common scheme. How to proceed? I cannot debug any deeper. 

CC @tintoy @anthonylangsworth

**Comment by krwq** [comment]
@peterwurzinger for running tests against full .NET: (thanks to @joperezr)
From root call:
Build.cmd -framework:netfx
Build-tests.cmd -framework:netfx

For individual project test build:
Build.cmd -framework:netfx (it is required to build the whole layout first)
Msbuild <yourtestproject>.csproj /p:TargetGroup=netfx /t:rebuildandtest

I've personally had some difficulties with the above instructions as it just didn't work for me at least on Windows. The other option which has worked for me despite any potential issues with the build is to simply copy paste the piece testing something to a new app targeting netfx and run. I'll let you know if there are some updates to the instructions.

For the error, It seems to me that error is fairly hard to debug in the current state. Our usual procedure is that we need to split it into managable and easier to understand pieces: Specifically, we need to verify if the error is on the crypto-xml side or on the DSA side (possibly few more tests which would help to find out), if the error is on the DSA side we need to file an issue with smallest possible repro and if crypto-xml's then we need to figure out what should we pass to DSA for this scenario to work (if you believe there are few scenarios broken then we possibly need a test per broken scenario).

Please let me know if you need further help as I got easier way to get to some of the internals so it might be easier for me to get into that (i.e. by talking to people more familiar with some pieces of code). I will likely not get into it right away though.

**Comment by tintoy** [comment]
It's odd, because the phrase "the parameter is incorrect" screams `E_INVALIDARG` at me. And I wouldn't have expected to find that in corefx since it's terminology you normally only see it coming out of unmanaged implementations (i.e. ones that use `HRESULT`s).

Still, I suppose someone could have tried to port as much of the old crypto code as possible, even if some of those implementations are unmanaged. Or maybe someone's explicitly setting `E_INVALIDARD` on `Exception.HResult`?

I'm a bit flat-out today, but if I get time tonight I'll try to have another look at this (even if only for my own curiosity).

**Comment by krwq** [comment]
@tintoy @peterwurzinger it is possible that we might be using wrong implementation assembly - I've seen that before (on Linux we used Windows assembly which was causing really weird errors)

**Comment by krwq** [comment]
This one is quite a mess - currently no clue why this is failing 😉

**Comment by krwq** [comment]
I've split this test a little bit so that we are able to tell what has happened and what is exactly missing. Currently seems to me that J is missing in DSAKeyValue after we import and export. I'm not ever seeing J in DSAKeyValue when I create that on Desktop - I'll further investigate if this is something we should be parsing or not.

**Comment by krwq** [comment]
Ok, J is optional and is only an optimization. I'll make a test accept either null or correct value
