### ISSUE TITLE
Cleanup null handling in System.Text.Encodings.Web

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefx#1678]
The APIs are inconsistent in the way they handle nulls. Some accept nulls, which results in nop. Some throw ArgumentNull and some simply null ref.

**Comment by krwq** [comment]
> The APIs are inconsistent in the way they handle nulls. Some accept nulls, which results in nop. Some throw ArgumentNull and some simply null ref.

**Comment by KrzysztofCwalina** [comment]
#1679 fixed the issue
