### ISSUE TITLE
HttpClient on Linux improvements and enhancements

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/corefx#16783]
@lgreenlee commented on [Mon Mar 06 2017](https://github.com/dotnet/coreclr/issues/9984)

After utilizing the HttpClient for several micro-services I believe some improvements can be made to the HttpClient under Linux.

### Improvement 1 - Remove the CURL dependency/Or HttpClientSlim?
I believe there is a thread discussing this already but the the dependency on CURL is problematic. It causes and will continue to cause a few basic issues such as this one. 
https://github.com/dotnet/coreclr/issues/9953

Over time the Curl dependency will become more pronounced as interfaces change. Eventually, there will be some sort of breaking change that will cause your users (like me) subtle and/or obvious problems such as software ceasing to work, or unwanted (but needed) system updates to non .NET software. The "fix" for this particular issue may be a static dependency. There are other reasons though...

A byproduct of the CURL dependency is that the behavior of the HttpClient is handicapped. We cannot retrieve an underlying network stream from the HttpClient and do with it as we wish. Access to the stream is hidden within curl. Rich signaling of error conditions and network state are not possible as a result.

Finally, there is also some overhead associated with pinvoke and the interop. We cannot say the current implementation is the most efficient way to make these requests.

I would propose a higher performance, "lighter weight" client with better underlying network access and memory usage our current implementation.

### Improvement 2 - Synchronous methods
In some scenarios I would like to be sure that I know what my code is doing. There are times, such as trying to design a process that is well understood and verifiable, where placing that code in a thread and running it to completion (or forever) is a desirable attribute. Fundamentally, the use of the await keyword introduces code that the developer does not write. After having spent the last 8 months developing on Linux with just the VS Code debugger - debugging complex threading issues is very difficult and time consuming. Finally the inclusion of the HttpClient forces me to change the overall structure of my service if it is primarily Synchronous in nature.

### Improvement 3 - Better indication of proper usage
Creation of the HttpClient through "new" to make an individual requests is not recommended, but it is easy to do and seemingly correct since there are no API features to prevent us from making the mistake. TIME_WAIT socket growth is also not an expected behavior if I call "Dispose" on the HttpClient. Perhaps implementing a HttpClientPool with the ability to retrieve named instances of an http client and hiding the constructor for the HttpClient?

The importance of the HttpClient to the .NET Core framework cannot be understated. It one of a handful of mechanisms to communicate outside the CLR, is the only Http based mechanism we have to complete REST operations. It must work well now and into the future for developers and organizations to continue to adopt .NET Core as a development and deployment platform.

---

@stephentoub commented on [Mon Mar 06 2017](https://github.com/dotnet/coreclr/issues/9984#issuecomment-284501248)

Thanks, but as a meta-point with regards to the title of this issue, I'm not sure how this is Linux-specific.  (2) and (3) are about the shape of HttpClient, and (1) is simply about having a managed implementation rather than relying on a native implementation, e.g. libcurl on Linux or WinHttp on Windows.

---

@stephentoub commented on [Mon Mar 06 2017](https://github.com/dotnet/coreclr/issues/9984#issuecomment-284503019)

(1) We are considering a managed HttpClientHandler implementation.  The core of that isn't challenging.  The challenging part is feature parity, e.g. support for Negotiate/Kerberos/NTLM, support for HTTP/2, etc.  Nothing insurmountable, just a lot of work before it could be substituted in silently.  In the meantime, we are considering putting out a prototype of a managed implementation on corefxlab, that folks could play with, contribute to, and even use if they desired.

(2) If this is about ease of us, you can't just block on the resulting Tasks, e.g. .Wait(), .Result, or .GetAwaiter().GetResult()?  That would impact scalability, but you wouldn't want to use synchronous methods if scalability were an issue anyway.  There was also already an issue about this:
https://github.com/dotnet/corefx/issues/13813
If you want to continue this discussion, probably best to do it there.

(3) Feel free to propose an API.  I suggest splitting this issue up, though, as it's difficult to have a reasonable discussion about multiple, largely-unrelated issues in the same thread.

I suggest closing this issue, using existing issues or opening new issues in the corefx repo for each constituent piece.

**Comment by karelz** [comment]
Closing per @stephentoub's suggestion above - @lgreenlee please create separate issues per @stephentoub's advise above. Thanks!

**Comment by lgreenlee** [comment]
Thanks - sorry dropped this all in one issue. I'll break it out and update the issue.
