### ISSUE TITLE
Microsoft.Extensions.Logging.EventLog not compitable with .NetCoreApp v1.0

### ISSUE THREAD

**Issue by zjleaman** [dotnet/corefx#16785]
```
Package Microsoft.Extensions.Logging.EventLog 1.1.1 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Extensions.Logging.EventLog 1.1.1 supports: net451 (.NETFramework,Version=v4.5.1)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
```

Is there an alternative to writing to the Windows EventLog for a .NetCore app?
The EventLog nuget package doesn't install and I want to use it's LoggerProvider.

**Comment by karelz** [comment]
This issue was moved to aspnet/Home#1952

**Comment by natemcmaster** [comment]
@karelz are there plans to support System.Diagnostics.EventLog on .NET Core? This package is a wrapper around this API.

**Comment by karelz** [comment]
It was punted from .NET Core 2.0 - see #6913.
If there is enough people interested, we can bring it back as extension (similar to Registry). Especially if community is interested in helping with the port and testing (like SerialPort, SignedXml).

**Comment by natemcmaster** [comment]
> we can bring it back as extension.

👍 

To make Microsoft.Extensions.Logging.EventLog work on .NET Core, we would need this. For now, until then Microsoft.Extensions.Logging.EventLog, has to target .NET Framework in order to access System.Diagnostics.EventLog.
