### ISSUE TITLE
[NetFX compat]: SortedSet<T>..ctor(IEnumerable<T>, IComparer<T>) netfx bug

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#16790]
There is a bug in netfx where `SortedSet<T>..ctor(IEnumerable<T>, IComparer<T>)` throws NullReferenceException when comparer argument is null. 

@AlexGhiondea @tarekgh

**Comment by stephentoub** [comment]
Is this a bug in CoreFx as well?

**Comment by safern** [comment]
No, just in netfx, this was already fixed in CoreFx some time ago.

**Comment by karelz** [comment]
Here's the code: https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/SortedSet.cs#L90-L93

Closing as fixed - @AlexGhiondea's tool will pick up netfx-port-consider also for closed issues.
Thanks @safern!

**Comment by safern** [comment]
Sounds good. The code is actually: https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/SortedSet.cs#L115

It is when the comparer is null and it is in netfx where hasn't being fixed. So just to keep track of that and the test I'm marking it as skip on desktop. 
Thanks

**Comment by karelz** [comment]
Thanks @safern, I removed my confusing link to the code.
