### ISSUE TITLE
Add Interlocked.MemoryBarrierProcessWide method

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#16799]
Proposal:

```c#
static public class System.Threading.Interlocked
{
      public static void ProcessWideMemoryBarrier();
}
```

Asymmetric lock free algorithms and data structures, where frequent operations are really cheap (not even interlocked operation) and rare operations are very expensive, are often used to achieve high scalability and performance. It is not possible to implement them in portable .NET code today because there is no process wide memory barrier API that is a key primitive used to implement them.

The proposal is to add system process wide memory barrier API. The implementation is a simple wrapper around [`FlushProcessWriteBuffers`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683148(v=vs.85).aspx) API on Windows; and equivalent on other operating systems (e.g. `sys_membarrier` on recent Linux kernels).

**Comment by omariom** [comment]
What is this thing in terms of barriers?

**Comment by jkotas** [comment]
This is system wide barrier. Check what FlushProcessWriteBuffers API does on Windows; or sys_membarrier on Linux. This one is just a thin portable .NET wrapper for these.

**Comment by omariom** [comment]
The local effect is the same as  Interlocked.MemoryBarrier has?

**Comment by jkotas** [comment]
Yes. You would not call this API because of the local effect. You would call it because of the global effect.

**Comment by jkotas** [comment]
Here is a sample implementation of asymmetric using this API: https://gist.github.com/jkotas/aff2ca3774414807be7312fa00d3d521

**Comment by stephentoub** [comment]
For very advanced scenarios / building low-level primitives, this seems like a reasonable thing to add.  We already have support in Windows, and Linux recently added first-class support due to recognizing the need for something like this.

**Comment by stephentoub** [comment]
I wonder about a different name, though.  It's closely tied to the Windows naming, currently, and another name may be more understandable.  Interlocked.ProcessWideMemoryBarrier()?

**Comment by jkotas** [comment]
>  and another name may be more understandable. `Interlocked.ProcessWideMemoryBarrier()` ?

Agree - updated the name.

**Comment by terrajobst** [comment]
Makes sense. Only suggestion would be to make it a suffix, rather than a prefix so both APIs show up side-by-side in IntelliSense and docs, so:

```c#
static public class System.Threading.Interlocked
{
      public static void MemoryBarrierProcessWide();
}
```

**Comment by danmosemsft** [comment]
@jkotas did you plan to do this one? if not do you believe we should keep this in 2.0?

**Comment by crowo** [comment]
> The cost of this API is that it is a very expensive call. It has to force every CPU in the process do to something, that is likely to be 1000s of cycles. (a normal interlocked operations is probably < 100)

isnt it better to do a dummy interlocked operation instead of this? i think i need to investiagate what it does more closely.

**Comment by jkotas** [comment]
It depends on the ratio of reads and writes of your datastructure. E.g. if you are doing million reads for every write, using this API is a win - million dummy interlocked operations is more expensive than a single call to this API.
