### ISSUE TITLE
Microsoft.Framework.WebEncoders.UnicodeHelpersTests.GetDefinedCharacterBitmap_ReturnsSingletonInstance failure in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1681]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/1217/
```
MESSAGE:
Assert.Same() Failure Expected: UInt32[] [0, 4294967295, 4294967295, 2147483647, 0, ...] Actual: UInt32[] [0, 4294967295, 4294967295, 2147483647, 0, ...]
+++++++++++++++++++
STACK TRACE:
at Microsoft.Framework.WebEncoders.UnicodeHelpersTests.GetDefinedCharacterBitmap_ReturnsSingletonInstance() in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Text.Encodings.Web\tests\UnicodeHelpersTests.cs:line 31
```

**Comment by stephentoub** [comment]
This test is bogus given the way GetDefinedCharacterBitmap is implemented.  Either GetDefinedCharacterBitmap needs to be changed to guarantee that the same instance will always be returned, even when multiple threads are racing to initialize the cached field, or the test needs to be removed.

**Comment by KrzysztofCwalina** [comment]
Yeah, I know. I will try to fix (disable) this test today.

**Comment by stephentoub** [comment]
:smile:

**Comment by KrzysztofCwalina** [comment]
@stephentoub. ok, I submitted a PR: https://github.com/dotnet/corefx/pull/1695. I would appreciate a CR. Thanks!

**Comment by KrzysztofCwalina** [comment]
#1695 fixed the issue.
