### ISSUE TITLE
Proposal: add "IEqualityComparer Comparer" property to the IReadOnlyDictionary<K,V> and to ISet<T>

### ISSUE THREAD

**Issue by dmitriyse** [dotnet/corefx#16818]
When we have only contract of the collection we cannot understand by what criteria keys or items are compared.
```CSharp
public void Test(ISet<MyObject> mySet)
{
      // I want to clone this set to get my personal copy.
      var myCopy = new HashSet(mySet, /*How to get comparer ?*/);
}

public interface ISet<T>
{
     // This new property can be introduced.
     IEqualityComparer<T> Compare { get;}
}
```

Improvements of BCL interfaces without loosing backward compatibility will be possible with help of 
https://github.com/dotnet/csharplang/issues/52

Also this proposal is mentioned here https://github.com/dotnet/corefx/issues/1973#issuecomment-283912409

**Comment by karelz** [comment]
@dmitriyse let's please stop filing default interface implementation API proposals in CoreFX, until the feature exists (or nearly exists).
I am also looking forward to it, but we need to understand all its implications on CoreFX - don't forget that CoreFX is also used for Xamarin (active port in progress), UWP and Desktop. Also some code ships downlevel from CoreFX - we have to avoid to use it there.
Overall we will have to come up with a holistic plan here, before we can start looking at these proposals one by one.

If it helps you, feel free to file a one uber-issue and list there APIs you want to keep track of. I woul dbe ok with that.

Closing for now.

**Comment by karelz** [comment]
cc @ianhays @safern

**Comment by dmitriyse** [comment]
Ok, sorry. I understand you.

**Comment by karelz** [comment]
> Ok, sorry. I understand you.

Thanks for understanding! Please do not view it as discouragement from contributions - we appreciate community contributions, incl. API proposals. The only problem is timing of your proposals - you are a bit ahead of the game and Roslyn :)

If you are interested in immediate actionable contributions, I would recommend to look at:
* [up for grabs](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22up%20for%20grabs%22%20no%3Aassignee%20-label%3Aapi-needs-work) issues which don't require API design
    * The **most impactful/valuable** ones for [next 2.0 release](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22up%20for%20grabs%22%20no%3Aassignee%20-label%3Aapi-needs-work%20milestone%3A2.0.0)
* [wishlist](https://github.com/dotnet/corefx/labels/wishlist) bugs/features - things we would really like
