### ISSUE TITLE
Failure in System.Diagnostics.Tests.ActivityTests.DiagnosticSourceStartStop

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16856]
@joperezr can you find the right owner for DiagnosticSource? This gave us a red badge this morning. This test may need some logging adding, and leave enabled.

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_release/lastCompletedBuild/consoleText

```
  xUnit.net console test runner (64-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.
  
  Discovering: System.Diagnostics.DiagnosticSource.Tests
  Discovered:  System.Diagnostics.DiagnosticSource.Tests
  Starting:    System.Diagnostics.DiagnosticSource.Tests
     System.Diagnostics.Tests.ActivityTests.DiagnosticSourceStartStop [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
           D:\j\workspace\outerloop_win---75d58f69\src\System.Diagnostics.DiagnosticSource\tests\ActivityTests.cs(378,0): at System.Diagnostics.Tests.ActivityTests.DiagnosticSourceStartStop()
  Finished:    System.Diagnostics.DiagnosticSource.Tests
  ```

**Comment by joperezr** [comment]
Looks like this particular test was added by @lmolkova on #15103 and the reviewer was @vancem. 
Other owners of DiagnosticSource seems to be @brianrob and @valenis according to the [issue guide](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md)

**Comment by danmosemsft** [comment]
You're quite right, I missed it in issue guide.

**Comment by lmolkova** [comment]
It's a new check added in the test in #16821. I'll fix it

**Comment by stephentoub** [comment]
Fixed by #16861

**Comment by danmosemsft** [comment]
@lmolkova I think it is now failing further along


```
     System.Diagnostics.Tests.ActivityTests.DiagnosticSourceStartStop [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
           D:\j\workspace\outerloop_win---75d58f69\src\System.Diagnostics.DiagnosticSource\tests\ActivityTests.cs(382,0): at System.Diagnostics.Tests.ActivityTests.DiagnosticSourceStartStop()
  Finished:    System.Diagnostics.DiagnosticSource.Tests
  ```

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_release/120/consoleText

This is based on 8c777d8 which is subsequent to your fix adc6627. It's also now on line 382 in the test.

**Comment by danmosemsft** [comment]
When you put up a new PR, please invoke Windows 7 tests explicitly as they're not on by default in CI. Eg:

@dotnet-bot test outerloop Windows 7 Debug	
@dotnet-bot test outerloop Windows 7 Release

**Comment by danmosemsft** [comment]
@mmitche what would be the impact of enabling Windows 7 release by default in CI? Would it be costly in VMs? I presume it wouldn't slow down the end to end?

**Comment by mmitche** [comment]
@danmosemsft It might.  the Win7 VMs are actually just Win2008 server VMs.  However their startup time is much longer, maybe 2-3x 2012R2, so wait times could be much longer in certain cases.

I would wait.  As part of the new test matrix I think they may get enabled by default in another method.

**Comment by vancem** [comment]
> On running Win7 by default 

If this is the first time this bit us, we should think carefully about just adding another kind of run.   The cure could easily be worse then the disease.   If this only happens pretty rarely (e.g. months between instances), and we have a process for detecting it before shipping, that could be fine.    I only ask that you be thoughtful about it.

**Comment by danmosemsft** [comment]
I'm happy to wait. I would only propose it at this point if it was free, which apparently it's not. (The inner loop test runs are pretty stable now, so adding another run should not be a problem from that POV)

**Comment by vancem** [comment]
Change #16908 should fix this.

**Comment by Jiayili1** [comment]
This issue failed again here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_debug/126/testReport/System.Diagnostics.Tests/ActivityTests/DiagnosticSourceStartStop/

Since it is closed 8 hours ago, we will check this issue no next build, if it is still repro, will reopen it.

**Comment by lmolkova** [comment]
Fixed in #16951, tested on outerloop Windows 7 Debug and Release

**Comment by Jiayili1** [comment]
This issue is repro on build 20170310.01, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170310.01/workItem/System.Diagnostics.DiagnosticSource.Tests/analysis/xunit/System.Diagnostics.Tests.ActivityTests~2FDiagnosticSourceStartStop

**Comment by danmosemsft** [comment]
@lmokova Build 20170310.01 was synced to 870fbaad. (Contact me if you want to know how to figure this out. It doesn't seem to be publicly accessible data right now.)

It seems that does contain the fix from yesterday:
git rev-list 870fbaad | find /i "8a69cc3"
8a69cc3c5f4d3d640246f23e1ea0bac39d8b530e

**Comment by danmosemsft** [comment]
@Jiayili1 is this still failing in the last few days? If not let's close as perhaps I was mistaken and this did have the fix.

**Comment by danmosemsft** [comment]
@sokket has this failed in the last 2 weeks?

**Comment by Jiayili1** [comment]
@danmosemsft I will close this issue first since it doesn't fail last few days, if it is repo, I will reopen it.

**Comment by Jiayili1** [comment]
This issue is repro on build 20170425.01, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170425.01/workItem/System.Diagnostics.DiagnosticSource.Tests/analysis/xunit/System.Diagnostics.Tests.ActivityTests~2FDiagnosticSourceStartStop

**Comment by Jiayili1** [comment]
This issue is repro on full framework tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170425.01/workItem/System.Diagnostics.DiagnosticSource.Tests

**Comment by vancem** [comment]
@Jiayili1 - the links above do not seem to point at details of the issue.   I clicked around but could not find something that told me what went wrong (the closest thing I found was a page showing 0 tests run).  

There is a very good chance this is a related to the change to use Stopwatch (PR #18651 and will be fixed by PR #18656).   Thus let's see if this just 'goes away' as that change gets propagated.  

@lmolkova  given the sketchiness of synchronization and that fact that really the test DiagnosticSourceStartStop was really not trying to deal with precision at all, we may wish to increase the Sleep to 100msec just to avoid inaccuracy causing spurious failures.

**Comment by danmosemsft** [comment]
This gives a linke number 397 but that doesn't ssem to correspond to an assert...

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170425.01/workItem/System.Diagnostics.DiagnosticSource.Tests/analysis/xunit/System.Diagnostics.Tests.ActivityTests~2FDiagnosticSourceStartStop

**Comment by danmosemsft** [comment]
The test does not repro locally on full fx (`msbuild /t:test /p:forceruntests=true /p:targetgroup=netfx`) but I only ran it once.

**Comment by lmolkova** [comment]
@vancem I believe the reason for test failure is that we compare precise time from Activity with imprecise DateTime.UtcNow, but I increased sleep time.

@Jiayili1 if the test fails again, it would be great to have exact line/stack trace.

**Comment by Jiayili1** [comment]
Another test failed with same issue: System.Diagnostics.Tests.ActivityTests.StopWithoutTimestamp

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/31/testReport/System.Diagnostics.Tests/ActivityTests/StopWithoutTimestamp/

MESSAGE:
~~~
Assert.True() Failure
    Expected: True
    Actual: False
~~~
STACK TRACE:
~~~
at System.Diagnostics.Tests.ActivityTests.StopWithoutTimestamp() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Diagnostics.DiagnosticSource\tests\ActivityTests.cs:line 292
~~~

**Comment by vancem** [comment]
It is likely to addressed by PR #18962

**Comment by stephentoub** [comment]
Closing under the assumption this was fixed by #18962.  Please re-open if it wasn't.

**Comment by CIPop** [comment]
Failed in NetFX tests for #21739

https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/616/consoleFull

```
16:52:03 D:\j\workspace\windows-TGrou---2a8f9c29\Tools\tests.targets(346,5): warning MSB3073: The command "D:\j\workspace\windows-TGrou---2a8f9c29\bin/Windows_NT.AnyCPU.Release/System.Diagnostics.DiagnosticSource.Tests/netfx//RunTests.cmd D:\j\workspace\windows-TGrou---2a8f9c29\bin/testhost/netfx-Windows_NT-Release-x86/" exited with code 1. [D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.DiagnosticSource\tests\System.Diagnostics.DiagnosticSource.Tests.csproj]
16:52:03 D:\j\workspace\windows-TGrou---2a8f9c29\Tools\tests.targets(354,5): error : One or more tests failed while running tests from 'System.Diagnostics.DiagnosticSource.Tests' please check D:\j\workspace\windows-TGrou---2a8f9c29\bin/Windows_NT.AnyCPU.Release/System.Diagnostics.DiagnosticSource.Tests/netfx/testResults.xml for details! [D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.DiagnosticSource\tests\System.Diagnostics.DiagnosticSource.Tests.csproj]
16:52:03 Command execution failed with exit code 1.


16:39:44   Running tests... Start time: 16:39:43.87
16:39:44   xUnit.net Console Runner (64-bit Desktop .NET 4.0.30319.42000)
16:39:46     Discovering: System.Diagnostics.DiagnosticSource.Tests
16:39:46   xUnit.net Console Runner (64-bit Desktop .NET 4.0.30319.42000)
16:39:46     Discovered:  System.Diagnostics.DiagnosticSource.Tests
16:39:46     Starting:    System.Diagnostics.DiagnosticSource.Tests
16:39:46     Discovering: System.Diagnostics.StackTrace.Tests
16:39:47     Discovered:  System.Diagnostics.StackTrace.Tests
16:39:47     Starting:    System.Diagnostics.StackTrace.Tests
16:39:47       System.Diagnostics.Tests.ActivityTests.StopWithoutTimestamp [FAIL]
16:39:47         Assert.InRange() Failure
16:39:47         Range:  (980 - 1.79769313486232E+308)
16:39:47         Actual: 972.2623
16:39:47         Stack Trace:
16:39:47           D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.DiagnosticSource\tests\ActivityTests.cs(327,0): at System.Diagnostics.Tests.ActivityTests.StopWithoutTimestamp()

```

**Comment by danmosemsft** [comment]
Moving to 2.1 as the failure was in the netfx run, which does not involve the 2.0 product. Test issue

**Comment by vancem** [comment]
@brianrob
