### ISSUE TITLE
Distinguish x86 and x64 build jobs

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#16850]
Our Windows Debug builds appear to be x86 while the Release builds are x64, but that distinction isn't obvious: it's not called out in the job name, all of the home page badges suggest all of the builds are x64, etc.  We should fix all of this to make it clear what's being tested.
cc: @mmitche, @mellinoe, @danmosemsft

**Comment by danmosemsft** [comment]
This should just be an edit to netci.groovy and README.md.

**Comment by mellinoe** [comment]
I'll give this a shot. Shouldn't be too hard.
