### ISSUE TITLE
Failure in WaitForChangedTests.Changed_Success 

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16857]
@JeremyKuhne, @ianhays this gave us a red badge this morning.

Perhaps this is just the intrinsic unreliability of FSW -- maybe there's a way to make it more robust, eg., try twice? 

``` c#
                Assert.Equal(WatcherChangeTypes.Changed, t.Result.ChangeType);
```

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu16.10_debug/lastCompletedBuild/consoleText
```
    System.IO.Tests.WaitForChangedTests.Changed_Success [FAIL]
        Assert.Equal() Failure
        Expected: Changed
        Actual:   0
        Stack Trace:
           /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu16.10_debug/src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.WaitForChanged.cs(174,0): at System.IO.Tests.WaitForChangedTests.Changed_Success()
```

**Comment by Jiayili1** [comment]
Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu16.10_debug/117/testReport/System.IO.Tests/WaitForChangedTests/Changed_Success/

**Comment by ianhays** [comment]
>Perhaps this is just the intrinsic unreliability of FSW -- maybe there's a way to make it more robust, eg., try twice?

I added retrying to most of the FSW tests already. This is one of a couple of tests that don't have it because they've already got long timeouts and live in Outerloop. That isn't really a perfect solution still though because the OS can still drop events and cause failures regardless of timeout length.

No reason we can't add Retries to these as well. It's not an ideal solution because it can potentially conceal future real errors, but it's better than just ActiveIssuing the tests and forgetting about them. At least we know *why* they're failing, we just can't do much about it beyond trying again or letting the test fail.

**Comment by JeremyKuhne** [comment]
@ianhays If there is no guarantee that the OS will produce an event it makes total sense to retry (and document). As to masking errors- thinking through what could go wrong if we've verified a happy path we might be able to suss out some more tests to mitigate (perhaps utilizing non-public reflection to poke our own state).

**Comment by danmosemsft** [comment]
>  because they've already got long timeouts and live in Outerloop

We should be careful not to think of Outerloop as the home of flaky tests any more. (We did temporarily dump networking tests there while we stablized them.) Outerloop is the place to get more OS configurations, and to run excessively slow tests. But it's nearly as expensive when stuff fails, our badges turn red, we still open issues and analyze them, make fixes, failures can obscure real bugs. Arguably tests in outerloop need to have an even tinier unreliability rate because there's a huger number of tests and configurations run in outerloop.

**Comment by danmosemsft** [comment]
What that means for FSW tests where the API is apparently intrinsically flaky is perhaps that we pick a certain tolerable failure rate and make the test verify that rate. Say, we expect to get the right notification 99% of the time and we would accept 1 spurious failure a month out of 10,000 runs. Then we can calculate a test retry count we are willing to accept. If that's too much thinking, we could try 2 or something :)
