### ISSUE TITLE
FindSystemTimeZoneById doesn't support "Eastern Standard Time" on Ubuntu

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/corefx#16871]
@AlexHankins commented on [Wed Mar 08 2017](https://github.com/dotnet/coreclr/issues/10042)

Method:  System.TimeZoneInfo.FindSystemTimeZoneById

According to [Time Zone IDs (Compact 2013)](https://msdn.microsoft.com/en-us/library/gg154758.aspx), this method would accept `"Eastern Standard Time"` as a parameter.  However, on Ubuntu 16.04, this fails with `System.TimeZoneNotFoundException: The time zone ID 'Eastern Standard Time' was not found on the local computer. ---> System.IO.FileNotFoundException: Could not find file '/usr/share/zoneinfo/Eastern Standard Time'`.

#### Workaround:

Try the Time Zone ID.  If that fails, look up by [TZ database value](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones):

```c#
            TimeZoneInfo easternTime;
            try {
                 easternTime = TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time");
            }
            catch (Exception ex)
            {
                 easternTime = TimeZoneInfo.FindSystemTimeZoneById("US/Eastern");
            }
```

**dotnet --info output:**

dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
Version: 1.0.1
Commit SHA-1 hash: 005db40

Runtime Environment:
OS Name: ubuntu
OS Version: 16.04
OS Platform: Linux
RID: ubuntu.16.04-x64
Base Path: /usr/share/dotnet/sdk/1.0.1

**Comment by gkhanna79** [comment]
@karelz @tarekgh PTAL

**Comment by tarekgh** [comment]
#2538 and #338 already tracking such issues.
