### ISSUE TITLE
Enable CdsSyncEtwBCLProvider for uapaot build of System.Threading

### ISSUE THREAD

**Issue by AntonLapounov** [dotnet/corefx#16881]
This requires adding EventSource to System.Private.CoreLib.

**Comment by brianrob** [comment]
This depends on #12652.

**Comment by karelz** [comment]
@AntonLapounov when you file bugs you immediately work on, can you please set the labels right away? It saves time to area owners to triage them later. See [simplified triage rules](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified). I'll be happy to explain the ideas behind in person.

**Comment by karelz** [comment]
@AntonLapounov when you file bugs you immediately work on, can you please set the labels right away? It saves time to area owners to triage them later. See [simplified triage rules](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified). I'll be happy to explain the ideas behind in person.

**Comment by brianrob** [comment]
@AntonLapounov, EventSource is now present and functional in UAPAOT.  You should be unblocked here.

**Comment by AntonLapounov** [comment]
Fixed by #22148.
