### ISSUE TITLE
Proposal: Add static ExceptionDispatchInfo.Throw(Exception)

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#16896]
If you have an exception object and you want to throw it without overwriting its existing call stack and bucket information, you do:
```C#
ExceptionDispatchInfo.Capture(exception).Throw();
```
This is unnecessary ceremony and also incurs some additional unnecessary cost (though we're on an exceptional path so the cost doesn't matter as much).  It'd be nicer if we could simply write:
```C#
ExceptionDispatchInfo.Throw(exception);
```

I propose we add the following method:
```C#
public sealed class ExceptionDispatchInfo
{
    public static void Throw(Exception source);
    ...
}
```

Its visible behavior would be identical to using Capture/Throw, so a valid implementation would be:
```C#
public static void Throw(Exception source) => Capture(source).Throw();
```
but a more efficient implementation could be provided that didn't need to allocate an EDI, copy all of the Exception's state into it, and then copy all of the state back.

**Comment by stephentoub** [comment]
An alternate shape that achieves the same purpose would be an instance or extension method on Exception, ala what @danmosemsft suggests at https://github.com/dotnet/corefx/pull/16898#issuecomment-285411090, e.g.
```C#
exc.Rethrow();
```

**Comment by stephentoub** [comment]
cc: @gkhanna79

**Comment by danmosemsft** [comment]
I would vote for an instance method on Exception as this seems core, commonly needed functionality.

**Comment by gkhanna79** [comment]
IMHO, adding the Rethrow method on Exception type would have the potential to confuse our users - whether to use "throw;" for rethrow or this new method, especially when rethrow semantics that exist today do maintain the stack trace.

Having the method off EDI maintains the segregation of semantics and intention.

CC @jkotas @rahku

**Comment by JonHanna** [comment]
I like the extension as a middle path, in that it has the convenience of @danmosemsft's idea, but only when the relevant namespace is in use (and even if an IDE did the work of adding the namespace, it should still be reasonably obvious that it did so).

**Comment by danmosemsft** [comment]
I'm curious why we can't make "throw ex;" attach the original stack (eg., in a new field on Exception) so that presumably EDI isn't needed and the "right thing just happens for free". Is that too breaking even to do in Core? Or just a big feature?

**Comment by jkotas** [comment]
There are situations where folks cache the exception and keep throwing it again and again. If `throw ex` did not reset the stacktrace to the current one, you would get memory leak (if it kept appending) or stale stacktrace (if it just kept what is there intact).

**Comment by jkotas** [comment]
@stephentoub Could you please link some real world code where would you use this? I would think that there are two situations:

- You want to rethrow the exception from inside the catch block. In this case, `throw;` should do the right thing.
- You want to pack the exception inside the catch block, move somewhere else (e.g. different thread), and rethrow it from there. In this case, call ExceptionDispatchInfo.Capture in the catch block and ExceptionDispatchInfo.Throw from the new spot.

Am I missing something?

**Comment by stephentoub** [comment]
> I would think that there are two situations

The two you mention are the most common.  But there are others, e.g.
- A large codebase that's passing around results/exceptions, e.g. using an older asynchronous pattern.  It's much easier to simply change how the exception is thrown at the end rather than trying to plumb an ExceptionDispatchInfo all the way through.  You ask for examples "except System.Net", but that's a real-world code example of this.
- Retry operations, or operations that involve trying multiple things.  You try op1, it throws an exception, so you catch and hold onto that.   Then you try op2; if it succeeds, you're done and you move on, if not you go on to op3, etc.  Eventually if they all fail then you throw one of the exceptions you got, and at that time you use ExceptionDispatchInfo to do it.  Depending on the construction, it could be possible to structure this such that you can propagate the last exception from its catch block, but you might want to propagate the first one instead, or organizing the code to enable that might be more challenging.  You can capture the ExceptionDispatchInfo for every exception, but that's unnecessary overhead, and it's instead easier to just re-throw the exception you actually want to propagate when/where you want to.

**Comment by danmosemsft** [comment]
> stale stacktrace (if it just kept what is there intact).

In my opinion that is okay (you could call the field _potentiallyRelevantStack if you want to make it clear...) the point of the callstacks in an exception are diagnostics for a developer, and a developer is sophisticated enough to be able to handle the fact that it may not be relevant. It could save expensive work such as changing the code and waiting for another repro, or attaching a debugger and attempting to repro etc.

**Comment by jkotas** [comment]
There is more than just the textual stacktrace. The Exception and ExceptionDispatchInfo also contains extra data for bucketing the crashes that an extra textual _potentiallyRelevantStack field would not just work.

A convenience method that does `Capture(source).Throw()` sounds reasonable for me. Would `ExceptionDispatchInfo.Rethrow` be a better name for it?

**Comment by danmosemsft** [comment]
I guess I've been in the situation countless times in previous teams where I've been looking at some log after the fact where either the system or some test harness logged ex.ToString() and that's all I've got. This is all we had in many cases for networking before Stephen made his change to the networking code, and there's still 150 hits of "throw XX" left in CoreFX of which some proportion involve losing the callstack. Extend this to all the other C# in the world and there's innumerable instances that won't realistically change to use a new method. My options in this case might be change the code and wait for another hit sometime, or often it was a customer and I don't have the opportunity to retrospectively change the code unless I sign something and share it.  That's my reasoning.

**Comment by davidfowl** [comment]
Here's an example:

https://github.com/aspnet/DependencyInjection/blob/7484d22ec24263342fcc9c865b993d183282660c/src/Microsoft.Extensions.DependencyInjection/ServiceLookup/CallSiteRuntimeResolver.cs#L33

**Comment by gkhanna79** [comment]
Changing `throw ex;` behaviour is also a breaking change. Also, not all such uses expect to perform a rethrow - they do know it will be a reset of stacktrace.

**Comment by danmosemsft** [comment]
@gkhanna79 that's why I was suggesting adding it to a new field on Exception. If there is custom serialization of exception or suchlike - it would be lost. I imagine that's usually not the case.

**Comment by terrajobst** [comment]
Looks good as proposed.

**Comment by gkhanna79** [comment]
>  I was suggesting adding it to a new field on Exception

Please see my earlier response - it sounds confusing relative to the existing usage semantics.

**Comment by danmosemsft** [comment]
@gkhanna79 I thought your pushback was a new method on Exception. A new field would not change usage.

**Comment by gkhanna79** [comment]
What purpose would this public do?

**Comment by danmosemsft** [comment]
It means if I inspect the exception in a debugger, or possibly do ToString() on it, I see this extra information that may potentially be useful.

**Comment by karelz** [comment]
Marking as up for grabs - code is mentioned by Stephen above. The only complexity is exposing a new API.
Any takers?
