### ISSUE TITLE
Slow Open Connection every 4 mintutes or so

### ISSUE THREAD

**Issue by FrancoisM** [dotnet/corefx#16892]
In this [SO post](http://stackoverflow.com/questions/42433948/azure-web-api-waiting-sql-connection-every-4-minutes-and-30-minutes), I described an anlysis where I observe that opening a connection is blocked on waiting for a long time every 4 minutes or so. However, I couldn't find out why and never got any answers either.

**Comment by karelz** [comment]
@FrancoisM do you have a small repro? That would speed up investigation greatly.

**Comment by saurabh500** [comment]
@FrancoisM Can you provide a repro?

**Comment by karelz** [comment]
11 days no response, closing. Feel free to reopen if there's a repo.
