### ISSUE TITLE
unmanaged resource leak when HttpClient is not disposed

### ISSUE THREAD

**Issue by proff** [dotnet/corefx#16897]
```
        [Test]
        public void Test()
        {
            TestInternal().Wait();
            GC.Collect();
            GC.WaitForPendingFinalizers();
            GC.Collect();
            dotMemory.Check(m =>
            {
                Console.WriteLine(m.GetObjects(a => a.Type.Like("System.Net.Http.HttpClient")).ObjectsCount); //always 0
                Console.WriteLine(m.GetObjects(a => a.Type.Like("System.Net.Connection")).ObjectsCount); //0 on Dispose(), 2 on Dispose(false) or without Dispose
            });
        }
        private static async Task TestInternal()
        {
            var client = new HttpClient();
            var s = await client.GetStringAsync("http://msdn.com");
            //client.Dispose();
            /*client.GetType()
                .GetMethod("Dispose", BindingFlags.NonPublic | BindingFlags.Instance)
                .Invoke(client, new object[] {false});*/
        }
```
![a001a-clip-78kb](https://cloud.githubusercontent.com/assets/991922/23751339/e9da0ecc-04e1-11e7-9a34-99aed0636545.png)
![003ed-clip-185kb](https://cloud.githubusercontent.com/assets/991922/23751446/74d90988-04e2-11e7-9323-a00ea38e6813.png)

HttpClient missing finalizer and Dispose(false) called from finalizer will do nothing

**Comment by davidsh** [comment]
This is a .NET Framework issue and not .NET Core.  So, this issue should be entered into the Connect bug reporting.

But, in terms of the "leak", keep in mind that the repro code here using GC.Collect() is not actually measuring leaks.  GC.Collect() will not necessary do all garbage collection immediately. These resources will be freed eventually before the process exits.

If you really want to measure true leaks, you need to create a long-running repro case with perhaps hundreds or thousands of iterations of HTTP requests.  Then, take a look at working set, handles, etc.  If those are being leaked, the working set will grow over time and not reduce.

cc: @stephentoub

**Comment by davidsh** [comment]
Closing this since it is not .NET Core specific and the methodology used to track "memory leaks' should be changed as per the guidance given above.

**Comment by CleverCoder** [comment]
Was an associated bug in the framework project created?

**Comment by proff** [comment]
I dont submitted it to connect because it will waste of time, because all bugs are features in connect
