### ISSUE TITLE
When call build.cmd -skiptests, build stops with error PE file is already strong-name signed

### ISSUE THREAD

**Issue by wildtang** [dotnet/corefx#16900]
Today I pull coreclr and corefx, build them on my Win10 with VS2015u3,
The build of coreclr finished without error,
But the build of corefx failed with the following strong-name sign error like following:

> Running: U:\OpenSrcResearch\MicrosoftOnGithub\corefx\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false /l:BinClashLogger,Tools\net45\Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log /p:SkipTests=true /p:OSGroup=Windows_NT /p:TargetOS=Windows_NT /p:ConfigurationGroup=Debug  /flp:v=normal  /flp2:warningsonly;logfile=msbuild.wrn  /flp3:errorsonly;logfile=msbuild.err
>   [21:50:05.58] Verifying all auto-upgradeable dependencies...
>   [21:50:18.36] Verifying all auto-upgradeable dependencies... Done.
>   [21:50:18.36] Restoring all packages...
>   [21:50:32.95] Restoring all packages...Done.
> U:\OpenSrcResearch\MicrosoftOnGithub\corefx\Tools\sign.targets(70,5): error : U:\OpenSrcResearch\MicrosoftOnGithub\corefx\bin/obj/ref/Microsoft.CSharp/4.0.0.0/Microsoft.CSharp.dll: PE file is already strong-name signed. [U:\OpenSrcResearch\MicrosoftOnGithub\corefx\src\Microsoft.CSharp\ref\Microsoft.CSharp.csproj]
>   Microsoft.VisualBasic -> U:\OpenSrcResearch\MicrosoftOnGithub\corefx\bin\ref\Microsoft.VisualBasic\10.0.0.0\Microsoft.VisualBasic.dll
> U:\OpenSrcResearch\MicrosoftOnGithub\corefx\Tools\sign.targets(70,5): error : U:\OpenSrcResearch\MicrosoftOnGithub\corefx\bin/obj/AnyOS.AnyCPU.Debug/Microsoft.VisualBasic/Microsoft.VisualBasic.dll: PE file is already strong-name signed. [U:\OpenSrcResearch\MicrosoftOnGithub\corefx\src\Microsoft.VisualBasic\src\Microsoft.VisualBasic.vbproj]

**Comment by wildtang** [comment]
How can I skip the strong-name sign process when build corefx?

**Comment by weshaggard** [comment]
What branch are you building? It looks pretty hold as we haven't been doing the "Restoring all packages..." for a couple months in master. I would suggest you pulling the latest changes from master and doing a "clean.cmd -all" followed by a "build.cmd"

**Comment by wildtang** [comment]
The branch I am building is release/1.1.0

**Comment by weshaggard** [comment]
I wouldn't expect this to happen at all on a clean build but if you want to essentially turn off signing you can pass `/p:SignType=oss` to the build to tell it to only do OSS signing which is limited.
