### ISSUE TITLE
Publish document about reference assemblies, contracts, and facades.

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#1690]
We are beginning to open source our facades and soon our contracts and so we need to add some documentation for people to better understand how these all work.

**Comment by SidharthNabar** [comment]
+1 Yes - let's have this please :) - It'll also greatly help as a reference for other documents and blogs where we mention words like "contracts" and "façades".

**Comment by hughbe** [comment]
I think we have this file now: https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/project-guidelines.md

If there is anything else to be added, I can do this. Else, this could probably be closed

**Comment by weshaggard** [comment]
@hughbe thanks for the offer but this is meant to track the publishing of a document we have internally which defines what each of these are with some diagrams. It needs a lot of reworking and updating and I will hopefully find some time at some point but right now it isn't a priority for me.
