### ISSUE TITLE
Inspect the files in .NET Core App and remove any unnecessary ones

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#16912]
We are getting close to a preview release so we should inspect all the files in the shared framework (in particular the private netcoreapp package from corefx) and make sure there isn't anything that shouldn't be there.

Some potential candidates for removal are:
System.Security.Permissions
System.Text.Encoding.CodePages.

cc @ericstj @Petermarcu

**Comment by Petermarcu** [comment]
These are assemblies that are there and not longer used as implementations of things in netcoreapp2.0 and are also not exposed in the API surface area.

**Comment by weshaggard** [comment]
Yes anything where the ref was a placeholder in previous .NET Core applications (ex: https://github.com/weshaggard/tests/blob/master/netcoreapp/1.1.1-nca11/project.assets.json#L6840) that are also not part of the implementation closure any longer are candidates for removal.

**Comment by mellinoe** [comment]
It's not exactly directly related to what this issue is probably referring to, but we should think about removing the duplicated dlls for which there are ni.dll's already. For example, we have both System.Private.CoreLib.dll and mscorlib.dll, even though their ni.dll's are there. We could save a little bit of space if we removed the former. This could also help the size of published applications, assuming we don't have some logic that filters that out (I don't think we do).

**Comment by Petermarcu** [comment]
Yeah, thats tracked here: https://github.com/dotnet/core-setup/issues/1484

**Comment by mellinoe** [comment]
Great! Carry on, then 😄

**Comment by ericstj** [comment]
It looks like Security.Permissions cannot come out because it is an implementation dependency of Registry and Net.Mail.  Codepages cannot come out because it is an implementation dependency of SqlClient.

**Comment by weshaggard** [comment]
I still want to take a closer look at those dependencies and break them if possible.

**Comment by ericstj** [comment]
@weshaggard I had a look and couldn't find anything that stuck out.   I know you did some removals.  Close this if you think you're done.

**Comment by weshaggard** [comment]
I want keep this open for now as I want to do an audit before we release after most of the changes are in to ensure we didn't pull in any other unwanted dependencies.

**Comment by weshaggard** [comment]
As part of this we need to audit the IsNetCoreRef=false cases and see if we can exclude any of those from some shared framework for some OS's.  Example https://github.com/dotnet/corefx/pull/18647 we should be able to remove those dependencies on unix now.

**Comment by weshaggard** [comment]
I think we can close this issue now I verified the bits in preview1 look reasonable. I will also be looking at these closer to release to double check but we don't need to keep this issue around to track that.
