### ISSUE TITLE
To Remove System.Xml.XmlSerializer.Tests.settings.targets

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#16914]
We'd like to remove System.Xml.XmlSerializer.Tests.settings.targets so that the XmlSerializer test projects would have the same structure as others. 

As part of the issue, we would need to add ProjectReferences in System.Xml.XmlSerializer.Tests.csproj.

/cc: @zhenlan

**Comment by danmosemsft** [comment]
I already have this in https://github.com/dotnet/corefx/pull/16704 but I didn't add any project references -- should I ? I can either revert this part or you could tell me what I should add.

**Comment by shmao** [comment]
Thanks for removing the file, @danmosemsft. The project references needed to be added are shown below, (they were in `System.Xml.XmlSerializer.Tests.settings.targets`)

```
    <ProjectReference Include="$(TestSourceFolder)..\..\System.Runtime.Serialization.Xml\pkg\System.Runtime.Serialization.Xml.pkgproj" />
    <ProjectReference Include="$(TestSourceFolder)..\..\System.Runtime.Serialization.Json\pkg\System.Runtime.Serialization.Json.pkgproj" />
```

Can you add them into `System.Runtime.Serialization.Xml.Tests.csproj` and `ReflectionOnly\System.Runtime.Serialization.Xml.ReflectionOnly.Tests.csproj`. Thanks!

**Comment by danmosemsft** [comment]
Those project references do not exist. Of course it was not erroring, because that targets file was not being used. Anything to do here?

**Comment by shmao** [comment]
@danmosemsft sorry, I gave wrong project references above. I've updated them to the right ones. However, they still do not exist anymore...

We used to have those `<ProjectReference>` so that the test project could test the package built from the repo instead of testing the one downloaded from myget. But I just found that most of the `\pkg` folders had been removed, e.g. the `\pkg` folder under `System.Private.Xml` had been removed. Does it mean that our test project does not need to explicitly reference the assembly being tested as `<ProjectReference>` anymore?

**Comment by danmosemsft** [comment]
I believe so. @joperezr

**Comment by danmosemsft** [comment]
Closing meantime as this is done in https://github.com/dotnet/corefx/pull/16704

**Comment by joperezr** [comment]
< Does it mean that our test project does not need to explicitly reference the assembly being tested as <ProjectReference> anymore?

Correct. We don't use myget anymore with our new infrastructure changes (at least not for anything that is built on the corefx repo itself). Which means that all tests are already referencing the live version of all assemblies by default so we don't need to specifically add ProjectReferences any longer.

**Comment by shmao** [comment]
@joperezr sounds good! Thanks for the explanation.

/cc: @zhenlan
