### ISSUE TITLE
SNI identity package not being built 

### ISSUE THREAD

**Issue by saurabh500** [dotnet/corefx#16918]
The SNI identity package at https://github.com/dotnet/corefx/blob/master/src/Native/pkg/runtime.native.System.Data.SqlClient.sni/runtime.native.System.Data.SqlClient.sni.pkgproj was last built on 1/13/2017 and has a version 4.4.0-beta-24913-02 

This identity package doesn't reference the latest SNI runtime assemblies which are being uploaded to myget from an internal build system. 
As a result, the sni identity package still points to version 4.3.0-xxxx of sni.dll. 
The current version is `<SniPackageVersion>4.4.0-beta-25007-02</SniPackageVersion>` from dependencies.props

cc @gkhanna79 @weshaggard @corivera @ericstj @dagood

**Comment by saurabh500** [comment]
Assigning to @ericstj as recommended offline by Wes and Gaurav

**Comment by ericstj** [comment]
I went ahead and turned this on, though it might be better if you built the identity package in your own repo. That way you only have to update one thing in corefx: the version of the identity package.

**Comment by ericstj** [comment]
@saurabh500 what do you think about producing the identity package in your repo?
