### ISSUE TITLE
[NetFX compat]: HttpWebRequest.GetRequestStreamAsync() hangs in desktop

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#16928]
When creating multiple `HttpWebRequest` instances and calling `GetRequestStreamAsync()` it hangs in desktop. There is a test class that does this and when running it in desktop it just hangs forever because all the tests create an `HttpWebRequest` instance and call `GetRequestStreamAsync().GetAwaiter().GetResult()` -- [source code](https://github.com/dotnet/corefx/blob/master/src/System.Net.Requests/tests/RequestStreamTest.cs#L107-L112) the project test is `System.Net.Requests.Tests`

I did this on a simple Console App targeting desktop:

```cs
static void Main(string[] args)
{
     for(int i = 0; i < 100; i++)
     {
          var request = GetRequest();
          var stream = request.GetRequestStreamAsync().GetAwaiter().GetResult();
          Console.WriteLine(stream.CanWrite);
          stream.Dispose();
          //request.Abort()
     }
}

public static HttpWebRequest GetRequest()
{
     HttpWebRequest request = HttpWebRequest.CreateHttp(new Uri("<myserverurl>"));
     request.Method = "POST";
     return request;
}
```

And it will also hang. If I just enable `request.Abort()` when I'm done using the request it will stop hanging.  I don't know if that is a good practice, but could be a workaround in the tests for desktop.

If we change the `ServicePointManager.DefaultConnectionLimit` to be a 100 it would also fix it but I don't think that would be a good solution.

After talking with @stephentoub he explained there was a difference in behavior in Core:

> My guess here is that disposing of the request stream doesn't release the underlying connection that HttpWebREquest opens to the server, and that the only way to do that would be to then get the response and dispose of that. That's why changing the connection limit allowed you to get further, because the system wasn't throttling you to the two connections you already opened. On core, HttpWebRequest is built on top of HttpClient, and  it's not going to actually open the connection until you've written all your data.

That is why the test don't hang in Core. There is a related issue to this https://github.com/dotnet/corefx/issues/11873

cc: @davidfowl @CIPop @tarekgh

**Comment by davidsh** [comment]
>When creating multiple HttpWebRequest instances and calling GetRequestStreamAsync() it hangs in desktop. 

This is .NET Framework bug (potentially).  Yet, you marked it as [NETFX compat].  We only use that marking if this was a .NET Core bug and the behavior was different than .NET Framework (Desktop).

We don't track .NET Framework (Desktop) bugs here.  Please open up a bug in the Connect portal.

**Comment by safern** [comment]
Ok, still I will be disabling the tests for Desktop.

**Comment by tarekgh** [comment]
> We don't track .NET Framework (Desktop) bugs here. Please open up a bug in the Connect portal

@davidsh could you please help logging the issue on connect and paste the issue link here? Thanks.

**Comment by davidsh** [comment]
cc: @weshaggard

**Comment by karelz** [comment]
@davidsh so it is a dupe of the "stop shipping System.Net.Http Nuget package" #16805?

**Comment by davidsh** [comment]
>@davidsh so it is a dupe of the "stop shipping System.Net.Http Nuget package" #16805?

No.  This is NOT a dupe.

The current System.Net.Requests package is separate from System.Net.Http.  This package needs changes to the build mechanism so the 'net46' target will be generated and needs to be full facade.  The 'netstandard' target can remain as-is with the .NET Core implementation.

**Comment by davidsh** [comment]
By the way, this is NOT an OOB package.  There is no System.Net.Requests package/dll on Desktop. Historically, it has been a facade in the Win 8/8.1 Store Profile.  But changed to implementation w/ NET Core.

**Comment by weshaggard** [comment]
@davidsh this library already exists inbox on .NET Framework so the package has a placeholder file for net45 and so we cannot put a facade in this package as we should only keep what is there already inbox. So there shouldn't need to be any package changes for this issue.  

So I think the issue is still that we have a difference in behavior on .NET Framework vs .NET Core and if we want to fix .NET Framework we should track the bug there and fix it.

**Comment by davidsh** [comment]
>So I think the issue is still that we have a difference in behavior on .NET Framework vs .NET Core and if we want to fix .NET Framework we should track the bug there and fix it.

Ok. So, this really then is a bug in .NET Framework.  On .NET Core, we don't see this bug due to #11873.  Once we fix #11873, then we might see the same behavior.

So, regardless.  I think this issue needs to be closed here because there currently is not a hang with .NET Core and this is clearly a .NET Framework specific bug.

**Comment by safern** [comment]
> So, regardless. I think this issue needs to be closed here because there currently is not a hang with .NET Core and this is clearly a .NET Framework specific bug.

Yes as I mentioned in the issue's main comment this is a .NET Framework specific bug where that code path will hang but in .NET Core it will not. I opened this issue to track it and add it to the `SkipOnTargetFrameworkAttribute` under the tests that were hanging so that when we scan those tests we know what is happening and why we are skipping them. So we can close it if you want.

**Comment by tarekgh** [comment]
@davidsh could you log a bug for the desktop? 

@safern please ensure the test is skipped

**Comment by karelz** [comment]
@tarekgh for logging Desktop bug we should just mark this one with netfx-port-consider label. And we can close it right away.

**Comment by safern** [comment]
@tarekgh the tests are skipped and linked to this issue.

**Comment by kenticomartinh** [comment]
Hi guys, we had the same problem (MVC 6, Framework version 451) and found out that the problem was not disposing the response after the request was executed. The code should call .GetResponse[Async]() and then .Dispose() the response after it is not necessary anymore. If the response was not Disposed, next (typically 3rd) call kept hanging on .GetRequestStream[Async]()

Hope this is related / helps
