### ISSUE TITLE
[NetFX compat]: Desktop doesn't have cancellation support.

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#16934]
There is two tests in `System.IO.Pipes` that hang forever when running in desktop. Desktop doesn't have cancellation support and this tests are trying to cancel a Task through a `CancellationToken`. 
* [Test 1](https://github.com/dotnet/corefx/blob/master/src/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.Simple.cs#L526-L561)
* [Test 2](https://github.com/dotnet/corefx/blob/master/src/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.Simple.cs#L624-L657)

We could consider adding this support on Desktop. 

cc: @stephentoub @tarekgh

**Comment by kouvel** [comment]
It looks like WriteAsync is not there in the desktop framework, how does it compile? Also I guess any cancellation support would have to be done in Stream first, moving to System.IO/Pipelines.

**Comment by stephentoub** [comment]
We should probably change those tests from ActiveIssue to SkipOnTargetPlatform.  The tests are validating a feature that's not yet in desktop.

> It looks like WriteAsync is not there in the desktop framework, how does it compile?

Which method are you referring to?  Stream.WriteAsync(byte[], int, int, CancellationToken) exists in desktop.

**Comment by kouvel** [comment]
Oops missed that, guess it would be in PipeStream

**Comment by safern** [comment]
Closing per: https://github.com/dotnet/corefx/pull/37972
