### ISSUE TITLE
ImmutableHashSet inconsistently accepts and rejects null values

### ISSUE THREAD

**Issue by madelson** [dotnet/corefx#16948]
It is possible to create an `ImmutableHashSet<T>`  containing a null value using `ImmutableHashSet.CreateRange<T>` and `Union`. However, other methods of doing so (`Add`, `Create<T>(T)`) result in `ArgumentNullException`:

```
var set = ImmutableHashSet<string>.Empty;
set = set.Add(null); // throws
set = set.Union(ImmutableHashSet.CreateRange(new string[] { null })); // adds null
```

Similarly, trying to remove a null with `Remove` throws but the null can be removed using `Except`.

This seems like a bug. I think these sets should allow null as an element since this can be useful functionality (note that `HashSet<T>` allows null elements).

**Comment by danmosemsft** [comment]
@AArnott

**Comment by AArnott** [comment]
Thanks for reporting, @madelson. You bring up an interesting point on the inconsistency. 

This overall problem is already tracked by #15403
