### ISSUE TITLE
In Web Request there is no way to set the Content-Type header without Content

### ISSUE THREAD

**Issue by vors** [dotnet/corefx#16947]
## Scenario

I want to do an equivalent of 
```
curl -X POST https://api.dropboxapi.com/2/team/get_info --header "Authorization: Bearer $AUTH_TOKEN"
```
Source:
https://www.dropbox.com/developers/documentation/http/teams#team-get_info

## Problem

Currently there is no way to do it.

## Details

I need to set Content-Type header on a request without setting Content.
Currently there is no way to do it, because to setup the Content-Type, I should call `request.Content.Headers['Content-Type']`. But if `Content` is not null, the body would not be null.

If I do set this up and send empty body, I will get an error:
```
Error in call to API function "team/get_info": request body: could not decode input as JSON
``` 

If I don't set it up and send request with no Content, I'm getting this error:
```
Error in call to API function "team/get_info": Bad HTTP "Content-Type" header: "application/x-www-form-urlencoded".  Expecting one of "application/json", "application/json; charset=utf-8", "text/plain; charset=dropbox-cors-hack".
```

Originally reported at https://github.com/PowerShell/PowerShell/issues/3131 this appeared to be a corefx problem.

**Comment by cakoose** [comment]
Tangent: to get your Dropbox API call to work, you should:
- Set `Content-Type: application/json`
- Put valid JSON in the request body.  The "team/get_info" call takes no parameters, so the body should contain the string "null".

**Comment by vors** [comment]
Oh, 'null' actually does the trick! Thank you for a workaround.

**Comment by karelz** [comment]
How common is the scenario? What would you suggest to change?

**Comment by cakoose** [comment]
(I'm looking in from the outside, so please excuse me if I'm misunderstanding something.)

It looks like @vors thought the Dropbox API required a `Content-Type` without an entity body?  This isn't true -- the entity body is required.  For the API request in his example, the entity body must be the string "null", which may have caused some confusion.

In general, I don't think it makes sense to have a `Content-Type` without an entity body, so I don't think there's anything to fix here.

**Comment by vors** [comment]
I could be wrong, but in my mind the fact that `null` string body worked for dropbox API is really a **workaround**.

> It looks like @vors thought the Dropbox API required a Content-Type without an entity body?

It intended to require no body, not "null" body, at least from [the documentation](https://www.dropbox.com/developers/documentation/http/teams#team-get_info):

In their example with `curl`, there is no "null" string-as-a-body passing.
```
curl -X POST https://api.dropboxapi.com/2/team/get_info --header "Authorization: Bearer $AUTH_TOKEN"
```

The fact that you can pass null is really a workaround and another backend in the same situation may not allow it.
For example, dropbox doesn't allow passing `{}` as a body.

In full .net framework, there was a separate [ContentType property](https://referencesource.microsoft.com/#System/net/System/Net/HttpWebRequest.cs,3f436e84703160b6), independent from the content body. Having it separately would solve the problem.

**Comment by karelz** [comment]
FYI: The same property is available also on .NET Core: [HttpWebRequest.ContentType](https://apisof.net/catalog/System.Net.HttpWebRequest.ContentType)

How common is the scenario that you need to send `Content-Type` without a body?

**Comment by vors** [comment]
I have no data about how common it is.

I actually confused `System.Net.Http.HttpRequestMessage` and `System.Net.Http.HttpRequest`. `HttpRequestMessage` is used with `System.Net.Http.HttpClient` and `HttpRequestMessage` doesn't have a separate `ContentType`.

**Comment by karelz** [comment]
Yes, it looks like the newer Http APIs (`HttpClient`) don't have separate `ContentType`. Changing that would require API change. If we go that route, we should be sure it is a common scenario. I would prefer to not add new APIs because of weird corner cases which are rarely used.

**Comment by cakoose** [comment]
According to the HTTP spec, every request may or may not have an "entity".  An entity consists of entity headers (e.g. `Content-Type`) and an entity body.  The presence of an entity is indicated by the presence of the `Content-Length` or `Transfer-Encoding` headers.

Typically, GET requests *do not* include an entity and POST requests *do* include an entity.  But that's not a hard requirement.  For example, you can make POSTs without entities; that's what @vors' cURL example does.

> I need to set Content-Type header on a request without setting Content.

I'm pretty sure this combination doesn't make sense.

**Should .NET Core support POST-without-entity?**

(I haven't tried it myself, but based on @vors' original report, it looks like maybe .NET Core can't do POST-without-entity.)

Do any services require it?  If so, that would be a good reason to add support.  (The Dropbox API *does not* require it; see below.)

API-wise, it seems intuitive: if `Content` is null, don't send an entity.  Unfortunately, this change seems likely to break existing code that depends on the current behavior, where .NET Core sends an entity with `Content-Type: application/x-www-form-urlencoded` and a zero-length entity body.

**Re: the Dropbox API**

Every Dropbox API call always takes a single JSON value as an argument.  When you make a POST request, the standard thing to do is to include an entity:
1. Send `Content-Type: application/json`.
2. Send the JSON value as the body.

The `team/get_info` API call doesn't need any information; it's single argument is defined to be a JSON null.  Passing in "null" *is not a workaround*.

As a convenience, the Dropbox API also accepts the POST-without-entity form when the argument is a JSON null.  That's what @vors' cURL example does:
1. It does NOT include a `Content-Type`.
2. It does NOT include an body.

**Comment by vors** [comment]
I'm going to close the issue, because it's likely to be uncommon.

**Comment by qmfrederik** [comment]
Here's another variation of this problem. Image you have an ASP.NET Core application which takes an optional JSON object as the content of a POST request:

```
[Route("very-important-url")]
[HttpPost]
public async Task<IActionResult> DoSomething([FromBody] string[] arguments, CancellationToken cancellationToken)
{
    return this.Ok();
}
```

If the content is optional, you can do a `POST /very-important-url` with `Content-Type application/json` and an empty body and ASP.NET Core will process the request.

However, if the `Content-Type application/json` header is missing, you will get `Response status code does not indicate success: 415 (Unsupported Media Type).` instead.

Posting `null` also works.
