### ISSUE TITLE
Consider adding PInvoke check against UWP list for tests built for UWP

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16944]
We do not run the PInvoke checker using the UWP list against tests as they do not need to go through store validation. However they do need to run in appcontainer and it's possible that they might end up using calls that do not work correctly there. It may be worth enabling the checker and baselining existing PInvokes so we think before we add any more.

Enabling this is just flipping a property in codeanalysis.targets.

@jkotas worth it?

https://github.com/dotnet/corefx/pull/16704

**Comment by jkotas** [comment]
How many PInvokes are there in the tests?

You will need to mark tests that do not work for UWP somehow. I think it should require as little ceremony as possible. Ideally, just mark the test with `[SkipOnTargetFramework(TargetFrameworkMonikers.UWP` or something similar.

If you start enabling things like PInvoke checker for tests, it will add to the ceremony required to deal with it.

**Comment by danmosemsft** [comment]
OK I won't bother unless this turns out to be a problem when we try to run them.
