### ISSUE TITLE
System.NotSupportedException when I want to load Assembly from Stream

### ISSUE THREAD

**Issue by Noldax** [dotnet/corefx#16967]
Hi everyone, 

I would like to load a DLL file from http://localhost:8080/bin/ and instantiate classes and functions in my .Net Core application.

But when I want to get the assembly I get this exception `System.NotSupportedException: Specified method is not supported.`

Here the code : 

```c#
string url = "http://localhost:8080/test-dll/Test.dll";

HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
request.Method = "GET";
using (var response = (HttpWebResponse)(await Task<WebResponse>.Factory.FromAsync(request.BeginGetResponse, request.EndGetResponse, null)))
{
    Stream answer = response.GetResponseStream();
    var myAssembly= AssemblyLoadContext.Default.LoadFromStream(answer);
}
```

How am I supposed to do that ? 

Thanks in advance !

**Comment by karelz** [comment]
Which API throws the exception? Networking or `LoadFromStream`? If it is `LoadFromStream` - does it happen with `FileStream` or `MemoryStream` as well?
Which version of .NET Core do you use?

**Comment by Noldax** [comment]
Thank you for your answer @karelz.

I resolve the problem by using the following code : 

```
using (HttpClient client = new HttpClient())
            {
                string url = "http://localhost:8080/test-dll/test.dll";
                using (var response = await client.GetAsync(url))
                {
                    response.EnsureSuccessStatusCode();

                    using (var inputStream = await response.Content.ReadAsStreamAsync())
                    {
                        var myAssembly= AssemblyLoadContext.Default.LoadFromStream(inputStream);

                        Type t = myAssembly.GetType("ConsoleApplication1.MyClass");
                        object myClass= Activator.CreateInstance(t);

                    }
                }
            }
```

**Comment by karelz** [comment]
So I guess it didn't work before, because of some limitation in `Task<T>.Factory.FromAsync` - maybe the conversion can do only so much. Can you paste the callstack you got with your original code?

**Comment by karelz** [comment]
cc @stephentoub if it is something interesting from async conversions point of view ...

**Comment by Noldax** [comment]
**Stack Trace :**
```
System.NotSupportedException: Specified method is not supported.
   at System.Net.Http.WinHttpResponseStream.get_Length()
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
```

**Comment by stephentoub** [comment]
> So I guess it didn't work before, because of some limitation in Task<T>.Factory.FromAsync 

No, that's unrelated.  This doesn't work by design: the Stream returned doesn't support seeking (it's streaming data from the server) and thus doesn't allow you to access its Length.  It worked when changing from using HttpWebRequest to HttpClient because the GetAsync method used with HttpClient by default buffers the output into a MemoryStream, which is the stream that ends up being returned and which supports Length.  If you were to change the GetAsync call from `GetAsync(url)` to `GetAsync(url, HttpCompletionOption.ResponseHeadersRead)`, you would then get the same exception.
