### ISSUE TITLE
PEBuilder.WriteCoffHeader does not populate the IMAGE_FILE_HEADER TimeDateStamp field

### ISSUE THREAD

**Issue by qmfrederik** [dotnet/corefx#16970]
The [PEBuilder.WriteCoffHeader](https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEBuilder.cs#L197) method does not populate the TimeDateStamp field of the IMAGE_FILE_HEADER struct.

Instead, it appears that random values are stored in this value every time a new file is generated.

I noticed this when trying to find out software started to show random build dates when compiled for .NET Core. We use logic similar to https://blog.codinghorror.com/determining-build-date-the-hard-way/ to get the compile date of an assembly.

**Comment by qmfrederik** [comment]
Code compiled with the NetFX compilers does have the TimeDateStamp set to a correct value.

I can submit a PR which fixes this behavior - seems easy enough. However, before doing so, I'd like to understand whether that PR would be accepted :), if you'd be OK with using `DateTime.Now`, and whether the Roslyn compilers use this code when running on .NET Core or whether there's another copy of this class somewhere over in the Roslyn repos?

/cc @tmat, @nguerrera as you were involved in adding this class to CoreFX in #5354

**Comment by nguerrera** [comment]
The timestamp is patched to a correct value [here](https://github.com/dotnet/corefx/blob/ec2a6190efa743ab600317f44d757433e44e859b/src/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEBuilder.cs#L116-L119)

The indirection through a provider is in support of deterministic (aka reproducible) builds. See http://blog.paranoidcoding.com/2016/04/05/deterministic-builds-in-roslyn.html and https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/PE-COFF.md

What you're seeing on .NET Core is that its project system enables `csc /deterministic` by default.
You can turn it off by specifying `<Deterministic>false</Deterministic>` in your .csproj if you really want the time stamp.

**Comment by qmfrederik** [comment]
@nguerrera OK - thanks for the explanation! Makes sense - `<Deterministic>false</Deterministic>` works in my case, so I'll stick with that at the moment.
