### ISSUE TITLE
Also include 'Visual Basic 2017' in the System.ValueTuple Package description.

### ISSUE THREAD

**Issue by KlausLoeffelmann** [dotnet/corefx#16974]
Visual Basic 2017 also got Tuple support.
In the description of the NuGet Package, only C#7 is mentioned.

It would be nice and helpful for the VB developers to include "Visual Basic 2017" in the description.

**Comment by karelz** [comment]
@jcouv can you please comment?

**Comment by jcouv** [comment]
I agree. That was an oversight.
I will need to confirm the proper name for this version of VB. Is it "VB 15" or "Visual Basic 2017" or another flavor.

![image](https://cloud.githubusercontent.com/assets/12466233/23807016/e43be908-0578-11e7-9eaa-5f0a05bbd66c.png)

**Comment by jcouv** [comment]
It looks like this was [already fixed](https://github.com/dotnet/corefx/pull/13916) to "Provides the System.ValueTuple structs, which implement the underlying types for tuples in C# and Visual Basic."

We will be refreshing the package on nuget next week (for mono support), so I expect this will be included.
I'll resolve the issue now, as duplicate (https://github.com/dotnet/corefx/pull/13916)

**Comment by jcouv** [comment]
Thanks @KlausLoeffelmann for bringing this issue up and helping make VS better :-)
