### ISSUE TITLE
The .editorconfig should be updated to support the code style options made available in VS2017

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#16972]
Currently we have a set of code style guidelines here: https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md.

However, we don't have a good way to enforce this (aside from manual code reviews and occasionally running https://github.com/dotnet/codeformatter) when users have their VS options configured away from the defaults.

VS2017 added support for specifying a majority of these options via the `.editorconfig` file:
* https://github.com/dotnet/roslyn/pull/15020
* https://github.com/dotnet/roslyn/pull/15029
* https://github.com/dotnet/roslyn/pull/15065

We should update the repositories `.editorconfig` to have a set of style options matching those specified in our coding-style documentation.

**Comment by karelz** [comment]
@tannergooding do you want to submit a PR?

**Comment by tannergooding** [comment]
I have a lot of various fixes I am tracking right now (both for dotnet repo's I actually work on and for dotnet repo's I actively contribute to).

I might get around to this eventually, but probably not within the next week.

**Comment by karelz** [comment]
Sounds good, it is up for grabs - if anyone wants it, please say so.
Complexity: Low

**Comment by cod7alex** [comment]
Hi,

I am willing to help with this, looks like a good thing for first PR.

**Comment by karelz** [comment]
@cod7alex great, let me know when you accept the invite, so that I can assign it to you ... (assigning to myself temporarily)

**Comment by cod7alex** [comment]
@karelz accepted

**Comment by karelz** [comment]
Thanks, assigned to you ...
