### ISSUE TITLE
Add more testing for FormatterServices.GetUninitializedObject

### ISSUE THREAD

**Issue by morganbr** [dotnet/corefx#16995]
We should expand testing for GetUninitializedObject to include:
* Running precise (non-BeforeFieldInit) constructors
* Pointer types
* ByRefs
* Arrays

**Comment by karelz** [comment]
@morganbr are you working on it?

**Comment by morganbr** [comment]
Not at the moment. I'm happy to have somebody else pick it up too.

**Comment by karelz** [comment]
In that case unassigning from you - see [triage rules](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified)

**Comment by hughbe** [comment]
grabbed in #17717

**Comment by karelz** [comment]
Assigned to you @hughbe, thanks!
