### ISSUE TITLE
Should we rename Span<T> to Memory<T> and Memory<T> to something else?

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#16997]
@terrajobst @KrzysztofCwalina

**Comment by jkotas** [comment]
Check the discussion in the linked CoreCLR issue.

**Comment by jkotas** [comment]
This needs to finalized for 2.0. I do not think we will be able to rename it after it.

**Comment by AlgorithmsAreCool** [comment]
Perhaps:
 `Span<T>` -> `Memory<T>` 
`Memory<T>` -> `MemoryRef<T>`

**Comment by KrzysztofCwalina** [comment]
I don't mind renaming Span to Memory (although I don't think the value of the rename is very large or any).
I definitely don't like renaming Memory to MemoryRef. MemoryRef sounds like some plumbing magic that should be avoided.

**Comment by AlgorithmsAreCool** [comment]
I had a notion today that perhaps `Block<T>` might be a decent name that is less overloaded than Span. Or of course `Buffer<T>`.

**Comment by ahsonkhan** [comment]
We have already renamed `Memory<T>` to `Buffer<T>` while keeping `Span<T>` as is. Shall we close this issue?
https://github.com/dotnet/corefxlab/blob/master/src/System.Buffers.Primitives/System/Buffers/Buffer.cs#L13

@KrzysztofCwalina, @shiftylogic
