### ISSUE TITLE
Some XPath.XDocument tests are failing

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#17]
Some XPath.XDocument queries have different results than other XPath navigators.
This might be an old behavior or newly introduced bug.

Failing tests:
build /p=IncludeTraits=ActiveIssue=17

**Comment by joshfree** [comment]
can you go through and resolve all of your old november/december 2014 issues this month?  these are starting to collect dust.

**Comment by MattWhilden** [comment]
Don't mind me too much, just bumping old items that are perhaps completed.

What's the state here @krwq?
