### ISSUE TITLE
Missing GetTypeFromProgID in Core 1.1?

### ISSUE THREAD

**Issue by jmroyb** [dotnet/corefx#17008]
Hi folks!

I'm building a netstandard 1.5 lib, but method .GetTypeFromProgID is missing. This code works fine in Framework 4.6.2:

`
            var t = Type.GetTypeFromProgID("VB6Interop.MyClass");         //missing GetTypeFromProgID
            var o = Activator.CreateInstance(t);
            var r = t.InvokeMember
                (
                    "MyMethod", 
                    System.Reflection.BindingFlags.InvokeMethod, null, o, 
                    new object[] { "", "" }
                );
`

Please can you tell me where is GetTypeFromProgID?

Thanks a lot!

**Comment by WernerMairl** [comment]
i hope for you that i'm wrong, but i think this function/feature is coming from COM/Ole directly depending and available on Windows ONLY, so probably it is not part of .Net Core (currently)

**Comment by svick** [comment]
[That method does not exist in .Net Standard 1.x, but it will be included in the upcoming .Net Standard 2.0.](https://apisof.net/catalog/System.Type.GetTypeFromProgID(String))

**Comment by jkotas** [comment]
@svick is right - it will be available in .NET Core 2.0. Check https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md if you would like to try nightly .NET Core 2.0 builds.

**Comment by jmroyb** [comment]
Thanks folks for your quick answer
