### ISSUE TITLE
Can't find XslTransform?

### ISSUE THREAD

**Issue by reneherrero** [dotnet/corefx#17015]
Hi,
I see the XslTransform in the source code here: https://github.com/dotnet/corefx/blob/b1865ea0847a7a86baefe8378b772ecf0b785681/src/System.Private.Xml/src/System/Xml/Xslt/XslTransform.cs

Has this shipped?  Is it included in some NuGet?

Thanks,

**Comment by svick** [comment]
[It will be included in .Net Core 2.0 and .Net Standard 2.0.](https://apisof.net/catalog/System.Xml.Xsl.XslTransform) If you want to try the latest prerelease version of that, follow [these instructions](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md).

**Comment by karelz** [comment]
Question seems to be answered, so closing ...

cc @sepidehMS @krwq

**Comment by reneherrero** [comment]
Yes, answered indeed.
Thanks guys!
