### ISSUE TITLE
Two TimeZoneTests failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#17028]
I assume today's DST change was a factor here.
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx_release_prtest/4421/
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/4428/
```
System.Tests.TimeZoneTests.TestRoundTripping [FAIL]
        Assert.Equal() Failure
        Expected: 2017-03-12T03:09:36.4716460-07:00
        Actual:   2017-03-12T04:09:36.4716460-07:00
        Stack Trace:
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Runtime/tests/TimeZoneTests.netstandard.cs(86,0): at System.Tests.TimeZoneTests.TestRoundTripping()
     System.Tests.TimeZoneTests.TestOffsetsAndDaylight [FAIL]
        Assert.Equal() Failure
        Expected: -07:00:00
        Actual:   -08:00:00
        Stack Trace:
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Runtime/tests/TimeZoneTests.netstandard.cs(67,0): at System.Tests.TimeZoneTests.TestOffsetsAndDaylight()
```

**Comment by danmosemsft** [comment]
Not the only ones hit by this. https://github.com/dotnet/corefx/issues/17036

**Comment by danmosemsft** [comment]
The first one at least is wrapped in `if (!TimeZoneInfo.Local.IsAmbiguousTime(now))` which apparently wasn't sufficient.
@tarekgh

**Comment by tarekgh** [comment]
we could have a bug here as I am expecting this code to work. I'll try to take a look

**Comment by tarekgh** [comment]
@stephentoub did we see these tests failing on OS's than OSX? I am asking because I couldn't repo it (at least on Windows so far)

**Comment by stephentoub** [comment]
I only saw it on macOS, but I assumed that was just a timing issue and that only the macOS legs ran in the magic window.

**Comment by tarekgh** [comment]
from the failure log the time around "2017-03-12T03:09:36.4716460-07:00" is not really special as we were already passed the daylight time switch by at least 6 or 7 hours. this is why I am wondering how I can repro this

**Comment by tarekgh** [comment]
sorry Ignore last comment I just added and removed it

**Comment by danmosemsft** [comment]
Actually, assuming I understand that API, `IsAmbiguousTime` wouldn't be relevant in this case, as when one springs forward, there is no ambiguous hour.

**Comment by tarekgh** [comment]
> Actually, assuming I understand that API, IsAmbiguousTime wouldn't be relevant in this case, as when one springs forward, there is no ambiguous hour.

that is right. this is why I said I expect this code to work.
