### ISSUE TITLE
Question: How do you calculate code coverage?

### ISSUE THREAD

**Issue by kimbell** [dotnet/corefx#17027]
With the release of Visual Studio 2017, my impression is that .NET Core Code Coverage isn't supported at the moment. Third party solutions such as Resharper doesn't provide a solution either.

This repo has some up for grab tasks that are related to code coverage. If someone from the community were to contribute to these tasks, how would they check that code coverage is increasing?

How has Microsoft set things up to get Code Coverage?

**Comment by stephentoub** [comment]
@kimbell, thanks for your interest in contributing.  Our code coverage solution is described here:
https://github.com/dotnet/corefx/blob/master/Documentation/building/code-coverage.md#local-code-coverage-runs
We'd welcome additional tests to improve things.  The most recent report (typically run daily) is available linked from the code coverage badge on the repo's home page:
https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/Code_Coverage_Report/
