### ISSUE TITLE
Is there any plan or roadmap to add the .net core and .net standard to VB.NET 

### ISSUE THREAD

**Issue by sarah17wu** [dotnet/corefx#17021]
Now in VS 2017, we can only create C# projects with .NET Core and .NET Standard, when the VB.NET will supported with .NET Core and .NET Standard.

**Comment by karelz** [comment]
@terrajobst?

**Comment by tarekgh** [comment]
Issue moved to [dotnet/sdk #984](https://github.com/dotnet/sdk/issues/984) via [**ZenHub**](https://www.zenhub.com/)

**Comment by karelz** [comment]
@tarekgh does it mean it is "just" limitation in the templates? (i.e. SDK)

**Comment by tarekgh** [comment]
I am seeing this the tool chain to create VB.NET app which mainly is VB compiler and the targets to build it. I am not seeing we'll have any changes in the library or the runtime side.

**Comment by karelz** [comment]
Fair, let's hope we don't need any changes to Microsoft.VisualBasic then.
