### ISSUE TITLE
System.Tests.GetEnvironmentVariable.EnumerateEnvironmentVariables failed in CI

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#17037]
Configuration: OuterLoop_Windows10_release ([build#126](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_release/126/testReport/))

Failed test: System.Tests.GetEnvironmentVariable.EnumerateEnvironmentVariables

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_release/126/consoleText

Message: 
~~~
System.Tests.GetEnvironmentVariable.EnumerateEnvironmentVariables(target: User) [FAIL]
        System.IO.IOException : No more data is available.
~~~

Stack Trace:
~~~
at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
              at Microsoft.Win32.RegistryKey.GetValueNames()
              at System.Environment.GetEnvironmentVariablesCore(EnvironmentVariableTarget target)
           D:\j\workspace\outerloop_win---6835b088\src\System.Runtime.Extensions\tests\System\Environment.GetEnvironmentVariable.cs(243,0): at System.Tests.GetEnvironmentVariable.EnumerateEnvironmentVariables(EnvironmentVariableTarget target)
~~~

**Comment by danmosemsft** [comment]
@JeremyKuhne PTAL. Different to https://github.com/dotnet/corefx/issues/16961

**Comment by JeremyKuhne** [comment]
Hmm- this one is interesting. Pulling directly from the registry in this case. Possibly no entries for the current user? Need to look up which error that message is in winerror.h.

**Comment by danmosemsft** [comment]
@JeremyKuhne the code does RegQueryInfoKey to get the number of values in the key. Then it calls RegEnumValue passing it indexes until it reaches the number of values it got earlier. If the number of values has been reduced during enumeration then RegEnumValue returns ERROR_NO_MORE_ITEMS according to MSDN.

Perhaps an environment variable was just cleared between the two function calls. I suggest just breaking out of GetValueNamesCore(int) when this error code is hit -- trimming the char[] array down to remove the value names it never got.

**Comment by danmosemsft** [comment]
I see this code was just copied from Desktop.

**Comment by danmosemsft** [comment]
@Jiayili1 if someone on your team would like to make an actual product code bug fix, this one could be a good one to start with. Optional - only if you have time and are interested.

**Comment by Jiayili1** [comment]
@danmosemsft We'd like to do it, but now I don't know how to change the code. Could you do me a favor?

**Comment by danmosemsft** [comment]
OK, hold on this one then until I have time to make a note or do it. thanks.

**Comment by danmosemsft** [comment]
Whoever fixes this, should use the debugger to confirm my theory before submitting the fix.

**Comment by Jiayili1** [comment]
Failed again here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_release/141/testReport/System.Tests/GetEnvironmentVariable/EnumerateEnvironmentVariables_target__Machine_/

**Comment by JeremyKuhne** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/10711.
