### ISSUE TITLE
System.Data.SqlClient package not updated for 1.1.1 release

### ISSUE THREAD

**Issue by apboyle** [dotnet/corefx#17039]
PR #15431 was listed in the release notes for [.NET Core 1.1.1](https://github.com/dotnet/core/blob/master/release-notes/1.1/1.1.1.md).
However, there was no new System.Data.SqlClient package so the fix has not been released.

Will this package be updated with the next servicing release?

**Comment by karelz** [comment]
@saurabh500 can you please comment? Is there any reason why we didn't ship the SqlClient package in 1.1.1?
cc @leecow

**Comment by saurabh500** [comment]
1.1.1 was supposed to have an updated Sqlclient package. That's why we made changes to the release/1.1 branch

**Comment by karelz** [comment]
Can you confirm that the package was not published? Maybe we need to republish it? @leecow should be able to help.

**Comment by paalmoest** [comment]
Any news on this ? @karelz @leecow

**Comment by karelz** [comment]
@saurabh500 was digging into it ...

**Comment by paalmoest** [comment]
I can confirm that connection leak is stil present in the microsoft/dotnet:1.1.1-sdk  @saurabh500

**Comment by paalmoest** [comment]
@saurabh500 Bump :)

**Comment by saurabh500** [comment]
@paalmoest The updated SqlClient with the connection leak fix, did not make it into the 1.1.1 release. 
I have opened a PR to rectify it.
https://github.com/dotnet/corefx/pull/17635

**Comment by paalmoest** [comment]
@saurabh500 Thats awesome ! It`s blocking our move to a dockerized .net core platform at the mooment.

**Comment by saurabh500** [comment]
New package is available at https://www.nuget.org/packages/System.Data.SqlClient/4.3.1
