### ISSUE TITLE
MemberInfo.HasSameMetadataDefinitionAs should capture the logic common to all Reflection providers

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#17048]
This is in support of the just approved api `HasSameMetadataDefinitionAs` in #5884

This api has a number of edge cases (constructed types and method instantiations.). These edge cases can mostly be implemented portably. Given that, it would be nice of MemberInfo itself could implement the portable portion, leaving the simplified task for the underlying Reflection provider. This would reduce the amount of implementation underlying Reflection providers have to do and promote more consistent behavior.

**Proposal for New API:** `MemberInfo.HasSameMetadataDefinitionAsImpl.`
```c#
        protected virtual bool HasSameMetadataDefinitionAsImpl(MemberInfo other)
        {
            throw new NotImplementedException();
        }
```

This would be an extension point for Reflection providers to implement the "non-portable" portion of HasSameMetadataDefinitionAs() on non-constructed entities.

The specification of `HasSameMetadataDefinitionAsImpl` would be as follows:

Return true if and on if <b>this</b> and <b>other</b>...
        
- Have the same MemberType value (i.e. both are methods or both are fields, etc.)
- Are implemented by the same Reflection provider.
- Represents the same metadata entity (e.g disregarding artifacts such as ReflectedType.)
        
Behavior undefined if:
- other is null
- this or other is a MethodInfo that represents a constructed generic method (e.g. the result of MethodInfo.MakeGenericMethod()
- this or other is a Type that isn't one of

     - a plain old named type (i.e. HasElementType == false && IsConstructedGenericType == false)
     - a generic type parameter (i.e. IsGenericParameter == true)

The implementation of MemberInfo.HasSameMetadataDefinitionAs() can then be this:

```c#
        public virtual bool HasSameMetadataDefinitionAs(MemberInfo other)
        {
            if (other == null)
                throw new ArgumentNullException(nameof(other));

            MemberInfo thisMember = Distill(this);
            MemberInfo otherMember = Distill(other);
            return thisMember.HasSameMetadataDefinitionAsImpl(otherMember);
        }

        private MemberInfo Distill(MemberInfo member)
        {
            switch (member)
            {
                case MethodInfo method:
                    if (method.IsGenericMethod && !method.IsGenericMethodDefinition)
                        method = method.GetGenericMethodDefinition();
                    return method;

                case Type type:
                    {
                        while (type.HasElementType)
                        {
                            type = type.GetElementType();
                        }
                        if (type.IsConstructedGenericType)
                            type = type.GetGenericTypeDefinition();
                        return type;
                    }
                default:
                    return member;
            }
        }
```

Note that `HasSameMetadataDefinitionAs` is still virtual, allowing providers to replace it entirely if they can provide a more performant version than the default. The default definition, however, still defines the required behavior.

**Comment by karelz** [comment]
@AtsushiKan do you plan it as protected or public method?
If it is protected, do we expect customers to inherit, or is it mostly for our own purposes (portability across CoreCLR, CoreRT, etc.)?

**Comment by AtsushiKan** [comment]
protected.

This is for customers that implement Reflection systems using Type as an abstract base type.

CoreCLR and CoreRT and keeping them in sync is certainly one (and the most immediate) use case for this.

However, third parties that implement their own Reflection subsystems (e.g. the oft-proposed TypeInfo over S.R.Metadata) would also benefit from being able to override the protected Impl() method rather than the public api.

**Comment by karelz** [comment]
Does anyone outside CoreFX repo truly implement their own Reflection subsystem?
If it is scoped to CoreFX repo, I would say we do not need API review ... (we can double-check in next meeting)

Of course, keep in mind that System.Reflection.Metadata targets also Desktop, so they might not be able to use the new API as it is not available everywhere. However, if it helps CoreCLR & CoreRT, let's just do it ...

**Comment by AtsushiKan** [comment]
User-extensibility of Reflection types is a feature and we have prior examples such as LMR.

System.Reflection.Metadata would not be using the api - TypeInfo over SRM would likely be a new assembly (that uses System.Reflection.Metadata.)

**Comment by karelz** [comment]
Fair, thanks for background info.

**Comment by karelz** [comment]
Somewhat similar to #5884

**Comment by terrajobst** [comment]
@AtsushiKan, is your design complete? It seems it's quite involved and we need to talk about this, so we can ask questions in order to fully understand the goals. Could we do this next Tuesday?

**Comment by AtsushiKan** [comment]
@terrajobst  While I'd personally be ok with the design as stated, there's plenty of wriggle room in spec'ing out this api, especially when it comes to the edge cases. (And yes, I half-expected this proposal would be a forcing function to have that discussion.)

So yes, let's indeed discuss further next Tuesday.

**Comment by AtsushiKan** [comment]
Pulling back on this fow now.
