### ISSUE TITLE
Verify that tests projects are configured to run on all possible platforms

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#17058]
I believe at the minimum, these test projects should be run on all platforms:

src/System.IO.FileSystem.DriveInfo/tests/Configurations.props
src/System.Net.WebHeaderCollection/tests/Configurations.props
src/System.Security.Cryptography.Primitives/tests/Configurations.props
src/System.Text.Encoding.CodePages/tests/Configurations.props

We should compare the test results from a Windows and Linux run and make sure there are no other unnecessary test gaps.

**Comment by mellinoe** [comment]
Here is a list of differences I've identified, by running `build.cmd/sh && build-tests.cmd/sh` and then searching for "testResults.xml" files. All of these projects only run on Windows:

```
Microsoft.Win32.Registry.AccessControl.Tests
Microsoft.Win32.Registry.Tests
System.IO.FileSystem.AccessControl.Tests
System.IO.Pipes.AccessControl.Tests
System.IO.Ports.Tests
System.Net.Http.WinHttpHandler.Functional.Tests
System.Net.Http.WinHttpHandler.Unit.Tests
System.Private.Uri.Functional.Tests
System.Security.AccessControl.Tests
System.Security.Cryptography.Cng.Tests
System.Security.Cryptography.Csp.Tests
System.Security.Cryptography.Pkcs.Tests
System.Security.Cryptography.ProtectedData.Tests
System.Security.Principal.Windows.Tests
System.ServiceProcess.ServiceController.Tests
System.Threading.AccessControl.Tests
System.Threading.Overlapped.Tests
```

(I've filtered out the four above because https://github.com/dotnet/corefx/pull/17059 will fix them).

Many of these look Windows-specific. System.Private.Uri.Functional.Tests should probably be run everywhere; it is just missing a Configurations.props file.

**Comment by mellinoe** [comment]
@bartonjs Should any of the Crypto tests above run outside of Windows? I'm not sure which are Windows-specific by design.

**Comment by danmosemsft** [comment]
Thank you for doing this @mellinoe I had just done the same analysis and was about to open an issue. My list is the same.

**Comment by bartonjs** [comment]
I don't think we want to make the CNG types work on Linux by magic (@danmosemsft?), so Cng.Tests should be Windows-only.
Csp.Tests is tracked by https://github.com/dotnet/corefx/issues/16585
Pkcs.Tests is tracked by https://github.com/dotnet/corefx/issues/3334
ProtectedData is explictly not supported on !Windows, so should probably be Windows-only.

**Comment by danmosemsft** [comment]
Whether to remove CNG from netstandard since they aren't impl in Unix is tracked by https://github.com/dotnet/standard/issues/235

**Comment by mellinoe** [comment]
I'm assuming all "AccessControl" assemblies are not supported by-design.

Registry: not supported by design

System.IO.Ports: Still coming online, doesn't work outside Windows

Crypto: Not supported by design

System.ServiceProcess.ServiceController: Not supported by design

System.Threading.Overlapped: Not supported by design

I fixed System.Private.Uri, so everything on this list should be accounted for now.

**Comment by weshaggard** [comment]
Thanks for digging into these @mellinoe. The changes you made look correct to me.
