### ISSUE TITLE
Make Sg.exe Parse Attributes Using Reflection

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#17055]
Sg.exe needs to convert CustomAttributeData to actual attribute objects. We currently have to write methods for each attribute for the conversion. Sg.exe would fail to parse an attribute if we didn't add such method for that attribute type. It would be great if Sg.exe can parse attributes using reflection so that we won't have to add such method for individual attribute types anymore.

**Comment by karelz** [comment]
@shmao 2.1 or Future milestone?

**Comment by shmao** [comment]
The fix for sg.exe has been checked in.
