### ISSUE TITLE
Release notes for packages

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/corefx#1706]
I just saw that [System.Collections.Immutable](https://github.com/dotnet/corefx/releases/tag/System.Collections.Immutable-1.1.36) and [System.Reflection.Metadata](https://github.com/dotnet/corefx/releases/tag/System.Reflection.Metadata-1.0.21) were tagged by @nguerrera.

The releases page on github has links to release notes on the msdn blog:

- http://blogs.msdn.com/b/bclteam/p/immutable.aspx
- http://blogs.msdn.com/b/bclteam/p/metadata.aspx

Is this how release notes are planned to be done in the future as well? Or can we put the release notes as Markdown on github?

**Comment by nguerrera** [comment]
I definitely think we can put them as markdown on GitHub. I was just linking to where things currently go, which predates this repo.

**Comment by akoeplinger** [comment]
Yeah, I suspected that, thanks for confirming :)

http://keepachangelog.com has a few good tips as well.

**Comment by nguerrera** [comment]
cc @terrajobst @richlander

**Comment by joshfree** [comment]
@leecow is recording release notes in markdown @ https://github.com/dotnet/core/tree/master/release-notes/.  Let us know what you think.

**Comment by akoeplinger** [comment]
Looks great! I also saw that you're linking them from the GitHub tag: https://github.com/dotnet/corefx/releases/tag/v1.0.0-rc2 :+1: 

The only other suggestion I'd have is adding the link to the releaseNotes tag into the nuspec for the packages as well, so they show up on nuget.org.

**Comment by joshfree** [comment]
> adding the link to the releaseNotes tag into the nuspec

@ericstj is this something you could improve before we fork for RTM?

**Comment by joshfree** [comment]
Thanks @akoeplinger!  I moved the other suggestion to a new issue for better tracking.
