### ISSUE TITLE
Exposing Windows.Foundation.UniversalApiContract as NuGet package

### ISSUE THREAD

**Issue by Reza1024** [dotnet/corefx#17071]
Hi,

I am trying to create a netcore library to be consumed in a Windows 10 app (UAP)
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform" Version="5.3.1" />
  </ItemGroup>
</Project>
```
But a big part of the API is not present in `Microsoft.NETCore.UniversalWindowsPlatform` and instead they are some contracts (`Windows.Foundation.UniversalApiContract`, ...) which cannot be added as a reference to the project. So none of the [UWP Apis](https://docs.microsoft.com/en-us/uwp/api/) can be consumed. It seems that these apis are internally available as [target packing](https://github.com/dotnet/corefx/blob/ac67ffac987d0c27236c4a6cf1255c2bcbc7fe7d/src/System.Runtime.WindowsRuntime/src/project.json#L12). Should not these apis be exposed externally as a nuget package so we could do:
```xml
<PackageReference Include="Windows.Foundation.UniversalApiContract" Version="[SDK Version]" />
```

**Comment by Reza1024** [comment]
[sdk](https://github.com/dotnet/sdk) repo is propbably more appropriate for this issue, moved it there: https://github.com/dotnet/sdk/issues/986

**Comment by ViktorHofer** [comment]
Hey there. Currently you cannot consume a netcoreapp library from UAP. Creating a .NET Standard >= 1.4 library which you can reference from UAP is possible. See version table here: https://docs.microsoft.com/en-us/dotnet/articles/standard/library

To build against the UniversalApiContract you need to create a UAP library (e.g. template inside Visual Studio) and set the minimum and default Windows 10 SDK version. The contracts are part of the Windows 10 SDK.
