### ISSUE TITLE
StringBuilder's indexer throws different exceptions for get & set

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#17075]
```cs
        [IndexerName("Chars")]
        public char this[int index]
        {
            get
            {
                StringBuilder chunk = this;
                for (;;)
                {
                    int indexInBlock = index - chunk.m_ChunkOffset;
                    if (indexInBlock >= 0)
                    {
                        if (indexInBlock >= chunk.m_ChunkLength)
                        {
                            throw new IndexOutOfRangeException();
                        }
                        return chunk.m_ChunkChars[indexInBlock];
                    }
                    chunk = chunk.m_ChunkPrevious;
                    if (chunk == null)
                    {
                        throw new IndexOutOfRangeException();
                    }
                }
            }
            set
            {
                StringBuilder chunk = this;
                for (;;)
                {
                    int indexInBlock = index - chunk.m_ChunkOffset;
                    if (indexInBlock >= 0)
                    {
                        if (indexInBlock >= chunk.m_ChunkLength)
                        {
                            throw new ArgumentOutOfRangeException(nameof(index), Environment.GetResourceString("ArgumentOutOfRange_Index"));
                        }
                        chunk.m_ChunkChars[indexInBlock] = value;
                        return;
                    }
                    chunk = chunk.m_ChunkPrevious;
                    if (chunk == null)
                    {
                        throw new ArgumentOutOfRangeException(nameof(index), Environment.GetResourceString("ArgumentOutOfRange_Index"));
                    }
                }
            }
        }
```

It throws an `IndexOutOfRangeException` with no parameter name for the getter, and an AOORE with `nameof(index)` for the setter. The latter exception seems superior because 1) it includes the parameter name, and 2) IOORE is only supposed to be used by arrays IIRC. Should we consider changing the getter to follow the setter?

**Comment by karelz** [comment]
What is the behavior on Desktop?

**Comment by jamesqo** [comment]
@karelz Presumably the same, I think it has been like this from the initial commit to coreclr.

**Comment by hughbe** [comment]
https://github.com/Microsoft/referencesource/blob/master/mscorlib/system/text/stringbuilder.cs#L515

**Comment by hughbe** [comment]
And tests exist for this here: https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/Text/StringBuilderTests.cs#L147

**Comment by JonHanna** [comment]
> IOORE is only supposed to be used by arrays IIRC.

There are other indexers that throw IOORE and the documentation certainly suggests it should be used in such cases. I'd consider it superior to AOORE in such cases where it not that those which throw AOORE are more numerous, and hence probably the one to go for.

Throwing one sometimes and the other other times is definitely unfortunate though, it's also quite possibly what someone has a dependency on.

**Comment by AlexGhiondea** [comment]
I am in favor in keeping this behavior as-is so that it matches what we have in Desktop. It is unfortunate that we were not consistent, but I am not sure the advantage of fixing this outweighs the compat risk.
