### ISSUE TITLE
Add tests to increase code coverage for Span<T> APIs

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#17078]
Here is a snapshot of the coverage:
![image](https://cloud.githubusercontent.com/assets/6527137/23919318/a410e1e2-08b3-11e7-8710-172522e8ebc6.png)

Currently, SpanHelpers, specifically SpanHelpers.Clear.cs needs tests.
https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/Code_Coverage_Report/System.Memory_SpanHelpers.htm

**Comment by ahsonkhan** [comment]
cc @KrzysztofCwalina, @shiftylogic 
Why is the CI showing low (zero) test coverage for Span.Clear?
Specifically, here it shows 0 code coverage. https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/Code_Coverage_Report/System.Memory_SpanHelpers.htm#Djworkspacecode_coverageb14a30e5srcSystemMemorysrcSystemSpanHelpersClearcs

But we have extensive Span.Clear tests (which get discovered and run/pass locally):
https://github.com/dotnet/corefx/blob/master/src/System.Memory/tests/Span/Clear.cs#L9

The tests also run in CI:
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/5033/testReport/System.SpanTests/SpanTests/

**Comment by shiftylogic** [comment]
Until yesterday, I'm pretty sure those tests were never running against slow Span. I added netfx to the test configuration, but we might need to add more.

**Comment by shiftylogic** [comment]
FYI, if you run code coverage locally against System.Memory using the netfx framework, the numbers look much better.

![image](https://cloud.githubusercontent.com/assets/11233697/24257140/3c228cf2-0fa7-11e7-9e74-e927f0f1ce8a.png)

**Comment by ahsonkhan** [comment]
Code Coverage

**SlowSpan:**
![image](https://cloud.githubusercontent.com/assets/6527137/24310184/2364ae58-108c-11e7-90b7-a99073acc14a.png)

**FastSpan:**
![image](https://cloud.githubusercontent.com/assets/6527137/24310198/34eacb6c-108c-11e7-900e-8800199783dd.png)

**Comment by ahsonkhan** [comment]
**System.Private.Corelib Code Coverage (for Span):**
![image](https://cloud.githubusercontent.com/assets/6527137/24312806/831fccbe-1097-11e7-903e-af77748dddd7.png)
![image](https://cloud.githubusercontent.com/assets/6527137/24312819/9634dc2c-1097-11e7-90cb-5af3f19f5d22.png)
