### ISSUE TITLE
Matrix4x4 perspective helper methods do not handle farPlaneDistance = float.PositiveInfinity

### ISSUE THREAD

**Issue by jesperll** [dotnet/corefx#17089]
All Matrix4x4.CreatePerspective* methods are affected 

If you pass in float.PositiveInfinity as farPlaneDistance the resulting matrix is invalid:
M33 and M43 are both float.NaN
They should be -1 and -nearPlaneDistance respectively

As a workaround you can use float.MaxValue instead but I think float.PositiveInfinity should create a valid projection matrix as well.

**Comment by mellinoe** [comment]
I don't think I have seen a matrix implementation which allows for this special case. All other implementations of a 4x4 matrix exhibit the same behavior as this, meaning `float.PositiveInfinity` is not a valid distance for the far plane. My immediate recommendation would be to create your own specialized factory method which has the semantics you would like, but we can discuss whether you think that is a valid option.

@shawnhar Do you have any particular thoughts on this?

**Comment by shawnhar** [comment]
I don't have a strong opinion on this.  There are some use cases for projection matrices with infinite far clip plane (notably in stencil shadow rendering) but this is definitely a corner case and not something that I see widely supported in other matrix implementations.  On the other hand the change seems benign, and this isn't a performance sensitive path so the extra conditionals aren't a big deal to carry around.

**Comment by mellinoe** [comment]
I would agree that the only downside is the "overhead" of the extra conditional, but that hardly matters given how often these functions are generally used. The fact that `float.MaxValue` is a direct replacement for this scenario, and the fact that no other libraries allow this, gives me a little pause. At the same time, it would be nice to remove one extra "corner case" for consumers to worry about, and just have things work as expected.

**Comment by jesperll** [comment]
WPF's [PerspectiveCamera](https://referencesource.microsoft.com/#PresentationCore/Core/CSharp/System/Windows/Media3D/PerspectiveCamera.cs,89) handles positive infinity if that's prior art enough ;) 

I'm porting some WPF specific rendering code to a cross-platform library and came across this edge case.
