### ISSUE TITLE
Proposal: Add Result property to non generic Task.

### ISSUE THREAD

**Issue by dmitriyse** [dotnet/corefx#17094]
Suppose you have some method:
```CSharp
public async Task<T> GetMyStructure<T>(string someParam)
{
....
}


//Suppose you need to pass result of this method to some non-generic routine
// await MySample(GetMyStructure<T>("structure1");
public async void MySample(Task getMyStructureTask)
{
     // Currently it's impossible.
     object result = await getMyStructureTask;

     // We can only get it through reflection
     await getMyStructureTask;
     result = task.GetType().GetTypeInfo().GetDeclaredProperty("Result")?.GetValue(task);

     // Do something with result.
     Console.WriteLine(result?.ToString());
}
```

**Comment by dmitriyse** [comment]
or we can introduce some contract that is useful in many other places:
```CSharp
public interface IObjectHandle<out T>
{
    T Target {get;}
}

public class Task<T>: IObjectHandle<T>
{
     T IObjectHandle<T>.Target
     {
          get 
          { 
               return this.Result;
          }
      }
}


// In this case we will get:
public async void MySample(Task getMyStructureTask)
{
     // Currently it's impossible.
     object result = await getMyStructureTask;

     // We can only get it through reflection
     await getMyStructureTask;
     result =((IObjectHandle<object>)Task).Target;

     // Do something with result.
     Console.WriteLine(result?.ToString());
}
```

**Comment by JonHanna** [comment]
What should it do with a `Task` that doesn't have a result (the sort of operation that would be `void` if not async?)

Why not just make `MySample` generic?

**Comment by dmitriyse** [comment]
1) Making MySample generic sometimes impossible. Generics is a virus - all path of instance traveling should be generic. For example why WPF was not implemented all in Generics - the answer is too heavy code (places with 10+ generic arguments).

2) Task.Result for Task (with out result) will always return null and it's no problem.

**Comment by stephentoub** [comment]
> it's no problem.

It is a problem.  It suggests that all non-generic tasks have results, and they don't.  There's also no way to differentiate null as a valid result from null meaning the Task doesn't have one. Further, this could have a perf impact, as Task doesn't store the result, rather the derived `Task<TResult>` does; that means that either the field would need to be moved down to Task, in which case it would bloat all non-generic tasks and would cause value type results to be boxed, or virtual calls would need to be introduced (and value type results would then be boxed when returning them out of the object Result property).

I appreciate the suggestion, but I do not believe we should add such a member.

**Comment by dmitriyse** [comment]
Please pay attention to my second post in this thread. This problem can be solved.

**Comment by svick** [comment]
@dmitriyse What are the "many other places" where `IObjectHandle<T>` could be used? Without those, I think the interface should be named `ITask<T>`, as proposed in https://github.com/dotnet/roslyn/issues/2981 (though the proposal does not belong in the roslyn repo, it belongs here) and [on UserVoice](https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/5754247-make-task-t-implement-covariant-interface-itask-o) (by me).

Also note that it wouldn't solve the problem completely, since you still couldn't cast e.g. `Task<int>` to `ITask<object>` (because variance doesn't work on value types).

**Comment by karelz** [comment]
@dmitriyse for future new API proposals please follow [API proposal process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md) (esp. the example).

**Comment by dmitriyse** [comment]
Ok, thanks. I will inspect this guide.

**Comment by groege** [comment]
Wouldn't this be solved with wildcard generics like '?' in java?
So like: Task<?> or Task<any> -> if this would work the problem would be solved.

So rather than asking for a non-generic task with a result, i'd ask for generic wildcards ;)

**Comment by stephentoub** [comment]
Thank you for the suggestion, but for the reasons I previously highlighted, we're not going to proceed with this proposal.
