### ISSUE TITLE
Improve test coverage of UnmanagedMemoryStream

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefx#1711]
The tests for UnmanagedMemoryStream have several TODOs to add tests for:
- different offsets and lengths
- WriteAsync, Timeout, Flush, CopyTo

It would be great to add these tests and remove all TODOs.

**Comment by stephentoub** [comment]
#1721 is adding coverage for CopyTo.  I've grabbed the rest and will send a PR shortly.
