### ISSUE TITLE
Win32 registry types missing a couple methods that are present on Desktop 

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#17128]
These should either be implemented, since we cannot add members OOB, or else (low priority) throw PNSE().

Usage of Registry.DynData is very low (~0.1%) and RegistryHive.DynData basically zero. 
```
MembersMustExist : Member 'Microsoft.Win32.RegistryHive Microsoft.Win32.RegistryHive.DynData' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'Microsoft.Win32.RegistryKey Microsoft.Win32.Registry.DynData' does not exist in the implementation but it does exist in the contract.
```

https://github.com/dotnet/corefx/blob/master/src/shims/ApiCompatBaseline.netcoreapp.netfx461.txt

**Comment by stephentoub** [comment]
> Usage of Registry.DynData is very low 

I would expect so, given this Obsolete message :smile:
```
[Obsolete("The DynData registry key only works on Win9x, which is no longer supported by the CLR.  On NT-based operating systems, use the PerformanceData registry key instead.")]
```

**Comment by danmosemsft** [comment]
Ha, I didn't see that. MSDN just says it always throws ObjectDisposedException so adding it would not be difficult.

For reference the impl was removed here https://github.com/dotnet/coreclr/pull/5724/commits/68e668e753b6596c2a9e550fe4f824809a8e1c22

@weshaggard happy to ignore this one?

**Comment by weshaggard** [comment]
We explicitly made the decision to not bring these back when we did the other registry API bring back which I still believe we shouldn't do as we don't support win9x any longer.

**Comment by weshaggard** [comment]
For reference see conversation at https://github.com/dotnet/corefx/issues/15332. Closing this one.
