### ISSUE TITLE
Missing ncrypt.dll with AWS Lambda

### ISSUE THREAD

**Issue by ianByrne** [dotnet/corefx#17123]
Honestly, I have no idea if this is the correct place to ask this, so one thousand apologies if it is not - this GitHub repo is the only thing I can find that is in any way related to my error.

I am having troubles authing to the Google API from an AWS Lambda function. When trying to create a GoogleCredential, the following exception is thrown:
> The type initializer for 'System.Security.Cryptography.CngKeyLite' threw an exception.
> at System.Security.Cryptography.CngKeyLite.ImportKeyBlob(String blobType, Byte[] keyBlob)
> at System.Security.Cryptography.RSAImplementation.RSACng.ImportKeyBlob(Byte[] rsaBlob, Boolean includePrivate)
> at System.Security.Cryptography.RSAImplementation.RSACng.ImportParameters(RSAParameters parameters)
> at Google.Apis.Auth.OAuth2.ServiceAccountCredential.Initializer.FromPrivateKey(String privateKey)
> at Google.Apis.Auth.OAuth2.DefaultCredentialProvider.CreateServiceAccountCredentialFromParameters(JsonCredentialParameters credentialParameters)
> at Google.Apis.Auth.OAuth2.DefaultCredentialProvider.CreateDefaultCredentialFromParameters(JsonCredentialParameters credentialParameters)
> at AlexaProjLib.GoogleSheet.Connect()
> at AlexaProj.Function.FunctionHandler(SkillRequest input, ILambdaContext context)

The inner exception lists a missing DLL:
>Unable to load DLL 'ncrypt.dll': The specified module could not be found.

This is the code that throws it:
`var credential = GoogleCredential.FromJson(_googleSecret).CreateScoped(_scopes);`

Is there a reference/package that I'm missing?
**System.Security.Cryptography.CngKeyLite** doesn't exist on NuGet
**Microsoft.Private.CoreFx.NETCoreApp** creates package restore issues
**Microsoft.NETCore.Runtime.CoreCLR** doesn't fix the missing DLL error

**Comment by mellinoe** [comment]
@bartonjs 

What operating system does this run on? "ncrypt.dll" is a Windows binary, so it should be present assuming you are running on Windows. It's possible that the code path you are attempting will only work on Windows, and you may need to use a different one on Linux/OSX. I'm not familiar with this Google library, so I can't say for sure about that.

**Comment by bartonjs** [comment]
Yeah, it looks like Google's OAuth2 is calling into RSACng directly, but that's a type that only works on Windows.

You'll need to raise an issue with Google's library.  Theythey should be using `RSA.Create()` instead of picking an implementation (at least on .NET Core.  If they want to use RSACng when they're on .NET Framework (or generally when on Windows) that's a fine choice to make).

**Comment by ianByrne** [comment]
Fantastic, thanks for the tip. I'll log an issue with them.

**Comment by ianByrne** [comment]
I've now resolved this issue for my project by using **dotnet lambda package**. More details [here](http://stackoverflow.com/questions/42868476/aws-lambda-and-net-core-using-a-linux-runtime/42874741#42874741), if anyone else has the same problem.
