### ISSUE TITLE
CodeDOM.Compiler missing 4 members

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#17129]
These four members exist on Desktop but not on .NET Core. We have a stub definition of Evidence, so we should implement stub definitions of these so that code that uses them does not fail merely because the method is missing which they may not even care about.

```
MembersMustExist : Member 'System.CodeDom.Compiler.CompilerParameters.Evidence.get()' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.CodeDom.Compiler.CompilerParameters.Evidence.set(System.Security.Policy.Evidence)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.CodeDom.Compiler.CompilerResults.Evidence.get()' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.CodeDom.Compiler.CompilerResults.Evidence.set(System.Security.Policy.Evidence)' does not exist in the implementation but it does exist in the contract
```

**Comment by stephentoub** [comment]
That would mean adding a dependency on System.Security.Permissions.dll. Haven't we been actively avoiding that?

**Comment by danmosemsft** [comment]
I think nothing in this System.CodeDom library is part of NS2.0. So it would be legal to add such a dependency, and a matter of choice whether we want to. Since their usage is zero or close to it it's probably not worth it so we can close this.
@weshaggard

**Comment by weshaggard** [comment]
I wouldn't add the dependency just for those members.
