### ISSUE TITLE
[Netfx compat]: CodeNamespaceImportCollection in desktop uses ArrayList as its data collection.

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#17130]
`CodeNamespaceImportCollection` in desktop uses `ArrayList` as its data collection and in core we use `List<CodeNamespaceImport>` which brings difference in behavior when using its APIs, such as different exception types. 

cc:  @tarekgh @ianhays

**Comment by tarekgh** [comment]
we can change the documentation if needed. looks the desktop behavior is better as can distinguish the invalid cast failure from other failures.

**Comment by safern** [comment]
What I'm looking is that it doesn't always throws `InvalidCastException` in desktop, I'm trying to identify the cases.

**Comment by safern** [comment]
But an `ArgumentException` also makes sense because you're passing and invalid argument as the array you are trying to copy to the destination has a value of a different type than the destination array.

**Comment by tarekgh** [comment]
> But an ArgumentException also makes sense because you're passing and invalid argument as the array you are trying to copy to the destination has a value of a different type than the destination array.

right, but we have cases we throw like ArgumentNullException when passing null argument. someone may claim ArgumentException could be right for null too. The same example apply for other cases like out of range exception for instance.

I don't have strong opinion as ArgumentException is correct too but I prefer for casting failure returning specific exception about the problem.

**Comment by safern** [comment]
Well yeah, you are right there! Then we should make it throw `InvalidCastException` for all the cases in Core and Desktop.

**Comment by JonHanna** [comment]
> but we have cases we throw like ArgumentNullException when passing null argument. someone may claim ArgumentException

If I've read the docs and done a `catch(ArgumentException)` then I'll catch that fine due to inheritance, but not `InvalidCastException`

**Comment by tarekgh** [comment]
> If I've read the docs and done a catch(ArgumentException) then I'll catch that fine due to inheritance, but not InvalidCastException

that is good point too. as I mentioned I don't have strong opinion. just want to differentiate if someone interested in catching cast exception case.

**Comment by JonHanna** [comment]
Which implementation(s) of the interface is differing?

**Comment by safern** [comment]
> Which implementation(s) of the interface is differing?

The one that I've found is `ArrayList.CopyTo()` which uses `Array.Copy`, and I've found the real difference. 

I've found this in `CodeNamespaceImportCollection` which in desktop uses an `ArrayList` to store its data and in Core we changed it to use `List<CodeNamespaceImport>` so if we create a `CodeNamespaceImportCollection` and try to use `CopyTo` passing a destination array with different element type it would throw a different exception. 

So will update the title and issue to mention that it is `ArrayList` specifically.

**Comment by safern** [comment]
Sorry actually the difference in behavior is in `CodeNamespaceImportCollection` not in `ArrayList`.

**Comment by stephentoub** [comment]
If there's a visible difference in behavior stemming from using List instead of Array list, should we just switch back to using ArrayList?

**Comment by safern** [comment]
I think we should probably switch back, I don't know why we change to use List (maybe performance or availability at the time we ported this type). We should consider this for 2.0 as it could be a potential breaking change in compatibility e.g: 

* differences in exceptions thrown in `Collection.CopyTo`. 
* When `Enumerable.Current` is at the end and elements are added to the collection afterwards in `ArrayList` it throws an `InvalidOperationException` and when using `List` it doesn't throw and returns it as `null`.

I will disable the tests on Desktop that encounter this issue so that they stop failing.

Adding @Priya91 as she is the owner in this area.

**Comment by stephentoub** [comment]
> I don't know why we change to use List

When I ported CodeDom to corefx, I changed it in response to PR feedback here;
https://github.com/stephentoub/corefx/commit/33ab56ac0d54b9f80cf0c572736822c6ffe20ce7
Since I broke it, I've put up a fix at #17151.
