### ISSUE TITLE
Missing AllowPartiallyTrustedCallers on ValueTuple

### ISSUE THREAD

**Issue by jcouv** [dotnet/corefx#17144]
Relates to https://github.com/dotnet/roslyn/issues/17783

The attribute is missing on both the `netstandard1.0` and `portable-net40+sl4+win8+wp8` targets.

```C#
// \\Mac\Home\Documents\Visual Studio 2017\Projects\DiscardClassification\DiscardClassification\bin\Debug\System.ValueTuple.dll
// System.ValueTuple, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

// Global type: <Module>
// Architecture: AnyCPU (64-bit preferred)
// Runtime: .NET 4.0

using System;
using System.Diagnostics;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;

[assembly: AssemblyVersion("4.0.1.0")]
[assembly: CLSCompliant(true)]
[assembly: Debuggable]
[assembly: AssemblyCompany("Microsoft Corporation")]
[assembly: AssemblyCopyright("© Microsoft Corporation.  All rights reserved.")]
[assembly: AssemblyDefaultAlias("System.ValueTuple")]
[assembly: AssemblyDescription("System.ValueTuple")]
[assembly: AssemblyFileVersion("4.6.24705.01")]
[assembly: AssemblyInformationalVersion("4.6.24705.01. Commit Hash: 4d1af962ca0fede10beb01d197367c2f90e92c97")]
[assembly: AssemblyMetadata(".NETFrameworkAssembly", "")]
[assembly: AssemblyMetadata("Serviceable", "True")]
[assembly: AssemblyProduct("Microsoft® .NET Framework")]
[assembly: AssemblyTitle("System.ValueTuple")]
[assembly: NeutralResourcesLanguage("en-US")]
[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
```

**Comment by karelz** [comment]
@terrajobst @weshaggard I guess we don't need API review for such change, do we?

**Comment by davidsh** [comment]
>@terrajobst @weshaggard I guess we don't need API review for such change, do we?

Perhaps not API review but security review needed.  Also they need to run secannotate tool on the 'netfx' binary for this package and verify 0 errors.

cc: @morganbr

**Comment by AlexGhiondea** [comment]
@jcouv is this something you are planning to work on?

**Comment by jcouv** [comment]
Yes, I plan to fix this. 
I wasn't sure if I should just assign the bug to myself or let it go through triage.

**Comment by karelz** [comment]
AFAIK ValueTuple is driven by you @jcouv - you are key decision maker, and responsible for it, so assigning to yourself is a good thing ;-). You don't need to block on Runtime area owners to bless things, just keep them informed. If ValueTuple grows into 10+ issues, we might want to create separate area path for it.
