### ISSUE TITLE
Can't find ways for custom marshaling

### ISSUE THREAD

**Issue by Dia6lo** [dotnet/corefx#17153]
I have created new .NET Core console app in VS 2017 (targeting .NETCoreApp 1.1) and I want to use custom marshaling in my code, but I stuck with 2 issues:
1. There is no UnmanagedType.CustomMarshaler (== 44) enum member anymore
2. There is no ICustomMarshaler anymore (I guess since https://github.com/dotnet/corefx/pull/15769)

So, there is a question: was custom marshaling removed from .NET Core or I'm just missing something?

**Comment by svick** [comment]
[`UnmanagedType.CustomMarshaler`](https://apisof.net/catalog/System.Runtime.InteropServices.UnmanagedType.CustomMarshaler) and [`ICustomMarshaler`](https://apisof.net/catalog/System.Runtime.InteropServices.ICustomMarshaler) are coming back in .Net Core 2.0/.Net Standard 2.0.

Though I don't know if that means custom marshaling will actually be supported on .Net Core 2.0.

**Comment by karelz** [comment]
@yizhang82 @tijoytom can you please comment?

**Comment by yizhang82** [comment]
It is supported in .NET Core 2.0. The commit is https://github.com/dotnet/coreclr/commit/e8c4f5499136e137fdb3e3c5fb798b2637b21996

**Comment by karelz** [comment]
Closing per @yizhang82's comment above. Please reopen if you feel it is not sufficient answer.

**Comment by danmosemsft** [comment]
@Dia6lo if you want to try out 2.0 you can take a look at this
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md

**Comment by Dia6lo** [comment]
Thanks, @danmosemsft, I'll surely try it!

**Comment by yizhang82** [comment]
@Dia6lo I gave the instruction a try on my MBP (using the MacOSX 64-bit tarball) and it worked for me. I copy/pasted some code from Mono.POSIX (and strip out some unnecessary dependency) and it just worked.  

```csharp
using System;
using System.Runtime.InteropServices;

class Unsafe
{
    class StringMarshaler : ICustomMarshaler {

		private static StringMarshaler Instance = new StringMarshaler ();

		public static ICustomMarshaler GetInstance (string s)
		{
			return Instance;
		}

		public void CleanUpManagedData (object o)
		{
		}

		public void CleanUpNativeData (IntPtr pNativeData)
		{
                        Marshal.FreeCoTaskMem(pNativeData);
		}

		public int GetNativeDataSize ()
		{
			return IntPtr.Size;
		}

		public IntPtr MarshalManagedToNative (object obj)
		{
			string s = obj as string;
			if (s == null)
				return IntPtr.Zero;
			IntPtr p = Marshal.StringToCoTaskMemAnsi(s);
			return p;
		}

		public object MarshalNativeToManaged (IntPtr pNativeData)
		{
			string s = Marshal.PtrToStringAnsi(pNativeData);
			return s;
		}
	}

    [DllImport ("libc", EntryPoint="mkdir", SetLastError=true)]
    internal extern static int syscall_mkdir ([MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef=typeof(StringMarshaler))] string pathname, int mode);
}

class Program
{
    static void Main(string[] args)
    {
        Unsafe.syscall_mkdir("test", 0);
        Console.WriteLine("Hello World!");
    }
}
```
