### ISSUE TITLE
Some members of ECDsaCng are missing from Core

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#17163]
The following members are on types implemented in .NET Core. However on desktop they have more members. The members below are missing from Core. I believe that's because the types are included in NS, and the NS definitions don't include them because they're not in Xamarin (?) even though at least some of them they've been in .NET Desktop for a while.

The problem with this situation is
- it defies user expectations that if a type X exists, code from other platforms that use X will work on .NET Core: instead they have to reason about individual members on X
- in some cases it cannot be fixed without servicing -- for instance methods we could supply a package with extension methods, but it would not be binary-compatible as different type identity

We are considering [removing these types from NS2.0](https://github.com/dotnet/standard/issues/235) but that should not be relevant. I didn't look at usage data. Any that are not be technically possible on Core in ideally would exist but throw PlatformNotSupportedException. Even if we don't have time to implement them, it's potentially valuable to do that (allows compile to succeed, for a runtime path that may not be followed). 

```
MembersMustExist : Member 'System.Security.Cryptography.ECDsaCng.FromXmlString(System.String, System.Security.Cryptography.ECKeyXmlFormat)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.ECDsaCng.HashAlgorithm.get()' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.ECDsaCng.HashAlgorithm.set(System.Security.Cryptography.CngAlgorithm)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.ECDsaCng.SignData(System.Byte[])' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.ECDsaCng.SignData(System.Byte[], System.Int32, System.Int32)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.ECDsaCng.SignData(System.IO.Stream)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.ECDsaCng.ToXmlString(System.Security.Cryptography.ECKeyXmlFormat)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.ECDsaCng.VerifyData(System.Byte[], System.Byte[])' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.ECDsaCng.VerifyData(System.Byte[], System.Int32, System.Int32, System.Byte[])' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.ECDsaCng.VerifyData(System.IO.Stream, System.Byte[])' does not exist in the implementation but it does exist in the contract
```

I've not included those below that are clearly dependent on ACL's. We made the decision to omit those to avoid an undesired reference to ACLs from a NS library. If this isn't NS we could possibly reconsider that.

```

MembersMustExist : Member 'System.Security.Cryptography.CspKeyContainerInfo.CryptoKeySecurity.get()' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.CspParameters..ctor(System.Int32, System.String, System.String, System.Security.AccessControl.CryptoKeySecurity, System.IntPtr)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.CspParameters..ctor(System.Int32, System.String, System.String, System.Security.AccessControl.CryptoKeySecurity, System.Security.SecureString)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.CspParameters.CryptoKeySecurity.get()' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.CspParameters.CryptoKeySecurity.set(System.Security.AccessControl.CryptoKeySecurity)' does not exist in the implementation but it does exist in the contract
```

**Comment by danmosemsft** [comment]
@weshaggard in case I misstated.

**Comment by danmosemsft** [comment]
We decided to remove `ECDsaCng` from .NET Standard, those we should do. The `Csp` ones remain and can't be done as they can't pick up that ACL dependency.

**Comment by ViktorHofer** [comment]
@steveharter @danmosemsft Tried to port members (stopped after the first one) from netfx. Brings a ton of dependencies and duplicate types with it. Is this still planned for 2.0?

**Comment by steveharter** [comment]
@danmosemsft can you clarify the current desired\expected API additions; is the original list still appropriate. Thanks

**Comment by bartonjs** [comment]
@ViktorHofer Where were you making the change?  ECDsaCng is only defined within System.Security.Cryptography.Csp, so I don't see how you'd need to add a reference to that package...

```
MembersMustExist : Member 'System.Security.Cryptography.ECDsaCng.FromXmlString(System.String, System.Security.Cryptography.ECKeyXmlFormat)' does not exist in the implementation but it does exist in the contract.
'System.Security.Cryptography.ECDsaCng.ToXmlString(System.Security.Cryptography.ECKeyXmlFormat)' does not exist in the implementation but it does exist in the contract.
```

PlatformNotSupportedException.  Circular dependency between cryptography and XML (and networking).

```
MembersMustExist : Member 'System.Security.Cryptography.ECDsaCng.HashAlgorithm.get()' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.ECDsaCng.HashAlgorithm.set(System.Security.Cryptography.CngAlgorithm)' does not exist in the implementation but it does exist in the contract.
```

Copy from netfx: https://referencesource.microsoft.com/System.Core/R/d4770e0d4e849594.html (deleting the Contract calls).

```
MembersMustExist : Member 'System.Security.Cryptography.ECDsaCng.SignData(System.Byte[])' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.ECDsaCng.SignData(System.Byte[], System.Int32, System.Int32)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.ECDsaCng.SignData(System.IO.Stream)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.ECDsaCng.VerifyData(System.Byte[], System.Byte[])' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.ECDsaCng.VerifyData(System.Byte[], System.Int32, System.Int32, System.Byte[])' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.ECDsaCng.VerifyData(System.IO.Stream, System.Byte[])' does not exist in the implementation but it does exist in the contract
```

These are just overloads which don't take HashAlgorithmName (because they get it from the property).  They're all, effectively:

```C#
public byte[] SignData(Stream data) =>
    SignData(data, new HashAlgorithmName(HashAlgorithm.Algorithm));
```

**Comment by ViktorHofer** [comment]
> Where were you making the change? ECDsaCng is only defined within System.Security.Cryptography.Csp, so I don't see how you'd need to add a reference to that package...

I tried to add these in System.Security.Cryptography.Algorithms. I noticed the ECDsaCng types and overlooked that they are wrapped inside a `ECDsaImplementation` namespace.

I will try add them according to your manual. Thanks!

**Comment by ViktorHofer** [comment]
@danmosemsft See Jeremys post. How much sense does it make to add these members if they only throw PNSE? If we will never implement those shouldn't we leave them out from the beginning?

**Comment by danmosemsft** [comment]
@ViktorHofer we are choosing to throw PNSE rather than MissingMethodException because (1) MME cannot be reliably caught, JIT can preemptively JIT even dead methods (2) MME would be thrown in a live method even if the actual codepath that calls the API is dead. So where a library has existing code that invokes the API, PNSE is likely to be better than MME - either it will never be seen, or possibly it could be caught.
