### ISSUE TITLE
XmlSerializer not building correctly for UAPAOT

### ISSUE THREAD

**Issue by DnlHarvey** [dotnet/corefx#17160]
Here's the call stack I'm seeing, I don't think this can work in this configuration:
System.Xml.Serialization.TempAssembly.GenerateRefEmitAssembly($XmlMapping[] xmlMappings, Type[] types, String defaultNamespace)
System.Xml.Serialization.TempAssembly..ctor($XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location) 
System.Xml.Serialization.XmlSerializer.GenerateTempAssembly($XmlMapping xmlMapping, Type type, String defaultNamespace, String location)
System.Xml.Serialization.XmlSerializer.GenerateTempAssembly($XmlMapping xmlMapping, Type type, String defaultNamespace)
System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)

**Comment by danmosemsft** [comment]
@zhenlan

**Comment by joperezr** [comment]
cc @shmao do you mind taking a look?

**Comment by shmao** [comment]
@joperezr The issue seems that the assembly for UWP doesn't use the code under `#if uapaot`. To fix this, we may need to target the assembly for `uapaot` instead of `uap`, and add
```
<DefineConstants Condition="'$(TargetGroup)' == 'uapaot'">$(DefineConstants);uapaot</DefineConstants> 
```

**Comment by joperezr** [comment]
I see, I can fix that. I'll send up a PR

**Comment by shmao** [comment]
This was fixed by @joperezr. Closing the issue.
