### ISSUE TITLE
Tests under System.Net.Sockets.Tests.DisconnectTest failed in CI

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#17179]
Configuration: OuterLoop_Fedora23_debug ([build#131](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_fedora23_debug/131/testReport/))

Failed tests:
System.Net.Sockets.Tests.DisconnectTest.Disconnect_Success(reuseSocket: False)
System.Net.Sockets.Tests.DisconnectTest.BeginDisconnect_Success(reuseSocket: False)
System.Net.Sockets.Tests.DisconnectTest.DisconnectAsync_Success(reuseSocket: False)

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_fedora23_debug/131/consoleText

~~~
 System.Net.Sockets.Tests.DisconnectTest.Disconnect_Success(reuseSocket: False) [FAIL]
        Assert.Equal() Failure
        Expected: IsConnected
        Actual:   Success
        Stack Trace:
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_debug/src/System.Net.Sockets/tests/FunctionalTests/DisconnectTest.cs(79,0): at System.Net.Sockets.Tests.DisconnectTest.Disconnect_Success(Boolean reuseSocket)
     System.Net.Sockets.Tests.DisconnectTest.BeginDisconnect_Success(reuseSocket: False) [FAIL]
        Assert.Equal() Failure
        Expected: IsConnected
        Actual:   Success
        Stack Trace:
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_debug/src/System.Net.Sockets/tests/FunctionalTests/DisconnectTest.cs(167,0): at System.Net.Sockets.Tests.DisconnectTest.BeginDisconnect_Success(Boolean reuseSocket)
     System.Net.Sockets.Tests.DisconnectTest.DisconnectAsync_Success(reuseSocket: False) [FAIL]
        Assert.Equal() Failure
        Expected: IsConnected
        Actual:   Success
        Stack Trace:
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_debug/src/System.Net.Sockets/tests/FunctionalTests/DisconnectTest.cs(125,0): at System.Net.Sockets.Tests.DisconnectTest.DisconnectAsync_Success(Boolean reuseSocket)
~~~

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/corefx/pull/17167

**Comment by stephentoub** [comment]
This appears to still be happening, in particular on macOS, even after my fix in #17167.
cc: @luhenry

**Comment by karelz** [comment]
@stephentoub @luhenry are you guys working on the problem? (given it is assigned to you)

cc: @Priya91 @ianhays @steveharter

**Comment by luhenry** [comment]
I have submitted https://github.com/dotnet/corefx/pull/17189

**Comment by danmosemsft** [comment]
@luhenry sounds like we can close this now that's merged - please reactivate if I'm wrong.

**Comment by Jiayili1** [comment]
this issue is repro on OuterLoop_Fedora24_debug ([build#119](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_fedora24_debug/119/testReport/))Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_fedora24_debug/119/consoleText

Will check on next build to see if needing to reopen it.
