### ISSUE TITLE
Drawing primitives are missing [Browsable(false)] attributes

### ISSUE THREAD

**Issue by qmfrederik** [dotnet/corefx#17184]
Some of the Drawing primitives are missing `Browsable(false)` attributes. This causes additional attributes to show up in the list of properties returned by the `TypeDescriptor` for those classes.

Here's the full list:

* `Size` and `SizeF`:
  - `IsEmpty` should be marked as `[Browsable(false)]`
* `Point` and `PointF`:
  - `IsEmpty` should be marked as `[Browsable(false)]`
* `Rectangle` and `RectangleF`: 
  - `IsEmpty` should be marked as `[Browsable(false)]`
  - `Bottom` should be marked as `[Browsable(false)]`
  - `Left` should be marked as `[Browsable(false)]`
  - `Location` should be marked as `[Browsable(false)]`
  - `Right` should be marked as `[Browsable(false)]`
  - `Size` should be marked as `[Browsable(false)]`
  - `Top` should be marked as `[Browsable(false)]`

Adding these attributes should be fairly trivial and I'd be happy to submit a PR for this. Before that, just want to make sure there isn't a specific reason these attributes have been left out - I notice a lot of other properties do mark properties with `Browsable(false)`.

**Comment by karelz** [comment]
@alexperovich does it align with Desktop? If not, is it the right thing to do? Note: @qmfrederik wants to contribute ;-)

**Comment by qmfrederik** [comment]
@karelz @alexperovich Here are the MSDN docs for Desktop, all showing the `[Browsable(false)]` attribute:

* [Size.IsEmpty](https://msdn.microsoft.com/en-us/library/system.drawing.size.isempty(v=vs.110).aspx)
* [Point.IsEmpty](https://msdn.microsoft.com/en-us/library/system.drawing.point.isempty(v=vs.110).aspx)
* [Rectangle.IsEmpty](https://msdn.microsoft.com/en-us/library/system.drawing.rectangle.isempty(v=vs.110).aspx)
* [Rectangle.Bottom](https://msdn.microsoft.com/en-us/library/system.drawing.rectangle.bottom(v=vs.110).aspx)
* [Rectangle.Left](https://msdn.microsoft.com/en-us/library/system.drawing.rectangle.bottom(v=vs.110).aspx)
* [Rectangle.Location](https://msdn.microsoft.com/en-us/library/system.drawing.rectangle.location(v=vs.110).aspx)
* [Rectangle.Right](https://msdn.microsoft.com/en-us/library/system.drawing.rectangle.right(v=vs.110).aspx)
* [Rectangle.Size](https://msdn.microsoft.com/en-us/library/system.drawing.rectangle.size(v=vs.110).aspx)
* [Rectangle.Top](https://msdn.microsoft.com/en-us/library/system.drawing.rectangle.top(v=vs.110).aspx)

**Comment by karelz** [comment]
You can also check Desktop code at https://referencesource.microsoft.com/ and https://github.com/Microsoft/referencesource
If Desktop has it, I don't see reason for .NET Core to drop it. @alexperovich should provide final call.

**Comment by qmfrederik** [comment]
Yup, that attribute is also present in the reference source:

- [Size](https://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/Size.cs,135)
- [Point](https://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/Point.cs,83)
- [Rectangle](https://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/Rectangle.cs,98)

**Comment by alexperovich** [comment]
I don't see any reason why they shouldn't have it. I believe they were not included because the attribute didn't exist in .net core, but it should exist now with the 2.0 work.

**Comment by mellinoe** [comment]
Is this something we should do a broader pass over, if it's a compatibility concern?

**Comment by alexperovich** [comment]
That would probably be a good idea, though BrowsableAttribute isn't really a compat thing. It's just used by designers.

**Comment by mellinoe** [comment]
This made me think it could affect actual code, although maybe the only code doing this is designers 😄 

> This causes additional attributes to show up in the list of properties returned by the TypeDescriptor for those classes.

**Comment by qmfrederik** [comment]
> This causes additional attributes to show up in the list of properties returned by the TypeDescriptor for those classes.

Yes, that's how this got on my radar. Some of the unit tests of Mono's System.Drawing fail on .NET Core 2.0 because of this.

I'll prepare a PR which brings back these attributes

**Comment by karelz** [comment]
@danmosemsft we may need to do broader pass on this attribute - can you please track it?
