### ISSUE TITLE
System.Diagnostics.Tests.ProcessTests.HandleCountChanges failed in CI

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#17180]
Configuration: InnerLoop_Fedora24_release ([build#1378](https://ci.dot.net/job/dotnet_corefx/job/master/job/fedora24_release/1378/testReport/))

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/fedora24_release/1378/consoleText

Failed test: System.Diagnostics.Tests.ProcessTests.HandleCountChanges

~~~
System.Diagnostics.Tests.ProcessTests.HandleCountChanges [FAIL]
        Assert.Equal() Failure
        Expected: 42
        Actual:   145
        Stack Trace:
           /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_release/src/Common/tests/System/Diagnostics/RemoteExecutorTestBase.cs(170,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
~~~

**Comment by stephentoub** [comment]
Looks like another case of https://github.com/dotnet/corefx/issues/16688
