### ISSUE TITLE
TestCommonPriorityAndTimeProperties failed in CI on macOS

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#17187]
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug_prtest/123/consoleText
```
System.Diagnostics.Tests.ProcessThreadTests.TestCommonPriorityAndTimeProperties [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest/src/System.Diagnostics.Process/tests/ProcessThreadTests.cs(26,0): at System.Diagnostics.Tests.ProcessThreadTests.TestCommonPriorityAndTimeProperties()
```

**Comment by danmosemsft** [comment]
@stephentoub this is saying that the threat state is not terminated but the ID is zero. It looks like there are circumstances on OSX where we can retrieve the ID but not the state (leaving it at "initialized"). Do you remember what those are -- your change: https://github.com/dotnet/corefx/pull/2185/files#diff-742d089551ef9077b50205f4b1610ef1R60

**Comment by stephentoub** [comment]
> Do you remember what those are

The main one IIRC is that getting the thread information is a two-step process: first we ask the OS for the thread IDs, and then we ask it in turn for each thread's information.  Since it's not atomic, it's possible between those steps a thread could have gone away, so we have its ID but don't know anything more about it.

I don't know if there are other cases where we'd be unable to get the data on the thread given the ID.  If there aren't any others, than we should change the code to only add the thread to the list if we were able to get its data, since an inability to get the data would mean the thread is no longer relevant.  If there are other reasons, we'd instead want to fix the test to accommodate it, as it would make sense for diagnostic purposes to keep the knowledge of the thread around even if we couldn't get more data on it.

**Comment by mellinoe** [comment]
Another repro: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release_prtest/591/consoleFull#18173352579fe3b83-f408-404c-b9e7-9207d232e5fc

**Comment by danmosemsft** [comment]
@Priya91 do you have a preference amongst the two optoins @stephentoub lists above?

**Comment by Priya91** [comment]
@danmosemsft I don't understand your comment, the test has failed because the thread id is less than zero when threadstate is not terminated. Given that we get the id first and then the thread state, we should not be in this state no?

**Comment by danmosemsft** [comment]
@Priya91 you're right, I misread `>= 0` as `> 0`. 

So what I described is not the cause here --  OSX is returning -1 and we need to find out why (or accommodate that?)

What I describe still sounds like it might be something we might want to improve some day.

**Comment by Jiayili1** [comment]
Failed again here: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release/759/testReport/System.Diagnostics.Tests/ProcessThreadTests/TestCommonPriorityAndTimeProperties/

**Comment by Priya91** [comment]
One possible explanation could be, the osx thread id is a ulong value, and the public surface area in .NET gives thread id as int, it could be that the ulong value was large that while casting it became a negative number [here](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessThread.cs#L59). Adding threadID value to error to check the assumption, if the value is int.minvalue then it should be a cast problem.
