### ISSUE TITLE
Improve SkipOnTargetFramework for UAP use

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#17193]
Right now TFM is defined like this
```
    public enum TargetFrameworkMonikers
    { ...
        NetFramework = 0x800,
        Netcoreapp = 0x1000,
        Uap = 0x2000,
        UapAot = 0x4000,
```
and these map 1:1 to the XUnit traits passed to the runs:
```
        internal static string NonNetfxTest = "nonnetfxtests";
        internal static string NonUapTest = "nonuaptests";
        internal static string NonUapAotTest = "nonuapaottests";
        internal static string NonNetcoreappTest = "nonnetcoreapptests";
```

Code for uap, uapaot, and netcoreapp is 99% the same and functional behavior should be 99% the same between netcoreapp and uap and 98% the same with uapaot. We want most implementation and tests to be oblivious of the differences.

So 
(1) it would be nice to have a shortcut for
 `[SkipOnTargetFramework(TargetFrameworkMonikers.Netcoreapp | TargetFrameworkMonikers.Uap  | TargetFrameworkMonikers.UapAot)]`

(2) it would be nice for `TargetFrameworkMonikers.Uap` to automatically include `TargetFrameworkMonikers.UapAot` just as `#if uap` applies in `uapaot` builds also.

This change would actually be in buildtools but I'll put it here for discussion first.

**Comment by danmosemsft** [comment]
@jkotas for comment on #2

**Comment by jkotas** [comment]
This is basically another incarnation of TFM hierarchy.

> it would be nice to have a shortcut for
> [SkipOnTargetFramework(TargetFrameworkMonikers.Netcoreapp | TargetFrameworkMonikers.Uap | TargetFrameworkMonikers.UapAot)]

There is a shortcut for it today used in number of places: `[SkipOnTargetFramework(~TargetFrameworkMonikers.NetFramework, ...)]`. It explains pretty well what it actually is - it is testing behavior that was changed from .NET Framework.

> it would be nice for TargetFrameworkMonikers.Uap to automatically include TargetFrameworkMonikers.UapAot

Agree.

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/buildtools #1395](https://github.com/dotnet/buildtools/issues/1395) via [**ZenHub**](https://www.zenhub.com/)
