### ISSUE TITLE
System.Xml.XPath.XmlDocument is no longer getting produced/published

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#17190]
`System.Xml.XPath.XmlDocument` is not in the shared framework, and there are no recent nuget packages for it on https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Xml.XPath.XmlDocument. 

We need to publish this assembly somewhere - either in the shared framework or as a standalone NuGet package.

@ericstj @weshaggard @krwq

**Comment by weshaggard** [comment]
@sepidehMS @danmosemsft 


We should avoid shipping another package for this if we can. We should verify but my assumption is that all the extension methods that are here are now instance members on the core XML types after our NS2.0 work, so this should never be needed for new source and only necessary for existing binaries.

The options I see are:

1. Live with old package for anyone that needs this binary. (We should verify that the 4.3.0 package works on .NET Core 2.0).
2. Just merge it in to the shared framework. 

If my assumptions are correct and the 4.3.0 package works on .NET Core 2.0 I would prefer we go with option 1.

**Comment by ericstj** [comment]
If we do option 1 then we should delete the entire contract from the master branch.

**Comment by eerhardt** [comment]
If we go with option 1, it would seem appropriate to have some sort of assurance (i.e. test) this continues to work.  I'm not sure where the best place to test it would be, maybe in `dotnet/core-setup`.

**Comment by sepidehMS** [comment]
The extension type in System.Xml.XPath.XmlDocument exposes 7 extension methods from which 2 are not available as instance members:

1. `public static System.Xml.XPath.XPathNavigator CreateNavigator(this XmlDocument document, System.Xml.XmlNode node)` which is `protected internal virtual System.Xml.XPath.XPathNavigator CreateNavigator(System.Xml.XmlNode node)` on XmlDocument type

2. `public static System.Xml.XPath.IXPathNavigable ToXPathNavigable(this XmlNode node)` which doesn't exist on XmlNode type

I tested referencing System.Xml.XPath.XmlDocument 4.3.0 package in a NetCoreApp2.0 project using one of these methods and that worked fine.

Given this information, do we expose these methods on NetCore2.0 and remove this branch, or do we go with option 2?

**Comment by ericstj** [comment]
For `ToXPathNavigable` is that because we missed something in the NS2.0 work or was that an entirely new method?

**Comment by sepidehMS** [comment]
@ericstj I believe it's a new method as it doesn't exist on Desktop.
