### ISSUE TITLE
Can System.Data.SqlClient take a dependency on non .Net Core libraries?

### ISSUE THREAD

**Issue by saurabh500** [dotnet/corefx#17202]
This is a question more than an issue which will help with the design of Azure Active Directory authentication for Azure SQL DB. 

SqlClient on Desktop depends on a DLL written in C++ and utilizes Windows APIs which needs to be installed on the client machine to be able to authenticate to Azure SQL DB using AAD. 

For .Net Core, the solution provided above doesn't apply as it is not applicable to Unix or macOS. 

To add Azure Active Directory support in SqlClient, the access token has to be retrieved from AAD using HTTP rest calls.
There are client libraries provided by AAD in C# to expedite clients to retrieve the Access Token. Can SqlClient take a dependency on one of these libraries?
If we cannot take a dependency, then SqlClient needs to implement the Access Token retrieval in the client itself which is a big maintenance overhead. 

What is the guidance in this case? Was such a design decision needed by any other .Net Core libraries?

**Comment by danmosemsft** [comment]
@weshaggard

**Comment by NickCraver** [comment]
One major issue is community as well: this isn't just `SqlClient`. This would affect things like Dapper as well - it's a mess for all downstream libraries as well when the core ones do things like this. I personally wouldn't want to see this dependency taken. IMO, it'd be cleaner to put that auth in another library (though that ship may have sailed).

**Comment by weshaggard** [comment]
We cannot take a dependency on anything in the core which we don't build the source for ourselves. I see a few possible directions:

1. We implement the authentication ourselves, either directly in SqlClient or another library.
2. We expose new APIs in SqlClient as an extension point that allow an application to do the authentication they need and pass along the access token so SqlClient can use it.
3. We do some sort of light-up dynamic dependency that SqlClient can use reflection to see if the library that does authentication exists and if so call it and if not then the feature doesn't work.

I don't know all the details of how this works but I would personally lean towards option (2) if at all possible.

**Comment by saurabh500** [comment]
@NickCraver @weshaggard Thanks for the feedback.

@NickCraver  
>IMO, it'd be cleaner to put that auth in another library (though that ship may have sailed)

Do you mean a .Net Core library which can provide the functionality which can be consumed by upstream libraries like SqlClient?

**Comment by karelz** [comment]
Option 1b: Share the source code with client library (assuming licenses are compatible, etc.)

**Comment by NickCraver** [comment]
@saurabh500 I'd expect to see such functionality in another library, e.g. `System.Data.SqlClient.AzureAD`. If you're using Azure AD, you reference that package. I think this integrates well @weshaggard's option 2 above (which I agree with).

**Comment by saurabh500** [comment]
Thanks for the feedback.
