### ISSUE TITLE
System.ServiceProcess.Tests.ServiceControllerTests.StopAndStart failed in CI

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#17222]
Failed test: System.ServiceProcess.Tests.ServiceControllerTests.StopAndStart
Configuration: OuterLoop_Windows10_release ([build#130](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_release/130/testReport/))

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_release/130/consoleText

Message:
~~~
System.ServiceProcess.Tests.ServiceControllerTests.StopAndStart [FAIL]
        System.ServiceProcess.TimeoutException : Time out has expired and the operation has not been completed.
~~~

Stack Trace:
~~~
D:\j\workspace\outerloop_win---6835b088\src\System.ServiceProcess.ServiceController\src\System\ServiceProcess\ServiceController.cs(849,0): at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
           D:\j\workspace\outerloop_win---6835b088\src\System.ServiceProcess.ServiceController\tests\System.ServiceProcess.ServiceController.Tests\ServiceControllerTests.cs(182,0): at System.ServiceProcess.Tests.ServiceControllerTests.StopAndStart()
~~~

**Comment by karelz** [comment]
@Jiayili1 can you please add test-run-core or test-run-desktop tags to bugs you file? They are more useful than the blocking-clean-ci ...
Thanks!
cc @danmosemsft

**Comment by Jiayili1** [comment]
@karelz Got it.

**Comment by karelz** [comment]
Thanks @Jiayili1!

**Comment by danmosemsft** [comment]
First thing to try could be increasing the 10 sec timeout in ServiceControllerTests.cs to 30 sec or something. @Priya91 if that seems reasonable, @Jiayili1 could do it for us?

**Comment by Priya91** [comment]
@danmosemsft Yes, that seems like a reasonable change, the 10s is a guesstimate. Also note that initially it was 5, and we bumped it to 10 sec. 

@Jiayili1 The timeout is [here](https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.Tests/ServiceControllerTests.cs#L25). Thanks for helping with this :)

**Comment by Jiayili1** [comment]
@danmosemsft @Priya91 I will change the 10 to 30 and update the pull request link here.

**Comment by Jiayili1** [comment]
https://github.com/dotnet/corefx/pull/17288
