### ISSUE TITLE
Is there a version 4.1.0.0 of System.Xml.ReaderWriter anywhere?

### ISSUE THREAD

**Issue by mattleibow** [dotnet/corefx#17236]
I notice in the v4.3.0 NuGet of System.Xml.ReaderWriter, the `netstandard1.3` assembly version is 4.1.0.0. But, no other version is like this, all appear to be version 4.0.10.0... The `netcore50` version is 4.0.10.0. Even System.Xml.XDocument, which has a direct dependency on System.Xml.ReaderWriter, references a version 4.0.10.0. (The references of which I speak are the actual assembly references, not NuGet references)

At runtime, I get an exception saying that v4.1 is not found - which is to be expected.

To resolve this, can either reference the v4.0.11 NuGet directly, or set the `NetStandardImplicitPackageVersion` property to `1.6.0`.

The real question is this by design? or is there a problem? I am running the latest stable/RTM version of Windows 10, and if I am having an issue after upgrading my .NET Standard version, there should be others?

My use case was building a new `netstandard1.3` assembly (which uses XML) and NuGet, and then reference that NuGet in a UWP app. Nothing fancy, just plain old NuGet. It was working fine when I was targeting project.json and `"NETStandard.Library": "1.6.0"`. So this really has to do with the "implicit" upgrade to v1.6.1 as well.

**Comment by karelz** [comment]
@ericstj @weshaggard packaging bug?

**Comment by weshaggard** [comment]
@mattleibow what are you targeting? Are you targeting .NET Framework?

There is a 4.1.0.0 version of this library in the nuget package under `lib\netstandard1.3\System.Xml.ReaderWriter.dll`

**Comment by mattleibow** [comment]
@weshaggard I was targeting UWP. I created a new .NET Standard library, and then took that output .dll and added it to my UWP app. I then got that runtime error.

**Comment by weshaggard** [comment]
Can you share your project.json file? 

As an aside UWP doesn't yet have first class support for the "NETStandard.Library" package. Is there a reason you are trying to consume the latest System.Xml.ReaderWriter library?

**Comment by mattleibow** [comment]
I was not trying to support that version particularly, I was just building this project file:
https://github.com/mono/SkiaSharp/blob/master/binding/SkiaSharp.NetStandard/SkiaSharp.NetStandard.csproj#L10

If I remove that line (line 10), then it builds against 1.6.1, which has a version ReaderWriter that is not available in a UWP app.

**Comment by weshaggard** [comment]
I see so you are building a netstandard1.3 library using the new msbuild tooling just released with VS2017 and then are you trying to consume this via a ProjectReference or are you referencing the nuget package in your UWP application?

**Comment by mattleibow** [comment]
I managed to get a test case: https://github.com/mattleibow/UWP-NetStandard-Test

Doesn't do much, except that ClassLibrary1 references:

```xml
<PackageReference Include="System.Xml.ReaderWriter" Version="4.3.0" />
```

and then the app (App2) references the dll:

```xml
<Reference Include="ClassLibrary1, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
```

If I reference the project, via a project reference, then it "works" but this is not what happens when my .dll is in a NuGet.

**Comment by mattleibow** [comment]
If I specify the lower NuGet version (v4.0.11) I get this warning:

>Detected package downgrade: System.Xml.ReaderWriter from 4.3.0 to 4.0.11 
> ClassLibrary1 (>= 1.0.0) -> NETStandard.Library (>= 1.6.1) -> System.Xml.ReaderWriter (>= 4.3.0) 
> ClassLibrary1 (>= 1.0.0) -> System.Xml.ReaderWriter (>= 4.0.11)			0

**Comment by weshaggard** [comment]
@srivatsn do you guys support referencing a new standard library project from a UWP project?

**Comment by srivatsn** [comment]
Yes referencing from UWP should work.

**Comment by mattleibow** [comment]
The actual referencing works, but the System.Xml.ReaderWriter v4.3.0 NuGet has an assembly version that does not appear to exist in the UWP profile: "System.Xml.ReaderWriter.dll,Version=4.1.0.0"

**Comment by weshaggard** [comment]
@mattleibow I took a look at your repo (thinks for the minimal project repo). You are correct this isn't fully working it appears as though the package references are not flowing across the ProjectReference so the UWP application isn't merging the package graphs and so it isn't picking up the newer package for System.Xml.ReaderWriter. On top of the workaround you suggested you can also explicitly add "System.Xml.ReaderWriter" 4.3.0 to your UWP project.json file.

@srivatsn @livarcocc where would be the right place to file a tooling issue for this?

**Comment by srivatsn** [comment]
I think you can start with https://github.com/dotnet/sdk

**Comment by mattleibow** [comment]
@weshaggard Thanks for confirming. For now, I will just build against the older NETStandard.Library. And if I need to use a later version, I can add a netstandard dependency into my .nuspec. That should solve all issues.

**Comment by weshaggard** [comment]
Issue moved to [dotnet/sdk #1038](https://github.com/dotnet/sdk/issues/1038) via [**ZenHub**](https://www.zenhub.com/)
