### ISSUE TITLE
Need api to determine if a type is "byref-like."

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#17232]
**Proposal for New API:** 

```c#
   class Type
   {
        public virtual bool IsByRefLike => throw new NotSupportedException();
   }
```

With Span<>, we're now introducing a mainstream type that has "by-ref-like" or "stack-only" restrictions. We also have TypedReference in this bucket, but Span<> takes this concept out of the "eccentric uncle in the closet" realm.

There is, however, no robust way to know if a type has these restrictions. Apis like Array.CreateInstance() need to guard against these types (https://github.com/dotnet/corert/pull/3000) and could use a formalized way to catch these types. It's likely that checks like these could go viral into app code or higher level libraries that call apis like this.

**Comment by karelz** [comment]
Looks somewhat related to recent #14047. Will we need more similar APIs for Span?
cc @jkotas

**Comment by jkotas** [comment]
This should wait for the design for byref-like types (e.g. ttps://github.com/dotnet/csharplang/pull/264).

I expect that the byref-like types will be explicitly marked by a custom attribute. So this property won't be inferred, but explicitly specified instead and this API will be essentially just a fetch of this custom attribute (or more efficient equivalent).

**Comment by MichalStrehovsky** [comment]
This would be an API that should be used in `Microsoft.CSharp` as well (in [isSpecialByRefType](https://github.com/dotnet/corefx/blob/f38d75c8a10309b34213e5d4a96313f538194392/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Semantics/Types/Type.cs#L613)). The current implementation of that seems to have been hollowed out when `TypedReference` and friends weren't in the .NET Core profile. It likely wants the special behavior for `Span<T>` as well.

Cc @JonHanna

**Comment by JonHanna** [comment]
@MichalStrehovsky  From taking a look at a disassembly of the version in the GAC it seems that that version is implementing `isSpecialByRefType` by checking against a few specified names, which aren't names the corefx version knows about. Making use of the API proposed here would likely be better than any attempt to just restore the old logic.

**Comment by MichalStrehovsky** [comment]
> This should wait for the design for byref-like types (e.g. dotnet/csharplang#264).

These now have an approved attribute (`System.Runtime.CompilerServices.IsRefLikeAttribute`) that marks them. Maybe we can drop the *blocked* tag?

**Comment by terrajobst** [comment]
We should align this with the attribute we approved earlier, which is named `IsByRefLikeAttribute`. Since the proposal matches that, it's approved as proposed.

**Comment by karelz** [comment]
FYI: The API review discussion was recorded - see https://youtu.be/VppFZYG-9cA?t=5306

**Comment by bergmeister** [comment]
@terrajobst The [IsByRef ](https://docs.microsoft.com/en-us/dotnet/api/system.type.isbyref?view=netcore-2.1) property on `System.Type` is only available in .Net Core and not in .Net Standard or full .Net. Could I use the [IsByRefLikeAttribute ](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.isbyreflikeattribute?view=netframework-4.7.2) instead on full .net as an equivalent implementation of my own for `IsByRef ` or is there another way of using this property on full .net (4.7.2)? The documentation says only `This attribute is used by the compiler for tracking metadata. It should not be used by application developers.`

**Comment by jkotas** [comment]
@bergmeister Correct, the workaround is to check for presence of IsByRefLikeAttribute. The first class support for byref-like types is present in .NET Core only. 

Also see https://github.com/dotnet/corefx/issues/33149
