### ISSUE TITLE
X509StoreTests.Constructor_StoreHandle failed on macOS in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#17235]
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_osx_debug_prtest/93/consoleText
```
System.Security.Cryptography.X509Certificates.Tests.X509StoreTests.Constructor_StoreHandle [FAIL]
        Assert.Equal() Failure
        Expected: 3
        Actual:   2
        Stack Trace:
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_osx_debug_prtest/src/System.Security.Cryptography.X509Certificates/tests/X509StoreTests.cs(63,0): at System.Security.Cryptography.X509Certificates.Tests.X509StoreTests.Constructor_StoreHandle()
```

**Comment by stephentoub** [comment]
Again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_osx_debug_prtest/94/

**Comment by bartonjs** [comment]
@mmitche I know we talked in the hallway about having the parallel job count for the Macs be reduced to 1; did that happen?

**Comment by bartonjs** [comment]
Actually, while parallel jobs can make this fire, I think it can occasionally trip itself, too.

If an outerloop store modifying test happens at the same time as this, there's the race condition between two reads of store.Certificates seeing a modified state.

So the test needs to be hardened.

* X509StoreMutableTests_OSX and X509StoreTests added to the same \[Xunit.Collection\]
* Make the test find a more reliable way of proving that it has an open handle
* Some other clever option.

Parallel jobs can still make the existing mutable tests confused; but we definitely shouldn't let a single job confuse itself.
