### ISSUE TITLE
Provide a way to override the logic of retrieving the preamble bytes in StreamWriter

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#17242]
@kichalla commented on [Tue May 05 2015](https://github.com/dotnet/coreclr/issues/933)

In ASP.NET MVC, we use StreamWriter in some places to write data to the response stream. We want to avoid writing the BOM or preamble bytes irrespective of whether an encoding requires preamble or not.

I was initially looking to subclass StreamWriter and override some method like `GetPreamble` to prevent writing the preamble bytes, but couldn't find any.

(I initially had a wrapper around the supplied encoding to prevent preamble bytes...even though this works, it feels hacky)

For reference:
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/StreamWriter.cs#L283

---

@bpschoch commented on [Wed May 06 2015](https://github.com/dotnet/coreclr/issues/933#issuecomment-99581315)

some say you can do it via the New UTF8Encoding(false) http://stackoverflow.com/questions/5266069/streamwriter-and-utf-8-byte-order-marks/11655096#11655096

I started an issue on corefx: https://github.com/dotnet/corefx/issues/1645

---

@kichalla commented on [Wed May 06 2015](https://github.com/dotnet/coreclr/issues/933#issuecomment-99608272)

Sure, I am aware of it...the thing is this encoding is provided by an end user and they might provide with a BOM encoding or not...

---

@bpschoch commented on [Wed May 06 2015](https://github.com/dotnet/coreclr/issues/933#issuecomment-99618606)

I made a general proposal on a possible solution here: https://github.com/dotnet/corefx/issues/1645
I'm trying to understand what you are looking for.  Your issue appears that you get handed an encoding and using that encoding, prevent any BOM from being generated.

Would that proposal solve your issue?

---

@kichalla commented on [Wed May 06 2015](https://github.com/dotnet/coreclr/issues/933#issuecomment-99619289)

yes, that's right....we want to prevent writing out the BOM in all cases...sure, that proposal would work for me...thanks..

---

@svick commented on [Wed May 06 2015](https://github.com/dotnet/coreclr/issues/933#issuecomment-99659995)

@kichalla That sounds to me like an edge case that doesn't need to be supported directly by the framework. Any reason why you can't use something like the following code?

``` c#
if (encoding is UTF8Encoding)
    encoding = new UTF8Ending(false);
else if (encoding is UnicodeEncoding)
    encoding = new UnicodeEncoding(false, false);
```

---

@jbevain commented on [Thu May 07 2015](https://github.com/dotnet/coreclr/issues/933#issuecomment-99775049)

Agreed with @svick.

I'd solve it in a generic way using:

``` csharp
    class WithoutPreambleEncoding : Encoding
    {
        private readonly Encoding _encoding;

        public WithoutPreambleEncoding(Encoding encoding)
        {
            _encoding = encoding;
        }

        public override byte[] GetPreamble()
        {
            return new byte[0];
        }

        public override int GetByteCount(char[] chars, int index, int count)
        {
            return _encoding.GetByteCount(chars, index, count);
        }

        public override int GetBytes(char[] chars, int charIndex, int charCount, byte[] bytes, int byteIndex)
        {
            return _encoding.GetBytes(chars, charIndex, charCount, bytes, byteIndex);
        }

        // ...
}
```

---

@kichalla commented on [Thu May 07 2015](https://github.com/dotnet/coreclr/issues/933#issuecomment-99838741)

@svick @jbevain : I actually had the same encoding wrapper like what you mentioned to solve for all encodings...but this felt hacky and so just wanted to check...

---

@joshfree commented on [Wed Oct 28 2015](https://github.com/dotnet/coreclr/issues/933#issuecomment-151951797)

@JeremyKuhne can you move this to /dotnet/corefx please

---

@karelz commented on [Fri Mar 17 2017](https://github.com/dotnet/coreclr/issues/933#issuecomment-287306822)

@ianhays @JeremyKuhne please move it to corefx repo. API additions should not be tracked in coreclr.

**Comment by JeremyKuhne** [comment]
Triage: Closing due to lack of interest (nearly 5 years).
