### ISSUE TITLE
Implement Process.set_Min/MaxWorkingSet on Linux for current process

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1725]
The Min/MaxWorkingSet properties have a working getter on Linux, but the setter throws PlatformNotSupportedException.  The OSX implementation also throws PlatformNotSupportedException, except for when the target process is the current process, in which case it's special-cased and works.  We should be consistent, and either implement this special case on Linux or remove the special case on OSX, preferably the former.

**Comment by ianhays** [comment]
Doesn't look like there's any way to set the resident set for a modern Linux machine; the closest possible alternative is to set the virtual memory space via setrlimit(RLIMIT_AS).  

There is some interesting discussion [here] (http://stackoverflow.com/questions/3043709/resident-set-size-rss-limit-has-no-effect) on using a cgroup manager to restrict the amount a physical memory that a process is using, but it requires the cgroup-bin or systemd packages to be installed.

**Comment by stephentoub** [comment]
Thanks for investigating, Ian. Looks like we should stick with what we have.
