### ISSUE TITLE
Investigate implementing Process.Modules on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1727]
On Unix, we currently return an empty array from Process.Modules, and we throw a PlatformNotSupportedException from Process.MainModule.  Is there something better we can reasonably do on Linux and OSX?  If so, we should do it.

**Comment by ianhays** [comment]
Mono on Linux implemented this functionality and will print the names of the loaded dll’s or exe’s, including that of the running program. In a Hello World example, getting the Modules of the running process will return:
* Msorlib
* Hello
* System

The source for Mono’s implementation is archaic and resides chiefly in the [ves_icall_System_Diagnostics_Process_GetModules_internal()] (https://github.com/mono/mono/blob/55d8296440ee2c62b7f22dd7ad6e3836f09e5db4/mono/metadata/process.c) function. In Mono, the ability to list out the loaded Modules is handwritten in C, whereas in .NET Windows it relies upon the C++ function [EnumProcessModules] (https://msdn.microsoft.com/en-us/library/windows/desktop/ms682631(v=vs.85).aspx). It would require a great deal of effort to replicate the Mono functionality and although it is possible, it is frankly beyond me. Perhaps another set of eyes could discern more than mine, but as far as I could tell Modules in Mono rely heavily on the underlying runtime implementation and wouldn't translate to .NET.


I'm still searching through OSX and Linux docs for APIs that do similar things, but have thus far come upon nothing of use.


As far as alternatives go, I personally like the suggestions in [github issue 1081] (https://github.com/dotnet/corefx/issues/1081). 
* @terrajobst suggests that we add something like Process.CanQueryModuleInformation if we are going to have Process.MainModule throw an exception on some platforms. I agree.
* @Giorgi suggests we add a Process.Path property to get the path of the executable. This would take some of the use cases away from Process.MainModule and Process.Modules (which would throw/return the empty array on Unix) while also providing value in the Windows implementations.

**Comment by stephentoub** [comment]
Closed by #2188

**Comment by stephentoub** [comment]
Still needs an OS X implementation...
