### ISSUE TITLE
SpanPool

### ISSUE THREAD

**Issue by bcronce** [dotnet/corefx#17286]
Like the new `ArrayPool`, I could see a SpanPool being useful once/if Span becomes better supported. 

And since `Spans` are structs, you could do cool stuff like a bunch of Spans could be backed by a single large Array, allowing better cache locality, assuming the Spans are larger than a cache-line and multiples of a cache-line. And reducing object counts. Shrinking the pool could also represent an issue, if supported.

**Comment by davidfowl** [comment]
Not sure if this makes sense. Span is stack only. Take a look at System.Buffer.Primitives in corefxlab to see the current thinking here. The pool returns an OwnedMemory which can be passed around and is reference counted. You can then get spans and memory from that object needed.

**Comment by bcronce** [comment]
I'm not entirely sure what you mean by "stack only". The Span is a struct, but the array it points to is on the heap. I do see a lot of "ref", but they all (I think all) point back to offsets in the heap object.

What does raise some flags is the usage of "Pinnable", which is difficult to follow how it's used via GitHub. If the object actually gets pinned, it would make me question how to best use Span where it won't mess with the GC. At least if you used a single large backing Array, it could go strait to the LOH where the potentially pinned object won't need to negatively affect the GC. Even if not pinned, would be nice to have the backing Array go strait to the LOH.

I Digress. This may be at best, premature, and at worst, encourage bad patterns. I shall look into "OwnedMemory" thing. Thanks  :smile:

**Comment by davidfowl** [comment]
> I'm not entirely sure what you mean by "stack only". The Span is a struct, but the array it points to is on the heap. I do see a lot of "ref", but they all (I think all) point back to offsets in the heap object.

It means it *cannot* live on the heap. You can read more about it here https://github.com/dotnet/coreclr/issues/5851. It means you can't store it in a field of a class (as an example).

> I Digress. This may be at best, premature, and at worst, encourage bad patterns. I shall look into "OwnedMemory" thing. Thanks 😄

Yep, take a look a OwnedMemory, and friends https://github.com/dotnet/corefxlab/tree/master/src/System.Buffers.Primitives/System/Buffers.

**Comment by davidfowl** [comment]
@bcronce  even better https://github.com/dotnet/csharplang/pull/264/files

**Comment by ahsonkhan** [comment]
@bcronce, @davidfowl, close this issue?

**Comment by davidfowl** [comment]
Yes
