### ISSUE TITLE
DSACng does not match netfx or NIST when H < sizeof(q)

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#17305]
A TODO got left in the implementation of DSACng concerning the scenario where the hash size is smaller than the Q size: https://github.com/dotnet/corefx/blob/2c32fb1c1a14a054609a6f1a94927eb4e13bdd5e/src/Common/src/System/Security/Cryptography/DSACng.SignVerify.cs#L61-L70.

The code, as it stands, produces answers when netfx does not.  And a NIST CAVP test confirms that the behavior it does do is not standards-conformant.

FYI @steveharter.

**Comment by steveharter** [comment]
Yes this should match desktop semantics. Thanks
