### ISSUE TITLE
Recognize the framework and version of an assembly with the MetadataReader

### ISSUE THREAD

**Issue by raffaeler** [dotnet/corefx#17309]
The System.Reflection.Metadata.MetadataReader class allows me to read the metadata without loading permanently the assembly in memory.

Once I open the assembly with the MetadataReader, what is the best way to distinguish the assemblies targeting different frameworks?
- netstandard (framework neutral)
- .net framework
- .net core

And for each of those, how can I read the version (I mean for example netstandard1.4, netcoreapp1.1 and net 4.6.2)?
Reading the custom attributes or what else?

**Comment by svick** [comment]
I think you can do this by looking at the [`TargetFrameworkAttribute`](https://msdn.microsoft.com/en-us/library/system.runtime.versioning.targetframeworkattribute(v=vs.110).aspx) of the assembly. For example, for .Net Standard 1.3, the `FrameworkName` is `.NETStandard,Version=v1.3`, while for .Net Framework 4.5, it's `.NETFramework,Version=v4.5`.

(I don't know System.Reflection.Metadata, so I can't help you with figuring out how exactly to read the attribute property.)

**Comment by raffaeler** [comment]
Thank you, this is what I am doing by reading that custom attributes at Assembly level.
I was wondering if there some global flag in the metadata that can speed up the operation.

**Comment by raffaeler** [comment]
It looks like traditional Framework.NET assemblies does not contain TargetFrameworkAttribute.
An example is the net462 of System.Net.Ping.
Can I safely assume that a missing attribute implies netframework?
I don't like this system at all ...

**Comment by tmat** [comment]
@terrajobst @weshaggard @nguerrera  to comment on TargetFrameworkAttribute

**Comment by weshaggard** [comment]
TargetFrameworkAttribute is an optional pieces that is generated by some msbuild targets so it is isn't totally reliable. I know for example we don't put it on most of the corefx libraries. If it is present it is potentially usable but if it isn't present there isn't any great way to figure out what it was compiled against. You can try and look at the assembly references but that also isn't full proof and cannot always be uniquely mapped back to a particular version.

**Comment by raffaeler** [comment]
Thanks @weshaggard .
I expected to find some flag in the metadata which could give me a hint at least on the required CLR or similar. Are you telling me that there is nothing in the metadata for this purpose?

Inf not, what is the best strategy to dynamically load plugins (which should be compatible with the currently running framework)? Simply trying to load the assembly (and see if its is null) or what else?

**Comment by weshaggard** [comment]
>Are you telling me that there is nothing in the metadata for this purpose?

Correct there isn't any metadata that tells you which target framework or runtime is required. There are assembly references which give some hints but doesn't really help in all cases. If you were really interested you could look a the assembly references and see if all of them with the right versions are available to be loaded but honestly I would let the assembly loader do that for you. If you want to try and guard you can load the assembly and handle load exceptions.

**Comment by raffaeler** [comment]
Thank you, got it.
