### ISSUE TITLE
dotnet core api documentation is a huge step backward

### ISSUE THREAD

**Issue by MarkPflug** [dotnet/corefx#17308]
It is my opinion that the high quality of the documentation provided for the .NET BCL has always been one of its strong points. Pressing F1 in Visual Studio would usually provide you with great detail about how to use an API. With VS2017 and the new .NET Core help system I feel there has been a massive step backwards in the value provided by the documentation.

Compare the old documentation for SqlConnection.BeginTransaction():
https://msdn.microsoft.com/en-us/library/86773566(v=vs.110).aspx

To the new documentation:
https://docs.microsoft.com/en-us/dotnet/core/api/system.data.sqlclient.sqlconnection#System_Data_SqlClient_SqlConnection_BeginTransaction

The new documentation provides almost no information that couldn't already be gleaned from the name of the method; zero value.

The vast majority of the value of the documentation was in the Remarks and Examples sections which have been completely omitted from the new documentation.

An even better example would be DateTime.ToString:
Old: https://msdn.microsoft.com/en-us/library/zdtaw1bw(v=vs.110).aspx
New: https://docs.microsoft.com/en-us/dotnet/core/api/system.datetime#System_DateTime_ToString_System_String_

The new docs are clearly just an incomplete version of the old docs. The DateTime.ToString(string) highlights this with the parameter documentation: _A standard or custom date and time format string **(see Remarks)**_. See remarks? There are no remarks! The ONLY reason I can think that someone would come to the documentation for this method is to find out what the standard and custom format strings are, but that information is not provided.

If .NET core is intending to attract new developers from other platforms, this documentation is going to be a very unwelcoming experience for people picking up .NET for the first time.

Fortunately, the help viewer still provides the full documentation, like it always has. Unfortunately, the help viewer is not installed by default: you have to go manually install it as a stand-alone feature: assuming you know it exists to begin with.

**Comment by svick** [comment]
I agree that this is currently the biggest issue with the .Net Core docs.

That being said, documentation issues belong in [the docs repo](https://github.com/dotnet/docs) and this is a known issue. For example, see https://github.com/dotnet/docs/issues/307 (created over a year ago by me).

**Comment by dend** [comment]
@MarkPflug thank you so much for the feedback! My team and I are working on ensuring that we improve that experience. Stay tuned - we have significant improvements coming to the docs site in the .NET area shortly.

**Comment by SolderedMushroom** [comment]
Agreed about remarks, but I've always found the example section of MSDN documentation to be at best useless, if not outright detrimental. Usually the samples are five times longer than they need to be and won't help you understand the actual method supposedly being documented, unless you carefully scrutinize the entire example and have foreknowledge of the several other, sometimes esoteric, functions being used alongside the one you're interested in.

**Comment by svick** [comment]
@SolderedMushroom Well, once that part of the docs becomes open source (I'm assuming that's part of those coming "significant improvements"), you'll be able to improve them yourself.

**Comment by karelz** [comment]
This issue was moved to dotnet/docs#1778
