### ISSUE TITLE
Ignore CMAKE_C_FLAGS and CXX_FLAGS settings that comes from outside CMakeLists.

### ISSUE THREAD

**Issue by jyoungyun** [dotnet/corefx#17328]
```
set(CMAKE_C_FLAGS "-std=c11")
set(CMAKE_CXX_FLAGS "-std=c++11")
```
These line destroy the setting that comes from outside CMakeLists silently.
It should preserve the old value like below.
```
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c11")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
```

Is there a reason to let existing values be ignored?
If not, it should be fixed.

**Comment by stephentoub** [comment]
Fixed by #17329
