### ISSUE TITLE
Can not create Raw socket on CentOS 7

### ISSUE THREAD

**Issue by Hawkeyes0** [dotnet/corefx#17324]
Hello everyone,
I get a problem when create a Socket object with Raw type.
My environment as follow:
* centos 7 x64
* dotnet Core 1.0.1

My code:
```C#
_socket = new Socket(AddressFamily.InterNetwork, SocketType.Raw, ProtocolType.IP);
```

It work perfect on Windows, but throw a SocketException on CentOS.

The Exception:
```
System.Net.Sockets.SocketException: Protocol not supported
   at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
```

how can I make it work?
Thx

**Comment by stephentoub** [comment]
That error is coming from the OS; if it doesn't support it, there's nothing the .NET layer on top of it can do to support it.

On the same machine, what do you get if you put the following code into a file `rawsock.c`:
```C++
#include <stdio.h>
#include <sys/socket.h>
#include <netinet/ip.h>

int main(int argc, char** argv)
{
    int sd = socket(PF_INET, SOCK_RAW, IPPROTO_IP);
    if (sd < 0) perror("socket failed with: ");
    else printf("success\n");
}
```
compile it with:
```
gcc -o rawsock rawsock.c
```
and then run it:
```
./rawsock
```
?

**Comment by karelz** [comment]
Sounds like not CoreFX problem, closing. Please let us know if you disagree.

**Comment by Hawkeyes0** [comment]
thanks for reply.
@stephentoub , i'v try the program, and it failed with "Protocol not supported". 
@karelz , yes, this is not CoreFX problem.

I'll find other solutions.
thanks again.
