### ISSUE TITLE
ImmutableArray<T>.Equals(object) does not handle variance

### ISSUE THREAD

**Issue by sharwell** [dotnet/corefx#1733]
The tests mentioned in #1731 suggest that `ImmutableArray<string>.Empty.Equals(ImmutableArray<object>.Empty)` should return `true`. Currently it does not.

The current implementation of `ImmutableArray<T>.Equals(object)` is the following:

```csharp
if (obj is ImmutableArray<T>)
{
    return this.Equals((ImmutableArray<T>)obj);
}

return false;
```

To handle variance, this method would need to be extended with a fallback to using `IImmutableArray`:

```csharp
if (obj is ImmutableArray<T>)
{
    return this.Equals((ImmutableArray<T>)obj);
}

IImmutableArray other = obj as IImmutableArray;
if (other != null)
{
    return this.array == other.Array;
}

return false;
```

**Comment by stephentoub** [comment]
Thanks, @sharwell.  For this and #1731, as you've done the work to both identify the issues and suggest fixes, are you planning to submit a PR to address them?

**Comment by sharwell** [comment]
Sure :smile:

**Comment by stephentoub** [comment]
Great :smile: Thanks!
