### ISSUE TITLE
There is no more SelectSingleNode method in System.Xml?

### ISSUE THREAD

**Issue by Cae2** [dotnet/corefx#17349]
Hello,

Im porting one application from .net 4.5 to .net core and could not find SelectSingleNode to use with Xpath to filter my xmls. This method isnt avaiable anymore? (System.Xml 4.3.0)

thanks

**Comment by svick** [comment]
[.Net Core 1.0 and .Net Standard 1.3 have `SelectSingleNode` as an extension method in the `System.Xml.XPath.XmlDocument` package](https://apisof.net/catalog/System.Xml.XmlDocumentXPathExtensions.SelectSingleNode(XmlNode,String)) (not sure why the page does not list .Net Standard 1.3, the extension method exists there), so you will need to add a reference to that package to use it.

[.Net Core 2.0 and .Net Standard 2.0 change it back to an instance method.](https://apisof.net/catalog/System.Xml.XmlNode.SelectSingleNode(String))

**Comment by danmosemsft** [comment]
@Cae2 if you want to try 2.0 that would be great, let us know how you find it:
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md

Please close this if your q was answered.

**Comment by Cae2** [comment]
@svick thank you! with that package everything went fine.

@danmosemsft I need to finish this port real quick, but will test 2.0 in another greenfield project, thanks!
