### ISSUE TITLE
Run package closure validation during official builds, possibly CI

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#17346]
I added some validation for packages in https://github.com/dotnet/corefx/pull/17246

This is tracking additional improvements:

- [x] Switch to latest CLI and MSBuild based projects.
- [ ] Add test cases post-restore that examine the following:
    - [x] No bin-clashes
    - [ ] API compat between ref & lib.
    - [x] No type-clashes in ref.
    - [x] Verify closure
- [ ] Enable the tests to run in helix / official builds.

For 3 @Chrisboh pointed me at some docs for that: https://github.com/dotnet/core-eng/pull/598

/cc @chcosta @MattGal @weshaggard

**Comment by ericstj** [comment]
I've marked this as blocking because I at least want to make sure we run these tests manually before release.

**Comment by weshaggard** [comment]
@ericstj are you handling the rest of this or is this part of @joperezr work?

**Comment by joperezr** [comment]
FWIW, I am not entirely sure what packages does this issue track, but I am doing ApiCompat between ref & lib of M.NC.A + OOB packages as part of my validation.

**Comment by ericstj** [comment]
I have it all working through manual runs but don't have the helix work done.  I suspect that'll have to be good enough for this release.

**Comment by weshaggard** [comment]
@joperezr is this covered by the work you did to validated the shared framework or is this slightly different?

**Comment by joperezr** [comment]
My validation work was all manual, although I did generate some scripts that can be ran from the release branches to test api compat for packages. If the issue was meant to have this happening on CI builds and official builds then my work doesn't cover that.

**Comment by weshaggard** [comment]
Moving to Post-ZBB as the work left is to automate to package validation but no expected product changes.

**Comment by weshaggard** [comment]
@joperezr @ericstj what is left for this for this release?

**Comment by weshaggard** [comment]
@joperezr @ericstj any work left for 2.1?

**Comment by ericstj** [comment]
I think we have as much as we need for 2.1.  Its running as part of the allConfigurations leg.
