### ISSUE TITLE
Cleanup/fix Process's AsyncStreamReader

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1734]
This implementation has a variety of issues, some worse than others:
- It invokes the user's delegate while holding a lock.  In certain circumstances this could lead to deadlock.
- Calling CancelOperation() doesn't actually cancel: it prevents the delegate from being invoked again, but it continues to read asynchronously until the end of the stream.
- It's got a bunch of dead code: its IDisposable implementation, Close, CurrentEncoding, BaseStream, etc.
- Its async reading implementation could be simplified using async/await.

**Comment by Maxwe11** [comment]
>It invokes the user's delegate while holding a lock
It's acceptable to switch on using ConcurrentQueue instead of `lock` with Queue? That will require additional dependency on System.Collections.Concurrent package.

**Comment by stephentoub** [comment]
> It's acceptable to switch on using ConcurrentQueue instead of lock with Queue? That will require additional dependency on System.Collections.Concurrent package.

I don't think it's necessary in this case (or, at least, I haven't seen performance evidence that it is), and you'd also need to do the necessary due diligence to verify everything is synchronized correctly with the other uses.  I was simply thinking the invocation of the delegate could be moved outside of the lock.
