### ISSUE TITLE
Need an api to determine if a Type is a "plain old non-constructed type."

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#17345]
**Proposal for New API:** 

```c#
   class Type
   {
        public virtual bool IsTypeDefinition { get { throw NotImplemented.ByDesign; } }
   }
```

**Why**

Right now, if we want to test if a type is a plain old non-constructed type (i.e. "one with a mdTypeDef metadata token"), we have to use this windy expression:

```c#
if (!type.HasElementType && !type.IsConstructedGenericType && !type.IsGenericParameter) {...}
```

There are a few problems with this:

- It's a mouthful.
- It take 3 virtual calls 
- It's not robust against future expansions of the api. Suppose a future expansion to Reflection adds more slices to the Venn diagram (e.g. function pointer types, modified types, or something not yet envisioned...). We want to be able to write robust code that falls through to an "I don't understand this. NotSupportedException" fallback, but right now, there's no way to do that. We have to call every other **Is** property we know of, then hope that the "else" case will represent the right set for all time.

There is also completeness issue - we have inclusion predicates for every other slice of the Venn diagram, yet the most common slice of all lacks one?

**Naming**

I'm proposing it be called **IsTypeDefinition** for two reasons:

- We already have **IsGenericTypeDefinition** that captures the subset of defined types with generic parameters. So **IsTypeDefinition** is a natural derivation from that.

- It also rhymes naturally with **Assembly.DefinedTypes** (which returns all the non-constructed types in an assembly.)

**Comment by terrajobst** [comment]
Looks good as proposed.

**Comment by AtsushiKan** [comment]
Assigning myself for the CoreRT part (I have some refactoring plans related to this so I want to be the one to do this.)
