### ISSUE TITLE
System.Text.Encoding.GetEncoding(Int32 codepage) 850 error

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#17356]
While migrating SharpZipLib pcl library to netstandard1.3 and tests to netcore2.0 I noticed an issue with a few of their tests:

```
              <test-case id="1058" name="UnicodeNameConversion" fullname="ICSharpCode.SharpZipLib.Tests.Zip.GeneralHandling.UnicodeNameConversion" methodname="UnicodeNameConversion" classname="ICSharpCode.SharpZipLib.Tests.Zip.GeneralHandling" runstate="Runnable" seed="7467847" result="Failed" label="Error" start-time="2017-03-21 21:38:32Z" end-time="2017-03-21 21:38:32Z" duration="0.001758" asserts="0">
                <properties>
                  <property name="Category" value="Zip" />
                </properties>
                <failure>
                  <message><![CDATA[System.NotSupportedException : No data is available for encoding 850. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.]]></message>
                  <stack-trace><![CDATA[   at System.Text.Encoding.GetEncoding(Int32 codepage)
   at ICSharpCode.SharpZipLib.Zip.ZipConstants.ConvertToString(Byte[] data, Int32 count) in C:\Users\vikto\Documents\src\SharpZipLib\src\ICSharpCode.SharpZipLib\Zip\ZipConstants.cs:line 470
   at ICSharpCode.SharpZipLib.Zip.ZipConstants.ConvertToStringExt(Int32 flags, Byte[] data) in C:\Users\vikto\Documents\src\SharpZipLib\src\ICSharpCode.SharpZipLib\Zip\ZipConstants.cs:line 533
   at ICSharpCode.SharpZipLib.Tests.Zip.GeneralHandling.UnicodeNameConversion() in C:\Users\vikto\Documents\src\SharpZipLib\test\ICSharpCode.SharpZipLib.Tests\Zip\ZipTests.cs:line 2048]]></stack-trace>
                </failure>
              </test-case>
```

This is what triggers the exception:
`System.Text.Encoding.GetEncoding(defaultCodePage);`

Default code page gets set like that:
`static int defaultCodePage = Encoding.UTF8.CodePage;`

Did we change anything with netcore regarding codesets?

Source: https://github.com/ViktorHofer/SharpZipLib/blob/master/src/ICSharpCode.SharpZipLib/Zip/ZipConstants.cs#L550

**Comment by justinvp** [comment]
Most of the code pages have been moved to a separate component (System.Text.Encoding.CodePages) for .NET Core...

The following code needs to run before Encoding.GetEncoding will be able to find them:

```c#
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
```

**Comment by ViktorHofer** [comment]
Thank you!

I guess a lot of users who are currently using code pages will hit that issue during migration. Any way to point that out inside VS or in the docs?

**Comment by justinvp** [comment]
> And where should the registration happen? I guess once when the application starts? When building a library where would be the best place to call it?

@tarekgh says in https://github.com/dotnet/corefx/pull/16589#discussion_r103972132:

> I think registering the encoding provider should be the app decision and not the library decision. having the library registering the provider means any app using the library will pay the cost of the encoding even if the app not using the non-Unicode encodings.

**Comment by ViktorHofer** [comment]
Thanks @justinvp! Still not sure if this should really be set by the application in this case.

**Comment by justinvp** [comment]
As an example, SerialPort's tests register a provider because there are some tests that use non-Unicode code pages, but the SerialPort library itself doesn't register one. See #15965. I would imagine the same approach could be taken with SharpZipLib. Any .NET Core app using SharpZipLib that needs non-Unicode code page support could register the CodePagesEncodingProvider at app start.

**Comment by tarekgh** [comment]
@ViktorHofer usually you can register the provider before using the encoding on question. you can register it during the app initialization path. or you can delay the registering till you need it. Also there is no harm to register the same provider more than once.

the remark section in the following link talking about what exncoding supported by default and how to register the provider.

https://msdn.microsoft.com/en-us/library/system.text.encodingprovider(v=vs.110).aspx

let me know if you have any more questions

**Comment by ViktorHofer** [comment]
@tarekgh Thanks for the link! I also noticed that the exception states "For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.", that's fine.

If I understand that correctly, netcore should by default support UTF-8. Now I'm really confused because UTF-8 is used in SharpZipLib:

		```
/// <remarks>
		/// The original Zip specification (https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) states 
		/// that file names should only be encoded with IBM Code Page 437 or UTF-8. 
		/// In practice, most zip apps use OEM or system encoding (typically cp437 on Windows). 
		/// Let's be good citizens and default to UTF-8 http://utf8everywhere.org/
		/// </remarks>
		static int defaultCodePage = Encoding.UTF8.CodePage;
```

So there shouldn't be any need for the encoding provider as it is already supported by default in netcore?

**Comment by justinvp** [comment]
The error message you pasted above says:

> System.NotSupportedException : **No data is available for encoding 850**. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.

Is the test setting `DefaultCodePage` to `850`?

**Comment by ViktorHofer** [comment]
You are absolutely right again. Just looked into the test cases and noticed that the DefaultCodePage gets set there to 850 manually:

		```
[Test]
		[Category("Zip")]
		public void UnicodeNameConversion()
		{
			ZipConstants.DefaultCodePage = 850;
```

Thanks for the help!

**Comment by tarekgh** [comment]
https://github.com/icsharpcode/SharpZipLib/blob/master/ICSharpCode.SharpZipLib.Tests/Zip/ZipTests.cs#L2043

**Comment by danmosemsft** [comment]
@weshaggard @terrajobst since this came up today can you confirm that we're okay with this behavioral breaking change? We are relying on some kind of readme for converters, I guess?

This is one of only 2 breaking changes we found so far in our conversion effort of 30 top nuget packages.

@karelz @sepidehMS

**Comment by tarekgh** [comment]
What exactly the breaking change we are talking about here? if you are talking about the encoding, this is the design for net core since day 1. yes it is different than the desktop behavior but we already documented this awhile ago with the workaround.

**Comment by weshaggard** [comment]
Correct this was an intentional design change that so far we haven't found any strong reason to reverse. The exception message already points folks to a doc they can read to figure out how to proceed. This is actually one of the nicest designs when it comes to directing folks what they might need to do.
