### ISSUE TITLE
Feature - ObservableCollections , Linq

### ISSUE THREAD

**Issue by Pinox** [dotnet/corefx#17376]
Not sure if I'm in the right forum for this suggestion.  It will be truly nice if the language team can extend the functionality of ObservableCollections to include functionality to detect when the item properties in the collection change (row change) ,  currently this does not seem possible it detects only add/ removed rows and not updated rows.

UPDATE: To be moved into separate issue:
~~Also, in linq we can't exclude field name in the select statement. `List.Select(x=> new { column1 , column2 })`~~
~~using code first approach in EF it would be seriously nice if we can say "give me all table fields except the byte[] field of 20mb.    By selecting the field names in the current linq scenario changing the database (code first - adding columns) you now always have to remember to add the new columns in the select statements. A better scenario would have included those new fields but still excluded the large byte[] field. `List.SelectAllExcept(x=> new { byte[] columns1 , byte[] column2 })`~~

Using currently .net core 1.1 

 Thks.

**Comment by svick** [comment]
> It will be truly nice if the language team can extend the functionality of ObservableCollections to include functionality to detect when the item properties in the collection change

What is the use case? As far as I know, the primary use case for change notifications is UI binding, and those libraries already know how to detect the changes themselves (assuming the objects implement `INotifyPropertyChanged`).

Also, if the objects do implement `INotifyPropertyChanged`, then writing a custom version of `ObservableCollection` that does this shouldn't be hard. If they don't implement it, I don't see how could the framework do it.

> Also, in linq we can't exclude field name in the select statement.

I'm not sure this is something that makes sense in the general LINQ. On the other hand [EF Core supports explicit `Include`](https://docs.microsoft.com/en-us/ef/core/querying/related-data), so maybe it could make sense if it also supported explicit `Exclude`. In that case, it might make sense to request this feature from [EF](https://github.com/aspnet/EntityFramework).

**Comment by karelz** [comment]
@Pinox please split your issue into 2 - they belong into different areas, involve different people. Let's keep this one only for the 1st part (I'll update your post).

**Comment by Pinox** [comment]
@svick 

"It will be truly nice if the language team can extend the functionality of ObservableCollections to include functionality to detect when the item properties in the collection change

What is the use case? As far as I know, the primary use case for change notifications is UI binding, and those libraries already know how to detect the changes themselves (assuming the objects implement INotifyPropertyChanged)."

I looked at the following code - https://www.codeproject.com/Tips/694370/How-to-Listen-to-Property-Chang

My use case is a listview that represents a  "datagrid" with 8 columns. (UWP desktop app) The data in the columns get updated continuously using server send events from backend.  I would like to use something that only updates the specific "cell" and does not refresh the whole list everytime I receive data from my source. Data in my case is bind to ObservableCollection. Currently no refresh happens as I probably have to use something as in link above.  Just think something like this should be build in as use case must be fairly common using real-time data.  In short a truly observable collection that change the UI when a specific item value change and does not refresh everything in the list.

**Comment by svick** [comment]
@Pinox Do your objects implement `INotifyPropertyChanged` properly? If they do, and you're using bindings correctly, the controls should update when the objects change, no need for changes to `ObservableCollection`.

**Comment by Pinox** [comment]
Hi @svick , not sure I'm following. My listview has semantic zoom and I currently binding to a list collection. I assume your saying I should bind to a class (object) that use INotifyPropertyChanged  property on the individual fields and then bind to a List of these observable object as in MS example - https://msdn.microsoft.com/en-us/library/ms229614(v=vs.110).aspx

**Comment by svick** [comment]
You should bind to an `ObservableCollection` containing objects that implement `INotifyPropertyChanged`. I believe it should work then.

**Comment by Pinox** [comment]
thnks for the advise , much appeciated. Will give it a try.
