### ISSUE TITLE
FormatterServices.GetSafeUninitializedObject

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/corefx#17377]
I've been Googling and reading my way through issues on this repo for nearly an hour now and cannot figure out how to call `FormatterServices.GetSafeUninitializedObject(Type)` from .NET Core.

I've tried adding a reference to every single System.Runtime.* NuGet package and I've tried targeting every single version of .NET Standard and .NET Core App 1.1 to no avail.

Is this API available in .NET Core, and if so, what do I need to do to use it?

Thanks.

**Comment by weshaggard** [comment]
I assume you are referring to FormatterServices.GetUninitializedObject. The API isn't available in .NET Core 1.x but will be available in .NET Core 2.0. see https://apisof.net/catalog/System.Runtime.Serialization.FormatterServices.GetUninitializedObject(Type).

**Comment by karelz** [comment]
It is part of upcoming 2.0:
* Here's how you check availability on various platforms: https://apisof.net/catalog/System.Runtime.Serialization.FormatterServices.GetSafeUninitializedObject(Type)
* Here's dogfooding instructions for 2.0: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md
