### ISSUE TITLE
IPAddress: use Span to support less allocaty IPv6

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#17378]
The IPAddress class has a constructor which accepts a long and an Address property that returns a long:
```c#
IPAddress(Int64)
public long Address { get; set; }
```
This makes it possible to:
- create an IPv4 IPAddress without allocating a byte[] which isn't stored
- retrieve the IPv4 address bytes without allocating a byte[]
- change the IPv4 IPAddress

The property has been deprecated, probably because it doesn't work for IPv6.

We can support these operations for both IPv4 and IPv6 using the Span type:

API Proposal:

```c#
IPAddress(ReadOnlySpan<byte>); // AddressFamily inferred from Span.Length
IPAddress(ReadOnlySpan<byte>, long scopeid); // Span.Length must be IPv6
void GetAddressBytes(Span<byte>); // Span.Length must match AddressFamily*
void SetAddressBytes(ReadOnlySpan<byte>) { SetAddressBytes(bytes, 0); }
void SetAddressBytes(ReadOnlySpan<byte>, long scopeid); // allocates if AddressFamily doesn't match*
bool Equals(ReadOnlySpan<byte>); // Span.Length must match AddressFamily*, scopeid not checked
bool Equals(ReadOnlySpan<byte>, long scopeid); // Span.Length must match AddressFamily*
```
*: special handling for IPv4MappedToIPv6.

**Comment by karelz** [comment]
Span it not yet ready to be sprinkled all over BCL. We are tracking the list of TODOs in #13892.
Once it is ready, we can reopen.

**Comment by karelz** [comment]
Just to clarify: I updated the top post of #13892 to list this proposal as well.

**Comment by tmds** [comment]
@karelz thanks
