### ISSUE TITLE
TransformBlock won't accept async delegate when used with BlockOptions

### ISSUE THREAD

**Issue by tucaz** [dotnet/corefx#1738]
Hello,

This is my first issue raised so forgive me if I'm out of place.

While doing some tests with TPL Dataflow I just noticed what might be a bug. Please consider the following code:

```
async void Main()
{
	var multiplyBlock = new TransformBlock<int, int>(async (int item) => { 
		await Task.Delay(TimeSpan.FromSeconds(item));
		return item * 2;
	});
	
	multiplyBlock.Post(1);
	
	multiplyBlock.Complete();
	await multiplyBlock.Completion;
	
	Console.WriteLine("finished");
}
```

It accepts an async delegate without any problems event if the signature says it should be a Func<int, int>.

However, when you pass a CancellationToken using DataflowBlockOptions it won't compile telling me that it is not possible to convert an async lambda into a Func<int,int>.

```
async void Main()
{
	var cts = new CancellationTokenSource();
	
	var multiplyBlock = new TransformBlock<int, int>(async (int item) => { 
		await Task.Delay(TimeSpan.FromSeconds(item));
		return item * 2;
	}, new DataflowBlockOptions { CancellationToken = cts.Token } );
	
	multiplyBlock.Post(1);
	
	multiplyBlock.Complete();
	await multiplyBlock.Completion;
	
	Console.WriteLine("finished");
}
```

What I can't understand is why it doesn't compile when passing the BlockOptions since the signature is the same. As a bonus to what I don't understand, my first example never gets "finished" written to the console after it's completed.

I'm trying this using LinqPad version 4.56.06 and TPL Dataflow version 4.5.24 from Nuget.

**Comment by svick** [comment]
The actual problem in your code is that [the `TransformBlock` constructor](https://msdn.microsoft.com/en-us/library/hh160345) requires `ExecutionDataflowBlockOptions`, not just `DataflowBlockOptions`. The following code compiles fine for me:

```c#
var multiplyBlock = new TransformBlock<int, int>(async (int item) =>
{
    await Task.Delay(TimeSpan.FromSeconds(item));
    return item * 2;
}, new ExecutionDataflowBlockOptions { CancellationToken = cts.Token });
```

(What you're trying to do logically kind of makes sense, but it's not how inheritance in works in .Net.)

That error message I'm getting from your code is:

> Cannot convert async lambda expression to delegate type '`System.Func<int,int>`'. An async lambda expression may return `void`, `Task` or `Task<T>`, none of which are convertible to '`System.Func<int,int>`'.

That is incredibly confusing and doesn't tell you what the actual error is at all. So while your code doesn't reveal any bug in TPL Dataflow, I think it does reveal a bug in the C# compiler's error messages. Consider reporting that [at the compiler repo](https://github.com/dotnet/roslyn).

**Comment by tucaz** [comment]
Thanks for the thorough reply @svick. The error message I get is exactly the same as yours. 

Unfortunately, I didn't try to use ```DataflowBlockOptions``` consciously, but by mistake because of autocomplete in Visual Studio and failed to find out that it was the incorrect type :(

From what I understand regarding how the compiler infer about types I think it is accepting my wrongly parameter (```DataflowBlockOptions``` instead of ```ExecutionDataflowBlockOptions```) because of inheritance and having problems with the first parameter.

I don't think I am able to judge that this is a compiler bug, but it would be really nice if the message was more helpful and maybe I could have figured it out by myself with a better message.

So, just to make sure I understood everything correctly, a ```TransformationBlock``` block -or any other block with an output queue, for that matter- won't complete until the output queue is cleared by some other block (say ```ActionBlock```) or the block being awaited is a block that does not have an output queue (again, ```ActionBlock```). Is that correct?

**Comment by svick** [comment]
> I don't think I am able to judge that this is a compiler bug

Ok, [I've reported it myself](https://github.com/dotnet/roslyn/issues/2735).

> So, just to make sure I understood everything correctly, a `TransformBlock` block -or any other block with an output queue, for that matter- won't complete until the output queue is cleared by some other block (say `ActionBlock`) or the block being awaited is a block that does not have an output queue (again, `ActionBlock`). Is that correct?

Yes, that's correct.
