### ISSUE TITLE
Process.GetProcessById() is slower than Process.GetProcesses()

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/corefx#17382]
According to the test below, `GetProcessById()` is twice as slow as `GetProcesses()`. I get similar results when testing .NET Framework. Seems like there's room for optimizations in `GetProcessById()`.

Version: dotnet cli version=1.0.1 (.NET Core 4.6.25009.03)

```
            Method |       Mean |    StdDev |
------------------ |----------- |---------- |
    GetProcessById | 19.0449 ms | 0.4639 ms |
 GetProcessesFirst |  9.8138 ms | 0.1876 ms |
  GetProcessesLast |  9.7993 ms | 0.2403 ms |
```

```C#
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

namespace ConsoleApp72 {
	public class Program {
		[Benchmark]
		public void GetProcessById() {
			Process.GetProcessById(0);
		}

		[Benchmark]
		public void GetProcessesFirst() {
			Process.GetProcesses().FirstOrDefault(a => a.Id == a.Id);
		}

		[Benchmark]
		public void GetProcessesLast() {
			Process.GetProcesses().FirstOrDefault(a => a.Id != a.Id);
		}

		static void Main(string[] args) {
			BenchmarkSwitcher.FromAssembly(typeof(Program).GetTypeInfo().Assembly).Run(args);
		}
	}
}
```

**Comment by karelz** [comment]
Did you get chance to profile it and identify the root cause? Do you plan to submit a PR?

Marking up-for-grabs
Complexity: medium (it's perf).

**Comment by stephentoub** [comment]
I believe the issue is the ProcessManager.IsProcessRunning implementation on Windows.  GetProcessById is implemented to check whether the process is running and throw if it's not, and IsProcessRunning is enumerating all of the active processes in order to see if the target ID is contained, so it's effectively doing what GetProcesses() is doing, but more.  We just need a better IsProcessRunning implementation.

**Comment by StanislavUshakov** [comment]
As I reckon it happens because of the diferent impelemntations for GetProcessIds method which differs for local and remote machine:
```csharp
public static int[] GetProcessIds(string machineName)
{
    // Due to the lack of support for EnumModules() on coresysserver, we rely 
    // on PerformanceCounters to get the ProcessIds for both remote desktop
    // and the local machine, unlike Desktop on which we rely on PCs only for 
    // remote machines.
    return IsRemoteMachine(machineName) ?
        NtProcessManager.GetProcessIds(machineName, true) :
        GetProcessIds();
}
``` 
For remote machine PerformanceCounters are used:
```csharp
public static int[] GetProcessIds(string machineName, bool isRemoteMachine)
{
    ProcessInfo[] infos = GetProcessInfos(machineName, isRemoteMachine);
    int[] ids = new int[infos.Length];
    for (int i = 0; i < infos.Length; i++)
        ids[i] = infos[i].ProcessId;
    return ids;
}
```
For local machine we use Interop.Kernel32.EnumProcesses:
```csharp
public static int[] GetProcessIds()
{
            int[] processIds = new int[256];
            int size;
            for (; ; )
            {
                if (!Interop.Kernel32.EnumProcesses(processIds, processIds.Length * 4, out size))
                    throw new Win32Exception();
                if (size == processIds.Length * 4)
                {
                    processIds = new int[processIds.Length * 2];
                    continue;
                }
                break;
            }
            int[] ids = new int[size / 4];
            Array.Copy(processIds, 0, ids, 0, ids.Length);
            return ids;
}
```
I can change implementation for local machine to PerformanceCounters and run test/benchmarks.

**Comment by karelz** [comment]
Are there any differences in corner cases between the 2 approaches? I worry a bit about potential breaking changes.

Is the 10ms speed up worth the effort & the risk? Why does the perf matter so much in this scenario?

**Comment by stephentoub** [comment]
It'd be better still to find a way that didn't involve having to enumerate all of the running processes at all, e.g. a way to ask Windows if a given process is running.

**Comment by 0xd4d** [comment]
@stephentoub  Perhaps [`OpenProcess()`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684320(v=vs.85).aspx) could be used, if it fails (as it will for some processes or invalid pids), use the slower code?

**Comment by StanislavUshakov** [comment]
Or [GetExitCodeProcess](https://msdn.microsoft.com/en-us/library/ms683189(VS.85).aspx) if it is equal STILL_ACTIVE

**Comment by stephentoub** [comment]
> Perhaps OpenProcess() could be used, if it fails (as it will for some processes or invalid pids), use the slower code?

I think this sounds like a reasonable approach.

> Or GetExitCodeProcess if it is equal STILL_ACTIVE

That'd be ok, except that STILL_ACTIVE is a valid exit code.  So we could use this and then fall back to the slower code if the result is STILL_ACTIVE, but for this use case we expect this to be the common case, so it wouldn't really help.

**Comment by StanislavUshakov** [comment]
Unfortunately OpenProcess method uses IsProcessRunning method in ProcessManager.

**Comment by stephentoub** [comment]
> Unfortunately OpenProcess method uses IsProcessRunning method in ProcessManager.

I don't believe @0xd4d was referring to the .NET method.  He's referring to the Win32 function:
https://github.com/dotnet/corefx/blob/c55435befeb372707558a5c441b3c64bf243948f/src/Common/src/Interop/Windows/kernel32/Interop.OpenProcess.cs#L13

**Comment by StanislavUshakov** [comment]
Yes, I understand. I wasn't clear, I meant that we cannot use the clr wrapper.
@stephentoub Can I try to implement this - modify method IsProcessRunning for the local machine and rerun the benchmarks?

**Comment by stephentoub** [comment]
> Can I try to implement this - modify method IsProcessRunning for the local machine and rerun the benchmarks?

Sounds good.

**Comment by riverar** [comment]
This OpenProcess implementation incorrectly assumes a handle is returned for a guaranteed running process, when it can return a handle if the process is zombied and wouldn't normally show up in enumeration.

**Comment by danmosemsft** [comment]
@riverar please open a new issue with details as this is closed
