### ISSUE TITLE
Feature - exclude field name using code-first approach

### ISSUE THREAD

**Issue by Pinox** [dotnet/corefx#17391]
As requested I opened a seperate thread for this request.

In linq we can't exclude field name in the select statement. List.Select(x=> new { column1 , column2 })
using code first approach in EF it would be nice if we can say "give me all table fields except the byte[] field of 20mb. By selecting the field names in the current linq scenario changing the database (code first - adding columns) you now always have to remember to add the new columns in the select statements. A better scenario would have included those new fields but still excluded the large byte[] field. List.SelectAllExcept(x=> new { byte[] columns1 , byte[] column2 })

Using currently .net core 1.1

Thks.

**Comment by svick** [comment]
Reposting my comment from https://github.com/dotnet/corefx/issues/17376:

> Also, in linq we can't exclude field name in the select statement.

I'm not sure this is something that makes sense in the general LINQ. On the other hand [EF Core supports explicit `Include`](https://docs.microsoft.com/en-us/ef/core/querying/related-data), so maybe it could make sense if it also supported explicit `Exclude`. In that case, it might make sense to request this feature from [EF](https://github.com/aspnet/EntityFramework).

**Comment by stephentoub** [comment]
This issue was moved to aspnet/EntityFramework#8138
