### ISSUE TITLE
BitConverter.GetBytes(long value) unaligned memory access

### ISSUE THREAD

**Issue by AronParker** [dotnet/corefx#17401]
As the .NET core supports architectures like ARM where unaligned memory writes can result in a fault, is the following code safe?

```csharp
byte[] bytes = new byte[8];
fixed (byte* b = &bytes[0])
    *((long*)b) = value;
```
[Source](https://github.com/dotnet/corefx/blob/0f2870b1ece429a0cc247b97d830fd55585abf22/src/System.Runtime.Extensions/src/System/BitConverter.cs#L76-L85)

As far as I know the allocator is only guaranteed to return an address aligned on a 32 bit boundary, what if the allocated memory is just 32 bit aligned but not 64 bit aligned? Then there would be a 64 bit write on an unaligned boundary of 32 bit. I am unable to test this because I do not have access to an ARM machine. Does someone know whether this can cause issues?

**Comment by danmosemsft** [comment]
@janvorli

**Comment by janvorli** [comment]
@BruceForstall what would JIT generate here for ARM?

**Comment by BruceForstall** [comment]
Looks like we generate:
```
str     r4, [r3]
str     r5, [r3+4]
```
so, 4 byte writes, since we have 4 byte registers.

On Windows, I don't believe we fault on unaligned stores; perhaps the OS fixes it up. We do try to ensure stores are aligned as much as possible, though.

We respect the cast, so if you change the code to:
```
byte[] bytes = new byte[9];
fixed (byte* b = &bytes[1])
    *((long*)b) = value;
return bytes;
```
we still generate the same instructions, although the address is now unaligned.

**Comment by janvorli** [comment]
So we don't generate strd / ldrd for 64 bit access, right? That means that the code BitConverter.GetBytes should be safe on ARM.

**Comment by BruceForstall** [comment]
Looks like we have support for emitting those instructions, but no code that uses it currently.

**Comment by jkotas** [comment]
Right, .NET Core does not support any architectures that require strict alignment currently. There are number of issues to fix throughout to stack if it ever changes.

If you would like to portable code that is compatible with architectures that require string alignment, you can use Unsafe.Read/WriteUnaligned<T>. Here is example from a test: https://github.com/dotnet/corefx/pull/16570/files#diff-401abe3f2532c0a42128029a72a1240dR583

**Comment by danmosemsft** [comment]
@AronParker is your question answered? if so feel free to close now.

**Comment by AronParker** [comment]
@danmosemsft Yes, sorry and thanks for the insights!
