### ISSUE TITLE
40+ tests failing with coreclr-beta-25122-02

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#17413]
Currently 40+ tests are failing with coreclr-beta-25122-02: 
https://github.com/dotnet/corefx/pull/17406

Thanks to @tarekgh and @joperezr  we found out that it might be connected to https://github.com/dotnet/coreclr/pull/10372.

One of the tests which is failing (ASCIIEncodingTests.cs):

```c#
[Theory]
[MemberData(nameof(Encodings_TestData))]
public void EncodingName(ASCIIEncoding encoding)
{
     Assert.NotEmpty(encoding.EncodingName); // US-ASCII in en-US
}
```

Encoding name property is calling into resources:
```c#
public virtual String EncodingName
{
get
{
return Environment.GetResourceString("Globalization.cp_" + m_codePage.ToString());
}
} 
```

**Comment by danmosemsft** [comment]
Seems the `.` changed to an `_` in the resource name but not in the code

```
Globalization.cp_1200 = Unicode
Globalization.cp_1201 = Unicode (Big-Endian)
Globalization.cp_65001 = Unicode (UTF-8)
Globalization.cp_65000 = Unicode (UTF-7)
Globalization.cp_12000 = Unicode (UTF-32)
Globalization.cp_12001 = Unicode (UTF-32 Big-Endian)
Globalization.cp_20127 = US-ASCII
Globalization.cp_28591 = Western European (ISO)

  <data name="Globalization_cp_1200" xml:space="preserve">
    <value>Unicode</value>
  </data>
  <data name="Globalization_cp_12000" xml:space="preserve">
    <value>Unicode (UTF-32)</value>
  </data>
  <data name="Globalization_cp_12001" xml:space="preserve">
    <value>Unicode (UTF-32 Big-Endian)</value>
  </data>
  <data name="Globalization_cp_1201" xml:space="preserve">
    <value>Unicode (Big-Endian)</value>
  </data>
  <data name="Globalization_cp_20127" xml:space="preserve">
    <value>US-ASCII</value>
  </data>
  <data name="Globalization_cp_28591" xml:space="preserve">
    <value>Western European (ISO)</value>
  </data>
  <data name="Globalization_cp_65000" xml:space="preserve">
    <value>Unicode (UTF-7)</value>
  </data>
  <data name="Globalization_cp_65001" xml:space="preserve">
    <value>Unicode (UTF-8)</value>
  </data>
```

@ViktorHofer my coreclr repo is not building right now, if you want to give this a shot before @alexperovich comes back tomorrow.

**Comment by ViktorHofer** [comment]
Thanks @danmosemsft! I'll take the issue and submit a PR in coreclr ASAP

**Comment by danmosemsft** [comment]
To test your change (run the encoding test with your own corelib), see
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md#testing-with-private-coreclr-bits

**Comment by jkotas** [comment]
I have submitted PR with the fix. There was also another issue in EventSource, and also tests in corefx that party on corelib internals using reflection that have changed will need to be updated (https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Tracing/tests/BasicEventSourceTest/TestsManifestNegative.cs#L36)

**Comment by ViktorHofer** [comment]
@jkotas I will create an issue for it as it depends on the changes from coreclr and the auto PR merges are still failing (some tests).

**Comment by tarekgh** [comment]
Looks this is already fixed by @jkotas.
