### ISSUE TITLE
Coverage report should consider OuterLoop tests

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#1742]
I have a reason to believe that coverage report doesn't count OuterLoop tests.

When looking at:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_coverage_windows/lastStableBuild/Code_Coverage_Report/
I can see test project (I know it shouldn't be on report):
System.Xml.RW.XmlReaderLib
has 0% coverage which is impossible as I'm 100% sure some outer-loop only tests projects are including it and run tests from there (and thus test the test project).

Also ridiculously low Xml.ReaderWriter coverage seems to be confirming it (I know coverage isn't perfect but I'm pretty sure it is much more than 17%).

**Comment by akoeplinger** [comment]
A quick glance at the msbuild log showed `-notrait category=OuterLoop`, so it looks the OuterLoop tests aren't even run.

**Comment by Chrisboh** [comment]
We also have the issue where we can't run InnerLoop and OuterLoop tests at the same time.  We are going to address this issue when fixing issue #1477.  Once that issue is fixed we should be able to easily collect code coverage for both.
