### ISSUE TITLE
alpine RID falls back to linux RID

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#17430]
In our RID fallback graph:

https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json#L571-L576

We list:

```
        "alpine": {
            "#import": [ "linux" ]
        },
        "alpine-x64": {
            "#import": [ "alpine", "linux-x64" ]
        },
```

However, from what I understand, `alpine-x64` isn't compatible with our portable `linux-x64` runtime.  Thus it seems like it shouldn't be listed as a fallback option, because that will cause problems when selecting runtime assets.  If there isn't an asset available for alpine, and an asset that uses a `glibc` is put as a `linux-x64` folder, it will get selected but won't work.

@gkhanna79 @ericstj @janvorli @weshaggard

**Comment by ericstj** [comment]
Just because one package isn't compatible doesn't mean that we should change the mapping.  It just means that package needs to override it. 

Consider that if you look at any single package you might make the same argument: because Foo depends on OS library bar and bar is different between linux distros and alipine then alpine shouldn't parent to linux.  

A counter argument can also be made: for my library I can share my linux-x64 IL library with all linux distros and alpine.  Why do I should I need duplicate it in two folders?

You have to examine the likelihood of the two cases.  If compatibility is at all possible the you might want to allow it to permit breadth / future-proofing.  If it turns out it doesn't work folks can always cross-compile and add a more specific asset.

**Comment by eerhardt** [comment]
Maybe the question turns into, "What does the `linux` RID mean?"

1. The asset could work on some linux distros
2.  The asset will work on all linux distros
3.  The asset will work on what we consider "portable linux" distros - meaning a certain version of glibc, certain kernel version, etc.

I guess with our new portable Linux build, I was assuming `linux` meant number 3.

**Comment by weshaggard** [comment]
I also assumed it meant (3) which would cause trouble for alpine which doesn't support glibc.

**Comment by gkhanna79** [comment]
linux-x64 is actually linux-glibc-x64.

**Comment by mellinoe** [comment]
Related discussion: https://github.com/dotnet/coreclr/issues/9208

We need to fix the rid graph to account for that discussion.

**Comment by mellinoe** [comment]
@karelz Are we not officially supporting Alpine Linux in 2.0?

**Comment by ericstj** [comment]
It means 3 in the context of our runtime packages.

In general it means 1.  Consider that its perfectly valid to do something like have an asset for unix-x64 and osx-x64.  Similar to the way its perfectly valid to have a an asset for netstandard1.0 and an asset for net45.

**Comment by karelz** [comment]
@mellinoe I am not sure - @Petermarcu @gkhanna79 is Alpine officially supported in 2.0? (can't find the support matrix email)

**Comment by Petermarcu** [comment]
We need to fix the rid graph, independent of whether Microsoft officially supports Alpine in 2.0, I want to make sure we're still providing builds for the community that get hooked up correctly.

**Comment by weshaggard** [comment]
We haven't shipped a stable package with this in the graph so we should try and make a call on what we want it to be before we ship 2.0.

**Comment by eerhardt** [comment]
Another thing to note is that we cut alpine builds on corefx and core-setup recently.

See the NOTE here: https://github.com/dotnet/corefx/pull/18035

**Comment by mellinoe** [comment]
Given that we won't produce packages for it, just removing the alpine RID is a viable option. Although, there's no harm in keeping it in, as long as we are comfortable with where it ends up landing in the graph.

**Comment by weshaggard** [comment]
Let's just remove alpine from the RID graph for 2.0 given that we aren't going to support it for 2.0.
