### ISSUE TITLE
System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_AccessInstanceProperties_NoExceptions failing on different environment

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#17439]
In my environment (European timezone, VS17, RS2 build 15063) the following test is failing (tested 2x times also with different clr packages):

```
<test name="System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_AccessInstanceProperties_NoExceptions" type="System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest" method="BasicTest_AccessInstanceProperties_NoExceptions" time="0.1081931" result="Fail">
        <traits>
          <trait name="category" value="nonlinuxtests" />
          <trait name="category" value="nonosxtests" />
          <trait name="category" value="nonfreebsdtests" />
          <trait name="category" value="nonnetbsdtests" />
        </traits>
        <failure exception-type="Xunit.Sdk.InRangeException">
          <message><![CDATA[Assert.InRange() Failure\r\nRange:  (0 - 9223372036854775807)\r\nActual: -1]]></message>
          <stack-trace><![CDATA[   at System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_AccessInstanceProperties_NoExceptions() in C:\Users\vikto\Documents\src\corefx\src\System.Net.NetworkInformation\tests\FunctionalTests\NetworkInterfaceBasicTest.cs:line 46]]></stack-trace>
        </failure>
      </test>
```

It seems they are not failing for @stephentoub. Therefore it might be connected to a different environment.

**Comment by ViktorHofer** [comment]
@danmosemsft commented:

> For the 2nd one, this comment suggests another adapter quirk (maybe returning -1 even when it's "up"?) explaining why it's speicifc to you.

```
                // Validate NIC speed overflow.
                // We've found that certain WiFi adapters will return speed of -1 when not connected.
                Assert.InRange(nic.Speed, nic.OperationalStatus != OperationalStatus.Down ? 0 : -1, long.MaxValue);
```

**Comment by ViktorHofer** [comment]
Thanks @danmosemsft. Hitting the issue with Marvell AVASTAR Wireless-AC Network Controller on a Surface Book. Testing now...

**Comment by ViktorHofer** [comment]
My tests are showing that the nic.Speed property returns -1 for Wi-Fi Direct Virtual Adapters (I guess as their is no speed for those without a Wi-Fi Direct connection):

```
Microsoft Wi-Fi Direct Virtual Adapter #4: Down, -1
Microsoft Wi-Fi Direct Virtual Adapter #5: Up, -1
```

I searched for properties which indicate that the NetworkInterface is virtualized but couldn't find anything.  As @danmosemsft pointed out, the quirk would be to allow -1 even when it is up.

Any thoughts?

**Comment by CIPop** [comment]
Thanks for reporting @ViktorHofer. Feel free to submit a PR changing the test and updating the comment.
WiFi Direct is relatively new and I doubt we've ran the tests when the interface was up. We're discovering a new variation of the possible Win32 API responses that was not captured in a test before.

**Comment by ViktorHofer** [comment]
As for now, I will go the route modifying the allowed speed to -1 as described above. For future references we might consider changing the tests as the api surface grows.

**Comment by karelz** [comment]
Thanks for fixing it @ViktorHofer!

**Comment by CIPop** [comment]
Thanks @ViktorHofer !
