### ISSUE TITLE
System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetAscii_Invalid failing on different environment

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#17433]
In my environment (European timezone, VS17, RS2 build 15063) the following test is failing (tested 2x times also with different clr packages):

```
<test name="System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetAscii_Invalid" type="System.Globalization.Tests.IdnMappingIdnaConformanceTests" method="GetAscii_Invalid" time="0.1277855" result="Fail">
        <failure exception-type="Xunit.Sdk.ThrowsException">
          <message><![CDATA[Assert.Throws() Failure\r\nExpected: typeof(System.ArgumentException)\r\nActual:   (No exception was thrown)]]></message>
          <stack-trace><![CDATA[   at System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetAscii_Invalid() in C:\Users\vikto\Documents\src\corefx\src\System.Globalization.Extensions\tests\IdnMapping\IdnMappingIdnaConformanceTests.cs:line 73]]></stack-trace>
        </failure>
      </test>
```

It seems they are not failing for @stephentoub. Therefore it might be connected to a different environment.

**Comment by danmosemsft** [comment]
@ViktorHofer can you break this into 2 issues? For the first one, it looks like it's looping over a bunch of data, you might want to add a line of code to log which one it's failing on. Unfortunately `Assert.Throws` does not take a message like `Assert.True` does. We try not to have tests do `Console.Write` in the passing case so you might have to modify it to use `Assert.True` instead.

**Comment by danmosemsft** [comment]
For the 2nd one, this comment suggests another adapter quirk (maybe returning -1 even when it's "up"?) explaining why it's speicifc to you.
```
                // Validate NIC speed overflow.
                // We've found that certain WiFi adapters will return speed of -1 when not connected.
                Assert.InRange(nic.Speed, nic.OperationalStatus != OperationalStatus.Down ? 0 : -1, long.MaxValue);
```

**Comment by ViktorHofer** [comment]
Thanks @danmosemsft. I'm investigating...

**Comment by tarekgh** [comment]
We depend on the OS for the IDN so there could be a changes in RS2 or so. if you can get me the failing case I can try to confirm that with Windows team.

**Comment by ViktorHofer** [comment]
"corefx\src\System.Globalization.Extensions\tests\IdnMapping\Data\Unicode_6_0\IdnaTest_6.txt" line number 769 is the culprit.

> B;	XN--CMBA;	\u06EF\u06EF;	xn--cmba

This line is NOT failing for me. As the comments say, some other lines were commented out for Win8.1. Should we also just comment it out or look for the reason why entry.GetASCIIResult.Success is false but not throwing an ArgumentException when passing it to the IdnMapping: 
`IdnMapping.GetAscii(entry.Source)`

**Comment by ViktorHofer** [comment]
@tarekgh just updated the same time you did. please find the failing case in my previous respone

**Comment by tarekgh** [comment]
I'll try to take a look and get back to you. thank you.

**Comment by tarekgh** [comment]
@ViktorHofer the line 769 in the file IdnaTest_6.txt conatins 

```
\uD802\uDDF2.---\u06A5\u07D2;	[P1 V6 V3 B1];	[P1 V6 V3 B1]
```

https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Globalization.Extensions/tests/IdnMapping/Data/Unicode_6_0/IdnaTest_6.txt#L769

Could you please confirm this is the line which is failing or the other line you said contains 

```
B;	XN--CMBA;	\u06EF\u06EF;	xn--cmb
```

https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Globalization.Extensions/tests/IdnMapping/Data/Unicode_6_0/IdnaTest_6.txt#L510

**Comment by ViktorHofer** [comment]
You are right:
`B;	\uD802\uDDF2.---\u06A5\u07D2;	[P1 V6 V3 B1];	[P1 V6 V3 B1]`

**Comment by tarekgh** [comment]
@ViktorHofer I am not able to repro it either. could you please run the following 2 lines in a desktop console app on the same failing machine and let me know if you'll get exception or not? 

```C#
            var map = new IdnMapping();
            Console.WriteLine(map.GetAscii("\uD802\uDDF2"));
```

**Comment by ViktorHofer** [comment]
With netfx46 console application it works as expected. Console prints "xn--tq9c"

**Comment by ViktorHofer** [comment]
Yeah I will take it. Should I create a new Textfile like for Win7?

**Comment by tarekgh** [comment]
under the folder 

https://github.com/dotnet/corefx/tree/master/src/System.Globalization.Extensions/tests/IdnMapping/Data

create a new sub-folder and name it Unicode_9_0 and then copy the contents of the folder Unicode_6_0 to the new folder then override the files IdnaTest_6.txt and ReadMe.txt from http://www.unicode.org/Public/idna/9.0.0/

then you rename the file Unicode_6_0_IdnaTest.cs to Unicode_9_0_IdnaTest.cs and update the code to work as expected with the new version. 

then update the code in the following lines to have some check to detect loading the new data files

https://github.com/dotnet/corefx/blob/master/src/System.Globalization.Extensions/tests/IdnMapping/Data/Factory.cs
https://github.com/dotnet/corefx/blob/master/src/System.Globalization.Extensions/tests/IdnMapping/Data/Factory.cs#L67

the detection can be done using the 2 lines of code 

```C#
            var map = new IdnMapping();
            map.GetAscii("\uD802\uDDF2")
```

if this code throw then we use v6.0 otherwise we use v9.0 

last you need to update the test csproj to include the new added data and source files. 

let me know if you have any question. thanks

**Comment by ViktorHofer** [comment]
Thanks @tarekgh. Wouldn't it make more sense - also performance wise - to not test the Unicode version by catching but by checking the windows version?

**Comment by tarekgh** [comment]
> Thanks @tarekgh. Wouldn't it make more sense - also performance-wise - not testing the Unicode version by catching but by checking the windows version?

That will be perfect when we ship. currently I am expecting some RS2 builds have the update and some are not. this is why I am conservative checking the OS version now. but if you feel strong about it we can give it a try and look what we'll get.

**Comment by ViktorHofer** [comment]
@tarekgh Perfect, yeah let's try. I will start with that by tomorrow, just one more question: If I need some more infos from the Windows team, especially when it comes to the versions, who should I contact?

**Comment by tarekgh** [comment]
you can just use the same idea as we do in 

https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/PlatformDetection.cs#L26

just get Windows version from your machine and try to use it.

**Comment by ViktorHofer** [comment]
Finished implementation of "test adapter" for Unicode 9. Problematic is that a lot of tests fail and it seems this "by design" on Windows... I would like to check with the Windows team if their implementation is "stable" on the current version I'm using (15063) as I already spent several hours to finding a cause.

For v6 a lot of entries in the test file are commented out as they are not working on Windows. Maybe that's enough, but I just want to make sure

**Comment by tarekgh** [comment]
Ye please follow up with Windows team. thanks.
