### ISSUE TITLE
Language proposal for C# vNext (8?)

### ISSUE THREAD

**Issue by jterry75** [dotnet/corefx#17449]
I find myself always writing code like:

```C#
enum States
{
    On,
    Off,
    InBetween
}

class Example
{
    public States State { get; }
}

class Program
{
    public static void Main(string[] args)
    {
        var t = new Example();
        // ...
        if (t.State == States.On || t.State == States.InBetween) // <- Interested here.
        {
             // Do something.
        }
    }
}
```

What if C# had an addition specifically for enum types to match as a language feature.
```C#
var t = new Example()
// ...
if (t.State.Is(On, InBetween)
{
    // Do Something
}
```

I can imagine that this has a few helpful optimizations. For 1 we only need to actually call `.State` once which means that we know the multiple calls are side-effect-free but for 2 we can actually infer the enum type exactly so we dont need its qualifiers.

```C#
enum WowWeWriteExtreemlyDescriptiveEnumNames
{
    A,
    B,
    C
}

var z = WowWeWriteExtremelyDescriptiveEnumNames.A;
// ...
if (z == WowWeWriteExtremelyDescriptiveEnumNames.A || 
    z == WowWeWriteExtremelyDescriptiveEnumNames.B)
{
    // Do Work
}
```
Goes to
```C#
if (z.Is(A, B))
{
    // Do Work
}
```

You could imagine for `[Flags]` enums we could match based on logical operation:
```C#
[Flags]
enum Test
{
    None = 0x0,
    A = 0x1,
    B = 0x2,
    C = 0x4
}

if (z.Is(A, B || C))
{
    // Do work
}
```

Ideas?

**Comment by danmosemsft** [comment]
@jterry75 thanks for the contribution. I'll move to what I think is the right repo
https://github.com/dotnet/roslyn

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/roslyn #18126](https://github.com/dotnet/roslyn/issues/18126) via [**ZenHub**](https://www.zenhub.com/)
