### ISSUE TITLE
Question: Calling Mac OS X Native APIs from .NET Core

### ISSUE THREAD

**Issue by pcgeek86** [dotnet/corefx#17454]
Hello,

I'd like to call Mac OS X native APIs from .NET Core. More specifically, I'm interested in calling the [IOPowerSource()](https://developer.apple.com/reference/iokit/iopowersources.h) API to get the battery charging status on a MacBook Pro running Mac OS X Sierra.

http://stackoverflow.com/questions/5751132/mac-get-battery-charging-status-plugged-in-or-not

**Edit**: The question is: How do I actually do this?

Cheers,
Trevor Sullivan

**Comment by karelz** [comment]
Did you try to use just PInvokes?
Here's example of Mac specific PInvokes in our code: https://github.com/dotnet/corefx/blob/master/src/Common/src/Interop/OSX/System.Security.Cryptography.Native.Apple/Interop.Ecc.cs

**Comment by W19117225a** [comment]
H
