### ISSUE TITLE
System.Runtime PointerFieldGetValue test is failfasting in Assert.IsType

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#17450]
tests [Sort_Array_Array_NonGeneric](https://github.com/dotnet/corefx/blob/15b4f51c2f3cb924840e5407bb8d5fe03bb282ea/src/System.Runtime/tests/System/ArrayTests.cs#L2909) and [PointerFieldGetValue](https://github.com/dotnet/corefx/blob/7f6ac8bf97a84666ed3e7ef6b77c1a9470ae78c8/src/System.Runtime/tests/System/Reflection/PointerTests.cs#L118) are crashing the uapaot test execution when throwing a Debug.Assert.

To get a repro locally, do the following:
 - Remove the `SkipOnTargetFramework` attribute on the tests
 - call `build.cmd -framework:uapaot`
 - `msbuild src\System.Runtime\tests\System.Runtime.Tests.csproj /p:TargetGroup=uapaot /t:rebuildAndTest /p:TestILCFolder=<path to ilc>`

**Comment by karelz** [comment]
@joperezr why is it up-for-grabs? It does not seem to be actionable for community, given our state of UWP testing in the open ...

**Comment by joperezr** [comment]
You are right, I marked it that way because System.Runtime tests can now run on uapaot, but as you point out we can't test them in the open.

**Comment by karelz** [comment]
Thanks!

**Comment by tijoytom** [comment]
@joperezr Do we know why it do Debug.Assert , if we can find that the right person can be engaged.

**Comment by joperezr** [comment]
One of the tests disabled by this issue is now passing so some other change must have fixed it, but the `PointerFieldGetValue` is still crashing throwing an AV when `value` is `-1`. There is not an interesting callstack since all that is really happening, is that we are calling Xunit's `Assert.IsType<Pointer>(actualValue)` and `actualValue` is an `System.Object &`. I don't have xunit symbols, so I can't really tell which PInvoke is causing this.
Callstack is:
```
KernelBase.dll!RaiseFailFastException()
xunit.console.netcore.dll!$79___Interop::kernel32_dll.PInvoke_RaiseFailFastException(Interop::_EXCEPTION_RECORD * pExceptionRecord=0x0000008b88ff9f38, System::IntPtr pContextRecord={...}, unsigned int dwFlags=1) Line 1061
xunit.console.netcore.dll!Interop::mincore.PInvoke_RaiseFailFastException(Interop::_EXCEPTION_RECORD * pExceptionRecord=0x0000008b88ff9f38, System::IntPtr pContextRecord={...}, unsigned int dwFlags=1)
xunit.console.netcore.dll!Interop::mincore.RaiseFailFastException(unsigned int faultCode=2147500037, System::IntPtr pExAddress={...}, System::IntPtr pExContext={...}) Line 123
xunit.console.netcore.dll!System::RuntimeExceptionHelpers.FailFast(System::String & message={...}, System::Exception & exception, System::RuntimeExceptionHelpers::RhFailFastReason reason=Unknown, System::IntPtr pExAddress={...}, System::IntPtr pExContext={...}) Line 236
xunit.console.netcore.dll!System::RuntimeExceptionHelpers.FailFast(System::String & message={...}) Line 134
xunit.console.netcore.dll!System::RuntimeExceptionHelpers.GetRuntimeException(System::Runtime::ExceptionIDs id=AccessViolation) Line 78
mrt100_app.dll!00007ffe6c25df85()
mrt100_app.dll!00007ffe6c25e045()
mrt100_app.dll!00007ffe6c264105()
xunit.console.netcore.dll!$78_Xunit::Assert.IsType(System::Type & expectedType={...}, System::Object & object) Line 87
xunit.console.netcore.dll!$78_Xunit::Assert.IsType<System.__Canon>(System::Object & InstParam=0x00007ffe2960c8a8) Line 71
xunit.console.netcore.dll!$56_System::Reflection::Tests::PointerTests.PointerFieldGetValue(int value=-1) Line 127
```

**Comment by joperezr** [comment]
re-assigning to you so that you can forward it to the right person.
