### ISSUE TITLE
UWP: System.Net.HttpListener

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#17462]
Move UAP to use the 100% managed HttpListener implementation in corefx\src\System.Net.HttpListener\src\System\Net\Managed as Unix does rather than the Windows one.

This should eliminate calls to the API's below and they can come out of the pinvoke baseline.
```
httpapi.dll!HttpAddUrlToUrlGroup
httpapi.dll!HttpCancelHttpRequest
httpapi.dll!HttpCloseRequestQueue
httpapi.dll!HttpCloseServerSession
httpapi.dll!HttpCloseUrlGroup
httpapi.dll!HttpCreateRequestQueue
httpapi.dll!HttpCreateServerSession
httpapi.dll!HttpCreateUrlGroup
httpapi.dll!HttpReceiveClientCertificate
httpapi.dll!HttpReceiveHttpRequest
httpapi.dll!HttpReceiveRequestEntityBody
httpapi.dll!HttpRemoveUrlFromUrlGroup
httpapi.dll!HttpSendHttpResponse
httpapi.dll!HttpSendResponseEntityBody
httpapi.dll!HttpSetUrlGroupProperty
httpapi.dll!HttpWaitForDisconnect
```

@Priya91 correct me if this is not the plan.

**Comment by geoffkizer** [comment]
Is this the plan?  My understanding is that managed HttpListener does not provide 100% feature parity.

**Comment by danmosemsft** [comment]
@davidsh @CIPop @stephentoub @karelz also. There was a thread on this last year -- need to determine whether to make whitelist requests

**Comment by stephentoub** [comment]
> My understanding is that managed HttpListener does not provide 100% feature parity.

It's also hard to know exactly where we are on parity, as we have extremely low test coverage right now, unfortunately.

**Comment by CIPop** [comment]
>  There was a thread on this last year -- need to determine whether to make whitelist requests

@danmosemsft, @geoffkizer  We did make requests and the answer was no.
If we look for feature parity with .Net Framework, that cannot be achieved with the current plan (e.g. HTTP2.0). If we look for parity with Mono, it should be very close to 100%.

**Comment by Priya91** [comment]
Currently https requests are not supported from managed Httplistener, since we don't have a way to get the certs for Unix. Tracked with #14691. This is the missing feature from Mono.

On UWP, we can leverage the windows cert store, and incorporate this to managed listener.

**Comment by danmosemsft** [comment]
If we had this missing feature, would we consider moving regular Windows over to the managed implementation? or are there more deficiencies/ performance compromises?

**Comment by Priya91** [comment]
>  or are there more deficiencies/ performance compromises?

We don't have the perf numbers to compare, but @stephentoub had already found areas where perf could be better. But we haven't invested in Httplistener, since it's considered legacy and only for compat purposes. So, there's no motivation in moving core windows implementation to managed. For UWP as well, I think this is just for compat purposes, and recommended APIs would be in asp.net. @CIPop @davidsh can correct me if i'm wrong..

**Comment by danmosemsft** [comment]
We are asking for the API, that keeps our options open.
