### ISSUE TITLE
Code Guidelines for VB.net contributions.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/corefx#17478]
The current coding guidelines are C-centric, with no or very little guideline for VB.net contributions, for projects within the .NET Foundation that use the language within their project. Thus lack of clear guidelines has and will cause friction between different opinions on stylistic aspects of the code / contribution, rather that the functional / semantic behavior of the code.

I'm working on implementing a VBnet Coding guideline. ([Here](https://github.com/AdamSpeight2008/Ideas/blob/master/VBCodingGuidelines.md))

**Comment by svick** [comment]
Out of curiosity, what .Net Foundation projects use VB, apart from the VB portion of Roslyn?

**Comment by AdamSpeight2008** [comment]
We should not have bias to the ,net language used within projects, and welcome them into the .net foundation family of contributors. Should such a project be warmed by the foundation.

**Comment by JonHanna** [comment]
@svick there's a few VB bits here in corefx too, though not much.

**Comment by karelz** [comment]
@AdamSpeight2008 where are the Foundation-wide coding styles? Are they in CoreFX repo?
Where are they linked from Foundation-wide?

**Comment by AdamSpeight2008** [comment]
@karelz  Of those I've seen use the CoreFX coding guideline as the basis of them.

**Comment by karelz** [comment]
Is it just the most popular coding guideline, or is there official link from some Foundation-wide repo/doc?
Can you post link to the C# code guidelines in CoreFX repo (to make sure we are talking about the same thing) and where it is linked from Foundation-wide?

IMO the key value of coding guidelines is to set common rules in a repo for day-to-day development. Given that we have [only 27 vb files](https://github.com/dotnet/corefx/search?l=Visual+Basic&q=%22End+Namespace%22&type=&utf8=%E2%9C%93) in CoreFX (and [not very active](https://github.com/dotnet/corefx/tree/bffef76f6af208e2042a2f27bc081ee908bb390b/src/Microsoft.VisualBasic/src)), I don't think we need VB coding styles in CoreFX repo. IMO it's a bad fit and would just add overhead for maintenance which is not valuable in CoreFX.

I think it would be best to add such VB coding guidelines in a place where they are needed -- to some VB-heavy repo. That way they can be battle-tested there before considered a "standard"/becoming more popular, the same way CoreFX C# coding guidelines were battle-tested in CoreFX (even prior to open sourcing) and became popular on their own.

**Comment by AdamSpeight2008** [comment]
CoreFx [Coding Guidelines](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md)

**Comment by karelz** [comment]
Thanks! Do you have a link(s) which make it .NET Foundation "standard coding guideline"?

**Comment by AdamSpeight2008** [comment]
@karelz Not one that says that explicitly, but could be interpreted as that. 
**Note** I've bold the parts of the text, the original contains no bold.
>The Roslyn project is **a member of the .NET Foundation and follow the same developer guide**. The team enforces this by regularly running the .NET code formatter tool on the code base. Contributors should ensure they **follow these guidelines** when making submissions. 

[link](https://github.com/dotnet/roslyn/wiki/Contributing-Code)

**Comment by karelz** [comment]
Thanks, the link helps.

Roslyn seems to have much more .vb source code ([~3,000](https://github.com/dotnet/roslyn/search?l=Visual+Basic&q=%22End+Namespace%22&type=&utf8=%E2%9C%93)), although most of them likely tests.

I interpret the text above (and its placement on Roslyn repo) as a soft standard. Kind of opt-in / suggestion for .NET Foundation projects. I think it was created by need on CoreFX and Roslyn repos and aligned there.
I would suggest to let VB coding guidelines grow in the same way, from the need. You might try to ask on Roslyn repo if they re interested to expand their [VB coding rules](https://github.com/dotnet/roslyn/wiki/Contributing-Code#visual-basic-conventions) into a full-blown text.

Overall I don't think the VB guidelines belong to CoreFX and as such I would suggest to close this issue here.
