### ISSUE TITLE
macOS builds failing with non-null compiler error

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#17487]
e.g. https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug_prtest/557/
```
/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest/src/Native/Unix/System.Security.Cryptography.Native.Apple/pal_keychain.cpp:253:117: error: null passed to a callee that requires a non-null argument [-Werror,-Wnonnull]
            SecKeychainItemCreateCopy(reinterpret_cast<SecKeychainItemRef>(privateKey), keychain, nullptr, &itemCopy);
                                                                                                  ~~~~~~~           ^
/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest/src/Native/Unix/System.Security.Cryptography.Native.Apple/pal_keychain.cpp:272:116: error: null passed to a callee that requires a non-null argument [-Werror,-Wnonnull]
        status = SecKeychainItemCreateCopy(reinterpret_cast<SecKeychainItemRef>(cert), keychain, nullptr, &itemCopy);
```

**Comment by bartonjs** [comment]
I don't suppose we have any idea why it started failing out of the blue?  That code hasn't changed in a while (and just built clean on my mac)

**Comment by stephentoub** [comment]
I think it might be an issue on only a subset of the machines; it's failing inconsistently, which is strange for a compilation error.  Maybe one or more of the machines has a different tool set?

**Comment by bartonjs** [comment]
dci-mac-build-052 - failed
dci-mac-build-051 - failed
dci-mac-build-043 - succeeded

@ellismg says that he had similar build failures on his mac when it was running 10.11.  I wonder if the two that are failing are somehow now upgraded.

**Comment by stephentoub** [comment]
>  I wonder if the two that are failing are somehow not upgraded

They're not... uname -r shows Darwin kernel version 15.6.0, which is El Capitan rather than Sierra. @mmitche, can you help fixing this?

**Comment by mmitche** [comment]
@ilyas1974 Did some of the machine accidentally not get reimaged with the correct image?

I'll take some of these offline for now

**Comment by stephentoub** [comment]
Thanks, @mmitche.

**Comment by mmitche** [comment]
@ilyas1974 51-55 didn't get reimaged.  Rest list 10.12.3

**Comment by tintoy** [comment]
Is Sierra now required to build corefx on OSX? I hope not, as I don't really want to have to upgrade (stuff always breaks) :-/

I'm on El Capitan (OSX 10.11.6 / Kernel 15.6.0), and I can no longer build corefx either (I get this same message). It used to work just fine.

**Comment by ellismg** [comment]
> Is Sierra now required to build corefx on OSX? I hope not, as I don't really want to have to upgrade (stuff always breaks) :-/

Yes.  In addition, Sierra is now a runtime dependency as well (we are using apple's new crypto libraries instead of OpenSSL and that forces a dependency on 10.12, unfortunately).

**Comment by tintoy** [comment]
Ugh. That... That kinda sucks. I understand _why_ but it means this is the end of my contributions to corefx until I can get hold of a decent machine that can run Windows :-(

Oh well, time to start saving up for a new laptop.

**Comment by tintoy** [comment]
(thanks for the quick reply, though, that's saved me a lot of troubleshooting!)

**Comment by ellismg** [comment]
> (thanks for the quick reply, though, that's saved me a lot of troubleshooting!)

No problem, I agree the situation sucks, as someone with a MacBook at home that can't upgrade to 10.12, I feel your pain.

**Comment by tintoy** [comment]
TBF, I've been looking for an excuse to buy a new laptop, and you've delivered me one :)

**Comment by mellinoe** [comment]
@mmitche Has this been fixed on the lab machines since this was filed? I don't think we've still been seeing it.

**Comment by mmitche** [comment]
@mellinoe Yeah.
