### ISSUE TITLE
Missing underscore in Framework Design Guidelines Digest wiki example

### ISSUE THREAD

**Issue by nohwnd** [dotnet/corefx#1748]
In the [Naming Guidelines](https://github.com/dotnet/corefx/wiki/Framework-Design-Guidelines-Digest#naming-guidelines) section of the Framework Design Guidelines Digest the last example in the first **DO** is missing an underscore. It says `Text color`, which is not a valid identificator, rather than `Text_color` that is used in the book.

**Comment by KrzysztofCwalina** [comment]
Thanks for catching this. 
Fixed!
