### ISSUE TITLE
ILC fails when trying to compile an array of pointers

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#17480]
PR #17446 added an ifdef that removes some tests in System.Runtime given that ILC would fail when trying to compile, by saying that Array of pointers type is not supported. This needs to be fixed externally. This issue is so that we track the remaining work on our side of uncommenting those tests for uapaot once ILC is fixed.

cc: @jkotas @morganbr

**Comment by morganbr** [comment]
@MichalStrehovsky is working toward some of this support.

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky is working toward some of this support.

I can look into enabling it on the CoreRT compiler and fixing up CoreLib (basically, go over all the places where we could end up doing `RhBox` on an element of an array without checking what it is), but someone will need to go fix up NUTC (or binder?) to do the right thing in terms of interfaces implemented by these types. It won't help UWP otherwise.

**Comment by karelz** [comment]
@joperezr why is it up-for-grabs? It does not seem to be actionable for community, given our state of ILC testing in the open ...

**Comment by tijoytom** [comment]
@MichalStrehovsky is this fixed? If not , can we open a TFS issue and clsoe this one?

**Comment by MichalStrehovsky** [comment]
I fixed it at the BCL side, runtime side, and CoreRT compiler side. NUTC/binder would be @davidwrighton area.

**Comment by davidwrighton** [comment]
Fix for this is in progress.

**Comment by davidwrighton** [comment]
.NET Native side of work is complete. On next update the tests can be updated to run again.

**Comment by danmosemsft** [comment]
@safern I'm guessing we have ingested this fix, maybe see whether the tests can be reenabled?

**Comment by safern** [comment]
Yes, I will test it locally and if so reenable and close this issue.

**Comment by joperezr** [comment]
already opened a PR for it #21721
