### ISSUE TITLE
Request for new API: System.Diagnostics.Process.CreationFlags

### ISSUE THREAD

**Issue by PaulHigin** [dotnet/corefx#17481]
This is a request for a new CreationFlags property that is identical to creation flags in Windows native API CreateProcess().  This needs to work appropriately for Windows and Linux platforms but should work identically for the CREATE_NEW_PROCESS_GROUP flag since process groups are similar between the two platforms.

Proposed API
---------------
CreationFlags property is of type CreationFlags that is an enum of supported creation flags
```
public CreationFlags System.Diagnostics.Process.CreationFlags { get; set; }

[Flags]
public enum CreationFlags
{
    CREATE_NEW_CONSOLE = 0x00000010,
    **CREATE_NEW_PROCESS_GROUP = 0x00000200**,
    CREATE_BREAKAWAY_FROM_JOB = 0x010000000,
    CREATE_DEFAULT_ERROR_MODE = 0x04000000,
    ...
};
```
Please see issue (https://github.com/dotnet/corefx/issues/17412) for rationale and discussion

**Comment by karelz** [comment]
Please post it as reply in the original issue #17412 - no point in having 2 dupes tracking the same thing.
