### ISSUE TITLE
System.TypeLoadException: 'Could not resolve type 'System.AppContext' 

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#17486]
I was trying to build serialization tests in CoreFx against uapaot. Sg.exe failed to resolve System.AppContext, which caused error when building the tests. Here's the error message,

```
System.TypeLoadException occurred
  HResult=0x80131522
  Message=Could not resolve type 'System.AppContext' in assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
  Source=mscorlib
  StackTrace:
   at System.TypeNameParser.ResolveType(Assembly assembly, String[] names, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark) in f:\dd\ndp\clr\src\BCL\system\typenameparser.cs:line 303
```

Is `System.AppContext` not available on uapaot?

**Comment by jkotas** [comment]
cc @DnlHarvey

**Comment by shmao** [comment]
Closing the issue as the failure did not repro anymore.

**Comment by myesn** [comment]
@shmao Hello, I then winserver2008 deployment also found this problem, how to solve it? Thank you！

**Comment by shmao** [comment]
Hi @myesn , the original bug tracked by this issue was found prior to the product release and was fixed. The error message you got may be identical with the error here, but I doubt they are the same issue.

Can you please provide more information regarding to the issue you're seeing? Please feel free to open a new issue for the problem you're having for better tracking.

**Comment by myesn** [comment]
@shmao  #13504 After I installed .Net Framework 4.6.1, the problem was solved, thanks!
