### ISSUE TITLE
System.IO.Path.GetInvalidPathChars() returns different result than Desktop

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#17490]
When running the following test using SharpZipLib NuGet package, I realized `GetInvalidPathChars()` returns a smaller set of characters compared to Desktop. Was this change of behavior intentional?

```
WindowsNameTransform wnt = new WindowsNameTransform();
wnt.TrimIncomingPaths = false;
Assert.Equal(@"c\_", wnt.TransformFile("c\\/>"));
```

`wnt.TransformFile("c\\/>")` returns `"c\>"` on .NET Core 2.0.

**Comment by danmosemsft** [comment]
This was changed in https://github.com/dotnet/corefx/pull/8669 
related https://github.com/dotnet/coreclr/pull/3942

So I think it's interntional.

fyi @JeremyKuhne .. this broke a test, not an actual library so I guess we're OK with it.
