### ISSUE TITLE
ASP.NET core AppContext.BaseDirectory is not the real "base" in development environment

### ISSUE THREAD

**Issue by Deren-Liao** [dotnet/corefx#17496]
I have a config file as sibling with web.config.  
When deployed, AppContext.BaseDirectory  get me the right path to the file. 
When debugging it within Visual Studio, then it takes me to the bin\ folder .    
I am not able to debug it within VS if I use the API.

**Comment by karelz** [comment]
Are you using .NET Core? There are no config files in .NET Core AFAIK.
If you use "Desktop" .NET Framework, then this is not the right place to ask -- use Microsoft support in such case, or various Forums/StackOverflow are sometimes helpful.

**Comment by Deren-Liao** [comment]
Yes, ASP.NET CORE as title said.  I think you referred to dot net configuration manager.    Config file does not necessary be a .NET supported config file.

**Comment by davidfowl** [comment]
Yes this is accurate. The application base can only be changed by the native host and there is no ASP.NET net specific native host. ASP.NET uses the `IHostingEnvironment.ContentRoot` for configuration files. You *can* always mark your configuration files as `CopyToOutput="true"` in your project file to get them in the right location at build time.

**Comment by karelz** [comment]
This sounds like ASP.NET Core question/problem, not CoreFX. Is that accurate?

If yes, can we close it here? Potentially move it into another repo? ... (sorry if it sounds stupid, I still didn't quite get what the question is about and where it belongs in the end-to-end)

**Comment by Deren-Liao** [comment]
Maybe it is more an ASP.NET core problem.  You can close it.

**Comment by karelz** [comment]
Thanks for confirmation.
