### ISSUE TITLE
Add TempFileCollection or something similar

### ISSUE THREAD

**Issue by niklaskarl** [dotnet/corefx#17497]
I always liked the idea behind the [TempFileCollection](https://msdn.microsoft.com/en-us/library/system.codedom.compiler.tempfilecollection(v=vs.110).aspx) class. It tackles some common problems, often faced when working with temporary files:

- Simple management of multiple temporary files belonging together
- Reliable creation of temporary files with specific extensions
- Easy release (deletion) of all generated temporary files when no longer needed with the dispose pattern

Therefore I propose to add a class with similar functionality to corefx. Such a class could reside in the _System.IO_ namespace even though I don't see it quite fitting as its use case is too specific to belong to such a widely used namespace.

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/blob/e11d6ed334725a8332ef81df195a5c35d48eb967/src/Common/src/System/IO/TempFileCollection.cs

**Comment by karelz** [comment]
Closing as it already exists. Please let me know if I missed some angle which is not covered.
