### ISSUE TITLE
Could not load file or assembly 'System.Net.Http in ASP NET CORE

### ISSUE THREAD

**Issue by parismiguel** [dotnet/corefx#17523]
Hi @karelz , I've been researching and working two nights in a row so far but I'm not able to fix this. All my System.Net.Http packages have been updated to version 4.3.1 but still get the same error.

My project is a NET Core project build using Visual Studio 2017 template

Please help me, I don't know what else to try or where to go. Thanks!

FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

![image 1](https://cloud.githubusercontent.com/assets/8812746/24325625/9e4a8852-116a-11e7-837e-d1483a5bec1b.jpg)

[IbmVcaCore.csproj.txt](https://github.com/dotnet/corefx/files/870320/IbmVcaCore.csproj.txt)

**Comment by karelz** [comment]
Thanks for moving it here from #11100!

Did you check if the assembly is part of your application? Is it the right assembly version?
That's my best bet that it is what's going on with your .NET Core app.

Other options: Try to downgrade to NuGet package 4.3.0. Does that work?

**Comment by karelz** [comment]
You should check out the content in your application folder -- where the binaries live. Not VS project (which I think you're doing based on your screenshot).
Run: `C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\ildasm.exe YouAppPath\System.Net.Http.dll`
In the buttom part of the window you will see something like:
```
.assembly System.Net.Http
{
  .ver 4:1:0:0
}
```
What does the version say?

**Comment by parismiguel** [comment]
OK... I've achieved to run the program provided but I'm not sure what the path is... Visual Studio installation path, Windows System path or my project path? I've looked at my project's path but i can't find any file named System.Net.Http.dll

**Comment by parismiguel** [comment]
I've found this: C:\Windows\Microsoft.NET\Framework\v4.0.30319\System.Net.Http.dll

.assembly System.Net.Http
{
  .ver 4:0:0:0
}

**Comment by karelz** [comment]
NuGet has to put it into your application path. Check there. If it is not there, something is horribly broken.
Try a new app, HelloWorld. Check it there to find out if it is one project problem or machine/installation problem.

The one you found is part of Desktop .NET Framework. Nothing from there should be loaded into your process. Check it via ProcessExplorer tool on your running app.

**Comment by parismiguel** [comment]
Well, I've created a brand new project using VS 2017 and ASP NET Web Core with authentication.... no traces of System.Net.Http at all... I'm suspicious about VS 2017... really tempted to go back to VS 2015...

![image 4](https://cloud.githubusercontent.com/assets/8812746/24326640/adf71e12-1180-11e7-95b0-18231b7d7c94.jpg)
![image 5](https://cloud.githubusercontent.com/assets/8812746/24326639/adf6edde-1180-11e7-8890-5c3cadac1190.jpg)

**Comment by karelz** [comment]
Which template did you use? The one for .NET Core or the one for .NET Framework (Desktop)?
I don't see the System.Net.Http NuGet in your screenshot, so maybe that's why it is not there ...

**Comment by parismiguel** [comment]
The web one...
I've also tried to install the system.net.http library using nuget but I'm not able to see any file using windows explorer under my project's root folder.

![image 6](https://cloud.githubusercontent.com/assets/8812746/24326699/15368a6c-1182-11e7-822d-5da7eedb86f3.jpg)

![image 7](https://cloud.githubusercontent.com/assets/8812746/24326713/796d985e-1182-11e7-80b2-e3c5dba774e6.jpg)

**Comment by karelz** [comment]
I just tried that, chose "Web Application" in the wizard. Added this line int About.cshtml:
```c#
ViewData["Message"] = typeof(System.Net.Http.HttpClient).AssemblyQualifiedName;
```
And I get the right answer:
System.Net.Http.HttpClient, System.Net.Http, Version=**4.1.1.0**, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

**Comment by karelz** [comment]
BTW: I didn't see the Entity Framework NuGet references. Did you try new vanilla web project?

**Comment by parismiguel** [comment]
Wish I could try for myself but I've decided to install vs 2015 update 3, for that reason, i'm n ot able right now to open my ide. I assume that, if everything is ok in your side then, my ide either is corrupted or it's just something of vs 2017.  About the HelloWorld project, it was all defaults: web core, single auth and nothing else... i see your point, if I chose authentication, them entity framework should be there... mmm... unfortunate moment to install vs 2015, though.

**Comment by karelz** [comment]
Just for the record: All my experiments were in VS 2017.

**Comment by parismiguel** [comment]
sorry... it was my despair and frustration moving forward before thinking anymore....anyways, i've also had problems syncing my projects to github and visual studio online among other changes in vs 2017... better go back with my old friend vs 2015. As soon the installation is finished, i'll do it all over again and let you know any outcome.... thank you for your outstanding support!

**Comment by karelz** [comment]
Sure thing.

BTW: My experience with VS upgrades in last few years is that they get better than previous version. It is **extremely rare** that basic scenarios regress or don't work (I could believe it maybe on the first day of the release, but not after ~3 weeks - you would find plenty blog posts and release notes on that).
Anyway, if my scenarios break, I always question if setup was successful in the first place. I would try a VM or another machine to confirm it is not a one machine problem.
Running back to older version is "easy", but it prevents you to experience the best and latest. And the support for newest things usually comes only to latest VS versions, so you need to migrate to new version eventually anyway ... just my 2 cents based on my personal experience with VS.

**Comment by parismiguel** [comment]
You're right... it will be just a brief time to get all my current projects running as before. Once they are finished, i'll upgrade again... it's just that i'm 2 days without sleep and i'm not getting any progress.  Warm regards,

**Comment by karelz** [comment]
I know that feeling, ... hope it gets worked around soon for you ...

**Comment by davidsh** [comment]
>FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

Without seeing a complete repro solution posted, it is difficult to know for sure. But, I have a theory about this.  The error seems to tell me 2 pieces of information. One, that the system is looking for System.Net.Http with assembly version 4.1.1.0.  This means that System.Net.Http Nuget package version 4.3.1 is being used or at least referenced.

However, the `FileNotFoundException` is telling me that it can't find the file during execution.  With ASP.NET, the default compilation/build scenario is to use "shared" .NET Core packages and binaries. That means that typically your projects 'bin/Debug' folder won't contain all the binaries for your solution. Rather, running this solution requires using the binaries that are already in the 'shared' location.  This problem that you're seeing with the FileNotFoundException might be a bug or other installation issue where the System.Net.Http.dll, assembly version 4.1.1.0 is not being placed into either the bin/debug folder.  It is unlikely that this dll is part of the 'shared' locations since it is a new binary and not part of any global meta-package references.

So, as part of debugging this, can you share a screenshot of your 'bin/debug' folder and show what binaries are there?

**Comment by karelz** [comment]
@parismiguel did you get chance to follow up on @davidsh's questions?

**Comment by parismiguel** [comment]
Hi @davidsh , thank you for your help. I've finally downgraded my visual studio to 2015 and build up a new project using asp framework mvc + web api which bundle the right libraries for http... everything is working just fine, incuding git sync!
Thank you @karelz for all your support!

**Comment by karelz** [comment]
OK, closing. If you find anything else concerning on another install, please let us know.
Thanks and good luck!

**Comment by DRAirey1** [comment]
Yeah, I've got this problem now, exactly, with Visual Studio 2017.

**Comment by dmx9600** [comment]
Yeah, I've got this problem now, exactly, with Visual Studio 2017

**Comment by karelz** [comment]
It is most likely separate problem. Please make sure you have latest Visual Studio. Create simple HelloWorld-style repro, then file a new bug if you are still hitting the problem.

**Comment by yifungl** [comment]
For those hitting this issue on VS 2017, does the issue go away if you go into the Visual Studio Installer and remove R Tools for Visual Studio?
