### ISSUE TITLE
Potential overflow in key size validation in System.Security.Cryptography.SymmetricAlgorithm

### ISSUE THREAD

**Issue by rielz** [dotnet/corefx#1755]
The current implementation of `SymmetricAlgorithm.Key` checks the size of the key with unchecked `key.Length * 8` which could overflow.

Thus a byte array with a size of `536870928` would be approved as a 128 bit key.

A first fix could be adding a checked expression for the multiplication.

As a later solution I propose a `public bool ValidKey(byte[])` method as every implementer of `SymmetricAlgorithm` will need their own key size checkes in implementations of `CreateDecryptor(byte[], byte[])` and `CreateEncryptor(byte[], byte[])`.

The same bug is present in the full .NET framework since at least 2012 when I reported it on Connect.
There the different implementations can not handle that unexpected array: 
- `AesManaged`: `IndexOutOfRangeException`
- `AesCryptoServiceProvider`: `OutOfMemoryException`
- ...

**Comment by stephentoub** [comment]
Thanks for the bug report, @rielz. Fixed with #1759.
