### ISSUE TITLE
Issue with the rd.xml embedded by System.Private.Xml.Linq

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#17557]
@vitek-karas found the following issue with the rd.xml used by System.Private.Xml.Linq

> The .rd.xml talks about System.Xml.Linq, instead of System.Private.Xml.Linq, which is just a façade, so it’s effectively ignored by the compiler. Also the directives would not apply to the code we wanted them to. 

It should refer to System.Private.Xml.Linq instead. This also issues warnings during ILC.

```
      System.Linq.Expressions.Resources.System.Linq.Expressions.rd.xml(9-9): warning : ILTransform : warning ILT0027: Type 'System.Linq.Expressions.Microsoft.CSharp.RuntimeBinder.R
  untimeBinderException' could not be found.
       System.Linq.Expressions.Resources.System.Linq.Expressions.rd.xml(10-10): warning : ILTransform : warning ILT0027: Type 'System.Linq.Expressions.System.Linq.Expressions.Expres
  sionCreator<>' could not be found.
       System.Linq.Expressions.Resources.System.Linq.Expressions.rd.xml(10-10): warning : ILTransform : warning ILT0027: Type 'System.Linq.Expressions.System.Linq.Expressions.Expres
  sionCreator<System.Func<System.Boolean>>' could not be found.
       System.Linq.Expressions.Resources.System.Linq.Expressions.rd.xml(11-11): warning : ILTransform : warning ILT0027: Type 'System.Linq.Expressions.System.Runtime.CompilerService
  s.CallSite<>' could not be found.
       System.Linq.Expressions.Resources.System.Linq.Expressions.rd.xml(11-11): warning : ILTransform : warning ILT0027: Type 'System.Linq.Expressions.System.Runtime.CompilerService
  s.CallSite<System.Func<System.Runtime.CompilerServices.CallSite,System.Object,System.Int32>>' could not be found.
       System.Linq.Expressions.Resources.System.Linq.Expressions.rd.xml(12-12): warning : ILTransform : warning ILT0027: Type 'System.Linq.Expressions.System.Runtime.CompilerService
  s.CallSiteOps' could not be found.
       System.Xml.Resources.System.Private.Xml.Linq.rd.xml(4-4): warning : ILTransform : warning ILT0027: Assembly name 'System.Xml.Linq' failed to bind.
```

**Comment by VSadov** [comment]
This is specific to linq to xml.

**Comment by krwq** [comment]
@shmao is this solely rd.xml file change? Are there any failing tests related to this? What are the steps to get this error locally? cc: @sepidehMS

**Comment by shmao** [comment]
The fix for this would be soley rd.xml file change (and potentially some changes in csproj). I'm not seeing any tests failing due to this directly, but there might be. Here're the steps to repro the issue.

From source root,
1. `build.cmd -framework:uapaot /p:TestILCFolder=<path to TestIlc folder>`
2. `msbuild src\System.Runtime.Serialization.Xml\tests\System.Runtime.Serialization.Xml.Tests.csproj /p:TargetGroup=uapaot /t:rebuildandtest`
3. You would see the warnings in the output.

Note that the above steps were for running XmlSerializer tests. That could be why I didn't see any tests failing due to this directly.
