### ISSUE TITLE
Backporting HttpClient instrumentation with DiagnosticSource to netstandard1.3

### ISSUE THREAD

**Issue by lmolkova** [dotnet/corefx#17564]
I have previously implemented changes that changes `HttpClientHandler` logging with `DiagnosticsSource` #16393. 
Now instrumentation is only available with netcoreapp2.0 since System.Net.Http [targets](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System.Net.Http.csproj) netcoreapp2.0 only among CoreFx targets. 

Would like to use this instrumentation in the existing project that target netstandard1.3 and higher (assuming they can take a dependency on a new System.Net.Http package).

Are there any problems with enabling netstandard1.3 target for System.Net.Http and publishing new nuget? Were there any changes in public API that would not make it compatible?

**Comment by davidsh** [comment]
>Are there any problems with enabling netstandard1.3 target for System.Net.Http and publishing new nuget? Were there any changes in public API that would not make it compatible?

{master] branch is only for netstandard20 work.

Perhaps you want to backport some of your changes to the release/1.0 or release/1.1 servicing branches.

**Comment by davidsh** [comment]
cc: @ericstj @karelz @weshaggard @stephentoub

**Comment by karelz** [comment]
Backporting to release/1.x sounds reasonable.
@weshaggard @ericstj what's your guidance?

cc @danmosemsft @leecow @vancem

**Comment by weshaggard** [comment]
You would need to go through the usual shiproom process and we would also need to ensure the necessary DiagnosticsSource changes were in the appropriate release branches. Otherwise I have no concerns.

**Comment by karelz** [comment]
@lmolkova it's going to be some non-trivial work. Is your team willing to sponsor it?

**Comment by lmolkova** [comment]
@karelz We are still has not make a decision on how critical it is for us, I should have more information during next week. If it is critical, we will do the backporting.

Could someone please share details about shiproom process?

**Comment by vancem** [comment]
@lmolkova   For what it is worth, I would only work on this after everything else works well.   There will be strong incentives for people to upgrade to 2.0 and the path should be hopefully easy (there is the change in build system, but the old system is rapidly being abandoned so they need to upgrade for other reasons as well).

**Comment by karelz** [comment]
@lmolkova please ping me and @leecow via email, I will share shiproom internal links ...

**Comment by karelz** [comment]
This got closed without any explanation - why?

**Comment by lmolkova** [comment]
I created this issue to understand how to downport Diagnostic instrumentation to necoreapp1.0+. However we are no longer interested in it and will not do any changes.

**Comment by karelz** [comment]
Thanks, that's a good context!
