### ISSUE TITLE
Desktop throws a TypeLoadException when `StreamingContext` is a typeforward to mscorlib and using any of the serialization event attributes

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#17575]
If an assembly is built against netstandard and run it against netfx (desktop) and it has a type marked as Serialized and this types have any of the event methods that use either `OnDeserializedAttribute`, `OnSerializingAttribute`, `OnSerializedAttribute`, and `OnDeserializingAttribute` it would throw an exception like this one: 

```
Type <type name> in assembly <assembly name> has method <method name> with an incorrect signature for the serialization attribute that it is decorated with
```

This would happen even if the method follows the guidelines stated in the msdn documentation:
> To use the OnSerializingAttribute, the method must contain a StreamingContext parameter. 

We are currently hitting this issue on the `System.Runtime.Serialization.Formatters.Tests` that have a type with this characteristics ([source code](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Serialization.Formatters/tests/SerializationTypes.cs#L321-L342)) when the test is built against netstandard and we run it against netfx.

After investigating with @weshaggard he found out that there a bug in the `methodtablebuilder.cpp` when verifying the signature for this method (requiring a `StreamingContext` parameter) it doesn't follow the typeforwards correctly on the case it was defined on a shim like in the case of netstandard that is a typeforward to mscorlib so it throws an exception that the method signature is bad. 

cc: @jkotas @stephentoub

**Comment by stephentoub** [comment]
Should this issue be moved to coreclr?

**Comment by jkotas** [comment]
This is .NET Framework bug. It should be moved to internal TFS where .NET Framework bugs are tracked.

**Comment by safern** [comment]
> This is .NET Framework bug. It should be moved to internal TFS where .NET Framework bugs are tracked.

Indeed it is a .NET Framework bug where the VM doesn't follow the typeforwards correctly. 

> @safern, should this issue be moved to coreclr?

We decided to open it here (github and corefx), so that a decision is made towards if we want to support binary serialization on 2.0 and document this bug or if we want to push that to 2.1 when this bug gets fixed on the next Full Framework release.

**Comment by stephentoub** [comment]
> so that a decision is made towards if we want to support binary serialization on 2.0

I don't understand this comment.  Can you elaborate?  What's not supported with .NET Core 2.0 that would need to be documented?

**Comment by safern** [comment]
We currently don't support building against netstandard and running on netfx a library/application that uses binary serialization. In theory we support this but due to this bug in the VM our customers will get a `TypeLoadException` when following this path. 

They would have to have to different binaries of their library/application for this to work (one built against netcoreapp and one against netfx)

Does this makes it clearer?

**Comment by stephentoub** [comment]
Ah.  In that case if you're looking for a GitHub tracking issue related to standard, wouldn't this be better in the dotnet/standard repo (in addition to whatever bug you open in TFS for desktop)?  It seems like there's zero action item here for core, and any documentation would be related to standard and desktop, not core.

**Comment by safern** [comment]
> In that case if you're looking for a GitHub tracking issue related to standard, wouldn't this be better in the dotnet/standard repo (in addition to whatever bug you open in TFS for desktop)?

Sounds good, I can take care of that.

**Comment by safern** [comment]
Opened: https://github.com/dotnet/standard/issues/300 and 407239 on TFS.
