### ISSUE TITLE
build -Outerloop passes without running any tests

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#17581]
To repro in the master branch:

```
clean -all && build -Outerloop
```

Expected:

Based on `build -?` documentation: Builds source and tests; executes the outerloop tests:

```[-Outerloop]                      Enables outerloops tests scenarios.
                                  => Default value: true
                                  => Legal values: [True, False].
```

Actual:

Builds `\src` (and `\pkg`?). Will not build (or run) anything under `\test`.

**Comment by weshaggard** [comment]
Build no longer does test build and run by default. YOu need to call build-tests.cmd. See https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md.

There is a shortcut which is `build.cmd -tests -Outerloop` which will build the product and tests.

**Comment by CIPop** [comment]
@weshaggard `build -?` is saying:

Builds source __and tests; executes the outerloop tests__.

Either the code or the docs are out of sync.

**Comment by wtgodbe** [comment]
`build -?` now says the following for `[-Outerloop]`

`Enables outerloops test scenarios`

This no longer says anything about running the tests, so I'm closing this.
