### ISSUE TITLE
build-tests -outerloop fails after clean -all: "The target "GetBuildConfigurations" does not exist in the project"

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#17583]
Running `clean -all & build-tests` will fail with "The target "GetBuildConfigurations" does not exist in the project."

To work-around use `clean -all & build & build-tests`.

**Comment by weshaggard** [comment]
You need to build the product first. See https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md.

**Comment by CIPop** [comment]
Argh... my grammar parser was off (and in the context of looking for a single build&test command):

To me "The following builds and runs all tests for netcoreapp in release configuration.
build-tests -release -framework=netcoreapp"

I thought that it builds netcoreapp then runs all tests for netcoreapp 😄 .
