### ISSUE TITLE
Some IO tests not run on Unix due to "Condition(s) not met: \"IsNotWindowsNanoServer\""

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#17593]
` System.IO.FileSystem.Tests  xunit   System.IO.Tests.FileStream_ctor_str_fm_fa_fs_buffer_fo/ValidFileOptions` is being skipped because `"Condition(s) not met: \"IsNotWindowsNanoServer\""`

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170328.01/workItem/System.IO.FileSystem.Tests/analysis/xunit/System.IO.Tests.FileStream_ctor_str_fm_fa_fs_buffer_fo~2FValidFileOptions

test is adorned with `        [ConditionalTheory(nameof(PlatformDetection) + "." + nameof(PlatformDetection.IsNotWindowsNanoServer))]`

```c#
    public static partial class PlatformDetection
    {
        public static bool IsWindows { get; } = RuntimeInformation.IsOSPlatform(OSPlatform.Windows);
        public static bool IsNotWindowsNanoServer { get; } = (IsWindows &&
            File.Exists(Path.Combine(Environment.GetEnvironmentVariable("windir"), "regedit.exe")));
```

Not clear to me why this isn't working.

**Comment by mellinoe** [comment]
That property will return `false` for any non-Windows platform, which doesn't necessarily seem correct just based on the name of it. @Priya91 is that intentional?

**Comment by danmosemsft** [comment]
Right, I just realized that myself. It's not causing a probelm elsewhere because it's only used when excluding Unix as well.
```
   57:         [ConditionalFact(nameof(PlatformDetection) + "." + nameof(PlatformDetection.IsNotWindowsNanoServer))]
   58          [PlatformSpecific(TestPlatforms.Windows)]  // Expected behavior varies on Windows and Unix
```

I suggest
1. Rename IsNotWindowsNanoServer to IsWindowsOtherThanWindowsNanoServer
2. Remove now redundant [PlatformSpecific(TestPlatforms.Windows)] wherever it's applied in conjunction with IsWindowsOtherThanWindowsNanoServer.
3. Add IsNotWindowsNanoServer like the current one but without IsWindows, ie., it returns true on Unix.
4. Leave the two ProcessTests.cs with `[ConditionalFact(nameof(PlatformDetection) + "." + nameof(PlatformDetection.IsNotWindowsNanoServer))]`

Seem reasonable?

**Comment by mellinoe** [comment]
Can we just change the current version to return `true` outside of Windows (e.g. match the name of the method) instead of doing all that? Sounds like we could if this is true:

> It's not causing a probelm elsewhere because it's only used when excluding Unix as well.

**Comment by danmosemsft** [comment]
Er.. yeah. haha. I'l make this change.

**Comment by danmosemsft** [comment]
@sokket here's a scenario where I think I fixed a test, and I'd like to see its history after the fix. So ideally I could go to 
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170328.01/workItem/System.IO.FileSystem.Tests/analysis/xunit/System.IO.Tests.FileStream_ctor_str_fm_fa_fs_buffer_fo~2FValidFileOptions
which is the failure and click on something to see other builds, Instead i have to edit the URL or do a bunch of clicking through pages. Is fixing that part of your plan?

**Comment by sokket** [comment]
@danmosemsft Gotcha, thanks for the direct visual and feedback. This is definitely part of my plan, seeing test history is vital for diagnosing failures and flakiness
