### ISSUE TITLE
System.Linq.Parallel Tests are Failing on AppVeyor Machines

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#176]
The following 5 tests are failing (some intermittently) on our AppVeyor CI builds. I haven't investigated deeply, but I suspect it has to do with the limited hardware that the VM's are equipped with. Some of the test explicitly test whether multiple threads are created, which might not even be the case in an underpowered VM.

**Comment by stephentoub** [comment]
Addressed with #598.

**Comment by Eyas** [comment]
@stephentoub I think you mean addressed with #589.

**Comment by stephentoub** [comment]
Oops, yes, thanks Eyas... fixed my typo.
