### ISSUE TITLE
[Linux/x86] Change to use official docker image for CI build 

### ISSUE THREAD

**Issue by hseok-oh** [dotnet/corefx#17601]
#17182 
https://github.com/dotnet/corefx/pull/17182#discussion_r106488967

We are using temporary private docker image for linux/x86 CI build. We need to change it to official one when that is ready to use. 

@gkhanna79 @mellinoe

**Comment by gkhanna79** [comment]
CC @MichaelSimons @wtgodbe

**Comment by karelz** [comment]
@hseok-oh would it be ok to push it to Future milestone, so that we have better idea what we have to ZBB on 5/10? Or do you use the milestone for your own tracking? Thanks!

**Comment by hseok-oh** [comment]
@karelz I think it's no matter to change it future milestone.

**Comment by karelz** [comment]
@hseok-oh do you mean that it is ok (you don't care), or that you dislike the idea (and would like to keep 2.0 milestone)?

**Comment by hseok-oh** [comment]
@karelz it's ok to push future milestone.

**Comment by karelz** [comment]
@hseok-oh great, thanks! That will be helpful for our tracking.
Do you mind if I do it with all the remaining 4 [arm32 2.0 issues in Infrastructure](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aopen%20label%3Aarea-Infrastructure%20label%3Aarch-arm32%20milestone%3A2.0.0)?

**Comment by hseok-oh** [comment]
Remaining issues looks different. These issues could be cleared if nuget packaged generated for armel(tizen) is uploaded to dotnet myget (or use additional myget feed).
cc/ @jyoungyun @gkhanna79

**Comment by karelz** [comment]
OK, let's take the discussion over there in that case ...

**Comment by hseok-oh** [comment]
I'll prepare enabling Linux x86 TC pri2 test on CI.

**Comment by kirsty14141** [comment]
`removed videoed
`

**Comment by wtgodbe** [comment]
This is no longer relevant with the new YAML scripts, closing
