### ISSUE TITLE
Announcement: Driving towards zero 2.0 bugs by May 10 (ZBB)

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#17619]
As we are getting closer to .NET Core 2.0 Preview and .NET Standard 2.0 Preview [ship dates](https://github.com/dotnet/core/blob/master/roadmap.md#ship-dates), we would like to **drive [2.0.0 bugs](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0) down to 0 by May 10** (see [milestone details](https://github.com/dotnet/corefx/milestone/4)) = ZBB (zero bug bounce) date.

We would like to encourage and ask our contributors to help us drive towards that goal. **Be part of .NET Core 2.0 release!**

How can you, the CoreFX contributors, help?
1. If you're picking up issues to work on, **prefer issues marked as [2.0.0 bugs](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0)** (some are even [up-for-grabs](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20label%3Aup-for-grabs)).
2. If you spot something in [Future](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3AFuture) milestone that should be part of 2.0, please say so and explain why (loop in @karelz). Conversely if there's something in 2.0 that perhaps is not as significant as it seems.
    * We strive to deliver high-quality product, so **impactful bugs, compatibility, reliability and performance issues** are top priority. Migration to .NET Core 2.0 from .NET Core 1.1 or from .NET Framework is one of the key priorities.
    * Adding additional new APIs, fixing pre-existing bugs or fixing corner-case issues with lower impact and with existing workaround is lower priority, not tracked as 2.0.
3. Issues with [no milestone](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20no%3Amilestone) - we expect to set their milestone in upcoming weeks (part of ongoing "triage"), so if you see something must-have for 2.0 there, please say so and explain why (loop in @karelz).
4. Watch for upcoming official preview announcements (on [.NET blog](https://blogs.msdn.microsoft.com/dotnet/) or on [dotnet/Announcements repo](https://github.com/dotnet/announcements)) to help validate and dogfood the end-to-end .NET Core 2.0 experience before final release.
    * Note: You can dogfood even our daily builds - see [dogfooding steps](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md)

Not surprisingly, to deliver overall end-to-end .NET Core 2.0 experience, similar ZBB efforts happen in our sister repos like [CoreCLR](https://github.com/dotnet/coreclr), [core-setup](https://github.com/dotnet/core-setup), etc. - we will welcome help in those as well, if you're interested.

Twitter announcement: https://twitter.com/ziki_cz/status/846839252629385216

**Comment by karelz** [comment]
cc'ing recently active contributors (in random order)

@hughbe @justinvp @JonHanna @xoofx @AlexRadch @stephenmichaelf @nietras
@benaadams @fujiy @jamesqo @SamuelEnglard @couven92 @tintoy @sparraguerra @vcsjones
@bartdesmet @lmolkova @dnickless @bbowyersmyth @matekm @fitzchak @omajid
@seanshpark @hseok-oh @ofirmakmal @hqueue @chunseoklee @Gregory-Bell @jcouv
@Clockwork-Muse @jyoungyun @odyth @lemmaa @kant2002 @lucenticus @bmeverett @ViIvanov @craigajohnson @tdupont750 @KirillOsenkov @svick @jirisykora83
@parjong @tralivali1234 @shrah @khellang @cshung @nikitozz @andrewlock @cesarbs

**Comment by karelz** [comment]
@roji @alaatm @cakine @TiagoSoczek @brfalcon @ChrisEelmaa @arc001 @thiagocamargos
@mramosMS @anthonylangsworth @borgdylan @stevedesmond-ca

**Comment by ctolkien** [comment]
`milestone details` links to the edit page (which non owners can't access) should be: https://github.com/dotnet/corefx/milestone/4

**Comment by danmosemsft** [comment]
Thanks @ctolkien I fixed the link. As you see we have a lot to do :)

**Comment by tarekgh** [comment]
@karelz we are keeping this issue just for announcing and no action needed against this issue. right?

**Comment by karelz** [comment]
Yep, I'd like to keep it opened until 5/10. I can move it into Future milestone, so it doesn't affect our bug count and reports ;-)

**Comment by karelz** [comment]
FYI if you're not on Twitter:
Here's progress we're making on CoreFX, CoreCLR, core-setup and WCF repos towards 2.0: https://twitter.com/ziki_cz/status/854409726754299904 (as of Tuesday 4/18)

Huge thanks to all contributors who jumped in and actively help us drive the 2.0 bugs!

**Comment by karelz** [comment]
**Announcement:** For next 2.5 weeks (until May 10) all API additions and larger changes will get more scrutiny. If they are risky and non-essential for .NET Core 2.0, we may delay merging PR until post-5/10.

Also note that **release/2.0.0 branch** is now created and will receive last full integration from master on 5/10. Changes after 5/10 will be cherry-picked from master to release/2.0.0 branch.

New update on Twitter with latest progress on 2.0 bugs: https://twitter.com/ziki_cz/status/856692569492774912 (as of Monday 4/24)

**Comment by karelz** [comment]
Another update on remaining issues: https://twitter.com/ziki_cz/status/858042980673957889 (as of couple of hours ago)

Huge progress in both fixes and triage!

Note that we have new Post-ZBB label to mark issues which are important for 2.0, but don't affect product source code (e.g. documentation bugs, infrastructure issues), so they will be exempt from ZBB rule (so far only 9 across all 4 repos).

**Comment by karelz** [comment]
Another update on remaining issues: https://twitter.com/ziki_cz/status/859459337042837504
Only 1 week and 1 day left before 5/10

Great progress on issues without milestone (potential work).

So far only 13 bugs are marked as Post-ZBB (documentation bugs, infrastructure issues).
We will likely slip a few Networking issues past 5/10.

**Comment by karelz** [comment]
Another update: https://twitter.com/ziki_cz/status/861641617865711616
Only 3 days left before 5/10 (end of day)

So far only 15 bugs are marked as Post-ZBB (documentation bugs, infrastructure issues and couple of late small features based on feedback from community).
We will slip few Networking issues past 5/10.

**Comment by karelz** [comment]
Quick update on our short-term plans:
* We will likely do the final integration into release/2.0.0 branch on **Monday 5/15** (to stabilize infra). All PRs which are "on hold" will be "on hold" until then (3 additional business days against original plan).
* core-setup repo will need more churn afterwards to land some infrastructure work necessary for 2.0. We will lock down **core-setup** repo (master branch) and either:
    * Consume rel/2.0.0 bits of CoreFX/CoreCLR,/WCF repos in core-setup master, or
    * Move active work in core-setup into rel/2.0.0 and then integrate it back into master.

**Comment by karelz** [comment]
We are very close to ZBB - few more hours left.
Remaining: **27 bugs** for ZBB: CoreFX [13](https://github.com/dotnet/corefx/issues?q=is%3Aissue+is%3Aopen+milestone%3A2.0.0+-label%3APost-ZBB+-label%3Aarea-Infrastructure+-label%3Aarea-Tizen+-label%3Aarea-System.Net+-label%3Aarea-System.Net.Http+-label%3Aarea-System.Net.Security+-label%3Aarea-System.Net.Sockets) + CoreCLR [1](https://github.com/dotnet/coreclr/issues?q=is%3Aissue+is%3Aopen+milestone%3A2.0.0+-label%3APost-ZBB+-label%3Aarea-Infrastructure+-label%3Aarea-Tizen+-label%3Aarea-System.Net+-label%3Aarea-System.Net.Http+-label%3Aarea-System.Net.Security+-label%3Aarea-System.Net.Sockets) + core-setup [6](https://github.com/dotnet/core-setup/issues?q=is%3Aissue+is%3Aopen+milestone%3A2.0.0+-label%3APost-ZBB+-label%3Aarea-Infrastructure+-label%3Aarea-Tizen+-label%3Aarea-System.Net+-label%3Aarea-System.Net.Http+-label%3Aarea-System.Net.Security+-label%3Aarea-System.Net.Sockets) + WCF [7](https://github.com/dotnet/wcf/issues?q=is%3Aissue+is%3Aopen+milestone%3A2.0.0+-label%3APost-ZBB+-label%3Aarea-Infrastructure+-label%3Aarea-Tizen+-label%3Aarea-System.Net+-label%3Aarea-System.Net.Http+-label%3Aarea-System.Net.Security+-label%3Aarea-System.Net.Sockets)

90 issues have ZBB exception from theses reasons:
* Marked as Post-ZBB (documentation, infrastructure) - currently 21
* area-Infrastructure (does not directly affect product) – currently 45
* area-System.Net* (known exception – the area will slip past ZBB) – currently 17
* area-Tizen (issues tracked by Samsung for 2.0) – currently 12

Only 14 issues without milestone - except one, all of them created in last 24 hours.

**Comment by karelz** [comment]
Yesterday we have released .NET Core 2.0 preview1: https://github.com/dotnet/core/issues/640
If you can, please try it out. Report any issues back to us ASAP (ideally in next week), so that we can fix it for final release.

**Comment by karelz** [comment]
We’re down to last 12 issues for ZBB. Almost there!
* core-setup - [7](https://github.com/dotnet/core-setup/issues?q=is%3Aissue+is%3Aopen+milestone%3A2.0.0+-label%3APost-ZBB+-label%3Aarea-Infrastructure+-label%3Aarea-Tizen+-label%3Aarea-System.Net+-label%3Aarea-System.Net.Http+-label%3Aarea-System.Net.Security+-label%3Aarea-System.Net.Sockets)
* CoreFX repo - [4](https://github.com/dotnet/corefx/issues?q=is%3Aissue+is%3Aopen+milestone%3A2.0.0+-label%3APost-ZBB+-label%3Aarea-Infrastructure+-label%3Aarea-Tizen+-label%3Aarea-System.Net+-label%3Aarea-System.Net.Http+-label%3Aarea-System.Net.Security+-label%3Aarea-System.Net.Sockets) - 1 issue has pending PR
* CoreCLR - [1](https://github.com/dotnet/coreclr/issues?q=is%3Aissue+is%3Aopen+milestone%3A2.0.0+-label%3APost-ZBB+-label%3Aarea-Infrastructure+-label%3Aarea-Tizen+-label%3Aarea-System.Net+-label%3Aarea-System.Net.Http+-label%3Aarea-System.Net.Security+-label%3Aarea-System.Net.Sockets)
* wcf - [0](https://github.com/dotnet/wcf/issues?q=is%3Aissue+is%3Aopen+milestone%3A2.0.0+-label%3APost-ZBB+-label%3Aarea-Infrastructure+-label%3Aarea-Tizen+-label%3Aarea-System.Net+-label%3Aarea-System.Net.Http+-label%3Aarea-System.Net.Security+-label%3Aarea-System.Net.Sockets)

Congratulations to WCF repo to hitting ZBB first!

**Comment by karelz** [comment]
**What's next, after ZBB?**
We will keep aggressively triaging incoming issues (i.e. set milestone), to make sure we react to feedback quickly.
If you see anything blocking final release, please ping area owners, or @karelz / @danmosemsft.

Currently we have **15 issues without milestone**:
* CoreCLR repo - [7](https://github.com/dotnet/coreclr/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20no%3Amilestone) (all <1d old)
* Core-setup repo - [4](url) (all <2d old)
* CoreFX repo - [3](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20no%3Amilestone) (only 1 issue is 4d old)
* wcf repo - [1](https://github.com/dotnet/wcf/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20no%3Amilestone) (<1d old)

**Comment by garfbradaz** [comment]
> Core-setup repo - 4 (all <2d old)

404 on link :)

**Comment by tarekgh** [comment]
@garfbradaz I fixed the link.

**Comment by karelz** [comment]
**Last 5 issues** for ZBB (queries restricted to issues created before 5/10). Almost there!

* CoreFX - [3](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20-label%3APost-ZBB%20-label%3Aarea-Infrastructure%20-label%3Aarea-Tizen%20-label%3Aarea-System.Net%20-label%3Aarea-System.Net.Http%20-label%3Aarea-System.Net.Security%20-label%3Aarea-System.Net.Sockets%20created%3A%3C2017-05-10%20)
* core-setup - [1](https://github.com/dotnet/core-setup/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20-label%3APost-ZBB%20-label%3Aarea-Infrastructure%20-label%3Aarea-Tizen%20created%3A%3C2017-05-10)
* CoreCLR - [1](https://github.com/dotnet/CoreCLR/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20-label%3APost-ZBB%20-label%3Aarea-Infrastructure%20-label%3Aarea-Tizen%20created%3A%3C2017-05-10)
* wcf - [0](https://github.com/dotnet/wcf/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20-label%3APost-ZBB%20-label%3Aarea-Infrastructure%20-label%3Aarea-Tizen%20created%3A%3C2017-05-10)

**Comment by karelz** [comment]
**Last 3 issues** for ZBB (queries restricted to issues created before 5/10). Getting closer and closer!

* CoreFX - [1](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20-label%3APost-ZBB%20-label%3Aarea-Infrastructure%20-label%3Aarea-Tizen%20-label%3Aarea-System.Net%20-label%3Aarea-System.Net.Http%20-label%3Aarea-System.Net.Security%20-label%3Aarea-System.Net.Sockets%20created%3A%3C2017-05-10%20) - #19179
* core-setup - [1](https://github.com/dotnet/core-setup/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20-label%3APost-ZBB%20-label%3Aarea-Infrastructure%20-label%3Aarea-Tizen%20created%3A%3C2017-05-10) - https://github.com/dotnet/core-setup/issues/2334
* CoreCLR - [1](https://github.com/dotnet/CoreCLR/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20-label%3APost-ZBB%20-label%3Aarea-Infrastructure%20-label%3Aarea-Tizen%20created%3A%3C2017-05-10) - https://github.com/dotnet/coreclr/issues/11453
* wcf - [0](https://github.com/dotnet/wcf/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20-label%3APost-ZBB%20-label%3Aarea-Infrastructure%20-label%3Aarea-Tizen%20created%3A%3C2017-05-10)

**Comment by karelz** [comment]
Here are 2.0 bugs filed after 5/10 - some of them by community and some of them even fixed right away!

* CoreFX - [18](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue%20milestone%3A2.0.0%20created%3A%3E2017-05-10)
* CoreCLR - [11](https://github.com/dotnet/coreclr/issues?utf8=%E2%9C%93&q=is%3Aissue%20milestone%3A2.0.0%20created%3A%3E2017-05-10)
* core-setup - [2](https://github.com/dotnet/core-setup/issues?utf8=%E2%9C%93&q=is%3Aissue%20milestone%3A2.0.0%20created%3A%3E2017-05-10)
* wcf - [1](https://github.com/dotnet/wcf/issues?utf8=%E2%9C%93&q=is%3Aissue%20milestone%3A2.0.0%20created%3A%3E2017-05-10)

Community contributions (excluding Microsoft and Samsung employees):
  * Fixed: #19710 (@slozier), #19712 (@NickCraver), #19673 (@FransBouma), #19651 (@RickStrahl)
    * Shout out to @justinvp for fixing #19651 - thanks!
  * Opened: #19708 (@NickCraver), #19694 (@yaakov-h), https://github.com/dotnet/coreclr/issues/11578 (@slozier)

**Comment by tarekgh** [comment]
dotnet/coreclr#11578 (@slozier) still opened because we need to add the test for the fixed case. We are waiting to get successful coreclr package in corefx repo.

**Comment by karelz** [comment]
We have hit ZBB (zero 2.0 bugs filed before 5/10) !!! **Hooray!!!**
* CoreFX repo - [0](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20-label%3APost-ZBB%20-label%3Aarea-Infrastructure%20-label%3Aarea-Tizen%20-label%3Aarea-System.Net%20-label%3Aarea-System.Net.Http%20-label%3Aarea-System.Net.Security%20-label%3Aarea-System.Net.Sockets%20created%3A%3C2017-05-10%20)
* CoreCLR repo - [0](https://github.com/dotnet/CoreCLR/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20-label%3APost-ZBB%20-label%3Aarea-Infrastructure%20-label%3Aarea-Tizen%20created%3A%3C2017-05-10)
* core-setup repo - [0](https://github.com/dotnet/core-setup/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20-label%3APost-ZBB%20-label%3Aarea-Infrastructure%20-label%3Aarea-Tizen%20created%3A%3C2017-05-10)
* wcf repo - [0](https://github.com/dotnet/wcf/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20-label%3APost-ZBB%20-label%3Aarea-Infrastructure%20-label%3Aarea-Tizen%20created%3A%3C2017-05-10)

Congratulations to the teams driving hard to get here!

We awarded a few exceptions along the way (one-off Post-ZBB label, and 3 areas: Networking, Infrastructure and Tizen). Here are details:


| Repo              | Post-ZBB | Created before 5/10 | Remaining<br/>work:  | All 2.0 bugs | No milestone bugs
|----------------|-----------|------------------------|-------------------|--------------|-----------------------
| **CoreFX**  |  [14](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20label%3APost-ZBB%20created%3A%3C2017-05-10%20) | Networking -  [4](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20-label%3Aarea-Infrastructure%20-label%3Aarea-Tizen%20-label%3APost-ZBB%20created%3A%3C2017-05-10%20) <br/> Infrastructure - [2](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20label%3Aarea-Infrastructure%20-label%3APost-ZBB%20created%3A%3C2017-05-10%20) <br/> Tizen - [1](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20label%3Aarea-Tizen%20-label%3APost-ZBB%20created%3A%3C2017-05-10%20) |   | [44](https://github.com/dotnet/corefx/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0) | [19](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20no%3Amilestone)
| **CoreCLR** | [8](https://github.com/dotnet/CoreCLR/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20label%3APost-ZBB%20created%3A%3C2017-05-10%20) | Infrastructure - [3](https://github.com/dotnet/CoreCLR/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20-label%3APost-ZBB%20label%3Aarea-Infrastructure%20created%3A%3C2017-05-10%20) <br/> Tizen - [9](https://github.com/dotnet/CoreCLR/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20-label%3APost-ZBB%20label%3Aarea-Tizen%20created%3A%3C2017-05-10%20) | | [30](https://github.com/dotnet/CoreCLR/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0) | [13](https://github.com/dotnet/CoreCLR/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20no%3Amilestone)
| **core-setup** | [1](https://github.com/dotnet/core-setup/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20label%3APost-ZBB%20created%3A%3C2017-05-10%20) | Infrastructure - [26](https://github.com/dotnet/core-setup/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20-label%3APost-ZBB%20label%3Aarea-Infrastructure%20created%3A%3C2017-05-10%20) <br/> Tizen - [3](https://github.com/dotnet/core-setup/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20-label%3APost-ZBB%20label%3Aarea-Tizen%20created%3A%3C2017-05-10%20) | | [35](https://github.com/dotnet/core-setup/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0) | [7](https://github.com/dotnet/core-setup/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20no%3Amilestone)
| **wcf** | [0](https://github.com/dotnet/wcf/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20label%3APost-ZBB%20created%3A%3C2017-05-10%20) | [0](https://github.com/dotnet/wcf/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%20created%3A%3C2017-05-10%20) | | [0](https://github.com/dotnet/wcf/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0%22) | [0](https://github.com/dotnet/wcf/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20no%3Amilestone)

We also started receiving high-value bug reports from people trying out Preview 1 - thanks everyone for your help!

### What's next for .NET Core?

**We are in "ask mode" until 5/26** (1.5 weeks), i.e. high-impactful bug fixes can get in, we have to ask shiproom (risk vs. value will be assessed).
**Starting 5/27, we will be in "Escrow mode"**, i.e. the bar for bug fixes goes even higher (to stabilize) and only truly important fixes (**show-stoppers**) will get in.
Every change will require shiproom discussion if taking it is worth the risk of "resetting Escrow". In practice it means rel/2.0.0 branch will be locking down for final release.

**Comment by karelz** [comment]
Latest update on 2.0 bugs -- see graphs in https://twitter.com/ziki_cz/status/866970797184659456
**Last week of Ask mode**, then we are in Escrow mode (i.e. truly impactful bugs only, the bar will be high)

* CoreFX - [67](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0)
* CoreCLR - [33](https://github.com/dotnet/coreclr/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0)
* core-setup - [15](https://github.com/dotnet/core-setup/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0)
* wcf - [3](https://github.com/dotnet/wcf/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A2.0.0)

Thanks everyone for filing great bugs! Highlights:
* We've got a stream of bugs in `System.Data.SqlClient`, we adjusted investment in the area and asked everyone for help -- see #19970 for details.
* We've got great stream of compat bugs for HttpListener by @hughbe (he created tests, filed [28 bugs](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue%20author%3Ahughbe%20created%3A%3E2017-05-10%20) and submitted some fixes - thanks a lot @hughbe!)

Overall 2.0 bugs filed by community:
* System.Net (HttpListener) - 24 bugs
* System.Data.SqlClient - 8 bugs
* System.Net - 4 bugs
* System.Security - 3 bugs
* System.Runtime - 3 bugs
* various areas - 6 bugs

**Comment by yaakov-h** [comment]
@karelz that twitter link 404s.

**Comment by karelz** [comment]
I deleted the original tweet couple of minutes after posting the GitHub reply, I immediately retweeted it with fixed typo.
I updated GH to the new link right away, so you likely clicked the old link from email notification. Here it is again: https://twitter.com/ziki_cz/status/866981185267707904

**Comment by karelz** [comment]
Thanks everyone for your help with ZBB and post-ZBB work. We are now deep in Escrow - i.e. taking only the most critical bug fixes.

I don't think we need this announcement issue around anymore.
