### ISSUE TITLE
Add messages for PNSE in Serialization

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#17616]
These PNSE are in Serialization code.

Would you consider throwing up a PR that either adds a message or a comment to each?

eg 
`throw new PlatformNotSupportedException(SR.PlatformNotSupported_ComInterop)`
where the message is like `<value>COM Interop is not supported on this platform.</value>`

Or if it’s something that’s not worth a specific resource, just a comment like this on the same line saves us digging up emails to remember why, and helps the next dev. eg

`throw new PlatformNotSupportedException(); // Not supported on Unix because NTLM is rarely used on Unix`

The message will help users (and perhaps help support). The comment at least documents the reason for the future devs and anyone checking we've implemented everything.

I've been slowly going through the tree adding these or other folks have been.

```
C:\git\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\SchemaExporter.cs:
   29:             throw new PlatformNotSupportedException();

C:\git\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerReadContextComplex.cs:
  139:             throw new PlatformNotSupportedException();

C:\git\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XsdDataContractExporter.cs:
   43:                 throw new PlatformNotSupportedException("SchemaImporter");
   61:                 throw new PlatformNotSupportedException();

C:\git\corefx\src\System.Private.DataContractSerialization\src\System\Xml\XmlDictionaryReader.cs:
  154:             throw new PlatformNotSupportedException();
  178:             throw new PlatformNotSupportedException();

C:\git\corefx\src\System.Private.DataContractSerialization\src\System\Xml\XmlDictionaryWriter.cs:
   69:             throw new PlatformNotSupportedException();

C:\git\corefx\src\System.Runtime.Serialization.Formatters\src\System\Runtime\Serialization\Formatters\Binary\BinaryUtilClasses.cs:
  412:                     throw new PlatformNotSupportedException();
```

**Comment by shmao** [comment]
C:\git\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\SchemaExporter.cs:
- [ ]    29:             throw new PlatformNotSupportedException();

C:\git\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerReadContextComplex.cs:
- [ ]   139:             throw new PlatformNotSupportedException();

C:\git\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XsdDataContractExporter.cs:
- [ ]    43:                 throw new PlatformNotSupportedException("SchemaImporter");
- [ ]    61:                 throw new PlatformNotSupportedException();

C:\git\corefx\src\System.Private.DataContractSerialization\src\System\Xml\XmlDictionaryReader.cs:
- [ ]   154:             throw new PlatformNotSupportedException();
- [ ]   178:             throw new PlatformNotSupportedException();

C:\git\corefx\src\System.Private.DataContractSerialization\src\System\Xml\XmlDictionaryWriter.cs:
- [ ]    69:             throw new PlatformNotSupportedException();

**Comment by shmao** [comment]
@stephentoub can you please have a look at the following PNSE?

```
C:\git\corefx\src\System.Runtime.Serialization.Formatters\src\System\Runtime\Serialization\Formatters\Binary\BinaryUtilClasses.cs:
  412:                     throw new PlatformNotSupportedException();
```
