### ISSUE TITLE
Environment.GetEnvironmentVariable returns garbage string if variable is set to empty string on Ubuntu 14.04

### ISSUE THREAD

**Issue by dagood** [dotnet/corefx#17614]
When an environment variable is empty, but set (like `var=`), `GetEnvironmentVariable` will return various garbage values for that variable in Ubuntu 14.04 (tested in Docker).

[Gist with Dockerfile and Program.cs to repro](https://gist.github.com/dagood/bce973c70021a010f70c2ec220c0f56a). (Dockerfile is based on the Core-Setup build infra, which is where this was encountered.) Just the execution:
```
RUN ~/.dotnet/dotnet run && \
    var=asdf ~/.dotnet/dotnet run && \
    var= ~/.dotnet/dotnet run
```

```C#
Console.WriteLine($"Var contains: '{Environment.GetEnvironmentVariable("var")}'");
```

> Var contains: ''
> Var contains: 'asdf'
> Var contains: '즔翾'

The project is using `Microsoft.NETCore.App` `1.1.1`.

Issue probably tracking adding tests for this case: https://github.com/dotnet/corefx/issues/4406 /cc @AlexGhiondea

**Comment by danmosemsft** [comment]
Could we be getting back `name=` with `=` as the last character? And this code is going past the end

https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/src/pal/src/misc/environ.cpp#L942
``` c++
            else if (*equalsSignPosition == '=')
            {
                retValue = equalsSignPosition + 1;
                break;
            }
```

**Comment by danmosemsft** [comment]
I think this case `name=` is anticipated in a different context, suggesting it does happen:
https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/src/pal/src/misc/environ.cpp#L844

**Comment by adityamandaleeka** [comment]
Looks like the bug is in the managed layer: [`GetEnvironmentVariableCore`](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Environment.cs#L679) doesn't handle the case where an environment variable is found but has length 0. If this happens, it effectively just does `StringBuilderCache.Acquire` followed by `StringBuilderCache.GetStringAndRelease`.

I'll send a fix.

**Comment by danmosemsft** [comment]
@adityamandaleeka do you believe this also needs to be addressed (protected against going off end)?

https://github.com/dotnet/corefx/issues/17614#issuecomment-289946833

**Comment by omajid** [comment]
`environ` is an array of null-terminated strings. Going one-past the last character of a string should point to the `null`. That should be safe if it's only used with functions that check for the end of the string before going past it, no?

**Comment by adityamandaleeka** [comment]
Yup. That part is fine.

**Comment by danmosemsft** [comment]
Ah - right
