### ISSUE TITLE
Enumerable methods with optimizations for IList<> should also optimize for IReadOnlyList<>

### ISSUE THREAD

**Issue by chrisdunelm** [dotnet/corefx#17629]
Enumerable methods such as `Last()` contain [an optimization for `IList<>`](https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Last.cs#L62). These methods should also optimize for `IReadOnlyList<>`

**Comment by Grauenwolf** [comment]
Has there been any progress on this?

**Comment by Grauenwolf** [comment]
Is this needed?

As much as I dislike it, all collections that implement `IReadOnlyList<T>` are supposed to also implement `IList<T>` with `IsReadOnly=false`.

**Comment by stephentoub** [comment]
Closing as dup of https://github.com/dotnet/corefx/issues/26579
