### ISSUE TITLE
Add regression test for https://github.com/dotnet/coreclr/pull/10352

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#17631]

**Comment by jkotas** [comment]
@ezverev Are you interested in adding the regression test? 

It should go to https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/TimeSpanTests.cs

**Comment by ezverev** [comment]
I will look into appending a test in order to assure there is no longer unneeded precision loss when constructing TimeSpan from a double of different scales.

**Comment by stephentoub** [comment]
Closing as the change was reverted in https://github.com/dotnet/coreclr/commit/6c978497a1c16373153c9263a2d1be09949b5b09.
