### ISSUE TITLE
Debug.Assert (or Contract.Assert) failure when running on Desktop will hang the test run

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#17636]
When a `Contract.Assert` fails it seems we pop assert UI which hangs the entire test run
https://github.com/dotnet/corefx/issues/17621

Note that `Debug.Assert` would have the same behavior in fact it's what's doing it.

cc @safern

**Comment by danmosemsft** [comment]
Looks like in S.D.Assert.Fail it checks `if (Debugger.IsAttached == true)` but only after the dialog has dismissed.

**Comment by danmosemsft** [comment]
Note this problem doesn't exist on Core as it doesn't support debug assert dialogs (#3708)

**Comment by stephentoub** [comment]
@danmosemsft, is this still a problem?

**Comment by danmosemsft** [comment]
Hasn't come to my attention, we can reopen if it does.
