### ISSUE TITLE
Bundle latest cURL with fixes we care about

### ISSUE THREAD

**Issue by janvorli** [dotnet/corefx#17647]
@karelz commented on [Tue Mar 28 2017](https://github.com/dotnet/coreclr/issues/10528)

Here's interesting list:
* Don't compile NSS version, it causes troubles - see https://github.com/dotnet/corefx/issues/16201
* cURL fix https://github.com/curl/curl/issues/1354 for https://github.com/dotnet/corefx/issues/17174

---

@stephentoub commented on [Tue Mar 28 2017](https://github.com/dotnet/coreclr/issues/10528#issuecomment-289860092)

> Don't compile NSS version

On Linux we always want to use a version based on OpenSSL.  While we tolerate NSS and other backends, lots of features don't work when targeting those, e.g. custom handling of certificates, revocation checking, etc.

---

@jkotas commented on [Wed Mar 29 2017](https://github.com/dotnet/coreclr/issues/10528#issuecomment-289959662)

Why is this tracked in CoreCLR repo?

---

@karelz commented on [Wed Mar 29 2017](https://github.com/dotnet/coreclr/issues/10528#issuecomment-289987914)

I thought cURL bundling happens in CoreCLR -- @janvorli? If I am wrong, feel free to move it.

---

@janvorli commented on [Wed Mar 29 2017](https://github.com/dotnet/coreclr/issues/10528#issuecomment-290013047)

No, it will happen in corefx repo. I am sorry for not noticing before this issue was in coreclr. Moving to corefx.

**Comment by tmds** [comment]
CC @omajid

**Comment by stephentoub** [comment]
I'm going to close this on the assumption we're not going down this path.  If that changes, we can re-open.
