### ISSUE TITLE
Fix System.IO tests for netfx

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#17659]
On my local run I get 106 test failures when running on NetFX. We need to audit the tests to make sure all of the platform differences are purposeful and add         `[SkipOnTargetFramework(TargetFrameworkMonikers.NetFramework, "")]` where necessary.

**Comment by danmosemsft** [comment]
Presumably @safern these are among the failures you are already tracking.

BTW please let's always have something in those quotes so we don't guess about why we have the attribute later!

**Comment by safern** [comment]
Yes this should be in the failures that I'm already tracking. Please open the corresponding issues if it is a bug/compat issue and add it to the attribute. If it doesn't fall on either of those let's just explain why we are disabling it. 

FYI: this 106 failures doesn't necessarily mean there is 106 tests failing. It could be a few tests failing with multiple input cases failing.

**Comment by safern** [comment]
Thanks @ianhays for following this and opening this issue.

**Comment by ianhays** [comment]
@safern when you say you're tracking the failures, does that mean you're currently working on making the tests pass? Or something else?

>FYI: this 106 failures doesn't necessarily mean there is 106 tests failing. It could be a few tests failing with multiple input cases failing.

That should be the case for most of these failures since the FileSystem tests make use of some  **heavy** inheritance.

>BTW please let's always have something in those quotes so we don't guess about why we have the attribute later!

Of course :)

**Comment by safern** [comment]
> @safern when you say you're tracking the failures, does that mean you're currently working on making the tests pass? Or something else?

I'm currently just tracking how many failures we currently have in desktop tests to try to get it to zero, but there is like 40-50 projects with failures so I'm going to start opening issues and help on some of those failures as I being doing. But in this particular case I'm not working on this tests so help would be appreciated :) 

Thanks!!

**Comment by ianhays** [comment]
Gotcha, thanks for the clarification. I'll go ahead and work on this then :)

**Comment by ianhays** [comment]
> there is like 40-50 projects with failures so I'm going to start opening issues and help on some of those failures as I being doing.

Ouch, hopefully we can get that number down before 2.0.0. In my experience desktop test failures have a high tendency to hide breaking changes that were made at a time when netcore didn't care as much about desktop compat as we do now. Let me know if there's anything I can do to help the effort :)

**Comment by danmosemsft** [comment]
@ianhays I'm definitely expecting this to be parallelized, @safern is just driving the effort so he'll be sending out issues and nagging.

**Comment by safern** [comment]
Yes I just wanted to have a clean run but I should start opening issues like this one today or tomorrow. Thanks for the help @ianhays 

Btw in the cases where there is one test failing multiple times to read the xunit output is a little bit difficult as it prints out all the cases that test failed. I wrote a small program that actually filters you out that list telling you the real number of test failing and which tests are failing. If that helps you I'm glad to share it.
