### ISSUE TITLE
Decide if we want System.*.AccessControl libraries to be available for UAP

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#17660]
cc: @weshaggard 

Today, some of the AccessControl libraries are part of the closure for UAP which is why some of them are includded in the meta-package's runtime assets. This issue is a good place to track the discussion of whether or not to include them for UAP, and if the decision is to remove them, then break all of the dependencies. I did to an initial try of removing them, and it is not trivial since  it would mean changing their configurations from netstandard to platform-specific (netcoreapp and netfx) and do that as well for all assemblies that depend on them, which were quite a few.

**Comment by joperezr** [comment]
Today, our uap layout for runtime is only pulling `System.Security.AccessControl` into the closure because `Microsoft.Win32.Registry` needs it, which is used by `System.Diagnostics.Process`. We potentially won't want Registry to be in UAP either, so perhaps this will be fixed by fixing #15966

**Comment by weshaggard** [comment]
Move this to 2.0 because we need to decide whether or not to ship a netstandard version of this library or not before we ship .NET Core 2.0 set of packages.

**Comment by tarekgh** [comment]
Marking as infra-structure as this is packaging decision.

**Comment by weshaggard** [comment]
@karelz should we add an area-packaging?

**Comment by tarekgh** [comment]
and area-Documentation too :-)

**Comment by karelz** [comment]
In general: Area labels make sense if there is 10+ issues. It is definitely reasonable to split larger areas (100+) into smaller that way.

I don't like area-Documentation. Having Documentation issue type makes area owners aware what is happening in the area and where we lack docs. Documentation is part of the end-to-end product and we will have to help with it. The good news is that actionable edits can be filed in docs repo, however we will need to chip in with samples, how-to, etc. Tracking that in CoreFX is IMO good idea.
fyi @mairaw 

area-Packaging is currently part of area-Infrastructure ([explicitly called out](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#areas)). I don't mind splitting it off, if it forms non-trivial part of the area-Infrastructure (let's say 20%+ or 10+ issues at least) or if it has non-trivial incoming rate.
@mellinoe @ericstj thoughts?

**Comment by tarekgh** [comment]
> The good news is that actionable edits can be filed in docs repo,

Does the documentation issues under area-Meta qualify for moving to the doc repo? if not then having area-documentation would make sense at that time.

**Comment by karelz** [comment]
@tarekgh what kind of docs are those? API docs? Repo docs? How may are there?

**Comment by karelz** [comment]
... and we should probably take it offline (either on area-Meta issue or into email)

**Comment by weshaggard** [comment]
This issue has been addressed the only AccessControl library part of UAP is the base System.Security.AccessControl library.
