### ISSUE TITLE
Need to bring back automated publishing of  Microsoft.Private.PackageBaseline

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#17675]
With the merging of the dev/eng branch to master (1/13/2017), we stopped getting updated versions of  Microsoft.Private.PackageBaseline on the myget feed.  @ericstj very helpfully provided a workaround for the time being, but for repos like WCF it would be very helpful to get this package back.

**Comment by wtgodbe** [comment]
The version of this package from master is being published regularly to the myget feed now - closing.
