### ISSUE TITLE
SerialPort: Move background Thread to Task

### ISSUE THREAD

**Issue by willdean** [dotnet/corefx#17696]
`SerialStream` (internal to `SerialPort`) currently does a `new Thread()` to make a `WaitForCommEvent` thread which blocks on `::WaitCommEvent` and dispatches events into the application's code.

The use of the background thread has created problems with unhandled events escaping (see #17661 & #17666) and is also possibly some part of an close/re-open problem described in #16261 (I'm not sure if it is or isn't).

It is worth investigating if we could change from a background `Thread` to `Task.Run` and then await the completion of this Task in the relevant dispose method.  This would bring exceptions back properly where they can be sensibly handled, and would ensure that the thread was finished before returning from the dispose.

At present no reference to the background thread is held by `SerialStream`, so it's impossible for it to make sure it's complete before finishing the close/dispose.

One for the future...

**Comment by JeremyKuhne** [comment]
Completed with #19146
