### ISSUE TITLE
Desktop and Core behavior differences in System.Net.Http

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#17691]
There are some differences in behavior between Desktop and core which are causing tests like this one fail on Desktop:

https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs#L281

cc: @davidsh

**Comment by danmosemsft** [comment]
@safern you can use the test-run-desktop label

**Comment by safern** [comment]
Sure. Will do so on next issues.
