### ISSUE TITLE
Omissions in types supported by both Desktop and Core - System.Data.SqlClient

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#17708]
For api compatibility between Desktop and Core we need to adjust these types in the System.Data.SqlClient area: (more info here: https://github.com/dotnet/corefx/issues/15255)

```
+ System.Data.IDataRecord (SqlDataRecord)
+ System.IServiceProvider (SqlClientFactory)
+ System.ICloneable (SqlCommand, SqlConnection, SqlParameter)
```

IDataRecord and IServiceProvider add new apis that must be wisely implemented in the types above. ICloneable needs to be added to these three classes. Simple migration from netfx isn't possible as those classes have change significantly.

**Comment by ViktorHofer** [comment]
@saurabh500 @YoungGah can you please take a look into it. are there any arguments why these types shouldn't implement these interfaces?

**Comment by saurabh500** [comment]
@ViktorHofer 

> System.Data.IDataRecord (SqlDataRecord)

This can be brought in. The source of .Net Framework would be sufficient for this implementation.

> System.IServiceProvider (SqlClientFactory)

I don't  see the value of implementing this API. This is because the API works with DpProviderServices https://msdn.microsoft.com/en-us/library/system.data.common.dbproviderservices(v=vs.110).aspx This API is not part of .Net Core.

> System.ICloneable (SqlCommand, SqlConnection, SqlParameter)

ICloneable can be implemented for the types above. I think that the .Net Framework source can be brought in for `SqlCommand` `SqlConnection` and `SqlParameter`

**Comment by ViktorHofer** [comment]
Thank you @saurabh500! I looked into it before and a 1:1 implementation from netfx isn't possible as for ICloneable the SQL classes changed dramatically (I have no idea what props need to be cloned now) and the IDataRecord is also somehow different now. 

Can you take this issue?

The omission of the IServideProvider sounds reasonable and I will mark it as a intentional change from netfx.

**Comment by saurabh500** [comment]
@ViktorHofer I can take this issue. What will happen if this is not addressed for 2.0 ?

**Comment by ViktorHofer** [comment]
Compatibility between netfx and core won't be guaranteed for System.Data.SqlClient. The reason why we are putting so much effort into aligning APIs (baselining) essentially is that there won't be any breaking changes for our Customer. E.g. they might need to cross-compile for NET461 and NETCOREAPP_20 because of diffent behaviors.

**Comment by danmosemsft** [comment]
In theory for Netfx and NetCore they could gamble their codepath won't be followed or use runtime checks. 

However if they use native compilation -- for example for an app in UWP -- it will fail to compile even if the codepath is not used at runtime (or at least if it can't determine that). So for UWP it's important that all imports exist, or #if is necessary (which aside from being ugly requires the library to be recompiled)

**Comment by saurabh500** [comment]
@danmosemsft and @ViktorHofer Thanks for the explanation. I have added a PR for SqlDataRecord. We will bring the other types in sync with Framework.

**Comment by saurabh500** [comment]
@ViktorHofer @danmosemsft 
For System.IServiceProvider (SqlClientFactory) , is it better to omit it, or to add it with a NotSupported exception ? I have mentioned the reason for not supporting this interface above. 
If we add the interface impl, then the behavior is not compatible with NetFx and if we omit it then there are problems that are going to surface as @danmosemsft mentioned. 

Let me know what you think SqlClientFactory? Which of the two approach is a better compromise?

**Comment by danmosemsft** [comment]
@weshaggard what do you think of the value of adding API that exists on desktop but throws PNSE on Core? Am I correct that generally it's goodness because it avoids breaking native compilation?

**Comment by weshaggard** [comment]
>@weshaggard what do you think of the value of adding API that exists on desktop but throws PNSE on Core? Am I correct that generally it's goodness because it avoids breaking native compilation?

I don't think there is much value. It is probably worth looking at some usage data to back up the decision to not support it but if it is only going to throw PNSE I would just exclude it from core and only add it if we get requests (given this is not part of the standard).

**Comment by danmosemsft** [comment]
What about that native compilation aspect? I bring a library that imports the API, it may not use it, but I can't native compile iwth it.

**Comment by weshaggard** [comment]
>What about that native compilation aspect? I bring a library that imports the API, it may not use it, but I can't native compile iwth it.

The .NET Native compiler is pretty resilient to these type of things and I think it will just work and generate a MissingType/Member exception for those if you use them at runtime. Either way though our plan was never to have every API that netfx has to avoid this so there is always a possibility of this if someone consumes a netfx library.

**Comment by danmosemsft** [comment]
Hey Morgan so I know once and for all, in exactly what circumstances will native compilation fail due to missing imports? 

Clearly we know having a [DllImport] pointing to libc fails. Does it fail if the native dll is there but not the export? As for managed imports, from @weshaggard comment above it sounds like compile succeeds.

Is all that right?

**Comment by danmosemsft** [comment]
Oops @morganbr see above

**Comment by morganbr** [comment]
It depends on an ILC flag; For most customer cases, a missing dll or export would just trigger a compile warning and an exception if it gets called. For most test cases, a missing dll or export would cause a launch failure. It would be much better to just not have missing imports.

CC @yizhang82 to keep me honest.

**Comment by yizhang82** [comment]
Correct. In .NET native all imports are early bound (unlike CoreCLR/desktop). Missing imports/dll is really *bad* and will cause launch failures. If you need delay loading, there isn't a good way to do it right now in managed code because loadLibrary is not part of WACK. There are a few options:
1. Ask Windows for LoadLibrary
2. We implement the C++ delay loading (a few week to a month of throw-away binder work) in .NET native
3. We create a C++ Dll just for delay loading purpose

**Comment by morganbr** [comment]
@danmosemsft I should also clarify that missing managed types/methods are different than P/Invokes to missing C++ exports. Missing managed types/methods work as @weshaggard described -- ILC mostly tries to just emit a warning and the runtime throws TypeLoadExceptions/MissingMethodExceptions if you try to use them. It's "best effort" support, so there are some cases that can fail native compilation (mostly if you have missing interfaces or structs).

**Comment by yizhang82** [comment]
@morganbr @danmosemsft I forgot to mention that we do have a safe guard in place that if the API is not part of windowsapp.lib, we'll emit a throw statement for that p/invoke as well, so it supports only the negative case. But this might be all that is required.

**Comment by danmosemsft** [comment]
Thanks. And yes, I caused confusion by asking about native and managed at the same time.

**Comment by danmosemsft** [comment]
@saurabh500 I think the upshot is it's a matter of taste, stubs with PNSE might make sense for a few members, for something larger it seems there isn't a great reason to do that.

**Comment by ViktorHofer** [comment]
IDataRecord and ICloneable implemented and merged into master. Decision made to not implement IServiceProvider, see discussion above. Closing.
