### ISSUE TITLE
Need Single Thread Apartment support to allow use of some COM objects

### ISSUE THREAD

**Issue by jeffbi** [dotnet/corefx#17711]
PowerShell cmdlets `Enable-WSManCredSSP` and `Disable-WSManCredSSP` require use of `IGroupPolicyObject`, which requires STA.

The PowerShell folk need to be able to port those cmdlets to Core (see [PowerShell/PowerShell#3353](https://github.com/PowerShell/PowerShell/issues/3353))

This relates to an earlier corefx issue, #522.

**Comment by karelz** [comment]
cc @yizhang82 @kouvel - do you guys have any insights here?

**Comment by kouvel** [comment]
`Thread.SetApartmentState` and `Thread.TrySetApartmentState` are available now in the latest Core, they can be called on a `Thread` instance before starting the thread to start it in STA mode. .NET Core 2.0.0 would include these APIs.

**Comment by yizhang82** [comment]
If it is main thread, use [STAThread]. It is also available in .NET Core 2.0

**Comment by karelz** [comment]
Very cool. Closing as fixed in 2.0 then.
