### ISSUE TITLE
Desktop: System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_CreateFromFile.FileInUse_CreateFromFile_SucceedsWithReadOnly failed with system.IO.IOException

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#17725]
Configuration: Outerloop_netfx_windows_nt_debug (build[#1](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/1/testReport/System.IO.MemoryMappedFiles.Tests/MemoryMappedFileTests_CreateFromFile/FileDoesNotExist_mode__Truncate_/))

Failed test: System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_CreateFromFile.FileInUse_CreateFromFile_SucceedsWithReadOnly

Message:
~~~
System.IO.IOException : The process cannot access the file 'C:\\Users\\dotnet-bot\\AppData\\Local\\Temp\\MemoryMappedFileTests_CreateFromFile_dd2twmrj.gsl\\FileInUse_CreateFromFile_SucceedsWithReadOnly_626' because it is being used by another process.
~~~

Stack Trace:
~~~
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) 
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) 
at System.IO.FileStream..ctor(String path, FileMode mode, FileSystemRights rights, FileShare share, Int32 bufferSize, FileOptions options) 
at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile(String path, FileMode mode, String mapName, Int64 capacity, MemoryMappedFileAccess access) 
at System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_CreateFromFile.FileInUse_CreateFromFile_SucceedsWithReadOnly() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.IO.MemoryMappedFiles\tests\MemoryMappedFile.CreateFromFile.Tests.cs:line 628
~~~

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/1/testReport/System.IO.MemoryMappedFiles.Tests/MemoryMappedFileTests_CreateFromFile/FileInUse_CreateFromFile_SucceedsWithReadOnly/

**Comment by danmosemsft** [comment]
```c#
            using (TempFile file = new TempFile(GetTestFilePath(), Capacity))
            using (MemoryMappedFile mmf1 = MemoryMappedFile.CreateFromFile(file.Path, FileMode.Open, null, Capacity, MemoryMappedFileAccess.Read))
            using (MemoryMappedFile mmf2 = MemoryMappedFile.CreateFromFile(file.Path, FileMode.Open, null, Capacity, MemoryMappedFileAccess.Read))
```
This scenario (write then immediately read, ...) is what provokes indexers and anti virus scanners. @mmitche I assume we have all that disabled ..

**Comment by danmosemsft** [comment]
Ah, this is a desktop test. Perhaps it didn't run before and this is an actual behavior change.

**Comment by danmosemsft** [comment]
This is caused by https://github.com/dotnet/corefx/pull/6152 which is obviously an intentional change.

**Comment by danmosemsft** [comment]
@ianhays do  you mind taking this one?

**Comment by danmosemsft** [comment]
Leaving in 2.0 as it does seem likely that we want to change our 2.0 behavior to match desktop.

**Comment by stephentoub** [comment]
@danmosemsft, see https://github.com/dotnet/corefx/pull/17655

**Comment by Jiayili1** [comment]
Failed again here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/21/testReport/System.IO.MemoryMappedFiles.Tests/MemoryMappedFileTests_CreateFromFile/FileInUse_CreateFromFile_SucceedsWithReadOnly/

**Comment by Jiayili1** [comment]
This issue is repro on Full Framework Tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170418.01/workItem/System.IO.MemoryMappedFiles.Tests/analysis/xunit/System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_CreateFromFile~2FFileInUse_CreateFromFile_SucceedsWithReadOnly

**Comment by Jiayili1** [comment]
This issue is repro on desktop, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/30/testReport/System.IO.MemoryMappedFiles.Tests/MemoryMappedFileTests_CreateFromFile/FileInUse_CreateFromFile_SucceedsWithReadOnly/
