### ISSUE TITLE
Cleanup System.Runtime test in netfx configuration

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#17723]
I'd like to add a `netfx` test configuration to System.Runtime. Is this something that would be a good idea? If so, I'd like to work on it - hopefully shouldn't be too hard!

Maybe someone's already working on it, so I'm making this issue to track this and claim it if no one is working on it!

**Comment by karelz** [comment]
@danmosemsft @AlexGhiondea @joperezr what do you think?

@hughbe I assume you mean to have tests specific to netfx. While that is useful, I don't think we want to have gazillion of such tests in CoreFX. IMO the key value is to have tests which cover both/all runtimes (Core, Desktop, Mono). Thinking that we will ever use CoreFX test bed as primary Desktop testing is IMO sci-fi.
cc @jkotas as he has opinions in the space ...

@hughbe even if there's agreement, I would like to ask you/encourage you to help us focus on delivering 2.0 over next few weeks - contribute to 2.0 issues/test improvements (see #17619 for details). Thanks!

**Comment by jkotas** [comment]
It should be sufficient to have tests that are expected to fail on desktop disabled in corefx, with a comment on why they are is disabled. I do not think we need a duplicate equivalent tests that work on desktop. The desktop testing is done by large old internal system. It is very unlikely that corefx testbed is going to replace it.  The primary reason for running corefx tests on desktop is to find unexpected differences and bugs in .NET Core, not to find bugs in desktop.

**Comment by danmosemsft** [comment]
I agree with @jkotas . @hughbe could you explain what your goal is?

**Comment by hughbe** [comment]
Sure - I observed that we're doing a lot of stuff to make sure we either document (by tests) or align with the behaviour of netfx. I wanted to see if System.Runtime could benefit from this.
So far, I've found one 2.0 bug (#17730), so it might be worth running netfx tests against System.Runtime

**Comment by danmosemsft** [comment]
Since it does not have a `netfx` configuration, we build and test its `netstandard` configuration (as the nearest compatible) when targeting netfx. So all tests will run against netfx, unless they are attributed otherwise.
https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/Configurations.props#L6
Let me know if you're seeing differently.

**Comment by hughbe** [comment]
I've got my own branch that I've updated the configuration for (https://github.com/hughbe/corefx/tree/runtime-tests-netfx)

But I'll look to work on 2.0 stuff as Karel mentioned

**Comment by danmosemsft** [comment]
@hughbe if I'm understanding right, all your code in that branch can go into CoreFX, you just don't need the .props edit. You get the netfx tests to run by doing `/p:targetgroup=netfx`. Does that not match what you see?

**Comment by hughbe** [comment]
Oh, haven't tried that! Was under the impression I had to add a netfx configuration!

**Comment by danmosemsft** [comment]
@joperezr did I miss anything?

**Comment by safern** [comment]
> @hughbe if I'm understanding right, all your code in that branch can go into CoreFX, you just don't need the .props edit. You get the netfx tests to run by doing /p:targetgroup=netfx. Does that not match what you see?

+1. This is exactly what we are trying to achieve with contracts that are part of the standard, have them built against net standard and run against netfx. We should only add the netfx configuration to the tests if they use an specific contract that is not part of netstandard.

Building against net standard and running against netfx we are testing the scenarios that our costumers will be hitting when running a netstandard library on desktop. I think we should close this issue.

PD. Great progress @hughbe thanks for your huge effort on getting S.R clean for desktop this is really helpful!

**Comment by hughbe** [comment]
> Building against net standard and running against netfx we are testing the scenarios that our costumers will be hitting when running a netstandard library on desktop. I think we should close this issue.

My intention in opening this issue was tracking getting System.Runtime.Tests passing with netfx, not actually adding the configuration - I may have confused things by making that the title of this issue

**Comment by karelz** [comment]
Great progress indeed, I updated the issue title to reflect the real goal. Feel free to update it.
