### ISSUE TITLE
(System.Random instance).Next - returning same numbers

### ISSUE THREAD

**Issue by xmrbrz** [dotnet/corefx#17738]
When you call a new instance of System.Random, the "Next" method returns the same results: 
```c#
Console.WriteLine("\r\nSame Random instance: ");
Random R = new Random();
for (int i = 0; i < 3; i++)
	Console.WriteLine(R.Next(1, 10).ToString());

// 4
// 6
// 1

Console.WriteLine("\r\nNew Random instance: ");
for (int i = 0; i < 3; i++)
	Console.WriteLine((new Random()).Next(1, 10).ToString());

// 4
// 4
// 4
```

General info: 
```
C:\Users\user>dotnet --info
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4
Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```

Random Ref: C:\Users\user\.nuget\packages\system.runtime.extensions\4.3.0\ref\netstandard1.5\System.Runtime.Extensions.dll

**Comment by svick** [comment]
This has been the case for a very long time, see for example [this SO answer](http://stackoverflow.com/a/768001/41071). It's also called out [in the MSDN documentation for `Random`](https://msdn.microsoft.com/en-us/library/system.random(v=vs.110).aspx):

> […] the parameterless Random() constructor uses the system clock to generate its seed value. However, because the clock has finite resolution, using the parameterless constructor to create different Random objects in close succession creates random number generators that produce identical sequences of random numbers. The following example illustrates how two Random objects that are instantiated in close succession generate an identical series of random numbers. On most Windows systems, Random objects created within 15 milliseconds of one another are likely to have identical seed values. 
> 
> To avoid this problem, create a single Random object instead of multiple objects.

Fixing this would probably make the parameterless `Random` constructor slower, but that doesn't seem like an unreasonable price to pay to me. So maybe it's worth considering?

**Comment by xmrbrz** [comment]
No problem, just wanted to make sure. Thanks! :-)

**Comment by karelz** [comment]
I was about to close the issue as well, but given the amount of confusion (e.g. on StackOverflow), I wonder if we could add constructor overload or change default behavior like @svick suggests. The perf hit IMO does not matter. People who use it "right pattern" will call it just once. People who use the anti-pattern will get some perf hit and if they care, they can fix the anti-pattern.

Thoughts?

**Comment by karelz** [comment]
Even better -- it is already improved this way in .NET Core 2.0! - see https://github.com/dotnet/coreclr/commit/9f6a0b675e5ac0065a268554de49162c539ff66d

Thanks @jkotas for the hint (BTW: @jkotas is there anything you **don't** know? ;))
