### ISSUE TITLE
System.Net.NameResolution.Pal.Tests test fixture fails on Fedora 24 with "invalid argument" giving "Unknown gethostbyname/gethostbyaddr error code"' 

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#17749]
Failed twice in my PR https://github.com/dotnet/corefx/pull/17716/files but is not failing in the latest Fedora 24. My PR only touches globalization code.

It might be good to make this assert dump the actual code it's getting (`fprintf(stderr...` .. I don't know if we have such a macro defined already)

```
  dotnet: /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug_prtest/src/Native/Unix/System.Native/pal_networking.cpp:414: int ConvertGetHostErrorPlatformToPal(int): Assertion `false && "Unknown gethostbyname/gethostbyaddr error code"' failed.
  /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug_prtest/bin/Unix.AnyCPU.Debug/System.Net.NameResolution.Pal.Tests/netcoreapp/RunTests.sh: line 83: 48789 Aborted                 (core dumped) $RUNTIME_PATH/dotnet xunit.console.netcore.exe System.Net.NameResolution.Pal.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
  command exited with ExitCode: 134
  command failed, trying to collect dumps
  corefile:
  no coredump file was found
  /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug_prtest/src/System.Net.NameResolution/tests/PalTests
```

**Comment by danmosemsft** [comment]
@Jiayili1 if this fails again please include output as we now have more logging.

**Comment by danmosemsft** [comment]
Now we have more info m it's 'invalid argument'. No test name gets to the log, so probably someone needs to loop this test on Fedora 24.
```
  Starting:    System.Net.NameResolution.Pal.Tests
  /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug_prtest/src/Native/Unix/System.Native/pal_networking.cpp (414): error 22: Unknown gethostbyname/gethostbyaddr error code. Invalid argument (false failed)
  dotnet: /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug_prtest/src/Native/Unix/System.Native/pal_networking.cpp:414: int ConvertGetHostErrorPlatformToPal(int): Assertion `false && "assert_err failed"' failed.
  /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug_prtest/bin/Unix.AnyCPU.Debug/System.Net.NameResolution.Pal.Tests/netcoreapp/RunTests.sh: line 83:  9657 Aborted                 (core dumped) $RUNTIME_PATH/dotnet xunit.console.netcore.exe System.Net.NameResolution.Pal.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=IgnoreForCI -notrait category=failing -notrait category=nonlinuxtests
  command exited with ExitCode: 134
  command failed, trying to collect dumps
```

**Comment by karelz** [comment]
cc @steveharter @Priya91

**Comment by danmosemsft** [comment]
This is breaking all System.Net.NameResolution.Pal.Tests tests because of the native assert. eg 

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170406.02/workItem/System.Net.NameResolution.Pal.Tests/wilogs

**Comment by karelz** [comment]
I am curious to find out what caused the test failure now ... some accidental non-deterministic product regression?

**Comment by Jiayili1** [comment]
This issue is repro on portable core tests: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170407.01/workItem/System.Net.NameResolution.Pal.Tests/wilogs

**Comment by tmds** [comment]
@karelz clicking the link above gives me a page

> The site is currently private to Microsoft employees due to dependencies on Microsoft resources. 
> Until then, please continue to look at our Jenkins CI results at ci.dot.net

And then I can go and figure out at ci.dot.net myself where to find the build logs :(

Perhaps the portable builds has some other conditions of:
```
#if !HAVE_THREAD_SAFE_GETHOSTBYNAME_AND_GETHOSTBYADDR
#if !HAVE_GETHOSTBYNAME_R
```

Posix has a newer function to do `gethostbyname`: `getaddrinfo`. I wonder if that is available on all platforms .NET Core is targeting?
It may fix issues like this one. It's thread safe and it has some nice features like being able to filter based on IPv4/IPv6 enabled on machine. And on Linux (not required by Posix), results are ordered according to RFC 3484, which means the the first address is the one that has the highest chance of working.

**Comment by karelz** [comment]
@tmds thanks for useful info!
@janvorli can you please help with questions about targeted platforms?
@Priya91 can you please check it out?

@tmds the mc.dot.net is not ready for external contributors yet :( ... AFAIK it is the long-term plan.
Do you think you would benefit from access to it in general? If yes, please ping me over email and let's ask around if it is ok to open it up for our partners from RedHat (no promises as I don't know what kind of information is there - AFAIK it goes well beyond CoreFX/.NET Core).

**Comment by tmds** [comment]
@karelz 
> Until then, please continue to look at our Jenkins CI results at [ci.dot.net](ci.dot.net)

If this last link would link to the jenkins build instead of the general site, that would avoid the manual lookup. Looks like the info is in the url, so it should be feasible to get it into the link.

**Comment by karelz** [comment]
@Chrisboh is it doable to help RedHat folks to be productive?

**Comment by janvorli** [comment]
@tmds is the getaddrinfo supported on RHEL7.2? That's the OS where we build our portable stuff and it contains the minumal supported libc etc. From its doc, is seems it should be there, since it seems it was introduced in libc 2.3.xxx
As for our other supported targets, it seems to be supported on OSX, FreeBSD, NetBSD, Alpine Linux and Android too, so we should be able to use that.

**Comment by tmds** [comment]
It's available on rhel7.

**Comment by steveharter** [comment]
The only other 'valid' error from gethostbyname that is not accounted for is NETDB_INTERNAL, so that error value should be added to the ConvertGetHostErrorPlatformToPal method and any appropriate managed or pal code.

NO_ADDRESS is actually the same value as NO_DATA so the recent change here didn't do anything.

For cases where gethostbyname_r is called extended error information can be obtained from the last parameter to that method when NETDB_INTERNAL is returned.

**Comment by steveharter** [comment]
This is not related to NETDB_INTERNAL as my previous comment mentioned. The "invalid argument" (EINVAL) is not an 'official' return code via man pages, but is being returned in Fedora 24 anyway.

This test is triggering the assert:
```
System.Net.NameResolution.PalTests.NameResolutionPalTests.GetHostByName_InvalidHostName_Throws(hostName: \"...\") [STARTING]
```
This test was recently added to verify the fix made in https://github.com/dotnet/corefx/pull/17574

The proposed fix (in progress) is to check for EINVAL and if the last errno parameter of gethostbyname_r is either NO_DATA or HOST_NOT_FOUND then map to HOST_NOT_FOUND

**Comment by Jiayili1** [comment]
This issue is repro on portable core tests in build 20170413.01, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170413.01/workItem/System.Net.NameResolution.Pal.Tests/wilogs

**Comment by tmds** [comment]
@karelz @stephentoub @steveharter What do you think about replacing gethostbyname with getaddrinfo? I can do a PR.

**Comment by karelz** [comment]
@tmds It might go against some of the planned work on our side. Let me check offline first.

**Comment by karelz** [comment]
It is likely we will soon need to target platform where it is not available.
If we keep it under ifdef, we can make the change. Would that be valuable in such case for the platforms that support the new POSIX API?

**Comment by tmds** [comment]
I was under the assumption the old function was no longer needed and this would also clean-up the implementation.
If it is still needed, adding another ifdef will make the code more error-prone especially because the return types from gethostbyname and getaddrinfo are not the same.
getaddrinfo has been around for quite a while, I am curious what platform doesn't support it.

**Comment by steveharter** [comment]
Note that the issue reported above is fixed; that was referencing the 0413 build which was reported before the 'fix' was merged \ new build made...

On getaddrinfo, as long as it is supported on all platforms, and functionality is same\better (including perf) I don't see why we wouldn't want to move to that. We are using an obsolete API with gethostbyname.

**Comment by karelz** [comment]
> On getaddrinfo, as long as it is supported on all platforms

That is likely not going to be correct assumption in next 1-2 months. Please wait for official announcements around specifics ... (can't disclose them yet, sorry)
