### ISSUE TITLE
Add StringBuilder(Char)

### ISSUE THREAD

**Issue by iSazonov** [dotnet/corefx#17745]
## Rationale 
In PowerShell repo we got a report https://github.com/PowerShell/PowerShell/issues/3457 about
```c#
var allErrors = new StringBuilder('\n');
```
It is expected that allErrors initialized with '\n' char.
Really compiler _silently_ convert the char -> ushort -> int and use `StringBuilder(int capacity)` constructor.
Sample http://ideone.com/1pPHlZ

Currently we already have method `Append(char value)` so suggestion is to add new constructor   `StringBuilder(char value)`.

## Proposed API ##
```c#
public sealed partial class StringBuilder : ISerializable 
{ 
        // Proposed constructor
        public StringBuilder(char value);
}
```

**Comment by karelz** [comment]
@iSazonov it makes sense to me. Can you please format it into a formal API proposal? https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md
It is just much easier to read and review in larger group. Thanks!

**Comment by iSazonov** [comment]
@karelz Issue was reformatted.

**Comment by terrajobst** [comment]
This is a good point. The same problem would also exist for this piece of code:


```C#
var allErrors = new StringBuilder(' ', 8);
```

So I suggest we add these two:

```C#
public partial class StringBuilder 
{ 
    public StringBuilder(char value);
    public StringBuilder(char value, int repeatCount);
}
```

**Comment by danmosemsft** [comment]
Ouch, I'm surprised this didn't come up before.

**Comment by terrajobst** [comment]
So after discussion we think it's not worth it. It's been 20 years and this isn't a widespread enough problem.
