### ISSUE TITLE
Test runs are disabled when building on Linux

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#1776]
See the skip of RunTestsForProject in https://github.com/dotnet/corefx/blob/master/mono.targets.

**Comment by JeremyKuhne** [comment]
Need to put the runtime package in the Unix packages list, update the BuildTools test targets to use corerun from the packages directory, and remove the override mentioned above.

**Comment by joshfree** [comment]
@JeremyKuhne does this issue still exist?

**Comment by JeremyKuhne** [comment]
@joshfree It still exists.

**Comment by JeremyKuhne** [comment]
This was fixed.
