### ISSUE TITLE
Test: System.IO.Tests.WaitForChangedTests.Renamed_Success failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#17762]
Configuration: outerloop_netcoreapp_win10_debug ([build#1](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win10_debug/1/testReport/))

Failed test: System.IO.Tests.WaitForChangedTests.Renamed_Success

Message:
~~~
Assert.True() Failure\r\nExpected: True\r\nActual: False
~~~

Stack Trace: 
~~~
at System.IO.Tests.WaitForChangedTests.Renamed_Success() in D:\j\workspace\outerloop_net---1bfe87b0\src\System.IO.FileSystem.Watcher\tests\FileSystemWatcher.WaitForChanged.cs:line 226
~~~

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win10_debug/1/testReport/System.IO.Tests/WaitForChangedTests/Renamed_Success/

**Comment by Jiayili1** [comment]
Closed Issue: https://github.com/dotnet/corefx/issues/14983

**Comment by alexperovich** [comment]
This test has not failed in the past 6 days of runs. Please reopen if it happens again.
