### ISSUE TITLE
Desktop: Tests under "DataContractSerializerTests" failed with "System.TypeInitializationException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#17774]
Configuration: outerloop_netfx_windows_nt_debug

Failed tests under: DataContractSerializerTests

~~~
MESSAGE:
System.TypeInitializationException : The type initializer for 'DataContractSerializerTests' threw an exception.\r\n---- No method named set_Option\r\nExpected: True\r\nActual: False
+++++++++++++++++++
STACK TRACE:
at DataContractSerializerTests.DCS_ArrayAsRoot() ----- Inner Stack Trace ----- at DataContractSerializerTests..cctor() in D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime.Serialization.Xml\tests\DataContractSerializer.cs:line 32
~~~

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/3/testReport/(root)/DataContractSerializerTests/DCS_ArrayAsRoot/

**Comment by danmosemsft** [comment]
@Jiayili1 per https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md, the correct label is area-Serialization.

**Comment by danmosemsft** [comment]
@shmao not sure what the cause of this is. Contact @safern if you need info about how the desktop run works. Ibelieve there is some binding remapping going on.

**Comment by danmosemsft** [comment]
oops

**Comment by danmosemsft** [comment]
I don't repro this. Instead I get a variety of more real errors.

**Comment by safern** [comment]
I did get a repro on this one by running: 
```
msbuild src\System.Runtime.Serialization.Xml\tests\ReflectionOnly\System.Runtime.Serialization.Xml.ReflectionOnly.Tests.csproj /v:m /m /t:rebuildandtest /p:TargetGroup=netfx /p:Outerloop=true
```
Which is the test project that runs this tests by including them and defining constant `ReflecionOnly`.

The codepath that is failing is the tests ctor is under the #if ReflectionOnly condition:
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Serialization.Xml/tests/DataContractSerializer.cs#L32

**Comment by safern** [comment]
I see the error. So DataContractSerializer.Option property is not available in Desktop at all, so that is why it fails when trying to get the property setter through reflection. Will add netcoreapp condition in the #if
