### ISSUE TITLE
Question: Immutable views

### ISSUE THREAD

**Issue by alrz** [dotnet/corefx#17795]
Can we implement immutable interfaces for arrays, lists, dictionaries, etc?
```cs
var mutableArray = new[] { .. };
IImmutableArray<T> immutableArray = mutableArray;

var mutableList = new List<T> { .. };
IImmutableList<T> immutableList = mutableList;
```

**Comment by karelz** [comment]
At minimum there is layering problem (ImmutableCollections are sitting on top of the stack, not at the bottom where Array/List live).
I bet this was considered in the past. I would expect that there are some wrapper workarounds ...
I let experts answer - cc @AArnott @ianhays @safern

**Comment by omariom** [comment]
It will be confusing. Immutability implies thread safety as the underlying storage cannot change. That's not the case for mutable collections.

**Comment by AArnott** [comment]
@omariom is correct. Collections should only implement these immutable interfaces if they are truly immutable. 
If you want an interface that (mostly) blocks changing the underlying collection that is already implemented by these popular mutable collections, use the `IReadOnlyCollection<T>` and similar interfaces. 

You can learn more about the various kinds of mutability/immutability and the interfaces that support them on [my blog post on the subject](https://blogs.msdn.microsoft.com/andrewarnottms/2011/08/21/read-only-frozen-and-immutable-collections/).
