### ISSUE TITLE
Proposal: Add Overlaps(...) extension method for ReadOnlySpan<T>

### ISSUE THREAD

**Issue by ektrah** [dotnet/corefx#17793]
### Problem

A method reading from a `ReadOnlySpan<T>` and writing to a `Span<T>` may produce incorrect results if the two spans overlap and the method overwrites data it has not read yet.

Here is a minimal but complete example that demonstrates the problem:

```csharp
public static void Twice(ReadOnlySpan<byte> src, Span<byte> dst)
{
    for (var i = 0; i < src.Length; i++)
    {
        dst[2 * i + 0] = src[i];
        dst[2 * i + 1] = src[i];
    }
}

[Fact]
public static void Test1()
{
    var src = new byte[] { 1, 2, 3, 4, 5, 6 };
    var dst = new byte[] { 1, 2, 3, 4, 5, 6 };

    Twice(new ReadOnlySpan<byte>(src, 0, 3), new Span<byte>(dst));

    Assert.Equal(new byte[] { 1, 1, 2, 2, 3, 3 }, dst);
    // works!
}

[Fact]
public static void Test2()
{
    var src = new byte[] { 1, 2, 3, 4, 5, 6 };
    var dst = src;

    Twice(new ReadOnlySpan<byte>(src, 0, 3), new Span<byte>(dst));

    Assert.Equal(new byte[] { 1, 1, 2, 2, 3, 3 }, dst);
    // fails! actual value: { 1, 1, 1, 1, 1, 1 }
}
```

It's a very small corner case, but it can lead to very subtle, hard-to-find bugs.

The problem can be prevented in `Twice` by
* making a defensive copy, or
* adding a check if the two spans overlap.

The copy is much more expensive, so it would be nice if it could be avoided.

With `ArraySegment<T>` arguments, the check can look like this:

```csharp
public static void Twice(ArraySegment<byte> src, ArraySegment<byte> dst)
{
    if (src.Array == dst.Array &&
        src.Offset < dst.Offset + dst.Count &&
        dst.Offset < src.Offset + src.Count)
    {
        throw new ArgumentException();
    }

    for (int i = 0; i < src.Count; i++)
    {
        dst.Array[dst.Offset + 2 * i + 0] = src.Array[src.Offset + i];
        dst.Array[dst.Offset + 2 * i + 1] = src.Array[src.Offset + i];
    }
}
```

This proposal is to add an API that enables similar checks for spans.

### Proposed API

```csharp
public static class SpanExtensions
{
    public static bool Overlaps<T>(this ReadOnlySpan<T> first, ReadOnlySpan<T> second);
}
```

*Open questions:*

* Are overloads for all four combinations of `Span<T>` and `ReadOnlySpan<T>` needed
* Should the name be `Overlaps` (like `Equals`) or `Overlap` (like `SequenceEqual`)
* Should the method return `true` or `false` if one or both of the spans is empty
* Should the method return the overlapping range rather than a `bool`
* Does it belong in SpanExtensions
* ...

*Usage:*

```csharp
public static void Twice(ReadOnlySpan<byte> src, Span<byte> dst)
{
    if (src.Overlaps(dst))
    {
        throw new ArgumentException();
        // or
        src = src.ToArray();
    }

    for (int i = 0; i < src.Length; i++)
    {
        dst[2 * i + 0] = src[i];
        dst[2 * i + 1] = src[i];
    }
}
```

### Prototype Implementation

I've come up with the following implementation that I would use if there is no strong need for an official API. It's based on the current implementation of the [`SpanHelpers.CopyTo<T>`](https://github.com/dotnet/corefx/blob/f17a94868f4a62c22c75b5710d19ab928f896e5e/src/System.Memory/src/System/SpanHelpers.cs#L23) method.

```csharp
public static class SpanExtensions
{
    public static bool Overlaps<T>(this ReadOnlySpan<T> first, ReadOnlySpan<T> second)
    {
        ref T x1 = ref first.DangerousGetPinnableReference();
        ref T y1 = ref second.DangerousGetPinnableReference();

        ref T x2 = ref Unsafe.Add(ref x1, first.Length);
        ref T y2 = ref Unsafe.Add(ref y1, second.Length);

        // return (x1 < y2) && (y1 < x2)
        IntPtr diff1 = Unsafe.ByteOffset(ref x1, ref y2);
        IntPtr diff2 = Unsafe.ByteOffset(ref y1, ref x2);

        return (IntPtr.Size == sizeof(int) ? (int)diff1 > 0 : (long)diff1 > 0)
            && (IntPtr.Size == sizeof(int) ? (int)diff2 > 0 : (long)diff2 > 0);
    }
}
```

It looks simple, but I'm not sure if it's correct. For example, is it legal to have `Unsafe.Add` return a `ref` past the end of a span if the `ref` is not dereferenced?

------

### Update

:boom: The above implementation has a number of problems. A pull request with the latest code is [here](https://github.com/dotnet/corefx/pull/18731).

**Comment by jkotas** [comment]
> IntPtr diff1 = Unsafe.ByteOffset(ref x1, ref y2);
> IntPtr diff2 = Unsafe.ByteOffset(ref y1, ref x2);

Note that the GC can move the objects between these two lines and swap the order of `first` and `second` in the address space. The simple obviously correct implementation is to pin the pointers. You can do it without pinning too, but it is tricky to get it right.

**Comment by jkotas** [comment]
The same API was discussed in https://github.com/dotnet/corefxlab/issues/827 as well.

**Comment by ektrah** [comment]
@ahsonkhan - `up-for-grabs` means pull requests welcome if/when this proposal gets the `api-approved` label?

@jkotas - What are the steps for pinning a generic `Span<T>`? Does that need slow span/fast span-specific support?

For now, I only need to check if two `Span<byte>` overlap; updated code for future reference below.

```csharp
public static class SpanExtensions
{
    public static unsafe bool Overlaps(this ReadOnlySpan<byte> first, ReadOnlySpan<byte> second)
    {
        fixed (byte* x1 = &first.DangerousGetPinnableReference())
        fixed (byte* y1 = &second.DangerousGetPinnableReference())
        {
            byte* x2 = x1 + first.Length;
            byte* y2 = y1 + second.Length;

            return (x1 < y2) && (y1 < x2);
        }
    }
}
```

**Comment by ahsonkhan** [comment]
> - up-for-grabs means pull requests welcome if/when this proposal gets the api-approved label?

Yes, as per: https://github.com/dotnet/corefx/blob/860b6f14c8f4186aecf061befa1fbe7b02349999/Documentation/project-docs/issue-guide.md

> up-for-grabs: Small sections of work which we believe are well scoped. These sorts of issues are a good place to start if you are new. Anyone is free to work on these issues.

**Comment by jkotas** [comment]
> What are the steps for pinning a generic `Span<T>`? Does that need slow span/fast span-specific support?

You need to cast `DangerousGetPinnableReference` to `ref byte` using `Unsafe.As`.

**Comment by ektrah** [comment]
Possible implementation without pinning based on a suggestion by @nietras:

```csharp
public static class SpanExtensions
{
    public static bool Overlaps<T>(this ReadOnlySpan<T> first, ReadOnlySpan<T> second)
    {
        ref T x1 = ref first.DangerousGetPinnableReference();
        ref T y1 = ref second.DangerousGetPinnableReference();

        IntPtr offset = Unsafe.ByteOffset(ref x1, ref y1);

        ref T x2 = ref Unsafe.Add(ref x1, first.Length);
        ref T y2 = ref Unsafe.Add(ref Unsafe.AddByteOffset(ref x1, offset), second.Length);

        // return (x1 < y2) && (y1 < x2)
        IntPtr diff1 = Unsafe.ByteOffset(ref x1, ref y2);
        IntPtr diff2 = Unsafe.ByteOffset(ref y1, ref x2);

        return (IntPtr.Size == sizeof(int) ? (int)diff1 > 0 : (long)diff1 > 0)
            && (IntPtr.Size == sizeof(int) ? (int)diff2 > 0 : (long)diff2 > 0);
    }
}
```

(not thoroughly tested yet)

**Comment by ektrah** [comment]
Possible implementation without pinning based on a suggestion by @nietras:

```csharp
public static class SpanExtensions
{
    public static bool Overlaps<T>(this ReadOnlySpan<T> first, ReadOnlySpan<T> second)
    {
        ref T x1 = ref first.DangerousGetPinnableReference();

        IntPtr offset = Unsafe.ByteOffset(ref x1, ref second.DangerousGetPinnableReference());

        ref T y1 = ref Unsafe.AddByteOffset(ref x1, offset);
        ref T x2 = ref Unsafe.Add(ref x1, first.Length);
        ref T y2 = ref Unsafe.Add(ref y1, second.Length);

        // return (x1 < y2) && (y1 < x2)
        IntPtr diff1 = Unsafe.ByteOffset(ref x1, ref y2);
        IntPtr diff2 = Unsafe.ByteOffset(ref y1, ref x2);

        return (IntPtr.Size == sizeof(int) ? (int)diff1 > 0 : (long)diff1 > 0)
            && (IntPtr.Size == sizeof(int) ? (int)diff2 > 0 : (long)diff2 > 0);
    }
}
```

(not thoroughly tested yet)

**Comment by ektrah** [comment]
Looking further at the [`SpanHelpers.CopyTo<T>`](https://github.com/dotnet/corefx/blob/166e73faa842fc8d8c46737c0b7b68293af5e1dd/src/System.Memory/src/System/SpanHelpers.cs#L25-L44) implementation, it seems that `isOverlapped` gives false positives if the GC swaps the order of `src` and `dst` after the assignment to `srcGreaterThanDst` and before the calculation of `tailDiff`. That doesn't hurt, but it's not perfect. Does that warrant an issue?

cc: @jkotas @shiftylogic

**Comment by jkotas** [comment]
> Does that warrant an issue?

I think so - if you can come up with the detailed example on where it will result in incorrect behavior.

**Comment by ahsonkhan** [comment]
Is this proposal ready for review?

**Comment by nietras** [comment]
I was wondering if `Overlaps`/`IsSliceOf` https://github.com/dotnet/corefxlab/issues/827 (etc. ??) are not part of an overall functionality around detecting different **kinds** of overlap. A naive approach would define some kind of enum to return the kind of overlap e.g. for `source.Overlap(target)`:

 - `source` entirely before `target`, no overlap
 - `source` starts before `target` and ends inside `target`
 - `source` is entirely contained in `target`
 - `source` starts inside target `target` and ends after `target` end
 - `source` entirely after `target`, no overlap
 - `source` starts before `target` and ends after `target`, i.e. `target` is contained in `source`

But this would probably have perf downsides... but each overlap kind is then interesting for a given operation being performed e.g. for memory copying we need to know if `target` is after `source`, but the other way around is not a problem. So it all depends on the operation being performed...

I would then think we need to think about naming the specific methods in the context of these different kinds of overlaps, so we do not end up with naming that is ambiguous or similar.

**Comment by shiftylogic** [comment]
Are their scenarios other than the CopyTo scenario where this would be useful?

**Comment by ektrah** [comment]
@shiftylogic - I'm currently aware of three methods that do some variant of overlap check:

* IsSliceOf (https://github.com/dotnet/corefxlab/issues/827 | https://github.com/dotnet/corefxlab/pull/830)
* Overlaps (https://github.com/dotnet/corefx/issues/17793 | https://github.com/dotnet/corefx/pull/18731)
* SpanHelpers.CopyTo&lt;T&gt; (https://github.com/dotnet/corefx/issues/18608 | https://github.com/dotnet/corefx/pull/18730)

**Comment by shiftylogic** [comment]
IsSliceOf and Overlaps are effectively the same thing. CopyTo has baked in overlap logic and is the reason I've seen that Overlap is desired.

I'm curious where people would possibly use IsSliceOf / Overlaps within a real world scenario.

**Comment by ektrah** [comment]
@shiftylogic - I'm using Overlaps [here](https://github.com/ektrah/nsec/blob/a12d0c6f6102b14c9757d527451199b9aa129976/src/Cryptography/AeadAlgorithm.cs#L92-L93), [here](https://github.com/ektrah/nsec/blob/a12d0c6f6102b14c9757d527451199b9aa129976/src/Cryptography/AeadAlgorithm.cs#L138-L139), [here](https://github.com/ektrah/nsec/blob/a12d0c6f6102b14c9757d527451199b9aa129976/src/Cryptography/AeadAlgorithm.cs#L138-L139), [here](https://github.com/ektrah/nsec/blob/a12d0c6f6102b14c9757d527451199b9aa129976/src/Cryptography/KeyDerivationAlgorithm.cs#L77-L78), [here](https://github.com/ektrah/nsec/blob/a12d0c6f6102b14c9757d527451199b9aa129976/src/Cryptography/HkdfSha256.cs#L79-L82), and [here](https://github.com/ektrah/nsec/blob/a12d0c6f6102b14c9757d527451199b9aa129976/src/Cryptography/HkdfSha512.cs#L79-L82). Each is a real world instance of the problem described in the first post (overwriting data that has not been read yet).

**Comment by bartonjs** [comment]
Yep, quite a lot of crypto things are well defined when src==dest and when !src.Overlaps(dest), but completely run off the rails when src == dest+/-1 (&& cbData > 1).

**Comment by ahsonkhan** [comment]
@ektrah, can you please update the API proposal so that we have clear proposal of all the possible scenarios that @nietras mentioned (i.e. different combinations of overlapping of two spans)?

**Comment by nietras** [comment]
@ahsonkhan I think @ektrah proposal is fine as such, but if we add another overload returning element index for `Overlaps` then this should cover most cases together with a possible `Contains` (`IsSliceOf`) overload:
```csharp
public static class SpanExtensions
{
    public static bool Overlaps<T>(this ReadOnlySpan<T> first, ReadOnlySpan<T> second);
    public static bool Overlaps<T>(this ReadOnlySpan<T> first, ReadOnlySpan<T> second, out int elementIndex);
    public static bool Contains<T>(this ReadOnlySpan<T> first, ReadOnlySpan<T> second);
    public static bool Contains<T>(this ReadOnlySpan<T> first, ReadOnlySpan<T> second, out int elementIndex);
}
```
where `elementIndex` is the relative index of `second` to `first` if they overlap or `second` is contained in `first`, respectively. With `elementIndex` one can use this to ensure a given function still works if this index is within a certain range so for example:
```csharp
public static void RepeatEvenIndices(ReadOnlySpan<byte> src, Span<byte> dst)
{
    if (src.Overlaps(dst, out var elementIndex) && elementIndex >= -1)
    {
        throw new ArgumentException();
    }

    for (int i = 0; i < src.Length / 2; i++)
    {
        dst[i + 0] = src[i * 2];
        dst[i + 1] = src[i * 2];
    }
}
```

Naming is still open. Especially, I am concerned with `Contains` being confused with checking if **values** are contained and not whether the slice is contained. To be explicit we could name these `OverlapsSlice`/`ContainsSlice`, as I mentioned before. 

I do not like `IsSliceOf` because it "reverses" the relationship of container/parent and child. It is customary for such a method to be called on the container e.g. a perhaps poor example `List<int>.Contains` but I hope you understand. I would assume there might have to be added a similar function to `Buffer<T>` perhaps.

We still need to decide whether all overlaps methods should check "alignment" and return "false" if it does not match as @mgravell proposes and gives an example for in https://github.com/dotnet/corefx/issues/18750#issuecomment-296970771.

> I maintain that it is a scenario that exists

Regarding this, I do understand that it is perfectly legal to have e.g. a `Span<int>` that is not 4-byte aligned. And perhaps my phrasing was unfortunate and incorrect. What I meant was the in what world will you have a span `parentAligned` and `parentUnaligned` representing almost the **same** region of memory? And a `child` that you would then check in both to see which it belongs to? I understand your example, but why would you check `IsSliceOf` in that case?

But perhaps I am just being unimaginative. My concern is this would perhaps be counterintuitive for some users if they think the method in question simply checks if there is memory overlap or not, disregarding "alignment". We might have a **true negative** or **false negative** depending on the users expectation. I don't know, to me it just seems like a case that 99% of programs will never hit, since you will almost always have a 1:1 correspondance from `child` to `parent` for e.g. `Span<int>`, what scenario would have two spans representing the same or overlapping memory region for a parent? Perhaps @mgravell can give a real word example of a case for this?

In any case, if we include "alignment" check in this we need to be absolutely sure this is well documented and have a fallback for checking disregarding alignment i.e. perhaps casting to `Span<byte>` although that seems rather unsafe...

A possibility would also be to split the `alignment` check out of `ContainsSlice` and have an extension method for that too.

**Comment by karelz** [comment]
@ahsonkhan do you have plans to push it through API review anytime soon? (there is pending PR for the not-yet-approved-API)

**Comment by ahsonkhan** [comment]
The API proposed (original post) as is does not cover all the scenarios, given @nietras post:
> @ahsonkhan I think @ektrah proposal is fine as such, but if we add another overload returning element index for `Overlaps` then this should cover most cases together with a possible `Contains` (`IsSliceOf`) overload:
...

I haven't had a chance to think about it too much, but we should make sure that the API being proposed covers all scenarios and then review it.

Should it just be, include:
```C#
public static bool Overlaps<T>(this ReadOnlySpan<T> first, ReadOnlySpan<T> second);
```

Or, do we want other overloads like:
```C#
public static bool Overlaps<T>(this ReadOnlySpan<T> first, ReadOnlySpan<T> second);
public static bool Overlaps<T>(this ReadOnlySpan<T> first, ReadOnlySpan<T> second, out int elementIndex);
public static bool Contains<T>(this ReadOnlySpan<T> first, ReadOnlySpan<T> second);
public static bool Contains<T>(this ReadOnlySpan<T> first, ReadOnlySpan<T> second, out int elementIndex);
```

@ektrah, thoughts?

Also, @nietras, can you explain how alignment would affect the result of Overlaps?
> But perhaps I am just being unimaginative. My concern is this would perhaps be counterintuitive for some users if they think the method in question simply checks if there is memory overlap or not, disregarding "alignment". We might have a **true negative** or **false negative** depending on the users expectation. I don't know, to me it just seems like a case that 99% of programs will never hit, since you will almost always have a 1:1 correspondance from `child` to `parent` for e.g. `Span<int>`, what scenario would have two spans representing the same or overlapping memory region for a parent? Perhaps @mgravell can give a real word example of a case for this?

**Comment by ektrah** [comment]
@ahsonkhan - I don't have a strong opinion on what overloads and variants should be included. In my use case, I could do some extended checking if the spans overlap and the offset is greater than some safe threshold. But I'll probably just go for the simple solution and check if they overlap. For that, a single overload without the `out` parameter would be sufficient (plus an overload where the `this` parameter is a `Span<T>`.)

**Comment by nietras** [comment]
> an you explain how alignment would affect the result of Overlaps

@ahsonkhan as far as I understand @mgravell was mainly concerned with `Contains/IsSliceOf` which should then return `false` if alignment does not match. It definitely is a good question what `Overlaps` should return if alignment doesn't match, lately I have been thinking that these should in fact throw in case of alignment issue instead e.g. `ArgumentException("Alignment issue....")` since especially `Overlaps` starts getting tricky if we would return `false` even if there is overlap but simply due to alignment. In the other case, returning `true` when any overlap, has issues if the overload returning an index is used. So perhaps this should simply throw if alignment does not match for both `Contains` and `Overlaps`. Not sure how other people feel about this...

We might consider adding a specialized `SameAs`/ `IsSame` (or similar name) overload too for checking if two spans represent exactly the same region. Overall, we probably should rewrite/write a new proposal with all the overloads (I think all are needed) and their return values for different cases. I don't have a lot of time for this currently though :|

**Comment by mgravell** [comment]
I'm comfortable with it throwing in those scenarios, as long as it is
clearly documented. People messing with the data type is an edge case of
people who should already be walking on a tightrope of crazy above a pit of
spikes laced with anger. Exceptions do not scare us :)

**Comment by ektrah** [comment]
To avoid that we end up with nothing in .NET Core 2.1:

The last few replies above seem to indicate consensus on having a `bool Overlaps<T>(ReadOnlySpan<T>, ReadOnlySpan<T>)` method plus additional overloads that output an offset or whether a span is fully contained.

Would it be reasonable to add `bool Overlaps<T>(ReadOnlySpan<T>, ReadOnlySpan<T>)` now and consider those other overloads later?

cc @ahsonkhan @jkotas @nietras @mgravell

**Comment by nietras** [comment]
sorry, I have been wanting to add a proposal for Overlaps and Contains but
simply haven't had the time, I will see if I can make a minimal proposal
this weekend, to at least get it started.

**Comment by ahsonkhan** [comment]
Closing this in favor of https://github.com/dotnet/corefx/issues/24103

Let's finalize the proposed API there and push it to review :)
