### ISSUE TITLE
No host_name when connecting to SQL Server

### ISSUE THREAD

**Issue by frdnga** [dotnet/corefx#17801]
I am facing problems deploying an ASP.NET Core Web API using Entity Framework Core. 

When I connect to the SQL Server, the session has no host_name, in development there's no problem and works fine, but the production servers have a Logon Trigger that checks the host_name and the login_name to grant access, so I'm getting the error Logon failed for login 'user' due to trigger execution.

When I compare the sessions from a ASP.NET Web API using Entity Framework and the ASP.NET Core, the Core version has no host_name:

`SELECT *
FROM SYS.DM_EXEC_SESSIONS
where login_name like '%user%'`

![image](https://cloud.githubusercontent.com/assets/8509636/24593488/923ddd5e-17e9-11e7-82ad-13d18a65c4af.png)

Is there a way for ASP.NET Core to send the host_name in the connection to SQL Server?

I'm using AspNetCore v1.0.1 and EntityFrameworkCore v1.1.0

**Comment by saurabh500** [comment]
What's the version of Sqlclient are you using? We made changes in .Net core after 1.1 to add the host name.

**Comment by frdnga** [comment]
I'm using Sqlclient version 4.3.0

**Comment by saurabh500** [comment]
Thanks for the confirmation. SqlClient in 4.3.0 doesn't have this support l because it cannot access the host name. The next version based on ns2.0 is going to have this capability
