### ISSUE TITLE
HttpWebRequest.SendRequest fails on UAP due to settting MaximumAutomaticRedirections to 50

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/corefx#17812]
The UAP specific code in https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/netcore50/System/Net/HttpClientHandler.cs will throw PlatformNotSupportedException if the MaximumAutomaticRedirections is to set anything but 10 (citing WinInet behavior).
But the code in HttpWebRequest.SendAsync sets the property to the value from HttpHandlerDefaults which is 50. Basically any usage of the HttpWebRequest.SendAsync on UAP will fail due to this.

**Comment by davidsh** [comment]
Fixed with https://github.com/dotnet/corefx/pull/21511
