### ISSUE TITLE
Move wiki content to repository

### ISSUE THREAD

**Issue by sharwell** [dotnet/corefx#1781]
Currently the wiki for this project contains quite a bit of information related to the project. I am proposing that this content be moved into the repository, preferably into a top-level folder named "documentation" (or similar). The following are my reasons for this:

1. After cloning the repository, users are able to work offline but still need to go online to access to the wiki content.
1. The process for contributing to the wiki is problematic in many ways.
  * Pull requests cannot be submitted. There is no straightforward way for users without commit access to propose actual changes.
  * Content changes cannot be easily reviewed prior to incorporating them.
  * Users watching the repository are not notified to changes in the wiki content.

After moving this content, the wiki can be disabled to eliminate confusion about the location of this documentation.

As an alternative to the above, it would also be possible to create a new top-level repository in the dotnet organization called "corefx-wiki", the content of which is automatically pushed to the wiki for this repository (via a unknown script maintained and run elsewhere). This would at least resolve the issues above regarding the inability of community members to participate in the ongoing development of this information.

**Comment by akoeplinger** [comment]
Related issue I filed a while ago: https://github.com/dotnet/coreclr/issues/456, so :+1: from me on this proposal.

> As an alternative to the above, it would also be possible to create a new top-level repository in the dotnet organization called "corefx-wiki", 

Funny, exactly this already exists: https://github.com/dotnet/corefx-wiki. The problem is it's not regularly updated, which means contributing to the wiki this way is painful. I'd much prefer we get rid of it entirely.

**Comment by weshaggard** [comment]
I know @richlander had some ideas on how to do this. It would be nice if github had some easy way to point the wiki entry point to another root folder in the repo or another repo we could have the nice navigation and editing facilities. Especially given it is my understanding that the wiki is actually backed by a git repo.

**Comment by ellismg** [comment]
We should probably just do what coreclr did (a "Documentation" folder for most things, with the Wiki having a bunch of links into the repo's Documentation folder), but FWIW, Rich also created a [dotnet/corefx-wiki](https://github.com/dotnet/corefx-wiki) project if we want to keep the PR flow.

**Comment by ellismg** [comment]
I spoke with Rich and he is working on doing this.

**Comment by richlander** [comment]
I'm working on it now. I'm going to take some liberties at the same time on how the wiki is structured and also move docs to the coreclr repo if that feels like the right choice.

**Comment by richlander** [comment]
Just deleted both coreclr-wiki and corefx-wiki repos in prep for moving the wiki content.

**Comment by richlander** [comment]
PRs are now waiting. Both reference this issue.

**Comment by sharwell** [comment]
@richlander I noticed that the wiki is still enabled. Are you planning to remove that link (theoretically reducing questions about the location of "source of truth" documentation), or keeping it around as an index?

**Comment by richlander** [comment]
I was thinking about keeping a single page there, with ~3 links. The wiki button has strong muscle memory for folks, so I was going to help out folks that want to click it. Fair?

**Comment by sharwell** [comment]
As long as you send a message to GitHub Support requesting the ability to customize the target of that button, sure. :smile: If implemented, eventually it could just be a hyperlink into the right folder of the source tree.

**Comment by richlander** [comment]
@sharwell Love that idea! I'll send that mail.

**Comment by sharwell** [comment]
@richlander This seems to be complete. Were you waiting for something else before closing it?

**Comment by richlander** [comment]
Forgot about this. Thanks.
