### ISSUE TITLE
Omissions in types supported by both Desktop and Core - CannotSealType

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#17811]
Parent: https://github.com/dotnet/corefx/issues/15255

The following types are sealed in netcore but not in netfx:
```
System.Runtime.InteropServices.RuntimeEnvironment
System.Security.Cryptography.SHA1Managed
System.Security.Cryptography.SHA256Managed
System.Security.Cryptography.SHA384Managed
System.Security.Cryptography.SHA512Managed
System.Net.HttpVersion
```

@karelz I think multiple area labels make sense here as this issue is like a container for discussions around CannotSealType errors.

**Comment by ViktorHofer** [comment]
System.Net.HttpVersion is defined in netfx like this:

```
public class HttpVersion {
        public static readonly Version  Version10 = new Version(1,0);
        ...
    }
```

In corefx HttpVersion is defined as a static class. Therefore we get those omission errors in ApiCompatBaseline.netcoreapp.netfx461.txt:

```
CannotMakeTypeAbstract : Type 'System.Net.HttpVersion' is abstract in the implementation but is not abstract in the contract.
CannotSealType : Type 'System.Net.HttpVersion' is sealed in the implementation but not sealed in the contract.
MembersMustExist : Member 'System.Net.HttpVersion..ctor()' does not exist in the implementation but it does exist in the contract.
```

Should we leave it static as it is now? I think the Constructor Usage is like non-existing at all: https://apisof.net/catalog/System.Net.HttpVersion..ctor()

cc: @danmosemsft, @weshaggard

**Comment by ViktorHofer** [comment]
All of these types are also sealed in netstandard20

**Comment by karelz** [comment]
For truly cross-cutting work, we have area-Meta :)
Multiple area labels = no responsibility :( ... it doesn't work well in my experience ...
