### ISSUE TITLE
Ensure we build packages for everything that's been impacted by `net461` > `netstandard2.0` remapping.

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#17819]
See https://github.com/dotnet/standard/issues/282.

We need to examine all the 1.1 packages to see if anything else is impacted in a similar way.

**Comment by ericstj** [comment]
Here's the set of packages in this category:
System.AppContext
System.ComponentModel.TypeConverter
System.Diagnostics.Tracing
System.IO
System.Linq.Expressions
System.Linq
System.Reflection
System.Reflection.TypeExtensions
System.Runtime.Extensions
System.Runtime.InteropServices
System.Runtime
System.Security.Cryptography.Algorithms
System.Security.Cryptography.Cng
System.Text.RegularExpressions

Of these, only System.Reflection.TypeExtensions is not subsumed by netstandard.

**Comment by weshaggard** [comment]
System.Security.Cryptography.Cng was also recently removed from netstandard. @bartonjs has an issue https://github.com/dotnet/corefx/issues/17667 to add the package back for it.

**Comment by ericstj** [comment]
I see.  I used 2.0.0-beta-25123-01 for this analysis.
