### ISSUE TITLE
SBCSCodePageEncoding with ExceptionFallback throws NullPointerException

### ISSUE THREAD

**Issue by RavuAlHemio** [dotnet/corefx#17839]
When decoding a byte array to a string using a single-byte character set code page encoding with `DecoderFallback.ExceptionFallback` as the decoder fallback, upon encountering a byte not defined in the encoding, the method `System.Text.SBCSCodePageEncoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, DecoderNLS decoder)` throws a `System.NullReferenceException`.

The expected behavior here is to throw a `System.Text.DecoderFallbackException`.

Test program:
```cs
using System;
using System.Linq;
using System.Text;

namespace GetStringNullReferenceException
{
    class Program
    {
        static void Main(string[] args)
        {
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
            Encoding win1252 = Encoding.GetEncoding("windows-1252", EncoderFallback.ExceptionFallback, DecoderFallback.ExceptionFallback);
            var enc = new byte[] { 0x81 };
            Console.WriteLine(win1252.GetString(enc));
        }
    }
}
```

Traceback is:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Text.SBCSCodePageEncoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, DecoderNLS decoder)
   at System.Text.EncodingNLS.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount)
   at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
   at System.Text.EncodingNLS.GetString(Byte[] bytes, Int32 index, Int32 count)
   at GetStringNullReferenceException.Program.Main(String[] args) in C:\temp\GSNRE\Program.cs:line 14
```

Target framework is `netcoreapp1.1` with the package `System.Text.Encoding.CodePages` at version `4.3.0`.

**Comment by danmosemsft** [comment]
I repro in latest 2.0

**Comment by stephentoub** [comment]
@tarekgh, why Future rather than 2.0?  Just not that common?

**Comment by tarekgh** [comment]
The only difference is the type of the exception there. and this behavior already exist in the last 2 releases. I mean this is not a regression. so I am not seeing we should fix it on 2.0.0.0

**Comment by danmosemsft** [comment]
@tarekgh it sounds like this is potentially a breaking change for libraries written for full framework? That could meet the 2.0 bar, especially if it's impactful or likely to have widespread impact. 

I imagine this ought to be breaking in our desktop runs, if we don't have a test hole?

**Comment by tarekgh** [comment]
I marked as 2.0.0 and will look at it later.

**Comment by RavuAlHemio** [comment]
I would have pinned it as a breaking change too, but the situation is a bit more complicated: I checked today and Full Framework uses the ["best-fit" decoding for windows-1252](http://www.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WindowsBestFit/bestfit1252.txt), where the undefined codepoints (0x81, 0x8D, 0x8F, 0x90 and 0x9D) are simply mapped to the numerically equal Unicode codepoints (U+0081, U+008D, U+008F, U+0090 and U+009D, respectively).

I'm fine with both best-fit decoding and throwing `DecoderFallbackException`, with a preference for the latter, since, from a formal point of view, those windows-1252 codepoints [are undefined](http://www.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WINDOWS/CP1252.TXT). Either way, I'd say letting `NullReferenceException` bubble up from framework into user code is "impolite", especially since I haven't passed a null object to the framework method.

**Comment by tarekgh** [comment]
@RavuAlHemio thanks for the info. I'll look at this and fix it.

**Comment by tarekgh** [comment]
@danmosemsft are you sure you are able to repro it with the latest? I tried the exact code and I cannot repro it. 

@RavuAlHemio what version of System.Text.Encoding.Codepages.dll you are using? could you please share the details of this version?

I have strong believe this is the issue fixed by @stephentoub in the commit 
https://github.com/dotnet/corefx/commit/827e85b010702abe05ee86b6fbea7414b9eba342

**Comment by RavuAlHemio** [comment]
@tarekgh: My instance of `System.Text.Encoding.CodePages.dll` is from NuGet package `System.Text.Encoding.CodePages` version 4.3.0; the file version is 4.6.24705.1.

Since I had not originally found a GitHub issue on this subject, I assumed it had not been brought to the project's attention yet. I confess I was slightly intimidated by corefx's build process, so I didn't try to reproduce it on master, especially after @danmosemsft reported to have reproduced it on 2.0.

However, I have now succeeded building corefx master on my machine and cannot reproduce the exception anymore -- the current code of System.Text.Encoding.CodePages appears to use best-fit mapping again. Thanks for the fix and apologies for the chatter!

**Comment by tarekgh** [comment]
@RavuAlHemio thanks for reporting it. it is good anyway to validate the fix :-) and ensure we don't have any problem.

**Comment by stephentoub** [comment]
If we don't already have one, could we add a test to ensure this doesn't regress?

**Comment by tarekgh** [comment]
> If we don't already have one, could we add a test to ensure this doesn't regress?

I'll check that and will add the test if there is no one catching such issue.
