### ISSUE TITLE
SqlDependency Class Support

### ISSUE THREAD

**Issue by maike9** [dotnet/corefx#17833]
Does .Net Core/Entity Framework support SQL Dependancies and if not directly, is there a way in .Net Core to receive notifications when data changes in SQL Server?

**Comment by saurabh500** [comment]
@maike9 Right now the SqlDependecy support is not available in System.Data.SqlClient. We will look at adding support in future releases.

**Comment by grahamehorner** [comment]
Is there any possibility of a short term work around ? until officially supported?

**Comment by saurabh500** [comment]
Closing this as a duplicate of #8188 
We are tracking query notifications and related APIs for 2.1

**Comment by maike9** [comment]
Following up on this.   Was SqlDependancies added to .net core 2.1?

**Comment by mattchidley** [comment]
It appears to have been added in the 2.1.0 preview1

This is the SqlClient package where it SqlDependency exists:

https://www.nuget.org/packages/System.Data.SqlClient/4.5.0-preview1-26216-02

**Comment by gmcit** [comment]
@mattchidley , Thanks I was able to use the  preview version with SqlDependency.
