### ISSUE TITLE
On Linux, on an NTFS volume, DirectoryInfo.Delete() fails to delete the junction

### ISSUE THREAD

**Issue by jeffbi** [dotnet/corefx#17844]
Given this directory structure on an NTFS volume
```
E:.
+---sub
|   |   sym-to-other
|   |
|   +---junction-to-other
|   |
|   \---symd-to-other
|
\---sub_other
```
running `dir` from the Windows command line shows
```
04/02/2017  05:27 PM    <JUNCTION>     junction-to-other [\??\E:\link-test\sub_other]
04/02/2017  05:27 PM    <SYMLINK>      sym-to-other [E:\link-test\sub_other]
04/02/2017  05:27 PM    <SYMLINKD>     symd-to-other [..\sub_other]
```
Moving the NTFS device to a Linux box, `ls -a` from bash shows
```
lrwxrwxrwx 2 jeff jeff   72 Apr  3 14:10 junction-to-other -> /media/jeff/My Book/link-test/sub_other
lrwxrwxrwx 2 jeff jeff   68 Apr  3 14:10 symd-to-other -> ../sub_other
lrwxrwxrwx 2 jeff jeff  116 Apr  3 14:10 sym-to-other -> /media/jeff/My Book/.NTFS-3G/E:/link-test/sub_other
```

Creating a `DirectoryInfo` object for `"junction-to-other"` results in an object whose `Attributes` property has `Directory`. However, invoking `Delete()` on that object throws a `System.IO.IOException` with `HRESULT == 20`, and `Message == "Not a directory"`.

Invoking `Delete()` on objects created for the other two symbolic links successfully deletes the items.

**Comment by JeremyKuhne** [comment]
Tracking this with #17843.
