### ISSUE TITLE
Dead tests in System.IO.Ports

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#17857]
Should these be added to compilation, or deleted?

```
src/System.IO.Ports/tests/Legacy/Manual/Regression_142639.cs
src/System.IO.Ports/tests/Legacy/Manual/USB_Serial_Regression.cs
src/System.IO.Ports/tests/Support/Sleep.cs
```

@willdean

**Comment by willdean** [comment]
`Sleep.cs` can be deleted, it's just a command line delay tool - I don't know why it's here at all.

The other two are stand alone tests (one of which requires manual cable plug/unplug) which don't feel like a good fit for automated test.  I'm not really sure they're a good fit for any kind of test other than for the guy who was working on those particular bugs at some distant point - if they disappeared I don't suppose anyone would miss them.
