### ISSUE TITLE
Get tests building for Dataflow

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#17856]
The tests are in `src/System.Threading.Tasks.Dataflow/tests` but they need a .csproj added that builds them successfully, and issues opened for tests that fail, with those disabled against that issue number.

**Comment by stephentoub** [comment]
@danmostmsft, what is the problem here?  The dataflow tests are building and running fine as far as I can see:
```
  Discovering: System.Threading.Tasks.Dataflow.Tests
  Discovered:  System.Threading.Tasks.Dataflow.Tests
  Starting:    System.Threading.Tasks.Dataflow.Tests
  Finished:    System.Threading.Tasks.Dataflow.Tests

  === TEST EXECUTION SUMMARY ===
     System.Threading.Tasks.Dataflow.Tests  Total: 319, Errors: 0, Failed: 0, Skipped: 0, Time: 1.335s
```

**Comment by danmosemsft** [comment]
It's the wildcard that threw off my script.
