### ISSUE TITLE
Dataflow: Add options for Task Faulting

### ISSUE THREAD

**Issue by ObsidianPhoenix** [dotnet/corefx#17871]
When using a `DataBlock` in `Tpl.DataFlow`, if a task in the block becomes faulted, then the entire block shuts down and must be completely re-initialised before it can be used again.

For example

    var block = new ActionBlock<Action>(a => a.Invoke());

    block.Post(() => Console.WriteLine("First Item")); //Printed
    block.Post(() => Console.WriteLine("Second Item")); //Printed
    block.Post(() => throw new ApplicationException("Throwing an exception here")); 
    block.Post(() => Console.WriteLine("Fourth Item")); //Not Printed
    block.Post(() => Console.WriteLine("Fifth Item")); //Not Printed

When using the blocks to construct an asyncronous queue for items, this can cause issues. You need to recreate the block and re-post any queued items that have not been processed.

The below suggestions provide some additional functionality to allow devs to dictate whether a DataBlock should shut down in the event of a fault.

**Suggested Change**

Consider adding a new `ExecutionDataflowBlockOptions` property to control how the block acts in faulting scenarios. For example: `new ExecutionDataflowBlockOptions() { ContinueOnTaskFault = true; }` (`false` by default to preserve existing functionality).

This functionality would effectively shift responsibility for managing the block faults to the developer. If they want to stop the block, they can call either `Complete` or action a `CancellationToken`.

**Alternative**

Add a new `ExecutionDataflowBlockOptions` property to specify a Faulting action, e.g. `new ExecutionDataflowBlockOptions() { FaultAction = (args) => HandleFault(args); }`. In this case, args would contain a property akin to `IsFaulted` that the action can set to `false` if they do not wish the block to stop.

**Comment by ObsidianPhoenix** [comment]
As an extension to this, would it be necessary/preferable to provide some mechanism for draining these faulted items off the block? Or would it be acceptable to simply drop the message?

A `LinkTo` option could be supplied to allow faulted items to flow into another datablock. e.g.

`block.LinkFaultTo(DataflowBlock.NullTarget<DataFlowTaskFaultException>());`

This would allow developers to construct an entire flow chain off the back of an exception on the origin block, rather than simply draining the offending item out of the block.

**Comment by omariom** [comment]
I would do this:
```C#
var block = new ActionBlock<Action>(a =>
{
    try
    {
       a.Invoke();
    }
    catch (Exception ex) when !ex.IsCritical()
    {
        HandleException(ex);
    }
});
```

**Comment by ObsidianPhoenix** [comment]
@omariom I've done that in my use case at the moment, but it seems like something that would be better suited in the core product. 

My real scenario was actually in the predicates on the `LinkTo`, rather than the Block itself. In an ideal world this suggestion would cover that too, but I think it has some merit on its own even without covering the predicates.

e.g.

    var block = new TransformBlock<Action, Action>(a =>
    {
        return a;
    });

    var blockB = new ActionBlock<Action>(a => { return; });
    block.LinkTo(blockB, a => { a.Invoke(); return true; });

    block.Post(() => Console.WriteLine("First Item"));
    block.Post(() => Console.WriteLine("Second Item"));
    block.Post(() => throw new ApplicationException("Throwing an exception here"));
    block.Post(() => Console.WriteLine("Fourth Item"));
    block.Post(() => Console.WriteLine("Fifth Item"));

    Console.ReadLine();

**Comment by svick** [comment]
I think that having an option to easily ignore exceptions is a bad idea. Most of the time, exceptions should be handled, not ignored. Ignoring exceptions is sometimes the right option, but the library should not guide you to do that.

**Comment by ObsidianPhoenix** [comment]
I'm not necessarily suggesting that we should *ignore* exceptions. But I am suggesting that the responsibility for managing an exception should be shifted to the developer without completely crashing out the Block. 

I just think that failure of a single task on the block should not necessarily stop all tasks from ever being processed.

**Comment by omariom** [comment]
`ContinueOnTaskFault ` is basically a directive to swallow exceptions. 
I think exception swallowing should be done explicitly.

**Comment by stephentoub** [comment]
We don't plan to do anything related to this.  If a developer wants to eat exceptions, they can do so explicitly.  Thanks for the suggestion.
