### ISSUE TITLE
.NET Core API inclusion principles doc

### ISSUE THREAD

**Issue by MattWhilden** [dotnet/corefx#1790]
So, I was responding in #1420 and tried to hunt down some docs here that had a set of principles for what was/should be included in .Net Core. I couldn't find anything in my quick search. Maybe I missed it? Maybe we need to get something better together?

/cc @nexussays  @nguerrera @blackdwarf

**Comment by nexussays** [comment]
+1 Would love to see this.

Since you guys will have to define these principles internally before the community can contribute, what can we do to get you to prioritize it?

**Comment by nguerrera** [comment]
Assigning to @richlander and also cc @terrajobst.

**Comment by danmosemsft** [comment]
This is super old and is probably interesting but at this point I'm not sure that tracking it here is useful.
