### ISSUE TITLE
Add TryAdd/Remove extension methods in CollectionExtensions

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#17918]
We should add extension methods in CollectionExtensions:

 * `public static bool TryAdd(this Interface, T value)`
* `public static bool Remove(this Interface, out T value)`

For IDictionary.

> Any other interfaces we should add this methods on?

* I was thinking probably ISet<T> but it already has Add and Remove which both return a bool indicating if the operation was successful.

* Also I thought about ICollection<T> but it would only make sense adding Remove as adding would just add an element at the end of the collection so it should always be successful. 

cc: @danmosemsft @ianhays

**Comment by karelz** [comment]
API was approved in https://github.com/dotnet/corefx/issues/17275#issuecomment-291636863

@safern technically speaking, `Remove` was not mentioned there. I believe we still didn't let the PR through, so that's why, right?

**Comment by karelz** [comment]
Next step: Add the APIs with tests -- you can use example of recently added `IDictionary.GetValueOrDefault` extension method (also on `CollectionExtensions` type) - see parts of PR #16605

This should be fairly easy and straightforward to do.

**Comment by safern** [comment]
> [EDIT] I think I figured it out - it was incorrectly mentioned as TryRemove, so I updated it as well. Technically speaking this can be done independently on the Dictionary.Remove API PR which is in progress.

That is correct it was incorrectly mentioned. Thanks for adding next steps, @karelz

**Comment by nbarbettini** [comment]
I'll grab this, I'd love to be able to contribute to corefx.

**Comment by karelz** [comment]
Great! Ping me when you accept invitation for collaborator. That way we can assign you issues ... assigning to myself temporarily.

**Comment by nbarbettini** [comment]
Done @karelz

**Comment by safern** [comment]
Assigned to you @nbarbettini -- thanks for your passion in contributing. Please submit a PR when you're ready. I will be glad to help if you have any question.

**Comment by karelz** [comment]
Also, if you have any advice for improving docs for first-time contributors, please speak up -- see my plan in #17534 (or feel free to contribute those docs as well ;-))

**Comment by karelz** [comment]
cc @danmosemsft to help new contributors while I am on vacation :grin:

**Comment by orobert91** [comment]
Methods should be documented:

https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.collectionextensions.tryadd?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Collections.Generic.CollectionExtensions.TryAdd%60%602);k(DevLang-csharp)%26rd%3Dtrue&view=netcore-2.0

**Comment by danmosemsft** [comment]
Thanks @orobert91 could you please open an issue in https://github.com/dotnet/docs (or even offer a PR if you would like)
