### ISSUE TITLE
Review package content for all packages

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#17914]
Refactoring the build system and automatically harvesting past assets make it really easy for our packages to accidentally ship bits that are old or unnecessary.  Static validation makes sure that this won't cause install / ref-def issues, but it doesn't make sure that the packages are minimal.

We should review the package to make sure we aren't shipping anything we don't want.

**Comment by weshaggard** [comment]
The harvesting is causing the netstandard1.1 ref (4.0.1) to have a different version then the net45 shim (4.0.2) for the System.Runtime.InteropServices.RuntimeInformation package. See https://github.com/dotnet/standard/issues/295

**Comment by ericstj** [comment]
I noticed this one when enabling package validation.

I plan to re-enable package validation to address all issues like this and https://github.com/dotnet/corefx/issues/18160

**Comment by ericstj** [comment]
Also during review I plan to address #7528 by filling in not-supported implementations for any contract that has a netstandard ref but no netstandard lib, and we agree that it should stay that way.

**Comment by weshaggard** [comment]
>and we agree that it should stay that way.

What is our going to be our guidance to decide whether or not they should stay that way or not?
