### ISSUE TITLE
Verify System.ValueTuple package works on .NET Framework

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#17960]
After https://github.com/dotnet/corefx/pull/17893 the System.ValueTuple package no longer has a ref\netstandard1.0 reference and now has a net463 reference. We should verify that this package still works as expected on .NET Framework < 4.6.3.

I believe it will still work and pick the portable asset but just wanted us to double check once we get a package published after that PR. 

cc @jcouv @ericstj

**Comment by weshaggard** [comment]
@jcouv is this something you were able to verify with your recent work?

**Comment by jcouv** [comment]
@weshaggard No, my recent validation was not done with a whole package, but with binaries manually extracted from the package.
I still need to figure something out for this validation work item.

**Comment by weshaggard** [comment]
For this task you can try installing the package from our myget feed into a desktop 4.6.1 or 4.6.2 project to make sure it correctly works. I just wanted to ensure it didn't regress after the package changes.

**Comment by weshaggard** [comment]
@jcouv is this on track to finish by ZBB?

**Comment by jcouv** [comment]
Yes. I'll stop by on Monday to discuss some validation scenarios and I'll focus on that. Sorry for the delay.

**Comment by jcouv** [comment]
@weshaggard Is there a place we published this modified package (I could not find it on myget), or do I have to build it locally?

**Comment by weshaggard** [comment]
https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.ValueTuple/4.4.0-preview1-25305-02

**Comment by jcouv** [comment]
Thanks. I was looking for "corefx" :-s
I ran a few simple scenarios with .Net 4.6. Seems ok.

Did run into a weird issue with PdbReader crashing when opening a simple assembly from a .NET Standard 1.0 project with a reference to ValueTuple package: https://github.com/dotnet/roslyn/issues/19352
