### ISSUE TITLE
Implement HttpListenerTimeoutManager properties where possible for Managed.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#17977]
From @stephentoub in response to a question about implementing HttpListenerTimeoutManager:

The timeout manager isn’t just one thing: it’s a collection of various timeouts.  And some of them can be implemented:
-	Likely can:
o	DrainEntityBody: I’m not aware of any reason we couldn’t do this.  But IIRC, we’re not doing connection pooling, so it’s largely irrelevant, and we shouldn’t be throwing a PNSE from it, as it doesn’t really matter what the timeout value is.
o	EntityBody: We should be able to support this.  It’s a matter of how long we wait in socket receives to receive the full body.
o	HeaderWait: Similarly, we can time how long it takes to receive and parse the headers.
o	IdleConnection: Not relevant if we’re not connection pooling… again, throwing PNSE here seems like overkill.
o	MinSendBytesPerSecond: We can also time this and do the appropriate calculations.  This is all about the sends that we issue.
-	Likely can’t:
o	RequestQueue: I don’t believe we have access to the listen queue in the OS.

**Comment by danmosemsft** [comment]
This shows up in my PNSE scan. Note, usage ~0% in our data.

**Comment by karelz** [comment]
@stephentoub can you please help?
