### ISSUE TITLE
System.NullReferenceException in System.Net.Http.CurlHandler.CurlResponseStream.SignalComplete(Exception error, Boolean forceCancel)

### ISSUE THREAD

**Issue by wgraham17** [dotnet/corefx#17978]
We are seeing application crashes while running a .NET Core 1.1 application on Ubuntu with the following stack trace:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
    at System.Net.Http.CurlHandler.CurlResponseStream.SignalComplete(Exception error, Boolean forceCancel)
    at System.Net.Http.CurlHandler.CurlResponseStream.Dispose(Boolean disposing)
    at System.Net.Http.CurlHandler.CurlResponseStream.Finalize()
```

As far as I can tell, throwing an exception inside `Dispose` is a pretty bad idea -- this is amplified by the fact that there is no way to catch the exception thrown by a finalizer.

**Comment by stephentoub** [comment]
Can you share a repro?

**Comment by wgraham17** [comment]
@stephentoub I can't get a reliable repro, it happens in our application pseudo-randomly after a few hours of running.

**Comment by stephentoub** [comment]
@mrazza, you gave a thumbs up emoji to the post... do you have a repro?

**Comment by stephentoub** [comment]
@wgraham17, I think I found a way this could happen, though I've been unable to repro.  Is it possible this is occurring for you when a request is canceled very soon after it was issued?

**Comment by wgraham17** [comment]
It's not _outside_ the realm of possibility but we aren't explicitly cancelling requests.  🤔

**Comment by stephentoub** [comment]
Hmm, ok.  Do you change the timeout from its default of 90s, or is it possible you have a huge backlog of work that the default 90s timeout would cause cancellation to occur before the request could begin?  I'm struggling to find something else that would result in the call stack you shared, and without more details to go on, a repro, etc., I'm afraid I'm at a loss if #18008 doesn't fix the issue.

**Comment by wgraham17** [comment]
> is it possible you have a huge backlog of work that the default 90s timeout would cause cancellation to occur before the request could begin

Potentially. We are in the process of turning down our parallelism for this work.

What is a "huge" backlog? Hundreds of requests? Thousands?

**Comment by stephentoub** [comment]
> What is a "huge" backlog? Hundreds of requests? Thousands?

Enough that the request queued doesn't get processed for 90s (or whatever you may have changed the timeout to). I don't have an exact number of what it would take.  I'm just reaching in trying to explain how this could be happening.
