### ISSUE TITLE
Update performance docs

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#17981]
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/performance-tests.md seems to be very out of date. We need to get the docs updated or removed and pointers to a more generic document that explains how to run them in multiple repos.

**Comment by Clockwork-Muse** [comment]
Duplicate of #9257 ?

**Comment by brianrob** [comment]
Yes, it is a duplicate of #9257.
