### ISSUE TITLE
No test result generated under System.Linq.Parallel.Tests

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#17982]
No test result generated, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170406.01/workItem/System.Linq.Parallel.Tests/wilogs

**Comment by danmosemsft** [comment]
@alexperovich could you please look?

**Comment by alexperovich** [comment]
This was a problem talking to azure storage to upload the logs. @MattGal is investigating that.

**Comment by Jiayili1** [comment]
This issue is repro on portable core tests: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170407.01/workItem/System.Linq.Parallel.Tests/wilogs

**Comment by MattGal** [comment]
Given the same tests hit the same issue on multiple days, and the logging shows the tests passing but failing inside helix infra code, I am self-assigning this and will investigate today.

**Comment by MattGal** [comment]
I ran this test 50x on a helix VM with identical to this run files, no repro. Something strange is happening whenever this repros with dumpling earlier on in the logs.   I will keep investigating.

**Comment by danmosemsft** [comment]
@MattGal any luck? We still get this
…
  File "/home/helixbot/dotnetbuild/scripts/helix/saferequests.py", line 105, in request_with_retry
    raise last_error
TypeError: data must be a byte string
2017-04-18 17:26:53,627: ERROR: logs(86): _log_uncaught_exception: Unhandled error: data must be a byte string


https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170418.03/workItem/System.Linq.Parallel.Tests/wilogs

**Comment by MattGal** [comment]
Unfortunately not, even connecting to a SUSE 42.1 machine and running the exact same test in a loop I can't reproduce the problem.

**Comment by MattGal** [comment]
Should be fixed now.  Basically we hit a known issue with pyOpenSSL and upgrading our dependency solved it.   The run starting in ~20 minutes will show whether I'm right.

**Comment by danmosemsft** [comment]
This seems fixed

**Comment by Jiayili1** [comment]
This issue is repro on Portable Core tests (2.0.0), detail: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170522.01/workItem/System.Linq.Parallel.Tests/wilogs

**Comment by MattGal** [comment]
The issue initially reported is still fixed;  this is an instance of:
https://github.com/dotnet/core-eng/issues/779 

I'm hoping to address this bug this week.

**Comment by kouvel** [comment]
Looks like the other issue was fixed, closing. Please reactivate if I misunderstood.

**Comment by MattGal** [comment]
Should be fixed.  Generally we'll deploy sprint-ly which means it might repro again with bad luck today or tomorrow, but should not happen again after next week.
