### ISSUE TITLE
CI failure to clone repository in Innerloop OSX10.12 tests

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#18006]
E.g. https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug_prtest/1240/ and https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release_prtest/1243/

Doesn't seem to be affecting all such builds, but is affecting a lot of them.

**Comment by stephentoub** [comment]
Yeah, I believe @mmitche is working on it.  Thanks for opening an issue.

**Comment by danmosemsft** [comment]
Update, this is obviously still a major issue. I understand they are trying new hardware over the weekend.

**Comment by mmitche** [comment]
@danmosemsft Completed.  Please let me know if you see any other issues.

It;s even faster than before!

**Comment by danmosemsft** [comment]
@mmitche awesome! Are you planning to kick all the PRs so they can clear through the weekend or should I?

**Comment by JonHanna** [comment]
I tried kicking off a few, and while it's cloning them, they builds are all failing. E.g. https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug_prtest/1427/

**Comment by mmitche** [comment]
@JonHanna The log probably means someone checked in a regression:

09:14:24 Initializing BuildTools...
09:14:46 sed: 1: "/Users/dotnet-bot/j/wor ...": extra characters at the end of d command
09:14:46 ERROR: An error occured when trying to initialize the tools. Please check '/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest/init-tools.log' for more details.1
09:14:46 Build step 'Execute shell' marked build as failure

**Comment by mmitche** [comment]
@danmosemsft Started failing here: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/507/

**Comment by mmitche** [comment]
@danmosemsft This looks like the suspicious commit: https://github.com/dotnet/corefx/commit/a51ffd4fb32ac494ab4d34b4fe4ba1ece4ffb63c

**Comment by danmosemsft** [comment]
I'll see if reverting it helps. It may have been the build tools update.

**Comment by fujiy** [comment]
It's now working for my PR

**Comment by JonHanna** [comment]
This seems to be resolved.
