### ISSUE TITLE
HttpClient Error "An internal response size limit was exceeded"

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#18019]
@zenixgrace commented on [Wed Apr 05 2017](https://github.com/dotnet/standard/issues/293)

Hello,

I got an error "An internal response size limit was exceeded" when calling SendAsync method in HttpClient 
Is it about buffer size or what?
try to set MaxResponseContentBufferSize but no luck.

---

@weshaggard commented on [Thu Apr 06 2017](https://github.com/dotnet/standard/issues/293#issuecomment-292295245)

Question better suited for corefx.

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/18000
