### ISSUE TITLE
Potential ArgumentNullException in Microsoft.XmlSerializer.Generator

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#18015]
In Microsoft.XmlSerializer.Generator code, `TempAssembly._assembly` is never being assigned to and will alwaybe null. This causes ArgumentNullException [here](https://github.com/dotnet/corefx/blob/39514943cac0ca081894ac0763c2a91d30345e52/src/System.Private.Xml/src/System/Xml/Serialization/Compilation.cs#L130)

cc: @huanwu @shmao, @zhenlan

**Comment by shmao** [comment]
Thanks for opening the issue, @sepidehMS . The usage of `TempAssembly` is being added by @huanwu 's PR https://github.com/dotnet/corefx/pull/17967. The issue would be fixed by that PR.

**Comment by danmosemsft** [comment]
Please remove this if @sepidehMS checks it in:
```
                    // use exception in the place of Debug.Assert to avoid throwing asserts from a server process such as aspnet_ewp.exe
                    if (_assembly == null) throw new InvalidOperationException(SR.Format(SR.XmlInternalErrorDetails, "Failed to generate XmlSerializer assembly"));  // Remove after https://github.com/dotnet/corefx/issues/18015 is fixed

```

**Comment by shmao** [comment]
@danmosemsft That seems not checked in. I don't see it in the latest code.

Closing the issue as the PR had been merged.
