### ISSUE TITLE
netstandard AssemblyVersion in .csproj file is generating version 0.0.0.0

### ISSUE THREAD

**Issue by JoshClose** [dotnet/corefx#18068]
I have a netstandard1.3 project and I have this in the `.csproj` file `<AssemblyVersion>3.0.0.0</AssemblyVersion>`. The version that is set on the generated assembly using `msbuild /t:pack` is `0.0.0.0`. If I put this `[assembly: AssemblyVersion( "3.0.0.0" )]` in the `AssemblyInfo.cs` file, it works fine.

Is this expected behavior or am I doing something wrong?

**Comment by weshaggard** [comment]
Issue moved to [dotnet/sdk #1099](https://github.com/dotnet/sdk/issues/1099) via [**ZenHub**](https://www.zenhub.com/)
