### ISSUE TITLE
Question: Best way to unit-test localisable error messages?

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#18065]
Error messages can be localisable, which means that tests that compare the message with a fixed string are locale-dependent.

So far whenever I've needed to examine a message I've either looked for a particular substring (which will serve my needs right now too, but it set me wondering about general principles), or verified that messages from exceptions thrown one way match those thrown another. Is there a better approach to take here that doesn't build assumptions about locale into the unit test?

**Comment by karelz** [comment]
@krwq @tarekgh @mellinoe @weshaggard any guidance? Does it belong rather into infra area?

**Comment by danmosemsft** [comment]
If the unit test runs in the same locale as the code under test, which presumably is usually the case as they're in the same process, the unit test can look up the string and compare -- verifying the exception is giving back SR.MissingFile not SR.MissingDirectory or whatnot. This is the approach I've used on a previous team successfully. I haven't seen CoreFX code use it and I don't think it's set up to without reflection to get to the SR class or duplicating it.

**Comment by danmosemsft** [comment]
If there are any such tests today, we should fix them. I see this issue: https://github.com/dotnet/corefx/issues/3850

**Comment by tarekgh** [comment]
@JonHanna you may just set CurrentUICulture to en-US and you'll always get the English/Neutral resources. I am wondering why you need to test the exception messages itself? I am asking because if you want to validate the message in the neutral resources doesn't mean the message will be correct in other localized languages. 

I think the best practice so far I have seen is to test the exception and the exception parameters. and if the exception message has parameters would be better to search for the value of such parameters but don't check the exception message itself.

**Comment by JonHanna** [comment]
@tarekgh generally it's come up either when the wrong one of a set of messages has been used, or when the message from one case should match that from another, so I'd be testing that the correct localisable message was used, rather than testing the details of the message itself.

**Comment by tarekgh** [comment]
> so I'd be testing that the correct localisable message was used, rather than testing the details of the message itself.

do you mean you want to test the message with specific localization language? or you you want to test all supported localized languages? or you want to test the neutral resources? 
Anyway, to control this you'll need to set CurrentUICulture which control the resource language which you get the exception messages with (if there is resources with that languages)

**Comment by tarekgh** [comment]
@JonHanna I am closing the issue here but feel free to respond with any follow up question or comment. Thanks.
