### ISSUE TITLE
Don't write ANSI escape sequences when output is not a tty?

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#1806]
When you redirect standard out to a file and then change the console color, the ANSI escape sequences are thrown into the file as well, which is not great.

Would it be possible to detect and not write the ASNI codes codes if we are redirected?

Steve, what do you think about this?

**Comment by stephentoub** [comment]
I assume by "redirect" you mean whether the Set* methods have been called to target a different TextWriter?  We could consider that, though I don't know that it would always be correct.  It'd be reasonable in some circumstances for a dev to call OpenOutputStream, wrap the result in their own writer, and then use SetOut to target that writer instead, in which case we'd be redirecting but still targeting the console (Roslyn actually does that exact thing, https://github.com/dotnet/roslyn/blob/109795e14c7e540f1494927d25085616a6c47b51/src/Compilers/Helpers/ConsoleUtil.cs#L37-L41)  In some cases we may still be able to handle that, such as with logic that tried to dig into a StreamWriter's BaseStream to see if it was one of our ConsoleStreams, but this wouldn't always work.

**Comment by ellismg** [comment]
I actually mean redirecting via the shell: `./corerun HelloWorld.exe > out.txt`  It would be great if that didn't cause us to litter escape sequences into things.

**Comment by stephentoub** [comment]
Ah. I think (though I haven't tried) that we can at least detect that (when SetOut hasn't been used) by checking the type of the underlying file descriptor to see if it's a named pipe. If so, we should also be able to detect in some limited additional SetOut cases like those I previously mentioned. It wouldn't be perfect, but maybe good enough?

**Comment by ellismg** [comment]
I think that would be great.

**Comment by stephentoub** [comment]
Submitted #1886 to fix this.
