### ISSUE TITLE
MembersMustExist: System.Diagnostics.Debug.Listeners

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#18069]
I am currently looking into differences between Core and Desktop and opening this issue as a child of https://github.com/dotnet/corefx/issues/15255#issuecomment-291137517

The following member is missing in corefx but is available in netfx:

`MembersMustExist : Member 'System.Diagnostics.Debug.Listeners.get()' does not exist in the implementation but it does exist in the contract.`

@joperezr: Would it make sense to port Listeners into corefx? It seems Xamarin is using it for Android: https://apisof.net/catalog/System.Diagnostics.Debug.Listeners. The types involved are TraceListenerCollection and TraceListener. Both are already in Core.

Related issue: https://github.com/dotnet/corefx/issues/6196

**Comment by joperezr** [comment]
cc: @jkotas 
I'm not too familiar with the code, but from an initial look it seems to be that it is not super trivial to implement this in corelib, at least not in the way we have it on desktop, where we use the Diagnostics configuration to initialize the listeners.

**Comment by joperezr** [comment]
I'll move this to future for now, and then if we decide that we want it for 2.0 we can always change the milestone.

**Comment by jkotas** [comment]
This was omitted intentionally https://github.com/dotnet/standard/issues/84

**Comment by ViktorHofer** [comment]
@jkotas Thanks!

I'll put it on the ignore of ApiCompatBaseline
