### ISSUE TITLE
MembersMustExist: System.Security.SecurityException

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#18078]
I am currently looking into differences between Core and Desktop and opening this issue as a child of https://github.com/dotnet/corefx/issues/15255#issuecomment-291137517

The following member is missing in corefx but is available in netfx:

```
MembersMustExist : Member 'System.Security.SecurityException.Zone.set(System.Security.SecurityZone)' does not exist in the implementation but it does exist in the contract.
```

@bartonjs @steveharter: It is possible / Does it make sense to port these members to Core? It lives in System.Runtime. https://apisof.net/catalog/System.Security.SecurityException.Zone

**Comment by weshaggard** [comment]
There isn't any real reason to in include this and I would suggest we not expose it.
