### ISSUE TITLE
MembersMustExist: System.Security.Cryptography.CspParameters

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#18079]
I am currently looking into differences between Core and Desktop and opening this issue as a child of https://github.com/dotnet/corefx/issues/15255#issuecomment-291137517

The following member is missing in corefx but is available in netfx:

```
MembersMustExist : Member 'System.Security.Cryptography.CspParameters.CryptoKeySecurity.set(System.Security.AccessControl.CryptoKeySecurity)' does not exist in the implementation but it does exist in the contract.
```

@bartonjs @steveharter: It is possible / Does it make sense to port these members to Core? It lives in System.Security.Cryptography.Csp. https://apisof.net/catalog/System.Security.Cryptography.CspParameters

**Comment by bartonjs** [comment]
This is about access control, and AFAIK we're still leaving those out.

**Comment by danmosemsft** [comment]
Yes, this cannot be added as it's a reference from inside to outside NS2.0.
