### ISSUE TITLE
MembersMustExist: System.ComponentModel.DataAnnotations

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#18075]
I am currently looking into differences between Core and Desktop and opening this issue as a child of https://github.com/dotnet/corefx/issues/15255#issuecomment-291137517

The following member is missing in corefx but is available in netfx:

`MembersMustExist : Member 'System.ComponentModel.DataAnnotations.ValidationContext.ServiceContainer.get()' does not exist in the implementation but it does exist in the contract.`

@lajones @divega @ajcvickers: It is possible / Does it make sense to port this member to Core? The usage is like a non-existent here: https://apisof.net/catalog/System.ComponentModel.DataAnnotations.ValidationContext.ServiceContainer but is **the only missing member** from netfx in System.ComponentModel.DataAnnotations.

**Comment by lajones** [comment]
@ViktorHofer I don't have permission to access that link but I looked it up. Basically that member provided access to a private class implementation of `ServiceContainer` which was a wrapper around the `ServiceContainer` contained within the `ServiceProvider` passed in at construction time (assuming you used the constructor that allowed you to pass that in). So basically you could get back a `ServiceContainer` that you had passed in and services from that container.

Only reason to do this would be to make it compatible with what NET Fx used to do.

Note: If we go ahead and do this we would also need to bring back in the private class definition and hook it up to all the places it used to be used and also port back in the code in `GetService()` which referenced this container.

We have triage for this tomorrow.

**Comment by ViktorHofer** [comment]
Yeah the reason why I brought this up is **compatibility**. We tried to reduce breaking changes between core and netfx in as many places as possible where it makes sense.

Thanks for keeping me updated.

**Comment by ViktorHofer** [comment]
@lajones Any update on that?

**Comment by lajones** [comment]
@divega @ajcvickers This is basically a compatibility issue. Any comment?

**Comment by ajcvickers** [comment]
Given the comments from @ViktorHofer and the analysis by @lajones I don't think we should do this unless there is a strong customer scenario for needing this member back.

**Comment by ViktorHofer** [comment]
That's fine for me! For our baseline analysis I will put that member into our ignore file and reference this issue as the reason for omitting it.
