### ISSUE TITLE
MembersMustExist: System.Security.Cryptography.ECDsaCng

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#18074]
I am currently looking into differences between Core and Desktop and opening this issue as a child of https://github.com/dotnet/corefx/issues/15255#issuecomment-291137517

The following member is missing in corefx but is available in netfx:

`MembersMustExist : Member 'System.Security.Cryptography.ECDsaCng.VerifyData(System.IO.Stream, System.Byte[])' does not exist in the implementation but it does exist in the contract.`

Related issue: https://github.com/dotnet/corefx/issues/17163. ECDsaCng are removed from netstandard but still live in netcore.

@bartonjs @steveharter: Is it possible / Does it make sense to port this member to Core? I can't see any usage of it in netfx: https://apisof.net/catalog/System.Security.Cryptography.ECDsaCng.VerifyData(Stream,Byte())

**Comment by bartonjs** [comment]
Yep, we should add the member.

**Comment by ViktorHofer** [comment]
Thanks! I will take it.

**Comment by ViktorHofer** [comment]
Duplicate of https://github.com/dotnet/corefx/issues/17163.
