### ISSUE TITLE
MembersMustExist: System.IO.IsolatedStorage

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#18071]
I am currently looking into differences between Core and Desktop and opening this issue as a child of https://github.com/dotnet/corefx/issues/15255#issuecomment-291137517

The following members are missing in corefx but are available in netfx:

```
MembersMustExist : Member 'System.IO.IsolatedStorage.IsolatedStorage.GetPermission(System.Security.PermissionSet)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.IO.IsolatedStorage.IsolatedStorageFile.GetPermission(System.Security.PermissionSet)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(System.IO.IsolatedStorage.IsolatedStorageScope, System.Security.Policy.Evidence, System.Type, System.Security.Policy.Evidence, System.Type)' does not exist in the implementation but it does exist in the contract.
```

Related issue which talks about the GetStore member: https://github.com/dotnet/corefx/issues/10935

@JeremyKuhne @ianhays: Is it possible / Does it make sense to port those members to Core? Jeremy already talked about that GetStore needs refactoring and would take a week. What about the others?

**Comment by JeremyKuhne** [comment]
They don't and won't do anything in Core as security has no implementation. Evidence is a dictionary of sorts that could in theory be implemented in Core, but this is one of the few places (or perhaps only place) where it might actually be useful.

Given how niche this is and the no-op nature of security I'd rather leave it out of NetStandard unless we see strong feedback. I suspect that anything we might get would be addressable with the other GetStore methods.

**Comment by ViktorHofer** [comment]
Thanks Jeremy for your input. Just to clarify, I was talking about porting it to netcore and not necessarily netstandard.

Sent from my Windows 10 phone

**Comment by JeremyKuhne** [comment]
>  I was talking about porting it to netcore and not necessarily netstandard

I understand- what I was inferring here is that these have little value in Core outside of potentially expanding netstandard, which I wouldn't want to do for these outside of strong feedback.

**Comment by ViktorHofer** [comment]
Alright, thanks Jeremy! I'll put it onto the ignore list for ApiCompatBaseline.
