### ISSUE TITLE
Downgrade warnings when referencing log4net in netcoreapp2.0

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#18088]
Copied from https://github.com/dotnet/corefx/issues/17278.

log4net referenced a mix of 1.0 and 1.1 packages.

When used in netcoreapp1.1 this didn't matter, since the netcore.app meta-package would lift all the packages up to 1.1.

In netcoreapp2.0 this no longer happens due to our smaller package graph.

The result is that the mix of 1.0 and 1.1 cause downgrade warnings when 1.1 package bring in the 1.1 lineup (Microsoft.NETCore.Targets).  This is because the lineup brings in 1.1 versions for **all** split packages, including those 1.0 references from log4net.  The 1.1 runtime packages reference 1.1 dependencies which ends up looking like a downgrade to nuget.

We could fix this by shipping a new version of Microsoft.NETCore.Targets in netcoreapp2.0 which has no lineup info in its runtime.json.  That would have the added benefit of reducing the download for mixed 1.x/2.0 projects, reducing the package graph, and thus our reliance on conflict resolution.  The downside is that it would grow the package graph slightly.

@weshaggard @terrajobst what do you think?

**Comment by weshaggard** [comment]
If we did ship a new version of Microsoft.NETCore.Targets who would bring that package into the graph?

**Comment by mtraudt** [comment]
Can I ask what is meant by "lineup info" in this context?

**Comment by ericstj** [comment]
@weshaggard: Microsoft.NETCore.App, same as we bring in Microsoft.NETCore.Platforms.

@mtraudt: have a look at the runtime.json inside Microsoft.NETCore.Targets.  You'll see that for each RID it associates a reference package like `System.IO.FileSystem` with a runtime specific implementation package `"runtime.win.System.IO.FileSystem": "4.3.0"`.  This is what we mean by "lineup", its a term that the NuGet folks were calling this behavior.  The runtime.json "lines up" a set of compatible implementation assemblies for the packages.  This thing is rather fragile, as you found out, which is one of the reasons why we're abandoning its use with granular packages in favor of larger flat packages in netcoreapp2.0.

**Comment by weshaggard** [comment]
I'm OK shipping one more package to clear out these. We could even do it one-off if you like.
