### ISSUE TITLE
Open-source GenFacades

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#1808]
At a bare minimum we need the following:

* Buildable executables for GenFacades and ApiCompat, including these dependencies:
  * Microsoft.Cci
  * Microsoft.Cci.Extensions
  * Microsoft.Fx.CommandLine
* Buildable NuGet package(s) containing the tools, to replace our internally-built one (Microsoft.DotNet.ApiTools).
  * As early as possible, we will switch to using this NuGet package.

I will also look into running these programs on CoreCLR, which should be fairly easy.

Open questions regarding these tools/libraries:
* Which repository should these tools live in? Buildtools? A new repository? Some of the library dependencies listed above are also used for various other tools we have, so we may want to put this stuff into its own repository. "CoreFxTools"?
* @ellismg had mentioned to me a while back that CCI, at the very least, depends on windows-specific libraries for generating PDB files. This will be a major hurdle going forward if we intend to run these tools on other platforms (which we do). At the minimum we can disable this functionality if it is unavailable.
* What is our plan for packaging/shipping console tools running on CoreCLR with regards to the runtime, host, and dependent libraries? Currently, GenFacades is built as a completely standalone desktop executable (with ILMerge'd dependencies). We will need a different scheme for a CoreCLR-based tool.

**Comment by ellismg** [comment]
> @ellismg had mentioned to me a while back that CCI, at the very least, depends on windows-specific libraries for generating PDB files. This will be a major hurdle going forward if we intend to run these tools on other platforms (which we do). At the minimum we can disable this functionality if it is unavailable.

Roslyn has the same problem.  They are developing a portable PDB format, but I think today they just don't generate PDBs when running cross platform.  We should just do the same thing.  I think it's reasonable for v1.0 to say if you want to get PDBs, you have to build on Windows.  Once their format is done, we need to understand how we consume it.  Do we add support for it to CCI?  Decide that we want to do the larger work item of building these tools on top of the metadata APIs (which probably means we have to build a metadata writer)?  Try to leverage Roslyn (which would have already solved this problem) in some interesting way?

> What is our plan for packaging/shipping console tools running on CoreCLR with regards to the runtime, host, and dependent libraries? Currently, GenFacades is built as a completely standalone desktop executable (with ILMerge'd dependencies). We will need a different scheme for a CoreCLR-based tool.

We should just figure out how we plan to consume Roslyn (which has the same problem) and follow their lead.  I assume it's a NuGet package and we combine it with the .NET Core runtime nuget package, but @jaredpar would probably know for sure.

**Comment by jaredpar** [comment]
@ellismg is correct that today we simply just don't generate PDB when compiling on non-Windows platform.  Portable-PDB is our current plan for cross platform PDB generation. 

Our rough plan at the moment for CoreCLR is that Roslyn will change the Microsoft.Net.Compilers NuGet to package both Roslyn and a CoreCLR implementation.  That would make it a truly standalone NuGet.

**Comment by mellinoe** [comment]
To give a small update on this as I have switched temporarily to other work:

I have a version of GenFacades running on CoreCLR, and have tested it on Windows. I have verified that it runs on Linux, but haven't tried using it to fill any partial facades there (spent a lot of time just setting up my machine and getting my environment set up). By that, I mean that I can get it to print out the "usage" message on Linux :). Barring any unexpected or external bugs, I expect that it will work fine as-is on Linux as the rest of the dependencies should be fully portable.
* PDB writing doesn't work at all in the CoreCLR version, even on Windows. The PDB reading/writing code relies on COM Activation, which isn't supported on CoreCLR. I could potentially work around this if I was more familiar with this part of the code, but it didn't seem worth it. We can continue using the full .NET Framework executable on Windows so PDB support isn't lost.
* We had some discussion about re-working GenFacades to use Roslyn for code-generation of the type-forwards. This would let us rely on Roslyn to eventually provide cross-plat PDB support. This probably wouldn't be too much work, but we'd have to support all of the different options and settings of GenFacades. Once we have a version with cross-plat PDB implementation, we can stop using the .NET Framework version on Windows.
* Packaging the GenFacades executable and runtime will still need some planning. Additionally, we aren't packaging any of our cross-plat assemblies just yet, nor is there a Linux CoreCLR package or host. These will probably all materialize in time I imagine. When I tested on Linux I hacked up a Runtime folder myself by building various things on Windows and Linux.

**Comment by saper** [comment]
Quick questions: 

1) Is `model.xml` something that will evolve are are we pretty flexible about its format?

2) Also, are `mscorlib.apiClosure.xml` and `mscorlib.implClosure.xml` required by your tooling or is it something we can support later (if at all)?

**Comment by mellinoe** [comment]
I have a working build of GenFacades and its dependencies at this repository here:

https://github.com/mellinoe/ApiTools

I'm building:
* GenFacades.exe
* Microsoft.Cci.Extensions
* Microsoft.Fx.CommandLine

Our plan is to use Cci built from an internal share still, shipped through some NuGet package. For now I've included it in the repository as a binary. It is also in our plans to phase out the dependency on CCI in the future.

Executables are built for CoreCLR and for the Desktop framework, and a full NuGet package is built for both. The CoreCLR package includes the full runtime and a host, making it a standalone tool. Right now, our NuGet packages are Windows-only, but we should soon be adding cross-plat support to those. At that point, the build can be slightly modified to support additional platform builds. I've manually tested on Ubuntu and verified that the executable works there, so when everything else comes together (packaging, etc) we should be able to integrate it into the build process there and consume it right away.

**Comment by mellinoe** [comment]
@saper Those files are related to the BclRewriter tool, which I'm not looking at currently, but which may come into this at some point. As for model.xml, I don't think we are really evolving it at this point. It's served a pretty specific purpose in the BclRewriter afaik.

**Comment by weshaggard** [comment]
@mellinoe is there any way to see that changes were needed to getting these working on CoreCLR? Ideally if your initial port into ApiTools repo was unmodified then we could see the differences from the changes you made.

I'm fine with these going into a BuildTools or a new ApiTools/CoreFxTools repo but we should chat with @terrajobst to see if he has other plans for the CoreFxTools yet.

**Comment by mellinoe** [comment]
I will recommit these with the original source files undernearth. For the most part there were very few changes, even in CCI extensions. There were a few buckets of changes:

* Reflection changes, mostly just adding "GetTypeInfo()" and everything here compiled
* System.Composition: I replaced the desktop MEF with the portable one. I'm not very familiar with this but there were only a small number of files affected here. Also it was mostly namespace changes.
* Command line stuff: There's a few things that aren't exposed in the contracts, like Environment.CommandLine, Environment.ExitCode, etc. so I reworked a bit of the CommandLine tool because of that.

I believe I put everything into #if COREFX blocks, as well, because I'm still compiling the desktop versions here.

**Comment by mellinoe** [comment]
I re-committed things on my repository so that the diff can be seen.

**Comment by mellinoe** [comment]
Splitting this up into a couple separate work items.

**Comment by mellinoe** [comment]
Fixed by this commit in buildtools:

https://github.com/dotnet/buildtools/commit/db31fd2a6f60cc022bc78f40f9ef8bba6be4d6c9

**Comment by mellinoe** [comment]
Split off two work items:

https://github.com/dotnet/buildtools/issues/228
  * Create Cross-Plat Versions of GenFacades, blocked by cross-plat NuGet packages

https://github.com/dotnet/buildtools/issues/229
  * Open-Source ApiCompat when it becomes necessary for our build.
