### ISSUE TITLE
Investigate dependency of Xslt on System.Xml.Xsl.Runtime at runtime

### ISSUE THREAD

**Issue by sepidehkh** [dotnet/corefx#18103]
Refer to the discussion in https://github.com/dotnet/corefx/pull/18042

Xslt is loading public types from System.Xml.Xsl.Runtime and making calls to them at runtime to generate IL code. Investigate why this dependency exists and why we cannot remove them/move them to a separate library?

**Comment by krwq** [comment]
Closing this as won't fix - while reducing the size of System.Xml might be a potential gain we will have to ship potential new runtime binary either way. I do not think this is worth the effort just for the sake of splitting.
