### ISSUE TITLE
UnmanagedMemoryStream methods missing from package?

### ISSUE THREAD

**Issue by jack-pappas** [dotnet/corefx#18118]
I re-wrote a small piece of code within the F# compiler dealing with memory-mapped files to use ``MemoryMappedFile`` instead of the win32 API to allow that functionality to work on all platforms.

Microsoft/visualfsharp#2528

The PR fails to build for CoreCLR, because the ``Read<T>`` and ``ReadArray<T>`` methods are missing on ``System.IO.UnmanagedMemoryStream`` (from which ``MemoryMappedFileAccessor`` is derived).

Am I doing something wrong in the code or the package references? I've looked around in this repository and dotnet/coreclr and haven't found anything to indicate why those methods would be missing from the ``UnmanagedMemoryStream`` class (from the ``System.IO.UnmanagedMemoryStream`` package).

**Comment by karelz** [comment]
Where are `Read<T>` and `ReadArray<T>` defined? I can't find them neither in [old MSDN docs](https://msdn.microsoft.com/en-us/library/system.io.unmanagedmemorystream(v=vs.110).aspx) nor in new [API reference docs](https://docs.microsoft.com/en-us/dotnet/api/system.io.unmanagedmemorystream.read?view=netframework-4.7).

**Comment by jkotas** [comment]
@jack-pappas meant to say UnmanagedMemoryAccessor. `Read<T>` and `ReadArray<T>` were added back to this type for NetStandard 2.0.

**Comment by karelz** [comment]
Yep, those are back in .NET Core 2.0:
* [`Read<T>`](https://apisof.net/catalog/System.IO.UnmanagedMemoryAccessor.Read%3CT%3E(Int64,T))
* [`ReadArray<T>`](https://apisof.net/catalog/System.IO.UnmanagedMemoryAccessor.ReadArray%3CT%3E(Int64,T(),Int32,Int32))

Closing

**Comment by jack-pappas** [comment]
@jkotas Yes, I meant ``UnmanangedMemoryAccessor``, thank you for the correction.

@karelz Ok, thank you. I'll see if we can target ``netstandard2.0`` for the F# compiler then in order to use these APIs.
