### ISSUE TITLE
Fix managed implementation of HttpListener to match Windows implementation

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#18128]
In #17999 some tests are disabled on Unix due to different implementations of HttpListener. Most of these are argument validation, and can easily be corrected. Some may need further investigation and may be by-design due to inherent platform differences.

I'm grabbing this one, once #17999 is merged

**Comment by danmosemsft** [comment]
@tijoytom fyi.

**Comment by karelz** [comment]
@hughbe any progress on this one?

**Comment by hughbe** [comment]
Yup I've submitted a bunch of PRs. This is a bit of an umbrella issue unfortunately - the more tests I add the more differences I find - so not sure how well it fits into milestones etc.

**Comment by karelz** [comment]
Got it.
When do you expect to reach the point of "good enough" coverage? Do you have rough estimation?

**Comment by hughbe** [comment]
I've gone through request stream, response streams request and listener.
I'm probably going to limit myself to response and authentication to conclude.
Maybe a good idea for me would be to close this issue once all the active issues are fixed - I dislike umbrella issues as much as anyone

**Comment by karelz** [comment]
Sounds great, thanks!

**Comment by Priya91** [comment]
@hughbe What other issues if this one tracking?

**Comment by hughbe** [comment]
The main remaining issue this tracks are (assuming #19138 and #19219 are merged):

- [ ] [GetClientCertificateAsync_NoCertificate_ReturnsNull](https://github.com/dotnet/corefx/blob/4aa6fb7a6e79edf9294079131ddf4b633c12d71e/src/System.Net.HttpListener/tests/HttpListenerRequestTests.cs#L259-L267): this test hangs forever on Unix. It's odd, as a call to `BeginGetClientCertificate` followed by `EndGetClientCertificate` works absolutely fine.
- [ ] [Add_InvalidPrefix_ThrowsHttpListenerException_Windows](https://github.com/dotnet/corefx/blob/c4ddfc3b9be6b6afa4b4168582507c1aca2b2a2e/src/System.Net.HttpListener/tests/HttpListenerPrefixCollectionTests.cs#L282-L289): this is an argument validation thing: we can add `http://192./` as a prefix.
- [ ] [EndGetContext_InvalidAsyncResult_ThrowsArgumentException](https://github.com/dotnet/corefx/blob/ffa1f8f2c80a602a85ca41978b64ffbf40d53c76/src/System.Net.HttpListener/tests/HttpListenerTests.cs#L125-L139): no argument validation is performed on `asyncResult`. Needs a bit of refactoring to fix, but is a good chance to consolidate windows/managed.
- [ ] [Write_TooMuch_ThrowsProtocolViolationException](https://github.com/dotnet/corefx/blob/e9e5c861c71300b34ac910365c4cf1ba506eb470/src/System.Net.HttpListener/tests/HttpResponseStreamTests.cs#L299-L326): no exception is thrown in managed. This looks tricky without deeper investigation, as it seems the Windows implementation tracks the content length specified in the response. Again, could be an opportunity to consolidate code here.
- [ ] [Write_TooLittleAsynchronouslyAndClose_ThrowsInvalidOperationException/Write_TooLittleSynchronouslyAndClose_ThrowsInvalidOperationException/](https://github.com/dotnet/corefx/blob/e9e5c861c71300b34ac910365c4cf1ba506eb470/src/System.Net.HttpListener/tests/HttpResponseStreamTests.cs#L328-L380): no exception in managed. This is similar to the one above. On Windows, we throw an exception trying to dispose the response stream if the response stream is incomplete.
- [ ] [EndWrite_InvalidAsyncResult_ThrowsArgumentException/EndWrite_CalledTwice_ThrowsInvalidOperationException](https://github.com/dotnet/corefx/blob/e9e5c861c71300b34ac910365c4cf1ba506eb470/src/System.Net.HttpListener/tests/HttpResponseStreamTests.cs#L539-L567): managed implementation performs insufficient argument validation on the `asyncResult`. This is a chance to consolidate the two implementations more.
- [ ] [EndRead_InvalidAsyncResult_ThrowsArgumentException/EndRead_CalledTwice_ThrowsInvalidOperationException](https://github.com/dotnet/corefx/blob/43ae928a933c5268ed012d84256508f609cb0a12/src/System.Net.HttpListener/tests/HttpRequestStreamTests.cs#L416-L449): same as above
- [ ] [Read_FromClosedConnectionAsynchronously_ThrowsHttpListenerException/Read_FromClosedConnectionSynchronously_ThrowsHttpListenerException](https://github.com/dotnet/corefx/blob/43ae928a933c5268ed012d84256508f609cb0a12/src/System.Net.HttpListener/tests/HttpRequestStreamTests.cs#L451-L511): no exception thrown. I don't know why.

**Comment by hughbe** [comment]
This is almost certainly too much work for ZBB

**Comment by karelz** [comment]
Networking has already exception from ZBB.
@Priya91 can you please help prioritize the failures above? Which are likely impactful enough for us to take them?

**Comment by karelz** [comment]
@Priya91 ping?

**Comment by Priya91** [comment]
@karelz Looking at the tests, will update when I have more info. I would prioritize the issues with different platform behaviors, that is cases where exceptions are not thrown/thrown.

**Comment by karelz** [comment]
I don't think we need the umbrela issue anymore, let's consider it addressed.

**Comment by stephentoub** [comment]
@karelz, there are 14 tests disabled against this issue, and PR https://github.com/dotnet/corefx/pull/19880 disables another 36 tests against it.

**Comment by karelz** [comment]
Ooops, thanks for catching that. I have moved the issue to Future. I assume we already made our peace with the disabled tests, right?
Or is there any 2.0 work left here?

**Comment by stephentoub** [comment]
> I assume we already made our peace with the disabled tests, right?

I wouldn't assume that.  Most of these differences we're only just learning about as @hughbe writes the tests we never had before.  To quote you from 5 days ago:
https://github.com/dotnet/corefx/issues/19744#issuecomment-301279350

**Comment by karelz** [comment]
Are you saying we didn't have time to look at the failures yet? That would be concerning ...

**Comment by stephentoub** [comment]
They're marked against this issue, and you assigned this issue to hughbe.  He's writing a ton of good tests and finding issues.  To my knowledge no one has further investigated those issues, but you would know better than I.

**Comment by karelz** [comment]
I think I mixed it up with "we need tests" - @Priya91 can you please review the test failures and help prioritize them?

**Comment by Priya91** [comment]
@karelz @stephentoub I've requested @hughbe to try to file separate issues for distinct known compat bugs, so that it's easier to surmarize what the issue is instead of reading the whole umbrella issue thread to figure out how much work is left. As to prioritizing the test failures, I'm not sure how to do that, all of them are differences in behavior between windows and unix, we need to fix all at equal priority for 2.0, since HttpListener was added for 2.0.

**Comment by hughbe** [comment]
Closing this issue as I've separated all the issues out into their own tests in #19880 
I'd like to grab some of the low hanging fruit this weekend, especially around HttpListenerResponse
