### ISSUE TITLE
Desktop: System.Security.Cryptography.Encryption.Tests.Asymmetric.CryptographicExceptionTests.Ctor failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18139]
Failed test: System.Security.Cryptography.Encryption.Tests.Asymmetric.CryptographicExceptionTests.Ctor

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/13/testReport/System.Security.Cryptography.Encryption.Tests.Asymmetric/CryptographicExceptionTests/Ctor/

~~~
MESSAGE:
Assert.Equal() Failure\r\nExpected: 5\r\nActual: -2147024891
+++++++++++++++++++
STACK TRACE:
at System.Security.Cryptography.Encryption.Tests.Asymmetric.CryptographicExceptionTests.Ctor() in D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Cryptography.Primitives\tests\CryptographicException.cs:line 20
~~~

**Comment by sepidehMS** [comment]
@AlexGhiondea Do you remember what was behind the change from the [Desktop implementation](http://referencesource.microsoft.com/#mscorlib/system/security/cryptography/crypto.cs,108) and the [core implementation](https://source.dot.net/#System.Private.CoreLib/shared/System/Security/CryptographicException.cs,18) of `CryptographicException(int)`?

**Comment by krwq** [comment]
Fixed with https://github.com/dotnet/corefx/pull/18575

**Comment by AlexGhiondea** [comment]
@sepidehMS I don't know, but @bartonjs probably does :).

**Comment by bartonjs** [comment]
@sepidehMS  Apparently CryptographicException is in System.Private.CoreLib now.  Who knew?  Presumably Alex, but definitely not me.

The netfx CryptographicException does stuff assuming that it's Win32.  Those behaviors don't make sense for Linux or macOS; so they're gone in corefx.
