### ISSUE TITLE
Desktop: Tests under "System.ComponentModel.DataAnnotations.Tests" failed with "Xunit.Sdk.ThrowsException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18148]
Failed tests:
System.ComponentModel.DataAnnotations.Tests.CustomValidationAttributeTests.RequiresValidationContext_BadlyFormed_ThrowsInvalidOperationException
System.ComponentModel.DataAnnotations.Tests.DataTypeAttributeTests.Ctor_String

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/13/testReport/System.ComponentModel.DataAnnotations.Tests/CustomValidationAttributeTests/RequiresValidationContext_BadlyFormed_ThrowsInvalidOperationException_validatorType__null__method____Does_not_matter___/

~~~
MESSAGE:
Assert.Throws() Failure\r\nExpected: typeof(System.InvalidOperationException)\r\nActual: (No exception was thrown)
+++++++++++++++++++
STACK TRACE:
at System.ComponentModel.DataAnnotations.Tests.CustomValidationAttributeTests.RequiresValidationContext_BadlyFormed_ThrowsInvalidOperationException(Type validatorType, String method) in D:\j\workspace\outerloop_net---903ddde6\src\System.ComponentModel.Annotations\tests\CustomValidationAttributeTests.cs:line 103
~~~

**Comment by Jiayili1** [comment]
This issue is repro on build 20170411.01, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170411.01/workItem/System.ComponentModel.Annotations.Tests/analysis/xunit/System.ComponentModel.DataAnnotations.Tests.CustomValidationAttributeTests~2FRequiresValidationContext_BadlyFormed_ThrowsInvalidOperationException(validatorType:%20null,%20method:%20%5C%22Does%20not%20matter%5C%22)

**Comment by safern** [comment]
This is taken care of PR: #17874
