### ISSUE TITLE
Desktop: Test "System.Linq.Parallel.Tests.OrderByThenByTests.ThenByDescending_NotPipelined_ExtremeComparer" failed with "Xunit.Sdk.AllException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18141]
Failed test: System.Linq.Parallel.Tests.OrderByThenByTests.ThenByDescending_NotPipelined_ExtremeComparer
 Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/13/testReport/System.Linq.Parallel.Tests/OrderByThenByTests/ThenByDescending_NotPipelined_ExtremeComparer_labeled__Partitioner_Random__count__2_/

Message:
~~~
Assert.All() Failure: 1 out of 2 items in the collection did not pass.\r\n[1]: Xunit.Sdk.InRangeException: Assert.InRange() Failure\r\n Range: (0 - 0)\r\n Actual: 1\r\n at Xunit.Assert.InRange[T](T actual, T low, T high, IComparer`1 comparer) in C:\\BuildAgent\\work\\cb37e9acf085d108\\src\\xunit.assert\\Asserts\\RangeAsserts.cs:line 36\r\n at System.Linq.Parallel.Tests.OrderByThenByTests.<>c__DisplayClass71_0.<ThenByDescending_NotPipelined_ExtremeComparer>b__2(Int32 x) in D:\\j\\workspace\\outerloop_net---903ddde6\\src\\System.Linq.Parallel\\tests\\QueryOperators\\OrderByThenByTests.cs:line 992\r\n at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\\BuildAgent\\work\\cb37e9acf085d108\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 31
~~~

Stack Trace:
~~~
at System.Linq.Parallel.Tests.OrderByThenByTests.ThenByDescending_NotPipelined_ExtremeComparer(Labeled`1 labeled, Int32 count) in D:\j\workspace\outerloop_net---903ddde6\src\System.Linq.Parallel\tests\QueryOperators\OrderByThenByTests.cs:line 992
~~~

**Comment by danmosemsft** [comment]
@alexperovich can you have a quick take on whether this is a concern for 2.0?

**Comment by alexperovich** [comment]
The fix for this is actually to port #2305 to netfx. That said I don't think this concerning for 2.0 because there is a simple workaround: don't return extreme values from your comparer implementation.

**Comment by alexperovich** [comment]
Test `System.Linq.Parallel.Test.OrderByThenByTests.OrderByDescending_ExtremeComparer` fails with same issue

**Comment by safern** [comment]
@alexperovich maybe disable them and pointing to this issue to have a clean run?

**Comment by alexperovich** [comment]
I will disable the tests

**Comment by safern** [comment]
Thanks

**Comment by stephentoub** [comment]
The test is annotated to be skipped on netfx.  Closing.
