### ISSUE TITLE
Desktop: System.ComponentModel.DataAnnotations.Tests.RangeAttributeTests.Validate_IConvertibleThrowsCustomException_IsNotCaught failed with "Xunit.Sdk.ThrowsException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18146]
Failed test: System.ComponentModel.DataAnnotations.Tests.RangeAttributeTests.Validate_IConvertibleThrowsCustomException_IsNotCaught

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/13/testReport/System.ComponentModel.DataAnnotations.Tests/RangeAttributeTests/Validate_IConvertibleThrowsCustomException_IsNotCaught/

~~~
MESSAGE:
Assert.Throws() Failure\r\nExpected: typeof(System.ArithmeticException)\r\nActual: typeof(System.ComponentModel.DataAnnotations.ValidationException): The field Object must be between 1 and 1.
+++++++++++++++++++
STACK TRACE:
at System.ComponentModel.DataAnnotations.ValidationAttribute.Validate(Object value, ValidationContext validationContext) at System.ComponentModel.DataAnnotations.Tests.RangeAttributeTests.<>c__DisplayClass11_0.<Validate_IConvertibleThrowsCustomException_IsNotCaught>b__0() in D:\j\workspace\outerloop_net---903ddde6\src\System.ComponentModel.Annotations\tests\RangeAttributeTests.cs:line 191
~~~

**Comment by Jiayili1** [comment]
This issue is repro on build 20170411.01, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170411.01/workItem/System.ComponentModel.Annotations.Tests/analysis/xunit/System.ComponentModel.DataAnnotations.Tests.RangeAttributeTests~2FValidate_IConvertibleThrowsCustomException_IsNotCaught

**Comment by safern** [comment]
This is taken care of PR: #17874
