### ISSUE TITLE
Desktop: System.Security.Cryptography.Encryption.Aes.Tests.AesContractTests.InvalidKeySizes failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18143]
Failed test: System.Security.Cryptography.Encryption.Aes.Tests.AesContractTests.InvalidKeySizes

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/13/testReport/System.Security.Cryptography.Encryption.Aes.Tests/AesContractTests/InvalidKeySizes_invalidKeySize__536870928_/

Message:
~~~
Got \r\nExpected: True\r\nActual: False
~~~

Stack Trace:
~~~
at System.Security.Cryptography.Encryption.Aes.Tests.AesContractTests.InvalidKeySizes(Int32 invalidKeySize) in D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\Security\Cryptography\AlgorithmImplementations\AES\AesContractTests.cs:line 86
~~~

**Comment by krwq** [comment]
@bartonjs here is a tiny repro:
```csharp
            using (Aes aes = AesFactory.Create())
            {
                var key = new byte[536870928];
                Assert.Throws<ArgumentException>(() => aes.CreateEncryptor(key, aes.IV));
            }
```

Could you take a look and tell if this sound familiar before I get deeper into this?

**Comment by krwq** [comment]
Even tinier repro:
```csharp
                var key = new byte[536870928];
                Console.WriteLine(aes.ValidKeySize(key.Length * 8));
```

Not sure why is this overflow not detected on desktop - should we wrap this with `checked`?

**Comment by bartonjs** [comment]
The OOM is likely a result of the host model.  If xunit runs as an x86 process it probably can't make the array :smile:.

The netfx side is already under  #18690 (SymmetricAlgorithm.set_Key permits large keys by mistake), so this can be suppressed to that issue.
