### ISSUE TITLE
Desktop: System.ComponentModel.DataAnnotations.Tests.CustomValidationAttributeTests.RequiresValidationContext_Get_ReturnsExpected failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18149]
Failed test: System.ComponentModel.DataAnnotations.Tests.CustomValidationAttributeTests.RequiresValidationContext_Get_ReturnsExpected

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/13/testReport/System.ComponentModel.DataAnnotations.Tests/CustomValidationAttributeTests/RequiresValidationContext_Get_ReturnsExpected_method____CorrectValidationMethodTwoArgs____expected__True_/

~~~
MESSAGE:
Assert.Equal() Failure\r\nExpected: True\r\nActual: False
+++++++++++++++++++
STACK TRACE:
at System.ComponentModel.DataAnnotations.Tests.CustomValidationAttributeTests.RequiresValidationContext_Get_ReturnsExpected(String method, Boolean expected) in D:\j\workspace\outerloop_net---903ddde6\src\System.ComponentModel.Annotations\tests\CustomValidationAttributeTests.cs:line 80
~~~

**Comment by Jiayili1** [comment]
This issue is repro on build 20170411.01, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170411.01/workItem/System.ComponentModel.Annotations.Tests/analysis/xunit/System.ComponentModel.DataAnnotations.Tests.CustomValidationAttributeTests~2FRequiresValidationContext_Get_ReturnsExpected(method:%20%5C%22CorrectValidationMethodTwoArgsStronglyTyped%5C%22,%20expected:%20True)

**Comment by safern** [comment]
This is taken care of PR: #17874
