### ISSUE TITLE
Desktop: System.Net.Tests.FtpWebRequestTest.Ctor_VerifyDefaults_Success failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18151]
Failed test: System.Net.Tests.FtpWebRequestTest.Ctor_VerifyDefaults_Success

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/13/testReport/System.Net.Tests/FtpWebRequestTest/Ctor_VerifyDefaults_Success/

~~~
MESSAGE:
Assert.False() Failure\r\nExpected: False\r\nActual: True
+++++++++++++++++++
STACK TRACE:
at System.Net.Tests.FtpWebRequestTest.Ctor_VerifyDefaults_Success() in D:\j\workspace\outerloop_net---903ddde6\src\System.Net.Requests\tests\FtpWebRequestTest.cs:line 43
~~~

**Comment by davidsh** [comment]
There are many more failures than this in innerloop tests for System.Net.Requests library against NETFX (Desktop). Looking at some of them reveal that the defaults are wrong compared with Desktop.

**Comment by davidsh** [comment]
Related to #17842
