### ISSUE TITLE
Individual library packages need netstandard2.0 configuration

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#18160]
All our packages need to be sure to have netstandard2.0 support.

1. If they are part of netstandard2.0 then they need to have a placeholder so their owner assets doen't get chosen.
2. If they are above netstandard and they have an older netstandard configuration then they need a netstandard2.0 configuration to ensure package graph is cleaned up. 

@ericstj I filed this issue once I realized packages like our System.Net.Http will not work if they are referenced from a netstandard 2.0 project.

**Comment by davidfowl** [comment]
> If they are above netstandard and they have an older netstandard configuration then they need a netstandard2.0 configuration to ensure package graph is cleaned up.

Is that really worth it? We're not doing this in ASP.NET and I'd assume people aren't doing this for their 3rd party packages as it forces you to cross compile when you otherwise wouldn't need to.

**Comment by weshaggard** [comment]
While we support not doing so I think for the packages we build in corefx we should do it to help take some load off the file/package conflict resolution task.

**Comment by davidfowl** [comment]
@weshaggard I don't think it's worth it.

**Comment by ericstj** [comment]
> packages like our System.Net.Http will not work if they are referenced from a netstandard 2.0 project.

@weshaggard can you clarify if you're talking about using old packages with ns2.0?  If that's the case then the problem is likely the versioning in standard repo.  If you're talking about new packages in new projects then I agree we need to make sure that works correctly.

Please provide some concrete examples of the issues you're talking about here (both 1 & 2).

**Comment by weshaggard** [comment]
>@weshaggard can you clarify if you're talking about using old packages with ns2.0? If that's the case then the problem is likely the versioning in standard repo. If you're talking about new packages in new projects then I agree we need to make sure that works correctly.

I'm talking about our new packages. I don't want to be in a race condition between file versions between corefx and standard repo's to determine which one wins the conflict resolution. We should be explicit for these packages where we ship a package and a shim. So for (1) the list should be driven by the intersection of  the netstandard shim list and the individual library packages we ship.

For (2) it is more of a nice to have I don't think there will be anything bad here if we don't do anything but currently it looks like most of these already have a netstandard2.0 configuration so it is more about just doing an audit to ensure they are all consistent.

**Comment by ericstj** [comment]
I'm rolling this into #17914
