### ISSUE TITLE
The executable generated from `dotnet publish -r ubuntu.16.04-x64` doesn't have "x" permission

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/corefx#18168]
`dotnet publish -r ubuntu.16.04-x64` generates an executable, however, the executable file doesn't have "x" permission.
This happens when building a stand-alone application targeting `netcoreapp2.0` with `dotnet-cli 2.0.0-preview1-005724`. It is a regression comparing to `dotnet sdk 1.1`.

Simple repro:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeIdentifier>ubuntu.16.04-x64</RuntimeIdentifier>
  </PropertyGroup>

</Project>
```
```
# dotnet restore
# dotnet publish -r ubuntu.16.04-x64
[/temp/console]
bash:96> bin/Debug/netcoreapp2.0/ubuntu.16.04-x64/publish/console
bash: bin/Debug/netcoreapp2.0/ubuntu.16.04-x64/publish/console: Permission denied
[/temp/console]
bash:97> dir bin/Debug/netcoreapp2.0/ubuntu.16.04-x64/publish/console
-rw-rw-r-- 1 dongbo dongbo 66412 Apr 10 14:12 bin/Debug/netcoreapp2.0/ubuntu.16.04-x64/publish/console
```

**Comment by mellinoe** [comment]
This sounds more like a CLI or SDK bug, given that it has to do with the "publish" command. Could you file an issue over here? https://github.com/dotnet/cli/issues

**Comment by daxian-dbw** [comment]
@mellinoe sure, I will open an issue in the dotnet-cli repo. Thanks!

**Comment by mellinoe** [comment]
@daxian-dbw Thanks!
