### ISSUE TITLE
System.Json assembly identity

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#18172]
We added System.Json with https://github.com/dotnet/corefx/pull/9897 and later updated the version number to match mono with https://github.com/dotnet/corefx/issues/9938. However we still haven't taken into account the public key. Currently it has the MSFT public key (soon to be the Open key https://github.com/dotnet/corefx/pull/18165) and so any existing binary references will still not bind to this assembly. 

We need to decide if we want this binary to exactly match the one we shipped with SL and if so we should give it the same complete assembly identity or we should rename it to a new assembly name and have it fall inline with any other new assembly in corefx.

I think I would make it match the exact assembly identity.

cc @stephentoub @terrajobst opinions? 

@karelz @danmosemsft do you know who owns this library?

**Comment by karelz** [comment]
No one owns it - it's not on our [area list](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#areas) and I haven't seen it in the internal OneNote predecessors of the list either.

We will need to ask someone to help with the task once we decide what to do.

**Comment by tarekgh** [comment]
@karelz @danmosemsft please assign owner for this one to take a look soon as this is marked as v2. thanks.

**Comment by stephentoub** [comment]
> I think I would make it match the exact assembly identity.

I agree.  The primary (whole?) point of adding this library was purely about improving compatibility with apps using Mono, so we should do everything we can to match the same identity used there.

**Comment by tarekgh** [comment]
I am going to do it. as suggested we'll keep the original Silverlight identity.
