### ISSUE TITLE
Checked Exceptions

### ISSUE THREAD

**Issue by pedroaliens** [dotnet/corefx#18190]
What about Checked Exceptions in C# like Java?

I think it would be helpful to expect all behaviors of the method/object.

```csharp
public class FileUtils
{
    public void Write(string content)
        throws : DirectoryNotFoundException
    {
        ...
    }

    public void WriteGeneric<T>(string content)
        throws : DirectoryNotFoundException
        where T: class
    {
        ...
    }
}
```
It will enforce that every method who calls FileUtils.Write should do it within a try..catch.. statement.

**Comment by danmosemsft** [comment]
Hi @pedroaliens could you please open an issue in https://github.com/dotnet/csharplang

As you can imagine this suggestion has history. Here's some explanation: http://www.artima.com/intv/handcuffs.html
