### ISSUE TITLE
Desktop: System.Security.Cryptography.EcDsa.Tests.ECDsaTests.PublicKey_CannotSign failed with "System.TypeLoadException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18198]
Failed test: System.Security.Cryptography.EcDsa.Tests.ECDsaTests.PublicKey_CannotSign

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/14/testReport/System.Security.Cryptography.EcDsa.Tests/ECDsaTests/PublicKey_CannotSign/

MESSAGE:
System.TypeLoadException : Could not load type 'System.Security.Cryptography.ECParameters' from assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
+++++++++++++++++++

STACK TRACE:
at System.Security.Cryptography.EcDsa.Tests.ECDsaTests.PublicKey_CannotSign()

**Comment by danmosemsft** [comment]
@safern looks like infra not the test in question?

**Comment by safern** [comment]
ECParameters is not available for desktop until 4.7 so the code that uses it should be #if-ed out. I can take care of this one tomorrow and should be quick.

**Comment by gulbanana** [comment]
:( I just had to convert a library to multi-targeting net461/netstandard2.0 instead of just netstandard2.0 because of the missing ECParameters. I'm glad this issue exists, as it's the only search result online for the error message you get.
