### ISSUE TITLE
Desktop: System.Net.Tests.HttpWebRequestTest.Abort_BeginGetResponseThenAbort_EndGetResponseThrowsWebException failed with "System.NullReferenceException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18203]
Failed test: System.Net.Tests.HttpWebRequestTest.Abort_BeginGetResponseThenAbort_EndGetResponseThrowsWebException

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/14/testReport/System.Net.Tests/HttpWebRequestTest/Abort_BeginGetResponseThenAbort_EndGetResponseThrowsWebException_remoteServer__http___corefx_net_cloudapp_net_Echo_ashx_/

MESSAGE:
System.NullReferenceException : Object reference not set to an instance of an object.
+++++++++++++++++++

STACK TRACE:
at System.Net.Tests.HttpWebRequestTest.Abort_BeginGetResponseThenAbort_EndGetResponseThrowsWebException(Uri remoteServer) in D:\j\workspace\outerloop_net---903ddde6\src\System.Net.Requests\tests\HttpWebRequestTest.cs:line 561

**Comment by davidsh** [comment]
Fixed as part of #18163
