### ISSUE TITLE
Test failures: System.Globalization.Tests.NumberFormatInfoPercentPositivePattern

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#18208]
Just ran build-tests from root and discovered that these two tests are failing in System.Globalization on Core:

```
<test name="System.Globalization.Tests.NumberFormatInfoPercentPositivePattern.PercentPositivePattern_Get(format: NumberFormatInfo { CurrencyDecimalDigits = 2, CurrencyDecimalSeparator = \&quot;.\&quot;, CurrencyGroupSeparator = \&quot;,\&quot;, CurrencyGroupSizes = [3], CurrencyNegativePattern = 0, ... }, expectedWindows: 0, expectedIcu: 1)" type="System.Globalization.Tests.NumberFormatInfoPercentPositivePattern" method="PercentPositivePattern_Get" time="0.0058248" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 0\r\nActual:   1]]></message>
          <stack-trace><![CDATA[   at System.Globalization.Tests.NumberFormatInfoPercentPositivePattern.PercentPositivePattern_Get(NumberFormatInfo format, Int32 expectedWindows, Int32 expectedIcu) in C:\Users\vikto\Documents\src\corefx\src\System.Globalization\tests\NumberFormatInfo\NumberFormatInfoPercentPositivePattern.cs:line 26]]></stack-trace>
        </failure>
      </test>
```

```
<test name="System.Globalization.Tests.NumberFormatInfoPercentNegativePattern.PercentNegativePattern_Get(format: NumberFormatInfo { CurrencyDecimalDigits = 2, CurrencyDecimalSeparator = \&quot;.\&quot;, CurrencyGroupSeparator = \&quot;,\&quot;, CurrencyGroupSizes = [3], CurrencyNegativePattern = 0, ... }, expectedWindows: 0, expectedIcu: 1)" type="System.Globalization.Tests.NumberFormatInfoPercentNegativePattern" method="PercentNegativePattern_Get" time="0.00054" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 0\r\nActual:   1]]></message>
          <stack-trace><![CDATA[   at System.Globalization.Tests.NumberFormatInfoPercentNegativePattern.PercentNegativePattern_Get(NumberFormatInfo format, Int32 expectedWindows, Int32 expectedIcu) in C:\Users\vikto\Documents\src\corefx\src\System.Globalization\tests\NumberFormatInfo\NumberFormatInfoPercentNegativePattern.cs:line 26]]></stack-trace>
        </failure>
      </test>
```

**Comment by tarekgh** [comment]
@ViktorHofer any idea why this started to fail? which OS you are running on?

**Comment by ViktorHofer** [comment]
Hey Tarek. Right in the middle of diagnosing possibles causes. Windows 10 1703 - 16170. Aaah yeah this is the new build which just came out a few days ago. I will check back later today after I reverted to the 1703 stable.

**Comment by tarekgh** [comment]
do you know with which culture this is failing?

**Comment by ViktorHofer** [comment]
Yeah the test is using en-US

Sent from my Windows 10 phone

**Comment by tarekgh** [comment]
@ViktorHofer will you fix this one or you want me help with it?

**Comment by ViktorHofer** [comment]
We just talked about that offline. Thanks @tarekgh for contacting the corresponding Team! Here are the news:

These 4 locales were changed in the recent Windows 10 Insider fast ring build (16170) which caused the two tests to fail as the percentage pattern change from 0 "N %" to 1 "N%":
• en-US
• es-MX
• nl-NL
• en-CA

We depend on the underlying OS implementation, therefore this issue hasn't yet occured on any other dev machine than mine. Changed milestone to future as we have plenty of time to fix that...

@tarekgh: Yes I will fix it. It seems that just affects those two tests therefore I will check the underlying operation system version like we did with the Unicode9 change. Okay for you?

**Comment by tarekgh** [comment]
I would suggest not testing these values at all on Windows. we already covering the parity testing with the OS in the test https://github.com/dotnet/corefx/blob/master/src/System.Globalization/tests/CultureInfo/CultureInfoAll.cs

really I am trying to avoid the hard coded values which keep changing and keep breaking the tests for no reason.

**Comment by ViktorHofer** [comment]
I agree and for others who are following, here is the article which describes why you shouldn't rely on specific culture data: https://blogs.msdn.microsoft.com/shawnste/2005/04/05/culture-data-shouldnt-be-considered-stable-except-for-invariant/
