### ISSUE TITLE
Desktop: System.Net.Tests.HttpWebRequestTest.Abort_BeginGetResponseThenAbort_ResponseCallbackCalledBeforeAbortReturns failed with "Xunit.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18204]
Failed test: System.Net.Tests.HttpWebRequestTest.Abort_BeginGetResponseThenAbort_ResponseCallbackCalledBeforeAbortReturns

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/14/testReport/System.Net.Tests/HttpWebRequestTest/Abort_BeginGetResponseThenAbort_ResponseCallbackCalledBeforeAbortReturns_remoteServer__https___corefx_net_cloudapp_net_Echo_ashx_/

MESSAGE:
Assert.Equal() Failure\r\nExpected: 1\r\nActual: 0
+++++++++++++++++++

STACK TRACE:
at System.Net.Tests.HttpWebRequestTest.Abort_BeginGetResponseThenAbort_ResponseCallbackCalledBeforeAbortReturns(Uri remoteServer) in D:\j\workspace\outerloop_net---903ddde6\src\System.Net.Requests\tests\HttpWebRequestTest.cs:line 549

**Comment by davidsh** [comment]
Fixed as part of #18163
