### ISSUE TITLE
Desktop: System.ComponentModel.Tests.MemberDescriptorTests.CopiedMemberDescriptorEqualsItsSource failed with "Xunit.Sdk.TrueException"

### ISSUE THREAD

**Issue by KristinXie1** [dotnet/corefx#18201]
Failed test: System.ComponentModel.Tests.MemberDescriptorTests.CopiedMemberDescriptorEqualsItsSource

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/14/testReport/System.ComponentModel.Tests/MemberDescriptorTests/CopiedMemberDescriptorEqualsItsSource/

**MESSAGE:**
Assert.True() Failure\r\nExpected: True\r\nActual: False
+++++++++++++++++++

**STACK TRACE:**
at System.ComponentModel.Tests.MemberDescriptorTests.CopiedMemberDescriptorEqualsItsSource() in D:\j\workspace\outerloop_net---903ddde6\src\System.ComponentModel.TypeConverter\tests\MemberDescriptorTests.cs:line 32

**Comment by safern** [comment]
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/15/testReport/System.ComponentModel.Tests/MemberDescriptorTests/CopiedMemberDescriptorEqualsItsSource/

In the latest build this shows as fixed -- this was fixed on PR: https://github.com/dotnet/corefx/pull/18010

Release run:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_release/lastCompletedBuild/testReport/System.ComponentModel.Tests/MemberDescriptorTests/CopiedMemberDescriptorEqualsItsSource/

Closing... we can reopen if we see a failure again.

**Comment by Jiayili1** [comment]
This issue is repro on Full framework tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170420.02/workItem/System.ComponentModel.TypeConverter.Tests/analysis/xunit/System.ComponentModel.Tests.MemberDescriptorTests~2FCopiedMemberDescriptorEqualsItsSource

**Comment by Jiayili1** [comment]
Failed again on desktop: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/34/testReport/System.ComponentModel.Tests/MemberDescriptorTests/CopiedMemberDescriptorEqualsItsSource/

**Comment by danmosemsft** [comment]
@safern, @AlexGhiondea is there anything of interest to 2.0 here? I assume not. if not we can move out.

Just above this assert is
```
            var attributes = new Attribute[]
            {
                new CategoryAttribute(description),
                // setting Decription and Category the same as .NET Framework has a bug in the equals that compares them
                // instead of each other. In .NET 4.6.2 and greater this is no longer an issue but to make the test
                // work on all platforms just setting them to be the same.
                new DescriptionAttribute(description)
            };
```

**Comment by safern** [comment]
This is quirked behavior that when TFM is < 4.6.2 MemberDescriptor.Equals does the comparison of object1.description vs object2.category instead of description vs description, so that is why @weshaggard decided to add category and description to be the same value, I tried to repro and didn't get a local repro, it seems to be flaky. But I don't really know why if it is pretty clear that description and category have the same value.

**Comment by safern** [comment]
http://index/?query=MemberDescriptor.Equals&rightProject=System&file=%5BRepoRoot%5D%5CNDP%5Cfx%5Csrc%5Ccompmod%5Csystem%5Ccomponentmodel%5CMemberDescriptor.cs&line=331

**Comment by safern** [comment]
https://referencesource.microsoft.com/#System/compmod/system/componentmodel/MemberDescriptor.cs,331

**Comment by danmosemsft** [comment]
@safern since this is desktop only, in a less critical API, and seems likely a flaky test, moved to future.

**Comment by safern** [comment]
Thanks @danmosemsft the test is already disable so sounds reasonable.

**Comment by safern** [comment]
Closing as we're no longer testing for netfx for this test assembly after: https://github.com/dotnet/corefx/pull/37972
