### ISSUE TITLE
HttpContent.LimitArrayPoolWriteStream.Write causes a Grow on every call

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/corefx#18219]
The code in the Write is:
EnsureCapacity(_buffer.Length + count);

The _buffer.Length is the size of the buffer, not the number of bytes written to it. So with this we're always asking for more than the buffer has room for, and thus we will call Grow. Grow is exponential (doubles the size of the buffer), so enough small writes into the stream will cause the Grow to ask for huge buffer and eventually run out of memory.
The correct code should be:
EnsureCapacity(_length + count);

**Comment by vitek-karas** [comment]
@davidsh 
@CIPop

**Comment by vitek-karas** [comment]
This breaks several applications in ProjectN.

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by davidsh** [comment]
>This breaks several applications in ProjectN.

Can you explain in more detail about how this breaks several applications?  This code is also used for non-UWP stuff...so why aren't we seeing problems there?  What is different about this code in UWP that causes problems?

**Comment by vitek-karas** [comment]
I honestly don't know. I ran it under the debugger and saw the Grow method being called over and over growing the buffer beyond 250MB, then it got OOM. So I looked at the callers and spotted this issue. I don't have an explanation why it doesn't repro elsewhere.

**Comment by danmosemsft** [comment]
Should be in 2.0 maybe?

**Comment by stephentoub** [comment]
I'll fix it.
