### ISSUE TITLE
Compile warning: Duplicate resource name "net_PropertyNotSupportedException" is not allowed

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#18211]
Occurred during test runs of https://github.com/dotnet/corefx/pull/18170 for portablelinux_debug

@davidsh - duplicate resource added 4/10/2017 in https://github.com/dotnet/corefx/commit/bbe86c8f0e113d70d0d97936cc254889afbbe149#diff-bac3839a816a936d5db4ecb32728de17

````
./src/Resources/Strings.resx : warning MSB3568: Duplicate resource name "net_PropertyNotSupportedException" is not allowed, ignored. [/mnt/resource/j/workspace/dotnet_corefx/master/portablelinux_debug_prtest/src/System.Net.Requests/tests/System.Net.Requests.Tests.csproj]
````

**Comment by davidsh** [comment]
#18163 introduced this presumably.  But it was merged after going clean thru CI.

Do compile warnings block CI?

cc: @stephentoub
