### ISSUE TITLE
TestProcessOnRemoteMachineWindows crashes on uapaot test runs

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#18212]
Test was crashing by throwing an AV when trying to call `Process.GetProcessById(currentProcess.Id, "127.0.0.1")`. I didn't to more deep investigation on it, but I disabled it for now for uapaot runs.

cc: @Priya91

**Comment by Priya91** [comment]
@joperezr Can you also provide information on how to repro the test failure locally for uwp?

**Comment by joperezr** [comment]
Sure, I'm in the process of writting a OneNote with the instructions.

**Comment by danmosemsft** [comment]
@safern maybe this test can be enabled now, quite likely it got fixed since.

**Comment by safern** [comment]
Will give it a try.
