### ISSUE TITLE
Xml_SystemPathResolverCannotOpenUri resource is empty

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/corefx#18225]
XmlSystemPathResolver will throw for Uris which are not from a local file system. The error message it uses is resource Xml_SystemPathResolverCannotOpenUri, but that resource is empty.
It used to look like:
Cannot open '{0}'. The Uri parameter must be a file system relative or absolute path.

**Comment by vitek-karas** [comment]
This is causing trouble in ProjectN when we validate the framework with applications.

**Comment by danmosemsft** [comment]
Oops, that's easily fixed. Looks like it's a new resource in Core. @sepidehMS could you please unblock @vitek-karas

**Comment by danmosemsft** [comment]
@krwq since @sepidehMS is out. I would do it, but I don't know what the string should say.
