### ISSUE TITLE
HttpWebRequest on corefx significantly slower than that of the .NET Framework

### ISSUE THREAD

**Issue by shravan2x** [dotnet/corefx#18237]
As per the title, the current HttpWebRequest is implemented as a wrapper around HttpClient. This change is problematic for many reasons, mainly that HttpClient forces the user to reuse the same configuration across requests via `HttpClientHandler` and `HttpClient`. This would be quite alright for a REST focused library such as RestSharp, but (atleast in my opinion) is an outright _bad_ idea for the main HTTP solution in a major framework.

This is a much smaller problem in the full .NET Framework as it fully supports both solutions. People who preferred to change these settings on a per-request basis could use `HttpWebRequest` and REST focused users could employ `HttpClient`. Some of the settings of `HttpWebRequest` I change on a regular basis are `Proxy`, `AllowAutoRedirect` and `Timeout`.

These are some benchmarks I ran on the .NET Framework 4.6 (The leftmost number is the average time in ms. The `RestSharp` benchmarks are present just for reference.):

```
HttpWebRequest
70   | 70   69   70   70   70   69   71   70   71   73   71   69   71   69   70  70   70   70   70   69

HttpWebRequest-Async
69   | 67   69   72   69   67   69   70   71   67   70   70   69   70   69   70  69   68   71   71   70

HttpClient-Async
151  | 145  154  149  147  149  149  148  147  152  151  163  151  154  153  152  161  147  151  149  152

HttpClient-Async,Reused
72   | 154  74   69   60   62   72   67   70   72   60   70   64   63   70   63  72   71   72   71   73

RestClient
71   | 74   73   75   72   73   62   73   70   76   73   74   74   75   67   74   74   70   73   74   62

RestClient-Reused
70   | 72   71   71   72   59   70   70   70   70   71   70   71   70   71   71   77   74   72   72   73
```

And the same benchmarks on .NET Framework 4.7:

```
HttpWebRequest
37   | 32   38   44   42   48   42   38   36   33   38   35   40   34   38   41   32   33   35   39   33

HttpWebRequest-Async
28   | 38   35   34   38   33   20   30   26   27   21   26   26   26   25   28   27   28   27   27   25

HttpClient-Async
48   | 46   48   45   51   46   46   52   45   48   48   46   48   48   46   48   46   46   46   70   58

HttpClient-Async,Reused
23   | 49   19   25   23   22   20   20   19   21   22   23   21   28   19   28   21   21   26   20   21

RestClient
38   | 53   48   42   39   40   38   41   43   39   44   40   36   41   40   35   37   37   20   27   36

RestClient-Reused
28   | 27   29   28   32   28   28   30   27   27   30   28   26   26   27   27   27   27   37   40   28
```

The above benchmarks are from a Windows 10 system running the creators update. The requests were made to a 6KB resource on a CDN. The tests were run on different hardware from different locations, but since I'd like to focus only on their relative performance, this should not be a problem. Please correct me if I'm wrong.

The most glaring difference between the two benchmarks is that .NET 4.7 optimized creating new `HttpClient` instances greatly (On .NET 4.6, the `HttpClient` row was consistently 150ms+). Note that while I was able to compile `2.0.0-preview1`, I have not tested the above on it.

The .NET framework appears to use a different approach (Seen at https://referencesource.microsoft.com/#System/net/System/Net/HttpWebRequest.cs). Please consider using a similar approach. Using an `HttpClient` under the hood of an `HttpWebRequest` seems more like a duct-tape solution just in the interest of maintaining compatibility. I would argue it does not accomplish this anyway, since programs that worked well on the .NET Framework would appear to work on .NET Core, only for the developers to find performance issues with no clue as to their cause (Creating a new `HttpClient` took almost 20ms more each request than `HttpWebRequest`!).

As as aside, I can imagine code as such as the following would causes deadlocks in cases where the synchronization context needs to be maintained (but I'm not sure if this case is handled elsewhere).

```
public override Stream GetRequestStream()
{
    return InternalGetRequestStream().Result;
}
```
<br/>

**UPDATE**:

These are the .NET Core 1.1 benchmarks on the same system as .NET 4.6 above.

```
HttpClient-Async
209  | 208  210  207  212  205  207  212  218  211  210  214  210  205  200  209  217  214  205  215  203

HttpClient-Async,Reused
72   | 204  58   73   66   61   58   60   60   69   67   58   69   60   72   70  69   70   66   70   70

RestClient
216  | 218  212  229  221  212  219  212  209  204  213  212  212  218  219  219   220  223  220  211  217

RestClient-Reused
215  | 208  213  211  211  221  227  211  214  214  220  213  210  219  218  210  217  211  231  215  225
```

I used the `RestSharp.NetCore` package in the test above, which uses `HttpWebRequest` internally (Which in turn creates new `HttpClient` instances under the hood). The performance hit is clear. `RestClient` takes around 8ms longer for its own code.

**Comment by shravan2x** [comment]
On another note, is this a valid HTTP header?

```
public bool KeepAlive
{
    get
    {
        return _webHeaderCollection[HttpKnownHeaderNames.KeepAlive] == bool.TrueString;
    }
    set
    {
        if (value)
        {
            SetSpecialHeaders(HttpKnownHeaderNames.KeepAlive, bool.TrueString);
        }
        else
        {
            SetSpecialHeaders(HttpKnownHeaderNames.KeepAlive, bool.FalseString);
        }
    }
} 
```

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive suggests that this should never be a true or false value. Shouldn't we be setting `Connection: keep-alive` instead?

**Comment by davidsh** [comment]
Regarding this issue:
>As as aside, I can imagine code as such as the following would causes deadlocks in cases where the synchronization context needs to be maintained (but I'm not sure if this case is handled elsewhere).

```c#
public override Stream GetRequestStream()
{
    return InternalGetRequestStream().Result;
}
```

That is being tracked here: #11873

In terms of changing the architecture for .NET Core HttpWebRequest, that is not going to happen in the short term. It will remain a layer over HttpClient.  The HTTP stack architecture in .NET Core is different than .NET Framework.  We consider HttpWebRequest a "legacy" API surface and it is in .NET Core to help devs port their existing code. But best practice is to use HttpClient API surface directly.

cc: @stephentoub

**Comment by karelz** [comment]
@davidsh given that we do not plan to invest into the compat-only API, should we just close the issue?

cc @geoffkizer

**Comment by davidsh** [comment]
>@davidsh given that we do not plan to invest into the compat-only API, should we just close the issue?

Yes. Other than addressing #11873 and #15460, there is no other work planned.

**Comment by karelz** [comment]
OK, closing then. @shravan2x feel free to reopen if you disagree or if there some evidence you think we missed. Thank you!

**Comment by shravan2x** [comment]
@karelz @davidsh I understand your point of view on spending less time on deprecated APIs, but I disagree with it. #15460 refers to reusing an `HttpClient` if all default settings match. While this is a good optimization, it is exactly the issue I'm arguing against.

Given a case where I use the default (or in general, just the _same_ settings across my application), I would use `HttpClient` as it meets the expected use-case. The case I'm pushing for is one where the `HttpClient` configuration would have to change every request. Right now, the best solution (I think) would be to maintain a configuration-HttpClient dictionary, which would be significantly inefficient for obvious reasons.

Another case where `HttpClient` would be the worse solution would be where the requests would complete very fast. This is because it does not provide support for purely synchronous code (See https://stackoverflow.com/questions/16194054/is-async-httpclient-from-net-4-5-a-bad-choice-for-intensive-load-applications and this http://stackoverflow.com/a/16528153/1935753 answer to it).

My main argument is that **`HttpClient` is not a good replacement for HttpWebRequest**. Because of this, HttpWebRequest should not be marked as a compat-only API, but a solution to a different problem than `HttpClient` addresses.

Could you also comment on https://github.com/dotnet/corefx/issues/18237#issuecomment-293434111?

**Comment by karelz** [comment]
If you think that `HttpClient` is lacking some important capabilities or characteristics, then please open issues for that. IMO it should not be reason for resurrecting compat-only APIs. Otherwise we would be soon maintaining several different stacks, which is not sustainable (it would drain resources from delivering innovation).
It would be great if you can provide real-world examples where particular things truly matter (i.e. real-world applications which truly hit the boundaries).

Note that we are working on new plans for networking stack - how to make it more performant, mnore reliable and support latest protocols. I hope we will be able to publish the plans in next few weeks.

Regarding your question above (https://github.com/dotnet/corefx/issues/18237#issuecomment-293434111), I don't know the answer. Note that it got lost in the larger issue. If you don't get response in next few days here, please file a new issue.

**Comment by shravan2x** [comment]
@karelz  I also you had added the **2.0.0** milestone. Could you clarify this change?

**If you think that HttpClient is lacking some important capabilities or characteristics, then please open issues for that.**
I will do this. Is https://github.com/dotnet/corefx the right repo to post such an issue?

**It would be great if you can provide real-world examples where particular things truly matter (i.e. real-world applications which truly hit the boundaries).**
While in no way an exhaustive list, here are some ways I use `HttpWebRequest` which `HttpClient` makes complicated or impossible:
1. I believe the [stackoverflow question from my last comment](https://stackoverflow.com/questions/16194054/is-async-httpclient-from-net-4-5-a-bad-choice-for-intensive-load-applications) is a good example. I have a large group of applications that communicate very frequently over localhost (In a way similar to analytics monitoring) and a lot of these JSON communications are very small, usually similar to `{"success":true}` or at most around 40 bytes. Using async does not make sense in this case.
2. Another good example is long-polling. While not a very commonly used technique in 2017, popular websites such as https://steamcommunity.com use it in their web-based chat systems. It is in the common interest to use varying timeouts here. Creating new `HttpClients` per request does not make sense. (**Side question**: Are persistent connections kept-alive between `HttpClient` instances?)
3. I usually leave `AllowAutoRedirect` set to `true` to allow the server to redirect me in the case that some resource's location has changed. However, I also often disable this when the status code itself is the information I need (Think sending a **HEAD** request to find a user's profile name from a redirected path like `/my`).

**Note that we are working on new plans for networking stack - how to make it more performant, mnore reliable and support latest protocols. I hope we will be able to publish drafts of the plans in next few weeks.**
This is good to hear. Please point me in the direction of any available resources if possible.

**If you don't get response in next few days here, please file a new issue.**
Regarding (https://github.com/dotnet/corefx/issues/18237#issuecomment-293434111), I have made a separate issue [here](https://github.com/dotnet/corefx/issues/18448).

**Comment by karelz** [comment]
> I noticed you had added the 2.0.0 milestone. Could you clarify this change?

The issue has been closed in the 2.0 product timeframe, that's why it has milestone 2.0.

> I will do this. Is https://github.com/dotnet/corefx the right repo to post such an issue?

Yes, this is the right place.

> While in no way an exhaustive list

Please make sure the relevant real-world examples are preserved in the issues that you file. On closed issues like this one, they will be lost and out of context.

> (2) Another good example is long-polling. ... Creating new HttpClients per request does not make sense.

Why cannot you just reuse HttpClient instances in this case?

> (3) I usually leave `AllowAutoRedirect` set to true to allow the server to redirect me in the case that some resource's location has changed.

Are you saying that `HttpClient` does not have the capability to disable `AllowAutoRedirect`?
How common is this pattern in general (not just your apps)?

> Please point me in the direction of any available resources if possible.

I will announce the info in a new CoreFX repo issue and also on Twitter (my account and dotnet account).

**Comment by shravan2x** [comment]
> Why cannot you just reuse HttpClient instances in this case?

I should have worded this better. There are usually multiple endpoints which I need to long-poll, each having different optimal timeouts. I suppose it is possible for me to use a separate `HttpClient` for each, but this just seems like bad framework design projecting into libraries.

> Are you saying that HttpClient does not have the capability to disable AllowAutoRedirect?
> How common is this pattern in general (not just your apps)?

No, `AllowAutoRedirect` is a property of `HttpClientHandler`. Even _if_ `HttpClient` had such a property, it would instead need to be in `HttpRequestMessage` so it can be changed on a per-request basis. In my experience, changing `AllowAutoRedirect` per-request is a commonly used technique to read the `Location` header (For many different reasons).

Do you know if persistent connections are kept-alive between HttpClient instances?

**Comment by geoffkizer** [comment]
Re KeepAlive property on HttpWebRequest:  That does look weird to me.  I would think we'd use Connection: keep-alive here.

**Comment by geoffkizer** [comment]
Re the stackoverflow post on sync vs async performance, I've seen this same code posted in a different context (I think it was a blog post).

I don't believe this is a useful perf test.  What it does is try to start a huge number of HTTP requests (I think the original blog post did a million, this one seems to do 10000) simultaneously.  I don't believe this is representative of what real world apps do.  (Not to say they don't issue tons of HTTP requests, but they don't do them at the exact same time.)  The test ends up measuring things like threadpool throttling policy and connection pooling policy as opposed to raw performance of async vs sync.

In theory, in certain specific circumstances, if you're simply blocking the calling thread anyway (i.e. task.Wait() or similar), then async can have more overhead than sync because the completion happens on the threadpool and then has to notify the original thread, instead of completing directly on the original thread as a sync call would do.  In practice, I have trouble coming up with real world scenarios where this would matter.  If you have such a scenario, I'd be interested to see it.

**Comment by geoffkizer** [comment]
> Do you know if persistent connections are kept-alive between HttpClient instances?

Mu understanding is that connections are not shared between HttpClient instances.  @davidsh would know for sure.

**Comment by geoffkizer** [comment]
I think that allowing per-request control over stuff like AllowAutoRedirect and timeouts etc is definitely interesting.  It would be great to understand the scenarios for this in more detail, this would help shape how we expose such functionality in the future.  Please reference me on any issues you file regarding this.

**Comment by stephentoub** [comment]
For timeouts specifically, unless they're more granular than the whole request, the CancellationToken provided to SendAsync should suffice I expect. That's how HttpClient.Timeout is implemented, basically by using CancellationTokenSource created with a timeout.

**Comment by karelz** [comment]
@shravan2x 

> I suppose it is possible for me to use a separate `HttpClient` for each, but this just seems like bad framework design projecting into libraries.

Why do you think using multiple instances is a bad design? Can you please provide more details? To me it feels just like slightly different API design.

> In my experience, changing `AllowAutoRedirect` per-request is a commonly used technique to read the `Location` header

Can you please file a separate issue? (with details about the scenarios as @geoffkizer hinted in https://github.com/dotnet/corefx/issues/18237#issuecomment-294366218) Let's move the specific discussion there, thanks!
