### ISSUE TITLE
BigInteger performance tests do not work with xunit.performance

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#18248]
The tests in this file do not work when run under the current perf test environment.

https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Numerics/tests/BigInteger/PerformanceTests.cs

I am going to disable them until I have time to re-work them with the correct style.

**Comment by adamsitnik** [comment]
Fixed https://github.com/dotnet/performance/pull/99
