### ISSUE TITLE
Cannot build Core FX (resolve failure)

### ISSUE THREAD

**Issue by parjong** [dotnet/corefx#18261]
Core FX build failed with the following error message:
```
$ ./build-managed.sh
Installing dotnet cli...
Restoring BuildTools version 1.0.27-prerelease-01511-02...
Initializing BuildTools...
BUILDTOOLS_SKIP_CROSSGEN is set. Skipping crossgen step.
Making all .sh files executable under Tools.
Done initializing tools.
Running: /var/jenkins/workspace/FX/FX_Test_Release/repo/code/Tools/msbuild.sh /nologo /verbosity:minimal /clp:Summary /maxcpucount /l:BinClashLogger,Tools/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log /p:ConfigurationGroup=Debug /p:BuildPackages=false  /flp:v=normal  /flp2:warningsonly;logfile=msbuild.wrn  /flp3:errorsonly;logfile=msbuild.err
/var/jenkins/workspace/FX/FX_Test_Release/repo/code/Tools/packageresolve.targets(86,5): error : The package Microsoft.Build with version 0.1.0-preview-00022 could not be found in /var/jenkins/workspace/FX/FX_Test_Release/repo/code/packages/, /var/jenkins/workspace/FX/FX_Test_Release/repo/code/packages, /root/.dotnet/NuGetFallbackFolder. Run a NuGet package restore to download the package. [/var/jenkins/workspace/FX/FX_
Test_Release/repo/code/src/Tools/CoreFx.Tools/CoreFx.Tools.csproj]
...
```

It seems that ``packages/microsoft.build/0.1.0-preview-00022/`` is restored:
```
$ pwd
/var/jenkins/workspace/FX/FX_Test_Release/repo/code
$ ls packages/microsoft.build/0.1.0-preview-00022/
lib  microsoft.build.0.1.0-preview-00022.nupkg  microsoft.build.0.1.0-preview-00022.nupkg.sha512  microsoft.build.nuspec
```

**Comment by karelz** [comment]
cc @mellinoe @weshaggard @ericstj

**Comment by ericstj** [comment]
@mellinoe is this some sort of casing problem following your CLI update?

**Comment by mellinoe** [comment]
It does look to be (Microsoft.Build vs. microsoft.build), but I'm not sure how or why it would be happening here. `PrereleaseResolveNuGetPackageAssets` should handle this case now.

@parjong Any chance you have old files lying around in your Tools folder? I haven't seen this on the systems I've tested.

**Comment by ericstj** [comment]
I see what it it is:
https://github.com/dotnet/buildtools/commit/7db3dfa102fe5865584c26ae398487b73ed11488#diff-3bb19c9cf0b9fb2a765b49b9c0c2a5feR905

That lower cases the entire path, not just the package ID.  @parjong has upper case characters in his path that you broke by lower-casing them.

**Comment by mellinoe** [comment]
Yep, that would do it. I'll put a fix up for that soon.

**Comment by mellinoe** [comment]
https://github.com/dotnet/buildtools/pull/1433 should do the trick.
