### ISSUE TITLE
Desktop: XmlDictionaryWriterTest.FragmentTest failed 

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18273]
Failed test: XmlDictionaryWriterTest.FragmentTest

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/15/testReport/(root)/XmlDictionaryWriterTest/FragmentTest/

MESSAGE:
Assert.False() Failure\r\nExpected: False\r\nActual: True
+++++++++++++++++++
STACK TRACE:
at XmlDictionaryWriterTest.FragmentTest() in D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime.Serialization.Xml\tests\XmlDictionaryWriterTest.cs:line 299

**Comment by zhenlan** [comment]
@Jiayili1 please add this to this test:
```
[SkipOnTargetFramework(TargetFrameworkMonikers.NetFramework, "is implemented on full framework")]
```
then you can close this issue.

**Comment by Jiayili1** [comment]
#18371

**Comment by zhenlan** [comment]
Thanks @Jiayili1.

**Comment by weshaggard** [comment]
@zhenlan what does "is implemented on full framework" mean in this context?

**Comment by zhenlan** [comment]
That's because it is a negative test case. The scenario actually works on full framework. Yes, the message is a bit confusing even though it's correct 😄.

**Comment by weshaggard** [comment]
OK then do we want a positive test as well for desktop?

**Comment by zhenlan** [comment]
Desktop has its own test bed. It should be covered already.

**Comment by danmosemsft** [comment]
@weshaggard in generally we seem to be occasionally adding Desktop-only tests when it's helpful to contrast with .NET Core behavior but not attempting to make a Desktop testbed. From chatting to Jan that is not a reaonable goal.

**Comment by weshaggard** [comment]
OK I'm fine with that for things that are shipping inbox (which is this case I believe), but for cases were the code actually ships out of corefx for desktop then we should have test coverage for it.
