### ISSUE TITLE
Desktop: XmlDictionaryWriterTest.CreateMtomReaderWriter_Throw_PNSE failed with "Xunit.Sdk.ThrowsException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18274]
Failed test: XmlDictionaryWriterTest.CreateMtomReaderWriter_Throw_PNSE

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/15/testReport/(root)/XmlDictionaryWriterTest/CreateMtomReaderWriter_Throw_PNSE/

MESSAGE:
Assert.Throws() Failure\r\nExpected: typeof(System.PlatformNotSupportedException)\r\nActual: (No exception was thrown)
+++++++++++++++++++
STACK TRACE:
at XmlDictionaryWriterTest.CreateMtomReaderWriter_Throw_PNSE() in D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime.Serialization.Xml\tests\XmlDictionaryWriterTest.cs:line 174

**Comment by danmosemsft** [comment]
@Jiayili1 please add this to this test:
```
[SkipOnTargetFramework(TargetFrameworkMonikers.NetFramework, "is implemented on full framework")]
```
then you can close this issue.

**Comment by Jiayili1** [comment]
#18363

**Comment by danmosemsft** [comment]
fixed
