### ISSUE TITLE
Remove dependency System.Private.Xml dependency on System.Reflection.Emit.* on uapaot

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#18283]
System.Reflection.Emit.* is not available on uapaot. System.Private.Xml dependency on System.Reflection.Emit.* should be removed.

https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System.Private.Xml.csproj#L517

**Comment by sepidehMS** [comment]
@krwq This seems to be a dupe of https://github.com/dotnet/corefx/issues/20739

**Comment by krwq** [comment]
Yep
