### ISSUE TITLE
Remove .rd.xml directive for RuntimeBinderException from System.Linq.Expressions rd.ml

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/corefx#18292]
The .rd.xml embedded in System.Linq.Expressions has a runtime directive for RuntimeBinderException which comes from the Microsoft.CSharp assembly.
For one the directive is in the wrong assembly element and causes warnings.
The other issue is that Microsoft.CSharp is not in the closure of references from System.Linq.Expressions, so System.Linq.Expressions should not have a directive for it, as it's not guaranteed to always be present.

**Comment by VSadov** [comment]
I think the directive should be added to the rd.xml of Microsoft.CSharp instead. 
Microsoft.CSharp does use this type dynamically in
https://github.com/dotnet/corefx/blob/23a1e8c7cd760602b11666e43c5c43539cccc82f/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/BinderHelper.cs#L139

**Comment by vitek-karas** [comment]
It's actually unclear whether we need that directive at all. The type was used dynamically before, and we didn't need the directive. I want to understand this a little before using the "big cannon" solution of adding it to .rd.xml.

**Comment by joshfree** [comment]
Any update on this?  This is causing some AppCompat failures

**Comment by vitek-karas** [comment]
Waiting on getting the latest CoreFx bits into .NET Native toolchain to validate. But right now it seems we don't need the directive at all (there are no AppCompat failures due to this anymore).

**Comment by vitek-karas** [comment]
The problem doesn't show up in latest AppCompat runs which include very recent CoreFx. So there's nothing to fix here.
