### ISSUE TITLE
Using incorrect API in GetExceptionFromNtStatus

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#18293]
RtlNtStatusToDosError should be LsaNtStatusToWinError. It's just a bug -- MSDN says LsaNtStatusToWinError for all LsaLogonUser calls and it's what Desktop uses. Don't know why we changed it.

Incidentally it's also what windows intend to add to WACK so it's necessary for UWP but since we already shipped and it works it desn't seem needed for 2.0

```
        private static Exception GetExceptionFromNtStatus (int status) {
            if ((uint) status == Win32Native.STATUS_ACCESS_DENIED)
                return new UnauthorizedAccessException();

            if ((uint) status == Win32Native.STATUS_INSUFFICIENT_RESOURCES || (uint) status == Win32Native.STATUS_NO_MEMORY)
                return new OutOfMemoryException();

            int win32ErrorCode = Win32Native.RtlNtStatusToDosError(status);
            return new SecurityException(Win32Native.GetMessage(win32ErrorCode));
```

**Comment by danmosemsft** [comment]
@ptorr-msft fyi.

**Comment by danmosemsft** [comment]
@joperezr could you please do this and then remove the pinvoke baselining for it?

**Comment by joperezr** [comment]
sure, will take care of it.

**Comment by danmosemsft** [comment]
To be explicit: we need to replace all use of RtlNtStatusToDosError in the tree not just for lsalogonuser.

**Comment by joperezr** [comment]
yeah, I found 5 calls to it, and replaced them. I'm done with the changes for netcoreapp but I'm missing some for uap, will send out a PR when I'm done.

**Comment by danmosemsft** [comment]
@joperezr do you havea partial change I could help finish

**Comment by joperezr** [comment]
Oh sorry totally forgot about this one, I actually had it almost done, I'll merge this in first thing tomorrow
