### ISSUE TITLE
Desktop: DataContractSerializerTests.XsdDataContractExporterTest failed with "XUnit.Sdk.ThrowsException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18313]
Failed test: DataContractSerializerTests.XsdDataContractExporterTest

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/16/testReport/(root)/DataContractSerializerTests/XsdDataContractExporterTest/

**MESSAGE:**
Assert.Throws() Failure\r\nExpected: typeof(System.PlatformNotSupportedException)\r\nActual: (No exception was thrown)
+++++++++++++++++++

**STACK TRACE:**
at DataContractSerializerTests.XsdDataContractExporterTest() in D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime.Serialization.Xml\tests\DataContractSerializer.cs:line 2688

**Comment by danmosemsft** [comment]
@shmao I assume this is expected -- we haven't impl this and Desktop has.

@Jiayili1 please disable this test for desktop with
```
[SkipOnTargetFramework(TargetFrameworkMonikers.NetFramework, "Full framework has an implementation and does not throw InvalidOperationException")]
```

**Comment by shmao** [comment]
@danmosemsft yes, this is expected.

**Comment by danmosemsft** [comment]
OK @Jiayili1 please do as I ask above. thanks

**Comment by Jiayili1** [comment]
#18370

**Comment by danmosemsft** [comment]
fixed
