### ISSUE TITLE
Desktop: System.Reflection.Tests.AssemblyNameTests.Ctor_String failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18311]
Failed test: System.Reflection.Tests.AssemblyNameTests.Ctor_String

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/16/testReport/System.Reflection.Tests/AssemblyNameTests/Ctor_String_name____NAME____expectedName____NAME___/

**Message:**
Assert.Equal() Failure
                   (pos 0)
        Expected: NAME
        Actual:   name
                   (pos 0)

**Stack Trace:**
          D:\j\workspace\outerloop_net---903ddde6\src\System.Reflection\tests\AssemblyNameTests.cs(53,0): at System.Reflection.Tests.AssemblyNameTests.Ctor_String(String name, String expectedName)

**Comment by Jiayili1** [comment]
This issue is repro on full framework test, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170420.02/workItem/System.Reflection.Tests/analysis/xunit/System.Reflection.Tests.AssemblyNameTests~2FCtor_String(name:%20%5C%22NAME%5C%22,%20expectedName:%20%5C%22NAME%5C%22)

**Comment by Jiayili1** [comment]
This issue is repro on desktop: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/System.Reflection.Tests/AssemblyNameTests/Ctor_String_name____NAME____expectedName____NAME___/

**Comment by safern** [comment]
@AtsushiKan could you please point out why this test is failing?

**Comment by Jiayili1** [comment]
This issue is repro on desktop, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/30/testReport/System.Reflection.Tests/AssemblyNameTests/Ctor_String_name____NAME____expectedName____NAME___/

**Comment by AtsushiKan** [comment]
Humphf - on the desktop, creating one AssemblyName with the string "name" forces every subsequent creation of AssemblyName to use that capitalization for "NAME". More Fusion madness.

I'd note this one down as a behavioral difference. Without an actual real world scenario, I can't imagine wanting to port this bogosity into .NET Core.

**Comment by safern** [comment]
So then the test should only be disabled and point that behavioral difference.
