### ISSUE TITLE
Desktop: System.PrivateUri.Tests.UriRelativeResolutionTest.Uri_Relative_SimplePartialPathWithScheme_Unicode_ReturnsPartialPathWithScheme failed with "System.NullReferenceException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18314]
Failed test: System.PrivateUri.Tests.UriRelativeResolutionTest.Uri_Relative_SimplePartialPathWithScheme_Unicode_ReturnsPartialPathWithScheme

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/16/testReport/System.PrivateUri.Tests/UriRelativeResolutionTest/Uri_Relative_SimplePartialPathWithScheme_Unicode_ReturnsPartialPathWithScheme

**MESSAGE:**
System.NullReferenceException : Object reference not set to an instance of an object.
+++++++++++++++++++

**STACK TRACE:**
at System.Uri.CreateUriInfo(Flags cF) 
at System.Uri.EnsureUriInfo() 
at System.Uri.ParseRemaining() 
at System.Uri.InitializeUri(ParsingError err, UriKind uriKind, UriFormatException& e) 
at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind) 
at System.PrivateUri.Tests.UriRelativeResolutionTest.Uri_Relative_SimplePartialPathWithScheme_Unicode_ReturnsPartialPathWithScheme() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Private.Uri\tests\FunctionalTests\UriRelativeResolutionTest.cs:line 152

**Comment by Jiayili1** [comment]
Closed issue: https://github.com/dotnet/corefx/issues/13250

**Comment by danmosemsft** [comment]
Seems like a bug in desktop, possibly fixed on our side in https://github.com/dotnet/corefx/pull/9542 tracked by https://github.com/dotnet/corefx/issues/15145

@Jiayili1 please disable this as follows

**Comment by safern** [comment]
Yes I think we should either disable them as per the issue you pointed out mentions they have a lot of quirked behavior... but that is going to be a bottleneck as we depend on xunit TFM, we can't change that and unfortunately xunit's TFM is 4.5.1 which is pretty "old" now.
