### ISSUE TITLE
Desktop: DataContractSerializerTests.DCS_ReadOnlyDictionary failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18312]
DataContractSerializerTests.DCS_ReadOnlyDictionary [FAIL]

**Message:**
~~~
XML comparison is also failing
Test failed for input: System.Collections.ObjectModel.ReadOnlyDictionary`2[System.String,System.Int32
Expected: <ReadOnlyDictionaryOfstringint xmlns="http://schemas.datacontract.org/2004/07/System.Collections.ObjectModel" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><_dictionary xmlns:a="http://schemas.microsoft.com/2003/10/Serialization/Arrays"><a:KeyValueOfstringint><a:Key>Foo</a:Key><a:Value>1</a:Value></a:KeyValueOfstringint><a:KeyValueOfstringint><a:Key>Bar</a:Key><a:Value>2</a:Value></a:KeyValueOfstringint></_dictionary></ReadOnlyDictionaryOfstringint>
Actual: <ReadOnlyDictionaryOfstringint xmlns="http://schemas.datacontract.org/2004/07/System.Collections.ObjectModel" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><m_dictionary xmlns:a="http://schemas.microsoft.com/2003/10/Serialization/Arrays"><a:KeyValueOfstringint><a:Key>Foo</a:Key><a:Value>1</a:Value></a:KeyValueOfstringint><a:KeyValueOfstringint><a:Key>Bar</a:Key><a:Value>2</a:Value></a:KeyValueOfstringint></m_dictionary></ReadOnlyDictionaryOfstringint>

Expected: True
Actual:   False
~~~

**Stack Trace:**
at DataContractSerializerTests.SerializeAndDeserialize[T](T value, String baseline, DataContractSerializerSettings settings, Func`1 serializerFactory, Boolean skipStringCompare) in D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime.Serialization.Xml\tests\DataContractSerializer.cs:line 2799 
at DataContractSerializerTests.DCS_ReadOnlyDictionary() in D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime.Serialization.Xml\tests\DataContractSerializer.cs:line 1891

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/16/testReport/(root)/DataContractSerializerTests/DCS_ReadOnlyDictionary/

**Comment by danmosemsft** [comment]
The difference is between `dictionary` in our baseline and `m_dictionary` in desktop result.

@shmao I've moved this to Future for now since this seems uninteresting. Feel free to change.

**Comment by shmao** [comment]
@danmosemsft Because of the issue, `ReadOnlyDictionary` cannot be transferred between desktop and NetCore. If we make a fix in the future, however, it will break the behavior of NetCore. Do we want to keep the issue open and fix this in the future? 

On the other hand, the root cause of the issue is that we name class members differently on NetCore and on Desktop, which causes the serialization payload for `ReadOnlyDictionary` is not compatible with the payload from desktop. It would be tough to make a fix for this from `DataContractSerializer` side. 

cc: @zhenlan

**Comment by danmosemsft** [comment]
In general we don't plan to support binary serialization exchange between .NET Core and .NET Framework, nor between version of .NET Core. @stephentoub to verify his undrestanding also.

This issue is of course in your area and it's entirely up to you whether you want to fix it though.

**Comment by zhenlan** [comment]
Hi @danmosemsft, this is *not* about binary serialization. It's DataContractSerializer. It's very important to keep compatibility between frameworks for DCS. For example, WCF service is only available on Full Framework, so the .NET Core version of WCF client has to talk with WCF service on full framework and DCS must be compatible.

The fix here needs to happen in `ReadOnlyDictionary`. All it needs is to name its fields in the same way as its full Framework version. There is nothing we can do in serialization. If this is not fixed now, it will only create more compat issues in the future. All we can do in the future is to route any future complaints to the owner of `ReadOnlyDictionary`.

**Comment by stephentoub** [comment]
@zhenlan, is DCS special-casing ReadOnlyDictionary?  If it is, it should be able to smooth over this.  If it's not, you're saying then that DCS is reflecting over and including private fields, and that you expect private fields of a type to never change?  That is not a viable constraint.

**Comment by shmao** [comment]
@stephentoub By default, DCS does not serialize private fields. But ReadOnlyDictionary is marked with `[Serializable]` attribute, so DCS serializes it's private fields. According to [MSDN](https://msdn.microsoft.com/en-us/library/system.serializableattribute(v=vs.110).aspx),

>When you apply the SerializableAttribute attribute to a type, all private and public fields are serialized by default. You can control serialization more granularly by implementing the ISerializable interface to override the serialization process.

Here's just my understanding, when a type is marked with `[Serializable]`, from serialization point of view, its private fields become some kind of APIs.

**Comment by stephentoub** [comment]
> But ReadOnlyDictionary is marked with [Serializable] attribute

[Serializable] is the binary serialization that @danmosemsft is talking about.

**Comment by shmao** [comment]
It seems that we decided to make DCS to support that programming model. According to [Types Supported by the Data Contract Serializer](https://msdn.microsoft.com/en-us/library/ms731923(v=vs.110).aspx), 

> Types marked with the `SerializableAttribute` attribute. Many types included in the .NET Framework base class library fall into this category. The` DataContractSerializer` fully supports this serialization programming model that was used by .NET Framework remoting, the BinaryFormatter, and the SoapFormatter, including support for the `ISerializable` interface.

**Comment by stephentoub** [comment]
Then this isn't just about ReadOnlyDictionary.  There are, last I checked, ~700 [Serializable] types in .NET Core 2.0.  When code was brought to .NET Core, all of the code was formatted to conform to coding guidelines, which included in many cases renaming fields.  Code was optimized, including removing fields.  Code was modified to fix bugs, which included adding and removing fields.  Etc.  At this point there are thousands upon thousands of changes that prevent types from being serialized/deserialized with BinaryFormatter across runtimes, and we have no intention of changing the system to support cross-platform serialization.

**Comment by zhenlan** [comment]
Let's not tie the usage of [Serializable] to binary serialization. Apparently it's used by other serializers too. It *is* the goal for DCS to keep cross framework compatibility.

Maybe it's not just about ReadOnlyDictionary, but we are pushing to fix every one we find during testing. If you think the DCS serialization of most types are already broken, we are essentially breaking the .NET Core story for WCF. I hope this is not the case.

**Comment by terrajobst** [comment]
> Let's not tie the usage of [Serializable] to binary serialization. Apparently it's used by other serializers too.

This concerns me. Just because a type is marked as `[Serializable]` doesn't mean it can be successfully serialized with an arbitrary serializer...

**Comment by stephentoub** [comment]
> If you think the DCS serialization of most types are already broken, we are essentially breaking the .NET Core story for WCF.

If DCS is factoring in [Serializable], then I suspect DCS between Framework and Core is broken for most [Serializable] types implemented in corefx and a fair number implemented in coreclr. If that's a problem, I suggest you revert to not using [Serializable], as must have been done prior to .NET Core 2.0 when [Serializable] wasn't available. We have no plans to make [Serializable] state work reliably between different runtimes.

**Comment by danmosemsft** [comment]
@weshaggard

**Comment by zhenlan** [comment]
Regardless whether [Serializable] is added in .NET Core, it won't change the requirement for the types that need to be serializable and compatible cross framework for DCS. The [Serializable] is present on ReadOnlyDictionary in full Framework, so the "serialization contract" for this type is already defined.

I know we may not like it. We can say .NET Core is new and cool and let it break from the full .NET Framework. That just did not fly for customers until we started NS2.0 effort.

**Comment by SolderedMushroom** [comment]
>I know we may not like it. We can say .NET Core is new and cool and let it break from the full .NET Framework. That just did not fly for customers

Or you only listened to the feedback from the ones who loudly complained, and not those of us who were thrilled that 10-15 years of legacy mess could be discarded and replaced with something better.

**Comment by zhenlan** [comment]
To @terrajobst's concern:

> This concerns me. Just because a type is marked as  [Serializable]  doesn't mean it can be successfully serialized with an arbitrary serializer...

A type with [Serializable] does *not* mean it will be serialized by arbitrary serializer. It only tells serializers that support this serialization programming model the intention of the *type*, for example, whether the type should be serialized, what fields should be serialized etc. Besides binary serializer, DCS supports this model. JSON.NET supports this model in [certain option](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/MemberSerialization.cs#L50) too.  Does this make sense?

To @SolderedMushroom comment, I totally understand, yes, everyone can be in different situations - some will start from scratch for Core and some just want to port their existing code to Core. As a platform to be success, we will have to consider all situations. I think we are trying to do better and cool for .NET Core development wherever we can while evaluating pros and cons 😄.

While I will encourage for compatibility, ultimately, it's the decision of the owner of ReadOnlyDictionary. If you decide to break people in the end I hope you do find value of doing so and ideally you have a mitigation plan in place in case someone is stuck in this issue in the future.

**Comment by Jiayili1** [comment]
This issue is repro on full framework tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170425.01/workItem/System.Runtime.Serialization.Xml.ReflectionOnly.Tests/analysis/xunit/DataContractSerializerTests~2FDCS_ReadOnlyDictionary

**Comment by danmosemsft** [comment]
@morganbr we need to establish whether your changes will "fix" this.

I've moved this to 2.0 while we figure out whether this change is acceptable and whether it will get fixed with our serialization remediation you're doing.

**Comment by danmosemsft** [comment]
(area-serialization may not be the best one)

**Comment by zhenlan** [comment]
Plan is to rename the private field to be desktop compatible.

**Comment by shmao** [comment]
@morganbr can you please confirm if this would be part of https://github.com/dotnet/corefx/issues/19119?

**Comment by zhenlan** [comment]
Relate to #19119

**Comment by karelz** [comment]
@safern Ian is OOF sick, can you please take a look at feasibility of this change in 2.0 ASAP? Thanks!

**Comment by danmosemsft** [comment]
This would be @ViktorHofer actually. He is fixing fields for @morganbr 's 100 (the set of types we plan to support [Serializable] on) to be desktop compatible. ReadOnlyDictionary is on that list.

**Comment by karelz** [comment]
Great, thanks!

**Comment by safern** [comment]
Thanks @karelz and @danmosemsft for follow up!

**Comment by ViktorHofer** [comment]
Fixed here https://github.com/dotnet/corefx/pull/20247

**Comment by ViktorHofer** [comment]
no, this is just the issue. the PRs are tracked by @krwq. He will create an issue soon for corefx which contains all the serialization PRs
