### ISSUE TITLE
Desktop: System.Reflection.Tests.AssemblyTests.Test_LoadFrom failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18310]
Failed test: System.Reflection.Tests.AssemblyTests.Test_LoadFrom

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/16/testReport/System.Reflection.Tests/AssemblyTests/Test_LoadFrom/

**MESSAGE:**
Assert.Equal() Failure
Expected: System.Runtime.Tests, Version=4.2.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb
Actual: System.Runtime.Tests, Version=4.2.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb
+++++++++++++++++++

**STACK TRACE:**
at System.Reflection.Tests.AssemblyTests.Test_LoadFrom() in D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime\tests\System\Reflection\AssemblyTests.cs:line 337

**Comment by safern** [comment]
@AtsushiKan could you please point out why this is failing?

**Comment by AtsushiKan** [comment]
This test doesn't exist anymore...

**Comment by safern** [comment]
Thanks @AtsushiKan

**Comment by karelz** [comment]
@AtsushiKan was it deleted recently? Or how else should I understand the fact that it failed 12 days ago ... it had to IMO exist in CoreFX test suite at that moment.
