### ISSUE TITLE
Min required libcurl version on Redhat?

### ISSUE THREAD

**Issue by TingluoHuang** [dotnet/corefx#18328]
Hi, 

Our [vsts-agent](https://github.com/Microsoft/vsts-agent) is built on  dotnet core 1.1
In pre-req doc dotnet core only mentioned about it needs libcurl on Redhat, but there is no min version.

Since the libcurl in Redhat7.2 is 7.29 which is pretty old, there are few bug we got report about the old version libcurl, ex, NTLM not working properly, proxy not working properly.

Can we update the doc to provide better guidance? 
or Can dotnet core work with Redhat to let them update the libcurl?

We have enterprise customer who are not allowed to update libcurl from source.

**Comment by stephentoub** [comment]
cc: @tmds

**Comment by tmds** [comment]
The dotnet software collection for RHEL has it's own version of curl which is newer than the system version.
```
$ yum list installed | grep curl
curl.x86_64                       7.29.0-39.el7          installed              
libcurl.x86_64                    7.29.0-39.el7          installed              
rh-dotnetcore10-libcurl.x86_64    7.47.1-4.el7           @rhel-7-server-dotnet-rpms
rh-dotnetcore11-libcurl.x86_64    7.47.1-4.el7           @rhel-7-server-dotnet-rpms
```

**Comment by TingluoHuang** [comment]
interesting, but i am shipping my dotnet core self-contained app to my customer, i can't ask them install the SDK in order to get latest libcurl, right?

**Comment by tmds** [comment]
This use-case is not well supported. When you create a self-contained app, the runtime that comes with your app is the one released by Microsoft for rhel on NuGet.
It is preferable to install the dotnet software collection and publish as a portable app.

**Comment by tmds** [comment]
I created an issue to better support this use-case: https://bugzilla.redhat.com/show_bug.cgi?id=1442220

**Comment by karelz** [comment]
Should be covered by RedHat docs above - see the issue linked above. Closing.
Note: 2.1 by default does not use libcurl anymore.
