### ISSUE TITLE
ZipFile.CreateFromDirectory(...) file locked after creation. File handle leak?

### ISSUE THREAD

**Issue by orthopteroid** [dotnet/corefx#18347]
Platform: Windows 7
Symptom: zipfiles I create are not available to be moved by the os after creation until the program ends.
Analysis: When ZipFile.CreateFromDirectory(...) calls ZipFileExtensions.DoCreateEntryFromFile(archive, ...) the ZipArchiveEntry is created with the following code (~line 220):

                ZipArchiveEntry entry = compressionLevel.HasValue
                                                ? destination.CreateEntry(entryName, compressionLevel.Value)
                                                : destination.CreateEntry(entryName);

But the ZipArchiveEntry that destination.CreatEntry(...) returns is an IDisposable object that is not wrapped with a (using ...) statement. Is this a handle leak?

Regards.

**Comment by stephentoub** [comment]
Can you share a repro?  This works fine for me:
```C#
using System;
using System.IO;
using System.IO.Compression;

class Program
{
    static void Main()
    {
        DirectoryInfo tmpDir = Directory.CreateDirectory(Guid.NewGuid().ToString("N"));
        File.Create(Path.Combine(tmpDir.FullName, "someFile1.txt")).Dispose();
        File.Create(Path.Combine(tmpDir.FullName, "someFile2.txt")).Dispose();

        string zipPath = tmpDir.FullName + ".1.zip";
        ZipFile.CreateFromDirectory(tmpDir.FullName, zipPath);
        File.Move(zipPath, zipPath.Replace(".1.zip", ".2.zip"));
    }
}
```
I've been able to rename/delete the created zip manually and programmatically immediate after CreateFromDirectory completes.

**Comment by orthopteroid** [comment]
Many thanks for your excellent example. I'm unable to share the code, but if I can cook my scenario up into something illustrative I'll repo it and reply here.

**Comment by stephentoub** [comment]
Ok, thanks. I'm going to close this for now.  Please reopen if you're able to share a repro we can use to verify what you're seeing and also to verify a fix if necessary.
