### ISSUE TITLE
Modules_GetMultipleTimes_ReturnsSameInstance test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#18352]
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/6248/consoleText
```
     System.Diagnostics.Tests.ProcessModuleTests.Modules_GetMultipleTimes_ReturnsSameInstance [FAIL]
        System.ComponentModel.Win32Exception : Only part of a ReadProcessMemory or WriteProcessMemory request was completed
        Stack Trace:
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(400,0): at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(294,0): at System.Diagnostics.NtProcessManager.GetModules(Int32 processId)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(107,0): at System.Diagnostics.ProcessManager.GetModules(Int32 processId)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs(312,0): at System.Diagnostics.Process.get_Modules()
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Diagnostics.Process\tests\ProcessModuleTests.cs(50,0): at System.Diagnostics.Tests.ProcessModuleTests.Modules_GetMultipleTimes_ReturnsSameInstance()
```
cc: @hughbe, @danmosemsft

**Comment by danmosemsft** [comment]
[EnumProcessModules ](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682631(v=vs.85).aspx) says `If this function is called from a 32-bit application running on WOW64, it can only enumerate the modules of a 32-bit process. If the process is a 64-bit process, this function fails and the last error code is ERROR_PARTIAL_COPY (299).`

The code attempts to prevent that case upstream of EnumProcessModules:
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessManager.Windows.cs#L336
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessManager.Windows.cs#L367

But the throw is line 400 which indicates EnumProcessModules was in fact called. So the question is why the upstream check didn't work.

[There is some suggestion ](http://stackoverflow.com/questions/10986486/c-sharp-only-part-of-a-readprocessmemory-or-writeprocessmemory-request-was-compl)that EnumProcessModulesEx does not have this problem, althoguh I see a comment on its MSDN page that it may.

No idea why this is new.

**Comment by hughbe** [comment]
This could be a race condition?
The current test is:

```cs
public class ProcessModuleTests : ProcessTestBase
{
    [Fact]
    public void Modules_GetMultipleTimes_ReturnsSameInstance()
    {
        Assert.Same(_process.Modules, _process.Modules);
    }
}
```

This accesses the inherited field `_process` that's shared with other tests.

Maybe this could work? This test has never failed for me on my PC so I can't check :/
```cs
[Fact]
public void Modules_GetMultipleTimes_ReturnsSameInstance()
{
    ProcessModuleCollection modules = Process.GetCurrentProcess().Modules;'
    Assert.Same(_process.Modules, _process.Modules);
}
```

There's a comment:
```
// Also, EnumProcessModules is not a reliable method to get the modules for a process. 
// If OS loader is touching module information, this method might fail and copy part of the data.
// This is no easy solution to this problem. The only reliable way to fix this is to 
// suspend all the threads in target process. Of course we don't want to do this in Process class.
 // So we just to try avoid the race by calling the same method 50 (an arbitrary number) times.
```

Could this be related? The key part is *copy part of the data*. The error message even says: *Only part of a ReadProcessMemory or WriteProcessMemory request was completed*

**Comment by stephentoub** [comment]
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/6276/
```
System.Diagnostics.Tests.ProcessModuleTests.Modules_GetMultipleTimes_ReturnsSameInstance [FAIL]
  downloaded dumpling.py
        System.ComponentModel.Win32Exception : Only part of a ReadProcessMemory or WriteProcessMemory request was completed
  downloaded analysis.py
  downloaded triage.ini
  total elapsed time 0:00:00.424000
        Stack Trace:
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(400,0): at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(294,0): at System.Diagnostics.NtProcessManager.GetModules(Int32 processId)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Diagnostics.Process\src\System\Diagnostics\ProcessManager.Windows.cs(107,0): at System.Diagnostics.ProcessManager.GetModules(Int32 processId)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs(312,0): at System.Diagnostics.Process.get_Modules()
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Diagnostics.Process\tests\ProcessModuleTests.cs(50,0): at System.Diagnostics.Tests.ProcessModuleTests.Modules_GetMultipleTimes_ReturnsSameInstance()
```

**Comment by stephentoub** [comment]
> This accesses the inherited field _process that's shared with other tests.

Every time an instance method test is executed, xunit instantiates a new test class, runs the instance method on that instance, and then disposes of the test class (if it's IDisposable).  So an instance field on the test class won't be shared between instance method tests.
