### ISSUE TITLE
System.Linq.Parallel Exceptions not consistent

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#1836]
The exceptions thrown (or wrapped) by PLINQ aren't consistent.

Enumerables throwing an exception during `GetEnumerator()` will expose the original exception, and won't wrap it in `AggregateException` (which at least a naïve reading of the documentation suggests it should), for everything but the following 'output' methods:
- `Average`
- `Count`
- `LongCount`
- `Max`
- `Min`
- `Sum`

... and `SequenceEqual`, but only when some other method is called first (eg, `new FailingEnumerable.AsParallel().Select(x => x).SequenceEquals(b)`).

If the enumerator itself throws an exception (from `MoveNext()` or `Current`), and additional PLINQ method is called first:
1. `SequenceEqual` throws nested `AggregateException`s
2. The following 'output' methods throw the original exception, and will not wrap it in an `AggregateException`:
   - `Aggregate(seed, accumulator)`
   - `Aggregate(seed, accumulator, resultSelector)`
   - `foreach(...)`
   - `ToArray`
   - `ToDictionary`
   - `ToList`

This is, at minimum, a 'gotcha' waiting to trip somebody up.  How should we handle it?
Interestingly, `SequenceEqual` has:

> // If first.GetEnumerator throws an exception, we don't want to wrap it with an AggregateException.
>    // If second.GetEnumerator throws an exception, we don't want to wrap it with an AggregateException.

... which I have a feeling was to deal with the case where an inner operator threw something already wrapped (to not nest it), but ended up missing the other cases.

<hr />

I've got a [Gist](https://gist.github.com/Clockwork-Muse/c10553dbce3de937aecd) of the tests I'm using to find this info, although I wasn't planning on adding them to the PLINQ tests in this form.  Especially because some stuff has been ad-hoc tweaked to be able to find the info better

**Comment by svick** [comment]
Wouldn't this break backward-compatibility? I.e. if someone catches `MyException`, but a new version throws `AggregateException`, their code will break. And vice versa.

**Comment by Clockwork-Muse** [comment]
If the exception is being thrown during `GetEnumerator()`, then yes, probably.  
If it's thrown during the other times, it depends on whether or not their current invocation calls an additional function first. Potential Heisenbugs here.
At minimum, behavior doesn't match documentation (and the pattern set up by the rest of the library).  

Out of curiosity, has anybody looked into distribution of times instantiating an enumerator throws an exception, versus using one?

**Comment by Clockwork-Muse** [comment]
An additional, related wrinkle here: cancellation isn't handled consistently either:

```
CancellationTokenSource cs = new CancellationTokenSource();
cs.cancel();

// Throws OperationCanceledException
new ThrowOnFirstEnumerationEnumerable().AsParallel().WithCancellation(cs.Token).First();

// Throws OperationCanceledException
ParallelEnumerable.Range(0, 10).WithCancellation(cs.Token).Zip(ParallelEnumerable.Range(0, 10), (x, y) => { throw new Exception(); } ).First();

// Throws AggregateException:
new ThrowOnFirstEnumerationEnumerable().AsParallel().WithCancellation(cs.Token).Zip(ParallelEnumerable.Range(0, 10), (x, y) => x).First();

// Throws AggregateException
ParallelEnumerable.Range(0, 10).WithCancellation(cs.Token).Select(x => { throw new Exception(); } ).Zip(ParallelEnumerable.Range(0, 10), (x, y) => x).First();
```
... the actual types and operations which trigger this varies a bit, but `Zip` seems to show up for most of them.

What's the expected "correct" result here?

**Comment by alexperovich** [comment]
@terrajobst Can we accept a breaking change like this?

**Comment by terrajobst** [comment]
We can generally make changes like this but:

1. We want to make .NET Framework and .NET Core consistent.
2. We don't want to break existing .NET Framework or .NET Core code. 

The way we do these things is via quirking. However, for changes with little to no benefit it's usually no worth it.  However, I don't have a good read on whether that's the case here or not.

@alexperovich, @stephentoub: thoughts?

/cc @karelz

**Comment by stephentoub** [comment]
> However, for changes with little to no benefit it's usually not worth it.

To me that feels like the case here.  Yes, consistency across the implementation is nice, but these are error conditions that have been like this for years, and changing it has a chance of breaking code while not providing significant benefit.

**Comment by terrajobst** [comment]
OK, that sounds to me we should close this.

@Clockwork-Muse, please let me know if there is something we didn't take into consideration.

**Comment by Clockwork-Muse** [comment]
@terrajobst - :shrug:  well, it's not like people should be aiming to hit these, and most of them would indicate programmer error anyways.
