### ISSUE TITLE
DataContractJsonSerializerTests.DCJS_VerifyDictionaryFormat test failed in CI

### ISSUE THREAD

**Issue by stone-li** [dotnet/corefx#18373]
DataContractJsonSerializerTests.DCJS_VerifyDictionaryFormat [FAIL]

### Message:
```
Test failed for input: System.Collections.Generic.Dictionary`2[TestClass,System.Object]
Expected: {"1,2#45":{"__type":"TestClass:#","floatNum":90,"intList":[4,5]},"6,7#10":{"__type":"TestStruct:#","value1":25}}
Actual:   {"1,2#45":{"floatNum":90,"intList":[4,5]},"6,7#10":{"value1":25}}
      
Expected: True
Actual:   False
```

### STACK TRACE:
at DataContractJsonSerializerTests.SerializeAndDeserialize[T](T value, String baseline, DataContractJsonSerializerSettings settings, Func`1 serializerFactory, Boolean skipStringCompare) in D:\j\workspace\windows_nt_re---37265eab\src\System.Runtime.Serialization.Json\tests\DataContractJsonSerializer.cs:line 2878 at DataContractJsonSerializerTests.DCJS_VerifyDictionaryFormat() in D:\j\workspace\windows_nt_re---37265eab\src\System.Runtime.Serialization.Json\tests\DataContractJsonSerializer.cs:line 2744

### Detail:
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/6197/testReport/junit/(root)/DataContractJsonSerializerTests/DCJS_VerifyDictionaryFormat_2/

**Comment by Jiayili1** [comment]
Another test failed with same issue: DataContractJsonSerializerTests.DCJS_VerifyDateTimeForFormatStringDCJsonSerSetting 

Message:

strings differ at index 13
                         ?
    [expected]:Date(1291190400000+0000)\\/\"
    [actual  ]:Date(1291161600000+0000)\\/\"
                         ?
    [Expected (with length=30)]:
    \"\\/Date(1291190400000+0000)\\/\"
    [Actual (with length=30)]:
    \"\\/Date(1291161600000+0000)\\/\"\r
    Test failed for input: 12/1/2010 12:00:00 AM\r
    Expected: \"\\/Date(1291190400000+0000)\\/\"\r
    Actual: \"\\/Date(1291161600000+0000)\\/\"\r
    Expected: True\r
    Actual:   False

        Stack Trace:

           at DataContractJsonSerializerTests.SerializeAndDeserialize[T](T value, String baseline, DataContractJsonSerializerSettings settings, Func`1 serializerFactory, Boolean skipStringCompare)
       at DataContractJsonSerializerTests.DCJS_VerifyDateTimeForFormatStringDCJsonSerSetting()

 Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170420.01/workItem/System.Runtime.Serialization.Json.ReflectionOnly.Tests/analysis/xunit/DataContractJsonSerializerTests~2FDCJS_VerifyDateTimeForFormatStringDCJsonSerSetting

**Comment by stone-li** [comment]
@Jiayili1 There is another issue #18538 to tracking the test fail
DataContractJsonSerializerTests.DCJS_VerifyDateTimeForFormatStringDCJsonSerSetting

**Comment by Jiayili1** [comment]
@stone-li thanks.

**Comment by Jiayili1** [comment]
Failed again here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_fedora24_debug/33/testReport/(root)/DataContractJsonSerializerTests/DCJS_VerifyDateTimeForFormatStringDCJsonSerSetting/

**Comment by shmao** [comment]
The test passed in the latest run. Closing the issue.

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_fedora24_debug/36/testReport/(root)/DataContractJsonSerializerTests/
