### ISSUE TITLE
Remove duplication of SHGetKnownFolderPath calls

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#18389]
The two different native calls in this file are actually identical. Remove the rigamarole around deciding which one to call

https://github.com/dotnet/corefx/blob/7422664ba77cac9c0a3cb1dcba79c854ca1b2db0/src/Common/src/Interop/Windows/shell32/Interop.SHGetKnownFolderPath.cs#L40

details
https://github.com/dotnet/corefx/pull/18383

**Comment by jguady** [comment]
Hi Dan, New contributor here. Probably still need to go through a lot of setup in order to test any changes. This sounds like a easy place to start though. It sounded like I can remove one (shellfolders) call and simplify SHGetKnownFolderPath to just the try/catch? Sound about right?

**Comment by danmosemsft** [comment]
Hi @jguady welcome. I think you just have to remove this function https://github.com/dotnet/corefx/blob/7422664ba77cac9c0a3cb1dcba79c854ca1b2db0/src/Common/src/Interop/Windows/shell32/Interop.SHGetKnownFolderPath.cs#L31 so calls go through directly.

**Comment by danmosemsft** [comment]
I sent you a collbaorator invite if you accept I can assign this.

**Comment by danmosemsft** [comment]
To get going, start here https://github.com/dotnet/corefx/wiki don't hesitate to @danmose me if you have q's.

**Comment by danmosemsft** [comment]
OK you're good to go.

**Comment by jguady** [comment]
Thanks Dan!
