### ISSUE TITLE
[Performance] Triage System.Collections performance regressions since v1.1

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#18390]
We've done an analysis of performance data from two builds of corefx: the released version of .NET Core 1.1, and a snapshot of corefx/master. The data is available through an internal website; contact me for information about how to access the info.

There are several regressions in test cases for System.Collections which we should investigate, triage, and potentially fix. The test cases which look reliable (i.e. they are not "random noise") are the following:

### `Dictionary<TKey, TValue>`

Test Name | Diff Time / Base Time
--------|-----------
Add(size: 1000) | 1.177
Add(size: 10000) | 1.314
ctor_int(size: 0) | 1.223
ctor_int(size:4096) | 1.287
Dictionary_ContainsKey_String_True(sampleLength: 100000) | 1.104
Dictionary_ContainsValue_Int_False(sampleLength: 1000) | 1.133
Dictionary_ContainsValue_Int_True(sampleLength: 1000) | 1.133
SetItem(size: 10000) | 1.145
Remove(initialSetSize: 8000000, countToRemove: 1) | 1.220
Union_NoOp(startSize: 32000, countToUnion: 320000) | 1.182

### `HashTable`

Test Name | Diff Time / Base Time
----------|----------------
Add(size: 1000) | **2.109 (!)**
Ctor_Empty | 1.143

### `List<T>`

Test Name | Diff Time / Base Time
----------- | ---------------
Add(size: 100000) | **2.011 (!)**
Clear(size: 10000) | **3.116 (!)**
GetCount(size: 10000) | 1.840
ctor | 1.129
GenericList_Reverse_String | 1.147
GetCount(size: 10000) | 1.840

**Comment by benaadams** [comment]
Hashtable.Add might be a simple one to isolate; its a big change and mostly just looks like its had attribute and dead path clear up; and resx used for exception

**Comment by danmosemsft** [comment]
@mellinoe could you please update this with the data you got from trying them locally?  Did you establish these were bogus?

**Comment by mellinoe** [comment]
I created some simple tests with BenchmarkDotNet and gathered some manual data on my local workstation for the worst offenders in the list above. After doing that, I was not able to see the same regressions that were indicated by this one-off data. Our view is that this data is not reliable enough to spend tons of time analyzing, and that the best way to move forward is to improve the test coverage we have (which is very lacking), and to improve our processes around data collection and monitoring.
