### ISSUE TITLE
On Linux systems: System.Diagnostics.FileVersionInfo.GetVersionInfo() hangs process/thread when used on named pipe files

### ISSUE THREAD

**Issue by PaulHigin** [dotnet/corefx#18409]
Repro
1. On Linux Ubuntu 16.04 install PowerShell from GitHub (https://github.com/powershell/powershell)
```
uname -a
Linux paul-UbuntuA 4.8.0-46-generic #49~16.04.1-Ubuntu SMP Fri Mar 31 14:51:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
2. Install VSCode as well because it creates named pipe files needed to repro.
3. On PowerShell command line type the following (replace named pipe file name with actual file in /tmp)
```powershell
[System.Diagnostics.FileVersionInfo]::GetVersionInfo('/tmp/clr-debug-pipe-12555-7925167-in')
```

Result
PowerShell process/thread hangs.  No exception is thrown.

Discussion
This appears to only happen with named pipe files.  I don't see the hang when passing in other file paths.
This breaks PowerShell remoting when enumerating directories containing named pipe files because PowerShell remoting returns serialized FileInfo objects which includes custom object members that evaluates FileVersionInfo.GetVersionInfo() with the file path. 
See issue (https://github.com/PowerShell/PowerShell/issues/1866)

**Comment by PaulHigin** [comment]
@stephentoub Thanks for addressing this so quickly.

**Comment by stephentoub** [comment]
Thanks for reporting it :smile:
