### ISSUE TITLE
Document API platform differences

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#18405]
We need to document API differences:
1. Between .NET platforms -- .NET Framework vs. .NET Core vs. .NET Native vs. Xamarin/Mono, and
2. Between OS's -- Windows vs. Linux vs. Mac

The documentation should be exposed as [platform-compat tooling](https://github.com/terrajobst/platform-compat) and also as standalone HTML.

**Comment by karelz** [comment]
Update also [porting.md - AppDomains](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/porting.md#app-domains) with link to differences.

**Comment by tarekgh** [comment]
@karelz do you think this can be done in v2.0 time frame? I think this will need sometime to cover such differences

**Comment by karelz** [comment]
This should happen in 2.0 timeframe - it is part of the platform end-to-end. It might be exemption to ZBB on 5/10 though.

**Comment by karelz** [comment]
BTW: The content/list of differences is now being collected here: https://github.com/dotnet/corefx/wiki/ApiCompat

**Comment by ViktorHofer** [comment]
@karelz ZBB label maybe?

**Comment by karelz** [comment]
Yep, good catch. Thanks @ViktorHofer!

**Comment by tarekgh** [comment]
@karelz are you following in this? will be able to close it before the end of the week?

**Comment by karelz** [comment]
I will follow up. Documentation changes can happen after Escrow ;) as they don't require code change.

**Comment by karelz** [comment]
The tooling was released as preview via nuget: https://blogs.msdn.microsoft.com/dotnet/2017/10/31/introducing-api-analyzer/

Source code is here: https://github.com/dotnet/platform-compat
