### ISSUE TITLE
Document upload-tests.proj

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#18400]
Reminder issue to write a markdown file detailing how to use upload-tests.proj.

**Comment by wtgodbe** [comment]
@MattGal @safern is this still needed?

**Comment by MattGal** [comment]
I had totally forgotten creating this issue;  I think enough folks have been able to use it without more docs that it doesn't matter, also you'll be exclusively using https://github.com/dotnet/corefx/blob/master/eng/sendtohelix.proj soon so I'll go ahead and close it.
