### ISSUE TITLE
What's the motivation for SkipOnTargetFrameworkAttribute in tests?

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/corefx#18401]
The closed source .NET ToF test tree had a concept of *capabilities* that could be mapped to a set of *target runtimes*.

What you could do with that was to say a test *requires* a capability and a *target runtime* could say that it *provides a capability*.

When you had a test (such as e.g. a test exercising Rank 1 multidimensional arrays), you could say that the test is only applicable to runtimes that support Rank 1 multidimensional arrays.

When a runtime added support for a capability, you would only need to update the list of it's capabilities, and all applicable tests would magically start running.

Conversely, if a new target runtime was added, you only had to specify a list of it's capabilities and all the applicable tests would start running instead of having to dig through failures and trying to understand them.

`SkipOnTargetFrameworkAttribute` seems to be inferior to the capabilities concept in every possible way: now you need to enumerate every possible runtime that the test is not supported on in the test itself. When the runtime learns that new feature, you better make sure and go over all the tests that were blocked for that particular runtime to make sure you're actually getting the test coverage you would expect for the new feature.

**Comment by ViktorHofer** [comment]
We are not going to change this anytime soon. Let's close this and reopen if we feel a strong necessity to switch to a capability mechanism.
