### ISSUE TITLE
Performance tests with empty loops

### ISSUE THREAD

**Issue by billwert** [dotnet/corefx#18416]
While doing some other work I noticed a handful of the System.Runtime performance tests that end up having their test optimized away by the JIT on amd64 release builds. 

Both tests here: [Perf.Object.cs](https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/Performance/Perf.Object.cs)
Both tests here: [Perf.IntPtr.cs](https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/Performance/Perf.IntPtr.cs)
[Perf_String.GetLength](https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/Performance/Perf.String.cs#L135)

These all jit to a pattern like this:
```
       E823E5FFFF           call     BenchmarkIteration:StartMeasurement():struct:this
       90                   nop

G_M28236_IG05:
       33C9                 xor      ecx, ecx

G_M28236_IG06:
       FFC1                 inc      ecx
       81F910270000         cmp      ecx, 0x2710
       7CF6                 jl       SHORT G_M28236_IG06
```

In general a strategy for working around issues like this is to assign the result to a field of the enclosing type. I did this as a quick experiment locally and it produces a better result. In most cases however these tests are still well optimized by the JIT. For example, this is the "fixed" JIT output for the ```IntPtr(0)``` constructor case:
```
       E89EDEFFFF           call     BenchmarkIteration:StartMeasurement():struct:this
       90                   nop

G_M39768_IG05:
       33C9                 xor      ecx, ecx

G_M39768_IG06:
       33D2                 xor      rdx, rdx
       48895618             mov      qword ptr [rsi+24], rdx
       48895618             mov      qword ptr [rsi+24], rdx
       48895618             mov      qword ptr [rsi+24], rdx
       48895618             mov      qword ptr [rsi+24], rdx
       48895618             mov      qword ptr [rsi+24], rdx
       48895618             mov      qword ptr [rsi+24], rdx
       48895618             mov      qword ptr [rsi+24], rdx
       48895618             mov      qword ptr [rsi+24], rdx
       48895618             mov      qword ptr [rsi+24], rdx
       FFC1                 inc      ecx
       81F910270000         cmp      ecx, 0x2710
       7CD0                 jl       SHORT G_M39768_IG06
```

It's not clear that's a particularly valuable test.

cc @ianhays as you seem to have written (or at least checked these in originally.) I didn't have a sophisticated parser or anything to find these; I just dumped the jitdisasm and looked for the inc/cmp/jl pattern by hand for these tests.

**Comment by benaadams** [comment]
Is it but that it doesn't optimize all but one mov away in second output?

**Comment by pgavlin** [comment]
cc @dotnet/jit-contrib re: the empty loops.

**Comment by mellinoe** [comment]
I suspect this is a common problem with the tests for many of our "primitive types" (using a loose definition). Types that just store state or perform some computations (rather than touch the disk, create a socket, perform interop, etc.) seem prone to this problem. Especially if they aren't persisting those results into a field or something. We just recently re-wrote most of the `Vector2/3/4` tests because the JIT was able to eliminate all of the computations being done.

Is there an easy way to detect when this is happening, or starts to happen? Obviously we can just analyze trends in the test's duration, but would a different metric ("instructions retired"?) help identify these problems more easily?

**Comment by billwert** [comment]
@mellinoe The easiest way, probably, is to add a test that is an empty for loop and see what other tests hit the same time/iteration and investigate them by hand. 

One could also imagine just JIT dumping all of the tests and grepping for the bad pattern.

**Comment by AndyAyersMS** [comment]
Would be nice to standardize across CoreCLR/CoreFX on a canonical and not-very-expensive way of consuming results that the jit can't see through.

Common examples over in CoreCLR perf tests are passing the value to a noinline method, storing it to a volatile static, or conditionally storing it to some object field where the jit can't know the condition and where at runtime the condition always evaluates false.

None of these are free but if the goal of the test is mainly is regression prevention they may be cheap enough to keep the thing you're trying to measure the predominant contributor to loop cost.

**Comment by mellinoe** [comment]
> Would be nice to standardize across CoreCLR/CoreFX on a canonical and not-very-expensive way of consuming results that the jit can't see through.

Yeah, it would be good to just have "standard guidance" on what to do as we write new tests, and fix up old ones. Maybe a helper library / class with obvious functions to call? A non-inlineable `PerfHelpers.PreserveResult<T>(T)` method, which does whatever we need it to do?

**Comment by benaadams** [comment]
> A non-inlineable PerfHelpers.PreserveResult<T>(T) method, which does whatever we need it to do?

Wouldn't invoking a `Func<T>` or `Action` variable do this?

**Comment by mellinoe** [comment]
Yeah, I think there's multiple ways we could do it. I'd just like for it to be simple and obvious, so we have something easy to point to when folks start writing new tests.

**Comment by AndyAyersMS** [comment]
@JosephTremoulet any ideas?

**Comment by JosephTremoulet** [comment]
My go-to pattern for this is volatile stores; AFAIK it's really the only thing that unambiguously tells the compiler that it must compute the value in question, so it will best hold up against future optimization improvements (e.g., passing the value to a noinline method would get defeated by analyzing the callee to see if it uses parameters and passing garbage values for unused ones, storing under an always-false condition would get defeated by moving the computation down under the conditional, etc.).  You can't volatile-store a struct, so if the thing being computed is a struct my default is to compute some scalar aggregation (like sum the fields) and store that to a volatile.  The main downside to volatile stores is that the optimizer can be shy about optimizing across them (this is why I avoided them in dotnet/coreclr#10216, for example, where we explicitly wanted to test optimizations across loop iterations like hoisting invariants), but if the volatile store is at the end of the sequence you're trying to measure and you don't want optimizations across iterations of whatever loop it may be in, I think it's a pretty safe way to go.

Another good option is returning the computed value (from a `NoInlining` method), but if you have a loop that you want to do the computation repeatedly that opens you to the risk of the optimizer nixing the loop and just doing the computation once (in theory -- it's certainly not something we're doing today).

Speaking of loops, this thread has been discussing finding a good non-elidable way to consume a value computed by a micro-benchmark, but if you are putting the computation in a loop you may need to make sure it's not invariant across iterations of the loop.  E.g. if you wanted to see how fast we add, and wrote

```c#
volatile static int sink;

[MethodImpl(MethodImplOptions.NoInlining)]
void TestAdd(int x, int y) {
  for (int i = 0; i < Iterations; ++i) {
    sink = x + y;
  }
}
```

then we'd (hopefully) do the add once and just copy the sum to `sink` on each iteration.  Making the input a function of the loop counter is a good way to go here, though again if you're trying to measure a really short sequence it can be tricky to find an appropriately cheap expression.

**Comment by stephentoub** [comment]
@adamsitnik, can this be closed?

**Comment by adamsitnik** [comment]
@stephentoub yes, this issue was solved when I ported benchmarks to BenchmarkDotNet

btw BenchmarkDotNet solves it in a way that it introduces it's own loop, consumes the returned result using [Consumer](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Engines/Consumer.cs) and moreover wraps the call to the benchmark with delegate (so it can not be inlined). If the benchmarked method gets optimized to const or simply empty method, BDN shows `0ns` in the results and produces a warning that explains it.

https://github.com/dotnet/performance/blob/2ad613b3853b99f33d632eb93e1f5cbe0f5aeb50/src/benchmarks/micro/corefx/System.Runtime/Perf.Object.cs#L15-L19

https://github.com/dotnet/performance/blob/2ad613b3853b99f33d632eb93e1f5cbe0f5aeb50/src/benchmarks/micro/corefx/System.Runtime/Perf.IntPtr.cs#L16-L20
