### ISSUE TITLE
ConcurrentDictionary throws for null comparer, unlike every other BCL API

### ISSUE THREAD

**Issue by jnm2** [dotnet/corefx#18432]
You would expect this to succeed:
```c#
new ConcurrentDictionary<object, object>((IEqualityComparer<object>)null)
```

I'll quite often take advantage of the fact that all BCL APIs use `EqualityComparer<T>.Default`  when you pass null, and chain constructors and other methods with the parameter `IEqualityComparer<T> comparer = null`.

I haven't found any other API that throws. Here are some that do not throw:

- `Dictionary`
- `HashSet`
- `ImmutableDictionary`
- `ImmutableHashSet`
- `ImmutableSortedDictionary`
- `ImmutableSortedSet`
- `KeyedCollection`
- `SortedDictionary`
- `SortedList`
- `SortedSet`
- `Array.BinarySearch`
- `Array.Sort`
- `List<>.BinarySearch`
- `List<>.Sort`
- `IEnumerable<>.Contains`
- `IEnumerable<>.Distinct`
- `IEnumerable<>.Except`
- `IEnumerable<>.GroupBy`
- `IEnumerable<>.GroupJoin`
- `IEnumerable<>.Intersect`
- `IEnumerable<>.Join`
- `IEnumerable<>.OrderBy`
- `IEnumerable<>.OrderByDescending`
- `IEnumerable<>.SequenceEqual`
- `IEnumerable<>.ThenBy`
- `IEnumerable<>.ThenByDescending`
- `IEnumerable<>.ToDictionary`
- `IEnumerable<>.ToImmutableDictionary`
- `IEnumerable<>.ToImmutableHashSet`
- `IEnumerable<>.ToImmutableSortedDictionary`
- `IEnumerable<>.ToImmutableSortedSet`
- `IEnumerable<>.ToLookup`
- `IEnumerable<>.Union`

**Comment by danmosemsft** [comment]
@AArnott

**Comment by jnm2** [comment]
Ah, found one more that throws! All arities of `Tuple` throw when you call `IStructuralEquatable.Equals` with null comparer. By comparison, Array acts like the rest of the BCL when you call `IStructuralEquatable.Equals`.

**Comment by AArnott** [comment]
Thanks for the report, @jnm2. I suspect we could take a PR that fixes this. But by my own measure this seems like a very low priority bug, because:

1. There is no interface contract for collection constructors requiring that they behave alike
1. The throwing path of supplying `(IEqualityComparer<object>)null` as the argument seems harder than the working path of specifying no argument at all, or `EqualityComparer<T>.Default`. 

Is there anything that I'm missing that would suggest this is more critical?

**Comment by jnm2** [comment]
As for 2, that's not the case when layering or chaining APIs. If my own constructor or extension method takes `IEqualityComparer<T> comparer = null`, I assume that I can pass that into the BCL method. If we're talking about more work, it's actually more work to check for null and pass `EqualityComparer<T>.Default` *or* call one or the other overload depending whether `comparer = null`.

It's not critical since the workaround is to pass `comparer ?? EqualityComparer<T>.Default` instead of `comparer`. This is an API gotcha that may go unnoticed until dependent code is shipped though.

I'd be happy to do a PR.

**Comment by jnm2** [comment]
@AArnott I see I didn't properly test [`Array.IStructuralEquatable.Equals`][1] and [`Array.IStructuralComparable.CompareTo`][2]. Apparently they have no null comparer check and will attempt to dereference null. They are in coreclr. Should I open an issue over there?

 [1]: (https://github.com/dotnet/coreclr/blob/e0b8c96334016770680d64fc83a8e7dbdeb657ee/src/mscorlib/src/System/Array.cs#L669-L696)
 [2]: https://github.com/dotnet/coreclr/blob/e0b8c96334016770680d64fc83a8e7dbdeb657ee/src/mscorlib/src/System/Array.cs#L698-L731

**Comment by jnm2** [comment]
[`Tuple<*>.IStructuralComparable.CompareTo`][3] and [`Tuple<*>.IStructuralEquatable.Equals`][4], same story.

 [3]: https://github.com/dotnet/coreclr/blob/e0b8c96334016770680d64fc83a8e7dbdeb657ee/src/mscorlib/src/System/Tuple.cs#L124-L136
 [4]: https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Tuple.cs#L143-L155

**Comment by jnm2** [comment]
[`ValueTuple<*>.IStructuralEquatable.Equals`][5] and [`ValueTuple<*>.IStructuralComparable.CompareTo`][6] have the same thing, however they are in this repo.

 [5]: https://github.com/dotnet/corefx/blob/124944c13686fd83b2cdaa01e7e94e629c4472f3/src/System.ValueTuple/src/System/ValueTuple/ValueTuple.cs#L335-L342
 [6]: https://github.com/dotnet/corefx/blob/124944c13686fd83b2cdaa01e7e94e629c4472f3/src/System.ValueTuple/src/System/ValueTuple/ValueTuple.cs#L371-L382

**Comment by AArnott** [comment]
I hate null-refs. But as they are all "structural", I wonder if there's a perf reason that they skip the check. I know we skip the check intentionally in the `ImmutableArray<T>` struct. @stephentoub may know.

**Comment by jnm2** [comment]
@stephentoub I'd like to follow with a fix for the [`IStructural*` implementations](https://github.com/dotnet/corefx/issues/18432#issuecomment-294326098) to being their behavior in line with the rest of the BCL, if you see no reason they should stay inconsistent.

**Comment by safern** [comment]
@jnm2 could you open a separate issue for those and we can discuss it over there?

**Comment by jnm2** [comment]
Sure thing. https://github.com/dotnet/corefx/issues/18528
