### ISSUE TITLE
HttpClient: Impossible to send "Accept: a;charset=b"

### ISSUE THREAD

**Issue by zugzwangm** [dotnet/corefx#18449]
I want to make a http request with a header `"Accept"` with value `"a;charset=b"`.
It is **impossible** to do that with **HttpClient**.

```c#
using (var client = new HttpClient())
{
	client.DefaultRequestHeaders.TryAddWithoutValidation("Accept", "a;charset=b");
	// ...
}
```

This will generate a request with header `"Accept"` with value `"a; charset=b"`.
Yes, this extra space is obviously valid, but the original value was also valid. And there are APIs out there that won't work with the extra space.

The only way to make it work is to _hack_ it with reflection:
```c#
client.DefaultRequestHeaders.TryAddWithoutValidation("Accept", "foo");
foreach (var v in client.DefaultRequestHeaders.Accept)
{
	if (v.MediaType.Contains("foo"))
	{
		var field = v.GetType().GetTypeInfo().BaseType.GetField("_mediaType", BindingFlags.NonPublic | BindingFlags.Instance);
		field.SetValue(v, "a;charset=b"); // avoid MediaType's validation
		v.CharSet = "";					
	}
}
```

Sugestion:
```c#
client.DefaultRequestHeaders.AddHeaderAndDontMessWithItDontChangeItDontParseItIWantTotalControlThankYouVeryMuch("Whatever header I want", "Whatever value I want");
```

**Comment by geoffkizer** [comment]
I don't understand why we don't send the original, unmodified header in cases like this.  @davidsh @cipop do you guys know?

**Comment by CIPop** [comment]
@geoffkizer Some parser (WinHTTP?) appears to do normalization. Interestingly the [RFC ABNF production](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) doesn't include a space yet some of the RFC examples do.

@zugzwangm Do you see the same behavior in .Net Desktop?

> And there are APIs out there that won't work with the extra space. 

If any of the ones you know are public, could you give a few examples please?

**Comment by davidsh** [comment]
>I don't understand why we don't send the original, unmodified header in cases like this. @davidsh @cipop do you guys know?

@geoffkizer In general, most HTTP stacks will try to normalize the headers when we send on the wire and that includes things like adjusting spaces as per the RFC rules of *should* and *must* things. The rule in networking is to be "strict in what we send" and "flexible in what we receive/parse". So, the tendency is to do things like this (add the space, etc.).

**Comment by davidsh** [comment]
Setting milestone

**Comment by devandanger** [comment]
I was more recently affected this, working with the vendor on their side to see if they can correct the logic to better conform with the RFS standard.  Currently getting the error on their side 'Unable to extract version number from content type'.

Curious what the process of fixing this and it making it into the mono repo is.  Any links which can better explain that flow would be great.  Thanks!

**Comment by DanRigby** [comment]
It would appear that .NET Framework doesn't share this behavior if this SO answer is correct: https://stackoverflow.com/a/40162071/53777

Some level of control over this normalization behavior would be helpful in working with non standards compliant host systems.

**Comment by karelz** [comment]
@DanRigby too many options affects usability and often makes the implementation more complex - so you pay by having more bugs, regressions and higher maintenance cost.
I may be fine if we adjust behavior and if we are more benevolent. I am not huge fan of adding more knobs to control things.

**Comment by JCKodel** [comment]
```
using(var x = new HttpRequestMessage())
{
	x.Headers.TryAddWithoutValidation("Accept", "application/json;something-weird-here");
}
```

It would make sense that `TryAddWithoutValidation` would not validate and/or normalize the header.
BTW, an example of this error can be seen in https://moip.com.br/en/ (an online payment gateway requires `Accept: application/json;version=2.1`. One space after `;` it won't recognize the version 2.1 (and will send an old response). 

I know this is a Moip problem (how hard is to follow RFC rules, after all?), but, we, as the "most amazing programming technology, like ever"™ users, must have the option to satisfy those Java... people =P

**Comment by karelz** [comment]
@JCKodel thanks for the real-world example, that is very helpful.
Do you happen to know what Moip uses under the hood? Is it problem in their code or in the server they use?
If it is problem in the server, then we can expect more instances and the priority of this API would be higher.

**Comment by felipeOliveira** [comment]
https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.Net.Http/src/System/Net/Http/Headers/NameValueHeaderValue.cs

![image](https://user-images.githubusercontent.com/2717505/44807670-820ff100-aba0-11e8-9a92-86a9b784bd57.png)

There is already support for leaving that space out, but no way to access it. `TryAddWithoutValidation` should pass true to the `leadingSeparator` argument.

As a workaround, reflection FTW:
```
foreach (var v in request.Headers.Accept)
{
    if (v.MediaType.Contains("application/json"))
    {
        var field = v.GetType().GetTypeInfo().BaseType.GetField("_mediaType", BindingFlags.NonPublic | BindingFlags.Instance);
        field.SetValue(v, "application/json;version=2.1");
        v.Parameters.Clear();
    }
}
```

**Comment by karelz** [comment]
@felipeOliveira the fact that something is technically possible is not a justification for adding new APIs. If we followed that, .NET API surface would be a GIANT mess today.
That said, @JCKodel's information is something that can support API addition.

Also, please remove your reflection code snippet - we do not want encourage anyone to use private reflection. That is unsupported hackary that leads to compat problems down the road when the underlying implementation changes. Thanks!
If anyone uses code like that, it should be with HUGE comment saying "UNSUPPORTED, IT MAY BREAK AT ANY TIME WITHOUT WARNING".

**Comment by mustakimali** [comment]
I hit the issue today. As I don't have any control over that non-conforming REST API I'm consuming - I have little option but to use the reflection method for now 😢

**Comment by MarcoRossignoli** [comment]
> The rule in networking is to be "strict in what we send" and "flexible in what we receive/parse". So, the tendency is to do things like this (add the space, etc.).

Maybe an overload on `TryAddWithoutValidation` like `skipNormalization`

**Comment by rmkerr** [comment]
This actually appears to be fixed in .NET Core 2.1. Capturing the request the request from the original report in fiddler, it appears that no space was added:
```
GET http://microsoft.com/ HTTP/1.1
Accept: a;charset=b
Host: microsoft.com
Connection: Keep-Alive
```

I'm not sure of the exact change that fixed this issue, but it was probably related to the switch from WinHttpHandler to SocketsHttpHandler for our underlying HTTP implementation.

I'm going to close this issue as fixed. If I missed something and there is still an active issue here, feel free to reopen it :)

**Comment by joseftw** [comment]
This appear to still by an issue, see below for repro and fiddler response.
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23
```

```
class Program
    {
        static async Task Main(string[] args)
        {
            var httpClient = new HttpClient();
            var request = new HttpRequestMessage(HttpMethod.Get, "http://localhost:5555");
            var acceptValue = "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3";
            request.Headers.Add("whatever", acceptValue);
            request.Headers.TryAddWithoutValidation("Accept", "application/json;something-weird-here");

            var result = await httpClient.SendAsync(request);
        }
    }
```

The above code produces the following result in Fiddler (notice the spacing in the Accept header but not in the ```whatever``` header):

```
GET http://localhost:5555/ HTTP/1.1
whatever: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept: text/html, application/xhtml+xml, application/xml; q=0.9, image/webp, image/apng, */*; q=0.8, application/signed-exchange; v=b3
Host: localhost:5555
```

**Comment by parxal** [comment]
Hi @rmkerr this still happens in version 2.2

**Comment by davidsh** [comment]
>Hi @rmkerr this still happens in version 2.2 . Any idea to override this? i am having a problem with a server that don't accept a white space after the ;

@rmkerr is not on .NET Core project anymore.

If you are still having a problem, please open a new issue. And please include enough information in order for us to reproduce the problem. Please include a run-able repro program.  Thx.

**Comment by parxal** [comment]
@davidsh open it here > https://github.com/dotnet/corefx/issues/39260
