### ISSUE TITLE
Support System.Net.Security.NegotiateStream

### ISSUE THREAD

**Issue by roncain** [dotnet/corefx#1844]
Add support for NegotiateStream that exists in the full .NET Framework. This involves either creating a new library or a newer version of an existing one.  As a minimum it should support the same client API surface as the full .NET Framework.  This is required for WCF to complete its NetTcpBinding implementation.

**Comment by joshfree** [comment]
@davidsh @CIPop @SidharthNabar @vijaykota

**Comment by CIPop** [comment]
Phase 1 complete: Added the contract and a temporary PlatformNotSupported implementation (will soon be added via @dotnet-bot automatic sync).

**Comment by SidharthNabar** [comment]
The implementation for NegotiateStream will likely not come in before RC. Till then, we will have a skeleton API surface which throws PlatformNotSupportedException, so that dependent libraries can build successfully in .NET Core.
