### ISSUE TITLE
HttpWebRequest KeepAlive correctness

### ISSUE THREAD

**Issue by shravan2x** [dotnet/corefx#18448]
This issue refers to the code [here](https://github.com/dotnet/corefx/blob/master/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs#L387).

Is this a valid HTTP header?

```c#
public bool KeepAlive
{
    get
    {
        return _webHeaderCollection[HttpKnownHeaderNames.KeepAlive] == bool.TrueString;
    }
    set
    {
        if (value)
        {
            SetSpecialHeaders(HttpKnownHeaderNames.KeepAlive, bool.TrueString);
        }
        else
        {
            SetSpecialHeaders(HttpKnownHeaderNames.KeepAlive, bool.FalseString);
        }
    }
} 
```

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive suggests that this should never be a true or false value. Shouldn't we be setting `Connection: keep-alive` instead?

**Comment by Priya91** [comment]
@shravan2x Connection is a different header on HttpWebRequest, it has it's own API. Although the Keep-Alive header value should be timeout=, max=. @davidsh why do we have a bool value for this Keep-Alive general header?

**Comment by shravan2x** [comment]
@Priya91 I completely agree. However, the traditional `HttpWebRequest` set the `Connection` header even when `KeepAlive = true;` was set (It used an internal `m_KeepAlive` boolean field). You can see this in the reference source [here](http://referencesource.microsoft.com/#q=httpwebrequest).

**Comment by davidsh** [comment]
>@shravan2x Connection is a different header on HttpWebRequest, it has it's own API. Although the Keep-Alive header value should be timeout=, max=. @davidsh why do we have a bool value for this Keep-Alive general header?

Have you observed what changing that property does on the wire itself? I'll need to research this on how it originally behaved in .NET Framework.  But I think this "header" isn't really transmitted as an HTTP header. But rather this property is used internally in this collection to change what is transmitted on the wire in terms of the real HTTP headers.

Did you observe any Fiddler or other trace output that shows we are actually transmitting an illegal HTTP header?  Or is your issue here just due to code inspection itself?

**Comment by davidsh** [comment]
I just researched this issue more. It does appear that the porting of this property from .NET Framework to .NET Core was done incorrectly.

The reference source:
https://github.com/Microsoft/referencesource/blob/master/System/net/System/Net/HttpWebRequest.cs#L449

shows this:

```c#
        public bool KeepAlive {
            get {
                return m_KeepAlive;
            }
            set {
                m_KeepAlive = value;
            }
        }
```

So, setting this property in .NET Framework only sets an internal field.  Later, this internal field is used by _Connection.cs:
https://github.com/Microsoft/referencesource/blob/master/System/net/System/Net/_Connection.cs

which results in actually using the appropriate HTTP header.

So, this is a bug in the .NET Core implementation.

**Comment by davidsh** [comment]
cc: @stephentoub @CIPop @karelz

**Comment by davidsh** [comment]
Looks like this bug was introduced with this PR https://github.com/dotnet/corefx/pull/12347 back in October. And unfortunately, we didn't catch it during code review.

cc: @tijoytom

**Comment by karelz** [comment]
Given this is new API and difference from Desktop, we should address it before shipping. Moving it to 2.0.

@davidsh do you know how costly is the fix? (one-liner vs. couple of days vs. more?) ... adding it to our "costing" OneNote

**Comment by davidsh** [comment]
>@davidsh do you know how costly is the fix? (one-liner vs. couple of days vs. more?) ... adding it to our "costing" OneNote

@stephentoub is working on this already with a PR

**Comment by karelz** [comment]
Great
