### ISSUE TITLE
.Net "PAL" version of MMAP flags differs most Linux

### ISSUE THREAD

**Issue by Drawaes** [dotnet/corefx#18454]
This code is used to define the flags for the MMAP command. It goes to the PAL which then remaps the ANON flag to the distro's version. 

As far as I can tell it is 0x20 on all the headers I can find. Seems confusing that this const would be mapped differently for use in .net, and makes it somewhat incompatible for no upside, unless I am missing something?

FYI 0x10 means static, or you need to use the pointer I passed in.

  // shared/private are mutually exclusive
    PAL_MAP_SHARED = 0x01,  // shared mapping
    PAL_MAP_PRIVATE = 0x02, // private copy-on-write-mapping
    PAL_MAP_ANONYMOUS = 0x10, // mapping is not backed by any file

**Comment by stephentoub** [comment]
> As far as I can tell it is 0x20 on all the headers I can find

We need to consider more than just Linux. It's 0x1000 on macOS, for example.

**Comment by Drawaes** [comment]
Yes but on macOS 0x10 is still Fixed.

**Comment by stephentoub** [comment]
I don't understand what the concern is. Some values differ, so we need a mapping, at which point it really doesn't matter what calls we pick for the .NET side and whether they do or don't map to the same values on some of the platforms.

**Comment by Drawaes** [comment]
I guess the issue I have is that, there is a POSIX standard for 0x10, that you have reused. I understand that you are not bound by that the PAL level,  but still. 

The reason for the differing in the MAP_ANONYMOUS is that it isn't POSIX defined. But seeing as your method has the same name, same params as the POSIX implementation, you would think the flags would map as close as possible.

**Comment by stephentoub** [comment]
> there is a POSIX standard

Can you point me to the POSIX specification where these numerical values are defined? (Not to the header files for a particular OS/distribution/version.)

> I understand that you are not bound by that the PAL level, but still

But still what? It's an internal implementation detail: all that matters is that the two sides of this, both private to our implementation, match, and they do. Could we have selected different values? Sure. I see no value in changing it at this point, though.

**Comment by Drawaes** [comment]
There is no "numerical" standard for fixed. I mean that Fixed is defined in the Posix standard, which is why it seems to be fixed in every header I can find (BSD, a few flavours of linux and OSX). 

My issue came that I was using your PAL, because I can't use your "managed" version because it is all marked internal. Thus it lead to confusion that the PAL layer was taking "Fixed" for Anon.

You can leave it how it is, however when doing some things not covered by the managed part directly before I have been steered towards using your PALs rather than making a new one, or PInvoke directly due to potential ABI issues that your PAL's take care of. 

That said, now I know I can work with it, close the issue if you want.

**Comment by stephentoub** [comment]
> I have been steered towards using your PALs rather than making a new one

We shouldn't be encouraging that. It's akin to encouraging folks to rely on private methods via reflection, and as with that, we could easily and accidentally end up breaking code with such an unexpected dependency. I realize we have a gap in that we've not made it easy to access the large number of libc APIs directly; that should be addressed soon I hope.

**Comment by Drawaes** [comment]
I would agree that is root cause.

**Comment by stephentoub** [comment]
Thanks.

**Comment by karelz** [comment]
@stephentoub do you expect the libc APIs to be exposed with the POSIX work or did you mean something else?

cc @janvorli

**Comment by stephentoub** [comment]
@karelz, https://github.com/dotnet/corefx/issues/15289

**Comment by karelz** [comment]
Yep, thanks! That's the one I had in my mind ... cc @eerhardt

**Comment by Drawaes** [comment]
Explicitly excludes mmap :(

**Comment by Drawaes** [comment]
Also is it even worth starting a public API on this until native int  etc has shaken out?

**Comment by karelz** [comment]
How is native int related to this?
