### ISSUE TITLE
ConcurrentQueue IsEmpty too slow?

### ISSUE THREAD

**Issue by SunnyWar** [dotnet/corefx#18464]
I have some hot-path production code that looks like this. The queue is _usually empty_.
`if(!myConcurrentQueue.IsEmpty)
{
     WorkItem item;
     if(myConcurrentQueue.TryDequeue(out item))
     {
          DoWork(item);
     }
}`

Clearly the assumption is that IsEmpty is a faster than calling TryDequeue. I decided to test this assumption with writing a little microbenchmark the compares IsEmpty versus TryDequeue on an empty queue..

I was surprised to find the IsEmpty appears to take about _twice a long_ as TryDequeue. Given that to dequeue anything there is probably a check to find out if there is anything in the queue, there's no reason I can think of for IsEmpty to be slower.

**Comment by stephentoub** [comment]
Can you share your microbenchmark? What version are you testing?  I just tried it on the latest bits in master and I see IsEmpty being ~25% faster than TryDequeue on an empty queue.

**Comment by karelz** [comment]
FYI: [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet) is good for writing and measuring tests.

**Comment by SunnyWar** [comment]
@stephentoub I'm using 4.6.2 as 4.7 doesn't (yet) show up as an option. I'll try BenchmarkDotNet out and see what I get.

**Comment by SunnyWar** [comment]
I'm an idiot. Even though poured over the code several time to make sure my conclusions were accurate I missed the fact I called .Start() on the stopwatch variable instead calling .Restart(). Now I'm seeing the 25% improvement that @stephentoub mentioned.

closing.

**Comment by karelz** [comment]
@SunnyWar that happens. That + measuring without warmup (i.e. incluing JIT time), doing statistics over number of iterations, etc. -- all that is exactly the reason why little benchmark wrappers like DotNetBenchmark (or MeasureIt in the past) are useful ;-).
