### ISSUE TITLE
Desktop: System.Security.Cryptography.Hashing.Tests.HmacAlgorithmTest.TrivialDerivationThrows failed with "Xunit.Sdk.ThrowsException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18478]
Failed test: System.Security.Cryptography.Hashing.Tests.HmacAlgorithmTest.TrivialDerivationThrows

Configuration: outerloop_netfx_windows_nt_debug

Message:
~~~
Assert.Throws() Failure
     Expected: typeof(System.PlatformNotSupportedException)
     Actual: (No exception was thrown)
~~~

Stack Trace:
~~~
at System.Security.Cryptography.Hashing.Tests.HmacAlgorithmTest.TrivialDerivationThrows() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Cryptography.Primitives\tests\HmacAlgorithmTest.cs:line 78
~~~

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/21/testReport/System.Security.Cryptography.Hashing.Tests/HmacAlgorithmTest/TrivialDerivationThrows/

**Comment by Jiayili1** [comment]
Failed tests: 
 System.Security.Cryptography.Hashing.Tests.HmacAlgorithmTest.TrivialDerivationThrows
 System.Security.Cryptography.Hashing.Tests.HmacAlgorithmTest.ResetAlgorithmName

**Comment by krwq** [comment]
Fixed with https://github.com/dotnet/corefx/pull/18575

**Comment by Jiayili1** [comment]
This issue is repro on desktop, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/31/testReport/System.Security.Cryptography.Hashing.Algorithms.Tests/HmacSha512Tests/ProduceLegacyHmacValues/

**Comment by danmosemsft** [comment]
@Jiayili1 your test link above is a different test. Please check.
