### ISSUE TITLE
Desktop: System.Diagnostics.Tests.ProcessTests.TestInvalidPriorityClass failed with "Xunit.Sdk.ThrowsException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18471]
Failed test: System.Diagnostics.Tests.ProcessTests.TestInvalidPriorityClass

Configuration: outerloop_netfx_windows_nt_debug

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/21/testReport/System.Diagnostics.Tests/ProcessTests/TestInvalidPriorityClass/

MESSAGE:
Assert.Throws() Failure
Expected: typeof(System.ArgumentException)
Actual: typeof(System.ComponentModel.InvalidEnumArgumentException): The value of argument 'value' (96) is invalid for Enum type 'ProcessPriorityClass'.\r\nParameter name: value
+++++++++++++++++++

STACK TRACE:
at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value) 
at System.Diagnostics.Tests.ProcessTests.<>c__DisplayClass53_0.<TestInvalidPriorityClass>b__0() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Diagnostics.Process\tests\ProcessTests.cs:line 672

**Comment by Jiayili1** [comment]
This issue is repro on Full Framework Tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170418.01/workItem/System.Diagnostics.Process.Tests/analysis/xunit/System.Diagnostics.Tests.ProcessTests~2FTestInvalidPriorityClass

**Comment by Jiayili1** [comment]
This issue is repro, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/30/testReport/System.Diagnostics.Tests/ProcessTests/TestInvalidPriorityClass/

Need to verify it on next build, since the commit is not in this build

**Comment by Priya91** [comment]
This doesn't repro in latest build.
