### ISSUE TITLE
Desktop: System.Security.Cryptography.Encryption.Tests.Symmetric.TrivialTests.TestKey failed with "Xunit.Sdk.ThrowsException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18476]
Failed test: System.Security.Cryptography.Encryption.Tests.Symmetric.TrivialTests.TestKey

Configuration: outerloop_netfx_windows_nt_debug

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/21/testReport/System.Security.Cryptography.Encryption.Tests.Symmetric/TrivialTests/TestKey/

Message:
~~~
Assert.Throws() Failure
     Expected: typeof(System.Security.Cryptography.CryptographicException)
     Actual: (No exception was thrown)
~~~

Stack Trace:
~~~
at System.Security.Cryptography.Encryption.Tests.Symmetric.TrivialTests.TestKey() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Cryptography.Primitives\tests\SymmetricAlgorithm\Trivial.cs:line 120
~~~

**Comment by krwq** [comment]
Fixed with https://github.com/dotnet/corefx/pull/18575

**Comment by Jiayili1** [comment]
Another test failed with the same issue, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/System.Security.Cryptography.Rsa.Tests/ImportExport/ImportNoDP/

Failed test: System.Security.Cryptography.Rsa.Tests.ImportExport.ImportNoDP

MESSAGE:
Assert.Throws() Failure
    Expected: typeof(System.Security.Cryptography.CryptographicException)
    Actual: (No exception was thrown)
~~~
STACK TRACE:
~~~
at System.Security.Cryptography.Rsa.Tests.ImportExport.ImportNoDP() 
in D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\Security\Cryptography\AlgorithmImplementations\RSA\ImportExport.cs:line 277
~~~

**Comment by krwq** [comment]
@Jiayili1 this is different test failing - I've created separate issue for this: https://github.com/dotnet/corefx/issues/18846

**Comment by Jiayili1** [comment]
@krwq Thanks for filing the new issue for this failure.
