### ISSUE TITLE
Desktop: System.Security.Cryptography.Encryption.Tests.Asymmetric.TrivialTests.ValidKeySizeUsesProperty failed with "System.NullReferenceException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18475]
Failed test: System.Security.Cryptography.Encryption.Tests.Asymmetric.TrivialTests.ValidKeySizeUsesProperty

Configuration: outerloop_netfx_windows_nt_debug

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/21/testReport/System.Security.Cryptography.Encryption.Tests.Asymmetric/TrivialTests/ValidKeySizeUsesProperty/

Message:
~~~
System.NullReferenceException : Object reference not set to an instance of an object.
~~~

Stack Trace:
~~~
at System.Security.Cryptography.AsymmetricAlgorithm.set_KeySize(Int32 value) 
at System.Security.Cryptography.Encryption.Tests.Asymmetric.TrivialTests.ValidKeySizeUsesProperty() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Cryptography.Primitives\tests\AsymmetricAlgorithm\Trivial.cs:line 51

**Comment by krwq** [comment]
Fixed with https://github.com/dotnet/corefx/pull/18575
