### ISSUE TITLE
Desktop: System.Security.Cryptography.Hashing.Tests.KeyedHashAlgorithmTest.SetKeyNull failed with "System.NullReferenceException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18477]
Failed test: System.Security.Cryptography.Hashing.Tests.KeyedHashAlgorithmTest.SetKeyNull

Configuration: outerloop_netfx_windows_nt_debug

Message:
~~~
System.NullReferenceException : Object reference not set to an instance of an object.
~~~

Stack Trace:
~~~
at System.Security.Cryptography.KeyedHashAlgorithm.set_Key(Byte[] value) 
at System.Security.Cryptography.Hashing.Tests.KeyedHashAlgorithmTest.SetKeyNull() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Cryptography.Primitives\tests\KeyedHashAlgorithmTests.cs:line 74
~~~

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/21/testReport/System.Security.Cryptography.Hashing.Tests/KeyedHashAlgorithmTest/SetKeyNull/

**Comment by Jiayili1** [comment]
Failed tests:
 System.Security.Cryptography.Hashing.Tests.KeyedHashAlgorithmTest.SetKeyNull
 System.Security.Cryptography.Hashing.Tests.KeyedHashAlgorithmTest.EnsureDisposeFreesKey

**Comment by krwq** [comment]
Fixed with https://github.com/dotnet/corefx/pull/18575
