### ISSUE TITLE
Desktop: System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestMultipleConcurrentRequests failed

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18474]
Failed test: System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestMultipleConcurrentRequests

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/21/testReport/System.Diagnostics.Tests/HttpHandlerDiagnosticListenerTests/TestMultipleConcurrentRequests/

Message:
~~~
The timestamp sent with the event doesn't look correct
     Expected: True
     Actual: False
~~~

Stack Trace:
~~~
at System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests.TestMultipleConcurrentRequests() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Diagnostics.DiagnosticSource\tests\HttpHandlerDiagnosticListenerTests.cs:line 244
~~~

**Comment by danmosemsft** [comment]
@Jiayili1 added logging, please check for it when this fails again.

**Comment by Jiayili1** [comment]
@danmosemsft This issue is repro, checked that this build contains commit 6a2a0f6, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170418.01/workItem/System.Diagnostics.DiagnosticSource.Tests/analysis/xunit/System.Diagnostics.Tests.HttpHandlerDiagnosticListenerTests~2FTestMultipleConcurrentRequests

Message:
~~~
The timestamp sent with the event doesn't look correct. Begin 3337522260 End 3367666474 Diff 30144214 Expected < 30000000
     Expected: True
     Actual:   False
~~~

**Comment by danmosemsft** [comment]
@stephentoub any objection to raising from 30sec to 60sec?

**Comment by stephentoub** [comment]
No objection, but 30s is already really long; my guess is something is actually hung and raising the timeout won't actually fix anything. We can see I guess.

**Comment by danmosemsft** [comment]
@Jiayili1 please update both lines I changed in https://github.com/dotnet/corefx/pull/18496 to change "30" to "60" in four places, and put up a PR for it. thanks.

**Comment by danmosemsft** [comment]
@stephentoub if it hung, would it finish in 30.1 seconds? maybe some timeout internally? I didn't see one in the test.

**Comment by Jiayili1** [comment]
@danmosemsft https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/tests/HttpHandlerDiagnosticListenerTests.cs#L276  this file is changed and don't have the code that need to be edited.

**Comment by danmosemsft** [comment]
Great. this assert is gone.
