### ISSUE TITLE
Porting bug: HttpListenerRequest.Cookies throws a CookieException for invalid cookies, NETFX doesn't throw

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#18482]
```cs

        public static async Task GetClientCertificate_NoCertificate_ReturnsNull()
        {
            await GetRequest(new[] { "cookie: name=value; domain=.domain.com" }, (_, request) =>
            {
                Assert.Empty(request.Cookies);
            });
        }

        private static async Task GetRequest(string[] headers, Action<Socket, HttpListenerRequest> requestAction)
        {
            using (HttpListenerFactory factory = new HttpListenerFactory())
            using (Socket client = factory.GetConnectedSocket())
            {
                client.Send(factory.GetContent("POST", "text", headers, true));

                HttpListener listener = factory.GetListener();
                HttpListenerContext context = await listener.GetContextAsync();

                HttpListenerRequest request = context.Request;
                requestAction(client, request);
            }
        }
```

Netfx doesn't throw; any cookie with a non-empty name is added.
Netcoreapp does throw

/cc @davidsh @Priya91

**Comment by davidsh** [comment]
What is invalid about this particular cookie?

```c#
await GetRequest(new[] { "cookie: name=value; domain=.domain.com" }, (_, request) =>
{
    Assert.Empty(request.Cookies);
});
```

**Comment by karelz** [comment]
@hughbe is it about client cookies or server cookies -- can you please share the code with us? Thanks!

**Comment by karelz** [comment]
This might be impactful on compat with Desktop. 2.0, until there's further evidence that this is low-pri.

**Comment by hughbe** [comment]
It is impactful IMO. I'm not sure what you mean by client vs server cookies. Basically this is cookies sent from httpclient to httplistener - httplistener struggles to parse them.

I'm getting ready to submit a PR. Unfortunately it relies on the http listener fixes that haven't been merged yet. Would be good to get those merged so I can fix this.

**Comment by karelz** [comment]
I pinged the PRs. Can you share a gist with the test case? That may help @davidsh and @CIPop to understand it better ...

BTW: Thanks for all your great help in the area!

**Comment by davidsh** [comment]
>I'm not sure what you mean by client vs server cookies. Basically this is cookies sent from httpclient to httplistener - httplistener struggles to parse them.

My question was about client-sent vs. server-sent cookies.   Servers send cookies to clients via the 'Set-Cookie' HTTP response header.  Clients send cookies to servers via the 'Cookie' HTTP request header.

It sounds like this is about client-sent cookies, i.e. 'Cookie' HTTP request headers sent to a server. In this case, the server is httplistener.

I agree that this is important to fix.  .NET Framework is doing the right thing by ignoring parsing errors with client-sent cookies.  I think httplistener will drop them or perhaps pass them upstack to allow the dev consuming httplistener to decide what to do with malformed cookies.  But .NET Core current behavior is wrong and should not be throwing an exception.

My other question in this thread is I could see from looking what is the exact problem with the cookie in question.  What makes this particular cookie invalid:

```c#
await GetRequest(new[] { "cookie: name=value; domain=.domain.com" }, (_, request) =>
{
    Assert.Empty(request.Cookies);
});
```

**Comment by hughbe** [comment]
Oh sorry I didn't see that last example. I took it from Cookie.cs tests for invalid cookies. I think it's the fact that the domain is prefixed with a dot

**Comment by ViktorHofer** [comment]
@hughbe so you are taking that one? 👍

**Comment by karelz** [comment]
@hughbe we asked @ViktorHofer to help with Networking issues, so if you have plenty of work / no time, just say so and he can pick it up ;-) (we just don't want to steal things from under your fingers ...)
