### ISSUE TITLE
CookieParser doesn't parse cookies separated by ';'

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#18486]
```cs
public static IEnumerable<object[]> Cookies_TestData()
{
    // Returns 2 objects in .NET Core.
    // Returns 3 objects in .NET Full framework and on Unix.
    yield return new object[]
    {
        "cookie: name1=value1,name2=value2;name3=value3", new CookieCollection()
        {
            new Cookie("name1", "value1"),
            new Cookie("name2", "value2"),
            new Cookie("name3", "value3")
        }
    };
}

[Theory]//[ConditionalTheory(nameof(PlatformDetection) + "." + nameof(PlatformDetection.IsNotOneCoreUAP))]
[MemberData(nameof(Cookies_TestData))]
public async Task Cookies_Get_ReturnsExpected(string cookieString, CookieCollection expected)
{
    await GetRequest("POST", null, new[] { cookieString }, (_, request) =>
    {
        Assert.Equal(expected.Count, request.Cookies.Count);
        for (int i = 0; i < expected.Count; i++)
        {
            Assert.Equal(expected[i].Name, request.Cookies[i].Name);
            Assert.Equal(expected[i].Value, request.Cookies[i].Value);
        }
    });
}

private async Task GetRequest(string requestType, string query, string[] headers, Action<Socket, HttpListenerRequest> requestAction, bool sendContent = true)
{
    using (HttpListenerFactory factory = new HttpListenerFactory())
    using (Socket client = factory.GetConnectedSocket())
    {
        client.Send(factory.GetContent(requestType, query, sendContent ? "Text" : "", headers, true));

        HttpListener listener = factory.GetListener();
        HttpListenerContext context = await listener.GetContextAsync();

        HttpListenerRequest request = context.Request;
        requestAction(client, request);
    }
}`
```

**Comment by hughbe** [comment]
Actually, it's the other way around - netfx doesn't allow them to be separated by ';'

**Comment by karelz** [comment]
cc @Priya91

**Comment by Priya91** [comment]
cc @davidsh This desktop vs .NET Core behavior known?

**Comment by hughbe** [comment]
Its odd because the managed implementation explicitly handles these cases. surely one solution could be moving CookieParser to common (it's an internal type) and using it in the same way as the .net full framework does? This would fix most compat issues

**Comment by davidsh** [comment]
>cc @davidsh This desktop vs .NET Core behavior known?

I don't think this is a known issue.

**Comment by Priya91** [comment]
The bug seems to be in windows port of httplistener, the public api surface is calling into CookieParser.Get, whereas on Desktop it uses the internal CookieParser.GetServer(). We can move CookieParser to common and build that source into httplistener.

**Comment by karelz** [comment]
Marking as 2.0 - it is new 2.0 API and we made a porting problem.

**Comment by karelz** [comment]
@hughbe are you interested in fixing it? @Priya91 can provide some guidance if needed ...

**Comment by hughbe** [comment]
Sure I can fix this, I'll look into this when my tests PR goes in

**Comment by karelz** [comment]
Awesome, thanks! Help in Networking area is extra appreciated these days! ;-)

**Comment by hughbe** [comment]
I might need a bit of guidance here. I've moved CookieParser to common. I fixed a couple of issues with CookieParse referring to internal Cookie state [here](https://github.com/dotnet/corefx/blob/a1afdee3754dc2f254eb3293458efb7c54fd8e9c/src/System.Net.Primitives/src/System/Net/Cookie.cs#L1323-L1344)

However, there are some problems I don't really know how to solve. Firstly, we call `Cookie.InternalSetName` in multiple places, such as [here](https://github.com/dotnet/corefx/blob/a1afdee3754dc2f254eb3293458efb7c54fd8e9c/src/System.Net.Primitives/src/System/Net/Cookie.cs#L1430-L1434). We also use the internal field `Cookie.IsQuotedDomain` [here](https://github.com/dotnet/corefx/blob/a1afdee3754dc2f254eb3293458efb7c54fd8e9c/src/System.Net.Primitives/src/System/Net/Cookie.cs#L1469)

These is part of the internal surface area of Cookie that I can't access from CookieParser.cs in System.Net.HttpListener.

One solution would be to move the entire Cookie class to Common. But when I tried this, I get errors that the Cookie in common conflicts with the cookie in System.Net.Primitives. Removing the reference to System.Net.Primitives caused compilation errors for things like `IPEndPoint` etc.

**Comment by karelz** [comment]
@Priya91 can you help please? cc @stephentoub

**Comment by Priya91** [comment]
We can't have duplicate public types in different implementations, as now there'll be conflicts, hence we can move only internal/private things to common. Looking at the implementation of ```Cookie.InternalSetName```, it is not doing much except some condition checking and setting internal _name field. We can use Cookie.Name public type to hit the same codepath, and catch the exception in case of empty or null string. For the case of ```Cookie.IsQuotedDomain```, it is only setting a field to track whether quotes need to be added while doing ```Cookie.ToString()``` or while retrieving the ```CookieContainer.GetCookieHeader```, so by not setting this, we might return cookie strings without quotes in domain names. Not sure how to hack this behavior, cc @davidsh what's the impact of missing quotes around domain values in cookie header strings?

**Comment by davidsh** [comment]
>. Not sure how to hack this behavior, cc @davidsh what's the impact of missing quotes around domain values in cookie header strings?

We should follow the relevant RFC's for Cookies.  What does it says regarding "quotes around domain values"?  And for HttpListener, we need to pay attention to 2 kinds of "cookie" HTTP heraders, 'Set-Cookie' and 'Cookie'.  The first is what server sends to client. The second is what client sends to server.

**Comment by hughbe** [comment]
This issue looks like its a bug in CookieParser, not HttpListenerRequest.
