### ISSUE TITLE
Resources File in .NET Standard (1.4) with New csproj

### ISSUE THREAD

**Issue by dagrooms52** [dotnet/corefx#18490]
I'm developing an application targeting .NET Standard 1.4, using the new csproj style (not project.json), and trying to get a localizable resources file to become available throughout the project. 

I get compiler errors when including a resources file currently, similar to `'Resources' does not contain a definition for 'X'` 

The csproj automatically includes the resources file as follows:

```xml
    <ItemGroup>
        <Compile Update="Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Resources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>
```

Did it miss a step in the generation? Why can't I access any of the members of my resources file throughout the assembly?

http://stackoverflow.com/questions/43454441/resources-file-in-net-standard-1-4-with-new-csproj

**Comment by tarekgh** [comment]
@karelz we need to move this issue to msbuild. this is tooling issue and not really corefx. do you know the repo we can move this issue to?

**Comment by karelz** [comment]
I guess https://github.com/Microsoft/msbuild

**Comment by tarekgh** [comment]
@dagrooms52 I moved the issue to msbuild repo so I am closing it here.
