### ISSUE TITLE
Compilation of custom System.Linq.Expressions.MemberBinding

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#18493]
Creation of custom classes derived from `MemberBinding` is discouraged by the protected constructor being marked as obsolete. It is possible though.

Upon compilation, if the `BindingType` is one of the values defined for the enum then both interpreter and compiler will throw an `InvalidCastException`. Otherwise the compiler will throw an `ArgumentException` while the interpreter will just ignore the binding.

At the very least these should be consistent, but it seems more useful to throw the `ArgumentException` mentioned for one case above upon the call to `MemberBind` or `MemberInit` that the custom class was passed to.

(Alternatively, making the constructor `internal` rather than `protected` would be better still, but a bigger change to the public API).

**Comment by OmarTawfik** [comment]
@VSadov can you comment on the breaking change?

**Comment by VSadov** [comment]
I think th eold behavior was very broken around extending this type and the constructor was indeed marked Obsolete. 
I think the possibility of actually breaking some meaningful scenario here is very low.
