### ISSUE TITLE
Directory.GetCurrentDirectory() returns installation directory of Visual Studio 2017 in unit tests.

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#18506]
@zuoanqh commented on [Mon Apr 17 2017](https://github.com/dotnet/standard/issues/304)

**Comment by danmosemsft** [comment]
@zuoanqh what are you expecting? Does it break tests?

**Comment by mellinoe** [comment]
This seems expected to me, since devenv.exe is presumably in this folder. Did the "desktop" test runner behave differently in this case, or something like that?

Not sure why this is area-Infrastructure. @karelz ?

**Comment by karelz** [comment]
@mellinoe I thought it is about running CoreFX tests inside VS ... ooops
@tarekgh I don't think this is IO stuff really either, this is more end-to-end. It may be either by design, or a problem in VS itself ... thoughts?

**Comment by tarekgh** [comment]
>  I don't think this is IO stuff really either, this is more end-to-end. It may be either by design, or a problem in VS itself ... thoughts?

From the issue it complains about Directory.GetCurrentDirectory() so for sure it is related to how the API works regardless the reason affect the API behavior.

**Comment by karelz** [comment]
Do you think there is a bug in `Directory.GetCurrentDirectory`?
I assumed that it is just infra/VS setting current directory for the unit test process to that value and that's why the API returns it. If that's the case, then it is the fault of the infra/VS setting it there, rather than fault of the API itself, isn't it?

**Comment by zuoanqh** [comment]
I was expecting it would be in the /debug directory where the unit test project is.

**Comment by tarekgh** [comment]
We'll not know the root cause without debugging Directory.GetCurrentDirectory.

**Comment by danmosemsft** [comment]
@tarekgh surely the odds of GetCurrentDirectory returning anything other than GetCurrentDirectoryW is extremely small. Either (1) the current directory is not wrong, something else is or (2) someone up stack is setting it to something wrong. Either way it seems it should not be in this repo untill someone investigates and demonstrates it's a base issue. What do you think?

**Comment by tarekgh** [comment]
@danmosemsft feel free to move it to any repo you think it should belongs to.

**Comment by danmosemsft** [comment]
Yep, I should have done that instead of porting it here.
@zuoanqh please open a VS bug using instructions here: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017

**Comment by elscript** [comment]
Hello, guys! So, where is the issue right now? We still get the C:\WINDOWS\system32\ for Directory.GetCurrentDirectory()

**Comment by karelz** [comment]
@elscript the upstack components should have the bug reported now, assuming the VS bug was reported ...
