### ISSUE TITLE
GenFacadesTask should enable assembly resolver

### ISSUE THREAD

**Issue by jcouv** [dotnet/corefx#18516]
Per discussion with Wes and Eric, if GenFacadesTask is the only task to be run, it fails to apply a workaround (something like [this](https://github.com/dotnet/buildtools/blob/78260239e4db68ad5c2df774a27d5f9a54fd92e5/src/Microsoft.DotNet.Build.Tasks.net45/IsRestoreRequired.Desktop.cs)).
As a result, it fails to load `System.IO.FileSystem` version 4.0.0.0.

In my case, as I was working on type-forwarding for ValueTuple to desktop 4.7, I was just running `C:\repos\corefx\src\System.ValueTuple\src>msbuild /p:TargetGroup=net47`.
And even though `C:\repos\corefx\Tools\net46` contained a `System.IO.FileSystem.dll`, there would be a failure to load because its version is 4.0.1.0.

**Comment by karelz** [comment]
@ericstj @weshaggard is it must have for 2.0?

**Comment by weshaggard** [comment]
No in fact it should be moved to BuildTools... moving now.

**Comment by weshaggard** [comment]
Issue moved to [dotnet/buildtools #1443](https://github.com/dotnet/buildtools/issues/1443) via [**ZenHub**](https://www.zenhub.com/)
