### ISSUE TITLE
DCJS_VerifyDateTimeForDateTimeFormat Fails on Unix.

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#18512]
DCJS_VerifyDateTimeForDateTimeFormat fails on Unix as the following method call serializes the object into different payloads,
```
SerializeAndDeserialize(new DateTime(1, 1, 1, 3, 58, 32), value, dcjsSettings);
```
On windows: baseline: `"\"03:58:32.00 a.m.\""`
On unix: actual output: `"\"03:58:32.00 a. m.\""`

**Comment by stone-li** [comment]
The test only fails on Ubuntu as same with #18539

**Comment by shmao** [comment]
@stone-li the issues probably shares the same root cause with #18539. Can you please fix the test? Thanks.
