### ISSUE TITLE
AsymmetricAlgorithm.{To|From}XmlString throwing wrong exception type

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#18530]
https://github.com/dotnet/corefx/blob/88ec4ba8432c1444fc43ecba5bd6d70f3d41d103/src/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/AsymmetricAlgorithm.cs#L65-L73

ToXmlString/FromXmlString are throwing NotImplementedException.  They should throw a PlatformNotSupportedException, with a message.

**Comment by danmosemsft** [comment]
Hmm, in Desktop they throw NIE. NIE is correct when something must be overridden. Is that not the case here?
```c#
        // This method must be implemented by derived classes. In order to conform to the contract, it cannot be abstract.
        public virtual void FromXmlString(String xmlString) {
            throw new NotImplementedException();
        }
 
        // This method must be implemented by derived classes. In order to conform to the contract, it cannot be abstract.
        public virtual String ToXmlString(bool includePrivateParameters) {
            throw new NotImplementedException();
        }
```

**Comment by danmosemsft** [comment]
Oop, I misspoke. PNSE means not implemented on this platform. NSE means should never be reached,. eg should be overridden, or never called. NIE means we didn't finish our job. In this case, the correct seems like it should be NSE however presumably NIE is more apporpriate since that's what Desktop had and there's no particular reason to change that.

**Comment by bartonjs** [comment]
Ah, nevermind(ish).  https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/RSA.Xml.cs is really what I was looking for.(and https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/DSA.Xml.cs).

They're PNSE; though lacking in a message.
