### ISSUE TITLE
为什么没有List<T>的源代码

### ISSUE THREAD

**Issue by taotaoideas** [dotnet/corefx#1853]
https://github.com/dotnet/corefx/tree/master/src/System.Collections/src/System/Collections/Generic我在这个目录下面找不到List<T>类型的源代码，是没有开放吗？

**Comment by stephentoub** [comment]
System.Collections is currently what's known as a "partial facade" (https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System.Collections.csproj#L9); some of the types are actually defined in System.Collections.dll, while others are actually defined in mscorlib and type forwarded from System.Collections to there.  The build tools compile the types that are defined in System.Collections.csproj, and then add type forwarders to mscorlib for any of the types in the System.Collections contract that aren't in the project.  ```List<T>``` is one such type; its implementation is pulled from mscorlib, with the code available at https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/List.cs.

**Comment by taotaoideas** [comment]
Thanks, Your answer is very useful.
