### ISSUE TITLE
DataContractJsonSerializerTests.DCJS_VerifyDateTimeForFormatStringDCJsonSerSetting Fails on others OS

### ISSUE THREAD

**Issue by stone-li** [dotnet/corefx#18538]
DCJS_VerifyDateTimeForFormatStringDCJsonSerSetting pass on windows and osx, fails on others OS as the following method call serializes the object into different payloads,

`SerializeAndDeserialize(value, baseline, dcjsSettings);`

On windows and osx: baseline:  `"\"\\/Date(1291190400000{timeZoneString})\\/\""`
On others os: actual output:  `"\"\\/Date(1291161600000{timeZoneString})\\/\""`

**Comment by Jiayili1** [comment]
DataContractJsonSerializerTests.DCJS_VerifyDateTimeForFormatStringDCJsonSerSetting 

Message:

strings differ at index 13
                         ?
    [expected]:Date(1291190400000+0000)\\/\"
    [actual  ]:Date(1291161600000+0000)\\/\"
                         ?
    [Expected (with length=30)]:
    \"\\/Date(1291190400000+0000)\\/\"
    [Actual (with length=30)]:
    \"\\/Date(1291161600000+0000)\\/\"\r
    Test failed for input: 12/1/2010 12:00:00 AM\r
    Expected: \"\\/Date(1291190400000+0000)\\/\"\r
    Actual: \"\\/Date(1291161600000+0000)\\/\"\r
    Expected: True\r
    Actual:   False

        Stack Trace:

           at DataContractJsonSerializerTests.SerializeAndDeserialize[T](T value, String baseline, DataContractJsonSerializerSettings settings, Func`1 serializerFactory, Boolean skipStringCompare)
       at DataContractJsonSerializerTests.DCJS_VerifyDateTimeForFormatStringDCJsonSerSetting()

 Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170420.01/workItem/System.Runtime.Serialization.Json.ReflectionOnly.Tests/analysis/xunit/DataContractJsonSerializerTests~2FDCJS_VerifyDateTimeForFormatStringDCJsonSerSetting

**Comment by Jiayili1** [comment]
This issue is repro on Core tests, checked the commit is in build 20170426.01, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170426.01/workItem/System.Runtime.Serialization.Json.ReflectionOnly.Tests/analysis/xunit/DataContractJsonSerializerTests~2FDCJS_VerifyDateTimeForFormatStringDCJsonSerSetting

**Comment by shmao** [comment]
@stone-li can you please take a look at this failure? The test failed on NetCore in nightly run.

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170426.01/workItem/System.Runtime.Serialization.Json.Tests/analysis/xunit/DataContractJsonSerializerTests~2FDCJS_VerifyDateTimeForFormatStringDCJsonSerSetting
