### ISSUE TITLE
Desktop: System.Xml.Tests.TCValidateElement.StringPassedToValidateEndElementDoesNotSatisfyIdentityConstraints failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18548]
Failed test: System.Xml.Tests.TCValidateElement.StringPassedToValidateEndElementDoesNotSatisfyIdentityConstraints

Configuration: outerloop_netfx_windows_nt_debug

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/lastCompletedBuild/testReport/System.Xml.Tests/TCValidateElement/StringPassedToValidateEndElementDoesNotSatisfyIdentityConstraints/

MESSAGE:
~~~
Assert.Equal() Failure
     Expected: 1
     Actual: 2
~~~
STACK TRACE:
~~~
at System.Xml.Tests.TCValidateElement.StringPassedToValidateEndElementDoesNotSatisfyIdentityConstraints() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Private.Xml\tests\XmlSchema\XmlSchemaValidatorApi\ValidateElement.cs:line 507
~~~

**Comment by sepidehMS** [comment]
@AlexGhiondea 
The behavior of this test depends on the value of [LocalAppContextSwitches.IgnoreEmptyKeySequences](https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/Core/LocalAppContextSwitches.cs#L26). The default value of this switch is:
On .NET Core: `False`
On Desktop: `False` for `version >= 4.6`, `True` for `version <= 4.5.2`
Based on these facts and the assumption that we are targetting the latest version of System.Xml on full framework, this test should technically pass with `TargetGroup=netfx`. However, that's not the case. What Full Framework version do we target for netfx tests? Is it possible we are consuming some version older than 4.6?
