### ISSUE TITLE
Desktop: System.Globalization.Tests.StringNormalizationTests.IsNormalized_Invalid failed with "Xunit.Sdk.ThrowsException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18547]
Failed tests:
System.Globalization.Tests.StringNormalizationTests.IsNormalized_Invalid
System.Globalization.Tests.StringNormalizationTests.Normalize_Invalid

Configuration: outerloop_netfx_windows_nt_debug

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/lastCompletedBuild/testReport/System.Globalization.Tests/StringNormalizationTests/IsNormalized_Invalid/

MESSAGE:
~~~
Assert.Throws() Failure
     Expected: typeof(System.ArgumentNullException)
     Actual: typeof(System.NullReferenceException): Object reference not set to an instance of an object.
~~~
STACK TRACE:
~~~
at System.StringNormalizationExtensions.IsNormalized(String value) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Globalization.Extensions\src\System\StringNormalizationExtensions.netfx.cs:line 11 
at System.Globalization.Tests.StringNormalizationTests.<>c.<IsNormalized_Invalid>b__1_3() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Globalization.Extensions\tests\Normalization\StringNormalizationTests.cs:line 34
~~~

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/pull/18535
