### ISSUE TITLE
Desktop: System.IO.Pipes.Tests.AnonymousPipeTest_Specific.ReadModeToByte_Accepted failed with "System.IO.IOException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18546]
Failed test: System.IO.Pipes.Tests.AnonymousPipeTest_Specific.ReadModeToByte_Accepted

Configuration: outerloop_netfx_windows_nt_debug

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/lastCompletedBuild/testReport/System.IO.Pipes.Tests/AnonymousPipeTest_Specific/ReadModeToByte_Accepted_serverDirection__Out__clientDirection__In_/

MESSAGE:
~~~
System.IO.IOException : The handle is invalid.
~~~

STACK TRACE:
~~~
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) 
at System.IO.Pipes.PipeStream.UpdateReadMode() at System.IO.Pipes.PipeStream.get_ReadMode() 
at System.IO.Pipes.Tests.AnonymousPipeTest_Specific.ReadModeToByte_Accepted(PipeDirection serverDirection, PipeDirection clientDirection) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.IO.Pipes\tests\AnonymousPipeTests\AnonymousPipeTest.Specific.cs:line 169
~~~

**Comment by stephentoub** [comment]
I think this was technically a by-design change, but I also think it probably makes sense to fix it in .NET Core.  We're differentiating in core based on whether a CancellationToken was provided: if one was, then cancellation that occurs for other reasons is treated as an IOException, but if one wasn't, then it's treated as OperationCanceledException.  I suggest we always treat it as OperationCanceledException.

**Comment by stephentoub** [comment]
(Oops, ignore previous comment, I commented on the wrong issue.)

**Comment by ianhays** [comment]
@sepidehMS are you working on this one?

**Comment by ianhays** [comment]
I cannot repro this failure locally and have not seen it fail in CI.

Also, the linked failure in the OP actually shows this test passing, not failing.

**Comment by ianhays** [comment]
I can repro this failure locally when run in a loop.

Also, the linked failure in the OP actually shows this test passing, not failing.

**Comment by ianhays** [comment]
This is related to #19287

**Comment by stephentoub** [comment]
Dup of #19656.
