### ISSUE TITLE
There is no TcpClient(string hostname, int port) in .Net Core 1.1.0

### ISSUE THREAD

**Issue by Edward-Zhou** [dotnet/corefx#18552]
I followed below link to try TcpClient, but there is no TcpClient(string hostname, int port) in current version of System.Net.Sockets.
[TcpClient Class](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcpclient?view=netcore-1.1.0).
It seems TcpClient(string hostname, int port) are defined in [https://github.com/dotnet/corefx/blob/df579d8531104524aeadd2377a12de67f256545e/src/System.Net.Sockets/src/System/Net/Sockets/TCPClient.cs](https://github.com/dotnet/corefx/blob/df579d8531104524aeadd2377a12de67f256545e/src/System.Net.Sockets/src/System/Net/Sockets/TCPClient.cs).
Could you share any information about this issue?
Thanks

**Comment by agoretsky** [comment]
It was added for .NET Core 2.0, with 1.1 you have to use ConnectAsync method. https://docs.microsoft.com/en-us/dotnet/api/?view=netcore-1.1.0&term=tcpclient

**Comment by ViktorHofer** [comment]
@Edward-Zhou if you are fine with @agoretsky s answer, please close the issue.
