### ISSUE TITLE
Run outer loop tests on 32 bit Windows in Jenkins

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#18569]
We don't do this at present. (The only 32 bit Windows runs we do is inner loop on Windows 8)

@gkhanna79 @wtgodbe is this planned? Any reason why we shouldn't? Is it worth someone updating the groovy file at least?

cc @mmitche @karelz

**Comment by danmosemsft** [comment]
@weshaggard pointed out they are running in MC just mislabed in some contexts. 

Transmuting this to ask whether we can set up Jenkins configurations for outerloop x86 Windows for regular runs and on-request in PR's.

**Comment by wtgodbe** [comment]
I don't know of any plans to do this, but I also don't know any reason why we couldn't. Maybe @ellismg or @stephentoub might know?

**Comment by ellismg** [comment]
> I don't know of any plans to do this, but I also don't know any reason why we couldn't.

I think this is just in the camp of "no one wanted this, so we never enabled it".  If it's desired, I do think it's easy to do (ensure that you restore an x86 version of CoreCLR).

Care to send a PR @danmosemsft ?

**Comment by mellinoe** [comment]
It sounds like we have coverage for this in Helix, at least, which is good. In that case, can we move this to "Future"? It would certainly be nice to have for future test coverage, but non-blocking for 2.0. Agree/disagree, @danmosemsft ?

**Comment by stephentoub** [comment]
We're not running stuff in Jenkins anymore :)
