### ISSUE TITLE
Some NuGet packages are inaccessable

### ISSUE THREAD

**Issue by xanather** [dotnet/corefx#1856]
Small issue, some packages shown on the corefx readme (main repo page) can't be consumed unless manually compiled. For example the System.Runtime.Environment package.

Is there a reason for this?

**Comment by stephentoub** [comment]
They're new and haven't yet been published.

cc: @Priya91

**Comment by Priya91** [comment]
yeah, the issue #1017 that started this work, has got some open questions, i'll schedule an api-review for that this Friday. Once the api-review is approved, i'll generate the contracts for this. 

cc @terrajobst

**Comment by xanather** [comment]
The System.Runtime.InteropServices.RuntimeInformation still isn't accessible even though code looks to be done for it

**Comment by Priya91** [comment]
The contract will be available in the next myget push.

**Comment by xanather** [comment]
Thanks for the reply.

Okay, well in that case this isn't really an issue anymore Ill close it.
