### ISSUE TITLE
System.Net.Http.WinHttpHandler not respecting request versions explicitly targeting http/2

### ISSUE THREAD

**Issue by non-standard** [dotnet/corefx#18560]
In WinHttpHandler.cs the if block on line 792 doesn't use HTTP/2 when the request message version is explicitly set.  It currently just defaults to the WinHTTP default for sending the request.

Change:
```
// Try to use the requested version if a known/supported version was explicitly requested.
// Otherwise, we simply use winhttp's default.
string httpVersion = null;
if (state.RequestMessage.Version == HttpVersion.Version10)
{
    httpVersion = "HTTP/1.0";
}
else if (state.RequestMessage.Version == HttpVersion.Version11)
{
    httpVersion = "HTTP/1.1";
}
```

To:

```
string httpVersion = null;
if (state.RequestMessage.Version == HttpVersion.Version10)
{
    httpVersion = "HTTP/1.0";
}
else if (state.RequestMessage.Version == HttpVersion.Version11)
{
    httpVersion = "HTTP/1.1";
}
else if(state.RequestMessage.Version == HttpVersion.Version20)
{
    httpVersion = "HTTP/2"
}
```

**Comment by davidsh** [comment]
WinHTTP uses a different mechanism to turn on HTTP/2 protocol.

See:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs#L1182

Conceptually, WinHTTP treats HTTP/2 as the transport protocol.  And within HTTP/2 protocol, HTTP/1.1 is really used anyways.

The current tests for HTTP/2 protocol are passing in CI.  So, the feature works as expected as long as the client is running on the latest version of Windows 10.

**Comment by davidsh** [comment]
And see here where we test for HTTP/2:

https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs#L1704

**Comment by non-standard** [comment]
Good to know, I thought I was on the right track there, but apparently I'm not.

I am working on some client code that communicates with a server that rejects any request that is not specifically HTTP/2.  When I try and stream content of unknown length to this server, the WinHttpHandler (or maybe the lower level WinHTTP) is specifying HTTP/1.1 in the request.

```
public class StreamingHttpContent : HttpContent
{
    private readonly Stream source;
    public StreamingHttpContent(Stream source)
    {
        this.source = source;
    }
    protected override Task SerializeToStreamAsync(Stream stream, TransportContext context)
    {
        return source.CopyToAsync(stream);
    }
    protected override bool TryComputeLength(out long length)
    {
        length = -1;
        return false;
    }
}
```

If I send a known length stream to the server, the outbound request does properly include HTTP/2.

**Comment by davidsh** [comment]
You can't use a request body that has unknown known unless you make sure to include 'Transfer-Encoding: chunked" request header.

I think it would reduce confusion to close this issue since the title and original question doesn't apply anymore.

If you think there is a bug regarding HTTP/2 support, you should open a new issue and attach a full buildable/runable repro.  I suspect the problem, though, is not within the CoreFx implementation of HttpClientHandler/WinHttpHandler but rather some other aspect of your server.

I also don't understand what you mean by this:

>If I send a known length stream to the server, the outbound request does properly include HTTP/2.

Are you saying that you have debugged the server and it is not using HTTP/2 protocol?  Or you have looked at the HttpResponseMessage.Version field and see that the response is not HTTP/2?

**Comment by davidsh** [comment]
>I am working on some client code that communicates with a server that rejects any request that is not specifically HTTP/2.

Also, this is not per RFC in my opinion.  Servers are supposed to downgrade to HTTP/1.1.  And many servers only support HTTP/2 connections using secure "https".

**Comment by non-standard** [comment]
> Also, this is not per RFC in my opinion. Servers are supposed to downgrade to HTTP/1.1. And many servers only support HTTP/2 connections using secure "https".

Agreed, but that is a constraint on the server I am trying to call.

> Are you saying that you have debugged the server and it is not using HTTP/2 protocol? Or you have looked at the HttpResponseMessage.Version field and see that the response is not HTTP/2?

To debug the issue, I created a simple http/2 server in nodejs that just dumps the request headers to logs.  When I set the HttpContent of the request to a StreamContent the request comes through my nodejs server as HTTP/2, if I set the HttpContent to a custom type that computes a -1 length, the request comes through my nodejs server as HTTP/1.1

> You can't use a request body that has unknown known unless you make sure to include 'Transfer-Encoding: chunked" request header.
> I think it would reduce confusion to close this issue since the title and original question doesn't apply anymore.

I'll close this until I can dig into it deeper and see if I can find out why I am seeing what I am seeing.  Thanks for the info and help!
