### ISSUE TITLE
Add ReadOnlySpan CopyTo tests that already exist for Span

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#18572]
cc @WinCPP, @shiftylogic 

An example of this would be the test recently added here: https://github.com/dotnet/corefx/pull/18286

We want these and possibly other such tests added to RoS from:
https://github.com/dotnet/corefx/blob/master/src/System.Memory/tests/Span/CopyTo.cs#L205

To here:
https://github.com/dotnet/corefx/blob/master/src/System.Memory/tests/ReadOnlySpan/CopyTo.cs#L123

**Comment by WinCPP** [comment]
@ahsonkhan I can work on this after I do #16640. Kindly assign it to me.
