### ISSUE TITLE
IsolatedStorage depends on two PlatformNotSupported assemblies on Unix

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#18578]
I noticed this when doing some package refactoring.

IsolatedStorage's unix implementation depends on System.Security.AccessControl and System.Security.Principal.Windows, both of which are not implemented.

I suspect this means that IsolatedStorage doesn't work on Unix, or at least some portion of it doesn't.

/cc @weshaggard

**Comment by JeremyKuhne** [comment]
It doesn't actually use these assemblies when running on Unix. The code does a platform check and only tries to ACL on Windows.

**Comment by ericstj** [comment]
Any reason why you didn't just cross-compile it instead?  Since this thing is part of the shared framework we're already building it separately for Windows vs Unix.  Nearly every other library with the same requirement handles this problem at build time rather than runtime.

**Comment by ViktorHofer** [comment]
Related: https://github.com/dotnet/corefx/issues/15337

I think we can definitely remove the dependencies on System.Security.AccessControl and System.Security.Principal.Windows for non Windows by excluding it at build time. 

But we need to need achieve more as @weshaggard pointed out in the issue above, that netcoreapp shouldn't reference System.Security.AccessControl at all.

**Comment by JeremyKuhne** [comment]
> Any reason why you didn't just cross-compile it instead?

Only that we didn't have to. It was one point of difference in the implementation and doing a runtime check avoided the cross-compile.

**Comment by ViktorHofer** [comment]
@JeremyKuhne I would offer to do the cross-compile change. With that we also fulfill the requirements in the other issue for at least non Windows platforms. Are you fine with that?

**Comment by JeremyKuhne** [comment]
@ViktorHofer Sure, go ahead and cross-compile it. You can remove the runtime check as part of doing that.
