### ISSUE TITLE
Desktop: System.Security.Permissions.Tests.EvidenceBaseTests.HashCallMethods failed with "System.IO.FileNotFoundException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18595]
Failed test: System.Security.Permissions.Tests.EvidenceBaseTests.HashCallMethods

Configuration: outerloop_netfx_windows_nt_debug

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/23/testReport/System.Security.Permissions.Tests/EvidenceBaseTests/HashCallMethods/

MESSAGE:
~~~
System.IO.FileNotFoundException : Could not load file or assembly 'System.Reflection' or one of its dependencies. The system cannot find the file specified.
~~~
STACK TRACE:
~~~
at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) 
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) 
at System.Reflection.Assembly.Load(AssemblyName assemblyRef) 
at System.Security.Permissions.Tests.EvidenceBaseTests.HashCallMethods() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Permissions\tests\EvidenceBaseTests.cs:line 45

**Comment by danmosemsft** [comment]
Test issue. This `            Hash hash = new Hash(Reflection.Assembly.Load(new Reflection.AssemblyName("System.Reflection")));` 
needs to instead be `            Hash hash = new Hash(Reflection.Assembly.Load(AssemblyGetExecutingAssembly());` or similar.

**Comment by danmosemsft** [comment]
@Jiayili1 can you please try making the change above, in this file, and verify it passes both normally and with `/p:targetgroup=netfx` and if so put up a PR.

**Comment by safern** [comment]
I was disabling all tests in System.Security.Permissions, should I disable them all or just the ones that don't make sense on Desktop that doesn't really test anything?

**Comment by Jiayili1** [comment]
@danmosemsft msbuild /t:BuildAndTest /p:targetgroup=netfx failed with 
Metadata file 'C:\Fork1\Source\Repos\corefx\bin/runtime/netfx-Windows_NT-Debug-x64/xunit.core.dll'
could not be found

But xunit.core.dll exists under that folder.

**Comment by safern** [comment]
Did you build for netfx from root before doing that?

Try doing from the root of your repo:
`clean.cmd -all`
`build.cmd -framework:netfx`

And then do msbuild...

**Comment by Jiayili1** [comment]
thanks @safern , msbuild /t:BuildAndTest /p:targetgroup=netfx failed with:

xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
  System.BadImageFormatException: Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, Pu
  blicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution.
  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
  System.BadImageFormatException: Cannot load a reference assembly for execution.
  Finished running tests.  End time= 0:03:05.70, Exit code = 1

**Comment by safern** [comment]
I'll investigate as this looks like infra issue.
