### ISSUE TITLE
System.Data.SqlClient.Tests.DiagnosticTest.ExecuteReaderAsyncTest failed with "Timed out after 60000ms waiting for remote process 54039"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18604]
Failed test: System.Data.SqlClient.Tests.DiagnosticTest.ExecuteReaderAsyncTest

Configuration: outerloop_netcoreapp_Ubuntu 14.04_release

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_ubuntu14.04_release/20/testReport/System.Data.SqlClient.Tests/DiagnosticTest/ExecuteReaderAsyncTest/

MESSAGE:
~~~
Timed out after 60000ms waiting for remote process 54039
Expected: True
Actual: False
~~~
STACK TRACE:
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()

**Comment by Jiayili1** [comment]
Closed issue: https://github.com/dotnet/corefx/issues/16421

**Comment by ViktorHofer** [comment]
@corivera this is one of the last issues for ZBB. Are you working on it? Do you need help?

**Comment by corivera** [comment]
Likely an issue with SQL tests' proxy server code. Moving to Future

**Comment by v-haren** [comment]
Failed again in ci, detail:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_debug/48/testReport/System.Net.Http.Functional.Tests/DiagnosticsTest/SendAsync_ExpectedDiagnosticSourceActivityLogging/

**Comment by danmosemsft** [comment]
cannot be diagnosed anymore
