### ISSUE TITLE
Desktop: System.Linq.Parallel.Tests.SumTests.Sum_Float_Longrunning failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18600]
Failed test: System.Linq.Parallel.Tests.SumTests.Sum_Float_Longrunning

Configuration: outerloop_netfx_windows_nt_debug

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/23/testReport/System.Linq.Parallel.Tests/SumTests/Sum_Float_Longrunning_count__65536_/

MESSAGE:
~~~
Assert.Equal() Failure
     Expected: 2.147451E+09
     Actual: 2.147422E+09
~~~
STACK TRACE:
~~~
at System.Linq.Parallel.Tests.SumTests.Sum_Float(Int32 count) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Linq.Parallel\tests\QueryOperators\SumTests.cs:line 132 
at System.Linq.Parallel.Tests.SumTests.Sum_Float_Longrunning(Int32 count) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Linq.Parallel\tests\QueryOperators\SumTests.cs:line 143
~~~

**Comment by Clockwork-Muse** [comment]
Probably due to not having #1215 ?  Given the large difference it shows (ie: unlikely to be just from rounding errors)

**Comment by Jiayili1** [comment]
This issue is repro on desktop, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/30/testReport/System.Linq.Parallel.Tests/SumTests/Sum_Float_Longrunning_count__65536_/

**Comment by stephentoub** [comment]
> This issue is repro on desktop

Different test, same issue.
