### ISSUE TITLE
Linux tests fail in CI due to mscorlib.ni.dll existing.

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#1861]
Linux test runs in CI have been failing (silently) for a while with execute assembly errors.  This started around here:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst/264/
 
Which had these changes:
 
Update to latest CoreFx packages (commit: 08c0d8628ef621fbd44d7aaa85b3239616a6b108)
Move DNU/Roslyn forward (commit: 804b4330a6ae767694cf89ebd173533b539f16f5)

The problem looks to be due to the fact that we are now copying mscorlib.ni.dll into the test folder.  This is not a Linux native image so things blow up when we try to load and run it.

To unblock things, I am adding some logic to run-tests.sh to just delete the native images, but that's not the right long term thing (especially with crossgen support coming real soon now).  We need to stop this incorrect native image from being deployed, and eventually deploy the right one.

This issue tracks doing the right thing.  Once fixed, we should remove the code in run-test.sh that's tagged with this issue number.

**Comment by mmitche** [comment]
Removed mscorlib.ni.dll from the copy list.  I think the right long term solution is to eliminate use of the corefx windows build from the test altogether.  This means using the Linux build, which means that the build steps for Linux corefx when not running tests should still set up the test directories to be ready for execution.

Or we could get mscorlib to run using CoreCLR on Linux.

**Comment by ellismg** [comment]
> This means using the Linux build, which means that the build steps for Linux corefx when not running tests should still set up the test directories to be ready for execution.

I think this is a great idea.

> Removed mscorlib.ni.dll from the copy list.

So is CI broken now without merging in #1862?  Do you want me to update it such that I don't have the hack in the `run-tests.sh` file anymore?

**Comment by ellismg** [comment]
This was fixed with #1862.
