### ISSUE TITLE
What can EntityFramework be waiting for so long?

### ISSUE THREAD

**Issue by FrancoisM** [dotnet/corefx#18626]
In that [SO ](http://stackoverflow.com/questions/43503179/azure-web-api-entityframework-inconsistent-bad-performances)post, I'm trying to find out why my query response time can vary so much. It shows that the time is spent waiting. But waiting what and why?

**Comment by ViktorHofer** [comment]
Wrong repo. Please post your question here: https://github.com/aspnet/EntityFramework.

**Comment by FrancoisM** [comment]
Oops, sorry I don't know how I ended up in the wrong repo.
