### ISSUE TITLE
Failure of WaitForChangedTests.CreatedDeleted_Success

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#18630]
@ianhays attempted to fix in https://github.com/dotnet/corefx/pull/17240
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/6591/consoleFull#-12256351162d31e50d-1517-49fc-92b3-2ca637122019
```
11:37:46 
     System.IO.Tests.WaitForChangedTests.CreatedDeleted_Success(changeType: Deleted) [FAIL]
11:37:47         Assert.Equal() Failure
11:37:47         Expected: Deleted
11:37:47         Actual:   0
11:37:47         Stack Trace:
11:37:47            D:\j\workspace\windows_nt_de---4526f5ff\src\System.IO.FileSystem.Watcher\tests\FileSystemWatcher.WaitForChanged.cs(152,0): at System.IO.Tests.WaitForChangedTests.CreatedDeleted_Success(WatcherChangeTypes changeType)
```

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/issues/16857

**Comment by ianhays** [comment]
Hmm. Looks like I was overconfident in the value of retries when I reduced the timeout from 50000ms to 500ms and moved the tests to innerloop.
