### ISSUE TITLE
No test result generated under "Microsoft.Win32.Registry.Tests"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18653]
No test result generated under "Microsoft.Win32.Registry.Tests"

Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20170420.01/workItem/Microsoft.Win32.Registry.Tests/wilogs

Configuration:
Windows.10.Amd64:x64-Debug

**Comment by ViktorHofer** [comment]
https://github.com/dotnet/corefx/pull/18648
