### ISSUE TITLE
Desktop: XmlSerializerTests.Xml_TimeSpanAsRoot failed with "XML comparison is also failing"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18661]
Failed tests:
Xml_TimeSpanAsRoot
Xml_TypeWithDateTimePropertyAsXmlTime
Xml_TypeWithTimeSpanProperty

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/24/consoleText

Message:
~~~
XML comparison is also failing
        Test failed for input: 01:02:03
        Expected: <?xml version="1.0" encoding="utf-8"?>
        <TimeSpan>PT1H2M3S</TimeSpan>
        Actual: <?xml version="1.0"?>
        <TimeSpan xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" />
        Expected: True
        Actual:   False
~~~

Stack Trace:
~~~
at XmlSerializerTests.SerializeAndDeserialize[T](T value, String baseline, Func`1 serializerFactory, Boolean skipStringCompare, XmlSerializerNamespaces xns) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Private.Xml\tests\XmlSerializer\XmlSerializerTests.cs:line 3432 
at XmlSerializerTests.Xml_TimeSpanAsRoot() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Private.Xml\tests\XmlSerializer\XmlSerializerTests.cs:line 1635
~~~

**Comment by Jiayili1** [comment]
This issue is repro on Full Framework Tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170426.01/workItem/System.Xml.XmlSerializer.ReflectionOnly.Tests/analysis/xunit/XmlSerializerTests~2FXml_TimeSpanAsRoot

**Comment by danmosemsft** [comment]
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170501.01/workItem/System.Xml.XmlSerializer.Tests

**Comment by danmosemsft** [comment]
Note this reproes in reflectoin only and non reflection only.
