### ISSUE TITLE
DNS protocol support enhancement: MX and SRV records

### ISSUE THREAD

**Issue by Bhaal22** [dotnet/corefx#1866]
Hi,

Is there any plan to support MX or SRV DNS field in corefx ?

Thank you.

Bhaal22

**Comment by davidsh** [comment]
Currently, we have the System.Net.NameResolution package which includes the Dns and IPHostEntry classes. That source code is not yet on GitHub.  Those were part of the original .NET Framework (Desktop).   While named 'Dns', it is not strictly a DNS lookup but uses additional name resolution mechanisms.

We have heard previous feedback from customers about having more Dns specific functionality such as what you mention, i.e. MX, SRV, TXT etc. record lookups.  We have no immediate plans for this but would welcome ideas on this especially on how the current Dns class object model would fit into expanding in that direction.

**Comment by Bhaal22** [comment]
Sure.
Is it planned to be included in the corefx repository ?
Will check procedure for API enhancement

**Comment by davidsh** [comment]
Yes, we plan to eventually open source and to the GitHub repo the current CoreFx sources that represent the rest of the System.Net packages (such as System.Net.NameResolution) over the next several weeks.

**Comment by karelz** [comment]
Should be covered by #13890.
