### ISSUE TITLE
Desktop: Test "XmlSerializerTests.SoapEncodedSerializationTest_Enum" failed with "System.InvalidOperationException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18660]
Failed tests:
 XmlSerializerTests.SoapEncodedSerializationTest_Enum
 XmlSerializerTests.SoapEncodedSerializationTest_Basic
 XmlSerializerTests.SoapEncodedSerialization_IncludeType
 XmlSerializerTests.SoapEncodedSerializationTest_With_SoapType
 XmlSerializerTests.SoapEncodedSerialization_SoapAttribute
 XmlSerializerTests.SoapEncodedSerialization_CircularLink
 XmlSerializerTests.SoapEncodedSerializationTest_ComplexField
 XmlSerializerTests.SoapEncodedSerializationTest_Array
 XmlSerializerTests.SoapEncodedSerializationTest_With_SoapIgnore
 XmlSerializerTests.SoapEncodedSerializationTest_NestedPublicType
 XmlSerializerTests.SoapEncodedSerializationTest_List
 XmlSerializerTests.SoapEncodedSerializationTest_With_SoapElement 

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/24/consoleText

Message:
~~~
System.InvalidOperationException : Unable to generate a temporary class (result=1).
        error CS0012: The type 'System.Enum' is defined in an assembly that is not referenced. 
       You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
~~~

Stack Trace:
~~~
at System.Xml.Serialization.Compiler.Compile(Assembly parent, String ns, XmlSerializerCompilerParameters xmlParameters, Evidence evidence)
             at System.Xml.Serialization.TempAssembly.GenerateAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, Evidence evidence, XmlSerializerCompilerParameters parameters, Assembly assembly, Hashtable assemblies)
             at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location, Evidence evidence)
             at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace)
             at System.Xml.Serialization.XmlSerializer..ctor(XmlTypeMapping xmlTypeMapping)
          D:\j\workspace\outerloop_net---903ddde6\src\System.Private.Xml\tests\XmlSerializer\XmlSerializerTests.cs(2684,0): 
at XmlSerializerTests.SoapEncodedSerializationTest_Enum()
~~~

**Comment by Jiayili1** [comment]
Failed tests:
 XmlSerializerTests.Xml_Soap_Enum_With_SoapEnumOverrides
 XmlSerializerTests.Xml_Soap_ComplexField
 XmlSerializerTests.Xml_Soap_Basic_FromMappings
 XmlSerializerTests.Xml_Soap_WithNullables
 XmlSerializerTests.Xml_Soap_Array
 XmlSerializerTests.Xml_Soap_TypeWithNullableFields
 XmlSerializerTests.Xml_Soap_List
 XmlSerializerTests.Xml_Soap_TypeWithEnumFlagPropertyHavingDefaultValue
 XmlSerializerTests.Xml_Soap_TypeWithReadOnlyMyCollectionProperty
 XmlSerializerTests.Xml_Soap_Basic
 XmlSerializerTests.Xml_Soap_Enum
 XmlSerializerTests.Xml_Soap_TypeWithXmlQualifiedName
 XmlSerializerTests.Xml_Soap_ObjectAsRoot_Nullable
 XmlSerializerTests.Xml_Soap_With_SoapIgnore
 XmlSerializerTests.Xml_Soap_NestedPublicType 
 XmlSerializerTests.Xml_Soap_Enums
 XmlSerializerTests.Xml_Soap_TypeWithMyCollectionField
 XmlSerializerTests.XmlMembersMapping_Soap_SimpleType
 XmlSerializerTests.Xml_Soap_With_SoapType
 XmlSerializerTests.Xml_Soap_With_SoapElement
 XmlSerializerTests.Xml_Soap_Nullable
 XmlSerializerTests.Xml_Soap_MyCollection

**Comment by safern** [comment]
Tracking issue: #18964
