### ISSUE TITLE
WebClient.UploadValuesAsync app-compat difference with Desktop

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#18674]
While investigating #17882, I root caused the failure of the WebClient.UploadValuesAsync test.

On .NET Framework, WebClient uses an internal method, `UrlEncodeBytesToBytesInternal`, to "UrlEncode" the NameValueCollection. This is causing it to use lowercase hex digits.

On .NET Core, WebClient uses the public WebUtility.UrlEncode method which always uses uppercase hex digits.

The public WebUtility.UrlEncode is behaving the same (uppercase digits) on both .NET Framework and .NET Core.

However, .NET Core WebClient is sending request body data using uppercase hex digits while on .NET Framework it is using lowercase hex digits while sending the request body data.

For app-compat, we should change .NET Core WebClient's implementation to match .NET Framework.

**Comment by davidsh** [comment]
cc: @stephentoub @karelz

**Comment by karelz** [comment]
Thanks @davidsh. Sounds reasonable, moving to 2.0.
