### ISSUE TITLE
dumpling error

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#18676]
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_fedora24_debug/25/consoleFull#-74100521779fe3b83-f408-404c-b9e7-9207d232e5fc
```
00:28:37   ImportError: No module named requests
00:28:37   python: can't open file '/mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug/tempHome/.dumpling/dumpling.py': [Errno 2] No such file or directory
```

@mellinoe

**Comment by mellinoe** [comment]
I'm working on getting that python module installed; shouldn't take long.

**Comment by mellinoe** [comment]
This should be fixed now. I'll close when i see the new images being used.

**Comment by mellinoe** [comment]
The new image looks like it's working.
