### ISSUE TITLE
XmlDictionaryReader / Writer Canonicalization throws NotSupportedException

### ISSUE THREAD

**Issue by brentschmaltz** [dotnet/corefx#18682]
Is there a plan to support Canonicalization in Core?

**Comment by karelz** [comment]
Which API in particular? [`EndCanonicalization`](https://apisof.net/catalog/System.Xml.XmlDictionaryReader.EndCanonicalization()) is part of .NET Core 1.0.

**Comment by brentschmaltz** [comment]
@karelz Yes the interface exists. An UnsupportedException is thrown for the same code path as a net451 target. Perhaps I need to make a different call.
at Microsoft.IdentityModel.Tokens.Saml2.Saml2Serializer.ReadNameIdType(XmlDictionaryReader reader) in c:\github\wilsonWsFed\src\Microsoft.IdentityModel.Tokens.Saml\Saml2\Saml2Serializer.cs:line 1063'. ---> System.NotSupportedException: Specified method is not supported.
   at System.Xml.XmlDictionaryReader.StartCanonicalization(Stream stream, Boolean includeComments, String[] inclusivePrefixes)

**Comment by krwq** [comment]
cc: @shmao

**Comment by karelz** [comment]
@shmao can you please provide guidance when you mark something up-for-grabs? What needs to happen?

**Comment by shmao** [comment]
@karelz Thanks for the guidance.

**Comment by karelz** [comment]
Sure thing. BTW: I didn't mean to discourage you to mark it up-for-grabs, but it should be accompanied with guidance, such that it is actionable for contributors to pick up and take a stab at it ... Thanks!

**Comment by brentschmaltz** [comment]
@karelz is the support missing?

**Comment by shmao** [comment]
@brentschmaltz the API is  in NetStandard for compilation compatibility purpose. The functionality of the API is not supported on NetCore now. Would you mind sharing the scenario where you use this API with us?

**Comment by brentschmaltz** [comment]
@shamo asp.net takes a dependency on Microsoft.IdentityModel ( https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet ) for OIDC, WsFed, Saml and Jwt support in Katana, We were hoping to extend WsFed support into Asp.Net Core 2.0 and need canonicalization support to validate XML signatures.

**Comment by danmosemsft** [comment]
@shmao can you clarify, does this work on .NET Framework?

I didn't have this on any list as it's throwing NotSupportedExceptoin not PlatformNotSupportedExceptoin. 

NSE should mean "no platforms support this" for example, the method must always be overridden. 

PNSE means "some platforms support this --usually desktop -- but currently this one does not". Those may be filled in in future, or in some cases never (eg., COM on Unix)

@Petermarcu

**Comment by brentschmaltz** [comment]
@danmosemsft there is no support in Core. There is support in Desktop.

**Comment by danmosemsft** [comment]
OK @shmao is there anything else in Serialization code this category -- where we added API in Core but it doesn't have full desktop functionality?

Everything either needs to work, or (if absolutely cannot) throw PNSE (with a nice reason) and not NSE.

@zhenlan

**Comment by danmosemsft** [comment]
My scanning only threw up these, all in XmlSerializer class.

        protected virtual XmlSerializationReader CreateReader() { throw new PlatformNotSupportedException(); }
        protected virtual object Deserialize(XmlSerializationReader reader) { throw new PlatformNotSupportedException(); }
        protected virtual XmlSerializationWriter CreateWriter() { throw new PlatformNotSupportedException(); }
        protected virtual void Serialize(object o, XmlSerializationWriter writer) { throw new PlatformNotSupportedException(); }

These seem to lead to a number of other API's potentially throwing. These API's may be amongst them, (we care about all but these are highest usage)
Deserialize(TextReader)
Deserialize(XmlReader)
Deserialize(Stream)

**Comment by shmao** [comment]
`XmlDictionaryReader.EndCanonicalization` was not on our NS2.0 radar as it was already in NetCore since 1.0. I had a look at the desktop implementation of the method. It's not trivial. As we're fully booked by other 2.0 issues, I'm afraid we won't have time to make this into 2.0. But I will change the exception to PNSE.

I'll look at the PNSE thrown from XmlSerializer.

cc: @zhenlan

**Comment by brentschmaltz** [comment]
@karelz @shmao @Eilon  yes, canonicalization is non trival. This will block WsFed in asp.net core. Asp.Net could still choose to support fed on desktop.

**Comment by danmosemsft** [comment]
@shmao here's the full list the analyzer threw up - it tried to find possible transitive PNSE paths leading back to NS2.0 API. Some could be bogus. All on XmlSerializer
```
Deserialize(TextReader)
Deserialize(XmlReader)
Deserialize(Stream)
Serialize(XmlWriter, Object, XmlSerializerNamespaces)
Serialize(XmlWriter, Object, XmlSerializerNamespaces, String)
Deserialize(XmlReader, String)
Deserialize(XmlReader, XmlDeserializationEvents)
CreateWriter()
Serialize(Object, XmlSerializationWriter)
Serialize(XmlWriter, Object, XmlSerializerNamespaces, String, String)
CreateReader()
Deserialize(XmlSerializationReader)
Deserialize(XmlReader, String, XmlDeserializationEvents)
```

**Comment by karelz** [comment]
It is a pity it comes as last minute ask :(, few weeks back we might have still options to do something about, oh well ...
@Eilon how impactful is it on your team?

**Comment by brentschmaltz** [comment]
@karelz actually it wasn't a last minute ask. More of a last minute discovery of a missing feature. It was discussed months ago that xml canonicalization was required.

**Comment by Petermarcu** [comment]
Wsfed has been a strong ask from customers on core. Unfortunately we all assumes that the ALL being there meant it worked :( We should talk about options.

**Comment by Petermarcu** [comment]
@danmosemsft, I assume this didn't show up in our list of PNSE's because it was an NSE? We need to get this added to our list of places where .NET Core may not be .NET Standard compliant. This API is in .NET Standard right?

**Comment by brentschmaltz** [comment]
@Petermarcu let's not give up yet.

**Comment by Petermarcu** [comment]
Oh, I didn't mean to give up. I meant to get this added to the list of gaps we need to find a way to address.

**Comment by Eilon** [comment]
Sorry not familiar with what scenarios require this. In terms of importance, I think that comes to @vibronet and @blowdart .

**Comment by Petermarcu** [comment]
@brentschmaltz , @zhenlan is going to see how he can get it implemented over the next few weeks.

**Comment by danmosemsft** [comment]
@Petermarcu 
> @danmosemsft, I assume this didn't show up in our list of PNSE's because it was an NSE? We need to get this added to our list of places where .NET Core may not be .NET Standard compliant. This API is in .NET Standard right?

Correct on both counts. I will do a scan of NSE now and see if I spot any that should not be NSE.

**Comment by danmosemsft** [comment]
The PNSE I listed above have now been fixed in #18768 by changing the exception type to NSE to match Desktop.

This issue remains open to track Canonicalization.

**Comment by krwq** [comment]
I'm not sure I have a full context but could possibly https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/XmlDsigC14NTransform.cs be reused here? Likely not most efficient but better than nothing

**Comment by shmao** [comment]
@brentschmaltz Do you need to use `XmlDsigC14NTransform` or `XmlDsigExcC14NTransform`? It seems that both of the APIs are available in NetCore2.0 only (not in NetStandard2.0). Is your application built against `netstandard` or `netcoreapp`?

**Comment by krwq** [comment]
@shmao - FYI crypto-xml can be easily built against netstandard2.0 if private builds are fine but there will be likely feature work after 2.0 that's why we haven't officially enabled it there yet

**Comment by brentschmaltz** [comment]
@shmao I am going to see how far XmlDsigC14nTransform and XmlDsigExcC14NTransform can get us. Thanks.

**Comment by krwq** [comment]
@shmao - for future it might be worth into looking into unifying some of the serialization and crypto-xml code - possibly there are more things like that

**Comment by brentschmaltz** [comment]
@shmao m.im* assemblies currently provide net451 and netstandard 1.4 targets. How does this fit with NetCore2.0?

**Comment by Petermarcu** [comment]
You should be able to use the netstandard 1.4 asset in .NET Core 2.0.

**Comment by karelz** [comment]
Marking as Post-ZBB as it will be DCR done later.

**Comment by brentschmaltz** [comment]
@Petermarcu  Attempting to include in my csproj <PackageReference Include="System.Security.Cryptography.Xml" Version="4.3.0-*"> results in a failure. Will I be able to include this in an assembly that provides a netstandard 1.4 target.  Or will I need to provide a netstandard 2.0 target?

 I realize I .NET core 2.0 app can consume a netstandard 1.4 targeted assembly.

**Comment by Petermarcu** [comment]
Not sure I completely followed that but you should be able to include a library that targets netstandard1.4 as a reference from another netstandard1.4 library. What is the error you are getting and what version of the tools are you using?

**Comment by krwq** [comment]
@Petermarcu - this is netstandard1.4 app trying to reference netcoreapp2.0 - I do not think this will work.

@brentschmaltz I believe you need to target netcoreapp2.0 unless for some reason you require netstandard then you will need private build which retargets crypto-xml to netstandard2.0 (change target to netstandard in configuration files and remove all references from csprojes)

**Comment by brentschmaltz** [comment]
@krwq that's is sort of what I thought. 

I believe I will need to add an additional 2.0 target (not clear about why netstandard 2.0 OR netcoreapp 2.0) for this all to work. Currently I have net451 and netstandard 1.4. WsFed support could then show up in asp.net vNext which is has a 2.0 target.

**Comment by krwq** [comment]
@brentschmaltz - netcoreapp is a subset of netstandard. netcoreapp also includes desktop so I believe only netcoreapp2.0 should be good enough.

**Comment by krwq** [comment]
Sorry, I meant it in a context of targets

**Comment by Petermarcu** [comment]
For libraries, they should be netstandard if they can be. Only choose a platform specific target if you have to. Netstandard is the way to work on multiple runtimes/frameworks.

**Comment by brentschmaltz** [comment]
Microsoft.IdentityModel 5.2.0 will provide targets: net451, netstandard1.4. This will get WsFed in Desktop.
Microsoft.IdentityModel 5.3.0 add a target for netstandard2.0 when the C14N support is figured out.

**Comment by Petermarcu** [comment]
Why wouldn't you provide the netstandard2.0 asset in 5.2? Does the netstandard1.4 asset support less?

C14N support is not missing API's right? Just missing an implementation on .NET Core?

**Comment by Petermarcu** [comment]
In other words, if you can ship a fully featured library that targets netstandard2.0 and that can run on .Net Framework and Mono that would be great. This will let other .NET Standard 2.0 libraries build on top of it and not have to fork for .NET Framework. .NET Core 2.0 has the API's and is missing a little implementation. You should ship your library expecting it to work on .NET Core 2.0 when its .NET Standard 2.0 support is complete.

**Comment by brentschmaltz** [comment]
@Petermarcu I am hoping it all lines up. I am reluctant to ship a library that I haven't tested hoping that when the OM shows up it all works. The 'light-up' CNG effort resulted in a backout of CNG in WCF. 
When I poked around with the .Net1.4 target, I found other OM missing (for example, XmlDictionaryReader.ReadString() is not in .Net1.4) and I had to change code so I wouldn't have a bunch of #ifdef's. When I find an acceptable workaround, I don't open an issue otherwise we would never get this don.

**Comment by Petermarcu** [comment]
Shipping it on netstandard2.0 means that you expect it to work anywhere that says it supports .NET Standard 2.0. It's up to the runtimes to fulfill that contract. You can use the netstandard2.0 asset on .NET 4.6.1 and it will work.

**Comment by brentschmaltz** [comment]
When the support shows up, we will include the support in M.IM after testing.
I will wait for notification that C14n support is available.

**Comment by Petermarcu** [comment]
My point is you can support .net standard 2.0 with full features on .NET Framework and Mono. You can test it there.

**Comment by brentschmaltz** [comment]
@Petermarcu in that respect, yes it should be very quick to run through a set of tests for a .netstandard 2.0 target on core and call it good. I expect a couple of things but at the noise level.

**Comment by shmao** [comment]
@brentschmaltz we've added the implementation for canonicalization on NetCore by https://github.com/dotnet/corefx/pull/19378. Can you please give it a try and see if it unblocks your development for wsfed?

**Comment by brentschmaltz** [comment]
@shamo I am on vacation until the 17th. of May.  I will make this a priority when I return.

**Comment by brentschmaltz** [comment]
@shamo was this in Preview1? https://github.com/dotnet/core/tree/master/release-notes

**Comment by shmao** [comment]
It's not in preview1. The latest preview2 should include it.

**Comment by brentschmaltz** [comment]
@shmoa can you point me to those packages?

**Comment by shmao** [comment]
https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.NETCore.App should include the fix for netcoreapp

**Comment by shmao** [comment]
@brentschmaltz any updates on this? Did you get a chance to try the Canonicalization feature?

**Comment by karelz** [comment]
Closing this as Fixed. If there are any issues, please file new bugs. They will have to go through Escrow.

**Comment by brentschmaltz** [comment]
@karelz @shmao I still haven't been able to walk through the code to prove out the Core2.0 app works.
Will have that soon.
