### ISSUE TITLE
Delete *UnknownUnix.*cs

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#18683]
We never set the property necessary to build them and they're only stubs.

@stephentoub shall I just delete them?

**Comment by stephentoub** [comment]
We don't still use that on FreeBSD? We added this when folks were bringing up additional platforms, so that libraries that needed more specialization than just "Unix" could be stubbed it easily and not break the entire build.

**Comment by danmosemsft** [comment]
Uh, you're right we use it for BSD's. The UnknownUnix property could probably be deleted but not important..
