### ISSUE TITLE
Validation missing when adding certain headers to WebClient.Headers collection

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#18680]
While investigating #17882, I discovered that adding certain request headers to `WebClient` are not error-checked the same between .NET Core and .NET Framework implementations.

Adding 'Connection', or 'Expect' request headers throws WebException when sending the request using .NET Framework.  But .NET Core does not throw exception.

Adding 'Host' request header with an illegal DNS name throws WebException when sending the request using .NET Framework.  But .NET Core does not throw exception.

Added new tests to validate this and marked the tests as disabled for .NET Core.

**Comment by karelz** [comment]
This is legacy API, new in .NET Core 2.0.
Expected cost: 1d-2d
P2 because it doesn't break compat with Desktop, but could potentially lead people down the wrong path.

@hughbe are you interested in this one?

**Comment by karelz** [comment]
Should be fairly straightforward. Would be nice to have a test or two.

**Comment by ViktorHofer** [comment]
Ah that's a good one! Validation is missing in Core because implementation is missing for some headers!!! E.g. Host isn't implemented in core:

```
if (!string.IsNullOrEmpty(connection))
            {
                //hwr.Connection = connection; // TODO #11881: Uncomment once member is available
            }

            if (!string.IsNullOrEmpty(expect))
            {
                //hwr.Expect = expect; // TODO #11881: Uncomment once member is available
            }

            if (!string.IsNullOrEmpty(referrer))
            {
                //hwr.Referer = referrer; // TODO #11881: Uncomment once member is available
            }

            if (!string.IsNullOrEmpty(userAgent))
            {
                //hwr.UserAgent = userAgent; // TODO #11881: Uncomment once member is available
            }

            if (!string.IsNullOrEmpty(host))
            {
                //hwr.Host = host; // TODO #11881: Uncomment once member is available
            }
```

**Comment by davidsh** [comment]
>@davidsh @stephentoub I'm not well into System.Net in Core yet. Why is HttpWebRequest implemented completely different than on netfx? Is it a reimplementation and not a port? Why are there a lot of members not implemented? Is there any specific reason behind it?

The HTTP stack is completely different between .NET Framework and .NET Core.

.NET Framework HTTP stack started with HttpWebRequest APIs which implemented HTTP protocol completely on top of managed Sockets.   HttpClient was introduced in .NET 4.5 and was a layer on top.

In .NET Core, we decided to not port that original HTTP stack from .NET Framework (long story).  We implemented something different in the HttpClientHandler/WinHttpHandler for HttpClient.  Those are the main handlers (i.e. the actual HTTP stack).

We then implemented HttpWebRequest which is considered a legacy API surface as a layer on top of HttpClient.

**Comment by davidsh** [comment]
And historically HttpWebRequest was not in the Windows Store App profile completely.  It was a stripped down API surface.  This is how the Windows Store apps for Windows 8/8.1 started out.  A lot of .NET was trimmed down for that.   Then we decided a few years later to add back the API surface for Store profile.  This is part of .NET Core work and .NET Core 2.0 for UWP work (.NET Core 2.1 release)

**Comment by ViktorHofer** [comment]
Alright, thanks for the explanation. I guesses that it would be that... I will diff the sources and check what needs to be pulled in to have both a fully functional HttpWebRequest and WebClient impl which behave the same as Desktop. Currently they are strongly diverging

**Comment by CIPop** [comment]
@davidsh We have an ActiveIssue in WebClient. Is this fixed now?

**Comment by Petermarcu** [comment]
Any update on this. Are we still considering this for 2.0.0 or should it be 2.1?

**Comment by davidsh** [comment]
This was fixed back in April with Viktor's PR #19118.

**Comment by Petermarcu** [comment]
Ok, I'm closing this then.

**Comment by CIPop** [comment]
@davidsh @Petermarcu I reopened because there is still an [ActiveIssue with this bug ID ](https://github.com/dotnet/corefx/blob/6f10c8b6823ed4736fde3c5940d6001fc7d30ad9/src/System.Net.WebClient/tests/WebClientTest.cs#L392) that I'm removing in my PR #21742 (I verified that the test runs fine).
