### ISSUE TITLE
BuildAllConfigurations and IsDesktopFacade don't play well together

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#18697]
An example of this is System.Security.Principal.Windows.

If you do:
`build.cmd -framework=netfx`
The correct facade ends up under `bin\ref\netfx` from the source build.
The ref gets bin-placed by https://github.com/dotnet/corefx/blob/master/dir.targets#L55

if you do:
`build.cmd -allconfigurations`

The netstandard ref for this assembly ends up under `bin\ref\netfx` which is incorrect. 
The ref gets bin-placed by https://github.com/dotnet/corefx/blob/master/dir.targets#L109

We should consider doing away with IsDesktopFacade completely to help eliminate all this special casing.

**Comment by ericstj** [comment]
The only downside of doing away with IsDesktopFacade is that we lose the ApiCompat check between NETStandard and desktop for these libraries and we have some manual authoring for the ref.  That said, having a ref facade is better since it doesn't duplicate IL bodies in the reference assembly.  It's also more WYSIWYG.

**Comment by ericstj** [comment]
Chatted with @weshaggard and he pointed out we still do a netstandard2x (all) -> netfx API compat run.  That will catch any cases where we were missing type-forwards / members.

That seals the deal for me.  I'm removing IsDesktopFacade.

I'm going to look into wether or not I can get GenFacades to produce the ref-facade automatically, similar to the way we do additive type-forwards for Partial-Facade generation, I'd like to do subtractive type-forwards for ref-facade generation.

**Comment by weshaggard** [comment]
>Chatted with @weshaggard and he pointed out we still do a netstandard2x (all) -> netfx API compat run. That will catch any cases where we were missing type-forwards / members.

Just to be safe can you please test this by excluding some type-forwards in one of your conversions.

**Comment by ericstj** [comment]
Confirmed that we catch missing types-forwards, missing members on forwarded types, missing OOB types, and missing members on OOB types.
