### ISSUE TITLE
Port S.S.Cryptography.Primitives changes to netfx

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#18690]
* AsymmetricAlgorithm validates against the LegalKeySizesValue field instead of the LegalKeySizes property. https://github.com/dotnet/corefx/issues/18475
* KeyedHashAlgorithm.Key (set/get) do not handle null well. https://github.com/dotnet/corefx/issues/18477
* SymmetricAlgorithm.set_Key permits large keys by mistake

**Comment by bartonjs** [comment]
Netfx, so closing.

**Comment by karelz** [comment]
@AlexGhiondea we edited the text of top post, after the bug was marked as netfx-port-consider. Is the updated text going to show up in the mirror? (or point me to db and I can check ;-))
