### ISSUE TITLE
Update Crypto API's to support Span<T>

### ISSUE THREAD

**Issue by Drawaes** [dotnet/corefx#18693]
As they take byte[], offset, length in a number of places which are then checked and fixed then often passed to a native call, as well as pretty much all being Sync in nature (CPU or Memory bound) they seem like ideal candidates.

This should increase safety/reduce checks (no need to check that length is past the array etc) and reduce the number of copies/interim arrays that are needed to be created. Will need an API review.

I realize this is a future task, just making sure it's logged.

**Comment by bartonjs** [comment]
@Drawaes Yes, I'm very much looking forward to taking Span.

**Comment by Drawaes** [comment]
I figured you would be. It's merely an issue for tracking in the future not a complaint or push :)

**Comment by karelz** [comment]
For now tracked by #13892
