### ISSUE TITLE
Can the System.IO namespace be modified to manipulate device handles?

### ISSUE THREAD

**Issue by zippy1981** [dotnet/corefx#187]
This assumes the `System.IO` and 'Microsoft.Win32.SafeHandles' namespace are being open sourced in CoreFX. If not close this ticket.

Right now if you do the following:

```
var handle = File.Open("\\\\.\\Global\\ProcmonDebugLogger", FileMode.Append);
```

You get an exception **FileStream will not open Win32 devices such as disk partitions and tape drives. Avoid use of "\.\" in the path.** If you want raw device access, you need to use P/Invoke. I propose the following:

```
public sealed class Microsoft.Win32.SafeHandles.SafeDeviceHandle: SafeHandleZeroOrMinusOneIsInvalid { . . . }
public static Microsoft.Win32.SafeHandles.SafeFileHandle System.IO.File.OpenHandle(string path) { 
    public bool DeviceIoControl( . . .) { . . . }
}
public static Microsoft.Win32.SafeHandles.SafeDeviceHandle System.IO.File.OpenDeviceHandle(string path) { . . .}
```

My use case for this would be to remove the [PInvoke functons from ProceMonDebugOutput](https://github.com/Wintellect/ProcMonDebugOutput/blob/master/Source/Sysinternals.Debug/NativeMethods.cs) by @JohnWintellect.

**Comment by ellismg** [comment]
Marking this as "enhancement" as it wasn't obvious that doing so would introduce new surface area.

**Comment by JeremyKuhne** [comment]
I removed the check for \\.\ in .NET 4.6.2 if you're running in full trust. There is still a block if the handle is something other than FILE_TYPE_DISK.

**Comment by JeremyKuhne** [comment]
It doesn't seem like we have any similar restrictions in Unix. I'd like to see the restriction removed or at least tightened.

My only concern is the implicit translation from `CON` to `\\.\CON` by GetFullPathName.  To avoid accidentally opening the legacy devices I think we could take an easy first step: skip the check if you're using `\\?\` instead of `\\.\`. `CON` will never get turned into `\\?\CON`.

**Comment by JeremyKuhne** [comment]
The recommendation (as per #8664) is to allow other CreateFile types (Pipes/Mailslots) when using `\\?\` syntax only. On all supported Windows versions there isn't additional security exposure by doing this, but even so, on desktop we only allow `\\?\` in full trust.

In investigating this I also discovered that our check for async on handles isn't accurate- there is an API to get the ground truth for the handle as opposed to attempting to r/w 0 bytes. I intend to switch to that API where possible.

**Comment by terrajobst** [comment]
@JeremyKuhne it seems we need a concrete proposal. We need to understand that whether we can do this for .NET Framework compatibly or not, and what other issues we have with accepting these paths.

Generally, it seems to follow the Unix spirit to accept strings rather than opening handles via a different API. But I think we're fine either way, so long we can make the change...

**Comment by JeremyKuhne** [comment]
@terrajobst Yes, it would be compatible. To err on the side of compatibility on desktop the pass through of all `\\?\` string handle types and utilization of the direct handle check for async would be behind an AppContext switch.

One question that has been brought up was access to raw devices (e.g. the underlying drive). These already come back as "File" types so the handle block doesn't apply. The lack of `\\?\` support also was already removed in 4.6.2. Finally, the original risk was a factor of too generous permissions on the root objects in much earlier versions of NT- you can't get at them without full admin rights in XP/Vista and beyond. (So the original concern isn't a problem anymore and is blocked in limited trust in any case.)

**Comment by JeremyKuhne** [comment]
@terrajobst 

They should not block other handle types for \\?\ strings. We already allow \\?\. No API surface change, just functional.

**Comment by terrajobst** [comment]
Sounds good.

**Comment by karelz** [comment]
BTW: There is somewhat-active PR from @JeremyKuhne - see #8664

**Comment by danmosemsft** [comment]
@JeremyKuhne is there any work left here after #8664 ? Seems not?

**Comment by JeremyKuhne** [comment]
I'll resurrect the old change to finish this.
