### ISSUE TITLE
IsolatedStorageFile.GetStore overloads should not throw PlatformNotSupportedException

### ISSUE THREAD

**Issue by billwert** [dotnet/corefx#18706]
This is a compat with desktop issue. Currently the only overload that is supported is GetStore(IsolatedStorageScope). We should consider the most sensible fallback possible for the other overloads. Code that happened to call ```IsolatedStorageFile.GetStore(System.IO.IsolatedStorage.IsolatedStorageScope.User | System.IO.IsolatedStorage.IsolatedStorageScope.Assembly,null,null)```, which is the same thing as calling ```GetUserStoreForAssembly()``` doesn't have to fail.

**Comment by billwert** [comment]
These overloads are also supported on Mono.

**Comment by ianhays** [comment]
Seems reasonable.
