### ISSUE TITLE
Desktop: System.Security.Cryptography.Cng.Tests.ECDsaCngTests.TestVerify521_EcdhKey failed with "System.ArgumentException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18719]
Failed test: System.Security.Cryptography.Cng.Tests.ECDsaCngTests.TestVerify521_EcdhKey

Configration: outerloop_netfx_windows_nt_debug

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/26/testReport/System.Security.Cryptography.Cng.Tests/ECDsaCngTests/TestVerify521_EcdhKey/

MESSAGE:
~~~
System.ArgumentException : Keys used with the ECDsaCng algorithm must have an algorithm group of ECDsa.
     Parameter name: key
~~~
STACK TRACE:
~~~
at System.Security.Cryptography.ECDsaCng..ctor(CngKey key) 
at System.Security.Cryptography.Cng.Tests.ECDsaCngTests.TestVerify521_EcdhKey() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Cryptography.Cng\tests\ECDsaCngTests.cs:line 93
~~~

**Comment by krwq** [comment]
@bartonjs this doesn't repro on my box, have you seen any fix in the last few days which could've fixed it? I'm only seeing two fixes coming in - one is unrelated and the other one not sure: https://github.com/dotnet/corefx/commit/7a7bf2e0cb40168c8819d84c66c99c8984746e02 . I've manually run it multiple times to see if there are any obvious intermittent failures in this projects but I got consistent same number of tests failing - also verified if the input might possibly be causing some intermittent failiures but it seems to be cloned before modifying

**Comment by bartonjs** [comment]
It's a 4.6.2 fix which isn't a retargeting fix.  You'd need to have a machine which has 4.6.1 installed but not 4.6.2.

**Comment by krwq** [comment]
@bartonjs should we leave the test as is then or is there some simple runtime check I could do to verify what machine I'm on? Not sure how do we test those kind of changes

**Comment by krwq** [comment]
either way, i do not believe this is blocking 2.0

**Comment by bartonjs** [comment]
I think we still have a general goal of having the test board green so we understand if we're regressing during release-branch fixes.  So we should probably still for ZBB target having the test either just not run on desktop or run and do complicated things to figure out if it thinks it should have passed or not.

**Comment by bartonjs** [comment]
>  is there some simple runtime check I could do

@AlexGhiondea I don't suppose we have a good/standard way of determining what netfx we have for non-quirked compat tests?

> Not sure how do we test those kind of changes

Probably we should take the line that's failing (https://github.com/dotnet/corefx/blob/ff08c4a41a57d18bed6c134dacaac990333b4f5d/src/System.Security.Cryptography.Cng/tests/ECDsaCngTests.cs#L93) and move it into something more complicated like

```C#
ECDsa ecdsaFromEcdhKey = null;

try
{
    ecdsaFromEcdhKey = new ECDsaCng(ecdh521);
}
catch (CryptographicException) when (IsDesktop && AlexsCodeSaysWeAreOn461OrLower)
{
    return;
}

using (ecdsaFromEcdhKey)
{
    ...
}
```

We could leave out the version check and just say that netfx is allowed to fail if we need to.

**Comment by AlexGhiondea** [comment]
Let's chat tomorrow (OOF today). I think there is a way to do this nicely :).
