### ISSUE TITLE
System.Text.Encoding.CodePages test relies on order of test execution

### ISSUE THREAD

**Issue by FiveTimesTheFun** [dotnet/corefx#1872]
The System.Test.Encoding.CodePages TestDefaultCodePage test relies on being the first test in the class to be executed and sets static state, which fails on new versions of xunit.

**Comment by Clockwork-Muse** [comment]
... Created a PR dealing with this specific issue.  Tests no longer care about order of execution.  

Potentially they should be expanded, to deal with differences in code pages (ie, a number of them use different currency symbols), but that wasn't part of this, so...

**Comment by Clockwork-Muse** [comment]
@FiveTimesTheFun - PR has been merged, you can close this issue.
