### ISSUE TITLE
Desktop: System.TypeLoadException : Could not load type 'System.Security.Cryptography.AesCng' from assembly 'System.Security.Cryptography.Cng'

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18720]
Failed test: System.Security.Cryptography.Encryption.Aes.Tests.AesModeTests.SupportsECB

Track issues under System.Sercurity.Cryptography failed with "System.TypeLoadException"

Detail: System.Security.Cryptography.Encryption.Aes.Tests.AesModeTests.SupportsECB

MESSAGE:
~~~
System.TypeLoadException : Could not load type 'System.Security.Cryptography.AesCng' from assembly 'System.Security.Cryptography.Cng, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
~~~
STACK TRACE:
~~~
at System.Security.Cryptography.Encryption.Aes.Tests.AesProvider.Create() 
at System.Security.Cryptography.Encryption.Aes.Tests.AesFactory.Create() 
in D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\Security\Cryptography\AlgorithmImplementations\AES\AesFactory.cs:line 18 
at System.Security.Cryptography.Encryption.Aes.Tests.AesModeTests.SupportsMode(CipherMode mode) in D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\Security\Cryptography\AlgorithmImplementations\AES\AesModeTests.cs:line 33 
at System.Security.Cryptography.Encryption.Aes.Tests.AesModeTests.SupportsECB() 
in D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\Security\Cryptography\AlgorithmImplementations\AES\AesModeTests.cs:line 22

**Comment by sepidehMS** [comment]
`System.Security.Cryptography.AesCng` doesn't have an implementation on netfx.  ([ApiCompatBaseline](https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Cng/src/ApiCompatBaseline.netfx.txt))
That's also the case for `System.Security.Cryptography.TripleDESCng`.

@safern Do we want to make these tests pass or do we move this to Future?

**Comment by safern** [comment]
This should be done for 2.0 as this is because the facade is missing some typeforwards since this types are available from 4.6.2 so I don't know why the facade is not being generated correctly. Maybe because netfx is targeted against 4.6.1

https://apisof.net/catalog/System.Security.Cryptography.AesCng

cc: @bartonjs @weshaggard

**Comment by bartonjs** [comment]
@ianhays Some more types in the Cng package that might be complicating matters :smile:.

@safern / @sepidehMS Are we executing on net461, net462, or net47?  That is: is this a facade problem, an execution environment problem, or both?

**Comment by weshaggard** [comment]
We currently generate the facades based on net461 which is the challenge here.

**Comment by safern** [comment]
As Wes said, this is a facade problem as the generation is based on 461, are we planning on moving yo to 462 or 47 any time soon?

**Comment by weshaggard** [comment]
>are we planning on moving to to create facades based on 462 or 47 any time soon?

You can actually generate the facades based on those today, just need to add that configuration in the cng project. However we only plan to have the net461 (aka netfx) test runs for this release in our automation so the tests will still need to be properly partitioned.

**Comment by safern** [comment]
I see, so netfx target generates the facades against 461 but we can actually add a later build configuration and partition the tests. What do you think @bartonjs, do you want me to take over this, add 462 and partition the tests to be included only when target group == netcoreapp and net462?

**Comment by ianhays** [comment]
>partition the tests to be included only when target group == netcoreapp and net462?

They should also be included if the TargetGroup == net47. That sounds like a good solution.

**Comment by safern** [comment]
Ok, I'll take over this one then.
