### ISSUE TITLE
ConsoleEncoding.InputEncoding_SetWithInInitialized_ResetsIn [FAIL]

### ISSUE THREAD

**Issue by shimingsg** [dotnet/corefx#18726]
test case failed on Ubuntu 16.04 when COMPlus_GCStress=2:

Exception from RemoteExecutorConsoleApp(System.Console.Tests, Version=4.1.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb, ConsoleEncoding+<>c, <InputEncoding_SetWithInInitialized_ResetsIn>b__3_0):
Assembly: System.Console.Tests, Version=4.1.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb
Type: ConsoleEncoding+<>c
Method: Int32 <InputEncoding_SetWithInInitialized_ResetsIn>b__3_0()
Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xunit.Sdk.NotSameException: Assert.NotSame() Failure
   at Xunit.Assert.NotSame(Object expected, Object actual)
   at ConsoleEncoding.<>c.<InputEncoding_SetWithInInitialized_ResetsIn>b__3_0()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at RemoteExecutorConsoleApp.Program.Main(String[] args)

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xunit.Sdk.NotSameException: Assert.NotSame() Failure
   at Xunit.Assert.NotSame(Object expected, Object actual)
   at ConsoleEncoding.<>c.<InputEncoding_SetWithInInitialized_ResetsIn>b__3_0()
   --- End of inner exception stack trace ---
   at RemoteExecutorConsoleApp.Program.Main(String[] args)
   ConsoleEncoding.InputEncoding_SetWithInInitialized_ResetsIn [FAIL]
      Assert.Equal() Failure
      Expected: 42
      Actual:   134
      Stack Trace:
            at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
            at ConsoleEncoding.InputEncoding_SetWithInInitialized_ResetsIn()

**Comment by karelz** [comment]
@shimingsg are you able to reproduce the failure?
Is it part of some new GCStress effort? Who drives it? (@danmosemsft or Serialization team)

**Comment by karelz** [comment]
@ianhays can you please check it out - if it is not product bug / not reproducible, feel free to move it out of 2.0.

**Comment by danmosemsft** [comment]
This may have nothing to do with console but instead the remote infra. Akin to https://github.com/dotnet/corefx/issues/16688. Which @ianhays is also looking at.

What is 134 -- I think seg fault was different -- @stephentoub  can you remind me how to look these up - what header and was some math involved (subtract 127?)

**Comment by stephentoub** [comment]
134 is typically SIGABRT (subtract 128). Most likely the process crashed with an unhandled exception, hit an assert(...) in a debug build of native code, received a SIGABRT issues by some other process, etc.

**Comment by danmosemsft** [comment]
GCSTress value would flow to the child process. Conceivably it coudl be stress related then. @shimingsg could you please loop this particular test under GCStress and see if yo ucan get a repro?

**Comment by danmosemsft** [comment]
For future ref @stephentoub is there a handy signal<->code table somewhere? I can't find one.

**Comment by stephentoub** [comment]
Only a handful of signals have portable numbers. You can see those in the table here:
https://en.m.wikipedia.org/wiki/Unix_signal
The others are implementing defined, e.g. for Linux see the table in the man page:
http://man7.org/linux/man-pages/man7/signal.7.html

**Comment by seanshpark** [comment]
I get this failure with debug version (CoreCLR and CoreFX) of AMD64/Linux (while working on x86/Linux and got this same failure)
```
~/netcore/corefx/bin/testhost/netcoreapp-Linux-Debug-x64/shared/Microsoft.NETCore.App/9.9.9/dotnet \
xunit.console.netcore.exe System.Console.Tests.dll  \
-xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests  \
-notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests \
-method ConsoleEncoding.InputEncoding_SetWithInInitialized_ResetsIn

xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Console.Tests
Discovered:  System.Console.Tests
Starting:    System.Console.Tests
>>> Console.InputEncoding 1 System.Text.UTF8Encoding+UTF8EncodingSealed
>>> Console.InputEncoding 2 System.Text.ASCIIEncoding+ASCIIEncodingSealed
>>> Object.ReferenceEquals True
Exception from RemoteExecutorConsoleApp(System.Console.Tests, Version=4.1.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb, ConsoleEncoding+<>c, <InputEncoding_SetWithInInitialized_ResetsIn>b__3_0):
Assembly: System.Console.Tests, Version=4.1.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb
Type: ConsoleEncoding+<>c
Method: Int32 <InputEncoding_SetWithInInitialized_ResetsIn>b__3_0()
Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xunit.Sdk.NotSameException: Assert.NotSame() Failure
   at Xunit.Assert.NotSame(Object expected, Object actual)
   at ConsoleEncoding.<>c.<InputEncoding_SetWithInInitialized_ResetsIn>b__3_0()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at RemoteExecutorConsoleApp.Program.Main(String[] args)

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xunit.Sdk.NotSameException: Assert.NotSame() Failure
   at Xunit.Assert.NotSame(Object expected, Object actual)
   at ConsoleEncoding.<>c.<InputEncoding_SetWithInInitialized_ResetsIn>b__3_0()
   --- End of inner exception stack trace ---
   at RemoteExecutorConsoleApp.Program.Main(String[] args)
   ConsoleEncoding.InputEncoding_SetWithInInitialized_ResetsIn [FAIL]
      Assert.Equal() Failure
      Expected: 42
      Actual:   134
      Stack Trace:
            at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
            at ConsoleEncoding.InputEncoding_SetWithInInitialized_ResetsIn()
Finished:    System.Console.Tests

=== TEST EXECUTION SUMMARY ===
   System.Console.Tests  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 0.804s
```

">>>" message are that I've added to find out the value
```
    [Fact]
    [SkipOnTargetFramework(TargetFrameworkMonikers.UapAot, "Issue https://github.com/dotnet/corefx/issues/18220")]
    public void InputEncoding_SetWithInInitialized_ResetsIn()
    {
        RemoteInvoke(() =>
        {
            // Initialize Console.In
            TextReader inReader = Console.In;
            Assert.NotNull(inReader);
            Assert.Same(inReader, Console.In);

            Console.WriteLine(">>> Console.InputEncoding 1 {0}", Console.InputEncoding);

            // Change the InputEncoding
            Console.InputEncoding = Encoding.ASCII;
            Console.WriteLine(">>> Console.InputEncoding 2 {0}", Console.InputEncoding);
            Assert.Equal(Encoding.ASCII, Console.InputEncoding);

            Console.WriteLine(">>> Object.ReferenceEquals {0}",
                Object.ReferenceEquals(inReader, Console.In));
            Assert.NotSame(inReader, Console.In);

            return SuccessExitCode;
        }).Dispose();
    }
```

Although `InputEncoding` is different, `inReader` and `Console.In` returns TRUE with `Object.ReferenceEquals()`. I don't know this is correct or not.
Do anyone know about this?

**Comment by danmosemsft** [comment]
@tarekgh

**Comment by Jiayili1** [comment]
This issue is repro on Core Tests, Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170502.01/workItem/System.Console.Tests/analysis/xunit/ConsoleEncoding~2FInputEncoding_SetWithInInitialized_ResetsIn

The test `ConsoleEncoding/InputEncoding_SetWithInInitialized_ResetsIn` has failed.

Assert.Equal() Failure\r
    Expected: 42\r
    Actual:   -532462766

        Stack Trace:

           at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
       at ConsoleEncoding.InputEncoding_SetWithInInitialized_ResetsIn()

**Comment by shimingsg** [comment]
get this error today, TestGCStressLevel=3:
  Exception from RemoteExecutorConsoleApp(System.Console.Tests, Version=4.1.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb, ConsoleEncoding+<>c, <InputEncoding_SetWithInInitialized_ResetsIn>b__3_0):
  Assembly: System.Console.Tests, Version=4.1.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb
  Type: ConsoleEncoding+<>c
  Method: Int32 <InputEncoding_SetWithInInitialized_ResetsIn>b__3_0()
  Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xunit.Sdk.NotSameException: Assert.NotSame() Failure
     at ConsoleEncoding.<>c.<InputEncoding_SetWithInInitialized_ResetsIn>b__3_0()
     --- End of inner exception stack trace ---
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     at RemoteExecutorConsoleApp.Program.Main(String[] args)

  Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xunit.Sdk.NotSameException: Assert.NotSame() Failure
     at ConsoleEncoding.<>c.<InputEncoding_SetWithInInitialized_ResetsIn>b__3_0()
     --- End of inner exception stack trace ---
     at RemoteExecutorConsoleApp.Program.Main(String[] args)
     ConsoleEncoding.InputEncoding_SetWithInInitialized_ResetsIn [FAIL]
        Assert.Equal() Failure
        Expected: 42
        Actual:   134
        Stack Trace:
              at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
  24
  80
  Finished:    System.Console.Tests

**Comment by danmosemsft** [comment]
@Jiayili1 two issues got mixed into one here.
This issue is about Unix.
Your comment here https://github.com/dotnet/corefx/issues/18726#issuecomment-298505991 is about Nano. Can you please open a new issue for that one.

**Comment by Jiayili1** [comment]
@danmosemsft I will open a new issue for it.
