### ISSUE TITLE
Config system should model versionless targetgroups as aliases

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#18736]
Today these are distinct nodes in the compatibility graph.

As a result `netstandard` isn't considered to be compatible with `netstandard2.0`, nor is `net461` nor `net462`.  This creates a maintainence problem.  We have to *remember* to keep the graph mappings correct.  This means that remapping the versionless targetgroups is not a simple task.

I'd like to fix this by treating the versionless identifiers as an alias.  This was my original intent with these, but we didn't do it because it required a code change rather than just props.

**Comment by ericstj** [comment]
I've implemented this but it may not be what we want.
https://github.com/ericstj/corefx/commit/748f7855677a99fde0c4b1cfc4a4db946f58afe3

It has the side-effect of always using the primary value, rather than the alias for the set value of the property.

That would prevent us from doing thinks like `'$(TargetGroup)' == 'netstandard'` since TargetGroup would never be set to `netstandard` instead it would be set to `netstandard2.0`.

I'm going to shelve this for now and move it to future since I don't think its something we need for 2.0.0.
/cc @weshaggard

**Comment by weshaggard** [comment]
That would be an unfortunate side effect. I didn't look deeply at your change but we should think about it a bit more and I agree we don't need it in 2.0.0.

Also as an aside I'm in the process of moving all these tasks to Buildtools.

**Comment by ericstj** [comment]
I've actually been thinking that the pattern of `'$(TargetGroup)' == 'netstandard'` might even be an anti-pattern because it creates more churn when doing updates like these:

Perhaps instead we should use things like TargetsNetStandard, TargetsNetCoreApp, TargetsNetFx, which are true for all targetgroups of the type.

Thoughts?

**Comment by weshaggard** [comment]
What would TargetsNetStandard imply? I don't think there is may cases were we would want it to mean any Netstandard version. We almost always want it to be some version or later. I don't know if there is a great way to model that with msbuild properties unless we generate a ton more properties for TargetsAtLeastTFMVx

**Comment by ericstj** [comment]
> We almost always want it to be some version or later

I disagree.  We typically only have one active build of a library and it will either "float" with new releases (keep using the versionless targetgroup), or "stick" in a particular release (moving from version-less to versioned, potentially keeping the versionless for vertical build).

**Comment by weshaggard** [comment]
So you don't think we will have any projects that both have a versioned and a version-less configuration? I think that will still used and in that case I don't know what TargetsNETCore/TargetsNETStandard would imply in those cases.

**Comment by wtgodbe** [comment]
@ericstj is there any update here?

**Comment by ericstj** [comment]
I think we can do this after we do some of the configuration work we've discussed where we avoid using TargetGroup in the projects.  Maybe I can start making some smaller changes in that direction.

**Comment by ViktorHofer** [comment]
This is done as we don't have versionless targetgroups anymore.
