### ISSUE TITLE
Nullable ValueTuple feedback

### ISSUE THREAD

**Issue by niemyjski** [dotnet/corefx#18745]
I get that this is a weird use case, but it's something the compiler allows me to do and I was even prompted by autocomplete to make my ValueTuple (a struct) nullable...

I was playing around with value tuples and in some cases I needed to return a null value (to say I can't handle it via a plugin). It was at this point autocomplete told me to make it nullable and did so for me. Granted this is the exact point in time, I should have created a class for this... But I was like ooh I can still have the pretty syntax and it works... I noticed that this quickly became a nightmare once I needed to handle null. I guess I was expecting destructuring to work and make my values null (if possible, or throw an compiler error if the tuple item type didn't support it)

```cs
        static void Main(string[] args)
        {
            (string subject, object data)? GetData() {
                return null;
            }

            /*
            Error	CS8130	Cannot infer the type of implicitly-typed deconstruction variable 'data'.
            Error	CS1061	'(string subject, object data)?' does not contain a definition for 'Deconstruct' and no extension method 'Deconstruct' accepting a first argument of type '(string subject, object data)?' could be found (are you missing a using directive or an assembly reference?)
            */
            (var subject, var data) = GetData();

            /*
            Error	CS1061	'(string subject, object data)?' does not contain a definition for 'Deconstruct' and no extension method 'Deconstruct' accepting a first argument of type '(string subject, object data)?' could be found (are you missing a using directive or an assembly reference?)
            Error	CS8129	No Deconstruct instance or extension method was found for type '(string subject, object data)?', with 2 out parameters and a void return type.
             */
            (string subject, object data) = GetData();

            // works
            var result = GetData();
            if (result == null || result.Value.subject == null)
                return;

            // Also I get that ValueTuple is a mutable struct.... This should work no?
            //Error CS1612  Cannot modify the return value of '(string subject, object data)?.Value' because it is not a variable
            result.Value.subject = result.Value.subject.ToLower();
        }
```

**Comment by niemyjski** [comment]
cc @jcouv

**Comment by jcouv** [comment]
Issue moved to [dotnet/roslyn #18885](https://github.com/dotnet/roslyn/issues/18885) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jcouv** [comment]
@niemyjski Thanks for the examples. I moved the issue to Roslyn repo and will take a look. In particular, the very last example (`CS1612` on assignment) surprised me too.

**Comment by niemyjski** [comment]
@jcouv thanks, what's interesting about that too is take a look at the intellisense, it's completely missing subject but data is there.
