### ISSUE TITLE
Consider bringing back System.Drawing API working cross-plattform

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#18752]
Consider bringing back System.Drawing API from netfx as identical as possible, working cross-plattform with whatever implementation.

Relates to:
https://github.com/dotnet/corefx/issues/18649
https://github.com/dotnet/corefx/issues/3634
https://github.com/dotnet/corefx/issues/2020
https://github.com/dotnet/corefx/issues/3778

cc: @danmosemsft @akoeplinger @terrajobst

**Comment by akoeplinger** [comment]
There's https://github.com/CoreCompat/System.Drawing from @qmfrederik which is a port of Mono's System.Drawing to .NET Core already.

**Comment by ViktorHofer** [comment]
Thanks @akoeplinger. Removed the "mono implementation" part from the description. Of course we shouldn't limit the discussion on Mono if there are already ports existing.

**Comment by qmfrederik** [comment]
Just to make this clear:
- The latest version of Mono's System.Drawing compiles on .NET Core 2.0, and all unit tests pass
- I package that code as CoreCompat.System.Drawing. There's a netstandard1.x NuGet package on NuGet right now, and I plan to publish one for .NET Core 2.0 once it hits preview (I guess early May?)
- Net, CoreCompat.System.Drawing really is "mono's implementation", packaged for .NET Core, by a 3rd party (me).
- That work has a dependency on libgdiplus
- The latest version of libgdiplus builds natively on about all Linux distro's plus macOS

So one way to resolve this would be to either just declar the CoreCompat package is enough, or have the Mono/.NET Core team re-publish the package as an "official" package.

As part of https://github.com/dotnet/standard/issues/222 @Petermarcu mentioned he's looking into the possibility of having netfx's version of System.Drawing available under an open source license; I don't know what the status is on that one.

**Comment by ViktorHofer** [comment]
Hea @qmfrederik, great to hear that! You say you already have a netstandard1x nuget package, would your netcore20 package also be able to target netstandard20?

**Comment by qmfrederik** [comment]
@ViktorHofer Yes, netstandard20 is supported as well.

**Comment by ViktorHofer** [comment]
AFAIK there was an announcement at build that it will be ported to .NET Core. Can't find the link currently. Closing...

**Comment by qmfrederik** [comment]
@ViktorHofer I saw some reference to the work planned for System.Drawing in the ASP.NET Core repository when they considered dropping support for NetFX, but I didn't see a formal announcement.

Could you provide us with some additional information about what's being planned? Is it based on Mono's System.Drawing or .NET's System.Drawing? Will it use libgdiplus on Linux and macOS?

Just trying to understand whether it makes sense to invest in those technologies from a contributor point of view, or whether the "new" System.Drawing solution will be based off another codebase alltogether.

Thanks!

**Comment by ViktorHofer** [comment]
I will try to find the official announcement somewhere. Just to clarify: I don't have any Insider information.

**Comment by ViktorHofer** [comment]
Ok, I can't find anything about it for now. I will Reopen the issue.

**Comment by qmfrederik** [comment]
From https://github.com/aspnet/Home/issues/2022:

@shanselman said [link](https://github.com/aspnet/Home/issues/2022#issuecomment-299536123):

> The remaining large gaps missing in .NET Core 2 are System.DirectoryServices and System.Drawing. We are working to have a Windows compat pack which would enable both of those on .NET Core on Windows this summer.

and [link](https://github.com/aspnet/Home/issues/2022#issuecomment-299536123)

> Drawing – Totally, this is a gap. We plan to have this for Core 2.0 around summer timeframe. Until this, these netstandard options also exist ImageSharp, ImageResizer, Mono options, etc

I think I at some point read that there will be first a Windows-only compat pack and then a cross platform one, but I can't find that statement anymore.

So any additional info would be welcome :)

**Comment by danmosemsft** [comment]
@mellinoe is the owner of this area now.

**Comment by karelz** [comment]
@mellinoe should we dupe it against your new #20325? Or is there any value I am missing in having 2 issues? Thanks!

**Comment by qmfrederik** [comment]
@ViktorHofer I think we can close this one for good, now that #20325 is tracking this work.

**Comment by ViktorHofer** [comment]
Thanks @qmdrfrederik
