### ISSUE TITLE
Add SafeFileHandle access for IStorageFolder and IStorageFile

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#18759]
With the Windows 10 Anniversary Update interfaces were added to `IStorageFolder` and `IStorageFile` to create a standard Win32 file handle. ([`IStorageFolderHandleAccess`](https://msdn.microsoft.com/en-us/library/mt765061(v=vs.85).aspx) and [`IStorageItemHandleAccess`](https://msdn.microsoft.com/en-us/library/mt765064(v=vs.85).aspx)) We should expose wrappers for the `Create` methods on these interfaces.

(Note that you explicitly have to request these through `IUnknown`)

## Rationale and Usage
Getting the Win32 handle allows richer interop with both .NET and other existing libraries. You can, for example, go straight to a .NET `FileStream` without complicated and potentially performance-sapping wrappers.

Exposing these methods is also a direct request from the Windows team.

Usage example:

``` C#
public void Foo(IStorageFile storageFile)
{
    SafeFileHandle handle = storageFile.CreateSafeFileHandle(FileAccess.Read);
    using (FileStream stream = new FileStream(handle, FileAccess.Read))
    {
       ...
    }
}
```

## Proposed API

We already have IO extension methods in [`System.IO.WindowsRuntimeStorageExtensions`](https://msdn.microsoft.com/en-us/library/system.io.windowsruntimestorageextensions(v=vs.110).aspx) (in `System.Runtime.WindowsRuntime.dll`). These would be added there.

``` C#
public static class WindowsRuntimeStorageExtensions
{
    public static SafeFileHandle CreateSafeFileHandle(
        this IStorageFile windowsRuntimeFile,
        FileAccess access = FileAccess.ReadWrite,
        FileShare share = FileShare.Read,
        FileOptions options = FileOptions.None) { ... }

    public static SafeFileHandle CreateSafeFileHandle(
        this IStorageFolder rootDirectory,
        string relativePath,
        FileMode mode)
    {
        return rootDirectory.CreateSafeFileHandle(relativePath, mode, (mode == FileMode.Append ? FileAccess.Write : FileAccess.ReadWrite));
    }

    public static SafeFileHandle CreateSafeFileHandle(
        this IStorageFolder rootDirectory,
        string relativePath,
        FileMode mode,
        FileAccess access,
        FileShare share = FileShare.Read,
        FileOptions options = FileOptions.None) { ... }
}
```
## Parameter Naming and Defaults
Parameters follow naming used in existing methods in `WindowsRuntimeStorageExtensions` and `FileStream`. `FileStream` defaults for constructors are the defaults here as well.

## Parameter Validation
| Exception | Case |
|---|---|
| ArgumentNullException | Thrown if `relativePath` is null |
| NotSupportedException | Thrown for `FileShare.Inheritable` and `FileOptions.Encrypted` |
| ArgumentOutOfRangeException | Thrown for any other undefined enum values |

Note that we explicitly allow `(FileOptions)0x20000000` (which is `NoBuffering`) as FileStream does.

We will not do other validation of incompatible combinations of enum values- we'll allow Windows to do this and surface whatever errors it returns.

## Error Handling
If the cast to `IStorageFolderHandleAccess` or `IStorageItemHandleAccess` fails for any reason we'll return null.

Failed HRESULTs returned from the methods will be converted into normal System.IO exceptions. (As [GetExceptionForWin32Error](http://source.dot.net/#System.Private.CoreLib/shared/System/IO/Win32Marshal.cs,8cf456a56c1e487e,references) would.)

## Other Notes
We will not support oplocks or `IOplockBreakingHandler`. We don't support oplocks elsewhere- any such support here should come in with general oplock support.

## Future Considerations
We should investigate converting the various `WindowsRuntimeStorageExtensions.OpenStreamFor*Async` extension methods to directly creating a FileStream via these new interfaces if possible. Adding additional non `Async` wraps should be considered as well.

**Comment by JeremyKuhne** [comment]
@ianhays, @danmosemsft Fyi

**Comment by danmosemsft** [comment]
@JeremyKuhne I assume yo'ull point Windows folk at this also

**Comment by JeremyKuhne** [comment]
@danmosemsft I've sent mail- I'll add the GitHub alias(es) once I know them (if they have them).

**Comment by ptorr-msft** [comment]
Thanks Jeremy!

**Comment by JeremyKuhne** [comment]
@ptorr-msft

**Comment by terrajobst** [comment]
Not sure I get the sample -- aren't you supposed to use the handle somewhere?

```C#
public void Foo(IStorageFile storageFile)
{
    SafeFileHandle handle = storageFile.CreateSafeFileHandle(FileAccess.Read);
    using (FileStream stream = new FileStream(FileAccess.Read))
    {
       ...
    }
}
```

**Comment by terrajobst** [comment]
It looks good to me.

@KrzysztofCwalina @weshaggard @ericstj ?

**Comment by ericstj** [comment]
What's the reasoning for us exposing these as extension methods rather than Windows just exposing a friendly API?  Can you point out the difference between how a user would do this without us adding extension methods vs with?

**Comment by KrzysztofCwalina** [comment]
There seems to be IStorageForlder2 interface too. Why? Which one should we support? https://docs.microsoft.com/en-us/uwp/api/windows.storage.istoragefolder2

**Comment by ptorr-msft** [comment]
@ericstj, WinRT APIs don't expose `HANDLE`s directly since they are not part of the WinRT type system (what would you do with a `HANDLE` in JavaScript, for example?). Similarly, WinRT APIs doesn't expose .NET types since they are meaningless in other languages / frameworks.

**Comment by ptorr-msft** [comment]
@KrzysztofCwalina, the interfaces are public because they are implemented by more than one runtime class (at least in theory, if not in practice). Most developers will code in terms of `StorageFile` or `StorageFolder` but sometimes you need to use one of the interfaces (or the more basic `IStorageItem`) because that's what you get from a different API. Ideally the extension methods would be on all of the different types

**Comment by karelz** [comment]
API review: We assume that these extension methods are convenience APIs only and that they are implementable just on top the interface (without casting to the underlying type).
If that's the case, we approve.

We need to make sure the Desktop implementation lights up (Desktop targets also older OS versions, incl. older Win10 versions like TH1/TH2/RS1).

**Comment by ericstj** [comment]
> WinRT APIs don't expose HANDLEs directly since they are not part of the WinRT type system (what would you do with a HANDLE in JavaScript, for example?). Similarly, WinRT APIs doesn't expose .NET types since they are meaningless in other languages / frameworks.

Handles are just opaque objects that are references to some other object.  They don't need to be natively supported to be useful.  The just need to be exposed and consumed by useful API.

I understand you'll have different type identities in WinRT.  I'm trying to gather if this is just a simple adapter layer where we are mapping WinRT types to the .NET equivalents or if we are doing fancy stuff in .NET because its not being done by WinRT.  An alternative to adapter is projected types but I would prefer the adapters given all the complexity around projected types.

**Comment by danmosemsft** [comment]
@JeremyKuhne note that @weshaggard believes that even modern Windows API usage in Core should be implemented via lightup in case people misuse the libraries on lower Windows versions than intended. Unsure whether we already do this in Core though so this might be a nic to have.

**Comment by ptorr-msft** [comment]
Windows provides the mapping from `IStorageItem` to `HANDLE` via the COM interface `IStorageItemHandleAccess` (existing feature since the Anniversary Update). 

.NET provides the mapping from HANDLE to `FileStream` (proposed new feature).

**Comment by JeremyKuhne** [comment]
> Not sure I get the sample

Whoops, added the handle

**Comment by JeremyKuhne** [comment]
> @weshaggard believes that even modern Windows API usage in Core should be implemented via lightup

This is a lightup feature- it will simply return null if you use the library pre RS3.

**Comment by danmosemsft** [comment]
@JeremyKuhne if this is just tracking port, I believe the protocol is to close it?

**Comment by JeremyKuhne** [comment]
It is currently in NetFX vnext.
