### ISSUE TITLE
Activity: StopActivity does not yet use the new more precise timestamp on the full framework

### ISSUE THREAD

**Issue by cwe1ss** [dotnet/corefx#18775]
#18651 introduced more precise timestamps for the full .net framework in the new Activity API. However, I think that there's one place missing in [StopActivity](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceActivity.cs#L44)

```csharp
if (activity.Duration == TimeSpan.Zero)
    activity.SetEndTime(DateTime.UtcNow);
```

@lmolkova @vancem

**Comment by vancem** [comment]
I believe @lmolkova  fixed this (your link above now points to fixed code).   Please reopen if this is not the case.

**Comment by cwe1ss** [comment]
Yes, this is fixed. thx!!
