### ISSUE TITLE
Enable tests for Environment.ExitCode

### ISSUE THREAD

**Issue by mazong1123** [dotnet/corefx#18776]
Based on this comment(https://github.com/dotnet/coreclr/issues/6206#event-1048947484), [the tests of Environment.ExitCode](https://github.com/dotnet/corefx/blob/0ebc867d6bad9d777dd61afb78d0445c86143b34/src/System.Runtime.Extensions/tests/System/Environment.Exit.cs#L52) should be enabled as the bug has been fixed in CoreCLR.

I'll work on this issue after https://github.com/dotnet/core-setup/issues/2050 resolved.

**Comment by karelz** [comment]
Assigned to you per your desire to work on it ...
