### ISSUE TITLE
How to check whether the PipeStream has data or not

### ISSUE THREAD

**Issue by ernest-morariu** [dotnet/corefx#18788]
In .NET, the pipe API doesn't expose any property the application can use in order to decide whether it's worth involving a Read operation or not. 

The other posts on this subject suggest using the async reading and CancellationToken for this. I don't like this very much because the Exception is intended to be used for exceptional cases only. Raising an OperationCancelledException every few milliseconds doesn't sound very appealing. 

Anyway, I tried that, as well. The reason I am writing this post is the fact that to me it seems the ReadAsync doesn't work either for this purpose. I guess this is because ReadAsync deals with unmanaged IO operations. IMO cancelling should, however, be possible when using PipeOptions.Asynchronous.

Please see the code below; it's the Main of a console application. The code contains comments explaining what are the actual and the expected behaviors. 

Thank you, Ernest. 

```csharp
// This is the Main of a console application
public void  Main()
{
    // This code is intended to verify if ReadAsync can be used to check the pipe doesn't have any data.
	
	string pipeName = "XYZ";
	
	// create the server (async)pipe and put it listenting mode
	var serverPipe = new System.IO.Pipes.NamedPipeServerStream(pipeName, System.IO.Pipes.PipeDirection.InOut,1,System.IO.Pipes.PipeTransmissionMode.Byte,System.IO.Pipes.PipeOptions.Asynchronous);
	var connWaiterTask = serverPipe.WaitForConnectionAsync();
	
	// create the client pipe and connect it to server. The client intentionally doesn't send any data to the server.
	var clientPipe = new System.IO.Pipes.NamedPipeClientStream("localhost", pipeName, System.IO.Pipes.PipeDirection.InOut); //, System.IO.Pipes.PipeOptions.Asynchronous);
	clientPipe.Connect();

        // prepare a cancellation source for ReadAsync
	System.Threading.CancellationTokenSource cts = new System.Threading.CancellationTokenSource();
	byte[] inBuffer = new byte[1];
	
	try
	{
                // invoke ReadAsync on the server pipe and immediately cancel the passed in cancellation token.
		var readAsyncTask =  serverPipe.ReadAsync(inBuffer,0,1, cts.Token);
		System.Threading.Thread.Sleep(50);
		cts.Cancel();  // cancel ReadAsync
		
		//clientPipe.WriteByte(1); // If the client sends some data, it unblocks the ReadAsync on server side 
		
		int n = readAsyncTask.Result; // The token is cancelled at this time, but ReadAsync doesn't seem to be aware of this. This line blocks indefinitely if the client doesn't send any data. 
	}
	finally
	{
		// The execution never gets here. Why?
		Console.WriteLine("FINISH");
	}
}
```

**Comment by ianhays** [comment]
I am unable to repro this on the latest netcoreapp. I put your sample code in a test and it passed with the "FINISH" printed out.
