### ISSUE TITLE
HttpWebRequest request stream returns different exceptions from Desktop

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#18787]
The request stream returned from `HttpWebRequest.GetRequestStream` is always a MemoryStream on .NET Core. On .NET Framework, it is a System.Net.ConnectStream (an internal class).

Due to this, there are small behavior difference w.r.t. the exception returned while doing argument checking:

See:
```c#
        [Fact]
        public void WriteAsync_OffsetPlusCountExceedsBufferLength_ThrowsArgumentException()
        {
            using (Stream stream = GetRequestStream())
            {
                if (PlatformDetection.IsFullFramework)
                {
                    // In .NET Framework, the request stream is a System.Net.ConnectStream
                    // which throws ArgumentOutOfRangeException in this case.
                    Assert.Throws<ArgumentOutOfRangeException>(() => { Task t = stream.WriteAsync(buffer, 0, buffer.Length+1); });
                }
                else
                {
                    // In .NET Core, the request stream is a System.IO.MemoryStream
                    // which throws ArgumentException in this case.
                    Assert.Throws<ArgumentException>(() => { Task t = stream.WriteAsync(buffer, 0, buffer.Length+1); });
                }
            }
        }

        [Fact]
        public void WriteAsync_OffsetPlusCountMaxValueExceedsBufferLength_Throws()
        {
            using (Stream stream = GetRequestStream())
            {
                if (PlatformDetection.IsFullFramework)
                {
                    // In .NET Framework, the request stream is a System.Net.ConnectStream
                    // which throws ArgumentOutOfRangeException in this case.
                    Assert.Throws<ArgumentOutOfRangeException>(() => { Task t = stream.WriteAsync(buffer, int.MaxValue, int.MaxValue); });

                }
                else
                {
                    // In .NET Core, the request stream is a System.IO.MemoryStream
                    // which throws ArgumentException in this case.
                    Assert.Throws<ArgumentException>(() => { Task t = stream.WriteAsync(buffer, int.MaxValue, int.MaxValue); });
                }
            }
        }
```

Discovered while investigating #17842 and related to #11873.

For app-compat, we should consider fixing this. The simplest fix would be to create a derived class of MemoryStream() and make sure all Write* methods are overridden with matching argument validation before calling the base methods.

**Comment by davidsh** [comment]
The specific argument validation done in .NET Framework for ConnectStream is:

```c#
            if (buffer==null) {
                throw new ArgumentNullException("buffer");
            }
            if (offset<0 || offset>buffer.Length) {
                throw new ArgumentOutOfRangeException("offset");
            }
            if (size<0 || size>buffer.Length-offset) {
                throw new ArgumentOutOfRangeException("size");
            }
```

This differs from MemoryStream.

**Comment by davidsh** [comment]
cc: @stephentoub @karelz @CIPop

**Comment by karelz** [comment]
Triage:
Catching the exceptions is rare. `ArgumentOutOfRangeException` would be better as it is more specific and likely being caught.

P2 for 2.0
Very simple fix.

**Comment by karelz** [comment]
@hughbe @WinCPP are you interested? It would be nice to have in 2.0 ...

**Comment by WinCPP** [comment]
@karelz Please assign it to me...

@davidsh Was trying to figure out the source of exception... Is it in this file ([link](https://github.com/dotnet/corefx/blob/e9ecf74d845476540f40fa8fdc62c53ebf048519/src/System.Net.Requests/src/System/Net/RequestStream.cs#L22))

I believe at [Line 22](https://github.com/dotnet/corefx/blob/e9ecf74d845476540f40fa8fdc62c53ebf048519/src/System.Net.Requests/src/System/Net/RequestStream.cs#L22) we want to assign new instance of the new derived class. It would have to be defined in the same project with a name, say, `MemoryStreamForRequest` and override `Write*` therein...

So wanted to confirm if I am looking into correct project / file... Thanks!

**Comment by davidsh** [comment]
@WinCPP Thank you for your interest in this.

In terms of what code to change, yes, you'll want to create a derived class of MemoryStream and override the Write* methods to do parameter validation and then call the base methods to do the actual work.

Please review this .NET Framework source to make sure you match behavior.  

https://github.com/Microsoft/referencesource/blob/master/System/net/System/Net/_ConnectStream.cs#L801

We'll also need new unit tests included in any PR.

**Comment by karelz** [comment]
Thanks @WinCPP!

**Comment by WinCPP** [comment]
@davidsh just asking... instead of creating a derived class of MemoryStream, how about doing the necessary validations that throw expected exceptions right in the RequestStream.Write* methods ([here](https://github.com/dotnet/corefx/blob/e9ecf74d845476540f40fa8fdc62c53ebf048519/src/System.Net.Requests/src/System/Net/RequestStream.cs#L100-L113))?

**Comment by davidsh** [comment]
>how about doing the necessary validations that throw expected exceptions right in the RequestStream.Write* methods (here)?

Yes, that is a better idea.  Please go with that.
