### ISSUE TITLE
Types missing [Serializable]

### ISSUE THREAD

**Issue by billwert** [dotnet/corefx#18780]
Based on #18704 I took a quick look at the rest of the .NET Core framework to find types that were marked [Serializable] in the desktop .NET Framework which are not marked so in .NET Core. I looked for 'serializable typename' in issues on CoreFX and CoreCLR and didn't find any hits on these to try and understand if these were known issues or by design and didn't come up with anything. (I also don't have a great way to split the list between CoreFX and CoreCLR, so I'm opening the issue here for all of them.)

The list:
Microsoft.VisualBasic.CompilerServices.IncompleteInitialization
Microsoft.VisualBasic.CompilerServices.InternalErrorException
Microsoft.VisualBasic.CompilerServices.StaticLocalInitFlag
System.AssemblyLoadEventHandler
System.Configuration.Assemblies.AssemblyHashAlgorithm
System.Configuration.Assemblies.AssemblyVersionCompatibility
System.Globalization.CultureTypes
System.Globalization.DateTimeStyles
System.Globalization.DigitShapes
System.Globalization.NumberStyles
System.Globalization.UnicodeCategory
System.IO.FileMode
System.IO.FileOptions
System.IO.FileShare
System.IO.SeekOrigin
System.LoaderOptimization
System.Reflection.Assembly
System.Reflection.AssemblyContentType
System.Reflection.AssemblyNameFlags
System.Reflection.Binder
System.Reflection.BindingFlags
System.Reflection.CallingConventions
System.Reflection.ConstructorInfo
System.Reflection.EventAttributes
System.Reflection.EventInfo
System.Reflection.FieldAttributes
System.Reflection.FieldInfo
System.Reflection.ImageFileMachine
System.Reflection.MemberFilter
System.Reflection.MemberInfo
System.Reflection.MemberTypes
System.Reflection.MethodAttributes
System.Reflection.MethodBase
System.Reflection.MethodImplAttributes
System.Reflection.MethodInfo
System.Reflection.Module
System.Reflection.ModuleResolveEventHandler
System.Reflection.ParameterAttributes
System.Reflection.ParameterInfo
System.Reflection.PortableExecutableKinds
System.Reflection.ProcessorArchitecture
System.Reflection.PropertyAttributes
System.Reflection.PropertyInfo
System.Reflection.ResourceAttributes
System.Reflection.ResourceLocation
System.Reflection.TypeAttributes
System.Reflection.TypeFilter
System.Reflection.TypeInfo
System.ResolveEventHandler
System.Resources.UltimateResourceFallbackLocation
System.Runtime.CompilerServices.MethodImplOptions
System.Runtime.InteropServices.CallingConvention
System.Runtime.InteropServices.CharSet
System.Runtime.InteropServices.LayoutKind
System.Runtime.InteropServices.UnmanagedType
System.Runtime.InteropServices.VarEnum
System.Runtime.Serialization.StreamingContextStates
System.Text.RegularExpressions.MatchEvaluator
System.Threading.ApartmentState
System.Threading.ThreadPriority
System.Threading.ThreadState
System.Type

**Comment by stephentoub** [comment]
Thanks, Bill. Note that while we've tried to keep attribution of enums for consistency, it's not actually necessary.; looks like that's maybe half of the list. For the rest, I'm fairly certain we examined at least some of those cases as part of doing a similar exercise previously, so it'd be interesting to understand if something regressed, if your list has false positives, or we simply missed something. Also note that in a few cases, the type may be duplicated between coreclr and corefx, in which case it could be the work has been done for coreclr but not corert yet. Regardless, if you want to take a first pass through, that'd be helpful. Otherwise I can take a look next week.

**Comment by billwert** [comment]
Yah, it's not my expectation that all of these are actually bugs. It was easy enough to produce the list.

This is done from metadata on binaries, not source, so hopefully duplication isn't a problem.



Get Outlook for iOS<https://aka.ms/o0ukef>
_____________________________

**Comment by jkotas** [comment]
> attribution of enums for consistency, it's not actually necessary

The same is true for delegates. Delegates are serializable by default.

**Comment by karelz** [comment]
cc @danmosemsft who was looking on serialization attributes AFAIK ...

**Comment by billwert** [comment]
Is there a downside to bringing the consistency even if it isn't required? I wonder if the schism causes any documentation problems If we have types on Desktop and CoreFX that differ in attributes does that cause trouble? (@mairaw). I also wonder if there are other tools etc that depend on this metadata in the ecosystem.

Put differently: How do we describe the upside of these changes (in the places where they are not obvious bugs)?

**Comment by jkotas** [comment]
More unnecessary cruft. However, we have a ton of cruft already, so a tiny bit more won't register on the radar.

**Comment by stephentoub** [comment]
> However, we have a ton of cruft already, so a tiny bit more won't register on the radar.

Yeah, I plan to bring it back to all of these.  I'm just out of the office for a few days and have only had intermittent spurts to work on it amongst other things.  If we subsequently decide to remove [Serializable] from places it's not actually needed, we can do it in one full sweep.

**Comment by stephentoub** [comment]
Closing in favor of #19119
