### ISSUE TITLE
IList-Reverse bug

### ISSUE THREAD

**Issue by jackzhenguo** [dotnet/corefx#18798]
IList<int> test = new List<int>() {0, 4, 9};
test.Reverse(); //it's failure

**Comment by JasonBock** [comment]
Works just fine for me:
```
Microsoft (R) Roslyn C# Compiler version 2.1.0.61520
Loading context from 'CSharpInteractive.rsp'.
Type "#help" for more information.
> var t = new List<int> { 0, 4, 9 };
> t.Reverse();
> t
List<int>(3) { 9, 4, 0 }
> 
```

**Comment by jackzhenguo** [comment]
I declare the t: IList<int>.  IList<int> t = new List<int>{0,4,9}; 
So try this. Thank you!

**Comment by jackzhenguo** [comment]
`IList<int> t = new List<int>{0,4,9}`

**Comment by davidfowl** [comment]
This should work:

```C#
IList<int> t = new List<int>{0,4,9};
foreach (var item in t.Reverse())
{
     Console.WriteLine(item);
}
```

- `List<T>.Reverse()` actually mutates the list.
- `IList<T>` doesn't have a `Reverse()` method, you're calling `Enumerable.Reverse()` which returns a reversed `IEnumerable<T>` but doesn't change the underlying list. That's likely what you're running into.

It's a pretty common problem people hit http://stackoverflow.com/questions/12390971/why-there-is-two-completely-different-version-of-reverse-for-list-and-ienumerabl.
