### ISSUE TITLE
Desktop: System.Runtime.InteropServices.Tests.SafeArrayTypeMismatchExceptionTests.SerializationRoundTrip failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18797]
Failed test: System.Runtime.InteropServices.Tests.SafeArrayTypeMismatchExceptionTests.SerializationRoundTrip

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/System.Runtime.InteropServices.Tests/SafeArrayTypeMismatchExceptionTests/SerializationRoundTrip/

Configuration: outerloop_netfx_windows_nt_debug

MESSAGE:
~~~
Assert.Equal() Failure
      ↓ (pos 266)
     Expected: ···tterHelpers.cs:line 31
     Actual: ···tterHelpers.cs:line 26
      ↑ (pos 266)
~~~
STACK TRACE:
~~~
at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterHelpers.AssertRoundtrips[T](T expected, Func`2[] additionalGetters) 
in D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\Runtime\Serialization\Formatters\BinaryFormatterHelpers.cs:line 39 
at System.Runtime.InteropServices.Tests.SafeArrayTypeMismatchExceptionTests.SerializationRoundTrip()
in D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServices\SafeArrayTypeMismatchExceptionTests.cs:line 18
~~~

**Comment by safern** [comment]
This looks as a very specific .Net Core test as it includes the file line should we change the test to instead of doing an Assert.Equal do an `Assert.Contains("FormatterHelpers.cs")` because the files could change and can be different in between target frameworks. 

cc: @danmosemsft

**Comment by safern** [comment]
Future as this looks more like test bug.
