### ISSUE TITLE
tizen builds fail with parser error

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#18794]
```
04:47:11 Build RootFS for armel tizen
04:47:11 + sudo docker run --privileged -i --rm -v /mnt/j/workspace/dotnet_corefx/master/tizen_armel_cross_release_prtest:/opt/corefx -w /opt/corefx t2wish/dotnetcore:ubuntu1404_cross_prereqs_v2 ./cross/build-rootfs.sh armel tizen --skipunmount
04:47:12 >>Start downloading files
04:47:12 [0;34mInitialize arm base[m
04:47:12 /opt/corefx/cross/rootfs/armel/tizen_tmp/tizen_base_pkgs/build.xml:6: parser error : Opening and ending tag mismatch: hr line 5 and body
04:47:12 </body>
04:47:12        ^
04:47:12 /opt/corefx/cross/rootfs/armel/tizen_tmp/tizen_base_pkgs/build.xml:7: parser error : Opening and ending tag mismatch: body line 3 and html
04:47:12 </html>
04:47:12        ^
04:47:12 /opt/corefx/cross/rootfs/armel/tizen_tmp/tizen_base_pkgs/build.xml:8: parser error : Premature end of data in tag html line 1
04:47:12 + handle_exit
04:47:12 + set +x
```
https://ci.dot.net/job/dotnet_corefx/job/master/job/tizen_armel_cross_debug_prtest/1511/console

**Comment by danmosemsft** [comment]
@parjong @hqueue @hseok-oh @jyoungyun

**Comment by hseok-oh** [comment]
https://ci.dot.net/job/dotnet_corefx/job/master/job/tizen_armel_cross_debug_prtest/1511 ~ https://ci.dot.net/job/dotnet_corefx/job/master/job/tizen_armel_cross_debug_prtest/1516 show build fail as same reason. 
And https://ci.dot.net/job/dotnet_coreclr/job/master/job/armel_cross_debug_tizen_prtest/1552/ ~ https://ci.dot.net/job/dotnet_coreclr/job/master/job/armel_cross_debug_tizen_prtest/1555/ also print same result.
I don't know the correct reason, but it seems network issue.

**Comment by jyoungyun** [comment]
@danmosemsft 
- period :  4/15 08:00 ~ 4/23 24:00 KST (9days including working day)
During this period, the Tizen server was unstable due to the build infra migration. It seems that there is no problem since it is now returned to normal. :)

**Comment by hqueue** [comment]
I also confirm that this is due to server failure of Tizen server and not related to ARM CI for Tizen.
https://lists.tizen.org/pipermail/dev/2017-April/007278.html
>   .Weekend(Sat~Sun)                 23:00(Fri) ~ 13:00(sat) UTC

Tizen build seems to work well now.

**Comment by karelz** [comment]
Looks like it is resolved. Please let me know if I misunderstood or reopen.
