### ISSUE TITLE
Desktop: Tests under "System.Diagnostics.Tracing.Tests.BasicEventSourceTests" failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18805]
Failed tests:
 BasicEventSourceTests.TestsWrite.Test_Write_T_EventListener
 BasicEventSourceTests.TestsWrite.Test_Write_T_EventListener_UseEvents
 BasicEventSourceTests.TestsUserErrors.Test_BadEventSource_MismatchedIds

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/BasicEventSourceTests/TestsWrite/Test_Write_T_EventListener/

Configuration: outerloop_netfx_windows_nt_debug

MESSAGE:
~~~
Assert.Equal() Failure
     ↓ (pos 0)
    Expected: 
    Actual: System.Threading.SynchronizationEventSour···
     ↑ (pos 0)
~~~
STACK TRACE:
~~~
at BasicEventSourceTests.TestUtilities.CheckNoEventSourcesRunning(String message) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestUtilities.cs:line 34 
at BasicEventSourceTests.TestsWrite.Test_Write_T(Listener listener) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestsWrite.cs:line 80 
at BasicEventSourceTests.TestsWrite.Test_Write_T_EventListener() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestsWrite.cs:line 46
~~~

**Comment by danmosemsft** [comment]
@brianrob is this expected on Desktop? What's the appropriate change? eg., if on desktop, ignore that event source?

**Comment by danmosemsft** [comment]
ping @brianrob @lmolkova we only have a few days :)
