### ISSUE TITLE
Tests under "System.Diagnostics.Tracing.Tests.BasicEventSourceTests" failed with "System.TypeLoadException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18807]
Failed test: BasicEventSourceTests.TestsManifestNegative.Test_GenerateManifest_InvalidEventSources

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/BasicEventSourceTests/TestsManifestNegative/Test_GenerateManifest_InvalidEventSources/

MESSAGE:
~~~
System.TypeLoadException : Could not load type 'System.SR' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
~~~
STACK TRACE:
~~~
at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type) 
at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase) 
at BasicEventSourceTests.TestsManifestNegative.GetResourceStringFromReflection(String key) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestsManifestNegative.cs:line 34 
at BasicEventSourceTests.TestsManifestNegative.GetResourceString(String key, Object[] args) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestsManifestNegative.cs:line 24 
at BasicEventSourceTests.TestsManifestNegative.Test_GenerateManifest_InvalidEventSources() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestsManifestNegative.cs:line 54
~~~

**Comment by danmosemsft** [comment]
@safern this is a test issue, it's doing
`            Type sr = typeof(EventSource).Assembly.GetType("System.SR", throwOnError: true, ignoreCase: false);`
this will not work on desktop framework where there is no System.SR type. It loads resources via text.

This whole test `Test_GenerateManifest_InvalidEventSources`  must be disabled or rewritten. @lmolkova is is reasonable for @safern to disable this test for desktop?

**Comment by safern** [comment]
If @lmolkova is ok on disabling it I will be happy to do so.

**Comment by lmolkova** [comment]
@danmosemsft probably I'm the wrong person for that, I do not know much about EventSource, @vancem could you help  with it?

**Comment by vancem** [comment]
@brianrob  who owns EventSource.  

It would be useful, however to understand how this failure is occurring at this point in time.  Are we running new tests or on different platforms that we weren't before?

**Comment by safern** [comment]
This is running against netfx which is 461. We just started running test against Desktop to make sure we are as compatible as possible in between desktop and core

**Comment by vancem** [comment]
We can certainly disable this one on desktop for now (since this is strictly better coverage than we were getting say a month ago).

**Comment by safern** [comment]
Ok so I will go ahead and disable this one. Thanks
