### ISSUE TITLE
Desktop: System.Security.Permissions.Tests.SecurityElementTest.Attributes_Name_Invalid_MS failed with "System.InvalidCastException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18815]
Failed test: System.Security.Permissions.Tests.SecurityElementTest.Attributes_Name_Invalid_MS

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/System.Security.Permissions.Tests/SecurityElementTest/Attributes_Name_Invalid_MS/

MESSAGE:
~~~
Assert.Throws() Failure
     Expected: typeof(System.ArgumentException)
    Actual: typeof(System.InvalidCastException): Unable to cast object of type 'System.Collections.DictionaryEntry' to type 'System.String'.
~~~
STACK TRACE:
~~~
at System.Security.SecurityElement.set_Attributes(Hashtable value) 
at System.Security.Permissions.Tests.SecurityElementTest.<>c__DisplayClass19_0.<Attributes_Name_Invalid_MS>b__0() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Permissions\tests\SecurityElementTests.cs:line 297
~~~

**Comment by danmosemsft** [comment]
@safern as mentioned please disable the entire System.Security.Permissions.Tests assembly for desktop. The tests are all bogusly verifying our stubs and will never pass on desktop and that's fine.

**Comment by safern** [comment]
I just ran the tests and only seeing 33 failures, should we really disable the whole test assembly? I am curious because System.Security.Permissions is shipped in the 461 netfx package. (it has a pkgproj that targets 461)

**Comment by Jiayili1** [comment]
This issue is repro on Full Framework Tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170426.01/workItem/System.Security.Permissions.Tests/analysis/xunit/System.Security.Permissions.Tests.SecurityElementTest~2FAttributes_Name_Invalid_MS
