### ISSUE TITLE
Desktop: System.IO.Tests.BinaryReaderTests.Read_InvalidEncoding failed with "Xunit.Sdk.ThrowsException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18813]
Failed test: System.IO.Tests.BinaryReaderTests.Read_InvalidEncoding

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/System.IO.Tests/BinaryReaderTests/Read_InvalidEncoding/

MESSAGE:
~~~
Assert.Throws() Failure
    Expected: typeof(System.ArgumentOutOfRangeException)
    Actual: (No exception was thrown)
~~~
STACK TRACE:
~~~
at System.AssertExtensions.Throws[T](String paramName, Func`1 testCode) 
in D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\AssertExtensions.cs:line 46 
at System.IO.Tests.BinaryReaderTests.Read_InvalidEncoding() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.IO\tests\BinaryReader\BinaryReaderTests.cs:line 128
~~~

**Comment by danmosemsft** [comment]
Test added in https://github.com/dotnet/corefx/pull/13093 to test code from https://github.com/dotnet/coreclr/pull/7778. This may have been security motivated.
@stephentoub @AlexGhiondea @ianhays thoughts about the behavioral breaking change here?
@safern

**Comment by ianhays** [comment]
This was a security motivated change. The test needs to be excluded from running on desktop.

**Comment by safern** [comment]
Disabling the test.
