### ISSUE TITLE
Desktop: System.Xml.Tests.XmlSystemPathResolverTests.TestResolveInvalidPaths failed with "Xunit.Sdk.TrueException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18810]
Failed test: System.Xml.Tests.XmlSystemPathResolverTests.TestResolveInvalidPaths

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/System.Xml.Tests/XmlSystemPathResolverTests/TestResolveInvalidPaths/

MESSAGE:
~~~
Assert.True() Failure
    Expected: True
    Actual: False
~~~
STACK TRACE:
~~~
at System.Xml.Tests.XmlSystemPathResolverTests.AssertInvalidPath(String path) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Private.Xml\tests\XmlSchema\XmlSchemaSet\XmlSystemPathResolverTests.cs:line 69 
at System.Xml.Tests.XmlSystemPathResolverTests.TestResolveInvalidPaths() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Private.Xml\tests\XmlSchema\XmlSchemaSet\XmlSystemPathResolverTests.cs:line 82
~~~

**Comment by Jiayili1** [comment]
Closed issue: https://github.com/dotnet/corefx/issues/7732

**Comment by danmosemsft** [comment]
I don't get this -- it says it passed. It also passes locally.

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/System.Xml.Tests/XmlSystemPathResolverTests/TestResolveInvalidPaths/
```
Passed

System.Xml.Tests.XmlSystemPathResolverTests.TestResolveInvalidPaths (from System.Xml.RW.XmlSystemPathResolver.Tests)
```

**Comment by Jiayili1** [comment]
@danmosemsft  this issue is repro on build#30, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/30/testReport/System.Xml.Tests/XmlSystemPathResolverTests/TestResolveInvalidPaths/

**Comment by Jiayili1** [comment]
This issue is repro on Full framework tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170426.01/workItem/System.Xml.XmlSchemaSet.Tests/analysis/xunit/System.Xml.Tests.XmlSystemPathResolverTests~2FTestResolveInvalidPaths

**Comment by danmosemsft** [comment]
Since tihs passes locally, I doubt there is a real bug here.

**Comment by krwq** [comment]
@danmosemsft seems we have two copies of these tests:
https://github.com/dotnet/corefx/blob/7e0170e0ce47ef07c987cdbf8716259d9054cd1d/src/System.Private.Xml/tests/XmlSchema/XmlSchemaSet/XmlSystemPathResolverTests.cs
https://github.com/dotnet/corefx/blob/30e9fb02d048e88c71f772eed80ccff407f614d9/src/System.Private.Xml/tests/XmlReader/XmlResolver/XmlSystemPathResolverTests.cs

I believe desktop should be throwing on latest here but corefx is fine. Merge of those files would be nice (they currently slightly differ). cc: @sepidehMS @tarekgh

**Comment by danmosemsft** [comment]
@sepidehMS can you take htis one maybe?
