### ISSUE TITLE
Desktop: System.Security.Permissions.Tests.ApplicationTrustTests.ApplicationTrustEnumeratorCallMethods failed with "System.NullReferenceException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18817]
Failed test: System.Security.Permissions.Tests.ApplicationTrustTests.ApplicationTrustEnumeratorCallMethods

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/System.Security.Permissions.Tests/ApplicationTrustTests/ApplicationTrustEnumeratorCallMethods/

MESSAGE:
~~~
System.NullReferenceException : Object reference not set to an instance of an object.
~~~
STACK TRACE:
~~~
at System.Security.Policy.ApplicationTrustEnumerator.MoveNext() 
at System.Security.Permissions.Tests.ApplicationTrustTests.ApplicationTrustEnumeratorCallMethods() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Permissions\tests\ApplicationTrustTests.cs:line 33
~~~

**Comment by ianhays** [comment]
@safern you're currently working on the desktop failures in the Security.Permissions tests, correct? Don't want to step on your toes by taking this issue or #18818 :)

**Comment by safern** [comment]
Yes, currently working on this :)
