### ISSUE TITLE
Desktop: System.IO.Tests.PathTests.GetFullPath_Windows_Wildcards and System.IO.Tests.PathTests.GetPathRoot_Windows_UncAndExtended failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18827]
System.IO.Tests.PathTests.GetFullPath_Windows_Wildcards [FAIL]
MESSAGE:
~~~
Assert.Equal() Failure
    Expected: path
    Actual: (null)
~~~
STACK TRACE:
~~~
at System.AssertExtensions.Throws[T](String paramName, Func`1 testCode) 
in D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\AssertExtensions.cs:line 49 
at System.IO.Tests.PathTests.GetFullPath_Windows_Wildcards(Char wildcard) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime.Extensions\tests\System\IO\PathTests.cs:line 708
~~~
Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/System.IO.Tests/PathTests/GetFullPath_Windows_Wildcards_wildcard______/

System.IO.Tests.PathTests.GetPathRoot_Windows_UncAndExtended [FAIL]
MESSAGE:
~~~
Assert.Equal() Failure
     ↓ (pos 7)
    Expected: \\\\?\\UNC\\test\\unc
    Actual: \\\\?\\UNC
     ↑ (pos 7)
~~~
STACK TRACE:
~~~
at System.IO.Tests.PathTests.GetPathRoot_Windows_UncAndExtended(String value, String expected) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime.Extensions\tests\System\IO\PathTests.cs:line 203
~~~
Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/System.IO.Tests/PathTests/GetPathRoot_Windows_UncAndExtended_value_________________UNC____test____unc____path____to____something____expected_________________UNC____test____unc___/

**Comment by JeremyKuhne** [comment]
See #18888

**Comment by karelz** [comment]
@JeremyKuhne only 1 area label please (otherwise we have double-counting and unclear responsibility ;)). Thanks!
