### ISSUE TITLE
Desktop: System.IO.Tests.PathTests.GetFullPath_Windows_ValidExtendedPaths failed with "System.NotSupportedException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18826]
Failed test: System.IO.Tests.PathTests.GetFullPath_Windows_ValidExtendedPaths

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/System.IO.Tests/PathTests/GetFullPath_Windows_ValidExtendedPaths_path_________________C_________/

MESSAGE:
~~~
System.NotSupportedException : The given path's format is not supported.
~~~
STACK TRACE:
~~~
at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath) 
at System.IO.Path.GetFullPath(String path) 
at System.IO.Tests.PathTests.GetFullPath_Windows_ValidExtendedPaths(String path) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime.Extensions\tests\System\IO\PathTests.cs:line 610
~~~

**Comment by JeremyKuhne** [comment]
See #18888

**Comment by karelz** [comment]
@JeremyKuhne only 1 area label please, otherwise we have double counting of issues and fuzzy responsibilities. Please refer to [triage rules](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified). Thank you!

**Comment by ianhays** [comment]
@safern assigning this one to you since you were working on the full path failures. This is an older failure so you may have resolved it already.

**Comment by safern** [comment]
This should be fixed with: https://github.com/dotnet/corefx/pull/19012
