### ISSUE TITLE
Desktop: System.IO.Tests.PathTests.GetFullPath_Windows_LegacyArgumentExceptionPaths failed with "System.ArgumentException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18823]
Failed test: System.IO.Tests.PathTests.GetFullPath_Windows_LegacyArgumentExceptionPaths

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/System.IO.Tests/PathTests/GetFullPath_Windows_LegacyArgumentExceptionPaths_path____C_______/

MESSAGE:
~~~
System.ArgumentException : The path is not of a legal form.
~~~
STACK TRACE:
~~~
at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths) 
at System.IO.Path.GetFullPathInternal(String path) 
at System.IO.Path.GetFullPath(String path) 
at System.IO.Tests.PathTests.GetFullPath_Windows_LegacyArgumentExceptionPaths(String path) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime.Extensions\tests\System\IO\PathTests.cs:line 507
~~~

**Comment by Jiayili1** [comment]
Following test failed with the same issue: System.IO.Tests.PathTests.GetFullPath_Windows_URIFormatNotSupported

System.ArgumentException: URI formats are not supported

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/System.IO.Tests/PathTests/GetFullPath_Windows_URIFormatNotSupported/

**Comment by JeremyKuhne** [comment]
See #18888

**Comment by karelz** [comment]
@JeremyKuhne only 1 area label please, otherwise we have double counting of issues and fuzzy responsibilities. Please refer to [triage rules](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified). Thank you!

**Comment by ianhays** [comment]
@safern assigning this one to you since you were working on the full path failures. This is an older failure so you may have resolved it already.

**Comment by Jiayili1** [comment]
Following tests still failed with the same issue:
[System.IO.Tests.PathTests.GetFullPath_Windows_NotSupportedExceptionPaths](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/42/testReport/System.IO.Tests/PathTests/GetFullPath_Windows_NotSupportedExceptionPaths_path____bad__$DATA___/)
[System.IO.Tests.PathTests.GetPathRoot](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/42/testReport/System.IO.Tests/PathTests/GetPathRoot/)
[System.IO.Tests.PathTests.GetDirectoryName](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/42/testReport/System.IO.Tests/PathTests/GetDirectoryName_path________expected__null_/)
