### ISSUE TITLE
Desktop: System.Tests.OperatingSystemTests.Ctor_InvalidArgs_Throws failed with "Xunit.Sdk.ThrowsException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18822]
Failed test: System.Tests.OperatingSystemTests.Ctor_InvalidArgs_Throws

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/System.Tests/OperatingSystemTests/Ctor_InvalidArgs_Throws/

MESSAGE:
~~~
Assert.Throws() Failure
    Expected: typeof(System.ArgumentOutOfRangeException)
    Actual: typeof(System.ArgumentException): Illegal enum value: -1.
    Parameter name: platform
~~~
STACK TRACE:
~~~
at System.OperatingSystem..ctor(PlatformID platform, Version version, String servicePack) 
at System.Tests.OperatingSystemTests.<>c.<Ctor_InvalidArgs_Throws>b__1_0() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime.Extensions\tests\System\OperatingSystemTests.cs:line 37
~~~

**Comment by danmosemsft** [comment]
There isn't a good reason for preferring AOORE, let's just revert it.

**Comment by danmosemsft** [comment]
@JeremyKuhne wrt your thumbs up -- I spaced that AOORE is a subtype of AE so this is an acceptable change and I"ll just adjust the test.
