### ISSUE TITLE
Desktop: System.Reflection.Tests.AssemblyNameProxyTests.ReferenceMatchesDefinition failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18829]
Failed test: System.Reflection.Tests.AssemblyNameProxyTests.ReferenceMatchesDefinition

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/System.Reflection.Tests/AssemblyNameProxyTests/ReferenceMatchesDefinition_a1__mscorlib__Version_4_0_0_0__Culture_neutral__PublicKeyToken_b77a5c561934e089__a2__System_Runtime_Extensions__expected__True_/

MESSAGE:
~~~
Assert.Equal() Failure
    Expected: True
    Actual: False
~~~
STACK TRACE:
~~~
at System.Reflection.Tests.AssemblyNameProxyTests.ReferenceMatchesDefinition(AssemblyName a1, AssemblyName a2, Boolean expected) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime.Extensions\tests\System\Reflection\AssemblyNameProxyTests.cs:line 37
~~~

**Comment by AtsushiKan** [comment]
This test is bogus. There are no guarantees as to where a framework type lives. On the desktop, AssemblyNameProxy lives in mscorlib, not System.Runtime.Extensions. Tomorrow, it may live somewhere else.

**Comment by safern** [comment]
Should we then disable/delete this test?

**Comment by AtsushiKan** [comment]
Delete it. We have other tests for this api.
