### ISSUE TITLE
Desktop: System.IO.Tests.PathTests.IsPathRooted_Windows_Invalid failed with "Xunit.Sdk.FalseException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18825]
Failed test: System.IO.Tests.PathTests.IsPathRooted_Windows_Invalid

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/System.IO.Tests/PathTests/IsPathRooted_Windows_Invalid_value__________foo___/

MESSAGE:
~~~
Assert.False() Failure
    Expected: False
    Actual: True
~~~
STACK TRACE:
~~~
at System.IO.Tests.PathTests.IsPathRooted_Windows_Invalid(String value) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime.Extensions\tests\System\IO\PathTests.cs:line 240
~~~

**Comment by danmosemsft** [comment]
See #18888 presuambly
