### ISSUE TITLE
Desktop: System.Tests.GetEnvironmentVariable.InvalidArguments_ThrowsExceptions failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18821]
Failed test: System.Tests.GetEnvironmentVariable.InvalidArguments_ThrowsExceptions 

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/System.Tests/GetEnvironmentVariable/InvalidArguments_ThrowsExceptions/

MESSAGE:
~~~
Assert.Equal() Failure
    Expected: value
    Actual: (null)
~~~
STACK TRACE:
~~~
at System.AssertExtensions.Throws[T](String paramName, Action action) 
in D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\AssertExtensions.cs:line 38 
at System.Tests.GetEnvironmentVariable.InvalidArguments_ThrowsExceptions() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime.Extensions\tests\System\Environment.GetEnvironmentVariable.cs:line 22
~~~

**Comment by danmosemsft** [comment]
@safern we throw the same exceptoin but desktop forgot the parameter name. This line 22 shoud change from
`AssertExtensions.Throws<ArgumentException>("value", () => Environment.SetEnvironmentVariable("test", new string('s', 65 * 1024)))`
to
`AssertExtensions.Throws<ArgumentException>("value", null, () => Environment.SetEnvironmentVariable("test", new string('s', 65 * 1024)))`

**Comment by safern** [comment]
Assigned to me.
