### ISSUE TITLE
Desktop: Tests under "System.ConfigurationTests.ImplicitMachineConfigTests" failed with "System.Configuration.ConfigurationErrorsException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18830]
Failed tests:
System.ConfigurationTests.ImplicitMachineConfigTests.DesignTimeAppSettingsAccessible
System.ConfigurationTests.ImplicitMachineConfigTests.RuntimeAppSettingsAccessible

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/System.ConfigurationTests/ImplicitMachineConfigTests/DesignTimeAppSettingsAccessible/

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/System.ConfigurationTests/ImplicitMachineConfigTests/RuntimeAppSettingsAccessible/

MESSAGE:
~~~
System.Configuration.ConfigurationErrorsException : An error occurred creating the configuration section handler for appSettings: Type 'System.Configuration.AppSettingsSection' does not inherit from 'System.Configuration.IConfigurationSectionHandler'. (C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\Config\\machine.config line 14)
    ---- System.TypeLoadException : Type 'System.Configuration.AppSettingsSection' does not inherit from 'System.Configuration.IConfigurationSectionHandler'.
~~~
STACK TRACE:
~~~
at System.Configuration.BaseConfigurationRecord.FindAndEnsureFactoryRecord(String configKey, Boolean& isRootDeclaredHere) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs:line 1740 
at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs:line 1083 
at System.Configuration.BaseConfigurationRecord.GetSection(String configKey, Boolean getLkg, Boolean checkPermission) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs:line 757 
at System.Configuration.BaseConfigurationRecord.GetSection(String configKey) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs:line 258 
at System.Configuration.Configuration.GetSection(String sectionName) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\src\System\Configuration\Configuration.cs:line 168 
at System.Configuration.Configuration.get_AppSettings() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\src\System\Configuration\Configuration.cs:line 79 
at System.ConfigurationTests.ImplicitMachineConfigTests.DesignTimeAppSettingsAccessible() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\tests\System\Configuration\ImplicitMachineConfigTests.cs:line 27 
----- Inner Stack Trace ----- 
at System.Configuration.TypeUtil.VerifyAssignableType(Type baseType, Type type, Boolean throwOnError) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\src\System\Configuration\TypeUtil.cs:line 187 
at System.Configuration.MgmtConfigurationRecord.CreateSectionFactory(FactoryRecord factoryRecord) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\src\System\Configuration\MgmtConfigurationRecord.cs:line 134 
at System.Configuration.BaseConfigurationRecord.FindAndEnsureFactoryRecord(String configKey, Boolean& isRootDeclaredHere)
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs:line 1735
~~~

**Comment by Jiayili1** [comment]
Following tests failed with "System.Configuration.ConfigurationErrorsException ":
MonoTests.System.Configuration.ConfigurationManagerTest.OpenExeConfiguration1_UserLevel_None 
MonoTests.System.Configuration.ConfigurationManagerTest.OpenExeConfiguration1_UserLevel_PerUserRoaming 
MonoTests.System.Configuration.ConfigurationManagerTest.exePath_UserLevelPerRoamingAndLocal 
MonoTests.System.Configuration.ConfigurationManagerTest.OpenExeConfiguration1_UserLevel_PerUserRoamingAndLocal
MonoTests.System.Configuration.ConfigurationManagerTest.TestContext 
MonoTests.System.Configuration.ConfigurationManagerTest.GetSectionReturnsNativeObject 
MonoTests.System.Configuration.ConfigurationManagerTest.exePath_UserLevelPerRoaming 
MonoTests.System.Configuration.ConfigurationManagerTest.mapped_ExeConfiguration_null
MonoTests.System.Configuration.ConfigurationManagerTest.TestAddRemoveSection

**Comment by danmosemsft** [comment]
@weshaggard @safern this is a desktop run, but hte implementation in the callstack is out of corefx. Is this expected? Seems it's not doing anything useful if it's not running against hte desktop s.config...

**Comment by safern** [comment]
@JeremyKuhne do you have any idea of what's happening in here?

**Comment by weshaggard** [comment]
It is because ConfigurationManager has a netstandard implementation but we need to add a netfx configuration that is a partial facade.

**Comment by safern** [comment]
Thanks for the update @weshaggard

**Comment by danmosemsft** [comment]
Without adding that facade, someone using this package on desktop will get ours, not the more capable desktop one. Seems we should avoid that.
