### ISSUE TITLE
Running MusicStore sample on NET461 fails with an exception

### ISSUE THREAD

**Issue by kichalla** [dotnet/corefx#18849]
**Repro:**

- Clone https://github.com/aspnet/MusicStore
- Checkout the branch `kichalla/net461`
- cd `samples/MusicStore`
- dotnet restore
- dotnet build
- Run `samples\MusicStore\bin\Debug\net461\MusicStore.exe`

**Expected:**
Application starts successfully and you can make a request successfully to `http://localhost:5000/` to see the home page.

**Actual:**
Application fails to start with an exception
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at MusicStore.Program.Main(String[] args)
```

A pull request where discussion about this has been going on:
https://github.com/aspnet/MusicStore/pull/775

cc @Eilon @pranavkm

**Comment by mellinoe** [comment]
I haven't looked at the repro very closely, but the fact that System.Runtime.Loader is trying to load jumps out at me. That is a .NET Core-only assembly; it cannot work on .NET Framework. The way MusicStore is being built might be broken in some way if it's producing a .NET Framework application that depends on System.Runtime.Loader.

**Comment by danmosemsft** [comment]
@weshaggard please find the right home thx.

**Comment by weshaggard** [comment]
@kichalla System.Runtime.Loader is not supported on desktop so if there is code that uses it that needs to be changed to not consume when on desktop.

**Comment by kichalla** [comment]
Thanks @weshaggard 

cc @Tratcher @davidfowl

**Comment by pranavkm** [comment]
@weshaggard - the API is available  in `netstandard1.5`. The calling code doesn't know it's running on desktop: https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/WebHostExtensions.cs#L96. If this isn't meant to work in desktop, shouldn't the API be moved to `netcoreappx.y`?

**Comment by pranavkm** [comment]
I suspect this is another manifestation of https://github.com/dotnet/corefx/issues/19058.

**Comment by weshaggard** [comment]
See https://github.com/dotnet/corefx/issues/11023 where this was discussed in the past. This is a case where we had a netstandard set of APIs but not all platforms supported an implementation for it. 

For this library we are no longer shipping it as an individual nuget package any longer and it will only ship in Microsoft.NETCore.App going forward so folks won't be able to consume it for a desktop application.

**Comment by davidfowl** [comment]
@weshaggard you realize that everyone that uses System.Runtime.Loader is broken because that package is permanently broken right? For some reason, it was originally made to support .NET Standard 1.5 instead of netcoreapp1.0 (which is what it should have been the whole time). Can we update that package or is it pretty much dead at this point?

**Comment by weshaggard** [comment]
That package is essentially dead once we ship 2.0. We could consider shipping an update of it to force the breaking change but I think our guidance will be to stop using it as opposed to updating it.

**Comment by ReubenBond** [comment]
@weshaggard why is System.Runtime.Loader essentially dead in 2.0, does something replace it?

**Comment by davidfowl** [comment]
It's not dead, or at least it shouldn't be. It should just be .NET Core specific. 

> does something replace it?

The older Assembly.Load* APIs are back in netstandard 2.0. `AssemblyLoadContext` gives way more control over what context assemblies get loaded into. You can avoid some of the extremely bizzare behavior by using it directly. The downside is that you're coupled to .NET Core.

**Comment by ReubenBond** [comment]
Ok, good, thanks for clearing that up

**Comment by weshaggard** [comment]
What @davidfowl said. The library isn't dead it is just .NET Core specific, what is dead is the individual library nuget package for it because it ships in the .NET Core 2.0 platform.
