### ISSUE TITLE
Add DateTime.Now perf tests

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#18853]
As a follow up to https://github.com/dotnet/corefx/issues/3571, we should have a perf test for this scenario.

/cc @danmosemsft @mellinoe

**Comment by eerhardt** [comment]
Nevermind, I see this already exists:  https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Runtime/tests/Performance/Perf.DateTime.cs#L12

/cc @Petermarcu - since he was asking about having a perf test for this scenario.

**Comment by mellinoe** [comment]
We do have some tests for `DateTime`, including `Now` and `UtcNow`:

https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/Performance/Perf.DateTime.cs#L12

I filed this issue recently which tracks our overall coverage and how it should be augmented: https://github.com/dotnet/corefx/issues/18763.

By the way, we don't have any "official" performance runs on Linux, so we won't be able to track the improvements there anyways, unfortunately.
