### ISSUE TITLE
Change exception returned when serializing HttpWebRequest to match NETFX

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#18850]
Comments from PR #18801:

From @safern "Binary Serialization is now supported on .NET Core 2.0 but it wasn't in 1.1 or 1.0; so probably that is why we were throwing PNSE, so I think the same thing, it sounds reasonable to throw SE."

```c#
        [Fact]
        public void HttpWebRequest_Serialize_Fails()
        {
            using (MemoryStream fs = new MemoryStream())
            {
                BinaryFormatter formatter = new BinaryFormatter();
                var hwr = HttpWebRequest.CreateHttp("http://localhost");

                if (PlatformDetection.IsFullFramework)
                {
                    // .NET Framework throws a more detailed exception.
                    // System.Runtime.Serialization.SerializationException):
                    //  Type 'System.Net.WebRequest+WebProxyWrapper' in Assembly 'System, Version=4.0.0.
                    //        0, Culture=neutral, PublicKeyToken=b77a5c561934e089' is not marked as serializable.
                    Assert.Throws<System.Runtime.Serialization.SerializationException>(() => formatter.Serialize(fs, hwr));
                }
                else
                {
                    // TODO: Issue #18850. Change HttpWebRquest to throw SerializationException similar to .NET Framework.
                    Assert.Throws<PlatformNotSupportedException>(() => formatter.Serialize(fs, hwr));
                }
            }
        }
```

**Comment by davidsh** [comment]
cc: @danmosemsft @safern

**Comment by davidsh** [comment]
@safern @danmosemsft 

Do we need to change HttpWebRequest or System.Runtime.Serialization.* code to change that exception? On .NET Framework, the exception seems to surface from Serialization code.

**Comment by safern** [comment]
Currently HttpWebRequest is throwing the PNSE, which makes sense for 1.1 and 1.0 as serialization was not supported. So if SE is being thrown from System.Runtime.Serialization code that means that we are missing to support HttpWebRequest to be serializable. Should we instead port the capability of HttpWebRequest being serializable to .NET Core?

**Comment by davidsh** [comment]
>Currently HttpWebRequest is throwing the PNSE,

Where in .NET Core code (i.e. master branch) is that happening?  I didn't see it.

**Comment by safern** [comment]
https://github.com/dotnet/corefx/blob/master/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs#L95-L109

**Comment by davidsh** [comment]
Thx.  Your vision is better than mine. :)

In terms of the solution, yes, we should remove the PNSE code and replace it with the NETFX code.

Something like:
https://github.com/Microsoft/referencesource/blob/master/System/net/System/Net/HttpWebRequest.cs#L5285

**Comment by danmosemsft** [comment]
I attempted to make them serializable and it was too complex to port the desktop behavior. I made it PNSE.. see https://github.com/dotnet/corefx/pull/14175

Of course I'd be happy if you actually do make them serializable but it's not a paste job.

**Comment by danmosemsft** [comment]
Same for HttpWebResponse.

**Comment by karelz** [comment]
Moving to Future - @danmosemsft is that ok from our latest Serialization plan POV?
Should we document it on AppCompat wiki/tool?

**Comment by danmosemsft** [comment]
I don't think anyone should make anything else serializable until we've resolved our binary serializer discussion.

**Comment by karelz** [comment]
Do we have primary Serialization issue I can link? So that we mark it unblocked when the plan is finalized ...

**Comment by ViktorHofer** [comment]
@karelz https://github.com/dotnet/corefx/issues/19119

**Comment by ViktorHofer** [comment]
@danmosemsft @stephentoub @karelz As this is now labeled as **blocked**, should we make `HttpWebRequest` implement `ISerializable` with respect to the privat field name differences between Core and Desktop?

**Comment by stephentoub** [comment]
I expect with https://github.com/dotnet/corefx/issues/19119 we're going to remove the [Serializable] attribute entirely.
cc: @morganbr

**Comment by ViktorHofer** [comment]
Even if we're removing the Serializable attribute, the three methods (ctor, ISerializable.GetObjectData, GetObjectData) are implemented because of ISerializable. Therefore I suggest changing the exception to SerializationException and removing the Serializable attribute (as we don't need it).

**Comment by ViktorHofer** [comment]
@danmosemsft @safern @davidsh Why should we support serialization of HttpWebRequest in Core when it never worked on netfx either? The only reason I could think of is, that this is considered as a netfx bug.

**Comment by stephentoub** [comment]
> Why should we support serialization of HttpWebRequest in Core when it never worked on netfx either?

Not sure what you mean... we already throw so it's already not supported.

**Comment by ViktorHofer** [comment]
See @davidsh post:

> In terms of the solution, yes, we should remove the PNSE code and replace it with the NETFX code.

See @danmosemsft:

> I attempted to make them serializable and it was too complex to port the desktop behavior. I made it PNSE.. see #14175. Of course I'd be happy if you actually do make them serializable but it's not a paste job.

**Comment by stephentoub** [comment]
At which point I refer you back to my previous comment: "I expect with #19119 we're going to remove the [Serializable] attribute entirely."

**Comment by davidsh** [comment]
HttpWebRequest is returning an error during serialization due to being unable to serialize the Proxy field since it is set (by default) to the system proxy.  Apparently that WebProxy field/object isn't serializable.

Serialization support in HttpWebRequest was marked as "obsolete" in .NET Framework several releases ago.  I think it was when .NET 4.0 first shipped.  I'll need to research it my old emails since that around 2008.  So, there was already a desire back then to remove this from HttpWebRequest.

In any case, we can wait on this particular issue until the global decision about serialization support in general for .NET Core is decided.

**Comment by ViktorHofer** [comment]
Alright, thanks David! I think my misconception was, that if we would remove the Serializable attribute we would keep the ISerializable interface with the method implementations.

**Comment by morganbr** [comment]
The plan with #19119  is to remove SerializableAttribute from HttpWebRequest and throw PlatformNotSupportedException from the serialization constructor and GetObjectData. Removing SerializableAttribute will make BinaryFormatter automatically throw SerializationExcepiton.

**Comment by davidsh** [comment]
This issue can be closed now.

The test has already been updated to reflect the final decisions on serialization for .NET Core 2.0.

```c#
        [Fact]
        public void HttpWebRequest_Serialize_Fails()
        {
            using (MemoryStream fs = new MemoryStream())
            {
                BinaryFormatter formatter = new BinaryFormatter();
                var hwr = HttpWebRequest.CreateHttp("http://localhost");

                // .NET Framework throws 
                // System.Runtime.Serialization.SerializationException:
                //  Type 'System.Net.WebRequest+WebProxyWrapper' in Assembly 'System, Version=4.0.0.
                //        0, Culture=neutral, PublicKeyToken=b77a5c561934e089' is not marked as serializable.
                // While .NET Core throws 
                // System.Runtime.Serialization.SerializationException:
                //  Type 'System.Net.HttpWebRequest' in Assembly 'System.Net.Requests, Version=4.0.0.
                //        0, Culture=neutral, PublicKeyToken=b77a5c561934e089' is not marked as serializable.
                Assert.Throws<System.Runtime.Serialization.SerializationException>(() => formatter.Serialize(fs, hwr));
            }
        }
```
