### ISSUE TITLE
Incomplete HTTP responses behaves different between Core and NETFX

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#18864]
While investigation #17691, I discovered a test that hangs on .NET Framework.

While the test intended to test a scenario with a "server that slowly returned data", it is testing it in the wrong manner.  Returning an HTTP response with a Content-Length header that is geater than the number of bytes actually being returned will cause a client to wait until all promised bytes are returned. This is how, for example, the long-polling type of scenarios work.

The fact the .NET Core is working and returning "partial data" doesn't seem right. I believe the bug is that .NET Core is not behaving as per RFC. And this test is testing something invalid.

If we really wanted a specific test for "slow data", we should return all data promised (but perhaps delayed slightly).

```c#
        [ActiveIssue(18864)]
        [OuterLoop] // TODO: Issue #11345
        [Fact]
        public async Task SendAsync_ReadFromSlowStreamingServer_PartialDataReturned()
        {
            await LoopbackServer.CreateServerAsync(async (server, url) =>
            {
                using (var client = new HttpClient())
                {
                    Task<HttpResponseMessage> getResponse = client.GetAsync(url, HttpCompletionOption.ResponseHeadersRead);

                    await LoopbackServer.AcceptSocketAsync(server, async (s, stream, reader, writer) =>
                    {
                        while (!string.IsNullOrEmpty(reader.ReadLine())) ;
                        await writer.WriteAsync(
                            "HTTP/1.1 200 OK\r\n" +
                            $"Date: {DateTimeOffset.UtcNow:R}\r\n" +
                            "Content-Length: 16000\r\n" +
                            "\r\n" +
                            "less than 16000 bytes");

                        using (HttpResponseMessage response = await getResponse)
                        {
                            var buffer = new byte[8000];
                            using (Stream clientStream = await response.Content.ReadAsStreamAsync())
                            {
                                int bytesRead = await clientStream.ReadAsync(buffer, 0, buffer.Length);
                                _output.WriteLine($"Bytes read from stream: {bytesRead}");
                                Assert.True(bytesRead < buffer.Length, "bytesRead should be less than buffer.Length");
                            }
                        }

                        return null;
                    });
                }
            });
        }
```

**Comment by davidsh** [comment]
cc: @stephentoub @safern @danmosemsft @CIPop

**Comment by karelz** [comment]
@stephentoub can you please chime in if this might be Loopback server problem or product issue? (@davidsh asks)

**Comment by stephentoub** [comment]
The server says it'll send 16000 bytes of content, and sends ~20 of it (but keeps the connection open so it could theoretically send the remaining ~15980 bytes).  The client reads that ~20 bytes and then disposes of the response / response stream.  It should be perfectly acceptable for a client to stop reading prior to receiving the entire content, and the server is in fact very slow... so slow that it never gets around to sending the remaining content before the client kills the request.

If this is hanging on desktop, sounds like a bug on desktop.

@davidsh, what am I missing?

**Comment by davidsh** [comment]
>If this is hanging on desktop, sounds like a bug on desktop.

Or, we have implemented it incorrectly/behavior-different on .NET Core.  

This code:

```c#
int bytesRead = await clientStream.ReadAsync(buffer, 0, buffer.Length);
```

is assuming that it will return with fewer bytes than buffer.Length is that is the only amount currently available on the wire.  But perhaps .NET Framework treats that Read call as wanting to wait to read all the bytes to fill the buffer except if it reaches the end of the stream completely.  And it would detect that via the connection being closed gracefully (i.e. complete the I/O reading 0 bytes) or the conclusion of the promised number of bytes according to the HTTP headers.

So, it is possible that we have implemented the read semantics differently between .NET Framework and .NET Core.

**Comment by stephentoub** [comment]
> is assuming that it will return with fewer bytes than buffer.Length if that is the only amount currently available on the wire. But perhaps .NET Framework treats that Read call as wanting to wait to read all the bytes to fill the buffer except if it reaches the end of the stream completely. And it would detect that via the connection being closed gracefully (i.e. complete the I/O reading 0 bytes) or the conclusion of the promised number of bytes according to the HTTP headers.

I'd consider that a bug in desktop.  For better or worse, Stream.Read{Async} is not supposed to do that.

**Comment by davidsh** [comment]
>For better or worse, Stream.Read{Async} is not supposed to do that.

Well, if there are no bytes to read at the moment, then Stream.Read cannot return anything until a byte appears.  It can't return with 0 bytes because the semantic of that is having reached "end of file".

**Comment by davidsh** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.networkstream.read?view=netframework-4.7#System_Net_Sockets_NetworkStream_Read_System_Byte___System_Int32_System_Int32_

>Returns
Int32
The number of bytes read from the NetworkStream, or 0 if the socket is closed.

**Comment by stephentoub** [comment]
That's not what I was referring to.  It can block / not complete while there's 0 bytes to be read, but once there's something to be read, it's not supposed to wait around in hopes of receiving everything that was requested.

**Comment by davidsh** [comment]
Maybe there are some race conditions we don't understand and .NET Framework hits them more than .NET Core. Perhaps this test is brittle in some way.  Need to be investigated more deeply

**Comment by CIPop** [comment]
@stephentoub / @davidsh the PR above disables the test on Desktop leaving this issue# in the comment.
The intention is unclear: which of these 3 possibilities did you decide on: is it a "TODO" / by design or saying that Desktop has a bug and needs to be fixed?

**Comment by stephentoub** [comment]
@cipop, I described the issue in the PR.  It's a desktop bug.

**Comment by CIPop** [comment]
Thanks for the clarification @stephentoub. 

For future reference and Framework 2 Core ports, this is a known behavior difference described in #19615:

> This netfx behavior diverges from expectations around how Stream is meant to behave: Stream.Read/ReadAsync can block (asynchronously in the Async case) until there's any data available, but once there is data available they should return it rather than waiting arbitrarily long for more.

@davidsh @karelz @DavidGoll :

1. We currently have no Desktop tracking item. Do we want to create one?
2. I know we're maintaining documentation containing a list of behavior differences. Reopening this issue and marking it for doc tracking purposes.

**Comment by safern** [comment]
By adding label netfx-port-consider an item referencing this one will be opened in TS to track the desktop issue.

**Comment by stephentoub** [comment]
> I know we're maintaining documentation containing a list of behavior differences. Reopening this issue and marking it for doc tracking purposes.

@CIPop, it should be moved out of 2.0 then, right?

**Comment by CIPop** [comment]
> By adding label netfx-port-consider an item referencing this one will be opened in TS to track the desktop issue.

To clarify: we won't backport any code - the fix in Framework will be different and is pending app-compat assesment. 
The label is set here just to track opening a Framework bug.

> @CIPop, it should be moved out of 2.0 then, right?

I'm not sure... Looks like this is a 2.0 bug but with `Post-ZBB` label?

@karelz - please review this bug in relation with #18405.

**Comment by davidsh** [comment]
Not useful to track this since it is current .NET Framework behavior.
