### ISSUE TITLE
Missing parameter validation for CredentialCache.Add method

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#18870]
While investigating #17691, discovered that CredentialCache is not doing proper validation with the 'Add' method.

On .NET Core, it allows for DefaultCredentials to be added for auth types such as 'Basic'. On .NET Framework, it throws:

>System.ArgumentException : Default credentials cannot be supplied for the Basic authentication scheme.
Parameter name: authType
Stack Trace:
at System.Net.CredentialCache.Add(Uri uriPrefix, String authType, NetworkCredential cred)

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by karelz** [comment]
Should be simple adding of validation.

The API is used, not legacy - we should fix it in 2.0. It may have impact on developers.
