### ISSUE TITLE
GetMetadataReader() throws BadImageFormatException

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/corefx#18883]
Repro,
```c#
var assemblyPath = "C:\\temp\\Microsoft.AspNetCore.Mvc.dll";
using (var stream = File.Open(assemblyPath, FileMode.Open))
{
    //var assembly = AssemblyLoadContext.Default.LoadFromStream(stream); // This works!
    var provider = MetadataReaderProvider.FromMetadataStream(stream);
    var reader = provider.GetMetadataReader(); // throws - Invalid COR20 header signature.
    var attributes = reader.CustomAttributes;
}
```

I am trying to read some assembly attributes without loading it. But when I try to call `GetMetadataReader()`, I get `BadImageFormatException: 'Invalid COR20 header signature.'` 

Related issue: https://github.com/dotnet/corefx/issues/1050

**Comment by ajaybhargavb** [comment]
Is there any workarounds for this?

**Comment by tmat** [comment]
'''MetadataReaderProvider.FromMetadataStream''' is not the right API to use for reading a PE file. You need to use ```new PEReader(stream)```

**Comment by ajaybhargavb** [comment]
@tmat that works. I am trying to extract the constructor arguments from a custom attribute. But I see `CustomAttributeDecoder` is internal. Is there a plan to expose it in the future? I'd prefer not having to copy that code and use it.

**Comment by tmat** [comment]
This should work: https://source.dot.net/#System.Reflection.Metadata/System/Reflection/Metadata/TypeSystem/CustomAttribute.cs,d081c5c9add06fae,references
