### ISSUE TITLE
Activity ID should not expose computer name

### ISSUE THREAD

**Issue by SergeyKanzhelev** [dotnet/corefx#18885]
This is continuation of the discussion started here: https://github.com/dotnet/corefx/issues/18418

Activity ID which is part of Diagnostics Source should not expose computer name. There are two scenarios when this causes the problem:

1. In case of server application that enabled monitoring - service owner may not realize that the computer name of the service will be exposed to the every HTTP/HTTPS dependency it calls. This causes an unnecessary information disclosure
2. In case of client applications that send telemetry - computer name is considered end user identifiable information and cannot be stored without consent. Having computer name as part of an Activity ID will require all monitoring solutions strip out the computer name substring.

Having computer name as part of ID also sets some expectations for the monitoring solutions of developers who might take a dependency on the format and will be broken by the potential format change in future

**Comment by SergeyKanzhelev** [comment]
CC: @vancem @lmolkova @cwe1ss

**Comment by cwe1ss** [comment]
I fully agree with @SergeyKanzhelev. The computer name should be part of the metadata that is sent with every activity by the tracer. This allows the tracer to either mask it or to not send it at all if there are PII requirements.

I see these additional reasons (mostly from #18418):

* ID may be started on a device that doesn't have a proper computer name (e.g. phones, a javascript client, ...)
* ID may be started on a machine that is managed by a 3rd party and therefore makes it irrelevant (as a part of the ID - not as a separate tag/metadata)
* the computer name may be very long (e.g. azure cloud role instance, azure vm scale set names)
* the computer name may contain a "-" which is currently used as a separator in the algorithm
* A computer name is some kind of user-supplied input outside of our control. What if Windows 2035 will support Unicode and Emojis for machine names? 😄
* The machine on which a trace starts is in no way more special than any other involved machine

As an alternative, I propose a 128bit random for the TraceId (to ensure global uniqueness) and a 64bit random for the ActivityId (to ensure uniqueness within one trace).

**Comment by cwe1ss** [comment]
* computer name may contain a "." which is also used in the current algorithm

**Comment by SergeyKanzhelev** [comment]
@vancem @lmolkova I just spoke to privacy advisor. The ONLY option to ship what we have today when we expose the computer name is to disable correlation by default and only enable it with the user consent. This bug is blocking the release.

I'll keep pushing, but realistically - let's just hash it at least. 

Also what @cwe1ss said about the special characters escaping....

**Comment by vancem** [comment]
We will remove the computer name.

**Comment by vancem** [comment]
Fixed by PR #19055
