### ISSUE TITLE
IO tests need conditionalized for new behavior to run correctly on desktop

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#18888]
Tests need split up and results need conditionalized on the relevant new behavior being enabled.

I already wrote a [helper](https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/tests/PathFeatures.cs#L38) for this. It needs moved to common.

Creating this issue to tag the various tests against.

**Comment by JeremyKuhne** [comment]
Fyi: @ianhays, @safern

**Comment by safern** [comment]
Thanks for opening this @JeremyKuhne

**Comment by ianhays** [comment]
@safern do you want this one or want me to take it?

**Comment by safern** [comment]
I take this one, already started but didn't assign it yet. Thanks for asking.

**Comment by ViktorHofer** [comment]
@safern are you on track? do you need some help?

**Comment by ianhays** [comment]
@ViktorHofer this is resolved by @safern 's PR https://github.com/dotnet/corefx/pull/19343 that was delayed waiting for a coreclr fix to be consumed. It should be resolved shortly :)
