### ISSUE TITLE
Two CryptoConfig members throw PNSE

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#18892]
@bartonjs comments: "Wasn’t supported in Mono/Xamarin, and costs a world of pain"
```
M:System.Security.Cryptography.CryptoConfig.AddAlgorithm(System.Type,System.String[])
M:System.Security.Cryptography.CryptoConfig.AddOID(System.String,System.String[])

```

If it's not supported in Mono this is not necessarily a must have. Also, useage seems negligible. Please triage to 2.0, Future, or close.

**Comment by danmosemsft** [comment]
Setting to 2.0 for visibility of these PNSE

**Comment by bartonjs** [comment]
@akoeplinger Is CryptoConfig still readonly in Xamarin, or did you start accepting mutation with netstandard20 alignment?

**Comment by akoeplinger** [comment]
@bartonjs there was no change in that regard, it still throws PNSE on AOT platforms (Xamarin.iOS).
I think it accepts mutation on JIT platforms (Xamarin.Android) though.

**Comment by jmezach** [comment]
I would like to work on this. I had a look at the [reference source](http://referencesource.microsoft.com/#mscorlib/system/string.cs,8281103e6f23cb5c) and it seems easy enough to port. I just need the resource strings. Can I get them from somewhere?

**Comment by bartonjs** [comment]
@jmezach Your reference source link is to System.String.  Are you commenting on the correct issue? What are you proposing for this one? (I'm personally torn between "make it work" and "document it as not working")

**Comment by jmezach** [comment]
@bartonjs Uhm, I think I pasted in the wrong URL. I was refering to [here](http://referencesource.microsoft.com/#mscorlib/system/security/cryptography/cryptoconfig.cs,565f8b55bbef37aa).

For now I've just copied the code from there (for AddAlgorithm) and got it to compile, except for the Environment.GetString calls. Haven't written any tests yet, so I'm not sure if I'll run into issues later on. Code doesn't seem that complex though. Do you have reason to believe it might not work as is?

**Comment by bartonjs** [comment]
@jmezach It's not `AddAlgorithm` and `AddOid` I'm worried about, but the callers of CryptoConfig.  But, I suppose, it's fine.  Turns out, if calling CryptoConfig.Add\* causes something to break you should just stop calling it

Cryptography_AlgorithmTypesMustBeVisible = Algorithms added to CryptoConfig must be accessable from outside their assembly.

Cryptography_AddNullOrEmptyName = CryptoConfig cannot add a mapping for a null or empty name.

If there are others that you need, just call them out.
