### ISSUE TITLE
PKCS1MaskGenerationMethod limited to SHA1 -- desktop is not

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#18898]
PKCS1MaskGenerationMethod.HashName will not accept any value other than "SHA1"  (or null). Otherwise it throws PNSE.

In desktop it accepted any value, and would then pass it to `CryptoConfig.CreateFromName(HashNameValue);`

I see ~0% usage. Is this limitation acceptable for 2.0?

**Comment by bartonjs** [comment]
It could probably just defer to CryptoConfig now.  I think it got implemented before CryptoConfig did.

**Comment by danmosemsft** [comment]
Setting to 2.0 for visibility of this PNSE.
