### ISSUE TITLE
Two X509 members throw PNSE on non Windows

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#18894]
```
M:System.Security.Cryptography.X509Certificates.X509Chain.#ctor(System.IntPtr)  // mac and unix
M:System.Security.Cryptography.X509Certificates.X509Store.#ctor(System.IntPtr)  // mac
```

~0% usage in our corpuses. @bartonjs mentioned the former is "tricky on mac". Please triage for 2.0.

**Comment by bartonjs** [comment]
@danmosemsft For X509Store did you possibly mean unix throws, mac doesn't?

If so, this is as expected due to platform (OS) differences.

**Comment by danmosemsft** [comment]
@bartonjs yes, corrected. OK, closing.
