### ISSUE TITLE
CspParameters.KeyPassword throws PNSE and should not

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#18896]
This throws PNSE because it accepts SecureString which was not available earlier. It should be enabled 
```
P:System.Security.Cryptography.CspParameters.KeyPassword
```
The implementation is trivial, `public SecureString KeyPassword { get; set; }` . In Desktop, it's used only by an internal method we do not have. So it's low priority to implement this, nevertheless it is an unnecessary public break.

**Comment by danmosemsft** [comment]
@krwq can you take this one? See @bartonjs comments in linked Pr which I don't have time to address.

**Comment by krwq** [comment]
@danmosemsft sounds good, I'll take over from your PR
