### ISSUE TITLE
Desktop: XmlDictionaryWriterTest.XmlBaseWriter_WriteStartEndElementAsync failed with "System.NotImplementedException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18899]
Failed test: XmlDictionaryWriterTest.XmlBaseWriter_WriteStartEndElementAsync

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/30/testReport/(root)/XmlDictionaryWriterTest/XmlBaseWriter_WriteStartEndElementAsync/

MESSAGE:
~~~
System.NotImplementedException : The method or operation is not implemented.
~~~
STACK TRACE:
~~~
at System.Xml.XmlWriter.WriteStartElementAsync(String prefix, String localName, String ns) 
at XmlDictionaryWriterTest.XmlBaseWriter_WriteStartEndElementAsync() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime.Serialization.Xml\tests\XmlDictionaryWriterTest.cs:line 108
~~~

**Comment by safern** [comment]
@shmao I suspect this is a difference in behavior?

**Comment by shmao** [comment]
@safern Yes, the async APIs were implemented on NetCore only. See https://github.com/dotnet/corefx/pull/2596. The behavior difference is expected.

**Comment by safern** [comment]
Thanks for clarifying. Will disable the test then.

**Comment by Jiayili1** [comment]
This issue is repro on desktop, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/31/testReport/(root)/XmlDictionaryWriterTest/XmlBaseWriter_FlushAsync_2/
