### ISSUE TITLE
HttpWebRequest.MediaType throws PNSE

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#18900]
HttpWebRequest.MediaType throws PNSE on all platforms, without any explanatory message.

This has 2% usage in apiport data and 1% in Unity top 100. 
https://apisof.net/catalog/System.Net.HttpWebRequest.MediaType

It's not clear in a quick glance at desktop code what it actually does or how easy it would be to port. Please triage for 2.0

**Comment by stephentoub** [comment]
> It's not clear in a quick glance at desktop code what it actually does or how easy it would be to port

From MSDN:
https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.mediatype(v=vs.110).aspx
"The value of the MediaType property affects the CharacterSet property. When you set the MediaType in the request, the corresponding media type is chosen from the list of character sets returned in the response Content-type HTTP header."

**Comment by davidsh** [comment]
The MediaType itself is part of 'Content-Type' HTTP header.  In some ways, the mediatype information can be simply a part of the complete ContentType property specified as a string.

For example, this code:

```c#
HttpWebRequest request = new HttpWebRequest(...);
request.ContentType = "text/plain; charset=utf-8";
```

should be equivalent to this code:

```c#
HttpWebRequest request = new HttpWebRequest(...);
request.ContentType = "text/plain";
request.MediaType = "charset=utf-8";
```

Both should end up transmitting the same 'Content-Type' HTTP request header of

```
Content-Type: text/plain; charset=utf-8
```

**Comment by karelz** [comment]
Cost: Easy-to-medium. We need few tests to really understand the Desktop behavior.

**Comment by ViktorHofer** [comment]
@davidsh I don't think that your assumption regarding the MediaType is correct. If I test your code in netfx I get the following raw request:
```
GET http://corefx-net.cloudapp.net/Echo.ashx HTTP/1.1
Content-Type: application/json
Host: corefx-net.cloudapp.net
Connection: Keep-Alive
```

and the following response:
```
HTTP/1.1 200 OK
Cache-Control: private
Content-Type: application/json; charset=utf-8
Content-MD5: gH3s4lqtcGl/FeW21dT6yQ==
Server: Microsoft-IIS/8.5
X-HttpRequest-Method: GET
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Sat, 29 Apr 2017 16:01:41 GMT
Content-Length: 326

{"Method":"GET","Url":"/Echo.ashx","Headers": {
    "Connection": "Keep-Alive",
    "Content-Type": "application/json",
    "Host": "corefx-net.cloudapp.net"
  },
  "Cookies": {},
  "BodyContent": "",
  "BodyLength": 0,
  "SecureConnection": false,
  "ClientCertificatePresent": false,
  "ClientCertificate": null
}
```

The WebHttpResponse object properties don't show any differences when you set the MediaType property or when not. I looked into the netfx code, it seems the value is just passed into the internal constructor of the WebHttpResponse object and isn't used at all there, **despite what MSDN says!**

**Comment by davidsh** [comment]
The 'MediaType' property is something you set on the HttpWebRequest.  It should affect the request headers.  It doesn't necessarily affect what comes back from the server (response headers....HttpWebResponse).  These request headers let the server know what types of response body content is preferred by a client but a server can ignore that.  See the RFC for details.

So, the real test is whether settings these properties on the HttpWebRequest are causing the expected behavior of the request headers.  You can measure that by looking at what goes out on the wire.

I will say looking at MSDN, it talks about how these headers affect the response and that is not explained well.

**Comment by ViktorHofer** [comment]
> The 'MediaType' property is something you set on the HttpWebRequest. It should affect the request headers.

But it doesn't affect them. I tested it in a netfx app and traced with fiddler. And when you look into the netfx code you see that the property is only passed into the constructor of HttpWebResponse where it isn't used (only serialization...).

**Comment by ViktorHofer** [comment]
Another test with better Content-Type and Media-Type.

My sample code:

```
HttpWebRequest request = WebRequest.CreateHttp("http://corefx-net.cloudapp.net/Echo.ashx");
request.ContentType = "text/plain";
request.MediaType = "charset=ISO-8859-1";
request.GetResponse();
```

Request raw:
```
GET http://corefx-net.cloudapp.net/Echo.ashx HTTP/1.1
Content-Type: text/plain
Host: corefx-net.cloudapp.net
Connection: Keep-Alive
```

Response raw:
```
HTTP/1.1 200 OK
Cache-Control: private
Content-Type: application/json; charset=utf-8
Content-MD5: X3LMlrPNFkHcbeDokl1fJg==
Server: Microsoft-IIS/8.5
X-HttpRequest-Method: GET
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Sat, 29 Apr 2017 16:39:19 GMT
Content-Length: 320

{"Method":"GET","Url":"/Echo.ashx","Headers": {
    "Connection": "Keep-Alive",
    "Content-Type": "text/plain",
    "Host": "corefx-net.cloudapp.net"
  },
  "Cookies": {},
  "BodyContent": "",
  "BodyLength": 0,
  "SecureConnection": false,
  "ClientCertificatePresent": false,
  "ClientCertificate": null
}
```

**Comment by karelz** [comment]
BTW: If you find deficiencies in docs, can you please file bug on docs to track the improvement? Or in CoreFX if it requires work from us to provide the right content first ... thanks!

**Comment by ViktorHofer** [comment]
Yeah 👍 But first we need to clarify if my statement is correct...

**Comment by karelz** [comment]
Sounds ... reasonable ;)

**Comment by karelz** [comment]
Triage: @davidsh can you please try to asnwer @ViktorHofer? Thanks!
