### ISSUE TITLE
Desktop: XmlDictionaryWriterTest.XmlBaseWriter_CheckAsync_ThrowInvalidOperationException failed with "Xunit.Sdk.ThrowsException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18902]
Failed test: XmlDictionaryWriterTest.XmlBaseWriter_CheckAsync_ThrowInvalidOperationException

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/30/testReport/(root)/XmlDictionaryWriterTest/XmlBaseWriter_CheckAsync_ThrowInvalidOperationException/

MESSAGE:
~~~
System.AggregateException : One or more errors occurred.
    ---- Assert.Throws() Failure
    Expected: typeof(System.InvalidOperationException)
    Actual: (No exception was thrown)
~~~
STACK TRACE:
~~~
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) 
at XmlDictionaryWriterTest.XmlBaseWriter_CheckAsync_ThrowInvalidOperationException() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime.Serialization.Xml\tests\XmlDictionaryWriterTest.cs:line 138 
----- Inner Stack Trace -----
~~~

**Comment by shmao** [comment]
The implementation for the method was added on NetCore originally. The test is not applied to netfx. We should skip the test on netfx.

**Comment by shmao** [comment]
@Jiayili1 can you please add [SkipOnFramework..] on the test? Thanks.

**Comment by shmao** [comment]
https://github.com/dotnet/corefx/commit/0671542316520f4ba0a489dff7e163c183eb0135 should have skipped the issue. The test didn't fail in the latest build. Closing the issue.
