### ISSUE TITLE
What are the rules on adding new APIs to CoreFX?

### ISSUE THREAD

**Issue by richlander** [dotnet/corefx#1891]
I saw this: https://github.com/dotnet/corefx/issues/1017#issuecomment-107752252. 

> To expose the RuntimeEnvironment class, it requires updation to the desktop api, which will not come to effect until next desktop release. Hence, the portable version cannot be released, before the desktop 4.6.1 is released, to ensure this contract works on all platforms, which is the same problem we had with PlatformID, we want to decouple ourselves from desktop dependencies and be more quick with releases.

What are the rules that are proposed for updating .NET Core? There are at least a few scenarios:

- Adding new members on a type that exists in the .NET Framework.
- Adding new types that represent a similar concept that exists in the .NET Framework
- Adding new types (new concepts) that do not exist in the .NET Framework.

Ideally, we could update .NET Core at the pace we want. Is the issue that we might add one new member to a type that is represented in contract foo and doing so would make contract foo incompatible with .NET Framework vLatest?

/cc @Priya91, @terrajobst, @davidfowl

**Comment by joshfree** [comment]
tagging as 'ready for api review' so this bubbles up in @terrajobst 's query.

**Comment by terrajobst** [comment]
This is addressed by #5480.
