### ISSUE TITLE
NetCore does not support Canonicalization

### ISSUE THREAD

**Issue by imcarolwang** [dotnet/corefx#18910]
Tests added and verified passed on netfx :

System.Runtime.Serialization.Xml.Canonicalization.Tests.XmlCanonicalizationTest
- C14NWriterNegativeTests
- TestC14NInclusivePrefixes
- ReaderWriter_C14N_DifferentReadersWriters

**Comment by karelz** [comment]
@shmao please add another issue type when you remove one - please refer to [triage rules](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified) for details. Thanks!
