### ISSUE TITLE
Improve error message when x86/64 bit dlls are inadvertently used together

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/corefx#18931]
The current message is bad image format. This doesn't encourage the developer to check for mismatched targets. 

Additional text can resolve this problem.

**Comment by karelz** [comment]
I think it belongs into CoreCLR repo ...

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/coreclr #11298](https://github.com/dotnet/coreclr/issues/11298) via [**ZenHub**](https://www.zenhub.com/)
