### ISSUE TITLE
WMI support in NetStandard 1.5

### ISSUE THREAD

**Issue by jmroyb** [dotnet/corefx#18932]
Folks,

can you tell if WMi is supported in NetStandard 1.5? I cannot find System.Management namespace ....

If not supported, do you plan to supported it and when?

Thanks a million

**Comment by ViktorHofer** [comment]
I doubt it will ever be added to netstandard as WMI is Windows specific. Netstandard (minus a few exceptions) only contains APIs which are cross-platform in nature.

**Comment by karelz** [comment]
Looks like dupe of #14762 to add it into .NET Core.

**Comment by jmroyb** [comment]
Thanks karelz for your update
