### ISSUE TITLE
Helix lacking infrastructure support for running AOT test in app-container.

### ISSUE THREAD

**Issue by tijoytom** [dotnet/corefx#18940]
Need infrastructure support to selectively run test in App Container.

**Comment by danmosemsft** [comment]
We need to decide whether we will do this. I will take a guess that we will not do this for ZBb.

**Comment by danmosemsft** [comment]
dupe https://github.com/dotnet/corefx/issues/18760

**Comment by Jiayili1** [comment]
ActiveIssue, reopen it, test classes and methods:
class ContainsUnknownFilesTests
class CopyFileTests
class CreateDirectoryTests
class CreateFileTests
class DeleteDirectoryTests
class DeleteFileTests
class DirectoryExistsTests
class FileExistsTests
class GetCreationTimeTests
class GetFileNamesTests
class GetLastAccessTimeTests
class GetLastWriteTimeTests
class GetStoreTests
GetDefaultIdentityAndHash
GetDataDirectory
class IdentityTests
class IsolatedStorageBaseClassTests
class IsoStorageTest
class MoveDirectoryTests
class MoveFileTests
class OpenFileTests
class RemoveTests
class CreateSafeFileHandleTests

**Comment by joshfree** [comment]
@Chrisboh is this something you can drive?

/cc @HollyAM @lt72

**Comment by danmosemsft** [comment]
This is not currently scheduled. Perhaps in a future cycle.

**Comment by wtgodbe** [comment]
Closing this as dead, please re-open if it's something that we still want
