### ISSUE TITLE
System.Span<T> constructor Span(IntPtr ptr, int offset, int length)

### ISSUE THREAD

**Issue by CoreyKaylor** [dotnet/corefx#18946]
Does it make sense to have another constructor overload for Span<T> that takes an IntPtr as well for interop with native libraries and memory?

An example of a structure I use for native interop today.

```cs
public struct MDBValue
{
    public IntPtr size;

    public IntPtr data;

    public byte[] GetBytes()
    {
        var buffer = new byte[size.ToInt32()];
        Marshal.Copy(data, buffer, 0, buffer.Length);
        return buffer;
    }

    //just demonstrating the problem
    public Span<byte> GetSpan()
    {
        var bytes = GetBytes();
        //extra allocations this route
        //alternative is dropping to use unsafe, where at least currently the library doesn't require it
        return new Span<byte>(bytes);
    }
}
```
Ideally, I would be able to do the following instead.
```cs
public struct MDBValue
{
        public IntPtr size;

        public IntPtr data;

        public Span<byte> GetSpan()
        {
            return new Span<byte>(data, 0, size.ToInt32());
        }
}
```

Looking at the pointer overload it looks like it's already using an IntPtr internally so I would think it wouldn't be all that difficult to do what I've proposed. I'm not sure though if there are any implications with this approach?

**Comment by benaadams** [comment]
This would work currently?
```csharp
new Span<byte>(data.ToPointer(), size.ToInt32());
```

**Comment by CoreyKaylor** [comment]
@benaadams Yes, technically it would work although it would force me to compile with unsafe options turned on and at this point I have yet to do so. Not the end of the world if that's the outcome, but to me this seemed like a logical addition.

**Comment by benaadams** [comment]
Non-unsafe overload should probably be
```csharp
Span(IntPtr ptr, int length)
```
As ptr is a ptr and includes any offset; so you could do this if you wanted an offset?

```csharp
new Span(IntPtr.Add(data, offset), size.ToInt32());
```

**Comment by CoreyKaylor** [comment]
@benaadams that sounds right, I didn't need the offset myself and was just matching the constructor of pointer constructor as a reference, but what you said makes sense.

**Comment by davidfowl** [comment]
One thing I don't quite understand is when we choose to expose Intptr vs void*' maybe @jkotas or @terrajobst can shed some light

**Comment by jkotas** [comment]
We are only exposing `void*` for any new unsafe APIs. Yes, it requires `unsafe` and that is a good thing.

**Comment by jkotas** [comment]
>  it would force me to compile with unsafe options turned on and at this point I have yet to do so

The `IntPtr` variant does not make your code any bit safer. It is exactly as unsafe as the `void*` variant, except that it is not explicit.

**Comment by CoreyKaylor** [comment]
Yeah, I wasn't making any statements as to safer or not, but rather "I already have one of these" and it seems to be what is used internally to Span. Thanks for the clarification on your previous statement all the same. If your recommendation is to use a pointer directly I'm fine with that. I've already been on the fence for other parts of my api to use other unsafe blocks so this may just push me over the edge to do so.

**Comment by ahsonkhan** [comment]
> We are only exposing `void*` for any new unsafe APIs. 

Can you please provide context around this guideline?

> If your recommendation is to use a pointer directly I'm fine with that.

In that case, do we need this API?

**Comment by jkotas** [comment]
> @jkotas, can you please provide context around this guideline?

We want operations with pointers to be explicit operation with pointers, and not hide them behind IntPtr that tend to give people a false sense of safety.

**Comment by jkotas** [comment]
I do not think we need this API.

**Comment by nxrighthere** [comment]
Maybe you change your mind and provide such API, please? Marshal has almost everything you need to work with `IntPtr` pointers and unmanaged memory without using unsafe code blocks. I really don't see a reason why `Span<T>` cannot do the same. As an example, take a look at [this](https://github.com/nxrighthere/Smmalloc-CSharp#write-data-to-memory-block).

**Comment by davidfowl** [comment]
Why  it just expose Span APIs from smmalloc directly?

**Comment by nxrighthere** [comment]
It's just the same example that is used in Span [docs](https://docs.microsoft.com/ru-ru/dotnet/api/system.span-1?view=netcore-2.1#spant-and-memory). I didn't write any high-level abstractions to stay as low as possible since this is one of the requirements in our project.

Any advice is highly welcome.

**Comment by jkotas** [comment]
> Why it just expose Span APIs from smmalloc directly?

Agree. Or expose APIs that return unmanaged pointers.

For the framework itself, we may consider simplifying these patterns by introducing more APIs that work with Spans or unmanaged pointers. It is unlikely that we will introduce convenience APIs that work with IntPtrs where unmanaged pointer are more appropriate.
