### ISSUE TITLE
Remove UAPAOT cheat in BinaryFormatterHelpers.Clone()

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#18942]
This disables many binary serialization tests on AoT platforms to reduce test noise until we have a real BinaryFormatter story.

**Comment by karelz** [comment]
@AtsushiKan please set areas for new issues based on [area list](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#areas) in future, thanks!

**Comment by AtsushiKan** [comment]
These are the lines that need to be deleted:

https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Runtime/Serialization/Formatters/BinaryFormatterHelpers.cs#L18

https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Runtime/Serialization/Formatters/BinaryFormatterHelpers.cs#L33

**Comment by tijoytom** [comment]
@morganbr @AtsushiKan Now we have binaryformater is this just a case of removing the two lines ?

**Comment by morganbr** [comment]
@tijoytom only sort of. Removing those lines will effectively enable a bunch of tests. We then have to make sure those tests actually pass.
