### ISSUE TITLE
Process_MainModule failed in CI (returned different module than expected)

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1896]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/1532/console
```
System.Diagnostics.ProcessTests.ProcessTest.Process_MainModule [FAIL]
        Assert.Equal() Failure
                   (pos 0)
        Expected: corerun
        Actual:   ntdll
                   (pos 0)
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Diagnostics.Process\tests\System.Diagnostics.Process.Tests\ProcessTest.cs(239,0): at System.Diagnostics.ProcessTests.ProcessTest.Process_MainModule()
```

**Comment by stephentoub** [comment]
@Priya91, since your check-in, the majority of our CI runs have failed due to this, whereas previously we only saw this happen once or twice, total.  I'm going to disable the test for now, but please take a look.  My hypothesis: the underlying Windows support can return a partial collection if queried at just the wrong time during process start up.  If that's the case, then it would explain why your change made this so much more common.  Previously we would try get the modules, and if we couldn't get any, we would exit the test.  That made it very binary, and the only way it would fail with this error is if the one time we accessed the modules we happened to hit it at exactly the wrong moment.  But with your change, if we can't get any modules, we repeatedly ask for the modules until we can, which makes it much more likely that we're going to ask for the modules at just the wrong time.

**Comment by pallavit** [comment]
We seem to have stable Process tests now, So, I will go ahead and close this one :)
