### ISSUE TITLE
Unable to run new app:  System.DllNotFoundException: Unable to load DLL 'api-ms-win -core-registry-l1-1-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by dannyb2100** [dotnet/corefx#18976]
Sorry if that has been previously addressed or answered, could not find an applicable solution.

The default generated web app with visual studio.

```
C:\Projects\DotNetCoreTest\WebApplication\WebApplication\bin\Debug\netcoreapp1.1
\win10-x64>C:\Projects\DotNetCoreTest\WebApplication\WebApplication\bin\Debug\ne
tcoreapp1.1\win10-x64\WebApplication.exe

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'api-ms-win
-core-registry-l1-1-0.dll': The specified module could not be found. (Exception
from HRESULT: 0x8007007E)
   at Interop.mincore.RegOpenKeyEx(SafeRegistryHandle hKey, String lpSubKey, Int
32 ulOptions, Int32 samDesired, SafeRegistryHandle& hkResult)
   at Microsoft.Win32.RegistryKey.InternalOpenSubKeyCore(String name, RegistryRi
ghts rights, Boolean throwOnPermissionFailure)
   at Microsoft.AspNetCore.DataProtection.RegistryPolicyResolver.ResolveDefaultP
olicy()
   at Microsoft.Extensions.DependencyInjection.DataProtectionServices.<GetDefaul
tServices>d__0.MoveNext()
   at Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescr
iptorExtensions.TryAdd(IServiceCollection collection, IEnumerable`1 descriptors)

   at Microsoft.Extensions.DependencyInjection.DataProtectionServiceCollectionEx
tensions.AddDataProtection(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcViewFeaturesMvcCoreBuilderExte
nsions.AddViewServices(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcViewFeaturesMvcCoreBuilderExte
nsions.AddViews(IMvcCoreBuilder builder)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.Ad
dMvc(IServiceCollection services)
   at WebApplication.Startup.ConfigureServices(IServiceCollection services) in C
:\Projects\DotNetCoreTest\WebApplication\WebApplication\Startup.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(ISer
viceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at WebApplication.Program.Main(String[] args) in C:\Projects\DotNetCoreTest\W
ebApplication\WebApplication\Program.cs:line 14
```

**Comment by karelz** [comment]
@gkhanna79 @janvorli looks like API set problem. Do you have any insight?

**Comment by gkhanna79** [comment]
This is a PInvoke in Interop layer of CoreFX for 1.1.0 where APISets are present. Someone in CoreFX should take an initial stab at this.

CC @weshaggard

**Comment by janvorli** [comment]
@dannyb2100 one additional question - which Windows version are you using?

**Comment by tarekgh** [comment]
@dannyb2100 could you tell what version of Windows you are running on? I guess it should be Windows 7. 

also could you try reference the package https://www.nuget.org/packages/Microsoft.NETCore.Windows.ApiSets/ and see if this will help?

**Comment by tarekgh** [comment]
CC @ericstj

**Comment by tarekgh** [comment]
@gkhanna79 

> This is a PInvoke in Interop layer of CoreFX for 1.1.0 where APISets are present

Do you mean 1.1.0 package containing the APISets? it looks the complain here is the APISet is not present

**Comment by gkhanna79** [comment]
> it looks the complain here is the APISet is not present

In this case, it maybe a bug in CoreFX as it is trying to pinvoke into an APISet that was never supported.

**Comment by tarekgh** [comment]
> In this case, it maybe a bug in CoreFX as it is trying to pinvoke into an APISet that was never supported.

I have looked at the package https://www.nuget.org/packages/runtime.win7-x64.Microsoft.NETCore.Windows.ApiSets/ and the APISet api-ms-win
-core-registry-l1-1-0.dll is there. My question is, does 1.1 include such package or does it have its own APISet package?

**Comment by gkhanna79** [comment]
I believe they all use the same package (see https://github.com/dotnet/coreclr/blob/release/1.1.0/dependencies.props#L21).

**Comment by karelz** [comment]
@tarekgh you moved it into 1.x. Do you know if we have the same problem in 2.0?

**Comment by tarekgh** [comment]
> you moved it into 1.x. Do you know if we have the same problem in 2.0?

No, we don't have the same problem in v2 because we are not using the APISets anymore. instead we are using the system DLLs. here is example 

https://github.com/dotnet/corefx/blob/c55435befeb372707558a5c441b3c64bf243948f/src/Common/src/Interop/Windows/advapi32/Interop.RegOpenKeyEx.cs#L13

**Comment by tarekgh** [comment]
@dannyb2100 could you please answer the questions we asked in this issue to know if we can help with it?

**Comment by dannyb2100** [comment]
@tarekgh, Sorry about the lack of replies. For some reason, I was not getting an email notification about replies! 

I am running Windows 7

**Comment by tarekgh** [comment]
@dannyb2100 thanks for your reply. could you please help with the questions:

- Could you try to find if the DLL api-ms-win-core-registry-l1-1-0.dll exist in your system anywhere too?
- Could you try reference the package https://www.nuget.org/packages/Microsoft.NETCore.Windows.ApiSets/ and see if this will help?
- if you can share a small project to repro the issue that will be very helpful. 

thanks again

**Comment by dannyb2100** [comment]
Hey @tarekgh, could not find 'api-ms-win-core-registry-l1-1-0.dll' on my system, but added 'Microsoft.NETCore.Windows.ApiSets' and it runs as expected now. 

Thanks again :)

**Comment by karelz** [comment]
Cool. So can we close?

Also I wonder if there is some documentation we should update to make it easier for others? Or was it more one off project-specific problem? Or just a rare problem?

**Comment by tarekgh** [comment]
@gkhanna79 could you please double check why 'api-ms-win-core-registry-l1-1-0.dll was missing in this case? I am expecting all dependency should be installed on windows 7 for 1.1. right?

**Comment by gkhanna79** [comment]
If the apiset package contains it, it should be there. Is there a repro for it?


Thanks,
Gaurav
________________________________

**Comment by tarekgh** [comment]
@dannyb2100 could you please provide a simple repro project to @gkhanna79 ? Thanks

**Comment by dannyb2100** [comment]
@tarekgh, before or after I referenced the package https://www.nuget.org/packages/Microsoft.NETCore.Windows.ApiSets ?

**Comment by tarekgh** [comment]
@dannyb2100 before you reference the APISet package. we need to see the problem happening.

**Comment by dannyb2100** [comment]
@tarekgh, repo created and invite sent.

**Comment by karelz** [comment]
@dannyb2100 people tend to post gists and provide link publicly, so that anyone can jump in. Any chance to do that?

**Comment by tarekgh** [comment]
[coreFx-tarekgh-master.zip](https://github.com/dotnet/corefx/files/984080/coreFx-tarekgh-master.zip)

**Comment by tarekgh** [comment]
@gkhanna79 could you please have a look at the attached zip?

**Comment by gkhanna79** [comment]
@ramarag Can you PTAL?

**Comment by tarekgh** [comment]
@ramarag just checking if you had a chance to take a look?
