### ISSUE TITLE
Add option to HttpClientHandler to validate certificates against custom root certificate authorities 

### ISSUE THREAD

**Issue by rolftimmermans** [dotnet/corefx#18972]
To validate a server certificate against a set of root certificates (instead of the system certificates), we are now limited to using ServerCertificateCustomValidationCallback. Unfortunately this callback does not work on all systems due to incompatibilities described in #9728, and it seems there are some blockers to fixing them on some platforms.

It may be easier for users to just be able to provide a file path to a set of root certificates (encoded as PEM), or have another API to provide custom root certificates to use for validation instead of the system root certificates.

One idea suggested in https://github.com/dotnet/corefx/issues/9728#issuecomment-297201090 is:

```
httpHandler.ServerCertificateRootCaFile = "/.../ca.pem";
```

Another option would be to provide custom instances of `X509Certificate2`.

**Comment by karelz** [comment]
Can you please summarize the API shape (see [API review](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md) - esp. sample)

**Comment by karelz** [comment]
Also more comments on scenarios, how common they are and workarounds ... - see https://github.com/dotnet/corefx/issues/9728#issuecomment-297118858

**Comment by rolftimmermans** [comment]
Some suggestions:

**Option 1: Provide the path to a PEM-encoded certificate bundle (example file: https://curl.haxx.se/ca/cacert-2017-01-18.pem)**

```var handler = new HttpClientHandler();
handler.UseSystemRoots = false; /* Do not validate against system roots. */
handler.CustomRootCertificateBundlePath = "ca.pem"; /* Validate against certificates in provided bundle. */
```

**Option 2: Allow adding to a list of X509Certificate2 root certificates.**

```var handler = new HttpClientHandler();
var myCaCert = new X509Certificate2(certBuffer);
handler.UseSystemRoots = false; /* Do not validate against system roots. */
handler.CustomRootCertificates.Add(myCaCert) /* Validate against certificates in IList (or something similar). */
```

**Comment by davidsh** [comment]
>To validate a server certificate against a set of root certificates (instead of the system certificates), we are now limited to using ServerCertificateCustomValidationCallback. Unfortunately this callback does not work on all systems due to incompatibilities described in #9728, and it seems there are some blockers to fixing them on some platforms.

From an API perspective, the ServerCertificateCustomValidationCallback is all you need.  It allows for complete custom validation using whatever criteria you want.

The problem being described is an implementation issue with how it works...it is not a problem with the API design itself.  Adding another API as suggested above is trying to solve an implementation problem, not an API design problem.

cc: @terrajobst

**Comment by karelz** [comment]
.NET Core 2.1 ships by default with SocketsHttpHandler which enables ServerCertificateCustomValidationCallback on all platforms. We should not need a new API to work around the platform limitations anymore.
