### ISSUE TITLE
system.security.cryptography.xml.tests failed

### ISSUE THREAD

**Issue by v-haren** [dotnet/corefx#18974]
https://ci.dot.net/job/dotnet_corefx/job/master/job/debian8.4_release/2089/consoleFull#178427296579fe3b83-f408-404c-b9e7-9207d232e5fc

**Comment by bartonjs** [comment]
@mellinoe We got a segfault with no stack trace.  Is that a known happenstance?

It looks like the coredump did get uploaded.  Do we have a good way of working with them? (Like, can we recover the binaries for the CI job? (or do we need to?))

**Comment by ianhays** [comment]
fyi this failed yesterday right around the time when Jenkins was failing legs left and right. It's possible that the failure is related to that in some way.

**Comment by stephentoub** [comment]
Let's close this under the assumption it was infrastructure.  We lack any other means of investigating this one occurrence (the mentioned logs are gone).
