### ISSUE TITLE
Fix and Reenable EventSource tests on Desktop Runtime

### ISSUE THREAD

**Issue by vancem** [dotnet/corefx#18984]
In PR #18965 some EventSource tests were disabled on Destkop because the tests were looking at internal items that were not on the Desktop runtime

This issue tracks fixing the test and enable these tests on Desktop 

@brianrob

**Comment by safern** [comment]
I just updated my PR to fix the test instead of disabling it. Please see my latest commit: https://github.com/dotnet/corefx/pull/18965/commits/fe72b03f4d1b3d110e633caa55425d0dfa434b65

**Comment by safern** [comment]
So this can be closed if you consider that is the correct fix.

**Comment by vancem** [comment]
Turns out @safern already did the work.
