### ISSUE TITLE
SqlClient hangs while opening connection on localdb with MARS enabled

### ISSUE THREAD

**Issue by smitpatel** [dotnet/corefx#18997]
csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.4.0-*" />
  </ItemGroup>
  
</Project>
```
Program.cs
```
using System;
using System.Data.SqlClient;

namespace SqlClientIssue
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Start!");
            //AppContext.SetSwitch("System.Data.SqlClient.UseLegacyNetworkingOnWindows", true);

            var connectionString =
                @"Data Source=(localdb)\MsSqlLocalDb;Database=master;Connect Timeout=5;MultipleActiveResultSets=true";

            using (var connection = new SqlConnection(connectionString))
            {
                connection.Open();
                Console.WriteLine("ServerVersion: {0}", connection.ServerVersion);
                Console.WriteLine("State: {0}", connection.State);
            }

            Console.WriteLine("Hello World!");

        }
    }
}
```

Expected output: Successful run.
Actual output: Program hangs after printing Start!. No communication is received by SqlServer (using Sql Profiler)

dotnet
```
.NET Command Line Tools (2.0.0-preview1-005846)

Product Information:
 Version:            2.0.0-preview1-005846
 Commit SHA-1 hash:  6dd6192155

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\smpatel\.dotnet\x64\sdk\2.0.0-preview1-005846\
Microsoft .NET Core Shared Framework Host
  Version  : 2.0.0-preview1-002061-00
  Build    : 2b70ec9c3b014af0c2a5f45de0e5b73a1ae51c09
```
SqlServer version 13.0.2151

The program runs fine with one of the following changes.
- Using external server instead of localdb
- Disabling MARS
- Using System.Data.Common 4.3.0 package
- Using native code for connection via `AppContext.SetSwitch("System.Data.SqlClient.UseLegacyNetworkingOnWindows", true);`

**Comment by ajcvickers** [comment]
@saurabh500 This is blocking the ability for ASP.NET to use 4.4 of the package, which is currently critical path for preview1, so this is high priority to get fixed. If it can't be fixed very quickly, can you flip the switch to use managed networking so that ASP.NET builds are not blocked?

/cc @Eilon @divega

**Comment by corivera** [comment]
Looking into it

**Comment by Petermarcu** [comment]
@corivera, let us know as soon as you have an ETA for a fix. Thanks for looking into it.

**Comment by corivera** [comment]
Fixed with https://github.com/dotnet/corefx/pull/19022

**Comment by stephentoub** [comment]
Actually, re-opening to track port to release/2.0 branch

**Comment by saurabh500** [comment]
Ported to release in https://github.com/dotnet/corefx/pull/19035
Shiproom email is pending.
