### ISSUE TITLE
Doc: workaround guidance for #8538 regarding multiple TLS protocols

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#19001]
Need to write documentation guidance for workaround for #8538.
"WinHttpHandler not updating response state with error from server when client supports multiple TLS protocols"

**Comment by davidsh** [comment]
cc: @karelz

**Comment by karelz** [comment]
Thanks @davidsh!

**Comment by davidsh** [comment]
Not useful to track this anymore.
