### ISSUE TITLE
Calling methods on default(ImmutableArray) unpredictable on UwpAOT

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#19016]
This helper (<a href="https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.Minimal.cs#L397">ImmutableArray<T>.ThrowNullRefIfNotInitialized()</a>) is supposed to ensure a NullReferenceException if you call a method on an uninitialized ImmutableArray.

It's coded to be performant.

On .NET Native (with "/buildtype:ret" passed to ILC), it's **really** performant.

As in, it gets optimized away entirely.

As a result, many tests in System.Collections.Immutable.Tests that test this guard fail. 

cc @davidwrighton - in case he has any guidance on how to avoid this.

**Comment by MichalStrehovsky** [comment]
@AtsushiKan I can't find a TFS bug for this - you should file one on the native codegen team - this is an invalid codegen optimization because it doesn't consider the side effects of the access.

It also reproes with e.g.:

```csharp
    class Foo
    {
        public int X;
    }

    Foo a = null;
    var unused = a.X;
```

**Comment by AtsushiKan** [comment]
Opened TFS 428550 - closing this issue as we'll track the work there.
