### ISSUE TITLE
Desktop: System.Security.Cryptography.Encryption.Aes.Tests.AesContractTests/ValidateDecryptorProperties  failed with "System.Security.Cryptography.CryptographicException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#19023]
Failed test: System.Security.Cryptography.Encryption.Aes.Tests.AesContractTests/ValidateDecryptorProperties 
 
Message:
~~~
System.Security.Cryptography.CryptographicException : Decrypting a value requires that a key be set on the algorithm object.
~~~

Stack Trace:
~~~
at System.Security.Cryptography.AesCryptoServiceProvider.CreateDecryptor()
   at System.Security.Cryptography.Encryption.Aes.Tests.AesContractTests.ValidateDecryptorProperties() in E:\A\_work\82\s\corefx\src\Common\tests\System\Security\Cryptography\AlgorithmImplementations\AES\AesContractTests.cs:line 202
~~~

Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170427.01/workItem/System.Security.Cryptography.Algorithms.Tests/analysis/xunit/System.Security.Cryptography.Encryption.Aes.Tests.AesContractTests~2FValidateDecryptorProperties

**Comment by danmosemsft** [comment]
@bartonjs do we expect this test to fail in tihs way on desktop?

**Comment by bartonjs** [comment]
That's a tricky question, Dan :smile:.  I certainly didn't "expect" it, and of all of the SymmetricAlgorithm objects this appears to be a unique behavior to AesCryptoServiceProvider; but it's definitely what the code says: http://referencesource.microsoft.com/#System.Core/System/Security/Cryptography/AesCryptoServiceProvider.cs,144

I guess in our AesCSP wrapper in corefx we could (should?) emulate this state by something like

```C#
public override byte[] Key
{
    get { return _impl.Key; }

    set
    {
        _impl.Key = value;
        _hasKey = true;
    }
}

public override int KeySize
{
    get { return _impl.KeySize; }

    set
    {
        _impl.KeySize = value;
        _hasKey = false; // even on setting it to the same value, apparently
    }
}
```

Pretty much tracking the m_key flow from netfx: http://referencesource.microsoft.com/#System.Core/System/Security/Cryptography/AesCryptoServiceProvider.cs,710bfe3ff24e26d9,references

Then, in CreateDecryptor() (but not CreateDecryptor(byte[], byte[])) throw if _hasKey is false.  And then make this test understand that AesCSP is special.

Pure compat says we should do it.  Not sure what cost/benefit says.

**Comment by danmosemsft** [comment]
Moving to 2.0 for you to decide for 2.0

**Comment by bartonjs** [comment]
After talking with @karelz this seems like it's probably not worth fixing.  We should just note it on the platform differences page.

1) We don't *really* have AesCryptoServiceProvider
2) It's the only SymmetricAlgorithm implementation in all of .NET with this behavior.

So in corefx we're just making AesCryptoServiceProvider act more like the rest of the platform.  If people complain we can always revisit it.

**Comment by karelz** [comment]
Key decision points for me:
* 97% customers use another API
* The different behavior is only error path - so typically affects "just" dev-cycle error detection. Those who depend on thrown exception in production should be very few (if any at all).
* It is costly (and ugly) to fix it in .NET Core

Overall it feels more in the bug-by-bug compatibility, rather than useful compat. So unless there is strong pushback, I would wait for further customer feedback. If it is migration painpoint, we can change it later (e.g. in servicing) ...

Please add compat entry here: https://github.com/dotnet/corefx/wiki/ApiCompat (assuming no one pushes back).

**Comment by danmosemsft** [comment]
Disable the whole AesContractTests.CreateTransformExceptions for desktop then?

**Comment by bartonjs** [comment]
@danmosemsft `ValidateDecryptorProperties` is what this issue says failed, not `CreateTransformExceptions`.

We can disable the test, or do something like

```diff
        [Fact]
        public static void ValidateDecryptorProperties()
        {
            using (Aes aes = AesFactory.Create())
            {
+               // The default AES provider on NetFx has an extra exception if
+               // CreateDecryptor is called without set_Key being called.
+               // So give it a key.
+               aes.Key = new byte[16];
                ValidateTransformProperties(aes, aes.CreateDecryptor());
            }
        }
```
