### ISSUE TITLE
[Suggestion] Add "Time-based" Class to enhance the "WeakReference"

### ISSUE THREAD

**Issue by MaleDong** [dotnet/corefx#1903]
Hello all:

In asp.net we have Cache, this can be automatically set "timeout" and release its memory by setting dependency such as "Timespan", "file"..... However in other situations we don't have such functions yet.

It would be better if we have such a  "Time-based" class, and it will automatically release many "short-period-timed" variable, something like WeakReferece (However, WeakReference doesn't have a time-based foundation yet, and we cannot control how long it will be released).

In my mind, this can be designed something like this following:

```
 public sealed class TimeBasedValue<T> :IDisposable where T:class
 {
     //An absolute time that bombs up the value
     public TimeBasedValue (T value, DateTime span){……}

     // Absolute/Relative time for bombing up the value
     public TimeBasedValue (T value, int timePeriod, Mode mode, Unit unit) {……}

     //When time is overdue, this value must be null
     public T Value{get;}

     //"Mode" is an enum that shows how the time period is calculated: Absolute, Relative to the last      access....
     public Mode TimeMode{get;}

     // Hour, Minute, Second or Millsecond?
     public Unit Unit{get;}

//This will be called once the time is overdue, and it will first check whether the Value has  implemented "IDisposable" or not, if yes, call it first. However no matter what happens, the Value should be set to null 
    public void Dispose()
    {
         var value = Value;
         IDisposable idisp = value as IDisposable ;
          try
          {
                if(idisp!=null)
                {
                    idisp.Dispose();
                }
          }
          finally
          {
                idisp = null;
          }
  }
 }
```

**Comment by svick** [comment]
Is anything stopping you from implementing this yourself, possibly by using `ObjectCache` in the implementation?

**Comment by MaleDong** [comment]
@svick : Do you mean using "MemoryCache"?
Yes, however this class is created since 4.0, and maybe net framework's 2.0/3.5 will need it. And this is very important used in a frequent-taken situation and release it automatically. So this can be reguarded as an extended package into Microsoft's NuGet.

**Comment by svick** [comment]
>  Do you mean using "MemoryCache"?

Yeah, pretty much. `ObjectCache` is the base class of `MemoryCache`, but I guess other implementations of `ObjectCache` wouldn't make much sense here.

**Comment by mj1856** [comment]
It should use `DateTimeOffset`, not `DateTime`.

**Comment by terrajobst** [comment]
@KrzysztofCwalina , is that related to object pooling.

**Comment by MaleDong** [comment]
Well……In Java you know that it has NOT ONLY weak reference, but soft reference……and other types.
I need a class that can be both controlled by TimeSpan or let it "disposed" itself automatically when memory/CPU is busy or taken much on different levels.

**Comment by karelz** [comment]
Based on the comments above and low interest, I would suggest to close this one. There are some workarounds and it is not super clear that this will bring huge value.
If you feel we missed your point, feel free to reopen with additional details and justification.

**Comment by MaleDong** [comment]
@karelz ：Sorry because of my busy work and I didn't give you a continuable response.
Now I wanna know more about your milestone Future 1.2.0：

1) What do you wanna add this feature? What features should it contain by your ideas?
2) In fact I mean that though .NET can collection by using GC.Collect() however sometimes when we create a huge thing taking a huge memory, and we should release it soon. Maybe the best solution for us is to use WeakReference or something like this. Dispose() can be called directly but GC cannot collect the garbages as soon as once it gets called. 

So I mean that we can:

  1. Create a WeakReference that is limited by TimeSpan or an absolute seconds, minutes, hours……ect.
  2. When the time is overdue, we DON'T need to directly call "Dispose" but it will call automatically, and the memory will be released as soon as once it gets called.
