### ISSUE TITLE
ArgumentException from GetFullPath should include the path

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#19033]
In a case such as the below it would be helpful if the message was something like `The path "C:|" is not of a legal form.`. Seems reasonable to add it unless there's some kind of information disclosure issue (I don't know why, we don't generally cleanse our exception messages)

```
System.ArgumentException : The path is not of a legal form.
Stack Trace :
   at System.IO.Path.GetFullPath(String path)
   at System.IO.FileInfo.Init(String fileName)
   at System.IO.FileInfo..ctor(String fileName)
   at MonoTests.System.Configuration.ConfigurationManagerTest.OpenExeConfiguration1_UserLevel_PerUserRoamingAndLocal()
```

**Comment by JeremyKuhne** [comment]
Not opposed, this is generally a left over from limited trust scenarios on desktop.

**Comment by danmosemsft** [comment]
There are probably several other exceptions that could usefully include paths.

**Comment by danmosemsft** [comment]
Also  this one.
   throw new NotSupportedException(SR.Argument_PathFormatNotSupported);

    ---> System.NotSupportedException: The given path's format is not supported.
       at System.IO.Path.GetFullPath(String path)
       at System.IO.Directory.SetCurrentDirectory(String path)

**Comment by danmosemsft** [comment]
Also 
 1183:   <data name="Argument_InvalidPathChars" xml:space="preserve">
 1184      <value>Illegal characters in path.</value>

Basically almost all the "throw new xxx" in Path*.cs.

**Comment by danmosemsft** [comment]
`   throw new PathTooLongException(SR.IO_PathTooLong + fullPath.ToString());` is clearly wrong.

**Comment by JeremyKuhne** [comment]
> throw new PathTooLongException(SR.IO_PathTooLong + fullPath.ToString()); is clearly wrong.

Yes, we should be creating formatted string resources for these where we don't have them. Many already have a "with path" and "without path" version. Some of them may already exist in other places- checking the desktop mscorlib is something that is worth doing.
