### ISSUE TITLE
Desktop: System.Security.Cryptography.Rsa.Tests.ImportExport.ExportAutoKey failed with "System.Security.Cryptography.CryptographicException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#19040]
Failed test: System.Security.Cryptography.Rsa.Tests.ImportExport.ExportAutoKey

Configuration: outerloop_netfx_windows_nt_debug

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/32/testReport/System.Security.Cryptography.Rsa.Tests/ImportExport/ExportAutoKey/

MESSAGE:
~~~
System.Security.Cryptography.CryptographicException : The requested operation is not supported.\r\n
~~~
STACK TRACE:
~~~
at System.Security.Cryptography.NCryptNative.ExportKey(SafeNCryptKeyHandle key, String format) 
at System.Security.Cryptography.CngKey.Export(CngKeyBlobFormat format) 
at System.Security.Cryptography.RSACng.ExportParameters(Boolean includePrivateParameters) 
at System.Security.Cryptography.Rsa.Tests.ImportExport.ExportAutoKey() 
in D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\Security\Cryptography\AlgorithmImplementations\RSA\ImportExport.cs:line 26
~~~

**Comment by danmosemsft** [comment]
@bartonjs another desktop failure needing your wisdom. breaking? or disable the test?

**Comment by bartonjs** [comment]
Another 4.6.2 fix.  People should really upgrade :).

Disabling seems fine.

**Comment by danmosemsft** [comment]
@safern I can't remember , do we have a way to disable a test just for <=4.6.1? It would be nice if the test just lit up when we moved xunit forward.

**Comment by safern** [comment]
@bartonjs is this a quirked behavior?

**Comment by bartonjs** [comment]
https://referencesource.microsoft.com/#System.Core/System/Security/Cryptography/RsaCng.cs,90 Nope

**Comment by safern** [comment]
> @safern I can't remember , do we have a way to disable a test just for <=4.6.1?

Nope, we can only disable for latest framework. `SkipOnTargetFramework(TargetFrameworkMonikers.NetFramework` will skip always when TargetGroup == netfx (which runs against latest installed framework in the computer that we are running)

**Comment by ianhays** [comment]
similar to #19042. I'll take these if you're not already working on them @safern.

**Comment by safern** [comment]
@ianhays I was just investigating this, we could parse `RuntimeInformation.FrameworkDescription` to see if the version is < 462 and if so return; to skip the test. Could you take these one?

**Comment by safern** [comment]
Because if the running computer has 461 as the latest Framework it will fail.

**Comment by safern** [comment]
Actually this one: #19041 is on this test method as well. Which I'm already fixing, so both should be fixed with my change. So assigning to myself -- @ianhays

**Comment by Jiayili1** [comment]
This issue is repro on desktop, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/38/testReport/System.Security.Cryptography.Rsa.Tests/ImportExport/UnusualExponentImportExport/

**Comment by danmosemsft** [comment]
The above is adifferent test. Opening a new issu.e
