### ISSUE TITLE
Test: System.IO.Tests.DirectoryInfo_Create/CDriveCase failed with "System.IO.DirectoryNotFoundException"

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#19056]
In behalf of @Jiayili1, moved from https://github.com/dotnet/corefx/issues/11687#issuecomment-297624327

This issue is repro on UWP F5 Tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20170427.01/workItem/System.IO.FileSystem.Tests/analysis/xunit/System.IO.Tests.DirectoryInfo_Create~2FCDriveCase

Message :
System.IO.DirectoryNotFoundException : Could not find a part of the path 'c:\'.

Stack Trace :
at System.IO.Win32FileSystem.CreateDirectory(String fullPath)
at System.IO.Tests.DirectoryInfo_Create.Create(String path)
at System.IO.Tests.Directory_CreateDirectory.CDriveCase()

**Comment by danmosemsft** [comment]
appcontainer .. disable this case for uwp...
