### ISSUE TITLE
I want to implement Ssl​Stream in Core console applicaiton

### ISSUE THREAD

**Issue by Edward-Zhou** [dotnet/corefx#19077]
I followed this [Ssl​Stream Class](https://docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslStream?view=netcore-1.1&viewFallbackFrom=netcore-1.1.0), but it is applied to Core 2.0 which has not been released.
Is there any document for Core 1.0 to use SslStream?
Thanks for your help.

**Comment by davidsh** [comment]
SslStream class is available in .NET Core 1.0 and 1.1.  It is in the System.Net.Security NuGet package/library.

**Comment by davidsh** [comment]
>Below code did not work under Core 1.1 in VS2017.

What didn't work exactly?  Did it compile?  Did you get errors?

cc: @karelz

**Comment by Edward-Zhou** [comment]
I got below errors:
1.the type or namespace name 'Hashtable' could not be found
I tried "using Hashtable = System.Collections.Generic.Dictionary<object, object>;"
2.'TcpClient' does not contain a constructor that takes 2 arguments
I tried `            TcpClient client = new TcpClient();
            client.ConnectAsync(machineName,443).Wait();`
3.'SslStream' does not contain a definition for 'AuthenticateAsClient'
I tried `                sslStream.AuthenticateAsClientAsync(serverName);
`
4.client.Close(); there is no client.Close()
I tried `client.Dispose();`.
Now, there is no error when compile. But I am not sure whether it will work. Is there any problem with my above changes?

**Comment by davidsh** [comment]
The issues you have above are related to new work (more APIs available) in .NET Core 2.0.  The APIs you're trying to use aren't available except in the .NET Core 2.0 release.

If you need your code above to work for .NET Core 1.0 or 1.1, you'll need to modify it to use only those APIs available in those releases.  Otherwise, please try out the .NET Core 2.0 builds from the daily build feed or wait a few weeks until an official preview of .NET Core 2.0 is released.

cc: @stephentoub

**Comment by davidsh** [comment]
If you have a bug after changing your code to use just .NET Core 1.0/1.1 APIs, please open up a new issue and attach your repro code, preferably as a complete Visual Studio solution.  Thanks!

**Comment by karelz** [comment]
If you want to try out .NET Core 2.0 early builds, please follow these instructions: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md

**Comment by karelz** [comment]
You can also check the .NET Portability Analyzer: https://docs.microsoft.com/en-us/dotnet/articles/standard/portability-analyzer it should give you .NET Core 2.0 and .NET Standard 2.0 information (I hope at least).

Here is official/public ship dates information about .NET Core 2.0: https://github.com/dotnet/core/blob/master/roadmap.md#ship-dates
