### ISSUE TITLE
System.Text.Encoding.Extensions.Tests aren't running on Linux

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1907]
The oddly-structured project hierarchy employed by System.Text.Encoding.Extensions (https://github.com/dotnet/corefx/pull/1700#discussion_r30080150) is causing failures in the logic around what tests to run on Linux, such that the System.Text.Encoding.Extensions.Tests aren't being found or run.

Once that's addressed, ~60 of the ~120 tests are currently failing on Unix, presumably because of #846.

cc: @venkat-raman251, @mmitche

**Comment by venkat-raman251** [comment]
Will change the structure and mark the failing tests now.

**Comment by stephentoub** [comment]
Thanks, Venkat.  I've marked the failing tests with PR #1908.

**Comment by stephentoub** [comment]
Fixed with #1908 and #1916
