### ISSUE TITLE
Desktop: System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.EdgeCasesTests.ZeroLengthContent_FixedValue failed with "System.Security.Cryptography.CryptographicException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#19090]
Failed test: System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.EdgeCasesTests.ZeroLengthContent_FixedValue

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/34/testReport/System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests/EdgeCasesTests/ZeroLengthContent_FixedValue/

Configuration: outerloop_netfx_windows_nt_debug

MESSAGE:
~~~
System.Security.Cryptography.CryptographicException : Invalid provider type specified.\r\n
~~~
STACK TRACE:
~~~
at System.Security.Cryptography.Pkcs.EnvelopedCms.DecryptContent(RecipientInfoCollection recipientInfos, X509Certificate2Collection extraStore) 
at System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.EdgeCasesTests.ValidateZeroLengthContent(Byte[] encodedMessage) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Cryptography.Pkcs\tests\EnvelopedCms\EdgeCasesTests.cs:line 174 
at System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.EdgeCasesTests.ZeroLengthContent_FixedValue() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Cryptography.Pkcs\tests\EnvelopedCms\EdgeCasesTests.cs:line 125
~~~

**Comment by ianhays** [comment]
[The log with that failure](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/34/consoleFull) shows 12 tests failing in the Pkcs test assembly, all with this same failure.

I cannot repro those failures locally.

**Comment by krwq** [comment]
@ianhays possibly got fixed or intermittent. Let's reopen if it repros for anyone again

**Comment by Jiayili1** [comment]
This issue is repro on desktop, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/40/testReport/System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests/EdgeCasesTests/ZeroLengthContent_FixedValue/

**Comment by ianhays** [comment]
Looks like these are failing on net461 and passing on net462 from a non-quirked fix. I'll put up a PR disabling them on <net462.
