### ISSUE TITLE
Desktop: BasicEventSourceTests.TestsManifestNegative.Test_GenerateManifest_InvalidEventSources failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by KristinXie1** [dotnet/corefx#19091]
Failed test: BasicEventSourceTests.TestsManifestNegative.Test_GenerateManifest_InvalidEventSources

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/34/testReport/BasicEventSourceTests/TestsManifestNegative/Test_GenerateManifest_InvalidEventSources/

Configuration: outerloop_netfx_windows_nt_debug

MESSAGE:
~~~
Assert.Equal() Failure
     ↓ (pos 135)
    Expected: ··· NonEvent attribute.
    Actual: ··· NonEvent attribute.\\r\\nMultiple definitions for string \"task_W···
     ↑ (pos 135)
~~~
STACK TRACE:
at BasicEventSourceTests.TestsManifestNegative.Test_GenerateManifest_InvalidEventSources() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\TestsManifestNegative.cs:line 145

**Comment by vancem** [comment]
@safern - is this the test you just enabled?

**Comment by safern** [comment]
Yes -- it is the one I "fixed" on: https://github.com/dotnet/corefx/pull/18965

**Comment by safern** [comment]
I can't get a local.

**Comment by vancem** [comment]
including @brianrob 

This looks like the test is just being a bit to picky about the exact error message.    Should be easy to fix but there may be several of the same type of issue 'behind' this one, so we need a nice local repro for @brianrob to look at.     We may wish to disable the test and log an issue to reenable it if we don't have time to fix it (these negative tests are not the highest prioirty).

**Comment by vancem** [comment]
Don't forget to re-enable the test after this is fixed (disabled with #19291)

**Comment by stephentoub** [comment]
FWIW, this passes for me when I run it locally.

**Comment by safern** [comment]
@stephentoub it is a flaky test, it doesn't fail on every build. I can't get a local repro either.

**Comment by brianrob** [comment]
This is a desktop bug - moving to future.

**Comment by safern** [comment]
Closing as this is in desktop.
