### ISSUE TITLE
Error while building CoreFx on Windows

### ISSUE THREAD

**Issue by saurabh500** [dotnet/corefx#19115]
I am trying to build CoreFx on Windows. I have synced the latest code and using build.cmd from the root of the repository. 

However the build fails with 
`Unhandled Exception: System.TypeLoadException: Could not load type 'System.Object' from assembly 'System.Runtime, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.`

I have cleaned the clone using `git clean -d -f -x `
I get the following

```
F:\netcore\corefx>build.cmd
Installing dotnet cli...
Restoring BuildTools version 2.0.0-prerelease-01528-02...
Initializing BuildTools...
Done initializing tools.

Unhandled Exception: System.TypeLoadException: Could not load type 'System.Object' from assembly 'System.Runtime, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

OS Windows Server 2012 R2

How do I get past this problem?

**Comment by saurabh500** [comment]
@mellinoe Do you have any pointers for this issue?

**Comment by karelz** [comment]
cc @weshaggard

**Comment by saurabh500** [comment]
I got around the issue by deleting the Nuget package cache and .donet folder from user profile.
This started happening after I built EF on my dev machine
