### ISSUE TITLE
Test System.Linq.Expressions.Tests.ParameterTests.ReadAndWriteRefParameters causes FailFast on AoT

### ISSUE THREAD

**Issue by alexperovich** [dotnet/corefx#19129]

**Comment by danmosemsft** [comment]
@safern similar to https://github.com/dotnet/corefx/issues/20717 does this still repro for you? I can't get the tests on this library to complete for uapaot.

**Comment by safern** [comment]
Let me try it. I don't have the repo built for uapaot though so it will take a few minutes. Will let you know

**Comment by safern** [comment]
I was able to run them and this still repro for me locally. If I re-enable the test I get:
```
  Discovering: System.Linq.Expressions.Tests
  Discovered:  System.Linq.Expressions.Tests
  Starting:    System.Linq.Expressions.Tests
  The system cannot find the file specified.
  Finished running tests.  End time=22:41:36.10, Exit code = 1
D:\repos\corefxCopy\corefx\Tools\tests.targets(346,5): warning MSB3073: The command "D:\repos\corefxCopy\corefx\bin/Win
dows_NT.AnyCPU.Debug/System.Linq.Expressions.Tests/uapaot//RunTests.cmd D:\repos\corefxCopy\corefx\bin/testhost/uapaot-
Windows_NT-Debug-x64/" exited with code 1. [D:\repos\corefxCopy\corefx\src\System.Linq.Expressions\tests\System.Linq.Ex
pressions.Tests.csproj]
D:\repos\corefxCopy\corefx\Tools\tests.targets(354,5): error : One or more tests failed while running tests from 'Syste
m.Linq.Expressions.Tests' please check D:\repos\corefxCopy\corefx\bin/Windows_NT.AnyCPU.Debug/System.Linq.Expressions.T
ests/uapaot/testResults.xml for details! [D:\repos\corefxCopy\corefx\src\System.Linq.Expressions\tests\System.Linq.Expr
essions.Tests.csproj]
```

**Comment by VSadov** [comment]
@danmosemsft - since this is causing FailFast, would it be an indication that it is specific to AOT/runtime?

**Comment by danmosemsft** [comment]
Can be. Note that debug.fail also causes fail fast now.

**Comment by safern** [comment]
I will try to attach locally and see if it is AOT/runtime. Might be related to: https://github.com/dotnet/corefx/issues/21804

**Comment by safern** [comment]
I see:

```
Unhandled exception at 0x00007FFEE7C5F0B9 (mrt100_app.dll) in xunit.console.netcore.exe: 0xC0000602:  A fail fast exception occurred. Exception handlers will not be invoked and the process will be terminated immediately.
```

in: https://github.com/dotnet/corefx/blob/master/src/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/LightLambda.cs#L431-L453

**Comment by VSadov** [comment]
So, is it the same as #21804 ? Should it be just made a duplicate?

The code in https://github.com/dotnet/corefx/blob/master/src/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/LightLambda.cs#L431-L453

is a very trivial kind of code. I doubt very much it is anything that needs be done on the side of Linq.Expressions

**Comment by safern** [comment]
This is the same as #21804 which was already fixed we don't see this failing anymore and the tests are running on ret mode. So closing this one.
