### ISSUE TITLE
Question: Visual Studio Designer Integration for .Net Core/.Net Standard 2.0

### ISSUE THREAD

**Issue by JinShil** [dotnet/corefx#19139]
.Net Standard 2.0 and .Net Core 2.0 have included APIs in `System.ComponentModel` for building and extending the Visual Studio designer (e.g `Component` class, `DesignerAttribute`, `TypeConverter`, etc..) 

However, if one tries to use these classes in the current release of Visual Studio 2017 to create designers for their classes, Visual Studio displays errors in the designer like

```c#
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Text;

namespace CoreDesignerTest
{
    public class Class1 : Component
    {
    }
}
```

In Visual Studio, right-click on the "Class1.cs" node and choose "View Designer".

> Could not load file or assembly 'System.ComponentModel.Primitives, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. 

With some hacking in my .config files, I can resolve the above error, but eventually Visual Studio fails to load the .Net Core assemblies with an "Invalid Format" error.

I'm assuming this is due to the fact that Visual Studio, being a .Net Framework-based application, is trying to load a .Net Core assembly into a .Net Framework application, and therefore failing.

My question is, with the coming release of .Net Core 2.0 and .Net Standard 2.0, will there also be an accompanying Visual Studio update that will provide the ability to create designers for .Net Core 2.0 and .Net Standard 2.0 classes?

**Comment by karelz** [comment]
In VS changes are needed (which is IMO likely), there will be accompanying VS update.

I wonder if this is more related to Desktop magic retargeting pack (or whatever we call it) -- @weshaggard @ericstj?

**Comment by danmosemsft** [comment]
@davkean

**Comment by weshaggard** [comment]
Eventually we will likely have VS designer support for .NET Core components but I don't expect that to come online in the next VS update. Most of the Component design is around WinForms and WPF support which is not a target for .NET Core (at least not at this time). 

The errors you are seeing are related to the fact that the inbox .NET Framework doesn't know about most of these .NET Core assembly identities so you assumption of the mixing between .NET Framework and .NET Core is the reason this scenario is broken.

**Comment by karelz** [comment]
Seems to be answered by @weshaggard, closing. Please let us know if you need more info (we can reopen again), thanks!

**Comment by davkean** [comment]
This issue was moved to dotnet/project-system#2100

**Comment by davkean** [comment]
Let's capture this bug, though. I've moved it over to project-system for the moment.
