### ISSUE TITLE
OSX build issue with low ulimit

### ISSUE THREAD

**Issue by jmezach** [dotnet/corefx#19152]
Today me and @ptoonen ran into an issue when doing a full build of the corefx repo on OSX. Compiling some assemblies failed with a Too Many Open files error. This is caused by a low ulimit (see ulimit -a, which showed 256 for open files on my machine (OSX Sierra 10.12.4)).

The init-tools.sh script already tries to change the ulimit by issuing ulimit -n 2048. It seemed that this can only be done when root, although I just tried it again and now it seems to work.

I ended up raising the limit system wide (as described [here](https://unix.stackexchange.com/questions/108174/how-to-persist-ulimit-settings-in-osx-mavericks)). After rebooting this fixed the issue.

After discussing this with @karelz we decided that it might be useful to raise an issue for this.

**Comment by karelz** [comment]
@mellinoe @weshaggard can (at minimum) detect the situation in our scripts and warn users?
It will make our first-time contributors life easier. (e.g. for the Netherlands hackaton which is in progress now).

Thanks!

**Comment by ptoonen** [comment]
Strange part is that root privileges should not be necessary and init-tools.sh performs the correct issues :-/ It appears as though something is resetting the limit in between.

**Comment by karelz** [comment]
Is it something you guys could help us track down - maybe even suggest a PR for the scripts?

**Comment by ptoonen** [comment]
Already looked into it (on the side), but mainly working on a different PR at the moment :) Will take another look once that's done.

**Comment by karelz** [comment]
Great, thanks! Appreciate your help here -- especially in things which will make it better for the next contributor.

**Comment by danmosemsft** [comment]
Ideally we would do this for tests also -- caused https://github.com/dotnet/corefx/issues/18463

**Comment by ptoonen** [comment]
I'll take a look at this tomorrow. My main dev machine is a mac.

**Comment by weshaggard** [comment]
@ptoonen is this something you are interested in submitting a fix for?

**Comment by ptoonen** [comment]
@weshaggard yes, though it's in intermittent WIP at the moment ;-)

**Comment by wtgodbe** [comment]
Closing as dead/resolved, please re-open if that isn't the case
