### ISSUE TITLE
WaitHandleWaitAll fails on desktop

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#19156]
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170429.02/workItem/System.Threading.Tests/analysis/xunit/System.Threading.Tests.ManualResetEventTests~2FWaitHandleWaitAll
```
Windows.10.Amd64-x64-Release
Unhandled Exception of Type System.NotSupportedException
Message :
System.NotSupportedException : WaitAll for multiple handles on a STA thread is not supported.
Stack Trace :
   at System.Threading.WaitHandle.WaitMultiple(WaitHandle[] waitHandles, Int32 millisecondsTimeout, Boolean exitContext, Boolean WaitAll)
   at System.Threading.WaitHandle.WaitAll(WaitHandle[] waitHandles, Int32 millisecondsTimeout, Boolean exitContext)
   at System.Threading.Tests.ManualResetEventTests.WaitHandleWaitAll() in E:\A\_work\313\s\corefx\src\System.Threading\tests\ManualResetEventTests.cs:line 55
```

Needs this adding
`[SkipOnTargetFramework(TargetFrameworkMonikers.NetFramework, "Full framework throws NotSupportedException  because test runs on STA and Core run on MTA")]`

**Comment by danmosemsft** [comment]
@Jiayili1 can you tell me why we didn't already have an issue for this (at least I couldn't find one). Are there any other desktop failures missing isuses?

@safern

**Comment by danmosemsft** [comment]
@Jiayili1 please disable the test with the attribute above and put up a PR

**Comment by danmosemsft** [comment]
@Jiayili1 never mind, Stephen's fixing it.

**Comment by Jiayili1** [comment]
@danmosemsft I'm sorry that I missed this message since we are oof on holiday for international labor day. And this test failed since 20170428.02, and last week we looked into 20170428.01, this test does't fail on 20170428.01.

**Comment by danmosemsft** [comment]
No problem, thanks!
