### ISSUE TITLE
Reflection.EmitWriteLine fails on Linux

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#1915]
```
System.Reflection.Emit.ILGeneration.Tests.ILGeneratorEmitWriteLine.PosTest1 [FAIL]
17:59:28       System.ArgumentNullException : Value cannot be null.
17:59:28       Parameter name: meth
17:59:28       Stack Trace:
17:59:28             at System.Reflection.Emit.ILGenerator.Emit(OpCode opcode, MethodInfo meth)
17:59:28             at System.Reflection.Emit.ILGenerator.EmitWriteLine(FieldInfo fld)
17:59:28             at System.Reflection.Emit.ILGeneration.Tests.ILGeneratorEmitWriteLine.PosTest1()
17:59:28 Finished:    System.Reflection.Emit.ILGeneration.Tests
```

Quoting @stephentoub 

> The EmitWriteLine method in mscorlib is using reflection to access Console.Out in mscorlib (https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Reflection/Emit/ILGenerator.cs#L1233), but Console.Out is getting removed by the BCL rewriter, so the MethodInfo is null, causing the ArgumentNullException. But even if it wasn't getting removed, this is not the right Console implementation for code to be targeting: the Console in System.Console.dll is the one that's cross-platform. @jkotas, FYI. (I wonder if the right solution is just to remove these EmitWriteLine methods from the contract and not expose them.)

**Comment by stephentoub** [comment]
Seems like there are a few potential options here:

1. Remove EmitWriteLine from the contract.
2. Change EmitWriteLine's implementation in mscorlib to use reflection to find and use System.Console from System.Console.dll.
3. Implement Console on Unix in mscorlib

and maybe something else I've not thought of.  (2) doesn't seem very robust, and (3) seems like complete overkill for what this is, especially as we try to pair down mscorlib.  (1) to me is the most palatable, as these seems like a helper that anyone could write on their own on top of the rest of the contract... but I don't know whether this is feasible at this point in time.

@weshaggard, thoughts?

**Comment by jkotas** [comment]
If (1) is not feasible, a feasible variant may be to throw NotSupportedException from EmitWriteLine on CoreCLR.

**Comment by weshaggard** [comment]
(1) seems like it would be the best approach, we haven't officially shipped the Ref.Emit contract for any platform yet so we can possibly remove it still. @nguerrera what do you think about removing this?

If we cannot remove it then throwing PlatformNotSupportedException would be likely our best option for this case.

**Comment by nguerrera** [comment]
(1) is still feasible and seems like the sensible option at this stage. I will take care of that. @Priya91, can you remove the tests that use it in the meantime.

**Comment by Priya91** [comment]
@nguerrera: Yes, i've skipped those tests for Unix platforms with ActiveIssue linking to this issue number. Once the issue is fixed, we can replace the ActiveIssue attribute with PlatformSpecific to run only on Windows.

**Comment by nguerrera** [comment]
I take back what I said about (1)  being feasible. The contract in question (System.Reflection.Emit.ILGeneration not System.Reflection.Emit) has in fact already shipped:

"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.5\Profile\Profile49\System.Reflection.Emit.ILGeneration.dll"

EmitWriteLine can already be called in Windows Phone Siliverlight 8 and PLIBs targeting WP8+desktop

**Comment by nguerrera** [comment]
We could mark the method as Obsolete and throw PlatformNotSupported, but make note that the change requires some care not to regress Windows Phone. I am actually now debating whether (2) would really be so bad...

**Comment by jkotas** [comment]
You have the same problem for (2) - the change needs to be done under a quirk for both.

**Comment by nguerrera** [comment]
Yes. Separately, though, I still wonder if we should break an API that's (1) handy/attractive enough and (2) stuck in the contract when we can in fact support it.

**Comment by stephentoub** [comment]
So here's what a fix that combines 2 and 4 (PlatformNotSupportedException) could look like:
https://github.com/stephentoub/coreclr/commit/e2d83f219023c85915c742125817cbbfb23d7046

If we like this, I can submit this as a PR to fix it.

If we don't, then the remaining option would seem to be removing from this everything but the throwing of PlatformNotSupportedException, either just on Unix or more generally.
