### ISSUE TITLE
How can I use binary serialization with CookieContainer

### ISSUE THREAD

**Issue by midnightstarr** [dotnet/corefx#19167]
I need to serialize CookieContainer to the binary file. I was looking for BinaryFormatter but couldn't find it. I use the newest version of .NET Core. I tried serializing it with protobuf-net and msgpack but it didn't work. Any solution for this? I saw the support for binary serialization was added in 2.0 but I need to use some alternative solution now in 1.1.

**Comment by davidsh** [comment]
In general .NET Core 1.x does not support binary serialization.  This is only supported in .NET Core 2.0.

You can always implement something custom via XML/Json, etc. but that requires you to hand serialize the objects using only the public API surfaces (properties, etc.).

**Comment by davidsh** [comment]
cc: @karelz @danmosemsft

**Comment by danmosemsft** [comment]
Although we have binary serialization in 2.0, we are planning to scale it back before we ship to just primitive and collection types (https://github.com/dotnet/corefx/issues/19119). For higher types like this we recommend using a different serializer.

**Comment by midnightstarr** [comment]
CookieContainer exposes too little to serialize it all and without using reflection and accessing _domainTable it's not possible to get all the cookies without specifying the Uri.

**Comment by davidsh** [comment]
@midnightstarr  I appreciate your frustration and agree that the cookie* classes don't have a lot of public API surface to approximate a serialization solution.

Unfortunately, for .NET Core 1.x, there is no good solution other than reflection.  I believe that .NET Core 2.0 will provide better serialization support.

**Comment by ViktorHofer** [comment]
With 2.0 we are adding serialization support for CookieContainer!

**Comment by davidsh** [comment]
>With 2.0 we are adding serialization support for CookieContainer!

Are we sure?  Based on this https://github.com/dotnet/corefx/pull/19742, I'm not so sure.

**Comment by ViktorHofer** [comment]
I'm sure :) I did it myself ;)

**Comment by danmosemsft** [comment]
This should be hte correct list of the types we preserved [Serializable] on: https://gist.github.com/morganbr/2a9901b12f1d342285694e69983a12d0 (minus Lazy)

**Comment by davidsh** [comment]
>I'm sure :) I did it myself ;)

@ViktorHofer Thanks!
