### ISSUE TITLE
UnderlyingSystemType replacement in .NET Standard1.4

### ISSUE THREAD

**Issue by rnagpal** [dotnet/corefx#19180]
I've some NETFX code that I'm trying to compile for .NET Standard 1.4 and one of the issues I'm facing is how to replace UnderlyingSystemType property on the Type object.

I see that this has been exposed from TypeInfo class for .NET Standard 1.5 and 1.6 but I'm looking for an equivalent in .NET Standard 1.4

Any suggestions?

**Comment by karelz** [comment]
What do you use it for? What is your scenario?

**Comment by AtsushiKan** [comment]
Closing due to lack of response.
