### ISSUE TITLE
Profile captured by PerfRunner is missing events needed by PerfView

### ISSUE THREAD

**Issue by mconnew** [dotnet/corefx#19191]
I am running performance tests using the following command:
```cmd
msbuild /t:BuildAndTest /p:Performance=true /p:ConfigurationGroup=Release /p:TargetOS=Windows_NT
```
When opening the .etl file in PerfView, most stack frames show the module as ManagedModule. For example:
```
ManagedModule!System.Xml.XmlTextWriter.InternalWriteEndElement(bool)
```
When running the test using PerfView to capture the profile, all the module names are correct.

**Comment by karelz** [comment]
@DrewScoggins can you please help?
@mconnew is it blocking you? Or were you able to work around it?

**Comment by mconnew** [comment]
@karelz, I can work around it. I do one run using the method listed above, grab the executing command line from the log and then have perfview run the exact same thing adding `*Microsoft-Xunit-Benchmark` as an additional provider to get the test start and stop events . Interestingly perfview also creates a significantly smaller .etl file. When loading the PerfRunner generated profile in perfview, I often get an error saying there's too many events and it's truncating the profile. PerfRunner will generate a 4.5GB etl file when PerfView generates a ~700MB etl file for the same run. It would be nice to move some of the events as optional via a /p:XXXX=true switch to msbuild. Even if they are on by default, reducing the set of events would be really helpful.

**Comment by karelz** [comment]
Sounds like Future milestone then ... @DrewScoggins @mellinoe is that ok?

**Comment by mellinoe** [comment]
Sounds fine to me.

**Comment by DrewScoggins** [comment]
Yeah, seems good.

**Comment by wtgodbe** [comment]
Seems we haven't had any traction on this for 1+ year, closing as dead. @DrewScoggins @mconnew please re-open if it's still something we should act on
