### ISSUE TITLE
CryptoStream - crash when bytesToDeliver=amountRead

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#19194]
Created based on Connect feedback: http://connect.microsoft.com/VisualStudio/feedback/details/2604876/bug-in-system-security-cryptography-cryptostream (internal bug [213692](https://devdiv.visualstudio.com/DevDiv/_workitems?id=213692&_a=edit))

**Description:** A case is not handled in the `Read` method where `bytesToDeliver` equals `amountRead` exactly - the `ProcessFinalBlock` label is never invoked and `_finalBlockTransformed` is not set to true. This means that a read operation that falls into this case will call `FlushFinalBlock` on `Dispose` - which throws an exception in the proprietary stream I'm using for reading. A `Flush` is never expected on stream used for reading only. The last thing that needs to be checked in the `if (bytesToDeliver >= numOutputBytes)` block is whether `bytesToDeliver` has gone to zero, in which case we should go to the `ProcessFinalBlock` label code. I've attached a solution to reproduce and included a copy of `CryptoStream` that with a one line fix.

**Repro Steps:** Basically, attempt to read (decrypt) a stream that falls into the "slow" label and into the `if (bytesToDeliver >= numOutputBytes)` block with `bytesToDeliver == numOutputBytes`.

Impact: For me, I get intermittent crashes when I read a stream of a particular length that just happens to fall into this case - `Flush` is called on a stream that accepts no write operations.

**Comment by karelz** [comment]
Suggested fix from the report: https://github.com/dotnet/corefx/blob/e9ecf74d845476540f40fa8fdc62c53ebf048519/src/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/CryptoStream.cs#L357-L362

```c#
                if (bytesToDeliver >= numOutputBytes)
                {
                    Buffer.InternalBlockCopy(_OutputBuffer, 0, buffer, currentOutputIndex, numOutputBytes);
                    currentOutputIndex += numOutputBytes;
                    bytesToDeliver -= numOutputBytes;
                    
                    // FIX: - DON'T FLUSH ON DISPOSE IF READING
                    if (bytesToDeliver == 0) goto ProcessFinalBlock;
                }
```

**Comment by karelz** [comment]
Repro from the bug report:

```c#
// File: Program.cs
using System;
using System.IO;
using System.IO.Compression;
using System.Security.Cryptography;
using System.Text;

namespace ConsoleApplication1
{
    internal class Program
    {
        private static void Main()
        {
            Console.WriteLine("Decrypting with fixed CryptStream (FixedCryptoStream.cs - line 246) ...");
            var length1 = DecryptWithFixedCryptoStream(new ReadonlyStream(File.OpenRead("Test.txt"))).Length;
            Console.WriteLine($"Decrypted - {length1} bytes");
            Console.WriteLine();
            Console.WriteLine();

            Console.WriteLine("Decrypting...");
            var length2 = DecryptWithBrokenCryptoStream(new ReadonlyStream(File.OpenRead("Test.txt"))).Length;
            Console.WriteLine($"Decrypted - {length2} bytes");
            Console.ReadLine();
        }

        private static SymmetricAlgorithm CreateAlgorithm()
        {
            using (var key = new Rfc2898DeriveBytes("4ZpHznL4ELiAiZEXpAloFPA7sO4NqVLLd8qavZ8D", Encoding.UTF8.GetBytes("vxZIH70vLr9i8pymHC0U")))
            {
                var algorithm = new RijndaelManaged { Mode = CipherMode.CBC };
                algorithm.Key = key.GetBytes(algorithm.KeySize / 8);
                algorithm.IV = key.GetBytes(algorithm.BlockSize / 8);
                return algorithm;
            }
        }

        public static byte[] DecryptWithBrokenCryptoStream(Stream stream)
        {
            if (null == stream)
                throw new ArgumentNullException(nameof(stream));

            using (var algorithm = CreateAlgorithm())
            using (var crypto = new CryptoStream(stream, algorithm.CreateDecryptor(), CryptoStreamMode.Read))
            using (var compression = new GZipStream(crypto, CompressionMode.Decompress))
            using (var memory = new MemoryStream())
            {
                var buffer = new byte[16 * 1024];

                int read;
                while ((read = compression.Read(buffer, 0, buffer.Length)) > 0)
                    memory.Write(buffer, 0, read);

                return memory.ToArray();
            }
        }

        public static byte[] DecryptWithFixedCryptoStream(Stream stream)
        {
            if (null == stream)
                throw new ArgumentNullException(nameof(stream));

            using (var algorithm = CreateAlgorithm())
            using (var crypto = new FixedCryptoStream(stream, algorithm.CreateDecryptor(), CryptoStreamMode.Read))
            using (var compression = new GZipStream(crypto, CompressionMode.Decompress))
            using (var memory = new MemoryStream())
            {
                var buffer = new byte[16 * 1024];

                int read;
                while ((read = compression.Read(buffer, 0, buffer.Length)) > 0)
                    memory.Write(buffer, 0, read);

                return memory.ToArray();
            }
        }
    }
}
```

```c#
// ReadOnlyStream.cs
using System;
using System.IO;

namespace ConsoleApplication1
{
    class ReadonlyStream : Stream
    {
        private readonly Stream _stream;

        public ReadonlyStream(Stream stream)
        {
            if (null == stream)
                throw new ArgumentNullException(nameof(stream));
            _stream = stream;
        }

        public override bool CanRead => _stream.CanRead;
        public override bool CanSeek => _stream.CanSeek;
        public override bool CanWrite => false;
        public override long Length => _stream.Length;

        public override long Position
        {
            get { return _stream.Position; }
            set { _stream.Position = value; }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _stream.Dispose();
        }

        public override void Flush()
        {
            throw new NotImplementedException("Flush should not occur - we're reading only");
        }

        public override int Read(byte[] buffer, int offset, int count)
        {
            return _stream.Read(buffer, offset, count);
        }

        public override long Seek(long offset, SeekOrigin origin)
        {
            return _stream.Seek(offset, origin);
        }

        public override void SetLength(long value)
        {
            throw new NotImplementedException();
        }

        public override void Write(byte[] buffer, int offset, int count)
        {
            throw new NotImplementedException();
        }
    }
}
```

**Comment by karelz** [comment]
Next steps:
1. Turn the repro above into a test case, validate it is still a problem.
2. Make the fix.

Should be fairly straightforward ...

**Comment by pjanotti** [comment]
hi @karelz - I can take this one. I'm not a contributor yet.

**Comment by karelz** [comment]
Invitation sent. Ping me when you accept, so I can assign it to you.
Let us know if you hit any roadblocks.

**Comment by karelz** [comment]
Also, welcome onboard!
And check out our (under construction) docs for new contributors: https://github.com/dotnet/corefx/wiki/New-contributor-Docs
If you have questions, ask. If you have tips & tricks, feel free to edit the wiki (it is opened for edits to anyone, without PR system).

**Comment by pjanotti** [comment]
I just accepted the invitation. I will start with the doc.

**Comment by pjanotti** [comment]
Building and running tests from VS 2017 command prompt ok. However from VS 2017 I am getting:

Could not load file or assembly 'System.IO.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

but this is not a blocker I can make progress with the command-line tools.

**Comment by karelz** [comment]
@mellinoe @weshaggard is that expected?

**Comment by pjanotti** [comment]
@karelz I built a simplified test that hit the issue but the proposed fix broke other tests. Tomorrow I will give another go at it (now I really want to debug it from VS...)

**Comment by karelz** [comment]
It's quite possible that the proposed fix was wrong, or that it is more involved - I didn't verify that.
@ianhays should be able to help if you can't figure it out - ping him if/when that's the case (he can get help from other experts if necessary).

**Comment by tah9m9** [comment]
I made the original bug report with the repro project and proposed solution. So I'll be interested in how it is resolved.

**Comment by pjanotti** [comment]
I am thinking that it is actually wrong for a Stream derived class to throw if Flush is called, even if it doesn’t support writing. Some points to corroborate that:

* [Here](https://msdn.microsoft.com/en-us/library/system.io.stream.canwrite(v=vs.110).aspx) it mentions the methods that throw NotImplementedException if a Stream derived type does not support writing, but, Flush is not listed there.
* [FileStream](https://msdn.microsoft.com/en-us/library/2bw4h516(v=vs.110).aspx) gives an example of usage of Flush when reading, using that as basis I can see some behavior in a derived type of Stream that supports only reading and can use Flush to reset some internal state.

With this in mind I think that we should not change CryptoStream.

@tah9m9 let's here from the experts to decide what to do here, but, perhaps you need to wrap the proprietary stream with a type that just ignores Flush and forward the other methods (I'm guessing that you already did that...)

@ianhays and @karelz let me know if you disagree if the rational above. If you disagree I'll take a closer look to fully understand the implications of such "fix".

**Comment by tah9m9** [comment]
I'll can go along with that. Although, my gut tells me that logically Flush is strictly a function of writable streams and Write operations. That it would be called during a Read operation is silly at best and unpredictable at worst. My theory is that the docs simply omitted the Flush operation by some kind of mistake and both should be corrected for consistency in the logical interpretation of how streams behave.

**Comment by karelz** [comment]
@ianhays can you please comment? The arguments above sound reasonable, but I don't have enough first-hand experience with Streams/CryptoStream to assess the fully ...

**Comment by karelz** [comment]
@tah9m9 is it ok if I close the Connect bug? I think the discussion & resolution here is easier to track ... (the end result of when/where/how it will be addressed is the same in both places)

**Comment by tah9m9** [comment]
@karelz It doesn't look like I can change the status or do anything to close that Connect issue.

**Comment by karelz** [comment]
You can't, but I can ;-) ... I'll take you comment as 'go ahead' signal ...

**Comment by tah9m9** [comment]
For the discussion.. I can understand if Flush were to be called consistently in the process of every Read (or at least full read) on CryptoStream, but it is only called in this one case where the only variable is stream length.

**Comment by weshaggard** [comment]
>Could not load file or assembly 'System.IO.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

I think you were hitting https://github.com/dotnet/buildtools/pull/1468 which we just fixed yesterday in our tools repo and should get integrated into our toolset in a few days.

**Comment by pjanotti** [comment]
Thanks @weshaggard

**Comment by pjanotti** [comment]
@weshaggard fyi I was able to run the tests from VS 2015 update 3

**Comment by ianhays** [comment]
>I am thinking that it is actually wrong for a Stream derived class to throw if Flush is called, even if it doesn’t support writing. Some points to corroborate that:

We also allow flushing [in DeflateStream regardless of `CanWrite`](https://github.com/dotnet/corefx/blob/master/src/System.IO.Compression/src/System/IO/Compression/DeflateZLib/DeflateStream.cs#L167), so there's another example.

**Comment by tah9m9** [comment]
Interesting... I guess that settles it. We'll keep our wrapper in place.

**Comment by pjanotti** [comment]
Ok, so let's close this issue. @karelz do I need to do something in this regard?

**Comment by karelz** [comment]
Closing per comments above, thanks everyone for help!

BTW: Do we need any documentation changes?

**Comment by pjanotti** [comment]
I think the docs for CanWrite and Flush should explicit state that implementation of Flush should not throw NotImplementedException for read only streams. Although it "feels" right to do so can hit cases like this one.

**Comment by karelz** [comment]
I assume on `CryptoStream` - @ianhays @bartonjs does it seem like reasonable request?
Should we reopen this one or file a new one?

**Comment by pjanotti** [comment]
@karelz I think that it should be general for any stream: the reason being that there may be already some streams out there that leverage Flush being called even if they are read-only. So we want to avoid people creating more read-only streams that throw NotImplementedException on Flush. I had submitted such request via the feedback to msdn docs but I don't know about the traction there. Changing at docs.microsoft.com perhaps is the new path...

**Comment by karelz** [comment]
@pjanotti can you please file it as new issue on CoreFX? I want area owners (@ianhays @JeremyKuhne) first to approve it, then we can move it to docs repo. Thanks!
