### ISSUE TITLE
Make XElement serializable in netstandard

### ISSUE THREAD

**Issue by huanwu** [dotnet/corefx#19204]
The default XElement constroctor is public in corefx, but not in dotnet standard. This breaks our serialization generator for XElement type. The code will be generated based on the corefx and use the default constructor when create a new XElement instance. But it cannot compile in dotnet standard since the default public constructor doesn't exist. Need make them be consistent to unblock our scenario. Either make XElement default contructor be internal like in desktop version. Or add it in the dotnet standard.

#16701

**Comment by karelz** [comment]
@huanwu @shmao should it got into 2.0?

**Comment by huanwu** [comment]
@karelz yes, it is 2.0

**Comment by karelz** [comment]
Can you please also add issue type label? See [triage rules](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified) for details.

**Comment by danmosemsft** [comment]
@weshaggard

**Comment by krwq** [comment]
Previously we have have marked XElement constructor internal in the contract so that serialization worked fine - would that be sufficient?

**Comment by weshaggard** [comment]
We cannot make the constructor public in .NET Standard 2.0. We should make it internal in Core. https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml.Linq/src/System/Xml/Linq/XElement.cs#L132.

**Comment by krwq** [comment]
@huanwu - I don't see why internal wouldn't work - is it uapaot problem? Should you update rd.xml?

**Comment by huanwu** [comment]
@krwq  This impact our serialization code generator scenario. The code was generated based on corefx,. Since the default constructor for XElement is public, (https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml.Linq/src/System/Xml/Linq/XElement.cs#L132)
the generated code is like
o.@MyElement = (global::System.Xml.Linq.XElement)ReadSerializable(( System.Xml.Serialization.IXmlSerializable)**new global::System.Xml.Linq.XElement());**

However the generated code cannot compile since the default constructor is not public in dotnet standard.

**Comment by krwq** [comment]
@huanwu would changing it to internal fix the issue and cause proper code to get generated?

**Comment by huanwu** [comment]
@krwq yes, it will solve our problem if you change it to internal.
