### ISSUE TITLE
UWP tests producing no result - crash in xunit?

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#19211]
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20170501.02 
 
shows Xunit Counts
Pass: 0
Fail: 0
Skip: 0 
 
execution produced no test result xml
2017-05-01 13:31:34,950: INFO: proc(54): run_and_log_output: Output: FAILED 0x8027025B (The app didn't start.

00 0000005c`adb9e830 00007ffd`6c404f55 KERNELBASE!RaiseException(unsigned long dwExceptionCode = <Value unavailable error>, unsigned long dwExceptionFlags = <Value unavailable error>, unsigned long nNumberOfArguments = <Value unavailable error>, unsigned int64 * lpArguments = <Value unavailable error>)+0x68 [d:\rs1\minkernel\kernelbase\xcpt.c @ 904] 
01 0000005c`adb9e910 00007ffd`6c4b0750 CoreCLR!GetCLRRuntimeHost+0x3cd65
02 0000005c`adb9ea30 00007ffd`6c03e011 CoreCLR!GetCLRRuntimeHost+0xe8560
03 0000005c`adb9ebe0 00007ffd`6c6ecff3 System_Private_CoreLib!System.AppDomain.Setup(<HRESULT 0x80004001>)+0x494ce1
04 0000005c`adb9eca0 00007ffd`6c448130 CoreCLR!GetCLRRuntimeHost+0x324e03
05 0000005c`adb9ece0 00007ffd`6c428b86 CoreCLR!GetCLRRuntimeHost+0x7ff40
06 0000005c`adb9ee10 00007ffd`6c3c7731 CoreCLR!GetCLRRuntimeHost+0x60996
07 0000005c`adb9f070 00007ffd`6c3c804b CoreCLR!coreclr_execute_assembly+0x14711
08 0000005c`adb9f540 00007ffd`b96219ec CoreCLR!coreclr_execute_assembly+0x1502b
09 0000005c`adb9f5a0 00007ffd`b9621ad6 UWPHOST!UWPHost::LoadAndStartCoreCLRRuntime(void)+0x2f8 [f:\dd\ndp\clr\src\coreclr\uwp\host\uwphost.cpp @ 167]  
 
Appears to be an ArgumentNullException inside System.Private.CoreLib.dll 

@MattGal has a dumpfile
@alexperovich ?

**Comment by danmosemsft** [comment]
Oh, I just noticed this is CoreCLR tests.

**Comment by MattGal** [comment]
See me for dump / repro info.  I noted this appears for the first time in build 20170428.02 

That means the change most likely occurred between commits 35903a1cab676d100b5b90754e5313f43b30170d and ea78c27d8d5f75825f9b596df4e95199d38a55e1.

**Comment by danmosemsft** [comment]
Realistically, nobody is going to look at this now.

cc @MattGal @alexperovich

**Comment by MattGal** [comment]
Also I think we fixed a lot of this since May by changing the launcher & runner, the pass rate has gone way up for this scenario since 5/1
