### ISSUE TITLE
Proposal for adding System.Runtime.CompilerServices.IsRefLikeAttribute

### ISSUE THREAD

**Issue by VSadov** [dotnet/corefx#19212]
# Rationale and Usage

For upcoming C# features captured in [Safe Spans proposal here](https://github.com/VSadov/csharplang/blob/3ab16a77b9fefe3805fa81044ba72d6c254e00f9/proposals/span-safety.md), the C# compiler needs a way to annotate structs in metadata as ref-like. The proposal is to add a new attribute to `System.Runtime.CompilerServices` namespace similar to`IsReadOnly`, named `IsRefLike`.

The purpose of the attribute is to request that all the requirements of ref-like structs be applied to the type by the compiler.  
Such struct will be allowed to have instance fields that are ref-like types (and typically will have such fields).

# Proposed API

```csharp
// .NET Core:
//      System.Runtime (reference assembly)
//      System.Private.CoreLib (implementation)
// .NET Framework 4.7++
//      mscorlib
// .NET Standard 2.0++
//      netstandard

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Struct)]
    public sealed class IsByRefLikeAttribute: Attribute
    {
        public IsByRefLikeAttribute();
    }
}
```

To ensure that using this type is an error on old compilers and compilers not familiar with safety rules of ByRefLikeStructs compiler will also emit an `Obsolete` attribute with a predefined message that can be filtered out by compilers that do know how to operate with spans.

```csharp
[Obsolete("ByRefLike types are not supported in this version of your compiler.", true)]
```

So a typical ref like struct will look like the following in the source:

```csharp
ref struct TwoSpans<T>
{
	// can have ref-like instance fields
	public Span<T> first;
	public Span<T> second;
} 

// error: arrays of ref-like types are not allowed. 
TwoSpans<T>[] arr = null;
```

and like the following in metadata

```csharp
    [IsRefLike]
    [Obsolete("ByRefLike types are not supported in this version of your compiler.", true)]
    public struct TwoSpans<T>
    {
       . . . . 
    }
```

**Comment by VSadov** [comment]
CC: @dotnet/roslyn-compiler @terrajobst @karelz @weshaggard @marek-safar

**Comment by karelz** [comment]
@VSadov just double-checking: It is fine to do it post-2.0, right?

**Comment by VSadov** [comment]
@karelz - the shipping requirements are basically the same as for "IsReadOnly" - https://github.com/dotnet/corefx/issues/17741

The feature will work without attributes in the runtime, except in netmodules where it will result in an error since an attribute cannot be embedded in a module.

Also, as soon as any span-like type (including Span/ReadOnlySpan themselves) is declared in a particular `corlib`, compiler will force this attribute to exist in the assembly anyways, except it will not be public.

I think it should be included in 2.0 if possible.

**Comment by karelz** [comment]
@VSadov The `IsReadOnly` was already last-minute exception, but it was high value for Roslyn. I'm starting to be concerned how many such we have remaining. Can you please confirm this is the last one?
We really want to decrease the risk of making last minutes mistakes. Rushing APIs rarely pays off.

You will have to run it by .NET Core shiproom at this point (see my every-two-business-days emails) - heads up to @Petermarcu.

**Comment by terrajobst** [comment]
We'd prefer this name:

```C#
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Struct)]
    public sealed class IsByRefLikeAttribute: Attribute
    {
        public IsByRefLikeAttribute();
    }
}
```

With respect to downlevel poisining, you should use a message like this:

```C#
[Obsolete("ByRefLike types are not supported in this version of your compiler.", true)]
```

Otherwise looks good.

**Comment by jkotas** [comment]
Do we also need to enlighten the runtime to recognize and enforce this attribute as part of this?

**Comment by VSadov** [comment]
@terrajobst - should this become "api-approved" or we have some open issues?

**Comment by VSadov** [comment]
@jkotas - making runtime recognize this attribute seems like a separate item. 
It seems that can be done only after the attribute actually exists and added to the types.

I am wondering what runtime could do with the attribute? - like refuse to JIT code that places this on the heap?

**Comment by jkotas** [comment]
> making runtime recognize this attribute seems like a separate item.

It is separate work item, but it is part of the same feature. Have you thought through what kind of breaking potential is going to come from shipping the attribute in one release and the actual enforcement in later release?

> I am wondering what runtime could do with the attribute? - like refuse to JIT code that places this on the heap?

It will do what it does for the existing hardcoded set of byref-like types: https://github.com/dotnet/coreclr/search?utf8=%E2%9C%93&q=IsByRefLike&type=

**Comment by VSadov** [comment]
@jkotas - I was not sure that runtime wanted to invest into enforcing the span safety.

Most these case should be compile errors, so adding enforcement in the runtime should not be extremely breaking. 
It is however something that would be good to have from the beginning, if possible.

**Comment by jkotas** [comment]
> @jkotas - I was not sure that runtime wanted to invest into enforcing the span safety.

We have always had checks for the fixed set of byref-like types to prevent them from being allocated using reflection on GC heap, etc. So it is natural to extend this to kick in for the explicitly marked byref-like types as well.

**Comment by jkotas** [comment]
Exposed by #19322

**Comment by karelz** [comment]
The API is part of 2.0, fixing the milestone to 2.0.0. (@jkotas can you please double check?)

**Comment by jkotas** [comment]
Correct.
