### ISSUE TITLE
ResourceSet enumeration fails on uapaot

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#19210]
Attempt to shared ResourceSet implementation between CoreRT and CoreCLR reveled bugs in the CoreRT/ProjectN version: https://github.com/dotnet/corefx/pull/19196#issuecomment-298439628

**Comment by danmosemsft** [comment]
@joshfree should project N resourcemanager go to @morganbr ?

**Comment by tijoytom** [comment]
The orginal issue looks more or like this https://github.com/dotnet/corert/pull/3687
I don't have enough context here , @jkotas rolled back the changes in CoreCLR , but the ResourceSet in CoreRT is still using dictionary but  https://github.com/dotnet/corert/pull/3687 fix the issue in CoreRT/N. 
Is the right fix to port https://github.com/dotnet/corert/pull/3687 to CoreCLR ?

**Comment by jkotas** [comment]
The ultimate fix for this is to rollback the rollback above: move ResourceSet.cs to the CoreLib shared partition and make the sources identical between CoreCLR and CoreRT.

**Comment by jkotas** [comment]
This is tracked by https://github.com/dotnet/coreclr/issues/17901 now.
