### ISSUE TITLE
Using System.Runtime.dll with HelloWorld example

### ISSUE THREAD

**Issue by lleraromero** [dotnet/corefx#1922]
Hi,

I'm trying compile the HelloWorld example hosted in corefxlab, but instead of using the System.Runtime.dll which is downloaded with Nuget I'm using the one that is available in CoreFX. However, when compiling I get the following error:
error CS0518: Predefined type 'System.Object' is not defined or imported
I believe that the definition of System.Object is being forwarded to the mscorlib, but it doesn't seem to work. 
Any ideas? Am I doing something wrong?

Thanks.

**Comment by mellinoe** [comment]
> believe that the definition of System.Object is being forwarded to the mscorlib, but it doesn't seem to work

Yes, that is correct. You should compile against the "contract assembly", which we don't currently produce from this repository. However, the contract assemblies are included in the NuGet packages that that we ship, which everything in this repo builds against. Ideally we would have something in our documentation section about this, but I'm not sure this topic has been covered yet. We have some good internal docs that we should bring out that have quite a good explanation of the subject.
