### ISSUE TITLE
WinRT app can't create mutex with Global\ prefix

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/corefx#19227]
System.IO.IsolatedStorage may end up trying to create a mutex with name starting with Global\ prefix. Apps running in the WinRT context don't have access right to create global named mutex. So this will always fail.

**Comment by vitek-karas** [comment]
This causes the biggest bucket of failures in our app compatibility tests right now.
Internal TFS bug number 406673.

**Comment by karelz** [comment]
@vitek-karas did it work in UWP apps in earlier versions of .NET Native?
You suggest it is a regression ...

cc @danmosemsft

**Comment by vitek-karas** [comment]
Yes, this is a regression caused by the recent NS2.0 integration. It was sort of covered by another issue with Mutex (endless loop) which @AntonLapounov fixed recently.

It affects cca 25 apps in Top2000.

**Comment by JeremyKuhne** [comment]
We can probably just remove the logic to put it under a random subfolder for RT as we didn't do it before.

**Comment by joshfree** [comment]
@danmosemsft can you help prioritize this issue for this sprint?  It's the last big AppCompat blocker with NS2.0 UWP

**Comment by danmosemsft** [comment]
@JeremyKuhne assigning to you -- please prioritize appripriately given its causing noise in the app compat runs.

**Comment by JeremyKuhne** [comment]
Fixed with #19840
