### ISSUE TITLE
System.Globalization.Tests.GregorianCalendarGetWeekOfYears.GetWeekOfYear failed in CI

### ISSUE THREAD

**Issue by v-haren** [dotnet/corefx#19220]
failed test: System.Globalization.Tests.GregorianCalendarGetWeekOfYears.GetWeekOfYear
detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/opensuse42.1_debug/2246/testReport/System.Globalization.Tests/GregorianCalendarGetWeekOfYears/GetWeekOfYear/

MESSAGE:
~~~
System.ArgumentOutOfRangeException : Year, Month, and Day parameters describe an un-representable DateTime.
~~~
STACK TRACE:
~~~
at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day) 
at System.DateTime..ctor(Int32 year, Int32 month, Int32 day)
at System.Globalization.Tests.GregorianCalendarGetWeekOfYears.<GetWeekOfYear_TestData>d__6.MoveNext() 
at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
~~~

**Comment by danmosemsft** [comment]
@tarekgh

**Comment by tarekgh** [comment]
yes I am trying to look at this. This failure on OpenSUSE and I am not able to see the history of this test on that OS. so I wondering if we started to run such OS? or why this test started to fail.

**Comment by danmosemsft** [comment]
@tarekgh as far as I know we've been running against OpenSuSE 42.1 for a while. Helix just changed to 42.2 and it's apparently passing there. 42.1 is out of support so if it's a 42.1 issue only we don't care about it, and we should probably update netci.groovy to change to 42.2.

**Comment by tarekgh** [comment]
This is very interesting failure because it fails when create DateTime object. the values we use to construct the DateTime is generated randomly. I have reviewed the code we have which generate such values and I am not seeing any obvious case which can generate wrong values for years, months and days. the only explanation I can have is Random class somehow generate negative values. 

I am going to add some log messages in the test so we can catch exactly the failed cases with the wrong values.

**Comment by Clockwork-Muse** [comment]
@tarekgh - sure it can, [the last case doesn't match year with the month/day-of-month generated](https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Globalization.Calendars/tests/GregorianCalendar/GregorianCalendarGetWeekOfYear.cs#L48-L49):

```
int randomYear = RandomYear();
yield return new object[] { new DateTime(RandomYear(), randomMonth, RandomDay(randomYear, randomMonth)), RandomCalendarWeekRule(), RandomDayOfWeek() };
```

... I think it's likely intellisense is to blame for supplying the wrong thing.

**Comment by Clockwork-Muse** [comment]
Actually, I'm less sure that's the actual problem, but it's still a potential issue.

A bigger problem is that all the calls to the random data functions are running off of a static, shared instance of `Random`, which isn't threadsafe.  So we might be getting bizarre data too.

**Comment by hughbe** [comment]
```cs
yield return new object[] { new DateTime(RandomYear(), randomMonth, RandomDay(randomYear, randomMonth)), RandomCalendarWeekRule(), RandomDayOfWeek() };
```

The `day` field depends on `randomYear`. However, the year is `RandomYear()`. `RandomYear() != randomYear` most of the time. So I guess if `RandomYear()` is a leap year, `randomMonth == 2`, and `RandomDay(randomYear, randomMonth)` is greater than 29 or whatever, the test will fail.
