### ISSUE TITLE
Commented out code in WebClient for issue that is closed

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#19226]
Ouch. And for the others
https://github.com/dotnet/corefx/blob/ee6845afaa8c316469ef522ac0f4747e157747c0/src/System.Net.WebClient/src/System/Net/WebClient.cs#L231

I'm submitting a PR fixing this

**Comment by ViktorHofer** [comment]
@hughbe I already submitted a PR for that. It is pending.

**Comment by ViktorHofer** [comment]
https://github.com/dotnet/corefx/pull/19118

**Comment by ViktorHofer** [comment]
Ooh I see, that's not the same one...

**Comment by hughbe** [comment]
I'll let you get your PR merged in first

**Comment by stephentoub** [comment]
@danmosemsft, we should probably do a TODO search across the codebase.

**Comment by ViktorHofer** [comment]
@hughbe I just updated my PR with the 3 commented out sections as I saw they are referencing the same issue as my code. I hope that's okay for you.

@stephentoub @danmosemsft I will created a dedicated issue for the TODO crawling

**Comment by hughbe** [comment]
There are more than 3 commented out sections, 5 or 6 from memory. Maybe you miscounted? HttpResponseHeaders has a bunch of TODOs for Connection,Exception,Host, ContentLengthh. 

Can't fix now as Internet at home is too bad to restore packages. Feel free to push for your PR to be merged. I also dont have time at work to figure out how to test these fixes so I appreciate all the help you are providing.
Anectodatally, slow internet is basically why I've been focusing on stuff that I already have compiled, e.g HttpListener. It's a shame dotnet restore doesn't have timeouts greater than 60s!!

**Comment by hughbe** [comment]
@karelz it's possibly unlikely that this dotnet restore timeout limitation (I.e we can't customise the restore timeout) affects many people, but is it worth pushing this through the build tools or the CLI people? It's a bit of a pain having to bring my laptop to work to restore packages to build corefx as home internet is < 100kbs. It can restore packages but takes longer than 60s which is a fixed limit set by dotnet restore. It's a contributor pain, although a temporary one, that seems arbritary.

**Comment by ViktorHofer** [comment]
Yeah it could have been more, I shouldn't have used a precise number. I addressed all TODOs section in System.Net.WebClient and System.Net.Requests.

Ooh that's unfortunate to hear. It's a shame that dotnet restore needs Internet, we should fix that 😋
