### ISSUE TITLE
Desktop failure in System.Security.Cryptography.Rsa.Tests/ImportExport/UnusualExponentImportExport/

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#19238]
This issue is repro on desktop, detail: 
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/38/testReport/System.Security.Cryptography.Rsa.Tests/ImportExport/UnusualExponentImportExport_2/

```
MESSAGE:
System.Security.Cryptography.CryptographicException : The requested operation is not supported.\r\n
+++++++++++++++++++
STACK TRACE:
at System.Security.Cryptography.NCryptNative.ExportKey(SafeNCryptKeyHandle key, String format) at System.Security.Cryptography.CngKey.Export(CngKeyBlobFormat format) at System.Security.Cryptography.RSACng.ExportParameters(Boolean includePrivateParameters) at System.Security.Cryptography.Rsa.Tests.ImportExport.UnusualExponentImportExport() in D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\Security\Cryptography\AlgorithmImplementations\RSA\ImportExport.cs:line 117
```

**Comment by safern** [comment]
On Helix:

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170502.03/workItem/System.Security.Cryptography.Cng.Tests/analysis/xunit/System.Security.Cryptography.Rsa.Tests.ImportExport~2FUnusualExponentImportExport

**Comment by safern** [comment]
@bartonjs 4.6.2 fix?

**Comment by Jiayili1** [comment]
Failed tests:
ImportExport1032
UnusualExponentImportExport
ImportReset
LargeKeyImportExport
PaddedExport
MultiExport

**Comment by safern** [comment]
ImportExport1032 was fixed on: https://github.com/dotnet/corefx/pull/19240

Which was merged after the jenkins build finished, so it shouldn't fail on next builds.

**Comment by karelz** [comment]
@safern do you plan to tackle this one?

**Comment by safern** [comment]
If this is something that got fixed on 462 I can tackle it by adding conditional fact to helper property I added. cc: @bartonjs

**Comment by danmosemsft** [comment]
@bartonjs ?

**Comment by bartonjs** [comment]
Probably net462?

**Comment by danmosemsft** [comment]
@safern assigned to you..

**Comment by Jiayili1** [comment]
@safern this test failed with the same issue: **System.Security.Cryptography.Rsa.Tests.EncryptDecrypt.RsaDecryptAfterExport**
Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/48/testReport/System.Security.Cryptography.Rsa.Tests/EncryptDecrypt/RsaDecryptAfterExport/

**Comment by safern** [comment]
Yes it is already fixed on: https://github.com/dotnet/corefx/pull/19537
