### ISSUE TITLE
Lambda expressions using dynamic types are optimized away by ILC toolchain analyzer. 

### ISSUE THREAD

**Issue by tijoytom** [dotnet/corefx#19249]
Example 
   dynamic d = 3;
   Assert.Throws<DivideByZeroException>(() => d / 0);

This will throw NullReferenceException in ILC tool chain since anonymous method will be optimized    () => d/0  but changing dynamic to int will fix the issue 

 int  d = 3;
 Assert.Throws<DivideByZeroException>(() => d / 0);

**Comment by morganbr** [comment]
@tijoytom , what's null in this case?

**Comment by karelz** [comment]
@tijoytom can you please set area label for new issues in future? See [triage rules](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified) and [area list](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#areas)
Thanks!

**Comment by joshfree** [comment]
@tijoytom since this is an ILC issue can you close this and move it to TFS for the bug push?

**Comment by tijoytom** [comment]
Verify that VSO have an equivalent bug

**Comment by stephentoub** [comment]
We no longer run tests on a `uapaot` configuration.
