### ISSUE TITLE
Rename class file appears to not update proj file

### ISSUE THREAD

**Issue by vsccarl** [dotnet/corefx#19255]
In the latest d15rel build renaming a class file keeps the original file name and marks it as 'Not Found' in solution explorer.

Repros in all .NET Core project types.

![image](https://cloud.githubusercontent.com/assets/12900364/25643859/efe179f0-2f56-11e7-8442-e2eaa2ac6b4f.png)

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/project-system #2109](https://github.com/dotnet/project-system/issues/2109) via [**ZenHub**](https://www.zenhub.com/)
