### ISSUE TITLE
 Dumpling.sh: line 24: /proc/self/coredump_filter: No such file or directory

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#19259]
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release_prtest/2864/consoleFull#-13326339622d31e50d-1517-49fc-92b3-2ca637122019

```
17:22:02   ls: /cores: No such file or directory
17:22:02   Running tests... Start time: 17:22:02
17:22:02   Commands:
17:22:02   source Dumpling.sh
17:22:02   chmod +x /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/bin/testhost/netcoreapp-OSX-Release-x64//dotnet
17:22:02   /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/bin/testhost/netcoreapp-OSX-Release-x64//dotnet xunit.console.netcore.exe System.Net.WebClient.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonosxtests
17:22:02   CollectDumps 0 System.Net.WebClient.Tests
17:22:02   /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/bin/AnyOS.AnyCPU.Release/System.Net.WebClient.Tests/netstandard /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/src/System.Net.WebClient/tests
17:22:02   executing ulimit -c unlimited
17:22:02   Dumpling.sh: line 24: /proc/self/coredump_filter: No such file or directory
```

**Comment by danmosemsft** [comment]
Or perhaps this is just saying "there's not been any dumps"?

**Comment by mellinoe** [comment]
I'm not sure. This might just be a Linux-ism that is trying to run on OSX as well. @sepidehMS Do you remember what that line is supposed to do?

**Comment by sepidehMS** [comment]
Seems to me that this is a linux-specific command attempting to control which memory segments are written to the core dump file in the event that a core dump is performed for this process. Look at [this](https://github.com/dotnet/corert/blob/master/tests/coredump_handling.sh#L27).

**Comment by wtgodbe** [comment]
We're not using dumpling anymore with the new CI, closing. @safern please re-open if I'm mistaken about dumpling

**Comment by safern** [comment]
I think we do have the intention to keep running dumpling. We just disabled it because it was failing due to a python2 dependency: https://github.com/dotnet/corefx/commit/4a8a86e81a3227593d6166a2baa44f20063b61ac

@danmosemsft I think we still want to run dumpling and fix these set of issues?

**Comment by danmosemsft** [comment]
We do need a way to get dumps from tests that segfault or hang, whether it's dumpling based or something new. I think the next step is to do some all up thinking about the right way forward. I think it's OK to close issues about specific dumpling bugs and start fresh.
@ahsonkhan owns this scenario.

I added a note to https://github.com/dotnet/corefx/projects/12
