### ISSUE TITLE
Desktop: Tests under "System.Security.Cryptography.Xml.Tests.XmlDecryptionTransformTest" failed with "System.NullReferenceException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#19264]
Failed tests:
System.Security.Cryptography.Xml.Tests.XmlDecryptionTransformTest.LoadStreamInput_CorrectXml
System.Security.Cryptography.Xml.Tests.XmlDecryptionTransformTest.GetOutput_XmlWithEncryptedDataInRoot
System.Security.Cryptography.Xml.Tests.XmlDecryptionTransformTest.GetOutput_XmlWithEncryptedData
System.Security.Cryptography.Xml.Tests.XmlDecryptionTransformTest.GetOutput_XmlNoEncryptedData
System.Security.Cryptography.Xml.Tests.XmlDecryptionTransformTest.GetOutput_XmlWithEncryptedDataAndExcept

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/39/testReport/System.Security.Cryptography.Xml.Tests/XmlDecryptionTransformTest/GetOutput_XmlWithEncryptedDataInRoot/

MESSAGE:
~~~
System.NullReferenceException : Object reference not set to an instance of an object.
~~~
STACK TRACE:
~~~
at System.Security.Cryptography.Xml.Transform.get_PropagatedNamespaces() 
at System.Security.Cryptography.Xml.XmlDecryptionTransform.GetOutput() 
at System.Security.Cryptography.Xml.Tests.XmlDecryptionTransformTest.GetTransformedOutput(XmlDocument doc, String nodeToEncrypt) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Cryptography.Xml\tests\XmlDecryptionTransformTest.cs:line 241 
at System.Security.Cryptography.Xml.Tests.XmlDecryptionTransformTest.GetOutput_XmlWithEncryptedDataInRoot() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Cryptography.Xml\tests\XmlDecryptionTransformTest.cs:line 201
~~~

**Comment by karelz** [comment]
Fixed in #19376
