### ISSUE TITLE
Desktop: System.Security.Cryptography.Xml.Tests.SigningAndVerifyingWithCustomSignatureMethod.SignedXmlHasVerifiableSignature failed with "System.Security.Cryptography.CryptographicException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#19269]
Failed test: System.Security.Cryptography.Xml.Tests.SigningAndVerifyingWithCustomSignatureMethod.SignedXmlHasVerifiableSignature

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/39/testReport/System.Security.Cryptography.Xml.Tests/SigningAndVerifyingWithCustomSignatureMethod/SignedXmlHasVerifiableSignature_signatureMethod____http___www_w3_org_2001_04_xmldsig_more_rsa_sha256____digestMethod____http___www_w3_org_2001_04_xmlenc_sha256___/

MESSAGE:
~~~
System.Security.Cryptography.CryptographicException : SignatureDescription could not be created for the signature algorithm supplied.
~~~
STACK TRACE:
~~~
at System.Security.Cryptography.Xml.SignedXml.ComputeSignature() 
at System.Security.Cryptography.Xml.Tests.SigningAndVerifyingWithCustomSignatureMethod.SignXml(XmlDocument doc, RSA key, String signatureMethod, String digestMethod) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Cryptography.Xml\tests\Samples\SigningVerifyingWithCustomSignatureMethod.cs:line 42 
at System.Security.Cryptography.Xml.Tests.SigningAndVerifyingWithCustomSignatureMethod.SignedXmlHasVerifiableSignature(String signatureMethod, String digestMethod) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Cryptography.Xml\tests\Samples\SigningVerifyingWithCustomSignatureMethod.cs:line 71
~~~

**Comment by krwq** [comment]
I do not recall seeing this failure locally - the only one I was seeing was this: https://github.com/dotnet/corefx/issues/19272

**Comment by krwq** [comment]
@bartonjs could we possibly be missing sha2 algorithms on this desktop implementation? Is it ok if I probe CryptoConfig on desktop to check if they are there or should we find some better way? I do not have local repro for this.

**Comment by bartonjs** [comment]
In order to repro it you'll need a machine which doesn't have net462 or net47 installed (just net461).

Probing CryptoConfig when on netfx seems reasonable.
