### ISSUE TITLE
Desktop: Tests under "System.Security.Cryptography.Cng.Tests.RsaCngTests" failed with "System.Security.Cryptography.CryptographicException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#19283]
Failed tests: 
System.Security.Cryptography.Cng.Tests.RsaCngTests.RSACng_Ctor_UnusualKeysize_1032
System.Security.Cryptography.Cng.Tests.RsaCngTests.RSACng_Ctor_UnusualKeysize_384

Detail:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/39/testReport/System.Security.Cryptography.Cng.Tests/RsaCngTests/RSACng_Ctor_UnusualKeysize_1032/
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/39/testReport/System.Security.Cryptography.Cng.Tests/RsaCngTests/RSACng_Ctor_UnusualKeysize_384/

MESSAGE:
~~~
System.Security.Cryptography.CryptographicException : Specified key is not a valid size for this algorithm.
~~~
STACK TRACE:
~~~
at System.Security.Cryptography.AsymmetricAlgorithm.set_KeySize(Int32 value) 
at System.Security.Cryptography.RSACng.set_Key(CngKey value) 
at System.Security.Cryptography.Cng.Tests.RsaCngTests.RSACng_Ctor_UnusualKeysize(Int32 expectedKeySize, Byte[] keyBlob, RSAParameters expectedParameters) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Cryptography.Cng\tests\RsaCngTests.cs:line 140 
at System.Security.Cryptography.Cng.Tests.RsaCngTests.RSACng_Ctor_UnusualKeysize_1032() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Security.Cryptography.Cng\tests\RsaCngTests.cs:line 128
~~~

**Comment by danmosemsft** [comment]
@bartonjs ?

**Comment by bartonjs** [comment]
net462 fix.  Prior to net462 we got cranky if the key size was invalid per our LegalKeySizes definition.  In net462 we said "eh, the OS says it's fine, here's the answer".  So we'd want to name this condition something like `KeySizeTrustsOSValue` if we want to have feature-named conditions.
