### ISSUE TITLE
strongly typed list<>

### ISSUE THREAD

**Issue by cheers00** [dotnet/corefx#1929]
Wondering if strongly typed list available in corefx.

**Comment by stephentoub** [comment]
If you mean via the library surface area, yes, it's available through System.Collections.dll.  If you mean the source code, that actually lives in the coreclr repo, as it's type-forwarded from System.Collections.dll to mscorlib.

**Comment by mellinoe** [comment]
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/List.cs

**Comment by cheers00** [comment]
Thanks.
