### ISSUE TITLE
Support building corefx on Ubuntu 17.04 and OSX 10.13

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#19305]
When building corefx on Ubuntu 17.04 getting some error like:

```
/home/tarek/oss/corefx/Tools/depproj.targets(83,5): error : Error no assets were resolved from NuGet packages. [/home/tarek/oss/corefx/external/ilasm/ilasm.depproj]
```

**Comment by tarekgh** [comment]
CC @mellinoe

**Comment by tarekgh** [comment]
#19284

**Comment by danmosemsft** [comment]
@janvorli as I think he was looking at build on latest distros.

**Comment by mellinoe** [comment]
I think he was looking at OLDER distros, rather than newer.

@weshaggard , @ericstj Can we just add ubuntu.17.04-x64 to the RID graph? I think the build should work fine as long as the CLI knows that it can pick up the portable Linux assets for Ubuntu 17.04. The problem right now is most likely that ubuntu.17.04-x64 is just a "completely unknown RID", and the tools don't know what to do with it.

**Comment by weshaggard** [comment]
We can consider adding this to the RID graph but not to fix the corefx build issue. For the corefx build issue we should start using the portable RIDs for our tools.

**Comment by janvorli** [comment]
@mellinoe I was actually looking into both cases recently - Debian 9 being the new distro case. But I was looking only into building native parts.

**Comment by ViktorHofer** [comment]
I just tried it and facing the same issue as Tarek. Is there an update on that matter?

**Comment by weshaggard** [comment]
This issue actually occurs when trying to build corefx for any new OS where we don't know about the RID. Some folks are also hitting this on OSX.10.13.

To work around this on folks can explicitly pass in the following property:
```
// For OSX
./build.sh -- /p:NugetRuntimeIdentifier=osx-x64

// For Linux
./build.sh -- /p:NugetRuntimeIdentifier=linux-x64
```

This issue will likely get handled as part of this PR https://github.com/dotnet/corefx/pull/21032.

**Comment by Petermarcu** [comment]
In 2.0 we intentionally moved to "portable" rids. I assume this issue is not about tracking the fix to the infra to infer the portable rid instead of the specific one?

**Comment by weshaggard** [comment]
>I assume this issue is not about tracking the fix to the infra to infer the portable rid instead of the specific one?

Yes I think this issue is about moving to consuming our portable assets for our external dependencies.

**Comment by weshaggard** [comment]
This should be fixed with https://github.com/dotnet/corefx/pull/21032. Please let me know if that isn't the case.

**Comment by bartonjs** [comment]
@weshaggard Every time I switch back to release/2.0.0 for whatever reason on my mac I need to hunt down the word "NuGetRuntimeIdentifier" again.  Is it feasible to make ./build.sh work with no esoteric parameters in release/2.0.0?

**Comment by weshaggard** [comment]
@bartonjs I assume this works fine for you in master? If so we can work on getting https://github.com/dotnet/corefx/pull/21032 ported to release/2.0.0 we might need it for some of the source-build stuff I'm working on anyway.

**Comment by bartonjs** [comment]
Yep, `./build.sh` runs fine in dotnet/master (57b4664ba)
