### ISSUE TITLE
Modified SocketPerformance_MultipleSocketClientAsync_LocalHostServerAsync can't handle large buffers

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#19307]
The test SocketPerformanceAsyncTests.SocketPerformance_MultipleSocketClientAsync_LocalHostServerAsync was modified to send a large buffer which occasionally fails under Unix, but works under Windows.

To repro the error, modify the test variables as follows:
```c#
int iterations = 20; // was 200 * _iterations
int bufferSize = 8192; // was 256
int socket_instances = 1; // was 200
```
The smallest buffer that repros was 4096 but that does not repro as easily as 8192. A buffer size of 2048 did not repro even after thousands of runs.

The result with these settings should be an Exception thrown from the test with a message `"Unexpected bytesSent"`. If this is debugged slightly, the number of bytes received by the client is lower than expected, and the value can vary with each run.

The test uses a Socket with SocketType.Stream and client using TaskCompletionSource<int> to return the number of bytes sent.

Whether this is a test or product bug is not known yet; the Windows version works even for very large buffers.

**Comment by karelz** [comment]
Worst case assessment: Send\Receive doesn’t work with large buffers on Linux.

**Comment by karelz** [comment]
@Priya91 can you please cost it?

**Comment by Priya91** [comment]
I'm not that familiar with this code base, need to debug the test for rootcause. cc @geoffkizer who's worked in this area before might have more data.

**Comment by steveharter** [comment]
@stephentoub may be looking at this based on an IM today.

**Comment by karelz** [comment]
@geoffkizer can you please take a look? (@stephentoub is OOF sick)

**Comment by stephentoub** [comment]
Hopefully I'll be feeling better tomorrow and can look.

**Comment by karelz** [comment]
Thanks @stephentoub, if you do, please assign it to yourself.
@Priya91 if you have spare time and Stephen is not on it, can you please take a look?

**Comment by stephentoub** [comment]
Still under the weather... if Priya can look today, that's be great, otherwise I'll try later today or this weekend if/when I'm better.

**Comment by Priya91** [comment]
@steveharter How do you run the performance tests? ```msbuild.sh /t:rebuildandtest /p:Performance=true ``` doesnt work

**Comment by steveharter** [comment]
@Priya91 I just run them from the folder.
```
cd c:\git\corefx\bin\Windows_NT.AnyCPU.Debug\System.Net.Sockets.Async.Performance.Tests\netstandard
c:\git\corefx\bin\testhost\netcoreapp-Windows_NT-Debug-x64\dotnet.exe xunit.console.netcore.exe System.Net.Sockets.Async.Performance.Tests.dll -notrait category=nonwindowstests
```

**Comment by stephentoub** [comment]
I'm working on this now...

**Comment by stephentoub** [comment]
Figured it out... it's a one-line bug in SocketAsyncContext.Unix.cs for the case involving a list of buffers... will put up a PR to fix.
