### ISSUE TITLE
decimal ToString("C") output difference across OS platforms

### ISSUE THREAD

**Issue by billpratt** [dotnet/corefx#19318]
I have an app that uses the decimal ToString(String, IFormatProvider) method to get currency formatted string for a specific culture ie $7.99 for en-US. I have noticed a slight difference for the culture "da-dk" on what is returned across Linux/OSX/Windows.

Sample code:
```
Console.WriteLine(9.99m.ToString("C", new CultureInfo("da-dk")));
```

On Windows and OSX, the output is: **9,99 kr.**

On Linux however, the output is missing the period: **9,99 kr**

Though this is a very minor bug this is one I hope is easy to fix to have consistent behavior across OS platforms.

dotnet --info across platforms:
OSX:
```
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.3
```

Windows:
```
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3
```

Linux (To test this on Linux I used the microsoft/dotnet:1.1.1 Docker image)

**Comment by billpratt** [comment]
To test this on Linux I used the microsoft/dotnet:1.1.1 Docker image

**Comment by tarekgh** [comment]
We depend on the OS for the underlying globalization data. so we don't carry any of such data to make it consistent across the OS's or even OS versions. This is by design for the .NET framework.

It will be good if you ask for the change from the OS. from what I am seeing looks Linux has wrong data. the other idea could be update the ICU package you are using in Linux and try to install the latest package if possible.

**Comment by billpratt** [comment]
@tarekgh Since the platform I'm using in an ASP.NET Core Docker image provided by Microsoft, I have submitted the issue there
