### ISSUE TITLE
Test S.N.NetworkInformation.Tests.NetworkInterfaceBasicTest.NetworkInterface_LoopbackInterfaceIndex_MatchesReceivedPackets crashes on uapaot

### ISSUE THREAD

**Issue by alexperovich** [dotnet/corefx#19314]

**Comment by davidsh** [comment]
We shouldn't be running any of these tests for UAP for System.Net.NetworkInformation.  Most of the library is not implemented for UWP (PLatformNotSupportedException).

cc: @danmosemsft @karelz

**Comment by danmosemsft** [comment]
Meaning we should run the tests, but they should ber disabled pending work?

**Comment by alexperovich** [comment]
This issue is specifically about this test crashing XUnit so we get no results. If the tests are all expected to fail that is another thing entirely.

**Comment by caesar1995** [comment]
I have run the test for many times, and I'm not able to repro (0 failure in the log).

Please re-open the issue if test crashes again.

@davidsh
