### ISSUE TITLE
System.Runtime.InteropServices.RuntimeInformation.get_OSArchitecture() fails on Win7/WS08R2

### ISSUE THREAD

**Issue by mikeharder** [dotnet/corefx#19313]
System.Runtime.InteropServices.RuntimeInformation.get_OSArchitecture() fails on Win7/WS08R2 during the ASP.NET CI builds:

```
System.DllNotFoundException : Unable to load DLL 'api-ms-win-core-sysinfo-l1-2-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.GetNativeSystemInfo(SYSTEM_INFO& lpSystemInfo)
   at System.Runtime.InteropServices.RuntimeInformation.get_OSArchitecture()
   at Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationDeployer.GetArchitecture()
```

# Standalone Repro
1. VM with clean WS08R2
2. Install CLI 2.0.0-preview1-005917
3. Create app with files below
4. dotnet restore
5. dotnet run

## Repro.csproj
```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net46</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Runtime.InteropServices.RuntimeInformation" Version="4.3.0" />
  </ItemGroup>

</Project>
```

## Program.cs
```C#
using System;
using System.Runtime.InteropServices;

namespace Repro3
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Console.WriteLine(RuntimeInformation.OSArchitecture);            
        }
    }
}
```

NuGet.config
```XML
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by danmosemsft** [comment]
@mikeharder is this 2.0? we changed that from apiset long ago.
```
    internal partial class Kernel32
    {
        [DllImport(Libraries.Kernel32)]
        internal extern static void GetNativeSystemInfo(out SYSTEM_INFO lpSystemInfo);
    }
```

@gkhanna79

**Comment by danmosemsft** [comment]
@mikeharder also, did this start brekaing recently?

**Comment by mikeharder** [comment]
@danmosemsft: The issue is impacting ASP.NET 2.0.0-preview1 tests.  It might be that ASP.NET is referencing an older version of the package than it should be.  Still investigating.

**Comment by mikeharder** [comment]
We're not sure exactly when it started failing, since ASP.NET tests on Win7 were blocked for a long time with SqlClient issues, and we're just now uncovering additional issues.

**Comment by mikeharder** [comment]
Added standalone repro.  Impacts apps targeting `net46` and referencing `System.Runtime.InteropServices.RuntimeInformation, Version=4.3.0`.

**Comment by mikeharder** [comment]
CC: @anurse

**Comment by gkhanna79** [comment]
CC @weshaggard

**Comment by gkhanna79** [comment]
So, this is an older version of the package that already shipped?

**Comment by gkhanna79** [comment]
If you add reference to https://www.nuget.org/packages/Microsoft.NETCore.Windows.ApiSets/1.0.1, does it address the problem?

**Comment by weshaggard** [comment]
This has always been an known issue. See https://github.com/dotnet/corefx/issues/8091#issuecomment-225641743. We fixed it with the latest package however because we no longer depend on api-sets. https://github.com/dotnet/corefx/issues/13566.
