### ISSUE TITLE
Remove UAP10.1 assets in packages

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#19316]
For the .NET Core 2.0 release we should exclude any uap10.1 specific assets in the individual packages as that isn't the correct TFM and we are targeting 2.1 for finishing that work so we should exclude them for now. The only uap package we should produce is the private platform package, but that one won't actually ship on nuget org.

cc @ericstj @joperezr @danmosemsft

**Comment by joperezr** [comment]
That is a good point although I'm not sure how easy will it be to implement this change with our packaging infrastructure, @ericstj would obviously know better. Just throwing out a thought, what if just for  2.0 we package all uap10.1 as uap10.0 in individual packages? I'm not sure if that would work but I can think that it in case it does, this would be an easier workaround than to skip packaging some assets in some verticals.

**Comment by ericstj** [comment]
We should be able to centrally exclude them relatively easily.

**Comment by joperezr** [comment]
What would be the plan then for internal people that needs consuming these packages since they are doing it today? Like PN for example? Or perhaps this issue will only be fixed once we have a release branch so that master packages still contain uap assets

**Comment by ericstj** [comment]
Yeah, only release branch.  Master will continue to have UAP10.1 assets.
