### ISSUE TITLE
`Path.GetPathRoot(string.Empty)` difference in behavior

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#19342]
`Path.GetPathRoot(string.Empty)` in Desktop throws `ArgumentException`, on .NET Core it returns `String.Empty`

See msdn documentation: https://msdn.microsoft.com/en-us/library/system.io.path.getpathroot(v=vs.100).aspx

cc: @JeremyKuhne @ianhays

**Comment by ViktorHofer** [comment]
`Path.GetPathRoot(" ")` in Desktop throws `ArgumentException`, on .NET Core it returns `String.Empty`

The documentation is indeed wrong about the current behavior on Desktop:

> The root directory of path, such as "C:\", or null if path is null, or an empty string if path does not contain root directory information.

If Path does not contain root directory information but a whitespaced string it throws ArgumentException.

**Comment by ViktorHofer** [comment]
I have a fix for both issues. If somebody agrees this isn't intentionally broken I will submit it for both coreclr and a few tests for corefx.

**Comment by danmosemsft** [comment]
We should match desktop behavior.

**Comment by JeremyKuhne** [comment]
> We should match desktop behavior.

I'm **not** keen on matching desktop in this case- especially as it doesn't match documentation. While it is _possible_ that code may depend on this behavior I suspect it is really really remote.

**Comment by JeremyKuhne** [comment]
I also think code is more likely to break expecting that this doesn't throw than vice-versa.

**Comment by ViktorHofer** [comment]
> I'm not keen on matching desktop in this case- especially as it doesn't match documentation

@JeremyKuhne The documention states ArgumentException throws when "String.Empty was passed to path.". I think Desktop matches the docs.

**Comment by JeremyKuhne** [comment]
Sorry, I misread, consider my objection withdrawn. Even though I dislike this behavior. :)

**Comment by ViktorHofer** [comment]
yes 👍
