### ISSUE TITLE
Add nice messages to all auto generated PNSE

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#19358]
For 2.0 we need to build on https://github.com/dotnet/buildtools/issues/1449 to add nice messages to all PNSE generated code. Talk to area owners to get nice strings.

**Comment by tarekgh** [comment]
@sepidehMS are you currently working on this issue?

**Comment by sepidehMS** [comment]
@tarekgh I haven't started talking to the area owners yet. Had plans to do this today. Why? :)

**Comment by tarekgh** [comment]
@sepidehMS I know @danmosemsft mentioned this v2.0 but I am not sure if this is has to be v2.0 as we can ship without it. If you are planning to work on it soon then that is fine.

**Comment by krwq** [comment]
@tarekgh - I think this is more a validation that we actually know about each PNSE and checking it again - concrete message suggests that someone knows why this is happening. Probably best if @danmosemsft comments

**Comment by tarekgh** [comment]
@krwq the stack trace in the exception can give this clue. I am seeing this something nice to have but is not  shipping stopper. as I mentioned I am ok to keep it on 2.0 as long as @sepidehMS already working on it.

**Comment by krwq** [comment]
@tarekgh fair point - I agree this is not a ship blocker but rather "should be done" category - @danmosemsft, what's the current bar for 2.0?

**Comment by tarekgh** [comment]
here is the bar: 

https://microsoft.sharepoint.com/teams/netfx/corefx/_layouts/OneNote.aspx?id=%2Fteams%2Fnetfx%2Fcorefx%2FDocuments%2FCoreFx%20Notes&wd=target%28Engineering%2FNET%20Core%20Planning.one%7C2020910E-13D4-4EDF-B477-853BE556D6A9%2F2.0%20Github%20triage%20bar%7C67AD81EF-00F0-4051-9534-6F2A2FE60750%2F%29

**Comment by danmosemsft** [comment]
Part of the 2.0 bar is "important for supporting 2.0 scenarios" or words to that effect. One of the top scenarios is making it easy to port to core. This is a simple change that helps port to core. If I get "Code access security is not supported on this platform" it tells me more than what I find out by just having one CAS related API fail. 

I wouldn't take it to shiproom probably but there's plenty of time to do it before then.

**Comment by ViktorHofer** [comment]
That's basically one of the biggest issues I'm hearing from customers in Austria right now. Transparency and documentation is lacking in .NET Core. The open docs repo and the tool @terrajobst is currently working on are definitely steps in the right direction.
