### ISSUE TITLE
[Suggestion] A general AOP inplementation structure, please

### ISSUE THREAD

**Issue by MaleDong** [dotnet/corefx#1935]
I know that we can use dynamic AOP structure such as "Dynamic Proxy", however that is a heavy bag for me. And to be honest, any dynamic compiling will need an interface to do AOP's injection. So if I have too many methods for AOP (such as do auto logging), I have to define so many interfaces or virtual methods.....

And consider that Microsoft seems to like "trick" in syntax such as C#'s LINQ, Async……It would be better if Microsoft can:

1) Define an Attribute or an interface that contains: DoBeforeExecute, DoExecute and DoAfterExecute.
2) Any method, class with the attributes will be automatcially do these steps, when the method is called.
3) When compiling, these customized attributes will be "injected" into your IL (Something like PostSharp, however PostSharp needs money and you see that this is a very important thing sometimes). 

I think NET's framework's everything is good except for a general AOP framework. So it's a necessary thing for Microsoft to add this very important into your framework.

**Comment by svick** [comment]
I think this looks like a proposal to change the C# language or the compiler, not the .Net library, which means this proposal probably belongs to [the Roslyn repo](https://github.com/dotnet/roslyn).

Also, to give some history, there was [a UserVoice proposal to "Make AOP a fundamental part of the .NET framework"](http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/2208065-make-aop-a-fundamental-part-of-the-net-framework), which was declined in 2012. And this would probably fall under the general topic of metaprogramming, which is listed under "Probably not this time" in [the C# 7 Work List of Features](https://github.com/dotnet/roslyn/issues/2136).

**Comment by stephentoub** [comment]
Thanks.  Yes, any such types in corefx would need to be support of a language/compiler feature.  As such I'm going to close this issue out, but of course feel free to request something over on Roslyn.

**Comment by MaleDong** [comment]
Well……I wanna know the process：Can Roslyn have this function anywhere in WinForm, WPF or ASP.NET WebForm, as well as in MVC？Any changes now?
