### ISSUE TITLE
Multiple tests in S.Net.Security cause xunit to crash on AOT

### ISSUE THREAD

**Issue by alexperovich** [dotnet/corefx#19379]
The following tests cause xunit to crash:

- CertificateValidationClientServer_EndToEnd_Ok
- CertificateValidationRemoteServer_EndToEnd_Ok
- ClientAsyncAuthenticate_ServerRequireEncryption_ConnectWithEncryption
- ClientAsyncAuthenticate_ServerNoEncryption_NoConnect
- ClientDefaultEncryption_ServerRequireEncryption_ConnectWithEncryption
- ClientDefaultEncryption_ServerNoEncryption_NoConnect
- EventSource_ExistsWithCorrectId
- NegotiateStream_StreamToStream_Authentication_TargetName_Success
- SslStreamConstructor_BadEncryptionPolicy_ThrowException
- ServerNoEncryption_ClientRequireEncryption_NoConnect
- ServerRequireEncryption_ClientRequireEncryption_ConnectWithEncryption
- ServerRequireEncryption_ClientAllowNoEncryption_ConnectWithEncryption
- ServerRequireEncryption_ClientNoEncryption_NoConnect
- SslStream_StreamToStream_Authentication_IncorrectServerName_Fail
- SslStream_StreamToStream_LargeWrites_Sync_Success
- SslStream_StreamToStream_Successive_ClientWrite_Async_Success
- SslStream_StreamToStream_WriteAsync_ReadByte_Success
- TransportContext_ConnectToServerWithSsl_GetExpectedChannelBindings

**Comment by davidsh** [comment]
FYI System.Net.Security isn't even available yet for UWP (AOT).  We recently did add the API surface for netstandard but we haven't done any work on this library yet since we have been working to get the implementation (which uses win32 APIs) to be workable in UWP.

**Comment by CIPop** [comment]
I've tested some of these already and they pass on both UAP and UAPAOT. 
I didn't yet run the tests disabled by ActiveIssues for previous CI reasons. That is currently tracked by #21285.
