### ISSUE TITLE
Add support for getting current stack into Exception

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#19416]
When writing managed wrappers for native components, it's common to create an Exception in one location (e.g. in a callback from native that includes an error code) and to then pass that off to a completely different location (e.g. storing the Exception into a TaskCompletionSource, with its Task awaited somewhere else).  In doing so, the created Exception object doesn't contain any stack trace information about the original location where it was created, sometimes making it difficult to track down where it came from.  It would be very helpful if there were a way of storing the equivalent of Environment.StackTrace into an Exception object.  It's possible to do:
```C#
try { throw e; } catch { }
```
but that doesn't really help, as the stack trace will only include the calling frame, not the entire stack, since the stack will stop after the catching frame.

This shows up in a bunch of our components.

**Proposal**

```C#
public static class ExceptionDispatchInfo
{
    ...
    public static void AppendCurrentStackTrace(Exception source);
    ...
}
```

cc: @jkotas

**Comment by terrajobst** [comment]
Based on the scenario, it seems `SetCurrentStackTrace` would more sense; if we ever need an append, we can add an overload with a Boolean.
