### ISSUE TITLE
Disable CLI's first time experience from within our repo

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#19413]
We don't want to run the CLI's first time experience in our builds.

See discussion: https://github.com/dotnet/corefx/pull/19407#issuecomment-299530720

/cc @weshaggard @eerhardt @livarcocc

**Comment by danmosemsft** [comment]
@ericstj is this 2.0?

**Comment by ericstj** [comment]
It's a general improvement.  Not must have for 2.0.

**Comment by ViktorHofer** [comment]
qq, was this ever done?

**Comment by eerhardt** [comment]
Yes.

https://github.com/dotnet/corefx/blob/4c314da457b550859e74f1f10f57d41b5fa07ca5/run.cmd#L42
https://github.com/dotnet/corefx/blob/4c314da457b550859e74f1f10f57d41b5fa07ca5/run.sh#L7
