### ISSUE TITLE
System.Net.Primitives.Functional.Tests.CookieTest.Value_PassNullToCtor_GetReturnsEmptyString_net46 fails consistently on all my dev machines

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#19423]
Running `msbuild /t:rebuild,test /p:Outerloop=true` in `\src\System.Net.Primitives\tests\FunctionalTests`

```
     System.Net.Primitives.Functional.Tests.CookieTest.Value_PassNullToCtor_GetReturnsEmptyString_net46 [FAIL]
        Assert.Null() Failure
        Expected: (null)
        Actual:
        Stack Trace:
           S:\corefx\src\System.Net.Primitives\tests\FunctionalTests\CookieTest.cs(249,0): at System.Net.Primitives.Functional.Tests.CookieTest.Value_PassNullToCtor_GetReturnsEmptyString_net46()
     System.Net.Primitives.Functional.Tests.CookieTest.Value_PassNullToCtor_GetReturnsEmptyString_net46 [FINISHED] Time: 0.0016697s
```

**Comment by CIPop** [comment]
/cc @davidsh @DavidGoll @karelz 

For some reason this only fails when I run these tests separately but not when I run the `build-tests -outerloop` command.

**Comment by danmosemsft** [comment]
Is it actually running (does it show up in the log) when you do `build-tests -outerloop` .. maybe there's a glitch in that.

**Comment by CIPop** [comment]
@weshaggard @danmosemsft This is identical to #19427. The same workaround fixes the issue (running `msbuild /t:rebuild,test /p:Outerloop=true` will not have any errors).

> Is it actually running (does it show up in the log) when you do build-tests -outerloop .. maybe there's a glitch in that.

@danmosemsft  I didn't see any errors when running e2e testing.

Duplicate to #19427, dotnet/buildtools#1462

**Comment by danmosemsft** [comment]
OK thanks, I'll look at that dupe when i have cycles.
