### ISSUE TITLE
Specifying /p:XunitOptions overrides -notrait category=nonnetcoreapptests

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#19427]
Running in `\src\System.Net.Mail\tests\Functional`, 
`msbuild /t:rebuild,test /p:Outerloop=true "/p:XunitOptions=-showprogress"` fails on my local dev box:

```
     System.Net.Mail.Tests.SmtpClientTest.ServicePoint_NetFramework_AddressIsInaccessible [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.NotSupportedException)
        Actual:   (No exception was thrown)
        Stack Trace:
           R:\corefx\src\System.Net.Mail\tests\Functional\SmtpClientTest.cs(139,0): at System.Net.Mail.Tests.SmtpClientTest.ServicePoint_NetFramework_
  AddressIsInaccessible()
     System.Net.Mail.Tests.SmtpClientTest.ServicePoint_NetFramework_AddressIsInaccessible [FINISHED] Time: 0.0122828s
```

**Comment by stephentoub** [comment]
The test is attributed as:
```
[SkipOnTargetFramework(TargetFrameworkMonikers.Netcoreapp | TargetFrameworkMonikers.Uap)]
```
It shouldn't have run.  This version of the test is specifically for desktop, whereas the test above it:
https://github.com/dotnet/corefx/blob/d0f39403fc7dedbafe7aeec8716f1f2ccb561bb1/src/System.Net.Mail/tests/Functional/SmtpClientTest.cs#L122
is the one that's meant for .NET Core, and is obviously passing appropriately.

**Comment by davidsh** [comment]
>It shouldn't have run. 

So, why did it run when the SkipOnTargetFramework attribute told it not to run? 

Is it possible that specifying Xunit options here: "/p:XunitOptions=-showprogress" is somehow interfering with the calculation of the Skip* attributes?

**Comment by karelz** [comment]
@weshaggard - any idea if this is tooling problem, or usage/documentation problem?
cc @mellinoe

**Comment by stephentoub** [comment]
> Is it possible that specifying Xunit options here: "/p:XunitOptions=-showprogress" is somehow interfering with the calculation of the Skip* attributes?

That appears to be the case.  When I don't specify /p:XunitOptions, I get:
```
call %RUNTIME_PATH%\dotnet.exe xunit.console.netcore.exe System.Net.Sockets.Tests.dll  -xml testResults.xml -notrait category=nonnetcoreapptests  -notrait category=failing -notrait category=nonwindowstests
```
but when I do, I get:
```
call %RUNTIME_PATH%\dotnet.exe xunit.console.netcore.exe System.Net.Sockets.Tests.dll   -notrait category=failing -notrait category=nonwindowstests
```
Note the former includes ```-notrait category=nonnetcoreapptests``` whereas the latter does not.

**Comment by stephentoub** [comment]
Related:
https://github.com/dotnet/buildtools/pull/1462

**Comment by weshaggard** [comment]
Yes I think this issue can be closed and instead tracked with https://github.com/dotnet/buildtools/pull/1462 as it provides a way to make sure we can add additional xunit options without messing with the default ones we calculate.

**Comment by CIPop** [comment]
@weshaggard Isn't this the same as #19423? That one seems to run during outerloop according to @danmosemsft .

**Comment by CIPop** [comment]
Disregard the last comment. It wasn't clear to me what the issue was.

__Workaround__:

`msbuild /t:rebuild,test /p:Outerloop=true`

Do not add any other options as they will interfere with test execution.

**Comment by safern** [comment]
@CIPop just FYI: this was fixed yesterday in: https://github.com/dotnet/buildtools/pull/1518
