### ISSUE TITLE
Sign contents of runtime.win-x64.runtime.native.system.data.sqlclient.sni

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#19433]

**Comment by ViktorHofer** [comment]
@saurabh500 is this required for ZBB? do you need help?

**Comment by ViktorHofer** [comment]
@safern after talking with @saurabh500 offline it seems like this needs to be done ASAP. Help by someone who is more verbose in the build system and microbuilds is very appreciated. Do you think you can help? If yes, please contact @saurabh500

**Comment by safern** [comment]
I don't have a lot of context in signing but I can take a look on how we sign other packages and maybe figure that out ;)

**Comment by safern** [comment]
Adding @weshaggard who is the expert in signing.

**Comment by weshaggard** [comment]
@saurabh500 this has to be done by the official build system you have for sni. We cannot do this in corefx as you have already packaged the binary and we cannot (and should not) pull it out sign it and repackage it.
