### ISSUE TITLE
Performance issue in ImmutableSortedSet.LeafToRootRefill

### ISSUE THREAD

**Issue by lifengl** [dotnet/corefx#1943]
The implementation is using a SortedSet, and then build the balance tree based on it.  It should not use the SortedSet here.  Internally, the SortedSet will use a list to sort items (unless the input collection is a sortedSet), and convert it to an array, then build into its own balance tree.  Because the SortedSet doesn’t support indexers, the immutable collection code will convert the SortedSet to an array, then use it to build its own AVL tree.  Those conversions are totally wasted, including allocating the entire tree in SortedSet.  The code can directly sort items with a list.

**Comment by stephentoub** [comment]
cc: @AArnott

**Comment by AArnott** [comment]
I agree. I implemented that particular method the cheapest way I could at the time to make it API complete, knowing eventually it would likely need to be re-implemented in a more efficient way.
