### ISSUE TITLE
Potential bug in HttpListener: adding an invalid prefix throws, but is still added

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#19437]
HttpListener refuses a uri prefix that has a host greater than length 255, throwing an `ArgumentOutOfRangeException`.

However, the prefix is still added. This breaks expectations of the user IMO.

Obviously HttpListener is a compat/legacy API. And, the full .NET Framework also has this bug, so this isn't a 2.0 issue and we may not even want to fix it

```cs
[Fact]
public void Add_LongHost_ThrowsArgumentOutOfRangeException()
{
    var listener = new HttpListener();
    string longPrefix = "http://" + new string('a', 256) + "/";
    Assert.Throws<ArgumentOutOfRangeException>("hostName", () => listener.Prefixes.Add(longPrefix));

    // Ouch: even though adding the prefix threw an exception, the prefix was still added.
    Assert.Equal(1, listener.Prefixes.Count);
    Assert.True(listener.Prefixes.Contains(longPrefix));

    Assert.Throws<HttpListenerException>(() => listener.Start());
}
```

**Comment by karelz** [comment]
I would suggest to close it, unless:
1. We see customers hitting it hard
2. Fix is simple and someone submits it

Otherwise I would not invest in legacy APIs to this level ... thoughts?

**Comment by hughbe** [comment]
Not sure about 1, but 2. I could fix after 5/10, should be as simple as wrapping the addition of the the prefix to the list of services in a try/catch. If an exception is thrown, then just remove the prefix from the list.

it's just awkward that this puts the listener in what could be described as a corrupted state. Obviously @davidsh and @priya91 and @stephentoub may have thoughts

Not important to spend Dev time until post-ZBB though so no pressure here

**Comment by karelz** [comment]
Sounds reasonable, thanks for the info!
And thanks for all your great help here in CoreFX repo, especially your help with landing 2.0! We highly appreciate it!

**Comment by Priya91** [comment]
Thanks @hughbe for reporting the bug, @davidsh / @CIPop The behavior exists on desktop as well, FYI.

Considering httplistener as legacy and fixing the behavior on .NET Core, and taking back the changes to desktop with quirks is not valuable in this case in my opinion. @davidsh / @CIPop Can provide more info.

**Comment by hughbe** [comment]
I agree. Let's close this issue. Investments for HttpListener should be limited to testing, netfx compat and managed/http.sys compatibility
