### ISSUE TITLE
HttpClient version System.Net.Http\4.3.0\ref\netstandard1.3\System.Net.Http.dll ignores proxy in asp.net core 1.1 app

### ISSUE THREAD

**Issue by robertledinski** [dotnet/corefx#19441]
When I try to use HttpClientHandler with my proxy server and add it to HttpClient requests go directly instead over proxy server. I checked multiple times using wireshark and fiddler, it doesn't matter if proxy is working ip or is it a fake one. I don't get any error and requests go directly.

For double checking I went on the server on which I sent requests and there wasn't IP address of sever 
which was used as proxy but direct PC.

I can write here code part of code to show.

**Comment by karelz** [comment]
Can you try latest version of the package - 4.3.1. We changed the implementation significantly.

**Comment by davidsh** [comment]
>When I try to use HttpClientHandler with my proxy server 

How exactly are you specifying the proxy server to HttpClient*?  HttpClient will usually look for proxy settings in the either the system default location (wininet / ie settings) or use a custom proxy specified via the HttpClientHandler.Proxy property.

**Comment by robertledinski** [comment]
karelz I just tried with package - 4.3.1 but problem remains. 
System.Net.Http\4.3.1\ref\netstandard1.3\System.Net.Http.dll

Here is my implementation example.
[proxy implementation.txt](https://github.com/dotnet/corefx/files/981177/proxy.implementation.txt)
You can check with your proxy server as well. I tried using both wireshark and fiddler. If i put proxy IP on my browser than it is working so it's 100% not proxy problem.

**Comment by davidsh** [comment]
Thanks for posting the code to your repro.  I looked thru it and I wonder whether it has ever worked?  Did this code work before with some other version of .NET Framework or .NET Core and now doesn't work?

Or, is this the first time you have tried out this code?

Looking at the code below:  it is not using the right semantics for specifying a proxy.  For example, you must always set HttpClientHandler.UseProxy to `true` if you want the IWebProxy interface to be interface to used.  Since you have a custom proxy, if IWebProxy returns true for IsBypassed(), then that request will not go thru the proxy.

You currently are setting the HttpClientHandler.UseProxy flag to something based on calling your custom proxy class. But that isn't correct.

```c#
Proxy proxy;
HttpClientHandler handler;
HttpClient httpClient;

protected string data()
{
    // init proxy url
    proxy = new Proxy(_proxyLink);

    handler = new HttpClientHandler
    {
        Proxy = proxy,
        UseProxy = proxy.IsBypassed(new Uri("_proxyLink"))
    };

    httpClient = new HttpClient(handler);

    // target Url
    Uri requestUri = new Uri(requestContainer.Url, UriKind.Absolute);
    Task<HttpResponseMessage> httpMsg = httpClient.PostAsync(requestUri, new StringContent("some body data" ?? "", Encoding.UTF8, requestContainer.ContentType));

    string result = null;

    httpMsg.Wait();
    HttpResponseMessage msgResult = httpMsg.Result;

    Task<string> readResultTask = msgResult.Content.ReadAsStringAsync();
    readResultTask.Wait();

    result = readResultTask.Result;

    return result;
}

class Proxy : System.Net.IWebProxy
{

    private System.Net.ICredentials creds;
    private string _proxy;
    private bool _proxyStatus;

    public Proxy(string proxy)
    {
        _proxyStatus = true;
        _proxy = proxy;
        GetProxy(new Uri(proxy));
    }
    
    public System.Net.ICredentials Credentials
    {
        get; set;
    }

    public Uri GetProxy(Uri destination)
    {
        if (!String.IsNullOrWhiteSpace(destination.ToString()))
            return destination;
        else
            return new Uri("");
    }

    public bool IsBypassed(Uri host)
    {
        if (!String.IsNullOrWhiteSpace(host.ToString()))
            return true;
        else
            return false;
    }   
```

I also don't understand what your custom proxy class has a constructor that is calling your internal method GetProxy().  That doesn't do anything.

**Comment by davidsh** [comment]
Also, I believe the key problem here is that your code is not really returning a valid proxy at all.

This code:

```c#
public Uri GetProxy(Uri destination)
    {
        if (!String.IsNullOrWhiteSpace(destination.ToString()))
            return destination;
        else
            return new Uri("");
    }
```

Is supposed to return the Uri of a proxy server based on a destination Uri.  But you are always returning the destination Uri from this method.  Instead, you should be returning "_proxyLink".    The reason why a proxy server isn't been used is because the GetProxy() method is never returning a proxy server Uri.  It is always returning the destination Uri.  Doing that results in never using your proxy server.

**Comment by robertledinski** [comment]
I know that code has some useless parts (i tried doing lots of random things). Do not mind GetProxy method parameter name. If I add  through constructor proxy url as private variable and use it in GetProxy it still doesn't work. 

If u see requestUri that is URL of server on which I want to sent request and it is not used anywhere before that part.

**Comment by robertledinski** [comment]
I suggest that u try using HttpClient and set your proxy server without credentials. U will see that using proxy will not work and no error will be shown. Request will go directly to targeted server without going through proxyed server. That is main thing I want to point out.

**Comment by karelz** [comment]
@robertledinski can you please provide working minimal repro? Otherwise I fear it is not actionable for us.

**Comment by davidsh** [comment]
As I mentioned above, this method must return a proxy Uri and not the destination Uri.

```c#
public Uri GetProxy(Uri destination)
{
    if (!String.IsNullOrWhiteSpace(destination.ToString()))
        return destination;
    else
        return new Uri("");
}
```

Please attach a complete working repro Visual Studio solution. Thanks.

**Comment by robertledinski** [comment]
First I would thank both of you for being patient with me and my mistakes such as not explaining best. On this link u can find test project which proves that proxy is not working.

https://github.com/robertledinski/HttpClient

Thank you for your fast answers even on Sunday.

**Comment by ism** [comment]
https://github.com/robertledinski/HttpClient/blob/master/src/HttpClient%20Proxy/Program.cs#L65

here you have set it to true

and from documentation 
"If IsBypassed is true, the proxy is not used to contact the host and the request is passed directly to the server."

Is that the case?

**Comment by robertledinski** [comment]
@ism  Thank you ism, I just set it to false and now I get this. 

![image](https://cloud.githubusercontent.com/assets/17179120/25797994/c81841e6-33df-11e7-8145-4997c183520e.png)

It's not really descriptive, any suggestion?

**Comment by ism** [comment]
@robertledinski now when your requests are proxified, you may want to install fiddler and use it to debug your session.

**Comment by robertledinski** [comment]
@ism This did help with the problem and I did some progress. however now I this error.

> [error](https://cloud.githubusercontent.com/assets/17179120/25797994/c81841e6-33df-11e7-8145-4997c183520e.png)

**Comment by ism** [comment]
@robertledinski can you attach fiddler log of your requests, please?

**Comment by robertledinski** [comment]
@ism It seems I was using https and my proxy server was configured to use http. Fiddler couldn't see it, but wireshark did. Thank you very much for help. Problem was in property IsBypassed was set to true.
