### ISSUE TITLE
Does .NET Core work on Arch Linux?

### ISSUE THREAD

**Issue by orb77** [dotnet/corefx#19447]
I'm using Antergos which is Arch Linux distribution and I was trying last several months to build 
dotnet core. 
Every time I was trying to build dotnet core I was facing different problem.

Today I decide to try again to build dotnet core hoping that will be build successfully,
because passed maybe a year of the first release but I face again some problem which i cannot solve.

My current problem is [this](https://pastebin.com/ZSP4KU4E)

**Comment by hughbe** [comment]
:(

Basically the issue is compiling the native crypto code. Looks like a potentially missing include for an OpenSSL primtive:

```
/home/linus/tmp/yaourt-tmp-linus/aur-dotnet/src/corefx-1.1.1/src/Native/Unix/System.Security.Cryptography.Native/openssl.c:84:22: error: 
      incomplete definition of type 'struct x509_st'
    memcpy(pBuf, x509->sha1_hash, SHA_DIGEST_LENGTH);
                 ~~~~^
/usr/include/openssl/ossl_typ.h:119:16: note: forward declaration of
      'struct x509_st'
typedef struct x509_st X509;
```
Maybe archlinux has different files needed to include? Have you got `libcurl4-openssl-dev` installed on your machine? There are instructions here: https://github.com/dotnet/corefx/blob/master/Documentation/building/unix-instructions.md

**Comment by TimurZanagar** [comment]
Do you need help? Yes, really? Is it a good start with "guys you suck"? (I think without a s is better)

**Comment by herecydev** [comment]
I'm sure they'll get right on it buddy.

**Comment by hughbe** [comment]
Possibly related: https://github.com/openssl/openssl/issues/594 maybe

**Comment by orb77** [comment]
Thank you @TimurZanagar  this solve my problem

**Comment by orb77** [comment]
@hughbe if is related how to fix it ?

**Comment by hughbe** [comment]
What's your OpenSSL version? It looks like some things may have changed between OpenSSL versions.
> openssl version

**Comment by jakubfijalkowski** [comment]
Check out the thread on Arch/AUR forums - https://bbs.archlinux.org/viewtopic.php?id=225790 , This AUR package depends on `openssl` package and this means that it will get OpenSSL 1.1.0e, but AFAIK `corefx` requires OpenSSL 1.0. The maintainer of the AUR package will probably fix this in the coming days.

**Comment by TimurZanagar** [comment]
@orb77 I don't think you're Problem can be solved here. You need a therapist for this kind of problem. 

And the other issue. Just READ!

**Comment by Expecho** [comment]
Your attitude is horrible, can't understand why people are even helping you. Does it hurt being friendly?

**Comment by hughbe** [comment]
No point berating him on his attitude, it'll just lead to this issue getting locked. We've all been in situations where technology that we wish just worked stumps us and we get annoyed.

**Comment by TimurZanagar** [comment]
I'm with you, but this is definitely not a excuse for this kind of attitude.

**Comment by orb77** [comment]
Ok guys you are right about my attitude I change also the part of the content.
Now I'm hoping that we will be able to fix this problem.

**Comment by danmosemsft** [comment]
@bartonjs for openssl

**Comment by danmosemsft** [comment]
@orb77 by the way, you can attach big files to issues, no need to paste...

**Comment by orb77** [comment]
The version of my openssl is: 

> OpenSSL 1.1.0e  16 Feb 2017

I also install:
> libcurl-openssl-1.0 7.54.0-1 

Installing libcurl-openssl doesn't solve the problem at all.

**Comment by bartonjs** [comment]
No, .NET Core does not support Arch.  And no, .NET Core does not work on Arch out of the box. For one, Arch has moved to OpenSSL 1.1 and we haven't (and it's a massive breaking change) - #9855.

https://github.com/dotnet/corefx/issues/9855#issuecomment-298982251 is a comment by a fellow Arch user who is trying to get things working, which leaves a breadcrumb to https://bbs.archlinux.org/viewtopic.php?pid=1708479.

**Comment by karelz** [comment]
I linked 'Supported OS Versions' from main CoreFX page [here](https://github.com/dotnet/corefx/blob/master/README.md#net-core) and [here](https://github.com/dotnet/corefx/blob/master/README.md#build--test-status) to avoid future confusion.

I also submitted PR to clarify & track status of (some) unsupported OS work: https://github.com/dotnet/core/pull/616

**Comment by karelz** [comment]
Overall I wonder if we should resolve this issue as duplicate of #9855 - @bartonjs @orb77 thoughts? Is this issue tracking anything else unique?

**Comment by orb77** [comment]
@karelz When you are planing to fix this issue ?

**Comment by karelz** [comment]
@orb77 do you mean the OpenSSL 1.0 package for Arch Linux linked [above](https://github.com/dotnet/corefx/issues/19447#issuecomment-299712006)?
I would expect Arch community to drive that ...

Or did you mean something else?

**Comment by orb77** [comment]
No I mean are you planing to migrate OpenSSL 1.0 dependency  to 1.1 ?

**Comment by karelz** [comment]
It is in Future milestone - AFAIK we do not have immediate plans to support it (@bartonjs can correct me if it falls into one of his items in the long-term plan).
I think there are more impactful things to do in .NET Core Security area. We just started shaping long-term Security area plans couple of weeks ago ...

**Comment by bartonjs** [comment]
@karelz With the supported OS table updates you did I think we can just close this as a pointer to that.  Us not having support for OpenSSL 1.1 is one of the things making Arch not work, but there are other, ongoing limitations.  (Or we can call it a dupe, but since "resolve as duplicate" isn't a github feature, it doesn't really feel like we need to make the distinction)

**Comment by karelz** [comment]
Closing per info above
