### ISSUE TITLE
WinHttpException "The parameter is incorrect" on HttpRequest with EnableRewind  

### ISSUE THREAD

**Issue by PavelStefanov** [dotnet/corefx#19469]
Hi,

Environment: .NET Core runtime 1.1.1 on Windows 10
Case: I get HttpRequest then I want to send this to other api.

```
 public class Program
    {
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            host.Run();
        }
    }

    public class Startup
    {
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            app.Run(async (context) =>
            {
                context.Request.EnableRewind();

                var httpRequestMesage = new HttpRequestMessage(new HttpMethod(context.Request.Method), $"https://mysite.com");

                if (context.Request.ContentLength != null && context.Request.ContentLength > 0)
                {
                    httpRequestMesage.Content = new StreamContent(context.Request.Body);
                    httpRequestMesage.Content.Headers.ContentType = MediaTypeHeaderValue.Parse(context.Request.ContentType);
                }

                try
                {
                    using (var httpClient = new HttpClient())
                    {
                        var response = await httpClient.SendAsync(httpRequestMesage);
                    }
                }
                catch (Exception exception)
                {
                    throw exception;
                }

            });
        }
    }
```
Request example:
```
http://localhost:5000/ POST
Content-Type: application/json;charset=UTF-8

test
```

When I'm using EnableRewind I have the following exception:
```
"System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> 
System.IO.IOException: The write operation failed, see inner exception. ---> 
System.Net.Http.WinHttpException: The parameter is incorrect
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpContent.<CopyToAsyncCore>d__44.MoveNext()
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.<CopyToAsyncCore>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<InternalSendRequestBodyAsync>d__131.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RewindIssue.Startup.<>c.<<Configure>b__0_0>d.MoveNext() in c:\\Projects\\RewindIssue\\Program.cs:line 50"
```

**Comment by stephentoub** [comment]
What does `EnableRewind` do?  Presumably it's going to affect the `context.Request.Body` Stream, changing its position or content or something, potentially concurrently with WinHttpHandler trying to read from it, potentially changing state that WinHttpHandler is relying on, etc.?

**Comment by benaadams** [comment]
Changes the steam type for the Body https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http/Internal/BufferingHelper.cs#L41-L78

**Comment by stephentoub** [comment]
> Changes the steam type for the Body 

Presumably it does that so the stream body can be replayed from its buffer.  What causes that Stream's position to be reset back to an earlier state? And when?  @davidsh could confirm if this theory makes sense, but my guess is that the CopyToAsync in SendAsync is copying more than WinHttp expected due to the position of the body Stream getting reset back to an earlier position during the copy.  Is that possible?

**Comment by Tratcher** [comment]
Looks like Stream.Length is the problem: https://github.com/aspnet/HttpAbstractions/blob/87cd79d6fc54bb4abf07c1e380cd7a9498a78612/src/Microsoft.AspNetCore.WebUtilities/FileBufferingReadStream.cs#L151
The buffering stream doesn't know the whole length until it completes buffering, so it returns the current length of the buffer. HttpContent uses Stream.Length for ContentLength if you haven't set one.
https://github.com/dotnet/corefx/blob/6f07f7ebdd0c1be3b2278a98d34b58d732b89af2/src/System.Net.Http/src/System/Net/Http/Headers/HttpContentHeaders.cs#L82-L85
https://github.com/dotnet/corefx/blob/6f07f7ebdd0c1be3b2278a98d34b58d732b89af2/src/System.Net.Http/src/System/Net/Http/StreamContent.cs#L71

Workarounds:

Complete the buffering first:
```
context.Request.EnableRewind();
await context.Request.Body.DrainAsync(CancellationToken.None);
context.Request.Body.Seek(0, System.IO.SeekOrigin.Begin);
```
or set ContentLength:
```
httpRequestMesage.Content.Headers.ContentLength = context.Request.ContentLength;
```
or set TransferEncodingChunked:
```
httpRequestMesage.Headers.TransferEncodingChunked = true;
```

**Comment by stephentoub** [comment]
> The buffering stream doesn't know the whole length until it completes buffering, so it returns the current length of the buffer.

Should it instead use _inner.Length if _inner is seekable?

**Comment by Tratcher** [comment]
It already knows inner is not seekable:
https://github.com/aspnet/HttpAbstractions/blob/6ffac0c722b1d71837d438f22da58aefddd6caac/src/Microsoft.AspNetCore.Http/Internal/BufferingHelper.cs#L49

**Comment by stephentoub** [comment]
Ah.  In that case it seems wrong that FileBufferingReadStream returns true from CanSeek before it's been fully buffered; code like this will query CanSeek to determine whether it can use and trust the Length, but in this case the Length is wrong until it's been fully buffered.

**Comment by Tratcher** [comment]
Yeah, this stream is pushing the capabilities of what the Stream contract can describe. It can Seek, but only over the buffered data, and it doesn't know how long the final data will be. There's also nothing in the contract about weather the values of CanSeek or Length can change during the lifetime of an instance. MemoryStream's Length can change as you write to it, and so can FileStream's. StreamContent assumes a fixed length.

You don't want to disable CanSeek because then you'd get double buffering if someone called EnableRewind again.

**Comment by stephentoub** [comment]
> You don't want to disable CanSeek because then you'd get double buffering if someone called EnableRewind again.

Why not just make the condition also based on whether the stream is already a FileBufferingReadStream?

**Comment by Tratcher** [comment]
That assumes it doesn't get wrapped for any other reason.

Besides, disabling CanSeek would also prevent people from seeking over the buffered data.

**Comment by stephentoub** [comment]
> That assumes it doesn't get wrapped for any other reason.

Such as?  In what situation would you want to double-wrap so as to get double-buffering?

> Besides, disabling CanSeek would also prevent people from seeking over the buffered data.

That's fair, though you'd know better than I how desirable it would be to seek on the buffered data before it was fully buffered; seems pretty niche, but maybe not.

Anyway, doesn't seem like there's any code change that should be made here to HttpClient.

**Comment by Tratcher** [comment]
Except improvements to the error messages...

**Comment by davidsh** [comment]
>Except improvements to the error messages...

The error message is coming directly from WinHTTP error strings that we grab. In general, when we get an error back from WinHTTP, we will grab the error message string from WinHTTP.dll and use that in our exception message.

I agree this scenario should be better in terms of error strings...perhaps we can detect this scenario and create a better outer exception message.

**Comment by oliverjanik** [comment]
Why was this closed? this is an API design fail. 

The use-case is to copy incoming bytes upstream. What is the most straightforward way to do this?
