### ISSUE TITLE
System.ComponentModel.EnumConverter.GetStandardValues() throw InvalidCastException

### ISSUE THREAD

**Issue by enjoycode** [dotnet/corefx#19461]
in source code: 
`IComparer comparer = Comparer;
if (comparer != null)
{
        objValues.Sort((IComparer<object>) comparer);
}`
when "comparer" is a InvariantComparer, it can't cast to IComparer<<object>>, implements on .netstandard 1.0 & 1.1 are correct, because objValues are ArrayList, and use objValues.Sort(comparer).

**Comment by karelz** [comment]
Can you please share full code passing the `InvariantComparer`?
Did you hit the bug on .NET Core 1.0 or 1.1? Does it work correctly on "Desktop" .NET Framework?

**Comment by enjoycode** [comment]
1. I don't pass InvariantComparer, it's default by EnumConverter: `protected virtual IComparer Comparer => InvariantComparer.Default;`
2. .net core 1.0 and 1.1 works fine
3. Desktop .net works fine.

**Comment by karelz** [comment]
So what doesn't work then? .NET Core 2.0?

**Comment by enjoycode** [comment]
I wrote a unit test: 
`using System;
using System.ComponentModel;
using Xunit;

namespace AppBox.UnitTests
{
    public class EnumConverterTest
    {

        [Fact]
        public void GetStandardValuesTest()
        {
            var converter = new EnumConverter(typeof(Gender));
            var collection = converter.GetStandardValues();
        }

    }

    public enum Gender
    {
        Male,
        Female
    }

}`

run it throw exception:

[xUnit.net 00:00:00.7042960]     AppBox.UnitTests.EnumConverterTest.GetStandardValuesTest [FAIL]
[xUnit.net 00:00:00.7062080]       System.InvalidCastException : Unable to cast object of type 'System.InvariantComparer' to type 'System.Collections.Generic.IComparer`1[System.Object]'.
[xUnit.net 00:00:00.7078520]       Stack Trace:
[xUnit.net 00:00:00.7095540]            at System.ComponentModel.EnumConverter.GetStandardValues(ITypeDescriptorContext context)
[xUnit.net 00:00:00.7096800]            at System.ComponentModel.TypeConverter.GetStandardValues()
[xUnit.net 00:00:00.7097430]            at AppBox.UnitTests.EnumConverterTest.GetStandardValuesTest()
[xUnit.net 00:00:00.7298040]   Finished:    AppBox.UnitTests
Test failed

**Comment by karelz** [comment]
OK, thanks for report - @AlexGhiondea @safern can you please check it out? This looks like breaking change per info above ...
