### ISSUE TITLE
CoreFX Jenkins badges reflect last completed build results: need badges that show status of last build of any kind

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#19483]
Eg for Win7 right now the badge shows last completed results: `https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_release/lastCompletedBuild/testReport/`. That's handy for seeing results because it ignores in progress builds.

However if the build does not complete (possibly for some days) this does not show up.

We should probably add badges showing build status, not just last completed.

**Comment by ViktorHofer** [comment]
As with Azure DevOps this will change I'm closing this in favor of https://github.com/dotnet/corefx/issues/30558
