### ISSUE TITLE
System.Diagnostics.Tests.ProcessTests flaky tests

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#19499]
I've seen the following tests failed in two different PRs today:

System.Diagnostics.Tests.ProcessTests.TestProcessOnRemoteMachineWindows
System.Diagnostics.Tests.ProcessTests.GetProcessesByName_RemoteMachineNameWindows_ReturnsExpected(machineName: \"3556bb7131de4d6ab3e7ada117d07ac9\")
System.Diagnostics.Tests.ProcessTests.GetProcessesByName_RemoteMachineNameWindows_ReturnsExpected(machineName: \"\\\\128636e3cc3e42888137ee11e9c4d4ad\")

They fail with error:
```
System.InvalidOperationException : Couldn't connect to remote machine.\r\n---- System.InvalidOperationException : Process performance counter is disabled, so the requested operation cannot be performed.
```

Latest CI leg where they failed: https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/7609/

Should we maybe fix them to retry if it wasn't able to connect to remote machine? 

cc: @Priya91 @stephentoub

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/issues/19474

**Comment by safern** [comment]
Thanks for pointing out.
