### ISSUE TITLE
macOS: cannot add self-signed cert to X509Store CurrentUser\My

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#19508]
**Repro**
1. Download latest build of .NET Core 2.0.0 preview2 https://github.com/dotnet/cli#installers-and-binaries
1. Create a self-signed cert
   1. `openssl genrsa 4096 > private.pem`
   1. `openssl req -x509 -new -key private.pem -out public.pem`
   1. `openssl pkcs12 -export -in public.pem -inkey private.pem -out mycert.pfx`
2. `dotnet new console` and edit code to match:

```c#
using System;
using System.Security.Cryptography.X509Certificates;

namespace addcert
{
    class Program
    {
        static void Main(string[] args)
        {
            var cert = new X509Certificate2("mycert.pfx", "password");
            var store = new X509Store(StoreName.My, StoreLocation.CurrentUser);
            try
            {
                store.Open(OpenFlags.ReadWrite);
                // this line throws
                store.Add(cert);
            }
            finally
            {
                store.Close();
            }
        }
    }
}
```
3. `dotnet run`

**Error**
```
Unhandled Exception: Interop+AppleCrypto+AppleCommonCryptoCryptographicException: The contents of this
item cannot be retrieved.
   at Interop.AppleCrypto.X509StoreAddCertificate(SafeKeychainItemHandle certOrIdentity, SafeKeychainHa
ndle keychain)
   at Internal.Cryptography.Pal.StorePal.AppleKeychainStore.Add(ICertificatePal cert)
   at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate)
   at addcert.Program.Main(String[] args)
```

**Details:**
Microsoft.NETCore.App/2.0.0-preview2-002093-00
macOS 10.12.4

Available Keychains:
![image](https://cloud.githubusercontent.com/assets/2696087/25830803/5f4ef3aa-3414-11e7-8d2a-90731f6f7c08.png)

Adding the .pfx file to 'login' via the Keychain Access utility works just fine, as does `security import mycert.pfx -k ~/Library/Keychains`

**Comment by karelz** [comment]
cc @bartonjs

**Comment by bartonjs** [comment]
This is an unfortunate aspect of how macOS is different.

Every loaded certificate+private key has to belong to a keychain, so we make one up for you.  You didn't ask for the key to be exportable, so when it goes to copy it to a different keychain it gets a non-exportability error.

On Windows what you're wanting to do would have required you use the `X509KeyStorageFlags.PersistKeySet` flag, and if you do that on macOS we actually import it straight into the default keychain (aka CU\My), saving you the step of copying it into a store.

(On Windows the key storage bits are about the key, and the thing in the cert store is a pointer to the key (not the actual key).  On macOS the exportability bit is also on the key, but the key and the certificate co-reside.)

```C#
// Make your code work
var cert = new X509Certificate2("mycert.pfx", "password", X509KeyStorageFlags.Exportable);
[rest of your code here]
// Or, for it to have worked on Windows:
var cert = new X509Certificate2("mycert.pfx", "password", X509KeyStorageFlags.PersistKeySet);
[rest of your code is optional, it has already done that part]
```

**Comment by natemcmaster** [comment]
Thanks for clarifying what's going on here. Would it be possible to detect this situation and improve the error message? The error message looks like a native message from macOS, but it's unfortunately generic. The [search results](https://www.google.com/search?q=The+contents+of+this+item+cannot+be+retrieved.) for this message are unlikely to help a user find this solution.

**Comment by bartonjs** [comment]
@natemcmaster Right now I'm trying to stay out of the business of reinterpreting system errors.  By occurrence `errSecDataNotAvailable` seems mostly to be about invalid state (e.g. `item->data` being `nullptr` long past the part where it shouldn't have been); but the "oh, the exportable bit isn't set? then report an error" check happens to also use it (in this case, it's not the data is missing, it's that the data is forbidden... but I guess English-y those are both "availablity" problems).

Feedback like this is good, though.  At some point I'll decide that the support cost of debugging system error messages exceeds the maintenance cost of wrapped/reinterpreted exceptions, and then we'll shift gears.

**Comment by natemcmaster** [comment]
> Right now I'm trying to stay out of the business of reinterpreting system errors.

Sounds reasonable. At the very least, this issue will pop up in search results now :).

By the way, the repro code above worked in .NET Core 1.x, but fails when moving to 2.0. Are there other significant ways X509Store has changed that might break 1.x code?

**Comment by bartonjs** [comment]
Almost everything in System.Security.Cryptography.X509Certificates was a complete rewrite on macOS for 2.0, part of getting rid of the OpenSSL dependency.  I happen to have just put out a doc PR: https://github.com/dotnet/corefx/pull/19536.  Anything that is different between macOS and Linux pretty much means "changed because we switched from OpenSSL to Security.framework".
