### ISSUE TITLE
Several new HttpListener tests are failing in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#19526]
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_debug/40/consoleText
```
System.Net.Tests.HttpListenerPrefixCollectionTests.Add_InvalidPrefixNotStarted_ThrowsHttpListenerExceptionOnStart(uriPrefix: \"http://microsoft.com/\") [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.Net.HttpListenerException)
        Actual:   (No exception was thrown)
        Stack Trace:
           D:\j\workspace\outerloop_net---dbe8fad8\src\System.Net.HttpListener\tests\HttpListenerPrefixCollectionTests.cs(264,0): at System.Net.Tests.HttpListenerPrefixCollectionTests.Add_InvalidPrefixNotStarted_ThrowsHttpListenerExceptionOnStart(String uriPrefix)
```
cc: @hughbe

**Comment by hughbe** [comment]
Oh dammit. I think the test was meant to make sure that we fail if we can't access (security reasons) a remote domain. 

I chose this because I assumed no one would be able to listen to http://microsoft.com/ odd

If this repros consistently could you disable it as I am AFK and won't be able to investigate until the next day

**Comment by stephentoub** [comment]
Disabling in #19530

**Comment by davidsh** [comment]
>Oh dammit. I think the test was meant to make sure that we fail if we can't access (security reasons) a remote domain. I chose this because I assumed no one would be able to listen to http://microsoft.com/ odd

If we need to create a remote domain that is unique, we should use `new Guid()` etc. so that the DNS name is unique.

**Comment by stephentoub** [comment]
Also:
Add_InvalidPrefixNotStarted_ThrowsHttpListenerExceptionOnStart
Remove_PrefixExistsStarted_ReturnsTrue

**Comment by safern** [comment]
This fails in Desktop as well.

**Comment by hughbe** [comment]
I don't really understand the failure. I assume it's because the CI machines can somehow access microsoft.com due to permissions - maybe the same org, I don't understand.
But still, does that mean that I just successfully associated an HttpListener with microsoft.com?
