### ISSUE TITLE
System.Reflection.Metadata 1.4.2 Package references wrong System.Collection.Immutable assembly version

### ISSUE THREAD

**Issue by T0pp3r** [dotnet/corefx#19548]
Hi

The System.Reflection.Metadata 1.4.2(NuGet Package) claims to reference System.Collections.Immutable >= 1.3.1. The System.Collection.Immutable 1.3.1 (NuGet Package) contains the assembly version 1.2.1.0 but the System.Reflection.Metadata.dll from 1.4.2 references 1.2.0.0.

This leads to an really unfortunate problem with Roslyn which needs both packages, but uses the correct System.Collections.Immutable.dll(1.2.1.0) and my program crashes because it can't find the System.Collections.Immutable.dll(1.2.0.0) which is required by System.Reflection.Metadata.dll.

Please help :)

**Comment by 0xd4d** [comment]
If it's a .NET Framework program, a workaround is to add an app.config file:

```XML
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<runtime>
		<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
			<dependentAssembly>
				<assemblyIdentity name="System.Collections.Immutable" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
				<bindingRedirect oldVersion="1.1.0.0-1.2.1.0" newVersion="1.2.1.0" />
			</dependentAssembly>
...
```

**Comment by karelz** [comment]
@tmat @nguerrera anything concerning for 2.0?

**Comment by tmat** [comment]
AFAIK 2.0 packages do not have this problem anymore.

**Comment by karelz** [comment]
@T0pp3r can you please try it with latest 2.0 build? https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md

**Comment by T0pp3r** [comment]
Hi, i forgot to mention it is a standard .NetFramework program, so no .NetCore. I don't know if i'm even right here because my problem relates just to the System.Reflection.Metadata (NeGet Package).

@0xd4d This redirection is added from the Nuget Package but i don't know why it does not work. Probably because it is an indirect reference?

@tmat I don't use the corefx, so a nightly would not help my here, even if i just extracted the needed dll i would still have the requirements of the Roslyn packages. Which would mean i have to make sure to overwrite the dll from the nuget package after the build with the one from the nightly. 

Just to clarify i use the System.Reflection.Metadata (NeGet Package), which gets automatically installed with the Roslyn (2.1.0) packages.

**Comment by tmat** [comment]
@T0pp3r I see. Yes, until Roslyn upgrades to netstandard 2.0 you'll need to use a binding redirect.

**Comment by T0pp3r** [comment]
Ok, thanks i will try to see why the redirecting is not working.

**Comment by dougbu** [comment]
@karelz and @tmat it appears the problem no longer exists in the 2.0.0 preview1 packages -- [system.collections.immutable.1.4.0-preview1-25305-02](https://www.nuget.org/packages/System.Collections.Immutable/1.4.0-preview1-25305-02) and [system.reflection.metadata.1.5.0-preview1-25305-02](https://www.nuget.org/packages/System.Reflection.Metadata/1.5.0-preview1-25305-02). But, it's not clear from this issue (closed without any changes but in the 2.0.0 milestone) whether that state will be maintained.

Please confirm the current .nuspec / .dll consistency will remain in 2.0.0 RTM and that needing a Microsoft/msbuild#1309 fix for these dependencies is a point-in-time issue.

**Comment by tmat** [comment]
@weshaggard @terrajobst To answer the versioning question.

**Comment by karelz** [comment]
@tmat why did you originally close the issue? Can you please comment on that first? Was there a PR? Was it invalid? Was it not repro?

**Comment by tmat** [comment]
@karelz The current versioning is by design. Binding redirects are required pre-netstandard 2.0. The versioning changed in netstandard 2.0 and binding redirects are not required anymore. I believe @dougbu is asking if the plan is to keep that versioning scheme or not.

**Comment by jnm2** [comment]
I have this exact issue, but the instructions to add an app.config file confuses me because what I'm building is an MSBuild task dll. Do .configs get loaded for every dll? Thought it was an .exe thing.

**Comment by tmat** [comment]
@jnm2 Unfortunately, MSBuild tasks do not currently support binding redirects, see https://github.com/Microsoft/msbuild/issues/1309.
