### ISSUE TITLE
Desktop: "System.Net.Tests.HttpListenerPrefixCollectionTests" failed

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#19543]
System.Net.Tests.HttpListenerPrefixCollectionTests.Add_InvalidPrefixAlreadyStarted_ThrowsHttpListenerExceptionOnAdd

Failed with error: 
```
Assert.Throws() Failure\r\nExpected: typeof(System.Net.HttpListenerException)\r\nActual: (No exception was thrown)
StackTrace:
at System.Net.Tests.HttpListenerPrefixCollectionTests.Add_InvalidPrefixAlreadyStarted_ThrowsHttpListenerExceptionOnAdd(String uriPrefix) in D:\j\workspace\outerloop_net---71bc9469\src\System.Net.HttpListener\tests\HttpListenerPrefixCollectionTests.cs:line 276
```

This failed on both Jenkins and Helix.

#### Jenkins
https://ci.dot.net/job/dotnet_corefx/job/master/job/portablelinux_debug_prtest/4880/testReport/junit/System.Net.Tests/HttpListenerPrefixCollectionTests/Remove_PrefixExistsStarted_ReturnsTrue/

#### Helix
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170509.02/workItem/System.Net.HttpListener.Tests/analysis/xunit/System.Net.Tests.HttpListenerPrefixCollectionTests~2FAdd_InvalidPrefixAlreadyStarted_ThrowsHttpListenerExceptionOnAdd(uriPrefix:%20%5C%22http:~2F~2Fmicrosoft.com~2F%5C%22)

cc: @davidsh

**Comment by safern** [comment]
I will disable the test on desktop.

**Comment by safern** [comment]
System.Net.Tests.HttpListenerPrefixCollectionTests/Add_InvalidPrefixNotStarted_ThrowsHttpListenerExceptionOnStart

Also failed on Helix:

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170509.02/workItem/System.Net.HttpListener.Tests/analysis/xunit/System.Net.Tests.HttpListenerPrefixCollectionTests~2FAdd_InvalidPrefixNotStarted_ThrowsHttpListenerExceptionOnStart(uriPrefix:%20%5C%22http:~2F~2Fmicrosoft.com~2F%5C%22)

**Comment by davidsh** [comment]
cc: @stephentoub @hughbe 

This is due to @hughbe latest PR changes in HttpLIstener.

**Comment by stephentoub** [comment]
I've already disabled this one (and a few others).
https://github.com/dotnet/corefx/blob/c4ddfc3b9be6b6afa4b4168582507c1aca2b2a2e/src/System.Net.HttpListener/tests/HttpListenerPrefixCollectionTests.cs#L268

**Comment by safern** [comment]
Thanks @stephentoub

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/issues/19526
