### ISSUE TITLE
DBNull is duplicated between System.Data.Common and CoreLib

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#19554]
System.DBNull exists as public in both System.Data.Common.dll and System.Private.CoreLib.dll in netcoreapp2.0.  This can cause type exchange issues as well as compile errors for runtime compilation.

I believe System.Data.Common.dll should type-forward this type.

When doing this, please remove the exception:
https://github.com/dotnet/corefx/pull/19502/files#diff-74b55c30c79e12e99b3ceb25668cc292R17

/cc @weshaggard

**Comment by stephentoub** [comment]
@ericstj, where do you see System.Data.Common including DBNull?

**Comment by ericstj** [comment]
Let me give more details.

The process for reproducing the error is (after removing the supression):
build -allConfigurations
msbuild pkg\test\testPackages.proj /m /fl /v:m /p:TestPackages=System.Data.Common

I'm doing this right now and will share the exact case that's identified.

**Comment by danmosemsft** [comment]
This needs an owner to get it fixed today :) Is that you @ericstj  ?

**Comment by ericstj** [comment]
Confirmed, this was due to an old shared framework.  I'm going to update the CLI being used to the shipping one from preview1 and I'll remove the suppression.
