### ISSUE TITLE
Overlapped types are duplicated between Overlapped and corelib

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#19553]
IOCompletionCallback, NativeOverlapped, Overlapped, PreAllocatedOverlapped, and ThreadPoolBoundHandle are duplicated between Overalapped and System.Private.CoreLib.

I believe we should typeforward these instead.

When doing this, please remove the exceptions:
https://github.com/dotnet/corefx/pull/19502/files#diff-74b55c30c79e12e99b3ceb25668cc292R11

/cc @weshaggard

**Comment by stephentoub** [comment]
@ericstj, as far as I can tell those types are no longer in System.Threading.Overlapped.  Where are you looking?

**Comment by stephentoub** [comment]
I see these are defined in the ref for System.Threading.Overlapped (they're not in the src).  You're saying the ref needs to reference System.Private.CoreLib and type forward to that?

**Comment by ericstj** [comment]
Nope, they're are showing up in the src.  Let me give you the exact case where the duplication happens.

**Comment by ericstj** [comment]
I see.  It's happening for the PlatformNotSupported assembly on Unix:
https://github.com/dotnet/corefx/blob/master/src/System.Threading.Overlapped/src/System.Threading.Overlapped.csproj#L9

I guess if Corelib has those types we can just forward them rather than build a PNS.  That's probably better anyways since these aren't necessarily not supported on unix, just not particularly useful on Unix.

**Comment by stephentoub** [comment]
> I guess if Corelib has those types we can just forward them rather than build a PNS.

I agree.  I think it makes sense as a general rule that we should actually implement types in the same assembly regardless of platform, so if we did want PNSEs thrown, it would be from the implementation in System.Private.CoreLib rather than manufacturing an implementation in CoreFx (but only for Unix).
