### ISSUE TITLE
Make the Initilize BuildTools during build.cmd less intensive.

### ISSUE THREAD

**Issue by dhoehna** [dotnet/corefx#19560]
When I am running build.cmd my computer will lag during the "Initilizing BuildTools" step.  This lag has happened on two of my computers so far.  The lag, specifically, slows down Visual Studio and firefox.  The slowdown in firefox is evident because youtube will lag and text input is delayed.

I don't know if this is a problem with other people but this lag is infuriating when I'm trying to use my computer for other activities while building corefx.

**Comment by danmosemsft** [comment]
@dhoehna next time this happens could you check your network connection and see whether it's saturated?

**Comment by dhoehna** [comment]
@danmosemsft I've never had to do that before.  Is that in Windows Task Manager->Networking?  What should I see if the network is saturated?

Also, I'll try tomorrow by removing corefx from my computer and trying to build from scratch.

**Comment by danmosemsft** [comment]
@dhoehna Yeah Task Manager>Performance, look at Etnernet or Wifi graph, if it's showing a value similar to your max of your wifi or cable connection, then we're saturating the network. Probably we wouldn't want to change doing that since that's what most people would want...

**Comment by dhoehna** [comment]
@danmosemsft I am on windows 7.  My performance tab does not have an ethernet or a wifi graph.

**Comment by weshaggard** [comment]
It would also be nice to confirm that it isn't IO bound. We recently fixed https://github.com/dotnet/corefx/pull/19109 which was traversing the entire disk under the repo root. Do you have that change in your local repo?

**Comment by dhoehna** [comment]
@weshaggard I cloned the repo yesterday.  I am deleting my corefx git repo on my computer and doing everything from scratch.  Should I look at IO usage as well?

**Comment by weshaggard** [comment]
Yes it would be good to figure out what is hammering your system. Is it networking, IO, CPU, etc. Also how long does this usually last for?

**Comment by dhoehna** [comment]
So, I re-ran build.cmd.  I got the message "Tools are already installed"   and no lag happened.  What do I have to remove so that won't happen?  @danmosemsft and @weshaggard

**Comment by weshaggard** [comment]
To get back into a clean state run `clean.cmd --all` and then when you run build.cmd it will initialize the tools again. You can also by-pass the build.cmd and just call init-tools.cmd.

**Comment by dhoehna** [comment]
Really?  Cool.  Thank you.

**Comment by wtgodbe** [comment]
Closing this as a dead issue, @dhoehna please re-open if it's still causing you problems.
