### ISSUE TITLE
Ping API calls are failing in appcontainer with access denied

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#19583]
They don't fail that way in ILC

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20170510.01/workItem/System.Net.Ping.Functional.Tests

Check we have the internet capability. Whatever manifest we use for our test app, it should enable all capabilities.

@AlexGhiondea where is it?
cc @ViktorHofer

**Comment by AlexGhiondea** [comment]
The app is in BuildTools. 

https://github.com/dotnet/buildtools/blob/master/src/xunit.runner.uap/Package.appxmanifest

I can help deploy the updated app

**Comment by ViktorHofer** [comment]
The manifest contains all possible Internet capabilities...

**Comment by ViktorHofer** [comment]
If we are pinging to local network hosts we probably need this one too:
`privateNetworkClientServer`

https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations

**Comment by stephentoub** [comment]
> If we are pinging to local network hosts we probably need this one too: privateNetworkClientServer

That's already in the list in your previous comment...?

**Comment by ViktorHofer** [comment]
You are right. I will look into it when I'm in office

**Comment by davidsh** [comment]
This is probably a problem with pinging localhost.  That is never allowed in app container

**Comment by davidsh** [comment]
So we'll need to figure out a different way to test this in UWP scenarios

**Comment by ViktorHofer** [comment]
We could use the EchoServers for that. There are tests in it which ping against a host and some ping against an IP Address. Is the EchoServers IP Address static?

**Comment by davidsh** [comment]
>Is the EchoServers IP Address static?

That is not something we should rely on.

The alternative for using loopback adapter in UWP scenarios is to use the checkisolation tool:
http://stackoverflow.com/questions/33259763/uwp-enable-local-network-loopback

But that requires changes to the local machine.

Fixing this is a test design topic that we are still evaluating alternatives.

**Comment by davidsh** [comment]
@danmosemsft @stephentoub @CIPop @karelz 

We have a lot of test collateral in CoreFx that lies on being able to talk to loopback adapter (localhost).  I think we should modify the CI machines with the 'checkisolation' tool to allow this communication.  That would then allow us to keep the tests the same and have them work in CI.

Then, it would just be a requirement for devs working on local machines to enable loopback via using the 'checkisolation' tool against the various Xunit* test runners/apps.

**Comment by ViktorHofer** [comment]
We could automate it, so that after registering the appx package on the machine it will run the checkisolation tool.

cc @joperezr

**Comment by CIPop** [comment]
I believe that the tool needs to be ran from an elevated prompt so this is a bit problematic as we don't have anything running elevated at the moment.

If the package family name doesn't change, we can add this as a documented prerequisite step. We could also change the tests to first verify if loopback networking is allowed (via the `Capability.*.cs` model).

> To add a Windows Store app to the list of apps that are exempt from the loopback firewall, run checknetisolation loopbackexempt -d -n=<package family name> from an elevated command prompt.

(https://msdn.microsoft.com/en-us/library/windows/apps/dn640582.aspx)

**Comment by DavidGoll** [comment]
ICMP APIs should be available for UWP apps now. Determine whether these will solve the problem.

**Comment by CIPop** [comment]
@DavidGoll @Diego-Perez-Botero I believe we've pinned this down to ICMP API bugs in the OS: some of the Win32 APIs are not properly working in an AppContainer. 
This explained why we're not seeing the bug in UAPAOT - since it's not running in an app-container (i.e. #18760).

@Diego-Perez-Botero are you going to disable the tests against this issue (right now they are disabled against the epic).

**Comment by Diego-Perez-Botero** [comment]
Correct - IcmpCreateFile is failing with **E_ACCESSDENIED** when running inside an AppContainer. This is an OS issue and there's no workaround; we'll need to wait for the OS folks to fix it.

I'll go ahead and disable the tests against this issue.

**Comment by karelz** [comment]
Does it impact the product, or only tests? (it is marked as test enhancement)

@Diego-Perez-Botero did you start the discussion with OS API owners to address it in RS3? Do you have a bug #?

**Comment by davidsh** [comment]
It is a product issue.  We are working with the Windows team to get it fixed.  It is an OS bug.

**Comment by karelz** [comment]
Switching to bug in that case. What is the impact of the bug? How many apps / APIs will be broken?

**Comment by CIPop** [comment]
@karelz /cc @Diego-Perez-Botero @DavidGoll The latest is that Ping will not work on UWP in this OS release.

This issue is not tracking code changes to:
1. Throw PNSE with the correct message
2. Document this for UWP

**Comment by DavidGoll** [comment]
> This issue is *not* tracking code changes to

I assume that was supposed to be "now".

Ping is used by 0.6% of apps.

**Comment by Diego-Perez-Botero** [comment]
I have updated the [ApiCompat page](https://github.com/dotnet/corefx/wiki/ApiCompat) with this UWP limitation and have sent out a PR to throw PNSE in UWP (#22338).

**Comment by Diego-Perez-Botero** [comment]
Re-opening and leaving it active for _Future_. All relevant tests are already marked as **ActiveIssue** with this issue's #.

**Comment by Jiayili1** [comment]
failed again: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170821.01/workItem/System.Net.Ping.Functional.Tests

**Comment by Jiayili1** [comment]
Following test failed again, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170908.01/workItem/System.Net.Ping.Functional.Tests/analysis/xunit/System.Net.NetworkInformation.Tests.PingTest~2FSendPings_ReuseInstance_Hostname

The test `System.Net.NetworkInformation.Tests.PingTest/SendPings_ReuseInstance_Hostname` has failed.

System.Net.NetworkInformation.PingException : An exception occurred during a Ping request.
    ---- System.Net.NetworkInformation.PingException : An exception occurred during a Ping request.

        Stack Trace:

           at System.Net.NetworkInformation.Ping.<GetAddressAndSendAsync>d__48.MoveNext() in /Users/buildagent/agent/_work/30/s/corefx/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.cs:line 364
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Net.NetworkInformation.Tests.PingTest.<SendPings_ReuseInstance_Hostname>d__15.MoveNext() in /Users/buildagent/agent/_work/30/s/corefx/src/System.Net.Ping/tests/FunctionalTests/PingTest.cs:line 349
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    ----- Inner Stack Trace -----
       at System.Net.NetworkInformation.Ping.<SendWithPingUtility>d__60.MoveNext() in /Users/buildagent/agent/_work/30/s/corefx/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.Unix.cs:line 210
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Net.NetworkInformation.Ping.<SendPingAsyncCore>d__58.MoveNext() in /Users/buildagent/agent/_work/30/s/corefx/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.Unix.cs:line 31
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Net.NetworkInformation.Ping.<GetAddressAndSendAsync>d__48.MoveNext() in /Users/buildagent/agent/_work/30/s/corefx/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.cs:line 353
Build : Master - 20170908.01 (Core Tests)
Failing configurations:
- OSX.1012.Amd64-x64
  - Release

**Comment by Diego-Perez-Botero** [comment]
@Jiayili1 The two test failures that you've referenced are for OSX runs. As such, they are completely unrelated to this active issue (#19583), which is a Windows-specific problem (IcmpCreateFile is failing with E_ACCESSDENIED when running inside an AppContainer).

Please open a separate issue to track the OSX test failures.

Thanks!

**Comment by Jiayili1** [comment]
Thanks@Diego-Perez-Botero , I will create a separate issue for it.

**Comment by karelz** [comment]
Next steps: We should disable the tests permanently. It will not be supported on UWP. No need to track it via this bug.

**Comment by davidsh** [comment]
I will change any ActiveIssue to SkipOnTargetFramework for this issue as part of my other UAP cleanup work.
