### ISSUE TITLE
System.Net.Requests test hanging sometimes on desktop

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#19580]
This is not all the time but they are hanging on some PRs and builds. Here is the console log of a failure:

https://ci.dot.net/job/dotnet_corefx/job/master/job/netfx_windows_nt_release_prtest/12/consoleFull#4967889112d31e50d-1517-49fc-92b3-2ca637122019

cc: @davidsh

**Comment by davidsh** [comment]
cc: @stephentoub 

@ViktorHofer Can you please investigate this?  Your PRs were the last ones to make major additions/changes to System.Net.Requests which include HttpWebRequest etc.

**Comment by davidsh** [comment]
cc: @karelz

**Comment by safern** [comment]
another hit: https://ci.dot.net/job/dotnet_corefx/job/master/job/netfx_windows_nt_release_prtest/10/consoleFull#10606384068101fac1-935e-4556-95f9-7a0e25ca0b52

**Comment by ViktorHofer** [comment]
looking at it right now

**Comment by safern** [comment]
Thabjs @ViktorHofer you might need to run them in a loop because they don't hang always

**Comment by ViktorHofer** [comment]
It looks like it has to do with the parallelization which we enabled today...

**Comment by karelz** [comment]
What kind of parallelization was enabled today? Why so close to ZBB? Is it possible to revert the change / disable it for now?

**Comment by ViktorHofer** [comment]
It was required to run Desktop tests on Helix as we had timeouts when they ran one after another. We already have a fix in place. As this is just about test reliability (so basically hardening networking tests --> making them more reliable with LoopbackServer and Outerloop attributes) it was required before ZBB

**Comment by karelz** [comment]
OK, thanks for explanation. If we have fix in place, I am ok with it. Thanks!

**Comment by safern** [comment]
#19584 @karelz it was something that needed to be fixed before ZBB in order to get CI desktop legs
