### ISSUE TITLE
System.Exception is not Serializable on UWP

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#19585]
We should mark the [`System.Exception`](https://github.com/dotnet/corert/blob/26413145abcbdd49468db230a6f29784494f6f46/src/Runtime.Base/src/System/Exception.cs#L9) on UWP with [Serializable]. This blocks serialization of exception types on UWP. And `Exception.GetObjectData` is throwing `NotImplementedException`.

**Comment by morganbr** [comment]
That's part of the plan for #19119

**Comment by AtsushiKan** [comment]
Adding ActiveIssue to System.Net.Mail.Functional.Tests
-method System.Net.Mail.Tests.SmtpExceptionTest.TestConstructorThrowsNull because of this.

**Comment by danmosemsft** [comment]
@morganbr maybe this is done already in which case @shmao or you should remove the ActiveIssue for this one and close it.

**Comment by shmao** [comment]
@danmosemsft this is not done yet. [`System.Exception`](https://github.com/dotnet/corert/blob/master/src/Runtime.Base/src/System/Exception.cs) is still not marked with `[Serializable]`.

**Comment by shmao** [comment]
@danmosemsft I thought the Exception used by UWP is from corert, not coreclr, no?

**Comment by morganbr** [comment]
Exception is marked Serializable, but GetObjectData does still throw NotImplementedException.

**Comment by morganbr** [comment]
For reference, the correct file is https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/Exception.cs

**Comment by tijoytom** [comment]
@shmao Do you need GetObjectData() too  or are you good with just Serializable attribute?

**Comment by shmao** [comment]
GetObjectData is required.

**Comment by morganbr** [comment]
This still isn't implemented.

**Comment by shmao** [comment]
@DnlHarvey any updates on this issue?

**Comment by DnlHarvey** [comment]
I have a code review in progress

**Comment by DnlHarvey** [comment]
Fixed with https://github.com/dotnet/corefx/pull/22162
