### ISSUE TITLE
Interfaces for Future APIs

### ISSUE THREAD

**Issue by reader-man** [dotnet/corefx#19592]
Hi,
Thanks for the great product, and specially the coming v2.0.

It would great to have in v2.0 interfaces for most of what is coming in v3, v4, v5, v6 of .net core.

For example all the generic collections, ot the IClonable or any other general utility apis, that you don't have time to implement in the current version i.e. v2.0.

As this will help current nuget/plugin developers to code their classes to implement those interfaces, and weather you (.net team) or others implement them, its just a matter of injecting the implementation, instead of re-coding a lot of the project links/coupling, and it will eliminate the need that each developer implement his own interface for later linking them with others or his own implementation.
 
As each interface done by different developers, even if it has the same functions, it will be considered different, because its from different assemblies.

Regards.

**Comment by karelz** [comment]
While in theory having interface without implementation is good idea, in practice interfaces (except the very basic ones) are rarely enough for anyone to get unblocked. People need primarily the implementation classes to instantiate. If they are to implement it on their own, they might as well contribute to CoreFX repo.
All the basic & most used interfaces/classes are already in .NET Core 2.0. The release was driven by API usage analysis of NuGet packages and applications - see https://apisof.net where some of the data is publicly available.

Also, there is no master plan of what will be in v3, v4, etc. - We have backlog, few things are on the top (DirectoryServices, Drawing, PerformanceCounters and few more), but for the rest, we're basically waiting to see demand.

If you have specific interfaces missing in 2.0 in mind, please let us know, we can discuss their specifics (please check existing issues first - esp. [port-to-core](https://github.com/dotnet/corefx/labels/port-to-core)).

Closing as this is not actionable.
