### ISSUE TITLE
System.Net.Tests.HttpListenerPrefixCollectionTests.Add_InvalidPrefixNotStarted_ThrowsHttpListenerExceptionOnStart(uriPrefix: \"http://a08196d3572648a99e9d3669ecdda58c/\") fails in CI on mac OSX

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#19593]
As discussed in https://github.com/dotnet/corefx/pull/19579

```cs

public static IEnumerable<object[]> InvalidPrefix_TestData()
{
    // [ActiveIssue()]
    if (!PlatfomDetection.IsOSX)
    {
        yield return new object[] { $"http://{Guid.NewGuid().ToString("N")}/" };
    }
}

[Theory]
[MemberData(nameof(InvalidPrefix_TestData))]
public void Add_InvalidPrefixNotStarted_ThrowsHttpListenerExceptionOnStart(string uriPrefix)
{
    var listener = new HttpListener();
    listener.Prefixes.Add(uriPrefix);

    Assert.Equal(1, listener.Prefixes.Count);
    Assert.True(listener.Prefixes.Contains(uriPrefix));
    Assert.Throws<HttpListenerException>(() => listener.Start());
}
```

This test fails with mac OSX: 

```
MESSAGE:
Assert.Throws() Failure\nExpected: typeof(System.Net.HttpListenerException)\nActual: (No exception was thrown)
+++++++++++++++++++
STACK TRACE:
at System.Net.Tests.HttpListenerPrefixCollectionTests.Add_InvalidPrefixNotStarted_ThrowsHttpListenerExceptionOnStart(String uriPrefix) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest/src/System.Net.HttpListener/tests/HttpListenerPrefixCollectionTests.cs:line 264
```

**Comment by hughbe** [comment]
So what confuses me here, is: does this mean we're listening to network traffic to `"http://a08196d3572648a99e9d3669ecdda58c/\"`

This is a randomly generated page that shouldn't exist anyway!

**Comment by karelz** [comment]
@Priya91 can you please triage it against 2.0?
If it is in 2.0, please add also Post-ZBB label, because it was filed late.

**Comment by Priya91** [comment]
@hughbe I executed this test on my local mac, and didn't get the test failure, remove the platformdetection.isosx check for the guid case.

**Comment by hughbe** [comment]
I think the problem with this test is that it seems to be indeterminate?

**Comment by Priya91** [comment]
> I think the problem with this test is that it seems to be indeterminate?

It's not i've added explanation to the linked PR. The url is not invalid, when HttpListener is not able to resolve the host to an IPAddress, it listens on 0.0.0.0, which is ipaddresses of all network interfaces. Hence, this test case is not what we want. It failed only on osx, because listening to 0.0.0.0 requires sudo access, and the innerloop runs except osx are not run in sudo environment. As a result all oses fails with permission denied, but on osx it passes. Modified the test in the linked PR.

**Comment by karelz** [comment]
Reopening to track 2.0 port.

**Comment by karelz** [comment]
2.0 porting tracked in https://github.com/dotnet/corefx/issues/20060#issuecomment-302956042
