### ISSUE TITLE
[Desktop] Test failures: System.Net.Tests.HttpListenerPrefixCollectionTests / Add_InvalidPrefix*

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#19619]
Tests affected `System.Net.Tests.HttpListenerPrefixCollectionTests`:
* `Add_InvalidPrefixNotStarted_ThrowsHttpListenerExceptionOnStart`
* `Add_InvalidPrefixAlreadyStarted_ThrowsHttpListenerExceptionOnAdd`

Failed again in Desktop daily run. I was not able to get a local repro, this seems to be more like the configuration on the CI machines but not sure what it is. Note that the only test case that failed was:

https://github.com/dotnet/corefx/blob/master/src/System.Net.HttpListener/tests/HttpListenerPrefixCollectionTests.cs#L245

So maybe removing that case when PlatformDetection.IsFullFramework for now?

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/51/testReport/

cc: @hughbe @stephentoub

**Comment by safern** [comment]
cc: @davidsh

**Comment by stephentoub** [comment]
These tests are more trouble than they're worth.  Let's just disable them until we're done with 2.0 and ZBB.

Failed again here on Windows on core:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_debug_prtest/64/consoleText
and here on Linux:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_ubuntu14.04_debug_prtest/30/consoleText

**Comment by stephentoub** [comment]
Failed here on desktop:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_release_prtest/2/
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug_prtest/7/

**Comment by karelz** [comment]
Note: The test-run-core part was addressed in #19526

**Comment by stephentoub** [comment]
We no longer run these tests on netfx.
