### ISSUE TITLE
Review all remaining samness tests in System.Text.Encodings.Web.Tests

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefx#1961]
There are some tests in the suite that Assert.Same. These need to be reviewed and either removed or we need to ensure the code is synchronizing properly and the tests will not fail.

**Comment by karelz** [comment]
@KrzysztofCwalina can you tell us what exactly is needed? It is not clear, sorry.

**Comment by karelz** [comment]
@KrzysztofCwalina ping?

**Comment by tarekgh** [comment]
looks to me the tests there are not failing and there is no any disabled test cases there. I am closing this issue and if we get any test failure later we can still fix it. @KrzysztofCwalina please reopen the issue if you think otherwise
