### ISSUE TITLE
Remove conditional compilation in System.Diagnostics.Tracing

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#19624]
As discussed offline with @vancem, we should remove conditional compilation which was introduced in PR https://github.com/dotnet/corefx/pull/18427 when these APIs will be available in NS21:

```
public abstract partial class EventListener : System.IDisposable 
{ 
    protected internal virtual void OnEventWritten(System.Diagnostics.Tracing.EventWrittenEventArgs eventData) { }
}
public class EventSourceCreatedEventArgs : EventArgs 
{ 
    public EventSourceCreatedEventArgs() { } 
    public EventSource EventSource { get; } 
} 
```

cc @brianrob

**Comment by brianrob** [comment]
@ViktorHofer, can this be fixed for 2.1?  It looks to me like this would require changing desktop, is that right?

**Comment by ViktorHofer** [comment]
Sorry Brian for getting back to you so late. I see that we are currently compiling the src/test/ref projects against netcoreapp and some against uap/uapaot. I believe all these APIs should be available there and we can just safely remove the DefineConstant and the if precompiler statements. I think when I created that issue we were also building against netstandard20.

**Comment by brianrob** [comment]
Marking this for the hackathon.  This is about removing the preprocessor define for FEATURE_ETLEVENTS.  Per @ViktorHofer it looks like this should be fairly straightforward.

**Comment by laurentkempe** [comment]
Hi, I'll try to fix this!

**Comment by karelz** [comment]
@laurentkempe great! Collaboration invite sent - see https://github.com/dotnet/corefx/wiki/Hackathon#how-can-i-grab-an-issue for details.

**Comment by laurentkempe** [comment]
@karelz ok I accepted the invitation
