### ISSUE TITLE
SqlClientFactory.CreateDataAdapter returns null

### ISSUE THREAD

**Issue by RickStrahl** [dotnet/corefx#19651]
I'm running the .NET Core 2.0 bits and testing against some legacy full framework packages (yeah some legacy code). Looks like most of the other services are working, just the data adapter isn't.

![image](https://cloud.githubusercontent.com/assets/1374013/25937667/655d86a2-35e1-11e7-9a87-8a7c17e388ec.png)

Is this something that will come later?

**Comment by justinvp** [comment]
I went ahead and grabbed this. Will submit PR shortly.
