### ISSUE TITLE
Docker Image microsoft/dotnet:1.1.1-runtime doesn't have fix in LibCurl

### ISSUE THREAD

**Issue by gortok** [dotnet/corefx#19658]
In PR #16895, a fix for lib_curl on linux was put in to improve HttpClient POST Performance in .NET Core.  However, even though the PR says it should be deployed to the dotnet:1.1.0 docker repo, I pulled and reproduced the issue with the `dotnet:1.1.1-runtime` docker image. A reproduction of the issue is here: https://github.com/gortok/httpclient-tests (Dockerfile is in that repo).

Was this fix deployed? If so, which docker image should contain it?

**Comment by solbirn** [comment]
@gortok Seems to be resolved in dotnet:1.1.2-runtime

**Comment by gortok** [comment]
@solbirn We checked that docker container and it still uses version 7.38.0 of libcurl (the slow version).

**Comment by MichaelSimons** [comment]
The [fix](https://github.com/dotnet/corefx/pull/15354) is in microsoft/dotnet:1.1.2-runtime image.  Note the fix was not to upgrade the libcurl dependency, rather it is to set `CURLOPT_TCP_NODELAY`.

**Comment by karelz** [comment]
Can we close it then? Or is there any action that needs to happen?

**Comment by gortok** [comment]
@karelz @MichaelSimons Great thanks; my question is: according to [this](https://github.com/dotnet/corefx/pull/16895) the fix was supposed to be in the Runtime 1.1.1 docker image; was it? We still see that latency issue with 1.1.1; so I want to be sure it wasn't included in 1.1.1, or that I'm crazy for reading this and thinking it was supposed to be in the 1.1.1 docker image.

**Comment by MichaelSimons** [comment]
The fix you reference is about porting the fix to the 1.1.0 branch.  When a fix is applied to a release branch such as 1.1.0, the fix would be included in the next service release for that branch.  In the case of the fix you reference, that equates to 1.1.2.  You will need to upgrade to 1.1.2 in order to get the fix.
