### ISSUE TITLE
XUnit should log all InnerExceptions if a test fails

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#19667]
Example of test failures that would benefit from having the entire `Exception` chain logged during test execution: #19635, #19633.

**Comment by stephentoub** [comment]
You're referring specifically to Assert.Throws, right?

**Comment by CIPop** [comment]
> You're referring specifically to Assert.Throws, right?

In this case yes.

I'll also bring your other observation from one of the bugs:

> We also have our own AssertExtensions.Throws which we could modify to do whatever we want, and then use it in more places.

I think this might be faster/easier and won't change the current XUnit behavior. 

For reference (please correct me if I'm wrong):

* XUnit is at https://github.com/xunit/xunit 
* We have some extensions at https://github.com/dotnet/buildtools/tree/master/src/xunit.netcore.extensions 

Where is AssertExtensions.Throws located?

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/AssertExtensions.cs

**Comment by ViktorHofer** [comment]
Nothing to do here as we now use the official xunit runner. If we are missing a feature open an issue at https://github.com/xunit/xunit. If tests should use AssertExtensions.Throws instead of Assert.Throws please open an issue for the specific areas.
