### ISSUE TITLE
SqlClient.SqlClientFactory doesn't implement DbProviderFactory.CreateDataAdapter()

### ISSUE THREAD

**Issue by FransBouma** [dotnet/corefx#19673]
Hi.

In netstandard 2.0, the method DbProviderFactory.CreateDataAdapter() is present, however this method isn't implemented in SqlClient.SqlClientFactory, leading to a null being returned. This is likely an oversight caused by the fact that the factory was ported over way before DataTable and friends were ported over. I think this should be corrected before 2.0 RTM, as it's an important method for code using datatables and dataadapters. 

ref: DbProviderFactory.CreateDataAdapter docs: https://apisof.net/catalog/System.Data.Common.DbProviderFactory.CreateDataAdapter()

thanks!

**Comment by justinvp** [comment]
Looks like a dupe of #19651

**Comment by ViktorHofer** [comment]
Closing because dupe of https://github.com/dotnet/corefx/issues/19651

**Comment by FransBouma** [comment]
Yep, sorry about this. I searched for the issue but I totally overlooked the issue already filed. My bad.
