### ISSUE TITLE
SendAsync_ExpectedDiagnosticSourceActivityLogging failed in CI on Windows and Linux.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#19689]
```
System.Net.Http.Functional.Tests.DiagnosticsTest.SendAsync_ExpectedDiagnosticSourceActivityLogging [FAIL]
17:11:22         Assert.Equal() Failure
17:11:22         Expected: 42
17:11:22         Actual:   134
17:11:22         Stack Trace:
17:11:22            /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_centos7.1_debug_prtest/src/Common/tests/System/Diagnostics/RemoteExecutorTestBase.cs(188,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
17:11:22            /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_centos7.1_debug_prtest/src/System.Net.Http/tests/FunctionalTests/DiagnosticsTests.cs(308,0): at System.Net.Http.Functional.Tests.DiagnosticsTest.SendAsync_ExpectedDiagnosticSourceActivityLogging()
```

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_centos7.1_debug_prtest/16/console

**Comment by Priya91** [comment]
possibly related to #16610

cc @stephentoub

**Comment by stephentoub** [comment]
The actual failure details are just above what you quoted in the log:
```
Exception from RemoteExecutorConsoleApp(System.Net.Http.Functional.Tests, Version=4.2.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb, System.Net.Http.Functional.Tests.DiagnosticsTest, <SendAsync_ExpectedDiagnosticSourceActivityLogging>b__6_0):
  Assembly: System.Net.Http.Functional.Tests, Version=4.2.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb
  Type: System.Net.Http.Functional.Tests.DiagnosticsTest
  Method: Int32 <SendAsync_ExpectedDiagnosticSourceActivityLogging>b__6_0()
  Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xunit.Sdk.FalseException: Request was logged when Activity logging was enabled.
  Expected: False
  Actual:   True
     at Xunit.Assert.False(Nullable`1 condition, String userMessage)
     at System.Net.Http.Functional.Tests.DiagnosticsTest.<SendAsync_ExpectedDiagnosticSourceActivityLogging>b__6_0() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_centos7.1_debug_prtest/src/System.Net.Http/tests/FunctionalTests/DiagnosticsTests.cs:line 368
     --- End of inner exception stack trace ---
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     at RemoteExecutorConsoleApp.Program.Main(String[] args) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_centos7.1_debug_prtest/src/Common/tests/System/Diagnostics/RemoteExecutorConsoleApp/RemoteExecutorConsoleApp.cs:line 55
```

**Comment by v-haren** [comment]
failed again in ci, detail:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_centos7.1_debug/43/testReport/

**Comment by Jiayili1** [comment]
This issue is repro on Core Tests in build 20170512.01, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170512.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.DiagnosticsTest~2FSendAsync_ExpectedDiagnosticSourceActivityLogging

**Comment by steveharter** [comment]
This test is failing on the majority of the outerloop tests

**Comment by Priya91** [comment]
@steveharter I think one of the re-enabled tests in the PR #19686 is interfering with this test, hence the sudden burst of failures? Disabling this test for now, pending investigation.

**Comment by Priya91** [comment]
@lmolkova Can you please help in debugging the failure, it's a recently added test with the activity instrumentation feature.

**Comment by lmolkova** [comment]
New behavior was introduced in #19659 that causes this test to fail. I'll submit fix later today.

**Comment by danmosemsft** [comment]
@lmolkova did you fix this with the commit above, so this can be closed? (Note, if you include the text `Fixes #1234` in your PR description, github will close the issue for you when it merges.

**Comment by lmolkova** [comment]
@danmosemsft 
Yes, it should be fixed with #19796.

> Note, if you include the text Fixes #1234 in your PR description, github will close the issue for you when it merges

good to know, thanks

**Comment by danmosemsft** [comment]
@lmolkova for future reference you should have powers to close issues like this :)

**Comment by lmolkova** [comment]
@danmosemsft I do not have permissions to close issues not created by me. Should I have it? :)

**Comment by karelz** [comment]
@lmolkova you can close via commit message in future: https://help.github.com/articles/closing-issues-via-commit-messages/
