### ISSUE TITLE
System.Net.Sockets.Tests.DualModeBeginAccept.BeginAcceptV4BoundToSpecificV4_Success fails with COMPlus_GCStress=3

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#19683]
When running the System.Net.Sockets tests with COMPlus_GCStress=3, the tests fail with:
```
System.Net.Sockets.SocketException : Connection reset by peer
      Stack Trace:
            at System.Net.Sockets.Tests.DualModeBeginAccept.DualModeConnect_BeginAccept_Helper(IPAddress listenOn, IPAddress connectTo)
```

This has been verified by running the tests twice with the same result. No other tests failed.

It only has failed on Linux (RHEL 72 used); Windows did not fail here.

'Connection reset by peer' usually means the client closed and re-opened the connection, which could happen if another tests was colliding on port #

Worst case is there is an issue with dual-mode support on Linux perhaps contributing to getting >1 client connections to the same port + family (IPv6).  The test uses an IPv4 Loopback address but uses an IPv6 protocol on top of that.

The easiest way to repro this is to modify the RunTests.sh in the corresponding test folder to add `export COMPlus_GCStress=3`

**Comment by steveharter** [comment]
FWIW here's a test that shows Linux behavior around port # allocation. This test will cause the Exception to be thrown on Linux, but not on Windows. On Linux, IPV4 and IPV6 address families can each have an independent socket on the same port.

```c#
        [Fact]
        public void LinuxPortBehavior()
        {
            using (Socket serverSocket = new Socket(SocketType.Stream, ProtocolType.Tcp))
            {
                int port = serverSocket.BindToAnonymousPort(IPAddress.Loopback); // or IPAddress.Any
                for (int i = 0; i < 100000; i++)
                {
                    using (Socket socketTemp = new Socket(SocketType.Stream, ProtocolType.Tcp))
                    {
                        int portTemp = socketTemp.BindToAnonymousPort(IPAddress.IPv6Loopback);
                        if (portTemp == port)
                            throw new Exception("MATHCING PORTS:" + portTemp.ToString());
                    }
                }
            }
        }
```

**Comment by steveharter** [comment]
Currently attempting another repro, and investigating the dispose semantics of the test (esp the client socket)

**Comment by karelz** [comment]
@wfurt can you please take a look? Talk to @steveharter about details.

**Comment by steveharter** [comment]
I tried another repro on RHEL and it did not repro; both debug and release builds.

The test should probably be re-written as it catches and eats exceptions I assume for the 'negative' tests. I don't think there should be any SocketExceptions of ObjectDisposedExceptions for the 'positive' tests. This can mask problems for the positive tests.

**Comment by karelz** [comment]
@steveharter do you recommend to punt it for post-2.0 then?
I wonder why it was reliable repro earlier ...

**Comment by karelz** [comment]
ping @steveharter?

**Comment by karelz** [comment]
Triage: It is likely time out, moving to 2.1

**Comment by steveharter** [comment]
Yes 2.1 is appropriate. There is no consistent repro or actionable data at this point. 

I do not know why this single test failed twice in a row but not thereafter. It could have been a borderline timeout situation. Suggest we invest in infrastructure that will run tests with COMPlus_GCStress in order to find failure patterns (tests that regularly fail) while accounting for issues with timeouts.

**Comment by Sunny-pu** [comment]
failed again in CI:
https://ci.dot.net/job/dotnet_corefx/job/master/job/fedora24_release/5749/testReport/System.Net.Sockets.Tests/DualModeBeginAccept/BeginAcceptV4BoundToAnyV4_Success/

**Comment by AriNuer** [comment]
Same test `System.Net.Sockets.Tests.DualModeBeginAccept.BeginAcceptV4BoundToAnyV4_Success` has failed here:
```
Error message
Assert.Equal() Failure\nExpected: ::ffff:127.0.0.1\nActual: ::127.0.0.1

Stack trace
   at System.Net.Sockets.Tests.DualModeBeginAccept.DualModeConnect_BeginAccept_Helper(IPAddress listenOn, IPAddress connectTo) in /_/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 863
   at System.Net.Sockets.Tests.DualModeBeginAccept.BeginAcceptV4BoundToAnyV4_Success() in /_/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 787
```
Details:
https://dnceng.visualstudio.com/public/_build/results?buildId=321278&view=ms.vss-test-web.build-test-results-tab&runId=9306386&resultId=153245&paneView=debug

**Comment by karelz** [comment]
The original issue is too old, we may revisit this in overall stress effort in 5.0 - @eiriktsarpalis 

The last 2 failures are different, we should file new issue if they appear again.
