### ISSUE TITLE
ForEach or Select void to do some logic and continue with the same collection

### ISSUE THREAD

**Issue by Thaina** [dotnet/corefx#19698]
I'm not sure we should add new API or just use Select. But it would be the same argument

```C#
IEnumerable<T> Select<T>(this IEnumerable<T> list,Action<T> action);
IEnumerable<T> Select<T>(this IEnumerable<T> list,Action<T,int> action);

or

IEnumerable<T> ForEach<T>(this IEnumerable<T> list,Action<T> action);
IEnumerable<T> ForEach<T>(this IEnumerable<T> list,Action<T,int> action);
```

This let us split iteration logic easier. We could do something before `Where` clause. We could split it out from `Where` without the need to return each item unneccessary

**Comment by svick** [comment]
I don't think LINQ should encourage side-effects, especially not in the middle of a query.

Though if this method is added, it should probably stay consistent with Rx, which calls this method [`Do()`](https://msdn.microsoft.com/en-us/library/hh229804(v=vs.103).aspx).

**Comment by mikem8361** [comment]
Please ignore the PRs/merges #31991. Wrong issue.

**Comment by stephentoub** [comment]
> I don't think LINQ should encourage side-effects, especially not in the middle of a query.

Agreed. This goes against the general approach we've tried to maintain with LINQ.
