### ISSUE TITLE
System.Net.Security.Tests.SslStreamCredentialCacheTest.SslStream_SameCertUsedForClientAndServer_Ok failed in ci

### ISSUE THREAD

**Issue by v-haren** [dotnet/corefx#19699]
failed test: System.Net.Security.Tests.SslStreamCredentialCacheTest.SslStream_SameCertUsedForClientAndServer_Ok

detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_release/44/testReport/System.Net.Security.Tests/SslStreamCredentialCacheTest/SslStream_SameCertUsedForClientAndServer_Ok/

MESSAGE:
~~~
Assert.True() Failure
Expected: True
Actual: False
~~~

STACK TRACE:
~~~
at System.Net.Security.Tests.SslStreamCredentialCacheTest.<SslSessionsCacheTest>d__1.MoveNext() in D:\j\workspace\outerloop_net---15cfbbd5\src\System.Net.Security\tests\FunctionalTests\SslStreamCredentialCacheTest.cs:line 50 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Net.Security.Tests.SslStreamCredentialCacheTest.SslStream_SameCertUsedForClientAndServer_Ok() in D:\j\workspace\outerloop_net---15cfbbd5\src\System.Net.Security\tests\FunctionalTests\SslStreamCredentialCacheTest.cs:line 23
~~~

**Comment by Jiayili1** [comment]
This issue is repro on Core Tests in build 20170512.01, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170512.01/workItem/System.Net.Security.Tests/analysis/xunit/System.Net.Security.Tests.SslStreamCredentialCacheTest~2FSslStream_SameCertUsedForClientAndServer_Ok

**Comment by karelz** [comment]
Is it a regression or recent test?
2 failures on the same day out of the blue is suspicious ...

**Comment by karelz** [comment]
@davidsh @CIPop @Priya91

**Comment by CIPop** [comment]
> Is it a regression or recent test?

New test.

**Comment by CIPop** [comment]
No repro on my Win7 test machine. I need access to one of the machines running Win7 from CI.

**Comment by CIPop** [comment]
@mmitche @steveharter I see that the build for Win7 itself is failing: https://github.com/dotnet/corefx#build--test-status and starting at that table is the only way I know to create a CI machine...
If that fails I have no idea how these tests ran or how to get a repro. Any ideas?

**Comment by mmitche** [comment]
@CIPop I took the machine that last ran one of those offline so you can login and repro.  Contact me for login details.

**Comment by CIPop** [comment]
I was able to repro this on the CI machine. My local machine had the Root certificate installed which makes the test pass.

**Comment by stephentoub** [comment]
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_release/47
and here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_debug/lastCompletedBuild/testReport/

**Comment by CIPop** [comment]
Thanks @stephentoub , the test is consistently failing - I'm investigating the cause.

**Comment by stephentoub** [comment]
> the test is consistently failing

Ok, to unblock CI, I'm disabling the test.

**Comment by CIPop** [comment]
> Ok, to unblock CI, I'm disabling the test.

Thanks @stephentoub!

**Comment by CIPop** [comment]
This appears to be an OS-level behavior difference: a server running on Win7 will not request client certificates unless its own certificate is trusted locally.
I'm working with the Schannel team to further understand why this is happening and why the behavior was changed in future versions of the OS.

This is a test-only issue: real applications should not use untrusted certificates for the server side.

**Comment by karelz** [comment]
If it is test-only problem, only on Win7, I would suggest to disable the test on Win7 only and move the issue to Future.

**Comment by CIPop** [comment]
@stephentoub Thanks for merging and closing this. I was curious why it didn't auto-link: I keep saying "Fixes: #nnn" but I think it should be "Fix #nnn"...

**Comment by karelz** [comment]
Everything is fine @CIPop - "Fixes #nnn" works as well, see: https://help.github.com/articles/closing-issues-via-commit-messages/
That's exactly what happened here - Stephen didn't close this issue explicitly, but "in #19915" - it means via the "auto-close" feature.
