### ISSUE TITLE
Environment.OSVersion.Platform returns Unix on macOS

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/corefx#19694]
Using .NET Core 2.0 SDK preview.

`dotnet --info`:

```
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0-preview1-005977/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983

```

Simple test case:

```
[12:41pm yaakov@Eadu:/tmp/osver] dotnet new console
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /private/tmp/osver/osver.csproj...
Restore succeeded.

[12:41pm yaakov@Eadu:/tmp/osver] vim Program.cs 
[12:42pm yaakov@Eadu:/tmp/osver] cat Program.cs 
using System;

namespace osver
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(Environment.OSVersion.Platform);
        }
    }
}
[12:42pm yaakov@Eadu:/tmp/osver] dotnet restore && dotnet build && dotnet run
  Restoring packages for /private/tmp/osver/osver.csproj...
  Lock file has not changed. Skipping lock file write. Path: /private/tmp/osver/obj/project.assets.json
  Restore completed in 177.16 ms for /private/tmp/osver/osver.csproj.
  
  NuGet Config files used:
      /Users/yaakov/.nuget/NuGet/NuGet.Config
  
  Feeds used:
      https://api.nuget.org/v3/index.json
      /Users/yaakov/.dotnet/NuGetFallbackFolder
Microsoft (R) Build Engine version 15.3.117.23532
Copyright (C) Microsoft Corporation. All rights reserved.

  osver -> /private/tmp/osver/bin/Debug/netcoreapp2.0/osver.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.29
Unix
[12:42pm yaakov@Eadu:/tmp/osver] 
```

I would expect the program to print `MacOSX`, i.e. `System.PlatformID.MacOSX` which is enum value `6`.

**Comment by danmosemsft** [comment]
@stephentoub it is hard coded that way - there is no `Environment.OSX.cs`. Is there any reason for that?

**Comment by yaakov-h** [comment]
`Environment.Unix.cs` has a whole lot of `IsMac` conditionals - I'd suggest either add one more (:smile:), or split it out into an `Environment.OSX.cs`.

**Comment by ViktorHofer** [comment]
There isn't a lot difference between the Unix and MacOSX implementation. The IsMac property is only used seven times the existing code.

**Comment by justinvp** [comment]
> @stephentoub it is hard coded that way - there is no Environment.OSX.cs. Is there any reason for that?

It's hard coded that way to match Mono's behavior of returning Unix on macOS.

**Comment by ViktorHofer** [comment]
@justinvp Thanks for that! I didn't know that this behavior is intentional. Will wait what @stephentoub has to say about.

**Comment by yaakov-h** [comment]
Without jumping the gun waiting for Stephen, if that is indeed the case then what is the purpose of `PlatformID.MacOSX` if no .NET runtime ever returns that value?

**Comment by justinvp** [comment]
> what is the purpose of PlatformID.MacOSX if no .NET runtime ever returns that value?

`PlatformID.MacOSX` was added for Silverlight to return on OSX. I wish we hadn't added that and instead returned `PlatformID.Unix` on OSX like Mono.

See also:
https://github.com/dotnet/corefx/issues/11878
https://github.com/terrajobst/platform-compat/issues/29

**Comment by yaakov-h** [comment]
So to figure out the current OS X version you need to combine `RuntimeInformation.IsOSPlatform(OSPlatform.OSX)` with `Environment.OSVersion.Version` and ignore `Environment.OSVersion.Platform`? That sounds like an accident waiting to happen...

**Comment by stephentoub** [comment]
> Will wait what @stephentoub has to say about.

What Justin said.

**Comment by stephentoub** [comment]
We can of course re-evaluate the design.  If we want to make a change here, we should do it for 2.0 or live with it.  It's a hard call; on the one hand, MacOSX is obviously the "tighter" answer, but on the other hand, we only brought OSVersion back to help with bringing over existing code, and existing code on desktop would only ever care about Windows vs non-Windows, and existing code from Mono would be expecting Unix on macOS, so I still think aligning with Unix is the slightly better path.

**Comment by svick** [comment]
@stephentoub 

> we only brought OSVersion back to help with bringing over existing code

But how am going to learn that if I'm writing new code? I think it would be nice if https://github.com/dotnet/corefx/issues/11878 was addressed for 2.0. Whether the decision is to use `[Obsolete]` or IntelliSense hiding or something else does not matter much, but something should be done.

**Comment by stephentoub** [comment]
> but something should be done.

And aligned with Mono how?
cc: @akoeplinger, @marek-safar

**Comment by akoeplinger** [comment]
We won't be changing what Mono returns as it'd break too much code. MSBuild is also returning `Unix` for `$(OS)` even on macOS. Yes this is pretty unfortunate but I don't see it changing...

I think applying `[EditorBrowsable(false)]` to the MacOSX enum value to hide it from IntelliSense does make sense.

**Comment by marek-safar** [comment]
I think it's good this enum is available for backward compatibility but when the type was re-introduced it should be marked immediately obsolete and replaced with something what is not broken by design. I has been quite painful during past 15 years to explain over and over again that this type exists but to use it you need to understand whole history of .NET.

http://www.mono-project.com/docs/faq/technical/#how-to-detect-the-execution-platform

**Comment by danmosemsft** [comment]
@svick terrajobst/platform-compat#29 tool may help detect this.

**Comment by stephentoub** [comment]
> I think applying [EditorBrowsable(false)] to the MacOSX enum value to hide it from IntelliSense does make sense.

This sounds reasonable to me.  Maybe also hiding some of the other legacy/defunct values as well?
```C#
    public enum PlatformID
    {
        [EditorBrowsable(false)] Win32S = 0,
        [EditorBrowsable(false)] Win32Windows = 1,
        Win32NT = 2,
        [EditorBrowsable(false)] WinCE = 3,
        Unix = 4,
        [EditorBrowsable(false)] Xbox = 5,
        [EditorBrowsable(false)] MacOSX = 6
    }
```

**Comment by stephentoub** [comment]
cc: @weshaggard for standard

**Comment by stephentoub** [comment]
@danmosemsft, @weshaggard, any objections to doing the enum change above? https://github.com/dotnet/corefx/issues/19694#issuecomment-301134072

**Comment by danmosemsft** [comment]
Go for it

**Comment by ViktorHofer** [comment]
Updated PR: https://github.com/dotnet/corefx/pull/19697

**Comment by weshaggard** [comment]
>@danmosemsft, @weshaggard, any objections to doing the enum attribute change above?

I'm fine with adding those annotations as well. It is probably worth doing in .NET Standard as well so I've filed https://github.com/dotnet/standard/issues/346 to do that.
