### ISSUE TITLE
Question: How to enumerate forwarded types from facade assemblies via reflection

### ISSUE THREAD

**Issue by slozier** [dotnet/corefx#19713]
I am attempting to enumerate the types from facade assemblies (for example System.Xml.Serialization) via reflection. I loaded the assembly via Assembly.Load, but I can't figure out how to get the types, I tried `GetTypes()`, `GetExportedTypes()`, `GetCustomAttributes(typeof(TypeForwardedToAttribute))` and they all return nothing. I am able to explicitly load a type which is forwarded (e.g. `GetType("System.Xml.Serialization.XmlRootAttribute")`) so the information is somewhere in there...

**Comment by karelz** [comment]
The TypeForwarders will kick in and you will get the real type loaded. It doesn't have TypeForwarding attribute anymore of course.
Did you try to use System.Reflection.MetadataReader? Or CCI, or Mono Cecil.

Why do you need the types from facade assemblies?
Do you run your tool on .NET Core or on .NET Framework?

**Comment by slozier** [comment]
We're trying to get IronPython working with .NET Core 2.0. In IronPython (with .NET Framework) you can do something like:
```Python
import clr
clr.AddReference("System.Xml")
import System
dir(System.Xml)
```
which outputs all the types in System.Xml. To discover what types are available it loops through loaded assemblies and finds the types using GetExportedTypes.

However with .NET Core 2.0 when you have a facade assembly (for example, all the Xml assemblies appear to be facades pointing System.Private.Xml) then GetExportedTypes returns an empty array. So it can't find any of the types exposed by the facade assembly. This means that none of the forwarded types are available for use. In the example could do `clr.AddReference("System.Private.Xml")` to get it working, however I'm guessing System.Private.Xml is more of an implementation detail and is not meant for direct use.

**Comment by danmosemsft** [comment]
@weshaggard

**Comment by weshaggard** [comment]
GetTypes() should return the types even if they are forwarded. See https://msdn.microsoft.com/en-us/library/y0cd10tb(v=vs.110).aspx.

```
If the type has been forwarded to another assembly, it is still returned by this method. For information on type forwarding, see Type Forwarding in the Common Language Runtime.
```

GetExportedTypes while is similar in name to "Exported type table" which is how forwards are stored in IL, it means something different in reflection.  https://msdn.microsoft.com/en-us/library/system.reflection.assembly.getexportedtypes(v=vs.110).aspx

**Comment by AtsushiKan** [comment]
This is a functionality hole in Reflection. It does point out that DefinedTypes and ExportedTypes are rather anachronistic in this this age of .Net Core where framework types consider themselves free to migrate around any implementation assembly of their choice.

This may be the time to propose an Assembly.ExposedTypes api that returns the "apparent" surface area of an assembly (by including forwarded types.)

Or, at the risk of some compat, change the definition of DefinedTypes/ExportedTypes to include these. After all, this is the same trick we're playing on apps at build time with our reference assemblies and facades.

**Comment by AtsushiKan** [comment]
>GetTypes() should return the types 

That's GetType() (singular) which loads a single type you request by name.

GetTypes() (plural) is a wrapper for DefinedTypes and it does not return forwarded types.

**Comment by slozier** [comment]
So does that mean there is no way to figure out the forwarded types via reflection and I should be using something like System.Reflection.MetadataReader?

**Comment by AtsushiKan** [comment]
That's correct.

**Comment by AtsushiKan** [comment]
Closing because question was answered.
