### ISSUE TITLE
netstandard2.0: SqlParameter's decimals are coming back with integer precision (SqlClient issue) 

### ISSUE THREAD

**Issue by NickCraver** [dotnet/corefx#19712]
I came across this when [updating Dapper to `netstandard2.0`](https://github.com/StackExchange/Dapper/commit/7e5bd308f99b790212e6990bc4ec8b0c72579406). Our unit tests checking for decimal precision accuracy are failing on `netstandard2.0` (yet passing on `netstandard1.6`). The basics are when you select a decimal like `11.884`, it comes back as `12`.

This could be an integer issue, or a precision/scale issue, or an ordering issue - I haven't had time to dig in yet, but I wanted to file it ASAP given the `netstandard2.0` time frame.

```c#
private void Issue261_Decimals_ADONET(bool setPrecisionScaleViaAbstractApi)
{
    try
    {
        using (var cmd = connection.CreateCommand())
        {
            cmd.CommandText = "create proc #Issue261Direct @c decimal(10,5) OUTPUT as begin set @c=11.884 end";
            cmd.ExecuteNonQuery();
        }
    }
    catch { /* we don't care that it already exists */ }

    using (var cmd = connection.CreateCommand())
    {
        cmd.CommandType = CommandType.StoredProcedure;
        cmd.CommandText = "#Issue261Direct";
        var c = cmd.CreateParameter();
        c.ParameterName = "c";
        c.Direction = ParameterDirection.Output;
        c.Value = DBNull.Value;
        c.DbType = DbType.Decimal;

        if (setPrecisionScaleViaAbstractApi)
        {
            IDbDataParameter baseParam = c;
            baseParam.Precision = 10;
            baseParam.Scale = 5;
        }
        else
        {
            c.Precision = 10;
            c.Scale = 5;
        }

        cmd.Parameters.Add(c);
        cmd.ExecuteNonQuery();
        decimal value = (decimal)c.Value;
        value.IsEqualTo(11.884M);
    }
}
```

Actual output:
```
Assert.Equal() Failure
Expected: 11.884
Actual:   12
```

This is a regression from `netstandard1.6`. I'm using the latest SQL Client code available on NuGet: `4.4.0-preview1-25305-02`

**Comment by karelz** [comment]
@saurabh500 @corivera looks like another 2.0 blocker. Can you please take a look?
cc @stephentoub @danmosemsft

**Comment by karelz** [comment]
Thanks for very fast turnaround @saurabh500!

@danmosemsft @weshaggard I wonder why we missed this implemented interface in the scans we did ...
Do we need to update .NET Standard 2.0 as well?

**Comment by danmosemsft** [comment]
@karelz we certainly found absences in the scans and fixed several. The rest are in https://github.com/dotnet/corefx/issues/17126. Sqlclient is not in standard so absences were not all fixed.

**Comment by karelz** [comment]
@saurabh500 why was the original issue #17126 moved to Future, when we find it is breaking compat with Desktop?
Was it an accidental one-off mistake or should we review all the missing things again?

**Comment by karelz** [comment]
cc @divega

**Comment by saurabh500** [comment]
@karelz 
Two things:
1. This issue wasnt caught by API scan. The issue here is that IDbDataParameter.Precision was added to the basetype to make it back compat with F/W and since SqlParameter didnt implement the interface explicitly, the base class IDpDataParameter.Precision and Scale were being called. 

2. Why was #17126 moved to future? We didn't plan the work for 2.0. Quoting from the issue
`No work is necessarily required here for 2.0. It's not part of NS2.0. I didn't look at usage data. I'm just flagging this so we're doing this consciously.`

**Comment by saurabh500** [comment]
To add to point 1, the API scan would find that SqlParameter implement Precision and Scale but I don't think it identifies which level of hierarchy is going to be called when a Property on the base type is invoked.

**Comment by karelz** [comment]
Thanks for the info @saurabh500!
@danmosemsft should we review what the tooling does and maybe flag this case as well? Are there others we might be missing?

**Comment by NickCraver** [comment]
@saurabh500 thanks for the quick fix here!
