### ISSUE TITLE
Microsoft.XmlSerializer.Generator Issues

### ISSUE THREAD

**Issue by huanwu** [dotnet/corefx#19715]

**Comment by karelz** [comment]
@huanwu you filed bunch of issues, can you please set their milestone? cc @shmao @zhenlan

**Comment by ViktorHofer** [comment]
@huanwu is this still to do?

**Comment by huanwu** [comment]
@ViktorHofer It is to track Microsoft.XmlSerializer.Generator issues. I will move the milestone to future for the remaining things.

**Comment by StephenBonikowsky** [comment]
Epic completed.
