### ISSUE TITLE
Directory.Move no longer moves files

### ISSUE THREAD

**Issue by slozier** [dotnet/corefx#19710]
The following works fine with net45 and netcoreapp1.0, throws a `DirectoryNotFoundException` with 2.0.
```
File.Create("test.txt").Dispose();
Directory.Move("test.txt", "test2.txt");
```

**Comment by stephentoub** [comment]
Likely broken here:
https://github.com/dotnet/corefx/commit/074bf02532c4c4496e7c79e03b4801e848848509
cc: @alexperovich, @JeremyKuhne, @ianhays

**Comment by JeremyKuhne** [comment]
Fixing.

**Comment by JeremyKuhne** [comment]
Fixed
