### ISSUE TITLE
Codegen not support generic type

### ISSUE THREAD

**Issue by huanwu** [dotnet/corefx#19727]
This also repro in the desktop.

**Comment by huanwu** [comment]
In UWP, when generating the serializer code, it know the related type e.g. it will use type MyGenericType`1[[System.String,System.Runtime]] as the serializable type. But in SGEN, we don't know what's the related type.  So there's no easy way to fix that.

**Comment by shmao** [comment]
We'd like to investigate if we can support a generic type if a user explicitly specify the type.

**Comment by shmao** [comment]
@huanwu can you please try passing the specific generic type via the new `SerializationType` parameter and see if it works?

**Comment by huanwu** [comment]
It works if you pass the generic type via the serialization type the new feature in #24491.

e.g.
For the generic type:
```
    public class MyGeneric<T>
    {
        public T MyType { get; set; }
    }
```

You can specify the generic type like:
```
    <SerializationAssembly Include="MyData">
      <SerializationType>MyData.MyGeneric`1[[System.String,System.Runtime]]</SerializationType>
    </SerializationAssembly>
```

**Comment by shmao** [comment]
@huanwu , can you please open a doc issue for the workaround?
