### ISSUE TITLE
Cannot generate code for recursive type

### ISSUE THREAD

**Issue by huanwu** [dotnet/corefx#19721]
When generate the code for recursive type, it will throw stackoverflow exception. This also repro on the desktop version.

**Comment by shmao** [comment]
We have fix for the issue in Net Native toolchain. We'd like to port the fix.

**Comment by huanwu** [comment]
In toolchain, the fix is only in DCS and DCJS. And the fix is limited to case that the collection type form the recursive with its item type as the following.

```
[CollectionDataContract]
public class RecursiveCollection : List<RecursiveCollection2>{}

[CollectionDataContract]
public class RecursiveCollection2 : List<RecursiveCollection3>{}

[CollectionDataContract]
public class RecursiveCollection3 : List<RecursiveCollection>{}
```

**Comment by shmao** [comment]
We don't see any user case of using XmlSerializer with recursive collections. Closing the issue.
