### ISSUE TITLE
Fail to generate the code if contain the classes with the same XmlType name

### ISSUE THREAD

**Issue by huanwu** [dotnet/corefx#19728]
Code generation will fail for the following classes. This also repro on the desktop.

```
[XmlType(TypeName = "MyXmlType")]
public class TypeWithStringArrayAsXmlAttribute
{
    [XmlAttribute(Form = XmlSchemaForm.Qualified)]
    public string[] XmlAttributeForms;
}

[XmlType(TypeName = "MyXmlType")]
public class TypeWithTypeNameInXmlTypeAttribute
{
    [XmlAttribute(Form = XmlSchemaForm.Qualified)]
    public string XmlAttributeForm;
}
```

**Comment by huanwu** [comment]
Same as issue #19720 and #19722, when to import the second type, in the code https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/Serialization/XmlReflectionImporter.cs#L713, it will return the mapping for the first type because their type name is same, which is MyXmlType in this case. The fix is to add one more key "fullname" to the NameTable class at huanwu/corefx@533072e. However, based one desktop regression run, there're some regression issue in wcf test. The cost of the fix might be high.

**Comment by shmao** [comment]
This is not a supported scenario. Considering the fix is risky, and we're not going to make fix for the issue until we get a strong customer ask.
