### ISSUE TITLE
Fail to generate the code if the type of the class contains any property that only have private setter.

### ISSUE THREAD

**Issue by huanwu** [dotnet/corefx#19723]
During code generation, if any of the class contains the property that only have private setter, it will throw exception. We need ignore this type but not make the code generation fail. This also repro on desktop.

**Comment by shmao** [comment]
Reopening the issue. The fix made by #24611 no longer worked after we move the serialization implementation back to System.Private.Xml.dll

**Comment by huanwu** [comment]
With some code moving back to system.private.xml.dll, we can no longer access the internal types like MemberMapping. Actually, when to serialize a type without public setter, the serialization will be broken (both IL and c# codegen). To fix this problem, we might have to impact the XmlSerializer behavior. In SG, we just exclude this type. But SG has the separate code and SGEN share the same code as XmlSerializer.

**Comment by StephenBonikowsky** [comment]
Closing as there is no customer ask to fix this and the same issue also exists on full framework.
