### ISSUE TITLE
When generate the code for two classes that contains the same collection type, the second one will be ignored

### ISSUE THREAD

**Issue by huanwu** [dotnet/corefx#19720]
If generate the code for two classes that contains the same collection type as the following, it won't generate the write method for the collection in the second class. During the serialization for the object of the second type, it will use the write method generated for the collection in the first type, which will end with conversion error. This also repro on the desktop.
```
public class MyCollection1 : IEnumerable<DateTime>, IEnumerable
{
    private List<DateTime> _values = new List<DateTime>();
…
}
public class EnumerableCollection : IEnumerable<DateTime>
{
private List<DateTime> _values = new List<DateTime>();
…
}
```

**Comment by huanwu** [comment]
This is because the mapping of the second collection type won't be saved because it has the same key as the same collection.  In the code https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/Serialization/XmlReflectionImporter.cs#L1059,  when process the mapping for the second type, it will return the mapping of the first collection type, which cause the second mapping being replaced by the first mapping. I made a fix here. https://github.com/huanwu/corefx/commit/533072e1114932faeea85e3649bee2bffd04566f

**Comment by shmao** [comment]
We'd like try the fix on .Net Framework and see if it would cause any regressions.

**Comment by huanwu** [comment]
Tried the fix on full framework. There're many regressions in wcf tests.  No clear clue from the error log. Need do many further investigation if still need take this fix. The cost might be high.
