### ISSUE TITLE
HttpWebRequest difference in behavior between .Net Core and Desktop

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#19732]
If we run the following code:

```cs
HttpWebRequest request = HttpWebRequest.CreateHttp(url);
request.BeginGetResponse(null, null);
request.BeginGetRequestStream(null, null);
```

When the `HttpMethod` doesn't support getting a request stream, i.e: `HttpMethod.Get`; in desktop we will get a `ProtocolViolationException` and in Net Core we will get an `InvalidOperationException` because the request was already submitted through `request.BeginGetResponse(null, null);`.

However if we don't submit the request and only do:

```cs
HttpWebRequest request = HttpWebRequest.CreateHttp(url);
request.BeginGetRequestStream(null, null);
``` 

Both platforms will throw a `ProtocolViolationException`. This is because in .Net Core we are checking first if the request was submitted, and in Desktop the first thing we do is checking if the current protocol is valid. 

#### Netcore
http://source.dot.net/#System.Net.Requests/System/Net/HttpWebRequest.cs,1026

#### Desktop
https://referencesource.microsoft.com/#System/net/System/Net/HttpWebRequest.cs,1515

However if we want to match behaviors by doing the protocol first in [.NET Core](http://source.dot.net/#System.Net.Requests/System/Net/HttpWebRequest.cs,1034) to match Desktop's behavior we would be introducing a breaking change because we already shipped this behavior in 1.1 and 1.0

Which one we care most, being compatible with Desktop or with core previous versions?

cc: @stephentoub @davidsh @ViktorHofer

**Comment by Priya91** [comment]
fyi @CIPop @karelz

**Comment by stephentoub** [comment]
> Which one we care most, being compatible with Desktop or with core previous versions?

Desktop

**Comment by safern** [comment]
> Desktop

It is a simple change then. Grabbing this one.
