### ISSUE TITLE
Possible bug in System.Data.SqlClient, with LocalDB and Stored Procedures

### ISSUE THREAD

**Issue by cskwg** [dotnet/corefx#19743]
While porting some code from .Net 4.5 to core, I noticed a possible bug and currently see no workaround.
It is a DOTNET CORE project, with all the latest nuget packages (v2.0 preview).
It is being build with Usual Studio 2017 15.1.

Details of the exception:

	System.InvalidOperationException: There is already an open DataReader associated with this Command which must be closed first.
	   at System.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)
	   at System.Data.SqlClient.SqlConnection.ValidateConnectionForExecute(String method, SqlCommand command)
	   at System.Data.SqlClient.SqlCommand.ValidateCommand(Boolean async, String method)
	   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
	   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
	   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
	   at System.Data.SqlClient.SqlCommand.ExecuteReader()
	   at DbBug.Program.Main(String[] args) in z:\TFS\IDB\etc\GKW\test\DbBug\Program.cs:line 43

In the full .NET Framework, the same code is running without problems.

Outline of the behavior is:

 - I'm using a connection for a sequence of database operations.
 - After doing some work with this connection, BeginTransaction fails with the above exception.
 - When I close and reopen the connection just before BeginTransaction, this statement runs without problems.
 - But then, after running some commands inside this connection, the call to transaction.Commit() fails with the same exception. 

I am very carefull with the DataReader, closing it after every use.

The problem only happens, if the connection is not closed before reading for the second time.

REPRO:
```c#
using System;
using System.Data;
using System.Data.SqlClient;
//
namespace DbBug {
    //
    class Program {
        //
        static void Main( string[] args ) {
            var connection_string = "Address=(localdb)\\LocalZDB;Database=ZENDB;UID=ZENDB;PWD=DbZenPw2017;WSID=GROOVE;Application Name=Db.Tests;Integrated Security=False;Max Pool Size=32;Min Pool Size=2;Pooling=true";
            var connection = new SqlConnection( connection_string );
            connection.Open();
            //
            IDataReader rdr = null;
            int count = 0;
            try {
                string sql = "EXEC [ZENDB].[dbo].UserReadAll";
                var cmd = connection.CreateCommand();
                cmd.CommandText = sql;
                cmd.CommandTimeout = 1000;
                rdr = cmd.ExecuteReader();
                //
                while ( rdr.Read() ) {
                    var id = rdr.IsDBNull( 0 ) ? 0 : rdr.GetInt64( 0 );
                    count++;
                }
            } catch ( Exception ex ) {
                Console.WriteLine( ex.ToString() );
            } finally {
                if ( rdr != null ) rdr.Close();
                //connection.Close();
            }
            var c = rdr.IsClosed;
            //
            //connection.Open();
            rdr = null;
            count = 0;
            try {
                string sql = "EXEC [ZENDB].[dbo].UserReadAll";
                var cmd = connection.CreateCommand();
                cmd.CommandText = sql;
                cmd.CommandTimeout = 1000;
                rdr = cmd.ExecuteReader();
                //
                while ( rdr.Read() ) {
                    var id = rdr.IsDBNull( 0 ) ? 0 : rdr.GetInt64( 0 );
                    count++;
                }
            } catch ( Exception ex ) {
                Console.WriteLine( ex.ToString() );
            } finally {
                if ( rdr != null ) rdr.Close();
                connection.Close();
            }
        }
    }
}
```

**Comment by karelz** [comment]
Looks like compat issue, marking it as 2.0 until proven otherwise - cc @saurabh500 @corivera @divega

**Comment by saurabh500** [comment]
@corivera I think this may have to do with SqldataReader not implementing the IDataReader directly.
`                if ( rdr != null ) rdr.Close(); `
The reader is being closed with the reference of `IDataReader`

**Comment by saurabh500** [comment]
@cskwg We couldn't get a repro with the above code snippet, however looking at the error message, I believe that the PR https://github.com/dotnet/corefx/pull/19851 should fix this issue for you. (we modified the repro to invoke Sql Queries for sample databases) 
We are probably not able to repro the issue with your code potentially because it may have to do with the Database and the stored procs that you are using. Can you provide a more contained repro with Database details (schema and data)? 

IDataReader.Close() was not calling the close of SqlDataReader because SqlDataReader didn't implement the interface explicitly. It received the implementation from the Base type DbDataReader. With the PR mentioned above, the Close() if SqlDataReader should be called closing the SqlDataReader correctly.

**Comment by karelz** [comment]
Let's close this as fixed.
@cskwg if you can test it on latest daily build, that would be a great help: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md

Please let us know how it goes. If it is still broken, please given us isolated repro as @saurabh500 suggests above. Note that we need to act quickly as Ask mode ends on 5/26 - see https://github.com/dotnet/corefx/issues/17619#issuecomment-301937346
