### ISSUE TITLE
netstandard2.0: SqlDataReader doesn't implement GetSchemaTable()

### ISSUE THREAD

**Issue by NickCraver** [dotnet/corefx#19748]
There's a disconnect between the `netstandard2.0` intent and actual implementations here, resulting in runtime errors on things that call `.GetSchemaTable()`.

The way ADO.NET is setup, `DbDataReader` has added some methods over time (since adding to interfaces is bad), of these `.GetSchemaTable()` is one brought back in `netstandard2.0`. It's a virtual that each implementation needs to override.

[Here's the Core FX `DbDataReader.GetSchemaTable()`](https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/src/System/Data/Common/DbDataReader.cs#L57):
```c#
public virtual DataTable GetSchemaTable()
{
    throw new NotSupportedException();
}
```

The problem is [`SqlDataReader` never overrides this](https://github.com/dotnet/corefx/blob/84d5d7e278249a8c3682801a05ff505cd489ebb1/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlDataReader.cs).

For comparison, here's reference source for .NET 4.x [where this does happen](https://referencesource.microsoft.com/#System.Data/System/Data/SqlClient/SqlDataReader.cs,1396).

In the current state, the result is a `NotSupportedException` when actually calling the method:
```
System.NotSupportedException : Specified method is not supported.
Stack Trace:
    at System.Data.Common.DbDataReader.GetSchemaTable()
    at System.Data.ProviderBase.SchemaMapping..ctor(DataAdapter adapter, DataSet dataset, DataTable datatable, DataReaderContainer dataReader, Boolean keyInfo, SchemaType schemaType, String sourceTableName, Boolean gettingData, DataColumn parentChapterColumn, Object parentChapterValue)
    at System.Data.Common.DataAdapter.FillMappingInternal(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 schemaCount, DataColumn parentChapterColumn, Object parentChapterValue)
    at System.Data.Common.DataAdapter.FillMapping(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 schemaCount, DataColumn parentChapterColumn, Object parentChapterValue)
    at System.Data.Common.DataAdapter.FillFromReader(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 startRecord, Int32 maxRecords, DataColumn parentChapterColumn, Object parentChapterValue)
    at System.Data.Common.DataAdapter.Fill(DataTable[] dataTables, IDataReader dataReader, Int32 startRecord, Int32 maxRecords)
    at System.Data.DataTable.Load(IDataReader reader, LoadOption loadOption, FillErrorEventHandler errorHandler)
    at System.Data.DataTable.Load(IDataReader reader)
```

Note that this wasn't calling it directly, it was trying to use `DataTable` much further away. So there's quite a few places this is used.

I think this was just an oversight after `DataTable` and truckloads of other things were brought back for `netstandard2.0`. Can we please get this in so it's usable?

Past issues for context on more usages (for prioritization):
- #1039
- #3423

Related concern: this isn't listed in #17126 because it compiles and doesn't have a `PlatformNotSupportedException`, but it's obviously missing. I think we need a separate API call for ADO.NET for things that aren't overridden in CoreFX, that's the superset of items we need to narrow down and fill the gaps on. Not everything should be overridden, but that's likely the easiest list to generate and quickly narrow down.

**Comment by NickCraver** [comment]
cc @karelz @saurabh500

**Comment by karelz** [comment]
@danmosemsft another example where we missed overrides in .NET Core 2.0 - I start to worry ... IMO we need to boost the tooling and scan for all missing implemented interfaces and overrides, then review them all.

**Comment by karldodd** [comment]
+1. Found this problem too while migrating my lib to netstarndard2.0 .

**Comment by saurabh500** [comment]
I have a branch with the code ported from Framework sitting at https://github.com/saurabh500/corefx/tree/datareaderSchema 
This needs testing though. I can't get to it until tomorrow. 
@NickCraver Do you think you can build the SqlClient from my branch and run it through Dapper tests?

**Comment by NickCraver** [comment]
@saurabh500 My time is very limited and building is usually a mess - if you can get me a `.nupkg` link I'm happy test it out that's pretty low time-cost and hopefully something easy to produce on your side? Let me know and I'll throw it in the mix ASAP.

**Comment by saurabh500** [comment]
@NickCraver If you can tell me how to execute the Dapper Tests selectively, that would be great. 
E.g. I want to run only Dapper.Tests.Tests.ExecuteReaderOpenAsync without executing any other tests. How do I do that?

**Comment by saurabh500** [comment]
Running Dapper tests with my changes to SqlClient 
Here is the status 

Before changes
`Dapper.Tests  Total: 286, Errors: 0, Failed: 10, Skipped: 13, Time: 36.848s` 

After changes
`Dapper.Tests  Total: 286, Errors: 0, Failed: 5, Skipped: 13, Time: 36.291s`

I don't see any more stack traces with the following. 
```
System.NotSupportedException : Specified method is not supported.
Stack Trace:
     at System.Data.Common.DbDataReader.GetSchemaTable()
```

I will add some more tests with my changes and send out a PR. 

PS: @NickCraver It would still be helpful to know the filters for Dapper tests so that I can execute them selectively.

**Comment by NickCraver** [comment]
@saurabh500 absolutely, starting at the repo root, here's how to run a single test:
```
dotnet restore
cd Dapper.Tests
dotnet xunit -method "Dapper.Tests.Tests.ExecuteReaderOpenAsync"
```

**Comment by saurabh500** [comment]
@NickCraver Thanks
Also is there a way to filter on the netcoreapp2.0 tests?

**Comment by NickCraver** [comment]
@saurabh500 Yep! `dotnet xunit -framework netcoreapp2.0`, you can see all the filter options with `dotnet xunit -h` :)

**Comment by saurabh500** [comment]
@NickCraver Thanks for the confirmation :) I was wondering if there is a different mechanism that you use. 
Many different projects have their own way of doing things. So I thought I would ask

**Comment by Davilink** [comment]
I have i project who target the Net Framework 4.7.1 it use a project who target Net Standard 2.0. In the project Net Standard 2.0, i use an SqlDataReader and when i tried to use the GetColumnSchema() it throws an exception (Not supported).

What i'm missing, isn't supported to work ?
