### ISSUE TITLE
UnknownHeaders_Success HttpListener test always hangs for me locally on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#19754]
It apparently passes in CI, but every run for me hangs.  The test sends 1000 custom headers to the server and validates they were all received: when I change the number to 998 or less, it passes quickly, but when it's 999 or greater, it hangs.  It runs successfully in all cases on netfx.

**Comment by stephentoub** [comment]
I'm fixing the test to at least not hang, splitting it into two tests (a small and large number of headers), disabling the large one against this issue, and moving this issue to Future, as such a large number of headers is very niche.

**Comment by karelz** [comment]
@stephentoub do you plan to take it into 2.0 with your bulk integration into rel/2.0.0? The number of failures is on the border of being bothersome ... OTOH we can fix tests even later (in servicing branches, if they cause noise ...)

**Comment by stephentoub** [comment]
> do you plan to take it into 2.0

Yes, as we've discussed, all changes related to HttpListener since we forked should go to rel/2.0 in bulk.

**Comment by karelz** [comment]
OK, thanks. Marked as 2.0 then and added to the list of things to port: https://github.com/dotnet/corefx/issues/20060#issuecomment-302956042

**Comment by caesar1995** [comment]
We should not close this issue, because it hasn't been completely fixed.

> ... splitting it into two tests (a small and large number of headers), disabling the large one against this issue, and moving this issue to Future, as such a large number of headers is very nice.

The `UnknownHeaders_Success_Large()` test remains disabled. We should Reopen the issue, and mark it as Future.

@karelz @davidsh

**Comment by karelz** [comment]
It's getting messy what is tracked where. @caesar1995 can you please open a new bug to track the remaining part?
The main part was fixed in both 2.0 and 2.1, by moving it to Future we will lose track of that track in issues / make it hard to reason about. Thanks!

**Comment by stephentoub** [comment]
> It's getting messy what is tracked where. @caesar1995 can you please open a new bug to track the remaining part?

@karelz, when asking for a replacement issue, let's please avoid closing the first issue until the replacement is created.  Otherwise it's too easy to get lost (e.g. if @caesar1995 happens to miss the notification of your comment).

(Separately, I don't really understand why we need to close this issue and create another, but I won't argue.)
