### ISSUE TITLE
HttpWebRequest.Host throw new PlatformNotSupportedException()

### ISSUE THREAD

**Issue by zokiad** [dotnet/corefx#19753]
Hi,

HttpWebRequest.Host throw new PlatformNotSupportedException()
Why ? Limitation ?
Host is usefull to test a web farm. We use server IP to connect and Host to define the web site to test.

```C#
    HttpWebRequest request = HttpWebRequest.CreateHttp("https://X.X.X.X");
    request.UserAgent = "Mozilla/5.0 (compatible; )";
    request.Timeout = 10000;
    request.Host = uri.Host;
```

**Comment by karelz** [comment]
@zokiad thanks for your report!

This has been addressed in #19118, which was not included in the Preview 1 bits.
See the change [here](https://github.com/dotnet/corefx/commit/9e2256d02d25d11b5317ee946453948ec45c7c6c#diff-c70c98d319d6fa28c754b26a04324f2eR279)

Could you please validate that it is addressed in latest daily build? See [dogfooding instructions](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md) - if they are too cryptic, please let me know. We may need to update them to patch up Preview 1 in VS.

**Comment by zokiad** [comment]
Ok, thanks. If it is not urgent, I will validate on next preview.

**Comment by stephentoub** [comment]
I'm going to close this.  The implementation no longer throws PNSE and we have multiple tests validating the updated behavior.  If you discover otherwise, please reopen.  Thanks.
