### ISSUE TITLE
The plugin hasn't been performed correctly: Problem on deletion failed in ci

### ISSUE THREAD

**Issue by v-haren** [dotnet/corefx#19767]
CI tests pass, but plugin fails to report results

[xUnit] [ERROR] - The plugin hasn't been performed correctly: Problem on deletion

detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_osx_debug/47/consoleFull#-7738886783554902-aff0-4799-9e92-0ada24ce2a06

**Comment by danmosemsft** [comment]
fyi @mmitche

**Comment by v-haren** [comment]
failed again here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_osx_release/50/consoleFull#-7738886783554902-aff0-4799-9e92-0ada24ce2a06

**Comment by mmitche** [comment]
@ilyas1974 @JPratherMS FYI

I may need to put some code in there to capture the stack trace.  Interesting that's it happening on similar legs.

**Comment by v-haren** [comment]
failed again here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_osx_release/76/consoleFull#-7738886783554902-aff0-4799-9e92-0ada24ce2a06

**Comment by stephentoub** [comment]
Again here:
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/osx_debug_prtest/267/
and again here:
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/osx_release_prtest/271/

**Comment by mmitche** [comment]
Agh, the worst.  This is going to be hard to track down.  @dotnet/eng-first I've filed https://github.com/dotnet/core-eng/issues/915 to track/fix this.

It's catching either IOException or InterruptedException.

**Comment by stephentoub** [comment]
Another:
https://ci.dot.net/job/dotnet_corefx/job/release_1.1.0/job/osx_debug_prtest/383/

**Comment by stephentoub** [comment]
Another:
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/osx_release_prtest/272/

**Comment by v-haren** [comment]
failed again here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_release/82/consoleFull#-7738886783554902-aff0-4799-9e92-0ada24ce2a06

**Comment by mmitche** [comment]
@v-haren Ooh, non-windows.

For now i'm going to add this to the retry logic.

**Comment by v-haren** [comment]
failed again here:https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_osx_debug/87/consoleFull#-7738886783554902-aff0-4799-9e92-0ada24ce2a06

**Comment by mmitche** [comment]
@v-haren We committed the retry logic just after this failure.  Let me know if you see it again.

**Comment by Jiayili1** [comment]
This issue is repro in outerloop_netcoreapp_win7_debug, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_debug/228/consoleFull#-7738886783554902-aff0-4799-9e92-0ada24ce2a06

**Comment by Jiayili1** [comment]
again on outerloop_netcoreapp_win7_release, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_release/258/

**Comment by danmosemsft** [comment]
Old
