### ISSUE TITLE
ThreadPoolBoundHandle.BindHandle should not be supported on Unix

### ISSUE THREAD

**Issue by kouvel** [dotnet/corefx#19785]
ThreadPool.BindHandle always returns false on Unix, so ThreadPoolBoundHandle.BindHandle would fail the assertion. It should throw PNSE.

**Comment by kouvel** [comment]
Since ThreadPoolBoundHandle is now type-forwarded to S.P.CoreLib as of https://github.com/dotnet/corefx/pull/19597, instead of S.T.Overlapped being a PNSE assembly

**Comment by danmosemsft** [comment]
@kouvel are you still tracking this for 2.0? if so do you have an eta.. ask mode ends this week.

**Comment by kouvel** [comment]
The fix and tests have been merged into the release branch through master:
- https://github.com/dotnet/coreclr/blob/release/2.0.0/src/mscorlib/src/System/Threading/ClrThreadPoolBoundHandle.Unix.cs#L12
- https://github.com/dotnet/corefx/blob/release/2.0.0/src/System.Threading.Overlapped/tests/ThreadPoolBoundHandle_BindHandleTests.cs#L47

Just missed closing this bug, closing now
