### ISSUE TITLE
Need Reflection api to enumerate type-forwards in an assembly.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#19789]
**Proposed Api**

```c#
     class Assembly
     {
          public virtual Type[] GetForwardedTypes() { throw new NotImplemented.ByDesign; }
     }
```

Gets the Types exposed by this assembly but defined in another assembly.

If one or more Types fail to load (perhaps because the forwardee assembly cannot be found), this api throws a **ReflectionTypeLoadException**. The **ReflectionTypeLoadException**'s **Types** and **LoaderExceptions** property can be queried to recover the Types that did successfully load. (Works similarly to **Assembly.GetTypes()** (https://msdn.microsoft.com/en-us/library/system.reflection.assembly.gettypes(v=vs.110).aspx))

**Why is the api signature so retro?**

This is a companion api to **Assembly.GetTypes()** and follows its form. We could also have used **Assembly.DefinedTypes** as a template but that form has two problems:

- That api was introduced for the aborted .Net Core 1.0 refactoring and returns **TypeInfo** rather than **Type**. **TypeInfo** is now a historical curiosity and an unnecessary distraction. **Assembly.GetTypes()** has the incumbency advantage.

- The **IEnumerable** form is intended to imply lazy list generation which is at odds with the **ReflectionTypeLoadException** mechanism of salvaging partial results in the event of type load exceptions. The docs are silent as to whether you can recover partial results with this form.

**Use case**

This was always a functionality hole in Reflection and in this world of refactoring-happy .Net Core, type forwarders are everywhere, even in reference assemblies. We've already had one issue raised about this (https://github.com/dotnet/corefx/issues/19713) as it used to be possible to enumerate System.Xml's surface area with Reflection but no longer.

**Nested Types**

The returned array will include any nested types within returned types whose visibility (and that of its containing nested types) is **NestedPublic**. This reflects the ECMA-335 rule that the ExportedTypes table can only contain types that are **Public** or **NestedPublic**.

Nested types will be returned whether or not the ExportedType table contains a separate entry for the nested type (as the presence or absence of it has no effect on whether the nested type can be resolved through that assembly.)

**AssemblyBuilder**

AssemblyBuilder does not override GetTypes() and there's no burning reason to override GetForwardedTypes() either. It's not like you can add type forwards using RefEmit today.

**Comment by AtsushiKan** [comment]
cc @slozier, @MichalStrehovsky , @davidwrighton 

Will open for discussion for a week before taking to api-ready.

**Comment by davidwrighton** [comment]
What are the expected semantics in situations where the assembly a type is forwarded to is not available at runtime?

**Comment by AtsushiKan** [comment]
@davidwrighton  That was addressed here:

If one or more Types fail to load (perhaps because the forwardee assembly cannot be found), this api throws a ReflectionTypeLoadException. The ReflectionTypeLoadException's Types and LoaderExceptions property can be queried to recover the Types that did successfully load. (Works similarly to Assembly.GetTypes() (https://msdn.microsoft.com/en-us/library/system.reflection.assembly.gettypes(v=vs.110).aspx))

**Comment by karelz** [comment]
API review:
@AtsushiKan will we ever need API which tells where the TypeForwarder goes to? The above won't tell you that in case there are 2 or more hops: type forwarders: A -> B -> C.
The underlying question: Is this the API users actually want?

(conditionally approved: if the answer above is yes, most customers want this API)

**Comment by AtsushiKan** [comment]
@karelz - I think that's a different use case (i.e. metadata analysis rather than just wanting to get the advertised type loaded.) For the latter case, type-forwarding is an implementation detail and the caller likely doesn't want to be bothered with it. It's like the CustomAttribute vs. CustomAttributeData divide. They're both useful but in different situations.

@slozier: feel free to chime in. I think your use case could be accomodate with either flavor, though the one we propose probably plugs it in more easily into your current codebase.

**Comment by slozier** [comment]
Yes, I believe this API is exactly what we need to get things working for us. The end goal is to be able to enumerate over all types in an assembly (forwarded or not) and this would give us exactly what we're missing (the forwarded types).

**Comment by karelz** [comment]
OK, API review: Approved.

**Comment by karelz** [comment]
@AtsushiKan please mark it up-for-grabs if suitable. With hints of next steps and cost estimation (see details in [Triage info](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified)).

**Comment by AtsushiKan** [comment]
Needs implementation on CoreCLR and Project N first (opened separate issues for those). The CoreCLR one may be grabbable for those with necesssary prereqs and moderate ambition.

Then it can be marked up-for-grabs (just adding the new api to the contract assemblies and writing some simple tests.)
