### ISSUE TITLE
Add System.Runtime.CompilerServices.RuntimeFeature.PortablePdb

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#19788]
Currently there is no support for Portable PDBs in Desktop FX. We are finishing support in stack traces for portable and embedded PDBs for 4.7.1. Features that generate code at runtime (such as scripting) would benefit from being able to detect whether the runtime supports Portable PDBs or not, as they could emit Portable PDBs instead of Windows PDBs. Emitting Portable PDBs has perf benefits.

In order to make the feature detection consistent across all platforms we propose to add the following APIs to netstandard as well.

# Proposed API 

```C#
namespace System.Runtime.CompilerServices
{
    public static class RuntimeFeature
    {
        public const string PortablePdb = nameof(PortablePdb);

        // returns true for feature == "PortablePdb"
        public static bool IsSupported(string feature);
    }
}

// Usage

if (RuntimeFeature.IsSupported("PortablePdb")
{
      // Emit code with Portable debug info
}
```

**Comment by tmat** [comment]
@karelz What's the process for approving this API for Desktop FX 4.7.1?

**Comment by karelz** [comment]
@tmat email fxdc. @leecow might also help.

**Comment by tmat** [comment]
@marek-safar What's the process of adding APIs to Mono? If we added this API to 4.7.1 should it also be added to Mono? Do you have a release synchronized with Desktop FX?

**Comment by karelz** [comment]
BTW: Mono is trying to reuse CoreFX source libraries, so it will be likely in the same boat as .NET Core.

**Comment by weshaggard** [comment]
>In order to make the feature detection consistent across all platforms we propose to add the following APIs to netstandard as well.

The RuntimeFeature API isn't slated for netstandard yet, at least not netstandard2.0. It would be good to get it into .NET Framework 4.7.1 however.

**Comment by marek-safar** [comment]
@tmat it's enough to cc me on the commit where the change is being worked on for CoreFX or CoreRT. We can add it earlier if the API is approved.

**Comment by terrajobst** [comment]
Looks good as proposed

**Comment by jcouv** [comment]
@tmat I see that the RuntimeFeatures "PortablePdb" flag was added. Are we using it in Roslyn at this point?
If we do, I'll use that as an example for a contributor who is working on another feature that needs a flag.

**Comment by tmat** [comment]
@jcouv We are not using it yet.
