### ISSUE TITLE
Importing Sdk.props results in circular dependency on web app creation

### ISSUE THREAD

**Issue by vsccarl** [dotnet/corefx#19790]
In the latest vsuml (26515.00) I'm seeing the below error when creating a new ASP .NET Core Web Application (both .NET Core and Framework) .NET Core 1.1. The solution does not successfully contain the new project after clicking ok.

![image](https://cloud.githubusercontent.com/assets/12900364/26073626/45a7221a-3964-11e7-8b36-8c02041aa7ba.png)

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/project-system #2173](https://github.com/dotnet/project-system/issues/2173) via [**ZenHub**](https://www.zenhub.com/)
