### ISSUE TITLE
New Contributor - Build-Tests Fails on Clean Clone

### ISSUE THREAD

**Issue by garfbradaz** [dotnet/corefx#19794]
Hey Guys,

I've decided to help out on the dead code issue (#17905), I have followed the repo's instructions on forking; cloning and building the root repository, and I'm finding test errors before I even start on changes required for #17905.

Here are the errors I have received when running **build-test.cmd** in root:

Build FAILED.

       "c:\dotnet\corefx\src\tests.builds" (default target) (1) ->
       "c:\dotnet\corefx\src\System.Net.NameResolution\tests\FunctionalTests\System.Net.NameResolution.Functional.Tests.csproj" (Test target) (88:3) ->
       (RunTestsForProject target) -> 
         c:\dotnet\corefx\Tools\tests.targets(338,5): warning :    System.Net.NameResolution.Functional.Tests  Total: 53, Errors: 0, Failed: 9, Skipped: 0, Time: 17.563s [c:\dotnet\corefx\src\System.Net.NameResolution\tests\FunctionalTests\System.Net.NameResolution.Functional.Tests.csproj]
         c:\dotnet\corefx\Tools\tests.targets(338,5): warning MSB3073: The command "c:\dotnet\corefx\bin/Windows_NT.AnyCPU.Debug/System.Net.NameResolution.Functional.Tests/netstandard//RunTests.cmd c:\dotnet\corefx\bin/testhost/netcoreapp-Windows_NT-Debug-x64/" exited with code 1. [c:\dotnet\corefx\src\System.Net.NameResolution\tests\FunctionalTests\System.Net.NameResolution.Functional.Tests.csproj]

       "c:\dotnet\corefx\src\tests.builds" (default target) (1) ->
       "c:\dotnet\corefx\src\System.Net.Security\tests\FunctionalTests\System.Net.Security.Tests.csproj" (Test target) (99:3) ->
         c:\dotnet\corefx\Tools\tests.targets(338,5): warning :    System.Net.Security.Tests  Total: 138, Errors: 0, Failed: 3, Skipped: 5, Time: 5.276s [c:\dotnet\corefx\src\System.Net.Security\tests\FunctionalTests\System.Net.Security.Tests.csproj]
         c:\dotnet\corefx\Tools\tests.targets(338,5): warning MSB3073: The command "c:\dotnet\corefx\bin/Windows_NT.AnyCPU.Debug/System.Net.Security.Tests/netcoreapp//RunTests.cmd c:\dotnet\corefx\bin/testhost/netcoreapp-Windows_NT-Debug-x64/" exited with code 1. [c:\dotnet\corefx\src\System.Net.Security\tests\FunctionalTests\System.Net.Security.Tests.csproj]

       "c:\dotnet\corefx\src\tests.builds" (default target) (1) ->
       "c:\dotnet\corefx\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.Tests.csproj" (Test target) (84:3) ->
         c:\dotnet\corefx\Tools\tests.targets(338,5): warning :    System.Net.Http.Functional.Tests  Total: 311, Errors: 0, Failed: 1, Skipped: 11, Time: 3.061s [c:\dotnet\corefx\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.Tests.csproj]
         c:\dotnet\corefx\Tools\tests.targets(338,5): warning MSB3073: The command "c:\dotnet\corefx\bin/Windows_NT.AnyCPU.Debug/System.Net.Http.Functional.Tests/netstandard//RunTests.cmd c:\dotnet\corefx\bin/testhost/netcoreapp-Windows_NT-Debug-x64/" exited with code 1. [c:\dotnet\corefx\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.Tests.csproj]

       "c:\dotnet\corefx\src\tests.builds" (default target) (1) ->
       "c:\dotnet\corefx\src\System.Security.Principal.Windows\tests\System.Security.Principal.Windows.Tests.csproj" (Test target) (201:3) ->
         c:\dotnet\corefx\Tools\tests.targets(338,5): warning :    System.Security.Principal.Windows.Tests  Total: 10, Errors: 0, Failed: 2, Skipped: 1, Time: 0.577s [c:\dotnet\corefx\src\System.Security.Principal.Windows\tests\System.Security.Principal.Windows.Tests.csproj]
         c:\dotnet\corefx\Tools\tests.targets(338,5): warning MSB3073: The command "c:\dotnet\corefx\bin/Windows_NT.AnyCPU.Debug/System.Security.Principal.Windows.Tests/netstandard//RunTests.cmd c:\dotnet\corefx\bin/testhost/netcoreapp-Windows_NT-Debug-x64/" exited with code 1. [c:\dotnet\corefx\src\System.Security.Principal.Windows\tests\System.Security.Principal.Windows.Tests.csproj]

       "c:\dotnet\corefx\src\tests.builds" (default target) (1) ->
       "c:\dotnet\corefx\src\System.Net.NameResolution\tests\FunctionalTests\System.Net.NameResolution.Functional.Tests.csproj" (Test target) (88:3) ->
       (RunTestsForProject target) -> 
         c:\dotnet\corefx\Tools\tests.targets(346,5): error : One or more tests failed while running tests from 'System.Net.NameResolution.Functional.Tests' please check c:\dotnet\corefx\bin/Windows_NT.AnyCPU.Debug/System.Net.NameResolution.Functional.Tests/netstandard/testResults.xml for details! [c:\dotnet\corefx\src\System.Net.NameResolution\tests\FunctionalTests\System.Net.NameResolution.Functional.Tests.csproj]

       "c:\dotnet\corefx\src\tests.builds" (default target) (1) ->
       "c:\dotnet\corefx\src\System.Net.Security\tests\FunctionalTests\System.Net.Security.Tests.csproj" (Test target) (99:3) ->
         c:\dotnet\corefx\Tools\tests.targets(346,5): error : One or more tests failed while running tests from 'System.Net.Security.Tests' please check c:\dotnet\corefx\bin/Windows_NT.AnyCPU.Debug/System.Net.Security.Tests/netcoreapp/testResults.xml for details! [c:\dotnet\corefx\src\System.Net.Security\tests\FunctionalTests\System.Net.Security.Tests.csproj]

       "c:\dotnet\corefx\src\tests.builds" (default target) (1) ->
       "c:\dotnet\corefx\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.Tests.csproj" (Test target) (84:3) ->
         c:\dotnet\corefx\Tools\tests.targets(346,5): error : One or more tests failed while running tests from 'System.Net.Http.Functional.Tests' please check c:\dotnet\corefx\bin/Windows_NT.AnyCPU.Debug/System.Net.Http.Functional.Tests/netstandard/testResults.xml for details! [c:\dotnet\corefx\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.Tests.csproj]

       "c:\dotnet\corefx\src\tests.builds" (default target) (1) ->
       "c:\dotnet\corefx\src\System.Security.Principal.Windows\tests\System.Security.Principal.Windows.Tests.csproj" (Test target) (201:3) ->
         c:\dotnet\corefx\Tools\tests.targets(346,5): error : One or more tests failed while running tests from 'System.Security.Principal.Windows.Tests' please check c:\dotnet\corefx\bin/Windows_NT.AnyCPU.Debug/System.Security.Principal.Windows.Tests/netstandard/testResults.xml for details! [c:\dotnet\corefx\src\System.Security.Principal.Windows\tests\System.Security.Principal.Windows.Tests.csproj]

       "c:\dotnet\corefx\src\tests.builds" (default target) (1) ->
       (TestAllProjects target) -> 
         c:\dotnet\corefx\dir.traversal.targets(77,5): error : (No message specified) [c:\dotnet\corefx\src\tests.builds]

    8 Warning(s)
    5 Error(s)

### Steps I followed

1. Forked and checked out repository (15th May)

https://github.com/dotnet/corefx/wiki/Checking-out-the-code-repository

> c:\dotnet>git clone https://github.com/garfbradaz/corefx.git
> Cloning into 'corefx'...
> remote: Counting objects: 562807, done.
> remote: Compressing objects: 100% (3/3), done.
> remote: Total 562807 (delta 0), reused 0 (delta 0), pack-reused 562804
> Receiving objects: 100% (562807/562807), 140.81 MiB | 6.11 MiB/s, done.
> Resolving deltas: 100% (440613/440613), done.
> Checking out files: 100% (15071/15071), done.

2. Ran the following (https://github.com/dotnet/corefx/wiki/Build-and-run-tests):
	a) sync
	b) build
	c) build-test

### My Tin

I dont know how much information you need from me so here is the **systeminfo**

> Host Name:                 WL0093
> OS Name:                   Microsoft Windows 10 Enterprise N
> OS Version:                10.0.15063 N/A Build 15063
> OS Manufacturer:           Microsoft Corporation
> OS Configuration:          Member Workstation
> OS Build Type:             Multiprocessor Free
> Registered Owner:          N/A
> Registered Organization:   N/A
> Product ID:                00330-00180-00000-AA640
> Original Install Date:     16/04/2017, 12:46:56
> System Boot Time:          12/05/2017, 14:44:36
> System Manufacturer:       HP
> System Model:              HP EliteBook Folio 1040 G3
> System Type:               x64-based PC
> Processor(s):              1 Processor(s) Installed.
>                            [01]: Intel64 Family 6 Model 78 Stepping 3 GenuineIntel ~2607 Mhz
> BIOS Version:              HP N83 Ver. 01.08, 02/09/2016
> Windows Directory:         C:\WINDOWS
> System Directory:          C:\WINDOWS\system32
> Boot Device:               \Device\HarddiskVolume2
> System Locale:             en-gb;English (United Kingdom)
> Input Locale:              en-gb;English (United Kingdom)
> Time Zone:                 (UTC+00:00) Dublin, Edinburgh, Lisbon, London
> Total Physical Memory:     8,073 MB
> Available Physical Memory: 2,478 MB
> Virtual Memory: Max Size:  15,753 MB
> Virtual Memory: Available: 7,217 MB
> Virtual Memory: In Use:    8,536 MB
> Page File Location(s):     C:\pagefile.sys
> Domain:                    hachette.hluk.net
> Logon Server:              \\WOT01ADS-HDC01
> Hotfix(s):                 2 Hotfix(s) Installed.
>                            [01]: KB4018483
>                            [02]: KB4015583
> Network Card(s):           3 NIC(s) Installed.
>                            [01]: Intel(R) Ethernet Connection I219-LM
>                                  Connection Name: Ethernet
>                                  Status:          Media disconnected
>                            [02]: Intel(R) Dual Band Wireless-AC 8260
>                                  Connection Name: WiFi
>                                  DHCP Enabled:    Yes
>                                  DHCP Server:     192.168.1.254
>                                  IP address(es)
>                                  [01]: 192.168.1.153
>                                  [02]: fe80::880e:5551:fa2c:5eff
>                            [03]: Bluetooth Device (Personal Area Network)
>                                  Connection Name: Bluetooth Network Connection
>                                  Status:          Media disconnected
> Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

### Test Logs mentioned in the error

The following are links to the **testResults.xml** for each of the **ERROR** tests mentioned above.

[c:\dotnet\corefx\bin/Windows_NT.AnyCPU.Debug/System.Net.NameResolution.Functional.Tests/netstandard/testResults.xml](https://gist.github.com/garfbradaz/a52df93b8687798103337cc79714a2d1)

[c:\dotnet\corefx\bin/Windows_NT.AnyCPU.Debug/System.Net.Security.Tests/netcoreapp/testResults.xml](https://gist.github.com/garfbradaz/3c7f4d4b75bc0508cfc6cd81af962d4e)

[c:\dotnet\corefx\bin/Windows_NT.AnyCPU.Debug/System.Net.Http.Functional.Tests/netstandard/testResults.xm](https://gist.github.com/garfbradaz/690c670d667a34ed9df6ddcc0ebbf972)

[c:\dotnet\corefx\bin/Windows_NT.AnyCPU.Debug/System.Security.Principal.Windows.Tests/netstandard/testResults.xml](https://gist.github.com/garfbradaz/bf278259d1c633a6953fe4bf827663d1)

I hope this is enough info? I dont mind looking into the test failures, BUT should a clean fork/clone be running into issues when **build-test** is run for the 1st time?

@karelz : You suggested in gitter i tag you in the issue :)

**Comment by karelz** [comment]
@mellinoe @weshaggard can you please help?

**Comment by mellinoe** [comment]
Hmm, it seems like some of the tests do not like how your machine is set up. Perhaps there is something unusual about your network or domain settings that is interacting badly with the tests. I wouldn't be surprised if it's the same underlying issue causing all of the test failures. For example, it seems really unusual that this test would be failing:

https://github.com/dotnet/corefx/blob/master/src/System.Net.NameResolution/tests/FunctionalTests/ResolveTest.cs#L17

That is a really basic test case; it doesn't do anything complicated.

This error message from the System.Net.Security tests looks very suspicious, too:
```
System.AggregateException : One or more errors occurred. (A call to SSPI failed, see inner exception.) (Authentication failed on the remote side (the stream might still be available for additional authentication attempts).)
---- System.Security.Authentication.AuthenticationException : A call to SSPI failed, see inner exception.
-------- System.ComponentModel.Win32Exception : The system cannot contact a domain controller to service the authentication request. Please try again later
```

@CIPop Does that error look like something that would happen on a machine with a weird domain configuration? I can't really tell what it means, other than the fact that it looks wrong and clearly isn't expected by the test code.

**Comment by CIPop** [comment]
> Does that error look like something that would happen on a machine with a weird domain configuration?

I think that the AD configuration is OK, just that the machine was not able to connect to its DC at that particular point in time while the OS expected it to be able to do that. 

If the machine is taken outside of a corpnet the credentials should be cached and the test should pass. In this case, could it be possible that the machine still believes it's in corpnet but the connection to the domain controller is somehow bad?

**Comment by CIPop** [comment]
Just saw the other failures. This explains it:
```
><![CDATA[System.ComponentModel.Win32Exception : The trust relationship between this workstation and the primary domain failed]]></message
```

The machine has most likely lost the trust relationship as it was outside of the domain network for more than the token expiration time. You should also see issues during login.

**Comment by garfbradaz** [comment]
> The machine has most likely lost the trust relationship as it was outside of the domain network for more than the token expiration time. You should also see issues during login.

I'm off to work in a mo, I will build the tests when there.  When using a FortiClient VPN to corpnet, I get the same errors.

Thanks guys, i will report back in the next couple of hours.

**Comment by garfbradaz** [comment]
# Update

I'm connected to my corp domain, run **build-tests** and ALL tests run successfully.

I will re-run tonight at home just to check, but I think my dev workflow for corefx will now be (until home machine is back online):

1. Home - code
2. Work - build-tests, *cough* lunchtimes check build errors and fix
3. Home - more code

Thanks everyone. Tonight I will close the issue once restested. FYI, even via VPN to corp domain the builds failed at home, so something iffy about my machine build. I may even just fire up a VM and be done with it.

**Comment by CIPop** [comment]
Sounds like the VPN is interfering by not allowing Domain Controller access (at least when the tests are trying to reach it) while the network containing it is apparently available to your system. 

You may be able to simplify your plan by using a local account on the same machine or, as you proposed, a VM.

The alternative is to figure out how to allow DC access through the VPN (you may be able to debug using `tracert` and then alter your routing table). This is more complicated and risky...
