### ISSUE TITLE
XmlDownloadManager HttpRequest in Core vs. WebRequest in Full Framework

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#19806]
XmlDownloadManager.GetNonFileStream uses HttpRequest on Core, whereas it uses WebRequest in Desktop. This change was originally made at time of porting Xml because WebRequest was not available then. 
This causes cases like `XmlReader.Create("ftp://www.bing.com")` not be acceptable and hit the following error:  `System.Net.Http.HttpRequestException: Only 'http' and 'https' schemes are allowed.`

The method needs to change to match Desktop implementation.

**Comment by safern** [comment]
Difference in behavior in between Core and Full Framework should be 2.0? @danmosemsft

**Comment by danmosemsft** [comment]
Yes 2.0
