### ISSUE TITLE
MARS async read timeouts in Entity Framework tests with parallel testing enabled

### ISSUE THREAD

**Issue by corivera** [dotnet/corefx#19810]
When using a managed SNI enabled SqlClient in Entity Framework tests, some tests in EFCore.SqlServer.FunctionalTests can take over a minute to complete when using MARS while XUnit test parallelization is enabled. When using the LongRunning task continuation option in SqlClient async reads, these tests runs go from over a minute to less than 10 seconds. We need to investigate the underlying threading issues that are causing the async reads to get blocked while using MARS.

**Comment by corivera** [comment]
CC @saurabh500 @divega

**Comment by stephentoub** [comment]
@corivera, is there another issue tracking fixing whatever the underlying cause of the blocking was and removing the LongRunning option?
