### ISSUE TITLE
typeof(MyEnum).GetEnumValues() return confusing result

### ISSUE THREAD

**Issue by dudikeleti** [dotnet/corefx#19822]
I do not know if it's a bug or it's on purpose ..

`enum MyEnum { A = 0, B = 0 }`

What do you think should be the result of this:

`typeof(MyEnum).GetEnumValues()`

the result is: A, A

If the return array was: 0,0 sure it's OK but A,A is little confusing.. why not B,B?

I think it was less confusing if it was A,B

(maybe not use just ` Enum.ToObject((Type) this, values[index])` but consider sort by name in case of two identical values)

**Comment by AtsushiKan** [comment]
It's not returning "A, A" or "B, B" - it 's returning (MyEnum)0, (MyEnum)0 which then gets printed as "A, A".

A and B are just two ways to get to the identical enum value. They are not two distinct values.
