### ISSUE TITLE
SqlConnection doesn't override DbProviderFactory property

### ISSUE THREAD

**Issue by FransBouma** [dotnet/corefx#19825]
Hi,

Currently SqlConnection doesn't override the `DbProviderFactory` property. On Desktop/.NET full this is used by `DbConnection.ProviderFactory`, an internal property used by `DbProviderFactories`. This last class isn't part of .NET core, however the lack of these properties and implementation makes it harder to bring this class back to .NET core, as `DbProviderFactories` contains a method `GetFactory(DbConnection)`, which simply reads the property `DbConnection.ProviderFactory`.

Likely a complete oversight due to the stalemate on whatever has to happen with DbProviderFactories in .NET core for the last 2 years (See #4571 )

My advice would be two-fold: 

* add `DbConnection.ProviderFactory` property, as internal. (See: https://referencesource.microsoft.com/#System.Data/System/Data/Common/DBConnection.cs,68) (will file another issue for that)
* override `DbConnection.DbProviderFactory` in SqlConnection.cs. 

This would then open the door to add `DbProviderFactories` to .NET core to make sharing code using that class between .NET full and .NET core easy.

**Comment by saurabh500** [comment]
I am moving this issue to 2.1.0. This is useful with DbProviderFactories and is a step forward in enabling the API in System.Data

**Comment by FransBouma** [comment]
It's a small use case, but it could limit people porting code to corefx to obtain the SqlClient factory (as there's no DbProviderFactories in 2.0.0) when obtaining a SqlConnection, through reflection: they can't use generic code to do that if this is absent: they have to use special case code which tests for SqlConnection and hard-codes to obtain the factory through SqlClientFactory.Instance. That's of course doable, though less ideal. As it's 1 line of code, I don't see a big problem merging this, but I don't control that :)

**Comment by FransBouma** [comment]
Merged! :)

**Comment by saurabh500** [comment]
@FransBouma  I am reopening this to port the PR to release/2.0.0 and track the port

**Comment by saurabh500** [comment]
To clarify, I will be doing the port and no other action item is needed here :)

**Comment by FransBouma** [comment]
Ah ok, sorry didn't know it was still needed! :) 😄

**Comment by saurabh500** [comment]
Ported to 2.0.0 using PR https://github.com/dotnet/corefx/pull/20198
Good to close now.
