### ISSUE TITLE
DbConnection doesn't offer an internal property ProviderFactory

### ISSUE THREAD

**Issue by FransBouma** [dotnet/corefx#19826]
Hi

(This issue is related to #19825). To bring back the functionality of the `DbProviderFactories` class to .NET core so sharing of code between .NET full and .NET core is easy, it's required to have `DbConnection.ProviderFactory` present, as `DbProviderFactories` has a method `GetFactory(DbConnection)` which reads this property to obtain the factory. 

.NET full has this implementation: https://referencesource.microsoft.com/#System.Data/System/Data/Common/DBConnection.cs,68
which reads the virtual property `DbProviderFactory` which is present in .NET core's DbConnection (and by default returns null). 

Implementing this property on DbConnection will make it easy to add the `DbProviderFactories` class from reference source to .NET core (without the machine.config stuff of course) and offer the same functionality so porting code over from .NET full to .NET core is easy.

**Comment by saurabh500** [comment]
@FransBouma I want to confirm if you will you be making changes and sending a PR for this issue?

**Comment by FransBouma** [comment]
Yes, I'll work on this today.

**Comment by FransBouma** [comment]
Issue #17905 has removed the code which implements this issue in commit 81506698. The PR will resurrect the 'dead' code. I've replied in that issue as well, will proceed with the PR, I'll leave it up to MS to decide what to do.

**Comment by FransBouma** [comment]
This issue should be labeled 2.1.0, it's incorrectly labeled 2.0.0. It's closely related to #4571

**Comment by saurabh500** [comment]
Ack. I am moving this issue to 2.1.0

**Comment by divega** [comment]
@FransBouma @saurabh500 it seems to me that this is already fixed in master. Can you please check?

**Comment by FransBouma** [comment]
@divega yes this has already been added: https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/src/System/Data/Common/DbConnection.cs#L38 The DbProviderFactories implementation otherwise wouldn't be working ;) I'll close this one. I didn't know it was still open.
