### ISSUE TITLE
Add <msxsl:script> support to System.Xml.Xsl

### ISSUE THREAD

**Issue by busbina** [dotnet/corefx#19837]
In need of this to be supported in order to move onto Core 2.0.

**Comment by morganbr** [comment]
We need to consider the security implications of Xsl scripting since there are a [number](https://msdn.microsoft.com/en-us/library/ms763800(v=vs.85).aspx) of [cases](https://msdn.microsoft.com/en-us/library/wk7yxab1(v=vs.110).aspx) where it is not safe to use. 

CC @blowdart

**Comment by blowdart** [comment]
Yea I'd much rather we don't even go here.

A single request doesn't strike me as justification for something so risky in terms of security.

**Comment by busbina** [comment]
I need it for legacy customer support, it already comes disabled, and I am fine enabling based on customer needs. Without it we are stuck on MSXML 6.0, with no package deployment options.

**Comment by jamesfarrer** [comment]
+1 for me for this. Also holding back a .NET Core port

**Comment by tehkyle** [comment]
+1 here as well.

**Comment by stevieg402** [comment]
+1 it's also holding back a .Net Core project here.

**Comment by nzthiago** [comment]
Have run into a customer porting a BizTalk mapping solution into Azure, trying to run their existing maps from inside Azure Functions, and ran into this same issue with Functions v2 (.NET Core based) while V1 worked fine (netfx based).

What are some alternatives? Remove any scripting from the maps, move the script code back into your main .NET code and edit the output file contents with it?

**Comment by krwq** [comment]
Current recommendation is to remove any dependency on this feature. We'll update if plans regarding support for this feature change

**Comment by TFTomSun** [comment]
+1 here as well

**Comment by TFTomSun** [comment]
@carlomilanesi can u please tell me more about your workaround? Is it possible to transform xslt with scripts on linux with ur solution?

**Comment by sharanys** [comment]
+1. Please update on the latest developments on this case

**Comment by connecsys** [comment]
+1 for me too.  I have a team that wants to leverage the BizTalk/EIP map designer to create XSLT that is executed in .NET Core.  Please let me know if there is another visual designer they can leverage that is compatible with .NET Core.

**Comment by hxbergen** [comment]
+1 for me too

**Comment by mstaal** [comment]
+1 for me too. I would very much appreciate this feature!

**Comment by mstaal** [comment]
+1 for me too!

**Comment by mstaal** [comment]
I would like this functionality for legacy purposes, but I realized that this concept is just as good, and it actually come with .NET Core as of now:
https://docs.microsoft.com/en-us/dotnet/standard/data/xml/xslt-extension-objects

**Comment by mstaal** [comment]
For those who may be interested, I have made this small example of how to use Microsoft XSLT Extension Objects instead of the msxsl-tag:
https://github.com/mstaal/XsltService/

**Comment by brandonh-msft** [comment]
Here's an example doing this in .NET Core v2 from w/in an Azure Function:
https://github.com/brandonh-msft/EmbeddedXsltTestFunction

**Comment by terrajobst** [comment]
We don't plan on bringing this .NET Framework API to .NET Core. See [this announcement](https://github.com/dotnet/corefx/issues/41769) for details.
