### ISSUE TITLE
'System.Text.Encoding is not assignable to parameter type 'System.Text.Encoding'

### ISSUE THREAD

**Issue by austindrenski** [dotnet/corefx#19832]
I'm working on a library targeting .NET Standard 1.6 and I'm seeing the following error:

>Argument type 'System.Text.Encoding [System.Text.Encoding, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]' is not assignable to parameter type 'System.Text.Encoding [System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]'
    
It sounds like one of the parameters is targeting a private version of `System.Text.Encoding`. 

Any advice?

>Screenshot:
> ![image](https://cloud.githubusercontent.com/assets/21338699/26119617/d4941f1e-3a3b-11e7-9b28-2c274360ade4.png)

>Snippet:
>```c#
>using (BinaryReader reader = new BinaryReader(stream, Encoding.ASCII))
>{
>}
>```

**Comment by danmosemsft** [comment]
@joperezr is this 2.0

**Comment by AlexGhiondea** [comment]
@tarekgh any ideas about this one?

**Comment by tarekgh** [comment]
CC @weshaggard who may guess what the problem is. does BinaryReader(Stream, Encoding) is exposed directly from corelib? or maybe the library @austindrenski trying to build is referencing corelib directly instead of System.Runtime?

**Comment by AlexGhiondea** [comment]
Marking as future for now. Feel free to bump to 2.0 if you believe that is better.

**Comment by weshaggard** [comment]
@austindrenski in order to help we need more information. How are you building this project? What references do you have? Perhaps a sample project or diag log would help.

**Comment by iccfish** [comment]
I think this issue maybe due to Reshaper, See https://youtrack.jetbrains.com/issue/RSRP-464676

**Comment by tarekgh** [comment]
@iccfish thanks for pointing to that.

@austindrenski could you please provide a repro project so we can confirm if the issue is Resharper or it is different issue?

**Comment by austindrenski** [comment]
@weshaggard @iccfish @tarekgh Ah, it was indeed a Resharper warning....should have taken a closer look at the logs. 

Thanks for taking a look at this, all.
