### ISSUE TITLE
Is Microsoft.XmlSerializer.Generator shipping with 2.0.0?

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#19835]
What is the plan for this package in release/2.0.0?

Do we plan to ship it as stable?
Pre-release?
Not at all?

**Comment by ericstj** [comment]
Can you state explicitly what your desire is for the release/2.0.0 branch?  Do you want a pre-release published to nuget?

**Comment by zhenlan** [comment]
This component should not release anything for 2.0 (neither pre-release nor stable).

**Comment by weshaggard** [comment]
We already pushed a prerelease version of this package during preview1 https://www.nuget.org/packages/Microsoft.XmlSerializer.Generator/1.0.0-preview1-25305-02. We can unlist it but if we don't want to ship it we need to make sure we remove it from the package list for the rest of the shipping cycles. @zhenlan should it even be producing a package yet?

**Comment by zhenlan** [comment]
Yes, please unlist this package. Thanks! Is there a package list I can update to exclude it from 2.0 release?

Our current plan is to release this component as a NuGet package eventually, so producing a package helps our E2E testing.

cc: @huanwu @shmao

**Comment by ericstj** [comment]
It sounds like you want it published to myget but not nuget.org.  No, we don't have anything to control that at the moment.  In the past the push to nuget.org was manual so we'd just leave it out of the list.  I believe @dagood is trying to make it automatic this release.  @dagood do you have a way to exclude a package?

We do have an extra safeguard that can be added to prevent us from accidentally marking something stable:
https://github.com/dotnet/corefx/commit/5e28c1b2afbb9e29ad24253989030b6ce71d1622#diff-b01830cd4393979ff5d59f4c53265860R8
That's just a redundant place to specify that you don't want the package marked stable.

**Comment by dagood** [comment]
There hasn't been any work on the automated release story yet, but I'll keep this type of exclusion in mind and see if it makes sense to have that config in the repo.

I have some small scripts I use to help with the manual releases which support package exclusions--I'll add this exclusion to that script in case we do another manual release before we get automation.

**Comment by zhenlan** [comment]
Sounds good. Thanks @dagood. Will you unlist the one on nuget.org?

**Comment by dagood** [comment]
No problem. I've unlisted it now and added an exclusion to my script for future 2.0.0 releases.

**Comment by zhenlan** [comment]
Awesome! Thanks @dagood.
