### ISSUE TITLE
Pipes: WritableBuffer.Write() throws InvalidOutOfRangeException when writing empty array

### ISSUE THREAD

**Issue by cesarbs** [dotnet/corefx#19845]
![image](https://cloud.githubusercontent.com/assets/924164/26129825/c13c1c5e-3a46-11e7-93e8-b0ef64ce8577.png)

![image](https://cloud.githubusercontent.com/assets/924164/26129852/e3b82bf6-3a46-11e7-8625-622ba7d8006c.png)

**Comment by stephentoub** [comment]
@cesarbs, did you intend to open this in corefxlab rather than corefx?

**Comment by stephentoub** [comment]
This issue was moved to dotnet/corefxlab#1547

**Comment by cesarbs** [comment]
Sorry, yeah, was meant for corefxlab.
