### ISSUE TITLE
PinnedObject.Release may attempt to release an invalid GCHandle during shutdown

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#19857]
If process shutdown happens to stop PinnedObject.Release processing within the GCHandle.Free call, then shutdown finalization of the same object will generate an InvalidOperationException. The same may occur if the constructor is preempted by shutdown.

**Comment by karelz** [comment]
Reopening to track the 2.0 fix

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/corefx/pull/20006
