### ISSUE TITLE
System.Reflection.Tests.MemberInfoTests.TestEquality_Multiple fails due to non-deterministic ordering of nested classes

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#19852]
See https://github.com/dotnet/corefx/pull/19842#issuecomment-301937137 and https://github.com/dotnet/corefx/pull/19849.

We should either remove the test case, do an on-ordered equality check, or sort on MetadataToken before doing the check.

/cc @AtsushiKan

**Comment by karelz** [comment]
@AtsushiKan @DnlHarvey @joshfree can you please triage milestone?
