### ISSUE TITLE
Making a member virtual should be considered a breaking change

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/corefx#19861]
The [breaking change document](https://github.com/dotnet/corefx/blob/d2a2d7ccb631aeaf97dc67b2241410b312241343/Documentation/coding-guidelines/breaking-change-rules.md) currently considers making a member virtual a non-breaking change with a small sidenote. When that rule was decided, the C# compiler was only emitting `call` IL instruction in a couple places that didn't really matter and used the IL `callvirt` for everything else (even if the destination instance method was non-virtual, because per the C# spec, calling instance methods with a null `this` needs to throw and `call` IL instruction won't throw). This made it unlikely that people would hit problems with it.

The addition of the null-propagation operator gave the C# compiler more opportunities to optimize `callvirt` into a `call` if the `this` is known to be not null.

dotnet/corert#3565 has an example where making a member virtual resulted in wrong method being called when compiling against PCL contracts because a breaking change was made making `ConstructorInfo.Invoke` virtual:

```csharp
var abc = (ABC) constr.Invoke(new object[0]); // This works
```

```csharp
var abc = (ABC) constr?.Invoke(new object[0]); // This calls the wrong method because
                                               // `this` is known not to be null and Invoke
                                               // is a non-virtual method
```

Making a member virtual is a breaking change for anyone using the null-propagation operator with the method.

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/pull/18138

**Comment by karelz** [comment]
Next step: We need PR with right wording ...
