### ISSUE TITLE
Remove SkipOnTargetFramework UAP/UAPAOT on whole classes

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#19871]
Skip only tests which are runnable on UAP/UAPAOT for either reasons:
- Win32Api not yet available
- Execution not possible because of AppContainer isolation

If the test tries to access the FileSystem outside of the whitelisted places (appx installation dir, appx temp dir --> %appdata%, capabilities --> pictures,documents,music,...) then rewrite test cases with TempDirectory.

**Comment by danmosemsft** [comment]
@ViktorHofer as far as I can see this doesn't track anything specifically? we ar etracking individual issues .
