### ISSUE TITLE
Assembly.Load currently not suppported on UWP

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#19872]
LoadFile / Load is currently intentionally blocked in Coreclr: https://github.com/dotnet/coreclr/blob/906f60ce3c55ab0cc41765d9eeea542ec65ff737/src/mscorlib/src/System/AppDomain.cs#L393

Will it be supported inside an AppContainer? If yes, re-enable deactivated tests.

**Comment by danmosemsft** [comment]
This one is already tracked by https://github.com/dotnet/coreclr/issues/9914 actually :)
