### ISSUE TITLE
SqlDbType exists both in NetStandard and System.Data.SqlClient 

### ISSUE THREAD

**Issue by RickStrahl** [dotnet/corefx#19882]
When using SqlDbType in .NET Core 2.0 SqlDbType errors with:

![image](https://cloud.githubusercontent.com/assets/1374013/26146341/add2c5e2-3aa4-11e7-8efc-0b44d538a801.png)

The type exists both in System.Data.SqlClient and .NET Standard, so the Sql Client version probably has to be removed.

**Comment by karelz** [comment]
@weshaggard @danmosemsft any advice?

**Comment by weshaggard** [comment]
This is expected and a side-effect of moving some of the SQL Types (particularly to support DataTable) into netstandard. To fix you need to reference the latest version prerelease version of the SqlClient package when consuming it from a netstandard 2.0 project.

**Comment by karelz** [comment]
OK, that makes sense to me. Closing as addressed.
@RickStrahl if you disagree or if you have more concerns regarding the end-to-end behavior, please let us know ASAP and we can reopen & continue the discussion. Thanks!

**Comment by RickStrahl** [comment]
Looks good with preview package (4.4.0-preview1-25305-02). Thank you.

Only outstanding issue on the System.Data bits for me is `DbProviderFactories` - Quite a few  places where this breaks for me. Specifically `GetFactory()`.

**Comment by karelz** [comment]
That should be addressed in PR #19825 by @FransBouma. If you think there's more, please let us know ASAP.

**Comment by FransBouma** [comment]
@karelz @RickStrahl DbProviderFactories is planned for today. I'll add that to the PR #19826, as the line of code in that PR is solely there because of that class.

**Comment by FransBouma** [comment]
@karelz #19825 and #19826 are both needed for DbProviderFactories, hence I added them. One is labeled for 2.0.0 (#19825) and one is labeled for 2.1.0 (#19826). I know you all are swamped right now, hence my plan to commit to 19826, or is it better to commit to 19825? As one will make it be added 2.0.0 and the other will make it be delayed to 2.1.0...

**Comment by karelz** [comment]
@saurabh500 can you please advise which change is must-have for 2.0 and how best to move forward here?

**Comment by 6heads** [comment]
> 
> 
> This is expected and a side-effect of moving some of the SQL Types (particularly to support DataTable) into netstandard. To fix you need to reference the latest version prerelease version of the SqlClient package when consuming it from a netstandard 2.0 project.

It's Q2 2019 and I still need to use a prelease to fix this issue. What's going on here?

**Comment by danmosemsft** [comment]
@6heads which package version are you referencing?
