### ISSUE TITLE
Confirm stability of new Perf.Environment tests

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/corefx#19892]
We checked in new tests in this PR, https://github.com/dotnet/corefx/pull/19623.  The tests appear to be good, but we should ensure that over the next week we are seeing stable results from these tests.

**Comment by stephenmichaelf** [comment]
@DrewScoggins 

Thanks for tracking this, I will check again in a week.

A few questions:

1. You ran a command to test perf "in the lab", where are those results?
2. Does this mean perf tests only run when specifically requested and not on every build/test run?
3. What is the longer term plan here? There are many other classes that need to be tested for System.Runtime.Extensions as well as for many other areas of the code. How are we going to scale this to make sure all new performance tests are stable and useful? Perhaps we can set up the output to write somewhere externally so we can easily see trends over time?
4. Should I tag you in all perf tickets in the future? If so I can update the perf testing documentation so others know.

Thanks!

**Comment by DrewScoggins** [comment]
> 1. You ran a command to test perf "in the lab", where are those results?

Sadly right now this is not viewable outside Microsoft.  We are currently working on bringing this site up publicly, but we have not finished yet.

> 2. Does this mean perf tests only run when specifically requested and not on every build/test run?

We run tests in CoreFX on every commit as well as when you request a perf run in a PR comment

> 3. What is the longer term plan here? There are many other classes that need to be tested for System.Runtime.Extensions as well as for many other areas of the code. How are we going to scale this to make sure all new performance tests are stable and useful? Perhaps we can set up the output to write somewhere externally so we can easily see trends over time?

We at this point have not thought too deeply about how we want to do onboarding of new tests, as we have been mostly focused on getting the infrastructure in place and getting results.  We currently are doing some work to automate looking for noisy tests, and this will likely be a good start to making the confirmation of stability easier.

> 4. Should I tag you in all perf tickets in the future? If so I can update the perf testing documentation so others know.

Please tag @dotnet/rap-team as that will hit everyone on our team.
