### ISSUE TITLE
Add support to System.Runtime.InteropServices.RuntimeInformation to determine what the currently executing framework is

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#19927]
We have a couple of places where we would like to run platform specific code without having to cross-compile. Essentially the same thing as https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/PlatformDetection.cs#L21. However using `RuntimeInformation.FrameworkDescription` seems fragile. Would it make sense to expose an API similar to `RuntimeInformation.IsOSPlatform` here i.e. `RuntimeInformation.IsFramework`?

**Comment by pranavkm** [comment]
cc @Eilon \ @natemcmaster

**Comment by svick** [comment]
I think this is a subset of https://github.com/dotnet/corefx/issues/16629.

**Comment by pranavkm** [comment]
@svick - fair enough. @weshaggard has an API suggestion in there `AppContext.TargetFrameworkName` which would've been useful, unfortunately that returns an empty string. I'll follow up with him on this.

**Comment by pranavkm** [comment]
Closing as dup of https://github.com/dotnet/corefx/issues/16629.
