### ISSUE TITLE
System.Security.PermissionSet

### ISSUE THREAD

**Issue by hugosmarques** [dotnet/corefx#19929]
im getting the following error System.TypeLoadException: 'Could not load type 'System.Security.PermissionSet' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.'
When i try to open a MySqlConnection with .Net Core 2. Did you know why?

**Comment by danmosemsft** [comment]
Hi @hugosmarques exactly how did you install? What is in your .csproj? What is "dotnet --version"?

@weshaggard

**Comment by hugosmarques** [comment]
im using the .Net Core 2.0 preiew and i install MySQL .Net Core 6.9.9

**Comment by hugosmarques** [comment]
dotnet --version
2.0.0-preview1-005977

**Comment by hugosmarques** [comment]
csproj
<ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>  
  
  <ItemGroup>

    <PackageReference Include="AWSSDK.Core" Version="3.3.14" />

    <PackageReference Include="AWSSDK.S3" Version="3.3.6.1" />

    <PackageReference Include="Log4Slack" Version="1.1.9" />

    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.1.0-beta4" />

    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="1.1.2" />

    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="2.0.0-preview1-final" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.0.0-preview1-final" />

    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.0-preview1-final" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="2.0.0-preview1-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.0.0-preview1-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="2.0.0-preview1-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="2.0.0-preview1-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="2.0.0-preview1-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.0.0-preview1-final" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.0.0-preview1-final" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="2.0.0-preview1-final" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.1" />

    <PackageReference Include="Amazon.Lambda.Core" Version="1.0.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="0.10.1-preview1" />
    <PackageReference Include="Amazon.Lambda.Logging.AspNetCore" Version="1.0.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="5.1.3" />
    <PackageReference Include="MySql.Data" Version="6.7.9" />
    <PackageReference Include="System.Data.Common" Version="4.3.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.1.3" />
    <PackageReference Include="System.Linq" Version="4.3.0" />
    <PackageReference Include="System.Linq.Expressions" Version="4.3.0" />
    <PackageReference Include="System.Security.Permissions" Version="4.4.0-preview1-25305-02" />
    <PackageReference Include="System.Text.Encodings.Web" Version="4.4.0-preview1-25305-02" />
  </ItemGroup>

**Comment by hugosmarques** [comment]
the code where the error occur:

MySqlConnection connection = new MySqlConnection
            {
                ConnectionString = "server=xxxxxxxxxxx;user id=admin;password=xxxxxxxxxx;persistsecurityinfo=True;port=xxxx;database=xxxxxxxx"
            };

            connection.Open(); (Error here when try to open the connection)

**Comment by weshaggard** [comment]
@hugosmarques what TargetFramework do you have set in your project? Do you have an mscorlib.dll in your application output or the shared framework you are running on?

**Comment by hugosmarques** [comment]
.Net Core 2.0

**Comment by hugosmarques** [comment]
@weshaggard I don't add the mscorlib.dll manually probably comes with other package I don't know

**Comment by weshaggard** [comment]
OK I was able to repro this locally. You actually hit upon a couple different bugs one is a nuget bug https://github.com/NuGet/Home/issues/5192 and the other is a package configuration issue in System.Security.Permissions package. While the configuration isn't necessarily wrong the nuget bug make it end up picking the wrong asset from that package and causing it to fail to load, if we configured differently we could have avoided the issue. I filed corefx issue https://github.com/dotnet/corefx/issues/19949 to track that.

Now for your project. You can workaround parts of the references you gave but not all. I was able to get a basic mysql project to work by updating the package version from 6.7.9 to 6.10.1-beta which supports netstandard directly instead of relying on the compat shims. You probably also want to remove your reference to System.Security.Permissions package which will not work with the nuget issue.

Give that a try and see how far you can get.

**Comment by hugosmarques** [comment]
@weshaggard thanks for your answer. I know that the workaround works. With the version  6.10.1- works, the problem is that wit this MySQL version i dont have access to MySQLDataReader! i don't know why, even in the last pre-release of the MySQL the MySQLDataREader is nor present... you know why? Right now i need to work the MySQL version 6.9.9 but with this version i have the error that i sent already....

**Comment by weshaggard** [comment]
>With the version 6.10.1- works, the problem is that wit this MySQL version i dont have access to MySQLDataReader

That I don't know, that would be for the mysql folks.

Depending on your scenario you could hack around this problem by deleting the runtimes folder under your nuget package cache for `C:\Users\<user>\.nuget\packages\System.Security\Permissions\4.4.0-preview1-25305-02`. This is a hack and if you ever restore the package again from a clean cache or another machine you will hit the problem again. Beyond that I don't have any good workarounds.

**Comment by hugosmarques** [comment]
@weshaggard ok, bt when this error is fixed will work without problems right?

**Comment by hugosmarques** [comment]
Anyone have a workaround in order to proceed with my tests?

**Comment by weshaggard** [comment]
I'm not really aware of any good workaround with the preview1 bits. With PR https://github.com/dotnet/corefx/pull/19989 the System.Security.Permissions package should work however I think you will then immediately hit the DbDataPermission issue. That could also be fixed by taking our nightly preview2 bits. Once we get https://github.com/dotnet/corefx/pull/19989 merged and a package for that I will try your repro locally again to see if I can get Open to at least work.

**Comment by hugosmarques** [comment]
@weshaggard hello. As i can see @ericstj make a commit. Did you already have a package?

**Comment by weshaggard** [comment]
So I did a little more playing with this late Friday and while I think we can get the basic scenarios working it will require you to start dogfooding the latest tools (https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md). You will essentially need a few fixes that are post the preview1 builds, and one more PR https://github.com/dotnet/corefx/pull/20029 that has yet to be merged, I'm going to work on getting that merged today.

Are you OK using our nightly builds if I point you at the right packages when they are ready?

As a disclaimer I was able to hack around locally and get the basic connection.Open() working but the MySql.Data library does still have some references that are not supported in .NET Core and so if you hit any of those code paths at runtime this scenario will become blocked. While .NET Core 2.0 added a lot of the .NET Framework APIs it doesn't support everything so consuming a .NET Framework binary like this will only work for APIs that exist in .NET Core. The best path to pursue is to get to request the mysql data library folks to support a .NET Standard or .NET Core version of their library.

**Comment by hugosmarques** [comment]
@weshaggard off course. As I said before I'm testing so please send me the nightly builds when ready. MySQL already have a version for .Net Core, I think that some features are not available yet like DataAdapter because the last version ( current version) of .net core does not have datatables... I think that with the version 2 of .net core MySQL will add more and more features.

**Comment by weshaggard** [comment]
OK let me get https://github.com/dotnet/corefx/pull/20029 merged today and have it build a package tonight and I then will send you a set of instructions to try and consume our nightly builds to get this working.

**Comment by hugosmarques** [comment]
@weshaggard one last question. Did you have an idea when the .net core 2 will be a LTS version? I need to know, because Amazon only use LTS versions on there AWS Lambda functions.

**Comment by weshaggard** [comment]
>@weshaggard one last question. Did you have an idea when the .net core 2 will be a LTS version? I need to know, because Amazon only use LTS versions on there AWS Lambda functions.

@hugosmarques that is a question I don't know the answer too yet. @leecow any ideas on that?

**Comment by leecow** [comment]
The LTS decision is still to be made. @hugosmarques - can you link to the LTS requirement for AWS Lambda?

**Comment by hugosmarques** [comment]
You can find in many blogs.. here an example
https://github.com/aws/aws-lambda-dotnet/issues/36

**Comment by hugosmarques** [comment]
@weshaggard and @leecow do you have news?

**Comment by weshaggard** [comment]
@hugosmarques OK we have a nightly build that I believe will get you unblocked (or at least to the next stage).

You will need to pick-up build `2.1.0-preview1-25323-04`. Following the dogfooding instructions at https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md you will either need to install (https://dotnetcli.blob.core.windows.net/dotnet/Runtime/2.1.0-preview1-25323-04/dotnet-runtime-2.1.0-preview1-25323-04-win-x86.exe) it globally or you will need to publish it as https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md#option-2-self-contained. 

You will need to set the following property in your project:
` <RuntimeFrameworkVersion>2.1.0-preview1-25323-04</RuntimeFrameworkVersion>`

you will also need to reference the following packages:
```
    <PackageReference Include="System.Security.Permissions" Version="4.5.0-preview1-25323-02" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.5.0-preview1-25323-02" />
    <PackageReference Include="System.Text.Encodings.Web" Version="4.5.0-preview1-25323-02" />
```

With that I believe you will get past the connection.Open() command successfully. Please let me know if you hit other issues afterwards.

Note that this build is from our nightly master builds which is targeting 2.1. I believe all the necessary fixes have been ported to our 2.0 release branches as well so once we get a build from there with all the fixes I can point you at the build.

**Comment by hugosmarques** [comment]
@weshaggard when i try to run dotnet restore im receiving the following error

C:\Program Files\dotnet\sdk\2.0.0-preview2-006127\NuGet.targets(98,5): error : Unable to resolve 'Microsoft.NETCore.App (>= 2.1.0-preview1-25323-04)' for '.NETCoreApp,Version=v2.0'. [C:\Users\hugo.marques\Documents\adigitalbook\sunpics\adigitalbook_core_api\adigitalbook_core_api.csproj]

**Comment by hugosmarques** [comment]
@weshaggard 
dotnet --version
2.0.0-preview2-006127

**Comment by hugosmarques** [comment]
@weshaggard 
dotnet --info
.NET Command Line Tools (2.0.0-preview2-006127)

Product Information:
 Version:            2.0.0-preview2-006127
 Commit SHA-1 hash:  946ea7980a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006127\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-25323-04
  Build    : df3188dafac88dd371ef26fda22e4f1f43adeb5f

**Comment by weshaggard** [comment]
@hugosmarques do you have `<add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />` in your nuguet.config? You will need to use our nightly feed to consume that package.

**Comment by hugosmarques** [comment]
@weshaggard i add the key but the error continue

mu  nuget.config file:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
	<add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
  </solution>
</configuration>

**Comment by hugosmarques** [comment]
[NuGet.zip](https://github.com/dotnet/corefx/files/1026347/NuGet.zip)

**Comment by weshaggard** [comment]
Your nuget.config needs to look something like:
```
<configuration>
  <packageSources>
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by hugosmarques** [comment]
@weshaggard it works now. I already debug the project and now when i open the mysqlconnection the following error appear:

{System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
   at MySql.Data.MySqlClient.MySqlConnectAttrs.get_OSDetails()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at MySql.Data.MySqlClient.NativeDriver.SetConnectAttrs()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.Authenticate(Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at ArealMedia.DAL.DbProviderBase.ConnectionOpen() in C:\Users\hugo.marques\Documents\adigitalbook\sunpics\adigitalbook\code\ArealMedia.DbManager\Providers\DbProviderBase.cs:line 108}

**Comment by weshaggard** [comment]
Great to see you make it further however this is kind of what I was hinting at in my earlier comments about hitting something that isn't supported on .NET Core. System.Management is not something we currently have an implementation for in .NET Core so there isn't any good way to fill that gap. There is a request for it (https://github.com/dotnet/corefx/issues/14762) but I don't know if or when that will get ported. 

I still feel the best course of action is to try and get the .NET Standard/.NET Core version of mysql library working for your needs, or getting the owners to update it as needed. I'm also trying to see if I can find out the owners offline to see if they can update the library.

**Comment by hugosmarques** [comment]
I appreciate that. MySQL .net core does not have DataAdapter and I don't know why...

**Comment by weshaggard** [comment]
@hugosmarques I don't think there is anything else really actionable on this issue so I'm going to close it. If I get any further information about an update mysql I will post it here.

**Comment by hugosmarques** [comment]
@weshaggard did you have an explanation for the fact that Mysql works fine with .net core 1?

**Comment by weshaggard** [comment]
>@weshaggard did you have an explanation for the fact that Mysql works fine with .net core 1?

The library you are trying to consume here most definitely won't work on .NET Core 1.0 or 1.1, it has a lot of dependencies that aren't present. The beta netstandard version of the library will likely work on both 1.0 and 2.0 but as you point out it has some missing features.

**Comment by hugosmarques** [comment]
@weshaggard hello. Did you already have an answer from the fact that MySQL .NEt Core does not have the MySQLAdapter.

**Comment by hugosmarques** [comment]
@leecow did you have an idea if .NET core 2 will be a LTS

**Comment by leecow** [comment]
@hugosmarques - Something we're working on it and that's the target.

**Comment by weshaggard** [comment]
>Did you already have an answer from the fact that MySQL .NEt Core does not have the MySQLAdapter.

Sorry I don't, have any contacts for the mysql folks. @bleroy is trying to see if he can get in contact with them.
