### ISSUE TITLE
Update NETStandard.Library to reference System.Net.Http 4.3.2

### ISSUE THREAD

**Issue by danroth27** [dotnet/corefx#19936]
When I create an ASP.NET Core 1.1 app that uses Azure SDK libraries to talk to Azure Key Vault and Azure AD on .NET 4.6.2 I get the following error:

```
System.TypeLoadException: Inheritance security rules violated by type: 'System.Net.Http.WebRequestHandler'. Derived types must either match the security accessibility of the base type or be less accessible.
   at Microsoft.Rest.ServiceClient`1.CreateRootHandler()
   at Microsoft.Azure.KeyVault.KeyVaultClient..ctor(ServiceClientCredentials credentials, DelegatingHandler[] handlers)
   at AspNetCoreIdentityServiceTest.Startup.<<Configure>b__6_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

Which was fixed by https://github.com/dotnet/corefx/issues/11100. I can get the error to go away by directly referencing System.Net.Http 4.3.2.

Looking at my assets.json file it looks like NETStandard.Library 1.6.1 is pulling in the older version of System.Net.Http. Can we update NETStandard.Library to pull in the newer fixed version of System.Net.Http? Presumably we would then need to update the ASP.NET Core 1.1 packages.

https://github.com/dotnet/standard/issues/354 tracks the similar issue for NETStandard.Library 2.0.0.

@ericstj @DamianEdwards @Eilon @karelz

**Comment by ericstj** [comment]
We can but the POR thus far has been to not update NETStandard.Library in servicing.  Upstack packages (or applications) which care about the individual fixes can reference the individual libraries.

This issue is about changing the POR so that libraries and applications have an "entry point" package update that provides servicing fixes.

**Comment by danroth27** [comment]
> We can but the POR thus far has been to not update NETStandard.Library in servicing.

Is there any justification for that POR? Wouldn't we want new libraries to get these fixes without having to manually add them?

**Comment by ericstj** [comment]
IIRC the justification was that the NETStandard.Library package would only track the NETStandard.Library surface area where major.minor mapped to the version of netstandard, and revision mapped to a release wave of the whole product and was only used to get packages to lineup on the same version for a release wave.  You can see some more background in the discussion for https://github.com/dotnet/corefx/issues/15735.

I think the place where this matters the most is desktop, where the revision determines whether or not you get bugfixes for any of the OOB packages that constitute netstandard.

This can actually cause potential issues on NETCoreAPP.  Suppose we release a new version of NETStandard.Library that references newer versions than were inbox in Microsoft.NETCore.App 1.1.  Folks will start to see those libraries copied app-local when referencing the new NETStandard.Library.  So they will get fixes, but they'll also see their app grow and become un-crossgened.

**Comment by davidsh** [comment]
Based on the lastest POR, the current behavior will remain as-is.  Closing issue.
