### ISSUE TITLE
Msbuild not defining TargetGroup property for uap when building for uap or uap-aot

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#19942]
I'm trying to do this in a CSPROJ file:

```
<DefineConstants Condition="'$(TargetGroup)' == 'uap'">$(DefineConstants);uap</DefineConstants>
```

But when I build either:
>msbuild /t:rebuildandtest /p:TargetGroup=uap

or

>msbuild /t:rebuildandtest /p:TargetGroup=uapaot

The `TargetGroup` property is not defined either 'uap' or 'uapaot'.

I would expect it to be defined as 'uap' whether it is 'uap' or 'uapaot' TargetGroup.  Instead, it is not being defined properly.

**Comment by davidsh** [comment]
cc: @danmosemsft @AlexGhiondea @ViktorHofer

**Comment by davidsh** [comment]
I noticed that TargetGroup is being defined as 'netstandard' even though I am defining it as 'uap' or 'uap-aot'

**Comment by danmosemsft** [comment]
Which library is this? If there is no uap/uapaot configuration explicitly in Configuration.props, perhaps the TargetGroup is netstandard.

**Comment by davidsh** [comment]
I observed it in src/System.Net.Http/tests/UnitTests when building those tests.  The Configuration.props doesn't have any 'uap' or 'uap-aot' configurations.  So, maybe that is the problem.

I do see that in src/System.Net.Http/src there is a Configuration.props that has this defined:

> uap-Windows_NT;

I will investigate and close this issue is that is the problem with Http unit tests project. Thx.

**Comment by davidsh** [comment]
Yes, that is the problem.  We need to add "uap-Windows_NT;" to the configuration file.
