### ISSUE TITLE
Avoid having runtime specific assets when they aren't necessary.

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#19949]
Due to an issue in nuget which will hopefully be address with https://github.com/NuGet/Home/issues/5192 some of our packages end up with the wrong asset being selected when we have both runtime and lib assets in the package. For some of our packages that isn't necessary.

Example: System.Security.Permissions has a runtime\net461 asset and a lib\netstandard2.0 asset and when a netcoreapp2.0 project has a fallback of net461 we will prefer the net461 asset over the netstandard2.0 asset which will not work on netcoreapp2.0. See https://github.com/dotnet/corefx/issues/19929. 

We should do an audit of other packages in this situation to avoid it.

**Comment by ericstj** [comment]
As we discussed the duplicated asset is completely unnecessary.  This situation was less likely in 1.0 due to the way we had factored projects but became more likely in 2.x because the config system made it easy.

**Comment by ericstj** [comment]
Reopen for rel/2.0
