### ISSUE TITLE
Unix throws the wrong exception creating a FileStream

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#19965]
Same underlying issue as #19850. Need to update CoreLib to throw DirectoryNotFound if the directory doesn't exist. (`/directory/doesnotexist/doesnotexist`)

**Comment by JeremyKuhne** [comment]
Corelib is updated, need to remove the skips when we take the next drop.

**Comment by karelz** [comment]
Reopening to track port to rel/2.0.0 branch.

**Comment by stephentoub** [comment]
@karelz, the fix is already in the rel/2.0 branch, right? The only thing I did and that closed this was re-enabling tests.  You're reopening this to track re-enabling those tests in 2.0 as well?

**Comment by karelz** [comment]
I don't see any PR in this issue against rel/2.0.0 branch. If there is one, let's link them properly.

**Comment by karelz** [comment]
I let you as experts decide if we need to re-enable the tests in rel/2.0.0 branch. If there is value, I'd suggest to do it.

**Comment by JeremyKuhne** [comment]
I'll open a separate issue for porting the test.

dotnet/coreclr#11757 fixed this in CoreCLR for master.
dotnet/coreclr#11807 ported the CoreCLR fix.
