### ISSUE TITLE
How do I generate Nuget package for an assembly in CoreFx

### ISSUE THREAD

**Issue by saurabh500** [dotnet/corefx#19974]
I am trying to create a Nuget package in CoreFx for System.Data.SqlClient using build-packages.cmd
However that only creates the packages for Microsoft.* .nupkg

How do I go about creating a package for System.Data.SqlClient or any other assembly?

**Comment by davidsh** [comment]
cc: @weshaggard 

Individual NuGet packages for each library are no longer produced except for a few ones.  Aggregate NuGet packages are created instead containing many libraries.  @weshaggard and @ericstj can explain more.

**Comment by ericstj** [comment]
SqlClient still has a package.  If you just want to build its package you can directly build the pkgproj.  If you'd like yo build all packages you can run build -allConfigurations from the root. You can use build-packages -allConfigurations, but that assumes you have done at least one build -allConfigurations from the root.
