### ISSUE TITLE
[HttpListener] [Managed] HttpListenerResponse should set properties directly in the Headers property on set/get

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#19972]
Causes the following test failures:

- [x] ContentType_SetAndSend_Success
- [x] ContentType_SetNullEmptyOrWhitespace_ResetsContentType
- [x] RedirectLocation_SetAndSend_Success
- [x] RedirectLocation_SetNullOrEmpty_ResetsRedirectLocation
- [x] Redirect_Invoke_SetsRedirectionProperties
- [x] KeepAlive_ContentLengthBoundaryAndRequestHttpVersionMinorIsZero_DoesNotChangeWhenSendingHeaders

**Comment by stephentoub** [comment]
The first three have been fixed.
The latter three still remain disabled on Unix.
