### ISSUE TITLE
[HttpListener] [Managed] Reading from a closed connection should throw HttpListenerException

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#19983]
Following tests are disabled with this issue:

- Read_FromClosedConnectionAsynchronously_ThrowsHttpListenerException
- Read_FromClosedConnectionSynchronously_ThrowsHttpListenerException

**Comment by karelz** [comment]
@stephentoub can you please drop 1 line with "why Future is ok" for this issue? (I don't have any context to have opinion either way)

**Comment by stephentoub** [comment]
My take: it's corner case and doesn't affect mainline behavior.  Basically rather than an exception being thrown, it just returns that it read 0 bytes, which code would already need to be able to handle and essentially means the same thing.

**Comment by karelz** [comment]
Thanks! That makes sense.

**Comment by caesar1995** [comment]
These two tests are not disabled anymore. They are throwing HttpListenerException when reading from a closed connection.
https://github.com/dotnet/corefx/blob/master/src/System.Net.HttpListener/tests/HttpRequestStreamTests.cs#L603

Seems this issues has been fixed. Please re-open it if there is a repro.
