### ISSUE TITLE
[Managed bug] HttpListenerRequest.Read with chunked input should align with Windows behaviour

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#19984]
Following tests are disabled with this issue:

- Read_LargeLengthAsynchronous_Success
- Read_LargeLengthSynchronous_Success

**Comment by Priya91** [comment]
@stephentoub Do we need to match the windows behavior in this case? On windows http.sys imposes limit that each read cannot be of buffer size greater than 128k [here](https://github.com/dotnet/corefx/blob/master/src/System.Net.HttpListener/src/System/Net/Windows/HttpRequestStream.Windows.cs#L65). I'm not sure why it has that limitation, but on managed we don't have such restrictions.

**Comment by stephentoub** [comment]
No, we don't need to artificially constrain the amount of data you can read in a single call.

**Comment by Priya91** [comment]
This issue as by-design.. @hughbe please re-enable test as per expected behavior..

**Comment by karelz** [comment]
@stephentoub do we want this one also ported to 2.0? (I can add it to the uber porting issue)

**Comment by stephentoub** [comment]
Yes. Basically every change that's affected HttpListener; they're all in the same bucket.

**Comment by karelz** [comment]
Makes sense, updated the to-be-ported list in https://github.com/dotnet/corefx/issues/20060#issuecomment-302956042

**Comment by stephentoub** [comment]
The list is really just everything here staring from the 17th:
https://github.com/dotnet/corefx/commits/master/src/System.Net.HttpListener

**Comment by karelz** [comment]
Great, once we port all those, we should chase down the original bugs and make sure they are in 2.0 milestones and have the port PR linked ...
