### ISSUE TITLE
[HttpListener] [Managed] HttpListenerResponseStream should validate how much or little we write

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#19981]
Following tests are disabled with this issue:

- Write_TooMuch_ThrowsProtocolViolationException
- Write_TooLittleAsynchronouslyAndClose_ThrowsInvalidOperationException
- Write_TooLittleSynchronouslyAndClose_ThrowsInvalidOperationException

**Comment by stephentoub** [comment]
Same as #20201
