### ISSUE TITLE
[Managed bug] HttpListenerRequest.EndRead should validate the IAsyncResult

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#19985]
Following tests are disabled with this issue:

- EndRead_InvalidAsyncResult_ThrowsArgumentException
- EndRead_CalledTwice_ThrowsInvalidOperationException

**Comment by danmosemsft** [comment]
@hughbe can you please set area path label and disabled test label where appropriate?

**Comment by hughbe** [comment]
I don't think I can do that myself - I don't have permissions

**Comment by karelz** [comment]
Correct, labels can be changed only by people who have RW permission to entire repo :( ... giving such permissions (incl. code base) to non-MS people is legally challenging for Microsoft :(

We need to push on GitHub to allow specific permissions to change labels - we could give it to a few trusted contributors then.
