### ISSUE TITLE
Desktop: System.Tests.Environment_Exit.ExitCode_VoidMainAppReturnsSetValue failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#19995]
Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/netfx_windows_nt_debug_prtest/453/System.Tests/Environment_Exit/ExitCode_VoidMainAppReturnsSetValue_mode__1_/

MESSAGE:
~~~
Assert.Equal() Failure
  Expected: 123
  Actual: 3
~~~
STACK TRACE:
~~~
at System.Tests.Environment_Exit.ExitCode_VoidMainAppReturnsSetValue(Int32 mode) 
in D:\j\workspace\netfx_windows---8c0e8fba\src\System.Runtime.Extensions\tests\System\Environment.Exit.cs:line 76
~~~

**Comment by stephentoub** [comment]
Why did this test run?  It's marked [ActiveIssue]:
https://github.com/dotnet/corefx/blob/0ebc867d6bad9d777dd61afb78d0445c86143b34/src/System.Runtime.Extensions/tests/System/Environment.Exit.cs#L52

cc: @safern

**Comment by safern** [comment]
Will take a look.

**Comment by safern** [comment]
The tests are not running. The failure that @Jiayili1 is pointing out is for a CI leg in PR: #19232 which is actually enabling this tests. This test is not running in official builds. 

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/lastCompletedBuild/testReport/
