### ISSUE TITLE
Simple name conflict resolution is not working for NETStandard.Library.NETFramework

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#20015]
Originally reported here: https://github.com/dotnet/standard/issues/355

Conflict resolution does not try to resolve conflicts between simple name references because it does not attempt to duplicate assembly search path probing done by RAR.

The SDK does removal of simple name references that overlap with nuget packages.  This is "good enough" in most cases.

The problem is that the NETStandard.Library.NETFramework package does not populate its references in a way that plugs into the SDK's logic.  Instead we provide the references from targets.  The reason for this is we need to hide these references from NuGet for the packages.config case: we don't want a packages.config project getting 100s of references added to its csproj.

Taking the SDK out of the picture, we have the exact same simple-name conflict problem for packages.config.

To fix this I propose the following:
1. We add a target to the NETStandard.Library.NETFramework project that removes simple name references that overlap with references added by our package, similar to https://github.com/dotnet/sdk/blob/1d81050cab00c6f9ab8bf5b984bc42eff2760c1e/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.PackageDependencyResolution.targets#L375.
2. In a packages.config project we make sure this runs before RAR.  The only source of references is the users project file.
3. In a PackageReference project we make sure this runs after `ResolveLockFileReferences`.  References may have come from user's project or nuget packages.
4. In a project.json project we make sure this runs after `ResolveNuGetPackageAssets`.  References may have come from user's project or nuget packages.

We can examine target sequencing to see if there is any way to accomplish 2-4 with a single target sequencing.

/cc @weshaggard @dsplaisted @natemcmaster

**Comment by ericstj** [comment]
Reopening for port to 2.0.0

**Comment by karelz** [comment]
Fixed in #20249 in rel/2.0.0 branch
