### ISSUE TITLE
Behavior difference between CoreFX and desktop WRT IO and symlinks

### ISSUE THREAD

**Issue by kumpera** [dotnet/corefx#20020]
CoreFX handles symlink loops differently that desktop dotnet.

On desktop, it throws UnauthorizedAccessException if you try to do any IO (such as File.Open) on such scenario.

I'm not 100% CoreFX handle the windows case correctly, but I'm positive it doesn't in unix case as that scenario gets you an ELOOP and GetExceptionForIoErrno doesn't handle it.

**Comment by mellinoe** [comment]
> I'm positive it doesn't in unix case

I guess you are referring to the mono implementation here?

**Comment by kumpera** [comment]
Mono now has the same behavior as dotnet desktop.
CoreFX (thus Dotnet Core) doesn't.

I found this, in fact, while fixing mono.

**Comment by stephentoub** [comment]
@kumpera, can you please share a repro for desktop?  I'm unable to get it to throw an UnauthorizedAccessException.  Here's an example:
```C#
using System;
using System.Diagnostics;
using System.IO;

class Program
{
    static void Main()
    {
        const int NumLinks = 32;

        string path1 = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        string orig = path1;
        File.Create(path1).Dispose();

        for (int i = 1; i <= NumLinks; i++)
        {
            string path2 = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
            CreateSymbolicLink(path2, path1);
            Console.WriteLine($"Created link from {path2} to {path1}");
            path1 = path2;
        }

        //File.Delete(orig);
        //CreateSymbolicLink(orig, path1);

        try
        {
            Console.WriteLine($"Opening {path1}");
            File.OpenRead(path1).Dispose();
            Console.WriteLine("No exception");
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
        }
    }

    public static void CreateSymbolicLink(string linkPath, string targetPath)
    {
        using (var symLinkProcess = new Process())
        {
            symLinkProcess.StartInfo.UseShellExecute = false;
            symLinkProcess.StartInfo.FileName = "cmd";
            symLinkProcess.StartInfo.Arguments = $"/c mklink \"{linkPath}\" \"{targetPath}\"";
            symLinkProcess.StartInfo.RedirectStandardOutput = true;
            symLinkProcess.Start();

            symLinkProcess.WaitForExit();
            if (symLinkProcess.ExitCode != 0) throw new Exception("couldn't create symlink: " + symLinkProcess.ExitCode);
        }
    }
}
```
On my system at least, for any NumLinks value >= 32, it throws:
```
System.IO.IOException: The name of the file cannot be resolved by the system.
```
For any NumLinks value < 32, no exception is thrown.  And if I uncomment the two lines that create a loop rather than just a really long chain, it still throws the same IOException.

**Comment by kumpera** [comment]
Hey @stephentoub, after looking carefully, there's something awfully wrong with my windows setup as mklink itself is failing for me now.

Windows won't let me create a symlink on my Documents folder <o>.

Besides that, your test verify link depth and not link cycles, not that it matter.

For cycles you'd do something like this:

```
CreateSymbolicLink ("a", "b");
CreateSymbolicLink ("b", "a") ;
```

**Comment by stephentoub** [comment]
> Besides that, your test verify link depth and not link cycles, not that it matter.

I actually mentioned that... it does both, you just need to uncomment the two lines in the middle that create a cycle:
"And if I uncomment the two lines that create a loop rather than just a really long chain, it still throws the same IOException."

**Comment by stephentoub** [comment]
> there's something awfully wrong with my windows setup as mklink itself is failing for me now.

Sorry to hear it.

How would you like to proceed?  Do you think the issue you were seeing is a result of your box being in disarray and this can be closed?  Or do you think there's a real issue here to pursue further?

Thanks for following up.

**Comment by kumpera** [comment]
I believe the best way to handle this one is to close it and I'll fix my setup and double check my early results.

**Comment by stephentoub** [comment]
Ok, thanks, sounds good.
