### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.ResponseStreamTest / ReadAsStreamAsync_ValidServerResponse_Success

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20024]
### The server returned an invalid or unrecognized response

Failure [20171216.02](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171216.02/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None)):
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : The server returned an invalid or unrecognized response
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext() in E:\A\_work\988\s\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 489
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.Functional.Tests.ResponseStreamTest.<ReadAsStreamHelper>d__9.MoveNext() in E:\A\_work\988\s\corefx\src\System.Net.Http\tests\FunctionalTests\ResponseStreamTest.cs:line 247
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.Functional.Tests.ResponseStreamTest.<ReadAsStreamAsync_ValidServerResponse_Success>d__8.MoveNext() in E:\A\_work\988\s\corefx\src\System.Net.Http\tests\FunctionalTests\ResponseStreamTest.cs:line 240
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in E:\A\_work\988\s\corefx\src\Common\src\System\Threading\Tasks\RendezvousAwaitable.cs:line 62
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext() in E:\A\_work\988\s\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 858
```

### The operation has been canceled

Failure [20171114.01](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171114.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None)):
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : The operation has been canceled
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext() in E:\A\_work\1272\s\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 489
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.Functional.Tests.ResponseStreamTest.<ReadAsStreamHelper>d__9.MoveNext() in E:\A\_work\1272\s\corefx\src\System.Net.Http\tests\FunctionalTests\ResponseStreamTest.cs:line 247
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.Functional.Tests.ResponseStreamTest.<ReadAsStreamAsync_ValidServerResponse_Success>d__8.MoveNext() in E:\A\_work\1272\s\corefx\src\System.Net.Http\tests\FunctionalTests\ResponseStreamTest.cs:line 240
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in E:\A\_work\1272\s\corefx\src\Common\src\System\Threading\Tasks\RendezvousAwaitable.cs:line 62
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext() in E:\A\_work\1272\s\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 858
```

### The handle is invalid

Failure [20171109.04](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171109.04/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20Chunked,%20transferError:%20None)):
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : The handle is invalid
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext() in E:\A\_work\1037\s\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 489
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.Functional.Tests.ResponseStreamTest.<ReadAsStreamHelper>d__9.MoveNext() in E:\A\_work\1037\s\corefx\src\System.Net.Http\tests\FunctionalTests\ResponseStreamTest.cs:line 247
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.Functional.Tests.ResponseStreamTest.<ReadAsStreamAsync_ValidServerResponse_Success>d__8.MoveNext() in E:\A\_work\1037\s\corefx\src\System.Net.Http\tests\FunctionalTests\ResponseStreamTest.cs:line 240
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Http.WinHttpException.ThrowExceptionUsingLastError() in E:\A\_work\1037\s\corefx\src\Common\src\System\Net\Http\WinHttpException.cs:line 44
   at System.Net.Http.WinHttpHandler.SetRequestHandleRedirectionOptions(SafeWinHttpHandle requestHandle) in E:\A\_work\1037\s\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 1082
   at System.Net.Http.WinHttpHandler.SetRequestHandleOptions(WinHttpRequestState state) in E:\A\_work\1037\s\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 956
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext() in E:\A\_work\1037\s\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 833
```

### IOException: The handle is in the wrong state for the requested operation

Failure [20171104.03](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171104.03/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20None,%20transferError:%20None)):
```
System.IO.IOException : The read operation failed, see inner exception.
---- System.Net.Http.WinHttpException : The handle is in the wrong state for the requested operation
   at System.Net.Http.WinHttpResponseStream.<ReadAsyncCore>d__22.MoveNext() in E:\A\_work\1388\s\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpResponseStream.cs:line 225
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.Functional.Tests.ResponseStreamTest.<ReadAsStreamHelper>d__9.MoveNext() in E:\A\_work\1388\s\corefx\src\System.Net.Http\tests\FunctionalTests\ResponseStreamTest.cs:line 253
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.Functional.Tests.ResponseStreamTest.<ReadAsStreamAsync_ValidServerResponse_Success>d__8.MoveNext() in E:\A\_work\1388\s\corefx\src\System.Net.Http\tests\FunctionalTests\ResponseStreamTest.cs:line 238
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
```

## History of failures

Day | Build | OS | Error message
-- | -- | -- | --
5/4 | 20170504.02 | Win10 | The server returned an invalid or   unrecognized response
5/6 | 20170506.02 | Win10 | The server returned an invalid or unrecognized response
5/9 | 20170509.02 | Win10 | The server returned an invalid or unrecognized response
5/11 | 20170511.02 | Win10 | The server returned an invalid or unrecognized response
5/13 | 20170513.01 | Win10 | The server returned an invalid or unrecognized response
5/13 | 20170513.02 | Win10 | The server returned an invalid or unrecognized response
5/21 | 20170521.01 | Win10 | The server returned an invalid or unrecognized response
5/28 | 20170528.01 | Win10 | The server returned an invalid or unrecognized response
6/14 | 20170614.03 | Win10 | The server returned an invalid or unrecognized response
6/22 | 20170622.02 | Win10 | The server returned an invalid or unrecognized response
7/11 | 20170711.03 | Win10 | The server returned an invalid or unrecognized response
7/25 | 20170725.01 | Win10 | The server returned an invalid or unrecognized response
9/26 | 20170926.05 | Win10 | The server returned an invalid or unrecognized response
9/26 | 20170926.05 | Win10 | The server returned an invalid or unrecognized response
9/26 | 20170926.06 | Win7 | The handle is invalid
9/27 | 20170927.02 | Win10 | The server returned an invalid or unrecognized response
10/1 | 20171001.01 | Win10 | The server returned an invalid or unrecognized response
10/3 | 20171003.02 | Win10 | The server returned an invalid or unrecognized response
10/9 | 20171009.03 | Win10 | The server returned an invalid or unrecognized response
10/13 | 20171013.01 | Win10 | The server returned an invalid or unrecognized response
10/14 | 20171014.01 | Win10 | The server returned an invalid or unrecognized response
10/16 | 20171016.02 | Win10 | The server returned an invalid or unrecognized response
10/17 | 20171017.01 | Win10 | The server returned an invalid or unrecognized response
10/18 | 20171018.02 | Win10 | The server returned an invalid or unrecognized response
10/19 | 20171019.01 | Win10 | The server returned an invalid or unrecognized response
10/20 | 20171020.02 | Win10 | The server returned an invalid or unrecognized response
10/23 | 20171023.02 | Win7 | The handle is invalid
10/26 | 20171026.01 | Win10 | The server returned an invalid or unrecognized response
10/28 | 20171028.01 | Win10 | The server returned an invalid or unrecognized response
10/30 | 20171030.02 | Win10 | The server returned an invalid or unrecognized response
11/2 | 20171102.05 | Win10 | The server returned an invalid or unrecognized response
11/3 | 20171103.10 | Win10 | The server returned an invalid or unrecognized response
11/4 | 20171104.03 | Win7 | IOException: The handle is in the wrong state for the requested operation
11/7 | 20171107.04 | Win10 | The server returned an invalid or unrecognized response
11/8 | 20171108.01 | Win10 | The server returned an invalid or unrecognized response
11/9 | 20171109.04 | Win7 | The handle is invalid
11/9 | 20171109.05 | Win7 | The operation has been canceled
11/11 | 20171111.01 | Win10 | The server returned an invalid or unrecognized response
11/11 | 20171111.01 | Win10 | The server returned an invalid or unrecognized response
11/14 | 20171114.01 | Win7 | The operation has been canceled
11/15 | 20171115.02 | Win10 | The server returned an invalid or unrecognized response
11/15 | 20171115.03 | Win10 | The server returned an invalid or unrecognized response
11/21 | 20171121.01 | Win10 | The server returned an invalid or unrecognized response
11/21 | 20171121.01 | Win10 | The server returned an invalid or unrecognized response
11/23 | 20171123.01 | Win10 | The server returned an invalid or unrecognized response
11/25 | 20171125.02 | Win10 | The server returned an invalid or unrecognized response
11/28 | 20171128.05 | Win10 | The server returned an invalid or unrecognized response
12/2 | 20171202.02 | Win10 | The server returned an invalid or unrecognized response
12/11 | 20171211.05 | Win10 | The server returned an invalid or unrecognized response
12/11 | 20171211.03 | Win10 | The server returned an invalid or unrecognized response
12/12 | 20171212.01 | Win10 | The server returned an invalid or unrecognized response
12/16 | 20171216.02 | Win10 | The server returned an invalid or unrecognized response - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171216.02/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None))
12/16 | 20171216.03 | Win10 | The server returned an invalid or unrecognized response - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171216.03/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None))
12/28 | 20171228.02 | Win10 | The server returned an invalid or unrecognized response - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171228.02/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None))
1/3 | 20180103.03 | Win10 | The server returned an invalid or unrecognized response - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180103.03/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None))
1/7 | 20180107.02 | Win8.1 | The operation has been canceled - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180107.02/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20Chunked,%20transferError:%20None))
1/10 | 20180110.03 | Win10 | The server returned an invalid or unrecognized response - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180110.03/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None))
1/11 | 20180111.02 | Win10 | 2x - The server returned an invalid or unrecognized response - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180111.02/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None))
1/16 | 20180117.01 | Win10 | The server returned an invalid or unrecognized response - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180117.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None))
1/21 | 20180122.01 | Win10 | The server returned an invalid or unrecognized response - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180122.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None))
1/22 | 20180122.02 | Win7 | The handle is invalid - only in [catastrophic failure logs](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180122.02/workItem/System.Net.Http.Functional.Tests/wilogs)
1/27 | 20180127.04 | Win10 | The server returned an invalid or unrecognized response - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180127.04/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None))
1/30 | 20180130.05 | Win8.1 | The operation has been canceled - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180130.05/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None))
2/1 | 20180201.05 | Win8.1  | The operation has been canceled - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180201.05/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None))
2/1 | 20180201.05 | Win10  | The server returned an invalid or unrecognized response - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180201.05/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None))
2/3 | 20180203.01 | Win10 | The server returned an invalid or unrecognized response - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180203.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None))
3/2 | 20180302.06 | Win7 | The handle is invalid
3/4 | 20180304.01 | Win7 | The handle is invalid
3/7 | 20180307.04 | Win7 | The handle is invalid

**Comment by Jiayili1** [comment]
Failed on 2.0.0, detail: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170526.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None)

**Comment by Jiayili1** [comment]
Failed on Core Tests (2.0.0) again, detail: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170705.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None)

**Comment by Jiayili1** [comment]
Failed again: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170719.03/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None)

**Comment by Jiayili1** [comment]
Failed again on Core Tests (Master), detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170725.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None)

**Comment by davidsh** [comment]
FWIW, this test does not use the Azure test endpoint. Rather, it uses a loopback server. So, it is odd for the test to fail with "The server returned an invalid or unrecognized response".

```c#
[OuterLoop] // TODO: Issue #11345
[Theory]
[InlineData(LoopbackServer.TransferType.None, LoopbackServer.TransferError.None)]
[InlineData(LoopbackServer.TransferType.ContentLength, LoopbackServer.TransferError.None)]
[InlineData(LoopbackServer.TransferType.Chunked, LoopbackServer.TransferError.None)]
public async Task ReadAsStreamAsync_ValidServerResponse_Success(
    LoopbackServer.TransferType transferType,
    LoopbackServer.TransferError transferError)
{
    IPEndPoint serverEndPoint;
    Task serverTask = LoopbackServer.StartTransferTypeAndErrorServer(transferType, transferError, out serverEndPoint);

    await ReadAsStreamHelper(serverEndPoint);

    await serverTask;
}
```

**Comment by Jiayili1** [comment]
failed again on Core Tests (2.0.0), detail: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170808.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None)

**Comment by davidsh** [comment]
An interesting data point about these test failures is that all of them all failing only on one of the 3 different inline datas for the theory:

```c#
[InlineData(LoopbackServer.TransferType.ContentLength, LoopbackServer.TransferError.None)]
```

**Comment by Jiayili1** [comment]
failed again in 2.0.0 branch, detail: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170914.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None)

**Comment by Jiayili1** [comment]
failed again in Master branch, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171013.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None)

**Comment by Jiayili1** [comment]
failed again in Master branch: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171017.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None)

**Comment by Sunny-pu** [comment]
failed again in Master branch: 
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171106.02/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandlerTest~2FPostAsync_CallMethod_StreamContent(remoteServer:%20http:~2F~2Fcorefx-net.cloudapp.net~2FVerifyUpload.ashx,%20content:%20StreamContentWithSyncAsyncCop...

**Comment by Sunny-pu** [comment]
failed again in Master branch:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171212.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ResponseStreamTest~2FReadAsStreamAsync_ValidServerResponse_Success(transferType:%20ContentLength,%20transferError:%20None)

**Comment by karelz** [comment]
Updated top post with failures history

**Comment by karelz** [comment]
Note that "The handle is invalid" failures would be just transformed into another exception (e.g. "The operation has been canceled") if #9228 was fixed, the test would still fail - see https://github.com/dotnet/corefx/issues/25912#issuecomment-351808254

**Comment by karelz** [comment]
(deleted a few unrelated test failures - the bug does NOT track general "The server returned an invalid or unrecognized response")

**Comment by karelz** [comment]
BTW: Another hit - this time with the "original" failure and on Win10. If it is different problem with the test, we may slipt it off.

**Comment by karelz** [comment]
BTW: I updated the bug with history for the **original** problem on `ReadAsStreamAsync_ValidServerResponse_Success` test. Sorry for the confusion earlier ...

**Comment by karelz** [comment]
No luck in tracking it down now - see https://github.com/dotnet/corefx/issues/25880#issuecomment-360297737 for details, moving it to Future.

**Comment by stephentoub** [comment]
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/3b3ef4445dfa7d0e598572684e8045a1cf5deba1/workItem/System.Net.Http.Functional.Tests

**Comment by rmkerr** [comment]
Closing as this issue has not occurred since April 12th.
