### ISSUE TITLE
Port 2.0: Prep tests for CoreCLR/CoreRT [Serializable] cleanup

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#20041]
We need to port PR #20035

cc @morganbr @stephentoub

**Comment by tarekgh** [comment]
@karelz this issue would be fixed after merging #20035 or is there more work need to be done here? it is not clear to me what need to be done here?

**Comment by karelz** [comment]
After merging #20035 we will have the fix in master = 2.1. We need to port it to 2.0. That's what this issue tracks.
Does it answer your question?

**Comment by tarekgh** [comment]
@morganbr I assigned this one to you. please let me know if you are not the one going to port it to 2.0.

**Comment by tarekgh** [comment]
@morganbr would you port the changes before the end of the week?

**Comment by danmosemsft** [comment]
@morganbr there seems no work here.
