### ISSUE TITLE
TripleDESCryptoServiceProvider.Key - specified Key is not valid size

### ISSUE THREAD

**Issue by RickStrahl** [dotnet/corefx#20053]
Running the following code:

```cs
[TestMethod]
public void TripleDesKeyTest()
{
	byte[] key = new byte[16] { 3, 3, 3, 5, 222, 13, 155, 55, 122, 123, 165, 187, 188, 1, 11, 133 };
	byte[] data = Encoding.UTF8.GetBytes("superSeekritSauerkraut");

	var des = new TripleDESCryptoServiceProvider();					
	des.Mode = CipherMode.ECB;
	des.Key = key;


	var Transform = des.CreateEncryptor();			
	byte[] encryptedResult = Transform.TransformFinalBlock(data, 0, data.Length);

	Assert.IsNotNull(encryptedResult);
	Assert.IsTrue(encryptedResult.Length > 0);
}
```

Works against full framework, but when running against .NET Core I get:

```
System.Security.Cryptography.CryptographicException occurred
  HResult=0x80131501
  Message=Specified key is not a valid size for this algorithm.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Security.Cryptography.SymmetricAlgorithm.set_Key(Byte[] value)
   at System.Security.Cryptography.TripleDES.set_Key(Byte[] value)
   at System.Security.Cryptography.TripleDESCryptoServiceProvider.set_Key(Byte[] value)
   at Westwind.Utilities.Test.EncryptionTests.TripleDesKeyTest() in C:\projects2010\Westwind.Utilities.Core\Westwind.Utilities.Test\EncryptionTests.cs:line 20
```
After digging around a bit it seems the key should be 16 or 24 bytes, but even if the key is that size it doesn't work.

Expected:
Same behavior as full framework which accepts a key of any byte size.

**Updated**
So it looks like a 24 byte key works.

Either way this doesn't seem right. If using CipherMode.ECB shouldn't the key be adjusted to fit?

Here's the test output:
```
PS C:\projects2010\Westwind.Utilities.Core\Westwind.Utilities.Test> dotnet test --filter Westwind.Utilities.Test.EncryptionTests.TripleDesKeyTest
Build started, please wait...
Build completed.

Test run for C:\projects2010\Westwind.Utilities.Core\Westwind.Utilities.Test\bin\Debug\netcoreapp2.0\Westwind.Utilities.Test.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170502-03
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Failed   Westwind.Utilities.Test.EncryptionTests.TripleDesKeyTest
Error Message:
 Test method Westwind.Utilities.Test.EncryptionTests.TripleDesKeyTest threw exception:
System.Security.Cryptography.CryptographicException: Specified key is not a valid size for this algorithm.
Stack Trace:
    at System.Security.Cryptography.SymmetricAlgorithm.set_Key(Byte[] value)
   at System.Security.Cryptography.TripleDES.set_Key(Byte[] value)
   at System.Security.Cryptography.TripleDESCryptoServiceProvider.set_Key(Byte[] value)
   at Westwind.Utilities.Test.EncryptionTests.TripleDesKeyTest() in C:\projects2010\Westwind.Utilities.Core\Westwind.Utilities.Test\EncryptionTests.cs:line 24


Total tests: 1. Passed: 0. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 0.9436 Seconds
Test run for C:\projects2010\Westwind.Utilities.Core\Westwind.Utilities.Test\bin\Debug\net452\Westwind.Utilities.Test.dll(.NETFramework,Version=v4.5.2)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170502-03
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 0.8669 Seconds
```

**Comment by karelz** [comment]
@ianhays @steveharter can you please assess if this is must have for 2.0 while Jeremy is on vacation? From the description it looks serious ...

cc @stephentoub

**Comment by RickStrahl** [comment]
I'm pretty sure this will break lots of code, because most people do what I do in a typical use case: Take a string, encode it to bytes then feed it to the Provider - with no concern for the key size. 

As I indicated a 24 byte key works.  I hacked this into my existing library like this:

```cs
public static byte[] EncryptBytes(byte[] inputBytes, byte[] encryptionKey)
{            
    TripleDESCryptoServiceProvider des = new TripleDESCryptoServiceProvider();
    MD5CryptoServiceProvider hashmd5 = new MD5CryptoServiceProvider();
	SHA256CryptoServiceProvider sha256 = new SHA256CryptoServiceProvider();

#if NETFULL
	des.Key = hashmd5.ComputeHash(encryptionKey);
#else
	byte[] bytes = hashmd5.ComputeHash(encryptionKey);

	// HACK: Fill out key to 24 bytes required
	if (bytes.Length < 24)
	{
		List<byte> byteList = new List<byte>(bytes);
		for (int i = bytes.Length -1; i < 24; i++)
		{
			byteList.Add(0);
		}
		bytes = byteList.ToArray();
	}
	des.Key = bytes.Take(24).ToArray();
#endif
	des.Mode = CipherMode.ECB;

    ICryptoTransform Transform = des.CreateEncryptor();

    byte[] Buffer = inputBytes;
    return Transform.TransformFinalBlock(Buffer, 0, Buffer.Length);
}
```

But this ends up creating different encrypted values obviously (unless the key bytes happen to be 24 bytes).

**Comment by karelz** [comment]
Thanks for confirming my suspicion @RickStrahl!
BTW: I admit I didn't look deeper into the code as I don't have previous expertise with crypto (and I don't scale to do that for each issue). My evaluation was just based on high-level description and best guess on impact. Your confirmation of the impact helps ;), so thanks!

**Comment by danmosemsft** [comment]
I opened a [suggestion](https://github.com/dotnet/corefx/issues/20055) to return what key sizes we support.

**Comment by karelz** [comment]
@danmosemsft does it mean we do not support certain key size which we support on Desktop?

**Comment by danmosemsft** [comment]
My understanding was in general, crypto API does not conceal [platform limitations ](https://github.com/dotnet/corefx/pull/18169#issuecomment-293105179). I am not a crypto guy either, so I can't say much.

**Comment by karelz** [comment]
That would make sense in Windows vs. Linux. This is however Desktop vs. .NET Core, both on Windows. We maybe use different crypto libraries under-the-hood and this may be one of the observable differences ... @steveharter do you know more about it? Could you or @ianhays please look into it?

**Comment by stephentoub** [comment]
Isn't this the same as https://github.com/dotnet/corefx/issues/9966?

**Comment by RickStrahl** [comment]
Yes that looks similar.

Still wonder, how is this working on desktop given that presumably the same logic is used? The desktop code fixes up short byte counts to 24 (or 16) and I wonder if it wouldn't be a good idea to provide that same functionality in the .NET Core bits for compatibility.

Consider this scenario for porting:

Say I have an full framework application that stores encrypted data in a database. It used the old formatting using a string based key converted to bytes to encrypt the data. Now you want to port that application to .NET Core and you want to bring your existing encrypted data with you. How do you match the encryption now? Answer: You can't because there no longer is a way to line up the encryption keys.

To be clear this is not blocking me, but I'm just thinking around the edges of this decision and I can see this causing quite a bit of friction when upgrading to .NET Core 2. The other issue I see is that most examples that show TripleDES encryption today all use random size string encryption keys rather than byte arrays and I wouldn't be surprised if the majority of code using TripeDES is using that approach. All of that will break when moving to NET Core in a way that's not easily fixable from an infrastructure POV.

**Comment by stephentoub** [comment]
> presumably the same logic is used? 

In core currently, TripleDESCryptoServiceProvider just wraps TripleDES.Create().

**Comment by RickStrahl** [comment]
I was playing with that last night - whether you use the provider directly or .Create() makes no difference in behavior in either framework. 

The issue is the keysize check and not fixing up keys to the required byte size as full framework did.

I think the way to fix this perhaps might be to have a flag that allows for the old behavior or a flag bit on the CipherMode.

**Comment by karelz** [comment]
@RickStrahl The implementation in Core uses different APIs under the hood AFAIK. That's why there are some subtle differences. We tried to minimize them as much as possible (proactively).

Your scenario makes sense to me, I'll ask @steveharter and @ianhays to look into it. If there's something we can do cheaply, we should do it. If it means rewriting half of the crypto stack, we will likely just live with it :( (although that would make me unhappy from the reasons you point out)

**Comment by RickStrahl** [comment]
Understood and totally agree.

Just thinking through some of the scenarios that can cause problems.

**Comment by karelz** [comment]
Yep, thanks. We appreciate that kind of feedback & insights. It is helpful for us to assess impact, even if it is "just theoretical". At minimum it confirms/adjusts our view point.

**Comment by bartonjs** [comment]
See https://stackoverflow.com/a/39453362/6535399. For a 16 byte -> 24 byte transition the answer is to copy the first 8 bytes again to the last 8 bytes.

**Comment by steveharter** [comment]
Marking this as a dupe of https://github.com/dotnet/corefx/issues/9966 which is still open. The conclusion there is that corefx should support 16 bytes keys since netfx does.

The corefx behavior for TripleDes has remained the same since 1.0. Currently if you have a 16-byte key (say as an MD5 hash) then currently the key will need to be manually changed to 24 bytes as @bartonjs states.

**Comment by beckyraj** [comment]
I've hit this problem as well, is there a date for when this will get released. I notice its been added to https://github.com/dotnet/corefx/milestone/5. 

Is there a workaround in the meantime? We have existing data that is encrypted so I can't change both encrypt and decrypt functions.
