### ISSUE TITLE
[HttpListener] Port HttpListener managed fixes to 2.0 en mass

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#20060]
We have a bunch of fixes coming in to the managed HttpListener.  We should roll-up and review all changes made since forking for 2.0, and port them over en masse rather than reviewing each piece meal.

**Comment by karelz** [comment]
List of PRs to port into rel/2.0.0:
* #19979 - PR #20059
* #19980 and #19985 - PR #20061
* #19982 - PR #20063
* #19986 - PR #20060
