### ISSUE TITLE
Process tests failing in Portable run due to needing elevation

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20070]
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170521.02/workItem/System.Diagnostics.Process.Tests

These tests need elevation. Either the runs need to be elevated, the tests need to elevate themselves, or they need filtering out by trait and covered some other way.

**Comment by danmosemsft** [comment]
Can easily filter out trait question is how to get coverage of those 3

**Comment by karelz** [comment]
Reopening to track port to 2.0 branch

**Comment by karelz** [comment]
Fixed in #20119 in rel/2.0.0 branch.
