### ISSUE TITLE
Small summary mistake

### ISSUE THREAD

**Issue by AndreasCag** [dotnet/corefx#20071]
https://github.com/dotnet/corefx/blob/master/src/System.ValueTuple/src/System/ValueTuple/ValueTuple.cs#L446
Change "first" to "second".

**Comment by svick** [comment]
Do you want to create a Pull Request that fixes it?

It's fairly simple: start by clicking on the pencil icon at the top of the file.

**Comment by karelz** [comment]
Here are docs (under construction) for first PR: https://github.com/dotnet/corefx/wiki/New-contributor-Docs#contributing-guide

**Comment by stephentoub** [comment]
Fixed in #20090
