### ISSUE TITLE
System.Threading.Tasks.Parallel.ForEach method does not always throw OperationCanceledException when canceled

### ISSUE THREAD

**Issue by OleksandrKrutykh** [dotnet/corefx#20093]
I have found that `ForEach` method in `System.Threading.Tasks.Parallel` class does not always finish with `OperationCanceledException` when canceled. Instead, `ForEach` method silently stops without throwing any exceptions and without executing all iterations. As a result, `Parallel.ForEach` may produce incomplete results. This behavior is observed for `Parallel.ForEach` method only, I was not able to reproduce it for `Parallel.For` method.

Let's assume that we have a method that performs some work with the help of `Parallel.ForEach`:

```c#
private static int DoWork(CancellationToken token)
{
    var parallelOptions = new ParallelOptions { CancellationToken = token };
    int counter = 0;
    Parallel.ForEach(
        new int[500],
        parallelOptions,
        dummy =>
        {
            // Waste some time and keep CPU busy.
            for (long i = 0; i < 500; i++) ;

            Interlocked.Increment(ref counter);
        });
    return counter;
}
```
The method executes 500 tasks, each of them increments `counter` variable. Each task also does a small amount of work in the form of an empty `for` cycle so that it does not finish right away. If `DoWork` method finishes successfully, the returned value should be equal to the number of tasks executed (500). If `CancellationToken` is canceled while `Parallel.ForEach` is still running, then (per documentation) `Parallel.ForEach` should throw `OperationCanceledException`. 

The problem is that if some code launches `DoWork` method, waits for a short time (a few milliseconds), and then cancels `DoWork`, the value returned from `DoWork` may be smaller than 500:

```C#
using (var tokenSource = new CancellationTokenSource())
{
    Task<int> task = Task.Run(() => DoWork(tokenSource.Token));

    // Waste some time and keep CPU busy before canceling DoWork.
    const long delay = 20000;
    for (long i = 0; i < delay; i++) ;

    tokenSource.Cancel();
    try
    {
        int counter = await task;
        if (counter == 500)
        {
            // This branch should be executed if tokenSource.Cancel() was called too late
            // and Parallel.ForEach had already finished.
        }
        else
        {
            // This branch should never be executed, but execution goes there from time 
            // to time.
        }
    }
    catch (OperationCanceledException)
    {
        // This is where we expect to land if DoWork was canceled.
    }
}
```

The probability that `DoWork` will return a value different from 500 depends on the value of `delay` constant. On my workstation the issue appears if `delay` is between 10000 and 50000 (see the image below). X-axis is `delay` constant, Y-axis is the probability of `DoWork` returning a wrong value.

![failurerate](https://cloud.githubusercontent.com/assets/23439941/26311148/8c484ef2-3f03-11e7-9748-a30b1f19fd69.png)

.NET Core console application that checks the probability of the issue: [ParallelTester.zip](https://github.com/dotnet/corefx/files/1018975/ParallelTester.zip)

I was able to reproduce the issue for .NET Core only. The same piece of code works fine when compiled under .NET Frawework 4.6.2.

Workstation Configuration:
Target Framework: .NETCoreApp 1.1 
OS: Windows 10 Pro
CPU: Core i7-4702MQ

**Comment by danmosemsft** [comment]
@stephentoub @kouvel

**Comment by Clockwork-Muse** [comment]
...What's the value of `counter` when it's not "correct"?
Note that the optimizer is allowed to do funny things, like remove loops that make no other changes to program state (although I don't know if that's happening here).
Having it cancel based on timing is extremely brittle - what happens if you cancel inside the task, based on the iteration?

**Comment by OleksandrKrutykh** [comment]
> ...What's the value of counter when it's not "correct"?

I ran `DoWork` method 100000 times with the delay between `DoWork` and cancellation set to the value that maximizes the number of failures. Out of these `counter` had an incorrect value 66559 times. "Incorrect value" here means a value different from 500. None of these incorrect `counter` values were larger than 500, minimal incorrect `counter` value was 22. Here's the distribution (X-axis: value of `counter`, Y-axis: number of times this value was returned):

![distributionofcountervalues](https://cloud.githubusercontent.com/assets/23439941/26328500/9755c5c8-3f43-11e7-9ef1-2a5daac518c6.png)

> Note that the optimizer is allowed to do funny things

Got it. Just in case: all the results were obtained with the test application compiled in "Debug" mode, with "Optimize code" checkbox not checked.

> What happens if you cancel inside the task, based on the iteration?

I could not reproduce the issue when invoking `CancellationTokenSource.Cancel()` from inside the task. I tried canceling after the counter reached different values (100, 200 etc), but each time I got zero errors out of 100000 `DoWork` invocations.

**Comment by OleksandrKrutykh** [comment]
An update: I turned `counter` variable into a field to be able to capture its value just before `CancellationTokenSource.Cancel()` is invoked. Then I calculated the difference between the value of `counter` field after `DoWork` finished incorrectly and the captured value. Here's the normalized distribution of differences: 

![differencedistribution](https://cloud.githubusercontent.com/assets/23439941/26332563/c6f26606-3f57-11e7-82f4-d0b2b4981f6a.png)

It means that most of the time `Parallel.ForEach` executes 5 - 15 tasks after `CancellationTokenSource.Cancel()` is invoked and then stops without throwing an `OperationCanceledException`. "Most of the time" is used because there were rare occasions when up to 250 tasks were executed before `Parallel.ForEach` stopped.

**Comment by OleksandrKrutykh** [comment]
I've managed to reproduce the issue without using any empty `for` loops . All that was needed was to perform the cancellation within the task, but asynchronously:

```C#
private static int DoWork(CancellationTokenSource tokenSource)
{
    var parallelOptions = new ParallelOptions { CancellationToken = tokenSource.Token };
    int counter = 0;

    Parallel.ForEach(
        new int[500],
        parallelOptions,
        dummy =>
        {
            Interlocked.Increment(ref counter);

            if (!tokenSource.IsCancellationRequested)
            {
                Task.Run(() => tokenSource.Cancel());
            }
        });
    return counter;
}
```

Here's the updated VS2017 solution with a console application that runs DoWork repeatedly until it fails: 
[ParallelTesterSimplified.zip](https://github.com/dotnet/corefx/files/1020558/ParallelTesterSimplified.zip)

**Comment by kouvel** [comment]
There's definitely some kind of race here, I'll take a look

**Comment by Clockwork-Muse** [comment]
> It means that most of the time Parallel.ForEach executes 5 - 15 tasks after CancellationTokenSource.Cancel() is invoked and then stops without throwing an OperationCanceledException. "Most of the time" is used because there were rare occasions when up to 250 tasks were executed before Parallel.ForEach stopped.

A `Task` is a specific thing/class in C#, and is most closely analogous to a thread (although it's not).  The TPL (probably, but seems likely given what I saw in PLINQ) uses about 1 task per CPU thread for execution, since you can't usually further parallelize past that point when the workload is CPU-bound.  What happens is that each task runs the lambda multiple times in a loop, but only checks for cancellation/exceptions every once in a while.  So there's 5-15 iterations that happen before it hits the check again.

> I've managed to reproduce the issue without using any empty for loops . All that was needed was to perform the cancellation within the task, but asynchronously:

Note this doesn't actually guarantee that the cancellation will run anytime soon - `Task.Run` is going to stick it into the same scheduler running the parallel invocation, which may result in it running _after_ all the other running threads have finished...  

... which _maybe_ isn't happening because your threads may not be doing enough work.  The TPL doesn't guarantee at all that things will be run on multiple threads, only that it will do so if it thinks it will help.  You're probably getting `Environment.ProcessorCount` threads/tasks, although the only way to be sure is to have a spin long enough to ensure a second one is created/used (this takes about a second - I'd have a thread check against the time).

**Comment by stephentoub** [comment]
> There's definitely some kind of race here, I'll take a look

With a quick glance, I noticed that the cancellation registration callback does:
```C#
                                // Cause processing to stop
                                sharedPStateFlags.Cancel();
                                // Record our cancellation
                                oce = new OperationCanceledException(parallelOptions.CancellationToken);
```
I don't know if this is _the_ problem, but it at least looks like _a_ problem, and the order of these lines should be reversed.  That first line to call Cancel could cause the loop to stop processing.  If all of the iterations stop processing and exit before the `oce` field is initialized to the new instance, they might still see `oce` as null here https://github.com/dotnet/corefx/blob/master/src/System.Threading.Tasks.Parallel/src/System/Threading/Tasks/Parallel.cs#L3311 even though cancellation was requested.  It also looks like those reads/writes with `oce` should be Volatile.Read/Write.

**Comment by Clockwork-Muse** [comment]
@stephentoub - I was wondering about that, more from the angle that the registration callback isn't necessarily run on the "main" thread (or any of them, really), and so the write may not have shown up yet anyways.

This would fit with the observed symptoms at least, that it correctly fails when the cancellation is invoked from inside one of the running tasks, but not when submitted separately.

**Comment by OleksandrKrutykh** [comment]
To @Clockwork-Muse:

Thanks for the detailed explanation. I understand that calling `CancellationTokenSource.Cancel` this way does not guarantee an immediate cancellation or any cancellation at all. That's why DoWork has to be invoked a few times in a loop for the issue to appear (it takes 2 - 5 tries on my workstation). Sorry for not mentioning that right away. 

I have no explanation for why it works this way, as `Parallel` class is a black box for me. The structure of `DoWork` method above was created just by trial and error.

**Comment by kouvel** [comment]
@stephentoub:

> I don't know if this is the problem, but it at least looks like a problem, and the order of these lines should be reversed. That first line to call Cancel could cause the loop to stop processing. If all of the iterations stop processing and exit before the oce field is initialized to the new instance, they might still see oce as null here 

It looks like that is the whole issue

> https://github.com/dotnet/corefx/blob/master/src/System.Threading.Tasks.Parallel/src/System/Threading/Tasks/Parallel.cs#L3311 even though cancellation was requested. It also looks like those reads/writes with oce should be Volatile.Read/Write. It's ok if we end up throwing an exception and it so happens that we actually processed everything, but it's definitely not ok if we don't report cancellation but don't process everything.

Agreed

**Comment by kouvel** [comment]
> https://github.com/dotnet/corefx/blob/master/src/System.Threading.Tasks.Parallel/src/System/Threading/Tasks/Parallel.cs#L3311 even though cancellation was requested. It also looks like those reads/writes with oce should be Volatile.Read/Write. It's ok if we end up throwing an exception and it so happens that we actually processed everything, but it's definitely not ok if we don't report cancellation but don't process everything.

On second thought, after reversing the statements in the cancellation callback, if a thread is at the point of `oce != null` due to cancellation, then it would already be guaranteed to see the exception due to volatile/interlocked accesses to the state value inside `sharedPStateFlags`. If instead the thread is at the point of `oce != null` due to completion, then it doesn't matter what it sees for `oce`. Also volatile on `oce` wouldn't help with the ordering since it's just secondary state dependent on the state value inside `sharedPStateFlags`, which needs to be volatile and is.

**Comment by stephentoub** [comment]
@kouvel, your second comment is just about the volatile-ness, not about the order of operations, right?

**Comment by kouvel** [comment]
Yes just about the volatileness

**Comment by kouvel** [comment]
There might be another issue. It seems possible for cancellation to be requested between `oce != null` and `ctr.Dispose()`, in which case the work is actually complete, but the returned result would indicate incomplete and with no exception. Is that a valid combination, or should the cancellation registration be disposed before checking the exception?

**Comment by stephentoub** [comment]
> Is that a valid combination, or should the cancellation registration be disposed before checking the exception?

Disposing of the registration before the check is a good idea.
