### ISSUE TITLE
Need to handle generating config files for exe's we launch from tests

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#20109]
exe's like our RemoteExecutorApp or others like [VoidMainWithExitCodeApp](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/tests/VoidMainWithExitCodeApp/VoidMainWithExitCodeApp.cs) need to have configuration files in order to successfully run. See https://github.com/dotnet/corefx/pull/19232 where I've temporarily checked in an appconfig file to address it for that test exe. We currently hardcode a list of config files we generate here https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets#L130. Instead of hardcoding we should make that list extensible or automatically detect exe's and generate config files for them.

While app.config is for the desktop runs we have a similar problem with the netcoreapp runs with runtimeconfig.json files that are needed. We should follow a similar process and generate them as well instead of having them be checked in along side all the test exe's.

**Comment by safern** [comment]
Sounds good. Will take a look later when I'm done with ConditionalFact/Theory

**Comment by safern** [comment]
We should also include in the Desktop config file a setting to override the `TraceListener` with a custom trace listener that treats debug.assert as a failed test instead of showing a pop-up which also causes the tests to hang. Something like: 

```xml
<system.diagnostics>
        <trace autoflush="true" indentsize="4">
            <listeners>
                <add name="TextListener" 
                    type="Xunit.Netcore.Extensions.CustomTraceListener, Xunit.Netcore.Extensions" />
            <remove name="Default" />
            </listeners>
        </trace>
</system.diagnostics>
```

This custom trace listener should be included in Xunit.Netcore.Extensions desktop version

**Comment by ViktorHofer** [comment]
For the migration I'm going to remove the net46 project and will it bring later probably in the same project when we get rid of project.json.

**Comment by ViktorHofer** [comment]
This is now automatically handled by Microsoft.DotNet.CoreFxTesting.
