### ISSUE TITLE
Several FileSystemWatcher tests are failing on OSX

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#2011]
Expected events are not being raised for at least:
- FileSystemWatcher_Changed_LastWrite_File
- FileSystemWatcher_Changed_LastWrite_Directory
- FileSystemWatcher_Created_MoveDirectory

A Debug.Assert in FindRenameChangePairedChange is also firing for the MoveDirectory test:

**Comment by sokket** [comment]
Looks like a timing issue since debugging through it shows the events are being captured and fired...will investigate

**Comment by stephentoub** [comment]
There are ~10 tests disabled with this issue number.  If they're still failing, they should be investigated, and if they're passing, they should be re-enabled.

**Comment by joshfree** [comment]
moving this to RTM
