### ISSUE TITLE
Re-enable long path tests for UAP

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#20117]
WinRT APIs weren't long path friendly. This should change for RS3. Additionally we're planning to remove WinRT specific codepaths, relying on our "traditional" Win32 APIs. Should tackle after #17470.

We have plenty of existing tests, they are just currently skipped for UAP.

**Comment by danmosemsft** [comment]
This is a test issue only -- it should "Just work" and if it doesn't, we likely won't have time to address it this release, but if it does, test coverage is goodness.

**Comment by danmosemsft** [comment]
@safern can you try enabling the issues disabled against 20117 see if they pass?

**Comment by safern** [comment]
Sure.
