### ISSUE TITLE
Make the description of 'Microsoft.NETCore.App' package clearer

### ISSUE THREAD

**Issue by anangaur** [dotnet/corefx#20118]
There is always a confusion as to why is 'Microsoft.NETCore.App' auto-referenced in a .NET Core project and why can it be not updated etc. We are trying to fix the text of such references on Visual Studio Package Manager as tracked here: https://github.com/NuGet/Home/issues/4964

I feel the the description of the package could also clear the air on which SDK (may be we need to use this term somewhere) to make it clearer to the end-customer why this package got included in first place and which SDK (and version) brought this package as dependency to the project.

**Comment by karelz** [comment]
@weshaggard @ericstj @mellinoe what do you think about it for 2.0?

**Comment by ericstj** [comment]
Sure, most of the descriptions were directly written by devs and never received any UX polish.  If folks what to change it just submit a change to https://github.com/dotnet/core-setup/blob/6887ab556bc8302390782711dcdd75b75e769cf5/src/pkg/projects/descriptions.json#L39.

**Comment by mellinoe** [comment]
Given that it's just a description change, I don't think this should be very "risky" from a shiproom perspective. But, obviously, we should try to make any changes as soon as possible if we want them in 2.0.

**Comment by karelz** [comment]
@anangaur do you have any wording suggestions? We can help you with the PR ...

**Comment by ericstj** [comment]
@terrajobst and @richlander likely have an opinion.

**Comment by anangaur** [comment]
May be:

"Automatically referenced by the .NET Core SDK (**version X.x.x**). Provides a set of .NET API's that are included in the default .NET Core application model."

This way the Package Manager UI shows the package got automatically added and the user need not get into the details view for this package:
![image](https://cloud.githubusercontent.com/assets/14800916/26380422/6cacff18-3fd3-11e7-8cfd-38a6afbde08b.png)

If possible we should put the **SDK version** for each of the package version that is autoreferenced. Don't know if that can happen through some variable or whether it would be overkill.

**Comment by terrajobst** [comment]
I’d rather we don’t show the package at all 😊

Can we even accurately specific the SDK version? Seems like a chicken and egg problem where some side would have to predict the version number the other side is going to produce.

**Comment by weshaggard** [comment]
We have no way of figuring out the matching SDK version.

**Comment by anangaur** [comment]
@terrajobst we want to show the NuGet dependencies whether implicit or explicit in the NuGet package manager.

If SDK version isn't possible, can we change the text for now, as proposed if there is no better text :)

**Comment by danmosemsft** [comment]
@terrajobst do you support the rewording if so shiproom might take it.

**Comment by danmosemsft** [comment]
Moving to future as I don't see anyone with cycles to push for this. @karelz @weshaggard feel free to grab otherwise.

**Comment by wtgodbe** [comment]
Closing this for now, as it seems we've been alright with the existing description. Someone can re-open it if we decide we still want to change the package description
