### ISSUE TITLE
Need to generate a RunTest.cmd unique to the BuildConfiguration instead of Configuration

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#20110]
Today if we have a configuration of netstandard in a test project and you try to run it once with one target group (say netcoreapp) and then a second time as another target group (say netfx) we keep overwriting the RunTest.cmd each time. We should ensure that the test output path takes into account the target you are running on as well as the target you are building for. 

I noticed this while helping with https://github.com/dotnet/corefx/pull/19232 and saw we were running the netfx tests from here `D:\git\corefx\bin\Windows_NT.AnyCPU.Debug\System.Runtime.Extensions.Tests\netstandard\RunTest.cmd` which didn't account for netfx as all.

**Comment by weshaggard** [comment]
@safern didn't you fix this issue?

**Comment by safern** [comment]
Yes, I fixed it in: https://github.com/dotnet/corefx/pull/23633
