### ISSUE TITLE
Move more OuterLoop tests into InnerLoop

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20122]
The netcore tests are close to 100% green, excepting networking. To help avoid going backwards, we should go through the Outerloop tests (except networking) and promote all of them that are (1) reliable and (2) not excessively time consuming. That way CI can protect them.

**Comment by weshaggard** [comment]
@danmosemsft this is labeled as infra but is more specific to individual tests. Do you want this still for tracking? If so I think it would make since to file individual issues against the owners for the tests in question.

**Comment by danmosemsft** [comment]
That woudl work if someone would grep where all the OuterLoop ones are and make issues for the biggest buckets.

**Comment by stephentoub** [comment]
Replaced by #36605.
