### ISSUE TITLE
UWP: System.Net.WebProxy

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#20137]
Tracking work for System.Net.WebProxy

**Comment by Jiayili1** [comment]
Following test failed with System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : No such device or address

Failed test: System.Net.Tests.WebProxyTest/BypassOnLocal_MatchesExpected 

Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170627.01/workItem/System.Net.WebProxy.Tests/analysis/xunit/System.Net.Tests.WebProxyTest~2FBypassOnLocal_MatchesExpected

**Comment by CIPop** [comment]
@Jiayili1 the failure has nothing to do with UWP - please open a different issue.
