### ISSUE TITLE
UWP: System.Net.NameResolution

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#20139]
Tracking UWP work for System.Net.NameResolution

**Comment by schen381** [comment]
Have run all tests under System.Net.NameResolution on framework=UAP (including outerloop), no failure observed.

**Comment by davidsh** [comment]
@schen381 Did you also check the test sources for any disabled tests on UWP?  If there are disabled tests, then those need to be re-enabled and fixed (test or product source) if needed.

**Comment by schen381** [comment]
@davidsh I will look into those disabled tests

**Comment by schen381** [comment]
Status update: there is no disabled test for NameResolution. Will look into dependency on WinRT APIs next

**Comment by schen381** [comment]
fixed in #20208

**Comment by DavidGoll** [comment]
Check neteventsource logging, and close if no issue.

**Comment by caesar1995** [comment]
Status update:
1. Blocked by #20470 
2. No [ActiveIssue] and [SkipOn] (the only one is related to #20470 )
3. No dependency on WinRT implementation
