### ISSUE TITLE
UWP: System.Net.WebSockets

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#20132]
Tracking work for System.Net.WebSockets (common, client and server).

**Comment by CIPop** [comment]
Verified that `System.Net.WebSocket` has no test failure in both UAP and UAPAOT.

**Comment by Diego-Perez-Botero** [comment]
After #22183, there are no remaining UAP-specific ActiveIssue or SkipOn* annotations in the entire System.Net.WebSockets* namespace.
