### ISSUE TITLE
Investigate XmlSchemaSet's behavior on Unix when temp path is passed as Uri

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#20148]
When XmlSchemaSet is trying to load schemas that were imported/included in another schema, if it receives temp path in the Uri, it would not load the schemas on non-Windows platforms, as `/tmp/` is not considered AbsoluteUri. This causes incorrect behavior with XmlSchemaSet.

For more details, please refer to the discussion in https://github.com/dotnet/corefx/issues/20046.

Please also re-enable the tests marked as ActiveIssue when this is fixed.

**Comment by karelz** [comment]
Reopening to track port into rel/2.0.0 branch.

**Comment by sepidehMS** [comment]
@karelz The PR associated with this issue only touches tests. Although I initially marked this with label "bug", it turned out that there is no way we can figure out if the given path is absolute or relative on Unix in XmlSchema, if the `Uri` class does not treat paths like `"/tmp"` as absolute. Having said that, should this still be ported to 2.0?

**Comment by karelz** [comment]
If it impacts our test runs, we should port it into 2.0 (we don't want noise in servicing branches, it back fires quickly).
If it doesn't cause any noise / significant test failures in test runs, fixing it in 2.1/master (as you did above) is sufficient - please adjust the milestone in such case with link to PR which fixed it. Thanks!

**Comment by sepidehMS** [comment]
This does not impact number of test failures on Desktop and was a regression of fixing uap tests in PR  https://github.com/dotnet/corefx/pull/19735. I think fixing it in 2.1 would suffice. The fix was made in https://github.com/dotnet/corefx/pull/20262. Closing.

**Comment by karelz** [comment]
Great, adjusting the milestone to 2.1 then.
