### ISSUE TITLE
UWP: System.Net.WebClient

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#20141]
Tracking UWP work for System.Net.WebClient.

**Comment by Jiayili1** [comment]
Failed again: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170608.01/workItem/System.Net.WebClient.Tests/analysis/xunit/System.Net.Tests.SyncWebClientTest~2FUploadFile_Success(echoServer:%20https:~2F~2Fcorefx-net.cloudapp.net~2FEcho.ashx)

**Comment by davidsh** [comment]
@Jiayili1 The comment you entered above about that failure was on a CentOs (Linux) build.  It had an error of "System.Net.Http.CurlException : Problem with the SSL CA cert (path? access rights?)" which is NOT related to this issue at all.

**Comment by CIPop** [comment]
@Jiayili1 this is tracking feature work. Please open a separate bug, do not change labels.

**Comment by Jiayili1** [comment]
@CIPop Thanks, I will open a separate bug.
