### ISSUE TITLE
UWP: System.Net.ServicePoint

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#20140]
Tracking UWP work for System.Net.ServicePoint.

**Comment by schen381** [comment]
Finished investigation on UWP work for S.N.ServicePoint.
1. all tests passed in uap & uapaot mode, no active issue or skip because of uap & uapaot related things
2. no reference to UWP related namespace, no dependency on win32 apis

**Comment by DavidGoll** [comment]
Check for NetEventSource logging, and close if no issue.

**Comment by caesar1995** [comment]
Status update:
1. No [ActiveIssue] inside the namespace (no matter UAP or non-UAP)
2. No test failure
3. No dependency on WinRT implementation
