### ISSUE TITLE
Build.cmd should pick up and use the VS 2017 developer command prompt automatically

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#20158]
I only have VS2017 installed on my PC, but when I run `build.cmd` from the normal command prompt (`cmd.exe`) I get
> Error: Visual Studio 2015 or 2017 required.
>        Please see https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md for build instructions.

It'd be nice if `build.cmd` picked up that I have only one of these environments installed and used it. Before VS2017 I could use build.cmd from the non-developer command prompt

**Comment by weshaggard** [comment]
I agree with your recommendation that this should just work.

Should be simple to add the detection here https://github.com/dotnet/corefx/blob/master/run.cmd#L19.

**Comment by steji113** [comment]
@weshaggard Did your work in #22575 address this?

**Comment by weshaggard** [comment]
@steji113 yes it did. Thanks for pinging this issue.
