### ISSUE TITLE
[HttpListener] HttpListenerResponse.Close(byte[], bool) does not properly shutdown all the time

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#20156]
```cs
[InlineData(true)]
[InlineData(false)]
// The managed implementation should set ContentLength to -1 after sending headers.
[ConditionalTheory(nameof(Helpers) + "." + nameof(Helpers.IsWindowsImplementation))] // [ActiveIssue(19973, TestPlatforms.AnyUnix)]
public async Task CloseResponseEntity_ChunkedNotSentHeaders_ModifiesContentLength(bool willBlock)
{
    using (HttpListenerResponse response = await GetResponse())
    {
        response.SendChunked = true;

        response.Close(new byte[] { (byte)'a' }, willBlock);
        Assert.Equal(-1, response.ContentLength64);

        // If we're non-blocking then it's not guaranteed that we received this when we read from the socket.
        try
        {
            string clientResponse = GetClientResponse(126);
            Assert.EndsWith("\r\n1\r\na\r\n0\r\n\r\n", clientResponse);
        }
        catch (SocketException)
        {
            // Most of the time, the Socket can read the content send after calling Close(byte[], bool), but
            // occassionally this test fails as the HttpListenerResponse closes before the Socket can receive all
            // content. If this happens, just ignore the failure and carry on.
            // The exception message is: "An existing connection was forcibly closed by the remote host."
            // Although part of this test is to ensure that the connection isn't forcibly closed when closing,
            // we want to avoid intermittent failures.
        }
    }
}
```

From @stephentoub in #19880:

> This is in both the Windows and managed implementation, or just the managed one? This sounds like a bug. It should be possible for the server to close the connection and still have the client receive all of the data sent before that, assuming the server is doing a proper shutdown of the connection.

**Comment by karelz** [comment]
Is it compat problem against Desktop?

**Comment by hughbe** [comment]
This test has never run against Desktop because of the `ConditionalFact` bug (#18483) but I will see

**Comment by hughbe** [comment]
So i've ran the tests several hundred times using a batch script with netcoreapp and netfx to try to repro this with both parallelization enabled and disabled, but can't reproduce this failure.

I was getting it about 1/100 before I added the catch statements to fix the intermittent failures.

**Comment by karelz** [comment]
OK, moving to 2.0 as it is reliability regression against Desktop.

**Comment by hughbe** [comment]
Sorry I should've made clear - it's unclear with desktop as I can't reproduce it on desktop or core now :/

**Comment by karelz** [comment]
You can't repro even on .NET Core anymore?

**Comment by hughbe** [comment]
> You can't repro even on .NET Core anymore?

No I can't. What do you think? Is it worth un-disabling these tests after ask-mode/escrow/release and seeing if it can repro in the wild?

**Comment by karelz** [comment]
> Is it worth un-disabling these tests after ask-mode/escrow/release and seeing if it can repro in the wild?

Yes please, given that there is no value in having permanently-disabled tests :)
If the test is flaky, we can disable it again / delete it entirely if we find it is bogus.
