### ISSUE TITLE
Adds runtime feature detection support for default interface method 

### ISSUE THREAD

**Issue by yizhang82** [dotnet/corefx#20157]
This proposal introduces a new flag for the presence of default interface methods (see the references below).

```csharp
    public static class RuntimeFeature
    {
        /// <summary>
        /// Indicates that this version of runtime supports default interface method implementations.
        /// </summary>
        // Original name, adjusted by API review: InterfaceDefaultMethods
        public const string DefaultImplementationsOfInterfaces = nameof(DefaultImplementationsOfInterfaces);

        /// <summary>
        /// Checks whether a certain feature is supported by the Runtime.
        /// </summary>
        public static bool IsSupported(string feature)
        {
            if (feature == DefaultImplementationsOfInterfaces )
                return true;

            return false;
        }
    }
```

`System.Runtime.CompilerServices.RuntimeFeature.IsSupported` returning true indicates that the runtime supports interface default method feature. It only indicates the presence of the feature and does *NOT* necessarily translate to any specific runtime behavior. This means that future runtime will keep returning true for this feature even in the case of breaking behavior changes (perhaps the only exception is when we decide to take the feature out, but that probably would never happen once we ship). 

Practically speaking, returning true means that the runtime supports the set of behaviors that is defined by first version of interface default method feature in the runtime (that we ship), plus/minus any future behavior changes that may or may not be breaking. If there are any requirements to support detection of any future behavior changes (that clients such as compilers care about), we can introduce a new flag that corresponds to the new behavior. Returning true would indicate the new behavior while returning false indicates otherwise. 

# References

[C# Language Spec Link](https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md)
[Runtime Feature Support API proposal](https://github.com/dotnet/corefx/issues/17116)
[CoreCLR issue] (https://github.com/dotnet/coreclr/issues/10504)
Runtime Design Spec (TBD)

**Comment by terrajobst** [comment]
Two questions:

* I assume this for 2.0, not 1.1?
* We should name the field `DefaultImplementationsOfInterfaces`.

**Comment by karelz** [comment]
Field name updated in top-post.

**Comment by davidwrighton** [comment]
Is this expected to be a .NET Standard 2.0 feature or a followon 2.1 or something?

**Comment by karelz** [comment]
2.0 is API frozen since mid April, so I assume 2.1 the earliest, but @yizhang82 moved it into Future - so not sure. @yizhang82?

**Comment by yizhang82** [comment]
We should add the API into netstandard when the feature is available everywhere, and we don't have a timeline for that yet. The only reason we might want to introduce the API (just the names) into netstandard is to better support Roslyn code (if it needs to target a particular netstandard when it ships), but that could also be easily resolved with just embedding the string. 

(Of course, this API will definitely go into CoreCLR with the default interface method implementation, just not any netstandard at this point)

@AlekseyTs @gafter @jaredpar What do you guys think?

**Comment by yizhang82** [comment]
@terrajobst @weshaggard any objections if I add this into System.Runtime contract in corefx master? The runtime code would correctly return false so we are OK there. And I think we have enough traction on this feature that I think it's just a matter of time before we ship this. Of course, I could always create a branch on corefx if you guys think that's better option.

**Comment by karelz** [comment]
@yizhang82 I don't fully understand your question.
The API is approved. If you have fully working implementation, then it can get into master (2.1) of .NET Core. It cannot get into .NET Standard obviously as .NET Standard needs first finalized versioning plan.

**Comment by yizhang82** [comment]
I want to get the API surface area (which really is the constant) into master sooner than the implementation - to make things a bit easier at compile time. Having the API doesn't mean the runtime will return "yes, it's supported".  The implementation will be in master later than 2.1.

**Comment by karelz** [comment]
Having the API with 'false' implementation in master sounds reasonable.

**Comment by weshaggard** [comment]
@terrajobst can correct me if I'm wrong but having IsSupported return false is never a real scenario when the field is actually present because the compiler will only ever look for the presences of the field and the IsSupported function is used for runtime codegen only. So if the field is present the IsSupported function should always return true.

**Comment by yizhang82** [comment]
Chatted with @AlekseyTs offline. Compiler is only checking for presence of the flag so we need to put this in a branch for now (can't show up earlier than the feature) and limit this to CoreCLR reference assemblies.

**Comment by karelz** [comment]
For CoreCLR-only reference you don't need this API approval. It will be necessary only to make the APIs public ;)

**Comment by yizhang82** [comment]
Supported in CoreCLR PR https://github.com/dotnet/coreclr/pull/11940 and CoreFX PR https://github.com/dotnet/corefx/pull/23266
