### ISSUE TITLE
System.Diagnostics.Tests.ProcessTests.TestStartOnWindowsWithBadFileFormat fails on Desktop

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#20150]
This test is marked as `[ConditionalFact]` which is currently not running in Desktop. I have the local fix already for that but I can't update it in Corefx until I disable the failing tests to have a green CI, so I will go ahead and disable it.

It fails with error:
```
System.Diagnostics.Tests.ProcessTests.TestStartOnWindowsWithBadFileFormat [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ComponentModel.Win32Exception)
        Actual:   (No exception was thrown)
        Stack Trace:
          D:\repos\corefxCopy\corefx\src\System.Diagnostics.Process\tests\ProcessTests.cs(1028,0): at System.Diagnostics.Tests.ProcessTests.TestStartOnWindowsWithBadFileFormat()
```

cc: @Priya91 @stephentoub

**Comment by danmosemsft** [comment]
@safern the difference is because on desktop, Process.UseShellExecute is true by default. (We dno't plan to change that) This will fail on desktop also
```C#
    var psi = new ProcessStartInfo(@"emptyfile");
    psi.UseShellExecute= false;
    var p = new Process();
    p.StartInfo = psi;
    p.Start();
```

So the test result is correct and you can change what it expects on desktop or just disable for desktop.

**Comment by safern** [comment]
Thanks, for digging in. I was going to disable all the failing tests before investigating. Will go ahead and fix it/disable for desktop

**Comment by karelz** [comment]
@safern also assume not needed for 2.0 ...

**Comment by safern** [comment]
Same as: https://github.com/dotnet/corefx/issues/20154#issuecomment-303570228
