### ISSUE TITLE
System.Runtime.Tests failed on Desktop

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#20154]
Two tests that are marked as [ConditionalFact] are failing for Desktop:

`System.Tests.IntPtrTests.GetHashCodeRespectAllBits` with error:

```
System.Tests.IntPtrTests.GetHashCodeRespectAllBits [FAIL]
        Assert.NotEqual() Failure
        Expected: Not -1
        Actual:   -1
        Stack Trace:
          D:\repos\corefxCopy\corefx\src\System.Runtime\tests\System\IntPtrTests.cs(149,0): at System.Tests.IntPtrTests.GetHashCodeRespectAllBits()
```

`System.Tests.UIntPtrTests.GetHashCodeRespectAllBits` with error:

```
System.Tests.UIntPtrTests.GetHashCodeRespectAllBits [FAIL]
        Assert.NotEqual() Failure
        Expected: Not 2147483647
        Actual:   2147483647
        Stack Trace:
          D:\repos\corefxCopy\corefx\src\System.Runtime\tests\System\UIntPtrTests.cs(146,0): at System.Tests.UIntPtrTests.GetHashCodeRespectAllBits()
```

This tests are currently not running in corefx as [ConditionalFact/Theory] fix is not in corefx. In order to check it in I have to disable this tests first.

cc: @joperezr @AlexGhiondea

**Comment by danmosemsft** [comment]
Both look like intentional fixes over Desktop

**Comment by safern** [comment]
Ok. Thanks for digging into this one as well.

**Comment by karelz** [comment]
@safern not needed for 2.0 I assume.

**Comment by safern** [comment]
Nope as the buildtools version in 2.0 doesn't have the fix for [ConditionalFact/Theory] so the tests are not running for Desktop
