### ISSUE TITLE
[porting bug] HttpListenerResponse.SetCookie does not throw in netcoreapp if the Cookie already exists

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#20159]
```cs
[Fact]//[ConditionalFact(nameof(PlatformDetection) + "." + nameof(PlatformDetection.IsNotOneCoreUAP))]
public async Task SetCookie_CookieDoesntExist_ThrowsArgumentException()
{
    HttpListenerResponse response = await GetResponse();
    var cookie1 = new Cookie("name", "value");

    response.SetCookie(cookie1);
    Assert.Throws<ArgumentException>("cookie", () => response.SetCookie(cookie1));

    var cookie2 = new Cookie("name", "value2");
    Assert.Throws<ArgumentException>("cookie", () => response.SetCookie(cookie2));
    Assert.Equal(new Cookie[] { cookie2 }, response.Cookies.Cast<Cookie>());
}
```

Netfx throws an ArgumentException. Netcoreapp does not throw. I have a fix for this and will send a PR when I've written more tests

**Comment by danmosemsft** [comment]
Nice work finding all these @hughbe ! thanks a lot. How are you finding them?

**Comment by hughbe** [comment]
I'm writing tests as part of #13618. After finding several bugs in the past I basically am writing the tests against the netfx implementation by using reference source, then running them against netcoreapp.

But also there's a bunch of coverage missing in HttpListener so I focussed on coverage
