### ISSUE TITLE
[porting bug] WebHeaderCollection.Add(null, "value") throws NRE in netcoreapp, ArgumentNullException in netfx`

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#20164]
```cs
[Fact]
public void Add_NullName_ThrowsArgumentNullException()
{
    var headers = new WebHeaderCollection();
    Assert.Throws<ArgumentNullException>("name", () => headers.Add(null, "value"));
}
```

This causes some HttpListener tests to fail after I've fixed #20161 

I have a fix and will submit a PR

**Comment by hughbe** [comment]
Following test also fails:

```cs
[Fact]
public void Add_EmptyName_ThrowsArgumentException()
{
    var headers = new WebHeaderCollection();
    Assert.Throws<ArgumentException>("name", () => headers.Add("", "value"));
}

```

**Comment by hughbe** [comment]
Found two more issues:

### 1: netcoreapp throws ANE, netfx throws AE
```
[Fact]
public void Add_WhitespaceName_ThrowsArgumentException()
{
    var headers = new WebHeaderCollection();
    Assert.Throws<ArgumentException>("header", () => headers.Add("   "));
}
```

**Comment by stephentoub** [comment]
> Found two more issues:

Hugh, those are fine from a product perspective.  It's ok if netcoreapp throws a more derived exception than NetFX, and ArgumentNullException derives from ArgumentException.

**Comment by hughbe** [comment]
> Hugh, those are fine from a product perspective. It's ok if netcoreapp throws a more derived exception than NetFX, and ArgumentNullException derives from ArgumentException.

Fair enough, but I ANE isn't really appropriate here anyway for a whitespace string (I know that WebHeaderCollection isn't consistent with this). We also get better exception messages as a result which is a bonus. I won't go hunting down and reporting these kinds of issues though, don't worry
