### ISSUE TITLE
[HttpListener] [Managed] Enable HttpListenerResponse cookie tests

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#20165]
Following tests are disabled with this issue:

- Cookies_SetCookie2InHeadersButNotInCookies_RemovesFromHeaders
- Cookies_SetAndSend_ClientReceivesExpectedHeaders
- Cookies_SetInHeader_ClientReceivesExpectedHeaders

**Comment by karelz** [comment]
Which issue disabled them?

**Comment by hughbe** [comment]
They were added in a currently opened PR https://github.com/dotnet/corefx/pull/20167
I'm just tracking them

**Comment by karelz** [comment]
Thanks for info!

**Comment by karelz** [comment]
OK, now I understand that you are disabling tests against this issue.
Do you think the disabled tests are signs of product issues or test issues? Is it compat with Desktop? If yes, we should address them in 2.0.

**Comment by stephentoub** [comment]
> Do you think the disabled tests are signs of product issues or test issues? Is it compat with Desktop?

Product, and yes, compat with Windows, both core and desktop.  That's the case for basically all of the problems Hugh has found.
