### ISSUE TITLE
SleepTest failed on ubuntu 17.04

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20173]
https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170523.01/workItem/System.Threading.Thread.Tests/analysis/xunit/System.Threading.Threads.Tests.ThreadTests~2FSleepTest
``` c#
        [Fact]
        public static void SleepTest()
        {
...
            var startTime = DateTime.Now;
            Thread.Sleep(500);
            Assert.True((DateTime.Now - startTime).TotalMilliseconds >= 100); <<<<<<<<<<<
        }
```

```
Assert.True() Failure\nExpected: True\nActual:   False
Stack Trace :
   at System.Threading.Threads.Tests.ThreadTests.SleepTest() in /root/corefx/src/System.Threading.Thread/tests/ThreadTests.cs:line 773
```

@stephentoub this should be using a stopwatch. But given the daylight savings did not change, can you think of why this might fail? I thought that sleeping X msec was guaranteed to cause you to sleep no less than X msec.

**Comment by danmosemsft** [comment]
@kouvel

**Comment by danmosemsft** [comment]
Hit on 1604:
```
Assert.InRange() Failure\r\nRange:  (100 - 2147483647)\r\nActual: -23.9198
Stack Trace :
   at System.Threading.Threads.Tests.ThreadTests.SleepTest() in /root/corefx/src/System.Threading.Thread/tests/ThreadTests.cs:line 773
```

any thoughts why this might fail? I'm guessing the sleep isn't going backwards in time so somehow two calls to DateTime.UtcNow are not producing monotonic results.

```
            Thread.Sleep(0);
            var startTime = DateTime.UtcNow;
            Thread.Sleep(500);
            Assert.InRange((DateTime.UtcNow - startTime).TotalMilliseconds, 100, int.MaxValue);
```

@kouvel

**Comment by kouvel** [comment]
A time sync could cause the value to go back in time, but it's strange that it would go back more than 500 ms, unless it's syncing for the first time in a long time (maybe first run on a VM). I'll change it to use a monotonic clock.

**Comment by danmosemsft** [comment]
Ah time sync, of course, didn't think about that. We do run tests like this many hundreds of times a week so it's not terribly surprising we've seen it twice in 2 weeks.
