### ISSUE TITLE
System.Data: ManagedSNI still requires sni.dll

### ISSUE THREAD

**Issue by EgorBo** [dotnet/corefx#20179]
If I set `TdsParserStateObjectFactory.UseManagedSNI = true` (on Windows it's currently [false by default](https://github.com/dotnet/corefx/pull/19084) and always `true` for unix) I assume SqlClient with ManagedSNI will use `TdsParserStateObjectManaged` instead of `TdsParserStateObjectNative` so I will not have to care about the **sni.dll**, but even with ManagedSNI it calls `[DllImport("sni.dll")] SNIInitialize(IntPtr)`. If I remove this call - my simple SqlClient tests (open a connection, execute some query, etc..) will pass without the **sni.dll**. So the question is - what **sni.dll** is used for on Windows+ManagedSNI and can we just wrap it like this.

```csharp
internal static uint SNIInitialize()
{
    return SNIInitialize(IntPtr.Zero);
}
```

TO:

```csharp
internal static uint SNIInitialize()
{
    try
    {
        return SNIInitialize(IntPtr.Zero);
    }
    catch (DllNotFoundException)
    {
        return TdsEnums.SNI_UNINITIALIZED;
    }
}
```

**Comment by EgorBo** [comment]
Sorry guys, the issue doesn't reproduce in .NET Core actually but does reproduce in mono (Mono uses same sources). 
The reason is: 
https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/TdsParserSafeHandles.cs#L19
this singleton has an inline field init, and the constructor calls that SNI.DLL method. but in .NET Core this type won't be initialized in [this line](https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/TdsParserStateObjectFactory.Windows.cs#L36) but it will in mono 😢 
Just take a look at this small snippet with a similar pattern - https://gist.github.com/EgorBo/6bcd2719209e5dd7470aaa65b8d89ead
Looks like a case where RyuJIT brakes backward compatibility.

**Comment by danmosemsft** [comment]
Hi @EgorBo are you asking for a change in CoreFX? Eg., break into a separate function?

**Comment by EgorBo** [comment]
@danmosemsft well, maybe you can advise a better way to make both corefx and mono happy? 
Options are:
1) Convert this field to a property and call ctor inside getter (classic singleton implementation with double-check lock)
2) Add an empty static constructor -- empty static constructor will remove 'beforefieldinit' from the type and the field won't be initialized at an unexpected time. 
3) ... better option?

**Comment by stephentoub** [comment]
I think it'd be reasonable to change:
```C#
internal static readonly SNILoadHandle SingletonInstance = new SNILoadHandle();
```
to instead be something like:
```C#
private static readonly Lazy<SNILoadHandle> s_sniSingleton = new Lazy<SNILoadHandle>(() => new SNILoadHandle());
internal static SNILoadHandle SingletonInstance => s_sniSingleton.Value; // lazily initialized to avoid loading on wrong platforms
```
basically your option (1).

@saurabh500, @corivera?

**Comment by stephentoub** [comment]
In terms of milestone, @EgorBo, you consume from master via source, right?  If so, seems like this could be pushed to post-2.0, in terms of a fix not needing to be ported to release/2.0, correct?

**Comment by saurabh500** [comment]
To consume a purely managed SNI implementation, you should look at using the files SqlClient uses for Unix. Windows implementation and build configuration was done in a way that Managed and Native SNI co-exist.

**Comment by saurabh500** [comment]
Also, I dont think this is a bug for 2.0.0 
@EgorBo Let me know if you need any help with the files related to pure managed sni implementation. 
I am moving this to 2.1.0

**Comment by saurabh500** [comment]
Even if managed SNI is consumed using the Unix compiled files, you need to include the right Windows/Unix files with Managed SNI for Integrated Auth.

**Comment by EgorBo** [comment]
@stephentoub yes we consume sources from a submodule pointing to corefx/master. And yes definitely not a bug for 2.0.0
@saurabh500 well, could you please tell me why it's important for corefx to have a native SNI impl aside with the managed one? We can also include the native lib to mono but I am not sure if we really need it.

**Comment by saurabh500** [comment]
We want to move away from the Native sni.dll which is specific to Windows. However we ran into some issues with it during 2.0 timeframe. The issue was related to performance during async operations. 

We kept native SNI around as a backup option. Switch from Managed SNI to native SNI was behind an appcontext switch which has been removed to make Native SNI the default Windows impl on 2.0 
One of the issues we are investigating with Managed SNI is at https://github.com/dotnet/corefx/issues/19836

**Comment by EgorBo** [comment]
@saurabh500 ah ok, I guess we will just use the Unix impl for mono-[windows](https://github.com/mono/mono/pull/4893/files#diff-57fdff8162e3d13094cf0dacc1dc39da) in this case. 
@marek-safar What do you think, do we need to 100% copy corefx behavior here and also include both implementations (it means we will have to include sni.dll for 3 architectures to mono).

**Comment by EgorBo** [comment]
The issue can be closed, we decided to use Managed SNI and after replacing .Windows.cs with .Unix.cs - the issue doesn't reproduce anymore on mono-windows.
