### ISSUE TITLE
CI jobs are succeeding despite FailFasts

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20172]
Eg https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/8272/ failed in 5 libraries but it shows as success. this means the PR succeds and the failure hits outer loop runs.

It seems that the return code is 0 .. and no doubt CI relies on it not being 0.

```
  total elapsed time 0:00:26.004000
  Trying to find crash dumps for project: System.Xml.RW.XmlReader.Tests
  Uploading dump file: C:\Users\DOTNET~1\AppData\Local\Temp\CoreRunCrashDumps\dotnet.exe.5644.dmp
  Finished running tests.  End time=13:30:49.34, Exit code = 0
```

Repro: Just do `Debug.Assert(false)` and run it through CI.

**Comment by danmosemsft** [comment]
This allowed https://github.com/dotnet/corefx/issues/20163 to get through CI and tank the runs.

**Comment by karelz** [comment]
This is a P0 for Networking - we are chasing down one real-world issue  #7812 (reported by ~5 customers) which occasionally happens in CI. We need crash dump from the failure - @schen381 is just changing the test to FailFast.
@weshaggard @mellinoe can we get attention to this ASAP? Any hacky workaround is fine. It is blocking the most scary bug in Networking for 2.0 :(

cc @schen381 @DavidGoll @davidsh @CIPop

**Comment by karelz** [comment]
cc @mmitche

**Comment by mmitche** [comment]
Yep, you need to return non-zero codes

**Comment by karelz** [comment]
@mmitche you = who? The assert? Test runner? Host?

**Comment by mmitche** [comment]
In the configured Jenkins build step (I assume it's running a batch file), must return non-zero for failure.  That means feeding it all the way from the test-runner on up.  My guess is that it's already fed properly in most cases.

**Comment by weshaggard** [comment]
It would appear as though dumplying isn't correctly passing along failure exit codes. I will have a look. While this is a unique case there are a few places where the exit codes don't correctly fail CI, see https://github.com/dotnet/corefx/pull/19122 where I've been trying to track some down in my spare time. However I agree this one is particularly bad so I will focus on getting it fixed.

**Comment by danmosemsft** [comment]
@mmitche question is though why this showed up correctly as failures in Helix. From talking to @Chrisboh he suggested that Helix runs check exit code + prsence of results xml, whereas Jenkins runs only look for the results xml. Given xunit was terminated, there would be no results xml. 

@MattGal

**Comment by danmosemsft** [comment]
Oh, I guess I had that backwards. Jenkins only looks at error code - that would explain the difference.

**Comment by mmitche** [comment]
@danmosemsft You can set Jenkins to fail on lack of test results xml files, but it has no idea what is going on in the step so it won't know if one of all of them is missing.  There are also some cases we've seen where failures print xml files, but ones with no failures, so relying on post-run analysis isn't great.

**Comment by danmosemsft** [comment]
Perhaps before starting xunit we could write out a dummy xml file with just one failure in, so that we get a failure if xunit dies. Returning non zero seems less hacky but maybe we should do both.

**Comment by mmitche** [comment]
@danmosemsft We know that xunit died right?  It would return a non-zero code?

**Comment by MattGal** [comment]
XUnit also returns non-0 for any test failure as well.   The version used in CoreFX will have return codes from 0..5 for "normal" execution and anything outside of that is expected to be un-handled exception.

**Comment by danmosemsft** [comment]
@karelz not sure whether networking folk need this fixed in 2.0 also. If so it would need a build tools update.

**Comment by karelz** [comment]
We can catch it just in master. It won't be that different.

**Comment by weshaggard** [comment]
>If so it would need a build tools update.

We plan to do a buildtools update in the release/2.0.0 branches once all the engineering work is done so this fix might just come along for the ride.

**Comment by weshaggard** [comment]
Fixed with https://github.com/dotnet/corefx/pull/20195.
