### ISSUE TITLE
Console.ReadLine() throws on CentOS

### ISSUE THREAD

**Issue by dinjonya** [dotnet/corefx#20178]
my testConsole publish on the centos server,
the console last line code is Console.ReadLine();

nohup dotnet xxx.dll & 
the console throw excetption:
System.UnauthorizedAccessException: Access to the path is denied. -

please help me ! I need help. how can do it

**Comment by karelz** [comment]
Which version of .NET Core did you try? Did you try to search / ask on StackOverflow?

**Comment by dinjonya** [comment]
my csproj  RuntimeIdentifiers  section is<RuntimeIdentifiers>win7-x64;centos.7-x64;</RuntimeIdentifiers>

**Comment by karelz** [comment]
Which version of .NET Core though? 1.0, 1.1, or 2.0?

**Comment by danmosemsft** [comment]
@karelz I believe he's indicating 1.1.
@dinjonya please share a minimal repro case including all steps and code - just a few lines if possible.

**Comment by karelz** [comment]
Oh, it was edited after my reply :)

**Comment by wjzhou** [comment]
I think this is expected, right?
The nohup will replace the stdin with /dev/null, with O_WRONLY.
Read from that will return an error.

**Comment by wfurt** [comment]
I think @wjzhou is right. man page for nohup says "redirects stdin from unreadable file".
I think we should close this @karelz
