### ISSUE TITLE
Quasi-support ShellExec for UWP

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20204]
We didn't ask for ShellExecuteEx to be added to the WACK so for UWP we should make some attempt to use Windows.System.Launcher and if it fails fall back to Process.Start. That ought to give us at least URL support.

@JeremyKuhne

**Comment by danmosemsft** [comment]
This is optional for UWP. Do this work last.

**Comment by JeremyKuhne** [comment]
There isn't a way to get the process for what we just launched, so this will be a little weird to implement / test. We should only attempt to use this API if UseShellExecute was requested.

https://docs.microsoft.com/en-us/uwp/api/windows.system.launcher

**Comment by danmosemsft** [comment]
I agree

**Comment by joperezr** [comment]
@danmosemsft do you think we should still do this for future versions of UWP or should we close it?

**Comment by danmosemsft** [comment]
> There isn't a way to get the process for what we just launched, so this will be a little weird to implement / test. 

This is also true on desktop when I Process.Start on a folder with UseShellExecute=true - it pops explorer and leaves the Process object unconnected to any process. So I think it's OK (although as you say hard to test)

I do think this is useful, but it's not on any priority list. I think we're using UWP6.1 for "unscheduled but UWP only" work.

**Comment by joperezr** [comment]
sounds good, I'll keep it as is then and flag it up for grabs in case people in the community are interested in this one.
