### ISSUE TITLE
UWP Cleanup: Remove common unreferenced UAP PAL files

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#20212]
Tracking common UAP PAL files that need to be removed when they are not referenced by any contract:

- [X] HostInformationPal.Uap.cs
- [ ] ContextAwareResult.Uap.cs
- [ ] CompletionPortHelper.Uap.cs

**Comment by CIPop** [comment]
@caesar1995 /cc @davidsh @DavidGoll 
There is nothing in this or linked comment explaining why `ContextAwareResult.Uap.cs` and related cannot be removed.
Having .Uap files in PAL means we have behavior differences between .Net Framework, .Net Core in Windows vs UAP apps.

**Comment by caesar1995** [comment]
Ok, I will put analysis here.

**Comment by caesar1995** [comment]
Sorry, after my investigation, the `ContextAwareResult.Uap.cs` can be removed. I will submit a PR to correct my mistake.

I will put my [analysis](https://github.com/dotnet/corefx/issues/20135#issuecomment-311796670) before making any decisions next time.

**Comment by caesar1995** [comment]
Fixed in #21670.
