### ISSUE TITLE
[API Change] Extension AsSpan(this string text) -> AsReadOnlySpan(this string text)

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#20242]
From #18420

Extension change to match other ReadOnlySpan return methods
```csharp
public static ReadOnlySpan<char> AsSpan(this string text);
```
to
```csharp
public static ReadOnlySpan<char> AsReadOnlySpan(this string text);
```

**Comment by ahsonkhan** [comment]
cc @shiftylogic, @KrzysztofCwalina, @terrajobst - api-ready-for-review

**Comment by weshaggard** [comment]
Api Review: Approved

- After decision the reviewers agreed we should be consistent and use AsReadOnlySpan for any methods that return a ReadOnlySpan.

**Comment by ahsonkhan** [comment]
@karelz, adding up-for-grabs

This issue is fairly easy to resolve. It is a method rename (along with it's uses) and shouldn't take more than 1-2 hours (including testing).

**Comment by adriangodong** [comment]
First time contributor, I can take this.

**Comment by karelz** [comment]
@adriangodong cool! Collaborator invite sent. Just remember to turn off repo notifications (300+ per day), otherwise you will be DoS'd. Let me know when you accept, so that we can assign this issue to you.

Also be warned that Changing public APIs is a bit involved and not yet documented ideally.
You can find docs in wiki (also linked from repo README.MD). Please help us improve them (it is RW for everyone): https://github.com/dotnet/corefx/wiki/New-contributor-Docs#contributing-guide

**Comment by adriangodong** [comment]
@karelz Invite accepted

**Comment by stephentoub** [comment]
@ahsonkhan, the method in corelib is still named AsSpan:
https://github.com/dotnet/coreclr/blob/8a5e061576e8ff7e6505059302460dcdd2f463b5/src/mscorlib/shared/System/Span.NonGeneric.cs#L121
Should this issue be re-opened to track updating that as well, or is that tracked elsewhere?

**Comment by ahsonkhan** [comment]
@stephentoub, Thanks for catching that! I have re-opened this issue.

@adriangodong, would you like to tackle the rename in corelib as well?
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Span.NonGeneric.cs#L121

**Comment by adriangodong** [comment]
@ahsonkhan Sure, I'll take a look at that class.

**Comment by jkotas** [comment]
Remainins to be done:
- Change references to AsSpan to AsReadOnlySpan in CoreFX repo (once the next `Update CoreClr to ...` goes into CoreFX repo)
- Delete the obsolete method from CoreCLR CoreLib

**Comment by adriangodong** [comment]
AsSpan -> AsReadOnlySpan in CoreFX is done (https://github.com/dotnet/corefx/pull/23563/commits/f4b098d4170e74e84d1530f4a40d821fe0f97cda).

@ahsonkhan @jkotas I have a question about the following test class:
https://github.com/dotnet/corefx/blob/f4b098d4170e74e84d1530f4a40d821fe0f97cda/src/System.Memory/tests/ReadOnlySpan/AsSpan.cs

I can't seem to use `System.Span.AsReadOnlySpan` extension from `coreclr`. What stops us from doing this and drop `System.SpanExtensions.AsReadOnlySpan` from `corefx`?

**Comment by adriangodong** [comment]
nvm, rtfm https://github.com/dotnet/coreclr#relationship-with-the-corefx-repository
