### ISSUE TITLE
Test failures: System.Net.NameResolution.PalTests.NameResolutionPalTests / GetHostByName_HostName & TryGetAddrInfo_HostName

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20245]
## Types of failures

Affected tests:
* GetHostByName_HostName
* TryGetAddrInfo_HostName

### TryGetAddrInfo_HostName

`TryGetAddrInfo_HostName` test in build 20171203.01 (same for OSX and Linux):
```
Assert.Equal() Failure
Expected: Success
Actual:   HostNotFound
at System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_HostName() in /Users/buildagent/agent/_work/320/s/corefx/src/System.Net.NameResolution/tests/PalTests/NameResolutionPalTests.cs:line 129
```

### GetHostByName_HostName

The error is:
* OSX - Device not configured
* Linux - No such device or address
(same callstack)

`GetHostByName_HostName` test in build 20171203.01 (OSX):
```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Device not configured
at   System.Net.NameResolutionPal.GetHostByName(String hostName) in   /Users/buildagent/agent/_work/320/s/corefx/src/System.Net.NameResolution/src/System/Net/NameResolutionPal.Unix.cs:line   157
at System.Net.NameResolution.PalTests.NameResolutionPalTests.GetHostByName_HostName()   in   /Users/buildagent/agent/_work/320/s/corefx/src/System.Net.NameResolution/tests/PalTests/NameResolutionPalTests.cs:line   53
```

## History of failures

Note: The tests always both fail - maybe bad setup?

Day | Build | OS | Test
-- | -- | -- | --
9/5 | 20170905.02 | Debian90 | GetHostByName_HostName & TryGetAddrInfo_HostName
9/10 | 20170910.01 | Ubuntu14.04 | GetHostByName_HostName & TryGetAddrInfo_HostName
9/15 | 20170915.02 | Debian87 | GetHostByName_HostName & TryGetAddrInfo_HostName
9/16 | 20170916.02 | Debian87 | GetHostByName_HostName & TryGetAddrInfo_HostName
9/20 | 20170920.03 | Debian90 | GetHostByName_HostName & TryGetAddrInfo_HostName
9/27 | 20170927.01 | Debian87 | GetHostByName_HostName & TryGetAddrInfo_HostName
9/27 | 20170927.02 | Debian87 | GetHostByName_HostName & TryGetAddrInfo_HostName
10/2 | 20171002.01 | Debian87 | GetHostByName_HostName & TryGetAddrInfo_HostName
10/3 | 20171003.01 | Debian87 | GetHostByName_HostName & TryGetAddrInfo_HostName
10/3 | 20171003.02 | Debian90 | GetHostByName_HostName & TryGetAddrInfo_HostName
10/9 | 20171009.04 | SLES12 | GetHostByName_HostName & TryGetAddrInfo_HostName
10/23 | 20171020.52 | Debian87 | GetHostByName_HostName & TryGetAddrInfo_HostName
10/25 | 20171025.07 | Debian87 | GetHostByName_HostName & TryGetAddrInfo_HostName
10/26 | 20171026.01 | Debian87 | GetHostByName_HostName & TryGetAddrInfo_HostName
11/16 | 20171116.01 | OSX10.12 | GetHostByName_HostName & TryGetAddrInfo_HostName
11/16 | 20171116.02 | Suse42.2 | GetHostByName_HostName & TryGetAddrInfo_HostName
12/3 | 20171203.01 | OSX10.12 | GetHostByName_HostName & TryGetAddrInfo_HostName

# Original report

This is in 2.0 on Ubuntu 1604.

https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170524.02/workItem/System.Net.WebProxy.Tests/analysis/xunit/System.Net.Tests.WebProxyTest~2FBypassOnLocal_MatchesExpected

```
Unhandled Exception of Type System.Net.Internals.SocketExceptionFactory+ExtendedSocketException
Message :
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : No such device or address
Stack Trace :
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6) in /root/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 46
   at System.Net.Dns.ResolveCallback(Object context) in /root/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 290
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) in /root/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 420
   at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) in /root/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 562
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Tests.WebProxyTest.<BypassOnLocal_MemberData>d__10.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext() in /root/corefx/src/System.Linq/src/System/Linq/Select.cs:line 133
```

**Comment by danmosemsft** [comment]
again, broke CI
https://mc.dot.net/#/user/schen381/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fportable~2Fcli~2F/d621e61a47d2042815527852228651de8e74f852/workItem/System.Net.WebProxy.Tests/analysis/xunit/System.Net.Tests.WebProxyTest~2FBypassOnLocal_MatchesExpected

**Comment by danmosemsft** [comment]
Same issue  for GetHostByName_HostName and TryGetAddrInfo_HostName on Ubuntu 1604


https://mc.dot.net/#/user/schen381/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fportable~2Fcli~2F/d621e61a47d2042815527852228651de8e74f852/workItem/System.Net.NameResolution.Pal.Tests/analysis/xunit/System.Net.NameResolution.PalTests.NameResolutionPalTests~2FGetHostByName_HostName

https://mc.dot.net/#/user/schen381/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fportable~2Fcli~2F/d621e61a47d2042815527852228651de8e74f852/workItem/System.Net.NameResolution.Pal.Tests/analysis/xunit/System.Net.NameResolution.PalTests.NameResolutionPalTests~2FTryGetAddrInfo_HostName

**Comment by stephentoub** [comment]
Again here:
https://mc.dot.net/#/user/AtsushiKan/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fportable~2Fcli~2F/6ec19f71035834ce341ea0c73812208ccaa1dd9d/workItem/System.Net.NameResolution.Pal.Tests/analysis/xunit/System.Net.NameResolution.PalTests.NameResolutionPalTests~2FGetHostByName_HostName

**Comment by danmosemsft** [comment]
Again here

https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fportable~2Fcli~2F/fb8b5bd13c0251b01a88cd3e65962ec2575fb023/workItem/System.Net.WebProxy.Tests/analysis/xunit/System.Net.Tests.WebProxyTest~2FBypassOnLocal_MatchesExpected

@karelz does anyone want to look at these or should we disable them for Ubuntu 1404 & 1604 ?

**Comment by karelz** [comment]
@wfurt can you please take a look at this one?

**Comment by stephentoub** [comment]
Also failed here, on Debian 8.7:
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/0fda5071af73601af0ef4f451ce9ce292ae2ca0e/workItem/System.Net.WebProxy.Tests/analysis/xunit/System.Net.Tests.WebProxyTest~2FBypassOnLocal_MatchesExpected

**Comment by danmosemsft** [comment]
Failed in #20247

**Comment by Jiayili1** [comment]
This issue is repro on Core Tests (Master), detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170606.01/workItem/System.Net.NameResolution.Pal.Tests/analysis/xunit/System.Net.NameResolution.PalTests.NameResolutionPalTests~2FGetHostByName_HostName

**Comment by danmosemsft** [comment]
Also on suse 422
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170606.01/workItem/System.Net.NameResolution.Pal.Tests/analysis/xunit/System.Net.NameResolution.PalTests.NameResolutionPalTests~2FGetHostByName_HostName

@wfurt have you had a chance to look?

**Comment by danmosemsft** [comment]
The other test fails thus, I'm assuming common issue:
```
Assert.Equal() Failure\nExpected: Success\nActual:   HostNotFound
Stack Trace :
   at System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_HostName() in /root/corefx/src/System.Net.NameResolution/tests/PalTests/NameResolutionPalTests.cs:line 128
```

**Comment by wfurt** [comment]
I'v been trying to figure out how to run this in loop with custom build @danmosemsft 
But I'm not there yet. I see this is failing but I need to get more reliable repro. 
So far I did not repro on my local Ubuntu machine.

**Comment by danmosemsft** [comment]
@wfurt it may be related to the way the Helix (test) machines are configured. Although, even then it's obviously not deterministic. You could talk to @MattGal to see if you can get access to one to loop the test there. Another option is to add lots of logging, submit that and wait for a hit. Thanks for looking, this one looks like it will be tricky.

**Comment by wfurt** [comment]
I have some update on this. I did set up fresh Ubuntu and I get 100% repro case. 

All those tests assume that "hostname" will resolve via DNS lookup. That is not true in general case - at least not on Linux. 

furt@DUT:~/dotnet/corefx/src/System.Net.WebProxy/tests$ nslookup dut
;; Got SERVFAIL reply from 10.222.116.92, trying next server
;; Got SERVFAIL reply from 10.222.118.154, trying next server
Server:		10.221.226.11
Address:	10.221.226.11#53

** server can't find dut: SERVFAIL

Name service is not connected to gethostname(). This will only work if proper entry is created in /etc/hosts or in DNS via dyn-dns or via pairing with DHCP. Also even if name is created, it depends to what name server we point to. For example if system points to 8.8.8.8 (public google service) this will probably aways fail. 

In next step I'm going to troubleshoot the random failures. I'll check with @MattGal to see how the infrastructure is set up. Maybe @CIPop also has some ideas from Windows side. 

On longer detour, it is frustrating that the tests do not provide any useful information on failure. It may be worth of adding some method to automatically call on failure. Instrumenting such callback could provide more information if this is truly transient or if it is setup/configuration problem in some cases.

**Comment by Jiayili1** [comment]
Following test failed with same issue: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170626.01/workItem/System.Net.WebProxy.Tests/analysis/xunit/System.Net.Tests.WebProxyTest~2FBypassOnLocal_MatchesExpected

**Comment by mellinoe** [comment]
Failed here: https://mc.dot.net/#/user/mellinoe/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/d4f956f62e0def412e948c95c83f9c9822a6eb47/workItem/System.Net.WebProxy.Tests/wilogs

**Comment by wfurt** [comment]
We tried to set up repro with @MattGal 

https://github.com/dotnet/core-eng/issues/903#issuecomment-308209397

>Hi Tomas,
>                For #2 https://github.com/dotnet/corefx/issues/20245, I ran the exact test bits used from a >recent release/2.0.0 Debug test run 600 times:
>https://helix.dot.net/api/2017-04-14/aggregate/jobs?>groupBy=job.name&maxResultSets=1&filter.name=0797b7a3-e755-4c41-a3e9c115b84b1cb9&access_token=
> 
>The Xunit facts in the test passed all 15K times.  Not sure what to tell you, but I can repeat the >experiment in a variety of ways fairly easily if you want.
> 
>Thanks,
>Matt

At this point I see no evidence this is unique to specific version of OS. 
I was not able to reproduce it locally either trying on several different Linux versions.  

We will either find way how to reproduce it more predictably or instrument tests to collect more information on failure. 
Those three tests are also making certain assumption which may not be true in general case. 
We can add code to check the pre-condition and skip tests if proper DNS entry is not present (Tests assume that value of "hostname()" is resolvable via DNS lookup)

**Comment by Jiayili1** [comment]
Failed again: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170627.01/workItem/System.Net.NameResolution.Pal.Tests/analysis/xunit/System.Net.NameResolution.PalTests.NameResolutionPalTests~2FGetHostByName_HostName

**Comment by Jiayili1** [comment]
failed again in Master branch, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170927.01/workItem/System.Net.NameResolution.Pal.Tests/analysis/xunit/System.Net.NameResolution.PalTests.NameResolutionPalTests~2FGetHostByName_HostName

**Comment by Sunny-pu** [comment]
failed again in Master branch, detail:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171116.01/workItem/System.Net.NameResolution.Pal.Tests/analysis/xunit/System.Net.NameResolution.PalTests.NameResolutionPalTests~2FGetHostByName_HostName

**Comment by karelz** [comment]
Removed test `WebProxy_BypassOnLocal_MatchesExpected` from the issue as it last failed on 9/2 and between 2017/5-9 it failed at least every 2 weeks.

**Comment by danmosemsft** [comment]
@karelz These broke CI on macOS 10.12 .. should they be outerloop?

https://mc.dot.net/#/user/danmosemsft/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/4f0763bf2447f7293e980b299e64e5c72748a499/workItem/System.Net.NameResolution.Pal.Tests

**Comment by karelz** [comment]
I didn't see them failing enough to move them into Outerloop. If it happen again in next 3-4 weeks, let's do it.
It almost feels like the tests are sensitive to environment / machine config.

**Comment by stephentoub** [comment]
Failed here:
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/20b481acdf8e4146f359dc8b388f823c22a8541b/workItem/System.Net.NameResolution.Pal.Tests/analysis/xunit/System.Net.NameResolution.PalTests.NameResolutionPalTests~2FGetHostByName_HostName
```
2018-01-31 08:11:52,617: INFO: proc(54): run_and_log_output: Output: Discovering: System.Net.NameResolution.Pal.Tests
2018-01-31 08:11:52,752: INFO: proc(54): run_and_log_output: Output: Discovered:  System.Net.NameResolution.Pal.Tests
2018-01-31 08:11:52,797: INFO: proc(54): run_and_log_output: Output: Starting:    System.Net.NameResolution.Pal.Tests
2018-01-31 08:11:54,278: INFO: proc(54): run_and_log_output: Output:    System.Net.NameResolution.PalTests.NameResolutionPalTests.GetHostByName_HostName [FAIL]
2018-01-31 08:11:54,280: INFO: proc(54): run_and_log_output: Output:       System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Device not configured
2018-01-31 08:11:54,285: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-01-31 08:11:54,371: INFO: proc(54): run_and_log_output: Output:          /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/src/System/Net/NameResolutionPal.Unix.cs(157,0): at System.Net.NameResolutionPal.GetHostByName(String hostName)
2018-01-31 08:11:54,372: INFO: proc(54): run_and_log_output: Output:          /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/tests/PalTests/NameResolutionPalTests.cs(52,0): at System.Net.NameResolution.PalTests.NameResolutionPalTests.GetHostByName_HostName()
2018-01-31 08:11:56,405: INFO: proc(54): run_and_log_output: Output:    System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_HostName [FAIL]
2018-01-31 08:11:56,405: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-01-31 08:11:56,405: INFO: proc(54): run_and_log_output: Output:       Expected: Success
2018-01-31 08:11:56,405: INFO: proc(54): run_and_log_output: Output:       Actual:   HostNotFound
2018-01-31 08:11:56,406: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-01-31 08:11:56,406: INFO: proc(54): run_and_log_output: Output:          /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/tests/PalTests/NameResolutionPalTests.cs(128,0): at System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_HostName()
2018-01-31 08:11:56,429: INFO: proc(54): run_and_log_output: Output: Finished:    System.Net.NameResolution.Pal.Tests
```

**Comment by wfurt** [comment]
Just a note, that DNS also depends on external service and may be sensitive to network outages. 
As I mentioned above some test do assume that their "hostname" will resolve via DNS lookup.
That is probably automatic on  windows but it may or may not work on Unix and it may depend on dns/dhcp integration.

**Comment by danmosemsft** [comment]
OSX10.12 again. @karelz we could disable just for that?

**Comment by stephentoub** [comment]
Failed again
https://mc.dot.net/#/user/dotnet-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/87333acf510f09c8ad0c3165d55180636726fc58/workItem/System.Net.NameResolution.Pal.Tests/analysis/xunit/System.Net.NameResolution.PalTests.NameResolutionPalTests~2FGetHostByName_HostName

**Comment by stephentoub** [comment]
I'm disabling these.  They're failing all over the place and driving me nuts.

**Comment by karelz** [comment]
Sounds good, I was about to ask someone on the team to do that anyway ...

**Comment by Sunny-pu** [comment]
failed again:
https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20180314.01/workItem/System.Net.NameResolution.Pal.Tests/analysis/xunit/System.Net.NameResolution.PalTests.NameResolutionPalTests~2FGetHostByName_HostName

**Comment by rmkerr** [comment]
On Linux this test depends on the configuration of `/etc/hosts`, which I suspect isn't consistent between machines. 

For example, the Azure VM I use for Linux development was by default configured in such a way that this test would fail. In the process of setting the machine up to work with remote desktop, I edited the hosts file, and the test passes with the new configuration. 

I'm waiting to hear back on whether or not we reset the state of /etc/hosts between runs. I can't say anything definitive until I get a response on that, but I do suspect that this is just a test/machine configuration issue.

**Comment by danmosemsft** [comment]
Ypu could perhaps log the content of etc/hosts in the failure case?

**Comment by rmkerr** [comment]
That sounds reasonable. I'll see if I can add logging and re-enable the test tomorrow.

Also, adding to the evidence that this is caused by the machine config is the following check elsewhere in the NameResolutionPal tests:
https://github.com/dotnet/corefx/blob/643bccc7f2c24a897cc15c42486d4184e1f931eb/src/System.Net.NameResolution/tests/PalTests/NameResolutionPalTests.cs#L97-L104 The network configuration mentioned there might not be in /etc/hosts, but it looks like it could cause the same issue.

**Comment by wfurt** [comment]
It seems like on Windows attempt to resolve "hostname" always works. On Unix it may or may not depending on configuration. It would be nice to check if lookup work and skip tests if it does not.

**Comment by rmkerr** [comment]
After discussing this issue with @karelz and @wfurt, I think that we should just be skipping this test on Unix. The ability to resolve the localhost just isn't a guarantee that is made on Unix. 

In the interest of "testing as much as we can" I'm going to enable the test, but pass it if we get the specific error that indicates we haven't been able to resolve the localhost on Unix. That way we'll hopefully still see failures if things go wrong somewhere else.
