### ISSUE TITLE
Question: ClaimTypes and Schema URIs

### ISSUE THREAD

**Issue by JoshuaGarrison27** [dotnet/corefx#20244]
File in question: https://github.com/Microsoft/referencesource/blob/master/mscorlib/system/security/claims/ClaimTypes.cs

If I want to create some custom claim types and I want to keep to the same formatting and code style as in this file, then is there a place where all possible (already created) URIs are listed? For example, is there one for DisplayName or userPrincipleName in active directory? There are just examples. I just want to make sure that I am writing good clean code instead of just using some obscure value for these properties.

Thanks!

**Comment by bartonjs** [comment]
@JoshuaGarrison27 Wow, sorry this slipped under the radar for so long.

I don't think there's any central registry in .NET for claim types.  The usage for [AuthenticationInstant](http://referencesource.microsoft.com/#mscorlib/system/security/claims/ClaimTypes.cs,b5796cb742eb0df2,references), for example, doesn't show anywhere that it's referenced in an all-up list (other than the file it was declared in).

UserPrincipalName (aka UPN) is defined in that file, `ClaimTypes.UPN`.  I don't see one that obviously maps to DisplayName from LDAP.

What would you expect such a place to look like, and where would you expect it?

**Comment by bartonjs** [comment]
Since it's unclear what the desired endstate is here, closing the issue (we can always reopen it if there's more data).
