### ISSUE TITLE
DeflateStream's crc32 calculation consuming up to 50% of GZipStream write time

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#2025]
Writing to a GZipStream is spending the majority of its execution time in zlib's deflate implementation, but the remainder is mostly spent in a crc32 calculation, anywhere from 0 to 50% depending on how complicated the compression is.  We should investigate whether using zlib's crc32 would result in measurably faster results.

**Comment by Maxwe11** [comment]
How to measure this? If any perf tests present in repo how to run it?

**Comment by stephentoub** [comment]
I wrote some benchmarks locally and was profiling those with VS.

Though I just realized that this would be a difficult issue to grab given that we haven't yet published clrcompression.dll and it doesn't currently export crc32.  I'm going to remove the up for grabs and assign it to myself for now.  Thanks for the interest, though!

**Comment by justinvp** [comment]
FYI for potential future optimizations... Intel implemented some patches to zlib and one of the changes was to make use of the SSE4.2 crc32 instruction on systems that support it. http://www.intel.com/content/dam/www/public/us/en/documents/white-papers/zlib-compression-whitepaper-copy.pdf

**Comment by stephentoub** [comment]
Thanks, Justin.  Yeah, I saw that. All the more reason to use it :smile:

**Comment by bjjones** [comment]
I’m happy to see this issue being raised. I identified this myself a few months back and spent some time working to find a solution. I agree utilizing the hardware instruction would be optimal.

I’d be very interested in taking ownership of this issue when clrcompression.dll becomes available.

**Comment by stephentoub** [comment]
@bjjones, you're welcome to give it a go.  I already updated clrcompression.dll to export crc32, and that updated version should already be in the NuGet packages now being used by corefx.  Thanks!

**Comment by stephentoub** [comment]
Fixed by #3817 and #3987
