### ISSUE TITLE
Move "GenerateReferenceSource" target into buildtools

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#20258]
We should move this new target into buildtools if we decide that the functionality is general-purpose enough to warrant it. This might involve cleaning it up, making it "automatic", and fixing some of the problems around multiple build configurations.

**Comment by weshaggard** [comment]
Issue moved to [dotnet/buildtools #1833](https://github.com/dotnet/buildtools/issues/1833) via [**ZenHub**](https://www.zenhub.com/)
