### ISSUE TITLE
Port four new reference assembly projects to release/2.0.0

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#20260]
This tracks porting the changes in https://github.com/dotnet/corefx/pull/20211 to the release/2.0.0 branch.

I've made a targeted fix which will reduce the IL size of the reference assemblies we ship with .NET Core. In total, we will bundle 729 KB less in the Microsoft.NETCore.App package. There is no observable difference other than the file size. This change just strips out the implementation IL for the assembly, which is already unused.

**Comment by mellinoe** [comment]
Done.

**Comment by karelz** [comment]
Can you link the PR please?

**Comment by mellinoe** [comment]
Pull request here: https://github.com/dotnet/corefx/pull/20261
