### ISSUE TITLE
IsWindowsImplementation / IsNotWindowsImplementation semantics

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#20270]
This is to track follow-up from the discussion at https://github.com/dotnet/corefx/pull/20250#pullrequestreview-40129192

src/System.Net.HttpListener/tests/GetContextHelper.cs

Helpers : IsWindowsImplementation / IsNotWindowsImplementation should either have better name description or should have the implementation changed to mean what they actually do: Windows but not Nano or UWP.

**Comment by stephentoub** [comment]
@CIPop, what implementation is mean to be used on Nano or UWP?  If the managed implementation, my change in https://github.com/dotnet/corefx/pull/20265 addresses that, by making IsWindowsImplementation mean "is this using the implementation that uses Interop.HttpAPI", and IsNotWindowsImplementation the inverse.

**Comment by CIPop** [comment]
> what implementation is mean to be used on Nano or UWP?

I'd need to confirm this but I'm almost certain that on NanoServer we should use the one based on HTTP.SYS. ( @davidsh , @DavidGoll - do you have more info about this?)
On UWP my understanding is that we'll use the Managed implementation. 

> my change in #20265 addresses that, by making IsWindowsImplementation mean "is this using the implementation that uses Interop.HttpAPI", and IsNotWindowsImplementation the inverse.

I think that's fine. This is more about the confusion generated by the name of this constant (see referenced PR) - I didn't want to block that PR just for that rename.
If we end up keeping the current implementation maybe we can simply change the names to 'IsUsingHttpSys' or 'IsUsingManagedImplementation'.

**Comment by davidsh** [comment]
>I'd need to confirm this but I'm almost certain that on NanoServer we should use the one based on HTTP.SYS. ( @davidsh , @DavidGoll - do you have more info about this?)

This is a good question, i.e. should we require that Nano server install the optional httpapi component in order to use .NET Core HttpListener.  I think the answer is probably yes. But we should document this somehow for the Nano folks and devs that use Nano server.

**Comment by CIPop** [comment]
> optional httpapi component

This list appears to have it Nano by default: https://msdn.microsoft.com/en-us/library/mt588480(v=vs.85).aspx#httpapi.dll

**Comment by hughbe** [comment]
The idea behind these is that they are temporary bool values to allow switching between running the HTTP.sys/managed specific tests. The idea is that we fix all the instances where this is used. They are just to avoid spammy test failures when running the managed tests on Windows.
Any method marked as conditional with these should have an issue associated with it.

**Comment by davidsh** [comment]
>I'd need to confirm this but I'm almost certain that on NanoServer we should use the one based on HTTP.SYS. 

Nano Server has become "Nano Container" and it no longer supports httpapi.dll (http.sys component).

Long term, we are looking into being able to support HttpListener class on Nano using managed implementation.  For UWP, managed implementation is used for HttpListener.

For now, though, this issue will be closed.
