### ISSUE TITLE
Test retargeting netframework project while using netstandard.library.netframework

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#20279]
We should do this in both a netcore.sdk project as well as a legacy project using package reference.  Packages.config is not interesting since retargeting has never been supported there.

@davkean mentioned the design time build may not react well when retargeting changes targets imported.

Interesting scenarios:
1. Reference an n 2.0 package that cross-compiles (like immutable) in net461.
2. Retargeting to net46.
3. Retargeting to net47. (Interesting in valuetuple case).

There are others too.  Filing this to ensure I don't forget to test this.

**Comment by danmosemsft** [comment]
@ericstj Eric when do you expect to do this? Is it likely to throw up bugs in 2.0 corefx (almost closed down) or only in tooling?

**Comment by ericstj** [comment]
Tooling, all of this has moved upstack.  I've done this testing initially with the new implementation and haven't found issues.  I can close it.
