### ISSUE TITLE
Inconsistent, unexpected bounds check in RemoveRange

### ISSUE THREAD

**Issue by sharwell** [dotnet/corefx#2028]
* `ImmutableArray<T>.RemoveRange` requires 0<=index<size
* `ImmutableList<T>.RemoveRange` requires 0<=index<size *unless* size is 0, in which case it allows index=0

These bounds checks are not only inconsistent with each other, but they do not behave the same way as other range-based methods. In both of the cases above, the allowed range for index should be 0<=index<=size, regardless of the current size of the collection.

**Comment by stephentoub** [comment]
cc: @AArnott

**Comment by AArnott** [comment]
I agree with making them consistent. I'd want to double-check a few BCL mutable collections' behavior first.
