### ISSUE TITLE
Desktop: System.ServiceProcess.Tests.ServiceControllerTests.Start_NullArg_ThrowsArgumentNullException failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#20282]
Failed test: System.ServiceProcess.Tests.ServiceControllerTests.Start_NullArg_ThrowsArgumentNullException 

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/66/testReport/System.ServiceProcess.Tests/ServiceControllerTests/Start_NullArg_ThrowsArgumentNullException/

Configuration: outerloop_netfx_windows_nt_debug

MESSAGE:
~~~
Assert.Equal() Failure
   ↓ (pos 0)
  Expected: args[0]
  Actual: Arguments within the 'args' array passed ···
   ↑ (pos 0)
~~~
STACK TRACE:
~~~
at System.AssertExtensions.Throws[T](String paramName, Action action) 
in D:\j\workspace\outerloop_net---903ddde6\src\Common\tests\System\AssertExtensions.cs:line 47 
at System.ServiceProcess.Tests.ServiceControllerTests.Start_NullArg_ThrowsArgumentNullException() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.ServiceProcess.ServiceController\tests\System.ServiceProcess.ServiceController.Tests\ServiceControllerTests.cs:line 165
~~~

**Comment by karelz** [comment]
@safern I assume this is flaky, otherwise we would hear about the failure earlier, right?

**Comment by safern** [comment]
Yes this seems to be flaky as we haven't seen it since the past month that we started having desktop runs in Helix/Jenkins and I haven't seen it on any PR leg. It could be a recently added test as well. 

Will take a look.

**Comment by karelz** [comment]
Thanks for confirmation. No rush. Just wanted to make sure Future is the right milestone ;)

**Comment by danmosemsft** [comment]
AGain I suspect `[ConditionalFact(nameof(RunningWithElevatedPrivileges))]` was not previously true. And netfx parameter value turns out to be different.

**Comment by Jiayili1** [comment]
Failed again: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/67/testReport/System.ServiceProcess.Tests/ServiceControllerTests/Start_NullArg_ThrowsArgumentNullException/
