### ISSUE TITLE
Desktop: System.ServiceProcess.Tests.ServiceControllerTests.ConstructWithServiceName_ToUpper failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#20281]
Failed test: System.ServiceProcess.Tests.ServiceControllerTests.ConstructWithServiceName_ToUpper 

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/66/testReport/System.ServiceProcess.Tests/ServiceControllerTests/ConstructWithServiceName_ToUpper/

Configuration: outerloop_netfx_windows_nt_debug

MESSAGE:
~~~
Assert.Equal() Failure
   ↓ (pos 3)
  Expected: 749b386a-fd41-4bed-951f-75d4a705f7d9
  Actual: 749B386A-FD41-4BED-951F-75D4A705F7D9
   ↑ (pos 3)
~~~
STACK TRACE:
~~~
at System.ServiceProcess.Tests.ServiceControllerTests.AssertExpectedProperties(ServiceController testServiceController) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.ServiceProcess.ServiceController\tests\System.ServiceProcess.ServiceController.Tests\ServiceControllerTests.cs:line 92 
at System.ServiceProcess.Tests.ServiceControllerTests.ConstructWithServiceName_ToUpper() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.ServiceProcess.ServiceController\tests\System.ServiceProcess.ServiceController.Tests\ServiceControllerTests.cs:line 109
~~~

**Comment by karelz** [comment]
@safern I assume the test result is flaky, otherwise we would hear about it earlier, right? Moving to Future based on that assumption.

**Comment by safern** [comment]
Could be flaky or a recently enabled/added test. Will take a look later.

**Comment by danmosemsft** [comment]
Could it be this didn't run before because of `[ConditionalFact(nameof(RunningWithElevatedPrivileges))]`?

And in netfx, it does not behave quite the same (does not return the same casing passed in).

If so the test could just disable for netfx.

**Comment by safern** [comment]
Yes that could be because of ConditionalFact because that was enabled back again yesterday or the day before. Will take a look and disable if it is the case that you pointed out.

**Comment by Jiayili1** [comment]
Failed again: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/67/testReport/System.ServiceProcess.Tests/ServiceControllerTests/ConstructWithServiceName_ToUpper/
