### ISSUE TITLE
ImmutableArray<T>.RemoveRange should not allocate if length is 0

### ISSUE THREAD

**Issue by sharwell** [dotnet/corefx#2029]
Currently `ImmutableArray<T>.RemoveRange` always creates a new underlying array. If `length` is 0, no changes are made to the array so the method should simply return `self`.

**Comment by jasonwilliams200OK** [comment]
:+1: 
Probably something like this: https://github.com/dotnet/coreclr/pull/637.

**Comment by stephentoub** [comment]
@sharwell, are you planning to submit PRs for the various issues you've raised?

**Comment by sharwell** [comment]
If someone beats me to it, that's OK. Right now I'm trying to get [java-immutable](https://github.com/tunnelvisionlabs/java-immutable) into a usable state (which is how I'm finding these). If no one fixes them before I get an initial release out, I'll come back through and make corrections for the various issues I reported.
