### ISSUE TITLE
NullReference Exception using'Microsoft-Diagnostics-DiagnosticSource' EventSource

### ISSUE THREAD

**Issue by vancem** [dotnet/corefx#20315]
Attached repro.  

[NullRefRepo.zip](https://github.com/dotnet/corefx/files/1029702/NullRefRepo.zip)

**Comment by stephentoub** [comment]
Same as https://github.com/dotnet/corefx/issues/20306?

**Comment by vancem** [comment]
Yes, closing #20316

**Comment by vancem** [comment]
Closing dup of #20306
