### ISSUE TITLE
[Proposal]: Add Generic Helper Methods to Enum/Delegate

### ISSUE THREAD

**Issue by HaloFour** [dotnet/corefx#2034]
Currently the helper methods provided by the BCL for working with `Enum` and `Delegate` types are not generic which eliminates type safety and requires additional casting.  I'd like to see generic versions of these methods added to the BCL to cover the common cases.  For example:

```cs
TEnum Enum.Parse<TEnum>(string value) where TEnum : System.Enum, struct;
TEnum Enum.Parse<TEnum>(string value, bool ignoreCase) where TEnum : System.Enum, struct;
bool Enum.TryParse<TEnum>(string value, out TEnum result) where TEnum : System.Enum, struct;
bool Enum.TryParse<TEnum>(string value, bool ignoreCase, out TEnum result) where TEnum : System.Enum, struct;
TEnum? Enum.TryParse<TEnum>(string value) where TEnum : System.Enum, struct;
TEnum? Enum.TryParse<TEnum>(string value, bool ignoreCase) where TEnum : System.Enum, struct;

TDelegate Delegate.Combine<TDelegate>(TDelegate a, TDelegate b) where TDelegate : System.Delegate;
TDelegate Delegate.Combine<TDelegate>(params TDelegate[] delegates) where TDelegate : System.Delegate;
TDelegate Delegate.Remove<TDelegate>(TDelegate source, TDelegate value) where TDelegate : System.Delegate;
TDelegate Delegate.RemoveAll<TDelegate>(TDelegate source, TDelegate value) where TDelegate : System.Delegate;
```

Generic support would also allow new additions to the BCL to cover such scenarios as type-safe delegate subscribing/unsubscribing where the target is a field:

```cs
void Delegate.Combine<TDelegate>(ref TDelegate a, TDelegate b) where TDelegate : System.Delegate;
void Delegate.Combine<TDelegate>(ref TDelegate a, params TDelegate[] delegates) where TDelegate : System.Delegate;
void Delegate.Remove<TDelegate>(ref TDelegate source, TDelegate value) where TDelegate : System.Delegate;
void Delegate.RemoveAll<TDelegate>(ref TDelegate source, TDelegate value) where TDelegate : System.Delegate; 
```

Notably due to limitations in the C# language it would not currently be possible to write these methods using C#, but they could be written using CIL and merged into the resultant assembly.  Such methods are consumable by languages like C# and VB.NET, they just don't support creating them.  They could be written using CIL and merged into the resultant assembly.  Admittedly that would be kludgy, but it would open the door to providing more helper methods around enums and delegates.

**Comment by svick** [comment]
What would be the difference between `Delegate.Combine(ref field, del)` and `field += del`?

**Comment by HaloFour** [comment]
@svick Thread-safety.

The latter roughly translates into `field = Delegate.Combine(field, del)` but since a delegate is immutable if that method is called and the result assigned by two threads at the same time one of the two subscriptions will be lost.  The C# and VB.NET compilers both emit default event adders which take this into account and perform a loop to compare and exchange the resulting delegate.  If you write a custom adder/remover unless you write a similar compare/exchange loop then your event accessors are not thread safe.  It would be trivial for the BCL to provide that out-of-the-box with a generic function accepting the target as a `ref` parameter, which isn't possible without generics constrained to delegates.

Here's a basic implementation of that method, although it could probably be written better if a static method of the `System.Delegate` class:

```cs
public static void Combine<TDelegate>(ref TDelegate source, TDelegate value) where TDelegate : System.Delegate
{
    TDelegate previous = field;
    TDelegate current;
    do
    {
        current = previous;
        TDelegate proposed = (TDelegate)Delegate.Combine(current, value);
        previous = Interlocked.CompareExchange(ref field, proposed, current);
    } while(previous != current);
}
```

**Comment by mburbea** [comment]
@HaloFour , Don't `Enum.TryParse<TEnum>(string value,out TEnum tenum)` already exist?

As for the other overload, those would be good, but don't match the other `.TryParse` methods. I'd love an  `Int.TryParse` that would return `null` if it fails.

I'd also like `Delegate.CreateDelegate<TDelegate>` as it's extraordinarily annoying to have to write this:
`(Func<int,int>)Delegate.CreateDelegate(typeof(Func<int,int>), someMethodInfo)`

**Comment by HaloFour** [comment]
> Don't Enum.TryParse<TEnum>(string value,out TEnum tenum) already exist?

Ah, you're right, but the constraint is `struct`, not `System.Enum`, and will fail at runtime if the generic type parameter isn't an `enum`.  I'd love to see that fixed but I imagine it would be considered a breaking change.

> I'd also like Delegate.CreateDelegate<TDelegate>

Agreed.  My list isn't exhaustive but only meant to start the ball rolling.  DRY and type-safe all at the same time.

**Comment by mburbea** [comment]
True, but C# still, unfortunately, does not support a `System.Enum`, `System.Delegate`, or `System.MulticastDelegate` constraints. I know the CLR does, but the compiler will complain over the BCL implementations until this constraint is relaxed.

**Comment by HaloFour** [comment]
@mburbea The C# and VB.NET compilers don't support generating assemblies with those constraints, but they do support consuming assemblies with those constraints and will happily enforce them.  Visual Studio also has no issue interpreting those constraints.  Hence this circuitous proposal to implement these helpful methods in CIL and to merge them into the final core assemblies.

Granted, I don't honestly expect that to happen as I imagine that it would be obnoxious.  But I am hoping that this proposal can start the dialog as to why these constraints are useful both for the BCL and for languages targeting the BCL.

**Comment by MgSam** [comment]
@mburbea

> As for the other overload, those would be good, but don't match the other .TryParse methods. I'd love an Int.TryParse that would return null if it fails.

.NET typically implements this pattern (return *null* for a failure) with methods suffixed with "OrDefault" rather than prefixed with "Try". For example, in Linq we have `FirstOrDefault` and `SingleOrDefault`.

**Comment by mburbea** [comment]
Yes, I'm aware that "sometimes" that's the case, but there are other examples where returning null is in vogue. Like the safe navigation operator, where you try to get a property, or invoke a method but you can fail and return null (e.g. `reader.Value.?AsInt32()`)

**Comment by MgSam** [comment]
@mburbea I wasn't commenting on the worthiness of your suggestion, just the naming. I think null-returning methods are often preferable to equivalent "try" actions as they're more concise. My comment was just that it would be confusing to make "try" methods sometimes use a boolean/`out` param and sometimes use null to indicate failure, especially when the "OrDefault" naming convention already exists.

**Comment by HaloFour** [comment]
The `OrDefault` methods imply they would return a default value for the
specified type, though.  I'd expect `int.ParseOrDefault` to return 0, not
`null`.  Perhaps `ParseOrNull` would make be a suitable alternative?

**Comment by zabulus** [comment]
```
int.ParseOrDefault(string text, int defaultValue = 0)
```
In most cases, if it was unable to parse a value from the text, you need to set it by some defined value.

Though, there is the case when the fact of failed Parse propagates further. For example bad user input and message box about it.

**Comment by KrzysztofCwalina** [comment]
We don't seem to have language or runtime features to implement this. Closing for now.
