### ISSUE TITLE
Add metdata API to get module custom attributes

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/corefx#20345]
### Rationale

System.Reflection.Metadata offers convenience methods to access custom attributes on most of the record types that correspond to `HasCustomAttribute` token types in the ECMA-335 spec. Notable omission is the `ModuleDefinition` record.

### Proposed API

```csharp
namespace System.Reflection.Metadata
{
    public struct ModuleDefinition
    {
        public CustomAttributeHandleCollection GetCustomAttributes();
    }
}
```

### Other thoughts

This can be worked around with `MetadataReader.GetCustomAttributes(System.Reflection.Metadata.Ecma335.MetadataTokens.EntityHandle(0x1))`, but it's rather awkward.

**Comment by MichalStrehovsky** [comment]
@tmat Can we flip this to api-ready-for-review?

**Comment by tmat** [comment]
```MetadataReader.GetCustomAttributes(EntityHandle.ModuleDefinition)``` also works, but I agree the API should be added.

**Comment by karelz** [comment]
API review: Approved.
I guess this is straightforward to do, given the functionality exists. Marking as up-for-grabs.

**Comment by cod7alex** [comment]
As i understand it is possible to simply expose `MetadataReader.CustomAttributes` ?

**Comment by tmat** [comment]
Yes.

**Comment by cod7alex** [comment]
Thanks @tmat .

**Comment by cod7alex** [comment]
Does this need any tests? (custom attributes are already tested)

**Comment by tmat** [comment]
Update a test that tests custom attributes on modules to use the new API as well.
