### ISSUE TITLE
NETStandard.Library.NETFramework references don't work well with PreserveCompilationContext

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#20364]
Using this in a desktop NETCore.SDK project and setting PreserveCompilationContext is failing to preserve the right information.

Ensure we make this work correctly.

**Comment by rynowak** [comment]
I've marked this issue as partner-blocking, as this is blocking our conversion back to supporting net461

**Comment by ericstj** [comment]
I've already got https://github.com/dotnet/corefx/pull/20363 as an experimental fix.  I'm working on looking at the repro to make sure its a complete fix.

**Comment by ericstj** [comment]
This part of the change is required but we also need an SDK fix: https://github.com/dotnet/sdk/issues/1259

**Comment by weshaggard** [comment]
@ericstj is this issue closed now?

**Comment by ericstj** [comment]
Yep. Closing here.  The remaining work should be tracked with the work @eerhardt is doing in the SDK.
