### ISSUE TITLE
Split off ExitCode_VoidMainAppReturnsSetValue for ILC runs.

### ISSUE THREAD

**Issue by ghost** [dotnet/corefx#20387]
System.Runtime.Extensions.Tests.dll -method System.Tests.Environment_Exit.ExitCode_VoidMainAppReturnsSetValue

fails on ILC because it needs to launch a child process using a test assembly and the build pipeline won't run ILC on that test assembly or copy it to the output directory. This test cannot use RemoteExecutor because it's testing ExitCode and needs to know that it is the true main method.

If we want to test this scenario for ILC, it should best be done in a standalone test (probably living in CoreRT) that doesn't sit on top of all this xunit stuff.  It's not that we can't hack the build pipeline again to accommodate this, it's more that people (like me) investigating test failures on ILC will not appreciate having yet another 3-5 minutes added to the build time of this project because of one single test.

**Comment by danmosemsft** [comment]
Why can't RemoteExecutor do all these things, based on parameters passed to it? if setting ExitCode is an alternative to int Main.

**Comment by stephentoub** [comment]
We no longer run tests on a `uapaot` configuration.
