### ISSUE TITLE
ActivityTests DiagnosticSourceStartStop failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#20418]
https://mc.dot.net/#/user/dotnet-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fportable~2Fcli~2F/c79148689a54240393f14c58768b066f6515b9cc/workItem/System.Diagnostics.DiagnosticSource.Tests/analysis/xunit/System.Diagnostics.Tests.ActivityTests~2FDiagnosticSourceStartStop
```
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Assert.True() Failure\nExpected: True\nActual:   False
Stack Trace :
   at System.Diagnostics.Tests.ActivityTests.DiagnosticSourceStartStop() in /mnt/j/workspace/dotnet_corefx/master/portable-linux-Config_Release+OuterLoop_false_prtest/src/System.Diagnostics.DiagnosticSource/tests/ActivityTests.cs:line 442
```

**Comment by stephentoub** [comment]
Another DiagnosticSourceStartStop failure here:
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fportable~2Fcli~2F/d38b08ebf9e3a2b07e1281f43a9597fa21c5bf23/workItem/System.Diagnostics.DiagnosticSource.Tests/analysis/xunit/System.Diagnostics.Tests.ActivityTests~2FDiagnosticSourceStartStop
```
Message :
Assert.True() Failure\nExpected: True\nActual:   False
Stack Trace :
   at System.Diagnostics.Tests.ActivityTests.DiagnosticSourceStartStop() in /mnt/j/workspace/dotnet_corefx/master/portable-linux-Config_Debug+OuterLoop_false_prtest/src/System.Diagnostics.DiagnosticSource/tests/ActivityTests.cs:line 445
```

**Comment by danmosemsft** [comment]
https://mc.dot.net/#/user/dotnet-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/e48d87ac50129845b045371da5e8e32b1f9ba7b7/workItem/System.Diagnostics.DiagnosticSource.Tests/analysis/xunit/System.Diagnostics.Tests.ActivityTests~2FDiagnosticSourceStartStop
```

Unhandled Exception of Type Xunit.Sdk.InRangeException
Message :
Assert.InRange() Failure\r\nRange:  (1/1/01 12:00:00 AM - 5/31/17 5:45:42 PM)\r\nActual: 5/31/17 5:45:42 PM
Stack Trace :
   at System.Diagnostics.Tests.ActivityTests.DiagnosticSourceStartStop() in /mnt/j/workspace/dotnet_corefx/master/portable-linux-Config_Debug+OuterLoop_false_prtest/src/System.Diagnostics.DiagnosticSource/tests/ActivityTests.cs:line 445
```

**Comment by danmosemsft** [comment]
I've seen 2 more today eg
`Assert.InRange() Failure\r\nRange:  (1/1/01 12:00:00 AM - 6/5/17 12:13:10 AM)\r\nActual: 6/5/17 12:13:10 AM`

It looks like it's only slightly out of range. @brianrob are you the owner of this test? 

It's this assert
```c#
                    // let's only check that Duration is set in StopActivity, we do not intend to check precision here
                    Assert.InRange(observer.Activity.StartTimeUtc + observer.Activity.Duration, DateTime.MinValue, DateTime.UtcNow.AddMilliseconds(2 * MaxClockErrorMSec))
```

https://mc.dot.net/#/user/8to5Developer/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/0feb1592e4f1daaf878bf1ebd5c250c8d904d0bb/workItem/System.Diagnostics.DiagnosticSource.Tests/analysis/xunit/System.Diagnostics.Tests.ActivityTests~2FDiagnosticSourceStartStop

**Comment by brianrob** [comment]
@danmosemsft, yes, I own this test.  How intermittent is this failure?  I would expect this to be fairly deterministic as there isn't any multi-threading here.  What could be happening is that the DateTime granularity is not very good on these platforms.  Do you know how the DateTime granularity on Linux compares to Windows?

**Comment by danmosemsft** [comment]
I don't. @stephentoub do you?

Note that as well as precision DateTime can also make larger jumps, eg., this affected a recent Sleep test where sporadically it would go backwards. Our assumption was that this was caused by a VM synchronizing its clock during the test. Changing to Stopwatch seems to have fixed it (so far). In this case that's not possible so I'd expect it to occasionally be an issue even if that's not the issue here.

**Comment by stephentoub** [comment]
> What could be happening is that the DateTime granularity is not very good on these platforms.

The precision and accuracy should be fairly good after https://github.com/dotnet/coreclr/pull/9772, though as it is an approximation of wall clock time it's not guaranteed to be monotonic and may jump forward or backwards a bit.

@janvorli, the switch to portable CoreCLR Linux builds wouldn't have affected HAVE_WORKING_CLOCK_GETTIME, would it?

**Comment by janvorli** [comment]
@stephentoub It should not. Running build on my CentOS 7:
`-- Performing Test HAVE_WORKING_CLOCK_GETTIME - Success`

**Comment by danmosemsft** [comment]
Do we have any better ideas than increasing the tolerance? 
Note even then this test will be vunerable to concurrent adjustments to the clock as we saw with the Sleep test: the only way I can think of to deal with that would be to try a second time if it failed the first.

**Comment by danmosemsft** [comment]
@brianrob can you please increase the tolerance, or make it try twice, or some other thing? I'm trying to fix all sporadic CI issues.

**Comment by brianrob** [comment]
@danmosemsft, I sent some more time looking at this test failure this morning.  It's not clear to me that the answer is to increase the tolerance.  The clock source being used should be accurate on the order of usec.  Thus, 40 ms should be more than enough unless there's something else happening here like 40 ms of negative clock adjustment.

Can you tell me more about what we saw in the sleep test?  How much time adjustment did you see happening?

As a next step, I think we should dump some diagnostics and then look at the failures.  I'll make a PR for this.

**Comment by danmosemsft** [comment]
@brianrob I certainly don't want you to make the wrong fix .. 
The sleep issue was https://github.com/dotnet/corefx/issues/20173 and in that case we saw a delta in DateTime.UtcNow of negative 23 milliseconds when it should have been a bit over positive 500. That happened at least twice on Ubuntu.

**Comment by brianrob** [comment]
That's quite significant actually.  My goal in diagnostic logging was to figure out if that was what was happening here.  I think we should probably do the same thing in this test - compare duration to a duration that we calculate using a monotonic clock source.  I'll scrap the diagnostics PR and do this instead.
