### ISSUE TITLE
HttpClient on Linux does not correctly handle zero-length chunked body

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#20419]
Run the following code:

```
            TcpListener listener = new TcpListener(IPAddress.Loopback, 0);
            listener.Start();
            int port = ((IPEndPoint)listener.LocalEndpoint).Port;
            var acceptTask = listener.AcceptTcpClientAsync();

            using (HttpClient client = new HttpClient())
            {
                client.DefaultRequestHeaders.TransferEncodingChunked = true;
                Task<HttpResponseMessage> clientTask = client.PostAsync($"http://localhost:{port}/", new StringContent(""));

                TcpClient server = await acceptTask;
                Stream serverStream = server.GetStream();
                int bytesRead = 0;
                byte[] buffer = new byte[4096];
                while (true)
                {
                    bytesRead = serverStream.Read(buffer, 0, 4096);
                    if (bytesRead == 0)
                    {
                        break;
                    }

                    Console.WriteLine(Encoding.UTF8.GetString(buffer, 0, bytesRead));
                }
            }
```

You will see output like this:

```
  POST / HTTP/1.1
  Host: localhost:51288
  Accept: */*
  Content-Type: text/plain; charset=utf-8
  Transfer-Encoding: chunked

```

HttpClient should be sending a 0-length chunk terminator, but it's not.

Works fine on Windows.

**Comment by geoffkizer** [comment]
@karelz @stephentoub FYI

**Comment by davidsh** [comment]
In terms of HttpClient, we have tests for validating POSTing a zero-length request body using chunked semanatics:

https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/tests/FunctionalTests/PostScenarioTest.cs#L67

So, if this test is passing, that would indicate we have some other problem here.

**Comment by stephentoub** [comment]
> So, if this test is passing, that would indicate we have some other problem here.

There's a small but apparently key difference between that test and Geoff's repro:
```C#
requestContent.Headers.ContentLength = null;
```
If you change Geoff's repro to set the content's ContentLength to null, it starts working as expected.

**Comment by davidsh** [comment]
Creating a `new StringContent()` will, by default, populate the 'Content-Length' header.  If you then also add 'Transfer-Encoding: chunked` to the request headers as well, you get a conflict.

So, perhaps the Linux version of HttpClient has a problem when there is a conflict between the 2 different semantics.  WinHttpHandler has code to explicitly resolve this conflict (and will remove the 'Content-Length' header in favor of chunked encoding.  Maybe the Linux version has a problem with this?
