### ISSUE TITLE
Running tests with netfx from Visual Studio

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#20429]
I know that VS isn't officially fully supported in corefx, but is there a way to have the F5/edit, debug continue experience for tests running against netfx? There may be a way to do this with the command line arguments

**Comment by danmosemsft** [comment]
@safern

**Comment by safern** [comment]
Yes there is you have to do the following:
1. Build the test project through msbuild /p:targetgroup=netfx
2. Open Visual Studio
3. Open xunit runner for your test project "%corefxpath%\bin\%OSGroup.Architecture.BuildConfiguarion%\%YOURPROJECT%\netstandard\xunit.console.exe"
    * Where %OSGroup.Architecture.BuildConfiguarion% is something like AnyOS.AnyCPU.Debug
4. Open project properties and fill in the next information:
    * Arguments -> ```%YOURPROJECT%.dll -noshadow -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetfxtests  -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests```
         * Note that this arguments change if you are running/debugging Outerloop tests (You would need to delete `-notrait category=Outerloop`. I usually build and copy xunit's arguments from RunTests.cmd inside the test project bin folder.
    * Debugger Type -> Managed (v4.6, v4.5, v4.0)
    * Environment -> you need to add an environment variable as follows:
         * DEVPATH -> %corefxpath%\bin\testhost\netfx-Windows_NT-Debug-x64\
    * Set a breakpoint on your test and run.

Let me know if you have any other question

**Comment by weshaggard** [comment]
While this is technically possible it as you can tell it is really painful, and it is painful to switch back to doing .NET Core debugging once you do this. Unfortunately this is is a limitation of VS debugger properties page not able to easily swap properties here based on the configuration you select in VS itself. Right now we don't have a great way and even the current command line options that @safern posted there change often enough that they will go stale in any documentation we write up on it. However I do think this is worth documenting @safern can you put these steps into our docs?

**Comment by safern** [comment]
Yes it is unfortunate that we have to go through those painful steps. There is also a way to do this through a batch file. I will post both in the docs later. 

Is there any specific doc where you would like this to be? Or should we add a new one specific for this?

**Comment by weshaggard** [comment]
I think I would put it somewhere under https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md.

**Comment by am11** [comment]
Maybe we can file it as a feature request at https://github.com/Microsoft/VSTest :)
