### ISSUE TITLE
ClientWebSocket on Windows may fail to connect to managed HttpListener

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#20439]
In our HttpListener tests, we currently have each test create a new HttpListener.  Since the HttpListener API doesn't support binding to 0 and having the OS pick an available port, the tests iterate through ports looking for one the HttpListener can bind to.  Often the listener ends up on the same port as the previous test, which means the client is effectively given the same Uri on one test as it was on its previous test.  The Windows ClientWebSocket is using connection pooling, and while this analysis may not be correct, it appears that sometimes there is a race condition whereby the client tries to reuse an existing connection for test N+1 after the server has closed that connection for test N.  This then results in the client failing the connection, with an error like:
```
        System.Net.WebSockets.WebSocketException : Unable to connect to the remote server
        ---- System.Net.WebSockets.WebSocketException : Unable to connect to the remote server
        -------- System.Net.Http.WinHttpException : The connection with the server was terminated abnormally
        Stack Trace:
           C:\Users\stoub\Source\Repos\corefx\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\WebSocketHandle.Win32.cs(60,0): at System.Net.WebSockets.WebSocketHandle.<ConnectAsy
  ncCore>d__20.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           C:\Users\stoub\Source\Repos\corefx\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\ClientWebSocket.cs(157,0): at System.Net.WebSockets.ClientWebSocket.<ConnectAsyncCor
  e>d__16.MoveNext()
```
Disabling the per-process connection pooling in ClientWebSocket, e.g.
```C#
                    uint optionData = 1;
                    if (!Interop.WinHttp.WinHttpSetOption(
                        _operation.SessionHandle,
                        Interop.WinHttp.WINHTTP_OPTION_MAX_CONNS_PER_SERVER,
                        ref optionData))
                    {
                        WinHttpException.ThrowExceptionUsingLastError();
                    }
```
causes the failure to go away, as does changing the tests to try to use a different port than was used by the last test.

**Comment by PeterSmithRedmond** [comment]
IMHO, this is a test bug -- we're reusing a port.  Naturally the client has no way to know that the server essentially went away and came back.

**Comment by stephentoub** [comment]
> Naturally the client has no way to know that the server essentially went away and came back.

Right, but that happens in the real world, too; servers close stale connections, and if ClientWebSocket end up reusing such a connection and then fails as a result, isn't that a problem?

**Comment by davidsh** [comment]
Marking as "bug" and not "test-bug" until this is investigated.

**Comment by davidsh** [comment]
Closing this issue since ClientWebSocket no longer uses WinHTTP APIs.  If we see similar symptoms in current tests, we can open a new issue.
