### ISSUE TITLE
Tizen emulator legs regularly timing out

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20458]
Eg https://ci.dot.net/job/dotnet_corefx/job/master/job/tizen_armel_cross_release_prtest/3234/

I don't know whether it's a hang, or just slow progress.

@seanshpark @hseok-oh @gkhanna79 @parjong

**Comment by danmosemsft** [comment]
another example
https://ci.dot.net/job/dotnet_corefx/job/master/job/tizen_armel_cross_debug_prtest/3371/console

@seanshpark @hseok-oh @gkhanna79 @parjong what can be done here?

**Comment by seanshpark** [comment]
cc @lemmaa

**Comment by parjong** [comment]
@danmosemsft https://ci.dot.net/job/dotnet_corefx/job/master/job/tizen_armel_cross_debug_prtest/3371/console seems to be blocking during managed build (which is not related with cross build at all), and I sometimes observed similar hang during managed build (for x64 testing).

Is there any known issue on .NET CLI?

**Comment by seanshpark** [comment]
Log of success of that failed is `xunit.runner.utility.dotnet.pdb` which took much more... 

15:12:43   /opt/corefx/packages/xunit.runner.utility/2.2.0-beta2-build3300/lib/netstandard1.1/xunit.runner.utility.dotnet.pdb (xunit.runner.utility.2.2.0-beta2-build3300) -> /opt/corefx/bin/runtime/netcoreapp-Linux-Debug-armel/xunit.runner.utility.dotnet.pdb
15:12:51   /opt/corefx/packages/microsoft.targetingpack.netframework.v4.6.1/1.0.1/lib/net461/Accessibility.dll (Microsoft.TargetingPack.NETFramework.v4.6.1.1.0.1) -> /opt/corefx/bin/AnyOS.AnyCPU.Debug/netfx/netcoreapp/Accessibility.dll

**Comment by danmosemsft** [comment]
I'm not aware of any issue (doesn't mean there isn't one). Also I only see this on armel.  I assume it's not simply because emulator is slow as it stopped at this step for over an hour.

Perhaps the next step is to get onto a machine that hangs this way.

@mmitche to help look for one.

**Comment by mmitche** [comment]
I started a couple more runs in the hope that it will hang.  If it does, we can pull the machine offline for investigation.

**Comment by parjong** [comment]
@danmosemsft  
 >  I assume it's not simply because emulator is slow as it stopped at this step for over an hour.

I totally agree wit that. As I know, emulator (qemu maybe?) is not used during managed build. 

@hseok-oh @jyoungyun @hqueue Could you please take a look? Please correct me if there is something wrong.

**Comment by hseok-oh** [comment]
@danmosemsft As @parjong says, armel build is not using emulator for build process. And amrel corefx job in CI is not doing any testrun processes. 
The difference for armel managed build is passing some build option (for packaging test)

https://github.com/dotnet/corefx/blob/master/cross/arm32_ci_script.sh#L240

For example, armel release build
`./build.sh -buildArch=armel -release -RuntimeOS=tizen.4.0.0 __extraCmd=/p:OverridePackageSource=https://tizen.myget.org/F/dotnet-core/api/v3/index.json

**Comment by danmosemsft** [comment]
@hseok-oh @parjong thanks for the thoughts. We'll look further on our side.

**Comment by wtgodbe** [comment]
Closing this as a dead issue
