### ISSUE TITLE
WebHeaderCollection tests fail in ILC mode due to missing strings in test runner

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#20465]
System.Net.WebHeaderCollection tests run fine in F5 ('uap') mode. But in ILC ('uap-aot') mode they are failing.  It seems that strings are missing from the exceptions being thrown in a test like this:

```c#
[Theory]
[MemberData(nameof(InvalidValues))]
public void Add_InvalidValue_ThrowsArgumentException(string value)
{
    var headers = new WebHeaderCollection();
    Assert.Throws<ArgumentException>("value", () => headers.Add("name", value));
 }
```

We get failures like this:

>System.Net.Tests.WebHeaderCollectionTest.Add_InvalidValue_ThrowsArgumentException(value: \"value1\\nvalue2\\r\") [FAIL]
        Assert.Equal() Failure
        Expected: value
        Actual:   (null)
        Stack Trace:
           s:\GitHub\corefx\src\System.Net.WebHeaderCollection\tests\WebHeaderCollectionTest.cs(495,0): at System.Net.Tests.WebHeaderCollectionTest.Add_Invalid
  Value_ThrowsArgumentException(String value)

Is this an expected problem from the UWP test runner in ILC mode?

cc: @tarekgh @danmosemsft @AlexGhiondea

**Comment by davidsh** [comment]
The WebHeaderCollection product code looks like this:

```c#
public override void Add(string name, string value)
{
    if (name == null)
     {
         throw new ArgumentNullException(nameof(name));
     }
     if (name.Length == 0)
     {
        throw new ArgumentException(SR.Format(SR.net_emptyStringCall, nameof(name)), nameof(name));
     }
```

**Comment by davidsh** [comment]
cc: @tijoytom

**Comment by tarekgh** [comment]
CC @joperezr

**Comment by danmosemsft** [comment]
@zamont this is ILC so it's not the resource issue we had in the F5 runs. Didn't you fix some resource loader issues? Maybe this can be reenabled now.

**Comment by davidsh** [comment]
>@zamont this is ILC so it's not the resource issue we had in the F5 runs. Didn't you fix some resource loader issues? Maybe this can be reenabled now.

This is not a ResourceManager issue.  I think the problem here is that it is a known issue that parameter names in exceptions are stripped out for ILC.

The fix here is to use AssertExtensions.Throws instead of Assert.Throws.  I didn't know about this fix when I first disabled this test.  I've already made similar fixes to other libraries for this problem. I can fix/renable this later next week.

**Comment by CIPop** [comment]
@davidsh as far as I can tell this is a test-only problem (the product won't correctly set the exception argument but an exception of the correct type will be thrown). Is that correct?

**Comment by davidsh** [comment]
We already know how to fix this issue.

Simply replace Assert.Throws with AssertExtensions.Throws and that will automatically take care of ignoring the fact that the parameter name is missing in ILC builds.  We already did a fix similar to this in another library.

And yes, this is a test-bug.
