### ISSUE TITLE
NetEventSource tests aren't working in ILC (multiple contracts)

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#20470]
Running this test passes in F5 ('uap') mode but fails in ILC ('uap-aot') mode:

Test:
```c#
public class WebHeaderCollectionLoggingTest
{
    [Fact]
    [SkipOnTargetFramework(TargetFrameworkMonikers.NetFramework, "NetEventSource is only part of .NET Core")]
    public void EventSource_ExistsWithCorrectId()
```

>System.Net.Tests.WebHeaderCollectionLoggingTest.EventSource_ExistsWithCorrectId [FAIL]
        System.TypeLoadException : The type 'System.Net.NetEventSource' cannot be found in assembly 'System.Net.WebHeaderCollection, Version=4.1.1.0, Culture=n
  eutral, PublicKeyToken=b03f5f7f11d50a3a'.
        Stack Trace:
f:\dd\ndp\fxcore\CoreRT\src\System.Private.Reflection.Core\src\System\Reflection\Runtime\General\Helpers.cs(158,0): at System.Reflection.Runtime.Gen
  eral.Helpers.CreateTypeLoadException(String typeName, Assembly assemblyIfAny)
f:\dd\ndp\fxcore\CoreRT\src\System.Private.Reflection.Core\src\System\Reflection\Runtime\TypeParsing\GetTypeOptions.cs(58,0): at System.Reflection.R
  untime.TypeParsing.GetTypeOptions.CoreResolveType(Assembly containingAssemblyIfAny, String name)
f:\dd\ndp\fxcore\CoreRT\src\System.Private.Reflection.Core\src\System\Reflection\Runtime\TypeParsing\TypeName.cs(90,0): at System.Reflection.Runtime
  .TypeParsing.NamespaceTypeName.ResolveType(Assembly containingAssemblyIfAny, $GetTypeOptions getTypeOptions)
f:\dd\ndp\fxcore\CoreRT\src\System.Private.Reflection.Core\src\System\Reflection\Runtime\Assemblies\RuntimeAssembly.cs(103,0): at System.Reflection.
  Runtime.Assemblies.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
           s:\GitHub\corefx\src\System.Net.WebHeaderCollection\tests\LoggingTest.cs(16,0): at System.Net.Tests.WebHeaderCollectionLoggingTest.EventSource_Exist
  sWithCorrectId()
              at _$ILCT$.$ILT$ReflectionDynamicInvoke$.InvokeRetV(Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean targetIsThisCall)
              at System.InvokeUtils.CalliIntrinsics.Call(IntPtr dynamicInvokeHelperMethod, Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Bo
  olean isTargetThisCall)
           f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\InvokeUtils.cs(400,0): at System.InvokeUtils.CallDynamicInvokeMethod(Object thisPtr, I
  ntPtr methodToCall, Object thisPtrDynamicInvokeMethod, IntPtr dynamicInvokeHelperMethod, IntPtr dynamicInvokeHelperGenericDictionary, Object targetMethodOrDe
  legate, Object[] parameters, BinderBundle binderBundle, Boolean invokeMethodHelperIsThisCall, Boolean methodToCallIsThisCall)

**Comment by CIPop** [comment]
@yizhang82  @danmosemsft please confirm if the following is something that should work in UWP or not:
`Type esType = typeof(SslStream).Assembly.GetType("System.Net.NetEventSource", throwOnError: true, ignoreCase: false);`

**Comment by danmosemsft** [comment]
In ILC mode, all reflection must be "declared" at build time otherwise the metadata is stripped away. I assume that breaks GetType(".."). If so you need to declare the type in an rd.xml file. Look for *.rd.xml in our tree and it'll likely be self explanatory. @AtsushiKan can help otherwise.

**Comment by AtsushiKan** [comment]
The first such fix:

https://github.com/dotnet/corefx/commit/97772890484e98f249a8173faf37e6380b3445cb

The first of many...

**Comment by CIPop** [comment]
We need to use @AtsushiKan 's example and fix this for other contracts where this was disabled without a bug#.
/cc @caesar1995

**Comment by yizhang82** [comment]
@morganbr @MichalStrehovsky Actually I expect the pattern above to "just work". It's possible we haven't implemented this one properly but in theory there is enough information to figure out that the type is needed.

**Comment by morganbr** [comment]
This falls into the bucket of NS 2.0 APIs that analysis doesn't handle yet (but will). If you'd like a workaround without rd.xml, you can use the TypeInfo.Assembly API to get those to chain together.
```
typeof(SslStream).GetTypeInfo().Assembly.GetType("System.Net.NetEventSource", throwOnError: true, ignoreCase: false);
```

**Comment by davidsh** [comment]
@morganbr 

That workaround doesn't appear to work. We tried using it already in the WebHeaderCollections tests:
https://github.com/dotnet/corefx/blob/master/src/System.Net.WebHeaderCollection/tests/LoggingTest.cs#L17

and we still see this error on UAPAOT test runs:

>     System.Net.Tests.WebHeaderCollectionLoggingTest.EventSource_ExistsWithCorrectId [FAIL]
        System.TypeLoadException : The type 'System.Net.NetEventSource' cannot be found in assembly 'System.Net.WebHeaderCollection, Version=4.1.1.0, Culture=n
  eutral, PublicKeyToken=b03f5f7f11d50a3a'.
        Stack Trace:
           f:\dd\ndp\fxcore\CoreRT\src\System.Private.Reflection.Core\src\System\Reflection\Runtime\General\Helpers.cs(150,0): at System.Reflection.Runtime.Gen
  eral.Helpers.CreateTypeLoadException(String typeName, Assembly assemblyIfAny)
           f:\dd\ndp\fxcore\CoreRT\src\System.Private.Reflection.Core\src\System\Reflection\Runtime\TypeParsing\GetTypeOptions.cs(58,0): at System.Reflection.R
  untime.TypeParsing.GetTypeOptions.CoreResolveType(Assembly containingAssemblyIfAny, String name)
           f:\dd\ndp\fxcore\CoreRT\src\System.Private.Reflection.Core\src\System\Reflection\Runtime\TypeParsing\TypeName.cs(90,0): at System.Reflection.Runtime
  .TypeParsing.NamespaceTypeName.ResolveType(Assembly containingAssemblyIfAny, $GetTypeOptions getTypeOptions)
           f:\dd\ndp\fxcore\CoreRT\src\System.Private.Reflection.Core\src\System\Reflection\Runtime\Assemblies\RuntimeAssembly.cs(102,0): at System.Reflection.
  Runtime.Assemblies.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
           s:\GitHub\corefx\src\System.Net.WebHeaderCollection\tests\LoggingTest.cs(17,0): at System.Net.Tests.WebHeaderCollectionLoggingTest.EventSource_Exist
  sWithCorrectId()
              at _$ILCT$.$ILT$ReflectionDynamicInvoke$.InvokeRetV(Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean targetIsThisCall)
              at System.InvokeUtils.CalliIntrinsics.Call(IntPtr dynamicInvokeHelperMethod, Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Bo
  olean isTargetThisCall)
           f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\InvokeUtils.cs(400,0): at System.InvokeUtils.CallDynamicInvokeMethod(Object thisPtr, I
  ntPtr methodToCall, Object thisPtrDynamicInvokeMethod, IntPtr dynamicInvokeHelperMethod, IntPtr dynamicInvokeHelperGenericDictionary, Object targetMethodOrDe
  legate, Object[] parameters, BinderBundle binderBundle, Boolean invokeMethodHelperIsThisCall, Boolean methodToCallIsThisCall)

**Comment by davidsh** [comment]
So, I tried creating an "rd.xml" file as done in the above referenced commit.

```xml
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
  <Library>
    <!-- Needed because EventSource uses reflection. -->
    <Type Name="System.Net.NetEventSource" Dynamic="Required Public" />
  </Library>
</Directives>
```

But I still get the same error when running as UAPAOT.

And I noticed this ILC errors as well which appear to point to the problem. But I'm not sure how to fix it.

```
  Compilation finished

  default.rd.xml(1-1): warning : ILTransform : warning ILT0027: The element 'Directives' in namespace 'http://schemas.microsoft.com/netfx/2013/01/metadata' can
  not contain text. List of possible elements expected: 'Application, Library' in namespace 'http://schemas.microsoft.com/netfx/2013/01/metadata'.
  default.rd.xml(2-2): warning : ILTransform : warning ILT0027: The element 'Application' in namespace 'http://schemas.microsoft.com/netfx/2013/01/metadata' ca
  nnot contain text. List of possible elements expected: 'Namespace, Assembly, TypeInstantiation, Type' in namespace 'http://schemas.microsoft.com/netfx/2013/0
  1/metadata'.
  default.rd.xml(3-3): warning : ILTransform : warning ILT0027: The element 'Application' in namespace 'http://schemas.microsoft.com/netfx/2013/01/metadata' ca
  nnot contain text. List of possible elements expected: 'Namespace, Assembly, TypeInstantiation, Type' in namespace 'http://schemas.microsoft.com/netfx/2013/0
  1/metadata'.
   Resources.System.Net.WebHeaderCollection.Tests.rd.xml(4-4): warning : ILTransform : warning ILT0027: Ambiguous type name detected. There are types with name
   'System.Net.NetEventSource' in both assembly 'System.Net.WebHeaderCollection' and 'System.Net.Requests'. This directive is ignored. Consider placing this di
  rective within an Assembly scope.
   Resources.System.Net.WebHeaderCollection.Tests.rd.xml(4-4): warning : ILTransform : warning ILT0027: Type 'System.Net.NetEventSource' could not be found.
   Resources.System.Private.CoreLib.rd.xml(113-113): warning : ILTransform : warning ILT0027: Type 'System.Diagnostics.Tracing.PropertyValue.ReferenceTypeHelpe
  r<System.Object>' is blocked from reflection. Please notify Microsoft of this error.
   System.Linq.Expressions.Resources.System.Linq.Expressions.rd.xml(158-158): warning : ILTransform : warning ILT0027: The 'Dynamic' attribute is invalid - The
   value 'Required' is invalid according to its datatype 'http://schemas.microsoft.com/netfx/2013/01/metadata:applicabilitySpec' - The Enumeration constraint f
  ailed.
      7 Warning(s)
      0 Error(s)
```

**Comment by yizhang82** [comment]
My guess is that the extra space after <Directives xmlns=""> is throwing the xml parser off.  Try removing that.

**Comment by davidsh** [comment]
>My guess is that the extra space after is throwing the xml parser off. Try removing that.

What extra space are you referring to?

**Comment by davidsh** [comment]
So, I have been iterating a few times on the *.rd.xml file.  There are warnings I can't control since there is a default.rd.xml file in the build process.

Here is my current attempt and I still get warning on rd.xml as well as can't find the type when I run the tests:

It would be good to know what the exact recipe is to get this to work and/or whether there are still bugs in the ILC toolchain.

```xml
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
  <Application>
    <Assembly Name="System.Net.WebHeaderCollection" />
      <!-- Needed because EventSource uses reflection. -->
      <Type Name="System.Net.NetEventSource" Activate="Required Public" Browse="Required Public" Dynamic="Required Public" />
    </Assembly>
  </Application>
</Directives>
```

```
default.rd.xml(1-1): warning : ILTransform : warning ILT0027: The element 'Directives' in namespace 'http://schemas.microsoft.com/netfx/2013/01/metadata' can
  not contain text. List of possible elements expected: 'Application, Library' in namespace 'http://schemas.microsoft.com/netfx/2013/01/metadata'.
  default.rd.xml(2-2): warning : ILTransform : warning ILT0027: The element 'Application' in namespace 'http://schemas.microsoft.com/netfx/2013/01/metadata' ca
  nnot contain text. List of possible elements expected: 'Namespace, Assembly, TypeInstantiation, Type' in namespace 'http://schemas.microsoft.com/netfx/2013/0
  1/metadata'.
  default.rd.xml(3-3): warning : ILTransform : warning ILT0027: The element 'Application' in namespace 'http://schemas.microsoft.com/netfx/2013/01/metadata' ca
  nnot contain text. List of possible elements expected: 'Namespace, Assembly, TypeInstantiation, Type' in namespace 'http://schemas.microsoft.com/netfx/2013/0
  1/metadata'.
   Resources.System.Net.WebHeaderCollection.Tests.rd.xml(6,7,6,7): warning : ILTransform : warning ILT0027: The 'Application' start tag on line 2 position 4 do
  es not match the end tag of 'Assembly'. Line 6, position 7.
   Resources.System.Private.CoreLib.rd.xml(113-113): warning : ILTransform : warning ILT0027: Type 'System.Diagnostics.Tracing.PropertyValue.ReferenceTypeHelpe
  r<System.Object>' is blocked from reflection. Please notify Microsoft of this error.
   System.Linq.Expressions.Resources.System.Linq.Expressions.rd.xml(158-158): warning : ILTransform : warning ILT0027: The 'Dynamic' attribute is invalid - The
   value 'Required' is invalid according to its datatype 'http://schemas.microsoft.com/netfx/2013/01/metadata:applicabilitySpec' - The Enumeration constraint f
  ailed.
      6 Warning(s)
      0 Error(s)
```

**Comment by davidsh** [comment]
cc: @DavidGoll

**Comment by davidsh** [comment]
I revised the System.Net.WebHeaderCollection.Tests.rd.xml:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
  <Library Name="System.Net.WebHeaderCollection.Tests">
    <Assembly Name="System.Net.WebHeaderCollection">
      <!-- Needed because EventSource uses reflection. -->
      <Type Name="System.Net.NetEventSource" Activate="Required Public" Browse="Required Public" Dynamic="Required Public" />
    </Assembly>
  </Library>
</Directives>
```

and got these errors:

```
 Compilation finished

default.rd.xml(1-1): warning : ILTransform : warning ILT0027: The element 'Directives' in namespace 'http://schemas.microsoft.com/netfx/2013/01/metadata' cannot contain text. List of possible elements expected: 'Application, Library' in namespace 'http://schemas.microsoft.com/netfx/2013/01/metadata'.
  default.rd.xml(2-2): warning : ILTransform : warning ILT0027: The element 'Application' in namespace 'http://schemas.microsoft.com/netfx/2013/01/metadata' cannot contain text. List of possible elements expected: 'Namespace, Assembly, TypeInstantiation, Type' in namespace 'http://schemas.microsoft.com/netfx/2013/01/metadata'.
  default.rd.xml(3-3): warning : ILTransform : warning ILT0027: The element 'Application' in namespace 'http://schemas.microsoft.com/netfx/2013/01/metadata' cannot contain text. List of possible elements expected: 'Namespace, Assembly, TypeInstantiation, Type' in namespace 'http://schemas.microsoft.com/netfx/2013/01/metadata'.
   Resources.System.Net.WebHeaderCollection.Tests.rd.xml(6-6): warning : ILTransform : warning ILT0027: Type 'System.Net.NetEventSource' is blocked from reflection. Please notify Microsoft of this error.
   Resources.System.Private.CoreLib.rd.xml(113-113): warning : ILTransform : warning ILT0027: Type 'System.Diagnostics.Tracing.PropertyValue.ReferenceTypeHelper<System.Object>' is blocked from reflection. Please notify Microsoft of this error.
   System.Linq.Expressions.Resources.System.Linq.Expressions.rd.xml(158-158): warning : ILTransform : warning ILT0027: The 'Dynamic' attribute is invalid - The value 'Required' is invalid according to its datatype 'http://schemas.microsoft.com/netfx/2013/01/metadata:applicabilitySpec' - The Enumeration constraint failed.
      6 Warning(s)
      0 Error(s)
```

This looks like a .NET Native ILC toolchain issue that needs to be solved especially these type of errors:

"Resources.System.Net.WebHeaderCollection.Tests.rd.xml(6-6): warning : ILTransform : warning ILT0027: Type 'System.Net.NetEventSource' is blocked from reflection. Please notify Microsoft of this error."

**Comment by morganbr** [comment]
@davidsh, this don't look like toolchain bugs. It looks likely that you have two issues:
1. These warnings are XML schema validation errors. I don't immediately see how you're breaking the schema, but I'd suggest looking for things like non-printing characters
```
default.rd.xml(1-1): warning : ILTransform : warning ILT0027: The element 'Directives' in namespace 'http://schemas.microsoft.com/netfx/2013/01/metadata' cannot contain text. List of possible elements expected: 'Application, Library' in namespace 'http://schemas.microsoft.com/netfx/2013/01/metadata'.
default.rd.xml(2-2): warning : ILTransform : warning ILT0027: The element 'Application' in namespace 'http://schemas.microsoft.com/netfx/2013/01/metadata' cannot contain text. List of possible elements expected: 'Namespace, Assembly, TypeInstantiation, Type' in namespace 'http://schemas.microsoft.com/netfx/2013/01/metadata'.
default.rd.xml(3-3): warning : ILTransform : warning ILT0027: The element 'Application' in namespace 'http://schemas.microsoft.com/netfx/2013/01/metadata' cannot contain text. List of possible elements expected: 'Namespace, Assembly, TypeInstantiation, Type' in namespace 'http://schemas.microsoft.com/netfx/2013/01/metadata'.
```

2. Internal types of framework assemblies are blocked from reflection -- that means that even if rd.xml says to make them reflectable, they won't be (that's what that warning means). If you have internal types you're reflecting over, the way to unblock them is to make them public.

**Comment by davidsh** [comment]
>These warnings are XML schema validation errors. I don't immediately see how you're breaking the schema, but I'd suggest looking for things like non-printing characters

Those warnings are coming from a "default.rd.xml" file that is not part of our library.  It is part of the XUnit UAP test runner. So, perhaps the runner has schema validation bugs.

>Internal types of framework assemblies are blocked from reflection -- that means that even if rd.xml says to make them reflectable, they won't be (that's what that warning means). If you have internal types you're reflecting over, the way to unblock them is to make them public.

We are trying to get System.Net.NetEventSource working for UAPAOT.  It works fine for UAP. In general, the EventSource architecture relies on reflection.  @vancem designed the architecture for EventSource. But fundamentally, we need to figure out why our NetEventSource seems broken in UAPAOT.  

Isn't it possible to also publish even internal types instead of just public?  I.e. instead of "Required Public", use "Required All" in the *.rd.xml?

**Comment by danmosemsft** [comment]
default.rd.xml comes from the TestILC package. I don't know where that comes from - @joperezr

**Comment by joperezr** [comment]
correct, that one gets packaged from ProjectN build as part of the TestILC package and will be used by default.

**Comment by davidsh** [comment]
>that one gets packaged from ProjectN build as part of the TestILC package and will be used by default.

So, what does that mean for me and what I am trying solve?  I am specifying my own *.rd.xml file in the System.Net.WebHeaderCollection.Tests library.  I see warnings about default.rd.xml and my System.Net.WebHeaderCollection.Tests.rd.xml.

Are both *.rd.xml files being processed?  I thought that having my own would mean that I wouldn't see anything about default.rd.xml.

**Comment by joperezr** [comment]
That's a good question, I'm not super familiar with default.rd.xml but @morganbr might understand better what the issue is.

**Comment by davidsh** [comment]
I was able to verify my theory and have submitted a PR #21584. If we're using the common file and including it directly in System.Net.Primitives, we don't need to use reflection anways.

**Comment by morganbr** [comment]
Multiple rd.xml files do get processed additively (mostly). 

@joperezr , that default rd.xml file isn't part of the product, it's something the CoreFX tests are adding to the package. It looks like it does have illegal characters in it that don't show up in notepad. It would be good to get those cleaned out so there aren't confusing warnings.

@davidsh, "Required All" does work for customer assemblies, but for framework assemblies, we block reflection on internals on purpose (and you have to make things public to make them reflectable). If you have an assembly where it has to do a lot of reflection on internals, it's possible to remove all blocking, but we have to be careful with the size impact.

**Comment by davidsh** [comment]
>@davidsh, "Required All" does work for customer assemblies, but for framework assemblies, we block reflection on internals on purpose (and you have to make things public to make them reflectable). If you have an assembly where it has to do a lot of reflection on internals, it's possible to remove all blocking, but we have to be careful with the size impact.

Ok. That's good information to know.

I'm trying to figure out whether we have an actual product bug (i.e. NetEventSource won't work in .NET Native compiled apps) vs. a test bug (we can't run our current tests for NetEventSource because they use reflection and that doesn't work on UAPAOT).

**Comment by morganbr** [comment]
@davidsh, got it. It looks like the stack above is from test code reflecting over NetEventSource. If I recall correctly, EventSource might work without reflection on UAPAOT, but @vancem and @brianrob would be the experts on that.

**Comment by davidsh** [comment]
>@davidsh, got it. It looks like the stack above is from test code reflecting over NetEventSource. If I recall correctly, EventSource might work without reflection on UAPAOT, but @vancem and @brianrob would be the experts on that.

One of our NetEventSource tests does reflection so, as you indicated, I expect that test not to work.  So, I'll disable that test on UAPAOT.

However, we have another test that does a real network activity and then we look to see if events were written.  And that test is failing as well.  This worries me because it appears as if EventSource will never work in UAPAOT and that means that shipped UWP apps (which use .NET Native) can't then use EventSource.

See this test that doesn't work:

```c#
        [Fact]
        public void EventSource_EventsRaisedAsExpected()
        {
            RemoteInvoke(() =>
            {
                using (var listener = new TestEventListener("Microsoft-System-Net-Security", EventLevel.Verbose))
                {
                    var events = new ConcurrentQueue<EventWrittenEventArgs>();
                    listener.RunWithCallback(events.Enqueue, () =>
                    {
                        // Invoke tests that'll cause some events to be generated
                        var test = new SslStreamStreamToStreamTest_Async();
                        test.SslStream_StreamToStream_Authentication_Success();
                        test.SslStream_StreamToStream_Successive_ClientWrite_Sync_Success();
                    });
                    Assert.DoesNotContain(events, ev => ev.EventId == 0); // errors from the EventSource itself
                    Assert.InRange(events.Count, 1, int.MaxValue);
                }
                return SuccessExitCode;
            }).Dispose();
        }
```

**Comment by CIPop** [comment]
@davidsh, @vancem Looks like this is a product bug. 
I've tried capturing ETW using [these scripts](https://github.com/dotnet/corefx/blob/master/src/Common/tests/Scripts/Tools/net_startlog.cmd). It works in Core, UAP but it doesn't capture network traces in UAPAOT.

**Comment by brianrob** [comment]
@cipop, @davidsh, EventSource will work for UAPAOT, but is not fully working right now.  I hope to have a change in today that I suspect might help.  That's the first thing to check.  If that doesn't help, then this likely needs to be debugged.  EventSources generally don't throw by design - so the lack of events is expected behavior.

If you're interested in trying out the fix, let me know and I can send you details offline (it's a TFS change).

**Comment by CIPop** [comment]
Changes in #21745 didn't seem to bring ETW tracing to UAPAOT. 
Sounds like there are TFS changes that may need to propagate before we can actually see the difference.

**Comment by brianrob** [comment]
@CIPop this is expected, as #21745 is just test changes.  You need the changes in System.Private.CoreLib which went into TFS.

**Comment by CIPop** [comment]
@brianrob /cc @davidsh, @DavidGoll we're now getting ETW traces for the test assembly but not from any of the production contracts such as System.Net.NameResolution, Primitives, Security or Sockets:

UWP, running in an app-container:
![image](https://user-images.githubusercontent.com/8635911/28093336-b16a4090-664b-11e7-99e6-a66f33e20a5f.png)

UWPAOT, running outside an app-container:
![image](https://user-images.githubusercontent.com/8635911/28093341-bb7d8204-664b-11e7-9869-f7b39518745c.png)

**Comment by davidsh** [comment]
Can you try to enable other System.* ETW traces (non System.Net.* ones)?  

If those show up and ours don't, then perhaps the problem is the way we have defined our base NetEventSource class?

**Comment by brianrob** [comment]
Good, that's consistent with what I'm seeing.  The reason (or at least one of them) is that non-public surface in CoreFX is automatically reflection blocked unless you opt-out, which means that the EventSource name and GUID are wrong (essentially garbage).  I'm currently working on the steps necessary to fix this.

If you unblock reflection, events should get emitted, but they won't show up properly in PerfView because the manifest doesn't get emitted.  There's a difference between chk and ret behavior that I'm currently tracking down.  With chk builds of the app, the manifest gets emitted, but with ret, it doesn't.  I hope to have information for you tomorrow.

**Comment by brianrob** [comment]
FYI @tijoytom - please see my previous comment.  This is likely to be impacting all of the EventSources that are in CoreFX - they will likely need to be addressed individually by area owners.

**Comment by morganbr** [comment]
@brianrob , my understanding is that .NET Native has an IL transformation that is supposed to make EventSource work without reflection. Did that get broken in some way?

**Comment by brianrob** [comment]
@morganbr, there is an IL transform that makes some EventSources work without reflection.  There is a hardcoded list of inbox EventSources that it operates on.  It does have some limitations though - for example it doesn't work if you use localized resources with your EventSource.  I believe there are some other cases, but I can't remember them right now.

**Comment by brianrob** [comment]
It looks like unblocking reflection is what you need to do.  That should be enough to make your events show up when you collect with ETW.  However, I will say that this introduced some failures in the diagnostics tests that I ran (https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/tests/FunctionalTests/DiagnosticsTests.cs).  They were all around missing metadata, so you likely need to add something to your rd.xml.

Hopefully that should unblock you.

**Comment by davidsh** [comment]
>It looks like unblocking reflection is what you need to do. 

What does that mean specifically?  Are you saying we need to change product source code (various libraries of System.Net.*) to "unblock reflection"?  Does that mean we add rd.xml to product source libraries?  If so, which ones, and how?

**Comment by brianrob** [comment]
I should also say that if you don't want to unblock reflection, you should be able to mark the types and probably methods public, and that should unblock them for reflection.  This is likely to be preferable because you'll take a size hit for all of the metadata.

**Comment by brianrob** [comment]
I spoke with @davidsh about this offline.  He's going to start with marking the types as public and go from there.

**Comment by Diego-Perez-Botero** [comment]
I'm working with @davidsh. Marking the types AND methods public does the trick without requiring rd.xml/csproj changes. We'll be going with this approach (#if uap).

**Comment by brianrob** [comment]
Excellent @Diego-Perez-Botero, I'm glad to hear that's working.

**Comment by davidsh** [comment]
@Diego-Perez-Botero 
See this:https://github.com/dotnet/corefx/issues/5755

We were previously warned about the problems we could run into having the same class name in all of the different System.Net.* libraries.  Vance had suggestions of how we could have made our design better.  We ended up in this situation because we tried to copy a pattern we used in .NET Framework. But that only worked well because all of our code was in a single dll.

We should consider changing the class names and other ways that are suggested in that referenced issue.

**Comment by caesar1995** [comment]
@stephentoub 

Reflection doesn't work on ILC (The metadata is stripped away if reflection is not declared at buildtime). The `internal sealed partial class NetEventSource` in `NetEventSource.Common.cs` doesn't work. We tried:
1. Add rd.xml to tell compiler not optimize the types. This will incur in larger metadata sizes.
2. Use `#if-def` to make `NetEventSource` public on ILC build. We will have duplicate type in multiple contrcts. (#22235)
```
C:\corefx\pkg\frameworkPackage.targets(144,5): error : Duplicate type System.Net.NetEventSource in both C:\corefx\bin\W
indows_NT.AnyCPU.Debug\System.Net.Http\uap\System.Net.Http.dll and C:\corefx\bin\Windows_NT.AnyCPU.Debug\System.Net.Htt
pListener\uap\System.Net.HttpListener.dll. [C:\corefx\pkg\Microsoft.Private.CoreFx.UAP\Microsoft.Private.CoreFx.UAP.pkg
proj]
```

For now, we have two ideas for the NetEventSource new design. Both approaches require huge code change the reorganization of the structure.

## The first idea
There will be no general NetEventSource. We use `#if-def` to change the NetEventSource type to the exact contract specific EventSource.
### For contract specific code:
```c#
// Sockets: (defines SOCKETS)
if (SocketsNetEventSource.IsEnabled()) { SocketsNetEventSource.Enter(); }

SocketsNetEventSource.Sockets.cs // rename the file
                public partial class SocketsNetEventSource {...}
```

### For Common logging code
```c#
// logging
NetEventSource.Common.cs:

                public partial class 

#if SOCKETS
                SocketsNetEventSource 
#else if REQUESTS
                RequestsNetEventSource
#endif
                : EventSource {...}

```

### For Common product code
```c#
// product (ContextAwareResult.cs):

internal class ContextAwareResult
{

                private INetEventSource s_log = 
#if SOCKETS
                SocketsNetEventSource;
#else if REQUESTS
                RequestsNetEventSource;
#endif

                /// ...
                if (s_log.IsEnabled()) { s_log.Enter(); }
```

Here is my implementation for NameResolution based on this idea (https://github.com/dotnet/corefx/compare/master...caesar1995:nevent). It compiles fine and every test in S.N.NameResolution will pass (including the logging test, I have re-enabled it).

## The second idea
Stop using Common included source code.

Create a publicly defined base class `NetEventSource` and expose the implementation in the System.Net.Primitives contract with the class definition available in the ref assembly. We can put all of our “common” code in that base class definition and implementation.  Then we can create separate derived classes (SocketsNetEventSource, HttpNetEventSource, etc.) in each library. Those classes will also be public in the implementation (due to ILC.EXE needing that) but we don’t have to expose those classes in the ref assembly.


@davidsh @CIPop @DavidGoll @Diego-Perez-Botero

**Comment by stephentoub** [comment]
> Add rd.xml to tell compiler not optimize the types. This will incur in larger metadata sizes.

How much?  Is it really prohibitive?

**Comment by davidsh** [comment]
@stephentoub It really is more complicated than just the rd.xml optimization. That isn't the real problem.  The real problem is type name clashing since all the type names are "NetEventSource" in all the different assemblies.  And then they get merged via ILC.EXE and stuff breaks.  So, using rd.xml is NOT going to work. Yes, it will expose the types.  But then everything breaks because of the similarly named types (duplicate types) in a single assembly.

I proposed the second idea which I prefer as a cleaner solution.

**Comment by stephentoub** [comment]
> The real problem is type name clashing since all the type names are "NetEventSource" in all the different assemblies. And then they get merged via ILC.EXE and stuff breaks.

Isn't that a toolchain issue then?  Assemblies can contain different internal types of the same name, whether in our code or in customer code.  What makes this case special?

**Comment by stephentoub** [comment]
> I proposed the second idea which I prefer as a cleaner solution.

Am I misreading, or isn't that solution involving publicly exposing new APIs in the ref assembly ("with the class definition available in the ref assembly")?

I already don't like the cases where we've made these kinds of EventSource classes public in the implementation assemblies, but I can at least hold my nose on those due to being hidden behind the contracts.  But now this sounds like it's talking about exposing new public API in the contracts.

**Comment by davidsh** [comment]
>Am I misreading, or isn't that solution involving publicly exposing new APIs in the ref assembly ("with the class definition available in the ref assembly")?

Yes.  I am proposing that.  We can document it as a "infrastructure use only" type of API.  In .NET Framework, we didn't have these issues because everything was in a single assembly (System.dll or System.Net.Http.dll).  But we keep running into cases where we need cross-assembly things because we have currently many different assemblies for components.

**Comment by davidsh** [comment]
>Isn't that a toolchain issue then? Assemblies can contain different internal types of the same name, whether in our code or in customer code. What makes this case special?

Yes, this is a toolchain issue.  But they can't solve it right now.  The alternatives are not to have any tracing for UWP in .NET Native mode or to try to use a messy ifdef approach to rename classes during common source include compiles.

**Comment by stephentoub** [comment]
> Yes. I am proposing that.

Honestly I would rather wait for the toolchain fix and in the meantime have no tracing in these builds than add new public API we need to maintain forever and that anyone could take a dependency on.

But that's just me.  If you want to add new surface area, you'll need to run it through the standard API review process.

**Comment by davidsh** [comment]
>Honestly I would rather wait for the toolchain fix and in the meantime have no tracing in these builds than add new public API we need to maintain forever and that anyone could take a dependency on.
But that's just me. If you want to add new surface area, you'll need to run it through the standard API review process.

I would rather we didn't add API surface either.  But we don't seem to have a good way to share code between library without using duplicated Common source includes.  Perhaps we need a new library that is intended as internal/private use for CoreFx libraries only.  We no longer can use `internalsvisibleto` for example.  We do have Microsoft.*.Private* assemblies and some our other libraries use them for certain things.

We are still working on a good design.

**Comment by jkotas** [comment]
I agree with Stephen.

I agree with Stephen. It is not acceptable to be adding internal types as public APIs just to make reflection blocking happy.

The simplest solution is to disable reflection blocking for the affected libraries. Yes, it has a size hit but it should better not be prohibitive because of all NuGet libraries and app code pays it.

If we are saying that reflection blocking is required to make libraries work great for UWP, then we have a problem because it means that NS2.0 NuGet libraries cannot work great for UWP - reflection blocking is internal undocumented feature.

**Comment by davidsh** [comment]
>The simplest solution is to disable reflection blocking for the affected libraries. Yes, it has a size hit but it should better not be prohibitive because of all NuGet libraries and app code pays it.

My understanding is that disabling reflection blocking is not sufficient to solve this.  One reflection blocking is disabled, the ILC.EXE tools has problems merging all the duplicate class names (NetEventSource) from all the libraries into one EXE.  So, the NetEventSource related class names still need to be made dis-similar and unique across all libraries.

**Comment by jkotas** [comment]
> Once reflection blocking is disabled, the ILC.EXE tools has problems merging all the duplicate class names

@morganbr, @brianrob Is this really the case? Why does ILC tools needs to merge anything here?

**Comment by MichalStrehovsky** [comment]
ILC.exe has no problem with duplicate class names in different assemblies. This happens all the time.

**Comment by DavidGoll** [comment]
Ultimately, this is a tooling issue and we should try to work around it in our implementation. Keeping this issue open, but moving it to 2.1.0.

**Comment by davidsh** [comment]
At this point, we are going to live with this behavior.
