### ISSUE TITLE
Numeric format to percentage: The default value is different from .net framework

### ISSUE THREAD

**Issue by chuanjiao10** [dotnet/corefx#20496]
in windows,the default value depends on user settings(control panel)
in linux,i don't know how to set the default value ? can be set?

Since it has not been resolved, so powershell team members recommend me to submit the issue.
https://github.com/PowerShell/PowerShell/issues/2194

somebody help to see,thanks.

Steps to reproduce
------------------
"{0:p}" -f 0.95
(0.95).tostring("p") 

powershell on windows return(i think return is right):
95.00%

powershell beta1 on .net core 2.0 return:
95.000%

PS /root> [System.Globalization.NumberFormatInfo]::CurrentInfo.PercentDecimalDigits                                                               
3

PS /root> [System.Globalization.NumberFormatInfo]::CurrentInfo.PercentDecimalDigits = 2                                                           
Exception setting "PercentDecimalDigits": "Instance is read-only."
At line:1 char:1
+ [System.Globalization.NumberFormatInfo]::CurrentInfo.PercentDecimalDi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting

Expected behavior
-----------------
default value same with windows

Environment data
----------------

Name                           Value                                                                                                             
----                           -----                                                                                                             
PSVersion                      6.0.0-beta                                                                                                        
PSEdition                      Core                                                                                                              
BuildVersion                   3.0.0.0                                                                                                           
CLRVersion                                                                                                                                       
GitCommitId                    v6.0.0-beta.1                                                                                                     
OS                             Linux 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017                                              
Platform                       Unix                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                               
SerializationVersion           1.1.0.1                                                                                                           
WSManStackVersion              3.0                                                                      

LANG=zh_CN.UTF-8

**Comment by tarekgh** [comment]
net core fully depends on the OS for providing the globalization data in general. we cannot guarantee to get same data across OS's or even between OS versions. this is by design for coreclr. on Linux we depends on ICU to get the globalization data. Windows team currently is conversion to use CLDR (which is used by ICU). if you see any bug in ICU data you can log issue for ICU to get this fixed. I am expecting at some point the data will be almost same in Windows and Linux.

**Comment by chuanjiao10** [comment]
@tarekgh
 how to set The number of digits after the decimal point to 2 on linux when use .net 2 numeric format to percentage?

**Comment by tarekgh** [comment]
```C#
            var currInfo = (NumberFormatInfo) NumberFormatInfo.CurrentInfo.Clone();
            currInfo.PercentDecimalDigits = 2;
            (0.95).ToString("p", currInfo);
```

if you want avoid passing currInfo to the formatting API (e.g. ToString) then you'll need to override the currentculture 

```C#
            var culture = (CultureInfo) CultureInfo.CurrentCulture.Clone();
            culture.NumberFormat.PercentDecimalDigits = 3;
            CultureInfo.CurrentCulture = culture;
            Console.WriteLine((0.95).ToString("p"));
```

**Comment by chuanjiao10** [comment]
3q.
No one feels the default  value is 3, which is unreasonable?

**Comment by tarekgh** [comment]
> No one feels the default value is 3, which is unreasonable?

As I mentioned we get this from ICU on Linux so coreclr has no control over the data. you may check the latest ICU if they changed/fixed that and if not, you may report it to them.
