### ISSUE TITLE
[Proposal] struct T.TryParse methods that return T? instead of bool

### ISSUE THREAD

**Issue by mburbea** [dotnet/corefx#2050]
Currently, many of the primitive/struct types have a `TryParse` that looks like the following
`public static bool TryParse(string input,out T value)`
And the expected usage is something like:
```csharp
int value;
if(int.TryParse(input, out value)){
     value=-1;
}
```

I think it'd be very useful to add an additional `TryParse` method that returns a `T?` instead of returning a bool and requiring passing an out parameter.
The following types could benefit:
  - `sbyte`
  - `byte`
  - `ushort`
  - `short`
  - `int`,
  - `uint`
  - `long`
  - `ulong`
  - `float`
  - `double`
  - `Guid`
  - `decimal`
  - `DateTime` (I'd probably want a form of TryParseExact for this one too)
  - `DatetimeOffset`
  - `enum` 

Possibly other. The example snippet above would become
```csharp
int? value = int.TryParse(input) ?? -1;
```
That looks a lot cleaner to me.

**Comment by whoisj** [comment]
While this sounds super useful, I have no idea how it would implemented. Most `TryParse` methods take a string, how would say a `CustomEventLogger.TryParse` be expected to work?

**Comment by whoisj** [comment]
Adding `TryParse` logic to the above listed types makes sense. I'm sure there are other types which could also benefit from similar methods.

My original comment was deleted as I originally misread the proposal.

**Comment by omariom** [comment]
:+1:

**Comment by whoisj** [comment]
One thing to consider here is the cost of boxing, although the cost of parsing strings is several orders of magnitude larger so I may be a completely moot point.

**Comment by mburbea** [comment]
What boxing? Nothing here should box. `Nullable<int>` is a struct, and the `??` operator will correctly translate it to a
```csharp
int? temp = input.TryParse(input)
int? value = temp.HasValue ? temp : (int?)-1

**Comment by whoisj** [comment]
Sure. However, `Nullable<T>` is a box in its own right. There's still the cost of allocating the extra struct - it fairly trivial, but it exists. Please read above: I **do** support this idea. Vetting it early is generally the best way to get it to pass mustard down the road. :wink:

**Comment by KrzysztofCwalina** [comment]
When we designed the TryParse pattern, we already had Nullable<T>. We explicitly chose not to use Nullable<T>. I am not sure we would like to start using it now, especially that now these new APIs would duplicate the existing ones.

**Comment by mburbea** [comment]
Oh yes, there is a small cost of `Nullable<T>`, and in environments that do not support generics these overloads cannot be present. 
@KrzysztofCwalina , That's true these showed up with 2.0 is there any justification? The only reason I could think of is keep the api symmetric with other `try` methods like `TryGetValue`. 

Another problem, the other problem with the current `Try*` pattern is it doesn't play well with language features like `async` and `yield return` requiring you to create intermediary methods to get the desired result.

 

Using ref/out parameters is very unwieldy. While things like `unsafe` are also unwieldy, they are normally done so to discourage usage, but `TryParse` is an extremely common pattern when dealing with input from a user.

**Comment by whoisj** [comment]
@KrzysztofCwalina excluding maintenance costs of API surface, is the a technical reason to not support these kinds of methods?

**Comment by KrzysztofCwalina** [comment]
@ahejlsberg felt strongly that Nullable<T> should not be used here. If I remember correctly, his justification was that null means "an absence of a value" and should not be used to communicate what amounts to an error (in parsing).

Also, the usage of TryParse seems as nice if not nicer than handling null:
int value;
if(int.TryParse(input, out value)){
   ...
}

vs
int? maybeInt = int.TryParse(input)
if(maybeInt != null){
  ...
} 

I do agree that async adds a twist here, but I am not sure how many Try APIs would/should be async.

**Comment by KrzysztofCwalina** [comment]
@whoisj, it's not about maintenance cost. All about confusion for millions of developers will now see 3 ways to parse and wonder which one they should use. If the value of an addition is very high, we often take the complexity hit, but in this case I have to say I don't see high value of this proposed addition.

**Comment by whoisj** [comment]
Well, I'm not about to argue language design with @ahejlsberg :grin: 

I personally like the `bool TryParse(string, out T value)` model, but there did seem to be cases where a  `T? TryParse(string)` could be considered cleaner. Mostly a moot topic, but interesting none the less. :smile:

**Comment by mburbea** [comment]
I agree that @ahejlsberg probably knows what he's doing :)

As for the pattern though, I think it is unwieldy and `null` meaning of absence also is construed with error very often. Unfortunately, the out/ref patterns are just unwieldy.

**Comment by KrzysztofCwalina** [comment]
Oh, I did not mean to shut the discussion with the trump card. Hopefully Anders can chime in and provide some more insight.

**Comment by svick** [comment]
For me, the problem with the current `Try*` pattern is that variable that you have to declare beforehand. This proposal of returning nullable is one way of solving that. Another is declaration expressions (dotnet/roslyn#254):

```c#
if (int.TryParse(input, out int value))
```

I would like to see either nullable `Try*` or declaration expressions. I don't need both.

**Comment by KrzysztofCwalina** [comment]
I am not sure how nullable solves this problem. See my two samples above one using nullable and one using out param.

**Comment by HaloFour** [comment]
The one case where the use of a nullable return value is nicer is if you want to default in the case of a parser error:

```cs
int value = int.TryParse(s) ?? 0;
```

Otherwise you're writing this:

```cs
int value;
if (!int.TryParse(s, out value)) {
    value = 0;
}
```

**Comment by HellBrick** [comment]
I would prefer the nullable API over the current out-parameter API, mostly because I often find myself in a situation where parsing failure is actually treated like a lack of value rather than an error. This typically happens when you're parsing some optional data that's going to be stored in an `int?` property anyway. And there's also the default value case @HaloFour just mentioned.

By the way, there's at least one more type this would be useful for: `Uri`.

**Comment by Giorgi** [comment]
Nullable TryParse method will also be useful when you have a list of strings and want to get a list of valid int-s. It will work nicely with the `Select` method.

**Comment by pebezo** [comment]
To avoid confusion, I would not call it Try*. Instead I would introduce a different pattern:

`int? result = int.ParseOrDefault(input);`
`int result = int.ParseOrDefault(input) ?? 0;`

This way it's intuitive that the return is not a bool (Try* = success or failure) and it mirrors the FirstOrDefault() pattern.

**Comment by exyi** [comment]
Why was this issue closed? I'd really like this feature.

**Comment by Steinblock** [comment]
While this may be useful in certain situations, I would not include this in the framwork because `Parse` (throws exception on failure) and `TryParse` (returns success) already cover every possible . 

If this proposal finds it's way into the framework you can simple create your own extension for that: [Proposal - Static extension methods](https://github.com/dotnet/roslyn/issues/996)

In the meantime you can create your own extension method.

```c#
string value = "1";
int result = value.TryParseInt(value) ?? -1;

private int? TryParseInt(this string s)
{
     int result = 0;
    if (int.TryParse(s, out result)
         return result;
    return null;
}
```

**Comment by pebezo** [comment]
Sure you can create an extension, but this is such basic functionality that is used all the time, that it should be part of the framework. A lot of times we don't care if the conversion was successful or not. For these cases the framework forces us to declare a variable only because TryParse needs it. 

If this would be a rarely used function then I could understand the reasoning, but it's used in a LOT of places (basically everywhere one needs to convert from a string to a better typed variable).

**Comment by Tydude4Christ** [comment]
I know this issue is closed but I like the ParseOrDefault method pebezo suggested except it should not return a nullable value but add an optional default parameter. See below for the implementation and example code. The value of this addition may be weak so I understand if this isn't seriously considered.

```
public static T ParseOrDefault(string value, T defaultValue = default(T))
{
    T result;
    return TryParse(value, out result) ? result : defaultValue;
}

int result = int.ParseOrDefault(input); // If parse fails returns 0
int result = int.ParseOrDefault(input, 100) // If parse fails returns 100
```

**Comment by Thaina** [comment]
This should be reopened
