### ISSUE TITLE
Failure in .DiagnosticSourceStartStop (slightly out of range)

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20510]
https://mc.dot.net/#/user/dotnet-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/e48d87ac50129845b045371da5e8e32b1f9ba7b7/workItem/System.Diagnostics.DiagnosticSource.Tests/analysis/xunit/System.Diagnostics.Tests.ActivityTests~2FDiagnosticSourceStartStop
```

Unhandled Exception of Type Xunit.Sdk.InRangeException
Message :
Assert.InRange() Failure\r\nRange:  (1/1/01 12:00:00 AM - 5/31/17 5:45:42 PM)\r\nActual: 5/31/17 5:45:42 PM
Stack Trace :
   at System.Diagnostics.Tests.ActivityTests.DiagnosticSourceStartStop() in /mnt/j/workspace/dotnet_corefx/master/portable-linux-Config_Debug+OuterLoop_false_prtest/src/System.Diagnostics.DiagnosticSource/tests/ActivityTests.cs:line 445
```

**Comment by stephentoub** [comment]
This is the same as https://github.com/dotnet/corefx/issues/20418, just with more data after https://github.com/dotnet/corefx/pull/20436.

**Comment by danmosemsft** [comment]
Dupe of #20418
