### ISSUE TITLE
System.Text.Encoding tests are crashing uapaot ilc test run

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#20525]
There are two System.Text.Encoding tests that are crashing the test run process only on Debug builds. From what I can tell after doing some debugging, the problem seems to be when we try to pass in some member data to a Theory, specifically when that member data is an object array for which one of the elements is a string containing a `\0` char. One example of one of the member data that is causing this problem is [this one](https://github.com/dotnet/corefx/blob/master/src/System.Text.Encoding/tests/UTF8Encoding/UTF8EncodingDecode.cs#L26) where the code looks like:
```c#
yield return new object[] { new byte[] { 0, 84, 101, 10, 115, 116, 0, 9, 0, 84, 15, 101, 115, 116, 0 }, 0, 15, "\0Te\nst\0\t\0T\u000Fest\0" };
```
I'm not 100% sure, but I believe that this is causing for us to hit the Debug.Assert() [on this array method](https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/Array.CoreRT.cs#L1214), the code looks like:
```c#
private Object GetValueWithFlattenedIndex_NoErrorCheck(int flattenedIndex)
{
    ref byte element = ref Unsafe.AddByteOffset(ref GetRawArrayData(), (nuint)flattenedIndex * ElementSize);

    EETypePtr pElementEEType = ElementEEType;
    if (pElementEEType.IsValueType)
    {
        return RuntimeImports.RhBox(pElementEEType, ref element);
    }
    else
    {
        Debug.Assert(!pElementEEType.IsPointer);
        return Unsafe.As<byte, object>(ref element);
    }
}
```

The callstack I get for the fail fast is:
```
xunit.console.netcore.dll!$16_System::Linq::Enumerable::<OfTypeIterator>d__32$1<System::__Canon>.MoveNext() Line 26
xunit.console.netcore.dll!System::Collections::Generic::List$1<System::__Canon>.InsertRange(int index=0, System::Collections::Generic::IEnumerable$1<System::__Canon> & collection) Line 814
xunit.console.netcore.dll!System::Collections::Generic::List$1<System::__Canon>.AddRange(System::Collections::Generic::IEnumerable$1<System::__Canon> & collection) Line 271
xunit.console.netcore.dll!$72_Xunit::Sdk::XunitTheoryTestCaseRunner::<AfterTestCaseStartingAsync>d__7.MoveNext() Line 68
```

cc: @AtsushiKan @jkotas

**Comment by tarekgh** [comment]
This is not really Encoding issue. maybe we need to move this issue to other repo (or ProjectN tracking issues)

**Comment by joperezr** [comment]
I agree this might not be a fix in corefx, but I would keep it open to track the work of re enabling the test once this is fixed.

**Comment by joshfree** [comment]
@AtsushiKan PTAL

**Comment by AtsushiKan** [comment]
Now tracking as TFS 460397. Not an Encoding or framework issue afaics. Needs to be investigated by someone who knows what an EETypePtr == 0x540000 means.

**Comment by AtsushiKan** [comment]
Looks like TFS 460335 is already tracking this - NUTC compiler bug forcing that byte array and string to share a room.

**Comment by tarekgh** [comment]
Right TFS:460335 assigned to @davidwrighton and tracking this issue.
