### ISSUE TITLE
Remove new "NotImplementedExceptions" from Exception and LockFreeHashTable.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#20538]
Sites found by tooling:

```
[System.Private.CoreLib] Internal.TypeSystem.LockFreeReaderHashtable`2.Enumerator::Reset()
[System.Private.CoreLib] Internal.TypeSystem.LockFreeReaderHashtable`2.Enumerator::System.Collections.IEnumerator.get_Current()
[System.Private.CoreLib] System.Exception::.ctor(SerializationInfo, StreamingContext)
[System.Private.CoreLib] System.Exception::GetObjectData(SerializationInfo, StreamingContext)

```

## How to remove:

1. Include the following in your .csproj file:

```
    <Compile Include="..\..\Common\src\System\NotImplemented.cs">
      <Link>System\NotImplemented.cs</Link>
    </Compile>
```

Options for removing “throw new NotImplementedException()”:

### If you can implement the missing functionality now:

Do so.

### If this is functionality that’s not supported on a particular framework or OS, replace with

`throw new PlatformNotSupportedException(SR.xxx);`

### If this is an api that needs to throw NotImplemented for backward compat reasons, replace with:
    
`throw NotImplemented.ByDesign;`

or

`throw NotImplemented.ByDesignWithMessage(SR.xxx);`

### If this is a virtual api method that’s only intended to work when overridden by another class, replace with:

`throw new NotSupportedException(SR.xxx);`

(Unless required for backward compat, refrain from throwing NotImplemented out of these.)

### If this is a virtual non-api method that’s only intended to work when overridden by another class, replace with:

An abstract method.

### If this is a compiler or toolchain intrinsic that only needs a body to make C# happy:

 `throw new NotSupportedException();`

### If this is true undone work and you just can’t fix it now, replace with:

`throw NotImplemented.ActiveIssue(“https://github.com/dotnet/corert/issues/xxx”);`   

The string will not leak out via Exception.Message. The string is for tooling and human readers only. In the past, we’ve usually added an inline comment but the trouble with those is that IL-based tooling can’t read comments.

**Comment by morganbr** [comment]
@AtsushiKan is this supposed to be a CoreRT bug?

**Comment by AtsushiKan** [comment]
Yes - forgot to switch to corert page before opening all those.

**Comment by AtsushiKan** [comment]
Wrong repo - moved to corert repo.
