### ISSUE TITLE
Review web-specific encoding APIs

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#2056]
ASP.NET has created [web-specific encoding APIs](https://github.com/aspnet/HttpAbstractions/tree/dev/src/Microsoft.Framework.WebEncoders.Core). @KrzysztofCwalina was driving a working group to push these APIs down so that they can become general purpose BCL-ish APIs. The [resulting is APIs are available here](https://github.com/dotnet/corefx/tree/master/src/System.Text.Encodings.Web).

Here are some raw notes I got from @KrzysztofCwalina to set the context for the review:

1. .NET already contains some similar encoder APIs, but these are not well suited for dependency injection. 
2. The technology is very general purpose, and so we worked with the ASP.NET team to “BCL-ize” the APIs and add them to CoreFx.
3. As part of the move to CoreFx, we made a few changes to the APIs. In particular we added the ability to encode directly to character buffers. Also, we made it simpler to implement perfromand custom encoders. The [new APIs are available here](https://github.com/dotnet/corefx/tree/master/src/System.Text.Encodings.Web).

More details:

* [API Reference](https://github.com/dotnet/apireviews/blob/2015-06-09-os-version/2015-06-16-web-encoders/issue-2056.md)
* [Sample Code](https://github.com/dotnet/apireviews/blob/2015-06-09-os-version/2015-06-16-web-encoders/issue-2056-samples.md)

We need to review these new APIs.

**Comment by terrajobst** [comment]
We believe the feature isn't ready yet. The notes can be found [here](https://github.com/dotnet/apireviews/tree/master/2015-06-16-web-encoders#2056-review-web-specific-encoding-apis).

**Comment by KrzysztofCwalina** [comment]
@terrajobst, should this be closed now? I updated the APIs based on review. The remaining investigation is to decide how these could support UTF8, but we said in the meeting we won't block on it.
