### ISSUE TITLE
Request for Ubuntu 17.04 build

### ISSUE THREAD

**Issue by MaximBar** [dotnet/corefx#20562]
When trying to install Powershell Ubuntu 10.04 .deb package, it asks for dependency libicu55 which is not available for Ubuntu 17.04 (it has libicu57).
I understand that powershell ( https://github.com/PowerShell/PowerShell/ ) is build on this project, and until you release a 17.04 build, they can't release it.
So please, release an Ubuntu 17.04 build/

Thank You,
Maxim.

**Comment by danmosemsft** [comment]
We have added 17.04 support in 2.0, but 2.0 is not shipped yet. Perhaps Powershell folk (@PaulHigin) have a preview based on 2.0 Preview 1?

**Comment by PaulHigin** [comment]
@daxian-dbw The latest builds of PowerShell are using DotNet 2.0 preview but I don't know if we support Ubuntu 17.04 yet.

**Comment by karelz** [comment]
This would be better to file in PowerShell. AFAIK .NET Core 2.0 supports Ubuntu 17.04. If you have evidence that something is wrong, please let us know ASAP (the time for fixing 2.0 is very short).
cc @janvorli

**Comment by janvorli** [comment]
@karelz I have just verified that the latest portable dotnet core 2.0 works fine on Ubuntu 17.04.

**Comment by karelz** [comment]
Great, thanks @janvorli! I guess all should be good for PowerShell now.

**Comment by TravisEz13** [comment]
Talked to @janvorli and by portable, he means targeting runtime id linux-x64 and standalone (specify the runtime id when publishing, which will includes all the assemblies and native shared libraries)
