### ISSUE TITLE
Test Hygiene: DirectoryInfo_Refresh.runTest

### ISSUE THREAD

**Issue by mmitche** [dotnet/corefx#2057]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_unittest_hygiene/21/testReport/(root)/DirectoryInfo_Refresh/runTest/

**Comment by ianhays** [comment]
This test no longer exists.

Also the link leads to a 404 page.

**Comment by mmitche** [comment]
@ianhays Ahh...we purge jobs after a few weeks to avoid having logs take too much space over time.

Is it not the test at:

src\System.IO.FileSystem\tests\DirectoryInfo\Refresh.cs?

**Comment by ianhays** [comment]
I recently redid that file's tests, and "runTest" is no longer a member. The replacement tests don't fail intermittently like the old one did.

**Comment by mmitche** [comment]
@ianhays great to hear, I see it now that I've merged.
