### ISSUE TITLE
DiagnosticSourceListener tests fails events and not enabled and event source count is zero

### ISSUE THREAD

**Issue by tijoytom** [dotnet/corefx#20579]
Tests from "System.Diagnostics.DiagnosticSource\tests"

**Comment by tijoytom** [comment]
#20511

**Comment by vancem** [comment]
@tijoytom  Is this only in .Net Native / CoreRT (what we talked about today)?   If so we should call this out (we should have a label).

**Comment by tijoytom** [comment]
@vancem yes this's only .NET Native ( UWP). What we talked about is different and i got past that issue by adding SkipReflectionBlock metadata to assembly. Now the  test registers event sources and looks for it and fails. This's not a an isolated failure , the same issue surface in #20511 . My understanding is that EventSource code was ported over for NS2.0 , but not much testing was done because of time constraint. 
@brianrob

**Comment by karelz** [comment]
Fixing to exactly 1 area label - see [Triage rules](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified).

**Comment by brianrob** [comment]
Fixed via #22185.
