### ISSUE TITLE
Serialization Backdown shuts down all ParameterInfo serialization, not just the runtime's implementation.,

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#20574]
The decision to make the runtime’s implementation of Reflection objects non-serializable went too far 
and changed the behaviors of methods inherited by all Reflection implementors. In particular,
by changing ParameterInfo.GetRealObject() to throw PNSE, all third-party implementations of ParameterInfo become undeserializable, not just the runtime’s implementation.

The intended change was to make the runtime’s implementation non-serializable which is already accomplished by removing [Serializable] from RuntimeParameterInfo.

This bug is about to be merged into release/2.0.0 via this open PR (https://github.com/dotnet/coreclr/pull/12020)

This issue is about fixing that bug.

**Comment by AtsushiKan** [comment]
cc @danmosemsft 
cc @morganbr

**Comment by danmosemsft** [comment]
@AtsushiKan are you fixing it, or should @morganbr ?
