### ISSUE TITLE
javascript : Need to update WINJS to provide more support for JavaScript Windows UWP APIs  

### ISSUE THREAD

**Issue by Linrstudio** [dotnet/corefx#20613]
There are very many web developers or JS developers who are excited to use JS or JavaScript for development in UWP. Now I've been using WINJS, but it's been a long time since it's been updated, and the new API is not going to happen. I hope you can continue to update Winjs. At the same time hope that UWP can introduce JS part of the function.

----------------------------------------------
有非常非常多的网页开发人员或是node.js 开发人员，如果能在 UWP 中使用 node.js 或是 Javascript 做开发，是非常另人兴奋的。现在我一直在使用 WinJS，但是已经很长一段时间没有再更新过了，新的 API 也没有办法实现。希望可以继续更新 WinJS。同时希望UWP能引入 node.js 的部分功能。

**Comment by karelz** [comment]
@Linrstudio you are on the wrong GitHub repo. Please find the right place for your WinJS questions.

I wonder what lead you to our CoreFX repo?

**Comment by karelz** [comment]
Similar to #20615
