### ISSUE TITLE
WebView: The Webview API requires additional access to the IFRAME.

### ISSUE THREAD

**Issue by Linrstudio** [dotnet/corefx#20615]
Webview need to add Invokescriptasync access to the IFRAME.

----------------------------------------------------------------------
WebView 需要添加 invokeScriptAsync 对 iframe 的访问。

**Comment by danmosemsft** [comment]
@Linrstudio I believe you have the wrong repo. This is for .NET Core framework. We aren't related to WinJS. @karelz where should feeback for that go?

**Comment by karelz** [comment]
No idea. @Linrstudio what is the namespace / API documentation?
Out of curiosity, why did you file the issue in this repo? What lead you to that? (it will help us identify gaps in proper routing in future)

**Comment by danmosemsft** [comment]
@karelz it is part of the modern Windows SDK, for UWP apps

**Comment by Linrstudio** [comment]
Sorry, I want to post the URL, But I do not know how to.
https://github.com/dotnet/corefx/milestone/13

**Comment by karelz** [comment]
Got it, that is our milestone for **.NET** in UWP. You will need to find the right forum/GitHub repo for WinJS. I would recommend to start on StackOverflow.com.

**Comment by karelz** [comment]
Similar to #20613
