### ISSUE TITLE
X509certificate2 does not work properly

### ISSUE THREAD

**Issue by neil-119** [dotnet/corefx#2062]
I created a certificate object like so:

```
var certificate = new X509Certificate2(pathToP12File, theSecretKey, X509KeyStorageFlags.Exportable);
```

When targeting DNX451, the code above works perfectly. However, when targeting DNXCore50, it throws the following exception:

**Exception thrown: 'System.Security.Cryptography.CryptographicException' in mscorlib.dll. Additional information: Cannot find the requested object.**

I am on beta4, but will try upgrading shortly.

**Comment by neil-119** [comment]
I'd also like to add that VisitBinary etc in ExpressionVisitor is never called in DNX Core 5 but works just fine in DNX 4.5.1.  Following this blog: http://blogs.msdn.com/b/mattwar/archive/2008/11/18/linq-links.aspx

**Comment by stephentoub** [comment]
> Second issue

@neil-119, thanks for the info; please open a separate issue for your second concern.

**Comment by bartonjs** [comment]
@neil-119 Have you had a chance to try with beta5? beta4 came out before we had the cryptography libraries ready for publication (notably, for dnxcore50 CryptographicException has moved out of mscorlib).

**Comment by neil-119** [comment]
Looks good now! Closing this issue.
