### ISSUE TITLE
XmlReader, XmlTextReader cannot resolve files when created with an absolute file path base uri on Unix

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#20626]
The XmlReader and XmlTextReader have a number of methods that accept a url string which used as the base uri to resolve other files.

XmlReader.Create(string) and new XmlTextReader(string) will convert the native file paths to an absolute file:// url and use that as the BaseURI. The other overloads do not convert the url-argument and use it as the BaseURI.

On Windows this works fine. Even when not converted to a file:// url, the resulting BaseURI string is treated as an absolute uri to resolve the other uris.

On Unix, the overloads that use the url-argument as-is don't work. The BaseURI (e.g. /tmp/myfile.xml) is considered to be a relative url and isn't used to resolve other files.
This was observed with failing tests in https://github.com/dotnet/corefx/pull/19735. The difference is due to the Uri class treating absolute file uris as relative on Unix (cfr https://github.com/dotnet/corefx/issues/20046). The tests were updated to pass (https://github.com/dotnet/corefx/commit/3a3ead6abb6c27364f12e41478a34d79ced6fdd1#diff-0bf8d1637c34db29730c199a32fd08ff).

This breaks existing code when running on Unix instead of Windows. These can be fixed with changes like the ones made to the tests.

To avoid breaking existing code, an option is to convert the url-arguments on Unix so they also become absolute uris. This is implemented in: https://github.com/dotnet/corefx/pull/20561. The PR only changes the behavior on Unix when passing an absolute native file path.

@karelz @stephentoub @sepidehMS @krwq

**Comment by tmds** [comment]
@karelz per https://github.com/dotnet/corefx/pull/20561#issuecomment-305516089, can we set this to 2.0 milestone?

**Comment by karelz** [comment]
@sepidehMS @krwq should drive these decisions ... I am not fully up to speed here

**Comment by tmds** [comment]
@sepidehMS @krwq PR is reviewed. I think this is 2.0 bugfix. What should happen now?

**Comment by krwq** [comment]
@tmds I'm still not convinced we should differ on how we parse uris in XML vs rest of the framework

**Comment by tmds** [comment]
@krwq This makes code like `XmlReader.Create(fullPath)` work cross-platform. Do you see downsides?

**Comment by krwq** [comment]
@tmds Uri not working cross-platform as well, Uri behaving differently than Xml

**Comment by krwq** [comment]
@tmds, wait a sec - I though all affected APIs were taking baseUri and not fullPath - for fullPath we should fix it, for baseUri I'm voting for not fixing

**Comment by tmds** [comment]
@krwq these api's take a `string` which has in it's name `uri`. If you set this to a full path on Windows, the reader can resolve other files.  I'm proposing the same behavior on Unix. I don't see any downsides. Do you?

**Comment by tmds** [comment]
@karelz @krwq @sepidehMS @stephentoub there are no outstanding actions for me on the issue and related PR. We need reach a decision whether this change will be included and in what version.

**Comment by sepidehMS** [comment]
Since this resolves a behavior inconsistency between Windows and Unix where a string fullpath uri is passed to XmlReader, I believe we should take it for 2.0. Otherwise, existing code might break when ported from Windows to Unix. @danmosemsft what is the bar for 2.0 port?
cc: @krwq

**Comment by danmosemsft** [comment]
The bar is that we would likely service the product to take the change. (As well as risk level is acceptably low). As a rule of thumb I would also assume that if the change broke something, we might have to ship that way.

@JeremyKuhne since this is analogous to paths, what's your opinion? + @davidsh for URI

**Comment by JeremyKuhne** [comment]
I do think we should take it for 2.0, but we should isolate the change to the Unix build and not do a runtime check.

**Comment by danmosemsft** [comment]
I support that. @stephentoub are you comfortable wiht the change? If you sign off, let's merge it and prepare a 2.0 change.

If shiproom rejects it for 2.0 we might want ot pull it from master.

**Comment by stephentoub** [comment]
> @stephentoub are you comfortable wiht the change?

Yes.  Left a few comments on the PR, but generally it looks good.

**Comment by davidsh** [comment]
>@JeremyKuhne since this is analogous to paths, what's your opinion? + @davidsh for URI

In terms of the proposed System.Uri changes, as long as they are scoped to just *NIx based parsing changees for filepaths, then the risk is low.  The RFCs for Uri are not very crisp on file-based paths in general, even for Windows.

**Comment by sepidehMS** [comment]
Fixed in https://github.com/dotnet/corefx/pull/20561. Closing.

**Comment by karelz** [comment]
Reopening the PR above is in 2.1, not in 2.0. @sepidehMS is there another PR which ported the fix into rel/2.0.0 branch?
If yes, can you please link it from top post of the PR? (I updated #20561 already)

**Comment by sepidehMS** [comment]
@karelz Done.

**Comment by Petermarcu** [comment]
@sepidehMS I assume this issue can now be closed?

**Comment by sepidehMS** [comment]
> @sepidehMS I assume this issue can now be closed?
Yes, this has been fixed in both 2.1 and 2.0
