### ISSUE TITLE
OpenText and FileStream cannot open file in readonly mode

### ISSUE THREAD

**Issue by nicolasr75** [dotnet/corefx#20624]
In a .NET Core (actually ASP.NET Core) project I am trying to read log files. The log files get created by a logger (Serilog in my case). When I try to open the currently written log file with this code

```c#
using (FileStream fs = new FileStream(filename, FileMode.Open, FileAccess.Read)) 
{
    using (StreamReader reader = new StreamReader(fs))
    {
        string content = await reader.ReadToEndAsync();
        ...
    }
}

```
I get a concurrency exception ("The process cannot access the file ... because it is being used by another process"). Notepad and Notepad++ can open the file for reading without any problem though!

It seems almost like the readonly flag would not be respected. Is there anything wrong on my side?

This is on Windows 10, VS 2017, netcoreapp1.1

**Comment by karelz** [comment]
Did you check that the file is not opened by another process? You might need to use [overload with `FileShare`](https://msdn.microsoft.com/en-us/library/5h0z48dh(v=vs.110).aspx).
I would be shocked if something as basic as file open has a bug in it.

Try the same code in Console app and in Desktop .NET Framework app, when your app is running.

**Comment by nicolasr75** [comment]
That is exactly the point: the file is in use by another process! But Notepad can open it for reading, the code that I showed not.

The overload you mention solves it though! I wasn't aware that the default is `FileShare.Read` which means this must fail if another process already has write access. The team probably has good reasons for this, I just had expected it to be `FileShare.ReadWrite` because that is how most text editors behave.
Thanks for the quick feedback. Can be closed.

**Comment by stephentoub** [comment]
> Can be closed.

Closing.

**Comment by karelz** [comment]
> I wasn't aware that the default is `FileShare.Read` which means this must fail if another process already has write access. The team probably has good reasons for this, I just had expected it to be `FileShare.ReadWrite` because that is how most text editors behave.

AFAIK C/C++ has the same default. This default exists 15 years in .NET Framework :).
Editors are special apps. General apps can rarely cope well when the content of the file is changed under their fingers, that's why `FileShare.ReadWrite` is usually an exception. `FileShare.Read` makes more sense, but it is what is it for last decades in C# & in C/C++.

**Comment by nicolasr75** [comment]
And that's why I never had to deal with that sort of problem in 15 years ;-)
But this time it is sort of a log viewer and it's the normal case that the file is opened for writing by the log writer at the time. Seems special to me too.
