### ISSUE TITLE
Using System.Runtime.Loader library for netstandard 1.3

### ISSUE THREAD

**Issue by spati2** [dotnet/corefx#20631]
I have a project that uses netstandard1.3 and I was wondering if there is support for System.Runtime.Loader on this framework and if not what is the alternative?

**Comment by karelz** [comment]
What is "this Framework"? The API is available on .NET Core 1.0+ -- see details in https://apisof.net/catalog/System.Runtime.Loader

**Comment by spati2** [comment]
The framework in question is netstandard1.3. As per nuget the package supports netstandard1.5.

**Comment by mellinoe** [comment]
The NuGet package is a bit confusing in this regard -- System.Runtime.Loader only supports .NET Core.

**Comment by spati2** [comment]
gotcha
