### ISSUE TITLE
Serializable attribute was removed on the System.Diagnostics.Activity

### ISSUE THREAD

**Issue by lmolkova** [dotnet/corefx#20640]
Activity was serializable because the current Activity is stored in the logical call context on .NET 4.5.

It was accidentally removed in https://github.com/dotnet/corefx/pull/19742 that causes SerizalizationException on .NET45 when Activity leaves AppDomain.

It only affects .NET45 and we do not have automated testing for it in corefx. We have tested it manually and agreed on the risk that it may break (#17262 (comment))

Our partners (ApplicationInsights) that consume this API do not have scenarios that involve cross AppDomain calls when the serialization breaks. So it was not detected there either

**Comment by danmosemsft** [comment]
Seems just reversing this:
```
diff --git a/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.Current.net45.cs b/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.Current.net45.cs
index b8b2bd24d8..d303b14274 100644
--- a/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.Current.net45.cs
+++ b/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.Current.net45.cs
@@ -7,7 +7,6 @@ using System.Security;
 
 namespace System.Diagnostics
 {
-    [Serializable]
     public partial class Activity
     {
         /// <summary>
@@ -35,7 +34,6 @@ namespace System.Diagnostics
```

**Comment by danmosemsft** [comment]
@morganbr can you please make this change and prep a port for 2.0? We may have to respin for preview 2.

**Comment by danmosemsft** [comment]
@krwq is around, he will do it.

**Comment by danmosemsft** [comment]
@lmolkova can you test the change if @krwq makes it?

**Comment by danmosemsft** [comment]
We should also add a prominent comment so it isn't removed in future. (Not that I expect us to ever remove [Serializable] anywhere public again)

**Comment by stephentoub** [comment]
Anyone concerned that someone could be using BinaryFormatter with Activity, upgrade from .NET 4.5 to something newer, and their code breaks?

**Comment by lmolkova** [comment]
@danmosemsft @morganbr @krwq 
I have the change and I'm testing it. It requires .net 4.5 test that are not automated as there is no .net4.5 configuration for net45 tests.
I'll submit PR once tests pass in ~1 hour.

I'll add comment not to remove it, however when there is a change like  #19742 with 460 files it's hard to notice it. 

I would really appreciate if you guys notify me when another change for Serializable happens.

**Comment by lmolkova** [comment]
@ stephentoub

If it helps, Activity stores itself in LogicalCallContext on .NET4.5 and uses AsyncLocal on other versions. So if users upgrade, they do not longer have Serializable attribute on Activity. Does it clarifies your concern?
Otherwise, could you please give me some more details on BinaryFormatter (I'm not familiar with it) and why upgrade matters?

**Comment by stephentoub** [comment]
> So if users upgrade, they do not longer have Serializable attribute on Activity. Does it clarifies your concern?

No.  I'm not talking about Activity's own storage of itself into LogicalCallContext.  I'm saying what if someone does this:
```C#
Activity a = ...;
CallContext.LogicalSetData("myactivity, a);
```
or this:
```C#
Activity a = ...;
var f = new BinaryFormatter();
var s = new MemoryStream();
f.Serialize(s, f);
```
With Activity marked a [Serializable] in 4.5 but not for subsequent versions, those snippets would succeed on the code running with .NET 4.5 and then start failing on upgrade to something later.

Or am I missing something?

**Comment by stephentoub** [comment]
Does Activity itself need to be marked Serializable, or could the implementation actually store some private state into the call context (the code reading it out would then construct am Activity from our around it)? That thing could be Serializable, and Activity could be left unadorned.

**Comment by lmolkova** [comment]
Activity is the new API, added in DiagnosticSource 4.4.0 (never released as stable) so the chances that someone already serialized beside the Activity itself are close to zero.

> Does Activity itself need to be marked Serializable, or could the implementation actually store some private state into the call context (the code reading it out would then construct am Activity from our around it)? That thing could be Serializable, and Activity could be left unadorned.

Activity.Current (that is wrapper around Get/Set Logical CallContext) is supposed to be heavily called by the application (basically for every log/trace), so reconstructing Activity every time from the private state could give huge performance impact

**Comment by stephentoub** [comment]
> so the chances that someone already serialized beside the Activity itself are close to zero.

Yet we're building this explicitly so that folks can use it with .NET 4.5.  By definition then those developers will be using Activity on .NET 4.5. I agree cases like I mention won't be common, but we're generally very protective of breaks going from desktop version N to N+1, and that's actually what this is.

> so reconstructing Activity every time from the private state could give huge performance impact

It wouldn't have to reconstruct it every time, just the first time; after that it could be cached for subsequent use.  I've not looked at the implementation, but imagine for example that Activity had something like the following sketch:
```C#
class Activity
{
    private State _state;
    ...

    public static ActivityCurrent
    {
        get => ((State)CallContext.LogicalGetData(Key))?.AssociatedActivity;
        set => CallContext.LogicalSetData(Key, _state);
    }
 
    [Serializable]
    private class State
    {
        ...
        public Active AssociatedActivity => _associatedActivity ?? (_associatedActivity = new Activity(this));
        [NonSerializable]
        private Activity _associatedActivity;
    }
}
```
Then the state could still be marshaled across appdomains in the call context due to being serializable, but Activity itself wouldn't need to be, and thus there wouldn't be concerns about differences across implementations.  Activity is using call context as an implementation detail in .NET 4.5; I'm suggesting that its [Serializable] also then be an implementation detail, one that doesn't bleed through as much as it currently does.

**Comment by lmolkova** [comment]
> With Activity marked a [Serializable] in 4.5 but not for subsequent versions, those snippets would succeed on the code running with .NET 4.5 and then start failing on upgrade to something later.

Now I've got you concern, it's valid. 
Storing Activity in the LogicalCallContext dot not make too much sense, since there is Activity.Current that do it. 
And typical Activity usage we are predicting suggests that whole Activity should not leave the process, and only it's properties (Id and Baggage) could be used to propagate operation context over the wire.
So your concern is valid, but the use case where it may break is not.
If we want to address it, should we mark Activity as serializable on all .net frameworks targets?

**Comment by lmolkova** [comment]
>It wouldn't have to reconstruct it every time, just the first time; after that it could be cached for subsequent use. 

Current could change at any moment, so caching it is not possible

**Comment by stephentoub** [comment]
> Current could change at any moment, so caching it is not possible

I think we're talking past each other.  You can see in my sketch earlier that I'm caching it, but I'm caching it on the object that's stored in call context.

**Comment by lmolkova** [comment]
I've got your point. I think we should not do that as a hotfix for 2.0 as it would require quite a big change. We should consider it for 2.1 though.

**Comment by danmosemsft** [comment]
@lmolkova you will need to mail shiproom to ask for permission to submit into 2.0. Also let them know if it must go in preview 2.

**Comment by karelz** [comment]
@vancem can you please chime in?

> @lmolkova I would really appreciate if you guys notify me when another change for Serializable happens.

Unfortunately I don't think it is sufficient and I don't know how to make that scalable. The same thing will happen for any other thing for which we do not have test coverage. I think the only sensible thing is to create a test suite targeting all 4.5 specifics in the package and run them manually as signoff before every release. Otherwise we won't be able to prevent thee mishaps from happening I am afraid :(
