### ISSUE TITLE
System.IO.FileSystem.Tests - four tests fail if %TMP% directory is a junction.

### ISSUE THREAD

**Issue by ghost** [dotnet/corefx#20652]
System.IO.FileSystem.Tests

-method System.IO.Tests.Directory_Move.MoveFile_TrailingSourceAltSlash_Windows
-method System.IO.Tests.Directory_Move.MoveFile_TrailingSourceSlash
-method System.IO.Tests.DirectoryInfo_MoveTo.MoveFile_TrailingSourceAltSlash_Windows
-method System.IO.Tests.DirectoryInfo_MoveTo.MoveFile_TrailingSourceSlash

These tests will fail on Windows if %TMP%/%TEMP% is set to a directory that's actually a junction to another partition. (The underlying Win32 MoveFile() api happily renames the file non-withstanding the trailing slash so the expected IOException is not generated.)

**Comment by JeremyKuhne** [comment]
Triage: Not a common scenario.
