### ISSUE TITLE
System.Composition.Tests disabled on UapAot

### ISSUE THREAD

**Issue by zacharycmontoya** [dotnet/corefx#20656]
Implementing ResourceManager alone did not resolve these issues. There seems to be an issue with the resources not being present that requires further investigation.

System.Composition.Lightweight.UnitTests.MetadataViewGenerationTests
 - AConcreteTypeWithUnsupportedConstructorsCannotBeUsedAsAMetadataView
 - UnsupportedMetadataViewMessageIsInformative

System.Composition.UnitTests.ContractTests
 - FormattingTheContractPrintsConstraintKeysAndValues
 - FormattingTheContractPrintsNameAndDiscriminator

System.Composition.UnitTests.DiscoveryTests
 - InstanceExportsOfIncompatibleContractsAreDetected
 - MultipleImportAttributesAreDetected
 - PropertyExportsOfIncompatibleContractsAreDetected

System.Composition.UnitTests.ErrorMessageQualityTests
 - MissingTopLevelExportMessageIsInformative
 - MissingTopLevelNamedExportMessageIsInformative

System.Composition.UnitTests.ExportFactoryTests
 - TheSameSharedInstanceIsReusedWithinItsSharingBoundary

System.Composition.UnitTests.OpenGenericsTests
 - TypesWithMismatchedGenericParameterListsAreDetectedDuringDiscovery
 - TypesWithNonGenericExportsAreDetectedDuringDiscovery

System.Composition.UnitTests.SharingTest
 - BoundarySharingTest
 - CircularBoundarySharingTest
 - MultipleBoundarySpecified

**Comment by danmosemsft** [comment]
This is a relatively low priority for this release.

**Comment by stephentoub** [comment]
We no longer run tests on a `uapaot` configuration.
