### ISSUE TITLE
Are DataColumn, DataTable and DescriptionAttribute supported with ASP .Net Core ?

### ISSUE THREAD

**Issue by archanasoni** [dotnet/corefx#2065]
I am trying to compile my existing app with ASP .Net Core 5.0. During compilation several error we are getting error like : 
error CS0246: The type or namespace name 'DescriptionAttribute' could not be found (are you missing a using directive or an assembly reference?)
etc.

Aren't these supported ?

**Comment by Maxwe11** [comment]
https://github.com/dotnet/corefx/issues/1039

**Comment by FredyWenger** [comment]
**Any news on this?**
I have to write a webservice with access to an existing MS-SQL-Server (**what - I think - is one of the main-reasons to create a webservice b.t.w.**) and lost two full day's to see that SQL-Client is only implemented "half (some objects like SqlCommand and SqlConnection are known, but other important objects like DataTable and SqlDataAdapter are not found).
**This posting is from Jun 2015...**
**When can i expect full support ?**
**_If not in the near time, I can't use MVC6 for my project!_**
