### ISSUE TITLE
Inconsistent behaviour of build.sh -? (help) command on OSX

### ISSUE THREAD

**Issue by 4creators** [dotnet/corefx#20665]
**./build.sh -? command displays help mixed with other actions  - installs dotnet cli, restores build tools, initializes build tools**

After installing prerequisites and cloning corefx repo based on my experience from Windows platform I have typed ./build.sh -? to get info on invocation parameters.

Script performed synchronously intermingled tasks:
1. display partial help
2. (i) Installing dotnet cli..., (ii) Restoring BuildTools version 2.0.0-prerelease-01630-02... (iii) Initializing BuildTools...
3. display remaining help

Complete output of the commad is in attached file.
[osx_corefx_build.sh_-?.txt](https://github.com/dotnet/corefx/files/1049612/osx_corefx_build.sh_-.txt)

Coreclr was successfully built for all configurations before attempting corefx build.

System: 

```
  System Version:	macOS 10.12.5 (16F73)
  Kernel Version:	Darwin 16.6.0
  Boot Volume:	Macintosh HD
  Boot Mode:	        Normal
  Computer Name:	MacBook Air
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	21:56
```

**Comment by karelz** [comment]
@4creators I don't quite understand what is your suggestion / ask, can you please clarify? Thanks!

cc @wfurt

**Comment by 4creators** [comment]
@karelz cc @wfurt  When someone passes help option to script build.sh expected behaviour is that usage info will be displayed. Instead build.sh -? command call starts both usage display and initial build steps as described. So instead of getting usage info only I get usage plus some build steps done in intermingled way. Pls look at attached terminal dump. I was quite confused as well

**Comment by jkotas** [comment]
Related to https://github.com/dotnet/corefx/issues/15184

**Comment by wfurt** [comment]
Thanks for the link @jkotas. I think it is quite reasonable if -? or --help only shows help without any other action. Alternatively we could remove that altogether and depend on instructions from Documentation folder.

**Comment by 4creators** [comment]
I have checked build -? behaviour on Windows and it's the same problem as on Mac. Calling it will start both usage display and installation and initialisation of tools in clean repo. As issue #15184 points out is't a problem of centralised command line parsing for build system based on run.exe but in my opinion use of run.exe should not create any additional build dependencies except for what is available in clean repo clone.

**Comment by weshaggard** [comment]
Lets use #15184 to track the run command conversations.
