### ISSUE TITLE
xUnit results reformatting

### ISSUE THREAD

**Issue by willdean** [dotnet/corefx#20674]
It appears that xUnit itself can output results in XML (its own) or XML (nUnit compatible) or HTML formats.

However, it appears that only the first option is supported within the tools in use on CoreFx.  I'm trying to make sense of local test results (i.e. I can't benefit from any CI result formatting), and I'm unclear how best to do this.

* I could just write something to process the XML, but that does seems like it's something which has probably already been done.
* I have tried passing `-html <filename>` to the test runner, but that causes an exception after all the tests have run:

```
Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Xunit.ConsoleClient.TransformFactory.<>c__DisplayClass5_0.<GetXmlTransformers>b__1(XElement xml)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Xunit.ConsoleClient.Program.RunProject(String defaultDirectory, XunitProject project, Boolean teamcity, Boolean ap
pVeyor, Boolean showProgress, Nullable`1 parallelizeAssemblies, Nullable`1 parallelizeTestCollections, Nullable`1 maxThr
eadCount)
   at Xunit.ConsoleClient.Program.Main(String[] args)
```

* I have tried searching for suitable tools on the Internet, but xUnit is a difficult thing to search for and I drew a blank there, other than the xUnit site itself which implies that it's built in (which I think must be for a different version).

I really just want a table with test names, status and run-duration - do people just roll this stuff themselves from scratch, or is there a command line recipe I'm missing?

#5593 might be relevant, but I wasn't clear how that actually related to xUnit as it is at present within corefx.

**Comment by danmosemsft** [comment]
The callstack above (along with sample XML maybe?) might be a good thing to open on the xunit repo.

**Comment by danmosemsft** [comment]
I repro the failure myself, perhaps I can have a look

**Comment by danmosemsft** [comment]
We use quite an old copy of xunit and I'm having trouble building xunit.console.netcore in buildtools with a newer one. I'll have to look tomorrow.

**Comment by danmosemsft** [comment]
@weshaggard I updated as below and compilation fails (with or without the xunit.abstractions line) apparently because it can't find xunit.abstractions. What am I doing incorrectly?
```
+++ b/src/xunit.console.netcore/project.json
@@ -1,14 +1,15 @@
 {
   "dependencies": {
-    "xunit": "2.2.0-beta2-build3300",
-    "xunit.runner.utility": "2.2.0-beta2-build3300",
+    "xunit": "2.2.0",
+    "xunit.runner.utility": "2.2.0",
+    "xunit.abstractions": "2.0.1",
     "Microsoft.NETCore.App": {
```

**Comment by willdean** [comment]
@danmosemsft Thanks for looking at this - don't spend too long on it, because I could knock-up something that extracts what I want from the XML very quickly.

I have not filed an xUnit issue because I'm not clear that the corefx command line runner is actually something that belongs to the xUnit team - on that other unit-testing issue they seemed to disown it.

**Comment by danmosemsft** [comment]
@willdean this is the part that is ours. I am not familiar with how it all fits together and unfortuantely it looks like I won't have time for a while to learn more.
https://github.com/dotnet/buildtools/tree/master/src/xunit.console.netcore

**Comment by willdean** [comment]
Thanks @danmosemsft - let's not worry about it, it's easy enough to deal with independently - thanks for the help anyway.
