### ISSUE TITLE
Collection

### ISSUE THREAD

**Issue by nagarajDeveloper** [dotnet/corefx#20683]
Other than collections are we using System.lynq with any other C# concepts?
if yes other than collection where we are using System.lynq
if no then System.lynq we can add part of System.Collections.Generic;

Please correct me if I am Incorrect.

**Comment by Clockwork-Muse** [comment]
`System.Linq` is used for a couple of different things, which may not be a Collection (it may just be `IEnumerable`, or one of a few other interfaces).

What is it you're trying to accomplish here?

**Comment by nagarajDeveloper** [comment]
Yes, but again IEnumerable is part of System.Collections. so we can add System.Linq classes and properties to System.Collections whenever developer wants to query a collection, developer can avoid importing 2 libraries i.e.  System.Collections and System.Linq respectively. if they imports System.Collections will be enough.

________________________________

**Comment by svick** [comment]
@nagarajDeveloper How would that be achieved? I can see several options, none of which sounds reasonable to me:

* Move `System.Linq.Enumerable` to `System.Collections` (or is it `System.Collections.Generic`?). This would be a major breaking change, so it's not going to happen.
* Add a new class `System.Collections.Enumerable`, in addition to `System.Linq.Enumerable`. I think this would cause ambiguity when selecting which one to use in existing code, so it's also a big breaking change, so it's also not a viable option.
* Add a feature to C# that means when you write `using System.Collections;`, `using System.Linq;` is also implicitly added. This doesn't sound like something that would be worth adding to the language.

Or do you have some other way to accomplish your goal in mind?

**Comment by nagarajDeveloper** [comment]
@svick<https://github.com/svick>

Actually i am talking about third point.when we write using System.Collections.Generic; , using System.Linq; has to add implicitly.

Because as per my understating  we are using "System.Linq" only when we use Collections. then what is point of importing System.Linq explicitly.



if we are using System.Linq rather than collection anywhere please mention those concepts.

________________________________

**Comment by svick** [comment]
> Actually i am talking about third point.when we write using System.Collections.Generic; , using System.Linq; has to add implicitly.

In that case, there is nothing to be done in corefx and instead you should reopen this issue in [the csharplang repo](https://github.com/dotnet/csharplang), since you're proposing a change to the C# language (and not a change to the libraries).

But like I said, I wouldn't expect such a feature to be actually added to the language, I don't think it would be worth it.

> if we are using System.Linq rather than collection anywhere please mention those concepts.

`System.Linq` also contains `IQueryable<T>` and PLINQ, not sure if those make a difference.

**Comment by ganesanarun** [comment]
We can use Linq over XML document, dataset, IQuaryable. So it does not make
sense to me to implicitly include System.Linq into System.Collections. And
also, there is no guarantee that I will always use linq for whenever I
refer collections. Linq itself is heavy library, it would be better to
include it explicitly whenever needed.

**Comment by nagarajDeveloper** [comment]
Thanks  Ganesan Arunachalam 😊

you are right. it's clear for me now.


________________________________
