### ISSUE TITLE
Malformed Uri in BitmapIcon causing crash in .NET Native Interop

### ISSUE THREAD

**Issue by martinsuchan** [dotnet/corefx#20689]
Not sure, if this is the right place to report bugs in UWP runtime, but this one looks quite interesing.

Orginally reported here on UserVoice: [BitmapIcon with UriSource="about:blank" causes app crash in edgehtml.dll](https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/19455838-bitmapicon-with-urisource-about-blank-causes-app)

If I use anywhere in my UWP app <BitmapIcon> with UriSource="about:blank", this can happen when using databinding, **the app crashes when navigating to other page which contains WebView**. 
Tested on Windows 10 Creators Update, VS2017 15.2. 
100% repro is available in ZIP below. 
Repro: https://1drv.ms/u/s!AlURSa6JiyiVo4lNj0cWfTva0_dN1A

The bug looks like some kind of Out-of-Bounds read, can't tell really.
SharedStubs.g.cs -> ComCallHelpers
![image](https://cloud.githubusercontent.com/assets/3041397/26774811/5ef6343a-49d2-11e7-9fe7-34213f05dc90.png)

**Comment by danmosemsft** [comment]
@MattWhilden where should this go.

**Comment by MattWhilden** [comment]
Using the solution you provided I've observed that this issue occurs with or without .NET Native (DEBUG vs RELEASE config). It's a fail fast coming out of edgehtml and I'll need to chase someone down in their org to take a look.
