### ISSUE TITLE
Reference Source hashes have changed, so links no longer work

### ISSUE THREAD

**Issue by IanKemp** [dotnet/corefx#20690]
1. Go to http://referencesource.microsoft.com/
2. Scroll down to the `Link to a type/member` text and click the link corresponding to that text: http://referencesource.microsoft.com/mscorlib/a.html#1f55292c3174123d
3. Notice that you are not directed to the appropriate line of code as you would expect. Instead, you are shown a page containing the text `Don't use this page directly, pass #symbolId to get redirected.`

This seems to have occurred because the file hashes (I assume) that are used for this functionality have changed. [This affects Visual Studio extensions like Ref12](https://github.com/SLaks/Ref12/issues/32#issuecomment-306161359).

**Comment by stephentoub** [comment]
cc: @richlander, @terrajobst

**Comment by karelz** [comment]
@preetikr can you please help?

**Comment by tarekgh** [comment]
https://github.com/dotnet/corefx/issues/16441

**Comment by tarekgh** [comment]
@preetikr @richlander why the repo https://github.com/Microsoft/referencesource not allowing creating issues there? can we change that so the related issues can be opened there?

**Comment by terrajobst** [comment]
> Why does the repo https://github.com/Microsoft/referencesource not allow creating issues there? 

We’ve disabled filing issues on referencesource because folks never reported infrastructure issues but bugs against .NET Framework, which we didn’t want, so we disabled it.

**Comment by tarekgh** [comment]
@terrajobst would you enable creating issues in this repo?

**Comment by terrajobst** [comment]
I've submitted a PR to add the issue template. Once merged, I'll re-enable issues (https://github.com/Microsoft/referencesource/pull/27).

**Comment by tarekgh** [comment]
closing the issue here as I moved it to https://github.com/Microsoft/referencesource/issues/28
