### ISSUE TITLE
System.IO.FileLoadException - Exception from HRESULT: 0x80131040

### ISSUE THREAD

**Issue by jmroyb** [dotnet/corefx#20695]
Folks,

I added System.Diagnostics.Process in a netstandard 1.6 library and I get this exception:

'System.IO.FileLoadException: 'Could not load file or assembly 'System.Diagnostics.Process, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

Before add, lib worked fine. I have added this in App.config (I'm into a WPF 4.7 app) and I get same exception:

      <dependentAssembly >
        <assemblyIdentity name="System.Diagnostics.Process" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="4.1.0.0" />
      </dependentAssembly>

Other test I did:

1. Upgrade System.Diagnostics.Process to 4.3.0 and same app.config
2. Downgrade to netstandard 1.5 both v4.3.0 and 4.1.0

Every step I run nuget locals all -clear and deleted bin and obj folders (all in solution). Desperated I removed System.Diagnostics.Process and tested with System.Console and same results with same tests...
WPF has netstandard 1.6 lib. Tested too netstandard 1.6.1 and same results with same tests ...

Finally I have tested this class library with a new console app (FW 4.7) and same result...

I forgot to tell you, class library and WPF app and console test app are compiled as x64.

[https://drive.google.com/open?id=0B3M-4-kZkv4FSktIbUluVGV1RGs](source with libs)

Please can you help me?

**Comment by karelz** [comment]
@ericstj @weshaggard can you please help?

**Comment by ericstj** [comment]
Make sure you enable bindingRedirects in your desktop project.  https://msdn.microsoft.com/en-us/library/2fc472t2(v=vs.110).aspx

The version of System.Diagnostics.Process from package version `4.3.1`  projects targeting .NET 4.6.1 and greater is `4.1.1.0`.
