### ISSUE TITLE
Replacing Appdomain.GetAssemblies()

### ISSUE THREAD

**Issue by spati2** [dotnet/corefx#20698]
Maybe I am flogging a dead horse here, but could you tell me what the equivalent for Appdomain.GetAssemblies() is in netcore? I think its supposed to be a part of AssemblyLoadContext but I am unable to locate it there.

**Comment by mellinoe** [comment]
@gkhanna79 Do we have any good documentation about the general migration path here?

**Comment by gkhanna79** [comment]
In .NET Core 2.0, you can use AppDomain.GetAssemblies.

**Comment by mellinoe** [comment]
Fair enough -- do we have any guidance for .NET Core 1.0 / 1.1?

**Comment by gkhanna79** [comment]
There is no good way to achieve the same for 1.X - other than manual book-keeping of the assemblies loaded.

**Comment by danmosemsft** [comment]
@spati2 is 2.0 (currently out in Preview 1) an option for you to try? woudl be interested in any other feedback you have on it.

**Comment by spati2** [comment]
Thanks, I will give that a try.
