### ISSUE TITLE
Disabled test on System.Linq.Expressions.Tests on ILC (amd64-x64)

### ISSUE THREAD

**Issue by ghost** [dotnet/corefx#20717]
-method System.Linq.Expressions.Tests.Compiler_Tests.UnaryPlus

which is annoyingly located not in CompilerTests.cs but here...

https://github.com/dotnet/corefx/blob/master/src/System.Linq.Expressions/tests/SequenceTests/SequenceTests.cs#L844

**Comment by danmosemsft** [comment]
@AtsushiKan what was the issue? Do we need @VSadov to look?

**Comment by AtsushiKan** [comment]
>Do we need @VSadov to look?

Yes. No root causing was done on this.

**Comment by danmosemsft** [comment]
@safern can you successfully run these tests? It says "  The system cannot find the file specified." and running runtests.cmd manually gives me an assembly load failure.
This issue may be fixed but I can't tell.

**Comment by safern** [comment]
Let me try it.

**Comment by safern** [comment]
> @safern can you successfully run these tests? It says " The system cannot find the file specified." and running runtests.cmd manually gives me an assembly load failure.
This issue may be fixed but I can't tell.

I was able to run them succesfully and I re-enabled the test locally and it did failed:

```
System.Linq.Expressions.Tests.Compiler_Tests.UnaryPlus(useInterpreter: True) [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
           D:\repos\corefxCopy\corefx\src\System.Linq.Expressions\tests\SequenceTests\SequenceTests.cs(871,0): at Syste
  m.Linq.Expressions.Tests.Compiler_Tests.UnaryPlus()
```

I ran on a clean repo:
```
sync.cmd
build.cmd -framework:uap
msbuild src\System.Linq.Expressions\tests\System.Linq.Expressions.Tests.csproj /p:targetgroup=uap /t:rebuildandtest
```

**Comment by danmosemsft** [comment]
OK. I really am not sure how much this one matters if all the others are passing it seems like a corner case.

@VSadov thoughts? is this necessry for the UWP6 release, which we are closing down soon?

**Comment by danmosemsft** [comment]
Moving out since this seems minor. Feel free to correct.

**Comment by stephentoub** [comment]
We no longer run tests on a `uapaot` configuration.
