### ISSUE TITLE
Disabled IntegratedAuthConnectionTest in System.Data.SqlClient.Tests on ILC

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#20718]
-method System.Data.SqlClient.Tests.SqlConnectionBasicTests.IntegratedAuthConnectionTest

Message from test ouput:

System.Data.SqlClient.SqlException : Failed to accept security SSPI context\r\nFailed to accept security context

**Comment by saurabh500** [comment]
@AtsushiKan Do you have any links to the failed tests?

**Comment by AtsushiKan** [comment]
https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/tests/FunctionalTests/SqlConnectionTest.cs#L30

**Comment by saurabh500** [comment]
@AtsushiKan I meant failing test execution in the CI . :)

**Comment by AtsushiKan** [comment]
They're not in CI yet - slapping ActiveIssues on these is part of them getting them to point where we can get into CI.

Here's a link to the Helix run though I don't know useful these links are. The original text contained the exception message which is pretty much the only useful thing you can get out of these Helix reports right now.

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170605.04/workItem/System.Data.SqlClient.Tests/analysis/xunit/System.Data.SqlClient.Tests.SqlConnectionBasicTests~2FIntegratedAuthConnectionTest

**Comment by corivera** [comment]
I could not repro these integrated auth failures when connecting to SQL Server. Seems like this may be integrated auth bug in the test proxy server code.

**Comment by saurabh500** [comment]
I think this was also related to sni.dll dependency

**Comment by corivera** [comment]
@saurabh500 It still repros for me in uapaot runs. But the failures seem to be coming from the test proxy code. Integrated auth against an actual server using uapaot code works fine.

**Comment by corivera** [comment]
The error seems to be a SEC_E_INVALID_TOKEN error coming from https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/tests/Tools/TDS/TDS.EndPoint/SSPI/SSPIContext.Windows.cs#L199

**Comment by saurabh500** [comment]
Ok. Got it.

**Comment by corivera** [comment]
@saurabh500 I see that the StartServerAuthentication() method in SSPIContext.Unix throws an not supported exception. Any idea why that is? Could this failure be another case where windows specific code is still being used uapaot runs?

**Comment by corivera** [comment]
Issue no longer repros.
