### ISSUE TITLE
Reconcile CoreRT and CoreCLR globalization code 

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#20715]
```
-method System.Text.Encodings.Tests.EncodingMiscTests.DefaultEncodingBOMTest 
-method System.Text.Encodings.Tests.EncodingMiscTests.NormalizationTest
-method System.Text.Tests.UnicodeEncodingTests.WebName
-method System.Text.Tests.UTF32EncodingTests.WebName
-method System.Text.Tests.UnicodeEncodingDecode.Decode_InvalidBytes  (amd64 only)

```

On quick glance, the Text.Encoding code in CoreRT needs to be synced with that in CoreCLR.

**Comment by tarekgh** [comment]
@AtsushiKan why we need to disable these tests? does the problem in ILC tool chain or in Encoding tests?

@joperezr is this because the failures in the ILC tool chain?

**Comment by AtsushiKan** [comment]
I did not have time to root-cause these. I believe it's the framework code being out of sync with CoreCLR. Most of these are due to locale names not being the same (case-wise) as CoreCLR: failures like these:

      Assert.Equal() Failure
      Expected: utf-16BE
      Actual:   utf-16be

**Comment by joperezr** [comment]
Linking PR where the attributes where added: #20720

**Comment by joperezr** [comment]
> @joperezr is this because the failures in the ILC tool chain?

@tarekgh we are not sure what the source of the problem is yet, but since we are driving to get to a green run, for now all tests that are failing are being disabled and tracked with an issue. We will later do a push to ZBB and we will fix/investigate all of these.

**Comment by danmosemsft** [comment]
There may be significant work here as CoreCLr globalization was cleaned up quite a bit.

**Comment by tarekgh** [comment]
> There may be significant work here as CoreCLr globalization was cleaned up quite a bit.

I didn't look at the corert yet but I am not expecting the change will be big. it looks to me the encoding data just need to uppercased/lowered cased to match coreclr. will confirm that when I get to it.

**Comment by ViktorHofer** [comment]
That's what I noticed a few days ago. E.g. a field in CompareInfo in corert had a name difference to the same field in coreclr. I guess the code should probably be aligned to match each other?
