### ISSUE TITLE
building corefx on linux platform with unknown rid

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#20731]
When trying to build corefx on a Linux host with an unsupported RID, the external/{ilasm,runtime}.depproj fail to compile because they are using the host rid.

These projects are compiled as:
* /p:TargetGroup=netstandard /p:ConfigurationGroup=Debug /p:ArchGroup=x64 /p:OSGroup=AnyOS /p:TargetFramework=netstandard2.0
* /p:TargetGroup=netcoreapp /p:ConfigurationGroup=Debug /p:ArchGroup=x64 /p:OSGroup=Unix /p:TargetFramework=netcoreapp2.0

The following change to external/dir.props makes them compile fine:
```diff
diff --git a/external/dir.props b/external/dir.props
index eb7e7b6..4ec6ee5 100644
--- a/external/dir.props
+++ b/external/dir.props
@@ -5,6 +5,8 @@
     <RuntimeOS Condition="'$(PortableBuild)' == 'true' and '$(OSGroup)' == 'Windows_NT'">win</RuntimeOS>
     <RuntimeOS Condition="'$(PortableBuild)' == 'true' and '$(OSGroup)' == 'OSX'">osx</RuntimeOS>
     <RuntimeOS Condition="'$(PortableBuild)' == 'true' and '$(OSGroup)' == 'Linux'">linux</RuntimeOS>
+    <RuntimeOS Condition="'$(PortableBuild)' == 'true' and '$(OSGroup)' == 'AnyOS'">linux</RuntimeOS>
+    <RuntimeOS Condition="'$(PortableBuild)' == 'true' and '$(OSGroup)' == 'Unix'">linux</RuntimeOS>
     <NugetRuntimeIdentifier>$(RuntimeOS)-$(ArchGroup)</NugetRuntimeIdentifier>
     <ContainsPackageReferences>true</ContainsPackageReferences>
     <!-- We need configuration-specific assets files. -->
```

I'm not sure what the proper change is to make the corefx repo compile on unsupported linux flavors (using portable linux).

**Comment by tmds** [comment]
CC @ellismg

**Comment by weshaggard** [comment]
cc @mellinoe 

While doing some other work I also noticed some inconsistencies here. I think what we want is something like:

(similar to https://github.com/dotnet/corefx/blob/master/pkg/dir.props). 
```
  <PropertyGroup>
    <_runtimeOSVersionIndex>$(RuntimeOS.IndexOfAny(".-0123456789"))</_runtimeOSVersionIndex>
    <_runtimeOSFamily Condition="'$(_runtimeOSVersionIndex)' != '-1'">$(RuntimeOS.SubString(0, $(_runtimeOSVersionIndex)))</_runtimeOSFamily>
  </PropertyGroup>

  <PropertyGroup Condition="'$(PortableBuild)' == 'true'">
    <NugetRuntimeIdentifier>linux-$(ArchGroup)</NugetRuntimeIdentifier>
    <NugetRuntimeIdentifierCondition="'$(_runtimeOSFamily)' == 'osx'">osx-$(ArchGroup)</NugetRuntimeIdentifier>
    <NugetRuntimeIdentifierCondition="'$(_runtimeOSFamily)' == 'win'">win-$(ArchGroup)</NugetRuntimeIdentifier>
  </PropertyGroup>

  <PropertyGroup Condition="'$(PortableBuild)' != 'true'">
    <NugetRuntimeIdentifier>$(RuntimeOS)-$(ArchGroup)</NugetRuntimeIdentifier>
  </PropertyGroup>
```

**Comment by tmds** [comment]
@weshaggard do you know why there is a PortableBuild condition?

**Comment by weshaggard** [comment]
The PortableBuild condition is now the default for our builds but some runtimes like Tizen will set PortableBuild=false and build RID specific package instead of using one of or portable RIDs.

**Comment by tmds** [comment]
I wonder if the condition is needed in the external folder. Do you know? Otherwise I can do a PR and see what platforms complain.

**Comment by weshaggard** [comment]
I do expect it is needed, particularly for the runtime.depproj which restores the runtime we do our tests runs against. If we didn't honor it I would expect the tizen test runs to fail as an example, but feel free to play around with it.

**Comment by tmds** [comment]
I don't think there are any more actions for this in corefx.

I've created an issue in source-build to have a CI build that runs on an unknown RID: https://github.com/dotnet/source-build/issues/297.
