### ISSUE TITLE
Unit test results presentation is unconventional

### ISSUE THREAD

**Issue by willdean** [dotnet/corefx#20733]
![image](https://cloud.githubusercontent.com/assets/1306085/26832554/c7c2878e-4ac7-11e7-89f6-f327ccf8636d.png)

The above is a picture of some test results on one of the various CI flavours that's currently in use on CoreFx.

I will try to remain polite, but this is completely nuts.  

* There is a 'fire' emoji (and "fire" is what the tool tip says) - does this mean it ran and it failed - i.e. "Failed"?
* There is an empty square - no tooltip - who knows - were these skipped?
* And there is an orange checkmark ("skip" says the tooltip) - does this mean "Skipped"?

All I can say is that I am filled with admiration for the vast creativity and freedom of thought which enables someone to come up with a completely new way to present a passed/failed/skipped table without being shackled by the tedious red/green cross/tick conventions that everyone else uses.  But sadly I don't actually find it helpful in understanding the results.

Is "Fire" some kind of MS argot for "Failed", or was it some kind of coded request to an HR department somewhere?

**Comment by stephentoub** [comment]
cc: @Chrisboh, @MattGal

**Comment by Chrisboh** [comment]
@willdean thanks for the feedback around this. We should be more clear around what the Fire means.  

For context Fire means there was a catastrophic failure with the execution of the test dll.  This is unfortunately an issue that is a bit specific to CoreFX as XUnit is using the same framework that is under test.  When this happens you are missing all test coverage that was coming from that test DLL, which is usually coverage for an entire library.  The reason it is different from just a red X is that we wanted to draw more urgency to these issues vs a typical test case failure.

**Comment by willdean** [comment]
@Chrisboh Thanks (and for the magnanimity in the face of my obnoxiousness!)  

Perhaps the easiest improvement would just be to fix the tooltips so that there was some explanation of the various icons.

**Comment by danmosemsft** [comment]
(Including a tooltip for the whiteboxes)

**Comment by Chrisboh** [comment]
Agreed we should be clear on all definitions.  I have added dotnet/core-eng#877 to track this issue.  Are you guys ok to close this out out and track it there?

**Comment by mellinoe** [comment]
That's a private repository; not everyone can see it or follow the discussion there.

**Comment by willdean** [comment]
I'm not fussed that I can't follow it there - happy to have this closed if that suits.

**Comment by ViktorHofer** [comment]
Tooltips are now already implemented. Closing.
