### ISSUE TITLE
Several Xml types use Ref Emit on uapaot which is not supported, which will cause a runtime exception

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#20739]
There are several types in System.Private.Xml today that are using types from System.Reflection.Emit which do not exist in UWP. From a quick scan, these types seem to be:
```
System.Xml.Xsl.IlGen.XmlILModule
System.Xml.Xsl.XmlIlGenerator
```

Once those two classes are correctly fixed to not use Ref Emit(either by throwing PNS or by different implementation) then we should also fix two things in order to better  catch things like this:
 - Modify the ref of ref emit to not have any types in uapaot(or better yet, don't build it at all). The fact that we are building the contract with the types, is what caused this issue since other implementaitions could reference it. And since we have a baseline today in the implementation project of ref emit for uapaot, the build succeeds.
 - System.Private.Xml shouldn't have configurations for both uap, and uapaot, and instead just have the one for uap which SHOULD NOT use ref emit. Today, we have the uap config which does use ref emit and expose some other types like CodeGenerator, XmlSerializationILGen, and XmlSerializationReaderILGen that use ref emit as well, and the uapaot config that only has XmlILModule and XmlILGenerator which uses it incorrectly.

cc: @sepidehMS @krwq @danmosemsft

**Comment by danmosemsft** [comment]
@krwq can you take this if @joperezr isn't already? There is also the question of what XslCompiledTransfor m should do -- throw PNSE, or pass through to XslTransform. For you and @sepidehMS to decide.
