### ISSUE TITLE
System.Diagnostic.Tracing tests need reflection metadata enabled for uapaot

### ISSUE THREAD

**Issue by tijoytom** [dotnet/corefx#20744]
These tests are failing with m$BlockedFromReflection . Need proper rd.xml or workaround

Test_Write_Fuzzy()
Test_Write_T_EventListener()
Test_Write_T_In_Manifest_Serialization()
Test_Write_T_EventListener_UseEvents()

**Comment by brianrob** [comment]
Fixed via #22058.
