### ISSUE TITLE
How to Configure Network Tracing on Linux?

### ISSUE THREAD

**Issue by karthiknadig** [dotnet/corefx#20741]
I want to enable network tracing similar to the tracing described here (https://msdn.microsoft.com/en-us/library/ty48b824.aspx). Is there anything equivalent on linux?

**Comment by karelz** [comment]
@geoffkizer @stephentoub @wfurt @Priya91 any suggestions?

**Comment by CIPop** [comment]
We have this for Windows documented here (ETW): https://github.com/dotnet/corefx/blob/master/Documentation/debugging/windows-instructions.md

You should be able to adapt (and if you have some time document at https://github.com/dotnet/corefx/blob/master/Documentation/debugging/unix-instructions.md) the instructions here on how to collect EventSource in Unix environments:

https://github.com/dotnet/corefx/blob/master/Documentation/debugging/unix-instructions.md

**Comment by wfurt** [comment]
Starting with 2.1, one can use EvenPipe to do tracing on Linux. That is part of coreclr and there is no longer need for lltng. This can be simple as:

```
export COMPlus_EnableEventPipe=1
export COMPlus_EventPipeConfig=*:0xFFFFFFFFFFFFFFFF:5
dotnet myCoolApp.dll
```

This will produce .netperf trace file in CWD -> typically where the application lives. 

To tune tracing a little bit additionan variables can be set. Following example shows tracing from major networking events with some tuning:

```
COMPlus_EventPipeCircularMB=8000
COMPlus_EventPipeConfig=Microsoft-System-Net-Sockets:0xFFFFFFFFFFFFFFFF:5,Microsoft-System-Net-Security:0xFFFFFFFFFFFFFFFF:5,Microsoft-System-Net-Http:0xFFFFFFFFFFFFFFFF:5,Microsoft-System-Net-NameResolution:0xFFFFFFFFFFFFFFFF:5
COMPlus_EventPipeOutputPath=/tmp
```

More information on variables can be found here: https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/clr-configuration-knobs.md

note, that the neperf files can be loaded to PerfView on Windows or they can be processed directly on Linux by functions from Microsoft.Diagnostics.Tracing. 


Starting with 3.0, additional options are available. One can follow instructions from https://devblogs.microsoft.com/dotnet/introducing-diagnostics-improvements-in-net-core-3-0/ and use dotnet directly with additional tools loaded. Current documentation and source for `dotnet-trace`  can be found here: https://github.com/dotnet/diagnostics

**Comment by wfurt** [comment]
Also aside from .Net tracing, following command can be used to trace network related system calls:

```
strace -T -t -f -s 200 -o trace.txt -e trace=network dotnet myApp.dll
```
