### ISSUE TITLE
MemoryMappedFile.CreateViewStream(int, int, MemoryMappedFileAccess.ReadWriteExecute) throws `IOException` in UapAot

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#20751]
If we run the following code in UapAot:
```cs
const int Capacity = 4096;
using (MemoryMappedFile mmf = MemoryMappedFile.CreateNew(null, Capacity, MemoryMappedFileAccess.Read))
{
       var stream = mmf.CreateViewStream(0, Capacity, MemoryMappedFileAccess.ReadWriteExecute);
}
```

`mmf.CreateViewStream(0, Capacity, MemoryMappedFileAccess.ReadWriteExecute);` will throw the following exception:

```
Actual:   typeof(System.IO.IOException): The parameter is incorrect
        Stack Trace:
           D:\repos\corefxCopy\corefx\src\System.IO.MemoryMappedFiles\src\System\IO\MemoryMappedFiles\MemoryMappedView.Windows.cs(46,0): at System.IO.MemoryMappedFiles.MemoryMappedView.CreateView($SafeMemoryMappedFileHandle memMappedFil
  eHandle, $MemoryMappedFileAccess access, Int64 offset, Int64 size)
           D:\repos\corefxCopy\corefx\src\System.IO.MemoryMappedFiles\src\System\IO\MemoryMappedFiles\MemoryMappedFile.cs(464,0): at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewAccessor(Int64 offset, Int64 size, $MemoryMapped
  FileAccess access)
```

Currently we are hitting this in this test: https://github.com/dotnet/corefx/blob/master/src/System.IO.MemoryMappedFiles/tests/MemoryMappedViewStream.Tests.cs#L101-L108

This is supposed to throw an `UnauthorizedAccessException` but only when access is set to `MemoryMappedFileAccess.ReadWriteExecute` we get an `IOException`. 

I debugged this a little bit and it looks like this [call](https://github.com/dotnet/corefx/blob/master/src/System.IO.MemoryMappedFiles/src/System/IO/MemoryMappedFiles/MemoryMappedView.Windows.cs#L41-L42) is getting an invalid `SafeMemoryMappedViewHandle` and the `Win32ErrorCode` is 87.

cc: @ViktorHofer @ianhays @jkotas

**Comment by danmosemsft** [comment]
87 = ERROR_INVALID_PARAMETER

**Comment by jkotas** [comment]
On UWP, this calls MapViewOfFileFromApp that disallows ReadWriteExecute and thus returns different error code for it: https://github.com/dotnet/corefx/blob/b1865ea0847a7a86baefe8378b772ecf0b785681/src/System.IO.MemoryMappedFiles/src/System/IO/MemoryMappedFiles/Interop.Windows.Uap.cs#L44

**Comment by safern** [comment]
So then this is expected behavior? ReadWriteExecute should not be allowed in UWP?

**Comment by ViktorHofer** [comment]
It should work in UAP since this change: https://github.com/dotnet/buildtools/pull/1503

I enabled codeGeneration capability there which is required for *Execute mode in MemoryMappedFile operations.

**Comment by ViktorHofer** [comment]
Code generation
The codeGeneration capability allows apps to access the following functions which provide JIT capabilities to apps.

VirtualProtectFromApp
CreateFileMappingFromApp
OpenFileMappingFromApp
MapViewOfFileFromApp

https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations

**Comment by jkotas** [comment]
codeGeneration capability does not allow you to create ReadWriteExecute  mapping.

The documentation for some of the above APIs has

```
The following constants generate an error:
PAGE_EXECUTE_READWRITE
PAGE_EXECUTE_WRITECOPY
```

This snippet is missing for some, but it is just documentation bug.

**Comment by ViktorHofer** [comment]
@safern If that's true and we need to work around it please see this PR which reverted my changed which handled those cases: https://github.com/dotnet/corefx/pull/19873

@jkotas You are sure about that and it can't be something missing from the Windows team?

**Comment by safern** [comment]
> codeGeneration capability does not allow you to create ReadWriteExecute mapping.

Thanks @jkotas, I was just digging to the Windows code and it is true, it is an expected behavior. 

 > If that's true and we need to work around it please see this PR which handled those cases (I reverted it partially)

I think I would rather split the test to test the right behaviors in all platforms

**Comment by safern** [comment]
Closing as it is an expected behavior.

**Comment by jkotas** [comment]
IMHO, IOException with `The parameter is incorrect` message is not very useful in this case. It may be more appropriate to throw UnauthorizedAccessException.

**Comment by safern** [comment]
> IMHO, IOException with The parameter is incorrect message is not very useful in this case. It may be more appropriate to throw UnauthorizedAccessException.

Agree. Maybe we should talk to the Windows team to get that changed

**Comment by jkotas** [comment]
Shipped already. Not going to change...
