### ISSUE TITLE
Serial port failures

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20764]
Unfortunately it's hard to find the red errors among the forest of yellow skipped. I found some representative ones, not sure whether there should be separate issues:
https://mc.dot.net/#/user/luqunl/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/f991037ff4a2b8628fc027bfdf6dccddb68a9f39/workItem/System.IO.Ports.Tests

@willdean are these all symptoms of somehow not having a port on this box? they're all on the `Windows.81.Amd64.Open-Debug-x64` leg.

https://mc.dot.net/#/user/luqunl/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/f991037ff4a2b8628fc027bfdf6dccddb68a9f39/workItem/System.IO.Ports.Tests/analysis/xunit/System.IO.Ports.Tests.WriteLine_Generic~2FBytesToWrite
```
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Timeout while waiting for data to be written to port (wrote 32770, queued 0, bufSize 0)\r\nExpected: True\r\nActual:   False
Stack Trace :
   at Legacy.Support.TCSupport.WaitForWriteBufferToLoad(SerialPort com, Int32 bufferLength)
   at System.IO.Ports.Tests.WriteLine_Generic.BytesToWrite()
```

https://mc.dot.net/#/user/luqunl/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/f991037ff4a2b8628fc027bfdf6dccddb68a9f39/workItem/System.IO.Ports.Tests/analysis/xunit/System.IO.Ports.Tests.WriteTimeout_Property~2FWriteTimeout_Infinite_Write_str
```
Task should not have completed while tx is blocked by flow-control\r\nExpected: False\r\nActual:   True
Stack Trace :
   at System.IO.Ports.Tests.WriteTimeout_Property.VerifyInfiniteTimeout(WriteMethodDelegate writeMethod, Boolean setInfiniteTimeout)
   at System.IO.Ports.Tests.WriteTimeout_Property.WriteTimeout_Default_Write_char_int_int()
```

https://mc.dot.net/#/user/luqunl/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/f991037ff4a2b8628fc027bfdf6dccddb68a9f39/workItem/System.IO.Ports.Tests/analysis/xunit/System.IO.Ports.Tests.WriteLine_Generic~2FSuccessiveReadTimeout
```
Message :
ERROR!!!: The write method timedout in 0 expected 1054 percentage difference: 1\r\nExpected: True\r\nActual:   False
Stack Trace :
   at System.IO.PortsTests.PortsTest.Fail(String format, Object[] args)
   at System.IO.Ports.Tests.WriteLine_Generic.VerifyTimeout(SerialPort com)
   at System.IO.Ports.Tests.WriteLine_Generic.SuccessiveReadTimeout()
```

**Comment by danmosemsft** [comment]
Same on full build also
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170607.01/workItem/System.IO.Ports.Tests

I've made sure there ar eissues logged in the internal DB to improve the test UI..

**Comment by Jiayili1** [comment]
Following tests failed with:
~~~
Message:
Task should not have completed while tx is blocked by flow-control\r\nExpected: False\r\nActual:   True
Stack Trace:
   at System.IO.Ports.Tests.WriteTimeout_Property.VerifyInfiniteTimeout(WriteMethodDelegate writeMethod, Boolean setInfiniteTimeout)
   at System.IO.Ports.Tests.WriteTimeout_Property.WriteTimeout_Default_WriteLine()
~~~
System.IO.Ports.Tests.WriteTimeout_Property/WriteTimeout_Default_WriteLine
System.IO.Ports.Tests.WriteTimeout_Property/WriteTimeout_Default_Write_byte_int_int
System.IO.Ports.Tests.WriteTimeout_Property/WriteTimeout_Default_Write_char_int_int
System.IO.Ports.Tests.WriteTimeout_Property/WriteTimeout_Default_Write_str
System.IO.Ports.Tests.WriteTimeout_Property/WriteTimeout_Infinite_WriteLine
System.IO.Ports.Tests.WriteTimeout_Property/WriteTimeout_Infinite_Write_byte_int_int
System.IO.Ports.Tests.WriteTimeout_Property/WriteTimeout_Infinite_Write_str

Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170607.01/workItem/System.IO.Ports.Tests/analysis/xunit/System.IO.Ports.Tests.WriteTimeout_Property~2FWriteTimeout_Default_WriteLine

**Comment by Jiayili1** [comment]
Following tests failed with:
System.IO.Ports.Tests.SerialStream_WriteTimeout_Property/WriteTimeout_750_WriteByte
System.IO.Ports.Tests.SerialStream_WriteTimeout_Property/WriteTimeout_750_Write_byte_int_int
System.IO.Ports.Tests.SerialStream_WriteTimeout_Property/WriteTimeout_LargeWrite
~~~
Message:
Err_88558amuph!!!: The write method timedout in 0 expected 750 percentage difference: 1 when called for the first time\r\nExpected: True\r\nActual:   False
Stack Trace:
   at System.IO.Ports.Tests.SerialStream_WriteTimeout_Property.VerifyTimeout(WriteMethodDelegate writeMethod, Stream stream)
   at System.IO.Ports.Tests.SerialStream_WriteTimeout_Property.VerifyTimeout(WriteMethodDelegate writeMethod, Int32 WriteTimeout)
   at System.IO.Ports.Tests.SerialStream_WriteTimeout_Property.WriteTimeout_750_WriteByte()
~~~
Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170607.01/workItem/System.IO.Ports.Tests/analysis/xunit/System.IO.Ports.Tests.SerialStream_WriteTimeout_Property~2FWriteTimeout_750_WriteByte

**Comment by Jiayili1** [comment]
Following tests failed with:
System.IO.Ports.Tests.SerialStream_WriteTimeout_Property/WriteTimeout_Default_WriteByte
System.IO.Ports.Tests.SerialStream_WriteTimeout_Property/WriteTimeout_Default_Write_byte_int_int
System.IO.Ports.Tests.SerialStream_WriteTimeout_Property/WriteTimeout_Infinite_WriteByte
System.IO.Ports.Tests.SerialStream_WriteTimeout_Property/WriteTimeout_Infinite_Write_byte_int_int
System.IO.Ports.Tests.SerialStream_WriteTimeout_Property/WriteTimeout_Int32MaxValue_WriteByte
System.IO.Ports.Tests.SerialStream_WriteTimeout_Property/WriteTimeout_Int32MaxValue_Write_byte_int_int
~~~
Message:
Err_17071ahpa!!! WriteByte terminated with a long timeout of -1ms\r\nExpected: True\r\nActual:   False
Stack Trace:
~~~
   at System.IO.Ports.Tests.SerialStream_WriteTimeout_Property.VerifyLongTimeout(WriteMethodDelegate writeMethod, SerialPort com1)
   at System.IO.Ports.Tests.SerialStream_WriteTimeout_Property.VerifyDefaultTimeout(WriteMethodDelegate writeMethod)
   at System.IO.Ports.Tests.SerialStream_WriteTimeout_Property.WriteTimeout_Default_WriteByte()
~~~
Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170607.01/workItem/System.IO.Ports.Tests/analysis/xunit/System.IO.Ports.Tests.SerialStream_WriteTimeout_Property~2FWriteTimeout_Default_WriteByte

**Comment by Jiayili1** [comment]
This issue is repro on desktop, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/79/testReport/
