### ISSUE TITLE
System.Numerics Matrix4x4  Right-Handed Coordinates Systems?

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20765]
@rochar commented on [Mon Jun 05 2017](https://github.com/dotnet/coreclr/issues/12081)

Hi,

It's supposed to use Matrix4x4 only in Left-Handed Coordinates systems?

Thanks
Ricardo

**Comment by mellinoe** [comment]
Some of the static factory methods on Matrix4x4 assume a right-handed coordinate system. Otherwise, the type can be used from any coordinate system; it makes no difference.

**Comment by rochar** [comment]
Thanks for your reply. Is there any way to distinguish what functions are right / agnostic handed system? 

For example the transform function uses a counter clockwise rotation? And the quaternion implementation?

**Comment by mellinoe** [comment]
Only a select few factory functions assume any handedness, like the ones involving camera and projection matrices.

* `CreateOrthographic`
* `CreateOrthographicOffCenter`
* `CreatePerspective`
* `CreatePerspectiveOffCenter`
* `CreatePerspectiveFieldOfView`
* `CreateLookAt`

These methods will assume you are using a right-handed coordinate system (+x == Right, +y == Up, +z = Towards you). 

If your program uses a different coordinate system convention, then you can use one of the regular constructors on `Matrix4x4`. The rest of the library will behave the same.

Does that help?

**Comment by rochar** [comment]
Yes thank you.

Just another related doubt, for example the Matrix4x4.CreateRotationX will do a counter clockwise rotation? What would be the best practice for this using the System.Numerics? If my system is left handed, I will need a clockwise rotation.
