### ISSUE TITLE
System.Threading.Thread TrySetApartmentState missing uap-aot implementation

### ISSUE THREAD

**Issue by tijoytom** [dotnet/corefx#20766]
These methods need to be implemented.

public ApartmentState GetApartmentState()
public bool TrySetApartmentState(ApartmentState state)
public void DisableComObjectEagerCleanup() 
public void Interrupt()

**Comment by robertmiles3** [comment]
FWIW, I hit a `PlatformNotSupportedException` as soon as I try to use:

```csharp
myProcess.StartInfo.UseShellExecute = true;
```

...because it ends up at `TrySetApartmentState`.

**Comment by stephentoub** [comment]
We no longer run tests on a `uapaot` configuration.
