### ISSUE TITLE
[WS-CLEANUP] Cannot delete workspace: remote file operation failed: /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_debug at hudson.remoting.Channel@2ce3a350:dci-mac-build-083: hudson.remoting.ChannelClosedException: channel is already closed

### ISSUE THREAD

**Issue by v-haren** [dotnet/corefx#20773]
detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_osx_debug/76/consoleFull#10182403706ee26338-6221-4f7c-8c8f-1d1d5cb4704a

**Comment by karelz** [comment]
@danmosemsft @weshaggard @mellinoe any idea where to route it?

**Comment by danmosemsft** [comment]
@mmitche this just seems all broken and the agent shows as broken: https://ci.dot.net/computer/dci-mac-build-083/ ?

**Comment by mmitche** [comment]
@danmosemsft I took the machine offline because it was misbehaving

**Comment by v-haren** [comment]
failed again here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_osx_debug/81/consoleFull#16488519756ee26338-6221-4f7c-8c8f-1d1d5cb4704a
ERROR: [WS-CLEANUP] Cannot delete workspace: remote file operation failed: /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_debug at hudson.remoting.Channel@5c28cefb:dci-mac-build-088: hudson.remoting.ChannelClosedException: channel is already closed
12:45:29 ERROR: Cannot delete workspace: remote file operation failed: /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_debug at hudson.remoting.Channel@5c28cefb:dci-mac-build-088: hudson.remoting.ChannelClosedException: channel is already closed
12:45:29 [xUnit] [INFO] - Starting to record.
12:45:29 [xUnit] [INFO] - Processing xUnit.Net-v2 (default)
12:45:29 ERROR: Step ‘Publish xUnit test result report’ aborted due to exception: 
12:45:29 java.io.IOException: remote file operation failed: /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_debug at hudson.remoting.Channel@5c28cefb:dci-mac-build-088: hudson.remoting.ChannelClosedException: channel is already closed

**Comment by mmitche** [comment]
We think that machine is having issues with its hard disk.  It's been removed.
