### ISSUE TITLE
No test reports found for the metric 'xUnit.Net' with the resolved pattern 'bin/**/testResults.xml'. failed in ci

### ISSUE THREAD

**Issue by v-haren** [dotnet/corefx#20772]
[xUnit] [ERROR] - No test reports found for the metric 'xUnit.Net' with the resolved pattern 'bin/**/testResults.xml'. Configuration error?.

detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_opensuse42.1_debug/71/consoleFull#136046166483554902-aff0-4799-9e92-0ada24ce2a06

**Comment by karelz** [comment]
@weshaggard @mellinoe any idea?
cc @danmosemsft

**Comment by danmosemsft** [comment]
@karelz look higher up the log or go to https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_opensuse42.1_debug/71 and you see it didn't clone the repo. The missing test results are an inevitable consequence.
This coincided with the github outage.

**Comment by v-haren** [comment]
@danmosemsft failed again in several runs, do we need to reopen this bug?
detail: 
https://ci.dot.net/job/dotnet_corefx/job/master/job/debian8.4_debug/2722/consoleFull#136046166483554902-aff0-4799-9e92-0ada24ce2a06
https://ci.dot.net/job/dotnet_corefx/job/master/job/fedora24_release/2737/consoleFull#136046166483554902-aff0-4799-9e92-0ada24ce2a06
https://ci.dot.net/job/dotnet_corefx/job/master/job/opensuse42.1_release/2756/consoleFull#136046166483554902-aff0-4799-9e92-0ada24ce2a06

**Comment by danmosemsft** [comment]
@v-haren thanks for flagging this. I opened https://github.com/dotnet/corefx/issues/20817 for it
