### ISSUE TITLE
building/windows-instructions.md docs need update

### ISSUE THREAD

**Issue by caesar1995** [dotnet/corefx#20788]
https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md

Under Required Software -> For Visual Studio 2017, there is a very important component missing:
we need to have .NET Core cross-platform development checked as well (Workloads -> Other Toolsets)

And there is a issue blocking me for two days, starting from Monday. If I pull from dotnet master, then do "clean.cmd" (or any other commands), it has the error message: "System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". However, if I reverted to a commit in last Friday, then everything is working. 

@davidsh found out that my VS2017 is missing some components, and after adding many things, the error message goes away.

I'm not sure what' the minimum requirements for VS2017 (the ones in windows-instructions.md are not  enough). I attached my configuration. For now, it works for me.
![capture1](https://user-images.githubusercontent.com/8537784/26905630-4538c8ec-4b9d-11e7-9b2c-98c292bb4037.PNG)
![capture2](https://user-images.githubusercontent.com/8537784/26905629-4535ace8-4b9d-11e7-8a16-e5dcb1be977b.PNG)
![capture3](https://user-images.githubusercontent.com/8537784/26905631-453947b8-4b9d-11e7-9376-771cc76dc62a.PNG)
![capture4](https://user-images.githubusercontent.com/8537784/26905632-454a01c0-4b9d-11e7-9ac6-b0759dfa761b.PNG)

**Comment by danmosemsft** [comment]
@caesar1995 would you consider fixing the doc, at least in part?

For the error, I would do "git clean -fdx" and then build from root.

**Comment by caesar1995** [comment]
@danmosemsft I tried to delete my local repo and do a new fork followed by a clone, the problem still existed. After I installed some VS2017 components, the error goes way though. 

I will fix part of the doc to include .NET Core cross-platform development.

**Comment by hughbe** [comment]
I had this exact issue yesterday. Cleaning didn't work, reckoning didn't work. Note that I have the right VS components installed.

The fix is to enable RemoteSigned execution policy in powershell. This seems like a recent build tools regression

**Comment by davidsh** [comment]
>The fix is to enable RemoteSigned execution policy in powershell.

```ps
Set-ExecutionPolicy RemoteSigned
```

**Comment by karelz** [comment]
Is it something that should be captured also in [new contrib docs](https://github.com/dotnet/corefx/wiki/New-contributor-Docs#contributing-guide)?

**Comment by caesar1995** [comment]
@karelz I think so. At least in this document: https://github.com/dotnet/corefx/wiki/Development-environment-setup-for-Windows we need to include .NET Core cross-platform development for 'Workloads' based install. Do you want me to add it?

**Comment by karelz** [comment]
Yes, please. Make the edits. It is wiki - RW for everyone, incl. contributors. We will change the content after-the-fact if we don't like it :)

**Comment by caesar1995** [comment]
The .NET Core cross-platform development has been included in `Workloads based install` in Wiki.

Since there is no other people hitting this issue from June 2017, I will close it.

/cc: @karelz
