### ISSUE TITLE
Implement Environment.GetFolderPath for UWP

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20782]
Windows are not exposing SHGetKnownFolderPath generally in RS3 as it doesn't yet give the correct answers for apps.

Environment.GetFolderPath should do this on UWP:
* For anything that should be app-isolated, use the WinRT Windows.Storage.ApplicationData API
* For anything that should be shared (photos, music, etc.) use SHGetKnownFolderPath, which .NET implementation will have special access to.
* For Documents, use Windows.Storage.ApplicationData.LocalFolder as that's what iOS/Android code expects. (Note: not SHGetKnownFolderPath with CSIDL_PRIVATEDOCUMENTS.) But offer an environment variable tentatively named COMPLUS_PublicDocuments=1 to force this to get hte shared location using SHGetKnownFolderPath and CSIDL_MYDOCUMENTS.

Long term we want SHGetKnownFolderPath but this is the interim plan for RS3.

**Comment by danmosemsft** [comment]
@ptorr-msft could you please confirm this is correct and also what each Environment.SpecialFolder should map to?

**Comment by danmosemsft** [comment]
@JeremyKuhne FYI, please correct me /ask Peter as needed.

**Comment by danmosemsft** [comment]
Still some discussion on this.

**Comment by danmosemsft** [comment]
Discussion of a new Windows API..

**Comment by joperezr** [comment]
@danmosemsft should this be UWP6.0 or UWPafter6.0?

**Comment by danmosemsft** [comment]
This should stay UWP6.0. I'll ping Windows folk for status.

**Comment by danmosemsft** [comment]
Windows are providing a WinRT based API. Tracked by 12392458 internally. Waiting on that.

**Comment by danmosemsft** [comment]
We are unblocked, Jeremy is going to do this.

**Comment by Jiayili1** [comment]
This issue is repro on Core Tests (Master), detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170804.01/workItem/System.Runtime.Extensions.Tests/analysis/xunit/System.Tests.EnvironmentTests~2FGetFolderPath_Windows(folder:%20CDBurning)

**Comment by JeremyKuhne** [comment]
This just went in (#22930).
