### ISSUE TITLE
ADOMD.NET support for .NET Core

### ISSUE THREAD

**Issue by Kevenvz** [dotnet/corefx#20809]
Hey,

I'd like to convert all of my existing applications to .NET Core but found out that there isn't ADOMD.NET support in .NET Core. I need to be able to query my SSAS cubes with impersonation. Is there any plan for you guys to support ADOMD.NET or might there be another way to query SSAS cubes (Using MDX)?

Thanks in advance!

**Comment by karelz** [comment]
What is ADOMD.NET?

**Comment by saurabh500** [comment]
AFAIK Adomd.net ships with SqlServer and not with .Net framework and hence will not ship with core. I recommend you open a connect  Issue for this  request.

**Comment by Karthikvenkat86** [comment]
Is ADOMD.net dll  nuget support available for .net core2.1.0 ? I tried ADOMD nuget which is supporting only framework 4.5.6.  Can you please help.

**Comment by jtmueller** [comment]
@saurabh500 I understand that this is not properly a .NET Core issue, but a SQL Server issue. For those of us who don't know what "open a connect issue" means, it would be helpful to include specific instructions on how to open a SQL Server issue.

**Comment by karelz** [comment]
Looks like UserVoice is the right place for SQL: https://docs.microsoft.com/en-us/collaborate/connect-redirect#sql-server-connect-site-id-68
