### ISSUE TITLE
Question: double division consistency for scaled integer pairs

### ISSUE THREAD

**Issue by YaakovDavis** [dotnet/corefx#20810]
I have the following method:
```c#
void Divide(long x, long y, int factor)
{
   var result1 = (double)x / y;
   var result2 = (double)(x * factor) / (y * factor);
}
```

Are `result1` & `result2` guranteed to be the same for arbitrary (* see bellow) inputs?

The following assumptions can be made:
1. `x`, `y`, & `factor` are positive.
2. `x * factor` & `y * factor` are representable by less than 50 bits.
3. `y >= x`.

**Comment by karelz** [comment]
@mellinoe can you please answer or route?

**Comment by danmosemsft** [comment]
@dcwuser are you interested in me adding you when I see numeric accuracy/precision related issues? if so which particular kinds?

**Comment by mellinoe** [comment]
@YaakovDavis This is a pretty particular question, I'm not sure I'll be able to provide a very good answer. In general, there is nothing here that is specific or particularly relevant to .NET. The answer will come out of the characteristics of 64-bit floating point values, how division is specified, etc. I'm afraid I'd have to study some IEEE specs to come up with an exact answer 😄. C#/.NET isn't doing anything special or unusual here, though; the answer should be the same for other languages.

**Comment by karelz** [comment]
Sounds like the question is answered, closing.

**Comment by YaakovDavis** [comment]
@mellinoe 

Knowing that .Net doesn't affect the result in any way, beyond the IEEE standard, is useful on its own. So thanks.

For anyone interested, [here's](https://www.physicsforums.com/threads/ieee-float-division.916989/) a discussion I opened in another forum.
It seems like consistency *can* be expected in this case.

**Comment by dcwuser** [comment]
Sorry to be late replying; I was out of town. Yes, feel free to forward any regarding numerical or scientific computing issues. This one is a fine example, sorry I missed out on it.


________________________________
