### ISSUE TITLE
Different encoding behavior in windows and linux

### ISSUE THREAD

**Issue by stepandohnal** [dotnet/corefx#20814]
docker linux -> Encoding.UTF8.GetString(new byte[] {195,173})	"Ă­"	string

		windows -> Encoding.UTF8.GetString(new byte[] {195,173})	"í"	string

**Comment by danmosemsft** [comment]
@tarekgh

**Comment by tarekgh** [comment]
I am taking a look

**Comment by tarekgh** [comment]
@stepandohnal I am seeing we are returning the right result on Linux. I mean Linux returning the same results as Windows "í" (hexa value 0x00ED). 

I guess this could be just issue how this character get displayed. could you please tell more how did you see "Ă­"? Also could you please try the following code and let me know the output:


```C#
   string s = Encoding.UTF8.GetString(new byte [] {195, 173});
   foreach (char c in s)
   {
      Console.WriteLine($"{c} -- {(int)c:x}"); 
   }
```

Thanks.

**Comment by stepandohnal** [comment]
![image](https://user-images.githubusercontent.com/5112200/26948711-ac36b806-4c97-11e7-90d9-f2815877146f.png)
![image](https://user-images.githubusercontent.com/5112200/26948782-e4546a26-4c97-11e7-9cf5-9818592d98a1.png)

**Comment by tarekgh** [comment]
This is VS problem and not encoding problem. you may look at https://github.com/dotnet/coreclr/issues/10898 which is same issue and it has a link for the issue reported to VS team. by that I am closing the issue here as this is not really corefx issue.
