### ISSUE TITLE
System.Security.Cryptography.* tests failing in UWP CoreCLR (UAP)

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#20825]
The test assemblies that have failures are the following: 

System.Security.Cryptography.Xml.Tests - 5 failures
System.Security.Cryptography.Pkcs.Tests - 1 failure
System.Security.Cryptography.Csp.Tests - 1 failure

cc: @bartonjs @danmosemsft @ianhays

**Comment by bartonjs** [comment]
@safern Are there logs somewhere?

**Comment by safern** [comment]
@bartonjs I just took a look and this is not related to crypto stuff. There was a change in ResourceManager that cause this tests to fail. So once that is solved this will go away.

**Comment by safern** [comment]
This was fixed with ResourceManager
