### ISSUE TITLE
Enable easy building of all projects for a given library

### ISSUE THREAD

**Issue by kellypleahy** [dotnet/corefx#20827]
I was trying to follow the build instructions here:

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md#building-individual-corefx-dlls

to build the individual projects in corefx (for instance, `System.Collections.Immutable`).  When following those instructions the build fails when the SLN file has `\` instead of `/` for the paths in it.  The build failure is an `MSB4025` for a missing `.metaproj` file.

I suspect many SLN files in the repo have this issue.  I'm not sure what the right fix is - I do know that once I changed it to `/` instead of `\` in the SLN it built successfully on linux.  This might be an msbuild issue or it might be corefx invalid solutions.

Anyway, it would be nice to either update to a msbuild version that fixes this issue or fix the SLN files so that the build/iterate workflow works on linux too.

**Comment by kellypleahy** [comment]
Seems to be related to: https://github.com/Microsoft/msbuild/issues/2022

**Comment by kellypleahy** [comment]
cc: @karelz - sounds like this needs to be fixed in msbuild rather than CoreFX.  For now I will just tweak my SLN files when working on assemblies and just not check those in.

**Comment by mellinoe** [comment]
First, a disclaimer: you probably shouldn't be building the solution files; they are just there so that projects can be opened in Visual Studio with Intellisense, etc. When building from the command line, you should be building individual project files, which are configured properly to be built everywhere.

That said, we can probably work around the MSBuild bug by using forward slashes, assuming that will work on Windows, and with Visual Studio. We already auto-generate the solution files in corefx, so it would be possible for the task to output forward slashes. If you'd like to attempt this, you can find the code here: https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/UpdateVSConfigurations.cs#L245

**Comment by kellypleahy** [comment]
Thanks @mellinoe.  It seems much more convenient to use the SLN files, I think, since you can just to `/t:BuildAndTest` and it automatically rebuilds both the code and the tests.  When building just the `csproj` for the tests it doesn't seem to automatically build the code.

**Comment by kellypleahy** [comment]
I'll also look into the `/` vs. `\` in the generator and make a PR for that if it seems to work on windows / linux.  Thanks for the tip @mellinoe

**Comment by karelz** [comment]
@mellinoe @weshaggard can we somehow fail SLN build to tell "this is not the thing you're looking for"?
cc @wfurt

**Comment by kellypleahy** [comment]
@karelz is there a reason we don't want to allow building the SLN?  It's really convenient to have *something* you can just run a single command line on and get a test run completed.  Of course, if this is too risky due to weirdness with the solutions, can we have another way to have a nice one-liner for quick "recompile and run tests on this assembly I'm working on" sort of workflow?

**Comment by karelz** [comment]
@kellypleahy fair question, it would make sense - @weshaggard @mellinoe can you answer?
If the answer is still "it is difficult", we should make sure contributors don't use it - i.e. fail fast with appropriate error message.

**Comment by mellinoe** [comment]
As long as the solution files are kept in sync (this is still a manual process), and ignoring the path separator issue, there is no technical reason why the solution files shouldn't work, I think. In the past, it has been VERY challenging for us to keep them completely in sync with the rest of our build system, so they very rarely would work 100% of the time. The actual project files, on the other hand, are always guaranteed to work, because we use them for the official and CI builds. Let's see if we can sort out the "path separator" problem and go from there.

**Comment by mellinoe** [comment]
Actually, thinking about it more (from on discussion on gitter), I think there may still be a problem if you try to run tests via the solution file. The solution files are generated in a way that works with Visual Studio, which means they are configured to run Windows tests. You will probably still have that same problem even if you fix the path separator issue. There may be ways to fix that problem as well, though.

**Comment by kellypleahy** [comment]
I ended up settling on a command in my profile like this:
```
bat()
{
  Tools/msbuild.sh src/$1/src/$1.csproj && Tools/msbuild.sh src/$1/tests/$1.Tests.csproj
}
```

that I can just use like `bat System.Collections.Immutable` to build & test the appropriate stuff.

**Comment by weshaggard** [comment]
With current VS tools the most we can do from the commandline is to build the solution file with the default configuration. There isn't any good way to change the configurations or call other targets like BuildAndTest on all the projects in the solution, as they all cannot support that target. I do think it is worth considering some wrapper scripts/commands but it is pretty low priority in my mind.

**Comment by kellypleahy** [comment]
Can I ask a different question?  `./build.sh -tests -project=src/System.IO.FileSystem` (for example) should build and run tests for just `System.IO.FileSystem` at least it seems so from the doc on `build.sh -?`.  However, that doesn't seem to run tests.  Do you agree that it should, and if so, can it be fixed to work on linux too?  It doesn't seem to work at least when I was trying it last.  cc @karelz

**Comment by weshaggard** [comment]
`-project=src/System.IO.FileSystem` is not a project it is a directory which essentially calls build on the sln file in that directory. That will give you the unwanted issues of calling msbuild on the solution as mentioned above.

Currently our root build.sh/cmd scripts don't work well for individual projects, that is something we could add support for however.

**Comment by kellypleahy** [comment]
@weshaggard thanks.  I guess I didn't notice what was really happening under the hood.  What I really wanted was a way to "build/test" the *project* for a single folder (family of projects) meaning the tests & the main project.  I suppose it's not too much trouble to run build.sh twice (once for the tests and once for the main project), but it seems like it would be a pretty common workflow to be working in an isolated project or small group of projects and want to build & run tests for just those to save a bunch of time compiling and running tests.

**Comment by weshaggard** [comment]
@kellypleahy I agree we should definitely make building individual projects easier, including all the projects in for a given library. I re-titled this issue to reflect that and we can use this issue to track doing that. Is this task something you might be interested in trying to tackle?

**Comment by kellypleahy** [comment]
@weshaggard I'm currently working on another PR, but I'll think about this one while I'm doing it and maybe I can help with this one afterwards...

**Comment by weshaggard** [comment]
I was thinking about this a little and I think I have a reasonable way to do this. I will try to put together a PR in the next few days.

**Comment by weshaggard** [comment]
Addressed with https://github.com/dotnet/corefx/pull/21063
