### ISSUE TITLE
API Proposal: Add and Subtract overloads that take a void pointer

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#20845]
## Proposed API
```C#
namespace System.Runtime.CompilerServices
{
    public static partial class Unsafe
    {
        public unsafe static void* Add<T>(void* source, int elementOffset);
        public unsafe static void* Subtract<T>(void* source, int elementOffset);
    }
}
```

## Rationale and Usage
Issue from: https://github.com/dotnet/corefxlab/issues/1529
> S.R.CS.Unsafe should be a good place. It has both `void*` and `ref T` overloads for most methods. `void*` overloads for Add and Subtract are missing for no good reason.

We ended up writing [our own implementation](https://github.com/dotnet/corefxlab/blob/master/src/System.Buffers.Primitives/System/Buffers/OwnedBuffer.cs#L68-L71) because of the need:
```C#
unsafe void* Add(void* pointer, int offset)
{
    return (byte*)pointer + ((ulong)Unsafe.SizeOf<T>() * (ulong)offset);
}
```

The Add API is required in System.Buffers.Primitives [Buffer\<T\>.Pin](https://github.com/dotnet/corefxlab/blob/master/src/System.Buffers.Primitives/System/Buffers/Buffer.cs#L93-L105) method.
```C#
public BufferHandle Pin()
{
    if (_owner != null)
    {
        return _owner.Pin(_index);
    }
    var handle = GCHandle.Alloc(_array, GCHandleType.Pinned);
    unsafe
    {
        var pointer = OwnedBuffer<T>.Add((void*)handle.AddrOfPinnedObject(), _index);
        return new BufferHandle(null, pointer, handle);
    }
}
```
## Open Questions
~- Should the Add/Subtract overload return `ref T` or `void*`?~

## Pull Request

A PR with the proposed changes is available: #20886

## Updates
- Changed return value from `ref T` to `void*`.

cc @jkotas, @KrzysztofCwalina, @karelz, @terrajobst

**Comment by jkotas** [comment]
> Should the Add/Subtract overload return `ref T` or `void*`?

It should return `void*`.

**Comment by omariom** [comment]
Should what can done with the "normal unsafe" go to `Unsafe`?

**Comment by jkotas** [comment]
The example above uses `Unsafe.SizeOf`. It cannot be completely done with the normal unsafe. `Unsafe` has prior art of adding convenience methods that could have be written using other Unsafe methods.

**Comment by karelz** [comment]
API review: Approved

**Comment by ahsonkhan** [comment]
API added in https://github.com/dotnet/corefx/pull/20886
