### ISSUE TITLE
IL and JIT-intrinsic exceptions are different for Vector<T> ctor and CopyTo

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#2084]
Our IL implementation of Vector<T>'s constructor throws an ArgumentNullException if a null array argument is passed in. When JIT intrinsics kick in, a NullReferenceException is thrown. We should clarify which exception type should be thrown and reconcile the differences.

* Vector\<T\>.ctor
* Vector\<T\>.CopyTo
* Vector2/3/4.CopyTo

**Comment by stephentoub** [comment]
Fixed by #2083
