### ISSUE TITLE
Strange bug: KnownColorTable.InitColorNameTable - constant initialization sets all values to null?

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#20865]
Steps to reproduce:

- Start debugging on L188 in System.Drawing.Common.KnownColorTable
![untitled](https://user-images.githubusercontent.com/1275900/26967236-b5f66ec8-4d27-11e7-8600-68be3c5de9b6.png)

- Step over the first assignment to `values[0]`:
![untitled](https://user-images.githubusercontent.com/1275900/26967271-cf753eba-4d27-11e7-83eb-0789a2d7fdab.png)

Observe that values is still null, even though everything has already been assigned...

This is causing a Debug assertion running the unit tests

**Comment by hughbe** [comment]
This is a porting bug that is fixed in #20867

**Comment by stephentoub** [comment]
> This is a porting bug that is fixed in #20867

What's the fix?  None of the commits appear to be specifically about a src fix.  Can you separate out just that fix into its own commit?

**Comment by hughbe** [comment]
It's tricky because the actual fix is to use the version of KnownColorTable in System.Drawing.Common in system.drawing.primitives. This is because the up-to-date version has code that supports system colours. 
There is no real fix that I've actually done so I didn't know how to show it. The fix is the actual code movement. You can see it by copying the contents of KnownColorTable in Drawing.Common to Drawing.Primitives.
