### ISSUE TITLE
Update C# compiler to RTM version

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#20869]
Looks like we're using Roslyn 2.0-rc, which has some bugs - e.g. https://github.com/dotnet/corefx/pull/20813#issuecomment-307258057
We should upgrade to RTM version (maybe even latest).

**Comment by karelz** [comment]
@weshaggard @ericstj @mellinoe can you please advise on the best course of action?

**Comment by weshaggard** [comment]
@chcosta has been the one updating our compilers in the past.

**Comment by chcosta** [comment]
Looks like CLI is on Roslyn beta2

```
<CLI_Roslyn_Version>2.3.0-beta2-61716-09</CLI_Roslyn_Version>
```

I'm starting to look at aligning the compiler we use from BuildTools, with what CLI is using.  Is there anybody looking at moving CLI to Roslyn RTM?

/cc @ellismg

**Comment by karelz** [comment]
What about CoreFX? My understanding was that CoreFX uses old C# compiler.

**Comment by chcosta** [comment]
Yes, CoreFx uses the compiler from BuildTools.  I was intending to align BuildTools with CLI.  If there's a desire to move to RTM compiler, then we should update CLI as well.

**Comment by ellismg** [comment]
> I'm starting to look at aligning the compiler we use from BuildTools, with what CLI is using. Is there any plan to move CLI to Roslyn RTM?

@livarcocc and @jaredpar would know for certain, but I expect that the compiler that is shipped in VS 15.3 would be the same one that is inserted in the final 2.0 CLI.  Note that there is no RTM compiler yet, the version CLI is consuming is what @jaredpar asked me to use when I updated the CLI a few weeks ago.

Personally, I'd like buildtools to just align on what CLI uses (and long term use the CSC from the CLI instead of having BuildTools restore it's own copy).

**Comment by weshaggard** [comment]
>Personally, I'd like buildtools to just align on what CLI uses (and long term use the CSC from the CLI instead of having BuildTools restore it's own copy).

Agreed. So long as we can get away with it and we can move it along fast enough to shim shim features together.

**Comment by weshaggard** [comment]
Moving to 2.1 because it isn't blocking 2.0. We don't appear to have any cases of the out parameter issue based on @chcosta's other issue https://github.com/dotnet/corefx/issues/20942

**Comment by weshaggard** [comment]
We have updated to post 2.0 RTM version of the compiler.
