### ISSUE TITLE
Consider having a way to systematically check styles locally before pushing to PR

### ISSUE THREAD

**Issue by kellypleahy** [dotnet/corefx#20875]
For external contributors (like me) and probably everyone else, it would be nice to have a way to check some of the formatting rules locally before pushing (i.e. as a build target or a script on the cmdline).  I'm running on linux so I don't have VS and don't get the stylecop stuff there.  

If there was a convenient way to run the style check locally I could be a better citizen and not push things that violate style rules (at least not as often) due to not noticing things or not knowing certain rules - and it would probably make the experience nicer for the reviewers as well, so they could focus on content, not formatting.

I'm thinking something like ./stylecop.sh in the root of the repo is the experience I'd be looking for.

Other suggestions that were raised were the following workflow:
1. commit your changes
2. run https://github.com/dotnet/codeformatter
3. revert all changes except those in the code you were working on
4. commit formatting fixes or squash into previous commit

Of course that whole workflow could be done locally.  If this is the sort of workflow we want (I'm fine with that option too), can we make tooling to make it easier as part of the corefx repo?  For instance, if (2) could be told how many commits to review and use `git whatchanged HEAD~k` where `k` is the number you provided to figure out which files were touched, that would be awesome.

If we want to agree on how changes like this might be done, I can happily help with the git-foo as this is one of my specialties ;)

**Comment by tannergooding** [comment]
FYI. @jaredpar

**Comment by sharwell** [comment]
StyleCop Analyzers should support the majority of formatting rules which would be considered "rules" here.

**Comment by mellinoe** [comment]
Semi-related to https://github.com/dotnet/buildtools/issues/1555. We could fold it into a "Make Sure Everything Is Clean" check.

**Comment by tannergooding** [comment]
@sharwell, do StyleCop analyzers work outside of VS/VS Code (i.e. how do you get them to run for command line builds)?

**Comment by sharwell** [comment]
@tannergooding They have no dependency on VS, but they do depend on using Roslyn (1.3+) as the compiler. If you are using C# 7 features, a handful of rules would need to be disabled while we finish updating it.

**Comment by tannergooding** [comment]
Ah, I forget that NuGet analyzers "just work" (I'm used to just using the built-in IDE analyzers lately).

**Comment by kellypleahy** [comment]
OK cool. so is there a nice one-liner for running these locally on the command line on linux within the repo?  I guess that's what I'm asking for (windows too).

**Comment by karelz** [comment]
Let's not forget that coding style should be mainly consistent with current file / component - see second paragraph: https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md
Having a 'checker' for new files, won't hurt. AFAIK we already had code reformatting tool - is that the dotnet/codeformatter?

**Comment by weshaggard** [comment]
I personally think it is better to have a script/cmd to run the formatting tool as opposed to a checker. Who needs a checker when you can just fix it :)

**Comment by sharwell** [comment]
@weshaggard What if the checker *also* can fix it?

**Comment by tannergooding** [comment]
CoreCLR uses the clang-formatter (IIRC) and it generates a patch you can download from the failed job. It's really useful.

**Comment by tannergooding** [comment]
You can also run it locally and pre-apply if you don't want to waste precious Jenkins resources

**Comment by weshaggard** [comment]
>@weshaggard What if the checker also can fix it? 

That is fine as well but I would much prefer we not duplicate rules in multiple locations and in the case of formatting I prefer auto-fixing over giving someone a warning/error about it.

**Comment by kellypleahy** [comment]
Yeah, autofixing was definitely what I was hoping for, but obviously only when appropriate (i.e. for things we've touched).  Either way, there will obviously be some manual intervention, I was just hoping to not spam the reviewers with a bunch of bad formatting nitpicks when unnecessary (and not very valuable).

**Comment by ViktorHofer** [comment]
We should consider adding [dotnet-format](https://www.nuget.org/packages/dotnet-format) as a repo tool when we switched to CLI 3.0.

**Comment by ViktorHofer** [comment]
We enabled analyzers for white-spaces vs tabs and for similar styles (brackets on the right line) recently and other editorconfig settings are covered as well. I believe we can continue enabling analyzers that make sense. I don't see any immediate action here therefore I'm closing this. Feel free to reopen / create a new issue for a specific style that you want to see enforced.
