### ISSUE TITLE
DirectoryInfo/FileInfo don't expand ~ on macOS

### ISSUE THREAD

**Issue by mstaessen** [dotnet/corefx#20880]
Using '~' in paths is not correctly translated.

*Expected*: \~/Downloads translates to FullPath /Users/\<username\>/Downloads
*Actual*: \<current directory\>/\~/Downloads

Not sure if this is intentional and whether there is an API to do so. `Environment.ExpandEnvironmentVariables` does not work either.

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/issues/5016

**Comment by mstaessen** [comment]
Seems reasonable.
