### ISSUE TITLE
Add Environment.UserName() equivalent to dotnet core

### ISSUE THREAD

**Issue by cedroid09** [dotnet/corefx#20899]
Hello,

I've been trying to find a way to get the current session user using dot net core 1.1 in a console project but in vain. Microsoft docs doesn't contain any information about this or it's me missing something. 

Is this possible in dot net core?

**Comment by karelz** [comment]
It is back in 2.0: https://apisof.net/catalog/System.Environment.UserName

**Comment by cedroid09** [comment]
Right thanks.
