### ISSUE TITLE
Publish regular alpha versions of vNext product

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#20911]
Goal: Provide great experience for early adopters to consume our vNext product.

We should have regular (monthly-ish) alpha releases of vNext product. The idea is that every month we would publish last good build of tools, libraries, runtime, etc. that work "well" together. If something go south, we can delist it.

Motivation: Consuming myget daily feed is painful -- too many builds, changing too often. It's sometimes hard to find working combo. It is likely mostly about perception.

What is the right technical solution?
1. Special myget feed with just the alpha monthly-ish bits
2. Regular alpha-previews on nuget
3. Special download of the tools bundle (CLI) on a web site

cc @benaadams @NickCraver 
cc @weshaggard @mellinoe @ericstj

**Comment by wtgodbe** [comment]
@karelz are we still planning on doing this?

**Comment by karelz** [comment]
I would still like to make this investment - something I may ask you in upcomming months ;)

**Comment by ViktorHofer** [comment]
We are already doing this now with the dependency flow system in arcade. From the infrastructure standpoint there is nothing to do here. Closing but feel free to reopen if you disagree.
