### ISSUE TITLE
Not able to install System.Runtime.Serialization.Json and System.Runtime.Serialization.Xml both in a project

### ISSUE THREAD

**Issue by arpit-nagar** [dotnet/corefx#20910]
I have visual studio 17. My project is targeting net461 and netstandard1.6
I want to use System.Runtime.Serialization.Json and System.Runtime.Serialization.Xml. but I am facing issues.

Steps to reproduce:
1. Install nuget System.Runtime.Serialization.Xml - 4.3.0
2. Now install nuget System.Runtime.Serialization.Json - 4.3.0

But when I am trying step 2 it uninstall  System.Runtime.Serialization.Xml .
How to use both nuget in code.

![capture](https://user-images.githubusercontent.com/16220515/27013697-b38d5698-4f06-11e7-8f78-1bde87a1e1d1.JPG)

**Comment by danmosemsft** [comment]
@weshaggard is this a case where we don't support installing these individually?

**Comment by weshaggard** [comment]
@danmosemsft Not that wouldn't be the case here.

@arpit-nagar that certainly doesn't look correct. You say you have a net461 and netstandard1.6 project that do you mean by that? Are you using a new project with TargetFrameworks set to both of those or are they two different projects?

**Comment by shmao** [comment]
@arpit-nagar I'm closing the issue. Please feel free to re-open this if you're still having the issue.
