### ISSUE TITLE
Can `sealed` modifier be removed from `DisplayAttribute`?

### ISSUE THREAD

**Issue by ydogus** [dotnet/corefx#2093]
I'm redirected here from MVC6 repo (https://github.com/aspnet/Mvc/issues/2706).
In MVC6 we are meant to use `DisplayAttribute` to define human readable texts for model's properties. In earlier versions, MVC was using `DisplayNameAttribute` and it could be inherited, so developers were overriding it and customizing texts, messages, labels on the air (like translating or formatting them etc.).

Now MVC6 uses .NET's `DisplayAttribute` for this use and it's sealed and unfortunately we are restricted here now.

Is it possible to remove the `sealed` modifier from this attribute? So I think the frameworks using this attribute will be more customizable.

**Comment by KrzysztofCwalina** [comment]
We seal attributes as it's more efficient to query for sealed attributes. Somebody would need to analyze perf impact of unsealing this one on the main scenarios that use this attribute.

**Comment by KrzysztofCwalina** [comment]
Did not mean to click close.

**Comment by cervengoc** [comment]
Have there been any progress on this issue?

**Comment by steveharter** [comment]
I did not measure the performance side yet. If performance is an issue we may have point-of-use caches added such as ValidationAttribute+ValidationAttributeStore (more invasive code changes, however).

Other reasons for using 'sealed':
- Avoid running malware code (http://alabaxblog.info/2009/07/why-sealed-attributes/)
- To prevent AmbiguousMatchException (AllowMultiple=false) when there is more than one such attribute for a given member (different attribute types but deriving from DisplayAttribute) which is not caught at compile time but will result in run-time exception

Also, DisplayAttribute.ResourceType is designed to support some loosely-coupled scenarios such as the ability to define a public static string property to return the display value.

**Comment by cervengoc** [comment]
- About the vulnerability you are right, although I can't guess how big of a danger it is in real world.
- I think the potential issue of the AmbiguousMatchException is not realted to this case, but in general for such kind of attributes. It should be the responsibility of the developer I think, to avoid it.
- About the loosely-coupled scenarios, I don't understand it completely, a little sample code would be very helpful.

**Comment by cervengoc** [comment]
Also, by removing the `sealed` modifier, it would be needed to make `LocalizedString` public so we can make use of it when extending the attribute with new properties.

**Comment by steveharter** [comment]
The AmbiguousMatchException concern is an edge case which would apply to extensible applications, and to any potential frameworks (aka mvc, asp.net) that need to deal with the fallout of that exception. For example:
```c
using System;
using System.Reflection;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var x = typeof(Bar).GetCustomAttribute<DisplayAttribute>();
        }
    }

    [AttributeUsageAttribute(AttributeTargets.Class, AllowMultiple = false, Inherited = true)]
    public class DisplayAttribute : Attribute
    {
    }

    public class ExtendedDisplayAttribute : DisplayAttribute
    {
    }

    [DisplayAttribute]
    public class Foo
    {
    }

    [ExtendedDisplayAttribute]
    public class Bar : Foo
    {
    }
}
```

For the loosely-coupled case, here's how to call a public static string method (which could then do something fancy):
```c
using System.ComponentModel.DataAnnotations;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            DisplayAttribute attribute = (DisplayAttribute)typeof(MyClass).GetProperties()[0].GetCustomAttributes(typeof(DisplayAttribute), true)[0];
            string name = attribute.GetName(); // returns "Hello"
        }
    }

    public class MyClass
    {
        [DisplayAttribute(Name = "MyNameProperty", ResourceType = typeof(MyResources))]
        public string Name { get; set; }
    }

    public static class MyResources
    {
        public static string MyNameProperty
        {
            get
            {
                return "Hello";
            }
        }
    }
}
```

**Comment by cervengoc** [comment]
I see now thank you for the examples. So if we accept that the sealing will stay at `DisplayAttribute`, what about making `LocalizedString` public, so one can create an *additional* display attribute (like I did before), eg. `DisplayExAttribute`? Then we had a chance to implement the same localization logic as `DisplayAttribute` does.

For me it would be a satisfactory solution in most cases.

**Comment by divega** [comment]
We are not planning to do what the title say but @lajones will try to figure out what it would mean to do what the last comment says and whether we need more information.

**Comment by lajones** [comment]
There are currently 2 internal implementation of the `LocalizableString` class (with the same namespace) – one defined in the `System.Web` assembly and one in `System.ComponentModel.DataAnnotations` assembly. While we could make one of them public it would then clash (compiler warning CS0436) with anything that refers to `LocalizableString` within the other one. So it could be done with a bit of work, but we would then have to update one of the builds to ignore that warning - which feels wrong. Instead, if you need this, I would suggest just replicating the parts of the code from [LocalizableString.cs](https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/LocalizableString.cs) that you need.

**Comment by divega** [comment]
Clearing out milestone so we can discuss this next time we triage.

**Comment by lajones** [comment]
I would imagine this covers #18075 as well.

**Comment by lajones** [comment]
We do not intend to make `LocalizableString` public. We consider it simple enough that if people want to replicate it they can just copy the code.

Re unsealing `DisplayAttribute`. After consideration we are changing our mind on this. We are not planning on working on this but we would consider a PR to do so. When doing so however consider that many usages of this code will be looking for just `DisplayAttribute` and not any descendants of it. So merely unsealing it may not help. There are also multiple usages of `Display` within the DataAnnotations code which will need to be revisited too.

**Comment by ajcvickers** [comment]
Closing this since we do not plan to implement.
