### ISSUE TITLE
Process start tests are not running for UAP

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#20948]
System.Diagnostics.Process.Tests is doing remote invoke to create another process and execute some code remotely. This is not going to work in UAP F5 scenario without some changes. In UAP we are going to handle the remote invoking by activating the runner Appx as background task and not by creating a process. The test need either to be permanently disabled for UAP scenario or has to be re-written for UAP to manually calls process create or do something else.

Talk to me to get more details. 

Note, we didn't enable the remote execution using the background task yet but we are going to enable it soon when upgrading Helix runs to use RS2+ images. remote invoking is currently not working anyway.

**Comment by danmosemsft** [comment]
We are enabling Process.Start in this version, so we will need to test it somehow.

**Comment by tarekgh** [comment]
Right. will need to update the tests to make it work on UAP.

**Comment by tarekgh** [comment]
cc @safern

**Comment by krwq** [comment]
@sepidehMS stealing this bug since you're OOF today

**Comment by krwq** [comment]
Giving it back since I was told you're already working on it
