### ISSUE TITLE
Missing System.Configuration assembly

### ISSUE THREAD

**Issue by darkengines** [dotnet/corefx#20940]
# csproj

```xml
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.NotificationHubs" Version="1.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.0.0-preview1-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="2.0.0-preview1-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="2.0.0-preview1-final" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.4.0-preview1-25305-02" />
  </ItemGroup>

```

# Issue
This line:

`NotificationHubClient = NotificationHubClient.CreateClientFromConnectionString(options.Value.ConnectionString, options.Value.HubPath);`

Throws: 

> System.IO.FileNotFoundException : 'Could not load file or assembly 'System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The file cannot be found.'

Did I miss something?
No build error / warning.

**Comment by ericstj** [comment]
@weshaggard added that recently post preview1.  See https://github.com/dotnet/corefx/commit/e933ffe48451a5549b76d03a3ff6023a08be1cfa.

**Comment by ericstj** [comment]
@darkengines you can try the following:
```
<RuntimeFrameworkVersion>2.0.0-preview2-25407-01</RuntimeFrameworkVersion>
```
And make sure you have https://dotnet.myget.org/F/dotnet-core/api/v3/index.json registered as a feed.

**Comment by darkengines** [comment]
Passed !
Thank you.

**Comment by mellinoe** [comment]
@darkengines Let us know if you hit any other issues.
