### ISSUE TITLE
TCP Socket.Dispose does not abort Connect on Linux in NetStandard2.0

### ISSUE THREAD

**Issue by caleblloyd** [dotnet/corefx#20954]
Consider the following code that implements a timeout on a TCP `Connect` call:

```
	tcpClient = new TcpClient(ipAddress.AddressFamily);
	using (cancellationToken.Register(() => tcpClient?.Client?.Dispose()))
	{
		try
		{
#if NETSTANDARD1_3
			await tcpClient.ConnectAsync(ipAddress, cs.Port).ConfigureAwait(false);
#else
			tcpClient.Connect(ipAddress, cs.Port);
#endif
		}
		catch (ObjectDisposedException ex) when (cancellationToken.IsCancellationRequested)
		{
			throw new MySqlException("Connect Timeout expired.", ex);
		}
	}
```

If this TCP socket connects to an address that does not respond, we expect the socket to get shutdown when the Cancellation Token fires with `cancellationToken.Register(() => tcpClient?.Client?.Dispose())`

- `NETSTANDARD2.0` Linux Ubuntu 14.04 x64: **does not work, times out after ~2 minutes (OS default?)**
- `NETSTANDARD2.0` Linux Ubuntu 17.04 x64: **does not work, times out after ~2 minutes (OS default?)**
- `NETSTANDARD2.0` Windows 10 x64: **works, times out when cancellation token fires**
- `NETSTANDARD1.3` Linux Ubuntu 14.04: **works, times out when cancellation token fires** (calls ConnectAsync though as Connect is not available in NETSTANDARD1.3
- `NET462` Windows 10 x64: **works, times out when cancellation token fires**

Here's our test cases:

- [Failing test case NETSTANDARD2.0 Ubuntu 14.04 x64](https://travis-ci.org/mysql-net/MySqlConnector/builds/240652076#L1033-L1037)
- [Passing test case NETSTANDARD2.0 Windows 10 x64](https://ci.appveyor.com/project/mysqlnet/mysqlconnector/build/1.0.622#L377) (lines 377-413; other tests failed but this Connect test passed)
- [Passing test case NETSTANDARD1.3 Ubuntu 14.04 x64](https://travis-ci.org/mysql-net/MySqlConnector/builds/238541828)
- [Passing test case NET462](https://ci.appveyor.com/project/mysqlnet/mysqlconnector/build/1.0.598)

**Comment by stephentoub** [comment]
I'm not sure there's much we can do about this.  The synchronous Connect method just uses the OS' `connect` function and is subject to the behaviors of that implementation.  On Linux, the behavior of closing a socket file descriptor while being used by `connect` is undefined, and on many systems it won't have the cancellation semantics you're hoping for.  You can see that with a simple C repro:
```C
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/ip.h>
#include <pthread.h>

void* closeConnection(void* connectFdPtr)
{
    printf("sleeping for 3 seconds\n");
    sleep(3);

    printf("closing fd %d\n", *(int*)connectFdPtr);
    close(*(int*)connectFdPtr);
    printf("closed fd\n");

    return NULL;
}

int main(void)
{
    int listenfd = socket(PF_INET, SOCK_STREAM, 0);
    if (listenfd < 0) { perror("socket failed"); return -1; }

    struct sockaddr_in serveraddr = {};
    serveraddr.sin_family = AF_INET;
    serveraddr.sin_addr.s_addr = INADDR_ANY;
    serveraddr.sin_port = 22345;
    int serveraddrlen = sizeof(serveraddr);

    if (bind(listenfd, (struct sockaddr*)&serveraddr, serveraddrlen) < 0) { perror("bind failed"); return -1; }
    if (getsockname(listenfd, (struct sockaddr*)&serveraddr, (socklen_t*)&serveraddrlen) < 0) { perror("getsockname failed"); return -1; }
    if (listen(listenfd, 1) < 0) { perror("listen failed"); return -1; }

    int connectfd = socket(PF_INET, SOCK_STREAM, 0);
    if (connectfd < 0) { perror("socket failed"); return -1; }

    struct sockaddr_in clientaddr = {};
    clientaddr.sin_family = AF_INET;
    clientaddr.sin_addr.s_addr = INADDR_LOOPBACK;
    clientaddr.sin_port = 22345;

    pthread_t closeThread;
    int err = pthread_create(&closeThread, NULL, closeConnection, &connectfd);
    if (err != 0) { printf("pthread_create failed: %d\n", err); return -1; }

    printf("connecting with fd %d...\n", connectfd);
    if (connect(connectfd, (struct sockaddr*)&clientaddr, sizeof(clientaddr)) < 0) { perror("connect failed"); return -1; }
    printf("connected\n");

    return 0;
}
```
Most of the time it hangs until the connect times out.

**Comment by caleblloyd** [comment]
Is there any way to pass receive timeout to the socket in C#? We could detect Linux and set:

`setsockopt (SO_RCVTIMEO)`

**Comment by stephentoub** [comment]
Yes, Socket.ReceiveTimeout:
https://msdn.microsoft.com/en-us/library/system.net.sockets.socket.receivetimeout(v=vs.110).aspx

**Comment by caleblloyd** [comment]
Thanks, we will add this in our library code. Would you like the issue closed or should it stay open for tracking purposes?

**Comment by stephentoub** [comment]
> Would you like the issue closed or should it stay open for tracking purposes?

Thanks, @caleblloyd.  I don't think there's any action to be taken here, so we can close it.
