### ISSUE TITLE
Unable to dogfood corefx

### ISSUE THREAD

**Issue by RFBennet** [dotnet/corefx#20951]
I'm new to .NET and .NET Core, but am eager to test out DirectoryServices in the 2.x daily builds. However, I can't seem to get things to work. I've read through a large variety of docs, and am unable to figure out what's wrong. Are the instructions on this page accurate?

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md

I can get coreclr to build locally, and my (very basic) test console app seems to be using it (I'm using the self-contained option). But I seem to be missing something in order to get corefx to work as well. Can someone perhaps quick check the doc? With an eye for those of us that are new to .NET...

Or maybe give us a hint as to how to verify basic corefx functionality? Maybe a short example .csproj and/or program.cs file or something...?

I'm running VS 2017 Preview (15.3.0 Preview 2.0) on 64-bit Win10.

Thanks!
Looking forward to the upcoming releases of .NET CORE!

**Comment by weshaggard** [comment]
I think the issue you are seeing is that we don't currently build a nuget package for our DirectoryServices library. So to consume that you will need to build corefx and then do a direct binary reference to it from the `bin/runtime/netcoreapp-Windows_NT-Debug-x64` directory.

**Comment by RFBennet** [comment]
I've tried adding the assembly (which looks like it got added just fine when I check the project's "bin" folder), and a range of other ideas. All without success.

I also tried this bit of code:
https://msdn.microsoft.com/en-us/library/87tye19w(v=vs.110).aspx

and for that, and many other attempts, I get this as an error message:
Unhandled Exception: System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'IAds'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{18492074-86BE-36C8-B003-81AE15B1C97E}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).

I can do all sorts of things via PowerShell on the same box, so is DirectoryServices ready for testing? Or am I missing something obvious...?

Thanks for all the hard work everyone is putting into Core 2.x!

**Comment by weshaggard** [comment]
FYI @karelz 

I know @hughbe is working on tests for these libraries, have you hit similar issues @hughbe?

**Comment by karelz** [comment]
> is DirectoryServices ready for testing

Sadly, no. The only thing we know is that it builds. The rest is TBD.

**Comment by pjanotti** [comment]
@weshaggard I hit the error reported by @RFBennet when running tests in my machine (it is a Win10 domain joined box). I will assign this to me (at least temporarily) while I take a deeper look.

**Comment by hughbe** [comment]
Oh nice - I did run into the issue @weshaggard mentioned, but I assumed it was just because I didn't have an active directory server running!

The fix will enable plenty of new tests I think :)
