### ISSUE TITLE
net462 library unable to use project reference to netstandard2 library

### ISSUE THREAD

**Issue by bencyoung** [dotnet/corefx#20974]
I have a netstandard2 library that has an interface that inherits from IReadOnlyDictionary<string, string>

```
    public interface IConfigurationDictionary : IReadOnlyDictionary<string, string>
    {
```

In the same solution I have a new csproj style project that targets net462. This then implements that library:

```
    public class NameValueSettings : IConfigurationDictionary
    {
```

However I get the error:

CS0012	The type 'IReadOnlyDictionary<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.	

I've tried it with both and without the NETStandard.Library in the net462 project and I get the same error. I've also tried adding Microsoft.NETCore.Portable.Compatibility to the net462 project but that also doesn't work. Any idea what I can do? I'd rather not make it an "old style" csproj if possible...

**Comment by bencyoung** [comment]
Hmm, I could make the errors go away by explicitly adding an assembly reference to C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0-preview1-002111-00\netstandard.dll which seems wrong!

**Comment by bencyoung** [comment]
For reference the project file looks like

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\NetStandardProperties.props" />
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NETStandard.Library" Version="2.0.0-preview1-25301-01" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\xyz.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="netstandard">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0-preview1-002111-00\netstandard.dll</HintPath>
    </Reference>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Security" />
  </ItemGroup>
</Project>
```

**Comment by lextm** [comment]
https://www.nuget.org/packages/NETStandard.Library.NETFramework/

You should add a reference to this.

**Comment by bencyoung** [comment]
Ah great thanks. Is that documented anywhere?

**Comment by lextm** [comment]
So far I think the only documentation is the GitHub issues, such as #18246 and its related items.
