### ISSUE TITLE
Method not found - Microsoft.Extensions.Caching.Memory.MemoryCacheOptions.set_CompactOnMemoryPressure(Boolean)

### ISSUE THREAD

**Issue by darkengines** [dotnet/corefx#20981]
# csproj

```xml
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
    <RuntimeFrameworkVersion>2.0.0-preview2-25407-01</RuntimeFrameworkVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RazorLight" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="2.0.0-preview3-25641" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="2.0.0-preview3-25641" />
  </ItemGroup>

```
I have https://dotnet.myget.org/F/dotnet-core/api/v3/index.json registered as a Nuget feed.

# Issue
This line:

`EngineFactory.CreatePhysical(Path.Combine(HostingEnvironment.ContentRootPath, @"Mailing\Templates"))`

(RazorLight template engine creation https://github.com/toddams/RazorLight)
Known issue : https://github.com/toddams/RazorLight/issues/69

Throws: 

> System.MissingMethodException : 'Method not found: 'Void Microsoft.Extensions.Caching.Memory.MemoryCacheOptions.set_CompactOnMemoryPressure(Boolean)'.'

Can you do something from your side?
No build error / warning.

Personal note: I think this is the last issue before we can move on netcoreapp2.0.

**Comment by danmosemsft** [comment]
This seeems to belong in https://github.com/aspnet/Caching did you try there?

**Comment by danmosemsft** [comment]
Please try there...

**Comment by darkengines** [comment]
Ok. Thanks for the advice.
