### ISSUE TITLE
CoreFX is more restrictive parsing if-match header values than the equivalent with the FullCLR.

### ISSUE THREAD

**Issue by dantraMSFT** [dotnet/corefx#20994]
One of our customers, nmbradford, is moving to PowerShell 6 from Windows PowerShell and has hit an incompatibility between CoreFX and FullCLR's handling of if-match header values.  

For example, the following Works on Windows PowerShell:
```
$headers = @{}
$headers.Add("if-match","12345")
Invoke-WebRequest -Uri "http://httpbin.org/headers" -Headers $headers
```

On PowerShell 6 with the CoreFx, the same results in a FormatException thrown by `System.Net.Http.Headers.HttpHeaderParser.ParseValue`.

His expectation is the header value should work on PowerShell/CoreFx as it does with Windows PowerShell/FullCLR.  Instead, he needs to special case this header for it to work.

See https://github.com/PowerShell/PowerShell/issues/2895 for the related PowerShell issue.

**Comment by danmosemsft** [comment]
@dantraMSFT thanks for the report. Is this using .NET Core 2.0 preview 1 or an earlier version, or ..?

**Comment by dantraMSFT** [comment]
@danmosemsft: I can repro this with 2.0.0-preview2-006388.

**Comment by Priya91** [comment]
@dantraMSFT Please provide a short repro with .NET Core APIs.

**Comment by dantraMSFT** [comment]
Here's a repro (in Powershell-speak.)
$uri = [Uri]::new("http://httpbin.org/headers")
$method = [System.Net.Http.HttpMethod]::Get
$request = [System.Net.Http.HttpRequestMessage]::new($method, $uri)
$request.Headers.Add("if-match", "12345")

**Comment by karelz** [comment]
@dantraMSFT we are not very familiar with PS specifics. Can you please provide the repro in C#? It also helps to remove any potential hidden PS dependencies/specifics from the discussion. Thanks!

**Comment by dantraMSFT** [comment]
using System;
using System.Net;
using System.Net.Http;

namespace Header20994
{
    class Program
    {
        static void Main(string[] args)
        {
            Uri uri = new Uri("http://httpbin.org/headers");
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, uri);
            // throws System.FormatException: The format of value '12345' is invalid.
            request.Headers.Add("If-Match","12345");
        }
    }
}

**Comment by JonHanna** [comment]
`12345` is indeed an invalid e-tag. Did the server 304 for it with the version that allowed it?

If not then it was doing no good anyway, so there's less value in being bug-compatible.

**Comment by dantraMSFT** [comment]
@nmbradford Can you answer Jon's question?

**Comment by JonHanna** [comment]
(Not to say that being bug-compatible is definitely not a good idea anyway, but it's more strongly justified in that case, and more strongly again if the server didn't work when given a valid e-tag like) `Headers.Add("If-Match","\"12345\"")`)

**Comment by nmbradford** [comment]
apologies for delay responding - been afk for a few weeks.  See https://github.com/PowerShell/PowerShell/issues/2895 for the original issue that ack's the fact that the etag header is invalid, but the server implementation does accept it (and worse, requires it!).  Understand the argument for not being bug compatible, just wanted people more savvy than I to adjudicate on it :)

**Comment by JonHanna** [comment]
It's far from me to make such a call, but I do think the server requiring the invalid behaviour is a strong point in favour of allowing it.

**Comment by davidsh** [comment]
You can also use .TryAddWithoutValidation() which should work on both .NET Framework and .NET Core.

```c#
Uri uri = new Uri("http://httpbin.org/headers");
HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, uri);
request.Headers.TryAddWithoutValidation("If-Match","12345");
```

**Comment by karelz** [comment]
Seems to be answered by last reply from @davidsh. In general we are not trying to be fully bug-by-bug compatible. If the impact on customers is non-trivial, we can reconsider it case by case.

Closing.
