### ISSUE TITLE
Helix-based CI runs are not flagging test failures

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#20997]
Example: https://ci3.dot.net/job/dotnet_corefx/job/master/job/portable-windows-Config_Debug+OuterLoop_false_prtest/773/

This job is labeled a success, but there are many test failures if you look deeper into the results.

@MattGal @karajas @weshaggard

**Comment by MattGal** [comment]
@mellinoe  I see there's a bug here that @mmitche's code doesn't make sure that all Work items execute successfully  (one of the work items failed in each run, will check that out) but I don't see any Xunit failures, can you clarify?

Runs:
https://helix.dot.net/api/2017-04-14/aggregate/jobs?groupBy=job.name&maxResultSets=1&filter.name=e73c84e2-b906-482f-aed2-61f82252ff04
https://helix.dot.net/api/2017-04-14/aggregate/jobs?groupBy=job.name&maxResultSets=1&filter.name=724fbd35-db7a-483c-bf37-5e7efbb54a1a
https://helix.dot.net/api/2017-04-14/aggregate/jobs?groupBy=job.name&maxResultSets=1&filter.name=07ab8282-7c5a-44ed-bed9-f447f53986e6
https://helix.dot.net/api/2017-04-14/aggregate/jobs?groupBy=job.name&maxResultSets=1&filter.name=ca3f5be9-c3ee-4c9e-9ceb-e5b9f48640f1

**Comment by karajas** [comment]
This should be resolved now.
