### ISSUE TITLE
[UWP] DummyTcpServer not working in TLS/SSL in System.Net.Security tests

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#21008]
I noticed that this test in System.Net.Security, TransportContextTest.cs, hangs at the `AuthenticateAsClientAsync` call but only in UAP test run and not UAPAOT test run.

```c#
        [Fact]
        public async Task TransportContext_ConnectToServerWithSsl_GetExpectedChannelBindings()
        {
            using (var testServer = new DummyTcpServer(
                new IPEndPoint(IPAddress.Loopback, 0), EncryptionPolicy.RequireEncryption))
            using (var client = new TcpClient())
            {
                await client.ConnectAsync(testServer.RemoteEndPoint.Address, testServer.RemoteEndPoint.Port);

                using (var sslStream = new SslStream(client.GetStream(), false, AllowAnyServerCertificate, null, EncryptionPolicy.RequireEncryption))
                {
                    await sslStream.AuthenticateAsClientAsync("localhost", null, SslProtocols.Tls, false); // HANGS

                    TransportContext context = sslStream.TransportContext;
                    CheckTransportContext(context);
                }
            }
        }
```
If I don't use the DummyTcpServer but instead just connect to "corefx-net.cloudapp.net:443" then it works fine. So I think the problem is specific to using a loopback TLS/SSL server within the UAP tests which use app-container.

This is currently blocking a lot of tests in System.Net.Security for UAP test runs.

**Comment by davidsh** [comment]
cc: @safern @CIPop @caesar1995

**Comment by CIPop** [comment]
@davidsh I didn't see this on when running all tests after my changes in #21283,.
If this happens again after these changes please capture a full-memory dump using procdump during the deadlock and reopen this issue.

> only in UAP test run

Sounds related to #18760 - the UAP run is the only one running in an AppContext.
