### ISSUE TITLE
Add TypeInfo.IsEquivalent(TypeInfo) to CoreFx

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#2101]
It is currently not possible to write a library that compares types correctly (considering NoPIA interface unification) and that works on both Desktop CLR and CoreCLR without calling Type.IsEquivalentTo via Reflection on Desktop.

**Comment by tmat** [comment]
Update Roslyn when fixed (search for bug number)

**Comment by pallavit** [comment]
@terrajobst Can we please add this to the API review agenda.

**Comment by pallavit** [comment]
This is exposed via #5029
