### ISSUE TITLE
Consider adding StringBuilder.AppendEncoded(Encoding encoding, byte* bytes, int byteCount)

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#2102]
In general Encoding APIs don't compose well with other fundamental APIs without allocating temporary blobs/strings in between.

**Comment by KrzysztofCwalina** [comment]
What's the scenario for efficiently creating UTF16 string from UTF8 data? i.e. I can see how this method would be useful if StringBuilder allowed to built UTF8 strings. But it does not.

**Comment by tmat** [comment]
In Portable PDB format the document name is encoded as a sequence of separated parts, each part is stored as UTF8 encoded blob. When the full name is asked for thru API that returns a string the reader needs builds it from the parts like so:

```C#
            StringBuilder builder = s_pool.Allocate();
            while (blobReader.RemainingBytes > 0)
            {
                if (separator != 0 && builder.Length > 0)
                {
                    builder.Append((char)separator);
                }

                var partReader = GetBlobReader(blobReader.ReadBlobHandle());

                // TODO: avoid allocating temp string
                builder.Append(partReader.ReadUTF8(partReader.Length));
            }

            var result = builder.ToString();
```

ReadUTF8 essentially calls Encoding.UTF8.GetString(byte*, int).

**Comment by KrzysztofCwalina** [comment]
Why would the implementation not use Encoding.GetChars(Byte[], Int32, Int32, Char[], Int32) to convert the blob to char[] and then StringBuilder.Append(char[]) to append the char array to the builder?

**Comment by tmat** [comment]
@KrzysztofCwalina Using a pooled char[] buffer? That would work but it's getting complicated. Wouldn't I need to handle the case when the buffer is not big enough and convert it in chunks?

**Comment by KrzysztofCwalina** [comment]
BTW, I am not sure if it's the right approach; just exploring for now if we cannot accomplish what you want without complicating StringBuilder.

Going back to the main discussion, maybe even better approach would be to try to stack allocate a char[] buffer and call the char*/byte* overloads. So no pooling would be required. Thoughts?

**Comment by tmat** [comment]
@KrzysztofCwalina Yeah, if I wanted to optimize away the pooling I could stack-allocate. But I'd prefer the code to be a single line, not 20 lines. I could indeed extract it to a helper method. However, I don't think basic operations like these should require such an effort to avoid allocations. If the framework doesn't provide basic building blocks for allocation free operations then it's gonna be hard to write efficient "system" level code.

To minimize cluttering the public API perhaps Append(byte*, int, Encoding) would be a better option than AppendEncoded.

**Comment by KrzysztofCwalina** [comment]
Ah, I totally understand that we don't want everybody to write these complex 20 lines of code (especially that they are unsafe). I think it would be reasonable to add such helper routine somewhere. 
What I would prefer not to do is add a dependency from StringBuilder to Encodings.

**Comment by tmat** [comment]
@KrzysztofCwalina An extension method in System.Text would work.

**Comment by KrzysztofCwalina** [comment]
Yeah, that seems like a fine idea. Would you like to prototype it and take it through the API review process?

**Comment by tmat** [comment]
Perhaps at some point. I have too many items on my plate currently.

**Comment by mattwarren** [comment]
@tmat @KrzysztofCwalina 

I produced a benchmark that shows the perf difference between the 2 approaches you discussed above (if I understood them correctly). It also shows the difference in the amount of GC collections, here are the results:

``` ini
BenchmarkDotNet-Dev=v0.7.8.0+
OS=Microsoft Windows NT 6.1.7601 Service Pack 1
Processor=Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz, ProcessorCount=8
HostCLR=MS.NET 4.0.30319.42000, Arch=64-bit  [RyuJIT]
Type=StringBuilderEfficientAppend  Mode=Throughput  Platform=HostPlatform  Jit=HostJit  .NET=HostFramework  toolchain=Classic  Runtime=Clr  Warmup=5  Target=10  

                                                                    | GC Collections per 1 million ops  |
    Method | StringLength |     AvrTime |    StdDev |          op/s |      Gen0 |      Gen1 |      Gen2 |
---------- |------------- |------------ |---------- |-------------- |-----------|-----------|-----------|
  Original |            1 |  42.4204 ns | 0.2792 ns | 23,573,547.49 |     10.17 |      0.00 |      0.00 |
  Improved |            1 |  34.2644 ns | 0.5882 ns | 29,185,409.98 |      0.00 |      0.00 |      0.00 |
  Original |            5 |  51.4178 ns | 0.5020 ns | 19,448,520.71 |     12.70 |      0.00 |      0.00 |
  Improved |            5 |  40.5619 ns | 0.4539 ns | 24,653,698.63 |      0.00 |      0.00 |      0.00 |
  Original |           10 |  65.3267 ns | 4.1725 ns | 15,307,753.00 |     15.25 |      0.00 |      0.00 |
  Improved |           10 |  53.0060 ns | 0.7845 ns | 18,865,819.59 |      0.00 |      0.00 |      0.00 |
  Original |           20 |  72.5353 ns | 3.3984 ns | 13,787,096.28 |     22.86 |      0.00 |      0.00 |
  Improved |           20 |  57.9108 ns | 0.6775 ns | 17,267,957.76 |      0.00 |      0.00 |      0.00 |
  Original |           50 | 239.1619 ns | 4.2924 ns |  4,181,363.40 |     40.61 |      0.00 |      0.00 |
  Improved |           50 | 222.7882 ns | 4.3712 ns |  4,488,568.45 |      0.00 |      0.00 |      0.00 |
```

For reference, my benchmark methods look like this (see [this gist](https://gist.github.com/mattwarren/ac96e434e81be338883a) for the full benchmark):

``` csharp
[Benchmark]
public void Original()
{
	// Slow way, requires an extra allocation of the temporary string
	var tempString = encoding.GetString(bytes, UTF8Bytes.Length); // This overload is in .NET 4.6 only
	builder.Append(tempString);
}

[Benchmark]
public void Improved()
{
	// Quick way, using the magic of "stackalloc"
	encoding.AllocFreeAppend(bytes, UTF8Bytes.Length, builder);
}
```

and the `AllocFreeAppend(..) extension method looks like this:

``` csharp
public static class EncodingExtensions
{
	public static unsafe StringBuilder AllocFreeAppend(this Encoding encoding, byte* bytes, int byteCount, StringBuilder builder)
	{
		var charCount = encoding.GetCharCount(bytes, byteCount);
		char* chars = stackalloc char[charCount];
		var charsWritten = encoding.GetChars(bytes, byteCount, chars, charCount);
		builder.Append(chars, charsWritten);
		return builder;
	}
}
```

I know that I need to add validation to `AllocFreeAppend` and create tests for it, but are you happy for me to take it through the API review process? Is it still "up for grabs"?

**Comment by mattwarren** [comment]
@KrzysztofCwalina is this issue still active?

**Comment by KrzysztofCwalina** [comment]
@mattwarren, sorry I have been super busy in the last couple of days. I will try to take a look later today.

**Comment by mattwarren** [comment]
That's fine, no rush. I just wanted to check if this issue was still being
watched

**Comment by KrzysztofCwalina** [comment]
Is there a reason its an extension on Encoding and not on String Builder?

**Comment by mattwarren** [comment]
I did it that was as that's what the [comment above](https://github.com/dotnet/corefx/issues/2102#issuecomment-114295419) seemed to be suggesting:

> @KrzysztofCwalina An extension method in System.Text.Encoding would work.

But maybe I mis-understood, I can change it if you want?

**Comment by KrzysztofCwalina** [comment]
Oops, sorry. I misspoke/mistyped. I meant extension to StringBuilder.

Anyway, before I can formally take it to an API review, we would need to decide on the strawman namespace, and type for this extensions. Also, the implementation needs to be smarted about the stackallock. If charCount is large, the code should either borrow from a pool or heap alloc the buffer.

**Comment by mattwarren** [comment]
> Also, the implementation needs to be smarted about the stackallock. If charCount is large, the code should either borrow from a pool or heap alloc the buffer.

If it was to borrow from a pool, does that mean that we would have to wait until https://github.com/dotnet/corefx/issues/4547 (or similar) was implemented to do this?

**Comment by KrzysztofCwalina** [comment]
Yes, but I just talked to @sokket who is working on the pool and it should be in corefx and on nuget very soon.

**Comment by sokket** [comment]
I'm finishing up the code now and should have the PR for the pool out tomorrow

**Comment by mattwarren** [comment]
Ah that's good to know, thanks

> If charCount is large, ...

Is there any guidance for what a large value of charCount is? Are there any
tests I can run to figure it out?

**Comment by KrzysztofCwalina** [comment]
@axelheer was doing some stack allocs in BigInteger and did some digging into the right thresholds for stack alloc. Axel, do you remember what what was the consensus there?

**Comment by axelheer** [comment]
Yeah, but I don't know if this applies here. Since we needed temporary memory for CPU bound work, we finally decided on the basis of "ordinary" benchmarks (multi threaded + server gc / single threaded + workstation gc).

A general observation was that we can assume a 1 MB stack and 256 stack frames, which leads to a 4k stack alloc to be "valid" per stack frame. You can look into #2291 for the dirty details, but its for CPU bound work as I already said. For encoding stuff it should be viable as well to chunk the stuff and I cannot help finding a good choice here.

**Comment by KrzysztofCwalina** [comment]
I think using a buffer from the pool might be the best option.

**Comment by sokket** [comment]
The BufferPool PR has been merged, so it should be ready to consume tomorrow when the MyGet packages have been generated

**Comment by mattwarren** [comment]
@sokket thanks for the heads-up, I'll take a look at using the BufferPool in this issue

**Comment by karelz** [comment]
We need formal API proposal -- if it is in the discussion, please distill it out and update the original post.

**Comment by GrabYourPitchforks** [comment]
This issue hasn't been touched in 4 years and there is no actionable API proposal. Closing the issue. If you feel that this issue has been closed in error please reopen with a reviewable API proposal.
