### ISSUE TITLE
System.Security.AccessControl should not need a UAP configuration

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#21023]
After pending PR this will no longer be in UAP package, so this configuration is harmless, still need to remove UAP configuration and add this to project
```
<!-- Although we have a netstandard configuration, we know we are not currently UAP compatible-->
    <UWPCompatible>false</UWPCompatible>
```
then remove the pinvoke baseline for that library. 

Essentially: https://github.com/dotnet/corefx/compare/master...danmosemsft:cleanup.accesscontrol?expand=1

**Comment by karelz** [comment]
@danmosemsft should it be up-for-grabs?
