### ISSUE TITLE
Change UWP calls to CreateFile etc to use brokered API (eg CreateFile2)

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#21025]
These libraries need to change to CreateFile2 in their UAP configurations, and delete their pinvoke baseline file.

System.IO.Pipes
System.IO.Ports
System.IO.FileSystem.Watcher
~~System.Diagnostics.FileVersionInfo~~

**Comment by JeremyKuhne** [comment]
Should be `CreateFile2`, not `CreateFileFromApp`

**Comment by danmosemsft** [comment]
@pjanotti tracking issue. System.Diagnostics.FileVersionInfo was listed above, but I don't know why. Of course , we should re scan everything. We should have zero pinvoke baseline files for UAP now, and no generic ones either (the ones with no target group suffix) as those would be used for UAP builds.

**Comment by pjanotti** [comment]
@danmosemsft closing this one now, let me know if there is still something missing.
