### ISSUE TITLE
Change MMF to use FromApp API's

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#21026]
Change System.IO.MemoryMappedFiles to have a uap configuration that uses the FromApp versions of these API's then delete the pinvoke baseline file there.
```
kernel32.dll!CreateFileMappingW
kernel32.dll!MapViewOfFile
kernel32.dll!OpenFileMappingW
kernel32.dll!VirtualAlloc
```

**Comment by danmosemsft** [comment]
@joperezr fyi

**Comment by JeremyKuhne** [comment]
This was sort of obfuscated, but it is already done: https://github.com/dotnet/corefx/commit/68949506e38203500c768fd2debbff73c0304b26

**Comment by danmosemsft** [comment]
@JeremyKuhne aha, yes, it was just still including them in the project file. Fixing in my pr.
