### ISSUE TITLE
Remove UWP (ILC & F5) and Desktop test runs on release/2.0.0 corefx runs

### ISSUE THREAD

**Issue by Chrisboh** [dotnet/corefx#21022]
@MattGal commented on [Thu Jun 08 2017](https://github.com/dotnet/core-eng/issues/904)

Per @danmosemsft we don't actually use or pay attention to test results coming from the release/2.0.0 corefx branch.   Disabling these runs, especially the ILC ones, will save huge amounts of time in test execution.

This should just be a quick PR to the build pipelines folder but will require a ship room email as it's a PR to a release branch.

**Comment by danmosemsft** [comment]
@Chrisboh is this something @MattGal is planning to do like for 1.0?

**Comment by danmosemsft** [comment]
From talking to @Chrisboh , Matt is not booked to do this. I'm going to resolve this.
