### ISSUE TITLE
TransactionScope does not rollback changes after exception

### ISSUE THREAD

**Issue by dopare** [dotnet/corefx#21030]
I was testing `TransactionScope` in .NET Core 2.0 console app and find out that it does not rollback changes even if there is an exception.

My test [application](https://github.com/dopare/SqlClientTest/blob/master/SqlClientTest/Program.cs) for repro.

Part of source code using `TransactionScope`

```C#
static void InsertUsingTransactionScope()
{
    try
    {
        using (var tr = new TransactionScope())
        using (var conn = new SqlConnection(ConnectionString))
        {
            conn.Open();
            // conn.EnlistTransaction(Transaction.Current); // System.NotSupportedException: Specified method is not supported.
            for (int i = 0; i < 3; i++)
            {
                var command = new SqlCommand("INSERT INTO Records VALUES(@name)", conn);
                command.Parameters.Add(new SqlParameter("@name", "Inserted by transaction scope #" + i));
                var result = command.ExecuteNonQuery();
                if (i == 1)
                    throw new Exception("InsertUsingTransactionScope");
            }
            tr.Complete();
        }
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex);
    }
}
```

Console Output:
```
System.Exception: InsertUsingBeginTransaction
   at SqlClientTest.Program.InsertUsingBeginTransaction() in C:\Users\Dopare\Source\Repos\SqlClientTest\Program.cs:line 51
System.Exception: InsertUsingTransactionScope
   at SqlClientTest.Program.InsertUsingTransactionScope() in C:\Users\Dopare\Source\Repos\SqlClientTest\Program.cs:line 84

====== Records ======
Id: 3 Name: Inserted by transaction scope #0
Id: 4 Name: Inserted by transaction scope #1
```

**Comment by saurabh500** [comment]
@dopare are you using Preview1 bits of SqlClient? 
Transactions nested in Transaction Scope is not supported in SqlClient. 
We changed Sqlclient so that an exception is thrown when an attempt to enroll a connectoin into System.Transaction.

**Comment by dopare** [comment]
What is currently supported with `TransactionScope` ?

**Comment by saurabh500** [comment]
Right now nothing is supported in TrabsactionScope. We are looking at releasing support post 2.0. the engineering effort is underway

**Comment by dopare** [comment]
So `TransactionScope` is in .NET Core for just compiling, isn't it ?

**Comment by geleems** [comment]
@dopare `TrabsactionScope` is supported in 2.1 preview. Please use it for your scenario.
