### ISSUE TITLE
Please provide ref indexer for collection builder types

### ISSUE THREAD

**Issue by alrz** [dotnet/corefx#21052]
For example `ImmutableArray<T>.Builder`. 

Note: https://github.com/dotnet/csharplang/issues/476 could make this a lot cleaner.

Also related: https://github.com/dotnet/csharplang/issues/461

**Comment by safern** [comment]
@alrz could you please add a formal API Proposal? 

Here are the guidelines on how to do it: https://github.com/dotnet/corefx/issues/22345#issue-243552910

**Comment by alrz** [comment]
I'll wait for dotnet/csharplang#461 to land. I think that is the main consumer of this API.

**Comment by benaadams** [comment]
Resolved by https://github.com/dotnet/corefx/pull/25738?

**Comment by alrz** [comment]
Yes, thanks
