### ISSUE TITLE
Not all overrided methods of expression visitor are called

### ISSUE THREAD

**Issue by neil-119** [dotnet/corefx#2105]
VisitBinary etc in ExpressionVisitor is never called in DNX Core 5 (works fine in DNX 4.5.1). This limits our ability to create custom LINQ providers targeting .NET Core.

**Comment by neil-119** [comment]
I re-tried this with the latest dev branch. The methods are called now, but the overridden `ToString()` is not called. I think it's calling `System.Object.ToString()` instead of the overridden function, returning `System.Linq.Enumerable+WhereEnumerableIterator'1[[TestApp.Program+Customer]]` instead.

**Comment by svick** [comment]
What makes you think [`WhereEnumerableIterator`](https://github.com/dotnet/corefx/blob/baed3e72c74ed9e0004bbec7a4c6ec3939192074/src/System.Linq/src/System/Linq/Enumerable.cs#L168) overrides `ToString()`? Or maybe I'm misunderstanding, but that's what you seem to be calling `ToString()` on.

**Comment by neil-119** [comment]
My bad, not sure what I was thinking; I should have created a new issue. This issue is fixed. Thanks!
