### ISSUE TITLE
Change S.Threading.Overlapped tests that test on OS-invalid handles to use SafeHandle-invalid handles instead

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#21066]
The tests: `BindHandle_ClosedSyncHandleAsHandle_ThrowsArgumentException` and `BindHandle_ClosedAsyncHandleAsHandle_ThrowsArgumentException` are failing in uap because it looks like they are expecting that `handle.CloseWithoutDisposing` should mark the property `handle.isClosed` to true, and it doesn't. Tests look more or less like:
```c#
....
            handle.CloseWithoutDisposing();

            AssertExtensions.Throws<ArgumentException>("handle", () =>
            {
                ThreadPoolBoundHandle.BindHandle(handle);
            });
...
```
Inside, BinHandle method, we do a check and throw ArgumentException if handle is closed, but that is not getting set when calling `CloseWithoutDisposing`.

This issue is to track the work of fixing those tests and re enabling them. cc: @kouvel @stephentoub

**Comment by danmosemsft** [comment]
This is failing even after fixing it to write to a valid path?

**Comment by joperezr** [comment]
Yes. I haven't checked yet why does this work in netcoreapp, but I believe this might be a bug in the test, not product code.

**Comment by kouvel** [comment]
It looks like that's what the test is trying to test, if a closed handle is passed in a valid SafeHandle, it should still fail. ThreadPoolBoundHandle catches all exceptions from the call to ThreadPool.BindHandle and uses the HResult to translate two of them from ApplicationException to ArgumentException, one of which is E_HANDLE. But on uap we're getting SEHException, which uses the HResult E_FAIL, so that is not getting translated to the expected ArgumentException.

Not sure yet where the unhandled exception is occurring.

**Comment by kouvel** [comment]
Ah the handle is being closed twice, the exception is occurring at the close of the using block. According to CloseHandle:
> If the application is running under a debugger, the function will throw an exception if it receives either a handle value that is not valid or a pseudo-handle value. This can happen if you close a handle twice, or ...

I guess we get that behavior when running in an app as well. I'll fix the test.

**Comment by kouvel** [comment]
The call to CreateIoCompletionPort with an already closed handle is resulting in an SEH exception instead of a return value indicating failure.

**Comment by kouvel** [comment]
Looks like an issue in Windows. These tests will need to remain disabled for the time being, moving to future.

**Comment by joperezr** [comment]
@kouvel did you figure out how come they work on netcoreapp if this is a Windows issue?

**Comment by kouvel** [comment]
The only difference is that for uap it's run inside an AppContainer, that may be the difference

**Comment by kouvel** [comment]
It looks like inside an AppContainer, some Windows APIs issue an SEH exception when closed handles are passed in. Will determine what to do about this after UWP6.0.

**Comment by joperezr** [comment]
sounds good, thanks for taking a look.
