### ISSUE TITLE
Can't Ctrl-C out of Installing dotnet cli in Windows command prompt hangs

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#21078]
Normally I can press Ctrl-C and quit the currently exectuting task in the WIndows command prompt.

However, things seem to jam up and hang if I press control C when installing the dotnet cli.

This is a pain because my slow internet takes upwards of 1 hour to download the CLI, and I also often get errors like these and can't quit the build...

```
C:\Users\hugh\Documents\GitHub\corefx>build
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\GenFacades.Core.dll - Access is denied.
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\Microsoft.Cci.dll - Access is denied.
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\Microsoft.Cci.Extensions.dll - Access is denied.
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\Microsoft.DotNet.Build.Tasks.dll - Access is denied.
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\Newtonsoft.Json.dll - Access is denied.
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\NuGet.Common.dll - Access is denied.
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\NuGet.Packaging.Core.Types.dll - Access is denied.
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\NuGet.Packaging.dll - Access is denied.
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\NuGet.ProjectModel.dll - Access is denied.
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\NuGet.Versioning.dll - Access is denied.
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\roslyn\tools\Microsoft.Build.Tasks.CodeAnalysis.dll - Access is denied.
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\System.Diagnostics.TraceSource.dll - Access is denied.
Installing dotnet cli...
```

**Comment by karelz** [comment]
@weshaggard @mellinoe any idea how to route it? This is significantly impacting contributor workflow :(

**Comment by danmosemsft** [comment]
Does Ctrl-Break work? Usually that's not ignorable, wheras Ctrl-C relies on the app handling it.

**Comment by weshaggard** [comment]
Also the access denied part is generally caused because msbuild or VS is holding locking those libraries so they cannot be updated. You generally need to shutdown those processes to unlock those files.

**Comment by danmosemsft** [comment]
And VBCSCompiler.exe. Taskkill that, devenv and msbuild...

**Comment by hughbe** [comment]
Sorry for the delay answering. I don't actually have a break key on my laptop - indeed I've never actually heard of one before!
https://en.wikipedia.org/wiki/Break_key shows some substitute key combinations for dell laptops, but they don't seem to work either

What I meant about the access denied errors is that if they occur I don't really want the build to continue, However, I can't exit the build at this point which is a pain

**Comment by ViktorHofer** [comment]
I think we should address this as the "ordinary" dev expects Ctrl + C to just work.

**Comment by ViktorHofer** [comment]
Moving to arcade as they are now the owners of the bootstrap script.

**Comment by ViktorHofer** [comment]
Issue moved to [dotnet/arcade #1534](https://github.com/dotnet/arcade/issues/1534) via [**ZenHub**](https://www.zenhub.com/)
