### ISSUE TITLE
Where should ref docs and associated samples be stored?

### ISSUE THREAD

**Issue by richlander** [dotnet/corefx#2108]
Ideally, they would live in the code repo. Thoughts?

For clarity, ref docs augment the metadata and /// comments already available in the repo/builds. Many topics won't have ref topics.

@blackdwarf, @danroth27 

In reference to #2107

**Comment by blackdwarf** [comment]
Well, yes, but we already are going with separate repos for conceptual documentation. Would it make sense to split them in this manner? Also, contriubuting policies might be different (more lax) for samples and such, so that is also one more reason to keep them separate from the main code repos.

**Comment by richlander** [comment]
The challenge I see is that there is close coupling between /// commends and the markdown that augments it. It feels really strange to split that. Conceptual content can be anywhere. The same coupling doesn't exist. I think that the samples are a bit of a red-herring.

**Comment by blackdwarf** [comment]
Why would it feel strange to split that? The process by which /// comments become ref docs is out-of-band. Will we ever have a way for users to to that directly from the repo? I.e. have a build target generate ref docs from the current set of things in the CoreFX repo?

**Comment by richlander** [comment]
My point was that the process of creating content for ref-docs would be best done as a unified process. When someone says "I want to improve the System.String ref doc", they need look in only one repo for that. Most of the content for the doc already comes from the repo. These MD files augment that.

Also, how would we add content for a new member in a separate repo? Would be branch it in the same way we branch the code repo? Conceptual content doesn't have this problem near to the same degree.

**Comment by danroth27** [comment]
For most of our API ref docs the code comments will be the only source of content. For any API ref topics that need to be augmented I would think the additional content would live in the same repo as the code. For Sphinx projects its very common to have a docs folder next to your src folder all in the same repo.

**Comment by blackdwarf** [comment]
@richlander raised a good point about versioning. Separate repos would add complexity on this, while the same repo would keep this story simple. 

I guess what I was thinking was the following: if there is an *automatic* process that takes code comments as input and provides MD files as output on every change to the source code, then the location of the docs is important only insofar as we are considering additional content, i.e. something users might add. In all other cases, we can keep the docs wherever, that is, I don't have a strong preference.

**Comment by richlander** [comment]
Yup. This is what I was thinking, @danroth27  and @blackdwarf. I'm wondering what to do about code samples that we also want to pull into the ref docs. I've asked our documentation team for some advice on this one.

**Comment by blackdwarf** [comment]
I guess we want the samples to be runnable on their own?

**Comment by richlander** [comment]
That would indeed be good. That's why I chose to write them as DNX apps.

**Comment by blackdwarf** [comment]
Well, then they can live inside the main repo as well, right? Near the ref docs?

**Comment by blackdwarf** [comment]
Well, wouldn't it be good for them to live in the same repo as ref docs? That way you can change/consume both at the same time.

**Comment by danmosemsft** [comment]
Cleaning up extremely old issue that is now redundant
