### ISSUE TITLE
Need options for System information

### ISSUE THREAD

**Issue by livarcocc** [dotnet/corefx#21081]
_From @vnd-edu on June 15, 2017 5:21_

## Steps to reproduce
I am migrating Asp.net web application in .net core. i am not getting any api to find system information.

## Expected  behavior
in .net application i used System.management api to run query and get the all information.

## Actual behavior
how to get system information like processor id , system installed date and time?
Please help me out.
## Environment data
`dotnet --info` output:

_Copied from original issue: dotnet/cli#6883_

**Comment by karelz** [comment]
System.Management namespace is tracked in #14762. Closing as dupe.

We may have a few APIs in System.Runtime.RuntimeInfo and in Process, but probably not what you need.
