### ISSUE TITLE
Windows TrimEndChars not aligned with NTFS

### ISSUE THREAD

**Issue by iricigor** [dotnet/corefx#21096]
In `corefx/src/System.IO.FileSystem/src/System/IO/PathHelpers.Windows.cs` we have definition

`internal static readonly char[] TrimEndChars = { (char)0x9, (char)0xA, (char)0xB, (char)0xC, (char)0xD, (char)0x20, (char)0x85, (char)0xA0 };`

This is not fully aligned with underlying file system. For example 0xA0 is allowed as end char on NTFS. This can cause problems, as described [here](https://github.com/PowerShell/PowerShell/issues/4017). I think the same is with char 0x85. Others seems to be OK, but I have not confirmed it.

**Comment by stephentoub** [comment]
cc: @JeremyKuhne

**Comment by JeremyKuhne** [comment]
We should stop trimming these altogether- Windows will take care of this correctly.  @iricigor Do you want to do the PR for this?

**Comment by JeremyKuhne** [comment]
@iricigor, if not, I'll fix this early next week.

**Comment by iricigor** [comment]
Hi @JeremyKuhne , I created pull request for problematic two chars, for which I am sure its OK to remove. I think removing trimming altogether is slightly beyond my expertise. 

Another thing, I am not sure if this is full scope of the issue. I raised an issue in corefx, as this is where I found the problem in code. But. the issue is impacting also full CLR, see also comment from @jeffbi in [PowerShell project](https://github.com/PowerShell/PowerShell/issues/4017)

**Comment by JeremyKuhne** [comment]
> I created pull request for problematic two chars, for which I am sure its OK to remove. I think removing trimming altogether is slightly beyond my expertise.

I am positive removing the entire thing is OK. The real bug is we shouldn't be doing this at all- certainly not in a world where our lowest supported OS is Windows 7. :)

> the issue is impacting also full CLR

After the change is done I'll mark it as NetFX Port Consider. That will get it in the pipeline for desktop. When it gets "ported" it would be under a "quirk" where it will only impact those targeting the latest version or those that explicitly opt-in.

**Comment by jkotas** [comment]
The same trimming is in CoreCLR CoreLib as well. Do we need the fix there too?

https://github.com/dotnet/coreclr/blob/6ba74dc2a7194f8d6c86c3aeab572a074ef645c8/src/mscorlib/shared/System/IO/PathInternal.cs#L17

**Comment by JeremyKuhne** [comment]
@jkotas Yes, we need to pull in both places- thanks for the reminder.

**Comment by JeremyKuhne** [comment]
https://github.com/dotnet/coreclr/pull/12862 took care of this for CoreCLR. Still need to close on #21126 for CoreFX.

**Comment by danmosemsft** [comment]
@JeremyKuhne it seems to me this is fixed. Please reopen if not.

**Comment by JeremyKuhne** [comment]
It is. Missed closing this one.
