### ISSUE TITLE
Port async-aware CultureInfo property from CoreCLR.

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#21093]
@AtsushiKan commented on [Wed May 31 2017](https://github.com/dotnet/corert/issues/3747)

The following two tests are ActiveIssued onthis:

System.Globalization.Tests
-method  System.Globalization.Tests.CultureInfoAsync.TestCurrentCulturesAsync
-method System.Globalization.Tests.CultureInfoAsync.TestCurrentCulturesWithAwait

---

@AtsushiKan commented on [Thu Jun 15 2017](https://github.com/dotnet/corert/issues/3747#issuecomment-308786245)

Now tracked as TFS451287

---

@tarekgh commented on [Thu Jun 15 2017](https://github.com/dotnet/corert/issues/3747#issuecomment-308799315)

I have reassigned the TFS back to you @AtsushiKan. 

@AtsushiKan, is this for UAP scenario? or in general for aot? if it is in general for aot (even when running as non UAP, then you may assign it back to me). also I am wondering why we are tracking this as TFS and not here?

**Comment by AtsushiKan** [comment]
No, this is specific to AOT (i.e. the corert CoreLib, not the CoreCLR CoreLib.) The tests for AOT are still running as normal console exe's (not AppX) so the failure is general. (And at the time I opened this issue, it was clear that CoreCLR had implemented async-friendly CultureInfo and the feature hadn't been merged into the CoreRT counterpart. So I assume this is a genuine WIP.)

The same test running on CoreCLR in an AppX container are passing on Helix.

**Comment by tarekgh** [comment]
ok, I'll close it again and activate the TFS
