### ISSUE TITLE
FileSystemWatcher test failing in uap when trying to delete directory

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#21109]
cc: @ianhays @JeremyKuhne 

Test `public void FileSystemWatcher_Directory_NotifyFilter_Security(NotifyFilters filter)` is throwing unauthorizedAccess exception when trying to delete a directory in UAP after calling the `SetSecurityInfoByHandle` PInvoke. Code looks something like:
```c#
                Action action = () =>
                {
                    // ACL support is not yet available, so pinvoke directly.
                    uint result = SetSecurityInfoByHandle(dir.Path,
                        SE_FILE_OBJECT,
                        DACL_SECURITY_INFORMATION, // Only setting the DACL
                        owner: IntPtr.Zero,
                        group: IntPtr.Zero,
                        dacl: IntPtr.Zero, // full access to everyone
                        sacl: IntPtr.Zero);
                    Assert.Equal(ERROR_SUCCESS, result);
                };
                Action cleanup = () =>
                {
                    // Recreate the Directory.
                    Directory.Delete(dir.Path);   //<-Exception is thrown here!
                    Directory.CreateDirectory(dir.Path);
                };
```
If I move the Delete call before calling the PInvoke, it doesn't throw. I'm not sure if this is related to the permissions set in uap yet. This issue is to track the work of root causing the issue and either fix or keep the test disabled.

**Comment by JeremyKuhne** [comment]
I suspect that UAP just doesn't like having no permissions?

**Comment by danmosemsft** [comment]
Curious case but FSW for security attributes changes is definitely low priority.
