### ISSUE TITLE
Manual shims need to build against the correct vertical references in AllConfigurations leg

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#21103]
See comments at https://github.com/dotnet/corefx/pull/20839. 

Currently the manual shims for mscorlib and System are resolving references from RuntimePath (https://github.com/dotnet/corefx/blob/master/src/shims/manual/mscorlib.csproj#L25), which is correct on individual vertical builds but as part of the AllConfigurations leg it will always be netcoreapp which means the shims for the other configurations (currently only uap) will not have the correct type-forwards. Given we don't ship them from that build leg this isn't a blocker but we need to fix this to ensure we produce the same assets in the AllConfigurations mode that we do in the individual vertical legs.

cc @ViktorHofer @ericstj

**Comment by weshaggard** [comment]
Future as this does not currently impact us.

**Comment by ericstj** [comment]
This was just hit recently by @maryamariyan.   We should look into a fix for this.  /cc @safern

**Comment by safern** [comment]
Can we do something similar to what we do for netcoreapp2.0? https://github.com/dotnet/corefx/blob/master/src/shims/manual/Directory.Build.props#L20

**Comment by ericstj** [comment]
Yes: runtimepath needs to change to something else that takes project configuration into account.  It should likely be something similar to one of the runtime binplace paths that's active during allconfigurations build.

We should also make sure we have configurations defined for every runtime we build for.  I think we were missing one for uapaot.

**Comment by ViktorHofer** [comment]
Closing in favor of https://github.com/dotnet/corefx/issues/21103
