### ISSUE TITLE
Documentation missing for ProcessStartInfo.RedirectStandardOutput

### ISSUE THREAD

**Issue by shravan2x** [dotnet/corefx#21119]
This issue is created in reference to my SO issue [here](https://stackoverflow.com/questions/44467762/disposing-contents-of-stdout/44580472), which did not receive an answer in days. I then decided to experiment on my own. A copy is given below.

I'm not sure if the dotnet team has access to the docs [here](https://msdn.microsoft.com/en-us/library/system.diagnostics.processstartinfo.redirectstandardoutput(v=vs.110).aspx), but since it applies to .NET Core as well, it could be updated to clarify my use case below and potentially mention the 64k buffer size.

**QUESTION**
I am writing an application to manage processes and handle failovers. This program is written in C# for .NET Core and will run on Ubuntu Server 16.04 x64.

I have this code to create processes and track them, with exit events and such

```c#
ProcessStartInfo psi = new ProcessStartInfo
{
    WorkingDirectory = "/home/xyzserver/someprocess",
    FileName = "mono",
    Arguments = "someprocess.exe",
    RedirectStandardOutput = true
};

_proc = Process.Start(psi);
_proc.EnableRaisingEvents = true;
_proc.Exited += ProcOnExited;
```

I understand from the docs [here](https://msdn.microsoft.com/en-us/library/system.diagnostics.process.standardoutput(v=vs.110).aspx) that calls to Console.WriteLine will block if the _proc.StandardOutput stream is full. I want to prevent this behavior and dispose all the output from the managed application, since it will also write to a physical log on its own.

In addition, I would like to avoid storing any of the output in any unused stream buffers since they will never be used. A preferred solution will not UseShellExecute.

I have considered adding these 2 lines in the hope that any received data will be disposed, but am unsure about correctness.

```c#
_proc.OutputDataReceived += (sender, eventArgs) => {};
_proc.BeginOutputReadLine();
```

**SOLUTION**
I manually ran the test on .NET Core using 3 programs:

```
1. An HTTP server to track the *TextOutputter* program.
2. A TextOutputter program that prints 1000 characters and makes an HTTP request every second.
3. a ProgramRunner that runs one instance of TextOutputter.
```

Without the 2 lines, the buffer fills upto 64k and stalls. With the 2 lines, there is no stalling.

**Comment by svick** [comment]
There is a new version of API reference documentation for .Net being worked on at https://docs.microsoft.com/dotnet/api/. Specifically, [here is the documentation for `RedirectStandardOutput`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.redirectstandardoutput?view=netcore-1.1).

The new API reference is open source, so if you have any suggestions for improvements, you can either make the improvements yourself and submit a PR or you can just point out the problem by opening an issue on [the docs repo](https://github.com/dotnet/docs).

The docs team also has the ability to modify the MSDN docs (but I'm not sure what exactly are rules about propagating changes from docs.MS to MSDN).

**Comment by shravan2x** [comment]
@svick Thanks for the links. I'll post an issue on the docs repo later today.
