### ISSUE TITLE
HttpListener support for Digest

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#21112]
The original HttpListener supported Digest and WDigest through Windows SSPIs. Since WDigest is not allowed by recent Windows versions, during the port, the SSPI code has been removed.

This is tracking the replacement code needed to support Digest authentication [RFC 2617](https://tools.ietf.org/html/rfc2617).

**Comment by CIPop** [comment]
@Priya91 is this applicable for the managed implementation as well?
/cc @karelz @DavidGoll

**Comment by davidsh** [comment]
fyi, RFC2617 (which describes Basic and Digest) is obsoleted by these RFCs:

https://tools.ietf.org/html/rfc7235 (overview)
https://tools.ietf.org/html/rfc7615 (authorization request and response headers)
https://tools.ietf.org/html/rfc7616 (digest scheme)
https://tools.ietf.org/html/rfc7617 (basic scheme)

**Comment by hughbe** [comment]
Does netfx support Digest? If so, what's the compat story for HttpListener in core - does compatability with the RFC or netfx preside?

**Comment by karelz** [comment]
From practical point of view, netfx compat should win over RFC, unless we have evidence that RFC incompatibility is causing troubles for mix-and-matching platforms in real apps.

**Comment by CIPop** [comment]
NetFX supports the Digest scheme through the Nego SSPI which should implement the RFC.

**Comment by Priya91** [comment]
@CIPop Managed implementation doesnt have Digest auth as well.

**Comment by karelz** [comment]
Nobody asked for it in 2 years. Windows is highly discouraging it, let's close it.
