### ISSUE TITLE
TypeConverters for System.Drawing

### ISSUE THREAD

**Issue by qmfrederik** [dotnet/corefx#21129]
TypeConverters are currently omitted from System.Drawing.Common, as described in #20593.

Since the idea is that Mono will use the CoreFX System.Drawing sources, and Mono maintains compatibility with Desktop .NET, we should add them back.

Here's what I can do:
- Add the TypeConverters (possibly from Mono) to CoreFX
- Add the TypeConverter attributes to the System.Drawing classes and hide them between a feature flag.

The same will probably apply other Desktop-only features, such as `[Serializable]` attributes.

**Comment by danmosemsft** [comment]
We are limiting the types we apply Serializable to so if you have new such attributes we might want to put them on mono specific partial classes.

**Comment by danmosemsft** [comment]
@weshaggard @morganbr I wonder if we need an analyzer to flag if more [serializable]'s appear.

**Comment by weshaggard** [comment]
As for the TypeConverters assuming we add them I would like to keep the in the TypeConverters library instead of System.Drawing.Common library if at all possible. We have been trying to invert this dependency to avoid everything needing to depend on TypeConverter.

**Comment by safern** [comment]
@qmfrederik interested on grabbing this one?

**Comment by qmfrederik** [comment]
@safern What's the timeline for this?

**Comment by safern** [comment]
It would be great to have this in the 2.1 timeline so that when we ship the stable Compat pack and 2.1 we have this compatibility with Desktop and Mono could use our implementation.

We're currently in prepping preview1 release which we don't have a date yet, but it would be nice to get this one any time soon.

**Comment by satano** [comment]
I would try to do this one. I just need to explain a what should be done. What converters to take and where to put them.

**Comment by safern** [comment]
@satano I found we're currently missing:

* FontConverter
* IconConverter
* ImageConverter
* ImageFormatConverter

We would need to port them from Mono:
https://github.com/mono/mono/blob/master/mcs/class/System.Drawing/System.Drawing/IconConverter.cs

Put them into System.ComponentModel.TypeConverter and then add the attributes to the corresponding types.

@qmfrederik is there any TypeConverter that I missed?

**Comment by satano** [comment]
OK. I'll do it.

**Comment by safern** [comment]
Assigned to you. Thanks!

**Comment by safern** [comment]
@satano any progress o this? Do you have any questions?

**Comment by safern** [comment]
> I am doing this locally. In couple of days I will submit first version and will have questions there - it will be better to have context.

Sweet. Thanks for the update.

**Comment by satano** [comment]
@safern I am ready for feedback. :)
