### ISSUE TITLE
Announcement: Corefx CI legs updating 

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#21135]
As part of so infrastructure changes we are shifting the CI system a little. As folks probably already have noticed we have added "Portable" legs instead of having a bunch of different individual linux distro legs. Given that Portable is our default netcoreapp configuration now we are also going to remove that term from the descriptions and simplify some of the other legs/names as well.

Given the large changes to the CI system there isn't a great way to test beyond just switching which we plan to do today and we will actively work through any issues we run into. Please leave feedback on this issue or ping @weshaggard on any PR's where CI looks it has issues because of these changes. 

After the changes are done we should have the following CI legs PR:

```
CROSS Check
OSX x64 Debug Build
OSX x64 Release Build
Linux x64 Debug Build
Linux x64 Release Build
Windows x64 Debug Build
Windows x64 Release Build
NetFx Debug Build
NetFx Release Build
UWP CoreCLR Debug Build
UWP CoreCLR Release Build
UWP NETNative Debug Build
UWP NETNative Release Build
All Configurations Debug Build
All Configurations Release Build
Tizen armel Debug Build
Tizen armel Release Build
Ubuntu14.04 arm Release Build
Ubuntu16.04 arm Debug Build
```

By default a leg will run inner loop tests only and be targeting .NET Core portable binaries, unless a different configuration is specified (i.e. netfx, uwp, all). Each of these legs will also support an outerloop trigger by prepending the leg name with "Outerloop" for folks that need to manually trigger outerloop test runs. 

The only .NET Core non-portable legs we currently have is Tizen armel and Ubuntu arm @hqueue @jyoungyun Do we still need all those legs or is the Tizen leg enough? 

For reference the PR making the CI changes is https://github.com/dotnet/corefx/pull/20508. If there is any feedback/questions please add them to this issue.

**Comment by justinvp** [comment]
As long as you're simplifying/cleaning up the names...

> OSX x64 Debug Build
> OSX x64 Release Build

Nit: Any reason these couldn't be macOS instead of OSX? It's been macOS for a couple OS releases now.

> NetFx Debug Build
> NetFx Release Build
> UWP NETNative Debug Build
> UWP NETNative Release Build

Nit: It'd be nice if the casing of Net vs. NET was consistent.

**Comment by weshaggard** [comment]
>Any reason these couldn't be macOS instead of OSX? It's been macOS for a couple OS releases now

While I don't particularly mind this change it would be inconsistent with everything else we have in our infrastructure. For that reason I would like to keep it OSX and if we wanted to change it we should do a larger push through the system which I'm not sure is worth the effort.

>It'd be nice if the casing of Net vs. NET was consistent.

I will fix this to make it NETFx.

**Comment by weshaggard** [comment]
After some more discussion with other folks offline want to make the list a little more sparse and also mix in x86 runs so the current proposal is:

```
CROSS Check
OSX x64 Debug Build
Linux x64 Release Build
Windows x64 Debug Build
Windows x86 Release Build
NETFx x86 Release Build
UWP CoreCLR x64 Debug Build
UWP NETNative x86 Release Build
Packaging All Configurations x86 Release Build
Tizen armel Debug Build
Ubuntu14.04 arm Release Build
```

That should give us a decent mix of architecture, frameworks, flavors, and OS's. While keeping the number of legs for each PR at a reasonable count. We will still enable triggers for all combinations so people can trigger any combination as needed. We will also run all combinations as part of our CI for a commit to the repo.

**Comment by danmosemsft** [comment]
@hughbe fyi.

**Comment by weshaggard** [comment]
PR https://github.com/dotnet/corefx/pull/20508 has been merged. Please let me know if you see any issues.

**Comment by weshaggard** [comment]
There have been numerous successful PR's so I'm going to close this. Please feel to ask more questions or provide feedback if you like.
