### ISSUE TITLE
System.Net.Sockets: Go back to using GCHandles for linking a SocketAsyncContext to native code

### ISSUE THREAD

**Issue by vancem** [dotnet/corefx#21148]
In the following commit:

https://github.com/dotnet/corefx/commit/730df62e8948846f8661189811980ac341559d1a

To fix a race we creates a new layer of 'tokens' and a dictionary to go from these tokens to the SocketAsyncContext (which is the managed object holding the state of a single asynchronous I/O.  

After some discussion with @geoffkizer @stephentoub @jkotas and others we believe that it is a straightforward solution that solves the race.  It looks much like what the code WAS like (thus reverting this change would be a good starting point), but on close it will hand off to the polling thread the responsibility of freeing the GCHandle.

**Comment by karelz** [comment]
@vancem what is status of this issue? Do you plan to submit PR?

**Comment by karelz** [comment]
@vancem ping?

**Comment by vancem** [comment]
@karelz - Just to make sure I checked again and we still do use this Token abstraction in the Socket implementation (given that Geoff and Stephen were actively playing in this code).   

I believe that this change is useful.   Basically we added another (surprising) level of indirection to fix a corner case that could be fixed other ways.   Thus it is clearly simpler AND efficient to avoid that indirection.  so I do believe it is useful.   It should have a small but measurable effect (I estimated ~1% in scenarios where you are sending packets rapidly), but perhaps the bigger value is to simplify the code base (We can probably eliminate 100+ lines of code as well as the conceptual complexity and opportunity for bugs).  

So I don't want to close this issue (at worst we move the milestone).   

However I don't want to give up on the possibility of getting into 2.1 just yet.   I will try to get to this in December.   If I don't get to it, we can move the milestone.   If I do, we can see where we land...

**Comment by vancem** [comment]
I am copying in the most relevant parts of the e-mail conversation we had on this issue:  I wrote (on 6/14/17) 

I am probably not understanding all the subtlety here,  so let’s talk through the problem (starting with the simplest solution), and see where we land.  

Basically we have three APIs
```
    CreateSocketEventPort(out IntPtr port);
    TryChangeSocketEventRegistration(IntPtr port, IntPtr socket, SocketEvents currentEvents, SocketEvents newEvents, IntPtr data);
    WaitForSocketEvents(IntPtr port, SocketEvent* buffer, int* count);
```
The first creates an socket event port, the second registers a socket with the socket event port (where we pass it a ‘data’ that tells us ‘which socket’ is ready for I/O), and third is called to wait until one of the registered sockets has I/O ready (and passes us our ‘data’ back)

We want this data to be  SocketAsyncContext (a managed object).   Normally what we would do is create a GCHandle (which is a stable pointer) of IntPtr size, and use that as ‘data’ in the API above and have that GCHandle point SocketAsyncContext (which has all the other info in it).
It is reasonable for this GCHandle to be ‘owned’ by the socket, and thus when it closes, the GCHandle will be freed (and thus allowed to be reused).     For this to be true we can’t have any ‘dangling’ references to it left in the socket event port.  

The ‘obvious’ thing to do is as part of Socket close, it would also unregister itself with the socket event port (presumably by calling  TryChangeSocketEventRegistration).

First: Why does that not work?   

From text in the bug the race is that the ‘eventloop’ thread is still in flight when the unregistration happens.     This can be solved pretty easily.   We just make it the responsibility of the ‘eventloop’ thread to do the delete.   Basically ‘Close’ simply puts the socket on the free list, and eventloop code does the deletion at its next opportunity (and if that wakeup was for a deleted socket, it simply igores it).    

Thus my guess is that this is pretty easy to solve.   Presumably it is harder than that.  

It may be that the lower level APIs have issues, like the socket event port does not cleanly allow you to unregister (you can call TryChangeSocketEventRegistration with new values but that does not (reliably) invalidate the old ones (probably for I/O in flight)).    I don’t want to speculate more because I would hope that OS APIs were better designed than that.

But the bottom line here is that from the OS point of view we have a set of synchronous APIs that allow registration and unregistration, than this is a pretty ‘standard’ PINVOKE problem, and we should be solving it in ‘standard’ ways (using GC handles, and locks, an maybe some low lock stuff).  

***************************** 
One of my important observations is the following:

My main issue is that the current solution seems to be a sledge hammer (we can’t reuse handles ‘ever’).  We take this approach basically NOWHERE else, and there does not seem to be a good reason to here, so I am advocating for a simpler solution.

The ‘obvious’ design is it use GC handles and locks to insure correct concurrent access, ideally only taking a lock once per request, and for the shortest time.    You then look at where the locks are costing you important perf and consider VERY CAREFULLY some low lock designs to avoid the issue.    I am arguing that if you do this you don’t end up with what we have, but something significantly simpler.  

Does anyone have an OBJECTION to idea of going back to GCHandles (assuming we are careful about it in the way described above)?     

It SEEMS like the original race that was talked about is relatively easy to solve, and I don’t see why ANY issue associated with sockets is fundamentally different than other Native API code, and we solve all those with GCHandles, locks and tricky low lock stuff.     We should do that same here.  

*****************************

@jkotas and @geoffkizer  agreed that the going back was a good general idea, but the devil is in the details.

My expectation is that we start by reverting the original change and then fix the bug by having close not actually delete the native handle but queue it for deletion by the eventloop thread.    The details of course need to be worked out, but the basic direction is sound...

**Comment by geoffkizer** [comment]
> I believe that this change is useful. 

I agree and I'd like to see this happen.  I was hoping to get around to this after some other changes, but haven't had time.

> My expectation is that we start by reverting the original change and then fix the bug by having close not actually delete the native handle but queue it for deletion by the eventloop thread.

Sounds good to me.

**Comment by karelz** [comment]
@geoffkizer @vancem do you think we need to finish it in 2.1?

**Comment by geoffkizer** [comment]
I don't think it's mandatory, but I'm not sure we should punt it yet.

**Comment by vancem** [comment]
We are actively trying to improve socket perf for 2.1.   We should leave this until we declare we are done on that effort and then this will either be done or punted.

**Comment by karelz** [comment]
I am moving it to Future. If it proves to be critical for Sockets perf 2.1, we can bring it back. On its own, I don't think it is critical at this point.

**Comment by karelz** [comment]
Looks like not so beneficial code cleanup. If it plays important role in perf of Sockets, it is going to show up in investigations.
