### ISSUE TITLE
SqlGuid is not deserializing properly on netfx

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#21141]
It's already in the: PR https://github.com/dotnet/corefx/pull/21137

**Comment by karelz** [comment]
Reopening to track port to rel/2.0.0

**Comment by krwq** [comment]
@karelz this is already in 2.0.0: https://github.com/dotnet/corefx/commit/71f12632c21194d238bcde54508871a4ee67156b

**Comment by karelz** [comment]
@krwq was there a PR? (I can't find it)
Can you please link this bug from it? (see [PR rule](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#pr-rules) [7])

**Comment by krwq** [comment]
This was part of the serialization work: https://github.com/dotnet/corefx/pull/21098

**Comment by karelz** [comment]
OK, in future, please just add "Fixes #abcd" to that PR top description (I did it in this case).
Fixed in #21098
