### ISSUE TITLE
System.Threading.Tests.MutexTests hanging in Uap

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#21151]
This two tests are hanging in uap: 

CrossProcess_NamedMutex_ProtectedFileAccessAtomic
AbandonExisting

Sorce code:
https://github.com/dotnet/corefx/blob/master/src/System.Threading/tests/MutexTests.cs#L142-L201

They both hang when calling `new Mutex(false, name)` and the name contains `"Global\\"` as its prefix. 

cc: @kouvel @AntonLapounov

**Comment by danmosemsft** [comment]
I'm assuming this is because they are hitting app container and not gracefully handling that.

**Comment by AntonLapounov** [comment]
Need to port changeset 1656573 from ProjectN branch.

**Comment by danmosemsft** [comment]
@tijoytom this will come automatically right?

**Comment by kouvel** [comment]
CoreCLR issue: https://github.com/dotnet/coreclr/issues/11306

Does this need to go into 2.0 or is 2.1 sufficient?

**Comment by kouvel** [comment]
I'll go ahead and port this, it needs some changes in the PAL as well

**Comment by tijoytom** [comment]
@danmosemsft CoreCLR changes are not syn'd to N/CoreRT , need to be manually ported.  Thanks @kouvel for doing it.

**Comment by danmosemsft** [comment]
@tijoytom fyi there is some sharing: corelib\src\mscorlib\shared syncs with corert\src\System.Private.CoreLib\shared automatically

**Comment by kouvel** [comment]
Closing as dupe of https://github.com/dotnet/coreclr/issues/11306

**Comment by safern** [comment]
Note that the affected tests where disabled with `[ActiveIssue]` pointing to this issue.

**Comment by kouvel** [comment]
Yes I have added a link to those to the other issue as well
