### ISSUE TITLE
Array initialization throws ArgumentOutOfRangeException if size is 0 in ILC mode

### ISSUE THREAD

**Issue by caesar1995** [dotnet/corefx#21158]
System.Net.Sockets.SendPacketsAsync tests run fine in F5 ('uap') & netcore & netfx mode. But in ILC ('uap-aot') mode they are failing.  It seems that the array initialization throws ArgumentOutOfRangeException if size is 0 (take one test for example):

```c#
        [Theory]
        [InlineData(SocketImplementationType.APM)]
        [InlineData(SocketImplementationType.Async)]
        public void EmptyBuffer_Ignored(SocketImplementationType type)
        {
            SendPackets(type, new SendPacketsElement(new byte[0]), 0);
        }
```

SendPackets() will eventually call into `SetupPinHandlesSendPackets()` in `SocketAsyncEventArgs.Windows.cs`

```c#
        private unsafe void SetupPinHandlesSendPackets()
        {
           ...
            _sendPacketsDescriptor =
                new Interop.Winsock.TransmitPacketsElement[_sendPacketsElementsFileCount + _sendPacketsElementsBufferCount];
            // throws ArgumentOutOfRangeException if size is 0, i.e _sendPacketsElementsFileCount + _sendPacketsElementsBufferCount == 0
           ...
        }
```

If _sendPacketsElementsFileCount + _sendPacketsElementsBufferCount == 0, we get failures like this:

>System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.

Is this an expected problem from the UWP test runner in ILC mode? This is the cause for 90% of Sockets Functional tests failure in ILC mode.

cc: @davidsh

**Comment by davidsh** [comment]
cc: @CIPop

**Comment by CIPop** [comment]
> Is this an expected problem from the UWP test runner in ILC mode?

@caesar1995 I think the general idea is that the code should work identically in both compiled and not compiled versions. Since we're using the not-compiled version for debugging, these kinds of differences will be extremely hard to understand and fix for app-developers.

@yizhang82 PTAL

**Comment by caesar1995** [comment]
Should I change the label? All of the tests failed with the same reason (array initialized with size 0), they only failed in ILC run. I don't think it's Socket related problem

**Comment by davidsh** [comment]
This might be related to #21243

**Comment by caesar1995** [comment]
Another note: if I directly do
`int[] a = new int[0];`
This will work in ILC mode. The situation is similar to the one I described here (From "But if I do"): #21062

**Comment by tijoytom** [comment]
@hoyMS Can you please take a look and see if this is the same issue as #21243?

**Comment by hoyMS** [comment]
I'm taking a look. Which project file should I use to repro the failure?

**Comment by hoyMS** [comment]
@caesar1995 Thanks. Could you point me to the instructions on how to enable outerloop runs?

**Comment by hoyMS** [comment]
@caesar1995  Or can you provide the repro binaries and intermediates?

**Comment by davidsh** [comment]
>Could you point me to the instructions on how to enable outerloop runs?

msbuild /t:rebuildandtest /p:TargetGroup=uapaot /p:Outerloop=true

**Comment by caesar1995** [comment]
@hoyMS 
`cd src\System.Net.Sockets\tests\FunctionalTests` 
`msbuild /t:rebuildandtest /p:TargetGroup=uapaot /p:Outerloop=true`

You need to remove the [ActiveIssue(20135, TargetFrameworkMonikers.Uap)] label I put on 
Please let me know if you are not able to repro by running those test.

**Comment by caesar1995** [comment]
@hoyMS Which area label you think is appropriate for this issue? 

The array initialization is not Sockets specific, and the test only fails in ILC run.

**Comment by hoyMS** [comment]
@caesar1995 I think test-run-uwp-ilc is OK.

**Comment by davidsh** [comment]
@yizhang82 I've updated the area label to "Infrastructure".  Not sure what label applies in general to .NET Native toolchain bugs.  Please revise if necessary.  Thanks!

**Comment by hoyMS** [comment]
For the zero length array I'm seeing there are references to its element in the loop following the allocation. That will also cause an exception. Is it by design?

**Comment by caesar1995** [comment]
> That will also cause an exception

No, explained offline.

**Comment by hoyMS** [comment]
I switched the no-opt test and verified that the failure is not from the loop but from the following routine with an zero length array and an zero index.


//====================================================================
        // UnsafeAddrOfPinnedArrayElement()
        //
        // IMPORTANT NOTICE: This method does not do any verification on the
        // array. It must be used with EXTREME CAUTION since passing in
        // an array that is not pinned or in the fixed heap can cause
        // unexpected results !
        //====================================================================
        public static IntPtr UnsafeAddrOfPinnedArrayElement(Array arr, int index)
        {
            if (arr == null)
                throw new ArgumentNullException(nameof(arr));

            if (index < 0 || index >= arr.Length)
                **_throw new ArgumentOutOfRangeException(nameof(index)_**);
            Contract.EndContractBlock();

            int offset = checked(index * arr.GetElementSize());

            return arr.GetAddrOfPinnedArrayFromEETypeField() + offset;
        }

Call stack:

	xunit.console.netcore.dll!$36_System::Runtime::InteropServices::Marshal.UnsafeAddrOfPinnedArrayElement(System::Array & arr, int index) Line 1443	Unknown
 	xunit.console.netcore.dll!$36_System::Runtime::InteropServices::Marshal.UnsafeAddrOfPinnedArrayElement<Interop+Winsock+TransmitPacketsElement>($28_Interop::Winsock::TransmitPacketsElement[] & arr, int index) Line 1453	Unknown
>	xunit.console.netcore.dll!$28_System::Net::Sockets::SocketAsyncEventArgs.SetupPinHandlesSendPackets() Line 1065	Unknown
 	xunit.console.netcore.dll!$28_System::Net::Sockets::SocketAsyncEventArgs.CheckPinSendPackets() Line 847	Unknown
 	xunit.console.netcore.dll!$28_System::Net::Sockets::SocketAsyncEventArgs.InnerStartOperationSendPackets() Line 661	Unknown
 	xunit.console.netcore.dll!$28_System::Net::Sockets::SocketAsyncEventArgs.StartOperationSendPackets() Line 584	Unknown
 	xunit.console.netcore.dll!$28_System::Net::Sockets::Socket.SendPacketsAsync($28_System::Net::Sockets::SocketAsyncEventArgs & e) Line 4313	Unknown
 	xunit.console.netcore.dll!$29_System::Net::Sockets::Tests::SendPacketsAsync.SendPackets($29_System::Net::Sockets::Tests::SocketImplementationType type, $28_System::Net::Sockets::SendPacketsElement[] & elements, $24_System::Net::Sockets::SocketError expectedResut, int bytesExpected) Line 459	Unknown
 	xunit.console.netcore.dll!$29_System::Net::Sockets::Tests::SendPacketsAsync.SendPackets($29_System::Net::Sockets::Tests::SocketImplementationType type, $28_System::Net::Sockets::SendPacketsElement & element, int bytesExpected) Line 433	Unknown
 	xunit.console.netcore.dll!$29_System::Net::Sockets::Tests::SendPacketsAsync.BufferZeroCount_Ignored($29_System::Net::Sockets::Tests::SocketImplementationType type) Line 179	Unknown


At this point, I would say it’s not an optimizer issue. We should probably change the test source.

**Comment by caesar1995** [comment]
@hoyMS Thanks for your help Hongtao. But probably this is not the answer.

I have few doubts:
1. I'm not able to find the implementation of UnsafeAddrOfPinnedArrayElement(), [this is what get.](https://github.com/dotnet/coreclr/blob/906f60ce3c55ab0cc41765d9eeea542ec65ff737/src/mscorlib/src/System/Runtime/InteropServices/Marshal.cs#L323) Could you please share where can I find the implementation?
2. Based on the above implementation. [If this line of code causes touble, ](https://github.com/dotnet/corefx/blob/481dfcd969465de63aeaf3a4c274eb94ad0e9053/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Windows.cs#L1065)
`_ptrSendPacketsDescriptor = Marshal.UnsafeAddrOfPinnedArrayElement(_sendPacketsDescriptor, 0);` which means index is always == 0 for `UnsafeAddrOfPinnedArrayElement(Array arr, int index)`
3. > ...verified that the failure is not from the loop but from the following routine with an zero length array and an zero index

which means `if (index < 0 || index >= arr.Length)` **will always be true** (0 >= 0), therefore `ArgumentOutOfRangeException` **will always been thrown**. No matter it's netcore/uap/uapaot run. However, we are only observing the failure in ILC mode.

4. >We should probably change the test source.

What test source, our product code, or test cases?

cc: @DavidGoll

**Comment by hoyMS** [comment]
The method UnsafeAddrOfPinnedArrayElement is not in CoreFX, instead it's in System.Private.Corelib:

CoreRT\src\System.Private.Interop\src\System\Runtime\InteropServices\Marshal.cs

@yizhang82 @tijoytom  Looks like the method is .Net Native specific. Do we want to do something special in SetupPinHandlesSendPackets for .Net Native?

**Comment by hoyMS** [comment]
@tijoytom Could you please take a look?

**Comment by tijoytom** [comment]
thanks , i will check-in a fix

**Comment by tijoytom** [comment]
@caesar1995 I have checked in a fix for this one ... but you can get much better performance from using System.Runtime.CompilerServices.Unsafe.
cc @jkotas @yizhang82

**Comment by davidsh** [comment]
>I have checked in a fix for this one

@tijoytom Where is the fix?  Can you put a link to the PR here?  Is it in the .NET Native toolchain?  If so, when will those updated TestILC packages be consumed in CoreFx?

**Comment by tijoytom** [comment]
The fix is in TFS, the tomorrow's CoreFX package should have the fix.

**Comment by tijoytom** [comment]
#1662861

**Comment by caesar1995** [comment]
I have verified test behavior. This issue has been fixed. Thanks! @tijoytom @hoyMS 

I will submit a PR to re-enable tests.

cc: @davidsh @DavidGoll
