### ISSUE TITLE
Enable UWP6.0 MF x86 and MF ARM legs in outerloop

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#21154]
This issue is tracking turning on the Multifile x86 and Multifile arm legs in Helix as part of the UWP6.0 zbb.

@tijoytom you'll want to chat with @joperezr for a pointer

/cc @yizhang82

**Comment by tijoytom** [comment]
@joshfree @yizhang82  I know noting about how to schedule  helix runs , someone familiar with infrastructure should do it.

**Comment by joshfree** [comment]
@tijoytom it'll be cloning @joperezr 's /dotnet/corefx PR for the other 2 legs.  Could you sync up with @joperezr?

**Comment by joperezr** [comment]
I'm happy to help with guidance offline @tijoytom so feel free to stop by.

**Comment by tijoytom** [comment]
I might ask for @botaberg for help here . He knows way more about helix than i do.
cc @yizhang82

**Comment by tijoytom** [comment]
@botaberg Can you please take a look at this one , @joperezr can help

**Comment by botaberg** [comment]
Hi @tijoytom @joperezr what PR needs to be cloned?

**Comment by joshfree** [comment]
@botaberg can this bug be closed now that your PR has been merged?

**Comment by botaberg** [comment]
@joshfree @joperezr have we gotten confirmation that the multifile ARM leg is running?

**Comment by joperezr** [comment]
I merged your PR today, so we can't really get a confirmation until a new full build occurs (either tonight's or tomorrow's)

**Comment by tijoytom** [comment]
@botaberg Closing this since the PR is merged.
