### ISSUE TITLE
System.Drawing.Imaging ColorrMatrix missing checking for wrong ctor params 

### ISSUE THREAD

**Issue by norek** [dotnet/corefx#21172]
ColorMatrix class has missing some of bad values checking
1. Check for null in ctor
2. Check if passed array is smaller (in each dimension) than [4][4].

I can provide checking and throw ArgumentExceptions.
What do your think @mellinoe ?

**Comment by hughbe** [comment]
I say no, we don't to break netfx compat - System.Drawing.Common is there for compat purposes mainly

**Comment by hughbe** [comment]
But do add tests for these kinds of things... I actually really enjoy  taking a look at the code and predicting what the results will be before I write the test. Makes the whole thing about more exciting, but maybe I'm weird 🙃

**Comment by norek** [comment]
Yup your are right! Im closing this issue and go write some test cases!

**Comment by hughbe** [comment]
Woohoo! tests are a form of documentation by themselves, and also we want to ensure that the Unix implementation matches the quirks in Windows (to a certain extent)
