### ISSUE TITLE
Remove unnecessary attributes and callback from non-serializable types

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#21187]
Relates to changes introduced in https://github.com/dotnet/corefx/issues/19119
Remove unnecessary attributes and callbacks (NonSerialized, OnSerializing, etc) from non-serializable types.

- [x] CoreFX
- [ ] CoreCLR
- [ ] CoreRT

cc @danmosemsft @morganbr

**Comment by stephentoub** [comment]
We need to be careful here not to break Mono in places where Mono is sharing corefx source.

**Comment by ViktorHofer** [comment]
System.Drawing.Common is currently the only place where we have extra files for Monos serialization support. Everywhere else we removed the Serializable attribute completely.

The corefx sources are now cleaned up and the coreclr cleanup PR is pending and awaiting review. Afterwards I will look into corert.
