### ISSUE TITLE
RemoteExecutorTestBase throws TargetParameterCountException passing an empty string as an argument

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#21181]
Example:
```cs
RemoteInvoke(param => Assert.Empty(param), string.Empty).Dispose();
```

**Comment by danmosemsft** [comment]
It is not quoting. It would need to do some quoting scheme on its arguments, and unquote at the other end;

https://github.com/dotnet/corefx/blob/master/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.Process.cs#L52
