### ISSUE TITLE
InvalidBufferSizeThrows failed on netfx

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#21186]
https://ci.dot.net/job/dotnet_corefx/job/release_2.0.0/job/netfx_windows_nt_debug_prtest/219/consoleText

System.IO.Tests.FileStream_ctor_sfh_fa_buffer_async.InvalidBufferSizeThrows [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentOutOfRangeException)
        Actual:   typeof(System.ObjectDisposedException): Cannot access a closed file.
    Finished:    System.Collections.Concurrent.Tests
        Stack Trace:
  === TEST EXECUTION SUMMARY ===
  Using D:\j\workspace\netfx_windows---120b7803\bin\testhost\netfx-Windows_NT-Debug-x86\ as the test runtime folder.
     System.Collections.Concurrent.Tests  Total: 2027, Errors: 0, Failed: 0, Skipped: 0, Time: 41.910s
  Executing in D:\j\workspace\netfx_windows---120b7803\bin\AnyOS.AnyCPU.Debug\System.Globalization.Extensions.Tests\netstandard\ 
  Running tests... Start time:  6:52:32.15
             at System.IO.__Error.FileNotOpen()
             at System.IO.FileStream.Flush(Boolean flushToDisk)
             at System.IO.FileStream.get_SafeFileHandle()
  Finished running tests.  End time= 6:52:32.47, Exit code = 0
          D:\j\workspace\netfx_windows---120b7803\src\System.IO.FileSystem\tests\FileStream\ctor_sfh_fa_buffer.cs(30,0): at System.IO.Tests.FileStream_ctor_sfh_fa_buffer.<>c__DisplayClass2_0.<InvalidBufferSizeThrows>b__1()

**Comment by danmosemsft** [comment]
Was fixed in dbd01e7691932235e007e454a1b7d7934b582de9

**Comment by stephentoub** [comment]
Does that fix need to be ported to the release branch then?

**Comment by danmosemsft** [comment]
I wouldn't object, but it's a bigger change so it would need inspection.

**Comment by danmosemsft** [comment]
@jeremykuhne any reason we shouldn't grab dbd01e7 for 2.0 ?doesn't seem it depends on anything?

**Comment by stephentoub** [comment]
This was a desktop-specific failure with a fix already in corefx, and the test in question no longer exists. Closing.
