### ISSUE TITLE
Thread.Name should use SetThreadDescription

### ISSUE THREAD

**Issue by Alois-xx** [dotnet/corefx#21190]
Windows 10 Creators Update delivers new APIs to set the thread name 

https://msdn.microsoft.com/en-us/library/windows/desktop/mt774976(v=vs.85).aspx

These should be used by the managed thread name set property as well so one can find the thread name in ETW traces on Windows as well. Currently there was no way to set the thread name for unmanaged threads with a decent API until Creators Update.

**Comment by danmosemsft** [comment]
@mikem8361 @brianrob as I understand it, `Thread.Name` is just a contract between CLR and the debugger and the value is stored on Thread. The idea is it could also SetThreadDescription.

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/coreclr #12354](https://github.com/dotnet/coreclr/issues/12354) via [**ZenHub**](https://www.zenhub.com/)
