### ISSUE TITLE
System.Drawing needs more code coverage (13.4%)

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#21193]
https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/Code_Coverage_Report/

This is a great place for new contributors to start.

**Comment by hughbe** [comment]
Note that System.Drawing.Common is tracked in #20711

**Comment by danmosemsft** [comment]
Ah yes -- well, maybe this one would help attract contributors.

**Comment by mellinoe** [comment]
I'm going to close this because it's primarily tracked by https://github.com/dotnet/corefx/issues/20711, and by now we have very good coverage, anyways.
