### ISSUE TITLE
One or more tests failed while running tests from 'System.Collections.Immutable.Tests' failed in ci

### ISSUE THREAD

**Issue by v-haren** [dotnet/corefx#21219]
/mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/Tools/tests.targets(353,5): error : One or more tests failed while running tests from 'System.Collections.Immutable.Tests' please check /mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/bin/AnyOS.AnyCPU.Debug/System.Collections.Immutable.Tests/netcoreapp/testResults.xml for details! [/mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/src/System.Collections.Immutable/tests/System.Collections.Immutable.Tests.csproj]

detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/rhel7.2_debug/2971/consoleFull#32536873579fe3b83-f408-404c-b9e7-9207d232e5fc

**Comment by danmosemsft** [comment]
It crashed but Dumpling failed
```
21:18:58   processing dump file /mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/bin/AnyOS.AnyCPU.Debug/System.Collections.Immutable.Tests/netcoreapp/core.17634
21:18:58   creating dumpling dump fdf4aa4148c7f9b28d64d93572cc7391fe43a545
21:18:58   uploading artifact fdf4aa4148c7f9b28d64d93572cc7391fe43a545 core.17634
21:18:58   Trying to find crash dumps for project: System.Collections.Immutable.Tests
21:18:58   Uploading dump file: /mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/bin/AnyOS.AnyCPU.Debug/System.Collections.Immutable.Tests/netcoreapp/core.17634
21:18:58   /mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/src/System.Collections.Immutable/tests
21:18:58   Finished running tests. End time=04:18:58. Return value was 139
21:18:58   Starting:    System.IO.FileSystem.Tests
21:18:58 /mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/Tools/tests.targets(345,5): warning MSB3073: The command "/mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/bin/AnyOS.AnyCPU.Debug/System.Collections.Immutable.Tests/netcoreapp/RunTests.sh /mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/bin/testhost/netcoreapp-Linux-Debug-x64/" exited with code 139. [/mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/src/System.Collections.Immutable/tests/System.Collections.Immutable.Tests.csproj]
21:18:58 
/mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_debug/Tool
```

https://github.com/dotnet/corefx/issues/21225

**Comment by safern** [comment]
Since this was about a month ago, we haven't seen this happen again in CI and we have no logs at all to get a repro, we are going to close it. If somebody hits it we could re-open and take a look at his logs.
