### ISSUE TITLE
NetworkInterface.Speed: different behavior

### ISSUE THREAD

**Issue by PawelGerr** [dotnet/corefx#21226]
The property `Speed` of type `NetworkInterface` behaves different on Linux than on Windows.

* On Windows I'm getting the number of **bytes** per second.
  * In my case the returned value is 1,000,000,000
  * That is the expected behavior (https://msdn.microsoft.com/de-de/library/system.net.networkinformation.networkinterface.speed(v=vs.110).aspx)
* On Linux I'm getting a `PlatformNotSupportedException` (that's ok) or **mega bytes** per second (not ok).
  * The returned value is 1,000

## System
* ubuntu 16.04 x64
* dotnet version: 1.04

### NIC Info on Linux
```
	Supported ports: [ TP ]
	Supported link modes:   10baseT/Half 10baseT/Full 
	                        100baseT/Half 100baseT/Full 
	                        1000baseT/Full 
	Supported pause frame use: No
	Supports auto-negotiation: Yes
	Advertised link modes:  10baseT/Half 10baseT/Full 
	                        100baseT/Half 100baseT/Full 
	                        1000baseT/Full 
	Advertised pause frame use: No
	Advertised auto-negotiation: Yes
	Speed: 1000Mb/s
	Duplex: Full
	Port: Twisted Pair
	PHYAD: 0
	Transceiver: internal
	Auto-negotiation: on
	MDI-X: off (auto)
Cannot get wake-on-lan settings: Operation not permitted
	Current message level: 0x00000007 (7)
			       drv probe link
	Link detected: yes

```

**Comment by stephentoub** [comment]
cc: @mellinoe

**Comment by mellinoe** [comment]
@PawelGerr Thanks for the bug report. It does look like we are neglecting to convert the value from `/sys/class/net/xyz/speed` into the correct units to match Windows. My understanding is that the value should be in bits per second, not bytes per second, but the Linux value is actually in megabits per second, not megabytes, so the conversion factor should be the same (1,000,000).

**Comment by mellinoe** [comment]
I just double-checked: the information we use on OSX is already in bits per second, so this bug should only affect Linux.

**Comment by PawelGerr** [comment]
@mellinoe you are right, it is **bits** not **bytes**

**Comment by stephentoub** [comment]
Reopening to track 2.0 port...

**Comment by stephentoub** [comment]
Ported in https://github.com/dotnet/corefx/pull/21318
