### ISSUE TITLE
clean.cmd should also stop dotnet and msbuild execution

### ISSUE THREAD

**Issue by alexperovich** [dotnet/corefx#21237]
The current clean.cmd only stops execution of VBCSCompiler.exe. It should also stop execution of dotnet.exe and msbuild.exe to prevent problems with cleaning the output.

**Comment by weshaggard** [comment]
I'm not sure we should have it kill dotnet or msbuild as that might kill any other instances of those on the machine. I know I'm often building different repo's at the same time so I wouldn't want it to blindly kill msbuild.

**Comment by alexperovich** [comment]
This is causing problems during the official builds where clean.cmd fails to delete the bin directory. We either need to kill those processes like we do VBCSCompiler.exe, or make clean.cmd not care if it can't delete something.

**Comment by weshaggard** [comment]
For official builds @MattGal already started killing those processes but want we really need is a better process clean-up mechanism. I talked with @MattGal about adding a poison env variable at the beginning official build and then at the end kill any process that has the variable defined in it. That should help keep processes cleaned in our official builds.

**Comment by weshaggard** [comment]
We are going to solve the official build issues in a different way. For local dev builds I don't think we should kill dotnet and msbuild as part of clean.cmd/sh
