### ISSUE TITLE
We need a way to run tests on different runtime

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#2124]
We need a way to choose between different platforms when running tests.

Example proposition:

```
build /p:TestProduct=Desktop
```

**Comment by mellinoe** [comment]
To run on desktop this should literally be as simple as just omitting the "corerun" portion of the command line args. The xunit.console.netcore executable we have is fully compatible with .NET 4.6.

`corerun.exe xunit.console.netcore.exe <testassembly>` : Runs on CoreCLR
`xunit.console.netcore.exe <testassembly>` : Runs on .NET Framework

**Comment by eatdrinksleepcode** [comment]
Related to dotnet/buildtools#132. I had started working on that a while back; I think I can put together a PR in the next day or two.

**Comment by krwq** [comment]
@mellinoe @eatdrinksleepcode, It will probably be necessary to also copy the runtime facades (they should be in the packages)

**Comment by mellinoe** [comment]
Most of the facades are actually already in the GAC on desktop, but there will be some extra ones we need to copy over. Hopefully with how the NuGet packages are set up, they will automatically be resolved in the build.

**Comment by mellinoe** [comment]
We have support for this now.
