### ISSUE TITLE
Proposal: ref returns API for Dictionary

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#21240]
@brandon942 commented on [Mon Jun 19 2017](https://github.com/dotnet/coreclr/issues/12361)

Dictionary value updates are not possible without unnecessary double lookups in the current Dictionary implementation.  
This issue has been there forever and is particularly problematic for value-type/struct values which are extensively used in game dev. Value updates require the whole struct to be copied, changed and reinserted (copied again) with another lookup. The C#7 ref feature allows one to create faster custom dictionaries without messing with Entry indexes, but why not fix the Dictionary in the coreclr?  

The following Dictionary methods are needed to prevent double lookups in checks & updates and insertions:

    public ref TValue GetValueByRef(TKey key) // throws if key not found
    private static TValue _DefaultVal; // needed for TryGetValueByRef as default return
    public ref TValue TryGetValueByRef(TKey key, out bool found) 
    public ref TValue TryGetValueByRefOrAdd(TKey key, out bool found, TValue setVal)
    public bool TryGetValueOrAdd(TKey key, out TValue value, TValue setValue)  

Furthermore I propose incrementing the `version`-field (used by enumerators) only when Entries are added or removed, but not when they are changed because it serves no purpose. Reference-type values can already be changed without the Dictionary knowing and incrementing the version.

**Comment by svick** [comment]
This is effectively a duplicate of https://github.com/dotnet/corefx/issues/20684.

**Comment by danmosemsft** [comment]
I'm going to resolve as such. @brandon942 please reactivate if it's not a dupe
