### ISSUE TITLE
[Cookie] CookieContainer has issues with cookies set to a different path than the current request uri path

### ISSUE THREAD

**Issue by javiercn** [dotnet/corefx#21250]
When a server sends back a cookie with a path different than the current request uri, CookieContainer throws an exception indicating that the path portion of the cookie is invalid. For example:

* HttpClient send a request to `/Home/About`
* The server answers with a redirect response to `/tfp/Identity/signinsignup/...` and sets a cookie to `/signin-oidc`
* Internally, CookieContainer throws or silently fails on line https://github.com/dotnet/corefx/blob/master/src/System.Net.Primitives/src/System/Net/Cookie.cs#L508

I believe this is due to the fact that an old version of the spec required any path on any cookie set by the server to be a prefix path of the current request URI. This doesn't seem to be the case in the latest version of the standard.

https://tools.ietf.org/html/rfc6265 (new version)
https://tools.ietf.org/html/rfc2109 (old version)

For reference, this works fine on all major browsers (Chrome, Firefox, Edge,...)

We ran into this on our authentication tests (that run the scenario mentioned above).

Limiting the path check in the code linked above to only the case when the cookie refers to an old version of the spec should be enough.

**Comment by javiercn** [comment]
@Eilon

**Comment by davidsh** [comment]
Current .NET Framework and .NET Core System.Net.Cookie does not handle RFC6265 yet.

related to: https://github.com/dotnet/corefx/issues/18013

**Comment by caesar1995** [comment]
Tracked in #29651.
