### ISSUE TITLE
TargetsWindows msbuild property is false for netfx configuration

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#21252]
For the `netfx` configuration, `'$(TargetsWindows) == 'false'`
However, we can use the `netfx-Windows_NT` configuration instead, and `'$(TargetsWindows) == 'true'`

Is this expected?

Example configuration.props
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <BuildConfigurations>
      netstandard;
      netcoreapp-Windows_NT;
      netfx;
    </BuildConfigurations>
  </PropertyGroup>
</Project>
```

Example csproj
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), dir.props))\dir.props" />
  <PropertyGroup>
    <ProjectGuid>{A824F4CD-935B-4496-A1B2-C3664936DA7B}</ProjectGuid>
    <DefineConstants Condition="'$(TargetGroup)'=='netcoreapp'">$(DefineConstants);netcoreapp</DefineConstants>
  </PropertyGroup>
  <!-- Default configurations to help VS understand the configurations -->
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'nestandard-Debug|AnyCPU'" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'nestandard-Release|AnyCPU'" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'netcoreapp-Windows_NT-Debug|AnyCPU'" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'netcoreapp-Windows_NT-Release|AnyCPU'" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'netfx-Windows_NT-Debug|AnyCPU'" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'netfx-Windows_NT-Release|AnyCPU'" />
  <ItemGroup>
    <Compile Include="Tests.cs" Condition="'$(TargetsWindows)' == 'true'" />
  </ItemGroup>
  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), dir.targets))\dir.targets" />
</Project>
```

Example Tests.cs

```c#
using Xunit;

public class Tests
{
    [Fact]
    public void AssertFailure()
    {
        Assert.False(true);
    }
}
```

**Comment by danmosemsft** [comment]
@weshaggard

**Comment by weshaggard** [comment]
That is expected. See https://github.com/dotnet/corefx/blob/master/tools-local/osgroups.props#L6 whenever you are building a configuration where the selected project configuration is Windows_NT then TargetsWindows will be set to true. If there is no OS specified in the configuration for the project then the OS will be AnyOS and thus TargetsWindows/TargetsUnix would not be set.

**Comment by hughbe** [comment]
I understand it's expect based off the infrastructure source code, but I'm not sure it's expected based off intuition. netfx is Windows only so I think this should be true for netfx

**Comment by weshaggard** [comment]
That would be true for uap as well but we are trying not to bake any such assumptions into the configuration system. There is definitely a potential in the future where netfx and mono are similar builds and in that case mono would be more then just windows. 

Thanks for the feedback @hughbe but at this point I don't think we want to make any changes to the current assumptions.
