### ISSUE TITLE
Command Line tokenization is done all over the place and inconsistently. They should be reconciled.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#21267]
We have at least four separate implementations of command line tokenization/pasting:

CoreCLR  - Windows - **Environment.GetCommandLineArgs()** and create a String[] array to pass to Main()
https://github.com/dotnet/coreclr/blob/master/src/utilcode/util.cpp#L2886

CoreRT - Windows - **Environment.GetCommandLineArgs()** and create a String[] array to pass to Main()
https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/Runtime/CommandLine.Windows.cs#L44

CoreFx - Unix - **System.Diagnostics.Process** - create String[] array to pass to Unix exec().
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs#L450

CoreFx - AnyPlatform - **Environment.CommandLine** - untokenize String[] array back to a single String. https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/Environment.cs#L64

There's also test infrastructure (https://github.com/dotnet/corefx/blob/master/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.Process.cs#L52) which implements a "String[]"-based process invocation utility. It should also paste the arguments using the canonical standard but right it now, it doesn't even make a minimal attempt.

While we can't easily share source for an algorithm that lives in three different repos and is written in two different languages, they should at least implement the same standard. It's a pity we never API'ized this in a usable way since every command line tool that parses a response file has to redo this work (and probably get it wrong.)

That standard should probably be the CRT's **parse_cmdline()** routine which is what the full framework has emulated ever since .Net 4.0.

The <a href="https://github.com/dotnet/coreclr/blob/master/src/utilcode/util.cpp#L2886">CoreCLR</a> and <a href="https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/Runtime/CommandLine.Windows.cs#L44">CoreRT</a> implementations are probably already good reference implementations to model (aside from some incorrect comments that imply the behavior is based on **CommandLineToArgvW()**. That may have been true once, but that behavior has diverged between it and the CRT.)

The <a href="https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs#L450">Unix tokenizer</a> at has at least one bug related to zero-length arguments.

And the <a href ="https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/Environment.cs#L64">repaster for Environment.CommandLine</a> looks highly suspect (does not recognize that argv[0] is tokenized using special rules, and handling of the 2N/2N+1 backslash rule.)

For reference here's also a good 3rd party overview of the sorry mess: http://www.windowsinspired.com/how-a-windows-programs-splits-its-command-line-into-individual-arguments/

**Comment by Priya91** [comment]
Related to #4720

**Comment by AtsushiKan** [comment]
All that's left to do now to make <a href="https://github.com/dotnet/corefx/blob/232f48884efed22d228ae4a9450b37fbfa92b861/src/System.Runtime.Extensions/src/System/Environment.cs#L64">Environment.CommandLine<a> call our <a href="https://github.com/dotnet/corefx/blob/445afb8e15007f8a69aa93849a298cd2367d44b2/src/Common/src/System/PasteArguments.cs#L16">Paste utility</a> and make sure our tests still pass.

The <a href="https://github.com/dotnet/corefx/blob/445afb8e15007f8a69aa93849a298cd2367d44b2/src/Common/src/System/PasteArguments.cs#L37">throw statement</a> for quotes inside argv0 needs to be replaced with something productizable. Since the input was constructed by the framework itself from the passed in command line, this shouldn't ever happen but if it ever does, throwing is a bit extreme here. I'd say just change this to insert a single-quote so that the output still looks reasonable inside a diagnostic log.

**Comment by ramusbucket** [comment]
This will be my first work. Can I take this up. I have forked, cloned, built and built-tested to the repo on my machine. Thanks.

**Comment by AtsushiKan** [comment]
Hi @ramusbucket. Thanks for taking this on! Absolutely, feel free to grab this.

**Comment by ramusbucket** [comment]
ok, I'm starting on this...

**Comment by artkpv** [comment]
Hello, thank you for this opportunity to contribute to .NET Core libraries!

@AtsushiKan I've created my first PR. Not sure I did all correctly, please review it. Some tests fails (`System.Drawing.Common.Tests`, `System.DirectoryServices.AccountManagement.Tests`, and other).

**Comment by artkpv** [comment]
@AtsushiKan I'm not sure about what this issue needs next. I'm going to check those places listed at the top and related issues if some reconciliation needs to be done. Please correct me.

**Comment by AtsushiKan** [comment]
@artkpv - That was the actually the last piece so I'm closing the issue now. Of course, if you do find any opportunities we missed earlier, feel free to go after it :-)
