### ISSUE TITLE
Add back some private constructors in System.Drawing.Common

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#21270]
https://github.com/dotnet/corefx/commit/f6bb2b5bb5f8841e839fb99eb60118b7b37c4901 removed a few private constructors, because they are not interesting for .NET Core. We should add them back behind a flag, because mono needs them to stick around when they compile this code.

@hughbe

**Comment by justinvp** [comment]
Why not add the private constructors back to corefx without a flag? Having them private in the implementation is good, IMO, as it makes it clear in the implementation that these types should not have a public default ctor and cannot be created that way.

**Comment by mellinoe** [comment]
Fair enough -- let's add them back unconditionally.

**Comment by hughbe** [comment]
I'll grab this
