### ISSUE TITLE
[NetFx/Mono compat] File.Delete throws IOException on non-existing file on a read-only file system on Linux

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/corefx#21273]
Repro steps:

```bash
$ sudo mkdir -p /mnt/readonlyfs
$ sudo mount --bind / /mnt/readonlyfs
$ sudo mount -o remount,ro,bind / /mnt/readonlyfs
$ cd /mnt/readonlyfs && touch test.txt  # just to be sure
touch: cannot touch ‘test.txt’: Read-only file system
```

```bash
$ cd ~
$ dotnet new console
  ... add the following code in Main(): ...
  System.IO.File.Delete ("/mnt/readonlyfs/test.txt");
$ dotnet run

Unhandled Exception: System.IO.IOException: Read-only file system
   at System.IO.UnixFileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at test.Program.Main(String[] args) in /home/alexander/dev/test/Program.cs:line 10
```

The same code works with Mono, i.e. throws no exception on the non-existent file as specified by MSDN: https://msdn.microsoft.com/en-us/library/system.io.file.delete(v=vs.110).aspx:
> If the file to be deleted does not exist, no exception is thrown.

---

Importantly, it also works with .NET Core/.NET Framework on Windows when you create a new partition and use `diskpart` to set it to read-only via `ATTRIBUTES VOLUME SET READONLY`.

.NET Core version (same on Linux/Windows):

```bash
$ dotnet --info
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0-preview1-005977/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

/cc @JeremyKuhne

**Comment by JeremyKuhne** [comment]
Need to check for exists first. 

[Mono delete code](https://github.com/mono/mono/blob/010fcfb9ecfef1654b415dbb909a01148a89e827/mono/metadata/w32file-unix.c#L2495)
[Mono unlink code](https://github.com/mono/mono/blob/010fcfb9ecfef1654b415dbb909a01148a89e827/mono/metadata/w32file-unix.c#L299)

**Comment by JeremyKuhne** [comment]
[Our code](https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/UnixFileSystem.cs#L148)

**Comment by akoeplinger** [comment]
Please note that the current Mono code in master has a bug/regression, which is what lead us to discover the issue. Fix is: https://github.com/mono/mono/pull/5082.

**Comment by JeremyKuhne** [comment]
> Please note that the current Mono code in master has a bug/regression

Noted- I wanted to illustrate that you're explicitly checking for exists. Our fix will be `if(!File.Exists()) return;` I assume.

**Comment by akoeplinger** [comment]
@JeremyKuhne where do you see that? From what I can see we simply call unlink().

**Comment by JeremyKuhne** [comment]
@akoeplinger Never mind, apparently I was seeing things last night. Just looked again. :)

**Comment by danmosemsft** [comment]
@JeremyKuhne is this intentionall in the 2.0 milestone? The PR is marked 2.1. I wonder whether they would take this fix at this point.

**Comment by Petermarcu** [comment]
@danmosemsft, this is still sitting in the 2.0.0 milestone. Is it coming through or moved out to 2.1?

**Comment by Petermarcu** [comment]
@JeremyKuhne If this can come in tomorrow, given that its really isolated and low risk, I think we can take it for 2.0. If not, lets just move this issue out to 2.1.

**Comment by danmosemsft** [comment]
When I talked to @JeremyKuhne he indicated 2.1. I agree because this seems such a corner case.
