### ISSUE TITLE
RemoteExecutorTestBase on UAP waits for the remote process

### ISSUE THREAD

**Issue by kouvel** [dotnet/corefx#21275]
It looks like the UAP implementation of RemoteInvoke waits for the remote process to finish before continuing, blocking the main process. Some tests are timing out due to this, and others that are expecting concurrent processing are being run sequentially.

Disabled tests:
- https://github.com/dotnet/corefx/blob/master/src/System.Threading/tests/EventWaitHandleTests.cs#L179
- https://github.com/dotnet/corefx/blob/master/src/System.Threading/tests/SemaphoreTests.cs#L283

**Comment by stephentoub** [comment]
cc: @tarekgh

**Comment by tarekgh** [comment]
I moved this to the future as I an not sure we'll get to this in the next couple of weeks. I have replied @kouvel email regarding this and suggested to work around these tests by using Tasks for now till we allow the remote executor to be async.

**Comment by danmosemsft** [comment]
@kouvel since yo moved the milestone back .. .are you doing this for ZBB? do you have an eta?

**Comment by kouvel** [comment]
Yea I was going to attempt to get it done today/tomorrow

**Comment by kouvel** [comment]
If not I'll just move it to future, I don't think it's critical for UWP6

**Comment by tarekgh** [comment]
if @kouvel couldn't get to it, I'll try to find some time next week to do it.

**Comment by danmosemsft** [comment]
AnonymousPipeTest_CrossProcess test is disabled with this issue also
```
        [Fact]
        [ActiveIssue("https://github.com/dotnet/corefx/issues/21275", TargetFrameworkMonikers.Uap)]
        public void PingPong()
```

**Comment by kouvel** [comment]
PR is up but no go yet

**Comment by safern** [comment]
The change was reverted as it was causing CI failures.

**Comment by ViktorHofer** [comment]
With https://github.com/dotnet/corefx/pull/31260 we are now executing uap remote code in separate processes. As the uap runner now support multi-instancing this shouldn't happen anymore. I'll re-activate the disabled tests.
