### ISSUE TITLE
WindowsIdentity.IsAuthenticated is false when running in an AppContainer

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#21282]
Tracking special-casing UWP in NegotiateStream_StreamToStream_Authentication_Success and NegotiateStream_StreamToStream_Authentication_TargetName_Success.
Since UAPAOT tests are not running in an AppContainer testing it will not exhibit the same problems. Fixing this is tracked by #18760.

I've narrowed the behavior difference to WindowsIdentity.IsAuthenticated when running in UAP mode, within an AppContainer.

**Comment by CIPop** [comment]
@bartonjs /cc @danmosemsft I've narrowed the behavior difference to `WindowsIdentity.IsAuthenticated` only when running in UAP mode, within an AppContainer.

Comparing Networking ETW traces between .Net Core and .Net UAP I found that we're getting the same results back from the Nego SSPI APIs. The [NegotiateStream_StreamToStream_Authentication_Success](https://github.com/dotnet/corefx/blob/8dd8794a65d11903cf75830f69c597109cf499d0/src/System.Net.Security/tests/FunctionalTests/NegotiateStreamStreamToStreamTest.cs#L68)  test is getting the client identity from the server-side NegotiateStream. Internally, this is a `WindowsIdentity` object exposed trough an `IIdentity` interface.

At a later time, the test is asserting that the client `IIdentity` is authenticated which ends up calling [WindowsIdentity.IsAuthenticated](https://github.com/dotnet/corefx/blob/8dd8794a65d11903cf75830f69c597109cf499d0/src/System.Net.Security/tests/FunctionalTests/NegotiateStreamStreamToStreamTest.cs#L74). 

Running in .Net Core mode, I see that the [PInvoke to CheckTokenMembership](https://github.com/dotnet/corefx/blob/6da4eea7a090ef6166c04cc4c152b4f7bbb47074/src/System.Security.Principal.Windows/src/System/Security/Principal/WindowsIdentity.cs#L406) sets the `isMember` out parameter to `true` while in UAP mode it will set it to `false`. This pinvoke is called by [IsAuthenticated](https://github.com/dotnet/corefx/blob/6da4eea7a090ef6166c04cc4c152b4f7bbb47074/src/System.Security.Principal.Windows/src/System/Security/Principal/WindowsIdentity.cs#L372) to check for `SECURITY_AUTHENTICATED_USER_RID`.

**Comment by CIPop** [comment]
I verified that the package manifest has the following capabilities:

```
internetClient
internetClientServer
privateNetworkClientServer
codeGeneration
enterpriseAuthentication
sharedUserCertificates
documentsLibrary
musicLibrary
picturesLibrary
videosLibrary
removableStorage
appointments
contacts
userAccountInformation
```

**Comment by bartonjs** [comment]
@karelz / @danmosemsft Not sure who this should be assigned to.

**Comment by karelz** [comment]
@brentschmaltz this looks like your area of expertise. Can you please take a look?

@CIPop is it blocking your UWP work? Is it must have for UWP6.0?

**Comment by CIPop** [comment]
Yes, this is blocking e2e Negotiate/Kerberos enterprise scenarios.

**Comment by karelz** [comment]
@CIPop please work directly with @brentschmaltz, he is the only expert around on identity
cc @DavidGoll

**Comment by CIPop** [comment]
Thanks @karelz.

@brentschmaltz, please let me know if you need more information.

**Comment by CIPop** [comment]
@brentschmaltz, @karelz /cc: @PeterSmithRedmond, @DavidGoll 

Any updates on `WindowsIdentity` status for UWP? This is blocking UWP release.

**Comment by brentschmaltz** [comment]
@CIPop what is the simplest repo?

**Comment by CIPop** [comment]
@brentschmaltz Running the [test](https://github.com/dotnet/corefx/blob/8dd8794a65d11903cf75830f69c597109cf499d0/src/System.Net.Security/tests/FunctionalTests/NegotiateStreamStreamToStreamTest.cs#L73) in UAP (F5 Debug mode) without the platform detection branch will make the test fail:


```C#
                //if (PlatformDetection.IsUap)
                //{
                //    // TODO #21282: UWP AppContainer issue - clientIdentity.IsAuthenticated == false.
                //    Assert.Equal(false, clientIdentity.IsAuthenticated);
                //}
                //else
                //{
                    Assert.Equal(true, clientIdentity.IsAuthenticated);
                //}
```

**Comment by brentschmaltz** [comment]
@CIPop a couple lines above does this assert fail?

               Assert.Equal("NTLM", clientIdentity.AuthenticationType);

**Comment by CIPop** [comment]
No. That works the same in all cases.

**Comment by CIPop** [comment]
I've talked with @brentschmaltz offline and we believe the fix is to call [CheckTokenMembershipEx ](https://msdn.microsoft.com/en-us/library/windows/desktop/hh448479(v=vs.85).aspx) passing the `CTMF_INCLUDE_APPCONTAINER` flag on uap only.

/cc @DavidGoll @davidsh This fix may not be testable in UAPAOC because of #18760.
