### ISSUE TITLE
Manually run multi-machine Enterprise test scenarios

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#21285]
- [ ] Several System.Net.Security can only be tested within a multi-machine environment. 
- [x] Manually re-enable and run tests disabled by the CI intermittent issue tracked by #16534

**Comment by tijoytom** [comment]
@CIPop Moving this Future since UWP6.0 is due in 4 weeks

**Comment by CIPop** [comment]
@tijoytom @karelz @DavidGoll I'm moving this back to UWP6.0 based on the offline discussion. This is required to ensure that Enterprise Authentication (Kerberos/NTLM) as well as client/server certificates scenarios actually work in UWP. 
1-box/CI/Helix testing do not have any coverage for these tests requiring special environment Capabilities.

**Comment by karelz** [comment]
Closing as it doesn't track any product/test issue. List of sign off criterias can be tracked externally.
