### ISSUE TITLE
Crashes on shutdown from EventListener in various test projects

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#21306]
We're continuing to be plagued by failures like this in netfx runs:
```
  System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
     at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
     at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
     at System.Diagnostics.Tracing.EventListener.DisposeOnShutdown(Object sender, EventArgs e)
```
e.g. https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/102/.  If we're not already on a version of netfx that includes the fix, we need to move CI to a newer version.  And if we are on a sufficiently new version, then apparently the issue isn't fixed.

**Comment by mmitche** [comment]
@stephentoub Will be fixed here: https://github.com/dotnet/dotnet-ci/pull/717

**Comment by stephentoub** [comment]
Thanks, Matt.

**Comment by danmosemsft** [comment]
@mmitche can we close this now then

**Comment by stephentoub** [comment]
I'll close it and we can re-open if we see it again. Thanks.
