### ISSUE TITLE
Corefx member named ProcessStartInfo.Environment instead of EnvironmentVariables

### ISSUE THREAD

**Issue by ryaneliseislalom** [dotnet/corefx#2131]
Steps:
Inspect signature for System.Diagnostics.ProcessStartInfo.Environment

Expected result:
Existing .NET framework signature looks like this:
public StringDictionary EnvironmentVariables { get; }
based on https://msdn.microsoft.com/en-us/library/system.diagnostics.processstartinfo.environmentvariables(v=vs.110).aspx

Actual result:
corefx ProcessStartInfo looks like this:
public IDictionary<string, string> Environment

Granted we probably want to use generic types for the return, so IDictionary is good. Even so, the name of the member should still be called EnvironmentVariables instead of Environment.

**Comment by stephentoub** [comment]
The .NET Framework has both:
https://msdn.microsoft.com/en-us/library/system.diagnostics.processstartinfo.environment(v=vs.110).aspx
