### ISSUE TITLE
Socket multicast will hang in AppContainer with loopback interface

### ISSUE THREAD

**Issue by caesar-chen** [dotnet/corefx#21327]
The description in #21018 is not correct. The test will hang if loopback interface is chosen.

Since there is no problem using other interfaces for socket multicast, we move this issue to future.

@davidsh @CIPop

**Comment by caesar1995** [comment]
This issue is related to app container (UWP work). As discussed, I need management's confirmation on the Milestone. (Because I want to close UWP Sockets epic #20135, and this is unfinished work)

@DavidGoll @karelz @davidsh
