### ISSUE TITLE
IdnMappingIdnaConformanceTests.GetAscii_Invalid failing on our Nano image

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#21332]
Don't know why this just started. We may need to remove this line from the IdnaTest_6.txt file. Unfortunately the test doesn't log what line it's on.

```
Windows.10.Nano.Amd64.Open-Debug-x64
Unhandled Exception of Type Xunit.Sdk.ThrowsException
Message :
Assert.Throws() Failure\r\nExpected: typeof(System.ArgumentException)\r\nActual:   (No exception was thrown)
Stack Trace :
   at System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetAscii_Invalid()
```

OS=Microsoft Windows 10.0.14393 OSVer=Microsoft Windows NT 10.0.14393.0 OSArch=X64 Arch=X64 Framework=.NET Core 4.6.00001.0

**Comment by tarekgh** [comment]
CC @ViktorHofer

**Comment by tarekgh** [comment]
This is tracked by #21344 closing it here.
