### ISSUE TITLE
System.IO.Filesystem  Directory.CreateDirectory not working in .NET Core

### ISSUE THREAD

**Issue by radenkozec** [dotnet/corefx#2134]
Hi there.
I am trying to use Directory.CreateDirectory in .NET Core.
It seams it is not supported.
I am using "System.IO.FileSystem": "4.0.0-beta-22816" 
http://stackoverflow.com/questions/31003013/directory-createdirectory-not-exists-in-net-core

Any help please?

**Comment by khellang** [comment]
Have you made sure the package itself has been restored? Did you do this through VS? Have you tried running `dnu restore`? Also, you could try using `4.0.0-beta-*` instead.

**Comment by radenkozec** [comment]
Yes, the package is successfully restored. See the picture at stackoverflow question.

**Comment by mellinoe** [comment]
You may also want to try posting on the asp.net repository, as they will be more familiar with their project system and how to fix your specific problem.

**Comment by stephentoub** [comment]
@radenkozec, are you hitting this issue with the sources currently in this repo?  It's working correctly both in the CI builds/tests and for me in my local repo.

**Comment by radenkozec** [comment]
![working](https://cloud.githubusercontent.com/assets/3481625/8412671/978b8c10-1e8b-11e5-99d5-23d9345bd2a9.png)
@stephentoub  I can confirm this is not a issue. Problem is that when I mouse over CreateDirectory it says it not supported like in screenshot attached. However when I call this method it works even on .NET Core. I will close this issue now. Thanks for help and sorry for false report this time.

**Comment by svick** [comment]
@radenkozec Isn't the erroneous mouseover a bug? (Though I'm not sure where exactly is that information coming from.)

**Comment by khellang** [comment]
If the dependencies had been declared correctly, it would show "Available" on both `dnx451` and `dnxcore50` :smile:

**Comment by khellang** [comment]
What's even more confusing is that `dnx451` is called "ASP.NET 5.0" and `dnxcore50` is called "ASP.NET Core 5.0" :confused:

**Comment by radenkozec** [comment]
Hm I don't know is that popup from VisualStudio or Resharper?
