### ISSUE TITLE
System.ComponentModel.Tests.CategoryAttributeTests.Ctor_Category failed in ci

### ISSUE THREAD

**Issue by v-haren** [dotnet/corefx#21356]
failed test: System.ComponentModel.Tests.CategoryAttributeTests.Ctor_Category

detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu16.10_debug/2836/testReport/System.ComponentModel.Tests/CategoryAttributeTests/Ctor_Category_category____Misc____expectedIsDefaultAttribute__True_/

MESSAGE:
~~~
Assert.Equal() Failure
Expected: True
Actual: False
~~~
STACK TRACE:
~~~
at System.ComponentModel.Tests.CategoryAttributeTests.Ctor_Category(String category, Boolean expectedIsDefaultAttribute) in /mnt/j/workspace/dotnet_corefx/master/ubuntu16.10_debug/src/System.ComponentModel.Primitives/tests/CategoryAttributeTests.cs:line 34
~~~

**Comment by danmosemsft** [comment]
must be racing.

**Comment by ericstj** [comment]
Hit this again in https://github.com/dotnet/corefx/pull/23168.
```
13:58:36   Running tests... Start time: 13:58:35.44
13:58:36         Expected: True
13:58:36         Actual:   False
13:58:36         Stack Trace:
13:58:36           D:\j\workspace\windows-TGrou---2a8f9c29\src\System.ComponentModel.Primitives\tests\CategoryAttributeTests.cs(35,0): at System.ComponentModel.Tests.CategoryAttributeTests.Ctor_Category(String category, Boolean expectedIsDefaultAttribute)
```
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/2262/consoleFull

This is on NETFx which I suspect doesn't have your fix https://github.com/dotnet/corefx/pull/21369.  Perhaps the test should be disabled for desktop?

**Comment by ericstj** [comment]
Hit this again: https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/2736/consoleFull.

I believe the test should be disabled on desktop since it doesn't have your fix.  Either that or fix the test.
