### ISSUE TITLE
[Regression] Previous valid NTFS paths are considered invalid in .NET Framework 4.6.2/.NET Core

### ISSUE THREAD

**Issue by davkean** [dotnet/corefx#21358]
1. Run the following code:

``` C# 
using System;
using System.IO;

class Program
{
    static void Main(string[] args)
    {
        for (char c = (char)0; c < Char.MaxValue; c++)
        {
            if (char.IsWhiteSpace(c) && CanCreateFile(c))
            {
                Console.WriteLine($"Valid Path Char: {ToCodePoint(c)} CanCreateFile: true CanGetFullPath: {CanGetFullPath(c)}");
            }
        }
    }

    private static string ToCodePoint(char c)
    {
        return string.Format("\\u{0:x4} ", (int)c);
    }

    private static bool CanGetFullPath(char c)
    {
        try
        {
            Path.GetFullPath(c.ToString());
            return true;
        }
        catch (ArgumentException)
        {
        }

        return false;
    }

    private static bool CanCreateFile(char c)
    {
        try
        {
            string path = Path.Combine(@"c:\Temp", c.ToString());

            File.WriteAllText(path, "");
        }
        catch (DirectoryNotFoundException)
        {   // Handle ' ' and '\t', etc 
            return false;
        }
        catch (ArgumentException)
        {
            return false;
        }

        return true;
    }
}
``` 

**Expected (behavior in .NET Framework 4.6.1 and below):**
```
Valid Path Char: \u1680  CanCreateFile: true CanGetFullPath: True
Valid Path Char: \u2000  CanCreateFile: true CanGetFullPath: True
Valid Path Char: \u2001  CanCreateFile: true CanGetFullPath: True
Valid Path Char: \u2002  CanCreateFile: true CanGetFullPath: True
Valid Path Char: \u2003  CanCreateFile: true CanGetFullPath: True
Valid Path Char: \u2004  CanCreateFile: true CanGetFullPath: True
Valid Path Char: \u2005  CanCreateFile: true CanGetFullPath: True
Valid Path Char: \u2006  CanCreateFile: true CanGetFullPath: True
Valid Path Char: \u2007  CanCreateFile: true CanGetFullPath: True
Valid Path Char: \u2008  CanCreateFile: true CanGetFullPath: True
Valid Path Char: \u2009  CanCreateFile: true CanGetFullPath: True
Valid Path Char: \u200a  CanCreateFile: true CanGetFullPath: True
Valid Path Char: \u2028  CanCreateFile: true CanGetFullPath: True
Valid Path Char: \u2029  CanCreateFile: true CanGetFullPath: True
Valid Path Char: \u202f  CanCreateFile: true CanGetFullPath: True
Valid Path Char: \u205f  CanCreateFile: true CanGetFullPath: True
Valid Path Char: \u3000  CanCreateFile: true CanGetFullPath: True
```

**Actual (.NET Framework 4.6.2/.NET Core):**
```
Valid Path Char: \u1680  CanCreateFile: true CanGetFullPath: False
Valid Path Char: \u2000  CanCreateFile: true CanGetFullPath: False
Valid Path Char: \u2001  CanCreateFile: true CanGetFullPath: False
Valid Path Char: \u2002  CanCreateFile: true CanGetFullPath: False
Valid Path Char: \u2003  CanCreateFile: true CanGetFullPath: False
Valid Path Char: \u2004  CanCreateFile: true CanGetFullPath: False
Valid Path Char: \u2005  CanCreateFile: true CanGetFullPath: False
Valid Path Char: \u2006  CanCreateFile: true CanGetFullPath: False
Valid Path Char: \u2007  CanCreateFile: true CanGetFullPath: False
Valid Path Char: \u2008  CanCreateFile: true CanGetFullPath: False
Valid Path Char: \u2009  CanCreateFile: true CanGetFullPath: False
Valid Path Char: \u200a  CanCreateFile: true CanGetFullPath: False
Valid Path Char: \u2028  CanCreateFile: true CanGetFullPath: False
Valid Path Char: \u2029  CanCreateFile: true CanGetFullPath: False
Valid Path Char: \u202f  CanCreateFile: true CanGetFullPath: False
Valid Path Char: \u205f  CanCreateFile: true CanGetFullPath: False
Valid Path Char: \u3000  CanCreateFile: true CanGetFullPath: False
```

What Unicode considers as whitespace (via String.IsNullOrWhitespace) does not match what NTFS considers as whitespace..

**Comment by davkean** [comment]
tag @JeremyKuhne

**Comment by davkean** [comment]
Can't find the source of path in CoreFX/CoreCLR, but basically, [this check](http://referencesource.microsoft.com/#mscorlib/system/io/path.cs,499) should probably be IsNullOrEmpty - I don't remember us ever doing a full unicode whitespace check. If you look at the comment on LongPathHelper.s_trimEndChars (can't link because it's not on reference source), it calls this out.

**Comment by karelz** [comment]
@davkean you marked it as regression - regression against what and in which version(s)? (at least to your current knowledge)

**Comment by danmosemsft** [comment]
@JeremyKuhne

**Comment by JeremyKuhne** [comment]
Thanks @davkean! I agree that we should IsNullOrEmpty here. In trying to get exceptions identical I was apparently a little over aggressive. :/

To be clear- this is only trying to normalize paths of just whitespace. Notably, if you tack them on the end of another path we would end up trimming the whitespace (at least in _some_ cases). We're removing the trimming in CoreFX completely and I'm intending to do the same for NetFX- which would "fix" this. (Note that Windows itself will trim "normal" spaces off the end.)

For NetFX, if you're dependent on exact behavior you can set the [UseLegacyPathNormalization](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/mitigation-path-normalization) quirk if you're targeting 4.6.2 or later. That will prevent using some of the new functionality, such as device (`\\?\`, `\\.\`) paths.

I'll try to get a new quirk into NetFX as soon as I can find an open window. I'm guessing "BlockWhitespaceOnlyPathsUnderNewNormalization" at this point. Expect a "TrimTrailingWhitespaceUnderNewNormalization" as well.

**Comment by davkean** [comment]
@karelz The before and after lists all the versions.

**Comment by karelz** [comment]
@davkean ah, sorry, I missed that :(. Thanks!
It doesn't sound like 2.0-critical (which is what I was after).

**Comment by danmosemsft** [comment]
@JeremyKuhne does any work remain here, after the above changes?

**Comment by JeremyKuhne** [comment]
Closing and marking the relevant PR as port consider.
