### ISSUE TITLE
Reenable build multithreading once dnx issues are fixed

### ISSUE THREAD

**Issue by mmitche** [dotnet/corefx#2135]
Once dnx concurrency issues are fixed, reenable project multithreading.  Currently disabled in CI using /p:SerializeProjects=false.

**Comment by joshfree** [comment]
is there a tracking bug in one of the aspnet repos for the blocking bug(s)?

/cc @danroth27

**Comment by joshfree** [comment]
Is this issue still relevant?

**Comment by danroth27** [comment]
Don't know - @muratg @davidfowl ?

**Comment by muratg** [comment]
Now everything is in dotnet CLI instead of dnx, I'm not sure if this is relevant or not.
