### ISSUE TITLE
.NET Core 2.0 Preview 1 - Could not load type 'System.Security.Permissions.ReflectionPermission'

### ISSUE THREAD

**Issue by rschiefer** [dotnet/corefx#21359]
Testing out Preview 2 and some Nuget packages.  One required adding the System.Security.Permissions Nuget package to get past the Permissions assembly not being found.

https://www.nuget.org/packages/System.Security.Permissions/4.4.0-preview1-25305-02

But now I'm getting the following error:

System.TypeLoadException occurred
  HResult=0x80131522
  Message=Could not load type 'System.Security.Permissions.ReflectionPermission' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Newtonsoft.Json.Serialization.JsonTypeReflector.get_DynamicCodeGeneration()
   at Newtonsoft.Json.Serialization.JsonTypeReflector.get_ReflectionDelegateFactory()
   at Newtonsoft.Json.Serialization.DefaultContractResolver.GetDefaultCreator(Type createdType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(JsonContract contract)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateDictionaryContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
...

Is this a known issue?

**Comment by karelz** [comment]
@bartonjs should we route it to Serialization?

**Comment by bartonjs** [comment]
I don't know if it's a problem with the serializer assuming mscorlib, or the input (specifying mscorlib).

Since we don't have an mscorlib there certainly can't be a ReflectionPermission type in it :smile:.  Either way, I don't think this is our bug (or, if it is, it's a big "do we have a story for serializing netfx to corefx?" -- maybe we do build a typeforward library called mscorlib somewhere?)

**Comment by karelz** [comment]
@danmosemsft @morganbr @stephentoub @weshaggard what are your thoughts?
Do we plan to support Framework <-> Core serialization for the types we chose to support serialization on Core?

cc @marek-safar

**Comment by danmosemsft** [comment]
Yes, we will support serialization between 4.6.2+ and Core 2.0 for these types https://gist.github.com/morganbr/2a9901b12f1d342285694e69983a12d0. We hope to support 4.5.2+ as well. We explicitly are not supporting binary serialization of any form for other types, but we're open to feedback...

**Comment by danmosemsft** [comment]
That list should be documented somewhere properly...

**Comment by weshaggard** [comment]
@rschiefer can you tell me which version of Microsoft.NETCore.App you are using in your application? It will contain an mscorlib shim and I would expect it to have a type-forward for ReflectionPermission which should be in the System.Security.Permissions library that you added the extra package reference for, which is correct although you are referencing the preview1 version of that package, I doubt that is the issue though.

**Comment by rschiefer** [comment]
Sorry for the delay.  

@karelz - Haven't tried the meta package.  Which one should I try?

@weshaggard - My target framework is "netcoreapp2.0".  Is that what you need?

The source is on GitHub:

https://github.com/rschiefer/SeleniumInDotNetCore2P1

**Comment by weshaggard** [comment]
@rafidka what version of the tools are you using? dotnet --info

Also could you look under your obj folder for the project.assets.json file and look for what version of Microsoft.NETCore.App it saying you are using there?

**Comment by rschiefer** [comment]
> .NET Command Line Tools (2.0.0-preview1-005977)
> 
> Product Information:
>  Version:            2.0.0-preview1-005977
>  Commit SHA-1 hash:  414cab8a0b
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.15063
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\
> 
> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 2.0.0-preview1-002111-00
>   Build    : 1ff021936263d492539399688f46fd3827169983

From project.assets.json - "Microsoft.NETCore.App/2.0.0-preview1-002111-00"

**Comment by weshaggard** [comment]
OK you are using preview1 not preview2, but at any rate I looked at the mscorlib.dll shim in the package and it does correctly have a type-forward for ReflectionPermission and I verified the type definition exists in System.Security.Permissions library you referenced so something else must be wrong. 

I tried your test project at https://github.com/rschiefer/SeleniumInDotNetCore2P1 and it doesn't demonstrate the problem could you update that project just enough to repro the exception?

**Comment by morganbr** [comment]
This is the Json.NET serializer, not BinaryFormatter. We didn't make any special guarantees about Json.NET or any other 3rd-party serializer's desktop/Core compatibility.

**Comment by rschiefer** [comment]
@weshaggard I updated the project to correctly reference the chrome driver.  Just run the unit test from VS or run "dotnet test" to see the error.

**Comment by ViktorHofer** [comment]
That's not related to binary serialization. Json.NET serializes public members (into json) and only calls private methods for serialization/deserialization. As the API surface (and implementation) of .NET Core 2.0 is similar to netfx461 external serialization libraries like JSON.NET hopefully _will_ just work.

**Comment by ViktorHofer** [comment]
@danmosemsft @morganbr the list still contains NameValueCollection so I assume it's not the most recent one.

**Comment by weshaggard** [comment]
@rschiefer I was able to repro the issue and you are hitting an unfortunate but in our preview1 tooling. The issue turns out to be cause because the tools pick the net461 version of System.Security.Permissions instead of the netstandard2.0 version. This causes issues where we get cycles in the type graph and it fails to load the type. 

To fix that problem you could set DisableImplicitPackageTargetFallback to true in your project however that will then break other packages you are restoring :( 

@livarcocc do you know if we are removing https://github.com/livarcocc/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.BeforeCommon.targets#L117 and fixing this in the preview 2 tooling?

**Comment by rschiefer** [comment]
Thanks for digging deeper on this @weshaggard! 

I look forward to a fix.

**Comment by Petermarcu** [comment]
@livarcocc, Is this fixed or does it need to move to the SDK repo to be tracked as a 2.0.0 issue?

**Comment by rschiefer** [comment]
After installing the .NET Core SDK 2.0.0 Preview 2 build 006497 I can confirm the issue is resolved.  Thanks for the help everyone!

**Comment by Petermarcu** [comment]
Thanks!

**Comment by jheidlage1222** [comment]
So I installed the netcore2.0 SDK and runtime as they've been officially released now and I'm encountering the same error as described in this thread.  I did a write up of what I did to fix it (largely your advice here) but I just wanted to throw it out there that this issue may have re-emerged in the official release.
https://github.com/rschiefer/SeleniumInDotNetCore2P2/issues/1

**Comment by Cronan** [comment]
I can confirm I'm seeing the issue:

> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Permissions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
> 
>    at Newtonsoft.Json.Serialization.JsonTypeReflector.get_DynamicCodeGeneration()
>    at Newtonsoft.Json.Serialization.JsonTypeReflector.get_ReflectionDelegateFactory()
>    at Newtonsoft.Json.Serialization.DefaultContractResolver.GetDefaultCreator(Type createdType)
>    at Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(JsonContract contract)
>    at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
>    at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
>    at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)


> dotnet --info
> .NET Command Line Tools (2.0.0)
> 
> Product Information:
>  Version:            2.0.0
>  Commit SHA-1 hash:  cdcd1928c9
> 
> Runtime Environment:
>  OS Name:     rhel
>  OS Version:  7
>  OS Platform: Linux
>  RID:         rhel.7-x64
>  Base Path:   /usr/share/dotnet/sdk/2.0.0/
> 
> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 2.0.0
>   Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by karelz** [comment]
@jheidlage1222 can you provide more details? If it repros on final version, we want to know more about it. Thanks!

**Comment by jheidlage1222** [comment]
@karelz What additional information do you need from me?  Did you read the post I linked to above?

**Comment by karelz** [comment]
I skimmed through your post earlier (and re-read it now again). Callstack would be helpful IMO.
I guess that the DLLs you are referencing are built against .NET Framework. It is quite possible that they are in the category which won't "just work" on .NET Core ... the callstack should help us to tell more.
