### ISSUE TITLE
4 specific System.Drawing.Common tests have started failing regularily on Windows 10 release mode

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#21360]
- Ctor_InvalidIconHandle_SetsHandleToZero:
```
Unhandled Exception of Type Xunit.Sdk.ThrowsException
Message :
Assert.Throws() Failure\r\nExpected: typeof(System.ObjectDisposedException)\r\nActual:   (No exception was thrown)
Stack Trace :
   at System.Drawing.Tests.IconTests.Ctor_InvalidIconHandle_SetsHandleToZero()
```

- Save_InvalidHandle_ThrowsCOMException
```
Unhandled Exception of Type Xunit.Sdk.ThrowsException
Message :
Assert.Throws() Failure\r\nExpected: typeof(System.Exception)\r\nActual:   (No exception was thrown)
Stack Trace :
   at System.Drawing.Tests.IconTests.Save_InvalidHandle_ThrowsCOMException()
```

- Size_GetFromInvalidHandle_ReturnsZeroSize
```
Unhandled Exception of Type Xunit.Sdk.EqualException
Message :
Assert.Equal() Failure\r\nExpected: {Width=0, Height=0}\r\nActual:   {Width=32, Height=32}
Stack Trace :
   at System.Drawing.Tests.IconTests.Size_GetFromInvalidHandle_ReturnsZeroSize()
```

- ToBitmap_InvalidHandle_ThrowsArgumentException
```
Unhandled Exception of Type Xunit.Sdk.ThrowsException
Message :
Assert.Throws() Failure\r\nExpected: typeof(System.ArgumentException)\r\nActual:   (No exception was thrown)
Stack Trace :
   at System.Drawing.Tests.IconTests.ToBitmap_InvalidHandle_ThrowsArgumentException()
```

**Comment by hughbe** [comment]
These tests all have something in common - the fact that the handle is invalid. I believe the handle they're using is `(IntPtr)100`.

I suppose what could have happened is that there is actually a valid icon at `(IntPtr)100`? I'm really not sure. Any ideas?

**Comment by hughbe** [comment]
Obviously the fact that these only fail in release mode is interesting. Also, Windows 10 only is odd

**Comment by ViktorHofer** [comment]
If they aren't fixable right now or take time then I suggest to disable them for now so that we get back to a clean CI for Release builds. I could sign that of.

**Comment by hughbe** [comment]
Will submit PR

**Comment by hughbe** [comment]
@mellinoe the tests are as follows:

```
[ConditionalFact(nameof(PlatformDetection) + "." + nameof(PlatformDetection.IsNotWindowsNanoServer))]
[ActiveIssue(21360)]
public void Ctor_InvalidIconHandle_SetsHandleToZero()
{
    using (Icon source = Icon.FromHandle((IntPtr)100))
    using (var icon = new Icon(source, 10, 10))
    {
        Assert.Throws<ObjectDisposedException>(() => icon.Handle);
    }
}
```

I haven't seen an handles that aren't over 6 digits, so chose a small number. I just chose the random number 100 which is probably inherently risky.
I think these tests are important as they show we don't cause AVs when we create an icon with an invalid handle. 

Note that my working assumption is these tests failed is because there is an Icon with the handle 100. A 
potential fix could be to do the following

```
private static IntPtr GetUnusedHandle()
{
    for (int i = 1; i < int.MaxValue; i++)
    {
        IntPtr handle = (IntPtr)i;
        Icon icon = Icon.FromHandle(handle);

        try
        {
            Size size = icon.Size;
        }
        catch (ObjectDisposedException)
        {
            return handle;
        }
    }
}
```

**Comment by mellinoe** [comment]
Hm. Do we know which line is causing the exception? There are a few native calls in `icon.Size`.

However, I'm not sure we should care that much about validating this behavior. The GDI+ calls we are using do not document what happens when you provide an invalid handle, so I'm not sure what the value is for us to validate that something specific happens when we do.

**Comment by hughbe** [comment]
So unfortunately, all assertions have lost their stack traces on Windows in .NET Core - I suspect due to #21079 

> However, I'm not sure we should care that much about validating this behavior.

I suspect you're right. These are just wrappers to GDI+. The reason why I added these tests is that they will always caused access violations with the mono implementation. GDI+ on Windows uses some kind of handle registration system internally and validates the handle, but libgdiplus (mono's shim for GDI+) just considers the handle as a pointer to an Icon in memory.

I wanted to make sure that this difference is documented and known - code that works on Windows can and will cause AV exceptions (immediate program crashes) on Mono.

What do you think?

**Comment by mellinoe** [comment]
I think we should just document the difference when the time comes. IMO, it is not unreasonable to cause an AV when a purposefully-invalid native handle is passed to function interpreting that handle. If we get to a place where we are able to make changes to libgdiplus (or re-implement parts of it in managed code), then we can try to harden that behavior.
