### ISSUE TITLE
Investigate/implement native shims for Unix functions

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#2137]
Our interop layer for accessing Unix functions (mostly libc) from managed code is currently fairly fragile, with hard-coded assumptions about the sizes of various types, with error values and various flag argument values needed to be copied into managed code per platform, etc.  Related to https://github.com/dotnet/corefx/issues/371, we should investigate (and subsequently implement as is appropriately) having a very thin native shim layer (one per managed library? one all-up?) that provides a P/Invokable and consistent surface area we can target, e.g. an ```open``` function in a System.IO.FileSystem.Native.so that in turn just calls the underlying libc's ```open``` function, doing whatever conversions are necessary between the standardized values/sizes/etc. expected by the managed code and what's actually used by the underlying platform.

**Comment by omariom** [comment]
Is the approach [SharpDX devs took](http://sharpdx.org/documentation/tools/sharpgen) applicable in this case? They generate a very thin interop layer right from  DirectX header files.

**Comment by nguerrera** [comment]
@omariom I think interop code generation, while definitely something to consider long term, is somewhat orthogonal to this. It could certainly help in theory, but as I dig into this it becomes apparent that there are lots of judgment calls to be made and that would either require very complex/configurable tooling or lots of opting out to manual mode. I think our best bet is to start with plain old hand-written C++ and C# code.

**Comment by nguerrera** [comment]
Making note that this issue is about the code changes needed to remove the fragility and reuse more managed code across unixes. Not covered here are:

1. Building the native shim code in the corefx repo (Issue #2301)
2. How to package and ship the shims (Issue #2302)

**Comment by nguerrera** [comment]
Still TODO after #2445:

- [ ] errno conversion
- [ ] declare fixed constants for stat file modes at shim layer

**Comment by janhenke** [comment]
Note that #2445 does not compile on FreeBSD. Is this still work in progress or are we supposed to submit a PR fixing the issue?

**Comment by nguerrera** [comment]
Please feel free to submit a PR and thanks for the help!

**Comment by janhenke** [comment]
Just a small problem. PR#2536

**Comment by bartonjs** [comment]
@nguerrera I know that there's still conversion to be done; but is there anything left for this particular issue? It seems like we have a plan forward, which sounds to me like the objective of this issue.

Just glancing through the open beta7 issues.

**Comment by nguerrera** [comment]
@bartonjs This is basically the only thing tracking the rest of the conversion so I'd leave it open.

**Comment by eerhardt** [comment]
I think with #4440 merged, this can now be closed, right? All of our native P/Invokes in CoreFX Unix code are to either native shims, libcoreclr, or OSX-specific functions.
