### ISSUE TITLE
SystemNative_SysConf Regression on Ubuntu 17.04

### ISSUE THREAD

**Issue by borgdylan** [dotnet/corefx#21386]
After further investigation of a bug that first manifested with powershell on Ubuntu 17.04, I have noticed that the SysConf method in System.Native is in some way allowing input that triggers its assertion. Running powershell in fact triggers this assertion immediately.

**Comment by karelz** [comment]
Which assertion?
Can you please provide (minimal) repro? (ideally just in C#, without PowerShell, it will help us isolate what is happening where)

**Comment by borgdylan** [comment]
@karelz The minimal repro would be to print out ```Environment.ProcessorCount```.

On my Intel Core i7 6900K I get teh following results:
net461(mono) : 16
netcoreapp1.0 (.NET Core 1.0.5): 16
netcoreapp1.1 (.NET Core 1.1.2): 16
netcoreapp2.0) (preview 2.0): assertion

The assertion is: 
```
dotnet: pal_io.cpp:758: int64_t SystemNative_SysConf(SysConfName): Assertion `false && "Unknown SysConfName"' failed.
```

**Comment by borgdylan** [comment]
This means that this is a regression that happened in the 2.0 dev timeframe which will be breaking anything taht moves/has moved to 2.0 that sues the Environmnt APIs that use the Linux ```sysconf``` system call (3 methods in total).

**Comment by borgdylan** [comment]
@karelz Where can I get .deb files for the latest internal 2.0 builds? I would like to test against them to see if the issue persists.

**Comment by karelz** [comment]
@joperezr @AlexGhiondea it looks like a regression, can you please check it / route it? Thanks!

**Comment by borgdylan** [comment]
Location of assertion in code: https://github.com/dotnet/corefx/blob/master/src/Native/Unix/System.Native/pal_io.cpp#L856

**Comment by borgdylan** [comment]
The code looks fine but I think that there is some issue in the P/Invoke. I never heard that you can use enums in methods called via P/Invoke. The ints could have been marshalled incorrectly (just an assumption).

**Comment by borgdylan** [comment]
What guarantees that the enum used has elements of type ```int32_t```, the same type of the constants that the method is comparing against?

**Comment by borgdylan** [comment]
Never mind, I looked at the code and the enum is indeed based on ```int32_t```.

**Comment by borgdylan** [comment]
The weirdest thing is that the assertion tries to output the offending input integer which does not make it out to my console.

**Comment by karelz** [comment]
Just to be super-clear: Did you try the minimal repro (printing out the value in C#)? If yes, can you post the code here? (should be simple and it is easy to copy-paste) .... Note: This is not be being lazy, I have seen way too many misunderstandings on basics in the past, that being super-clear is my second nature. Overall it avoids LOTS of wasted time :)

**Comment by borgdylan** [comment]
```
﻿using System;

class Program
{
    public static void Main(string[] args)
    {
        Console.WriteLine(Environment.ProcessorCount);
    }
}
```

**Comment by borgdylan** [comment]
```
﻿<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.0;net461</TargetFrameworks>
    <RuntimeIdentifiers>win7-x64;win7-x86;osx.10.10-x64;osx.10.11-x64;ubuntu.14.04-x64;ubuntu.16.04-x64;centos.7-x64;rhel.7.2-x64;debian.8-x64;fedora.23-x64;opensuse.13.2-x64</RuntimeIdentifiers>
    <RuntimeIdentifier Condition=" '$(TargetFramework)' == 'net461' ">win7-x86</RuntimeIdentifier>
    <AssemblyName>cstest</AssemblyName>
    <OutputType>Exe</OutputType>
    <Version>1.0.0.0</Version>
    
    <PackageId>cstest</PackageId>
    <RuntimeFrameworkVersion Condition=" '$(TargetFramework)' == 'netcoreapp2.0' ">2.0.0-preview1-002111-00</RuntimeFrameworkVersion>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net461' ">
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  
  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp2.0' ">
  </ItemGroup>

</Project>
```

**Comment by borgdylan** [comment]
To repro you will need the REAL ubuntu, WSL may behave differently.

**Comment by borgdylan** [comment]
Side note: I used the mono version of MSBuild to compile (had compiled and installed the latest version), I used .NET Core installed via APT from the official MSFT package feed.

**Comment by borgdylan** [comment]
ping

**Comment by joperezr** [comment]
cc: @danmosemsft @stephentoub who might be more familiar with this code. Looks like the only recent change that we have made around that was #17760 which doesn't really look like could have broken this.

**Comment by danmosemsft** [comment]
@janvorli can you help cast light on this perhaps?

**Comment by janvorli** [comment]
I don't see how the Interop.SysConf.cs could call the SystemNative_SysConf with a value different from the 1, 2 or 3 (values of the enum members) unless there is a bug in enum marshalling, but that would mean that it would fail on all Linuxes and not just Ubuntu 17.04.
@joperezr - the change #17760 was not in for the version of runtime that @borgdylan used - based on the assert message pasted above that doesn't contain the argument value.

@borgdylan since the assert happens in debug builds only, I assume you must have built corefx yourself. Is that true?

**Comment by janvorli** [comment]
@borgdylan I've just tested your app with the latest dotnet core sdk on Debian 9, which should be mostly equivalent to the Ubuntu 17.04 and it worked correctly (even though it is a release build and so the assert is not there, it would have returned -1 if it has failed, so I would be able to see that)

**Comment by borgdylan** [comment]
That happened with preview packages installed via apt-get. I do not know if they were debug builds or not.

**Comment by borgdylan** [comment]
The bug itself prevents me from building corefx myself.

**Comment by janvorli** [comment]
Could you please try the latest sdk tarball from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-linux-x64.tar.gz
?

You just untar it to any folder and run the dotnet from that folder.

**Comment by borgdylan** [comment]
I get the assertion nonetheless.
```
dotnet: pal_io.cpp:758: int64_t SystemNative_SysConf(SysConfName): Assertion `false && "Unknown SysConfName"' failed.
Aborted (core dumped)
```

**Comment by borgdylan** [comment]
The muxer reports version ```2.1.0-preview1-006567```.

**Comment by borgdylan** [comment]
The cli page on github states ```6576``` as the latest build. That means the linux CI is stuck in some way and has not been making new builds.

**Comment by janvorli** [comment]
The same here - and it works on Debian 9. Can you please share the commands you use to build and run the app?

**Comment by borgdylan** [comment]
```
msbuild /t:Restore
msbuild
 /home/dylan/Downloads/preview-dotnet/dotnet cstest.dll
```

The last command is run in the bin/Debug/netcoreapp2.0 directory. I was using the Mono variant of desktop MSBuild.

**Comment by borgdylan** [comment]
@janvorli Debian 9 has just been released and ubuntu 17.04 is still technically part of the Debian 8 family still using ICU 55.

**Comment by janvorli** [comment]
I was using 
```bash
dotnet new console
```
followed by editing the generated Program.cs to change the WriteLine to print Environment.ProcessorCount
And then
```bash
dotnet restore
dotnet build
dotnet run
```
If you get error during dotnet restore, you'll need to create NuGet.config file with the following contents in the same folder as your Program.cs:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
  </packageSources>
</configuration>
```
Can you try that?

**Comment by borgdylan** [comment]
I do not install the actual CLI as you did,  it does nor allow me from developing stuff for mono. Any solution that works with the CLI only is not a solution in my case.

**Comment by borgdylan** [comment]
Running a restore using the untared SDK prints out the assertion. The CLI itself is out of order on my machine.

**Comment by borgdylan** [comment]
To re-iterate what I said above. Things based on .NET Core 1.0.x/1.1.x did not exhibit this issue.

**Comment by janvorli** [comment]
@borgdylan I am not sure I understand. You don't need to install anything - you just untar the tarball and then use the dotnet from it. That's all.

**Comment by borgdylan** [comment]
I got the assertion when I did that.

**Comment by janvorli** [comment]
@borgdylan Would you be able to run the command that ends with the asserts under lldb or gdb, set a breakpoint at the SystemNative_SysConf and when the breakpoint is hit see what is in the RDI register, which carries the parameter?

**Comment by borgdylan** [comment]
How would I do that? I have both gdb and lldb but never used them directly.

**Comment by janvorli** [comment]
You would run:
`gdb --args dotnet new console`
When gdb starts, you'd enter
`b SystemNative_SysConf`
It would ask you
```
Function "SystemNative_SysConf" not defined.
Make breakpoint pending on future shared library load? (y or [n])
```
You'd enter `y`
Then you'd start the process by entering 
`r`
When you hit the breakpoint, the gdb would display something like:
```
Thread 14 "dotnet" hit Breakpoint 1, 0x00007ffff0313800 in SystemNative_SysConf ()
   from /home/janvorli/dotnet.tst/shared/Microsoft.NETCore.App/2.0.0-preview2-25319-02/System.Native.so
```
you'd enter 
`p/x $rdi`

And share the result.

That's it.

**Comment by borgdylan** [comment]
```
Thread 1 "dotnet" hit Breakpoint 1, 0x00007fffec3d4939 in SystemNative_SysConf
    () from /usr/local/lib/libSystem.Native.so
(gdb) p/x $rdi
$1 = 0x3
```

I used the runtime in the tar file.

**Comment by borgdylan** [comment]
I get the same value when using the runtime installed with apt-get. The break point address changes to ```0x00007ffff05d3939```.

**Comment by janvorli** [comment]
Ok, so the value is correct. Can you please try to enter `c` after hitting the breakpoint to see if it hits it again or asserts? Maybe only some of the calls are wrong, which would be even stranger.

**Comment by borgdylan** [comment]
```(gdb) c
Continuing.
dotnet: pal_io.cpp:758: int64_t SystemNative_SysConf(SysConfName): Assertion `false && "Unknown SysConfName"' failed.

Thread 1 "dotnet" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
58	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

```
(gdb) p/x $rdi
$2 = 0x2
```

**Comment by stephentoub** [comment]
This is the path when using the build from the tar?
/usr/local/lib/libSystem.Native.so

**Comment by janvorli** [comment]
Oh, thanks @stephentoub for noticing that! There is some probably outdated dotnet installation in the /usr/local/lib and its native library is being loaded. No wonder it fails.

**Comment by borgdylan** [comment]
I looked for that file and found it. I had a manual install at one point. I thought that dotnet set $LD_LIBRARY_PATH to force probe native stuff from its folder first like most other runtimes.

**Comment by borgdylan** [comment]
If I remove it, things work OK. What still perplexes me, why would it fail with 2.0 and not with 1.0/1.1?

**Comment by janvorli** [comment]
I guess the reason is that that library was from version 1.0 where this function worked differently than in 2.0

**Comment by borgdylan** [comment]
As it is a private library and that allows contract changes?

**Comment by janvorli** [comment]
The contract is just between the libSystem.Native.so and the managed part of CoreCLR that uses it. So they version together, including their contract.
