### ISSUE TITLE
[Arm64/Unix] Add ARM64 Native builds to CI

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/corefx#21384]

**Comment by sdmaclea** [comment]
@dotnet/arm64-contrib

**Comment by sdmaclea** [comment]
@wtgodbe FYI

**Comment by sdmaclea** [comment]
Native builds were integrated in #27656 and following, but there is no tests performed in CI yet.

**Comment by ViktorHofer** [comment]
Closing as fixed as adding tests to CI is tracked by https://github.com/dotnet/corefx/issues/21384
