### ISSUE TITLE
Visual Studio F5 tests should not break every single time there's an exception

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#21416]
If you try running tests from visual studio with F5 (I know it's not really supported), then the tests break *every single* time an exception is thrown in the product code.

This is annoying as these are all expected and are used in Assert.Throws tests

**Comment by stephentoub** [comment]
Do you have "Just My Code" enabled?
Are your exception settings set to break on throw for all CLR exception types?

**Comment by hughbe** [comment]
"Just my code" is enabled and I've unchecked "Common Language Runtime Exceptions", but VS still breaks. An example screenshot is below
![untitled](https://user-images.githubusercontent.com/1275900/27485482-0f3f9a10-5857-11e7-91ee-a272009ecc45.png)

Thanks btw

**Comment by stephentoub** [comment]
> "Just my code" is enabled

Have you tried disabling it?

**Comment by hughbe** [comment]
Well there you go, that seems to do the trick!
