### ISSUE TITLE
Quiet msbuild mode

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#21414]
Can we get a build mode, maybe `msbuild /T:BuildAndTest /P:Quiet=true` that gets rid of all the build logs and just prints out the test results?

This is useful to compare test failures and I don't really care about what's compiling.

**Comment by ViktorHofer** [comment]
Yes verbosity switch set to minimal: `/v:m`

**Comment by hughbe** [comment]
amazing! cheers
