### ISSUE TITLE
System.Net.WebSockets failed with Segfault on Ubuntu 16.10

### ISSUE THREAD

**Issue by v-haren** [dotnet/corefx#21434]
[xUnit] [ERROR] - No test reports found for the metric 'xUnit.Net' with the resolved pattern 'bin/**/testResults.xml'. Configuration error?.

detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_ubuntu16.10_release/87/consoleFull#136046166483554902-aff0-4799-9e92-0ada24ce2a06

**Comment by danmosemsft** [comment]
@v-haren the link above actually has this better information;
`/mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu16.10_release/Tools/Microsoft.CSharp.Core.targets(67,5): error MSB6006: "/mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu16.10_release/Tools/dotnetcli/dotnet" exited with code 139. [/mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu16.10_release/src/System.Net.WebSockets.Client/tests/System.Net.WebSockets.Client.Tests.csproj] `

This tells us thaat System.Net.WebSockets failed, and 139 means 'segmentation fault'

**Comment by v-haren** [comment]
failed again: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_release/122/consoleFull#136046166483554902-aff0-4799-9e92-0ada24ce2a06

**Comment by stephentoub** [comment]
> failed again: 

That's not a failure in this test (and that run was Win7)... build tools couldn't be restored, meaning nothing was actually built or run.

**Comment by danmosemsft** [comment]
Not actionable
