### ISSUE TITLE
[RS5] Reenable Console tests related to OutputEncoding

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#21483]
```
kernel32!SetConsoleOutputCP
kernel32!GetConsoleOutputCP
```

are currently not available on UAP but are on RS3, reenable once this is available

I believe our CIs already use RS3 although most of the people don't so let's keep them disabled until this works locally too

**Comment by danmosemsft** [comment]
@krwq the API's are available back to Windows 2000 so please go ahead and make the change now.
(RS3 is only relevant because of the WACK allow list, which runs on users machines not our machines)

**Comment by krwq** [comment]
@danmosemsft, how do I test locally if those tests actually pass without RS3? Can I locally update WACK allow list?

**Comment by danmosemsft** [comment]
@krwq when you build the src folder as uap, it flags anything that isn't in WACK and isn't already in the src\PinvokeAnalyzerExceptionList.analyzerdata.uap baseline file.

If you want to actually test functionality on RS3 then you have to have RS3. We'll probably need to think about how we're going to protect those tests with a check for RS3 else tests will fail for many other peopl,e.

**Comment by krwq** [comment]
@danmosemsft can we leave this disabled until we figure this out? this will interupt local workflow - you would usually expect local tests to pass.

Is there possibly any reliable way we could detect that we are on RS3 and skip the tests based on that?

**Comment by danmosemsft** [comment]
There is already code like this in PlatformDetection.cs
```c#
public static bool IsWindows10Version1703OrGreater => IsWindows &&
            GetWindowsVersion() == 10 && GetWindowsMinorVersion() == 0 && GetWindowsBuildNumber() >= 15063;
```

I'm not sure what 1703 means, but you should be able to make another property like this. 14393 is RS1. 15063 is RS2. The RS3 build that Helix is currently using is `16215.1000.amd64fre.rs_prerelease.170603-1840_Client_Enterprise_en-US `.
 
Some other info -- 
https://support.microsoft.com/en-us/help/4000825 
https://support.microsoft.com/en-us/help/4018124/windows-10-update-history

**Comment by krwq** [comment]
I have checked on 16227 and API was not available

**Comment by krwq** [comment]
Reopen or recreate when this is unblocked https://github.com/dotnet/corefx/pull/21594

**Comment by krwq** [comment]
@danmosemsft this will likely get fixed in RS4, should we change label to UWP.after6.0?

**Comment by tarekgh** [comment]
if the fix will come in RS4 then move it to the future milestone as we cannot do anything now.
