### ISSUE TITLE
System.Threading.Tasks.Tests.TaskRtTests_Core.RunTaskWaitAllTests [FAIL]

### ISSUE THREAD

**Issue by Diego-Perez-Botero** [dotnet/corefx#21489]
I'm hitting this test failure in multiple flavors while running outerloop tests as part of #21466:

- OuterLoop netcoreapp Windows_NT Release x64 ([results](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_release_prtest/29/))
- OuterLoop netcoreapp Windows_NT Debug x64 ([results](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_debug_prtest/134/))
- OuterLoop netcoreapp Ubuntu16.10 Debug x64 ([results](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_ubuntu16.10_debug_prtest/20/))
- OuterLoop netcoreapp OSX10.12 Debug x64 ([results](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_osx_debug_prtest/56/))

> MESSAGE:
> Assert.Equal() Failure\nExpected: (null)\nActual: tasks
> +++++++++++++++++++
> STACK TRACE:
> at System.AssertExtensions.Throws[T](String paramName, Action action) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_debug_prtest/src/Common/tests/System/AssertExtensions.cs:line 48 at System.Threading.Tasks.Tests.TaskRtTests_Core.RunTaskWaitAllTests() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_debug_prtest/src/System.Threading.Tasks/tests/Task/TaskRtTests_Core.cs:line 1326

**Comment by stephentoub** [comment]
I just checked in a fix.
