### ISSUE TITLE
WinRtToNetFxStreamAdapter.Flush seems to be blocked when waiting for WinRT stream's FlushAsync

### ISSUE THREAD

**Issue by yymsft** [dotnet/corefx#21481]
Hi, we are seeing an issue where an in app that uses the WinRT StreamSocket API to implement a webserver and listens/responds to connection requests. The issue we are seeing is the app (acting as the webserver) stops responding because there are 500 worker threads accumulated over time that are hanging, which reached the threadpool limit for the process. 

We noticed that the hanging threads all have an identical stack, which shows that  WinRtToNetFxStreamAdapter.Flush is calling the WinRTStream's flushASync and waiting forever for it. 

However on the WinRT side, the FlushAsync seems to be completing if called outside of the .NET context.

We further noticed that this only repros with Debug build of the app, either using F5 debug or a standalone debug build without the debugger attached. On release builds, the issue does not repro.

I have the repro app. Please email me when needed and I'll send you the zip.

**Comment by davidsh** [comment]
>I have the repro app. Please email me when needed and I'll send you the zip.

It is better to post the repro here directly instead of using email. You can post files directly into the GitHub issue here.  Just make sure to use Chrome as the browser. You can drag/drop them into the text box.  You can also just set up a personal, free, repo on your GitHub server account and have the complete Visual Studio repro solution there.

**Comment by davidsh** [comment]
cc: @danmosemsft - Who owns this code?  Is it part of System.IO ownership?

**Comment by yymsft** [comment]
[Repro.zip](https://github.com/dotnet/corefx/files/1099195/Repro.zip)
Repro app uploaded. To repro this, just run the app on a machine(I just tested RS3), and on another machine open any browser, and try visiting the server's address. The webpage will refresh when it gets a response, so it will keep refreshing till the server eventually stops responding because it runs out of thread quota.

**Comment by danmosemsft** [comment]
@davidsh the owner is @JeremyKuhne

**Comment by davidsh** [comment]
cc: @DavidGoll

**Comment by danmosemsft** [comment]
@yymsft is this blocking you?

**Comment by DavidGoll** [comment]
(On behalf off YY who is out on vacation)
Because it affects non-ILC only, it's not blocking.

**Comment by danmosemsft** [comment]
@yymsft @davidsh @DavidGoll moving to post 6.0 since this is not new and does not affect our current goals.
