### ISSUE TITLE
Unit tests on Windows run on 32-bit CoreCLR

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#2150]
We are using a 32bit coreclr to run all of our tests when running on windows.  This is different from what we do for OSX and Linux (where we use the 64 bit version of the runtime built from [dotnet/coreclr](https://github.com/dotnet/coreclr)).

I believe because of this we also don't get coverage on any of the RyuJIT specific optimizations around Vectors as part of our unit tests.

I think it would be ideal if we also ran tests on a 64 bit runtime and it corresponded to some LKG build from [dotnet/coreclr](https://github.com/dotnet/coreclr).

/cc @stephentoub

**Comment by mellinoe** [comment]
> I believe because of this we also don't get coverage on any of the RyuJIT specific optimizations around Vectors as part of our unit tests.

This is true, RyuJIT optimizations kick in on 64-bit Release builds only (no debug builds).

**Comment by mellinoe** [comment]
We probably just need to add another test configuration that uses the "x64" version of these packages:

       "Microsoft.NETCore.Runtime.ApiSets-x86": "1.0.0-beta-*",
       "Microsoft.NETCore.Runtime.CoreCLR.TestHost-x86": "1.0.0-beta-*",
       "Microsoft.NETCore.Runtime.CoreCLR-x86": "1.0.0-beta-*",

Assuming the xunit console runner can be used in a 64-bit environment.

**Comment by mmitche** [comment]
It doesn't appear that changing test-runtime's project.json (and TestArchitecture) to x64 works.  For whatever reason the test directory setup procedures ignore everything except for mscorlib.ni.dll and corerun.exe.  I'm looking into it.

**Comment by stephentoub** [comment]
@ellismg, this is fixed now, right?

**Comment by ellismg** [comment]
Yup.
