### ISSUE TITLE
Debian 9 is RTM - dotnet core support in roadmap?

### ISSUE THREAD

**Issue by ReneHerrero** [dotnet/corefx#21508]
Hi,
Debian 9 (stretch) is RTM has been released.  Is core support in roadmap?
Thanks,

**Comment by danmosemsft** [comment]
Hi @ReneHerrero yes this is supported for 2.0. It should work in the released preview 1 bits (I think) if not it definitely works in the preview 2 bits (imminent). Please see https://github.com/dotnet/core/blob/master/roadmap.md
