### ISSUE TITLE
Can't run UAP and non UAP tests serially because wrong remoteeexcutor is used

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#21515]
CoreFx.Private.TestUtilities.dll is target framework specific (there is a separate binary for UAP, UAPAOT, netcore, and netfx). However it gets copied only once to the test folder.

So eg. if I run UAP tests for console, using /p:targetgroup=uap, I get the UAP one in my test folder:
C:\git\corefx\bin\Windows_NT.AnyCPU.Debug\System.Console.Tests\netstandard\CoreFx.Private.TestUtilities.dll
then if I try to run tests again, without /p:targetgroup=uap, the tests fail because it's trying to use the UAP copy of it. 

This binary comes from the test package (xunit.runtime.depproj) and I'm unsure how to modify that to fix it.
@tarekgh / @weshaggard  ?

**Comment by tarekgh** [comment]
Just to mention, looks this issue is not specific to CoreFx.Private.TestUtilities.dll but it can happen with any cross compiled library used by a test which is has netstandard only configuration. 

CC @ericstj

**Comment by weshaggard** [comment]
This library should be going into the runtime specific output folder instead of the test folder. @tarekgh  Is there a reason it ends up in the test output folder as well? Is it because some projects have a ProjectReference to it? If so then the fix is to remove the ProjectReference to it.

**Comment by ericstj** [comment]
Moreover: we better not be putting anything that is test-execution-configuration-specific in the test-build-configuration folder.  If that's happening its a bug in the test targets.

**Comment by tarekgh** [comment]
>  Is there a reason it ends up in the test output folder as well? Is it because some projects have a ProjectReference to it? If so then the fix is to remove the ProjectReference to it.

The library is correctly bin placed to the runtime folder. bu twhen running the tests we hard link the runtime files to the test output folder

```
  Hardlink created for CoreFx.Private.TestUtilities.dll <<===>> F:\OSS\corefx\bin\testhost\uap-Windows_NT-Debug-x64\\UAPLayout\CoreFx.Private.TestUtilities.dll
```

I think this is done by @joperezr

**Comment by joperezr** [comment]
Right, as we pointed out in a different buildtools issue, the problem here is that when we switched to the dev/eng work we removed the concept of testPath since as of now that is the same as the RuntimePath (Which doesn't include build configuration). In some verticals, specifically in uap and uapaot we will copy stuff specific to the vertical into the test folder which is what is causing all of this. Build tools issue tracking this is https://github.com/dotnet/buildtools/issues/1587

**Comment by tarekgh** [comment]
@danmosemsft should we close this one as we have it tracked in buildtools?

**Comment by danmosemsft** [comment]
sure as long as it's tracked somehwere

**Comment by tarekgh** [comment]
closing per @joperezr comment
