### ISSUE TITLE
[Perf] Fix XmlDocument/XPath to properly compare strings by ref

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#2152]
XmlDocument/XPath when comparing namespaces it uses fixed string object (from private class defined in XmlConst.cs). During the split of System.Xml.dll to smaller libraries (XmlDocument, ReaderWriter, XPath, XPath.XmlDocument) we introduced shared XmlConst.cs file for those constants and thus different references for those strings. To optimize implementation is comparing built-in namespaces by reference and thus in some cases it doesn't work properly and causes some undefined behavior. The cases which were breaking tests were already fixed although there are some other broken scenarios which got introduced when running product on Desktop (runtime).
Steps:
- [x] Workaround to not compare by ref (one line change in Ref.cs) to unblock Desktop ASAP (we are gonna lose some perf but correctness is more important than perf) - https://github.com/dotnet/corefx/pull/2154
- [ ] Make sure there is only one copy of string constants in one of the libraries (ReaderWriter or XmlDocument) and other libraries should get the valid and needed references to string some other way (i.e. through XmlDoc's NameTable or exposing something new in the contract if NameTable is too slow or not possible)
- [ ] Re-enable comparison by ref and validate it is passing when running on Desktop runtime (on Win 10) and coreclr

**Except for the first checkbox it is up for grabs**

Please revert Ref.cs to its original form with the last checkbox:
```csharp
        public static bool Equal(string strA, string strB)
        {
#if DEBUG
            if (((object)strA != (object)strB) && string.Equals(strA, strB))
                System.Diagnostics.Debug.Fail("Ref.Equal: Object comparison used for non-atomized string '" + strA + "'");
#endif
            return (object)strA == (object)strB;
        }
```

**Comment by joshfree** [comment]
@ianhays do we have good perf test coverage here?

**Comment by ianhays** [comment]
> do we have good perf test coverage here?

No, we don't have any. System.Xml.XPath.XDocument didn't come up in any of my usage data (though System.Xml.XDocument did). I can add it to my list of places to perf test next though.

**Comment by krwq** [comment]
Closing this as System.Private.Xml should not doing that anymore
