### ISSUE TITLE
Large performance gap in SqlCommand.ExecuteNonQuery between net461 and netcoreapp

### ISSUE THREAD

**Issue by scionwest** [dotnet/corefx#21530]
Sharing the following code on a full framework net461 Console application and a netcoreapp Console app, I am seeing huge gaps in performance when executing `SqlCommand.ExecuteNonQuery` with `SqlConnection`. It doesn't matter if I use it within a transaction or not.

        public async Task AddDataWithADO(int id, string name)
        {
            SqlConnection connection = this.transaction.Connection;
            SqlCommand command = new SqlCommand("INSERT INTO TestTable ( Id, Name ) VALUES ( @Id, @name )", connection, this.transaction);
            command.Parameters.AddWithValue("@id", id);
            command.Parameters.AddWithValue("@name", name);
            await command.ExecuteNonQueryAsync();
        }

When I run this on my local machine against a LocalDb, I see an average insertion time of 19.89ms in netcoreapp1.0 and 1.1. When I run the same code in full framework net461, then I see insertion times of 0.83ms. It's a shared NetStandard1.4 class library with a reference to `System.Data.SqlClient` 4.3.1. My current .Net Core runtime is 1.1.0

I was moving my Azure Functions which ran on net461 over to ASP.net Core when I saw this gap. Why is there such a huge difference in performance?

I have a repro repository that you can look at here (originally thought this was [a Dapper issue](https://github.com/StackExchange/Dapper/issues/810), turned out to be ADO.Net): https://github.com/scionwest/DapperRepro/tree/ADO_net_issue

You can publish the Sql database project that's in the solution to a LocaLDb and then run the two console apps to see the difference.

**Comment by NickCraver** [comment]
cc @saurabh500 - known issue?

**Comment by WernerMairl** [comment]
any difference using a full sql server instance ?
LocalDB seems to have some "special behavior" regarding startup.... (not remembering every detail)

regards
Werner

**Comment by scionwest** [comment]
The perf issue seems to be the same when talking to a Sql Server instance. My Sql Server calls were to one in our data center, so the overall slower calls are to be expected vs my localdb inserts. However the gap still seems to be about the same percentage-wise.

Data Store | Runtime            | Average Insert Time (milliseconds)
--------------------------------------------------------------
LocalDb     | netcoreapp1.1  | 12.5
LocalDb     | net461              | 0.8
Sql Server  | netcoreapp1.1  | 19.6
Sql Server  | net461              | 6.7

**Comment by scionwest** [comment]
I just ran the tests against netcoreapp2.0 and netstandard2.0 and had the same results. I also updated from `System.Data.SqlClient` 4.3.1 to the 4.4.0-preview1-25305-02 release and had the same results.

**Comment by saurabh500** [comment]
@scionwest Have you tried the Sync APIs as well?

**Comment by saurabh500** [comment]
Also are these results of a single call when the application starts up or are you seeing these results as an average of multiple calls?

**Comment by scionwest** [comment]
@saurabh500 Average time over 1,000 iterations, as shown [in my repro](https://github.com/scionwest/DapperRepro/blob/ADO_net_issue/DataAccess/AppService.cs#L28), within a single open connection using a transaction. Note that these results are roughly the same if I create/open a new connection each iteration or if I omit the use of a transaction all together.

I have not tried the synchronous APIs yet. I will give them a shot next.

**Comment by scionwest** [comment]
I see the same thing with the synchronous API.

**Comment by scionwest** [comment]
Any updates on this @saurabh500? This would have a substantial cost affect for us when we deploy. We will have to pay for a much larger SQL server instance than necessary because of the gap in core. Either that or port our entire stack back to full framework which isn't cost effective either.

**Comment by corivera** [comment]
I ran your DapperRepro tests on a VM with 1 core and 500MB of memory, connecting to a localdb instance. These are the results from one of my test runs, executing the console apps multiple times in a row:

net461 test
Total average: 3.05684050000001 ms
Total average: 0.807116800000001 ms
Total average: 0.5157157 ms
Total average: 0.5049637 ms
Total average: 0.520481100000001 ms
Total average: 0.4160756 ms
Total average: 2.7093892 ms
Total average: 1.17444440000001 ms
Total average: 0.677895499999999 ms
Total average: 1.0000855 ms
Total average: 0.631835 ms

netcoreapp test
Total average: 1.717231 ms
Total average: 0.708947400000001 ms
Total average: 0.9888239 ms
Total average: 1.263527 ms
Total average: 1.6733024 ms
Total average: 1.5673712 ms
Total average: 0.8787862 ms
Total average: 1.1596408 ms
Total average: 0.679306400000002 ms
Total average: 1.0749333 ms
Total average: 1.2741569 ms

The only runs I ever saw high insert times like you described were after clean builds with a restarted machine, and even then I saw some timeouts with the net461 app on some of its first runs. So those high times are likely a warmup issue in my test runs. Do you get these high times with repeated test executions?

**Comment by scionwest** [comment]
Hmm, I see these differences consistently on every run. I will spin up a VM in azure tonight and run the same tests and report back. I've tried this on the same machine, but with two different installs of Windows, with the same gap. Perhaps it's something specific to my machine or Windows version.

**Comment by scionwest** [comment]
@corivera I see the same results as before. An average of 13ms for netcoreapp and an average of 0.6ms on net461. This is in a brand new Standard DS3 v2 Promo (4 cores, 14 GB memory) VM in Azure running Windows 10 Enterprise N, 10.0.15063 Build 15063. I installed Visual Studio 15.2 my self, rather than using the pre-installed image in Azure.

This is my install info for Visual Studio.
> Microsoft Visual Studio Enterprise 2017 
> Version 15.2 (26430.14) Release
> VisualStudio.15.Release/15.2.0+26430.14
> Microsoft .NET Framework
> Version 4.7.02046
> 
> Installed Version: Enterprise
> 
> Visual Basic 2017   00369-60000-00001-AA700
> Microsoft Visual Basic 2017
> 
> Visual C# 2017   00369-60000-00001-AA700
> Microsoft Visual C# 2017
> 
> Visual C++ 2017   00369-60000-00001-AA700
> Microsoft Visual C++ 2017
> 
> Visual F# 4.1   00369-60000-00001-AA700
> Microsoft Visual F# 4.1
> 
> ASP.NET and Web Tools 2017   15.0.30503.0
> ASP.NET and Web Tools 2017
> 
> ASP.NET Web Frameworks and Tools 2017   5.2.50303.0
> For additional information, visit https://www.asp.net/
> 
> Azure App Service Tools v3.0.0   15.0.30209.0
> Azure App Service Tools v3.0.0
> 
> Azure Data Lake Node   1.0
> This package contains the Data Lake integration nodes for Server Explorer.
> 
> Azure Data Lake Tools for Visual Studio   2.2.5000.0
> Microsoft Azure Data Lake Tools for Visual Studio
> 
> Common Azure Tools   1.9
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> Fabric.DiagnosticEvents   1.0
> Fabric Diagnostic Events
> 
> JavaScript Language Service   2.0
> JavaScript Language Service
> 
> JavaScript Project System   2.0
> JavaScript Project System
> 
> JavaScript UWP Project System   2.0
> JavaScript UWP Project System
> 
> KofePackagePackage Extension   1.0
> KofePackagePackage Visual Studio Extension Detailed Info
> 
> Merq   1.1.17-rc (cba4571)
> Command Bus, Event Stream and Async Manager for Visual Studio extensions.
> 
> Microsoft Azure Hive Query Language Service   2.2.5000.0
> Language service for Hive query
> 
> Microsoft Azure Tools   2.9
> Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50131.1
> 
> Microsoft MI-Based Debugger   1.0
> Provides support for connecting Visual Studio to MI compatible debuggers
> 
> Microsoft Visual Studio VC Package   1.0
> Microsoft Visual Studio VC Package
> 
> Mono Debugging for Visual Studio   Mono.Debugging.VisualStudio
> Support for debugging Mono processes with Visual Studio.
> 
> Node.js Tools   1.3.50417.1
> Adds support for developing and debugging Node.js apps in Visual Studio
> 
> NuGet Package Manager   4.2.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
> 
> Redgate ReadyRoll   1.13.22.3147
> Extend DevOps processes to your SQL Server databases and safely automate database deployments.
>     
> Visit https://www.red-gate.com/readyroll for more information.
> 
> Copyright (C) 2011 Red Gate Software Ltd. All rights reserved.
>   
> This software contains components from Component Owl.
> SQL Server is a registered trademark of Microsoft Corporation. 
> Visual Studio is a registered trademark of Microsoft Corporation. 
> 
> ReadyRoll contains code from the following open source software:
> 
> NuGet https://www.nuget.org/
> SQL LocalDB Wrapper https://github.com/martincostello/sqllocaldb
> Autofac https://autofac.org/
> Json.NET https://json.net/
> MahApps.Metro http://mahapps.com/
> SemVer https://github.com/maxhauser/semver
> Menees Diff Controls http://www.menees.com/
> Log4Net http://logging.apache.org/log4net/
> Extended WPF Toolkit https://wpftoolkit.codeplex.com/
> Code InfoBox VSX http://www.codeproject.com/Articles/55196/Code-InfoBox-Visual-Studio-Extension-VSX
> OctoPack https://github.com/OctopusDeploy/OctoPack
> SQLite https://sqlite.org/
> 
> This product contains icons from http://www.visualpharm.com distributed under a free backlink license.
> 
> For license details or other notices relating to the above software, please see NOTICE.TXT and EULA.rtf in the ReadyRoll application folder.
>     
> 
> Redgate SQL Prompt   7.4.1.767
> Write, format, and refactor SQL effortlessly
> 
> Redgate SQL Search   2.3.10.1131
> Search functionality for SQL Server databases, from within Visual Studio
> 
> SQL Server Data Tools   15.1.61702.140
> Microsoft SQL Server Data Tools
> 
> ToolWindowHostedEditor   1.0
> Hosting json editor into a tool window
> 
> TypeScript   2.2.2.0
> TypeScript tools for Visual Studio
> 
> Visual Studio Tools for Universal Windows Apps   15.0.26430.06
> The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.
> 
> Xamarin   4.5.0.486 (fec6f88)
> Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
> 
> Xamarin.Android SDK   7.3.1.2 (9dbc4c5)
> Xamarin.Android Reference Assemblies and MSBuild support.
> 
> Xamarin.iOS and Xamarin.Mac SDK   10.10.0.37 (ad35de4)
> Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by scionwest** [comment]
@corivera I tried this on a machine at my office, connecting to both a localdb instance on the machine, as well as to a Sql Server 2012 instance in our data center. I saw the same performance gap issue with both tests (albeit with slightly different times).

**Comment by geleems** [comment]
I was trying to reproduce the performance gap issue in my local machine, and I noticed interesting performance change in .NET Core.

I ran my sample code in my local VM by :
* Creating a new project of Console App (.NET Framework 4.6.1) -- Release / Any CPU
* Creating a new project of Console App (.NET Core 1.1.0) -- Release / Any CPU
* Adding the sample code to release/1.1.0 `CoreFx\src\System.Data.SqlClient\Tests\FunctionalTests`
* Adding the sample code to recent code 7d18ff370feb7b9a465318e96c71ce47a3693a03 `CoreFx\src\System.Data.SqlClient\Tests\FunctionalTests`
***
Here is my sample test code to reproduce the issue.
```
public static void TestMain()
{
    for (int i = 0; i < 10; ++i)
    {
        CurrentTest();
    }
}

public static async void CurrentTest()
{
    string connString = "Server=tcp:.,1433;User ID=testuser;Password=test1234";
    SqlConnectionStringBuilder builder = new SqlConnectionStringBuilder(connString);
    string connectionString = builder.ConnectionString;

    string testTableName = GenerateTableName();
    RunNonQuery(connectionString, "create table " + testTableName + " (col1 int)");

    int count = 1000;
    Stopwatch stopwatch = new Stopwatch();

    try
    {
        using (SqlConnection connection = new SqlConnection(connectionString))
        {
            connection.Open();
            using (SqlCommand command = connection.CreateCommand())
            {
                stopwatch.Start();
                for (int i = 0; i < count; ++i)
                {
                    command.CommandText = "INSERT INTO " + testTableName + " VALUES (" + i + ")";
                    await command.ExecuteNonQueryAsync();
                }
                stopwatch.Stop();
            }
        }
    }
    finally
    {
        RunNonQuery(connectionString, "drop table " + testTableName);
    }

    float average_time = (float)stopwatch.ElapsedMilliseconds / 1000F;
    Console.WriteLine("average_time: " + average_time + "ms");
}

private static void RunNonQuery(string connectionString, string sql)
{
    try
    {
        using (SqlConnection connection = new SqlConnection(connectionString))
        {
            connection.Open();
            using (SqlCommand command = connection.CreateCommand())
            {
                command.CommandText = sql;
                command.ExecuteNonQuery();
            }
        }
    }
    catch { }
}
```
***
Execution result in ***.NET Framework 4.6.1*** by creating Console App project (Release/Any CPU) in Visual Studio 2017 :
```
average_time: 6.899ms
average_time: 6.956ms
average_time: 6.981ms
average_time: 6.985ms
average_time: 7.104ms
average_time: 7.082ms
average_time: 7.2ms
average_time: 7.35ms
average_time: 7.194ms
average_time: 7.425ms
```
***
Execution result in ***.NET Core 1.1.0*** by creating Console App project (Release/Any CPU) in Visual Studio 2017 : 
```
average_time: 79.86ms
average_time: 80.322ms
average_time: 80.647ms
average_time: 81.113ms
average_time: 80.731ms
average_time: 81.306ms
average_time: 81.871ms
average_time: 81.041ms
average_time: 80.452ms
average_time: 80.828ms
```
***
Execution result in ***.NET Core 1.1.0*** by adding the sample code to `System.Data.SqlClient\Tests\FunctionalTests` : 
```
average_time: 7.573ms
average_time: 7.653ms
average_time: 7.664ms
average_time: 7.784ms
average_time: 7.716ms
average_time: 7.828ms
average_time: 8.013ms
average_time: 8.175ms
average_time: 8.218ms
average_time: 8.262ms
```
***
Execution result in ***.NET Core recent version*** 7d18ff370feb7b9a465318e96c71ce47a3693a03 by adding the sample code to `System.Data.SqlClient\Tests\FunctionalTests` : 
```
average_time: 7.965ms
average_time: 8.181ms
average_time: 8.173ms
average_time: 8.176ms
average_time: 8.221ms
average_time: 8.332ms
average_time: 8.274ms
average_time: 8.434ms
average_time: 8.474ms
average_time: 8.598ms
```
***
I could observe `SqlCommand.ExecuteNonQueryAsync()` becomes about 10 times slower when I run it by creating a project Console App (.NET Core) in Visual Studio. It seems there is no performance difference for `SqlCommand.ExecuteNonQuery()`. It only affected to ***Async*** method.

**Comment by tiandian** [comment]
I transfer a qt function to .net core, I found  SqlCommand.ExecuteNonQuery is very slow when compare to qt.
i insert 3300 record into sqlserver, 
qt: total 1.004s.  0.304ms/record. (02:15:16.573~02:15:17.577), 
.net core 2.0: total 26.183s. 7.9ms/record, (02:18:41.620~02:19:07.803), 
qt is 26 time faster than .net core.
.net core's ado.net insert one record to sqlserver need 7.9ms, this is too slow when compare to qt.

**Comment by scionwest** [comment]
Any update on this?

**Comment by saurabh500** [comment]
This is related to the fix submitted for https://github.com/dotnet/corefx/pull/26595
Closing as the fix is checked in. The fix should improve perf of all Async executions in SqlClient.
