### ISSUE TITLE
Timeouts with SslStream are fatal

### ISSUE THREAD

**Issue by roji** [dotnet/corefx#21549]
[The documentation for SslStream](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream?view=netcore-2.0) contains the following sentences:

```
SslStream assumes that a timeout along with any other IOException 
when one is thrown from the inner stream will be treated as fatal by its caller.
Reusing a SslStream instance after a timeout will return garbage.
An application should Close the SslStream and throw an exception in these cases.
```

Consider modifying to SslStream to treat timeouts as non-fatal, like a normal NetworkStream - there are various scenarios where network timeouts can be (relatively) normal events and reconnecting the socket after them is a heavy and unwieldy workaround.

**Comment by karelz** [comment]
cc @geoffkizer @Priya91 @stephentoub

**Comment by karelz** [comment]
Triage: The work is extremely large. We don't think it makes sense to do it.

Key question @roji: Do we throw exceptions after the SslStream gets into corrupted state? We should have that behavior.

**Comment by roji** [comment]
> Do we throw exceptions after the SslStream gets into corrupted state? We should have that behavior

@karelz I honestly don't know... I'm assuming that the SslStream bubbles up the exception it intercepts from the inner stream (or throws another one in its place).

On the larger question, I get that this is expensive to do and not necessarily valuable enough. Just a thought though - it raises the question of the semantics which users may assume of streams around exceptions - SslStream is broken, NetworkStream isn't, etc. If streams are supposed to be a robust abstraction, we may want to think about this (e.g. add some way for users to find out if the stream is still usable).
