### ISSUE TITLE
`SystemUri.Compare` requires query string parameters to be in the same order.

### ISSUE THREAD

**Issue by JohnLBevan** [dotnet/corefx#21559]
**The Issue**

When comparing two URIs, we get a non-zero result if two URIs are functionally identical, but with query string parameters ordered differently.  For example:

```c#
var uriComponentsOptions = UriComponents.AbsoluteUri;
var uriFormatOptions = UriFormat.SafeUnescaped;
var stringComparisonOptions = StringComparison.OrdinalIgnoreCase;
var uriX = "https://example.com/demo?param1=abc&param2=xyz";
var uriY = "https://example.com/demo?param2=xyz&param1=abc"; //calling this URI would have the same affect as calling the above
var result = Uri.Compare(uriX, uriY, uriComponentsOptions, uriFormatOptions, stringComparisonOptions); //yet this returns a non-zero value
```

**Suggestion**

It would be helpful if there were a value for [UriComponents](https://msdn.microsoft.com/en-us/library/7767559y(v=vs.110).aspx) called `QueryIgnoreOrder` (or equivalent), allowing the query string of the URL to be compared without taking the order of the parameters into account.

**Use Case**

In automated test code, sometimes we need to compare URIs to ensure the correct URI is being generated.  However, we don't care about the order of the parameters there, since that has no functional impact.  We could code our tests to use fixed orders, but this would mean that any change to our code which altered that order would break our unit tests, creating more work to recode those strings for no real benefit.
Currently I have this scenario / have had to code a workaround where my tests sort the parameters in key order before making a comparison (see https://stackoverflow.com/questions/44751296/uri-comparer-ignoring-query-string-order/44757683#44757683); but I'd hope that this would be something offerred by the .Net framework itself, as it feels a fairly common scenario / one of the key benefits of using Uri's Compare over a string comparison.

Related Method: https://github.com/dotnet/corefx/blob/7df6b74cc4aeebc86e76b5c7901a59fa7fa793f6/src/System.Private.Uri/src/System/UriExt.cs

**Comment by karelz** [comment]
While it sounds useful, it would have bad impact on compat with Desktop (imagine .NET Standard library). I wonder if it wouldn't be easier to create standalone Uri class, or if we should introduce new API `CompareIgnoreOrder`. Thoughts?

**Comment by davidsh** [comment]
>When comparing two URIs, we get a non-zero result if two URIs are functionally identical, but with query string parameters ordered differently

What does the RFC say about this?

**Comment by JohnLBevan** [comment]
@karelz Those options sound good.  One reason I'd suggested using `UriComponents` is we can combine options; so can compare the absolute Uri ignoring query-string key order, or can compare just the queries (etc.):

- `var uriComponentsOptions = UriComponents.AbsoluteUri | UriComponents.QueryIgnoreOrder;`
- `var uriComponentsOptions = UriComponents.Query | UriComponents.QueryIgnoreOrder;` 

That said I agree that this is a misuse ofthe enum as it's not strictly a component as a comparison type.  `UriComponents.QueryParameters` would get around that, but isn't recognised as an official part of a uri, so has it's own issue there.

@davidsh It states that query is often made up of name-value pairs, but doesn't give info on their sequence / also suggests that that's not the only use for the query component. 
 https://tools.ietf.org/html/rfc3986#section-3.4

**Comment by rmkerr** [comment]
The HTTP 1.1 RFC describes how to compare http URIs. From [section 3.2.3](https://tools.ietf.org/html/rfc2616#section-3.2.3):
```
When comparing two URIs to decide if they match or not, a client
   SHOULD use a case-sensitive octet-by-octet comparison of the entire
   URIs, with these exceptions:
        - A port that is empty or not given is equivalent to the default
          port for that URI-reference;
        - Comparisons of host names MUST be case-insensitive;
        - Comparisons of scheme names MUST be case-insensitive;
        - An empty abs_path is equivalent to an abs_path of "/"
```
While queries are often made up of name-value pairs, as far as I know there is no formal specification that describes the format. Without that a lot of things are unclear. What should the separators be? Should sequence matter? Should casing matter? Those kinds of decisions are application specific, and we shouldn't dictate them in System.Uri. @JohnLBevan I'm going to go ahead and close this issue, but don't hesitate to re-open it if you do find some evidence of standardization in how queries should be compared.
