### ISSUE TITLE
Update 'debugging using vscode' doc

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#21557]
The documentation on debugging using vscode is a bit out-dated and can be improved: https://github.com/dotnet/corefx/blob/master/Documentation/debugging/unix-instructions.md#using-visual-studio-code

> Open the folder containing the source you want to debug in VS Code

Can this be the toplevel corefx folder? Or does this need to be a folder with a csproj? Is debugging limited to source code in that folder?

> set program to the full path to corerun in the test directory

There is no corerun in the test directory.

> set args to the command line arguments to pass to the test
something like: [ "xunit.console.netcore.exe", "<test>.dll", "-notrait", .... ]

An example launch configuration (e.g. for Linux including typical traits) would be nice.

**Comment by mellinoe** [comment]
I have tried to debug tests with VS Code recently, and didn't have any luck. I got a cryptic error from the debugger, and it failed to attach. At the very least, we can try to update the instructions so that they reference the right files (`bin/testhost/Linux-netcoreapp-Debug-x64/dotnet`, etc.), but I'm not sure that things are in a working state for 2.0 in the first place. It may require some VS Code or C# extension updates.

**Comment by tmds** [comment]
@karelz can someone take a look at this please?

**Comment by karelz** [comment]
We can put it on our backlog. It would be best to bundle it together with new developer instructions, which also need some love.

cc @ianhays @wfurt

**Comment by caozhiyuan** [comment]
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "program": "/home/caozhiyuan/corefx/bin/testhost/netcoreapp-Linux-Debug-x64/dotnet",
            "args": [ "xunit.console.netcore.exe", "System.Net.Sockets.Tests.dll"],
            "cwd": "/home/caozhiyuan/corefx/bin/AnyOS.AnyCPU.Debug/System.Net.Sockets.Tests/netcoreapp",
            "stopAtEntry": false,
            "console": "internalConsole"
        }
    ]
}
but can't enter breakpoint
@tmds  @karelz  
it's any way to debug?

**Comment by wtgodbe** [comment]
https://github.com/dotnet/corefx/pull/27384 should resolve
