### ISSUE TITLE
Consider adding SslStream.DataAvailable

### ISSUE THREAD

**Issue by roji** [dotnet/corefx#21550]
NetworkStream provides a [DataAvailable property](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.networkstream.dataavailable?view=netcore-2.0#System_Net_Sockets_NetworkStream_DataAvailable) which allows non-blocking style usage by examining whether a read would block. Consider providing the same for SslStream.

**Comment by stephentoub** [comment]
@roji, can you share more details about what solution you have in mind, keeping in mind that SslStream wraps arbitrary Streams and not just NetworkStream? Thanks.

**Comment by roji** [comment]
You're right - I didn't consider that SslStream can wrap arbitrary streams.

The point here was to improve general .NET support for non-blocking I/O (as opposed to async I/O). As a (better) replacement for the issue, would you consider making SslStream compatible with general non-blocking reads (i.e. Blocking set to true on the socket)? IIRC this currently throws a NotSupportedException.

(see https://github.com/davidfowl/Channels/issues/48 for a general discussion with @benaadams and @davidfowl on things lacking at the stream level for proper non-blocking I/O)

**Comment by stephentoub** [comment]
> would you consider making SslStream compatible with general non-blocking reads (i.e. Blocking set to true on the socket)? IIRC this currently throws a NotSupportedException.

That shouldn't have anything to do with SslStream specifically.  If anything, that would be NetworkStream, right?  Regardless, if NetworkStream doesn't work with non-blocking sockets today, I agree we should look into why and investigate fixing it (I could see why maybe the synchronous Read/Write methods wouldn't work, but I don't see why the Read/WriteAsync methods couldn't).  Can you open a separate issue for that with a repro?

**Comment by roji** [comment]
@stephentoub I've opened #21570 for making NetworkStream support non-blocking (or polling) I/O. Note that the point is to make *synchronous* methods compatible with non-blocking, and not ReadAsync/WriteAsync - the whole point is that calls return immediately, so anything returning a Task doesn't seem well-suited.

I'm not sure what you mean by a repro - non-blocking I/O is a basic pattern (at least in the Unix/Linux world), if you think any info is missing let me know.

**Comment by stephentoub** [comment]
> I'm not sure what you mean by a repro

I meant example code that doesn't work that should work.  But looking now I see a repro would be trivial, as the ctor simply checks for Blocking and throws:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/NetworkStream.cs#L55-L58

**Comment by roji** [comment]
@stephentoub OK understood, yeah, that's mentioned in the description for #21570.

**Comment by stephentoub** [comment]
> the whole point is that calls return immediately, so anything returning a Task doesn't seem well-suited.

I was simply commenting that there shouldn't be any reason the existing Read/WriteAsync methods can't work with non-blocking sockets today just as well as they work with blocking sockets, with no API changes; in fact I'd expect they'd "just work" if the exception were removed from the ctor, though I've not verified.

**Comment by roji** [comment]
@stephentoub - ah I understand. I'm not sure what value that would add though, over just telling the user to turn off blocking as you do today.
