### ISSUE TITLE
System.Diagnostics.Tests.StackTraceTests failed with Xunit.Sdk.NullException

### ISSUE THREAD

**Issue by v-haren** [dotnet/corefx#21554]
detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_debug/96/testReport/System.Diagnostics.Tests/StackTraceTests/Ctor_SkipFrames_FNeedFileInfo_skipFrames__0__fNeedFileInfo__True_/

MESSAGE:
~~~
Assert.Null() Failure
Expected: (null)
Actual: D:\\j\\workspace\\outerloop_net---92764178\\src\\System.Diagnostics.StackTrace\\tests\\StackTraceTests.cs
~~~
STACK TRACE:
~~~
at System.Diagnostics.Tests.StackTraceTests.VerifyFrames(StackTrace stackTrace, Boolean hasFileInfo) in D:\j\workspace\outerloop_net---92764178\src\System.Diagnostics.StackTrace\tests\StackTraceTests.cs:line 375 
at System.Diagnostics.Tests.StackTraceTests.Ctor_SkipFrames_FNeedFileInfo(Int32 skipFrames, Boolean fNeedFileInfo) in D:\j\workspace\outerloop_net---92764178\src\System.Diagnostics.StackTrace\tests\StackTraceTests.cs:line 94
~~~

failed test: 
System.Diagnostics.Tests.StackTraceTests.Ctor_SkipFrames_FNeedFileInfo
System.Diagnostics.Tests.StackTraceTests.Ctor_ThrownException_GetFramesReturnsExpected
System.Diagnostics.Tests.StackTraceTests.Ctor_FNeedFileInfo
System.Diagnostics.Tests.StackTraceTests.Ctor_Exception_SkipFrames_FNeedFileInfo
System.Diagnostics.Tests.StackFrameTests.Ctor_FNeedFileInfo
System.Diagnostics.Tests.StackFrameTests.Ctor_SkipFrames_FNeedFileInfo

**Comment by danmosemsft** [comment]
@hughbe do you want to take a look? If not I can.

**Comment by hughbe** [comment]
Looks like we've got line numbers back. I can't fix this evening as I'm out, sorry

**Comment by v-haren** [comment]
failed again: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_debug/97/testReport/System.Diagnostics.Tests/StackTraceTests/Ctor_SkipFrames_FNeedFileInfo_skipFrames__1__fNeedFileInfo__True_/

**Comment by v-haren** [comment]
failed again: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_debug/98/testReport/
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug/3422/testReport/
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_debug/89/testReport/

**Comment by v-haren** [comment]
failed again: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_debug/99/testReport/
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug/3442/testReport/
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_debug/90/testReport/

**Comment by danmosemsft** [comment]
@sepidehMS could you please fix these tests today since we have line numbers back? Should be a fairly trivial change.

That will get our windows runs green again on the corefx homepage.

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_debug/lastCompletedBuild/testReport/ etc

**Comment by Jiayili1** [comment]
Still repro, https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_debug/91/testReport/System.Diagnostics.Tests/StackTraceTests/Ctor_SkipFrames_FNeedFileInfo_skipFrames__1__fNeedFileInfo__True_/

Checked the commit is not in, will check it on next build
