### ISSUE TITLE
Adding Amazon Linux to the Runtime IDs

### ISSUE THREAD

**Issue by gokarnm** [dotnet/corefx#21591]
I'd like to add Amazon Linux to list of Runtime IDs (RID). What are the steps to achieve this? 

1. Does adding new Amazon Linux RIDs in [runtime.json](https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json) suffice? Are there any other steps involved?

2. The logic to create the RID string for a given Linux distro resides here in corehost [pal::get_current_os_rid_platform](https://github.com/dotnet/core-setup/blob/master/src/corehost/common/pal.unix.cpp#L295) , is that correct?

@Petermarcu, this is based on the discussion you and @normj had at NDC Oslo.

**Comment by karelz** [comment]
cc @janvorli

**Comment by gokarnm** [comment]
Hey guys any update on this?

**Comment by Petermarcu** [comment]
I believe all you need to do is add to runtime.json. That said, with our linux-64 rid working nearly everywhere, that's all we should really need. Is there something about amazon Linux that would require people to cross compile their native assets? Remind me which distro and version it's based on?

**Comment by gokarnm** [comment]
Thanks @Petermarcu! Amazon Linux isn't based on a single upstream Linux distro. It has a degree of compatibility with RHEL 7, many of the packages have EL7 as their upstream.

Does each minor release version for a given Linux distro (e.g. [RHEL](https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json#L275)) needs to be listed in runtime.json in case minor versions are backward compatible? Is this so that library developers can target newer features in a minor version of a distro? I'm trying to understand if there is a way to avoid updates to runtime.json file for each minor version release of a distro.

**Comment by Petermarcu** [comment]
If its compatible at the glibc level and has the other dependencies/versions of the dotnet package dependencies, then we can just think of it as `linux-x64` from a rid graph perspective. We're also trying not to update the runtime.json.

**Comment by karelz** [comment]
@gokarnm thanks for submitting your PR! I have sent you collaborator invite, so that we can assign the work item to you. Please ping us when you accept (assigning temporarily to myself).

ProTip: Disable notifications for CoreFX repo (automatic for collaborators), otherwise it will DoS you (400-500 notifications daily)

**Comment by gokarnm** [comment]
@karelz , thanks for the invite! I've accepted it.

**Comment by gokarnm** [comment]
Closing this issue, based on the discussion in PR #22105
