### ISSUE TITLE
ResourceManager ignores localized resources

### ISSUE THREAD

**Issue by tomasherceg** [dotnet/corefx#2161]
It seems that the ResourceManager cannot find localized ResX files and always returns values from the default RESX file.
I am using the version "System.Resources.ResourceManager": "4.0.0-beta-22816"

1. Create a new ASP.NET 5 Console Application project.
2. Add a resource file Test.resx with a resource entry "TestString" with value "Hello".
3. Add a second localized file Test.cs-CZ.resx with a resource entry "TestString" with value "Ahoj".
4. I am using the following code:
```
var resourceManager = new ResourceManager("ResxTest.Test", typeof (Program).GetTypeInfo().Assembly);
Console.WriteLine(resourceManager.GetString("TestString", new CultureInfo("en-US")));
Console.WriteLine(resourceManager.GetString("TestString", new CultureInfo("cs-CZ")));
```
When I run the code, I get "Hello" twice instead of "Hello" and "Ahoj". The same code works correctly in the good old .NET 4.6.

**Comment by christiannagel** [comment]
Is an update available for this issue? It seems that all the resources for different languages are created inside the same assembly (checking the generated assembly via ildasm). Shouldn't there be satellite assemblies?

**Comment by davidfowl** [comment]
Yea it wilbe fixed in beta8

**Comment by christiannagel** [comment]
Thanks, David!

**Comment by joshfree** [comment]
@ramarag @gkhanna79

**Comment by oliverw** [comment]
This issue is currently a big deal breaker for us. Any chance this will finally fixed in RC2?

**Comment by davidsh** [comment]
cc: @weshaggard @tarekgh

**Comment by gkhanna79** [comment]
CoreCLR looks for localized assemblies under PLATFORM_RESOURCE_ROOTS - see BindByTpaList for details at https://github.com/dotnet/coreclr/blob/master/src/binder/assemblybinder.cpp.

@davidfowl Is this a ASP.NET Host bug? Is not passing the path to platform_Resource_roots to CoreCLR or is not placing the localized assembly in the platform_resource_roots?

**Comment by davidfowl** [comment]
Most likely. We don't do any of that, resource loading is handled by the AssemblyLoadContext. Today it works outside of VS but not in VS. For RC2 it's all changing anyways.

**Comment by gkhanna79** [comment]
@davidfowl Thanks - should I assign the issue to you?

**Comment by davidfowl** [comment]
Sure, though with all of the architectural changes happening, this will be m00t.

**Comment by gkhanna79** [comment]
We should chat about that as part of the overall RC2 discussion to understand how localization experience of ASP.NET is going to come in.

**Comment by davidfowl** [comment]
Sure

**Comment by oliverw** [comment]
@gkhanna79 @davidfowl Clearing up the confusion about the team's overall vision for ASP.Net Localization would be indeed a good thing. I for one would like to know if localizing Razor Views using the old fashioned approach of accessing strongly typed string resources directly in the view will be even supported at all (i.e. `<span>@SharedStrings.FooString</span>`)

**Comment by gkhanna79** [comment]
CC @schellap

**Comment by gkhanna79** [comment]
This should now be addressed by the universal host present in CLI repo. https://github.com/dotnet/cli/blob/master/Documentation/specs/corehost.md describes how satellite assembly lookup would be done.

CC @anurse 

@davidfowl Let me know if there are concerns closing this.
