### ISSUE TITLE
XmlNodeReader not wotking

### ISSUE THREAD

**Issue by BisiAden** [dotnet/corefx#21613]
Please, what is an alternative for using xmlNodeReader as it is not working at the moment for .net core?

**Comment by svick** [comment]
[`XmlNodeReader` is going to be added in .Net Core 2.0.](https://apisof.net/catalog/System.Xml.XmlNodeReader)

In the meantime, can you use `XmlReader` instead? If not, can you clarify how are you using `XmlNodeReader`?

**Comment by danmosemsft** [comment]
This is in .NET Core 2.0.
