### ISSUE TITLE
Suggestion: Partner with SlickEdit

### ISSUE THREAD

**Issue by clrjunkie** [dotnet/corefx#21615]
I recently evaluated the SlickEdit code editor and was totally blown by its speed and feature-set.

I installed it inside a VM running Ubuntu Desktop with 4GB ram/2 proc and honestly I couldn't sense a VM environment in any way.

I highly recommend the team reach out and discuss .NET Core support. It would be super to have it as an additional cross-platform editor alongside other offerings like JetBrains Rider.

https://www.slickedit.com

**Comment by danmosemsft** [comment]
@richlander

**Comment by karelz** [comment]
That is .NET Core broad suggestion, beyond CoreFX scope. Should we move it to dotnet/core repo? @richlander

**Comment by tarekgh** [comment]
Issue moved to [dotnet/core #716](https://github.com/dotnet/core/issues/716) via [**ZenHub**](https://www.zenhub.com/)

**Comment by tarekgh** [comment]
I moved it to the core repo.
