### ISSUE TITLE
wrong implementation of the try pattern ?

### ISSUE THREAD

**Issue by shadowca** [dotnet/corefx#21614]
Hi,
I've just stumbled across the following code.
``` 
if (_state != State.Running) {
  Bid.PoolerTrace("<prov.DbConnectionPool.GetConnection|RES|CPOOL> %d#, DbConnectionInternal State != Running.\n", ObjectID);
  connection = null;
  return true;
  }
```
This is an snippet from the **TryGetConnection** method of class **DbConnectionPool** and I would expect a return value _false_ if the connection is null.

**Comment by stephentoub** [comment]
This is an internal method.  Is the behavior you've highlighted causing a problem for the internal code consuming it?

cc: @saurabh500

**Comment by saurabh500** [comment]
This is not a bug. The calling function checks if the connection was null and if it was null, then it checks the state of the connection pool to throw the correct errors.
