### ISSUE TITLE
Implement HttpClientHandler ClientCertificates for UWP

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#21628]
Part of: #20010 epic.

**Comment by stephentoub** [comment]
@davidsh, there are tests still disabled against this issue.  Is that by design?

**Comment by davidsh** [comment]
Not sure.  Which tests are those?

**Comment by stephentoub** [comment]
> Not sure. Which tests are those?

https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=20010&type=

**Comment by davidsh** [comment]
Many tests are disabled using that same issue number. Some of the comments indicate the test hangs on UAP....other tests don't reflect why it was disabled.

We might try re-enabling those tests on UAP and see if we can repro the problem.
