### ISSUE TITLE
Windows.winmd needs to be updated to Windows Insider SDK flight 16225

### ISSUE THREAD

**Issue by Diego-Perez-Botero** [dotnet/corefx#21642]
The current UWP (UAP/UAPILC) implementations of System.Net.WebSockets.Client and System.Net.Http.HttpClient use WinRT APIs. The following high-priority **_.NET Standard 2.0 for UWP_** work requires us to consume new WinRT APIs that are part of the recently-flighted Windows Insider SDK 16225: #7877 #21393 #21102 

In order to call these new APIs, we need to have the Windows.winmd file updated in the CoreFx repo and associated .NET Native toolchain.

- Windows Insider SDK flight 16225 download page: https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK

Of course, we will call the new APIs only if they are present from a runtime perspective: 

```
using Windows.Foundation.Metadata;
     
if (ApiInformation.IsPropertyPresent("Windows.Networking.Sockets.WebSockets.MyNewAPI"))
{
    // Use the new API if present…
}

```

CC: @davidsh @weshaggard @yizhang82 @tijoytom @safern @DavidGoll @danmosemsft @joperezr

**Comment by davidsh** [comment]
cc: @joshfree

**Comment by joshfree** [comment]
Joe is picking this up per the email thread last night.

**Comment by joperezr** [comment]
corefx side change done.

**Comment by tijoytom** [comment]
TFS updated , should be in tomorrows build

**Comment by Diego-Perez-Botero** [comment]
Thanks for the quick turnaround, @tijoytom and @joperezr  ! 🥇
