### ISSUE TITLE
How do I use TextWriter.Synchronized in netcoreapp1.1

### ISSUE THREAD

**Issue by krzysztofdrys** [dotnet/corefx#21657]
I want to use [TextWriter.Synchronized](https://msdn.microsoft.com/en-us/library/system.io.textwriter.synchronized(v=vs.110).aspx) method in my app. My target framework is: `netcoreapp1.1`. 

This is the program I am trying to compile:

    using System;
    using System.IO;
    
    namespace program
    {
        class Program
        {
            static void Main(string[] args)
            {
                using (var log = File.CreateText("out.log"))
                {
                    var syncedLog = TextWriter.Synchronized(log);
                }
             }
        }
    }

This is my csproj file:

    <Project Sdk="Microsoft.NET.Sdk">
      <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp1.1</TargetFramework>
      </PropertyGroup>
    </Project>

Unfortunatelly, this does not work: 

    > dotnet run
      Program.cs(12,47): error CS0117: 'TextWriter' does not contain a definition for 'Synchronized' 

How do I fix this?

I am sorry, if this is a wrong repository to ask this question. Please redirect me, if you fell there is one more appropriate.

**Comment by danmosemsft** [comment]
@krzysztofdrys `TextWriter.Synchronized` is not available until .NET Core 2.0: https://apisof.net/catalog/System.IO.TextWriter.Synchronized(TextWriter)

You will have to perform your own synchronization. StackOverflow might be a good place for questions about that.

**Comment by krzysztofdrys** [comment]
Thanks for you answer, much appreciated. 

I have already asked this [question on StackOverflow](https://stackoverflow.com/questions/44699441/how-do-i-use-textwriter-synchronized-in-netcoreapp1-1) some time ago. Well, now I can answer it myself. :)
