### ISSUE TITLE
Create meta-package for .NET Framework support

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#21664]
We have added a number of nuget packages to fill the API gaps in .NET Core and a lot of them are part of the Microsoft.NETCore.App but there are still a lot that aren't. To help folks with porting we should create another meta-package that will reference all the libraries that we have individual nuget packages that are above Microsoft.NETCore.App and are to help bridge the gap with .NET Framework.

cc @Petermarcu @ericstj @terrajobst 

Proposed list of packages:

```
System.CodeDom
System.ComponentModel.Annotations
System.Configuration.ConfigurationManager
System.Data.SqlClient
System.DirectoryServices
System.DirectoryServices.AccountManagement
System.DirectoryServices.Protocols
System.IO.FileSystem.AccessControl
System.IO.Packaging
System.IO.Pipes.AccessControl
System.IO.Ports
System.Numerics.Vectors
System.Reflection.TypeExtensions
System.Security.AccessControl
System.Security.Cryptography.Cng
System.Security.Cryptography.Pkcs
System.Security.Cryptography.ProtectedData
System.Security.Cryptography.Xml
System.Security.Permissions
System.Security.Principal.Windows
System.ServiceProcess.ServiceController
System.Text.Encoding.CodePages
System.Threading.AccessControl
System.Threading.Tasks.Dataflow
```

For reference all the extra nuget packages we produce can be seen at https://github.com/dotnet/versions/blob/master/build-info/dotnet/corefx/master/Latest_Packages.txt I've filtered that list to just things that already exist in the .NET Framework.

**Comment by Petermarcu** [comment]
We had agreed on a name last week. I think we just Said Microsoft.NETFramework.Compatibility.Windows. @terrajobst is that what you recall? We had also discussed just dropping Windows because it could be inferred because that is where .NET Framework runs. I have mixed opinions on that part.

**Comment by weshaggard** [comment]
We don't want NETCore in the package name to indicate it is about adding support to .NET Core?

**Comment by ericstj** [comment]
Id should try and be short but specific.  It doesn't need to be complete, just make sure it doesn't overlap with something else that would like to use the same name.  You can add more detail in the name or description to provide detail.

**Comment by Petermarcu** [comment]
Should we categorize the ones that we expect to just work on Windows vs which ones can work everywhere?

**Comment by weshaggard** [comment]
>Should we categorize the ones that we expect to just work on Windows vs which ones can work everywhere?

We could but I'm not sure the distinction is all that interesting given that we want to focus this on Window .NET Framework support which all of them should support.

**Comment by Petermarcu** [comment]
The OpenSSL one for example only works on Linux/Mac though and is not in .NET Framework right?

**Comment by weshaggard** [comment]
>The OpenSSL one for example only works on Linux/Mac though and is not in .NET Framework right?

Fair I overlooked that one I will remove it.
