### ISSUE TITLE
Fix Microsoft.VisualBasic tests on UapAot

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#21682]
Some new tests were added recently which are not working in uapaot. This issue is to track the work of investigating, fixing and enabling (the ones that should be re-enabled) them.

FYI: @hughbe who recently added them.

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/pull/21683

**Comment by tijoytom** [comment]
@AtsushiKan Can you please take quick look ?
@joshfree
