### ISSUE TITLE
test bug: test helper treats non-serial ports as serial ports

### ISSUE THREAD

**Issue by pjanotti** [dotnet/corefx#21699]
This is a tiny test issue that I hit on my box. The comparison made by the helper ended up treating some ports like "COMPATIBLEBUS*" as serial ports, and that broke the `AllHelperPortsAreInGetPortNames` test.

**Comment by pjanotti** [comment]
@karelz it seems that I don't have rights to add labels (or my noobness is showing...)

Per area owership /cc @JeremyKuhne and @ianhays - this is just a single line change in a test helper.

**Comment by karelz** [comment]
@pjanotti sent email to @richlander to fix your permissions.
