### ISSUE TITLE
2.0.0 Core Tests: Fire issues on Fedora.26.Amd64

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#21698]
Detail: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170629.01

Several tests have fireball on Fedora.26.Amd64

**Comment by danmosemsft** [comment]
fixed
