### ISSUE TITLE
UWP ILC Tests: Serveral tests have fireball on Windows.10.Amd64-arm

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#21696]
Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170629.01

Configuration: Windows.10.Amd64-arm

**Comment by karelz** [comment]
cc @danmosemsft @tijoytom

**Comment by danmosemsft** [comment]
pinged engineering

**Comment by danmosemsft** [comment]
please reactivate if reproes more

**Comment by Jiayili1** [comment]
This issue is still repro on build #20170703.01, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170703.01

**Comment by danmosemsft** [comment]
@joperezr is alreayd looking.

**Comment by joperezr** [comment]
talked to @ChadNedzlek about this, looks like it was a transient Azure issue, so I will close this issue since we believe this should be solve in next run. Please do reactivate if it happens again.

**Comment by Jiayili1** [comment]
This issue is still repro, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170711.01

**Comment by ChadNedzlek** [comment]
We've added some logging around this, but until it happens again, there isn't much we can do. So we'll wait and see.

**Comment by joperezr** [comment]
@MattGal made some changes on re-queueing yesterday to make this more reliable, and I already see that it didn't repro again today, so I'll close this for now.

**Comment by MattGal** [comment]
Yup, the fix is in prod and I've validated it.  It was a VERY subtle bug, but fixed for sure.
