### ISSUE TITLE
ActionBlock<T>.Post fail

### ISSUE THREAD

**Issue by ilab-admin** [dotnet/corefx#21715]
We use many ActionBlock<T> and create instances using constructors that accept only Action<T> without any configurations. So it should be unbound. But in some cases method Post returns false. What can cause this issue?

**Comment by stephentoub** [comment]
Post on an ActionBlock that's unbounded should only return false if the ActionBlock has been closed to additional messages, which could happen for example if someone called Complete on the block or if the block's delegate threw an exception that went unhandled and caused the block to fault.

**Comment by GreatFireWall** [comment]
> if the block's delegate threw an exception that went unhandled and caused the block to fault.

The answer solve a bug that I find it 2 days. Please add this to the document.

**Comment by stephentoub** [comment]
> Please add this to the document

The documentation says:
https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/dataflow-task-parallel-library
"We recommend that you handle exceptions in the bodies of such blocks. However, if you are unable to do so, the block behaves as though it was canceled and does not process incoming messages."

What additional information would you like to see?  Or you just want the above to be made more prominent?

Thanks.

**Comment by GreatFireWall** [comment]
I think add to the `Post` and `SendAsync` methods' remarks of each block will be better. 

Because it is usually people found that they return false to realize that something is wrong, normal people will start looking the docs of  `Post` and `SendAsync`.

**Comment by stephentoub** [comment]
> I think add to the Post and SendAsync methods' remarks/returns of each block will be better.

@GreatFireWall, the docs are open source.  Please feel free to submit a PR to https://github.com/dotnet/dotnet-api-docs with the details you're hoping for. Thanks!
