### ISSUE TITLE
When compiling in TFS, using the ECMA key requires setting <AssemblyKeyType> before dir.props import

### ISSUE THREAD

**Issue by FiveTimesTheFun** [dotnet/corefx#2171]
Because the TFS build targets sets <SkipSigning>true, sign.targets won't respect the UseECMAKey property.  Additionally, because dir.props sets <AssemblyOriginatorKeyFile> based on the AssemblyKeyType conditional, AssemblyKeyType needs to be set in the project before importing dir.props.

**Comment by mellinoe** [comment]
This is no longer relevant, closing.
