### ISSUE TITLE
Verify that Interop.Kernel32.SetFileCompletionNotificationModes is available in UAP

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#21726]
Ensure that Interop.Kernel32.SetFileCompletionNotificationModes Win32 API is available in the Store Profile.

Related to the discussion in #20212

**Comment by caesar1995** [comment]
Last time I built the project without the CompletionPortHelper.Uap.cs in UAP mode, the compiler complained that "error: SetFileCompletionNotificationModes() is not supported on UAP". But now the error goes away.

Besides, I have run the WACKVerify tool, no failures were detected.
![capturewack](https://user-images.githubusercontent.com/8537784/27708161-d18f0dac-5ccc-11e7-88dd-1c1d1aa042e0.PNG)


@danmosemsft Could you please confirm?

**Comment by caesar1995** [comment]
Had offline discussion with @danmosemsft , the API is available in UAP.
