### ISSUE TITLE
Throw PNSE for  Process.Modules and Process.MainModule in UWP

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#21728]
We cannot use K32EnumProcessModules in UWP as it's not on the approved list.

It’s used by Process.Modules and Process.MainModule -- usage is low and there's workarounds so just throw PNSE for those in UWP only.

**Comment by danmosemsft** [comment]
@sepidehMS

**Comment by danmosemsft** [comment]
then delete from src\System.Diagnostics.Process\src\PinvokeAnalyzerExceptionList.analyzerdata.uap

**Comment by stephentoub** [comment]
> so just throw PNSE for those in UWP only.

Rather than throwing, can we do something like what we do on macOS?
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessManager.OSX.cs#L107-L110

**Comment by danmosemsft** [comment]
Sounds good to me. The usage for MainModule is about 5x higher than Modules.
