### ISSUE TITLE
Turn netcore vs netfx apicompat checks into errors

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#21722]
To help with compat issues like https://github.com/dotnet/corefx/pull/21388/files#r123627397 we need to turn the ApiCompat runs on all the time and make them errors. 

The start of this work is in branch https://github.com/weshaggard/corefx/tree/EnableNetFxApiCompat but it still needs some work before it passes. 

cc @ericstj @danmosemsft

**Comment by weshaggard** [comment]
This is to make any additions to shims\ApiCompatBaseline.netcoreapp.netfx461.txt cause a build error. Treat it as a baseline.

We don't see this as essential for 2.1.

**Comment by ViktorHofer** [comment]
I don't think we absolutely need this. Should we close it? @danmosemsft @ericstj

**Comment by danmosemsft** [comment]
Your call
