### ISSUE TITLE
 Possible feature request: Introduce Task.Empty property

### ISSUE THREAD

**Issue by am11** [dotnet/corefx#2173]
I am not entirely sure if there is a better way of returning an empty `Task` instead of using `Task.Factory` like this:

```c#
// in some abstract class
protected virtual Task PostWritingResult(CompilerResult result)
{
    return Task.Factory.StartNew(() => { });
    // the more ugly version could be:
    // return Task.FromResult<dynamic>(null);
}
```

If we just return `null`, it throws NER on `await` etc.

Would it make sense to have `Task.Empty` property at API level (in `System.Threading.Tasks`) for better readability?

**Comment by akoeplinger** [comment]
[Task.CompletedTask](https://msdn.microsoft.com/en-us/library/system.threading.tasks.task.completedtask(v=vs.110).aspx) should be what you want and is already there :)

**Comment by am11** [comment]
@akoeplinger, thank you much! 
I changed the target framework to 4.6 and found it.  :)
It wasn't available till 4.5.2, but probably added in 4.5.3, don't have that installed. The MSDN article states: ".NET Framework 4.6 and 4.5" on top and then "Supported in: 4.6" under Version Information heading.

**Comment by akoeplinger** [comment]
Yep, it's [new in .NET 4.6](http://blogs.msdn.com/b/pfxteam/archive/2015/02/02/new-task-apis-in-net-4-6.aspx), so I'm a bit surprised that MSDN would show it as "and 4.5".

**Comment by am11** [comment]
[This article](http://blogs.msdn.com/b/dotnet/archive/2014/10/06/announcing-october-2014-updates-to-net-framework-vnext-asp-net-vnext-and-net-native-in-visual-studio-14-ctp4.aspx,) lists it as new feature in .NET Framework 4.5.3 and in the "diff from the .NET Framework 4.5.2 to .NET Framework 4.5.3 [[excel](https://dotnetweb.blob.core.windows.net/blog/NetFramework_452to453_diff.xlsx)]" it lists `CompletedTask` as added property in mscorlib. I think it was later when v4.5.3 was promoted as v4.6.
