### ISSUE TITLE
Using WindowsRuntimeBuffer should not require rd.xml

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#21744]
From @yizhang82 in #21658 

> @hughbe @safern The MissingMetadataException doesn't make sense to me. It looks like there is a bug in latest .NET native. We should not require people to add WindowsRuntimeBuffer in rd.xml. @tijoytom Can you help take a look?
The exception diff seems to be a result of overly aggressive optimization. I remember @hoyMS mentioned something like this in the past. If we keep running into issues like these, we should consider turning off that particular optimization, at least in our testing. And if that optimization doesn't bring us a lot of value, we should consider simply turn it off in the compiler by default.

The failing tests were fixed by updating the `rd.xml` file.

The failing tests were:
- IsSameData_Buffer_ReturnsExpected
- AsStream_Buffer_Success

**Comment by yizhang82** [comment]
@hughbe thanks for logging the issue.
@tijoytom Have you got a chance to look into this?

**Comment by morganbr** [comment]
@tijoytom, it would be particularly good to know whether the MissingMetadataException occurs during normal usage or because XUnit is reflecting on random objects.

**Comment by tijoytom** [comment]
This is really an xunit reflection issue , xunit tries to reflect on the "ToString()" method of IBuffer ( which in this case is WindowsRuntimeBuffer) and fails.Using windowsruntime buffer as suhc do not need rd.xml , here rd.xml is required since xunit does reflection

**Comment by tijoytom** [comment]
I am closing this issue since the current rd.xml for the tests works
