### ISSUE TITLE
System.DirectoryServices.AccountManagement.Tests.PrincipalContextTests.ValidateCredentials_IncorrectUserNamePassword_ThrowsException failed with "Xunit.Sdk.ThrowsException" in CI

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#21759]
Failed test: System.DirectoryServices.AccountManagement.Tests.PrincipalContextTests.ValidateCredentials_IncorrectUserNamePassword_ThrowsException 

Configuration: outerloop_netcoreapp_win7_release

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_release/102/testReport/System.DirectoryServices.AccountManagement.Tests/PrincipalContextTests/ValidateCredentials_IncorrectUserNamePassword_ThrowsException/

MESSAGE:
~~~
Assert.Throws() Failure
  Expected: typeof(System.Exception)
  Actual: typeof(System.IO.FileNotFoundException): The network path was not found.\r\n
~~~
STACK TRACE:
~~~
at System.DirectoryServices.AccountManagement.UnsafeNativeMethods.IADs.Get(String bstrName) 
at System.DirectoryServices.AccountManagement.CredentialValidator.BindSam(String target, String userName, String password) 
in D:\j\workspace\outerloop_net---15cfbbd5\src\System.DirectoryServices.AccountManagement\src\System\DirectoryServices\AccountManagement\Context.cs:line 134 
at System.DirectoryServices.AccountManagement.Tests.PrincipalContextTests.<>c__DisplayClass21_0.<ValidateCredentials_IncorrectUserNamePassword_ThrowsException>b__0() 
in D:\j\workspace\outerloop_net---15cfbbd5\src\System.DirectoryServices.AccountManagement\tests\PrincipalContextTests.cs:line 297
~~~

**Comment by danmosemsft** [comment]
@hughbe one of your new tests ..thoughts? not sure if this is flaky, or it's win7 specific.

**Comment by hughbe** [comment]
The exception trace for this test method is
```
System.Exception: The user name or password is incorrect.

     at System.DirectoryServices.AccountManagement.UnsafeNativeMethods.IADs.Get(String bstrName)
     at System.DirectoryServices.AccountManagement.CredentialValidator.BindSam(String target, String userName, String p
  assword)
     at System.DirectoryServices.AccountManagement.CredentialValidator.Validate(String userName, String password)
     at System.DirectoryServices.AccountManagement.PrincipalContext.ValidateCredentials(String userName, String password)
     at System.DirectoryServices.AccountManagement.Tests.PrincipalContextTests.<>c__DisplayClass21_0.<ValidateCredentia
  ls_IncorrectUserNamePassword_ThrowsException>b__0()
     at Xunit.Assert.RecordException(Func`1 testCode)
  Finished:    System.DirectoryServices.AccountManagement.Tests
```

The code for the test is
```cs
[ConditionalFact(nameof(PlatformDetection) + "." + nameof(PlatformDetection.IsNotWindowsNanoServer))]
public void ValidateCredentials_IncorrectUserNamePassword_ThrowsException()
{
    var context = new PrincipalContext(ContextType.Machine);
    Assert.Throws<Exception>(() => context.ValidateCredentials("userName", "password"));
}
```

Looking at the test message for this failing test "The network path was not found", I'm confused. We're getting the context for the current machine - which should always be found.

If the test is flaky, it's likely to be a configuration issue. I'm trying to stress-test now

**Comment by hughbe** [comment]
Update: I did a quick google around and found this: https://stackoverflow.com/questions/25060655/c-sharp-principalcontext-the-network-path-was-not-found

> I found the answer. It looks that DirectoryServices doesn't work on remote Windows 7 or newer. I guess when a computer is in a workgroup then it is local and we can connect and when it is in a domain then it is remote.

It seems orthoganally related, but I'm not sure

**Comment by danmosemsft** [comment]
@tquerec can you advise whether this is expected behavior here?

I'm not sure how this is "remote" though.

**Comment by v-haren** [comment]
failed again: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_release/106/testReport/System.DirectoryServices.AccountManagement.Tests/PrincipalContextTests/ValidateCredentials_IncorrectUserNamePassword_ThrowsException/

**Comment by hughbe** [comment]
It's failed twice and only on Windows 7: I'd hedge my bets and say it's a Win7 issue

**Comment by Jiayili1** [comment]
Failed again in CI: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_release/148/testReport/System.DirectoryServices.AccountManagement.Tests/PrincipalContextTests/Ctor_ContextType_Name_Container_UserName_Password_contextType__Machine__name__null__container__null__userName____userName____password____password___/

**Comment by Jiayili1** [comment]
failed again in CI: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_release/154/testReport/

**Comment by Jiayili1** [comment]
failed again: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_debug/178/testReport/System.DirectoryServices.AccountManagement.Tests/PrincipalContextTests/Ctor_ContextType_Name_Container_UserName_Password_contextType__Machine__name__null__container__null__userName____userName____password____password___/

**Comment by Jiayili1** [comment]
Now it fails: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170825.01/workItem/System.DirectoryServices.AccountManagement.Tests/analysis/xunit/System.DirectoryServices.AccountManagement.Tests.PrincipalContextTests~2FValidateCredentials_IncorrectUserNamePassword_ThrowsException

The test `System.DirectoryServices.AccountManagement.Tests.PrincipalContextTests/ValidateCredentials_IncorrectUserNamePassword_ThrowsException` has failed.

Assert.Throws() Failure\r
    Expected: typeof(System.Exception)\r
    Actual:   (No exception was thrown)

        Stack Trace:

           at System.DirectoryServices.AccountManagement.Tests.PrincipalContextTests.ValidateCredentials_IncorrectUserNamePassword_ThrowsException()
Build : Master - 20170825.01 (Core Tests)
Failing configurations:
- Windows.81.Amd64-x86
  - Release
- Windows.7.Amd64-x86
  - Release
- Windows.10.Amd64.Core-x86
  - Release
- Windows.10.Amd64-x86
  - Release
- Windows.81.Amd64-x64
  - Release
- Windows.7.Amd64-x64
  - Release
- Windows.10.Amd64.Core-x64
  - Release
- Windows.10.Amd64-x64
  - Release

**Comment by danmosemsft** [comment]
Old.
