### ISSUE TITLE
[Proposal] Change internal type name System.Net.WebFileStream to System.Net.FileWebStream

### ISSUE THREAD

**Issue by 4creators** [dotnet/corefx#21763]
After porting one of my projects from .NET Framework 4.6.1 to netcoreapp2.0 target I have noticed some failing tests due to a tests dependency on netfx internal type name System.Net.FileWebStream. This type has different name in .Net Core - [System.Net.WebFileStream](https://github.com/dotnet/corefx/blob/master/src/System.Net.Requests/src/System/Net/FileWebRequest.cs#L311).

Although I am aware of consequences of taking dependencies on internal framework types (they are not guaranteed to not change in the future) I think that in this case it would be reasonable to use identical type names for types performing the very same functions across related frameworks.

Going even further it could be quite useful to have this type exposed in public API as it is exposed publicly anyway as a return type of some framework methods i.e. 

```C#
public Stream System.Net.WebClient.OpenRead(Uri uri);
```
That change would allow safe use of return type in scenarios where it is used to differentiate source of data returned.

**Comment by svick** [comment]
> Going even further it could be quite useful to have this type exposed in public API as it is exposed publicly anyway as a return type of some framework methods

Being returned from a method is not the same as being publicly exposed.

> That change would allow safe use of return type in scenarios where it is used to differentiate source of data returned.

Could you explain why exactly do you need that? Maybe "source of data" could be added as a public property to `Stream`.

**Comment by karelz** [comment]
Dependencies on internal types is very slippery slope. I would like to prevent that as much as possible. Same holds for private reflection.

If you think we need a new public API, please follow [API review process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md) and describe API shape, motivation, usage examples, etc.
The API shape should not be shaped around existing internal APIs, but rather focus on customers' need.
