### ISSUE TITLE
Process.Start("cmd.exe") launches inside existing console window (on Windows)

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#21767]
_From @danwalmsley on June 30, 2017 8:57_

I would expect this code to launch a separate console window.
```
using System;
using System.Diagnostics;

namespace console_test
{
    class Program
    {
        static void Main(string[] args)
        {
            Process.Start("cmd.exe");
            Console.ReadKey();
        }
    }
}
```

_Copied from original issue: dotnet/coreclr#12571_

**Comment by danwalmsley** [comment]
@jkotas thanks for putting issue in the right place.

I found a workaround for people currently having this problem:

```
startInfo.FileName = "cmd.exe";
startInfo.Arguments = $"/c start cmd.exe";
```

**Comment by krwq** [comment]
@danwalmsley when you open regular cmd.exe and type `cmd.exe` it also does it in the same window. I believe this is intentional. `/c` seems like a correct approach:
```
/C      Carries out the command specified by string and then terminates
```

**Comment by danmosemsft** [comment]
It is a divergence from desktop framework. It's probably because UseShellExecute is false by default for Core, not true. I'l check.

**Comment by danmosemsft** [comment]
Yes, that's the reason. @danwalmsley if you change to this you get the behavior you want.
```c#
using System;
using System.Diagnostics;

namespace console_test
{
    class Program
    {
        static void Main(string[] args)
        {
            var psi = new ProcessStartInfo("cmd.exe");
           psi.UseShellExecute = true;
            Process.Start(psi);
            Console.ReadKey();
        }
    }
}
```

This defaulting was a conscious change in behavior: https://github.com/dotnet/corefx/issues/18949#issuecomment-302802961

Many thanks for the report -- we are always interested in cases where our behavior is different to desktop.

**Comment by stephentoub** [comment]
> if you change to this you get the behavior you want

FYI, that requires .NET Core 2.0.

**Comment by jnm2** [comment]
> FYI, that requires .NET Core 2.0.

Which answers the question I was just about to ask. =)
