### ISSUE TITLE
Silent Failure: XmlSerializer.Deserialize Method (XmlReader)

### ISSUE THREAD

**Issue by KaelumYodi** [dotnet/corefx#2177]
I attempted to file this on Connect, but it appears that even though Connect states that it is still accepting issues, it is closed.  There is a bug in the current release version (4.5.2) that fails w/o any errors, on the deserialization of a property of a class that is defined as a List<string>.  I haven't tried lists of other types, but they are probably affected as well, and this only affects Deserialize, not Serialize.

There are 2 classes below, and both serialize properly, in the exact same way.  However, the Works class will deserialize properly, while the DoesNotWork class will not.  The DoesNotWork class will end up with an Items property that contains a list with zero items, when 1 or more items exist.  We discovered this in a property that has code in both the get and set accessors, while all properties that don't have any get or set code work perfectly.

```C#
[Serialize]
[XmlRoot("root")]
public class Works
{
	[XmlElement("items")]	
	public List<string> Items { get; set; }
}


[Serialize]
[XmlRoot("root")]
public class DoesNotWork
{
	private List<string> _items;

	[XmlElement("items")]	
	public List<string> Items
	{
		get { return _items; }
		set { _items = value; }
	}
}
```

**Comment by khdang** [comment]
@KaelumYodi  By [Serialize] do you mean the [Serializable] attribute?
I've tried this in both NetCore and Desktop but I didn't get the repro. Can you provide the code that cause the incorrect behavior?

```
public static void TestDoesNotWork()
        {
            var s = new XmlSerializer(typeof(DoesNotWork));
            var o1 = new DoesNotWork() { Items = new List<string>() { "a", "b" } };
            using (var stream = new MemoryStream())
            {
                s.Serialize(stream, o1);
                stream.Position = 0;
                var o2 = (DoesNotWork)s.Deserialize(stream);
                if (o2.Items.Count != o1.Items.Count || !o2.Items.SequenceEqual(o1.Items))
                {
                    throw new Exception("DoesNotWork");
                }
            }
        }
```

**Comment by khdang** [comment]
@KaelumYodi I'm closing this since I couldn't see the behavior you described above. If you can provide the repro code I will look into this again.
