### ISSUE TITLE
No testResults.xml for System.Data.Common.Tests in UAPAOT

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#21776]
This tests are failing fast. I just investigated and the tests that are causing this to happen are: [SqlXmlTest](https://github.com/dotnet/corefx/blob/ad697e016a5ed01a698ba780ea9dda0ed5cee901/src/System.Data.Common/tests/System/Data/SqlTypes/SqlXmlTest.cs#L34)

It seems like all of them cause this tests to fail fast and not produce testResults.xml

My guess since they are failing fast and only in all the Debug runs is that a Debug.Assert is failing.

cc: @saurabh500 @krwq @danmosemsft @joshfree

**Comment by safern** [comment]
I will go ahead and disable the whole class so that we start having testResults.xml for this test project

**Comment by saurabh500** [comment]
@safern these are the culprits https://github.com/dotnet/corefx/issues/19202

**Comment by saurabh500** [comment]
I suggest reverting the PR https://github.com/dotnet/corefx/pull/21648

**Comment by saurabh500** [comment]
Also dont disable the whole class, there are some tests in there which run

**Comment by safern** [comment]
Closing as it is a dupe of: #19202 

@saurabh500  I will disable only the ones pointed in that issue then.
