### ISSUE TITLE
UWP test runner metadata needs to be updated to Windows Insider SDK flight 16225

### ISSUE THREAD

**Issue by Diego-Perez-Botero** [dotnet/corefx#21786]
The Windows.winmd files used by the CoreFX repo and associated .NET Native toolchain were updated this week to the Windows.winmd corresponding to Windows Insider SDK flight 16225. For full context, see #21642
 
I’m now working on #21102 (out for PR - #21755) and the new code that references new APIs compiles just fine. However, running the UWP tests (i.e., msbuild /t:rebuildandtest /p:TargetGroup=uap) leads to a bunch of MissingMethodExceptions, such as:
 
> System.Exception: Unknown ---> System.MissingMethodException: Method not found: 'Void Window
>   s.Networking.Sockets.MessageWebSocketControl.put_ReceiveMode(Windows.Networking.Sockets.MessageWebSocketReceiveMode)'
 
All new API calls are guarded by _IsPropertyPresent_ checks already, and the code is executing on a machine that contains the new APIs (which is why the new code attempts to use them). After some analysis, we realized that these exceptions are due to the test runner’s UWP app having been compiled against an old Windows 10 SDK. Could you please help us update the test runner to be compiled against the RS3 16225 SDK? :)
 
Please, let me know how I can help.
 
P.S. Compiling against pre-RS3 SDKs won’t be supported for NETStandard20, so this is just a test issue.
P.P.S. All tests pass in UAPAOT mode, since they execute outside of a UWP package.

CC: @davidsh @weshaggard @yizhang82 @tijoytom @safern @DavidGoll @danmosemsft @joperezr @joshfree @MattGal

**Comment by yizhang82** [comment]
@Diego-Perez-Botero The problem is likely that CoreCLR F5 tests didn't carry a copy of windows.winmd with them (and also the host needs to point to it using a magic variable as well). Without it, CoreCLR will be looking at the Windows metadata on the machine, which by definition won't be available in down-level OS. As a result, type loader will complain about missing metadata at *runtime*, and this has nothing to do with compile time, at least not in the CoreCLR case. This is the adaptive lightup scenario.
For UWP AOT tests, they compile Windows metadata into the app itself, and therefore don't need to carry windows.winmd and don't have this problem.

**Comment by yizhang82** [comment]
See https://github.com/dotnet/core-setup/blob/master/src/uwp/Host/UWPHost/UWPHost.cpp#L86 on how to make this work.

**Comment by Diego-Perez-Botero** [comment]
Thanks for the info, Yi. The exceptions are happening on a machine running a Windows build that's greater than 16225, so wouldn't the Windows metadata on the machine be OK?

**Comment by yizhang82** [comment]
It's likely a different branch so the API haven't made there yet. Or there is a breaking change. you can confirm what exactly is the problem by running `ildasm C:\windows\system32\WinMetadata\Windows.Networking.winmd`

**Comment by Diego-Perez-Botero** [comment]
Well...you were right, Yi! I manually replaced the Windows.winmd that was under C:\corefx2\corefx\bin\Windows_NT.AnyCPU.Debug\System.Net.WebSockets.Client.Tests\netstandard\WinMetadata with the 16225 Windows.winmd, and now all the tests pass!!!

**Comment by Diego-Perez-Botero** [comment]
So....where is the test runner getting its Windows.winmd from? I guess that's what we need to update.

**Comment by davidsh** [comment]
>So....where is the test runner getting its Windows.winmd from? 

The test-runtime might be bin placing that older Windows.winmd.....or the UAP Test Runner is bin placing it.

**Comment by Diego-Perez-Botero** [comment]
Below is a list of all the windows.winmd files in my corefx clone (which I fetched today). Those that need updating are in **bold**:

BYTES     PATH
5,740,544 c:\corefx2\corefx\bin\AnyOS.AnyCPU.Debug\winrt\uap\Windows.winmd
5,740,544 c:\corefx2\corefx\bin\ref\uap\Windows.winmd
**5,348,864 c:\corefx2\corefx\bin\testhost\uap-Windows_NT-Debug-x64\Runner\WinMetadata\Windows.winmd
5,348,864 c:\corefx2\corefx\bin\Windows_NT.AnyCPU.Debug\System.Net.WebSockets.Client.Tests\netstandard\WinMetadata\Windows.winmd
5,348,864 c:\corefx2\corefx\packages\microsoft.dotnet.uap.testtools\1.0.12\Tools\arm\Runner\WinMetadata\Windows.winmd
5,348,864 c:\corefx2\corefx\packages\microsoft.dotnet.uap.testtools\1.0.12\Tools\x64\Runner\WinMetadata\Windows.winmd
5,348,864 c:\corefx2\corefx\packages\microsoft.dotnet.uap.testtools\1.0.12\Tools\x86\Runner\WinMetadata\Windows.winmd**
5,740,544 c:\corefx2\corefx\packages\microsoft.targetingpack.private.winrt\1.0.4\lib\netstandard1.0\Windows.winmd
5,740,544 c:\corefx2\corefx\packages\testilc.amd64ret\1.0.0-beta-25430-00\TestILC\ExternalFiles\TargetPlatformSdkMetadataPath\windows.winmd
5,740,544 c:\corefx2\corefx\packages\testilc.armret\1.0.0-beta-25430-00\TestILC\ExternalFiles\TargetPlatformSdkMetadataPath\windows.winmd
5,740,544 c:\corefx2\corefx\packages\testilc.x86ret\1.0.0-beta-25430-00\TestILC\ExternalFiles\TargetPlatformSdkMetadataPath\windows.winmd

**Comment by Diego-Perez-Botero** [comment]
Essentially....the **microsoft.dotnet.uap.testtools** package is what is yet to be updated with the correct Windows.winmd file ;)

**Comment by davidsh** [comment]
The test runner will have to be updated as well (see CSPROJ)

https://github.com/dotnet/buildtools/blob/master/src/xunit.runner.uap/XUnit.Runner.Uap.csproj

**Comment by Diego-Perez-Botero** [comment]
@joperezr - are you the right person to update the Windows.winmd file in the **microsoft.dotnet.uap.testtools** package, or should I reassign this to someone else? Thanks!

**Comment by joperezr** [comment]
Yes, I am the right person, but I first need to make sure that by changing this I won't break the scenario of running the tests on a RS2 machine. Today most of four developers working for UAP 6.0 are working on RS2 OS, plus our CI test runs run on RS2 as well, so I will first verify that this change won't break that flow. If it doesn't, then I'll go ahead and do the update.

**Comment by Diego-Perez-Botero** [comment]
@joperezr - is there an ETA on the metadata update? Thanks! :)

**Comment by pjanotti** [comment]
This also blocks trying the new API mentioned in #21156.

**Comment by yizhang82** [comment]
@joperezr Having new metadata won't break running down-level as long as RS3-aware code is properly guarded with IsApiPresent. It'd be good to validate it in a RS2 machine, of course.
