### ISSUE TITLE
Delete the 4.5.0-preview2 packages from myget

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#21781]
We had a couple builds of master that used the post-2.0 versioning (4.5.0) with the preview2 string.  This is bogus.  The packages are causing problems for folks who try to "get latest" and are getting old builds.  /cc @weshaggard 

@dagood can you help script this with your NuGet-CLI-fu?

**Comment by dagood** [comment]
Sure. Looks like just these two builds got published:

https://github.com/dotnet/versions/blob/61076147ca863b39fc5d32253f31d889ccfd1d12/build-info/dotnet/corefx/master/Last_Build_Packages.txt
https://github.com/dotnet/versions/blob/d74fba51a1bd5b9374facd4bb57fa51954859a38/build-info/dotnet/corefx/master/Last_Build_Packages.txt

I'll go ahead and delete them from MyGet. (If someone needs them for some reason, they're in storage.)

**Comment by ericstj** [comment]
Awesome, thank you @dagood

**Comment by dagood** [comment]
No problem. The nuget calls are all done to unlist those builds, and MyGet will just need a little time to update.

**Comment by ericstj** [comment]
This is now irrelevant due to https://github.com/dotnet/corefx/pull/21685
