### ISSUE TITLE
Feature Request: leaveOpen in System.Net.Http.StreamContent 

### ISSUE THREAD

**Issue by CXuesong** [dotnet/corefx#21790]
Hi, recently I'm using `StreamContent` with `HttpClient` to perform some file uploading operations. When I tried to implement the retry logic, I found out that

* The passed-in `HttpContent` contained in `HttpRequestMessage` got disposed in `HttpClient.SendAsync`.
* The underlying `Stream` in `StreamContent` [got disposed](https://github.com/dotnet/corefx/blob/6bf1e7c3032d3c24d5a41bbd880549ef4a8de2da/src/System.Net.Http/src/System/Net/Http/StreamContent.cs#L85) in `StreamContent.Dispose()` invocation.

This means that if I have passed in a `Stream` in `StreamContent`'s ctor, the very `Stream` will be inevitably disposed after the first `HttpClient.SendAsync` invocation. This is not good, especially if the `StreamContent`-user is agnostic about how to reconstruct another brand-new `Stream` instance (but still can seek the position so the `Stream` will be at the same position as it is in the first call, as long as its `CanSeek` is `true`).

I ended up writing [my own version of `StreamContent`](https://github.com/CXuesong/WikiClientLibrary/blob/3a3ece77923beb31956afee973e72e17fe1d2f4f/WikiClientLibrary/HttpContentEx.cs#L65) that won't dispose the underlying `Stream` when disposed. Still, I hope there will be some `leaveOpen`-like parameter in the constructor of `StreamContent`, like [the constructor of `StreamReader`](https://github.com/dotnet/corefx/blob/6bf1e7c3032d3c24d5a41bbd880549ef4a8de2da/src/System.Runtime.Extensions/src/System/IO/StreamReader.cs#L140).

**Comment by davidsh** [comment]
This was already fixed in PR #19082.  We changed the behavior in .NET Core 2.0 to allow scenarios such as yours.

cc: @stephentoub

**Comment by CXuesong** [comment]
Thank you! If I got this right, the .NET Core 2.0 implementation of the `HttpClient` won't dispose the passed-in `HttpContent` after the request, which is great, and this do-not-dispose behavior currently only exists on .NET Core 2.0, so I can't rely on it, for now.

Still, I have a series of questions on what I should do, were I to make use of this new behavior (in the future)
* Do I have to upgrade the .NET Standard version of my library?
* Do I have to tell the library users to upgrade their .NET Core/Framework versions?
* Or to simply tell them to upgrade their `System.Net.Http` NuGet package version?

Finally, I saw "OOB"s in your refered issue, and curious about what it means…

**Comment by davidsh** [comment]
>Do I have to upgrade the .NET Standard version of my library?

Yes.  You will need the .NET Core 2.0 version of this binary that has these changes. By the way, the packaging layouts have changed and there is no longer a separate System.Net.Http NuGet package. Instead, there is a combined Netstandard.library package with many binaries in it.  You'll need the "2.0" version of that.

>Or to simply tell them to upgrade their System.Net.Http NuGet package version?

See above. There is no separate System.Net.Http NuGet package anymore starting with .NET Core 2.0 releases.

>Do I have to tell the library users to upgrade their .NET Core/Framework versions?

Yes, your library users will need to use the updated binaries. But if your library itself has a depedency to NetStandard2.0 itself, then any consumers of your library would get that dependency themselves. So, they wouldn't necessarily have to reference it directly.

cc: @weshaggard who can explain the revised packaging model of .NET Core 2.0 / NETStandard2.0.

**Comment by CXuesong** [comment]
Oh, now I see. Thank you for your explanation.

Btw, there's another problem with `System.Net.Http.FormUrlEncodedContent`, which doesn't allow the overall encoded content length be larger than 65,520 bytes (See CXuesong/WikiClientLibrary#6). Is it by design or not? If not, is it possible for me to open a PR and propose a fix on it?

**Comment by davidsh** [comment]
>Btw, there's another problem with System.Net.Http.FormUrlEncodedContent, which doesn't allow the overall encoded content length be larger than 65,520 bytes (See CXuesong/WikiClientLibrary#6). Is it by design or not? If not, is it possible for me to open a PR and propose a fix on it?

This is a known issue.  See: https://github.com/dotnet/corefx/issues/1936. Please review that issue and the discussion about it.  You can submit a PR for any issue in the repo.  Please include appropriate tests for any PRs that change code.

**Comment by davidsh** [comment]
CLosing this issue now that the question has been answered.
