### ISSUE TITLE
Android Chrome Cryptographic Exception

### ISSUE THREAD

**Issue by troncomputers** [dotnet/corefx#21791]
Hi!
I'm wondering if this is normal behavior. Sometimes we are getting Cryptographic Exception on Android Chrome. Never happend on desktop. I'm new to ASP, specialy Core.
Project is made with ASP .NET Core WebPages (Razor with seperate model class) with EntityFramework.
I'm not sure if you be able to test/check/try but here it is:
http://kasiarz.optimo365.pl

![screenshot_20170701-202439](https://user-images.githubusercontent.com/29543667/27764604-7c14e914-5e9d-11e7-8a17-f328d6991c61.png)

**Comment by karelz** [comment]
Android Chrome should not be related to the failure as it happens on the server, right?

Please post callstacks as text (in triple tick in markdown). Pictures are very suboptimal and can't be really searched.

The issues seems to originate in `Microsoft.AspNetCore.DataProtection.KeyManagement` -- I would recommend to file the issue on asp/Home repo (or nearby) (with textual callstack please!).
