### ISSUE TITLE
System.Linq.Parallel.Tests crashing in UapAot when building in ret mode

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#21804]
A bunch of tests are crashing when this tests are built in ret mode. If we build them in chk mode the tests run successfully.  The exception thrown that is causing them to crash is the following: 

```
Unhandled exception at 0x581410DF (mrt100_app.dll) in xunit.console.netcore.exe: 0xC0000005: Access violation reading location 0x00000000.
```

One place where I've got the debugger to break on this exception was: https://github.com/dotnet/corefx/blob/master/src/System.Linq.Parallel/src/System/Linq/Parallel/Utils/GrowingArray.cs#L27

Note that this only happens in ret mode for the following configurations:

- Debug x86
- Release x86
- Release Arm
- Debug Arm

This seems to be a codegen bug when running optimization.

cc: @kouvel @danmosemsft @joshfree

**Comment by danmosemsft** [comment]
@joshfree can you suggest an owner?

**Comment by safern** [comment]
I've forced them to be built in chk mode for the affected configurations so that we have a clean run and testResults.xml generated. This is the PR: https://github.com/dotnet/corefx/pull/21805

**Comment by joshfree** [comment]
@VSadov could you take a look?

**Comment by stephentoub** [comment]
Why was this assigned to me?  Isn't this some kind of .NET Native optimization bug, rather than something specific to PLINQ?

**Comment by VSadov** [comment]
This is in TPL, which is not exactly Linq. 
I think @stephentoub is the owner or might know who is. 
However, since this is an Access Violation, the bug is likely to be at the AOT/Runtime level, possibly a GC hole. 
Andd it is kind of disturbing that we see AVs

**Comment by VSadov** [comment]
@stephentoub - right, most likely a .Net Native optimization bug. Added you just for the triage purpose, but it seems rather bad to see AVs

@joshfree - where should this go then? I do not think we are the best equipped with investigating .Net optimization issues over here.

**Comment by joshfree** [comment]
@VSadov feel free to chat with @AtsushiKan or @swgillespie who can point you in the right direction.

**Comment by AtsushiKan** [comment]
Original AV is here - looking inside the RegDisplay and finding a NULL in ebx where it was expecting something more interesting.

https://github.com/dotnet/corert/blob/96869aedb94e5a536332c4f4a6065c2b6433edd1/src/Native/Runtime/RHCodeMan.cpp#L797

High likelihood - whatever's responsible for this is also responsible for https://github.com/dotnet/corefx/issues/21986#issuecomment-313764464

same regdisplay issue just on the unwind path this time.

**Comment by swgillespie** [comment]
cc @AntonLapounov - I thought the issue behind #21986 was x86 only, though.

**Comment by AntonLapounov** [comment]
@safern Do you remember how the crash call stack looked like on ARM?  The x86 unwinder issue is fixed in ProjectN build 25510; the ARM failure must be a different issue.

**Comment by safern** [comment]
> @safern Do you remember how the crash call stack looked like on ARM?

I didn't see the ARM stack trace as I don't have an ARM machine, perhaps @joperezr could help getting you that trace as he has access to the ARM machines

**Comment by AntonLapounov** [comment]
I opened #22040 for ARM and re-enabled x86 ret tests.
