### ISSUE TITLE
Groovy failing in CI for Linux x64 Release Build

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#21807]
`Caused: java.lang.IllegalArgumentException: Failed to prepare archiveArtifacts step` at https://ci3.dot.net/job/dotnet_corefx/job/master/job/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/741/console and other runs.

**Comment by karelz** [comment]
@weshaggard @mellinoe can you please help assess how much it impacts CI? And route as appropriate? Thanks!

**Comment by weshaggard** [comment]
@JonHanna does that just happen sometimes? I've not seen that particular error.

**Comment by mellinoe** [comment]
Hm. I have not seen this either, and the log has since expired. It seems very rare, so I don't think it is having much impact.

**Comment by JonHanna** [comment]
There was a spate of them at the time I reported this, but I haven't seen it since.
