### ISSUE TITLE
.NET Core should consider having the equivalent of Windows.Devices.*

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#21810]
Filing based on feedback:
https://docs.microsoft.com/en-us/uwp/api/

There are lots of basic device operations from GPIO, I2C, to Bluetooth that should be really easy to do on all devices when using .NET Core.

**Comment by shaggygi** [comment]
@Petermarcu I've been hoping this will come eventually.  However, I was thinking it would be API(s) outside of CoreFx as it appears to be Windows specific.  How would this be added to work for other OSes like Raspbian and such?

**Comment by shaggygi** [comment]
@Petermarcu In addition, @tyskink was recently [asking about Windows.Devices.SerialCommunication](https://github.com/dotnet/corefx/issues/984#issuecomment-311631692).  How would serial fall into this effort?

**Comment by shaggygi** [comment]
@jeremylindsayni also has done some good work related to this topic.

https://jeremylindsayni.wordpress.com/2017/04/05/turning-gpio-pins-high-and-low-on-a-raspberry-pi-3-using-net-core-2-and-ubuntu/

**Comment by Petermarcu** [comment]
I just put this here for tracking purposes. It would be totally fine to be in another library outside of corefx. The key is that the .NET ecosystem needs this. I've been looking at @jeremylindsayni's projects. Good stuff there :)

**Comment by shaggygi** [comment]
Yup, this would definitely be a nice feature 👍

**Comment by shaggygi** [comment]
I added this issue link as it is somewhat related.  https://github.com/dotnet/coreclr/issues/12159

I was wondering about UWP support using .NET Core/Standard using topics (Bluetooth, IO, etc.) mentioned here.

**Comment by clrjunkie** [comment]
"System.IO.Connectivity" ?

**Comment by tarekgh** [comment]
adding @juscla comments from the linked issue:

```
So i currently have frameworks that talk to devices over HID protocol, by pinvoking HID.DLL and would like to have this supported in the .netCore going forward. I have a Project that shows you how i am using it.
```

**Comment by brinkie2004** [comment]
Where does CoreFX stand as far as Bluetooth LE is concerned?

**Comment by danmosemsft** [comment]
@richlander is Bluetooth on your radar?

**Comment by shaggygi** [comment]
It'd be great if [Windows.Devices.Bluetooth](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth) moves over similar to where GPIO is headed.

**Comment by rakshith-ravi** [comment]
I strongly believe this is an excellent opportunity to redesign the core APIs (Bluetooth, Serial, maybe IO, etc) from scratch for multi-platform (Desktop, Mobile, Server (maybe?))  usage. The existing APIs can be ported over to the new ones using some sort of an official polyfill library to make the transition smoother.

**Comment by shaggygi** [comment]
@rakshith-ravi This work is going on over at the https://github.com/dotnet/iot repo.  The official APIs are now `System.Device.*`

@danmosemsft  This is somewhat of an older issue and could be closed now that v1 of `System.Device.Gpio` package is nearing release.

**Comment by danmosemsft** [comment]
@shaggygi that makes sense to me.

cc @joperezr
