### ISSUE TITLE
'System.Net.Http.Functional.Tests' failed in ci

### ISSUE THREAD

**Issue by v-haren** [dotnet/corefx#21817]
/mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug/Tools/tests.targets(354,5): error : One or more tests failed while running tests from 'System.Net.Http.Functional.Tests' please check /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug/bin/Unix.AnyCPU.Debug/System.Net.Http.Functional.Tests/netcoreapp/testResults.xml for details! [/mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug/src/System.Net.Http/tests/FunctionalTests/System.Net.Http.Functional.Tests.csproj]

detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/centos7.1_debug/3384/consoleFull#-9775515633fe3402-0c0f-45a7-a707-47164965bab5

**Comment by stephentoub** [comment]
Already fixed
