### ISSUE TITLE
'System.Net.WebSockets.Client.Tests' failed in CI

### ISSUE THREAD

**Issue by v-haren** [dotnet/corefx#21821]
/mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_debug/Tools/tests.targets(354,5): error : One or more tests failed while running tests from 'System.Net.WebSockets.Client.Tests' please check /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_debug/bin/Unix.AnyCPU.Debug/System.Net.WebSockets.Client.Tests/netstandard/testResults.xml for details! [/mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_debug/src/System.Net.WebSockets.Client/tests/System.Net.WebSockets.Client.Tests.csproj]

detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_opensuse42.1_debug/96/

**Comment by stephentoub** [comment]
Already fixed
