### ISSUE TITLE
System.Text.RegularExpressions.Tests.Match_SpecialUnicodeCharacters* is failing on UAP

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#21835]
This test is failing because of combination of two windows bugs:
- setting a culture to invariant does not always happen
- turkish I should not be lowercased to i on en-US

This test is being renamed to System.Text.RegularExpressions.Tests.Match_SpecialUnicodeCharacters_Invariant
in https://github.com/dotnet/corefx/pull/21782

@tarekgh, could you provide details?

**Comment by krwq** [comment]
@tarekgh has found a workaround which we will use on our side and is already in the PR
https://github.com/dotnet/corefx/pull/21782

**Comment by tarekgh** [comment]
@krwq you may close this issue now.
