### ISSUE TITLE
Question: how to store RSA piravate keys?

### ISSUE THREAD

**Issue by zhengbli** [dotnet/corefx#21867]
With 2.0 now the private part of `RSAParameters` cannot be serialized any more, so what is the recommended way to store the private key? Thanks!

**Comment by danmosemsft** [comment]
@bartonjs

**Comment by bartonjs** [comment]
@zhengbli The private key fields of RSAParameters have always been \[NonSerialized\] (in versions of .NET which had serializers).  What were you doing before that isn't working anymore?

**Comment by zhengbli** [comment]
https://github.com/dotnet/corefx/commits/master/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/RSAParameters.cs

The non serialization attributes were added recently. I didn't use this with non-core dotnet before. I am curious what is the recommended way to save a generated key / parameters, as i didn't find one that doesn't require serialization of the private key

**Comment by bartonjs** [comment]
> The non serialization attributes were added recently

True, but 1.0/1.1 didn't have any serializers, so we didn't have any serialization attributes.

> I am curious what is the recommended way to save a generated key / parameters

We don't really have a recommended way.  It's just a per-application decision and per-application code.  I'm hoping we'll have better support for importing and exporting keys with standard file formats in the next release; so then you can decide to save it to (e.g.) an encrypted PKCS#8 file.

**Comment by bartonjs** [comment]
Any work that we know of from this is tracked under #20414, so closing this issue.
