### ISSUE TITLE
Zero byte Socket.ReceiveAsync does not complete when peer disconnects on Unix

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#21865]
When there is a pending Socket.ReceiveAsync for count==0 and the peer disconnects, the Completed event does not fire.

This is caused by a workaround for macOS. When the peer disconnects, GetBytesAvailable returns 0.
https://github.com/dotnet/corefx/blob/29fb3994aa493d68bb080063287f200a3a50167d/src/System.Net.Sockets/src/System/Net/Sockets/SocketPal.Unix.cs#L619-L640.

CC @stephentoub 

repro:
```C#
using System;
using System.Diagnostics;
using System.Net;
using System.Net.Sockets;
using System.Threading;
using System.Threading.Tasks;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            new Program().Run();
        }

        Thread _serverThread;
        Thread _clientThread;

        // used to synchronize between the threads
        TaskCompletionSource<IPEndPoint> _serverListening = new TaskCompletionSource<IPEndPoint>();
        TaskCompletionSource<object> _clientCompleted = new TaskCompletionSource<object>();

        public void Run()
        {
            _serverThread = new Thread(ServerThread);
            _clientThread = new Thread(ClientThread);

            var threads = new [] { _serverThread, _clientThread };
            foreach (var thread in threads)
            {
                thread.Start();
            }

            foreach (var thread in threads)
            {
                thread.Join();
            }
        }

        public void ServerThread(object state) => ServerThreadAsync().Wait();
        public void ClientThread(object state) => ClientThreadAsync().Wait();

        public async Task ServerThreadAsync()
        {
            var listener = new TcpListener(IPAddress.Loopback, 0);
            listener.Start();

            // clients can connect
            _serverListening.SetResult(listener.LocalEndpoint as IPEndPoint);
            
            var socket = await listener.AcceptSocketAsync();
            System.Console.WriteLine($"{DateTime.Now}: Server: accept client");

            socket.Dispose();
            System.Console.WriteLine($"{DateTime.Now}: Server: dispose client");
        }

        public async Task ClientThreadAsync()
        {
            // wait for the server to start
            var endpoint = await _serverListening.Task;

            Socket socket = new Socket(endpoint.AddressFamily, SocketType.Stream, ProtocolType.Tcp);
            socket.Connect(endpoint);

            var sea = new SocketAsyncEventArgs();
            sea.Completed += ReceiveCompleted;
            sea.SetBuffer(new byte[0], 0, 0);
            if (socket.ReceiveAsync(sea))
            {
                System.Console.WriteLine($"{DateTime.Now}: Client: receive pending");
            }
            else
            {
                System.Console.WriteLine($"{DateTime.Now}: Client: receive completed");
                _clientCompleted.SetResult(null);
            }
            // wait for the client to complete
            await _clientCompleted.Task;
        }

        public void ReceiveCompleted(object sender, SocketAsyncEventArgs ae)
        {
            System.Console.WriteLine($"{DateTime.Now}: Client: receive completed");
            _clientCompleted.SetResult(null);
        }
    }
}
```

outputs
```
7/4/17 5:59:56 PM: Client: receive pending
7/4/17 5:59:56 PM: Server: accept client
7/4/17 5:59:56 PM: Server: dispose client
```

**Comment by karelz** [comment]
@tmds which OS did you reproduce it on? Linux?
I wonder if it is the same behavior on Windows. And on .NET Framework.

**Comment by tmds** [comment]
I reproduced this on Linux. I don't expect this to reproduce on Windows.

**Comment by tmds** [comment]
@karelz confirming this doesn't reproduce on Windows using .NET framework. Also on Linux it doesn't reproduce using .NET Core 1.x.

**Comment by tmds** [comment]
@karelz I think this should be fixed for 2.0. Not detecting peer close leads to all sorts of resource leaks.

**Comment by stephentoub** [comment]
> I think this should be fixed for 2.0

I agree it should ideally be fixed.  Do you have a suggestion for how? Previously ReceiveAsync with a 0 count would complete immediately on macOS, which defeats the purpose.  The referenced change made it work correctly on macOS, but introduced this issue for both Linux and macOS.  Any fix should ensure we don't regress the macOS behavior (there's already a test for it) and should address the peer-close issue for both.

**Comment by tmds** [comment]
@stephentoub I don't have a mac, so I can't reproduce or try to fix it, but I do have a suggestion...

For this code:
```C#
await socket.ReceiveAsync(Array.Empty<byte>(), 0, 0, SocketFlags.None);
int count = socket.Available;
```
The behavior is ReceiveAsync doesn't complete until there is some data, and then Available returns 0?

According to the `kqueue` man page, the `data` field for the read event contains the number of available bytes.
If this value is correct, it can be used to distinguish between EOF and data. This can be combined with the existing GetAvailable check when !EOF.
If the data value is also returning `0`, perhaps it works better when setting `fflags` to `NOTE_LOWAT`, and `data` to `1` for the `EVFILT_READ` filter.

**Comment by stephentoub** [comment]
> The behavior is ReceiveAsync doesn't complete until there is some data, and then Available returns 0?

The behavior of ReceiveAsync with a 0 count is supposed to be that the returned task doesn't complete until data is available.  The previous bug was that that behavior was happening on Windows and Linux, but on macOS ReceiveAsync with a 0 count was completing its task immediately, regardless of whether any data was available; most likely the macOS recv implementation special-cased 0 as a nop and returned success immediately for a request for 0 bytes.

**Comment by tmds** [comment]
> ReceiveAsync with a 0 count was completing its task immediately, regardless of whether any data was available

Ah, I don't think kevent knows about count. So this is due to the synchronous attempt that is done before going async? So, perhaps the synchronous attempt can be skipped for count==0?

**Comment by stephentoub** [comment]
> So, perhaps the synchronous attempt can be skipped for count==0?

I'm not sure that would be sufficient.  After registering with kevent/epoll, we still need to check again with a "synchronous" check as to the status, as an event may have arrived before the registration.

Is there anything we can query to determine whether the peer has disconnected?  We could then just change the condition checked from "available != 0" to "available != 0 || peerDisconnected".

**Comment by tmds** [comment]
> After registering with kevent/epoll, we still need to check again with a "synchronous" check as to the status, as an event may have arrived before the registration.

If there is data pending at registration, it will also cause an event. It isn't necessary to check this.
Skipping the synchronous attempt should work.

> Is there anything we can query to determine whether the peer has disconnected? We could then just change the condition checked from "available != 0" to "available != 0 || peerDisconnected".

recvmsg with PEEK

**Comment by stephentoub** [comment]
> If there is data pending at registration, it will also cause an event.

Not for edge triggered, right?

> recvmsg with PEEK

And that won't special-case 0 on macOS just like recv appears to special-case 0?

**Comment by tmds** [comment]
> Not for edge triggered, right?

Right.
I prefer EPOLLONESHOT over EPOLLET.

> And that won't special-case 0 on macOS just like recv appears to special-case 0?

I mean peek with a 1 byte buffer.

**Comment by stephentoub** [comment]
> Right. I prefer EPOLLONESHOT over EPOLLET.

We've talked about switching to (or at least experimenting with) EPOLLONESHOT for other reasons, but that's a significant change and likely too big to take into 2.0.

> I mean peek with a 1 byte buffer

If that works, I agree using recvmsg with MSG_PEEK instead of Available is a good solution.  Do you want to give it a shot?  Our CI system will help validate it on macOS.

**Comment by tmds** [comment]
I'll give it a shot.

**Comment by stephentoub** [comment]
Cool. Thanks!

**Comment by karelz** [comment]
Reopening to track port to release/2.0.0 branch
