### ISSUE TITLE
Should ReadOnlySpan<char>.ToString() return the contents of the span?

### ISSUE THREAD

**Issue by bbowyersmyth** [dotnet/corefx#21899]
Trying out the new Spans for the first time and I was expecting `ReadOnlySpan<char>.ToString()` to be an easy way to do a conversion. It just returns the default type name.

I understand that `ReadOnlySpan<T>` is an array-like structure but with https://github.com/dotnet/corefx/issues/21395 coming `ReadOnlySpan<char>` is going to look string-like.

Is their any precedent to `Something<char>.ToString()` being special cased?

**Comment by omariom** [comment]
`Span<T>` is a too low level type to override `ToString`. There could be an extension method for `ReadOnlySpan<T> ` but more practical approach would be to add another ctor to`string` which will be taking `ReadOnlySpan<T> `

**Comment by benaadams** [comment]
Handled by something around [System.Text.Primitives](https://github.com/dotnet/corefxlab/tree/master/src/System.Text.Primitives/System/Text/Encoding)?

Though not sure if outputing a `string` is in there? /cc @KrzysztofCwalina

**Comment by bbowyersmyth** [comment]
@omariom I think it's a good idea to add the `string` ctor either way but to me the `ToString()` looks better. Closer to a `StringBuilder` than an array.

```
string a = myCharSpan.Trim().ToString();

string b = new String(myCharSpan.Trim());
```
It is not critical but a nice to have.

**Comment by benaadams** [comment]
Don't think you can specifically override; or provide an extension method (as is defined instance method) for
```csharp
Span<char>.ToString()
```
Would have to override `Span<T>.ToString()` then `typeof(T)` to get that effect

**Comment by jkotas** [comment]
`Span<char>` is very much like array. `char[].ToString()` does not return the content as a string either.
