### ISSUE TITLE
No testResults.xml generated for System.Data.*.Tests in UapAot when running in arm

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#21890]
- System.Data.SqlClient.ManualTesting.Tests
- System.Data.SqlClient.Stress.Tests
- System.Data.SqlClient.Tests

These tests are crashing in arm.

@joperezr could you take a look at which tests are causing it to crash the arm machines? 

cc: @saurabh500 @danmosemsft @joshfree

**Comment by joperezr** [comment]
I believe we know what the issue is already and AFAIK @saurabh500 was working on it. https://github.com/dotnet/corefx/issues/21598

Unless this is a different issue.

**Comment by saurabh500** [comment]
This must be some other issue. ManualTests and StressTests are always skipped in the CI and the IntegratedAuth tests were never re-enabled.

**Comment by joperezr** [comment]
this is ILC tests, so if you just skipped them by adding an `[ActiveIssue]` that won't do the trick. The reason is that ILC tests do not support assembly loading at execution time, only at load time, so if your test assembly depends on on sni.dll, which I believe it still is, then this will crash the execution. I haven't actually tried to repro this, but I would bet that this is the problem.

**Comment by saurabh500** [comment]
For ManualTests, the skip happens when an environment variable is checked during runtime. When not found, the test is skipped. This is done via a customer Xunit attribute in our tests.

**Comment by joperezr** [comment]
Just verified in an ARM machine that this is in fact the problem. Basically, in order for these tests to run, you can't have a reference to sni.dll, even though at runtime you won't call it. You will need to make sure that in your uapaot asset, all of the code calling into sni.dll is #ifdef'd out.

**Comment by joperezr** [comment]
![image](https://user-images.githubusercontent.com/13854455/27890041-441af386-61a5-11e7-96ef-bfe9120e569a.png)

**Comment by saurabh500** [comment]
@joperezr While I am working to get this taken care of, what change caused this issue? I believe that the tests were executing earlier with the exception of Integrated Auth tests.

**Comment by saurabh500** [comment]
cc @corivera

**Comment by joperezr** [comment]
mm the only thing that changed was that we brought up ARM runs, and this only fails in ARM, which basically means that this has never really worked on ARM since this has always been a problem.
