### ISSUE TITLE
Bring XSL-T to CoreFX

### ISSUE THREAD

**Issue by bradwilson** [dotnet/corefx#2189]
The [xUnit.net](https://github.com/xunit) unit test framework uses XSL-T to transform its native XML reporting format into other XML (NUnit, xUnit.net v1) formats as well as to generate HTML reports. This strategy works well for desktop runners, but is currently not supported in our [DNX runner](https://github.com/xunit/dnx.xunit) because of the lack of XSL-T support on the platform. This is a [feature request for our DNX runner](https://github.com/xunit/dnx.xunit/issues/42) which we cannot satisfy without some form of XSL-T support.

In particular, the code we use today exercises `XslCompiledTransform`: https://github.com/xunit/xunit/tree/05826dcfd3cee97d93ff63201db0296933dd3511/src/xunit.runner.reporters.desktop

**Comment by stephentoub** [comment]
@weshaggard, @krwq?

**Comment by matsprea** [comment]
Any rational behind not including System.Xml.Xsl in CoreFX? Is there any hope we can get it running on CoreCLR soon?

**Comment by joshfree** [comment]
@piotrpMSFT can you comment

**Comment by jasongaylord** [comment]
+1 I need to use XslCompileTransform in an embedded assembly by passing in controlled documents.

**Comment by NerdsRule** [comment]
Would also appreciate this feature in Core or in a package. We create HTML using XSLT + Styling + XML.

**Comment by kpboyle1** [comment]
Some applications, including my MVC layer, plan to continue using System.Xml.Xsl for the foreseeable future, A review of the w3.org site shows they've just released new standards for version 3.0, suggesting they might agree. As of March 17, 2016, it's the only library on my MVC layer that is being reported as incompatible with NetCore 1.0.

**Comment by danmosemsft** [comment]
Duping against https://github.com/dotnet/corefx/issues/5593

This is now in the dev/api branch, so the work is largely done but it's not yet shipped.
