### ISSUE TITLE
API Request: Debug.AssertEval

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#21898]
## Background

I've been running more and more into methods lately that perform some kind of action, and return a `bool` indicating whether they succeed. From the BCL, `IEnumerator.MoveNext` or `HashSet.Add` would be examples. I don't deal with specifically those methods often, but as I've been working on a Xamarin.Android app, I've run into methods like `ISharedPreferencesEditor.Commit()`, `Activity.RequestWindowFeature()`, etc. a fair number of times which also return a boolean to indicate success/failure.

For example, consider this method from my codebase:

```cs
        private void WriteAccessToken(string key, string token)
        {
            var prefs = ApplicationContext.GetSharedPreferences(Strings.SPFile_AccessTokens);
            var editor = prefs.Edit();
            editor.PutString(key, token);
            editor.Commit();
        }
```

Since I expect `editor.Commit()` to succeed, I want to wrap it in a `Debug.Assert` like so: `Debug.Assert(editor.Commit(), "Failed to commit")`. However, that causes `Commit()` to be omitted in release builds, so I end up doing this:

```cs
if (!editor.Commit())
{
    Debug.Fail("Failed to commit");
}
```

Which is much less ergonomic to write out. Again, I use this particular method (`ISharedPreferencesEditor.Commit()`) a lot, and I have to add those extra braces and `Debug.Fail` each time I do so.

## Proposal

There should be a static method on `Debug` that forces evaluation of the condition, in both Debug/Release builds. A possible name could be `Debug.AssertEval`. Here's how it'd be implemented:

```cs
// Note: No [Conditional("DEBUG")]
public static void AssertEval(bool condition) => Assert(condition);
public static void AssertEval(bool condition, string message) => Assert(condition, message);

// Usage:
Debug.AssertEval(editor.Commit());
```

Thoughts? Does anyone else run into C-style methods that perform an action and return a status code where this would be useful (maybe @tannergooding)?

**Comment by stephentoub** [comment]
>  I use this particular method (ISharedPreferencesEditor.Commit()) a lot, and I have to add those extra braces and Debug.Fail each time I do so.

Why haven't you just added your own helper for it in your project?
```C#
internal static void AssertEval(bool condition, string message)
{
    if (!condition) Debug.Fail(condition, message);
}
```

**Comment by stephentoub** [comment]
Also, how is this different from Trace.Assert?

**Comment by tannergooding** [comment]
@stephentoub, `Trace.Assert` is filtered on `TRACE` being defined (which may be default for VS, but not necessarily for all builds or all build systems).

As for what I do (as I frequently run into similar issues with various interop code), I have an `ExceptionUtilities` and an `AssertUtilities` class that wraps logging/throwing/etc

**Comment by stephentoub** [comment]
> which may be default for VS, but not necessarily for all builds or all build systems

If you're depending on it in your code, you can also ensure it's set.

**Comment by tannergooding** [comment]
I think the point of the proposal here is that there should be a set of Assert functions available where the call is not conditioned but that still only throws under the respective condition (DEBUG, TRACE, etc).

That being said, I think writing a wrapper class for this is trivial enough (and probably rare enough) that I'm not sure its worth being part of CoreFX.

I think that most libraries will end up with their own wrappers for this type of code anyways and will end up adding in other functionality (such as logging) to the call.

**Comment by stephentoub** [comment]
> I think the point of the proposal here is that there should be a set of Assert functions available where the call is not conditioned but that still only throws under the respective condition (DEBUG, TRACE, etc). That being said, I think writing a wrapper class for this is trivial enough (and probably rare enough) that I'm not sure its worth being part of CoreFX.

I understand the point of the proposal.  And I was pushing back on it :)

**Comment by jamesqo** [comment]
@stephentoub Thanks for the advice. I guess I could write my own wrapper for this, but it feels really weird to write `DebugExtensions.AssertEval` or even `DebugEx.AssertEval`-- too many case changes. I can accept that this will probably not get into corefx though, it's such a trivial method that exists purely for ergonomics and doesn't add any functionality. I really hope static extension methods come to C# sometime soon, so I can just add this to `Debug` myself.

**Comment by stephentoub** [comment]
> but it feels really weird to write DebugExtensions.AssertEval or even DebugEx.AssertEval-- too many case changes

```C#
using static DebugExtensions;
...
AssertEval(...);
```
?

**Comment by jamesqo** [comment]
@stephentoub Good point, thank you for helping. I do prefer having `Debug.` before the method call though because I'm a lot more used to it. The solution I ended up with was introducing a custom `Debug` class in my project, and inserting

```cs
using Debug = Repository.Internal.Debug;
```

at the top of the file.
