### ISSUE TITLE
ILC is failing to compile multiple test projects

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#21891]
- System.CodeDom.Tests
- System.Collections.Concurrent.Tests
- System.Collections.Immutable.Tests
- System.Collections.NonGeneric.Test

@joshfree who would be the right person to take a look at this? 

cc: @danmosemsft

**Comment by joshfree** [comment]
@safern sync with @tijoytom offline - who investigates next depends on the error, but when in doubt please start with @tijoytom for all things ILC

**Comment by safern** [comment]
> @safern sync with @tijoytom offline - who investigates next depends on the error, but when in doubt please start with @tijoytom for all things ILC

Thanks, I will sync with @tijoytom offline

**Comment by tijoytom** [comment]
@safern I have opened nutc issue for this one .. all seems to fail on the same nutc issue

**Comment by safern** [comment]
> @safern I have opened nutc issue for this one .. all seems to fail on the same nutc issue

thanks :)

**Comment by tijoytom** [comment]
@safern I am closing this one since you mentioned this is fixed.

**Comment by safern** [comment]
> @safern I am closing this one since you mentioned this is fixed.

Yes I didn't see this on today's run. I will keep an eye of this on future runs.
