### ISSUE TITLE
Consider adding API to return common Funcs and Actions without reallocating

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#219]
See pull request #181: In that case, caching was proposed for System.Linq.Parallel. This means that other libraries can't share the same cache (which can grow by the number of generic instantiations). Furthermore, since the actual call sites affected in PLINQ were already allocating considerably, it is doubtful that PLINQ would benefit from the optimization.

We should study if we can design public API in the BCL in the same vein as the new `Array.Empty<T>().`

_Before_ we do this, we should:
1. Gather data about how many places we have across the stack that would benefit from these shared allocations and find use cases in more compelling places than PLINQ.
2. Design the API. We can use this issue to discuss and evolve it in to a mini-spec. Here's an idea just to get that ball rolling on that.

``` C#
namespace System {
    public static class CommonAction {
        public static Action Empty { get; }
    }
    public static class CommonFunc {
        public static Func<T, bool> AlwaysTrue<T>();
        public static Func<T, T> Identity<T>();
        public static Func<TArgument, TType> IsInstanceOf<TArgument, TType>();
        public static Func<TArgument, TType> Cast<TArgument, TType>();
    }
}
```

**Comment by nguerrera** [comment]
@alexandrnikitin Sorry for not replying to this for a while. That's pretty cool and compelling. I think we should do this, but I'm not sure about the API shape. I don't like the Common prefix I used in my strawman. I kind of wish it could be Action.Empty, but there's no way to add a static factory to a delegate. Do you have any thoughts on how a public API should look? How about others on the team? /cc @terrajobst @davkean

**Comment by svick** [comment]
> there's no way to add a static factory to a delegate

Actually, I think there is. Only you have to write the delegate in IL: https://gist.github.com/svick/2d6ce35f9608fe5e7e7f.

Though I'm not sure whether it's worth the increased complexity of implementation. Especially considering that it could also be confusing to users.

**Comment by nguerrera** [comment]
@svick Yes, good point. :) I wouldn't consider this design unless C# and VB were willing to adopt for the same reason - it's complicated for us to define and it's unexpected for callers to discover.

**Comment by joperezr** [comment]
@nguerrera I unassigned you as you were not working on this. Is this still something you think we should add?

**Comment by nguerrera** [comment]
I don't see why not. We'd need a formal API proposal. I just sketched the idea.

**Comment by karelz** [comment]
Next steps: We need survey of common delegates to decide which are worth adding and which are not ([1] in top post called out by @nguerrera).
It aligns well with our direction for BCL.

**Comment by jnm2** [comment]
Why not properties instead of methods? Properties give the sense the the value is cached and is the same every time you access it. Methods give the sense that they are doing more significant work on each call, such as allocating the delegates.

**Comment by nguerrera** [comment]
Properties can't be generic.

We'd have to factor into separate generic types and that would hurt discoverability IMHO.

**Comment by jnm2** [comment]
Thanks, not sure how I missed that. I agree.

**Comment by stephentoub** [comment]
While I see some potential benefit here, we don't have any data to show that this would really be impactful (it's not just about how many call sites can be found, but how frequently the allocations result on hot paths), and this issue hasn't made any progress in years. I don't see that changing, so I'm going to close this. If someone has the time and inclination to do the appropriate analysis across enough code to demonstrate its worth, we could certainly reconsider (even then we'd want to consider a compiler angle, like method/delegate folding). Thanks.
