### ISSUE TITLE
User-provided SSL callback exceptions are rethrown incorrectly

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#21904]
The current .NET Core code is behaving differently than .NET Framework when exceptions are thrown in a user-provided callback for the HttpClient ServerCertificateCustomValidationCallback.

In .NET Framework, any exception bubbling out of a user-provided callback is trapped, saved, and placed as an inner exception to the main HttpRequestException that is thrown.  This is the current behavior of HttpClient on .NET Framework.  Even for HttpWebRequest on .NET Framework, the exception is placed as an inner exception to the top-level WebException.

Currently, .NET Core is throwing a raw exception from the callback and propagating it as a top-level exception for HttpClient APIs. This bad pattern started with WinHttpHandler when I introduced (unknowingly) the bug.  The behavior was then copied to the *Nix version.

This current test is therefore invalid:

```c#
[Fact]
public async Task UseCallback_CallbackThrowsException_ExceptionPropagates()
{
    // ...
    var handler = new HttpClientHandler();
    using (var client = new HttpClient(handler))
    {
        var e = new DivideByZeroException();
        handler.ServerCertificateCustomValidationCallback = delegate { throw e; };
        Assert.Same(e, await Assert.ThrowsAsync<DivideByZeroException>(() => client.GetAsync(Configuration.Http.SecureRemoteEchoServer)));
    }
}
```

In my PR #21905 implementing ServerCertificateCustomValidationCallback for UWP, I have revised this test and disabled it on all platforms except UAP.

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by stephentoub** [comment]
@davidsh, is the desired change to wrap the exception in both WinHttpHandler and CurlHandler (even though technically that's a breaking change from 1.x/2.0)?

**Comment by davidsh** [comment]
>@davidsh, is the desired change to wrap the exception in both WinHttpHandler and CurlHandler (even though technically that's a breaking change from 1.x/2.0)?

Yes.  That raw exception that leaks from the user-provided callback needs to be surfaced as an inner exception to an HttpRequestException, like all other async exceptions on the I/O path.

**Comment by davidsh** [comment]
Now that #24111 is merged, this issue can be closed since it is fixed on all platforms.
