### ISSUE TITLE
UnknownHeaders_Success_Large() test will hang on Windows sometimes

### ISSUE THREAD

**Issue by caesar1995** [dotnet/corefx#21902]
Please see the discussions here: https://github.com/dotnet/corefx/issues/19754#issuecomment-301313041

The `UnknownHeaders_Success_Large()` test are still disabled [(See here)](https://github.com/dotnet/corefx/blob/cd20a23b5225a51665d202e99a2a04fbf240f749/src/System.Net.HttpListener/tests/SimpleHttpTests.cs#L128)

**Comment by stephentoub** [comment]
> UnknownHeaders_Success_Large() performance on Windows

This isn't about performance, is it?  The test hangs.

**Comment by caesar1995** [comment]
I tried to remove the [ActiveIssue] label and run the test. The test will pass on my local machine without hanging every time.

I will change the title to: ... test hangs on Windows sometimes.

**Comment by stephentoub** [comment]
> The test will pass on my local machine without hanging every time.

Meaning you can't get it to ever hang?

**Comment by caesar1995** [comment]
@stephentoub No, I have run it for 50 times on both netcore and uap mode, and didn't observe its hanging.

I tried to set numHeaders = 2000, still no hang.

Do I need to close this issue? Since I'm not able to repro.

**Comment by stephentoub** [comment]
Hmm.  It's not hanging for me now, either.  But I've also upgraded to a newer Windows build since then.  Maybe it was a temporary http.sys issue.  In any event, if it doesn't repro for you and it passes CI, please feel free to re-enable it and close the issue. Thanks.
