### ISSUE TITLE
BinaryFormatter incompatibility regarding base class values between Desktop and Core

### ISSUE THREAD

**Issue by sandyarmstrong** [dotnet/corefx#21918]
Given the following serializable classes:

```csharp
[Serializable]
class BaseClass
{
    public const string DefaultValue = "hello";
    public string MissingValue { get; } = DefaultValue;
}

[Serializable]
class FinalClass : BaseClass { }
```

When serializing `FinalClass` on Desktop .NET (4.6.1) and deserializing on .NET Core 2.0
Preview 2, `FinalClass.MissingValue` will always be unset.

## Test Case

https://github.com/sandyarmstrong/BinaryFormatterSubclassTest

## Runtimes tested

* .NET Core 2.0.0-preview2-006497
* .NET 4.6.1 (MS.NET and Mono 5.2.0.179)

**Comment by sandyarmstrong** [comment]
My initial example used a custom `SerializationBinder`, but I think that part is not necessary. I'm updating to put the shared code in a .NET Standard 2.0 library.

**Comment by sandyarmstrong** [comment]
I'm having some trouble getting everything to build correctly on Mac if I move the shared code to a .NET Standard 2.0 library. I'll update my test case later, when I figure that out.

Regardless, I don't believe the custom binder has any bearing on this issue.

**Comment by danmosemsft** [comment]
@ViktorHofer @morganbr

**Comment by morganbr** [comment]
@sandyarmstrong , I wonder if your desktop and .NET Core C# compilers are generating different field names for the backing field for MissingValue. You could check that with reflection (make sure to include private fields) or with ildasm.

**Comment by sandyarmstrong** [comment]
@morganbr It seems to be `.field private initonly string '<MissingValue>k__BackingField'` in each case, according to `ildasm`. However, I do notice that if I change my test to use public fields instead of public properties, the bug goes away, at least on Windows (can try more combinations in the morning).

**Comment by sandyarmstrong** [comment]
@morganbr changing `BaseClass` to use an explicit backing field does not fix anything:

```csharp
	[Serializable]
	class BaseClass
	{
		public const string DefaultValue = "hello";

		string missingValue = DefaultValue;
		public string MissingValue => missingValue;
	}
```

Same broken behavior.

**Comment by morganbr** [comment]
@ViktorHofer , can you please take a look? If the fields match, I'm not aware of any other expected issues.

**Comment by ViktorHofer** [comment]
@sandyarmstrong @morganbr Using an explicit backing field works for me:

```csharp
[Serializable]
class BaseClass
{
    public const string DefaultValue = "hello";

    string missingValue = DefaultValue;
    public string MissingValue => missingValue;
}


[Serializable]
class FinalClass : BaseClass { }

[Fact]
public void Test()
{
    string blob = SerializeObjectToBlob(new FinalClass(), FormatterAssemblyStyle.Full);
    var obj = DeserializeBlobToObject(blob, FormatterAssemblyStyle.Full) as FinalClass;
    Console.WriteLine(obj.MissingValue); // hello
}
```

Additionally, looking into the blob shows that the value is saved correctly (Ignore the qualified assembly name as I tested your code in our serialization test assembly):
```
???????????
???pSystem.Runtime.Serialization.Formatters.Tests, Version=4.0.2.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb???MSystem.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests+FinalClass???BaseClass+missingValue??????hello
```

**Comment by ViktorHofer** [comment]
Using an auto property:

```csharp
[Serializable]
class BaseClass
{
    public const string DefaultValue = "hello";
    public string MissingValue { get; } = missingValue;
}


[Serializable]
class FinalClass : BaseClass { }

[Fact]
public void Test()
{
    string blob = SerializeObjectToBlob(new FinalClass(), FormatterAssemblyStyle.Full);
    var obj = DeserializeBlobToObject(blob, FormatterAssemblyStyle.Full) as FinalClass;
    Console.WriteLine(obj.MissingValue); // hello
}
```

And produces the following blob which is the same again on core and netfx:

```
???????????
???pSystem.Runtime.Serialization.Formatters.Tests, Version=4.0.2.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb???MSystem.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests+FinalClass???'BaseClass+<MissingValue>k__BackingField??????hello
```

I can't see any issue here. @sandyarmstrong maybe something else related to the unset field?

**Comment by sandyarmstrong** [comment]
@ViktorHofer I don't see where your test is taking serialized output from .NET Desktop and deserializing in .NET Core, which is where the bug surfaces.

**Comment by ViktorHofer** [comment]
> Additionally, looking into the blob (which is the same for netfx and core)...

The serialization payload generated on netfx (.NET Desktop) and core (.NET Core) is exactly the same.

**Comment by sandyarmstrong** [comment]
Thanks, I missed that. Let me try a daily build and see if I can get results like you.

**Comment by ViktorHofer** [comment]
There was an issue when it comes to serialization of parent type fields which we fixed here: https://github.com/dotnet/corefx/pull/20938 (I can't say if it was already included in preview-2)

**Comment by ViktorHofer** [comment]
It might also help if you post your base64 blob into here so I can take a look. You might use this method for it https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Serialization.Formatters/tests/BinaryFormatterHelper.cs#L274

**Comment by sandyarmstrong** [comment]
@ViktorHofer I just tested with 2.0.0-preview3-006689 on Windows and it seems fixed now. I'll verify on Mac as well.

**Comment by ViktorHofer** [comment]
Thanks for testing!! 👍 I will close this now.

**Comment by sandyarmstrong** [comment]
Looks good on Mac, too, thanks!
