### ISSUE TITLE
Port Uri.CheckForUnicode rewrite to desktop

### ISSUE THREAD

**Issue by davkean** [dotnet/corefx#21933]
Visual Studio uses Uri to verify and check paths due to some limitations in the Path APIs.

Uri.CheckForUnicode, (which appears to be have been rewritten in CoreFx to not allocate), is a cause of a [large amount of data](http://referencesource.microsoft.com/#System/net/System/UriExt.cs,258) in certain scenarios. Can we please port this rewrite to desktop?

Here's an example of a trace taken just opening (http://github.com/dotnet/project-system) in Visual Studio, this one method is the cause of 3.7% of all data allocated:
![image](https://user-images.githubusercontent.com/1103906/27902230-4ee93376-6278-11e7-8602-6169e3fcef55.png)

**Comment by stephentoub** [comment]
> Visual Studio uses Uri to verify and check paths due to some limitations in the Path APIs.

What are the cited limitations?
cc: JeremyKuhne

**Comment by davidsh** [comment]
We will open up a bug in TFS for this about porting this.  But changes to System.Uri for .NET Framework are rarely done.  If this doesn't cause any behavior change and is only about performance, then we might be able to do it in a future .NET Framework update.

cc: @CIPop

**Comment by davkean** [comment]
I filed https://github.com/dotnet/corefx/issues/22245 for the first reason we're using Uri.

**Comment by davidsh** [comment]
There is now an internal TFS bug 470763 for possible .NET Framework Uri changes for this.

Closing this issue now since it doesn't track any changes in CoreFx.
