### ISSUE TITLE
Http test server flaky?

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#21949]
Lots of tests failed last night:

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170706.02/workItem/System.Net.Http.Functional.Tests 

We have various http tests that fail on and off but this is something different. You might want to take a look to avoid lots of noise.

@davidsh @CIPop @Priya91

**Comment by stephentoub** [comment]
> Lots of tests failed last night

That link comes up empty for me.

Are you referring to the ManagedHandler tests?  Those are newly checked in and unrelated to the test server's reliability.  Separate issues were opened for the various failures.

**Comment by danmosemsft** [comment]
Yes, most are that. OK fine.
