### ISSUE TITLE
Application Manifest File does not build correctly

### ISSUE THREAD

**Issue by vsccarl** [dotnet/corefx#21954]
In a .NET Core project, add an Application Manifest File to the project and build the solution. An error of `CS1926	Error opening Win32 manifest file c:\app1.manifest -- Could not find file 'c:\app1.manifest'.` 

In .NET Framework projects, adding this file works and builds without any modification.

**Comment by Petermarcu** [comment]
@livarcocc @davkean which repo should this get moved to? Its not a corefx issue.

**Comment by tarekgh** [comment]
Issue moved to [dotnet/sdk #1401](https://github.com/dotnet/sdk/issues/1401) via [**ZenHub**](https://www.zenhub.com/)
