### ISSUE TITLE
Contribution guide: add guidance for when to add commits to a PR vs. amending/squashing

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/corefx#2195]
It's often not clear how to react to code review feedback (e.g. see the discussion [here](https://github.com/dotnet/corefx/pull/2182#issuecomment-116794742)), should you add a new commit or just amend the previous one?

I think it'd be good to have an "official" guidance on this in the [contributing](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/contributing.md) doc to prevent confusion.

@stephentoub's response looks like a good basis to me:
> In this case I'd suggesting adding additional commits and then squashing later. Personally, I prefer to just ammend the existing commit when the changes are small / trivial and I don't expect anyone to need to re-review, e.g. fixing up typos or making simple one-line fixes. For larger things, I prefer to have the additional commits so that it's clear to a reviewer what's changed.

Thoughts?

**Comment by Maxwe11** [comment]
dup #1063

**Comment by akoeplinger** [comment]
Thanks, glad it's not just me :smile: 

Closing this, but it'd be great if @terrajobst or @richlander could take a look at #1063 and discuss how we should move forward.
