### ISSUE TITLE
Intermittent Failure in ServicePointManager tests

### ISSUE THREAD

**Issue by nchikanov** [dotnet/corefx#21963]
Intermittent failure, see details below.

System.Net.Tests.TlsSystemDefault.ServicePointManager_SecurityProtocolDefault_Ok() [failed](https://mc.dot.net/#/user/nchikanov/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/ccff43e892dac662b67327aad3d7e20625f3f2bc/workItem/System.Net.ServicePoint.Tests/analysis/xunit/System.Net.Tests.TlsSystemDefault~2FServicePointManager_SecurityProtocolDefault_Ok): 
Assert.Equal() Failure\r\nExpected: SystemDefault\r\nActual:   Tls11

**Comment by davidsh** [comment]
@nchikanov Thx for the bug report.  The Jenkins/Helix system doesn't seem to be giving me back information (the webpage is hanging).  Can you paste into this issue some more information?  We need to know especially the type of OS run this was (Windows or Linux) and specifically what kind of Windows OS run (UAP, NETFX, netcore, etc.).

The ServicePointManager class is a no-op for netcore. So, I would be surprised if anything fails.  And so, we need more information to diagnose this.  Thx.

cc: @stephentoub

**Comment by davidsh** [comment]
Closing this issue for now since the logs are no longer available.
