### ISSUE TITLE
System.IO.FileAttributes needs Unix permissions for cross-platform compatibility

### ISSUE THREAD

**Issue by rmunn** [dotnet/corefx#21967]
This is a duplicate of #312 and #15201. #312 was incorrectly closed on Feb. 11, 2017, and should be reopened. If #312 somehow can't be reopened, I suggest further discussion of this problem here.

**Comment by rmunn** [comment]
See also https://github.com/dotnet/templating/issues/1028 for relevant discussion.

**Comment by Petermarcu** [comment]
Closed in favor of the original.
