### ISSUE TITLE
System.Xml.Linq.Events.Tests crash on UapAot

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#21986]
This tests are crashing with following error:

```
Unhandled exception thrown: read access violation.

pContext->pRbx was nullptr.
```

I've seen this failed in several places, one of them is: https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/Core/XmlEncodedRawTextWriter.cs#L138

Note that this only happens in ret mode, if I build the test  project in chk then this doesn't happen anymore.

cc: @tijoytom

**Comment by safern** [comment]
Also note that this is only happening in x86

cc: @joshfree

**Comment by joshfree** [comment]
@AtsushiKan please take a quick look

**Comment by AtsushiKan** [comment]
This is for compiler or runtime folks. The GC is doing a stack walk and seeing something in the regDisplay that it didn't expect to see:


 	mrt100_app.dll!EECodeManager::UnwindStackFrame(GCInfoHeader * pInfoHeader, REGDISPLAY * pContext) Line 797	C++
 	mrt100_app.dll!Module::UnwindStackFrame(MethodInfo * pMethodInfo, REGDISPLAY * pRegisterSet, void * * ppPreviousTransitionFrame) Line 457	C++
 	mrt100_app.dll!StackFrameIterator::NextInternal() Line 1108	C++
 	mrt100_app.dll!StackFrameIterator::Next() Line 1081	C++
>	mrt100_app.dll!Thread::GcScanRootsWorker(void * pfnEnumCallback, void * pvCallbackData, StackFrameIterator & frameIterator) Line 517	C++
 	mrt100_app.dll!Thread::GcScanRoots(void * pfnEnumCallback, void * pvCallbackData) Line 405	C++
 	mrt100_app.dll!GCToEEInterface::GcScanRoots(void(__stdcall*)(Object * *, ScanContext *, unsigned int) fn, int condemned, int max_gen, ScanContext * sc) Line 88	C++
 	mrt100_app.dll!WKS::gc_heap::background_mark_phase() Line 25509	C++
 	mrt100_app.dll!WKS::gc_heap::gc1() Line 15242	C++
 	mrt100_app.dll!WKS::gc_heap::bgc_thread_function() Line 26852	C++
 	mrt100_app.dll!WKS::gc_heap::bgc_thread_stub(void * arg) Line 24807	C++
 	kernel32.dll!74c68744()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]	
 	ntdll.dll!__RtlUserThreadStart(long(__stdcall*)(void *) StartAddress, void * Argument) Line 997	C
 	ntdll.dll!_RtlUserThreadStart(long(__stdcall*)(void *) StartAddress, void * Argument) Line 914	C

**Comment by safern** [comment]
Note that this tests are forced to be build as chk mode to avoid hitting this issue. So to get a local repro either passing /p:ILCBuildType=ret or delete this line: https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml.Linq/tests/events/System.Xml.Linq.Events.Tests.csproj#L6

**Comment by AntonLapounov** [comment]
Fixed in ProjectN build 25510.

**Comment by tijoytom** [comment]
@AntonLapounov Is this fix still in 25510 , i thought you rolled it back ?

**Comment by AntonLapounov** [comment]
@tijoytom I rolled back the change that broke unwinding on x86.
