### ISSUE TITLE
Invalid RD.XML in System.Linq.Expression

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/corefx#21993]
The embedded RD.XML in System.Linq.Expression doesn't conform to the schema and causes compilation warnings on UWP:

```
  System.Linq.Expressions.Resources.System.Linq.Expressions.rd.xml(158-158): warning : ILTransform : warning ILT0027: The 'Dynamic' attribute is invalid - The value 'Required' is invalid according to its datatype 'http://schemas.microsoft.com/netfx/2013/01/metadata:applicabilitySpec' - The Enumeration constraint failed. [D:\dd\PN1\src\QA\ToF\tests\ToolChain\Analysis\SimpleFlow.csproj]

```

What we need to investigate is why there are no failing tests (a badly specified RD.XML does nothing) - is this directive needed? Do we need more tests?

Also, the RD.XML needs to be fixed or all users will see this warning in VS.

**Comment by MichalStrehovsky** [comment]
Cc @AtsushiKan

**Comment by AtsushiKan** [comment]
>

>a badly specified RD.XML does nothing

Something's not adding up about that (aside from sounding way too draconian a policy). This was part of a change (364428426ee64cbea654cbe9890a176c298fffe5) that caused ILC Helix runs to start passing, and there was a subsequent change (cea36058acd4c1b5d24dcec7e856da089de90a45) to this same (that would be a nop if this statement were true) that also unblocked new tests.

I don't think we got tests running by causing scads of types to leave their metadata at home.

**Comment by MichalStrehovsky** [comment]
I should rephrase that: a badly specified RD.XML *directive* does nothing. Line 158 does nothing.

**Comment by AtsushiKan** [comment]
That makes more sense. IEnumerator is pretty common - it's not too hard to believe that something else was causing that one method to be retained, thus hiding the bug.

**Comment by joshfree** [comment]
@VSadov @jaredpar

**Comment by VSadov** [comment]
@MichalStrehovsky @AtsushiKan  - can you take a look at https://github.com/dotnet/corefx/pull/21994 ?

Would that fix the issue?
