### ISSUE TITLE
About FileShare.Read behavior?

### ISSUE THREAD

**Issue by iboxdb** [dotnet/corefx#22011]
Create two Write FileStream with **FileShare.Read**, but have no exception.

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup> 
  </ItemGroup>
</Project>
```

```c#
Console.WriteLine (typeof(FileStream).GetTypeInfo().Assembly.FullName);
var f1 = new FileStream ("/tmp/a", FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.Read, 1);
var f2 = new FileStream ("/tmp/a", FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.Read, 1);
f1.Write( new byte[]{ (byte)'a', (byte)'a', (byte)'a'},0,3);
f2.Write( new byte[]{ (byte)'b'},0,1);
Console.WriteLine("Hello World! NET1.0 ");
```

```
user@ubuntu:~/net/n1$ dotnet --version
1.0.4

user@ubuntu:~/net/n1$ uname -a
Linux ubuntu 3.13.0-32-generic 57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

user@ubuntu:~/net/n1$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty

user@ubuntu:~/net/n1$ dotnet run
System.IO.FileSystem, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Hello World! NET1.0 
```

What expected.
```
Unhandled Exception:
System.IO.IOException: Sharing violation on path /tmp/a
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) [0x00000] in <filename unknown>:0 
```

[EDIT] by karelz - fixed formatting of code & log blocks

**Comment by stephentoub** [comment]
While not ideal, this is by design due to limitations of what support the OS provides, where essentially we only have the ability to specify a shared lock or an exclusive lock, rather than the fine-grainedness of control one has on Windows and which is exposed from FileShare.  You can see this detailed in the comment here:
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/IO/FileStream.Unix.cs#L70-L73

**Comment by svick** [comment]
@stephentoub Should this be documented in the API reference (either for [`FileShare`](https://docs.microsoft.com/en-us/dotnet/api/system.io.fileshare?view=netcore-2.0), the relevant [`FileStream` constructors](https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream.-ctor?view=netcore-2.0) or both), not just in the source code?

**Comment by stephentoub** [comment]
Probably. There are a bunch of places where platform differences result in subtle behavioral differences, and they should ideally all be catalogued.

**Comment by jnm2** [comment]
Is this a candidate for terrajobst/platform-compat? @karelz

**Comment by iboxdb** [comment]
Has replaced with Lock(),  thanks!

**Comment by karelz** [comment]
@JeremyKuhne @pjanotti should we add it to ApiCompat? (I missed @jnm2 reply when on vacation in July)

**Comment by pjanotti** [comment]
@karelz yes, that is a good one. I will do that, and take a pass a the template too (we should also include it in the docs anyway, I will check with @mairaw the best way to ensure that these issues are covered both on ApiCompat but also on the docs).
