### ISSUE TITLE
EqualityComparer binary serialization test failures on uapaot

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#22016]
An EqualityComparer test which uses byte as the generic argument is currently failing on uapaot.

```
      <test name="System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs(obj: GenericEqualityComparer`1 { }, blobs: [\&quot;AAEAAAD/////AQAAAAAAAAAEAQAAAC9TeXN0ZW0uQ29sbGVjdG\&quot;..., \&quot;AAEAAAD/////AQAAAAAAAAAEAQAAAC9TeXN0ZW0uQ29sbGVjdG\&quot;...])" type="System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests" method="ValidateAgainstBlobs" time="0.0008977" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[The stored blob for type System.Collections.Generic.GenericEqualityComparer`1[[System.Byte, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]] is outdated and needs to be updated.\r\nStored blob: AAEAAAD/////AQAAAAAAAAAEAQAAAC9TeXN0ZW0uQ29sbGVjdGlvbnMuR2VuZXJpYy5CeXRlRXF1YWxpdHlDb21wYXJlcgAAAAAL\r\nGenerated runtime blob: AAEAAAD/////AQAAAAAAAAAEAQAAAJABU3lzdGVtLkNvbGxlY3Rpb25zLkdlbmVyaWMuR2VuZXJpY0VxdWFsaXR5Q29tcGFyZXJgMVtbU3lzdGVtLkJ5dGUsIG1zY29ybGliLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OV1dAAAAAAs=\r\nExpected: True\r\nActual:   False]]></message>
          <stack-trace><![CDATA[   at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.SanityCheckBlob(Object obj, String[] blobs)
   at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs(Object obj, String[] blobs)
   at xunit.console.netcore!<BaseAddress>+0x10d66cf
   at xunit.console.netcore!<BaseAddress>+0x1064945
   at xunit.console.netcore!<BaseAddress>+0x10646d1]]></stack-trace>
        </failure>
      </test>
```

coreclr serializes `EqualityComparer<byte>.Default`, corert to `System.Collections.Generic.GenericEqualityComparer1[[System.Byte, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]`: https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/Collections/Generic/EqualityComparer.cs#L19

@morganbr @tarekgh Is it intentional that byte doesn't have its own optimized equality comparer in corert? Others like int or string are returning the same type as coreclr.

cc @danmosemsft

**Comment by tarekgh** [comment]
CC @jkotas as he may knows better here.

**Comment by morganbr** [comment]
@davidwrighton would know for sure, but I believe it's intentional that EqualityComarer<byte>.Default doesn't have a special comparer. If you want to fix the test, you could create ByteEqualityComparer with reflection though.

**Comment by ViktorHofer** [comment]
ping @davidwrighton

**Comment by davidwrighton** [comment]
It is intentional that EqualityComparer.Default doesn't have a special comparer, the behavior of the standard one has equivalent performance to a special one. Now, that said, I'm curious why the test is failing. Is it specifically attempting to verify the type of the comparer?

**Comment by ViktorHofer** [comment]
The test was failing because it compared the serialization payload between coreclr and corert, which was obviously different. Morgan already implemented a workaround for the test. I just wanted to make sure that the behavior is intentional.
