### ISSUE TITLE
GraphicsPathIterator.CopyData throws EntrypointNotFoundException - does not on netfx

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#22026]
```cs
using System.Drawing;
using System.Drawing.Drawing2D;

namespace Test
{
    public class Program
    {
        public static void Main()
        {
            // Throw ArgumentException.
            //CopyData_StartEndIndexesOutOfRange_ReturnsExpeced(new PointF[3], new byte[3], -1, 2);
            //CopyData_StartEndIndexesOutOfRange_ReturnsExpeced(new PointF[3], new byte[3], 0, 3);

            // Return 0
            CopyData_StartEndIndexesOutOfRange_ReturnsExpeced(new PointF[3], new byte[3], int.MinValue, 2);
            CopyData_StartEndIndexesOutOfRange_ReturnsExpeced(new PointF[3], new byte[3], 0, int.MaxValue);
            CopyData_StartEndIndexesOutOfRange_ReturnsExpeced(new PointF[3], new byte[3], 2, 0);
        }
   
        public static void CopyData_StartEndIndexesOutOfRange_ReturnsExpeced(PointF[] points, byte[] types, int startIndex, int endIndex)
        {
            PointF[] resultPoints = new PointF[points.Length];
            byte[] resultTypes = new byte[points.Length];

            using (GraphicsPath gp = new GraphicsPath(points, types))
            using (GraphicsPathIterator gpi = new GraphicsPathIterator(gp))
            {
                gpi.CopyData(ref resultPoints, ref resultTypes, startIndex, endIndex);
            }
        }

    }
}
```

This runs fine with netfx. With netcoreapp, an EntrypointNotFoundException is thrown.

**Comment by hughbe** [comment]
See #20711 for more context. @KostaVlev @mellinoe cc

**Comment by hughbe** [comment]
There are two possible fixes. The first would be to change the entry point of [ZeroMemory](https://github.com/dotnet/corefx/blob/1f055788ff130aacae11fae8c15584beaa7dd3b6/src/System.Drawing.Common/src/System/Drawing/Gdiplus.cs#L3531-L3532) to
```cs
[DllImport(ExternDll.Kernel32, EntryPoint = "RtlZeroMemory")]
static internal extern void ZeroMemory(IntPtr destination, UIntPtr length);
```

Or, we could avoid the PInvoke and use a managed implementation that `System.Data.Obdc` [uses](https://github.com/dotnet/corefx/blob/e34d49b97f5f638d91300d797509983b1041b97d/src/System.Data.Odbc/src/Common/System/Data/Common/SafeNativeMethods.cs#L19-L23)

```cs
internal static void ZeroMemory(IntPtr ptr, int length)
{
   var zeroes = new byte[length];
   Marshal.Copy(zeroes, 0, ptr, length);
}
```

The .NET reference source is the same though. It's not clear why this bug only affects .NET Core

**Comment by mellinoe** [comment]
> The .NET reference source is the same though. It's not clear why this bug only affects .NET Core

Yeah, that is pretty odd. The only thing that would make sense is the .NET Framework version isn't hitting that call. I don't see how it could work as-written. We can just replace it with some simpler managed code, although that snippet from System.Data.Odbc is kind of silly in that it allocates a whole temporary array to just clear some memory.

**Comment by danmosemsft** [comment]
RtlZeroMemory is probably too low level for us to use. Even though WACK may never be relevant to System.Drawing, I bet it is not even in OneCore. I would use 

```c#
            internal static unsafe void ZeroMemory(byte* ptr, ulong len)
            {
                for (ulong i = 0; i < len; i++) *ptr++ = 0;
            }
```

**Comment by safern** [comment]
@hughbe interested in fixing this one?

**Comment by MarcoRossignoli** [comment]
@safern i think this could be closed, i checked source and seems [this](https://github.com/dotnet/corefx/pull/24656) pull fix the issue.

**Comment by safern** [comment]
A right. Thanks @MarcoRossignoli
