### ISSUE TITLE
Can't install nuget package of library developed by .net 4.7 full on .net core 2 app

### ISSUE THREAD

**Issue by ysmoradi** [dotnet/corefx#22032]
I've a .NET core 2 app and when I add nuget packages of a library which has .NET 4.7 binaries only, I receive following error:

Package XYZ 1.2.3.4 is not compatible with netcoreapp2.0

But when I open %userprofile%\.nuget\packages folder and in "lib" folder of that package, I rename "net47" to "net45". After this small change, everything works fine and apps work properly.
App is using same .net 4.7 dlls, so a folder name is a only change.

What should I do? is there any incompatibility between .net 4.7 & .net core 2 ?

Thanks in advance

**Comment by pjanotti** [comment]
My understanding is that this is not possible at this moment, but /cc @livarcocc @terrajobst that can correct me if I'm wrong.

**Comment by ysmoradi** [comment]
@pjanotti Thanks. This is a link of sample traditional ASP.NET Web API/Owin app on top of .NET Core 2 & ASP.NET Core >> https://github.com/ysmoradi/WebApiAspNetCore which works fine with no modification, due all nuget packages are coming from .net 45 folders. But in main app I'm developing, there are nuget packages with .net 47 folder. My .net core app does not restore those .net 47 dlls. But when I rename the 47 folder in lib folder of nuget package to 45, it restores and works properly. It seems to be a bug rather than policy or something like that, because when I read .net core 2 release blog post, they said you can use .net full dlls in .net core 2 apps, they didn't say anything about .net 4.5 dll works but .net 47 won't work.

**Comment by karelz** [comment]
@ysmoradi did you try latest Preview2?
I have seen demos of Desktop NuGet packages being referenced from .NET Standard library. I assume same can happen from .NET Core library/app.

**Comment by ysmoradi** [comment]
@karelz Yeah, I'm using latest previews. I think this is a bug in sdk and (dotnet restore | dotnet add package). Because you can fix all problems with a simple folder rename in nuget package folder.

This is a sample of app I'm talking about >> https://github.com/bit-foundation/bit-framework/tree/master/Samples/WebApiSamples/6WebApiDotNetCoreHost This is a "traditional asp.net web api / owin" sample app works on top of "asp.net core / .net core" If you run dotnet restore and then dotnet run, it works fine. But that works fine, because in nuget packages I've created for that, I'm putting the "same" dlls in both lib/net47 and lib/netcoreapp2 folders! If I delete bit/netcoreapp2 folder from my nuget packages, then you won't be able to run the app which was working fine before.

**Comment by weshaggard** [comment]
Sounds like this was an SDK bug so closing the issue here. If there is still more follow-up please open it in the sdk repo.
