### ISSUE TITLE
WinHttpHandler stops possible chain of handlers

### ISSUE THREAD

**Issue by ausmurp** [dotnet/corefx#22038]
Very simple (at first glance) fix, please make WinHttpHandler inherit DelegatingHandler instead of HttpMessageHandler, so inner handlers can be passed and chained appropriately.

**Comment by davidsh** [comment]
Both HttpClientHandler and WinHttpHandler are base handlers.  They inherit from HttpMessageHandler.

If you need additional handlers on top of those, you need to create your own new handler that is derived from DegatingHandler.  Your new handler logic will be the "outer" handler and then you pass in the HttpClientHandler or WinHttpHandler as the "inner" handler.  The actual HTTP protocol stack itself represented by HttpClientHandler or WinHttpHandler should always be the "inner" handler as it is the own closest to the transport (wire).

**Comment by davidsh** [comment]
Closing this now since the question has been answered. The current behavior is by-design.
