### ISSUE TITLE
System.Linq.Parallel.Tests crashing in UapAot when building in ret mode on ARM

### ISSUE THREAD

**Issue by AntonLapounov** [dotnet/corefx#22040]
Forked from #21804.  At present we are forcing chk build in src/System.Linq.Parallel/tests/System.Linq.Parallel.Tests.csproj.

**Comment by joshfree** [comment]
> At present we are forcing chk build in 

@VSadov @stephentoub who should make this fix?

**Comment by MattGal** [comment]
Sorry if it's obvious, but what's the request for me?

**Comment by AntonLapounov** [comment]
Not actionable without the crash dump.

**Comment by karelz** [comment]
@mellinoe was working on crash dump collection, but likely not ARM. You might want to check with him what is possible ...

**Comment by AntonLapounov** [comment]
I disabled the workaround and ran System.Linq.Parallel.Tests in a loop on an ARM device. The test passes every run, just takes a long time to finish (1,000–1,300 seconds on a quad-core machine).

**Comment by joshfree** [comment]
> The test passes every run, just takes a long time to finish (1,000–1,300 seconds on a quad-core machine)

@AntonLapounov instead of closing, should this go to @fadimounir to investigate the long running time problem?  Is this USG related?

**Comment by AntonLapounov** [comment]
@joshfree I don't know whether it has anything to do with USG.  There are 186,403 tests in this assembly, and the execution time seems reasonable to me.

**Comment by Clockwork-Muse** [comment]
If you're getting 180k+ tests, you're probably also running the outerloop tests (the majority of which are combinatorial operations).  Which includes things like explicit timeouts, waits for additional threads, etc.
