### ISSUE TITLE
System.Xml.Tests.XmlWriterTestModule.TCFullEndElement failing in uap test runs

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#22042]
TCFullEndElement has been crashing the execution of tests in all archs for most runs lately. The problem seems to be related to WindowsRuntimeResourceManager. Crash is happening because of an unhandeled System.ArgumentException, here is the callstack:
```
Value does not fall within the expected range.
   at Windows.ApplicationModel.Resources.Core.ResourceContext.get_Languages()
   at System.Resources.WindowsRuntimeResourceManager.GlobalResourceContextChanged(Object sender, IMapChangedEventArgs`1 e)

```

cc: @krwq @tarekgh

**Comment by joperezr** [comment]
#22043 PR that disabled the test

**Comment by krwq** [comment]
Me and @joperezr looked at the test and test seem to be ok although not necessarily pretty - @tarekgh I believe you are the right person to take a look
