### ISSUE TITLE
System.Net.HttpListener HttpListenerRequestTests class takes too long to finish in UAP mode

### ISSUE THREAD

**Issue by caesar-chen** [dotnet/corefx#22050]
After enable all test cases in HttpListenerRequestTests, it takes about 2 minutes to run all tests in this particular class in UAP mode.

We need to mark some test cases in this file as [OuterLoop] to improve test performance.

@davidsh @CIPop

**Comment by davidsh** [comment]
In general, all networking tests that do send/receive should be marked as Outerloop.

But, also, this needs to be investigated deeper to understand why UAP mode is much slower than .NET Core mode.
