### ISSUE TITLE
LoadUnmanagedDllFromPath / LoadUnmanagedDll is not working on linux if .so file is present in any other path other than application output directory

### ISSUE THREAD

**Issue by PrashanthIBM** [dotnet/corefx#22076]
Hi , 

i am not sure whether the issue exists in coreclr or corefx.

So notifying the issue here https://github.com/dotnet/coreclr/issues/12707

Thanks,
Prashanth.

**Comment by joperezr** [comment]
@kouvel is this expected?

**Comment by kouvel** [comment]
The coreclr issue should be sufficient
