### ISSUE TITLE
PathGradientBrush.Blend.Positions returns unexpected when running with netcoreapp but works correct with netfx.

### ISSUE THREAD

**Issue by KostaVlev** [dotnet/corefx#22099]
I simplified the test I wrote:

          private readonly PointF[] _defaultFloatPoints = new PointF[2] { new PointF(1, 2), new PointF(20, 30) };
   
          public static IEnumerable<object[]> Blend_FactorsPositions_TestData()
        {
            yield return new object[] { new float[1] { 1 }, new float[1] { 0 } };
            yield return new object[] { new float[1] { 1 }, new float[3] { 0, 3, 1 } };
        }

        [ConditionalTheory(nameof(PlatformDetection) + "." + nameof(PlatformDetection.IsNotWindowsNanoServer))]
        [MemberData(nameof(Blend_FactorsPositions_TestData))]
        public void Blend_ReturnsExpected(float[] factors, float[] positions)
        {
            using (PathGradientBrush brush = new PathGradientBrush(_defaultFloatPoints, WrapMode.TileFlipXY))
            {
                brush.Blend = new Blend { Factors = factors, Positions = positions };
                Assert.Equal(new float[1] { 0 }, brush.Blend.Positions);
            }
        }

Running the test with `netcoreapp` results are:

**Expected:** float[1] { 0 }
**Actual:** float[1]{random value}. Running the test  multiple times I got values from -3 to +7.

Running the test with `netfx` results are:

**Expected:** float[1] { 0 }
**Actual:** as expected float[1] { 0 }

More related data at #20711

**Comment by KostaVlev** [comment]
Actually after running the test numerous times `netfx` failed with same result as `netcoreapp`.

Running the test with netcoreapp results are:
Expected: float[1] { 0 }
Actual: float[1]{random value}

Running the test with netfx results are:
Expected: float[1] { 0 }
Actual: float[1]{random value}

So this is not an issue in this context.

**Comment by mellinoe** [comment]
@KostaVlev That's a relief...? At least it's not a .NET Core-specific problem 😄

**Comment by KostaVlev** [comment]
I stuck on this for two days LOL
