### ISSUE TITLE
System.Net.HttpListener tests hanging in UAPAOT

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#22110]
Some of the HttpListener tests are hanging in AOT mode only. The failures are intermittent and the following may not be a complete list:

- [ ] 7 tests in HttpRequestStreamTests.cs 
- [x] 2 test in HttpResponseStreamTests.cs

**Comment by caesar1995** [comment]
There are 5 tests in HttpResponseStreamTests.cs disabled with this issue.

I will look into it.

**Comment by CIPop** [comment]
@caesar1995 /cc @DavidGoll @jkotas @stephentoub 
There's some chance this is caused by the same reason here: https://github.com/dotnet/corefx/issues/22066#issuecomment-315242374 - If Stream is not able to figure out that we have Begin/End defined, it will fall-back to synchronous I/O which in turn may create random deadlocks within tests using async/await.

On top of that, the tests are already known to be bad: #20103 and AOT is almost impossible to diagnose because we can't trace (#20470).

**Comment by caesar1995** [comment]
@CIPop I have finished implementing Stream.*Async overrides in HttpResponseStreamTests.cs

The good new is, the tests will pass on my machine without hanging.

I will continue my work towards HttpRequestStreamTests.cs.

**Comment by caesar1995** [comment]
Status update: 

I'm still investigating the hang in HttpRequestStreamTests. I added `Console.WriteLine("some_test begins");` at the beginning of each hanging test case, 
and `Console.WriteLine("some_test ends");` at the end of it. The behavior is, tests are still hanging, without printing anything on Console.

Some tests will run fine separately and print everything as expected, but if I enable them together, they will hang. This is not expected because we have disabled [parallel execution](https://github.com/dotnet/corefx/blob/9d8c3dcdcb78ad799de519be08149092a467e8d2/src/System.Net.HttpListener/tests/XUnitAssemblyAttributes.cs#L9) for HttpListener tests. (The hang will only happen in UAPAOT.)

I created a dump for the xunit process in Task Manager, and trying to understand what's going on.

**Comment by caesar1995** [comment]
I was able to narrow down to 3 problematic test cases: `Read_InvalidOffset_ThrowsArgumentOutOfRangeException`, `Read_InvalidOffsetSize_ThrowsArgumentOutOfRangeException` and `Read_TooMuchAsynchronous_Success`.
1. `Read_TooMuchAsynchronous_Success` will always hang
2. `Read_InvalidOffset_ThrowsArgumentOutOfRangeException` and `Read_InvalidOffsetSize_ThrowsArgumentOutOfRangeException` will hang if BOTH of them are enabled. If only enable one of them, the test will run fine.

They share one thing in common: they are all calling `HttpListenerRequest.InputStream.ReadAsync()`. If commented out `ReadAsync` operation in `Read_InvalidOffset_ThrowsArgumentOutOfRangeException` and `Read_InvalidOffsetSize_ThrowsArgumentOutOfRangeException`, those two test cases will not hang anymore.

```c#
        [InlineData(-1, true)]
        [InlineData(3, true)]
        [InlineData(-1, false)]
        [InlineData(3, false)]
        public async Task Read_InvalidOffset_ThrowsArgumentOutOfRangeException(int offset, bool chunked)
        {
            Console.WriteLine("6 test begin");
            HttpListenerRequest request = await _helper.GetRequest(chunked);
            using (Stream inputStream = request.InputStream)
            {
                AssertExtensions.Throws<ArgumentOutOfRangeException>("offset", () => inputStream.Read(new byte[2], offset, 0));
                //await AssertExtensions.ThrowsAsync<ArgumentOutOfRangeException>("offset", () => inputStream.ReadAsync(new byte[2], offset, 0));
            }
            Console.WriteLine("6 test end!!!");
            Console.WriteLine("-----------------");
        }
```

**Comment by DavidGoll** [comment]
We have determined that this is *not* a product issue, so I have re-tagged as a test bug and set the milestone to Future.

@caesar1995 to provide the details

**Comment by caesar1995** [comment]
I can confirm that it's not a product issue. I am able to solve the hang by fixing tests, and I am working on the PR right now. The PR will contain more details.
