### ISSUE TITLE
Invalid Rd.xml in System.ComponentModel.TypeConverter

### ISSUE THREAD

**Issue by davidwrighton** [dotnet/corefx#22113]
The embedded RD.XML in System.ComponentModel.TypeConverter doesn't conform to the schema and causes compilation warnings on UWP:

```
System.ComponentModel.TypeConverter.Resources.System.ComponentModel.TypeConverter.rd.xml(26-26): warning : ILTransform : warning ILT0027: The 'Dynamic' attribute is invalid - The value 'Required Public' is invalid according to its datatype 'http://schemas.microsoft.com/netfx/2013/01/metadata:memberApplicabilitySpec' - The Enumeration constraint failed. [E:\ProjectN_2\src\ndp\pntoolchain\ilc\ilc_selfhosted.proj]

```

What we need to investigate is why there are no failing tests (a badly specified RD.XML does nothing) - is this directive needed? Do we need more tests?

Also, the RD.XML needs to be fixed or all users will see this warning in VS.

**Comment by davidwrighton** [comment]
@AtsushiKan It looks like you made the change that introduced this issue.

**Comment by AtsushiKan** [comment]
Fixed here: https://github.com/dotnet/corefx/pull/21994

**Comment by MichalStrehovsky** [comment]
This is for System.ComponentModel.
