### ISSUE TITLE
API checker issue with CheckTokenMembershipEx 

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#22128]
[CheckTokenMembershipEx](https://msdn.microsoft.com/en-us/library/windows/desktop/hh448479(v=vs.85).aspx)  is documented to have an entrypoint in kernel32.dll but the checker places it in advapi32.dll.

As a workaround I have temporarily added CheckTokenMembershipEx to the ignore file.
```
     Getting error BCL0015: kernel32.dll!CheckTokenMembershipEx is not supported on one\more targeted platforms.Consider using advapi32.dll!CheckTokenMembershipEx instead which doesn't exist.

     Using advapi32.dll!CheckTokenMembershipEx will give out a runtime error: System.EntryPointNotFoundException : Unable to find an entry point named 'CheckTokenMembershipEx' in DLL 'advapi32.dll'.
```

**Comment by CIPop** [comment]
/cc @danmosemsft @AlexGhiondea 

I have started an discussion with the Windows SDK team.

**Comment by danmosemsft** [comment]
As noted in the PR please use a baseline file instead.
We just need them to fix modernapis.xml

**Comment by CIPop** [comment]
> As noted in the PR please use a baseline file instead.

Changed in the PR and updated the description on this issue.

**Comment by CIPop** [comment]
@danmosemsft this got fixed on 7/13 in Windows. What needs to be updated on CoreFX to remove the workaround?

**Comment by danmosemsft** [comment]
@pjanotti can help there

**Comment by pjanotti** [comment]
Not closed yet, language in the commit marked this one as closed but we still have to update things on corefx side. I will do that.

**Comment by CIPop** [comment]
Thanks @pjanotti !
