### ISSUE TITLE
Xslt recursion incorrect result

### ISSUE THREAD

**Issue by ymor** [dotnet/corefx#22139]
Hi,
We have come across an issue when using the Xslt 1.0 implementation in .Net Core 2.0.0-preview2-006497.

I have committed a sample project at the following location: https://github.com/ymor/NetCore2-XSLTIssue

If you run the tests you will see the test "TestNetCore_InlineCalculation_ReturnsHelloWorld" fails as the output is 'Hllo World' instead of 'Hello World'.  The .net framework 4.6.2 version of this test passes correctly.

If you compare the outputs from the two tests, you will see that on iteration 2 of the .net core version the result is incorrect.

I have noticed that if you do the "calculation" outside of the with-param, the .Net Core test will pass. (ExternalCalculation.xslt).

I hope the example is sufficient to help diagnose the issue.
Many thanks.

**Comment by sepidehMS** [comment]
This seems to be JIT-related. It would fail on .NET Framework 4.6.2 for x64 as well. @briansull @erozenfeld

**Comment by erozenfeld** [comment]
It's almost certainly an instance of https://github.com/dotnet/coreclr/issues/12761. It's fixed by https://github.com/dotnet/coreclr/pull/12735. A workaround is
`set COMPlus_TailCallLoopOpt=0`

**Comment by sepidehMS** [comment]
Thanks @erozenfeld. Closing as it is already fixed. 
@ymor please feel free to re-open if it's not gone after a new CoreClr update is merged.
