### ISSUE TITLE
Named pipe stream endpoint cannot be created under application directory

### ISSUE THREAD

**Issue by aviviadi** [dotnet/corefx#22141]
In order to preserve application's permissions also on the created pipe, I have to create a directory under the temp path. However it will be much easier not to create one, and just use the path of the current running dotnet app.

Currently I'm w/a this by overriding : https://github.com/dotnet/corefx/blob/master/src/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs#L28

Can dotnet provide a way to set _path ?

**Comment by ayende** [comment]
What we would like to do here is to either be able to specify permissions when we create the pipe, so it is created with atomic permissions, or we can create it on our own path, so we can define the permissions directly on that.

**Comment by pjanotti** [comment]
On 2.1 it is possible to specify an absolute path see [here](https://github.com/dotnet/corefx/blob/dd8449ded9dda04f50d8394341e2b9a59bee2b0e/src/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs#L49). Just keep in mind that there are limits to the length of the name (restricted for Unix Domain Sockets by the system).
