### ISSUE TITLE
SendAsync_Cancel_CancellationTokenPropagates throw wrong exception on UAP

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#22159]
HttpClientHandler test  SendAsync_Cancel_CancellationTokenPropagates() is throwing OperationCanceledException on UAP.  But it throws TaskCanceledException on .NET Core.

**Comment by stephentoub** [comment]
The test is likely just too strict; often in cases where an OperationCanceledException is expected we throw the derived TaskCanceledException.

**Comment by davidsh** [comment]
>The test is likely just too strict; often in cases where an OperationCanceledException is expected we throw the derived TaskCanceledException.

Who or what is "we throw the derived TaskCanceledException"?  Is this code we can change in our UAP HttpClient implementation. Even we decide to won't fix this and adjust the test, it would be nice to understand why there is a difference.

**Comment by stephentoub** [comment]
> Who or what is "we throw the derived TaskCanceledException"?

When you await a task from a TaskCompletionSource that's been {Try}SetCanceled, it'll throw a TaskCanceledException; TaskCanceledException derives from OperationCanceledException but carries with it the actual Task in question, to help with debugging for example.  Generally though callers simply expect an OperationCanceledException.
