### ISSUE TITLE
[CI Failure] System.Transactions.Local.Tests failed on NETFX

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#22168]
Ref: PR #22155.

NETFX CI failure:
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/1109/console

12:55:09 D:\j\workspace\windows-TGrou---2a8f9c29\Tools\tests.targets(346,5): warning : System.Transactions.Local.Tests Total: 286, Errors: 0, Failed: 1, Skipped: 0, Time: 6.235s [D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Transactions.Local\tests\System.Transactions.Local.Tests.csproj]
12:55:09 D:\j\workspace\windows-TGrou---2a8f9c29\Tools\tests.targets(346,5): warning MSB3073: The command "D:\j\workspace\windows-TGrou---2a8f9c29\bin/AnyOS.AnyCPU.Release/System.Transactions.Local.Tests/netstandard//RunTests.cmd D:\j\workspace\windows-TGrou---2a8f9c29\bin/testhost/netfx-Windows_NT-Release-x86/" exited with code 1. [D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Transactions.Local\tests\System.Transactions.Local.Tests.csproj]
12:55:09 D:\j\workspace\windows-TGrou---2a8f9c29\Tools\tests.targets(354,5): error : One or more tests failed while running tests from 'System.Transactions.Local.Tests' please check D:\j\workspace\windows-TGrou---2a8f9c29\bin/AnyOS.AnyCPU.Release/System.Transactions.Local.Tests/netstandard/testResults.xml for details! [D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Transactions.Local\tests\System.Transactions.Local.Tests.csproj]
12:55:09 Command execution failed with exit code 1.

**Comment by qizhanMS** [comment]
Can we skip System.Transactions.Local.Tests on NETFX?

**Comment by dmetzgar** [comment]
No updates on this issue. Closing
