### ISSUE TITLE
Can we delete ValueTask.CreateAsyncMethodBuilder?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#22171]
https://github.com/dotnet/corefx/blob/5a6d8ca975b512eeeea7404c740afcf865128405/src/System.Threading.Tasks.Extensions/src/System/Threading/Tasks/ValueTask.cs#L156-L161

This CreateAsyncMethodBuilder function was used as part of the initial C# compiler design for supporting arbitrary async return types, but the final design switched away from needing it.  Unfortunately we neglected to then remove the method prior to shipping the library as stable.

The method is hidden from IntelliSense, and there's no good reason for someone to call it.

Can we remove it?

**Comment by karelz** [comment]
Approved.

Checked API usage (nuget and API port): no usage at all.
If anyone ever hits it, they can just use the `default`.
