### ISSUE TITLE
Azure Active Directory on .NET core on a Mac

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#22172]
_From @glenster75 on July 11, 2017 0:8_

I'm following the sample code from: https://azure.microsoft.com/en-us/resources/samples/active-directory-dotnet-webapp-openidconnect-aspnetcore/ On Windows 10 with Visual Studio 2017 it works fine, but when developing on my Mac, I cannot figure out why "await HttpContext.Authentication.ChallengeAsync" does not work on Mac. It crashes dotnet. Please see screenshot on my question on Twitter: https://twitter.com/glenster75/status/883213695995699200 and on StackOverflow: https://stackoverflow.com/questions/44974254/azure-active-directory-on-net-core-on-a-mac
![aspnet core error](https://user-images.githubusercontent.com/4316520/28045494-56c150de-6592-11e7-8bb2-e70c52b1dd75.gif)
 

_Copied from original issue: dotnet/coreclr#12726_

**Comment by davidsh** [comment]
The `HttpContext` class is part of ASP.NET and not in .NET Core. This issue should be moved there.

**Comment by davidsh** [comment]
@glenster75

We're closing this here.  If this is still a problem, please open an issue in ASP.NET repo.  Thx.
https://github.com/aspnet/home
