### ISSUE TITLE
PostAsync_RedirectWith307_LargePayload test fails on UAP

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#22191]
>ERROR:    System.Net.Http.Functional.Tests.HttpClientHandlerTest.PostAsync_RedirectWith307_LargePayload [FAIL]
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Runtime.InteropServices.COMException : The text associated with this error code could not be found.
        The HTTP redirect request must be confirmed by the user

**Comment by davidsh** [comment]
Looks like this bug has been reported before:
https://stackoverflow.com/questions/31150900/httprequestexception-when-trying-putasync

This probably a WinRT HttpClient bug.

**Comment by davidsh** [comment]
Opened internal bug 12757218

**Comment by davidsh** [comment]
PR #22702 changes how redirection works and we know can workaround this limitation in the WinRT layer.

**Comment by eiriktsarpalis** [comment]
FWIW we're still skipping [this test](https://github.com/dotnet/corefx/blob/19ea63fee517327e1f6fbfa730300ddef5ef8a3b/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs#L2260) on account of the issue.
