### ISSUE TITLE
Cannot install Microsoft.NETCore.UniversalWindowsPlatform as NuGet dependency for .NET Core Library

### ISSUE THREAD

**Issue by mqudsi** [dotnet/corefx#22215]
I suppose this is more of a "known issue" or even possibly a "by design," but according to the breakdown chart of the different .NET frameworks and how everything fits together with .NET Core 1.0 and now 2.0, shouldn't `Microsoft.NETCore.UniversalWindowsPlatform` be available as a package that can be installed as a dependency for any .NET Core project, though only available on Windows?

As it currently stands, creating a .NET Framework library in Visual Studio 2017 (15.3 preview), setting <TargetFrameworks> to netstandard1.3, and then attempting to install `Microsoft.NETCore.UniversalWindowsPlatform` leads to package install errors.

**Comment by mellinoe** [comment]
> according to the breakdown chart of the different .NET frameworks and how everything fits together with .NET Core 1.0 and now 2.0

Could you link the chart you are referring to?

I don't think this will work. the UniversalWindowsPlatform package is part of the UWP product, so it shouldn't be able to be used from a .NET Core library -- they are separate targets. From a UWP or .NET Core project, you are able to reference a .NET Standard library, but the reverse is not true.

**Comment by weshaggard** [comment]
It is by design that the Microsoft.NETCore.UniversalWindowsPlatform package cannot be referenced outside of a UWP application or library.
