### ISSUE TITLE
Add xunit.analyzers to corefx infrastructure 

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#22210]
I just saw a PR in Roslyn: https://github.com/dotnet/roslyn/pull/20814

The Anlayzer found multiple missing facts, etc. Etc.  This could benefit corefx as well.
I'm not sure how to integrate this in a non-intrusive way - VS integration by default would be a super plus

**Comment by weshaggard** [comment]
@hughbe if this is something you are interested in tackling you can update the analyzers that corefx uses from the buildtools repo, see https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.CodeAnalysis/PackageFiles/codeAnalysis.targets.

**Comment by ViktorHofer** [comment]
I just saw this. I think we should do this after we brought the official xunit runner in.

**Comment by ViktorHofer** [comment]
This is already integrated in the infrastructure and can now be enabled by settings `EnableXUnitAnalyzer` to true in the project file. I'm opening a new issue to start a community effort to enable the analyzers in our test projects: https://github.com/dotnet/corefx/issues/38677
