### ISSUE TITLE
RSAKeyValue.LoadXml not working when XmlElement input has namespace prefix.

### ISSUE THREAD

**Issue by brunin2509** [dotnet/corefx#22229]
Hello, guys!

When I used the method LoadXml from RSAKeyValue.cs, I was always receiving the following exception:

`System.Security.Cryptography.CryptographicException: 'Root element must be KeyValue element in namepsace http://www.w3.org/2000/09/xmldsig#'`

After searching for some bug, I've found that the second IF statement inside LoadXml is verifying if value.Name (instead of value.LocalName) is different from "KeyValue". Because of that, when this method receives any XmlElement that has namespace prefix, it will throw the exception above. 

Code with the bug:
```csharp
if (value.Name != KeyValueElementName
	|| value.NamespaceURI != SignedXml.XmlDsigNamespaceUrl)
{
	throw new CryptographicException($"Root element must be {KeyValueElementName} element in namepsace {SignedXml.XmlDsigNamespaceUrl}");
}
```

How I think it should be:
```csharp
if (value.LocalName != KeyValueElementName
	|| value.NamespaceURI != SignedXml.XmlDsigNamespaceUrl)
{
	throw new CryptographicException($"Root element must be {KeyValueElementName} element in namepsace {SignedXml.XmlDsigNamespaceUrl}");
}
```

By the way, you could also fix the "namepsace" inside the CryptographicException message hehe.

Thanks!

**Comment by krwq** [comment]
@brunin2509, agreed this looks like a bug - would you like to send a PR with the patch?

**Comment by brunin2509** [comment]
Sure, I think I can do that! Thanks for the reply!

**Comment by brunin2509** [comment]
@krwq I've just submitted the PR (https://github.com/dotnet/corefx/pull/22336). Is there anything else I could do?

**Comment by krwq** [comment]
@brunin2509 thank you a lot! I think all of the comments will be in the PR
