### ISSUE TITLE
ILC Failed to compile to test projects in multi file mode

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#22222]
ILC failed to compile System.Linq.Expressions.Tests and System.Runtime.Tests in multi file mode.

Multi file is enabled in:

- Release-x64
- Debug-x86

cc: @joshfree

**Comment by tijoytom** [comment]
@safern 
System.Runtime.Test fails with a nutc issue and is tracked by TFS:464118
System.Linq.Expressions seems to be fine on my localmachine with the latest bits

**Comment by safern** [comment]
System.Linq.Expressions still failed to ILC in todays build. When are your latest bits from? Are they running in helix against them yet?

**Comment by safern** [comment]
@tijoytom today's build didn't show this failures so closing the issue.
