### ISSUE TITLE
Consider removing ConfigurationManager dependency from System.Drawing.Common

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#22233]
The only usage of ConfigurationManager is in this internal class:

https://github.com/dotnet/corefx/blob/master/src/System.Drawing.Common/src/System/Drawing/BitmapSelector.cs#L33
In turn, `BitmapSelector` is only used by one public type:
https://github.com/dotnet/corefx/blob/master/src/System.Drawing.Common/src/System/Drawing/ToolboxBitmapAttribute.cs

There is already a "graceful" fallback path if there is no "system.drawing" ConfigurationSection defined, so we can easily just delete it. I find it extremely unlikely that anybody would ever care about this functionality going away: it looks incredibly obscure, and not that useful in the first place. The main use case seems to be for UI designers (like the VS WinForms designer), to select different bitmaps with. The .NET Core version of the library likely won't ever be used for that.

Thoughts @hughbe @stephentoub ?

**Comment by hughbe** [comment]
From the comments:

> /// Gets the bitmap ID suffix defined in the application configuration, or string.Empty if
> /// the suffix is not specified.  Internal for unit tests
 
Could it be that this was never meant to have been exposed?

**Comment by mellinoe** [comment]
This dependency was removed as part of targeting .NET Core 2.0.
