### ISSUE TITLE
SqlClient - ManagedSNI doesn't work on Windows?

### ISSUE THREAD

**Issue by EgorBo** [dotnet/corefx#22236]
In **System.Data.SqlClient** solution in **System.Data.SqlClient.Tests** I created a small simple test with the following code:
```
[Fact]
public static void SimpleTest()
{
    string cs = @"Server=.\SQLEXPRESS;Database=...;User Id=...;Password=...;";
    using (var connection = new SqlConnection(cs))
    {
        connection.Open();
    }
}
```

the SQL Server is running and the test passes. But if I go to the TdsParserStateObjectFactory.Windows.cs
and change `UseManagedSNI = false` to `true` -- the tests fails with 

```
System.Net.Sockets.SocketException: 'An existing connection 
was forcibly closed by the remote host'
at DoBeginReceiveFrom(...)
```

Am I doing something wrong or ManagedSNI mode doesn't work on Windows at the moment?

**Comment by corivera** [comment]
Can you post the full stack trace?

**Comment by EgorBo** [comment]
@corivera https://gist.github.com/EgorBo/da39a750f3f52bb5cc20b11ac6d7739d

**Comment by corivera** [comment]
Looks like something is failing during the instance name resolution step.

@geleems Can you look into this?

**Comment by EgorBo** [comment]
@corivera @geleems if I specify port in the connection string - it works
string cs = @"Server=.\SQLEXPRESS,1433;
(since port is defined - it won't call `GetPortByInstanceName`)

**Comment by geleems** [comment]
@EgorBo Did you turn on ***SQL Server Browser*** ?

**Comment by EgorBo** [comment]
@geleems good catch! It was disabled (I enabled and now it works even without the 1433 in CS)
Is it expected behavior? Classic .NET and corefx with native SNI work even if the SQL Server Browser is disabled.

**Comment by geleems** [comment]
@EgorBo 
***SQL Server Browser*** is the one who translates instance name into port number. Without it, connection should fail if connection string contains only instance name without port. It is the same behavior both in `Native SNI` and `ManagedSNI`.

I am currently trying to figure out how you made connection successfully with `Native SNI` with this connection string: `string cs = @"Server=.\SQLEXPRESS;Database=...;User Id=...;Password=...;";`
This connection string only contains instance name, and it should be *impossible* to translate it into port without SQL Server Browser. I tried to reproduce the behavior, and I was never able to make connection successfully without SQL Server Browser both in `Native SNI` and `ManagedSNI`.

Are you sure you are able to connect to SQL Server with ***SQL Server Browser*** **off** on `Native SNI` by the connection string that only contains instance name and no port specified??

**Comment by EgorBo** [comment]
@geleems yeah this is what confuses me the most now,
And yes I am totally sure SQLBrowser is disabled and this case corefx+NativeSNI as well as classic .net 4.6 still open connection starting with `Server=.\SQLEXPRESS`

![g1qtquk](https://user-images.githubusercontent.com/523221/28194536-99522488-684d-11e7-80e4-ce17bdd92c00.png)

**Comment by corivera** [comment]
Are you still able to connect if you change the instance's TCP port or Named Pipe path (if enabled)?

**Comment by EgorBo** [comment]
I mean here in https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNIProxy.cs#L399 it throws an exception instead of assigning a default port like it's done in line 409 but it's just my guess as I didn't see the native implementation.

**Comment by EgorBo** [comment]
@corivera will try in a moment

**Comment by EgorBo** [comment]
@corivera 
Ok I've changed the TCP port to 1435, SQLBroswer is disabled, other protocols are disabled
NativeSNI doesn't work.
if I specify 1435 in the connection string `@"Server=.\SQLEXPRESS,1435` - NativeSNI works
if I enable SQLBroswer service - NativeSNI works.

**Comment by corivera** [comment]
@geleems Seems like we may be missing some fallback mechanism in the managed SNI code then. Or maybe there's some caching going on somewhere.

**Comment by geleems** [comment]
@EgorBo 
Can you switch the `SQLEXPRESS` instance TCP port back to 1433, and try this connection string: `string cs = @"Server=.\SQLEXPRESS1111;` with `Native SNI` and  with SQL Server Browser ***off*** ?

If it still able to connect to SQL Server instance `SQLEXPRESS`, then it seems `Native SNI` trys 1433 when port resolution fails.
If it cannot connect, then it seems there is a cache that stores `SQLEXPRESS == 1433` information.

**Comment by jhudsoncedaron** [comment]
> Seems like we may be missing some fallback mechanism in the managed SNI code then

That would be correct, but I'm pretty sure the fallback mechanism is shared memory which is a royal pain in managed code and won't work when talking to another computer.

**Comment by EgorBo** [comment]
@geleems @jhudsoncedaron 
yeah looks like NativeSNI uses "Shared Memory" as a fallback protocol (Managed SNI doesn't).
SQLEXPRESS1111 doesn't work in both Native and Managed

.\SQLEXPRESS works in NativeSNI only if "Shared Memory" is enabled (when SQLBroswer is disabled).

**Comment by corivera** [comment]
@geleems If you have time, it might be a good idea to improve the error reporting in this case so that's it's clear that it's a connection failure rather than a connection reset error.

**Comment by geleems** [comment]
I added appropriate error message for the error when SQL Server Browser is not accessible: https://github.com/dotnet/corefx/pull/22400
