### ISSUE TITLE
Add a replacement for IsPathRooted that actually returns if a path is relative

### ISSUE THREAD

**Issue by davkean** [dotnet/corefx#22245]
As [mentioned previously](https://github.com/dotnet/corefx/issues/21933), for better or worse, we use Uri over the Path APIs in Visual Studio due to two main reasons, this represents the first reason.

Windows [docs state](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx) (emphasis mine) and IsPathRooted implements this behavior:

> **Fully Qualified vs. Relative Paths**
> For Windows API functions that manipulate files, file names can often be relative to the current directory, while some APIs require a fully qualified path. _**A file name is relative to the current directory if it does not begin**_ with one of the following:
> - A UNC name of any format, which always start with two backslash characters ("\\"). For more information, see the next section.
> - A disk designator with a backslash, for example "C:\" or "d:\".
> - **_A single backslash, for example, "\directory" or "\file.txt". This is also referred to as an absolute path._**

However, that last point is incorrect. 

A path of `\directory' or '\file.txt' is treated as _relative_ to the root of the current directory as this clearly demonstrates:

``` C#
Environment.CurrentDirectory = @"C:\Temp";

Console.WriteLine(Path.GetFullPath(@"\Foo"));

Environment.CurrentDirectory = @"D:\";

Console.WriteLine(Path.GetFullPath(@"\Foo"));
```

Which outputs:

```
C:\Foo
D:\Foo
```

Inside VS we need to answer; _will this path change based on the current directory?_. IsPathRooted does not supply that - whereas, Uri does:

``` C#
Console.WriteLine("Path.IsPathRooted: " + Path.IsPathRooted(@"\Foo"));
Console.WriteLine("Uri.TryCreate: " + Uri.TryCreate(@"\Foo", UriKind.Absolute, out Uri result));
```

Which outputs:

```
Path.IsPathRooted: True
Uri.TryCreate: False
```

I suspect what Windows docs is referring to and what IsPathRooted is actually handling, is the _device namespace_, such as  `\Device\HarddiskVolume4` but as far as I'm aware you cannot use that syntax via Win32, you need to prepend; `\\.\`.

**Comment by davkean** [comment]
tag @stephentoub @JeremyKuhne

**Comment by JeremyKuhne** [comment]
@davkean This one is a pet peeve of mine. We already have this implemented:

``` C#
/// <summary>
/// Returns true if the path specified is relative to the current drive or working directory.
/// Returns false if the path is fixed to a specific drive or UNC path.  This method does no
/// validation of the path (URIs will be returned as relative as a result).
/// </summary>
/// <remarks>
/// Handles paths that use the alternate directory separator.  It is a frequent mistake to
/// assume that rooted paths (Path.IsPathRooted) are not relative.  This isn't the case.
/// "C:a" is drive relative- meaning that it will be resolved against the current directory
/// for C: (rooted, but relative). "C:\a" is rooted and not relative (the current directory
/// will not be used to modify the path).
/// </remarks>
internal static bool IsPartiallyQualified(string path)
```

https://github.com/dotnet/coreclr/blob/a2329cb926774ef13b09c377f1c866f68718e2aa/src/mscorlib/shared/System/IO/PathInternal.Windows.cs#L284-L308

> I suspect what Windows docs is referring to and what IsPathRooted is actually handling, is the device namespace, such as \Device\HarddiskVolume4 but as far as I'm aware you cannot use that syntax via Win32, you need to prepend; \\.\.

It is possible they're thinking of the NT or device path syntax- it might also just be a confusing technicality.

My expectation was to make this API public as `IsPathFullyQualified()`. Does that meet your needs?

**Comment by davkean** [comment]
Yeah that sounds like it would work. We'd need this for desktop - or I can just grab the source code if its self contained.

**Comment by JeremyKuhne** [comment]
@davkean Wouldn't be hard- the internal API is already there. :)

https://referencesource.microsoft.com/#mscorlib/system/io/pathinternal.cs,465

**Comment by JeremyKuhne** [comment]
@niustephanie Can you prep this for API review?
