### ISSUE TITLE
UAPAOT: System.Diagnostics.Tests.ProcessStartInfoTests/StartInfo_NotepadWithContent(useShellExecute: False)

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#22244]
Failed in Outerloop during validation for #22237:

https://mc.dot.net/#/user/CIPop/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/343581b48553b789c3a92222e109b9d4b07927c1/workItem/System.Diagnostics.Process.Tests/analysis/xunit/System.Diagnostics.Tests.ProcessStartInfoTests~2FStartInfo_NotepadWithContent(useShellExecute:%20False)

```
Windows.10.Amd64.ClientRS2.Open-Debug-x64
Unhandled Exception of Type System.InvalidOperationException
Message :
System.InvalidOperationException : WaitForInputIdle failed.  This could be because the process does not have a graphical interface.
Stack Trace :
   at System.Diagnostics.Process.WaitForInputIdleCore(Int32 milliseconds)
   at System.Diagnostics.Process.WaitForInputIdle(Int32 milliseconds)
   at System.Diagnostics.Process.WaitForInputIdle()
   at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent(Boolean useShellExecute)
```

**Comment by Jiayili1** [comment]
This issue is repro on UWP ILC tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170714.02/workItem/System.Diagnostics.Process.Tests/analysis/xunit/System.Diagnostics.Tests.ProcessStartInfoTests~2FStartInfo_NotepadWithContent(useShellExecute:%20False)

**Comment by Jiayili1** [comment]
Failed again on UWP ILC Tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170718.01/workItem/System.Diagnostics.Process.Tests/analysis/xunit/System.Diagnostics.Tests.ProcessStartInfoTests~2FStartInfo_NotepadWithContent(useShellExecute:%20False)

**Comment by joperezr** [comment]
Poaching from @krwq :)

**Comment by danmosemsft** [comment]
These should be PNSE
```
C:\git\corefx\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Uap.cs:
   24:         private bool WaitForInputIdleCore(int milliseconds) => throw new InvalidOperationException(SR.InputIdleUnkownError);

C:\git\corefx\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Unix.cs:
  559:         private bool WaitForInputIdleCore(int milliseconds) => throw new InvalidOperationException(SR.InputIdleUnkownError);
```
And tests should match.

it would be nice to fix the misspelling of Unknown also
