### ISSUE TITLE
System.Diagnostics.Process.MainModule.FileName has junk characters in the prefix on UAP

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#22264]
(Test case will be added soon, creating issue so that I can disable that in the PR)

Junk characters might be BOM or Xunit display error

```
 ERROR:    System.Diagnostics.Tests.ProcessTests.TestMainModuleOnNonOSX [FAIL]
        Assert.EndsWith() Failure:
        Expected:    xunit.runner.uap.exe
        Actual:   ┬╖┬╖┬╖XUnit.Runner.Uap.exe
```

**Comment by danmosemsft** [comment]
This test name should be corrected `public void TestMainModuleOnNonOSX()` it is testing OSX also.

**Comment by krwq** [comment]
Seems like original issue was an Xunit/Xunit.Runner.Uap display error
