### ISSUE TITLE
Enable NamedPipe tests against updated Windows build

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#22271]
When fixing #21392 we discovered a regression that was made after RS1 on the `WaitNamedPipe()` PInvoke when running inside an appcontainer. This has now been fixed for RS3, but since we are running our CI tests in RS2 then those tests will hang forever. I have already validated that in RS3 all the tests disabled by this issue are passing succesfully. This issue is to track the work of re-enabling those tests once we are running our CI on RS3. 

This bug will obviously go beyond ZBB.

cc: @JeremyKuhne @AlexGhiondea @joshfree

**Comment by danmosemsft** [comment]
@joperezr verified the Windows bug fixes our tests: we are waiting on the build to be updated now.

**Comment by danmosemsft** [comment]
Casey is updating the build in Helix now. Anyway @joperezr you should be able to enable the tests dependent on a condition as @JeremyKuhne did -- see PlatformDetection, IsWindows10Version16251OrGreater.
This assumes that the fix got to RS_PRERELEASE which is where we pull from.

**Comment by joperezr** [comment]
I didn't know we had that in Platform detection, I will add that to the tests. Do we want to do it only in master or do we want to port this fix to release as well?

**Comment by danmosemsft** [comment]
Since it adds test coverage of something we expect in release, I would expect it to need to go to release.

@MattGal tells me the test machines just now got updated to rs_prerelease.170805-2131. I don't know what build number that corresponds to.  You will be able to read it off from what we log in the RuntimeInformation test eg at
(https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170807.02/workItem/System.Runtime.InteropServices.RuntimeInformation.Tests/wilogs):

2017-08-07 13:07:51,013: INFO: proc(54): run_and_log_output: Output:  OS=Microsoft Windows 10.0.14393 OSVer=Microsoft Windows NT 6.2.9200.0 OSArch=X64 Arch=X64 Framework=.NET Core 4.6.00001.0

In the above it is 14393.

**Comment by MattGal** [comment]
Sorry @danmosemsft , didn't think it was relevant.  Full build string is 16262.rs_prerelease.170805-2131, so plenty higher than 14393.

**Comment by danmosemsft** [comment]
@joperezr can you give an update on this one? branch is in escrow shortly.

**Comment by joperezr** [comment]
I'll take care of it by tomorrow EOD. Sorry for the delay.

**Comment by joshfree** [comment]
Moving this to UWP6.1.

**Comment by danmosemsft** [comment]
@joperezr did you end up doing this?

**Comment by joperezr** [comment]
yeah, it was done by: https://github.com/dotnet/corefx/pull/24307

**Comment by pjanotti** [comment]
Actually tests are still disabled since we had to revert the change that re-enabled them.

**Comment by ptorr-msft** [comment]
Opening named pipes via `CreateFileFromApp` *should* work in the daily Windows builds now.

**Comment by joperezr** [comment]
sorry @pjanotti you are right, I didn't track the revert. I'll assign this to you since you are the area owner now.

**Comment by joperezr** [comment]
@ViktorHofer all of these issues that got closed, will they be opened in the new repo?

**Comment by ViktorHofer** [comment]
We don't have UWP tests anymore in master and I assumed that this issue is tracking a disabled UWP test. Is that wrong?

**Comment by joperezr** [comment]
oh I see, this one in particular does seem like that is the case, I just saw that a bunch of issues in general got closed and just wanted to know if this was just something we didn't want to track any longer or it was just part of the consolidation.

**Comment by ViktorHofer** [comment]
So yes, I closed issues that we don't track anymore. We won't close any issues as part of the consolidation
