### ISSUE TITLE
FileSystem intermittent test failures

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#2227]
Tests for the FileSystem class intermittently fail. The offenders are:

Test Failure | Notes
---------------- | -------------------- 
File_WriteAll_all.runTest |
File_ReadAll_all.runTest |
File_WriteAllBytes_StrBtA.runTest |
File_AppendAll_all.runTest | 
File_Copy_str_str_b.runTest | also leaves leftover test directories (only on failure)
FileInfo_Refresh.runTest | also leaves leftover test directories (only on failure)
FileInfo_getLastWriteTime | according to #1313 - I detected no failures on my runs
FileInfo_Create_str | 
DirectoryInfo_Refresh.runTest  | also leaves leftover test directories (only on failure)
DirectoryInfo_Move_str.runTest | also leaves leftover test directories (only on failure)

The source of the failures is the repeated use of the same test file names causing file already in use exceptions.

**Comment by mmitche** [comment]
Thanks for the detailed info!  I was just about to file another of these :)

**Comment by ianhays** [comment]
My pleasure! I'm preparing a PR now to get it running without errors... should be up by the end of tomorrow :)
