### ISSUE TITLE
[System.Diagnostics.Process]::Start() different behavior from FullCLR

### ISSUE THREAD

**Issue by SteveL-MSFT** [dotnet/corefx#22280]
Repro:
Pass `c:\` as the process to start

```powershell
PS> [System.Diagnostics.Process]::Start("c:\")
```

Expected:
With FullCLR (I'm using 4.7.02531 on Win10) it will open that folder in explorer

Actual:
If you do the same with 2.0.0-preview2-006502 you get Access Denied.  
This causes a regression in PowerShell https://github.com/PowerShell/PowerShell/issues/4252

**Comment by stephentoub** [comment]
> This causes a regression in PowerShell 

Regression from when running on what, .NET Framework or .NET Core 1.x?

Have you tried setting UseShellExecute to true explicitly? It's false by default in core, by design, as true can't work on some platforms.
