### ISSUE TITLE
[System.Diagnostics.Process]::Start() doesn't return error on Unix if fileName is directory

### ISSUE THREAD

**Issue by SteveL-MSFT** [dotnet/corefx#22299]
Repro:

Using PowerShell:
```powershell
PS> [System.Diagnostics.Process]::Start("/home")
```

Expected:
error that `/home` isn't valid or access denied

Actual:
New forked powershell process

**Comment by karelz** [comment]
Does it repro in C# with `Process.Start("/home")` call?

**Comment by krwq** [comment]
Is it possibly ShellExecute=true? that would sound like vaild behavior then. Not sure what the value for that is by default on linux, if false then it's a bug

**Comment by mellinoe** [comment]
I did some very basic tests on .NET Core 1.1, and there does seem to be some strange behavior. `Process.Start("/home")` does succeed. On the returned process object, `ProcessName` returns "dotnet", `StartInfo.UseShellExecute` returns false, and `MainModule` returns null (which seems bad).

**Comment by stephentoub** [comment]
> On the returned Process object, ProcessName returns "dotnet", StartInfo.UseShellExecute returns false, and MainModule returns null (which seems bad).

Presumably the exec call fails, such that the ExitCode indicates the failure?

**Comment by mellinoe** [comment]
In my test, `ExitCode` returns 13.

**Comment by stephentoub** [comment]
And errno 13 is permission denied.

**Comment by SteveL-MSFT** [comment]
errno 13 is expected and what should be returned

In PowerShell, we rely on xdg-open as the equivalent to shellexecute on Windows.

**Comment by stephentoub** [comment]
> In PowerShell, we rely on xdg-open as the equivalent to shellexecute on Windows.

https://github.com/dotnet/corefx/issues/19956

**Comment by stephentoub** [comment]
> errno 13 is expected and what should be returned

So it's behaving as expected?  I thought you were asking that the API, for example, throw an exception from Start.

**Comment by SteveL-MSFT** [comment]
Sorry should have been more specific.  We expect a Win32Exception to be thrown and NativeErrorCode to be 13.  This doesn't happen for when filename is a directory.

**Comment by SteveL-MSFT** [comment]
Simple repro
```c#
using System;
using System.Diagnostics;

namespace test
{
    class Program
    {
        static void Main(string[] args)
        {
            Process p = new Process();
            p.StartInfo.FileName = "/home";
            p.Start();
        }
    }
}
```
