### ISSUE TITLE
Hang/Race-condition observed in Sockets

### ISSUE THREAD

**Issue by harshjain2** [dotnet/corefx#22318]
We are using Sockets and using `BufferedStream` of size [8 * 1024](https://github.com/harshjain2/vstest/blob/fe6fbc50699511baf8bc838bfc23ff5278fb5de3/src/Microsoft.TestPlatform.CommunicationUtilities/SocketCommunicationManager.cs).

We are observing an intermittent hang because of which the test execution doesn't complete as expected. 
Is this a known issue?
We tried debugging, but couldn't find anything wrong.

Repro steps :
1. Clone the repositroy : https://github.com/harshjain2/vstest
2. Checkout branch hangrepro.
3. From the root of repo, invoke `build.cmd -noloc`
4. From the root of repo, invoke `test.cmd`

For reproing this issue consistently, I have increased the buffer size to 1024 * 1024. 

cc: @codito

**Comment by karelz** [comment]
Which .NET Core version do you use? Latest 2.0 Preview 2? Daily 2.1 builds? Older 1.1/1.0?
Did you try to isolate the repro to a specific test case? The repo above has quite a bunch of tests :(
How often does it happen?

**Comment by karelz** [comment]
@stephentoub @geoffkizer did we fix anything in the area recently? I vaguely remember we had similar-ish hang issues in Sockets ...

**Comment by stephentoub** [comment]
@harshjain2, there's a ton of code in that repo.  Do you have an isolated repro you can share?  We can't debug all of VSTest.  Without knowing more, my initial guess would simply be that if the buffered stream is sitting around the socket that you're not flushing everything you need to, but I've not actually looked at the code.

> I vaguely remember we had similar-ish hang issues in Sockets

@karelz, not that I'm aware of.

**Comment by harshjain2** [comment]
- Dotnet CLI version 2.1.0-preview1-006329

- I have tried to narrow down the repro to a single test project.
Here is the specific test project in which I am getting a consistent repro. 
This project targets netcoreapp but we have also seen this issue reproing for full clr as well.
E:\Code\github\harshjain2\vstest\tools\dotnet\dotnet.exe E:\Code\github\harshjain2\vstest\artifacts\Debug\netcoreapp2.0\vstest.console.dll E:\Code\github\harshjain2\vstest\test\Microsoft.Te
stPlatform.Utilities.UnitTests\bin\Debug\netcoreapp1.0\Microsoft.TestPlatform.Utilities.UnitTests.dll /platform:x64 /framework:.NETCoreApp,Version=v1.0 /testAdapterPath:E:\Code\github\harshjain
2\vstest\packages\MSTest.TestAdapter\1.1.18\build\_common /logger:"trx;LogFileName=Microsoft.TestPlatform.Utilities.UnitTests.dll_netcoreapp1.0_TrxLogResults.trx" /logger:"console;verbosity=min
imal"

- I've repro'd this issue on Windows 10 OS.

**Comment by stephentoub** [comment]
> I have tried to narrow down the repro to a single test project

@harshjain2, I meant a repro outside of VSTest, having nothing to do with it, a little C# app that would demonstrate the problem.

**Comment by harshjain2** [comment]
@stephentoub Sure, I can try to repro the issue using C# app.

**Comment by stephentoub** [comment]
> I can try to repro the issue using C# app.

Thanks.

**Comment by davidsh** [comment]
Closing this issue for now.  Please re-open when a verified repro is available.

**Comment by karelz** [comment]
BTW: The issue above was for full .NET Framework - we should not track such bugs on GitHub as it is unrelated to CoreFX source code.

**Comment by jnm2** [comment]
They go in https://github.com/Microsoft/dotnet/issues, don't they?

**Comment by karelz** [comment]
@jnm2 I think it was meant more for higher-level all-.NET feedback, rather than specific bug reports. But it is mostly guess work on my side.
I don't think we have any plans to do .NET Framework bug tracking on GitHub (at least engineers owning the code across .NET Framework, .NET Core and UWP are not aware of that)

 @richlander will know the plan for https://github.com/Microsoft/dotnet repo
