### ISSUE TITLE
Failed to download package 'Microsoft.NETCore.Targets.1.0.1' in CI

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#22321]
Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_debug/125/
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_fedora24_release/lastCompletedBuild/
Failed to generate the test report

/mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_release/Tools/dotnetcli/sdk/2.0.0-preview1-005977/NuGet.targets(97,5): error : Failed to download package 'Microsoft.NETCore.Targets.1.0.1' from 'https://api.nuget.org/v3-flatcontainer/microsoft.netcore.targets/1.0.1/microsoft.netcore.targets.1.0.1.nupkg'. [/mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_release/external/test-runtime/XUnit.Runtime.depproj] [/mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_release/external/test-runtime/XUnit.Runtime.depproj]

**Comment by karelz** [comment]
@weshaggard @mellinoe any idea?
cc @danmosemsft

**Comment by weshaggard** [comment]
Looks like a network timeout issue with nuget. I don't think there is much we can do with this.
