### ISSUE TITLE
AppDomain events have wrong sender

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#22343]
```
AppDomain.UnhandledExceptionEventHandler
AppDomain.AssemblyLoadEventHandler
AppDomain.ResolveEventHandler
AppDomain.FirstChanceException
AppDomain.ProcessExit
...
```

The sender argument for these events should be AppDomain.CurrentDomain, but it is actually the internal AppDomain object.

#22330 fixed this for FirstChanceException event on uapaot only. This should be fixed for all of the events and for both CoreCLR and CoreRT. Also, tests should be added.

We may consider fixing this by moving AppDomain back to CoreLib. Having it in CoreFX seems to have less and less value.

**Comment by jkotas** [comment]
Tagging this with UWP6.0 milestone for visibility, though I will likely get postponed at this point.

**Comment by jkotas** [comment]
cc @DnlHarvey

**Comment by danmosemsft** [comment]
@DnlHarvey this does not seem necessary for this release, moving out. Feel free to push back.
