### ISSUE TITLE
CI issue: Error during cleanup: java.io.IOException: in OSX Debug

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#22347]
https://ci3.dot.net/job/dotnet_corefx/job/master/job/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/1318/console

https://ci3.dot.net/job/dotnet_corefx/job/master/job/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/1316/console

and a few more in the last couple of hours.

**Comment by karelz** [comment]
@weshaggard @mellinoe are you aware of this?
cc @danmosemsft

**Comment by mellinoe** [comment]
I believe we have seen this sort of problem infrequently for a long time. This category of problems doesn't have much to do with our tests or our build infrastructure, but it's rather a problem with Jenkins itself, or maybe a problem with the way our Jenkins servers are configured. @mmitche Do you have any more specific info about this particular issue?

**Comment by danmosemsft** [comment]
@dotnet/dnceng

**Comment by dleeapho** [comment]
@maririos PTAL CI failure. Your tracking issue: https://github.com/dotnet/core-eng/issues/1231

**Comment by maririos** [comment]
Thanks @JonHanna for reporting the issue.

Rebooting the server and the nodes fixed the issue. Recent jobs executed in the nodes have completed 
successfully.
