### ISSUE TITLE
Add method IsPathFullyQualified() to replace IsPathRooted() for returning if a path is relative

### ISSUE THREAD

**Issue by niustephanie** [dotnet/corefx#22345]
A common mistake is to assume that `IsPathRooted()` paths cannot be relative. To make the distinction between rooted and relative clear, `Path` should implement a `IsPathFullyQualified()` method that returns whether or not changing the current directory will change the path.

Details in issue #22245

## Rationale and Usage
Currently, `IsPathRooted()` does not answer the question of whether changing the current directory will change a given path. Adding `IsPathFullyQualified()` will more explicitly and correctly address this question.

Note: `IsPathRelative()` may seem like a more intuitive name for the method to be added. However, `IsPathRelative()` suggests that the method determines whether or not the path contains '.' or '..', which is not true. `IsPathFullyQualified()` is broader and addresses whether the path will change based on the current directory. This terminology is also consistent with [documentation.](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#fully_qualified_vs._relative_paths) 

## Proposed API
``` c#
       /// <summary>
       /// Returns false if the path specified is relative to the current drive or working directory.
       /// Returns true if the path is fixed to a specific drive or UNC path.  This method does no
       /// validation of the path (URIs will be returned as relative as a result).
       /// </summary>
       /// <remarks>
       /// Handles paths that use the alternate directory separator.  It is a frequent mistake to
       /// assume that rooted paths (Path.IsPathRooted) are not relative.  This isn't the case.
       /// "C:a" is drive relative- meaning that it will be resolved against the current directory
       /// for C: (rooted, but relative). "C:\a" is rooted and not relative (the current directory
       /// will not be used to modify the path).
       /// </remarks>
      public static bool IsPathFullyQualified(string path)
```
## Details
Doesn't handle URIs (will say all URIs are relative).
## Open Questions
N/A
## Pull Request
N/A

**Comment by JeremyKuhne** [comment]
Note that this is already implemented as an internal method:

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/IO/PathInternal.Windows.cs#L270-L306

**Comment by terrajobst** [comment]
We've [reviewed & approved](https://youtu.be/jKQWMCPZ08Y?t=55) this issue today:

* Should we fix `IsPathRooted` to not consider `\foo.txt` and `C:foo.txt` as being rooted, i.e. make it match `IsFullyQualified`
    - No, we believe this would be an unacceptable breaking change
    - Also, we'd no longer match the Windows definition of rooted paths, relative paths, and fully qualified paths.
    - On Unix: `IsPathRooted` and `IsFullyQualified` are effectively the same
* We should document `IsPathRooted` as a problematic API (because most customers don't want the behavior), we shouldn't deprecate it but we should probably add it to the platform-compat analyzer
