### ISSUE TITLE
Add Random Span-based APIs

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#22356]
Separated out of https://github.com/dotnet/corefx/issues/21281 for tracking purposes.

- [x] Implement in System.Private.CoreLib in coreclr (corert shares the same file)
- [x] Expose from System.Runtime.Extensions contract in corefx
- [x] Add tests to System.Runtime.Extensions tests in corefx

```C#
namespace System
{
    public class Random
    {
        public virtual void NextBytes(Span<byte> buffer);
        …
    }
}
```

Implementation should be in terms of `Next()`.  The `NextBytes(byte[])` base method is implemented in terms of `InternalSample`, but `NextBytes(Span<byte>)` shouldn't be implemented in terms of that, as it's not public and thus an existing derived type couldn't have overridden it, and thus the new virtual wouldn't pick up existing behaviors.  It also shouldn't be in terms of `NextBytes(byte[])`, as that would require allocating/copying an array, largely defeating the purpose of the method (at least for the base class).  But since `Next()` on the base class just delegates to `InternalSample()`, `Next()` is a reasonable thing to base the implementation on, e.g.
```C#
public virtual void NextBytes(Span<byte> buffer)
{
    for (int i = 0; i < buffer.Length; i++)
    {
        buffer[i] = (byte)(Next() & 0xFF);
    }
}
```

**Comment by MaggieTsang** [comment]
@stephentoub Should the existing `NextBytes(byte[])` also call `Next()`? Otherwise, if you derive the class `NextBytes(Span<byte>)` and `NextBytes(byte[])` won't give identity results if you override `Next()`.

**Comment by stephentoub** [comment]
We shouldn't change the existing `NextBytes(byte[])`, as that could be a breaking change (it will now be impacted by a virtual it wasn't previously impacted by), and it could have a performance impact (each byte would then incur an extra virtual method call instead of a non-virtual call).

**Comment by jnm2** [comment]
I'm curious, why is it written as `(byte)(Next() & 0xFF)` instead of `(byte)Next()`?

**Comment by stephentoub** [comment]
It could be :smile:

**Comment by jnm2** [comment]
😄 I was curious what the other overload was doing...

https://github.com/dotnet/coreclr/blob/4d9f5e3a0bc2b01c99337d68a8c90fc77b3182bd/src/mscorlib/shared/System/Random.cs#L263-L271

**Comment by jnm2** [comment]
😄 I was curious what [NextBytes(byte[]) was doing](https://github.com/dotnet/coreclr/blob/4d9f5e3a0bc2b01c99337d68a8c90fc77b3182bd/src/mscorlib/shared/System/Random.cs#L263-L271)... now I wish I hadn't looked...

```c#
        public virtual void NextBytes(byte[] buffer)
        {
            if (buffer == null) throw new ArgumentNullException(nameof(buffer));
            Contract.EndContractBlock();
            for (int i = 0; i < buffer.Length; i++)
            {
                buffer[i] = (byte)(InternalSample() % (Byte.MaxValue + 1));
            }
        }
```

**Comment by stephentoub** [comment]
I basically just copied NextBytes for my example (changing the `% 256` to `& 0xFF`.

But, yeah, that's unnecessarily complex.  And because the JIT doesn't know that InternalSample() returns a non-negative value, the resulting asm is going to be worse than it needs to be.

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/13708 and https://github.com/dotnet/corefx/pull/23692
