### ISSUE TITLE
System.Runtime.ExceptionServices.Tests.ExceptionDispatchInfoTests/StaticThrow_UpdatesStackTraceAppropriately failed in UapAot

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#22351]
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170717.02/workItem/System.Runtime.Tests/analysis/xunit/System.Runtime.ExceptionServices.Tests.ExceptionDispatchInfoTests~2FStaticThrow_UpdatesStackTraceAppropriately

Message :
```
Assert.Equal() Failure\r\nExpected: 1\r\nActual:   0
```

Stack Trace
```
at System.Runtime.ExceptionServices.Tests.ExceptionDispatchInfoTests.StaticThrow_UpdatesStackTraceAppropriately()
   at Object _$ILCT$+$ILT$ReflectionDynamicInvoke$.InvokeRetV(Object, IntPtr, InvokeUtils+ArgSetupState&, Boolean) + 0x51
   at Object System.InvokeUtils+CalliIntrinsics.Call(IntPtr, Object, IntPtr, InvokeUtils+ArgSetupState&, Boolean) + 0x43
   at Object System.InvokeUtils.CallDynamicInvokeMethod(Object, IntPtr, Object, IntPtr, IntPtr, Object, Object[], BinderBundle, Boolean, Boolean) + 0x183
```

cc: @danmosemsft

**Comment by Jiayili1** [comment]
Failed again: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170718.01/workItem/System.Runtime.Tests.Execution/analysis/xunit/System.Runtime.ExceptionServices.Tests.ExceptionDispatchInfoTests~2FStaticThrow_UpdatesStackTraceAppropriately

**Comment by danmosemsft** [comment]
Another one looking for "end of stack trace" dupe of https://github.com/dotnet/corefx/issues/22350.
@trylek

**Comment by Jiayili1** [comment]
This issue is repro on UWP ILC tests (UWP6.0), detail: https://mc.dot.net/#/product/netcore/uwp60/source/official~2Fcorefx~2Frelease~2Fuwp6.0~2F/type/test~2Ffunctional~2Filc~2F/build/20170722.02/workItem/System.Runtime.Tests/analysis/xunit/System.Runtime.ExceptionServices.Tests.ExceptionDispatchInfoTests~2FStaticThrow_UpdatesStackTraceAppropriately

**Comment by safern** [comment]
Did the fix make it to the release branch? Because this is not failing in master.

**Comment by tijoytom** [comment]
@trylek Tomas can you  please take look ?

**Comment by trylek** [comment]
@tijoytom Well, when I first heard about this issue on Tuesday, Anton said that it was just an integration problem - the ProjectNRel bits didn't end up propagating to the UWP6.0 branch. Anton expected that the bug would be fixed the next day, I'm not sure if the recent build breaks didn't affect the integration process. Where can I double-check if the problem still reproes?

**Comment by tijoytom** [comment]
@safern Can you please provide tomas with the link to latest failure ? It's definitely integration failure since @safern mentioned that it pass on master

**Comment by safern** [comment]
They are not failing anymore in rel branch. When they where reported as failing I suspect the release branch didn't have consumed the latest builds from ProjectNRel.

**Comment by trylek** [comment]
@safern Thanks a lot Santiago for your immediate action!

Tomas
