### ISSUE TITLE
System.Net.Http.FormUrlEncodedContent throws exception for large value

### ISSUE THREAD

**Issue by mirhagk** [dotnet/corefx#22369]
This bug is an existing bug in .NET 4.6.1, and .NET core contains the same bug.

The issue occurs when you attempt to use FormUrlEncodedContent class for a value that is very large (greater than `0xFFF0`). When using `FormUrlEncodedContent` for the post body this would be acceptable according to the [`application/x-www-form-urlencoded` spec](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1) and yet it throws a `UriFormatException` complaining about the length.

The faulty code path starts in [FormUrlEncodedContent.cs](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/FormUrlEncodedContent.cs#L47) `Encode` method where it calls out to `Uri.EscapeDataString`. Eventually [`UriHelper.EscapeString`](https://github.com/dotnet/corefx/blob/bfac45af5dddcbd70b6935fcf92b4b8755f3cd1c/src/System.Private.Uri/src/System/UriHelper.cs#L128) is called, which throws an exception if the length is too long.

I'm not sure whether the issue is with the UriHelper that throws if the length is too long or with the FormUrlEncodedContent class for assuming that the UriHelper is the correct method to encode the data. Either way the behaviour is incorrect according to the spec, and entirely undocumented and unexpected.

There have been [some questions about this](https://stackoverflow.com/questions/34178056/string-too-large-for-formurlencodedcontent-in-windows-phone-8-post-upload) that have resolved it by replacing FormUrlEncodedContent, but it causes a lot of confusion since people don't expect URL length exceptions from a long body.

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/1936?

**Comment by mirhagk** [comment]
Yes, I apologize.

Although it is concerning that the issue has been open for a while. I'll close this issue, and comment there. (If it's legitimately up for grabs I'll see if I can tackle it)

**Comment by mguinness** [comment]
For anyone else that encounters the following issue, the code below can be used as a workaround.

> FormUrlEncodedContent() uses EscapeDataString() which has an upper limit of 65520 characters.

```C#
var items = formData.Select(i => WebUtility.UrlEncode(i.Key) + "=" + WebUtility.UrlEncode(i.Value));
var content = new StringContent(String.Join("&", items), null, "application/x-www-form-urlencoded");
var response = await client.PostAsync(url, content);
```
