### ISSUE TITLE
Add Version Span-based APIs

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#22376]
Separated out of https://github.com/dotnet/corefx/issues/21281 for tracking purposes.

- [x] Implement in System.Private.CoreLib in coreclr (corert shares the same files)
- [ ] Expose from System.Runtime contract in corefx
- [ ] Add tests to System.Runtime tests in corefx

```C#
namespace System
{
    public class Version
    {
        public static Version Parse(ReadOnlySpan<char> input);
        public static bool TryParse(ReadOnlySpan<char> input, out Version result);
        public bool TryFormat(Span<char> destination, out int charsWritten, int fieldCount = 4);
        …
    }
}
```
---
EDIT 8/17/2017:
We'd approved:
```C#
public bool TryFormat(Span<char> destination, out int charsWritten, int fieldCount = 4);
```
as a way to avoid needing to add two TryFormat overloads based on whether it takes a fieldCount or not, but it turns out that deviates from the ToString()/ToString(fieldCount) behavior, where the former doesn't always use fieldCount == 4 but rather dynamically determines the value based on the instance, so we should add both:
```C#
public bool TryFormat(Span<char> destination, out int charsWritten);
public bool TryFormat(Span<char> destination, int fieldCount, out int charsWritten);
```

**Comment by kassemsandarusi** [comment]
It is likely I am incorrect, but this issue seems dependent on #22403. In order to Parse the version, you likely need:
```C#
namespace System
{
    public struct Int32 {
        public static bool TryParse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider provider, out Int32 result)
    }
}
```
