### ISSUE TITLE
Add TimeSpan Span-based APIs

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#22375]
Separated out of https://github.com/dotnet/corefx/issues/21281 for tracking purposes.

- [ ] Implement in System.Private.CoreLib in coreclr (corert shares the same files)
- [ ] Expose from System.Runtime contract in corefx
- [ ] Add tests to System.Runtime tests in corefx

```C#
namespace System
{
    public struct TimeSpan
    {
        public static TimeSpan Parse(ReadOnlySpan<char> input, IFormatProvider formatProvider = null);
        public static TimeSpan ParseExact (ReadOnlySpan<char> input, string format, IFormatProvider formatProvider, TimeSpanStyles styles = TimeSpanStyles.None);
        public static TimeSpan ParseExact (ReadOnlySpan<char> input, string[] formats, IFormatProvider formatProvider, TimeSpanStyles styles = TimeSpanStyles.None);

        public static bool TryParse(ReadOnlySpan<char> input, out TimeSpan result, IFormatProvider formatProvider = null);
        public static bool TryParseExact (ReadOnlySpan<char> input, string format, IFormatProvider formatProvider, out TimeSpan result, TimeSpanStyles styles = TimeSpanStyles.None);
        public static bool TryParseExact (ReadOnlySpan<char> input, string[] formats, IFormatProvider formatProvider, out TimeSpan result, TimeSpanStyles styles = TimeSpanStyles.None);

        public bool TryFormat(Span<char> destination, out int charsWritten, string format = null, IFormatProvider provider = null);
        …
    }
}
```

**Comment by WinCPP** [comment]
@stephentoub didn't realize that #22406 was not up-for-grabs. How about this one? Quite smaller than #22403. Also it will help me get started after a gap. Thanks!

**Comment by WinCPP** [comment]
Ok. Analyzed what this potentially involves. I believe it goes all the way down in to the tokenizer in the TimeSpanParser as well to replace ```string``` with ```Span<char>``` ... and then do related changes to support both ```Span<char>``` and existing ```string``` overloads at the interface? Am I on right track? Please let me know.

**Comment by stephentoub** [comment]
> Am I on right track? 

That's generally the right approach, but this one is tricky as, in its current design, that would result in a span getting stored as a field in another type, and as a ref-like type, spans can only be stored as fields in other ref-like types, and at the moment there's no way to indicate that in C#.  Even if the runtime doesn't currently complain, it will end up producing compilation errors later when the C# compiler verifies such things.

**Comment by WinCPP** [comment]
> ref-like type, spans can only be stored as fields in other ref-like types ..... no way to indicate that in C# ..... it will end up producing compilation errors later when the C# compiler verifies such things.

I guess you are referring to ```FormatLiterals```, a struct which will end up holding ```ReadOnlySpan```s...

**Comment by stephentoub** [comment]
There are several, like TimeSpanTokenizer.

**Comment by stephentoub** [comment]
We can't make those classes; that would result in allocations we need to avoid while parsing.  It may be that we need to wait to tackle this issue until we have an updated compiler that will appropriately validate ref structs.
cc: @VSadov

**Comment by WinCPP** [comment]
Yup got it. We may live with ```TimeSpanTokenizer``` being allocated on heap, say, for a moment. However ```TimeSpanToken``` is surely not a candidate for becoming a class; it stores a ```sep```, a `String`.

> It may be that we need to wait to tackle this issue...

So should I take up something else, that I have got hang of what is to be done in such set of problems?

**Comment by stephentoub** [comment]
> So should I take up something else

Probably.  How about the span-based TextReader/Writer methods, and the overrides on various types like StreamWriter?
https://github.com/dotnet/corefx/issues/22406
https://github.com/dotnet/corefx/issues/22409
etc.

You won't be able to do the buffer-based overloads yet, but you should be able to do the span-based ones.

**Comment by WinCPP** [comment]
Yup... was just typing 'may I' request in #22406 :-)
