### ISSUE TITLE
Add String Span-based method for writing into String's buffer

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#22380]
Separated out of https://github.com/dotnet/corefx/issues/21281 for tracking purposes.

- [x] Implement in System.Private.CoreLib in coreclr
- [x] Implement in System.Private.CoreLib in corert (if string isn't yet "shared" between coreclr and corert)
- [x] Expose from System.Runtime contract in corefx
- [x] Add tests to System.Runtime tests in corefx

```C#
namespace System
{
    public delegate void StringCreateAction<TState>(TState state, Span<char> destination);

    public class String
    {
        public static string Create<TState>(int length, TState state, StringCreateAction action);
        …
    }
}
```

Mostly approved, but open issue around the delegate, its name, what namespace it lives in (or nested type within String), etc.  A custom delegate is needed as span can't be used as a generic type argument with one of the built-in action types.

**Comment by karelz** [comment]
Approved in this shape:
```c#
namespace System
{
    public delegate void SpanAction<T, in TArg>(Span<T> span, TArg arg);

    public class String
    {
        public static string Create<TState>(int length, TState state, SpanAction<char, TState> action);
    }
}
```

Discussed points:
* We will use `System` namespace - it is where `Span` lives.
* `SpanAction` is better than `ActionOverSpan` (lexicographic ordering)
* Order of args and naming is similar to `Action`

**Comment by karelz** [comment]
Added `ReadOnlySpanAction` and moved to `System.Buffers` based on review of #21472

**Comment by ektrah** [comment]
Span\<T\> and ReadOnlySpan\<T\> cannot be used as a type argument, so the above Create\<TState\> method cannot be used with spans as input/state. I can imagine that that would be something common to do. Could another overload be added?

```csharp
public delegate void SpanSpanAction<TIn, TOut>(ReadOnlySpan<TIn> input, Span<TOut> output);

public class String
{
    public static string Create<TIn>(
        int length, ReadOnlySpan<TIn> state, SpanSpanAction<TIn, char> action);
}
```

**Comment by stephentoub** [comment]
> Could another overload be added?

I suggest we wait until there's a proven need for it.  While you may be right and it could end up being common, most of the cases I've seen historically are not based on taking in string-like data as input, but rather some other kind of data that's then used to produce characters.  Often these characters are stored into a heap-allocated char[], so this new overload avoids that allocation and then the copy from it into the string, or into a stack-allocated char*, in which case this new overload helps avoid the copy.

**Comment by justinvp** [comment]
Is there a planned use for `ReadOnlySpanAction` or scenario in mind where it'd be used? If not, should we hold-off on adding it until there's a proven need?

**Comment by stephentoub** [comment]
> Is there a planned use for ReadOnlySpanAction or scenario in mind where it'd be used? If not, should we hold-off on adding it until there's a proven need?

@KrzysztofCwalina, I believe you asked for this?  Or am I misremembering?

**Comment by stephentoub** [comment]
> Is there a planned use for ReadOnlySpanAction or scenario in mind where it'd be used?

I just remembered where:
https://github.com/dotnet/corefx/issues/21472
