### ISSUE TITLE
Add support for disabled short path generation to System.IO.Tests.Directory_GetFileSystemEntries_str.PatternTests_DosStarOddSpace()

### ISSUE THREAD

**Issue by makroeze** [dotnet/corefx#22384]
```PatternTests_DosStarOddSpace()``` currently tests for pattern-matching behavior on files that, according to inline documentation in the test source, is due to a preexisting bug in the Windows stack. However, the exhibited behavior is intended on systems that have short path alias generation enabled because the pattern is matched against both the full file name and the shortened alias generated by Windows. Consequentially, this test fails on systems that do not have short path alias generation enabled.

Expected behavior is as follows:

- If the system has short path alias generation enabled, then the current set of expected results should be used.
- If the system has short path alias generation disabled, then the set of results labeled as ```// Really should be:``` should be expected.

**Comment by JeremyKuhne** [comment]
Thanks for the details on this.

**Comment by JeremyKuhne** [comment]
Triage: Closing as this isn't a common scenario.
