### ISSUE TITLE
Add Stream Span/Buffer-based APIs

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#22381]
Separated out of https://github.com/dotnet/corefx/issues/21281 for tracking purposes.

- [x] Implement span-based APIs in System.Private.CoreLib in coreclr
- [x] Implement buffer-based APIs in System.Private.CoreLib in coreclr
- [x] Implement span-based APIs in System.Private.CoreLib in corert (if Stream isn't yet in "shared")
- [x] Implement buffer-based APIs in System.Private.CoreLib in corert (if Stream isn't yet in "shared")
- [x] Expose span-based APIs from System.Runtime contract in corefx
- [ ] Expose buffer-based APIs from System.Runtime contract in corefx
- [x] Add span-based APIs tests to System.Runtime tests in corefx
- [ ] Add buffer-based APIs tests to System.Runtime tests in corefx

```C#
namespace System.IO
{
    public class Stream
    {
        public virtual int Read(Span<byte> destination);
        public virtual ValueTask<int> ReadAsync(Buffer<byte> destination, CancellationToken cancellationToken = default(CancellationToken));

        public virtual void Write(ReadOnlySpan<byte> source);
        public virtual Task WriteAsync(ReadOnlyBuffer<byte> source, CancellationToken cancellationToken = default(CancellationToken));
        …
    }
}
```

**Comment by sharwell** [comment]
:bulb: Can start writing `= default` for the default value, assuming you don't want to go the actual right way and make it required. 😉

**Comment by jnm2** [comment]
++ for the actual right way 😄

**Comment by KubaO** [comment]
I think that the use of `byte[]` as a stand-in for "a buffer of bytes" was just a broken API to begin with; with spans and buffers there's no reason to even use the array-based API. I wish it were deprecated already...
