### ISSUE TITLE
Override new Span/Buffer-based APIs on CryptoStream

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#22391]
Dependent on #22381.

**Comment by morganbr** [comment]
This would also need to be plumbed through the encryption and hash algorithms to get any of the benefits of Span (CryptoStream doesn't really do anything on its own, it just calls into ICryptoTransform).

CC @bartonjs

**Comment by bartonjs** [comment]
@morganbr Yeah, ICryptoTransform is still on the to-review log.  After 5 hours of API reviews we've made it through System.IO while reviewing the full surface of corefx :smile:.

\*Stream has a Span-shape now, so the API is approved; the implementation details for CryptoStream will end up being dependent on ICryptoTransform.

**Comment by stephentoub** [comment]
The verdict on ICryptoTransform was to not do anything now and wait for (hopefully) default interface implementations in the future.
https://github.com/dotnet/coreclr/issues/10504

Until such time, there's little value in overriding the span-based Read/Write methods, as the common usage will result in our needing to convert the input spans to arrays, anyway, and we could end up actually doing worse than the base implementations would.

For the buffer-based ones, we have a similar issue.  We could extract the byte[] from the buffer if it wraps one and then plumb that through, but the base implementation already does that.

As such, we'll leave these not overridden for the foreseeable future.
