### ISSUE TITLE
Add BigInteger Span-based APIs

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#22401]
Separated out of https://github.com/dotnet/corefx/issues/21281 for tracking purposes.

- [ ] Implement in System.Runtime.Numerics
- [ ] Expose from System.Runtime.Numerics ref
- [ ] Test in System.Runtime.Numerics.Tests

```C#
namespace System.Numerics
{
    public struct BigInteger
    {
        public BigInteger(ReadOnlySpan<byte> value);

        public int GetByteCount();
        public bool TryWriteBytes(Span<byte> destination, out int bytesWritten);

        public static BigInteger Parse(ReadOnlySpan<char> value, NumberStyles style = NumberStyles.Integer, IFormatProvider provider = null);
        public static bool TryParse(ReadOnlySpan<char> value, out BigInteger result, NumberStyles style = NumberStyles.Integer, IFormatProvider provider = null);
        …
    }
}
```

**Comment by bazzilic** [comment]
When do you think this will reach the big .NET Framework?

**Comment by jnm2** [comment]
The question on everyone's minds... (at least until [.NET Core 3](https://blogs.msdn.microsoft.com/dotnet/2018/05/07/net-core-3-and-support-for-windows-desktop-applications/) comes out!)
