### ISSUE TITLE
Override new Span/Buffer-based APIs on StreamReader

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#22408]
Depends on https://github.com/dotnet/corefx/issues/22406.

**Comment by WinCPP** [comment]
@stephentoub I'm working on this along with #22406 ...

**Comment by WinCPP** [comment]
@stephentoub I implemented the following two span-based ```Read``` calls for ```TextReader``` which delegate to the ```Read(char [], index, count) API.

```C#
        public virtual int Read(Span<char> destination);
        public virtual int ReadBlock(Span<char> destination);
```
Given that, do we still need to override them in ```StreamReader``` instead of using base implementation which delegates to the ```Read(char [], index, count)``` of the base or of ```StreamReader``` as the case may be...?

**Comment by stephentoub** [comment]
> do we still need to override them in StreamReader

Yes, please see my comments in your PR.

**Comment by WinCPP** [comment]
Hi @stephentoub, as with #22409, I am not sure, but going through the code it looks like I will have to create `Slices` and new `Spans` interspersed in the code for working with the `Read` and in the `ReadBuffer` overload. I think this is a bit more involved that I initially thought and I suspect it requires additional APIs which directly work by copying from source to destination span without creating slices or new spans. Would you mind taking over this issue. I will move to something less involved and simpler given that I may soon run short on time and this is getting delayed.

Thanks!
