### ISSUE TITLE
Add BinaryWriter Span-based APIs

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#22429]
Separated out of https://github.com/dotnet/corefx/issues/21281 for tracking purposes.

- [ ] Implement in System.Private.CoreLib in coreclr
- [ ] Implement in System.Private.CoreLib in corert (if BinaryWriter isn't yet in "shared")
- [ ] Expose from System.IO contract in corefx
- [ ] Add tests to System.IO tests in corefx

```C#
namespace System.IO
{
    public class BinaryWriter
    {
        public virtual void Write(ReadOnlySpan<byte> value);
        public virtual void Write(ReadOnlySpan<char> value);
        …
    }
}
```

**Comment by pjanotti** [comment]
@stephentoub I'm closing this per PRs below

https://github.com/dotnet/coreclr/pull/13378 (also in corert)
https://github.com/dotnet/corefx/pull/23253 (tests and ref in corefx)

**Comment by gusarov** [comment]
any estimates when this will be available in Net Standard?
