### ISSUE TITLE
System.ComponentModel.ComponentResourceManager.ApplyResources separator conflicts in uwp

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#22444]
Since UWP apps merge their resources into a pri file given the '.' separator for [ApplyResources](https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.TypeConverter/src/System/ComponentModel/ComponentResourceManager.cs#L70-L200) our costumers could potentially hit a MakePri failure when compiling their application. 

The reason why costumers could hit this is if they add into their Application's resources or consume a library that their resources have key/values like the example below:

```xml
<data name="Object" xml:space="preserve">
    <value>Object</value>
  </data>
<data name="Object.GetSetProperty" xml:space="preserve">
    <value>ObjectGetSetProperty</value>
  </data>
  <data name="Object.NoSuchProperty" xml:space="preserve">
    <value>ObjectNoSuchProperty</value>
  </data>
```

Where a resource is the Prefix of the full property name (Class.PropertyName). If we have this resources structure inside a UWP app when building it will fail with an error similar to this one: 

```
error PRI175 : 0x80073b0f - Processing Resources failed with error : Duplicate Entry. 
error PRI278: 0xdef00531 - 'Resources.TestResx/Object' or one if its parents is defined as both resource and scope, which is not allowed.
```

We will need to provide an additional separator to our customers to have a valid workaround here rather than changing the "Default" resource (I suggest '-').

With this separator our customers will be able to have resources in the following structure: 

```xml
<data name="Default" xml:space="preserve">
    <value>Default</value>
  </data>
  <data name="Default-GetSetProperty" xml:space="preserve">
    <value>DefaultGetSetProperty</value>
  </data>
  <data name="Default-NoSuchProperty" xml:space="preserve">
    <value>DefaultNoSuchProperty</value>
  </data>
  <data name="Default-GetOnlyProperty" xml:space="preserve">
    <value>DefaultGetOnlyProperty</value>
  </data>
  <data name="Default-PrivateProperty" xml:space="preserve">
    <value>DefaultPrivateProperty</value>
  </data>
```

cc: @weshaggard @tarekgh

**Comment by tarekgh** [comment]
Thanks @safern for logging the issue

**Comment by danmosemsft** [comment]
Usage of https://apisof.net/catalog/System.ComponentModel.ComponentResourceManager is quite small. I think at this point this can move out.

**Comment by safern** [comment]
> Usage of https://apisof.net/catalog/System.ComponentModel.ComponentResourceManager is quite small. I think at this point this can move out.

@danmosemsft, already fixing this here: #22418

**Comment by tarekgh** [comment]
> Usage of https://apisof.net/catalog/System.ComponentModel.ComponentResourceManager is quite small. I think at this point this can move out.

Are you suggesting to not expose this class? I don't think we can change this for net core 2.0 at this moment

**Comment by danmosemsft** [comment]
@tarekgh no I meant I am not tracking it as debt for 6.0
