### ISSUE TITLE
HttpClient not thread Safe

### ISSUE THREAD

**Issue by Bhaal22** [dotnet/corefx#2246]
Hi,

Recently I noticed HttpClient, FtpClient (maybe SMTPClient I have to check) are not thread safe when Scheme is set https.
Since all those classes relies on static member SecurityProtocol in ServicePointManager.

We cant have multiple tasks or threads targeting different SSL or TLS version at the same time.

I didn't see ServicePointManager in corefx repository located in System.Net namespace.

Are there plans to open this piece of code ?

**Comment by davidsh** [comment]
ServicePointManager is only in .NET Desktop.  It will not be present in CoreFx.  The HTTP stack has been redone and the ServicePointManager classes are not used.  The architecture is different. 

In particular, the feature of the 'SecurityProtoocol' property of ServicePointManager is available when using the WinHttpHandler directly within HttpClient:  See the WinHttpHandler.SslProtocols property.

https://github.com/dotnet/corefx/tree/master/src/System.Net.Http.WinHttpHandler

FtpClient and SmtpClient are also only .NET Desktop classes.  Those are currently not in CoreFx contracts.  There is an open issue about SmtpClient #1006 and we are looking into that as we work with the community on requirements.

I'm not sure I fully understand your comment about thread safety.  Do you have any specific code examples where you observe in CoreFx that there are concurrent thread issues?

/cc @CIPop @SidharthNabar

**Comment by Bhaal22** [comment]
My bad, I was speaking about classic .net Framework.
I will try to move my current code to corefx implementation where I target mutliple Http endpoints in multiple Threads.
I noticed thread safe issues and issues with connection pool.

What about if we have multiple calls in parallel targeting SSL3 endpoints and TLS1.0 or TLS1.1 / TLS1.2 endpoints. I'll do some tests. 

I'll keep you posted if I find out similar issues.
