### ISSUE TITLE
Integrated authentication failing when attempting to connect to SQL Server from macOS Sierra

### ISSUE THREAD

**Issue by carlowahlstedt** [dotnet/corefx#22463]
This issue is originally discussed [here](https://github.com/Microsoft/vscode-mssql/issues/356#issuecomment-316166467).

Following the [Kerberos Setup Instructions](https://github.com/Microsoft/vscode-mssql/blob/380cfb4e8acce9d9d8368d2a5f32cfff9c73a933/KERBEROS_HELP.md). Steps 1 through 3 work perfectly. However, when attempting step 4 I get the following:
```
mssql: Failed to connect: Cannot access Kerberos ticket. Ensure Kerberos has been initialized with 'kinit'.

[3:36:58 PM] Error connecting to server "[ServerName]". Details: Cannot access Kerberos ticket. Ensure Kerberos has been initialized with 'kinit'.
ErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error -  An unsupported mechanism was requested (unknown mech-code 0 for mech unknown).
   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)
   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)
   at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)
   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)
   at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
```

Per @kevcunnane request, I'm submitting an issue here.

The only other thing I've noticed since the other issue, is that if I run the `klist` command without first running the `kinit` command I have several other entries:

```
Credentials cache: API:ED70540F-329F-44FB-9C08-059260828BBB
        Principal: me@DOMAIN.COMPANY.COM

  Issued                Expires               Principal
Jul 19 22:31:24 2017  Jul 20 08:31:24 2017  krbtgt/DOMIAN.COMPANY.COM@DOMIAN.COMPANY.COM
Jul 19 22:31:41 2017  Jul 20 08:31:24 2017  host/COMPANYSERVER.DOMIAN.COMPANY.COM@DOMIAN.COMPANY.COM
Jul 19 22:31:41 2017  Jul 20 08:31:24 2017  HTTP/COMPANYSERVER.DOMIAN.COMPANY.COM@DOMIAN.COMPANY.COM
```

We do use the [Jamf Casper Suite](https://www.jamf.com/products/jamf-pro/) to manage our Macs, and I'm assuming that's what those other entries are from.

Finally, I also setup a .Net Core Console app to see if integrated security would run from there, following along the same lines as [this issue](https://github.com/dotnet/corefx/issues/22453) and I received the same exception as the one the VS Code is giving me with the mssql extension.

> macOS 10.12.5
> dotnet 2.0.0-preview2-006497

**Comment by carlowahlstedt** [comment]
For clarity, updated to dotnet 2.0.0 and still seeing the issue.

**Comment by Code-DJ** [comment]
This has not been assigned any milestone. Can we get an idea on the timeline? Thanks.

**Comment by geleems** [comment]
@carlowahlstedt 
Could you confirm that you use Fully Qualified Domain Name for SQL Server SPN?
The error is throw from this code part (line# 139) :
https://github.com/dotnet/corefx/blob/dcc29528c9c4633e81b1937e7dd9fde7115a938c/src/Common/src/System/Net/Security/NegotiateStreamPal.Unix.cs#L122-L144

**Comment by geleems** [comment]
Do you have the following two lines in your `~/.ssh/config` file, or in your `/etc/ssh_config`? :
```
GSSAPIAuthentication yes
GSSAPITrustDNS yes
```
The first is required to enable GSSAPI (Kerberos) authentication, the second one is required to get ssh to canonicalize the hostname via DNS and use the canonical name to obtain a host service ticket. Without the second one, ssh will use the exact hostname or IP address entered on the command line to try and obtain a host service ticket, and in this case it fails.

**Comment by carlowahlstedt** [comment]
@geleems I created the config file in `~/.ssh/config` and added these two settings. 
```
GSSAPIAuthentication yes
GSSAPITrustDNS yes
```
I then restarted but realized I should have first gone back through the [original setup document](https://github.com/Microsoft/vscode-mssql/blob/master/KERBEROS_HELP.md). After I did that, it connected! So, looks like that document needs updated with your suggesting of adding these two lines into an ssh config file.

Would that be something that makes sense for everyone to make sure they have setup? Seems confusing to me why it would work for many others but not me?

Thanks so much for your help @geleems!!

**Comment by Code-DJ** [comment]
@geleems This did not work for me. Note: My mac is domain joined. I login as the domain user to the mac.

Created ~/.ssh/config file (was missing):
GSSAPIAuthentication yes
GSSAPITrustDNS yes

Created /etc/krb5.conf file (was missing):
[libdefaults]
    default_realm = DOMAIN.COM

[realms]
DOMAIN.COM = {
    kdc = adservername.domain.com
}

Ran:
kinit myuser@domain.com
entered my domain password.

In VSCode tried connecting to a SQL Server on the domain. Still get the same error.
Rebooted my computer and tried again in VSCode. Still get the same error.

**Comment by carlowahlstedt** [comment]
@Code-DJ What version of macOS are you running? The [release notes for v1.1 of the mssql extension](https://github.com/Microsoft/vscode-mssql/blob/master/README.md) states:
> macOS "El Capitan" and older versions will not support this feature

**Comment by Code-DJ** [comment]
@carlowahlstedt macOS Sierra.

**Comment by carlowahlstedt** [comment]
I also think I had to update OpenSSL for some other tool I used. Not sure if that's applicable here. I believe I used Homebrew to do the update. You could potentially try that.

**Comment by Code-DJ** [comment]
@carlowahlstedt I had 1.0.2k 1.0.2l and it shows that it is the latest version. Thanks.

**Comment by geleems** [comment]
@carlowahlstedt
Thanks for the confirmation, and I am so glad yours is now working.
We realized some customers are experiencing Kerberos issue as you did, and currently work hard to find what configurations are missing in the instruction such as GSSAPIAuthentication and GSSAPITrustDNS.
I will definitely update the instruction for macOS by adding the missing config.

**Comment by carlowahlstedt** [comment]
Thanks @geleems we can close this issue whenever you're satisfied. Thanks again for the help.

**Comment by geleems** [comment]
@Code-DJ  Can you check those settings in your machine?
***
/etc/pam.d/authorization : 
```
# authorization: auth account
auth       optional       pam_krb5.so use_first_pass use_kcminit default_principal
auth       sufficient     pam_krb5.so use_first_pass default_principal
...
```
***
/etc/pam.d/screensaver : 
```
# screensaver: auth account
auth optional pam_krb5.so use_first_pass use_kcminit default_principal
...
```
***
/etc/pam.d/sudo
```
# sudo: auth account password session
auth sufficient pam_krb5.so try_first_pass default_principal
...
```

**Comment by Code-DJ** [comment]
@geleems here are the values:

# authorization: auth account
auth       optional       pam_krb5.so use_first_pass use_kcminit
auth       optional       pam_ntlm.so use_first_pass
auth       required       pam_opendirectory.so use_first_pass nullok
account    required       pam_opendirectory.so

❯ cat /etc/pam.d/screensaver
# screensaver: auth account
auth       optional       pam_krb5.so use_first_pass use_kcminit
auth       required       pam_opendirectory.so use_first_pass nullok
account    required       pam_opendirectory.so
account    sufficient     pam_self.so
account    required       pam_group.so no_warn group=admin,wheel fail_safe
account    required       pam_group.so no_warn deny group=admin,wheel ruser fail_safe


❯ cat /etc/pam.d/sudo
# sudo: auth account password session
auth       sufficient     pam_smartcard.so
auth       required       pam_opendirectory.so
account    required       pam_permit.so
password   required       pam_deny.so
session    required       pam_permit.so


❯ cat ~/.ssh/config
GSSAPIAuthentication yes
GSSAPITrustDNS yes
GSSAPIDelegateCredentials yes

I didn't have the last line in .ssh/config. Didn't work even after adding it.

**Comment by geleems** [comment]
@Code-DJ
Thanks for confirming that.
Are you able to ssh and login to your macOS machine with Kerberos?

**Comment by geleems** [comment]
@Code-DJ 
Thanks for the information. Since the issue of the author was resolve, I am closing this ticket. Your issue is more closer to https://github.com/Microsoft/vscode-mssql/issues/985, so please refer this thread.
