### ISSUE TITLE
System.IO.Compression.ZipFile contents not available on Android platforms

### ISSUE THREAD

**Issue by Shtong** [dotnet/corefx#22468]
Hello,

After installing the official NuGet package `System.IO.Compression.ZipFile`, version 4.3.0, on a Xamarin Android project, the `System.IO.Compression.ZipFile` assembly is not made available, even though the `System.IO.Compression` is there. 

The Nuget package actually only contains the library for the `net46` and `netstandard1.3` frameworks. The other 'supported' frameworks (all mobile specific) does not contain the library. So even if I've made sure that my android project is NetStandard compatible, I'll get the empty `MonoAndroid10` libraries.

**Comment by danmosemsft** [comment]
@weshaggard thoughts?

**Comment by mellinoe** [comment]
If there is an empty folder for `MonoAndroid10`, that usually means that the assembly is supposed to be shipped with MonoAndroid itself, which means you wouldn't need anything from the package. What version of MonoAndroid are you using?

**Comment by Shtong** [comment]
I'm using MonoAndroid 7.1. After reading your message I quickly found out that the assembly is indeed shipped with MonoAndroid, but it is named `System.IO.Compression.FileSystem`. After adding it I was able to access the `ZipFile`class.

**Comment by mellinoe** [comment]
@Shtong Great! Let us know if you have any other questions.
