### ISSUE TITLE
Unaccounted forced unoptimized build of System.Security.Cryptography.X509Certificates tests

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/corefx#22475]
The tests are forced to run unoptimized with ILC but there's no issue I can find tracking an underlying codegen issue: https://github.com/dotnet/corefx/pull/22173#issuecomment-316449128.

These either shouldn't be forced to run unoptimized, or there should be a UWP6.0 bug that codegen people are looking at.

**Comment by hoyMS** [comment]
The fix has been checked into TFS as 1667844

**Comment by MichalStrehovsky** [comment]
We'll need to remove the line that forces the test to run without optimizations.

**Comment by danmosemsft** [comment]
@safern can you remove the no-optimizations line when we get a new project N ?

**Comment by safern** [comment]
Yes, I will.

**Comment by safern** [comment]
@hoyMS was the fix ported to release branch? If I build this tests in ret mode in the release branch they fail. Could you please port it?

**Comment by hoyMS** [comment]
No, it is still in ProjectN branch now. I'm going to port it to the release branch today. Will let you know once it's done.

**Comment by safern** [comment]
Thanks.

**Comment by hoyMS** [comment]
@safern The fix has been ported to ProjectNRel.

**Comment by safern** [comment]
> @safern The fix has been ported to ProjectNRel.

Thanks @hoyMS tomorrow once we consume them I will make sure that this is ported in the coreFX side.
