### ISSUE TITLE
NullReferenceException from System.Uri

### ISSUE THREAD

**Issue by jodavis** [dotnet/corefx#22479]
Sometimes `Uri.TryCreate` returns an invalid Uri when given a file path with a trailing slash. The `MinimalUriInfoSet` flag is set, but `m_Info` is null, so most of the methods and properties of the Uri throw `NullReferenceException`. The behavior is not deterministic; for the same input I sometimes get a working Uri.

I can reproduce this (sometimes) with the following code in a unit test:

```
Uri result;
string input = @"C:\users\jodavis\Documents\Visual Studio 2017\WebApplication1\WebApplication1\";

Uri.TryCreate(input, UriKind.Absolute, out result);

Assert.AreEqual("file://", result.GetComponents(UriComponents.SchemeAndServer, UriFormat.SafeUnescaped));
```

It doesn't reproduce every time. It seems to happen more frequently when built for Release. It also seems more frequent if I step into the `Uri.TryCreate` method; but if I step in any deeper than that, then it never reproduces.

**Comment by danmosemsft** [comment]
Surprises me it's not consistent. I didn't know that the URI class had any non determinism.

**Comment by rmkerr** [comment]
This looks really interesting, especially since it appears to be non-deterministic. My initial attempts to repro have been unsuccessful, but I'll continue looking in to it. @jodavis do you have any more details on when this issue occurs? And approximately how often are you running into this issue?

**Comment by stephentoub** [comment]
> I didn't know that the URI class had any non determinism.

Uri uses a lot of unsafe code.  If there is a problem here, my guess would be that there's a bug in that unsafe code, walking off the end of some memory somewhere, such that it's non-deterministic because it's based on what data exists in the arbitrary memory being looked at.  Just a guess.

**Comment by jodavis** [comment]
I don't have any more detail since I posted. I was hitting it a lot while I was debugging some particular code that used Uri.TryCreate, but I haven't seen it in production.

**Comment by rmkerr** [comment]
What version of .NET Core you were running on at the time? I've tried to track down any instances of memory corruption caused by this issue, and have yet to find anything.

**Comment by rmkerr** [comment]
Without a repro or more info I don't think this issue is actionable. I've tested the code pretty thoroughly running normally and under appverifier to check for memory corruption and haven't seen anything. @jodavis if you're able to consistently reproduce the issue again don't hesitate to reopen this!

**Comment by SEnglishSMP** [comment]
For what it's worth, I've run into this exact problem myself, but on .NET Framework (not Core).  I've had to add work-around code or even just abandon using the Uri class in favor of plain strings (where possible).  Like @jodavis, it's intermittent.  Sometimes it only occurs while debugging, other times we've hit it in a production app.
