### ISSUE TITLE
HttpClient forcing spaces into Accept headers with parameters breaking non-conforming REST APIs.

### ISSUE THREAD

**Issue by thomas-frantz** [dotnet/corefx#22472]
Alright, so an API we are having to use (which, of course, we have no control over) appears to be strictly looking for an `Accept` header formatted as `application/json;masked=false`. However, `HttpClient` is breaking this apart and forcing a space between the `;` and masked, causing their API to treat it as `application/json` (which I'm pretty sure is just their default.) I've reproduced this in postman to ensure this was the issue. We have already contacted them, but I don't have much hopes of them fixing it on their end.

So, this leaves me kind of stuck. While the RFC says the space in this is valid, I have no way to make this header take effect because of the space. Is there no way to override this behavior? Or is there an alternative that exists in .net core currently?

Thanks

**Comment by svick** [comment]
I think this a duplicate of https://github.com/dotnet/corefx/issues/18449, which also has a workaround that involves private reflection.

**Comment by thomas-frantz** [comment]
@svick It is, I just found that one too. Thanks.

Sorry about that.
