### ISSUE TITLE
./build-native.sh fails to build after adding openssl function if run from root

### ISSUE THREAD

**Issue by Drawaes** [dotnet/corefx#22485]
On a clean Ubuntu 14.04 LTS machine with only the prereq's for .netcore and with the entire thing building first.....

If I add a function to the opensslshim.h such as

PER_FUNCTION_BLOCK(CRYPTO_set_ex_data, true) \

with adding the pointer as well

#define CRYPTO_set_data_ex CRYPTO_set_data_ex_ptr

and then run ./build-native.sh from the "corefx" root folder I get the following output

https://gist.github.com/Drawaes/7b2011e7b9eda9c6adea4e4fdac0c9b4

However if I run it from 

/corefx/src/Native

folder it works fine... ?

**Comment by mellinoe** [comment]
Hm. Something wrong with how we are using / invoking CMake from different folders, perhaps?

**Comment by Drawaes** [comment]
Very possibly, seeing as I am basically at the level of having two commands in VIM :P it is all a bit beyond me, but I can def repeat it and it's a clean Ubuntu VM on hyper V so should be repeatable.

**Comment by Drawaes** [comment]
Found the issue... missing a FUNCTIONBLOCK (XXXXXX, **true**) at the end of my lines. Still odd with the different behaviour but closing the issue
