### ISSUE TITLE
System.Data.SqlClient doesn't work with System.Transactions.Transaction

### ISSUE THREAD

**Issue by DRAirey1** [dotnet/corefx#22484]
I understand that there's no support for ambient transactions, but even explicit transactions don't seem to work.  I have a middle tier which I'm porting to .NET Core.  I simply want to make sure that the in-memory update is committed with the SQL update as an atomic operation.  I had been using ambient transactions, but decided to move to explicit after reading that ambient wasn't supported.  So I have:

    this.committableTransaction = new CommittableTransaction();
    this.committableTransaction.EnlistVolatile(VolatileTransaction.Current, EnlistmentOptions.None);
    this.sqlConnection = new SqlConnection("...");
    sqlConnection.Open();
    sqlConnection.EnlistTransaction(this.committableTransaction);

**VolatileTransaction.Current** is my own implementation of the **IEnlistmentNotification** interface.  When I run this, I get: _System.NotSupportedException: 'Enlisting in Ambient transactions is not supported.'_

If there's a different way to support a two-phase commit then I'll use it, just let me know how I'm supposed to do this basic operation.

**Comment by corivera** [comment]
SqlClient transaction support was only added recently in https://github.com/dotnet/corefx/commit/6de0d9478326f4e76016a59193b646508540e75a

It will be included in the 2.1.0 release.

@geleems Do you have anything else to add here regarding two-phase commits?

**Comment by DRAirey1** [comment]
Like I said, my middle tier requires that I commit an in-memory operation and a database operation as an atomic unit.  Should I abandon my attempt to move to .net core until Q4 2017?

**Comment by corivera** [comment]
We have preview packages available, if you'd like to try using those.

SqlClient Package: https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Data.SqlClient
Myget feed: http://dotnet.myget.org/F/dotnet-core/api/v3/index.json

**Comment by DRAirey1** [comment]
Install-Package System.Data.SqlClient -Version 4.5.0-preview2-25520-92 -Source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json 
Restoring packages for C:\Source\Main\Trading Post\Web Application\WebApplication\WebApplication.csproj...
  GET https://api.nuget.org/v3-flatcontainer/system.data.sqlclient/index.json
  OK https://api.nuget.org/v3-flatcontainer/system.data.sqlclient/index.json 177ms
Install-Package : Package restore failed. Rolling back package changes for 'WebApplication'.
At line:1 char:1
+ Install-Package System.Data.SqlClient -Version 4.5.0-preview2-25520-9 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by geleems** [comment]
@DRAirey1 Can you provide a short sample code to test your scenario with your newly added transaction support? I guess it would work with our latest support, and I would like to try it.

**Comment by DRAirey1** [comment]
It took me most of last evening, but after clearing the Gnuget cache, I was able to load the 4.5.0 preview.  However, that didn't change the result.

```
        public ProductsController(DataModel dataModel)
        {
            this.committableTransaction = new CommittableTransaction();
            this.committableTransaction.EnlistVolatile(VolatileTransaction.Current, EnlistmentOptions.None);
            this.sqlConnection = new SqlConnection("...");
            sqlConnection.Open();
            sqlConnection.EnlistTransaction(this.committableTransaction);
        }

```
System.NotSupportedException: 'Enlisting in Ambient transactions is not supported.' when the **EnlistTransaction** is called.

**Comment by DRAirey1** [comment]
I can't even get a simple program to run.  I've got a clean copy of Visual Studio 2017 Preview (2), got a brand new .NET Core console application.  I plug the code in above into the 'Main' method and when I run it I get:

```
System.TypeInitializationException occurred
  HResult=0x80131534
  Message=The type initializer for 'System.Data.SqlClient.SqlConnection' threw an exception.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at System.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at SqlTest.Program.Run() in c:\users\donaldairey\source\repos\ConsoleApp2\ConsoleApp2\Program.cs:line 26
   at SqlTest.Program.Main(String[] args) in c:\users\donaldairey\source\repos\ConsoleApp2\ConsoleApp2\Program.cs:line 19

Inner Exception 1:
FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

```
When it tries to execute the 'new SqlConnection' line.

**Comment by geleems** [comment]
@DRAirey1 I just tried with ff11ac65876e8ea8ed16a6b51ded48e19d6283ba. And no error occurred.

With test code:
```
public static void TestMain()
{
	Console.WriteLine("Test started.");

	string connString = "Server=tcp:.;User ID=testuser;Password=test1234";
	SqlConnectionStringBuilder builder = new SqlConnectionStringBuilder(connString);
	string connectionString = builder.ConnectionString;

	CommittableTransaction ct = new CommittableTransaction();
	MyEnlistmentClass myEnlistment = new MyEnlistmentClass();
	ct.EnlistVolatile(myEnlistment, EnlistmentOptions.None);
	SqlConnection connection = new SqlConnection(connectionString);
	connection.Open();
	connection.EnlistTransaction(ct);
	
	Console.WriteLine("successful");
}
```

Console output:
```
Discovering: System.Data.SqlClient.Tests
Discovered:  System.Data.SqlClient.Tests
Starting:    System.Data.SqlClient.Tests
Test started.
successful
Finished:    System.Data.SqlClient.Tests
```

**Comment by geleems** [comment]
@DRAirey1 
As @corivera mentioned, the transaction support was recently added to .NET Core, and official build is not released. The error you got with clean official .NET Core is surely expected since current official release build does not have transaction support.
