### ISSUE TITLE
DbDataReader.Close() doesn't unify with System.Data.Common

### ISSUE THREAD

**Issue by bricelam** [dotnet/corefx#2249]
If I write a provider against System.Data.Common on .NET Standard 1.2 and implement `Dispose` appropriately, then I try to use that provider on .NET Framework 4.6 or .NET Core 2.0, the following code won't work.

``` C#
reader.Close(); // No-op
Assert.True(reader.IsClosed); // Fails since Dispose is never called
```

It fails because on .NET Framework and .NET Core 2.0, `Dispose` calls `Close` (not the other way around) and since there is no virtual `Close` method on .NET Standard 1.2, I cannot override it without cross-targeting the frameworks that do have it.

**Comment by YoungGah** [comment]
@bricelam: It is not ideal that Dispose calls Close but unfortunately that is how Dispose is implemented on NET Framework. As for Close being removed from DbDataReader, we carefully reviewed all Close methods under System.Data.Common as Close is a synonym for Dispose. We concluded that Close on DbDataReader is redundant and does not provide any additional value unlike Close method on DbConnection. Close method on DbConnection is appropriate as DBConnection has Open method.

This issue is not ideal, but given that the recommendation is for users to call Dispose method by "using" statement with DbDataReader, we won't be fixing this issue.

**Comment by bricelam** [comment]
I'm re-opening this because it is a real issue for provider writers that prevents them from creating a provider that *just* targets .NET Standard 1.2 (without cross-targeting .NET Framework 4.5.1).

IMHO, the solution here is to add `Close()` back to `DbDataReader` in .NET Standard 1.2 (as we're doing in .NET Standard 2.0)

**Comment by bricelam** [comment]
Maybe even put `[EditorBrowsable(EditorBrowsableState.Never)]` on it so users won't call it, but provider writers can provide a correct implementation.

**Comment by bricelam** [comment]
This issue now appears on `netstandard2.0` and `netcoreapp2.0` in addition to `net451`. Because `DbDataReader.Close()` has been added back, you can write the code above, but if a `netstandard1.2` provider hasn't worked around it by corss-targeting `net451` and `netstandard2.0`, calling `Close()` is a no-op.

**Comment by krwq** [comment]
I have looked at SqlDataReader, DataTableReader and OdbcDataReader and they all have `Close()` implemented and Dispose is calling into `Close()`

For DbDataReader there is not logic in `Close()` on Desktop which I believe is expected since this is abstract class.

Can this be closed or am I missing something?

**Comment by bricelam** [comment]
This is an issue in the .NET Standard 1.2 System.Data.Common contract that has since been fixed in 2.0. This issue is tracking whether we should backport the fix (add a virtual `Close` method to `DbDataReader`) into the .NET Standard 1.2 System.Data.Common contract. @divega, @terrajobst, @ericstj, et al. are currently investigating whether this is feasible.

**Comment by bricelam** [comment]
(I've updated the main description to better articulate the issue.)

**Comment by krwq** [comment]
I've assigned them to this task since they are working on it

**Comment by ericstj** [comment]
I would imagine that is possible if you rebuild the ns1.2 ref and ensure that all implementations have the Close method (including those where it is inbox like xamarin).  It doesn't appear to be inbox anywhere else (Desktop, .NET Core, UAP) so it seems feasible.

This is actually the first I've heard of this, but I think the right course of action would be for the folks who own Data.Common to propose a solution, test that on all frameworks, then take the change to FxDC if it involves any API changes.

**Comment by ViktorHofer** [comment]
@bricelam @karelz This is neither a netcoreapp nor a 2.0 issue. I suggest moving it to netstandard.

**Comment by weshaggard** [comment]
@ViktorHofer this isn't something that would be fixed in the standard repo. If we were to take a fix for this, which I'm not convinced we should, then it would need to happen in the corefx repo.

**Comment by ViktorHofer** [comment]
I see, thanks for enlighten me

**Comment by ViktorHofer** [comment]
As of tomorrows ZBB, we need to make the decision of either ignoring the issue for 2.0 or fixing it.
@danmosemsft @weshaggard @karelz

**Comment by karelz** [comment]
@saurabh500 @corivera @ericstj can you please chime in?

**Comment by corivera** [comment]
We've already added the Close() API in 2.0.0, so this just seems like a 1.2 servicing issue.

**Comment by karelz** [comment]
Which servicing branch does it live in? 1.0.x or 1.1.x - can you please set the milestone to match that?

**Comment by corivera** [comment]
According to @weshaggard we would have to make changes in 1.1.0

**Comment by corivera** [comment]
Actually, looks like DbDataReader.Close() is already present in 1.1.0: https://github.com/dotnet/corefx/commit/27240e90597d477c213b0af81142e6b53b6ea315#diff-7ce02b6f11b3db97a63d932124bd3cdaR288

**Comment by corivera** [comment]
Actually, looks like DbDataReader.Close() was already added to 1.1.0 in this commit: https://github.com/dotnet/corefx/commit/27240e90597d477c213b0af81142e6b53b6ea315

**Comment by karelz** [comment]
Can you please work with @ericstj @weshaggard to make sure we have the right bits in the right place. If it was there, this report wouldn't exist I assume ...

**Comment by divega** [comment]
@bricelam can you clarify? see the latest comments.

**Comment by bricelam** [comment]
Now I'm really confused. 1.1.0 of what? The lowest .NET Standard supported by System.Data.Common is 1.2, and the package versions are all 4.x.x

**Comment by weshaggard** [comment]
Lets take a step back for a moment. 
1.1.0 is the .NET Core 1.1 release and which maps to the 4.3.0 package version for System.Data.Common. Looking at the APIs we expose there I see https://github.com/dotnet/corefx/blob/release/1.1.0/src/System.Data.Common/ref/System.Data.Common.cs#L364. So while DbDataReader doesn't contain an Close method it does contain both a Dispose and if you cast it to IDataReader you could call Close (or implement that interface). I'm not sure if that will be a good enough work around for you but it something that should be considered.

Assuming that doesn't fit the need and we need a public virtual close then we will have to make the change in our release/1.1.0 branch as part of our next servicing event. It looks like all we need to do is change the Close method from explicit to implicit in the ref (https://github.com/dotnet/corefx/blob/release/1.1.0/src/System.Data.Common/ref/System.Data.Common.cs#L364). Of course that assumes that the base implementation of Close and Dispose does the correct things.

**Comment by corivera** [comment]
1.1.0 DbDataReader's Dispose doesn't call Close either, so we include that change along with the contract changes.

**Comment by danmosemsft** [comment]
@corivera spoke offline wrt whether you want to backport this or it doesn't meet the servicing bar.

**Comment by roji** [comment]
Seems like this can be closed, no? Is there still any value in servicing 1.1.0 for data providers, I have a hard time imagining this would be useful anymore...

**Comment by bricelam** [comment]
Yeah, now that we recommend targeting .NET Standard 2.0 by default (and cross-targeting it when targeting .NET Standard 1.x) it's mostly a non-issue.
