### ISSUE TITLE
[uapaot] AsyncTaskMethodBuilder<TResult>.SetStateMachine throws when 'm_moveNextAction' is uninitialized

### ISSUE THREAD

**Issue by kouvel** [dotnet/corefx#22506]
It's a difference from CoreCLR behavior, the exception occurs here:
https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs#L874

The following test was temporarily disabled for uapaot in PR https://github.com/dotnet/corefx/pull/22481:
- AsyncValueTaskMethodBuilderTests.SetStateMachine_InvalidArgument_ThrowsException

Test:
```c#
            AsyncValueTaskMethodBuilder<int> b = ValueTask<int>.CreateAsyncMethodBuilder();
            AssertExtensions.Throws<ArgumentNullException>("stateMachine", () => b.SetStateMachine(null));

// The following line throws InvalidOperationException on uapaot
            b.SetStateMachine(new DelegateStateMachine());
```

**Comment by stephentoub** [comment]
We no longer run tests on a `uapaot` configuration.
