### ISSUE TITLE
Value 0x0010 for DllCharacteristics is missing

### ISSUE THREAD

**Issue by jakepetroules** [dotnet/corefx#22508]
In corefx/src/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEFileFlags.cs, there is no value for 0x0010 listed.

I cannot find it documented anywhere, however if I build a native DLL with cl.exe and pass /APPCONTAINER to the linker, this bit is present in the resulting PE file's DllCharacteristics field.

While the link.exe documentation for /APPCONTAINER isn't clear whether it actually applies to DLLs, the fact that the C# compiler only has a single /out:library option as opposed to separate /out:winexe and /out:appcontainerexe options would seem to indicate that it doesn't apply.

Can someone check with the Visual C++ compiler team to find out what the value of 0x0010 is in DllCharacteristics and if it has anything to do with building a DLL with /APPCONTAINER, or is just a coincidence as a result of /APPCONTAINER activating other options in the reuslting output?

**Comment by mellinoe** [comment]
@nguerrera Any idea what that flag value means?

**Comment by jakepetroules** [comment]
Sorry, my fault, I completely forgot PE files are little endian. The value I was looking at is indeed 0x1000 (IMAGE_DLLCHARACTERISTICS_APPCONTAINER), not 0x0010.
