### ISSUE TITLE
Project URL isn't meaningful

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#22527]
Our packages all point to `http://dot.net` which isn't a very meaningful location. Instead, the packages should probably point to their proper GitHub repos, e.g. `https://github.com/dotnet/corefx`.

**Comment by jnm2** [comment]
https 😈

**Comment by terrajobst** [comment]
Point taken and fixed.

**Comment by ViktorHofer** [comment]
Yes it does, i.e. https://www.nuget.org/packages/System.Reflection.Context/4.6.0-preview.18571.3
