### ISSUE TITLE
Request: Consider displaying count in debugger display when known for System.Linq iterators

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#22520]
Today I was debugging an xUnit theory that accepted an `IEnumerable<int>`. In my test data method, I was generating the enumerable via `Enumerable.Range`. When I looked at the enumerable in the debugger, it was stringified to `{System.Linq.RangeIterator}`. I needed to evaluate the enumerable via 'Results View' and count the number of elements displayed to find the count.

<img width="960" alt="corefx_dbgview" src="https://user-images.githubusercontent.com/9159214/28488366-16ec7e24-6e76-11e7-8ac7-426088f11ca2.PNG">

Can we consider just displaying the count in the debugger display if we know it already? We can even consider adding more information for a few iterators, where there's not a risk of stringifying a really long collection or evaluating user-supplied functions. For example, we can show `Start = x, Count = y` in the debugger display for `Range` and `Element = ..., Count = x` for `Repeat`.

**Comment by danmosemsft** [comment]
Seems like this probably comes from src\System.Linq\src\System\Linq\DebugView.cs. There's a note there that VS instantiates them by hard coded name. Perhaps if you add a Count property there, and test whether the IEnumerable is an ICollection, and if so return the count, you might get some of this.
