### ISSUE TITLE
ClientWebSocket throws exception when connecting after abort

### ISSUE THREAD

**Issue by Trolldemorted** [dotnet/corefx#22535]
The [documentation ](https://msdn.microsoft.com/en-us/library/system.net.websockets.clientwebsocket.abort(v=vs.110).aspx) of `ClientWebSocket.Abort()` says:
> Aborts the connection and cancels any pending IO operations.

But after calling `Abort`, one can no longer connect with that ClientWebSocket. The following snippet throws an ObjectDisposedException ("Cannot access a disposed object"):

```
CancellationTokenSource src = new CancellationTokenSource();
ClientWebSocket socket = new ClientWebSocket();
socket.ConnectAsync(new Uri("wss://echo.websocket.org"), src.Token).Wait();
socket.Abort();
socket.ConnectAsync(new Uri("wss://echo.websocket.org"), src.Token).Wait();
```

I understand that this exception is thrown when trying to reconnect after a `Dispose` call (since the documentation states that unmanaged resources are released), but why is it also thrown after `Abort`?

**Comment by davidsh** [comment]
This is the same behavior as .NET Framework.  Calling Abort() is a terminal operation and closes the socket.  The connection lifetime is over at that point and essentially this is similar to Dispose().

The documentation can probably be enhanced to explain this better.

**Comment by davidsh** [comment]
cc: @CIPop @DavidGoll

**Comment by Trolldemorted** [comment]
Thanks for the quick response - after having read the documentation i assumed that Abort would only reset the current state of the socket and it would behave as a new instance would do.

**Comment by rmkerr** [comment]
The documentation has been updated -- closing this issue now.
