### ISSUE TITLE
[uapaot] Investigate AssemblyResolve event raising for CoreLib resources

### ISSUE THREAD

**Issue by kouvel** [dotnet/corefx#22555]
.NET Core PRs:
https://github.com/dotnet/coreclr/pull/12999
https://github.com/dotnet/corefx/pull/22552

**Comment by danmosemsft** [comment]
Should this be UWP6.0 ?

**Comment by kouvel** [comment]
Yes that's what I meant, thanks

**Comment by kouvel** [comment]
Looks like AssemblyResolve is not raised at all in CoreRT (looks to me like that is by design to disallow changing assembly resolution), and Assembly.LoadFrom is not supported (looks like for the same reason).

**Comment by kouvel** [comment]
And because it's aot I guess
