### ISSUE TITLE
Linux Sockets: Close with pending synchronous Receive hangs

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#22564]
If you issue a blocking Receive on a connected socket, and then try to Close it from another thread, the Close call will hang and the Receive will never complete.

This works properly on Windows -- the Close succeeds and the Receive throws a SocketException with errorCode = ConnectionAborted.

**Comment by geoffkizer** [comment]
Also note, this works fine with an asynchronous Receive.

**Comment by stephentoub** [comment]
> This works properly on Windows

I believe it's undefined behavior in BSD sockets.  Windows makes that work, but we can't depend on it working on arbitrary systems.

**Comment by geoffkizer** [comment]
I should have been clearer.  I don't necessarily expect the Receive call to complete; that's OS dependent.  

The specific problem here is that we're hanging in the Close path trying to close the AsyncContext, because of some deadlock in AsyncContext's close logic.

If I just disable the AsyncContext close call, then the Close does not hang and the Receive never completes, which is what we expect on Linux, I believe.

**Comment by stephentoub** [comment]
> The specific problem here is that we're hanging in the Close path trying to close the AsyncContext, because of some deadlock in AsyncContext's close logic.

Ah.  What happens if you issue a Shutdown before closing the handle... does that help at all?

**Comment by geoffkizer** [comment]
Haven't tried that (I will later).

**Comment by geoffkizer** [comment]
Calling shutdown() before close() seems to cause the sync Receive to return 0 bytes (i.e. EOF). 

This certainly seems better than hanging forever.  I suppose we could try to detect that we're in the process of closing and convert this into an exception, like Windows does.  Or we could just leave it returning 0 bytes.

That said, calling shutdown made a few other tests break which I have not investigated.

**Comment by geoffkizer** [comment]
FYI, for sync Send the behavior is similar: without shutdown it hangs, with shutdown it returns EINVAL -- presumably because the socket is no longer valid for sending.

**Comment by jhudsoncedaron** [comment]
I found this also hangs on Windows on a single processor box. The underlying system call choices are undefined here.

**Comment by wfurt** [comment]
This may be similar to #26034. In this case there is pending blocking accept() system call. 
The current code does not get to actually closing socket and it hangs. calling shutdown before TcpListener.stop() also fixes the hang. (and accept() will fail and come back)

For #26034 I was not sure if that is real bug of if it is expected that blocking call would actually block.
Can we possibly track pending blocking operations and call shutdown as needed?

**Comment by davidsh** [comment]
Reactivating since we reverted PR #37486.
