### ISSUE TITLE
Core Tests (Master): All work items has fireball on Ubuntu.1610.Amd64-x64

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#22578]
Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170725.01

All work items has fireball on Ubuntu.1610.Amd64-x64

**Comment by danmosemsft** [comment]
@mattgal any more to do here?

**Comment by MattGal** [comment]
No more action needed, @weshaggard  already did the right stuff and merged it (https://github.com/dotnet/corefx/pull/22568), but it evidently wasn't in by 5 PM yesterday.  20170725.02 does not have this problem

We do I believe still need to do this in any release branches that use 16.10... I've set up the 16.10 queue to automatically forward to the deadletter (instant fireball) queue so this sort of problem will pop up anywhere we need to clean it up. (I believe it should just be release/uwp6.0 from a quick peek )

**Comment by danmosemsft** [comment]
@weshaggard any chance you could remove 16.10 from the uwp60 and release/2.0 branches as well?

**Comment by MattGal** [comment]
@danmosemsft as mentioned before it's actually only in the uwp60 branch.  I'm happy to make the PR, do I need to send a ship-room template for this?

**Comment by danmosemsft** [comment]
Oh, I just saw it in the 2.0 results because they are old https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170719.03

Yes, I'll send the template offline.

**Comment by Jiayili1** [comment]
All tests have fireball issue on RedHat.69.Amd64-x64, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170824.01

**Comment by MattGal** [comment]
Hi @Jiayili1 .  Fireballs are just the worst type of work item failure, it is usually a good idea to create a new issue to be safe, as the title of this issue makes it look like a less interesting problem (since Ubuntu 16.10 is end-of-life and not supported).  Unless the operating systems and logs match in some meaningful way, I'd really prefer we create new issues for new problems.

From a quick check of the logs, we've worked past the RedHat 6.9 problem with Dumpling from last week and we're on to binary dependencies being missing on the execution machines.  This is still possible to be an infra issue ( @smile21prc , @dotnet/dnceng FYI) if there are libraries that need to be set up on the machines at provisioning time.

```
/home/helixbot/dotnetbuild/work/365af8b5-6a53-4e95-8cfd-25268b50b0d9/Payload/dotnet: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /home/helixbot/dotnetbuild/work/365af8b5-6a53-4e95-8cfd-25268b50b0d9/Payload/dotnet)
/home/helixbot/dotnetbuild/work/365af8b5-6a53-4e95-8cfd-25268b50b0d9/Payload/dotnet: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.17' not found (required by /home/helixbot/dotnetbuild/work/365af8b5-6a53-4e95-8cfd-25268b50b0d9/Payload/dotnet)
/home/helixbot/dotnetbuild/work/365af8b5-6a53-4e95-8cfd-25268b50b0d9/Payload/dotnet: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by /home/helixbot/dotnetbuild/work/365af8b5-6a53-4e95-8cfd-25268b50b0d9/Payload/dotnet)
/home/helixbot/dotnetbuild/work/365af8b5-6a53-4e95-8cfd-25268b50b0d9/Payload/dotnet: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /home/helixbot/dotnetbuild/work/365af8b5-6a53-4e95-8cfd-25268b50b0d9/Payload/dotnet)
/home/helixbot/dotnetbuild/work/365af8b5-6a53-4e95-8cfd-25268b50b0d9/Payload/dotnet: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /home/helixbot/dotnetbuild/work/365af8b5-6a53-4e95-8cfd-25268b50b0d9/Payload/dotnet)
```
@janvorli, any thoughts?

**Comment by janvorli** [comment]
It looks like a wrong "dotnet" is being used. This one was definitely not built on RHEL 6.

**Comment by janvorli** [comment]
The issue causing all RedHat.69.Amd64-x64 tests being red should be fixed by #23536

**Comment by danmosemsft** [comment]
@Jiayili1 fixed?

**Comment by Jiayili1** [comment]
@danmosemsft This issue is not repro in build 20170829.02, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170829.02

**Comment by karelz** [comment]
Not repro, closing.
