### ISSUE TITLE
Trivial change to make Queue<T>'s Enqueue / Dequeue twice faster

### ISSUE THREAD

**Issue by omariom** [dotnet/corefx#2257]
[Generic Queue](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/Queue.cs) doubles its capacity on each grow. And by default it starts with 4 items in its underlying array.

```C#
private const int MinimumGrow = 4; 
private const int GrowFactor = 200;  // double each time 
private const int DefaultCapacity = 4; 
```
It gives us opportunity to use well known trick - bitwise AND instead of modulus -  in Enqueue, Dequeue and Contains methods. We just need to check if size of the underlying array is power of two.

For example Dequeue could look like this:
```C#
public T Dequeue() 
{ 
    if (_size == 0) 
        throw new InvalidOperationException(SR.InvalidOperation_EmptyQueue); 

    T removed = _array[_head]; 
    _array[_head] = default(T); 
    _head = _isCapacityPowerOfTwo
                  ? (_head + 1) & (_array.Length - 1)  
                  : (_head + 1) % _array.Length; 
    _size--; 
    _version++; 
    return removed; 
} 
```

In microbechmarks  it makes Enqueue and Dequeue twice faster when default ctor is used or initial capacity (set via another ctor)  is power of two. And it doesn't degrade in opposite case because division is much heavier compared to branching on _isCapacityPowerOfTwo field.

The change doesn't make Queue consume more memory.

**Comment by nguerrera** [comment]
Interesting. This would add an extra field to every instance of Queue, which might be worth weighing against the speedup. 

How does `if (++_head == array.Length) { _head = 0; }` perform in the same microbenchmark?

**Comment by omariom** [comment]
@nguerrera 
> This would add an extra field to every instance of Queue, which might be worth weighing against the speedup.

Technically we don't have to use the new field if [in this ctor](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/Queue.cs#L48) we increase capacity to next power of 2. 

> How does  if (++_head == _array.Length) { _head = 0; }  perform in the same microbenchmark?

I will check that.

**Comment by stephentoub** [comment]
> Technically we don't have to use the new field if in this ctor we increase capacity to next power of 2.

The point of that ctor, though, is for someone to say how much memory they're going to need; if we artificially increase it, that's going to consume even more memory than an extra Boolean field.

> in this ctor

TrimExcess would also be affected, or more generally anything that calls SetCapacity.

**Comment by omariom** [comment]
@stephentoub
Yes, this is what I meant when I wrote "The change doesn't make Queue consume more memory."

**Comment by stephentoub** [comment]
> Yes, this is what I meant when I wrote "The change doesn't make Queue consume more memory."

I'm not following... you're drawing a distinction between whether the extra memory is associated with the Queue object itself or with the underlying array object the Queue creates?

**Comment by omariom** [comment]
With underlying array.

Personally I would prefer not to use an extra field and  make code linear but I knew that the  memory usage increase will be a concern for you, guys :)

**Comment by omariom** [comment]
@nguerrera 
>How does  if (++_head == _array.Length) { _head = 0; }  perform in the same microbenchmark?

It is twice fast as well. 
It is a win-win!

**Comment by nguerrera** [comment]
:) I think we should go with that then.

**Comment by stephentoub** [comment]
@omariom, are you going to submit a PR for this?

**Comment by omariom** [comment]
@stephentoub, I am not going to miss such opportunity )

**Comment by stephentoub** [comment]
@omariom, just checking in on this.  Are you still planning to submit a PR here?

**Comment by sharwell** [comment]
@nguerrera Your example is the conclusion I came to as well. :+1:

**Comment by omariom** [comment]
@stephentoub, I am. Just been a bit busy last weeks.

**Comment by omariom** [comment]
@stephentoub
The PR is ready: https://github.com/dotnet/corefx/pull/2515
