### ISSUE TITLE
Strange code coverage of PipeAsyncResult

### ISSUE THREAD

**Issue by Maxwe11** [dotnet/corefx#2258]
Look at `CallUserCallback()` method. Seems on race condition in tests.

http://dotnet-ci.cloudapp.net/job/dotnet_corefx_coverage_windows/335/artifact/bin/tests/coverage/System.IO.Pipes_PipeAsyncResult.htm

http://dotnet-ci.cloudapp.net/job/dotnet_corefx_coverage_windows/336/artifact/bin/tests/coverage/System.IO.Pipes_PipeAsyncResult.htm

http://dotnet-ci.cloudapp.net/job/dotnet_corefx_coverage_windows/337/artifact/bin/tests/coverage/System.IO.Pipes_PipeAsyncResult.htm

http://dotnet-ci.cloudapp.net/job/dotnet_corefx_coverage_windows/338/artifact/bin/tests/coverage/System.IO.Pipes_PipeAsyncResult.htm
I have the same floating results locally

**Comment by stephentoub** [comment]
We need better tests in general that validate more than what's currently being validated, and more consistently. That said, I don't think this points at a functional problem in the tests nor in the product.  This IAsyncResult is used as part of Begin/EndWaitForConnection, which is called on some paths with a null callback (when using the synchronous WaitForConnection with IsAsync set to true) and on some with a non-null (when using WaitForConnectionAsync).  However, the CallUserCallback method isn't invoked on every usage, only when the Win32 ConnectNamedPipe invocation doesn't complete the work synchronously.

**Comment by Maxwe11** [comment]
>Win32 ConnectNamedPipe invocation doesn't complete the work synchronously.
Missed that, thanks.
