### ISSUE TITLE
Unable to construct X509Certificate2 object from byte array on UWP

### ISSUE THREAD

**Issue by mconnew** [dotnet/corefx#22597]
The WCF team has a test infrastructure which creates new short lived client certificates for each run. In our scenario test code we fetch the bytes for a certificate from our test server and instantiate an X509Certificate2 object to then install in the local user MY certificate store. This works fine on all platforms 
except UWP where we get a WindowsCryptographicException with the message `Access denied`. This is the code we're trying to run:
```csharp
        var certificate = new X509Certificate2(certBytes, "test", X509KeyStorageFlags.PersistKeySet);
```
It throws the following exception:
```csharp
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Access denied
Stack Trace:
     at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
     at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
     at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
```
If I change the constructor to use `X509KeyStorageFlags.EphemeralKeySet | X509KeyStorageFlags.Exportable`, instead I get the same exception but with the message `Bad Data`. An example of the certificate we're using [is here](https://github.com/dotnet/corefx/files/1174392/wcf-client-cert.zip). It's created with bouncy castle as we need to control CRL's for our testing.

**Comment by danmosemsft** [comment]
@bartonjs are you available to investigate this?

**Comment by ianhays** [comment]
Jeremy is at Defcon for the remainder of the week. I'll take a look and see if I can follow the path of the failure.

**Comment by ianhays** [comment]
@mconnew I repro your bug. I'm guessing your certs' default is to try to install to the machine store which is disallowed on UWP.

You can circumvent the "Access Denied" exception and override the default by specifying X509KeyStorageFlags.UserKeySet e.g.
```
var certificate = new X509Certificate2(certBytes, "test", X509KeyStorageFlags.UserKeySet | X509KeyStorageFlags.PersistKeySet);
```

**Comment by mconnew** [comment]
I'm not trying to import it into any store at this point, I'm simply constructing an X509Certificate2 object. This works on .Net core on Windows and then can successfully use X509Store to import it into the user store. Even though you've provided a work around, full framework/.Net core code should work unmodified on UWP.

**Comment by bartonjs** [comment]
@mconnew If it's just the user vs machine permissions, then the same PFX would fail if you tried to open it by a non-admin without specifying a scope.  A PFX normally goes into UserKeySet unless it has a marker within it saying it came from a machine key store, at which point not having a preference means to put it back.

So if this is just User vs Machine, I don't think any code change for UWP is warranted.
