### ISSUE TITLE
Add IPAddress Span-based APIs

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#22607]
Separated out of https://github.com/dotnet/corefx/issues/21281 for tracking purposes.

- [ ] Implement in System.Net.Primitives in corefx
- [ ] Expose from System.Net.Primitives contract in corefx
- [ ] Add tests to System.Net.Primitives tests in corefx

```C#
namespace System.Net
{
    public class IPAddress
    {
        public IPAddress(ReadOnlySpan<byte> address);
        public IPAddress(ReadOnlySpan<byte> address, long scopeid);

        public bool TryWriteBytes(Span<byte> destination, out int bytesWritten);

        public static IPAddress Parse(ReadOnlySpan<char> ipChars);
        public static bool TryParse(ReadOnlySpan<char> ipChars, out IPAddress address);
        public static bool TryFormat(Span<char> destination, out int charsWritten);
        …
    }
}
```

**Comment by Paxxi** [comment]
I'm interested in this one.

I'm curious, what is `TryWriteBytes` supposed to do here?

**Comment by stephentoub** [comment]
> I'm interested in this one.

Great

> what is TryWriteBytes supposed to do here?

The same thing as GetAddressBytes, except instead of allocating an array and writing the bytes to that, it writes the bytes to the supplied span and stores the number of bytes written into the out int.  If there's enough room to store the bytes, it returns true. If the span is too small, nothing is written, the out int is set to 0, and it returns false.

**Comment by Paxxi** [comment]
Thank you. I was looking for a similarly named method and completely missed GetAddressBytes.

Now I ran into an issue getting it to build after adding a reference to System.Memory for the Span. I guess I've missed adding the reference somewhere but haven't been able to figure out where.

current test changes https://github.com/Paxxi/corefx/commit/2f91befe23a6d45191fbe2fc4323e34f19f2f397

error I get when building
```
  Microsoft.Private.CoreFx.NETCoreApp -> C:\code\corefx\bin/packages/Debug/specs/runtime.win-x64.Microsoft.Private.CoreFx.NETCoreApp.nuspec
  Verifying closure of runtime.win-x64.Microsoft.Private.CoreFx.NETCoreApp runtime assemblies
C:\code\corefx\pkg\frameworkPackage.targets(124,5): error : Assembly 'System.Net.Primitives' is missing dependency 'System.Memory' [C:\code\corefx\pkg\Microsoft.Private.CoreFx.NETCoreApp\Microsoft.Private.CoreFx.NETCoreApp.pkgproj]

C:\code\corefx\pkg\frameworkPackage.targets(124,5): error : Assembly 'System.Net.Primitives' is missing dependency 'System.Memory' [C:\code\corefx\pkg\Microsoft.Private.CoreFx.NETCoreApp\Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
Command execution failed with exit code 1.
```

**Comment by stephentoub** [comment]
You don't need/want to add a System.Memory reference; Span is now exposed from System.Runtime in corefx master, so the System.Net.Primitives src/ref projects already have access to it.  For the test project, it's currently building against netstandard, so you'll want to add a netcoreapp build of the tests in order to test the new API that's being added only to .NET Core.  You can see an example of doing that in https://github.com/dotnet/corefx/pull/22689:
- Adding a netcoreapp entry to its Configurations.props file, e.g. https://github.com/dotnet/corefx/pull/22689/commits/dccf73bc6573c948f6e49085c42d29c9b9d24424#diff-55c3506c014b947ed9b7a9efef3039e9R6
- Updating the .csproj to have an appropriate configuration, e.g. https://github.com/dotnet/corefx/pull/22689/commits/dccf73bc6573c948f6e49085c42d29c9b9d24424#diff-e5cc77cf764c1b35ba202b78bd9918b3R10
- And putting the tests that use the new APIs in their own files that are only built in the netcoreapp configuration, e.g. https://github.com/dotnet/corefx/pull/22689/commits/dccf73bc6573c948f6e49085c42d29c9b9d24424#diff-e5cc77cf764c1b35ba202b78bd9918b3R59

**Comment by Paxxi** [comment]
Thank you for the pointers, that got me going. Not sure about the etiquette since it's a large repo so I didn't want to post just a thank you.

Now I have a new issue which I've been fighting with over the weekend.
The simple act of changing the signature of `IPv6AddressHelper::Parse(string address, ushort* numbers, int start, ref string scopeId)` to `IPv6AddressHelper::Parse(ref ReadOnlySpan<char> address, ushort* numbers, int start, ref string scopeId)` results in tests crashing with
```

**Comment by stephentoub** [comment]
ToString on a span doesn't do what you want it to (just as it doesn't on a char[]) and is likely the cause of the error.

**Comment by karelz** [comment]
@Paxxi I sent you collaborator invite, so that we can assign the issue to you (let me know when you accept).
BTW: I recommend to disable all CoreFX repo notifications (you will be subscribed to all once you accept the invite), otherwise you will be DoS'd.

Thanks for your contribution!

**Comment by Paxxi** [comment]
I have accepted the invitation now.
