### ISSUE TITLE
Add HashAlgorithm Span-based APIs

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#22613]
Separated out of https://github.com/dotnet/corefx/issues/21281 for tracking purposes.

- [ ] Implement in System.Security.Cryptography.Primitives in corefx
- [ ] Expose from System.Security.Cryptography.Primitives contract in corefx
- [ ] Add tests to System.Security.Cryptography.Primitives tests in corefx

```C#
namespace System.Security.Cryptography
{
    public abstract class HashAlgorithm
    {
        public bool TryComputeHash(ReadOnlySpan<byte> source, Span<byte> destination, out int bytesWritten);
        protected virtual void HashCore(ReadOnlySpan<byte> source);
        protected virtual bool TryHashFinal(Span<byte> destination, out int bytesWritten);
        …
    }
}
```

These methods should then be overridden as-is appropriate on the implementations for:
- [ ] MD5
- [ ] SHA1
- [ ] SHA256
- [ ] SHA384
- [ ] SHA512

**Comment by KrzysztofCwalina** [comment]
Often the source bytes will not be in a single span. Maybe we should also expose these two protected members publicly?

**Comment by stephentoub** [comment]
> Often the source bytes will not be in a single span. Maybe we should also expose these two protected members publicly?

I believe the intent for such a case is to use IncrementalHash.  @bartonjs?

**Comment by bartonjs** [comment]
Yup.  `HashAlgorithm` is for one-shot, `IncrementalHash` is for cumulative/iterative.

**Comment by KrzysztofCwalina** [comment]
OK, makes sense.

**Comment by Tornhoof** [comment]
Is `Rfc2898DeriveBytes` getting the Span Treatment too or is this rather #22615?
