### ISSUE TITLE
Add WebSocket Buffer-based APIs

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#22610]
Separated out of https://github.com/dotnet/corefx/issues/21281 for tracking purposes.

- [ ] Implement in System.Net.WebSockets in corefx
- [ ] Expose from System.Net.WebSockets contract in corefx
- [ ] Add tests to System.Net.WebSockets tests in corefx

```C#
namespace System.Net.WebSockets
{
    public abstract class WebSocket
    {
        public virtual ValueTask<ValueWebSocketReceiveResult> ReceiveAsync(Buffer<byte> buffer, CancellationToken cancellationToken = default(CancellationToken));
        public virtual Task SendAsync(ReadOnlyBuffer<byte> buffer, CancellationToken cancellationToken = default(CancellationToken));
        …
    }

    [StructLayout(LayoutKind.Auto)]
    public struct ValueWebSocketReceiveResult
    {
        public ValueWebSocketReceiveResult(int count, WebSocketMessageType messageType, bool endOfMessage);
        public ValueWebSocketReceiveResult(int count, WebSocketMessageType messageType, bool endOfMessage, WebSocketCloseStatus? closeStatus, string closeStatusDescription);
        public WebSocketCloseStatus? CloseStatus { get; }
        public string CloseStatusDescription { get; }
        public int Count { get; }
        public bool EndOfMessage { get; }
        public WebSocketMessageType MessageType { get; }
     }
}
```

**Comment by benaadams** [comment]
Just a thought... on `WebSocketCloseStatus?`

A value of 0 is in invalid status; so the enum could have `WebSocketCloseStatus`.`NoClosed`/`NoStatus` = 0 rather than being a nullable as a nullable int is much bigger

**Comment by stephentoub** [comment]
> A value of 0 is in invalid status; so the enum could have WebSocketCloseStatus.NoClosed/NoStatus = 0 rather than being a nullable as a nullable int is bigger

And that's reflected in the comment here:
https://github.com/dotnet/corefx/blob/master/src/System.Net.WebSockets/src/System/Net/WebSockets/WebSocketCloseStatus.cs#L11-L12
Seems reasonable to me.

@davidsh?

**Comment by benaadams** [comment]
Or JS has different events for Close and Receive; different question... 

If `ReceiveAsync` returns close information, it should never throw? e.g. that's what Status 1000+ are for.

However it throws in all sorts of ways; based on state, on close, on bad message etc; so should Close not be part of result but part of a WebscoketCloseExcpetion type instead?

**Comment by davidsh** [comment]
Actually 1006 is the code that should be used if an "unclean" code happens, i.e. a close frame handshake fails to occur.

https://tools.ietf.org/html/rfc6455#page-42

>If _The WebSocket Connection is Closed_ and no Close control frame was received by the
endpoint (such as could occur if the underlying transport connection
is lost), _The WebSocket Connection Close Code_ is considered to be
1006.

**Comment by benaadams** [comment]
Currently if the socket closes then you call `ReceiveAsync` on it, it will throw and it has a whole bunch of [exceptions](https://github.com/dotnet/corefx/blob/master/src/System.Net.WebSockets/src/System/Net/WebSockets/WebSocketException.cs), so am questioning the api generally.

e.g. should the `ValueWebSocketReceiveResult` be shrunk to (since its by val)
```csharp
public struct ValueWebSocketReceiveResult
{
    public ValueWebSocketReceiveResult(int count, WebSocketMessageType messageType, bool endOfMessage);
    public int Count { get; }
    public bool EndOfMessage { get; }
    public WebSocketMessageType MessageType { get; }
}
```
If could return `Count == 0`; `EndOfMessage == true` at close and `WebSocket` have the additional properties
```csharp
public abstract class WebSocket
{
    public WebSocketCloseStatus? CloseStatus { get; }
    public string CloseStatusDescription { get; }
    …
}
```

**Comment by stephentoub** [comment]
I agree; seems like there's little value in paying to pass around the CloseStatus and CloseStatusDescription when they're already available off of the WebSocket itself.  Let's leave them off of ValueWebSocketReceiveResult.
