### ISSUE TITLE
Move S.R.Metadata throw helpers together

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#2261]
We have a pattern in the reader to move all throw helpers into simple non-inlined helpers taking no arguments. This makes them have the smallest impact possible on calling methods, which both improves the likelihood that callers will be inlined and reduces the impact on code size from their inlining. The exceptional cases are rare (by definition) so there is no value in inlining their implementation.

Today we have various private static void ThrowXyz() spread throughout. These would be better organized within a single internal Throw static class with documentation around why we have this pattern.

**Comment by weshaggard** [comment]
@nguerrera do we think having these type of throws helpers is worth it? I ask because it isn't consistent throughout the libraries and we did a large clean-up to remove them from other locations like the collections.

**Comment by nguerrera** [comment]
It is definitely measurably worth it in at least some very particular places in the metadata reader.  I did a bunch of performance tuning on the BlobReader and it made a significant difference.

**Comment by weshaggard** [comment]
Is it something that we would recommend for a general pattern throughout the libraries? As an aside we actually have a IL transform for .NET Native that optimizes all these throw sites. I wonder if this wouldn't be better as a compiler optimization or a transform of some sort. That way we would have it consistently applied through the code and we wouldn't need to have it authored in the cs files directly.

**Comment by nguerrera** [comment]
I wouldn't necessarily recommend it without having done some measuring in a real scenario that needs tuning, but it is a worthwhile pattern to have at your disposal when you find you need it. Yes, sufficiently smart codegen could fix this for you, but this library's most critical usage (by Roslyn) doesn't have these optimizations today and even if they were added, we likely wouldn't want to regress downlevel perf...

My stance is basically that we don't need to push for this, nor should we push against it. I don't think there's much harm in a bit of case-by-case per library here.
