### ISSUE TITLE
Create a docker file for RHEL 6 distro

### ISSUE THREAD

**Issue by smile21prc** [dotnet/corefx#22620]
Per @Petermarcu @janvorli 
As part of the plan to be able to ship .NET Core 2.0 that supports RHEL 6, we need build machines for that distro. This is necessary as RHEL 6 is super ancient w.r.t. the libraries that we depend on. So if we build on RHEL 7, which was our minimum supported distro, the binary will get dependencies on versions of some symbols that are not present on RHEL 6.

As a result, to run dotnet core on RHEL 6, it has to be built on RHEL 6, which requires the corresponding docker to be created.

RHEL 6 is NOT free, so we should create equivalent CentOS 6 docker instead. We already have CentoOS docker file available, which can be used as the starting point for the CentOS 6 one.

**Comment by smile21prc** [comment]
This active issue is currently blocking the creation of docker images:
https://github.com/dotnet/core-eng/issues/1251

**Comment by janvorli** [comment]
Here is a Dockerfile contents I have just prepared for the CentOS 6 docker image. It contains all dependencies and tools necessary for dotnet core native parts build.

```Dockerfile
FROM centos:6

# Install build time dependencies

RUN yum install -y git cmake lzma wget xz epel-release centos-release-SCL
RUN yum install -y libuuid-devel libunwind-devel lttng-ust-devel python-argparse cmake3
RUN yum install -y ncurses-devel swig doxygen readline-devel libedit-devel \
krb5-devel libidn-devel libmetalink-devel libnghttp2-devel libssh2-devel nss-devel openldap-devel openssh-server stunnel "perl(Time::HiRes)"

RUN rpm --import http://linuxsoft.cern.ch/cern/slc6X/x86_64/RPM-GPG-KEY-cern
RUN wget -O /etc/yum.repos.d/slc6-devtoolset.repo http://linuxsoft.cern.ch/cern/devtoolset/slc6-devtoolset.repo

RUN yum install -y devtoolset-2-toolchain python27
WORKDIR /root/build

# Build clang and lldb 3.9.1 from sources

RUN wget http://releases.llvm.org/3.9.1/cfe-3.9.1.src.tar.xz
RUN wget http://releases.llvm.org/3.9.1/llvm-3.9.1.src.tar.xz
RUN wget http://releases.llvm.org/3.9.1/lldb-3.9.1.src.tar.xz

RUN tar -xf llvm-3.9.1.src.tar.xz
RUN mkdir llvm-3.9.1.src/tools/clang
RUN mkdir llvm-3.9.1.src/tools/lldb
RUN cd llvm-3.9.1.src/tools/clang && tar -xf ../../../cfe-3.9.1.src.tar.xz --strip 1
RUN cd llvm-3.9.1.src/tools/lldb && tar -xf ../../../lldb-3.9.1.src.tar.xz --strip 1

WORKDIR /root/build/llvmbuild
RUN scl enable python27 devtoolset-2 'cmake3 -DCMAKE_CXX_COMPILER=/opt/rh/devtoolset-2/root/usr/bin/g++  -DCMAKE_C_COMPILER=/opt/rh/devtoolset-2/root/usr/bin/gcc -DCMAKE_LINKER=/opt/rh/devtoolset-2/root/usr/bin/ld -DCMAKE_BUILD_TYPE=Release ../llvm-3.9.1.src'
RUN scl enable python27 devtoolset-2 'make -j 9'

# Workaround - the install scripts expects that folder to exist, but for some reason, it was not created
RUN mkdir lib/python2.7
RUN scl enable python27 devtoolset-2 'make install'

# Build the CURL 7.45.0

WORKDIR /root/build
RUN wget https://curl.haxx.se/download/curl-7.45.0.tar.lzma
RUN tar -xf curl-7.45.0.tar.lzma

WORKDIR /root/build/curl-7.45.0
RUN scl enable python27 devtoolset-2 './configure --disable-ftp --disable-file --disable-ldap --disable-ldaps --disable-rtsp --disable-dict --disable-telnet --disable-tftp --disable-pop3 --disable-imap --disable-smb --disable-smtp --disable-gopher --without-librtmp --disable-manual --disable-libcurl-option --with-nghttp2--with-gssapi --enable-ipv6 --with-ssl --enable-symbol-hiding --enable-optimize --with-ca-bundle=/etc/pki/tls/certs/ca-bundle.crt'
RUN scl enable python27 devtoolset-2 'make install'

# Get and install ICU 57.1 binaries

WORKDIR /root/build
RUN wget http://download.icu-project.org/files/icu4c/57.1/icu4c-57_1-RHEL6-x64.tgz
RUN tar -xf icu4c-57_1-RHEL6-x64.tgz -C /

# Cleanup

WORKDIR /root
RUN rm -r build
```

**Comment by smile21prc** [comment]
Hi, @MichaelSimons , Jan has create the CentOS 6 docker file above, what are the following steps to make sure the images created from it are in the lab?

**Comment by MichaelSimons** [comment]
@janvorli, The next step would be to create a PR for this new Dockerfile at https://devdiv.visualstudio.com/DevDiv/_git/DotNetCore?path=%2Fdockerfiles.  I would suggest consolidating some of the commands to reduce the number of layers produced in the resulting image.  Additionally it looks like some tar files could be cleaned up to reduce the size of the resulting image.

**Comment by janvorli** [comment]
@MichaelSimons my experience with creating Dockerfiles and building images out of them is quite small - in fact, this is my first Dockerfile ever. I have assumed that docker would be somehow able to consolidate all the layers at the end of the build or using some command. Obviously I was not right.

**Comment by janvorli** [comment]
Hmm, which docker version do we use? The docker 1.13 has a `--squash` option that does what I was assuming - squashes all the layers into one after the build is done.

**Comment by MichaelSimons** [comment]
The `--squash- option is only supported when running with experimental features enabled.  In general using the `squash` option is not a good practice IMO because it prevents the use of shared layers.  This is not really applicable here but it is used in the other dockerfiles we use for official builds.

**Comment by weshaggard** [comment]
@smile21prc @janvorli I believe this work is done so closing but if not please reactive issue.
