### ISSUE TITLE
HashAlgorithm.Create throws PNSE on .NET Core 2

### ISSUE THREAD

**Issue by onovotny** [dotnet/corefx#22626]
If you need to call `HashAlgorithm.Create` to create an instance without knowing the concrete type, it throws PNSE on .NET Core 2.

Workaround is to call `(HashAlgorithm)CryptoConfig.CreateFromName(string)`, though calling `CryptoConfig` directly is generally discouraged.

**Comment by danmosemsft** [comment]
Hm, I don't remember the rationale for this one. @bartonjs @ianhays why isn't it like desktop:
```c#
      public static HashAlgorithm Create(String hashName) {
            return (HashAlgorithm) CryptoConfig.CreateFromName(hashName);
        }
```

If the caller just has to do exactly that, it seems perverse for us to not do it. There's no string in the PNSE either.

**Comment by danmosemsft** [comment]
This method has non trivial usage.

**Comment by bartonjs** [comment]
It just got missed when CryptoConfig finally made it back.  If @Petermarcu wants to take it this late I don't have an objection.  But I can't, with a straight face, say it's necessary.

**Comment by Petermarcu** [comment]
We should get it fixed in 2.0.1

**Comment by onovotny** [comment]
@Petermarcu as a library author, how do I know where the fix is and how to set baseline requirements? I can target `netstandard2.0`, but then what? There's no way for me to force that it needs `netcoreapp2.0.1` on that platform?

**Comment by danmosemsft** [comment]
@Petermarcu may have a better answer, but I think you're right that if you target netstandard2.0 the only safe approach is to leave the workaround in. The purpose of servicing is to at least help folks who fully deploy the servicing release: they don't need the workaround in their own code.

**Comment by Petermarcu** [comment]
There are always going to be bugs in the platform implementations of .NET Standard that may require workarounds. 

Yes, as long as you want to behave well on 2.0.0 you will have to use the workaround. The lifespan of 2.0.0 should be fairly short as support for it will die off quickly once we ship a 2.0.1 which I expect will only be a month or two out.  Apps will automatically roll forward to it, all the download links will be updated, and servicing releases will have security fixes in them where we will strongly encourage people to get the latest.

**Comment by Petermarcu** [comment]
Lets make sure we leave this in the 2.0.0 milestone so we don't lose track of it for the first update.

**Comment by onovotny** [comment]
@Petermarcu one thing that'll help are regular telemetry releases that show the % of users who have what version deployed -- ideally would love a time-series chart to see as new versions are introduced and watch it exceed the current version.

**Comment by Petermarcu** [comment]
I agree. I think that would help everyone. We currently don't have any telemetry at runtime which would be the most accurate way to get this info but should be able to get a better understanding of the trend of which SDK they are using which also tells us all which runtime people are running on at dev time at least.

**Comment by Petermarcu** [comment]
@richlander do we have the datapoint in the sdk to tell us which runtime they are running on and/or which runtime they are deploying with their SCD?

**Comment by danmosemsft** [comment]
@ianhays can you please document this in https://github.com/dotnet/corefx/wiki/ApiCompat.

**Comment by ianhays** [comment]
@danmosemsft sure thing :)

**Comment by danmosemsft** [comment]
This needs fixing in more places:
```
Searching 11736 files for "Create\(string.*\n.*{.*\n.*PlatformNot" (regex)

C:\git\corefx\src\System.Security.Cryptography.Primitives\src\System\Security\Cryptography\AsymmetricAlgorithm.cs:
   19:         public static AsymmetricAlgorithm Create(string algName)
   20:         {
   21:             throw new PlatformNotSupportedException();

C:\git\corefx\src\System.Security.Cryptography.Primitives\src\System\Security\Cryptography\HashAlgorithm.cs:
   23:         public static HashAlgorithm Create(string hashName)
   24:         {
   25:             throw new PlatformNotSupportedException();

C:\git\corefx\src\System.Security.Cryptography.Primitives\src\System\Security\Cryptography\HMAC.cs:
   31:         public static new HMAC Create(string algorithmName)
   32:         {
   33:             throw new PlatformNotSupportedException();

C:\git\corefx\src\System.Security.Cryptography.Primitives\src\System\Security\Cryptography\KeyedHashAlgorithm.cs:
   16:         public static new KeyedHashAlgorithm Create(string algName)
   17:         {
   18:             throw new PlatformNotSupportedException();

C:\git\corefx\src\System.Security.Cryptography.Primitives\src\System\Security\Cryptography\SymmetricAlgorithm.cs:
   20:         public static SymmetricAlgorithm Create(string algName)
   21:         {
   22:             throw new PlatformNotSupportedException();
```

**Comment by krwq** [comment]
I agree with @bartonjs that this API is not necessary.

On desktop HashAlgorithm.Create will create SHA1 implementation which is not recommended to use because of the recent progress on breaking it.

If we change the default to better hash algorithm which in theory seems like was a plan when creating this general purpose API then people validating a hash between two different frameworks will not be able to use the same API and leaving the default will make existing users unaware of using weak hashing function - throwing an exception is a good trade-off since it will at least trigger (hopefully) good things to happen in users code.

HashAlgortithm.Create is simply too generic and should not be used. A while ago I also thought it was a good idea to have similar APIs like HMAC.Create (https://github.com/dotnet/corefx/issues/16640) and after having multiple conversations about that with @bartonjs I believe it is a good idea not to port them or have them at all as they lead to bad decisions.

**Comment by onovotny** [comment]
@krwq to be clear, I'm not referring to `HashAlgorithm.Create()`, I specifically need `HashAlgorithm.Create(string)`, which takes in the name of the algorithm to create. No defaults. The workaround is just silly IMO, that it'd cause bunches of existing code to break at runtime.

**Comment by krwq** [comment]
@onovotny that sounds good then 😉

**Comment by bartonjs** [comment]
Yeah, I think we made a conscious choice to have AsymmetricAlgorithm, HashAlgorithm, and SymmetricAlgorithm .Create(void) throw.  But the Create(string) versions should be fine to continue dipping into CryptoConfig.

**Comment by danmosemsft** [comment]
@krwq please get a fix for this into master, anything we might want to service, I would like to have baking in master.

**Comment by danmosemsft** [comment]
(leave the issue open)

**Comment by krwq** [comment]
It seems that we missed that:
- HashAlgorithm
- HMAC
- KeyedHashAlgorithm
- SymmetricAlgorithm
- AsymmetricAlgorithm

live inside System.Security.Cryptography.Primitives while CryptoConfig (which is needed to implement Create(string)) lives inside System.Security.Cryptography.Algorithms which depends on System.Security.Cryptography.Primitives. Fixing this would create dependency problem.

Given that we have decided NOT to add this back for now as there is not much requests for this and the workaround is straightforward.

For anyone interested with adding this back please comment and upvote this issue. Closing for now.

**Comment by bartonjs** [comment]
Reopening due to activity on https://github.com/dotnet/standard/issues/530.

**Comment by jocull** [comment]
I appreciate you taking action on this @bartonjs - thank you!
