### ISSUE TITLE
API Proposal: Add *Async operations to signing abstract types

### ISSUE THREAD

**Issue by vcsjones** [dotnet/corefx#22637]
The abstract types `RSA` and `ECDSA` have synchronous operations for signing, verifying, and in the case of RSA specifically, encryption and decryption.

For custom implementations of these types, it would be nice if there were *Async versions of these APIs. For example, an [implementation](https://github.com/onovotny/RSAKeyVaultProvider) that uses Azure Key Vault can do this asynchronously.

I would propose these types be virtual, and if no inheritor overrides them, delegates to the synchronous version in the similar fashion that some of the IO Stream types do.

Going forward, it would be nice then if the core framework used those asynchronous APIs when possible. This also allows other user implementations to take an `RSA` type and get the benefit of async if the inheritor chooses to implement a real async version.

Sample idea:

```csharp
public virtual Task<byte[]> SignDataAsync(
	byte[] data,
	HashAlgorithmName hashAlgorithm,
	RSASignaturePadding padding
)
{
    return Task.FromResult(this.SignData(data, hashAlgorithm, padding));
}
```

**Comment by vcsjones** [comment]
I'm happy to flesh out the API proposal and do the work if the proposal is sound and agreed upon.

**Comment by jnm2** [comment]
What's the alternative? Maintain a separate abstraction specific to communication with a remote signer?

**Comment by vcsjones** [comment]
>What's the alternative? Maintain a separate abstraction specific to communication with a remote signer?

That is doable but rather tedious, and getting it in the core framework will allow library authors to use this instead of everyone inventing their own abstraction. Everyone just goes through the `RSA` type.

A long term goal would be to add async operations for higher level constructs that performing signing, such as `SignedXml`, etc.

**Comment by vcsjones** [comment]
A proposal.

```csharp
namespace System.Security.Cryptography
{
    public abstract partial class ECDsa : AsymmetricAlgorithm
    {
        public Task<byte[]> SignDataAsync(byte[] data, HashAlgorithmName hashAlgorithm);
        public virtual Task<byte[]> SignDataAsync(byte[] data, int offset, int count, HashAlgorithmName hashAlgorithm);
        public virtual Task<byte[]> SignDataAsync(Stream data, HashAlgorithmName hashAlgorithm);

        public Task<bool> VerifyDataAsync(byte[] data, byte[] signature, HashAlgorithmName hashAlgorithm);
        public virtual Task<bool> VerifyDataAsync(byte[] data, int offset, int count, byte[] signature, HashAlgorithmName hashAlgorithm);
        public virtual Task<bool> VerifyDataAsync(Stream data, byte[] signature, HashAlgorithmName hashAlgorithm);

        public virtual Task<byte[]> SignHashAsync(byte[] hash);
        public virtual Task<bool> VerifyHashAsync(byte[] hash, byte[] signature);

        protected virtual Task<byte[]> HashDataAsync(byte[] data, int offset, int count, HashAlgorithmName hashAlgorithm);
        protected virtual Task<byte[]> HashDataAsync(Stream data, HashAlgorithmName hashAlgorithm);
    }

    public abstract partial class DSA : AsymmetricAlgorithm
    {
        public virtual Task<byte[]> CreateSignatureAsync(byte[] rgbHash);
        public virtual Task<bool> VerifySignatureAsync(byte[] rgbHash, byte[] rgbSignature);

        protected virtual Task<byte[]> HashDataAsync(byte[] data, int offset, int count, HashAlgorithmName hashAlgorithm);
        protected virtual Task<byte[]> HashDataAsync(Stream data, HashAlgorithmName hashAlgorithm);

        public Task<byte[]> SignDataAsync(byte[] data, HashAlgorithmName hashAlgorithm);
        public virtual Task<byte[]> SignDataAsync(byte[] data, int offset, int count, HashAlgorithmName hashAlgorithm);
        public virtual Task<byte[]> SignDataAsync(Stream data, HashAlgorithmName hashAlgorithm);

        public Task<bool> VerifyDataAsync(byte[] data, byte[] signature, HashAlgorithmName hashAlgorithm);
        public virtual Task<bool> VerifyDataAsync(byte[] data, int offset, int count, byte[] signature, HashAlgorithmName hashAlgorithm);
        public virtual Task<bool> VerifyDataAsync(Stream data, byte[] signature, HashAlgorithmName hashAlgorithm);
    }

    public abstract partial class RSA : AsymmetricAlgorithm
    {
        public virtual Task<byte[]> EncryptAsync(byte[] data, RSAEncryptionPadding padding);
        public virtual Task<byte[]> DecryptAsync(byte[] data, RSAEncryptionPadding padding);

        public virtual Task<byte[]> SignHashAsync(byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding);
        public virtual Task<bool> VerifyHashAsync(byte[] hash, byte[] signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding);

        protected virtual Task<byte[]> HashDataAsync(byte[] data, int offset, int count, HashAlgorithmName hashAlgorithm);
        protected virtual Task<byte[]> HashDataAsync(Stream data, HashAlgorithmName hashAlgorithm);

        public Task<byte[]> SignDataAsync(byte[] data, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding);
        public virtual Task<byte[]> SignDataAsync(byte[] data, int offset, int count, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding);
        public virtual Task<byte[]> SignDataAsync(Stream data, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding);

        public Task<bool> VerifyDataAsync(byte[] data, byte[] signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding);
        public virtual Task<bool> VerifyDataAsync(byte[] data, int offset, int count, byte[] signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding);
        public Task<bool> VerifyDataAsync(Stream data, byte[] signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding);
    }
}
```

**Comment by karelz** [comment]
@bartonjs is it something we could/should put on crypto roadmap?

**Comment by bartonjs** [comment]
@stephentoub Thoughts?

I'm not sure how I feel about it, personally.  In particular, when using a "keystore backed" CNG or CAPI key it could be on a network attached HSM and Windows (AFAIK) doesn't expose that in an asynchronous manner.  Similarly for OpenSSL using a pkcs11 engine.

So I think we'd be looking at all of the complexities of having async members while we are usually synchronous, and even when we "should" be async we're still synchronous because our underlying API hid it from us.

It *would* make the KeyVault case nicer... but a remote call isn't really expected here.  In extremis: I can imagine an implementation of `IEqualityComparer<T>.Equals(object a, object b)` which needs to hit a database (or other networked resource); but I don't think we'd make an EqualsAsync method if we were doing it today.  Or to make IDisposable have DIsposeAsync, for example.

So, I'm not "opposed", I'm just "skeptical", and think that the line for when we put async overloads is a little further out than this.

**Comment by benaadams** [comment]
@onovotny made us all sad when asking about what use of async in a "sync" call wouldn't deadlock [and pointed out there were no async methods to override](https://github.com/onovotny/RSAKeyVaultProvider/blob/022739a05a3e40575b1423c1e38f904e93522b31/RSAKeyVaultProvider/RSAKeyVault.cs#L24-L82)

**Comment by benaadams** [comment]
KeyValut isn't the only scenario, out-of-proc signing/encryption is another

**Comment by vcsjones** [comment]
> In particular, when using a "keystore backed" CNG or CAPI key it could be on a network attached HSM and Windows (AFAIK) doesn't expose that in an asynchronous manner. Similarly for OpenSSL using a pkcs11 engine.

Yes, that I am fairly sure is true. For the cases of CNG / CAPI / SecureTransforms, I suspect the synchronous APIs will continue to serve their job.

>It would make the KeyVault case nicer... but a remote call isn't really expected here.

Well, the unfortunate part is many times signing operations are remote. The limitations of PKCS#11 and Win32 just present them as synchronous APIs. Network attached HSMs are the norm, and remote signing services like KeyVault are increasingly common.

>In extremis: I can imagine an implementation of `IEqualityComparer<T>.Equals(object a, object b)`

That's where I disagree, slightly. `Equals` should not be a remote call - it needs to be fast and it would be surprising to many if it did do a remote call. However, signing operations in my mind for any enterprise is going to be remote - its just a matter if the underlying presentation of it (CAPI, CNG, or HTTP) allow for it to be asynchronous.

>Or to make IDisposable have DIsposeAsync, for example.

Well, unless I misunderstood, that is a [current proposal](https://github.com/dotnet/csharplang/blob/master/proposals/async-streams.md#iasyncdisposable) that has decent traction.

>So, I'm not "opposed", I'm just "skeptical", and think that the line for when we put async overloads is a little further out than this.

That's fair. It would be nice to have async here, and more importantly, if the Core framework has no interesting in using the async APIs when possible, then they wouldn't provide much value.

**Comment by vcsjones** [comment]
After further consideration and the availability of some work arounds, I don't think this API proposal has merit anymore.

The utility of {Sign,Verify}Async methods on `AsymmetricAlgorithm` and friends depends on the framework using it themselves. I do not think this will happen.
