### ISSUE TITLE
System.Net.Http.Functional.Tests.ManagedHandler_HttpClientHandlerTest.GetAsync_ServerNeedsAuthAndNoCredential_StatusCodeUnauthorized failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#22642]
Failed test: System.Net.Http.Functional.Tests.ManagedHandler_HttpClientHandlerTest.GetAsync_ServerNeedsAuthAndNoCredential_StatusCodeUnauthorized 

Configuration: OuterLoop_netcoreapp_rhel7.2_debug

MESSAGE:
~~~
Assert.Equal() Failure\nExpected: 42\nActual: -117
~~~
STACK TRACE:
~~~
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() 
in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_rhel7.2_debug/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 175 
at System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_ServerNeedsAuthAndNoCredential_StatusCodeUnauthorized() 
in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_rhel7.2_debug/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs:line 433
~~~

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_rhel7.2_debug/121/testReport/System.Net.Http.Functional.Tests/ManagedHandler_HttpClientHandlerTest/GetAsync_ServerNeedsAuthAndNoCredential_StatusCodeUnauthorized/

**Comment by davidsh** [comment]
cc: @stephentoub 
ManagedHandler

**Comment by davidsh** [comment]
Closing this test issue for now.  This is usually the RemoteExecutor which previuosly had poor diagnostics when reporting errors.  That has been fixed.  So future failures in tests using RemoteExecutor will have more info.
