### ISSUE TITLE
Is it possible to package assemblies during build into individual packages i.e. System.Numerics

### ISSUE THREAD

**Issue by 4creators** [dotnet/corefx#22658]
Tried to find code which would allow to pack assemblies in a standard way and in addition each assembly individually - without success. Is it possible or do I have to create additional build code to get it done?

I need to get normal build output plus all assemblies packaged each in it's own NuGet package.

**Comment by karelz** [comment]
Are you asking about CoreFX build system or in general?
cc @weshaggard @ericstj

**Comment by ericstj** [comment]
The `build -allConfigurations` leg of the build produces packages.  Packages must be authored to be included in this leg, see the `.pkgproj` files in the repo for examples.

**Comment by 4creators** [comment]
@karelz My question was for CoreFX specifically but general answer regarding all repos participating in build for shipping version of .NET Core would very helpful. Essentially what I am looking for is to build complete shipping (private) version of .NET Core with fine granularity allowing for referencing individual assemblies or runtime.

**Comment by 4creators** [comment]
@ericstj 

> Packages must be authored to be included in this leg, see the .pkgproj files in the repo for examples.

My understanding is that I need to write .pkgproj or include packaging info in .csproj if this does not exists currently. Could you confirm that?

**Comment by weshaggard** [comment]
In corefx to create a library nuget package you need a pkgproj.
