### ISSUE TITLE
System.Net.Primitives Nuget is unusable

### ISSUE THREAD

**Issue by snpz** [dotnet/corefx#22655]
Hi.

I'm experiencing the following:
When I install System.Net.Primitives package via Nuget to my project, I get the following in the place, where the dlls should live.

![grafik](https://user-images.githubusercontent.com/30478030/28638972-d8c81c0a-7246-11e7-9bb2-41c7f43c0f9f.png)

Not any dll in there, installation does not raise an error.

**Comment by danmosemsft** [comment]
I'm guessing this is because in this TFM, the implementation is supposed to already exist - @weshaggard ?

**Comment by weshaggard** [comment]
That is called a placeholder file which allows nuget to install the package but when you reference or deploy it doesn't included any binaries because it should already exist on that platform (or those platforms in this case of a PCL target).
