### ISSUE TITLE
Memory overconsumption on SqlClient with MARS

### ISSUE THREAD

**Issue by ipinak** [dotnet/corefx#22661]
I have a simple web api application which connects to SQLServer with MARS enabled. I have noticed that the application consumes a lot of memory and never release any of it. However, when MARS is disabled everything works fine and memory is properly released. Memory increases constantly until it reaches the maximum physical limit, after that it starts writing on swap.

The same application works as expected on Windows. Actually on Windows memory consumption goes to **~300MB** and then stops increasing.

OS: **ubuntu 16.04** (and on docker)
dotnet version: **preview1-final**

**Comment by corivera** [comment]
What connection string options are you using besides MARS? And do you have any simple repro steps?

**Comment by jnm2** [comment]
(Off-topic: I've found that leaving MARS enabled leads to inefficient development practices. Also ran into http://www.freetds.org/mars.html.)

**Comment by ipinak** [comment]
@corivera  here is the connection string: `Data Source=some.source\\DB;Initial Catalog=TheCatalog;Persist Security Info=True;Trusted_Connection=True;Pooling=False;MultipleActiveResultSets=True;Connect Timeout=60;Encrypt=False;TrustServerCertificate=True;Integrated Security=SSPI;`

**Comment by ipinak** [comment]
@jnm2 thanks for the link!

**Comment by ipinak** [comment]
I have found this test `TestSqlAsyncMARS` inside `SqlClientTestGroup`, which I suppose if modified to execute more commands (e.g. 500), it can help replicate the issue.

**Comment by corivera** [comment]
Managed to repro the issue. Looking into it.

**Comment by corivera** [comment]
When connection pooling is disabled, the number of MARS connections in this file keep accumulating and are never disposed: https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNIMarsManager.cs#L16

Working on a fix.

**Comment by corivera** [comment]
@ipinak Looks like the workaround for this issue is to set Pooling=true

**Comment by ipinak** [comment]
Ok, I will try it out. Thank you!
Do you know on which version will this be released?
