### ISSUE TITLE
AssemblyName ctor throws on Core when version number does not have 4 parts - works on full Framework

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#22663]
This code succeeds on Desktop but throws on Core. Can we either make this work, or be more helpful?
```
Unhandled Exception: System.IO.FileLoadException: The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
   at System.Reflection.AssemblyName.nInit(RuntimeAssembly& assembly, Boolean forIntrospection, Boolean raiseResolveEvent)
   at System.Reflection.AssemblyName..ctor(String assemblyName)
   at ConsoleApp2.Program.Main(String[] args) in C:\dotnet.2\1\Program.cs:line 11
```

```c#
using System;
using System.Reflection;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            var assemblyName = new AssemblyName("asdfasdfa, Version=1.0, Culture=neutral, PublicKeyToken=null");
        }
    }
}
```

@morganbr is this expected?

**Comment by jnm2** [comment]
Oh boy, I can think of two projects offhand that will fail on Core. That had better be load and clear in the constructor's XML summary if it has to stay for some reason.

**Comment by danmosemsft** [comment]
@AtsushiKan ?

**Comment by AtsushiKan** [comment]
AssemblyNames on CoreCLR are parsed by the CoreCLR binder which demands that version numbers have all four parts: this is enforced here:

https://github.com/dotnet/coreclr/blob/5e82b75a22e9f1ee379beab45c2ddc6146132aab/src/binder/textualidentityparser.cpp#L382

I'd rather have the area owner for the CoreCLR binder figure out what to do about that - alternatively, we could force CoreCLR to use CoreRT's managed parser which doesn't have this restriction.

**Comment by jnm2** [comment]
Never mind, my uses specify full version or nothing.

**Comment by danmosemsft** [comment]
@kouvel are you the owner of the CoreCLR binder now, de facto? Or who is?

**Comment by danmosemsft** [comment]
Incidentally it would be nice if we could make this message ` The given assembly name or codebase was invalid.` more helpful.

**Comment by danmosemsft** [comment]
Putting into 2.0 for servicing consideration.

**Comment by kouvel** [comment]
> are you the owner of the CoreCLR binder now, de facto? Or who is?

Not that I'm aware of, and not sure if there is an owner, but I can take a look.

**Comment by danmosemsft** [comment]
This API has substantial usage, but we cannot say how often the version number does not have four parts.

**Comment by danmosemsft** [comment]
We should probably service for this.

**Comment by danmosemsft** [comment]
This is now fixed in master. We decided not to rush into servicing.
