### ISSUE TITLE
Add RandomNumberGenerator.GetBytes(Span)

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#22690]
Currently RandomNumberGenerator provides a GetBytes method that takes a byte[].  We should add one that takes a Span<byte>.
```C#
namespace System.Security.Cryptography
{
    public abstract class RandomNumberGenerator
    {
        public virtual void GetBytes(Span<byte> data);
        ...
    }
}
```
cc: @bartonjs

**Comment by bartonjs** [comment]
@stephentoub Did you mean to mark this one as ready-for-review, or approved?  I thought we reviewed this one already...

**Comment by stephentoub** [comment]
ready-for-review... I neglected to include this in the original list we reviewed (we reviewed Random, but not RandomNumberGenerator).
