### ISSUE TITLE
Random exceptions with System.Net.Http.WinHttpHandler

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#22697]
_From @hanabi1224 on July 27, 2017 18:34_

It randomly(at very low chance) throws 'An item with the same key has already been added.' when SendAsync being called, and same issue never happen after removing  WinHttpHandler
Package version: 4.3.1
.Net version: 4.6.2
OS: Azure guest OS 5-*
Http version: 2.0

_Copied from original issue: dotnet/coreclr#13086_

**Comment by davidsh** [comment]
@hanabi1224

Interesting bug report but there is no actionable information to debug this.

Can you please attach a call stack and/or process dump?

**Comment by hanabi1224** [comment]
@davidsh I can never repro it locally but if someone can pass me a debug build of System.Net.Http.WinHttpHandler I can help get stacktrace

**Comment by davidsh** [comment]
If you need a debug build of WinHttpHandler, you can build one by enlisting in the CoreFx repo and just building System.Net.Http.WinHttpHandler.

For now, I will close this bug until you're able to get a callstack or more actionable information.  Thanks.
