### ISSUE TITLE
Xml test case disabled on UAP needs to be reenabled on RS4

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#22705]
This is a Windows issue and will likely be fixed on RS4. It is related to frequently changing culture.
Converting this test case to use RemoteInvoke is significantly increasing test execution time (from seconds to minutes).

```
   at Windows.ApplicationModel.Resources.Core.ResourceContext.get_Languages()
   at System.Resources.WindowsRuntimeResourceManager.SetGlobalResourceContextDefaultCulture(CultureInfo ci)
   at System.Globalization.CultureInfo.set_CurrentCulture(CultureInfo value)
   at System.Xml.Tests.TCFullEndElement.TCWriteValue.writeValue_27(XmlWriterUtils utils, Int32 param, String sourceStr, String destStr, Boolean isValid, Object expVal)
```

_change is still pending in the PR_

**Comment by ViktorHofer** [comment]
The first RS4 build is already available: Windows 10 Build 16251 (rs_prerelease). Might the fix already be included there?

**Comment by krwq** [comment]
@ViktorHofer I do not see the repro on my box anymore at all (not sure if that was after syncing, luck or my Windows got updated), the CIs have consistent repro since they run on RS2

**Comment by ViktorHofer** [comment]
I see. We also have RS3 CIs, right? Is it failing for those too?

**Comment by krwq** [comment]
@ViktorHofer I think I didn't see RS3 but I'm not 100% sure, I think this should fail on RS3 as well - AFAIK Windows bug is not fixed yet. (There were actually two similar bugs around setting cultures frequently - for one of them @tarekgh has added a workaround on our side - this test case is hitting the other issue which we do not have any good workaround for)

**Comment by tarekgh** [comment]
@krwq my understanding you were going to fix the test to avoid such case. did you do that? 

Also if the issue consistently repro, could you please create a iDNA dump file we can look more at it and send it to the WinRT team? I was going to do that later as it was not a high priority. don't assume Windows has a fix in RS4.

**Comment by krwq** [comment]
@tarekgh it has stopped happening on my box after I rebased but still happening on the CI - I have converted it to use RemoteInvoke but since this case is a fairly large theory with hundreds of test cases it has increased the test runtime from seconds to minutes - I decided to disable that instead on UAP as it is not worth it
