### ISSUE TITLE
All 2.1.0 branches create Microsoft.NETCore.Platforms with the same fixed version

### ISSUE THREAD

**Issue by dagood** [dotnet/corefx#22713]
`master`, `release/uwp6.0`, and ~~`release/defaultintf`~~`dev/defaultintf` all produce `Microsoft.NETCore.Platforms 2.1.0-preview1-25324-02`:

[build-info/dotnet/corefx/master/Last_Build_Packages.txt#L2](https://github.com/dotnet/versions/blob/356894fb584a6a16010f894f7723176b18166dd9/build-info/dotnet/corefx/master/Last_Build_Packages.txt#L2)
[build-info/dotnet/corefx/release/uwp6.0/Last_Build_Packages.txt#L2](https://github.com/dotnet/versions/blob/356894fb584a6a16010f894f7723176b18166dd9/build-info/dotnet/corefx/release/uwp6.0/Last_Build_Packages.txt#L2)
[build-info/dotnet/corefx/dev/defaultintf/Last_Build_Packages.txt#L2](https://github.com/dotnet/versions/blob/356894fb584a6a16010f894f7723176b18166dd9/build-info/dotnet/corefx/dev/defaultintf/Last_Build_Packages.txt#L2)

This is making publish fail now that the package feed is set to forbid overwrites. (Even if only master were building, this version doesn't seem to correspond to the build and would still cause problems.)

It looks like this is because of [Microsoft.NETCore.Platforms.pkgproj#L6](https://github.com/dotnet/corefx/blob/c708a0af2550fc2aa4d246b8160588bda6060cdb/pkg/Microsoft.NETCore.Platforms/Microsoft.NETCore.Platforms.pkgproj#L6) using the `PlatformPackageVersion` from [dependencies.props#L24](https://github.com/dotnet/corefx/blob/c708a0af2550fc2aa4d246b8160588bda6060cdb/dependencies.props#L24), but I don't know the intent behind it. @weshaggard @ericstj ?

FYI @joshfree (release/uap6.0 impact)

**Comment by ericstj** [comment]
What's the versioning story for this branch?  Typically when we branch for release we'll assign some version of the packages and then increment master (either through version or pre-release string).  It looks like that wasn't done here.

I suspect that's because the UWP branch isn't expected to ship many of the packages.  In that case, perhaps you should just disable build of Microsoft.NETCore.Platforms and ensure that the branch's packageIndex is updated to use the stable 2.1.0 that was build from rel/2.0 branch.

I have no idea what `release/defaultintf` but it my gut feel is that this guy should disable all the packages that it isn't planning to ship, or give it self a unique version string...

**Comment by joshfree** [comment]
We discussed this with @ellismg before creating /release/uwp6.0 branches.  The intent was to use -preview1 for the release branch and -preview2 for master.  Looks like master was not bumped to preview2 properly

**Comment by joshfree** [comment]
@joperezr is going to assist per offline thread

**Comment by dagood** [comment]
(Typo'd in the description: `dev/defaultintf`, not `release/defaultintf`.)

This package looks like a weird special case because for some reason it's being treated as a dependency, but also building at the same version it depends on. Without very intentionally overwriting packages, this just doesn't make sense. (@joperezr See the pkgproj and dependencies.props I linked in the desc.)

**Comment by joperezr** [comment]
right, found the root cause. I'll put up a PR for master and then port it to the other two branches.

**Comment by joperezr** [comment]
fixed in all 3 branches.

**Comment by weshaggard** [comment]
@joperezr doesn't this also need to be fixed in master? Currently we are referencing the older version instead of the live version.

**Comment by joperezr** [comment]
@weshaggard PR https://github.com/dotnet/corefx/pull/22729 should have fixed this in master.

**Comment by weshaggard** [comment]
Don't we also need to update https://github.com/dotnet/corefx/blob/master/pkg/frameworkPackage.targets#L33? @ericstj?
