### ISSUE TITLE
Immutable Collections Validation namespace

### ISSUE THREAD

**Issue by sillyotter** [dotnet/corefx#2271]
The Immutable Collection code introduces a global Validation namespace that interferes with anything else named Validation that might be in the current scope.  For instance, a static class I had called Validation that was imported into a file.  As soon as I referenced Immutable, Validation namespace conflicted with Validation class.  

It would be nice if System.Collection.Immutable dint pollute the global namespace like that, and prefixed it with something to keep it from getting in the way.  Perhaps prefixing it with something.

**Comment by terrajobst** [comment]
Sorry -- didn't see this bug before. I've filed #2271 instead.
