### ISSUE TITLE
The release/1.1.0 branch produces old stable-versioned Compression packages

### ISSUE THREAD

**Issue by dagood** [dotnet/corefx#22721]
4.3.0 versions of `runtime.[non-windows].runtime.native.System.IO.Compression` are being produced and pushed to MyGet dotnet-core. ([build-info/dotnet/corefx/release/1.1.0/Latest_Packages.txt](https://github.com/dotnet/versions/blob/9ad683d7d73031d00f0d2a60d9ebc1feea57781f/build-info/dotnet/corefx/release/1.1.0/Latest_Packages.txt))

This is now causing build failures because overwriting is disabled on the MyGet feed. Right now, `runtime.debian.8-x64.runtime.native.system.io.compression.4.3.0.nupkg` has different contents on the NuGet gallery vs. the MyGet dev feed.

I think the package version upgrade was missed when enabling these packages to build during servicing. @weshaggard @ericstj

**Comment by ericstj** [comment]
@ianhays can you fix this?  I can't recall if you intended to not rebuild those x-plat packages (and should exclude them) or if you wanted to build them and increment the versions.

**Comment by ianhays** [comment]
Yeah, I'll fix this. We don't need to be pushing new versions of the non-windows packages.

**Comment by ianhays** [comment]
resolved by https://github.com/dotnet/corefx/pull/22733
