### ISSUE TITLE
HttpClient test SendAsync_RequestVersion20_ResponseVersion20 fails

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#22735]
See discussion in PR #22702:

Outerloop tests for .NET Core and UWP are failing on this test:
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/16/

>SendAsync_RequestVersion20_ResponseVersion20(server: https://www.microsoft.com/)

It looks like the www.microsoft.com server is not using HTTP/2.0 protocol today. Our tests assume that this server always uses HTTP/2 protocol. Don't know if this is temporary problem. We might need to switch to a different HTTP/2 test server. I also confirmed using the Chrome browser that www.microsoft.com is not using HTTP/2.

**Comment by davidsh** [comment]
cc: @stephentoub 

I will push a commit to my active PR #22702 to disable this test for now.

**Comment by CIPop** [comment]
We could use https://http2.akamai.com  instead maybe?

**Comment by davidsh** [comment]
>We could use https://http2.akamai.com instead maybe?

Yes. We can submit a PR to re-enable this test and change the http/2 test server after #22702 gets merged

**Comment by Jiayili1** [comment]
Failed again on UWP6.0 branch, detail: https://mc.dot.net/#/product/netcore/uwp60/source/official~2Fcorefx~2Frelease~2Fuwp6.0~2F/type/test~2Ffunctional~2Filc~2F/build/20170729.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandlerTest~2FSendAsync_RequestVersion20_ResponseVersion20(server:%20https:~2F~2Fwww.microsoft.com~2F)

**Comment by davidsh** [comment]
This failure in UWP6.0 branch is now fixed as of PR https://github.com/dotnet/corefx/pull/22759 which disabled the test in the release/uwp6.0 branch.
