### ISSUE TITLE
Unix Path.NormalizePath acquires StringBuilder but never releases it.

### ISSUE THREAD

**Issue by AustinWise** [dotnet/corefx#2275]
In this file:
[src\System.Runtime.Extensions\src\System\IO\Path.Unix.cs](https://github.com/dotnet/corefx/blob/7938a0e9264f4fbbe3fa5638494387b08444f383/src/System.Runtime.Extensions/src/System/IO/Path.Unix.cs)
the NormalizePath method uses StringBuilderCache to acquire a StringBuilder, however the StringBuilder is never released back to the cache.

**Comment by stephentoub** [comment]
Good catch.
