### ISSUE TITLE
TextEncoder misses last BMP character after surrogate pair

### ISSUE THREAD

**Issue by miloush** [dotnet/corefx#22755]
**Version:** 2.0.0-preview2-final
```C#
string url = System.Text.Encodings.Web.UrlEncoder.Default.Encode("𐌺X");
string html = System.Text.Encodings.Web.HtmlEncoder.Default.Encode("𐌺X");
string js = System.Text.Encodings.Web.JavaScriptEncoder.Default.Encode("𐌺X");
```
**Expected:**
```
url  = "%F0%90%8C%BAX"
html = "&#x1033A;X"
js   = "\uD800\uDF3AX"
```
**Actual:**
```
url  = "%F0%90%8C%BA"
html = "&#x1033A;"
js   = "\uD800\uDF3A"
```

**Comment by miloush** [comment]
I would find this blocking for ASP.NET Core release.

In [EncodeIntoBuffer](https://github.com/dotnet/corefx/blob/f462fa1e1f9dc3b7d297c856e8585ee2c4e2a2fc/src/System.Text.Encodings.Web/src/System/Text/Encodings/Web/TextEncoder.cs#L127) the condition of `if (!wasSurrogatePair)` final block does not make sense, it's irrelevant whether the previous character was a surrogate pair or not, this block is meant to process remaining odd character, so it should test for that instead, e.g.:
```C#
private unsafe int EncodeIntoBuffer(char* buffer, int bufferLength, char* value, 
                                    int valueLength, int firstCharacterToEncode)
{
     ...
    // this loop processes character pairs (in case they are surrogates).
    // there is an if block below to process single last character.
    int secondCharIndex;
    for (secondCharIndex = valueIndex + 1; secondCharIndex < valueLength; secondCharIndex++)
    {
        ...
    }

    if (secondCharIndex == valueLength) // was if (!wasSurrogatePair)
    {
        ...
    }

    return totalWritten;
}

**Comment by svick** [comment]
@miloush If you know how to fix it, why don't you create a PR?

**Comment by miloush** [comment]
@svick Because I haven't done that before, thought issues should be discussed first, suspected that declaring the iteration variable out of a the loop might not be the preferred solution, don't have the build environment set up, expected I would be asked to write tests for that which I don't have any experience with either and feared it would take me much more time than someone doing this on daily basis.

I do care though about this issue being fixed though, so here is my attempt. Thanks for prompting me.
