### ISSUE TITLE
Serialization test case DCS_BasicPerSerializerRoundTripAndCompare_Collections_FailedInuapaot_InCollections failed when targeting uapaot

### ISSUE THREAD

**Issue by JimboWei** [dotnet/corefx#22779]
This case is a part of test case DCS_BasicPerSerializerRoundTripAndCompare_Collections , it failed when **targeting `uapaot`** , so we move these scenarios into a new case.

**Detail** : the class in these scenarios has **DataMember attribute decorate Collections type** ,has different result with baseline when serialization.

**Baseline** : … <List2 i:type=\"b:System.Collections.Generic.List`1[[SerializationTestTypes.SimpleDC, System.Runtime.Serialization.Xml.Tests, Version=4.1.4.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb]]\" xmlns:b=\"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\"><SimpleDC z:Ref=\"i2\"/><SimpleDC z:Ref=\"i6\"/></List2>…

**Actual**: …<List2><SimpleDC z:Ref=\"i2\"/><SimpleDC z:Ref=\"i6\"/></List2>…

**Missing assembly information of the List**.

**Comment by shmao** [comment]
This was caused by a bug in `XmlObjectSerializerWriteContext.SerializeWithXsiType`. The method used `DataContract.TypeIsInterface` which was supposed to be populated at app startup by UWP toolchain. For DataContract created at runtime, however, the field, `TypeIsInterface`, was never set.
