### ISSUE TITLE
Roslyn Error MSB3883: Unexpected exception:  when build is run

### ISSUE THREAD

**Issue by D383125** [dotnet/corefx#22775]
Hi,
Im having problems building corefx, using build-managed.  When the ..\corefx\Tools\net46\roslyn\tools\Microsoft.CSharp.Core.targets(72,5)  file is loaded, a series of 
"System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified" are thrown.  Each of the files reported missing are present and the VS command-prompt is run with Administrator privileges.  See below for csc command and output.  Enviroment is:
OS: Win 10 Pro	10.0.14393 Build 14393
VS: 15.2 (26430.16) Release
Visual C# Compiler version 2.2.0.61624

Thanks
Brian

24>CoreCompile:
         C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /warn:4 /define:DEBUG;TRACE;DEBUGRESOURCES;SIGNED /reference:"D:\Development\C#\Forked\corefx\bin/ref/netstandard/netstandard.dll" /debug+ /debug:full /delaysign+ /keyfile:"D:\Development\C#\Forked\corefx\Tools/MSFT.snk" /optimize- /out:"D:\Development\C#\Forked\corefx\bin/obj/ref/Microsoft.VisualBasic/10.0.0.0/netstandard/Microsoft.VisualBasic.dll" /ruleset:"D:\Development\C#\Forked\corefx\CodeAnalysis.ruleset" /target:library /warnaserror+ /utf8output /analyzer:"D:\Development\C#\Forked\corefx\Tools/net46/analyzers/Microsoft.DotNet.CodeAnalysis.dll" Microsoft.VisualBasic.cs "D:\Development\C#\Forked\corefx\bin/obj/ref/Microsoft.VisualBasic/10.0.0.0/netstandard/_AssemblyInfo.cs" "D:\Development\C#\Forked\corefx\Tools\/BlockReflectionAttribute.cs" @"D:\Development\C#\Forked\corefx\Tools\checksum.rsp"
         Using shared compilation with compiler from directory: D:\Development
    24>D:\Development\C#\Forked\corefx\Tools\net46\roslyn\tools\Microsoft.CSharp.Core.targets(72,5): error MSB3883: Unexpected exception:  [D:\Development\C#\Forked\corefx\src\Microsoft.VisualBasic\ref\Microsoft.VisualBasic.csproj]
    23>CoreCompile:
         Using shared compilation with compiler from directory: D:\Development
    24>D:\Development\C#\Forked\corefx\Tools\net46\roslyn\tools\Microsoft.CSharp.Core.targets(72,5): error : System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified [D:\Development\C#\Forked\corefx\src\Microsoft.VisualBasic\ref\Microsoft.VisualBasic.csproj]
    24>D:\Development\C#\Forked\corefx\Tools\net46\roslyn\tools\Microsoft.CSharp.Core.targets(72,5): error : at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo) [D:\Development\C#\Forked\corefx\src\Microsoft.VisualBasic\ref\Microsoft.VisualBasic.csproj]
    24>D:\Development\C#\Forked\corefx\Tools\net46\roslyn\tools\Microsoft.CSharp.Core.targets(72,5): error : at System.Diagnostics.Process.Start() [D:\Development\C#\Forked\corefx\src\Microsoft.VisualBasic\ref\Microsoft.VisualBasic.csproj]
    24>D:\Development\C#\Forked\corefx\Tools\net46\roslyn\tools\Microsoft.CSharp.Core.targets(72,5): error : at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [D:\Development\C#\Forked\corefx\src\Microsoft.VisualBasic\ref\Microsoft.VisualBasic.csproj]
    24>D:\Development\C#\Forked\corefx\Tools\net46\roslyn\tools\Microsoft.CSharp.Core.targets(72,5): error : at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.HandleResponse(BuildResponse response, String pathToTool, String responseFileCommands, String commandLineCommands) [D:\Development\C#\Forked\corefx\src\Microsoft.VisualBasic\ref\Microsoft.VisualBasic.csproj]
    24>D:\Development\C#\Forked\corefx\Tools\net46\roslyn\tools\Microsoft.CSharp.Core.targets(72,5): error : at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [D:\Development\C#\Forked\corefx\src\Microsoft.VisualBasic\ref\Microsoft.VisualBasic.csproj]
    24>Done Building Project "D:\Development\C#\Forked\corefx\src\Microsoft.VisualBasic\ref\Microsoft.VisualBasic.csproj" (Build target(s)) -- FAILED.

**Comment by pjanotti** [comment]
@D383125 thanks for reporting the issue. I could reproduce the issue and workaround it by renaming the folder `C#` to `CSharp`.  I updated the instructions at https://github.com/dotnet/corefx/wiki/Checking-out-the-code-repository to reflect this issue.

**Comment by D383125** [comment]
Thanks pjanotti :o)
