### ISSUE TITLE
Serialization test case DCS_BasicPerSerializerRoundTripAndCompare_SampleTypes_FailedInuapaot_InheritedFromIList failed when targeting uapaot

### ISSUE THREAD

**Issue by JimboWei** [dotnet/corefx#22777]
This case is a part of test case DCS_BasicPerSerializerRoundTripAndCompare_SampleTypes , it failed when **targeting `uapaot `**, so we move these scenarios into a new case.

**Detail** : the class in these scenarios  inherit from **IList**  will fail when serialization.

**Error Message** : System.Runtime.Serialization.InvalidDataContractException : Collection type 'SerializationTestTypes.SampleListTExplicitWithoutDC' does not have a valid Add method.

**Note** : I checked the test classes they already implement interface explicitly and have a method named **`ICollection<..>.Add`**.

**Comment by shmao** [comment]
In the test scenario, UWP toolchain won't pre-generate serializer for the type. Therefore, at runtime the serializer would use reflection based serialization which reuqires metadata of IList.
