### ISSUE TITLE
Converge root scripts for Unix and Windows

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#22786]
This is intended to be more a question than an issue. Currently we have to the following scripts with each two flavors for Unix and Windows:
- build-managed
- build-native
- build-packages
- build-tests
- build
- clean
- init-tools
- publish-packages
- (run-test.sh)
- run
- sync

Are there any plans to converge them? If yes, will we use the dotnet-cli for that? If not, what about using cross-platform powershell scripts?

@weshaggard @ericstj

**Comment by Clockwork-Muse** [comment]
...doesn't windows support shell scripts now, too (hey I'm more a windows guy, so approach things from that end, but still....)?

**Comment by weshaggard** [comment]
cc @dleeapho @markwilkie

>Are there any plans to converge them? If yes, will we use the dotnet-cli for that? If not, what about using cross-platform powershell scripts?

Unfortunately there isn't any good thing to converge them on that will work on all the places we need to build. If you look at the scripts our goal is to keep them simple and get into our build engine as quickly as possible and let it do most of the heavy lifting. 

For now I believe using cmd/ps on windows and sh on unix are our best options without introducing more dependencies in our repo. 

That said I expect we will likely reduce and/or move some of these scripts out of the root of the repo and under a sub-directory as part of some upcoming engineering work.

**Comment by ViktorHofer** [comment]
I understand the need to use a common lightweight build scripts for various projects. Wouldn't that be possible with cross-platform and still slim ps1s? Is taking a dev-dependency on powershell (opensource version) too much of an issue/blocker?

That the root of the repo will be cleanup in a future PR is definitely a step forward 👍

**Comment by mellinoe** [comment]
Taking a dependency on PowerShell is not that different in theory from the current "run tool", which is a managed app that runs on our toolset. But PowerShell is vastly more complicated, and considerably larger, than run.exe. Also, I think we want to phase out the usage of run.exe for a variety of reasons.

**Comment by weshaggard** [comment]
Another thing to keep in mind is that we need to ensure that we can build the native assets without the need for any managed code to execute otherwise we will have a bootstrapping issue for any new platform (distro, new arch etc) we want to start building on.

**Comment by ViktorHofer** [comment]
> build the native assets without the need for any managed code to execute

That means Powershell Core isn't an option as it targets .NET Core (you could also target .NET Framework but obviously that would then limit the runnable platforms). 
I think Powershell Core would really have made sense as it _the_ cross platform scripting language pushed by Microsoft and if something would have been missing we could have just submitted a PR.

**Comment by weshaggard** [comment]
>That means Powershell Core isn't an option as it targets .NET Core (you could also target .NET Framework but obviously that would then limit the runnable platforms).

Exactly that is why it isn't really a good option. We have to be able to bootstrap new platforms that cannot run .NET code yet.

**Comment by dleeapho** [comment]
> For now I believe using cmd/ps on windows and sh on unix are our best options without introducing more dependencies in our repo.

I agree the current scheme is our best option. Even that duplicates effort and doubles the potential fragility so getting to some lightweight xplat scripting would be goodness.
