### ISSUE TITLE
Rename Validation to Microsoft.Internal.Validation

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#2278]
The C# (and possibly VB compiler) will match the top-level namespace `Validation` in `System.Collections.Immutable` even though it only contains internal types. This prevents customers from using a type named `Validation` in their code. Specifically, assume a customer has defined the type like this:

```C#
namespace Support
{
    public static class Validation
    {
	    public static bool IsValid(string x) { return true; }
    }
}
```
Consuming this type stops working when `System.Collections.Immutable` is referenced:

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Support;

namespace ImmutableTest
{
    public class Experiment
    {
        // With out Immutable included, the below works just fine.
        // Once I include immutable, Validation, which was really
        // Support.Validation, but was found because of the using
        // statement above, it starts to fail showing that it can't
        // find IsValid in the namespace Validation.
	public void Test1() { Validation.IsValid("AS"); }
	public void Test2() { Support.Validation.IsValid("AS"); }
    }
}
```

According to @jaredpar this behavior is by-design:

> This behavior is by design for C# at least.  A simple name lookup will prefer matching namespaces over types (section 7.5.2).   I didn’t check the VB spec but it almost assuredly has the same design here.  

In order to avoid that conflict, we should rename the `Validation` namespace to something like `System.Validation`.

**Comment by terrajobst** [comment]
@jaredpar Hmm, is `System.Validation` gonna work if people have a using for `System`?

**Comment by AArnott** [comment]
@terrajobst Jared recommended we use the namespace `Microsoft.Internal`. That seems like it should work for our purposes in this library.

**Comment by terrajobst** [comment]
Giving it more thought: we should probably not have any internal only namespaces. So we could either:

1. Move internal types into the global namespace
2. Or use an existing public namespace

**Comment by jaredpar** [comment]
@AArnott to clarify. I wasn't necessarily recommending that, it is just a pattern I had observed in the past.  

@terrajobst IMHO the second option is the better one.

**Comment by bbarry** [comment]
> We should probably not have any internal only namespaces. 

I think this should be in the framework design guidelines. Nobody should have internal only namespaces.

**Comment by AArnott** [comment]
> Nobody should have internal only namespaces

That might be a tall order, @bbarry. I know a lot of assemblies share code between each other (for error handling, etc.) and do so with internal types of course. But because the namespaces of each assembly may be distinct, what namespace would these shared internal types belong to?
