### ISSUE TITLE
System.Net.Sockets.SendPacketsElement should have Int64 offset

### ISSUE THREAD

**Issue by kurtschelfthout** [dotnet/corefx#22796]
# Latest Proposal

```c#
public partial class SendPacketsElement
{
    // Existing APIs
    public SendPacketsElement(string filepath, int offset, int count) { }
    public SendPacketsElement(string filepath, int offset, int count, bool endOfPacket) { }
    public int Offset { get; }

    // New APIs:
    public SendPacketsElement(string filepath, long offset, int count) { }
    public SendPacketsElement(string filepath, long offset, int count, bool endOfPacket) { }
    public long OffsetLong { get; } 
}
```

# Original Proposal

The [_offset field](https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/SendPacketsElement.cs#L12) in SendPacketsElement defines the offset to start sending from, in the byte buffer or the filename. In the former case an `int` is fine, but in the latter it would be great to allow  `int64` to allow offsets beyond the 2Gb mark in large files.

The winsock API accepts an int64 too: https://github.com/dotnet/corefx/blob/master/src/Common/src/Interop/Windows/Winsock/Interop.WinsockAsync.cs#L70 and https://msdn.microsoft.com/en-us/library/windows/desktop/ms740570(v=vs.85).aspx

In case the offset means an offset in a byte buffer, there is validation in place already to check that the offset is not out of bounds.

Perhaps it is enough to make the field into an `int64` and add another constructor overload taking a filename and `int64` offset.

**Comment by kurtschelfthout** [comment]
How about the following API.

```csharp
    public partial class SendPacketsElement
    {
        // existing API - ctors
        public SendPacketsElement(byte[] buffer) { }
        public SendPacketsElement(byte[] buffer, int offset, int count) { }
        public SendPacketsElement(byte[] buffer, int offset, int count, bool endOfPacket) { }
        public SendPacketsElement(string filepath) { }
        public SendPacketsElement(string filepath, int offset, int count) { }
        public SendPacketsElement(string filepath, int offset, int count, bool endOfPacket) { }

        // proposed API - ctors
        public SendPacketsElement(string filepath, long offset, int count) { }
        public SendPacketsElement(string filepath, long offset, int count, bool endOfPacket) { }

        // existing API - properties
        public byte[] Buffer { get { throw null; } }
        public int Count { get { throw null; } }
        public bool EndOfPacket { get { throw null; } }
        public string FilePath { get { throw null; } }
        public int Offset { get { throw null; } }

        // proposed API - property
        public long FileOffset { get; } 
    }
```
Assuming backwards compatibility is important (though I doubt this API is frequently used), `Offset` still returns the offset if it fits into an `int`, even if one of the new ctors is used with a `long` offset, and throws if the offset exceeds `int.MaxValue`.

**Comment by karelz** [comment]
Just curious if you found it by trying to send parts of large (2GB+) file. Can you please confirm?

We may need to rename `FileOffset` to `OffsetLong`, the API reviewers will have general guidance I hope.
Marking for API review.

**Comment by karelz** [comment]
Top post updated with API proposal

**Comment by kurtschelfthout** [comment]
> Just curious if you found it by trying to send parts of large (2GB+) file. Can you please confirm?

Yes, that is exactly my use case. We have a file server which serves columns/blocks from data files which are witten in a columnar data format. The header gives us the offsets in the (potentially 2Gb+) file of the columns and the blocks of data in the columns. Clients ask for a set of columns/blocks which translates to a set of chunks of the file that the server needs to send to the client over the socket connection.

> We may need to rename FileOffset to OffsetLong, the API reviewers will have general guidance I hope.

Sure. I added the File prefix because this offset can only be used with files, not with byte arrays.

**Comment by terrajobst** [comment]
Given #25354 it seems we should look at this API holistically. I've commented there.
