### ISSUE TITLE
Does SortedSet.UnionWith need to optimize for another SortedSet?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#22809]
Hi, I'm in the middle of trying to clean up the `SortedSet` code. Over [here](https://github.com/jamesqo/corefx/blob/9f892eb60e68916d24670190ecc070eb22b6973e/src/System.Collections/src/System/Collections/Generic/SortedSet.cs#L927-L989), in both `UnionWith` and `IntersectWith`, there is a huge 60-line block of code that checks if the other enumerable is a `SortedSet<T>` and if so does a mergesort on it, all inline. I'm wondering why this optimization was added in the first place: is it a common case to call `UnionWith` with a `SortedSet<T>`? And were there perf problems with a naive implementation like

```cs
foreach (T item in other) { Add(item); }
```

?

I checked the earliest version of `SortedSet.cs` on the [referencesource repo](https://github.com/Microsoft/referencesource/blob/9da503f9ef21e8d1f2905c78d4e3e5cbb3d6f85a/System/compmod/system/collections/generic/sortedset.cs#L1005), and the optimization was still there. If possible, can a maintainer with access to the TFS history please go back and see why it was added?

/cc @ianhays @safern

**Comment by jamesqo** [comment]
Similarly things like this seem silly: https://github.com/jamesqo/corefx/blob/9f892eb60e68916d24670190ecc070eb22b6973e/src/System.Collections/src/System/Collections/Generic/SortedSet.cs#L1303-L1307. I can't imagine that would be driven by a real perf problem...

**Comment by benaadams** [comment]
I assume you mean the inlined algo rather than the casting (to avoid enumerator boxing)? 

e.g. writing [2 naive specific functions](https://github.com/NuGet/NuGet.Client/blob/53fee133b29200bf24423247a25d6a7a39b02c9c/src/NuGet.Core/NuGet.Frameworks/FrameworkNameProvider.cs#L1150-L1175) for `HashSet` that took a `HashSet` for `SetEquals` and `UnionWith` saves 194MB of allocations during a NuGet restore of Rosyln https://github.com/NuGet/NuGet.Client/pull/1594 - interestingly `SetEquals` does as convert to `HashSet`, but then boxes the enumerator though the private method `ContainsAllElements`

Was thinking of raising issue for `HashSet` and `SortedSet` where they didn't deal with their own types specifically.

**Comment by benaadams** [comment]
> And were there perf problems with a naive implementation like

I'd assume if you were adding two large sorted sets together adding items one by one would cause an issue? As  [Add is quite a chunky function](https://github.com/jamesqo/corefx/blob/9f892eb60e68916d24670190ecc070eb22b6973e/src/System.Collections/src/System/Collections/Generic/SortedSet.cs#L315-L393) by itself.

**Comment by jamesqo** [comment]
@benaadams 

> e.g. writing 2 naive specific functions for HashSet that took a HashSet for SetEquals and UnionWith saves 194MB of allocations during a NuGet restore of Rosyln NuGet/NuGet.Client#1594 - interestingly SetEquals does as convert to HashSet, but then boxes the enumerator though the private method ContainsAllElements

That's interesting, so `HashSet<>` is actually lacking optimizations in this area you seem to be saying.

> Was thinking of raising issue for HashSet and SortedSet where they didn't deal with their own types specifically.

Have you seen any cases where `SortedSet` (not `HashSet`) not specializing for itself created a performance problem? From what I've seen the type looks quite slow/allocation-heavy (e.g. node allocated for each item) anyway, so I can't imagine a few more boxed enumerators would make much of a difference.

**Comment by stephentoub** [comment]
Closing as a question asked and answered.
