### ISSUE TITLE
Add tests to System.Data.DataSetExtensions and create pkgproj

### ISSUE THREAD

**Issue by nchikanov** [dotnet/corefx#22803]
Recently ported System.Data.DataSetExtensions to Core (see #22669)

Still need to add relevant tests to ensure full coverage, and later create a package.

**Comment by hughbe** [comment]
Are the tests up for grabs? No problem if not

**Comment by nchikanov** [comment]
@hughbe Not at the moment, will let you know if anything changes 👍
