### ISSUE TITLE
Test failure: System.Net.Sockets.Tests.SendReceiveSync / Receive0ByteReturns_WhenPeerDisconnects

### ISSUE THREAD

**Issue by KristinXie1** [dotnet/corefx#22814]
## History of failures

Day | Build | OS
-- | -- | --
7/11 | 20170711.03 | Win10
7/15 | 20170715.02 | Win8.1
7/23 | 20170723.01 | Win7
9/16 | 20170916.02 | Win10
9/17 | 20170917.01 | Win10
11/4 | 20171104.02 | Win10
11/16 | 20171116.01 | Win8.1

# Original report

Failed test: System.Net.Sockets.Tests.SendReceiveSync.Receive0ByteReturns_WhenPeerDisconnects 
Configuration: OuterLoop_netcoreapp_windows_nt_release

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_release/122/testReport/System.Net.Sockets.Tests/SendReceiveSync/Receive0ByteReturns_WhenPeerDisconnects/

MESSAGE:
~~~
System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host
~~~
STACK TRACE:
~~~
at System.Net.Sockets.Tests.SendReceiveSync.<>c__DisplayClass3_0.<ReceiveAsync>b__0() 
in D:\j\workspace\outerloop_net---7a39cc82\src\System.Net.Sockets\tests\FunctionalTests\SendReceive.cs:line 1025 
at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) 
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Net.Sockets.Tests.SendReceive.<Receive0ByteReturns_WhenPeerDisconnects>d__27.MoveNext() 
in D:\j\workspace\outerloop_net---7a39cc82\src\System.Net.Sockets\tests\FunctionalTests\SendReceive.cs:line 726 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
~~~

**Comment by Jiayili1** [comment]
Failed again: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_release/125/testReport/System.Net.Sockets.Tests/SendReceiveSync/Receive0ByteReturns_WhenPeerDisconnects/

**Comment by Jiayili1** [comment]
failed again in CI: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_debug/142/testReport/System.Net.Sockets.Tests/SendReceiveSync/Receive0ByteReturns_WhenPeerDisconnects/

**Comment by Jiayili1** [comment]
This issue is repro in OuterLoop_netcoreapp_windows_nt_debug, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_debug/165/testReport/System.Net.Sockets.Tests/SendReceiveSync/Receive0ByteReturns_WhenPeerDisconnects/

**Comment by Jiayili1** [comment]
failed again in CI: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_debug/167/testReport/System.Net.Sockets.Tests/SendReceiveSync/Receive0ByteReturns_WhenPeerDisconnects/

**Comment by Sunny-pu** [comment]
failed again in CI:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_debug/209/testReport/System.Net.Sockets.Tests/SendReceiveSync/Receive0ByteReturns_WhenPeerDisconnects/

**Comment by Sunny-pu** [comment]
failed again in master branch:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171116.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendReceiveSync~2FReceive0ByteReturns_WhenPeerDisconnects

**Comment by karelz** [comment]
Updated history of failures in top post.

**Comment by wfurt** [comment]
One failure in last 180 days: 2018-11-10 on Windows Nano

**Comment by karelz** [comment]
Does not seem to be a problem anymore. Please open new issue if it happens again.
