### ISSUE TITLE
Please provide a weak reference version of ArrayPool

### ISSUE THREAD

**Issue by ygc369** [dotnet/corefx#22813]
This kind of WeakArrayPool should only hold the weak reference of every array, so the arrays in the pool could be collected by GC, and could be reused before GC. It would be a self-balanced array cache mechanism.

**Comment by ygc369** [comment]
> I thought that ArrayPool already has reasonable aging & releasing algorithm.

Are you sure? What's that algorithm? What if it does not have?

**Comment by stephentoub** [comment]
Weak references generally are not a good approach for this kind of pool.  You often end up both with lots of arrays getting promoted to gen1 or gen2 and then getting dropped, making for very expensive collections, and with lots of arrays never getting reused, such that the pool provides little benefit.

**Comment by ygc369** [comment]
@stephentoub 
>You often end up both with lots of arrays getting promoted to gen1 or gen2 and then getting dropped, making for very expensive collections.

I don't think so. Why would lots of arrays get promoted to gen1 or gen2 even if they didn't get reused?
The weak reference pool only holds weak references of arrays, so it would not impact GC.

>and with lots of arrays never getting reused

Even if this happened, it would not be worse then not using any pool. 
Imagine that  an app frequently discards old arrays and allocates new ones in a process, many arrays would get reused before GC if they were managed by weak reference pool. When the process finishes, these arrays would get collected by next GC. But if you use the current ArrayPool and forget to dispose it after using, there would be memory leak.

**Comment by stephentoub** [comment]
> I don't think so. Why would lots of arrays get promoted to gen1 or gen2 even if they didn't get reused? The weak reference pool only holds weak references of arrays, so it would not impact GC.

If arrays aren't getting reused at all, there's no point in having a pool at all.  If arrays are getting reused, then they're likely going to be surviving GCs, and then a GC occurs that would cause the weak references to be dropped for any in the pool, they will have been promoted to higher generations.

**Comment by stephentoub** [comment]
> Even if this happened, it would not be worse then not using any pool.

Sure it would.  Weak references cost something.  Using a pool costs something.

**Comment by ygc369** [comment]
>If arrays aren't getting reused at all, there's no point in having a pool at all. If arrays are getting reused, then they're likely going to be surviving GCs, and then a GC occurs that would cause the weak references to be dropped for any in the pool, they will have been promoted to higher generations.

The problem is that sometimes we can't know whether arrays would be reused. We only know that they may be reused. If we don't use any pool, we must allocate new arrays once needing, even before GC, while there're "free" arrays to reuse. If we use the current ArrayPool, there would be memory waste or even memory leak if we don't use any arrays later. If we could have weak reference pool, we would be able to balance these two situations.

For example, an app uses a complex algorithm which needs a lot of arrays as temporary buffers. The app may run this algorithm only once or many times, depending on different situations, such as different user inputs. So we can't know whether these arrays would be reused ahead of time. So it is hard for me to decide whether to use an ArrayPool, but if there was a weak reference array pool, I would use it with no doubt.

**Comment by stephentoub** [comment]
I understand the concerns.  My point is that I don't believe just having a weak array pool is the way to address it.  It would be better to address it via https://github.com/dotnet/coreclr/issues/7747.

**Comment by ygc369** [comment]
@stephentoub 
Oh yes, that's a better solution.

**Comment by qbit86** [comment]
@ygc369 You can have outer weak reference to your own `ArrayPool<T>` instance, instead of weak references to individual inner buffers/buckets.

Off topic: Is there any `List<T>` reimplementation via `ArrayPool<T>`?
