### ISSUE TITLE
Deserialization of Claim blows up, if Properties was set

### ISSUE THREAD

**Issue by jan-johansson-mr** [dotnet/corefx#22818]
The following code snippet causes the de-serialization of [serialized] claim to blow up:

```c#
        private static void T_22()
        {
                var c2 = new Claim(ClaimTypes.Actor, "Test", ClaimValueTypes.String, "Test", "Test");

                c2.Properties["Prop1"] = "Value1";
                c2.Properties["Prop2"] = "Value2";

                var b0 = T_22_Encode((stream, writer) => {
                        c2.WriteTo(writer);
                        writer.Flush();
                        return stream.ToArray();
                });

                var y0 = T_22_Decode(b0, reader => new Claim(reader));
        }

        private static byte[] T_22_Encode(Func<MemoryStream, BinaryWriter, byte[]> func)
        {
                using (var m0 = new MemoryStream())
                using (var w0 = new BinaryWriter(m0))
                        return func.Invoke(m0, w0);
        }

        private static T T_22_Decode<T>(byte[] encoded, Func<BinaryReader, T> func)
                where T : class
        {
                using (var m0 = new MemoryStream(encoded))
                using (var r0 = new BinaryReader(m0))
                        return func.Invoke(r0);
        }
```

With the following exception:

```
System.IO.EndOfStreamException occurred
  HResult=0x80070026
  Message=Unable to read beyond the end of the stream.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at System.Security.Claims.Claim..ctor(BinaryReader reader, ClaimsIdentity subject)
   at System.Security.Claims.ClaimsIdentity.CreateClaim(BinaryReader reader)
   at System.Security.Claims.ClaimsIdentity.Initialize(BinaryReader reader)
   at System.Security.Claims.ClaimsIdentity..ctor(BinaryReader reader)
   at System.Security.Claims.ClaimsPrincipal.CreateClaimsIdentity(BinaryReader reader)
   at System.Security.Claims.ClaimsPrincipal..ctor(BinaryReader reader)
```

There is no issue if the properties are not used.

[EDIT] Fixed code markdown by @karelz

**Comment by karelz** [comment]
Which .NET Core version did you use? 2.0 preview? Or older?
cc @ianhays

**Comment by jan-johansson-mr** [comment]
Hi,

I'm using the latest and greatest :-) That is the 2.0 version.

2017-08-01 14:40 GMT+02:00 Karel Zikmund <notifications@github.com>:

**Comment by danmosemsft** [comment]
@viktorhofer

**Comment by ViktorHofer** [comment]
Could be related to my code changes yesterday. Will look at it later.

**Comment by jan-johansson-mr** [comment]
Thanks! :-)

2017-08-01 16:55 GMT+02:00 Viktor Hofer <notifications@github.com>:

**Comment by ViktorHofer** [comment]
Jan, so you mean the 2.0 nightly build version from master? Or a preview version?

**Comment by jan-johansson-mr** [comment]
Hi,

I'm working with the preview [2.0.0-preview2-006497], so I guess what I see
has been there for a while.

2017-08-01 18:09 GMT+02:00 Viktor Hofer <notifications@github.com>:

**Comment by ViktorHofer** [comment]
Thanks, that verifies that the error isn't connected to my latest change. I will now test it locally. I guess it's connected to the fact that we removed the serialization attribute from these types.

**Comment by ViktorHofer** [comment]
The mentioned behavior is indeed broken and presents a production issue for 2.0. The constructor of System.Security.Claims.Claim which accepts a BinaryReader seems either reading too much from the stream or the function System.Security.Claims.Claim.WriteTo(BinaryWriter) writes too much into the stream.

I will check that latter (currently on an event).

**Comment by jan-johansson-mr** [comment]
Thanks for feedback!

2017-08-01 20:14 GMT+02:00 Viktor Hofer <notifications@github.com>:

**Comment by bbowyersmyth** [comment]
@ViktorHofer Looks to be a pre-existing bug. Reading `Properties` is not advancing `numPropertiesRead`

**Comment by ViktorHofer** [comment]
It also repros on .NET Framework 4.7 which also has the new Claim overloads. Unfortunately our test coverage for `System.Security.Claims.Claim` is very poor therefore we haven't detected that issue.

**Comment by jan-johansson-mr** [comment]
Perhaps the issue has been there all along...

2017-08-02 13:11 GMT+02:00 Viktor Hofer <notifications@github.com>:

**Comment by karelz** [comment]
@jannikbuschke the associated PR claims it was fixed in 2.1. Maybe you're hitting different issue?

**Comment by jannikbuschke** [comment]
Im seeing above exception when targeting 461 in a netcore 2.1 app deserializing a claim that has a Properties.Count > 0. See https://github.com/dotnet/corefx/issues/34840#issuecomment-458750316

**Comment by karelz** [comment]
What does it mean targeting 461 in netcore 2.1? Do you run it on .NET Framework as the linked issue says?
Should we just keep the discussion on the main issue, or is there value to have it here as well?

**Comment by jannikbuschke** [comment]
yes exactly. Running dotnet core on the fullframework. Lets follow up on my original issue
