### ISSUE TITLE
ImmutableArrayBuilderDebuggerProxy ctor should throw ArgumentNullException on null parameter

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#22837]
Unlike other debugger proxies for immutable collections, this accepts a null `ImmutableArray` parameter, then throw NRE on use.

**Comment by jamesqo** [comment]
Why? I thought the debugger doesn't bother trying to instantiate the debugger proxy if a variable is null-- wouldn't the better approach be to remove null validation from all of them instead?

**Comment by JonHanna** [comment]
It's a public interface, so there isn't so much "the debugger" as "a debugger", that should no more be assumed as correct as any other client code.

**Comment by jamesqo** [comment]
@JonHanna 

> It's a public interface

Can you clarify what you mean by that? AFAICS the types are internal/private.

**Comment by JonHanna** [comment]
Well, public-ish, since it does require reflection to get to, which we don't usually consider as public, but it has on the other hand pointed to the type in a documented way, so there's a greater expectation that such reflection will be done.
