### ISSUE TITLE
add outlookbar to wpf standard controls

### ISSUE THREAD

**Issue by furesoft** [dotnet/corefx#2285]

**Comment by svick** [comment]
AFAIK, there is nothing WPF-related in this repository, so I think this request doesn't belong here. You could try [User Voice](http://visualstudio.uservoice.com/forums/121579-visual-studio/category/89380-windows-presentation-foundation) instead.

**Comment by terrajobst** [comment]
Hi @furesoft! @svick is correct. While it's OK to fail issues for things that aren't open sourced at this point, it only makes sense to track work for items that are on the [road map of becoming open source](http://github.com/dotnet/corefx-progress).

As @svick suggested, the place to go for WPF is [user voice](http://visualstudio.uservoice.com/forums/121579-visual-studio/category/89380-windows-presentation-foundation). Sorry about that!
