### ISSUE TITLE
SqlCommand EndExecuteXmlReader is private

### ISSUE THREAD

**Issue by EgorBo** [dotnet/corefx#22876]
I know the missing API stuff in System.Data is listed here https://github.com/dotnet/corefx/issues/17126
but in this particular case the [method](https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlCommand.cs#L1299) is fully implemented but it's private ([public](https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlcommand.endexecutexmlreader(v=vs.110).aspx) in .NET 4.6)
it looks like it can be easily fixed ;-)

the full list of private members:
```
- IAsyncResult BeginExecuteNonQuery(System.AsyncCallback callback, object stateObject)
- System.IAsyncResult BeginExecuteXmlReader(System.AsyncCallback callback, object stateObject)
- int EndExecuteNonQuery(System.IAsyncResult asyncResult)
- SqlDataReader EndExecuteReader(System.IAsyncResult asyncResult)
- XmlReader EndExecuteXmlReader(System.IAsyncResult asyncResult)

```

**Comment by saurabh500** [comment]
Closed with https://github.com/dotnet/corefx/pull/26252
