### ISSUE TITLE
Allow Type.MakeGenericType to further instantiate partially instantiated Types

### ISSUE THREAD

**Issue by kingces95** [dotnet/corefx#22870]
Currently `Type.MakeGenericType` will throw for types for which `Type.IsGenericTypeDefinition` is `false`. I'd like to lift that restriction and allow Type.MakeGenericType to further instantiate partially instantiated types. For example, given a `type` representing `Foo<T0, int>` where `T0` represents the first generic type parameter then the type `Foo<string, int>` could be constructed by calling `type.MakeGenericType(typeof(string))`.

Here is a fiddle of a slightly more complicated example which is copied below: https://dotnetfiddle.net/HYGMv9. 

A few "food for thought" cases:
* If fewer types are supplied to `MakeGenericType` then the missing generic parameters are assumed to be the existing substitutions. Thus `type.MakeGenericType(new Type[] { })` would always succeed and return `type`. 
* `MakeGenericType` may accept fewer than or an equal number of types than `GenericTypeParameters.Length` but never more.
* If all types have been substituted then `type.MakeGenericType(...)` will succeed (if an equal or fewer number of types than there are generic parameters are supplied) and return `type`
* If no type parameters exist for a given substitution than that substitution is ignored.
* `null` can be passed as a substitution argument to `MakeGenericType` if there no long exist any generic parameters which would be substituted for the position `null` occupies. 
* Although type parameters from other types can be used to instantiate a type only the type parameters for the type be instantiated are substituted. 

``` C#
using System;

public class Foo<T0, T1, T2> { }

public class Program
{
	public static void Main()
	{
		var type = typeof(Foo<,,>);
		var genericArguments = type.GetGenericArguments();
		var T0 = genericArguments[0];
		var T1 = genericArguments[1];
		var T2 = genericArguments[2];
		
		var type_Int_T2_T1 = type.MakeGenericType(typeof(int), T2, T1);

		var type_Int_T1_Short = type.MakeGenericType(typeof(int), T0, typeof(short));
		
		// Currently throws; Wish for it to succeed
		if (type_Int_T1_Short == type_Int_T2_T1.MakeGenericType(
			null, 		// T0 replacement => typeof(int)
			typeof(short), 	// T1 replacement
			T0)		// T2 replacement
		)
			Console.WriteLine("success");			
	}
}

**Comment by kingces95** [comment]
Here is a first shot at the implementation (minus error checking) and an updated fiddle: https://dotnetfiddle.net/ioDgBe. 

The complete solution would include generic methods and similarly expanding `MethodInfo.MakeGenericMethod`.

``` c#
public Type MakeGenericTypeEx(this Type type, params Type[] substitutions) {
    if (!type.IsGenericType)
        return type;

    return Substitute(type.GetGenericTypeDefinition(), substitutions, type);
}
private static Type Substitute(Type definition, Type[] substitutions, Type type) {
    var info = type.GetTypeInfo();

    // substitution
    if (info.IsGenericParameter && info.DeclaringType == definition) {
        return substitutions[info.GenericParameterPosition];
    }

    // leaf
    if (!info.IsGenericType || info.IsGenericParameter)
        return type;

    // substitute sub-trees
    var arguments = type.GetGenericArguments();
    for (int i = 0; i < arguments.Length; i++) {
        arguments[i] = Substitute(definition, substitutions, arguments[i]);
    }

    // node
    return info.GetGenericTypeDefinition().MakeGenericType(arguments);
}

**Comment by AtsushiKan** [comment]
`MakeGenericType()` is implemented by the specific implementor, not the `Type` class itself. (So that's CoreCLR, CoreRT, `TypeBuilder` on CoreCLR, third party implementors such as LMR, and various private implementations that live around the codebase.) So any changes or additions to its semantics would require addressing all of these implementations.

`MakeGenericType()` is also the core mechanism for creating instanced types so it should stick to the "perform one task and do it well" philosophy. Adding all these new rules and behaviors would slow down the api, make it harder for legitimate programming errors to be detected and it could not be pay-for-play (i.e. the extra cost incurred only when `IsGenericTypeDefinition == false`) on CoreCLR because CoreCLR lacks separate representations for `G<>` and `G<T>`

Respecialization does not seem to be a common enough use case to put this on the core class. What you're describing could be written as an extension method that's independent of the details of the underlying Type implementation.

**Comment by kingces95** [comment]
What is an "instanced type"?

**Comment by AtsushiKan** [comment]
"instanced type" = Type for which `IsConstructedGenericType == true`. I guess I should use that term consistently - it's just Such A Long Name...

The more general point being that the `Make...()` apis on `Type` are the core "factory methods" on that class. Doing a recursive walk over the type tree and replacing generic type parameters with concrete types is a big step above that.

**Comment by kingces95** [comment]
@AtsushiKan Just out of curiosity, what practical use case does `IsConstructedGenericType` address?

**Comment by AtsushiKan** [comment]
BTW, I suspect a general purpose "Type Visitor" api that walks the tree and lets you perform a custom action or replacement would be a more likely candidate for an api. This lets apps be more future-proof in case we extend Reflection hierarchy in the future to accomodate stuff like (say) function pointer signature types or custom-modified types.

(I'm assuming that you meant `Substitute` to recurse down things like arrays, byrefs and pointer types.)

**Comment by AtsushiKan** [comment]
Same use as `IsArray`, `IsGenericParameter`, etc. It tells you what flavor of Type it is, which in turn, determines which apis are safe to call on it.

**Comment by AtsushiKan** [comment]
Closing as I don't think this has broad enough applicability to be a part of the CoreFX api.

**Comment by kingces95** [comment]
@AtsushiKan Thanks for considering the suggestion! This request aside, is there an API that is safe to call if `IsConstructedGenericType` is `true` for which there is not an existing predicate? For example, the following table captures the relationships I'm familiar with:

| Predicate | Enabled Operation |
|----|----|
| `IsGenericType` | `GetGenericArguments`, `GenericTypeArguments`, `GenericTypeParameters` |
| `IsGenericTypeDefinition` | `MakeGenericType` |
| `IsGenericParameter` | `GenericParameterPosition`, `GenericParameterAttributes`, `GetGenericParameterConstraints` |
| `ContainsGenericParameters` | _cannot_ `Activate`, `Invoke` _nor_ `MakeGenericType` |

What API is safe to call if `IsConstructedGenericType` is `true`?

**Comment by AtsushiKan** [comment]
`IsConstructedGenericType` was a CLR 4.0 addition that captured what `IsGenericType` should have been. `IsGenericType` is a CLR 2.0 api and is equivalent to `IsGenericTypeDefinition || IsConstructedGenericType` The CLR 2.0 api design reflected a rather iffy mental model of generics that (improperly in my mind) conflated the concept of the basic generic type (the generic type definition) and instantiations of it (the constructed generic type.) `IsGenericType` is one of the vestiges of that and sticks around for compat sake. Personally, I flag its use any time I see that api in code reviews.

So in that table, I'd put 

`IsConstructedGenericType`    `GetGenericArguments`, `GenericTypeArguments`, `GetGenericTypeDefinition()`

and a skull and crossbones next to the `IsGenericType` line :-)

**Comment by kingces95** [comment]
@AtsushiKan I see. And thanks for indulging my questions! 

So `IsGenericType` conflates `IsGenericTypeDefinition` and `IsConstructedGenericType`.

If I could play Devil's Advocate for a second I'd ask: For `public class Foo<T1, T0> { }` why shouldn't reflection treat a type representing `Foo<T1, T0>` and one representing `Foo<T0, T1>` the same (except for `IsGenericTypeDefinition` which blesses one type parameter ordering as the one declared); Why differentiate between a type that `IsGenericTypeDefinition` and the same type but with the generic arguments in a different order?  

Instead, isn't it more desirable to have fewer partitions of the set of reflection API which work and don't for all the various types of Types? To that end, at least with CLR 2.0 API, if `MakeGenericType` were made to work in both cases than that would unify two partitions: Those types for which IsGenericTypeDefinition is true and the same type with a different instantiation.

Fewer Partitions == Good Thing, no?

**Comment by jnm2** [comment]
> Just out of curiosity, what practical use case does IsConstructedGenericType address?

In my codebase, it only shows up as:

```c#
public static Type GetGenericTypeDefinitionIfGeneric(this Type type) => type.IsConstructedGenericType ? type.GetGenericTypeDefinition() : type;
```
