### ISSUE TITLE
SqlConnection doesn't support empty values

### ISSUE THREAD

**Issue by EgorBo** [dotnet/corefx#22879]
```
var cn = new SqlConnection("Timeout=");
Console.WriteLine(cn.ConnectionTimeout);
```
.NET 4.6 (and mono) prints:
> 15

.NET Core:
> System.ArgumentNullException: 'Value cannot be null.'

I suspect it happens with other parameters too, for example - "packet Size="

**Comment by Clockwork-Muse** [comment]
Question - are you working with a keyboard/interface language set to non-English?  Are you sure that the visible characters are the only bytes?

**Comment by EgorBo** [comment]
@Clockwork-Muse nope, there is no hidden symbols here :-)

**Comment by EgorBo** [comment]
it's here https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/Common/DbConnectionOptions.cs#L75-L81
this method should use "defaultValue" if value from _parsetable is null (it does in .net ref sources)

**Comment by EgorBo** [comment]
https://github.com/dotnet/corefx/commit/b75fc80468ed312a2ce3674eb4595fef88707f82#diff-8fa652387990e8cfc78a4a6bdc672da7L207
