### ISSUE TITLE
SqlConnection GetSchema throws NullReferenceException

### ISSUE THREAD

**Issue by EgorBo** [dotnet/corefx#22882]
```
SqlConnection cn = new SqlConnection();
cn.GetSchema();
```
.NET 4.6 (and mono):
> System.InvalidOperationException: 'Invalid operation. The connection is closed.'

.NET Core:
> NullReferenceException

I guess NRE is not really user friendly

**Comment by saurabh500** [comment]
Closed with https://github.com/dotnet/corefx/pull/26252
