### ISSUE TITLE
Proposal/discussion: Task/Task<T> implementing IObservable<T>?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#22891]
When Task/Task<T> were initially introduced, we went back and forth on whether they should implement IObservable<T>.  The remnants of this are even still visible in the desktop code, e.g.
http://referencesource.microsoft.com/#mscorlib/system/threading/Tasks/Future.cs,75
http://referencesource.microsoft.com/#mscorlib/system/threading/Tasks/Future.cs,1598

If I remember correctly (and I might not), the reason we eventually didn't implement it was for layering concerns at the time, but given that both Task and IObservable are in corelib on all platforms, and in System.Runtime, I don't think there are any such layering concerns remaining.

The main benefit to implementing these interfaces is that then combinators for IObservable would then also work for Task, e.g. making it easier to stream together the results from arbitrary numbers of async operations.

This would raise the question of whether a Task would also implement an IAsyncEnumerable if/when such an interface exists, and if not, why it would implement IObservable.

There's also the question of whether both `Task<T>` and `Task` would implement the interface, and if so, what would the type `T` be in `IObservable<T>`, e.g.
```C#
public class Task<T> : Task, IObservable<T> { ... }
public class Task : IObservable<Task> { ... }
```
or
```C#
public class Task<T> : Task, IObservable<Task<T>> { ... }
public class Task : IObservable<Task> { ... }
```
or
```C#
public class Task<T> : Task, IObservable<T> { ... }
public class Task : IObservable<SomeVoidType> { ... }
```
or
```C#
public class Task<T> : Task, IObservable<T> { ... }
public class Task { ... }
```
with the oddity compounded by `Task<T>` implementing both the `IObservable<T>` interface it implements and the `IObservable<U>` its base Task implements, if the latter does so.

**Comment by stephentoub** [comment]
cc: @davidfowl

**Comment by onovotny** [comment]
Related is this PR from @bartdesmet to make `IObservable` more Task-like: https://github.com/Reactive-Extensions/Rx.NET/pull/343

**Comment by jamesqo** [comment]
@stephentoub I saw this issue yesterday and thought it was really interesting. One thing that immediately came to my mind was having `Task` implement `IObservable<Unit>`, however as you say two `IObservable` implementations may confuse the compiler, and [`Unit` lives in Rx](https://github.com/Reactive-Extensions/Rx.NET/blob/develop/Rx.NET/Source/src/System.Reactive/Unit.cs).

I think the best solution would be option #4, having `Task<T> : IObservable<T>` and `Task` not implementing `IObservable` at all. If Rx uses want to be notified when a `Task` completes, then they can convert it to a `Task<Unit>` through an extension method in Rx and subscribe to that. 

```cs
// In Rx
public static async Task<Unit> ToUnitTask(this Task task)
{
    await task;
    return Unit.Default;
}

// User code
NonGenericTaskAsync().ToUnitTask().Subscribe(...);
```

**Comment by kentcb** [comment]
I don't see any mention here of the `ToObservable` extension method and why that doesn't suffice. I realise it's in Rx, but if you're composing tasks as observables, you're going to depend on Rx anyway, right? And I'd argue that once you're hooked on observables (as I am) you end up avoiding TPL altogether and doing everything with Rx.

**Comment by 4creators** [comment]
Just for reflection on the subject:

[Maier, Ingo, and Martin Odersky. Deprecating the Observer Pattern with Scala. React. EPFL-REPORT-176887. 2012.](https://infoscience.epfl.ch/record/176887/files/DeprecatingObservers2012.pdf)

The article essentially scientifically explains what @kentcb said.

**Comment by yzorg** [comment]
@stephentoub Can you break out the options, or is there a place the community can vote?  

I vote for the last option.  I would prefer to explicitly convert `Task` to `IObservable<Unit>` via `.ToObservable()` (in my experience that composition is rare, the biggest value IMO is seamlessly composing `Task<T>` with `IObservable<T>`).

**Comment by yzorg** [comment]
> ... if you're composing tasks as observables, you're going to depend on Rx anyway, right?

@kentcb True, but would it avoid allocations.  I don't know if there is a coherent _"low allocation async"_ story for dotnet (i.e. `Span<ValueTask<T>>`) but my intuition says being able to seamlessly compose `Task<T>` and `IObservable<T>` with less allocations would be a performance win for my apps.

**Comment by stephentoub** [comment]
We will continue to rely on Rx for this.  If you're working with observables, you're using it anyway.
