### ISSUE TITLE
UWP ILC Tests (Master): Several work items have fireball, failed to generate the test result

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#22903]
failed configurations:
Windows.10.Amd64-arm
Windows.10.Amd64.ClientRS3-x64
Windows.10.Amd64.ClientRS3-x86
Windows.10.Amd64.Core-arm

Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170803.01

**Comment by joperezr** [comment]
I'll take a look at what is going on here.

**Comment by joperezr** [comment]
tried taking a look but can't figure out right off the bat why is ILC failing to run `GenerateCodeAndCompile` transform all of a sudden. I don't see any recent changes in corefx side that might have broken this. @MichalStrehovsky do you mind taking a look and forwarding appropiately?

**Comment by MichalStrehovsky** [comment]
> why is ILC failing to run `GenerateCodeAndCompile`

For the random test I looked at, I'm getting this instead:

```
    Running 'Delegate' transform, heap at 270 MB.
    Running 'LazyGenerics' transform, heap at 274 MB.
    MSBUILD : error : ILT0021: Could not resolve method 'System.Byte System.Span<System.Byte>.get_Item(System.Int32)'
```

Seems like this is hitting multiple issues left and right.

**Comment by MichalStrehovsky** [comment]
Okay, tracked it down to a copypaste bug [here](https://github.com/Microsoft/cci/blob/c9cdc0e4852ff6a38a6e5057c90c41cc138b70a8/CoreObjectModel/MetadataHelper/Members.cs#L3223) that nobody hit in years. Next build should have a fix.

**Comment by Jiayili1** [comment]
This issue is still repro: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170804.01

**Comment by MichalStrehovsky** [comment]
> This issue is still repro

That run still uses version 2.0.25603.00 of the ILC compiler. 25604 or later is the one with the fix.

**Comment by joperezr** [comment]
Tahnks for checking @MichalStrehovsky, I will close this and then @Jiayili1 can help us re-open if this is not fixed after consuming the next version of ILC.
