### ISSUE TITLE
Include and ThenInclude not working after groupBy with OrderBy

### ISSUE THREAD

**Issue by AniMeIIIkA** [dotnet/corefx#22909]
Core 2.0
AspNetCore.All 2.1.0-preview1-26462
 Navigation property ICollection is null,
Core 1.1 work fine

**Comment by JonHanna** [comment]
At a guess I'd say this may need to be raised in https://github.com/aspnet/EntityFramework/ presuming you mean their `Include` and `ThenInclude` methods, even if the root cause is something to do with corefx. A minimal repro would likely help, too.

**Comment by karelz** [comment]
@AniMeIIIkA it would be best to post a minimal repro for your bug.
