### ISSUE TITLE
Releasing self-contained apps for different Windows versions

### ISSUE THREAD

**Issue by gregolsky** [dotnet/corefx#22915]
When publishing an app with target runtime `win7-x64` we get some additional DLLs in the output directory, than when we build for `win10-x64` e.g. `api-ms-win-core-console-l2-1-0.dll` and friends. As far as I know it's called runtime compatibility package and it's only available and needed for running on Windows 7.

Given `win7-x64` build we verified the app works fine on both on Windows 7 and Windows 10, loading and using those additional DLLs. However, we were wondering if we lose something in the process, when running an app targeted for `win7-x64` on Windows 10 rather than running a build targeted for `win10-x64`. Does the app enter some kind of compatibility mode by loading those DLLs, can we lose performance or need additional memory?

In general, should we release 2 versions of the app - a separate version for Windows 7 and another one for higher Windows versions?

**Comment by mellinoe** [comment]
You don't need to release two different versions of your app -- the win7-x64 version will work everywhere. The "api-ms-*" forwarder binaries will be ignored on Windows 10, or at least they will be harmless if present.

**Comment by danmosemsft** [comment]
@gregolsky can this be closed?

**Comment by gregolsky** [comment]
Yes, that answers my question. Thanks a lot!

pon., 7.08.2017, 16:44 użytkownik Dan Moseley <notifications@github.com>
napisał:

**Comment by danmosemsft** [comment]
Great.
