### ISSUE TITLE
sqlclient not Found Exception

### ISSUE THREAD

**Issue by hannespreishuber** [dotnet/corefx#22911]
get exception on sqlconnection open. UWP Visual Studio preview, Windows 10 Creators update 

referenced 
6.0.0-preview2-25602-02
sqlclient 4.5.0-preview2-25603-01

System.IO.FileNotFoundException ist aufgetreten.
  HResult=0x80070002
  Nachricht = Could not load file or assembly 'System.Threading.Thread, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Das System kann die angegebene Datei nicht finden.
  Quelle = <Die Ausnahmequelle kann nicht ausgewertet werden.>
  Stapelüberwachung:
   bei System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   bei System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   bei System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   bei System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   bei System.Data.SqlClient.SqlConnection.Open()
   bei ADO.NETSharp.MainPage.Button_Click(Object sender, RoutedEventArgs e) in c:\win10\ADO.NETSharp\ADO.NETSharp\MainPage.xaml.cs: Zeile37

**Comment by corivera** [comment]
CC @weshaggard

**Comment by weshaggard** [comment]
I've not seen this particular issue. System.Threading.Thread should be included in the root UWP meta-package so I would expect it to be present.

**Comment by hannespreishuber** [comment]
perhaps I miss something to add/install
demo project, which crash on open()
https://github.com/hannespreishuber/ado.netsharp3

**Comment by hannespreishuber** [comment]
to come back on that, any documentation what have to been installed? update to Windows Insider Build, took new sdk from yesterday, same result.
