### ISSUE TITLE
Publish non-allocating coding patterns found during PR review.

### ISSUE THREAD

**Issue by clrjunkie** [dotnet/corefx#22929]
PR review is a rare window of opportunity to identify common coding pitfalls in production code. Since over-allocation has proved to have negative impact on .NET programs I suggest documenting common coding patterns seen in PR which avoid over-allocation. I believe this type of knowledge would be very hard to gather later on; therefore I suggest this be added as a goal to PR review.

**Comment by karelz** [comment]
@clrjunkie do you have some specific ideas in mind?

**Comment by clrjunkie** [comment]
@karelz The idea is to have people who regularly review PR identify common memory saving patterns/techniques used when doing code review.  I didn't review any performance improving PR's so I can’t advocate for any one case in particular. Point being, there are numerous ways to avoid allocating memory and I think PR review is an opportunity to identify those reoccurring ways which bring the most bang for the buck.

**Comment by tarekgh** [comment]
CC @stephentoub

**Comment by stephentoub** [comment]
Multiple books have been written on writing high-performance C# code, and many factors are considered when reviewing PRs.  I'm skeptical we could do it justice or produce something particularly meaningful with only a small document.  As this has now been open and unaddressed for several years, I'm going to close it.  Thanks for the suggestion.
