### ISSUE TITLE
How to build self-contained app on archlinux?

### ISSUE THREAD

**Issue by netroby** [dotnet/corefx#22949]
https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json

I can not find any define in runtime.json

but i can really run dotnet run to exec my app.

I read full https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli

But not find how to build on archlinux

would you please add a archlinux.x64 to runtime.json?

**Comment by weshaggard** [comment]
Adding archlinux-x64 to the runtime.json alone doesn't help. We would also need to build a specific runtime for it as well. Do you know if using just "linux-x64" as your RID will work for your needs? Assuming it does that is the best option here.

**Comment by netroby** [comment]
Hello, @wadewegner , i can only see linux-x64 on the runtime.json, but your document
https://docs.microsoft.com/en-us/dotnet/core/rid-catalog

Not describe that. so i have no idea can we using the "linux-x64" as RID

Thanks.

**Comment by weshaggard** [comment]
Yeah I just filed issue https://github.com/dotnet/docs/issues/2843 to try and get the docs updated as they don't talk about our portable RIDs. 

linux-x64 is what we call a portable RID which we try and make assets work in as many places as we can. I believe assets targeting that basically only depend on glibc. I don't know anything about archlinux but assuming it supports glibc you likely can use linux-x64 as your RID.

**Comment by netroby** [comment]
Thanks for your great works. I already build my project . and enjoy the .net
