### ISSUE TITLE
Expose an `Unsafe.CallIndirect` method.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#22957]
### Rationale
Today, in C#, you can only invoke an unmanaged function pointer by first calling `Marshal.GetDelegateForFunctionPointer` and then invoking the resulting delegate that is created.

This not only comes with the increased overhead of the call (`Marshal.GetDelegateForFunctionPointer`) itself, but it also incurs a heap allocation and a 4-6x memory increase, not including internal runtime allocations/overhead -- the `MulticastDelegate` type has an `object` and an `IntPtr` field and the base `Delegate` type itself has two `object` and two `IntPtr` fields -- Invoking the method also has some increased overhead as it goes through the `Delegate.Invoke` call rather than as a direct invocation.

The C# language has planned support for `static delegates` in the future (https://github.com/dotnet/csharplang/blob/c5de26f52019ca0e1e79d88584f75bfe530ee986/proposals/static-delegates.md), but those may still be a way off and could potentially not come at all.

Other languages may also face similar issues if they do not provide equivalent support.

### Proposal
We should expose a new method on the `System.Runtime.CompilerServices.Unsafe` type that functions as an equivalent to the `calli` instruction.

```C#
namespace System.Runtime.CompilerServices
{
    public static class Unsafe
    {
        // Potential other names include: Call, Invoke, InvokeIndirect, Calli, etc...
        public static TResult CallIndirect<TDelegate, TResult>(IntPtr ptr, params object[] args);
    }
}
```

The runtime should treat this as an equivalent to the `calli` instruction with a signature matching `TDelegate`.

The runtime should validate that `TResult`/`args` matches the return/input type of `TDelegate`.

### Other Thoughts

Using generics means that pointers are harder to use, there would have to be support to interpret `IntPtr` and `UIntPtr` args (those passed to `CallIndirect`) as equivalent to a pointer (as declared for the corresponding field in `TDelegate`).

The current proposal (using `params object[]`) means boxing for arguments, maybe having explicit `<TDelegate, TArg, TResult>`, `<TDelegate, TArg1, TArg2, TResult>` overloads would be better?
* I can provide some details for the min/max/avg number of args the interop delegates take (at least for DirectX).

I think, for either case, `out` and `ref` would not be readily supported unless `Unsafe.AsRef` were used internally (also having special handling to interpret `IntPtr` and `UIntPtr` as `ref` equivalents).

### Example Usage

A user might have a manually authored interop type such as:

```C#
[Guid("7B7166EC-21C7-44AE-B21A-C9AE321AE369")]
unsafe public /* blittable */ struct IDXGIFactory
{
    #region Fields
    public readonly Vtbl* lpVtbl;
    #endregion

    #region Delegates
    [SuppressUnmanagedCodeSecurity]
    [UnmanagedFunctionPointer(CallingConvention.ThisCall, BestFitMapping = false, CharSet = CharSet.Unicode, SetLastError = false, ThrowOnUnmappableChar = false)]
    [return: ComAliasName("HRESULT")]
    public /* static */ delegate int EnumAdapters(
        [In] IDXGIFactory* This,
        [In, ComAliasName("UINT")] uint Adapter,
        [Out] IDXGIAdapter** ppAdapter
    );

    [SuppressUnmanagedCodeSecurity]
    [UnmanagedFunctionPointer(CallingConvention.ThisCall, BestFitMapping = false, CharSet = CharSet.Unicode, SetLastError = false, ThrowOnUnmappableChar = false)]
    [return: ComAliasName("HRESULT")]
    public /* static */ delegate int MakeWindowAssociation(
        [In] IDXGIFactory* This,
        [In, ComAliasName("HWND")] void* WindowHandle,
        [In, ComAliasName("UINT")] uint Flags
    );

    [SuppressUnmanagedCodeSecurity]
    [UnmanagedFunctionPointer(CallingConvention.ThisCall, BestFitMapping = false, CharSet = CharSet.Unicode, SetLastError = false, ThrowOnUnmappableChar = false)]
    [return: ComAliasName("HRESULT")]
    public /* static */ delegate int GetWindowAssociation(
        [In] IDXGIFactory* This,
        [Out, ComAliasName("HWND")] void** pWindowHandle
    );

    [SuppressUnmanagedCodeSecurity]
    [UnmanagedFunctionPointer(CallingConvention.ThisCall, BestFitMapping = false, CharSet = CharSet.Unicode, SetLastError = false, ThrowOnUnmappableChar = false)]
    [return: ComAliasName("HRESULT")]
    public /* static */ delegate int CreateSwapChain(
        [In] IDXGIFactory* This,
        [In] IUnknown* pDevice,
        [In] DXGI_SWAP_CHAIN_DESC* pDesc,
        [Out] IDXGISwapChain** ppSwapChain
    );

    [SuppressUnmanagedCodeSecurity]
    [UnmanagedFunctionPointer(CallingConvention.ThisCall, BestFitMapping = false, CharSet = CharSet.Unicode, SetLastError = false, ThrowOnUnmappableChar = false)]
    [return: ComAliasName("HRESULT")]
    public /* static */ delegate int CreateSoftwareAdapter(
        [In] IDXGIFactory* This,
        [In, ComAliasName("HMODULE")] void* Module,
        [Out] IDXGIAdapter** ppAdapter
    );
    #endregion

    #region Structs
    public /* blittable */ struct Vtbl
    {
        #region Fields
        public IDXGIObject.Vtbl BaseVtbl;

        public IntPtr EnumAdapters;

        public IntPtr MakeWindowAssociation;

        public IntPtr GetWindowAssociation;

        public IntPtr CreateSwapChain;

        public IntPtr CreateSoftwareAdapter;
        #endregion
    }
    #endregion
}
```

In order to invoke `EnumAdapters` today, the user would code something similar to:

```C#
var EnumAdapters = Marshal.GetDelegateForFunctionPointer<IDXGIFactory.EnumAdapters>(pFactory->lpVtbl->EnumAdapters);

IDXGIAdapter* pAdapter;
for (var adapterIndex = 0u; DXGI_ERROR_NOT_FOUND != EnumAdapters(pFactory, adapterIndex, &pAdapter); adapterIndex++)
{
    // Check if the adapter supports D3D12
}
```

Under the proposal, someone would now declare:

```C#
IDXGIAdapter* pAdapter;
for (var adapterIndex = 0u; DXGI_ERROR_NOT_FOUND != Unsafe.CallIndirect<IDXGIFactory.EnumAdapters, int>(pFactory->lpVtbl->EnumAdapters, pFactory, adapterIndex, pAdapter); adapterIndex++)
{
    // Check if the adapter supports D3D12
}
```

**Comment by MichalStrehovsky** [comment]
I would kind of prefer the C# compiler team adds dotnet/roslyn#11475 to their schedule instead. We have had to [work](https://github.com/dotnet/corert/issues/3251) [around](https://github.com/dotnet/corert/blob/b0924f3d4721f188dbeb87fda38e1b602a462692/src/System.Private.CoreLib/src/System/Activator.cs#L70) [that](https://github.com/dotnet/corert/blob/b0924f3d4721f188dbeb87fda38e1b602a462692/src/Common/src/TypeSystem/IL/Stubs/CalliIntrinsic.cs) in CoreRT for years.

If someone isn't satisfied with the `Marshal.GetDelegateForFunctionPointer` overhead, I doubt they would be happy with the array allocation and boxing required to do each call. (It would definitely not help us in CoreRT land.)

**Comment by tannergooding** [comment]
> I doubt they would be happy with the array allocation and boxing required to do each call

That is why I suggested "maybe having explicit <TDelegate, TArg, TResult>, <TDelegate, TArg1, TArg2, TResult> overloads would be better" in the other thoughts section.

> I would kind of prefer the C# compiler team adds dotnet/roslyn#11475 to their schedule instead

I fully expect we will get proper `static delegate` support (which compiles down to `calli`) before we get support for `compiler intrinsics` (at least based on https://github.com/dotnet/csharplang/issues/789, where the `static delegates` proposal is on the roadmap, but `Compiler Intrinsics` is not).

The point of this proposal is to provide a stop-gap between now and C# 8 (or later, if it gets pushed out) and to provide a stop-gap mechanism for other languages missing such a feature.

Providing generic overloads for the arguments (`<TDelegate, TArg, TResult>`) avoids the boxing problem and will be able to cover most methods. A general `params object[]` overload will cover the remaining cases and can at least avoid some of the remaining overhead (but not all of it).

**Comment by mellinoe** [comment]
> If someone isn't satisfied with the Marshal.GetDelegateForFunctionPointer overhead, I doubt they would be happy with the array allocation and boxing required to do each call. (It would definitely not help us in CoreRT land.)

I certainly wouldn't switch any of my `calli` usage (done through [a rewriter step](https://github.com/mellinoe/vk/blob/master/src/vk.rewrite/Program.cs#L101) similar to CoreRT) to this if it involved an array allocation and boxing per-parameter. I think that is clearly a non-starter. Providing a bunch of fixed-arity generic overloads would be closer, but the problem of pointers is a bad one, IMO. Most of your `calli` targets will involve pointer parameters, realistically speaking, and now they will all need to be represented as `IntPtr`. If you want strongly-typed pointer overloads, you'll have to write another wrapper. Modifying the runtime in support of `Unsafe` is not really reasonable -- none of the other methods we've added have been treated specially at all by the runtime(s), they all map to simple IL instructions which are well-supported by all of our existing runtimes.

> The point of this proposal is to provide a stop-gap between now and C# 8 (or later, if it gets pushed out) and to provide a stop-gap mechanism for other languages missing such a feature.

I get what you're saying, but there's not really such a thing as a "stop-gap" for the BCL. This would have to be supported forever, on all of our runtimes, even when the proper solutions (static delegates or compiler intrinsics) come into existence.

Is there a way we can "bump up the priority" of the language features (either/or/both)? It feels to me that they would be very, very helpful at addressing a clear gap in the current system.

**Comment by MichalStrehovsky** [comment]
dotnet/roslyn#11475 is not a language feature - it's just a matter of someone sitting down and doing it. I'll buy beers (or other beverage of their choosing) to the person who makes it happen because I *really* want to use it in CoreRT. The feature was [discussed in LDM](https://github.com/dotnet/csharplang/blob/0709623617764880198f972d66845e88a89fe149/meetings/2017/LDM-2017-01-11.md) in January. I would hope we can find someone to do it in the 7.x timeframe.

**Comment by mellinoe** [comment]
@MichalStrehovsky Good point, it's just a "compiler feature". I also really want to use it, and I've discussed it with a few other projects who would use it.

**Comment by tannergooding** [comment]
> I get what you're saying, but there's not really such a thing as a "stop-gap" for the BCL. This would have to be supported forever, on all of our runtimes, even when the proper solutions (static delegates or compiler intrinsics) come into existence.

I think there are always going to be languages that don't support this (possibly just because it is out of scope for the language).

I also think, that while compiler intrinsics are nice, it is probably more worthwhile to invest in actual language features that expose things in desired ways (for the compiler team, what is the benefit of providing a `compiler intrinsic` for `calli` when they are already looking at exposing `static delegates` which does the same thing in a much better way).

I think the `Unsafe` class should be the thing that fills in these gaps instead, as it makes it available to all languages, both existing and future, for when they don't expose the functionality themselves (most of these 'missing' features seem to be fairly consistent and are already exposed in `Unsafe`).

> Is there a way we can "bump up the priority" of the language features (either/or/both)? It feels to me that they would be very, very helpful at addressing a clear gap in the current system.

Sadly, I don't think so.  Like most of the teams, there is plenty of backlog for requested features, planned features, etc and only so many devs that can work on them. So it all comes down to priorit, need, etc

**Comment by MichalStrehovsky** [comment]
> Sadly, I don't think so.  Like most of the teams, there is plenty of backlog for requested features

Yet you're proposing a feature that puts it on the backlog of CoreCLR, CoreRT/.NET Native, and Mono teams :). System.Runtime.CompilerServices.Unsafe targets NetStandard 1.0 - requiring runtime features will require bumping it way up.

> when they are already looking at exposing `static delegates` which does the same thing in a much better way

The proposed intrinsics have a broader applicability because they're not limited to static methods. Static delegates would only cover maybe a half of my use cases and I'm only half as excited about them.

**Comment by tannergooding** [comment]
> Yet you're proposing a feature that puts it on the backlog of CoreCLR, CoreRT/.NET Native, and Mono teams :). 

I'm slightly more confident in being able to implement one of those myself :)

**Comment by mjsabby** [comment]
The right thing to do is for the C# Compiler to just implement the ability to emit `calli`, it's been a while since the intrinsic proposal was first initially floated.

I even have a working implementation I've been using for a year or so that we use internally at Bing.

https://github.com/mjsabby/roslyn/commit/e6123e0451b26c578a02e677a8a4b3e65d583d61 (or as a nuget package like Microsoft.Net.Compilers package, https://www.nuget.org/packages/CSCWithCompilerIntrinsics)

The only part I don't like about my implementation is that it generates the `calli` in a method body. The JIT team fixed inlining `calli` methods with default calling convention which partially mitigates this for my scenario. (https://github.com/dotnet/coreclr/issues/12713)

Prior to this I had my own tool like @mellinoe, https://github.com/mjsabby/PInvokeCompiler and I'm sure many others have reinvented their own.

So I don't think the proposal here makes sense, but we should ping the Compiler Intrinsics proposal again.

**Comment by stephentoub** [comment]
@tannergooding, can this be closed in favor of the function pointer support coming in C#?
https://github.com/dotnet/csharplang/blob/56d8447281d054d4acf20e501f41a40c2db009cd/proposals/function-pointers.md
