### ISSUE TITLE
Serial port tests blocking when loopback is present with USB seria ports

### ISSUE THREAD

**Issue by pjanotti** [dotnet/corefx#22966]
This is not related to code in corefx since I can repro it in Desktop framework. However, it makes the coverage of my local tests for serial ports very limited. The issue is that after certain tests the code trying to close the port gets blocked on closing the handle (it proceeds if I unplug the USB). I suspect that is related to the way that the tests are using threads to read/write and force exceptions to be throw.

I tried with the driver automatically installed (2.12.24.0) latest from http://www.ftdichip.com/Drivers/VCP.htm (2.12.26.0) but no change.

@JeremyKuhne @willdean let me know if you guys have any idea about this issue. For now blocks me from getting good coverage for adding serial ports to UWP (see #22887).

**Comment by willdean** [comment]
If you're using an FTDI device, then there aren't "MS drivers" that I know of, just FTDI ones (some versions are in-box in Windows though).

I have had quite good coverage with FTDI devices here earlier during the porting process, although there have been some changes to the way the driver cleans-up at close more recently which perhaps might have turned into a hang using FTDI hardware.    

If I was to try and run the tests here again with FTDI hardware, it would be very helpful if you could let me know exactly which tests are hanging (or at least one example), so that I don't have to spend ages searching for it.

**Comment by pjanotti** [comment]
@willdean I edited the original issue to correct the bit of MS driver. Here is a quick dirt code that I put in place from the tests that reproduces the issue, likely it can be trimmed to a smaller repro. On my box the second run of the test hangs on close:

```c#
using System;
using System.Diagnostics;
using System.IO.Ports;
using System.Threading;
using System.Threading.Tasks;

namespace SerialPortOnFullFx
{
    class Program
    {
        private const int s_DEFAULT_BUFFER_LENGTH = 1025;
        private const int HardwareTransmitBufferSize = 0;
        private static string PortName = "COM4";

        static void Main(string[] args)
        {
            if (args?.Length > 0)
                PortName = args[0];

            OutBufferFilled_Discard_Once();
            OutBufferFilled_Discard_Once();
        }

        public static void OutBufferFilled_Discard_Once()
        {
            using (SerialPort com1 = new SerialPort(PortName))
            {
                Console.WriteLine("Verifying Discard method after write buffer has been filled");
                com1.Open();
                com1.WriteTimeout = 500;
                com1.Handshake = Handshake.RequestToSend;

                Task task = Task.Run(() => WriteRndByteArray(com1, s_DEFAULT_BUFFER_LENGTH));
                WaitForWriteBufferToLoad(com1, s_DEFAULT_BUFFER_LENGTH);

                VerifyDiscard(com1);

                // Wait for write method to fail with IOException
                // Assert.Throws<AggregateException>(() => task.Wait(2000));
                try
                {
                    task.Wait(2000);
                    throw new ApplicationException("Expected AggregateException was not raised.");
                }
                catch (AggregateException)
                {
                    var innerException = task.Exception.InnerException;
                    Console.WriteLine($"InnerException: {innerException.GetType()}: {innerException.Message}");
                }
            }
        }

        public static void OutBufferFilled_Discard_Cycle()
        {
            using (SerialPort com1 = new SerialPort(PortName))
            {
                Console.WriteLine(
                    "Verifying call Discard method after input buffer has been filled discarded and filled again");

                com1.Open();
                com1.WriteTimeout = 500;
                com1.Handshake = Handshake.RequestToSend;
            }
        }

        private static void WriteRndByteArray(SerialPort com, int byteLength)
        {
            byte[] buffer = new byte[byteLength];
            Random rndGen = new Random(1);

            for (int i = 0; i < buffer.Length; i++)
            {
                buffer[i] = (byte)rndGen.Next('a', 'z');
            }

            // This will abort with an IOException when the test calls DiscardOutBuffer
            // we will catch that exception on the Task.Wait()
            com.Write(buffer, 0, buffer.Length);
        }

        public static void WaitForWriteBufferToLoad(SerialPort com, int bufferLength)
        {
            Console.Write("Starting wait for buffer to load ");
            Stopwatch sw = Stopwatch.StartNew();
            int totalBytes;
            while ((totalBytes = com.BytesToWrite + HardwareTransmitBufferSize) < bufferLength)
            {
                Console.Write($" {totalBytes} ");
                Thread.Sleep(50);
                Debug.Assert(sw.ElapsedMilliseconds < 3000, $"Timeout while waiting for data to be written to port (wrote {bufferLength}, queued {com.BytesToWrite}, bufSize {HardwareTransmitBufferSize})");
            }
            Console.WriteLine($"done ({totalBytes}).");
        }

        private static void VerifyDiscard(SerialPort com)
        {
            ////Debug.Assert(0 > com.BytesToWrite, "BytesToWrite <= 0 @ VerifyDiscard");
            Console.WriteLine("BytesToWrite=" + com.BytesToWrite);
            com.DiscardOutBuffer();
            var bytesToWrite = com.BytesToWrite;
            Console.WriteLine("BytesToWrite=" + bytesToWrite);
            Debug.Assert(0 == bytesToWrite, "BytesToWrite != 0 @ VerifyDiscard");
        }
    }
}
````

**Comment by willdean** [comment]
Thanks for that - if it runs once and then fails the second time, I think that must be a driver issue, because there would be no application state which persisted between the two runs.

I will see if I can try it here sometime.

**Comment by pjanotti** [comment]
Just to clarify: I put two calls of `OutBufferFilled_Discard_Once` code so you get blocked on the close of the second call, but, if you have only one call on the program the second run of the program blocks. So it seems really a driver issue.

**Comment by willdean** [comment]
@pjanotti Right.  I suspect that the only hope of getting FTDI to look at this would be to repro it in native Win32 code, which might be very tedious.  

You don't by any chance have third-party drivers for your motherboard's USB host hardware do you?  They don't seem common nowadays, but at one time they were a notorious cause of USB issues, and you could often improve things by just deleting the USB host controller devices and letting Windows reinstall its own drivers in their place.

**Comment by pjanotti** [comment]
@willdean All my USB related drivers (except for the FTDI one) are Microsoft. The issue also happens in a different machine (one is a HP desktop and the other is a Lenovo notebook). I did attach a debugger to the program when it was blocked and I could see that it was blocked at `ntdll!ZwClose(void)` so it happens at the kernel level.

**Comment by willdean** [comment]
Although I think this is really a driver bug, I wonder if there is any sort of cancellation we can do prior to the CloseHandle call which would improve things here?

**Comment by pjanotti** [comment]
shooting from the hip: that seems worth a try since this is likely related with the code leaving some pending IO in which the driver blocks until it is completed.

**Comment by willdean** [comment]
@pjanotti I'm sure you're right.  It's just pending IRPs of some kind (possibly one of the Wait IOCTLs) which need cancellation somehow.  It's probably a few hours work to determine what's going on, which I don't have free right at the moment.  

It might actually be this issue which I helped someone with earlier in the year:  #16529

**Comment by pjanotti** [comment]
@willdean thanks for the link to the previous issue. I am also short on time right now but will try to look as soon as I get a chance.

**Comment by pjanotti** [comment]
@willdean I gave a try to some clean up but no luck so far. I *think* I can write a repro of the issue in native but meanwhile I am ordering serial ports with a different chipset to see if I can get better test coverage.

**Comment by pjanotti** [comment]
/cc @willdean @JeremyKuhne @danmosemsft 
Jeremy had some USB-to-Serial w/ chipset from ProLiant and those did not have the same issue, so this is not blocking anymore. I did hit some test failures, I will investigate those.
