### ISSUE TITLE
Core test failure: System.Globalization.Tests.RegionInfoPropertyTests.DisplayName(name: \"en-US\", expected: \"United States\")

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#22964]
If DisplayLanguage is not en-US the following test is failing:

```
System.Globalization.Tests.RegionInfoPropertyTests.DisplayName(name: \"en-US\", expected: \"United States\") [FAIL
  ]
        Assert.Equal() Failure
                   (pos 0)
        Expected: United States
        Actual:   Vereinigte Staaten
                   (pos 0)
        Stack Trace:
           D:\git\corefx\src\System.Globalization\tests\RegionInfo\RegionInfoTests.Properties.cs(37,0): at System.Globa
  lization.Tests.RegionInfoPropertyTests.DisplayName(String name, String expected)
```

In my case I had just switched my display language to German and the test started to fail. The test should either be conditioned to only run when display language is en-US or be disabled completely. 

The related production code:
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Globalization/RegionInfo.cs#L211

@tarekgh

**Comment by tarekgh** [comment]
Right, this test needs to set the CurrentUICulture before calling the DisplayName property. and the test need to be executed with RemoteInvoke

**Comment by ViktorHofer** [comment]
Yah, that's even better. Do you want to submit the PR or should I?

**Comment by ViktorHofer** [comment]
I just tried and it's not working. It seems the language used for DisplayName depends on the installation language of the framework. At least it was like that with .NET Framework according to MSDN. It that still the case with .NET Core? Do we have an installation language?

https://msdn.microsoft.com/en-us/library/system.globalization.regioninfo.displayname%28v=vs.110%29.aspx

See Remarks section.

**Comment by ViktorHofer** [comment]
My configuration:
- Installed language of OS and .NET framework / .NET Core: de-AT
- Additional installed language: en-US
- Region: same as display language

**Comment by tarekgh** [comment]
Setting CurrentUICulture should do it. if not, then we have a bug. how did you set current UI culture? could you send me the changes you have to take a look?

**Comment by ViktorHofer** [comment]
According to the docs it depends on the installation language... Yes here is the test method with my changes
```

[Theory]
        [InlineData("en-US", "United States")]
        public void DisplayName(string name, string expected)
        {
            RemoteInvoke((string _name, string _expected) =>
            {
                //System.Threading.Thread.CurrentThread.CurrentUICulture = new CultureInfo(_name); <-- tried that too, does not help
                CultureInfo.CurrentUICulture = new CultureInfo(_name);
                Assert.Equal(_expected, new RegionInfo(_name).DisplayName);

                return SuccessExitCode;
            }, name, expected).Dispose();
        }
```

**Comment by tarekgh** [comment]
> According to the docs it depends on the installation language

I  agree the doc is confusing. but it explicitly states the following too :-) 

```
The value of the DisplayName property is taken from the resource files in the language of the current user interface culture, represented by CurrentUICulture.
```

https://msdn.microsoft.com/en-us/library/system.globalization.regioninfo.displayname%28v=vs.110%29.aspx#Remarks

I see where is the problem now so I am going to fix this on Monday. This is not a test bug but we'll still need to keep your proposed test changes.

**Comment by ViktorHofer** [comment]
Alright. Thank you Tarek!

**Comment by tarekgh** [comment]
can you submit the test changes anyway? My fix will be in coreclr and fix the test from now will not hurt.
