### ISSUE TITLE
No line numbers for test failures on Windows

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#22979]
This is happening in the test runs we do on Windows Server 2016 Core. It makes debugging problems harder than it should be. The official runs we do seem to all be "Release" configuration, but even when I manually copy a Debug runtime and tests into a VM, I still don't get line numbers.

**Comment by karelz** [comment]
@mellinoe do you think it is infra issue or product issue?

**Comment by mellinoe** [comment]
@karelz I'm not sure -- it could be either. It's possible that we just haven't installed some component that enables line numbers on our test machines, but I'm not sure what that is. We had a similar problem recently where we weren't copying a certain file into our test runtime, and line numbers disappeared. Perhaps we are missing something on the machines themselves in this case.

**Comment by mellinoe** [comment]
@mikem8361 Do you know why this might be happening?

**Comment by danmosemsft** [comment]
@mellinoe did you verify that msdia140.dll  is present and registered? (the issue UWP had)

**Comment by mikem8361** [comment]
Is microsoft.diasymreader.native.amd64.dll part the .NET Core binaries? It needs to be next to coreclr.dll and should be part of the shared frame install.  It is in Microsoft.DiasymReader.Native package.

**Comment by mikem8361** [comment]
I'm assuming this is .NET Core and not UWP/.NET Native,

**Comment by danmosemsft** [comment]
Line numbers are missing for all regular Windows runs.

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170807.02/workItem/System.ServiceProcess.ServiceController.Tests/analysis/xunit/System.ServiceProcess.Tests.ServiceBaseTests~2FTestOnPauseThenStop

They are working on Unix and on ILC UWP. Don't know about CoreCLR UWP as there aren't any tests failing.

**Comment by mellinoe** [comment]
@danmosemsft  You're right, it's not working anywhere. Diasymreader is being included anymore in the test runtime. Perhaps there was a recent regression, because I thought your change had fixed it (https://github.com/dotnet/corefx/commit/28a796797ba135c466fa8b7f086d228d3a3a9d9d). @weshaggard

**Comment by mellinoe** [comment]
Oops -- I meant to say "Diasymreader is NOT being included".

**Comment by mellinoe** [comment]
#23028 Fixes the issue with DiaSymReader not being copied into the test runtime, but it doesn't look like line numbers are working for some Windows versions, still.

**Comment by danmosemsft** [comment]
Unix and Mac have line numbers for both test and product eg https://github.com/dotnet/corefx/issues/23631 https://github.com/dotnet/corefx/issues/23630 

Windows has line numbers for just tests eg https://github.com/dotnet/corefx/issues/23679  https://github.com/dotnet/corefx/issues/23548 but sometimes neither https://github.com/dotnet/corefx/issues/23548

**Comment by danmosemsft** [comment]
@joperezr is going to look at this.

**Comment by joperezr** [comment]
Just to update, I haven't got a chance to look into this yet, but I will try to check on it this week.

**Comment by danmosemsft** [comment]
Thanks @joperezr !
cc @safern

**Comment by joperezr** [comment]
Fix has been merged into coreclr directly so closing this one. Please do feel free to reopen in case the issue still remains.
