### ISSUE TITLE
Please expand DataAnnotations validation to enable conditional validation and others

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/corefx#22986]
Hi,

I'd like to request to extend the `ValidationAttribute` by adding a few properties that will enable conditional validation.
I love the idea of validating by attributes, but it would be nice if we could extend the validation attribute a little bit.
The downside of attributes, is that there are no generics, and no complex parameters so there is no nice way to extend the current behavior.

So please add a few properties to the abstract `ValidationAttribute` class, there a many ways to think of how to gather the condition. Some of which are:

- Expose a set of properties `PropertyName` and `IsEqualTo` that enables validation only when a property with the specified name equals the specified value.
- Have the class implement an interface `IShouldValidate` etc.
- Make it easier to attach/unattach metadata types for validation
- Add a generic methods to `Validator` class, so it's easier to validate using `IValidatable`
For example:

`public ValidationResult ValidateValue<TValidationAttribute>(object value, Func<TValidationAttribute> setup = null);`

Example usage (within `IValidatableObject.Validate`):

    yield return Validator.Validate<RequiredAttribute>(this.Name); (returns `ValidationResult`);
    yield return Validator.Validate<RangeAttribute>(this.Age, () => new RangeAttribute(10, 20));

Would be also interesting to hear about more ideas and workarounds too.

**Comment by lajones** [comment]
We're going to make this one `up-for-grabs` and will look at individual PR's for features as they come in. For reference we would like the following for any PR on this:

- A detailed description of the new behavior and how it is expected to be used
- A complete API proposal
- Confidence that there is essentially zero risk of the change breaking any existing code

**Comment by weitzhandler** [comment]
@lajones 
I'm willing to implement this.
But I'd like some guidance.

One of the problems I can see, Imagine we add those conditional properties into `ValidationAttribute`, now for example EF uses the `RequiredAttribute` and some other attributes to generate SQL columns accordingly. How will it behave if the attributes are conditional?
Same problem may arise with any implementations relying on the current infrastructure of the `ValidationAttribute`s.
I'm not so familiar with EF Core, does it rely on these attributes?

Any other propositions on what ways we can take to implement that?

**Comment by lajones** [comment]
@weitzhandler Sorry for the delay. Your concerns are valid and apply to any change to `DataAnnotations` attributes. There may be any number of frameworks out there relying on the current behavior of any one of these attributes - which is why a high priority is to keep the current functionality of the attributes the same.

We can't speak for all such frameworks of course. Re EF, we do not use validation in the newest version of EF, EFCore. However we did use it in EF6: by default validation was run (optionally, but on by default) during `SaveChanges()`. This involved calling the `Validate()` method of any applicable attributes and throwing an exception if validation failed. If you need EF6 to be updated in parallel with or after your `DataAnnotations` changes then I would log an issue at https://github.com/aspnet/EntityFramework6/issues.

Another major Microsoft framework which uses those attributes is MVC. @dougbu are you able to comment from the MVC side?

**Comment by dougbu** [comment]
MVC discovers and executes `IValidationAttribute`s and other validation-related annotations automatically. The attributes can (mostly-statically) be added using `IValidationMetadataProvider`. Or, users can implement `IValidatableObject` in their model types and (dynamically) choose what properties get validated in those implementations.

I suspect MVC would pick up `ValidationAttribute` and `IValidatableObject` additions automatically if the `ValidationAttribute.GetValidationResult(object, ValidationContext)` and `IValidatableObject.Validate(ValidationContext)` methods still did the Right Thing:tm: even in new cases. Will back-compatibility there be a goal?

Note MVC does not use the `Validator` class.

**Comment by weitzhandler** [comment]
Thanks for your response, @lajones!

The difference between EF and some other frameworks that might rely on the annotation validation attributes (e.g. MVC), is that EF relies on the attribute **type**, rather than on the actual validation result, we're not going to have a problem with MVC if we expand `ValidationAttribute` to include conditional validation, because down the line, MVC is going to actually validate the entity/property by calling the `IsValid` method of the `ValidationAttribute`, so in case conditional validation is implemented, we do want MVC to include/ignore the specific validation rule.

The problem we have with conditional validation in EF is that EF (core included), relies on the attribute **type**, to generate the appropriate columns, for instance if a column is annotated with the `RequiredAttribute`, EF-SQL will generate a non-nullable column in the DB, without having to actually trigger any validation.
We could address this, maybe by adding an additional boolean property that determines if the attribute is conditional, to give a hint to implementors. Question is if the EF would be willing to add this check in their code base, so that conditional validation attributes don't affect the model metadata (so in case of a conditionally required column, the DB column will still be nullable).
@divega/@smitpatel/@ajcvickers/@bricelam, sorry for bothering you, and I'm really hoping one of you can have a look.

**Comment by weitzhandler** [comment]
Thanks for your response, @lajones!

The difference between EF (and/or others?) and some other frameworks that might rely on the annotation validation attributes (e.g. MVC), is that EF relies on the attribute **type**, rather than on the actual validation result.
With MVC, we're not going to have any problem to expand `ValidationAttribute` to include conditional validation, because down the line, MVC is going to actually validate the entity/property by calling the `IsValid` method of the `ValidationAttribute`, so with conditional validation implemented, we do want MVC to include/ignore the specific validation rule. @dougbu can you please confirm?

EF however, relies on the attribute **type** to assemble the model metadata, and in turn generate the appropriate DB columns.
For instance if a column is annotated with the `RequiredAttribute`, EF-SQL will generate a non-nullable column in the DB, without having to actually trigger any validation.

This could obviously be addressed, perhaps determining if a `ValidationAttribute` is conditional (maybe adding a boolean property to determine that would be nice), and ignore conditional validation attributes from affecting the model metadata. I'd wonder if the EF team would be willing to add such a check in their code base (so in the example of a property annotated with a conditional `RequiredAttribute`, the generated DB column will still be nullable). The general rule would be that conditional attributes are only treated at runtime, I think.

@divega / @smitpatel / @ajcvickers / @bricelam, sorry for bothering you, and I'm really hoping one of you can have a look.

**Comment by dougbu** [comment]
@weitzhandler with the framework calling `GetValidationResult(object, ValidationContext)` already, what might need to change in MVC?

That said, **client-side** validation in MVC would likely get _very_ confused by conditional `ValidationAttribute`s. MVC would probably skip generating the relevant HTML for a `ValidationAttribute` that "looks" conditional i.e. conditional attributes would only be validated server-side. The easier it is to detect that case, the better for MVC.

**Comment by weitzhandler** [comment]
@dougbu [`GetValidationResult`](https://source.dot.net/#System.ComponentModel.Annotations/System/ComponentModel/DataAnnotations/ValidationAttribute.cs,426) internally calls `IsValid`, so from MVCs nothing is supposed to change in the server.
Anyway, you're right about the client-side code, since - like EF does - rely on the attribute **type** to generate appropriate JS without actually triggering the C# validation code. We'll have to implement that change to either leave conditional validation for the server or generate matching client-side validation, if that's an option at all.
Let's see if there is positive response from the various teams for that (EF, MVC and who knows).

@lajones 

I was also thinking of a different approach, maybe we can incorporate some way of metadata classes (like we used to do in RIA services :tongue:) that are easy to plug in and out according to conditions:

```
[ValidationScope(Condition...1, MetadataType = typeof(ContactOpenMd))]
[ValidationScope(Condition...2, MetadataType = typeof(ContactStrictMd))]
public class Contact
{
    public string Name { get; set; }
    public EntryStatus Status { get; set; }
}

public class ContactOpenMd : ContactMd
{
    [Required]
    public string Name { get; set; }
}

public class ContactStrictMd
{
    [Required, StringLength(16)]
    public string Name { get; set; } 
}
```

This could be simplified by having all properties in `Contact` as `virtual`, so that the MD properties will be overridden and annotated, to avoid hard-coding the property names, in MDs, classes are never meant to instantiate anyway.

**Comment by lajones** [comment]
We'll discuss in the next DA Triage meeting (Aug 24) and get back to you.

**Comment by weitzhandler** [comment]
In general, please expand the whole concept of validation in .NET, please give it some more love and flexibility.

**Comment by divega** [comment]
**DataAnnotations Triage:** We discussed this today again. We don't disagree that being able to have more flexible validation is a good idea. However, after thinking about all the points that you raised, we don't believe that extending the current architecture or changing the semantics of existing annotations would be the best approach.

Changing the semantics of existing annotations would potentially cause a lot of confusion, especially because consuming validation frameworks may not understand the new semantics. 

We believe that this is something that would be better addressed in an opinionated manner by an external component instead of trying to solve it in a general way in DataAnnotations. 

That said, it may require decoupling validation from general application frameworks like MVC and EF. Note that for the latter, we already made the decision not to include validation functionality in EF Core: validation is a completely orthogonal concern and we don't want EF Core to get in the way of users doing validation in whatever way they decide. 

I would like to cc @dougbu in case he has any comments about how customers can plug in their own custom validation framework in ASP.NET Core MVC. We are not sure if validation is factored as service or set of services that can be replaced.

**Comment by dougbu** [comment]
> We are not sure if validation is factored as service or set of services that can be replaced.

The MVC abstractions are not tied to `ValidationAttribute` or other concepts from the `System.ComponentModel.DataAnnotations` namespace. And, most components of the validation system can be extended or replaced. Replacement would be a big job&hellip;

I'm not sure even extending the validation system is necessary in general. On the server side, as long as the `ValidationAttribute` methods still work, MVC should be fine.

For client-side validation, the default is to ignore `ValidationAttribute`s; no HTML attributes are generated for `ValidationAttribute`s except the specific ones known to the system (see [`ValidationAttributeAdapterProvider`](https://github.com/aspnet/Mvc/blob/7b2a4ff46583f9897041fbd8d1463be068ddc287/src/Microsoft.AspNetCore.Mvc.DataAnnotations/ValidationAttributeAdapterProvider.cs)). Users with conditional `ValidationAttribute`s in their application should either ignore client-side validation or add associated `IClientModelValidator` implementations to handle their new attribute types (perhaps replacing `ValidationAttributeAdapterProvider` in DI).

**Comment by weitzhandler** [comment]
@divega @dougbu extending the current validation to be conditional is also very hard. It could be easier if generic attributes and complex parameters were supported, then we could go:

    [ConditionalValidation<Range>(() => new RangeAttribute)]
    public Name { get; set; }

>That said, it may require decoupling validation from general application frameworks like MVC and EF. Note that for the latter, we already made the decision not to include validation functionality in EF Core: validation is a completely orthogonal concern and we don't want EF Core to get in the way of users doing validation in whatever way they decide.

EF Core does have ties to the validation. It's not validating the entities, it's just relying on the validation-attribute type to generate the appropriate model schema. And that's actually where our problem lies. We would have to change EF to only consider annotation attributes that `IsConditional` evaluates to `false`, probably not a big deal to implement, but it'll have to be done. Same as with MVC - it should only generate client validation if the attributes are not conditional - ~~~(or alternatively, generate conditional validation on client, if that's even possible)~~~.

**Comment by weitzhandler** [comment]
Extending the current validation to be conditional is also very hard. It could be easier if generic attributes and complex parameters were supported, then we could go:

    [ConditionalValidation<Range>(() => new RangeAttribute)]
    public Name { get; set; }

>That said, it may require decoupling validation from general application frameworks like MVC and EF. Note that for the latter, we already made the decision not to include validation functionality in EF Core: validation is a completely orthogonal concern and we don't want EF Core to get in the way of users doing validation in whatever way they decide.

EF Core does have ties to the validation. It's not validating the entities, it's just relying on the validation-attribute type to generate the appropriate model schema. And that's actually where our problem lies. We would have to change EF to only consider annotation attributes that `IsConditional` evaluates to `false`, probably not a big deal to implement, but it'll have to be done.

>For client-side validation, the default is to ignore ValidationAttributes; no HTML attributes are generated for ValidationAttributes except the specific ones known to the system (see ValidationAttributeAdapterProvider). Users with conditional ValidationAttributes in their application should either ignore client-side validation or add associated IClientModelValidator implementations to handle their new attribute types (perhaps replacing ValidationAttributeAdapterProvider in DI).

That sounds like something any MVC dev would be willing to in exchange to having out-the-box conditional validation. The MVC team might decide to enhance the `ValidationAttributeAdapterProvider` to skip conditional validation in client validation generation. Thanks for your research @dougbu!

---
@divega  Really it's time for the .NET to mature this subject of validation and offer conditional validation, and as I see it, validation scopes is more extendable option. It might be a bit of work at the beginning but it will multiply the productivity of the entire validation process in .NET.

**Comment by weitzhandler** [comment]
Related: #39749
