### ISSUE TITLE
Disable System.Runtime.Extensions tests expected to fail on Server Core

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#22997]
•	In one case ShGetKnownFolderPath returns a different value. It’s kind of bogus API on these platforms so I suggest just disabling it for Server Core.
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170726.03/workItem/System.Runtime.Extensions.Tests

https://github.com/dotnet/corefx/issues/22656

**Comment by joperezr** [comment]
@tarekgh how often does this fail in Server Core? if this is often then it might be worth disabling it as you propose.

**Comment by tarekgh** [comment]
@danmosemsft is the one who logged the original issue #22656 he may tell more about this failure.

**Comment by danmosemsft** [comment]
Did it in  612c36d672297d0308058e1edc803a19dba9811d
