### ISSUE TITLE
Linq Permutation Cross and Multiple variable for Zip and Join

### ISSUE THREAD

**Issue by Thaina** [dotnet/corefx#23005]
I would like to have linq `Zip` and `Join` can take more than 2 collections. May be up to 8

```C#
public static IEnumerable<V> Zip<T0, T1, T2, T3, V>(this IEnumerable<T0> c0,IEnumerable<T1> c1,IEnumerable<T2> c2,IEnumerable<T3> c3,Func<T0,T1,T2,T3,V> func)
public static IEnumerable<V> Join<T0, T1, T2, T3,K,V>(this IEnumerable<T0> c0,IEnumerable<T1> c1,IEnumerable<T2> c2,IEnumerable<T3> c3,Func<T0,K> outer,Func<T1,K> inner1,Func<T2,K> inner2,Func<T3,K> inner3,Func<T0,T1,T2,T3,V> func)
``` 

And I would like to suggest addition function `Cross` (or any other name) that would yield permutations of collections

```C#
	public static IEnumerable<V> Cross<T0, T1, V>(this IEnumerable<T0> c0,IEnumerable<T1> c1,Func<T0,T1,V> func)
	{
		foreach(var v0 in c0)
			foreach(var v1 in c1)
				yield return func(v0,v1);
	}

var bools = new[] { false,true };
var ints = new[] { 0,1 };

bools.Cross(ints,(b,i) => (b,i));
// yield (false,0) (false,1) (true,0) (true,1)
``` 

Also `Cross` should has overload of multiple collections like `Zip`

**Comment by Clockwork-Muse** [comment]
.... Should it remove duplicates?  A better name might be `Permutate` or similar, but efficiently generating permutations is always an interesting puzzling problem.
You can get `Join` to do this in the case of two collections (say, with an always-true comparator).

Note that it's somewhat unusual to have more than two collections with the same equality key.

For the moment, there's nothing restricting you from writing these methods yourself.  A big reason to consider adoption of such a method would be if we need to add parallel versions, since 3rd-party extensions can't reference the underlying infrastructure there.

**Comment by Thaina** [comment]
@Clockwork-Muse 

> Should it remove duplicates?

I don't think it necessary. We can just call `Distinct` or create it as a HashSet beforehand. Most of the time collection would already unique when we want to cross it

> somewhat unusual to have / nothing restricting from writing these methods

I think it wouldn't pain to have. I already write it for use myself. Then I felt it too similar to the standard function. I want it to be just an overload in the same namespace as the original `Zip` and `Join` and would have the same coding logic

**Comment by LYP951018** [comment]
With my [proposal](https://github.com/dotnet/corefx/issues/24788) and deconstruction, we could write:

```cs
foreach (var (x, (y, z)) in seq1.Zip(seq2.Zip(seq3)))
```

That should be sufficient.

**Comment by svick** [comment]
Regarding `Join`: Is joining several collections on the same key actually that common? What are the use cases?

And I think that LINQ query syntax already handles that case decently:

```c#
from x1 in c1
join x2 in c2 on x1.Key equals x2.Key
join x3 in c3 on x1.Key equals x3.Key
select (x1, x2, x3)
```

---

Regarding `Cross`: That's a special case of `SelectMany`; the example can be written using that as: `bools.SelectMany(b => ints, (b, i) => (b, i))`. What's the advantage of `Cross` over `SelectMany`?

**Comment by Thaina** [comment]
@LYP951018 I think that would make it iterate collection too many times. While multiple variable `Zip` will iterate all collection once for each of it

@svick I don't use LINQ syntax so I want the equivalence functionality in LINQ extension method

And it would be the same reason as above. Nesting multiple of it with SelectMany result in repetition of iteration. I wish it should have multi variable function and that would iterate all collections only once

**Comment by svick** [comment]
@Thaina Can't you use `ToList()` to make sure the collections are iterated only once? The methods you propose would very likely have to do the same thing internally.

**Comment by Thaina** [comment]
@svick Sorry I was misunderstand. It not really make repeat iteration

Still it make a code become complicate.
Instead of `var (x,y,z) in a.Cross(b,c)` it will become
`var (x,(y,z)) in a.SelectMany((itemA) => b,(itemA,itemB) => (itemA,itemB)).SelectMany((pair) => c,( (itemA,itemB),itemC) => (itemA,itemB,itemC))`

**Comment by OmarTawfik** [comment]
I don't see a lot of upvotes or use cases for this pattern, and I see this better fit into an extension library for the subset of users that might need it. I'll close it for now, and please let me know if you still disagree, and we can reconsider/reopen.
