### ISSUE TITLE
HttpClient file descriptors leak running on docker

### ISSUE THREAD

**Issue by anjmao** [dotnet/corefx#23009]
I was doing some .NET CORE vs Golang performance testing and noticed that HttpClient keeps a lot of HTTP connections in TIME_WAIT state.  I'm using Docker `microsoft/dotnet:2.0.0-preview2-sdk` image.

1.  Running .NET CORE for 100s I got about **3000** HTTP connections in TIME_WAIT state.
2. Running Golang for 100s I got only 4 HTTP connections in TIME_WAIT state.

Is this is a bug in HttpClient or this is normal behaviour?

All source code can be found here https://github.com/anjmao/netcore-vs-golang with instructions how to run it.

**Comment by anjmao** [comment]
@benaadams Hi, I'm trying to set MaxConnectionsPerServer but I feel like it is not working. I found this this code
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.MultiAgent.cs#L261

Is there any tutorial or documentation how I can enable EventSourceTrace and see logs inside docker container? Thanks in advice.

**Comment by stephentoub** [comment]
> Is there any tutorial or documentation how I can enable EventSourceTrace and see logs inside docker container?

System.Net.Http on unix uses an EventSource for tracing.  There are two ways to enable that tracing:
1. Use perfcollect: https://github.com/dotnet/coreclr/blob/027180d8ef4a8a0e50f4cba3ad985af38882f5ef/Documentation/project-docs/linux-performance-tracing.md
2. In your project, instantiate an EventListener-derived type to receive all of the events, and then do with them what you want.  For example, if you were to copy-and-paste this class into your project (https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Diagnostics/Tracing/ConsoleEventListener.cs) and instantiate one at the beginning, the tracing would be output to the console.  You could modify it to write to a file or whatever you wanted.

**Comment by anjmao** [comment]
Thanks @stephentoub :)

Some more investigations:
1) Set Env variable CURLHANDLER_DEBUG_VERBOSE=true
2) Set HttpClient MaxConnectionsPerServer=1000
3) Run wrk with 50 connections for only 10 seconds.
4) At first it looks like connections are reused and I see curl trace messages `Re-using existing connection!`
5) After some time I start getting `Connection cache is full, closing the oldest one.` https://github.com/curl/curl/blob/master/lib/multi.c#L503

To me this sounds like libcurl cache max connections number is way lower than max connections on http client this is why they are closed and not reused.

**Comment by karelz** [comment]
@wfurt can you please take a look?
cc @Priya91

**Comment by wfurt** [comment]
ok @karelz , I'll take a look.
Do we know if this is docker specific @anjmao ? The notes in source repo claims you are running on MacBook. Is that correct? I'll try to reproduce it locally and any more specific information may be useful.

**Comment by anjmao** [comment]
@wfurt Hi, I made all tests on docker, but was getting similar results running on mac. You should be able to reproduce it very easily but cloning repo and running docker compose. Steps are described in README.md, but let me know if something is not working for you :)

**Comment by wfurt** [comment]
hi @anjmao, sorry for the delay. I was able to get this finally running.  Since this is quite trivial I did run API directly using go run and then I use use "dotnet run" to start netcore app. 
The connection to 5002 port peaked at 512 and stay flat through out the test run. 

Since the original post was on preview build, could you please try it again with released version (or possibly use 2.1 preview for comparison)

**Comment by wfurt** [comment]
BTW I'm running without containers on osx 10.12.6

**Comment by anjmao** [comment]
Hi @wfurt 

I just update repository code and .net docker image to use `microsoft/dotnet:2.0-sdk`. 
Here are results after wrk stopped running. It seems that updating version didn't helped and problem still exists. Could you try running it on docker with docker-compose to make sure you are also reproducing it? Thanks 👍 
<img width="1075" alt="netcore_file_descriptors" src="https://user-images.githubusercontent.com/3028012/37520098-6626f7e4-2924-11e8-9716-e0bcea3b9138.png">

**Comment by wfurt** [comment]
ok, I'll give it try. BTW When I counted my connections I only counted connections to port 5002 e.g. connection  caused by HttpClient. Also sockets in TIME-WAIT state is not sign of descriptor leak. That is mandatory state _after_ TCP connection was closed. 
http://www.tcpipguide.com/free/t_TCPOperationalOverviewandtheTCPFiniteStateMachineF-2.htm

You can track socket usage with
lsof -n | grep ^dotnet

**Comment by karelz** [comment]
Not actionable. If there repro on .NET Core 2.1, please let us know.
