### ISSUE TITLE
System.Memory: how does the Xamarin.Mac dependency end up in the nuspec?

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/corefx#23019]
I just looked at the System.Memory package on https://www.nuget.org/packages/System.Memory and wondered why it has an explicit entry for Xamarin.Mac in the nuspec:

```
<dependencies>
    <group targetFramework=".NETCoreApp2.0">
    <dependency id="Microsoft.NETCore.Platforms" version="2.0.0-preview2-25405-01" />
    <dependency id="System.Runtime.CompilerServices.Unsafe" version="4.4.0-preview2-25405-01" exclude="Compile" />
    </group>
    <group targetFramework=".NETStandard1.0">
    <dependency id="NETStandard.Library" version="1.6.1" />
    <dependency id="System.Runtime.CompilerServices.Unsafe" version="4.4.0-preview2-25405-01" exclude="Compile" />
    </group>
    <group targetFramework=".NETStandard2.0">
    <dependency id="System.Numerics.Vectors" version="4.4.0-preview2-25405-01" exclude="Compile" />
    <dependency id="System.Runtime.CompilerServices.Unsafe" version="4.4.0-preview2-25405-01" exclude="Compile" />
    </group>
    <group targetFramework=".NETPortable4.5-Profile259">
    <dependency id="System.Runtime.CompilerServices.Unsafe" version="4.4.0-preview2-25405-01" exclude="Compile" />
    </group>
    <group targetFramework="Xamarin.Mac2.0">
    <dependency id="System.Runtime.CompilerServices.Unsafe" version="4.4.0-preview2-25405-01" exclude="Compile" />
    </group>
</dependencies>
```

I looked at the csproj's in corefx but couldn't figure out how this ends up there. @weshaggard ?

**Comment by weshaggard** [comment]
@ericstj can point it out.

**Comment by ericstj** [comment]
We look at assembly dependencies then map those to packages.  We set up dependency groups for the TFM of that assembly with all the dependencies.

For any portable TFM dependency group(EG: netstandard2.0, portable-*) we look at the frameworks that are compatible with that group.  Then we look if those compatible TFMs have inbox support for the dependencies.  If so, then we'll copy the dependency group and remove some dependencies.

After doing all this we remove any redundant dependency groups and map packages to meta-packages to further simplify the nuspec.  You can see this here: https://github.com/dotnet/buildtools/blob/5d44d077f86aebe3983d446454b83783916d83c6/src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets#L583-L751.

In this case what's happening is the profile259 assembly applies to most of the xamarin profiles.  This profile includes most of the dependencies inbox, so it only has a dependency on Unsafe remaining.

Xamarin.mac is not treated as compatible with profile259 by the nuget we're using when building the packages, so it gets its own dependency group, projected from the netstandard2.0 group.

I suspect if we updated to a NuGet version with this change: https://github.com/NuGet/NuGet.Client/commit/9bb3952a37ac26664d11079fea5d2b7b352264ed the specific dependency group would go away.

**Comment by akoeplinger** [comment]
Thanks Eric.
