### ISSUE TITLE
Move source code from dotnet/coreclr/src/corefx to this repository

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#2301]
Putting source code there is a temporary measure to keep things moving forward without blocking on having the right infrastructure in place for building native code in this repository.

**Comment by sharwell** [comment]
:bulb: When you are ready to bring it over, if you want to keep the history you can use a git subtree merge. I describe something similar [for this project](https://github.com/rackerlabs/dotnet-collections/blob/master/CONTRIBUTING.md), *however* my use of `--squash` does not preserve history.

**Comment by saper** [comment]
On one hand native shims might go down to modules that closely match some portions of the managed code, so it is better if they are packaged together (in the CoreFX code).

On the other hand there is one important issue which makes me think maybe they should stay
in CoreCLR repo: There should be one place to deal with various build issues - compilers, flags, platform libraries, runtimes etc. etc. Those things are have its own complexity and overflowing this onto CoreFX seems a bit too much.

It pretty much depends if we are going to end up with a couple of general-purpose native shims that can be reused across managed packages (in this case it might be better to stay with CoreCLR) or they will serve only one or two managed packages.

**Comment by nguerrera** [comment]
Fixed by #2445, #2457, and dotnet/coreclr#1280
