### ISSUE TITLE
XDeclaration failed to display "<?xml ... ?>" when using ToString()

### ISSUE THREAD

**Issue by fletchsod-developer** [dotnet/corefx#23024]
var xml = new XDocument(
        new XDeclaration("1.0", "UTF-8", "yes"),
        new XElement("Envelope", "")
    );

It works when you do this.  It showed < ? xml version="1.0" encoding="utf-8" standalone="yes" ? > in the text file.

    xml.Save(@"Xml\foooo.xml");

But it does not work when you do the ToString() object.  It did NOT showed < ? xml version="1.0" encoding="utf-8" standalone="yes" ? > in xml string.

    var debug = xml.ToString();

**Comment by krwq** [comment]
Try this:

```csharp
            var xml = new XDocument(
                new XDeclaration("1.0", "UTF-8", "yes"),
                new XElement("Envelope", "")
            );

            var sb = new StringBuilder();
            using (var writer = new StringWriter(sb))
            {
                xml.Save(writer);
            }

            Console.WriteLine(sb.ToString());
```

**Comment by fletchsod-developer** [comment]
We can't use any kind of Builder objects cuz it ruin the computer resources.

**Comment by krwq** [comment]
@fletchsod-developer could you please create separate issue with more details on that? ToString no matter how you implement it will need to create some kind of builder object underneath... String needs to go into memory either way - if you have perf issues you might try not to create a string at all and pass stream where your object needs to go directly to Save (i.e. network stream)
