### ISSUE TITLE
Proposal: Span-based methods on Encoder/Decoder

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23057]
In https://github.com/dotnet/corefx/issues/22431, we agreed on new span-based methods on Encoding, but we didn't discuss the lower-level Encoder/Decoder types.  @jkotas reminded me of this in https://github.com/dotnet/coreclr/pull/13269#issuecomment-321020525, and upon taking a look, I expect methods like the following are the ones we'd want to add:
```C#
namespace System.Text
{
    public abstract class Encoder
    {
        public virtual void Convert(ReadOnlySpan<char> chars, Span<byte> bytes, bool flush, out int charsUsed, out int bytesUsed, out bool completed);
        public virtual int GetByteCount(ReadOnlySpan<char> chars, bool flush);
        public virtual int GetBytes(ReadOnlySpan<char> chars, Span<byte> bytes, bool flush);
        ...
    }

    public abstract class Decoder
    {
        public virtual void Convert(ReadOnlySpan<byte> bytes, Span<char> chars, bool flush, out int bytesUsed, out int charsUsed, out bool completed);
        public virtual int GetCharCount(ReadOnlySpan<byte> bytes, bool flush);
        public virtual int GetChars(ReadOnlySpan<byte> bytes, Span<char> chars, bool flush);
    }
}
```
@tarekgh, thoughts, both on exposing such methods and on the specific ones I've listed?  These are basically just span-based versions of the existing pointer-based virtuals on those two types.

**Comment by tarekgh** [comment]
>  thoughts, both on exposing such methods and on the specific ones I've listed? These are basically just span-based versions of the existing pointer-based virtuals on those two types.

Encoder and Decoder are used exactly as the Encoding APIs. it just helps in keeping the state so you can encode/decode the data with multiple calls. As we exposed Encoding APIs to use Spans, it makes a lot of sense to expose the Encoder and Decoder APIs using the spans too.

The list of APIs you have in your proposal is good to me too. 

side note, we are using the encoders and decoders in the implementation of Streams and Xml. so may be we'll need to look at the usage if we can benefit from using the spans there.

**Comment by stephentoub** [comment]
Thanks, Tarek.
