### ISSUE TITLE
System.Net.Http.Functional.Tests.ManagedHandler_DiagnosticsTest.SendAsync_ExpectedDiagnosticSourceUrlFilteredActivityLogging failed in CI

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#23102]
Failed test: System.Net.Http.Functional.Tests.ManagedHandler_DiagnosticsTest.SendAsync_ExpectedDiagnosticSourceUrlFilteredActivityLogging 

MESSAGE:
~~~
Exit code was 139 but it should have been 42\nExpected: True\nActual: False
~~~
STACK TRACE:
~~~
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() 
in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_centos7.1_debug/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 181 
at System.Net.Http.Functional.Tests.DiagnosticsTest.SendAsync_ExpectedDiagnosticSourceUrlFilteredActivityLogging() 
in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_centos7.1_debug/src/System.Net.Http/tests/FunctionalTests/DiagnosticsTests.cs:line 387
~~~

**Comment by danmosemsft** [comment]
@Jiayili1 please include URL and platform thanks.

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170810.02/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ManagedHandler_DiagnosticsTest~2FSendAsync_ExpectedDiagnosticStopOnlyActivityLogging

**Comment by Jiayili1** [comment]
@danmosemsft Yes, I forgot it, I will remember it, thanks.

**Comment by Jiayili1** [comment]
Failed again on OuterLoop_netcoreapp_rhel7.2_debug, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_rhel7.2_debug/137/testReport/System.Net.Http.Functional.Tests/ManagedHandler_DiagnosticsTest/SendAsync_ExpectedDiagnosticSourceLogging/

**Comment by Jiayili1** [comment]
failed again in CI: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_centos7.1_debug/146/testReport/System.Net.Http.Functional.Tests/ManagedHandler_DiagnosticsTest/SendAsync_ExpectedDiagnosticStopOnlyActivityLogging/

**Comment by Jiayili1** [comment]
failed again in CI: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_portablelinux_debug/147/testReport/System.Net.Http.Functional.Tests/ManagedHandler_DiagnosticsTest/SendAsync_ExpectedDiagnosticSourceUrlFilteredActivityLogging/

**Comment by Jiayili1** [comment]
Test failed with same issue: System.Net.Http.Functional.Tests.ManagedHandler_DiagnosticsTest.SendAsync_HttpTracingEnabled_Succeeds 

Configuration: outerloop_netcoreapp_centos7.1_release

MESSAGE:
~~~
Exit code was 139 but it should have been 42\nExpected: True\nActual: False
~~~
STACK TRACE:
~~~
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_centos7.1_release/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 178
~~~

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_centos7.1_release/145/testReport/System.Net.Http.Functional.Tests/ManagedHandler_DiagnosticsTest/SendAsync_HttpTracingEnabled_Succeeds/

**Comment by Jiayili1** [comment]
This test failed with same issue: System.Net.Http.Functional.Tests.ManagedHandler_HttpClientHandlerTest.GetAsync_ServerNeedsAuthAndNoCredential_StatusCodeUnauthorized 

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_centos7.1_debug/153/testReport/System.Net.Http.Functional.Tests/ManagedHandler_HttpClientHandlerTest/GetAsync_ServerNeedsAuthAndNoCredential_StatusCodeUnauthorized/

**Comment by Jiayili1** [comment]
failed again in CI: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_portablelinux_debug/165/testReport/System.Net.Http.Functional.Tests/ManagedHandler_DiagnosticsTest/SendAsync_ExpectedDiagnosticStopOnlyActivityLogging/

**Comment by Jiayili1** [comment]
This test: System.Net.Http.Functional.Tests.ManagedHandler_HttpClientHandler_DefaultProxyCredentials_Test.ProxySetViaEnvironmentVariable_DefaultProxyCredentialsUsed

failed with same issue, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_centos7.1_debug/167/testReport/System.Net.Http.Functional.Tests/ManagedHandler_HttpClientHandler_DefaultProxyCredentials_Test/ProxySetViaEnvironmentVariable_DefaultProxyCredentialsUsed_useProxy__False_/

**Comment by Jiayili1** [comment]
failed again: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_centos7.1_debug/176/testReport/System.Net.Http.Functional.Tests/ManagedHandler_DiagnosticsTest/SendAsync_ExpectedDiagnosticSourceNewAndDeprecatedEventsLogging/

**Comment by Jiayili1** [comment]
failed again in outerloop_netcoreapp_debian8.4_release, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_debian8.4_release/191/testReport/System.Net.Http.Functional.Tests/DiagnosticsTest/SendAsync_ExpectedDiagnosticSourceLogging/

**Comment by Jiayili1** [comment]
following test failed with same issue, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171026.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandler_DefaultProxyCredentials_Test~2FProxySetViaEnvironmentVariable_DefaultProxyCredentialsUsed(useProxy:%20True)

The test `System.Net.Http.Functional.Tests.HttpClientHandler_DefaultProxyCredentials_Test/ProxySetViaEnvironmentVariable_DefaultProxyCredentialsUsed(useProxy: True)` has failed.

Exit code was 139 but it should have been 42
    Expected: True
    Actual:   False

        Stack Trace:

           at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() in /root/corefx-1088740/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 189
       at System.Net.Http.Functional.Tests.HttpClientHandler_DefaultProxyCredentials_Test.ProxySetViaEnvironmentVariable_DefaultProxyCredentialsUsed(Boolean useProxy) in /root/corefx-1088740/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.DefaultProxyCredentials.cs:line 127
Build : Master - 20171026.01 (Core Tests)
Failing configurations:
- suse.422.amd64-x64
  - Release

**Comment by karelz** [comment]
Most of the failures were in ManagedHandler. Closing for now as the tests are disabled and tracked by general ManagedHandler work.

Day | Build | OS | Error message
-- | -- | -- | -- 
8/1 | 20170801.01 | Ubuntu17.04 | Assert.Equal() Failure\nExpected: 42\nActual:   -117 | ManagedHandler - SendAsync_ExpectedDiagnosticSourceUrlFilteredActivityLogging
8/22 | 20170822.01 | Centos73 | Exit code was 139 but it should have been 42 | ManagedHandler - SendAsync_ExpectedDiagnosticSourceUrlFilteredActivityLogging
9/25 | 20170925.03 | Ubuntu17.04 | Exit code was 139 but it should have been 42 | ManagedHandler - SendAsync_ExpectedDiagnosticSourceUrlFilteredActivityLogging
10/26 | 20171026.01 | Suse42.2 | Exit code was 139 but it should have been 42 | ProxySetViaEnvironmentVariable_DefaultProxyCredentialsUsed

**Comment by karelz** [comment]
Test failures tracked by #26042
