### ISSUE TITLE
Update package versions to service release/1.1 and 1.0 branches.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#23119]
I went through the history of the release/1.1 branch, this [commit](https://github.com/dotnet/corefx/commit/9e98f24f508d2cda97f10474a86052f51bc9c7e3), which is an update after the servicing release. From then these are the concrete product commits,

1. [Interop.MountPoints.cs](https://github.com/dotnet/corefx/commit/3d2debcf3f4fb7ce06f58c0b617348835e9036c8) by @wfurt 
2. [WinHttpHandler](https://github.com/dotnet/corefx/commit/454bdeb2ef477344b8626307892f442bff2a3106) by @davidsh 

We need to update the package and assembly versions of the libs where these changes need to serviced for 1.1 release.

refer pr #23113

**Comment by karelz** [comment]
@Priya91 what else is left? Is it 1.1 or 2.1 bug?

**Comment by Priya91** [comment]
@Priya91 what else is left? Is it 1.1 or 2.1 bug?

The bug is not fixed, this is to update the package versions of the libs that need to be serviced as part of 1.1/1.0 servicing release. @danmosemsft Can you provide details of when this release matches with 2.1

**Comment by danmosemsft** [comment]
@karelz I will share servicing info offline. As @Priya91 mentions, she will be making changes to make sure the fixes mentioned above are picked up in the next servicing event.

**Comment by danmosemsft** [comment]
This is presumably needed in 1.0 also.

**Comment by danmosemsft** [comment]
Confirmed it is -- at least, the driveinfo fix is not showing up in tests.

**Comment by Priya91** [comment]
> This is presumably needed in 1.0 also.

Have a PR up for 1.0 as well #23274

**Comment by Priya91** [comment]
this is fixed.
