### ISSUE TITLE
Request: please add a safe constructor to System.Reflection.Metadata.MetadataReader

### ISSUE THREAD

**Issue by ljw1004** [dotnet/corefx#2312]
The three constructors of MetadataReader are all declared unsafe, and all take byte* parameters. They explain in the comments:
```cs
/// Use <see cref="PEReader.GetMetadata()""/> to obtain metadata from a PE image.
```

Please don't make us go through this extra step! There should be a constructor for MetadataReader that takes a PEReader directly. This new constructor will save most users two pointless lines of code. And because this new constructor doesn't need to be unsafe, it will be possible to call it from VB.

```cs
unsafe
{
    var metadata = pereader.GetMetadata();
    return new System.Reflection.Metadata.MetadataReader(metadata.Pointer, metadata.Length);
}
```

I don't think there's a strong "decoupling" argument. Both `PEReader` and `MetadataReader` are defined in the same assembly, the same NuGet package.

**Comment by SantiFdezM** [comment]
There is no need to use the metadata information out of the PEReader. You could only do this:

``` C#
_peReader = new PEReader(fileStream);
_mdReader = _peReader.GetMetadataReader();
```

**Comment by ljw1004** [comment]
@SantiFdezM I don't think I understand... What I want is an object of type `MetadataReader`, so I can enumerate all the types contained in the assembly. The code you posted will give me `_mdReader` of type `PEMemoryBlock`, but I don't see where to go from there?

**Comment by SantiFdezM** [comment]
@ljw1004 the code that I posted will give you the ` ` ` MetadataReader ` ` ` object itself with all the iterators you'll need. You just need to create your ` ` ` PEReader ` ` ` and call its ` ` ` GetMetadataReader() ` ` ` method and that's where you get the actual  ` ` ` MetadataReader ` ` ` you are trying to get. That without constructor call needed.
So my ` ` ` _mdReader  ` ` ` variable in my code is of type ` ` ` MetadataReader ` ` ` not of type  ` ` ` PEMemoryBlock  ` ` `.

**Comment by mellinoe** [comment]
This method?

https://github.com/dotnet/corefx/blob/94fef02bbe2971a429b3e6ec13b445b10d649a82/src/System.Reflection.Metadata/src/System/Reflection/Metadata/PEReaderExtensions.cs#L68

**Comment by ljw1004** [comment]
@SantiFdezM  @mellinoe thank you very much! I guess being a VB user I'm not in the habit of "using" all the namespaces of types I use (instead I rely on VB's smart name lookup rules). That meant that I didn't import the System.Reflection.Metadata namespace. And because the extension methods are all in a [EditorBrowsable(Never)] class, I'd never discovered them in intellisense directly.

Got it now. Thank you!
