### ISSUE TITLE
ManagedHandler: Support 1.0 requests

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23132]
Currently the handler throws an exception for 1.0 requests.  It needs to tolerate them.

**Comment by wfurt** [comment]
Do we have better list of what needs to be done @stephentoub ?
I can probably make the failing tests pass but I'm not sure if that is enough.

I look at the code and RFC and as minimum it seems like we should throw exception if anybody wants to use chunking & 1.0. There is no Keep-Alive and multiple requests over same socket. Host: is optional (yet request may include it IMHO) There are some other differences but I'm not sure to what level of compliance we need to go. I feel in worst case we the request may have some headers and they will be ignored by server.

On related note, do we care about HTTP 0.9? I would not with exception allowing "GET /" e.g. missing version string is treated and .9 and implied.
