### ISSUE TITLE
[ManagedHandler] Basic auth can't handle ':' in domain name

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23135]
Some of the theory inputs to Proxy_BypassFalse_GetRequestGoesThroughCustomProxy are failing as a result.

**Comment by geoffkizer** [comment]
Priya -- I think you wrote some code to handle this for digest -- can we do the same for Basic here?

**Comment by Priya91** [comment]
> Priya -- I think you wrote some code to handle this for digest -- can we do the same for Basic here?

The RFC states that username part of basic auth should not contain ':' [here](https://tools.ietf.org/html/rfc2617#section-2)

```
To receive authorization, the client sends the userid and password,
   separated by a single colon (":") character, within a base64 [7]
   encoded string in the credentials.

      basic-credentials = base64-user-pass
      base64-user-pass  = <base64 [4] encoding of user-pass,
                       except not limited to 76 char/line>
      user-pass   = userid ":" password
      userid      = *<TEXT excluding ":">
      password    = *TEXT

   Userids might be case sensitive.
```

**Comment by geoffkizer** [comment]
I'm not sure.  WinHttpHandler does something here to make this work.  @davidsh do you know what the right behavior here is, and where is this defined?

I thought there were other tests failing because of illegal chars in username as well, but I can't find them now...

**Comment by davidsh** [comment]
>I'm not sure. WinHttpHandler does something here to make this work. @davidsh do you know what the right behavior here is, and where is this defined?

I'm not sure what question is being asked.  In general, username and domain names in Windows cannot have ":" characters in them.  WinHttpHandler doesn't have any specific code to enforce that.  It will take the NetworkCredential object as-is.  The only thing it is doing "special" is that if there is a non-empty string for the .Domain property of the NetworkCredential, it is using that as well as .UserName, combining it, and then passing it down to WinHTTP.  WinHTTP ony takes "username" and "password" for explicit credentials to be set.  So, WinHttpHandler will take the domain name and combine it with backslash and the username like this:

```c#
var cred = new NetworkCredential("username", "password", "domain");

// Call WinHTTP passing it a username and password
string username = cred.UserName;
string password = cred.Password
if (!string.IsNullOrEmpty(cred.Domain))
{
    username = cred.Domain + "\\" + username;
}

WinHttpAPI(username, password);
```

**Comment by karelz** [comment]
Currently we throw `NotImplementedException`. I would suggest to change the exception to `ArgumentException` (or `ArgumentOutOfRangeException` / `NotSupportedException`).

**Comment by pjanotti** [comment]
@geoffkizer @karelz why enforcing the RFC on the client in this case? Shouldn't we do the same as WinHttpHandler?

**Comment by geoffkizer** [comment]
Yes, we should probably do the same as WinHttpHandler here.  I assume CurlHandler does the same?

**Comment by davidsh** [comment]
>Yes, we should probably do the same as WinHttpHandler here. I assume CurlHandler does the same?

We should try to match .NET Framework.  But there are some validations that are not done even in .NET Framework and we let the lower layers simply fail.

**Comment by karelz** [comment]
It is not just enforcing RFC, but rather making sure we produce valid format/output. For ':' we can't produce valid format. I assume other implementations (.NET Framework, WinHttpHandler/CurlHandler) will also fail in some way.
We should just capture in the tests that ManagedHandler fails in a particular way.

It is corner case, invalid scenario, so I am not too worried about it -- addressing it in Future is fine.
We should however have some positive tests for the auth scenario (without ':'). By looking at the code, I am not sure if we have them - @Priya91?

**Comment by wfurt** [comment]
could the ':' in name be encoded? I can try to set up repro case on Unix - where the system probably does not care but it may be hard to find client/server combination which will handle that. I suspect most packages will simply use first ':'

**Comment by geoffkizer** [comment]
> It is not just enforcing RFC, but rather making sure we produce valid format/output. For ':' we can't produce valid format. I assume other implementations (.NET Framework, WinHttpHandler/CurlHandler) will also fail in some way.

Are you sure?  The tagged test looks like it succeeds.

If we are punting this because it's a corner case and we don't care, then fine.  But we aren't matching the behaviors of other handlers here -- winhttp, curl, netfx.  So it's a real issue.  That's why it was logged in the first place.

**Comment by karelz** [comment]
I am not sure it fails. Looking at the format I don't see how it could work though, but I am be wrong as you point out.

I would personally punt it as corner case out of 2.1 regardless if I am wrong or right :).
We should make sure we have at least some tests running (without ':') for ManagedHandler in 2.1 though.

**Comment by pjanotti** [comment]
Created a PR to separate the test cases. Making the managed handler match the behavior of the other handlers is trivial (see below). I don't know what .NET Framework does for such cases but at least in CoreFX the managed handler is the different one.

```c#
        public static string GetBasicTokenForCredential(NetworkCredential credential)
        {
            Debug.Assert(credential != null);

            string username = string.IsNullOrEmpty(credential.Domain) ? credential.UserName :
                credential.Domain + "\\" + credential.UserName;
            string basicToken = username + ":" + credential.Password;

            return Convert.ToBase64String(Encoding.UTF8.GetBytes(basicToken));
        }
```

**Comment by geoffkizer** [comment]
That is trivial.  But I'm not sure it's the right behavior... it will likely cause a real server to reject the auth header.

**Comment by wfurt** [comment]
BTW htpasswd on Linux and Mac does not allow ':' in name either.

$ htpasswd -c /tmp/aa "foo:bar"
htpasswd: username contains illegal character ':'

**Comment by pjanotti** [comment]
Yeah, neither Windows nor Unix will like that. I was a bit worried that the test existed to ensure that some legacy behavior was preserved but reading the history of the test file I see that the ':' was added (#7494) to test encoding of credentials for CurlHandler. 

So it seems we have 3 behaviors:

1. ManagedHandler: throws
2. CurlHandler: encodes before concatenating
3. WinHttpHandler: concatenates as given by network credentials

**Comment by stephentoub** [comment]
> So it seems we have 3 behaviors:

What does netfx do?

**Comment by pjanotti** [comment]
It passes the tests, its code is equivalent to:

```c#
            string rawString = ((!string.IsNullOrWhiteSpace(domain)) ? (domain + "\\") : "") + username + ":" + password;
```

**Comment by pjanotti** [comment]
I was looking at the disassembly, here is the actual source: https://referencesource.microsoft.com/#System/net/System/Net/_BasicClient.cs,107
