### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23134]
ManagedHandler should support HTTP/2.

**Comment by kasper3** [comment]
Should we add a TODO referencing to this issue in https://github.com/dotnet/corefx/blob/b2893f07cf61dae81d424dd676a0d903a36a10c2/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/SocketsHttpHandler.cs#L348 and throw `NotSupportedException(SR.net_http_unsupported_version)` if `Version.Major > 1`?

**Comment by stephentoub** [comment]
No. If HTTP/2 isn't supported, we downgrade to 1.1; that's how it's always worked.

**Comment by stephentoub** [comment]
> could we filter out a (high-level) checklist of actionable items from the RFC? :)

Feel free to do so.

**Comment by geoffkizer** [comment]
We can close it.
