### ISSUE TITLE
[ManagedHandler] Disposing the handler should initiate cancellation of requests

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23131]
According to the comment, "the ManagedHandler isn't correctly handling disposal of the handler. It should cause the outstanding requests to be canceled with OperationCanceledExceptions, whereas currently it's resulting in ObjectDisposedExceptions."

**Comment by karelz** [comment]
We need to figure out if it is architectural problem.
The symptom itself is lower pri.

**Comment by Tratcher** [comment]
How is this different from HttpClient canceling them on Dispose?
https://github.com/dotnet/corefx/blob/024f17e558dcc2666a336d6d60c9da3981d1d3db/src/System.Net.Http/src/System/Net/Http/HttpClient.cs#L567

**Comment by stephentoub** [comment]
@Tratcher, see the issue description. Apparently the wrong behaviors are resulting. I've not looked into it.

**Comment by davidsh** [comment]
>How is this different from HttpClient canceling them on Dispose?

HttpClient.Dispose() does 2 things.  It cancels pending requests itself via the _pendingRequestsCts object.  And it disposes the handler assuming it owns it (i.e. HttpClient constructor was called w/ ownsHandler=true).

However, there might be cases where HttpClient doesn't own the handler.  And then someone just disposes the handler on their own.  In that case, they will bypass the HttpClient "feature" that cancels pending requests.
