### ISSUE TITLE
[ManagedHandler] SSL proxy tunneling is not yet implemented

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23136]
It should be implemented.

https://github.com/dotnet/corefx/blob/b265a0f0066dbce3cf4845c25444fe85266c81d0/src/System.Net.Http/src/System/Net/Http/Managed/HttpProxyConnectionHandler.cs#L62-L66

**Comment by karelz** [comment]
Blocking release: Needed for ManagedWebSockets to satisfy all requirements.

**Comment by wfurt** [comment]
closed by #27220
