### ISSUE TITLE
ManagedHandler: ManagedHandler_DefaultCredentialsTest tests are disabled

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23140]
These tests are disabled for the managed handler.  They need to be investigated and either src or tests fixed.

**Comment by wfurt** [comment]
This one is only for windows platforms.

**Comment by Priya91** [comment]
These tests are for testing credentials with negotiate and ntlm auth. The infrasturcture to run these tests doesn't exist yet, closing this bug as dupe of #10041

**Comment by davidsh** [comment]
cc: @karelz

**Comment by Priya91** [comment]
@davidsh I was just creating a PR as we speak :)

**Comment by davidsh** [comment]
ok.  sounds good.  But to avoid confusion, please close the issue after the PR? As you can see, I was confused. :)

**Comment by karelz** [comment]
Should we assign it to @Priya91 then? Or will it be just partial fix?
