### ISSUE TITLE
[ManagedHandler] Avoid string allocations while parsing headers

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23147]

**Comment by karelz** [comment]
@geoffkizer can you please check if we're ready to close it.

**Comment by geoffkizer** [comment]
@stephentoub Are there specific allocations you had in mind here? #23186 should have helped a lot here, is there more we should consider?

**Comment by stephentoub** [comment]
Nothing further at this point. We can address individual cases as they arise.
