### ISSUE TITLE
Signature Decoder not providing ValueType or Class value for Types.

### ISSUE THREAD

**Issue by SantiFdezM** [dotnet/corefx#2314]
On the metadata reader, the signature decoder is not providing the valuetype or class value encoded on the signature blob.

**Comment by tmat** [comment]
Which API do you specifically mean?

**Comment by SantiFdezM** [comment]
@tmat in System.Reflection.Metadata.Decodig under dev/metadata branch

**Comment by tmat** [comment]
Do you mean that ```public static TType DecodeType<TType>(Handle handle, ISignatureTypeProvider<TType> provider)``` should have a "isValueType" parameter that reflects that distinguishes between CLASS and VALUE type codes in the signature? 

We don't expose that information intentionally. For a couple of reasons. First, the flag is not necessary for type resolution. The resolution should actually not depend on whether you're looking for value type or reference type. Second, in WinMD files some value types are projected to reference types and vice versa. We would need to perform that projection here just to pass the API a flag that it doesn't need.

Do you have a scenario that requires knowledge of the flag?

**Comment by SantiFdezM** [comment]
Yes I mean that API. So now I'm working on a ILDasm Library built at top of the Metadata Reader. I need that flag in order to know when should I expose the valuetype or class prefix on types in IL.

So right now I had to add the class prefix on all of the types I find, but there are some cases where the type signature doesn't have to expose that for example in IL instructions when receiving a type as an argument there are some cases it doesn't expose any prefix.

So I need that flag, to know when to expose it and if so, know if either I need to expose valuetype or class prefix.

**Comment by tmat** [comment]
@SantiFdezM Do you need to exactly match ildasm output? Why don't you just omit the flag. It's not really useful anyways.

**Comment by SantiFdezM** [comment]
@tmat yes we need to match the output, that's the goal of the project, being able to roundtrip an assembly through my library and then through ilasm and get a running assembly.

**Comment by weitzhandler** [comment]
I have a similar issue, I can't find Type.GetTypeInfo either (on DNX).

https://github.com/aspnet/dnx/issues/2299

**Comment by mikedn** [comment]
@weitzhandler That sounds like an unrelated issue, `GetTypeInfo` is an extension method so you won't find it on `Type`. It's in `System.Reflection.IntrospectionExtensions`.

**Comment by weitzhandler** [comment]
@mikedn that I didn't know thanks!

**Comment by SantiFdezM** [comment]
@nguerrera Adding Nick to the thread

**Comment by nguerrera** [comment]
I think being able to match the output of ildasm exactly is valuable. We could pass some form of promise that only evaluated the projection if you asked for it.

**Comment by tmat** [comment]
Yes.

**Comment by SantiFdezM** [comment]
Probably changing the Provider Interface to have some flag configuration to ask for that valuetype or class flag?
