### ISSUE TITLE
ManagedHandler: Support canceling opening connections

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23151]
Right now we use the instance socket.ConnectAsync method, which doesn't give us a way to cancel the connection.  We should investigate other approaches that would allow us to do so, e.g. with SocketAsyncEventArgs and its connection cancellation support, or worst case, disposing of the socket (though that might have reliability concerns).

**Comment by koenigst** [comment]
I will extend ConnectHelper with cancellation support as this is the starting point from my point of view.

I still have some concerns about HttpConnectionPool. To support cancellation we would also have to extend the connection pool to support cancellation. This is a bit of a refactoring especially when there is no connection available and a ConnectionWaiter is enqueued. Would it be possible to split this in two pull requests to reduce the complexity?

**Comment by stephentoub** [comment]
> Would it be possible to split this in two pull requests to reduce the complexity?

Sure

**Comment by stephentoub** [comment]
@koenigst, are you still working on this?

**Comment by stephentoub** [comment]
@koenigst, thanks for your interest.  As it's been a month and there are a few things queued behind this, I'm going to go ahead and submit a fix for it.  Thanks, again.
