### ISSUE TITLE
[ManagedHandler] Determine how to ship it, and implement that

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23166]
Opt-in/Opt-out? Enabled via an environment variable? Shipped as public API? Etc.  We need a supported way to allow for granular use of ManagedHandler on per-instance basis and not just process-wide.

**Comment by steji113** [comment]
In my personal opinion, with the managed implementation being so new, as a user I would expect this to be opt-in functionality for the 2.1.0 time frame. I think the trade off is that you are opting in to better performance, but perhaps a few rough edges in terms of stability until it gets some real-world, production usage. Post 2.1.0 I think it would be viable to be switched to being the default handler, especially on Linux where the implementation was pretty new anyways.

Also, in terms of how you opt in, I think an environment variable should be fine. Just my .2 cents.

**Comment by karelz** [comment]
We will need a way for Preview1 to opt in into ManagedHandler process-wide, but not via environment variable.
We should reuse `AppContext` settings in appsettings.json - @wfurt can you please add it? I propose name: `DefaultHttpClientHandlerToManagedHandler`
@stephentoub are you ok with the name? (if we decide to rename `ManagedHandler` to something else post-Preview1, we can rename it later, we just need something in now for our early adopters to use in the interim)

FYI: For 2.1 we are looking into exposing ManagedHandler as public class.

**Comment by stephentoub** [comment]
> process-wide but not via environment variable

Why?

**Comment by eerhardt** [comment]
> We should reuse AppContext settings in appsettings.json

Do you mean `AppName.runtimeconfig.json`?  I would assume we would follow the same approach we took with `System.Globalization.Invariant`.  We added both a `runtimeconfig.json` setting (https://github.com/dotnet/coreclr/pull/10264) and an environment variable (https://github.com/dotnet/coreclr/pull/15024).

**Comment by karelz** [comment]
> @stephentoub Why?

To enable shipping tools/apps to customers which opt-in into ManagedHandler (incl. the libraries/SDKs they use). Asking customers of such tool to run the tool with environment variable set is not great user experience.

@eerhardt yeah, I didn't double check the config file name - whichever is the app-specific config file name.
We are taking same approach as Globalization (and Drawing), except we don't run as early as Globalization and therefore we can use the AppContext class (guidance from Tarek BTW). Our lives are a bit easier here ...

**Comment by wfurt** [comment]
I used AppName.runtimeconfig.json for my testing. My understanding is that there are different ways how to set the values, but the actual API call in HTTP handler would not care.

**Comment by wfurt** [comment]
To enable managed handler one can use AppName.runtimeconfig.json 


```JSON
{
   "runtimeOptions": {
     "configProperties": {
        "System.Net.Http.UseManagedHttpClientHandler": true
     }
  }
}
```

**Comment by stephentoub** [comment]
> To enable shipping tools/apps to customers which opt-in into ManagedHandler (incl. the libraries/SDKs they use). Asking customers of such tool to run the tool with environment variable set is not great user experience.

Ok, thanks. It's helpful to understand why something is being stated as required.
