### ISSUE TITLE
LINQ/PLINQ `Sum(int)` does not loft to long for intermediate calculation.

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#2316]
Currently, even if the total value of elements in a collection falls within the range of the type, LINQ/PLINQ will throw errors if the _running_ total would overflow.  That is:

```
new[] { int.MaxValue, int.MaxValue, int.MinValue }.Sum()
```

... currently throws an overflow exception because of the first two items, even though the total is within range (`int.MaxValue - 1`).

It may be beneficial to loft to long for the intermediate cancellation, similar to how float lofts to double (although that particular one is more about an accurate result, not exactly overflow).

**Comment by Clockwork-Muse** [comment]
And a demonstration [for PLINQ](https://github.com/Clockwork-Muse/corefx/tree/2316_SumLoft)

**Comment by karelz** [comment]
This does not look like a good idea. There is simple workaround: use `long` as type if you want to get `long` output. It is in line how `10 + 20` code works -- neither here the compiler promotes it to long on your behalf without explicit cast.
