### ISSUE TITLE
Master should remap `netfx` to `net471`

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#23165]
Related #23116

We should also disable the majority of the `netfx` configurations for things inside netstandard as well as the support package since we aren't shipping them anymore.  New versions of the 4.6.1 support package will come from servicing and every library in `netstandard2.0` is now part of `net4.7.1`.

/cc @weshaggard @AlexGhiondea

**Comment by ericstj** [comment]
I've started to prepare this work from the source changes side of things.

I think we also need a 4.7.1 targeting pack and we need to install 4.7.1 on out CI machines so that when we test for netfx (net471) we get the correct behavior.  / cc @AlexGhiondea

**Comment by weshaggard** [comment]
@ericstj Is this something we need for .NET Core 2.1?

**Comment by ericstj** [comment]
No, it’s more like moving corefx forward to “latest” for desktop testing

**Comment by ViktorHofer** [comment]
Closing as we are running net472 now in master.
