### ISSUE TITLE
System.Threading.Tasks tests hanging

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23201]
In the last few weeks, CI runs have been timing out sporadically due to the System.Threading.Tasks test project hanging.  It looks like it's due to the RunStackGuardTests test; this test is not new nor has it been changed recently.

**Comment by danmosemsft** [comment]
@kouvel do you have cycles to take a look?

**Comment by kouvel** [comment]
Ya I'll take a look

**Comment by stephentoub** [comment]
FYI, when I run just that test locally in a loop, it hangs for me maybe 1/3 of the time.
