### ISSUE TITLE
(api review) IL Object Model

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/corefx#2320]
@terrajobst

From the recent [API Review 2015-07-08](https://github.com/dotnet/apireviews/tree/master/2015-07-08-ildasm-and-drawing)
**IL Object Model**

**Observations**
- Implement a custom object model.
- use [Mono's Cecil](https://github.com/jbevain/cecil) implementation.

**Parsing**
- From the byte stream
- From the text representation.

**Output**
- Byte stream
- Text Representation
  The issue here I see is that some instructions have "pointers" to data embedded into the assembly bytes. A very common one is `Strings`. So you're going to need an object to represent that so that construction of the output bytes is correct.

**IL Labels**
These point to data objects that encoded into the assembly. 
- Strings being a common one.
- `switch` uses them as jump targets.

A benefit of an IL object model, is that you could get an IL representation of a method, without doing a full compilation. 

**Targeting**

For example 

Roslyn should "compile" to an IL Object model, first. which then permit for further diagnostic analysers (or an optional layer). On the produced IL
For example:- A analyser to help minimise Boxing operations. you'll should be able to trickle that information back to source-code level.

**Compilation**
The last stage would "Compilation Targets" for various architectures eg. x86, x64,ARM and maybe even Typescript. This could be supplied as NuGet package.  

---

Side Note I implemented a partial implementation of an object model for IL [here](https://github.com/AdamSpeight2008/IL.Sarc)

**Comment by leppie** [comment]
As long as PE verification is included, I am all game ;p

**Comment by mattwarren** [comment]
> For example:- A analyser to help minimise **Boxing operations**. you'll should be able to trickle that information back to source-code level.

This would be nice, I was able to write an Analyser to do this, but because I had to get Roslyn to do a full compile/emit every time, it was slow (plus I had to make use of [Cecil](http://www.mono-project.com/docs/tools+libraries/libraries/Mono.Cecil/) to parse the IL). Being able to get Roslyn to compile code directly into an IL Object would be nice.

FYI if you interested my project is here https://github.com/mattwarren/RoslynHeapAllocations

**Comment by karelz** [comment]
We do not believe that such a large API surface must be part of CoreFX. It is perfectly fine to have independent library sitting on top of it.
Closing. Feel free to reopen if you disagree.

cc: @terrajobst for checking our conclusion
