### ISSUE TITLE
System.Drawing.Printing.PrinterSettings PrintRange() and Duplex() Throws wrong exception when parameter is invalid. 

### ISSUE THREAD

**Issue by KostaVlev** [dotnet/corefx#23217]
The tests passes on **netfx** but fails on **core**. 

The failing tests are:
```c#
[Theory]
[InlineData(PrintRange.AllPages - 1)]
[InlineData(PrintRange.SomePages + 1)]
[InlineData((PrintRange)int.MaxValue)]
[InlineData((PrintRange)int.MinValue)]
public void PrintRange_Invalid_ThrowsInvalidEnumArgumentException(PrintRange printRange)
{
     var printerSettings = new PrinterSettings();
     AssertExtensions.Throws<InvalidEnumArgumentException>("value", () => printerSettings.PrintRange = printRange);
}

[ActiveIssue(20884, TestPlatforms.AnyUnix)]
[ConditionalTheory(Helpers.GdiplusIsAvailable)]
[InlineData(Duplex.Default - 1)]
[InlineData(Duplex.Horizontal + 1)]
[InlineData((Duplex)int.MaxValue)]
[InlineData((Duplex)int.MinValue)]
public void Duplex_Invalid_ThrowsInvalidEnumArgumentException(Duplex duplex)
{
    var printerSettings = new PrinterSettings();
    AssertExtensions.Throws<InvalidEnumArgumentException>("value", () => printerSettings.Duplex = duplex);
}
```

Running the tests on `netcoreapp` I am getting:

```c#
Assert.Throws() Failure
\r\nExpected: typeof(System.ComponentModel.InvalidEnumArgumentException)
\r\nActual:   typeof(System.ComponentModel.InvalidEnumArgumentException): The value of argument 'value' (-1) is invalid for Enum type 'PrintRange'.
```

To test the exception I wrote:

```c#
var printerSettings = new PrinterSettings();
try
{                
    printerSettings.PrintRange = printRange;
}
catch (Exception e)
{
    Assert.Equal(typeof(InvalidEnumArgumentException), e.GetType());
}
```
The Assert fails with:

```
Assert.Equal() Failure
        Expected: typeof(System.ComponentModel.InvalidEnumArgumentException)
        Actual:   typeof(System.ComponentModel.InvalidEnumArgumentException)
```

The tested method:

```c#
public PrintRange PrintRange
{
    get { return _printRange; }
    set
    {
         if (!Enum.IsDefined(typeof(PrintRange), value))
         throw new InvalidEnumArgumentException("value", unchecked((int)value), typeof(PrintRange));

        _printRange = value;
    }
}
```

(#23161) (#20711)

 **Edited**

**Comment by KostaVlev** [comment]
Actually the reason Assertion is failing is very obvious. I just didn't see it until now... :(

The expected Exception is [`System.ComponentModel.Primitives.InvalidEnumArgumentException`](https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Primitives/src/System/ComponentModel/InvalidEnumArgumentException.cs) and actual is [`System.ComponentModel.InvalidEnumArgumentException`](https://github.com/dotnet/corefx/blob/master/src/System.Drawing.Common/src/misc/InvalidEnumArgumentException.cs) which is also `internal`.

I will update the tests to use `Assert.ThrowsAny<>` :

`Assert.ThrowsAny<ArgumentException>(() => printerSettings.Duplex = duplex);`
`Assert.ThrowsAny<ArgumentException>(() => printerSettings.PrintRange = printRange);`

**Comment by mellinoe** [comment]
Sorry -- I've been on vacation. When the library was retargeted to .NET Core 2.0 (as opposed to 2.1), I had to create a local copy of InvalidEnumArgumentException inside System.Drawing.Common, because it isn't exposed from ComponentModel in 2.0. This is why the types don't match. Using `ThrowAny` is the correct approach.
