### ISSUE TITLE
SqlClient v4.4.0 on .NET core 2.0 throws FileLoadException when property's set

### ISSUE THREAD

**Issue by FransBouma** [dotnet/corefx#23211]
(Using vs 2017, 15.3 preview 17.1, dotnet --version: 2.0.0-preview2-006497)

This code: 

```cs
using System;
using System.Data.SqlClient;

namespace ConsoleApp3
{
    class Program
    {
        static void Main(string[] args)
        {
	        var con = new SqlConnection();
	        con.ConnectionString = "data source=<some server>;initial catalog=master;integrated security=SSPI;persist security info=False;packet size=4096";
	        con.Open();
	        con.Close();
	}
    }
}
```

using project file:

``` xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.4.0" />
  </ItemGroup>

</Project>
```
throws:
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.SqlConnection' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Data.SqlClient.SqlConnection..cctor()
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at ConsoleApp3.Program.Main(String[] args) in c:\users\frans\documents\visual studio 2017\Projects\ConsoleApp3\ConsoleApp3\Program.cs:line 11
   Press any key to continue . . .
```
Looking into the v4.4.0 SqlClient package, it appears to contain SqlClient v4.2 dll. Not sure whether that's OK or not, but at least it's impossible to do anything with it on .net core 2.0

**Comment by FransBouma** [comment]
cc @karelz @divega @saurabh500

**Comment by FransBouma** [comment]
Updating the CLI tools to 2.0.1 from dotnet/cli fixes it. 

This is very problematic. Installing visual studio 2017 15.3 latest preview should install latest CLI tools, at least if these are used by visual studio. Please fix this mess, it's causing a lot of grief and problems and time wasted. It shouldn't be the case that installing the latest preview of vs 2017 still keeps the dotnet CLI tools on an old outdated verson.

**Comment by divega** [comment]
cc @corivera in case Saurabh isn’t available.

**Comment by FransBouma** [comment]
Ok. In any case it is resolved when the RTM tools / netcore2.0 sdk are installed. IMHO vs 2017 15.3 RTM should install this, no extra net sdk should be required. :)

**Comment by danmosemsft** [comment]
@FransBouma we hear your feedback. This was intentional to allow VS and the .NET Core SDK to version and install independently but clearly it makes this situation possible for those that install previews.
I'm going to close this as my undrestanding is as you say it's resolved.
