### ISSUE TITLE
ReadOnlyCollection<T> interfaces.

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/corefx#2321]
From MSDN:

```
public class ReadOnlyCollection<T> : IList<T>,
    ICollection<T>, IEnumerable<T>, IEnumerable, IList, ICollection,
    IReadOnlyList<T>, IReadOnlyCollection<T>
```

Suggested fix:

```
public class ReadOnlyCollection<T> : IEnumerable<T>, IEnumerable, IReadOnlyList<T>, IReadOnlyCollection<T>, ICollection
```

**Comment by stephentoub** [comment]
Can you elaborate on the problem the suggested fix solves?

**Comment by JohanLarsson** [comment]
It would eliminate the need for [throw on set](http://referencesource.microsoft.com/#mscorlib/system/collections/objectmodel/readonlycollection.cs,198)

I understand that it is ~impossible to fix this for backwards compatibility reasons but thinking about that it will look like this ten years from now makes me sad :)

**Comment by karelz** [comment]
This would be a breaking change. We can't take it.
