### ISSUE TITLE
Ensure build of netcoreapp vertical of CoreFx can be done without past packages

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#23220]
Some recent changes cause us to require past shipped packages, see https://github.com/dotnet/corefx/pull/23168#discussion_r132996424.

We should eliminate those.  The only packages pulled down for netcoreapp vertical build should be buildtools (and its related closure), netstandard, desktop targeting packs, and the runtime.

/cc @weshaggard @mellinoe

**Comment by weshaggard** [comment]
@safern wasn't this work done with the compat package work?

**Comment by safern** [comment]
I added netcoreapp to all the projects assemblies included in the compat pack. I don't think that is what we needed to fix this issue right?

**Comment by weshaggard** [comment]
That is the key thing needed to fix this. I guess we just need to survey to see if there are any other libraries that weren't in the compat pack that also need a netcoreapp configuration.

**Comment by safern** [comment]
Yes, I'll do that check and update them if needed and then close this issue. Thanks.

**Comment by weshaggard** [comment]
I think the easiest way to verify this is to disable the restoring of the netcoreapp2.0 targeting pack under external and do a full netcoreapp vertical build. It should succeed and if it doesn't then you will find the ones that need a configuration.

**Comment by safern** [comment]
Good idea. Will do that.
