### ISSUE TITLE
FW link on release notes is broken in DiagnosticsSource

### ISSUE THREAD

**Issue by SergeyKanzhelev** [dotnet/corefx#23221]
https://preview.nuget.org/packages/System.Diagnostics.DiagnosticSource/

Release notes link https://go.microsoft.com/fwlink/?LinkID=799421 leads to 1.1 release notes https://github.com/dotnet/core/blob/master/release-notes/1.1/1.1.0-preview1.md

**Comment by danmosemsft** [comment]
@leecow this comes from corefx\packaging.props
`    <ReleaseNotes>https://go.microsoft.com/fwlink/?LinkID=799421</ReleaseNotes>`

We didn't update the link for 2.0. We can either update the link for 2.0 or change it to point at the 2.0 relnotes (affecting 1.1 packages also). 

I suggest you supply another fwlink and we can update this file in 2.0 servicing.

**Comment by danmosemsft** [comment]
@richlander you have an fwlink for the 2.0 release notes? (ie to https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0.0.md)

**Comment by karelz** [comment]
Seems to be addressed now, the FW link points to https://github.com/dotnet/core/tree/master/release-notes
