### ISSUE TITLE
System.Security.Cryptography.Cng package needs Xamarin support

### ISSUE THREAD

**Issue by marek-safar** [dotnet/corefx#23233]
Xamarin SDKs have custom System.Security.Cryptography.Cng facade because the underlying types exist in system assemblies but System.Security.Cryptography.Cng package is missing `_._` redirects to allow this facade to be used

**Comment by karelz** [comment]
@weshaggard can you please help here?
@marek-safar how urgent is it?

**Comment by weshaggard** [comment]
@ericstj I assume this is just another case where we want to add the Xamarin supports to the package?

**Comment by marek-safar** [comment]
It's not urgent as System.Security.Cryptography.Cng package is not broadly used. We found the issue internally during our netstandard 2.0 testing.

**Comment by bartonjs** [comment]
@ericstj I forget if I asked you if you were working on this.  And then I double-forget if you said yes.
