### ISSUE TITLE
System.Net.Mail broke when upgrading to .NET Core 2

### ISSUE THREAD

**Issue by CharlBest** [dotnet/corefx#23246]
![image](https://user-images.githubusercontent.com/6147400/29315640-7e163ac0-81c4-11e7-8fc3-b87571581105.png)

Updating to .net core 2 broke System.Net.Mail reference.

**Comment by danmosemsft** [comment]
@weshaggard can you help shed light? I'm not really able to diagnose this kind of errors.

**Comment by weshaggard** [comment]
With .NET Core 2.0 we shipped System.NET.Mail as part of it so you should be able to remove your package reference to System.Net.Mail and it should work.

**Comment by CharlBest** [comment]
The addition of the System.Net.Mail nuget package was just an example of the package not working or conflicting core 2. But here is my real setup: 
![image](https://user-images.githubusercontent.com/6147400/29399052-e967be48-8327-11e7-9603-43e028c5f825.png)
I am referencing a package called SendGrid.NetCore to send emails with. Are you sure if they remove the System.Net.Mail reference that it will just start working? @thinkingserious from SendGrid can maybe help with this problem.

**Comment by CharlBest** [comment]
Thanks @weshaggard for your help. We figured it out. I was referencing an old/pre-released package. Stupid me.
