### ISSUE TITLE
HttpWebRequest.Host throw WebException

### ISSUE THREAD

**Issue by zokiad** [dotnet/corefx#23244]
Hi,

I use .net core 2.0 with VS 15.3.
This example work fine on Framework .net 6.4.2.

This request work fine:

```C#
string host = "www.google.fr";
string url = "https://" + host;

try
{
    System.Net.HttpWebRequest request = System.Net.HttpWebRequest.CreateHttp(url);
    request.UserAgent = "Mozilla/5.0 (compatible;)";
    request.Timeout = 10000;
    //request.Host = uri.Host;

    HttpWebResponse response = request.GetResponse() as HttpWebResponse;
}
catch(Exception ex)
{
    Console.WriteLine(ex.ToString());
}
```

But when a try to use Host with IP address. I obtains with exception:

```C#
string host = "www.google.fr";
string url = "https://" + host;

try
{
    Ping ping = new Ping();
    PingReply reply = ping.Send(host);
                
    System.Net.HttpWebRequest request = System.Net.HttpWebRequest.CreateHttp("https://" + reply.Address.ToString());
    request.UserAgent = "Mozilla/5.0 (compatible;)";
    request.Timeout = 10000;
    request.Host = host;

    HttpWebResponse response = request.GetResponse() as HttpWebResponse;
}
catch (Exception ex)
{
    Console.WriteLine(ex.ToString());
}
```

**Exception:**

> System.Net.WebException: An error occurred while sending the request. A security error occurred ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A security error occurred
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
>    at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
>    --- End of inner exception stack trace ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at System.Net.HttpWebRequest.<SendRequest>d__194.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at System.Net.HttpWebRequest.GetResponse()
>    --- End of inner exception stack trace ---
>    at System.Net.HttpWebRequest.GetResponse()
>    at HttpWebRequest.Program.Main(String[] args) in..Program.cs:line 38

**Comment by davidsh** [comment]
This is by-design.

You are sending an HTTPS request to a server using the ip address as the DNS name.  But that "name" doesn't match the server's TLS/SSL certificate.  That is why you are getting an error:

>System.Net.Http.WinHttpException: A security error occurred

If you really want to talk with a server and disregard TLS/SSL certificate errors (such as name mismatch in this case), then please take a look at using this API for HttpWebRequest.

https://github.com/dotnet/corefx/blob/master/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs#L734

**Comment by davidsh** [comment]
You can see from the certificate from that server that it only allows certain name matches:
![image](https://user-images.githubusercontent.com/7684835/29320324-a4ebb898-818b-11e7-936f-739a8de85891.png)

**Comment by zokiad** [comment]
OK thanks.
To accept SSL:
request.ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) => true;

**Comment by chick-fil-a-21** [comment]
After upgrading to 2.0, getting same error

request url(get_json): https://e1171.name1.name2.name3.com/oauth2/.wel
l-known/openid-configuration
An error occurred while sending the request. A security error occurred

**Comment by davidsh** [comment]
This issue is closed and was specific to using IP addresses.

Please open up a new issue for your report.  Closed issues are not typically monitored.

cc: @karelz
