### ISSUE TITLE
[System.Security.Cryptography.Hashalgorithm]::Create($Hashname) gives error in PowerShell 6.0 beta

### ISSUE THREAD

**Issue by peterquirk** [dotnet/corefx#23245]
## Steps to reproduce ##
Fetch Get-StringHash from PowerShell Gallery at https://gallery.technet.microsoft.com/scriptcenter/Get-StringHash-aa843f71

Execute Get-StringHash ("admin", "MD5") 

## Expected behavior ##
get-stringhash "admin" "MD5"
21232f297a57a5a743894a0e4a801fc3

This is what I get with PowerShell 5.1.16257.1. CLRVersion 4.0.30319.42000
## Actual behavior ##
Exception calling "Create" with "1" argument(s): "Operation is not supported on this
platform."
At line:5 char:1
+ [System.Security.Cryptography.HashAlgorithm]::Create($HashName).Compu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : PlatformNotSupportedException
## Environment data ##
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.5
OS                             Microsoft Windows 10.0.16257
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by krwq** [comment]
This is a duplicate of https://github.com/dotnet/corefx/issues/22626 - This scenario is currently not supported. As a workaround you can use:
```
[System.Security.Cryptography.CryptoConfig]::CreateFromName($String)
```
