### ISSUE TITLE
https://apisof.net/ is having certificate error

### ISSUE THREAD

**Issue by smitpatel** [dotnet/corefx#23255]
```
This site is not secure

This might mean that someone's trying to fool you or steal any info you send to the server. You should close this site immediately

The website's security certificate is not yet valid or has expired.                                    
Error Code: DLG_FLAGS_SEC_CERT_DATE_INVALID
```

Browser: Edge

**Comment by karelz** [comment]
Closing as it does not belong to CoreFX. AFAIK @terrajobst was talking for quite some time about some solution.

**Comment by smitpatel** [comment]
@karelz - Which should be correct place to report this? (or perhaps get fixed)

**Comment by karelz** [comment]
I don't think there is any "right place" on GitHub or anywhere :(.
Last time I checked, the web page was front-end for APIReview tool. And it was not properly funded by any team :(, basically just a hobby project.

**Comment by og-carefree** [comment]
contact@dotnetfoundation.org

That might be your best bet... Attempting to log in to the apisof.net site gives a github auth dialog which shows dotnet is the owner of the application.

![image](https://user-images.githubusercontent.com/29863520/29617447-d0f89d8e-880c-11e7-9b1a-a0399aa25bbd.png)

**Comment by svick** [comment]
The correct place to report this is [terrajobst/apisof.net](https://github.com/terrajobst/apisof.net) and it has already been reported there: https://github.com/terrajobst/apisof.net/issues/3.
