### ISSUE TITLE
GetTypeFromProgID not working on NetStandard 2.0

### ISSUE THREAD

**Issue by jmroyb** [dotnet/corefx#23260]
Hi folks, 

This piece of code works fine in 4.61 and later:

`
        public sealed class ComLoader
        {
            private string m_fullName;
            private Type m_t;
            private Object m_o;

            public ComLoader(string fullName)
            {
                m_fullName = fullName;
            }

            public void InvokeMethod(string name, object[] parameters, out string result)
            {
                m_t = Type.GetTypeFromProgID(m_fullName);

                if (m_t == null)
                    throw new Exception("'" + name + "' not found");

                m_o = Activator.CreateInstance(m_t);
                var r = m_t.InvokeMember
                    (
                        name,
                        System.Reflection.BindingFlags.InvokeMethod, null, m_o,
                        parameters
                    );

                if (r == null)
                    result = null;
                else
                    result = r.ToString();
            }
        }
`

I call it from console app (4.6.1 and later):

`
            var x = new ComLoader("VBAInterop.myClass");
            x.InvokeMethod("myMethod", null, out string r);
`

When class ComLoader is within netstandard2.0 class library, code raises this exception:

Retrieving the COM class factory for component with CLSID {9910CCF8-F352-4823-AF20-EE524E614D82} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)) at m_o = Activator.CreateInstance(m_t);

When class ComLoader is within net 4.6.1 and later class library, code works fine. 

Please can you help me?

**Comment by danmosemsft** [comment]
@yizhang82 can someone on your team look?

**Comment by danmosemsft** [comment]
@tijoytom

**Comment by yizhang82** [comment]
@jmroyb Can you double check whether your COM server is registered as 64-bit? .NET Core by default runs apps in 64-bit.

**Comment by jmroyb** [comment]
@yizhang82, I registered com library using C:\Windows\SysWow64\regsvr32.exe. Using it from Syswow64 works. Using C:\windows\system32\regsvr32.exe does not work in net 4.6.1 and later.

**Comment by yizhang82** [comment]
I believe you have your 4.6.1 app built as x86, that's why it works when you register it using 32-bit SysWow64\regsvr32.exe. You can confirm that by running corflags.exe. 
32-bit app can only load 32-bit COM registered using 32-bit regsvr32 in 32-bit of the registry, and 64-bit app can only load the 64-bit COM registered using 64-bit regsvr32.exe in 64-bit part of the registry.

**Comment by jmroyb** [comment]
Solved. It was my fault about registering com library

**Comment by carlosneto** [comment]
> Solved. It was my fault about registering com library

I have the same problem... what you do to solve your problem ?

**Comment by jmroyb** [comment]
Remember to register COM library with regsvr32. Trye one of this:

 Directory of C:\Windows\System32

15/09/2018  07:29            24.064 regsvr32.exe
               1 File(s)         24.064 bytes

 Directory of C:\Windows\SysWOW64

15/09/2018  07:29            20.992 regsvr32.exe
               1 File(s)         20.992 bytes

**Comment by carlosneto** [comment]
Thanks @jmroyb, I tried to register the dll with both but the problem persists!
The same code compiled with .Net Framework 4.x works! With .NET Core 2.0 I got the error: "Retrieving the COM class factory for component with CLSID {BD816878-EE72-49C2-BCB0-132A7D5CE5B1} failed error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG ))."

**Comment by jmroyb** [comment]
I suggest to report it to team...
