### ISSUE TITLE
Global invariant mode - Turkish I problem

### ISSUE THREAD

**Issue by CoskunSunali** [dotnet/corefx#23270]
Nevermind, please delete this issue if possible.

**Comment by danmosemsft** [comment]
@CoskunSunali that only applies when you opt your app into globalization invariant mode - which is something like locking it into en-US to make it as lightweight as possible.

If you develop apps that need to be more culture aware, you would not opt into this mode.

does that help?

**Comment by CoskunSunali** [comment]
@danmosemsft That definitely helps. I figured that out once I create the issue - in a rush :)

That is the reason I updated the issue asking for a deletion. Sorry, would not remove the original text if I had known you would have replied sooooo fast!

Do you know if I can somehow get the original issue text back?

**Comment by danmosemsft** [comment]
here you are
```
I have been reading documentation at https://github.com/dotnet/corefx/blob/master/Documentation/architecture/globalization-invariant-mode.md
The doc states the following:
Turkish I casing will not be supported when using Turkish cultures.
I wonder why? That would be a bottleneck for us, developers developing apps in Turkish culture.
Is there a suggested workaround or something?
Thanks in advance.

```
we can't delete issues, only replies

**Comment by CoskunSunali** [comment]
@danmosemsft Thank you! I just updated the original issue for future references.

Sorry for the inconvenience and thanks for your replies!

**Comment by danmosemsft** [comment]
No inconvenience at all .. it's my job, and I'm glad you're trying out our work. Please do keep feedback coming.
