### ISSUE TITLE
Test failed: System.Net.Security.Tests.SslStreamCredentialCacheTest / SslStream_SameCertUsedForClientAndServer_Ok

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23291]
## Types of failures

```
System.TimeoutException : Task timed out after 15000
at System.Threading.Tasks.TaskTimeoutExtensions.<TimeoutAfter>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Net.Security.Tests.SslStreamCredentialCacheTest.<SslStream_SameCertUsedForClientAndServer_Ok>d__0.MoveNext() in E:\A\_work\1384\s\corefx\src\System.Net.Security\tests\FunctionalTests\SslStreamCredentialCacheTest.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
```

## History of failures

History since 2017/6, when another unrelated problem was addressed in the test.

Day | Build | OS | Details
--- | --- | --- | ---
11/28 | 20171128.03 | Win7 |
12/18 | CI: 55314276e4392f81422c627c94b074f4da492ca7 | Unknown
12/30 | 20171230.02 | Win7 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171230.02/workItem/System.Net.Security.Tests/analysis/xunit/System.Net.Security.Tests.SslStreamCredentialCacheTest~2FSslStream_SameCertUsedForClientAndServer_Ok)
1/3 | CI: ef02f28820e7b930dec93f66d5e7f349be3a80c3 | Win7 | 
1/27 | 20180127.01 | Win7 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180127.01/workItem/System.Net.Security.Tests/analysis/xunit/System.Net.Security.Tests.SslStreamCredentialCacheTest~2FSslStream_SameCertUsedForClientAndServer_Ok)
3/16 | 20180316.01 | Win7
3/16 | 20180316.03 | Win7
3/23 | 20180323.03 | Win10

# Original report

It timed out, but this test doesn't even use networking.
https://github.com/dotnet/corefx/pull/23188
```
System.Net.Security.Tests.SslStreamCredentialCacheTest.SslStream_SameCertUsedForClientAndServer_Ok [FAIL]
        System.TimeoutException : The operation has timed out.
        Stack Trace:
           D:\j\workspace\windows_nt_re---e95ab8b5\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs(23,0): at System.Threading.Tasks.TaskTimeoutExtensions.<TimeoutAfter>d__0.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           D:\j\workspace\windows_nt_re---e95ab8b5\src\System.Net.Security\tests\FunctionalTests\SslStreamCredentialCacheTest.cs(49,0): at System.Net.Security.Tests.SslStreamCredentialCacheTest.<SslSessionsCacheTest>d__1.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           D:\j\workspace\windows_nt_re---e95ab8b5\src\System.Net.Security\tests\FunctionalTests\SslStreamCredentialCacheTest.cs(23,0): at System.Net.Security.Tests.SslStreamCredentialCacheTest.SslStream_SameCertUsedForClientAndServer_Ok()
```
This was on 1.1, though, so maybe something has been fixed since then?

**Comment by karelz** [comment]
Only 1 failure in official Helix runs on 11/28 since 2017/6 (when another unrelated problem was addressed in the test):

Build: 20171128.03 - Win7
```
System.TimeoutException : Task timed out after 15000
at System.Threading.Tasks.TaskTimeoutExtensions.<TimeoutAfter>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Net.Security.Tests.SslStreamCredentialCacheTest.<SslStream_SameCertUsedForClientAndServer_Ok>d__0.MoveNext() in E:\A\_work\1384\s\corefx\src\System.Net.Security\tests\FunctionalTests\SslStreamCredentialCacheTest.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
```

Moving to Future for now as rare test failure.

**Comment by ahsonkhan** [comment]
Failed again here: https://github.com/dotnet/corefx/pull/28389
https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/8ed94f0eae5b9dcee1b8bc23b9adaae381c0c69a/workItem/System.Net.Security.Tests/analysis/xunit/System.Net.Security.Tests.SslStreamCredentialCacheTest~2FSslStream_SameCertUsedForClientAndServer_Ok

**Comment by davidsh** [comment]
This test has been running successfully now since 4/23.
![image](https://user-images.githubusercontent.com/7684835/40387062-587ce7e0-5dc0-11e8-9f83-2d42e53bf427.png)

**Comment by ahsonkhan** [comment]
Failing in coreclr: https://github.com/dotnet/coreclr/pull/21216

https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_release_windows_nt_corefx_innerloop_prtest/4125/testReport/junit/System.Net.Security.Tests/SslStreamCredentialCacheTest/SslStream_SameCertUsedForClientAndServer_Ok/

System.Net.Security.Tests.SslStreamCredentialCacheTest.SslStream_SameCertUsedForClientAndServer_Ok (from (empty))


```text
Stacktrace
MESSAGE:
System.TimeoutException : Task timed out after 15000ms
+++++++++++++++++++
STACK TRACE:
at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, Int32 millisecondsTimeout) in D:\j\workspace\windows-TGrou---74aa877a\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 26 at System.Net.Security.Tests.SslStreamCredentialCacheTest.SslStream_SameCertUsedForClientAndServer_Ok() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Security\tests\FunctionalTests\SslStreamCredentialCacheTest.cs:line 42 --- End of stack trace from previous location where exception was thrown ---
```
