### ISSUE TITLE
Installation is not compatible with Windows 7

### ISSUE THREAD

**Issue by chengjinshengtaichanyejituan** [dotnet/corefx#23305]

**Comment by adityamandaleeka** [comment]
@chengjinshengtaichanyejituan I've translated the title for others' convenience. Please let us know if that's a mistranslation. 

Can you also please share more details about what you're trying to do?

**Comment by chengjinshengtaichanyejituan** [comment]
也没有，知识有点 不懂

**Comment by lextm** [comment]
@chengjinshengtaichanyejituan if you don't know English at all, please post to MSDN Chinese forums, https://social.msdn.microsoft.com/forums/zh-cn/home where you can use 中文 to get what you want.

**Comment by danmosemsft** [comment]
@yizhang82 can you help figure out what product this concerns?

**Comment by yizhang82** [comment]
@chengjinshengtaichanyejituan 请问你安装遇到问题是什么？能够把相关的错误信息发一下吗？是.NET Core SDK的安装出问题？

**Comment by karelz** [comment]
Closing as we do not have actionable info.
