### ISSUE TITLE
Why do you check the first argument of Extension Method for null to throw Argument(Null)Exception???

### ISSUE THREAD

**Issue by xperiandri** [dotnet/corefx#2331]
Why do you ever check the first argument of Extension Method for null?
For example
``` C#
namespace System.Linq
{
    public static class Enumerable
    {
        public static IEnumerable<TSource> Where<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate)
        {
            if (source == null) throw Error.ArgumentNull("source"); // <<<<< Stupid! Unnecessary!
            if (predicate == null) throw Error.ArgumentNull("predicate");
            if (source is Iterator<TSource>) return ((Iterator<TSource>)source).Where(predicate);
            if (source is TSource[]) return new WhereArrayIterator<TSource>((TSource[])source, predicate);
            if (source is List<TSource>) return new WhereListIterator<TSource>((List<TSource>)source, predicate);
            return new WhereEnumerableIterator<TSource>(source, predicate);
        }
```

It is stupid!
If you we assume that Extension Method must look like a regular method than it must not ever check for null. Because if you call a method on null instance you got NullReferenceException but not ArgumentNullException.
So there is no reason to check for null because if first argument will be null NullReferenceException occur anyway

**Comment by hackcraft** [comment]
For one thing, there's no way for the code to know whether it was called as `someEnumrable.Where(x => x.SomeFlag)` or `Enumrable.Where(someEnumerable, x => x.SomeFlag)`.

The latter use should definitely throw `ArgumentNullException`.

**Comment by xperiandri** [comment]
So what? No one does that!

**Comment by JohanLarsson** [comment]
(IEnumerable<int>null).Max() is a valid call.

**Comment by xperiandri** [comment]
@JohanLarsson could you explain?

**Comment by hackcraft** [comment]
People certainly do call extension methods as static methods. It can be particularly sensible from within neighbouring extension methods, or even more sensible if using a language that doesn’t support calling extension methods with instance method syntax, which .Net languages are not required to support.

While the syntactic sugar makes calls look like instance calls, they still at root aren't instance calls.

**Comment by JohanLarsson** [comment]
@xperiandri [sample](https://dotnetfiddle.net/IE6V9J)

**Comment by xperiandri** [comment]
@JohanLarsson, OK, I corrected title so my question is more specific

**Comment by xperiandri** [comment]
@hackcraft, I understand this point. However it is an abstract statement.
So that is worse: to do a unnecessary checks 90% of time or to get NullReferenceException instead of ArgumentNullException?

**Comment by hackcraft** [comment]
For samples, there's running code in this repository that does calls extension methods this way. 

Incidentally. Assuming an extension method `SomeStatic.SomeMethod` exists, and `val` is a value of a type that matches the type of the first parameter after overload resolution, it is not always the case that `val.SomeMethod()` and `SomeStatic.SomeMethod(val)` are the same. The former can be override by an instance method on `val` while the latter guarantees that the extension method is called. This is an edge-case for the most part, but an example that when you lick off the syntactic sugar, extension methods are still static methods with arguments, not instance methods.

**Comment by hackcraft** [comment]
> So that is worse: to do a unnecessary checks 90% of time and get ArgumentNullException instead of NullReferenceException 90% of time or to get NullReferenceException instead of ArgumentNullException occassionally?

To get `NullReferenceException` is clearly much worse. It is the incorrect exception and its being thrown from a static method that is part of a public interface is a clear bug. (I have some code out there that offers low-level copying that will throw `NullReferenceException` but I am at least apologetic about it).

The static method should either work with `null` or throw `ArgumentNullException` if it can't. Indeed, there is a further difference between extension methods and instance methods; C# and VB.NET can't call instance methods on null objects (other languages can if the method isn't virtual) but can on extension methods.
