### ISSUE TITLE
Improve ServicePointManager.DefaultConnectionLimit

### ISSUE THREAD

**Issue by GSPP** [dotnet/corefx#2332]
`ServicePointManager.DefaultConnectionLimit` appears to be `2` on .NET 4.5 in non-ASP.NET apps. This is too low for almost any production load. I don't know what this low limit is supposed to accomplish. I understand the presence of *some* limit as a safety measure but `2` is really never useful.

Many developers have trouble with that: https://www.google.com/webhp?complete=1&hl=en&gws_rd=cr,ssl&ei=#complete=1&hl=en&q=site:stackoverflow.com+%22ServicePointManager.DefaultConnectionLimit%22 When somebody asks "My HTTP requests are unexpectedly slow" the default answer is "DefaultConnectionLimit = int.MaxValue" and this solves the problem in about 80% of the cases. This is strong evidence that the default should be changed. This is an ongoing cause for trouble and surprise.

There are three choices that I can think of:

1. Unlimited. ASP.NET has chosen this (`SetAutoConfigLimits`) presumably for good reasons. I think this is the least surprising choice. When a developer says `new WebClient().Download(...)` he expects the request to be sent right away. The dev is responsible for ensuring a sane degree of concurrency. he can use `SemaphoreSlim` or the service point infrastructure for that.
2. A constant factor on the CPU count of the machine (e.g. 10). Pro: This scales up with the size of the machine. Con: It might be a low-CPU (e.g. 2) machine that does little processing but relays it's request to some backend REST service that does the heavy lifting. 100 outstanding requests per CPU would not surprise me at all in such a situation. The benefits of async IO would be throttled.
3. `1`. At least this would make developers very quickly aware that the limit exists and that they need to change it. Maybe the value of `2` follows from that reasoning. I consider this to be a weak choice that is going to be perceived as stupid (as is `2`).

Another reason for "Unlimited" is that there should not be global limits but per-service limits. A .NET process often hosts many components each of which potentially take from the global limit. They could interact in surprising (and spooky) ways.

I think the .NET Framework should pick the default value that has the least surprise and set this to `int.MaxValue`.

Also, consider revising the default value of `Expect100Continue`. I believe there is not a single developer in the world who expects each `POST` request to be performed twice by default. I do not know a single case where this was ever deemed useful. Disabling this behavior would entail, I believe, low compatibility risk. (See http://stackoverflow.com/search?q=Expect100Continue)

**Comment by hackcraft** [comment]
> I don't know what this low limit is supposed to accomplish. I understand the presence of some limit as a safety measure but 2 is really never useful.

Note that RFC 2616 states:

> Clients that use persistent connections SHOULD limit the number of
   simultaneous connections that they maintain to a given server. A
   single-user client SHOULD NOT maintain more than 2 connections with
   any server or proxy. A proxy SHOULD use up to 2*N connections to
   another server or proxy, where N is the number of simultaneously
   active users. These guidelines are intended to improve HTTP response
   times and avoid congestion

However, this is obsoleted by RFC 7230 which says instead:

> A client ought to limit the number of simultaneous open connections
   that it maintains to a given server.

>   Previous revisions of HTTP gave a specific number of connections as a
   ceiling, but this was found to be impractical for many applications.
   As a result, this specification does not mandate a particular maximum
   number of connections but, instead, encourages clients to be
   conservative when opening multiple connections.

The W3C note at [Network Performance Effects of HTTP/1.1, CSS1, and PNG](http://www.w3.org/Protocols/HTTP/Performance/Pipeline.html) would be of interest here, but is now very old, and I don't know if there is more recent work on this.

**Comment by davidsh** [comment]
ServicePointManager is a class in the .NET Desktop Framework.  It is NOT part of CoreFx and won't be.  The HTTP stack is changed in CoreFx.

**Comment by GSPP** [comment]
@davidsh You've got a point there... What's the appropriate location to raise this issue? (I really hope the answer is not MS Connect.)

**Comment by SidharthNabar** [comment]
@GSPP - You guessed it right. It's on MS Connect under .NET framework. 

Thanks,
Sid

**Comment by GSPP** [comment]
Could you please delete this issue administratively? I don't want to have the same ticket on the web multiple times. I want one canonical destination which is going to be MS Connect. I have save the text already. Thanks.

**Comment by stephentoub** [comment]
@GSPP, closing and locking.
