### ISSUE TITLE
Please Consider to Simplify the Keyword of "await"!

### ISSUE THREAD

**Issue by juepiezhongren** [dotnet/corefx#23322]
Async is now everywhere, but "await" is always not that convenient, I think 2 things are making trouble:
  现在异步无处不在，但是"await"有地方不太方便，其中两点很困扰：

- [ ] - 1.     await is a bit LONG, especially when a lot of async functions are consequently called;    
await有点长，特别是在有很多异步方法调用时就显得格外抓狂；
- [ ] - 2.     await is on the LEFT! Considerring how many javaers envy the Extending Method, which is the same troubling when you going to do chaining async function calls with so many "()".
await是放在左侧的！想想javaer们有多羡慕我们有扩展方法吧，现在用异步写链式方法调用真的不爽，各种屌括号；

My proposition is use "_" to simplify "await", and below is my showing example:
我的建议是允许使用"_"去简化"await"，下面是例子：
```
        async Task<string> NormalAsync() {
            await aAsync();
            await bAsync();
            await cAsync();
            await Task.Delay(1000);
            var str = (await (await (await 5.AAsync()).BAsync()).CAsync());
            return str;
        }

        async Task<string> SimplifiedAsync() {
            aAsync()_;
            bAsync()_;
            cAsync()_;
            Task.Delay(1000)_;
            var str = 5.AAsync()_.BAsync()_.CAsync()_;
            return str;
        }
```

**Comment by eyalsk** [comment]
@juepiezhongren You may want to post this at [csharplang](https://github.com/dotnet/csharplang) which is the official repo for the language.

**Comment by danmosemsft** [comment]
@juepiezhongren please post at csharplang as suggested.
