### ISSUE TITLE
HTTP Error 502.5 - Process Failure ASP.Net Core2 after update to Microsoft.EntityFrameworkCore -Version 2.0.0 #7462

### ISSUE THREAD

**Issue by embryologist** [dotnet/corefx#23320]
## Steps to reproduce
[ARTSQLCORE.zip](https://github.com/dotnet/corefx/files/1230002/ARTSQLCORE.zip)

```
`dotnet --info` output:
ARTNetCore> It was not possible to find any compatible framework version
ARTNetCore> 
ARTNetCore> The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
ARTNetCore> 
ARTNetCore>   - Check application dependencies and target a framework version installed at:
ARTNetCore> 
ARTNetCore>       \
ARTNetCore> 
ARTNetCore>   - Alternatively, install the framework version '2.0.0'.
ARTNetCore> 
ARTNetCore> It was not possible to find any compatible framework version
ARTNetCore> 
ARTNetCore> The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
ARTNetCore> 
ARTNetCore>   - Check application dependencies and target a framework version installed at:
ARTNetCore> 
ARTNetCore>       \
ARTNetCore> 
ARTNetCore>   - Alternatively, install the framework version '2.0.0'.
ARTNetCore> 
ARTNetCore> It was not possible to find any compatible framework version
ARTNetCore> 
ARTNetCore> The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
ARTNetCore> 
ARTNetCore>   - Check application dependencies and target a framework version installed at:
ARTNetCore> 
ARTNetCore>       \
ARTNetCore> 
ARTNetCore>   - Alternatively, install the framework version '2.0.0'.
ARTNetCore> 
ARTNetCore> It was not possible to find any compatible framework version
ARTNetCore> 
ARTNetCore> The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
ARTNetCore> 
ARTNetCore>   - Check application dependencies and target a framework version installed at:
ARTNetCore> 
ARTNetCore>       \
ARTNetCore> 
ARTNetCore>   - Alternatively, install the framework version '2.0.0'.
```
I installed `Microsoft.NETCore.App -Version 2.0.0` yet when I run the app I get this msg,

> HTTP Error 502.5 - Process Failure
> 
> 
> Common causes of this issue:
> 
> The application process failed to start
> The application process started but then stopped
> The application process started but failed to listen on the configured port
> 
> Troubleshooting steps:
> 
> Check the system event log for error messages
> Enable logging the application process' stdout messages
> Attach a debugger to the application process and inspect

**Comment by karelz** [comment]
Do you have a minimal repro? The attached project is rather large and hard to debug.

**Comment by tarekgh** [comment]
Should this get moved to https://github.com/aspnet?

**Comment by embryologist** [comment]
@karelz, how can I provide you with a minimal one?

**Comment by tarekgh** [comment]
> how can I provide you with a minimal one?

you can zip it and attach it to github here or put it on OneDrive and send a link

**Comment by karelz** [comment]
Or make it so minimal, that the code modifications to default template fit here as source code ... that would be ideal

**Comment by embryologist** [comment]
I believe its `<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />`
I think updating it ti version 2 with the current Asp.Net Core Preview creates a conflict.  downgrading solved the problem

**Comment by tarekgh** [comment]
This issue was moved to aspnet/EntityFrameworkCore#9480

**Comment by tarekgh** [comment]
I moved this issue to the right place which can be tracked there
