### ISSUE TITLE
Assembly level ConfigureAwait attribute

### ISSUE THREAD

**Issue by UnoSD** [dotnet/corefx#23330]
I would like to suggest a new assembly attribute that will set the default behaviour of `await`.

As in library code `.ConfigureAwait(false)` is widely used and missing it can lead to bugs, would be nice to disable capturing the context at assembly level.

`[assembly:ConfigureAwaitDefaultAttribute(false)]`

Alternatively, this can be implemented in Roslyn as a switch in csproj that would simply add `ConfigureAwait(false)` everywhere making the implementation easier (happy to open the issue on Roslyn if this is the preferred way).

**Comment by svick** [comment]
How exactly do you propose the attribute would work? How would it ensure that `ConfigureAwait(false)` is used?

I think this would have to be at the language level and there's already a proposal for that: https://github.com/dotnet/roslyn/issues/7673.

**Comment by UnoSD** [comment]
Only thinking out loud for now as it might be not feasible at corefx level or perform quite bad; I have seen an example using `SynchronizationContext.SetSynchronizationContext` to `null` (will try and find it later) which could be in the implementation of the `GetAwaiter` conditionally on the attribute; of course this not a real suggestion and needs thinking through.

Thank you for the link to the other proposal, and it probably does make more sense to implement it on the compiler. As the attribute would be in the corefx, I thought this could be the right place, but I am happy to close this and follow the other issue.

**Comment by stephentoub** [comment]
There's no reliable way I see that this could be implemented purely in library; it would need to be based in language support.  As such, I'm going to close this out.  Thanks for the interest.
