### ISSUE TITLE
Unable to resolve service for type 'Core.Data.CoreContext' while attempting to activate 'Core.Data.Repositories.UnitOfWork'

### ISSUE THREAD

**Issue by borisdj** [dotnet/corefx#23336]
I have part of WebAPI application that I want to move to separate project as class library.
It is common base structure that almost every app has so idea is to make it easy shareable.

What I have done in that direction is created a project named Core and moved those shared elements there, including Base Entities (e.g. User, Settings, etc), CoreContext, UnitOfWork, Generic Repository, BaseRepositories,...

In the Main project of app there are others Entities, AppContext that inherits CoreContext, more Repositories, and all Controllers, ...

I was able to build the app but when after starting it get the following error:

> InvalidOperationException: Unable to resolve service for type 'Core.Data.CoreContext' while attempting to activate 'Core.Data.Repositories.UnitOfWork'.

>Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, ISet<Type> callSiteChain, ParameterInfo[] parameters, bool throwIfCallSiteNotFound)...

Problem seems to be that `UnitOfWork` class is in Core project and in Main project is `Startup.cs` with method` ConfigureServices` that has `services.AddTransient<IUnitOfWork, UnitOfWork>();`.

Is this a bug or am I just not configuring it correctly and how could it be achieved, if possible at all.

### Further technical details
NetCore & EF Core version: 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
IDE: Visual Studio 2017 15.3
Operating system: Windows 10

**Comment by karelz** [comment]
Which CoreFX type do you have problem with? I am unable to get that from your description.
It generally helps to create a minimal repro.

**Comment by borisdj** [comment]
Application type is:
ASP.NET Core Web Application / .NET Framework - ASP.NET Core 2.0 / Web API

I will try to isolate example with the exception manifestation and add link to it.

**Comment by karelz** [comment]
If the types in question are in ASP.NET / Web API land, it would be best to file the issue under https://github.com/aspnet repos.
If the type in question lives in CoreFX repo, then this is the right place.

**Comment by borisdj** [comment]
I guess the issue is for ASP.NET Core repo - [https://github.com/aspnet/Home](https://github.com/aspnet/Home)
Closing this one and moving it there.
