### ISSUE TITLE
System.Security.Cryptography.Algorithms doesn't load on net461

### ISSUE THREAD

**Issue by onovotny** [dotnet/corefx#23344]
Here's the scenario:

.NET Core SDK 2.0
Project targeting .NET Standard 1.4

Unit test project with net461 as a target

Getting
Could not load file or assembly 'System.Security.Cryptography.Algorithms, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d5

https://ci.appveyor.com/project/onovotny/rsakeyvaultprovider/build/1.0.0-preview.1.build.20+ge84ccf841e#L104

This repros in https://github.com/onovotny/RSAKeyVaultProvider/pull/1

**Comment by christophwille** [comment]
Another similar scenario, this time for System.Security.Cryptography.Primitives

https://github.com/icsharpcode/SharpZipLib

The library targets netstandard1.3, and when (eg) used via Nuget in a net461 project, it fails loading System.Security.Cryptography.Algorithms version 4.0

**Comment by ericstj** [comment]
@onovotny something is fishy here.  Its not a conflict, it's actually missing from the output directory.

**Comment by ericstj** [comment]
Found it, appears to be an SDK bug:
```
2>    Encountered conflict between 'CopyLocal:C:\Users\ericstj\.nuget\packages\system.security.cryptography.algorithms\4.3.0\lib\net461\System.Security.Cryptography.Algorithms.dll' and 'Runtime:C:\Users\ericstj\.nuget\packages\system.security.cryptography.algorithms\4.3.0\runtimes\osx\lib\netstandard1.6\System.Security.Cryptography.Algorithms.dll'.  Choosing 'Runtime:C:\Users\ericstj\.nuget\packages\system.security.cryptography.algorithms\4.3.0\runtimes\osx\lib\netstandard1.6\System.Security.Cryptography.Algorithms.dll' because AssemblyVersion '4.2.1.0' is greater than '4.1.0.0'.
2>    Encountered conflict between 'Runtime:C:\Users\ericstj\.nuget\packages\system.security.cryptography.algorithms\4.3.0\runtimes\osx\lib\netstandard1.6\System.Security.Cryptography.Algorithms.dll' and 'Runtime:C:\Users\ericstj\.nuget\packages\system.security.cryptography.algorithms\4.3.0\runtimes\unix\lib\netstandard1.6\System.Security.Cryptography.Algorithms.dll'.  Could not determine winner due to equal file and assembly versions.
2>    Encountered conflict between 'Runtime:C:\Users\ericstj\.nuget\packages\system.security.cryptography.algorithms\4.3.0\runtimes\osx\lib\netstandard1.6\System.Security.Cryptography.Algorithms.dll' and 'Runtime:C:\Users\ericstj\.nuget\packages\system.security.cryptography.algorithms\4.3.0\runtimes\win\lib\net461\System.Security.Cryptography.Algorithms.dll'.  Choosing 'Runtime:C:\Users\ericstj\.nuget\packages\system.security.cryptography.algorithms\4.3.0\runtimes\osx\lib\netstandard1.6\System.Security.Cryptography.Algorithms.dll' because AssemblyVersion '4.2.1.0' is greater than '4.1.0.0'.
```

The SDK is incorrectly passing RID-specific assets to conflict resolution for a desktop project which doesn't even understand RIDs.  I've opened an SDK bug: https://github.com/dotnet/sdk/issues/1510

To workaround this you can specify a RID for net461 configuration.
```
    <RuntimeIdentifier Condition="'$(TargetFramework)' == 'net461'">win</RuntimeIdentifier>
```

@christophwille I'm not sure you're seeing the same problem.  I responded to the issue you opened in your repo.  If that doesn't help please open a new issue with specific repro steps and the symptoms you observe and I'll try to take a look.

**Comment by erikbra** [comment]
I seem to have the exact same problem without targeting Netstandard at all, but using SDK-style projects for pure net461 solution. So it looks like the error is not dependent on netstandard being part of the mix (I might of course be wrong, please tell me if I can provide anything to help identify the issue).

**Comment by tomcarver** [comment]
FYI I had this issue locally, and fixed it just by deleting my bin folder and trying to build again.

**Comment by ericstj** [comment]
@erikbra correct, netstandard doesn't need to be in the mix, just packages which have runtime-specific assets.  Targeting netstandard just happens to be a way that folks might bring in those packages.
