### ISSUE TITLE
RSACrpytoServiceProvider throws exception when decrypting fOAEP padded data

### ISSUE THREAD

**Issue by Spacefish** [dotnet/corefx#23340]
https://github.com/dotnet/corefx/blob/2d7ee255d3cdb1b13072176d4881e1b58453358b/src/System.Security.Cryptography.Csp/src/System/Security/Cryptography/RSACryptoServiceProvider.Windows.cs#L269

This check throws an exception if the data is fOAEP padded, even if the real data is smaller than the key!

**Comment by bartonjs** [comment]
https://tools.ietf.org/html/rfc8017#section-7.1.2

> 7.1.2.  Decryption Operation
>
>   RSAES-OAEP-DECRYPT (K, C, L)
>
>   ...
>
>   Input:
>
>      K        recipient's RSA private key (k denotes the length in
>               octets of the RSA modulus n), where k >= 2hLen + 2
>      C        ciphertext to be decrypted, an octet string of length k

Even under OAEP the decryption payload (*an octet string of length k*) should have the same number of bytes as the modulus (*k denotes the length in octets of the RSA modulus n*).

OAEP-encrypt still goes through RSA-encrypt (`m^e % n`), where m is the OAEP-padded input.

**Comment by Spacefish** [comment]
Sorry for the ticket.. it was my fault..
i used the provider without a key being loaded, as i used a XML to load the key which is not supported on .NET Core, works like a charm now!

**Comment by bartonjs** [comment]
Glad you got it worked out :smile:
