### ISSUE TITLE
Rename tests in System.Globalization

### ISSUE THREAD

**Issue by venkat-raman251** [dotnet/corefx#2336]
About 40-50% of the tests in System.Globalization do not have self descriptive names. They are currently named PosTest, NegTest etc.

**Comment by stephentoub** [comment]
@hughbe, each time we merge one of your changes, this issue gets closed, because your PR/commit messages all state that it fixes 2336.

**Comment by hughbe** [comment]
whoops sorry, i'll make sure not to say that each time
