### ISSUE TITLE
Microsoft.XmlSerializer.Generator Preview 

### ISSUE THREAD

**Issue by huanwu** [dotnet/corefx#23373]
Track the issues that need be solved by SGEN preview release

**Comment by karelz** [comment]
@huanwu what is the issue? Can you please add a short description?

**Comment by huanwu** [comment]
This is z zenhub epic to track the SGEN issues that need be solved by preview release.

**Comment by karelz** [comment]
Ah, then please mark it as Epic, ideally with [Epic] prefix in the title as well. Thanks!
