### ISSUE TITLE
Add Unicode Tests to System.Globalization

### ISSUE THREAD

**Issue by venkat-raman251** [dotnet/corefx#2337]
Write Unicode Tests that are generic and not coupled with a particular version of Unicode.
Specifically CharUnicodeInfo.GetNumericValue() and CharUnicodeInfo.GetUnicodeCategory()

**Comment by hackcraft** [comment]
Different versions add characters with new values for those methods that were previously unassigned. As such, GetNumericaValue and GetUnicodeCategory. Also, while the policy is now that Unicode versions won't change many values, that wasn't the case in 1.0 and some such did change with 2.0. There has to be a version that you are testing compliance to, though it can be a minimum value (e.g. test for compliance of the immutable properties and skip unassigned characters in say Unicode 5.0, and the test should still be true for 6.0, 7.0, 12345.0, etc.).
