### ISSUE TITLE
Do you support  System.Web.UI.WebControls？

### ISSUE THREAD

**Issue by ghd258** [dotnet/corefx#23382]
System.Web.UI
System.Web.UI.Adapters
System.Web.UI.HtmlControls
System.Web.UI.WebControls.Adapters
System.Web.UI.WebControls.WebParts
System.Web.UI.WebControls;

**Comment by danmosemsft** [comment]
@ghd258 right now, System.Web is not supported on Core.
Generally you can see what is supported where by searching here: https://apisof.net/catalog/System.Web.UI
If you'd like to ask for it to be ported, please open an issue in an aspnet repo -- perhaps https://github.com/aspnet/Home.

**Comment by karelz** [comment]
Seems to be answered.
