### ISSUE TITLE
Add ConcurrentBag<T> and ConcurrentQueue<T> Clear method

### ISSUE THREAD

**Issue by MarkusSintonen** [dotnet/corefx#2338]
Currently `ConcurrentBag<T>` does not support clearing of the bag. Currently only way to clear the bag is to call `TryTake` in a loop which is suboptimal in high concurrency applications:

``` CSharp
T dummy;
while(bag.TryTake(out dummy)) {}
```

Instead `Clear` method could be implemented so that the bag is emptied at once. Here is the proposed implementation:

``` CSharp
public void Clear()
{
    // Short path if the bag is empty
    if (_headList == null)
        return;

    bool lockTaken = false;
    try
    {
        FreezeBag(ref lockTaken);

        ThreadLocalList currentList = _headList;
        while (currentList != null)
        {
            currentList.Reset();
            currentList = currentList._nextList;
        }
    }
    finally
    {
        UnfreezeBag(lockTaken);
    }
}
```

Internal class `ThreadLocalList` needs new `Reset/Invalidate` method which sets the thread specific linked list _head and _tail to null as well as resets the counters. GC would then collect the non referenced linked list nodes.

``` CSharp
internal void Reset()
{
    _head = null;
    _tail = null;
    _count = 0;
    _stealCount = 0;
}
```

`Clear` would lock the bag for the duration of the operation since it could cause undefined behaviour  if other threads would access the bag while linked lists are being reseted. (Similarly ConcurrentDictionary<K,T> also locks the dictionary when `Clear` is called.)

**Comment by stephentoub** [comment]
Thanks, @MarkusSintonen.  Can you share some specific examples for where such a ```Clear``` method would be valuable?

**Comment by MarkusSintonen** [comment]
For example in an application where we are collecting some operation requests to a bag from multiple threads simultaneously but then user requests to cancel all pending operations. In this type of an application Clear would be beneficial. Just a quick dummy example:
````CSharp
class SomeRequestProcessor<T>
{
	private readonly ConcurrentBag<T> _requests = new ConcurrentBag<T>();
	
	public RequestProcessor()
	{
		var t = new Thread(ProcessRequests);
		t.Start();
	}
	
	public void AddRequest(T request)
	{
		_requests.Add(request);
	}
	
	public void CancelRequests()
	{
		_requests.Clear(); // Cool we can clear the bag
	}
	
	private void ProcessRequests()
	{
		while (true)
		{
			T request;
			if (_requests.TryTake(out request))
				request.doSomething();
		}
	}
}
````

**Comment by MarkusSintonen** [comment]
It has been discussed also in SO: http://stackoverflow.com/questions/5377296/how-to-remove-all-items-from-concurrentbag

**Comment by hackcraft** [comment]
I don't think resetting `_version` is correct here. It's currently a one-way transition that increments when the state changes from empty to non-empty, and doesn't decrement or otherwise change in any other case.

A `Clear` should behave as if all items had been `Remove`d. (Ideally, atomically). This means that it does not.

**Comment by MarkusSintonen** [comment]
@hackcraft, I modified the implementation so that `_version` is not reseted. I also wondered whether it would be possible to `Clear` the bag "almost atomically" (without looping through the thread locals and resetting the linked lists). In this case the `_headList` and `_tailList` references would be just null'd as well as the `_locals` disposed and reinitialized. The problem is that the `UnfreezeBag` would then fail miserably because the synchronization object (`_locals`) have changed. Also the locks would not be freed from the now unreferenced synchronization objects (thread local lists).

Even though the locks would be freed properly afterwards, there would be another risk where eg. add operation would modify a thread local list which would been just unreferenced by `Clear`. Then this add would be missed. Fixing this, if possible, would require also changing the add/removal logic.

**Comment by terrajobst** [comment]
The API itself seems fine. Most concurrent collections have a `Clear` method, except for `ConcurrentQueue<T>` and `ConcurrentBag<T>`. We should probably add it for both.

It's just a matter of implementing it correctly, considering that's it's collection that supports concurrent access.

@MarkusSintonen are you interested in picking this up?
