### ISSUE TITLE
Please consider supporting 10.11

### ISSUE THREAD

**Issue by endowdly** [dotnet/corefx#23389]
Some Mac users cannot upgrade to 10.12 due to Apple hardware requirements. 

This blocks users of Mac OS 10.11- from using dotnet core 2, which blocks use of Powershell 6 alpha.

Please remove if this is a duplicate issue.

**Comment by karelz** [comment]
We have hard dependencies on MacOS 10.12 features (incl. crypto AFAIK).
Also, looking at the MacOS support cycle pattern, it seems 10.11 will be unsupported in Aug 2018, so adding (costly) support now (i.e. in next few months) would not be very practical IMO.

Given that this is the only ask and it is highly unlikely we will invest into something like that, I am closing the issue.
If you strongly disagree and/or if there are significantly more votes, we can reopen the issue and leave it for community support.

**Comment by endowdly** [comment]
>  it seems 10.11 will be unsupported in Aug 2018, so adding (costly) support now (i.e. in next few months) would not be very practical IMO.

This is really depressing news. Looks like I'll have to upgrade my hardware! 

Thanks for taking the time.

**Comment by karelz** [comment]
@endowdly understood, sadly moving forward is the entire SW industry must-have trend (and sometimes pain point as well).
Thanks for understanding!
