### ISSUE TITLE
Finish rewriting System.IO.FileSystem tests

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#2339]
Finish rewriting the tests for System.IO.FileSystem and replacing the giant runTest() methods with individual [Fact]s and [Theory]s, replacing every instance of Console.WriteLine along the way.

**Comment by ianhays** [comment]
This issue will require solutions to #1220, #1221, #1222, #1223.

**Comment by ianhays** [comment]
resolved by #2512.

The mounted drives and current directory tests should be revisited once the build system has the tools to handle them

**Comment by stephentoub** [comment]
> The mounted drives and current directory tests should be revisited once the build system has the tools to handle them

Is there a separate issue tracking that?

**Comment by ianhays** [comment]
Yes, #1220 and #1221
