### ISSUE TITLE
Make DBNull binary serializable

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#23398]
We marked Datasets/DataTables as serializable but they can contain these.

Note it needs some special treatment as it is singleton - see reference sources.

See https://github.com/dotnet/corefx/issues/23213#issuecomment-323272756   
cc @FransBouma

**Comment by Petermarcu** [comment]
@danmosemsft @ViktorHofer what timeframe are we targeting with this?

**Comment by ViktorHofer** [comment]
Probably the next possible servicing release. Dan said he has somebody doing the work required for it.

**Comment by danmosemsft** [comment]
I didn't ask anyone yet. I put it in 2.0.x as a servicing candidate as it makes it unreliable to successfully serialize real world Datasets.

**Comment by danmosemsft** [comment]
Not going to make 2.0.2. Needs a volunteer to do the work.

**Comment by JonHanna** [comment]
Does it have to serialise with an output compatible with NetFX, or just roundtrip within corefx?

**Comment by ViktorHofer** [comment]
Output compatible with NetFX

**Comment by JonHanna** [comment]
I imagine its necessary to bring `UnitySerializationHolder` into CoreLib then.

**Comment by FransBouma** [comment]
Thanks for the PR :) Hopefully it makes it into the next service release :)
