### ISSUE TITLE
Please introduce some location interfaces into .NET Standard

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#23393]
@weitzhandler commented on [Mon Aug 07 2017](https://github.com/dotnet/standard/issues/436)

For example the [`GeoCoordinate`](https://msdn.microsoft.com/en-us/library/system.device.location.geocoordinate) class and the like.

---

@dotMorten commented on [Wed Aug 09 2017](https://github.com/dotnet/standard/issues/436#issuecomment-321441857)

If you were to do this, make sure this is heavily extensible and has custom implementations, as there are many ways of getting location, and also many types of metadata associated with the retrieved location, that in some cases are just as important as the longitude/latitude/altitude (not to mention it's not always longitude/latitude, and altitude can also mean many things).

---

@weshaggard commented on [Fri Aug 18 2017](https://github.com/dotnet/standard/issues/436#issuecomment-323416413)

This issue is better suited for the corefx repo. We won't put anything into the standard until it exists in .NET Core.

**Comment by danmosemsft** [comment]
@weitzhandler @dotMorten do you consider porting GeoCoordinate (well all of System.Device.Location) a good and reasonable approach?

Looking at usage, it seems it was almost exclusively used in Phone apps. https://apisof.net/catalog/System.Device.Location

**Comment by dotMorten** [comment]
@danmosemsft I (and our customers) use it extensively in WPF too. I think it's a reasonable basic class, and as long as it's un-sealed and creatable, we can extend it with our additional more advanced needs, and so can the individual platforms that have more to offer.

I do wish the doc stated very clearly the spatial reference used for longitude and latitude (I assume it's WGS84 but it never clearly says that it must be that). The same goes for the altitude. It at least says it's meters, but not whether it's relative to the geoid, ellipsoid or terrain. An alternative would be to add properties that clearly states the spatial and vertical reference system used.

**Comment by eliashdezr** [comment]
Any update on the GeoCoordinate class?

**Comment by safern** [comment]
Per @ericstj:

_Looks to be built upon the Windows Location COM API https://docs.microsoft.com/en-us/windows/win32/locationapi/windows-location-api-portal. Looks like this API is deprecated and not even supported on many Windows SKUs._

Which might be a blocker/limitation to do this work.

**Comment by ericstj** [comment]
@danmosemsft do you see any problem with putting this  up on ReferenceSource as a first step?

**Comment by terrajobst** [comment]
We don't plan on bringing this .NET Framework API to .NET Core. See [this announcement](https://github.com/dotnet/corefx/issues/41769) for details.
