### ISSUE TITLE
Undo "goto return" works-around

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/corefx#23395]
Issue to track following up on feedback at https://github.com/dotnet/coreclr/pull/13314#issuecomment-321586182 -- now that the JIT tries to pull early returns out of loops, find the code where `goto` has been added to work around its prior inability to do so, revert, and make sure the JIT gives the desired layout.

**Comment by JosephTremoulet** [comment]
Partner of https://github.com/dotnet/coreclr/issues/13466.  Will need to wait for compiler change to propagate.

**Comment by tarekgh** [comment]
@JosephTremoulet do we have links for the PR's which added the goto as a workaround? or pointer to some example for the code need to change? Thanks.

**Comment by JosephTremoulet** [comment]
@tarekgh, here's what @stephentoub said in https://github.com/dotnet/coreclr/pull/13314#issuecomment-321586182:

> @JosephTremoulet, if this fixes the problem, it'd be great to also undo the workarounds employed in a variety of places, e.g.
> https://github.com/dotnet/coreclr/blob/fca2b735f4b5193dfbf7f8b5b8d36060d73a9967/src/mscorlib/src/System/String.Comparison.cs#L47
> https://github.com/dotnet/corefx/blob/b769a73ecf278f92993a8b789aaaaedbc55a7dc3/src/System.Net.Http/src/System/Net/Http/Headers/HeaderUtilities.cs#L334
> https://github.com/dotnet/corefx/blob/cab2165f92380e8424589909158a26ce79e18683/src/System.Memory/src/System/SpanHelpers.byte.cs#L158
> (I think there are also some cases where a comment wasn't left, so it might be worth searching for gotos.)

I'm doing a pass through coreclr now looking for relevant `goto`s, and plan to do the same for corefx when the compiler change has propagated.

**Comment by JosephTremoulet** [comment]
I should mention, as @jkotas did in https://github.com/dotnet/coreclr/issues/13466#issuecomment-323429800, that these `goto`s have been keeping the early return code out of loops (which the JIT should now be able to do by itself) but also have been sharing the same function epilog when multiple such `goto`s target the same function return point (which the JIT does not yet do on its own), so we're not ready to remove all these `goto`s.

**Comment by JosephTremoulet** [comment]
As in https://github.com/dotnet/coreclr/issues/13466, there are a few levels of complexity in the `goto`s I see in the source base:

1. Cases where a single `goto` is the only predecessor of the label.  The JIT can handle these now, and I'll submit a PR shortly.

2. Cases where multiple `goto`s target the same label, but that label simply returns a constant (e.g. the `goto NotEqual` cases in `SequenceEqual` in the two SpanHelpers files.  As in https://github.com/dotnet/coreclr/issues/13466, tweaking our return block sharing to segregate constants could be a cheap way to address these.

3. Cases where multiple `goto`s target the same label, but that label returns something other than a constant (e.g. the various returns in `[IndexOf<T>](https://github.com/dotnet/corefx/blob/dd8bc0d9e929ff4a7da368ae1c16b9b33e9c8a6a/src/System.Memory/src/System/SpanHelpers.T.cs#L48-L120)`.  I don't know why these are written as separate return statements instead of chaining them with mutations to get a single return like in the [analogous String code](https://github.com/dotnet/coreclr/blob/fca2b735f4b5193dfbf7f8b5b8d36060d73a9967/src/mscorlib/src/System/String.Searching.cs#L41-L81), but as written they are a case that a straightforward implementation of tail merge would collapse. back to the current code if we put all the returns inline.

/cc @dotnet/jit-contrib

**Comment by stephentoub** [comment]
Fixed.
