### ISSUE TITLE
System.Data.DataSetExtensions Test Failures with Unbox<T>

### ISSUE THREAD

**Issue by nchikanov** [dotnet/corefx#23407]
Tests fail fast / crash when running ILCBuildType=ret in System.Data.DataSetExtensions on UapAot.
Test do not fail when ILCBuildType=chk. This is likely a code gen bug.

**Failure Location**: (One of many)
https://github.com/dotnet/corefx/blob/73f62d06803d086ee7f6745b55dfde63e27be779/src/System.Data.DataSetExtensions/tests/Mono/EnumerableRowCollectionTest.cs#L99-L102

Then Field<T> calls UnboxT<T>, where there is a failure:
`Exception Unhandled: Unhandled exception at 0x00007FFA233500A0 (xunit.console.netcore.dll) in xunit.console.netcore.exe: 0x80004005: Unspecified error.`
https://github.com/dotnet/corefx/blob/73f62d06803d086ee7f6745b55dfde63e27be779/src/System.Data.DataSetExtensions/src/System/Data/DataRowExtensions.cs#L146

**Execution failed on:**
Windows.10.Amd64.ClientRS3-x64:Release 
Windows.10.Amd64.ClientRS3-x64:Debug 
Windows.10.Amd64.ClientRS3-x86:Debug 
Windows.10.Amd64.ClientRS3-x86:Release 
Windows.10.Amd64-x86:Debug 

**Error message**: 
`Access Violation: Attempted to read or write protected memory. This is often an indication that other memory is corrupt. The application will be terminated since this platform does not support throwing an AccessViolationException.`

**Call stack**:
```
xunit.console.netcore.dll!$14_System::Data::DataRowExtensions::UnboxT$1<System::__Canon>..cctor() Line 146
xunit.console.netcore.dll!System::Runtime::CompilerServices::ClassConstructorRunner.EnsureClassConstructorRun(System::Runtime::CompilerServices::StaticClassConstructionContext * pContext) Line 92
xunit.console.netcore.dll!System::Runtime::CompilerServices::ClassConstructorRunner.CheckStaticClassConstruction(void * returnValue, System::Runtime::CompilerServices::StaticClassConstructionContext * pContext) Line 38
xunit.console.netcore.dll!$14_System::Data::DataRowExtensions.Field<System.__Canon>($13_System::Data::DataRow & InstParam, System::String & row) Line 27
xunit.console.netcore.dll!$15_MonoTests::System::Data::EnumerableRowCollectionTest::<>c.<QueryWhereSelectOrderByDescending>b__3_2($13_System::Data::DataRow & line) Line 161
[Inline Frame] xunit.console.netcore.dll!System::Func$2<System::__Canon,System::__Canon>::Invoke(System::__Canon &) Line 16707565
xunit.console.netcore.dll!$26_System::Linq::Enumerable::SelectEnumerableIterator$2<System::__Canon,System::__Canon>.MoveNext() Line 131
xunit.console.netcore.dll!$15_MonoTests::System::Data::EnumerableRowCollectionTest.QueryWhereSelectOrderByDescending() Line 135
```

cc: @danmosemsft @safern

**Comment by nchikanov** [comment]
I'll open a PR to force the tests to build on ILCBuildType=chk 👍

**Comment by safern** [comment]
Note that this failure is happening on master only because when this tests were added they didn't make the  cut and didn't make it to the release branch; but I would bet this issue is in the release branch as well. 

@hoyMS  could you guys take a look please?

cc: @joshfree

**Comment by hoyMS** [comment]
Sure, will take a look.

**Comment by safern** [comment]
thanks @hoyMS assigned to you.

**Comment by danmosemsft** [comment]
@hoyMS just checking you're not blocked on this investigation?

**Comment by hoyMS** [comment]
No, the fix is ready. Will check it into TFS ProjNdev3 first.

**Comment by hoyMS** [comment]
The fix has been checked into ProjectN as Changeset 1671794

**Comment by safern** [comment]
Thanks @hoyMS

**Comment by joshfree** [comment]
Milestone = UWP6.1

**Comment by joshfree** [comment]
this fix will be in Preview 2

**Comment by safern** [comment]
I still need to reenable to build the tests in ret mode. Will open a PR later
