### ISSUE TITLE
FtpWebRequest on core does not reuse connections

### ISSUE THREAD

**Issue by pakrym** [dotnet/corefx#23404]
FtpWebRequest on .net core connects and disconnects for every operation:

![image](https://user-images.githubusercontent.com/1697911/29480430-1aeaaf88-842d-11e7-8359-3e4f07b1e579.png)

Eventually hitting connection rate limit:

![image](https://user-images.githubusercontent.com/1697911/29480440-2e2bbb6e-842d-11e7-99b9-0d55aebb2e35.png)

Same code on net461 reuses connection:
![image](https://user-images.githubusercontent.com/1697911/29480455-43bcbcda-842d-11e7-8348-6b85efcc533a.png)

Code:
``` c#
 var request = (FtpWebRequest) WebRequest.Create(address);
request.Method = WebRequestMethods.Ftp.UploadFile;
request.KeepAlive = true;
request.UseBinary = true;
request.Credentials = new NetworkCredential(publishingProfile.FtpUsername, publishingProfile.FtpPassword);
request.ConnectionGroupName = "group";
using (var fileStream = File.OpenRead(file.FullName))
{
    using (var requestStream = await request.GetRequestStreamAsync())
    {
        await fileStream.CopyToAsync(requestStream);
    }
}
await request.GetResponseAsync();
```

**Comment by davidsh** [comment]
The Ftp code was rewritten for core and uses a simpler TCP logic (TcpClient) than the .NET Framework which uses ServicePoint architecture and connection pools.

cc: @karelz @Priya91

**Comment by karelz** [comment]
That's correct `FtpWebRequest` is obsolete API: https://github.com/terrajobst/platform-compat/blob/master/docs/DE0003.md

We should update the docs to suggest alternatives.
@geoffkizer @Priya91 can you please update the API compat page? https://github.com/dotnet/corefx/wiki/ApiCompat

**Comment by halter73** [comment]
Suggestions for alternatives would certainly be appreciated.

**Comment by caesar1995** [comment]
The API compat page has already contains the `System.Net.*WebRequest` should not be used.

> We should update the docs to suggest alternatives.

Do you mean [here](https://github.com/dotnet/docs)? As for the alternative, I'm not sure what could be. Probably [FluentFTP](https://www.nuget.org/packages/FluentFTP)? (which is also compatible with latest .net standard 2.0)

@davidsh @karelz

**Comment by karelz** [comment]
We should document it in https://github.com/terrajobst/platform-compat/blob/master/docs/DE0003.md - it recommends HttpClient, which is replacement only for HttpWebRequest. We may need to add specific entries there. Feel free to check with @pjanotti

**Comment by caesar1995** [comment]
Close in https://github.com/dotnet/platform-compat/pull/102
