### ISSUE TITLE
Enable System.Runtime.CompilerServices.Unsafe and System.Memory tests for UAP

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#23406]
We need to get targeted unit test for Span enabled. They are very likely uncover bugs that will be hard to track down otherwise (e.g. #23073).

**Comment by danmosemsft** [comment]
@ahsonkhan would this be you? Do you expect to be able to do this in the relatively near future?

**Comment by ahsonkhan** [comment]
I will not be able to get to this issue until next week at the earliest. What exactly is needed to enable the test for UAP?

**Comment by danmosemsft** [comment]
It might be as simple as editing src\System.Memory\tests\Configurations.props and src\System.Runtime.CompilerServices.Unsafe\tests\Configurations.props to replace netcoreapp with netstandard (or, if there are netcoreapp specific tests, then add uap)
@safern is that all that's required to get these to run for UAP? The implementations already have uap/netstandard configurations.

**Comment by safern** [comment]
> @safern is that all that's required to get these to run for UAP? The implementations already have uap/netstandard configurations.

Correct. That is the only thing needed.

**Comment by danmosemsft** [comment]
@ahsonkhan I've assigned this to you if you don't mind. If you don't think you can get to it next week, let me know. 
@jkotas are you suggesting that coverage is missing in general, or just observing the tests aren't on yet for uap?

**Comment by jkotas** [comment]
From above: These tests are very likely uncover bugs that will be hard to track down otherwise (e.g. #23073).

We are getting some indirect coverage as Span is getting used in more and more places in corefx. However, it would be much more productive to debug uapaot-specific Span bugs in targeted Span tests than in the more complex tests that happen to exercise Span indirectly.
