### ISSUE TITLE
 .NET Core 2.1 support  .NET Framework 4.7？ OR .NET Framework 4.6.2

### ISSUE THREAD

**Issue by ghd258** [dotnet/corefx#23411]
.NET Core 2.1 support  .NET Framework 4.7？ OR .NET Framework 4.6.2

**Comment by danmosemsft** [comment]
@ghd258 can you clarify, what do you mean by support?

Also we havent announced goals for 2.1 yet.

**Comment by tarekgh** [comment]
CC @weshaggard

**Comment by danmosemsft** [comment]
@ghd258 does this help? If not please clarify.
https://docs.microsoft.com/en-us/dotnet/standard/net-standard
