### ISSUE TITLE
.NET Core 2.0 Ubuntu 16.04 SocketException 10040 MessageSize

### ISSUE THREAD

**Issue by caozhiyuan** [dotnet/corefx#23416]
Ubuntu 16.04 SocketException 10040 MessageSize
nioBuffers List<ArraySegment<byte>> nioBuffers 
when nioBuffers  is large (total 892913 byte)  SocketException 10040 MessageSize

SocketError errorCode;
long localWrittenBytes = socket.Send(nioBuffers, SocketFlags.None, out errorCode);
if (errorCode != SocketError.Success && errorCode != SocketError.WouldBlock)
{
      throw new SocketException((int)errorCode);
}

![29483441-fbe0779c-84d8-11e7-8963-383c88c35151](https://user-images.githubusercontent.com/3415285/29486311-61bdaf58-8515-11e7-9aa6-6e1730a78697.png)

**Comment by caozhiyuan** [comment]
git https://github.com/caozhiyuan/DotNetty     run Rpc.Server in Ubuntu 16.04    run Rpc.Client in windows

**Comment by caozhiyuan** [comment]
@karelz  git https://github.com/caozhiyuan/DotNetty 
in examples folder run SocketAsyncClient in linux  run  SocketAsyncServer in window 
![qq 20170821184606](https://user-images.githubusercontent.com/3415285/29516004-4edbb1f4-86a1-11e7-83cc-f0a127021046.png)

**Comment by karelz** [comment]
That looks like a large project. Can you please isolate the repro to **minimal**?
That will ensure there are no accidental dependencies on undesired classes, libraries, etc. from the rest of the project.

**Comment by caozhiyuan** [comment]
@karelz  SocketAsyncClient  SocketAsyncServer has no dependencies  just git clone cd examples folder and dotnet run

**Comment by caozhiyuan** [comment]
it's just test code

**Comment by karelz** [comment]
Both source codes seem to use DotNetty components:
https://github.com/caozhiyuan/DotNetty/blob/dev/examples/Rpc.Server/Program.cs
https://github.com/caozhiyuan/DotNetty/blob/dev/examples/Rpc.Client/Program.cs

Hard to say how deep the rabbit hole goes.

We really need isolated repros to be efficient on the team. Debugging through larger frameworks is huge waste of time (hours at best, days at worst). The first thing I usually do is to make the repro smaller anyway.

**Comment by caozhiyuan** [comment]
@karelz https://github.com/caozhiyuan/DotNetty/tree/dev/examples/SocketAsyncClient  
https://github.com/caozhiyuan/DotNetty/tree/dev/examples/SocketAsyncServer

**Comment by caozhiyuan** [comment]
@karelz please take a look

**Comment by tmds** [comment]
@caozhiyuan What is `nioBuffers.Length` ?

According to the POSIX spec of sendmsg:

> [EMSGSIZE]
The message is too large to be sent all at once (as the socket requires), or the msg_iovlen member of the msghdr structure pointed to by message is less than or equal to 0 or is greater than {IOV_MAX}.

IOV_MAX on linux is 1024.

**Comment by caozhiyuan** [comment]
@tmds nioBuffers is  List<ArraySegment> 
when i use Blocking Socket will not has this error

**Comment by tmds** [comment]
> @tmds nioBuffers is List

How many elements are there in the list? Does it start to fail when it's over 1024?

**Comment by caozhiyuan** [comment]
@tmds  when nioBuffers total byte size big than 344064,will raise 10040 MessageSize Error（Message Too Long） (noblocking socket)

**Comment by caozhiyuan** [comment]
@tmds  at now i use block socket and  no problem

**Comment by tmds** [comment]
> @tmds when nioBuffers total byte size big than 344064

I don't want to know the total byte size. I'd like the know the number of ArraySegment in nioBuffers.

**Comment by caozhiyuan** [comment]
@tmds  code blow:
 List<ArraySegment<byte>> nioBuffers = new List<ArraySegment<byte>>();
                for (int i = 0; i < 4000; i++)
                {
                    nioBuffers.Add(new ArraySegment<byte>(Encoding.UTF8.GetBytes(message)));
                }

                SocketError errorCode;
                long localWrittenBytes = clientSocket.Send(nioBuffers, SocketFlags.None, out errorCode);
                if (errorCode != SocketError.Success && errorCode != SocketError.WouldBlock)
                {
                    throw new SocketException((int)errorCode);
                }

**Comment by tmds** [comment]
@caozhiyuan If you play a little with the `4000`, I think it will work for `1024` (IOV_MAX) and less and fail when higher.

**Comment by caozhiyuan** [comment]
@tmds  block socket no this problem. and in windows block and noblock socket both no this problem

https://github.com/dotnet/corefx/issues/23737

**Comment by tmds** [comment]
@caozhiyuan can you find out at what value (instead of `4000`) noblock socket works on Linux?

**Comment by caozhiyuan** [comment]
@tmds  344064 bytes

**Comment by tmds** [comment]
```
for (int i = 0; i < 4000; i++)
                    ~~~~
```
What is the highest value you can put here that works?

**Comment by caozhiyuan** [comment]
@tmds just write a test and run

**Comment by tmds** [comment]
Summary:
Socket.Send with List<ArraySegment> fails with MessageSize error when Count is higher than IOV_MAX

\cc @stephentoub @geoffkizer @karelz

**Comment by tmds** [comment]
Minimal repro:
```C#
            for (int segmentCount = 1023; segmentCount <= 1025; segmentCount++)
            {
                var listener = new TcpListener(IPAddress.Loopback, 0);
                listener.Start();
                var client = new TcpClient();
                client.Connect(listener.LocalEndpoint as IPEndPoint);
                Socket socket = listener.AcceptSocket();

                socket.Blocking = false;
                var buffers = new List<ArraySegment<byte>>();
                var buffer = new byte[1];
                for (int i = 0; i < segmentCount; i++)
                {
                    buffers.Add(new ArraySegment<byte>(buffer));
                }
                SocketError error;
                int bytesSent = socket.Send(buffers, SocketFlags.None, out error);

                System.Console.WriteLine($"{segmentCount}: {bytesSent} - {error}");
            }
```
Outputs:
```
1023: 1023 - Success
1024: 1024 - Success
1025: 0 - MessageSize
```
Expected:
```
1023: 1023 - Success
1024: 1024 - Success
1025: 1025 - Success
```

**Comment by stephentoub** [comment]
@tmds, thanks for the summary. What is the bug here?  It sounds like the OS simply doesn't support the operation being tried, and Socket.Send is correctly reporting the EMSGSIZE error provided by the OS.

**Comment by tmds** [comment]
@stephentoub The OS behavior is surfacing. I think this will behave the same xplat if we'd `msghdr.msg_iovlen = min(msghdr.msg_iovlen, IOV_MAX)` when calling `sendmsg` and `recvmsg`.

**Comment by stephentoub** [comment]
> I think this will behave the same xplat if we'd msghdr.msg_iovlen = min(msghdr.msg_iovlen, IOV_MAX) when calling sendmsg and recvmsg.

Ah, such that we'll restrict ourselves to the max, and then if the full data wasn't sent, the existing logic would simply retry for whatever remains?  That makes sense.

**Comment by tmds** [comment]
> Ah, such that we'll restrict ourselves to the max, and then if the full data wasn't sent, the existing logic would simply retry for whatever remains? That makes sense.

Exactly! I can do a PR next week if it's up for grabs.

**Comment by stephentoub** [comment]
Thanks :)

**Comment by stephentoub** [comment]
cc: @geoffkizer

**Comment by caozhiyuan** [comment]
@tmds  i limit to list count 1024 now in linux.
