### ISSUE TITLE
HttpWebRequest in .NET Core 2.0 throwing 301 Moved Permanently

### ISSUE THREAD

**Issue by lviana1** [dotnet/corefx#23422]
The following single-line console program works just fine in .NET Framework 4.6.1:

```c#
Console.WriteLine(XDocument.Load("http://feeds.thisamericanlife.org/talpodcast"));
```

However, in .NET Core 2.0 it throws the following exception:

```
Unhandled Exception: System.Net.WebException: The remote server returned an error: (301) Moved Permanently.
   at System.Net.HttpWebRequest.GetResponse()
   at System.Xml.XmlDownloadManager.GetNonFileStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri)
   at ConsoleApp1.Program.Main(String[] args)
```

This has always worked in the full .NET Framework, presumably because it automatically follows the redirection. However, it does not do that in .NET Core (it seems that AllowAutoRedirect is simply ignored), so I'm assuming this is a bug. Please let us know if there's a workaround.

[EDIT] Fixed C# syntax highlight & exception code formatting by @karelz

**Comment by karelz** [comment]
Are you able to reproduce the same problem with just using Networking APIs? (without XML APIs) -- that will help us identify if it is problem in XML or Networking area.

BTW: The URL above does not seem to be forwarded anywhere in browser. Is that expected?

**Comment by lviana1** [comment]
Yes, I can reproduce the same problem using just Networking APIs. You can use the simple console app below:

`using System.Net;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var request = WebRequest.Create("http://feeds.thisamericanlife.org/talpodcast");
            var response = request.GetResponse();
        }
    }
}
`

If you target that console app against .NET Framework 4.6.1 it works fine. However, it you target the very same code, using the very same IDE (Visual Studio 2017 15.3), running on the very same OS (Windows 10), it will throw the exception below:

`Unhandled Exception: System.Net.WebException: The remote server returned an error: (301) Moved Permanently.
   at System.Net.HttpWebRequest.GetResponse()
   at ConsoleApp1.Program.Main(String[] args)`

**Comment by sandersaares** [comment]
The site has an interesting redirect pattern:

1. Redirect to HTTPS variant of the same URL.
1. Redirect to a different URL over HTTP.

.NET Core appears to be throwing the exception on the second redirect.

**Comment by lviana1** [comment]
FWIW, I've seen similar exceptions being thrown with other sites in .NET Core. For instance: http://www.npr.org/rss/podcast.php?id=35.

**Comment by karelz** [comment]
https->http redirection is not supported - see #19183

**Comment by lviana1** [comment]
Are you saying that this is by design in .NET Core, but NOT in the full .NET Framework? As I mentioned above, the exact same code has always worked just fine when targeted against the full .NET Framework, so if this is by design in .NET Core and NOT in the full .NET Framework that seems inconsistent...

**Comment by davidsh** [comment]
>Are you saying that this is by design in .NET Core, but NOT in the full .NET Framework?

Yes, this is by-design in .NET Core.  This is a security-related change to prevent HTTPS -> HTTP redirection which is inherently insecure.  For apps that need to follow those redirections, you can turn off automatic redirection in the handler and follow the Location: response header manually.

**Comment by tynor88** [comment]
If you do:

```csharp
HttpWebRequest webRequest = HttpWebRequest.CreateHttp("https://someurl.com");
webRequest.AllowAutoRedirect = false;
```

And read the response from an Uri that gets redirected to _http_ the following code throws an exception:
```csharp
var resp = (HttpWebResponse)webRequest.GetResponse()
```

It looks like the AllowAutoRedirect = false doesn't work properly.

Is that also by design @davidsh ?

**Comment by davidsh** [comment]
If you set AllowAutoRedirect, then you will end up not following the redirect.  That means ending up with the 301 response.

HttpWebRequest (unlike HttpClient) throws exceptions for non-successful (non-200) status codes.  So, getting an exception (most likely a WebException) is expected.

**Comment by tynor88** [comment]
Makes sense. Thanks for the swift explanation!

**Comment by krispenner** [comment]
Hi,  I don't think I understand the proposed work around.  Both a WebClient and HttpWebRequest fail to follow a 301 Redirect.

Yahoo is giving the same redirect scenario as mentioned above:

> The site has an interesting redirect pattern:
>   1. Redirect to HTTPS variant of the same URL.
>   2. Redirect to a different URL over HTTP.

This all worked fine for over a year in .NET 4.6.1 but after moving the class library to .NET Standard 2.0 and running within .NET Core 2.0 both options blow up with a WebException.  If I code in the new redirection URL then it works, but if the URL ever changes in the future this may break again.

If this was all disabled to prevent https -> http then why not use an enum for the auto redirection property instead of a boolean?
AllowAutoRedirect = AutoRedirectMode.Always|SameSchemeOnly|Never;
Then set WebClient to use Always.
Or add a second boolean property:
AllowInsecureSchemaRedirects = true|false;
Again ensure the WebClient is set to true for this.
I believe anyone using the WebClient expects it to follow redirects, the whole point of that class was for it to just work and get the resource you're after super easy.

> If you **set** AllowAutoRedirect, then you will end up **not** following the redirect. That means ending up with the 301 response.

Not sure I understand the statement there...
Setting or not setting AllowAutoRedirect on the HttpWebRequest has no affect from my testing.

You can try this with the code below
**http**://finance.yahoo.com/d/quotes.csv?s=CADUSD=X&f=sxnpm3m4jkd1
the response is a redirect to
**https**://finance.yahoo.com/d/quotes.csv?s=CADUSD=X&f=sxnpm3m4jkd1
then:
**http**://**download**.finance.yahoo.com/d/quotes.csv?s=CADUSD=X&f=sxnpm3m4jkd1


      var url = "http://finance.yahoo.com/d/quotes.csv?s=CADUSD=X&f=sxnpm3m4jkd1";

      // System.Net.WebException: The remote server returned an error: (301) Redirect.
      //   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
      //   at System.Net.WebRequest.<> c.< GetResponseAsync > b__68_2(IAsyncResult iar)
      var request = WebRequest.CreateHttp(url);
      request.AllowAutoRedirect = true;
      using (var response = await request.GetResponseAsync().ConfigureAwait(false))
      using (var stream = response.GetResponseStream())
      using (var reader = new StreamReader(stream, Encoding.UTF8))
      {
        var results = await reader.ReadToEndAsync().ConfigureAwait(false));
      }

      // System.Net.WebException: The remote server returned an error: (301) Redirect.
      //   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
      //   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
      //   at System.Net.WebClient.< GetWebResponseTaskAsync > d__112.MoveNext()
      using (var web = new WebClient())
      {
        var results = await web.DownloadStringTaskAsync(new Uri(url)).ConfigureAwait(false);
      }

Appreciate any help or guidance on how to cleanly and easily handle this.  I don't see how HttpClient will solve this scenario unless I write my own handlers and keep creating new requests when receiving redirects and I believe this should just work out of the box.

Thanks,
kp

**Comment by RevealedFrom** [comment]
I have `AllowAutoRedirect` set to false, and the exact same code and web site that work fine in normal .NET throws an exception in Core when the response is 302. 

In my case, the redirect was from HTTPS to HTTPS, same web server.

**Comment by jgilbert2017** [comment]
No, it's not the "standard use" of HttpWebRequest.

Throwing an exception when AllowAutoRedirect=false prevents access to the full HTTP response (eg Headers or payload text/data).

The flag AllowAutoRedirect has always allowed for the caller to manually process the redirects which is an important piece of functionality.  This is NOT a good API design decision.  There should be a way to manually process the redirects without resorting to try/catch.

@karelz you need to trap it in try/catch block and inspect the WebException etc. That is standard use of HttpWebRequest.
