### ISSUE TITLE
XmlSchema in CoreFX

### ISSUE THREAD

**Issue by lleraromero** [dotnet/corefx#2342]
Hi,

Are there any plans to include XmlSchema in CoreFX? If not, is there any recommended way to manipulate schemas?

Thank you.

**Comment by Grochni** [comment]
+1 Validation using XmlSchema is a big thing I'm missing.

**Comment by mjrousos** [comment]
+1, I've worked with a couple customers now who have requested this feature in .NET Core. In my experience, it's one of the few commonly-requested features that we don't have a good story for. I think we ought to prioritize adding this.

**Comment by SariDev** [comment]
+1 for this.
A similar Issue exists over here:
[https://github.com/dotnet/corefx/issues/3633#issuecomment-200741235](url)

**Comment by prachi2607** [comment]
Schema validation is a very much needed feature.
Is there a milestone assigned for it

**Comment by krwq** [comment]
We are targeting this for post 1.0, most likely November this year. We are aware this is really important feature. Since XmlReader/XmlWriter design changed quite a bit between full .NET and .NET core and does not include XmlSchema right now, we need to carefully design this so that System.Xml.ReaderWriter remains slimmer and XmlSchema functionality is still working.

**Comment by krwq** [comment]
System.Private.Xml is already on the way in dev/api. We need to resolve packaging problems for System.Xml facade to make that widely accessible: https://github.com/NuGet/Home/issues/3167

**Comment by karelz** [comment]
It should be already done, @sepidehMS can you please double-check?

**Comment by danmosemsft** [comment]
XML Schema is already done. It's not yet in an easily consumable form though.

**Comment by brentschmaltz** [comment]
@danmosemsft is XML Schema available in a public package?

**Comment by sepidehMS** [comment]
@brentschmaltz Xml Schema will be publieshed as part of System.Xml.ReaderWriter package in NetCore2.0 and NetStandard2.0. If you like to consume the latest prerelease version, please follow [these instructions](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md).
