### ISSUE TITLE
System.Runtime.Extensions nuget package installs signed dll (v4.6.24705.1)

### ISSUE THREAD

**Issue by onematchfox** [dotnet/corefx#23436]
When referencing System.Runtime.Extensions (4.3.0) (or anything that makes uses of it), the dll that gets downloaded/deployed seems to be v4.6.24705.1 as opposed to the standard unsigned version as per the rest of the system dlls. The results in issues such as the following when attempting to publish for ubuntu 16.04. 

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication..ctor(Boolean throwOnUnexpectedArg)
```

Issue was not present when targeting .NET Core 1.1 and only presented itself after upgrading to .NET Core 2.0.

Any advice on how to get around this?

(Have attempted to clear nuget cache without any luck).

[EDIT] Fixed exception formatting by @karelz

[EDIT] Added details around affected version by @onematchfox.

**Comment by danmosemsft** [comment]
@weshaggard ?

**Comment by weshaggard** [comment]
` v4.6.24705.1` is the file version not the assembly version. I would need more information about what you are targeting to help with the error. ARe you targeting .NET Core 1.1 or .NET Core 2.0?

**Comment by onematchfox** [comment]
Sorry. That info should have been there in the first place. Targeting. NET
Core 2.0. No issue with 1.1. Issue only presented itself when upgrading.

On 22 Aug 2017 18:29, "Wes Haggard" <notifications@github.com> wrote:

v4.6.24705.1 is the file version not the assembly version. I would need
more information about what you are targeting to help with the error. ARe
you targeting .NET Core 1.1 or .NET Core 2.0?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dotnet/corefx/issues/23436#issuecomment-324080572>, or mute
the thread

**Comment by weshaggard** [comment]
@onematchfox with .NET Core 2.0 the System.Runtime.Extensions package reference isn't even needed as it is included in the core platform package. Can you remove your package reference to that and see if that helps?

**Comment by onematchfox** [comment]
@weshaggard , thanks for the suggestion. Unfortunately it is not as simple as that. Yes, this works in the case of the actual error being thrown from Microsoft.Extensions.CommandLineUtils. However, the library (System.Runtime.Extensions) is (indirectly) referenced by other libraries I I cannot get away from using. Most importantly would be Newtonsoft.Json. This is why I thought adding a "hard" dependency/reference on the actual library might resolve the issue. Another example which results in this issue is CsvHelper (https://github.com/JoshClose/CsvHelper) - although, interestingly enough, this one can be resolved by referencing Microsoft.Csharp 4.4.0.

**Comment by onematchfox** [comment]
Also, this issue seems to affect other libraries as well. See https://github.com/dotnet/core/issues/857 which was closed based on my suggestion that the reference to Microsoft.AspNetCore.All was causing the error. It seems like the underlying issue could be the same.

**Comment by weshaggard** [comment]
@onematchfox Is there any way you can create a project that repro's the problem and point me at it? From there I should be able to diagnose what is going wrong and suggest a fix.

**Comment by onematchfox** [comment]
@weshaggard. Sure thing. Done. 

https://github.com/onematchfox/NetCore2Console

Initial commit is broken by direct reference to System.Runtime.Extensions. - https://github.com/onematchfox/NetCore2Console/commit/4eb835d79349e68d9cef12f6ad71a92df206bddf

Working version with reference removed - https://github.com/onematchfox/NetCore2Console/commit/339e7623489d72fb2a74acf5b2a6d6e889acaee2

Finally (current master state), broken again by reference to Newtonsoft.Json - https://github.com/onematchfox/NetCore2Console/commit/141b490bcd1f51ac1b3d2e14185240a846b0094f

**Comment by weshaggard** [comment]
@onematchfox your project actually works for me can you tell me what version of the tools you have?  Both VS and dotnet SDK (dotnet --info). It would seem that you potentially are using a prerelease version of the tools before we included the conflict resolution tasks.

**Comment by onematchfox** [comment]
@weshaggard 
-----------
Microsoft Visual Studio Community 2017 
Version 15.3.0
VisualStudio.15.Release/15.3.0+26730.3
Microsoft .NET Framework
Version 4.7.02046
-------------

.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by onematchfox** [comment]
Also, just to confirm @weshaggard, you are publishing for ubuntu and running that output? Building and running via VS on Windows works fine as does publishing for windows.

**Comment by weshaggard** [comment]
Your tool versions look correct. 

>Also, just to confirm @weshaggard, you are publishing for ubuntu and running that output? Building and running via VS on Windows works fine as does publishing for windows. (Just want to be sure I haven't been unclear above)

I was running on windows. I didn't catch the ubuntu publish mention in the first post. Can you give me the exact command you are using to build/publish for ubuntu?

**Comment by onematchfox** [comment]
Am using VS folder profile to publish. Xml available in the repo at https://github.com/onematchfox/NetCore2Console/blob/master/NetCore2Console/Properties/PublishProfiles/ubuntu.pubxml

**Comment by weshaggard** [comment]
I'm not familiar with how that publishing works, but I can see it doesn't appear to be running our conflict resolution logic which is why you are getting the older System.Runtime.Extensions.dll.

@ericstj @dsplaisted do you guys know anything about how that VS publish targets work? It would appear we don't correctly hook in the conflict resolution into that publish.

As a workaround you can publish from the command line `dotnet publish -r ubuntu.16.04-x64` which does appear to correctly run the conflict resolution and picks the correct System.Runtime.Extensions.dll

**Comment by ericstj** [comment]
I think you may be hitting this bug: https://github.com/dotnet/sdk/issues/1502.  

If that's the case, you can try building/publishing using dotnet.exe to see if it works?

**Comment by onematchfox** [comment]
@weshaggard and @ericstj, I can confirm that publishing via dotnet.exe does indeed work. Wes, thanks so much for your assistance (and your patience) in identifying/resolving this! Will close this issue now as the problem clearly lies with msbuild rather than in corefx. 

Eric, Am happy to continue you this discussion on the referenced issue if you would prefer? Suffice to say that I haven't been able to 100% confirm that this is the same error as you have linked as I don't see the same error when running "msbuild /t:publish". But that command also doesn't seem to be actually publishing a standalone copy of the app for me so I guess I'm missing one of more arguments. Have tried running with /p:PublishProfile=ubuntu on the repo mentioned above but that still doesn't seem to select the correct folder profile. Any idea what command arguments I would need to use to correctly test this? Found https://docs.microsoft.com/en-us/aspnet/core/publishing/web-publishing-vs?tabs=aspnetcore2x but that doesn't seem to cover all the options (e.g. to correctly specifying the target platform/runtime identifier).

**Comment by ericstj** [comment]
You don't necessarily need to do it from the command-line.  You can [increase the verbosity](https://msdn.microsoft.com/en-us/library/jj651643.aspx#To-change-the-amount-of-information-included-in-the-build-log) of the output log in visual studio then examine the output window, then search for "encountered conflict".

I'm pretty certain you're hitting that bug if you are publishing for a non-Windows RID from a Windows machine.

**Comment by onematchfox** [comment]
@ericstj, sorry to come back to this again. Followed your advice and enabled diagnostic logging for publishing and I'm afraid I still don't see the same error as the one in the issue you linked. All conflict resolution seems to "pass" - i.e. a winner is selected. There are no instances of the text "Could not determine a winner" and I also don't even see an "encountered conflict" message relating to System.Runtime.Extensions. Attaching full diagnostic log for reference. Do you still think this is the same issue?

[NetCore2Console publish log.txt](https://github.com/dotnet/corefx/files/1266290/NetCore2Console.publish.log.txt)

**Comment by ericstj** [comment]
The log doesn't actually include the publish target in it, this looks like only the output for build.  We do two passes of conflict resolution, one during build and another during publish.  You can ensure you're looking at a publish log by finding `_HandlePublishFileConflicts` in the log.

The reason why your build log is not showing the conflict for S.R.E is that you appear to be referencing it transitively with exclude:compile.  That's normal for that assembly since it typically is only used for runtime and has few exchange types in it.  I do see the requisite conditions, however, that would trigger https://github.com/dotnet/sdk/issues/1502 on publish.

Regarding your earlier comment around command line, you can use `msbuild /t:publish /p:RuntimeIdentifier=ubuntu.16.04-x64 /flp:v=diag`

In this case since your conflicts are all coming from our old runtime-specific packages, you should be able to workaround the issue as I mention here: https://github.com/dotnet/corefx/issues/23283#issuecomment-322849842

Add the following dependency to your project:
```xml
<PackageReference Include="Microsoft.NETCore.Targets" Version="2.0.0" />
```

**Comment by onematchfox** [comment]
Thanks again @ericstj! I just wanted to make sure it was the same issue. Am happy to workaround by publishing via "dotnet publish" for the time being but will also try your additional suggestion.
