### ISSUE TITLE
Update documentation for `System.Numerics.Vector<T>` to be more explicit.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#23448]
This was raised in the dotnet/corefx gitter channel.

It is not currently clear from the documentation that the types exposed by the `System.Numerics.Vectors` assembly are not meant for general purpose `Vector` operations and that the types are heavily tied to the underlying hardware.

The documentation for this could be greatly improved.

Some types, such as `Vector<T>` should have explicit (and readily visible) documentation that its element count is limited to `Vector<T>.Count`, and that certain methods (such as the [Vector<T>(T[])](https://msdn.microsoft.com/en-us/library/dn877694(v=vs.111).aspx) constructor) will only use the first `Vector<T>.Count` elements and ignore the remaining.

**Comment by aliostad** [comment]
Thank you!

**Comment by danmosemsft** [comment]
I think this issue probably should be in https://github.com/dotnet/docs.

**Comment by karelz** [comment]
We need to propose wording changes in docs, then move it to docs repo.
Anyone interested?

**Comment by Gnbrkm41** [comment]
Opened a fix PR that (hopefully) points these out in dotnet/dotnet-api-docs repo.
