### ISSUE TITLE
Resetting attributes broken in brokered locations

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#23444]
Related to PR: #23316

Setting attributes twice on a file in a brokered location under UAP doesn't work. Issue is understood, need a new drop of FileApiInterop to fix.

**Comment by joshfree** [comment]
Also tracked as DevDiv 485014

**Comment by danmosemsft** [comment]
#24848

**Comment by JeremyKuhne** [comment]
We never took this interop dll.
