### ISSUE TITLE
IPEndPoint should have Parse/TryParse methods

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#23463]
IPAddress has this, but not IPEndPoint.

**Comment by stephentoub** [comment]
What would it parse specifically? Anything in the exact format it renders in ToString?

**Comment by geoffkizer** [comment]
Yes.  Basically, IPAddress:Port.

**Comment by NickCraver** [comment]
I came here to second this, I was looking at a library we maintain and IPv6 failures (basically splitting on `:` underneath) and you find examples like: https://stackoverflow.com/questions/2727609/best-way-to-create-ipendpoint-from-string

This *really* seems like something that should be in the BCL. When it was IPv4, sure, split on the port delimiter and call it a day. But not we have IPv6 and semicolons are everywhere and people are parsing (and allocating arrays and re-joining them) all over the place. It's not good practice, many implementations are error-prone, and won't keep up (just as they haven't with IPv4 -> IPv6). This should be on `IPEndPoint` for all to use instead.

**Comment by stephentoub** [comment]
Sounds reasonable.

**Comment by NickCraver** [comment]
cc @terrajobst this would be a simple API proposal (one method addition) - are we open to such for ns3.0?

**Comment by davidsh** [comment]
Tracking this with #31291
