### ISSUE TITLE
Name not legible IsSuccessStatusCode in HttpResponseMessage

### ISSUE THREAD

**Issue by fernandoresalves** [dotnet/corefx#23468]
I believe that the attribute IsSuccessStatusCode could be more intuitive.

**Comment by davidfowl** [comment]
What are you suggesting? The name can't be changed because that would be massively breaking for little gain.

**Comment by fernandoresalves** [comment]
My suggestion and successStatus.

**Comment by davidsh** [comment]
Thank you for your suggestion. Unfortunately, this would be a large break in app-compat for the API.

Feel free to contribute your ideas, though, as part of future planning for revisions to networking APIs:
https://github.com/dotnet/designs
