### ISSUE TITLE
Enable MinLengthAttribute and MaxLengthAttribute in more collection types.

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/corefx#23461]
Please implement a `ValidationAttribute` that validates that a collection-typed property has any elements.
Maybe expand the `RangeAttribute` functionality to work with collection?

```
public class Contact
{
  [Range(3, 10)]
  public ICollection<Phone> Phones { get; set; }
}
```

**Comment by lajones** [comment]
Note: [MaxLengthAttribute](https://github.com/dotnet/corefx/blob/7c3c88d490ae557241aa838695063415822dc692/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/MaxLengthAttribute.cs#L81) and [MinLengthAttribute](https://github.com/dotnet/corefx/blob/7c3c88d490ae557241aa838695063415822dc692/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/MinLengthAttribute.cs#L65) can already be applied to `ICollection`s.

**Comment by weitzhandler** [comment]
Wow, that's great than!
But apparently it only works with arrays 😳 

Repro:

    class Program
    {
      static void Main(string[] args)
      {
        var p = new Program();
        var result = Validator.TryValidateObject(p, new ValidationContext(p), null, true);
        Debug.Assert(!result);
      }

      [MinLength(2)]
      public IEnumerable<string> Names { get; } = new List<string>(); //works: new string[] { };
    }

StackTrace:
```
   at System.ComponentModel.DataAnnotations.MinLengthAttribute.IsValid(Object value)
   at System.ComponentModel.DataAnnotations.ValidationAttribute.IsValid(Object value, ValidationContext validationContext)
   at System.ComponentModel.DataAnnotations.ValidationAttribute.GetValidationResult(Object value, ValidationContext validationContext)
   at System.ComponentModel.DataAnnotations.Validator.TryValidate(Object value, ValidationContext validationContext, ValidationAttribute attribute, ValidationError& validationError)
   at System.ComponentModel.DataAnnotations.Validator.GetValidationErrors(Object value, ValidationContext validationContext, IEnumerable`1 attributes, Boolean breakOnFirstError)
   at System.ComponentModel.DataAnnotations.Validator.GetObjectPropertyValidationErrors(Object instance, ValidationContext validationContext, Boolean validateAllProperties, Boolean breakOnFirstError)
   at System.ComponentModel.DataAnnotations.Validator.GetObjectValidationErrors(Object instance, ValidationContext validationContext, Boolean validateAllProperties, Boolean breakOnFirstError)
   at System.ComponentModel.DataAnnotations.Validator.TryValidateObject(Object instance, ValidationContext validationContext, ICollection`1 validationResults, Boolean validateAllProperties)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\Shimmy\AppData\Local\Temporary Projects\ConsoleApp1\Program.cs:line 16
```

**Comment by weitzhandler** [comment]
Apparently this has been discussed before: #18361.
Should I keep this issue open?

**Comment by weitzhandler** [comment]
Apparently this has been discussed before: #18361.

**Comment by lajones** [comment]
Note to self: see also [PR20934](https://github.com/dotnet/corefx/pull/20934).

**Comment by weitzhandler** [comment]
Re-opening, because the concern of generic `ICollection` and `IEnumerable` is still valid.

**Comment by weitzhandler** [comment]
I'd love to see `IEnumerable` addressed as well, would be glad to see something like the following added [here](https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/MinLengthAttribute.cs#L69):

      else if (value is IEnumerable enumerable)
      {
        var enumerator = enumerable.GetEnumerator();
        while (length < Length && enumerator.MoveNext())
        {
          length++;
        }
      }

And the following added [here](https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/MaxLengthAttribute.cs#L85):

      else if (value is IEnumerable enumerable)
      {
        var enumerator = enumerable.GetEnumerator();
        while (length <= Length && enumerator.MoveNext())
        {
          length++;
        }
      }

**Comment by weitzhandler** [comment]
@karelz I chose flat highlighting to be able to use the `<b>` tags to emphasize the operators 😉

**Comment by karelz** [comment]
Oh, I missed that - fixed it (remove the bold).
It is all code diff, it's not clear top me what the bold would mean. Do you want to call it out in text?

**Comment by weitzhandler** [comment]
I wanted to emphasize the difference between the top snippet of the bottom snippet, so I wanted to bold it out in the code snippet, I just don't know how to set language in <pre><code> in GitHub to enable syntax coloring as well.

**Comment by lajones** [comment]
@weitzhandler Are you creating .NET Core or .NET Framework for your results above? And what version?

**Comment by weitzhandler** [comment]
It doesn't matter, .NET Framework [only supports `Array`s](http://referencesource.microsoft.com/#System.ComponentModel.DataAnnotations/DataAnnotations/MinLengthAttribute.cs,54), while .NET Core [only supports `ICollection`s](https://source.dot.net/#System.ComponentModel.Annotations/System/ComponentModel/DataAnnotations/MinLengthAttribute.cs,71).

`ICollection<T>` and `IEnumerable<T>` are not supported in either, hence this suggestion.

**Comment by divega** [comment]
**DataAnnotations Triage:** We think that enabling `[MinLength]` and `[MaxLength]` on `ICollection<T>` is a reasonable request and we would consider a PR for it.

Note that the code necessary to invoke the `Count` property in an `ICollection<T>` for an unknown `T` can be tricky. We think it would be reasonable to fall back to using reflection and invoking a `Count` property getter.

Also, we don't think it is a good idea to open up this for `IEnumerable<T>` as not all `IEnumerable<T>` instances are countable.

**Comment by weitzhandler** [comment]
@divega did you see [my suggestion](https://github.com/dotnet/corefx/issues/23461#issuecomment-324176869) on `IEnumerable`?
In `IEnumerable`s, I'd like  iterate the collection to the necessary point to determine if validation succeeded/failed.

**Comment by divega** [comment]
@weitzhandler we saw the proposal for `IEnumerable`, but perhaps we didn't discuss it enough. 

You should use a `using` statement for the enumerator, but besides that, I don't see a problem with it.

@ajcvickers @lajones do you see a problem with this?

**Comment by weitzhandler** [comment]
@divega I'm using the non-generic enumerator, which does not implement `IDisposable`.

**Comment by divega** [comment]
@weitzhandler use `IEnumerable<object>` instead.

**Comment by weitzhandler** [comment]
I would, but can you please link a source on why? Should generic enumerable always be preferred when type unavailable? Asking just out of curiosity.

**Comment by weitzhandler** [comment]
@divega 
I will, but can you please link a source on why `IEnumerable<object>` over `IEnumerable`?
Is this a general practice in .NET? Asking just so I can expand my knowledge.
And bear in mind that that won't work for primitive non-generic types which aren't a generic `IEnumerable` by any means (for example `ArrayList`).

**Comment by divega** [comment]
It is just not safe to not dispose the enumerator: Many enumerables use resources that need to be disposed deterministically, e.g. think about database queries, not just in-memory collections.

You could always achieve this by adding a try/catch/finally and checking if the `IEnumerator` happens to be an `IDisposable` and then dispose it in the finally block. But using `IEnumerable<object>` and then assigning the `IEnumerator<object>` in a using block is much simpler, and seems adequate because:

- Your stated goal was from the beginning to support `IEnumerable<T>` and not any arbitrary `IEnumerable`
- Thanks to generic covariance all `IEnumerable<T>` can be assigned to `IEnumerable<object>`

**Comment by weitzhandler** [comment]
Actually to satisfy my curiosity I created this benchmark, and generic is indeed much faster:

    static void Main(string[] args)
    {
      var priSw = new Stopwatch();
      var genSw = new Stopwatch();
                            
      var list = new List<object>();
      for (int i = 0; i < 1000*1000; i++)
      {                             
        priSw.Start();
        var priEnumerator = ((IEnumerable)list).GetEnumerator();
        while (priEnumerator.MoveNext()) ;
        priSw.Stop();

        genSw.Start();
        using (var genEnumerator = list.GetEnumerator())
          while (priEnumerator.MoveNext()) ;
        genSw.Stop();

        Console.Write($"\r{i}");
      }

      Console.WriteLine($"Primitive: {priSw.Elapsed}");
      Console.WriteLine($"Generic: {genSw.Elapsed}");
      Console.ReadKey();
    }

Results:
Primitive: 00:00:00.1682750
Generic: 00:00:00.0403097

So for conclusion I want to add a check for `ICollection<T>` (using reflection), then `IEnumerable<object>`, and also for `IEnumerable` if it doesn't fall thru the generic one.
Will you accept a PR accomplishing this?

**Comment by ajcvickers** [comment]
@divega Still not in favor of doing this for enumerable. I don't think that the semantics align well enough, and I think that enumerating the collection could be both unexpected and potentially have side effects.

**Comment by divega** [comment]
@weitzhandler see @ajcvickers point on why not doing this for `IEnumerable<T>`. I also don't think there is necessarily a lot of value in it.

**Comment by weitzhandler** [comment]
OK so the verdict is to currently only support `ICollection<T>` and `ICollection`, is that right?

**Comment by weitzhandler** [comment]
@divega 
OK so the verdict is to currently only add support for `ICollection<T>` is that right? I agree that covers most common collections indeed.

**Comment by divega** [comment]
That seems right.

**Comment by weitzhandler** [comment]
See PR #23664.

**Comment by jamesqo** [comment]
For completeness' sake, should `IReadOnlyCollection<T>` be supported too? It also has a `Count` property but is independent of `ICollection` or `ICollection<T>`.

**Comment by weitzhandler** [comment]
@jamesqo Pity `ICollection<T>` doesn't inherit from `IReadOnlyCollection<T>`. See #23578 for the complete discussion on this painful `Count` property.
