### ISSUE TITLE
Some IO tests now fail with "The directory is not empty"

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23473]
When running the System.IO.FileSystem tests locally, I sporadically hit the following error on Windows 10:
```
System.IO.Tests.DirectoryInfo_Delete_bool.RecursiveDelete_DeepNesting [FAIL]
        System.IO.IOException : The directory is not empty
        Stack Trace:
           C:\Users\stoub\Source\Repos\corefx\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs(542,0): at Syst
  em.IO.Win32FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
           C:\Users\stoub\Source\Repos\corefx\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs(439,0): at Syst
  em.IO.Win32FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
           C:\Users\stoub\Source\Repos\corefx\src\System.IO.FileSystem\src\System\IO\DirectoryInfo.cs(431,0): at System
  .IO.DirectoryInfo.Delete(Boolean recursive)
           c:\Users\stoub\Source\Repos\corefx\src\System.IO.FileSystem\tests\DirectoryInfo\Delete.cs(40,0): at System.I
  O.Tests.DirectoryInfo_Delete_bool.Delete(String path, Boolean recursive)
           c:\Users\stoub\Source\Repos\corefx\src\System.IO.FileSystem\tests\Directory\Delete.cs(277,0): at System.IO.T
  ests.Directory_Delete_str_bool.RecursiveDelete_DeepNesting()
```

**Comment by Jiayili1** [comment]
failed again in UWP6.0 branch, detail: https://mc.dot.net/#/product/netcore/uwp60/source/official~2Fcorefx~2Frelease~2Fuwp6.0~2F/type/test~2Ffunctional~2Fuwp~2F/build/20170823.02/workItem/System.IO.FileSystem.Tests/analysis/xunit/System.IO.Tests.WinRT_BrokeredFunctions~2FCreateDirectory

**Comment by danmosemsft** [comment]
I don't think this will meet the 6.0 bar at this point. Moving to 2.1

**Comment by danmosemsft** [comment]
I just noticed it's consistent, and it's not just on the long path case. CreateDirectory, FindFirstFile, RemoveDirectory are all consistently failing -- but only through WinRT_BrokeredFunctions

https://mc.dot.net/#/product/netcore/uwp60/source/official~2Fcorefx~2Frelease~2Fuwp6.0~2F/type/test~2Ffunctional~2Fuwp~2F/build/20170824.01/workItem/System.IO.FileSystem.Tests

Quite possibly nothing to do with the topmost issue...
```
System.IO.IOException : The directory is not empty
Stack Trace :
   at System.IO.Win32FileSystem.RemoveDirectoryHelper(String fullPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Win32FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path)
   at System.IO.Tests.WinRT_BrokeredFunctions.CreateDirectory()
```

**Comment by Jiayili1** [comment]
failed again: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20170830.01/workItem/System.IO.FileSystem.Tests

**Comment by JeremyKuhne** [comment]
I've added a PR that allows for directory not empty if we successfully remove all files as there isn't a guarantee that all files will be removed within any specific timeframe- they are dependent on all handles being closed first. (Background tasks such as virus scanners, indexers, etc. can hold them open.)
