### ISSUE TITLE
Please introduce a reusable implementation of ILookup

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/corefx#23476]
Hi,

The [`Lookup`](https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Lookup.cs) class' constructor is `private`, and its `Create` methods are `internal`.
I'd like to request to make the `Create` methods in lookup public, and/or introduce a `public`/`protected` constructor to it, so we can benefit of having custom `Lookup` implementations.

Alternatively (preferable option), please provide a comprehensive solution to deal with mutable multi-value dictionaries (i.e. single key with multiple values).
The `MultiValueDictionary` in the [corefxlab](/dotnet/corefxlab) repo, implements `IReadOnlyDictionary`, which is immutable. I'd prefer a permanent editable multi-value dictionary.
Here's a shallow way of how I achieve this, but it'll only work if the keys are immutable (just like `KeyedCollection` itself will).

```
private abstract class Lookup<TKey, TElement> : KeyedCollection<TKey, ICollection<TElement>>
{
  protected override TKey GetKeyForItem(ICollection<TElement> item) =>
    item
    .Select(b => GetKeyForItem(b))
    .Distinct()
    .SingleOrDefault();

  protected abstract TKey GetKeyForItem(TElement item);

  public void Add(TElement item)
  {
    var key = GetKeyForItem(item);
    if (Dictionary != null && Dictionary.TryGetValue(key, out var collection))
      collection.Add(item);
    else
      Add(new List<TElement> { item });
  }

  public void Remove(TElement item)
  {
    var key = GetKeyForItem(item);
    if (Dictionary != null && Dictionary.TryGetValue(key, out var collection))
    {
      collection.Remove(item);
      if (collection.Count == 0)
        Remove(key);
    }
  }
}
```

**Comment by danmosemsft** [comment]
@weitzhandler hello, please format your proposal as per example linked here https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md

**Comment by weitzhandler** [comment]
@danmosemsft updated

**Comment by danmosemsft** [comment]
@weitzhandler please present the API in reference format similar to `Proposed API` inhttps://github.com/dotnet/corefx/issues/271. Also it's good to break out Motivation, and Potential Alternatives. In some cases Performance is also worth breaking out. You already have an Example of use which is good.
I know it's paperwork but it makes it much easier to formally review to have sections organized.

**Comment by danmosemsft** [comment]
You can copy/paste relevant part of https://github.com/dotnet/corefx/blob/master/src/System.Linq/ref/System.Linq.cs and add in your API.

**Comment by weitzhandler** [comment]
I guess that's a no. My motive was code reuse, rather than copy-pasting thing.
I'm gonna close this issue.
