### ISSUE TITLE
Add macOS 10.13 to CI options

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#23484]
@danmosemsft commented on [Tue Aug 08 2017](https://github.com/dotnet/core-eng/issues/1460)

Helix runs now include 10.13 (high sierra). Can we please add this an optional leg to Jenkins for corefx?

Ideally for release/1.x and 2.0 branches also.

---

@maririos commented on [Thu Aug 10 2017](https://github.com/dotnet/core-eng/issues/1460#issuecomment-321660036)

FYI @mmitche 

---

@mmitche commented on [Thu Aug 10 2017](https://github.com/dotnet/core-eng/issues/1460#issuecomment-321667673)

This is a product work item.  @danmosemsft ci.dot.net has 4 10.13 nodes.  They can be transferred to ci3.dot.net if needed (for pipeline support), but you should be good to add the legs in corefx.

---

@danmosemsft commented on [Thu Aug 10 2017](https://github.com/dotnet/core-eng/issues/1460#issuecomment-321668051)

OK. @tarekgh maybe you could add this CI support as part of your 10.13 work? We will want to port it into all the release branches.

---

@tarekgh commented on [Thu Aug 10 2017](https://github.com/dotnet/core-eng/issues/1460#issuecomment-321668810)

I'll look at that next week. is there any doc how I can do it? sorry I didn't do that before.

---

@mmitche commented on [Thu Aug 10 2017](https://github.com/dotnet/core-eng/issues/1460#issuecomment-321671970)

@tarekgh Here is the info on pipelines: https://github.com/dotnet/dotnet-ci/blob/dev/pipelinesupport/docs/CI-PIPELINES.md

The existing corefx jobs are declared here: https://github.com/dotnet/corefx/blob/master/buildpipeline/pipelinejobs.groovy.  The OSX jobs there call the osx.groovy file here: https://github.com/dotnet/corefx/blob/master/buildpipeline/osx.groovy

You probably just want to parameterize this script so that the target OS here: https://github.com/dotnet/corefx/blob/master/buildpipeline/osx.groovy#L11 is passed in as a parameter to the script, then alter pipelinejobs.groovy so that it differentiates between 10.12 and 10.13 and passes the appropriate OS name in there.  The rest of the build workflow will stay the same.

I'll ensure that there are available 10.13 machines connected to the right CI server tomorrow or early next week.

@weshaggard Any idea why we're not using Helix for the testing for OSX in CI?  I think you put together that testing.

---

@danmosemsft commented on [Thu Aug 10 2017](https://github.com/dotnet/core-eng/issues/1460#issuecomment-321672560)

BTW @Priya91 @wfurt @bartonjs do we yet know to our satisfcation that Apple supports building on one version of OSX and deploying on another? (As Windows generally does). For a while we were guessing that it might be causing segfaults, but that wasn't the case. It would be nice to know it's actually supported and we can continue to do all our building on 10.12.

---

@mmitche commented on [Thu Aug 10 2017](https://github.com/dotnet/core-eng/issues/1460#issuecomment-321673034)

#1483 for moving a couple machines over.

---

@weshaggard commented on [Thu Aug 10 2017](https://github.com/dotnet/core-eng/issues/1460#issuecomment-321679172)

>@weshaggard Any idea why we're not using Helix for the testing for OSX in CI? I think you put together that testing.

We don't want to build on 10.13 just test so as long as we have the necessary Open helix queue then we can add them. 

---

@mmitche commented on [Thu Aug 10 2017](https://github.com/dotnet/core-eng/issues/1460#issuecomment-321687380)

We're not submitting through Helix today though....any idea why?

---

@weshaggard commented on [Thu Aug 10 2017](https://github.com/dotnet/core-eng/issues/1460#issuecomment-321691249)

>We're not submitting through Helix today though....any idea why?

I don't think there is any reason beyond the queues weren't ready when I updated it last. We should definitely start doing it. 

---

@mmitche commented on [Tue Aug 22 2017](https://github.com/dotnet/core-eng/issues/1460#issuecomment-324111208)

This has been completed

---

@tarekgh commented on [Tue Aug 22 2017](https://github.com/dotnet/core-eng/issues/1460#issuecomment-324114406)

Thanks @mmitche. so there is no more actions needed from our side. right?

---

@mmitche commented on [Tue Aug 22 2017](https://github.com/dotnet/core-eng/issues/1460#issuecomment-324121653)

The machines are available in the CI pools, but the jobs will need to be reworked to build using them,.  That is something for the product team to do.

---

@tarekgh commented on [Tue Aug 22 2017](https://github.com/dotnet/core-eng/issues/1460#issuecomment-324132304)

Reopen the issue as we still need to do some work from our side.

---

@mmitche commented on [Tue Aug 22 2017](https://github.com/dotnet/core-eng/issues/1460#issuecomment-324134639)

@tarekgh I think this should go into the corefx/coreclr repos then.

---

@tarekgh commented on [Tue Aug 22 2017](https://github.com/dotnet/core-eng/issues/1460#issuecomment-324135248)

I didn't notice we are not on corefx :-) I'll move it there.

**Comment by wfurt** [comment]
Do we use new XCode and brew packages on 10.13 @tarekgh ?

**Comment by tarekgh** [comment]
> Do we use new XCode and brew packages on 10.13

I used your remote 10.13 machine and was able to build and run successfully. did you have a new XCode and brew version there? if not, then I wouldn't expect to have new packages there.

**Comment by bartonjs** [comment]
For the product releases we're building on 10.12 and executing on 10.13.  Hopefully that's what we're doing in CI until such a time as we change how we're doing the official builds.

**Comment by wfurt** [comment]
To @bartonjs  point: The box has updated Xcode and Brew to match 10.13. To build 10.13 specific version may be useful at some point but making sure 10.12 build runs well on both 10.12 and 10.13 is probably more important at this point.

**Comment by tarekgh** [comment]
This is done in the PR https://github.com/dotnet/corefx/pull/23831
