### ISSUE TITLE
Occasional hangs of threading tests on CI machines

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#23483]
Per https://github.com/dotnet/corefx/pull/23462#issuecomment-324078900 there is speculation this is related to them only having 2 CPU.

We should loop the tests on a 2 CPU machine and see whether they are just getting starved and never complete in a reasonable time. If that's the case we should either adjust the tests or the product.

Was in Suse:
https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/02a6e4efff40d87d98e92a4c8a5a0c8fb5ad1c96/workItem/System.Threading.Tasks.Tests/wilogs

**Comment by MattGal** [comment]
Just wanted to point out a thing, if you stand up an Azure D2_V2 VM with the OS you want (all linuxes except Fedora come from default azure images) you'll have nearly identical hardware to the ones that hang these tests you can SSH into to run tests on.

**Comment by danmosemsft** [comment]
Probably not going to do this now.
