### ISSUE TITLE
Where is System.Security.Cryptography.Xml?

### ISSUE THREAD

**Issue by adragoner** [dotnet/corefx#23502]
Apologies for a dumb question, but as far as I can see System.Security.Cryptography.Xml is a part of .net core 2.0 release. How comes it is not included in dependencies of .net core 2.0 project?

1. Installed .net Core 2.0 SDK
2. Installed .net Core 2.0 runtime
3. Created .net Core 2.0 console application in Visual Studio 2017 (15.3)

System.Security.Cryptography.Xml is nowhere to be found.

**Comment by karelz** [comment]
I don't remember if we shipped it as final - @krwq @weshaggard do you know?
If we did ship it, then it is likely a separate package.

**Comment by danmosemsft** [comment]
@adragoner it's not part of the main package -- please add a Nuget package reference to System.Security.Cryptography.Xml to your project.

We'd welcome any bug reports (as new issues) especially discrepancies from desktop behavior.

**Comment by danmosemsft** [comment]
BTW please close if this fixes it...

**Comment by krwq** [comment]
I have just quickly tested it with new .NET CLI.

Adding to my csproj:
```
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.Xml" Version="4.4.0" />
  </ItemGroup>
```

````
dotnet restore
dotnet run
```

restores and runs correctly. Closing.
