### ISSUE TITLE
Remove code under FEATURE_RANDOMIZED_STRING_HASHING from corefx

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#23515]
IIRC `string` does randomized hashing by default in .NET Core so the collections don't need to be modified to use a randomized equality comparer. [This code](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/HashSet.cs#L1249-L1253) doesn't even compile.

**Comment by ianhays** [comment]
going by @ellismg 's comment [here](https://github.com/dotnet/corefx/issues/1534#issuecomment-143086216), this code should be removed without worry.

**Comment by safern** [comment]
Fixed in #24178
