### ISSUE TITLE
[xUnit] [ERROR] - No test reports found for the metric 'xUnit.Net' with the resolved pattern 'bin/**/testResults.xml'. Configuration error?

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#23517]
[xUnit] [ERROR] - No test reports found for the metric 'xUnit.Net' with the resolved pattern 'bin/**/testResults.xml'. Configuration error?.

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/fedora24_debug/3681/consoleFull#126823694079494335-f7bd-47d0-8771-8661e00c2db2

Configuration: fedora24_debug

**Comment by Jiayili1** [comment]
closed issue: https://github.com/dotnet/corefx/issues/20772

**Comment by danmosemsft** [comment]
T his is actually a segfault during *build*
```
/mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/Tools/Microsoft.CSharp.Core.targets(67,5): error MSB6006: "/mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/Tools/dotnetcli/dotnet" exited with code 139. [/mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/src/System.Private.Xml/src/System.Private.Xml.csproj]
```

**Comment by danmosemsft** [comment]
@mellinoe is it feasible to have dumpling trigger when the build segfaults?

**Comment by mellinoe** [comment]
@danmosemsft Yikes, during build? I'm not sure -- seems like we couldn't do it in MSBuild, since that's what crashed... It'd have to be in the shell script or somewhere higher up.

**Comment by danmosemsft** [comment]
logs gone
