### ISSUE TITLE
Serialized Exception and AggregateException may not exchange successfully between CoreRT and CoreCLR

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#23520]
`AggregateException` has a field `_innerExceptions` in CoreRT but `m_innerExceptions` in CoreCLR. It does not implement ISerializable so I think it will not exchange correctly.

`Exception` does implement ISerializable and from eyeball it looks like the de/serialization will work although I notice CoreRT does not implement `ExceptionMethod` and `WatsonBuckets` and it does not set `RemoteStackTrace` even though CoreCLR needs that (it reads `StackTrace` but then nulls it out in `[OnDeserialized]`). Similarly `RemoteStackIndex`.

**Comment by danmosemsft** [comment]
Part of the problem is that we don't store a blob for E and AE in our tests:
```
        public static IEnumerable<object> SerializableExceptions_MemberData()
        {
            var exception = new Exception("Exception message", new Exception("Inner exception message"));
            yield return new object[] { new AggregateException("Aggregate exception message", exception) };
            yield return new object[] { exception };
        }
```

https://github.com/dotnet/coreclr/pull/13492#discussion_r134897870

**Comment by danmosemsft** [comment]
@ViktorHofer

**Comment by danmosemsft** [comment]
Remaining work is to enable the test once corert is ingested.

**Comment by joperezr** [comment]
@ViktorHofer just checking, did you re-enable the test?

**Comment by ViktorHofer** [comment]
Aaah yeah that's already finished quite a while :)
