### ISSUE TITLE
API Addition: Add generic Array.Reverse<T>

### ISSUE THREAD

**Issue by justinvp** [dotnet/corefx#2352]
Add generic `Array.Reverse<T>`.

## Rationale

[`Array.Reverse`](https://github.com/dotnet/coreclr/blob/ef1e2ab328087c61a6878c1e84f4fc5d710aebce/src/mscorlib/src/System/Array.cs#L1570-L1606) is non-generic. It includes a fast path for a known set of primitive types via a call into the runtime (see [`TrySZReverse`](https://github.com/dotnet/coreclr/blob/4cf8a6b082d9bb1789facd996d8265d3908757b2/src/classlibnative/bcltype/arrayhelpers.cpp#L390-L424)), otherwise it falls back to slower code paths that involve boxing for value types. This is a significant performance cost for non-primitive value types, ~22x slower.

Callers of `Array.Reverse` (like `List<T>.Reverse` and `ImmutableArray<T>.Builder.Reverse`) are affected by this performance issue. As a workaround, [`List<T>.Reverse`](https://github.com/dotnet/coreclr/pull/1231) and [`ImmutableArray<T>.Builder.Reverse`](https://github.com/dotnet/corefx/pull/2354) are being updated to not use the non-generic `Array.Reverse` method until the generic `Array.Reverse<T>` method becomes available.

Other non-generic methods on `Array` have generic counterparts like `Array.Sort` and `Array.Sort<T>`, so this would just be making `Reverse` consistent with those.

## Proposed API

```c#
public abstract class Array : ...
{
    // Proposed
    public static void Reverse<T>(T[] array);
    public static void Reverse<T>(T[] array, int index, int length);

    // Existing
    public static void Reverse(Array array);
    public static void Reverse(Array array, int index, int length);
}
```

**Comment by justinvp** [comment]
cc: @terrajobst

**Comment by whoisj** [comment]
I like it. :shipit:

**Comment by hackcraft** [comment]
How fast a path is the primitive fast-path?
Is it fast enough to make `if (TrySZReverse(array, index, length)) return;` worth adding to the generic form?
Is it fast enough to consider even adding (or coercing) other blittable types to work with it? I'm imagining it should work with value types that don't have fields that aren't either primitive or also such value types.

**Comment by hackcraft** [comment]
Actually, that should be `if (default(T) != null && TrySZReverse(array, index, length)) return;` so the jitter can consider all reference type attempts to be dead code and not jit the path that tries it for any of them.

**Comment by mikedn** [comment]
@hackcraft 
> How fast a path is the primitive fast-path?

Not very fast, I did a quick test in the related CoreCLR [PR](https://github.com/dotnet/coreclr/pull/1231). And for very small arrays `TrySZReverse` will always loose due to the cost of another call and dispatching to the correct native implementation.

**Comment by KrzysztofCwalina** [comment]
That would be a very nice addition. It's also a very simple API, and so I marked it "ready for API review" where we can discuss how to make this happen (mainly logistically).

**Comment by KrzysztofCwalina** [comment]
Assigned to @terrajobst to take it though the API review process.

**Comment by terrajobst** [comment]
I like the APIs as well.

@weshaggard, what are your thoughts? If there is no more pushback I'd mark it as `api-approved`.

**Comment by weshaggard** [comment]
I like the proposed API.

**Comment by justinvp** [comment]
https://github.com/dotnet/coreclr/pull/7132
https://github.com/dotnet/corert/pull/1842

This issue can now be tagged as "api-needs-exposed"
