### ISSUE TITLE
Please add bitwise shift operators to Enum

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/corefx#23524]
### Description 

In `[Flags]` annotated enums, I often want to move an enum property to the next value, something like the `++` operator, but for enum.

```
[Flags]
public enum DaysInWeek { Sunday = 1, Monday = 2, Tuesday = 4, Wednesday = 8 ..... }
public class Store
{
  DaysInWeek OpenDays { get; set; }
}
```

What I want, is to be able to move the property value to next day:

### Example usage

```
//initial value
store.OpenDays = DaysInWeek.Sunday;
//move next (check if smaller than sat)
store.OpenDays <<= 1;
```

### Current behavior

Currently it's achievable like this:

    store.OpenDays = (DaysInWeek)((int)store.OpenDays << 1);

My suggestion is to add `<<` and `>>` bitwise shift operators to `Enum`, so that we can benefit from this without casting.

### Notes
Maybe the `DaysInWeek` example I gave here isn't the right one to demonstrate the motive so well. Just imagine you have an enum that is in some cases supposed to be a single value and you want to advance to next value. And BTW, a multi-value enum will move to the next set of values (i.e. if it's set to `Sunday,Monday`, shifting by one will set it to `Monday,Tuesday`.
Additionally, `Enum` supports `integer` operations, and `++` or `--` is available for enums. I think it should be just natural to also enable the bitwise shift operators to complete the picture.

**Comment by svick** [comment]
I don't see how could adding the operators to `System.Enum` possibly work. On the other hand, doing this in the language makes sense to me, since that's how the existing operators on `enum`s work (i.e. there is no `operator +` on `Enum`, instead the C# compiler knows what IL to generate for the operation). Because of that, I think this proposal should be moved to [dotnet/csharplang](https://github.com/dotnet/csharplang).

**Comment by weitzhandler** [comment]
Yes, I just saw that the Enum class has no operators in the CLR level, it's the compiler, so yes, I'd love the compiler to take care of inline bitwise shift operations of `enum`s too.

**Comment by weitzhandler** [comment]
Migrated: https://github.com/dotnet/csharplang/issues/849
