### ISSUE TITLE
DllNotfound exception sni.dll

### ISSUE THREAD

**Issue by foxjazz** [dotnet/corefx#23534]
All I did was publish an asp.net 2.0 project up from 1.1.
using SqlConnection fails on open. 

An unhandled exception was thrown by the application. (560e7d32)
System.DllNotFoundException: Unable to load DLL 'sni.dll'

**Comment by danmosemsft** [comment]
@weshaggard can you help diagnose this one?

**Comment by weshaggard** [comment]
Likely need to update your package reference to System.Data.SqlClient to 4.4.0 as well.

**Comment by danmosemsft** [comment]
Is it necessary to do this manual edit when upgrading to 2.0 ? Feels like we need better docs on that maybe.
@terrajobst I assume you are tracking this one.

**Comment by weshaggard** [comment]
Most packages don't end up getting forced to be updated but SqlClient is definitely one that does because some of the types in the old package are now in the shared framework.

**Comment by saurabh500** [comment]
Closing as the fix was suggested above.
