### ISSUE TITLE
NETSTANDARD2_0 not support in .net framework project?

### ISSUE THREAD

**Issue by TimRowe** [dotnet/corefx#23551]
![qq 20170825220515](https://user-images.githubusercontent.com/5651857/29717447-c6b74b64-89e1-11e7-971a-865577006101.png)

Why the code can't reach ?  I use ASP.NET Core in .NET Framework 4.6.1.

**Comment by karelz** [comment]
I don't understand your bug report. What doesn't work?
BTW: If you have question about ASP.NET, then please use https://github.com/aspnet repos ...

**Comment by mellinoe** [comment]
@TimRowe You need to add that DefineConstant to your project file if you would like it to be active. Unless I missed some change to the defaults, then it won't be added automatically.

**Comment by tarekgh** [comment]
@TimRowe could you send more details from where the code you mentioned exists? I am seeing some asp.net code using such define but I couldn't find the exact code you sent.

**Comment by svick** [comment]
By default, .Net Core SDK defines constants that match exactly the target framework of your project. So, a .Net Standard 2.0 library defines `NETSTANDARD2_0` (but not also e.g. `NETSTANDARD1_3`). A .Net Framework 4.6.1 application defines `NET461`, but not `NETSTANDARD2_0`, even though .Net Framework 4.6.1 supports .Net Standard 2.0. This explains the behavior you see. If you want something different, you will have to define the constants yourself.

[Here is the documentation about this.](https://docs.microsoft.com/en-us/dotnet/standard/frameworks#how-to-specify-target-frameworks)

**Comment by tarekgh** [comment]
@TimRowe I am closing the issue but feel free to send any more questions here.

**Comment by TimRowe** [comment]
@tarekgh @svick @mellinoe, Thanks all. I raised the question because .Net Framework 4.6.1 supports .Net Standard 2.0, now i understand. So  NETSTANDARD2_0 will only match the  CORE APP 2.0 now？

**Comment by svick** [comment]
> So NETSTANDARD2_0 will only match the CORE APP 2.0 now?

No.

In a .Net Standard 2.0 project, the only constant that is defined by default is `NETSTANDARD2_0`.  
In a .Net Core 2.0 project, the only constant that is defined by default is `NETCOREAPP2_0`.

So `#if NETSTANDARD2_0` will not match in a .Net Core 2.0 app, only in a .Net Standard 2.0 library.

**Comment by tarekgh** [comment]
CC @weshaggard
