### ISSUE TITLE
/p:XunitOptions build option does not work properly on Unix

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#23568]
Run msbuild with a quoted /p:XunitOptions parameter on Unix, and it will fail because it's not properly handling the quoted parameter:

```
../../../Tools/msbuild.sh /t:RebuildAndTest /p:Outerloop=true "/p:XunitOptions=-showProgress -parallel none"
Microsoft (R) Build Engine version 15.1.523.56541
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1001: Unknown switch.
Switch: -parallel
```

This works on Windows.

I believe @wfurt knows how to fix this.

**Comment by mellinoe** [comment]
As a workaround, you can set it as an environment variable. We should fix this, though.

**Comment by wfurt** [comment]
do you have example @mellinoe ? I searched developer-guide.md and I did not find any hint. 
The true fix is quite simple but has some risk associated with CI runs.

**Comment by mellinoe** [comment]
Instead of 

```
../../../Tools/msbuild.sh /t:RebuildAndTest /p:Outerloop=true "/p:XunitOptions=-showProgress -parallel none"
```
Use:
```
XunitOptions="-showProgress -parallel none" ../../../Tools/msbuild.sh /t:RebuildAndTest /p:Outerloop=true
```

**Comment by weshaggard** [comment]
Closing as a dup of https://github.com/dotnet/corefx/issues/23360
