### ISSUE TITLE
Clean up or pragma disable warnings 0169, 0414, and 0649 in Microsoft.XmlSerializer.Generator.csproj

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#23560]
See https://github.com/dotnet/corefx/commit/84c6a81f7d1343a038850c6aa6286bd50f210a29#diff-47a9f2bd971e727d7993cdfad3d33f58R13

The new build of roslyn started catching unused fields.  Microsoft.XmlSerializer.Generator.csproj had too many for me to fix.  Please remove the warnings and either fix these by deleting the unused fields, or pragma disable and add a comment about how they are used if accessed through reflection or kept for serialization (for example).

**Comment by krwq** [comment]
cc: @shmao
