### ISSUE TITLE
Want a turnkey way to build the product without building the tests.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#2357]
The top level "build.cmd" could really use an option to build the product without building the tests.

(Yes, I've already created a local workaround which consisted of plagiarizing the src\dirs.proj file and deleting the "&lt;Project Include="\*\test\\*\*\\*.csproj"..&gt;" lines in my private copy. But this is pretty  unbecoming as a workaround.)

**Comment by stephentoub** [comment]
@AtsushiKan, I'm just curious, why do you want to avoid building the tests (separate from avoiding running the tests, which you can do with ```/p:SkipTests=true```)?  For me personally, I typically only do ```build.cmd``` or ```build.cmd /p:SkipTests=true``` from the root of my enlistment when I want to build everything, because I'm checking for accidental breaks I may have introduced and the like.  In my normal workflow, though, I'm rarely building everything, instead just building an individual project (```msbuild``` from the relevant csproj or sln directory) or building and running the tests for just that project (```msbuild /t:RebuildAndTest``` from the project's tests directory).

**Comment by AtsushiKan** [comment]
I have two use-cases for build.cmd:

  1. Regression test after working on feature and before pushing to PR (want to build and run tests.)

  2. Rebuild the full corefx stack <i>before</i> working on feature, or after pulling down upstream commits (building and running tests not useful and is unneeded overhead.) Payoff: full source-level debugging and locally tweakable binaries for the entire stack (not just one assembly) while writing code.

My ask is to support scenario 2 in a nice, well documented way as it's a very natural part of my workflow.

Note that I've opened a parallel issue for this (https://github.com/dotnet/coreclr/issues/1240) against CoreClr since I like to have locally built coreclr and mscorlib as well. If we do add a switch to build.cmd, it'd be nice to have this uniformly named across our dotnet repositories.

**Comment by akoeplinger** [comment]
@AtsushiKan just curious as well: how much less time does not building the tests on your machine take? For me, not running the tests with /p:SkipTests=true saves the most time vs. building them which is usually really since most of them are cached.

**Comment by AtsushiKan** [comment]
@akoeplinger : 

    Without building tests:                     45 seconds
    With building (not running) tests:           2 minutes

(Both run after deleting the bin directory - I've been burned enough times that I only trust incremental builds for my own changes - and sometimes, not even then.)

So that's a 2.6x difference.

Also, I'd expect the ratio to rise over time. It'd be worrying if we were adding product code at a faster rate than our test code.

**Comment by akoeplinger** [comment]
@AtsushiKan ok thanks, I agree this is quite a noticeable difference and a separate switch might be a good idea :)

**Comment by jasonwilliams200OK** [comment]
A switch `skiptestbuild` has been proposed in CoreCLR build script via https://github.com/dotnet/coreclr/pull/1247.
