### ISSUE TITLE
HttpUtility.ParseQueryString incorrect if first item's name begins with a question mark

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#23574]
If a query-string's first name-value pair begins with a question mark then the initial question mark is stripped twice, so the name in the parsed collection is incorrect.

E.g. with `??name=value&x=y` the result is a collection where `["name"] == "value"` while if it isn't the first element, as in `?x=y&?name=value` then it has the correct result of `["?name"] == "value"`

**Comment by JonHanna** [comment]
This seems to be related to #23582

**Comment by JonHanna** [comment]
This issue doesn't happen with netfx, so this has compatibility implications.

**Comment by karelz** [comment]
@davidsh can you please run it by AppCompat?
We should also get 2.0.x approval, then we can check it into 2.1. If we don't get 2.0.x servicing approval ...

**Comment by karelz** [comment]
OK, doing compat discussion here: @ericstj @stephentoub @terrajobst @Petermarcu @danmosemsft  @weshaggard -- this is breaking change we introduced in 2.0 against Desktop, related to #23582.

The API is new in .NET Core 2.0: https://apisof.net/catalog/System.Web.HttpUtility.ParseQueryString(String)
It is part of .NET Framework 2.0+ and also part of .NET Standard 2.0.
Telemetry shows 2.25% usage from API Port telemetry (non-trivial). 1.25% usage on nuget.org.

Questions:
* Should we fix it in 2.1 to match Desktop? (area owners recommendation: Yes)
* Should we (proactively) fix it in 2.0.x servicing, or wait for more reports first?
    * This one seems to be less severe than #23582 - I can imagine both answers, either bundling it with #23582 or waiting for additional feedback. Personally I would choose to bundle it with #23582.

**Comment by Petermarcu** [comment]
If we're intending to break in 2.1, I'd rather get things to the right behavior as soon as possible. Can we kick off the 2.0.X discussion?

**Comment by karelz** [comment]
@Petermarcu I meant to kick off the discussion here. We do not have compat alias.
Or did you mean kick off .NET Core Shiproom discussion?

**Comment by Petermarcu** [comment]
Shiproom where we can also discuss compat.

**Comment by danmosemsft** [comment]
@karelz do we plan for 2.0.2?

**Comment by karelz** [comment]
Reopening to track porting to release/2.0.0 branch.

**Comment by karelz** [comment]
2.0.x branch fixed in PR #23918.
