### ISSUE TITLE
IList<T>.Swap  not Supported ?

### ISSUE THREAD

**Issue by maogo** [dotnet/corefx#23575]

**Comment by JonHanna** [comment]
There is no `IList<T>.Swap`. Adding it would be a breaking change (removing it if there had been one would too). Are you perhaps used to working with a library that provided a `Swap` method?

**Comment by maogo** [comment]
@JonHanna Yes ，i feel very useful

**Comment by jnm2** [comment]
Does this achieve what you're after?

```c#
public static void Swap<T>(this IList<T> list, int index1, int index2)
{
    if (list == null) throw new ArgumentNullException(nameof(list));
    var temp = list[index1];
    list[index1] = list[index2];
    list[index2] = temp;
}
```

**Comment by maogo** [comment]
@jnm2   no thanks

**Comment by jnm2** [comment]
Just curious, what does the extension method not do that you were hoping for?
