### ISSUE TITLE
Enumerable.Generate

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/corefx#23583]
### Description

`Enumerable.Repeat`, when used with a reference type, will generate an iteration of the specified count with reference sharing the same object. For example `Enumerable.Repeat(new Contact(), 10) will generate a single `Contact` and an iterator of 10 references to that single object.

My suggestion is hereby to please introduce a new method in the `Enumerable` class, that generates a number of instances according to the desired one.

### Suggestion

Please implement one of the following options:

- Introduce a new method in the `Enumerable` class that generates a separate new reference type for each iteration
- Add a new overload with a flag that specifies whether to activate a new one for each iteration or reuse them
- Add a new overload that takes an `Action<TResult>` that uses as an activation action, and is called upon each iteration
- One of the above plus an `Action<int, TResult>` where `int` is the current index.

What I'm looking for is simply a shorthand for:

    Enumerable.Range(0, count).Select(i => new Contact { Id = i });

Looks like there is a demand for it, see [this](https://stackoverflow.com/questions/17865166/creating-a-list-filled-with-new-instances-of-an-object) and [this](https://stackoverflow.com/questions/13553022/how-can-i-use-linq-to-initialize-an-array-of-repeated-elements))

Additionally, as a syntactic sugar, please make an overload of `Enumerable.Repeat` without the [first argument](https://source.dot.net/#System.Linq/System/Linq/Repeat.cs,12), (instead, perhaps and the `where TResult: new()` constraint), and when called activate a new element of TResult without having to specify it.

Related: #5078, #13909.

**Comment by weitzhandler** [comment]
Dupe of #5078.

**Comment by weitzhandler** [comment]
@karelz [Reopened](https://github.com/dotnet/corefx/issues/3093#issuecomment-325413845).

**Comment by jnm2** [comment]
I'm struggling to come up with a scenario where I could see myself using it. Do you have some real-world examples to share?

**Comment by weitzhandler** [comment]
```
[Post]
public Task GeneratePeople(int incidentId, int numberOfInvolvedPeople)
{
    ...
    //the poster has no info on the people, only the number of people to be generated.
    foreach(var person in Enumerable.Generate(new Person { IncidentId = incidentId }, numberOfInvolvedPeople);
      DbContext.InvolvedPeople.Add(person);
    ...
}
```

**Comment by karelz** [comment]
Personally I don't find the usage to be so common to warrant an API. If there are 5+ upvotes on the API, I'll happily adjust my view of the world.

Moreover, I don't think it can be much shorter than `Enumerable.Range(0, count).Select(i => new Contact { Id = i })` -- at best it would be IMO `Enumerable.Generate(i => new Contact { Id = i }, count)`.

I am also not thrilled by tying it to `int` as indexer and by hardcoding 0 as lower bound.

**Comment by weitzhandler** [comment]
@karelz 
What's really the use case of `Repeat`?

**Comment by OmarTawfik** [comment]
cc @karelz

**Comment by karelz** [comment]
I don't know what the original purpose of the API was. I can only guess. I am not sure if we would add it today if it didn't exist yet.
I don't see the point in discussing use case for `Repeat` here. The API exists and does what it does.

Given that we didn't see a single upvote in last 5 months, I would recommend to close the API suggestion. We can reopen later if other folks ask about it.
@weitzhandler are you ok with that?

**Comment by weitzhandler** [comment]
I guess no votes speaks for itself. Will reopen on demand.
