### ISSUE TITLE
System.Text.Encodings.Web.Tests ForbidRange test failed on macOS in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23585]
https://ci3.dot.net/job/dotnet_corefx/job/master/job/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/2743/consoleText
```
Microsoft.Framework.WebEncoders.TextEncoderSettingsTests.ForbidRange [FAIL]
        Assert.Equal() Failure
        Expected: True
        Actual:   False
        Stack Trace:
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Text.Encodings.Web/tests/TextEncoderSettingsTests.cs(277,0): at Microsoft.Framework.WebEncoders.TextEncoderSettingsTests.ForbidRange()
```

**Comment by tarekgh** [comment]
@stephentoub is this blocking porting new coreclr package to corefx?

**Comment by stephentoub** [comment]
> is this blocking porting new coreclr package to corefx?

There are a bunch of tests deterministically failing in that PR.  I don't believe this is one of them.  It failed at least once, but I've not reviewed the failures each time the PR has been auto-updated to see whether it's failed more than once.

**Comment by jkotas** [comment]
The failures suggest that there may be GC hole bug in the CoreCLR update. If it is the case, a lot of different tests can be failing intermittently.

**Comment by tarekgh** [comment]
Looks @jkotas is right. looking at the current OSX results 

https://ci3.dot.net/job/dotnet_corefx/job/master/job/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/2771/consoleText

I am not seeing this test is failing. Also, I have reviewed the failed test and the product code and I am not seeing how this can fail. and if it does, it should fail consistently and on all platforms.

I am going to close this one and I am CC'ing @swgillespie if want to take a deeper look or track it.
