### ISSUE TITLE
[ADO.NET] Support changeUser for DbConnection

### ISSUE THREAD

**Issue by yukozh** [dotnet/corefx#23597]
https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/src/System/Data/IDbConnection.cs

Since we have supported change database, why not add change user support? This will be useful when develop an EF Core provider in change into master connection scenario.

The php has already supoorted change user in mysqli: http://php.net/manual/en/mysqli.change-user.php

**Comment by divega** [comment]
*System.Data Triage:* There seems to be little value in this. And there are other reasons not to do it:
1. Currently the concept of a user doesn't seem to even exist in the base classes of ADO.NET
2. It seems that right now you can do this modifying the connection string (with a provider specific DbConnectionStringBuilder or manually) and creating a new provider specific DbConnection object with the new connection. 
3. In most database providers we know about, changing the user after the connection is open will require closing the connection and opening it again.
4. @yukozh Above mentions that this could be useful to change to master, e.g. to check for database existence or delete other databases, however that doesn't seem to be the case. Either the existing ChangeDatabase method or being able to clone the connection and change the user (however that doesn't work and that is why EF Core providers need to implement this themselves).

Closing for now, but feel free to comment or create new issue if you disagree.
