### ISSUE TITLE
System.Text.Encodings.Web.TextEncoder throws NRE on constructing copy

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#23600]
```C#
TextEncoder copyFrom = null;
TextEncoder copy = new TextEncoder(copyFrom); // Throws NullReferenceException
```

Should really throw `ArgumentNullException`.

**Comment by karelz** [comment]
Does it throw `ArgumentNullException` on Desktop? Compat with Desktop might be a good reason to fix it, otherwise I have hard time to convince myself it is worth the compat risk with .NET Core 2.0.
