### ISSUE TITLE
error PRI210: 0x80070020 from UWP CI

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#23614]
See https://github.com/dotnet/corefx/pull/23611#issuecomment-325437628

It seems that when building UWP tests there is a race condition when building the pri file.

I suspect two projects get in MakeCommonResourcesPriFile because the output doesn't exist yet, then they fight over writing the file.

**Comment by ericstj** [comment]
@safern I see multiple PRs hitting this.  I think you'll need to take a look ASAP.

**Comment by safern** [comment]
> @safern I see multiple PRs hitting this. I think you'll need to take a look ASAP.

Taking a look now.

**Comment by ericstj** [comment]
Still being hit, despite my workaround.  I found another test referencing src that could be triggering it.  FYI @tarekgh root cause is https://github.com/dotnet/corefx/issues/23618 that caused this regression.

**Comment by ericstj** [comment]
This commit brought back the regression.  https://github.com/dotnet/corefx/pull/23612

It renamed a CSProj and that CSProj had a projectreference to src from a test.

**Comment by tarekgh** [comment]
> Still being hit, despite my workaround. I found another test referencing src that could be triggering it. FYI @tarekgh root cause is #23618 that caused this regression.

@ericstj is this blocking issue now? I mean should we give it a high priority? or you have work around till we fix it?

**Comment by ericstj** [comment]
I'm playing wack-a-mole with the workarounds.  I would consider this blocking.  It has other side-effects just on incremental build of the src projects that I expect folks will start noticing.  Please fix the root-cause issue #23618.

**Comment by weshaggard** [comment]
Looks like it was fixed as part of https://github.com/dotnet/corefx/issues/23618.
