### ISSUE TITLE
Mac 不能安装sdk2.0

### ISSUE THREAD

**Issue by Hareis** [dotnet/corefx#23627]
我的mac系统版本是11.6 安装sdk出现提醒：只能安装在10.12以后版本 这是为什么呢

**Comment by karelz** [comment]
@Hareis can you please state your question in English? Automatic translators didn't quite help :(

**Comment by karelz** [comment]
Also note that Mac 10.12 is the minimal required for .NET Core 2.0 - see [2.0 supported OS versions](https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0-supported-os.md#macos)

**Comment by fubar-coder** [comment]
The bing translator provides a slightly better translation:

My Mac system version is 11.6 Install SDK appears reminder: can only be installed after 10.12 version what is this?

IOW: He tries to install on macOS 11.6 and the installer complains that it can only be installed on 10.12 or later.

**Comment by tarekgh** [comment]
Issue moved to [dotnet/sdk #1549](https://github.com/dotnet/sdk/issues/1549) via [**ZenHub**](https://www.zenhub.com/)

**Comment by karelz** [comment]
FYI:
I assume that refers to 10.11.6 - El Captain macOS version: http://apple.wikia.com/wiki/OS_X_10.11.6

That macOS version is sadly not supported - we need 10.12 at minimum due to dependencies on new crypto APIs in macOS -- it is dupe of #23389
