### ISSUE TITLE
IPAddress.Parse incorrectly parsing invalid IPv6 addresses

### ISSUE THREAD

**Issue by joseph-newton** [dotnet/corefx#23639]
Prior to upgrading to .NET Core 2.0, this would throw a FormatException (note the extra character in the final hextet):

    IPAddress.Parse("3fff:ffff:ffff:ffff:ffff:ffff:ffff:abcde");

Following the upgrade, the code above parses as if the first character were not there i.e as equivalent to:

    IPAddress.Parse("3fff:ffff:ffff:ffff:ffff:ffff:ffff:bcde");

Additional characters in any of the first seven hextets do still cause the expected FormatException to be thrown:

    IPAddress.Parse("3fff:ffff:ffff:ffff:ffff:ffff:affff:ffff");

Is this an intentional change of behavior from NetCoreApp1.1 and Net461?

**Comment by danmosemsft** [comment]
@joseph-newton what version do you have that this works on? It fails for me on 1.1.1-servicing-005133 also. At a glance the code has not changed.

**Comment by joseph-newton** [comment]
The expected (FormatException throwing) behavior occurs with version 1.1.2 build c7e321e6ef7272cebfbfebe37fbb47cb023a6270.

**Comment by danmosemsft** [comment]
Ah yes - I was mistaken in the version I was using.

**Comment by stephentoub** [comment]
It looks like I inadvertently broke that case in https://github.com/dotnet/corefx/commit/187c7c0066e6f9312562ae730ebb75da336274ae as part of fixing other cases.  I'll submit a fix for it.

**Comment by karelz** [comment]
Reopening to track port to 2.0.x as it is a regression we introduced.

@Petermarcu do you agree?

**Comment by Petermarcu** [comment]
Yes, lets have a servicing discussion about it.

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/pull/23744

**Comment by danmosemsft** [comment]
@stephentoub I guess you can close now
