### ISSUE TITLE
Runtime error with [OnDeserialized] in netstandard2.0 library running in framework461 project

### ISSUE THREAD

**Issue by Mardoxx** [dotnet/corefx#23645]
1. Create new Project
1. Create net461 app (A)
1. Create netstandard2.0 class library with the below code (B)
1. Reference (B) in (A)
1. Try and compile

```cs
using System;
using System.Runtime.Serialization;

namespace ClassLibraryNetStandard20
{
    [Serializable]
    public class SerializableClass : ISerializable
    {
        private readonly string _value;

        public SerializableClass(string value)
        {
            _value = value;
        }

        public SerializableClass(SerializationInfo info, StreamingContext context)
        {
            _value = info.GetString(nameof(Value));
        }

        public string Value => _value;

        public void GetObjectData(SerializationInfo info, StreamingContext context)
        {
            info.AddValue(nameof(Value), _value);
        }

        [OnDeserialized]
        private void OnDeserialized(StreamingContext context)
        {
        }
    }
}
```

Runtime error of:

> Type 'ClassLibraryNetStandard20.SerializableClass' in assembly 'ClassLibraryNetStandard20, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' has method 'OnDeserialized' with an incorrect signature for the serialization attribute that it is decorated with.

------

N.B. this works fine if (B) targets net461

**Comment by ViktorHofer** [comment]
I will look into this. I haven't yet fully understand what is happening here.

My guess is that the OnDeserialized attribute of .NET Standard 2.0 and .NET 4.6.1 doesn't match (type-forward).

cc @ericstj for type forwarding from netstandard2.0 to net461

**Comment by Mardoxx** [comment]
Thanks!

I have no clue whatsoever, but this was my (uneducated) guess. It's looking
for the wrong `StreamingContext` class.

May be worth noting that there are no external libraries referenced. The
netstandard2.0 csproj has just the directive to set the target framework.


On 29 Aug 2017 6:44 pm, "Viktor Hofer" <notifications@github.com> wrote:

I will look into this. I haven't yet fully understand what is happening
here.

My guess is that the OnDeserialized attribute of .NET Standard 2.0 and .NET
4.6.1 doesn't match (type-forward).

cc @ericstj <https://github.com/ericstj> for type forwarding from
netstandard2.0 to net461

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dotnet/corefx/issues/23645#issuecomment-325740472>, or mute
the thread

**Comment by ericstj** [comment]
What version of the tooling are you using?  In this case I would expect application A to get a netstandard.dll in its output directory that should redirect StreamingContext from netstandard.dll to mscorlib.  This requires the VS 2017 15.3 update in order to work correctly.  /cc @weshaggard

**Comment by Mardoxx** [comment]
@ericstj VS 2017 15.3.2. Just seen there is 15.3.3, I shall update and report back.

Need any further info?

**Comment by ViktorHofer** [comment]
We are right now chatting offline and working on it. Thanks Mardoxx.

**Comment by weshaggard** [comment]
It sounds like you are hitting a known issue https://github.com/dotnet/standard/issues/300. There is a bug in the .NET Framework that needs to be fixed to address this.

**Comment by Mardoxx** [comment]
Wow, thanks -- very quick! May close this if you like.

Any idea on ETA?

**Comment by ViktorHofer** [comment]
cc @danmosemsft

**Comment by ViktorHofer** [comment]
@Mardoxx we maybe have a workaround for it. I will link to it later.

**Comment by karelz** [comment]
Given that it does not affect .NET Core, let's move the discussion into the dupe https://github.com/dotnet/standard/issues/300
