### ISSUE TITLE
Wrong text encoding on console apps

### ISSUE THREAD

**Issue by ahumeniy** [dotnet/corefx#23643]
I have a console app made in dotnet core which, among other things, receive text input using Console.ReadLine. This works fine except when entering words using non english characters (áéíóúñ) I can write such text without problem using Console.WriteLine and debugging I can see the text received have the usual marker for invalid character.

This is happening in dotnet core 1.1.0

**Comment by joperezr** [comment]
@ahumeniy thanks for reporting this, quick question, have you tried using .NET Core 2.0 and see if it fails there as well? I suspect that it would be easier to include this fix on the next version of the framework as I'm not sure it would meet a bar for servicing.

**Comment by beyazc** [comment]
I have tested this with .net core 2.0 and .net fw 4.6.1 both successfully can readline and writeline successfully:
My code was as beloe for both .net core and .net 4.6.1
`            while (true)
            {
                string read = Console.ReadLine();
                Console.WriteLine(read);
            }
`
Both produced following 
```
a
a
á
á

```

therefore i think this issue can be closed

**Comment by joperezr** [comment]
great to hear and thanks so much for checking @beyazc!
