### ISSUE TITLE
Replace span-based optional arguments with fixed overloads

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23642]
When I outlined what span-based {Try}Parse methods I thought we should have on primitive types (int, long, etc.), I tried to keep the list of overloads short by using optional parameters.  For example, Int32 has these string-based Parse methods:
```C#
public static int Parse(string s);
public static int Parse(string s, NumberStyles style);
public static int Parse(string s, NumberStyles style, IFormatProvider provider);
public static int Parse(string s, IFormatProvider provider);
```
and I suggested (and we agreed on and we now have) adding just one span-based one to cover them all:
```C#
public static int Parse(ReadOnlySpan<char> s, NumberStyles style = NumberStyles.Integer, IFormatProvider provider = null);
```
For the most part, that’s seemed to work well, in terms of the experience I’ve had then consuming this in other code.

However, it’s worked less well in my experience for TryParse.   For TryParse, Int32 has:
```C#
public static bool TryParse(string s, out int result);
public static bool TryParse(string s, NumberStyles style, IFormatProvider provider, out int result);
```
and we’ve now added:
```C#
public static bool TryParse(ReadOnlySpan<char> s, out int result, NumberStyles style = NumberStyles.Integer, IFormatProvider provider = null);
```
The problem is in the order of the arguments.  Because the optional parameters need to come at the end of the signature, the `out int result` argument is now in the middle, differing from the corresponding long overload that works with a string.  When converting code from being string-based to span-based, for me at least this has been jarring and hasn’t been a pit of success.

For example, let’s say you’ve got code like this:
https://github.com/dotnet/corefx/blob/master/src/Common/src/Interop/Linux/procfs/Interop.ProcFsStat.cs#L133-L138
```C#
string startingString = s.Substring(start, pos);
if (long.TryParse(startingString, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out startingAddress))
{
    string endingString = s.Substring(pos + 1, end - (pos + 1));
    long.TryParse(endingString, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out endingAddress);
}
```
It’s pretty straightforward to replace the `.Substring` with `.AsReadOnlySpan().Slice`:
```C#
ReadOnlySpan<char> startingString = s.AsReadOnlySpan().Slice(start, pos);
if (long.TryParse(startingString, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out startingAddress))
{
    ReadOnlySpan<char> endingString = s.AsReadOnlySpan().Slice(pos + 1, end - (pos + 1));
    long.TryParse(endingString, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out endingAddress);
}
```
but then that doesn’t compile because the arguments are in the wrong order, and the developer needs to realize the problem and take the extra step of changing the code to be:
```C#
ReadOnlySpan<char> startingString = s.AsReadOnlySpan().Slice(start, pos);
if (long.TryParse(startingString, out startingAddress, NumberStyles.HexNumber, CultureInfo.InvariantCulture))
{
    ReadOnlySpan<char> endingString = s.AsReadOnlySpan().Slice(pos + 1, end - (pos + 1));
    long.TryParse(endingString, out endingAddress, NumberStyles.HexNumber, CultureInfo.InvariantCulture);
}
```

We should back away from the optional parameters here for TryParse, and add the same set of overloads as we have for strings.  In most cases, it should mean adding only one or two more methods.

**Comment by justinvp** [comment]
+1 I'm glad you opened this, as I've found the order difference jarring as well when switching between string-based and span-based TryParse. Thanks!

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/corefx/pull/25076 (https://github.com/dotnet/corefx/pull/25179)
