### ISSUE TITLE
System.ServiceModel.BasicHttpBinding throwing InvalidOperationException in dotnet core 2.0

### ISSUE THREAD

**Issue by mtf30rob** [dotnet/corefx#23646]
I am getting an invalid operation exception calling an external web service when setting the proxy settings on the BasicHttpBinding class. The error is: 

When using a non-null Proxy, the WindowsProxyUsePolicy property must be set to WindowsProxyUsePolicy.UseCustomProxy. (Source: System.Net.Http.WinHttpHandler)

My code:
```c#
var binder1 = new BasicHttpBinding();
binder1.UseDefaultWebProxy = false;
binder1.ProxyAddress = proxyAddress;
```

Removing these two lines (so it uses the machines default proxy settings) results in a successful web service call. From Dudod's comments in https://github.com/dotnet/wcf/issues/1592 it seems it may be related to the WinHttpHandler implementation.

I'm using Visual Studio 2017 version 15.3.0, my dll is targeting netstandard2.0 and I am using version 2.0.0 of the sdk. I'm testing this code using xunit tests targeting netcoreapp2.0. 

FYI if I switch the unit test target from netcoreapp2.0 to net461 the above code works.

[EDIT[ Fix C# syntax highlighting by @karelz

**Comment by mtf30rob** [comment]
After a bit more testing removing the binder1.UseDefaultWebProxy = false line fixes the issue when targeting netcoreapp2.0. However it breaks when targeting net461 with the following error: 

You cannot specify an explicit Proxy Address as well as UseDefaultWebProxy=true in your HTTP Transport Binding Element.

**Comment by karelz** [comment]
Any chance to get a repro for Networking without WCF magic? cc @mconnew

**Comment by mtf30rob** [comment]
I would say it is less magic and more cheating! I am working with a client’s codebase so would be unable to provide the exact example but have created a simple mockup here:
https://github.com/mtf30rob/BasicHttpBindingSample

The steps I have taken are:
1.	Create a service reference in a full framework project.
2.	Manually copy the Reference.cs to a dot net standard 2.0 dll 
3.	Reference the dot net standard dll in a dot net core 2.0 app

To test just run the DotNetCoreApp console application and you should get the error.

**Comment by davidsh** [comment]
>When using a non-null Proxy, the WindowsProxyUsePolicy property must be set to WindowsProxyUsePolicy.UseCustomProxy. (Source: System.Net.Http.WinHttpHandler)

This error is BY-DESIGN.

It sounds like WCF is calling WinHttpHandler incorrectly.

**Comment by karelz** [comment]
@mtf30rob can you please bring the discussion back to WCF repo?
If there is Networking problem under the hood, it would be best to provide a repro WITHOUT WCF to demonstrate it. Thanks!

**Comment by mtf30rob** [comment]
Crated new issue in wcf repo as requested: https://github.com/dotnet/wcf/issues/2261

**Comment by mconnew** [comment]
@karelz, while WCF should be explicit in setting the UseProxy property, I believe this is an `HttpClient` issue. If you look at [`HttpHandlerDefaults.DefaultUseProxy`](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Net/Http/HttpHandlerDefaults.cs#L20) you can see that the default is intended to be enabled. If you look at how `CurlHandler` is initialized, it [sets the initial value of `_useProxy`](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.cs#L136) to `HttpHandlerDefault.DefaultUseProxy`. If you look at the `ManagedHandler` implementation, it defers to the class `HttpConnectionSettings` which [initializes  `_useProxy`](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnectionSettings.cs#L20) to `HttpHandlerDefault.DefaultUseProxy`. So the default value of HttpClientHandler.UseProxy is true when using unix, when using Windows with the ManagedHandler and the value of HttpHandlerDefaults.DefaultUseProxy is true. WCF simply sets the Proxy property of HttpClientHandler to whatever has been specified. If HttpClientHandler using WinHttpHandler was using the declared default and matched all other platforms, this wouldn't be a problem.

**Comment by mconnew** [comment]
To be clear, WCF isn't directly using WinHttpHandler but is instead using HttpClientHandler.

**Comment by mconnew** [comment]
I missed that WinHttpHandler sets the *property* and not the field for the default UseProxy. This is a bug in WCF so closing again.

**Comment by freerider7777** [comment]
Updating to current versions of packages fixed the bug for me
