### ISSUE TITLE
Blocking: Package restore failing with nuget errors.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#23654]
As of this morning, any attempt to "sync -p" (master branch, synced to current bits, "git clean -xdf" done), aborts with this set of error messages (which seems to me like they should be warnings.)

```
c:\dd\CoreFx\external\test-runtime\XUnit.Runtime.depproj : error NU1603: Microsoft.xunit.netcore.extensions 1.0.1-prerelease-01911-02 depends on System.Linq.Expressions (>= 4.0.11) but System.Linq.Expressions 4.0.11 was not found. An
approximate best match of System.Linq.Expressions 4.1.0 was resolved.

c:\dd\CoreFx\external\test-runtime\XUnit.Runtime.depproj : error NU1603: Microsoft.xunit.netcore.extensions 1.0.1-prerelease-01911-02 depends on System.Text.RegularExpressions (>= 4.0.12) but System.Text.RegularExpressions 4.0.12 was
not found. An approximate best match of System.Text.RegularExpressions 4.1.0 was resolved.

c:\dd\CoreFx\external\test-runtime\XUnit.Runtime.depproj : error NU1603: xunit.console.netcore 1.0.3-prerelease-00921-01 depends on System.Text.RegularExpressions (>= 4.0.12) but System.Text.RegularExpressions 4.0.12 was not found. An
 approximate best match of System.Text.RegularExpressions 4.1.0 was resolved.

c:\dd\CoreFx\Tools\packageresolve.targets(42,5): error MSB3073: The command ""c:\dd\CoreFx\Tools/dotnetcli/dotnet.exe" restore --packages "c:\dd\CoreFx\packages" --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
--source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://api.nuget.org/v3/index.json c:\dd\CoreFx\external\test-runtime\XUnit.Runtime.depproj /p:TargetGroup=netstandard /p:ConfigurationGroup=Debug /p:ArchGrou
p=x64 /p:OSGroup=AnyOS /p:TargetFramework=netstandard2.0 -r win10-x64 " exited with code 1. [c:\dd\CoreFx\external\test-runtime\XUnit.Runtime.depproj]


```

Syncing back to commits that I knew worked yesterday and retrying just produces other nuget errors.

This looks like something changed nuget configuration on my box althought I thought corefx was supposed to be insulated from that.

Can anybody assist. 

@ericstj ; @weshaggard

**Comment by ericstj** [comment]
@weshaggard didn't you mention there was some behavior in the host where it was choosing a machine-wide SDK even when run from a private copy?  /cc @Petermarcu @eerhardt 

I agree those look like they should be warnings.  At the very least we should clean them up. I filed https://github.com/dotnet/buildtools/issues/1655 to fix that.

Now I'm trying to understand what's making those appear to you as errors.

**Comment by eerhardt** [comment]
@AtsushiKan - can you run `c:\dd\CoreFx\Tools/dotnetcli/dotnet.exe --info` from the `c:\dd\CoreFx\external\test-runtime` working directory and list the output?

**Comment by AtsushiKan** [comment]
```
.NET Command Line Tools (2.1.0-preview1-007042)

Product Information:
 Version:            2.1.0-preview1-007042
 Commit SHA-1 hash:  e94a82c9a3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\atsushik\.dotnet\x64\sdk\2.1.0-preview1-007042\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983


```

(Note: This was probably triggered by my cloning the aspnet/Kestrel yesterday as its build script installs/upgrades stuff in under %USERPROFILE%\.dotnet.)

**Comment by eerhardt** [comment]
Yes, you are hitting a change we had temporarily in the `dotnet.exe` host.  It was backed out for the official 2.0 release.

Delete the folder `C:\Users\atsushik\.dotnet\x64\sdk` and try again.

**Comment by AtsushiKan** [comment]
After renaming the sdk folder, `.\sync -p` now runs to completion. (The warnings are gone too.)

**Comment by AtsushiKan** [comment]
For further clarification:

- Is there a more offical way to uninstall that bad preview version of dotnet.exe than deleting the sdk folder?

- Is it expected that this external event should break the corefx build?

**Comment by eerhardt** [comment]
For more information on this behavior -

Here are the PRs that put the initial changes in 2.0.0
https://github.com/dotnet/core-setup/pull/1241
https://github.com/dotnet/core-setup/pull/1568

And here's the change that took out the `%USERPROFILE%` lookup out later in 2.0.0
https://github.com/dotnet/core-setup/pull/2627.

> Is there a more offical way to uninstall that bad preview version of dotnet.exe than deleting the sdk folder?

No.  Just deleting the folder manually is the only way.

> Is it expected that this external event should break the corefx build?

No, it isn't expected.  However, corefx is using an out-dated `dotnet.exe` host.  Moving to the released version or newer will solve this.

**Comment by AtsushiKan** [comment]
Ok, thanks.

**Comment by AtsushiKan** [comment]
>Yes, you are hitting a change we had temporarily in the dotnet.exe host. 

When can we expect to see this fixed in the master branch? It's getting to be a pain constantly renaming this directory.

**Comment by eerhardt** [comment]
> When can we expect to see this fixed in the master branch?

I was under the assumption that @joperezr was updating the CLI version to `2.0.0`, which would fix this.

/cc @weshaggard

**Comment by AtsushiKan** [comment]
Just to be, on current master bits, that little experiment: (run c:\dd\CoreFx\Tools/dotnetcli/dotnet.exe --info from the c:\dd\CoreFx\external\test-runtime working directory) still yields the output:

"Base Path:   C:\Users\atsushik\.dotnet\x64\sdk\2.1.0-preview1-007042\"

I have not re-attempted a build of corefx under this state..

**Comment by joperezr** [comment]
> I was under the assumption that @joperezr was updating the CLI version to 2.0.0, which would fix this.

Correct, I'm planning to do this either next week or the next. It is the next workitem once I'm done updating the compiler used in all of our repos.
