### ISSUE TITLE
Unable to build the repo on my machine

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/corefx#23657]
Hi, I followed [these](https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md) directions, but when I'm building it fails.

## My setup

- Windows 10.0.15063 Build 15063 x64 Home edition
- VS 2017 (15.3.3) Community edition (only IDE)
  - Workloads:
![image](https://user-images.githubusercontent.com/2716316/29845753-bb02a0e6-8d1c-11e7-9025-06af8acda619.png)
  - Individual components:
![image](https://user-images.githubusercontent.com/2716316/29846084-00e4d3bc-8d1e-11e7-8d84-96cb050ecbb3.png)
- Instructions from [here](https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md)

## Actual behavior

Calling *build-native.cmd* (or *build.cmd*) gives the following output:

```
Tools are already initialized.
Running: C:\Users\Shimmy\Source\Repos\corefx\src\Native\build-native.cmd   x64  Debug  Windows_NT  --numproc 8  -portable  toolSetDir=c:\tools\clr
Tools are already initialized.
Running: C:\Users\Shimmy\Source\Repos\corefx\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false /l:BinClashLogger,Tools\net46\Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log /p:ConfigurationGroup=Debug /p:BuildPackages=false /p:GenerateNativeVersionInfo=true  /flp:v=normal  /flp2:warningsonly;logfile=msbuild.wrn  /flp3:errorsonly;logfile=msbuild.err  C:\Users\Shimmy\Source\Repos\corefx\src\Native\..\../build.proj /t:GenerateVersionHeader
Project file contains ToolsVersion="14.0". This toolset may be unknown or missing, in which case you may be able to res
olve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVers
ion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://g
o.microsoft.com/fwlink/?LinkId=291333.
Command execution succeeded.
The system cannot find the path specified.
Commencing build of native components

Error: DIA SDK is missing at "DIA SDK". This is due to a bug in the Visual Studio installer. It does not install DIA SDK at "" but rather at VS install location of previous version. Workaround is to copy DIA SDK folder from VS install location of previous version to "" and then resume build.
Visual Studio Express does not include the DIA SDK. You need Visual Studio 2015 or 2017 (Community is free).
See: https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/developer-guide.md#prerequisites
Command execution failed with exit code 1.
```

When calling *build-managed.cmd* however, [this](http://pasted.co/03cc0523/fullscreen.php?hash=46ea6283825f86890ec8711f16f2ed78&toolbar=true&linenum=false) is the output I'm getting.

Any help please?

**Comment by danmosemsft** [comment]
@weitzhandler what is your setup? What version of VS do you have, and what version of the developer prompt do you have?

One of your errors is `C:\Users\Shimmy\Source\Repos\corefx\Tools\net46\roslyn\build\Microsoft.Net.Compilers.props(11,5): error : Microsoft.Net.Compilers is only supported on MSBuild v14.0 and above ` which makes me wonder if you have an old VS or you are not opening the developer command window for the latest VS.

You might try installing VS2017 (Community is free) if you haven't already.

**Comment by weitzhandler** [comment]
@danmosemsft I accidentally hit 'Post' while still editing my issue...
Anyway, I only have VS 2017 15.3.3.

**Comment by weitzhandler** [comment]
@danmosemsft I accidentally hit 'Post' while still editing my issue...
Please see my updated post.

**Comment by danmosemsft** [comment]
@weitzhandler what do you get when you do `where msbuild` in your prompt? This is what I get:

```
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26730.8
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************

C:\git\corefx>where msbuild
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe
```

**Comment by weitzhandler** [comment]
```bat
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe
```

**Comment by weitzhandler** [comment]
I only get

```bat
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe
```

**Comment by danmosemsft** [comment]
does `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe` exist? 

if so what do you get when you do `set PATH` ?

**Comment by weitzhandler** [comment]
Gonna add it to the path now, 1 sec

**Comment by danmosemsft** [comment]
The developer prompt should have added it. Are you opening the developer prompt, or just a command window? You should see something like this when you open it
```
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26730.8
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
```

**Comment by weitzhandler** [comment]
It's working now.
Thanks for your help Dan!

**Comment by weitzhandler** [comment]
Is it possible to debug it in VS 2017?

**Comment by danmosemsft** [comment]
@weitzhandler just to be clear, if you manually edited the path, rather than getting it from the developer prompt, you will likely have other issues further along.

For debugging you can see https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md

If the instructions need clarifying/improving, a PR to do that would be most welcome.

**Comment by danmosemsft** [comment]
Ah I see the issue!

https://github.com/dotnet/corefx/commit/244efc5332bc55c96873c242ed520e85a04e0e03

**Comment by weitzhandler** [comment]
Thank you Dan, that was it.

**Comment by weitzhandler** [comment]
Please also take care of fd33901fe77a946889d11ea4677699534f4d8e5c

**Comment by weitzhandler** [comment]
@danmosemsft 
The tests are not discovered, what am I missing?

**Comment by danmosemsft** [comment]
@joperezr any ideas? I tend to run tests on the command line.

**Comment by mellinoe** [comment]
@weitzhandler The test explorer window is not supported, if that is what you are referring to. You can set the test project as the "VS Startup Project" and debug it that way, or you can run tests on the command line.

**Comment by karelz** [comment]
@weitzhandler please check also steps linked form our main page - they are located on our wiki (for now).
In particular, check https://github.com/dotnet/corefx/wiki/Build-and-run-tests#build-run-and-debug-tests-using-visual-studio

**Comment by karelz** [comment]
Also, please do not reuse the same issue for 2 different reports ... it gets messy.

**Comment by weitzhandler** [comment]
@karelz 
I allowed myself doing it since this issue was closed anyway. Nevertheless thanks a lot Karel!
