### ISSUE TITLE
Add support for OpenSuse 42.2 in .NET CoreFx 1.1.0 

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#23667]
This issue tracks ensuring that your team has considered how to handle OpenSuse 42.2 builds in your .NET Core 1.1.0 repositories.

Since .NET Core 1.1 is an LTS release, per @leecow we need to support OpenSUSE 42.2 with it.  Unfortunately, when 1.1 release branches were snapped, 42.1 was the used version.  It turns out there was not even a RID (runtime identifier) that matches this build (In the 1.1 time frame, ‘opensuse.42.1-x64’ was used)

Please use this issue to track addressing the issue for your specific repository.  In some cases, little-to-no change will be required but lacking a previously-used RID we need to figure something out.

@weshaggard  FYI.

**Comment by weshaggard** [comment]
We have addressed this by continuing to build on 42.1 which should work on 42.2. At this time we don't plan to move to building on the latest version in our 1.x servicing releases.
