### ISSUE TITLE
CurlHandler Does Not Respect MaxConnectionsPerServer Property

### ISSUE THREAD

**Issue by NickGerleman** [dotnet/corefx#23676]
Setting MaxConnectionsPerServer on an HttpClientHandler doesn't do anything on Unix systems. The property is propagated to CurlHandler which [stores it as an instance variable](https://github.com/dotnet/corefx/blob/a26de495ffa390a9d6b3a0d0f338e9d9f97ad5fe/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.cs#L371) but doesn't ever use it. This seems like an oversight since [documentation for libcurl](https://curl.haxx.se/libcurl/c/CURLMOPT_MAX_HOST_CONNECTIONS.html) shows it can be set, and there is already piping to set related settings [in CurlHandler.MultiAgent.cs](https://github.com/dotnet/corefx/blob/a27929935d2782cdc3e7be21653e8c4530274c6f/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.MultiAgent.cs#L232).

**Comment by NickGerleman** [comment]
It looks like there is already piping to set related flags [in CurlHandler.MultiAgent.cs](https://github.com/dotnet/corefx/blob/a27929935d2782cdc3e7be21653e8c4530274c6f/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.MultiAgent.cs#L232).

**Comment by stephentoub** [comment]
> The property is propagated to CurlHandler which stores it as an instance variable but doesn't ever use it

It's used here:
https://github.com/dotnet/corefx/blob/a27929935d2782cdc3e7be21653e8c4530274c6f/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.MultiAgent.cs#L261

**Comment by NickGerleman** [comment]
My apologies, I only looked in the file where the property existed and forgot to look for partial classes.
