### ISSUE TITLE
Unix Socket Client Send WouldBlock  Server Receive Data Error

### ISSUE THREAD

**Issue by caozhiyuan** [dotnet/corefx#23672]
```c#
        /// <summary>
        /// Exchange a message with the host.
        /// </summary>
        /// <param name="message">Message to send.</param>
        /// <returns>Message sent by the host.</returns>
        internal void Send(string message)
        {
            if (!this.isContinue)
            {
                Console.WriteLine($"isContinue {this.isContinue}");
                return;
            }
            if (this.connected)
            {
                var nioBuffers = new List<ArraySegment<byte>>();
                nioBuffers.Add(new ArraySegment<byte>(Encoding.UTF8.GetBytes(message)));

                SocketError errorCode;
                long localWrittenBytes = this.clientSocket.Send(nioBuffers, SocketFlags.None, out errorCode);
                if (errorCode != SocketError.Success && errorCode != SocketError.WouldBlock)
                {
                    throw new SocketException((int)errorCode);
                }
                if (errorCode == SocketError.WouldBlock)
                {
                    this.isContinue = false;
                    Console.WriteLine(message);
                    var sendArgs = new SocketAsyncEventArgs();
                    sendArgs.BufferList = nioBuffers;
                    sendArgs.Completed += this.SendArgs_Completed;
                    bool pending = this.clientSocket.SendAsync(sendArgs);
                    if (!pending)
                    {
                        Console.WriteLine($"pending false BytesTransferred {sendArgs.BytesTransferred}");
                    }
                    else
                    {
                        Console.WriteLine($"pending true");
                    }
                }
                else
                {
                    Console.WriteLine($"{nioBuffers.Sum(n => n.Array.Length)} {localWrittenBytes}");
                }
            }
            else
            {
                throw new SocketException((int)SocketError.NotConnected);
            }
        }
```

https://github.com/caozhiyuan/DotNetty/tree/dev/examples/SocketAsyncClient

https://github.com/caozhiyuan/DotNetty/tree/dev/examples/SocketAsyncServer

![qq 20170830084137](https://user-images.githubusercontent.com/3415285/29850341-72317066-8d5f-11e7-9727-90cd239e0db0.png)

[EDIT] Add C# syntax highlighting by @karelz

**Comment by caozhiyuan** [comment]
Server in Windows  and Client in Ubuntu

**Comment by caozhiyuan** [comment]
when send  wouldblock,it has sent some bytes 
![qq 20170830191527](https://user-images.githubusercontent.com/3415285/29869937-a694f2d0-8db7-11e7-8010-9be80baac365.png)

**Comment by tmds** [comment]
@caozhiyuan TCP is a 'stream' protocol. This means data sent in 1 operation by one peer, can arrive at the other peer in separate messages. It looks like you are observing a message being cut because it would go over the peer recv buffer size. Then you hit the WouldBlock on the next send because the OS is waiting for the peer to receive data.

**Comment by IvanAntipov** [comment]
I made a repro **without** DotNetty

Socket.Send returns 0, but 29200 bytes are transmited in network. (NonBlocking mode is enabled)

To Run test
Depoloy TestTCP on Ubuntu14.04
1.1 Build
1.2 Copy files
1.3 Enable connections to port 8183 ( ufw allow 8183)
1.4 Start listener ( `dotnet TestTCP.dll syncnoblock`)
On Windows (client) side
2.1 `dotnet TestTCP get __your_ubuntu_ip_address`

[TestTCPSyncNoBlock.zip](https://github.com/dotnet/corefx/files/1269743/TestTCPSyncNoBlock.zip)

**Comment by caozhiyuan** [comment]
@tmds  @IvanAntipov  is linux it always returns 0, 0 means no buffer send. in windows no this problem

**Comment by tmds** [comment]
@IvanAntipov please share the console output of client&server when running the steps.

**Comment by caozhiyuan** [comment]
@tmds  you debug it get a 257 byte msg , for 1 to 4000 add to List<ArraySegment<byte>>, then send

**Comment by IvanAntipov** [comment]
![client](https://user-images.githubusercontent.com/18117729/29964186-ef733a38-8f11-11e7-85bc-f531ea77cb38.png)
![server](https://user-images.githubusercontent.com/18117729/29964187-ef91700c-8f11-11e7-8c69-c945d03a37ec.png)

**Comment by caozhiyuan** [comment]
@IvanAntipov  both in windows , no this problem

**Comment by tmds** [comment]
@IvanAntipov Interesting. Can you share the output when running `strace -f -e sendmsg dotnet TestTCP.dll syncnoblock`?

**Comment by IvanAntipov** [comment]
@tmds

>  Can you share the output when running strace -f -e sendmsg dotnet TestTCP.dll syncnoblock?

root@test9:/usr/src/testtcp# strace -f -e sendmsg dotnet TestTCP.dll syncnoblockProcess 16245 attached
Process 16244 attached
Process 16246 attached
Process 16247 attached
Process 16248 attached
Process 16249 attached
ListenSyncSendNoBlock
Process 16250 attached
Process 16251 attached
Bind
Wait
Process 16252 attached
[pid 16251] +++ exited with 0 +++
Process 16253 attached
Send
Process 16254 attached
[pid 16250] sendmsg(33, {msg_name(0)=NULL, msg_iov(1)=[{"<!DOCTYPE html>\r\n<html class=\" a"..., 127135}], msg_controllen=0, msg_flags=0}, 0) = 29200
[pid 16250] sendmsg(33, {msg_name(0)=NULL, msg_iov(1)=[{"pan class=\"x-ph__link__text\">\320\230\320"..., 97935}], msg_controllen=0, msg_flags=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
Sent count 0
Wait
[pid 16253] +++ exited with 0 +++
[pid 16254] +++ exited with 0 +++
[pid 16250] +++ exited with 0 +++

**Comment by tmds** [comment]
@IvanAntipov `Send` should have returned `29200` (return value from first sendmsg call). Are you running .NET Core 2.0 release on the Linux machine?

**Comment by IvanAntipov** [comment]
@tmds 

> Send should have returned 29200 (return value from first sendmsg call). Are you running .NET Core 2.0 release on the Linux machine?

Yes, i running .Net Core 2.0

**Comment by tmds** [comment]
I think we arrive here:
https://github.com/dotnet/corefx/blob/fe0e443ac01ee5a5afefb302b89f1504c3988eda/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L1210-L1220

errorCode is WouldBlock and `0` is returned instead of `bytesTransferred`.

**Comment by caozhiyuan** [comment]
@tmds  i debug it on linux , native code return 0

**Comment by tmds** [comment]
Summary:
Socket.Send returns `0` instead of the amount of bytes transferred when data is partially sent over a non-blocking socket.

\cc @stephentoub @geoffkizer @karelz

**Comment by caozhiyuan** [comment]
@tmds  https://github.com/dotnet/corefx/blob/fe0e443ac01ee5a5afefb302b89f1504c3988eda/src/System.Net.Sockets/src/System/Net/Sockets/SocketPal.Unix.cs#L148

**Comment by tmds** [comment]
Minimal repro:
```C#
            var listener = new TcpListener(IPAddress.Loopback, 0);
            listener.Start();
            var client = new TcpClient();
            client.Connect(listener.LocalEndpoint as IPEndPoint);
            Socket socket = listener.AcceptSocket();

            socket.Blocking = false;
            var data = new byte[100_000_000];
            SocketError error;
            int bytesSent = socket.Send(data, 0, data.Length, SocketFlags.None, out error);
            
            Console.WriteLine($"{bytesSent} - {error}");
```
outputs:
```
0 - WouldBlock
```
strace shows:
```
sendmsg(26, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., iov_len=100000000}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 2772174
sendmsg(26, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., iov_len=97227826}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
```
The output should have been:
```
2772174 - Success
```

**Comment by caozhiyuan** [comment]
@tmds  @stephentoub is has any idea to fix it

**Comment by caozhiyuan** [comment]
@tmds  wo now use Socket.SendAsync(operation)  , async method no bug

**Comment by tmds** [comment]
@caozhiyuan that is the preferred way of working: :+1:
