### ISSUE TITLE
Address PR feedback for System.Net.WebHeaderCollection

### ISSUE THREAD

**Issue by pgavlin** [dotnet/corefx#2368]
- Replace `HeaderParser` with `Func<string, string[]>`
- Make static fields `readonly`
- Optimize `HeaderInfoTable` for allocation volume and remove the static constructor
- Replace non-generic collections with generic collections

**Comment by davidsh** [comment]
Reference initial commit #2358

**Comment by bbowyersmyth** [comment]
Is the ToString() a candidate for using the System.IO.StringBuilderCache? Is that how it is being written to the http response?

**Comment by davidsh** [comment]
The ToString() method is not used to write data to the wire.  This class is only a helper class for the System.Net.HttpWebRequest class.

**Comment by davidsh** [comment]
Fixed with #2380.
