### ISSUE TITLE
Move some System.Net.WebHeaderCollection tests from [Fact]s to [Theory]s

### ISSUE THREAD

**Issue by pgavlin** [dotnet/corefx#2370]
The current version of xUnit used by CoreFX has problems writing text containing certain code points to the test log. There are tests in S.N.WHC that use these code points. These tests are currently [Fact]s, but should be combined with the appropriate [Theory] once CoreFX has taken an updated version of xUnit that fixes the issue.

**Comment by davidsh** [comment]
Reference initial commit #2358

**Comment by davidsh** [comment]
Now that dotnet/buildtools#334 is fixed, we can work on this issue.
