### ISSUE TITLE
Handle EAGAIN in Console.Write

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23717]
Already fixed in master. https://github.com/dotnet/corefx/pull/23713 ports it to the release/2.0 branch and should be merged for 2.0.2.

**Comment by Petermarcu** [comment]
This is approved for checkin when the branch is open for 2.0.2.

**Comment by CESARDELATORRE** [comment]
Related issues:
https://github.com/Microsoft/msbuild/issues/2153#issuecomment-310011758
https://github.com/dotnet-architecture/eShopOnContainers/issues/288

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/pull/23713
