### ISSUE TITLE
ClientWebSocket does not send SNI header on linux

### ISSUE THREAD

**Issue by danzel** [dotnet/corefx#23731]
When creating a ClientWebSocket to a `wss://` url on linux (Ubuntu 16.04), the SNI header is not set in the TLS handshake.

This is in violation of the WebSockets RFC (And it breaks real world usage when SNI is actually required)
https://tools.ietf.org/html/rfc6455#page-17 (End of point 5).

Linux (Ubuntu 16.04-x64)
![image](https://user-images.githubusercontent.com/393086/29955833-af5bf956-8f36-11e7-8291-27b8f194c338.png)
(`extension: server_name` is missing)

Windows
![image](https://user-images.githubusercontent.com/393086/29955836-b7347e6e-8f36-11e7-818d-121752fe5a69.png)
(`extension: server_name` is included)

**Test code**
This will succeed as SNI is not required for this server, however if you look at the packets in wireshark the SNI extension is not included.
```cs
using System;
using System.Net.WebSockets;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace HttpsTest
{
        class Program
        {
                static void Main(string[] args)
                {
                        Task.Run(WebSocketTask).Wait();
                }

                static async Task WebSocketTask()
                {
                        var ws = new ClientWebSocket();
                        Console.WriteLine("Connecting");
                        await ws.ConnectAsync(new Uri("wss://echo.websocket.org"), CancellationToken.None);
                        Console.WriteLine("Sending");
                        await ws.SendAsync(new ArraySegment<byte>(Encoding.UTF8.GetBytes("test hi")), WebSocketMessageType.Text, true, CancellationToken.None);
                        Console.WriteLine("Receiving");
                        var res = await ws.ReceiveAsync(new ArraySegment<byte>(new byte[100]), CancellationToken.None);
                        Console.WriteLine("Received " + res.Count);
                        await ws.CloseAsync(WebSocketCloseStatus.NormalClosure, String.Empty, CancellationToken.None);
                }
        }
}
```

**Comment by stephentoub** [comment]
@geoffkizer, @Priya91, could one of you take a look?  ClientWebSocket on Linux is just using SslStream, so if there's actually an issue here, it's with SslStream:
https://github.com/dotnet/corefx/blob/a27929935d2782cdc3e7be21653e8c4530274c6f/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.Managed.cs#L91-L100

**Comment by Priya91** [comment]
Will take a look!

**Comment by Priya91** [comment]
Assigning to myself to set reminder.

**Comment by Priya91** [comment]
Looked at this, it seems like openssl doesn't send the server name extension automatically, it gets sent only if configured with -servername option or by using SSL_set_tlsext_host_name in c apis. Will put up a PR to default send sni extension. This is anyways work in pending.

**Comment by qmfrederik** [comment]
@Priya91 I just hit the same issue on a Linux box.

I see there's no milestone set for this issue, so not sure whether it's something that's being actively worked on. Is there a workaround or a fix we can try?

**Comment by Priya91** [comment]
This is related to #24553, when sslstream supports sni, this is easy to fix.

**Comment by Priya91** [comment]
We can make this work by default on client, just like the windows behavior, and shelf the api-proposal for server side. On the client side sslstream, this doesn't require any new apis, but will require an implementation change.
