### ISSUE TITLE
Tests under "System.Security.Cryptography.X509Certificates.Tests" failed with "Interop+AppleCrypto+AppleCommonCryptoCryptographicException" in CI

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#23738]
Failed tests:
 System.Security.Cryptography.X509Certificates.Tests.X509StoreTests.ReOpen_IsOpenTrue
 System.Security.Cryptography.X509Certificates.Tests.X509StoreTests.AddReadOnlyThrowsWhenCertificateExists
 System.Security.Cryptography.X509Certificates.Tests.X509StoreTests.ReadMyCertificates
 System.Security.Cryptography.X509Certificates.Tests.X509StoreTests.Constructor_OpenFlags_StoreName
 System.Security.Cryptography.X509Certificates.Tests.X509StoreTests.Dispose_IsOpenFalse
 System.Security.Cryptography.X509Certificates.Tests.X509StoreTests.AddDisposedThrowsCryptographicException
 System.Security.Cryptography.X509Certificates.Tests.X509StoreTests.AddReadOnlyThrows
 System.Security.Cryptography.X509Certificates.Tests.X509StoreTests.Constructor_OpenFlags
 System.Security.Cryptography.X509Certificates.Tests.X509StoreTests.RemoveReadOnlyThrowsWhenFound
 System.Security.Cryptography.X509Certificates.Tests.X509StoreTests.Constructor_OpenFlags_OpenAnyway
 System.Security.Cryptography.X509Certificates.Tests.X509StoreTests.TestDispose
 System.Security.Cryptography.X509Certificates.Tests.X509StoreTests.OpenMyStore
 System.Security.Cryptography.X509Certificates.Tests.X509StoreTests.Constructor_StoreHandle
 System.Security.Cryptography.X509Certificates.Tests.X509StoreTests.Open_IsOpenTrue
 System.Security.Cryptography.X509Certificates.Tests.CertTests.X509Cert2ToStringVerbose

MESSAGE:
~~~
Interop+AppleCrypto+AppleCommonCryptoCryptographicException : A default keychain could not be found.
~~~
STACK TRACE:
~~~
at Interop.AppleCrypto.SecKeychainCopyDefault() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/Common/src/Interop/OSX/System.Security.Cryptography.Native.Apple/Interop.Keychain.cs:line 106 
at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.OSX/StorePal.cs:line 106 
at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Store.cs:line 127 
at System.Security.Cryptography.X509Certificates.Tests.X509StoreTests.ReOpen_IsOpenTrue() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/System.Security.Cryptography.X509Certificates/tests/X509StoreTests.cs:line 201
~~~

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release/2971/testReport/

**Comment by bartonjs** [comment]
@mmitche have we changed something about how OSX runs work recently?

**Comment by mmitche** [comment]
@bartonjs Nope.

**Comment by Jiayili1** [comment]
This issue is repro in osx10.12_release, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release/3132/testReport/

**Comment by bartonjs** [comment]
> 10:25:24 Building remotely on dci-mac-build-053 (dtap osx-10.12) in workspace /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release

If it happens again, and it's on 053, it means that machine is somehow configured differently than the rest.

**Comment by Jiayili1** [comment]
This issue is repro in oxs10.12_debug, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/3133/testReport/

**Comment by bartonjs** [comment]
@mmitche All the failures I've seen have been on dci-mac-build-053.  It'd be great if we could ensure it's set up the same as the rest of the machines.  (Seems like it hasn't ever had an interactive login by the execution user, or it's SSH, or something)

**Comment by mmitche** [comment]
@bartonjs  I'm just going to take this thing offline and have it reimaged.

**Comment by bartonjs** [comment]
Haven't heard anything about this in a while, and I don't see it in recent runs. Seems like it was a machine problem.

**Comment by Sunny-pu** [comment]
This issue is repro in oxs10.12_debug, detail: 
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/4132/testReport/

**Comment by bartonjs** [comment]
@mmitche Of the last 7 runs it looks like 6 worked just fine, and one of them has no default keychain:

| Job | Machine | Happy |
|----|----|----|
| [4127](https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/4127/) | OSX.1012.Amd64.Open-0130163239940-0 | Yes |
| [4128](https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/4128/) | OSX.1012.Amd64.Open-0130203050235-0 | Yes |
| [4129](https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/4129/) | dci-mac-build-054 | Yes |
| [4130](https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/4130/) | dci-mac-build-099 | Yes |
| [4131](https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/4131/) | dci-mac-build-080 | Yes |
| [4132](https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/4132/) | OSX.1012.Amd64.Open-0130225759945-0 | No (no default keychain) |
| [4133](https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/4133/) | dci-mac-build-086 | Yes |

Digging back to 4091 I didn't see any other failures.  Seems the new pool has some sort of mild flakiness to its setup.

**Comment by mmitche** [comment]
@bartonjs Filed https://github.com/dotnet/core-eng/issues/2546.  How can the default keychain be set up again?  It's been a while

**Comment by bartonjs** [comment]
No idea :smile:.  First interactive logon, maybe?  The only machines I've ever seen with the problem were in CI.

**Comment by MattGal** [comment]
047 is disabled for now.  I'll have someone investigate it by trying to run the x509 tests on it directly, and it doesn't go back into the pool until that is understood.

**Comment by joshfree** [comment]
> How can the default keychain be set up again? It's been a while

it should be something like

Apps Folder > Utilities > Keychain Access 
-> Preferences -> General -> Reset My Default Keychain.. reboot.

**Comment by MattGal** [comment]
Thanks Josh!  While it literally took me almost 5 minutes to find the apps folder, that worked and the X509 tests now pass on DCI-MAC-BUILD-047.  Putting it back into the pool now.
