### ISSUE TITLE
WindowsIdentity ctor should pass authType to base

### ISSUE THREAD

**Issue by brentschmaltz** [dotnet/corefx#23742]
This constructor passes null to base, should pass authType

https://github.com/dotnet/corefx/blob/master/src/System.Security.Principal.Windows/src/System/Security/Principal/WindowsIdentity.cs#L202

**Comment by danmosemsft** [comment]
Looks like this was just copied from desktop.
https://referencesource.microsoft.com/#mscorlib/system/security/principal/windowsidentity.cs,158 

I'll let area owner say whether we can fix it..

**Comment by brentschmaltz** [comment]
@danmosemsft that would be me, I say we fix it.

**Comment by danmosemsft** [comment]
@bartonjs, @ianhays are down for System.Security.*. Can one of you guys ok?

**Comment by bartonjs** [comment]
In what circumstances does the difference matter? And why would we want core to deviate from netfx behavior?

**Comment by brentschmaltz** [comment]
We should make the same fix in desktop.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bartonjs** [comment]
Okay... what's the difference? What's the test that fails currently that we believe should pass? If it's measurable that means it's a compat problem, so assess it from a compat risk... what user is going to depend on this in vFuture and then find that they blow up in weird places on vCurrent?

**Comment by brentschmaltz** [comment]
@bartonjs I haven't looked at tests yet, it may be missing. Are you saying that a 4.7.2 user (after the fix) should have the same experience as 4.5.2? We could apply a quirk if necessary.

**Comment by bartonjs** [comment]
I'm just asking what the measurable change is, and why it's worth doing.  If no one can see the difference, we should leave the code alone.  If someone can see the difference then it should probably undergo a compat review for .NET Framework before we make a change in .NET Core, so we understand what the reconciliation is.  (Code written against .NET Framework 4.7 or .NET Core 2.0, then the runtime upgrades and now things are different.)

**Comment by brentschmaltz** [comment]
@bartonjs if your making the point, who cares and we have items to address that would better serve our customers. I would not push back if you closed this issue.

**Comment by stephentoub** [comment]
@brentschmaltz, Jeremy is simply asking why this change should be made.  You've proposed a what but not a why.  What does this change do?  What's broken without it?  What improves with it?  etc.

**Comment by brentschmaltz** [comment]
@stephentoub yes I agree those are the questions.The authtype was not passed to ClaimsIdentity in this ctor: https://github.com/dotnet/corefx/blob/master/src/System.Security.Principal.Windows/src/System/Security/Principal/WindowsIdentity.cs#L202 which means that the WindowsIdentity and ClaimsIdentity have different instance variables for AuthenticationType.  Looking at it carefully, I can't see a bug. I was think I was reacting to the different logic between the base and derived. Which in ClaimsIdentity is: IsAuthenticated is related to AuthenticationType != null or Empty. Whereas WindowsIdentity has two separate variables. So a WindowsIdentity could have an AuthenticationType but IsAuthenticated == false.  Seems odd.

**Comment by bartonjs** [comment]
Without having a reason for the change it doesn't seem to make sense to me.  We'd have trouble justifying a "why" for the change to .NET Framework, and it seems wrong to diverge Core and Framework without a reason.
