### ISSUE TITLE
System.Net.Http.CurlException: Server returned nothing (no headers, no data)

### ISSUE THREAD

**Issue by mayconbeserra** [dotnet/corefx#23745]
Hi there,

I'm getting an error `System.Net.Http.CurlException: Server returned nothing (no headers, no data)`  when calling a https endpoint in .NET Core 1.1.2 only on Docker Container.

Currently, it works on Windows running via Visual Studio, but it doesn't work inside my Linux Container.

**As part of my customer environment, I have to add their CA certificates in our containers but it still doesn't work.

Please, could you someone highlight any issue with my approach?

**The details are below:**

My docker file is -

```
FROM microsoft/aspnetcore:1.1.2

ADD /CA.crt /usr/local/share/ca-certificates/CA.crt
RUN chmod 777 /usr/local/share/ca-certificates/CA.crt

RUN apt-get update && apt-get install -y apt-transport-https ca-certificates
RUN update-ca-certificates
............
```

Code example:
```c#
var clientCertificate = new X509Certificate2("Certificates/my-certificate.pfx", "password");

var handler = new HttpClientHandler();

handler.ClientCertificateOptions = ClientCertificateOption.Manual;
handler.SslProtocols = SslProtocols.Tls12;
handler.ClientCertificates.Add(clientCertificate);

var httpClient = new HttpClient(handler);
httpClient.DefaultRequestHeaders.Add("Authorization", "Basic XPTO");

var response = await http.SendAsync(request);
```

Exception:

```
System.Net.Http.CurlException: Server returned nothing (no headers, no data)
app_1  |    at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
app_1  |    at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)

```

File Info for `HttpClient`:

```
app_1  | [16:13:20 DBG] File:             /usr/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/System.Private.CoreLib.ni.dll
app_1  | InternalName:     System.Private.CoreLib.ni.dll
app_1  | OriginalFilename: System.Private.CoreLib.ni.dll
app_1  | FileVersion:      4.6.25211.01
app_1  | FileDescription:  System.Private.CoreLib
app_1  | Product:          Microsoft/x00ae .NET Framework
app_1  | ProductVersion:   4.6.25211.01. Commit Hash: 7a35adb1a68baa02f542ed06b5d7a1b9167f32fb
app_1  | Debug:            False
app_1  | Patched:          False
app_1  | PreRelease:       False
app_1  | PrivateBuild:     False
app_1  | SpecialBuild:     False
app_1  | Language:         Language Neutral
app_1  |
app_1  | [16:13:20 DBG] File:             /usr/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/System.Net.Http.dll
app_1  | InternalName:     System.Net.Http.dll
app_1  | OriginalFilename: System.Net.Http.dll
app_1  | FileVersion:      4.6.25220.01
app_1  | FileDescription:  System.Net.Http
app_1  | Product:          Microsoft┬« .NET Framework
app_1  | ProductVersion:   4.6.25220.01. Commit Hash: 936d52df0532d56a19ff8486bc9aa7eac19860b3
app_1  | Debug:            False
app_1  | Patched:          False
app_1  | PreRelease:       False
app_1  | PrivateBuild:     False
app_1  | SpecialBuild:     False
app_1  | Language:         Language Neutral
```

[EDIT] Add C# syntax highlighting by @karelz

**Comment by mayconbeserra** [comment]
@davidsh If I build the image and run in my CI (Ubuntu), I have a different error:

```
System.Net.Http.HttpRequestException:
An error occurred while sending the request. --->
System.Net.Http.CurlException: Failure when receiving data from the peer
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
```

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by karelz** [comment]
@mayconbeserra do you still see the problem? Can you please try to reproduce it on .NET Core 2.0?
Are you able to reproduce it on any Linux VM?
Can you please provide full repro steps how to set up the (minimal) repro locally?

**Comment by karelz** [comment]
No response, closing. Feel free to reopen when there is more info available.

**Comment by sabatmonk** [comment]
I have the same (or very similar) issue with core 2.0 

`Unhandled Exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Server returned nothing (no headers, no data)
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference'1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable'1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
   at BassArachniWorker.Executor.<CreateNewScan>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
   at BassArachniWorker.Executor.<Run>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
   at BassArachniWorker.Worker.<>c__DisplayClass1_0.<<Run>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()`

tried workaround from #9357 but using direct ip in call did not help.

Like the original issue, work flawlessly in debug mode of VS(studio and code) and jetbrains riders, i tried them all. But break when using microsoft dotnet linux container

**Comment by karelz** [comment]
@sabatmonk do you have a minimal repro we can try locally? Which distros did you try?

**Comment by mayconbeserra** [comment]
Sorry for the delay @karelz , but It works on .NET Core 2.

I only have one similar issue with .NET Core 2 on macOS High Sierra:

**Reported issue:** https://github.com/dotnet/corefx/issues/27000

**Comment by karelz** [comment]
@mayconbeserra there is different exception in #27000. Why is that the same?

**Comment by sabatmonk** [comment]
@karelz i will try to make a container to reproduce the issue without code from work ;)
As for repo, i use microsoft/dotnet but it failed with microsoft/aspnetcore also. From my tests, i cannot call an arachni server on a different machine but it works if i use an arachni container ("official" one or custom) in the same docker network. Also, it does a weird behavior where the arachni server will create two scans, meaning it received to requests, even though the netcore code is failling in the container.
