### ISSUE TITLE
Add GenericMethodParameters and GenericMethodArguments to MethodBase

### ISSUE THREAD

**Issue by kingces95** [dotnet/corefx#23741]
## Proposed Additions

```
class MethodBase
{
    public virtual Type[] GenericMethodArguments => IsConstructedGenericMethod ? GetGenericArguments() : Array.Empty<Type>();
    public virtual Type[] GenericMethodParameters => IsGenericMethodDefinition ? GetGenericArguments() : Array.Empty<Type>();
}
```

As with most Reflection methods, these are defined virtually to allow implementors to override with more efficient versions. CoreRT is well positioned to do this.

### Symmetry

These properties exist on `TypeInfo` (as `GenericTypeArguments` and `GenericTypeParameters`). It is inconsistent for them to be missing on `MethodBase`

With this addition, the api space would look like this:

| Type/TypeInfo | MethodBase/MethodInto |
| ---- | ---- |
| IsGenericType | IsGenericMethod |
| IsGenericTypeDefinition | IsGenericMethodDefinition |
| GetGenericArguments | GetGenericArguments |
| GetGenericTypeDefinition | GetGenericMethodDefinition |
| MakeGenericType | MakeGenericMethod |
| IsConstructedGenericType | IsConstructedGenericMethod |
| ContainsGenericParameters | ContainsGenericParameters |
| GenericTypeArguments |  GenericMethodArguments [new] |
| GenericTypeParameters |  GenericMethodParameters [new] |

@AtsushiKan
> ### GetGenericArguments() is a code smell
> Generic parameters and generic arguments are different things. The former are the "type formals" declared by the generic method definition. The latter are the actual (usually closed) types used to create an instantiation of the generic method definition. The 2.0 `GetGenericArguments()` api conflates the two, and while it's not the end of the world, some developers prefer to be explicit about their intentions.

@kingces95
> ### GetGenericArguments() smells of roses
> See [comment](https://github.com/dotnet/corefx/issues/23741#issuecomment-326705519)

## Why on MethodBase rather than MethodInfo

The existing pattern in Reflection is to put apis pertaining to generics on `MethodBase` **unless** the api returns a method, in which case, it lives on `MethodInfo` so that the caller receives a `MethodInfo` without casting. Should .NET ever decide to support generic constructors, this bit of future proofing will pay off - in any case, it costs next to nothing to put it on `MethodBase`. The following apis already exist on `MethodBase`.

- IsGenericMethodDefinition 
- IsConstructedGenericMethod 
- IsGenericMethod 
- GetGenericArguments 

## Naming: GenericMethodParameters or GenericTypeParameters?

While a case could be made that the word "Type" refers to the fact that generic parameters are "**type** variables", we did just introduce a new api named `Type.MakeGenericMethodParameter()`. So I'm inclined to roll with the "Method" names.

**Comment by AtsushiKan** [comment]
@MichalStrehovsky 

Some initial thoughts:

- I too have been irritated at having to write `GetGenericArguments()` to get a generic method's **parameters**, so I can appreciate this. And we did add `IsConstructedGenericMethod` using this same argument.

- Semantic cleanliness aside though, it is the safer way given CoreCLR and full desktop's annoying inability to represent the generic method definition separately from the generic method instantiated over its own generic parameters. `GenericTypeParameters` would fail on this case. This api was more useful in an alternate world where the .NET Core 1 refactoring succeeded (and in that world, we also removed `GetGenericArguments()` so there was no duplication.)

- `GenericTypeParameters` lives on `TypeInfo`, not `Type` so it's not completely symmetric.

So I'm on the fence on this. Reflection already has many duplicative apis due to its history - I'm not sure there's a strong reason to add another.

**Comment by AtsushiKan** [comment]
Also, all of these apis are actually on `MethodBase`, not `MethodInfo`. 

```
        public virtual bool IsConstructedGenericMethod
        public virtual bool IsGenericMethod
        public virtual bool IsGenericMethodDefinition
        public virtual Type[] GetGenericArguments();
        public virtual bool ContainsGenericParameters

```
So maybe these two should go on `MethodBase` too? Who knows, generic constructors might become a thing some day...

**Comment by JonHanna** [comment]
It would save having to do a cast just to get to them, and if it required an implementation in `ConstructorInfo` it would be trivial.

**Comment by kingces95** [comment]
IMHO achieving symmetry outweighs the price of duplication. But regardless, in this case, as noted, `GetGenericArguments()` is _not_ a duplicate of `GenericTypeArguments` as the former returns generic arguments on on all types for which `IsGenericType` is true while the latter does the same _except_ when `IsGenericTypeDefinition` is true. Given the difference, some customers may prefer `GenericTypeArguments` when using `Type` and may want to adopt the same convention when using `MethodInfo`. 

This [fiddle](https://dotnetfiddle.net/ZX5X2D) illustrates the difference. It will print the following for the lengths of the arrays returned for the two API for instantiations of a type `class Foo<T, V> { }`: 

> fooTV.GetGenericArguments(): 2
fooTV.GenericTypeArguments: 0
fooVT.GetGenericArguments(): 2
fooVT.GenericTypeArguments: 2

````C#
using System;
using System.Reflection;

public class Foo<T, V> { }

public class Program
{
    public static void Main(string[] args)
    {
		var fooTV = typeof(Foo<,>);
		Console.WriteLine($"fooTV.GetGenericArguments(): {fooTV.GetGenericArguments().Length}");
		Console.WriteLine($"fooTV.GenericTypeArguments: {fooTV.GenericTypeArguments.Length}");
		
		var fooTVInfo = fooTV.GetTypeInfo();
		var T = fooTVInfo.GenericTypeParameters[0];
		var V = fooTVInfo.GenericTypeParameters[0];
		
		var fooVT = fooTV.MakeGenericType(V, T);
		Console.WriteLine($"fooVT.GetGenericArguments(): {fooVT.GetGenericArguments().Length}");
		Console.WriteLine($"fooVT.GenericTypeArguments: {fooVT.GenericTypeArguments.Length}");
    }
}
````

**Comment by AtsushiKan** [comment]
I'm leaning towards accepting this but I'll leave this open for a week to give others a chance to provide feedback.

**Comment by AtsushiKan** [comment]
I've updated the top post with a more formal proposal.

**Comment by kingces95** [comment]
Cool! I have a different take on `GetGenericArguments` so I quoted your commentary. 

IMHO, using `GetGenericArguments()` can be simpler than using `GenericTypeArguments` and `GenericTypeParameters`.  

For example, consider [this fiddle](https://dotnetfiddle.net/2ULtuN). It defines a type `Foo<T>` with a pair of `Activate` method overloads. It then tries to print the first generic argument of the return type of each overload.
````c#
class Foo<T> { 
    public static Foo<T> Activate(T arg) { ... } 
    public static Foo<int> Activate(int arg) { ... }
} 
````
Compare `GetGenericArguments()`
```` C#
foreach (var method in typeof(Foo<>).GetTypeInfo().DeclaredMethods)
	Console.WriteLine(method.ReturnType.GetGenericArguments().First());
````
vs `GenericTypeArguments`/`GenericTypeParameters`
```` C#
foreach (var method in typeof(Foo<>).GetTypeInfo().DeclaredMethods) {
	var returnType = method.ReturnType;
	var genericArguments = !returnType.IsGenericTypeDefinition ?
		returnType.GenericTypeArguments :
		returnType.GetTypeInfo().GenericTypeParameters;
	Console.WriteLine(genericArguments.First());
}
````
The former is simpler. 

But either way, `GenericTypeArguments` and `GenericTypeParameters` should still have `MethodInfo` counterparts.

**Comment by AtsushiKan** [comment]
Yeah, the old apis are a necessary evil for making it easy to work with CoreCLR/Netfx quirky Reflection model. In a perfect world, ReturnType would always return a constructed generic type even for the `Foo<T>` method and the code could be written cleanly.

**Comment by AtsushiKan** [comment]
Closing due to lengthy inaction.
