### ISSUE TITLE
How can we maintain library packages for things that also ship in framework packages?

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#23743]
See https://github.com/dotnet/corefx/issues/23656, https://github.com/dotnet/corefx/pull/23719#issuecomment-326450314, and https://github.com/dotnet/corefx/commit/75962dae7f338445b57d7d276d018774e1dd2e46.

Whenever we wish to expose portable surface area for a library we must do so through a package. If that library is also *inbox* in the framework the framework will carry an optimized version of the library that should take precedence.

In all cases the library does not need to follow the netstandard rules (new API can only be in a new NETStandard version), since it is not part of netstandard.

1. In some cases the library can deliver its implementation completely out of band to all frameworks, so the library will want to add new API in a new package and make that API available to all platforms supporting some low version of netstandard say `netstandard1.1`.  It needs to do this without regressing the inbox implementations on existing frameworks, and also without dropping support for those frameworks or causing missing member/type exceptions or loader exceptions.  Examples of this sort of library are System.Collections.Immutable, System.Buffers, and System.Memory.  The latter two are interesting in that they are coupled to the NETCore runtime and must preserve that implementation.

2. In other cases the library cannot deliver new implementation out of band to some frameworks: for example if the library is exposing types that already exist in desktop and we do not wish to (or cannot) deliver a replacement library out of band.  In this case the library cannot add API to existing netstandard versions because those imply a version of desktop which will not have the new API.  In these cases we should freeze the API and the assembly version, and ideally not even rebuild the library unless it contains actual code.  We should also ensure our build system leads folks into this path so that we don't accidentally break these rules.  Examples of this sort of library are Microsoft.CSharp and System.IO.Ports.

We can refer to these two cases as "OOB" libraries and "Anchored" libraries for the purpose of this discussion.

/cc @weshaggard @terrajobst @Petermarcu

**Comment by weshaggard** [comment]
We at a minimum need to inspect the packages we are shipping as part of this release to ensure we don't break on any of the existing frameworks (.NET Core, .NET Framework, and UAP).

**Comment by weshaggard** [comment]
@ericstj any thoughts on a good approach to ensure the packages are valid? Should we diff the nuspecs between last release and this release and perhaps manually look at any new packages?

**Comment by ericstj** [comment]
Package validation helps since it looks at assembly versions supported by the last package and latest, but isn't foolproof since it doesn't crack the assemblies.  

The [package tests](https://github.com/dotnet/corefx/tree/master/pkg/test) are one good thing to run.  Those will catch cases where we replace a facade with an IL implementation.  We can also grow them to make sure they cover the scenarios in this issue (EG: Add API compat).  We should also get them [running in Helix](https://github.com/dotnet/corefx/issues/17346).  Currently they are broken due to a nuget breaking change that I'm investigating.

**Comment by weshaggard** [comment]
@ericstj I know you did your package validation work is there more you plan to do for this issue?

**Comment by joperezr** [comment]
yeah, what we talked about is that once he fixed all of the current issues with his tests, I would take them and have them run either on Official builds or on Helix daily. So that is the missing piece and it is what I'm working on now.

**Comment by weshaggard** [comment]
Can we enable them optionally at the end of the allconfiguration build leg and just enable that option in CI/official builds?

**Comment by ericstj** [comment]
We could, but it will make those builds really long.  On my dev box with pciExpress SSD it still takes 15 minutes to run everything.  I bet they wouldn't do so well on a VM.

**Comment by joperezr** [comment]
As discussed with both of you offline the plan is as follows:
 - I will plug in the tests to the `-allConfigurations` leg and send out a PR to try to see how long it would take for CI machines to run these tests.
 - If the time of the allConfigurations leg is acceptable, then we won't do anything else. 
 - On the other hand, if it takes too long to run the tests, then I will add a `-SkipTests` and a `-ArchiveTests` options that should only generate the projects, zip them up, and submit them to Helix so we can parallelize the tests so that they run faster.

**Comment by weshaggard** [comment]
Moving to Post-ZBB as all that is left is to automate the checks the code changes for the produce are believed to be done.

**Comment by weshaggard** [comment]
Actually @joperezr lets use https://github.com/dotnet/corefx/issues/17346 to track the automation of the work.
