### ISSUE TITLE
Need performance tests for creating and deleting directories

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#23759]
We should have some performance tests for creating and deleting nested directories. I have a stress test that shows how to create deeply nested directories that can be used as a reference:

https://github.com/dotnet/corefx/blob/1d3cc0417753bf0a436824abfeff9c3c1712f63f/src/System.IO.FileSystem/tests/Directory/Delete.cs#L256

There are limits to path lengths on some platforms. As such here are some suggested scenarios:

**All Platforms**

Create/Delete a directory that is 10 & 100 levels deep

**Windows Only**

Create/Delete a directory that is 1000 levels deep

Creation and deletion should be separate tests. Call Create / Delete on a simple directory to ensure the code has been compiled before doing the core of the test. Tests should be in the performance test project in System.IO.FileSystem.

**Comment by ViktorHofer** [comment]
Jeremy do we need this for 2.1? If yes I will add some.

**Comment by JeremyKuhne** [comment]
@ViktorHofer If you have time for it, please take it. If not, move it to future please. :)
