### ISSUE TITLE
BigRational

### ISSUE THREAD

**Issue by dharmatech** [dotnet/corefx#2376]
The BCL project included a BigRational type:

http://bcl.codeplex.com/releases/view/42782

The code seems to be released under the [Microsoft Public License](http://bcl.codeplex.com/license). Would there be any license related issue around including BigRational in corefx?

It looks like it's also available on [NuGet](https://www.nuget.org/packages/BigRationalLibrary/).

There's also a Rational type in [Solver Foundation](https://msdn.microsoft.com/en-us/library/microsoft.solverfoundation.common.rational(v=vs.93).aspx), but the code doesn't appear to be freely available.

**Comment by mellinoe** [comment]
I'm not familiar with this, as it was done a good while before I started on the team. I doubt there would be any problems if we wanted to try to bring some of the code forward or adapt parts of it, but then again I'm not sure who was responsible for creating it in the first place. Does anyone have more context regarding this project?

**Comment by dharmatech** [comment]
Hey Eric. It also seems to be available on NuGet: [BigRationalLibrary](https://www.nuget.org/packages/BigRationalLibrary/).

@mellinoe

**Comment by mellinoe** [comment]
@davidfowl 

Do you have any more information about this library? Just asking because you are listed as an owner, although the last package was published 4 years ago.

**Comment by ellismg** [comment]
I believe this was @joshfree's baby when we put the source out there to start with.  Josh, do you know what the plan for the stuff there is?  Is it something that makes sense to re-license as MIT and pull into CoreFXLabs?

**Comment by davidfowl** [comment]
@mellinoe This was something the BCL team did a while back and I helped publish it to nuget :smile:

**Comment by joshfree** [comment]
@ellismg @davidfowl I don't think there's much value in the type as-is; It's bare bones - I wrote it over a weekend a long time ago just for fun; and it was never meant to ship on NuGet.  If @mellinoe or anyone else is interested in finishing the type then we can put it on corefxlab

**Comment by mellinoe** [comment]
Right now I think it's fair to say that we don't have any concrete plans to port this over to corefx. If you feel that there's a scenario you'd like to have this functionality for, please open a new issue and we can talk about the necessary shape of the library there, use cases, etc, perhaps using this old BigRational type as a starting point.

**Comment by dharmatech** [comment]
There's also the [Rational Structure](https://msdn.microsoft.com/en-us/library/microsoft.solverfoundation.common.rational(v=vs.93).aspx) that comes as part of the Microsoft Solver Foundation. That one looks more polished, however, the source doesn't appear to be available under a free license.

**Comment by JimBobSquarePants** [comment]
@mellinoe It's a shame this isn't implemented. It'd be useful for parsing certain EXIF properties in Jpeg files.  https://github.com/JimBobSquarePants/ImageProcessor/pull/357/files#r58133502

**Comment by dharmatech** [comment]
[Symbolism](https://github.com/dharmatech/Symbolism) is another library that currently has to roll its own basic rational numbers.
