### ISSUE TITLE
Test failed: System.Net.WebSockets.Client.Tests.SendReceiveTest / SendReceive_VaryingLengthBuffers_Success

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#23765]
## Types of failures

Few of variants on Linux and Mac:

```
System.OperationCanceledException : Aborted
---- System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'SslStream'.

System.OperationCanceledException : The operation was canceled.
---- System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'SslStream'.

System.OperationCanceledException : The operation was canceled.
---- System.IO.IOException : Unable to transfer data on the transport connection: Operation canceled.
-------- System.Net.Sockets.SocketException : Operation canceled
```

Windows:
```
System.OperationCanceledException : The operation was canceled.
```

## History of failures (before test disabled on 2017/9/2)

Day | Build | OS
-- | -- | --
8/1 | 20170801.01 | Ubuntu17.10
8/1 | 20170801.02 | Ubuntu17.10
8/1 | 20170801.03 | Ubuntu17.10
8/2 | 20170802.01 | Ubuntu17.10
8/4 | 20170804.01 | Ubuntu14.04
8/4 | 20170804.01 | Ubuntu17.10
8/4 | 20170804.01 | Win8.1
8/24 | 20170824.01 | RedHat73
8/24 | 20170824.01 | Fedora26
8/30 | 20170830.01 | OSX10.12
9/2 | 20170902.01 | RedHat72
9/2 | 20170902.02 | Fedora26
9/2 | 20170902.02 | RedHat73
9/3 | 20170903.01 | RedHat73
9/3 | 20170903.01 | Ubuntu16.04
9/3 | 20170903.01 | Centos73
9/3 | 20170903.01 | Debian87
9/3 | 20170903.01 | RedHat72

# Original report

Test failed during PR run:
https://mc.dot.net/#/user/davidsh/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/169daaad2062ab623fdafa738c3fdbc778d3652e

Unhandled Exception of Type System.OperationCanceledException
Message :
System.OperationCanceledException : The operation was canceled.
---- System.IO.IOException : Unable to transfer data on the transport connection: Operation canceled.
-------- System.Net.Sockets.SocketException : Operation canceled

**Comment by caesar1995** [comment]
Have run the test 500 times on local Windows 10 machine. No failure. The previous stack trace is too old, which cannot reflect which code path results in this failure.

Next step:

Enable the test [PlatformSpecifict: Windows], to see if it fails in CI. If it fails, I can investigate further.

**Comment by caesar1995** [comment]
No report since I enable the test on Windows 2 weeks ago.

**Comment by caesar1995** [comment]
Have run the test 200 times locally on Ubuntu VM, no failure. Will enable the test.

**Comment by stephentoub** [comment]
Re-enabled in https://github.com/dotnet/corefx/pull/28106.
