### ISSUE TITLE
HttpClient test failed: RequestVersion20_ResponseVersion20IfHttp2Supported

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#23770]
Test failed during PR run:
https://mc.dot.net/#/user/davidsh/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/169daaad2062ab623fdafa738c3fdbc778d3652e

RequestVersion20_ResponseVersion20IfHttp2Supported(server: https://http2.akamai.com/) (Linux)
Unhandled Exception of Type System.Net.Http.HttpRequestException
Message :
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.CurlException : Operation was aborted by an application callback
-------- Assert.Equal() Failure
Expected: PartialChain
Actual:   NotSignatureValid

**Comment by Priya91** [comment]
This is a dupe of #23037

**Comment by davidsh** [comment]
Duplicate of #23037.
