### ISSUE TITLE
BinaryFormatter has inconsistency when handling assembly names of core runtime types

### ISSUE THREAD

**Issue by CXuesong** [dotnet/corefx#23785]
It seems that in .NET Framework, `BinaryFormatter` will only store the `Type` name without assembly name when the `Type` is in `mscorlib`. This can be inferred from the [source code of `ObjectWriter.GetAssemblyId`](http://referencesource.microsoft.com/#mscorlib/system/runtime/serialization/formatters/binary/binaryobjectwriter.cs,1356). However, in .NET Core, there are actually two assemblies involved. See the source below
https://github.com/dotnet/corefx/blob/2443b0d5f2a25f9c619aff9dca8ec2625eba1c96/src/System.Runtime.Serialization.Formatters/src/System/Runtime/Serialization/Formatters/Binary/BinaryObjectWriter.cs#L987-L992

The two assemblies, as defined in the follow
https://github.com/dotnet/corefx/blob/87f4f3290ec7b2fc9418cf9c8bf9fbfd0cd7c485/src/System.Runtime.Serialization.Formatters/src/System/Runtime/Serialization/Formatters/Binary/Converter.cs#L34-L42

are, in effect

```
s_urtAssembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
s_urtAlternativeAssembly: System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
```

When de-serializing, `BinaryParser.ReadObjectWithMapTyped` will determine whether the assembly id is 0, and if so, it will use the default assembly as mentioned above
https://github.com/dotnet/corefx/blob/2443b0d5f2a25f9c619aff9dca8ec2625eba1c96/src/System.Runtime.Serialization.Formatters/src/System/Runtime/Serialization/Formatters/Binary/BinaryParser.cs#L430-L433

The problem is, the object parser just defaults the assembly to `mscorlib`, so for some types, e.g. `System.RuntimeType`, which is defined in `System.Private.Corelib`, will not be found, and eventually cause a `TypeLoadExceptionHolder` [instantiated here](https://github.com/dotnet/corefx/blob/87f4f3290ec7b2fc9418cf9c8bf9fbfd0cd7c485/src/System.Runtime.Serialization.Formatters/src/System/Runtime/Serialization/Formatters/Binary/BinaryObjectReader.cs#L240-L246).

By the way, I am just trying to unofficially port BotBuilder SDK to .NET Core 2.0. It relies on the serialization of `Delegate`s, which amounts to the serialization of `Type`, `MemberInfo`, etc. I tried to use `ISerializationSurrogate` to hack the formatter, making it support more object types, but when trying to surrogate the deserialization of `RuntimeType`, my `ISerializationSurrogate.GetSurrogate` will just receive a `Type` of `TypeLoadExceptionHolder`. This is just suprising. Though I am now using `SerializationInfo.SetType` and  `IObjectReference` to workaround the problem, I'm still curious. Is this behavior is by design or not? Thank you.

Update: Well, does this have something to do with `System.RuntimeType` that it doesn't have `[TypeForwardedFrom]` attribute?

**Comment by danmosemsft** [comment]
@viktorhofer

**Comment by ViktorHofer** [comment]
> The problem is, the object parser just defaults the assembly to mscorlib, so for some types, e.g. System.RuntimeType, which is defined in System.Private.Corelib, will not be found, and eventually cause a TypeLoadExceptionHolder instantiated here.

Correct. Because it searches for that type in our mscorlib.dll façade which only contains the following list of types (typeforwards): https://github.com/dotnet/corefx/blob/master/src/shims/manual/mscorlib.forwards.cs#L7

To support serialization of `System.RuntimeType`, the following steps are required:
1. A TypeForwardedFrom attribute here https://source.dot.net/#System.Private.CoreLib/src/System/RtType.cs,73: `[System.Runtime.CompilerServices.TypeForwardedFrom("mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089")]`
**This is required so that the typeforward which is created in step 2 can be resolved. Also it is needed for serialization so that the attributed QualifiedAssemblyName is used instead of S.P.Corelib. Without it a serialized RuntimeType wouldn't be abled to be resolved in .NET Framework because there is no S.P.Corelib.**
2. A manual typeforward entry here https://github.com/dotnet/corefx/blob/master/src/shims/manual/mscorlib.forwards.cs#L7: `[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.RuntimeType))]`
**The binary formatter first tries to find the type in mscorlib.dll. As we don't use that anymore we have a ref assembly for it (shim) which just typeforwards all public types and the ones in the linked file which are internal to the corresponding implementation in .NET Core. Most of them go to System.Private.Corelib. In our case it type forwards System.RuntimeType from mscorlib.dll to System.Private.Corelib.**
3. Mark the type as serializable (optional if you use a ISerializationSurrogate)

> Is this behavior is by design or not?

Yes it is by design as we don't support serialization of System.RuntimeType.

**Comment by ViktorHofer** [comment]
By the way. That's the repro for it:

Netfx:
```csharp
var runtimeType = typeof(string).GetType().GetType();

using (var memoryStream = new System.IO.MemoryStream())
{
    var binaryFormatter = new System.Runtime.Serialization.Formatters.Binary.BinaryFormatter();
    binaryFormatter.Serialize(memoryStream, runtimeType);
    string serializedRuntimeTypeBase64 = System.Convert.ToBase64String(memoryStream.ToArray());
}
```

serializedRuntimeTypeBase64:
```AAEAAAD/////AQAAAAAAAAAEAQAAAB9TeXN0ZW0uVW5pdHlTZXJpYWxpemF0aW9uSG9sZGVyAwAAAAREYXRhCVVuaXR5VHlwZQxBc3NlbWJseU5hbWUBAAEIBgIAAAASU3lzdGVtLlJ1bnRpbWVUeXBlBAAAAAYDAAAAS21zY29ybGliLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OQs=```

Core:
```csharp
byte[] raw = System.Convert.FromBase64String(serializedRuntimeTypeBase64);
var binaryFormatter = new System.Runtime.Serialization.Formatters.Binary.BinaryFormatter();
using (var serializedStream = new System.IO.MemoryStream(raw))
{
    binaryFormatter.Deserialize(serializedStream);
}
```

**Comment by CXuesong** [comment]
I see. Thank you @ViktorHofer !

Actually it is reasonable for the `TypeLoadExceptionHolder` to be instantiated for `RuntimeType` because it is not intended to be serialized. Still, it causes surprise because apparently you can serialize a `SerializationInfo` whose nominal Type is `RuntimeType` without any problem, but later you cannot de-serialize it, the serializer telling you 
```
SerializationException:“Unable to load type System.RuntimeType required for deserialization.”
```
IMO it might be better if the exception description can show us the assembly name, such as
```
SerializationException:“Unable to load type System.RuntimeType from mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 required for deserialization.”
```
This will expose at an earlier time that the serializer is trying to find a type in the wrong assembly.

And it could be better if an `SerializationException` would be thrown for (nominal) types that is in `System.Private.CoreLib` but does not have `[TypeForwardedFromAttribute]`, because in this case they are destined to be missing during deserialization.

**Comment by CXuesong** [comment]
For one more reference, [here](https://gist.github.com/CXuesong/a29e8c126db96343e5948d67eb6010db#file-coreserializationtest-cs) is my code for problem reproduction.

On `net462`
```
Test for surrogate: System.RuntimeType
System.String      System.RuntimeType   AssemblyNamFullName   Kmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Test for surrogate: System.RuntimeType
Test for surrogate: System.RuntimeType
Test for surrogate: System.RuntimeType
Deserialized: System.String
```
On `netcoreapp2.0`
```
Test for surrogate: System.RuntimeType
System.String      System.RuntimeType   AssemblyNamFullName   YSystem.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
Test for surrogate: System.Runtime.Serialization.TypeLoadExceptionHolder

Unhandled Exception: System.Runtime.Serialization.SerializationException: Unable to load type System.RuntimeType required for deserialization.
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at CoreSerializationTest.Program.Laundry[T](T graph, IFormatter formatter) in Program.cs:line 29
   at CoreSerializationTest.Program.Main(String[] args) in Program.cs:line 18
```

**Comment by ViktorHofer** [comment]
Thanks for the suggestions. I'm not sure if we want to change any exceptions as they would then differ with full .NET Framework. We backported binary serialization for compat reasons but encourage customers to shift to other serialization frameworks which operate on the public API surface (security concerns).

But i think we could at least refine the exception message as you suggest :)

> Still, it causes surprise because apparently you can serialize a SerializationInfo whose nominal Type is RuntimeType without any problem, but later you cannot de-serialize it, the serializer telling you

You can serialize a SerializationInfo object? We didn't mark that as serializable: https://source.dot.net/#System.Private.CoreLib/src/System/Runtime/Serialization/SerializationInfo.cs,26. Or do you mean with your custom serialization surrogate? If yes then the TypeForwardedFrom attribute is the reason why it can't deserialize it as you stated. Instead of doing a string comparison we thought about using Type.GetType() to probe through mscorlib and System.Private.Corelib but the performance implications were to high... (~30% regressions).

It seems like with our current model we don't support custom serialization surrogates or other workarounds very well.

**Comment by CXuesong** [comment]
@ViktorHofer 
> You can serialize a SerializationInfo object? We didn't mark that as serializable: 

Oh I didn't make it clear. I mean you can either leave `SerializationInfo.ObjectType` unchanged in `ISerializationSurrogate.GetObjectData` , in this case, leaving it as `RuntimeType`, or you can change `ObjectType` via `SetType(Type)`. In both cases the data contained in `SerializationInfo` will be _written into the stream_ without any problem, but when _reading from the stream_, for the former case, there would be `TypeLoadExceptionHolder` instantiated. I'm not going to `BinaryFormatter.Serialize` the `SerializationInfo`, of course 😄 

> I'm not sure if we want to change any exceptions as they would then differ with full .NET Framework.

Well, I haven't thought of the behavioral identity with .NET Framework before… So yes, now I see the issue with extra SerializationException here. I agree that usage of `BinaryFormatter` should be limited to compatibility-related areas, and that's exactly what I am doing…

Anyway, now I will just use `IObjectReference` to fix this type-load problem.

Finally, one more question: is it for the same compatibility consideration that many corefx/coreclr types "implement" `ISerializable` with `PlatformNotSupportedException` and are not marked with `[Serializable]`? (e.g. `Regex`)

**Comment by ViktorHofer** [comment]
> I'm not going to BinaryFormatter.Serialize the SerializationInfo, of course 😄

Good 😄

> Finally, one more question: is it also the compatibility consideration (with .NET Framework) that many corefx/coreclr types "implement" ISerializable with PlatformNotSupportedException and are not marked with [Serializable]? (e.g. Regex)

You nailed it. We don't support serialization of these types anymore but left the interface on it so that we don't break customer code where we just cast to ISerializable but don't use its implementation.

**Comment by CXuesong** [comment]
Okay, now I see. Then I will close this issue 😄

Thank you, Viktor!

**Comment by ViktorHofer** [comment]
We are currently discussing what should be changed in the next servicing release. We will probably add some exception types to the list. Any feedback from your side to summarize this thread?

**Comment by CXuesong** [comment]
From my current situation, it's nice to have `Delegate`, (and subsequently) `Type`, and `MemberInfo` serializable. But for me it's not a necessity, because I can always (regardless of the robustness) use surrogates to make them somewhat "serializable". Then problem I brought up in this issue is about reduce the "bewilderment" when we are implementing the surrogates. In this case, either making the `BinaryFormatter` correctly resolves (i.e. Call `ISerializationSurrogate` with correct `Type`) `RuntimeType`, or tell the users about such limitations, is enough, so the users will directly head to the `IObjectReference` approach. Otherwise they might have to plunge into the corefx/coreclr code to find out what have gone wrong (for me it's not a bad thing, though).

It's also nice to have `Regex` serializable. After all, `Newtonsoft.Json` has their built-in [`RegexConverter`](https://github.com/JamesNK/Newtonsoft.Json/blob/42ccb6b1c0fdf1c9d09fa21d0c93cbe70401a974/Src/Newtonsoft.Json/Converters/RegexConverter.cs#L38).

And it suddenly struck me that perhaps some `ISerializationSurrogate` implementations could be made available as some NuGet packages, so they can be maintained separately, and for compatibility problems, the developers could plug-in the surrogates and the legacy code will just work.

As for other types, such as `Exception`-derived classes and `Attribute`-derived classes, from my perspective I see no much benefit other than enabling them to cross `AppDomain` boundaries. If someone wants to send the Exception to other machine/process by hand, they may well send the information contained in it (e.g. Message, StackTrace, etc.), so is for persistence.

p.s.
[Here](https://github.com/CXuesong/BotBuilder.Standard/blob/netcore2/CSharp/Library/Microsoft.Bot.Builder.Standard/Fibers/NetStandardSerialization.cs) is my surrogates for the types mentioned above, for reference. And I have to say, my `MemberInfoSerializationSurrogate` is rather rudimentary.
