### ISSUE TITLE
System.Net.Http.StreamContent.ReadOnlyStream size awareness

### ISSUE THREAD

**Issue by Warpten** [dotnet/corefx#23788]
Streams typically returned by `HttpClient` (`StreamContent.ReadOnlyStream` - I am **explicitely** trying not to use buffered streams, so `MemoryStream` is out of question) are neither size nor position-aware.

https://github.com/dotnet/corefx/blob/6bf1e7c3032d3c24d5a41bbd880549ef4a8de2da/src/System.Net.Http/src/System/Net/Http/HttpContent.cs#L248-L275

This is for obvious reasons: the `Content-Length` header is not actually required to be sent at all times (see [RFC](https://tools.ietf.org/html/rfc7230#section-3.3.3)). I guess I could return a wrapped stream which exposes `Content-Length`, if sent by the server.

~Additionally - because I'm not sure it's worth adding another issue for, when this is more of a question as of now than an actual "pull request poll", `System.IO.Compression.DeflateStream` does not support seek operations. Now, I will be the first to admit I don't exactly know how the deflate algorithm works. I was just curious of the reasoning behind that, since it is already memory-backed, and surely it should be easy enough to implement forward-seeking, by just quickly glancing at the current implementation. `SeekOrigin.End` may become problematic with `StreamContent.ReadOnlyStream` in regards to the fact that it does not expose the complete amount of bytes returned by the server, or would do so in an unusual way (regarding the point above).~
>Removed because actual code suggests it works a little differently.

I guess my question here is: is adding a way to tell actual content-length inside a network stream something worth creating a pull request for? ~Additionally, is it worth trying to implement seek operations in `DeflateStream` ?~

**Comment by Warpten** [comment]
This is a quick and dirty polyfill I threw together that wraps around a stream and behaves like a stream that can be seeked **forward**. For backwards seeking, it would probably be advisable to implement a backing MemoryStream and read from it when going back - assuming the underlying stream cannot seek backwards. Since I'm mostly using network streams, and did not need to seek backwards, I skipped that part.

https://gist.github.com/Warpten/250a6acfb82195022a0d89912502211e

**Comment by Priya91** [comment]
@Warpten What's the issue here? I don't understand what the ask is for?

**Comment by karelz** [comment]
No response, closing.
Feel free to reopen when there's more info/follow up. Thanks!
