### ISSUE TITLE
NullReferenceException when setting TcpClient.SendTimeout

### ISSUE THREAD

**Issue by fitzchak** [dotnet/corefx#23790]
We use netstandard2.0.

See: http://issues.hibernatingrhinos.com/issue/RavenDB-8440

System.NullReferenceException occurred
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Net.Sockets.TcpClient.set_SendTimeout(Int32 value)

![image](https://user-images.githubusercontent.com/629734/30052131-33ef6d30-922d-11e7-89aa-cb8b30cd266a.png)

![image](https://user-images.githubusercontent.com/629734/30052139-39982506-922d-11e7-80a9-0e3068ef4e45.png)

**Comment by stephentoub** [comment]
`TcpClient._clientSocket` is `null`.  How was this TcpClient instance created?  Is some code somewhere setting `client.Client = null;`?  Is this code running after the TcpClient has been disposed?

**Comment by ayende** [comment]
This was created a few lines above this code, and there wasn't anything that would dispose it or should set it to null.
We have moved the code to be a bit closer and we'll check this again, I suspect that it is some rare loop causing us to access this after the dispose, though.

If that is the case, can this throw `ObjectDisposedException` ?
