### ISSUE TITLE
System.IO.Packaging attempt to delete non-existent property fails

### ISSUE THREAD

**Issue by kenleese** [dotnet/corefx#23795]
An attempt to delete a package property that was not previously defined fails in subsequent Dispose().

Lines 481-489 in [http://referencesource.microsoft.com/#WindowsBase/Base/MS/Internal/IO/Packaging/PartBasedPackageProperties.cs,2e226d8b23d00ee4](url) have no equivalent implementation in the corefx implementation https://github.com/dotnet/corefx/blob/release/2.0.0/src/System.IO.Packaging/src/System/IO/Packaging/PartBasedPackageProperties.cs#L400 

A repro is available in https://github.com/OfficeDev/Open-XML-SDK/issues/235

**Comment by stephentoub** [comment]
cc: @EricWhiteDev
