### ISSUE TITLE
Add tests for double/single GetHashCode and Equals invariant fix.

### ISSUE THREAD

**Issue by mazong1123** [dotnet/corefx#23792]
While fixing https://github.com/dotnet/coreclr/issues/6237 , we need to add tests to ensure:

- All `System.Double.NaNs` have same hash code.
- All `System.Single.NaNs` have same hash code.

So that we can keep the `Equals` -> `GetHashCode` invariant.

**Comment by danmosemsft** [comment]
@mazong1123 any interest in a PR so we can close this? Sounds small.

**Comment by mazong1123** [comment]
@danmosemsft The tests is for https://github.com/dotnet/corefx/pull/23793 which has been closed as we have to wait for jit compiler enhancement to mitigate the performance issue. I'm fine if this issue been closed until we https://github.com/dotnet/corefx/pull/23793 be re-opened.

**Comment by danmosemsft** [comment]
Ok thanks @mazong1123
