### ISSUE TITLE
Come up with a proposal for using given-when-then model in corefx unit tests

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/corefx#2379]
http://martinfowler.com/bliki/GivenWhenThen.html

**Comment by davidsh** [comment]
Personally I like the "Arrange, Act, Assert" model:  http://xp123.com/articles/3a-arrange-act-assert/

In particular, our team likes this book for designing good unit tests:
"The Art of Unit Testing"
http://www.amazon.com/The-Art-Unit-Testing-examples/dp/1617290890/ref=dp_ob_title_bk

It has helped us think about what a good unit test is and how to write them correctly.

/cc @CIPop @SidharthNabar

**Comment by Sridhar-MS** [comment]
I have been reading about Arrange-Act-Assert model too. Though I have not personally used it. I would love to see some samples.

**Comment by Sridhar-MS** [comment]
GWT model is very restrictive for corefx unit testing especially when it comes to Theory based tests with InlineData or MemberData. Hence closing this issue. There will be ongoing efforts to produce a unified test-naming convention for corefx tests.
