### ISSUE TITLE
Converge TimeZoneInfo sources (coreclr & corert)

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#23804]
This is a reminder to finish the convergence of the TimeZoneInfo source files.

WIP here: https://github.com/ViktorHofer/coreclr/tree/TimeZoneInfoConverganceBackup

When finished, remove this line https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Serialization.Formatters/tests/BinaryFormatterHelper.cs#L139 and update the blobs.

**Comment by ViktorHofer** [comment]
cc @tarekgh

**Comment by jkotas** [comment]
> finish the convergence of the TimeZoneInfo source files.

This is done now. https://github.com/dotnet/coreclr/pull/15926 is the primary PR.

> When finished, remove this line 

This still needs to be done.

**Comment by ViktorHofer** [comment]
Thanks, I will do the remaining work in the binary serialization test project.
