### ISSUE TITLE
Updates to RID graph are clunky and error-prone

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#23807]
Updating the file https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json is clunky and error prone.

Now ideally RIDs would have more strongly-typed semantics that have continuous (eg: version) or discrete (eg: architecture) values, along with relationships and precedence between them.  Today we handle these by convention.  At runtime the RID is just an opaque string that's related to other opaque strings.

We should create a smaller representation of the RID graph and codify all of our conventions into a some code generation task.

For example:
OSFamily : linux
Parent OSFamily: unix
Versions: none
Architectures: x64, x86, arm, armel, arm64
Additional qualifiers: none

OSFamily : rhel
Parent OSFamily: linux
Versions: 6, 7, 7.0, 7.1, 7.2, 7.3, 7.4
Architectures: x64
Additional qualifiers: none

We can also have a pass-through that merges runtime.json fragments for things we don't want to represent with a generator.

Given this smaller set of information we should be able to generate the same RID graph we have today but in a less-error prone way. 

/cc @Petermarcu

**Comment by ericstj** [comment]
I've started working on this.

Buildtools task is here:
https://github.com/ericstj/buildtools/commit/5d83d87bdafaa015689838a90c2f27876726f9f9

Sample consumption in corefx is here (WIP):
https://github.com/ericstj/corefx/commit/eeccb107b01f332448fc7bb6b6493e771173ab52

I wanted to check in generated runtime.json so we have visibility into what the generator is doing.

I'm very surprised by the number of bugs we have in the current runtime.json: inconsistent heirarchies, misspellings, missing intermediates.

I still need to figure out how to model a couple things: 
1. `ol` and `centos` have a *parallel* import behavior with `rhel` RIDs of the same version.
2. deterime if we care to define *floor* versions for architectures and qualifiers (EG: to constrain arm to only win8 and later, constrain arm64 to only win10 and later).

For 2 I'm leaning towards just saying *don't care* and creating the RIDs even though we don't use them.

/cc @weshaggard @eerhardt

**Comment by ericstj** [comment]
Ok, I was able to fix both of these as well as some issues that @eerhardt pointed out.

The remaining discrepancies with what existed before are primarily for corert which appears to have had a bunch of type-os and was out of date, a couple of missing imports from new additions (eg: android), and a couple consistency issues with win*aot.  The only ones that are concerning are the aot ones and to validate they aren't an issue I'll restore the latest public UWP packages with and without this change to ensure we get the same result.

Here's are the new commits:
https://github.com/ericstj/buildtools/commit/b627267a708988ae7371ade661cf729df58fd7e7
https://github.com/ericstj/corefx/commit/bccfcad2cc4ef97ce7782fe6f643facd6f0e3ca5

I haven't submitted PRs yet because I need to polish the code, but would appreciate any feedback folks have on the tooling / naming.

I think I should probably update the readme as well.

**Comment by eerhardt** [comment]
I think the naming and the tooling looks good.  My only question is if you'd want to split out all the item "data" into a separate .props file to isolate it, and keep it cohesive.

> I think I should probably update the readme as well.
+1

**Comment by ericstj** [comment]
> split out all the item "data" into a separate .props file

Yeah, I was planning to do that anyhow in order to serve as a good input/output of the target.  I'm also going to include the target in the build.  I know modifying source during build is a no-no, but here I think the benefit of having this checked in over-rides that, and sequencing it in the build makes it one less thing for people to have to read the docs in order to understand.

**Comment by bording** [comment]
@ericstj Would it make sense to include additional distros in the RuntimeGroup data to cover everything listed in https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0-supported-os.md as part of this change, or should those come as a separate PR after this is merged?

**Comment by ericstj** [comment]
Let's make that separate.  I want to make this change purely about the tooling.
