### ISSUE TITLE
ReadOnlySpan and Span must be `readonly` structs.

### ISSUE THREAD

**Issue by VSadov** [dotnet/corefx#23809]
ReadOnlySpan and Span do not have any mutable fields and should be `readonly` just from the principle of least privilege.

Also, being not readonly makes the code like the following an error:

```C#
            Span<int> stackAllocated = stackalloc int[100];
            Span<int> returnableSpan = new int[100];

            // error, compiler thinks that CopyTo could just do 'this = other'
            // there would be no danger if Span<T> was `readonly`
            returnableSpan.CopyTo(stackAllocated);
```

Also see: https://github.com/dotnet/roslyn/issues/21911

For now I can assume that ReadOnlySpan and Span will be `readonly` and specialcase them to be `readonly` regardless of annotations. 
That would fix https://github.com/dotnet/roslyn/issues/21911 temporarily. 

Depending on the compiler used they should be either

```C#
public readonly ref struct Span<T> { ... }
```
or 

```C#
[S.R.CS.ReadOnlyAttribute]
[S.R.CS.IsByRefLikeAttribute]
public struct Span<T> { ... }
```

**Comment by VSadov** [comment]
CC @jkotas @stephentoub

**Comment by stephentoub** [comment]
cc: @KrzysztofCwalina, @ahsonkhan

**Comment by KrzysztofCwalina** [comment]
Should the same be done to Memory<T> and ReadOnlyMemory<T>?

**Comment by VSadov** [comment]
@KrzysztofCwalina Re: Memory and ReadOnlyMemory   -  if they are large (more than 2-4 pointers in size) immutable structs, then it would not hurt making them `readonly` just for possible perf improvements.

**Comment by ahsonkhan** [comment]
> if they are large (more than 2-4 pointers in size) immutable structs, then it would not hurt making them `readonly` just for possible perf improvements.

Memory/ReadOnlyMemory are 3 pointers in size ([an object and two ints](https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/Memory.cs#L24-L26)). So, they are not larger than 2-4 pointers in size.
