### ISSUE TITLE
PlatformDetection.IsNetfx...() returns wrong results on netfx471

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#23806]
My machine is running on an RS3 build which includes .NET Framework 4.7.1 (4.7.2552.0) Preview. If I run .NET Core tests with TargetGroup=netfx which make use of the helper method `PlatformDetection.IsNetfx471OrAbove()` I get failures because the function returns true (because it checks the version table: https://github.com/dotnet/corefx/blob/master/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.cs#L104) but in fact uses the 4.6.1 for it (spoke to @weshaggard).

In my case I tried to run serialization tests for ValueTuples which aren't serializable in .NET Framework < 4.7.1: https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Serialization.Formatters/tests/BinaryFormatterTestData.cs#L669

```
Using D:\git\corefx\bin\testhost\netfx-Windows_NT-Debug-x64\ as the test runtime folder

System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateBasicObjectsRoundtrip(obj: (), assemblyFormat: Full, filterLevel: Full, typeFormat: TypesAlways) [FAIL]
        System.Runtime.Serialization.SerializationException : Type 'System.ValueTuple' in Assembly 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' is not marked as serializable.
```

I'm not sure why we ever needed the version table when we always run the tests against a specific netfx version?

cc @safern @danmosemsft

**Comment by safern** [comment]
> I'm not sure why we ever needed the version table when we always run the tests against a specific netfx version?

We build against a specific netfx version but we run them against the latest installed netfx version in the running computer.

**Comment by ViktorHofer** [comment]
> but we run them against the latest installed netfx version in the running computer.

but that means that e.g. ValueTuples should be serializable and I shouldn't get the error message, right? I check my local assemblies with ILSpy and they contain the serialization attribute. Therefore I'm assuming we are not running the tests against the newest installed version...

**Comment by safern** [comment]
Then it doesn't seem to be an issue with `PlatformDetection.IsNetFx...()` as it uses `RuntimeInformation.FrameworkDescription` to get the running framework version. Could you please confirm what version `RuntimeInformation.FrameworkDescription` returns when you run the tests for netfx?

**Comment by ViktorHofer** [comment]
Yes, already checked: 4.7.2552.0 which is 4.7.1.

**Comment by safern** [comment]
> Yes, already checked: 4.7.2552.0 which is 4.7.1. Maybe I'll check with ProcessExplorer which assemblies are definitely loaded when running the tests with netfx target group.

Then `PlatformDetection.IsNetFx..()` is behaving as expected as 4.7.1 maps to 4.7.2500.0 or greater.

**Comment by ViktorHofer** [comment]
You are absolutely right. Sorry again for the noise.
