### ISSUE TITLE
List<T>.Reverse should not call Array.Reverse, or add Array.Reverse<T> method and call it.

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#23815]
From analysis of real profiles:

List<T>.Reverse should not call Array.Reverse, or add Array.Reverse<T> method and call it.
Here is List<T>.Reverse implementation:
```c#
// System.Collections.Generic.List<T>
public void Reverse(int index, int count)
{
    ..
    Array.Reverse(._items, index, count);
    _version++;
}
```
Notice Array.Reverse is not a generic method because there is no `Array.Reverse<T>` method. It's implementing using boxing for custom struct and GetValue/SetValue calls. Super expensive. The whole JToken.get_Path method is expensive and it building a new string every time through StringBuilder.

**Comment by danmosemsft** [comment]
Scratch that, we do have `Reverse<T>`. I'll tag as port consider at least.

**Comment by JonHanna** [comment]
#2352 dealt with by dotnet/coreclr#7132
