### ISSUE TITLE
HttpClient virtual SendAsync is not properly called

### ISSUE THREAD

**Issue by CoolDadTx** [dotnet/corefx#23812]
HttpClient has several overloads of SendAsync. Only the one that accepts a request and cancellation token is marked virtual. Looking at the implementations they all call the version that accepts the request, option and cancellation token. Inside this method it ultimately calls the SendAsync version that accepts a request and cancellation token but from the base class. The net result is that deriving from HttpClient and overriding the only virtual implementation of SendAsync doesn't impact anything unless you happen to call the version that accepts the given parameters. 

HttpClient should have an overload that can be called to hook into all the methods to allow pre/post request processing. Alternatively the existing implementation should be adjusted such that all the overloads eventually call the overridable implementation that then defers to the base implementation.

```public class MyHttpClient : HttpClient
{
   public override Task<HttpResponseMessage> SendAsync ( HttpRequestMessage request, CancellationToken cancellationToken ) 
   {
     //Will never be called unless code explicitly calls this override
    return base.SendAsync(request, cancellationToken);
   }
}
```

**Comment by davidsh** [comment]
The design of HttpClient is that it isn't meant to be derived from.

Customization involving SendAsync is done by deriving from HttpMessageHandler and DelgatingHandler which has the virtual SendAsync() method.  Then those handlers are passed into HttpClient.

**Comment by davidsh** [comment]
cc: @karel

**Comment by davidsh** [comment]
cc: @karelz

**Comment by davidsh** [comment]
>Here's a link to another reporting of this issue that says to use HttpMessageHandler but then the last comment says it still doesn't work with GetAsync. Has this been resolved?

Regarding #6535, this comment "" was never verified.  As long you create a new derived HttpMesageHandler (i.e. in order to do custom pre and post processing of the request and response), that handler and its SendAsync() method will be used everywhere that any HttpClient SendAsync, GetAsync, etc. method is used.  All convenience methods such as HttpClient.GetAsync, HttpClient.PostAsync all end up calling the handler main SendAsync() method.

**Comment by davidsh** [comment]
The specific problem that was being reported by that individual was that they were deriving from HttpClient which is not the right pattern.  If they had derived a new handler from HttpMessageHandler and passed that handler into HttpClient's constructor, then everything would work as designed.

**Comment by CoolDadTx** [comment]
I'll try and see, thanks. Still think the documentation should be updated to make it clear this class isn't designed to be overridden. Would also call into question why the method was marked as virtual if it wasn't designed to be overridden either.

**Comment by davidsh** [comment]
>Still think the documentation should be updated to make it clear this class isn't designed to be overridden. 

We will update the documentation. Thanks.

>Would also call into question why the method was marked as virtual if it wasn't designed to be overridden either.

HttpClient can be derived from.  But the reasons for doing so are different than when you should create a new handler based on HttpMessageHandler.

HttpClient itself is derived from HttpMessageInvoker which is the base class that calls handler.  HttpClient adds convenience methods and some buffering logic for repsonse content, i.e. HttpCompletionOption enum parameter.  Devs could derive from HttpClient to create new convenience methods, for example.  But they should not derived from it if they want to do pre and post processing of "SendAsync".  That is whn you should create new handlers.

I agree that the documentation should be clarified around this.

cc: @stephentoub @Priya91

**Comment by karelz** [comment]
@CoolDadTx can you please suggest documentation changes as PRs in https://github.com/dotnet/docs repo? Please tag me & @davidsh. Thanks!

**Comment by CoolDadTx** [comment]
Will do

**Comment by karelz** [comment]
FYI: The docs were updated in https://github.com/dotnet/docs/pull/3105
