### ISSUE TITLE
How to use DataTable and DataView in asp.net core 2.0

### ISSUE THREAD

**Issue by sureshkumar1115** [dotnet/corefx#23825]
Hi All,

I have using DataTable (https://blogs.msdn.microsoft.com/devfish/2017/05/15/exploring-datatable-and-sqldbadapter-in-asp-net-core-2-0/) in asp.net core but not work in DataTable (https://apisof.net/catalog/System.Data.DataTable ) and DataView(https://apisof.net/catalog/System.Data.DataView). I have already referred System.Data.Common, Version=4.3 assembly extension.

could you please right me to proper way.

thanks.

**Comment by karelz** [comment]
What exactly doesn't work? Can you please post a small isolated repro?

**Comment by sureshkumar1115** [comment]
Hi Karelz,

thanks for your update.

in our previous source we have process (iterate and process the data in DataTable) using DataView and DataSet in MVC platform but while we have upgrade the dotnet Core 2.0 we have facing the error in DataTable and DataSet. after my analysis the dotnet core 2.0 is support the DataTable. but the **System.Data.Common** assembly does not have support in DataSet and DataTable. but in MVC **System.Data** assembly have support DataSet and DataView support.

can you please assist the any alternative way to iterate, fetch and process the data without using DataView and DataSet.

thanks.

**Comment by karelz** [comment]
Which APIs are missing? Can you provide a list?
Note: I would recommend to use this tool: https://github.com/Microsoft/dotnet-apiport

**Comment by sureshkumar1115** [comment]
Sorry for the late reply,

class list that works perfectly in MVC : 
1. System.Data.DataRow
2.System.Data.DataView
3.System.Data.DataTable

but now in Core 2.0 that classes are not support.

**Comment by sureshkumar1115** [comment]
once I have check and make full upgrade my system to Core 2.0 this issue will resolve now. 
thanks for your response and support @karelz .
