### ISSUE TITLE
Add CancellationTokenRegistration.Token property

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23828]
When registering with a CancellationToken, a common pattern is to then store the resulting CancellationTokenRegistration onto some object for later disposal when the associated asynchronous operation completes.  It's also common to store the original CancellationToken, so that it can, for example, be passed to TaskCompletionSource.TrySetCanceled.  But having to store the CancellationToken in addition to the CancellationTokenRegistration should be unnecessary, as the registration already knows with which CancellationToken it's associated... it just doesn't expose that information.  We should expose it.
```C#
public struct CancellationTokenRegistration
{
    public CancellationToken Token { get; }
    ...
}
```
This property now exists, it's just internal:
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/CancellationTokenRegistration.cs#L44
We should simply make it public.

This will allow us to shrink by a reference-sized field several objects that store the CT in addition to the CTR.

**Comment by tarekgh** [comment]
@stephentoub we have not same but related issue https://github.com/dotnet/corefx/issues/23716. do you think your proposal will affect that issue? or you think we can combine the 2 proposals if we are going to design review it?

**Comment by stephentoub** [comment]
> do you think your proposal will affect that issue?

I believe they are unrelated in both design and implementation.  This is purely about exposing from CancellationTokenRegistration information we already have in order to not have to carry that information around separately.  The other proposal you mention is about adding new functionality to CancellationTokenSource, such that the implementation can queue the invocation of any registered handlers if any exist.

**Comment by terrajobst** [comment]
Approved as proposed.

**Comment by karelz** [comment]
FYI: The API review discussion was recorded - see https://youtu.be/m4BUM3nJZRw?t=4706 (2 min duration)
