### ISSUE TITLE
System.Net.Http httpClient ServerCertificateCustomValidationCallback does not include the intermediate certificates provided by the server

### ISSUE THREAD

**Issue by yoelkohn** [dotnet/corefx#23827]
When we assign a callback to ServerCertificateCustomValidationCallback (SCCVC) (tested on Win7/Win8.1,) the passed "chain" arg only includes the server certificate but no intermediate certs passed by the server. The "chain" only has multiple ChainElements if the server cert is signed by a certificate, intermediate or root, that exists in the local store. If we have a cert signed by an intermediate CA and that cert is chained by the server, even if that CA cert is in turn signed by a root/intermediate CA that exists in the store, the chain will not include any of the intermediate certificates, and will show just the server certificate. In such a case where the root cert exists in the store and the intermediate cert is chained by the HTTPS server, the request will go through successfully when no callback is defined, yet show up in the callback with ChainElements.Count == 1 and SslPolicyErrors != none; which some might find a smidge ironic. 

The following are the current behaviors and the corresponding behavior in the ServerCertificateValidationCallback (SCVC) in .NET Framework which I assume should be the expected behavior here.

1) When the server passes a certificate chain and a given certificate is _different_ to the one in the store for the same CN/SAN, SCCVC gets the store cert, while SCVC (expected) gets the one passed by the server.

2) When the server passes a certificate chain which does not conflict with the store, SCCVC does not get any of the certificates passed to "chain" other than the server cert itself. Expected behavior per SCVC is to have the server intermediate certs passed along and ADDITIONAL certs, only if the final cert is not self-signed, added to the chain where appropriate.

This is preventing us from using httpClient in production. We have our certs signed by an intermediate CA which we cannot install on target systems' local cert stores. Furthermore, we use an internal root CA for testing and we would prefer to compare the CA cert to the final cert in the chain in the validation callback, rather than installing and re-installing certs as test CAs pop in and out of existence.

**Comment by davidsh** [comment]
@bartonjs You'll need to investigate this.  HttpClient just uses whatever crypto give us.

**Comment by bartonjs** [comment]
@yoelkohn Can you provide a repro?  A particular URL I can hit, and what OS you're hitting it from (and what version of .NET Core are you running)?

I just checked the contents of the X509Chain object provided during the callback to https://www.microsoft.com/ and I see the full chain present:

```
SSL Policy Errors: None
Chain:
  CN=www.microsoft.com, OU=MSCOM, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
  CN=Symantec Class 3 Secure Server CA - G4, OU=Symantec Trust Network, O=Symantec Corporation, C=US
  CN=VeriSign Class 3 Public Primary Certification Authority - G5, OU="(c) 2006 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
```

I tried this on Linux (Ubuntu 16.04) and Windows (2012 R2 / 8.1 Server).  Granted, that matches your comment that it works when the certs are present in the store.  But without knowing what sort of failure you're encountering it's not easy to figure out what's going on.

**Comment by yoelkohn** [comment]
@bartonjs I am not encountering a failure as much as the function does not get passed more than one cert. To recreate the problem you can simply delete the intermediate cert (N=Symantec Class 3 Secure Server CA - G4) from your store. Expected behavior is that it should chain the intermediate cert passed by the server and the root from the store and still have no errors, but instead the chain will only contain the sever cert and the corresponding errors. If you were not to call the callback, then the default certification validation _will_ be successful as it does chain it correctly.

Alternatively, you can test against https://i-98000004.ins.blhps.net/. This uses a server chained to an intermediate and a root non-public CA. The validation callback should have all three certs in the chain with SslPolicyError = UntrustedRootDomain. Instead it has just the one.

**Comment by bartonjs** [comment]
On Linux:
```
SSL Policy Errors: RemoteCertificateChainErrors
Chain:
  CN=i-98000004.ins.blhps.net, OU=IT, O=Bellhop Solutions Inc, L=Ramsey, S=New Jersey, C=US
  CN=testintca.blhps.net, O=Bellhop Solutions Inc CA, S=NJ, C=US
  CN=testca.blhps.net, O=Bellhop Solutions Inc CA, L=Ramsey, S=NJ, C=US
```

On Windows I do see the behavior you've reported:

```
SSL Policy Errors: RemoteCertificateChainErrors
Chain:
  CN=i-98000004.ins.blhps.net, OU=IT, O=Bellhop Solutions Inc, L=Ramsey, S=New Jersey, C=US
```

But if I do it with SslStream instead of HttpClient I get the full chain.

@davidsh If SslStream on Windows works and HttpClient on Windows doesn't, it seems to be a problem with how the WinHttpClientHandler is building the chain.

This certificate chain doesn't have an Authority Information Access extension, so Windows can't download the rest of the chain if it doesn't already know about it.  And it looks like the Http copy of BuildChain (https://github.com/dotnet/corefx/blob/46579e40b32f86301363f8e7c7d9637218e243b2/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpCertificateHelper.cs#L17) doesn't pass the rest of the chain context in via the ExtraStore parameter. (Which SslStream does: https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/src/System/Net/Security/SecureChannel.cs#L1018)

So the other certs from the TLS connection need to be pushed into ExtraStore.  I don't know how to get those out of WinHttp.  (It's possible that they've put the leaf cert into a memory store with the rest of the chain, so it might be within pCertContext->hCertStore; or maybe just some other property)

**Comment by davidsh** [comment]
>So the other certs from the TLS connection need to be pushed into ExtraStore. I don't know how to get those out of WinHttp. (It's possible that they've put the leaf cert into a memory store with the rest of the chain, so it might be within pCertContext->hCertStore; or maybe just some other property)

Perhaps this is related to this open issue https://github.com/dotnet/corefx/issues/4473

**Comment by bartonjs** [comment]
Yeah, sounds like the same problem to me.

**Comment by yoelkohn** [comment]
Does anyone know why #4473 has been kicked down the road a couple of times? And whether the current 2.1 milestone is firm-ish?

**Comment by davidsh** [comment]
@yoelkohn I was trying to verify the repro. But it seems this server is no longer listening on port 443:

https://i-98000004.ins.blhps.net/

**Comment by yoelkohn** [comment]
It's back up. Thanks!

Yoel Kohn
SEVP Engineering
Bellhop Solutions
