### ISSUE TITLE
Changes in master with respect to UWP

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#23837]
@JeremyKuhne added System.Memory inbox on UWP with https://github.com/dotnet/corefx/commit/1d3cc0417753bf0a436824abfeff9c3c1712f63f but I don't think that made it to release/uwp6.0.  @JeremyKuhne did you intend to ship that in UWP6?

If not, we should probably make sure it isn't marked as inbox there.  We should also retarget master to something after UWP6 so we don't let things get out of sync (like we did with netcoreapp2.1 and I had to clean up later with https://github.com/dotnet/corefx/pull/23168).  /cc @joperezr @weshaggard

**Comment by danmosemsft** [comment]
It was not intended to ship in UWP6. 
Indeed this edit to packageIndex.json doesn't seem to be in the UWP6 branch:
https://github.com/dotnet/corefx/blob/release/uwp6.0/pkg/Microsoft.Private.PackageBaseline/packageIndex.json#L2245

**Comment by ericstj** [comment]
I understand that.  The problem is that master is still targeting UWP6, which is incorrect.  It should move on to V next so that when we ship NETCore 2.1 we don't accidentally ship things in packages that treat UWP v.next as UWP6.

**Comment by joperezr** [comment]
ok, that makes sense. @danmosemsft @joshfree  have we thought of a version for servicing for UWP? I suppose we could start with uap10.1 for now and once we have a version for RS4 we could move to uap10.0.RS4.0

**Comment by joshfree** [comment]
I'll defer the package versioning to you and Eric.  We can chat about it in our sync up this afternoon.

**Comment by ericstj** [comment]
Note that this isn't about servicing: we aren't servicing out of master.  This is about v.next.

**Comment by JeremyKuhne** [comment]
@ericstj who should this issue belong to? Should the title be "Move master UWP to v.next"?

**Comment by ericstj** [comment]
Ultimately, but I think we should do something sooner tactically.  As it stands right now anything you've changed to make inbox on UWP is completely broken when used there.  Perhaps we should remove those from being inbox in the package index and suppress any other errors that complain about this.
