### ISSUE TITLE
LINQ Concat.ToArray outputs null elements when it shouldn't

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#23833]
From @markples at https://github.com/dotnet/corefx/issues/23680#issuecomment-326906526

---

Here is a repro (from @vuminhle). It seems very specific - reducing the list sizes or changing the construction in various ways loses the repro.

```cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace repro {
    internal class Program {
        private static void Main(string[] args) {
            A[] list = List1().Concat(List2()).Concat(List3()).ToArray();
            foreach (A a in list) {
                Console.WriteLine(a.Value);
            }
        }

        internal static IEnumerable<A> List1() {
            for (var i = 0; i < 4; i++) {
                yield return new A(i);
            }
        }

        internal static IEnumerable<A> List2() {
            return Enumerable.Range(0, 2).Select(v => new A(v));
        }

        internal static IEnumerable<A> List3() {
            for (var i = 0; i < 5; i++) {
                yield return new A(i);
            }
        }

        internal class A {
            public A(int v) {
                Value = v;
            }

            public int Value { get; }
        }
    }
}
```

**Comment by karelz** [comment]
Is that a regression between 1.1 and 2.0?

**Comment by danmosemsft** [comment]
@karelz It is a regression introduced between 1.1 and 2.0.

**Comment by karelz** [comment]
@OmarTawfik @VSadov can you please look into it for 2.0.x servicing?

**Comment by OmarTawfik** [comment]
I'm looking at it now.

**Comment by OmarTawfik** [comment]
@jamesqo this was the same issue as #23680. And I tried with the PR I sent and it produces correct results. Any reason you filed a separate issue?

**Comment by OmarTawfik** [comment]
Please try again against master (my PR is merged now) and close this if you agree.

**Comment by karelz** [comment]
Closing as per info above. @jamesqo if you disagree or have more info, please let us know.
