### ISSUE TITLE
How do I reference corefx libs with net.core 2 app

### ISSUE THREAD

**Issue by letmefree** [dotnet/corefx#23835]
Hi there!
I am happy to write here, thank you all <3!!
Actually I cant understand how can I build a library and use it in to my project. There are not enought info or I cant understand base things.
My steps are:
-0 Add a new "Hello World!" method somewhere System.Collections library
-1 Compile it (use cmd.exe build \src\System.Collections -os=Windows_NT)
-2 Create an empty net.core 2.0 console app then add referece to obtained on prev step dll
-3 Get an error "the reference is invalid or unsupported" (VS 2017 community)

The question is: how can I use compiled libraries (or reference whole projects) from the repo in my net.core 2 projects  ? Where is the trick ?

**Comment by karelz** [comment]
I am not sure if I understand your question correctly, but let me try to give you few pointers:
* You can use latest (daily) builds of .NET Core 2.1 in your app: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md
* Adding new API is rather involved - see some tricks [here](https://github.com/dotnet/corefx/wiki/Contributions#add--expose-api-in-corefx-net-core-only). I don't think we have any steps how to use it directly. Probably using direct DLL reference would be easiest, or using dogfooding described above.

**Comment by weshaggard** [comment]
Closing as there has been no further information. @letmefree if you still have questions please help us better understand the scenario.
