### ISSUE TITLE
Figure out how to provide parameters to unit tests at build/run-time.

### ISSUE THREAD

**Issue by pgavlin** [dotnet/corefx#2383]
The System.Net tests are likely to need this in order to provide some configurability for the servers used during testing.

**Comment by davidsh** [comment]
Reference: https://github.com/dotnet/wcf/search?utf8=%E2%9C%93&q=TestProperties

**Comment by CIPop** [comment]
@davidsh  Regarding the reference above: The only downside that I see is that it adds a dependency on System.Collections.Generic.

A simpler alternative would be a TestConfig.cs file that can be checked in with default values and can be modified easily by executing a script. The downside to my proposal is that it will require writing scripts in Powershell and bash to generate C# code for the configuration. (This is somehow similar to how config.h is working in *NIX environments.)
