### ISSUE TITLE
DiagnosticSource does not install with nuget 2.8.6

### ISSUE THREAD

**Issue by lmolkova** [dotnet/corefx#23843]
DiagnosticSource [pkgproj](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/pkg/System.Diagnostics.DiagnosticSource.pkgproj#L6)  sets MinClientVersion to 2.8.6

```
  <PropertyGroup>
    <!-- we need to be supported on pre-nuget-3 platforms (Dev12, Dev11, etc) -->
    <MinClientVersion>2.8.6</MinClientVersion>
  </PropertyGroup>
```

However nuget 2.8.6 does not support packages with netstandard target.: https://github.com/NuGet/Home/issues/3131

Minimum version that supports them is 2.12.

The same problem is relevant for other packages that have 2.8.6 specified: https://github.com/dotnet/corefx/search?q=minClientVersion&type=Code&utf8=%E2%9C%93

Please advise what is the best way to fix that. Is there some default setting for minClientVersion?

**Comment by karelz** [comment]
@weshaggard @ericstj can you please comment?

**Comment by ericstj** [comment]
Here are our defaults:
https://github.com/dotnet/buildtools/blob/0d5177dfbcef15a7d20aaf759e84c421df7216fd/src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets#L63-L66

Some packages chose different defaults because they needed to work for existing customers using TFMs like net45 or portable-a+b+c which were supported by 2.8.6.  Typically NuGet will just ignore TFMs that it doesn't understand, but you can run into bugs if you have more than one TFM-specific-dependencyGroup it doesn't understand: nuget may map them both to unsupported then complain about duplicate dependencies.  EG: https://github.com/NuGet/Home/issues/5162.  Net result, a package can still install applying non-netstandard assets in an old client if it only has 1 netstandard dependency group.  There were many packages which intentionally walk this fine line due to desire for breadth of install.

You can see that DiagnosticSource does indeed attempt to make itself work on the old clients by using the portable TFM: https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/System.Diagnostics.DiagnosticSource.csproj#L7-L11

IIRC this was an intentional decision with the original DiagnosticSource so that it could be used in very old versions of VS which didn't support updated NuGet clients.  The genesis of that behavior goes all the way back to the original source drop from TFS: https://github.com/dotnet/corefx/commit/fa811f379c45504a4b5fdae5b08a22a31202bea9#diff-3ceb85008c987bf5d32907d19e9c850fR13

**Comment by ericstj** [comment]
Did you actually test every package in that query?  I agree DiagnosticSource appears to be broken.  I see some like System.Collections.Immutable that would install...

I think we'd need to let the library/package owners decide if they want to force their users to upgrade nuget or fix their package dependencies to walk the fine-line of the nuget bug/behavior.

**Comment by lmolkova** [comment]
Yes, I actually tested all the packages:

```
> .\nuget install System.Collections.Immutable
Attempting to resolve dependency 'NETStandard.Library (≥ 1.6.1)'.
'NETStandard.Library' already has a dependency defined for 'Microsoft.NETCore.Platforms'.

> .\nuget install System.Reflection.Metadata
Attempting to resolve dependency 'System.Collections.Immutable (≥ 1.4.0)'.
Attempting to resolve dependency 'NETStandard.Library (≥ 1.6.1)'.
'NETStandard.Library' already has a dependency defined for 'Microsoft.NETCore.Platforms'.

> .\nuget install System.Threading.Tasks.Dataflow
Attempting to resolve dependency 'NETStandard.Library (≥ 1.6.1)'.
'NETStandard.Library' already has a dependency defined for 'Microsoft.NETCore.Platforms'.

> .\nuget install System.Threading.Tasks.Extensions
Attempting to resolve dependency 'System.Collections (≥ 4.3.0)'.
'System.Collections' already has a dependency defined for 'Microsoft.NETCore.Platforms'.

> .\nuget install System.Numerics.Vectors
Attempting to resolve dependency 'NETStandard.Library (≥ 1.6.1)'.
'NETStandard.Library' already has a dependency defined for 'Microsoft.NETCore.Platforms'.
```

I agree that solution for some packages could be to support 2.8.6 by removing dependencies and it's up to lib owners to decide.

**Comment by ericstj** [comment]
What type of project are you trying to install to?  S.C.I only has a dependency on NS.L on framework netstandard1.0, so a NuGet that doesn't understand netstandard at all shouldn't even be installing the NS.L package to get that error.  //cc @emgarten

**Comment by lmolkova** [comment]
right, I forgot to mention it's an old VS2012 csproj with packages.config, targeting 4.5

**Comment by ericstj** [comment]
Do you get the same results from the Package Manager UI on the project itself?  Its possible `nuget install` from the commandline is trying to download and install all possible dependencies rather than constraining it to the specific TFM of the project.

**Comment by lmolkova** [comment]
from the UI

1. System.Diagnostics.DiagnosticSource - same error
'System.Diagnostics.DiagnosticSource' already has a dependency defined for 'System.Collections'.

2. System.Collections.Immutable - success

3. System.Reflection.Metadata
'System.Reflection.Metadata' already has a dependency defined for 'System.Collections.Immutable'.

4. System.Threading.Tasks.Dataflow
'System.Threading.Tasks.Dataflow' already has a dependency defined for 'NETStandard.Library'.

5. System.Threading.Tasks.Extensions - success

6. System.Numerics.Vectors - success

`nuget restore`  works fine after installation from Package Manager UI

**Comment by ericstj** [comment]
Dataflow: @stephentoub
DiagnosticSource: @vancem 
Reflection.Metadata: @nguerrera @tmat

We need to decide if we should raise the minclient version of these packages, preventing them from installing on NuGet 2.8.6, and thus VS2012, or fix the packages to try and collapse the dependencies down to a single NETStandard group that would be compatible with 2.8.6.

We could put some validation targets into the package build to make sure that in the future folks don't add new dependency groups that would trip up NuGet 2.8.6.

**Comment by emgarten** [comment]
Raising the minclient version to 2.12 for packages that have netstandard dependency groups seems like a good solution to me.

The *already has a dependency defined* error in NuGet 2.x occurs when reading the nuspec file, if there is more than 1 unknown framework they are merged together under *unsupported* and this collision occurs.

**Comment by ericstj** [comment]
@emgarten that's not necessarily a solution: its a breaking change since nuget didn't ship 2.12 to VS 2012 afaik, but I may be wrong.  Couldn't find this documented anywhere.

**Comment by emgarten** [comment]
There was an RC of 2.12 for VS 2012 but it did not ship due to other issues that were hit when using netstandard on VS 2012.

**Comment by karelz** [comment]
@ericstj just one area label please - see [triage rules](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified).

**Comment by nguerrera** [comment]
Do we have data on package downloads by nuget version. How long has this been broken? My instinct is that we can bump the min client for SRM and tell folks on 2012 to keep using the last version that worked there or upgrade VS.

**Comment by ericstj** [comment]
I believe it was only broken in 1.5.0 when the netstandard2.0 dependency group was added (in order to omit the dependency on the NETStandard.Library package), but its possible that a previous release may have been broken due to the Xamarin profiles.  @lmolkova can you test version 1.4.2?

As far as stats, you can see those here: https://www.nuget.org/stats/packages/System.Reflection.Metadata?groupby=Version&groupby=ClientName&groupby=ClientVersion

**Comment by lmolkova** [comment]
@ericstj 
The latest version that I was able to install with cli was 1.0.21
```
> .\nuget install System.Reflection.Metadata -Version 1.4.2
Attempting to resolve dependency 'System.Collections.Immutable (≥ 1.3.1)'.
Attempting to resolve dependency 'System.Collections (≥ 4.3.0)'.
WARNING: 'System.Collections' already has a dependency defined for 'Microsoft.NETCore.Platforms'.
'System.Collections' already has a dependency defined for 'Microsoft.NETCore.Platforms'.

> .\nuget install System.Reflection.Metadata -Version 1.4.1
Attempting to resolve dependency 'System.Collections.Immutable (≥ 1.3.0)'.
Attempting to resolve dependency 'System.Collections (≥ 4.3.0)'.
WARNING: 'System.Collections' already has a dependency defined for 'Microsoft.NETCore.Platforms'.
'System.Collections' already has a dependency defined for 'Microsoft.NETCore.Platforms'.

> .\nuget install System.Reflection.Metadata -Version 1.3.0
Attempting to resolve dependency 'System.Collections.Immutable (≥ 1.2.0)'.
Attempting to resolve dependency 'System.Collections (≥ 4.0.11)'.
WARNING: 'System.Collections' already has a dependency defined for 'Microsoft.NETCore.Platforms'.
'System.Collections' already has a dependency defined for 'Microsoft.NETCore.Platforms'.

> .\nuget install System.Reflection.Metadata -Version 1.1.0
Attempting to resolve dependency 'System.Collections.Immutable (≥ 1.1.37)'.
Attempting to resolve dependency 'System.Runtime (≥ 4.0.0)'.
Attempting to resolve dependency 'System.Resources.ResourceManager (≥ 4.0.0)'.
The 'System.Resources.ResourceManager 4.0.0' package requires NuGet client version '3.0' or above, but the current NuGet version is '2.8.60717.93'.

> .\nuget install System.Reflection.Metadata -Version 1.0.22
Attempting to resolve dependency 'System.Runtime (≥ 4.0.0)'.
Attempting to resolve dependency 'System.Resources.ResourceManager (≥ 4.0.0)'.
The 'System.Resources.ResourceManager 4.0.0' package requires NuGet client version '3.0' or above, but the current NuGet version is '2.8.60717.93'.

> .\nuget install System.Reflection.Metadata -Version 1.0.21
Attempting to resolve dependency 'System.Collections.Immutable (≥ 1.1.36)'.
Installing 'System.Collections.Immutable 1.1.36'.
Successfully installed 'System.Collections.Immutable 1.1.36'.
Installing 'System.Reflection.Metadata 1.0.21'.
Successfully installed 'System.Reflection.Metadata 1.0.21'.
```

Apparently, VS2012 Package MAnager UI does not allow to install older versions of packages.

It seems that powershell nuget cmdlets have the same behavior as UI and with this, I was able to install  1.1.0, but not later
```
PM> Install-Package System.Reflection.Metadata -Version 1.4.2
Attempting to resolve dependency 'System.Collections.Immutable (≥ 1.3.1)'.
Install-Package : 'System.Reflection.Metadata' already has a dependency defined for 'System.Collections.Immutable'.At line:1 char:1
+ Install-Package System.Reflection.Metadata -Version 1.4.2
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
```

**Comment by nguerrera** [comment]
Based on the small download numbers from older clients and that this has been non-functional since 1.0.21 without feedback until now, I think we should just bump the min client version for S.R.M. @tmat, do you agree?

**Comment by ericstj** [comment]
Yeah.  Agreed, for SRM.

**Comment by tmat** [comment]
YEah

**Comment by ericstj** [comment]
Ok, @vancem / @stephentoub do you guys have a preference on DiagnosticSource / DataFlow?

**Comment by stephentoub** [comment]
I don't have a strong preference. My inclination would be to do the simple thing, raising the min version, and then do the more complicated thing later if it actually becomes problematic for folks.

**Comment by vancem** [comment]
I am also OK with bumping the minimum client version number.    Is someone going to do this for all instances or are we doing it piecemeal?

**Comment by karelz** [comment]
We should do it together. Is there any volunteer? If not, I will appoint one ;)
