### ISSUE TITLE
ClaimTypes class is not declared as partial

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/corefx#23848]
Should the [ClaimTypes.cs](https://github.com/dotnet/corefx/blob/master/src/System.Security.Claims/src/System/Security/Claims/ClaimTypes.cs) class be declared as a partial class?

That way the class could be further extended by a third-party class with further custom claim types.

**Comment by JonHanna** [comment]
A third party couldn't extend the class using `partial` unless they copied the source into their application, in which case they could add `partial` to it when they did so. They can't extend the `System.Security.Claims.ClaimTypes` class from outside of `System.Security.Claims` even if it was `partial`.

**Comment by vanillajonathan** [comment]
Oh, I see. So just declaring a partial class with the same name in the same namespace is not enough?

In that case, close this issue.

I guess I will have to create my own class where I declare the claim types, but then name the class something else such as `MyClaimTypes` so to avoid having ambiguous class references.

**Comment by JonHanna** [comment]
Yes, `partial` is useful in having more than one file for your own class. One example within corefx would be how `System.Linq.Enumerable` is split over several files that each deal with related cases but are all the same large class as far as consumers can see. Another common case is when you want to have some of the code generated programmatically and some written by hand; having two `partial` declarations in different files lets you re-run the code generations without it over-writing the hand-coded bit in another file. Once it's compiled, there's no such thing as `partial` any more; it doesn't affect the output at all.
