### ISSUE TITLE
CI: RHEL7, CentOS7 and Ubuntu 14.04 are running outdated versions of libgdiplus

### ISSUE THREAD

**Issue by qmfrederik** [dotnet/corefx#23846]
The CI servers running RHEL7, CentOS7 and Ubuntu 14.04 are running version 2.x of libgdiplus, causing some tests to fail because of bugs in that version of libgdiplus.

These are currently being disabled on those OSes, but we should try to install a more recent version of libgdiplus on those machines.

**Comment by karelz** [comment]
That also means we should document that we require specific version of libgdiplus to be available on Linux as prereq, right?

**Comment by danmosemsft** [comment]
@mellinoe  I got a segfault on Centos7.3 is tha related potentially
https://mc.dot.net/#/user/danmosemsft/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/bb77128c10d80888512031e9a95feb41a99c1ef8/workItem/System.Drawing.Common.Tests

**Comment by safern** [comment]
Tracked by: https://github.com/dotnet/core-eng/issues/2168
