### ISSUE TITLE
Move and make `TypeInfo.GetDeclaredXXX` APIs symmetric with `RuntimeReflectionExtensions.GetRuntimeXXX`

### ISSUE THREAD

**Issue by kingces95** [dotnet/corefx#23854]
_Carving this discussion out of #23762_

# Proposal
Hold on. Let me try this again...

**Comment by AtsushiKan** [comment]
`RuntimeReflectionExtensions` was mostly a way to ease over the pain of the .NETCore 1.0 Type surface minimization. Now that .NETCore 2.0 has put back all the original apis on `Type`, `RuntimeReflectionExtensions` isn't all that useful and is likely to become marginalized as well. I wouldn't make symmetry with that a driving argument.

For me, the compelling benefits would be:

- No reaching into base classes (and thus producing those ReflectedType monstrosities.)

- Apis that support exact binding only. No binders, no BindingFlags with its mongrel mixture of flags.

- No `AmbiguousMatchExceptions`. In other words, https://github.com/dotnet/corefx/issues/23852

To get the perf benefits of instantating only the MethodInfo objects necessary, it would have to live on Type itself - an extension method wouldn't have the required access. I don't know that we'd guarantee no internal allocations of candidates, but we do already do some work to keep it down to a reasonable number.

**Comment by AtsushiKan** [comment]
As pointed out in the other issue (https://github.com/dotnet/corefx/issues/23852), searching only the specified type leaves you vulnerable to hoist-to-the-base-class changes in the targeted type. The existing `Type.GetMethod()` apis search base classes with rules that keep that in mind.

With that, I don't think we want to add any more "search only this class by name" type apis.
