### ISSUE TITLE
Desktop (4.6.2): System.Security.Cryptography.CngKey.Create fails with System.Security.Cryptography.CryptographicException ("The requested operation is not supported.\r\n")

### ISSUE THREAD

**Issue by ohadschn** [dotnet/corefx#23853]
@bartonjs 

The following code succeeds, meaning the private key is valid (and indeed I can export it and use it with a `SigningCredentials` successfully):
```cs
CngKey.Import(PrivateKeyBytes, CngKeyBlobFormat.Pkcs8PrivateBlob);
```

However, the following code fails:
```cs
var keyParams = new CngKeyCreationParameters
{
  Parameters =
  {
    // I verified the key size with openssl
    new CngProperty("Length", BitConverter.GetBytes(2048), CngPropertyOptions.None),
    // this is the problematic line, if I remove it it works 
    // but the whole point is to import an existing key to the KSP, not generate a new one
    new CngProperty(CngKeyBlobFormat.Pkcs8PrivateBlob.Format, PrivateKeyBytes, 
                    // I tried all 3 values of CngPropertyOptions, no effect
                    CngPropertyOptions.None)
  }
};

key = CngKey.Create(CngAlgorithm.Rsa, PrivateKeyName, keyParams);
```

```
   System.Security.Cryptography.CryptographicException ("The requested operation is not supported")
   at System.Security.Cryptography.NCryptNative.SetProperty(SafeNCryptHandle ncryptObject, String propertyName, Byte[] value, CngPropertyOptions propertyOptions)
   at System.Security.Cryptography.CngKey.SetKeyProperties(SafeNCryptKeyHandle keyHandle, CngKeyCreationParameters creationParameters)
   at System.Security.Cryptography.CngKey.Create(CngAlgorithm algorithm, String keyName, CngKeyCreationParameters creationParameters)
```

**Comment by bartonjs** [comment]
"PKCS8_PRIVATEKEY" (CngKeyBlob.Format.Pkcs8PrivateBlob.Format) isn't a valid property identifier (see https://msdn.microsoft.com/en-us/library/windows/desktop/aa376242(v=vs.85).aspx).

What are you trying to do? (Alternatively: What is import doing (or not doing) that you want to be doing something different?)

**Comment by ohadschn** [comment]
Curious that `PKCS8_PRIVATEKE` isn't a valid property identifier, supposedly this is what these guys did and it solved their issues:
* https://stackoverflow.com/a/43756359/67824
* https://social.msdn.microsoft.com/Forums/vstudio/en-US/467485eb-1249-406e-86c8-289eb42bd51b/net-cng-full-backup-recovery-of-rsa-keypair-cngkeyimport-cngkeyblobformat-?forum=netfxbcl

As for the reason I'm trying to use `CngKey.Create`, it is my limited understanding that it securely stores a key in the KSP where it can later be retrieved by  `CngKey.Open`. Presumably that would be preferable to repeated calls to `CngKey.Import`, but I may be way off so do let me know.

**Comment by ohadschn** [comment]
BTW regarding the property identifier, the guy who implemented it (second link I gave above), referenced [this](https://msdn.microsoft.com/en-us/library/windows/desktop/bb427412(v=vs.85).aspx) (emphasis mine):

> _To import a persisted key_
> Create a persisted key by using the NCryptCreatePersistedKey function.
> Set any desired properties on the key object by using the NCryptSetProperty function.
> **Set the import key BLOB as a property on the key, with the BLOB type as the property name**.
> Finalize the persisted key import by using the NCryptFinalizeKey function.

**Comment by bartonjs** [comment]
Interesting. Learn something new every day.

It looks like the GenericPrivate blob type is wired up for this, but not the PKCS8 blob:

```C#
byte[] blob;
RSAParameters pubParams;

using (RSACng bleh = new RSACng(4096))
{
    blob = bleh.Key.Export(CngKeyBlobFormat.GenericPrivateBlob);
    pubParams = bleh.ExportParameters(false);
}

var keyParams = new CngKeyCreationParameters
{
    Parameters =
    {
        new CngProperty(CngKeyBlobFormat.GenericPrivateBlob.Format, blob, CngPropertyOptions.None),
    }
};

const string KeyName = "ImportTestKey";

if (CngKey.Exists(KeyName))
{
    using (CngKey existing = CngKey.Open(KeyName))
    {
        existing.Delete();
    }
}

using (CngKey.Create(CngAlgorithm.Rsa, KeyName, keyParams))
{
}

using (CngKey existing = CngKey.Open(KeyName))
using (RSA persisted = new RSACng(existing))
using (RSA pubOnly = RSA.Create())
{
    pubOnly.ImportParameters(pubParams);

    byte[] message = Encoding.ASCII.GetBytes("Hello");
    byte[] encrypted = pubOnly.Encrypt(message, RSAEncryptionPadding.OaepSHA1);
    byte[] decrypted = persisted.Decrypt(encrypted, RSAEncryptionPadding.OaepSHA1);

    Console.WriteLine(Encoding.ASCII.GetString(decrypted));
}
```

Note that setting the key length is redundant with giving it the blob.

So, I'll pass the info on to the CNG team, but it does look like there is a workaround for you (use Import on the PKCS8 blob, export it as GenericPrivate, then use Create to make it persisted).

I'm going to go ahead and close this here since there's nothing actionable for .NET.
