### ISSUE TITLE
Ensure reflection APIs exist that can specify any single info

### ISSUE THREAD

**Issue by kingces95** [dotnet/corefx#23852]
_Carving this discussion out of #23762_

# Proposal 
Ensure methods exist that allow the user to specify a single info (specifically Method, Constructor, and Property) to reflection to activate and in so doing allow reflection to only activate and cache the minimum infos needed by the user.

A bit of recent history:
> This issue arose as part of a more general push to move useful APIs off of `TypeInfo` to more accessible locations. While considering what to do with the `TypeInfo.GetDeclaredXXX` family of APIs we though, if we do move them let's change their signatures so they're each able to specify each type of info they retrieve. The idea of moving the `GetDeclaredXXX` met with a lukewarm response and is not specifically what this issue is addressing. Here we address the proposal to ensure we have methods to return a single info. 

https://github.com/dotnet/corefx/issues/23762#issuecomment-327633532 @AtsushiKan
---------------------
Right, I think we're on the same page. We want an api that lets you pass everything that guarantees a single (or zero) result.

The existing api

`Type.GetMethod(string name, int genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConvention, Type[] types, ParameterModifier[] modifiers)`

comes <b>pretty</b> close. I know of at least two things it's missing:

1. Return type (e.g. the `operator explicit` case, though it's not limited to that of course.)

2. Custom modifiers on parameter types. You can overload on them too.

The thing is, that for this to have any chance of getting approved, it really has to get it right. We've got so many overlapping apis to do the 99% job already - if it doesn't really solve something 100%, it's not going to be added.

https://github.com/dotnet/corefx/issues/23762#issuecomment-327830616 @AtsushiKan 
---------------------
The uber-GetMethod is a much more ambitious effort (and much harder to justify on a cost-benefit basis - Reflection has been demented with regard to custom modifiers since its inception and it doesn't seem to have mattered much in the real world.) That can wait for another day.

---------------------
So this may just be a place holder to collect any ideas about this for some future release.

**Comment by AtsushiKan** [comment]
It occurs to me that this could be further subdivided (no need to fission the issues just yet - this is still a place holder.)

- Adding a "returnType" parameter to GetMethod. This is pretty simple.

- Adding the ability to specify custom modifers. This would be about augmenting Signature Types (in progress: https://github.com/dotnet/corefx/issues/16567) with the ability to create a ModifiedType. This is a feature that is orthogonal to the first one, and would direction attention to that the Reflection also has no (complete) solution for reading custom modifiers off an existing signature. This is the one that's much more work.

**Comment by AtsushiKan** [comment]
The shopping list of items needed to specify a method **unambiguously** (based on ECMA 335 - 1.8.6.1.5 - 1.8.6.1.6)

1. The declaring `Type`
2. The name
3. The generic parameter count (including 0 for non-generic methods)
4. static or instance
5. vararg or fixedarg (aka "Standard")
6. Return Type
7. Parameter Types

Note that 3, 4, and 5 are encoded in the `CorCallingConvention` byte in the metadata signature. But few people are familiar with that enum, so our api should surface these options in a friendlier way. 
 
The most analogous existing api is this one:

`public MethodInfo GetMethod(string name, BindingFlags bindingAttr, Binder binder, CallingConventions callConvention, Type[] types, ParameterModifier[] modifiers)`

Some trivia about this apI:
 
  - `callConvention`. `GetMethod()` ignores everything but `Standard` and `VarArgs` bits (these two
     value are mutually exclusive but are designed so the caller of `GetMethod()` can OR them together
     to specify "don't care". There's a defined enum value for this: 

           `CallingConventions.Any = CallingConventions.Standard | CallingConventions.VarArg`

   - The `callConvention` enum also has bits for static/instance and generic/non-generic. But
     `GetMethod()` has other parameters for those, and those other parameters are the controlling
     ones. 


  - `modifiers` relates solely to invoking IDispatch COM objects (it's a bool-mask indicating which parameters are VT_BYREF.) It has nothing to do with disambiguation or ECMA metadata - in fact, `GetMethod` ignores it completely, only passing it to the binder. And the default binder does nothing whatsoever with it.

   - `Type.GetMethod()` does not let you specify a return type, although it is legal to overload differing only in return type (`operator explicit` being a useful example.) This is a functionality hole in this api.

So here's my starting wish-list:

   - Name of api will be `GetDeclaredMethod()`

   - It will not search base classes. Only the methods physically declared on that type.
 
   - It will not have a `callingConvention` argument. Static/Instance, VarArg/FixedArg
     should be specified in an intuitive way. (boolean arguments? a new enum bitmask?)

   - For the return type and parameter types, it will accept SignatureTypes as well as normal Types.
     (to maintain parity with `Type.GetMethod()`.)

   - If SignatureTypes evolve become formally complete (i.e. supporting custom modifiers), this
     new api will never have to throw `AmbiguousMatchException`.

   - Types must match **exactly**. None of that "type compatibility" policy that no one can remember.

**Comment by jkotas** [comment]
What scenario is this method good for? I have never encountered a case where I wanted to a match on all of the above. 

And if you really need to do an exact match on everything, you can do it today by enumerating all methods.

**Comment by AtsushiKan** [comment]
Well if I wanted to pick out a specific method, especially from a type I don't own and that might evolve out of my control, and be sure I don't get an AmbiguousMatchException, this is the kind of api I'd want. A one-line call to such an api is a lot more convenient than enumerating methods and applying a predicate.

**Comment by jkotas** [comment]
If it can evolve out of your control, your code should be robust against non-breaking IL changes (method moved to base class). To be robust against non-breaking IL changes, it should look into the base class as well.

This is the general problem with the `GetDeclared*` methods.

**Comment by AtsushiKan** [comment]
A fair point. With that, this api just crossed the "-100 points" threshold for me. Better to stay with the apis we have, homely as they are.
