### ISSUE TITLE
SocketException: Message too long when sending large byte array over UDP on macOS

### ISSUE THREAD

**Issue by lextm** [dotnet/corefx#23871]
It can be easily reproduced with the following code snippet in a console app,
```
var buffer = new byte[20000];
var target = new IPEndPoint(IPAddress.Loopback, 161);
var client = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
client.SendTo(buffer, target);
```
And the exception only appears on macOS (High Sierra) Version 10.13 Beta (17A360a). Can reproduce under `netcoreapp1.0`, `netcoreapp1.1`, and `netcoreapp2.0`.

The exception does not occur on Windows (I am testing on Windows Server 2016) and Linux (I am testing on Ubuntu 14.04 Travis CI).

The error message might be related to #23579, but I guess they are different things.

**Comment by stephentoub** [comment]
Do you get a similar error on the same OS if you write the equivalent C code?

**Comment by lextm** [comment]
Thanks for the advice.

I can reproduce the error by using the following Python script,
```
import socket

UDP_IP = "127.0.0.1"
UDP_PORT = 161
file = open("/some/file", "r") 
MESSAGE = file.read()

print "UDP target IP:", UDP_IP
print "UDP target port:", UDP_PORT

sock = socket.socket(socket.AF_INET, # Internet
             socket.SOCK_DGRAM) # UDP
sock.sendto(MESSAGE, (UDP_IP, UDP_PORT))
```
So it should be an operating system level configuration that triggers the socket exception, not .NET Core.

**Comment by lextm** [comment]
Found more information from https://stackoverflow.com/questions/22819214/udp-message-too-long and I can suppress the exception by setting `net.inet.udp.maxdgram=65535`.
