### ISSUE TITLE
DCR: Review ReferenceCountedDisposable as an alternative to IRetainable

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#23870]
_From @ahsonkhan on September 7, 2017 20:26_

Design Change Request (DCR)
From https://github.com/dotnet/coreclr/pull/13583#issuecomment-325162865:
> :bulb: My strongest recommendation here would be to carefully review the semantics of [`ReferenceCountedDisposable<T>`](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Utilities/ReferenceCountedDisposable.cs) in Roslyn and consider how they might be usable in these scenarios as an alternative to `IRetainable`. This type provides strong guarantees in concurrent code and eliminates many concerns related to ownership when both `IDisposable` and `IRetainable` are at play. It also provides a weak reference type with strong semantic guarantees.

cc @KrzysztofCwalina, @shiftylogic 

_Copied from original issue: dotnet/coreclr#13840_

**Comment by joshfree** [comment]
Reviewed offline with feature team; closing suggestion issue and sticking with current design shape.  If you'd like to create an API proposal we can follow up further.  Thank you
