### ISSUE TITLE
System.Drawing.Common.Tests failed

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#23877]
Failed to generate the test results.

Failed configuration: OuterLoop_netcoreapp_ubuntu14.04_release

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_ubuntu14.04_release/lastCompletedBuild/

/mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu14.04_release/Tools/tests.targets(483,5): error: One or more tests failed while running tests from 'System.Drawing.Common.Tests' please check /mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu14.04_release/bin/tests/System.Drawing.Common.Tests/netcoreapp-Linux-Release-x64/testResults.xml for details!
[mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu14.04_release/src/System.Drawing.Common/tests/System.Drawing.Common.Tests.csproj]

**Comment by Jiayili1** [comment]
This issue is repro in ubuntu14.04_release, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu14.04_release/4251/

**Comment by Jiayili1** [comment]
This issue is repro in ubuntu16.04_release, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu16.04_release/4142/

**Comment by Jiayili1** [comment]
This issue is repro in debian8.4_release, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/debian8.4_release/3880/

**Comment by safern** [comment]
Its been a while since this issue hasn't been updated with a repro. Will close and we can re-open if we see the failure again.
