### ISSUE TITLE
Support casting ReadOnlySpan<T> to Span<T>

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#23884]
# Proposal

```
     struct ReadOnlySpan<T>
     {
          public Span<T> DangerousAsSpan();
     }
```

I have not found a workable way to do this (at least one that works across both fast and slow Span.) This functionality is needed to bridge code that uses ReadOnlySpan with code that supports both reading and writing (Span).

**Comment by ektrah** [comment]
If it's added, could it be hidden somewhere in System.Runtime.CompilerServices?

Adding it to the type directly makes it a bit too convenient to convert a ReadOnlySpan\<T\> to a Span\<T\>, even if it has "Dangerous" in its name.

----

```csharp
namespace System.Runtime.CompilerServices
{
    public static class DangerousSpanHelpers
    {
        public static Span<T> AsSpan<T>(ReadOnlySpan<T> readOnlySpan);

        public static Span<T> CreateSpan<T>(object obj, ref T objectData, int length);
        public static ReadOnlySpan<T> CreateReadOnlySpan<T>(object obj, ref T objectData, int length);

        public static ref T GetPinnableReference<T>(Span<T> readOnlySpan);
        public static ref T GetPinnableReference<T>(ReadOnlySpan<T> readOnlySpan);
    }
}
```

See also https://github.com/dotnet/corefx/issues/18747.

**Comment by KrzysztofCwalina** [comment]
@AtsushiKan, what's the bridge code you need to write?

I would like to minimize the number of "Dangerous" APIs. They are just loopholes that can be used in safe code. For rare cases, could you pin the r/o span and wrap the pinned pointer in r/w Span?

**Comment by AtsushiKan** [comment]
The bridge code was embedding corefxlab's HttpParser into the existing Kestrel code. Yes, I'm aware this isn't a "shipping" type issue since the ultimate fix is to propagate the ReadOnly into the Kestrel code.

Does pinning work for arbitrary Span's (i.e. I don't know if the original ROSpan was created around a managed object or a native pointer.) As long as there is a way to do it, that's all I really care about.

**Comment by benaadams** [comment]
> Does pinning work for arbitrary Span's

yes

**Comment by AtsushiKan** [comment]
How do I write that in C#?

**Comment by benaadams** [comment]
> Does pinning work for arbitrary Span's 

yes
```csharp
fixed (byte* buffer = &span.DangerousGetPinnableReference())
{
    // code here
}
```

**Comment by AtsushiKan** [comment]
Ok. It's slightly unfortunate that you can't write a generic version of that (C#, no pointers to generics) but other than that, this is good enough for me.
