### ISSUE TITLE
Process.ProcessName is expensive on Windows

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#23887]
It causes an enumeration of all processes just to get the name of the current process

https://source.dot.net/#System.Diagnostics.Process/System/Diagnostics/Process.cs,900
https://source.dot.net/#System.Diagnostics.Process/System/Diagnostics/ProcessManager.Windows.cs,53

On Windows it could call just GetProcessName. There may be other places it could avoid examining all processes just to get information about the current process. (All this is arguably fallout of giving the Process class three responsibilities -- spawning processes, representing the current process, and accessing general process information)

Feedback from internal service that calls `Process.ProcessName` often for logging on Windows.

**Comment by ericstj** [comment]
GetCurrentProcess() (or some new API) should also return a singleton, that's also adding to the problem.

**Comment by danmosemsft** [comment]
@dnickless you mentioned you were interested in perf work, this is one where we know the issue. If you are more looking for an open investigation, I'll dig around.

**Comment by dnickless** [comment]
Thanks for the pointer. Is that really an issue, though? When I look at

https://source.dot.net/#System.Diagnostics.Process/System/Diagnostics/Process.cs,897

the `ProcessInfo` instance gets cached until someone explicitly calls `Refresh()`. So accessing `ProcessName` on the same instance of a `Process` should be fast after the first time (which, however, will trigger the enumeration of all processes once).

@ericstj's "singleton" finding is probably key to the topic, I'm happy to submit a change to cache the current process in a static variable...?!

**Comment by ericstj** [comment]
I think the downside with even the caching is that ProcessManager fetches all the PIs for the entire machine and then throws them away: https://source.dot.net/#System.Diagnostics.Process/System/Diagnostics/ProcessManager.Windows.cs,3d8819b2e143fe81

**Comment by dnickless** [comment]
Yeah, I've seen this. I'm just thinking that this is a one-off hit when you access any property from the `ProcessInfo` the first time like `ProcessName` etc. But then it should be fast. So I am having difficulties in seeing how this would cause performance problems to the internal guys that @danmosemsft  quoted here:

> Feedback from internal service that calls Process.ProcessName often for logging on Windows.

Nonetheless, I'll look into that bit and see what can be done.

**Comment by ericstj** [comment]
IIRC The folks reporting the bad-behavior had a case of some logging code calling `Process.GetCurrentProcess().ProcessName` so they weren't caching the process and every call ended up enumerating all processes on the machine.

**Comment by dnickless** [comment]
That's what I suspect, too. Mind you, that should be a quick one to fix, shouldn't it?

**Comment by ericstj** [comment]
I think the challenge with making it a singleton is that it may be mutable.  For instance: what happens if you Dispose it? I haven't looked deeply at this but there may be other similar issues.

**Comment by danmosemsft** [comment]
I don't feel strongly about this one for the reasons you state. However it seems like it's a case where we can make an easy change to help anyone using this questionable pattern of `Process.GetCurrentProcess().ProcessName`. We coudl have easily have implemented it this way in the first place.

**Comment by dnickless** [comment]
Ok, I got some changes locally now. But I'm getting this:

![image](https://user-images.githubusercontent.com/985774/30297564-303855d8-9716-11e7-9e19-1331fcf19ea8.png)

I've seen that someone else had the same problem here: https://github.com/dotnet/sdk/issues/1514

Can anyone help?

**Comment by danmosemsft** [comment]
Maybe @ericsj has a suggestion. But I never use `dotnet` within my repo. We are working on converting projects over so that we can, but our projects pre-date it. For testing one library I do eg `msbuild /t:buildandtest`

**Comment by ericstj** [comment]
See the [developer guide](https://github.com/dotnet/corefx/blob/7059f8b316723f5db64e4b1d28e2b1e8b137ab1e/Documentation/project-docs/developer-guide.md) for details.

**Comment by dnickless** [comment]
Or  how about just a plain "build" command:

![image](https://user-images.githubusercontent.com/985774/30343427-9721d11a-97cb-11e7-804a-5b8b77434af4.png)

**Comment by dnickless** [comment]
Or "msbuild" in the src\System.Diagnostics.Process and src\System.Diagnostics.Process\src folder:

![image](https://user-images.githubusercontent.com/985774/30343502-d1e3c812-97cb-11e7-8cb6-8726bfbc3bb7.png)

**Comment by dnickless** [comment]
I'll try to clone the entire repo again an build from scratch...

**Comment by ericstj** [comment]
You have to build from the root once before you can build individual folders/tests.

It looks like you cloned at a point where someone snuck a build break in that @joperezr [fixed](https://github.com/dotnet/corefx/commit/2d5901e37416d3d737f7405b94c0ec3d42e5f806) yesterday, so fetch latest to fix that.  (thanks @joperezr )

The process failures are due to the build halting from above break.

**Comment by dnickless** [comment]
Indeed, things are starting to look a little better. Thanks.

**Comment by wtgodbe** [comment]
@dnickless what is the status of this issue?

**Comment by dnickless** [comment]
Progress should be possible when I'm back from my extended weekend trip as in next week. Are we in a hurry here?

**Comment by danmosemsft** [comment]
Not at all, @wtgodbe is just going through issues in his area...

**Comment by dnickless** [comment]
I was under the impression I could somehow create my pull request right into this conversation. That doesn't seem to be the case, though... Oh well, lots to learn. Check out this one instead: https://github.com/dotnet/corefx/pull/24198

**Comment by am11** [comment]
> I was under the impression I could somehow create my pull request right into this conversation

It *is* possible for admins to convert thread type `issue` to `pull` using `git + hub = GitHub` scripts: https://github.com/github/hub#git--hub--github. 🤓
