### ISSUE TITLE
Break out System.Data.DataSet and DataTable from System.Data.Common

### ISSUE THREAD

**Issue by joshudson** [dotnet/corefx#23907]
Most projects using System.Data.SqlClient have no need or use of DataSet or DataTable classes. It is to them about half a megabyte of junk they do not need and will never try to use, but it gets loaded because all this stuff references it. Most projects are better off using DataReader directly or EntityFramework which uses DataReader.

The classes along with whatever depends on them should be broken out into another dll such as System.Data.DataSet.

SqlDataAdapter would also need to get broken out into its own dll or it defeats the purpose.

There is no point arguing this will break backwards compatibility. Backwards compatibility of System.Data.Common is already broken. Better to fix this soon before too much depends on it.

**Comment by divega** [comment]
*System.Data Triage:* There was a time in .NET Core 1.x timeframe when this could have been possible and considered desirable, but given the direction taken in 2.0 towards prioritizing compatibility and the cyclic dependencies between System.Data.Common and DataSet APIs, it is no longer viable. 

Closing.
