### ISSUE TITLE
Intermittent build failure: The type or namespace name 'Policy' does not exist in the namespace 'System.Security' 

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#23912]
_From @sdmaclea on September 9, 2017 0:24_

CoreCLR is referencing CoreFX 13b5345

Building managed on Ubuntu AMD64 results in the following error.

The type or namespace name 'Policy' does not exist in the namespace 'System.Security' 

_Copied from original issue: dotnet/coreclr#13881_

**Comment by jkotas** [comment]
_From @sdmaclea on September 9, 2017 0:25_

```
/home/vmjenkins/workspace/Dotnet/build_corefx/Tools/Microsoft.Common.CurrentVersion.targets(1987,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Security.Permissions". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Security.Cryptography.Xml/ref/System.Security.Cryptography.Xml.csproj]
System.Security.Cryptography.Xml.cs(120,32): error CS0234: The type or namespace name 'Policy' does not exist in the namespace 'System.Security' (are you missing an assembly reference?) [/home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Security.Cryptography.Xml/ref/System.Security.Cryptography.Xml.csproj]
System.Security.Cryptography.Xml.cs(119,78): error CS0234: The type or namespace name 'Policy' does not exist in the namespace 'System.Security' (are you missing an assembly reference?) [/home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Security.Cryptography.Xml/ref/System.Security.Cryptography.Xml.csproj]
    1 Warning(s)
    2 Error(s)

```

**Comment by jkotas** [comment]
_From @sdmaclea on September 9, 2017 0:26_

This was the last CoreFX reference which I tried to build and it built successfully. 063b06d

**Comment by jkotas** [comment]
_From @sdmaclea on September 9, 2017 0:27_

@jkota @RussKeldorph FYI

**Comment by jkotas** [comment]
I do not think this has anything to do with CoreCLR. System.Security.Cryptography.Xml is not directly referencing anything in CoreCLR, and the type that it is complaining about (System.Security.Policy) does not live in CoreCLR either.

Also, I do not see either 063b06d or 13b5345 in my tree:

```
C:\corefx>git log 063b06d
fatal: ambiguous argument '063b06d': unknown revision or path not in the working tree.

C:\corefx>git log 13b5345
fatal: ambiguous argument '13b5345': unknown revision or path not in the working tree.
```

**Comment by jkotas** [comment]
_From @sdmaclea on September 9, 2017 5:26_

Those reference are the values in dependencies.props.
`<CoreFxCurrentRef>063b06d0342b9e575e852d0c52b590f1bdd85606</CoreFxCurrentRef>`



The CoreCLR issue is that dotnet-bot updated the reference to a corefx version which does not build successfully on Ubuntu.  2fbf7f1e80a3d is the commit

**Comment by jkotas** [comment]
This is failing in both CI (e.g. in https://github.com/dotnet/corefx/pull/23908) and official builds.

cc @weshaggard

**Comment by kingces95** [comment]
@jkotas Looks like the fix could simply be to add a `ProjectReference`.

**Comment by kingces95** [comment]
Likely fixed by https://github.com/dotnet/corefx/pull/23946.
