### ISSUE TITLE
ProcessStartInfo.UseShellExecute documentation is inconsistent with behavior

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/corefx#23913]
The documentation for the `UseShellExecute` property in the `ProcessStartInfo` class states the following:

> Gets or sets a value indicating whether to use the operating system shell to start the process. Returns: true if the shell should be used when starting the process; false if the process should be created directly from the executable file. **The default is true**.

This seems to be inconsistent with the actual behavior.

```cs
using System;
using System.Diagnostics;

namespace Example
{
    class Program
    {
        static void Main(string[] args)
        {
            var info = new ProcessStartInfo()
            {
                // UseShellExecute = true,
            };

            Console.WriteLine($"UseShellExecute: {info.UseShellExecute}");
        }
    }
}
```

Which prints out:
> UseShellExecute: False

Reference:
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessStartInfo.Unix.cs#L41

**Comment by joshudson** [comment]
What OS?

**Comment by vanillajonathan** [comment]
Linux.

```
$ dotnet --version
2.0.0
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu Artful Aardvark (development branch)"
```

**Comment by danmosemsft** [comment]
We chose the opposite default for core. See https://github.com/dotnet/corefx/issues/18949
Docs need an issue in the docs repo probably.

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/docs #3111](https://github.com/dotnet/docs/issues/3111) via [**ZenHub**](https://www.zenhub.com/)
