### ISSUE TITLE
Roundtripping DateTime with mn-MN FullDateTimePattern on Windows 8.1 fails

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23922]
```
Unhandled Exception of Type System.FormatException
Message :
System.FormatException : The string was not recognized as a valid DateTime. There is an unknown word starting at index 16.
Stack Trace :
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.Tests.DateTimeTests.Parse_ValidInput_Suceeds(String input, CultureInfo culture, Nullable`1 expected)
```

**Comment by tarekgh** [comment]
On Windows 8.1, the full date pattern was wrong and got fixed on later Windows releases. 
The pattern was 

```
yyyy 'оны' M'-р сарын' d. dddd 'гариг'. HH:mm:ss
```

Which formatting will produce a string like the following when formatting today's date:

```
2017 оны 9-р сарын 13. Лхагва гариг. 00:00:00
```

The problem with that is the part ```9-р сар``` can be recognized as a month name. in the same time, the part ```сарын``` can be recognized as a date word token. That confuses the parser and let it decide to go with parsing ```9-р сар``` as month name and then will fail to parse the rest of the string. The parser doesn't do all possible alternative parsing for the perf reason. ParseExact will help to parse such string to date. 

@stephentoub by that, I'll go ahead and fix the test to not use the full date pattern and then close this issue. Are you ok with that?

**Comment by stephentoub** [comment]
Thanks for investigating.

> by that, I'll go ahead and fix the test to not use the full date pattern and then close this issue. Are you ok with that?

Or since it was a bug in Windows 8.1, maybe just disable the test for Windows 8.1?
