### ISSUE TITLE
 Enlisting in Ambient transactions is not supported

### ISSUE THREAD

**Issue by cscer** [dotnet/corefx#23927]

**Comment by karelz** [comment]
@cscer do you have some details for your claim? Which API is that?

**Comment by cscer** [comment]
SqlConnection  void EnlistTransaction(Transaction transaction);

Here is the simple codes：

            SqlConnectionStringBuilder builder = new SqlConnectionStringBuilder()
            {
                DataSource = @"(localdb)\MSSQLLOCALDB",
                InitialCatalog = "MASTER"
            };
            TransactionOptions options = new TransactionOptions()
            {
                IsolationLevel = IsolationLevel.ReadUncommitted
            };

            CommittableTransaction trans = new CommittableTransaction(options);
            Transaction.Current = trans;

            using (SqlConnection conn = new SqlConnection(builder.ToString()))
            {
                conn.Open();
                conn.EnlistTransaction(trans);
                var cmd = conn.CreateCommand();
                cmd.CommandText = "select name from sys.tables";

                var reader = cmd.ExecuteReader();

                while (reader.Read())
                {
                    Console.WriteLine(reader.GetString(0));
                }

                reader.Close();
            }

**Comment by saurabh500** [comment]
The work for this was merged into master and is targeted the next major release.
