### ISSUE TITLE
GetAscii_Invalid failing in release branches

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23928]
The System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetAscii_Invalid test is causing lots of PRs to fail in the release branches.  It's also why the Windows 8.1 line at https://github.com/dotnet/corefx/tree/release/2.0.0 is red across the board.

cc: @danmosemsft, @karelz, @tarekgh, @Petermarcu

**Comment by danmosemsft** [comment]
It's not failing in master. Perhaps what is needed is the edit to IdnaTest_6.txt out of 70790f8d9760ff1060f2f853e4427feb21a0d08c. Need to modify the test to log what line of the data it failed on.

**Comment by danmosemsft** [comment]
Threw up a PR.

**Comment by stephentoub** [comment]
Addressed in release/2.0 by #23933, but the other release branches are still affected.

**Comment by danmosemsft** [comment]
This should be fixed in 1.1 and 1.0 by 545580a e86a00f on Friday.

**Comment by danmosemsft** [comment]
1.1 is fixed, 1.0 results aren't complete.

**Comment by tarekgh** [comment]
> 1.1 is fixed, 1.0 results aren't complete.

Is it possible to see if this test already run and completed yet in 1.0 without waiting for the whole results?

**Comment by tarekgh** [comment]
@danmosemsft I am closing this one. feel free to re-open if you see the failure.
