### ISSUE TITLE
System.Diagnostics.ProcessTests.ProcessTests.TestMainModule failed

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#2395]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release/791/console
```
System.Diagnostics.ProcessTests.ProcessTests.TestMainModule [FAIL]
        Assert.NotNull() Failure
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release\src\System.Diagnostics.Process\tests\System.Diagnostics.Process.Tests\ProcessTests.cs(198,0): at System.Diagnostics.ProcessTests.ProcessTests.TestMainModule()
```

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release/789/console
```
System.Diagnostics.ProcessTests.ProcessTests.TestMainModule [FAIL]
        Assert.NotNull() Failure
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release\src\System.Diagnostics.Process\tests\System.Diagnostics.Process.Tests\ProcessTests.cs(198,0): at System.Diagnostics.ProcessTests.ProcessTests.TestMainModule()
```

**Comment by stephentoub** [comment]
@Priya91, this failed, even after your attempted fix, in both debug and release:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug/813/consoleFull
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release/799/console

**Comment by Priya91** [comment]
@stephentoub : The failure is happening at SpinWait, failing to load the process modules, even after 100s. Looking into this.
