### ISSUE TITLE
Check if we can open the directory on Linux when UseShellExecute is set

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#23969]
I am creating this issue to track if we can open the directory on Linux when having ShellExecute is set. 

- Ideally we would want to throw exception only when UseShellExecute option was false. 

- In OSX, the program "open" successfully opens folder using "finder".  

- But Linux needs extra effort to be able to open a folder here. In Linux, xdg-open cannot open folder, so I decided to throw when startInfo.FileName is a directory, regardless of UseShellExecute option being true or false. 
Probably the failure happens when the OS doesnt have the installed libraries to open.
The current behavior in Linux is captured [here](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs#L67L71) 

Part of this goal is to keep a consistent behavior with Windows.

- When UseShellExecute is set on windows desktop, Process Start opens directory using File Explorer.

- Also, the current behavior in Windows running on .NET Core is captured [here](https://github.com/dotnet/corefx/blob/e670fd396d1c2a6ae99f2bb0ec24a81e30c668e7/src/System.Diagnostics.Process/tests/ProcessTests.cs#L134-L149
) 

Code Sample:
```
var startInfo = new ProcessStartInfo { UseShellExecute = true, FileName = Environment.CurrentDirectory };
                using (var px = Process.Start(startInfo)) { ... }
```
@tarekgh

**Comment by mellinoe** [comment]
Hmm, getting the "open a folder" functionality will be decidedly trickier. I guess the method would be different for each desktop environment (if one is even running). I know that Ubuntu, and I guess GNOME systems, use the "nautilus" application for the default file browser. You can run `nautilus <path>` to open a browser at the given folder. I suppose there are ways to detect which desktop environment is being used, but I'm definitely not an expert in that.

**Comment by danmosemsft** [comment]
> Moreover, Windows running on .NET Core has the following behavior:
1-When UseShellExecute is set: throws PlatformNotSupportedException with message "UseShellExecute must always be set to false"

You must have accidentally tried this on 1.x. On 2.0, .NET Core fully supports UseShellExecute on Windows, and it will pop explorer with the folder.

**Comment by TSlivede** [comment]
> But In Linux, xdg-open cannot open folder

Although the `xdg-open` manpage does not mention how to open a folder, calling `xdg-open /bin` works for me on my Ubuntu 14 VM, on my Xubuntu 14 VM and on WSL (Ubuntu 16) with LXDE installed.

It is also suggested on [stackexchange](https://elementaryos.stackexchange.com/questions/3073/how-can-i-opening-a-directory-from-the-terminal-in-a-new-session).

Therefore, I think a directory should not be a special case if `UseShellExecute` is set.

**Comment by maryamariyan** [comment]
@danmosemsft thanks for your comment, I updated the description for this issue accordingly, pointing to the tests in corefx that illustrate the latest behavior

**Comment by TSlivede** [comment]
After thinking about it, I believe `xdg-open` *does* officially support to open directories. The man page says `xdg-open opens a file or URL in the user's preferred application`. For unixoid operating systems, directories are just "special files". From [Wikipedia](https://en.wikipedia.org/wiki/Unix_file_types#Directory): `The most common special file is the directory`.

The manpage of `xdg-open` does not mention anything about only supporting `regular files` or forbidding `special files` or directories, so I think opening directories via `xdg-open` should be fine.

**Comment by maryamariyan** [comment]
PR #24017 fixes this issue.

**Comment by realvictorprm** [comment]
So with the referenced code it's possible to open a folder x-platform?

**Comment by danmosemsft** [comment]
@realvictorprm should be, try it out?
