### ISSUE TITLE
Error in .NET Standard 2.0-library: The type 'X' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

### ISSUE THREAD

**Issue by TheNovakExperience** [dotnet/corefx#23970]
Hello everyone!

I've been trying to find an open case just like mine but all I found so far has been references to preview versions. I'm currently using production-ready .NET Standard 2.0 and in my project I get the following errors:

`The type 'IList<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.`

and

`The type 'IEnumerable<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.`

This happens on the marked line as you can see on the screenshot below:

![capture](https://user-images.githubusercontent.com/29184014/30317343-27a08186-97aa-11e7-9a95-0303d5130cf3.PNG)

It doesn't really matter if I change to a different method. The same thing happens. My project file looks like the following:

```xml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<OutputPath>bin\debug\</OutputPath>
		<BaseIntermediateOutputPath>Cache</BaseIntermediateOutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<OutputPath>bin\release\</OutputPath>
		<BaseIntermediateOutputPath>obj</BaseIntermediateOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="pub\**" />
		<EmbeddedResource Remove="pub\**" />
		<None Remove="pub\**" />
		<None Remove="publish.ps1" />
		<None Remove="refresh.ps1" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="x.x.Shared.Models" Version="1.0.3-continuous" /><!-- My custom package -->
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="2.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.0.0" />
	</ItemGroup>
</Project>
```

Q1: How do I resolve this error?

Q2: In addition to the above, I cant find the "Add"-method for the IHeaderDictionary shown in the screenshot. Is there any special Nuget-package that I need?

**Comment by PowerCodr** [comment]
Workaround found. Had a custom cachepath (BaseIntermediateOutputPath) set on my debug-environment. Changing it to "default" name helped. Should it be like this?

**Comment by danmosemsft** [comment]
@wesh ?

**Comment by weshaggard** [comment]
@TheNovakExperience you may be hitting an issue in the SDK (perhaps https://github.com/dotnet/sdk/issues/803) where things don't work as expected when overriding that property.
