### ISSUE TITLE
RegularExpressionAttribute overload for Regex parameter

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/corefx#23971]
This is an API idea. It might not be a good idea.

Perhaps the [`RegularExpressionAttribute`](https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/RegularExpressionAttribute.cs) class ought to have a constructor overload that takes a parameter of the [`Regex`](https://github.com/dotnet/corefx/blob/master/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs) type?

```cs
        public RegularExpressionAttribute(Regex pattern)
            : base(() => SR.RegexAttribute_ValidationError)
        {
            Pattern = pattern.ToString();
            MatchTimeoutInMilliseconds = 2000;
        }
```

**Comment by henkmollema** [comment]
`Regex` is a complex type and can not be used as parameter for an attribute. Only primitive types (or arrays of them) can be used as attribute parameters.

Consider this example:
```cs
public class FooAttribute : Attribute
{
    public FooAttribute(Regex regex)
    {
    }
}

[Foo(new Regex(@"\d"))]
public class MyClass
{
}
```

Will result in this compiler error:
> Attribute constructor parameter 'regex' has type 'Regex', which is not a valid attribute parameter type

**Comment by vanillajonathan** [comment]
Ah thanks. Bad idea then. Sorry.
