### ISSUE TITLE
Add OSPlatform.FreeBSD API

### ISSUE THREAD

**Issue by wfurt** [dotnet/corefx#23989]
### Rationale and Usage

There is code all around core-setup, cli and perhaps elsewhere which looks like

```c#
if (System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(
        System.Runtime.InteropServices.OSPlatform.OSX))
{
....
}
```

We would like to also target FreeBSD as a platform. 
FreeBSD is not officially supported but partial support is sprinkled through coreclr and corefx at least. 

### Proposed API
This adds FreeBSD property same way as it is done for current OSes. (Windows, Linux and OSX) 

```diff
namespace System.Runtime.InteropServices
{
    public struct OSPlatform : IEquatable<OSPlatform>
    {
        private readonly string _osPlatform;

+       public static OSPlatform FreeBSD { get; } = new OSPlatform("FREEBSD");
+ 
        public static OSPlatform Linux { get; } = new OSPlatform("LINUX");

        public static OSPlatform OSX { get; } = new OSPlatform("OSX");

        public static OSPlatform Windows { get; } = new OSPlatform("WINDOWS");

        private OSPlatform(string osPlatform)
        {
            if (osPlatform == null) throw new ArgumentNullException(nameof(osPlatform));
            if (osPlatform.Length == 0) throw new ArgumentException(SR.Argument_EmptyValue, nameof(osPlatform));

            _osPlatform = osPlatform;
        }

```

We may consider adding other BSD flavors or other operating systems but reasonable support is probably not anywhere close. For FreeBSD, there is some community interest. 

### Pull Request

 #23986

**Comment by wfurt** [comment]
Request for FreeBDS support @karelz

**Comment by mellinoe** [comment]
I don't think there's any problem with adding it now, even if the full support is still being worked out through the stack. Worst case scenario: `IsOSPlatform(FreeBSD)` returns "false" while the work is still in flight. I'm sure the support will eventually get there regardless, and I can't think of any other way to express the platform other than this.

**Comment by wfurt** [comment]
The note was more about OpenBSD, NetBSD, Plan9 etc. Sorry if that was not clear @mellinoe

**Comment by stephentoub** [comment]
When discussing these convenience properties previously, we'd decided that we would add new OSPlatform static properties for a platform when support in coreclr/corefx was far enough along that the system was actually usable, e.g. that the majority of corefx unit tests ran and passed.  I don't think we're there yet (correct me if I'm wrong).  We can still add support for "FREEBSD" in the implementation, such that code can do `if (RuntimeInformation.IsOSPlatform(new OSPlatform("FREEBSD")) { ... }` and have that work correctly, we should just be cautious about adding public surface area until it's meaningful.

**Comment by karelz** [comment]
Once we have the API, we should replace any existing workarounds (`new OSPlatform("FREEBSD")`) with the newly added property.

Marking the API as blocked and api-needs-work again. We can flip it to api-ready-for-review / api-approved, once there is enough progress on the OS.

**Comment by joshfree** [comment]
Just a note that I think "BSD" is a better API than something specific like "FreeBSD".  We should have this property be usable for [FreeBSD, NetBSD, OpenBSD, DragonFly BSD](https://en.wikipedia.org/wiki/Comparison_of_BSD_operating_systems)...

https://en.wikipedia.org/wiki/List_of_BSD_operating_systems

**Comment by wfurt** [comment]
note that they are distinct operating systems and chunks of code needs to account for that. 
Lumping them to single bucket seem inappropriate.

**Comment by bartonjs** [comment]
@joshfree That wikipedia page says, to me, that FreeBSD, NetBSD, and OpenBSD are the "not compatible with each other" progenitors of many smaller projects.  So "FreeBSD" is still potentially interesting vs "OpenBSD" or "NetBSD".

**Comment by joshfree** [comment]
I think I'd like to see more data on the differences still.

**Comment by wfurt** [comment]
What exactly are you looking for @joshfree? As minimum, there is no binary compatibility. 
That seems different enough to me. 

cc: @krytarowski  to advocate for NetBSD.

**Comment by krytarowski** [comment]
I'm in SFBA right now and can look at it next week.

**Comment by bartonjs** [comment]
At a minimum, prebuilt packages can still be added on OpenBSD via `pkg_add`, and on FreeBSD they can't (FreeBSD got rid of (their version of) pkg_add during the 9.3 -> 10.0 upgrade).

I don't really know what the real-world usage is for this particular API, so maybe that's not fair.  But I don't know that we'd lump macOS into "BSD", making our distinction sort of arbitrary.

**Comment by krytarowski** [comment]
I oppose to add a BSD target, because it's lost ship 25 years ago. Systems diverged too much to make it usable and they keep diverging.

Also BSD refers too BSD4.4-code, which is no longer really by supported by modern BSDs. More sense makes a generic check for POSIX or UNIX.
