### ISSUE TITLE
Possible race condition in ICommand WinRT adapter

### ISSUE THREAD

**Issue by TautvydasZilys** [dotnet/corefx#23990]
I'm been digging through some more interop code in CoreFX and came across this:

https://github.com/dotnet/corefx/blob/master/src/System.Runtime.WindowsRuntime/src/System/Runtime/InteropServices/WindowsRuntime/MarshalingHelpers.cs#L380

This line looks to be a race condition: GetValueFromEquivalentKey method loops through the table entries in a foreach loop and it doesn't lock the table before doing so. I believe that if you happen to add an entry to the table on another thread by calling add_CanExecuteChanged method on any instance of ICommand, the enumerator would get invalidated and it would throw an exception.

**Comment by stephentoub** [comment]
> I believe that if you happen to add an entry to the table on another thread by calling add_CanExecuteChanged method on any instance of ICommand, the enumerator would get invalidated and it would throw an exception.

ConditionalWeakTable's enumerator supports concurrent reading like that.  It does not get invalidated by concurrent changes to the table (though it's also not guaranteed to reflect those changes in that enumeration).
