### ISSUE TITLE
MulticastInterface_Set_AnyInterface_Succeeds test hangs on Fedora

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#24008]

**Comment by stephentoub** [comment]
cc: @tmds

**Comment by stephentoub** [comment]
Likely due to https://github.com/dotnet/corefx/issues/24036

**Comment by wfurt** [comment]
Should be roll back the changes @stephentoub since https://github.com/dotnet/corefx/issues/24036 was resolved?

**Comment by stephentoub** [comment]
> Should we roll back the changes @stephentoub since #24036 was resolved?

What changes?

**Comment by wfurt** [comment]
https://github.com/dotnet/corefx/pull/24010 
With CI changes the test should pass on Fedora.

**Comment by stephentoub** [comment]
Yes, if the test passes, we should remove the ActiveIssue from it.

**Comment by wfurt** [comment]
fixed by #25552
