### ISSUE TITLE
System.Runtime.Serialization.Primitives version 4.2.0.0

### ISSUE THREAD

**Issue by desmondgc** [dotnet/corefx#24018]
I recently started migrating some library projects to .NET Standard 2.0.

In my solution, I have a .NET 4.6.1 WPF application, a .NET 4.6.1 test project, and a handful of .NET Standard 1.4 and .NET Standard 2.0 class libraries. Since targeting .NET Standard 2.0, tests are failing with the following error:

```
System.IO.FileLoadException : Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  ----> System.IO.FileLoadException : Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

I had many headaches with System.Runtime.Serialization.Primitives and binding redirects when first targeting .NET Standard 1.4 (ref: #16823). I was able to resolve most issues by installing System.Runtime.Serialization.Primitives package version 4.3.0 explicitly in pretty much every project and adding the following binding redirect:

```
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.Serialization.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.2.0" newVersion="4.1.2.0" />
      </dependentAssembly>
```

Now I'm not sure what to do to move forward. I can't seem to find a package available that provides System.Runtime.Serialization.Primitives version 4.2.0.0, and attempting to update the binding redirect to downgrade from 4.2.0.0 to 4.1.2.0 has no effect (I don't think the test runner honors the project's binding redirects).

**Comment by danmosemsft** [comment]
@ericstj thoughts?

**Comment by ericstj** [comment]
This is due to the injected support for NETStandard 2.0.  We inject new assemblies into NET 4.6.1 and later desktop projects in order to add support for netstandard2.0.  We do this in targets now instead of packages because its no longer a requirement to reference a package to build a netstandard library.  This injection happens whenever we see a netstandard1.5 or greater library referenced (see https://github.com/dotnet/sdk/issues/1386).

The best thing to do is set up your project to use automatic bindingRedirects.  See https://github.com/dotnet/standard/issues/481 for more details.

**Comment by desmondgc** [comment]
Thank you for clarifying. After reading dotnet/standard#481 I have a better understanding of what's happening under the hood. We were in a precarious situation because we were relying on ClickOnce "publish" functionality in Visual Studio which adds some additional hurdles with respect to .NET Standard. One of our DevOps guys was able to rejig our build process to do all the ClickOnce packaging manually which simplified everything.

The issue has been resolved (for now) after upgrading several packages and removing manually-defined binding redirects from every project.
