### ISSUE TITLE
System.Runtime.CompilerServices.Unsafe does not have Windows file metadata

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#24012]
Due to the way we build ilproj files, System.Runtime.CompilerServices.Unsafe.dll does not have Windows file metadata.

![image](https://user-images.githubusercontent.com/8918977/30396460-8c7e8b0a-987e-11e7-87f9-761af0d91d51.png)

We do have the equivalent managed attributes defined in IL: https://github.com/dotnet/corefx/blob/master/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.il#L12-L17.
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.il#L40

Apparently, getting the Windows file metadata embedded can be accomplished using a .res file. We could easily pass that file into the parameters of ILAsm (/RESOURCE:<file>), assuming the option is supported everywhere -- including non-Windows platforms. I'm not sure there is an easy way to generate this resource file, though.

@eerhardt

**Comment by mellinoe** [comment]
@ericstj @weshaggard

**Comment by ericstj** [comment]
I think we need to pass a res file to ilasm.

**Comment by mellinoe** [comment]
@jkotas Is the /RESOURCES flag supported outside of Windows? It looks like it [may not be](https://github.com/dotnet/coreclr/blob/7bb5207734cce3c267032a85331a8891dbdf44dd/src/ilasm/writer.cpp#L1304-L1306), but I'm not positive.

We could maintain a .res file for use in the Windows build. Ideally it would get auto-generated along with  [this line](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.il#L40) getting updated (we can use another #include'd file to accomplish that).

**Comment by jkotas** [comment]
> Is the /RESOURCES flag supported outside of Windows? 

Right, it is not supported in ilasm outside of Windows.

The easiest option compatible with cross-plat may be some flavor of IL merge of C# envelope with the class written in IL. I believe that ILLink can do IL merging already, or it should be pretty close.

**Comment by jkotas** [comment]
Or we can switch over to CoreLib implementation of Unsafe for .NET Core. There is internal incomplete Unsafe implementation in CoreLib today - we can make it complete & public.

This won't solve the problem for the netstandard versions of the library, but do we need them to be building perfectly outside of Windows?

**Comment by ericstj** [comment]
> This won't solve the problem for the netstandard versions of the library. Do we need them to be building perfectly outside of Windows?

No, the ones we ship come from the `-allConfigurations` build which happens on windows.  If the netcoreapp version switched to a facade (built with csproj) that would fix the problem.

**Comment by jkotas** [comment]
We may rather rip out System.Runtime.CompilerServices.Unsafe from netcoreapp.

**Comment by joperezr** [comment]
I'm working on a fix for this now

**Comment by joperezr** [comment]
Flagging the issue as Servicing-Consider given that this was an ask from an internal team which needs the header information on our assembly to be present in order to be ingested by their team.

**Comment by joperezr** [comment]
Reopening to track the insertion of this into release branch.

**Comment by karelz** [comment]
Fixed in release/2.1 in PR #31806. Will be part of 2.1.5.
