### ISSUE TITLE
stack smashing detected

### ISSUE THREAD

**Issue by hezc13** [dotnet/corefx#24028]
when I was debuging the project with VSCode on ubuntu16.04,I met with the "stack smashing detected" exception and the project paused immediately.This exception occurs when the program try to load a .so file that is programed in C and compiled by GCC on ubuntu16.04 .The program attempt to access a function defined in the .so file and then the "stack smashing detected" exception comes along.I try to fix it but failed
## the code is here:
`[DllImport("TripleDES.dll", CallingConvention = CallingConvention.Cdecl)]
static extern int data_convert([MarshalAs(UnmanagedType.LPArray)]byte[] indata, int in_len, [MarshalAs(UnmanagedType.LPArray)]byte[] outdata, int flag, [MarshalAs(UnmanagedType.LPArray)] byte[] key);`
## I use the data_convert function here:
`byte[] toEncrypt = Encoding.UTF8.GetBytes(this.GetString(strString));
 byte[] key = Encoding.UTF8.GetBytes(this.GetKeyCode(this.Keys));
 byte[] result = new byte[256];
 int count = data_convert(toEncrypt, en_len, result, 1, key);
 byte[] resultBytes = new byte[count];
 Array.Copy(result, 0, resultBytes, 0, count)`
## the data_convert function in the .c file :
`int  data_convert(unsigned char *in,int in_len,unsigned char * out,char flag,unsigned char *key)`

**Comment by stephentoub** [comment]
Your DllImport defines `flag` as an `int`, which is four bytes, whereas your native export defines `flag` as `char`, which is one byte.

**Comment by hezc13** [comment]
I have modified the defination as follows:
## the DLL declaration:
`[DllImport("3desintf.so",EntryPoint="data_convert")]

static extern int data_convert([MarshalAs(UnmanagedType.LPArray)]byte[] indata,int in_len,
[MarshalAs(UnmanagedType.LPArray)]byte[] outdata,int flag,[MarshalAs(UnmanagedType.LPArray)]byte[] key);`
## the data_convert function :
`int  data_convert(unsigned char *in,int in_len,unsigned char * out,int flag,unsigned char *key)`
but the exception is still there

**Comment by stephentoub** [comment]
What calling convention does the native function expect, and have you tried setting that on the DllImport?

**Comment by hezc13** [comment]
However,when I compiled the same .c file to .dll file and used it in the same project in VS2015 on Windows ,it went normally.

**Comment by stephentoub** [comment]
Other things to look at besides validating the calling convention would be things like whether the bitness of the .NET process matches that of the compiled C binary, whether the data_convert native function itself is actually correct or whether it has a bug and is writing over stack memory it shouldn't be, whether sizeof(int) in the C function is 4 as expected, etc.
