### ISSUE TITLE
Proposal: Add protected {Unmanaged}MemoryStream.Read/WriteSpan method

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#24039]
We've added new virtual `Read(Span<byte>)` and `Write(ReadOnlySpan<byte>)` methods to Stream, and overridden them on MemoryStream and UnmanagedMemory stream.  However, these new overrides can't just directly write to the in-memory storage: existing types derived from these that override the existing Read/Write virtuals would have their logic skipped until they also overrode the new property.  To address that, these overrides check the concrete type of the stream (e.g. `if (GetType() == typeof(MemoryStream)`), writing directly to the storage of it's not a derived type, and delegating to the existing virtuals if it is a derived type.  This, however, causes a potential perf issue for a derived type.  It's often the case with such derived types that they do a bit of work and then delegate to the base implementation, but that base implementation will then proceed to see that it's a derived type and skip the efficient path.  To re-enable that efficiency, we need a way for the derived type overriding the new virtuals to call the efficient implementation and skip the type check.  I propose we add the following:

```C#
class MemoryStream & class UnmanagedMemoryStream
{
    protected void WriteSpan(ReadOnlySpan<byte> source);
    protected int ReadSpan(Span<byte> destination);
}
```
to both MemoryStream and UnmanagedMemoryStream.

cc: @JeremyKuhne, @ianhays, @KrzysztofCwalina, @ahsonkhan

**Comment by karelz** [comment]
FYI: The initial API review discussion was recorded - see https://youtu.be/m4BUM3nJZRw?t=6574 (10 min duration)

**Comment by terrajobst** [comment]
@KrzysztofCwalina suggested to generalize this beyond these two types; @stephentoub said he has to think about to do this and whether it's even possible.

**Comment by JeremyKuhne** [comment]
@stephentoub I'm moving this to future- have you thought about @KrzysztofCwalina's suggestions?

**Comment by stephentoub** [comment]
I'm going to close this until there's actually a demonstrated need for it.  We've not seen one since this issue was originally theorized in the 2.1 timeframe.
