### ISSUE TITLE
Update CI Fedora firewall rules

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#24036]
We had some issue in the past where MulticastInterface_Set_AnyInterface_Succeeds was hanging on Fedora CI. This was discussed here: https://github.com/dotnet/corefx/issues/13323. Resolution was to update the firewall rules to make the test pass:

> find the local port range by executing sysctl net.ipv4.ip_local_port_range
to allow a udp port range do something like this: firewall-cmd --zone=public --add-port=4990-4999/udp
adding the --permanent flag will make this persistent. You need to restart the firewall to make it use the permanent rule.

This test is now hanging again and is disabled on Fedora: https://github.com/dotnet/corefx/pull/24010

Perhaps the new Fedora CI machines (Fedora 25 and 26) are not configuring the firewall?

CC @stephentoub @Priya91 @MattGal

**Comment by stephentoub** [comment]
> Perhaps the new Fedora CI machines (Fedora 25 and 26) are not configuring the firewall?

I think that's very likely. Assuming it is, we should a) fix the machines and b) add these details to the test as a comment. Or alternatively just add other comment and continue to leave the test disabled on Fedora.

cc: @mattgal, @geoffkizer

**Comment by tmds** [comment]
Maybe we can have some doc that describes the required machine config? I don't like the idea of disabling tests, but I wouldn't want to go and debug this hang either when I run the tests.

**Comment by tmds** [comment]
I will also have a look at why this test hangs instead of failing.

**Comment by stephentoub** [comment]
(It should no longer permanently hang... it should now timeout after 20 seconds or so. I fixed that at the same time as disabling it.)

**Comment by MattGal** [comment]
For our test execution machines, opening up ports is fine, but for external developers trying to run these tests on Fedora that might be a hard pill to swallow.  Is it actually impossible to make the tests work (pass and test what they're supposed to) without opening ports on the executing machine?

**Comment by MattGal** [comment]
@stephentoub FYI, the port range has been changed on all Helix Fedora machines.  I validated this by running test bits built from 9/10 before the "skip on Fedora" behavior was added, and should fix this for .Open (CI) queues as well.

**Comment by stephentoub** [comment]
Thanks, @MattGal!

**Comment by wfurt** [comment]
It seems like this is working now. closing.
