### ISSUE TITLE
cn-win7 , error on load assembly System.Private.CoreLib

### ISSUE THREAD

**Issue by cscer** [dotnet/corefx#24031]
Assert Failure
Expression: [Recursive resource lookup bug]
Description: Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: Argument_AbsolutePathRequired
Stack Trace:
   at System.SR.InternalGetResourceString(String key)
   at System.SR.GetResourceString(String resourceKey, String defaultString)
   at System.Reflection.Assembly.LoadFile(String path)

where is the file System.Private.CoreLib.resource

**Comment by clegendre** [comment]
Hello, 
We ran into the same issue.
See here for the workaround. https://github.com/dotnet/corefx/issues/23608

Tested, it works...

**Comment by cscer** [comment]
set  UICulture to 1033  ,it works
