### ISSUE TITLE
When using Process.Start with UseShellExecute,the process is null on some windows runtimes

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#24048]
**Summary**: using Process.Start when UseShellExecute is set, returns null process on some windows runtimes when it is used to open a file. Code sample

```
using (var px = Process.Start(new ProcessStartInfo { UseShellExecute = true, FileName = fileToOpen })) 
{ ... /* px is null */ }
```

Refer to existing test in corefx ([here](https://github.com/dotnet/corefx/blob/a16368dc4694c0334a8794107a9e868020f0bed5/src/System.Diagnostics.Process/tests/ProcessTests.cs#L182)):
*ProcessStart_UseShellExecute_OnWindows_DoesNotThrow(isFolder:false)*

Process px was null using ([logs](https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows_prtest/56/consoleFull#19963278882d31e50d-1517-49fc-92b3-2ca637122019)):
```
ProductType=8InstallationType=Server OS=Microsoft Windows 6.3.9600 OSVer=Microsoft Windows NT 6.2.9200.0 OSArch=X64 Arch=X64 Framework=.NET Core 4.6.25714.01
```
but when running the same test on another Windows NT machine (Win 10) locally, the process is not null:
```
ProductType=4InstallationType=Client OS=Microsoft Windows 10.0.15063 OSVer=Microsoft Windows NT 6.2.9200.0 OSArch=X64 Arch=X64 Framework=.NET Core 4.6.25714.01
```

Code sample to help with debugging:
```     
        private void DumpRuntimeInformationToConsole()
        {
            // Not really a test, but useful to dump to the log to
            // sanity check that the test run or CI job
            // was actually run on the OS that it claims to be on
            string dvs = PlatformDetection.GetDistroVersionString();
            string osd = RuntimeInformation.OSDescription.Trim();
            string osv = Environment.OSVersion.ToString();
            string osa = RuntimeInformation.OSArchitecture.ToString();
            string pra = RuntimeInformation.ProcessArchitecture.ToString();
            string frd = RuntimeInformation.FrameworkDescription.Trim();

            Console.WriteLine($@"{dvs} OS={osd} OSVer={osv} OSArch={osa} Arch={pra} Framework={frd}");
        }
```

**Comment by stephentoub** [comment]
From the docs:
>Return Value
Type: System.Diagnostics.Process
A new Process that is associated with the process resource, **or null if no process resource is started**. Note that a new process that’s started alongside already running instances of the same process will be independent from the others. In addition, Start may return a non-null Process with its HasExited property already set to true. In this case, the started process may have activated an existing instance of itself and then exited.

**Comment by danmosemsft** [comment]
What is the file @maryamariyan  ? Your code snippet at the top is not a repro.

Certainly this can happen eg., if you have UseShellExecute and invoke a folder on Windows. Under the covers ShellEXecuteEx need not return a process:

> Note  ShellExecuteEx does not always return an hProcess, even if a process is launched as the result of the call. For example, an hProcess does not return when you use SEE_MASK_INVOKEIDLIST to invoke IContextMenu.

https://msdn.microsoft.com/en-us/library/windows/desktop/bb759784(v=vs.85).aspx

The only question then is whether it ought to in this case, but this issue does not have a repro in it.

**Comment by Petermarcu** [comment]
@maryamariyan, @danmosemsft is the repro the [linked test case](https://github.com/dotnet/corefx/blob/a16368dc4694c0334a8794107a9e868020f0bed5/src/System.Diagnostics.Process/tests/ProcessTests.cs#L182)? Was this test flaky and this was happening just on certain machines?

I see logging was added in the case where the null is returned but I'm not sure anyone is watching for it so we can get [this](https://github.com/dotnet/corefx/blob/a16368dc4694c0334a8794107a9e868020f0bed5/src/System.Diagnostics.Process/tests/ProcessTests.cs#L180,L183) cleaned up.

**Comment by maryamariyan** [comment]
@Petermarcu we ended up removing the log. here's what the test case looks like in master branch [now](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/tests/ProcessTests.cs#L175)

It's supposed to be tracked by this issue

**Comment by Petermarcu** [comment]
Ok, so we're curious why we are still getting null sometimes and this issue is tracking us trying to understand why that can be? Do we need to track it or just close this issue at this point?

**Comment by maryamariyan** [comment]
That's right.

Sure, we could close the issue if we don't need to track it using this issue.

**Comment by danmosemsft** [comment]
Let's close this because it isn't important unless folks hit it and it's a problem. BTW, this is a good reason why its best not to put issue ID's into the implementation code, as now it needs  a change to remove "tracked by 24048"

**Comment by Petermarcu** [comment]
There is also another comment a little further up that I wouldn't want to see in code. That should be cleaned up too. 

// Not sure why px returned is null. but the call does not throw and opens folder successfully.
