### ISSUE TITLE
HttpUtility - Add Mono copyright line

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#24043]
We forgot to add Mono copyright lines to HttpUtility.cs when we reused the code.
See https://github.com/dotnet/corefx/pull/23918#issuecomment-329558714 for more details.

**Comment by karelz** [comment]
Affected file:
* [HttpUtility.cs](https://github.com/dotnet/corefx/blob/master/src/System.Web.HttpUtility/src/System/Web/HttpUtility.cs) - see copyright in [Mono](https://github.com/mono/mono/blob/0af1ea70c29a66a59765183b45d6b75fa6c3d8fa/mcs/class/System.Web/System.Web/HttpUtility.cs#L3-L30)

Note: [HttpUtilityTests.cs](https://github.com/dotnet/corefx/blob/master/src/System.Web.HttpUtility/tests/HttpUtility/HttpUtilityTest.cs#L4-L30) is OK (from [Mono source code](https://github.com/mono/mono/blob/0af1ea70c29a66a59765183b45d6b75fa6c3d8fa/mcs/class/System.Web/Test/System.Web/HttpUtilityTest.cs#L4-L27))

@alexperovich can you please review the list of files? Were there more files you might have missed?

**Comment by danmosemsft** [comment]
Alex I looked at the other 4 files in the lib (in the utils folder) and you missed the headers on those, however the Mono versions only have Microsoft headers (from reference source) so I guess it's fine.
