### ISSUE TITLE
Few questions about the Memory

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/corefx#24067]
Hello guys!

I am currently trying to update my blog post/presentation about Span. I read the code and I have few questions. I hope that you can help me to get a better understanding.

1. One of the reasons for making `Span` and `ReadOnlySpan` a stack-only types was to avoid struct tearing. `Memory` is a struct and it consist of 3 fields. By design it's not stack-only. Is it not going to suffer from struct tearing? Why is it not a class?
2. `ReadOnlyMemory.DangerousTryGetArray` is breaking the encapsulation by exposing `ArraySegment` which allows to modify the content via indexer (it has a setter). It's hidden from the IDE via `EditorBrowsable` attribute and has a name that indicates the consequences. Is this method really needed? Why not to introduce new type like `ReadOnlyArraySegment` ?

cc @KrzysztofCwalina @jkotas

**Comment by KrzysztofCwalina** [comment]
Memory needs to be a struct to allow cheap slicing and to be an allocation-free factory of spans. It's a tradeoff between safety and efficiency.

ReadOnlyArraySegment would mean that now we need to have 2 overloads for APIs that otherwise take ReadOnlyMemory. 

cc: @ahsonkhan, @stephentoub

**Comment by jkotas** [comment]
System.Memory does not provide as nice safety guarantees as Span. We will need very good documentation that explains how to use it correctly what to avoid. Related to #23863.

**Comment by adamsitnik** [comment]
thanks for the explanation!
