### ISSUE TITLE
Add HashSet.AddRange

### ISSUE THREAD

**Issue by GSPP** [dotnet/corefx#2406]
This is a very useful method. The other collection classes have it as well. It should be in the framework.

**Comment by rickbrew** [comment]
What about having a set of extension methods for `ICollection<T>` ? No need to limit this to `HashSet<T>` :)

```
public static void AddRange<T>(this ICollection<T> collection, IEnumerable<T> items)
{
    // ... obvious code goes here ...
}
```

**Comment by mikedn** [comment]
What is `AddRange` supposed to do? It seems to me that you're looking for `UnionWith`.

**Comment by GSPP** [comment]
Hah! I did not know about `UnionWith`. Thanks, I guess that settles it. Adding a redundant AddRange method probably is not great API design.
