### ISSUE TITLE
Span extension method to slice off of a string instance

### ISSUE THREAD

**Issue by jnm2** [dotnet/corefx#24072]
# [Current API proposal](https://github.com/dotnet/corefx/issues/24072#issuecomment-347610584)

TODO (see https://github.com/dotnet/corefx/issues/24072#issuecomment-349412729): Add array overloads. Consider ArraySegment overloads for consistency.

```cs
public static class MemoryExtensions
{
    public static ReadOnlySpan<char> AsReadOnlySpan(this string text, int start);
    public static ReadOnlySpan<char> AsReadOnlySpan(this string text, int start, int length);
    public static ReadOnlyMemory<char> AsReadOnlyMemory(this string text, int start);
    public static ReadOnlyMemory<char> AsReadOnlyMemory(this string text, int start, int length);
}
```

----

# Original post

I expected to see these:

```cs
class System.SpanExtensions
{
    public static ReadOnlySpan<char> Slice(this string text, int start);
    public static ReadOnlySpan<char> Slice(this string text, int start, int length);
}
```

But now I also see a proposal for a non-stack-only [`StringSegment`](https://github.com/dotnet/corefx/issues/20378) type. So I have two questions.

 1. Is there a clearly preferable return type for such an extension method?
 2. Is the most efficient way to slice a string `str.AsReadOnlySpan().Slice(...)`, or is there a single method call I can make that I haven't found yet? That's a little verbose for my liking, even if the two calls are inlined.

**Comment by karelz** [comment]
cc @stephentoub

**Comment by stephentoub** [comment]
cc: @KrzysztofCwalina, @ahsonkhan 

> Is the most efficient way to slice a string

Currently, yes.

> I expected to see these

We've discussed adding such overloads.  @KrzysztofCwalina would likely know the current plan.

> Is there a clearly preferable return type for such an extension method?

For now `StringSegment` doesn't exist.  I expect we'll have such discussions as part of considering adding it.

**Comment by ahsonkhan** [comment]
>  2. Is the most efficient way to slice a string `str.AsReadOnlySpan().Slice(...)`, or is there a single method call I can make that I haven't found yet? That's a little verbose for my liking, even if the two calls are inlined.

Yes, that is how you would slice a string. I would imagine you would grab a span from a string once (i.e. call str.AsReadOnlySpan()) and then pass that span around and slice multiple times using span.Slice().

cc @KrzysztofCwalina

**Comment by KrzysztofCwalina** [comment]
Last time I discussed this with @jaredpar and @MadsTorgersen the conclusion was that we need to be super sure that ReadOnlySpan\<char\> is the best representation for string slices to take the plunge and bur the best name (Slice) for a method returning ROS\<char\>. 

I think there are two cadidate types for the repserantation: ROS\<char\> and something like ReadOnlyMemory\<char\>. The former is safe and fast, but with all the restrictions of ref-like types. The later is subject to tearing, slower, but convinient to use.

**Comment by KrzysztofCwalina** [comment]
We have gotten lots of feedback that the current str.AsReadOnlySpan().Slice(from, length) is to verbose.
Maybe a good compromise would be to add:

```c#
class System.MemoryExtensions
{
    public static ReadOnlySpan<char> AsReadOnlySpan(this string text, int start);
    public static ReadOnlySpan<char> AsReadOnlySpan(this string text, int start, int length);
}
```

@MadsTorgersen, @jaredpar, @stephentoub, @ahsonkhan?

**Comment by stephentoub** [comment]
I'd be fine with such overloads.

**Comment by KrzysztofCwalina** [comment]
@jnm2, could you please update the API design at the top of this issue? ... I will mark it as ready for API review then.

**Comment by jnm2** [comment]
Oh, forgot this was one I started. 😄 Done.

**Comment by terrajobst** [comment]
That seems like a good suggestion, but we should do the same for arrays.

**Comment by karelz** [comment]
There seem to be also similar extension for `ArraySegment` @KrzysztofCwalina does it make sense to make it consistent with string and array overloads we are adding here?

**Comment by karelz** [comment]
FYI: The API review discussion was recorded - see https://youtu.be/BI3iXFT8H7E?t=3913 (13 min duration)
