### ISSUE TITLE
Error while copying content to a stream.

### ISSUE THREAD

**Issue by shao200** [dotnet/corefx#24074]
my Desktop Code is follow:
```c#
    HttpResponseMessage response = await Client.GetAsync(ActionStringBase + "/" + id.ToString());
    var sinstal = await response.Content.ReadAsStringAsync();
    //var sinstal=await Client.GetStringAsync(ActionStringBase + "/" + id.ToString());
    var jsspp = new JsonSerializerSettings { DefaultValueHandling = DefaultValueHandling.Ignore };
    var _Data = JsonConvert. DeserializeObject<T>(sinstal, jsspp);
```
webapi code is follow:
if code is that
```c#
 public IActionResult Get(int id)
{
    var table = _dbContext.Cmodel3Ds.Find(id);
    return json(table);
}
```
return no problem
if code add Include or _dbcontext.entity(x).collection(r=>r.inve....) 
then on Desktop Throw "Error while copying content to a stream."
o,db in property of table is contain some binary(max)
 
[EDIT] Add C# syntax highlighting by @karelz

**Comment by davidsh** [comment]
Is this on .NET Framework or .NET Core?  .NET Framework bugs are not tracked in this repo.

Also, please attach a full Visual Studio solution that repro's this problem.  The code snippet above is not sufficient to repro this issue for us.

**Comment by shao200** [comment]
think you!
my system structure is:
Desktop(framework4.62)<-->WrapLib httpClient (standard2.0)<-->Webapi(net.core2.0)framework4.62

**Comment by davidsh** [comment]
>Desktop(framework4.62)<-->WrapLib httpClient (standard2.0)<-->Webapi(net.core2.0)framework4.62

Thank you for describing the architecture.  However, we really need a complete Visual Studio solution so that we can easily compile all the source files and include the same NuGet packages that you are using.  That will help us to repro.

You can simply zip up your Visual Studio solution and attach it to this issue.

**Comment by shao200** [comment]
[CoordinationStandard.zip](https://github.com/dotnet/corefx/files/1308032/CoordinationStandard.zip)

[WpfClient.zip](https://github.com/dotnet/corefx/files/1308037/WpfClient.zip)
thank you .

**Comment by shao200** [comment]
Server side deployed in Aliyun, is an IIS  DataBase WebAPI

**Comment by shao200** [comment]
Server-side deployment in Aliyun, is an IIS APIs is a very simple table add, delete, change, check. One of the tables is a self associated table, and I want to get his tree, so I add include and entity (r=>r. XXX) to the controller, which has data within it. Collection. But through JSON, with HttpClient to accept the error. Some of the fields of the child table associated with the tree are some relatively large binary data, and the fields are binary (max).

**Comment by shao200** [comment]
在 System.Net.Http.HttpContent.d__49.MoveNext() --- 引发异常的上一位置中堆栈跟踪的末尾 --- 在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 在 System.Net.Http.HttpClient.d__58.MoveNext() --- 引发异常的上一位置中堆栈跟踪的末尾 --- 在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() 在 CoordinationStandard.Common.WebObject`1.d__18.MoveNext() --- 引发异常的上一位置中堆栈跟踪的末尾 --- 在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() 在 CoordinationProject.Coordination.Dbtowpf3d.d__1.MoveNext() 位置 D:\Visual Studio 2017\Projects\CoordinationProject\CoordinationProject\Coordination\Dbtowpf3d.xaml.cs:行号 37

**Comment by Priya91** [comment]
@davidsh Were you able to verify the repro?

**Comment by karelz** [comment]
@shao200 can you please provide a minimal repro? (ideally without database, ASP.NET, WPF, etc.)

**Comment by karelz** [comment]
No response, closing. Feel free to reopen when there is more info available.
