### ISSUE TITLE
Use buffer pooling in DeflateManaged in System.IO.Compression

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#24083]
Here are some candidates:
https://github.com/dotnet/corefx/blob/8d40fac24b4a1fdaacd46ae923f3258da1996e16/src/System.IO.Compression/src/System/IO/Compression/DeflateManaged/DeflateManagedStream.cs#L106
https://github.com/dotnet/corefx/blob/8d40fac24b4a1fdaacd46ae923f3258da1996e16/src/System.IO.Compression/src/System/IO/Compression/DeflateManaged/DeflateManagedStream.cs#L123
https://github.com/dotnet/corefx/blob/8d40fac24b4a1fdaacd46ae923f3258da1996e16/src/System.IO.Compression/src/System/IO/Compression/DeflateManaged/FastEncoderWindow.cs#L69-L71
https://github.com/dotnet/corefx/blob/8d40fac24b4a1fdaacd46ae923f3258da1996e16/src/System.IO.Compression/src/System/IO/Compression/DeflateManaged/HuffmanTree.cs#L127
https://github.com/dotnet/corefx/blob/8d40fac24b4a1fdaacd46ae923f3258da1996e16/src/System.IO.Compression/src/System/IO/Compression/DeflateManaged/OutputWindow.cs#L24

Consider reusing some of these arrays in a buffer pool.

While we are at this we should make the buffer size tunable: https://github.com/dotnet/corefx/blob/3fca26cedf6c54aabc100e69106fc7e263db7815/src/System.IO.Compression/src/System/IO/Compression/DeflateZLib/DeflateStream.cs#L116

**Comment by stephentoub** [comment]
@ianhays, where is the managed implementation still used?  Is it just used when decompressing Deflate64 files?  If there are places we can avoid the large array allocations, great, just wondering about priority.

**Comment by ianhays** [comment]
>where is the managed implementation still used? Is it just used when decompressing Deflate64 files? 

Correct, it is only used to decompress Deflate64 (which is seldom used).

> If there are places we can avoid the large array allocations, great, just wondering about priority.

I'd rank it pretty low down on priority. The main scenario for which we hit the managed implementation is when we're dealing with Windows zips > 2gb so we aren't worried as much about the allocations.

**Comment by ericstj** [comment]
I see, if that applies to all of these you can deprioritize.  I filed this after seeing a report for a customer on desktop who did some gymnastics to workaround these allocations.  I suppose we'd want to give desktop the native-zlib improvements rather than fix up the managed implementation?

**Comment by stephentoub** [comment]
> I suppose we'd want to give desktop the native-zlib improvements rather than fix up the managed implementation?

Yeah, there's a huge perf win to be had by switching the implementation to use zlib.

**Comment by ianhays** [comment]
> suppose we'd want to give desktop the native-zlib improvements rather than fix up the managed implementation?

That would be much better, yes. Desktop decompression is still on the old managed implementation and also lacks deflate64 support. Upgrading it to use zlib with the modified delfate64 managed available a la netcore would be substantial improvement.

**Comment by carlossanlop** [comment]
Triage:
Some entries might have already done by @stephentoub.

**Comment by stephentoub** [comment]
> Some entries might have already done

I haven't bothered with the DeflateManaged implementation because it's rarely used now (we use the zlib implementation for everything except decompressing Deflate64); I don't expect any improvements there to move the needle.

**Comment by ericstj** [comment]
Closing since this is only calling out DeflateManaged
