### ISSUE TITLE
Native build fails on CentOS 6

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#24092]
This PR https://github.com/dotnet/corefx/pull/23976 introduced a slightly different declaration for `in_pktinfo`. Unfortunately, the CentOS build is detecting the wrong configuration for `HAVE_LINUX_IN_H`, which is causing the wrong `SOCKET_INCLUDES` to be set. Instead of linux/in.h, netinet/in.h is being used. On CentOS, linux/in.h contains the definition for `in_pktinfo`. This causes us to emit the struct declaration even though it is already defined in a header.

@janvorli

**Comment by mellinoe** [comment]
The check probably needs to be something like this:

https://github.com/mellinoe/corefx/commit/9a23536615616ee0c1c27d5de2f7ceb79694e5b3

I'm sure this will break other systems, though, so I'll need some help getting the CMake config stuff right.

**Comment by janvorli** [comment]
@mellinoe don't worry about it, I'll fix it.

**Comment by mellinoe** [comment]
Much appreciated!

**Comment by mellinoe** [comment]
This was fixed by https://github.com/dotnet/corefx/pull/24100.
