### ISSUE TITLE
Change ReadOnlySpan indexer to return ref readonly

### ISSUE THREAD

**Issue by ektrah** [dotnet/corefx#24105]
```diff
 namespace System
 {
     public struct ReadOnlySpan<T>
     {
         ...
-        public T this[int index] { get; }
+        public ref readonly T this[int index] { get; }
         ...
     }
 }
```

See https://github.com/dotnet/corefx/issues/23881#issuecomment-328741859.

**Comment by KrzysztofCwalina** [comment]
@jkotas, @ahson, @jaredpar, @VSadov, thoughts?

**Comment by stephentoub** [comment]
Sounds fine to me.

**Comment by VSadov** [comment]
Good change. 
Will avoid copies in cases like.

```cs
ReadonlySpan<HugeNestedStruct> h =  ObtainSomehow();

int iOnlyNeedAnInt = h[42].Some.Deep.Nested.IntField;

```

**Comment by jkotas** [comment]
Sounds fine to me.

**Comment by KrzysztofCwalina** [comment]
Great. Thanks!

**Comment by jaredpar** [comment]
Yes def should do this

**Comment by karelz** [comment]
FYI: The API review discussion was recorded - see https://youtu.be/b96co3sNzNI?t=2423 (2 min duration)

**Comment by ahsonkhan** [comment]
Can someone please explain the distinction between `ref readonly` and `readonly ref`?

There is inconsistency in this particular issue, the title says:
> Change ReadOnlySpan indexer to **return readonly ref**

The API change proposed (which is probably correct) says:
`public ref readonly T this[int index] { get; }`

@ektrah, can you please update the title?

Returning `readonly ref` throws compiler error:
> The modifier 'readonly' is not valid for this item

The indexer should return `ref readonly T` while Span\<T\> is a `readonly ref struct`.

cc @VSadov

**Comment by ektrah** [comment]
Oops, sorry for the confusion. I've updated the title.

(It's really confusing that *read-only references* are denoted by `ref readonly`.)
