### ISSUE TITLE
Allow long path syntax for Windows

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#2411]
Enable \\\\?\ formatted paths.

**Comment by jakesays** [comment]
The BCL team did something like this a while ago: [LongPath](http://bcl.codeplex.com/wikipage?title=Long%20Path)

**Comment by JeremyKuhne** [comment]
Part of #645.

**Comment by JeremyKuhne** [comment]
We're good to go with \\\\?\\.
