### ISSUE TITLE
Documentation Error in System.Collections.Immutable.ImmutableInterlocked

### ISSUE THREAD

**Issue by koenigst** [dotnet/corefx#24112]
The summary of `TryPop` in [ImmutableInterlocked](https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableInterlocked.cs) is a copy of `Push` which is obviously wrong.

As this is a very small change and I'm new to corefx I would correct this quickly.

**Comment by danmosemsft** [comment]
That would be welcome, @koenigst !

**Comment by karelz** [comment]
FYI: The public API reference is ok: https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutableinterlocked.trypop?view=netcore-2.0

**Comment by safern** [comment]
Fixed in #24113
