### ISSUE TITLE
StreamReader.ReadLine fails to return null when end-of-stream is reached

### ISSUE THREAD

**Issue by tintoy** [dotnet/corefx#24118]
Hi.

I've run into some puzzling behaviour with `StreamReader.ReadLine` that appears to deviate that described in [the documentation](https://docs.microsoft.com/en-au/dotnet/api/system.io.streamreader.readline?view=netcore-2.0). According to these docs, `StreamReader.ReadLine` should return `null` if the end of the input stream is reached (before a line-ending sequence is encountered, I assume, although that assumption may be the source of the problem). But that's not the behaviour I'm seeing.

A simple repro:

```csharp
byte[] data = Encoding.ASCII.GetBytes("Hello world"); // No newline
using (MemoryStream dataStream = new MemoryStream(data))
using (StreamReader dataReader = new StreamReader(dataStream, Encoding.ASCII, detectEncodingFromByteOrderMarks: false, bufferSize: 5))
{
    string line = dataReader.ReadLine();
    if (line == null)
        Console.WriteLine("No line.");
    else
        Console.WriteLine($"Line: '{line}'.");
}
```

Am I reading the documentation correctly, or is the implication that `ReadLine` will return whatever it has even if it has never encountered a new-line sequence?

**Comment by danmosemsft** [comment]
@tintoy my reading of the code is that it does not require a line ending at the end of the stream. Files often don't end in a newline.

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/StreamReader.cs#L704

I believe this is intended behavior -- perhaps the docs could be clearer, perhaps you might want to open an issue against the docs repo for that ? https://github.com/dotnet/docs

**Comment by tintoy** [comment]
Yeah now that you put it that way, it does sound like that's the correct behaviour. I'll open a PR for the docs though - maybe I can save someone else from running into the same confusion.

Thanks!

**Comment by danmosemsft** [comment]
Thanks @tintoy !
