### ISSUE TITLE
[Question] What is the most efficient way to read/write `Vector<T>` from/to managed memory?

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/corefx#24124]
I'm optimizing floating-point color conversion methods for the [ImageSharp](https://github.com/SixLabors/ImageSharp) library, using the  .NET Core 1.1 runtime for my experiments.  I have to do several arithmetic operations using SIMD vectors and scatter the elements of the result vectors to different memory locations. I tried two approaches for this:
1. Read the input as `Vector<T>` -> calculate -> [copy the vectors into an another struct on the stack, and use it for further operations](https://github.com/SixLabors/ImageSharp/blob/84944e2db9b74f4b5f226de33b3c8a5787dc8dc4/src/ImageSharp/Formats/Jpeg/Common/Decoder/JpegColorConverter.FromYCbCr.cs#L117). (Note: This is an AVX2 only execution path.)
2. [Do everything with `Vector4`.](https://github.com/SixLabors/ImageSharp/blob/343a8920d806d9d92efeb45c2f43f103fadfdbd4/src/ImageSharp/Formats/Jpeg/Common/Decoder/JpegColorConverter.FromYCbCr.cs#L95)

With the first approach I was only able to reach a small (~`2x`) speedup compared to the scalar code, but the speedup was really significant with the second, `Vector4`-only solution. This is not what I expected.

Correct me if I am wrong, but I started to think that the way I read/write `Vector<T>` might prevent the JIT from generating optimized code. I ended up having the following question:

Is there any difference in the quality of the generated machine code for this:

```C#
ref FooStruct fooRef = ref GetFooRef(); // can be heap or stack reference
Vector<float> v = Unsafe.As<FooStruct, Vector<float>>(ref fooRef);
v+= new Vector<float>(42);
Unsafe.As<FooStruct, Vector<float>>(ref fooRef) = v;
```

VS this:

```C#
ref FooStruct fooRef = ref GetFooRef(); // can be heap or stack reference
ref Vector<float> vRef = Unsafe.As<FooStruct, Vector<float>>(ref fooRef);
vRef+= new Vector<float>(42);
```

VS this:

```C#
FooStruct* fooPtr = GetFooPtr(); // can be heap or stack pointer
Vector<float> v = Unsafe.Read<Vector<float>>(fooPtr);
v+= new Vector<float>(42);
Unsafe.Write<Vector<float>>(fooPtr, v);
```
VS this?

```C#
FooStruct* fooPtr = GetFooPtr(); // can be heap or stack pointer
Vector<float> v = Unsafe.ReadUnaligned<Vector<float>>(fooPtr);
v+= new Vector<float>(42);
Unsafe.WriteUnaligned<Vector<float>>(fooPtr, v);
```

I'm interested in both:
- Reading/writing `Vector<float>` from/to unalinged managed heap locations
- Reading/writing to a `struct` located on the stack

Any hints? Is there something wrong with my approach? Should I ask this on `coreclr` instead?

Thanks!

**Comment by mellinoe** [comment]
This line from the first example:

`Vector<float> v = ref Unsafe.As<FooStruct, Vector<float>>(ref fooRef);`

should probably be

`Vector<float> v = Unsafe.As<FooStruct, Vector<float>>(ref fooRef);`

**Comment by mellinoe** [comment]
@CarolEidt Do you know how differently the JIT will optimize these patterns? The main pivots seem to be:

* Operating directly on a `ref Vector<T>`  vs. pulling a value into a local and then storing it back out (through a `ref struct`)
* Operating on pointers vs. `ref`s
* `Unsafe.Read/Write` vs. `Unsafe.Read/WriteUnaligned`. I think we always do unaligned reads/writes in our codegen, so this is probably a wash?

**Comment by antonfirsov** [comment]
Fixed my first example, thanks!

**Comment by CarolEidt** [comment]
- Ideally, pulling a value into a local and then storing it back out should not pessimize code generation. 
  - However, it is still the case that the JIT may introduce extraneous copies in some cases. 
  - That said, if you are going to use the vector multiple times, and you have other writes to non-stack memory in-between uses, you are better off putting it in a local so that the JIT doesn't think it has to redo the load (it is rather conservative when it encounters stores to heap memory).
- There should be no difference in the handling of pointers vs. refs.
- We always do unaligned reads/writes of anything that is not on the stack.

**Comment by antonfirsov** [comment]
I managed to turn my some of my cases [into microbenchmarks](https://github.com/antonfirsov/BenchmarkingExperiments/blob/master/BenchmarkRunner/FetchVectors.cs), and by running them it looks like there is no real difference.

There must be some other weakness in my original color conversion code. Will come back, and leave my notes here, as soon as I manage to figure it out.

**Comment by safern** [comment]
@antonfirsov do we still need this issue? It is being a long time already. Please feel free to re-open or open a new one with your further questions if you have any :)
