### ISSUE TITLE
Sql Connection Pooling

### ISSUE THREAD

**Issue by avireddy02** [dotnet/corefx#24120]
We are having issues when connecting from .net core application to sql server. The connections opened by application was not closed/ connection pooling was not happening as expected. Below is the sample code used to open a sql connection.
```
using (var conn = new SqlConnection(_connStr))
            {
                var query = @"INSERT INTO dbo.user
                              ([uid],[email_address],[create_datetime],[created_by],[last_update_datetime],[last_updated_by])
                              VALUES(@Userid,@EmailAddress,SYSUTCDATETIME(),@UserId,SYSUTCDATETIME(),@UserId);";

                await conn.ExecuteAsync(query, new
                {
                    UserId = request.UserId, 
                    EmailAddress = request.EmailAddress
                });
            }
```

On an average 200-400 inactive connections are opened in a day. In couple of weeks, inactive connections count reaching SQL max connection limits. Which brings the application down.

Current work Around: Restart application service to close all inactive connections.

Current System Specs:

Application Server :
OS: Ubuntu 16.0.4 LTS
App : Asp.Net Core 1.1
ORM: Dapper 

Sql Server:
Version : SQL server Enterprise 2012
OS: Windows 2012 Ent.,

**Comment by corivera** [comment]
@geleems  Could this be related to the connection pool fragmentation issue you fixed a while back? https://github.com/dotnet/corefx/commit/4839aaf6dbbf2d453b9c27283325e0df90db5f5d

**Comment by corivera** [comment]
Unlikely this is caused by the connection pool fragmentation bug, since that one would just make empty pools. 

@avireddy02 We had a connection leak bug that was fixed in System.Data.SqlClient 4.3.1. Does targeting that version resolve this issue?

**Comment by avireddy02** [comment]
@corivera After updating to .Net Core 2.0 which point to latest System.Data.SqlClient the issue is resolved. Thanks a lot!!
