### ISSUE TITLE
Please introduce a default blank templates for posting issues

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/corefx#24126]
In the [API Review Process / Steps](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md#steps) section, there is a link to a good API proposal example.

It could be a lot easier and more productive to make a default template so that when users create an issue they can choose to fill in the questions or just <kbd>Ctrl</kbd>+<kbd>A</kbd> and start typing to make one of their own.

See also:
- [Issue and PR templates](https://github.com/blog/2111-issue-and-pull-request-templates)
- [Creating an issue template for your repository](https://help.github.com/articles/creating-an-issue-template-for-your-repository)

**Comment by danmosemsft** [comment]
Interesting idea. It would be helpful to have a template for API proposals, but it would show up when opening any issue. And I think we are doing OK without having a template for regular issues -- we usually don't need information like product version, and many issues don't need repro steps.
@karelz  ?

**Comment by stephentoub** [comment]
We had both PR and issue templates.  We removed them: https://github.com/dotnet/corefx/pull/6474.

**Comment by weitzhandler** [comment]
I'm closing this issue then.
Sorry I missed that PR, and thank ya'll.

**Comment by karelz** [comment]
We should not hijack old existing issues for discussion. If you need a discussion, we should have it here (feel free to reopen).

In ideal world, we would have templates. I would create them once we have proper clear guidance on contributions (it is still under construction in wiki), esp. issue types, etc. We can then put there links to the docs.
As @danmosemsft suggested we are mostly fine now, so adding a few links to API proposal is not a big deal IMO. It also allows area owners to pre-screen the ideas early and potentially avoids wasting time on reporter's side for API ideas which would be rejected.

**Comment by weitzhandler** [comment]
Thanks for your response.
Anyway looks like the subject has its conclusions, so I'm keeping this issue closed.
Any member can open it if or when there is a demand.
