### ISSUE TITLE
Needs to check corefx-utcs consider some situations when they are native images made by using crossgen

### ISSUE THREAD

**Issue by YongseopKim** [dotnet/corefx#24138]
I've recently tested coreclr/corefx utcs which are native images made by using crossgen `FNV` or `R2R`. I found some problems. I need to get feedback from you by sharing this.

One of them is `System.Reflection.Tests.ModuleTests.Name`.
```
   System.Reflection.Tests.ModuleTests.Name [FAIL]
      Assert.Equal() Failure
                                       ↓ (pos 21)
      Expected: ···ystem.runtime.tests.dll
      Actual:   ···ystem.Runtime.Tests.ni.dll
                                       ↑ (pos 21)
      Stack Trace:
            at System.Reflection.Tests.ModuleTests.Name()
```

Code of `System.Reflection.Tests.ModuleTests.Name`.
```cs
        [Fact]
        [SkipOnTargetFramework(TargetFrameworkMonikers.UapAot, "Module.Name does not indicate file location on UwpAot")]
        public void Name()
        {
            Assert.Equal("system.runtime.tests.dll", Module.Name, ignoreCase: true);
        }
```

When the tc is a native image, the `Module.Name` is `System.Runtime.Tests.ni.dll` while the expeced `Module.Name` is `System.Runtime.Tests.dll`. This causes because some tcs assume that the loaded assembly is only `.dll` file although it can be a native image such as `.ni.dll`.

We can think corefx-utc doesn't need to be native image itself. However an application could be native image. In my opinion, some tcs need to be fixed to consider this situation.

@dotnet/arm32-contrib

**Comment by YongseopKim** [comment]
Failed TCs when they are native images and trying loading themselves. (Some of them can be passed if they are native image made by crossgin with `R2R`. I don't know exactly, `FNV(FragileNonVersionable)` NI File cannot be loaded directly. It causes `System.BadImageFormatException : Bad IL format`. Anyway, it doesn't matter that it is `FNV` or `R2R`. The important thing is that tcs don't consider ni files.)

```
System.Runtime.Loader.Tests.DefaultLoadContextTests.LoadInDefaultContext
System.Runtime.Loader.Tests.RefEmitLoadContextTests.LoadRefEmitAssembly
System.Reflection.Tests.ModuleTests.FullyQualifiedName
System.Reflection.Tests.AssemblyTests.AssemblyLoadFromBytes
System.Reflection.Tests.AssemblyTests.AssemblyLoadFromBytesWithSymbols
System.Reflection.Tests.AssemblyTests.GetFiles
System.Reflection.Tests.AssemblyTests.GetFile
System.Reflection.Tests.AssemblyTests.LoadFrom_SameIdentityAsAssemblyWithDifferentPath_ReturnsEqualAssemblies
```

**Comment by weshaggard** [comment]
@YongseopKim I'm not sure we ever need to run our tests in the context where the assemblies are ".ni.dll", While it might be interesting to have some specific tests that validate ".ni.dll"'s I'm not sure it is worth the complication in the test infra to get this little bit extra test coverage. Those type of tests would more naturally be part of the coreclr test bed which validates the ni images.
