### ISSUE TITLE
BadImageFormatException with Span<T> with xUnit.net

### ISSUE THREAD

**Issue by lextm** [dotnet/corefx#24135]
`Span<T>` has been so special, that a strange runtime exception can occur. Reported to xUnit.net already, https://github.com/xunit/xunit/issues/1457 but not sure if the issue is merely caused by xUnit.net. I hope a better exception as well as more meaningful call stack can be thrown if possible.

**Comment by stephentoub** [comment]
https://github.com/xunit/xunit/issues/1457#issuecomment-330546584

**Comment by karelz** [comment]
We can use this issue to track better exception at runtime when it happens - see https://github.com/xunit/xunit/issues/1457#issuecomment-330795410

**Comment by joshfree** [comment]
@VSadov can you point folks to the pre-release compiler package with the compile-time checks that would prevent this?

**Comment by karelz** [comment]
@joshfree do you want to reuse this issue to track better Runtime exception info as I suggested above or another one?

**Comment by joshfree** [comment]
@karelz a coreclr repo issue would be fine to track a better runtime exception

**Comment by karelz** [comment]
@joshfree ok, can you (or someone on your team) please create one and link it from xunit?
Do we still need this one?

**Comment by joshfree** [comment]
Sure.

Moved issue to coreclr repo  https://github.com/dotnet/coreclr/issues/14097
