### ISSUE TITLE
WinHttpException: Not enough storage is available to process this command

### ISSUE THREAD

**Issue by davidkaya** [dotnet/corefx#24139]
Hello,

I have an ASP.Net Core 2.0 server (Kestrel) on Windows Server 2016 [Standard D2s v3 (2 vcpus, 8 GB memory)] in Azure. I am trying to load test an endpoint which just sends 2 "get" and 2 "post" http requests to NoSQL database. 

For load testing I use https://github.com/tsenart/vegeta from 3 computers. Throughput was approximately 15.000 rpm.

Approximately every minute it throws a lot of these exceptions and then it works correctly for a while and after some time again throws exceptions:

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HL7UO2PLN0UI", Request id "0HL7UO2PLN0UI:00000001": An unhandled exception was thrown by the appl
cation.
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpExceptio
: Not enough storage is available to process this command
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
```

here are screenshots of graphs:

![screen shot 2017-09-19 at 08 34 30](https://user-images.githubusercontent.com/3832960/30578809-1213639e-9d16-11e7-9d99-26fbe6285152.png)
![screen shot 2017-09-19 at 08 34 42](https://user-images.githubusercontent.com/3832960/30578815-1abb1082-9d16-11e7-9383-f7698e5c3e15.png)

Is this just some mistake in configuration or is the problem somewhere else?

**Comment by davidkaya** [comment]
And this is the same application on Ubuntu 16.04LTS
![screen shot 2017-09-19 at 10 51 32](https://user-images.githubusercontent.com/3832960/30583922-8cddd9c6-9d28-11e7-855a-7ddf6d8ea550.png)

**Comment by davidsh** [comment]
In order to diagnose this, we need a way to repro this.  It sounds like HttpClient is being called from your Kestrel server in reaction to clients accessing Kestrel?  Please post the full Visual Studio solution to the Kestrel server and a way for us to repro this.

**Comment by davidsh** [comment]
Closing for lack of info to diagnose problem.
