### ISSUE TITLE
UWP F5 Tests (Master): All work items have fireball issue

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#24136]
UWP F5 Tests (Master): All work items have fireball issue

Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20170918.03

Almost failed on **Windows.10.Amd64.ClientRS3-x64**

**Comment by danmosemsft** [comment]
@safern

**Comment by safern** [comment]
My initial thought about this is that when restoring the nuget package it took the latest published package rather than the specified in the dependencies proj. Will have to investigate further. Because I haven't merged any change to consume the latest package yet.

**Comment by safern** [comment]
fixed by my buildtools rollback. I can see it in the current build that is now running.
