### ISSUE TITLE
can't find a coreclr equivalent of System.Environment.GetCommandLineArguments()

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/corefx#2413]
Many of the F# test scripts call this API to get the command line arguments to the script.  The script can be called from our Repl or compiled into a .exe.

Again the scripts don't typically have main specified and so there is nowhere for us to introduce the command line Arguments, each script will need to be modified with a Main, when command line.

It would certainly be nicer if we could use the API System.Environment.GetCommandLineArguments() which has been part of the framework for years.

**Comment by stephentoub** [comment]
cc: @weshaggard, @terrajobst

**Comment by weshaggard** [comment]
Thanks for reporting the issue @KevinRansom I think this is similar to issue https://github.com/dotnet/corefx/issues/2353 in that we should figure out a way to expose the functionality but I'm not sure it should be directly on Environment given that it is more app-model specific. As we start to bring up more first class support for Console applications we will see about exposing something like this. I have similar reservations about this API when CoreCLR is being hosted, I'm not entirely sure what we should expect the command line arguments to be in that case, particular arg[0].

**Comment by mellinoe** [comment]
I think this could be useful, at least in some form. Most of the console tools that we are using have a dependency on this, because the command-line parsing helper we use calls it. This is mostly just out of convenience, we can work around it since it isn't available right now. For other use cases it might be much more tedious to work around.

Few questions:
* What does Mono return for this API? Does it include "mono" as arg[0]?
* What's the underlying OS call used on other platforms? Does it behave similarly to the Win32 call we use on the .NET Framework?
* Maybe we should expose something on Process? From what I understand this is what the info is tied to on Windows. It may be different on other platforms.

**Comment by pallavit** [comment]
> Maybe we should expose something on Process? From what I understand this is what the info is tied to on Windows. It may be different on other platforms.

I think this scenario makes more sense for the Console applications than UI applications and so I am not certain process is the right place for this.
Also, for a hosted app I would think we should have a default behavior and a mechanism for the host (at the start-up time) to override the behavior in case it choses to do so.

**Comment by pallavit** [comment]
@stephentoub Do you know if this can be supported cross-plat?

**Comment by stephentoub** [comment]
> Do you know if this can be supported cross-plat?

To my knowledge there aren't any general unix APis for this.  On Linux it can be read out of procfs, from the file at /proc/PID/cmdline.  Not sure about APIs for this on OS X.

But there's also the option of just having CoreCLR store the command-line arguments it's given when the runtime PAL is initialized, and surface those from GetCommandLineArguments... which appears to already be implemented:
https://github.com/dotnet/coreclr/blob/575e0d05b748e4e11ff75d66fa085e8d976f2083/src/pal/src/thread/process.cpp#L2224

**Comment by KevinRansom** [comment]
Is there any progress on to report on this?

**Comment by davidfowl** [comment]
+1

**Comment by stephentoub** [comment]
https://github.com/dotnet/apireviews/pull/19

**Comment by pallavit** [comment]
This is now implemented.

**Comment by davidfowl** [comment]
nice!
