### ISSUE TITLE
Allow receiving a Socket from a file handle

### ISSUE THREAD

**Issue by logankp** [dotnet/corefx#24143]
It would be nice to have the ability to receive a socket from a file handle and be able to call Accept() on it. This is useful to enable functionality like [systemd socket activation](http://0pointer.de/blog/projects/socket-activation.html).

Ex.
```cs
var listeningSocket = Socket.FromFileHandle(handle); //socket is already bound by the service manager
var connectionScoket = listeningSocket.Accept();
//Send data through connectionSocket
```

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/14041?

**Comment by karelz** [comment]
Duplicate of #14041
