### ISSUE TITLE
Clean up Begin/End usage in System.IO.Pipes

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#2414]
The System.IO.Pipes implementation still has a bunch of APM legacy floating around in its implementation, making it both more expensive and more complicated than if it just used Tasks directly.  This should be cleaned up, as was done for System.IO.FileSystem in #972.

**Comment by Maxwe11** [comment]
Are you expecting PRs from community? :smile:

**Comment by stephentoub** [comment]
If you're interested, you're welcome to it! :smile:

**Comment by stephentoub** [comment]
@Maxwe11, do you want me to mark this as assigned to you?

**Comment by Maxwe11** [comment]
@stephentoub I think this issue should be resolved in a couple independent PRs
- [ ] clean up BeginWaitForConnection/EndWaitForConnection
- [ ] clean up BeginRead/BeginWrite/etc.

I already have some work in private branch against first point (BeginWaitForConnection/EndWaitForConnection) so grabbing it now.

**Comment by Maxwe11** [comment]
In the meantime someone else could grab the second point so leave issue as `up-for-grabs` or split it.

**Comment by stephentoub** [comment]
Sounds good.  Thanks.

**Comment by Maxwe11** [comment]
grabbing the rest :smile:
