### ISSUE TITLE
Problem on `string.Split`

### ISSUE THREAD

**Issue by Cologler** [dotnet/corefx#24162]
I doubt that this is not the expected behavior:

``` cs
> "455".Split(new [] { "455" }, 2, StringSplitOptions.RemoveEmptyEntries)
string[0] { }
> "455".Split(new [] { "455" }, 1, StringSplitOptions.RemoveEmptyEntries)
string[1] { "455" }
```

**Comment by jnm2** [comment]
You doubt that is *is* the expected behavior, or that it's *not* the expected behavior?

https://docs.microsoft.com/en-us/dotnet/api/system.string.split?view=netcore-2.0#return-value-details:

> If this instance does not contain any of the strings in `separator`, or the `count` parameter is 1, the returned array consists of a single element that contains this instance.
