### ISSUE TITLE
Support folder names ending with a period?

### ISSUE THREAD

**Issue by mguinness** [dotnet/corefx#24160]
I have an issue related to Windows folder names that end with a period.  In my case this was caused by a cloud storage desktop sync application where creating folders in the cloud like "Some Corp Ltd." is possible.

Since there was already work done to support long filenames in .NET Core (see https://github.com/dotnet/corefx/issues/645) I thought it might be feasible that this issue might be addressed as well.

I'm aware of libraries like [AlphaFS](http://alphafs.alphaleonis.com/) (using [LongFullPath](http://alphafs.alphaleonis.com/doc/2.1/api/html/5E9EE47E.htm)) that work with the full framework, but I wondering if anything is planned for .NET Core (I'm assuming this isn't an issue for Linux).

I understand that it's an edge case, but currently using Directory.Exists in this situation returns false which is a misleading IMHO.

@JeremyKuhne is it possible to support folders with names ending with a period in System.IO.FileSystem?

**Comment by JeremyKuhne** [comment]
It is the nature of Win32 path normalization that trailing periods on a path get eaten (as do spaces). The extended device syntax `\\?\` allows you to get around this, and both Core and Desktop (NetFX) support this. The other option is to stick a trailing separator on the path. Anything before the final `\` isn't at the end of the string and won't be eaten by Win32 path normalization.

Using device syntax is a little tricky as `\\?\` requires that the path be fully normalized. Relative paths and alternate directory separators don't work. The usual pattern for using `\\?\` is to call Path.GetFullPath() to normalize, then prepend with `\\?\`. As already stated, however, you would need a trailing separator to keep Win32 from eating the spaces & periods in the normalization call.

**Comment by mguinness** [comment]
Thanks for the help.  I wasn't able to get the trailing separator working, but the extended device syntax worked.

However, there is another issue which is a little tricky.  Given that "Some Corp Ltd." is under C:\Firms, running the following:

`var dirs = new DirectoryInfo(@"C:\Firms").EnumerateDirectories();`

Generates exception "Could not find a part of the path 'C:\Firms\Some Corp Ltd'", but will work if using:

`var dirs = new DirectoryInfo(@"\\?\C:\Firms").EnumerateDirectories();`

That is understandable based upon your description.  I guess my take is would it be possible for the internals in System.IO.FileSystem to detect if a path parameter ends with a period and automatically prepend \\?\ for Win32?

**Comment by JeremyKuhne** [comment]
> would it be possible for the internals in System.IO.FileSystem to detect if a path parameter ends with a period and automatically prepend \\?\ for Win32?

It seems reasonable to me to do this for enumeration as the paths aren't accessible without it and we _know_ the actual, existing path that was just reported from Windows. The `\\?\` could throw off some client code, but is much more likely to be accidentally successful than "phantom" truncated paths.

Path strings being passed _into_ System.IO APIs I'm not keen on automatically doing this for a few reasons:

1. It doesn't match Win32 API / CMD behavior.
2. `"Foo."` and `"Foo"` can both exist (as can `"Foo "`)- we can't be positive of intent, particularly given the above.
3. I want to discourage people from accidentally creating files with trailing periods/spaces as _most_ code can't handle it.

**Comment by mguinness** [comment]
A suggestion for System.IO APIs is that when paths with trailing spaces or periods are passed without the extended device syntax, a logging warning is generated notifying that Win32 path normalization will occur.

**Comment by JeremyKuhne** [comment]
> A suggestion for System.IO APIs is that when paths with trailing spaces or periods are passed without the extended device syntax, a logging warning is generated notifying that Win32 path normalization will occur.

We don't really have a way to do this. We could try and improve the detail in the docs, and/or have them link to my blog posts on the details of path normalization. (These posts start [here](https://blogs.msdn.microsoft.com/jeremykuhne/2016/04/21/path-format-overview/)).

**Comment by JeremyKuhne** [comment]
In theory, enumeration should work for these sort of paths with my 2.1 changes #25873. I'll write some tests to validate that we get the right results for file/directories with trailing space or period characters.

**Comment by JeremyKuhne** [comment]
I've validated this now works, written tests, and made additional fixes. You can now use DirectoryInfo and FileInfo classes successfully with paths that end in periods or spaces. Creating such paths still requires `\\?\`, which I detail the reasoning for above.

**Comment by mguinness** [comment]
@JeremyKuhne Thanks, I look forward to 2.1 release.

**Comment by ptr727** [comment]
I just ran into this problem with dotnet core 3 preview 4.
I have to iterate through files and folders, and I encountered file not found exceptions.
Directory iteration correctly identifies folder ending in a dot, enumerating files in that folder fails with file not found exception.

@JeremyKuhne I am not sure if this is now expected to work without me needing to know about the actual paths based on the comment above?

```
int main()
{
	CreateDirectoryW(L"\\\\?\\C:\\Temp\\Test", NULL);
	CreateDirectoryW(L"\\\\?\\C:\\Temp\\TestDot.", NULL);
	CreateDirectoryW(L"\\\\?\\C:\\Temp\\TestDotDot..", NULL);

	CAtlFile testFile;
	testFile.Create(L"\\\\?\\C:\\Temp\\Test\\Test.txt", GENERIC_READ | GENERIC_WRITE, FILE_SHARE_READ, OPEN_ALWAYS);
	testFile.Close();
	testFile.Create(L"\\\\?\\C:\\Temp\\TestDot.\\TestDot.txt", GENERIC_READ | GENERIC_WRITE, FILE_SHARE_READ, OPEN_ALWAYS);
	testFile.Close();
	testFile.Create(L"\\\\?\\C:\\Temp\\TestDotDot..\\TestDotDot.txt", GENERIC_READ | GENERIC_WRITE, FILE_SHARE_READ, OPEN_ALWAYS);

	return 0;
}
```

```
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                DirectoryInfo sourceInfo = new DirectoryInfo(@"C:\Temp");
                foreach (DirectoryInfo dirInfo in sourceInfo.EnumerateDirectories("*", SearchOption.AllDirectories))
                {
                    foreach (FileInfo fileInfo in dirInfo.EnumerateFiles("*.*", SearchOption.TopDirectoryOnly))
                    {
                    }
                }
            }
            catch (Exception e)
            {
                // Exception thrown: 'System.IO.DirectoryNotFoundException' in System.IO.FileSystem.dll
                Console.WriteLine(e);
            }
        }
    }
```
