### ISSUE TITLE
Please implement SymmetricExceptWith in LINQ

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/corefx#24161]
## Motive

`HashSet<T>` provides a wonderful method that allows getting the [symmetric difference](https://en.wikipedia.org/wiki/Symmetric_difference) of two collections, that is, only the values that exists in either one of the collections, but not in both.

## Use case
Imagine you have an existing store entity and a client entity that just came in to be saved.
The entity has a collection of related entities (1 to M).

You want to mess with those related entities that were either added or removed, but not the others.

## Implementation

Add the following methods to the `Enumerable` class:

```c#
    public static SymmetricExceptWith<T>(this IEnumerable<T> collection, IEnumerable<T> other);

    public static SymmetricExceptWith<T>(this IEnumerable<T> collection, IEnumerable<T> other, 
      IEqualityComparer<TSource> comparer);
```

If this is approved, I'm willing to implement this.

Area: System.Linq

[EDIT] Add C# syntax highlight by @karelz

**Comment by jnm2** [comment]
> Use case: You want to mess with those related entities that were either added or removed, but not the others.

Wouldn't you rather have the added items and removed items returned separately? I feel like you haven't gained anything if you're lumping them back together.

It looks like you're addressing a many-to-many scenario here where the collections are only IDs, not a one-to-many scenario entity objects which have IDs and may represent updates as well as inserts and deletes. Most of the time I actually need to separate into three groups: added, removed, and possibly-modified, and I'm mapping based on child entity ID. This can be done in a single pass with a dictionary.

**Comment by stephentoub** [comment]
There hasn't been a lot of expressed interest in this for several years, and such an extension method could easily be implemented in another library, so I'm going to close this.  Regardless, thank you for the suggestion.
