### ISSUE TITLE
.NET Core Version of System.Web.UI.HtmlTextWriter

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/corefx#24169]
Does such a thing exist? What is the alternative? I'm using this type to do XSL transforms like so:

```c#
private static Stream XslTransform(XDocument document, XmlReader xslReader)
{
    var xslTransform = new XslCompiledTransform();
    var stringBuilder = new StringBuilder();

    using (var stringWriter = new StringWriter(stringBuilder))
    {
        using (var htmlWriter = new HtmlTextWriter(stringWriter))
        {
            xslTransform.Load(xslReader);
            xslTransform.Transform(document.CreateReader(), new XsltArgumentList(), htmlWriter);
            htmlWriter.Flush();
        }
    }

    return new MemoryStream(Encoding.UTF8.GetBytes(stringBuilder.ToString()));
}
```

[EDIT] Add C# syntax highlighting by @karelz

**Comment by danmosemsft** [comment]
@Eilon is there an equivalent? 

I wonder if it could be ported. It does not seem to depend significantly on other types in System.Web, except its friends like CSSTextWriter.

**Comment by RehanSaeed** [comment]
After reading your comment, I tried copying across the `HtmlTextWriter` class and some of it's dependencies but quickly found that it uses a lot of types in that themselves had dependencies on types in`System.Web`.

I may be misunderstanding what is possible but could I not move my XslTransform method into a .NET 4.6.1 class library and call that from my netcoreapp2.0 application? Would that work with and without the .NET Framework being installed on the machine?

**Comment by Eilon** [comment]
No equivalent in ASP.NET Core - the rendering model for HTML is completely different and based on the Razor (CSHTML) syntax.

**Comment by karelz** [comment]
> I may be misunderstanding what is possible but could I not move my XslTransform method into a .NET 4.6.1 NuGet package and call that from my netcoreapp2.0 application? Would that work with and without the .NET Framework being installed on the machine?

No it would not work. netcoreapp2.0 runs on .NET Core 2.0 and some of your dependencies are just missing there.

Per @Eilon's reply, I think we can close this one. If you think Razor syntax is not sufficient, I would suggest to open a discussion on ASP.NET repos (https://github.com/aspnet)
