### ISSUE TITLE
SFTP connection throws 'Device not Configured' Error

### ISSUE THREAD

**Issue by rich-ware** [dotnet/corefx#24182]
Hi, I am trying to connect to an SFTP server and I receive the following error: 

nerException [Exception]:{System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x00000005): Device not configured\n   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)\n   at System.Net.Dns.ResolveCallback(Object context)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)\n   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)\n   at System.Net.Sockets.Socket.DoDnsCallback(IAsyncResult result, MultipleAddressConnectAsyncResult context)\n   at System.Net.Sockets.Socket.DnsCallback(IAsyncResult result)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\n   at System.Net.Sockets.TcpClient.<>c....
InnerExceptions [ReadOnlyCollection]:Count = 1
Message [string]:"One or more errors occurred. (Device not configured)"
Source [string]:"System.Private.CoreLib"
StackTrace [string]:"   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\n   at System.Threading.Tasks.Task.Wait()\n   at DayForceImportValidator.FileOperations.SFTP.<ConnectToSftpServer>d__1.MoveNext() in /Users/richblumer/Projects/DayForceImport/DayForceImportValidator/FileOperations/SFTP.cs:line 24"

I have also tried to connect to the Test SFTP provided here, [http://www.sftp.net/public-online-sftp-servers] . 

That was also unsuccessful.

I get a similar error on Windows 10. The error message is **Host is Unknown**.

Here is my local environment info:

.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

Thanks in advance!

**Comment by davidsh** [comment]
cc: @Priya91 
TcpClient on Linux

**Comment by Priya91** [comment]
@rich-ware This seems more of a machine configuration issue, from the callstack it looks like dns lookup failed. Are you able to access the servers from your machine outside of .NET? try 

```
host <servername>
```

**Comment by davidsh** [comment]
Closing this issue for now due to lack of repro information.
