### ISSUE TITLE
Codeformatter Tool

### ISSUE THREAD

**Issue by schweinsbauch** [dotnet/corefx#24185]
"We also use the .NET Codeformatter Tool to ensure the code base maintains a consistent style over time, the tool automatically fixes the code base to conform to the guidelines outlined above."

Can this be true if the codeformatter tool had it's last commit on Nov 11, 2016? (Some Issues over there are preventing the use of this tool, just check the issues there.)

**Comment by danmosemsft** [comment]
@jaredpar who is the owner of this (who reviews PR's)?

**Comment by karelz** [comment]
We use the tool ad-hoc. It was mostly used during porting time and it served its purpose.
I think we should move the discussion about future of that tool to its repo. Here's some general discussion: https://github.com/dotnet/codeformatter/issues/267#issuecomment-331320957
