### ISSUE TITLE
calls to sql server query from EfCore / Ado.net  timesout in 100seconds

### ISSUE THREAD

**Issue by kishoretvk** [dotnet/corefx#24206]
HI, 
when we run queries from Efcore, with underlying ado.net for sql server ! queries take more than 100seconds, are retried after 100 seconds untill command timeout ot connection timeout. but they do not wiat untill the query executes. 

i've a sp which runs more than 2 minutes, and they sp is executed several times , before timeout happens 
i  configured command timeout as 600, it gets retried for 6 times. but not waiting until it gets ececuted. 

finally error is trows i migrated to Efcocre 2.0 if this could be resolved but it does not happen. in Efcore 2.0 the timeout is 100 

can some  one help me  with this ?

i have a data load of more than a billion  records on wich i operate.

**Comment by elsyms** [comment]
Could you share some code that you're experiencing the issue with?

**Comment by saurabh500** [comment]
What's your server client topology? And also what operating systems are you using?

**Comment by saurabh500** [comment]
Ping @kishoretvk Are you using Linux ?

**Comment by saurabh500** [comment]
Closing due to no response
