### ISSUE TITLE
UWP - System.IO.File Tests failing on outerloop

### ISSUE THREAD

**Issue by Drawaes** [dotnet/corefx#24217]
The test is just hanging on two unrelated PR's

https://mc.dot.net/#/user/Drawaes/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/46a30dd69c4652f1c4b4a09f645ed893136b5b9f/workItem/System.IO.FileSystem.Tests/wilogs

#23715
#24116

**Comment by danmosemsft** [comment]
@jeremykuhne

**Comment by JeremyKuhne** [comment]
Please reactivate if this occurs again.
