### ISSUE TITLE
AnonymousPipeClientStream.ReadAsync does not seem to support cancellation

### ISSUE THREAD

**Issue by tintoy** [dotnet/corefx#24228]
Hi.

After some experimentation, it seems to me that unlike `NamedPipeClientStream`, `AnonymousPipeClientStream` (or `AnonymousPipeServerStream` for that matter) does not support cancellation (because there's no way to open the pipe in async mode and so `Stream.ReadAsync` is used instead of `PipeStream.ReadAsyncCore`). This is a little painful because it means there's no way to "unblock"  a pending read or write on that stream when the stream contains no data.

Here's a simple repro that shows what I'm trying to do. It works for named pipes, but not for anonymous ones:

```csharp
NamedPipeServerStream source = new NamedPipeServerStream("pipe-test", PipeDirection.Out, 1, PipeTransmissionMode.Byte, PipeOptions.Asynchronous);
NamedPipeClientStream destination = new NamedPipeClientStream(".", "pipe-test", PipeDirection.In, PipeOptions.Asynchronous);
await destination.ConnectAsync();

CancellationTokenSource cancellationSource = new CancellationTokenSource();

byte[] buffer = new byte[10];
Task<int> readTask = destination.ReadAsync(buffer, 0, buffer.Length, cancellationSource.Token);

// Right now, readTask is blocked waiting for data.
Task timeout = Task.Delay(TimeSpan.FromSeconds(1));
Task winner = await Task.WhenAny(readTask, timeout);
Assert.Equal(timeout, winner);

cancellationSource.Cancel();

// readTask will now fault with TaskCanceledException
timeout = Task.Delay(TimeSpan.FromSeconds(5));
winner = await Task.WhenAny(readTask, timeout);
Assert.Equal(readTask, winner);

// Prove that it was canceled via the correct CancellationToken
TaskCanceledException cancelled = await Assert.ThrowsAsync<TaskCanceledException>(() => readTask);
Assert.Equal(cancellationSource.Token, cancelled.CancellationToken);
```

Is this by design, or simply something nobody has gotten around to, yet? Because it looks like it should be possible to implement by constructing the base `PipeStream` with `isAsync: true` to use the [correct code-path](https://github.com/dotnet/corefx/blob/1f434a9665d666542497250a0b4e211ce20b40df/src/System.IO.Pipes/src/System/IO/Pipes/PipeStream.cs#L164-L175).

**Comment by pjanotti** [comment]
@tintoy this is a limitation of anonymous pipes in Windows: 

> Asynchronous (overlapped) read and write operations are not supported by anonymous pipes. This means that you cannot use the ReadFileEx and WriteFileEx functions with anonymous pipes. In addition, the lpOverlapped parameter of ReadFile and WriteFile is ignored when these functions are used with anonymous pipes.

source: https://msdn.microsoft.com/en-us/library/aa365141(VS.85).aspx

**Comment by tintoy** [comment]
Ah, ok thanks - that's the missing piece of the puzzle; I'll stick to named pipes for now then :)
