### ISSUE TITLE
System.Management.Automation support on .NET Core

### ISSUE THREAD

**Issue by j3vans** [dotnet/corefx#24227]
Are there any plans to support running PowerShell runspaces/commands from within a .NET Core, this is the last thing preventing us from moving all our project to .NET Core.

Thanks!

@terrajobst

**Comment by j3vans** [comment]
Looks like this is possible:

https://github.com/PowerShell/PowerShell/tree/master/docs/host-powershell

**Comment by danmosemsft** [comment]
@j3vans is there an issue tracking this in the powershell repo? It would be that repo who would do the work. Of course if we have some blocking issue we would like to hear about it so we can help.

**Comment by karelz** [comment]
It does not seem to be related to .NET Core itself - please raise it as a question on PowerShell repos. Thanks!
