### ISSUE TITLE
HttpClient with Certificates not supported

### ISSUE THREAD

**Issue by EssenRoc** [dotnet/corefx#24232]
**system: centos 7.3
runtime: dotnet core 2.0.0**

Code:
```
var x509Certificate2 = new X509Certificate2();  // Replace this class instantation with actual X509Certificate2 data
var httpClientHandler = new HttpClientHandler();
httpClientHandler.ClientCertificates.Add(x509Certificate2);
using (var httpClient = new HttpClient(httpClientHandler))
{
    // Post
}
```

Error:
```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: The handler does not support client authentication certificates with this combination of libcurl (7.29.0) and its SSL backend ("NSS/3.28.4").
System.PlatformNotSupportedException: The handler does not support client authentication certificates with this combination of libcurl (7.29.0) and its SSL backend ("NSS/3.28.4").
   at System.Net.Http.CurlHandler.SslProvider.SetSslOptionsForUnsupportedBackend(EasyRequest easy, ClientCertificateProvider certProvider)
   at System.Net.Http.CurlHandler.SslProvider.SetSslOptions(EasyRequest easy, ClientCertificateOption clientCertOption)
   at System.Net.Http.CurlHandler.EasyRequest.InitializeCurl()
   at System.Net.Http.CurlHandler.MultiAgent.ActivateNewRequest(EasyRequest easy)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by elsyms** [comment]
Have you tried updating libcurl? You're nearly 20 minor versions behind the latest stable release.

**Comment by EssenRoc** [comment]
@elsyms  Thank you [https://github.com/dotnet/corefx/issues/9728#issuecomment-286251370](url)

**Comment by EssenRoc** [comment]
```
sudo yum update
sudo yum install openssl-devel
```
```
wget https://curl.haxx.se/download/curl-7.55.1.tar.gz
tar -zxf curl-7.55.1.tar.gz
cd curl-7.55.1
./configure --prefix=/usr/local/curl/ --without-nss --with-ssl=/usr/local/ssl/
make && make install
```
`mv /usr/bin/curl /usr/bin/curl.bak`
`ln -s /usr/local/curl/bin/curl /usr/bin/curl`

**Comment by MonikaMalik123** [comment]
System - Linux 7.3
Run -Time - dotnet core 2.0.0

I am running dotnet Core 2.0 application on this container (registry.access.redhat.com/dotnet/dotnet-20-rhel7:latest) in linux 7.3, but when login to application and enter password gives me this error - "**One or more errors occurred. (The handler does not support custom handling of certificates with this combination of libcurl (7.29.0) and its SSL backend ("NSS/3.28.3").)**"
FYI -  This application works fine on Windows.

Please give me any resolution for this issue? Much Appreciated if anyone can help me with this

Thanks

**Comment by wfurt** [comment]
recommendation from @elsyms should work. .net currently does not support NSS for callbacks. 
@tmds  may have some other recommendations. There may be some alternative version with openssl

**Comment by kishoretvk** [comment]
does this also affect windows servers too? i'm getting file not found in path exception but when i try to add the keyset it says, can;t find credentials?

**Comment by tmds** [comment]
I hadn't noticed this issue before...

> system: centos 7.3 runtime: dotnet core 2.0.0

@EssenRoc The dotnet packages that are built for RHEL are also available for CentOS and they include a recent version of libcurl+openssl. https://www.microsoft.com/net/download/linux-package-manager/rhel/sdk-2.0.3 has installation instructions.

> I am running dotnet Core 2.0 application on this container (registry.access.redhat.com/dotnet/dotnet-20-rhel7:latest) in linux 7.3, but when login to application and enter password gives me this error - "One or more errors occurred. (The handler does not support custom handling of certificates with this combination of libcurl (7.29.0) and its SSL backend ("NSS/3.28.3").)"

@MonikaMalik123 That image contains the updated version of libcurl+openssl. There is a known issue that this is not used for stand-alone applications (SCD). If you deploy framework dependent (FDD) then your app will work.
