### ISSUE TITLE
No successful code coverage CI run since July

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#24240]
https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/

:frowning:

**Comment by mellinoe** [comment]
It looks like the tests have been failing on the FileSystem tests for a long time. The test that is failing is this one:
https://github.com/dotnet/corefx/blob/3f6fc6bdb578cfa06324735a2fcab09decced96a/src/System.IO.FileSystem/tests/Directory/Delete.cs#L260

 I opened up the latest crash in the debugger, and it has this call stack:
![image](https://user-images.githubusercontent.com/8918977/30832305-780242ea-a1ff-11e7-9e4f-1669b8282010.png)

That top frame repeats many times, but interestingly it ends in this, which seems to be different:
![image](https://user-images.githubusercontent.com/8918977/30832419-e4b936d2-a1ff-11e7-9930-118e4209cfcb.png)

There is a comment in the test code:

> // On debug we were overflowing the stack with directories that were under 1000
> // levels deep. Testing on a 32GB box I consistently fell over around 1300.
> // With optimizations to the Delete helper I was able to raise this to around 3200.
> // Release binaries don't stress the stack nearly as much (10K+ is doable, but can
> // take 5 minutes on an SSD).


I think we need to change this test.

@JeremyKuhne

**Comment by mellinoe** [comment]
I filed https://github.com/dotnet/corefx/issues/24242 to disable the test against for now.

**Comment by mellinoe** [comment]
The build currently running should have the problematic test disabled:

https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/329/

**Comment by mellinoe** [comment]
There were two issues with that build:

* A sockets test failed. `System.Net.Sockets.Tests.SendReceiveSync.Receive0ByteReturns_WhenPeerDisconnects`

```
10:56:18 
     System.Net.Sockets.Tests.SendReceiveSync.Receive0ByteReturns_WhenPeerDisconnects [FAIL]
10:56:18         System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host
10:56:18         Stack Trace:
10:56:18            D:\j\workspace\code_coverage---b14a30e5\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(1420,0): at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
10:56:18            D:\j\workspace\code_coverage---b14a30e5\src\System.Net.Sockets\tests\FunctionalTests\SocketTestHelper.cs(45,0): at System.Net.Sockets.Tests.SocketHelperArraySync.<>c__DisplayClass4_0.<ReceiveAsync>b__0()
10:56:18               at System.Threading.Tasks.Task`1.InnerInvoke()
10:56:18               at System.Threading.Tasks.Task.<>c.<.cctor>b__279_1(Object obj)
10:56:18               at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
10:56:18               at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
10:56:18            --- End of stack trace from previous location where exception was thrown ---
```

* The run timed out after starting the Transactions tests:

```
11:52:38   Discovering: System.Transactions.Local.Tests
11:52:38   Discovered:  System.Transactions.Local.Tests
11:52:38   Starting:    System.Transactions.Local.Tests
12:29:30 
Build timed out (after 180 minutes). Marking the build as aborted.
```

**Comment by danmosemsft** [comment]
No need to wait another day. I just clicked Rebuild on it. (CAn't remember the difference between Rebuild and Retry..)

**Comment by mellinoe** [comment]
The latest build succeeded: https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/330/artifact/bin/tests/coverage/index.htm

**Comment by stephentoub** [comment]
Thanks, @mellinoe.

**Comment by danmosemsft** [comment]
Now it's hanging in transactions tests. Hopefully this rare one: https://github.com/dotnet/corefx/issues/16283
