### ISSUE TITLE
RecursiveDelete_DeepNesting fails due to StackOverflowException under Code Coverage

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#24242]
This happens on our CI machines, at least.

Call stack from a recent Code Coverage run:

![image](https://user-images.githubusercontent.com/8918977/30832720-02d303a4-a201-11e7-8667-7bf06a6b653a.png)

@JeremyKuhne

**Comment by danmosemsft** [comment]
Guess: runtime generates bigger stack frames when code coverage is enabled. Obvious fix would be to reduce frames by 50% or something.

**Comment by JeremyKuhne** [comment]
The stack is obviously under more pressure in the code coverage runs. Is there a way to tell that we're running under code coverage? Neutering the test isn't a great idea- want to make sure we don't regress what was fixed here.

**Comment by pjanotti** [comment]
This is not happening currently, closing.
