### ISSUE TITLE
GetValueOrDefault available for IReadOnlyDictionary but not IDictionary

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/corefx#24256]
The `CollectionExtensions` extension class provides the `GetValueOrDefault` extension method.
However it extends classes that implement the `IReadOnlyDictionary` interface, hence its usable from `ReadOnlyDictionary` but not from a normal `Dictionary`.

Why isn't this extension method also available for the `Dictionary`?
Wouldn't it be nice if it were?
Perhaps another extension method that extends classes that implement the `IDictionary` interface ought to be inserted into the  `CollectionExtensions` class?

**Comment by stephentoub** [comment]
`Dictionary<TKey, TValue>` implements `IReadOnlyDictionary<TKey, TValue>`.

**Comment by karelz** [comment]
We had the method on `Dictionary` and extension of `IDictionary`. We pulled it out - here's why: #17917.

**Comment by vanillajonathan** [comment]
I see. So as I have come to understand it existed previously but was removed due to conflict when a class implements both the `IDictionary` and the `IReadOnlyDictionary` interfaces.

I find the `GetValueOrDefault` method to be very convenient as it is useful, concise and reduces boilerplate code. I appreciate its presence when using properties and methods with the type declared as `IReadOnlyDictionary`.

However, more often I come across libraries and classes with properties and methods that return the `IDictionary` type. What is the recommended way to get the value if the key exists or return a default value if the key does not exist?

While I think I understand the rationale behind removing it (conflict when implementing both interfaces), I still feel "bummer" because I desire a convenient way to get the value or default value when interacting with dictionaries.

**Comment by karelz** [comment]
Read the rationale behind the interface choice: https://github.com/dotnet/corefx/issues/17917#issuecomment-298706121
Also note the principles we applied which lead to removal even of `Dictionary.GetValueOrDefault`: https://github.com/dotnet/corefx/issues/17275#issuecomment-291636863

**Comment by vanillajonathan** [comment]
Yes, I've read that.
So this means in a future version of .NET Core the `IDictionary` will extend `IReadOnlyDictionary` and hence I will be able to use `GetValueOrDefault` in the future on a `Dictionary` instance?

I understand why it was removed, but find the method convenient and will miss it.

**Comment by danmosemsft** [comment]
@vanillajonathan unfortunately, moving interface members up to a new base interface is a breaking change. See explanation here: https://stackoverflow.com/questions/12622539/why-doesnt-generic-icollection-implement-ireadonlycollection-in-net-4-5
It's unfortunate of course, but I expect some language and runtime changes would need to happen to make this a safe change. I don't closely follow the Roslyn repo, so perhaps this is being discussed, or already decided against.

**Comment by vanillajonathan** [comment]
@danmosemsft I see, so it doesn't sound like `GetValueOrDefault` is coming to `Dictionary` in the near future.

`GetValueOrDefault` is a convenient and much appreciated method though. So if we want to use something like this, should developers resort to create their own `GetValueOrDefault` extension method that extends `IDictionary`, or do something like:

```cs
var foo = dictionary.TryGetValue("key", out string value) ? value : "default";
```
which is tedious and not that concise.

Or is there any solution for this planned, any solution in sight, or any recommended way to deal with the use case of wanting to obtain the value or default value from a dictionary.

**Comment by danmosemsft** [comment]
@vanillajonathan I would add your own extension method, as you say, it's almost a one liner and it would be no less efficient than if it was in the framework.

Hmm, in one of the linked issues, Immo said:

>It seems likely that we'll be able to change the inheritance hierarchy to make IDictionary<K,V> extend IReadOnlyDictionary<K,V>

If that's the case, maybe this will come back later.

**Comment by vanillajonathan** [comment]
@danmosemsft Thanks, so I'll make a extension method meanwhile and then cross my fingers and hope it gets fixed in a later version of .NET Core. :)

**Comment by jnm2** [comment]
@vanillajonathan 

> I see, so it doesn't sound like GetValueOrDefault is coming to Dictionary in the near future.

I don't understand. It did come to `Dictionary<,>` already by virtue of being an extension method on `IReadOnlyDictionary<,>`.

In for original question:

> However it extends classes that implement the IReadOnlyDictionary interface, hence its usable from ReadOnlyDictionary but not from a normal Dictionary.

This is not correct. `Dictionary<,>` implements `IReadOnlyDictionary<,>`. And yes, we all know that the BCL made a mistake and used `IReadOnly*` when it should have used `IReadable*`. It's just a a historical artifact like many other words which we use that aren't strictly etymological English.

**Comment by vanillajonathan** [comment]
@jnm2 Ah, I see. Yes now I see that `GetValueOrDefault` is actually available for `Dictionary`, I missed that because when I declare a field, property or method I always declare the type as `IDictionary` instead of `Dictionary` so as to expose interfaces instead of concrete classes.

So in that case, I have to typecast it to a `Dictionary`.

```cs
((Dictionary<string, string>)foo).GetValueOrDefault("key", "defaultValue");
```

It would be nice if `GetValueOrDefault` was available from `IDictionary` without having to typecast it into a `Dictionary`.

**Comment by danmosemsft** [comment]
@vanillajonathan obviously we can't modify IDictionary itself, but perhaps default interface methods would allow us to solve this. I'm not sure whether it's definitely happening though.

https://github.com/dotnet/csharplang/issues/52

**Comment by jnm2** [comment]
> So in that case, I have to typecast it to a Dictionary.

Specifically, you only have to typecast it to `IReadOnlyDictionary`. And yes, I agree that this is not optimal and I hope there's some way `IDictionary` can base off `IReadOnlyDictionary` in the future.

I'm 100% sure default interface methods is happening, but I'm not sure how interested you'd be in adding all these things as instance methods given the push to keep helper methods as extension methods only.

**Comment by jnm2** [comment]
I thought @tannergooding had started an issue discussing the potential of breaking overload ties by assigning priority via attributes, but I'm failing to find it on csharplang or roslyn. Maybe I have the wrong guy. That would also solve this.

**Comment by jnm2** [comment]
Oops, it was actually @ashmind. Here's the issue, though hopefully it moves to csharplang soon: https://github.com/dotnet/roslyn/issues/5605 (Thanks for finding it, @tannergooding!)

**Comment by jnm2** [comment]
Finally moved to csharplang: https://github.com/dotnet/csharplang/issues/964
