### ISSUE TITLE
System.Console intellisense text not localized

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#24251]
![image](https://user-images.githubusercontent.com/8228359/30842958-e506af44-a23a-11e7-8679-de08a01ef3d2.png)

**Comment by danmosemsft** [comment]
I assume thisi s .NET Core? Is this Console specifically, or all intellisense?

**Comment by Petermarcu** [comment]
I copied this from another issue report. From the image, it's netcoreapp1.1. It could very well be more than Console although I thought we included a ton of localized content in the packages.

**Comment by danmosemsft** [comment]
@mairaw is this your area?

**Comment by mairaw** [comment]
@danmosemsft it would be the Loc team (/cc @nokura). But I see that is Portuguese. I'm not sure if we shipped localized IntelliSense for Portuguese before. Let me find out.

**Comment by karelz** [comment]
@mairaw @nokura any update?

**Comment by mairaw** [comment]
@weshaggard for .NET Core, we've only included English so far, no?

**Comment by weshaggard** [comment]
That is correct. We only have English.

**Comment by mairaw** [comment]
Just FYI, we're still discussing this and how to enable that for .NET Core. We should have a plan in the next few weeks. If anyone needs to be involved in that, in addition to @ahsonkhan and @safern, please let me know.

**Comment by stephentoub** [comment]
Thanks, @mairaw.

**Comment by mairaw** [comment]
Just FYI, we released today a solution for developers to install localized IntelliSense for .NET Core:
https://docs.microsoft.com/dotnet/core/install/localized-intellisense

@terrajobst is looking at how we can make that better for future releases.
