### ISSUE TITLE
Thounds of threads call System.Threading.WaitHandle.WaitOne

### ISSUE THREAD

**Issue by anthonywanted** [dotnet/corefx#24278]
Our application running a signalR server and thrift server. While it runs 2 days or more, it use cpu 100% and threads count up to thounds, just suddenly. 
I dump a core dump, and run sos EEStack, thounds of threads stack looks like this
![image](https://user-images.githubusercontent.com/26265122/30893942-66942e36-a373-11e7-80db-83aef70e0e2e.png)

Here is the zabbix graphs
![image](https://user-images.githubusercontent.com/26265122/30894354-e4bbbf84-a375-11e7-8bd6-f928eb3069c8.png)
![image](https://user-images.githubusercontent.com/26265122/30894370-fae14f4a-a375-11e7-9ecb-a5dd4f719d9c.png)

Here is the code, core dump is showing some problem in 
`cancelTokenSource.Token.WaitHandle.WaitOne();`

    public class AccessServer
    {
        private ILogUtility logger = LogFactory.Create(typeof(AccessServer));

        private CancellationTokenSource cancelTokenSource = new CancellationTokenSource();

        protected IWebHost webHost;

        public void Run()
        {
            try
            {
                var settings = ConfigurationUtility.GetSettings<Settings>("appsettings");
                var commonSettings = ConfigurationUtility.GetSettings<CommonSettings>("commonsettings");
                string serviceName = typeof(IAccessService).GetThriftServiceName();
                int port = settings.ThriftPorts[serviceName];

                StartupService.Current
                .LoadAllAssemblyInBaseDirectory()
                .UseAutofac()
                .RegisterMapper()
                .InitStartupTask()
                .InitUpstreamMessageManager()
                .Start();

                webHost = new WebHostBuilder()
                    .UseKestrel(o => { })
                    .UseContentRoot(Directory.GetCurrentDirectory())
                    .UseStartup<Startup>()
                    .UseUrls(settings.LocalServer)
                    .Build();

                webHost.Start();
                $"SignalR running on {settings.LocalServer}".WriteInfoLog();
                StartupService.Current.StartThriftServices(commonSettings.LocalServerIP, port, cancelTokenSource,
                   new List<(Type Type, string ServiceName, string ServiceNameConfig)>() { (typeof(IAccessService), $"{serviceName}-{commonSettings.LocalServerIP.Replace(".", "-")}-{port}", serviceName) });

                cancelTokenSource.Token.WaitHandle.WaitOne();
            }
            catch (Exception ex)
            {
                logger.Error($"Access run error：{ex.Message}", ex);
            }
        }
    }

environment is docker(17.06.0-ce, build 02c1d87) using dotnet image (dotnet:v1.1 runtime) running on centos 7.2(kernel 3.10.0-327.el7.x86_64)

**Comment by danmosemsft** [comment]
@anthonywanted I'm not familiar with SignalR (this is the CoreFX repo, not the SignalR repo) but if you are seeing many callstacks with Main->Run then that would mean your Main() is calling Run() on many threads.  (Each thread is then launching this service, then waiting on it.) Is that what you expect?

**Comment by karelz** [comment]
This issue was moved to aspnet/SignalR#965
