### ISSUE TITLE
Tests under "System.Globalization.Tests" failed with "Xunit.Sdk.TrueException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#24298]
System.Globalization.Tests.RegionInfoPropertyTests.DisplayName failed

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release/3216/testReport/System.Globalization.Tests/RegionInfoPropertyTests/DisplayName_name____en_US____expected____United_States___/

Configuration: osx10.12_release

MESSAGE:
~~~
Exit code was 131 but it should have been 42\nExpected: True\nActual: False
~~~
STACK TRACE:
~~~
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() 
in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 189
~~~

**Comment by Jiayili1** [comment]
Failed tests:
 System.Globalization.Tests.RegionInfoPropertyTests.DisplayName
 System.Globalization.Tests.RegionInfoPropertyTests.CurrentRegion
 System.Globalization.Tests.CultureInfoDateTimeFormat.TestSettingThreadCultures
 System.Globalization.Tests.NumberFormatInfoCurrentInfo.CurrentInfo_Subclass_OverridesNumberFormat
 System.Globalization.Tests.NumberFormatInfoCurrentInfo.CurrentInfo_Subclass_OverridesGetFormat
 System.Globalization.Tests.NumberFormatInfoCurrentInfo.CurrentInfo_CustomCulture
 System.Globalization.Tests.CurrentCultureTests.CurrentCulture_BasedOnLangEnvVar
 System.Globalization.Tests.CurrentCultureTests.CurrentUICulture
 System.Globalization.Tests.CurrentCultureTests.DefaultThreadCurrentCulture
 System.Globalization.Tests.CurrentCultureTests.CurrentCulture_DefaultWithNoLang
 System.Globalization.Tests.CurrentCultureTests.CurrentCulture
 System.Globalization.Tests.CurrentCultureTests.DefaultThreadCurrentUICulture

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release/3216/testReport/

**Comment by danmosemsft** [comment]
131 = SIGQUIT. This has passed since, not worth investigation unless it happens again.
