### ISSUE TITLE
Port fixes for RHEL69 tests to 2.0

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#24304]
https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170927.01

@tarekgh since you made these fixes would you mind porting so this goes green? Look like trivial disablings, although a few lines need pasting into PlatformDetection, as it's moved around since 2.0 branched.

**Comment by tarekgh** [comment]
will try to get into this in the first chance.

**Comment by krwq** [comment]
Globalization and pipes failures and some FileSystem failures are gone. I do not have context for the remaining System.IO failures - also haven't seen them locally:
https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20171011.01

**Comment by karelz** [comment]
Given that 2.0 will be out of support in less than 1 month, closing as Won't Fix.
