### ISSUE TITLE
Nobody but the developer should ever modify a GIT-tracked file.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#24303]
I regularly keep GIT-tracked files as read-only, both so I can browse them in editors with peace and so I can catch things that try to do what this thing is doing:

https://github.com/dotnet/corefx/blob/a989d4f91cf4208b7a2481d120498a581328eb1d/pkg/Microsoft.NETCore.Platforms/runtimeGroups.props#L144

```
  <Target Name="GenerateRuntimeJson" BeforeTargets="CreatePackage">

    <!-- Note that we intentionally modify the runtime*json that is under source control.

         We want to keep this up to date in source control so that we can see the diff in the 

         runtime.json over time as changes are made to RuntimeGroups. -->
```

In a word, **no**. 

**Only** the developer should ever alter a GIT-tracked file. If GIT reports a change to a file I didn't make, I will "git reset --hard." This is precisely one of the benefits of source control - to alert me to unauthorized changes.

**Comment by ericstj** [comment]
It will only create a diff to the file if you modify the runtimeGroups.props file so it is the developer making the change, we're just translating the change to a couple other formats.

We have been doing the same thing for the API compat baselines in the past to avoid the forcing developers to manually update them.

In this case we do this to provide diff's of the shipping asset (so we can see what actually gets produced and git-blame it) and diffs of the changes to the compatiblity chain.  Both of these are good things.  They are a lot more meaningful to diff when folks change the RID graph.

It sounds like you don't want us even rewriting the file.  I can change the target to do that: only write the file if there is a physical difference.

I'd really like to avoid forcing the developer to run a different target to do this because I always get the complaint "why don't you just do that for me"?

Would that make it better?

**Comment by AtsushiKan** [comment]
>It will only create a diff to the file if you modify the runtimeGroups.props file

You're opening a write-access file handle to runtime.json every single time, whether or not there is a diff.

>In this case we do this to provide diff's of the shipping asset 

Right, I get that this is a form of telemetry, but it should be done in a way that doesn't impact GIT workflows. It shouldn't show up in "git status" on someone's local branch. 

>I'd really like to avoid forcing the developer to run a different target to do this because I always get the >complaint "why don't you just do that for me"?

What's the plan for keeping out-of-sync runtime.json's out of the master branch? When I purposefully clean-build on a repo with an out of date and attrib -r'd runtime.json, there's no notification from the build that that file changed - it just happens silently. So if someone submits a PR that changes the .props file without updating the .json, the CI will still pass (it'll just "fix" the problem on its own branch) but the bad change will still get into the master branch. Now, everyone who fetches the upstream master and runs "build.cmd" will have a dirty workspace with no actionable response. It's one of the tenets of the fork-and-pull workflow that you never commit local changes to the master branch, and in any case, it's not their change or responsibility to do so.

So yes, if two tracked files require a synchronized change, it **should** require special attention from the developer that made the change so he knows to make them synchronized before submitting his branch for a PPR.

**Comment by ericstj** [comment]
> You're opening a write-access file handle to runtime.json every single time, whether or not there is a diff.

Understood, I already mentioned I'll fix that.

> if two tracked files require a synchronized change, it should require special attention from the developer that made the change so he knows to make them synchronized before submitting his branch for a PPR.

That's a good principle to have.  I've followed it in the past and got a **lot** of negative feedback (PackageIndex), so I was hoping to do better here.  The frequency of the runtime.json updates is much lower so perhaps it's less of an issue.

**Comment by AtsushiKan** [comment]
So here's what I'd consider the min-fix:

- As already discussed and apparently agreed, don't write or even open the file for writing unless there's an actual change to be made. (And if the file is not writable, a better diagnostic than "System.IO.Exception" would be good too. Something like "Sorry, we have to change this other file because of a change in this one. Your attrib +r'ing the files indicates you'd rather not we not do this automatically. But the somehow or other, change has to be made before things will work.")

- Out of sync .json files should be fatal error in CI builds.

**Comment by ericstj** [comment]
I don't want to try to make CI catch it  but have things be automatic on dev builds.  That'll cause folks to miss the change from their commits, or might break if our mechanism for detecting a CI build changes.

I'll keep it simple and just fail when things are out of sync anywhere and force people to run a target manually.

When running a manual target (an explicit developer action) do you think its reasonable to force-overwrite a readonly file?  That way I won't make you explicitly attrib -r, you can just run /t:UpdateRuntimeJson.

**Comment by AtsushiKan** [comment]
>When running a manual target (an explicit developer action) do you think its reasonable to force-overwrite a readonly file?

That sounds reasonable. GIT does the same thing.
