### ISSUE TITLE
IPPacketInformation.Interface

### ISSUE THREAD

**Issue by tamaskaroly** [dotnet/corefx#24312]
Hi! Could you please specify the meaning of the value of IPPacketInformation.Interface? I thought it was an index into the array returned by NetworkInterface.GetAllNetworkInterfaces(), but it is not the case. It isn't a random number, but it's definitely not the proper index either. Thanks, Tamás

**Comment by tamaskaroly** [comment]
After further analysis, I found that there is no direct relationship between IPPacketInformation.Interface and the array returned by NetworkInterface.GetAllNetworkInterfaces(). To correctly map IPPacketInformation.Interface to an interface you have to use if_indextoname from libc, then use that name to look up the interface in the array mentioned. To avoid having to use p/invoke, it would be great if you could add a read-only "Index" property to the NetworkInterface class that would contain the value from if_nametoindex. Both if_indextoname and if_nametoindex are available on Linux, OSx and Windows.

**Comment by tamaskaroly** [comment]
if_nametoindex and if_indextoname work correctly under Linux, but under Windows the returned interface names are very strange (long names with guids). I found no way to get the proper index from the interface name, so I think there is no simple solution to solve this. I recommend you close this issue.

**Comment by CerebralMischief** [comment]
Maybe there is a way to use some "hacky" Windows only lookup from a dictionary that will allow the proper name to be returned?  The trick becomes then determine how to populate said dictionary with the odd long name with guids along with the proper name.  Or am I missing a bigger issue here?  Thanks!

**Comment by tamaskaroly** [comment]
Ok, false alarm! networkInterface.GetIPProperties().GetIPv4Properties().Index contains the correct index of the adapter. I tested it under Linux and Windows and it returns the same values as the IPPacketInformation.Interface. Sorry for reporting this as an issue without analyzing the problem deeper. (I don't actually understand why Index is under the IPv4 properties, but that's a different story.)

**Comment by CerebralMischief** [comment]
Good news! :)
