### ISSUE TITLE
Unable to use .NET Framework library that uses System.Drawing

### ISSUE THREAD

**Issue by IGx89** [dotnet/corefx#24332]
Hello! Apologies if the answer is obvious, but I'm attempting to use a .NET Framework library (ZedGraph) that uses System.Drawing in my .NET Core 2 application and am having difficulties doing so. I added a reference to the new System.Drawing.Common package, but while it lets me use System.Drawing classes (like Graphics) it doesn't seem to transfer to the .NET Framework library I'm using.

If I attempt to call a method in the library that takes in or returns a System.Drawing object such as Graphics, I get a compile error like the following:

```
CS7069: Reference to type 'Graphics' claims it is defined in 'System.Drawing', but it could not be found
```

Any clue what's going on? I tried recompiling the library to .NET Framework 4.5.1 (it was previous compiled for 3.5), to no avail.

Thanks!

Steps to reproduce:

1. Create a ,NET Core 2 class library
2. Add references to System.Drawing.Common and ZedGraph
3. Call a ZedGraph method whose signature involves a System.Drawing class, such as this: `new ZedGraph.GraphPane().Draw(out System.Drawing.Graphics g);`

**Comment by mellinoe** [comment]
@weshaggard @ericstj Do we have a way for customers to get a newer version of the shims for .NET Core? The System.Drawing shim built into .NET Core 2.0 will obviously only have type-forwards for stuff in System.Drawing.Primitives.

**Comment by weshaggard** [comment]
Currently we don't without updating to the latest Microsoft.NETCore.App.

**Comment by danmosemsft** [comment]
@IGx89 are you able to use newer builds ?

**Comment by IGx89** [comment]
Of what? .NET Core? 2.1 preview 1?

**Comment by ViktorHofer** [comment]
One of the nightly builds for example. There isn't an official .NET Core 2.1 preview 1 out yet. 

Another option would be building corefx from master and copying "~\corefx\bin\testhost\netcoreapp-Windows_NT-Debug-x64\shared\Microsoft.NETCore.App\9.9.9\System.Drawing.dll" to "~\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0\System.Drawing.Primitives.dll". This file contains all the necessary type forwards that we are added since the Core 2.0 release with the System.Drawing effort.

**Comment by safern** [comment]
This should be fixed on the live builds and in the next builds. 

@IGx89 please feel free to ask more questions or keep the discussion going in this issue if you need further help.
