### ISSUE TITLE
Static PerformanceCounterLib.GetPerformanceCounterLib is not thread-safe

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#24364]
Outside of any locks GetPerformanceCounterLib both reads and writes to a normal. static `Dictionary<>`.
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/PerformanceCounterLib.cs#L74-L78

**Comment by supporterPL** [comment]
@stephentoub Is exclusive lock around read/write code will be enough?

` lock (LazyInitializer.EnsureInitialized(ref s_libraryTableSyncObject))
      {
            if (!PerformanceCounterLib.s_libraryTable.TryGetValue(libraryKey, out library))
            {
                library = new PerformanceCounterLib(machineName, lcidString);
                PerformanceCounterLib.s_libraryTable[libraryKey] = library;
             }
     }
`

**Comment by stephentoub** [comment]
@supporterPL, that would fix the race condition, but it would also incur taking a lock even on the fast path of just reading an already initialized counter.  I've not measured, but I suspect that could actually lead to a scalability issue.  A better fix in my opinion would be using a ConcurrentDictionary instead of a Dictionary.

**Comment by supporterPL** [comment]
@stephentoub I will try to compare performance between lock and ConcurrentDictionary in different scenrios and let you know.

**Comment by supporterPL** [comment]
@stephentoub  You were right. ConcurrentDictionary is faster for fast and slow path. May I take this issue? 

Results:

Method | ConcurrentThreads | Mean | Error | StdDev | Median
-- | -- | -- | -- | -- | --
FastPathLockTest | 10 | 9.497 us | 0.1999 us | 0.5895 us | 9.526 us
FastPathConcurrentDictionaryTest | 10 | 6.352 us | 0.0385 us | 0.0342 us | 6.348 us
SlowPathConcurrentDictionaryTest | 10 | 7.032 us | 0.1403 us | 0.2184 us | 6.917 us
SlowPathLockTest | 10 | 11.352 us | 0.1233 us | 0.1030 us | 11.341 us
FastPathLockTest | 100 | 62.847 us | 0.3996 us | 0.3337 us | 62.855 us
FastPathConcurrentDictionaryTest | 100 | 40.029 us | 0.8712 us | 1.8186 us | 39.165 us
SlowPathConcurrentDictionaryTest | 100 | 38.623 us | 0.7562 us | 0.9563 us | 38.147 us
SlowPathLockTest | 100 | 73.007 us | 0.4587 us | 0.4291 us | 73.122 us
FastPathLockTest | 1000 | 510.328 us | 5.0925 us | 4.7635 us | 510.937 us
FastPathConcurrentDictionaryTest | 1000 | 389.969 us | 7.3587 us | 8.7600 us | 391.541 us
SlowPathConcurrentDictionaryTest | 1000 | 412.112 us | 10.6824 us | 17.8479 us | 404.328 us
SlowPathLockTest | 1000 | 649.940 us | 9.1496 us | 8.1109 us | 649.538 us

**Comment by stephentoub** [comment]
> May I take this issue?

Sure, thanks :)

**Comment by supporterPL** [comment]
Added PR (#24476).

**Comment by wtgodbe** [comment]
Can we close this?

**Comment by stephentoub** [comment]
Yup.
