### ISSUE TITLE
XmlDocument The name 'debuggerDisplayProxy' does not exist in the current context

### ISSUE THREAD

**Issue by angelcalvasp** [dotnet/corefx#24360]
When I create a new XmlDocument the local variable is showing the following error

error CS0103: The name 'debuggerDisplayProxy' does not exist in the current context

![image](https://user-images.githubusercontent.com/7502746/31047927-f6ac56ee-a5d8-11e7-9123-d7342f1a1dcc.png)

**Comment by ckrandhir** [comment]
I have the same problem when I am using this line of code

var doc = new XmlDocument
          {
            XmlResolver = null,
            PreserveWhitespace = true
          };

      var samlResponse = encoding.GetString(Convert.FromBase64String(base64SamlResponse));
            doc.LoadXml(samlResponse);
            return doc;

please help

**Comment by stephentoub** [comment]
> I have the same problem when I am using this line of code

Are you using .NET Core 2.1?  The fix for this is there.

**Comment by ckrandhir** [comment]
I am using .Net core 2.0

**Comment by danmosemsft** [comment]
@ckrandhir note that 2.0 will go out of support on Sept 1st.

https://github.com/dotnet/core/blob/master/microsoft-support.md
https://github.com/dotnet/core/blob/4c4642d548074b3fbfd425541a968aadd75fea99/release-notes/2.1/2.1.1.md
