### ISSUE TITLE
WinHttpHandler not respecting case sensitivity of request `Connection` header (`Keep-Alive`)

### ISSUE THREAD

**Issue by MatthewLymer** [dotnet/corefx#24363]
The `WinHttpHandler` class (and I'm assuming WinHTTP) has an issue when sending the `Connection` HTTP header.

The problem is that any requests sent through `WinHttpHandler` that are intended to be keep-alive always emit a header that reads `Connection: Keep-Alive` (note the casing of the header value).  

I am also looking for a workaround / alternatives, as I have no control over the server I am sending requests to (the server chokes on `Connection: Keep-Alive` but not `Connection: keep-alive`).

Setup:
- Dotnet Core 2.0.0
- Windows 10 Creators Update

Notes:
- Dotnet Core 2.0.0 on Ubuntu 16.04.2 LTS with `CurlHandler` does not exhibit this problem

Unit Test:
```
public sealed class WinHttpHandlerTests
{
    [Theory]
    [InlineData("keep-alive")]
    [InlineData("KEEP-ALIVE")]
    [InlineData("Keep-Alive")]
    [InlineData("KEEP_ALIVE")]
    public async Task ShouldRespectConnectionCaseSensitivity(string expectedHeaderValue)
    {
        using (var listener = new EchoingHttpListener())
        using (var request = new HttpRequestMessage(HttpMethod.Get, $"http://localhost:{listener.Port}"))
        {
            request.Headers.TryAddWithoutValidation("Connection", expectedHeaderValue);

            using (var client = new HttpClient(new WinHttpHandler()))
            using (var response = await client.SendAsync(request))
            {
                var body = await response.Content.ReadAsStringAsync();
                var actualHeaderValue = Regex.Match(body, "Connection: (.*)\r\n").Groups[1].Value;
                Assert.Equal(expectedHeaderValue, actualHeaderValue);
            }
        }
    }
}

internal sealed class EchoingHttpListener : IDisposable
{
    private readonly CancellationTokenSource _cts = new CancellationTokenSource();
    private readonly TcpListener _listener = new TcpListener(IPAddress.Any, 0);
    private readonly Task _listenTask;

    public EchoingHttpListener()
    {
        _listener.Start();
        Port = ((IPEndPoint) _listener.LocalEndpoint).Port;

        var token = _cts.Token;

        _listenTask = Task.Run(async () => await Listen(token));
    }

    private async Task Listen(CancellationToken token)
    {
        while (!token.IsCancellationRequested)
        {
            using (var client = await _listener.AcceptTcpClientAsync())
            {
                var stream = client.GetStream();

                var encoding = new UTF8Encoding(false);

                using (var reader = new StreamReader(stream, encoding, false, 2048, true))
                using (var writer = new StreamWriter(stream, encoding, 2048, true))
                {
                    var request = await ReadRequestAsync(reader);

                    await writer.WriteLineAsync("HTTP/1.1 200 OK");
                    await writer.WriteLineAsync("Connection: close");
                    await writer.WriteLineAsync("Content-Type: text/plain; charset=utf-8");
                    await writer.WriteLineAsync($"Content-Length: {encoding.GetByteCount(request)}");
                    await writer.WriteLineAsync();
                    await writer.WriteAsync(request);
                }
            }
        }
    }

    private static async Task<string> ReadRequestAsync(TextReader reader)
    {
        var sb = new StringBuilder();

        string line;

        do
        {
            line = await reader.ReadLineAsync();
            sb.AppendLine(line);
        } while (line != string.Empty);
        
        return sb.ToString();
    }

    public int Port { get; }

    public void Dispose()
    {
        _listener.Stop();
        _cts.Cancel();

        try
        {
            _listenTask.Wait();
        }
        catch
        {
            // ignored
        }
        
        _cts.Dispose();
    }
}
```

**Comment by davidsh** [comment]
The headers and values are supposed to be case insensitive.

What is the exact version of the IIS server that is having problems?

**Comment by MatthewLymer** [comment]
It might not be relevant (or even IIS), it's a 3rd party server so the only information I have indicating it is response headers:
```
X-AspNetMvc-Version: 4.0
X-AspNet-Version: 4.0.30319
```

**Comment by davidsh** [comment]
Unfortunately, the Connection: Keep-Alive is something that is "owned" by WinHTTP and hence WinHttpHandler.  There is no workaround to change how the casing of this works.

**Comment by cboudereau** [comment]
You are right about spec but sometimes we have to use crazing system that will not support the "Keep-Alive" with K and A in upper case. It is a blocking issue here. How can we fix winhttp.dll ?

**Comment by davidsh** [comment]
cc: @karelz 

>How can we fix winhttp.dll ?

What type of fix are you proposing?

1) Change winhttp.dll so that it sends out "keep-alive" with lowercase letters
2) Change winhttp.dll so that it keeps the casing as-is if the header is manually specified by an app developer (i.e. thru the .NET api's etc.)

It is unlikely that 1) can be done since changes like that are risky and might affect app-compat for other scenarios.  Change 2) might be possible.  

You can submit feedback to the Windows team about this request via the Feeback Hub app:
![image](https://user-images.githubusercontent.com/7684835/48650757-63094a00-e9ac-11e8-9e67-2babd32939bc.png)

See:
https://windows10.help/blogs/entry/54-how-to-submit-a-suggestion-or-bug-report-in-windows-10-using-feedback-hub/

**Comment by cboudereau** [comment]
Thank you. Yes I guess a default one but if we provide our keep-alive
header value it will keep it like libcurl.
