### ISSUE TITLE
RSAKeyValue.LoadXml not working when XmlElement input has namespace prefix

### ISSUE THREAD

**Issue by angelcalvasp** [dotnet/corefx#24375]
Are there any know workaround for issue #22229 with digital signatures?

**Comment by karelz** [comment]
cc @brunin2509 @krwq @bartonjs @ianhays

**Comment by brunin2509** [comment]
Apparently, since version 4.5.0-preview2-25520 or something like that (when PR #22336 was merged into master), a solution for this issue has already been included in System.Security.Cryptography.Xml.

**Comment by angelcalvasp** [comment]
Yes I know this but its on a preview version, which I cant use for my current development proyect, but I found myself a workaround to get that behavior on 2.0.0

**Comment by petertsu** [comment]
@angelcalvasp  Could you you share  your workaround please ? I need that behavior on 2.0.3 .
Thanks

**Comment by d96patel** [comment]
@angelcalvasp Could you please share your workaround for 2.0.0?
