### ISSUE TITLE
Give access to raw list of headers in HttpResponseHeaders

### ISSUE THREAD

**Issue by cknaap** [dotnet/corefx#24373]
If a header is not accessible through HttpResponseHeaders (in my case Last-Modified) it would be convenient to have access to the raw list of headers:

response.Headers.Values("Last-Modified")

Currently this does not give a result, although I put the header in the response (as I can check by testing it in Postman).

**Comment by davidsh** [comment]
You can already get any header you want by using HttpResponseMessage.Headers.TryGetValues or HttpResponseMessage.Content.Headers.TryGetValues

https://msdn.microsoft.com/en-us/library/system.net.http.headers.httpheaders.trygetvalues(v=vs.118).aspx

**Comment by cknaap** [comment]
Thanks. The method works, but returns an empty enumeration where I expected the Last-Modified header value that I put in it.

**Comment by Priya91** [comment]
@cknaap Can you share the code that you used to test this, with expected and actual outputs?

**Comment by karelz** [comment]
No response in 20 days. Closing.
Feel free to reopen when you have repro available. Thanks!
