### ISSUE TITLE
HttpClient: The HTTP redirect request failed

### ISSUE THREAD

**Issue by mfilippov** [dotnet/corefx#24380]
Hi, all. I try to port a VimeoDotNet library to .NET Core but I have the problem.
I have the request:
```
PUT https://1512435594.cloud.vimeo.com/upload?ticket_id=108999278&video_file_id=842140596&signature=0766cfcc58ec6815425054fd2f31c2ab&v6=1 HTTP/1.1
Connection: Keep-Alive
Content-Range: bytes */*
Accept: application/vnd.vimeo.*+json; version=3.2, application/json
Accept-Encoding: gzip, deflate
Content-Length: 0
Host: 1512435594.cloud.vimeo.com
```
and the response:
```
HTTP/1.1 308 Resume Incomplete
Server: Vimeo/2.0
Content-Type: text/plain
Access-Control-Allow-Origin: *
Timing-Allow-Origin: *
Access-Control-Expose-Headers: Range
Access-Control-Allow-Headers: Content-Type, Content-Range,  X-Requested-With
X-Requested-With: XMLHttpRequest
Access-Control-Allow-Methods: POST, PUT, GET, OPTIONS
Content-Length: 0
Connection: close
Range: bytes=0-5510872
Date: Mon, 02 Oct 2017 18:57:37 GMT
X-Backend-Server: kopiluwak
```
It's worked on Full framework but on .NET Core I have exception:
```
The HTTP redirect request failed
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
```
How can I workaround it?

**Comment by davidsh** [comment]
I tried to repro this just using Fiddler and the composer tab in Fiddler.  I sent the PUT request as you detailed above.

And I got the same response back:

```
HTTP/1.1 308 Resume Incomplete
Server: Vimeo/2.0
Content-Type: text/plain
Access-Control-Allow-Origin: *
Timing-Allow-Origin: *
Access-Control-Expose-Headers: Range
Access-Control-Allow-Headers: Content-Type, Content-Range,  X-Requested-With
X-Requested-With: XMLHttpRequest
Access-Control-Allow-Methods: POST, PUT, GET, OPTIONS
Content-Length: 0
Connection: close
Range: bytes=0-5510872
Date: Mon, 02 Oct 2017 22:39:37 GMT
X-Backend-Server: kopiluwak
```

**Comment by davidsh** [comment]
And normally the 308 response code is a "redirect" type response.  And this reponse is supposed to have a "Location: " response header.  That response header would be used to figure out how to do automatic redirection.

But as shown above, this 308 response is missing the "Location: " response header.  So, this looks like a server problem.

**Comment by davidsh** [comment]
Also, according to this:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308

```
Some Web applications may use the 308 Permanent Redirect in a non-standard way and for other purposes. For example, Google Drive uses a 308 Resume Incomplete response to indicate to the client when an incomplete upload stalled.
```

So, it's possible that this website is using the 308 but not as a redirect, but rather as some non-standard way of returning an error due to a PUT/POST request failing.  In this case, it is probably failing but the Content-Length is zero.  Perhaps, this server needs a non-zero body in the PUT/POST.

**Comment by mfilippov** [comment]
@davidsh Thanks for the answer. I try to contact with server developers. I don't understand why it behaves differently with full framework.

**Comment by mfilippov** [comment]
@davidsh Could I avoid this exception?

**Comment by mfilippov** [comment]
@davidsh I found workaround just disable auto redirects:
```
new HttpClient(new HttpClientHandler { AllowAutoRedirect = false });
````

**Comment by davidsh** [comment]
>@davidsh I found workaround just disable auto redirects:
new HttpClient(new HttpClientHandler { AllowAutoRedirect = false });

Yes, that is the correct way to handle this.  Since the server is sending a faulty redirect code, turning off automatic redirects will prevent the HttpRequestException.  Then, you simply get the 308 response state code back in an HttpResponseMessage.

Since this is a server issue, I will close this issue now.
