### ISSUE TITLE
Please introduce IEnumerable<char> constructor in System.String

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/corefx#24395]
Hi,

### Motive

In order to initialize a `string` from an `IEnumerable<char>` via LINQ etc., we must first manually create an array by calling `ToArray` or other means.

### Desired API

```c#
IEnumerable<char> chars = GetChars();
string str = new string(chars);
```

Achievable by adding another constructor overload that copies the enumerable of chars into a new string.

**Comment by stephentoub** [comment]
This already works:
```C#
IEnumerable<char> chars = GetChars();
string str = string.Concat(chars);
```
If the concern then is just about perf, I'd rather see the implementation of Concat specialized to handle char than to introduce a new member for this.

**Comment by weitzhandler** [comment]
Re-opening to consider dedicated a special `Concat` overload.

**Comment by stephentoub** [comment]
> Re-opening to consider dedicated a special Concat overload.

I didn't mean a new overload. I meant changing the existing overload's implementation to special-case T==char, as an optimization / implementation detail.

**Comment by weitzhandler** [comment]
@stephentoub Oh, now I understand. Because `string` is still `IEnumerable<char>`, so we don't have to change anything, is that what you meant?

If so, there might however be a performance impact because it will lose deferred execution which might impact performance in large char arrays when the desired result is a deferred execution `IEnumerable<char>` rather than `string`.

**Comment by stephentoub** [comment]
> we don't have to change the return type of Enumerable.Concat, just the implementation, is that what you meant?

`string.Concat(IEnumerable<T>)` already exists and provides the desired semantics: you give it an `IEnumerable<char>`, it gives you back a string of those chars.  The issue with that as an implementation is it's relatively inefficient, as it works with arbitrary Ts and thus calls ToString on each individual T in order to append the string to an internal StringBuilder.  But we can special-case when T==char, avoid going through intermediate strings, and use StringBuilder.Append(char):
https://github.com/dotnet/coreclr/pull/14298

> there might however be a performance impact because it will lose deferred execution

I'm not following.  Can you elaborate?

**Comment by weitzhandler** [comment]
@stephentoub 
>I'm not following. Can you elaborate?

Irrelevant. I thought you were talking about `Enumerable.Concat`.

**Comment by weitzhandler** [comment]
@stephentoub 
>I'm not following. Can you elaborate?

Irrelevant. I thought you were talking about `Enumerable.Concat`.

Anyway, I'm willing to implement this, you can assign me @karelz.

**Comment by stephentoub** [comment]
> I'm willing to implement this

Already did:
https://github.com/dotnet/coreclr/pull/14298

**Comment by weitzhandler** [comment]
Awesome! Thank you!
