### ISSUE TITLE
Passing null to an method that takes a ReadOnlySpan<T> throws, but default(ReadOnlySpan<int>) does not

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#24409]
This is because default(ReadOnlySpan<T>) results in a zero-length span, null is treated as a T[] which is implicitly converted to ReadOnlySpan<T> and triggers a [null check](https://github.com/dotnet/corefx/blob/8d212b41126baff94fc025e4438d6f4e8cbff7e9/src/System.Memory/src/System/Span.cs#L32-L33) in the constructor.

It's non-intuitive for an implicit operator to throw.  It violates the [API design guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/operator-overloads) as well:

>X DO NOT throw exceptions from implicit casts.
It is very difficult for end users to understand what is happening, because they might not be aware that a conversion is taking place.

/cc @ahsonkhan @KrzysztofCwalina

**Comment by ahsonkhan** [comment]
Should the implicit operation call an internal constructor which returns default(Span) when the array is null instead of throwing?
https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/Span.cs#L351

The implicit cast would also throw if there is an [array mismatch](https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/Span.cs#L34-L35). What should we do in that scenario?
```C#
static void Main(string[] args)
{
    string[] a = { "Hello" };
    ReadSpanLength(a);  // Throws System.ArrayTypeMismatchException: Attempted to access an element as a type incompatible with the array.
}

public static void ReadSpanLength(Span<object> span)
{
    Console.WriteLine(span.Length);
}
```

**Comment by KrzysztofCwalina** [comment]
Yeah, I think this is reasonable, i.e. the cast should result in empty memory

**Comment by ahsonkhan** [comment]
> The implicit cast would also throw if there is an [array mismatch](https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/Span.cs#L34-L35). What should we do in that scenario?

> Yeah, I think this is reasonable, i.e. the cast should result in empty memory

Even for array type mismatch?

**Comment by KrzysztofCwalina** [comment]
I would not change the ctor; just the cast operator. In the cast operator, there is no possibility of mismatch (as the type of the span is inferred from the array), is there?

**Comment by ahsonkhan** [comment]
> there is no possibility of mismatch 

What about array covariance (from the code snippet I posted above)?
```C#
object[] array = new String[10];
```

**Comment by KrzysztofCwalina** [comment]
keep going, i.e. how do I get to be casing null.

**Comment by ahsonkhan** [comment]
> keep going, i.e. how do I get to be casing null?

In the code snippet, there is no null casting, but it still goes against the guideline that @ericstj mentioned since an implicit cast (from string[] to Span\<object\>) is resulting in an exception being thrown.

**Comment by benaadams** [comment]
Similar issue to https://github.com/dotnet/coreclr/issues/14012 on ArraySegments

**Comment by KrzysztofCwalina** [comment]
I think casting nulls, comparing nulls, etc. should just work and we can make it work. I don't believe there is a solution to the covarinace issue, i.e. 
```c#
object[] array = new String[10];
Span<object> s = array;
```
will always fail and we cannot make it not fail.

**Comment by ericstj** [comment]
What if you delayed the co-variance exception to access instead of in the constructor?  Do you think it would be a more intuitive failure, or do you think this is a case where we have to break the rule (you wrote I believe 😉) about throwing from implicit cast.

**Comment by KrzysztofCwalina** [comment]
I think we need to break the rule. 
Doing the check in the accessors (e.g. the indexer) would be both slow and probably surprising

**Comment by benaadams** [comment]
Its the Exception that proves the rule 😉

**Comment by KrzysztofCwalina** [comment]
That would be an awsome annotation to the design guideline :-)

**Comment by ericstj** [comment]
I do think we need some guidelines for Span/Memory as well.
