### ISSUE TITLE
Proposal for unordered remove API's for List<T> 

### ISSUE THREAD

**Issue by ArthurBrussee** [dotnet/corefx#24408]
First time contributor, long time lurker. I have a background in gamedev, and while it might be some time before Unity uses Core I wanted to contribute early!

A common pattern in game dev to keep lists of objects of a certain type so they can be quickly iterated over eg to call some Update function. Objects register / deregister when created / destroyed. A direct implementation would be:

```C#
void OnCreate() { All.Add(this); }
void OnDestroy() { All.Remove(this); }
```

However, when a (part of) the world gets destroyed, lots of objects deregister at once. Each Remove has to move over the backing array. A common way to prevent this additional move is to use a remove with a swap back:

```C#
All[index] = All[All.Count - 1];
All.RemoveAt(All.Count - 1);
```
Unreal engine has specific API's for their "List" Implementation to do a swap remove: https://docs.unrealengine.com/latest/INT/API/Runtime/Core/Containers/TArray/RemoveAtSwap/index.html

I think it could be helpful to introduce the following extension methods:

```C#
class ListExtensions {
     public void RemoveAtUnordered(this List<T> list, int index);
     public void RemoveUnordered(this List<T> list, T element);
     public void RemoveAllUnordered(this List<T> list, Predicate<T> match);
     public void RemoveRangeUnordered(this List<T> list, int index, int count);
}
```
Implementing them as extension methods prevents code bloat as lists are instantiated quite often.

The naming uses Unordered instead of Swap because I think it communicates the difference vs a normal remove more clearly. 

**Benchmarks**

List of N items. 10% of items are removed at random indices. The Small value type is 16 bytes. The large value type is 64 bytes.

**RemoveAt**, Best case scenario if you know the index beforehand:

``` ini

BenchmarkDotNet=v0.10.9, OS=Windows 10 Redstone 2 (10.0.15063)
Processor=Intel Core i7-4790K CPU 4.00GHz (Haswell), ProcessorCount=8
Frequency=3906249 Hz, Resolution=256.0001 ns, Timer=TSC
.NET Core SDK=2.0.0
  [Host]     : .NET Core 2.0.0 (Framework 4.6.00001.0), 64bit RyuJIT
  Job-UOEMAQ : .NET Core 2.0.0 (Framework 4.6.00001.0), 64bit RyuJIT

InvocationCount=1  LaunchCount=1  TargetCount=100  
UnrollFactor=1  WarmupCount=10  

```
 |                      Method |     N |           Mean |           Error |          StdDev |         Median |
 |---------------------------- |------ |---------------:|----------------:|----------------:|---------------:|
 |                 **RemoveAtRef** |   **100** |       **829.4 ns** |      **44.3143 ns** |     **130.6616 ns** |       **729.6 ns** |
 |        RemoveAtUnorderedRef |   100 |       384.0 ns |       0.0000 ns |       0.0000 ns |       384.0 ns |
 |          RemoveAtValueSmall |   100 |       691.2 ns |       0.0000 ns |       0.0000 ns |       691.2 ns |
 | RemoveAtUnorderedValueSmall |   100 |       303.3 ns |      43.8459 ns |     128.5923 ns |       179.2 ns |
 |          RemoveAtValueLarge |   100 |       861.3 ns |      50.4064 ns |     147.0378 ns |       934.4 ns |
 | RemoveAtUnorderedValueLarge |   100 |       362.5 ns |      44.4507 ns |     130.3661 ns |       460.8 ns |
 |                 **RemoveAtRef** |  **1000** |    **11,229.1 ns** |     **234.9079 ns** |     **650.9286 ns** |    **11,174.4 ns** |
 |        RemoveAtUnorderedRef |  1000 |     1,577.6 ns |      46.0818 ns |     132.9567 ns |     1,689.6 ns |
 |          RemoveAtValueSmall |  1000 |    12,644.7 ns |     287.8187 ns |     811.7978 ns |    12,569.6 ns |
 | RemoveAtUnorderedValueSmall |  1000 |     1,484.8 ns |       0.0000 ns |       0.0000 ns |     1,484.8 ns |
 |          RemoveAtValueLarge |  1000 |    68,777.9 ns |   1,617.6589 ns |   4,693.1217 ns |    69,004.8 ns |
 | RemoveAtUnorderedValueLarge |  1000 |     1,984.0 ns |       0.0000 ns |       0.0000 ns |     1,984.0 ns |
 |                 **RemoveAtRef** | **10000** |   **971,682.6 ns** |  **14,307.3651 ns** |  **41,050.5125 ns** |   **964,288.3 ns** |
 |        RemoveAtUnorderedRef | 10000 |    13,795.2 ns |      84.2591 ns |     230.6580 ns |    13,721.6 ns |
 |          RemoveAtValueSmall | 10000 | 1,888,886.2 ns |  25,194.7093 ns |  71,473.1969 ns | 1,880,000.5 ns |
 | RemoveAtUnorderedValueSmall | 10000 |    13,050.1 ns |      72.3786 ns |     205.3259 ns |    13,171.2 ns |
 |          RemoveAtValueLarge | 10000 | 9,647,115.0 ns | 126,638.1818 ns | 371,407.8652 ns | 9,617,845.7 ns |
 | RemoveAtUnorderedValueLarge | 10000 |    16,399.6 ns |      95.6210 ns |     266.5530 ns |    16,268.8 ns |

**Remove**, first finding the item:

 |                      Method |     N |           Mean |         Error |        StdDev |         Median |
 |---------------------------- |------ |---------------:|--------------:|--------------:|---------------:|
 |                 **RemoveRef** |   **100** |       **2.801 us** |     **0.1060 us** |     **0.3040 us** |       **2.701 us** |
 |        RemoveUnorderedRef |   100 |       2.390 us |     0.1167 us |     0.3366 us |       2.483 us |
 |          RemoveValueSmall |   100 |      12.682 us |     0.8923 us |     2.6170 us |      11.917 us |
 | RemoveUnorderedValueSmall |   100 |      13.222 us |     0.9460 us |     2.7293 us |      12.326 us |
 |          RemoveValueLarge |   100 |      14.382 us |     0.9318 us |     2.6584 us |      13.952 us |
 | RemoveUnorderedValueLarge |   100 |      13.580 us |     0.8255 us |     2.3419 us |      13.517 us |
 |                 **RemoveRef** |  **1000** |     **179.429 us** |     **4.7003 us** |    **12.9459 us** |     **177.715 us** |
 |        RemoveUnorderedRef |  1000 |     164.773 us |     3.1782 us |     9.0675 us |     163.814 us |
 |          RemoveValueSmall |  1000 |   1,116.633 us |    32.5813 us |    94.5243 us |   1,106.842 us |
 | RemoveUnorderedValueSmall |  1000 |   1,167.612 us |    30.4712 us |    87.9164 us |   1,163.559 us |
 |          RemoveValueLarge |  1000 |   1,441.630 us |    43.5135 us |   124.8483 us |   1,426.906 us |
 | RemoveUnorderedValueLarge |  1000 |   1,320.419 us |    35.7561 us |   103.1646 us |   1,309.952 us |
 |                 **RemoveRef** | **10000** |  **17,427.345 us** |   **145.7787 us** |   **425.2433 us** |  **17,418.411 us** |
 |        RemoveUnorderedRef | 10000 |  16,445.359 us |   173.2089 us |   502.5103 us |  16,380.599 us |
 |          RemoveValueSmall | 10000 | 108,541.970 us |   644.3526 us | 1,848.7683 us | 108,544.937 us |
 | RemoveUnorderedValueSmall | 10000 | 114,086.368 us |   752.6536 us | 2,171.5778 us | 114,107.856 us |
 |          RemoveValueLarge | 10000 | 137,065.974 us | 1,006.2662 us | 2,951.2045 us | 136,833.469 us |
 | RemoveUnorderedValueLarge | 10000 | 128,156.691 us | 1,053.0958 us | 3,071.9300 us | 128,141.114 us |

**RemoveAll** Here on average 5 random items match the predicate:

 |                       Method |     N |        Mean |         Error |        StdDev |      Median |
 |----------------------------- |------ |------------:|--------------:|--------------:|------------:|
 |                 **RemoveAllRef** |   **100** |    **704.0 ns** |     **0.0000 ns** |     **0.0000 ns** |    **704.0 ns** |
 |        RemoveAllUnorderedRef |   100 |    550.4 ns |    43.4116 ns |   128.0000 ns |    460.8 ns |
 |          RemoveAllValueSmall |   100 |    517.1 ns |    60.6822 ns |   178.9227 ns |    409.6 ns |
 | RemoveAllUnorderedValueSmall |   100 |    422.4 ns |     0.0000 ns |     0.0000 ns |    422.4 ns |
 |          RemoveAllValueLarge |   100 |    620.4 ns |    48.4392 ns |   141.2994 ns |    704.0 ns |
 | RemoveAllUnorderedValueLarge |   100 |    537.6 ns |    45.1315 ns |   133.0713 ns |    652.8 ns |
 |                 **RemoveAllRef** |  **1000** |  **4,515.6 ns** |   **148.7692 ns** |   **417.1648 ns** |  **4,518.4 ns** |
 |        RemoveAllUnorderedRef |  1000 |  2,432.0 ns |     0.0000 ns |     0.0000 ns |  2,432.0 ns |
 |          RemoveAllValueSmall |  1000 |  3,112.5 ns |    66.8587 ns |   193.9693 ns |  3,212.8 ns |
 | RemoveAllUnorderedValueSmall |  1000 |  2,562.7 ns |    39.1437 ns |   112.9384 ns |  2,496.0 ns |
 |          RemoveAllValueLarge |  1000 |  5,377.5 ns |   133.9996 ns |   364.5558 ns |  5,312.0 ns |
 | RemoveAllUnorderedValueLarge |  1000 |  4,181.6 ns |    49.1519 ns |   141.0259 ns |  4,262.4 ns |
 |                 **RemoveAllRef** | **10000** | **43,763.8 ns** | **1,835.5378 ns** | **4,931.0531 ns** | **44,416.0 ns** |
 |        RemoveAllUnorderedRef | 10000 | 21,523.3 ns |   111.9587 ns |   306.4852 ns | 21,414.4 ns |
 |          RemoveAllValueSmall | 10000 | 42,740.4 ns | 2,502.4247 ns | 7,098.9625 ns | 40,601.6 ns |
 | RemoveAllUnorderedValueSmall | 10000 | 24,007.6 ns |   243.4599 ns |   674.6261 ns | 23,961.6 ns |
 |          RemoveAllValueLarge | 10000 | 52,489.9 ns | 2,107.8894 ns | 5,805.7396 ns | 52,364.8 ns |
 | RemoveAllUnorderedValueLarge | 10000 | 38,643.8 ns |   777.8369 ns | 2,116.1625 ns | 37,798.4 ns |

Few observations:
-If you know the index beforehand, it's O(n) vs O(n^2) so the results are quite dramatic. The larger the stored item the worse the extra memory copy becomes.
-RemoveUnordered on ref types is at best ~10% faster than Remove. Do note however that the worst case is hit if the items are added FIFO - as they would be in a common use case in Unity. If they are, the benchmarks look quite similair to the RemoveAt benchmark. An unordered remove guarantees performance is consistent.
-RemoveAllUnordered is 10-50% faster in these benchmarks.

Project used to generate these benchmarks:
[NetCoreDev.zip](https://github.com/dotnet/corefx/files/1356989/NetCoreDev.zip)

**Current Workarounds:**
Projects use their own extension methods/static helpers to implement this on List<T>

**Discussion:** 
For non high-performance applications having two slightly different ways to remove elements is confusing, and it is not great to have these additional methods show up in intellisense. 

It could be argued List<T> is just an inherently ordered data type and for unordered data some other structure should be used. The problem is that many other API's want you to pass in a List<T>.

**Comment by danmosemsft** [comment]
If we implement this, since the implementation can be efficiently implemented as an extension method, we might want to do that instead of growing List<T> itself, for code bloat reasons as List<T> code is instantiated quite a few times typically. Similar to our arguments for recent Dictionary<K,V> additions: those that need not access private state to be efficient, we made extensions.

**Comment by jnm2** [comment]
I'm skeptical that this is a general enough need to be in everyone's intellisense. We all maintain those extensions methods we always use and they wouldn't necessarily be relevant to the average application.

**Comment by Clockwork-Muse** [comment]
> Each Remove has to move over the backing array - meaning O(n^2) deregistration.

Except, unless `Remove` was implemented completely braindead, it's O(n) (where at some n it switched from reads to a bulk copy of the remainder of the list, via `Array.Copy`).

> A common way to adress this is to do the remove with a swap back:
> ```
> void OnCreate() { All.Add(this); } 
>
> void OnDestroy() { 
>     int index = All.IndexOf(this);
>     All[index] = All[All.Count - 1];
>     All.RemoveAt(All.Count - 1);
> }
> ```

Except you're using `IndexOf`, which is _also_ O(n).  So you're optimizing on the amount of data moved, nothing else.

For small arrays/types, especially anything that would fit in cache, my ignorant intuition says I don't expect the performance to be a huge gain.  For large types, any of which would be classes, and thus reference types, I'd be curious about what happens during access to heap space; what would be stored in the array would be a pointer, and while objects _might_ have been originally allocated in a linear block (depending on how they were created/added, though- c++ has better control here, obviously), the reordering of the array would make heap access be random....

**Comment by danmosemsft** [comment]
Some performance measurements would be interesting @ArthurBrussee -- eg with Benchmark.NET and various sized lists, with reference type and with small/large structs maybe etc.

**Comment by ArthurBrussee** [comment]
Thanks for the comments

@danmosemsft Makes sense! I have adjusted the proposal to address this.

@jnm2 Fair enough. As a resharper user my intellisense List<> is already miles long with all Linq extensions. I guess if these are extension methods in a namespace this could be resolved. I don't think there is any precedent for these type of extension methods though so not sure where this would go however.

@Clockwork-Muse Fair points, and I shouldn't make performance claims without measurements. I have attached BenchmarkDotNet results below. It's O(n^2) in the sense that n objects deregister, each deregister being O(n). You're right index of is O(n) too and I definitely made some mistakes in my post while trying to oversimplify the examples of where I encounter this in the wild. I also hoped that IndexOf would be much faster than having to actually copy around the array, but from the benchmarks it seems this extra copy barely matters vs the already linear iteration.

**Comment by Clockwork-Muse** [comment]
>It's O(n^2) in the sense that n objects deregister, each deregister being O(n). 
.... sure, but `IndexOf()` is going to cause the same problem.  If you have n objects to deregister, you still have n objects to find.  Best case requires you to know the index ahead of time, but still has to fallback on the search.

A big gain would be if you remove multiple different objects, since then way fewer moves happen, but you can probably get around that somewhat by using `RemoveAll`

Speaking of `RemoveAll`, I'm curious if the performance could be increased by switching to `Array.Copy` - it looks like the reference source has it copying each item individually, which for sparse finds is going to be a big drain, as opposed to block shifting between removed items.

**Comment by danmosemsft** [comment]
Those are encouraging results. @safern, @ianhays own collections and one of them will take a look in due course.

**Comment by danmosemsft** [comment]
@ianhays or @safern could one of you please give feedback.

**Comment by Clockwork-Muse** [comment]
Having thought about this a little more, I'm wondering if perhaps a non-ordered collection is a better fit; one of the major operations is mutating the order of the items in (what kinda looks like) a non-deterministic fashion.  In contrast to `List`, which (besides implying "retains insertion order") has a property of "the existing order is maintained".  A non-concurrent `Bag`, I guess?

**Comment by svick** [comment]
How is `RemoveAtUnordered` supposed to be used? You can't for example remember the position an item was inserted at, because that item could have been moved by some other `Remove*Unordered` in the meantime. So, probably the only safe way is using `IndexOf` and following that immediately by `RemoveAtUnordered`. But at that point, it's almost the same as `RemoveUnordered`.

**Comment by ArthurBrussee** [comment]
@Clockwork-Muse I think that definitely makes sense conceptually . I am a little concerned however that existing API's will not easily take a bag in though - passing by eg IList is not that common (in the Unity world at least). Converting a Bag to a list would defeat the performance improvments. The implementations would be almost identical, take these Remove functions. 

@svick Fair point. I think the main use case would be to use it when removing items in a reverse for loop. Lots of those cases are probably also (better?) covered by RemoveAll, but the reverse for is a somewhat common pattern in game development.

**Comment by safern** [comment]
@ianhays and I think that it is too specific to add it to .NET Core and that it would actually confuse people more than help them. Since this could be added as an extension method we think it is not worth adding this "very specific" to one scenario API.

**Comment by stephentoub** [comment]
Closing per discussion above. Thanks.
