### ISSUE TITLE
Process.Start() fails when a directory exists in the working directory with the same name as the executable

### ISSUE THREAD

**Issue by livarcocc** [dotnet/corefx#24402]
_From @ahsonkhan on September 29, 2017 2:48_

## Steps to reproduce
1. Clone corefxlab repo https://github.com/dotnet/corefxlab
2. Run ./build.sh
3. Observe failure to restore pacakges (only on OSX and Ubuntu, package restore works fine on Windows).

From:
https://github.com/dotnet/corefxlab/pull/1787 https://ci.dot.net/job/dotnet_corefxlab/job/master/job/ubuntu16.04_release_prtest/807/consoleFull#7440085258bb52e59-de52-4f1c-b131-470db4c594cd

```bash
echo "Restoring all packages"
  ./$dotnetExePath restore $myFile /p:VersionSuffix="$BuildVersion"
  ret=$?
  if [ $ret -ne 0 ]; then
    echo "Failed to restore packages."
    exit -1
  fi
```

## Expected  behavior
Package restore succeeds on all configurations.

Previous CLI version (2.1.0-preview1-007191) was working as expected.

## Actual behavior
Package restore failing with System.ComponentModel.Win32Exception.

18:50:13 System.ComponentModel.Win32Exception (0x80004005): The FileName property should not be a directory unless UseShellExecute is set.
18:50:13    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
18:50:13    at System.Diagnostics.Process.Start()
18:50:13    at Microsoft.DotNet.Cli.Utils.ProcessStartInfoExtensions.Execute(ProcessStartInfo startInfo)
18:50:13    at Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingApp.Execute()
18:50:13    at Microsoft.DotNet.Tools.Restore.RestoreCommand.Run(String[] args)
18:50:13    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
18:50:13    at Microsoft.DotNet.Cli.Program.Main(String[] args)
18:50:13 

## Environment data
dotnet cli version 2.1.0-preview1-007228

_Copied from original issue: dotnet/cli#7726_

**Comment by livarcocc** [comment]
@steveharter @stephentoub can you guys take a look?

**Comment by livarcocc** [comment]
This is a regression for sure, but it happens because you have you have your toolset under a folder called dotnet. I haven't narrowed down why yet, but if I moved the dotnet folder to dt and execute dt/dotnet restore it works. I will investigate and figure out why, but maybe this will work for you as a workaround.

**Comment by livarcocc** [comment]
Ok, I actually know what is going... when we shell out to execute dotnet msbuild and do the restore (or most of our other operations as well), we just shell out to dotnet from the location where the command is being run. It just so happens that when you invoke dotnet (without typing the full path), there will be a folder called dotnet there and the shell will believe you are invoking the folder and not the command in the path. Next I will investigate where we have regressed that.

**Comment by livarcocc** [comment]
All right, this seems to be a regression in corefx. This started happening once we updated the runtime version in the CLI to preview1-25719-04. I will move this folder to corefx.

**Comment by stephentoub** [comment]
I expect this was introduced by https://github.com/dotnet/corefx/pull/23705 or the related changes.
cc: @maryamariyan, @danmosemsft

**Comment by danmosemsft** [comment]
Thanks for investigation. @maryamariyan please put aside ODBC for the moment and fix this.

**Comment by maryamariyan** [comment]
as @livarcocc mentioned earlier, this happens when we update the runtime version in the CLI to include my fix for: https://github.com/dotnet/corefx/issues/22299 
The reason for added this fix was to ensure we provide error message when Process.Start using UnixShellExecute takes directory as input.

as @livarcocc  explained to me:
- dotnet gets invoked like this: dotnet/dotnet restore 
- behind the scenes, the CLI itself will create a StartInfo with dotnet as the filename and msbuild /t:Restore as the arguments and it will Process.Execute that 
at that point, it will fail, because the current working directory will be the git root, with a dotnet folder in it and it will confuse the executable, that exists in the path, with the folder

**Comment by maryamariyan** [comment]
@joperezr  explained to me that in corefx this doesnt happen because in the corefx repo the folder is called 'dotnetcli' not dotnet.

- in corefx: Tools\dotnetcli\dotnet
- in corefxlab: dotnet\dotnet

**Comment by ahsonkhan** [comment]
> Iin corefx this doesnt happen because in the corefx repo the folder is called 'dotnetcli' not dotnet.

Renaming the folder does not resolve the issue. I still see restore failure error on Ubuntu and OSX:
https://github.com/dotnet/corefxlab/pull/1826
https://ci.dot.net/job/dotnet_corefxlab/job/master/job/osx10.12_release_prtest/833/consoleFull#7440085258bb52e59-de52-4f1c-b131-470db4c594cd

**Comment by maryamariyan** [comment]
@ahsonkhan I meant you could rename the dotnet folder, not the dotnet shell script name.

Also note, I'm putting up a PR in a bit that should fix this.

**Comment by ahsonkhan** [comment]
> I meant you could rename the dotnet folder to dotnetcli (as a temporary workaround), not the dotnet shell script name.

That is what I have done in this [PR](https://github.com/dotnet/corefxlab/pull/1826/files). I changed the dotnet folder to dotnetcli.
