### ISSUE TITLE
Bring back exception serialization support

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#24424]
We see strong customer demand for being able to serialize Exceptions with BinaryFormatter or DCS.

The following actions are required:
- [x] Make coreclr exception types serializable, add typeforwards and bring back serialization implementation (https://github.com/dotnet/coreclr/pull/14311)
- [x] Mirror in corert
- [x] Make corefx exception types serializable, add typeforwards and bring back serialization implementation (https://github.com/dotnet/corefx/pull/24427)
- [x] Add typeforwards for internal types (https://github.com/dotnet/corefx/pull/24427)
- [x] Add tests in System.Runtime.Serialization.Formatters.Tests
- [x] Port to release branches
- [x] Update docs

cc @jkotas @stephentoub @danmosemsft

**Comment by 4creators** [comment]
With which framework will this change be shipped?

**Comment by danmosemsft** [comment]
@4creators definitely in 2.1. We are exploring the possibility of servicing 2.0 for it. Generally we don't service for "features" but this is necessary for some customers to port successfully. Do you need it?

**Comment by 4creators** [comment]
Yeah, unfortunately I need it for all custom exceptions I use in every library I work on 😒

**Comment by danmosemsft** [comment]
@4creators custom exceptions in general should be serializable already, as in 2.0 we made Exception do all necessary work to serialize. They just need to call the base. The problem is other exceptions we ship.

**Comment by 4creators** [comment]
@danmosemsft My implementation pattern for throwing exceptions is to derive from every framework exception I want to throw my own exception i.e. CustomInvalidOperationException etc. Therefore Exception is not enough and I can not derive from Exception either as this would be braking change for error handling code where I do it seperatly for my CustomInvalidOperationException and framework InvalidOperationException.

**Comment by danmosemsft** [comment]
Got it.
