### ISSUE TITLE
[Cookie] WinRT WebSocket ignores Set-Cookie header in handshake response

### ISSUE THREAD

**Issue by aka-STInG** [dotnet/corefx#24420]
The issues affects UWP implementation of `ClientWebSocket`.
Cookie is set in request, but never read from response.
So calling `clientWebSocket.Options.Cookies.GetCookieHeader(uri)` return empty string regardless of Set-Cookie header present in handshake response.

**Comment by davidsh** [comment]
ClientWebSocketOptions is not fully implemented.

Essentially a duplicate of #5120.

**Comment by davidsh** [comment]
>Cookie is set in request, but never read from response.
So calling clientWebSocket.Options.Cookies.GetCookieHeader(uri) return empty string regardless of Set-Cookie header present in handshake response.

Also, when you say this 

"Cookie is set in request, but never read from response.", 

I think you really mean this: 

"A Set-Cookie header is received in the HTTP response headers but is not stored in the cookie container for the clientwebsocket. Hence, it is not returned back in subsequent requests" ?

**Comment by aka-STInG** [comment]
Yes, plus another related issue is there is no way to reset cookie via `clientWebSocket.Options.Cookies`.
I mean once it is set in response Set-Cookie header, consequent requests will have this cookie present even if you call `clientWebSocket.Options.Cookies.SetCookies(uri, string.Empty)`

**Comment by caesar1995** [comment]
The managed ClientWebSocket implementation now provides support for all of ClientWebSocketOptions #24288.

@aka-STInG Could you please confirm the problem still exist?

**Comment by caesar1995** [comment]
At some point in the future that we may change to use ManagedWebSocket for UWP apps, instead of WinRT WebSocket.

@aka-STInG Does ManagedWebSocket has the same issues?

**Comment by caesar1995** [comment]
Opened #29644 to track changing to use ManagedWebSocket for UWP.

Closing this issue.
