### ISSUE TITLE
Current Regex cache structure is ineffecient and inflexible

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#24425]
For larger cache lanes the current Cache structure isn't optimized as its operates with O(n). We see internal demand to optimize the current structure to me more flexible for both - small and large cache length - cases.

Furthermore the current cache stores only parts of the instantiated Regex object. There might be some value in investigating if whole Regex objects can be stored in it to reduce GC pressure when using static Regex methods in a loop. The timeout instance field could be problematic as it does not change the Regex Tree but is stored in the instance --> reusing.

cc @vancem @danmosemsft

**Comment by artkpv** [comment]
@ViktorHofer  
Regarding the first part. Do I understand it right? We need to keep the cache in the way that more frequently retrieved items stay there longer. And the constructor can be called many times. And we need to get cache quickly. So, imho, adding a hash table to get an item and then move it at first place in `s_livecode` should suit. (Using only hash table doesn't give us what item to remove next; heap works slower.) And then the removal (cache resized or no place) by getting last in `s_livecode`.
Also it needs a performance test ([using this](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/benchmarking.md)).

**Comment by artkpv** [comment]
Here is the test I'm thinking to optimize:
```
    public class RegexCtorPerfTests
    {
        private const int N = 1000;
        private string[] _regexs;
        private string _input;

        public RegexCtorPerfTests()
        {
            _regexs = new string[N];
            // regexs: "(0+)", "(1+)", .., "(1+)(0+)(0+)", .., "(9+)(9+)(8+)", ..
            for (int i = 0; i < N; i++)
                _regexs[i] = i.ToString().Select(c => "(" + c + "+)").Aggregate((s1, s2) => s1 + s2);

            _input = "0123456789";
        }

        [Benchmark]
        public void IsMatch_PerfTest()
        {
            foreach (var re in _regexs)
                Regex.IsMatch(_input, re);
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var summary = BenchmarkRunner.Run<RegexCtorPerfTests>();
        }
    }
```
Runs in 7.258ms, mean time.

**Comment by ViktorHofer** [comment]
That benchmark should be good enough. I would increase N to 100k. If I'm counting right, IsMatch would return 6 times true right now (not relevant for the benchmark).

Cache needs to be:
- resizable via Regex.CacheSize
- fast for frequently used regexes (pattern + options + timeout)
- small memory footprint (I don't see a hashtable or dictionary here)
- thread safe

**Comment by ViktorHofer** [comment]
Giving it a second thought it seems your benchmark doesn't test the cache at all. The default size of the cache is 15. You are creating N (1000) different regex patterns and iterate over them. That means the cache will also miss and never hit as the pattern isn't already in the cache.

I would suggest the following parameters to test the cache:

NC = size of Cache => 15
NPU = number of unique regex patterns => NC * 2
NPT = number of total regex patterns => NPU * 1000 (clone existing patterns and shuffle them)

Also make sure to attribute the benchmark class with the MemoryDiagnoserAttribute to also get the allocation size.

**Comment by artkpv** [comment]
@ViktorHofer Thanks for answers!

About the test. Yes, it is not full, I'm changing the cache size, adding duplicates and shuffling. Also I guess we need to test on large cache size. Making it N =100k, the cache size and unique regexes - 2% of N. Not sure about real world scenario for this, probably parsing some text file.

> small memory footprint (I don't see a hashtable or dictionary here)

What does it mean? I guess it's `Dictionary` and `Hashtable`. But hash table would be the quickest way to get an entry along with the linked list for the frequency. That puzzles me. We can do O(log N) with some tree (self-balancing BST) then, but that is not the quickest way. Sure it would be less size.

**Comment by ViktorHofer** [comment]
> Not sure about real world scenario for this, probably parsing some text file.

Not important for the perf test :) I will comment on the memory footprint question later. If you want you can submit the perf test as a PR similar to what Dan did here: https://github.com/dotnet/corefx/pull/26827

**Comment by artkpv** [comment]
@ViktorHofer Yes, i'm making the pull request after i overcome two problems. Couldn't run tests with my local build (BDN throws that regex dlls are not in Release). Following [this](https://github.com/dotnet/corefx/blob/14bf87805112c53d08eac5a0b03309bbe027cdc0/Documentation/project-docs/benchmarking.md#benchmarking-net-core-20--21-applications) and [that](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md#advanced-scenario---using-a-nightly-build-of-microsoftnetcoreapp). And second, is i couldn't run perf. tests from CoreFx (the one of Dan #26827 ).

**Comment by ViktorHofer** [comment]
> BDN throws that regex dlls are not in Release

Make sure that you build corefx in Release mode `.\build -release` and to point to it in the Nuget.Config file as described in the second link.

**Comment by danmosemsft** [comment]
@artkpv when I ran that test I ran [these instructions](https://github.com/dotnet/corefx/blob/14bf87805112c53d08eac5a0b03309bbe027cdc0/Documentation/project-docs/performance-tests.md)

**Comment by danmosemsft** [comment]
Also worth considering: API to get cache hit stats. It would be easy and cheap to maintain such stats - depending on the design of the cache, I suppose.

**Comment by artkpv** [comment]
@ViktorHofer Here is some perf test. It outputs locally:
```
 System.Text.RegularExpressions.Performance.Tests.dll          | Metric         | Unit  | Iterations |    Average |   STDEV.S |        Min |        Max
  :------------------------------------------------------------- |:-------------- |:-----:|:----------:| ----------:| ---------:| ----------:| ----------:
   System.Text.RegularExpressions.Tests.Perf_Regex_Cache.IsMatch | Duration       | msec  |     24     |    419.967 |     6.694 |    412.504 |    438.813
   System.Text.RegularExpressions.Tests.Perf_Regex_Cache.IsMatch | GC Allocations | bytes |     24     | 5.247E+006 | 40842.570 | 5.157E+006 | 5.265E+006
```

@danmosemsft Regarding hit stats. I guess this is to measure accuracy of a test?

**Comment by danmosemsft** [comment]
I figured hit stats would allow the user to dial up the cache until it gets acceptably few misses. It is not always practical to tune the cache with profiling.

**Comment by artkpv** [comment]
@danmosemsft  Didn't understand all. User would change CacheSize based on the stats? Yes, adding API only for profiling doesn't seem practical to me.

Next, i'm going to optimize the cache with this test. Measure memory allocation. Try `Dictionary` first, etc.
