### ISSUE TITLE
Rename MemoryHandle.PinnedPointer to Pointer

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefx#24426]

**Comment by karelz** [comment]
Discussed originally here: https://github.com/dotnet/corefx/issues/23974#issuecomment-333943725

**Comment by terrajobst** [comment]
Looks good as proposed.

**Comment by karelz** [comment]
FYI: The API review discussion was recorded - see https://youtu.be/BEBq3__WfDc?t=856 (4 min duration)
