### ISSUE TITLE
Current CancellationToken?

### ISSUE THREAD

**Issue by n9** [dotnet/corefx#24447]
What about to add sort of "CancellationToken.Current" which would pass token automatically? In case of [the passed point of no cancellation](https://blogs.msdn.microsoft.com/andrewarnottms/2014/03/19/recommended-patterns-for-cancellationtoken/), CancellationToken will be set to "CancellationDenied". So that developers do not have to pass it manually.

(Maybe the question has been already answered somewhere, however I am unable to find it.)

**Comment by karelz** [comment]
cc @stephentoub

**Comment by stephentoub** [comment]
This would add non-trivial expense, as we'd need to the flow the token across async points and also do extra TLS lookups. It would be a breaking change, as methods that had explicitly decided not to be cancelable would start to be. It would be ambiguous if there were multiple tokens in play. Etc.

**Comment by aluanhaddad** [comment]
Seems like something that would warrant discussion at the programming language level as well. It sounds rather like Scala's implicits, a vaguely first-class notion of ambient context.
