### ISSUE TITLE
ArraySegment null check is throwing ArgumentNullException

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#24441]
@serkantkaraca reported this issue here: https://github.com/dotnet/core/issues/994

SDK 2.0 breaks null check on type value contract for ArraySegment.

            var arraySegment = new ArraySegment<byte>(new byte[10]);

            // This throws as below. Should be False as per C# spec. Works on 4.6.2
            var isNull = arraySegment == null;

System.ArgumentNullException occurred
  HResult=0x80004003
  Message=Value cannot be null.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.ArraySegment`1.op_Implicit(T[] array)
   at ConsoleApp.Program.Main(String[] args) in

**Comment by stephentoub** [comment]
https://github.com/dotnet/coreclr/issues/14012

**Comment by danmosemsft** [comment]
dupe
