### ISSUE TITLE
Add Dictionary<TKey, TValue>.Capacity to let you resize map after created

### ISSUE THREAD

**Issue by davkean** [dotnet/corefx#24445]
[edited by @danmosemsft to put into review format]

## Latest Proposal

See https://github.com/dotnet/corefx/issues/24445#issuecomment-352869027

```c#
    public partial class Dictionary<TKey, TValue> :  ...
    {
           // Makes sure that capacity is at least that capacity, ie, the dictionary can accept this many items without resizing its internal data structures
           public void EnsureCapacity(int capacity);
           public void TrimExcess(); // Calls the other passing Count
           public void TrimExcess(int capacity);
    }
```

## Issue 
While I can set the initial capability of a dictionary when it's created, I cannot resize it after it's created.  Please add `Dictionary<TKey, TValue>.Capacity` property or an `EnsureCapacity` method so that that you can.

## Rationale
MSBuild, are resizing multiple times during Add that they cannot avoid without recreating the dictionary: https://github.com/Microsoft/msbuild/issues/2587. 
Another case came up in an Azure service profile today, where a dictionary was being copied into another dictionary which had already been constructed and resize CPU and allocation cost was high.

## Proposal (old)
```c#
    public partial class Dictionary<TKey, TValue> :  ...
    {
        public Dictionary(int capacity) { }   // existing constructor 
        public int Capacity { get { } set { } }
    }
```
The name `Capacity` is chosen to match the parameter name of the existing constructor.  

Setting Capacity to `value` causes the Dictionary to ensure it can have up to `value` elements without resizing. Behind the scenes if `value` is less than the existing capacity it calls Resize to increase the backing storage to the smallest Prime that is not less than the requested `value`.

The getter is probably not terribly useful (debugging?) but a setter without a getter is strange.

## Discussion
Implementation of this looks like it will be straightforward, not significantly increase the instantiated size of Dictionary's, and not affect code paths that do not call it. The resizing codepath obviously already exists, although right now it is never given a desired size: it starts with doubling.

**Comment by davkean** [comment]
Note, even recreating the dictionary isn't an exact science - we don't know whether the dictionary is going to resize on add because the current capability isn't exposed.

**Comment by ianhays** [comment]
Similar to https://github.com/dotnet/corefx/issues/23954.

**Comment by danmosemsft** [comment]
@davkean do you always want to increase? or ever want to trim?

**Comment by davkean** [comment]
I can see cases where we might want to trim for long lived dictionaries that end up becoming read-only, but for the most part we only wanted increases only.

**Comment by jnm2** [comment]
I have a couple use cases for trimming to create a long-lived read-only master copy which is repeatedly cloned so that items can be removed.

**Comment by danmosemsft** [comment]
Updated to review format.

**Comment by benaadams** [comment]
The setter would be very expensive if the dictionary contains items; as it will have to move everything

**Comment by benaadams** [comment]
The setter would be very expensive if the dictionary contains items; as it will have to move everything - use the hashes to work out positions; move on collisions etc

**Comment by terrajobst** [comment]
We don't want to store the capacity as it makes serialization harder. Also, changing the capacity is likely an expensive operation (as it requires rehashing).

Instead, we would like an API like this:


```csharp
public partial class Dictionary<TKey, TValue>
{
    // Already exists
    public Dictionary(int capacity) { }
    // New API
    public void Resize(int capacity);
}
```

`Resize` will allow growing and shrinking the underlying array but it would throw if `capacity < Count`.

**Comment by benaadams** [comment]
```csharp
public partial class Dictionary<TKey, TValue>
{
    public void Resize(int capacity);
    public int Capacity { get };
}
```

**Comment by danmosemsft** [comment]
The word Size to me suggests the number of items in the collection, rather than how many it can hold (Capacity). So I wonder if Resize is the best word? Maybe GrowCapacity?

**Comment by benaadams** [comment]
Capacity is real size of underlying capacity not Resize value. If you add items, it will then resize and it will change anyway.

However you probably don't want to be running at 100% capacity anyway as perf will be bad... :-/

**Comment by terrajobst** [comment]
Looks like the API needs more discussion.

**Comment by karelz** [comment]
FYI: The API review discussion was recorded - see https://youtu.be/BI3iXFT8H7E?t=1745 (28 min duration)

**Comment by karelz** [comment]
@danmosemsft The API is supposed to also shrink the capacity. Do you have alternative name for `Resize`? Maybe the argument name could be sufficient specification?

@davkean would the shortly-approved https://github.com/dotnet/corefx/issues/24445#issuecomment-349403320 API fit your needs? (i.e. no `Capacity` exposed - you mentioned it is ok, just double checking)

**Comment by davkean** [comment]
I would consider calling it EnsureCapacity - this will tackle the prime number issue (where the capacity is actually the next next prime number above the capacity).

**Comment by davkean** [comment]
StringBuilder calls it that: https://msdn.microsoft.com/en-us/library/system.text.stringbuilder.ensurecapacity(v=vs.110).aspx.

**Comment by karelz** [comment]
The key argument against `EnsureCapacity` was that it leads you to believe it can only grow, and won't shrink (which is the key purpose of the API).

**Comment by davkean** [comment]
``` C#
// Trims the capacity to at/or next prime number above Size (List<T> calls it TrimExcess, ArrayList calls it TrimToSize()
public void TrimToSize()/TrimExcess();

// Makes sure that capacity is at least that capacity or next prime number
public void EnsureCapacity(int capacity);
```

Then you never need to expose the capacity - and the problem that it doesn't actually represent the capacity you set.

**Comment by davkean** [comment]
The key purpose was of the API, at least when I filed it, was to increase the size - not trim it. You only want to trim it when you know that you are done adding items at which point, you just trim it to its current Count.

**Comment by danmosemsft** [comment]
> // Trims the capacity to at/or next prime number above Count (List<T> calls it TrimExcess, ArrayList calls it TrimToSize()

@davkean that would result in the absolute minimum size, but it could make the load factor excessive. If the capacity is only a little more than the count, there will be a lot of collisions, making lookup inefficient. You might instead want it to pick a prime that is, say, 20% larger than count (taking capacity possibly from 200% or arbitrarily larger than that, down to 120%). Or use the value you would get if you simply added all the items to a new dictionary without any removals. There is not an obvious "correct" amount to Trim. 

EnsureCapacity doesn't have this problem - it never increases the load factor. It seems uncontroversial. 

I suggest just adding EnsureCapacity at this point.

**Comment by davkean** [comment]
Fair enough, I have zero opinion on the "reducing the capacity" scenario.

**Comment by karelz** [comment]
My bad, I incorrectly remembered the scenario as mainly Trimming.

So what is the end-to-end scenario for growth?
You set initial capacity in constructor and then later on you need to add a batch of entries, so you call `dictionary.EnsureCapacity(dictionary.Count + newlyAddingCount)`? And then later maybe again.
Is that the pattern?

Just to clarify: It is NOT about scenario where you continuously add items (without knowing at any point how many there will be yet), observing that overall perf sucks. That would mean our growing algorithm is not good for the scenario and `EnsureCapacity` would be just an attempt to tweak and trick the inner Dictionary algorithm.

**Comment by danmosemsft** [comment]
@karelz correct, `dictionary.EnsureCapacity(dictionary.Count + newlyAddingCount)`

**Comment by davkean** [comment]
It's not about tricking the algorithm, it's about having more information than the dictionary about how many exactly items we're going to add immediately to prevent:

1) Prevent multiple resizes (traces show that we resize a significant amount of times in Add)
2) Prevent wasted space by adding too much capacity.

The pattern above is exactly the pattern that we would use.

**Comment by benaadams** [comment]
Seems reasonable to only increase; as Trimming will cause perf issues (increasing collisions and cost for finding new entry for everything)

```csharp
// Makes sure that capacity is at least that capacity or next prime number
public void EnsureCapacity(int capacity);
```

Perhaps additionally internalize the size calc?
```csharp
public void EnsureCapacity(int capacity, int loadFactorPercentage);
```

Combine the two; with default value to have low(ish) collisions?

```csharp
public void EnsureCapacity(int capacity, int loadFactorPercentage = 50);
```

**Comment by danmosemsft** [comment]
Trimming is not a bad idea per se (imagine a dictionary that grew huge and then had almost all its items removed, right know if you care about size you have to guess this happened, then copy into another dictionary) it's just hard to pick a policy...

I would rather not expose load factor as it constrains implementation. I don't think @davkean wants to have to pick a load factor. He just wants to give us a simple hint. We can choose what to do with that.

My vote is for
```c#
// Makes sure that capacity is at least that capacity, ie, the dictionary can accept this many items without resizing its internal data structures
public void EnsureCapacity(int capacity);
```

**Comment by benaadams** [comment]
Base on [current dictionary](https://github.com/dotnet/coreclr/blob/4865f600df7270fbda7d36af34424343f10caa7f/src/mscorlib/shared/System/Collections/Generic/Dictionary.cs#L498-L501) implementation would be?

```csharp
public void EnsureCapacity(int capacity)
{
    Resize(HashHelpers.GetPrime(min: capacity), false);
}
```

**Comment by danmosemsft** [comment]
@benaadams yes I think so; if the caller wanted to tell us that it would likely not get any further inserts, we could use a smaller capacity, but that would be a different feature not requested here (I think)

**Comment by benaadams** [comment]
That is the smallest :)

Otherwise you'd go for
```csharp
public void EnsureCapacity(int capacity)
{
    Resize(HashHelpers.ExpandPrime(min: capacity), false);
}
```
To bump it even if the capacity was a prime (and a little bit of loading slack)

**Comment by custarddog** [comment]
You're right, I misread.

**Comment by danmosemsft** [comment]
You're right, I misread.

**Comment by davkean** [comment]
@danmosemsft Yes that's what I would like.

**Comment by danmosemsft** [comment]
Hopefully this can get a quick OK from review then @maryamariyan can do it.

**Comment by terrajobst** [comment]
Alright, looking around it seems we want this API:

```csharp
public int EnsureCapacity(int capacity);
public void TrimExcess(); // Calls the other passing Count
public void TrimExcess(int capacity);
```

Notes:
* Ideally, we'd design this as a single API but the established APIs (`StringBuilder` `List<T>`, `HashSet<T>`) we think having separate APIs is more conistent. While @davkean cares mostly about growing, not supporting shrinking seems unnecessary dumb, especially it might end up being the very next ask due to perf work.
* `EnsureCapacity` returns the adjusted capacity, which might be larger than what was passed in.
* For bonus points, we should probably add `EnsureCapacity` to `HashSet<T>` and `SortedSet<T>`.

**Comment by karelz** [comment]
FYI: The API review discussion was recorded - see https://youtu.be/ZrT0uOsqQlI?t=4774 (30 min duration)

**Comment by benaadams** [comment]
Just watching review

`public int EnsureCapacity(int capacity)` is good

> supporting shrinking seems unnecessary dumb, especially it might end up being the very next ask due to perf work

`public void TrimExcess(int capacity)`

:worried: Not sure you'd be wanting to shrink for perf; it would be a very expensive and allocating call, re-allocating 90% of the dictionary:
1. Reallocate the `buckets` and `entries` arrays
2. Copy entires 1 by 1, defragging removed entry gaps (Resize[increase] just does array copy)
3. Clear the free list
4. Recalculate collision chains and with a high likelyhood of collisions (since it goes to 100% load). 

Dictionary has no concept of load factor (you are thinking `Hashtable`); Dictionary goes to 100% load before resizing.

`TrimExcess` would **only** have an effect on `Dictionary` after `Remove` has been called on 50% of its elements (as otherwise its already at right size).

For performance you'd likely want to create a much larger Dictionary for a lower collision rate; so it would be a perf trap to shrink :-/

Not sure I understand why you'd want to Trim for perf?

**Comment by benaadams** [comment]
Note: not saying `TrimExcess` isn't possible; just it may be a counter productive api - as people will likely call it if its there, but really they shouldn't as its outcome will usually be bad

**Comment by benaadams** [comment]
Suppose you could do
```csharp
dict.Clear();
dict.TrimExcess(256);
```
When you were pooling the Dict, but wanted no greater than a size of 256 carried forward (in-case run had dict of 100k items)

**Comment by danmosemsft** [comment]
I'm surprised TrimExcess came up again due to the issues we discussed earlier with agreeing on the algorithm/goals. I think the scenario is not perf but size. If you are holding a large dictionary that may have had most of the items removed (or many such smaller dictionaries) and you want to save memory. 

As a straw man what about making TrimExcess equivalent to newing up a new Dictionary passing in the size of the current dictionary -- or the explicit capacity (which must be larger than size). That seems straightforward to implement as well. @benaadams @maryamariyan does that make sense?

**Comment by benaadams** [comment]
It makes sense; though 99% of the time TrimExcess will probably be not a good function to call; however I can now see a few corner cases where it might be useful.

I have been tweaking Dictionary recently https://github.com/dotnet/coreclr/pull/15419; however I got the impression from the review that adding these apis was already an assigned task so I'll not do it :)

**Comment by danmosemsft** [comment]
@benaadams right, @maryamariyan already started on this one ...

**Comment by maryamariyan** [comment]
Closing this issue as we've added EnsureCapacity and TrimExcess APIs to Dictionary and HashSet.

Created a new issue https://github.com/dotnet/corefx/issues/28328 for tracking adding the same APIs to SortedSet.

**Comment by ViktorHofer** [comment]
What was the reason that we never exposed the Capacity { get; } property here?

**Comment by maryamariyan** [comment]
@ViktorHofer I think the title here is confusing. Capacity { get; } existed. Here we wanted to be able to set the Capacity, which resulted in adding API EnsureCapacity(int capacity).

**Comment by ViktorHofer** [comment]
> Capacity { get; } existed

I don't see it exposed in the ref?

**Comment by karelz** [comment]
I think that `Capacity` getter is internal implementation detail. What value would it give to the user if it was exposed? Users can use `Count` and compute predicted capacity needed, then pass it to `EnsureCapacity` or `TrimExcess`.
If we had `Capacity` we would have to decide if it should return either the internal capacity (which can be different from last call to `EnsureCapacity`/`TrimExcess`), or if we need to remember the last `capacity` arg passed and return that.

**Comment by ViktorHofer** [comment]
Thanks Karel, I will browse through the video later. If the argument really was that we are exposing an implementation detail than I'm fine with it. I just had a case (ok it's a test - but still) where I needed the real capacity without any modification.

**Comment by maryamariyan** [comment]
Also, EnsureCapacity doesn't guarantee to set to the argument value. What is returned is the actual Capacity value.
You can use dictionary.EnsureCapacity(0) to get the actual capacity

**Comment by ViktorHofer** [comment]
> You can use dictionary.EnsureCapacity(0) to get the actual capacity

Oh I didn't know that. Thanks! But if we already implemented it this way that means we are exposing internals. So back to my question, why not just exposing the prop?

**Comment by karelz** [comment]
Turn the question around - why to expose the prop? What is the value?

**Comment by ViktorHofer** [comment]
it gives you more control over the data structure. Not sure if it's just me but I find it weird to get to the Capacity via this hack.

**Comment by danmosemsft** [comment]
I suggest leave as is and see what if any feedback we get. (And whether we see lots of use of EnsureCapacity(0) )
