### ISSUE TITLE
[release/1.1.0] Backport PreferInbox=true to dead-end packages

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#24452]
Many of our packages are no longer produced in 2.0.0 because they were absorbed into .NETStandard.

As a result, there is no new version of those packages with fixes that were only put into the 2.0 codebase.

One example of such a change is https://github.com/dotnet/corefx/pull/18307 (issue https://github.com/dotnet/corefx/issues/15112).  There may be others.

We should backport these changes if they apply to any package that we're no longer shipping in 2.0 so that folks get the changes.  When backporting we should also make sure to ship the complete set of packages impacted.

**Comment by ViktorHofer** [comment]
.NET Core 1.1 reaches end-of-support in four days therefore I'm closing this issue.
