### ISSUE TITLE
ETA for a stable  System.ServiceProcess.ServiceController v4.5 package (for netcore) 

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/corefx#24468]
### Context

The `ServiceBase` functionality for netcore is provided by the [System.ServiceProcess.ServiceController](https://www.nuget.org/packages/System.ServiceProcess.ServiceController/) package. However the current stable version does not provide enough functionality so an [unstable version](https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.ServiceProcess.ServiceController) needs to be used. The current unstable can be resolved from https://dotnet.myget.org/F/dotnet-core/api/v3/index.json

### Question

What is the expected ETA of stable  System.ServiceProcess.ServiceController v4.5 package?

Is there anything i can do to help progress this?

**Comment by SimonCropp** [comment]
and as a followup. can the current unstable of System.ServiceProcess.ServiceController v4.5 please be published to nuget

**Comment by danmosemsft** [comment]
@SimonCropp we aim to have a stable version on nuget next month. Can you get by with the myget version meantime?

Incidentally, have you found that the myget version works for you -- this is good confirmation that it is ready to release.

**Comment by SimonCropp** [comment]
@danmosemsft thanks to getting back to me so quick

> Incidentally, have you found that the myget version works for you -- this is good confirmation that it is ready to release.

Yep been using it on and off for a couple of months now. stable enough for me. ie i have not been able to tell it is a beta

> we aim to have a stable version on nuget next month. Can you get by with the myget version meantime?

For me yes. but we [have doco around this stuff for clients](https://docs.particular.net/samples/hosting/windows-service/?version=core_7#net-core-system-serviceprocess-servicecontroller). and would prefer to minimise the number of hoops we get them to jump through

**Comment by danmosemsft** [comment]
OK, well it should be about a month.

**Comment by SimonCropp** [comment]
thanks. please ping me if u want someone to smoke test

**Comment by SimonCropp** [comment]
@danmosemsft it would also be great if ServiceBase had async OnStart and OnStop methods. Do u need a diff issue for that?

**Comment by danmosemsft** [comment]
For sure, you could make an API proposal as described in [here](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md)

@weshaggard do you see any issues with potentially adding API to this library? I don't.

**Comment by danmosemsft** [comment]
Note, such API might take a while to get ported to desktop .NET Framework, depending on interest. That release runs on a different schedule.

**Comment by weshaggard** [comment]
>@weshaggard do you see any issues with potentially adding API to this library? I don't.

There is no issue with adding new APIs for .NET Core specifically it won't enable them to work on .NET Framework or .NET Standard.

**Comment by SimonCropp** [comment]
https://github.com/dotnet/corefx/pull/24494

**Comment by karelz** [comment]
Seems to be answered and tracked by #24909. Closing.

**Comment by danmosemsft** [comment]
@SimonCropp it's shipped
https://blogs.msdn.microsoft.com/dotnet/2017/11/16/announcing-the-windows-compatibility-pack-for-net-core/
Note - it's marked preview, but it is on nuget.
Please open an issue if you find one.

**Comment by SimonCropp** [comment]
@danmosemsft thanks for the update. and will let u know of any issue :)
