### ISSUE TITLE
Different exceptions being throw in Unix and OSX in HashProviderDispenser

### ISSUE THREAD

**Issue by pjanotti** [dotnet/corefx#24462]
I didn't check if that is also the case for other locations but we have different exceptions between OSX and Unix for the same issue:

https://github.com/dotnet/corefx/blob/b6ef0f1458bbbb43465eaef04ca396e192ff19ed/src/System.Security.Cryptography.Algorithms/src/Internal/Cryptography/HashProviderDispenser.OSX.cs#L30

https://github.com/dotnet/corefx/blob/b6ef0f1458bbbb43465eaef04ca396e192ff19ed/src/System.Security.Cryptography.Algorithms/src/Internal/Cryptography/HashProviderDispenser.Unix.cs#L30

**Comment by danmosemsft** [comment]
Presumably they should do what Windows does, which I think is to throw CryptographicException?
https://github.com/dotnet/corefx/blob/154c2a35d5480d359729959f3e3e7d8578a18612/src/Common/src/Internal/Cryptography/HashProviderCng.cs#L48
