### ISSUE TITLE
The type initializer for 'System.Drawing.KnownColors' threw an exception

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#24478]
@lianggx commented on [Mon Apr 17 2017](https://github.com/dotnet/core/issues/594)

debian.8.x.x64
if you throw The type initializer for 'System.Drawing.KnownColors' threw an exception 
to do:apt-get install libgdiplus

I hope some one can fix it！

---

@richlander commented on [Mon Jul 03 2017](https://github.com/dotnet/core/issues/594#issuecomment-312744247)

@lianggx can you share a sample?

---

@MeetOct commented on [Mon Jul 24 2017](https://github.com/dotnet/core/issues/594#issuecomment-317357160)

i found this in docker images(microsoft/dotnet:1.1.2-runtime) when i used  EPPlus.Core
```
The type initializer for 'System.Drawing.KnownColors' threw an exception.
   at System.Drawing.KnownColors.FromKnownColor(KnownColor kc)
   at System.Drawing.Color.get_White()
```

**Comment by stephentoub** [comment]
What is the inner exception of the exception you shared? Do you have libgdiplus installed?

**Comment by danmosemsft** [comment]
@lianggx can you try with .NET Core 2.0 ?

**Comment by drwharris** [comment]
I am having this issue with core 2.0.

The inner exception is 

Message	"Unable to load DLL 'libdl': The specified module or one of its dependencies could not be found.\n (Exception from HRESULT: 0x8007007E)"	string

Andrew

**Comment by safern** [comment]
This is related to: https://github.com/dotnet/corefx/issues/25102

An API is being added to load native libraries and once that is added we can consume it from System.Drawing and fix the issues we've been hitting when trying to do dlopen that lives in libdl. 

In the meantime as a workaround you can install libc6-dev package and it will give you libdl locally. Will close this issue as the previously mentioned issue is already tracking this.
