### ISSUE TITLE
Serialization error in .net core 2.0, same code was working in .net core 1.1

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#24473]
@chintan3100 commented on [Mon Sep 11 2017](https://github.com/dotnet/core/issues/959)

 public class CustomClass
    {
        [Required]
        public System.Guid? clientId { get; set; }
}

`"\"bb2f3da7-bf79-4d14-9d54-0a1f7ff5f902\""`

system.argumentexception Could not cast or convert from System.String to System.Guid. newtonsoft.json

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

---

@chintan3100 commented on [Mon Sep 11 2017](https://github.com/dotnet/core/issues/959#issuecomment-328666671)

I can not change client call who calling API with `"\"bb2f3da7-bf79-4d14-9d54-0a1f7ff5f902\""`. Client has code freeze.

---

@chintan3100 commented on [Tue Sep 12 2017](https://github.com/dotnet/core/issues/959#issuecomment-328758137)

Hi 
.net core 1.1 : When we return string from api it like
"bb2f3da7-bf79-4d14-9d54-0a1f7ff5f902"
.net core 2.0

`"\"bb2f3da7-bf79-4d14-9d54-0a1f7ff5f902\""`

---

@Petermarcu commented on [Tue Sep 12 2017](https://github.com/dotnet/core/issues/959#issuecomment-328893753)

@ViktorHofer @danmosemsft can you take a look?

---

@ViktorHofer commented on [Tue Sep 12 2017](https://github.com/dotnet/core/issues/959#issuecomment-328913996)

@chintan3100 I spent some time trying to reproduce your issue but I don't have enough information to understand what's going on here.

Please post a small reproduction code. I don't know which APIs you are using (even it they aren't .NET Core related but Json.NET). 

---

@Petermarcu commented on [Fri Oct 06 2017](https://github.com/dotnet/core/issues/959#issuecomment-334623526)

@ViktorHofer can you move this issue over to dotnet/corefx to track it?

**Comment by rajurh** [comment]
Reported issue is fixed? Or will be fixed in future releases? So in order to progress with .Net core 2.0 what will be the alternative option. Any suggestion will be much appreciated.

**Comment by ViktorHofer** [comment]
No, I'm still waiting for a repro sample. The information provided in the initial post isn't enough

**Comment by rajurh** [comment]
Please find the attached repo sample which show the issue what reported in the above chain. 

If you look at code in SerializationErrorMVC for home controller it calls a API endpoint in MoE.ERS.ManagementService and in the response it comes with extra slashes and this managment api was migrated from 1.1 to 2.0. Hope this helps please do let me know if you have more questions on it
[SerializationError.zip](https://github.com/dotnet/corefx/files/1393597/SerializationError.zip)

**Comment by ViktorHofer** [comment]
@rajurh sorry not responding. Could you provide a minimal sample, with the least amount of code, probably in a console application? Thanks a lot!

**Comment by rajurh** [comment]
Thanks sample application has been provided in just above your post which is date on Oct 18. Please do let me know if you need more details of it.

**Comment by danmosemsft** [comment]
@Anipik can you try the repro code above on 2.1?

**Comment by Anipik** [comment]
@danmosemsft yeah I will do it

**Comment by Anipik** [comment]
@rajurh @ViktorHofer I tried running the zip file that you sent me but it doesnot throw any error related to serialization
the error thrown is 
```
HttpRequestException: An error occurred while sending the request.
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult()
System.Net.Http.DiagnosticsHandler+<SendAsync>d__2.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult()
System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__58.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
SerializationError.Controllers.HomeController+<Index>d__1.MoveNext() in HomeController.cs
+
            var responseLookUpUser = await httpClient.GetAsync("http://localhost:63095/v1/ResourceRequest/Test");
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__14.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```
@rajurh can you provide some more info ?

**Comment by ViktorHofer** [comment]
That's why I asked for a minimal repro. The one provided doesn't outline the error described in this thread.

**Comment by ViktorHofer** [comment]
I don't believe this is specific to 2.0 nor to .NET Core at all. The Uri serialization code is the same between netfx and master. I believe this is due to a special handling of non-serializable types (.NET Core 1.1) in JSON.NET. I'm closing this for now. If we get another minimal repro I'm happy to look into it and reopen.
