### ISSUE TITLE
SmtpClient throws NullReferenceException on Dispose()

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#24485]
@sibvic commented on [Wed Aug 30 2017](https://github.com/dotnet/core/issues/912)

I'm using:
    <TargetFramework>netcoreapp2.0</TargetFramework>

    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.0" PrivateAssets="All" />

The next code throws an exception:

            using (var client = new SmtpClient("smtp.mail.ru", 465))
            {
                client.UseDefaultCredentials = false;
                client.Credentials = new NetworkCredential(Options.EmailSenderUser, Options.EmailSenderPassword);
                client.SendAsync(emailMessage, new object());
            }//throws an exception here!!!

NullReferenceException: Object reference not set to an instance of an object.

    System.Net.Mail.SmtpConnection.ReleaseConnection()
    System.Net.Mail.SmtpClient.Dispose(bool disposing)
    System.Net.Mail.SmtpClient.Dispose()

---

@Petermarcu commented on [Wed Aug 30 2017](https://github.com/dotnet/core/issues/912#issuecomment-326046972)

@Priya91, can you copy this over to corefx and maybe take a look?

---

@shalaka198 commented on [Thu Sep 21 2017](https://github.com/dotnet/core/issues/912#issuecomment-331329224)

Is there any update on this issue? I am facing the same.

---

@msvprogs commented on [Sun Sep 24 2017](https://github.com/dotnet/core/issues/912#issuecomment-331741350)

+1, I have the same problem. OS CentOS 7, .NET Core 2.0

**Comment by davidsh** [comment]
This code starts an async operation and it is still running when this code exits the 'using' block.  The code should wait until the async operation is done before existing the 'using' block.

```c#
client.SendAsync(emailMessage, new object());
```

**Comment by Petermarcu** [comment]
Agreed, @sibvic let us know if you have any issues after you update your code to do as @davidsh suggests. I'm going to close this now as it doesn't appear to be an issue in .NET Core.

**Comment by msvprogs** [comment]
I've used synchronous Send() method, nevertheless, I experienced the same problem.

**Comment by Priya91** [comment]
@msvprogs Can you post the exact repro code you used and the callstack?

**Comment by msvprogs** [comment]
@Priya91
Stacktrace:
`Sep 25 00:09:31 localhost dotnet: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
Sep 25 00:09:31 localhost dotnet: An unhandled exception has occurred: Object reference not set to an instance of an object.
Sep 25 00:09:31 localhost dotnet: System.NullReferenceException: Object reference not set to an instance of an object.
Sep 25 00:09:31 localhost dotnet: at System.Net.Mail.SmtpConnection.ReleaseConnection()
Sep 25 00:09:31 localhost dotnet: at System.Net.Mail.SmtpClient.Dispose(Boolean disposing)`

Code:
`using (var client = new SmtpClient
{
	Host = m_Parameters.Host,
	UseDefaultCredentials = false,
	Credentials = new NetworkCredential(m_Parameters.Email, m_Parameters.Password),
	EnableSsl = m_Parameters.UseSsl,
	Port = m_Parameters.Port
})
{
	var messageToSend = new MailMessage
	{
		From = new MailAddress(m_Parameters.Email, m_Parameters.DisplayName),
		Subject = message.Subject,
		Body = message.Body,
		To = { message.Email },
		IsBodyHtml =  message.IsBodyHtml
	};
	client.Send(messageToSend);
}`

**Comment by stephentoub** [comment]
My guess:
The body of the using is throwing an exception, before something gets initialized. Then the finally block from the using runs and null refs, propagating that exception instead of the original. If that's the case, there are two issues: the user code is failing, but SmtpClient isn't correctly handling that possibility in Dispose.

Do you get a different exception if you just avoid disposing the SmtpClient? e.g. just remove the using.

**Comment by msvprogs** [comment]
No, the mail is sent correctly, so it isn't the user code failing problem. Exception occurs right after the Send() method returns control. If I ignore disposing SmtpClient, it actually solves the problem (it means that destructor of SmtpClient handles this state correctly), but it isn't correct in terms of predictable resource releasing.

**Comment by stephentoub** [comment]
Hmm, well, from a cursory look at the code and a quick test, @Priya91, the issue I called out is a real issue: if Send tries to establish a connection and fails, Dispose wlll encounter a null network stream and null ref.  I don't currently see how it's possible to have a null network stream after a successul Send, but fixing the former will presumably fix the latter as well (still, it'd be good to understand how/why that's happening).
