### ISSUE TITLE
System.PlatformNotSupportedException: 'Registry is not supported on this platform.'

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#24483]
@saharM commented on [Mon Aug 21 2017](https://github.com/dotnet/core/issues/876)

## Steps to reproduce:

In Visual Studio 2017 version 15.3.0, in a .NET Core 2.0 Class library I install this Nuget package:

    <PackageReference Include="Microsoft.Win32.Registry" Version="4.4.0" />

I write a simple method that uses RegistryKey class like this:

        internal static bool ReadRegistry()
        {
            bool ret = false;
            RegistryKey sampleDir = Registry.CurrentUser.CreateSubKey("Software\\Company\\Name");
            if (!string.IsNullOrEmpty(sampleDir.GetValue("Foo", "").ToString()))
                ret = true;
            return ret;
        }

I add a new Windows Form project to the solution and in this new project add a reference to my class library and call ReadRegistry method. Building the solution is successful. 

**Side Problem:** At runtime every time that the code reaches the line that calls ReadRegistry method I get this error: 

`System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'`

I try a workaround for this problem by downloading the package manually and copying "\microsoft.win32.registry.4.4.0\lib\netstandard2.0\Microsoft.Win32.Registry.dll" file into WinForm project "\bin\Debug" folder. It works and I can debug inside the ReadRegistry method.

**Main Problem:** Registry.CurrentUser is null and all static properties of Registry class are null and calling RegistryKey.OpenBaseKey method throws this exception:

`System.PlatformNotSupportedException: 'Registry is not supported on this platform.'`

**Comment by danmosemsft** [comment]
@weshaggard it sounds like this is a .NEt Framework (winforms) project referencing a .NET Core library. VS should block that: it shouldn't work.
@saharm can you change your library to a .NET Standard library? (Create a new one)

**Comment by weshaggard** [comment]
@saharM is your class library a .NET Standard library? As @danmosemsft points out you would need that to consume it from a .NET Framework winforms application.

**Comment by saharM** [comment]
@danmosemsft @weshaggard my class library is a .NET Standard 2.0 library.

**Comment by jherby2k** [comment]
I have this issue as well. I have a netcore2.0;net471 multi-targeted test project that uses several netstandard2.0 libraries, one of which references Microsoft.Win32.Registry. The tests that exercise the registry work fine via netcore2.0, but throw the afformentioned exception when running under net471. Shouldn't this library just be a façade for the same Registry types in mscorlib when running under full framework?

**Comment by weshaggard** [comment]
>Shouldn't this library just be a façade for the same Registry types in mscorlib when running under full framework?

Yes it should be Do you have a Microsoft.Win32.Registry.dll in your net471 application output?

**Comment by jherby2k** [comment]
Well, I have one in the netstandard library's output. What's the difference? Well... i'm using MEF to load the netstandard extensions, which are located in a subdirectory (I'm also using assemblyloader to locate dependencies for the extensions). Sounds like this functionality requires a direct dependency for it to put the correct façade in?  I guess I still don't understand how this is all supposed to work.. any suggestions on how to load the correct assembly? I don't even know where to find it.

**Comment by weshaggard** [comment]
When you are doing dynamic loading (i.e. MEF) you become responsible for deploying the right dependencies along with the library being loaded. The tooling will deploy the correct dependencies if they are statically referenced from the application. For this particular case if your .NET Framework application references Microsoft.Win32.Registry package then the correct facade would get deployed in the application. If you cannot or don't want to reference that then you will need to deploy it yourself. For this case if you want to find the right binary look in the Microsoft.Win32.Registry package folder under the `lib\net46` folder as that is the one that will work on .NET Framework.

**Comment by jherby2k** [comment]
Thanks. Certainly seems like MEF needs a hard rethink to work with netstandard and core out of the box... I've written a lot of platform-specific loader code trying to work around all this nonsense.

**Comment by weshaggard** [comment]
This isn't a MEF or a netstandard particular problem but instead it is a general dependency management problem. 

>Would be great if there was some way to include all the dependency libs for selection at runtime.

In order to do that you need to know where the library is running. We have this challenge as well with our msbuild tasks we run for our infrastructure and to help with it we end up building the package targeting netstandard and netfx with `CopyNuGetImplementations` set to true (see example https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks.Feed.net45/Microsoft.DotNet.Build.Tasks.Feed.net45.csproj#L7) that will copy all the dependencies for that library to the output for the appropriate builds.  While that isn't the greatest solution unfortunately is necessary when you try to run the same library on multiple frameworks.

**Comment by weshaggard** [comment]
There isn't anything actionable here so closing. Feel free to ask follow-up questions or examples you need help fixing.
