### ISSUE TITLE
Add support for reading a PFX for Unix builds

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#2449]

**Comment by bartonjs** [comment]
This pulled in a lot of new functionality.  I now have PFX working for X509Certificate2 and X509Certificate2Collection; and load-by-filename support for both of them.

Also, RSAOpenSsl..ctor(IntPtr).  It will allow support for custom ENGINE loading for hardware RSA via OpenSSL, and I needed it for this change :smile:.

There's a lot of scaffolding that needs to be torn down, and interop files cleaned up; but the functionality is there.

15 tests get [ActiveIssue] removed, two changed to a more specific number, and one new test was added.

**Comment by PinpointTownes** [comment]
@bartonjs quick question: do you plan to bring back `X509Certificate2.PublicKey.Key` and `X509Certificate2.PrivateKey` in the future?

I know you recently replaced them by new extensions  (https://github.com/dotnet/corefx/commit/ce0506baea623efdb74707aee0e4aa169d6f468c#diff-bfa5d8625e077d0d1698dff0f9d18709R19), but these extensions are directly tied to RSA while the old properties returned `AsymmetricAlgorithm` and thus were better candidates for extensibility (though I dunno if you have plans to support DSA).

**Comment by bartonjs** [comment]
@PinpointTownes Those two properties returning AsymmetricAlgorithm caused callers to need to cast it to something more useful in order to make use of it.  In 4.6 we fixed the RSA class to be functional without casting to a more specific type (which that change brought in); and added the extension methods to try to eliminate the need for casting.  So the plan is to add extension method pairs for each supported algorithm.

We tried pretty hard to come up with a way to make AsymmetricAlgorithm a meaningful type, but couldn't really come up with anything:
* RSA has sign and encrypt
* DSA and EC-DSA have sign, but not encrypt
* DH and EC-DH have key exchange, but not sign or encrypt.

And we couldn't really come up with an ISignatureAlgorithm type interface because the inputs aren't all the same:
* RSA needs a hash algorithm and a padding mode
* DSA has no choices
* ECDSA needs a hash algorithm

So, in the end, we felt that since you had to cast the return value of `PrivateKey` or `PublicKey.Key`, and it was too tempting to cast to the implementation type, that we wanted to remove those properties from the contracts to encourage programs to switch to the already-typed extension methods.

**Comment by PinpointTownes** [comment]
Wooo, thanks for your great explanation!

It makes total sense, though I'm personally not a huge fan of using extension methods for such critical things. Semantically, a certificate class contract that doesn't directly expose the public or private key seems shaky.

I guess having both the properties and the extension methods would be the best of both worlds.
