### ISSUE TITLE
.net core 1.1 IFormFileCollection files Performance issue

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#24495]
@chintan3100 commented on [Sun Sep 03 2017](https://github.com/dotnet/core/issues/934)

   public async Task<bool> Put(IFormFileCollection files)
        {
            return await UpdateFile(file);
        }

I have hosted application in azure PAAS and analysis log of server. 6 second are taking to get file on server. file size 10 MB.  
Ref Link:http://weblogs.thinktecture.com/pawel/2017/03/aspnet-core-webapi-performance.html

**Comment by benaadams** [comment]
You probably want to file over in aspnet? https://github.com/aspnet/Home

**Comment by Petermarcu** [comment]
In reading, seems there was a kestrel and an httpclient angle to this. Thoughts?

**Comment by benaadams** [comment]
Oh, missed that; looks like its related to buffer size on `HttpClient`? 

Other side would be MVC? https://github.com/aspnet/Mvc/issues/6045

**Comment by Petermarcu** [comment]
Yeah, that was my read of it. :)

**Comment by stephentoub** [comment]
Whereas HttpClient used to use its own copy implementation, it now just uses Stream.CopyToAsync. And CopyToAsync has its own (much larger) default buffer size. We might want to just defer to that default unless an override size was provided to the StreamContent. CopyToAsync also pools the buffer, so the impact of a larger buffer is often not as impactful on GC.

**Comment by karelz** [comment]
cc @valenis

**Comment by rmkerr** [comment]
I've been looking into the original issue described [here](http://weblogs.thinktecture.com/pawel/2017/03/aspnet-core-webapi-performance.html). I have their repro working, but so far I'm getting very different results:
```
"OK"
Ping took 00:00:02.0110560
Upload from Memory of 20 MB took 00:00:00.5958383. Speed = 33.57 MB/s
Upload from Memory of 20 MB took 00:00:00.5411754. Speed = 36.96 MB/s
Upload from Memory of 20 MB took 00:00:00.4639538. Speed = 43.11 MB/s
Upload from File System of 20 MB took 00:00:00.3225483. Speed = 62.01 MB/s
Upload from File System of 20 MB took 00:00:00.3411222. Speed = 58.63 MB/s
Upload from File System of 20 MB took 00:00:00.4163231. Speed = 48.04 MB/s
UploadMultipart using IFormFile of 20 MB took 00:00:01.8634437. Speed = 10.73 MB/s
UploadMultipart using IFormFile of 20 MB took 00:00:01.5458462. Speed = 12.94 MB/s
UploadMultipart using IFormFile of 20 MB took 00:00:01.5839196. Speed = 12.63 MB/s
UploadMultipart using Multipart-Reader of 20 MB took 00:00:00.4219229. Speed = 47.40 MB/s
UploadMultipart using Multipart-Reader of 20 MB took 00:00:00.3753970. Speed = 53.28 MB/s
UploadMultipart using Multipart-Reader of 20 MB took 00:00:00.4286988. Speed = 46.65 MB/s
Download using Default-FileResult of 20 MB took 00:00:01.2164005. Speed = 16.44 MB/s
Download using Default-FileResult of 20 MB took 00:00:01.2633937. Speed = 15.83 MB/s
Download using Default-FileResult of 20 MB took 00:00:01.2682102. Speed = 15.77 MB/s
Download using CustomFileResult of 20 MB took 00:00:00.7284986. Speed = 27.45 MB/s
Download using CustomFileResult of 20 MB took 00:00:00.7156857. Speed = 27.95 MB/s
Download using CustomFileResult of 20 MB took 00:00:00.7212038. Speed = 27.73 MB/s
```
I think the difference is likely a result of running both the client and the server on the same machine. I'm going to try to get the server set up remotely and will see if I can get more consistent results.

**Comment by rmkerr** [comment]
I have a tentative fix ready for this issue, but before I send out a pull request I'm going to try to set up some more extensive performance testing. I've never done any perf testing before, so any advice there would be appreciated. Otherwise I'll just dive into it on my own 😄 

If you're interested in checking it out, you can find my changes [here](https://github.com/rmkerr/corefx/tree/CopyAsync_NoBufferSizeProvided_UsesDefaultSize).
