### ISSUE TITLE
Linux Memory Leak using DefaultRequestHeaders.ConnectionClose = true

### ISSUE THREAD

**Issue by psyonix-luis** [dotnet/corefx#24499]
We've been investigating a memory leak for a while now and have finally found the cause. Originally, due to some requirements we were forced to close connections after each request, so we set HttpClient.DefaultRequestHeaders.ConnectionClose to true on our HttpClient singleton. The leak was exposed under a load test. We added a setting around ConnectionClose and simply leaving it at false stops the leak. 

This leak can be reproduced under centos7 environment using a load test on this basic core 2.0 project : https://github.com/psyonix-luis/CloseConnectionLeak

We are unable to reproduce this in Windows, memory stays relatively constant : https://i.imgur.com/IBD0CFQ.jpg

After a test of 300k requests using the sample project in linux, the app was taking up about 5.5GB : https://i.imgur.com/qZM5K7W.jpg

Comparison true vs false : https://i.imgur.com/Z6Z6CSG.png

I would expect some performance difference not reusing connections, but not a _killer_ difference.

**Comment by stephentoub** [comment]
> This leak can be reproduced under centos7 environment

What version of curl do you have ("curl --version"), and have you tried installing a newer one?

**Comment by psyonix-luis** [comment]
Thank you @stephentoub , that was it! I was originally at `7.29.0`, and after upgrading to `7.56.0` I am no longer seeing memory issues.
