### ISSUE TITLE
Difference between Windows and OSX

### ISSUE THREAD

**Issue by ejsmith** [dotnet/corefx#24507]
The following test passes when running on Windows, but fails when running on OSX.

```c#
[Fact]
public void NonAbsoluteUriShouldThrow()
{
   Assert.Throws<UriFormatException>(() => new Uri("/api/", UriKind.Absolute));
}
```

**Comment by stephentoub** [comment]
That's because Uri accepts file paths, and on Unix, "/api/" is a valid absolute file path.

**Comment by ejsmith** [comment]
Ahhh true. Duh. Sorry.
