### ISSUE TITLE
Add core-setup's RuntimeEnvironment (platform detection) logic to RuntimeInformation

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#24522]
Currently we have multiple pieces of code used for detection OS and its version:
https://github.com/dotnet/corefx/blob/master/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.cs
https://github.com/dotnet/core-setup/blob/master/src/managed/Microsoft.DotNet.PlatformAbstractions/RuntimeEnvironment.cs

this logic is non-trivial to get correctly and thus we should not duplicate this logic.

I believe RuntimeInformation is the most intuitive place where platform detection code should live.

**Comment by danmosemsft** [comment]
Wasn't this done @krwq?

**Comment by jkotas** [comment]
This was not done.

> duplicate this logic

If you just want to avoid duplicating this logic, you consume these APIs via https://www.nuget.org/packages/Microsoft.DotNet.PlatformAbstractions/ NuGet package.

A separate issue is that these APIs are de-facto public .NET Core APIs, but they live in a pretty non-standard place: The sources for it live in  https://github.com/dotnet/core-setup/tree/master/src/managed/Microsoft.DotNet.PlatformAbstractions, never gone through API review, ... .

**Comment by krwq** [comment]
AFAIK only Redhat related pieces were unified

**Comment by danmosemsft** [comment]
Note the implementation of the Libc methods is not a specialization of reading a file version. It calls gnu_get_libc_version().

It seems either
- We allow RuntimeEnvironment to remain an appropriate location for these not so generally interesting API
- CLI allows me to paste in the implementation
- We cannot collect such datapoints.

**Comment by jkotas** [comment]
Why can't you PInvoke `gnu_get_libc_version` yourself from the telemetry code? It looks odd to have APIs for it in the runtime/framework.

**Comment by tannergooding** [comment]
> It seems either
> * We allow RuntimeEnvironment to remain an appropriate location for these not so generally interesting API, or
> * CLI allows me to paste in the implementation, or
> * We cannot collect such datapoints.

I don't think that these APIs (strictly speaking) need to be part of CoreFX. However, I also agree that they do not belong in CLI.

These are more general APIs that telemetry code, in general, may want to use, and adding an API to some shared telemetry library and referencing that from CLI seems like the most appropriate action.

**Comment by danmosemsft** [comment]
> Why can't you PInvoke gnu_get_libc_version yourself from the telemetry code? It looks odd to have APIs for it in the runtime/framework.

@livarcocc could you please speak to that?

**Comment by livarcocc** [comment]
Have we considered maybe putting them in PlatformAbstractions in CoreSetup?

I also agree 100% with Tanner's comment above. The code had enough specificity to it that it felt it did not belong in the CLI.

**Comment by danmosemsft** [comment]
We can do that if we are happy holding API in Microsoft.DotNet.PlatformAbstractions.dll to a lower bar (less general purpose, not API reviewed, possibly lower compat bar). This is apparenlty what we have done so far.

**Comment by jkotas** [comment]
If you are collecting the telemetry point for LIBC version in CLI, it makes it part of CLI whether you like it or not. Having <10 line implementation to get it living somewhere else won't change that.

The interesting telemetry points evolve over time.  Let's say we decide that the LIBC version is useless point 6 months from now, but we would want to have telemetry about openssl version instead. Are we going to add API for it to Microsoft.DotNet.PlatformAbstractions? Just trying see where we will end up.

> possibly lower compat bar

I doubt it. This .dll is evolving into a very *useful* .dll that tells you about OS you are running on, and that everybody will depend on before you know it. It has ~10 million downloads on nuget.org.

**Comment by eerhardt** [comment]
> These are more general APIs that telemetry code, in general, may want to use, and adding an API to some shared telemetry library and referencing that from CLI seems like the most appropriate action.

What's the difference between the proposed APIs and the existing [`MacAddressGetter`](https://github.com/dotnet/cli/blob/af676518dd963814c76c45adb80d59adc1b387b8/src/dotnet/Telemetry/MacAddressGetter.cs#L84)?  "Getting a mac address" is also a "more general API", but it was deemed worthy of adding the code to dotnet/cli.

It would seem, if we need the data points, and no one lower in the stack is willing to add an API for the scenario, then the only possible outcomes are:

* We cannot collect such datapoints, or
* CLI allows me to paste in the implementation, or
* Someone creates a new library to put these generally useful APIs

Honestly, my personal opinion on how to handle these types of situations are "second time pays for generality" (-Uncle Bob).  We only have 1 case where someone needs to use this data (CLI telemetry).  Until we have a 2nd, we shouldn't attempt to pay the cost of generalizing it.

**Comment by wli3** [comment]
>  Having <10 line implementation

It is 10 lines of implementation, and there is efforts to make sure all the calls this 10 lines of code depends on exist on all the OSs we support.

>  MacAddressGetter

What "getMacAddress" is really doing is to "get mac address **exactly** like VS and VSCode", or we could just use `NetworkInterface.GetAllNetworkInterfaces()`.

Also it is several lines of code, but turned out one of the command it shells out (_getmac_) does not exist on Windows Nano. We had to back and forth on that.

getMacAddress has 2 commands to shell out. The proposed code has much more native dependencies.

> second time pays for generality

We **are** building generality to support all OSs via these c# apis

**Comment by eerhardt** [comment]
> get mac address exactly like VS and VSCode

That sounds like even MORE of a reason to put that code in a “general telemetry library” and not have it in dotnet/cli.

**Comment by ViktorHofer** [comment]
Closing in favor of https://github.com/dotnet/corefx/issues/16629
