### ISSUE TITLE
System.ComponentModel.Tests.AsyncOperationFinalizerTests.Finalizer_OperationNotCompleted_CompletesOperation failed in CI

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#24537]
Failed test: System.ComponentModel.Tests.AsyncOperationFinalizerTests.Finalizer_OperationNotCompleted_CompletesOperation 

Configuration: osx10.12_debug

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/3273/testReport/System.ComponentModel.Tests/AsyncOperationFinalizerTests/Finalizer_OperationNotCompleted_CompletesOperation/

MESSAGE:
~~~
Exit code was 131 but it should have been 42\nExpected: True\nActual: False
~~~
STACK TRACE:
~~~
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 191 
at System.ComponentModel.Tests.AsyncOperationFinalizerTests.Finalizer_OperationNotCompleted_CompletesOperation() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/src/System.ComponentModel.EventBasedAsync/tests/AsyncOperationFinalizerTests.cs:line 42
~~~

**Comment by Jiayili1** [comment]
related issue: https://github.com/dotnet/corefx/issues/24298

@danmosemsft For this exit code 131, do we need to ignore it?

**Comment by danmosemsft** [comment]
@Jiayili1 no, don't ignore 131. It's a real failure. 

This line is above it in the log, and hte same in the #24298 as well:

` A fatal error occurred, the required library libhostfxr.dylib could not be found at /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/bin/testhost/netcoreapp-OSX-Release-x64/shared/Microsoft.NETCore.App/9.9.9/`

higher up I see it was apparently gotten successfully from the package from core-setup:

`  /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/packages/runtime.osx-x64.Microsoft.NETCore.DotNetHostResolver/2.0.1-servicing-25615-03/runtimes/osx-x64/native/libhostfxr.dylib (runtime.osx-x64.Microsoft.NETCore.DotNetHostResolver.2.0.1-servicing-25615-03) -> /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/bin/Unix.AnyCPU.Release/runtime/netcoreapp/libhostfxr.dylib`

I do not know why it was missing and only for these tests. Some more logigng may be needed.

**Comment by Sunny-pu** [comment]
failed again in CI:
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release/lastCompletedBuild/testReport/System.ComponentModel.Tests/AsyncOperationFinalizerTests/Finalizer_OperationNotCompleted_CompletesOperation/

**Comment by Sunny-pu** [comment]
failed again in CI:
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release/3874

**Comment by Sunny-pu** [comment]
failed again in CI:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_osx_release/327/testReport/

**Comment by danmosemsft** [comment]
I'm going to close this since it's apparently been 6 weeks and it's not clearly actionable - please reopen if it happens again
