### ISSUE TITLE
System.Diagnostics.Process.StartTime can be improved in Windows

### ISSUE THREAD

**Issue by NN---** [dotnet/corefx#24542]
When Process instance is created using Process.GetProcesses() , it calls GetProcessInfos method inside.
In WIndows it calls to internal [NtQuerySystemInformation](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessManager.Win32.cs) which returns process creation time.

[ProcessInfo](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessInfo.cs) can be initialized using this value and pass it into Process.

This allows getting StartTime property without any exception thrown.

**Comment by stephentoub** [comment]
> This allows getting StartTime property without any exception thrown.

Can you share a repro of the problem you're facing?

**Comment by NN---** [comment]
For instance Process.GetProcesses() returns all processes including CSRSS.exe, but when I ask for its StartTime I get an exception.

**Comment by stephentoub** [comment]
> when I ask for its StartTime I get an exception.

Presumably you're getting an access denied error?  Have you tried running your code as an administrator?

**Comment by NN---** [comment]
You cannot get Process handle of CSRSS even if you are administrator.
My point is that the relevant data is already retrieved in one API without any process handle requirements.

**Comment by stephentoub** [comment]
> You cannot get Process handle of CSRSS even if you are administrator.

When I run this code:
```C#
using System;
using System.Diagnostics;

class Program
{
    static void Main()
    {
        foreach (var p in Process.GetProcessesByName("csrss"))
        {
            Console.Write($"{p.Id} {p.ProcessName} ");
            try { Console.WriteLine(p.StartTime); }
            catch (Exception e) { Console.WriteLine(e.GetType().Name + " = " + e.Message); }
        }
    }
}
```
without admin rights, I get:
```
636 csrss Win32Exception = Access is denied
528 csrss Win32Exception = Access is denied
```
but when I Run As Administrator, I get:
```
636 csrss 10/4/2017 5:29:53 AM
528 csrss 10/4/2017 5:29:52 AM
```

**Comment by poizan42** [comment]
@stephentoub I think what @NN--- is saying is that NtQuerySystemInformation with SystemProcessInformation returns certain informations about processes even if you do not have the privileges to open a handle. So the Process class could use the information from that if even if it can't open a handle.

The CreateTime field is not officially documented though (it is part of Reserved1), so there is no guarantee that it is still there tomorrow.

**Comment by NN---** [comment]
@stephentoub It works, but requires elevation.
@poizan42 Thanks. That what I meant.
I agree about not officially documented.
I doubt it is going to be changed in Windows versions and if you want to be on safe side it can be protected with Windows version comparison.

**Comment by stephentoub** [comment]
> Thanks. That what I meant.

Ok, thanks for clarifying.  If there's a way to avoid the need for elevation, great, but .NET can't take a dependency on an undocumented field, even with a version check.
cc: @danmosemsft

**Comment by danmosemsft** [comment]
@NN--- yes, we cannot allow .NET Core to use any undocumented Windows API. Eg in the case of SYSTEM_PROCESS_INFORMATION we explicitly follow what is documented for it in NtQuerySystemInformation and ZwQuerySystemInformation (they are not quite the same - a doc issue). Perhaps there is some way to get this information through documented API? If not, a 3rd party library is free to use the undocumented API, at the risk of course of being broken at any time.

**Comment by NN---** [comment]
[SystemProcessInformation](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessManager.Windows.cs#L845) still differs from [SYSTEM_PROCESS_INFORMATION](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724509(v=vs.85).aspx) in MSDN .
For example MSDN doesn't define 'NumberOfThreads' or even 'ImageName':

```c
typedef struct _SYSTEM_PROCESS_INFORMATION {
    ULONG NextEntryOffset;
    BYTE Reserved1[52];
    PVOID Reserved2[3];
    ....
```

```cs
        [StructLayout(LayoutKind.Sequential)]
        internal unsafe struct SystemProcessInformation
        {
            internal uint NextEntryOffset;
            internal uint NumberOfThreads;
            private fixed byte Reserved1[48];
            internal Interop.UNICODE_STRING ImageName;
           ...
```

How they are considered as documented even if they are not defined in MSDN ?

**Comment by danmosemsft** [comment]
@NN--- ZwQuerySystemInformation mentions NumberOfThreads. ImageName should be documented --  this is a doc bug (or I'm just not finding the right version of the doc). I've reached out internally to get the doc corrected. That wouldn't include what you need here though unfortunately.

**Comment by NN---** [comment]
@danmosemsft Seems like Nt version should update docs.
There are more fields that are not documented, perhaps another documentation bug.
Such as BasePriority, SessionId, PeakVirtualSize, VirtualSize, PeakWorkingSetSize , WorkingSetSize, QuotaPagedPoolUsage, QuotaNonPagedPoolUsage

**Comment by danmosemsft** [comment]
@NN--- yep.

**Comment by NN---** [comment]
@danmosemsft Following this case, is there a reason why other fields such as CreateTime won't be documented too ?

**Comment by danmosemsft** [comment]
@NN--- the doc has been updated to include everything that .NET Core uses:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms724509(v=vs.85).aspx

For CreateTime - Windows wants to minimise what they document here, so they have the flexibility to change their implementation. There really ought to be some other way to get the information, though.

**Comment by danmosemsft** [comment]
Nothing we can do unforunately... please reopen if I'm wrong.
