### ISSUE TITLE
Stream Dispose does not call Dispose(bool)

### ISSUE THREAD

**Issue by artiomchi** [dotnet/corefx#24543]
I'm comparing the behaviour between .NET Framework and .NET Core, and I noticed an interesting inconsistency.

In the .NET Framework, the `Stream` class has a `Dispose()` method, which calls `Close()`, which in turn calls `Dispose(bool)`.

In the .NET Core framework, the `Close()` method has been removed as a duplicate of `Dispose()`, but it seems like nothing ever calls `Dispose(bool)` anymore.

You can see classes like `SqlStream` overriding `Dispose(bool)`, which from the looks of it will never be called, when you actually try to dispose the object.

Since there's no source code for these classes, I've used a decompiler to look at `System.IO`:
![image](https://user-images.githubusercontent.com/822898/31382399-6f31c440-adaf-11e7-8482-f631a5af41c0.png)

Could someone confirm that?

**Comment by mikedn** [comment]
> Since there's no source code for these classes, I've used a decompiler to look at System.IO:

Hmm? You may be looking in the wrong place, the source is definitely available. It's in corelib so you can find it in the coreclr repository rather than the corefx repository.

https://github.com/dotnet/coreclr/blob/be3715cbba1022c95bb668d45521016b0414bc25/src/mscorlib/src/System/IO/Stream.cs#L226-L257

Seems fine to me. `Dispose()` calls `Close()` and `Close()` calls `Dispose(bool)`.

**Comment by artiomchi** [comment]
Hmm.. Interesting.

I'm looking at the Release 1.0 and 1.1 branch, and they have the `Close()` method as well, but if I compile my app against netcoreapp1.1, the `Close()` method shouldn't be present in the `Stream` class! Looking at this, I'm not sure whether the branch is pointing to the right location or not =/

I've been looking at the reference assembly from System.IO package for .NET Standard 1.5, and the Stream class seems to have the code I linked above. I'm guessing the reference assemblies are also not accurate then. Great! /s

**Comment by mikedn** [comment]
Note that reference assemblies contain only methods that are available in the contract (e.g. NETStandard). Implementation assemblies (such as System.Private.CoreLib) can and will contain additional methods. So the fact that there's no `Close` method in the reference assembly doesn't mean that such a method doesn't actually exist.

**Comment by artiomchi** [comment]
Ahh.. Well that explains a lot. I got so used to checking the source of the .NET framework assemblies, that I assumed that the reference assemblies will have the correct source.

Seems like this is a non issue after all.

Thanks for setting me straight, and pointing me to the correct sources :)
