### ISSUE TITLE
Issues in CoreFx build and opening particular solution in VS 2017 community edition.

### ISSUE THREAD

**Issue by WinCPP** [dotnet/corefx#24548]
I am seeing following issue in build and opening System.Runtime.Extension solution in VS 2017 Community edition IDE. About three (plus) weeks back these issues were not seen. Last weekend, I sync'd my fork with latest code in dotnet/master and since then these issues have been happening consistently. Not only on my branch for #22409 but also on the master branch in my fork. I also recreated my local git repo, but no luck. Issues are,

a. On firing "build.cmd" / "build-managed.cmd" execution is stuck at below line seen on console for about 10 - 15 mins and, at that time network activity kicks in. I see download at about 300kBps from the server "blob.byaprdstr06a.store.core.windows.net". Roughly 50MB of stuff is downloaded and then the build proceeds. The line on console after which download begins is as below:

```D:\WinCPP\corefx\packages\Microsoft.TargetingPack.NETFramework.v4.6.1\1.0.1\lib\net461\sysglobl.dll (Microsoft.TargetingPack.NETFramework.v4.6.1.1.0.1) -> D:\WinCPP\corefx\bin\AnyOS.AnyCPU.Release\netfx\netcoreapp\sysglobl.dll```

b. On opening System.Runtime.Extension in VS 2017 Community edition IDE, it gets stuck at "Preparing Solution" for similar duration (10 - 15 mins). In this case too, network activity kicks in and devenv.exe appears to be downloading data from same server "blob.byaprdstr06a.store.core.windows.net". Alt+Tab into VS 2017 Community IDE at that point gives a pop up at lower right saying VS is busy and information has been sent to "Visual Studio Experience Improvement Program"...

Both the above issues repeat on each run of build command or each time the solution is opened in VS IDE.

Primarily the problem is that 50MB per build (or even on opening VS) translates to 500 MB if I were to build / open VS for about 10 times during one coding session; a number that can be easily exceeded. Secondly, the 10-15 min delay holds up build / opening VS IDE.

Kindly help. I am wondering if the download is not able to write some sort of ".complete" file because of which the entire download is repeated every time I run build command or open the solution?

This could very well be an issue with my setup that got introduced after I rebased about a month's data from dotnet/master.

@karelz @weshaggard created this issue as per our discussion on gitter.

**Comment by weshaggard** [comment]
Thanks for the report @WinCPP I will attempt these steps and see if I can repro the issue. Do you know what the 50MB's that keeps getting downloaded is?

**Comment by WinCPP** [comment]
Thank you @weshaggard. Actually I am also interested in knowing that so I could provide more details. But running build.cmd with -verbose option doesn't give anything as to what it is doing at that point of time. Is there some additional option that I need to give for debugging the build process itself?

Between, just now, my build is stuck at that step for last 30+ minutes....!

**Comment by weshaggard** [comment]
So the build does download a number of packages but once they are downloaded they shouldn't need to keep being downloaded.  How is your internet connection? Also another option you can do is to download upfront you can run the "sync.cmd"

**Comment by WinCPP** [comment]
The build ended and it downloaded about 91 MB this time. I could see msbuild.exe using network resources during that time.

My internet connection is a 25 Mbps broadband...

I will try sync.cmd. One question about location of the packages. Few months back, due to depleting space on C drive (system), I was looking for ways to move the NuGet package directory to D drive and someone helped me with the NuGet config file changes to achieve that on the gitter.im/corefx discussion forum. He has also written up a note in the docs section in this corefx repo, but I am not able to find that at this moment. Would that customized path be causing an issue because I understand from @karelz that some changes have happened at the server side for the content repo... just thought I would mention about customized path... Thanks!

**Comment by WinCPP** [comment]
@weshaggard I am seeing similar issue with sync.cmd as well. Ran it multiple times. Each time it is stuck just after the below line for about 15+ mins and downloaded around 80 MB.

```
  D:\WinCPP\corefx\packages\runtime.win-x64.Microsoft.NETCore.Runtime.CoreCLR\2.1.0-preview1-25806-01\runtimes\win-x64\lib\netstandard1.0\SOS.NETCore.dll (runtime.win-x64.Microsof
  t.NETCore.Runtime.CoreCLR.2.1.0-preview1-25806-01) -> D:\WinCPP\corefx\Tools\ilasm\SOS.NETCore.dll
```

**Comment by WinCPP** [comment]
Between. I cancelled sync.cmd when it was stuck and it gave this output... looks like some hint what is happening / downloading at that time...

```
D:\WinCPP\corefx\Tools\Symbols.targets(533,7): warning MSB4220: Waiting for the currently executing task "DownloadFilesFromUrl" to cancel. [D:\WinCPP\corefx\external\runtime\runtime.depproj]
```

**Comment by weshaggard** [comment]
Yes it does sound like the downloading might be your issue and changing the packages path might have something to do with it. Can you try undoing your nuget.config change and see if that helps at all?

**Comment by WinCPP** [comment]
Ok. Got the doc which mentioned how to customize NuGet package path. Please refer [here](https://github.com/dotnet/corefx/wiki/Build-and-run-tests#nuget-cache-customization)

I will try undoing the nuget.config changes... But the customized path worked fine for me since May '17 until last weekend when I did a sync from dotnet/master after which I started having this download issue.

Between the runtime.depproj mentioned in previous comment has Download instructions for symbol packages, etc. which don't appear to have checks for if they have been already downloaded...?

**Comment by weshaggard** [comment]
We did recently start downloading symbol packages which might have some issues. @safern can you help look into this?

**Comment by weshaggard** [comment]
@WinCPP you can also help test this theory by setting DownloadCoreCLRSymbols=false in your env or 
passing it to the build commands. 

@safern it doesn't look like we are doing this download incrementally https://github.com/dotnet/corefx/blob/master/external/runtime/runtime.depproj#L92, we should definitely fix that.

**Comment by safern** [comment]
> @safern it doesn't look like we are doing this download incrementally https://github.com/dotnet/corefx/blob/master/external/runtime/runtime.depproj#L92, we should definitely fix that.

Taking a look now.

**Comment by WinCPP** [comment]
Wow! That was awesome! @weshaggard Thank you for suggesting the flag "DownloadCoreCLRSymbols=false". With that flag set, build was a breeze. Even my machine's fan hummed in same way as it used to previously do.

To confirm it, I ran build with that flag set multiple times and never did it stop at the dlls that I mentioned in the opening comment. Also network activity was negligible.

Also to confirm converse, I close the developer command prompt and relaunched it without setting the flag; fired build. And it is stuck once again with all the network activity.

Hope this helps.

**Comment by WinCPP** [comment]
Additionally, for the second problem in the opening comment - "issue with VS 2017 Community Edition IDE while opening System.Runtime.Extension solution" - I did the same thing. Opened Developer command prompt 2017 -> set the environment variable that @weshaggard provided -> launched devenv.exe from that prompt (so it takes this additional env variable) -> opened the said solution from the IDE. Again as above, the experience was as original i.e. the solution opened immediately and I didn't get the "Preparing Solution..." dialog box.

To test converse, I closed everything -> opened VS IDE directly (no command prompt; no DownloadCoreCLRSymbols=false being set anywhere) -> opened the solution and it was once again stuck at "Preparing solution..." with all the network activity in resource monitor.

So looks like it is related to symbols in both the cases...? Could we make this into some command line option which when set, only then should the symbols be downloaded and that too incrementally? Pardon me, if I don't know the purpose behind the change to get symbols, but I was just trying to save on bandwidth and also to have a responsive build and IDE launch experience :)

Between, do you guys need me around? It is couple of hours past midnight here, need to catch couple of hours of sleep...!!!

Thank you again for helping!

**Comment by safern** [comment]
I think we should disable the download symbols by default to not affect contributors as it is a 50MB package and have a property to enable it. Then where we need them, like CI and official builds to track test crashes and get code coverage we can enable that flag. 

What do you think? @weshaggard

**Comment by safern** [comment]
@WinCPP we decided that we are going to keep the download by default but I just did it incremental such that if we have already the symbols in the cache don't download them again and just get them from there. Which means after you've run sync.cmd or build.cmd once you shouldn't have any problems. Also you could set the env var if you want to disable it always if it is slow in your end.

**Comment by WinCPP** [comment]
@safern Thanks for the fix.

Quick curiosity questions.
1. What could be the reason that only symbol downloads are at few hundreds of kbps rate whereas rest of the downloads i.e. setting up git repo, the package refresh etc., happens at 20-25Mbps... i.e. full speed of my connection. Is it because other stuff that downloads fast is cached on some servers which are near to me and the symbols come from one specific server and are not cached anywhere? Could that also be resolved?
2. Opening solution in VS also used to trigger a download. I guess that was due to project dependencies? Could such dependencies be moved to the build step?

Also, the fix that you have done will be helpful to conserve monthly internet quota!!

Thanks,
Mandar
