### ISSUE TITLE
Need to build new 2.0.x Microsoft.NETCore.Platforms package

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#24551]
We've made changes to the RID graph in the release/2.0.0 servicing branch.  Specifically we [added support for RHEL 6](https://github.com/dotnet/corefx/pull/22970).

However, we aren't producing a `2.0.x` version of the `Microsoft.NETCore.Platforms` package that contains these changes.  In order to fully support RHEL 6, we need a new Platforms package with these changes in it.

@weshaggard @Petermarcu @ericstj

**Comment by weshaggard** [comment]
Fixed with https://github.com/dotnet/corefx/pull/24560
