### ISSUE TITLE
HttpListener cannot recognize Websocket request from firefox

### ISSUE THREAD

**Issue by alhimik45** [dotnet/corefx#24550]
When establishing websocket connection, firefox sends such `Connection` header: `Connection: keep-alive, Upgrade` and `System.Net.HttpListener` can't recognize the `Upgrade`

It can be tested with inserting this test case
```csharp
[InlineData("Connection: keep-alive, Upgrade\r\nUpgrade: websocket", true)]
```
to the `IsWebSocketRequest_GetProperty_ReturnsExpected` test of `HttpListenerRequestTests.cs`

**Comment by stephentoub** [comment]
Which OS? Windows? Linux? Both?

**Comment by alhimik45** [comment]
Both

**Comment by jcao219** [comment]
I ran into this issue today.

The spec says that the Connection header need only _include_ the string "Upgrade", but the HttpListenerRequest checks for equality.

**Comment by caesar1995** [comment]
Not able to repro, probably [has already been fixed here](https://github.com/dotnet/corefx/blob/master/src/System.Net.HttpListener/src/System/Net/HttpListenerRequest.cs#L133).

Please re-open this bug if the problem still exists.
