### ISSUE TITLE
System.Net.Sockets.Tests.IPPacketInformationTest.Equals_NonDefaultValue_Success failed with "Xunit.Sdk.TrueException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#24566]
System.Net.Sockets.Tests.IPPacketInformationTest.Equals_NonDefaultValue_Success [FAIL]
18:26:35         Assert.True() Failure
18:26:35         Expected: True
18:26:35         Actual:   False
18:26:35         Stack Trace:
18:26:35   downloaded dumpling.py
18:26:35   total elapsed time 0:00:00.156276
18:26:35   downloaded dumpling.py
18:26:35   total elapsed time 0:00:00.155070
18:26:35            /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/System.Net.Sockets/tests/FunctionalTests/IPPacketInformationTest.cs(76,0): at System.Net.Sockets.Tests.IPPacketInformationTest.GetNonDefaultIPPacketInformation()
18:26:35            /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/System.Net.Sockets/tests/FunctionalTests/IPPacketInformationTest.cs(32,0): at System.Net.Sockets.Tests.IPPacketInformationTest.Equals_NonDefaultValue_Success()

Configuration: osx10.12_release

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release/3312/

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release/3312/consoleFull#-14347295752d31e50d-1517-49fc-92b3-2ca637122019

**Comment by wfurt** [comment]
There are no failures in Helix runs. This seems one-off in CI.

**Comment by karelz** [comment]
No Helix official run failure, closing.
