### ISSUE TITLE
Atom10ItemFormatter. WriteToAsync() return wrong Result.

### ISSUE THREAD

**Issue by JimboWei** [dotnet/corefx#24572]
Test code : 
```c#
SyndicationItem item1 = new SyndicationItem("SyndicationFeed released for .net Core", "A lot of text describing the release of .net core feature", new Uri("http://Contoso.com/news/path"));
string serializeFilePath = Path.GetTempFileName();
try
{
    XmlWriter writer = XmlWriter.Create(serializeFilePath, new XmlWriterSettings() { Async = true });
    Atom10ItemFormatter f = new Atom10ItemFormatter(item1);
    Task task = f.WriteToAsync(writer);
    Task.WhenAll(task);
    writer.Close();
}
finally
{
    File.Delete(serializeFilePath);
}
```
**Result File content**:
`<?xml version="1.0" encoding="utf-8"?><entry xmlns="http://www.w3.org/2005/Atom" />`

**It should be like this**:
`<?xml version="1.0" encoding="utf-8"?><entry xmlns="http://www.w3.org/2005/Atom"><id>uuid:43481a10-d881-40d1-adf2-99b438c57e21;id=1</id><title type="text">SyndicationFeed released for .net Core</title><updated>2017-10-11T11:25:55Z</updated><link rel="alternate" href="http://contoso.com/news/path" /><content type="text">A lot of text describing the release of .net core feature</content></entry>`

**Comment by JimboWei** [comment]
The root cause is the same with issue #24604, but the exception is not caught.

**Comment by shmao** [comment]
@JimboWei this should be fixed by https://github.com/dotnet/corefx/pull/24882. Can you please rebase your change to the latest after https://github.com/dotnet/corefx/pull/24882 get merged.

The test `AtomEntryPositiveTest_Write` still failed at text comparison. It seems to be an issue with `XmlDiff`.

**Comment by JimboWei** [comment]
It is not an issue with `XmlDiff`, I have opened new issue #24894 for it.
