### ISSUE TITLE
Make BigInteger BigEndian-friendly

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#24575]
The current state of BigInteger accepts a `byte[]` (and now a `ReadOnlySpan<byte>`) as a little-endian signed value, and the writer APIs (`ToByteArray()` and `TryWriteBytes`) only emit as a signed little-endian value. Various wire protocols may dictate either of 1) an unsigned value in transmission or 2) big-endian transmission.  Both of these protocol choices result in the application/library needing to understand the translation of protocol bytes to BigInteger bytes, at a cost to performance and risk to reliability.

## Proposal
```C#
partial class BigInteger
{
    // Augment existing
    public BigInteger(
        ReadOnlySpan<byte> value,
        bool isBigEndian=false,
        bool isUnsigned=false) => throw null;

    // Augment existing
    public bool TryWriteBytes(
        System.Span<byte> destination,
        out int bytesWritten,
        bool isBigEndian=false,
        bool isUnsigned=false) => throw null;

    // New overload.
    public byte[] ToByteArray(bool isBigEndian=false, bool isUnsigned=false) => throw null;
}
```

Since the span-based APIs have not yet released, I propose that they be augmented with the default-value-parameters.  For `ToByteArray` an overload will have to be added, but the existing method can just forward to `ToByteArray(false, false)`.

A byte[]-based ctor overload may also be warranted if Span and BigInteger may have different velocities to .NET Framework (or the implicit cast causes too much cognitive overload).

## Behavior

Given `byte[] data = { 0xFE, 0x80 };`

* `new BigInteger(data, isBigEndian: false, isUnsigned: false)` => `(short)0x80FE` => `-32514`
* `new BigInteger(data, isBigEndian: true, isUnsigned: false)` => `(short)0xFE80` => `-384`
* `new BigInteger(data, isBigEndian: false, isUnsigned: true)` => `(int)0x000080FE` => `33022`
* `new BigInteger(data, isBigEndian: true, isUnsigned: true)` => `(int)0x0000FE80` => `65152`

When the most significant byte of the input data does not have the most significant bit set the `isUnsigned` value has no meaning.

Emitting values (reminder, parameter order is `isBigEndian, isUnsigned`; `isBigEndian` label removed to prevent bulleted list from gaining line-wraps)

* `new BigInteger(-32514).ToByteArray(false, isUnsigned: false)` => ` {0xFE, 0x80 }`
* `new BigInteger(-32514).ToByteArray(true, isUnsigned: false)` => `{ 0x80, 0xFE }`
* `new BigInteger(-32514).ToByteArray(false, isUnsigned: true)` => exception
* `new BigInteger(-32514).ToByteArray(true, isUnsigned: true)` => exception
* `new BigInteger(33022).ToByteArray(false, isUnsigned: false)` => `{ 0xFE, 0x80, 0x00 }`
* `new BigInteger(33022).ToByteArray(true, isUnsigned: false)` => `{ 0x00, 0x80, 0xFE }`
* `new BigInteger(33022).ToByteArray(false, isUnsigned: true)` => `{ 0xFE, 0x80 }`
* `new BigInteger(33022).ToByteArray(true, isUnsigned: true)` => `{ 0x80, 0xFE }`

**Comment by bgribaudo** [comment]
Definitely agree that this would be valuable when working on wire protocol drivers!

**Comment by terrajobst** [comment]
Looks good, minor comments:

* We may want to swap the `isBigEndian` and `isUnsigned`
* It's a bit odd to have one type for signed and unsigned, but adding `UBigInteger` seems like overkill

**Comment by karelz** [comment]
FYI: The API review discussion was recorded - see https://youtu.be/OZnaGV2omvI?t=631 (25 min duration)

**Comment by magol** [comment]
I see `isUnsigned` as a double negation. `isUnsigned=false` is for me the same as `is not signed=false`. 
I suggest to change it to `isSigned`.

```C#
partial class BigInteger
{
    // Augment existing
    public BigInteger(
        ReadOnlySpan<byte> value,
        bool isBigEndian=false,
        bool isSigned=true) => throw null;

    // Augment existing
    public bool TryWriteBytes(
        System.Span<byte> destination,
        out int bytesWritten,
        bool isBigEndian=false,
        bool isSigned=true) => throw null;

    // New overload.
    public byte[] ToByteArray(bool isBigEndian=false, bool isSigned=true) => throw null;
}
```
