### ISSUE TITLE
Perf optimization for FirstOrDefault of List<T>

### ISSUE THREAD

**Issue by lechu445** [dotnet/corefx#24585]
Extension method FirstOrDefault that takes predicate as parameter could use native List<T> implementation by calling method Find of an object instance.

So, I propose to add the code below to Enumerable.FirstOrDefault(predicate):
```
List<TSource> simpleList = source as List<TSource>;
if(simpleList != null) return simpleList.Find(item => predicate(item));
```

**Comment by danmosemsft** [comment]
This optimization seems present in FirstOrDefault() but not the predicate form. @JonHanna any reason?

**Comment by justinvp** [comment]
Does it make a measurable improvement? Using `predicate` like that will result in a closure allocation (care will need to be taken to avoid the closure allocation when `source` is not `List<T>`), but maybe that (along with the more efficient enumeration over the array inside `List<T>`) is better than allocating/using an enumerator?

**Comment by JonHanna** [comment]
The optimisation on `IList<T>` covers more cases than this, and in fact was present in netfx before corefx existed.
This only benefits `List`, so isn't as wide ranging, and requires a wrapping of the predicate which might undo the benefit.
There's no harm in seeing what sort of gains or losses it would bring, I suppose.

**Comment by OmarTawfik** [comment]
@lechu445 did we calculate the gains/changes we would see in that case?
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/performance-tests.md

**Comment by lechu445** [comment]
I've done a few tests with a simple console application that uses Stopwatch and I see that in case of `List` there is not a significant performance gain (a few percent). The change with considerable performance results is to create a separate overload
`    public static TSource FirstOrDefault<TSource>(this List<TSource> source, Func<TSource, bool> predicate) => source.Find(predicate.Invoke);`. But I suppose this is not the way it should be done.
Maybe it is worth considering doing this optimisation on compiler side or Refactor suggestions side as it Roslynator does https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1119.md
