### ISSUE TITLE
HttpClient status code - different behavior (Windows / CENT OS)

### ISSUE THREAD

**Issue by deepumi** [dotnet/corefx#24580]
DotNet version - 1.0.1
OS - CENT OS
URL - http://www.switchboard.com
![image](https://user-images.githubusercontent.com/554039/31459668-d775c758-ae91-11e7-9159-34737c344cd2.png)

DotNet version - 1.0.1
OS - Windows 10 OS
URL - http://www.switchboard.com
![image](https://user-images.githubusercontent.com/554039/31459224-8a20d728-ae90-11e7-95d1-85bc99f72b8f.png)

Basically the app does return a status code and redirected URL. In windows it work as expected (return MovedPermanently with redirected URL). However, In linux the HttpClient library return different status code (MethodNotAllowed) and does not return any redirected URL.

Also, tried to verify the same URL in a [third party app ](http://redirectdetective.com/)which work same as  Windows version.
![image](https://user-images.githubusercontent.com/554039/31460192-8d58db86-ae93-11e7-82a2-feecb704f275.png)

Any help would be appreciated.

**Comment by davidsh** [comment]
@deepumi Please attach WireShark traces.  That will make it easier to diagnose this.

cc: @stephentoub

**Comment by deepumi** [comment]
@davidsh Is there any sample code available to generate wireshark traces for .net core console app 
CENT OS or you need just request and response details?

**Comment by davidsh** [comment]
>@davidsh Is there any sample code available to generate wireshark traces for .net core console app
CENT OS or you need just request and response details?

I'm not familiar with running Wireshark on Linux.  But I assume you can simply install it and just run it.

Please also attach your Visual Studio solution showing your repro code, i.e. how you are using the .NET Http APIs, etc.

**Comment by deepumi** [comment]
@davidsh Thank you. Please find the code I am using to make .Net Core Http APIs. 

```csharp
using System;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace hwapp
{
    internal class HttpClientTest
    {
        static void Main()
        {
            var result = MakeHttpRequest("http://www.switchboard.com").GetAwaiter().GetResult();
            Console.WriteLine("Status code ==> " + result.statusCode);
            Console.WriteLine("Location ==> " + result.location);
            Console.WriteLine("Press any key to exit");
            Console.ReadKey();
        }

        private static async Task<(HttpStatusCode statusCode, string location)> MakeHttpRequest(string url)
        {
            var httpClientHandler = new HttpClientHandler
            {
                AllowAutoRedirect = false,
                AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip
            };

            httpClientHandler.ServerCertificateCustomValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;

            using (var client = new HttpClient(httpClientHandler) { Timeout = TimeSpan.FromSeconds(60) })
            {
                client.DefaultRequestHeaders.TryAddWithoutValidation("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8");
                client.DefaultRequestHeaders.TryAddWithoutValidation("User-Agent", "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36");
                client.DefaultRequestHeaders.TryAddWithoutValidation("Accept-Encoding", "gzip, deflate, sdch, br");
                client.DefaultRequestHeaders.TryAddWithoutValidation("Accept-Language", "en-US,en;q=0.8");
                client.DefaultRequestHeaders.CacheControl = new CacheControlHeaderValue { NoCache = true };

                using (var request = new HttpRequestMessage(HttpMethod.Get, url))
                {
                    using (var response = await client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false))
                    {
                        switch (response.StatusCode)
                        {
                            case HttpStatusCode.Redirect:
                            case HttpStatusCode.MovedPermanently:
                            case HttpStatusCode.RedirectKeepVerb:
                            case HttpStatusCode.RedirectMethod:
                                string location = response.Headers.GetValues("Location").LastOrDefault();
                                if (location?.IndexOf("://", StringComparison.Ordinal) == -1 || location?.IndexOf("/", StringComparison.Ordinal) == 0)
                                    location = new Uri(new Uri(url), location).ToString();
                                return (response.StatusCode, location);

                            default:
                                return (response.StatusCode, string.Empty);
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by deepumi** [comment]
@davidsh  Were you able to reproduce the issue from your end?

**Comment by davidsh** [comment]
>@davidsh Were you able to reproduce the issue from your end?

Are you asking about trying the repro on Linux?  If so, the answer is that I have not tried that repro.  @Priya91 would be the one to look at that.

**Comment by stephentoub** [comment]
@deepumi, are you experiencing this with other sites?  This appears to be an issue with the site, not the client.  If I just do:
```
curl www.switchboard.com
```
on Linux, I similarly get back a 405 response code, and if you look at the body of the response, you see this:
```
        <h1>Pardon Our Interruption...</h1>
        <p>
          As you were browsing <strong>www.switchboard.com</strong> something about your browser made us think you were a bot. There are a few reasons this might happen:
        </p>
        <ul>
          <li>You're a power user moving through this website with super-human speed.</li>
          <li>You've disabled JavaScript in your web browser.</li>
          <li>A third-party browser plugin, such as Ghostery or  NoScript, is preventing JavaScript from running. Additional information is available in this <a title='Third party browser plugins that block javascript' href='http://ds.tl/help-third-party-plugins' target='_blank'>support article</a>.</li>
        </ul>
        <p>
          To request an unblock, please fill out the form below and we will review it as soon as possible.
        </p>
```
So it appears the server is detecting something about the client and believes it's a robot.  Similar error happens with `wget`.  And the same message body comes back just using socket connection directly from C#:
```
using System;
using System.Net;
using System.Net.Sockets;
using System.Text;
using System.IO;

internal class Repro
{
    static void Main()
    {
        using (var s = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
        {
            s.Connect(new DnsEndPoint("www.switchboard.com", 80));
            s.Send(Encoding.ASCII.GetBytes(
                "GET / HTTP/1.1\r\n" +
                "Host: www.switchboard.com\r\n" +
                "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\r\n" +
                "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36\r\n" +
                "Accept-Encoding: gzip, deflate\r\n" +
                "Accept-Language: en-US,en;q=0.8\r\n" +
                "\r\n"));
            using (StreamReader reader = new StreamReader(new NetworkStream(s)))
            {
                string line = null;
                while ((line = reader.ReadLine()) != null) Console.WriteLine(line);
            }
        }
    }
}
```
Same with a little go program:
```
package main

import "net/http"
import "fmt"

func main() {
        resp, err := http.Get("http://www.switchboard.com")
        if (err != nil) { panic(err) }
        fmt.Println(resp)
}
```
So this doesn't appear to be a .NET issue.

**Comment by deepumi** [comment]
@stephentoub Thanks,

May I know why the same code works fine in WINDOWS environment and get a different status code? 

Why is the status code different in Linux?

For ex : 
OS - CENT OS
Status Code = **MethodNotAllowed**

OS - Windows 10 OS
Status Code = **MovedPermanently**

**Comment by deepumi** [comment]
@stephentoub 

> are you experiencing this with other sites? 

Yes

**Comment by stephentoub** [comment]
>> are you experiencing this with other sites?
> Yes

Which ones?

**Comment by deepumi** [comment]
@stephentoub I think the below one,

https://www.era.com/

**Comment by stephentoub** [comment]
Having never connected to that site from my Linux box, I just ran this go program:
```go
package main

import "net/http"
import "fmt"

func main() {
        resp, err := http.Get("http://www.era.com")
        if (err != nil) { panic(err) }
        fmt.Println(resp)
}
```
and it produced:
```
stoub@SToubUbuntu17102:~$ go run repro.go
&{405 Method Not Allowed 405 HTTP/2.0 2 0 map[Expires:[Thu, 01 Jan 1970 00:00:01 GMT] Server:[nginx] Vary:[Accept-Encoding Accept-Encoding] Content-Length:[16142] Date:[Tue, 14 Nov 2017 15:42:33 GMT] Edge-Control:[no-store, bypass-cache] Surrogate-Control:[no-store, bypass-cache] Cache-Control:[private, no-cache, no-store, must-revalidate] Content-Type:[text/html; charset=UTF-8]] {0xc420390280} 16142 [] false false map[] 0xc4200d4400 0xc42035cb00}
```

**Comment by deepumi** [comment]
However, same running in windows returns 200 status, that's what confusing

**Comment by stephentoub** [comment]
Are both your Windows and Linux machines on the same network?  Are they both VMs?  Is maybe one of them in a cloud and the other not?  There could be a variety of things the server is picking up on to believe that the client is a bot.

**Comment by stephentoub** [comment]
My previous tests were done on a Linux VM in the cloud.  I just tried it on a local Linux machine, and your repro runs fine on Linux:
```
stoub@stoubhp:~/tmpapp$ dotnet run
Status code ==> MovedPermanently
Location ==> https://www.whitepages.com/?from_switchboard=true
```
So again I think this is more to do with things the server is interpreting about the client than about the client being used.

**Comment by deepumi** [comment]
Only Linux VM is with Azure.

**Comment by stephentoub** [comment]
Yeah.  So most likely the server is seeing the IP address of the client and is deciding that it's a bot, regardless of the OS or client software being used.

**Comment by deepumi** [comment]
@stephentoub - Thank you!
