### ISSUE TITLE
NamedPipeClientStream depends on WaitNamedPipe, which is not supported in Windows Containers

### ISSUE THREAD

**Issue by jiria** [dotnet/corefx#24594]
`NamedPipeClientStream.TryConnect` calls into native `WaitNamedPipe` first to make sure the pipe is available and only then into native `CreateNamedPipeClient`. The problem is that currently `WaitNamedPipe` is not supported from inside of Windows Containers (however `CreateNamedPipeClient` works ok). It fails with `ERROR_FILE_NOT_FOUND`. As such, managed code using `NamedPipeClientStream` is broken in Windows Containers due to the ordering of the calls. This includes Docker.Dotnet library and projects depending on it. Since both these calls happen in a loop which is making sure that the given timeout is not exceeded, we could swap them and call `WaitNamedPipe` only if `CreateNamedPipeClient` fails in a predicable manner first.

**Comment by danmosemsft** [comment]
@jiria can this be closed now?

**Comment by jiria** [comment]
Should we wait until https://github.com/dotnet/corefx/pull/25323 is completed? Ultimately, we need it in 2.0 so I would say this is not resolved until it gets there. But I am open either way, based on how you prefer.

**Comment by pjanotti** [comment]
Leaving this one open until we get it on a servicing branch.

**Comment by pjanotti** [comment]
@jiria this was merged to the servicing branch.
