### ISSUE TITLE
System.Diagnostics.Tests.ProcessStartInfoTests.TestEnvironmentOfChildProcess failed in CI

### ISSUE THREAD

**Issue by v-haren** [dotnet/corefx#24599]
Failed test: System.Diagnostics.Tests.ProcessStartInfoTests.TestEnvironmentOfChildProcess 

Configuration: osx10.12_debug

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/3296/testReport/System.Diagnostics.Tests/ProcessStartInfoTests/TestEnvironmentOfChildProcess/

MESSAGE:
Expected: HUDSON_COOKIE=2b6c4278-574d-442d-ad2f-c878bb995f20, WORKSPACE=/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug, LANG=en_US.UTF-8, BUILD_TAG=jenkins-dotnet_corefx-master-osx10.12_debug-3296, GitBranchOrCommit=*/master, BUILD_NUMBER=3296, JOB_DISPLAY_URL=https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/display/redirect, GIT_PREVIOUS_COMMIT=3143b836af48be68d3b02b45188b134dca25b27c, EXECUTION_DIR=/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/bin/tests/System.Diagnostics.Process.Tests/netcoreapp-OSX-Debug-x64, JENKINS_SERVER_COOKIE=637e320b5b282ff8, HOME=/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/tempHome, XPC_FLAGS=0x0, BranchName=master, SHLVL=7, QualifiedRepoName=dotnet/corefx, BUILD_TIMESTAMP=2017-10-11 21:36:27 PDT, HUDSON_SERVER_COOKIE=637e320b5b282ff8, GithubProjectName=corefx, GIT_BRANCH=origin/master, NODE_LABELS=dci-mac-build-054 dtap osx-10.12, OLDPWD=/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/src/System.Diagnostics.Process/tests, JENKINS_HOME=/jenkins, BUILD_DISPLAY_NAME=#3296, GIT_PREVIOUS_SUCCESSFUL_COMMIT=3143b836af48be68d3b02b45188b134dca25b27c, _=/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/bin/testhost/netcoreapp-OSX-Debug-x64//dotnet, CORECLR_SERVER_GC=0, com.apple.java.jvmTask=CommandLine, JAVA_ARCH=x86_64, HUDSON_URL=https://ci.dot.net/, BUILD_URL=https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/3296/, __BUILDTOOLS_USE_CSPROJ=true, AutoSaveReproEnv=false, MSBuildLoadMicrosoftTargetsReadOnly=true, XPC_SERVICE_NAME=0, MSBuildForwardPropertiesFromChild=TargetPath, JENKINS_URL=https://ci.dot.net/, LC_ALL=en_US.UTF-8, RUNTIME_PATH=/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/bin/testhost/netcoreapp-OSX-Debug-x64/, GIT_COMMIT=882303fc6863f3cfd86c6860c37fd898905d781f, BUILD_ID=3296, PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin, NODE_NAME=dci-mac-build-054, EXECUTOR_NUMBER=0, DOTNET_CLI_TELEMETRY_PROFILE=IsInternal_CIServer;dotnet/corefx, GIT_URL=https://github.com/dotnet/corefx.git, __CF_USER_TEXT_ENCODING=0x0:0:0, JOB_URL=https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/, JAVA_MAIN_CLASS_66742=hudson.remoting.Launcher, HUDSON_HOME=/jenkins, JOB_BASE_NAME=osx10.12_debug, TestEnvironmentOfChildProcess_SpecialStuff=ሴ\n噸, RUN_CHANGES_DISPLAY_URL=https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/3296/display/redirect?page=changes, PWD=/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/bin/tests/System.Diagnostics.Process.Tests/netcoreapp-OSX-Debug-x64, RUN_DISPLAY_URL=https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/3296/display/redirect, JOB_NAME=dotnet_corefx/master/osx10.12_debug, GithubOrgName=dotnet\n

Actual: \n
Expected: True\n
Actual: False

STACK TRACE:
at System.Diagnostics.Tests.ProcessStartInfoTests.TestEnvironmentOfChildProcess() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/src/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs:line 225

**Comment by Jiayili1** [comment]
failed again in outerloop_netcoreapp_osx10.12_release, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_osx_release/221/testReport/System.Diagnostics.Tests/ProcessStartInfoTests/TestEnvironmentOfChildProcess/

**Comment by danmosemsft** [comment]
Too old.
