### ISSUE TITLE
System.Diagnostics.Tests.ProcessCollectionTests.TestThreadCollectionBehavior failed in CI

### ISSUE THREAD

**Issue by v-haren** [dotnet/corefx#24598]
Failed test: System.Diagnostics.Tests.ProcessCollectionTests.TestThreadCollectionBehavior

Configuration: 
osx10.12_debug

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/3296/testReport/System.Diagnostics.Tests/ProcessCollectionTests/TestThreadCollectionBehavior/

MESSAGE:
~~~
System.IndexOutOfRangeException : Index was outside the bounds of the array.
~~~

STACK TRACE:
~~~
at System.Diagnostics.Tests.ProcessCollectionTests.TestThreadCollectionBehavior() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/src/System.Diagnostics.Process/tests/ProcessCollectionTests.cs:line 95
~~~

**Comment by danmosemsft** [comment]
A fatal error occurred, the required library libhostfxr.dylib could not be found at /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/bin/testhost/netcoreapp-OSX-Debug-x64/shared/Microsoft.NETCore.App/9.9.9/

**Comment by Jiayili1** [comment]
failed again in outerloop_netcoreapp_osx10.12_release, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_osx_release/221/testReport/System.Diagnostics.Tests/ProcessCollectionTests/TestThreadCollectionBehavior/

**Comment by danmosemsft** [comment]
Too old.
