### ISSUE TITLE
System.Diagnostics.Tests.ProcessTests.TestBasePriorityOnUnix failed in CI

### ISSUE THREAD

**Issue by v-haren** [dotnet/corefx#24601]
Failed tests:
  * System.Diagnostics.Tests.ProcessTests.TestBasePriorityOnUnix 
  * System.Diagnostics.Tests.ProcessStreamReadTests.TestAsyncErrorStream 

Configuration: osx10.12_debug

Detail:
* https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/3296/testReport/System.Diagnostics.Tests/ProcessTests/TestBasePriorityOnUnix/
* https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/3296/testReport/System.Diagnostics.Tests/ProcessStreamReadTests/TestAsyncErrorStream/

MESSAGE: (System.Diagnostics.Tests.ProcessTests.TestBasePriorityOnUnix)
~~~
System.ComponentModel.Win32Exception : No such process
~~~

STACK TRACE:
~~~
at System.Diagnostics.Process.get_PriorityClassCore() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 196 at System.Diagnostics.Process.get_PriorityClass() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/src/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 466 
at System.Diagnostics.Tests.ProcessTests.TestBasePriorityOnUnix() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs:line 238
~~~

MESSAGE: (System.Diagnostics.Tests.ProcessStreamReadTests.TestAsyncErrorStream)
~~~
Assert.Equal() Failure\n ↓ (pos 0)\nExpected: System.Diagnostics.Process.Tests started ···\nActual: A fatal error occurred, the required libr···\n ↑ (pos 0)
~~~

STACK TRACE:
~~~
at System.Diagnostics.Tests.ProcessStreamReadTests.TestAsyncErrorStream() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/src/System.Diagnostics.Process/tests/ProcessStreamReadTests.cs:line 50
~~~

**Comment by danmosemsft** [comment]
allthese had  A fatal error occurred, the required library libhostfxr.dylib could not be found at /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/bin/testhost/netcoreapp-OSX-Debug-x64/shared/Microsoft.NETCore.App/9.9.9/

**Comment by Jiayili1** [comment]
failed again in OuterLoop_netcoreapp_osx10.12_release, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_osx_release/221/testReport/System.Diagnostics.Tests/ProcessTests/TestBasePriorityOnUnix/

**Comment by karelz** [comment]
@wtgodbe please check test history from @wfurt.
It seems like one off hiccup on OSX in installation of the product (I would expect more tests failed however). If it fails again, we may need to jump on it right away, and check the machine.

Another option is to look at the test and see if we can add more diagnostics logging which could help.

**Comment by wfurt** [comment]
For Helix runs, I see last failure from 2017-05-10

Just a note that there were some emails about Azure troubles. That mar or may not be related.

**Comment by wfurt** [comment]
BTW the last CI link is dead and returns 404.

**Comment by karelz** [comment]
It seems like the product was not installed properly on the machines. It may be some infra hiccup.
If it happens again, please reopen, @wtgodbe will jump on it right away to chase down more detailed machine logs, while they are around.
