### ISSUE TITLE
System.Memory package for netcoreapp2.0 is missing System.Numerics.Vectors reference

### ISSUE THREAD

**Issue by ektrah** [dotnet/corefx#24606]
*Steps to Reproduce*:

1. docker run -it --rm microsoft/dotnet:2.0-sdk
2. mkdir ~/project
3. cd ~/project
4. dotnet new console
5. dotnet add package System.Memory --version 4.5.0-preview1-25812-01 --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
6. `static void Main() { System.SpanExtensions.SequenceEqual(new byte[123], new byte[123]); }`
7. dotnet run

*Expected Behavior*:

No error.

*Actual Behavior*:

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.SpanHelpers.SequenceEqual(Byte& first, Byte& second, Int32 length)
   at System.SpanExtensions.SequenceEqual(Span`1 first, ReadOnlySpan`1 second)
   at project.Program.Main()
```

*Workaround*:

8. dotnet add package System.Numerics.Vectors --version 4.5.0-preview1-25812-01 --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json

**Comment by danmosemsft** [comment]
@ektrah thanks for the great easy repro. The package authoring seems broken. @weshaggard is taking a look.

**Comment by weshaggard** [comment]
I suspect this is caused by @ericstj change in https://github.com/dotnet/corefx/pull/23719.

The issue is caused by the fact that we have a netcoreapp2.0 dependency group without the vectors dependency yet not netcoreapp2.0 library only a netstandard2.0 library. Something in our packaging infra is incorrectly putting a netcoreapp2.0 dependency group.

**Comment by danmosemsft** [comment]
@weshaggard are you planning to look at this one, since @ericstj is out?

**Comment by weshaggard** [comment]
Yes I'm investigating. I've found the error but I'm now trying to see if we have the problem elsewhere which I expect that we do.
