### ISSUE TITLE
Proposal: Span<T>.Sort Extensions

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#24614]
## Span<T>.Sort Extensions

```csharp
public static class SpanExtensions
{
    public static void Sort<T>(this Span<T> span) where T : IComparable<T> { } 
    public static void Sort<T>(this Span<T> span, Collections.Generic.IComparer<T> comparer) { } 
    public static void Sort<T>(this Span<T> span, Comparison<T> comparison) { } 
}
```
**Notes:**
* No offset, length overloads as can slice before sort
* Extensions so general case can be overridden by more more specific types 

e.g.
```csharp
public static void Sort(this Span<byte> span) { } 
public static void Sort(this Span<MyType> span) { } 
```

Mentioned in api review for array sort https://github.com/dotnet/apireviews/blob/master/2017/10-10-GitHub%20issues.md

/cc @stephentoub @KrzysztofCwalina @terrajobst @karelz

**Comment by karelz** [comment]
@benaadams is it on Array type?

**Comment by ektrah** [comment]
Duplicate of #15329

**Comment by benaadams** [comment]
And already approved! 😄 

That was fast 😆
