### ISSUE TITLE
Is System.Net.Sockets a Implement Of NIO?

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#24610]
@anthonywanted commented on [Thu Oct 12 2017](https://github.com/dotnet/core/issues/1025)

# Issue Title

Is System.Net.Sockets an Implement Of NIO?

# General

Just few questions.
Is System.Net.Sockets an Implement of NIO?
In windows, is it an implement of IOCP?
In Linux, is it an implement of epoll?

How about aspnet core?

**Comment by stephentoub** [comment]
System.Net.Sockets supports both blocking and non-blocking sockets, and both synchronous and asynchronous APIs. The asynchronous implementations use completion ports on Windows, epoll on Linux, and kqueues on macOS.

**Comment by anthonywanted** [comment]
Thanks!
