### ISSUE TITLE
NullReferenceException in SqlBulkCopy when setting ColumnMappings with names

### ISSUE THREAD

**Issue by satano** [dotnet/corefx#24638]
We use `SqlBulkCopy` to insert data. In full .NET framework (4, 4.6) it works. The same code in .net core 2 throws `NullReferenceException`. The problem has something to do with column mappings (`SqlBulkCopy.ColumnMappings`). When we set mappings using indexes, everything works. When we set mappings using column names, NRE is thrown. See the attached example.

[SqlBulkCopySample.zip](https://github.com/dotnet/corefx/files/1382531/SqlBulkCopySample.zip)

**Comment by danmosemsft** [comment]
Do you have a callstack @satano ?

**Comment by satano** [comment]
Yes. The callstack is:

```
System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerCommon(Int32 columnCount)
System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
System.Data.SqlClient.SqlBulkCopy.WriteToServer(IDataReader reader)
SqlBulkCopySample.Program.Insert(String message, Action`2 addColumnMappingsAction)
```

**Comment by danmosemsft** [comment]
@gleems

**Comment by danmosemsft** [comment]
@geleems rather

**Comment by satano** [comment]
I looked into it a bit and I think that the fix is simple. Problem really is in `SqlBulkCopy.WriteRowSourceToServerCommon` method on this line:

https://github.com/dotnet/corefx/blob/87ecb7c05300727e46de69905e499ccb8e6befab/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlBulkCopy.cs#L1966

 It is using `_DbDataReaderRowSource`, but in case of own implementation of `IDataReader` this field is `null`.

I can make a Pull Request if you want.
