### ISSUE TITLE
System.Collections.NonGeneric.Performance.Tests failed

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#24637]
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_centos7.1_debug/196/ 

No test result generated, but shows the following issue:

/mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_centos7.1_debug/Tools/tests.targets(481,5): error : One or more tests failed while running tests from 'System.Collections.NonGeneric.Performance.Tests' please check /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_centos7.1_debug/bin/tests/System.Collections.NonGeneric.Performance.Tests/netcoreapp-Linux-Debug-x64/testResults.xml for details! [/mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_centos7.1_debug/src/System.Collections.NonGeneric/tests/Performance/System.Collections.NonGeneric.Performance.Tests.csproj]

**Comment by Jiayili1** [comment]
This issue also exists in outerloop_netcoreapp_rhel7.2_debug, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_rhel7.2_debug/195/

**Comment by Jiayili1** [comment]
Also outerloop_netcoreapp_portablelinux_debug, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_portablelinux_debug/201/

**Comment by danmosemsft** [comment]
Several linux dumps.

https://dumpling.azurewebsites.net/api/dumplings/archived/80b7d06ba27cdca61916ba74f999fb7b57b8a0dd
https://dumpling.azurewebsites.net/api/dumplings/archived/5aac01775da9daa8a6b45d82afd66f13c86cfb42
https://dumpling.azurewebsites.net/api/dumplings/archived/9ad65902d956108709f5ad635bf47eb5074db782

@ianhays or @safern could one of you please crack one of these and get an idea what test it is (and ideally why)

**Comment by safern** [comment]
Sure. I'll take a look later today.

**Comment by stephentoub** [comment]
I fixed this yesterday: https://github.com/dotnet/corefx/pull/24631

**Comment by stephentoub** [comment]
Or at least I fixed the obvious problem, which is in the log:
```
FailFast: You passed an Int32 to Remove that wasn't in the ArrayList.
  Did you mean RemoveAt?  int: 50000  Count: 99999
  
     at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage) in /root/coreclr/src/mscorlib/shared/System/Diagnostics/Debug.cs:line 97
     at System.Collections.ArrayList.Remove(Object obj)
     at System.Collections.Tests.Perf_ArrayList.Remove() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_centos7.1_debug/src/System.Collections.NonGeneric/tests/Performance/Perf.ArrayList.cs:line 353
```

**Comment by danmosemsft** [comment]
Ah yes. @Jiayili1 please reopen this if this test fails again after tomorrow.

**Comment by danmosemsft** [comment]
I added a failure type for FailFast so I won't miss it agian.

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_centos7.1_debug/failure-cause-management/b9589c5c-b3e3-4466-9114-8f806d1dc8e5/
