### ISSUE TITLE
Update tzfile parsing in TimeZoneInfo to V2 and create AdjustmentRules correctly for Linux

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#2465]
I’ve come across a big difference in the Time Zone adjustment rules between Windows and Linux.
 
On Windows, the public type TimeZoneInfo.AdjustmentRule defines the structure of the data stored in the registry.
 
Basically, time zone adjustment rules are 100% geared around daylight savings time.
The AdjustmentRule defines:
1.	A span of time (DateStart to DateEnd) that the rule is valid
2.	An offset (DaylightDelta) from the BaseUtcOffset that should be used when daylight savings time is in effect.
3.	And then 2 “TransitionTime” structures DaylightTransitionStart and DaylightTransitionEnd, that describe when inside the span of time (1.) that Daylight savings time is in effect.

However, on Linux, time zone information is stored differently and isn’t based solely on daylight savings time.  It shows every single time the time changed in the time zone.  For the US, you get 2 entries for every year in time zones that support DST.  The last 3 time transitions in Moscow haven't been logged as daylights savings transitions, as they were supposed to be permanent transitions:

Transition Date | Transition Offset
---------------------|---------------------
03/27/2010 23:00:00 | 04:00:00 DST
10/30/2010 23:00:00 | 03:00:00
03/26/2011 23:00:00 | 04:00:00
10/25/2014 22:00:00 | 03:00:00

The structure of data in the tzfile is:
1.	A “Transition Date”, which is the date and time that the time offset changed
2.	A “Transition Offset”, which is the offset from UTC that went into effect on the Transition Date
3.	A value whether this offset is to be considered “daylight savings time” or not.

The issue is, given the structure of AdjustmentRule, there is no way to express these types of offset transitions, since AdjustmentRule is based on daylight savings time.

To solve this, we need to add a "StandardDelta" property to AdjustmentRule that can be used when a non-daylight savings transition was made.  Then we need to update the AdjustmentRule creation code for Linux to correctly fill out a new AdjustmentRule for each transition.
To handle DateTimes less than the first transition time, we should make an AdjustmentRule based on the first standard-time ttinfo structure in the file.
To handle DateTimes greater than the last transition time, we need to parse the V2 information, which has the POSIX style rule:
http://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html
format: std offset dst [offset],start[/time],end[/time].
ex. EST+5EDT,M3.2.0/2,M11.1.0/2
For V1 tzfiles, we should just use the last transition noted in the file for dates greater than what is expressed.

**Comment by jskeet** [comment]
As it happens, I've just been writing code to parse the zic output as part of tzvalidate (https://github.com/nodatime/tzvalidate - could well be useful for validation!)

The actual file format of the transition data is a little more complicated than described above, as there are "transition types" and each transition has an index into that type.

It's important to note that there are some "transitions" which aren't useful in any meaningful way - they're a transition in terms of one type to another, but they don't change the tuple of wall-offset/is-daylight/name - they just change whether the transition was observed at a standard/wall/UTC offset. When I've committed the code I'm currently writing in ZicDump, I can point out where I'm checking it.

It's also worth being aware that while most time zones have a "big bang" transition to indicate their standard time before the first transition, a few don't (PST8PDT, WET etc).

There's a horrible mixture of cases to consider here:

- Different versions of deployed data (i.e. different tz releases)
- Different versions of deployed code (i.e. zic interpreting data differently)
- Different versions of the file (V1, V2, V3 etc)

Do we definitely want to use the time zone data of the system rather than including our own (and allowing it to be updated)?

**Comment by eerhardt** [comment]
@ellismg, @joshfree and I had a discussion on including our own data, but we felt reading the information from the OS was a better way to go.  The reasoning is that when time zones are changed, users just need to apply the patch to their OS to get the updated information.  If we were to include our own copy, it would need to be updated in 2 places - the OS and our copy.

**Comment by eerhardt** [comment]
> It's also worth being aware that while most time zones have a "big bang" transition to indicate their standard time before the first transition, a few don't (PST8PDT, WET etc).

According to the tzfile man page:

>       localtime(3)  uses the first standard-time ttinfo structure in the file
       (or simply the first ttinfo structure in the absence of a standard-time
       structure)  if  either tzh_timecnt is zero or the time argument is less
       than the first transition time recorded in the file.

On my Ubuntu 14.04 machine, the WET tzfile starts like this:
Transition Date                 Transition Offset
04/03/1977 01:00:00                     01:00:00 DST
09/25/1977 01:00:00                     00:00:00
04/02/1978 01:00:00                     01:00:00 DST
10/01/1978 01:00:00                     00:00:00
04/01/1979 01:00:00                     01:00:00 DST

and contains 2 ttinfo structures:
tt_gmtoff             tt_isdst
{1:00:00}            true
{0:00:00}            false

The way I interpret the man page is that for DateTimes before 04/03/1977 01:00:00, the offset should be {0:00:00}, since that is the first **standard** time ttinfo.  And if all the ttinfo structures were tt_isdst == true, then simply the first one should be used.

The PST8PDT file is similar - except it has 4 ttinfo sturctures, of which only 1 is standard time, which would be used.

Am I interpreting this correctly?

**Comment by jskeet** [comment]
> The reasoning is that when time zones are changed, users just need to apply the patch to their OS to get the updated information.

That's a big "just". That means the users aren't in control of their own destiny - they have to wait for their OS vendor to ship the new time zone files, which can be hard to predict and can often come quite a long time after the change has been announced. In some countries, changes are announced very late - potentially leaving local end users looking at the wrong time. There's a thread on the IANA mailing list about exactly this problem at the moment. Admittedly users (devs) *could* download the IANA code and data, and run zic themselves - but I would like to think we could do better than that :)

Personally I think it's really, really useful to be able to specify a data source explicitly. You could always fall back to the OS data by default if you want, of course.

> Am I interpreting this correctly?

Yes, I believe so. You just need to be aware of it and not be lulled into a false sense of security by all the other time zones having a "big bang" transition.

Mind you, the man page doesn't make sense in terms of talking about "the first ttinfo structure" if `tzh_timecnt` is 0... given that `tzh_timecnt` is the count of `ttinfo` structures!

**Comment by eerhardt** [comment]
> Personally I think it's really, really useful to be able to specify a data source explicitly. You could always fall back to the OS data by default if you want, of course.

I just wrote the code last night to respect the TZDIR environment variable.  https://github.com/eerhardt/coreclr/commit/c1a1817276abd6dea069437927a9686865a3d8c4
If someone really wanted to specify their own data source, they can set the TZDIR variable to point to their own files.  Does that work?

> Mind you, the man page doesn't make sense in terms of talking about "the first ttinfo structure" if  tzh_timecnt  is 0... given that  tzh_timecnt  is the count of  ttinfo  structures!

tzh_timecnt is the count of transitions stored in the file.  The count of ttinfo structures is specified by tzh_typecnt.

**Comment by jskeet** [comment]
> If someone really wanted to specify their own data source, they can set the TZDIR variable to point to their own files. Does that work?

Yup, I think so. It's a little inconvenient having to fetch the code, build it, fetch the data, run zic - but it's definitely good in terms of 

> tzh_timecnt is the count of transitions stored in the file. The count of ttinfo structures is specified by tzh_typecnt.

Whoops, of course. Although if timecnt is 0, it would be surprising to have any ttinfo entries, I think. (I haven't checked zic.c to see whether it could ever produce one. Even if it doesn't now, it's possible that it's done so in the past - it would be a reasonable way of representing a fixed time zone.)

My own tzvalidate code works slightly differently - it tries to find the ttinfo associated with the earliest transition into standard time. Maybe I should change that... (In practice it makes no odds right now.)

**Comment by eerhardt** [comment]
> My own tzvalidate code works slightly differently - it tries to find the ttinfo associated with the earliest transition into standard time. Maybe I should change that... (In practice it makes no odds right now.)

I think that is a good idea because some of the data stored in the "V2" section of the tzfiles have a ['LMT'](https://en.wikipedia.org/wiki/Local_mean_time) ttinfo that isn't used in any of the transitions, but it is the first ttinfo in the file.  This is perfect to use in early times, because that was the local time used before standard time came.
For example, the Australia/Sydney has the following ttinfo structures:
tt_gmtoff     tt_isdst     Abbreviation
 {10:04:52}    false          LMT
 {11:00:00}    true           AEDT
 {10:00:00}    false          AEST
 {11:00:00}    true           AEDT
 {10:00:00}    false          AEST

**Comment by jskeet** [comment]
Aha. Good call. Done :) (Although in the data I'm looking at, it looks like Australia/Sydney does use the LMT type, for the first "big bang" transition.)

Let me know if you'd like me to port the tzvalidate "time zone dumping" code to TimeZoneInfo for you to test this, btw. So far I've found discrepancies in every platform I've run it against.

**Comment by mj1856** [comment]
There's a lot more to consider on this topic.

- Several time zones that have had two-sets of DST periods in the same year, such as Egypt and Morocco that have "suspended" DST for Ramadan.

- Transitions can occur for other reasons than DST.  For example, Samoa's 2011 switch to the other side of the international date line, or Russia's 2014 changes of base offset.

- DST changes for time zones in the southern hemisphere usually start in one year and end in the next.

- Windows intentionally writes some of it's transitions to the registry as 23:59:59 that really occur at 00:00:00 the next day.  Tzdb data probably doesn't have this concern, but we should make sure that there's no code in `TimeZoneInfo` that tries to counteract this problem.

**Comment by mj1856** [comment]
Also, WRT to the following:

> ... To solve this, we need to add a "StandardDelta" property to AdjustmentRule that can be used when a non-daylight savings transition was made.

This was already discussed and approved in #1450.  I just haven't had the time to address it yet.

But thinking a bit more on this, I think the design of the `AdjustmentRule` class needs to be changed or expanded to accommodate the variety of transitions rules that occur.   One way would be to create a base class or interface for different types of adjustment rules.

**Comment by mj1856** [comment]
> @ellismg, @joshfree and I had a discussion on including our own data, but we felt reading the information from the OS was a better way to go. The reasoning is that when time zones are changed, users just need to apply the patch to their OS to get the updated information. If we were to include our own copy, it would need to be updated in 2 places - the OS and our copy.

I think this needs more consideration than just a short discussion.  IMHO, this is a big problem with the current design.   Developers need to be able to update their applications with current time zone data without regard to OS patching.

This is a current problem with .NET in Azure.  You can't patch the OS with time zone updates when you don't have control of the OS.  Azure Cloud Services and Web Apps have to wait for the next guest OS update.  Even then, the time zone updates that are put out as hotfixes don't always make it in.  Only the "cumulative updates" are guaranteed to be there, and only in the subsequent guest OS release.   Developers affected by short-notice time zone updates really don't have a choice except to use Noda Time instead of `TimeZoneInfo`.

**Comment by tarekgh** [comment]
@mj1856 I agree with you regarding updating the OS data is not available option for the applications all the time. I think having the Provider model (which we talked about it offline) would be a good direction to fix most of such issues we are talking about and we can look at what need to be adjusted in the current exposed APIs and the internal implementation too.

**Comment by ellismg** [comment]
FWIW, I am not opposed to a provider model.  I think a model where we allow all platforms to carry their own version of tzinfo data is very interesting and should be explored.

My general point was that, by default, we should be going to the OS provided data (just like we do on Windows).  The framework shouldn't ship it's own copy.  If this can be harmonized with the provider model (e.g. a default provider which just hits the registry on Windows and the default tzinfo store on Linux) then that's great and we should totally do it.

I do hope that we don't block progress on this issue however.  I would like us to bring cross-plat to parity with Windows and then move all the platforms atomically.  I don't believe we need to design the provider model before addressing this bug.

**Comment by mj1856** [comment]
Sounds good.  Thanks.

**Comment by tarekgh** [comment]
@ellismg I think we are in same page. what @eerhardt did is good so far. I don't think anything is blocking. the provider and exposing the rules is something can comes later. what @eerhardt did is enable TZI which will get cross platform support working.

**Comment by jskeet** [comment]
Is this at a stage where it would be worth me writing a TimeZoneInfo-based version of tzvalidate?
(http://github.com/nodatime/tzvalidate as a reminder)

**Comment by eerhardt** [comment]
@jskeet - Not quite yet.  I'm actively working on transferring the tzfile info into TimeZoneInfo and AdjustmentRules.  It should hopefully be a couple days to a week. (fingers crossed).

**Comment by tarekgh** [comment]
maybe start writing the TZvalidate in parallel will be good too as it can be used to test @eerhardt work and hopefully can trigger issues with TZI that we need to fix. does the tzvalidate work against defined data? I mean you compate it with IANA data?  or it just validate the calculation regardless of the data?

**Comment by jskeet** [comment]
Each tzvalidate tool basically does its own thing in terms of obtaining data - some (ICU4J, Java 7, Java 8, Ruby) dump whatever the platform provides by default. Others (zic, Joda Time, Noda Time) allow you to specify a data source - for Joda Time and Noda Time that's the tz input; for zic it's zic output (i.e. you run zic against a directory, then run zicdump afterwards).

You then compare the output of multiple tools against each other - ideally resulting in total equality.

I'll start off by just using whatever TimeZoneInfo.GetSystemTimeZones does, but we can then work out how to point it at a specific data source when we know what that integration code looks like. I'll try to make a start on it tomorrow - I've got enough examples now that it shouldn't be too hard :)

**Comment by jskeet** [comment]
First pass is done.
https://github.com/nodatime/tzvalidate/commit/945207dbd25849f4b39e48891d52f836dc9430bc

Let me know I can usefully try it out against any more recent code.

**Comment by tarekgh** [comment]
@jskeet that is great start. we may need to think if we need to move this validator to one of the FX repos too

**Comment by eerhardt** [comment]
Here's my proposed design for this issue.  @tarekgh, @jskeet, @mj1856, @joshfree, @ellismg please let me know if you have any feedback.

In order for the TimeZoneInfo class to work correctly on Linux, we need to take [tzfile information](http://man7.org/linux/man-pages/man5/tzfile.5.html) and transpose it to TimeZoneInfo.AdjustmentRule instances.

Basically, the AdjustmentRule class is geared around daylight savings time.
 The AdjustmentRule defines:
 1. A span of time (DateStart to DateEnd) that the rule is valid
	- These are Date-only values, no "time" is allowed
 2. An offset (DaylightDelta) from the BaseUtcOffset that should be used when daylight savings time is in effect.
 3. And then 2 “TransitionTime” structures DaylightTransitionStart and DaylightTransitionEnd, that describe when inside the span of time (1.) that Daylight savings time is in effect.
4. Recently an internal-only property "BaseUtcOffsetDelta" was added to AdjustmentRule, to handle the situation when the time zone offset changed for non-DST reasons.

However, on Linux, time zone information is stored differently and isn’t based solely on daylight savings time. It shows every single time the offset changed in the time zone. For the US, you get 2 entries for every year in time zones that support DST. The last 3 time transitions in Moscow haven't been logged as daylights savings transitions, as they all are considered "standard time", and not daylight savings:

Transition Date | Transition Offset
---------------------|---------------------
03/27/2010 23:00:00 | 04:00:00 DST
10/30/2010 23:00:00 | 03:00:00
03/26/2011 23:00:00 | 04:00:00
10/25/2014 22:00:00 | 03:00:00

In order to convert tzfile information into AdjustmentRule objects, the following approach will be taken.

	1. For all datetimes before the first transition in the file (which is usually in the late 1800s to early 1900s), an AdjustmentRule will be created with DateStart = DateTime.Min and DateEnd = the date of the first transition.  The offset used will be taken from the first standard time transition info object ("ttinfo"), or the first ttinfo if there are no standard time transitions.
	2. For each transition noted in the tzfile, a single AdjustmentRule will be created to represent that transition.  DateStart = the date of the n - 1 transition and DateEnd = the date of the nth transition.  If the transition is designated as tt_isdst = true, then the DaylightDelta field will be set to the difference between the TimeZoneInfo.BaseUtcOffset and the offset noted in the ttinfo object.  If the transition is designated as tt_isdst = false, then the (currently internal) property BaseUtcOffsetDelta will be set to the difference between TimeZoneInfo.BaseUtcOffset and the offset in ttinfo.
	3. After the last transition in the tzfile, one of two approaches is used.
		a. If the tzfile specifies a POSIX-TZ-environment-variable-style string, use it for handling datetimes after the last transition.
			i. This POSIX style string is similar to our current AdjustmentRule structure:
			ii. std offset dst [offset],start[/time],end[/time]
			iii. ex. EST+5EDT,M3.2.0/2,M11.1.0/2
		b. If there isn't a POSIX style string, continue the last transition offset until DateTime.Max

Two changes will need to be made to AdjustmentRule in order to make this data work.
	1. AdjustmentRule will need to allow UTC DateTimes that specify a date and a time portion for the DateStart and DateEnd properties. This will allow the code to know precisely when the offset changed.
	2. AdjustmentRule will need an extra boolean - "IsFixedAdjustment" to specify that this rule changes the time zone offset for the whole time it is in effect, and there are no other offset changes during the time period.
		a. We could tell this some other way, by coming up with some special convention, like if DaylightTransitionStart and End are set to some special/sentinel value.

So, if the above table was the info we received out of the tzfile, the following AdjustmentRule instances would be created:

TimeZoneInfo.BaseUtcOffset 03:00:00
AdjustmentRule #1:
         DateStart 1/1/0001 12:00:00 AM
         DateEnd 03/27/2010 23:00:00
         BaseUtcOffsetDelta 00:00:00 // first standard time transition was UTC+3, so this is set to 0
         DaylightDelta 00:00:00
         DaylightTransitionStart – default(TransitionTime)
         DaylightTransitionEnd – default(TransitionTime)
AdjustmentRule #2:
         DateStart 03/27/2010 23:00:00
         DateEnd 10/30/2010 23:00:00
         BaseUtcOffsetDelta 00:00:00
         DaylightDelta 01:00:00
         DaylightTransitionStart – default(TransitionTime)
         DaylightTransitionEnd – default(TransitionTime)
AdjustmentRule #3:
         DateStart  10/30/2010 23:00:00
         DateEnd 03/26/2011 23:00:00
         BaseUtcOffsetDelta 00:00:00
         DaylightDelta 00:00:00
         DaylightTransitionStart – default(TransitionTime)
         DaylightTransitionEnd – default(TransitionTime)
AdjustmentRule #4:
         DateStart  03/26/2011 23:00:00
         DateEnd 10/25/2014 22:00:00
         BaseUtcOffsetDelta 01:00:00
         DaylightDelta 00:00:00
         DaylightTransitionStart – default(TransitionTime)
         DaylightTransitionEnd – default(TransitionTime)
AdjustmentRule #5:
         DateStart  10/25/2014 22:00:00
         DateEnd 12/31/9999 23:59:59
         BaseUtcOffsetDelta 00:00:00
         DaylightDelta 00:00:00
         DaylightTransitionStart – default(TransitionTime)
         DaylightTransitionEnd – default(TransitionTime)

**Comment by tarekgh** [comment]
I think the proposal is reasonable to me. 

one small thing we may do is change the BaseUtcOffsetDelta instead to be the delta from the current UTC offset to be the actual utc offset in the period of this rule. this may simplify the calculation a little bit more and that what we'll need to expose eventually when we expose the adjustment rule class. 
Note this change doesn't have to be done now but if this is simple enough you may do it with your change. 

for IsFixedAdjustment, please correct me if I misunderstood anything here. this field will be useful only if there is no daylight saving in such rule period. right? if so we can detect this case when we have m_daylightDelta is zero. and that will tell the rule is no daylight saving and only the UTC offset is changed.

**Comment by eerhardt** [comment]
> for IsFixedAdjustment, please correct me if I misunderstood anything here. this field will be useful only if there is no daylight saving in such rule period. right?

No it is useful even when daylight savings is on.  See AdjustmentRule # 2 above.
IsFixedAdjustment doesn't have anything to do with whether daylight savings was on or off.  It simply says that this AdjustmentRule is "fixed" (or static or unchanging) by only changing the offset at the DateStart through the DateEnd, and never changes the offset in between.  So even when DST is on, we still need to say this AdjustmentRule is "fixed" to know that the offset never changes in between DateStart and DateEnd.

**Comment by eerhardt** [comment]
> one small thing we may do is change the BaseUtcOffsetDelta instead to be the delta from the current UTC offset to be the actual utc offset in the period of this rule.

My only reservations about this proposal are that it would be inconsistent with the DaylightDelta property and the name might have to be changed.  DaylightDelta is the offset from TimeZoneInfo.BaseUtcOffset, it isn't the total offset to use during DST.  Also, it feels correct that AdjustmentRule.BaseUtcOffset**Delta** should actually be the delta from TimeZoneInfo.BaseUtcOffset.

**Comment by eerhardt** [comment]
@jskeet - With https://github.com/dotnet/coreclr/pull/1352, the main line scenarios are now working for TimeZoneInfo on Linux (ConvertTime, IsDaylightSavings, IsAmbiguous/Invalid, GetUtcOffset).  However, TimeZoneInfo.GetSystemTimeZones() is not yet implemented.  That is the next feature I'm going to work on.

I see your tzvalidate code requires GetSystemTimeZones to work, so after my next PR we will be able to run tzvalidate on TimeZoneInfo on Linux.  But, if you wanted to hardcode the timezones and use FindSystemTimeZoneById for now, that should work with https://github.com/dotnet/coreclr/pull/1352.

**Comment by eerhardt** [comment]
@jskeet - TimeZoneInfo is now fully functional on Linux.  Test away with tzvalidate and please log any issues that come up.

**Comment by jskeet** [comment]
Great, thanks - will need to work out how to get a fully-functional dev setup first, but will see what I can do. Is there a way of pointing it at a particular directory of tz data?

**Comment by eerhardt** [comment]
Yes, you can point to your own directory of tz data by setting the TZDIR environment variable to the directory that contains all the tzfiles and the zone.tab file.
Let me know if you have any questions setting up the dev environment.

**Comment by jskeet** [comment]
Okay, I've managed to build it and get a dump out. I've run into two problems...

- Specifying TZDIR doesn't work for me. I've downloaded release 2015f, and run `make TOPDIR=/home/jon/tz/install install`... but then if I use `TZDIR=/home/jon/tz/install/etc/zoneinfo` then `TimeZoneInfo.GetSystemTimeZones()` returns an empty collection. Using `strace` I've found that it *is* opening all the files I'd expect it to, so I'm not sure what's wrong.

- Lots of transitions are *1 tick* off - they occur one tick before they should. Sample code for that:

```csharp
using System;

class Test
{
    static void Main()
    {
        var zone = TimeZoneInfo.FindSystemTimeZoneById("Africa/Casablanca");
	// Theoretical transition time
	var after = new DateTime(2011, 7, 30, 23, 0, 0, 0, DateTimeKind.Utc);
	var before = after.AddTicks(-2);
	var mid = after.AddTicks(-1);
	
	// Should print 01:00:00, 01:00:00, 00:00:00
	// Actually prints 01:00:00, 00:00:00, 00:00:00
	Console.WriteLine(zone.GetUtcOffset(before));
	Console.WriteLine(zone.GetUtcOffset(mid));
	Console.WriteLine(zone.GetUtcOffset(after));
    }
}
```

**Comment by eerhardt** [comment]
> Specifying TZDIR doesn't work for me. I've downloaded release 2015f, and run  make TOPDIR=/home/jon/tz/install install ... but then if I use  TZDIR=/home/jon/tz/install/etc/zoneinfo  then  TimeZoneInfo.GetSystemTimeZones()  returns an empty collection. Using  strace  I've found that it is opening all the files I'd expect it to, so I'm not sure what's wrong.

I debugged this issue this morning.  The problem is that the 2015f version of the tzdata contains an initial "Transition Time" that is out of order.  The beginning of the tzfile looks like the following:

Transition Time| Transition Offset
---------------------|---------------------
01/01/1970 00:00:00 | -05:50:36
11/18/1883 18:00:00 | -06:00:00
03/31/1918 08:00:00 | -05:00:00 DST
10/27/1918 07:00:00 | -06:00:00

Notice the first entry is for 1970, and then the next entry is for 1883.  This breaks the documentation of the 'man tzfile':

> The above header is followed by tzh_timecnt four-byte  values  of  type long,  **sorted  in  ascending order**.  These values are written in "standard" byte order.  Each is used as a transition time  (as  returned  by time(2)) at which the rules for computing local time change.

This causes the TimeZoneInfo parsing code to throw an exception because it is assuming these transitions are sorted in ascending order.

Is this an intentional change in the tzfiles?  I skimmed the "NEWS" file, but didn't see any reference to this change.

**Comment by jskeet** [comment]
Doesn't sound like it - sounds like a bug, and worth reporting on tz@iana.org.

Note that this almost certainly isn't a problem in tzdata itself, but in the output of zic. My guess is that the first transition isn't really meant to be a transition at all - the changes of it "just happening" to be at the Unix epoch are tiny! Which zone is this, by the way? Or is it all of them?

**Comment by eerhardt** [comment]
> Lots of transitions are 1 tick off - they occur one tick before they should.

I debugged this, and it is an issue in the `CheckIsDst` method when using the "NoDaylightTransition" AdjustmentRules on Linux.  When we build the AdjustmentRules up, we set the StartDate to be the Transition Time that comes from the tzfile, and we set the EndDate to the be (the next Transition Time - 1 tick).  That way the next AdjustmentRule goes into effect at the exact transition time. The issue is that the code in CheckIsDst uses a less than operator when comparing the endTime, but for these rules it should be less than or equal to:

```C#
            if (startTime > endTime) {
                // In southern hemisphere, the daylight saving time starts later in the year, and ends in the beginning of next year.
                // Note, the summer in the southern hemisphere begins late in the year.
                isDst = (time < endTime || time >= startTime);
            }
            else {
                // In northern hemisphere, the daylight saving time starts in the middle of the year.
                isDst = (time >= startTime && time < endTime);
            }
```

Because of this check, 1 tick before the transition is going to fail the check `time < endTime`.

I have logged #2788 for this issue.

**Comment by eerhardt** [comment]
> Doesn't sound like it - sounds like a bug, and worth reporting on tz@iana.org.

Sending the email now.

> Which zone is this, by the way? Or is it all of them?

The one I referenced above is America/Chicago.  But doing a quick search it appears to be all of them.

**Comment by mj1856** [comment]
The only zone I can find in the tzdata with a `-05:50:36` offset is [`America/Chicago`](https://github.com/eggert/tz/blob/2015f/northamerica#L336), and it's not out of sequence.  Whatever is assigning the epoch 1/1/1970 to the initial transition time is invalid.

There's no implied initial transition in the data.  That's part of why the columns are labeled with "until" dates.  The initial entry being the LMT value reads as "Until 1883 Nov 18 12:09:24, the local mean time offset was -5:50:36".

There's no bug in the data.

**Comment by mj1856** [comment]
Was that output showing the 1/1/1970 transition coming from zic/zdump?

**Comment by eerhardt** [comment]
> Was that output showing the 1/1/1970 transition coming from zic/zdump?

That output showing 1/1/1970 is from parsing the bytes directly.

**Comment by mj1856** [comment]
So we might think the bug is in the zic compiler, but it might also be in the way we're interpreting the bytes.  Given that all the data defined with "until" dates, it may be that the first transition in the data will always show as 0, but is not meant to be used.

**Comment by jskeet** [comment]
As a single datapoint, my ZicDump program shows the normal output for America/Chicago:

```
America/Chicago
Initially:           -05:50:36 standard LMT
1883-11-18T18:00:00Z -06:00:00 standard CST
1918-03-31T08:00:00Z -05:00:00 daylight CDT
1918-10-27T07:00:00Z -06:00:00 standard CST
1919-03-30T08:00:00Z -05:00:00 daylight CDT
```

Of course, it may depend on which version of the data in the file is being read - I read the *second* copy of the data in each file, but I believe there are three copies...

**Comment by eerhardt** [comment]
The people on the tz@iana.org alias were really helpful and informed me about the "big bang" transition that was introduced in the tzdata release 2014c.  The tzfiles on my Unbuntu machine were from an older version of tzdata, so I wasn't seeing these "big bang" transitions.  The reason I was seeing the Epoch time as the first transition was because of an overflow in the code I was using.

I logged https://github.com/dotnet/corefx/issues/2816 to fix this issue.  Thank you, Jon, for finding this issue.
