### ISSUE TITLE
System.ComponentModel.Win32Exception doesn't match ref contract

### ISSUE THREAD

**Issue by Rew** [dotnet/corefx#24650]
I encountered an issue while working with the corefx libraries using custom tooling.  It's possible that the following scenario is allowed, but here's what I'm seeing.

In M.Win32.Primitives the Win32Exception class has the GetObjectData method defined in the ref contract.  The method was removed from the implementation in https://github.com/dotnet/corefx/commit/9eafffc6054c8f039d788465621bcfd49a379ca1.  Assemblies in corefx build against the ref contract and have a memberref to a non existing member.  It is still implemented by a base type, but shouldn't this cause method binding errors?  Is this a case that is allowed by CIL spec or is this actually an error hidden by coreclr?

Edit for clarity:  This isn't a binding question, it's more of a CIL decoding question.  The particular error I encountered has a MemberReference token to the method in question.  AFAIK a CIL decoder shouldn't need to do method resolution while trying to decode the stream.

Edit:
The method is also explicitly overridden by Win32Exception in the netstandard contract.

**Comment by Rew** [comment]
After reviewing the spec pertaining to member ref row and methodspec sig I am unsure if this is an issue.  The method can be resolved based on the sig.  I believe this is the only method referenced by netstandard that has this implementation.

**Comment by karelz** [comment]
It seems to be back in https://github.com/dotnet/corefx/commit/e3eae2c20350d707d721940c2c90586b90e7fd60#diff-f65dfa34c672aea90ad744fefab3020f

See also code:
https://github.com/dotnet/corefx/blob/2172d3f9c324ac8add4f34a44597911049e58092/src/Microsoft.Win32.Primitives/src/System/ComponentModel/Win32Exception.cs#L70-L79

**Comment by danmosemsft** [comment]
@weshaggard can you confirm @Rew 's understanding is correct, that our ref .cs must always explicitly include overrides.

**Comment by Rew** [comment]
I found several other cases where the implementation matches this case.  Including at least one class where the ref implementation was specifically newslot and doesn't exist.  If this isn't allowed by spec, is there an issue with the coreclr implementation or missing test coverage?  Should api compat checks find this?

**Comment by danmosemsft** [comment]
If it's a problem, yes apicompat should be finding it. I defer to @weshaggard

**Comment by weshaggard** [comment]
>@weshaggard can you confirm @Rew 's understanding is correct, that our ref .cs must always explicitly include overrides.

Refs don't need to always include overrides but we often do include them if any of the implementations have an override. There are plenty of cases where we have overrides in refs but not in some implementations and that is completely legal. At runtime we do a virtual dispatch to find the correct method to call so if the class doesn't have this method the base method will be called instead.

**Comment by Rew** [comment]
@weshaggard thanks for the explanation.  It's clear that ecma didn't really cover the concept of facade assemblies and cases like this existing.  The runtime implementations of .Net and netcore are essentially the standard anyways, regardless of spec.  I did have 2 questions on runtime implications of this that should clear up any ambiguity here.

By virtual dispatch are you referring to a virtual method stub existing for the method in question and it dispatching to the base method?  Or is it done in JIT where the actual call goes to the base method stub?  I guess the core of this question is does the method exist in the runtime type system?  On this point, would a ldtoken that had a memberref to the method (i.e. delegate creation) point at an inferred method created in the type system, or would such a ldtoken call point at the base method?

The second question relates to newslot.  I'm not sure how this case would be implemented. Consider the following contract:

```
public class Test1 { public virtual void SomeMethod(); }

public class Test2 : Test1 { public new virtual void SomeMethod(); }
```

If Test2.SomeMethod has no implementation, which method would be called in the following consumer code?  Test1.SomeMethod is clearly what should be called based on the contract, however in this case Test2.SomeMethod may never have existed at runtime.  In this case the runtime would (incorrectly?) call Test3.SomeMethod.  

```
public class Test3 : Test2 { public override void SomeMethod(); }

class Program
{
    static void Main()
    {
        Test1 obj = new Test3();
        obj.SomeMethod();
    }
}
```

This is clearly a niche case and it does not seem likely to exist in many cases.  Especially since it is easy to get around for the API designer when it matters.  I'd still be able to live with an answer of .NET works that way since it seems like a very small potential for issues.  Unless facades become the next big thing for API developers, then who knows.

**Comment by weshaggard** [comment]
Unfortunately I don't know the exact details of how the runtime handles these, but I will give you some general answers. @jkotas can probably give you more specific details.

>By virtual dispatch are you referring to a virtual method stub existing for the method in question and it dispatching to the base method? 

By virtual dispatch I mean the runtime will create a vtable for each object and these vtables have a slot for ever virtual method and pointers to the correct methods to call when make a call to virtual method. I don't think it creates a method stub for override slots it just points to the closest base class that contains the method.

>If Test2.SomeMethod has no implementation, which method would be called in the following consumer code?

@jkotas can correct me if I'm wrong but I believe in your sample code Test1.SomeMethod will be called because that is the type of your obj. The only time the newslot Test2.SomeMethod will be called is if your object type is Test2.

**Comment by jkotas** [comment]
>  Is this a case that is allowed by CIL spec or is this actually an error hidden by coreclr?

Yes, this is allowed by the spec. Look for `I.12.4.1.3 Computed destinations` or `This implements “call base class” behavior.` in http://www.ecma-international.org/publications/standards/Ecma-335.htm

>  I believe in your sample code Test1.SomeMethod will be called 

I think so as well.
