### ISSUE TITLE
the Package: System.Text.Encoding.CodePages (ver:4.4.0) cannot be published

### ISSUE THREAD

**Issue by ringrid** [dotnet/corefx#24657]
I found this package of version 4.4.0 cannot be publish when I use "dotnet publish".
when I change to version 4.3.0, It's ok, It has rutimes\win and runtimes\unix.
for version 4.4-preview, it has only runtimes\win, no runtimes\unix.

**Comment by tarekgh** [comment]
@ringrid could you tell what version of net core you are targeting in your app? if you can share a simple project we can look at that will be good. 

CC @weshaggard

**Comment by ringrid** [comment]
@tarekgh my dotnet core info:
Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by ringrid** [comment]
@tarekgh 
I found it was normal in console app, This problem only occurs in web applications.
My steps are as follows：
1、dotnet new web
2、dotnet add package System.Text.Encoding.CodePages -v 4.4.0
3、Add simple code in Main method:
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
            Encoding.GetEncoding("GBK");
4、dotnet publish

I could not found System.Text.Encoding.CodePages.dll under the "publish" folder.

**Comment by tarekgh** [comment]
@ringrid we believe this is expected because it is part of the closure of ASP.NET and as such ships in the runtime store with ASP.NET. If you run your sample web application you will see that it actually functions correctly.

@davidfowl do you know how the web applications filter out binaries for publishing?

**Comment by ringrid** [comment]
@tarekgh It could not running correctly, I copied publish folder to Linux, It throwed exception, the effect is cannot find System.Text.Encoding.CodePages.

**Comment by tarekgh** [comment]
@ringrid when you publish the bits to use on Linux, you'll need to specify the runtime RID. something like 

```
dotnet publish --runtime linux-x64
```

for the complete list of the RID, you can look at https://docs.microsoft.com/en-us/dotnet/core/rid-catalog

I tried that and it is publishing all needed assemblies correctly.

**Comment by ringrid** [comment]
@tarekgh Thanks for your reply. I think I did not describe my problem clearly. I have known it can be normally by using RID, but my Linux OS has already installed dotnet core SDK, not dotnet runtime. I think it can "write once, run everywhere".  before this question, other packages can be published normally, but this package can not be published,  so I think I need to be published without RID.

Thanks for your help again!

**Comment by tarekgh** [comment]
Thanks @ringrid for clarification. 

@davidfowl looks when referencing the SqlClient package which is referencing System.Text.Encoding.CodePages, the web app publishing will filter out System.Text.Encoding.CodePages because it is in the closure of the SqlClient package. Is that right? do you know why System.Text.Encoding.CodePages is filtered out when publishing the web app? 

```JSON
      "System.Data.SqlClient/4.4.0": {
        "dependencies": {
          "Microsoft.Win32.Registry": "4.4.0",
          "System.Security.Principal.Windows": "4.4.0",
          "System.Text.Encoding.CodePages": "4.4.0",
          "runtime.native.System.Data.SqlClient.sni": "4.4.0"
        },
```

**Comment by ringrid** [comment]
@tarekgh Did you have any result?

**Comment by tarekgh** [comment]
This issue was moved to aspnet/Mvc#6982

**Comment by tarekgh** [comment]
This issue was moved to aspnet/Mvc#6983

**Comment by ringrid** [comment]
@tarekgh thanks a lot. :+1:
