### ISSUE TITLE
New APIs in SyndicationFeedFormatter

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#24668]
We proposed to add two new properties in `SyndicationFeedFormatter`. We planned to add the APIs on .Net Core only, not in netstandard, for now.

```c#
namespace System.ServiceModel.Syndication
{
    public abstract partial class SyndicationFeedFormatter
    {
        public System.Func<string, string, string, System.DateTimeOffset> DateTimeParser { get { throw null; } set { } }
        public System.Func<string, System.UriKind, string, string, System.Uri> UriParser { get { throw null; } set { } }
    }
}
```

There're cases that the default `DateTimeParser` used by `SyndicationFeedFormatter` cannot handle some DateTime format. The new APIs enable developers to use their custom `DateTimeParser` or `UriParser` to parse the values in syndication feeds.

Alternatively, we can add the following APIs using named delegate,

```c#
namespace System.ServiceModel.Syndication
{
    public delegate DateTimeOffset DateTimeParserDelegate(string dateTimeString, string localName, string namespaceURI);
    public delegate Uri UriParserDelegate(string uriString, UriKind uriKind, string localName, string namespaceURI);
    public abstract partial class SyndicationFeedFormatter
    {
        public DateTimeParserDelegate DateTimeParser { get { throw null; } set { } }
        public UriParserDelegate UriParser { get { throw null; } set { } }
    }
}
```

/cc: @zhenlan @mconnew

**Comment by terrajobst** [comment]
Any reason this can't be a named delegate? A constructed generic with that many parameters makes it hard to be consumed/produced by existing APIs.

**Comment by shmao** [comment]
There's no reason it can't be a named delegate. We were just following the pattern used by other APIs for consistency, e.g. see https://github.com/dotnet/corefx/blob/a9fdc79ff8feb5ad46e9fcbe18fdffcd0bd74679/src/System.Net.Http.WinHttpHandler/ref/System.Net.Http.WinHttpHandler.cs#L45. 

I'm open to add new named delegates for the new APIs. What do you think? @terrajobst

**Comment by karelz** [comment]
Can you please suggested alternative with named delegates? Side-by-side, so that we can decide.
`WinHttpHandler` is expert type and doesn't set the right example IMO.

**Comment by karelz** [comment]
FYI: The API review discussion was recorded - see https://youtu.be/BI3iXFT8H7E?t=6154 (3 min duration)

**Comment by mconnew** [comment]
@karelz, is HttpClientHandler an expert type too as that has a similar api which doesn't use a named delegate.

**Comment by shmao** [comment]
@karelz Thanks for the suggestions. I updated the description with the named delegates.

**Comment by shmao** [comment]
@terrajobst @karelz can you please review the new APIs that use the named delegates? Thanks.

**Comment by karelz** [comment]
We will do that in our Tuesday API review session (hopefully the next one). You might want to join us (please ping Immo to send you the invite).

**Comment by terrajobst** [comment]
Notes:

* The generic funcs are hard to understand as the three strings don't tell customers what's going on.
* Consider passing in the local name and namespace name as a single `XmlQualifiedName` instance
* User code seems to have to chain with the default one, which is a bit weird with properties that are set. We usually use virtual methods where overriders can simply call the base implementation.
* The callback signature doesn't have a good way to return that it couldn't parse -- the caller has to catch the exceptions which makes chaining even more inconvenient. Consider using the `TryParse`-pattern.
* Since delegates are multi-cast customers can chain by prepending/appending to the underlying delegate list. Not very discoverable, but workable.

**Comment by karelz** [comment]
FYI: The API review discussion was recorded - see https://youtu.be/KKUjm8zaJBM?t=10 (50 min duration)

**Comment by shmao** [comment]
@terrajobst @karelz Please see below for the updated proposed APIs,

```c#
namespace System.ServiceModel.Syndication
{
    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct ParseDateTimeArgs
    {
        public string DateTimeString { get { throw null; } set { } }
        public System.Xml.XmlQualifiedName ElemntQualifiedName { get { throw null; } set { } }
    }
    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct ParseUriArgs
    {
        public System.Xml.XmlQualifiedName ElemntQualifiedName { get { throw null; } set { } }
        public System.UriKind UriKind { get { throw null; } set { } }
        public string UriString { get { throw null; } set { } }
    }
    public abstract partial class SyndicationFeedFormatter
    {
        public System.ServiceModel.Syndication.TryParseDateTime DateTimeParser { get { throw null; } set { } }
        public System.ServiceModel.Syndication.TryParseUri UriParser { get { throw null; } set { } }
    }
    public delegate bool TryParseDateTime(System.ServiceModel.Syndication.ParseDateTimeArgs parseDateTimeArgs, out System.DateTimeOffset dateTimeOffset);
    public delegate bool TryParseUri(System.ServiceModel.Syndication.ParseUriArgs parseUriArgs, out System.Uri uri);
}
```

I had a PR for making the changes. Please let me know if you have any concerns regarding to the new APIs. Thanks.

**Comment by huanwu** [comment]
Already merged.

**Comment by karelz** [comment]
It is not merged. It needs final API review.

**Comment by huanwu** [comment]
@mconnew Could you work on final API review and merge the changes?

**Comment by mconnew** [comment]
@terrajobst, @karelz I've updated the [above comment](https://github.com/dotnet/corefx/issues/24668#issuecomment-356144185) with the latest api proposal from the PR #26153. Can we review this offline now?

**Comment by karelz** [comment]
@mconnew https://github.com/dotnet/corefx/issues/24668#issuecomment-351145636 asked for sample code. Do you plan to add it?
BTW: I would recommend to start email thread with Immo once it is ready.

**Comment by stephentoub** [comment]
@karelz et al, what's the status of this? There's an open PR blocked on it.  We should either get this issue resolved so we can merge the PR, or we should close the PR and it can be reopened when this is ready to go.  Thanks.

**Comment by karelz** [comment]
We're waiting on API review to happen (this morning?) - @mconnew didn't add the sample code which was asked earlier ... not sure if it will be block the review.

**Comment by zhenlan** [comment]
@mconnew is OOF. @karelz, can tests in PR #26153 be considered as samples? Can you please review the PR?

**Comment by karelz** [comment]
@zhenlan I am OOF myself :( ... can you please ping Immo? (email is safer with him ;))

**Comment by terrajobst** [comment]
Looks good, but we shouldn't use the `Delegate` suffix.

```csharp
namespace System.ServiceModel.Syndication
{
    public delegate DateTimeOffset DateTimeParserCallback(string dateTimeString, string localName, string namespaceURI);
    public delegate Uri UriParserCallback(string uriString, UriKind uriKind, string localName, string namespaceURI);
    public abstract partial class SyndicationFeedFormatter
    {
        public DateTimeParserCallback DateTimeParser { get { throw null; } set { } }
        public UriParserCallback UriParser { get { throw null; } set { } }
    }
}
```

**Comment by mconnew** [comment]
@terrajobst, I think you reviewed the wrong thing. [This](https://github.com/dotnet/corefx/issues/24668#issuecomment-356144185) comment has the latest where we are using an Args parameter and the Delegate suffix isn't used.

**Comment by karelz** [comment]
@mconnew in future, please update top post to latest proposal, or add there link to latest proposal to avoid these kind of confusions ...

**Comment by terrajobst** [comment]
Sorry about that.

```csharp
namespace ServiceModel.Syndication
{
    public partial struct XmlDateTimeData
    {
        public XmlDateTimeData(string dateTimeString, XmlQualifiedName elementQualifiedName);
        public string DateTimeString { get; }
        public XmlQualifiedName ElementQualifiedName { get; }
    }
    public partial struct XmlUriData
    {
        public XmlUriData(string uriString, UriKind uriKind, XmlQualifiedName elementQualifiedName);
        public XmlQualifiedName ElementQualifiedName { get; }
        public UriKind UriKind { get; }
        public string UriString { get; }
    }
    public abstract partial class SyndicationFeedFormatter
    {
        public TryParseDateTimeCallback DateTimeParser { get; set; }
        public TryParseUriCallback UriParser { get; set; }
    }

    public delegate bool TryParseDateTimeCallback(XmlDateTimeData data, out DateTimeOffset dateTimeOffset);

    public delegate bool TryParseUriCallback(XmlUriData data, out Uri uri);
}
```

**Comment by karelz** [comment]
BTW: structs renamed to `*Data`, delegates are `*Callback`, args renamed to `data`.
