### ISSUE TITLE
To Support New APIs of SyndicationFeedFormatter on Netfx

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#24669]
PR https://github.com/dotnet/corefx/pull/24613 added the following new APIs in `SyndicationFeedFormatter`. 

```c#
public System.Func<string, string, string, System.DateTimeOffset> DateTimeParser { get { throw null; } set { } }
public System.Func<string, string, string, string> StringParser { get { throw null; } set { } }
public System.Func<string, System.UriKind, string, string, System.Uri> UriParser { get { throw null; } set { } }
```

We need to decide whether the APIs should work on netfx and whether we can support them.

**Comment by yujayee** [comment]
Shall we close this issue @Lxiamail ? We already brought this to shiproom last year and got rejected.

**Comment by Lxiamail** [comment]
Yes, we can close this issue now.
