### ISSUE TITLE
Cannot decompress Rijndael encrypted Gzip

### ISSUE THREAD

**Issue by gabor182** [dotnet/corefx#24662]
Hello,

we are using Rijndael encrypted gzips. The following code works just fine in .NET Framework 4.6.1 but throws exception in .NET Core 2.0
```
using (var rijAlg = Rijndael.Create())
{
    rijAlg.Key = _configK;
    rijAlg.IV = _configI;
    rijAlg.BlockSize = 128;
    rijAlg.Padding = PaddingMode.PKCS7;

    // Create a decrytor to perform the stream transform.
    var decryptor = rijAlg.CreateDecryptor(rijAlg.Key, rijAlg.IV);

    // Create the streams used for decryption. 
    using (var sourceStream = new MemoryStream(buffer))
    {
        using (var decryptStream = new CryptoStream(sourceStream, decryptor, CryptoStreamMode.Read))
        {
            if (isGzipped)
            {
                using (var unzipStream = new System.IO.Compression.GZipStream(decryptStream, System.IO.Compression.CompressionMode.Decompress)) 
                {
                    using (var targetStream = new MemoryStream())
                    {
                        unzipStream.CopyTo(targetStream);
                        Content = targetStream.ToArray();
                    }
                }
            }
            else
            {
                using (var targetStream = new MemoryStream())
		{
		    decryptStream.CopyTo(targetStream);
		    Content = targetStream.ToArray();
		}
	    }
	}
    }
}
```
The exception is: 
`The archive entry was compressed using an unsupported compression method.`

Stack trace:
```
   at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.Inflater.Inflate(Byte[] bytes, Int32 offset, Int32 length)
   at System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.Compression.GZipStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
```

Maybe the decryptor has a bug which results in an invalid decrypted data and that's why GzipStream fails to decompress it?

**Comment by danmosemsft** [comment]
@ianhays can indicate whether tihs is expected.

**Comment by gabor182** [comment]
I've created a test console application in which I Gzipped a string, encrypted it with Rijndael encryption, then tried to decrypt and decompress it. The result is that if I don't set the `SymmetricAlgorithm.Blocksize` property to 128 bits, then everything works fine. 
As soon as I set it to 128 bits I get the `System.IO.InvalidDataException`. The message is the same as mentioned in my original comment:
`The archive entry was compressed using an unsupported compression method.`

This error is not present in .NET Framework 4.6.2 (tested it with this very same test class).

I attached my test console project.
[Cryptography.zip](https://github.com/dotnet/corefx/files/1391256/Cryptography.zip)

**Comment by ianhays** [comment]
>The result is that if I don't set the SymmetricAlgorithm.Blocksize property to 128 bits, then everything works fine.

Interesting... [the default BlockSize is 128](https://github.com/dotnet/corefx/blob/927f4ac218c305408af316cc92f131629527cb3e/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/Rijndael.cs#L28), so specifying it explicitly *shouldn't* make a difference.

**Comment by ianhays** [comment]
Alright, I found the issue. In your test program, you're setting the IV and then setting the BlockSize like so:
```
                rijAlg.IV = IV;
                rijAlg.Padding = PaddingMode.PKCS7;
                rijAlg.BlockSize = 128;
```

So the problem here is that normally, [setting the blocksize will cause the IV to be set to null](https://github.com/dotnet/corefx/blob/dev/release/2.0.0/src/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/SymmetricAlgorithm.cs#L56). However, in .net core we have a special-case that makes [setting the blocksize not reset the IV when the algorithm supports several blocksizes and the current blocksize is equivalent to what you're trying to set the new blocksize as](https://github.com/dotnet/corefx/blob/dev/release/2.0.0/src/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/SymmetricAlgorithm.cs#L52). This is to retain back-compat with some weird netfx behavior [here](http://referencesource.microsoft.com/?#mscorlib/system/security/cryptography/symmetricalgorithm.cs,95).

In full framework we supported more than one BlockSize in Rijndael so we hit this condition, but in .net core [we limited it to only support BlockSize=128](https://github.com/dotnet/corefx/issues/12064#issuecomment-251155477). This resulted in the likely unintended side-effect of changing the set_BlockSize/get_IV relationship.

If I change your code to set BlockSize first then your repro program passes without issue:

```
                rijAlg.Padding = PaddingMode.PKCS7;
                rijAlg.BlockSize = 128;
                rijAlg.IV = IV;
```

**Comment by ianhays** [comment]
cc: @bartonjs on next-step decisions for what we want to do about this (if anything). 

Personally i find this entirely unintuitive and would like to either:
- Remove the [value==BlockSizeValue](http://referencesource.microsoft.com/?#mscorlib/system/security/cryptography/symmetricalgorithm.cs,95) check (doubt we can do this for compat reasons)
- Special-case Rijndael to not set IV to null when setting BlockSize.

**Comment by bartonjs** [comment]
Looks like in NetFx we always clear IV on assigning BlockSize, so I guess we should remove the "this hasn't changed" filter.  http://referencesource.microsoft.com/#mscorlib/system/security/cryptography/symmetricalgorithm.cs,bb2ebc49dd5eb9cd

**Comment by gabor182** [comment]
@ianhays Thank you for the thorough explanation.

**Comment by ianhays** [comment]
>Looks like in NetFx we always clear IV on assigning BlockSize,

Not always. You can reach [this return statement](http://referencesource.microsoft.com/#mscorlib/system/security/cryptography/symmetricalgorithm.cs,99) without setting the IV to null (which is what the repro program on netfx is hitting).

>I guess we should remove the "this hasn't changed" filter.

I'm not sure what you mean by this. Could you elaborate?

**Comment by bartonjs** [comment]
@ianhays  Ooooh.  It's that it dropped to a single block size and gained different behaviors and now it IS nulling it out.  I read the behavior backwards.  (Note to self: Don't try to read code while also trying to pay attention in meetings)

So the compat fix would be to make CoreFx RijndaelManaged override set_BlockSize and no-op; to prevent the base class from clearing the IV.

Did I read it right that time? :smile:

**Comment by ianhays** [comment]
>So the compat fix would be to make CoreFx RijndaelManaged override set_BlockSize and no-op; to prevent the base class from clearing the IV.
>Did I read it right that time?

Yup, that is correct! We will want to leave in the set_BlockSize checks against validBlockSizes so we still throw when given a value other than 128, but other than that it should no-op.

**Comment by bartonjs** [comment]
![](https://memegenerator.net/img/instances/34189571/make-it-so-number-one.jpg)
