### ISSUE TITLE
Build step 'Execute shell' marked build as failure in CI

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#24660]
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_ubuntu14.04_debug/200/

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_ubuntu14.04_debug/lastCompletedBuild/consoleFull#-8536224876a086b3e-df04-41d2-bc4d-43e8f9406d07

Configuration: outerloop_netcoreapp_ubuntu14.04_debug

Build step 'Execute shell' marked build as failure
15:52:05 [xUnit] [INFO] - Starting to record.
15:52:05 [xUnit] [INFO] - Processing xUnit.Net-v2 (default)
15:52:06 [xUnit] [INFO] - [xUnit.Net-v2 (default)] - No test report file(s) were found with the pattern 'bin/**/testResults.xml' relative to '/mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu14.04_debug' for the testing framework 'xUnit.Net-v2 (default)'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'xUnit.Net-v2 (default)'?
15:52:06 
[xUnit] [ERROR] - No test reports found for the metric 'xUnit.Net' with the resolved pattern 'bin/**/testResults.xml'. Configuration error?.
15:52:06 [xUnit] [INFO] - Failing BUILD.
15:52:06 [xUnit] [INFO] - There are errors when processing test results.
15:52:06 [xUnit] [INFO] - Skipping tests recording.
15:52:06 [xUnit] [INFO] - Stop build.

**Comment by danmosemsft** [comment]
```
15:52:04 Please install clang before running this script
15:52:04 Command execution failed with exit code 1.
```

**Comment by danmosemsft** [comment]
@mmitche is looking at these.

**Comment by Jiayili1** [comment]
still repro, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_ubuntu14.04_debug/201/

**Comment by mmitche** [comment]
@Jiayili1 Fixing this now.

**Comment by danmosemsft** [comment]
@Jiayili1 if this is fixed now please close

**Comment by Jiayili1** [comment]
This issue is not repro, close it.
