### ISSUE TITLE
Tests under "System.Console.Tests" failed with "Exit code was 131 but it should have been 42" 

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#24678]
failed test: CancelKeyPressTests.CanAddAndRemoveHandler_Remote 
Configuration: oxs10.12_release

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release/3358/testReport/(root)/CancelKeyPressTests/CanAddAndRemoveHandler_Remote/

MESSAGE:
~~~
Exit code was 131 but it should have been 42\nExpected: True\nActual: False
~~~
STACK TRACE:
~~~
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() 
in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 189
~~~

**Comment by Jiayili1** [comment]
Failed tests:
 CancelKeyPressTests.CanAddAndRemoveHandler_Remote
 ConsoleEncoding.OutputEncoding_SetWithErrorAndOutputInitialized_ResetsErrorAndOutput
 ConsoleEncoding.InputEncoding_SetWithInInitialized_ResetsIn
 RedirectedStream.InputRedirect
 RedirectedStream.OutputRedirect
 RedirectedStream.ErrorRedirect
 ReadKey.RedirectedConsole_ReadKey
 WindowAndCursorProps.Title_GetSet_Unix
 System.Tests.NonStandardConfigurationTests.NonBlockingStdout_AllDataReceived

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release/3358/testReport/

**Comment by danmosemsft** [comment]
`A fatal error occurred, the required library libhostfxr.dylib could not be found at /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/bin/testhost/netcoreapp-OSX-Release-x64/shared/Microsoft.NETCore.App/9.9.9/`

**Comment by Jiayili1** [comment]
Following tests failed with same issue, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release/3449/testReport/

**Comment by Sunny-pu** [comment]
Following tests failed with same issue, detail: 
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/3543/testReport/

**Comment by Sunny-pu** [comment]
Following tests failed with same issue, detail:
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/3837/testReport/

**Comment by danmosemsft** [comment]
Old.
