### ISSUE TITLE
HttpClient SendAsync Object disposed exception when request version is Http 1.1 passes when it is HTTP 1.0

### ISSUE THREAD

**Issue by ankgupta067** [dotnet/corefx#24683]
I am using HttpClient to send a post request to my service , where when user is unauthorized 401 status code is returned on receiving that i throw an exception from my client code, but once this use case is done my client program keeps throwing , i get an exception when i call HttpClient.SendAsync() method.

> System.ObjectDisposedException occurred Message: A first chance exception of type 'System.ObjectDisposedException' occurred in System.dll Additional information: Cannot access a disposed object.

and finally i get -

```
System.Net.Http.HttpRequestException occurred
   _HResult=-2146233088
   _message=Error while copying content to a stream.
   HResult=-2146233088
   IsTransient=false
   Message=Error while copying content to a stream.
   Source=mscorlib
   StackTrace:
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   InnerException: System.IO.IOException
        _HResult=-2146232800
        _message=The read operation failed, see inner exception.
        HResult=-2146232800
        IsTransient=false
        Message=The read operation failed, see inner exception.
        Source=System.Net.Http
        StackTrace:
             at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.BeginRead(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
             at System.Net.Http.StreamToStreamCopy.StartRead()
        InnerException: System.Net.WebException
             _HResult=-2146233079
             _message=The request was aborted: The connection was closed unexpectedly.
             HResult=-2146233079
             IsTransient=false
             Message=The request was aborted: The connection was closed unexpectedly.
             Source=System
             StackTrace:
                  at System.Net.ConnectStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
                  at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.BeginRead(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
             InnerException: 
```

I have to in fact restart service to get proper response again.

Above behavior happens only if HttpRequestMessage.Version is set to HttpVersion.Version11 but when HttpVersion.Version10 everything works fine, following is a sample code i created to reproduce same , any insights on why this happens?
```c#
class Program {
        static HttpClientHandler handler = new HttpClientHandler{Credentials = CredentialCache.DefaultCredentials};           

        static void Main()
        {
            for (int i = 0; i < 10; i++)
            {
                try {
                    Main2().Wait();
                } catch (Exception e) {
                    Console.WriteLine(e);
                }

            }
            Console.ReadLine();
        }

        private static async Task Main2() {
            var client1 = new HttpClient(handler,false);
             client1.DefaultRequestHeaders.CacheControl = CacheControlHeaderValue.Parse("no-cache");
             HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, "http://localhost/RestFramework/AuditEventService/AuditEvent") {
                 Content = new StringContent("sdad"),
                 Version = HttpVersion.Version11

             };
           request.Content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = null;
            try
            {
                response = await client1.SendAsync(request); // i am expecting a 401 status code, this line cause issue
                if (!response.IsSuccessStatusCode)
                {
                    var statusCode = response.StatusCode; 
                    throw new Exception(statusCode.ToString());
                }
            } finally {
                client1.Dispose();
            }
        }
```

my web api service returns a 401 for the request which i am passing, if i put a sleep in my filter code mentioned below everything works fine ,the code for filter looks below-

```c#
internal class IntegrateWindowsAuthenticationFilter : IActionFilter {
     
  /// <summary>
        /// user groups
        /// </summary>
        public IList<string> UserGroups { get; set; }

        /// <summary>
        /// user names
        /// </summary>
        public  IList<string> UserNames { get; set; }

        #region IActionFilter Members

        /// <summary>
        ///     Executes the action filter asynchronous.
        /// </summary>
        /// <param name="actionContext">The action context.</param>
        /// <param name="cancellationToken">The cancellation token.</param>
        /// <param name="continuation">The continuation.</param>
        /// <returns></returns>
        public Task<HttpResponseMessage> ExecuteActionFilterAsync(HttpActionContext actionContext,
            CancellationToken cancellationToken, Func<Task<HttpResponseMessage>> continuation) {
            //Thread.sleep(1000) // this make things work with http 1.1
            var output = false;
            if (UserGroups != null) {
                foreach (var group in UserGroups) {
                    output = actionContext.RequestContext.Principal.IsInRole(group);
                    if (output) {
                        return continuation();
                    }
                }
            }
            if (UserNames != null) {
                foreach (var user in UserNames) {
                    output =
                        actionContext.RequestContext.Principal.Identity.Name
                            .Equals(user,
                                StringComparison.OrdinalIgnoreCase);
                    if (output) {
                        return continuation();
                    }
                }
            }

            var outcome = new OperationOutcome();
            outcome.Issue.Add(new IssueComponent {
                Details = Constants.UnauthorizedAccess
            });
            return Task.FromResult(new HttpResponseMessage(HttpStatusCode.Unauthorized));
        }

        #endregion

        #region IFilter Members

        /// <summary>
        ///     Gets a value indicating whether [allow multiple].
        /// </summary>
        /// <value>
        ///     <c>true</c> if [allow multiple]; otherwise, <c>false</c>.
        /// </value>
        public bool AllowMultiple {
            get {
                return false;
            }
        }

        #endregion
    }

```

[EDIT] Fix code and exception formatting by @karelz

**Comment by davidsh** [comment]
>StackTrace:
at System.Net.ConnectStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)

From looking at the call stack, I assume this is happening on .NET Framework and not .NET Core?  .NET Framework bugs are not tracked here.

**Comment by davidsh** [comment]
Please try out the latest .NET Framework 4.7.2:
https://blogs.msdn.microsoft.com/dotnet/2018/04/30/announcing-the-net-framework-4-7-2/

If this problem is still occurring with .NET Framework, please open an issue here directly against .NET Framework:
https://developercommunity.visualstudio.com/spaces/61/index.html

Thx.

**Comment by karelz** [comment]
We had internal report of the same problem (https://developercommunity.visualstudio.com/content/problem/359756/httpclient-sendasync-object-disposed-exception-whe.html), where we were able to get a minimal repro (using internal server returning 401):

## Repro
```c#
using System;
using System.Net;
using System.Net.Http;

class Program
{
    public static void Main()
    {
        using (var client = new HttpClient(new HttpClientHandler { Credentials = CredentialCache.DefaultCredentials }))
        {
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, "https://hdgtfsuat/tfs/Surfuat")
            {
                Content = new StringContent("a"),
                Version = HttpVersion.Version11
            };
            // Original repro: I am expecting a 401 status code,
            //   but different HttpWebRequestException (with inner "The request was aborted: The connection was closed unexpectedly." exception) is thrown instead
            HttpResponseMessage response = client.SendAsync(request).Result;
        }
    }
}
```

It does not repro in these cases:
* If POST request is without body (delete line `Content = new StringContent("a"),`)
* If `Credentials = CredentialCache.DefaultCredentials` is not set in `HttpClientHandler`
* If request version is HTTP/1.0: `Version = HttpVersion.Version11`

Interestingly we are able to consistently reproduce it on 2 different machines (and different accounts), while it always passes on other 2 machines (and different accounts) - all on recent .NET Framework 4.7.2.
It looks like an "interesting" long-existing bug in .NET Framework - in the way we handle the response.

## Workaround
There is a workaround to just read response headers first (`HttpCompletionOption.ResponseHeadersRead`, check the `StatusCode` for 401 and if it is ok, read the response body `Content`:
```c#
            // Workaround: Split the call into HeadersRead, check status code and if it is ok, continue with body read
            HttpResponseMessage response = client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead).Result;
            Console.WriteLine($"{response.StatusCode} - {(int)response.StatusCode}"); // Prints "Unauthorized - 401"
            // Throws the 'bad' unexpected exception
            string body = response.Content.ReadAsStringAsync().Result;
```

Kudos to @davidsh for analysis and help with debugging it & workaround suggestion.

**Comment by IsaackRasmussen** [comment]
@karelz 

We just hit this bug as well and for us, its not happening in all our environments which we are still trying to figure out, but finding this github issue at least allowed us to move ahead.

But I cannot make your workaround work. I need UseDefaultCredentials and I can confirm if I set the credentials it works.
I can only make it work by using HTTP/1.0

**Comment by BillArmstrong** [comment]
I ran into this several months ago. At the time we didn't investigate further because we didn't need to connect using default credentials. Now we do, which led me to discover this thread.

The provided workaround assumes that the logged on user does not have permissions to access the resource being targeted and that the 401 error being returned is a legitimate error. In my scenario the user actually does have access to the resource, and I'm still seeing the exception. I tried the suggested workaround, and all it did was allow me to see the 401 error being returned, but I should not be getting a 401 error at all.

Interestingly, if I use Fiddler and configure it to decrypt the HTTPS traffic, the problem goes away. The request authenticates properly and I get an appropriate response with no errors.

I am desperate to find a workaround for this issue. I don't want to have to prompt the user for a username and password when I should be able to just use their logged on user credentials.

Any suggestions would be appreciated.

**Comment by davidsh** [comment]
>I am desperate to find a workaround for this issue. I don't want to have to prompt the user for a username and password when I should be able to just use their logged on user credentials.
Any suggestions would be appreciated.

The root cause is a problem in the .NET Framework HTTP stack.  The .NET Framework bug has not been fixed.  The repro is sensitive to race conditions. This is why it "works" when you Fiddler and decrypt HTTPS traffic. That affects the timing of everything including how fast network packets are being read by the HTTP stack.

The workarounds were discussed above in this thread.

> I can only make it work by using HTTP/1.0

This workaround suggested by @IsaackRasmussen works because it changes the timing of the connections and specifically doesn't use Keep-Alive as the default for connections (since that is the default for HTTP/1.1 and not HTTP/1.0).

Usually, it is sufficient to use code like this to separate the reading of the HTTP response headers from the subsequent reading/buffering of the response body.  That is usually enough to mitigate the race conditions that can cause this bug.

```c#
// Workaround: Split the call into HeadersRead, check status code and if it is ok, continue with body read
HttpResponseMessage response = client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead).Result;

// Some delay

// Read response body
string body = response.Content.ReadAsStringAsync().Result;
```

**Comment by BillArmstrong** [comment]
Thanks @davidsh. I ended up rewriting our code to use HttpWebRequest instead of HttpClient. Now default credentials are working perfectly.

**Comment by davidsh** [comment]
>Thanks @davidsh. I ended up rewriting our code to use HttpWebRequest instead of HttpClient. Now default credentials are working perfectly.

Glad to see you found a workaround.  The irony is that on .NET Framework, HttpClient APIs use HttpWebRequest underneath as the implementation.  So, probably the reason why your workaround is working is due to race conditions changing as as result of the direct use of HttpWebRequest.
