### ISSUE TITLE
Generic List<T> source code in System.Collections.Generic?

### ISSUE THREAD

**Issue by ganeshran** [dotnet/corefx#2471]
Hi, I'm looking for source code of the Generic List<T> class but can't find it in the folder https://github.com/dotnet/corefx/tree/master/src/System.Collections/src/System/Collections/Generic

There are test cases but the code itself is not present in the folder mentioned above.

**Comment by mellinoe** [comment]
List<T>, along with some of the other types in System.Collections.Generic, are implemented in mscorlib, here:

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/List.cs

**Comment by ganeshran** [comment]
@mellinoe Thank you!

**Comment by HelloKitty** [comment]
While technically this isn't an issue, the response provided is no longer correct. It has been moved here: https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Collections/Generic/List.cs

**Comment by jnm2** [comment]
In general, just press <kbd>T</kbd> while on the repo's home page and type `List.cs`. If it doesn't appear in the search results, try it at the other repo's home page.

**Comment by weitzhandler** [comment]
@jnm2 didn't know that useful one, thanks for sharing!

**Comment by jnm2** [comment]
New thing I learned last week: go to `http://source.dot.net`, type `List<`, click the top entry, then click the 'Web Access' link in the bottom right corner.

**Comment by weitzhandler** [comment]
Ah! kewwl!
BTW, I have source.dot.net as a Chrome search engine, so I just type `so` in the address bar, and hit <kbd>Tab</kbd> to search.

**Comment by Mirandatz** [comment]
Both links provided in the answers are broken.

**Comment by HelloKitty** [comment]
I believe this is the new link @Mirandatz : https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Collections/Generic/List.cs

**Comment by Mirandatz** [comment]
Thank you very much.

**Comment by SunTaoA** [comment]
https://referencesource.microsoft.com/#mscorlib/system/collections/generic/list.cs
