### ISSUE TITLE
Question: How are unmanaged code libraries loaded as SafeHandles?

### ISSUE THREAD

**Issue by aerotog** [dotnet/corefx#24726]
**How are C++ libraries loaded into SafeHandle() classes in .Net Core on Linux (or any platform)?**

I am attempting to port an application to .Net Core. The application makes external calls to a C++ library.  Before doing so, it loads the library into a SafeHandle.

Windows platform:
```
[DllImport("Kernel32", CharSet = CharSet.Auto, BestFitMapping = false, SetLastError = true)]
private static extern SafeLibraryHandle LoadLibrary(string fileName);
```

Posix platform (via Mono):
```
[DllImport(__Internal, CallingConvention = CCCdecl)]
private static extern SafeLibraryHandle dlopen(IntPtr filename, int flags);
```

The class "SafeLibraryHandle" inherits from Microsoft.Win32.SafeHandles.SafeHandleZeroOrMinusOneIsInvalid. (The SafeHandleZeroOrMinusOneIsInvalid base class was added in .Net Core 2.0.)

The Kernel32 LoadLibrary() works as expected when running in .Net Core on Windows. When running on Linux, the Mono method is called and fails as expected because there is no __Internal library available.

From what I've found, Mono wraps the [Linux dlopen() command](http://man7.org/linux/man-pages/man3/dlopen.3.html) like [this](https://github.com/mono/mono/blob/master/libgc/gc_dlopen.c).

I'm rather unfamiliar with loading/using unmanaged code. From what I can tell, the purpose of these SafeHandle classes is to load the library files into memory and turn them into disposable types. Since the SafeHandle base class exists in .Net Standard and is used in .Net Core, it seems like there should be way to load libraries on any platform. **So how should C++ libraries be loaded into SafeHandle() classes in .Net Core on Linux?**

**Comment by jkotas** [comment]
This is how it is done in .NET Core implementation itself: https://github.com/dotnet/corefx/search?p=1&q=Libdl&type=&utf8=%E2%9C%93

https://github.com/dotnet/corefx/issues/24213 has some related discussion that you may be interested in.

cc @russellhadley

**Comment by aerotog** [comment]
Using the Mono hooks but replacing "__Internal" with "libdl" is working:

```
[DllImport("libdl", CallingConvention = CCCdecl)]
private static extern SafeLibraryHandle dlopen(IntPtr filename, int flags);
```

Based on the .NET Core examples, this seems to be the correct way of calling dlopen.

I've tested this change locally and it seems to solve my problem. For anyone else who comes across this, just know that it may not work for a given C++ library due to [function name mangling](http://www.tldp.org/HOWTO/C++-dlopen/theproblem.html).

Since using "libdl" answers my original question, I'm closing this issue. Thank you jkotas!
