### ISSUE TITLE
Engineering System Epic

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#24739]
This Epic is to track planned engineering work specific to the CoreFX repo. (The actual work may be in part in the BuildTools repo)

Like all our Epics in order to see the child work items you must have the free [Zenhub browser plugin ](https://www.zenhub.com/) enabled.

**Comment by danmosemsft** [comment]
This may include: making dumps easier to consume and debug; easier to set up dev environment, outerloop robustness, CoreFX specific work for faster full stack builds, improve unit testing experience, move tests to inner loop, servicing work specific for CoreFX.

**Comment by weshaggard** [comment]
A few source-build epics that we need to resource our part for the core repos:

https://github.com/dotnet/source-build/issues/145
https://github.com/dotnet/source-build/issues/251

**Comment by weshaggard** [comment]
https://github.com/dotnet/source-build/issues/229

**Comment by danmosemsft** [comment]
@weshaggard are all the child issues linked into this aspired to for 2.1? 

To prioritize the issues for 2.1 you can drag into P1/P2 columns on the Zenhub board for this Epic: https://github.com/dotnet/corefx#boards?epics=26295345_24739&notFullScreen=false&repos=26295345&showPRs=false&showClosed=false

Any issues that are not realistic for 2.1 please detach from this Epic; if you want to keep track of them, we can make a post 2.1 Engineering Epic.

I would like to get points costs on each of the ones you keep in this Epic. I can drop by if you like.

**Comment by danmosemsft** [comment]
No more for 2.1

**Comment by weshaggard** [comment]
Dan I don't see any reason to keep this open so closing.
