### ISSUE TITLE
Crypto Epic

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#24743]
This Epic is to track work we are doing for Crypto for the next release.

Like all our Epics in order to see the child work items you must have the free [Zenhub browser plugin ](https://www.zenhub.com/) enabled.

**Comment by danmosemsft** [comment]
@joshfree please link issues representing the likely work for 2.1.

**Comment by stephentoub** [comment]
We're not using epics anymore, per @danmosemsft.
