### ISSUE TITLE
Security Epic

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#24745]
This Epic is to track (non Crypto) work we are doing in CoreFX for Security for the next release.

Like all our Epics in order to see the child work items you must have the free [Zenhub browser plugin ](https://www.zenhub.com/) enabled.

**Comment by danmosemsft** [comment]
@joshfree you're the owner with @GrabYourPitchforks ... can one of you please help break out likely work and link to this ?

**Comment by danmosemsft** [comment]
@GrabYourPitchforks if you do this note you have to have Zenhub installed and logged in then click Modify This Epic to choose from issues (or create them)

**Comment by danmosemsft** [comment]
Need to talk to @GrabYourPitchforks

**Comment by tarekgh** [comment]
@joshfree @danmosemsft what is remaining here?

**Comment by danmosemsft** [comment]
AFAIK this is done. @joshfree @GrabYourPitchforks

**Comment by tarekgh** [comment]
closing it then. please feel free to re-open if there is anything more need to be done.
