### ISSUE TITLE
Performance Epic

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#24747]
This Epic is to track work we are doing in CoreFX (and corelib) to monitor and improve performance for the next release - excepting Networking performance, which is likely in the [Networking Epic](https://github.com/dotnet/corefx/issues/24742).

Like all our Epics in order to see the child work items you must have the free [Zenhub browser plugin ](https://www.zenhub.com/) enabled.

**Comment by danmosemsft** [comment]
We want to use data - such as Azure profiler; customer traces; [CLBG](http://benchmarksgame.alioth.debian.org/), TechEmpower - to target performance improvements where they matter most, generally in widely-used existing API. Candidate areas include: Timers, Async methods, Cancellation, Synchronization, Linq, Regex, Collections, Strings. Often changes will be candidates for porting to .NET Framework.

**Comment by danmosemsft** [comment]
Ownership to discuss with @valenis ..

**Comment by tarekgh** [comment]
@stephentoub  @joshfree @danmosemsft what is remaining here?

**Comment by danmosemsft** [comment]
Completed 2.1 work

**Comment by stephentoub** [comment]
We're not using epics anymore, per @danmosemsft.
