### ISSUE TITLE
Azure IoT Hub Epic

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#24744]
This Epic is to track work we are doing for Azure IoT hub for the next release.

Like all our Epics in order to see the child work items you must have the free [Zenhub browser plugin ](https://www.zenhub.com/) enabled.

**Comment by danmosemsft** [comment]
This may include remaining work for Alpine, and possibly libraries needed for IoT and capability API.

**Comment by danmosemsft** [comment]
@joshfree you're the owner. Can you link issues encompassing the major work items /investigations (as far as we know them)?

**Comment by danmosemsft** [comment]
No work planned for 2.1 currently.

**Comment by stephentoub** [comment]
We're not using epics anymore, per @danmosemsft.
