### ISSUE TITLE
Microservices and Cloud Epic

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#24741]
This Epic is to track work we are doing in CoreFX to support ASP.NET Core.

Like all our Epics in order to see the child work items you must have the free [Zenhub browser plugin ](https://www.zenhub.com/) enabled.

**Comment by danmosemsft** [comment]
This may include work for the runtime store, running on sockets, ALPN, HTTP2, SslStream perf (if not in Networking Epic), Channels, remaining work for Span, Memory, and other primitives.

**Comment by tarekgh** [comment]
@KrzysztofCwalina  @danmosemsft @joshfree what is remaining here?

**Comment by joshfree** [comment]
@tarekgh all bugs with "Epic" in the title are zenhub epic issues.  They can move to the Future milestone if needed to cleanup the 2.1 query.

**Comment by tarekgh** [comment]
@joshfree what you prefer? I am ok to keep them on 2.1 as long as someone really actively looking at them.

**Comment by joshfree** [comment]
I'm fine moving this out to Future or to 2.2, once the milestone opens.

**Comment by stephentoub** [comment]
We're not using epics anymore, per @danmosemsft.
