### ISSUE TITLE
Linux/Windows Parity Epic

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#24750]
This Epic covers work to address places where Linux support is behind Windows support, and also potentially any Linux-specific features we add in CoreFX for this release.

**Comment by danmosemsft** [comment]
This may include API's for such areas as link and path handling and Linux ACL's; investigating and fixing some performance gaps with Windows; pick up and consume Mono.Posix if necessary.

**Comment by danmosemsft** [comment]
If this is primarily going to be perf work this cycle we may just roll that into the Performance Epic and treat the rest as stocking stuffers.

**Comment by danmosemsft** [comment]
Linking to this epic does not necessarily imply work will happen in 2.1.

**Comment by tarekgh** [comment]
@danmosemsft what is remaining here?
