### ISSUE TITLE
Parse CultureInfo no longer supported in .NET Core

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#24755]
@viktor-morin commented on [Thu Oct 19 2017](https://github.com/dotnet/core/issues/1035)

Hi!

I reported an error using Newtonsoft.Json where I recieved that the error was in .NET Core and not Newtonsoft.Json itself. Copy paste the issue here below:

We are now changing to .NET Core and we get following error when trying to parse a following class:

`Dictionary<CultureInfo,string>`

> ArgumentException: Could not cast or convert from System.String to System.Globalization.CultureInfo.
> Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(object value, Type initialType, Type targetType)
> JsonSerializationException: Error converting value "en-US" to type 'System.Globalization.CultureInfo'. Path 'Name.en-US', line 1, position 17.
> Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, object value, CultureInfo culture, JsonContract contract, Type targetType)
> JsonSerializationException: Could not convert string 'en-US' to dictionary key type 'System.Globalization.CultureInfo'. Create a TypeConverter to convert from the string to the key type object. Path 'Name.en-US', line 1, position 17.
> Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, string id)

This is working in .NET Framwork.

Link to original post:
[https://github.com/JamesNK/Newtonsoft.Json/issues/1457](https://github.com/JamesNK/Newtonsoft.Json/issues/1457)

[@danmosemsft edited to make link clickable]

**Comment by danmosemsft** [comment]
We do have CultureInfoConverter in .NET Core (as of 2.0). For some reason it is not getting used (assuming this is 2.0). Needs investigation.

**Comment by danmosemsft** [comment]
@Anipik when you have a moment could you please try on .NET Core 2.0 to use Newtonsoft.Json to serialize and deserialize an object with type Dictionary<CultureInfo, string>?

**Comment by danmosemsft** [comment]
Assuming the above fixes this, this may be a servicing candidate.

**Comment by karelz** [comment]
@Anipik is master fully fixed by PR #24855?

**Comment by Anipik** [comment]
Yah master fully fixes the candidate

**Comment by karelz** [comment]
@Anipik fully fixed by just the PR #24855?

**Comment by danmosemsft** [comment]
We haven't gotten more feedback, so I'm going to close this as fixed in 2.1
