### ISSUE TITLE
Customer adoption Epic

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#24751]
This Epic covers work we are doing in CoreFX to make it easier for existing .NET Framework customers to use .NET Core. For example, the recently announced portability package.

It also covers outreach to NuGet package owners to help them repackage/support .NET Standard 2.0.

Like all our Epics in order to see the child work items you must have the free [Zenhub browser plugin ](https://www.zenhub.com/) enabled.

**Comment by danmosemsft** [comment]
The [API compatibility analyzer](https://blogs.msdn.microsoft.com/dotnet/2017/10/31/introducing-api-analyzer/) is important to this goal and is tracked in https://github.com/dotnet/platform-compat/. Maybe it should have a sub Epic.

**Comment by tarekgh** [comment]
@danmosemsft do we still have anything we need to do here?

**Comment by danmosemsft** [comment]
Yeah let's leave it a bit.

**Comment by danmosemsft** [comment]
Moving to Future as we completed 2.1 work except for the compat pack which is separately tracked

**Comment by stephentoub** [comment]
We're not using epics anymore, per @danmosemsft.
