### ISSUE TITLE
System.IO.IOException: The system cannot find message text for message number 0x%1 in the message file for %2\r\n

### ISSUE THREAD

**Issue by schalkvanwyk** [dotnet/corefx#24753]
Hi

It seems there is bug in the way exception messages are looked up.

I'm getting the following exception when trying to move a file:

> System.IO.IOException: The system cannot find message text for message number 0x%1 in the message file for %2\r\n   at System.IO.Win32FileSystem.MoveFile(String sourceFullPath, String destFullPath)\r\n   at System.IO.File.Move(String sourceFileName, String destFileName)

The exception seems to materialize from the call to Win32Marshal.GetExceptionForWin32Error in 
[System.IO.Win32FileSystem.MoveFile(String sourceFullPath, String destFullPath)](https://github.com/dotnet/corefx/blob/e791e8b7a4f1e4d6ff5b4295fad04a6c9f65e909/src/System.IO.FileSystem/src/System/IO/Win32FileSystem.cs#L381)

Regards

**Comment by danmosemsft** [comment]
@schalkvanwyk do you have a way for us to reproduce this? If not, can you figure out what error code is getting passed to Win32Marshal.GetExceptionForWin32Error?

**Comment by JeremyKuhne** [comment]
Please reopen if a repro is available.
