### ISSUE TITLE
Create aggressive read/write concurrency test for SslStream

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#24759]
https://github.com/dotnet/corefx/issues/24142#issuecomment-330671855 has identified that we don't work well on macOS with the 2.0.0 product (in... some... circumstances?) when an async read is blocked-running while a write writes to the same SslStream object.

Since the scenario is one that we find virtuous, we should have a test to ensure that once the macOS version is fixed that it doesn't regress (and that the other platforms are meeting the guarantee and not regressing, either).

(cc @karelz @Priya91 @wfurt)

**Comment by wfurt** [comment]
do you envision sone kind of automation @bartonjs - for example similar to perf tests? 
Do you have any recommendations for concurrency and duration?

**Comment by bartonjs** [comment]
I don't really have any particular expectation of how it would work.  But "crashes 3 out of 4 times on the current macOS build" (current now, not current when it gets written) would be a good goal to start with (so that with the fix it stops crashing and we have confidence in the fix).
