### ISSUE TITLE
Machine Learning Epic

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#24761]
This Epic is to track work in CoreFx for the ML scenario. We expect this to principally include introducing a Tensor exchange type.

Like all our Epics in order to see the child work items you must have the free [Zenhub browser plugin ](https://www.zenhub.com/) enabled.

**Comment by danmosemsft** [comment]
@eerhardt do you have enough to break out some work items here into issues I can link to this (your) epic? Minor things can alternatively be noted in here. The idea is we we can look at this page periodically to get an idea of status/progress.

**Comment by danmosemsft** [comment]
Comments on this work are welcome here or on individual issues. Collaboration is also welcome: work with @eerhardt

**Comment by tarekgh** [comment]
@eerhardt @danmosemsft do we still have anything we need to do here for 2.1?

**Comment by danmosemsft** [comment]
No

**Comment by stephentoub** [comment]
We're not using epics anymore, per @danmosemsft.
