### ISSUE TITLE
Need a list of enhancements/features from .NET Core that incorporated into .NET Framework

### ISSUE THREAD

**Issue by eriawan** [dotnet/corefx#24769]
# Background

Since .NET Core has been around, some of the enhancements/optimizations are put into .NET Framework.
For example, this blog post seems to provide description of optimization in .NET Core 2.0 and .NET Framework 4.7: [https://blogs.msdn.microsoft.com/dotnet/2017/06/07/performance-improvements-in-net-core/](https://blogs.msdn.microsoft.com/dotnet/2017/06/07/performance-improvements-in-net-core/)
In that article, it's nice to have an article that describe the optimizations, but there's no easy way to see the detail of optimizations in terms of what changes. especially in the forms of detailed summary of changes in the perspective of commits and merges.

# Problem
Since there's no easy way to quickly see solved issues or merged PR that is related to these enhancements in .NET Core that is also made in .NET Framework, it's hard for most developers to justify the upgrade of older version (example: 4.6.x) to 4.7 or even 4.7.1, rather than waiting for the MS product lifecycle to enter post-mainstream support. Also it's hard to see in the perspective of .NET Framework users, because .NET Framework is closed source in nature.

I know that I can open .NET Framework refererencesources, but I see that as _"read only"_ because it's not open source as the nature of .NET Core.
Is there any way we could have what enhancements/optimizations/feature additions that incorporated from .NET Core to .NET Framework? 

# Proposal
These are my proposals:

1. Not just having the list of related merge/commits of what .NET Core version mapped to which .NET FW version, it would be also nice to have the detail of what breaking changes might be.
2. IF this list will be long and exhaustive, maybe it's better to have its own repo such as "netcore-netfw-featuremap" or whatever. Therefore many of us (especially non-MS FTE contributors) can amend or make the list better with actual sample code or article, just like the blog I've mention above.

Any feedback welcome! 
cc @danmosemsft , @Petermarcu

**Comment by benaadams** [comment]
That over here?

https://github.com/Microsoft/dotnet/blob/master/releases/net471/README.md

**Comment by benaadams** [comment]
Historic changes are in the same repo https://github.com/Microsoft/dotnet/tree/master/releases

**Comment by eriawan** [comment]
> https://github.com/Microsoft/dotnet/tree/master/releases/net471

Thanks!
Yes, but that list is mixed of .NET FW bugfix and related .NET Core enhancements, It's quite near what I want, but I just want a list that contains what .NET Core brings to .NET FW. 
IMHO it's a little bit harder to dissect quickly the features/fixes/enhancements from .NET Core to .NET FW, because I have to look at the detailed bullets one by one.

**Comment by danmosemsft** [comment]
@eriawan I realize you said you don't see https://github.com/Microsoft/referencesource as part of a solution, but in case it's helpful to others, the commits in there are labeled with the release. So eg.,
`git diff 90b323fe52bec428fe4bd5f007e9ead6b265d553...b31308b03e8bd5bf779fb80fda71f31eb959fe0b` shows me a diff between 4.7 and 4.7.1 (albeit missing anything that's not in referencesource for some reason)

**Comment by eriawan** [comment]
>  I realize you said you don't see https://github.com/Microsoft/referencesource as part of a solution, but in case it's helpful to others, the commits in there are labeled with the release. So eg.,
git diff 90b323fe52bec428fe4bd5f007e9ead6b265d553...b31308b03e8bd5bf779fb80fda71f31eb959fe0b shows me a diff between 4.7 and 4.7.1

That's a good idea, @danmosemsft 👍 
Ok, I'm going to look at the referencesource again.

**Comment by mattwarren** [comment]
If you don't want to download referencesource and run `git diff` locally you can actually do this comparison directly on GitHub.com, see https://github.com/Microsoft/referencesource/compare/90b323fe...b31308b0 (diff between 4.7 and 4.7.1)

**Comment by eriawan** [comment]
Thanks @mattwarren !

I've been able to see the diff, now I need to have those git diff as CSV or something else so it should be easier to look and read.
Ok, I'm able to see the diff without looking directly at the source code. I'm closing this.

Thanks again guys!

**Comment by mattwarren** [comment]
> I've been able to see the diff, now I need to have those git diff as CSV or something else so it should be easier to look and read.

You can partially do that by putting `.diff` (or `.patch`) on the end of the url, like so https://github.com/Microsoft/referencesource/compare/90b323fe...b31308b0.diff
