### ISSUE TITLE
Add optimized path for IReadOnlyCollection/IReadOnlyList in System.Linq

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/corefx#24773]
It's kind of historical reason for the readonly interfaces not inherited by `ICollection<T>`/`IList<T>`.
Adding a optimized path needs a copy of all `ICollection<T>`/`IList<T>` paths and classes.
Implementing `ICollection<T>` with `IsReadOnly = true` does get the optimizations, but it's kind of violating the interfaces.

**Comment by stephentoub** [comment]
Optimized path in what?  What optimizations?  What's the scenario?

**Comment by huoyaoyuan** [comment]
Sorry for forgetting type LINQ in the title.

**Comment by molinch** [comment]
@stephentoub @huoyaoyuan It's not just about Linq but also in many other areas like: List.InsertRange, see: http://referencesource.microsoft.com/#mscorlib/system/collections/generic/list.cs,711

If you give an IReadOnlyCollection it will instanciate an Enumerator and iterate, whereas it could be super optimized.

**Comment by stephentoub** [comment]
> It's not just about Linq but also in many other areas like: List.InsertRange [...] otherwise it could be super optimized [...]

Yes. But adding that `IReadOnlyCollection<T>` type check is an expense that's paid for all enumerables, not just `IReadOnlyCollection<T>`.  As with many optimizations, you make some things faster at the expense of making other things slower, and the upside needs to be worth the downside.  As you pointed out, most enumerables in the core libraries that are `IReadOnlyCollection<T>` also implement other interfaces already optimized for, so the upside for the majority of collections people use is small.  To take such a change, there'd need to be a solid set of data provided about what the positive and negative impacts would be and why it's worthwhile.

> shouldn't ICollection implement IReadOnlyCollection?

It's actually a breaking change.  See https://github.com/dotnet/corefx/issues/5489 for an example.

**Comment by molinch** [comment]
Thanks @stephentoub for the quick feedback.
Couldn't what Nick shows be solved by the C# compiler?

Just another remark related to this, Array.cs doesn't implement IReadOnlyList neither IReadOnlyCollection. Would you accept a PR doing so?

**Comment by stephentoub** [comment]
> doesn't implement IReadOnlyList neither IReadOnlyCollection

Arrays do, they're just a very special type and the implementation is provided by the runtime, i.e. this works fine:
```C#
using System;
using System.Collections.Generic;

class Program
{
    static void Main()
    {
        var data = new int[1] { 42 };
        IReadOnlyList<int> list = data;
        Console.WriteLine(list[0]);
    }
}
```

**Comment by molinch** [comment]
That's interesting! I expected what is in Array.cs to be the source of truth.
Thanks a lot for the explanation.

**Comment by mattwarren** [comment]
@molinch `<shameless plug>` if you want more info on this, see a blog post I wrote [Arrays and the CLR - a Very Special Relationship](http://mattwarren.org/2017/05/08/Arrays-and-the-CLR-a-Very-Special-Relationship/), in particular the 'Implementation Details' section  `</shameless plug>`

**Comment by molinch** [comment]
Many things are much more clear, thanks @mattwar !
I love the sentence "Arrays are basically voodoo." hahaha

**Comment by stephentoub** [comment]
Closing as dup of https://github.com/dotnet/corefx/issues/26579
