### ISSUE TITLE
Add RemoveIfValue to ConcurrentDictionary

### ISSUE THREAD

**Issue by CornedBee** [dotnet/corefx#24770]
EDIT by: @scalablecory 

@CornedBee I'd like to get this suggestion to a point where it can be reviewed as a proposal. What do you think of this?

@safern what do you think?

# Rationale and Usage

`ConcurrentDictionary` has an implementation of "remove if" hidden away inside of the private `ICollection<T>.Remove`. Usage of this looks like:
```c#
void DecrementCount(ConcurrentDictionary<string, int> dict, string key)
{
    while(true)
    {
        int current = dict[key];

        if(current != 1)
        {
            if(dict.TryUpdate(key, current - 1, current))
            {
                return;
            }
        }
        else
        {
	    ICollection<KeyValuePair<string, int>> col = dict;
            if(col.Remove(new KeyValuePair<string, int>(key, current)))
            {
                return;
            }	
        }
    }
}
```

This proposal is to expose this existing feature in a more friendly and discoverable API. New usage:
```c#
void DecrementCount(ConcurrentDictionary<string, int> dict, string key)
{
    while(true)
    {
        int current = dict[key];

        if(current != 1)
        {
            if(dict.TryUpdate(key, current - 1, current))
            {
                return;
            }
        }
        else
        {
            if(dict.TryRemoveIf(key, current))
            {
                return;
            }	
        }
    }
}
```

The discoverability issue:
* https://stackoverflow.com/q/8723585
* https://stackoverflow.com/q/27297326
* https://stackoverflow.com/q/39516516
* https://stackoverflow.com/q/39679779
* @stephentoub's https://devblogs.microsoft.com/pfxteam/little-known-gems-atomic-conditional-removals-from-concurrentdictionary/

# Proposed API

```c#
class ConcurrentDictionary<>
{
    public bool TryRemoveIf(TKey key, TValue comparisonValue);
}
```

# Approved API
```c#
class ConcurrentDictionary<>
{
    public bool TryRemove(KeyValuePair<TKey key, TValue> keyValuePair);
}
```

# Details

* This brings parity with `TryUpdate`.
* Unfortunately we have a wart: the existing `TryRemove` does not compare a value, but `TryUpdate` does. `TryRemoveIf` will therefor have naming inconsistent with one of them.

# Open Questions

* Should we make the existing method public? Not sure if reasonable API signature.
* It could be useful to return a type other than `bool` that indicates one of: removed, key not found, or value not found.
* It could also be useful to return the original `value` in an out param.
   * This would avoid rehashing in a spin loop. Existing implementation inside of `ConcurrentDictionary` has spin loops that do this, so the feature already exists and it's clearly a useful optimization, but avoiding rehashing in general is a larger discussion.
   * It would also allow some cleanup if the value removed is "equal" but not the same instance, though I'm not sure how common this is.
* This API, along with the existing `TryUpdate`, has a non-obvious complication in that it only uses the default comparer for a type: the example above would not work as the user intended if `MyState` is a `class` that hasn't overridden `Equals`. It may be worth trying to make this easier to use.
   * There's worry that `TryRemoveIf`'s use case has greater exposure to misuse, and it may be worth keeping it hidden to avoid that.
* Do we want to support custom comparers for values? I can't see a big use case for this, and if we need more flexibility here I would prefer a general `TryRemoveIf(TKey key, Func<TKey, TValue, object, bool> comparer, object state)`.

**Comment by ianhays** [comment]
This seems like a reasonable proposal. I wonder if it might be better just to make the ICollection remove public instead of adding a new API though.

**Comment by CornedBee** [comment]
It would mean allocation of a temporary KeyValuePair object just to call that method.

**Comment by yizhang82** [comment]
I just ran into the exact same problem and my workaround is the same - just cache ICollection and use `ICollection.Remove`. 

One problem with the current `ICollection.Remove` implementation is that it always uses the default comparer, which isn't always what one would want. 

```
 bool valuesMatch = EqualityComparer<TValue>.Default.Equals(oldValue, curr._value);
```

So adding an `TryRemoveIf` API with a new overload and also allowing passing a value comparer in constructor would be helpful.

**Comment by scalablecory** [comment]
This would bring feature parity with `ConcurrentDictionary.TryUpdate`, and would be useful.

**Comment by scalablecory** [comment]
We've got these two APIs already:

```c#
public bool TryRemove(TKey key, out TValue value);
public bool TryUpdate(TKey key, TValue newValue, TValue comparisonValue);
```

So I'd like to see these overloads added:

```c#
class ConcurrentDictionary<>
{
    public bool TryRemove(TKey key, out TValue value, TValue comparisonValue);
    public bool TryRemove(TKey key, out TValue value, TValue comparisonValue, IEqualityComparer<TValue> comparer);
    public bool TryUpdate(TKey key, TValue newValue, TValue comparisonValue, IEqualityComparer<TValue> comparer);
}
```

**Comment by safern** [comment]
I agree with @ianhays old comment, I think to make it less confusing, wouldn't make sense to just make `ICollection.Remove(KeyValuePair<TKey, TValue>` public?

That would also make it consistent with other collections and APIs in the framework where the way to remove is through a `Remove` API which returns a `bool`. 

@scalablecory thoughts on that?

**Comment by scalablecory** [comment]
@safern Dictionaries have avoided operating on `KeyValuePair`, and `ConcurrentDictionary` has a `Try` theme going on. I assume these are the reasons `Remove` is currently explicitly implemented -- it would not be consistent.

**Comment by safern** [comment]
I agree it has avoided to operate on`KeyValuePair` but in Dictionary we don’t have a `TryRemove`, we have a `Remove(TKey)`

https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.remove?view=netframework-4.8

I agree the `TryRemove` in ConcurrentCollection broke this consistency, but TryRemoveIf was confusing at first sight, because there is no condition, basically the `if` is referring to, if the TKey contains a TValue, which at the end `Remove(KeyValuePair<TKey, TValue>)` speaks for itself. That is why IMHO the latter is the one that fits best for this scenario.

@stephentoub who has experience with ConcurrentCollections might have insights as well.

**Comment by stephentoub** [comment]
> Dictionaries have avoided operating on KeyValuePair

Really?  It's part of the `IDictionary<>` interface.

> TryRemoveIf was confusing at first sight

I agree... the `If` is confusing.  Why can't it just be an overload of the existing TryRemove?

> Since ConcurrentDictionary has already introduced the Try pattern, we could just add an extra override of TryRemove without the if that accepts both the TKey and TValue

That would be my preference.

> if(dict.TryGetValue("foo", out MyState state) && state.Count == 0) dict.TryRemoveIf("foo", state);

All that said, this example used to motivate this API has a race condition: state.Count could change away from 0 after the check and before the TryRemove call. No?

**Comment by bartonjs** [comment]
> Why can't it just be an overload of the existing TryRemove?

TryRemove(key, value) vs TryRemove(key, out value) have very different meanings (one is double-input conditional, one is single-input conditional).  Do we have a similar place where we have an overload differing by ref-ness with a similar complexity change?  It sort of makes sense when it's "more" complicated instead of "differently" complicated: `TryRemove(TKey key, TValue matchValue, out TValue existingValue)`.

Based on the sample usage with the double-dip, it seems like it really wants a predicate overload: 

```C#
bool TryRemove(TKey key, Predicate<TValue> predicate, out TValue existingValue);

...

if (dict.TryRemove("foo", s => s.Count == 0, out MyState state))
{
    // Yep
}
else if (state != null)
{
    // Predicate didn't match
}
else
{
    // Key didn't match (or key stored null)
}
```

**Comment by stephentoub** [comment]
> it seems like it really wants a predicate overload

That predicate would need to be invoked while holding one of the dictionary's locks.  We've stayed away from that as it can easily lead to deadlock.

**Comment by bartonjs** [comment]
Wouldn't AddOrUpdate, when invoking `updateValueFactory`, be in the same state? (Perhaps it's "yes, and it leads to deadlock all the time")

**Comment by scalablecory** [comment]
> Really? It's part of the IDictionary<> interface.

Outside of explicitly implemented members, we have no methods that mutate a dictionary taking a KeyValuePair.

Doesn't mean it can't be done, but it would not be look right.

**Comment by scalablecory** [comment]
> this example used to motivate this API has a race condition: state.Count could change away from 0 after the check and before the TryRemove call. No?

It depends on the type of `state`. I call this out in open questions. Note, TryUpdate and ICollection.Remove have the same issue -- this isn't immediately obvious to users.

**Comment by scalablecory** [comment]
> TryRemove(key, value) vs TryRemove(key, out value) have very different meanings (one is double-input conditional, one is single-input conditional).

The struggle with this API is that you want similar naming to TryUpdate, which is a "double-input conditional", but TryRemove is already taken for a different purpose with a signature that varies only by a `ref`.

A `TryRemove(key, value, ref oldvalue)` would actually allow more efficient usage in a spin loop, so I'm not opposed to it, but it does feel strange to me to be moving the ref's position when the 2nd arg has the same type.

TryRemoveIf is not an ideal name, because, yea, I'd expect it to take a predicate too.

**Comment by benaadams** [comment]
`KeyValuePair<TKey, TValue>` makes more sense to me; as what you are trying to remove is literally the key value pair when both the key and value are equal to the given one; you want to remove both the key and value.

**Comment by benaadams** [comment]
`KeyValuePair<TKey, TValue>` makes more sense to me; as what you are trying to remove is literally the key value pair when both the key and value are equal to the given one; you want to remove both the key and value. i.e. remove this ValueType from the dictionary if its there.

**Comment by stephentoub** [comment]
> Outside of explicitly implemented members, we have no methods that mutate a dictionary taking a KeyValuePair.

This isn't impacted by whether something is explicitly or implicitly implemented. If I'm using an IDictionary<>, that API is there front and center, available in IntelliSense, doesn't require any casting to call it, etc.

> Note, TryUpdate and ICollection.Remove have the same issue 

Remove makes no promise about comparing a value, and the comparison TryUpdate does is limited to equality. This is a very different issue, with the intended use case being one that's not safe.

> KeyValuePair<TKey, TValue> makes more sense to me

I'm fine with that. But I would still like to understand the use cases.

**Comment by scalablecory** [comment]
> This is a very different issue

I think we've crossed some wires -- this issue is much simpler to me than I'm hearing you state it. Fundamentally what I'm asking for is to surface `ICollection<>.Remove` as an API that is idiomatic to `ConcurrentDictionary`, as we have done with several other `ICollection<>` and `IDictionary<>` APIs.

> the comparison TryUpdate does is limited to equality. This is a very different issue, with the intended use case being one that's not safe.

`TryRemoveIf` would have identical functionality to its implementation of `ICollection<>.Remove`, which has the same safety as `TryUpdate`.

> This isn't impacted by whether something is explicitly or implicitly implemented.

At some point, we decided that `ICollection<>.Remove`, and any other mutation APIs which take `KeyValuePair`, were not suited for the exposed API in `Dictionary` or `ConcurrentDictionary` and chose to explicitly implement them. Instead we wrote methods which take key and value in separate parameters.

It is worth considering if we want to break with this decision. I'm not strongly opposed to it, but I do think it's a clear break.

> Remove makes no promise about comparing a value,

This as a documentation shortcoming.

`Dictionary<TKey,TValue>` implements `Remove` such that it only removes the element if both the key and the value match the data in the dictionary, and thus `ConcurrentDictionary<TKey,TValue>` does the same.  And as it’s a concurrent data structure, `ConcurrentDictionary<TKey,TValue>` ensures that the comparison is done atomically with the removal.  Tada!

(this is a quote from [your blog](https://devblogs.microsoft.com/pfxteam/little-known-gems-atomic-conditional-removals-from-concurrentdictionary/)).

**Comment by stephentoub** [comment]
> At some point, we decided that ICollection<>.Remove, and any other mutation APIs which take KeyValuePair, were not suited for the exposed API in Dictionary or ConcurrentDictionary

I'm not sure where you're getting that from. I designed ConcurrentDictionary.  Whether an API took KeyValuePair was not part of the decision to leave Remove explicitly implemented.  Rather, it was that we were using Try prefixes to help connote the transient nature of state in the dictionary and to impress upon folks that every mutating operation couldn't depend upon previously validated state.

> This is a documentation shortcoming.

We're talking past each other; my point has nothing to do with the documentation, and the quote you cited from my blog is also not relevant.

> this issue is much simpler to me than I'm hearing you state it.

It's not to me.

The point I was trying to make is that you shared a single use case to motivate adding a public API, and in many cases, that use case is exactly why we cared about the Try prefix: the example is buggy 9 times out of 10.  Your example is factoring in more information than whether two objects are equal: you're attempting to implement a compound operation that only does the removal if a property on the object is a certain value, and that is inherently unsafe if there's any chance that value could change... which is generally going to be the case with an example like you used.  The Count in your example could of course be immutable, but most of the times I've seen people use a pattern like what you've done is as part of a scheme where multiple consumers are using some state stored in the dictionary, they're ref counting that mutable state, and when it hits zero, they want to remove it.  The API being proposed will not solve that problem well.

> which has the same safety as TryUpdate

TryUpdate is not used in the pattern you've described as the motivating reason for this API.

> TryRemoveIf would have identical functionality to its implementation of ICollection<>.Remove,

Yes, but if you're using the functionality via the interface, then you're generally not going to be relying on it for thread-safety.

I'm not against the functionality.  As you say, it's already there, just hidden.  But we're now talking about adding it as a prominent public API on the type, and for that we need a good reason that outweighs the liklihood that it'll be abused and actually lead to more problems than it solves.

**Comment by scalablecory** [comment]
I've updated the sample in the proposal to something more reasonable.

**Comment by scalablecory** [comment]
> we're now talking about adding it as a prominent public API on the type, and for that we need a good reason that outweighs the liklihood that it'll be abused and actually lead to more problems than it solves.

This is my concern as well. `ConcurrentDictionary` is certainly not an "expert-only" class. I think `TryUpdate` has the same issue, but if we can think of more cases where a `TryRemoveIf` would be misused, I'm swayable toward thinking this isn't a good idea.

**Comment by CornedBee** [comment]
> All that said, this example used to motivate this API has a race condition: state.Count could change away from 0 after the check and before the TryRemove call. No?

Avoiding that race condition is exactly why I needed the value-comparing remove. Note that `state.Count` must participate in the equality check of `MyState` for this to work, but that should be kind of obvious. Perhaps my perspective is skewed there.

And if `MyState` is a reference type (it's a value type in my own code) and `Count` is mutable, then yes, there's a race. But it's a data race on `Count` itself, and unaffected by the semantics of `TryRemoveIf`.

**Comment by terrajobst** [comment]
If we're adding it, it should be `TryRemove(KV<K, V>)`.

**Comment by scalablecory** [comment]
From API design: needs good documentation to note `EqualityComparer` behavior to prevent misuse.

**Comment by stephentoub** [comment]
> From API design: needs good documentation to note EqualityComparer behavior to prevent misuse.

I was actually referring to good and bad usage patterns for the API.  But adding details about EqualityComparer is good, too.
