### ISSUE TITLE
netcoreapp build vertical needs to be buildable without previous versions

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#24776]
See comment at https://github.com/dotnet/corefx/pull/24708#discussion_r145993635.

For our netcoreapp build vertical we need to be able to build it against the latest version without needing to restore the older packages. This is for the build-from-source efforts which require us to build all the assets instead of restoring them.

**Comment by weshaggard** [comment]
@danmosemsft this is an issue that we should do a sweep of once we finish the compat work.

**Comment by danmosemsft** [comment]
@safern assigned to you as this seems like a natural part of what you're doing.

**Comment by weshaggard** [comment]
Duplicate of https://github.com/dotnet/corefx/issues/23220
