### ISSUE TITLE
socket server shutodown  linux client socket still established

### ISSUE THREAD

**Issue by caozhiyuan** [dotnet/corefx#24787]
tcp        0 159660 192.168.139.132:33693   10.1.4.204:2181         ESTABLISHED

socket server(10.1.4.204:2181) shutodown,  linux client socket still established

how to deal with it.

**Comment by stephentoub** [comment]
Can you share a repro of the problem you're facing?

**Comment by caozhiyuan** [comment]
run zkserver in windows cmd, run zkclient repro in linux  ,then close server and 2 sec after open server, in linux use netstat -nta , socket still established. now i set a idel time to reconnect but always connect timeout.  zkclient repro in windows is ok.  code in ClientConnectionRequestProducer.cs file, repro: https://github.com/caozhiyuan/ZooKeeperNetCore.git

**Comment by caozhiyuan** [comment]
@stephentoub

**Comment by LYP951018** [comment]
How could you know this is a corefx issue not you library's bug?

**Comment by caozhiyuan** [comment]
@LYP951018  in windows  work fine

**Comment by caozhiyuan** [comment]
socket server shutodown client socket still established it's normal , i would like to know in linux socket it has some way to avoid this

**Comment by caozhiyuan** [comment]
ZooKeeperNetEx lib is ok , close this issus
