### ISSUE TITLE
[Api] BuilderMethodAttribute

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#24795]
From https://github.com/dotnet/coreclr/pull/14608

## Motivation

From looking at a stack trace (or using the `StackFrame`s) there's a lot of noise; but perhaps more importantly there isn't enough detail to tell what overloads of a method were called for async and iterators due to the name mangling prior to `.MoveNext()`.

e.g.
```csharp
at Program.<MethodAsync>d__11.MoveNext() 
```
Which of these overloads is it?
```csharp
public async Task<int> MethodAsync(long count, string name);
private static async Task<int> MethodAsync(long count);
private async Task<int> MethodAsync(int count);
```

Using stack traces can be made a more productive experience; whether trying to identify causes from logs and what code to look at, or just to not be daunting to new developers. 

e.g.

Useful stack trace output
```
   at System.Linq.Enumerable.SkipWhileIterator[TSource](IEnumerable`1 source, Func`3 predicate)
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Program.LinqIteration(Int32 count)
   at Program.Iterator(Int64 count, Int32 value)
   at Program.MethodAsync(Int32 count) 
   at Program.ConfiguredAsync(Int32 count)
   at Program.Main(String[] args) 
```
Rather than the more impenetrable 
```
   at System.Linq.Enumerable.<SkipWhileIterator>d__179`1.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Program.LinqIteration(Int32 count) 
   at Program.<Iterator>d__4.MoveNext()
   at Program.<MethodAsync>d__14.MoveNext()
   at Program.<ConfiguredAsync>d__13.MoveNext()
   at Program.<Main>d__0.MoveNext()
```

## Proposed Api

```csharp
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Constructor | AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
    public class BuilderMethodAttribute : Attribute
    {
        public BuilderMethodAttribute(MethodBase builderMethodType)
        {
            BuilderMethodType = builderMethodType;
        }

        public MethodBase BuilderMethodType { get; }
    }
}
```

## Usage
A compiler (e.g. Roslyn) would add the attribute to the generated class/struct/method that the method builds e.g.
```
.class auto ansi sealed nested private beforefieldinit '<MethodAsync>d__11'
       extends [System.Runtime]System.Object
       implements [System.Threading.Tasks]System.Runtime.CompilerServices.IAsyncStateMachine
{

  .custom instance void 
  CompilerGeneratedAttribute::.ctor() = ( 01 00 00 00 )   
  BuilderMethodAttribute::.ctor(class System.Reflection.MethodInfo) = ...MethodAsync(int count)...
} // end of class '<MethodAsync>d__11'

```

## Related Items

Currently the Builder Method for async/iterators is marked with either `IteratorStateMachineAttribute` or `AsyncStateMachineAttribute` which points at statemachine Type which gets constructed; however there is no-reverse linkage; so it is not possible only using the type system (short of searching) to match back to the source method.

PDBs produce line numbers for the source code rather than generated code; but you don't always have pdbs to produce line numbers. 

Equally it would be useful if stack traces reflected the source code rather than adjunct code 

i.e.
For 99% of cases is 
```
at System.Linq.Enumerable.<SkipWhileIterator>d__179`1.MoveNext()
```
more or less helpful than?
```
at System.Linq.Enumerable.SkipWhileIterator[TSource](IEnumerable`1 source, Func`3 predicate)
```
## Questions

* Is it enough to also cover more general Generators?
* Don't think it covers anonymous types (e.g. lambas/closures)

/cc @jaredpar @tmat @aelij @stephentoub @noahfalk

**Comment by benaadams** [comment]
Roslyn issue https://github.com/dotnet/roslyn/issues/22803

**Comment by tmat** [comment]
A few points:

1) Custom attributes can't have MethodBase as an argument. It would need to be an Int32 (token). That is also problematic though. When an assembly is processed by an IL rewriter the rewriter would need to know about this attribute to update the token, if the token changes during the rewriting. 

2) This information is already encoded in the PDB. PDBs are perhaps not available in all scenarios, but aren't they available in most cases where we care about the stack trace being pretty?

3) Even if we added this attribute it's not gonna be available for libraries that are already built and being used. Then you'll get stack traces that are mixed - some frames are "pretty-printed" others aren't. 

4) You are correct that this attribute wouldn't cover many other compiler generated members that might appear in the trace. Some more general approach would be better.

**Comment by aelij** [comment]
@tmat 

> aren't they available in most cases where we care about the stack trace being pretty

NuGet packages normally do not contain PDBs. It's not just our own code we'd care about prettifying.

> Then you'll get stack traces that are mixed 

I'd be fine with a "best effort" approach. And not many libraries remain stagnant nowadays.

> Custom attributes can't have MethodBase as an argument

My original thought was to have an attribute containing a string with the method's signature, e.g. `MyMethod(Int32, String)`. That would have the disadvantage of locking in the format, and the advantage that it could handle harder cases like lambdas and local functions.

I'm not sure how I feel about the compiler doing this kind of work, but I don't see how else it could be done without parsing compiler-specific mangled names, like in @benaadams's previous PR.

**Comment by benaadams** [comment]
It as could be
```
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Constructor | AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
public class BuilderMethodAttribute : Attribute
{
    public BuilderMethodAttribute(MethodBase builderMethodType, string builderMethodName, BindingFlags builderMethodBindingFlags)
    {
        BuilderMethodBindingFlags = builderMethodBindingFlags;
        BuilderMethodType = builderMethodType;
        BuilderMethodName = builderMethodName;
    }

    public Type BuilderMethodType { get; }
    public string BuilderMethodName { get; }
    public BindingFlags BuilderMethodBindingFlags { get; }
}
```

Then can use `BuilderMethodType.GetMethod(BuilderMethodName, BuilderMethodBindingFlags)` and find which one has the matching `Type` in `StateMachineAttribute` to get the correct overload

**Comment by benaadams** [comment]
Still won't be able to match lambas and local functions back to their overloaded method source though :-/

**Comment by tmat** [comment]
@benaadams You need the full signature to match. The textual representation of such signature is possible but would add a significant amount of metadata size overhead.

@aelij In future NuGet packages are likely going to contain PDBs (at least Portable PDBs).

**Comment by tmat** [comment]
@benaadams Actually, you are right. Good point about looking for the attribute. Using that you'll just need the method name essentially.

**Comment by benaadams** [comment]
Hmm... do lambdas always create a class even if they don't capture? Could mark the method with the attribute of the class like the statemachine and allow multiple; then match in same way.

Local functions don't though it looks like.

**Comment by benaadams** [comment]
> In future NuGet packages are likely going to contain PDBs (at least Portable PDBs).

And coreclr/corefx runtime stuff? Still have no pdbs with 2.0 😢

**Comment by tmat** [comment]
@benaadams It's being worked on:  https://github.com/aspnet/Universe/issues/131#issuecomment-338266583. There are some details that need to be figured out.

**Comment by benaadams** [comment]
Can't seem to use `GetStateMachineKickoffMethod`
```csharp
MethodDebugInformationHandle methodDebugHandle = ((MethodDefinitionHandle)handle).ToDebugInformationHandle();
MethodDebugInformation methodInfo = reader.GetMethodDebugInformation(methodDebugHandle);

MethodDefinitionHandle mdh = methodInfo.GetStateMachineKickoffMethod();
if (!mdh.IsNil)
{
    Console.WriteLine("true"); // Outputs
    MethodDefinition method = reader.GetMethodDefinition(mdh); // Throws BadImageFormat
    string methodName = reader.GetString(method.Name);
    Console.WriteLine(methodName);
}
```

**Comment by benaadams** [comment]
`reader.GetMethodDefinition(mdh)`
```
{System.Reflection.Metadata.MethodDefinition}
    Attributes: 'reader.GetMethodDefinition(mdh).Attributes' threw an exception of type 'System.BadImageFormatException'
    Handle: {System.Reflection.Metadata.MethodDefinitionHandle}
    ImplAttributes: 'reader.GetMethodDefinition(mdh).ImplAttributes' threw an exception of type 'System.BadImageFormatException'
    Name: 'reader.GetMethodDefinition(mdh).Name' threw an exception of type 'System.BadImageFormatException'
    RelativeVirtualAddress: 'reader.GetMethodDefinition(mdh).RelativeVirtualAddress' threw an exception of type 'System.BadImageFormatException'
    RowId: 5
    Signature: 'reader.GetMethodDefinition(mdh).Signature' threw an exception of type 'System.BadImageFormatException'
    Treatment: None
    _reader: {System.Reflection.Metadata.MetadataReader}
    _treatmentAndRowId: 5
```
`reader.GetMethodDefinition(methodDebugHandle.ToDefinitionHandle())`
```
{System.Reflection.Metadata.MethodDefinition}
    Attributes: 'reader.GetMethodDefinition(methodDebugHandle.ToDefinitionHandle()).Attributes' threw an exception of type 'System.BadImageFormatException'
    Handle: {System.Reflection.Metadata.MethodDefinitionHandle}
    ImplAttributes:
` 'reader.GetMethodDefinition(methodDebugHandle.ToDefinitionHandle()).ImplAttributes' threw an exception of type 'System.BadImageFormatException'`
    Name: 'reader.GetMethodDefinition(methodDebugHandle.ToDefinitionHandle()).Name' threw an exception of type 'System.BadImageFormatException'
    RelativeVirtualAddress: 'reader.GetMethodDefinition(methodDebugHandle.ToDefinitionHandle()).RelativeVirtualAddress' threw an exception of type 'System.BadImageFormatException'
    RowId: 33
    Signature: 'reader.GetMethodDefinition(methodDebugHandle.ToDefinitionHandle()).Signature' threw an exception of type 'System.BadImageFormatException'
    Treatment: None
    _reader: {System.Reflection.Metadata.MetadataReader}
    _treatmentAndRowId: 33
```

**Comment by benaadams** [comment]
PDB probably the way to go; also have an alternative method https://github.com/dotnet/coreclr/pull/14655

**Comment by tmat** [comment]
>  MethodDefinition method = reader.GetMethodDefinition(mdh); // Throws BadImageFormat

This reader is a reader of the PDB -- it doesn't have MethodDefinitions in it. The PE image reader does. I'd just return the handle (or perhaps token which you can get by calling ```MetadataTokens.GetToken(handle)```) out of ```GetSourceLineInfo``` and propagate it to the stack formatting code, where you can get the right Reflection MethodInfo from the token.

**Comment by benaadams** [comment]
Would need an api change; however do think its better to go with the PDB+`GetSourceLineInfo` rather than attribute as it should also be possible to tie up lambdas; locals and closures this way? (Would also need to get the local function name somehow)

**Comment by tmat** [comment]
@benaadams I appreciate your passion for getting nice stack traces, but if you're trying to fix it for all compiler generated code you'll need to involve the Roslyn compiler team. This is a significant feature that needs to go thru proper design and review process and can't be implemented in a single PR. We need to figure out how to make it work across languages (at least C#, VB and F#, but others too) and for future versions as well. Is there a Roslyn issue tracking this? I think there is but can't find it now. 

What do you think about the problems I stated here re different languages having different views of the types https://github.com/dotnet/coreclr/pull/14652#issuecomment-338521072?

**Comment by benaadams** [comment]
> I appreciate your passion for getting nice stack traces, but if you're trying to fix it for all compiler generated code you'll need to involve the Roslyn compiler team.

I'm thinking of it as an "in the future" item :) I don't even have an idea of proposal for how lambdas/closures etc could be satisfactorily named - just mentioning that it would be good if they could be identified so at one point it *might* be possible.

> What do you think about the problems I stated here re different languages having different views of the types

In the links you highlighted each pdb has a language associated with it; so each trace *could* be output as per original source - which would make sense for source matching; however I think mixed mode would make many people unhappy. 

Equally they *could* all be formatted in the language of the exe - which might be helpful to the app developer - until they looked at the source.

There probably isn't a good one-size fits all; and something configurable, with a sensible default would likely take a while to reach consensus on. However, some interesting possibilities!

**Comment by tmat** [comment]
Yeah, there is bunch of possibilities and things to figure out. Hence the ask for a proper design. I'd prefer if we looked at the problem holistically instead of handling one kind of generated code at a time eventually ending with a hodgepodge of partial solutions. 

Since we already have the concept of state machine encoded in the PDBs as a first class entity I think using that now would be reasonable.

**Comment by benaadams** [comment]
> I appreciate your passion for getting nice stack traces 

Its purely self interest after helping to decipher one too many production stack traces. Empowering less experienced developers to more easily work out what's going on and where to look from a stack trace is good for them and good for me 😁 

> Since we already have the concept of state machine encoded

The statemachines for Async, IEnumerable/Linq are the big ticket items; also where the stack traces become hardest to read; so to me, that's more about not having unproductive stack traces.

I think stack traces can be improved further; but its a less pressing issue, and as you point out should be done as more of a big picture item.
