### ISSUE TITLE
CultureInfo behaves different on Windows / Linux

### ISSUE THREAD

**Issue by bassebaba** [dotnet/corefx#24797]
```
static void Main(string[] args)
{
            Console.WriteLine(Environment.OSVersion.Platform);
            var swedishProvider = new CultureInfo("sv-SE");
            var d = DateTime.Now;
            Console.WriteLine("");
            Console.WriteLine(d.ToString("d MMM yyyy HH:mm", swedishProvider));
}
```
When run on Ubuntu:
```
Unix
22 Okt. 2017 15:15
```
When run on windows 10:
```
Win32NT
22 okt 2017 15:22
```

The minor problem is that we have upper/lowercase "o" in month name.
The major problem is that Unix produces a . after the month name.
This is a problem when doing a DateTime.ParseExact since the parse fails on either system depending on the "." or not.

```
Windows:
6 okt. 2017 21:14     --> String was not recognized as a valid DateTime.
6 okt 2017 21:14      --> 2017-10-06 21:14:00

Linux
6 okt. 2017 21:14     --> 10/6/17 9:14:00 PM
6 okt 2017 21:14      --> String was not recognized as a valid DateTime.

```

Am I using this in the wrong way or is this a bug?
Is it faulty to expect "CultureInfo" to work the same way on Windows/Linux/Mac?

**Comment by danmosemsft** [comment]
@krwq @tarekgh

**Comment by tarekgh** [comment]
The framework depends on the OS for the globalization data in general. You should expect differences when running on different OS's or different OS versions. if you think the data is wrong in some instances, you can file an issue to the Windows team if it is Windows OS, or file the issue to ICU if it is Linux/OSX issue.
