### ISSUE TITLE
Unknown character appears after Path.Combine()

### ISSUE THREAD

**Issue by rvhuang** [dotnet/corefx#24806]
Target framework: .NET Core 2.0 (netcoreapp2.0)
Dotnet Core version: 2.0.2 (x64)
OS: Windows 10 Professional x64 (build 15063)

Considering simple code below:

```csharp
    var path = AppDomain.CurrentDomain.BaseDirectory;
    var file = Path.Combine(path, "‪testing.json");

    Console.WriteLine(AppDomain.CurrentDomain.BaseDirectory);
    Console.WriteLine(file);

```

The output shows strange behavior which has an unknown character between `path` and "testing.json".

    C:\ConsoleApp3\ConsoleApp3\bin\Debug\netcoreapp2.0\
    C:\ConsoleApp3\ConsoleApp3\bin\Debug\netcoreapp2.0\?testing.json

Note: the following code shows additional details about the unknown character: 

```csharp
    Console.WriteLine(char.GetNumericValue(file[path.Length]));
    Console.WriteLine(char.GetUnicodeCategory(file[path.Length]));
    Console.WriteLine((int)file[path.Length]);
```
 And the output is:

    -1
    Format
    8234

Please take a look at the issue. Thanks.

**Comment by jkotas** [comment]
Your code fragments contains weird invisible Unicode characters `0x202A` at the start of the "testing.json" string. Deleting the string in your code fragment and retyping it again makes everything work fine.

**Comment by rvhuang** [comment]
@jkotas  Thanks for replying! It's weird that the "invisible" character only pop up on .NET Console. I think the issue is okay to be closed then.
