### ISSUE TITLE
Socket.SendAsync not firing SocketAsyncEventArgs Completed event

### ISSUE THREAD

**Issue by Eastrall** [dotnet/corefx#24818]
I noticed that with `netcoreapp2.0` the `SocketAsyncEventArgs.Completed` event is not fired when data is sent using the socket `SendAsync` method. This causes some issues when we implement a sending queue along with an `AutoResetEvent`.

Since it's the first time I open an issue here, should I provide samples? Just let me know if you need more informations.

I am finding this issue only with `netcoreapp2.0`. Doesn't have this issue with `netcoreapp1.0`.

You can find here an implementation of my tcp socket client with `SocketAsyncEventArgs` : https://github.com/Eastrall/Ether.Network/blob/develop/src/Ether.Network/Client/NetClient.cs

**Comment by davidsh** [comment]
>Since it's the first time I open an issue here, should I provide samples? Just let me know if you need more information.

Yes, please include a full repro Visual Studio solution.  That will make it easier to troubleshoot and inspect the Socket APIs that you are using.

**Comment by stephentoub** [comment]
@Eastrall, what is the Boolean return value of SendAsync?  The SocketAsyncEventArg operations return a bool indicating whether they've completed or not, and if they've completed synchronously, then event won't be raised.  Optimizations in .NET Core 2.0 make it much more likely that operations like send will complete synchronously, making them much more efficient, but also potentially exposing bugs in consuming code that wasn't properly expecting them to be able to complete synchronously.

From:
https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.sendasync?view=netframework-4.7.1#System_Net_Sockets_Socket_SendAsync_System_Net_Sockets_SocketAsyncEventArgs_
```
Returns false if the I/O operation completed synchronously. In this case, The Completed event on the e parameter will not be raised and the e object passed as a parameter may be examined immediately after the method call returns to retrieve the result of the operation.
```

**Comment by Eastrall** [comment]
@stephentoub oh, yes, with that boolean I can check if I wait for a synchronous operation or not with my `AutoResetEvent` ...
I'll read the docs in details more carefully next time I have an issue... It will avoid disturbing for nothing... Since I didn't had this bug on `netcoreapp1.0`, I thought it was an issue on `netcoreapp2.0`. Wrong thought, my bad.

Thank you for your assistance. Solved.

**Comment by stephentoub** [comment]
Great, glad you got it sorted out.
