### ISSUE TITLE
FileSystemWatcher misleading exception message

### ISSUE THREAD

**Issue by makcakaya** [dotnet/corefx#24817]
I encountered an exception being thrown in an ASP.NET Core 2.0 project which said "The directory name {0} is invalid." and it was misleading. [`FileSystemWatcher`](https://github.com/dotnet/corefx/blob/724ddb8fc95a5b1f639cfa508a32b9a8c50c1949/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.cs#L108) throws an exception with this message, and in my case the path was valid but the directory did not exist.

"The directory name {0} does not exist." would be a more helpful message for me.

**Comment by danmosemsft** [comment]
@makcakaya would you like to submit a PR to fix the string?
Looks like the code calls Directory.Exists, which strictly speaking woudl return false and lead to this message if the path was actually invalid. But arguably it wouldn't exist in that case either so your proposal seems reasonble.

**Comment by makcakaya** [comment]
By the way, the `path.Length == 0` seems redundant because `Directory.Exists()` already includes the same check [here](https://github.com/dotnet/corefx/blob/724ddb8fc95a5b1f639cfa508a32b9a8c50c1949/src/System.IO.FileSystem/src/System/IO/Directory.cs#L74).

So, the line `if (path.Length == 0 || !Directory.Exists(path))` in [FileSystemWatcher](https://github.com/dotnet/corefx/blob/724ddb8fc95a5b1f639cfa508a32b9a8c50c1949/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.cs#L108) can be rewritten as `if(!Directory.Exists(path))` and throw an exception with the message "The directory name {0} does not exist.".

**Comment by danmosemsft** [comment]
@makcakaya that cleanup would be welcome. There should be single quotes `'` around the path btw.

**Comment by danmosemsft** [comment]
Somewhat related issue that's up for grabs: https://github.com/dotnet/corefx/issues/23710
