### ISSUE TITLE
Implement System.Net.Sockets on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#2482]

**Comment by SidharthNabar** [comment]
Pre-requisite for this work is - #896

**Comment by SidharthNabar** [comment]
#896

**Comment by MartinJohns** [comment]
In the latest Community Standup blog Jeffrey wrote:
> No new feature work is being developed - only completing existing APIs and features

Does this mean Sockets support won't be part of beta 8 (and thus within 1.0 release) anymore?

**Comment by stephentoub** [comment]
Sockets is part of "existing APIs and features". It's actively being worked on for Unix.

**Comment by MartinJohns** [comment]
Alright, thanks for the clarification! Looking forward to the next release. :-)

**Comment by joshfree** [comment]
i'm closing this issue now that the initial xplat sockets PR from @pgavlin is in master
