### ISSUE TITLE
System.IO.Pipelines Epic

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#24824]
Tracking item for productizing [System.IO.Pipelines](https://github.com/dotnet/corefxlab/tree/master/src/System.IO.Pipelines)

Related #24174

**Comment by stephentoub** [comment]
Which piece of pipelines do you envision moving to corefx?

**Comment by muratg** [comment]
@pakrym @KrzysztofCwalina @davidfowl

**Comment by pakrym** [comment]
@stephentoub Main `System.IO.Pipelines`  package + tests

**Comment by pakrym** [comment]
We were also hoping to move `MemoryPool*` and `IScheduler` to more suitable locations.

**Comment by kasper3** [comment]
Is this moving scoped to copy/pasting the directories and updating some xml files? Or would it also include using Pipelines in existing BCL types (<many>*Stream APIs, HttpClient, websocket etc.)?

**Comment by davidfowl** [comment]
The former. The latter would be a much bigger effort and *may* happen eventually but the first step is to BCLize the APIs and move them into corefx.

**Comment by joshfree** [comment]
@pakrym can you close this tracking issue out after your corefx PR is merged and the corefxlab copy of the code has been removed?

**Comment by kasper3** [comment]
Fixed by #27007 ✌️

**Comment by pakrym** [comment]
Not yet, corefxlab is not updated yet.
