### ISSUE TITLE
ClientWebSocket produces malloc exception in multi-threaded environments.

### ISSUE THREAD

**Issue by lwansbrough** [dotnet/corefx#24821]
Running a .NET Core 2.0 CLI app on macOS 10.12.6. ClientWebSocket version is the latest I believe.

When operating in a multi-threaded environment, I receive what looks like a C++ malloc exception.

This appears to be happening when the remote host terminates the connection unexpectedly. I have locks on reads + writes so there is never more than one of each happening at once. When I make a call to either `SendAsync` or `ReceiveAsync` and the connection has been terminated unexpectedly, I receive the following error:

```
dotnet(75902,0x700010355000) malloc: *** error for object 0x7fe5669dbf20: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

I can't say for certain whether or not the remote host has terminated the connection because I don't have a stack trace, but it is my suspicion as I know there is a rate limit on the web socket endpoint, and this issue only happens shortly after sustained requests exceed rate limit threshold.

I can't think of any way of preventing this issue in user code (other than a rate limiter but that only stops a certain type of unexpected termination.)  Adding a lock won't solve it because the the connection could be terminated between when I call ReceiveAsync and when ReceiveAsync reaches the point in native code where it breaks.

**Comment by davidsh** [comment]
Is this happening on Windows or Unix?  Please specify the exact platform.

**Comment by lwansbrough** [comment]
Yeah sorry, I updated the question: Unix, macOS 10.12.6.

**Comment by stephentoub** [comment]
cc: @bartonjs

**Comment by lwansbrough** [comment]
^ This is definitely interesting. I was in fact using a `wss://` URI. Switching to `ws://` to test now... It's definitely more stable. Haven't received the error yet!
