### ISSUE TITLE
Internal relative relationships for System.IO.Packaging.Package fail to load on Mono

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/corefx#24822]
Uri parsing on Mono has a quirk when parsing a Uri that if you pass `UriKind.RelativeOrAbsolute`, a forward slash `/` is treated as absolute while in .NET Framework this would be parsed as relative. This causes packaging to break when reading a package file (for a real example, see OfficeDev/Open-XML-SDK#249 where DocumentFormat.OpenXml fails to load documents on Xamarin) where internal relationships are managed by relative Uris.

There are a few workarounds available (see www.mono-project.com/docs/faq/known-issues/urikind-relativeorabsolute/ for details):

1. Use a special `UriKind` defined by Mono when run on that runtime; ie `(UriKind)300`
2. Set an environment variable to force all Uri instances that start with a forward slash to be parsed as relative (`export MONO_URI_DOTNETRELATIVEORABSOLUTE=true`)

## Potential Fix
There is a single instance of `UriKind.RelativeOrAbsolute` and it is while parsing internal relationships: https://source.dot.net/#System.IO.Packaging/System/IO/Packaging/InternalRelationshipCollection.cs,357. A potential fix to not require the environment variable would be to use `UriKind.Relative` when target mode is internal.

## Repro

```csharp
using (var ms = new MemoryStream())
{
    using (var package = Package.Open(ms, FileMode.OpenOrCreate, FileAccess.ReadWrite))
    {
        package.CreateRelationship(new Uri("/target", UriKind.Relative), TargetMode.Internal, "type");
    }

    ms.Position = 0;

    using (var package = Package.Open(ms, FileMode.OpenOrCreate, FileAccess.ReadWrite))
    {
        var relationships = package.GetRelationships();

        var relationship = Assert.Single(relationships);

        Assert.Equal(new Uri("/", UriKind.Relative), relationship.SourceUri);
        Assert.Equal(new Uri("/target", UriKind.Relative), relationship.TargetUri);
        Assert.Equal(TargetMode.Internal, relationship.TargetMode);
    }
}
```

## Expected

Successfully retrieve relationships and have asserts pass

## Observed

```
Unhandled Exception when attempting to call `package.GetRelationships()`:

System.ArgumentException: PackageRelationship target must be relative URI if TargetMode is Internal.
Parameter name: targetUri
```

**Comment by twsouthwick** [comment]
Appears that this is not just Mono, but .NET Core on Linux (https://github.com/dotnet/corefx/issues/22098).

**Comment by stephentoub** [comment]
cc: @tmds

**Comment by tmds** [comment]
> Appears that this is not just Mono, but .NET Core on Linux (#22098). I can't repro the exception on Linux. 

That is a different issue. It relates to .NET Core allowing Absolute uris starting with a slash, while .NET Framework does not.

> Uri parsing on Mono has a quirk when parsing a Uri that if you pass UriKind.RelativeOrAbsolute, a forward slash / is treated as absolute while in .NET Framework this would be parsed as relative.

This is a quirk on Mono, .NET Core parses these as relative (like .NET Framework).
```
            var uri = new Uri("/tmp/file", UriKind.RelativeOrAbsolute);
            Console.WriteLine($"IsAbsolute: {uri.IsAbsoluteUri}");
```
outputs:
```
IsAbsolute: False
```

Your request is to make a change so "_System.IO.Packaging_" works out-of-the-box **on mono** (i.e. without export MONO_URI_DOTNETRELATIVEORABSOLUTE=true)?

By changing this line:

https://github.com/dotnet/corefx/blob/7e91c485254e054e0f3c14291f97e6a382659bec/src/System.IO.Packaging/src/System/IO/Packaging/InternalRelationshipCollection.cs#L357

To:

```C#
Uri targetUri = new Uri(targetAttributeValue, targetMode == TargetMode.Internal ?
 UriKind.Relative : UriKind.RelativeOrAbsolute);
```

To avoid the exception:

https://github.com/dotnet/corefx/blob/7e91c485254e054e0f3c14291f97e6a382659bec/src/System.IO.Packaging/src/System/IO/Packaging/InternalRelationshipCollection.cs#L416-L417

**Comment by twsouthwick** [comment]
Yeah, this request is to make it work out of the box with mono (good to know this is a different issue than the one I linked to). If this fix looks good, I can create a PR
