### ISSUE TITLE
[Proposal] Return something like an IList<T> instead of the real array in ArrayPool.

### ISSUE THREAD

**Issue by msedi** [dotnet/corefx#24835]
Currently ArrayPool returns the array from the buffer with the given chunksize, which can be larger than the  requested element size. The problem here is that handing over the array means that the "user" of the array needs to be aware of the true requested size.

In my opinion it would help a lot, if a "object", like ArraySegment<T> can be returned. The only problem with ArraySegment is, that the indexing is very slow and so I was thinking if it's not helpful to return a more generic approach with an interface, something like IArray<T>.

**Advantages:**
1. I can return something that implements IArray<T>. I personally would prefer IList<T>or better also IReadOnlyList<T>. If ArrayPool supports something like 

`ArrayPool<T, TListType> where TListType : IList<T>`

this can be also made generic

2. In this case I can create my own ArrayPool that also might have the ability to return "WeakObjects" and have an auto-conditioning ArrayPool that might throw away unused objects. Currently I need to track this myself.

**Problems:**
1. The problem of using IList<T> is that accessing this[indexer] is pretty slow, somehow in my tests 15 times slower than a regular array indexing. 

2. I somehow thought that Span<T> derives from IList<T> with an optimized access that is detected by the JITter. But looking in the code Span<T> doesn't derive from IList<T> which I find a little sad.

3. I also thought Span<T> or Memory<T> are somehow the fast way to access an index, But it seems to me that only the indexer is "elevated" via "AggressiveInlining". 

Maybe you can point me in some directions?

**Comment by mikedn** [comment]
> In my opinion it would help a lot, if a "object", like ArraySegment can be returned

It depends on what scenarios you have in mind. For those scenarios that `ArrayPool` was originally 
designed for, returning anything other than an array doesn't help at all, quite the contrary.

> ArrayPool<T, TListType> where TListType : IList<T>

That starts to look more like a generic object pool.

> But looking in the code Span doesn't derive from IList which I find a little sad.

The reasons why Span doesn't implement `IList` (or any other interface are somewhat complicated) and have been discussed in the past. Let's just say that `Span`'s main purpose in life is performance and dragging interfaces into the mix doesn't exactly help.

> I also thought Span or Memory are somehow the fast way to access an index, But it seems to me that only the indexer is "elevated" via "AggressiveInlining".

Don't know about `Memory` but the JIT does have some special handling for `Span`. Most importantly, it is able to eliminate range checks like it does for arrays.

> Currently ArrayPool returns the array from the buffer with the given chunksize, which can be larger than the requested element size. The problem here is that handing over the array means that the "user" of the array needs to be aware of the true requested size.

Sounds like a `Span<T> RentSpan(int size)` method could be useful and would complement the ongoing "spanification" of various APIs. Unfortunately this is likely problematic to implement, it also needs a `ReturnSpan(Span<T>)` and recovering the array from the span is tricky/risky/impossible.

**Comment by msedi** [comment]
@mikedn:

> It depends on what scenarios you have in mind

Well, in the end you are right. Maybe I need to explain some things about my needs. I'm currently having something like an ArrayPool which I call MemoryManager (MM). This MemoryManager returns memory that are supervised by the MM since the amount of memory I need exceeds the available amount of memory (RAM). The returned memory is wrapped into a MappableObject that is able to dump the memory into a file (and also load it again when needed). In some sort it's a combination of MemoryMappedFile and a GC. The regular GC using WeakReferences does not work here, this is why I did my own implementation. I was thinking that I could use the ArrayPool an and wrap my functions there. But you made me think about it, and I think the ArrayPool should just pool arrays and should do nothing else.

Maybe the only thing that bothers me is that the returned array is a multiple of the size of the internal chunk size and this size is returned to the caller. Lets assume the chunk size is 1024 and I request 512. I will get 1024 which is a little bit unhandy, since I have to now carry an object that holds the requested size and the array itself.

Lets assume I'm dealing with images in a stack. Each image is 513x513=263169 (if linearized) (the image size can vary a lot im my scenario), chunksize=1024, then I get an array 264192 elements, which does not correspond to the image size.

To sum things up. If I could derive from array and hide the internal to the users I would like the approach  more. And now comes maybe my main problem: There is not possibility to mimic array-like features except doing it with an indexer. The indexer would be OK for me, but the speed of the indexer is awful and that's maybe also something where the Span<> comes into play with it's JIt optimized access to the indexer.

It would be in general much nicer though, if something like Array<T> which has internal JIT optimization but which I can also inherit from.

In the end I'm dreaming maybe of a more holistic/generic solution for the whole Span<>, Memory<>, IList<> solution when it comes to the part of indexing.

> Sounds like a Span<T> RentSpan(int size)

If there would be a base interface/class for all of those classes that are array-like and the result would be Array<T> it shouldn't be much of a problem to clean things up. As I said, the only problem is that there exists no Array<T> and I cannot derive from Array.

I'd like to discuss a lot in this topic since we had to do tremendous work having vector arithmetic, type casting and type conversion. So please feel free to show me your opinion.

**Comment by jkotas** [comment]
> base interface/class for all of those classes that are array-like 

This is the new `System.Memory<T>` type. It abstraction for an arbitrary block of memory.
Spec: https://github.com/dotnet/corefxlab/blob/master/docs/specs/memory.md
Implementation: https://github.com/dotnet/corefx/tree/master/src/System.Memory

You should be able to implement System.Memory specialization that uses your MappableObject as the underlying storage.

**Comment by msedi** [comment]
@jkotas: Thanks for pointing this out. I already had a look at `System.Memory<T>` it looks quite what I need the only problem is that it lack a `this[]`.

Maybe you have a suggestion for the following question. How would I achieve a vectorized add, let's say

`public static T[] Add<T>(T[] a, T[] b)`

I currently have to do this via IL since C# does not support math on generics neither pointers. The problem is though that I also have matrix classes, image, and a lot of other stuff that needs the same method. For that reason I created another another method and derived all of my classes (or better added an interface) from `IArray<T>` and then made

`public static IArray<T> Add<T>(IArray<T> a, IArray<T> b)`

The first method can be well optimized and is quite fast, method 2 though can only be accessed by `this[]` and is awfully slow. If now something would exist that either derives from something or can be easily wrapped and is also lightweight that would be great.

**Comment by jkotas** [comment]
> it looks quite what I need the only problem is that it lack a `this[]`

Memory<T> has Span property. Span has indexer. The reason for this is that getting the Span out of Memory is relatively slow, and indexing into Span is fast (about as fast as indexing into array). The idea is that you get a local Span out of Memory<T> and then do multiple operations on it to amortize the cost.

> C# does not support math on generics

I am not sure how you are doing this with IL. The current best way to do this is to auto-generate specialized copies of the code. For example, you can take a look at how the math on generics problem is solved in https://github.com/dotnet/corefxlab/tree/master/src/System.Numerics.Tensors/System/Numerics

**Comment by jkotas** [comment]
The math on generics is discussed in https://github.com/dotnet/corefx/issues/11030 and related issues.

**Comment by benaadams** [comment]
You should use the `.Span` property on Memory as @jkotas points out
```csharp
Memory<float> memory;
var span = memory.Span;

// Cast to Span of Vector
var spanOfVector = span.NonPortableCast<float, Vector<float>>()
Vector<float> total;
for (var i = 0; i < span.Length; i++)
{
    total += spanOfVector[i];
}

// Can also use Span's ref to to convert to Vector via fixed; or Unsafe.As<TFrom, TTo> etc
// span.DangerousGetPinnableReference()
```

**Comment by stephentoub** [comment]
Closing per the discussion.  Thanks.
