### ISSUE TITLE
Add SpanExtensions.EndsWith

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefx#24840]
SpanExtensions have StartsWith overloads. We should add EndsWith counterparts:

```c#
public static bool EndsWith<T>(this Span<T> span, ReadOnlySpan<T> value) where T : IEquatable<T>;
public static bool EndsWith<T>(this ReadOnlySpan<T> span, ReadOnlySpan<T> value) where T : IEquatable<T>;
```

**Comment by terrajobst** [comment]
Seems reasonable. We should consider removing the `Span<byte>` as we believe we can specialize the implementation without performance loss.

**Comment by ahsonkhan** [comment]
> We should consider removing the `Span<byte>` as we believe we can specialize the implementation without performance loss.

@benaadams, @jkotas, can you recall why we specialized the `Span<byte>` APIs outside of the `Span<T>` ones? I remember we had specialized both `Span<byte>` and `Span<char>` but then we removed the `Span<char>` non-generic methods in favor of the generic ones but still kept `Span<byte>` overloads.

For context, these were added by @AtsushiKan here: https://github.com/dotnet/corefx/pull/15115

https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/SpanHelpers.byte.cs
```C#
        public static int IndexOf(this Span<byte> span, byte value) { throw null; }
        public static int IndexOf(this Span<byte> span, ReadOnlySpan<byte> value) { throw null; }

        public static int IndexOfAny(this Span<byte> span, byte value0, byte value1) { throw null; }
        public static int IndexOfAny(this Span<byte> span, byte value0, byte value1, byte value2) { throw null; }
        public static int IndexOfAny(this Span<byte> span, ReadOnlySpan<byte> values) { throw null; }
        public static bool SequenceEqual(this Span<byte> first, ReadOnlySpan<byte> second) { throw null; }
        public static bool StartsWith(this Span<byte> span, ReadOnlySpan<byte> value) { throw null; }
```

**Comment by benaadams** [comment]
> can you recall why we specialized the Span<byte> APIs outside of the Span<T> ones?

Not particularly; though not specializing would make the single implementation function very large and mean the Jit has to process a lot of code for every instantiation before throwing it away - not sure that matters.

Do generics inside generics cause Jit bumps? 

e.g.

`IndexOfAny(this Span<T> span ...` having `Vector<byte>` internally?

**Comment by karelz** [comment]
FYI: The API review discussion was recorded - see https://youtu.be/OZnaGV2omvI?t=2140 (6 min duration)

**Comment by jkotas** [comment]
> can you recall why we specialized the Span<byte> APIs outside of the Span<T> ones? 

Well, the original proposal was to have all T/byte/char specializations. Then we have removed the char specializations (https://github.com/dotnet/corefx/pull/17168) because they felt not very useful, but I do not think we have looked at removing the byte specialization as well.

As @benaadams says, you want to specialize the implementation for byte anyway. So it is really only a question whether you make this detail exposed in the API surface, or whether you depend on the JIT optimizations to figure it out.

> not specializing would make the single implementation function very large 

I do not think this would be the case. All these methods are implemented as two layers because of you want to share the code between the ReadOnlySpan and Span overloads. I expect that the specialization would be in the outer thin layer.

**Comment by KrzysztofCwalina** [comment]
I removed the struct constraint

**Comment by ahsonkhan** [comment]
@KrzysztofCwalina, can you update the original post and remove the byte specific EndsWith overloads?

**Comment by KrzysztofCwalina** [comment]
@ahsonkhan, which original post? I did remove the byte overloads in this issue (at the top).

**Comment by ahsonkhan** [comment]
Remove these from https://github.com/dotnet/corefx/issues/24840#issue-268103434:
```C#
public static bool EndsWith(this Span<byte> span, ReadOnlySpan<byte> value);
public static bool EndsWith(this ReadOnlySpan<byte> span, ReadOnlySpan<byte> value);
```

**Comment by KrzysztofCwalina** [comment]
Done. Thanks.

**Comment by zaytsev-victor** [comment]
I want to take it.
