### ISSUE TITLE
Provide IEnumerable<T> support for Memory<T>

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#24854]
## Rationale
Users should be able to pass `Memory<T>` to methods that take in `IEnumerable<T>` similar to array. Currently, this requires calling ToArray() to copy the contents of the `Memory<T>` into an array for it to work, and is unnecessary.

For example (from @eerhardt):
https://github.com/dotnet/corefxlab/blob/master/src/System.Numerics.Tensors/System/Numerics/DenseTensor.cs#L10
```C#
public void SomeMethod(DenseTensor<float> tensor)
{
   Memory<float> memory = tensor.Buffer;
   var value = CreateBatch<T>(..., memory.ToArray(), ...);
}
```

https://github.com/Microsoft/CNTK/blob/master/bindings/csharp/CNTKLibraryManagedDll/ShimApiClasses/ValueShim.cs#L104

```C#
public static Value CreateBatch<T>(NDShape sampleShape, IEnumerable<T> batch, DeviceDescriptor device, bool readOnly = false)
{
    T[] batchAsArray = batch.ToArray();
    return CreateBatch<T>(sampleShape, batchAsArray, 0, batchAsArray.Count(), device, readOnly);
}
```

If `Memory<T>` implemented `IEnumerable<T>`, then the ToArray() call would not be required. However, this would cause applications that reference System.Memory and `Memory<T>` for any scenario to be larger (when compiled AOT). Furthermore, if `Memory<T>` was an `IEnumerable<T>`, it might result in a pit of failure as it could lead to users unintentionally using the enumerator to iterate over the data rather than the more performant indexer on Memory.Span (especially for primitive types like `Memory<byte>`). To discourage unnecessary use of the enumerator but still provide support for the scenarios where you need an IEnumerable, the proposed solution is to add an adapter class and a ToEnumerable extension method on `Memory<T>`.

As an FYI, `Span<T>` cannot implement `IEnumerable<T>` since it is a stack-only, byref type, and casting it to an interface would cause boxing. The compiler will throw and error: `'Span<T>': ref structs cannot implement interfaces`

## Proposed API
```C#
namespace System
{
   public static class MemoryExtensions {
     public static IEnumerable<T> ToEnumerable(this Memory<T> memory);
   }
}
```

## Usage
Taking the above example, it would look as follows:
```C#
public void SomeMethod(DenseTensor<float> tensor)
{
   Memory<float> memory = tensor.Buffer;
   var value = CreateBatch<T>(..., memory.ToEnumerable(), ...);
}
```

## Partial Implementation
```C#
public static IEnumerable<T> ToEnumerable(this Memory<T> memory) => new MemoryEnumerable<T>(memory);

internal class MemoryEnumerable<T> : IEnumerable<T>
{
    ReadOnlyMemory<T> _memory;

    public MemoryEnumerable(ReadOnlyMemory<T> memory) => _memory = memory;

    public IEnumerator<T> GetEnumerator() => new MemoryEnumerator<T>(_memory);

    IEnumerator IEnumerable.GetEnumerator() => new MemoryEnumerator<T>(_memory);
}

internal class MemoryEnumerator<T> : IEnumerator<T>
{
    ReadOnlyMemory<T> _memory;
    int _index;

    public MemoryEnumerator(ReadOnlyMemory<T> memory) => _memory = memory;

    public T Current => _memory.Span[_index];

    object IEnumerator.Current => _memory.Span[_index];

    public void Dispose()
    {
        throw new NotImplementedException();
    }

    public bool MoveNext()
    {
        _index++;
        return _index <_memory.Length;
    }

    public void Reset()
    {
        _index = 0;
    }
}

```

cc @eerhardt, @KrzysztofCwalina, @stephentoub, @jkotas, @terrajobst, @karelz, @ericstj

**Comment by svick** [comment]
Would other collection interfaces make sense too? Like `IReadOnlyList<T>`?

**Comment by stephentoub** [comment]
> might result in a pit of failure as it could lead to users unintentionally using the enumerator to iterate over the data

How is Memory any more susceptible than IEnumerable on other types like List and T[]?

**Comment by eerhardt** [comment]
Why can’t Memory{T} implement IEnumerable{T} directly?  That way you wouldn’t need to call a method, nor alloc a throw away object.

**Comment by ahsonkhan** [comment]
> How is Memory any more susceptible than IEnumerable on other types like List and T[]?

It is just as susceptible. The difference being we can change `Memory<T>`.

**Comment by jkotas** [comment]
> Why can’t Memory{T} implement IEnumerable{T} directly? That way you wouldn’t need to call a method, nor alloc a throw away object.

You always need to alloc a throw away object to get IEnumerable out of memory. If Memory implemented IEnumerable directly, casting to IEnumerable would box.

**Comment by eerhardt** [comment]
Oh right.  I missed that Memory{T} is a struct.

**Comment by stephentoub** [comment]
> Partial Implementation

This is an implementation detail, but we should use the same allocated object as both the enumerable and enumerator in the common case, as is done by the compiler with iterators and in LINQ (this could likely just be implemented with an iterator).

**Comment by stephentoub** [comment]
> Span<T> cannot implement IEnumerable<T> since it is a stack-only, byref type, and casting it to an interface would cause boxing

Only tangentially related to this issue, have we considered giving Span an instance or extension GetEnumerator that returns a ref struct Enumerator?  And/or have there been any discussions about enabling the compiler to support foreach'ing a span and generating optimal code for that?  Just as I can foreach an array and end up with asm equivalent to walking through each element, it'd be nice to be able to do that with span as well, e.g.
```C#
foreach (T item in span)
{
    ...
}
```
being the same as:
```C#
for (int i = 0; i < span.Length; i++)
{
    T item = span[i];
    ...
}
```

**Comment by KrzysztofCwalina** [comment]
Language support for foreach would be great.

**Comment by terrajobst** [comment]
Looks good as proposed. `MemoryExtensions` doesn't exist yet but `SpanExtensions` will be renamed to it.

**Comment by stephentoub** [comment]
I opened https://github.com/dotnet/csharplang/issues/1085 for `foreach` support for `Span<T>` from the language side of things.  We still need to decide if we want to add `GetEnumerator` instance method to `Span<T>` and `ReadOnlySpan<T>`.

**Comment by karelz** [comment]
FYI: The API review discussion was recorded - see https://youtu.be/HnKmLJcEM74?t=391 (13 min duration)

**Comment by KrzysztofCwalina** [comment]
@ahson, should we close this issue now? We added the enumerator.

**Comment by stephentoub** [comment]
> should we close this issue now? We added the enumerator.

We added one to span.  I don't think we added one to memory.

**Comment by stephentoub** [comment]
I would assume not, as you'd most likely want to use it with LINQ and other such consumers. And if you did want a byref one, you could instead enumerate .Span.

**Comment by VSadov** [comment]
We tried the same route with ImmutableArray - add an adapter class and ToEnumerable method (or was it AsList ? ) - we did not like boxing of ImmutableArray. 
Anyways people despised that so we ended up with IEnumerable anyways.

**Comment by ianhays** [comment]
Do we still want to add ```public static IEnumerable<T> ToEnumerable(this Memory<T> memory);``` even if we also add ```Memory<T>.GetEnumerator()``` a la https://github.com/dotnet/coreclr/pull/14922?

**Comment by benaadams** [comment]
`Memory<T>` isn't getting `.GetEnumerator()` and `IEnumerable<T> ToEnumerable(this Memory<T> memory)` is a performance hole provided for compat (as you can't put a span in a `IEnumerator`), so is an explicit call. (As far as I understand)

**Comment by ianhays** [comment]
>Memory<T> isn't getting .GetEnumerator()
>as you can't put a span in a IEnumerator

isn't that exactly what we're already doing [right here](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Span.cs#L420) (though as Enumerator, not IEnumerator)? Or did you mean that you can't put a Memory into the Enumerator (which makes sense because it's not by-ref)?

**Comment by stephentoub** [comment]
> isn't that exactly what we're already doing right here

No, that's a ref struct, and it doesn't implement `IEnumerator<T>`, and that's for `Span<T>`, not `Memory<T>`.  That's just implementing a pattern that's bindable to foreach by the C# compiler, no interfaces involved.

> even if we also add Memory<T>.GetEnumerator() a la dotnet/coreclr#14922?

We're not adding an `IEnumerable<T>` implementation to `Memory<T>`, as that likely ends up being more expensive than a ToEnumerable method.  Consider a method that accepts an `IEnumerable<T>`. If `Memory<T>` (a struct) implemented `IEnumerable<T>`, passing the struct to that method would box it, resulting in an allocation; then when that method calls GetEnumerator and gets back an `IEnumerator<T>`, that'd be a second allocation.  In contrast, with a `ToEnumerable` method, the `IEnumerable<T>` that's returned can also implement `IEnumerator<T>`, such that the instance you get back can be the sole allocation in the 99% case where the enumerable is enumerated once.

**Comment by ianhays** [comment]
Thanks @stephentoub, I've got some better context now. Your comments in [The API Review video on this topic](https://www.youtube.com/watch?v=HnKmLJcEM74&feature=youtu.be&t=391) helped too :)

**Comment by ianhays** [comment]
There's pushback in #26284 about this being implemented as an extension method so I closed it so we can decide for sure what the API shape will look like and where the API should live (MemoryMarshal? Some new class?)

cc: @KrzysztofCwalina
