### ISSUE TITLE
Investigate other options for concurrent connection limits and allocations

### ISSUE THREAD

**Issue by Tratcher** [dotnet/corefx#24850]
The connection limit and connection allocation strategy are some of the most frequently hit problems for the prior .NET managed stack. This is one aspect of the new stack that warrants quite a bit of up-front scrutiny. There have already been design improvements here with the central queue vs the old queue-per-connection strategy, but the limits also need to be redesigned.

I’m not aware of any consistent connection management behavior across stacks or good publicized algorithms. Interviewing the WinHttp team would be one starting point.

The RFC has removed the old limit of two connections per host, it now says:
https://tools.ietf.org/html/rfc7230#section-6.4
"...this specification does not mandate a particular maximum
   number of connections but, instead, encourages clients to be
   conservative when opening multiple connections.
...
   Note that a server might reject traffic that it deems abusive or
   characteristic of a denial-of-service attack, such as an excessive
   number of open connections from a single client."

There is nothing conservative about the current allocation algorithm. MaxConnectionsPerServer defaults to int.MaxValue and there is no throttling on the rate at which new connections will be established. The old ServicePointManager.DefaultConnectionLimit started at 2 but also had no allocation throttle. A burst of requests will cause new connections to be established for every request up to the limit. This is likely more expensive and slower than queueing some of those requests to reuse existing connections as they become available.

Customers regularly run into the DefaultConnectionLimit bottleneck and ask what the correct value should be. There is no good answer to this question, nor even an easy way for the user to work it out for a specific application. This implies that the limit concept and allocation strategy themselves are flawed. The new stack isn't much different in this respect except that the default is MaxValue. This will manifest as a series of less obvious problems like added latency per request when they create extra new connections, added memory and CPU usage creating and maintaining idle connections, more sporadic failures when a request gets assigned to an idle connection that has been dropped, etc..

So what would a new design look like? It would need avoid being an app bottleneck like DefaultConnectionLimit, and also throttle bursts to avoid wasting resources like MaxConnectionsPerServer.

The .NET thread pool has these mechanics and would be an interesting design to test. Threads are analogous to connections except that connections are even more expensive to create and maintain. Work items are analogous to requests though requests can be assigned to connections a lot longer. The thread pool injects new threads at a throttled rate and only slowly approaches its configurable limit. Similarly the connection pool should explore only injecting new connections at a throttled rate to prevent bursts from wasting resources. The thread pool also has a configurable min thread limit to avoid bottlenecks at startup.

**Comment by davidsh** [comment]
>I’m not aware of any consistent connection management behavior across stacks or good publicized algorithms. Interviewing the WinHttp team would be one starting point.

I had recent conversations with the WinHTTP team when diagnosing a current .NET Framework HTTP stack bug related to problems with its connection management algorithm.

Some comments from WinHTTP about WinHTTP algorithms for connection management:

- Idle connections aren’t used after 1 minute of inactivity.
 
- There is a periodic scavenger that runs every 2 minutes to remove/close these connections.  They are also removed/closed when a request comes in and sees that they are past the idle timeout.

**Comment by Tratcher** [comment]
Interesting, that cleanup pattern sounds roughly consistent with both ServicePoint and ManagedHandler.

Did they have anything to say about their allocation pattern?

**Comment by davidsh** [comment]
>Did they have anything to say about their allocation pattern?

No.  It was a short conversation.
