### ISSUE TITLE
Windows NT Services

### ISSUE THREAD

**Issue by unicomp21** [dotnet/corefx#24860]
We need examples showing how to build an NT Service using .Net Core

**Comment by danmosemsft** [comment]
@unicomp21 the tests for service base necessarily create a service and then manipulate it:

https://github.com/dotnet/corefx/blob/master/src/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.TestService/TestService.cs 
etc.

Is that sufficient?

**Comment by unicomp21** [comment]
Already tried to leverage that code, couldn't get it to work.  Correct me if I'm wrong, I think the event used in the onstart signaling isn't initialized in a thread-safe manner.  Are there plans to promote ServiceBase out into the .net core 2.0 framework?

**Comment by danmosemsft** [comment]
@unicomp21 yes it will go up on nuget next month: https://github.com/dotnet/corefx/issues/24909

If there's an issue in the code, we'd welcome PR.

**Comment by danmosemsft** [comment]
Could you clarify the issue? I see that if ServiceMainCallback is entered on two threads, the event will get reinitilalized and not work as intended, but I'm not sure whether it's spuposed to be thread safe.

**Comment by unicomp21** [comment]
Yep, that's the part I was talking about.  Didn't realize it was
intentional.

**Comment by unicomp21** [comment]
Could we get a full NT service example around the ServiceBase class?

**Comment by unicomp21** [comment]
I think creating that example might flush a couple issues.

**Comment by danmosemsft** [comment]
ServiceBase is on nuget: https://docs.microsoft.com/en-us/dotnet/core/porting/windows-compat-pack

**Comment by unicomp21** [comment]
Thanks!
