### ISSUE TITLE
WinHttpHandler is not using Host header in SSL handshake

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#24862]
The .NET Framework does.

**Comment by davidsh** [comment]
>The .NET Framework does.

Can you be more specific about this?  Do you mean using the "Host: " header in the SNI portion of SSL handshake?  Or some other portion?  Can you attach a Wireshark trace, etc. ?

**Comment by stephentoub** [comment]
This test:
https://github.com/dotnet/corefx/pull/24820/files#diff-06a6483ff6bb478e06f199d69522bcd4R312

**Comment by davidsh** [comment]
cc: @karelz 

Duplicate of #23362 (which triage decided to close since ManagedHandler supports this).
