### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by sawachika-kenji** [dotnet/corefx#24865]
My procedure is very simple, through the socket to accept the connection and then through the sslstream forward data to the back-end server, a simple socket proxy, but soon after the start of the system memory is exhausted, I guess there may be a memory leak, how should I find the problem The

**Comment by danmosemsft** [comment]
Can you provide sample code? What platform are you using, and is it possible to check adifferent one?

**Comment by sawachika-kenji** [comment]
Thank you for your reply
I can send all the code to you via email.
Is there any way I can find the reason for memory leaks?


.NET CORE 2.0
CentOS Linux release 7.3.1611 (Core) 
4.12.4-1.el7.elrepo.x86_64

**Comment by Clockwork-Muse** [comment]
Normally you'd attach a profiler to your application, although I'm not sure what's available for core on linux.
If you're going to post code, then could you make it a repository/gist, please?

**Comment by danmosemsft** [comment]
@sawachika-kenji I would start by attaching lldb and loading sos then getting heap stats to see what type objects are taking up all the space, and what is rooting them.

Load sos with `plugin load libsosplugin.so`

There are various docs on sos on the web, and also you can do `soshelp`. 

If you are stuck you can share a dumpfile, or a repro as suggested by @Clockwork-Muse . 

@mikem8361 what is the recommended way of creating a dump on Linux?

**Comment by mikem8361** [comment]
If you are running lldb and have libsosplugin.so loaded and coreclr is 2.0 or master, then there is a “sos CreateDump” command that will create a core dump. You can also use the “createdump” utility on a running .NET Core process.  See the help for both commands on the details. Or for more info: https://github.com/dotnet/coreclr/blob/master/Documentation/botr/xplat-minidump-generation.md

**Comment by sawachika-kenji** [comment]
What tools can I use to view memory? I see there PerfView, can i use it?

**Comment by karelz** [comment]
PerfView is a good tool as is Visual Studio.
