### ISSUE TITLE
Implement System.Net.WebSockets.Client on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#2486]

**Comment by SidharthNabar** [comment]
#2490

**Comment by Flavien** [comment]
Is this planned for RC2?

WebSockets client is not supported on Linux, this is quite an important feature, it would be great if it makes it for RC2.

**Comment by joshfree** [comment]
Hi @Flavien I agree this is an important feature; it's currently not slated for RC2 at this time. I suspect right now that the feature will come off the backlog early next year for the next minor update after 1.0.  With that said, we'd be receptive to community contributions in this space earlier than that.

CC'ing some folks who can contribute to the open design issues.

/cc @stephentoub @SidharthNabar @vijaykota

**Comment by ayende** [comment]
Any news on this feature?

**Comment by joshfree** [comment]
@ayende this is still on the backlog

**Comment by ayende** [comment]
Can you explain a bit what is required to make this happen? We need this functionality, and want to know if we can contribute it.

Since Kesterl is how this is served on Linux, and since it is already working on Windows, I assume that there isn't something big that is missing right now.

**Comment by davidfowl** [comment]
@ayende We have a websocket client here https://github.com/aspnet/WebSockets/ but we haven't looked into the what a websocket upgrade looks like using libcurl (maybe it just works?). Here's what we have today (it's only tests on .NET Framework):

Wire up the websocket prefixes:

https://github.com/aspnet/WebSockets/blob/dev/src/Microsoft.AspNetCore.WebSockets.Client/WebSocketClient.cs#L23

Create the websocket from the opaque stream:

https://github.com/aspnet/WebSockets/blob/dev/src/Microsoft.AspNetCore.WebSockets.Client/WebSocketClient.cs#L74

You could possibly make this work if the HttpClient implementation gives you back the raw stream. You could hand it over to the websocket protocol layer.

/cc @Tratcher

**Comment by ayende** [comment]
Okay, so the current limitation is client side, right? Is there any issues
on the server side on Linux?

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by davidfowl** [comment]
WebSockets isn't being shipped as 1.0 as part of the ASP.NET Core 1.0 release. Though others are using it and it seems to be working just fine :smile: . Do try it out and if you find any issues, contribute to the repo. https://github.com/aspnet/WebSockets/

/cc @benaadams

**Comment by benaadams** [comment]
@ayende we've used the WebSockets middleware to send over 40 billion messages at an extremely high frequency; there are some issues; but if you are already handling reconnects - the biggest of which is probably a noisy log file https://github.com/aspnet/WebSockets/issues/63

**Comment by ayende** [comment]
Yes, we are using this as well, and I wanted to verify that the current
limitation on Linux was just plugging libcurl properly

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by Tratcher** [comment]
@davidfowl We've never even prototyped a way to do an opaque upgrade via HttpClient. I have a few ideas, but you can't just use the Stream from StreamContent because it gives you a restricted wrapper.

**Comment by ayende** [comment]
From my perspective, if there is a problem with libcurl, we can just fall
back to a completely managed impl.
Such as starting from here:
https://github.com/sta/websocket-sharp/tree/master/websocket-sharp

The stumbling block is the server, so I'm pretty happy, even if libcurl
proves problematic.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ayende** [comment]
I tried getting started on this, but it seems like the CLI is currently badly broken (see: https://github.com/aspnet/cli-samples/issues/15).
Couldn't get even the samples to work

**Comment by qooroo** [comment]
Are there any updates on this? We've been porting projects from mono to .net core and this is the only blocker remaining. I'd be happy to contribute to any work in progress items.

**Comment by ayende** [comment]
@qooroo We have implemented a trivial fix for this by writing this:
https://github.com/ayende/ravendb/blob/v4.0/src/Raven.Client/Platform/Unix/RavenUnixClientWebSocket.cs

It is not to be considered a viable alternative to a real implementation, but it allowed us to get ahead and not be blocked by this missing feature.
