### ISSUE TITLE
ServicePointManager_SecurityProtocolDefault_Ok failed Assert.Equal

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#24875]
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/98d53f272c58b4df9ce997d816d853ddff43e7d8/workItem/System.Net.ServicePoint.Tests/analysis/xunit/System.Net.Tests.TlsSystemDefault~2FServicePointManager_SecurityProtocolDefault_Ok
```
Unhandled Exception of Type Xunit.Sdk.EqualException
Message :
Assert.Equal() Failure
Expected: SystemDefault
Actual:   Tls11
Stack Trace :
   at System.Net.Tests.TlsSystemDefault.ServicePointManager_SecurityProtocolDefault_Ok() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.ServicePoint/tests/TlsSystemDefault.cs:line 14
```

The test is reading a static property.  Most likely there's another test in the project that's modifying that property and either it's not resetting it or they happened to run concurrently.

**Comment by davidsh** [comment]
>Most likely there's another test in the project that's modifying that property and either it's not resetting it or they happened to run concurrently.

Tests for app-wide (app-domain wide) classes should be run in isolation.

**Comment by danmosemsft** [comment]
This one is likely running concurrently.
```c#
        public static void SecurityProtocol_Roundtrips()
        {
            var orig = (SecurityProtocolType)0; // SystemDefault.
            Assert.Equal(orig, ServicePointManager.SecurityProtocol);

            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls11;
```
