### ISSUE TITLE
SqlBulkCopy can fail with a null ref exception for some IDataReader implementations

### ISSUE THREAD

**Issue by pensivebrian** [dotnet/corefx#24871]
SqlBulkCopy.WriteToServer accepts an IDataReader parameter. If the following two condition are met, the call will fail with a NullReferenceException:
1.  The passed implementation of IDataReader does not inherit from DbDataReader
2. A column mapping is specified

In the implementation of SqlBulkCopy.WriteToServer, the code attempts to cast the passed parameter to an DbDataReader, which is result in _DbDataReaderRowSource always being null. 

Attached is a zipped up .cs file with a repro: [Program.zip](https://github.com/dotnet/corefx/files/1415532/Program.zip)

**Comment by satano** [comment]
This is already reported #24638 and also pull request is waiting #24655.

**Comment by saurabh500** [comment]
Closed with https://github.com/dotnet/corefx/pull/24655
