### ISSUE TITLE
[Question] Has anybody run xunit tests on linux-arm?

### ISSUE THREAD

**Issue by chuckries** [dotnet/corefx#24877]
I am trying to build a test project on windows and run the tests on linux-arm. I have a shared framework installed on the linux-arm hardware, but I do not have a full SDK installed on linux-arm because there is not one available. Because there is no cli, I cannot simply run 'dotnet test' on the project. 

I had hoped that I would be able to create a [Self Contained Deployment](https://docs.microsoft.com/en-us/dotnet/core/deploying/) from the test project and it would include the test runner in the published output, but this is not the case. 

I hacked together a deployment of vstest.console.dll and it's dependencies that runs on the shared framework on my linux-arm hardware. When I invoked 'dotnet vstest.console.dll mytest.dll' however, no tests are run. Example output:
```
pi@chuckr-pi:~/vstest $ dotnet --fx-version 2.0.4-servicing-25824-03 vstest.console.dll ../test/scratch.dll
Microsoft (R) Test Execution Command Line Tool Version 15.6.0-dev
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
pi@chuckr-pi:~/vstest $
```

In this example ../test/scratch.dll contains one xunit test that should fail. This is the contents of the test dir:
```
pi@chuckr-pi:~/test $ ls
scratch.deps.json  scratch.pdb                     scratch.runtimeconfig.json                xunit.runner.utility.netstandard15.dll
scratch.dll        scratch.runtimeconfig.dev.json  xunit.runner.reporters.netstandard15.dll  xunit.runner.visualstudio.dotnetcore.testadapter.dll
```

Has anybody on the corefx team tried to do something similar?

**Comment by weshaggard** [comment]
I suspect no one as done normal "dotnet test" type scenarios. However we do run our tests on linux-arm as our tests just depend on some xunit libraries and the dotnet runtime itself, so they are very similar to dotnet applications.
