### ISSUE TITLE
GetResponseAsync_ServerNameNotInDns_ThrowsWebException failing locally

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#2488]
I just upgraded to Windows 10 RTM and VS2015 RTM.  Not sure if it's related, but this test is now failing for me locally.
```
Discovering: System.Net.Requests.Tests
  Discovered:  System.Net.Requests.Tests
  Starting:    System.Net.Requests.Tests
     System.Net.Requests.Test.HttpWebRequestTest.GetResponseAsync_ServerNameNotInDns_ThrowsWebException(remoteServer: Uri { AbsolutePath = "/get", AbsoluteUri
  = "http://httpbin.org/get", Authority = "httpbin.org", DnsSafeHost = "httpbin.org", Fragment = "", ... }) [FAIL]
        Assert.True() Failure
        Stack Trace:
           \corefx\src\System.Net.Requests\tests\HttpWebRequestTest.cs(398,0): at System.Net.Requests.Test.HttpWebRequestTest.GetRes
  ponseAsync_ServerNameNotInDns_ThrowsWebException(Uri remoteServer)
     System.Net.Requests.Test.HttpWebRequestTest.GetResponseAsync_ServerNameNotInDns_ThrowsWebException(remoteServer: Uri { AbsolutePath = "/get", AbsoluteUri
  = "https://httpbin.org/get", Authority = "httpbin.org", DnsSafeHost = "httpbin.org", Fragment = "", ... }) [FAIL]
        Assert.True() Failure
        Stack Trace:
           \corefx\src\System.Net.Requests\tests\HttpWebRequestTest.cs(398,0): at System.Net.Requests.Test.HttpWebRequestTest.GetRes
  ponseAsync_ServerNameNotInDns_ThrowsWebException(Uri remoteServer)
  Finished:    System.Net.Requests.Tests
```

**Comment by stephentoub** [comment]
cc: @davidsh, @CIPop, @SidharthNabar, @pgavlin

**Comment by stephentoub** [comment]
Ah, interesting, it looks like it's not related to Windows or VS, but rather to what network I'm on.  I was connected via a mobile hotspot; when I switched to a different wifi connection, the test passed, when I switched back to the hotspot, it failed.  Something about DNS resolution must be wonky on the hotspot?

**Comment by davidsh** [comment]
The test result appears to show that on the hotspot network DNS resolution is ALWAYS working even for bad DNS names that aren't really available in DNS (which is what this test is testing for and making sure we get the appropriate error value in the WebException.Status property).

**Comment by hackcraft** [comment]
Perhaps the hotspot mungs the DNS to provide "helpful" content (i.e. a bunch of advertising bundled with search results instead of a useful error message).

**Comment by stephentoub** [comment]
That appears to be exactly what's happening.  I'll close this out; I don't think it's worth sacrificing such a test case for this.
