### ISSUE TITLE
Result string of Win32Exception.ToString() method missing Win32Exception.NativeErrorCode

### ISSUE THREAD

**Issue by stukselbax** [dotnet/corefx#24892]
When we working with Win API via P/Invoke, it is common practice to check the result of called function and throw new [Win32Exception()](https://github.com/dotnet/corefx/blob/9eafffc6054c8f039d788465621bcfd49a379ca1/src/Microsoft.Win32.Primitives/src/System/ComponentModel/Win32Exception.cs#L21). We can pass error code explicitly, or the default constructor will catch the last one using [Marshal.GetLastWin32Error()](https://github.com/dotnet/coreclr/blob/da8b7181dbe362fbfe64c7ef72ff3a4a7db68f24/src/mscorlib/src/System/Runtime/InteropServices/Marshal.cs#L839). When we log the exception, the result string does not contain root *Win32Exception.NativeErrorCode*:

```csharp
var winError = new System.ComponentModel.Win32Exception(0x35);
/*
winError.ToString() provides:
"System.ComponentModel.Win32Exception (0x80004005): The network path was not found"
*/
```

The *0x80004005* referes to the common HResult.E_FAIL, which is _Unspecified error_ in winerror.h; That's wrong (IMHO)! We have provided exact error code, it is well specified.

Expected result:

```csharp
/*
winError.ToString() provides:
"System.ComponentModel.Win32Exception (0x80070035): The network path was not found"
OR
"System.ComponentModel.Win32Exception (0x00000035): The network path was not found"
*/
```

The last one logs the number we passed, the first one is the result of [Marshal.GetHRForLastWin32Error()](https://github.com/dotnet/coreclr/blob/da8b7181dbe362fbfe64c7ef72ff3a4a7db68f24/src/mscorlib/src/System/Runtime/InteropServices/Marshal.cs#L852)

**Comment by danmosemsft** [comment]
Win32Exception does'nt know the error code you give it is an HRESULT which is presumably the reason it stores it as NativeErrorCode and passes E_FAIL to its base class. 

I agree it certainly should include the supplied error code especially since it is showing the message it generated from NativeErrorCode. I see the same in desktop.

The only question in my mind is whether it should still include the HResult, since after all this is what you get when you get the HResult property. If we want to keep it, what should the message look like?

**Comment by danmosemsft** [comment]
Also should we display the supplied code as hex or decimal? Some heuristic, eg., if it's greater than some value it's hex?

**Comment by stukselbax** [comment]
I think that we don't need HResult. We need to see the error we passed. It can be either HResult or other error we get. But due to the fact that base class uses property for storing error code is named **HResult**, I think it will be more accurate to pass HResult to the base class. If it is applicable, we can modify the Win32Exception as follow:

```csharp
        public Win32Exception() : this(Marshal.GetHRForLastWin32Error())
        {
        }

        // Here we pass error code to the base class, and it will be taken into account
        public Win32Exception(int error, string message) : base(message, error) 
        {
            NativeErrorCode = error;
        }

        public Win32Exception(string message) : this(Marshal.GetHRForLastWin32Error(), message)
        {
        }
```

Let the base class to take care of [ToString()](https://github.com/dotnet/coreclr/blob/da66c3a146563d5841502a8dec76fe082ee9fef6/src/mscorlib/shared/System/Runtime/InteropServices/ExternalException.cs#L64) method. It is ok if the error code will be hex.

**Comment by danmosemsft** [comment]
@stukselbax that would be a breaking change in behavior: it would change the value returned by the property, potentially breaking existing code. I don't think we can do more than change the message.

**Comment by stukselbax** [comment]
It was a try. The main point is to show **NativeErrorCode** when **ToString** method is called.

**Comment by danmosemsft** [comment]
Would you like to offer a PR?

**Comment by jnm2** [comment]
It would have made so much sense to reflect the error code in HResult, but another problem with changing that now is that people will no longer realize that they still need this special case to keep their code from breaking on older platform versions:

```cs
var winErrorCode = (ushort)(ex is Win32Exception win32ex ? win32ex.NativeErrorCode : ex.HResult);
```

**Comment by stukselbax** [comment]
@danmosemsft I would like to introduce this kind of breaking change, because it reflect the true value of error. We can preserve the value of **NativeErrorCode**, but we should pass the kind of **HResultFromWin32Error** to the base class. Thus we don't need to duplicate the **ToString()** method of base class, or introduce parameterized version of it. I think that developer should work differently with HResult and Win32Errors, but it's naive suggestion.

So, before doing that, I would like to know which sort of PR it should be. What do you think?

**Comment by jnm2** [comment]
If you were to do this, you should put a noticeable warning in the XML documentation for HResult` that if you are making a decision about the kind of error– such as what logic to use when IOException is due to`ERROR_PATH_NOT_FOUND`– you should try casting to `Win32Exception` and using `NativeErrorCode ` first. Otherwise your logic will be screwed on current and older BCLs.

**Comment by danmosemsft** [comment]
CC @stephentoub for his opinion.

What I think of as Win32 error codes are not HRESULTs. They are the relatively small numbers many API return to indicate file not found, etc. So I do not think the behavior is accidental.

(Of course there are many API in Win32 that do return HRESULT and hopefully they don't pass it to the Win32Exception constructor.) 

I do not think the compatibility reviewers would allow a change which could break 15 years of existing code.

**Comment by stephentoub** [comment]
> CC @stephentoub for his opinion.

I'd simply override ToString on Win32Exception and format the data there however we see fit, essentially a tweaked copy of what the base ExternalException class does in its ToString.
