### ISSUE TITLE
Path.GetFullPath difference between Windows and Linux

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#24907]
@YvonneArnoldus commented on [Thu Oct 26 2017](https://github.com/dotnet/coreclr/issues/14707)

I have written some code that uses Path.GetFullPath().  I have found some different results for the same paths between Windows and Linux in my Docker image.

Windows: 
input:  a\b\\..\\..\c.\ -> output: C:\code\fontoxml-sdk-schemacompiler\test\FontoXml.Server.Utils.XmlCatalog.Tests\bin\Debug\netcoreapp2.0\c\

Linux:  a/b/../../c./ -> output: /app/test/FontoXml.Server.Utils.XmlCatalog.Tests/bin/Release/netcoreapp2.0/c./

It seems the current directory indicator isn't resolved on Linux as it is on Windows while the parent directory indicator is.

**Comment by janvorli** [comment]
I think there is no issue here. The `.` in your path doesn't represent current directory. You would have to separate it by `/` to represent it. The way you have it means that the `.` is part of the directory name. On Unix, the directory (or file) name can end with `.`. But on Windows, the name with `\` at the end is considered equivalent to the name without the `.`. Try to create a file or directory named `c.` using e.g. the command prompt and you'll see that what gets created is named just `c`.

**Comment by YvonneArnoldus** [comment]
You are right. The test I wrote was not correct, on Windows it looked correct because the invalid character is striped from the full path.
