### ISSUE TITLE
Check that long relative paths work on Windows

### ISSUE THREAD

**Issue by DemiMarie** [dotnet/corefx#24901]
We should check that long relative paths work on Windows.  It appears (from looking at the source) that they do not.

Problem is in [PathInternal.Windows.cs][1]: `EnsureExtendedPrefixOverMaxPath` simply returns if the path is relative, rather than calling `GetFullPathNameW` and then adding the extended prefix.  As a result, the underlying Windows API function will fail.

This is a rather simple fix, though I don’t have a Windows machine to test it with.

 [1]: https://github.com/dotnet/corefx/blob/f2e440450e8b52317f08c21fe66f70141c9e933c/src/Common/src/System/IO/PathInternal.Windows.cs#L117

**Comment by danmosemsft** [comment]
@JeremyKuhne can you answer this long paths question.

**Comment by JeremyKuhne** [comment]
@DemiMarie All code paths that hit that method should have already been normalized. If you find a case where that isn't happening we should, of course, fix it. I'm open to adding a debug assertion here if we aren't fully qualified.

If we _did_ call normalize here it would be expensive (1) and potentially breaking (2), as normalization eats characters that we may want to keep.  If we're iterating filenames from the OS we wouldn't want to turn `"foo "` into `"foo"`, for example.

**Comment by danmosemsft** [comment]
I'm going to close feel free to reopen if needed.
