### ISSUE TITLE
XmlSerializer generates list of empty values for attribute including whitespace character.

### ISSUE THREAD

**Issue by Sojaner** [dotnet/corefx#24914]
## Description
While using `System.Xml.Serialization.XmlSerializer` with `XmlSerializer.Deserialize()` method, the output for an attribute which is supposed to be mapped to a List<string> outputs empty values if there is only a whitespace character in the attribute,

Is this the intended behaviour?

## Reproduction Steps
1) Create a .NET Core 2.0.2 console application.
2) Copy the following code to `Program.cs` file.
```c#
using System;
using System.Collections.Generic;
using System.IO;
using System.Xml;
using System.Xml.Serialization;

namespace XmlTest
{
    internal class Program
    {
        private static void Main()
        {
            string xml = "<Test list=\" \" />";

            List<string> outputList = new List<string>();

            using (XmlReader reader = XmlReader.Create(new StringReader(xml)))
            {
                XmlSerializer serializer = new XmlSerializer(typeof(Test));

                outputList = ((Test)serializer.Deserialize(reader)).List;
            }

            Console.WriteLine($"Input XML: {xml}");

            Console.WriteLine($"Generated list's length: {outputList.Count}");

            Console.WriteLine("Listing the list contents:");

            foreach (string output in outputList)
            {
                Console.WriteLine($"Content:'{output}', content length:{output.Length}");
            }

            Console.WriteLine("End of process. Press enter to exit...");

            Console.ReadLine();
        }
    }

    public class Test
    {
        [XmlAttribute("list")]
        public List<string> List { get; set; }
    }
}
```
3) Run the code and read the console outputs.

## Observation

The output seems like the result of code similar to the following:
```c#
string test = " ";

string[] parts = test.Split(' ');

List<string> output = new List<string>(parts);
```
I couldn't find the spot where the serialization is happening in the code though, however if it's really something like this _and it is not the intended behaviour_, changing the `test.Split(' ')` piece to `test.Split(' ', StringSplitOptions.RemoveEmptyEntries)` should be fixing the issue.

**Comment by huanwu** [comment]
@Sojaner This is the expected behavior. Just like what you observed, our serialization read method use the split method without RemoveEmptyEntries, so it will output the list with the empty value.

**Comment by Sojaner** [comment]
As a user, it was a strange behavior to me. Wouldn't it be more logical to `Trim` the string inside an attribute before the `Split`, if there is a solid reason for not using the `RemoveEmptyEntries` flag with the `Split` method @huanwu?

**Comment by huanwu** [comment]
@Sojaner, it is too risky to make the change. The existing customer might already work around this problem. It will break their workaround if making this change.
