### ISSUE TITLE
How to debug the source code of ServiceModel.Http (4.4.0) using Visual Studio 2017

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#24918]
@SCKlausZ commented on [Thu Oct 26 2017](https://github.com/dotnet/core/issues/1048)

Visual Studio 15.3.4
.net core 2.0.0
System.ServiceModel.Http NuGet package 4.4.0

I'm having a strange transient error when calling a web service and I would like to step into WinHttpHandler (and WinHttpRequestCallback) to get more information, but I just get an "Source Not Available".

I have cloned both the coreclr and corefx repositories, I have setup VS2017 according to [Visual Studio Doc](https://docs.microsoft.com/en-us/visualstudio/debugger/specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger) and [issue 897](https://github.com/dotnet/core/issues/897), and I can step into things like System.Private.CoreLib.dll.

In the Modules window, I can see that the System.ServiceModel.Http.pdb is loaded. I can find the source code in ...\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs. I can open the source file, and if I set a breakpoint it is brown (red?) as if it is enabled. But execution doesn't break at the breakpoint.

I can set a breakpoint in ExceptionDispatchInfo, but when I try to switch to a frame in WinHttpHandler/WinHttpRequestCallback I get "Source Not Available (see screendump).

![debugwinhttphandler](https://user-images.githubusercontent.com/33118160/32053847-c028aa3a-ba5c-11e7-94bf-06090700899c.png)

Can I do something so that I can step into the source code for the System.ServiceModel.Http NuGet package?

**Comment by joshfree** [comment]
@zhenlan @mconnew

**Comment by zhenlan** [comment]
@SCKlausZ, the source code of System.ServiceModel.* packages are at https://github.com/dotnet/wcf repo.

**Comment by danmosemsft** [comment]
@SCKlausZ if you need symbols and don't want to build yourself you can get them manually from https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.ServiceModel.Http. They may be on the symbol server https://msdl.microsoft.com/download/symbols also.

**Comment by SCKlausZ** [comment]
@zhenlan Thank you for your reply. I have fetched the source for the wcf repo (and the aspnet/mvc). It doesn't make any difference.
![debugsourcefiles](https://user-images.githubusercontent.com/33118160/32161400-ad57b134-bd55-11e7-923c-1bbf87255d49.png)

**Comment by SCKlausZ** [comment]
@danmosemsft Thank you for your reply. VS2017 is able to find the symbols - they are not missing. In the Modules window, I can see that they are loaded from ...\.nuget\packages\... - so they must be distributed with the nuget package.
![modules](https://user-images.githubusercontent.com/33118160/32161726-e99ca64e-bd56-11e7-9c8f-895799d90f12.png)

**Comment by danmosemsft** [comment]
@SCKlausZ I would try using privately built bits, see if those symbols work better.

**Comment by SCKlausZ** [comment]
@danmosemsft OK, I'll build them myself.

**Comment by danmosemsft** [comment]
@SCKlausZ to consume self built bits, this may be helpful:
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md

Also I notice you have VS 15.3. I would try updating to the latest (15.4 or a subsequent preview) to see if it resolves the symbols issu.e

**Comment by tarekgh** [comment]
Issue moved to [dotnet/wcf #2390](https://github.com/dotnet/wcf/issues/2390) via [**ZenHub**](https://www.zenhub.com/)

**Comment by zhenlan** [comment]
Looks like the issue currently is with System.Net.Http.WinHttpHandler.dll, which is built in corefx. Reopen this issue and closed the one that was moved to wcf repo.

**Comment by tarekgh** [comment]
@zhenlan does this still owned by WCF? who is the right person to look at this issue?

**Comment by zhenlan** [comment]
WCF does not (never) own System.Net.Http.WinHttpHandler.dll. I think it's owned by networking team.

**Comment by davidsh** [comment]
@@SCKlausZ 

Can you please attach a Visual Studio solution that repro's this problem?  Also, please include the Windows OS version and Visual Studio 2017 version you are using?

**Comment by karelz** [comment]
No response, closing.
If there is more information, let us know and we can reopen.
