### ISSUE TITLE
System.Data.SQLClient throws an Exceoption by calling open Method

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#24919]
@Martin-Stein commented on [Wed Oct 25 2017](https://github.com/dotnet/core/issues/1045)

Hi folks,

Its great to have direct SQL access, but my UWP Application, with target Fall Creators Update, runs into an IO Exception when I call open-Method on my SQLConnection object:
 
System.IO.FileNotFoundException  occurred.
  HResult=0x80070002
  Message= Could not load file or assembly 'System.Threading.Thread, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. File not found   
at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   bei System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   bei System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   bei System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   bei System.Data.SqlClient.SqlConnection.Open()
   bei SQLDBDiagrammGenerator.UWP.MainPage.connect_Click(Object sender, RoutedEventArgs e) 

I have loaded System.data.common version 4.3.0
System.Data.SQLClient 4.4.0
Microsoft.NETCore.UniversalWindowsPlatform Ver. 6.0.1 via Nuget.

What can it be, how can it be solved?

Best regards,

Martin

**Comment by joshfree** [comment]
@saurabh500 @corivera

**Comment by danmosemsft** [comment]
Hello @martin-stein
I just tried this: created a new UWP application, target Fall Creators Update, added a reference to System.Data.SqlClient 4.4.0, pasted in this code into InitializeComponent:
```c#
            var c = new System.Data.SqlClient.SqlConnection("server=foo");
            c.Open();
```
Then I hit F5 ( in debug configuration ) and it throws because it can't find "foo" but I see System.Threading.Thread, Version=4.1.1.0 was loaded successfully.

Can you help me find repro steps? Perhaps share a repo with a minimal repro case?

**Comment by saurabh500** [comment]
Closing due to no response
