### ISSUE TITLE
[Binary serialization] Dictionary<string,string> does not roundtrip with full .NET Framework

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#24938]
Run this on .NET Core:

```
using System;
using System.IO;
using System.Collections.Generic;
using System.Runtime.Serialization.Formatters.Binary;

class Program
{
    static void Main(string[] args)
    {
        var d = new Dictionary<string,string>();
        d.Add("Hello", "World");

        using (var fs = new FileStream("DataFile.dat", FileMode.Create))
        {
            BinaryFormatter formatter = new BinaryFormatter();
            formatter.Serialize(fs, d);
        }
    }
}
```

Then run this on .NET Framework:

```
using System;
using System.IO;
using System.Collections.Generic;
using System.Runtime.Serialization.Formatters.Binary;

class Program
{
    static void Main(string[] args)
    {
        using (var fs = new FileStream("DataFile.dat", FileMode.Open))
        {
            BinaryFormatter formatter = new BinaryFormatter();
            var d = (Dictionary<string,string>)formatter.Deserialize(fs);
            foreach (var e in d) Console.WriteLine($"{e.Key} {e.Value}");
        }
    }
}
```

Result: Deserialization on .NET Framework fails with:

```
Unhandled Exception: System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Runtime.Serialization.SerializationInfo.GetValue(String name, Type type)
   at System.Collections.Generic.Dictionary`2.OnDeserialization(Object sender)
   at System.Runtime.Serialization.ObjectManager.RaiseDeserializationEvent()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at Program.Main(String[] args)
```

**Comment by jkotas** [comment]
We seem to have a hole in testing methodology if something this basic slipped through.

**Comment by danmosemsft** [comment]
Indeed.

**Comment by ViktorHofer** [comment]
Looking now...

Just a note, Dictionary<,> and Hashtable are definitely not trivial types as their serialization path differs on the generic input, the ctor overload, ... We are currently testing Dictionary<,> with a few different generic types. We thought this should cover all paths but it seems Dictionary<string,string> is again specialized.

**Comment by danmosemsft** [comment]
This suggests not many people are using binary serialization yet...

**Comment by stephentoub** [comment]
> This suggests not many people are using binary serialization yet...

Across runtimes.

**Comment by ViktorHofer** [comment]
Desktop uses `GenericEqualityComparer<,>`, Core uses `NonRandomizedStringEqualityComparer`:

https://www.diffchecker.com/ZySHrK9V

**Comment by danmosemsft** [comment]
Note that when there have been 100 collisions, if it's using NRSEC, Dictionary changes to the default string comparer. Your tests will never encounter that transition. (See https://github.com/dotnet/corefx/pull/24779). However you should be covering that case so long as we have a test for the default comparer if passed in explicitly.

**Comment by ViktorHofer** [comment]
I think the `NonRandomizedStringEqualityComparer` was never meant to be serialized. We introduced code (probably an optimization) which uses it instead of the `GenericEqualityComparer<string>`. I have a potential fix for it which replaces the NRSEC with a GEC<string> in the GetObjectData method. 

Drawback: Core --> Core serialization probably looses the optimization.

@jkotas is my assumption correct? thoughts?

**Comment by jkotas** [comment]
I think so. 

> `Core` --> `Core` serialization probably looses the optimization.

We are losing similar optimizations in other cases (e.g. the enum compared optimizations are lost). I think it is ok to lose the comparer optimization in this case too.
