### ISSUE TITLE
Calling Dispose() on a socket inside a synchronous Accept() on Linux hangs

### ISSUE THREAD

**Issue by LHCGreg** [dotnet/corefx#24943]
Operation System: Debian Stretch
Tested with git master (coreclr SHA 67a66156d0307b49522a13618522d289268bc1f9 and corefx SHA 389d7ee)

Reproduction code: https://gist.github.com/LHCGreg/a8a144da68d59f225a4b2c4bd1cbd05d

This program takes three arguments. First argument is 'async' or 'sync' for whether to call Accept() or AcceptAsync(). Second argument is 'shutdown' to try to stop listening socket by calling Shutdown(SocketShutdown.Both), then Dispose(), or 'dispose' to just call Dispose(). Third argument is 'signal' to register signal handlers for SIGINT (or ctrl+c on windows) and SIGTERM (netcore only), or 'auto' to automatically try to stop the listening socket after 3 seconds.

Reproduction steps:

On Linux, run

```
dotnet SocketStopTest.dll sync dispose auto
```

Expected result: A SocketException is thrown from the Accept() call and the program terminates.

Actual result: The program hangs inside Socket.Dispose().

On Windows, both full framework and .net core, calling Dispose() on a Socket that is in a synchronous Accept() call will break it out of the Accept() call with a SocketException. On Linux, it hangs inside the Dispose(). On Linux, calling Shutdown(SocketShutdown.Both) before calling Dispose() works and causes a SocketException to be thrown from the Accept(), although the exception message is a little weird: "Invalid argument". But on Windows, whether full framework or .net core, calling Shutdown(SocketShutdown.Both) apparently hangs when called from regular code or throws a SocketException on the Shutdown (and does not interrupt the Accept) when called from a ctrl+c handler with a message of "A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied"

With AcceptAsync(), Dispose() generally works as expected on Windows full framework, Windows .net core, and Linux .net core, with the small exception of Windows full framework raising ObjectDisposedException from the accept task instead of SocketException.

See outcome.txt in the gist for outcomes of all combinations of Windows net47 vs Windows netcore vs Linux netcore, Accept() vs. AsyncAccept(), Shutdown(SocketShutdown.Both) + Dispose() vs. just Dispose(), and socket stopped from delayed Task vs. ctrl+c/SIGINT handler vs. SIGTERM handler.

It's also far from clear from documentation what the correct way of interrupting an Accepting socket is. One might guess to call Dispose() on it, but calling Shutdown would be another reasonable guess and works on Linux but not Windows.

**Comment by stephentoub** [comment]
This is the same as https://github.com/dotnet/corefx/issues/20954, and https://github.com/dotnet/corefx/issues/24677.  The native behavior of closing a socket file descriptor while it's being used in a synchronous/blocking accept/connect/send/recv/etc. call is undefined on Linux, and often results in a hang.  There's little we can do about that higher up.

**Comment by LHCGreg** [comment]
I see. Sounds like a good reason to stick with async sockets.
