### ISSUE TITLE
Assistance with making first pull request

### ISSUE THREAD

**Issue by darrenstarr** [dotnet/corefx#24940]
I have implemented RIPE160 hashing as documented in the .NET 4.7.1 API reference by porting Antoon Bosselaers's C implementation to C#. As with most security algorithms, it is a bit messy, however I've tested it quite thoroughly.

Is there anyone here who would like to hand-hold me while performing my first pull request? SSH.NET does not compile with .NET Core from the development branch because of lack of RIPE160 support. I considered making better #ifdefs in the SSH.NET code to detect and disable the feature, but reconsidered that adding RIPE160 was in fact the better solution.

Thank you in advance... my repository is : https://github.com/darrenstarr/RIPEMD160.net and I believe I'm most of the way there.

There is a single unit test which I don't understand well enough yet to provide the correct value as the result. I suppose once I properly get the code checked out and ready, it should be pretty easy to sort out.

**Comment by jkotas** [comment]
cc @bartonjs

**Comment by bartonjs** [comment]
We intentionally cut RIPEMD160 from .NET Core.  If I understand correctly, SSH is designed to allow for algorithm capability negotiation, and a version of SSH.NET built on .NET Standard (or explicitly against .NET Core) would need to simply not support RIPEMD160.  (Or SSH.NET can build it in, or depend on a 3rd party library, et cetera).

**Comment by darrenstarr** [comment]
I understand it was cut intentionally, but just as MD5 and SHA-1 are needed for compatibility with older systems, RIPEMD160 is a common component for packet authentication in SSH for compatibility with older devices.

I don’t wish to start internal debates over the politics of security concerns, but just as .NET generates warnings (or errors) for using know to be insecure hashes like MD5 and SHA-1, RIPEMD160 is equally prudent and should be considered an equally “bad citizen” to those hashes.

I could of course build the has directly into SSH.NET for compatibility with devices where RIPEMD160 is the least of all evils when connecting to older devices where firmware updates are not available, but RIPEMD160 with proper warning and errors are certainly standards that should be supported as part of a common security library as System.Security.Cryptography. 

While it may be considered insecure (which is certainly is), it’s no worse than MD5 or SHA-1 which are also needed for compatibility if not security.

For now, I’ll build it as a 3rd party library and publish it to NUGET. With the exception of support for HashAlgorithmNames (I’m on my phone and might have the class name wrong), there does not seem to be any features which will be lost by doing so. I do however hope that it is later added to .NET Standard since RIPEMD160 is an important class.

**Comment by bartonjs** [comment]
Since we're still of the position that .NET Core shouldn't have RIPEMD160 there's no action here, closing the issue.
