### ISSUE TITLE
Expose RuntimeWrappedException constructor

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#24946]
High-fidelity interpreters need to create RuntimeWrappedException. There is no public constructor for RuntimeWrappedException today.

# Proposed API
```C#
public class RuntimeWrappedException
{
    public RuntimeWrappedException(object thrownObject);
}
```

# Details
The constructor is public in the CoreLib implementation already. It is used by our own `System.Linq.Expression` interpreter (see #24945). This issue is about exposing it in the contract so that 3rd party libraries have access to it as well, and do not have to resort to private reflection.

**Comment by terrajobst** [comment]
Looks good as proposed.

**Comment by karelz** [comment]
FYI: The API review discussion was recorded - see https://youtu.be/HnKmLJcEM74?t=83 (3 min duration)
