### ISSUE TITLE
Memory leak when HttpClient.GetByteArrayAsync() is used

### ISSUE THREAD

**Issue by romanryasne2** [dotnet/corefx#24942]
There is no this problem with memory when using HttpClient.GetStreamAsync() and getting byte array manually.

After research of source code I've found HttpClient.GetByteArrayAsyncCore() and here some code from this method:

```
if (contentLength.HasValue)
{
    // If we got a content length, then we assume that it's correct and create a MemoryStream
    // to which the content will be transferred.  That way, assuming we actually get the exact
    // amount we were expecting, we can simply return the MemoryStream's underlying buffer.

    buffer = new HttpContent.LimitMemoryStream(_maxResponseContentBufferSize, (int)contentLength.GetValueOrDefault());

    await responseStream.CopyToAsync(buffer).ConfigureAwait(false);

    if (buffer.Length > 0)
    {
        return ((HttpContent.LimitMemoryStream)buffer).GetSizedBuffer();
    }
}
```

As you can see _buffer_ is not disposed after the method returned. May it is a reason of memory leak?

To continue a theme of used memory I run this small program targeting .Net Framework 4.7 and .Net Core 2.0.

```
using System;
using System.IO;
using System.Net.Http;
using System.Threading.Tasks;

namespace TestCsharp
{
    internal class Program
    {
        private static void Main()
        {
            HttpClient client = new HttpClient();

            Parallel.For(0, 100, i =>
            {
                using (Stream stream = client.GetStreamAsync("https://music.nashe.com.ua/ANEBO_-_Holos_za_pochuttia.mp3").Result)
                using (MemoryStream memory = new MemoryStream())
                {
                    stream.CopyTo(memory);
                    byte[] b = memory.ToArray();
                }
            });

            Console.ReadKey();
        }
    }
}
```

Using Diagnostic Tools I've noticed different GC behaviour (in .Net Framework it calls frequently and memory releasings are larger after it). During work .Net Core uses up to 1 GB (.Net Framework no more than 400 MB) and when tasks are done Process Memory in .Net Core is near 500 MB whereas .Net Framework program uses near 50 MB.

How to achive the same usage of memory in .Net Core? (Except of targeting .Net Framework).

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by stephentoub** [comment]
> As you can see buffer is not disposed after the method returned. May it is a reason of memory leak?

No, it doesn't actually need to be disposed.

> Memory leak when HttpClient.GetByteArrayAsync() is used

Do you have a repro for that?  The code you shared is for GetStreamAsync.  What is the "leak" you're observing?

**Comment by davidsh** [comment]
Closing due to not enough information to diagnose.
