### ISSUE TITLE
SqlClient doesn't support "always encrypt" (column encryption setting=enabled)

### ISSUE THREAD

**Issue by wizofaus** [dotnet/corefx#24951]
SqlClient from .NET 4.6+ supports SQL Server 2016's "always encrypted" option using the connection string option "column encryption setting=enabled". This allows application code to transparently read/write data from columns such that it is automatically encrypted before sending to the database server, in such a way that it cannot be decrypted from other systems without access to the relevant keys.
Unfortunately it's not yet supported under .NET Core, which limits the use of this feature in security-conscious platforms (e.g. payment systems).

**Comment by wizofaus** [comment]
The meat of the logic to support this appears to be in:
https://github.com/Microsoft/referencesource/blob/master/System.Data/System/Data/SqlClient/TdsParser.cs

If it doesn't look like it's too much work to copy the relevant bits of code into the dotnet corefx source I don't mind doing so, though so far I haven't been able to get it to build (getting errors trying to download required packages etc.)

**Comment by saurabh500** [comment]
@wizofaus we have a security team that is trying to get this feature into .Net Core and it seems that there are some Windows specific dependencies in this feature. 
The logic is spread across SqlCommand and TdsParser 
If you want to give the port  a shot, you are welcome to. Right now with a code port we can support AKV integration scenarios only.

**Comment by wizofaus** [comment]
Unfortunately I still haven't been able to get dotnet building, but if there's a team already looking at it that's great.

**Comment by bricelam** [comment]
Duplicate of #18276
