### ISSUE TITLE
File URI cannot be parsed with @ sign

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/corefx#24963]
The DocumentFormat.OpenXml library uses System.IO.Packaging to open office related documents. A user posted an issue where one of the package relationships uses a legacy URI format that fails to be parsed. This document opens fine in PowerPoint and would like to be able to open it with the .NET library. The URI in question has the form:

```
file:///\\contoso.com@SSL\user\content\path\projects\blank.xlsx
```

**Comment by davidsh** [comment]
Does this work .NET Framework?

**Comment by twsouthwick** [comment]
No. This fails to parse on both .NET Framework and .NET Core.

**Comment by twsouthwick** [comment]
Here's a repro:

```csharp
using System;

namespace ConsoleApp6
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                var result = new Uri(@"file:///\\contoso.com@SSL\user\content\path\projects\blank.xlsx", UriKind.Absolute);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }
    }
}
```

And the error:

```
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at ConsoleApp6.Program.Main(String[] args) in C:\Users\tasou\source\repos\ConsoleApp6\ConsoleApp6\Program.cs:line 11
```

**Comment by davidsh** [comment]
>where one of the package relationships uses a legacy URI format that fails to be parsed

Can you point to the relevant RFC for URI's that describe this "legacy" format?  Since both .NET Framework and .NET Core don't support this format, we need to understand more about it.  Most of the URI RFC's we support are in RFC 3986, 3987 (IRIs).

**Comment by poizan42** [comment]
That looks more like a UNC path naively prefixed with "file:///" than any sort of valid URI. Maybe OpenXML should do its own parsing if it need to support that?

**Comment by twsouthwick** [comment]
@poizan42 may be right. Looks like this is a WebDAV path expressed as a UNC path (see https://en.wikipedia.org/wiki/Path_(computing)) with `file:///` prepended. Office seems to be able to handle it, but I can't find any documentation for what the format is.

**Comment by twsouthwick** [comment]
Since this seems to be a non-standard way of forming a URI, I'll close this for now. Thanks for the help!
