### ISSUE TITLE
init-tools.cmd hangs when running out of disk space

### ISSUE THREAD

**Issue by chucklu** [dotnet/corefx#24968]
After open the cmd file,I just get the following info.
Installing dotnet cli...

I have checked the log file

> Running init-tools.cmd 
> Installing 'https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0/dotnet-sdk-2.0.0-win-x64.zip' to 'D:\ChuckLu\Git\GitHub\dotnet\corefx\Tools\dotnetcli\dotnet-sdk-2.0.0-win-x64.zip' 
>

**Comment by chucklu** [comment]
Never mind, I have received a system info, I have run out of my disk space.

**Comment by chucklu** [comment]
Is it possible for you to check the disk space in script？And echo the error info about the lack of disk space

**Comment by danmosemsft** [comment]
@chucklu would you like to offer a PR?

**Comment by weshaggard** [comment]
I'm going to close this issue as I'm not sure what a disk space check would really look like here or at what place it would go because there are many places we download stuff.
