### ISSUE TITLE
Invoke_Instance_And_Static_Method_Win32_Process failed

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#24961]
This is on regular Windows 8.1 (well, Server 2012)

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171030.02/workItem/System.Management.Tests/analysis/xunit/System.Management.Tests.ManagementObjectTests~2FInvoke_Instance_And_Static_Method_Win32_Process

Seems notepad did not get terminated. Is the WMI "Terminate" asynchronous possibly? Consider a loop with sleeps. Or maybe it did terminate and the bug is in WMI process.Get. Consider using the regular Process class to check whether the PID is terminated.

@pjanotti

**Comment by pjanotti** [comment]
Terminate should be synchronous... another possibility is that the same process Id was reused then the call to Get did not throw the expected exception. I will see what we can do to make the test more reliable.

**Comment by danmosemsft** [comment]
Yes, that could be it. If the PID still exists, you can check the start time of the process has changed.

**Comment by Jiayili1** [comment]
same issue: https://github.com/dotnet/corefx/issues/24912

**Comment by pjanotti** [comment]
Related merge, #24975, should have fixed this (assuming that the diagnostic of pid re-use was right).

**Comment by pjanotti** [comment]
This is still happening, reopening.

**Comment by pjanotti** [comment]
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171103.09/workItem/System.Management.Tests/analysis/xunit/System.Management.Tests.ManagementObjectTests~2FInvoke_Instance_And_Static_Method_Win32_Process
