### ISSUE TITLE
StackExchange.Redis.StrongName, Version=1.2.4.0

### ISSUE THREAD

**Issue by hanxinimm** [dotnet/corefx#24970]
The type 'ConnectionMultiplexer' exists in both 'StackExchange.Redis.StrongName, Version=1.2.4.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' and 'StackExchange.Redis, Version=1.2.6.0, Culture=neutral, PublicKeyToken=null'	Hunter.Authorization.ApiCommandServer

![image](https://user-images.githubusercontent.com/13499426/32214320-66e0c128-be59-11e7-8b7b-656c0ae00ea2.png)

**Comment by karelz** [comment]
It does not seem to be related to CoreFX repo, but rather to StackExchange.Redis. Please ask the question on their repo/forum/SO.
