### ISSUE TITLE
Use Rss20FeedFormatter to deserialize and then serialize cause node docs in Rss feed got missing

### ISSUE THREAD

**Issue by JimboWei** [dotnet/corefx#24971]
Rss feeds file with node **docs** using `rss20ItemFormatter.ReadFrom()` to Deserialize and then using  `Rss20FeedFormatter.WriteTo()` to serialize , the node <docs> will disappear in result file.
rss feed file :
```
<rss version="2.0">
  <channel>
    <title>Valid docs</title>
    <link>http://purl.org/rss/2.0/</link>
    <description>foo</description>
    <docs>http://backend.userland.com/rss</docs>
  </channel>
</rss>
```
Result file :
```
<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:a10="http://www.w3.org/2005/Atom" version="2.0">
  <channel>
    <title>Valid docs</title>
    <link>http://purl.org/rss/2.0/</link>
    <description>foo</description>
  </channel>
</rss>
```

I try to **fix the Bug** adding some code after [this line](https://github.com/dotnet/corefx/blob/master/src/System.ServiceModel.Syndication/src/System/ServiceModel/Syndication/Rss20FeedFormatter.cs#L1335),
Add code:
```
//Documentation
if (Feed.Documentation != null)
{
    await writer.WriteElementStringAsync(Rss20Constants.DocumentationTag, Feed.Documentation.Uri.ToString()).ConfigureAwait(false);
}
```
The **docs** node can be serialize .

**Comment by shmao** [comment]
This was fixed after we reset the code base.
