### ISSUE TITLE
MemoryMappedFilesTests.DataShared failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#2498]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/1332/console
```
InterProcessCommunication.Tests.MemoryMappedFilesTests.DataShared [FAIL]
12:44:49       System.IO.IOException : The process cannot access the file '/tmp/MemoryMappedFilesTests_8729349d9699eb9cc0a6adf22b1b7afa/DataShared_16' because it is being used by another process.
12:44:50       Stack Trace:
12:44:50 Starting:    System.Collections.Immutable.Tests
12:44:50             at System.IO.UnixFileStream.SysCall[TArg1,TArg2](Func`4 sysCall, TArg1 arg1, TArg2 arg2, Boolean throwOnError)
12:44:50             at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
12:44:50             at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
12:44:50             at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
12:44:50             at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
12:44:50             at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
12:44:50             at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
12:44:50             at InterProcessCommunication.Tests.MemoryMappedFilesTests.DataShared()
12:44:50 Finished:    InterProcessCommunication.Tests
```

**Comment by stephentoub** [comment]
Failed again:
InterProcessCommunication.Tests.MemoryMappedFilesTests.DataShared [FAIL]
08:51:47       System.IO.IOException : The process cannot access the file '/tmp/MemoryMappedFilesTests_339a79be42f1b33c1db9597642dcdd9c/DataShared_16' because it is being used by another process.
08:51:47       Stack Trace:
08:51:47 Starting:    System.Collections.Immutable.Tests
08:51:47             at System.IO.UnixFileStream.SysCall[TArg1,TArg2](Func`4 sysCall, TArg1 arg1, TArg2 arg2, Boolean throwOnError)
08:51:47             at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
08:51:47             at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
08:51:47             at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
08:51:47             at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
08:51:47             at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
08:51:47             at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
08:51:47             at InterProcessCommunication.Tests.MemoryMappedFilesTests.DataShared()
08:51:48 Finished:    InterProcessCommunication.Tests
08:51:48 
08:51:48 === TEST EXECUTION SUMMARY ===
08:51:48    InterProcessCommunication.Tests  Total: 3, Errors: 0, Failed: 1, Skipped: 0, Time: 1.049s

**Comment by nguerrera** [comment]
Just saw this again: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/2608/console
```
00:09:33    InterProcessCommunication.Tests.MemoryMappedFilesTests.DataShared [FAIL]
00:09:33       System.IO.IOException : The process cannot access the file '/tmp/MemoryMappedFilesTests_jmk3cb2r.0tl/DataShared_17' because it is being used by another process.
00:09:33       Stack Trace:
00:09:34 Starting:    System.IO.Pipes.Tests
00:09:34             at System.IO.UnixFileStream.SysCall[TArg1,TArg2](Func`4 sysCall, TArg1 arg1, TArg2 arg2, Boolean throwOnError, Boolean ignoreNotSupported)
00:09:34             at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
00:09:34             at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
00:09:34             at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
00:09:34             at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
00:09:34             at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
00:09:34             at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
00:09:34             at InterProcessCommunication.Tests.MemoryMappedFilesTests.DataShared()
00:09:34 Finished:    System.ComponentModel.Annotations.Tests
00:09:34 Finished:    InterProcessCommunication.Tests
00:09:34 
```

**Comment by stephentoub** [comment]
Grrrr... I was really hoping I'd see the assert from https://github.com/dotnet/corefx/commit/bdb90cb4f98c60c33b6a8bfba3c3b0302ba8d76a the next time this occurred :-(

**Comment by stephentoub** [comment]
This hasn't failed again since https://github.com/dotnet/corefx/pull/3404 went in.  I'm going to close this now, and we can reopen it if we see it again.
