### ISSUE TITLE
Enhance System.Type.FullName to return non-null for open generic types.

### ISSUE THREAD

**Issue by lambdageek** [dotnet/corefx#24998]
Consider

```csharp
  class Foo<A,B> { }
  class H<T> { }
  class Bar<X> : Foo<Int, H<X>> { }
```

Currently `typeof (Bar<>).BaseType.FullName` returns `null`, as documented here https://docs.microsoft.com/en-us/dotnet/api/system.type.fullname?view=netcore-2.0#System_Type_FullName):

> The fully qualified name of the type, including its namespace but not its assembly; or null if the current instance represents a generic type parameter, an array type, pointer type, or byref type based on a type parameter, or a generic type that is not a generic type definition but contains unresolved type parameters.

I propose that instead `Type.FullName` is changed on .NET Core, .NET Framework and Xamarin to return a sensible string representation of open generic types.  For the example above, for example, a reasonable result may be: `"Foo<Int, H<X>>"`

**Comment by AtsushiKan** [comment]
`Type.FullName` is designed to round-trip with strings passed to `Type.GetType(String)`. That's why types that embed generic type parameter return null. There's no string you can pass to `Type.GetType(String)` that will retrieve a generic type parameter. `ToString()` is what you want to use when you need something that's human-descriptive.

**Comment by lambdageek** [comment]
`Type.GetType(String)` doesn't roundtrip with `Type.FullName` - at best `Type.AssemblyQualifiedName` may roundtrip - but of course maybe you got the type from a reflection-only assembly in which case the best you can really say is that `Type.ReflectionOnlyGetType(String)` may roundtrip with `Type.AssemblyQualifiedName`.

In short: I don't know what `Type.FullName` is for, but it's certainly not for general-purpose round-tripping.  So it might as well do something useful.

**Comment by AtsushiKan** [comment]
It round-trips for types defined in the current assembly or the core assembly, as well as round-tripping with Assembly.GetType(string). 

(And yes, `AssemblyQualifiedName` roundtrips as well (it's a concatenation of the assembly name and the `FullName` string.))

**Comment by lambdageek** [comment]
Hm. Well fair enough.
