### ISSUE TITLE
TcpClient bug in branch release/1.1.0 (Unix)

### ISSUE THREAD

**Issue by anthonywanted** [dotnet/corefx#24990]
https://github.com/dotnet/corefx/blob/release/1.1.0/src/System.Net.Sockets/src/System/Net/Sockets/TCPClient.Unix.cs
and
https://github.com/dotnet/corefx/blob/release/1.1.0/src/System.Net.Sockets/src/System/Net/Sockets/TCPClient.cs

ConnectAsync(string, int) will call ConnectAsyncCore(host, port);
ConnectAsync(IPAddress[], int) will call ConnectAsyncCore(IPAddress[], int);
ConnectAsync(IPAddress, int) will call BeginConnect

In ConnectAsyncCore(host, port) and ConnectAsyncCore(IPAddress[], int) will do this
if (_clientSocket != null)
{
throw new PlatformNotSupportedException(SR.net_sockets_connect_multiaddress_notsupported);
}

TcpClient.Client will call TcpClient.ClientCore
TcpClient.ClientCore will set _clientSocket;
So once we call TcpClient.Client, _clientSocket is not null, then ConnectAsyncCore(host, port) and ConnectAsyncCore(IPAddress[], int) will throw a wrong PlatformNotSupportedException

**Comment by stephentoub** [comment]
@anthonywanted, can you share a repro?  Are you concerned that a PlatformNotSupportedException is being thrown, or are you concerned about the message in the PNSE?

**Comment by anthonywanted** [comment]
Once I call client.Client, ConnectAsync(string, int) will throw a PNSE, even though I pass a ip string
So easy to reproduce the bug

TcpClient client = new TcpClient();
client.Client.NoDelay = true;
client.ConnectAsync(“127.0.0.1”,80); //Throw PNSE

Changing client.Client.NoDelay to NoDelay, everything works fine

The reason is what I said above.

**Comment by wfurt** [comment]
This works as expected when targeting 2.0 and 2.1. 
1.1 throws exception as reported. 
Do you have any thoughts on porting fixes back to 1.1 @karelz

**Comment by karelz** [comment]
It's fixed in latest version(s). Closing.
If there is large impact on multiple customers, we can consider porting to 1.1.
