### ISSUE TITLE
Multi-server System.IO.Pipes tests hanging on OSX

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#24994]

**Comment by karelz** [comment]
@stephentoub do you have any details / pointers? Are those older tests? New tests?

**Comment by stephentoub** [comment]
They're new: https://github.com/dotnet/corefx/pull/24995

**Comment by stephentoub** [comment]
It's the MultipleWaitingClients_ServerServesOneAtATime test I added; it's buggy.  I'll fix it.
