### ISSUE TITLE
System.Json bugs and perf issues

### ISSUE THREAD

**Issue by grant-d** [dotnet/corefx#25005]
We're using `System.Json` quite extensively and have run into a couple of issues. Some looks like design (inconsistency) issues, some may be code bugs. 

1. **Possible design bug**: Inconsistent handling of `null` array members:
  This works as expected: 
  ```C# 
   var a = new JsonArray(new JsonValue[] { "abc", 123, null }); // Note 3rd item is null
  ```
  This alternative pattern `throws` inside `Add` due to an explicit `null` guard:
  ```C#
  var b = new JsonArray(new JsonValue[] { "abc", 123 }); b.Add(null); // ArgumentNullException
  ```
  I see that the units support this behavior, but it seems to be an inconsistent design. Adding a `null` member to an array should be acceptable?

2. **Possible code bug**: `JsonType` derivation on `JsonPrimitive` seems faulty:
```C#
   var p = new JsonPrimitive(Guid.NewGuid()); // Guid
   var t = p.JsonType; // Expected: JsonType.String. Actual: JsonType.Number
```
  (The nested conditionals here may be iffy: [JsonPrimitive.cs](https://github.com/dotnet/corefx/blob/master/src/System.Json/src/System/Json/JsonPrimitive.cs#L118-L120))
  This case does not seem to be covered by any units.

```C#
  public override JsonType JsonType =>
    _value == null || _value.GetType() == typeof(char) || _value.GetType() == typeof(string)
    || _value.GetType() == typeof(DateTime) 
    || _value.GetType() == typeof(object)
    ? JsonType.String // DateTimeOffset || Guid || TimeSpan || Uri // <=========
    : _value.GetType() == typeof(bool) 
    ? JsonType.Boolean :
    JsonType.Number;
```

3. **Possible design bug**: `JsonPrimitive.ToString()` throws for some primitives.
  The following throws; I would expect to return the `Guid` in `string` form. Note that this is _not_ one of the expected errors that are explicitly `thrown` for some types (see notes on stack trace).
  I see that the units support this behavior, but it seems to be an inconsistent design.
```C#
  var p = new JsonPrimitive(Guid.NewGuid());
  var t = p.JsonType;
  var s = p.ToString(); // FormatException

  // Note that GetFormattedString explicitly throws for some types
  // But that's not happening here, since it's making it all the way to Guid.ToString()
  System.FormatException
    Message=Format String can be only "D", "d", "N", "n", "P", "p", "B", "b", "X" or "x".
    Source=System.Private.CoreLib
    StackTrace:
     at System.Guid.ToString(String format, IFormatProvider provider)
     at System.Json.JsonPrimitive.GetFormattedString()
     at System.Json.JsonValue.SaveInternal(TextWriter w)
     at System.Json.JsonValue.ToString()
```

4. **Perf: Equals is Expensive**:
  The straight-forward way to compare two `JsonValue` instances is to `ToString()` them both and then use a `StringComparer.Ordinal` comparer. But this is unnecessarily expensive considering the number of `string` allocs that need to happen internally while walking the tree. A better way would be to walk the tree regardless, but compare each individual `JsonObject`, `JsonArray` and `JsonPrimitive`.
  Something similar to this: [JsonValueComparer.cs](https://github.com/k2workflow/Clay/blob/master/src/SourceCode.Clay.Json/JsonValueComparer.cs)

[Benchmark](https://github.com/k2workflow/Clay/blob/master/src/SourceCode.Clay.Json.Bench/JsonEqualsBench.cs) (**2x improvement in both time & memory**)
```C#
          Method |      Mean |     Error |    StdDev | Scaled | ScaledSD |    Gen 0 |    Gen 1 |   Gen 2 | Allocated |
---------------- |----------:|----------:|----------:|-------:|---------:|---------:|---------:|--------:|----------:|
  ToStringEquals | 13.998 ms | 0.2782 ms | 0.5807 ms |   1.00 |     0.00 | 809.3750 | 434.3750 | 90.6250 | 6267600 B |
NewtonDeepEquals |  2.729 ms | 0.0514 ms | 0.0456 ms |   0.20 |     0.01 |        - |        - |       - |       0 B |
     SmartEquals |  6.817 ms | 0.1334 ms | 0.1638 ms |   0.49 |     0.02 | 789.0625 |        - |       - | 3323776 B |
```

5. **Perf: Clone is Expensive**:
   Similar reasoning to the previous bullet: `ToString` works but is expensive due to allocations on the way out and redundant parsing on the way back in.
   Here's an alternative approach that walks the tree and clones each node explicitly: [JsonClone.cs](https://github.com/k2workflow/Clay/blob/master/src/SourceCode.Clay.Json/JsonExtensions.cs#L304-L430)
  (Unfortunately even it isn't as memory-efficient as it could be, since `SortedDictionary` does not expose an `initialCapacity` parameter in order to pre-allocate an exact-sized map.)

[Benchmark](https://github.com/k2workflow/Clay/blob/master/src/SourceCode.Clay.Json.Bench/JsonCloneBench.cs) (**2-3x improvement in both time & memory**)
```
         Method |     Mean |     Error |    StdDev | Scaled | ScaledSD |     Gen 0 |    Gen 1 |   Gen 2 | Allocated |
--------------- |---------:|----------:|----------:|-------:|---------:|----------:|---------:|--------:|----------:|
  ToStringClone | 29.21 ms | 0.5792 ms | 0.5948 ms |   1.00 |     0.00 | 1562.5000 | 812.5000 | 62.5000 |   9.92 MB |
NewtonDeepClone | 19.16 ms | 0.3727 ms | 0.5101 ms |   0.66 |     0.02 | 1218.7500 | 562.5000 | 62.5000 |   7.02 MB |
     SmartClone | 10.14 ms | 0.1964 ms | 0.4311 ms |   0.35 |     0.02 |  671.8750 | 312.5000 |       - |   3.94 MB |
```

**Comment by danmosemsft** [comment]
@grant-d we ported System.Json  to make it possible to port existing code that already uses it. If you can, we  recommend using a different, higher performance Json serialization library like Newtonsoft.JSON. Is that an option?

**Comment by danmosemsft** [comment]
We would consider PR's though if they have minimal risk of breaking other users.

**Comment by grant-d** [comment]
I personally don't consider Newtonsoft to be higher-performance as it is reflection and string heavy. I have had better performance results from `System.Json` ever since it landed in `corefxlab`; it is much closer to the wire.

**Comment by grant-d** [comment]
Newtonsoft comparative benchmarks added (using `JToken.DeepClone`/`DeepEquals`)
I am not sure whether the allocs on my code are coming from, will investigate

**Comment by grant-d** [comment]
Benchmark comparing `Newtonsoft.Linq.JObject.Parse` to `System.Json.JsonValue.Parse`:
(Roughly equal in performance)

```
         Method |     Mean |     Error |    StdDev | Scaled | ScaledSD |    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
--------------- |---------:|----------:|----------:|-------:|---------:|---------:|---------:|---------:|----------:|
    NewtonParse | 6.146 ms | 0.1225 ms | 0.2271 ms |   1.00 |     0.00 | 395.2546 | 267.6505 | 120.0810 |   3.02 MB |
 JsonValueParse | 6.699 ms | 0.1310 ms | 0.1345 ms |   1.09 |     0.05 | 434.3750 | 252.0833 |  78.1250 |   2.99 MB |
```

**Comment by grant-d** [comment]
Benchmark comparing `Newtonsoft.Linq.JObject.ToString to System.Json.JsonValue.ToString:
(Roughly equal in performance)
```
            Method |     Mean |     Error |    StdDev | Scaled | ScaledSD |    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
------------------ |---------:|----------:|----------:|-------:|---------:|---------:|---------:|---------:|----------:|
    NewtonToString | 5.842 ms | 0.1159 ms | 0.1699 ms |   1.00 |     0.00 | 392.1875 | 265.1042 | 119.7917 |   3.02 MB |
 JsonValueToString | 6.715 ms | 0.1307 ms | 0.1223 ms |   1.15 |     0.04 | 435.4167 | 252.6042 |  78.1250 |   2.99 MB |
```

**Comment by karelz** [comment]
@grant-d I would recommend to break down your issue into separate bug reports. If you have PRs for some, we can definitely consider them (assuming compat impact is reasonable).

**Comment by grant-d** [comment]
No problem @karelz , I will close this issue and have opened new individual ones:

https://github.com/dotnet/corefx/issues/25018
https://github.com/dotnet/corefx/issues/25019
https://github.com/dotnet/corefx/issues/25020
https://github.com/dotnet/corefx/issues/25021
https://github.com/dotnet/corefx/issues/25022

**Comment by karelz** [comment]
Great, thanks!
@tarekgh can you please look at them one by one and asses which PRs we would take vs. not?

**Comment by grant-d** [comment]
> we ported System.Json to make it possible to port existing code that already uses it
Thanks @danmosemsft , I didn't realize this was a port, I thought it was brand-new. Which is why I have been surprised regarding its semantics and performance. 
I have submitted the issues anyway, but might look at migrating to `Newtonsoft`.
