### ISSUE TITLE
Should Directory.GetDirectories (and related methods) take a StringComparison overload?

### ISSUE THREAD

**Issue by rianjs** [dotnet/corefx#25008]
This matters less on Windows, but it's more significant on platforms where case-sensitive filesystems are more common.

**Comment by danmosemsft** [comment]
@JeremyKuhne as he's lookign at these enumeration API.

**Comment by JeremyKuhne** [comment]
Currently we do case sensitive on Unix and insensitive on Mac/Windows. The future plan is to allow providing custom filters. See #18922 for a related request. If there are other matching scenarios you're interested in please share them as well.

**Comment by JeremyKuhne** [comment]
#25873 should take care of this. We'll offer explicit options for IgnoreCase and you'll be able to extend to match for more complicated string comparison types.
