### ISSUE TITLE
How to build CoreFX for x86 Linux

### ISSUE THREAD

**Issue by philippweidhas** [dotnet/corefx#25002]
Hallo there im looking for a guide or a way to build the CoreFX project for an x86 Linux based Project.
I have already sucessfully build coreclr for x86 following these  [CoreCLR build guide](https://github.com/dotnet/coreclr/issues/13192#issuecomment-320188913).
Now i need something like that for CoreFX,
Im thankful for help.

Greetings from Germany

Philipp

[EDIT] Fix link by @karelz

**Comment by abdevnet** [comment]
I'm interested in this too.

**Comment by seanshpark** [comment]
Hello, like as the one mentioned as CoreCLR, almost the same

Install packages described at https://github.com/dotnet/corefx/blob/master/Documentation/building/unix-instructions.md#user-content-linux

And get the source, then prepare RootFS for x86,
```
git clone https://github.com/dotnet/corefx
cd corefx
sudo ./cross/build-rootfs.sh x86
```
And build
```
./build-native.sh -debug -- clang3.8
./build-native.sh -debug -buildArch=x86 -- cross clang3.8
./build-managed.sh -BuildTests=false
```
Also read https://github.com/dotnet/corefx/blob/master/Documentation/building/cross-building.md for cross building (the document is about cross building arm but think it as x86)

**Comment by philippweidhas** [comment]
Hello @seanshpark ,

i finally found the time to try to build the binaries following your instructions. I was able to generate:
./build-native.sh -debug -- clang3.8
./build-native.sh -debug -buildArch=x86 -- cross clang3.8

im working on:
./build-managed.sh -BuildTests=false

Now im looking for the way to integrate this binaries on my destination linux system. Where do i have to place the Binaires of corecr and corefx? Maybe i read over the right part of the linked guides.

Thx for your help.

**Comment by philippweidhas** [comment]
Hello again @seanshpark ,

i receive following erros by building the build-managed.sh : 
/home/arbeit/Tools/depProj.targets(83,5): error : Error no assets were resolved from NuGet packages. [/home/arbeit/corefx/external/netstandard/netstandard.depproj]
/home/arbeit/Tools/depProj.targets(83,5): error : Error no assets were resolved from NuGet packages. [/home/arbeit/corefx/external/docs/docs.depproj]
/home/arbeit/Tools/depProj.targets(83,5): error : Error no assets were resolved from NuGet packages. [/home/arbeit/corefx/external/ILLink/ILLink.depproj]

Could you help me im looking for the solution but was not lucky.

Best Wishes

Philipp

**Comment by seanshpark** [comment]
> /home/arbeit/Tools/depProj.targets(83,5): error : Error no assets were resolved from NuGet packages. [/home/arbeit/corefx/external/netstandard/netstandard.depproj]

Um... Sorry but never seen this. Maybe posting a new issue and ask for help would be a way...

**Comment by seanshpark** [comment]
> Now im looking for the way to integrate this binaries on my destination linux system. Where do i have to place the Binaires of corecr and corefx?

I'm not sure there is a guide but one keyword that might help is `overlay` like in https://github.com/dotnet/coreclr/blob/master/Documentation/building/unix-test-instructions.md page. When testing CoreCLR, CoreFX libraries are needed and this overlay is gatherings of the libraries (this is what I think but maybe not correct)

This is something like what I do to prepare the overlay
```
mkdir -p $NETCORE/overlay
cd  $NETCORE/overlay

cp -v $NETCORE/corefx/bin/runtime/netcoreapp-Linux-Debug-x64/*.dll .
cp -v $NETCORE/corefx/bin/Linux.x86.Debug/native/*.so .
cp -vR $NETCORE/coreclr/bin/Product/Linux.x86.Debug/* .

# some test requires dotnet
cp corerun dotnet

# remove ni as it's x64
rm System.Private.CoreLib.ni.dll
```

where `NETCORE` points to the root of CoreCLR and CoreFX path.

Put the application DLL (or EXE) built from any platform in `$NETCORE/overlay` and use `corerun` or copied `dotnet` to run the application. For example,
```
./corerun helloworld.dll
```
I'm also not sure as this small steps are from several months ago. If you have any problem, please add a comment.

**Comment by weshaggard** [comment]
@philippweidhas is this still something you are working on and still need help with?

**Comment by philippweidhas** [comment]
@seanshpark @weshaggard thx for any help. The solution was building corefx and corecr in the same vm. First build corecr and then build corefx. Thats it.
