### ISSUE TITLE
Event logging for System.Net.*

### ISSUE THREAD

**Issue by pgavlin** [dotnet/corefx#2500]
Event logging for these assemblies is currently unimplemented: we need to design and implement a solution.

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar

**Comment by stephentoub** [comment]
Any reason not to just use an EventSource?

**Comment by davidsh** [comment]
That is our plan.  We just haven't done it yet.  We've been getting some of it to work in System.Net.Sockets and working out issues with it with other .NET folks like @vancem

**Comment by stephentoub** [comment]
Great.

**Comment by omariom** [comment]
Is EventSource going to be supported on other platforms? 
For me it is a synonym for ETW.

**Comment by stephentoub** [comment]
> Is EventSource going to be supported on other platforms?

Yes. EventSource has two mechanisms: the ability to target registered EventListeners, and the ability to target a platform-specific tracing scheme. The former is already working across Windows and Unix. The latter targets ETW on Windows and is currently a nop on UNIX, but the plan is to target something. @brianrob can provide more info.

**Comment by omariom** [comment]
Great! No need to abstract tracing  as I planned.

**Comment by davidfowl** [comment]
One concern I have (and I don't know enough about the EventSource impl) is the amount of "stuff" that gets used when using a low level APIs like sockets. It's great to have tracing at such a low level in the stack (like we do today in .NET Framework), but today creating a socket allocates a boatload of strings because -> tracing -> configuration -> xml -> rabbit hole. I'd like to see us not repeat the same mistakes. We had some socket code on the startup path in dnx and it costed us 250 ms (testing on my Macbook) of startup time. We worked around it like so https://github.com/aspnet/dnx/blob/dev/src/dnx.clr.managed/DomainManager.cs#L62

:smile:

**Comment by vancem** [comment]
Two Points:


  1.  EventSource is NOT just a conduit to ETW.    While it was designed to let you log to ETW trivially, it really couples EventSources to EventListeners (there is just a built in EventListener for ETW).   Thus it is a cross-platform concept (we will support it on Linux).
  2.  EventSource can be VERY lean when it is not operating.    The check can be literally 2 instructions (compare and branch)  There are no config files to look up (unless you make listeners that do this).


That said, you can always screw up perf.   However EventSource really is designed for things like logging of the Socket library etc.   You should be using it.


If you have any questions, I can probably answer them...


Vance



________________________________

**Comment by brianrob** [comment]
For Linux, we plan to target LTTng for all cases where we log to ETW on Windows.  This includes EventSource and events that are logged from the runtime itself.  For more details on the plan, see https://github.com/dotnet/coreclr/blob/master/Documentation/coding-guidelines/cross-platform-performance-and-eventing.md.

**Comment by tushargupta51** [comment]
Is there any update on the EventSource support on linux/mac as described in this document: https://github.com/dotnet/coreclr/blob/master/Documentation/coding-guidelines/cross-platform-performance-and-eventing.md.? We are using EventSource in our library that is cross platform and was wondering how EventSource.WriteEvent(..) will work by default on linux/mac. And if there is any support for EventListener coming soon on these platforms?

**Comment by stephentoub** [comment]
> And if there is any support for EventListener coming soon on these platforms?

EventListener already works on Linux and OS X.

**Comment by CIPop** [comment]
Completed by @josguil within #5101 and #5151
