### ISSUE TITLE
Remove dead code - SafeWinHttpHandleWithCallback

### ISSUE THREAD

**Issue by pgavlin** [dotnet/corefx#2501]
SafeWinHttpHandleWithCallback is a better pattern; SafeWinHttpHandle is probably a better name. The implementation for the former should probably be folded into the latter.

**Comment by davidsh** [comment]
While fixing various WinHttpHandler bugs regarding leaking handles, I've noticed that the `SafeWinHttpHandleWithCallback` is using the `SafeHandle` pattern in an incorrect manner regarding the `Dispose(bool disposing)` method. So, I will be handling this issue as part of my longer term work of this consolidation.

**Comment by SidharthNabar** [comment]
Marking this as future since this is not required for RTM and the tracking issue #2165 is in Future milestone

**Comment by CIPop** [comment]
@davidsh, @karelz I remember this was a reliability issue: the app may crash if the callback is called and CLR unloaded the AppDomain (or otherwise collected the delegate). 
This is applicable to both WinHttp and WebSockets.Client.

@jkotas could you please review the pattern? 
[WinHttpWebSocketCallback](https://github.com/dotnet/corefx/blob/master/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/WinHttpWebSocketCallback.cs) is kept alive by [SafeWinHttpHandleWithCallback](https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/Common/src/Interop/Windows/winhttp/Interop.SafeWinHttpHandle.cs#L81). 
The pattern is described by https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/Common/src/Interop/Windows/winhttp/Interop.SafeWinHttpHandle.cs#L81.

**Comment by jkotas** [comment]
> `SafeWinHttpHandleWithCallback` is using the `SafeHandle` pattern in an incorrect manner regarding the Dispose(bool disposing) method

I agree with this. Maybe it works, but it is not how the safe handles are meant to be used.

> the app may crash if the callback is called and CLR unloaded the AppDomain

I do not see how this pattern can prevent unload of AppDomain. Anyway, there are no AppDomains in .NET Core so it is not something to worry about.

> otherwise collected the delegate

Keeping the delegate in `static Interop.WinHttp.WINHTTP_STATUS_CALLBACK s_StaticCallbackDelegate` is sufficient to prevent it from getting collected.

**Comment by CIPop** [comment]
> I do not see how this pattern can prevent unload of AppDomain.

I wasn't sure either (couldn't find enough documentation at the time) but I didn't see the bug on .Net Desktop after adding this (most likely timing).

>  there are no AppDomains in .NET Core so it is not something to worry about.
> Keeping the delegate in static Interop.WinHttp.WINHTTP_STATUS_CALLBACK s_StaticCallbackDelegate is sufficient to prevent it from getting collected.

Thanks @jkotas! That actually simplifies the design a lot.

**Comment by karelz** [comment]
Next steps:
1. Merge the 2 types into SafeWinHttpHandle.
2. Run perf & stress tests (that's where the problem was discovered)

**Comment by matekm** [comment]
Hi @karelz 

I see this ticket is up for grabs and no one actively working on it. Will it be ok if I start work on it?

As I understand there are following things that needs to be done:
1. Move AttachCallback and DetachCallback from SafeWinHttpHandleWithCallback  to SafeWinHttpHandle
2. Implement proper dispose in SafeWinHttpHandle
3. Replace SafeWinHttpHandleWithCallback  with SafeWinHttpHandle in various places in corefx

there is also a note about perf and stress test, what do you mean by that? Is that some kinds of tests that are in corefx source code repository?

**Comment by davidsh** [comment]
Thx for your interest in this issue.  Actually, this issue should be closed now.  It is no longer needed.

When we did the work of switching the ClientWebSocket implementation from using WinHTTP to the new managed handler (SocketsHttpHandler), we no longer use the SafeWinHttpHandleWithCallback type.

In fact, that type could be removed from the repo now.

**Comment by matekm** [comment]
Thanks @davidsh - should I create a ticket for that and then remove this type or someone else will handle that?

**Comment by davidsh** [comment]
If you want, feel free to submit a PR to remove the type and use this issue number as the "Fixes XXX" line in your commit.

**Comment by davidsh** [comment]
I can assign this issue to you if you want.

**Comment by karelz** [comment]
I have renamed the issue and assigned to @matekm. Thanks for your help!
