### ISSUE TITLE
Facades, PermissionSets and RedistList are missing from Microsoft.TargetingPack.NETFramework.* nuget packages.

### ISSUE THREAD

**Issue by hubuk** [dotnet/corefx#25012]
I really don't know if these packages are still in use but I cannot find any other nuget packages closer to the .NET Framework developer packs than these. My use-case is to build CPS projects targeting net* TFMs on a Windows machine without Visual Studio and on \*NIX systems without mono. Referencing a single nuget with an assistance of `<FrameworkPathOverride>` makes this a simple task. As far as I know these missing directories are required for dotnet to build projects targeting net\* TFMs and to run tests for them.

Is there any chance to get the packages updated or is there any other approach that should be taken for my use-case?
I already know that [aspnet/BuildTools](https://github.com/aspnet/BuildTools) is using https://aspnetcore.blob.core.windows.net/buildtools/netfx/4.6.1/netfx.4.6.1.tar.gz But I found no out-of-the-box way of unpacking tar.gz files on Windows. In addition this archive contains targeting packs for all previous version of .NET Framework.

**Comment by weshaggard** [comment]
These packages are currently intended to only be used by our build infrastructure. They aren't supported for general use. That said we realize there is a gap here and what you ask for is something we need and there issues like https://github.com/dotnet/corefx/issues/3934 which have requested them but we just haven't ever got enough support to fund that work properly. However I think this is definitely something we should try to fund.
 cc @richlander

**Comment by weshaggard** [comment]
There are no plans to make Microsoft.TargetingPack.NETFramework.* packages support this as they are only intended for our custom build infrastructure. @hubuk If the general scenario is something you want to push on I suggest adding comments to https://github.com/dotnet/corefx/issues/3934
