### ISSUE TITLE
System.Json: JsonValue.Equals() is expensive

### ISSUE THREAD

**Issue by grant-d** [dotnet/corefx#25021]
Comparing two `JsonValue` instances for equality is a common operation. The current idiom is expensive compared to the alternatives. The provided prototype shows a micro-bench result of **2-3x** improvement.

# Rationale and Usage
The straight-forward way to compare two `JsonValue` instances is to `ToString()` them both and then use a `StringComparer.Ordinal` comparer. But this is unnecessarily expensive considering the number of internal `string` allocs that need to happen internally while walking the tree. 

```C#
var json1 = new JsonObject(...);
var json2 = new JsonObject(...);

// Current idiom for equality
var str1 = json1.ToString(); // Many internal string allocs
var str2 = json2.ToString();
var equal = StringComparer.Ordinal.Equals(str1, str2);

// Proposed method
var equal = JsonValueComparer.Strict.Equals(json1, json2);
```

An alternatively approach is to migrate to `Newtonsoft.Linq.JValue` which has similar semantics and performs adequately.

# Proposed API
```C#
public abstract class JsonValueComparer : IEqualityComparer<JsonValue>
{
    /// <summary>
    /// Gets a <see cref="JsonValueComparer"/> that compares all fields of a <see cref="JsonValue"/>
    /// value in a strict manner (ordinal string comparisons, deterministic ordering of members).
    /// </summary>
    public static JsonValueComparer Strict { get; } = new JsonStrictComparer();

    protected JsonValueComparer()
    { }

    /// <summary>
    /// Determines whether the specified objects are equal.
    /// </summary>
    /// <param name="x">The first object to compare.</param>
    /// <param name="y">The second object to compare.</param>
    /// <returns>
    /// true if the specified objects are equal; otherwise, false.
    /// </returns>
    public abstract bool Equals(JsonValue x, JsonValue y);

    /// <summary>
    /// Returns a hash code for this instance.
    /// </summary>
    /// <param name="obj">The object.</param>
    /// <returns>
    /// A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table.
    /// </returns>
    public abstract int GetHashCode(JsonValue obj);

    private sealed class JsonStrictComparer : JsonValueComparer
    {...}
}
```

# Details
A less expensive way would be to walk the internal tree and directly compare each individual member directly, without converting to a `string`.
Ideally this requires the introduction of a new `JsonValueComparer` class, similar to this prototype: [JsonValueComparer.cs](https://github.com/k2workflow/Clay/blob/master/src/SourceCode.Clay.Json/JsonValueComparer.cs)
We'd need to decide on comparison semantics. 
For example the `Strict` comparer enforces ordinal string rules and co-located members. Perhaps there are other comparers.

# Open Questions
* Since `JsonValue` is `abstract`, end users may have inherited from it. Not sure how to handle equality in those cases, perhaps just using a traditional `object.Equals` check as the final fallback?
* Do we need other comparers that (say) allow different orderings of members.

# Pull Request
I am happy to PR myself, given a finalized design.

# Benchmarks
_Per recommendation from @danmosemsft, included `Newtonsoft` in benchmark_

[Benchmark](https://github.com/k2workflow/Clay/blob/master/src/SourceCode.Clay.Json.Bench/JsonEqualsBench.cs) (**2-3x improvement in both time & memory**)
```C#
           Method |      Mean |     Error |    StdDev | Scaled |    Gen 0 |    Gen 1 |   Gen 2 | Allocated |
----------------- |----------:|----------:|----------:|-------:|---------:|---------:|--------:|----------:|
   ToStringEquals | 13.818 ms | 0.3012 ms | 0.3347 ms |   1.00 | 808.4677 | 435.9879 | 89.7177 | 6267582 B |
 NewtonDeepEquals |  3.028 ms | 0.0657 ms | 0.1854 ms |   0.22 |        - |        - |       - |       0 B |
       JsonEquals |  5.940 ms | 0.1109 ms | 0.1187 ms |   0.43 | 531.2500 |        - |       - | 2258560 B |
```

_[See original issue summary [here](https://github.com/dotnet/corefx/issues/25005), @karelz suggested I submit separately]_

**Comment by grant-d** [comment]
Benchmark comparing `Newtonsoft.Linq.JObject.ToString` to `System.Json.JsonValue.ToString`:
(Roughly equal in performance and `GC`)
```
            Method |     Mean |     Error |    StdDev | Scaled | ScaledSD |    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
------------------ |---------:|----------:|----------:|-------:|---------:|---------:|---------:|---------:|----------:|
    NewtonToString | 5.842 ms | 0.1159 ms | 0.1699 ms |   1.00 |     0.00 | 392.1875 | 265.1042 | 119.7917 |   3.02 MB |
 JsonValueToString | 6.715 ms | 0.1307 ms | 0.1223 ms |   1.15 |     0.04 | 435.4167 | 252.6042 |  78.1250 |   2.99 MB |
```

**Comment by grant-d** [comment]
@danmosemsft, @karelz, I am going to cut short my losses and move to a different json lib.
I don't want to waste your or my time on fixing this - it requires a complete overhaul in some places.
I did not realize it was a port, so expected it to be well-designed and performant.

Feel free to open again if you want to fix the issues anyway.

**Comment by karelz** [comment]
`System.Json` is a Json parser predating Json.NET. AFAIK its key value is that you don't need external dependency - some enterprise customers don't like non-Microsoft dependencies, it is also useful for libraries to not drag in other libraries for just.
There is no active development in the library. However, we would take low-risk changes to it if they help.

Our general recommendation for Json parsers is:
* [JiL](https://github.com/kevin-montrose/Jil) for performance
* [Json.NET](https://www.newtonsoft.com/json) for usability
* `System.Json` for no 3rd party dependencies

We have an active prototype for a fast Json reader/writer/DOM: [System.Text.Json](https://github.com/dotnet/corefxlab/tree/master/src/System.Text.Json). However, we do not have fixed schedule and there is no guarantee it will ship at all. If you want to explore and contribute there, we will be happy to take PRs.

**Comment by grant-d** [comment]
Awesome, thanks @karelz, that's exactly what I was looking for. I will take a look at the latter.
