### ISSUE TITLE
Networking - SocketsHttpHandler Epic

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#25025]

**Comment by stephentoub** [comment]
@karelz, can this be closed?

**Comment by karelz** [comment]
Technically we're not done with all features tied to it yet - let's keep it opened, so that it shows on ZenHub board for 2.1 Epics.

**Comment by stephentoub** [comment]
It was the "alpha" part I was questioning mainly.  Your renaming it now addressed that. Thanks.

**Comment by karelz** [comment]
It is now turned on as default HttpClientHandler. We have a bug tail and a small feature adjustment in progress, otherwise it is done. Closing.
