### ISSUE TITLE
AtomFeedPositiveTest_WsFeedIcon Failed

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#25058]
Test `System.ServiceModel.Syndication.Tests.BasicScenarioTests.AtomFeedPositiveTest_WsFeedIcon` failed.

The expected <icon> element is,

```xml
<icon>http://example.com/icon.jpg</icon>
```

The actual <icon> is,

```xml
<icon xmlns="http://www.w3.org/2005/Atom">http://example.com/icon.jpg</icon>
```

The behavior, however, is the same as the full framework's.

**Comment by shmao** [comment]
@JimboWei can you take a look at this issue? I tried the test on desktop and I got the same behavior.

**Comment by JimboWei** [comment]
@shmao I have tested the issue, got different result with yours:

**coreFx actual** is,  `<icon>http://example.com/icon.jpg</icon>`
**full framework's actual** is, `<icon xmlns="http://www.w3.org/2005/Atom">http://example.com/icon.jpg</icon>`

In coreFx the element `<icon>` is a property of class `SyndicationFeed` 
In full framework's the element `<icon>` is an item of `SyndicationFeed.ElementExtensions` 

Is it possible your test branch contain some product [change](https://github.com/dotnet/corefx/pull/25059/files#diff-17e5b9d84669baaca0f770eac9913409L47), in this PR #25059?

PS:
In **coreFx** current master branch the element `<icon>favicon.ico</icon>` will throw an exception : This operation is not supported for a **relative** URI.

But in **full framework's** is can get result `<icon xmlns="http://www.w3.org/2005/Atom">favicon.ico</icon>`

**Comment by shmao** [comment]
@JimboWei Sorry I didn't make it clear. Yes, the test `AtomFeedPositiveTest_WsFeedIcon` is being added by PR #25059. After that PR, corefx would have the same behavior of full framework's, i.e. corefx's actual would be ,

```c#
<icon xmlns="http://www.w3.org/2005/Atom">http://example.com/icon.jpg</icon>
```

And that would fail the test, which means the full framework's behavior fails the test. So I wondered if the test is as expected.

Yes, the element <icon> currently,  before PR #25059, is a property of class SyndicationFeed as you found. After that PR, <icon> would become an element extension as it is on desktop.

**Comment by shmao** [comment]
@JimboWei I've merged PR #25059. You can fetch the latest master and you should be able to repro the test failure by removing the [ActiveIssue] from test `AtomFeedPositiveTest_WsFeedIcon`.

**Comment by JimboWei** [comment]
@shmao I have fixed this issue in PR #24972.
It is because I used `XmlWriter ` instead of `XmlDictionaryWriter `, then got different result.

Current full framework and coreFx can get same result:
`XmlWriter `will get `<icon xmlns="http://www.w3.org/2005/Atom">http://example.com/icon.jpg</icon>`
`XmlDictionaryWriter `will get `<icon>http://example.com/icon.jpg</icon>`

**Comment by shmao** [comment]
@JimboWei sounds good. Thanks for root causing the issue. Just to confirm, is `XmlDictionaryWriter` the one that we used in our exiting desktop tests?

**Comment by JimboWei** [comment]
Yes, the added test cases `AtomEntryPositiveTest` , `AtomFeedPositiveTest `, `RssEntryPositiveTest `, `RssFeedPositiveTest` all used `XmlDictionaryWriter ` in desktop tests.
