### ISSUE TITLE
Build breaks when targetting UWP SDK 16299 (DotNet core) along with Microsoft advertising

### ISSUE THREAD

**Issue by schemburkar** [dotnet/corefx#25063]
The UWP app build in Release mode breaks when targeting the latest UWP SDK that uses dotnet core toolchain along with Microsoft advertising sdk.

Environment: 
Visual Studio 2017 (15.4.1) 
UWP SDK 16299 
Microsoft Advertising SDK 10.0.7 
UWP App project ( Target Version 10.0.16299.0, Min Version 10.0.16299.0)
Microsoft.NETCore.UniversalWindowsPlatform  6.0.1
NetStandard 2.0.0

Error Details:
1>  Task "ResolveToolchainRequiredAssemblyRoots"
1>  Done executing task "ResolveToolchainRequiredAssemblyRoots".
1>  Task "ILTransformAssemblyClosure"
1>C:\Users\shubh\.nuget\packages\microsoft.net.native.compiler\2.0.0\tools\Microsoft.NetNative.targets(726,5): error : ILT1307: Assemblies 'D:\Next Applications\Near Me\SourceCode\Source Code-10.0\NextApps.MapsPlus.Universal\obj\x64\Release\ilc\in\WinMetadata\Microsoft.Advertising.winmd' and 'C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.Advertising.Xaml\10.0\References\CommonConfiguration\neutral\Microsoft.Advertising.winmd' have conflicting simple names.
1>  Done executing task "ILTransformAssemblyClosure" -- FAILED.
1>  Done building target "ConstructILTransformAssemblyClosure" in file "Preparation" -- FAILED.
1>  Done building project "Preparation" -- FAILED.
1>  Compilation failed
1>  
1>  The command exited with code 1201.

Problem is in Release mode only, debug builds are fine. Release mode has Compile with .Net native tool chain flag On.

**Comment by Moreno-Borsalino** [comment]
Same problem here with the same configuration but on another file:
error : ILT1307: Assemblies 'E:\DevProjects\VisualStudio11\PasswordSyncFluent3\obj\x86\Release\ilc\in\WinMetadata\Microsoft.Services.Store.Engagement.winmd' and 'C:\Users\Moreno\.nuget\packages\microsoft.services.store.engagement\10.1706.16001\SDK\Windows Kits\10\ExtensionSDKs\Microsoft.Services.Store.Engagement\10.0\References\CommonConfiguration\neutral\Microsoft.Services.Store.Engagement.winmd' have conflicting simple names.

**Comment by danmosemsft** [comment]
@tijoytom this seems an issue with the SDK or toolchain. Where is the right place to get help with that?

**Comment by karelz** [comment]
netnativehelp@microsoft.com is the right place to file bugs against .NET Native tooling. Closing here ...

**Comment by schemburkar** [comment]
@karelz I can't send an email to netnativehelp@microsoft.com, postmaster delivery failed. The email is Microsoft internal only. Can you loop them in for me with the details?

**Comment by karelz** [comment]
Alias updated to the external one (dotnetnative@microsoft.com) - see [.NET Native help](https://blogs.msdn.microsoft.com/dotnet/2014/05/21/net-native-deep-dive-help-i-hit-a-missingmetadataexception/).

My apologies, I copied the wrong alias from some MSDN forum post I found :(
