### ISSUE TITLE
Optimize locking patterns in System.Net.WebSockets.Client.

### ISSUE THREAD

**Issue by pgavlin** [dotnet/corefx#2506]
For example, release the lock between operations and check, under the lock, that the state is still valid before continuing.

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar

**Comment by karelz** [comment]
There should be TODOs in the code point to this issue.

@davidsh's gut feel is that this may be hard - you have to worry about callbacks, etc.

**Comment by davidsh** [comment]
This has been obsoleted since we no longer use WinHTTP for System.Net.WebSockets.Client.
