### ISSUE TITLE
How can I send some requests from authenticated proxy server ?

### ISSUE THREAD

**Issue by saeedmsdi** [dotnet/corefx#25062]
Hi,

I have an application wants to send some of outbound requests from an authenticated proxy server.
I have `schema` `host` `port` `username` and `password` of my proxy server.

I have 2 problem: 

1. how can I implement for specific outbound addresses not all.
2.  how can send this requests from proxy server!

I just find [this](http://josephwoodward.co.uk/2016/07/proxying-http-requests-asp-net-core-using-kestrel) pkg, but it doesn't help me!

thank

**Comment by karelz** [comment]
I am not sure what exactly you're asking for.
If you need to make HTTP requests, use `HttpClient` class. If it doesn't work as it should, please ask specific question, ideally with repro.
If you have questions regarding HTTP server (Kestrel, ASP.NET), please ask on https://github.com/aspnet
