### ISSUE TITLE
When I try to build the corefx in my local with VS2017 enterprise, it always point to community.

### ISSUE THREAD

**Issue by bertdev** [dotnet/corefx#25070]
![image](https://user-images.githubusercontent.com/33082483/32431896-4087655c-c310-11e7-90f2-b265f5938287.png)

Actually I have installed an enterprise version of VS2017.

**Comment by danmosemsft** [comment]
@bertdev did you try doing repair on your VS installation? (Did you have Community before?)

**Comment by karelz** [comment]
@weshaggard is it known problem?

**Comment by weshaggard** [comment]
It isn't a known problem. I might also suggest you do a clean build as the CMake generated files might be outdated based on your current VS isntalles.

**Comment by bertdev** [comment]
Thanks guys. I will try to fix based on your comments. And will update progress later.

**Comment by bertdev** [comment]
My local env have community before and later when company apply the license of enterprise, I installed an enterprise version again. Now I am trying to clean my local env first, then install enterprise again to see what happened.

**Comment by danmosemsft** [comment]
@bertdev any luck?

**Comment by bertdev** [comment]
Thanks guys. Sorry for forgetting update. I installed enterprise again and now it works.
