### ISSUE TITLE
Client cert auth doesn't work in HttpClientHandler

### ISSUE THREAD

**Issue by kchanlee** [dotnet/corefx#25072]
We have a Nginx server that lives behind a Barracuda Web Application Firewall. We configure the firewall to only allow request with specific client cert. I am writing code leveraging on `HttpClient` to access Nginx.

With the following .Net Core 2.0 code, I always get `System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A security error occurred`
```
                var cert = FindCertificateByThumbprint("1A7201E21CA93CAFED9FDCD1736716F606A22651");

                using (var handler = HttpMessageHandlerFactory.Create(cert))
                using (var client = new HttpClient(handler))
                {
                    client.BaseAddress = new Uri("https://release.sample.com");
                    client.DefaultRequestHeaders.Host = "release.sample.com";

                    var postString = ...  // some json data

                    using (var postContent = new StringContent(postString, Encoding.UTF8, "application/json"))
                    using (var response = await client.PostAsync("/some_api", postContent))
                    {
                        var responseContent = await response.Content.ReadAsStringAsync();

                        Console.WriteLine(responseContent);
                    }
                }
```
```
        public static HttpMessageHandler Create(X509Certificate2 cert)
        {
            var handler = new HttpClientHandler();
            handler.ClientCertificateOptions = ClientCertificateOption.Manual;
            handler.ClientCertificates.Add(cert);
            return handler;
        }
```

But if I switch to .Net Framework 4.6.1 with the following code change (1 line only), it works:
```
            var handler = new WebRequestHandler();
```

I have no ideas about this. What's the difference between .Net Core `HttpClientHandler` and .Net Framework `WebRequestHandler`?How can I make it work in .Net Core 2.0? Can anyone help me? Thanks in advance!

My application is an Asp.Net Core 2.0 web app based on .Net Core 2.0 running on Windows 10 x64, and is deployed as an Azure WebApp

Here is the simplest code that reproduces the issue, it is a console app: https://github.com/kchanlee/HttpMessageHandlerIssue

**Comment by davidsh** [comment]
Looking at the code you have I don't see anything in particular that points to a problem.  

In order to help further, we would need a real repro of some kind using the real certificates and server endpoint.  Or perhaps you can get detailed WireShark and other traces.  There is something going on with the TLS/SSL handshake (which is why you get the "security error").  But only more detailed logs will help point out the problem.

**Comment by kchanlee** [comment]
Hello, here are packets captured by Wireshark [packets.zip](https://github.com/dotnet/corefx/files/1448828/packets.zip). (My Wireshark didn't capture packets from my computer to server...)

And I find something more interesting. I add the following .Net Core code, then add a break point inside the callback and start **debug**ging, it works. But if I debug without this break point or run without debugging, it doesn't work.
```
            handler.ServerCertificateCustomValidationCallback = (request, serverCert, serverCertChain, error) =>
            {
                return true;
            };

```

**Comment by davidsh** [comment]
>Hello, here are packets captured by Wireshark packets.zip

Can you provide the binary WireShark captures?  The text files can't be easily parsed.

Can you also provide more information about the application, the server URI that you are connecting to and the client certificate you're using?  There still isn't enough information in this issue to figure out the problem.

**Comment by kchanlee** [comment]
@davidsh I may not upload my client certificate in the public space. May I send it to you by email? Or is there any other private way to send my certificate?

**Comment by davidsh** [comment]
> I may not upload my client certificate in the public space.

Just looking at the client certificate won't be enough.  We really need a full repro to figure this out.  The exception you're getting is simply a generic TLS/SSL handshake failure.  So, the question is why does it fail?

Looking at the client certificate could help at least determine if the certificate has the proper X509v3 fields set.

>And I find something more interesting. I add the following .Net Core code, then add a break point inside the callback and start debugging, it works. But if I debug without this break point or run without debugging, it doesn't work.

This is interesting behavior.  Adding a debugger should not affect anything.

Can you post more information about the application?  Or create a smaller repro that shows the problem?  Right now, there is not enough information to diagnose this.

**Comment by kchanlee** [comment]
@davidsh What do you mean by "a smaller repro"? The reproduce steps? Or a smaller code repository that can reproduce the issue?

The latter is already in my first post: https://github.com/kchanlee/HttpMessageHandlerIssue

I will provide more details (binary WireShare capture, client certificate) later.

**Comment by kchanlee** [comment]
@davidsh I have sent you the Wireshark binary captures and my client certificate by email. Given that the server is inside the Azure private VNet, you have no access to it. I will try to ask our ops team to expose it to the public so that you can do trouble-shooting from your computer. Please let me know if you need more information from me.

**Comment by kchanlee** [comment]
@davidsh update: the server (in my GitHub code) is now exposed to public.

**Comment by davidsh** [comment]
I took a look at the WireShark traces you sent offline.  I used the filters for IP addresses you mentioned in the README file.  I don't understand, though, why the "TLS Client Hello" is missing from those traces.

Did you take the trace from the client or the server machine?  Either way, why is the TLS Client Hello missing.  I do see the TLS Server Hello in the trace.

The only difference between the working and not-working traces is that the non-working ones appear to have a TLS alert sent from the server (10.21.9.10) back to the client after the final key exchange.  The TLS alert is encrypted so I can't tell what is going on.

You opened this bug with the title about "Client auth not working".  But do you think the problem is why client certificates specifically?  Have you been able to set up the server to not require client certificates and see if the TLS/SSL handshake works?  I don't think this problem is related to certificates at all.  I think there is some problem with TLS cipher suites or other TLS handshake criteria.

We might need to take advanced SCHANNEL traces and send those to another team for analysis.

**Comment by kchanlee** [comment]
@davidsh I took the trace from the client only. Some packets from client to server seemed missing.

 I just sent you the new packets (packets-20171109.zip) by email.

> Have you been able to set up the server to not require client certificates and see if the TLS/SSL handshake works?
I just had a try and it worked. The captures are in the email attachment.

By the way, the two APIs are exposed to the public now. You can clone the code and have some tests from you computer.

**Comment by softwaretecture** [comment]
I would try making sure both the client and server code use the same TLS cipher like:
 ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

**Comment by kchanlee** [comment]
>I would try making sure both the client and server code use the same TLS cipher like:
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

@softwaretecture Actually I had tried `handler.SslProtocols = SslProtocols.Default`, `None`, `Ssl2`, `Ssl3`, `Tls`, `Tls11`, `Tls12` one by one, but none of them worked.

**Comment by softwaretecture** [comment]
Also, the quality of a certificate on both the server and the client matters. Normally you should not see issues with certs issued by real CAs. Self-signed, especially those without exportable private key are an issue.

**Comment by softwaretecture** [comment]
I have the same code in my client and it works as expected in .NET 4.X as well as .NET Core 1-2 with proper certs.
What's the server code doing?

**Comment by davidsh** [comment]
FYI:
>ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

ServicePointManager is not used on .NET Core.  Setting the .SecurityProtocol field doesn't do anything.

If you need to control TLS/SSL protocols, you use the HttpClientHandler.SslProtocols property.

>Normally you should not see issues with certs issued by real CAs. Self-signed, especially those without exportable private key are an issue.

I looked at the private key and it seems ok in terms of having the right X509v3 fields, etc.

We will need to take advanced SCHANNEL/NCRYPT tracing logs in order to troubleshoot this problem.

**Comment by softwaretecture** [comment]
Sorry, that's what I meant. ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12; for .NET 4.X and HttpClientHandler.SslProtocols for Core.

also, here's the server code that works for us:

```
.UseKestrel(options =>
                {
                    options.Listen(IPAddress.Any, 443, listenOptions =>
                    {
                        var httpsOptions = new HttpsConnectionAdapterOptions();
                        httpsOptions.ClientCertificateMode = ClientCertificateMode.RequireCertificate;
                        httpsOptions.CheckCertificateRevocation = false;
                        httpsOptions.SslProtocols = SslProtocols.Tls12;
                        //configure a handler to verify client certificate for each request
                        //                        httpsOptions.ClientCertificateValidation +=>(a,b, c){ };
                        httpsOptions.ClientCertificateValidation +=
                            (clientCertificate, chain, errors) =>
                            {
                                Console.WriteLine("Received client certificate");
                                Console.WriteLine(clientCertificate.Thumbprint);
                                return true;
                            };

                        var cert= [LoadCertHere]
                        httpsOptions.ServerCertificate = cert;
                        listenOptions.UseHttps(httpsOptions);
                    });
                })


```

**Comment by kchanlee** [comment]
@softwaretecture Thanks for your sample server code, but my target server is Barracuda Web Application Firewall...

@davidsh I found HttpGet with client certificate authentication works well in the same situation.

**Comment by davidsh** [comment]
>@davidsh I found HttpGet with client certificate authentication works well in the same situation.

I don't understand this comment.  What is "HttpGet"? Is that a different program?  Or are you talking about doing an HTTP request with the "GET" verb/method?  Was that request using client cert auth as well or not?

**Comment by davidsh** [comment]
I have reproduced the failure with client cert negotiation.

The WinHttpException you're getting is due to WinHttpHandler returning error  ERROR_WINHTTP_SECURE_FAILURE (12175).  That is translated from an SCHANNEL error SEC_E_ILLEGAL_MESSAGE (0x80090326).

The error is happening when the server does TLS renegotiation and then requests the client certificate.  A TLS alert is being sent back from the server.

We are consulting with SCHANNEL experts to diagnose further.

**Comment by kchanlee** [comment]
>>@davidsh I found HttpGet with client certificate authentication works well in the same situation.

>I don't understand this comment. What is "HttpGet"? Is that a different program? Or are you talking about doing an HTTP request with the "GET" verb/method? Was that request using client cert auth as well or not?

I meant I tried an HTTPS request with "GET" verb/method. "in the same situation" meant (1) to the same URL, (2) the server is asking for the same client certificate for authentication, (3) my .Net Core code is similar and sends the same client certificate

**Comment by davidsh** [comment]
From: Kris (Kequan) Li 
Sent: Tuesday, November 14, 2017 2:51 AM

Hi David,

Barracuda confirmed that this is a bug in their product and they will provide a patch to fix it. I will keep you updated once the patch is applied or when we get more details from Barracuda.

Thanks,
Kris
