### ISSUE TITLE
Run tests on non-en-US culture

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#25082]
Right now our CI and official runs all use en-US. When contributors run tests locally on a machine with different culture settings, they sometimes get failures - which we fix, but it would be nice to prevent this upstream especially as sometimes they are product bugs.

**Comment by danmosemsft** [comment]
This hole came up when discussing Xamarin testing overlap, in the context of having the same behavior on specific cultures. Our tests generally don't verify what culture specific behavior is, but just that culture specific behavior occurs. We rely on the OS/ICU to determine this behavior. Xamarin has a hybrid approach.

**Comment by svick** [comment]
@ViktorHofer Based on https://github.com/dotnet/corefx/issues/28729 and https://github.com/dotnet/corefx/pull/28855, I think that's true.
