### ISSUE TITLE
Release pinned buffers at correct time in WinHttpResponseStream, WinHttpWebSocket

### ISSUE THREAD

**Issue by pgavlin** [dotnet/corefx#2508]
This is a potential bug: pinned buffers must not be released until it is guaranteed that no further operations will be made that use those buffers.

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar

**Comment by CIPop** [comment]
@pgavlin Can you add more details on this please?

**Comment by pgavlin** [comment]
See e.g. https://github.com/dotnet/corefx/blob/383db8b8a8b5a83e540d7fcb952e0e9b4f2da6c4/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpResponseStream.cs

It looks like we may be releasing some pinned buffers early (i.e. before we can be sure that native code will no longer attempt to access them).

**Comment by CIPop** [comment]
Thanks! (Probably searched for the wrong bug number yesterday.)

https://github.com/dotnet/corefx/search?utf8=✓&q=2508
https://github.com/dotnet/corefx/blob/383db8b8a8b5a83e540d7fcb952e0e9b4f2da6c4/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/WinHttpWebSocket.cs#L721

**Comment by SidharthNabar** [comment]
Moving to future since this needs non-trivial redesign and may add risk

**Comment by davidsh** [comment]
We need to fix this in order to fix #6142.

**Comment by ericeil** [comment]
There is still a TODO comment referencing this issue, in WinHttpRequestStream.cs.  It does not appear to have been addressed by #6500.  Reopening this issue.

**Comment by karelz** [comment]
Next step: We need to confirm if this is still a problem. Or if we need to just adjust the comment.

**Comment by davidsh** [comment]
This has been obsoleted since we no longer use WinHTTP for System.Net.WebSockets.Client and use SocketsHttpHandler for HTTP stack.
