### ISSUE TITLE
Share .NET Standard test bed

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#25084]
We already have good tools to ensure that .NET Standard implementations fulfil the .NET Standard API surface area. We should now also share tests in order to minimize functional differences. In CoreFX we have a attempted to separate out tests for .NET Standard. In discussion with @marek-safar and @luhenry of Xamarin it likely makes sense to make this test bed reuseable so we can run it against Xamarin as well.

We expect this to also help us drive standardization/documentation of the behavior of .NET Standard API's, where it's not already clear. We’d like to establish principles (with examples) for which behavior we’d like to prescribe. There is inherent tension between making .NET behavior consistent across all platforms and making .NET behavior self-consistent on a given platform. Sharing tests will help map this out, and prevent divergence.

Longer term we may want to run Mono tests against .NET Core, and run .NET Core (ie., full netcoreapp) tests against Mono where appropriate: these may have value but are not in scope of this epic.

@marek-safar @luhenry @terrajobst

**Comment by ViktorHofer** [comment]
Closing as we decided to go into a different direction with Mono and CoreClr. We will focus on .NET Core.
