### ISSUE TITLE
ARM/Linux: NetworkChange.NetworkAddressChanged crashes

### ISSUE THREAD

**Issue by Const-me** [dotnet/corefx#25081]
Here's a program:
```
using System;
using System.Net.NetworkInformation;

class Program
{
	static void Main( string[] args )
	{
		printAll();
		NetworkChange.NetworkAddressChanged += addressChanged;
		Console.ReadLine();
	}

	static void addressChanged( object sender, EventArgs e )
	{
		printAll();
	}

	static void printAll()
	{
		NetworkInterface[] all = NetworkInterface.GetAllNetworkInterfaces();
		foreach( var i in all )
			Console.WriteLine( "{0}, status {1}", i.Description, i.OperationalStatus );
	}
}
```
Here's the output when I unplug Ethernet cable from the device:
```
lo, status Unknown
sit0, status Down
eth0, status Up
wlan0, status Down
lo, status Unknown
sit0, status Down
eth0, status Down
wlan0, status Down

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.NetworkInformation.NetworkChange.OnSocketEvent(NetworkChangeKind kind)
   at System.Net.NetworkInformation.NetworkChange.ProcessEvent(Int32 socket, NetworkChangeKind kind)
   at System.Net.NetworkInformation.NetworkChange.LoopReadSocket(Int32 socket)
   at System.Net.NetworkInformation.NetworkChange.<>c.<CreateSocket>b__17_0(Object s)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__276_1(Object obj)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by Const-me** [comment]
Fortunately, the workaround was relatively simple. Basically, I’ve copy-pasted what’s in src\Native\Unix\System.Native\pal_networkchange.cpp into my own C++ shared library, applying minor fixes for better API (e.g. there’s no need to native calls each loop iteration, the complete loop is fine running in C++, the task occupies the whole thread anyway). Don’t forget TaskCreationOptions.LongRunning when starting that loop.

This gave me the notifications I need without the buggy portion of .NET framework.

I’m still using NetworkInterface.GetAllNetworkInterfaces to list interfaces after the notification, that part of the framework works OK here.

**Comment by danmosemsft** [comment]
So `GetAllNetworkInterfaces()` is returning one or more null entries? Any chance you could debug it a bit to see where that's coming from? Perhaps we just need to drop any nulls that the OS is giving us.

**Comment by Const-me** [comment]
> So GetAllNetworkInterfaces() is returning one or more null entries?

That's not what's happening here.

There’s no my code anywhere in the exception stack trace. It’s all deep inside .NET framework code.

The way NetworkAddressChanged event is implemented in .NET framework, it creates a socket of type [AF_NETLINK](http://man7.org/linux/man-pages/man7/netlink.7.html), reads it in the endless loop using blocking `recvmsg` API and parses the result. This all happens on the internal thread that I have no control of, the only thing I can do to that thread is stop it by unsubscribing from that event.

It's that internal thread who has crashed, I can't even catch that exception.

The source file for that is src\System.Net.NetworkInformation\src\System\Net\NetworkInformation\NetworkAddressChange.Linux.cs, shich calls native stuff from pal_networkchange.cpp.

**Comment by Const-me** [comment]
I can’t debug .NET on that system, I’ve installed the framework from a binary package.

But based on the source code, I think it’s the s_availabilityTimer field that’s null.

It’s set to non-null when NetworkAvailabilityChanged event is subscribed, and I don’t do that, I’m only subscribing to NetworkAddressChanged. However, OnSocketEvent method calls s_availabilityTimer.Change().

You should probably change line 182 from
`s_availabilityTimer.Change(AvailabilityTimerWindowMilliseconds, -1);`
to
`s_availabilityTimer?.Change(AvailabilityTimerWindowMilliseconds, -1);`

**Comment by stephentoub** [comment]
I think that change is necessary but not sufficient.  The locking here appears to be problematic, in that the changing of the s_availabilityTimer is covered by the s_subscriberLock lock, but then the invocation covered by the s_availabilityLock lock.  If one thread is removing the last delegate from NetworkAvailabilityChanged at the same time as a socket event arrives and we call s_availabilityTimer.Change, we could end up with the cited NullReferenceException if s_availabilityTimer is null, or we could end up with an ObjectDisposedException if it's already been disposed.

I don't know why the code is using two different locks.  Seems like they should just be consolidated down to a single lock, at which point the suggested change of s_availabilityTimer.Change to s_availabilityTimer?.Change should be good.
