### ISSUE TITLE
Webpack failure on dot net core 2 gives wrong message.

### ISSUE THREAD

**Issue by prashantchoudhary** [dotnet/corefx#25099]
DotNet Core 2.0 with Angular 5
If angular is updated to angular 5 and ngtools is not latest, then following error comes during runtime.
Error: Version of @angular/compiler-cli needs to be 2.3.1 or greater. 
Current version is "5.0.0".

Error message is clearly misleading.

**Comment by karelz** [comment]
@prashantchoudhary how is it related to .NET Core? Is it problem of managed code or JS?

**Comment by tarekgh** [comment]
This issue was moved to angular/angular#20485

**Comment by prashantchoudhary** [comment]
yes looks more like an npm issue. I posted in dotnet section as the template was dotnet core with angular and webpack.
