### ISSUE TITLE
Handle SSL-related failures in WinHttpWebSocketCallback.

### ISSUE THREAD

**Issue by pgavlin** [dotnet/corefx#2509]
This code needs to be shared with WinHttpHandler.

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar

**Comment by CIPop** [comment]
This code needs to be shared with WinHttpHandler.

**Comment by davidsh** [comment]
@pgavlin Can you help me to remember what this issue is really about?

**Comment by pgavlin** [comment]
This is in reference to the following `TODO` in WinHttpWebSocketCallback.cs: https://github.com/dotnet/corefx/blob/master/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/WinHttpWebSocketCallback.cs#L186

I don't have any further context; IIRC this issue was created to track that TODO as part of open-sourcing this code.

**Comment by karelz** [comment]
Cost: Medium-large

**Comment by davidsh** [comment]
We no longer use WinHTTP for System.Net.WebSockets.Client.
