### ISSUE TITLE
Add methods for manipulating date and time with respect to a particular time zone

### ISSUE THREAD

**Issue by mj1856** [dotnet/corefx#25110]
There currently is not an easy way to manipulate date and time values with respect to a particular time zone.  For example, the US went through a DST transition recently.  Using methods such as `AddDays` and similar do not reflect that correctly - even on the `DateTimeOffset` versions.

I suggest adding the following:

## Proposed API
```diff
namespace System {
     public struct DateTimeOffset {
+        public static DateTimeOffset AddYears(int years, TimeZoneInfo timeZone)
+        public static DateTimeOffset AddMonths(int months, TimeZoneInfo timeZone)
+        public static DateTimeOffset AddDays(int days, TimeZoneInfo timeZone)
+        public static DateTimeOffset AddHours(double hours, TimeZoneInfo timeZone)
+        public static DateTimeOffset AddMinutes(double minutes, TimeZoneInfo timeZone)
+        public static DateTimeOffset AddSeconds(double seconds, TimeZoneInfo timeZone)
+        public static DateTimeOffset AddMilliseconds(double milliseconds, TimeZoneInfo timeZone)
+        public static DateTimeOffset AddTicks(long ticks, TimeZoneInfo timeZone)
+        public static DateTimeOffset Add(TimeSpan timeSpan, TimeZoneInfo timeZone)
+        public static DateTimeOffset Subtract(TimeSpan timeSpan, TimeZoneInfo timeZone)
     }
     public struct DateTime {
+        public static DateTime AddYears(int years, TimeZoneInfo timeZone)
+        public static DateTime AddMonths(int months, TimeZoneInfo timeZone)
+        public static DateTime AddDays(int days, TimeZoneInfo timeZone)
+        public static DateTime AddHours(double hours, TimeZoneInfo timeZone)
+        public static DateTime AddMinutes(double minutes, TimeZoneInfo timeZone)
+        public static DateTime AddSeconds(double seconds, TimeZoneInfo timeZone)
+        public static DateTime AddMilliseconds(double milliseconds, TimeZoneInfo timeZone)
+        public static DateTime AddTicks(long ticks, TimeZoneInfo timeZone)
+        public static DateTime Add(TimeSpan timeSpan, TimeZoneInfo timeZone)
+        public static DateTime Subtract(TimeSpan timeSpan, TimeZoneInfo timeZone)
     }
}
```

## Example Usage
```csharp
// setup
TimeZoneInfo tz = TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time");
DateTimeOffset dto = DateTimeOffset.Parse("2017-11-05T00:00:00-04:00");

// example of using AddDays in existing API
DateTimeOffset result1 = dto.AddDays(1);        // 2017-11-06T00:00:00-04:00

// example of using AddDays with respect to time zone in proposed API
DateTimeOffset result2 = dto.AddDays(1, tz);    // 2017-11-06T00:00:00-05:00

// example of using AddHours in existing API
DateTimeOffset result3 = dto.AddHours(24);      // 2017-11-06T00:00:00-04:00

// example of using AddHours with respect to time zone in proposed API
DateTimeOffset result4 = dto.AddHours(24, tz);  // 2017-11-05T23:00:00-05:00
```

Note that in this context, `AddDays` is intended to manipulate a calendar day, not an elapsed 24-hour duration.  Thus its argument is an `int` rather than a `double`.  `AddMonths` and `AddYears` already behave similarly.

Also, if #24555 goes through, then we'd also need `AddMicroseconds` versions of the above.

For discussion: We could also include overloads that allow the user to supply a delegate to control how ambiguous results are handled, and how invalid or ambiguous `DateTime` inputs are resolved.  Or we could default that behavior to existing behaviors present in the framework already, or to something more sensible for these scenarios.

**Comment by danmosemsft** [comment]
I don't know much about DateTimeOffset etc so I'll leave informed comment to others. Notwithstanding that I"m having trouble understanding what it means to add an hour with respect to a timezone. As I understand it DateTimeOffset stores a DateTime plus an offset. What does it mean in real terms to add an hour to that passing a different offset (in the form of a time zone)? Is it modifying the offset as well as the UTC time?

**Comment by Clockwork-Muse** [comment]
....at this point, would it be better to propose a `DateTimeZoned` type?

>For discussion: We could also include overloads that allow the user to supply a delegate to control how ambiguous results are handled, and how invalid or ambiguous `DateTime` inputs are resolved. Or we could default that behavior to existing behaviors present in the framework already, or to something more sensible for these scenarios.

How would you get ambiguous results?  Granted, `DateTime` doesn't have an offset, but isn't there an internal flag that says "is in DST"?

**Comment by Clockwork-Muse** [comment]
@danmosemsft -
Presumably passing in an invalid offset (one that would not be in effect at the given time in that timezone) would be an exception.
In general, adding an hour with a timezone would update the offset, though, yes (which is why my question about a `DateTimeZoned`).  The current problem is that it's difficult to do date/time math with the current API, taking the zone into account.

**Comment by mj1856** [comment]
@danmosemsft - Say, for example, that you were in Seattle last weekend, on Sunday November 5th at 1:30 AM in Pacific Daylight Time (UTC-7).  Adding an hour *should* result in 1:30 AM Pacific Standard Time (UTC-8).  In our current API, we have awareness of offset, but not time zone.  So, you end up at 2:30 AM UTC-7, which isn't valid in Pacific time on that date.

**Comment by mj1856** [comment]
@Clockwork-Muse - We've talked about a type like that before, and decided it opens more problems than it's worth.  For example, such a type can't implement `IComparable` consistently across all operations.  (Noda Time's `ZonedDateTime` type has this problem.)

One can get ambiguous results by adding a year, month, or day.  For example, does `2017-11-04T01:00:00-07:00` + 1 day with respect to US Pacific time end up at `2017-11-05T01:00:00-07:00` or `2017-11-05T01:00:00-08:00`?   Other existing .net methods have historically chosen Standard time (the second result), but IMHO that is a mistake and the more sensible default is Daylight time (the first result) because time moves in a forward direction.  This comes up in scheduling daily tasks, for example.

**Comment by mj1856** [comment]
> Granted, `DateTime` doesn't have an offset, but isn't there an internal flag that says "is in DST"?
... only for `DateTimeKind.Local`, and only with respect to the local time zone.  It doesn't help here.

**Comment by mj1856** [comment]
> Presumably passing in an invalid offset (one that would not be in effect at the given time in that timezone) would be an exception.

That's up for discussion.  I think it would be equally valid to accept it and normalize it to the time zone given. Since it's a `DateTimeOffset`, it's unambiguous as to what point in time is being given.

**Comment by joperezr** [comment]
cc: @tarekgh

**Comment by tarekgh** [comment]
Personally, I don't think bloat DateTime/DateTimeOffset with TZ functionality is a good idea. I would prefer we introduce a new type (something like ZonedDateTime) which can encapsulate the needed functionality and target this functionality. 

@mj1856 what you think to create a new proposal for ZonedDateTime?

**Comment by mj1856** [comment]
So, based on outcome from #25089 discussion, I think this API proposal also needs modification to move to the `TimeZoneInfo` class.  However, I'm not sure that the current names would make sense in that context.  Any suggestions?

```csharp
TimeZoneInfo tz = TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time");
DateTimeOffset result = tz.AddDays(dto, 1);  // this is functional, but feels weird
```

@tarekgh?

**Comment by tarekgh** [comment]
@mj1856 how strongly you feel about these APIs as needed now? I am asking because we can think more if we can expose this to another new type (I understand you don't like ZonedDateTime), We just need to think about that more and look how this will fit with the future plans (as you know we have some more work to do with time zones in general).

**Comment by mj1856** [comment]
I do think they are needed.  Perhaps the naming strangeness here does reflect the need for a `ZonedDateTime` type.  Let's discuss offline.

**Comment by mj1856** [comment]
After meeting with @tarekgh, we've decided to close this for now.  We will discuss this scenario as part of a larger effort, which may or may not involve a ZonedDateTime type.
