### ISSUE TITLE
System.Threading.Channels is not compatible with .NETStandard 1.3

### ISSUE THREAD

**Issue by aka-STInG** [dotnet/corefx#25121]
I was using [System.Threading.Tasks.Channels](https://www.nuget.org/packages/System.Threading.Tasks.Channels/) package for project with .NETStandard 1.3 target and was very excited it is on its way to become stable (by moving from corefxlab to corefx repo).
But today I got frustrated that it suddenly dropped support for .NETStandard 1.3 and min possible target is set to .NETStandard 2.0
`Package System.Threading.Channels 4.5.0-preview1-25907-04 is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Package System.Threading.Channels 4.5.0-preview1-25907-04 supports: netstandard2.0 (.NETStandard,Version=v2.0)
`
If there is no reason please support lowest possible version of .net standard.

**Comment by danmosemsft** [comment]
@stephentoub

**Comment by stephentoub** [comment]
> If there is no reason please support lowest possible version of .net standard.

The main reason was difficulties in the initial port in getting the packaging right in corefx, but that should be fixable.

**Comment by danmosemsft** [comment]
@joshfree would you like someone on my team to have a quick look in case this is easy?

**Comment by joshfree** [comment]
@danmosemsft yes, if you wouldn't mind;

/cc @ahsonkhan @KrzysztofCwalina as FYI

**Comment by danmosemsft** [comment]
I put up a PR.

**Comment by joshfree** [comment]
Closing issue per discussion in PR.
