### ISSUE TITLE
Make SignedXml.XmlDsigRSASHA256Url etc. public

### ISSUE THREAD

**Issue by AndersAbel** [dotnet/corefx#25123]
In the full framework the constants for the algorithm names (`XmlDsigRSASHA256Url` et. al) are public: http://referencesource.microsoft.com/#System.Security/system/security/cryptography/xml/signedxml.cs,83

In .NET Core they are `internal`: https://github.com/dotnet/corefx/blob/7b7da40c0b509fd902814529cbbd840da7698017/src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/SignedXml.cs#L71

 Is there any specific reason to why? If they are available to use the constants should be public.

**Comment by bartonjs** [comment]
The API got locked to netstandard20 equivalence, which was the .NET Framework version before they were made public.

**Comment by bartonjs** [comment]
Fixed by https://github.com/dotnet/corefx/pull/30911
