### ISSUE TITLE
Introducing Xml Serializer Generator for .NET Core 

### ISSUE THREAD

**Issue by huanwu** [dotnet/corefx#25138]
# Introducing Xml Serializer Generator for .NET Core
Like the Xml Serializer Generator (sgen.exe) on desktop, Microsoft.XmlSerializer.Generator NuGet package is the solution for .NET Core and .NET Standard Libraries. It creates an Xml serialization assembly for types contained in an assembly in order to improve the startup performance of Xml serialization when serializing or de-serializing objects of those types using XmlSerializer. 

You can start using the tool today by following the [instructions](https://github.com/dotnet/core/blob/master/samples/xmlserializergenerator-instructions.md). 

## Details
When the Xml Serializer Generator is not used, an XmlSerializer generates serialization code for each type every time when an application runs. You can improve the startup performance of Xml serialization by simply adding the reference of Microsoft.XmlSerializer.Generator NuGet package to your project. Xml Serializer Generator will generate the serialization code and compile it into an assembly next to your output assembly at build time in advance. This assembly can then be deployed and ran with your application. 

Please create an issue with your feedback at [dotnet/corefx](https://github.com/dotnet/corefx/issues). We are actively looking to improve the tool and your input is a valuable part of the process.

**Comment by jherbert** [comment]
First off, thanks for porting this over. It's really going to help start up time for those of us with huge number of serialized objects. The simplicity of having this within the normal dotnet build is fantastic.

I've successfully got gotten a `*.XmlSerializers.dll` in a hello world type scenario. However when doing a more complex project with `System.ServiceModel.*` dependencies I'm getting this back from the generator.

```
1>  [Microsoft (R) .NET Core Xml Serialization Generation Utility, Version 1.0.0-preview1]
1>  Copyright (C) Microsoft Corporation. All rights reserved.
1>  Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
1>  Could not load the specified file.
```

Why would it be looking for `System.ServiceModel.Primitives Version 4.1.1.0`? 

This is what my *.csproj looks like

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <RuntimeFrameworkVersion>2.0.4-servicing-25831-01</RuntimeFrameworkVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.XmlSerializer.Generator" Version="1.0.0-preview1-25906-03" />
    <PackageReference Include="System.ServiceModel.Duplex" Version="4.4.0" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.4.0" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.4.0" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.XmlSerializer.Generator" Version="1.0.0-preview1-25906-03" />
  </ItemGroup>

</Project>
```

**Comment by shmao** [comment]
@jherbert Thanks for trying out the tool. I guessed that some types indirectly reference types in System.ServiceModel.Primitives (btw version 4.2.0.0 ships with package 4.4.0). Does any of your types have dependency on any types in the 4 packages you listed above? If so, would you mind sharing the type definition with me? I can take a look. Thanks!

**Comment by jherbert** [comment]
It's code generated using https://marketplace.visualstudio.com/items?itemName=WCFCORETEAM.VisualStudioWCFConnectedService

Attached is Reference.cs which has all of those types.
[Reference.txt](https://github.com/dotnet/corefx/files/1458726/Reference.txt)

Thanks!

**Comment by shmao** [comment]
I see. Xml Serializer Generator, like the SGen tool on desktop, does not support generating serializers for . `ServiceContract` or `OperationContract` types. It does not know about WCF. The tool that can generate serializers for WCF services is svcutil.

The good news is that we're actively working on svcutil for .Net Core. And it is exactly for the scenario you mentioned above.

**Comment by jherbert** [comment]
Ah okay, thank you for taking a look. I guess I was under the impression that svcutil was just for code generation and not for building the XmlSerializers.

Glad to hear that this scenario is on the road map then. Thanks!

**Comment by sandorfr** [comment]
You should write that it does not support WCF it in that documentation: https://github.com/dotnet/core/blob/master/samples/xmlserializergenerator-instructions.md.

Do you know if there is any ETA on a solution for WCF. this problem is currently very painful as it can currently take more than one second for a request to be serialized.

**Comment by shmao** [comment]
Thanks for the suggestions, @sandorfr . We would consider to change the instructions and add the note.

The tool for WCF requires changes in .Net Core framework library. I expect the tool to be available after next .Net Core release.

> it can currently take more than one second for a request to be serialized.
This might be a performance issue with the serializer. The serializer generator is for improving the start-up performance of the serializers. It doesn't speed up the actual serialization. Would you mind sharing a sample app with us for the performance issue? We can have a look.

**Comment by sandorfr** [comment]
Ok @shmao I'll try to build a repro project I can share with you.

**Comment by huanwu** [comment]
@sandorfr The tool for wcf is available at https://github.com/dotnet/wcf/issues/2927.

**Comment by tbolon** [comment]
Hi. Can someone involved in this tool confirm if the generated assembly is using the deterministic msbuild option ? Or if the compiler/roslyn parameters are exposed ?

We use sgen tool with assemblies which use the deterministic option to prevent the output binary to change when the inputs are identical. See [this page](https://github.com/dotnet/roslyn/blob/master/docs/compilers/Deterministic%20Inputs.md) or [this blog](http://blog.paranoidcoding.com/2016/04/05/deterministic-builds-in-roslyn.html) for details.

The current sgen.exe does not allow to customize the csc.exe parameters. As a suggestion, perhaps this library should expose them ?

**Comment by matsoo** [comment]
Is there a way to use this tool to generate serializers for classes that inherits from a class in a referenced project/library? When running the tool integrated in Visual Studio it just seems to ignore them.

**Comment by huanwu** [comment]
@matsoo, did you reference this referenced project as project reference or package reference? Could you try to use package reference as a workaround and it should work. It seems not work well for project reference and I will take a look.

**Comment by matsoo** [comment]
I was using a project reference. Using a package reference works. Thank you!

**Comment by TranstecJasonD** [comment]
How do you serialize only a single class? I created a .NET 2.0 Standard library project with VS 2017. Added the package and DotNetCliToolReference. When I compile the project, it appears that is attempting to serialize the entire DLL, which fails. When using sgen, I would use the "/t" option.

**Comment by sei-jmattson** [comment]
When I test this using the [instructions](https://github.com/dotnet/core/blob/master/samples/dotnet-svcutil.xmlserializer-instructions.md) on `dotnet-sdk 2.1.402`, I get:
```
Target "GenerateSerializationAssemblies" skipped, due to false condition; ('$(_SGenGenerateSerializationAssembliesConfig)' == 'On' or ('@(WebReferenceUrl)'!='' and '$(_SGenGenerateSerializationAssembliesConfig)' == 'Auto')) was evaluated as ('Off' == 'On' or (''!='' and 'Off' == 'Auto')).
```
How can I turn it 'On'?

**Comment by syedabidali** [comment]
Microsoft.XmlSerializer.Generator v2.0.0 stable not working due to large no.of references.
![image](https://user-images.githubusercontent.com/14038836/51842670-433ebc80-2333-11e9-8a67-cf6a7acd3917.png)
![image](https://user-images.githubusercontent.com/14038836/51842681-49cd3400-2333-11e9-90dc-087d031c51de.png)

**Comment by huanwu** [comment]
@yujayee Can you take a look?

**Comment by yujayee** [comment]
All questions in this thread should already be addressed. If there are any other further questions or issues regarding Xml Serializer Generator, please open an issue in corefx repo directly. It's easier for us to track them that way. Thanks!
