### ISSUE TITLE
SqlException: Cannot access Kerberos ticket. Ensure Kerberos has been initialized with 'kinit'.

### ISSUE THREAD

**Issue by VimalKumarS** [dotnet/corefx#25149]
I am trying to connect to mssql using integrated security credential, dotnet core 2.0 runtime/sdk, running on Macox 10.12.6, dot net core version 2.0.2
tried setting up kinit, i also see klist - list the credential. tried to  set up open ssl.

got following exception, any pointers

`SqlException: Cannot access Kerberos ticket. Ensure Kerberos has been initialized with 'kinit'. ErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An unsupported mechanism was requested (unknown mech-code 0 for mech unknown). at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed) at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags) at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName) at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer) at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)`

-vimal

**Comment by ipinak** [comment]
I have experienced the same issue running on Centos 7.

**Comment by saurabh500** [comment]
I am closing this issue after the follow ups on https://github.com/Microsoft/vscode-mssql/issues/985#issuecomment-345408856
