### ISSUE TITLE
string.Contains should provide a StringComparison parameter

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/corefx#25176]
The `Contains` method of the `String` object currently does not provide any means to perform a case-insensitive string contains operation.

Add a parameter that takes `StringComparison` to the `Contains` method on the `String` object.

## Rationale
The `StartsWith` and `EndsWith` methods provides overloads that accept a `StringComparison` parameter. 

[Developers inquire about this](https://stackoverflow.com/questions/444798/case-insensitive-containsstring).

Possible:
```cs
"foo".StartsWith("foo", StringComparison.InvariantCultureIgnoreCase);
"foo".EndsWith("foo", StringComparison.InvariantCultureIgnoreCase);
```

Not possible:
```cs
"foo".Contains("foo", StringComparison.InvariantCultureIgnoreCase);
```

## Proposed API
```cs
public bool Contains(String value, StringComparison comparisonType);
```

**Comment by stephentoub** [comment]
This already exists:
https://github.com/dotnet/coreclr/pull/12400
https://github.com/dotnet/corefx/issues/20846
