### ISSUE TITLE
HttpClient throws 'The server returned an invalid or unrecognized response' error

### ISSUE THREAD

**Issue by elucidsoft** [dotnet/corefx#25180]
When connecting to an SSE stream and in chunked mode, the HttpClient will throw an 'The server returned an invalid or unrecognized response' error every single time.

To see the issue, try to connect to [This API Call ](https://horizon-testnet.stellar.org/accounts/GAZHWW2NBPDVJ6PEEOZ2X43QV5JUDYS3XN4OWOTBR6WUACTUML2CCJLI/transactions?limit=50)and use the header Accept: text/event-stream, HttpClient will throw an exception every single time. It's easy to reproduce, Fiddler seems to return back the results just fine.

**Comment by stephentoub** [comment]
This code runs fine for me:
```C#
using System;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;

class Program
{
    public static async Task Main()
    {
        using (var http = new HttpClient())
        {
            Console.WriteLine(await http.GetStringAsync(@"https://horizon-testnet.stellar.org/accounts/GAZHWW2NBPDVJ6PEEOZ2X43QV5JUDYS3XN4OWOTBR6WUACTUML2CCJLI/transactions?limit=50"));
        }
    }
}
```
It outputs the json to the console.

Can you share a repro?

**Comment by stephentoub** [comment]
This also runs fine for me:
```C#
using System;
using System.IO;
using System.Net.Http;
using System.Threading.Tasks;

class Program
{
    public static async Task Main()
    {
        var m = new HttpRequestMessage(HttpMethod.Get, @"https://horizon-testnet.stellar.org/accounts/GAZHWW2NBPDVJ6PEEOZ2X43QV5JUDYS3XN4OWOTBR6WUACTUML2CCJLI/transactions?limit=50");
        m.Headers.TryAddWithoutValidation("Accept", "text/event-stream");

        using (var http = new HttpClient())
        using (var resp = await http.SendAsync(m, HttpCompletionOption.ResponseHeadersRead))
        using (var s = new StreamReader(await resp.Content.ReadAsStreamAsync()))
        {
            string line;
            while ((line = await s.ReadLineAsync()) != null)
            {
                Console.WriteLine(line);
            }
        }
    }
}
```
It just waits after outputting all of the data as presumably the server hasn't stopped sending events.

**Comment by elucidsoft** [comment]
Keep it open for at least 3 minutes and you will see it happen...

**Comment by elucidsoft** [comment]
You will notice it fails on	System.Net.Http.dll!System.Net.Http.WinHttpResponseStream.ReadAsyncCore(byte[] buffer, int offset, int count, System.Threading.CancellationToken token)

I have stepped through it but was not able to come to any conclusion.  It's possible its a heartbeat tick being sent by the server that is causing it to fail. I was unable to find a way to see exactly what came over the wire to cause the exception.

**Comment by stephentoub** [comment]
From what I can see, the server is simply closing the connection after a few minutes, and is doing so without sending a terminating chunk, even though it specified Transfer-Encoding: chunked.  As such, the response is invalid, and you're getting the associated exception.  Same thing happens with curl on linux, e.g. this:
```
```
downloads the data, and then fails at the end when the server closes the connection:
```
curl: (18) transfer closed with outstanding read data remaining
```

**Comment by elucidsoft** [comment]
Ok, I will open an issue with the Horizon team and see if they can track it down.  Thanks!

**Comment by stephentoub** [comment]
Thanks.
