### ISSUE TITLE
PowerShell v6.0.0-beta.7 xml save on Linux and MacOS X has an additional [] in DOCTYPE

### ISSUE THREAD

**Issue by jamesloh** [dotnet/corefx#25184]
[xml]$XmlDoc = get-content 'Info.plist'

$XmlDoc.Save('def.plist')

The two lines above work correctly in PowerShell 5.1 on Windows 10 but incorrectly with PowerShell v6 on Linux and MacOSX.

Notice the [] just before the end in DOCTYPE.

<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"[]>

**Comment by karelz** [comment]
Please ask the question on PowerShell repo. If there is underlying problem in .NET Core, please provide a repro without PowerShell for us to look at. Thanks!
