### ISSUE TITLE
Infra: Sync the sources of {ReadOnly}Memory and friends between corefx and corelib

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#25188]
> I'd suggest someone compares the files in the two repos and gets them to be as close as possible. I noticed there are various discrepancies between them that make diff'ing harder, like differences in XML comments, differences in the ordering of members, etc.

Use ifdefs for small differences

From https://github.com/dotnet/coreclr/pull/14906#discussion_r149799699 (for context)

Also figure out and setup a source mirroring strategy between the two repos.

cc @stephentoub, @KrzysztofCwalina, @jkotas, @brianrob, @safern

**Comment by jkotas** [comment]
> Also figure out and setup a source mirroring strategy between the two repos.

We may want to mirror the whole `https://github.com/dotnet/coreclr/tree/master/src/mscorlib/shared` with corefx.

**Comment by ahsonkhan** [comment]
> We may want to mirror the whole `https://github.com/dotnet/coreclr/tree/master/src/mscorlib/shared` with corefx.

cc @ianhays

**Comment by tarekgh** [comment]
@jkotas 

> We may want to mirror the whole https://github.com/dotnet/coreclr/tree/master/src/mscorlib/shared with corefx.

Why do we need to mirror the whole folder? is it ok to have un-used files in corefx? 
Actually, this will be easier in general but I am just wondering if this would be ok. 

Note, we already have a mirroring between corefx and coreclr which doing System.Diagnostics.Tracing folder only.

**Comment by jkotas** [comment]
> Why do we need to mirror the whole folder? 

Simplicity. So that we do not have to manage mirroring of every little piece individually.

> is it ok to have un-used files in corefx?

I think so, as long as it does not have major impact on the repo footprint:

- The CoreFX is 13,000 .cs files, 150 MB today.
- The shared CoreLib partition is 700 files, 6 MB today.

These number means that adding shared CoreLib partition to CoreFX is not going to have increase the repo footprint significantly.

**Comment by jkotas** [comment]
Also, having shared CoreLib partition present in CoreFX would simplify things for Mono. They would not need to depend on CoreRT repo to get the shared CoreLib parts that presents release logistic challenge for them today.

cc @marek-safar

**Comment by tarekgh** [comment]
@jkotas looks reasonable mirroring the whole shared folder. do you think we can store it on the src root? I mean having corefx\src\Shared? or should we add a corelib level, something like  corefx\src\corelib\shared?

cc @weshaggard

**Comment by jkotas** [comment]
My name pick would be `corefx\src\System.Private.CoreLib\shared`. I do not have a strong opinion on it.

**Comment by weshaggard** [comment]
I'm ok with sharing the entire folder. I would put it under `corefx\src\Common\src\System.Private.CoreLib`. We already use the Common folder for sharing between projects so I think that makes the most since.

**Comment by marek-safar** [comment]
It'd certainly help us to simplify synchronization of CoreFX sources for our releases. Right now there is no clear link between CoreFX and CoreRT and we go out of sync with shared files when we update CoreFX sources. This should also allow committing API changes to System.Runtime together with implementation in many cases.

**Comment by safern** [comment]
Mirror is running in between coreclr and corefx, here is the initial PR:

https://github.com/dotnet/corefx/pull/26311

**Comment by safern** [comment]
Just for reference, the PR to start the mirroring is: https://github.com/dotnet/corefx/pull/26314 because we decided to change the folder path in corefx.
