### ISSUE TITLE
Environment.ProcessorCount does not take into account cgroup/Docker limits

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#25193]
This leads to managed code over-dimensioning when running in Docker.

coreclr takes into account docker cpu limits: https://github.com/dotnet/coreclr/blob/dbfd10c94055fb5af823b4a7e30774641afcb3b2/src/classlibnative/bcltype/system.cpp#L349-L350

**Comment by terrajobst** [comment]
@stephentoub @weshaggard

**Comment by tmds** [comment]
@stephentoub @janvorli I'd like to do a PR for this, but I'm not sure how I should call the `PAL_GetCpuLimit` of coreclr in corefx?

**Comment by jkotas** [comment]
I think we should switch `Environment.ProcessorCount` to delegate to the runtime:
- Add ProcessorCount to https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/Internal/Runtime/Augments/EnvironmentAugments.cs and and https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/Internal/Runtime/Augments/EnvironmentAugments.Unix.cs / https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/Internal/Runtime/Augments/EnvironmentAugments.Windows.cs.
- Change the CoreFX implementation to forward ProcessorCount to the runtime.

**Comment by tmds** [comment]
Thanks @jkotas I will take a shot at implementing that.
