### ISSUE TITLE
Interlocked.Read x100 slowdown in some condition

### ISSUE THREAD

**Issue by nshibano** [dotnet/corefx#25213]
Interlocked.Read usually takes ~10 nanoseconds, but in some unconfirmed condition it takes ~1000 nanoseconds.

This is F# code I used to measure Interlocked.Read speed. (Executing this code on your machine will not reproduce the issue. Please read below section.)

```
open System
open System.Diagnostics
open System.Threading
// Opening other proprietary module

[<EntryPoint>]
let main argv =

    // Other proprietary definitions here

    let counter = ref 0L
    while true do
        let sw = Stopwatch.StartNew()
        let n = 1000000
        for i = 1 to n do
            Interlocked.Read(counter) |> ignore
        sw.Stop()
        let t = int (1e9 * float sw.ElapsedTicks / float Stopwatch.Frequency / float n)
        Console.WriteLine(sprintf "%d (ns)" t)
        Console.ReadKey() |> ignore

    // Other proprietary definitions here

    0
```
This is output from process in normal state.
```
9 (ns)
9 (ns)
9 (ns)
9 (ns)
```

This is output from process in erroneous state.
```
762 (ns)
734 (ns)
728 (ns)
```

# Difficulty in reproducing

I couldn't reproduce this issue in small code.  Currently this issue only reproduced in following condition.

- One individual machine (Ryzen 5 1600X CPU, Windows 10)
- Linked with other proprietary codes (I can not share it here. Sorry.)
- Release build
- Without debugger attached
- With some random factor (reproduces with ~70% possibility for process launch)
- Once process enters erroneous state, it continues until process terminates

Even trivial change in code (removing unused code, changing length of unused string constant) makes not able to reproduce this issue. So I suspect this issue is related to low-level things such as memory layout in the process.

**Comment by mikedn** [comment]
Hmm, one possible reason is that `counter` is not properly aligned. Couple of questions:
* 32 bit or 64 bit code? 
* `counter` looks like a local variable but it looks like in F# that ends up stored in a class and thus on the heap. I suppose that the proprietary code does allocate memory too?
* When it gets slow can you attach a debugger to the process and get the assembly code generated for that piece of code?

**Comment by JonHanna** [comment]
Another possibility would be [false sharing](https://en.wikipedia.org/wiki/False_sharing), and if it happens often enough, it might benefit from some padding to force it out of cache lines being used by other cores.

**Comment by nshibano** [comment]
Thank you, @mikedn and @JonHanna.

@mikedn,

- The process is 32 bit since Environment.Is64BitProcess is false. The exe is compiled with "Any CPU" with "Prefer 32 bits" checked.

- Yes. I have looked at IL and creation of mutable variable `counter` was construction of `FSharpRef<T>` class instance. Counter value is in private field of `FSharpRef<T>` class. Therefore it is on the heap.

- I have attached Visual Studio debugger to it but it didn't show assembly code. But it seems that OllyDbg can show assembly. I will gather some data and post it here.

@JonHanna,

I think it's quite possible since 6 core Ryzen is internally 3+3 core.

**Comment by JonHanna** [comment]
If you don't have a lot of such objects, try adding padding to it and see if it fixes it.

**Comment by mikedn** [comment]
> The process is 32 bit since Environment.Is64BitProcess is false. The exe is compiled with "Any CPU" with "Prefer 32 bits" checked.

Right. On 32 bit systems `long` fields are not guaranteed to be 8 byte aligned because objects themselves are only 4 byte aligned. By itself misalignment doesn't usually cause issues on x86. But misaligned values can also straddle cache lines, if that happens... good luck with performance.

False sharing it less likely to cause such a significant slowdown on a single processor system. Well, maybe on Ryzens with their many cores it's possible :). It's also less likely that your code and some other code running in another thread end up hammering exactly the same cache line.

**Comment by stephentoub** [comment]
> Right. On 32 bit systems long fields are not guaranteed to be 8 byte aligned because objects themselves are only 4 byte aligned. By itself misalignment doesn't usually cause issues on x86. But misaligned values can also straddle cache lines, if that happens... good luck with performance.

Yeah.  You can see a similar case where we worked around this in https://github.com/dotnet/corefx/pull/19277.

**Comment by nshibano** [comment]
@JonHanna,

Since I can not modify `FSharpRef<T>` implementation, I think this is the best I can do.

```
    let dummy0 = ref 0L
    let dummy1 = ref 0L
    let dummy2 = ref 0L
    let dummy3 = ref 0L
    let counter = ref 0L
    let dummy4 = ref 0L
    let dummy5 = ref 0L
    let dummy6 = ref 0L
    let dummy7 = ref 0L
```

It didn't change the rate of the process enters erroneous state. I can not say this experiment is perfect though.

**Comment by nshibano** [comment]
@mikedn and all,

This is screen shots of OllyDbg. Left side is in erroneous state, and right side is in normal state. I am not familiar with assembly language so I can not read it. Is there something in this data? Which number is the address of `counter`?
 
![samples](https://user-images.githubusercontent.com/16814225/32737393-44b34fec-c8dd-11e7-99c7-a8f902dcafb2.png)

**Comment by mikedn** [comment]
> This is screen shots of OllyDbg. Left side is in erroneous state, and right side is in normal state. I am not familiar with assembly language so I can not read it. Is there something in this data? Which number is the address of counter?

In your screenshots the address is in register `esi`. It can be seen that in all case the address ends up in C (hexa). So it's a multiple of 4 but not a multiple of 8. The long value is not properly aligned.

**Comment by mikedn** [comment]
For clarity here's a little program that attempts to read at various offsets from a block of memory:
```C#
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Threading;

unsafe class Program
{
    [StructLayout(LayoutKind.Sequential, Size = 128)]
    struct Block128
    {
        public long x;
    }

    static void Main()
    {
        const int n = 1000000;
        var blk = new Block128();
        var sw = Stopwatch.StartNew();

        for (int offset = 0; offset < 120; offset++)
        {
            ref long counter = ref Unsafe.AddByteOffset(ref blk.x, (IntPtr)offset);

            sw.Restart();
            for (int i = 0; i < n; i++)
                Interlocked.Read(ref counter);
            sw.Stop();

            long cacheLineOffset = ((long)Unsafe.AsPointer(ref counter) & 63);

            Console.WriteLine("{0:X04}-{1:X04} {2:G}ns", cacheLineOffset, cacheLineOffset + 7, (sw.Elapsed.TotalMilliseconds * 1000000.0) / n);
        }
    }
}
```
You'll notice the 100x slowdown when the cache line offset is between 0x39 and 0x3F (a cache line has 64 bytes).

**Comment by tannergooding** [comment]
> Right. On 32 bit systems long fields are not guaranteed to be 8 byte aligned because objects themselves are only 4 byte aligned. By itself misalignment doesn't usually cause issues on x86. But misaligned values can also straddle cache lines, if that happens... good luck with performance.

I'm surprised this is the case, I would have expected us to match the native side where `int64` and `float64` are 8-byte aligned by default.

I would think `int64` is a common enough case that the perf drop at every cache line (or worse, every page) boundary would show up and cause issues on 32-bit machines.

**Comment by nshibano** [comment]
@mikedn ,

Thank you again. Your code reproduced the issue. 👏😂

I have run it on two machines, desktop Ryzen and laptop Core i5. It is shown that this issue occurs on both machine.

Result on Ryzen 5 1600X (desktop) machine:

```
0030-0037 7.5064ns
0031-0038 7.8368ns
0032-0039 7.8977ns
0033-003A 7.9332ns
0034-003B 7.4959ns
0035-003C 7.9519ns
0036-003D 7.9332ns
0037-003E 7.9746ns
0038-003F 7.5749ns
0039-0040 806.1358ns
003A-0041 770.3689ns
003B-0042 772.433ns
003C-0043 795.2339ns
003D-0044 808.667ns
003E-0045 780.5986ns
003F-0046 765.6315ns
0000-0007 7.6054ns
0001-0008 7.9359ns
0002-0009 7.8736ns
0003-000A 7.912ns
0004-000B 7.5392ns
0005-000C 7.9271ns
0006-000D 7.8781ns
0007-000E 7.9207ns
0008-000F 7.5504ns
0009-0010 11.8987ns
000A-0011 12.0399ns
000B-0012 11.9849ns
000C-0013 11.188ns
000D-0014 11.9662ns
000E-0015 12.0279ns
000F-0016 12.014ns
0010-0017 7.4676ns
0011-0018 7.9521ns
0012-0019 7.9172ns
0013-001A 7.9103ns
0014-001B 7.4681ns
0015-001C 7.8037ns
0016-001D 7.8776ns
0017-001E 7.9278ns
0018-001F 8.2886ns
0019-0020 12.2509ns
001A-0021 12.2905ns
001B-0022 12.2381ns
001C-0023 11.5148ns
001D-0024 12.3618ns
001E-0025 12.2461ns
001F-0026 12.1662ns
0020-0027 7.5469ns
0021-0028 7.8926ns
0022-0029 7.9477ns
0023-002A 7.9042ns
0024-002B 7.476ns
0025-002C 7.9279ns
0026-002D 7.9216ns
0027-002E 7.8887ns
0028-002F 7.4799ns
0029-0030 12.0103ns
002A-0031 12.0467ns
002B-0032 11.9953ns
002C-0033 11.2422ns
002D-0034 11.9843ns
002E-0035 11.9493ns
002F-0036 12.5999ns
0030-0037 8.3419ns
0031-0038 7.9239ns
0032-0039 7.947ns
0033-003A 7.9353ns
0034-003B 7.4848ns
0035-003C 7.881ns
0036-003D 7.9375ns
0037-003E 7.9053ns
0038-003F 7.5324ns
0039-0040 771.4705ns
003A-0041 764.9124ns
003B-0042 768.3741ns
003C-0043 755.0655ns
003D-0044 764.3959ns
003E-0045 746.3215ns
003F-0046 766.666ns
0000-0007 7.571ns
0001-0008 7.8373ns
0002-0009 7.9494ns
0003-000A 7.9462ns
0004-000B 7.5587ns
0005-000C 7.8767ns
0006-000D 7.8574ns
0007-000E 7.8728ns
0008-000F 7.5079ns
0009-0010 12.0063ns
000A-0011 12.055ns
000B-0012 13.1439ns
000C-0013 11.2589ns
000D-0014 11.9293ns
000E-0015 11.9277ns
000F-0016 12.0793ns
0010-0017 7.5044ns
0011-0018 7.9459ns
0012-0019 7.9466ns
0013-001A 7.865ns
0014-001B 7.5088ns
0015-001C 7.8685ns
0016-001D 7.8792ns
0017-001E 7.9242ns
0018-001F 7.549ns
0019-0020 12.2365ns
001A-0021 12.2155ns
001B-0022 12.3306ns
001C-0023 11.7324ns
001D-0024 12.3692ns
001E-0025 12.2898ns
001F-0026 12.2667ns
0020-0027 7.5126ns
0021-0028 7.9156ns
0022-0029 7.95ns
0023-002A 7.8815ns
0024-002B 7.5115ns
0025-002C 7.9102ns
0026-002D 7.8811ns
0027-002E 7.8856ns
```

Result on Core i5 5200U (laptop) machine:

```
0010-0017 17.5042ns
0011-0018 17.4137ns
0012-0019 15.5924ns
0013-001A 16.5403ns
0014-001B 17.158ns
0015-001C 16.0654ns
0016-001D 15.5284ns
0017-001E 17.2826ns
0018-001F 17.9903ns
0019-0020 15.98ns
001A-0021 16.6644ns
001B-0022 16.9294ns
001C-0023 16.8781ns
001D-0024 15.7533ns
001E-0025 15.6418ns
001F-0026 16.9243ns
0020-0027 16.6229ns
0021-0028 15.4398ns
0022-0029 15.7804ns
0023-002A 16.5548ns
0024-002B 17.6068ns
0025-002C 16.6985ns
0026-002D 17.3446ns
0027-002E 17.5746ns
0028-002F 16.5996ns
0029-0030 15.7542ns
002A-0031 17.9203ns
002B-0032 15.4771ns
002C-0033 17.0839ns
002D-0034 15.4379ns
002E-0035 18.5058ns
002F-0036 15.9954ns
0030-0037 18.0458ns
0031-0038 18.2287ns
0032-0039 18.8259ns
0033-003A 17.6759ns
0034-003B 16.232ns
0035-003C 16.7755ns
0036-003D 18.2073ns
0037-003E 16.6444ns
0038-003F 16.8301ns
0039-0040 1031.9881ns
003A-0041 1006.3536ns
003B-0042 1001.1765ns
003C-0043 989.1461ns
003D-0044 1025.5668ns
003E-0045 1025.8192ns
003F-0046 1000.3326ns
0000-0007 17.8005ns
0001-0008 16.74ns
0002-0009 16.5679ns
0003-000A 17.7482ns
0004-000B 17.1487ns
0005-000C 16.9122ns
0006-000D 15.8858ns
0007-000E 16.9878ns
0008-000F 16.5683ns
0009-0010 15.6955ns
000A-0011 18.0953ns
000B-0012 16.4699ns
000C-0013 16.7078ns
000D-0014 16.0645ns
000E-0015 16.9173ns
000F-0016 17.8387ns
0010-0017 16.7512ns
0011-0018 16.2306ns
0012-0019 15.9521ns
0013-001A 16.134ns
0014-001B 16.9696ns
0015-001C 15.8513ns
0016-001D 16.8361ns
0017-001E 16.6047ns
0018-001F 16.1312ns
0019-0020 15.9978ns
001A-0021 17.0619ns
001B-0022 15.827ns
001C-0023 17.6344ns
001D-0024 16.9462ns
001E-0025 16.4274ns
001F-0026 16.4825ns
0020-0027 16.1363ns
0021-0028 17.2075ns
0022-0029 17.5271ns
0023-002A 17.4879ns
0024-002B 16.252ns
0025-002C 16.1895ns
0026-002D 16.0743ns
0027-002E 15.7636ns
0028-002F 18.3589ns
0029-0030 16.7083ns
002A-0031 16.3729ns
002B-0032 17.6768ns
002C-0033 15.8186ns
002D-0034 17.438ns
002E-0035 18.5273ns
002F-0036 17.5672ns
0030-0037 15.8933ns
0031-0038 15.688ns
0032-0039 17.632ns
0033-003A 16.051ns
0034-003B 15.8695ns
0035-003C 16.1947ns
0036-003D 16.8422ns
0037-003E 16.7923ns
0038-003F 17.4361ns
0039-0040 1024.1215ns
003A-0041 1010.7782ns
003B-0042 1043.1895ns
003C-0043 1019.3745ns
003D-0044 1012.8291ns
003E-0045 1022.03ns
003F-0046 999.7508ns
0000-0007 15.3414ns
0001-0008 15.4267ns
0002-0009 14.4741ns
0003-000A 16.1867ns
0004-000B 14.6388ns
0005-000C 14.712ns
0006-000D 14.44ns
0007-000E 14.4946ns
```

**Comment by nshibano** [comment]
@stephentoub,

Thanks, the root cause seems same.

**Comment by nshibano** [comment]
So, now I'm clear about why this happens. I think this is something by design and it should be avoided to use Interlocked.Read(long) in 32 bit process if possible.

All, thank you for your help.

**Comment by Clockwork-Muse** [comment]
@nshibano - Um, in a 32-bit process (or, [on a 32-bit machine, at least](https://msdn.microsoft.com/en-us/library/system.threading.interlocked.read(v=vs.110).aspx)) was where that particular method was **designed** to run.  If you're on a 64-bit machine you don't need the method at all (going to naively assume it no-ops).

You only need it if you have multiple threads writing and reading at the same time, though, which is quite probably **less** of an issue in F#, given that language's focus on immutability.  You might not need it if you architect your program correctly.

**Comment by mikedn** [comment]
> If you're on a 64-bit machine you don't need the method at all (going to naively assume it no-ops).

To be clear - the method is not a no-op on 64 bit. A `lock cmpxchg` instruction is still generated and the performance will be just as bad if the long value somehow ends up unaligned. The MSDN documentation claims that the method's only feature is atomicity but the implementation also has load acquire/store release semantics that the documentation conveniently fails to mention.

The difference is that on 64 bit you should not run into alignment issues unless you do something weird (like I did in the example for example).
