### ISSUE TITLE
How to integrate CoreFX Binaries manually in a Linux System 

### ISSUE THREAD

**Issue by philippweidhas** [dotnet/corefx#25212]
Hallo .Net Core Community,

im looking for a way to integrate my selfbuild Binaries of coreclr and corefx in an UbuntuSystem. I build the binaries for x86 to get .Net Core running on a x86 Ubuntu System. Now i need a guide where and how to place the binaries in this UbuntuSystem. Can someone give me a instruction or a link to an guide wich i was not able to find.

Greetings
Philipp

**Comment by karelz** [comment]
Check out these instructions: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md#more-advanced-scenario---using-your-local-corefx-build
