### ISSUE TITLE
Change OwnedMemory Pin to take an optional integer offset

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#25229]
Related to https://github.com/dotnet/corefx/issues/24317 and https://github.com/dotnet/corefx/pull/24323#discussion_r141769638

> the scenario is I use OwnedMemory and MemoryHandle directly, without using Memory, e.g. I implement my own Memory-like factory for spans. If we don't like AddOffset, we should add OwnedMemory.Pin overload that takes offset to the added to the pointer inside the handle.

## API Proposal
Change:
```C#
namespace System.Buffers
{
    public abstract class OwnedMemory<T> : IDisposable, IRetainable 
    {
        public abstract MemoryHandle Pin();
    }
}
```

To:
```C#
namespace System.Buffers
{
    public abstract class OwnedMemory<T> : IDisposable, IRetainable 
    {
        public abstract MemoryHandle Pin(int offset = 0);
    }
}
```

## Usage
**Example** from [NativeOwnedMemory](https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Buffers/NativeOwnedMemory.cs#L56):
```C#
public override unsafe MemoryHandle Pin() => new MemoryHandle(this, (void*)_ptr);
```
Would become:
```C#
public override unsafe MemoryHandle Pin(int offset = 0) 
{
   void* pointer = (void*)((byte*)_ptr + offset);
   return new MemoryHandle(this, pointer);
}
```

The following can then be re-written from [Memory.Retain](https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/Memory.cs#L193-L197):
```C#
if (_index < 0)
{
    memoryHandle = ((OwnedMemory<T>)_arrayOrOwnedMemory).Pin();
    memoryHandle.AddOffset((_index & RemoveOwnedFlagBitMask) * Unsafe.SizeOf<T>());
}
```
To:
```C#
if (_index < 0)
{
    memoryHandle = ((OwnedMemory<T>)_arrayOrOwnedMemory).Pin((_index & RemoveOwnedFlagBitMask) * Unsafe.SizeOf<T>());
}
```

We can then remove the internal AddOffset method [here](https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/Buffers/MemoryHandle.cs#L48-L58) which was added in https://github.com/dotnet/corefx/pull/24323.

cc @KrzysztofCwalina, @stephentoub, @karelz, @terrajobst, @pakrym

**Comment by pakrym** [comment]
`AddOffset ` can be removed without adding anything, see https://github.com/dotnet/corefx/pull/24323#discussion_r141769011 second point.

**Comment by ahsonkhan** [comment]
How would that work? Wouldn't we need to add getters to the private fields of MemoryHandle (for example, for `GCHandle _handle`?
```C#
memoryHandle = ((OwnedMemory<T>)_arrayOrOwnedMemory).Pin();
void* pointer = (void*)((byte*)memoryHandle.Pointer + ((_index & RemoveOwnedFlagBitMask) * Unsafe.SizeOf<T>()));
memoryHandle = new MemoryHandle((OwnedMemory<T>)_arrayOrOwnedMemory, pointer); // what about GCHandle?
```

**Comment by stephentoub** [comment]
> The following can then be re-written from Memory.Retain:

Is that the only benefit?

> How would that work? Wouldn't we need to add getters to the private fields of MemoryHandle (for example, for GCHandle _handle?

Your example is in the same assembly.  We could add internal getters, we could make the fields internal, etc., or simply keep the internal AddOffset we have today.

What's the key scenario for exposing this functionality?

**Comment by KrzysztofCwalina** [comment]
The key scenario is using OwnedMemory directly without using Memory<T>/RreadOnlyMemory<T>. Memory<T> and friends are factories of spans. They are very general purpose, e.g. they handle arrays, native pointers, and now strings. Quite often (when using OwnedMemory internally), it's more efficient to create a custom span factory to avoid the overhead associated with the general purpose Memory<T>. But without the Pin(int) APIs, it's not possible for the factory to be slicable (as explained in @ahsonkhan's comment).

**Comment by karelz** [comment]
FYI: The API review discussion was recorded - see https://youtu.be/BI3iXFT8H7E?t=3747 (2 min duration)

**Comment by ahsonkhan** [comment]
Reverted here - https://github.com/dotnet/coreclr/pull/15516

Re-opening.

**Comment by ahsonkhan** [comment]
The change from the previous PR (https://github.com/dotnet/coreclr/pull/15410) was reverted here (https://github.com/dotnet/coreclr/pull/15516) to unblock CoreCLR ingestion into CoreFX - this change was causing CoreFX socket tests to fail.

See trail of build update failures:
https://github.com/dotnet/corefx/pull/25787
https://github.com/dotnet/corefx/pull/25821
https://github.com/dotnet/corefx/pull/25872

**It requires further investigation to why that is happening to resolve it.**

Resolves: https://github.com/dotnet/corefx/issues/25229

Related to https://github.com/dotnet/corefx/pull/25770

FYI @KrzysztofCwalina, @jkotas, @stephentoub, @davidfowl, @pakrym

**Comment by ahsonkhan** [comment]
The change from the previous PR (https://github.com/dotnet/coreclr/pull/15410) was reverted here (https://github.com/dotnet/coreclr/pull/15516) to unblock CoreCLR ingestion into CoreFX - this change was causing CoreFX socket tests to fail.

See trail of build update failures:
https://github.com/dotnet/corefx/pull/25787
https://github.com/dotnet/corefx/pull/25821
https://github.com/dotnet/corefx/pull/25872

**It requires further investigation to why that is happening to resolve it.**

Related to https://github.com/dotnet/corefx/pull/25770

FYI @KrzysztofCwalina, @jkotas, @stephentoub, @davidfowl, @pakrym

**Comment by AtsushiKan** [comment]
Since this appears to a byte offset, despite OwnedMemory<> having a type parameter for the element, shouldn't the argument be named "byteOffset"? Right now, I have to play a guessing game to figure out what's intended...

**Comment by ahsonkhan** [comment]
> Since this appears to a byte offset, despite OwnedMemory<> having a type parameter for the element, shouldn't the argument be named "byteOffset"?

I am fine with this change.
