### ISSUE TITLE
HttpClient possibly causing "Unresolved P/Invoke" crash

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#25224]
Case Link:
https://social.msdn.microsoft.com/Forums/windowsapps/en-US/15f89674-8c49-43d5-920b-d0997bb607f5/rs31709systemnethttphttpclient-possibly-causing-unresolved-pinvoke-crash?forum=wpdevelop

Issue Descrption:
Many customers in our MSDN forum report that when running app from the Windows Store, any HTTP requests made with the System.Net.Http.HttpClient class causes an exception: "Unresolved P/Invoke method 'kernel32.dll!LocalAlloc' from this method. But it works fine in the debug and release mode, it only happens when running the app from the store.

Repro Environment:
Windows 10 (16299.19)
App Target and Minimum SDK: 16299.15
.NETCore UWP: 6.0.1
Visual Studio: 15.4.2

Ref: Internal Microsoft WDG Bug 14634810

**Comment by DavidGoll** [comment]
This affecting multiple libraries. There is an update that needs to be made in the store so that the submitted app is compiled with the latest Windows API’s (requires a coordinated update of the .NET Native toolchain and Store pipeline).
New ref: Internal Microsoft WDG Bug 14647032.

**Comment by davidsh** [comment]
The issue is now resolved and fixes have been made to the Windows Store app submission infrastructure.

Anyone who might be impacted just needs to resubmit their app to the Windows Store without making any changes.
