### ISSUE TITLE
Generic Range type

### ISSUE THREAD

**Issue by YohDeadfall** [dotnet/corefx#25220]
Currently there is the non-generic `Range` type in the corefxlab repository ([link](https://github.com/dotnet/corefxlab/blob/2711e0824729fb318eb4e25544236bb2f53fa33e/src/System.Buffers.Experimental/System/Range.cs#L5-L20)) which is designed for a new C# slice syntax. As you can see, it's limited only to `int` values.

```csharp
public readonly struct Range
{
   public readonly long Index;
   public readonly long Length;
}

public readonly ref struct Span<T>
{
    public Span<T> Slice(Range range) => Slice(range.Index, range.Length);
    public Span<T> Slice(int index, int length) { throw null; }
}
```
```csharp
var buffer = new Span<int>();
var slice1 = buffer[3..4]; // with syntax sugar
var slice2 = buffer.Slice(new Range(3, 4 - 3)); // without it
```
So it would be nice to have a generic one instead it to represent ranges of different types.

## Rationale and Usage

Implementing the generic version would allow to have a common type to represent ranges. There are too many areas where it could be used including numeric processing, range based operations, and simply to store intervals (for example `Range<Time> OpenHours`).

## Proposed API

```csharp
[Serializable]
public readonly struct Range<T> : IEquatable<Range<T>>, IFormattable, ISerializable
    where T : IComparable<T>
{
    public readonly T From;
    public readonly T To;

    public Range(T from, T to) { throw null; }
    private Range(SerializationInfo info, StreamingContext context) { throw null; }

    public void Deconstruct(out T from, out T to) { throw null; }

    public override bool Equals(object obj) { throw null; }
    public bool Equals(Range<T> other) { throw null; }
    public override int GetHashCode() { throw null; }

    public override string ToString() { throw null; }
    public override string ToString(string forma) { throw null; }
    public override string ToString(string format, IFormatProvider formatProvider) { throw null; }

    void ISerializable.GetObjectData(SerializationInfo info, StreamingContext context) { throw null; }
}

public static class Range
{
    // all methods should be aggressively inlined
    public static bool IsNormalized<T>(this Range<T> range) where T : IComparable<T> { throw null; }
    public static Range<T> Normalize<T>(this Range<T> range) where T : IComparable<T> { throw null; }

    public static bool IsEmpty<T>(this Range<T> range) where T : IComparable<T> { throw null; }
    public static bool Contains<T>(this Range<T> range, T value) where T : IComparable<T> { throw null; }
    public static bool Intersects(this Range<T> range, Range<T> other) where T : IComparable<T> { throw null; }
    public static Range<T> Intersect(this Range<T> range, Range<T> other) where T : IComparable<T> { throw null; }

    // Specialized versions of the previous methods for numeric and time types
    public static bool IsNormalized(this Range<int> range) { throw null; }

    // Only for numeric and time types
    public static int Length(this Range<int> range) { throw null; }
}
```

## Details

There is no `struct` constraint to support `string` because it's a good candidate for range based operations, but there are methods which accept `IComparable<T>` as the second parameter should exist to do culture specific actions.

```csharp
var range = new Range<string>("A", "a");
var emptyCS = range.IsEmpty(StringComparer.InvariantCulture); // false
var emptyCI = range.IsEmpty(StringComparer.InvariantCultureIgnoreCase); // true
```

The implementations wouldn't conflict with the syntax sugar for slices and would not hurt performance because the length computation is inlined:
```csharp
public readonly ref struct Span<T>
{
    public Span<T> Slice(Range<int> range) => Slice(range.From, range.Length());
    public Span<T> Slice(int index, int length) { throw null; }
}
```

```csharp
var buffer = new Span<int>();
var slice1 = buffer[3..4];
var slice2 = buffer.Slice(new Range<int>(3, 4)); // without it
```

It's possible to implement `IsEmpty`, `IsNormalized` and other things as instance members using generic type parameter checks, but that will cause poor performance for non-BCL types.

### Benchmark

```csharp
public static class Range
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsNormalizedSpecialized(this Range<long> range)
        => range.To >= range.From;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsNormalizedGeneric<T>(this Range<T> range)
        where T : IComparable<T>
        => range.To.CompareTo(range.From) >= 0;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsNormalizedComparer<T>(this Range<T> range, IComparer<T> comparer)
        where T : IComparable<T>
        => comparer.Compare(range.To, range.From) >= 0;
}
```

Test environment: Intel Xeon E5-2687W, 3100 MHz, 8 cores, 16 threads
Iterations: 1000000 for inner loop, 1000000 for outer loop

| Method                  | Duration (msec) |
|:------------------------|----------------:|
| IsNormalizedSpecialized |             643 |
| IsNormalizedGeneric     |             975 |
| IsNormalizedComparer    |            1336 |

Duration is measured for a single outer loop iteration.

## Open Questions

* Should `Range<T>` support nullable values? That prevents being of `IComparable<T>` constraint on the generic type parameter, but at the same time allows to have open-ended ranges. Type safety could be implemented in the static constructor of `Range<T>`.

```csharp
static Range()
{
    var valueType = typeof(T);
    if (valueType.IsGenericType && valueType.GetGenericTypeDefinition() == typeof(Nullable<>))
    {
        valueType = valueType.GetGenericArguments()[0];
    }

    var comparableType = typeof(IComparable<>).MakeGenericType(valueType);
    if (!comparableType.IsAssignableFrom(valueType))
    {
        throw new Exception($"The {valueType.Name} type doesn't implement {typeof(IComparable<>).Name}.");
    }
}
```

Another way to do that is to use `T?` as the field type, but it would increase the size of generic instances and would cause performance lose.

```csharp
public readonly struct Range<T> : IEquatable<Range<T>>, IFormattable, ISerializable
    where T : IComparable<T>
{
    public readonly T? From;
    public readonly T? To;
}

public static class Range
{
    public static int? Length(this Range<int?> range) { throw null; }
}
```

| Implementation (`T` is `int`) | Size (bytes) |
|:------------------------------|-------------:|
| `Range(T, T)`                 |            8 |
| `Range(T?, T?)`               |           16 |

**Comment by svick** [comment]
My questions:

1. What is the point of `IsNormalized` and `Normalize`? Wouldn't it be better if ranges where `From` is larger than `To` weren't allowed in the first place?
2. Does `Range<T>` represent [closed, open or half-open interval](https://en.wikipedia.org/wiki/Interval_(mathematics)#Terminology)?
3. `public static bool Contains<T>(this Range<T> range)`

   This signature doesn't make sense to me. Was it supposed to be `public static bool Contains<T>(this Range<T> range, T value)`?

**Comment by JonHanna** [comment]
An implication of @svick's second question is that it's obvious to everyone where a range with a `Length` ends, when such things are reasonable (not so much for things that don't support subtraction and addition of unitless numbers) is that the problems for confusion between closed, open and half-open doesn't exist.

**Comment by YohDeadfall** [comment]
1. There is no argument validation in the constructor for two reasons:

  - Poor performance because of `Comparer<T>.Default`. It's possible to restrict `T` to be `IComparable<T>`, but then it isn't possible to support nullable value types. See the Benchmarks section.

  - It wouldn't work for strings because of Unicode. We should provide a comparer to the non-default constructor to solve that issue, and that isn't a good idea since it should be stored too.

These methods should be used to validate user input (for example model parameter validation in ASP.NET), but later you can omit them for performance optimization.

2. Half-open. @JonHanna already commented about that. If you want to include the maximum value of `T` then use `Range<T?>`:

```csharp
var range1 = new Range<int>(int.MinValue, int.MaxValue);
var range2 = new Range<int?>(int.MinValue, int.MaxValue);

range1.Contains(int.MaxValue); // false;
range2.Contains(int.MaxValue); // true
```

But it's impossible to compute `Length` for `Range<T?>`. And that is fine, since `null` should be treated as infinity.

3. Thanks. Fixed.

**Comment by karelz** [comment]
@KrzysztofCwalina can you comment if `Range` is ready for CoreFX repo?

**Comment by KrzysztofCwalina** [comment]
The corfxlab Range is not ready yet. There are the following open questions:
1. Should Range be generic?
2. If not, should its indexes be long or int?
3. The compiler team wants to provide syntax for ranges, will this range type worrk for the compiler?
4. Is range (index, count) or (from,to)
5. If (from,to), is it exclusive or inclusive?
6. In Python, ranges/sliceing can support skipping elements. Do we want to support it to?

**Comment by karelz** [comment]
OK, let's close this API proposal then. We should first iterate on the proposal in CoreFxLab.

**Comment by YohDeadfall** [comment]
@karelz Should I reopen this issue in the CoreFxLab repo?

**Comment by karelz** [comment]
@YohDeadfall that might be reasonable - @KrzysztofCwalina can provide further guidance how issues are tracked in CoreFxLab repo.
