### ISSUE TITLE
Tests under "System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_CreateCounter_SetReadOnly" failed with "Assert.NotEqual() Failure\r\nExpected: Not 0\r\nActual: 0"

### ISSUE THREAD

**Issue by Sunny-pu** [dotnet/corefx#25236]
failed test: 
System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_CreateCounter_SetReadOnly (from (empty)) 
Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_release/lastCompletedBuild/testReport/System.Diagnostics.Tests/PerformanceCounterTests/PerformanceCounter_CreateCounter_SetReadOnly/

MESSAGE:
~~~
Assert.NotEqual() Failure\r\nExpected: Not 0\r\nActual: 0
~~~
STACK TRACE:
~~~
at System.Diagnostics.Tests.Helpers.RetryOnAllPlatforms[T](Func`1 func) in D:\j\workspace\outerloop_net---7a39cc82\src\System.Diagnostics.PerformanceCounter\tests\Helpers.cs:line 71 at System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_CreateCounter_SetReadOnly() in D:\j\workspace\outerloop_net---7a39cc82\src\System.Diagnostics.PerformanceCounter\tests\PerformanceCounterTests.cs:line 78
~~~

**Comment by danmosemsft** [comment]
@adiaaida ptal

**Comment by adiaaida** [comment]
It looks like we hit the retry limit on this test run. I can either up the retry limit, or change the sleep amount. I'll look into additional ways to harden the tests.

**Comment by wtgodbe** [comment]
@adiaaida any updates on the status of this?

**Comment by adiaaida** [comment]
I've been looking at the results for this test, and I think the change to disable parallelism (#25401) fixed this issue. It hasn't failed since.

**Comment by wtgodbe** [comment]
Great! I'll close this then, if it gets hit again the issue can be re-opened.
