### ISSUE TITLE
Move RandomNumberGenerator to coreclr

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#25232]
There are many cases where RandomNumberGenerator needs to be used. Currently it requires pulling in whole System.Security.Cryptography.Algorithms. It would be useful to have it defined in coreclr to avoid this dependency.

cc: @bartonjs @morganbr

**Comment by stephentoub** [comment]
Hope does moving it to coreclr help? What dependencies?

**Comment by morganbr** [comment]
@stephentoub, it would have helped in #25013 and we might want it for other future hash algorithms as well.

**Comment by stephentoub** [comment]
That's a corefx PR. Why does it require moving something to coreclr (and corert)? And we're implementing new hash algorithms in coreclr rather than corefx?

**Comment by morganbr** [comment]
Because I accidentally pointed to the wrong PR 😄 . https://github.com/dotnet/coreclr/pull/14863 is the right one.

**Comment by morganbr** [comment]
Future hash algorithms would probably be in CoreFX. I'd be fine with a move to System.Runtime to start with and see if we really need CoreLib.

**Comment by jkotas** [comment]
I am strongly opposed on having on strong cryptography in CoreCLR. It creates more problems than it solves.
