### ISSUE TITLE
Should we randomise pivots in remaining S.Linq quicksorts?

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#25240]
In #24116 @stephentoub replaced Linq's main use of quicksort with `Array.Sort` (which uses a hybrid sort) to avoid the worse case scenarios identified in #24110

Linq still uses variants of quicksort; partial quicksort to find just part of an ordered sequence and quickselect to find a single element in the ordered sequence. Both of these have the same worse cases as quicksort.

`Array.Sort()` is not amenable to these variants.

(Also Linq.Parallel still uses quicksort).

4c538585453895abbdde2d4c1e13f1adf1578b3e tests for similar cases to those #24110 complains of. I ran them on the current code, the previous code, and the previous code modified to use random pivots with a xorshift128+ random (faster than `Random.Next()` and no heap allocation). Along with those existing tests that touch on ordering, I found the following:

|Test Name|Reverted|Array|Random|Improvement Array|Improvement Random|
|---|---|---|---|---|---|
|OrderBy(size: 100, iteration: 1000, wrapType: ICollection)|7.12835916007773|8.44284162141898|9.55231274424703|-18.4401828221983|-34.0043694451399|
|OrderBy(size: 100, iteration: 1000, wrapType: IEnumerable)|8.31319256253207|9.64644876629239|13.3377040230432|-16.0378361710201|-60.4402150283013|
|OrderBy(size: 100, iteration: 1000, wrapType: IReadOnlyCollection)|8.287985653899|9.66300892106141|10.8402846595428|-16.5905604157935|-30.7951667899316|
|OrderBy(size: 100, iteration: 1000, wrapType: NoWrap)|7.12519855811195|8.4986142334852|9.83434900229923|-19.2754723138155|-38.0221045363423|
|OrderByDescending(size: 100, iteration: 1000, wrapType: ICollection)|6.83798124538432|6.16107873794186|9.04367368779049|9.89915712183875|-32.256485697369|
|OrderByDescending(size: 100, iteration: 1000, wrapType: IEnumerable)|8.09819885341283|7.30799004841846|10.9410867061306|9.75783404801615|-35.1051870196999|
|OrderByDescending(size: 100, iteration: 1000, wrapType: IReadOnlyCollection)|8.03923158418696|7.69064121266405|10.3879201120447|4.33611555871311|-29.2153361084606|
|OrderByDescending(size: 100, iteration: 1000, wrapType: NoWrap)|6.83359279037543|6.07240320977215|9.14982792796568|11.1389367782546|-33.8948370007133|
|OrderByThenBy(size: 100, iteration: 1000, wrapType: ICollection)|7.61908238511442|9.08396891367261|10.1217532816741|-19.2265479556984|-32.8474056331141|
|OrderByThenBy(size: 100, iteration: 1000, wrapType: IEnumerable)|8.80899047807415|10.277000339993|11.3423225286133|-16.6649046286606|-28.7584832432807|
|OrderByThenBy(size: 100, iteration: 1000, wrapType: IReadOnlyCollection)|9.17246763473642|10.5101108520149|11.2456625407076|-14.5832427057337|-22.6023681797462|
|OrderByThenBy(size: 100, iteration: 1000, wrapType: NoWrap)|7.60360406591007|9.20888756607525|9.93286135010613|-21.1121395360694|-30.6335951215428|
|OrderDifferentSequencePatterns(size: 1000, iterationCount: 1000, pattern: "asc and desc mixed", sequence: [0, 999, 2, 997, 4, ...])|105.411336048631|97.9249670353268|143.400279892381|7.10205305608725|-36.0387651535163|
|OrderDifferentSequencePatterns(size: 1000, iterationCount: 1000, pattern: "asc then desc", sequence: [1000, 999, 998, 997, 996, ...])|420.020209192197|263.470161474411|195.16256008508|37.2720274624096|53.5349595533925|
|OrderDifferentSequencePatterns(size: 1000, iterationCount: 1000, pattern: "asc", sequence: [0, 1, 2, 3, 4, ...])|105.362480225828|86.9211643744856|141.131704381542|17.5027351404564|-33.9487302112177|
|OrderDifferentSequencePatterns(size: 1000, iterationCount: 1000, pattern: "desc then asc", sequence: [0, 1, 2, 3, 4, ...])|2805.12054839126|306.402120712674|197.79463755362|89.077042664409|92.9488008040491|
|OrderDifferentSequencePatterns(size: 1000, iterationCount: 1000, pattern: "desc", sequence: [999, 998, 997, 996, 995, ...])|106.657028249226|136.226477408211|143.234062552128|-27.7238637194071|-34.2940684766055|
|OrderDifferentSequencePatterns(size: 1000, iterationCount: 1000, pattern: "random", sequence: [534011718, 237820880, 1002897798, 1657007234, 1412011072, ...])|200.154685225037|178.204408640957|217.880368583894|10.9666563934794|-8.85599222367827|

`Array.Sort` is worse for many cases, but better for a few and much better for quicksort's worse cases.
Randomised-pivot quicksort is worse for almost all cases, but even better than `Array.Sort` for the worse cases. Randomised pivots are also usable with the variants like quickselect.

It would seem that randomised pivots aren't worth it for the full sorts, but what about the partials? Is the cost to the general case worth the benefit of avoiding the worse case? Should a different pivot strategy again be used?

**Comment by stephentoub** [comment]
> Array.Sort is worse for many cases, but better for a few and much better for quicksort's worse cases.

I'm not aware of any reason why we'd generally expect different kinds of inputs to Array.Sort from LINQ's OrderBy, and thus I don't believe we should have two different implementations for them.  If there are improvements to be made to perform better on a wider set of inputs, we should make such improvements to Array.Sort rather than bifurcating and maintaining a separate implementation.

That's of course separate from the partial/select cases, where we can't use Array.Sort.

**Comment by JonHanna** [comment]
Yes, it's only the partial cases I think need be considered further, but I would have been remiss if I didn't compare `Array.Sort` and the previous version as well. If it had been consistently worse for the majority of cases, instead of worse sometimes and better others it might have been worth considering why that was so.

**Comment by OmarTawfik** [comment]
@JonHanna @stephentoub it seems that it was concluded that we're not updating Linq's sort function after all. We can close this issue, and maybe consider `Array.Sort()` for further improvements.

**Comment by JonHanna** [comment]
@OmarTawfik I was thinking of the partial versions that can't be implemented with `Array.Sort()`. That said, the ideas in #25945 would mean that they then could be implemented with it, and it would have applicability beyond that, so I'm happy to close this while that remains a possibility.
