### ISSUE TITLE
System.Text.Formatting Epic

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#25249]
Tracking item for [System.Text.Formatting](https://github.com/dotnet/corefxlab/tree/master/src/System.Text.Formatting)

Related #24174

**Comment by KrzysztofCwalina** [comment]
We should identify what exactly from System.Text.Formatting we need. The corfxlab project/dll/package has several separable features.

**Comment by ahsonkhan** [comment]
SignalR does not currently depend on this. Moving the issue to future  and removing it from the parent epic.

**Comment by stephentoub** [comment]
@ahsonkhan, what is this issue tracking now?

**Comment by ahsonkhan** [comment]
> what is this issue tracking now?

Mainly some `IBufferWrite<byte>` implementations: https://github.com/dotnet/corefxlab/blob/e075d78df60452b68d212e3333fd3f37cd28d4f0/src/System.Text.Formatting/System/Text/Formatting/Formatters/ArrayFormatter.cs#L12

This is tracked by the recent ArrayBufferWriter proposal/work: https://github.com/dotnet/corefx/issues/34894

And some ReadOnlySequence helpers:
https://github.com/dotnet/corefxlab/blob/e075d78df60452b68d212e3333fd3f37cd28d4f0/src/System.Text.Formatting/System/Text/Parsing/SequenceParser.cs#L15

This should ideally be tracked by https://github.com/dotnet/corefx/issues/32588 (`SequenceReaderExtensions`). It looks like we didn't add the `Parse` methods.

cc @davidfowl, @JeremyKuhne 

Given that, I think we can close this issue (pending the `SequenceReader` issue update).

**Comment by stephentoub** [comment]
Thanks. Given that, and that we're not using epics anymore, per @danmosemsft, I'm closing it.
