### ISSUE TITLE
System.Uri.GetComponents behavior and MSDN documentation

### ISSUE THREAD

**Issue by a4lg** [dotnet/corefx#2525]
`System.Uri.GetComponents` method behaves different from the MSDN documentation.
https://msdn.microsoft.com/en-us/library/system.uri.getcomponents%28v=vs.110%29.aspx

The documentation says:

> When `Query` or `Fragment` is specified alone, the return value includes the delimiter.

But actually, this method returns value without delimiter.

``` csharp
var uri = new Uri("http://www.example.com/path/to/sample.html?key=value#fragment");
// Expected: "path/to/sample.html" (without delimiter; not "/path/to/sample.html")
Debug.Assert(uri.GetComponents(UriComponents.Path, UriFormat.SafeUnescaped).Equals("path/to/sample.html"));
// Expected: "/path/to/sample.html" (with delimiter)
Debug.Assert(uri.GetComponents(UriComponents.Path | UriComponents.KeepDelimiter, UriFormat.SafeUnescaped).Equals("/path/to/sample.html"));
// FAIL (Expected: "?key=value", Actual: "key=value")
Debug.Assert(uri.GetComponents(UriComponents.Query, UriFormat.SafeUnescaped).Equals("?key=value"));
// Expected: "?key=value" (with delimter)
Debug.Assert(uri.GetComponents(UriComponents.Query | UriComponents.KeepDelimiter, UriFormat.SafeUnescaped).Equals("?key=value"));
// FAIL (Expected: "#fragment", Actual: "fragment")
Debug.Assert(uri.GetComponents(UriComponents.Fragment, UriFormat.SafeUnescaped).Equals("#fragment"));
// Expected: "#fragment" (with delimiter)
Debug.Assert(uri.GetComponents(UriComponents.Fragment | UriComponents.KeepDelimiter, UriFormat.SafeUnescaped).Equals("#fragment"));
```

I needed `UriComponents.KeepDelimiter` flag just like `UriComponents.Path` to get result with delimiter.

I'm not sure that this is a bug (maybe this is a documentation issue; even Mono behaves like this), but I want this "issue" to be reviewed anyway.

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar

**Comment by SidharthNabar** [comment]
I verified that behavior on .NET framework and the behavior is the same as described above. I propose we treat this as a documentation bug and fix the MSDN documentation.

**Comment by davidsh** [comment]
>I propose we treat this as a documentation bug and fix the MSDN documentation.

Yes, please open up a doc bug.

**Comment by karelz** [comment]
@mairaw can you please fix it?

**Comment by mairaw** [comment]
Sure. The writer of this topic has started to make similar fixes to the topic so I'm checking with him if it's ready to be published.

/cc @DelfCo

**Comment by mairaw** [comment]
I've published the updates done by the writer into production. Let me know if that looks good. Thanks!

**Comment by karelz** [comment]
Wow, thanks for quick turn-around @mairaw! I wish we didn't sit on it for 1+ year on our side ... well, we can just try to do better in future from now on :)

**Comment by karelz** [comment]
It's fixed, closing.
