### ISSUE TITLE
Add RID for Fedora 27 and enable CoreFX runs

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#25252]
https://fedoramagazine.org/announcing-fedora-27/

https://fedoraproject.org/wiki/Releases/27/Schedule

https://fedoraproject.org/wiki/End_of_life

Related: https://github.com/dotnet/corefx/pull/16302

**Comment by weshaggard** [comment]
@karelz is this something @wtgodbe could look at?

**Comment by karelz** [comment]
Sounds reasonable. Is there preferred timeline?

**Comment by weshaggard** [comment]
We will need it for 2.1, it would be nice to have for preview1 but I don't think it is required for preview1.

**Comment by wtgodbe** [comment]
Does anyone know if we already have a docker image for Fedora 27? @chcosta maybe?

**Comment by weshaggard** [comment]
The RID for this was added in https://github.com/dotnet/corefx/pull/26439. 

We just need to get some test images setup.

**Comment by ianhays** [comment]
Fedora27 Outerloop daily runs will be enabled by https://github.com/dotnet/corefx/pull/27129.

Fedora26 is our current on-PR and on-Push Fedora test version.

**Comment by ianhays** [comment]
Since we're already doing official build Fedora27 daily runs, I'm closing this.
