### ISSUE TITLE
How to implement System.IO.FileSystem.DriveInfo on FreeBSD?

### ISSUE THREAD

**Issue by janhenke** [dotnet/corefx#2526]
This issue should coordinate our effort to implement the ```System.IO.FileSystem.DriveInfo``` assembly on FreeBSD.

/cc @josteink

**Comment by josteink** [comment]
I did some work on this before @sokket refactored the Interop code.

Iiirc I verified that his `getmntent`Interop-bits seemed to work as they should, so we should be able to build a proper DriveInfo implentation on top of that.

See my preliminary code here, where everything is concatenated into one file:

https://github.com/josteink/corefx/blob/driveinfo-test/test.cs

**Comment by janhenke** [comment]
Rebuilding with current HEAD, this assembly seems to be generated. Does anybody know which commit introduced the fix?

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/pull/2136

**Comment by jasonwilliams200OK** [comment]
Depending on the build error it was throwing before, it might be due to this change: https://github.com/nguerrera/corefx/commit/2b01345b2a925400569269b1149afd645c77b790.
To get the exact commit hash, `git bisect` can be used, see: https://github.com/dotnet/roslyn/issues/3166#issuecomment-106750411. :smile:

**Comment by jasonwilliams200OK** [comment]
This issue was opened after #2136.

**Comment by janhenke** [comment]
This assembly compiles now, but it would be nice to know which PR enabled this. It was not #2136, but something in between.

**Comment by jasonwilliams200OK** [comment]
Perhaps it was nguerrera@2b01345 from https://github.com/dotnet/corefx/pull/2606, which might have fixed some underlying bug.

**Comment by janhenke** [comment]
Well, it is for our list only anyway. I'll add #2606 as the PR fixing and close this issue. :)

**Comment by stephentoub** [comment]
> This assembly compiles now, but it would be nice to know which PR enabled this.

I guess I'm not clear on what the problem was then, as System.IO.FileSystem.DriveInfo.dll compiled fine for FreeBSD after #2136, e.g. this:
```
git checkout 2589d830efed209ab9705c404c2c8c97df57981e
cd src\System.IO.FileSystem.DriveInfo\
msbuild /t:rebuild /p:OSGroup=FreeBSD
```
successfully builds System.IO.FileSystem.DriveInfo.dll.

**Comment by janhenke** [comment]
I am also not sure any more what particular problem caused this assembly to not build. Luckily it builds now, so we do not have to worry about it.

**Comment by sokket** [comment]
I'll be changing this implementation for Linux, OS X, and FreeBSD either today or tomorrow, so any build wonkiness will go away with that :). I'll be sure to add all of you onto the PR as FYI
