### ISSUE TITLE
Test failure: System.Data.Tests.DataTableTest.PropertyExceptions

### ISSUE THREAD

**Issue by Cronan** [dotnet/corefx#25268]
The test `System.Data.Tests.DataTableTest.PropertyExceptions ` has failed.

Assert.Throws() Failure
Expected: typeof(System.ArgumentException)
Actual:   (No exception was thrown)

```
Stack trace:

at System.Data.Tests.DataTableTest.<>c.<PropertyExceptions>b__16_0() in D:\git\dotnetfix\corefx\src\System.Data.Common\tests\System\Data\DataTableTest.cs:line 886

Child process:
  System.Data.Common.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb System.Data.Tests.DataTableTest+<>c Int32 <PropertyExceptions>b__16_0()
```

- Config:  netcoreapp-Windows_NT-Debug-x64
- OS: Microsoft Windows [Version 6.1.7601]

**Comment by danmosemsft** [comment]
@Cronan oops, your locale must be en-GB. I pushed up a fix. 

We should have some runs that aren't en-US.

**Comment by danmosemsft** [comment]
@weshaggard could we change one of our test runs to be a different culture? Maybe one Linux and one Windows?

**Comment by danmosemsft** [comment]
@Cronan do all other tests pass in en-GB?

**Comment by weshaggard** [comment]
>@weshaggard could we change one of our test runs to be a different culture? Maybe one Linux and one Windows?

Sure it would require a new test queue. File an issue for core-eng to set it up.

**Comment by Cronan** [comment]
11 tests failed in total, I’ll rerun again after the fix has been merged and raise an issue with all the details here ...
