### ISSUE TITLE
Error: CS1703: System.Runtime, Version=4.1.2.0

### ISSUE THREAD

**Issue by Vohuman** [dotnet/corefx#25260]
When my MVC.core project tries to open any page, I face with the following error:

> CS1703: An assembly with the same identity 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has already been imported.

I tried to clean Temporary folder and checked about the conflicts within the projects but I found nothing.

**Comment by karelz** [comment]
Do you have a (minimal) repro for your failure?
Are you running on .NET Core or on .NET Framework?
Are you able to reproduce the problem outside of MVC? (if not, starting the bug report in MVC repo might be best)

**Comment by tarekgh** [comment]
This issue was moved to aspnet/Mvc#7058

**Comment by tarekgh** [comment]
CC @joperezr
