### ISSUE TITLE
Is it possible to run test against runtime only?

### ISSUE THREAD

**Issue by Deren-Liao** [dotnet/corefx#25287]
I was able to build and run corefx tests.  
My work has a constraint that it need to use docker image less than 500MB in size. 
The docker image contains corefx, coreclr and with built tests is 13.4 GB  

I wonder if it is possible that I copy minimum required files to the microsoft/dotnet:2.0-runtime-jessie image and have the test run?

**Comment by karelz** [comment]
Size of tests is not a metric we are optimizing for.
If you need to run tests on small Docker images, you will need to manually build & deploy only subset of tests (e.g. per project, or in extreme per test). There is nothing in our scripts/infrastructure which would help you beyond that.

I am curious why you have the 500MB limit on Docker image ...

**Comment by Deren-Liao** [comment]
It has something to do with our existing test infrastructure.  We'll have to find an alternatives.   Thanks.
