### ISSUE TITLE
HttpListener failure on Windows ARM

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#25289]
System.Net.HttpListenerException: Invalid access to memory location
   at System.Net.HttpListener.BeginGetContext(AsyncCallback callback, Object state)
   at DotNetCoreHttpListener.Program.Main(String[] args) in C:\src\DotNetCoreHttpListener\Program.cs:line 22

**Comment by jkotas** [comment]
This is bug in .NET Core implementation of System.Net.HttpListener on Windows ARM.

https://msdn.microsoft.com/en-us/library/windows/desktop/aa364495(v=vs.85).aspx says “The pRequestBuffer parameter must point to a valid memory buffer with a memory alignment equal or greater to the memory alignment requirement for an HTTP_REQUEST structure.”

The alignment requirement for HTTP_REQUEST structure on Windows ARM is 8.

System.Net.HttpListener does not fulfill this requirement because of it casts BYTE* to HTTP_REQUEST* in several places:
https://github.com/dotnet/corefx/blob/ea1852dcf0099aeee670857231f3d87e742bc296/src/System.Net.HttpListener/src/System/Net/Windows/SyncRequestContext.cs#L35
https://github.com/dotnet/corefx/blob/ee8fa8715cc2c5f29410feffbfcf02ffe8368ba8/src/System.Net.HttpListener/src/System/Net/Windows/AsyncRequestContext.cs#L60

**Comment by davidsh** [comment]
>The alignment requirement for HTTP_REQUEST structure on Windows ARM is 8.

@jkotas 
This issue is currently marked as "arch-arm32".  Wouldn't a requirement of "8" be for "arch-arm64"?  Is this bug repro'ing on arm32 or arm64 architectures?

**Comment by jkotas** [comment]
This is for `arch-arm32`. ARM32 ABI requires 8-byte alignment for structures that contain 64-bit integers or floats.

**Comment by rmkerr** [comment]
This issue turned out to be a lot more complicated than I had hoped, but I believe that I've found a workable fix. I'm in the process of validating the change and making sure that the code is clean before I submit for review.

**Comment by davidsh** [comment]
Re-opening for porting to release/2.0.x branch.

**Comment by davidsh** [comment]
@rmkerr Please submit a PR and associated shiproom email for a release/2.0.0 port of this fix.

**Comment by rmkerr** [comment]
Ideally I'd like to make sure the 2.0.0 fix is as similar as possible to the 2.1.0 fix. However, I've been having some trouble with using span in 2.0.0. I get the error:

> The type or namespace name 'Span<>' could not be found (are you missing a using directive or an assembly reference?) 

Despite Span<> having been implemented at that point. As far as I can tell no relevant references have been added to HttpListener.csproj. I can't help but think that I'm missing something simple, but have not been able to figure it out. Any suggestions? If not, I'll submit the change with an alternative fix.

**Comment by davidsh** [comment]
@stephentoub Can you help w/ this?

>Despite Span<> having been implemented at that point. As far as I can tell no relevant references have been added to HttpListener.csproj. I can't help but think that I'm missing something simple, but have not been able to figure it out. Any suggestions? If not, I'll submit the change with an alternative fix.

**Comment by stephentoub** [comment]
> Despite Span<> having been implemented at that point. As far as I can tell no relevant references have been added to HttpListener.csproj. I can't help but think that I'm missing something simple, but have not been able to figure it out. Any suggestions? If not, I'll submit the change with an alternative fix.

Span is exposed from the System.Runtime contract starting in 2.1.  To use it in 2.0, you need to add a reference to System.Memory, which contains the out-of-band implementation of Span rather than the one implemented in the runtime.

**Comment by rmkerr** [comment]
Thanks for the quick response. I'll go ahead and do it that way.

**Comment by jkotas** [comment]
System.Memory have not shipped a stable version yet. It is disabled in 2.0 servicing branches. You won't be able to add it as a dependency in 2.0 servicing fix.

You should redo the 2.0 servicing fix to not depend on Span.

**Comment by rmkerr** [comment]
Closing this since the 2.0.x servicing port has been merged.
