### ISSUE TITLE
IsolatedStorageException using System.IO.Packaging

### ISSUE THREAD

**Issue by DavidThi808** [dotnet/corefx#25294]
We are getting an IsolatedStorageException in the System.IO.Packaging code ([details here](https://github.com/OfficeDev/Open-XML-SDK/issues/292#issuecomment-344715377)). Two questions:

1. What is the best way to avoid this using the existing code.
2. I'm willing to contribute a fix to eliminate this issue - can I volunteer to do so?

thanks - dave

**Comment by ViktorHofer** [comment]
@karelz who owns System.IO.Packaging?

**Comment by karelz** [comment]
@DavidThi808 as first step, it would be great to create minimal repro. Can you help with that?

@ViktorHofer check the list of [area owners](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#areas) - it is currently part of System.IO. If there is need to split it off, I would expect System.IO experts to initiate that discussion.

**Comment by karelz** [comment]
Ah, I missed the zip link. It seems rather large repro. Is there a chance to minimize it to a sample code which could be copy pasted here? Or is the zip the minimal thing possible?

**Comment by DavidThi808** [comment]
That's the minimum. You only need the Word AddIn project to repro. The big file is the chart.xml and it needs that giant set of data to cause the error.

You need to run the Word AddIn project - it runs fine as a command line app.

**Comment by karelz** [comment]
Any chance to repro without the Word AddIn? And minimize the data needed? The larger repro, the more difficult it is to debug. (yes, it may be non-trivial work to get there)
Smaller repros without additional libraries also minimize the chance of analyzing problems in the libraries themselves.

**Comment by DavidThi808** [comment]
Sorry, no. One of the projects there is identical except it's a command line app - it works. And if the amount of data is smaller, it works. It's the combination of being an AddIn and the large data that causes the error.

sorry - dave

ps - With that said, the code to reproduce this is very minimal. It's just the number of nodes on chart.xml that's large.

**Comment by karelz** [comment]
OK, that's a good context to have ;)

**Comment by danmosemsft** [comment]
@DavidThi808 with respect to your original comment, you are very welcome to contribute a fix (if a fix is required). There is information on how to contribute here https://github.com/dotnet/corefx/tree/master/Documentation
especially https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md

**Comment by twsouthwick** [comment]
This issue, I believe, is only hit when running the .NET Framework version of the packaging library. The .NET Core version (which this repo contains) does not use IsolatedStorage and does not hit this issue. Even though the System.IO.Packaging NuGet package says it supports .NET 4.6, in reality it is just redirecting to the implementation in .NET Framework. This means, that even using the NuGet package, if you're running on .NET Framework, you will continue to hit this issue even though it is fixed in .NET Core.

**Comment by ericstj** [comment]
Correct.  Given that this repo is only implementing System.IO.Packaging on .NETCore which doesn't use IsolatedStorage I'm closing this.
