### ISSUE TITLE
Problem building the build-managed.sh for an x86 CoreFX Linux build

### ISSUE THREAD

**Issue by philippweidhas** [dotnet/corefx#25293]
Hallo Github Community,

im facing following problems building the build-managed.sh for an corefx x86 build:
```
/home/arbeit/Tools/depProj.targets(83,5): error : Error no assets were resolved from NuGet packages. [/home/arbeit/corefx/external/netstandard/netstandard.depproj]
/home/arbeit/Tools/depProj.targets(83,5): error : Error no assets were resolved from NuGet packages. [/home/arbeit/corefx/external/docs/docs.depproj]
/home/arbeit/Tools/depProj.targets(83,5): error : Error no assets were resolved from NuGet packages. [/home/arbeit/corefx/external/ILLink/ILLink.depproj]
```
I was following these steps:

```
git clone https://github.com/dotnet/corefx.git
cd corefx
sudo ./cross/build-rootfs.sh x86

./build-native.sh -debug -- clang3.8
./build-native.sh -debug -buildArch=x86 -- cross clang3.8
./build-managed.sh -BuildTests=false
```
The build-native.sh builds working fine, but the managed build not. I also tried -release instead of -debug.

I found [these  issue with a workaround](https://github.com/dotnet/corefx/issues/15274) but i have no 
src/Tools/CoreFx.Tools/CoreFx.Tools.csproj.

Can someone help me with that problems?

Greetings

Philipp.

**Comment by weshaggard** [comment]
@philippweidhas something seems to not have restored correctly. Can you go and just build `/home/arbeit/corefx/external/netstandard/netstandard.depproj` and send me the detailed log and I can help narrow down the issue.

**Comment by philippweidhas** [comment]
@weshaggard thx for asking. The solution was building corefx and corecr in the same vm. First build corecr and then build corefx.

**Comment by weshaggard** [comment]
Thanks for the follow-up @philippweidhas I'm going to close this issue then.

**Comment by deinok** [comment]
@philippweidhas I have the same issue.
`Error no assets were resolved fom NuGet packages` on `corefx/external/runtime/runtime.depproj`

I try to build coreclr and corefx on same VM (the two for x86) but stucks at this point

**Comment by weltkante** [comment]
> Error no assets were resolved fom NuGet packages on corefx/external/runtime/runtime.depproj

Same for me.

I'm also trying to build x86, can get coreclr and corefx-native build by following various issues suggestions on github, but failing to build corefx-managed. As I understand I need corefx-managed to produce the nuget packages required for x86?

It's really annoying that there are no prebuilt packages for x86 because x64 has twice the memory requirements. I can understand that you don't want to maintain live images but can we please at least get instructions how to build and use x86 ourselves?
