### ISSUE TITLE
X509Store.Add pops up a dialog, fails on OneCore systems

### ISSUE THREAD

**Issue by arturl** [dotnet/corefx#25306]
Repro:

```c#
using System;
using System.Security.Cryptography.X509Certificates;

namespace CertTest
{
    class Program
    {
        static void Main(string[] args)
        {
            X509Store store = new X509Store(StoreName.Root, StoreLocation.CurrentUser);
            store.Open(OpenFlags.ReadWrite);
            string certPath = "c:\\test\\t.cer";
            store.Add(new X509Certificate2(X509Certificate2.CreateFromCertFile(certPath)));
            Console.WriteLine("Added Cert: " + certPath);
            store.Close();
        }
    }
}
```

The code below pops up a dialog: "You are about to install a certificate from a certification authority... ":

![image](https://user-images.githubusercontent.com/1875734/32924226-6bac68ee-caf0-11e7-934e-afef4e317c16.png)

when run on a desktop version on Windows. On a GUI-less OneCore system (such as Nano or IoT Core), it fails immediately with exception 
`Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException: 'The operation was canceled by the user'` making this API completely unusable.

Interestingly, the API succeeds on Linux.

So either we have a security hole on Linux, or we need to fix it on Windows (at least OneCore SKUs) to avoid the dialog.

The popup can be avoided when the certificate is added to the local machine root, however that only works for an administrator and is not possible for many scenarios.

[EDIT] Add C# syntax highlight by @karelz

**Comment by bartonjs** [comment]
The dialog is popped (or not) by the Windows native library, not by .NET.  There has been internal discussion on this problem, and if Windows advises us to make some changes we will; but until then there's nothing we can do about it.
