### ISSUE TITLE
Feature request: Add a method to get the core framework version.

### ISSUE THREAD

**Issue by scegg** [dotnet/corefx#25310]
Due to some function is brought in with newer version of core framework, I need to test the installed version of core framework on client side while my app running.

Is there any way to get the framework version, e.g. "2.0.3" ?
Currently, Environment.Version is set to netfx version even the app is running as core app.

Thanks.

**Comment by Joe4evr** [comment]
That's not how things work in the new world. If you need some functionality from the framework, you target the NetStandard version that contains that functionality.

**Comment by scegg** [comment]
@Joe4evr So, how to check this?
Method will throw PlatformNotSupported until 2.0.4.

https://github.com/dotnet/corefx/issues/25259

**Comment by karelz** [comment]
Your app can decide which version to target and can even require minimal minor version (e.g. 2.0.4), or be self-contained. Would that be sufficient for you?

**Comment by scegg** [comment]
@karelz 
It should be good. How can I do that?
Thanks

**Comment by karelz** [comment]
Modify your app.runtimeconfig.json (runtimeOptions/framework/version) to desired minimal version:
https://github.com/dotnet/cli/blob/master/Documentation/specs/runtime-configuration-file.md#appnameruntimeconfigjson
