### ISSUE TITLE
Tests under "System.Net.Tests" failed with "Exit code was 131 but it should have been 42"

### ISSUE THREAD

**Issue by Sunny-pu** [dotnet/corefx#25311]
Failed tests:
 System.Net.Tests.WebRequestTest.DefaultWebProxy_SetThenGet_ValuesMatch
 System.Net.Tests.GlobalProxySelectionTest.Select_Success
 System.Net.Tests.HttpWebRequestTest.DefaultMaximumResponseHeadersLength_SetAndGetLength_ValuesMatch
 System.Net.Tests.HttpWebRequestTest.DefaultMaximumErrorResponseLength_SetAndGetLength_ValuesMatch
 System.Net.Tests.HttpWebRequestTest.DefaultCachePolicy_SetAndGetPolicyReload_ValuesMatch
 System.Net.Tests.AuthenticationManagerTest.CredentialPolicy_Roundtrip
 System.Net.Tests.AuthenticationManagerTest.CustomTargetNameDictionary_ValidCollection
 System.Net.Tests.AuthenticationManagerTest.Register_Unregister_ModuleCountUnchanged

Configuration: osx10.12_debug

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/3587/testReport/

MESSAGE:
Exit code was 131 but it should have been 42\nExpected: True\nActual: False
+++++++++++++++++++
STACK TRACE:
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 205 at System.Net.Tests.WebRequestTest.DefaultWebProxy_SetThenGet_ValuesMatch() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/src/System.Net.Requests/tests/WebRequestTest.cs:line 36

**Comment by danmosemsft** [comment]
Look at the full console and you see`A fatal error occurred, the required library libhostfxr.dylib could not be found at /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/bin/testhost/netcoreapp-OSX-Debug-x64/shared/Microsoft.NETCore.App/9.9.9/`
Please dupe all such against https://github.com/dotnet/corefx/issues/25037
