### ISSUE TITLE
Better error messaging for Integrated Auth Failure in SqlClient

### ISSUE THREAD

**Issue by saurabh500** [dotnet/corefx#25328]
SqlClient error should also point the user to check if Kerberos is enabled on Sql Server for authentication when Integrated Authentication fails.

**Comment by saurabh500** [comment]
Related problems https://github.com/dotnet/corefx/issues/25149

**Comment by saurabh500** [comment]
Needs string change which shouldn't be done unless really necessary.

**Comment by danmosemsft** [comment]
I have no opinion on this, but note that we don't localize our strings currently so string changes are fine from that POV. There is no loc freeze for example.

**Comment by saurabh500** [comment]
OK. In that case, I will take the opportunity to enhance this message :)
