### ISSUE TITLE
TryFormat with format strings as ReadOnlySpan<char> or string

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#25337]
We've approved and added a bunch of `TryFormat` methods for doing the equivalent of `ToString`, but rendering into a supplied `Span<char>` instead of allocating a `string`.  Many of these `TryFormat` methods accept a `string format` argument, just as does `ToString`.  @justinvp raised the question of whether these should instead be `ReadOnlySpan<char> format`.

Example scenario:
His scenario was in looking at changing the implementation of `string.Format`, `StringBuilder.AppendFormat`, etc.: today they allocate substrings when parsing out formats from holes, e.g. `"blah {0:D4} blah {1:[##-##-##]}"`, in order to supply that format string to the formatting API.  We can achieve this internally for these methods; the question is whether we should expose that publicly so that other scenarios can benefit from it as well, if there are other scenarios.

Another scenario:
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Numerics/src/System/Numerics/BigNumber.cs#L578
BigInteger creates a format string to use when formatting its _sign value, in order to specify the number of digits.  If format supported `ReadOnlySpan<char>`, we could use stack space instead of allocating a string.

The main downside to this change is it makes the methods a bit harder to use, in particular because there's no implicit cast from `string` to `ReadOnlySpan<char>`, so instead of passing in a format like `"D4"`, you need to do `"D4".AsReadOnlySpan()`. `TryFormat` methods on the following types would be affected:
```C#
BigInteger // TryFormat not yet implemented
Byte
DateTime
DateTimeOffset
Decimal
Double // TryFormat not yet implemented
Guid
Int16
Int32
Int64
SByte
Single // TryFormat not yet implemented
TimeSpan
UInt16
UInt32
UInt64
```

Options
---
1. Leave the design as-is.  We could using `string format`, we can address `string.Format`/`StringBuilder.AppendFormat` internally, and rare public uses can allocate strings when needed.
2. Change the methods to use `ReadOnlySpan<char> format` instead of `string format`.  Callers use `AsReadOnlySpan()` when they have a string.
3. Change the methods to use `ReadOnlySpan<char> format` instead of `string format`, and add an implicit cast on `string` from `string` to `ReadOnlySpan<char>`.
4. Keep the existing `string format` methods, and add overloads that take `ReadOnlySpan<char>`.

**Comment by terrajobst** [comment]
We seem to gravitate to (2) because it doesn't require an implicit conversion, but also doesn't prevent us fro adding it in the future.

**Comment by karelz** [comment]
FYI: The API review discussion was recorded - see https://youtu.be/o5JFZtgaJLs?t=1593 (18 min duration)
