### ISSUE TITLE
Error on ComputeSignature when changing from SHA256 to SHA1

### ISSUE THREAD

**Issue by Cae2** [dotnet/corefx#25340]
Hello,
I need to use a service who still dont accept SHA256 Algorithm.

the following works when I execute:

>var docXml = new SignedXml(xml);
>...
>docXml.SignedInfo.SignatureMethod = "http://www.w3.org/2000/09/xmldsig#rsa-sha1";
>docXml.ComputeSignature();

but the Xml Reference stills in SHA256. If I change the Reference to also use SHA1 with:

>var refer = new Reference { Uri = "xxxxx" };
>...
>refer.DigestMethod = "http://www.w3.org/2000/09/xmldsig#rsa-sha1";

the ComputeSignature() shows the error:

>Exception has occurred: CLR/System.Security.Cryptography.CryptographicException
>An exception of type 'System.Security.Cryptography.CryptographicException' occurred in >System.Security.Cryptography.Xml.dll but was not handled in user code: 'Could not create hash >algorithm object.'

can someone give me some advices to change all algorithms in that xml signature to SHA1? 

thanks!

Edit:
ops, forgot to mention that I'm using ASP.NET Core 2.0, also tried with the last 
System.Security.Cryptography.Xml 4.5.0-preview1-25914-04

**Comment by Cae2** [comment]
solved, I was using a wrong algorithm

changed: 

`refer.DigestMethod = "http://www.w3.org/2000/09/xmldsig#rsa-sha1";`
for
`refer.DigestMethod = SignedXml.XmlDsigSHA1Url;`

**Comment by LeoFonSilva** [comment]
> solved, I was using a wrong algorithm
> 
> changed:
> 
> `refer.DigestMethod = "http://www.w3.org/2000/09/xmldsig#rsa-sha1";`
> for
> `refer.DigestMethod = SignedXml.XmlDsigSHA1Url;`

Hello, I would like to know how you created your signature class, because I tried everything, did what you said and did not work, I can not sign xml using SHA1 in Core
