### ISSUE TITLE
Tests : Remove the number of unneeded blocking tasks in tests

### ISSUE THREAD

**Issue by Drawaes** [dotnet/corefx#25346]
I am launching this as a tracking issue for Tests in general.

There a number of cases where Tests block (Task.WaitAll is the biggest culprit it seems) across the Repo. You can get away with this for a certain amount of time, but as the test coverage grows, you tend to hit threadpool starvation and random timeouts, it also has the potential to deadlock xunit.

I have launched this issue to track the PR's and to link them back to why I am making the changes. Also to identify other tests that need changing.

Areas that need PR's to fix

- [x] System.Net.Security (SslStream)
- [ ] System.Net.Sockets
- [x] System.Net.Http
- [x] System.Net.NameResolution
- [x] System.Net.Security (Negotiate)
I will update this list with more that I find.

ref #25345 
ref #19705
ref #25360

**Comment by Drawaes** [comment]
I am going to combine the Net.Http and NameResolution as there are only a few in each unless you want a seperate PR for each @stephentoub ?

**Comment by davidsh** [comment]
>unless you want a separate PR for each @stephentoub ?

I would prefer separate PRs.

**Comment by Drawaes** [comment]
Sure no problem, I will keep them separate.

**Comment by davidsh** [comment]
At this point, I believe that System.Net.Sockets tests have no significant issues remaining.

If there are still System.Net.Sockets tests that require enhancement, please open a separate issue/PR with details about tests need changes.  Thanks!
