### ISSUE TITLE
System.Text.Encoding HeaderName missing

### ISSUE THREAD

**Issue by jstedfast** [dotnet/corefx#2535]
Was this property removed on purpose? Or is it just not yet implemented?

If it *has* been purposely removed, what should I be using instead if I want the name to use in email headers?

**Comment by stephentoub** [comment]
cc: @davidsh, @ellismg, @weshaggard

**Comment by davidsh** [comment]
@jstedfast When you say removed, are you saying: "it was in the .NET 4.5.x Framework but isn't in CoreFx"?

Can you provide a small code sample of what you are trying to do?  I don't quite understand what you're asking about.  Thx.

**Comment by jstedfast** [comment]
@davidsh yea, I'm working on trying to port [MimeKit](https://github.com/jstedfast/MimeKit).

Since you seem surprised that I'm not finding it, I'm probably doing something wrong (or I'm submitting this "bug" to the wrong place).

But anyway, in Visual Studio 2015 Community, I created a Web -> Class Library (Package) project.

Here's the link to my project.json file: https://github.com/jstedfast/MimeKit/blob/master/MimeKit/project.json

Building this project results in errors about System.Text.Encoding not having a HeaderName property and VS2015 also underlines the HeaderName property with a red squiggly.

Maybe I'm just missing a nuget package?

**Comment by jstedfast** [comment]
if it helps, here's a screenshot: http://screencast.com/t/IGefdkEDruK4

**Comment by jstedfast** [comment]
And this is a code sample:

```csharp
public static string GetMimeCharset (Encoding encoding)
{
	if (encoding == null)
		throw new ArgumentNullException ("encoding");

	switch (encoding.CodePage) {
	case 949: // ks_c_5601-1987
		return "euc-kr";
	default:
		return encoding.HeaderName.ToLowerInvariant ();
	}
}
```

**Comment by davidsh** [comment]
@jstedfast You are correct that the `HeaderName` property is not in the System.Text.Encoding class.

It is in the .NET Framework including .NET 4.6.  
https://msdn.microsoft.com/en-us/library/system.text.encoding.headername(v=vs.110).aspx

But it was not part of the Portable Class library definitions and is not part of the current contracts for the System.Text.Encoding library for CoreFx.

@ericstj and @stephentoub can comment more. But that property as well as some others from the original .NET Framework (Desktop) are not in CoreFx.

**Comment by weshaggard** [comment]
@tarekgh might have more information about this property.

**Comment by tarekgh** [comment]
HeaderName is not exposed and not implemented in System.Text.Encoding.CodePages. the work around here is to use WebName which will cover you with the most of the supported encoding and can special case the encodings which WebName wil not work with emails (as you are doing with 949 case)

**Comment by jstedfast** [comment]
@tarekgh yea, that's what I figured I would do if there was no plan to add HeaderName.

Thanks.

This issue can probably be closed now. I'll leave it up to you guys, though, in case you want to keep it open for whatever reason.

**Comment by tarekgh** [comment]
I am closing this issue for now. if we find we have enough demand on supporting HeaderName, we can consider it.

**Comment by jstedfast** [comment]
For anyone else that runs into this issue, it turns out that based on a simple program I wrote to compare all of the Encodings, there are only 3 where the WebName property differs from the HeaderName property. These are the following:

```csharp
case 932: return "iso-2022-jp";   // shift_jis
case 50221: return "iso-2022-jp"; // csISO2022JP
case 50225: return "euc-kr";      // iso-2022-kr
```

**Comment by tarekgh** [comment]
Great! thanks for your investigation. this is very helpful.
