### ISSUE TITLE
Cannot catch exception on SmtpClient.SendMailAsync when no server is listening

### ISSUE THREAD

**Issue by MrAntix** [dotnet/corefx#25369]
See repo here
https://github.com/MrAntix/cant-catch-exception

I need to be able to catch an exception when the emailing fails for what ever reason

**Comment by MrAntix** [comment]
if I turn off only my own code and debug I see the exception

Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
An unhandled exception of type 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' occurred in System.Private.CoreLib.dll
No connection could be made because the target machine actively refused it

**Comment by stephentoub** [comment]
> See repo here

I get a 404 from GitHub.  Is the repo public?

**Comment by MrAntix** [comment]
it is now :) sorry about that

**Comment by MrAntix** [comment]
there is not much there in any case, its an xunit test project with one test

    public class try_to_catch
    {
        public const int NO_SERVER_PORT = 26;

        [Fact]
        public async Task when_no_server()
        {
            try
            {
                using (var smtp = new System.Net.Mail.SmtpClient("localhost", NO_SERVER_PORT))
                {
                    var message = new MailMessage(
                        "from@localhost", "to@localhost",
                        "Message Subject",
                        "Message Body");

                   await smtp.SendMailAsync(message);
                }
            }
            catch (Exception)
            {
                Assert.True(true, "success");
            }
        }
    }

**Comment by stephentoub** [comment]
Thanks.  I believe this was already fixed with https://github.com/dotnet/corefx/pull/24536.  And I can repro your issue on 2.0 but not on 2.1.

**Comment by MrAntix** [comment]
any chance it can be patched in 2.0?

basically crashes dotnet which will make it difficult for anyone writing a reliable service which sends email

**Comment by karelz** [comment]
Closing as Fixed then. Feel free to reopen if that is not the case for you.

**Comment by stephentoub** [comment]
> any chance it can be patched in 2.0?

It already was, in https://github.com/dotnet/corefx/pull/24727.  That should be part of whenever the next 2.0 update happens.

**Comment by MrAntix** [comment]
I am able to catch that exception now, many thanks

Product Information: Version: 2.1.4
Microsoft .NET Core Shared Framework Host  Version  : 2.0.5
