### ISSUE TITLE
readdir and multi-threading

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#25375]
readdir_r has been made obsolete in glibc, and using readdir is recommended instead.
To accomodate, corefx falls back to readdir when readdir_r is not available (https://github.com/dotnet/corefx/pull/10795).

The readdir implementation in glibc is thread-safe in that it allows multiple different DIRs (which may point to the same path) to be enumerated simultaneously.
It does **NOT** allow a single DIR to be iterated by multiple threads.

Is it expected from functions like `Directory.EnumerateFiles` to return an iterator that can be consumed simultaneously by multiple threads?

**Comment by stephentoub** [comment]
> Is it expected from functions like Directory.EnumerateFiles to return an iterator that can be consumed simultaneously by multiple threads?

By "simultaneously", do you mean multiple thread in parallel all accessing the same enumerator without locks?  That's definitely not supported.  But it should be valid to do:
```C#
IEnumerable<T> e = ...;
e.MoveNext();
Use(e.Current);
Task.Run(() =>
{
    e.MoveNext();
    Use(e.Current);
});
```
such that the same enumerator is used serially from different threads.  This is actually common with code like:
```C#
Parallel.ForEach(Directory.EnumerateFiles(...), file =>
{
    Use(file);
});
```
such that different threads will all try to use the same enumerator, but they access MoveNext/Current under a lock so that access to the enumerator is serialized.

That needs to work.  I can't tell from your comment if you're saying it does or doesn't.

**Comment by tmds** [comment]
> By "simultaneously", do you mean multiple thread in parallel all accessing the same enumerator without locks?

Yes, multiple threads without locking.

> I can't tell from your comment if you're saying it does or doesn't.

The locked approach works fine.

In the readdir case, the native code does a memcpy:

https://github.com/dotnet/corefx/blob/920196986a7bd75826d810c105fab7c7c0cb517d/src/Native/Unix/System.Native/pal_io.c#L400

I don't think this copy is needed. We can use the data from the native buffer held by DIR, instead of copying into the stackalloced buffer.
wdyt?

**Comment by stephentoub** [comment]
> I don't think this copy is needed. We can use the data from the native buffer held by DIR, instead of copying into the stackalloced buffer. wdyt?

Can you elaborate?  Why isn't it necessary?  What would you do instead?

**Comment by tmds** [comment]
The value returned by readdir is valid till the next call to readdir/closedir. So we don't have to copy it over to keep it in scope.
`entry = result` should be enough.

If someone tries to use this 'multi-threaded' things will go wrong. That is already the case for the current code. Maybe we can add some checks for this, if desired.
