### ISSUE TITLE
HttpBinding HttpClientCredentialType.Windows IIS10 - Core 2.0

### ISSUE THREAD

**Issue by cgountanis** [dotnet/corefx#25376]
Trying to connect to SSRS Execution. Works fine on my development machine, soon as I move to IIS I get errors with the same exact remote SSRS server. Any tips tricks, most of the help from Google is the old way of doing it with XML file configurations. What really gets me is that it works from my development machine using IISExpress, why not on a TEST Server using IIS?

AppPool No Managed Code

The rest of the Core 2.0 MVC application works perfectly. Why would it work remote on my machine via VPN then throw error like that on TEST server which is on same network? I really think this has something to do with IIS.

```
basicHttpBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Windows;

var serviceSoapClient = new ReportExecutionServiceSoapClient(basicHttpBinding, new EndpointAddress($"{model.ReportServerUrl}/ReportExecution2005.asmx"));

serviceSoapClient.ClientCredentials.Windows.AllowedImpersonationLevel = System.Security.Principal.TokenImpersonationLevel.Impersonation;

serviceSoapClient.ClientCredentials.Windows.ClientCredential = (NetworkCredential)(new NetworkCredential() { UserName = model.Username, Password = model.Password, Domain = model.Domain });
```

Error:

System.AggregateException: One or more errors occurred. (The HTTP request is unauthorized with client authentication scheme 'Negotiate'. The authentication header received from the server was ''.) ---> System.ServiceModel.Security.MessageSecurityException: The HTTP request is unauthorized with client authentication scheme 'Negotiate'. The authentication header received from the server was ''.

https://github.com/aspnet/Hosting/issues/1276

**Comment by karelz** [comment]
Looks like problem with IIS configuration - if it is specific to ASP.NET Core 2.0, I would recommend to ask them. Or dig deeper into IIS.
Does not seem to be related to BCL in .NET Core 2.0, closing.

**Comment by karelz** [comment]
OK, looking at @Tratcher's comment https://github.com/aspnet/Hosting/issues/1276#issuecomment-345742100 - WCF lives in https://github.com/dotnet/wcf, not in CoreFX.

**Comment by cgountanis** [comment]
I still feel this is a hosting issue personally. Works locally, works connecting remote with IISExpress, no worky in IIS 10 with the Core Hosting installed. I will move to that forum I guess :)

**Comment by cgountanis** [comment]
Moved to https://github.com/dotnet/wcf/issues/2398

**Comment by cgountanis** [comment]
https://stackoverflow.com/questions/47416234/core-2-mvc-wcf-to-ssrs-execution-project-needs-administrator-iis-apppool-to-wo
