### ISSUE TITLE
Manually run CoreFX netstandard tests against Mono

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#25378]
Get an idea of the pass rate and any complications in doing this.

**Comment by danmosemsft** [comment]
I'm going to estimate quite large as I imagine there will be many failures to go through and understand.

**Comment by akoeplinger** [comment]
When you say "CoreFX netstandard tests" which ones do you mean?

**Comment by weshaggard** [comment]
@danmosemsft is this something you are still targeting for 2.1?

**Comment by danmosemsft** [comment]
No, it's not on the 2.1 schedule.
