### ISSUE TITLE
Update man pages documentation for Linux developers

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#25381]
The `man` pages installed by .NET Core have outdated content eg relating to project.json and commands that no longer exist.  Clean this up and make it more useful: `man` pages are where Unix users start.

**Comment by ViktorHofer** [comment]
Also update MAN pages which was discussed in @eerhardt s talk.

**Comment by danmosemsft** [comment]
The man pages referred to are those you get with the CLI, which are quite different. That's what I had actually meant, but I'll create a new issue.

**Comment by danmosemsft** [comment]
@ViktorHofer thanks, that's what this should have been. fixed.

**Comment by eerhardt** [comment]
I see this issue's Milestone set to `Future`, but it is in a 2.1 "Epic".  That seems contradictory to me.

**Comment by eerhardt** [comment]
See also https://github.com/dotnet/docs/issues/2791

**Comment by omajid** [comment]
This isssue is also tracked (well, sort of) in the cli repo: https://github.com/dotnet/cli/issues/7291

**Comment by danmosemsft** [comment]
@eerhardt is 3 dev days a reasonable time to do a good job of this?

**Comment by omajid** [comment]
I can help out with implementing this. But I don't know if there was consensus on how this should be fixed.

**Comment by danmosemsft** [comment]
Actually I think this is suffiicently tracked by the CLI and docs tasks.

**Comment by danmosemsft** [comment]
@omajid your help would be welcome - perhaps you can nudge the other issues?

**Comment by omajid** [comment]
Yup, I will continue nudging it until I see some movement. I just dont know when that will be.
