### ISSUE TITLE
Only run Debug corefx official builds and tests runs weekly

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#25382]
We don't need to do official builds for both release and debug multiple times daily. Our general official builds should be defaulted to Release but we should enable a weekly Debug build for extra test validation. 

@danmosemsft any preference on which day of the week so you can pay extra attention to the test results?

**Comment by stephentoub** [comment]
> any preference on which day of the week so you can pay extra attention to the test results?

Maybe Sunday night?

**Comment by weshaggard** [comment]
We can't do this automatically without core-eng#2176.
For 2.1 we will have to manually queue builds periodically.

**Comment by weshaggard** [comment]
For 2.1 here is a manual 2.1 Debug build:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180314.07

For comparision here is the Release build test results:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180314.06

@danmosemsft could you please as someone to compare the results to ensure we don't have any meaningful differences?

**Comment by danmosemsft** [comment]
I went through them and nothing looks chk specific., I made sure there were issues for everything.

Can you set this up to run weekly now?

**Comment by danmosemsft** [comment]
And if you do, how will we avoid missing them in all the release builds?

**Comment by weshaggard** [comment]
>Can you set this up to run weekly now?

Not yet we are still dependent on something dotnet/core-eng#2176 which isn't funded.

**Comment by ViktorHofer** [comment]
This can probably be done after migration to Azure DevOps is done. @safern I'll assign you, I hope that's fine.

**Comment by ViktorHofer** [comment]
Do we still want that? The additional legs in official builds aren't much to pay, I wouldn't remove the Debug legs unless there's a strong reason to do so.

**Comment by danmosemsft** [comment]
@viktorhofer I have no opinion. If they are not distracting and we aren't asked to free machines I guess it should be OK to keep them.

**Comment by ViktorHofer** [comment]
OK great, let's close this until somebody asks.

**Comment by safern** [comment]
> I wouldn't remove the Debug legs unless there's a strong reason to do so.

You can't remove them, because there are no Debug legs now in official builds :smile: -- I  think this issue is to add 1 weekly run for Debug builds of our official matrix.

**Comment by danmosemsft** [comment]
Oh! We should certainly have regular runs at some frequency.

**Comment by ViktorHofer** [comment]
Ok 😀

**Comment by safern** [comment]
I think to do this periodically we would need to create a new build def and do some plumbing on the yml files. Shouldn't take long, but don't have bandwidth now, I'll probably work on it in 5 weeks or so :smile:

**Comment by ViktorHofer** [comment]
Closing as we just restructured our test matrix and don't run tests anymore in official builds. I believe disabling additional configurations isn't necessary anymore as we already saved resources.

**Comment by ViktorHofer** [comment]
(feel free to reopen if you disagree)
