### ISSUE TITLE
TimeZoneInfoTests.TestNames fails on Linux

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#2539]
```
Starting:    System.Runtime.Tests
12:14:54    TimeZoneInfoTests.TestNames [FAIL]
12:14:54       Assert.NotEqual() Failure
12:14:54       Expected: Not "UTC"
12:14:54       Actual:   "UTC"
12:14:54       Stack Trace:
12:14:54 Warning: Libya time zone is not exist in this machine
12:14:55             at TimeZoneInfoTests.TestNames()
```
cc @eerhardt

**Comment by mj1856** [comment]
The test is:

```csharp
TimeZoneInfo local = TimeZoneInfo.Local;
TimeZoneInfo utc = TimeZoneInfo.Utc;
Assert.NotEqual(local.DaylightName, utc.DaylightName);
Assert.NotEqual(local.DisplayName, utc.DisplayName);
Assert.NotEqual(local.StandardName, utc.StandardName);
```

This doesn't seem like a valid test, as there's no guarantee that the local time zone isn't set to UTC.   Indeed, most cloud & CI environments are *likely* to have UTC as the local time zone setting.

**Comment by justinvp** [comment]
@eerhardt hope you don't mind, but I went ahead and submitted a PR for this: #2543 since it's currently causing CI failures.

**Comment by eerhardt** [comment]
No problem.  I was trying to figure out how this test passed before my changes, and why it passes in Windows.  It must be because the Windows machines aren't set to UTC.  And before my changes the "TimeZoneInfo.Local" was returning fake information for the names, causing the `Assert.NotEquals` to pass.

**Comment by eerhardt** [comment]
Looks like it passes on Windows because

```C#
Console.WriteLine(utc.DaylightName);
Console.WriteLine(utc.DisplayName);
Console.WriteLine(utc.StandardName);
```
outputs

```
UTC
UTC
UTC
```

And 
```C#
Console.WriteLine(local.DaylightName);
Console.WriteLine(local.DisplayName);
Console.WriteLine(local.StandardName);
```
outputs

```
Coordinated Universal Time
(UTC) Coordinated Universal Time
Coordinated Universal Time
```

**Comment by eerhardt** [comment]
It passed before my change because TimeZoneInfo.Local was implemented like this:
```C#
 // the data returned from the PAL is completely bogus; return a dummy entry
return CreateCustomTimeZone(c_localId, TimeSpan.Zero, c_localId, c_localId);
```
So all those properties were running "Local" all the time.

**Comment by nguerrera** [comment]
I missed that this was causing failures in CI before restarting a bunch of jobs after an issue we had with our myget feed. How is it that this got through CI in the first place? Do some our build machines have local time = UTC while others don't?

**Comment by eerhardt** [comment]
> How is it that this got through CI in the first place?

The change that broke this was made to coreclr.  Do we run corefx tests against every checkin of coreclr?

**Comment by nguerrera** [comment]
Ah. I see.

**Comment by nguerrera** [comment]
cc @ellismg We should think about how to validate such changes to mscorlib as they happen on the coreclr side.

**Comment by ellismg** [comment]
I think the only tenable solution is to move away from the "always roll to latest automatically" policy that we have for consuming mscorlib.  Ideally, coreclr would produce a runtime package, uploaded to some feed.  CoreFX would consume it via a fixed version reference.  This would let us control when we move to a new version.  I think we basically do this today for the windows side of things, but on Linux we still pick up the latest coreclr and mscorlib from CI during a corefx test run.
