### ISSUE TITLE
PerformanceCounterLib is not fully thread safe

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#25403]
PerformanceCounterLib instances are stored in a static table such that there's a single instance for a machine/LCID combination. As such there is an expectation that operations are thread safe (since to the caller they appear to be static operations)

The code attempts to achieve this but it appears to have holes, eg _customCategoryTable, a HashTable, is modified [here ](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs#L706 )without protection against concurrent write at this same location (or in other places).

Make a pss through PerformanceCounterLib to make it thread safe through its static members.

https://github.com/dotnet/corefx/pull/25401

**Comment by MarcoRossignoli** [comment]
I can try to fix it, i found one test [here](https://github.com/MarcoRossignoli/corefx/blob/9f3438c6ee37d243de2c7ac5ae98f18d408124c0/src/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs#L247) where without lock after some seconds "Category does not exist." exception raise.
