### ISSUE TITLE
Invalid System.Numerics.Vector Elements in Property Preview

### ISSUE THREAD

**Issue by zcanann** [dotnet/corefx#25404]
![ones](https://user-images.githubusercontent.com/5906208/33058114-df92c7a8-ce42-11e7-9f3e-56cfa4f7ffbe.jpg)

Mousing over an Int32 vector always shows the last 4 elements as 0, even though Vector<Int32>.Count is 8. The same logic holds for other data types (ie the last 16 bytes are zero'd out).

In the example above, even the static Vector<Int32>.Ones contains elements with the value 0. However, after copying the values over to an array, they are all 1s.

This makes debugging pretty challenging. Hopefully I'm not missing something here.

**Comment by stephentoub** [comment]
Thanks. Dup of https://github.com/dotnet/coreclr/issues/10148.
