### ISSUE TITLE
Add implicit cast from string to ReadOnlySpan<char>

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#25413]
Proposal:
```C#
public class String
{
    public static implicit operator ReadOnlySpan<char>(string value) =>
        value != null ? new ReadOnlySpan<char>(ref value.GetRawStringData(), value.Length) : default;
    ...
}
```

**Comment by stephentoub** [comment]
cc: @ahsonkhan, @KrzysztofCwalina, @jkotas

**Comment by karelz** [comment]
cc @GrabYourPitchforks

**Comment by karelz** [comment]
BTW: This was OK'd in the API review, waiting just for experts to raise potential concerns or agree ... it is considered conditionally approved.

**Comment by jkotas** [comment]
I would love to see C# compiler to construct ReadOnlySpan for constant strings directly when there is ReadOnlySpan<char> receiver. It would save us from having to allocate string objects on GC heap for things like format strings when the Format method takes Span. I assume that this implicit conversion is not going us to prevent from doing that. cc @VSadov @jaredpar 

Otherwise looks good to me.

> public static implicit operator ReadOnlySpan<char>(string value) => value.AsReadOnlySpan();

This impl would throw exception for null string. Should this rather be:

```
   public static implicit operator ReadOnlySpan<char>(string value) => (value != null) ? new ReadOnlySpan<char>(ref value.GetRawStringData(), value.Length) : default;
```

**Comment by stephentoub** [comment]
> This impl would throw exception for null string. Should this rather be:

Yup

**Comment by stephentoub** [comment]
> I would love to see C# compiler to construct ReadOnlySpan for constant strings directly when there is ReadOnlySpan receiver

+1

**Comment by VSadov** [comment]
>  I assume that this implicit conversion is not going us to prevent from doing that.
No, that is not a problem. At the end it is a special method taking a literal as an argument. We can detect that and emit something else. 

Not sure how to get to the data having a string token. I assume there are ways...

**Comment by jkotas** [comment]
There would not be string token involved. It would be constant data in the data section.

**Comment by VSadov** [comment]
Ideally there would be a helper that takes a string token or something like that - to avoid directly dealing with pointers, which us formally unsafe.  
Will need to figure out how to do this.

**Comment by VSadov** [comment]
We can also do what we do for array literals.
That could lead to storing same string twice - as a string and as a blob. Not a big problem IMO.

**Comment by jkotas** [comment]
You are dealing with pointers for stackalloc, ... .

If you need to something safe, it means that we either need new IL instruction (non-starter) or the JIT needs to pattern match it: You would emit the regular ldstd + conversion to ReadOnlySpan, the JIT would pattern match it and skipped allocating the intermediate string literal. Basically, the helper that you are looking for is the API proposed by this issue.

**Comment by VSadov** [comment]
We may also need a similar solution for the  `new ReadOnlySpan<int>{1,2,3,4}`, or whatever syntax will be for that, and possibly for the indexable fixed size buffers too. - No need to design it right here. Just saying that it should be possible. As a last resort there are pointers...
