### ISSUE TITLE
Add PipeOptions.CurrentUserOnly option

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#25427]
Systems that use named pipes often want to try to lock down access, validating that only the user that created the server is able to connect to it, and similarly validating that the client is connecting to a server it expects.

On Windows this can be done with a complicated dance involving ACLs.  On Unix where our PipeStream is built on top of domain sockets, it can be done with a complicated dance involving creating a directory that's permissioned just to the user, creating the domain socket on a path in there, etc.

As we've seen several systems want to do this, including for example Roslyn with its compiler server, we should expose an option and handle the difficulties of this in one place so that customers of NamedPipeServer/ClientStream don't need to reinvent the wheel each time.

Proposal:
```C#
namespace System.IO.Pipes
{
    [Flags]
    public enum PipeOptions // existing type
    {
        ...
        CurrentUserOnly = unchecked((int)0x20000000) // new value proposed
    }
}
```
(Note that today the implementation on Windows just passes PipeOptions in by value to CreateNamedPipe.  We would strip off this new value if it was set before doing so, but for extra good measure we should also choose a value that's not currently accepted by CreateNamedPipe.)

[edit by @danmosemsft: this flag will cause a check that the pipe is owned by the same user with the same elevation level ]

**Comment by danmosemsft** [comment]
In the persistent process reuse scenario it is also necessary to verify that the other end has the same elevation level (on Windows..presumably sudoness on Unix). Should this mechanism also help with that?

**Comment by stephentoub** [comment]
> Should this mechanism also help with that?

Yes, whatever mechanism we settle on, it should cover both.

**Comment by danmosemsft** [comment]
@pjanotti @jaredpar any comments or is this ready for API review?

**Comment by jaredpar** [comment]
Read for review IMHO.

**Comment by danmosemsft** [comment]
@pjanotti I marked ready for review. Feel free to change -- otherwise, let's talk about this at tomorrow's meeting.

@stephentoub I added a line to your top post for review purposes, hopefully accurate.

**Comment by stephentoub** [comment]
> I added a line to your top post for review purposes, hopefully accurate

@danmosemsft, what did you add?

**Comment by danmosemsft** [comment]
Oops, didn't hit the button. Done.

**Comment by stephentoub** [comment]
> Oops, didn't hit the button. Done.

:smile:

**Comment by karelz** [comment]
FYI: The API review discussion was recorded - see https://youtu.be/9F_NsviGT0Y?t=2670 (5 min duration)

**Comment by danmosemsft** [comment]
On Windows this is currently achieved by MSBuild and presumably Roslyn by setting ACL's on the pipe using the PipeSecurity object -- which we don't have on the constructor anymore (#24040).

Here's links to the code:

At the server end, MSBuild sets appropriate ACL on the pipe to limit who can connect to it: https://github.com/Microsoft/msbuild/blob/63d5e628f9b87a3faf33a8ac061c5c17fcf7f6b3/src/Shared/NodeEndpointOutOfProcBase.cs#L221

similar for Roslyn
https://github.com/dotnet/roslyn/blob/14aed138a01c448143b9acf0fe77a662e3dfe2f4/src/Compilers/Server/VBCSCompiler/NamedPipeClientConnection.cs#L80


At the client end, MSBuild checks the owner of the pipe is the one it expects:
https://github.com/Microsoft/msbuild/blob/0a47f62a138b32cb406d058fe7f49c0494aa6c84/src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs#L360
I don't see an explicit check for elevation level -- is that included in this owner check?

Again Roslyn is very similar
https://github.com/dotnet/roslyn/blob/c7a465fabaf688affbd5897d7348431eeb2059b5/src/Compilers/Shared/BuildServerConnection.cs#L451

The work here is to enable users to pass PipeOptions.CurrentUserOnly to their NamedPipeClientStream or NamedPipeServerStream and all this security above happens automatically for them on Windows and Unix.

It looks like @khyperia made a start on Unix equivalent checks:

https://github.com/dotnet/roslyn/blob/c7a465fabaf688affbd5897d7348431eeb2059b5/src/Compilers/Shared/BuildServerConnection.cs#L490
and
https://github.com/dotnet/roslyn/blob/14aed138a01c448143b9acf0fe77a662e3dfe2f4/src/Compilers/Server/VBCSCompiler/NamedPipeClientConnection.cs#L153

It looks like @khyperia left so you might want to check with @jaredpar on status?

**Comment by rynowak** [comment]
@pjanotti - what's the state of this now that the PR is merged? Ready for us to start using?

**Comment by pjanotti** [comment]
This is done via https://github.com/dotnet/corefx/pull/26395 and 2 other smaller complementary PRs: https://github.com/dotnet/corefx/pull/27463 and https://github.com/dotnet/corefx/pull/27573.

@rynowak this is ready to be used in 2.1

**Comment by rynowak** [comment]
Cool beans! Thanks 👍

**Comment by tylerl0706** [comment]
@stephentoub I'm not quite on 2.1 yet so I can't use the new hotness... would you mind elaborating on how you did this:

> On Unix where our PipeStream is built on top of domain sockets,
it can be done with a complicated dance involving creating a directory that's permissioned just to the user,
creating the domain socket on a path in there, etc.

I saw that passing an absolute path into NamedPipeServerStream is possible but also in 2.1 :(
https://github.com/dotnet/corefx/pull/27826

**Comment by stephentoub** [comment]
> would you mind elaborating on how you did this

That would be in the implementation rather than something you can do on top of the API.  We also ended up not doing that, as it turned out not to be necessary to implement this.
