### ISSUE TITLE
SslApplicationProtocols.ToString() shouldn't allocate for known protocols

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#25432]
For http/1.1 and h2 it shouldn't allocate a new string https://github.com/dotnet/corefx/blob/1d95739cf905df31685fed2451aedeec95880ade/src/System.Net.Security/src/System/Net/Security/SslApplicationProtocol.cs#L97. Those 2 should be hardcoded to return constants.

/cc @Priya91 @stephentoub @karelz

**Comment by stephentoub** [comment]
Makes sense. @davidfowl, want to submit a PR?

**Comment by davidfowl** [comment]
Sure!
