### ISSUE TITLE
Proposal: BitConverter.ToString to roundtrip with GetBytes(string)

### ISSUE THREAD

**Issue by kasper3** [dotnet/corefx#25441]
# Rationale

There are three solutions presented for BitConverter.ToString roundtriping back to byte[]: https://stackoverflow.com/questions/1230303/bitconverter-tostring-in-reverse

That is some boilerplate code which consumer code has to carry.

# Proposal

BitConverter has the following GetBytes overloads:

```c#
        public static byte[] GetBytes(bool value)
        public static byte[] GetBytes(char value)
        public static byte[] GetBytes(double value)
        public static byte[] GetBytes(short value)
        public static byte[] GetBytes(int value)
        public static byte[] GetBytes(long value)
        public static byte[] GetBytes(float value)
        [System.CLSCompliantAttribute(false)]
        public static byte[] GetBytes(ushort value)
        [System.CLSCompliantAttribute(false)]
        public static byte[] GetBytes(uint value)
        [System.CLSCompliantAttribute(false)]
        public static byte[] GetBytes(ulong value)
```

In addition to these, please consider:

```c#
        public static byte[] GetBytes(string value)
        public static byte[] GetBytes(ReadOnlySpan<char> value)
```

# Usage

```c#
var expected = new byte[100];

var random = new Random();
random.NextBytes(expected);

var stringRepresentation = BitConverter.ToString(expected);
var actual1 = BitConverter.GetBytes(stringRepresentation);

Assert.Equal(expected, actual1);

ReadOnlySpan<char> spanRepresentation = stringRepresentation;

var actual2 = BitConverter.GetBytes(spanRepresentation);

Assert.Equal(expected, actual2);
Assert.Equal(actual1, actual2);
```

**Comment by Clockwork-Muse** [comment]
...the current way to do this is via `Encoding.UTF8.GetBytes(string)`, which is probably why it's not in there currently - strings really need to be encoded for the bytes to make any sense.

**Comment by jkotas** [comment]
@Clockwork-Muse comment is spot on. The methods to do this are on the Encoding class. The methods on Encoding class let you choose which encoding you would like to use, and also give you control over the buffer lifetime - the BitConverter.GetBytes() method above allocate a new buffer for you every time that tends to lead to performance issues.
