### ISSUE TITLE
CMS:  enable adding certificates and unsigned attributes post-signing

### ISSUE THREAD

**Issue by dtivel** [dotnet/corefx#25449]
CMS permits post-signing changes to `SignedData.certificates` and `SignerInfo.unsignedAttrs` collections; however, `System.Security.Cryptography.Pkcs.SignedCms.Certificates` and `System.Security.Cryptography.Pkcs.SignerInfo.UnsignedAttributes` properties return copies of the data and mutations of these collections are not persisted back to the root `SignedCms` object.

Example 1:  to an existing `SignerInfo` object attempt to add a timestamp per [RFC 3161 appendix A](https://tools.ietf.org/html/rfc3161#page-20).
Example 2:  to an existing `SignedCms` object attempt to add additional certificates found during a chain building for the timestamp authority's certificate in example 1.  (According to RFC 3161, if `certReq` is TRUE in the timestamp request, the TSA is only obliged to return in its response the signing certificate, not all certificates in a complete chain for the signing certificate.)

While this issue was discovered on .NET Framework, it is relevant to both .NET Framework and .NET Core's #14197 and #24524 and NuGet package signing's cross-platform plan.  NuGet has a Windows-only workaround (P/Invoking) and a cross-platform workaround too, but the cross-platform workaround is a hack and a blocker for other features (like ECDSA support).

One option is to introduce add/remove helper methods on `SignedCms` and `SignerInfo` classes.

CC @bartonjs, @rido-min

EDIT by @krwq:

API proposal:

```diff
public class SignerInfo {
+  void AddUnsignedAttribute(AsnEncodedData unsignedAttribute);
+  void RemoveUnsignedAttribute(AsnEncodedData unsignedAttribute);
}

public class SignedCms {
+  void AddCertificate(X509Certificate2 certificate);
+  void RemoveCertificate(X509Certificate2 certificate);
}
```

**Comment by krwq** [comment]
Talked with @bartonjs offline and we will go with this:

```diff
public class SignerInfo {
+  void AddUnsignedAttribute(Oid oid, AsnEncodedData encodedData);
+  void RemoveUnsignedAttribute(Oid oid, AsnEncodedData encodedData);
}

public class SignedCms {
+  void AddCertificate(X509Certificate2 certificate);
+  void RemoveCertificate(X509Certificate2 certificate);
}
```

**Comment by bartonjs** [comment]
@krwq AsnEncodedData has the oid as a property already (AsnEncodedData.Oid).

AddUnsignedAttribute(AsnEncodedData unsignedAttribute) and RemoveUnsignedAttribute(AsnEncodedData unsignedAttribute) should be sufficient.

And maybe Remove should return a bool indicating whether or not it removed anything.  (I'm not sure if we've landed on a consistent place for that or not across the framework)

**Comment by krwq** [comment]
@bartonjs for RemoveCounterSignature we are throwing the exception - I will follow this pattern and let's see if there is different opinion on that during the API review

**Comment by krwq** [comment]
Moving relevant parts of [comment conversation](https://github.com/dotnet/corefx/pull/29408#discussion_r185072407) from PR here:

*From @bartonjs*

> Our CounterSigner does add a new attribute set per counter-signer, to maintain parity with what NetFx was already doing.
> 
> Please try to find some other frameworks and get an idea of what they would do here.
> 
> It seems weird that if someone prepares them ahead of time we will build
> 
> ```
> UnsignedAttributes
>     AttributeSet
>         oid
>         values
>             value0
>             value1
> ```
> 
> But that if they do it individually with AddUnsignedAttribute it becomes
> 
> ```
> 
> UnsignedAttributes
>     AttributeSet
>         oid
>         values
>             value0
>     AttributeSet
>         oid
>         values
>             value1
> ```

*From @krwq*

> @bartonjs Bouncy Castle allows setting Asn1Set directly in AttributeTable which allows both. In OpenSSL you also provide the whole attribute. I think only counter signatures are expected to be duplicate.
> 
> Either way we got 3 options:
> - leave as is, pick whichever convention and if we got request with a valid scenario we add bool overload
> - add a bool overload (argument might be confusing) - we might want to rename API to something like AddAttributeValue and call bool something like `mergeWithExistingAttribute` to make it less confusing
> - come back to my previous design which take CryptographicAttributeObject
> 
> I think first and second option sound reasonably good - I'm not convinced bool will be super useful but we can add it just in case. Thoughts?

**Comment by krwq** [comment]
We talked offline and will have API as is but output representation will be more compact (merge by default)

**Comment by terrajobst** [comment]
Looks "good" :-)

**Comment by bartonjs** [comment]
Didn't make it into 2.2, already completed for 3.0

**Comment by heng-liu** [comment]
Hi @bartonjs , may I know if AddUnsignedAttribute() works for CounterSignerInfos elements?
I countersigned successfully(checked _signedCms.SignerInfos[0].CounterSignerInfos[0] is not null), but when I tried to add a timestamp to the countersignature as an unsignedAttribute, by using: _signedCms.SignerInfos[0].CounterSignerInfos[0].AddUnsignedAttribute(unsignedAttribute);

I encountered an exception of "System.Security.Cryptography.CryptographicException: 'Cannot find the original signer.'"

Not sure if it's not supported or I used it in a wrong way. Can you pls advise?  Thanks!

**Comment by krwq** [comment]
@heng-liu if I remember correctly counter signatures are actually attributes on the original signer so presumably adding unsigned attributes to a counter-signer would be equivalent to adding an unsigned attribute to the original signer (with some extra info suggesting that it actually is related to counter signature and not original signer).

The easiest way to check all supported scenarios would be to review tests added with this feature:
https://github.com/dotnet/corefx/pull/29408/files#diff-c1d9902de080ccd6d367099964623138R18

**Comment by heng-liu** [comment]
@krwq Thanks for your help!

**Comment by heng-liu** [comment]
Hi @krwq , I checked the tests added with this feature, and there is no SignerInfos[0].CounterSignerInfos[0].AddUnsignedAttribute examples. 
So we can only use: **SignerInfos[i].AddUnsignedAttribute**, 
but **SignerInfos[i].CounterSignerInfos[j].AddUnsignedAttribute** is not supported, right?

Since CounterSignerInfos[j] is also a SignerInfo class, I thought it could use the method AddUnsignedAttribute. But actually it could not. May I know is it by design? Thanks!

**Comment by bartonjs** [comment]
I don't know that it's "by design", but it may be a limitation of the Win32 CMS library that we're built on top of.

It feels like it should probably work.  If it works on macOS/Linux then that's probably cause to use some heroic workarounds on Windows to enable the scenario.

**Comment by krwq** [comment]
Second look and I think we should support both unsigned and theoretically also signed attributes although I'm not sure yet how would that work.

@heng-liu it might be worth checking Linux implementation per @bartonjs's suggestion

**Comment by krwq** [comment]
@heng-liu I've created the issue about this - currently to unblock yourself you'd need to decode counter-signature unsigned attribute and manually encode timestamp in there (then you can remove original counter-signature and add it back with modified one)

**Comment by heng-liu** [comment]
@bartonjs and @krwq Thanks :) I tried SignerInfos[i].CounterSignerInfos[j].AddUnsignedAttribute on Linux and Windows. And they both failed for the same reason:  System.Security.Cryptography.CryptographicException : Cannot find the original signer.

When I debug on windows for netcoreapp3.0, it failed at here:  https://github.com/dotnet/corefx/blob/release/3.0-preview9/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignerInfo.cs#L125-L129

**Comment by heng-liu** [comment]
Hi @krwq, I could not find any decode, encode method for SignerInfo and CryptographicAttributeObject. And the CryptMsgOpenToDecode function only works for windows platform.
May I know if the workaround mentioned above works for both Linux and Windows? If yes, can you pls tell me more details?Thanks!

**Comment by krwq** [comment]
@heng-liu unfortunatelly ASN.1 reader/writer is not currently public but you can copy it to your project (or call it by reflection)...

**Comment by danmosemsft** [comment]
Of course  if you call internals via reflection you may be broken in a future release

**Comment by krwq** [comment]
@danmosemsft this is just to unblock herself - better solution would be to send a patch to https://github.com/dotnet/corefx/issues/41158 and then use nightly bits and perhaps request to include in 3.1 (if we will have one)

**Comment by heng-liu** [comment]
Hi @krwq , I tested 6 test cases which calls _signedCms.SignerInfos[0].CounterSignerInfos[0].AddUnsignedAttribute(unsignedAttribute);

And there're two different results:
1.  "System.Exception : Cannot find the original signer." is thrown, and failed to add the unsignedAttribute to the CounterSingerInfo[j]
2.  no exception is thrown,  but the unsignedAttribute is not added to the CounterSingerInfo[j]

By the way, I tested on both Windows and Linux for netcoreapp3.0. The results are exactly the same.

I haven't figured out why there're two different results. But none of them succeeded in adding unsignedAttribute to a CounterSingerInfo.
 May I know if you can repro on Windows and Linux platform? Thanks!

If you can repro as well,  then I think we need a workaround for both Windows and Linux.

**Comment by heng-liu** [comment]
@krwq For the ASN.1 reader/writer you mentioned above, is it from : System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Asn1/  ? Thanks~

**Comment by bartonjs** [comment]
The AsnReader and AsnWriter types are available as an experimental package (e.g. https://dotnet.myget.org/feed/dotnet-corefxlab/package/nuget/System.Security.Cryptography.Asn1.Experimental/0.1.1-e190917-2).  Be aware that due to a bad versioning change in January that the "newest" package is not actually the newest.

**Comment by heng-liu** [comment]
Thanks! @bartonjs

**Comment by heng-liu** [comment]
> We talked offline and will have API as is but output representation will be more compact (merge by default)

Hi @krwq, may I know if AddUnsignedAttribute will do the merge according to the Oid for both signers and counter signers? So it impossible for any signers nor counter signers to have multiple unsignedAttributes with the same Oid, right? Thanks!

**Comment by bartonjs** [comment]
>  So it impossible for any signers nor counter signers to have multiple unsignedAttributes with the same Oid, right?

That depends on if you are reading, or writing.

The CMS file format allows for

```
* UnsignedAttributes
    * Attr0 (Oid 0.0)
        * AttrValue0
    * Attr1 (Oid 0.0)
        * AttrValue1
    * Attr2 (Oid 0.1)
        * OtherAttrValue0

```

and also

```
* UnsignedAttributes
    * Attr0 (Oid 0.0)
        * AttrValue0
        * AttrValue1
    * Attr1 (Oid 0.1)
        * OtherAttrValue0
```

When reading, if the data is presented in the split form (top) you'll see two different collections.  When you call add, we always merge like the latter form. (I don't remember what happens if you read the top and you write AttrValue2... it's either all 3 are squished into one, or there's two in one and one in the other).

Both counter-signers and primary-signers should behave in the same way.

We don't enforce whether or not any attribute says "you can only have this once", except for attributes which change how SignedCms itself functions.

**Comment by heng-liu** [comment]
Thanks! @bartonjs

**Comment by krwq** [comment]
Exactly as @bartonjs wrote. When adding we always merge with the first attribute with the same Oid.
In order to force the latter structure you need to remove all attributes and add them back but we won't change existing structure.

The logic is the same for both signers and counter-signers.

**Comment by heng-liu** [comment]
Thanks for your additional explanation @krwq
