### ISSUE TITLE
Should remove CheckInvalidPathChars

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#25450]
The check for invalid path chars on the majority of System.IO APIs aggregates to a significant cost in real world performance metrics. There is little benefit to premptively checking- we should start by removing the check from everything but Path.GetFullPath().

http://source.dot.net/#System.Private.CoreLib/shared/System/IO/PathInternal.cs,486d9b8f9e6ecd64,references

We need to remove checks in CoreCLR (where Path lives) and System.IO.FileSystem.

**Comment by danmosemsft** [comment]
@Anipik work here is delete all use of CheckInvalidPathChars except for in GetFullPath, and update/remove the tests so they continue to pass.

**Comment by danmosemsft** [comment]
Note the work is in both CoreFX and CoreCLR

**Comment by JeremyKuhne** [comment]
With further discussion with @pjanotti we've decided that removing the check from `Path.GetFullPath` should also be done. I didn't add it to the initial description as I wanted to spend some time discussing it with him.

We still expose `Path.GetInvalidPathChars()` and `GetInvalidFileNameChars()` which provide a way for people to check that characters aren't generally friendly for paths on the current system. This set of characters is not accurate for all path types (it is over aggressive on Windows and does not account for NTFS/FAT mounted volumes on Unix) and can actually block access to some resources on Windows as we call Path.GetFullPath in many places.
