### ISSUE TITLE
SqlConnection should NOT be sealed (nothing should be sealed, really)

### ISSUE THREAD

**Issue by JCKodel** [dotnet/corefx#25469]
Imagine the following scenario:

For security reasons (or performance, or policies, or whatever), I want to have a readonly sql connection to some features and a read/write connection for others.

What's the most easy way to accomplish this? Using .net core dependency injection:

```
services.AddScoped(_ => new ReadOnlySqlConnection(Configuration.GetConnectionString("ReadOnlySqlConnectionStringWithAReadOnlyUser")));
services.AddScoped(_ => new ReadWriteSqlConnection(Configuration.GetConnectionString("ReadWriteSqlConnectionStringWithAReadOnlyUser")));
```

Then, I could implement a simple inheritance to resolve what type of connection I want:

```
public class ReadOnlySqlConnection : SqlConnection
{
}

public class ReadWriteSqlConnection : SqlConnection
{
}
```

I could even create a specialized SqlCommand to throw exceptions on write methods while using a ReadOnly connection (overriding ExecuteNonQuery to throw an exception). So I could make a specialized method on it:

```
public class ReadOnlySqlConnection : SqlConnection
{
    public ReadOnlySqlCommand CreateCommand(...)
    {
        ...
    }
}

public class ReadWriteSqlConnection : SqlConnection
{
    public ReadWriteSqlCommand CreateCommand(...)
    {
        ...
    }
}
```

Sealing classes is bad for the extensible nature of .net :(

I KNOW there are other ways to doing this... but, why seal anything, really? Let's us extend all we want \O/

**Comment by Clockwork-Muse** [comment]
[Some reasons are mentioned in this answer](https://stackoverflow.com/a/6389669/812837) (and the linked post), but the short answer is that allowing subclassing makes any user of that type have a problem.  For instance, if I declared my own program to accept a `SqlConnection`, I'd probably expect that I could both read and write with it...

If you want something to extend, you're probably looking at `DbConnection` (or maybe the interface, `IDbConnection`).

**Comment by mikedn** [comment]
> For instance, if I declared my own program to accept a SqlConnection, I'd probably expect that I could both read and write with it...

That expectation is not quite correct. The connection string may very well point to a database that's readonly. But then

> I could even create a specialized SqlCommand to throw exceptions on write methods while using a ReadOnly connection (overriding ExecuteNonQuery to throw an exception). So I could make a specialized method on it:

Overriding base class methods and changing them to throw new exceptions is a dubious thing to do in OOP. Assuming you care about OOP design...

> What's the most easy way to accomplish this? Using .net core dependency injection:

There may be other legitimate reasons to inherit from `SqlConnection` but creating new types just to get DI to work is suspect. Injecting some kind of connection factory would be better, not only that you don't need to inherit from `SqlConnection` but it also gives you better control over connection's lifetime.

**Comment by jnm2** [comment]
I agree with the others. If you want to layer semantics on top, use composition and create an appropriate interface that gives you the control you need to enforce it. Inheritance is not a great tool in this particular scenario.

**Comment by saurabh500** [comment]
SqlConnection was never designed to be inherited from and cannot be changed to be not `sealed` 
I agree with @jnm2 that composition should be used to accomplish the behavior that is desired. 
This allows better separation of boundaries and better diagnosis of runtime problems as well.
