### ISSUE TITLE
Many deprecation warnings in System.Security.Cryptography.Native on Mac OS X

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#2546]
I'm about to unblock the mac build by disabling the warnings, but building System.Security.Crytpography.Native on Mac OS X produces many deprecation warnings.

**Comment by bartonjs** [comment]
Really the problem is that for OSX we should be using CommonCrypto instead of OpenSSL, and that's what these deprecation warnings are trying to tell us.  This is something that we definitely need to do long-term, but we have to start somewhere.  Moving to "Future".

**Comment by jasonwilliams200OK** [comment]
@bartonjs, found some references for similar CommonCrypto support work: https://github.com/search?q=openssl+commoncrypto+is%3Apr&ref=searchresults&type=Issues&utf8=✓.
Seems like mostly they have prefixed the function names with `CC_`, for which `#define`s and `static_cast`s would be required. Hopefully, there won't be a major blocker for S.S.C.N coverage.

**Comment by bartonjs** [comment]
When we stopped building against 0.9.8 the warnings went away.  So this is pretty stale now :smile:
