### ISSUE TITLE
SmtpClient should enable predictable filenames when using SpecifiedPickupDirectory delivery method

### ISSUE THREAD

**Issue by toepoke** [dotnet/corefx#25463]
## Current Situation
Currently we can write an email to the filesystem so we can verify the content without actually sending a communication.

```c#
	string from = "someone@example.com";
	string to = "someone-else@example.com";
	SmtpClient client = new SmtpClient("smtp.example.com");
	client.PickupDirectoryLocation = @"C:\temp";
	client.DeliveryMethod = SmtpDeliveryMethod.SpecifiedPickupDirectory;
			
	MailMessage m = new MailMessage(from, to);
	m.Body = "Hey core-coders!";
	m.Subject = "Example.com email";
	client.SendMail(m);
```

Which predictably writes a file to **C:\temp** - however the filename is an auto generated guid (e.g. *e98d022e-8885-4969-b87e-c16b03c02712.eml*).

## Rational and Usage
This works well, however it doesn't scale well if you have a routine that sends 20+ emails and you're interested in looking at 1 of them.  

A simple way to improve this is to add a method on the **MailMessage** class to stipulate how the filename should be written to the filesystem.

```c#
	m.SpecifiedPickupFile = "my-filename.eml";
```

### Proposed API

```c#
	namespace System.Net.Mail {
		public class MailMessage : IDisposable {
			public string SpecifiedPickupFile { get; set; }
			....
		}
	}
```

## Details
- Above change would also help with integration testing.

## Open Questions
- What happens if the file already exists in the **SpecifiedPickupDirectory**? Personally I think an exception would be the sensible choice (duplicate file exception?).

## Pull Request
Proposal not yet approved.

## Updates
- Initial version

**Comment by karelz** [comment]
`SmtpClient` is legacy API in maintenance mode, which we don't have plans to evolve significantly (beyond high-pri bug fixes) - see our [Networking roadmap](https://github.com/dotnet/designs/issues/9).
We recommend customers to migrate to other, modern email client libraries - e.g. [MailKit](https://github.com/jstedfast/MailKit) (see our [deprecation entry](https://github.com/dotnet/platform-compat/blob/master/docs/DE0005.md)).

This particular scenario does not seem to fit the "high-pri bug fix" bar, so closing - let me know if you strongly disagree or if there is additional evidence that could prove my assessment wrong. Thanks!
