### ISSUE TITLE
AsyncLocal.OnValueChanged seems to be called with a stale change, crashing the process

### ISSUE THREAD

**Issue by lakeman** [dotnet/corefx#25477]
I've attempted to write a middleware service to use WindowsIdentity.RunImpersonated, Wait()-ing for the next handler to return. 

However I've seen that WindowsIdentity.CurrentImpersonatedTokenChanged is called a final time after my middleware finishes, with a closed but valid windows token. This leads to Environment.FailFast being called in ExecutionContext.OnContextChanged, which is logging the stack trace from OnContextChanged, but isn't logging the details of the exception that was caught.

There seem to be a number of problems here;
- We need an async version of RunImpersonated (#24977)
- WindowsIdentity.CurrentImpersonatedTokenChanged should check for closed tokens
- Environment.FailFast should log the exception details (https://github.com/dotnet/coreclr/issues/15203)
- AsyncLocal.OnValueChanged seems to be called with a stale change after an async task has completed.

In the meantime, I've worked around the problem by calling advapi32.dll ImpersonateLoggedOnUser / RevertToSelf directly from an AsyncLocal change handler, essentially implementing an async version of RunImpersonated myself.

EDIT by @ViktorHofer: added issue link for failfast.

**Comment by danmosemsft** [comment]
@lakeman thanks for the report. Can you open a separate issue for #3 (and maybe #2). For this issue, #4 I guess, is it feasible to share a repro?

@ViktorHofer for FailFast, did you look at logging the exception data? I assume it is pExceptionInfo in https://github.com/dotnet/coreclr/commit/0c4a490a74c81e9735b0b7ef5b272add75e95ddf

**Comment by ViktorHofer** [comment]
> @ViktorHofer for FailFast, did you look at logging the exception data? I assume it is pExceptionInfo in dotnet/coreclr@0c4a490

If I can remember correctly `pExceptionInfo` was either always or sometimes null. There was a reason why I couldn't touch it. I will check again.

**Comment by ViktorHofer** [comment]
> Environment.FailFast should log the exception details

https://source.dot.net/#System.Security.Principal.Windows/System/Security/Principal/WindowsIdentity.cs,681
`CurrentImpersonatedTokenChanged` currently calls `Environment.FailFast(string)` and not `Environment.FailFast(string,Exception)` which probably is the reason why the exception data isn't logged. I'm not sure if passing the `Win32Exception` as the exception parameter would make sense as we create it ourselves without ever throwing it which means it does not have any stacktrace data.

**Comment by lakeman** [comment]
I've seen a stack trace from ExecutionContext.OnContextChanged in my app's stdout / log. I'm fairly certain that this exception is being thrown by the safe handle, not by WindowsIdentity.

**Comment by ViktorHofer** [comment]
I see, so the issue is not that the stacktrace is missing but that you want more exception data logged.

**Comment by lakeman** [comment]
No, the stack trace from the caught exception is missing, only the stack trace from the FailFast call is present.

**Comment by benaadams** [comment]
> AsyncLocal.OnValueChanged seems to be called with a stale change after an async task has completed.

`OnValueChanged` gets called with the updated values as you go deeper into the await stack and change the value; then it rewinds as you await back out of the stack, giving you previous values.

What happens if you add a `try`/`catch` in your `OnValueChanged` handler rather than letting the exception escape?

**Comment by ViktorHofer** [comment]
> No, the stack trace from the caught exception is missing, only the stack trace from the FailFast call is present.

I see. Thanks for the feeback! I created an issue for it in the coreclr repo: https://github.com/dotnet/coreclr/issues/15203

**Comment by lakeman** [comment]
Here's my version of an async windows impersonation middleware, that I wrote to work around this issue; 
https://gist.github.com/lakeman/26af3a6d047d3de84c710711781ea709

In my testing, TokenChanged is called *after* setting the value to null, with a non-null closed token.

**Comment by benaadams** [comment]
`throw new Win32Exception()` in `TokenChanged` will crash the process

**Comment by lakeman** [comment]
Perhaps, I copied and pasted that from WindowsIdentity.RunImpersonated without looking into what that exception type does. But I'm not hitting that exception in practice, and neither is the problem I'm referring to above.

The problem is that within Kestrel middleware, I'm seeing that AsyncLocal.OnValueChanged is called once more with a stale current value, after the request pipeline has completed.

The existing implementation of WindowsIdentity.CurrentImpersonatedTokenChanged throws an exception, I believe because the windows login token has already been closed by some other part of Kestrel, and the value cannot be converted to the right argument type for the dll call.

Which causes ExecutionContext.OnContextChanged to call FailFast.

Which doesn't log the true cause of the problem.

**Comment by benaadams** [comment]
Its an aside; type of exception doesn't matter, throwing any exception in `OnContextChanged` will crash the process as it has nowhere to go; its at the top of the stack.

> Which doesn't log the true cause of the problem.

FailFast probably should record the inner exception if there is one; e.g cause

OTOH, I'm interested in the `OnValueChanged` issue.

If you do add at the top of `TokenChanged` 

```csharp
private static void TokenChanged(AsyncLocalValueChangedArgs<WindowsIdentity> args)
{
   Console.WriteLine($"{args.CurrentValue != null}, {args.PreviousValue != null}, {args.contextChanged}");
```
What sequence does it output?

**Comment by lakeman** [comment]
I did look at the current, previous and ThreadContextChanged values before raising this issue. And everything seemed to make sense. Except for the last call.

Here's a screen shot of the stack trace and source of that last call from VS;
![stack_trace](https://user-images.githubusercontent.com/590814/33217317-54c6d09a-d187-11e7-84c4-3d9b7704736e.PNG)

By this point I believe that currentValue should have evaluated to null.

**Comment by benaadams** [comment]
So: `CurrentValue` != `PreviousValue` and both are `WindowsIdentity` and its a `async` change rather than manual change?

Which would suggest its not after `currentToken.Value = null;` but the `currentToken` is changed to `WindowsIdentity` a second time, and is being reverted at an `await`.

Can `Invoke` be called multiple times in the same call stack?

**Comment by benaadams** [comment]
Adding to
```csharp
private static void TokenChanged(AsyncLocalValueChangedArgs<WindowsIdentity> args)
```
The following
```csharp
Console.WriteLine("TokenChanged");
Console.WriteLine($"- current  == null    : {args.CurrentValue == null}");
Console.WriteLine($"- previous == null    : {args.PreviousValue == null}");
Console.WriteLine($"- current  == previous: {args.PreviousValue == args.CurrentValue}");
Console.WriteLine($"- await revert        : {args.contextChanged}");
```
Then making one request and checking the console output should provide some clarity?

**Comment by lakeman** [comment]
Request begins;

dbug: ClientDB.Code.Impersonate[0]
      Impersonating FORSYTE\jeremy
TokenChanged
- current  == null    : False
- previous == null    : True
- current  == previous: False
- ThreadContextChanged: False
TokenChanged
- current  == null    : False
- previous == null    : True
- current  == previous: False
- ThreadContextChanged: True

*Lots* of these pairs;

TokenChanged
- current  == null    : True
- previous == null    : False
- current  == previous: False
- ThreadContextChanged: True
TokenChanged
- current  == null    : False
- previous == null    : True
- current  == previous: False
- ThreadContextChanged: True

Last log entry from the MVC controller action ommitted.
currentToken.Value = null; triggers this as expected;

TokenChanged
- current  == null    : True
- previous == null    : False
- current  == previous: False
- ThreadContextChanged: False
dbug: ClientDB.Code.Impersonate[0]
      Impersonation complete
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 10264.8886ms 200 text/event-stream

And everything else after here makes no sense, since the only place that set a value has finished, and already set the value back to null;

TokenChanged
- current  == null    : False
- previous == null    : True
- current  == previous: False
- ThreadContextChanged: True
TokenChanged
- current  == null    : True
- previous == null    : False
- current  == previous: False
- ThreadContextChanged: True
TokenChanged
- current  == null    : False
- previous == null    : True
- current  == previous: False
- ThreadContextChanged: True

(yay, multiple threads....)

TokenChanged
- current  == null    : True
TokenChanged
- previous == null    : False
- current  == null    : False
- previous == null    : True
- current  == previous: False
- ThreadContextChanged: True
- current  == previous: False
- ThreadContextChanged: True
TokenChanged
- current  == null    : True
- previous == null    : False
- current  == previous: False
- ThreadContextChanged: True
TokenChanged
- current  == null    : False
- previous == null    : True
- current  == previous: False
- ThreadContextChanged: True
TokenChanged
- current  == null    : True
- previous == null    : False
- current  == previous: False
- ThreadContextChanged: True
TokenChanged
- current  == null    : False
- previous == null    : True
- current  == previous: False
- ThreadContextChanged: True
TokenChanged
- current  == null    : True
- previous == null    : False
- current  == previous: False
- ThreadContextChanged: True
TokenChanged
- current  == null    : False
- previous == null    : True
- current  == previous: False
- ThreadContextChanged: True
TokenChanged
- current  == null    : True
- previous == null    : False
- current  == previous: False
- ThreadContextChanged: True

Hmmmm, It might be possible that there's a missing await somewhere, but I haven't seen any compiler warnings. If that's what is causing this problem, I'll be quite annoyed, but at least I'd have an answer.

**Comment by benaadams** [comment]
breakpoint: `logger.LogDebug($"Impersonation complete");`

Then when its hit; look at the `Tasks` view in VS?

**Comment by lakeman** [comment]
The tasks view is blank, I think that's a known issue with v2.

It looks like ExecutionContextSwitcher.Undo is causing the first callback after completion. The remaining callbacks from the above log seem to be triggered by a timer.

Is there anything else we can do to improve diagnosis for this issue or similar problems?

**Comment by lakeman** [comment]
I think I'm getting closer to understanding the role of ExecutionContext here. So this is what I've deduced;

My dodgy Impersonation middleware doesn't capture a new execution context until the first time a task is awaited. So when the AsyncLocal is first assigned, it's essentially attached to the callers context. When the AsyncLocal is cleared, it only affects the newly captured context. When the middleware returns, the callers context is reloaded which still has the same token attached to it. Causing an immediate problem since the token has now been closed. I think I can fix this by capturing a new context first, similar to the internal implementation of WindowsIdentity.RunImpersonated.

I think I'm getting closer to identifying the original problem I was trying to diagnose. Somewhere that I haven't yet identified, perhaps in MVC / EF, some form of delay / timer task is being started. When this timer elapses, a captured ExecutionContext containing the windows login token is being reloaded, but the token has since been closed, causing WindowsIdentity.CurrentImpersonatedTokenChanged to crash the process.

So back to my first question, should WindowsIdentity.CurrentImpersonatedTokenChanged ignore closed tokens as well is invalid ones? Should we call the thread's default exception handler instead of FailFast? Or is there a better way to help developers diagnose issues like these?

**Comment by lakeman** [comment]
I've found the source of the timer crashing my process and raised #25627 with a short reproducer.

**Comment by bartonjs** [comment]
@brentschmaltz Any thoughts on

> So back to my first question, should WindowsIdentity.CurrentImpersonatedTokenChanged ignore closed tokens as well is invalid ones?

**Comment by bartonjs** [comment]
@lakeman Since it seems like the underlying problems are being fixed and it's now down to just a design/philosophy question I'm marking this as future.  If there's anything I'm missing, just speak up.

**Comment by kouvel** [comment]
Is this a duplicate of https://github.com/dotnet/corefx/issues/30275? The token passed into `RunImpersonated` is now duplicated and should have the expected lifetime.
