### ISSUE TITLE
Implement managed and independent websocket support

### ISSUE THREAD

**Issue by TechnikEmpire** [dotnet/corefx#25489]
According to the code here, there's no websocket implementation for Windows 7. Since windows 7 isn't EOL and it's listed as a supported plaform, this is a bug . Since Microsoft I guess wants to keep ubiquitous web technology out of Windows 7 I guess to coerce people into upgrading to Windows Spy edition, probably should implement this or strip windows 7 from the list of supported operating systems.

**Comment by stephentoub** [comment]
Thanks. Dup of https://github.com/dotnet/corefx/issues/9503.

**Comment by TechnikEmpire** [comment]
Ah, my bad. I did a search but found nothing. Thanks.

**Comment by stephentoub** [comment]
No problem.  It can be very difficult to find issues for things. :smile:
