### ISSUE TITLE
Add PrepareAsync() to DbCommand

### ISSUE THREAD

**Issue by roji** [dotnet/corefx#25505]
ADO.NET includes `DbCommand.Prepare()` for command preparation, to speed up subsequent repeated executions of the command. As this method may perform I/O to create a server-side statement, it should have a `DbCommand.PrepareAsync()` counterpart. As with other ADO.NET async overloads, `DbCommand` should provide a default implementation which delegates to the sync version.

**Comment by JonHanna** [comment]
Agreed. I remember working on that `NpgsqlCommand.Prepare()` override some time ago, and it is a very natural method for an async version. I would assume the same would be true of other providers.

The API could be:

```C#
public abstract class DbCommand
{
    public virtual Task PrepareAsync();
}
```

(The implementation need only be `{Prepare(); return Task.CompletedTask();}`).

**Comment by divega** [comment]
*System.Data Triage:* This looks like a good idea, although we are not going to implement it right away. 
This related to another issue that calls for implementing async versions of other APIs that can block now.
Moving to Future.

**Comment by roji** [comment]
Closing in favor of #35012
