### ISSUE TITLE
corefx build fails with  zero as null pointer constant

### ISSUE THREAD

**Issue by sam0302** [dotnet/corefx#25515]
I am trying to build corefx for raspberry pi with clang 5.0. I am betting below error at multiple places.

/src/Native/Unix/System.Native/pal_random.cpp::9494::2222::

  errorerror: : zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
        srand48(time(NULL));        srand48(time(NULL));
                     ^~~~                     ^~~~
                     nullptr                     nullptr

/corefx/2.0.0-r0/recipe-sysroot-native/usr/lib/clang/5.0.1/include/stddef.h::100100::1818::  notenote: : expanded from macro NULL expanded from macro NULL
 `#` define NULL __null#    define NULL __null

Any suggestion would be of great help.

**Comment by benaadams** [comment]
When I've seen this in coreclr its because `NULL` needs to be changed to `nullptr` for  C++11 onwards 

This is because of the ambiguity of `NULL` (it can also represent `int` etc)

**Comment by sam0302** [comment]
Ok, I see, is there a patch already available? I see a lot of .cpp files and header files where we need to change from NULL to nullptr.

**Comment by benaadams** [comment]
coreclr does a clang formatting check so their are no `NULL`s in there.

Don't think corefx does; is probably worth putting a patch in to change them if its causing you issue?

**Comment by sam0302** [comment]
I see format-code.py  inside corefx has only checkonly option, I cannot run this to format the native code.

**Comment by karelz** [comment]
The PAL is slowly being migrated to C code - to enable sharing more code with Mono: https://github.com/dotnet/corefx/commits/master/src/Native/Unix/System.Native
I think it should address problem for this file.

cc @luhenry

**Comment by luhenry** [comment]
As `pal_random.cpp` is a C++ file, it should most likely be `nullptr` instead of `NULL`. And as @karelz pointed out, the PAL is slowly being migrated to C, so at some point `pal_random.cpp` will become `pal_random.c` and this `nullptr` will become `NULL` again, but I don't have any definite timeline for that, so a PR fixing it for C++ should probably be submitted.

**Comment by karelz** [comment]
@ViktorHofer please do not remove area labels - replace them with new ones. Without area label, nobody is paying attention ;)

**Comment by ViktorHofer** [comment]
This was done with https://github.com/dotnet/corefx/commit/f23fcfde91aa15d9ea26947abc812768d571269f
