### ISSUE TITLE
Remove suffix ".sh" from Unix shell scripts such as "build.sh" - let the shebang line do its job

### ISSUE THREAD

**Issue by mklement0** [dotnet/corefx#25512]
On Unix platforms, it is solely the executable bit that determines whether files are executable - irrespective of the filename or its suffix (extension, in Windows-speak).

A file marked as executable that happens to be a _script_ file specifies the executable (interpreter) to use via its _shebang line_,  the very first line which looks something like `#!/usr/bin/env bash`.

Therefore, **rename `build.sh` to just `build`, ...**  - **suffix `.sh` is technically unnecessary and generally a bad habit.**

Omitting the `.sh` suffix will make invocation on Unix more like on Windows:

```cmd
:: cmd.exe
build

# PowerShell
./build
```

```sh
# bash
./build
```

Note that, for security reasons, the `./` part is necessary in order to invoke an executable in the current dir. on Unix platforms, just as it is in PowerShell.

**Comment by karelz** [comment]
There are quite a lot of dependencies on the .sh names already - in other scripts, our automation and documentation. I wonder if it is worth a change.

I see quite a few hits on .sh extension on internet, so I wonder - is it just one of the style/opinion-based things, or is it truly highly recommended mainstream thing to drop the extension on Linux? cc @wfurt 

BTW: I actually plan to drop the ./ from our contributors' docs and plan to recommend putting build.bat/.sh on path for easier development.

**Comment by wfurt** [comment]
The argument is valid as execution does not depend on extension on Unix systenms.  However this is cosmetic issue as well as may depend on personal preference. I don't think there is any harm to have shell script with .sh extension. I don't think the risk and effort is worth of the outcome @karelz unless @tmds disagrees. 
This is not just the code but also cleanup for all the documentation and build automation.

**Comment by tmds** [comment]
> I don't think the risk and effort is worth of the outcome

+1. Let's stick to the current style.

> I actually plan to drop the ./ from our contributors' docs and plan to recommend putting build.bat/.sh on path for easier development.

@karelz my opinion: I don't notice the './' and I'm picky of what I put on my PATH :smile: 
'./' in the docs makes things more copy-pastable. Also if you have multiple repos with build.sh, the PATH thing gets messy.
```
~/repos/corefx $ build.sh     # builds what is on PATH ...
```

**Comment by karelz** [comment]
@tmds multiple repos will need to create multiplexer - build.sh/.bat which finds the right one in your directory hierarchy. It is not mandatory, just convenience for when you are not in root directory (common case).

Closing this issue as Won't Fix based on above discussion.

**Comment by mklement0** [comment]
Understandable that you don't want to change at this point, but just for the record:

It's more than a _cosmetic_ issue, because - unlike with `.cmd` and `.bat` on Windows - you have to _type_ the `.sh` suffix (though tab completion can obviously help with that).

Also, without the `.sh` suffix, the invocations would be the same on both Windows and Unix (at least once you put the scripts in the PATH: `build`; even without that, if you contrast PowerShell with Unix, `./build` would then also work on both platforms).

On a more philosophical note: Yes, there is no _harm_ in a shell scripts having extension `.sh`, but there is also _no benefit_ in doing so - on the contrary, not least because the fact that the executable happens to be a shell script is an _implementation detail_ that you may want to change later (say to a faster re-implementation in C#, or a different scripting language).
