### ISSUE TITLE
System.Net.Http.dll 4.6.25220.1和 System.Net.Http.dll 4.6.25514.4不兼容

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#25516]
@ghd258 commented on [Thu Nov 16 2017](https://github.com/dotnet/core/issues/1098)

System.Net.Http.dll 4.6.25220.1和
System.Net.Http.dll 4.6.25514.4 不兼容 而且NuGet就没有4.6.25514.4 这个版本

---

@Petermarcu commented on [Sun Nov 26 2017](https://github.com/dotnet/core/issues/1098#issuecomment-347080256)

Translated:
System.Net.Http.dll 4.6.25220.1 and System.Net.Http.dll 4.6.25514.4 is not compatible and NuGet is not 4.6.25514.4 this version

@davidsh is this another instance of the OOB/Binding redirect challenges with System.Net.Http?

**Comment by davidsh** [comment]
>@davidsh is this another instance of the OOB/Binding redirect challenges with System.Net.Http?

There is not enough information in this bug report to diagnose anything.

**Comment by karelz** [comment]
Seems not actionable. @ghd258 please provide more details or repro steps. Please link Nuget versions you have troubles with: https://www.nuget.org/packages/System.Net.Http/

Closing until we have more info.
