### ISSUE TITLE
FreeBSD: building corefx managed components fails on ODBC32 namespace

### ISSUE THREAD

**Issue by maurocolella** [dotnet/corefx#25517]
Dear All,

I am on Windows 10, and I am referring specifically to:
https://github.com/dotnet/corefx/wiki/Building-.NET-Core--2.x-on-FreeBSD#user-content-building-managed-components-on-windows

As well as the Linux counterpart. I tried:
1) `build.cmd` with default flags. This works, but I am well uncertain what to copy to my FreeBSD (11) system.
2) `build-managed.cmd` with the same flags recommended for Linux. The build fails at:

```System.Data.forwards.cs(10,83): error CS0234: The type or namespace name 'ODBC32' does not exist in the namespace 'System.Data.Odbc' (are you missing an assembly reference?)```

3) The same on Ubuntu 16.04, on Hyper-V (using both build.sh and build-managed.sh). Same failure as on Windows. Corefx revision is:
`commit d61b6095568c18cb5e24cff24e0ecf488dfe0f75`

Furthermore, I am uncertain what to do with the binaries, should I be able to produce them. From the following passage, I seem to understand which binaries/libraries are required for testing: should I just move that set of files to `/usr/.../bin` in order to access them globally?

**Comment by karelz** [comment]
cc @wfurt

**Comment by wfurt** [comment]
I can take a look @maurocolella . @RussellHaley was working on Windows instructions.

As far as the path I never used /.. folders. The tests should be self contained within build tree. 
I use rsync (xcopy) to get ./bin over. That is probably more than you need as it includes intermediate objects but it was easy to describe. I'll add some clarification to notes as well.

**Comment by maurocolella** [comment]
Thank you @wfurt 

The most important issue for me at this time is of course `The type or namespace name 'ODBC32' does not exist in the namespace 'System.Data.Odbc'`

This happens I think as soon as I specify `-OS=FreeBSD`. Whether I attempt to compile on Windows, or Linux; I am not sure what alternative I have to build the managed portion of the code.

**Comment by wfurt** [comment]
Just to verify this: when you simply run "./build.sh" everything works ok? 
The -OS is needed to properly select features available on FreeBSD. Without it managed code would assume default platform and than fail when copied over. This also pull in proper files for Interop/*

**Comment by maurocolella** [comment]
On Windows, I tried `build.cmd` and everything worked Ok. As soon as I added the OS flag, the build failed with the ODBC error.

I am trying the build again on Ubuntu. When I tried it there with the OS flag, the error was the same.

**Comment by maurocolella** [comment]
The build finished without errors using `build.sh` on Linux with no flags.

**Comment by RussellHaley** [comment]
I have been testing the coreclr right now. I am in a similar spot to @maurocolella. I built on Windows using no OS flag. I was able to get the native tests to pass but haven't had the Managed tests work yet. OS flag may be part of the problem. Will try to post some notes about what I transferred over. FYI I used mount_smbfs to transfer between Windows Host and FreeBSD VMs. See https://forums.freebsd.org/threads/55091/#post-365528

**Comment by wfurt** [comment]
It seems like things got broken again. I'm working on fix. This is going to be ongoing battle until we get to point we have automatic build regression.

**Comment by maurocolella** [comment]
Building the coreclr (and running the tests) works fine. My issue is
specifically with corefx.

**Comment by maurocolella** [comment]
Thank you for your help. Last question: how can I correctly match builds of `corefx`, `coreclr`, and ensure the proper `core-setup` version?

**Comment by wfurt** [comment]
there is no easy answer to that. unfortunately. There be separate project to build .net from sources. Also there is bootstrap script to take released .net runtime, find proper code and rebuild it for given platform. Most of the time, if you take drop from same time, it will probably work.

**Comment by maurocolella** [comment]
Ok. Again thank you.
