### ISSUE TITLE
thread contention at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.GetTypeInformation 

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#25529]
@AndresPabloGomez commented 4 days ago
Please change the method GetTypeInformation to use ReaderWriterLockSlim or something else, to access typeNameCache dictionary.

 @msisterna commented 4 days ago
I have the same problem.

**Comment by danmosemsft** [comment]
@ViktorHofer does this change make sense to you? Seems reasonable to me. If so perhaps @Anipik could take it. It will need perf measurements as sanity check.

**Comment by stephentoub** [comment]
> change the method GetTypeInformation to use ReaderWriterLockSlim or something else

RWLS would likely make things worse. If it's going to be changed, a ConcurrentDictionary would likely be best, so that there's no lock at all on the already initialized read path.

> I have the same problem

Can someone share more details / a repro of the problem?

**Comment by danmosemsft** [comment]
ccing @AndresPabloGomez @msisterna for that information in case pasting them in above didn't do the trick.

**Comment by AndresPabloGomez** [comment]
Hi. I took a dump from a production server with high load, and a lot of thread where waiting for the typeNameCache dictionary:

000000001cf4c6e8 000000007714c2ea [GCFrame: 000000001cf4c6e8] 
000000001cf4c900 000000007714c2ea [GCFrame: 000000001cf4c900] 
000000001cf4c938 000000007714c2ea [HelperMethodFrame: 000000001cf4c938] System.Threading.Monitor.Enter(System.Object)
000000001cf4ca30 000007fef6c2ed07 System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.GetTypeInformation(System.Type) [f:\dd\ndp\clr\src\BCL\system\runtime\serialization\formatters\binary\binaryformatter.cs @ 241]
000000001cf4cac0 000007fef6c2ec71 System.Runtime.Serialization.Formatters.Binary.SerObjectInfoCache..ctor(System.Type) [f:\dd\ndp\clr\src\BCL\system\runtime\serialization\formatters\binary\binaryobjectinfo.cs @ 929]
000000001cf4cb00 000007fef6c2eb08 System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo() [f:\dd\ndp\clr\src\BCL\system\runtime\serialization\formatters\binary\binaryobjectinfo.cs @ 344]
000000001cf4cb70 000007fef6c2e89a System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(System.Object, System.Runtime.Serialization.ISurrogateSelector, System.Runtime.Serialization.StreamingContext, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoInit, System.Runtime.Serialization.IFormatterConverter, System.Runtime.Serialization.Formatters.Binary.ObjectWriter, System.Runtime.Serialization.SerializationBinder) [f:\dd\ndp\clr\src\BCL\system\runtime\serialization\formatters\binary\binaryobjectinfo.cs @ 169]
000000001cf4cbf0 000007fef6c2fcaf System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo, System.Runtime.Serialization.Formatters.Binary.NameInfo, System.Runtime.Serialization.Formatters.Binary.NameInfo) [f:\dd\ndp\clr\src\BCL\system\runtime\serialization\formatters\binary\binaryobjectwriter.cs @ 422]

Thanks for your attention.
Please tell me if you need more info
Andres

**Comment by ViktorHofer** [comment]
Sounds reasonable to me with using a ConcurrentDictionary as Stephen mentioned. We are already using a Dictionary, the change should be straightforward. I'm more interested about the perf results. @Anipik go for it, please include perf results which outlines the time spent on waiting when using a lock vs the ConcurrentDictionary. I would recommend using BenchmarkDotNet for it, but you are the one to decide.

**Comment by msisterna** [comment]
Hi.
Like said @stephentoub i think a ConcurrentDictionary would be perfect.

**Comment by danmosemsft** [comment]
Please use Benchmark.NET to show change in both contended and uncontended scenarios.

**Comment by msisterna** [comment]
I wanted to ask you if this kind of change applies to both .net core and .net fx.
Thank you.

**Comment by ViktorHofer** [comment]
We marked it as "netfx-port-consider" which means that we consider porting it to the full framework. But before even planning to do that we need the change in corefx.

**Comment by danmosemsft** [comment]
@AndresPabloGomez as @ViktorHofer mentioned, this has been logged internally as a potential port to the .NET Framework, which I see is what you're using. That would take a while though. I'm curious whether your server could potentially run .NET Core? If you're using Webforms, for example, that would not be possible.

**Comment by AndresPabloGomez** [comment]
Hi, is not possible to port to .Net Core. We have a high performance, scalable, fault tolerance Middleware and Application Server solution. Some features uses low level APIs to interface with other systems and legacies. We appreciate this changes implemented in .Net Framework.

**Comment by AndresPabloGomez** [comment]
I’d like to track the port to the .Net Framework, Is there an issue or request opened to track? Thanks

**Comment by ViktorHofer** [comment]
There is one in our internal TFS. I will keep this thread updated as we progress with the Desktop port

**Comment by phyde-work** [comment]
Pinging to see if there is a port to desktop planned anytime soon. I have a website using sql-in memory sessions via binary formatter/serialization that would take a large amount of effort to port to .net core, and this locking issue has bit us a couple times now.

**Comment by ViktorHofer** [comment]
cc @danmosemsft

**Comment by danmosemsft** [comment]
@ViktorHofer can share what release this is in.
