### ISSUE TITLE
"Don't directly throw Exception" System.Data.SqlClient 

### ISSUE THREAD

**Issue by MarcoRossignoli** [dotnet/corefx#25527]
I did some test [here](https://github.com/dotnet/corefx/compare/master...MarcoRossignoli:issue_23748_SqlClient#diff-4443802483f189746d4dcd5ca6e8d62c) on SqlClient(#23748) and i think it's a special case when exception is catch after throw. Maybe "InvalidOperationException"? @JonHanna do you think is fine here?
@saurabh500 @corivera

**Comment by saurabh500** [comment]
@MarcoRossignoli I can confirm that the `Exception` thrown is consumed internally. 
`InvalidOperationException` is reasonable here because the exception is being thrown without a valid Kerberos token.
