### ISSUE TITLE
SocketOptionName.MulticastInterface not supported with Linux IPv6

### ISSUE THREAD

**Issue by pepone** [dotnet/corefx#25525]
Set the multicast interface socket option on IPv6 socket causes a SocketException

```c#
using System;
using System.Net.Sockets;

namespace client
{
    class Program
    {
        static void Main(string[] args)
        {
            var socket = new Socket(AddressFamily.InterNetworkV6, SocketType.Dgram, ProtocolType.Udp);
            socket.SetSocketOption(SocketOptionLevel.IPv6, SocketOptionName.MulticastInterface, 1);
        }
    }
}
```

When run this on Ubuntu Linux with dotnet 2.0.4 results in a SocketException

```
Unhandled Exception: System.Net.Sockets.SocketException: Operation not supported
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at client.Program.Main(String[] args) in /home/jose/client/Program.cs:line 11
```

[EDIT] Add C# syntax highlight by @karelz

**Comment by stephentoub** [comment]
@pepone, have you tried the equivalent code in C on the same machine?

**Comment by pepone** [comment]
I try the same C# code on Windows machine and it worked fine. That was part of my effort to port Ice to .NET Standard 

For C++ we use

```
setsockopt(fd, IPPROTO_IPV6, IPV6_MULTICAST_IF, reinterpret_cast<char*>(&interfaceNum), int(sizeof(int)));
```

See https://github.com/zeroc-ice/ice/blob/master/cpp/src/Ice/Network.cpp#L2138

**Comment by pepone** [comment]
Shouldn't this use IPV6_MULTICAST_IF for ipv6

https://github.com/dotnet/corefx/blob/master/src/Native/Unix/System.Native/pal_networking.c#L1275

**Comment by karelz** [comment]
That might be very much it. Can you try to compile CoreFX and run your test with your proposed fix?
