### ISSUE TITLE
Need Span overloads for Path APIs

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#25539]
In order to reduce allocations for path generation and manipulation we need Span overloads for `System.IO.Path` APIs.

## Proposed API

``` C#
namespace System.IO
{
    public static class Path
    {
        public static ReadOnlySpan<char> GetDirectoryName(ReadOnlySpan<char> path);
        public static ReadOnlySpan<char> GetExtension(ReadOnlySpan<char> path);
        public static ReadOnlySpan<char> GetFileName(ReadOnlySpan<char> path);
        public static ReadOnlySpan<char> GetFileNameWithoutExtension(ReadOnlySpan<char> path);
        public static ReadOnlySpan<char> GetPathRoot(ReadOnlySpan<char> path);
        public static bool HasExtension(ReadOnlySpan<char> path);
        public static bool IsPathFullyQualified(ReadOnlySpan<char> path);
        public static bool IsPathRooted(ReadOnlySpan<char> path);
    }
}
```

## Implementation Notes

- If the current APIs return null, these would return an empty span.

**Comment by karelz** [comment]
FYI: The API review discussion was recorded - see https://youtu.be/9F_NsviGT0Y?t=552 (7 min duration)

**Comment by JeremyKuhne** [comment]
This change is pretty straight-forward. We'll need to clean up internal "index of" helpers and have existing APIs call these new public methods. Tests will need to be added.

**Comment by danmosemsft** [comment]
5 days assuming it's someone less familar with the area, including cleanup mentioned.

**Comment by danmosemsft** [comment]
@dsyme assuming some folks do need these for perf (like ourselves) are you suggesting they should have gone on a new type? (`PathSpan`..)

@jkotas Could tooling someday help here, somehow hiding overloads that differ only in ReadOnlySpan<char> vs string, and just letting the compiler bind to the right one? (That doesn't help where the signature changes entirely eg the Try pattern ones)

**Comment by JeremyKuhne** [comment]
> Just to mention I don't like these changes. I think they make these very basic APIs considerably harder to use for beginners.

These weren't added for the coolness factor. These overloads are very important for I/O heavy solutions. Allocations for path manipulation is a significant drag on VS/MSBuild for example.

They also aren't intended for beginners. The existing APIs are still there and can and should be used by people who don't care about allocations. We could, in theory, move them into a different class or namespace, but I'm afraid that boat has already sailed. Discoverability was judged to be more important for APIs that match existing ones- and that has been done throughout the framework.

**Comment by jkotas** [comment]
> @jkotas Could tooling someday help here, somehow hiding overloads that differ only in ReadOnlySpan vs string

You are typing `Path.`. What is the crystal ball IntelliSense should use to decide whether to show you the expert Span overloads; or just the regular string overloads?

I guess there can be AI applied to it, classify the users and the APIs, and then decide that most of the users like you do not use Span Path APIs and do not show you those either. I am not saying it is a good idea ... just brainstorming.

BTW: As some of you know I am worried that there are usability issues with the new Path APIs even for expert use. https://github.com/dotnet/coreclr/pull/17429#discussion_r179645599 and https://github.com/dotnet/coreclr/pull/17528#discussion_r181917479 has some of the discussions.

**Comment by danmosemsft** [comment]
If we could show a notional `IString` then perhaps we could collapse the two since most people would assume that `IString` would accept a `String`. I think of `ReadOnlySpan<char>` as just an extension of string (or can be). Yeah, I guess this doesn't make sense and I don't have an answer.
