### ISSUE TITLE
Missing line numbers for NETFX test and code

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#25554]
In at least some cases, eg https://github.com/dotnet/corefx/issues/25550 dumped:
```
        Stack Trace:
             at System.Drawing.Bitmap..ctor(String filename)
             at MonoTests.System.Drawing.Imaging.IconCodecTest.Bitmap16Pixels()
```

May need someone to use the Helix repro tool to see why.

**Comment by danmosemsft** [comment]
Works fine locally.

**Comment by wtgodbe** [comment]
Closing as stale, please re-open if we should still look into it
