### ISSUE TITLE
Consider changing HttpMethod to do equality comparisons case-sensitive

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#2556]
Reference PR #2553.  Consider changing the `System.Net.Http.HttpMethod` class so that equality comparison between two `HttpMethod` objects is done in a case-sensitive manner (aligning with the latest HTTP RFC) instead of the current case-insensitive manner.

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar @pgavlin

**Comment by justinvp** [comment]
Despite the RFC, I do not think the design of `HttpMethod` should be changed to do case-sensitive `Equals`/`GetHashCode`. This would mean that `HttpMethods` that were previously considered equal, now may be unequal, a truly breaking change.

However, I am in favor of changing the behavior of `GetHashCode` to use `StringComparer.OrdinalIgnoreCase.GetHashCode(_method)` instead of `_method.ToUpperInvariant().GetHashCode()` to improve performance and avoid the extra string allocation. Changing the behavior of `GetHashCode()` to improve performance should be an acceptable change given the documentation for `GetHashCode()` explicitly states that it may change.

**Comment by justinvp** [comment]
I think this should really be two separate issues (which can be discussed at the same time):

 1. Can `HttpMethod.GetHashCode()` be changed from `_method.ToUpperInvariant().GetHashCode()` to `StringComparer.OrdinalIgnoreCase.GetHashCode(_method)` to improve performance, avoid the extra string allocation, and align `GetHashCode`'s behavior with `Equals`' use of  `StringComparison.OrdinalIgnoreCase`? Such a change would be consistent with similar changes that have already been made to the header classes, which were acceptable.

 2. Should `HttpMethod`'s `Equals`/`GetHashCode` be changed from case-insensitive comparisons to case-sensitive, to match the RFC?

Personally, I'm in favor of 1, not of 2.

**Comment by khellang** [comment]
Since I brought it up at https://github.com/dotnet/corefx/pull/2553#issuecomment-125778805, I might as well add my :+1: here as well :smile:

**Comment by nguerrera** [comment]
I am in 100% agreement with @justinvp: yes to 1, no to 2.

**Comment by darrelmiller** [comment]
I think this is a classic case of Postel's law.   My belief is that any incoming request that uses one of the standard methods but with lower case letters, is not intending it to be a distinct method.  Therefore using a case insensitive equals is the right thing to do.

It is one thing to preserve the case of HTTP methods for dispatching to object methods in a case sensitive language.  It's a whole other thing to support the notion of two distinct methods that differ only in case.  I'm quite confident that the IETF review board would never allow such a thing in the HTTP method registry.

As HTTP methods follow the `token` syntax they are limited to ASCII characters, so the methods ToUpperInvariant and OrdinalIgnoreCase are functionally equivalent from a comparison perspective. Considering a large percentage of middleware components will check HTTP methods, any performance gain is good.

So, I also feel:  yes to 1 and no to 2

**Comment by justinvp** [comment]
FWIW: I'm still in favor of 1 in principle, but once #2561 is merged, 1 is less of a concern to me. (I'm still opposed to 2).

**Comment by davidsh** [comment]
We have already made performance optimizations for 1). The consensus is that 2) is a breaking change and not useful to make.

Closing this issue for now.
