### ISSUE TITLE
Unsealing HttpRequestHeaders and HttpResponseHeaders

### ISSUE THREAD

**Issue by shravan2x** [dotnet/corefx#25561]
The built-in [HttpRequestHeaders](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Headers/HttpRequestHeaders.cs) and [HttpResponseHeaders](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Headers/HttpResponseHeaders.cs) types contain properties for many HTTP headers like `ExpectContinue`, `Host` and so on. 

It would be useful if users could add extend these types and add their own properties (maybe Acme Inc. uses a custom `X-Acme-Awesomeness` header for internal usage and wants to add a property for easy access). However, this can currently not be done since the types are sealed. The closest alternative is to use `GetValues("X-Acme-Awesomeness").First()`, which is messier.

A good example is that `HttpResponseHeaders` does not contain a property for the HTTP `Set-Cookie` field.

Another idea may be to wait to see if C# 8.0 includes extension properties, which would be a solution here.

**Comment by davidsh** [comment]
There are no plans to unseal these types.  The types are meant to return strongly objects and thus need "parsers" associated with them.  That is why we discourage extensibility on these objects by sealing the classes.

For some headers like 'Set-Cookie' response headers, we have seen some requests for that.  In particular, some folks wanted that to return strongly typed objects such as an array of Cookie objects, etc.  However, usually more use of cookies would be bettered handled using the HttpClientHandler.CookieContainer object.  But some requirements for request specific cookie parsing has been considered.

If there are commonly used HTTP request or response headers that are missing from these collections and if strongly typed object parsing is desired, then we would be open to reviewing those proposals.

**Comment by shravan2x** [comment]
> However, usually more use of cookies would be bettered handled using the HttpClientHandler.CookieContainer object. But some requirements for request specific cookie parsing has been considered.

My primary use-case here is again per-request cookie management. I have upvoted the associated proposal.

However, I still feel it very restrictive of the library that users cannot neatly set up support for custom HTTP headers (ones that aren't common enough to be added to .NET Core itself).

> The types are meant to return strongly typed objects and thus need "parsers" associated with them. That is why we discourage extensibility on these objects by sealing the classes.

I understand, but even with extensibility, users could set up their own parsers for new fields. For example, if `X-Acme-Awesomeness` was a JSON array, the user could check it, throw exceptions if necessary and then return the parsed array.

As a bonus, users wanting a `Cookie` property could easily add one themselves until it is added to the core library (or if it isn't).

**Comment by davidsh** [comment]
Freel free to prototype your ideas in CoreFxLab.  That is a place where such things can be done, iterated on, and eventually ported back to CoreFx after being finalized.

**Comment by karelz** [comment]
Let's close this issue for now. When there is a solid proposal / experiment aligned with current API design, we can reopen it and reconsider.
