### ISSUE TITLE
performance of Socket.Select on windows

### ISSUE THREAD

**Issue by zl-cn** [dotnet/corefx#25570]
System: windows 10
Platform: .net core 2.0
under .net core 2.0 calling Socket.Select caused high cpu usage.
but under .net 4.6 it's ok.
simple code:

`
while(true)
{
     Socket.Select(checkRead, checkWrite, checkError, 0);
     if (checkError.Count == 0 && checkWrite.Count == 0 && checkRead.Count == 0)
     {
             Thread.Sleep(10);
             continue;
      }
}
`

**Comment by stephentoub** [comment]
Can you share the full (but small) program to repro what you're seeing? In the snippet you shared, that's going to be an infinite polling loop if any of the sockets are already signaled (such that we don't Sleep), and you'd expect it to consume an entire CPU.

**Comment by stephentoub** [comment]
Closing as dup of https://github.com/dotnet/corefx/issues/25572
