### ISSUE TITLE
 .net core 2.0 calling Socket.Select caused high cpu usage.

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#25572]
_From @zl-cn on November 29, 2017 5:54_

System: windows 10
Platform: .net core 2.0
under .net core 2.0 calling Socket.Select caused high cpu usage.
but under .net 4.6 it's ok.
simple code:

while(true) { Socket.Select(checkRead, checkWrite, checkError, 0); if (checkError.Count == 0 && checkWrite.Count == 0 && checkRead.Count == 0) { Thread.Sleep(10); continue; } }

_Copied from original issue: dotnet/coreclr#15264_

**Comment by stephentoub** [comment]
The code you shared is expected to result in high CPU usage, and does on .NET 4.6.  If, for example, `checkRead` in your example contains a socket with data available on it, that loop will spin, as each call to Socket.Select will immediately return to say data is available and the subsequent if block won't Sleep because `checkRead.Count > 0`.  You can see this code pegs a CPU, on both .NET 4.6 and .NET Core 2.0, as expected:
```C#
using System.Collections.Generic;
using System.Net;
using System.Net.Sockets;
using System.Threading;

class Program
{
    static void Main()
    {
        using (var listener = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
        using (var client = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
        {
            listener.Bind(new IPEndPoint(IPAddress.Loopback, 0));
            listener.Listen(1);

            client.Connect(listener.LocalEndPoint);
            using (Socket server = listener.Accept())
            {
                server.Send(new byte[] { 42 }); // send data to client

                var checkRead = new List<Socket> { client };
                var checkWrite = new List<Socket>();
                var checkError = new List<Socket>();

                Socket.Select(checkRead, checkWrite, checkError, -1); // make sure data is available for the client

                while (true)
                {
                    Socket.Select(checkRead, checkWrite, checkError, 0); // will return immediately
                    if (checkRead.Count == 0 && checkWrite.Count == 0 && checkError.Count == 0) // will not be true
                    {
                        Thread.Sleep(10);
                        continue;
                    }
                }
            }
        }
    }
}
```
I'm not seeing a problem here.

**Comment by stephentoub** [comment]
I'm going to close this, as there doesn't appear to be an actual problem here. @zl-cn, if you believe otherwise, please re-open and provide more details. Thanks.
