### ISSUE TITLE
Add Run(Func<Task>) overload to TaskFactory

### ISSUE THREAD

**Issue by ohadschn** [dotnet/corefx#25603]
Could be convenient and more consistent with [`Task`](https://msdn.microsoft.com/en-us/library/system.threading.tasks.task.run%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396).

**Comment by benaadams** [comment]
There is a [`Task.Run(Func<Task>)`](https://msdn.microsoft.com/en-us/library/hh160382(v=vs.110).aspx) method?

**Comment by ohadschn** [comment]
Yes, I'm talking about adding `TaskFactory.Run(Func<Task>)`

**Comment by stephentoub** [comment]
To what benefit? Task.Run had very specific semantics that would carry over. It targets the default scheduler. It uses the default options. Etc. The whole point of Task factory is to change such defaults, which Run then wouldn't respect.

**Comment by ohadschn** [comment]
I was thinking mostly about the convenience of avoiding the call to `Unwrap()` (since `StartNew(Func<Task>)` returns `Task<Task>`)...

**Comment by stephentoub** [comment]
Sure, that makes sense.  The difficulty is, as I noted, it could be more confusing to have a Run method, as its semantics would either match Task's but ignore TaskFactory's settings, or it would end up having different semantics from Task.  And there's already a `TaskFactory.StartNew(Func<T>)` method, which if you give it a `Func<Task>` will have `T == Task` and thus will return a `Task<Task>`, so adding a `StartNew(Func<Task>)` overload would be a source breaking change.

**Comment by ohadschn** [comment]
Well I don't think anyone would expect `mySpecialTaskFactory.Run` to use the default scheduler :) So I think having different semantics from `Task` is a given, and personally I'm OK with it (that's just me of course).

Another possibility would be to invent a new name, like `TaskFactory.StartAsyncNew` or `TaskFactory.StartUnwrapped` or... well, you know what they say about naming things.

**Comment by stephentoub** [comment]
I don't see us further extending TaskFactory with convenience methods. It has an unfortunately huge number of overloads making it more difficult to use than we'd like, and I don't think adding additional overloads or methods to it in order to avoid needing Unwrap will help; if anything I think it'll hurt. Thanks, though.
