### ISSUE TITLE
Dispose should not throw PlatformNotSupportedException even when the type is not supported

### ISSUE THREAD

**Issue by svick** [dotnet/corefx#25605]
As reported by @ayende in [a blog post](https://ayende.com/blog/180641/if-you-have-a-finalizer-watch-your-ctor?Key=e518b670-167f-4582-afaa-0e201896bd4f), some types throw `PlatformNotSupportedException` from `Dispose(bool disposing)` on platforms that are not supported. This is problematic, because:

1. The big issue: The finalizer of a base class of some of those types (like `Component`) calls `Dispose(false)`, which causes the process to crash.
2. The smaller issue: It's against [the Framework Design Guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern#basic-dispose-pattern):

    >  X AVOID throwing an exception from within `Dispose(bool)` except under critical situations where the containing process has been corrupted (leaks, inconsistent shared state, etc.).
    >
    > Users expect that a call to `Dispose` will not raise an exception. 

    I think this applies even for types that are not supported.

The original example was `SqlConnection`, but I think a simpler repro is with `SerialPort`, which is not supported on .Net Core on Linux:

0. The following should apply to any Linux machine with .Net Core installed (in my case, Ubuntu 16.04 and .Net Core SDK 2.0.3).
1. `dotnet new console`
2. `dotnet add package System.IO.Ports`
3. Change `Program.cs` to:

    ```c#
    using System;
    using System.IO.Ports;

    class Program
    {
        static void Main()
        {
            try
            {
                new SerialPort();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }

            // to simulate GC and subsequent finalization at some point in the future
            GC.Collect();
            GC.WaitForPendingFinalizers();
        }
    }
    ```
4. Run it in Release mode (to make sure the finalizer is run): `dotnet run -c Release`
5. The program first correctly catches the exception thrown from the `SerialPort` constructor, but then it crashes:

    ```
    System.PlatformNotSupportedException: System.IO.Ports is currently only supported on Windows.
       at System.IO.Ports.SerialPort..ctor()
       at Program.Main() in /home/osboxes/hwapp/Program.cs:line 10

    Unhandled Exception: System.PlatformNotSupportedException: System.IO.Ports is currently only supported on Windows.
       at System.IO.Ports.SerialPort.Dispose(Boolean disposing)
       at System.ComponentModel.Component.Finalize()
    ```

I think that for unsupported types, `Dispose` should be empty. It should not throw, to avoid crash that cannot be prevented (and to follow Framework Design Guidelines).

**Comment by davidsh** [comment]
cc: @terrajobst 

I agree that Dispose() should be a no-op instead of throwing an exception in those cases.

**Comment by JonHanna** [comment]
Conceptually also, I don't think "creating this object is supported on this platform, but cleaning it up after not doing anything with it is not" makes a lot of sense.

**Comment by stephentoub** [comment]
The non-Windows build is auto-generated with these PNSEs:
https://github.com/dotnet/corefx/blob/master/src/System.IO.Ports/src/System.IO.Ports.csproj#L8
I think it'd be reasonable to change the generator to simply not throw from void-returning instance methods.

**Comment by svick** [comment]
@JonHanna That's not the case here. Creating the object is not supported, which means that e.g. `new SerialPort()` throws an exception and you don't get your hands on the object. But the partially constructed object still exists and so the runtime still calls its finalizer after it's GCed.

This also means what the design guidelines say is not really relevant, since the user will not be able to call `Dispose()` on the object.

**Comment by JonHanna** [comment]
Ah. That also makes @stephentoub's idea sound then, since there's no way to get an object and hence have a silent failure on e.g. `SerialPort.Open()`.

**Comment by stephentoub** [comment]
> since there's no way to get an object

Right ;)

That said, it looks like @safern recently changed the code to explicitly throw from finalizers:
https://github.com/dotnet/buildtools/pull/1746
@safern, am I understanding correctly?  That would need to be changed, too.

**Comment by svick** [comment]
Actually, I think there is one legitimate* way to get that object: create a class that inherits from the unsupported type and `override` its `Dispose()`. E.g.:

```c#
using System;
using System.IO.Ports;

class Program
{
    static void Main()
    {
        try
        {
            new MySP();
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
        }

        // to simulate GC and subsequent finalization at some point in the future
        GC.Collect();
        GC.WaitForPendingFinalizers();
    }
}

class MySP : SerialPort
{
    protected override void Dispose(bool disposing)
    {
        this.Open();
        base.Dispose(disposing);
    }
}
```

This currently crashes because of the call to `Open()`:

```
System.PlatformNotSupportedException: System.IO.Ports is currently only supported on Windows.
   at System.IO.Ports.SerialPort..ctor()
   at Program.Main() in /home/svick/hwapp/Program.cs:line 10

Unhandled Exception: System.PlatformNotSupportedException: System.IO.Ports is currently only supported on Windows.
   at System.IO.Ports.SerialPort.Open()
   at MySP.Dispose(Boolean disposing) in /home/svick/hwapp/Program.cs:line 27
   at System.ComponentModel.Component.Finalize()
```

It can be argued that this *should* crash, because the user code tried to perform an unsupported operation in a finalizer and that the user should have made sure to not throw from their overridden `Dispose(bool)`. With the proposal to change all `void`-returning methods to empty, this code would not crash.

Is this worth worrying about?

---

\* There are also some illegitimate way, like using `FormatterServices.GetUninitializedObject()` to bypass the constructor or calling a method from the debugger. But I don't think those matter.

**Comment by karelz** [comment]
I think we should keep throwing from all void-returning methods (e.g. `Initialize`), I don't see value in `Open` not throwing - moreover the default values for out args might be as well unexpected under normal circumstances.

We should IMO just not throw from `Dispose()` and `Dispose(bool)` - which probably means to have their 'default' implementations (call base / the other Dispose).

**Comment by davidsh** [comment]
>We should IMO just not throw from Dispose() and 

Dispose should never throw so we should definitely fix that.

**Comment by safern** [comment]
> That said, it looks like @safern recently changed the code to explicitly throw from finalizers:
dotnet/buildtools#1746
@safern, am I understanding correctly? That would need to be changed, too.

Yes, if we don't want to throw from Dispose we should revert my change and add NoWarn to the projects that are generating a turd assembly with an empty finalizer, because that is why we add the throw in the finalizer

**Comment by danmosemsft** [comment]
Or just put in a no op line of code.

**Comment by theunrepentantgeek** [comment]
Adding a finalizer - of any kind - changes the way the GC treats the object. 

Microsoft's own .NET programming guidelines *strongly recommend* not using finalizers unless really necessary. They also warn about the dangers of exception leakage from finalizers, the deleterious effects these will have, and that finalizers should never *ever* leak an exception.

Instead of generating an empty finalizer, *don't generate one at all*.

**Comment by tarekgh** [comment]
@danmosemsft  is there anyone looking at this one? or we are waiting for @safern?

**Comment by danmosemsft** [comment]
Nobody. If I understand correctly, this does not affect anyone unless they use the dummy assemblies that throw everywhere right? Is there a scenario where that is valid?

It should be fixed but does not seem urgent then.

**Comment by weshaggard** [comment]
>Instead of generating an empty finalizer, don't generate one at all.
