### ISSUE TITLE
Suppress compiler warnings from XmlSerializer.Generator

### ISSUE THREAD

**Issue by remcoros** [dotnet/corefx#25616]
When using the new XmlSerializer.Generator, there is a lot of warnings like:

    warning CS0219: The variable 'tmp' is assigned but its value is never used 
    warning CS0219: The variable 'a_2' is assigned but its value is never used

see: https://ci.appveyor.com/project/ublsharp/ublsharp/build/108

Looking at the msbuild targets here https://github.com/dotnet/corefx/blob/master/src/Microsoft.XmlSerializer.Generator/pkg/build/Microsoft.XmlSerializer.Generator.targets#L16 I see there's no way to pass nowarn/DisabledWarnings to the Csc tasks. 

Any way to take a variable here? 

On a side-note, should I even be doing this (including the sgen dll with the nuget packge), or is that something for the package consumer? What are the recommendations?

**Comment by shmao** [comment]
@remcoros Thanks for submitting the issue. To disable the warning, we probably can add something like below in the CSC task.

```xml
DisabledWarnings="$(NoWarn);219;"
```

Can you please share a sample type that cause the warning with us? I haven't been able to repro the issue.

> On a side-note, should I even be doing this (including the sgen dll with the nuget packge), or is that something for the package consumer? What are the recommendations?

If it's your package that uses XmlSerializer to serialize types defined in your package, it would make sense to pack the generated assembly in the package. If it's the package consumers who would instantiate XmlSerializer to serialize types in your package, it'd be better to let the consumers to generate the serialization code for their applications.

**Comment by remcoros** [comment]
@shmao Here is the build output with A LOT of (the same) warnings: https://ci.appveyor.com/project/ublsharp/ublsharp/build/108

- CS0219: The variable 'tmp' is assigned but its value is never used
- CS0162: Unreachable code detected

I think it's those two.

I'd prefer a new msbuild (like XmlSerializersNoWarn) property and not reuse 'NoWarn', so we still can catch warnings from the main library.

**Comment by huanwu** [comment]
@remcoros Thanks for reporting this issue. We'll fix it.

**Comment by remcoros** [comment]
Looks very good, Thanks !!
