### ISSUE TITLE
Provide a method to query memory status on Linux and OSX

### ISSUE THREAD

**Issue by KKhurin** [dotnet/corefx#25617]
This could be similar to [Interop.GlobalMemoryStatusEx.cs](https://github.com/dotnet/corefx/blob/master/src/Common/src/Interop/Windows/kernel32/Interop.GlobalMemoryStatusEx.cs) and provide information similar to the one in MEMORYSTATUSEX. While the memory management is different on Windows and other platforms and this functionality is arguably low level, it still could be useful in a range of user scenarios such as determining memory pressure (e.g. to see if the cache needs to be trimmed) or trying to evaluate memory usage before reserving/mapping/committing large chunks of memory, or trying to decide whether a service wants to reject processing a new request.

It appears that most of the groundwork is already done in 
[sysinfo.cpp](https://github.com/dotnet/coreclr/blob/master/src/pal/src/misc/sysinfo.cpp#L221) but is not exposed via managed APIs.

**Comment by stephentoub** [comment]
@KKhurin, is this still something you're pursuing now that https://docs.microsoft.com/en-us/dotnet/api/system.gc.getgcmemoryinfo?view=netcore-3.0 was added?  I understand they're not exactly the same thing, but those added APIs were meant to help with scenarios like what you describe as the motivation here.  With that, and with no progress on this issue in two years, I'm tempted to close this.  Thanks.

**Comment by KKhurin** [comment]
GC.GetGCMemoryInfo should be suffice.
