### ISSUE TITLE
dotnet publish on FreeBSD

### ISSUE THREAD

**Issue by maurocolella** [dotnet/corefx#25633]
This is more of a question. I apologize in advance if this is not the proper place to ask for a clarification.

I was able to compile the runtime for FreeBSD, by following the instructions at:
https://github.com/dotnet/corefx/wiki/Building-.NET-Core--2.x-on-FreeBSD

I have applications that need to be `dotnet run` from the SDK. If I `dotnet publish` those applications on a Windows host, barring some very particular dependencies, should they run on my FreeBSD environment?

**Comment by karelz** [comment]
`dotnet run` should work even without SDK. Once it is fully working on FreeBSD, you should be able to run with it apps published on other hosts.
cc @wfurt

**Comment by wfurt** [comment]
There is not a simple answer @maurocolella 
Simple assemblies should just run e.g. "dotnet mycool.dll" 
 
In Theory you should be able o publish on windows (or Linux) for other platforms with "-r XXX" However your sdk may not have a clue about FreeBSD RID. You may also run to problems while fetching NuGet packages - currently there are not any for FreeBSD as far as I know.  corefx is still missing few assemblies on FreeBSD - most notably NetworkInfo - and that breaks ping, mail and few other assemblies. 

Long time ago I got bastard SDK running on FreeBSD: https://github.com/wfurt/blob
With that you could publish on FreeBSD. It was working for simple projects but with more complicated parts - like corefx it would blow up.  I was planing to recreate it one again with moe recent an complete code. If you would be interested in giving it try I can probably get that ready over the weekend.

**Comment by maurocolella** [comment]
I am very interested @wfurt. Long story made short, these applications run tasks related to blockchain. A growing trend, hence increasing security requirements as well. With all respect due to solutions like `Docker`, I am a huge believer in FreeBSD's jail system.

**Comment by maurocolella** [comment]
@wfurt have you had a chance to look into that?

**Comment by wfurt** [comment]
yes I did but I hit some roadblocks again. Things got broken as we do not have automated builds for FreeBSD (yet) I'm hopeful I'll have something today or tomorrow.

**Comment by wfurt** [comment]
Hello @maurocolella for the delay. I posted new sdk here: https://github.com/wfurt/blob
It is version 2.2 based on daily snapshots and 2.1 runtime. I've done very limited testing.

```
mkdir foo
cd foo
export COMPlus_ZapDisable=1
export  COMPlus_ReadyToRun=0
export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
export DOTNET_CLI_TELEMETRY_OPTOUT=1
dotnet new console 
dotnet restore
dotnet build
dotnet publish
dotnet --fx-version 2.1.0-preview1-26013-05  bin/Debug/netcoreapp2.0/foo.dll
Hello World!
```

note, that first two environmental variables are mandatory at this point. 

Also going back to your original questions:  As @karelz mentioned, you can skip the 'run' keyword and simply pass in your assembly. Publishing on windows should work in theory but if you use 2.0.x version it will miss all the FreeBSD fixes (which are in 2.1/master branch) 
Maybe publish is something @RussellHaley can experiment with.

**Comment by maurocolella** [comment]
Thank you so much @wfurt !

**Comment by wfurt** [comment]
Closing now. I updated documentation with notes how to rebuild Frankenstein SDK for FreeBSD. 
I have some fixes for bootstrap script and I'll try to get them in soon. I can also provide patch if needed. Notes should outline steps and strategy. I'll try to keep them updated as fixes get submitted (or code broken)
