### ISSUE TITLE
Cannot import PKCS12 certificates on OS X

### ISSUE THREAD

**Issue by pepone** [dotnet/corefx#25631]
```c#
using System;
using System.Security.Cryptography.X509Certificates;

namespace x509import
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {

                X509Store certStore = new X509Store("My", StoreLocation.CurrentUser);
                certStore.Open(OpenFlags.ReadWrite);
                X509Certificate2Collection certs = new X509Certificate2Collection();
                try
                {
                    certs.Import("s_rsa_cai1.p12", "password", X509KeyStorageFlags.DefaultKeySet);
                    foreach(X509Certificate2 c in certs)
                    {
                        certStore.Add(c);
                    }
                }
                finally
                {
                    foreach(X509Certificate2 c in certs)
                    {
                        certStore.Remove(c);
                    }
                }
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex);
            }
        }
    }
}
```

This program fails in OS X with the following exception

```
Interop+AppleCrypto+AppleCommonCryptoCryptographicException: The contents of this item cannot be retrieved.
   at Interop.AppleCrypto.X509StoreAddCertificate(SafeKeychainItemHandle certOrIdentity, SafeKeychainHandle keychain)
   at Internal.Cryptography.Pal.StorePal.AppleKeychainStore.Add(ICertificatePal cert)
   at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate)
   at x509import.Program.Main(String[] args) in /Users/jose/x509import/Program.cs:line 21
```

The same program works fine with Linux and Windows, The test certificate can be download from 
https://github.com/zeroc-ice/ice/raw/3.7/csharp/test/IceSSL/certs/s_rsa_cai1.p12

[EDIT] Add C# syntax highlighting by @karelz

**Comment by bartonjs** [comment]
When importing a PFX that you are adding to a cert store you should assert `X509KeyStorageFlags.PersistKeySet`, otherwise (on Windows) the private key should get deleted during a cleanup step.

PersistKeySet will cause the PFX to already import into login.keychain on macOS, so the store Add should be redundant there.

Otherwise, for your example to work you need to import with Exportable; since on macOS adding the cert+privatekey to the store requires copying the private key from one keychain to another, and that requires the exportable bit.

**Comment by pepone** [comment]
@bartonjs  `X509KeyStorageFlags.PersistKeySet` solves my main issue, as that imports the certificate including the certificate chain to the login keychain.

it is still a bit unfortunate that such a simple program cannot work cross platform, I think it should have just import the certificates without the private key.

**Comment by bartonjs** [comment]
> I think it should have just import the certificates without the private key.

That causes a different set of simple program to not work, one where a PFX is opened and used to sign or decrypt data, then discarded.

Since adding certs to stores seems more rare than using a key from a PFX, that's where the "macOS doesn't treat these the same, how do we handle it?" worked out.

**Comment by pepone** [comment]
>PersistKeySet will cause the PFX to already import into login.keychain on macOS, so the store Add should be redundant there.

Note that test still produce the same error with this falg set

>That causes a different set of simple program to not work, one where a PFX is opened and used to sign or decrypt data, then discarded.

That is right, the most common case here is that you will be using the key.
