### ISSUE TITLE
Alpine Linux hierarchy chain is incorrect

### ISSUE THREAD

**Issue by janvorli** [dotnet/corefx#25638]
In https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtimeGroups.props, the alpine linux has incorrect parent "any" instead of "unix".

**Comment by tarekgh** [comment]
CC @weshaggard 

who should look at this issue?

**Comment by janvorli** [comment]
@tarekgh, I am going to fix it since it turned out it prevents a related fix in core-setup (https://www.github.com/dotnet/core-setup/issues/3483) from working.
