### ISSUE TITLE
[ManagedHandler] ProxySetViaEnvironmentVariable_DefaultProxyCredentialsUsed test disabled

### ISSUE THREAD

**Issue by wfurt** [dotnet/corefx#25640]
This may not be specific to ManagedHandler. We are disabling them for now to reduce noise for 2.1.

ProxySetViaEnvironmentVariable_DefaultProxyCredentialsUsed:
failing sometimes on Windows (this used to be Unix test only) 

12 failures so far in November.

**Comment by caesar1995** [comment]
This test will hang forever if run locally. Investigating.

**Comment by caesar1995** [comment]
> This may not be specific to ManagedHandler

Yes, this test will hang forever with WinHttpHandler as well.

**Comment by davidsh** [comment]
This is probably a test bug with the loopback (proxy) server.

**Comment by caesar1995** [comment]
re-assign to Max: likely loopback server proxy authentication issue.

**Comment by rmkerr** [comment]
This looks like it may be a product issue. By watching the network I can see that the requests are eventually being sent for both proxy enabled and proxy disabled cases:
![image](https://user-images.githubusercontent.com/4656175/38102498-4bff1270-3338-11e8-8ba5-33bcaeacf035.png)
However, I see **no traffic** over loopback. That makes me think that the proxy enabled case is not using the proxy as it should be. This manifests as a hang, since the loopback proxy task never receives data and so never completes.

**Comment by wfurt** [comment]
do you use ncap driver? Loopback on WIndows can be tricky.

**Comment by rmkerr** [comment]
Thanks for the quick response.

Since that support would be a new feature, I'm going to leave this disabled on Windows. I'll open a PR to remove the active issue tag and go back to the old method for skipping the test, just to make it clear this isn't a bug.

**Comment by davidsh** [comment]
.NET Framework also supports app-domain wide proxy settings (which override WinINET-style settings) via an app.config file:

https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/defaultproxy-element-network-settings

```xml
<defaultProxy  
        enabled="true|false"  
        useDefaultCredentials="true|false">  
           <bypasslist> … </bypasslist>  
           <proxy> … </proxy>  
           <module> … </module>  
</defaultProxy>
```

**Comment by rmkerr** [comment]
That's interesting. Are those app.config settings available to the background service accounts & NT-style services you mentioned that don't have access to the registry?

**Comment by davidsh** [comment]
>Are those app.config settings available to the background service accounts & NT-style services you mentioned that don't have access to the registry?

Yes.   app.config works for any .NET Framework EXE. And these same XML settings can be made to machine.config which is a machine-wide config file for .NET.

.NET Core doesn't currently support any config file mechanisms right now except for some JSON style settings file(s) for appcontext switches.
