### ISSUE TITLE
Should performance tests be included in coverage reports?

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#25657]
Currently they are, but I can see some downsides.

1. Running in debug with the overhead of coverage being tracked doesn't give a good performance test (lack of optimisations aside, it could be measuring the time of a debug-only "validate all items in collection" method).
2. They can be among the more long-running tests (System.Memory.Performance.Tests took over 23 minutes today) and the coverage builds are often timing out.
3. They are written with measuring performance rather than correctness in mind. While coverage is like spellcheck in that it's better at telling you you've got someting wrong (spellt rong, or not covered) than got it right (spelled right rather than spilled Wright, covered with sound tests rather than covered but failing to consider permutations it can't reflect), it suggests that there is at least an attempt to confirm the correctness of a path. Anything measured for performance should also be tested for correctness, and coverage should imo reflect the latter (or if anything, reflect the two separately).

**Comment by stephentoub** [comment]
> Currently they are

Aren't they only run in Outerloop with a single iteration, rather than hundreds as is done when they're actually used for perf?

> System.Memory.Performance.Tests took over 23 minutes today

And that's because of the perf tests?

**Comment by JonHanna** [comment]
> Aren't they only run in Outerloop with a single iteration, rather than hundreds as is done when they're actually used for perf?

TIL. That definitely reduces that part of my scepticism. I'm still wondering about the value of coverage from performance tests combined with coverage from correctness tests.

**Comment by stephentoub** [comment]
> the value of coverage from performance tests combined with coverage from correctness tests

a) Do you have evidence that the perf tests make any measurable impact on what shows as covered vs not?

b) Tests that don't assert anything can still have value, in that they demonstrate that code that's expected to run successfully does so.

**Comment by JonHanna** [comment]
b) has convinced me.
