### ISSUE TITLE
Issue with Workaround: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.Binder.InvokeMember'

### ISSUE THREAD

**Issue by scegg** [dotnet/corefx#25672]
Hi all.

Today, while I'm using Roslyn to compile some code under netcoreapp 2, I got such an error:
Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.Binder.InvokeMember'

If you google this, it will point you to add Microsoft.CSharp as reference while calling Roslyn method. But sadly, it's done in my project.

After several hour digging and testing, I found the problem and solution:
It seems that some methods related to Linq are used in my code. Adding **System.Linq.Expressions** as reference to Roslyn fixes the problem.

Note: Images of these references should be loaded only from TRUSTED_PLATFORM_ASSEMBLIES.

**Comment by karelz** [comment]
Does the failure happen when you compiler your project?
How do you compile it? From command line or from Visual Studio?

**Comment by scegg** [comment]
Calling Roslyn Emit method, passing source code and references

**Comment by karelz** [comment]
It sounds like a question specific for Roslyn repo - can you move it there please?

**Comment by scegg** [comment]
Ahh I posted this in a wrong group, sorry.

**Comment by karelz** [comment]
No worries, closing. If it turns out to be problem here, please provide additional information why, ideally with repro without entire Roslyn ;)
