### ISSUE TITLE
Add MemberInfo.IsCollectible & Assembly.IsCollectible

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#25671]
We may wish to treat a collectible assembly or member info differently to a non-collectible. Most obviously, we might want to avoid caching a collectible type or method for a long time and preventing that possible collection. (`Type` has an `IsCollectible` method, but it is not exposed.)

Proposed API:

```C#
namespace System.Reflection
{
    public abstract class Assembly
    {
        public virtual bool IsCollectible { get; }
    }

    public abstract class MemberInfo
    {
        public virtual bool IsCollectible { get; }
    }
}
```

Note that collectibility of assemblies is not the only factor on collectibility of member infos. `TypeBuilder` is derived from `Type` and instances are always collectible.

`TypeDelegator` is itself collectible, but it should report on its delegatee.

**Editted to include all of `MemberInfo` and also `Assembly`.**

**Comment by jkotas** [comment]
cc @AtsushiKan

**Comment by terrajobst** [comment]
Why would this property live on `Type` rather than `Assembly`? My understanding is that we have collectible assemblies, not collectible types IOW collectible types would be typed defined in a collectible assembly, no?

**Comment by JonHanna** [comment]
I was thinking about suggesting it on assemblies too, but for here:

1. Most developers deal with types more often than assemblies.
2. In terms of implementation, types is currently easy (already done, but not exposed), assemblies not (the only approach I can find being used is to get a type from it and examine that).

Assembly might still be worth doing too.

**Comment by karelz** [comment]
I still don't understand why the current implementation in CoreCLR is on Type - is it because of LTG @jkotas?
The only true collectibility is at assembly level ...

**Comment by karelz** [comment]
FYI: The API review discussion was recorded - see https://youtu.be/BI3iXFT8H7E?t=5891 (4 min duration)

**Comment by JonHanna** [comment]
The current implementation might just be because it's needed, since it's internal (and goes back to before corefx) and used internally, with the full implementation being extern. That in itself though shows that the CLR at least had a need for such a property (well, it was a method until yesterday) but not for one on assemblies.

Not that I think exposing that information about assemblies is necessarily without use either; ironically while @jkotas' had clearly been thinking of that CLR method in his suggestion to my looking for a better prediction of collectibility, I found it through a google hit on someone using it to determine if assemblies were collectible, so there's at least one person out there wanting that too.

**Comment by jkotas** [comment]
As @JonHanna said, this is about what the current needs is (collectibility at type level) vs. what the implementation is constrained to today (collectibility at Assembly / AssemblyLoadContext level and Method level). In theory, we can have collectibility at type level at some point in future. E.g. we can have DynamicType that is close sibling of existing DynamicMethod that can live without really having own assembly.

So we have a choice:
1. Expose what matches the constrains of the current implementation. Today, assemblies and methods are individually collectible. So it would make sense to expose Assembly.IsCollectible and MethodBase.IsCollectible.
2. Expose what the current uses care about: Type.IsCollectible
3. Assume that everything can be individually collectible individually, and expose all: Assembly.IsCollectible, Type.IsCollectible and MethodBase.IsCollectible.

**Comment by JonHanna** [comment]
There's perhaps a nomenclature issue in that *Is Collectible* in the sense "is this a thing that can at some point be collected" is perfectly apt for `Type` and indeed is always true for some implementations (`TypeBuilder`, `EnumBuilder`, etc. are all types of `Type` and can all be collected, as indeed can `TypeDelegator` though I would assume that someone asking this of a delegator cares about the delegatee).

Indeed, for runtime types while it's the assembly that dictates whether the type could ever be collected, it's the types that have more effect on whether this happens as the types being reachable keep their assembly alive but the assembly being reachable does not keep its types allive.

*Is Collectible* in the sense of "is this an assembly that has that special condition that allows it and its types to be collected" obviously only applies to assemblies.

I think though that *Is Collectible* is reasonable for "can this ever be collected" and preferable to other terms I could think of (*Is Permanent*, *Is Transient*).

> Assume that everything can be individually collectible eventually, and expose all: Assembly.IsCollectible and MemberInfo.IsCollectible (this covers Type.IsCollectible and MethodBase.IsCollectible).

I think there's a case for all of these. Alas I haven't been able to retrace my google breadcrumbs, but I did come across someone seeking to determine `Assembly.IsCollectible` (accepted answer: get a type from it and use reflection to call `RuntimeTypeHandle.IsCollectible()` on its type handle), and one of the uses of the conservative guessing S.L.Expressions does to determine collectability really wants `MethodBase.IsCollectible`). So if this is feasible, I'll happily change the request to this option.

**Comment by terrajobst** [comment]
Looks good as proposed; my only question is whether we need/should expose this on `TypeInfo` as well?

**Comment by karelz** [comment]
FYI: The API review discussion was recorded - see https://youtu.be/dOpH6bUNbcw?t=992 (8 min duration)

**Comment by JonHanna** [comment]
With the extension from the original proposal, I don't have a good idea about implementation. For `Type` we can just expose what's already there. For `Assembly` the best one can currently do is find a `Type` and see if it is collectible but that doesn't work if there's no types (an edge case admittedly). Other `MethodInfo`s are either `DynamicMethod`s which are collectible, or collectible if they belong to a collectible type.

Am I missing another case?

Are false negatives okay on assemblies with no types? Do we need an external method to give a more dependable answer?

**Comment by jkotas** [comment]
Yes, new calls into the unmanaged portion of the runtime need to be added to handle the method and assembly cases well. https://github.com/dotnet/coreclr/blob/master/Documentation/botr/mscorlib.md#calling-from-managed-to-native-code

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/corefx/pull/33979
