### ISSUE TITLE
build.cmd fails when only VS pre-release is installed

### ISSUE THREAD

**Issue by sebastienros** [dotnet/corefx#25684]
On this line

https://github.com/dotnet/corefx/blob/master/run.cmd#L24

I only have VS2017 15.6 which is pre-release. `vswhere.exe` fails to list it as it now requires the `-prerelease` flag to list these versions. It then falls back to VS14 and fails to build binary assets.

**Comment by karelz** [comment]
We could pass the `-prerelease` flag always, or we could do another call with `-prerelease` when the first call without it fails to find any VS.
@weshaggard any preference?

@sebastienros would you be willing to test the change locally & submit a PR once we decide on the approach?

**Comment by weshaggard** [comment]
We have already started passing "-prerelease" to this in the coreclr repo and we can do the same in corefx. @sebastienros would you mind putting together a PR for this?

**Comment by sebastienros** [comment]
I tried it locally and it works. Creating a PR now.
