### ISSUE TITLE
CoreFX downloads cli every build

### ISSUE THREAD

**Issue by RussellHaley** [dotnet/corefx#25690]
Hi, is there a way to prevent the system from downloading the cli tools every time I build? I'm trying to build on a laptop using a hotspot and it seems unnecessary to download a binary tool every time.

**Comment by karelz** [comment]
@weshaggard @wtgodbe any advice? I would expect we cache the binaries ...

**Comment by weshaggard** [comment]
@RussellHaley we shouldn't be downloading the CLI each time you build, assuming you don't do a full clean --all, in between. Can you give more information on what you are doing? What OS and what commands you are running?

**Comment by wtgodbe** [comment]
Are you referring to https://github.com/dotnet/corefx/blob/master/init-tools.cmd#L48-L58? As Wes mentioned, this should only execute when you build from a clean repo.

**Comment by mikedn** [comment]
This sounds familiar. Same as this one from coreclr https://github.com/dotnet/coreclr/pull/11912 ?

**Comment by wtgodbe** [comment]
@mikedn could be! confirming locally

**Comment by wtgodbe** [comment]
The semaphore file is created for me from a clean repo locally, but maybe it's not consistent across all machine configurations? @russellhadley can you confirm that you have an `init-tools.completed` file inside of `Tools\{ToolsVersion}` ?

**Comment by weshaggard** [comment]
There are possibilities of the semaphore not getting written. See https://github.com/dotnet/source-build/issues/203. It would be good to fix this similar to what dotnet/coreclr#11912 does in corefx.

**Comment by wtgodbe** [comment]
https://github.com/dotnet/corefx/pull/25737 should hopefully resolve

**Comment by wtgodbe** [comment]
@russellhadley can you check out latest CoreFX and see if this still repros? If not, we can close this.

**Comment by RussellHaley** [comment]
Much obliged. I can confirm the change works correctly. The tools report as initialized on a second run.

/*****************************************************/
C:\Users\russh\Git\dotnet\corefx>build.cmd
Tools are already initialized.
Running: C:\Users\russh\Git\dotnet\corefx\src\Native\build-native.cmd x64 Debug Windows_NT --numproc 4 -portable toolSetDir=c:\tools\clr
Tools are already initialized.
Running: C:\Users\russh\Git\dotnet\corefx\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false /l:BinClashLogger,Tools\net46\Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log /p:ConfigurationGroup=Debug /p:BuildPackages=false /p:GenerateNativeVersionInfo=true /flp:v=normal /flp2:warningsonly;logfile=msbuild.wrn /flp3:errorsonly;logfile=msbuild.err C:\Users\russh\Git\dotnet\corefx\src\Native..../build.proj /t:GenerateVersionHeader
Build succeeded.
0 Warning(s)
0 Error(s)
Time Elapsed 00:00:00.07
Command execution succeeded.

**Comment by weshaggard** [comment]
Thanks @RussellHaley for confirming and thanks @wtgodbe for fixing.
