### ISSUE TITLE
System.Runtime.CompilerServices.Unsafe package needs an updated version for other runtimes

### ISSUE THREAD

**Issue by pentp** [dotnet/corefx#25707]
As C# 7.2 is now released there is a need for an updated S.R.CS.Unsafe on runtimes other than .NET Core. I couldn't find any way to get an updated nuget package for S.R.CS.Unsafe, can't even build it from source and the last preview version is from September.

**Comment by karelz** [comment]
@pentp why is it needed for C# 7.2?

**Comment by pentp** [comment]
`ref T AsRef<T>(in T source)` is needed to get writeable references.

**Comment by ahsonkhan** [comment]
@pentp, is this still an issue when using the preview1 packages that were published recently (https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe/4.5.0-preview1-26216-02)?


This package should have the API you were looking for:

> `ref T AsRef<T>(in T source)` is needed to get writeable references.

**Comment by pentp** [comment]
The latest preview version resolves the issue.

**Comment by karelz** [comment]
Closing per comment above
