### ISSUE TITLE
Dotnet Core 2.0.3 Migration | Encoding unable to translate bytes [8B]

### ISSUE THREAD

**Issue by Spaceman1861** [dotnet/corefx#25705]
Hi folks,

Im not sure if this is the correct place for this issue so please tell me if i should move it.

I recently have upgraded one of my apps to use dotnet core 2.0.3 from 1.1.4.

Everything works fine locally but when I deploy to my app service in azure I get the following exception.

```c#
    System.Text.DecoderFallbackException: Unable to translate bytes [8B] at index 1 from specified code page to Unicode. 
```

The code that calls it is a httpclient that talks between the apps.

```c#
    public async Task<T1> Get<T1>(string url, Dictionary<string, string> urlParameters = null) where T1 : DefaultResponse, new()
    {
        var authToken = _contextAccessor.HttpContext.Request.Cookies["authToken"];
        using (var client = new HttpClient().AcceptJson().Acceptgzip().AddAuthToken(authToken))
        {
            var apiResponse = await client.GetAsync(CreateRequest(url, urlParameters));

            T1 output;
            if (apiResponse.IsSuccessStatusCode)
            {
                output = await apiResponse.Content.ReadAsAsync<T1>();
                //output.Succeeded = true;
            }
            else
            {
                output = new T1();
                var errorData = GlobalNonSuccessResponseHandler.Handle(apiResponse);
                output.Succeeded = false;
                output.Messages.Add(errorData);
            }
            return output;
        }
    }

    public static HttpClient AcceptJson(this HttpClient client)
    {
        client.DefaultRequestHeaders.Clear();
        client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        return client;
    }

    public static HttpClient Acceptgzip(this HttpClient client)
    {
        // Commenting this out fixes the issue.
        //client.DefaultRequestHeaders.AcceptEncoding.Add(StringWithQualityHeaderValue.Parse("gzip"));
        client.DefaultRequestHeaders.AcceptEncoding.Add(StringWithQualityHeaderValue.Parse("deflate"));
        return client;
    }

    public static HttpClient AddAuthToken(this HttpClient client, string authToken)
    {
        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", authToken);
        return client;
    }
```

I'm a bit stumped as to whats going on.

So I have 2 apps which we call client and server from now on.

Client uses the above code to talk to the server.

Locally this is fine on azure not so, this all worked fine before upgrading.

So I setup the client locally to talk to the server on azure I was able to replicate the issue.

I had a look at the response in fiddler and it is able to correctly decode it.

I decided to remove gzip and then everything started working.

```c#
    client.DefaultRequestHeaders.AcceptEncoding.Add(StringWithQualityHeaderValue.Parse("gzip"));
```

Can anyone explain this?

SO question for ref
https://stackoverflow.com/questions/47625708/dotnet-core-2-0-3-migration-encoding-unable-to-translate-bytes-8b

[EDIT] Add C# syntax highlighting by @karelz

**Comment by karelz** [comment]
Do you have a minimal repro we can run locally as well? What is the exception call stack?

**Comment by PeterSmithRedmond** [comment]
Looking at the [AutomaticDecompression](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.automaticdecompression?view=netcore-2.0#System_Net_Http_HttpClientHandler_AutomaticDecompression) docs, I'd guess that you need to add GZip and Deflate as an AutomaticDecompression value.  

The "can't convert 8b at index 1" is a hint that you're getting a GZIP response (the header for GZIP starts 1f,8b) and that it's not being automatically decompressed.

**Comment by PeterSmithRedmond** [comment]
BTW: It's a general good practice to create a single HttpClient object and then reuse the created object for multiple requests.

**Comment by Spaceman1861** [comment]
@PeterSmithRedmond you may be onto a winner with that

> When the System.Net.Http NuGet package v4.1.0 to v4.3.2 is used, the default is GZip and Deflate.
> After NuGet package v4.3.2, the default value of None is used.

In relation to the dispose per request structure I agree it needs a refactor.

I will add AutomaticDecompression settings if this fails i will post the stack and create a repo

**Comment by Spaceman1861** [comment]
@PeterSmithRedmond 

Adding the following appears to have fixed the issue.
` new HttpClient(new HttpClientHandler { AutomaticDecompression = DecompressionMethods.GZip })`

This should probably have a clearer error or at the very least be listed on the breaking changes on the doco

https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/
https://github.com/aspnet/announcements/issues?page=1&q=is%3Aissue+is%3Aopen+label%3A2.0.0+label%3A%22Breaking+change%22&utf8=%E2%9C%93

Thanks for the help 👍

**Comment by karelz** [comment]
Closing as external issue then.
