### ISSUE TITLE
RuntimeInformation.OSArchitecture returns wrong value between net461 and netstandard2.0 and loads two different assemblies

### ISSUE THREAD

**Issue by jkotalik** [dotnet/corefx#25706]
## **Example:**
Create a new application and a new library:
`dotnet new console`

Repro.cs:
```csharp
using System;
using System.Runtime.InteropServices;

namespace Repro
{
    class Program
    {
        public static void Main()
        {
            Console.WriteLine(RuntimeInformation.OSArchitecture + typeof(RuntimeInformation).AssemblyQualifiedName);
            var temp = typeof(Environment).GetProperty("Is64BitOperatingSystem", System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Static);
            if (temp != null)
            {
                temp.GetValue(null);
                Console.WriteLine("Is64BitOS: " + temp.GetValue(null));
            }
            ReproLibrary.Class1.Print();
        }
    }
}
```
Repro.csproj:
```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReproLibrary\ReproLibrary.csproj" />
  </ItemGroup>

</Project>
```

Now create a class library called ReproLibrary.
ReproLibrary.cs
`dotnet new classlib`

```csharp
using System;
using System.Runtime.InteropServices;

namespace ReproLibrary
{
    public class Class1
    {
        public static void Print()
        {
            Console.WriteLine(RuntimeInformation.OSArchitecture + typeof(RuntimeInformation).AssemblyQualifiedName);
            var temp = typeof(Environment).GetProperty("Is64BitOperatingSystem", System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Static);
            if (temp != null)
            {
                temp.GetValue(null);
                Console.WriteLine("Is64BitOS: " + temp.GetValue(null));
            }
        }
    }
}
```
ReproLibrary.csproj
```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

</Project>

```

## **Expected Result:**
I expect both RuntimeInformation.OSArchitecture to return the same assembly and return the same results. I also expect them both to return x64 as my OS is 64 bit.

## **Actual Results:**
```
X64 System.Runtime.InteropServices.RuntimeInformation, System.Runtime.InteropServices.RuntimeInformation, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Is64BitOS: True
X86 System.Runtime.InteropServices.RuntimeInformation, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Is64BitOS: True
```

There seems to be two issues here. One is that that the mscorlib library is return x86, which it should not. Secondly, referencing netstandard2.0 and net461 brings two different versions of System.Runtime.InteropServices.RuntimeInformation, which have different behavior. This could be because the machine has net471 on it and the associated issues with it, however it is hard to tell if it is installed.

cc/ @pranavkm @pakrym

**Comment by MichalStrehovsky** [comment]
Related to #25267.

**Comment by weshaggard** [comment]
@AlexGhiondea @joperezr Looks like we might have a issue in the version of RuntimeInformation that we put into .NET Framework.

**Comment by weshaggard** [comment]
>There seems to be two issues here. One is that that the mscorlib library is return x86, which it should not. Secondly, referencing netstandard2.0 and net461 brings two different versions of System.Runtime.InteropServices.RuntimeInformation, which have different behavior. This could be because the machine has net471 on it and the associated issues with it, however it is hard to tell if it is installed.

I agree there appears to be a bug in OSArchitecture returning x86 which should be addressed. 

The reason that you have 2 different assemblies is because of a type unification issue in .NET 4.7.1 where the netstandard.dll that gets loaded directly type-forwards to the RuntimeInformation type in mscorlib instead of forwarding to System.Runtime.InteorpServices.RuntimeInformation as it should be doing. This issue is being fixed as part of other work @joperezr is doing.

**Comment by jkotalik** [comment]
> The reason that you have 2 different assemblies is because of a type unification issue in .NET 4.7.1 where the netstandard.dll that gets loaded directly type-forwards to the RuntimeInformation type in mscorlib instead of forwarding to System.Runtime.InteorpServices.RuntimeInformation as it should be doing. This issue is being fixed as part of other work @joperezr is doing.

Yeah that's what I assumed regarding the NET 471 issues. What version of RuntimeInformation is in mscorlib? Do they include newer bits?

**Comment by weshaggard** [comment]
In .NET 4.7.1 we included RuntimeInformation in the framework and as part of that it got put into mscorlib. I don't think it is newer bits but I do think the bits are slightly different which is where this OSArchitecture bug is coming from.

**Comment by ViktorHofer** [comment]
Correct me if I'm wrong but this sounds like a bug in netfx and not something fixable as port of Core 2.1, right? Setting milestone to future. Do we have a TFS item that tracks this?

**Comment by AlexGhiondea** [comment]
This was fixed in .NET Framework 4.7.2.

@jkotalik there is an Early Access Preview for .NEt4.7.2 that you can try that has this fix.
