### ISSUE TITLE
Serverless performance analysis

### ISSUE THREAD

**Issue by valenis** [dotnet/corefx#25719]
Investigate the performance of Azure Functions

**Comment by tarekgh** [comment]
@DrewScoggins any update on this one?

**Comment by DrewScoggins** [comment]
We did some work to add collection for some small end to end scenarios as well as cold start and you can find the results here, https://benchview/trendline?build_selector=latest&count=100&aggregate=arithmeticMean&filterTail=one&filterVal=100&interval=INTERVAL_MIN_MAX&rtids=[1123]&archids=[9]&mpids=[1318,1315]&cfgids=[2932]&testids=[105461,105460,105457,105456,105458,105455]&jobgroup=Azure%20Function%20Perf&jobtype=rolling&branchId=446&

We wanted to try and work with the Azure team, but were never able to make any headway with them. The data that we collected shows that we are a considerable amount slower in cold start than AWS.

**Comment by tarekgh** [comment]
thanks @DrewScoggins for the update. what is the action we need to take here according to your finding? and should we have this issue for 2.1?

**Comment by stephentoub** [comment]
@adamsitnik, can this be closed?

**Comment by adamsitnik** [comment]
@DrewScoggins do I remember correctly that you got some traces from Azure Functions Team and the problem was solved?

**Comment by DrewScoggins** [comment]
I think we can go ahead and close this. I was never able to get any traction from their side and I will not be pushing on this any longer. Maybe @billwert or @brianrob would have an opinion as well.
