### ISSUE TITLE
IEnumerable.Single and IEnumerable.SingleOrDefault that take a predicate evaulate the entire range of the IEnumerable

### ISSUE THREAD

**Issue by kstreith** [dotnet/corefx#2571]
As seen in the current code for IEnumerable.Single, the entire range of the IEnumerable is evaluated against the provided predicate.

This evaluation could be terminated early once 2 items in the enumeration match the predicate, since Single must throw an exception if anything other than 0 or 1 items match the predicate.

Making this change is straightforward, I would be able to submit the required patch and this would improve the performance of .Single and .SingleOrDefault when using a predicate on large IEnumerable ranges.

Please advise if this would be considered a valid issue and if a patch for this issue would be accepted.

![image](https://cloud.githubusercontent.com/assets/288973/8988029/fac97b3c-36b1-11e5-94e9-9842e02e16e4.png)

**Comment by stephentoub** [comment]
I believe this is a dup of https://github.com/dotnet/corefx/issues/2349.

**Comment by kstreith** [comment]
Yes, I agree, hadn't seen that issue. This can be closed.
