### ISSUE TITLE
Competitive performance analysis

### ISSUE THREAD

**Issue by valenis** [dotnet/corefx#25723]
Competitive performance analysis across various managed stacks and environments

**Comment by tarekgh** [comment]
@valenis who you think this should be assigned to? I am seeing you marked for 2.1

**Comment by tarekgh** [comment]
@valenis @karelz do you know who is following up with this? we should assign this to some owner.

**Comment by valenis** [comment]
Moving this to post 2.1

**Comment by stephentoub** [comment]
@adamsitnik, can this be closed?

**Comment by adamsitnik** [comment]
@stephentoub We made it very easy to compare Core vs Desktop vs Mono vs CoreRT for all Operating Systems. The question is: was this issue originally about making it possible or making it possible, doing it and sharing some summary?

**Comment by stephentoub** [comment]
> The question is

I have no idea.  The description is cryptic ;)

**Comment by karelz** [comment]
Unclear, closing. The right things are happening.
