### ISSUE TITLE
Performance scenarions: RWC workloads

### ISSUE THREAD

**Issue by valenis** [dotnet/corefx#25721]
Bring up Real World Code scenarios for benchmarking

**Comment by tarekgh** [comment]
@jorive any update in this?

**Comment by jorive** [comment]
@tarekgh we are working on bringing RWC scenarios to different repos across dotnet. There are some already added in [coreclr](https://github.com/dotnet/coreclr), but ultimately we will be adding them to a stand alone .NET performance repository. This way we should be able to run against different dotnet repos.
I have moved this issue to future, and will add more details in the near future.

**Comment by jorive** [comment]
Some of the .NET real-world code benchmarks are here: https://github.com/dotnet/performance, and there is an effort to bring up some more.
I'm closing this issue, but feel free to open a new one, in https://github.com/dotnet/performance, if you have an specific real-world code benchmarks that should be brought up.
