### ISSUE TITLE
Cross-platform performance analysis: Linux/Mac/Windows

### ISSUE THREAD

**Issue by valenis** [dotnet/corefx#25722]
Cross-platform performance analysis: Linux/Mac/Windows

**Comment by tarekgh** [comment]
@valenis who you think this should be assigned to?

**Comment by tarekgh** [comment]
@valenis @karelz do you know who is following up with this? we should assign this to some owner.

**Comment by valenis** [comment]
Moving this to post 2.1

**Comment by stephentoub** [comment]
@adamsitnik, can this be closed?

**Comment by adamsitnik** [comment]
@stephentoub we upload the results for Windows and Ubuntu to BenchView now. But was the expected output of this task to produce some kind of summary?

**Comment by stephentoub** [comment]
> But was the expected output of this task to produce some kind of summary?

No idea.  Since we don't know what it is and no one's working on it, I'm going to close it.  Thanks.
