### ISSUE TITLE
Add proper build leg to CI for corefx native components

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#2573]
To get things bootstrapped, I made the run-test.sh script build the native components in the test phase. We should remove that hack and add the appropriate build leg.

In particular, not doing it as a build leg is preventing the binaries from being archived, which is needed to unblock some other work that @chcosta is doing.

cc @ellismg

**Comment by mmitche** [comment]
Thanks

**Comment by ellismg** [comment]
@mmitche Added this.  Thanks!
