### ISSUE TITLE
Handling of SIGINT, SIGQUIT when SIG_IGN

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#25749]
When dotnet is started with SIGINT, SIGQUIT set to SIG_IGN it should not change the disposition of those signals.

A shell may set these to SIG_IGN to ensure a background process it not killed.
See https://unix.stackexchange.com/questions/356408/strange-problem-with-trap-and-sigint

When set to SIG_IGN, we should keep it at that value because it also affects child processes. If the disposition is changed, the child process will reset to the SIG_DFL.

This means the `Console.CancelKeyPress` will no longer fire. I think this matches with what the shell is trying to achieve.

**Comment by tmds** [comment]
CC @stephentoub

**Comment by stephentoub** [comment]
Seems reasonable.  It should just be a matter of changing:
https://github.com/dotnet/corefx/blob/33ec2994d85935b6c62df0792aef88b285d6c765/src/Native/Unix/System.Native/pal_console.cpp#L480-L485
to first check the current value by calling sigaction with a null second argument and then only proceeding to do this code if it's not SIG_IGN.

**Comment by tmds** [comment]
Implemented in https://github.com/dotnet/coreclr/pull/15393 and https://github.com/dotnet/corefx/pull/25753
