### ISSUE TITLE
"Access is denied" when calling IPGlobalProperties.GetActiveUdpListeners on UWP

### ISSUE THREAD

**Issue by anders9ustafsson** [dotnet/corefx#25752]
I have a UWP application (minimum version set to 16299, Fall Creators Update) that consumes a .NET Standard 2.0 class library.

```c#
using System.Net.NetworkInformation;

IPGlobalProperties properties = IPGlobalProperties.GetIPGlobalProperties();
IPEndPoint[] endPoints = properties.GetActiveUdpListeners();
```
When calling `IPGlobalProperties.GetActiveUdpListeners()`, I get an *Access is denied* `NetworkInformationException`.

I have enabled internet (client and server) and intranet capabilities as well as enterprise authentication and system information, all to no avail. 

Am I doing something wrong? Limitation? Bug?

>System.Net.NetworkInformation.NetworkInformationException
  HResult=0x80004005
  Message=Access is denied
  Source=System.Net.NetworkInformation
  StackTrace:
   at System.Net.NetworkInformation.SystemIPGlobalProperties.GetActiveUdpListeners()
   at SIPSorcery.Sys.Net.FreePort.FindNextAvailableUDPPort(Int32 startPort)
   at ...

**Comment by davidsh** [comment]
You probably need to have additional capabilities defined in your UWP manifest.  For example, do you have "Intranet" defined, i.e. "Private client/server" capability.  Can you attach your manifest file and/or list the XML for it here in this issue.

**Comment by anders9ustafsson** [comment]
As I mentioned above, I have tested all capabilities that seemed remotely relevant, including Internet, Intranet, Enterprise Authentication, System Management, Remote System. None of them made any difference. If it matters, my tests were made in debug mode on the local machine.

**Comment by anders9ustafsson** [comment]
If there is another capability other than those I have listed above, I am eager to try it. Just point me in the right direction.

**Comment by davidsh** [comment]
Update:

It seems all of these APIs throw "Access Denied".

* IPGlobalProperties.GetActiveTcpConnections();
* IPGlobalProperties.GetActiveTcpListeners();
* IPGlobalProperties.GetActiveUdpListeners();

This error is coming from the Win32 API call that is used to get the TCP / UDP network information. It seems that while these APIs are documented for use in a UWP app, some of them are not working and are returning "Access is denied".  This is likely a problem with the Windows OS itself. This will need to be research with the Windows OS team.

cc: @karelz

**Comment by queequac** [comment]
Stumbled into exactly the same issue.
Any news on this?

**Comment by davidsh** [comment]
>Stumbled into exactly the same issue.
Any news on this?

Unfortunately, there are no updates at this time.  The problem stems from an issue in the Windows OS layer which is causing the "Access denied" errors to bubble up to the .NET API calls.

cc: @karelz

**Comment by davidsh** [comment]
Unfortunately, this is still a limitation for UWP apps regardless of the capabilities you enable in the UWP Package.appxmanifest file.

If this functionality is required for your app development, I suggest you submit to the portal here:
https://wpdev.uservoice.com/forums/110705-dev-platform

Perhaps a future Windows platform SDK will enable these APIs to work for UWP apps.

At this time, we will close the issue since there is nothing that can be fixed in .NET Core for this.
