### ISSUE TITLE
Consolidate UTF8 inspection / processing APIs to a single assembly

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/corefx#25759]
This is a tracking issue for our ZenHub Security Epic.

**Comment by GrabYourPitchforks** [comment]
This is a tracking issue for our ZenHub Security Epic.

**Comment by GrabYourPitchforks** [comment]
Potential APIs that would be part of this assembly:

- `Utf8Char` (or whatever type we use to represent a UTF8 code unit)
- Validate the well-formedness of a UTF8 string
- Get UTF16 / UTF32 code unit count from a UTF8 string (and vice versa)
- Convert UTF8 string to UTF16 / UTF32 string (and vice versa)
- Convert invalid UTF8 string to valid UTF8 string (via invalid char replacement)
- Forward and reverse enumeration of scalars from a UTF8 string

**Comment by stephentoub** [comment]
@GrabYourPitchforks, a lot (all?) of this is tracked in other issues, or already completed, right? Can this be closed then? Thanks.
