### ISSUE TITLE
Span tag in the xml documentation for System.Diagnostics.DiagnosticSource.4.4.1

### ISSUE THREAD

**Issue by vonlar** [dotnet/corefx#25764]
There's a span tag being generated in the System.Diagnostics.DiagnosticSource.xml file
`<?xml version="1.0" encoding="utf-8"?><span>
<doc>
  <assembly>
    <name>System.Diagnostics.DiagnosticSource</name>
  </assembly>`

I was unable to figure out how or where the span tag is getting added.

**Comment by karelz** [comment]
Where is the documentation file generated? Is it in CoreFX source code? Or is it part of docs repo?
Why does it matter what is in the XML file? What breaks? What doesn't work?

**Comment by vonlar** [comment]
So the documentation file gets automatically generated during the compilation process.  It looks at the source code comments and creates it from the comments.  How it managed to get a span tag in there I have no clue, I've never seen this ever happen since it's the compiler that creates it.

It's possible that the tag would keep Intellisense from working.  But in my use case, it's blocking down chain documentation from building.

**Comment by brianrob** [comment]
Looks like this was fixed by #27005.
