### ISSUE TITLE
ASP.NET Web Forms build fails after updating to Visual Studio 15.5 (SharedCompilationId parameter)

### ISSUE THREAD

**Issue by Quppa** [dotnet/corefx#25767]
After updating to Visual Studio 15.5, the two ASP.NET Web Forms projects in our solution are failing to build with the following errors:
```
29>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(137,10): error MSB4064: The "SharedCompilationId" parameter is not supported by the "Csc" task. Verify the parameter exists on the task, and it is a settable public instance property.
29>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error MSB4063: The "Csc" task could not be initialized with its input parameters.
```

I can work around the issue by removing the line `SharedCompilationId="$(SharedCompilationId)"` from the `Csc` element in `Microsoft.CSharp.Core.targets`.

Every project in our solution is using the latest version of `Microsoft.Net.Compilers` (2.4.0) and the web projects are using the latest version of `Microsoft.CodeDom.Providers.DotNetCompilerPlatform` (1.0.8). Our ASP.NET MVC and ASP.NET Web API projects are building without issue.

A new Web Forms project with the same Nuget compiler packages installed doesn't exhibit the issue. I'll try to find time later to do a diff between the CSPROJ files.

**Comment by karelz** [comment]
I have no idea where to route this issue. I would recommend to file VSFeedback from within VS.
It may not be specific to ASP.NET Web Forms. Probably a problem between C# and msbuild ...

**Comment by Quppa** [comment]
@karelz All right - I've submitted it via VS Feedback.

**Comment by karelz** [comment]
Great, hopefully it will be better routed there (it seems like the best place to me at least).
