### ISSUE TITLE
MSB3277 warnings when building aspnetcore while referencing newest 2.1 runtime

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/corefx#25766]
Scanning through our build logs after we tried to ingest the newest shared runtime, I'm beginning to see warnings from msbuild: `C:\Users\johluo\.dotnet\x64\sdk\2.2.0-preview1-007522\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3277: Found conflicts between different versions of "System.Security.Cryptography.Cng" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\gh\tp\TestDeps\TestDeps.csproj]`. A simplified repro is available at https://github.com/JunTaoLuo/PackageConflictWarnings. I've also included the diagnostic build log as build.log in the repro.

cc @weshaggard @pranavkm @natemcmaster 

related: https://github.com/aspnet/Universe/issues/671

`dotnet --info`:
```
.NET Command Line Tools (2.2.0-preview1-007522)

Product Information:
 Version:            2.2.0-preview1-007522
 Commit SHA-1 hash:  d58fc6120d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\johluo\.dotnet\x64\sdk\2.2.0-preview1-007522\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-25914-0
  Build    : 352f0c04c28a53a47eaec4fccff002a813e40c60
```

**Comment by danmosemsft** [comment]
Should this be 2.1?
```xml
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeFrameworkVersion>2.1.0-preview1-25915-01</RuntimeFrameworkVersion>
```

**Comment by weshaggard** [comment]
Yes. The 2.1 package doesn't work with netcoreap20

**Comment by natemcmaster** [comment]
Which package? Microsoft.NETCore.App or System.Security.Cryptography.Cng?

**Comment by weshaggard** [comment]
Microsoft.NETCore.App 2.1.* only works with netcoreapp2.1 framework.

**Comment by natemcmaster** [comment]
Are there any plans to change the Microsoft.NETCore.App 2.1.0-* package to only target .NETCoreApp2.1? If the package can't work on .NETCoreApp2.0, I don't see why there would be a problem removing this from its nuspec.

**Comment by weshaggard** [comment]
We have issue https://github.com/dotnet/core-setup/issues/2437/ tracking the work to figure out how to handle the different netcoreapp TFM's from this package. We were originally going to try and keep support for all the older TFM's but the more we look into that the more we realize the amount of maintenance cost to do so so I expect before we ship 2.1 we will make this package only work for netcoreapp2.1

**Comment by natemcmaster** [comment]
Ok, thanks for clarifying.

**Comment by pranavkm** [comment]
I'm also seeing this when referencing the 4.5.0 version of the System.Security.Cryptography.Cng package from a netcoreapp2.0 (referencing M.N.A 2.0.0):

```
References which depend on "System.Security.Cryptography.Cng, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" 
 C:\Users\Pranav\.nuget\packages\system.security.cryptography.cng\4.5.0-preview1-25914-04\ref\netcoreapp2.0\System.Security.Cryptography.Cng.dll
   Project file item includes which caused reference "C:\Users\Pranav\.nuget\packages\system.security.cryptography.cng\4.5.0-preview1-25914-04\ref\netcoreapp2.0\System.Security.Cryptography.Cng.dll".
     C:\Users\Pranav\.nuget\packages\system.security.cryptography.cng\4.5.0-preview1-25914-04\ref\netcoreapp2.0\System.Security.Cryptography.Cng.dll
References which depend on "System.Security.Cryptography.Cng, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [].
 C:\Users\Pranav\.nuget\packages\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.Core.dll
   Project file item includes which caused reference "C:\Users\Pranav\.nuget\packages\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.Core.dll".
     C:\Users\Pranav\.nuget\packages\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.Core.dll
```

**Comment by weshaggard** [comment]
>C:\Users\Pranav\.nuget\packages\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.Core.dll

Something seems off with your package cache. My System.Core.dll on my machine references System.Security.Cryptography.Cng version 0.0.0.0, as expected. Can you double check your version in ILDasm to see if it shows the same?

**Comment by pranavkm** [comment]
> `ildasm C:\Users\Pranav\.nuget\packages\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.Core.dll`
```
.assembly extern System.Security.Cryptography.Cng
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 0:0:0:0
}
```

**Comment by weshaggard** [comment]
Yes that is what it is supposed to be. I don't know why your msbuild log is saying it references 4.3.1.0 version of the library then.

**Comment by anurse** [comment]
Is there some resolution to this? I'm seeing this in quite a few ASP.NET Core repos (basically any project referencing Kestrel will see it as Kestrel references System.Security.Cryptography.Cng)

**Comment by pranavkm** [comment]
@weshaggard would you like me to get a repro app for you? In my case, all I did was attempt to build one of the samples in Kestrel referencing these specific package versions.

**Comment by weshaggard** [comment]
Sure if you have repro project I'm happy to take a look.

**Comment by pranavkm** [comment]
I verified building the dev branch of https://github.com/aspnet/KestrelHttpServer/ produces this warning. Specifically building https://github.com/aspnet/KestrelHttpServer/tree/dev/samples/SampleApp produces the warning.

**Comment by weshaggard** [comment]
I've found the issue and filed https://github.com/dotnet/corefx/issues/25870 to track fixing it.

**Comment by weshaggard** [comment]
The underlying issue should be fixed with https://github.com/dotnet/corefx/pull/25925. So there shouldn't be an assembly version mismatch any longer.
