### ISSUE TITLE
The type initializer for 'System.Net.Http.CurlHandler' threw an exception

### ISSUE THREAD

**Issue by tengl** [dotnet/corefx#25774]
Hi,

I'm getting a weird error while running my server under CentOS. It said it is **"Unable to load DLL 'System.Net.Http.Native'"** (see exception below), and it only occurs when I start the server during startup using systemd or manually in Linux Screen, not in regular shell (Bash, PuTTY). 

Why is this happening? From what I have found on Google, it seems to be an issue with openssl-libs, but how come it is working in the shell?

Being quite new to Linux I don't know the difference between the environments. 

More details below
---------
I use the same user in all cases.
The systemd .service is minimal, default type, only an After=network.target
The server does not use TLS/SSL encryption. 

CentOS Linux release 7.4.1708 (Core)
Dotnet --version 2.0.3

Here is a list of the [dependencies](https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x) (according to Yum). I've updated all packages so there are not later version available (in Yum).  

```
libunwind.x86_64         2:1.2-2.el7 
lttng-ust.x86_64         2.4.1-4.el7)
libcurl.x86_64           7.29.0-42.el7_4.1 
openssl-libs.x86_64      1:1.0.2k-8.el7 
libuuid.x86_64           2.23.2-43.el7_4.2
krb5-libs.x86_64         1.15.1-8.el7   
libicu.x86_64            50.1.2-15.el7     
zlib.x86_64              1.2.7-17.el7 
```

```
System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Http' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Net.Http.Native': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.Http.GetSslVersionDescription()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at Veridict.LiveMap.ServerPlatform.Modules.GtfsRt.GtfsRtModule.Run()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by Priya91** [comment]
@tengl System.Net.Http.native is a native shim that's installed by .net core and consumed by the networking libs during execution. It looks like the way you are calling your app this dll is not found. Can you add the .netcore install location to the path, so that it finds this dll, I'm not sure how systemd works to find the dependencies.

**Comment by karelz** [comment]
@wfurt can you please advise here as Linux expert?

**Comment by wfurt** [comment]
Typically you environment variables are different when running as a service, so as actual user. 
You may also check if SELinux is enabled and if you can look at your policies or you can try to disable it to see, if that would make a difference. 
Your description is lacking details on how _exactly_ you trying to run the service. 

When you say "Linux screen" you mean "screen" utility e.g. /usr/bin/screen ~/mycoolapp ??? 

There are few things you may try @tengl 
The easy thing to do would be creating shell scrip wrapper and perhaps printing PATH, LD_LIBRARY_PATH etc. 
Second lins may be using strace. You can try something like "/usr/bin/strace -f -s 200 ~/mycoolapp 2>/tmp/service.trace.txt"
and then grep -e libcurl -e libcrupto -e libss /tmp/service.trace.txt

You may see some failing system calls and that may give you some clues.

**Comment by tengl** [comment]
Thanks for the hints, it seems that it might be LD_LIBRARY_PATH that was missing. Thought the variables were identical, but they weren't. Will confirm on monday. 

Btw, yes, @Priya91, it was the screen utility. Good to know, easier to trace errors there than in a service.

**Comment by tengl** [comment]
Confirmed. 
Adding `Environment="LD_LIBRARY_PATH=/opt/rh/rh-dotnet20/root/usr/lib64"` to .service file did the trick.
Thanks

**Comment by tmds** [comment]
@tengl I guess you have hard-coded `dotnet` to the path in the rh-dotnet20 software collection (scl)? Instead, you should enable the dotnet scl, then it will put `dotnet` on `PATH` and set `LD_LIBRARY_PATH` for you. The command-line in your service file should be something like `/usr/bin/scl enable rh-dotnet20 -- dotnet <your assembly>`.

**Comment by tmds** [comment]
@wfurt fyi, software collections are a way of packaging on RHEL/CentOS that allow including native libraries needed for an scl, without updating the 'global' system libraries (which could break existing applications). For dotnet we use it to include a different version of libcurl.

**Comment by tengl** [comment]
Thanks @tmds, that's better than hard coded paths..
