### ISSUE TITLE
API Addition: Add Lazy<T>(T value) constructor that just takes the value

### ISSUE THREAD

**Issue by justinvp** [dotnet/corefx#2578]
Consider adding a constructor to `Lazy<T>`, e.g. `public Lazy(T value)`, for cases where the value is already available but still needs to be wrapped in a `Lazy<T>` instance to match other uses.

## Rationale

There are situations where a value is already available but still needs to be wrapped in a `Lazy<T>`, e.g.:

```c#
string value = ...;
Lazy<string> lazy = new Lazy<string>(() => value);
```

Unfortunately, this requires two extra allocations: one for the `Func<string>` delegate and another for the closure around `value`.

A new constructor on `Lazy<T>` that just takes the value would avoid these unnecessary delegate and closure allocations, e.g.:

```c#
string value = ...;
Lazy<string> lazy = new Lazy<string>(value);
```

## Proposed API

```c#
public class Lazy<T>
{
    // Proposed
    public Lazy(T value);

    // Existing
    public Lazy();
    public Lazy(bool isThreadSafe);
    public Lazy(LazyThreadSafetyMode mode);
    public Lazy(Func<T> valueFactory);
    public Lazy(Func<T> valueFactory, bool isThreadSafe);
    public Lazy(Func<T> valueFactory, LazyThreadSafetyMode mode)

    ...
}
```

**Comment by justinvp** [comment]
In the meantime, it's worth mentioning that @AArnott and @nguerrera came up with a way to [avoid the closure allocation](https://gist.github.com/AArnott/d285feef75c18f6ecd2b) in such cases. However, this trick still doesn't eliminate the delegate allocation.

**Comment by justinvp** [comment]
cc @stephentoub @terrajobst

**Comment by nguerrera** [comment]
I like it. Let's do it.

**Comment by bartonjs** [comment]
I'm definitely a fan.

**Comment by AArnott** [comment]
Yes, I made this same request with an internal bug on the .NET Framework, IIRC.

**Comment by terrajobst** [comment]
API addition looks fine.

@AlexGhiondea, it seems you'd own this :-)

**Comment by jasonwilliams200OK** [comment]
@justinvp, just out of curiosity; if something like this:

```c#
/// <summary>
/// Initializes a new instance of the <see cref="T:System.Threading.Lazy{T}"/> class that
/// uses a pre-initialized specified value.
/// </summary>
/// <remarks>
/// An instance created with this constructor should be usable by multiple threads
//  concurrently.
/// </remarks>
public Lazy(T value)
{
    m_boxed = (Boxed)value;
}
```

is added here: https://github.com/dotnet/coreclr/blob/21f8416/src/mscorlib/src/System/Lazy.cs#L182

would it save an extra `Boxed` allocation? (I mean `new Boxed(value)` vs. `(Boxed)value` given the context)

**Comment by justinvp** [comment]
@jasonwilliams200OK, it'd be nice if the internal `Boxed` allocation could be avoided.

**Comment by jasonwilliams200OK** [comment]
Yes that would be nice and as is the internal `Value` getter is relying on `Boxed` type to detect whether or not `m_boxed` field is initialized. I think with current implementation only `m_boxed = new Boxed(value);` would go: `(Boxed)value` gives compilation error and `value as Boxed` fails the check `(value as boxed) != null`.. :(

**Comment by justinvp** [comment]
@jkotas, this was closed automatically when https://github.com/dotnet/coreclr/pull/6304 was merged. Should this be re-opened to track exposing the new API in the contract, or should we open a new issue to track?

**Comment by jkotas** [comment]
I guess we may want to open a new issue ... because of this one will keep getting closes as the change is merged around.

**Comment by jasonwilliams200OK** [comment]
Should we add tests to https://github.com/dotnet/corefx/blob/bb25242/src/System.Runtime/tests/System/LazyTests.cs along with addition to ref? For example a test can Assert.True on `new Lazy<string>("hello").IsValueCreated` etc.

**Comment by justinvp** [comment]
> Should we add tests

Yes, adding tests would be good. I'll open a new issue to track adding to the contract and adding tests.

**Comment by justinvp** [comment]
#10127
