### ISSUE TITLE
Alpine.3.6 x64 Debug Build build fails

### ISSUE THREAD

**Issue by lmolkova** [dotnet/corefx#25783]
```
chmod: cannot access '/mnt/j/workspace/dotnet_corefx/master/alpine-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/bin/testhost/netcoreapp-Linux-Debug-x64/dotnet': No such file or directory
12:16:36 /mnt/j/workspace/dotnet_corefx/master/alpine-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/external/runtime/runtime.depproj(73,5): error MSB3073: The command "chmod +x /mnt/j/workspace/dotnet_corefx/master/alpine-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/bin/testhost/netcoreapp-Linux-Debug-x64/dotnet" exited with code 1.
```

https://ci3.dot.net/job/dotnet_corefx/job/master/job/alpine-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/14/consoleFull

**Comment by karelz** [comment]
@janvorli @weshaggard any idea what's going on?

**Comment by janvorli** [comment]
I bet it is an issue with dotnet host nuget package restoring. I've seen that at some point in the past when the core-setup packages were not being built yet. I wonder if it is possible that a specific version of the package is missing on myget. The restore seems to restore nothing in that case and doesn't fail for some reason.

**Comment by karelz** [comment]
How did you make that connection based on the log above? Did you find more evidence in the full log?

**Comment by janvorli** [comment]
No, just the fact that the dotnet file is missing was the evidence. The sync.sh should have restored the package that contains dotnet, but there is nothing logged about it being restored and also no error. I know that the sync.sh is supposed to do that.

**Comment by janvorli** [comment]
I will locally check which version of the dotnet host package it is trying to pull and see if my theory is correct.

**Comment by joshfree** [comment]
Just hit this issue during PR https://github.com/dotnet/corefx/pull/25802

https://ci3.dot.net/job/dotnet_corefx/job/master/job/alpine-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/59/console

**Comment by janvorli** [comment]
@joshfree The change is not in yet, there is a problem, the version change of dotnet host package causes Invariant.Tests test failure over all platforms.

**Comment by weshaggard** [comment]
I disabled

**Comment by steveharter** [comment]
The last 3 core-setup builds have been [failing ](https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1216037&_a=summary)on alpine.3.6-x64. Related?

The [error ](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1216040)message:
```
2017-12-12T15:18:51.4617580Z Running: /root/coresetup/packages/microsoft.dotnet.buildtools/2.1.0-prerelease-02311-01/lib/init-tools.sh /root/coresetup /root/coresetup/Tools/dotnetcli/dotnet /root/coresetup/Tools
2017-12-12T15:18:52.0419570Z ##[error]/usr/bin/docker failed with return code: 1
2017-12-12T15:18:52.0476990Z ##[error]/usr/bin/docker failed with error: /usr/bin/docker failed with return code: 1
```

**Comment by janvorli** [comment]
No, this is a different issue, see https://github.com/dotnet/core-eng/issues/2260.

**Comment by weshaggard** [comment]
I believe this was fixed with https://github.com/dotnet/corefx/pull/25868.
