### ISSUE TITLE
Some tests in consumptive perf metrics failing

### ISSUE THREAD

**Issue by mmitche** [dotnet/corefx#2579]
System.IO.FileSystem.Tests.DirectoryInfo_Delete_bool.WindowsExtendedDirectoryWithSubdirectories [FAIL]
        System.IO.PathTooLongException : The specified file name or path is too long, or a component of the specified path is too long.
        Stack Trace:
           d:\j\workspace\dotnet_corefx_perf_consumptive_windows\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs(109,0): at System.IO.Win32FileSystem.CreateDirectory(String fullPath)
           d:\j\workspace\dotnet_corefx_perf_consumptive_windows\src\System.IO.FileSystem\src\System\IO\DirectoryInfo.cs(90,0): at System.IO.DirectoryInfo.CreateSubdirectoryHelper(String path)
           d:\j\workspace\dotnet_corefx_perf_consumptive_windows\src\System.IO.FileSystem\src\System\IO\DirectoryInfo.cs(77,0): at System.IO.DirectoryInfo.CreateSubdirectory(String path)
           d:\j\workspace\dotnet_corefx_perf_consumptive_windows\src\System.IO.FileSystem\tests\Directory\Delete.cs(98,0): at System.IO.FileSystem.Tests.Directory_Delete_str.WindowsExtendedDirectoryWithSubdirectories()
     System.IO.FileSystem.Tests.Directory_Delete_str_bool.WindowsExtendedDirectoryWithSubdirectories [FAIL]
        System.IO.PathTooLongException : The specified file name or path is too long, or a component of the specified path is too long.
        Stack Trace:
           d:\j\workspace\dotnet_corefx_perf_consumptive_windows\src\System.IO.FileSystem\src\System\IO\Win32FileSystem.cs(109,0): at System.IO.Win32FileSystem.CreateDirectory(String fullPath)
           d:\j\workspace\dotnet_corefx_perf_consumptive_windows\src\System.IO.FileSystem\src\System\IO\DirectoryInfo.cs(90,0): at System.IO.DirectoryInfo.CreateSubdirectoryHelper(String path)
           d:\j\workspace\dotnet_corefx_perf_consumptive_windows\src\System.IO.FileSystem\src\System\IO\DirectoryInfo.cs(77,0): at System.IO.DirectoryInfo.CreateSubdirectory(String path)
           d:\j\workspace\dotnet_corefx_perf_consumptive_windows\src\System.IO.FileSystem\tests\Directory\Delete.cs(98,0): at System.IO.FileSystem.Tests.Directory_Delete_str.WindowsExtendedDirectoryWithSubdirectories()

http://dotnet-ci.cloudapp.net/job/dotnet_corefx_perf_consumptive_windows/lastFailedBuild/consoleFull

Failing since commits in this change:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx_perf_consumptive_windows/60/

**Comment by mmitche** [comment]
@JeremyKuhne Could this be from your change: https://github.com/dotnet/corefx/commit/0721434e19e7f9ecf8bf6dba7485f6c86827388c

**Comment by JeremyKuhne** [comment]
@mmitche Probably- I'm guessing this run is using published packages only?

**Comment by mmitche** [comment]
It's just the stock corefx build with a  couple extra switches thrown.  What are you thinking?

It's possible that the dotnet_corefx_perf_consumptive_windows part of the path is causing the path length to become long, but I am not sure whether that would be considered a test bug or an infra bug in this case.

**Comment by JeremyKuhne** [comment]
Ok, then not that. I see the path now as well. That is probably pushing it just over the edge. I'll look to see if I can unblock this by allowing the longer lengths through (just hadn't gotten there yet).

**Comment by JeremyKuhne** [comment]
Sorry, this took quite a bit of digging to understand exactly what is going on with max directory length. Now that I understand exactly what is going on I'm looking at unblocking it correctly.

**Comment by JeremyKuhne** [comment]
Should be resolved with #2700.
