### ISSUE TITLE
NamedPipeServerStream creates a socket not a fifo on ubuntu

### ISSUE THREAD

**Issue by huiguochen** [dotnet/corefx#25792]
I expected to use NamedPipeServerStream  to create a fifo file on linux,  but it created a socket Named "CoreFxPipe_1.fifo"  in /tmp directory.
here is test code:
```c#
            NamedPipeServerStream fifo = new NamedPipeServerStream("1.fifo",PipeDirection.InOut);
            fifo.WaitForConnection();
```
what is the reason? how to create a fifo on linux?

[EDIT] Add C# syntax highlighint by @karelz

**Comment by mikedn** [comment]
See https://github.com/dotnet/corefx/issues/1849

**Comment by eerhardt** [comment]
Thanks @mikedn.  #1849 answers this question, and along with the description of the PR that changed from fifo to sockets - #6833.

Closing as this is answered.

**Comment by DrSensor** [comment]
Any workaround or specific param like `NamedPipeServerStream("1.fifo",PipeDirection.Out, nounixsocket: true)` to use linux named pipe instead of unix socket? It break the compatibility when in use for communicating between 2 different programming language.

> FYI: [Windows 10 now support unix socket](https://blogs.msdn.microsoft.com/commandline/2018/02/07/windowswsl-interop-with-af_unix/)

**Comment by eerhardt** [comment]
You can use the [Mono.Posix.NetStandard](https://www.nuget.org/packages/Mono.Posix.NETStandard/) library on .NET Core to get access to the [mkfifo](https://github.com/mono/mono/blob/47187bbc9b552f6ca5b2d80a2be6c7395b40da9e/mcs/class/Mono.Posix/Mono.Unix.Native/Syscall.cs#L4013-L4017) POSIX command.  This will allow your program to read/write to a FIFO/Unix named pipe.

Regarding Windows 10 now supporting unix domain sockets, .NET Core allows that as well if you are running on a Windows 10 machine that has support for UDS.  See https://github.com/dotnet/corefx/pull/27631 for the PR that added support for it.
