### ISSUE TITLE
Core doesn't read the server certificate

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#25816]
@hammond-of-texas commented on [Fri Dec 08 2017](https://github.com/dotnet/core/issues/1142)

# Issue Title

Core doesn't read the server certificate

# General

In general, a simple request like this will work in .Net:

```c#
        static void Main(string[] args)
        {
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create("https://www.sbb.ch");
            HttpWebResponse response = (HttpWebResponse) request.GetResponse();
            X509Certificate cert = request.ServicePoint.Certificate;
        }
```

The same thing will fail in core 2.0 with a "System.PlatformNotSupportedException: 'Operation is not supported on this platform.'" exception.

---

@richlander commented on [Sat Dec 09 2017](https://github.com/dotnet/core/issues/1142#issuecomment-350486532)

PTAL @davidsh

**Comment by davidsh** [comment]
`ServicePointManager` and `ServicePoint` are not supported on .NET Core.

To get the server certificate associated with a HTTPS request, you can assign a delegate to[ServicePointManager.ValidationCallback](https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.servercertificatevalidationcallback?view=netframework-4.7#System_Net_ServicePointManager_ServerCertificateValidationCallback) and then it will get called with the certificate.

**Comment by davidsh** [comment]
cc: @karelz

**Comment by karelz** [comment]
@hammond-of-texas I have noticed your thumbs up on previous answer. Does it mean you are now unblocked?

BTW: `HttpWebRequest` is flagged as deprecated API by our [platform compat tool](https://github.com/dotnet/platform-compat). We recommend to move to `HttpClient`.

**Comment by karelz** [comment]
No response for 17 days, assuming the response above was satisfactory.
Closing.
