### ISSUE TITLE
My build is failing  on Windows 10 

### ISSUE THREAD

**Issue by RussellHaley** [dotnet/corefx#25811]
I have been getting build errors for a couple of days. I  just updated to ec6014e and it's the same error so I don't suspect the code. The following is an example:

C:\Users\russh\Git\dotnet\corefx\src\shims\ApiCompat.proj(76,5): error : TypesMustExist : Type 'System.ComponentModel.Composition.AttributedModelServices' does not exi
st in the implementation but it does exist in the contract.

The complete output is here: https://pastebin.com/4pjSMYnp

The errors seem to start after the following warning:

EXEC : ApiCompat warning : 0 : Found 'System.ComponentModel.Composition' with PublicKeyToken 'b77a5c561934e089' instead of 'b03f5f7f11d50a3a'. [C:\Users\russh\Git\dotn
et\corefx\src\shims\ApiCompat.proj]

Can anyone tell me what I've done wrong?

**Comment by danmosemsft** [comment]
@RussellHaley try `clean -all` (one hyphen) at the root then build again.

Sometimes a pull will pull down new tools to build with, and the incremental build is not robust to that and will give strange errors. Whenever you get strange errors unrelated to your changes, try a clean.

**Comment by RussellHaley** [comment]
Great, thanks for the guidance! I'll RTM again... sorry for the noise.

https://github.com/dotnet/buildtools/blob/master/Documentation/Dev-workflow.md
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md

**Comment by danmosemsft** [comment]
@RussellHaley no problem at all ping again if you get stuck.

**Comment by RussellHaley** [comment]
While ultimately successful, the build paused at cmake:

C:\Users\russh\Git\dotnet\corefx>build.cmd
Installing dotnet cli...
Restoring BuildTools version 2.1.0-prerelease-02304-01...
Initializing BuildTools...
Done initializing tools.
Running: C:\Users\russh\Git\dotnet\corefx\src\Native\build-native.cmd   x64  Debug  Windows_NT  --numproc 4  -portable  toolSetDir=c:\tools\clr
Tools are already initialized.
Running: C:\Users\russh\Git\dotnet\corefx\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false /l:BinClashLogger,Tools\net46\Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log /p:ConfigurationGroup=Debug /p:BuildPackages=false /p:GenerateNativeVersionInfo=true  /flp:v=normal  /flp2:warningsonly;logfile=msbuild.wrn  /flp3:errorsonly;logfile=msbuild.err  C:\Users\russh\Git\dotnet\corefx\src\Native\..\../build.proj /t:GenerateVersionHeader

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.62
Command execution succeeded.
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.4.2
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86_x64'
Commencing build of native components

-- The C compiler identification is MSVC 19.11.25547.0
-- The CXX compiler identification is MSVC 19.11.25547.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Failed
-- Performing Test COMPILER_HAS_DEPRECATED
-- Performing Test COMPILER_HAS_DEPRECATED - Success
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/russh/Git/dotnet/corefx/bin/obj/Windows_NT.x64.Debug/native
Tools are already initialized.
Running: C:\Users\russh\Git\dotnet\corefx\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false /l:BinClashLogger,Tools\net46\Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log /p:ConfigurationGroup=Debug /p:BuildPackages=false  /flp:v=normal  /flp2:warningsonly;logfile=msbuild.wrn  /flp3:errorsonly;logfile=msbuild.err  C:/Users/russh/Git/dotnet/corefx/src/Native/../../bin/obj/Windows_NT.x64.Debug/native\install.vcxproj /t:rebuild /p:Configuration=Debug /p:Platform=x64 /p:PlatformToolset=v141
  Checking Build System
  CMake does not need to re-run because C:/Users/russh/Git/dotnet/corefx/bin/obj/Windows_NT.x64.Debug/native/CMakeFiles
  /generate.stamp is up-to-date.
  CMake does not need to re-run because C:/Users/russh/Git/dotnet/corefx/bin/obj/Windows_NT.x64.Debug/native/clrcompres
  sion/CMakeFiles/generate.stamp is up-to-date.
  Building Custom Rule C:/Users/russh/Git/dotnet/corefx/src/Native/Windows/clrcompression/CMakeLists.txt

It stopped there with no CPU, disk or network usage (as per resource monitor). I left it for over 15 minutes in that state. When I pressed Esc, the build process restarted and finished. 

I'd rather not re build right now (as I have working software) so I can't repeat/verify the above until later. 

Thanks again
Russ
