### ISSUE TITLE
Build warnings from outer-loop only test projects

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#2582]
We have a bunch of these on every build:
```
EXEC : warning : System.Xml.RW.FactoryReader.Tests has no tests to run
```

My understanding is that these libraries contain only outer loop tests by design. in that case, we should adjust things to not warn in that case. I also wonder if we really need so many different XML test assemblies...

**Comment by krwq** [comment]
That is because some XML projects have only outer loop tests and this is how we handle that.

**Comment by stephentoub** [comment]
As of https://github.com/dotnet/buildtools/pull/245 we no longer issue build warnings for these cases.
