### ISSUE TITLE
Creation of X509Certificate2 fails on Linux but works on Windows

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#25828]
@secana commented on [Sun Dec 10 2017](https://github.com/dotnet/core/issues/1145)

# Creation of X509Certificate2 fails on Linux but works on Windows

Creating a X509Certificate2 instance from a byte array works on Windows but fails on Linux with a "CryptographicException".

# General

Tested Systems:
Windows 10
Ubuntu 16.04, Ubuntu 17.10
OpenSuse 42

All tested with:
**Dotnet Core Version: 2.0.2**

Example code:
```
static void Main(string[] args)
{
      var cert = new X509Certificate2(Cert.CertBytes);
}
```
On Windows: Valid X509Certificate2 instance is created
On Linux: An exception is thrown:
```
{System.Security.Cryptography.CryptographicException: Cannot find the original signer.
   at Internal.Cryptography.Pal.PkcsFormatReader.TryReadPkcs7(SafePkcs7Handle pkcs7, Boolean single, ICertificatePal& certPal, List`1& certPals)
   at Internal.Cryptography.Pal.PkcsFormatReader.TryReadPkcs7Der(Byte[] rawData, Boolean single, ICertificatePal& certPal, List`1& certPals)
   at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] data)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData)
   at CertTest.Program.Main(String[] args) in /home/CertTest/Program.cs:line 14}
```

If the certificate is first parsed by BouncyCastle and then converted into a X509Certificate2 it works.
Example which works on Linux
```
static void Main(string[] args)
{
       var bouncy = new Org.BouncyCastle.X509.X509CertificateParser();
       var bcert = bouncy.ReadCertificate(Cert.CertBytes);
       var wcert = new System.Security.Cryptography.X509Certificates.X509Certificate2(bcert.GetEncoded());
}
```

**Comment by bartonjs** [comment]
@secana Can you share an example file/byte-array which exhibits this behavior?

**Comment by secana** [comment]
@bartonjs of course. You find a valid X509 certificate which can be parsed on Windows but not Linux here: https://gist.github.com/secana/9c13f8fa495681f8a30adb5d8754450e

**Comment by bartonjs** [comment]
Well, there seems to be a pretty good reason why it failed:

https://github.com/dotnet/corefx/blob/317dfb7f69ebf8274e9ad0106a738525e8d8a0b0/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/PkcsFormatReader.cs#L194-L204

When using the single certificate constructor we can't read a Pkcs7 file; because our test corpus wasn't big enough to include one.  And apparently it took just over two years for anyone to notice :smile:.

Given that we now have a report of it, I'm going to move #2910 to a more active state, but this is a (very useful) duplicate of that issue.

**Comment by bartonjs** [comment]
```C#
X509Certificate2Collection coll = new X509Certificate2Collection();
coll.Import(Cert.CertBytes);
```

will populate `coll` with all of the certs contained in the CMS certificates collection.  The order they come out from that file format is usually smallest first; so you'd need to do a bit of work to line that up with what the single certificate ctor does for you.

**Comment by secana** [comment]
@bartonjs Thx for the tip. I got it working with the collection approach. Just had to parse the ASN.1 structure to find the serial number of the signing certificate to select the correct one in the collection. Where the serial number can be found is documented in the "Authenticode Standard" by Mircosoft.
