### ISSUE TITLE
Checksum is calculated before signing in System.Reflection.Metadata.PEBuilder

### ISSUE THREAD

**Issue by agocke** [dotnet/corefx#25829]
Look here at the code to verify the checksum:

https://github.com/dotnet/corefx/blob/45b724f6b6391910edea8a70f3f22a4a7996696d/src/System.Reflection.Metadata/tests/PortableExecutable/PEBuilderTests.cs#L665-L685

Note that there are no binary modifications before calculating the checksum, so the checksum should include everything in the binary except for the checksum blob itself.

But now look at the signing code: https://github.com/dotnet/corefx/blob/45b724f6b6391910edea8a70f3f22a4a7996696d/src/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEBuilder.cs#L496-L505

The checksum is calculated before writing the strong name signature, so it's calculated with the zero value. This doesn't look correct to me, and my tests with the CLR signing code seem to indicate that the checksum should include the strong name signature.

**Comment by morganbr** [comment]
I think this is the right behavior, but you might want to confirm against the desktop runtime. Strong Name signatures typically don't allow anything to change in the binary after they're completed.

**Comment by tmat** [comment]
Just verified that ```sn``` calculates the checksum after it writes the signature.
