### ISSUE TITLE
ResourceManager only Supports retrieving StringResources whats the plan for other resource types

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/corefx#2584]
As far as I can tell ResourceManager only has GetString("name") and GetString""name", cultureinfo)
Are there plans to implement GetObject blah ....

Thanks

Kevin

**Comment by KevinRansom** [comment]
Entered in error

**Comment by manu-silicon** [comment]
Why was this entered in error? As of today, I do not see GetObject in ResourceManager and this is problematic for me.

**Comment by lextm** [comment]
See #11532 for an update.
