### ISSUE TITLE
Add StringBuilder.Equals(string) to efficiently compare a StringBuilder with a string.

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#25846]
## Issue 
There is no efficient way to compare the content of a large StringBuilder with a string. If you iterate with the string builder indexer, you hit [pathological performance](https://github.com/dotnet/corefx/issues/25804) on chunky StringBuilders (the typical case). If instead you create a temporary string from the builder, you have a large string that has to be garbage collected.

## Rationale
MSBuild has to compare StringBuilder with String in two hot paths ([one ](https://github.com/Microsoft/msbuild/blob/d075c6f7c09bb2d766b45ac740d867ecf08ff6bb/src/Shared/ReuseableStringBuilder.cs#L86) and [two](https://github.com/Microsoft/msbuild/blob/3986423a4cd2e7a716ab0c0d6ef28485f1844977/src/Shared/OpportunisticIntern.cs#L309)). Right now it does it with indexes. If the string is large, which it can be if it was created by reading a file into an item list, [a customer observed this](https://github.com/Microsoft/msbuild/issues/1593) to be pathologically slow. They can take a change to fall back to making a temporary string for long builders, but that's an extra branch and they have to pick a cut over point. However it would be easy for a StringBuilder to efficiently compare itself with a string, because it just walks its chunks.

## Proposal
```c#
    public sealed partial class StringBuilder : ...
    {
        public bool Equals(System.Text.StringBuilder sb) { throw null; } // already exists
        public bool Equals(System.String value) { throw null; } // proposed
    }
```
The implementation would produce a result equivalent to 
```c#
    return String.Equals(this.ToString(), s, StringComparison.Ordinal);
```
but be implemented by walking the chunks and the string together. There are various ways this could be optimzed, but the goal here is to just not be awful.

**Comment by jnm2** [comment]
Happy to see this. I could have used it a number of times.

**Comment by terrajobst** [comment]
It's a bit odd that the existing `Equals(StringBuilder)` does an ordinal comparison -- that's inconsistent with how string comparisons work (defaults to current culture). Hence, it seems acceptable to have an `Equals(string)` that is ordinal only too. Adding `Equals(string, StringComparison)` would be doable too, but the only efficient one would be ordinal (all others likely have to enumerate char by char or even allocate), which might make the API a performance trap.

Conclusion: approved as proposed.

**Comment by mikedn** [comment]
> It's a bit odd that the existing Equals(StringBuilder) does an ordinal comparison -- that's inconsistent with how string comparisons work (defaults to current culture).

`String.Compare` defaults to the current culture but `String.Equals` does not, it uses ordinal by default.

**Comment by danmosemsft** [comment]
OK, well we will be consistent with String's inconsistency :)

**Comment by mikedn** [comment]
Kind of late to the part but shouldn't it be `bool Equals(ReadOnlySpan<char>)`? :grin:

**Comment by danmosemsft** [comment]
Post script from API review thanks to @mikedn : yes, we want:
```c#
    public sealed partial class StringBuilder : ...
    {
        public bool Equals(System.String s) { throw null; } // ordinal
        public bool Equals(System.ReadOnlySpan<char> s) { throw null; } // ordinal
    }
```
But, if @KrzysztofCwalina can confirm that the cast from string to ReadOnlySpan<char> has negligible ovehead, the string overload can be omitted.

**Comment by karelz** [comment]
cc @stephentoub as he might have an opinion

**Comment by stephentoub** [comment]
My $.02: Compared to the other overheads here, the cast should be negligible and we should not add the string overload until someone proves otherwise and that it's actually valuable.

**Comment by karelz** [comment]
FYI: The API review discussion was recorded - see https://youtu.be/dOpH6bUNbcw?t=62 (15 min duration) + few ad-hoc mini discussions later on:
* https://youtu.be/dOpH6bUNbcw?t=1420 (2 min)
* https://youtu.be/dOpH6bUNbcw?t=2049 (3 min)
* https://youtu.be/dOpH6bUNbcw?t=2746 (3 min)

**Comment by danmosemsft** [comment]
OK so for explicitness, we only need 
```c#
    public sealed partial class StringBuilder : ...
    {
        public bool Equals(System.ReadOnlySpan<char> s) { throw null; } // ordinal
    }
```

**Comment by KrzysztofCwalina** [comment]
Yes, the cast from String to Span<char> has negligible cost in comparison to the cost of Equals for all but the sortest strings.

**Comment by karelz** [comment]
Offline discussion: We are ok renaming `s` arg name to `value`. Top post updated.
