### ISSUE TITLE
DIA SDK missing error message is wrong/misleading

### ISSUE THREAD

**Issue by OzieGamma** [dotnet/corefx#25856]
When trying to build CoreFX I ran `.\build.cmd`. I got the following error message:

```
if exist "%VSINSTALLDIR%DIA SDK" goto GenVSSolution
echo Error: DIA SDK is missing at "%VSINSTALLDIR%DIA SDK". ^
This is due to a bug in the Visual Studio installer. It does not install DIA SDK at "%VSINSTALLDIR%" but rather ^
at VS install location of previous version. Workaround is to copy DIA SDK folder from VS install location ^
of previous version to "%VSINSTALLDIR%" and then resume build.
:: DIA SDK not included in Express editions
echo Visual Studio Express does not include the DIA SDK. ^
You need Visual Studio 2015 or 2017 (Community is free).
echo See: https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/developer-guide.md#prerequisites
exit /b 1
```

The DIA SDK is now correctly installed by the installer. However I forgot to select the correct components when installing VS Community 2017.

I am creating a PR to change the error message.

**Comment by karelz** [comment]
If you can detect all needed components of VS, that would be great. Don't forget to test it also with VS 2015 which we still support.

**Comment by OzieGamma** [comment]
I'll have a look at those that I can detect. Does VS 2015 do component based install?

**Comment by karelz** [comment]
It's been a while I played with VS 2015 pre-req. Here's what is necessary: https://github.com/dotnet/corefx/wiki/Development-environment-setup-for-Windows#visual-studio-2015
