### ISSUE TITLE
How do I utilize HTTP caching with WinHttpHandler and HttpClient?

### ISSUE THREAD

**Issue by LeonidVasilyev** [dotnet/corefx#25854]
I'm using .NET Framework 4.7, but creating issue here because [System.Net.Http.WinHttpHandler](https://www.nuget.org/packages/System.Net.Http.WinHttpHandler/) NuGet package release notes lead to .NET Core repository, and another [issue](https://github.com/dotnet/core/issues/1023) about `WinHttpHandler` was moved from .NET Core repository to CoreFx repository.

It is stated in many places accross .NET Framework documentation that WinINET is not suppose to be used in server enviroment, for example [Caching](https://msdn.microsoft.com/en-us/library/windows/desktop/aa383928(v=vs.85).aspx) page on MSDN:
> **Note**  WinINet does not support server implementations. In addition, it should not be used from a service. For server implementations or services use [Microsoft Windows HTTP Services (WinHTTP)](https://msdn.microsoft.com/en-us/library/windows/desktop/aa384273(v=vs.85).aspx). 

Moreover, WinINET caching is not always working in IIS. See [HttpClient enable cache on server](https://stackoverflow.com/questions/47715084/httpclient-enable-cache-on-server), [HttpClient not using cache on staging server](https://stackoverflow.com/questions/22375795/httpclient-not-using-cache-on-staging-server), [HttpWebRequest's cache is not working for ASP.NET Application on Windows Server 2012 R2](https://social.technet.microsoft.com/Forums/windows/en-US/1725a82d-7e21-41a3-9c7d-19a6b5819369/httpwebrequests-cache-is-not-working-for-aspnet-application-on-windows-server-2012-r2?forum=winservercore) questions and [IIS Hosted Web API Not Caching Internal HTTP Responses](http://chrisoldwood.blogspot.ru/2015/01/iis-hosted-web-api-not-caching-internal.html) article.

So if I need to communicate with other HTTP servers in my server application (Web API or windows service) I need to use WinHTTP. I couldn't find any way to switch from WinINET to WinHTTP except using [`WinHttpHandler`](https://msdn.microsoft.com/en-us/library/system.net.http.winhttphandler(v=vs.105).aspx) class from [System.Net.Http.WinHttpHandler](https://www.nuget.org/packages/System.Net.Http.WinHttpHandler/) NuGet package:
```csharp
var client = new HttpClient(new WinHttpHandler())
{
    BaseAddress = new Uri("http://myresourceserver.com/")
};

var response = await client.GetAsync("resource");
var result = await response.Content.ReadAsStringAsync();
```
Now with this handler `HttpClient` is not using cache by default. I use following command to configure WinHTTP to use Fiddler proxy: `netsh winhttp set proxy 127.0.0.1:8888 "<-loopback>"` and confirm that cache is not used.  With `WinHttpHandler` I can't explicitly specify `CachePolicy` like I can with `WebRequestHandler`. It also seems like `WinHttpHandler` ignores `<requestCaching>` configuration file section and `HttpWebRequest.DefaultCachePolicy` static property. 

I found no information about caching in WinHTTP in official [documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/aa384273(v=vs.85).aspx).

**Comment by davidsh** [comment]
>I found no information about caching in WinHTTP in official documentation.

There is no caching support in native WinHTTP nor WinHttpHandler.  Thus, the HttpClient, HttpWebRequest APIs etc. in .NET Core do not support caching.

**Comment by davidsh** [comment]
> I couldn't find any way to switch from WinINET to WinHTTP except using WinHttpHandler class from System.Net.Http.WinHttpHandler NuGet package:

Also, WinINET is not supported on .NET Core.  The exception is that WinINET is the underlying implementation of the .NET Core Windows UWP HTTP stack.  But it used indirectly via System.Net.Http APIs on .NET Core UWP being implemented on top of WinRT Windows.Web.Http APIs (which use WinINET underneath).

In general, though, native Windows WinINET is a poor choice is not supported for server applications such as background services, etc.  It is used extensively in UI based applications such as UWP and supports other native Windows applications such as Internet Explorer and Edge browsers.

**Comment by davidsh** [comment]
cc: @karelz

**Comment by karelz** [comment]
Seems to be answered. Let us know if you have further questions.
