### ISSUE TITLE
SignatureDecoder isValueType not set correctly for some projected types and should be optional

### ISSUE THREAD

**Issue by SantiFdezM** [dotnet/corefx#2586]
Follow-up to PR #2551 

a. isValueType is not set correctly when a type is projected from value type to class or vice versa.
b. There should be an opt-in option to pas non-null isValueType. By default, it should always be null and when option is on, it should compute isValueType (including possible projection case)

cc @nguerrera

**Comment by nguerrera** [comment]
This is fixed already in dev/metadata and in the PR #4809 in progress to main.
