### ISSUE TITLE
Investigate improving GetFiles array perf.

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#25863]
The APIs that return arrays currently use an enumerable internally. We could potentially write optimized solutions for these that take into account the result will be a flat array (i.e. forgo some of the enumerable overhead).

``` C#
namespace System.IO
{
    public static class Directory
    {
        public static string[] GetDirectories(string path, string searchPattern, SearchOption searchOption);
        public static string[] GetFiles(string path, string searchPattern, SearchOption searchOption);
        public static string[] GetFileSystemEntries(string path, string searchPattern, SearchOption searchOption);
    }

    public sealed class DirectoryInfo : FileSystemInfo
    {
        public DirectoryInfo[] GetDirectories(string searchPattern, SearchOption searchOption);
        public FileInfo[] GetFiles(string searchPattern, SearchOption searchOption);
        public FileSystemInfo[] GetFileSystemInfos(string searchPattern, SearchOption searchOption); 
    }
}
```

Mono had some optimizations along these lines. https://github.com/dotnet/designs/pull/24#issuecomment-351102126

**Comment by benaadams** [comment]
Shame Windows has no async file**system** apis; as querying directories, files etc is blocking on remote, slow or asleep drives https://windowsserver.uservoice.com/forums/295056-storage/suggestions/32606341-async-callback-apis-for-drive-directory-file-query

**Comment by SunnyWar** [comment]
> Shame Windows has no async filesystem apis
@benaadams I seem to recall the Directory.EnumerateFile and EnumerateDirectories were supposed to be asynchronous, but a I could not verify this by a quick look at the code. Also, a mention was made for add FS async methods in #24931.

**Comment by benaadams** [comment]
None of the `FindFirstFile`,`FindFirstFileEx`,`FindFirstFileTransacted`,`FindNextFile`,`GetFileInformationByHandle` OS level apis have completion port, async or callback versions

**Comment by JeremyKuhne** [comment]
@benaadams I'm more than happy to help shepherd some async wrapper APIs, would you like to make a proposal? If not I'll open a tracking issue.

**Comment by benaadams** [comment]
Yeah; I have a HDD that falls asleep and most .NET apps hang looking at directories (e.g. save/open dialog) waiting for it to wakeup...

Wonder if its a good fit for an early async enumerable type scenario? https://github.com/dotnet/csharplang/blob/master/proposals/async-streams.md

Please open a tracking issue as I think they should probably be coordinated.

**Comment by benaadams** [comment]
Though suppose this might be more lightweight?
```csharp
namespace System.IO
{
    public static class Directory
    {
        public static Task<string[]> GetDirectoriesAsync(string path, string searchPattern, SearchOption searchOption);
        public static Task<string[]> GetFilesAsync(string path, string searchPattern, SearchOption searchOption);
        public static Task<string[]> GetFileSystemEntriesAsync(string path, string searchPattern, SearchOption searchOption);
    }

    public sealed class DirectoryInfo : FileSystemInfo
    {
        public Task<DirectoryInfo[]> GetDirectoriesAsync(string searchPattern, SearchOption searchOption);
        public Task<FileInfo[]> GetFilesAsync(string searchPattern, SearchOption searchOption);
        public Task<FileSystemInfo[]> GetFileSystemInfosAsync(string searchPattern, SearchOption searchOption); 
    }
}
```

**Comment by JeremyKuhne** [comment]
Closing this one as we're about as optimized as you can generically get for the array methods now. There is no way to know exactly how many items you'll have in your results. One could do a low allocation file count and use that data as a _hint_ for a second pass. Hitting the disk is expensive, however, and this would not be something we could do without significant perf impacts. The new extensible APIs allow building this sort of solution (or other hinted solutions) if the various tradeoffs were useful.
