### ISSUE TITLE
Remove obsolete attribute from XslTransform

### ISSUE THREAD

**Issue by pjanotti** [dotnet/corefx#25874]
Some customers hesitate in using `XslTransform` even when recommended because of the presence of this attribute.

Depending on the scenario it could be better to use `XslTransform` instead of `XslCompiledTransform`, however, `XslTransform` was marked as obsolete back in .NET 2.0 which creates the impression that eventually it is going to be pulled out, however this is not really happening.  In UWP is even stranger since `XslCompiledTransform` is not available at all and only the *deprecated* one is available.

**Comment by danmosemsft** [comment]
@krwq

**Comment by pjanotti** [comment]
/cc @weshaggard @terrajobst @AlexGhiondea @joperezr 

The type is marked with the obsolete attribute on .NET Standard, is it a breaking change to remove it? If so can we remove it in a future version of the Standard?

Ideally we would remove it from the Standard then from CoreFX and desktop.

**Comment by terrajobst** [comment]
And this is why we can't have nice things :-)

**Comment by pjanotti** [comment]
We should consider marking the `ObsoleteAttribute` with itself... :P

**Comment by weshaggard** [comment]
>The type is marked with the obsolete attribute on .NET Standard, is it a breaking change to remove it?

No it isn't a breaking change.

>If so can we remove it in a future version of the Standard?

Yes we can consider removing it.

**Comment by pjanotti** [comment]
@mairaw we should also update the docs to reflect this "un-obsolence" of `XslTransform`.

**Comment by JonHanna** [comment]
Preferably the docs would give some insight into the "Depending on the scenario it could be better to use" comment above. Having two classes that seem to do the same thing and no insight into which to use is a displeasing dilemma.

**Comment by pjanotti** [comment]
Good point, I will work with docs folks but basically it is similar to interpreter vs compiler discussion, plus:

1. XslCompiledTransform does not work in UWP (or any situation that JIT is not available)
2. XslCompiledTransform causes load of modules via code generation (depending on how many times this happens it can be a problem).
