### ISSUE TITLE
Chinese random code on  dotnet core ,but on Framework is  normal

### ISSUE THREAD

**Issue by luckyhappy** [dotnet/corefx#25886]
byte[] contentByte = { 214, 208 };
 Console.WriteLine(Encoding.Default.GetString(contentByte));
operating system:windows 10 ，Chinese Version

![qq 20171213185822](https://user-images.githubusercontent.com/2962847/33935680-c8a0fdd8-e037-11e7-8d89-5f12588dc0f4.png)

![qq 20171213185848](https://user-images.githubusercontent.com/2962847/33935681-c8f1ac24-e037-11e7-896b-f1444ae8dfb9.png)

**Comment by JonHanna** [comment]
The default encoding in .NET Core is UTF-8, so the bytes for `"中"` would be `{ 228, 184, 173 }`.

To use a legacy encoding, use it explicitly, `Console.WriteLine(Encoding.GetEncoding("GB2312").GetString(new byte[]{ 214, 208 }));`
It can be worth storing an encoding you'll use often in a static field.
