### ISSUE TITLE
Make Span IndexOfAny a generic method with special case for byte

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#25895]
Similar to LastIndexOfAny (added here - https://github.com/dotnet/corefx/pull/25848), change the IndexOfAny APIs to be generic. The premise is that there should be little performance degradation for the byte case when we make this change. This needs to be confirmed by comparing performance results before/after.

**Change:**
```C#
public static int IndexOfAny(this Span<byte> span, byte value0, byte value1) { throw null; }
public static int IndexOfAny(this Span<byte> span, byte value0, byte value1, byte value2) { throw null; }
public static int IndexOfAny(this Span<byte> span, ReadOnlySpan<byte> values) { throw null; }

public static int IndexOfAny(this ReadOnlySpan<byte> span, byte value0, byte value1) { throw null; }
public static int IndexOfAny(this ReadOnlySpan<byte> span, byte value0, byte value1, byte value2) { throw null; }
public static int IndexOfAny(this ReadOnlySpan<byte> span, ReadOnlySpan<byte> values) { throw null; }
```

To:
```C#
public static int IndexOfAny<T>(this Span<T> span, T value0, T value1) where T : IEquatable<T> { throw null; }
public static int IndexOfAny<T>(this Span<T> span, T value0, T value1, T value2) where T : IEquatable<T> { throw null; }
public static int IndexOfAny<T>(this Span<T> span, ReadOnlySpan<T> values) where T : IEquatable<T> { throw null; }

public static int IndexOfAny<T>(this ReadOnlySpan<T> span, T value0, T value1) where T : IEquatable<T> { throw null; }
public static int IndexOfAny<T>(this ReadOnlySpan<T> span, T value0, T value1, T value2) where T : IEquatable<T> { throw null; }
public static int IndexOfAny<T>(this ReadOnlySpan<T> span, ReadOnlySpan<T> values) where T : IEquatable<T> { throw null; }
```

Example implementation change:
```C#
public static int IndexOfAny<T>(this Span<T> span, T value0, T value1)
    where T : IEquatable<T>
{
    if (typeof(T) == typeof(byte))
        return SpanHelpers.IndexOfAny(
            ref Unsafe.As<T, byte>(ref span.DangerousGetPinnableReference()),
            Unsafe.As<T, byte>(ref value0),
            Unsafe.As<T, byte>(ref value1),
            span.Length);
    return SpanHelpers.IndexOfAny(ref span.DangerousGetPinnableReference(), value0, value1, span.Length);
}
```

Then implement the following to SpanHelpers.T.cs
```C#
public static unsafe int IndexOfAny<T>(ref T searchSpace, T value0, T value1, int length)
            where T : IEquatable<T>
```

Should be relatively easy. cc @karelz 

cc @KrzysztofCwalina, @GrabYourPitchforks

**Comment by KennethLundberg** [comment]
@ahsonkhan I've been looking for a nice issue to get my feet wet with. May I take up this issue? Considering you made a similar change a few days ago, I have a pretty good model to go off of in terms of how things should be done. [In a coreclr issue](https://github.com/dotnet/coreclr/issues/6136) it was mentioned that they use "PerfView to profile, Benchmark.NET to prove the win (post results here)". Is that the same process I should perform here?

**Comment by ahsonkhan** [comment]
> I've been looking for a nice issue to get my feet wet with. May I take up this issue? 

Awesome. Absolutely.

> [In a coreclr issue](https://github.com/dotnet/coreclr/issues/6136) it was mentioned that they use "PerfView to profile, Benchmark.NET to prove the win (post results here)". Is that the same process I should perform here?

That would be fine. As an alternative, you could also try to create and run xunit.performance tests. See this for details - https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/performance-tests.md#performance-tests

Here are some example performance tests using xunit.performance - https://github.com/dotnet/corefx/tree/master/src/System.Memory/tests/Performance

**Comment by KennethLundberg** [comment]
@karelz, could I please get that invite requested above? Thanks!

**Comment by karelz** [comment]
@KennethLundberg sorry for the delay, I missed the original message.
Done. Pro-tip: GitHub will auto-subscribe you to all notifications on the repo (500+ per day), which is quite a lot. We recommend to disable the notifications to "just your mentions".

**Comment by KennethLundberg** [comment]
@ahsonkhan I'm not sure what the etiquette is for this. but I was finally assigned this task. however I stopped working on it a few days ago as I saw AlexG's commit referenced earlier. I'm not sure how things are resolved for these matters, so should I commit my similar changes, or let Alex proceed and give the task to him?

**Comment by AtsushiKan** [comment]
cc @joshfree 

Hi @AlexG2017 - were you planning to turn your commit into a PR for this in the next few days? 

This issue got reassigned to me because it's internal priority got bumped up and we'd like to close in the next week or so. If you can't get to it in the next few days, that's no problem - I can grab it or reassign it back to Kenneth - I just need to know your plans. Thanks!

**Comment by ahsonkhan** [comment]
There is already a PR out for this (in review):
https://github.com/dotnet/corefx/pull/26100

**Comment by AtsushiKan** [comment]
Ah, ok. Looks like it's approved and CI is green too so I expect it'll be merged shortly.
