### ISSUE TITLE
ReflectionTypeLoadException's ToString() should include inner exceptions

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#25906]
As thrown by the runtime, ReflectionTypeLoadException always has its default message, which is:
`Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.`

The information is only in LoaderExceptions and that can contain many possible messages along the lines of type X could not be loaded due to reason Y.

AggregateException is analogous and includes these inner exceptions in its ToString(). Unfortunately RuntimeTypeLoadException does not. This means in console output that records the crash, the information is gone and irretrievable. So I am faced with a test log that just says 

```
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at repro.Program.Main() in C:\Users\danmose\source\repos\ConsoleApp32\Program.cs:line 32
```

If it did the same as AggregateException it would look like

```
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.  
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at repro.Program.Main() in C:\Users\danmose\source\repos\ConsoleApp32\Program.cs:line 32

Could not load type 'repro.StructA' from assembly 'ConsoleApp32, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'repro.StructB' from assembly 'ConsoleApp32, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
```

Which makes it easier to figure out what happened. 

Note the inner exceptions often do not have callstacks - just messages - if they don't have stacks, the output should not show any.
Note also I removed the text `Retrieve the LoaderExceptions property for more information.` which becomes essentially redundant.

**Comment by danmosemsft** [comment]
https://github.com/dotnet/coreclr/issues/10520 made me think of this. These types of load related errors are often configuration specific and therefore not easily reproduceable after the fact so it's particularly important that the exception provide all the information possible.

**Comment by wtgodbe** [comment]
@danmosemsft where does the code for ReflectionTypeLoadException live? A search in the repo only comes up with tests.

**Comment by karelz** [comment]
It's in CoreCLR repo: https://github.com/dotnet/coreclr/blob/da66c3a146563d5841502a8dec76fe082ee9fef6/src/mscorlib/shared/System/Reflection/ReflectionTypeLoadException.cs

**Comment by wtgodbe** [comment]
@danmosemsft it looks like ReflectionTypeLoadException has no ToString() method. Instead the String is created here - https://github.com/dotnet/coreclr/blob/master/src/vm/invokeutil.cpp#L771, in this cpp utility file. It is defined here https://github.com/dotnet/coreclr/blob/122acaaad78cefbed71bdb137505f70552e13265/src/mscorlib/Resources/Strings.resx#L3286. The AggregateException is also defined in that file, and InnerException is defined here -https://github.com/dotnet/coreclr/blob/122acaaad78cefbed71bdb137505f70552e13265/src/mscorlib/Resources/Strings.resx#L162 and referenced in AggregateException's ToString() method. I'm a little confused as to why ReflectionTypeLoadException has that special-cased Exception Instantiation method, and what the best way to append an Inner Exception there would be. If I add something similar to AggregateException's InnerException string to Strings.resx, it seems to me that the information on Inner Exceptions wouldn't be available by the time we hit https://github.com/dotnet/coreclr/blob/46ab1d132c9ad471d79afa20c188c2f9c85e5f20/src/vm/commodule.cpp#L1110, so it wouldn't be as simple as concatenating the two strings.

**Comment by danmosemsft** [comment]
@wtgodbe if you add a ToString() to RTLE analogous to AE's, by the time it is called, the RTLE objects' LoaderExceptions will be populated right? It can just walk through those. Shouldn't need any work on the native side?

**Comment by wtgodbe** [comment]
That was my thinking, I just wasn't sure if there was a particular reason why the ToString-y behavior was being handled on the native side instead of in RTLE.cs. Would you think any of that native code would become redundant if I added a ToString()?

**Comment by danmosemsft** [comment]
Some exceptions, like RTLE, are essentially thrown from native code. In those cases they are constructed in native rather than thrown from managed code. As far as I know it isn't any more interesting than that. After they are constructed they behave just the same either way.

**Comment by wtgodbe** [comment]
I see. I am still unclear on if https://github.com/dotnet/coreclr/blob/46ab1d132c9ad471d79afa20c188c2f9c85e5f20/src/vm/commodule.cpp#L1110 or any other code in that file becomes redundant after adding a ToString(). Is it sufficient to just add a ToString() to RTLE.cs, not change anything else, and confirm locally that the exception looks how I expect it to?

**Comment by wtgodbe** [comment]
Resolved by https://github.com/dotnet/coreclr/pull/15688
