### ISSUE TITLE
Managed sockets binding regression on linux 

### ISSUE THREAD

**Issue by halter73** [dotnet/corefx#25914]
@tmds @stephentoub 

Starting with runtime build 2.1.0-preview1-25915-01, it is now possible to bind multiple times simultaneously to the exact same TCP address on linux without setting any special options.

### SampleApp:

```c#
using System;
using System.Net;
using System.Net.Sockets;

namespace DoubleBind
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var socket1 = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
            {
                socket1.Bind(new IPEndPoint(IPAddress.Loopback, 5000));

                using (var socket2 = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
                {
                    socket2.Bind(new IPEndPoint(IPAddress.Loopback, 5000));
                }
            }

            Console.WriteLine("Success!?");
        }
    }
}
```

### Expected output:

```
DoubleBind$ dotnet run

Unhandled Exception: System.Net.Sockets.SocketException: Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at DoubleBind.Program.Main(String[] args) in /Users/shalter/source/halter73/DoubleBind/Program.cs:line 17
```

This is what is seen today on Windows and macOS.

### Actual output:

```
DoubleBind$ dotnet run
Success!?
```

This is the behavior on Linux (tested on Ubuntu 16.04.3 LTS) starting with the 2.1.0-preview1-25915-01 build.

### My theory

[Here](https://github.com/dotnet/corefx/compare/25f80ade543903293ae08ac091cffd457a7a9ad4...7eba4bf88983ac276348ea1626c81595e1b237c6) are the changes introduced in the 2.1.0-preview1-25915-01 build. But even without looking at that, it stands to reason that #24809 is the likely cause of this change in behavior.

Setting the SO_REUSEADDR option by itself should not cause this behavior (this is what we've been doing manually in Kestrel for a couple months now), so maybe SO_REUSEPORT is getting set when it shouldn't be.

**Comment by tmds** [comment]
The exception you are looking for has moved to the `Listen` call.

TCP connections are identified by the quadruplet `(srcaddr, srcip, dstaddr, dstip)`. So when the `Bind` call is made, only two of them are really fixed. Theoretically, you could `Bind` two sockets to the same src-pair, and then `Connect `to a different dst-pair. If an OS throws on `Bind` (Windows, macOS), they are assuming everything is fixed at that point.

Considering the platform differences, I think the current implementation as good as it gets.

**Comment by tmds** [comment]
This is the test in corefx that behaves the same on all platforms. Notice the second `Bind` fails, because the first socket has also called `Listen`.
https://github.com/dotnet/corefx/blob/1e955510bf4f95963dc9276539870ddbf7319988/src/System.Net.Sockets/tests/FunctionalTests/SocketOptionNameTest.cs#L340-L358

**Comment by tmds** [comment]
Depending on the order, the exception can also be thrown on the Listen call.
Exception thrown on Bind:
```
Socket 1: Bind
Socket 1: Listen
Socket 2: Bind // throws
```
Exception thrown on Listen:
```
Socket 1: Bind
Socket 2: Bind
Socket 1: Listen
Socket 2: Listen // throws
```

**Comment by karelz** [comment]
@wfurt can you please take a look?

**Comment by halter73** [comment]
@tmds. Thanks for the explanation. This behavior is fine for Kestrel of course. Given that Listen still throws an address in use error, I doubt any other real-world app would be adversely affected either. We just need to update a few tests.

Thanks. I'm fine with closing this BTW.

**Comment by karelz** [comment]
Closing per discussion above
