### ISSUE TITLE
Create new label for hardware intrinsics i.e. area-System.Runtime.Intrinsics

### ISSUE THREAD

**Issue by 4creators** [dotnet/corefx#25933]
There is a growing number of issues and PRs in both coreclr and corefx repos which are result of ongoing work in implementation of Intel and Arm hardware instrinsics. It would be very helpful in managing the information flow if that area would have it's own labels to better organize work and information flow.

cc: @karelz @jkotas @tannergooding @CarolEidt  @fiigii @sdmaclea

**Comment by tannergooding** [comment]
It should probably be `area-System.Runtime.Intrinsics`, to better match the existing area paths.

**Comment by 4creators** [comment]
Much better than mine - changing title

**Comment by karelz** [comment]
In general, I am not keen on creating new labels for areas with less than 10-20 issues in CoreFX. I didn't see more than 3-ish issues in CoreFX so far I think. Did I miss more?

BTW: I can't speak on behalf of CoreCLR repo - I assume the JIT work will be tracked under JIT label anyway. The area-System.\* namespaces are only for BCL pat of CoreCLR repos.

**Comment by danmosemsft** [comment]
IMO labels should be our servant, if they are useful for a period, then we should have one, and delete it later.

**Comment by danmosemsft** [comment]
If it would confuse the area-owner system, it could be a separate label like "Numerics"

**Comment by karelz** [comment]
> IMO labels should be our servant,

Agreed. I just don't think that creating a label for 3-5 issues is doing us any good service. It is creating more clutter IMO and doing us disservice.
As I said, if there's more, I'm on board.

> if they are useful for a period, then we should have one, and delete it later.

I think this is independent and more applicable to other non-area labels. That said, I don't believe we do that in practice. We tend to hang on the some-time-ago-useful labels and it is pretty hard to get rid of them :(

**Comment by tannergooding** [comment]
I also imagine many more will open up as the intrinsic are implemented.

Not to mention that Arm is likely going to be in the same boat (pending api review sometime next year).

**Comment by fiigii** [comment]
> In CoreCLR, I agree that we should have a label that we will use to tag the issues related to the hardware intrinsics. There is a lot of them in CoreCLR.

Agree with  @jkotas, most of the intrinsic work is (and will be) in CoreCLR.

**Comment by karelz** [comment]
The number of issues grew to 10, so I created the label: https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Aarea-System.Runtime.Intrinsics+
