### ISSUE TITLE
Remove dead code related to CookieCollection.IsReadOnly from System.Net.Primitives

### ISSUE THREAD

**Issue by justinvp** [dotnet/corefx#2593]
**Edit:** `IsReadOnly` is dead code that should be removed from CoreCLR.

---
Original issue description (kept here so the comments below make sense):

>The [default constructor](https://github.com/dotnet/corefx/blob/63ff03fce5ab7c7ac6920d99af148a447d04c822/src/System.Net.Primitives/src/System/Net/CookieCollection.cs#L33) sets this to `true`, but `CookieCollection` is always mutable (same as on the desktop framework) -- there's nothing in its implementation that enforces it being read-only.
>
>Is it too late to remove this public property from the System.Net.Primitives contract? (I'm assuming it can't be removed, but figured I'd ask anyway).
>
>If it can't be removed, should the default value be changed to `false` to reflect the actual behavior? However, this would go against the [MSDN documentation](https://msdn.microsoft.com/en-us/library/w6x28886(v=vs.110).aspx) for the desktop framework, which states the default value is `true`.

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar @pgavlin @josguil

**Comment by davidsh** [comment]
Right now, the contracts are locked especially for System.Net.Primitives.  And this class is defined on desktop as well which makes REMOVING existing APi surface very difficult.

**Comment by justinvp** [comment]
Actually... I may be missing something, but the System.Net.Primitives contract does not have the `IsReadOnly` property. Should it even exist in the source here?

https://github.com/dotnet/corefx-progress/blob/master/src-full/System.Net.Primitives.cs#L34-L44

Also, I see other differences like `IsSynchronized` and `SyncRoot` are implemented explicitly (private) in the contract, but are implicit (public) in the source on GitHub.

**Comment by davidsh** [comment]
@justinvp You are correct that the `IsReadOnly` property is not in the CoreFx System.Net.Primitives contract. It is a property in the .NET Framework including 4.6. (Desktop). But it was not included in the original .NET Store Profile for Win 8/8.1 which formed the basis of contracts for CoreFx.

https://msdn.microsoft.com/en-us/library/system.net.cookiecollection(v=vs.110).aspx

You'll note on the documentation page referenced, that property does not have the green Portable Class Library icon next to it.

A lot of our CoreFx source code was originally ported from .NET Framework (Desktop).  So, it's possible that we still have some dead code right now.  We'll be cleaning that up as we go and is part of our refactor efforts right now.

**Comment by SidharthNabar** [comment]
You guys are right - the CookieCollection type in desktop has the IsReadOnly property, but in CoreFx, that property is not present. Given that, @justinvp - should we re-title this issue to say "Remove dead code related to CookieCollection.IsReadOnly from System.Net.Primitives"?

**Comment by weshaggard** [comment]
I suspect this is one of those holder overs from the early days where we added IsReadOnly to all the collection types and perhaps we removed the IList implementation, which exposed IReadOnly, before it ever shipped. I agree this looks to be dead code that can be cleaned up.
