### ISSUE TITLE
RuntimeFeature.IsSupported("EmitIL") would be a useful feature check.

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#25944]
Whether one can emit IL or not is a significant difference between platforms, that impacts on the best approach to some problems, so it would be useful if `RuntimeFeature` could be queried about it.

This should close #10470 as well, which wishes to be able to enquire as to whether `LamdbaExpression.Compile()` can emit IL, which in turn depends on that feature.

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/issues/25530

**Comment by karelz** [comment]
Duplicate of #25530
