### ISSUE TITLE
Where do I get nightly master builds (dotnet-core myget feed is for dev/defaultintf)

### ISSUE THREAD

**Issue by lmolkova** [dotnet/corefx#25947]
I'm trying to consume DiagnosticSource nightly build to integrate recent bugfix with partners.

The latest available in dotnet-core myget is  [4.5.0-dev-di-26015-02](https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Diagnostics.DiagnosticSource/4.5.0-dev-di-26015-02)

That points to the ce3b6524a275b2ac814d76e5e49e96aa9be7f877 and is a head of dev/defaultintf branch.

Is it expected?
If so, where are master nightly builds?

**Comment by MichalStrehovsky** [comment]
This one is the latest: https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Diagnostics.DiagnosticSource/4.5.0-preview1-26015-06

Both the master branch and the defaultInterfaces branch are producing these packages. The defaultinterfaces build happened to be published 6 minutes after master, making it the latest.

**Comment by lmolkova** [comment]
@MichalStrehovsky 

Thanks! I've got confused with 4.5.0-preview2  builds from September
