### ISSUE TITLE
long.TryParse return false for negative numbers in ubuntu

### ISSUE THREAD

**Issue by hmdhasani** [dotnet/corefx#25967]
I have an asp core 1.1.5 app and I'm running it in Ubuntu with docker
In Windows (Dev environment) It's OK but in Ubuntu I found that long.TryParse return false for negative inputs. I think its a bug
currently I use this code to solve the problem:

```c#
public static bool TryParseLong(string input, out long output)
 {
   var isNegetive = false;
   if (input[0] == '-')
   {
                input = input.Substring(1);
                isNegetive = true;
            }

            if (long.TryParse(input, out long longValue))
            {
                if (isNegetive)
                {
                    output = -longValue;
                }
                else
                {
                    output = longValue;
                }

                return true;
            }

            output = 0;
            return false;
        }
```

[EDIT] Add C# syntax highlighting by @karelz

**Comment by hmdhasani** [comment]
I think It's because of  hyphen-minus (-) and dash(—).
in linux long.toString and long.Parse use dash but in windows use hyphen-minus

**Comment by JonHanna** [comment]
@hmdhasani is it dash or minus (U+2212)?

**Comment by hmdhasani** [comment]
@JonHanna  I think that's the main point
In windows system.long works with minus 
but in Linux works with dash

**Comment by JonHanna** [comment]
Windows works with hyphen-minus (U+002D), and so for that matter does the Linux install I have to hand (but it's .NET Core 2.1.3, and also maybe this is locale-related) and the code in your workaround. Minus (U+2212) would make semantic sense while em-dash (U+2014, the dash character you put in your comment above) doesn't mean minus and so wouldn't make semantic sense. That would make producing U+2014 and then failing to parse it a slightly different problem to producing U+2212 and then failing to parse it.

**Comment by hmdhasani** [comment]
another problem is in JS as JS use hyphen-minus when I run the app in the Linux server my javascripts does not work properly and I have to fix this manually too

**Comment by karelz** [comment]
@hmdhasani can you please post a self-contained repro which contains the good and bad 'minus'? (entered via `\u` in the string). Thanks!

**Comment by hmdhasani** [comment]
the normal minus is an one ascii char: '-'
but in Linux servers it is in fact two character witch first one has no graphical representation and is '‎' (note that there is actually a hidden charter between quotes if you use arrow keys for moving cursor you will find it )
and the next charter is I think '—'

**Comment by karelz** [comment]
@hmdhasani can you please post a self-contained repro as I asked?
You seem to suggest that Linux doesn't recognize 'normal' minus character and that it has 2 alternative UTF characters. That sounds very weird to me and suspicious. If it is true, please link official documentation.

**Comment by karelz** [comment]
No response, closing.
If you have a repro, feel free to reopen.

**Comment by effyteva** [comment]
@karelz 
Hi, we tried switching to Docker containers with Linux, and just ran into the same issue.
Reproduction is pretty simple, 
long.Parse("-1") (minus, not dash) - throws in exception
Our application uses CultureInfo of he-IL
This seems like a major bug, not sure how it managed to slip through...

Is there any way of setting the Linux .NET to always use minus and not dash sign?

**Comment by effyteva** [comment]
Another example for this issue - the MySQL .NET core library suffers from the same issue as well, as can be seem from the stack track:
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt64(ReadOnlySpan`1 value, NumberStyles options, NumberFormatInfo numfmt)
   at MySql.Data.Types.MySqlInt64.MySql.Data.Types.IMySqlValue.ReadValue(MySqlPacket packet, Int64 length, Boolean nullVal)
   at MySql.Data.MySqlClient.NativeDriver.ReadColumnValue(Int32 index, MySqlField field, IMySqlValue valObject)
   at MySql.Data.MySqlClient.ResultSet.ReadColumnData(Boolean outputParms)
   at MySql.Data.MySqlClient.ResultSet.NextRow(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlDataReader.Read()

This happens when we try fetching a negative Int64 value from the database.

**Comment by effyteva** [comment]
This might be the same issue as https://github.com/dotnet/coreclr/issues/1734
Which for some reason Microsoft decided to abandon 😞

**Comment by svick** [comment]
@effyteva If you're not working with localized strings, you should always pass `CultureInfo.InvariantCulture` to any parsing or formatting methods you call. E.g.:

```c#
long.Parse("-1", CultureInfo.InvariantCulture)
```

**Comment by benaadams** [comment]
Or set it prior to making a call if its happening further down the stack e.g.
```csharp
var culture = Thread.CurrentThread.CurrentCulture;
Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;

// Db stuff
reader.Read()

// Exiting, return to culture
Thread.CurrentThread.CurrentCulture = culture;
```

**Comment by effyteva** [comment]
Thanks guys, updating all our Parse methods to InvariantCulture solved this.
Not sure where the MySQL error original from, but as soon as the Parse methods were fixed, the MySQL issue disappeared as well.

**Comment by effyteva** [comment]
> Thanks guys, updating all our Parse methods to InvariantCulture solved this.
> Not sure where the MySQL error original from, but as soon as the Parse methods were fixed, the MySQL issue disappeared as well.

We're continuing the migration to Linux. Apparently the issue with MySql originates from the MySql Connector not using the InvariantCulture as recommended.
Created a pull request on MySql connector: https://github.com/mysql/mysql-connector-net/pull/28

**Comment by effyteva** [comment]
Hi,
For anyone suffering from this issue, I've create a simple solution.
https://github.com/effyteva/Teva.Common.Cultures
