### ISSUE TITLE
ASP.NET Core 2.0 WriteStartElementAsync in XmlDictionaryWriter

### ISSUE THREAD

**Issue by CliffordSimak** [dotnet/corefx#25966]
Hello!

I`m trying to create a SOAP protocol middleware for ASP.NET Core based on [Microsoft article: Custom ASP.NET Core Middleware Example](https://blogs.msdn.microsoft.com/dotnet/2016/09/19/custom-asp-net-core-middleware-example/). And I ran into a problem of a WSDL generation.

---

On the second line I get  **`System.NotImplementedException: "The method or operation is not implemented."`**

```
await writer.WriteStartElementAsync("xs", "schema", http://www.w3.org/2001/XMLSchema");
await writer.WriteAttributeStringAsync(null, "someName", null,"someValue");
await writer.WriteEndElementAsync();
```
---

If I use `writer.WriteAttributeString( "someName","someValue");` , it works fine.

I saw [a few issues](https://github.com/dotnet/corefx/issues/18899) about` Async` methods in `XmlDictionaryWriter`, but there is nothing about `WriteAttributeStringAsync`

Thanks!
- dotnet --info
```
Product Information:
 Version:            2.1.2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
```
cc: @shmao

**Comment by JonHanna** [comment]
Was the `XmlDictionaryWriter` created using an `XmlWriter` that in turn was created using an `XmlWriterSettings` for which `Async` was set to true?

**Comment by CliffordSimak** [comment]
@JonHanna I override `System.ServiceModel.Channel.BodyWriter` class methods like:
```
protected override async void OnWriteStartEnvelope(XmlDictionaryWriter writer) {}
```
I tried to write this:
```
protected override async void OnWriteStartEnvelope(XmlDictionaryWriter writer)
{
    var settings = new XmlWriterSettings { Async = true };

    var asyncWriter = XmlWriter.Create(writer, settings)

    await asyncWriter.WriteStartElementAsync(null, "definitios", null);

    await asyncWriter.WriteAttributeStringAsync(null, "xmlns:s", null, "http://www.w3.org/2001/XMLSchema");
}
```

but **`asyncWriter`** has `XmlWriterSettings.Async = false`

**Comment by JonHanna** [comment]
I think it's a bug that it throws not implemented instead of invalid operation then, but in terms of getting a result rather than an exception, can you try setting Async to true?

**Comment by CliffordSimak** [comment]
I tried to setting `Async` to `true` in Debug mode, but after pressing the Enter key, the value is returned to `false`.

I think if the problem is in `Async mode`, then `WriteStartElementAsync` should not work, but it works.

**Comment by StephenBonikowsky** [comment]
@CliffordSimak please let us know if this is still an issue and if you need any assistance.
