### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.HttpClientHandler_DefaultProxyCredentials_Test / ProxyExplicitlyProvided_DefaultCredentials_Ignored

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#25983]
### The operation has been canceled

Failure [20171215.05](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171215.05/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandler_DefaultProxyCredentials_Test~2FProxyExplicitlyProvided_DefaultCredentials_Ignored):
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : The operation has been canceled
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext() in E:\A\_work\1955\s\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 464
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.Functional.Tests.LoopbackGetRequestHttpProxy.<StartAsync>d__2.MoveNext() in E:\A\_work\1955\s\corefx\src\System.Net.Http\tests\FunctionalTests\LoopbackGetRequestHttpProxy.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.Functional.Tests.HttpClientHandler_DefaultProxyCredentials_Test.<ProxyExplicitlyProvided_DefaultCredentials_Ignored>d__2.MoveNext() in E:\A\_work\1955\s\corefx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.DefaultProxyCredentials.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in E:\A\_work\1955\s\corefx\src\Common\src\System\Threading\Tasks\RendezvousAwaitable.cs:line 62
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext() in E:\A\_work\1955\s\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 858
```

## History of failures

Previously, the test was failing (on .NET Core) on different error: https://github.com/dotnet/corefx/issues/23702#issuecomment-352601673

Day | Build | OS | Error message
-- | -- | -- | --
12/15 | 20171215.05 | Win8.1 | The operation has been canceled - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171215.05/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandler_DefaultProxyCredentials_Test~2FProxyExplicitlyProvided_DefaultCredentials_Ignored)
12/16 | 20171216.01 | Win8.1 | The operation has been canceled - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171216.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ManagedHandler_HttpClientHandler_DefaultProxyCredentials_Test~2FProxyExplicitlyProvided_DefaultCredentials_Ignored) (ManagedHandler)
2/9 | 20180209.05 | Win8.1 | The operation has been canceled - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180209.05/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandler_DefaultProxyCredentials_Test~2FProxyExplicitlyProvided_DefaultCredentials_Ignored)

One of the failures is on MangedHandler - most likely a test issue.

**Comment by rmkerr** [comment]
I took a look at a wireshark capture of this failure, and it looks to me like the correct request is being sent to the LoopbackGetRequestHttpProxy. The request includes the correct credentials (rightusername:rightpassword), but no response is ever received. That leads me to think that the issue might be another server problem, since the LoopbackGetRequestHttpProxy ultimately makes a request to the corefx-net.cloudapp.net echo server.

**Comment by karelz** [comment]
Why do you think `LoopbackGetRequestHttpProxy` forwards to echo server?
Based on the name and brief code inspection, it should be just local on loopback. Is it not the case?

**Comment by karelz** [comment]
Or did you mean the test itself uses echo servers?

https://github.com/dotnet/corefx/blob/7bdd866d7711c2d766772ab50b5c8367f227a2eb/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.DefaultProxyCredentials.cs#L64

**Comment by rmkerr** [comment]
That's what I assumed was happening after looking at the code, particularly lines 96-100 of the LoopbackGetRequestHttpProxy:
```
// Forward the request to the server.
var request = new HttpRequestMessage(HttpMethod.Get, url);
foreach (var header in headers) request.Headers.Add(header.Key, header.Value);
using (HttpClient outboundClient = new HttpClient())
using (HttpResponseMessage response = await outboundClient.SendAsync(request).ConfigureAwait(false))
```
But yes, that would be specific to this particular test since it takes the remote url from the request.
