### ISSUE TITLE
HttpClient/HttpWebRequest gives error 407 (ProxyAuthenticationRequired) when used with a proxy server that requires authentication

### ISSUE THREAD

**Issue by chetski** [dotnet/corefx#25997]
When making a HTTP request with either HttpClient or HttpWebRequest via a proxy server that requires authentication the result is always 407 (ProxyAuthenticationRequired). Compiling the same code with .NET framework does not give an error. Code to reproduce the issue:

```c#
    var credentials = new NetworkCredential("username", "password");
    var proxyURI = new Uri("http://xxx.xxx.xxx.xxx:80");
    WebProxy proxy = new WebProxy(proxyURI, true) { UseDefaultCredentials = false, Credentials = credentials };

    HttpWebRequest req = HttpWebRequest.Create(new Uri("http://bbc.co.uk")) as HttpWebRequest;
    req.UseDefaultCredentials = false;
    req.Proxy = proxy;

    using (WebResponse response = req.GetResponse())
    {
        using (StreamReader responseStream = new StreamReader(response.GetResponseStream()))
        {
             string htmlData = responseStream.ReadToEnd();
        }
    }
```

The same error is given if we make the request via `HttpClient` and `HttpWebRequest`. It also happens if you create a custom proxy server by implementing `IWebProxy`. Verified the bug on Windows 10 using VS2017 using .NET Core 1.0, 1.1 & 2.0. Verified the exact same code works fine on the same environment using .NET Framework 4.6.1.

[EDIT] Add C# syntax highlighting by @karelz

**Comment by chetski** [comment]
@karelz is this a confirmed bug now and I presume will be resolved in v2.1.0?
Also, are there any workarounds in the meantime?

**Comment by karelz** [comment]
@chetski it is likely a bug (my best guess based on your report). Area experts need to validate.
Given that it is compatibility difference against .NET Framework, we should try to address it in 2.1 (unless there are special circumstances).

**Comment by karelz** [comment]
Triage: @chetski do you have a repro with HttpClient? We believe we have tests covering the case there. HttpWebRequest might be broken.

**Comment by karelz** [comment]
No response, closing. Feel free to reopen when there's more information.
