### ISSUE TITLE
System.Numerics.Vectors 4.1.0 not portable?

### ISSUE THREAD

**Issue by TIHan** [dotnet/corefx#2599]
I noticed the new release of System.Numerics.Vectors 4.1.0, but I cannot add it to a Profile7 PCL project because there is no portable library of it. 4.0.0 had a portable library, is there something that I am missing?

**Comment by weshaggard** [comment]
cc @mellinoe

**Comment by mellinoe** [comment]
I'm working on a fix for this, sorry for the delay.

**Comment by mellinoe** [comment]
Hey @TIHan , I should have a newer version of the package that supports the old PCL profile. Could you try grabbing the package here and see if it works for you (installs, builds, etc) in your project?

http://1drv.ms/1f8F8BS

I've tested locally in a few different project types in VS 2015, and a couple in 2013.

**Comment by mellinoe** [comment]
This is fixed in any of the newer (beta) versions of System.Numerics.Vectors. Let me know if those give you any issues in this scenario, but it should now be installable into any project that it could be previously.

**Comment by dsancho** [comment]
I'm trying to use with profile 111 with no luck. I tried release and beta.

**Comment by mellinoe** [comment]
We currently on support the portable target of `net45 + win8`. As part of our [current packaging work](https://github.com/dotnet/corefx/pull/6047), we may choose to add some additional valid targets that support it's dependencies, which might include profile 111 (I'm not sure which targets exactly that is).
