### ISSUE TITLE
Does anybody know what these errors mean at runtime? (Authentication)

### ISSUE THREAD

**Issue by ColbyBurke** [dotnet/corefx#25995]
I am using Swagger so maybe that has to do with it...
```
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService:Information: Authorization failed for user: (null).
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService:Information: Authorization failed for user: (null).
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
Microsoft.AspNetCore.Mvc.ChallengeResult:Information: Executing ChallengeResult with authentication schemes ().
Microsoft.AspNetCore.Mvc.ChallengeResult:Information: Executing ChallengeResult with authentication schemes ().
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler:Information: AuthenticationScheme: bearer was challenged.
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler:Information: AuthenticationScheme: bearer was challenged.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action AngularChat.Controllers.HomeController.Index (AngularChat) in 74.8893ms
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action AngularChat.Controllers.HomeController.Index (AngularChat) in 74.8893ms
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Users\Colby\.nuget\packages\microsoft.aspnetcore.webutilities\2.1.0-preview1-27853\lib\netstandard2.0\Microsoft.AspNetCore.WebUtilities.dll'. Cannot find or open the PDB file.
Microsoft.AspNetCore.NodeServices:Information: webpack built 0f085bd0025f58178255 in 5815ms
Microsoft.AspNetCore.NodeServices:Information: webpack built 0f085bd0025f58178255 in 5815ms
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 2455.4288ms 401 
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 2455.4288ms 401 
```
here is from my utils:

    internal sealed class UserInfoProvider : IUserInfoProvider
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        public UserInfoProvider(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor
                ?? throw new ArgumentNullException(nameof(httpContextAccessor));
        }

        public UserInfoModel Get()
        {
            var userIdentity = _httpContextAccessor.HttpContext.User.Identity;

            if (!userIdentity.IsAuthenticated)
                throw new UnauthorizedAccessException();

            return new UserInfoModel(userIdentity.Name);
        }
    }

**Comment by Clockwork-Muse** [comment]
... you probably want StackOverflow, or _maybe_ the relevant ASP NET repositories, if they can't give you any help.  This isn't really the correct place for this question.

First, though, I'd check and make sure your JWT is valid, being sent, etc.  It's impossible to tell what's really going wrong here otherwise.

**Comment by ColbyBurke** [comment]
I cant post on stackoverflow anymore...

**Comment by karelz** [comment]
Please ask on [ASP.NET repos](https://github.com/aspnet) or on StackOverflow ("cant post there" seems weird unless there was a ban or something like that)
