### ISSUE TITLE
Invalid setting csharp_new_line_within_query_expression_clauses in .editorconfig

### ISSUE THREAD

**Issue by wanton7** [dotnet/corefx#25991]
I used .editorconfig from corefx in our project. Noticed that .editorconfig file has one invalid setting that Roslyn doesn't support csharp_new_line_within_query_expression_clauses.
But Roslyn does support csharp_new_line_between_query_expression_clauses and it's missing from .editorconfig.

Also noticed that at least following settings are missing as well

csharp_indent_case_contents_when_block  
dotnet_style_prefer_inferred_tuple_names  
dotnet_style_prefer_inferred_anonymous_type_member_names  
dotnet_style_require_accessibility_modifiers  
dotnet_style_prefer_auto_properties  
csharp_style_deconstructed_variable_declaration  
dotnet_style_prefer_is_null_check_over_reference_equality_method

**Comment by weshaggard** [comment]
@wanton7 is this something you would like to submit a PR to address?

**Comment by weshaggard** [comment]
No problem @wanton7 thanks for reporting. We generally get the settings in the .editorconfig to match our coding guidelines (https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md).  I personally don't even know how to determine which settings are valid or not in this file. For this issue I think it is best to just rename csharp_new_line_within_query_expression_clauses to csharp_new_line_between_query_expression_clauses. 

If you want to try and submit a PR with that change it would be a good easy first PR. If not I will fix that.

**Comment by sharwell** [comment]
Tagging @kuhlenh who was looking into unifying these
