### ISSUE TITLE
MetadataStringComparer needs to use the user-supplied MetadataStringDecoder.

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#26]
MetadataReader.GetString now uses the Encoding provided via MetadataStringDecoder.Encoding or falls back to Encoding.UTF8 if none is provided.

However, MetadataStringComparer still uses a custom UTF-8 implementation, which does not handle errors correctly and prevents any customization of the fallback behaviour.

Care must be taken when making this change to not allocate as that is essentially the entire point of MetadataStringComparer.

**Comment by orteipid** [comment]
Could you possibly clarify the use of "not to allocate" in the last sentence? Assuming that this is a user-supplied MetadataStringDecoder and using one of the code examples in MetadataStringComparer, do you have something in mind such as:

    if (reader.StringComparer.Equals(typeDef.Namespace, "System", MetadataStringDecoder decoder) &&
        reader.StringComparer.Equals(typeDef.Name, "Object", MetadataStringDecoder decoder))
    {
        // found System.Object
    }

Please pardon if this is question is off-base; I've just been looking at this issue after seeing it mentioned in Gitter chat and would be looking to help in any way I can.

**Comment by nguerrera** [comment]
@orteipid The MetadataReader already has a MetadataStringDecoder and the StringComparer has a MetadataReader. There's no need to pass it in. 

The problem is that we don't use the decoder to compare UTF-8 values in metadata to UTF-16 System.Strings. Today, we only use it to create System.Strings from metadata. This is inconsistent but only observable for malformed UTF-8 in metadata.

The entire point of MetadataStringComparer.Equals is to avoid allocation so we can't just create a string using the MetadataStringDecoder and call String.Equals. I think we'll have to decode to UTF-16 on the stack or pooled memory N characters at a time, but we should optimize the common ascii-only case to not bother copying the text anywhere.

**Comment by nguerrera** [comment]
I'm looking at this now. I'll have a fix tomorrow.
