### ISSUE TITLE
Change OwnedMemory<T> to IOwnedMemory<T>

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefx#26002]
This would allow many types with existing class hierarchy to work with Memory<T>.
For example, SafeBuffer, Utf8String, etc.

cc: @stephentoub, @terrajobst, @davidfowl, @ahsonkhan, @joshfree, @jkotas

**Comment by ianhays** [comment]
Since https://github.com/dotnet/corefx/issues/25188 is In-Progress, it would probably be wise to wait until its completion before starting this issue to avoid clashes.

**Comment by terrajobst** [comment]
We decided against it. We cannot model read-only spans with this interface unless we're creating RW and RO interfaces for this.
