### ISSUE TITLE
System.IO.Directory.Exists(string path) does not trim trailing whitespace of provided path on Linux

### ISSUE THREAD

**Issue by bergmeister** [dotnet/corefx#26008]
The documentation of `System.IO.Directory.Exists(string path)` [here ](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.exists?view=netcore-2.0#System_IO_Directory_Exists_System_String_) states that
> Trailing spaces are removed from the end of the path parameter before checking whether the directory exists.

This is true for Windows, but not for Linux (tested on Ubuntu 17 and WSL)
## Expected
````c#
Assert.True(System.IO.Directory.Exists("./"));
Assert.True(System.IO.Directory.Exists("./ "));
````
## Actual

The second assertion fails only on Linux (Ubuntu 17.04 VM in Azure and also WSL)

## Environment
````
> dotnet --info
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  17.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.2/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
````

**Comment by divinity76** [comment]
this shouldn't be done anyway on linux, because on linux, folder names ending in spaces is perfectly legal. in fact, a folder name only containing spaces is perfectly legal.  if this was "fixed", it would be impossible to use this function to deduce if the folder "   " (3 spaces) exists or not.

**Comment by bergmeister** [comment]
Ok. I see your point. Then either the documentation needs to be updated or the breaking change to not trim trailing whitespace on Windows should be made to make the implementation consistent. I don't understand why the trimming is implemented/needed on Windows at all.

**Comment by divinity76** [comment]
my vote goes to updating the docs ^^ 

(also, funfact, on windows, mkdir() is a wrapper for the CreateDirectory winapi, CreateDirectory is a wrapper for NtCreateFile, but first CreateDirecotry calls ntdll.dll!RtlDosPathNameToRelativeNtPathName_U , which fails if there are trailing spaces, and if that fail, CreateDirectory refuse to create the directory, but if you call NtCreateFile directly, you can actually create folders with trailing spaces in windows too (windows 7 ultimate x64 at least) - but that is a long way from "perfectly legal", as is the case in linux)

**Comment by danmosemsft** [comment]
@JeremyKuhne can you confirm this is a doc issue.

**Comment by JeremyKuhne** [comment]
This is a documentation issue. Spaces are valid trailing chars in Unix. In Windows they get normalized away as @divinity76 has pointed out (as do trailing periods).  If you're curious I've described this in great detail at https://blogs.msdn.microsoft.com/jeremykuhne/2016/04/21/path-normalization/.  There are other posts on my blog that go into how paths go through the system.

If you want the trailing space on Windows you can use `\\?\`, which skips normalization in both .NET and Windows. Note that using trailing space or periods in your paths is highly discouraged. Most applications will fail as Win32 normally trims these away.

In the interest of completeness, there are more obscure behaviors that .NET has. In .NET Core 2.1 these behaviors have been removed. These all came from `Path.GetFullPath()` which most APIs call. Other whitespace characters (other than space) were trimmed by `GetFullPath()`.  Additionally, in some cases, leading spaces would be removed.

I'm going to call out these issues as part of the 2.1 doc updates.  (https://github.com/dotnet/docs/issues/4483)  I'm closing out this issue in lieu of that.
