### ISSUE TITLE
Build Fail on Linux Ubuntu: cookecollection.cs could not be found

### ISSUE THREAD

**Issue by breautek** [dotnet/corefx#2600]
Trying to build the latest corefx on linux Ubuntu eventually produces this error and stops:

CSC : error CS2001: Source file '/home/norman/development/corefx/src/System.Net.Primitives/tests/UnitTests/../../src/System/Net/cookiecollection.cs' could not be found. [/home/norman/development/corefx/src/System.Net.Primitives/tests/UnitTests/System.Net.Primitives.Unit.Tests.csproj]

I had a look at the directory and I have a file named "CookieCollection.cs", so I suspect it's just a case sensitivity error.

If anymore information is required.. please let me know what to include, and how to obtain the required information.

**Comment by akoeplinger** [comment]
Yep, you're right. @pgavlin already fixed that casing difference in https://github.com/dotnet/corefx/pull/2595, so just wait until that one is merged :smile:

**Comment by breautek** [comment]
Cool. In that case I'll close this issue.

But if anyone requires a changeset in the meantime: https://github.com/breautek/corefx/commit/aa9227ff364e28c47a7902fba00294df1b16d125
