### ISSUE TITLE
Uniform tuple representation

### ISSUE THREAD

**Issue by Horusiath** [dotnet/corefx#26003]
Right now, tuples/value tuples are implemented as set of types with distinct arity (max to 7 elements). However they could be implemented in more uniform manner:

```csharp
public interface ITuple { }
public struct Unit : ITuple 
{
    public static Unit Default { get; } = new Unit();
}
public struct Cons<TValue, TNext> : ITuple where TNext: ITuple
{
    public TValue Value { get; }
    public TNext Next { get; }
    public Cons(TValue value, TNext next) { ... }
}
````
With this implementation and some helper methods we could represent Tuples of any size:

```csharp
Cons<int, Cons<string, Cons<bool, Unit>>> tuple = 
    Tuple.Cons(1, Tuple.Cons("hello", Tuple.Cons(true, Unit.Default)));
int item1 = tuple.Value;      // tuple.Item1
string item2 = tuple.Next.Value;    // tuple.Item2
bool item3 = tuple.Next.Next.Value;    // tuple.Item3
```
While this design can work (and potentially can be even as efficient as `ValueTuple<>` thanks to generic nature of this data structure), it's quite clear, that without compiler's help it looks obscure and it's not pleasant to work with.

For this reason, the idea here would be to add language level support for tuples or variadic size:

```csharp
Unit a = (); // unit type - potentially useful in the future of the language
(int, string, bool) tuple = (1, "hello", true); // equivalent to Cons<int, Cons<string, Cons<bool, Unit>>>
(item1, item2, item3) = tuple; // tuple deconstruction
```

**Comment by JonHanna** [comment]
How does this differ in practice from what we already have with `(1, 2, 3, 4, 5, 6, 7, 8, 9)` being a `ValueTuple< int, int, int, int, int, int, int, ValueTuple<int, int>>`? This seems perhaps a bit theoretically simpler, a bit less convenient if one does have to deal with the type without the sugar, and about the same for most use.

How would this be made compatible with the existing syntax that produces `ValueTuple`? I don't see how the compiler would infer which was needed.

**Comment by Horusiath** [comment]
I think, that the most advantages will target library designers and systems using heavy code emitting and generic programming. I.e. right now there is no way of defining things like `DoSmth<T>(T args) where T: ITuple`. Even then, if a person would like to present any kind of generic programming over tuples, he/she needs to check for every of 8 possible variants and build the same repetitive thing for every single one of them - I know I had to do that more than once ex:

- emitters wrapping generic operations (see: TypeShape project or F# GraphQL implementation).
- serializers
- type-safe zippers and folders for streaming libraries

However this design could go further: i.e. this would allow us fold multiple versions of `Func<>` and `Action<>` into one like `Func<(int, int), int>` (as existing Func equivalent) or `Func<(int, int), Unit>` (as existing Action equivalent). This abstraction doesn't have to come with cost. This design already exists in several languages, and some of them - like F# - are able to elide actual tuple instantiation when calling such delegates.

The only problem I see here is how to comfort this with existing design. This is were I hope to get some help from .NET community.

**Comment by jcouv** [comment]
@Horusiath The `System.ValueTuple` types are designed closely after `System.Tuple` for ease of migration and interop with F#. The API has shipped and therefore cannot be changed at this point.

As for proposing a language feature to allow tuple syntax to use different underlying types, I'd suggest checking out the [csharplang](https://github.com/dotnet/csharplang/) repo. I suspect there is already a discussion/proposal along those lines, although maybe not for that specific underlying type.
Personally, I'm skeptical, as the purpose of the tuple syntax is to abstract away from the underlying type, so I don't want to worry that your tuple and my tuple are not the same (and so cannot interop properly).
