### ISSUE TITLE
PipeStream handling of async read on broken pipe is broken with non-async handle (on Windows at least)

### ISSUE THREAD

**Issue by poizan42** [dotnet/corefx#2601]
PipeStream.BeginRead returns a PipeStreamAsyncResult if the pipe is broken, and does not set pipeStreamAsyncResult._activeReadWriteTask. However PipeStreamAsyncResult.EndRead expects the async result passed to either be of type StreamReadWriteAsyncResult or _activeReadWriteTask to be non-null. This result in a `throw new ArgumentException(SR.InvalidOperation_WrongAsyncResultOrEndReadCalledMultiple)` getting executed.

Note that this issue is also present in the current .NET frameworks (in the reference source as well as in System.Core v4.0_4.0.0.0__b77a5c561934e089): PipeStream.BeginRead returns a PipeStreamAsyncResult here as well when the pipe is broken and does not set _activeReadWriteTask. PipeStream.EndRead forwards the call to Stream.EndRead when it's not asynchronous, which then fails with the same exception because _activeReadWriteTask is null.

**Comment by bpschoch** [comment]
I think the idea is to get rid of the BeginRead/EndRead constructs at least for core...see #2414

**Comment by Maxwe11** [comment]
This bug present but couldn't be repro in .NET Core because `PipeStream.BeginRead` is private.
It should be fixed in full .NET.
/cc @stephentoub

**Comment by stephentoub** [comment]
@poizan42, thanks for the issue.   As @Maxwe11 and @bpschoch mentioned, this issue doesn't exist for .NET Core as the Begin/End methods aren't available, and instead only the Task-based methods are exposed.  For .NET 4.6, I tried the below and I couldn't get this to repro:
```C#
using System;
using System.IO.Pipes;
using System.Threading.Tasks;

class Program
{
    static void Main()
    {
        const string name = "testpipe1";
        using (var server = new NamedPipeServerStream(name, PipeDirection.Out, 1, PipeTransmissionMode.Byte, PipeOptions.Asynchronous))
        using (var client = new NamedPipeClientStream(".", name, PipeDirection.In, PipeOptions.Asynchronous))
        {
            Task t = server.WaitForConnectionAsync();
            client.Connect();
            t.Wait();

            server.Disconnect();

            IAsyncResult iar = client.BeginRead(new byte[1], 0, 1, null, null);
            try { Console.WriteLine(client.EndRead(iar)); }
            catch (Exception e) { Console.WriteLine(e); }
        }
    }
}
```
Do you have a repro you could share?

**Comment by Maxwe11** [comment]
@stephentoub `server.Disconnect();` touggle server into `PipeState.Disconnected` state, for repro server should be in `PipeState.Broken` state.

**Comment by poizan42** [comment]
using System;
	using System.IO.Pipes;

	namespace corefx2601
	{
	  class Program
	  {
		static void Main()
		{
		  using (var pipeOut = new AnonymousPipeServerStream(PipeDirection.Out))
		  using (var pipeIn = new AnonymousPipeClientStream(PipeDirection.In, pipeOut.ClientSafePipeHandle))
		  {
			pipeOut.Close();
			pipeIn.ReadByte();
			IAsyncResult iar = pipeIn.BeginRead(new byte[1], 0, 1, null, null);
			try { Console.WriteLine(pipeIn.EndRead(iar)); }
			catch (Exception e) { Console.WriteLine(e); }
		  }
		}
	  }
	}

When running this in .NET 4.6 it outputs:

	System.ArgumentException: Either the IAsyncResult object did not come from the corresponding async method on this type, or EndRead was called multiple times with the same IAsyncResult.
	   at System.IO.Stream.EndRead(IAsyncResult asyncResult)
	   at corefx2601.Program.Main() in c:\projects\kb-f2-version-4.5.1\corefx2601\corefx2601\Program.cs:line 16

**Comment by stephentoub** [comment]
@poizan42, great, thank you for the code!

This does repro for me as well on .NET 4.6, as does the following equivalent using ReadAsync:
```C#
using System.IO.Pipes;

class Program
{
    static void Main()
    {
        using (var pipeOut = new AnonymousPipeServerStream(PipeDirection.Out))
        using (var pipeIn = new AnonymousPipeClientStream(PipeDirection.In, pipeOut.ClientSafePipeHandle))
        {
            pipeOut.Close();
            pipeIn.ReadByte();
            pipeIn.ReadAsync(new byte[1], 0, 1).GetAwaiter().GetResult();
        }
    }
}
```

The Task-based version doesn't have the same problem on .NET Core.   There's a test for the case for Read and ReadByte, but it was missing ReadAsync, so I've added that to the test case here: #2899.

Since it doesn't repro on .NET Core, this issue isn't the ideal place to track the problem, so I'm going to close this and open a bug against the desktop implementation in our internal TFS.

Thanks, again.
