### ISSUE TITLE
HttpStatusCode to implement RFC 6585 

### ISSUE THREAD

**Issue by kasper3** [dotnet/corefx#26018]
Please implement complete list of HTTP status codes.  See https://tools.ietf.org/html/rfc6585 for many status codes that are missing in:

https://github.com/dotnet/corefx/blob/master/src/System.Net.Primitives/src/System/Net/HttpStatusCode.cs

Ignoring the `Unofficial codes` section from this list: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes, we basically should have all status codes covered in HttpStatusCode enum.

Ex, Azure DocumentDB server returns 429 (Too Many Requests) for which i have to check integral value of HttpResponseMessage.StatusCode in HttpClient.

**Comment by davidsh** [comment]
This issue is basically a duplicate of this: #4382

**Comment by kasper3** [comment]
Thanks!
