### ISSUE TITLE
Microsoft.CSharp is missing DynamicMetaObjectProviderDebugView

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/corefx#26012]
Why isn't `Microsoft.CSharp.RuntimeBinder.DynamicMetaObjectProviderDebugView` available in .NET Core? It's a debug view used by debuggers to show properties of dynamic types.

**Comment by OmarTawfik** [comment]
@stephentoub do you know who can answer this?

**Comment by stephentoub** [comment]
> do you know who can answer this?

You? :smile:  Or @VSadov?

If it's valuable, I don't see why it couldn't be added; it's internal, so it's not additional surface area.

Maybe it was removed because nothing was visibly relying on it?

**Comment by cston** [comment]
Fixed in https://github.com/dotnet/corefx/pull/38656
