### ISSUE TITLE
File.GetLastWriteTimeUtc on Ubuntu is precise only up to seconds

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#26024]
### Steps to reproduce:
1. Create a new console app
2. Edit Program.cs to print it's last write time out:

```C#
using System;
using System.IO;

namespace ts_test
{
    class Program
    {
        static void Main(string[] args)
        {
            var file = Path.Combine(Directory.GetCurrentDirectory(), "Program.cs");
            var t = File.GetLastWriteTimeUtc(file);

            Console.WriteLine(t.ToString("o"));
        }
    }
}
```

On my Windows machine, here's the output:

> 2017-12-22T04:59:47.5871375Z

On my Ubuntu VM, here's the output:

> 2017-12-22T05:18:38.0000000Z

Notice the missing precision after the seconds digits. The filesystem does seem to have a higher precision timestamp associated with the file:
```
>:~/src/ts-test$ ls --full-time Program.cs
-rw-rw-r-- 1 prkrishn prkrishn 320 2017-12-22 05:18:38.250041900 +0000 Program.cs
```

```
 dotnet --info
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.2/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

### Further background:
I noticed this when I was writing tests to cover incremental build scenarios in my MSBuild target. MSBuild uses file timestamps to determine if the inputs are consistent with the outputs. Consequently inputs modified within a second of creating the output would be treated as consistent resulting in MSBuild target executions from being skipped. I also some my tests fail on Travis OSX 10.12 but I don't have a machine handy to confirm if this was the cause.

**Comment by pranavkm** [comment]
cc @rynowak

**Comment by stephentoub** [comment]
@pranavkm, how do you suggest getting a more precise result? e.g. stat gives back time_t values with second-level precision.

**Comment by pranavkm** [comment]
@stephentoub running `getmtime` in python gives me a higher precision result:

```
dt= os.path.getmtime('/home/prkrishn/src/ts-test/Program.cs')
print(datetime.datetime.utcfromtimestamp(dt))

> 2017-12-22 14:36:35.642042
```

Their implementation also seems to use os.stat: https://github.com/python/cpython/blob/6f0eb93183519024cb360162bdd81b9faec97ba6/Lib/genericpath.py#L53-L55.

**Comment by danmosemsft** [comment]
I think this is relevant in stat.h:
```c++
  65 #ifdef __USE_XOPEN2K8
  66     /* Nanosecond resolution timestamps are stored in a format
  67        equivalent to 'struct timespec'.  This is the type used
  68        whenever possible but the Unix namespace rules do not allow the
  69        identifier 'timespec' to appear in the <sys/stat.h> header.
  70        Therefore we have to handle the use of this header in strictly
  71        standard-compliant sources special.  */
  72     struct timespec st_atim;            /* Time of last access.  */
  73     struct timespec st_mtim;            /* Time of last modification.  */
  74     struct timespec st_ctim;            /* Time of last status change.  */
  75 # define st_atime st_atim.tv_sec        /* Backward compatibility.  */
  76 # define st_mtime st_mtim.tv_sec
  77 # define st_ctime st_ctim.tv_sec
  78 #else
  79     __time_t st_atime;                  /* Time of last access.  */
  80     unsigned long int st_atimensec;     /* Nscecs of last access.  */
  81     __time_t st_mtime;                  /* Time of last modification.  */
  82     unsigned long int st_mtimensec;     /* Nsecs of last modification.  */
  83     __time_t st_ctime;                  /* Time of last status change.  */
  84     unsigned long int st_ctimensec;     /* Nsecs of last status change.  */
  85 #endif
```

My guess is Python is compiled with some define that enables the first block so their st_mtime is actually getting st_mtim.tv_sec. Whereas our SystemNative is not. We apparently need to define `_POSIX_C_SOURCE=200809L` or explicitly get st_mtim.tv_sec etc and stick them on the end. 

Note that the CoreCLR PAL defines `_POSIX_C_SOURCE=200809L`  for Linux. I am not sure what other effects it would have if we define it for SystemNative.

**Comment by danmosemsft** [comment]
The above is not correct. Nanoseconds are available in both senses of the define above (either with st_mtim.tv_nsec or with st_mtimensec). However that is the kernel shape of the struct. The API shape can be different and glibc converts between as needed (xstatconv). The shape we are reading off the API only has the time_t.

I'm not famlilar with how to navigate the headers efficiently so I'm having trouble fitting together how one gets back the nsec.

**Comment by danmosemsft** [comment]
By adding `save-temps=obj` to `src/Native/Unix/CMakeLists.txt` I can see the preprocessor output and it shows our ConvertFileStatus code like
```
    dst->ATime = src->st_atime;
```
is becoming
```
    dst->ATime = src->st_atim.tv_sec;
```
So I was right the first time. We simply need to access st_atim instead of st_atime.

**Comment by danmosemsft** [comment]
It looks like this is where Python is getting the full nsec out of the native struct and putting it into the Python struct as `st_mtime` even though it may have come from `st_mtim`. 
https://github.com/python/cpython/blob/bbdb17d19bb1d5443ca4417254e014ad64c04540/Modules/posixmodule.c#L2018
That explains why the Python implementation linked above is including nanoseconds despite seemingly using `st_mtime`.

**Comment by danmosemsft** [comment]
Working on fix.

**Comment by danmosemsft** [comment]
This should be fixed now. @pranavkm if you are interested you could look into adding subsecond granularity to setting timestamps, using utimensat  where available.
