### ISSUE TITLE
`ListEqualityComparer<TList>.Default` in contrast to `EqualityComparer<T>.Default`

### ISSUE THREAD

**Issue by qaqz111** [dotnet/corefx#26036]
The `EqualityComparer<T>.Default` returns a default implement of `EqualityComparer<T>` which was returned by `EqualityComparer<T>.CreateComparer()`, but this one do not consider for the situation of `T`=`IEnumerable<TSource>`.

The basic thought is, add this logic to `EqualityComparer<T>.CreateComparer()`:
```C#
var genericParameter = typeof(T);
if (genericParameter.IsGenericType
  && genericParameter.GenericTypeArguments.Length == 1
  && typeof(IEnumerable<>).MakeGenericType(genericParameter.GenericTypeArguments[0])
    .IsAssignableFrom(genericParameter))
{
  return (EqualityComparer<T>)RuntimeTypeHandle.CreateInstanceForAnotherGenericParameter(
    (RuntimeType)typeof(SequentialEqualityComparer<T>), genericParameter);
}
```
The `SequentialEqualityComparer<T>` is a derived class of `EqualityComparer<T>`:
```C#
internal sealed class SequentialEqualityComparer<T> : EqualityComparer<T>
{
  private static readonly MethodInfo miSequenceEqual = typeof(Enumerable)
    .GetMethods(BindingFlags.Public | BindingFlags.Static)
    .First(mi => nameof(Enumerable.SequenceEqual) == mi.Name && 2 == mi.GetParameters().Length)
    .MakeGenericMethod(typeof(T).GenericTypeArguments[0]);

  public override bool Equals(T x, T y) => miSequenceEqual.Invoke(null, new object[]{x, y});

  public override int GetHashCode(T obj)
  {
    //return obj.GetHashCode();
  }

  //...other overrides
}
```

**Comment by JonHanna** [comment]
This could be useful in many cases (if you fix that the `GetHashCode()` is wrong as it doesn't match the equality criteria) but wouldn't be safe for all enumerations (there's no guarantee that an `IEnumerable<T>` can be successfully cycled through twice) and more importantly would be a very strongly breaking change.

**Comment by qaqz111** [comment]
I know that the `GetHashCode` should not be implemented like that, the main purpose is to give a thought and a basic implementation snippet as a reference.

And, yes you are right, looks like there is not a stable way to solve the problem of enumerating twice on an `IEnumerable<T>`, maybe this is why `EqualityComparer<T>.Default` does not walk into `IEnumerable<TSource>`.

**Comment by JonHanna** [comment]
The biggest issue remains the incompatibility. Until now anyone who wanted reference equality on such types got it as the default. This would break all such code.

**Comment by qaqz111** [comment]
Yes, any logic change of `EqualityComparer<T>.Default` will break existing code that using it. So, there can be a new class called `ListEqualityComparer<TList>` but not making change to `EqualityComparer<T>.Default`.
