### ISSUE TITLE
Dictionary exposes internal type comparer

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#26033]
According to @jkotas, Dictionary is not supposed to leak the fact that it is internally using the NonRandomizedComparer as it does below:

```
var dict = new Dictionary<string, int>();
Assert.NotSame(EqualityComparer<string>.Default, dict.Comparer);
```

For more information please take a look at the following PR #24779

**Comment by jkotas** [comment]
This is regression from .NET Core 2.0.

**Comment by maryamariyan** [comment]
@jkotas what is the expected fix for this?

**Comment by jkotas** [comment]
I think the implementation of the Dictionary Comparer property should be changed to:

```
public IEqualityComparer<TKey> Comparer
{
    get
    {
        return (_comparer is NonRandomizedStringEqualityComparer) ? (IEqualityComparer<TKey>)EqualityComparer<string>.Default : _comparer;
    }
}
```

**Comment by MarcoRossignoli** [comment]
I removed [special-cases checks](https://github.com/dotnet/corefx/compare/master...MarcoRossignoli:issues/26033) and tests with my private [CoreCLR](https://github.com/dotnet/coreclr/pull/16151). Do i have to wait merge on CoreCLR to pull?Sorry this is first time to me on "cross changes" i don't know the steps.

cc: @jkotas @maryamariyan @danmosemsft

**Comment by jkotas** [comment]
@MarcoRossignoli Yes, that's the process.

**Comment by jkotas** [comment]
Wait for the matching
