### ISSUE TITLE
Unnecessary "is"-"cast" sequence in IPEndPoint.Equals()

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/corefx#26049]
Here's the current code:

    //class IPEndPoint
    public override bool Equals(object comparand)
        {
            if (!(comparand is IPEndPoint))
            {
                return false;
            }
            return ((IPEndPoint)comparand)._address.Equals(_address) && ((IPEndPoint)comparand)._port == _port;
      }

`is` is followed by two casts. This can be replaced with single `as`:

      var other = comparand as IPEndPoint;
      if (other == null)
      {
         return false;
      }
      return other._address.Equals(_address) && other._port == _port;

**Comment by AlexG2017** [comment]
Hi guys,
Could you please assign the issue to me?

**Comment by JonHanna** [comment]
This seems like a reasonable case for implementing `IEquatable<T>` too, though that would need an API change.

**Comment by karelz** [comment]
Fixed in #26057
