### ISSUE TITLE
IPEndPoint cannot return the correct value when compare the same value

### ISSUE THREAD

**Issue by Luoyingliang** [dotnet/corefx#26048]
There are wrong value return when I do the execute this code:
ip1==ip2
both ip1 and ip2 are IPEndPoint type,and value both are "192.168.31.15:55360",but it doesn't return true.
now I used the ToString() method to instead of that

**Comment by Dmitry-Me** [comment]
This is because the class doesn't have `operator ==` overloaded. You could try `Equals()` method instead.

**Comment by Luoyingliang** [comment]
could you consider to add the operator overloaded method to next version?

**Comment by jnm2** [comment]
Out of curiosity, why was `==` left as reference equality? This has bugged me.
