### ISSUE TITLE
Add another constructor to Span using IntPtr

### ISSUE THREAD

**Issue by realvictorprm** [dotnet/corefx#26045]
Hello,

in F# we cannot cast ptr's to void ptr's (the type `nativeptr<unit>` is disallowed due to `unit` isn't an unmanaged type). Therefor it's currently not possible for me to create a Span from stackallocated memory in F# 😢 (Signature of the constructor is funnily `ptr:nativeptr<unit>* length:int -> Span`).

Easiest solution short-term would be to add another constructor to the Span class which accepts an `IntPtr`. Long-term I try to solve the issue in F#, for reference see [this](https://github.com/Microsoft/visualfsharp/issues/4166) issue.

If there's something wrong with `IntPtr` please tell me, I might miss some reason for not using it🤔 ?

**Comment by jkotas** [comment]
Similar overload was proposed and rejected in https://github.com/dotnet/corefx/issues/18946.

**Comment by realvictorprm** [comment]
Hm okay. Well I think my reason for adding such a constructor is quite different than the one in the issue so maybe it could be considered again?

**Comment by poizan42** [comment]
@realvictorprm I agree it's a bit silly that F# complains here, but you can just use IntPtr.ToPointer as a workaround, so no need for another .NET constructor:

```FSharp
let someOperationWithSpan () =
    let data = NativePtr.stackalloc<byte>(256)
    let voidPtr = (data |> NativePtr.toNativeInt).ToPointer()
    let stackMemory = new Span<byte>(voidPtr, 256)
    // Do some stuff with the span!
    ()
```

And yes, the inferred type of voidPtr is nativeptr<unit> even though you are forbidden from declaring it as such.

**Comment by realvictorprm** [comment]
@poizan42 Thanks, I didn't know about that trick!
