### ISSUE TITLE
Test failures: System.Net.Http.Functional.Tests.DiagnosticsTest / *

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#26042]
## Types of failures

Affected tests:

* System.Net.Http.Functional.Tests.DiagnosticsTest:
  * SendAsync_ExpectedDiagnosticSourceLogging
  * SendAsync_ExpectedDiagnosticSourceNewAndDeprecatedEventsLogging
  * SendAsync_ExpectedDiagnosticSourceUrlFilteredActivityLogging
  * SendAsync_ExpectedDiagnosticStopOnlyActivityLogging
* System.Net.Http.Functional.Tests.HttpClientHandler_DefaultProxyCredentials_Test:
  * ProxySetViaEnvironmentVariable_DefaultProxyCredentialsUsed

Test `SendAsync_ExpectedDiagnosticStopOnlyActivityLogging`
```
Exit code was 139 but it should have been 42
Expected: True
Actual:   False
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() in /root/corefx-1192569/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 203
at System.Net.Http.Functional.Tests.DiagnosticsTest.SendAsync_ExpectedDiagnosticStopOnlyActivityLogging() in /root/corefx-1192569/src/System.Net.Http/tests/FunctionalTests/DiagnosticsTests.cs:line 583
```

## History of failures

Day | Build | OS | Test
-- | -- | -- | --
5/31 | 20170531.01 | Ubuntu16.04 | SendAsync_ExpectedDiagnosticSourceLogging
7/8 | 20170708.04 | Suse42.2 | [ManagedHandler] SendAsync_ExpectedDiagnosticSourceNewAndDeprecatedEventsLogging
8/1 | 20170801.01 | Ubuntu17.04 | SendAsync_ExpectedDiagnosticSourceUrlFilteredActivityLogging
8/19 | 20170819.02 | Ubuntu17.04 | [ManagedHandler] SendAsync_ExpectedDiagnosticSourceNewAndDeprecatedEventsLogging
8/22 | 20170822.01 | Centos73 | [ManagedHandler] SendAsync_ExpectedDiagnosticSourceUrlFilteredActivityLogging
8/23 | 20170823.07 | Ubuntu17.04 | [ManagedHandler] SendAsync_ExpectedDiagnosticSourceNewAndDeprecatedEventsLogging
8/27 | 20170827.01 | Centos73 | [ManagedHandler] SendAsync_ExpectedDiagnosticSourceNewAndDeprecatedEventsLogging
9/25 | 20170925.03 | Ubuntu17.04 | [ManagedHandler] SendAsync_ExpectedDiagnosticSourceUrlFilteredActivityLogging
9/26 | 20170926.06 | RedHat72 | [ManagedHandler] SendAsync_ExpectedDiagnosticSourceLogging
9/26 | 20170926.06 | RedHat72 | [ManagedHandler] SendAsync_ExpectedDiagnosticSourceNewAndDeprecatedEventsLogging
10/1 | 20171001.01 | RedHat72 | [ManagedHandler] ProxySetViaEnvironmentVariable_DefaultProxyCredentialsUsed
10/26 | 20171026.01 | Suse42.2 | ProxySetViaEnvironmentVariable_DefaultProxyCredentialsUsed
11/18 | 20171118.03 | Ubuntu17.10 | SendAsync_ExpectedDiagnosticSourceLogging
11/27 | 20171127.01 | Ubuntu16.04 | SendAsync_ExpectedDiagnosticSourceNewAndDeprecatedEventsLogging
12/4 | 20171204.02 | Ubuntu17.04 | SendAsync_ExpectedDiagnosticStopOnlyActivityLogging
12/23 | 20171223.03 | Ubuntu17.04 | SendAsync_ExpectedDiagnosticSourceNewAndDeprecatedEventsLogging
1/12 | 20180112.01| Ubuntu14.04 | SendAsync_ExpectedDiagnosticStopOnlyActivityLogging - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180112.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.DiagnosticsTest~2FSendAsync_ExpectedDiagnosticStopOnlyActivityLogging)
1/19 | 20180119.01 | Suse42.4 | ProxySetViaEnvironmentVariable_DefaultProxyCredentialsUsed - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180119.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandler_DefaultProxyCredentials_Test~2FProxySetViaEnvironmentVariable_DefaultProxyCredentialsUsed(useProxy:%20False))
3/31 | 20180331.02 | Ubuntu16.04 | SendAsync_ExpectedDiagnosticSourceLogging
3/31 | 20180331.05 | OpenSuse42.3 | SendAsync_ExpectedDiagnosticSourceLogging

Note: Related to:
* Some failures in #23209
* ManagedHandler failures in #23771

**Comment by karelz** [comment]
Analysis from @vancem in duplicate bug: https://github.com/dotnet/corefx/issues/24807#issuecomment-348545336

> I am assuming that this is a non-deterministic (and rare) error.  Please correct me if I am wrong. 
> Looking at the error detail
```
2:14:30   xUnit.net console test runner (64-bit .NET Core)
12:14:30   Copyright (C) 2014 Outercurve Foundation.
12:14:30   
12:14:30   Discovering: System.Net.Mail.Functional.Tests
12:14:31   Discovered:  System.Net.Mail.Functional.Tests
12:14:31   Starting:    System.Net.Mail.Functional.Tests
12:14:32 
  A fatal error occurred, the required library libhostfxr.dylib could not be found at /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_release/bin/testhost/netcoreapp-OSX-Release-x64/shared/Microsoft.NETCore.App/9.9.9/
12:14:33 
     System.Net.Mail.Tests.LoggingTest.EventSource_EventsRaisedAsExpected [FAIL]
12:14:33         Exit code was 131 but it should have been 42
12:14:33         Expected: True
12:14:33         Actual:   False
12:14:33         Stack Trace:
12:14:33            /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_release/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs(203,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
12:14:35   Finished:    System.Net.Mail.Functional.Tests
```
> This seems to be some sort loader issue with libhostfxr.dylib  which I am guessing is something to do with the test host.   
> We probably need to bring in some expertise with this DLL and how it is deployed.   It seems to have little to do with the actual code being tested.

**Comment by davidsh** [comment]
These tests have been active for a while now and no failures reported.
