### ISSUE TITLE
run-test.sh deploys WP8 dataflow if present, fails ETW test

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#2604]
On my machine (might have different behavior based on file system order), running with System.Threading.Tasks.Dataflow and System.Threading.Tasks.Dataflow.WP8 dlls in the corefx bin path, the test overlay gets the WP8 build, which doesn't have FEATURE_TRACING and the ETW test fails

**Comment by nguerrera** [comment]
Can we get rid of the WP8 specifc build and make vNext of dataflow drop support for WP8?

**Comment by stephentoub** [comment]
cc: @weshaggard

**Comment by weshaggard** [comment]
I don't know the exact implications of why this was done so I don't have a particular opinion. In general I'm in favor of eliminating forks of the libraries if it is possible.

**Comment by nguerrera** [comment]
Fixed by #3585.
