### ISSUE TITLE
Tests under "System.Text.RegularExpressions.Tests" failed with "Exit code was 131 but it should have been 42"

### ISSUE THREAD

**Issue by Sunny-pu** [dotnet/corefx#26055]
failed test: RegexMatchTests.Match_SpecialUnicodeCharacters_Invariant
Configuration: oxs10.12_release
Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release/lastCompletedBuild/testReport/System.Text.RegularExpressions.Tests/RegexMatchTests/Match_SpecialUnicodeCharacters_Invariant/
MESSAGE:
Exit code was 131 but it should have been 42\nExpected: True\nActual: False
~~~~~~
STACK TRACE:
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 186

**Comment by Sunny-pu** [comment]
Failed tests:
Match_SpecialUnicodeCharacters_Invariant
Match_SpecialUnicodeCharacters_enUS
GroupsBasic
GroupsTurkish
GroupsAzeriLatin
GroupsDanish
GroupsEnUS
GroupsCzech

**Comment by danmosemsft** [comment]
This is not actionable without local repro at least until OSX dumps are fixed.
