### ISSUE TITLE
run-test.sh should delete mscorlib.ni.dll

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#2605]
run-test.sh needs to delete mscorlib.ni.dll if it was obtained from nuget as that native image is platform specific and the CLR will fail to start up with it present on Linux/OS X.

**Comment by weshaggard** [comment]
As opposed to deleting it shouldn't we simply stop copying it for x-plat test runs? At some point soon hopefully we will have x-plat libraries in our packages and we will just need to copy the right set based on the platform.

**Comment by nguerrera** [comment]
Right now run-test.sh is designed to clobber things from Windows. As long as we're using it, it should make sure to clobber the ni.dll too. Eventually, I expect us not to need run-test.sh or to have a drastically simpler version of it, in which case this is moot. This is more about a missing step in the current workaround.

**Comment by ellismg** [comment]
IIRC, The way this is handled now is that when Jenkins copies tests over to the test machine, it ignores all .ni.dll assemblies.

I would also prefer a model Nick proposes, given more folks are starting to run run-test.sh "by hand".
