### ISSUE TITLE
Provide ImmutableSortedSetArray<T> an ImmutableSortedSet based on array not on tree

### ISSUE THREAD

**Issue by fabricefou** [dotnet/corefx#26058]
# Rational

ImmutableSortedSet<T> is based on an AVL Tree also:
* property Item[Int32] has compexity in O(Log(N))
* We can't have an "equivalent" ImmutableArray without make a copy

In the ImmutableCollections framework, we already have the same type of choice for our data structures.
I think to the distinction between ImmutableArray<T> vs ImmutableList<T> (based on tree data structure)

With this structure we could have:
* property Item[Int32] with O(1) complexity
* We can have an property ToImmutable without any copy make (call of the internal ImmutableArray constructor).

# Usage

Very ofen we want to have the garanty (by type) than the incomming Array T[] is sorted to call safely BinarySearch. Of course we could used the ImmutableSortedSet<T> but this structure isn't efficient when working with indexes.

Another use case come when we have to rely on native API (eg Interpolation API) when we want a sorted Array double* in input. With an ImmutableSortedSetArray<double> we can without copy have an double* via a Span-based API or some other magic trick.

Could you provide an ImmutableSortedSet based on a Array ?

**Comment by sharwell** [comment]
:memo: Several of the use cases for this would be mitigated by #1502.

**Comment by safern** [comment]
After discussing this with @ianhays we think that it is not valuable adding a new API which would be a copy of an existing API but with a different implementation. First of all this would confuse costumers, second of all any one could implement this by using our interfaces. So we really think that what is suggested here is to change the implementation to have a better performance, something like proposed in #1502.

**Comment by fabricefou** [comment]
Thanks for the answer 😀. But with this kind of thought we'd never have had the 2 distincts implementations ImmutableArray<T> and ImmutableList<T>. Both implement the same contract. I think we would never have one single implementation efficient for all use case (building and reading). Another example is the existence of SortedDictionary<Key, Value> and SortedList<Key, Value>, two distinct implementations with equivalent contract but with different performance trade off. I really think you will help your consumers by adding this kind of implementations.
