### ISSUE TITLE
Setting HttpWebRequest.ContentLength throws exception with incorrect message

### ISSUE THREAD

**Issue by diamondo25** [dotnet/corefx#26060]
https://github.com/dotnet/corefx/blob/master/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs#L239-L259

As you can see, it uses the `net_io_timeout_use_ge_zero` (Timeout can be only be set to 'System.Threading.Timeout.Infinite' or a value >= 0.) message, while it should have its own message.

**Comment by karelz** [comment]
Looks like copy-paste bug. Do you want to check if there is appropriate existing resource we could use?
Are you interested in submitting a PR for the change?
