### ISSUE TITLE
DbConnectionPool shouldn't capture AsyncLocals into its Timer

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#26064]
Causing those AsyncLocal values to live forever

As seen in https://github.com/dotnet/corefx/issues/25477#issuecomment-346866897

For ASP.NET Core can capture logging scope, HttpContext, ConcurrentBag items, Authentication (example https://github.com/dotnet/corefx/issues/25477#issuecomment-346866897); other state etc

**Comment by divega** [comment]
The namespace and type names are misleading. This type is actually internal and hence each provider that was originally in System.Data.dll got a copy.

Assuming this is about SqlClient I have updated the area. However I see above that PRs for both ODBC and SqlClient have been merged. @benaadams is it possible that this is already fixed and should be closed?

**Comment by benaadams** [comment]
>  is it possible that this is already fixed and should be closed?

Yep
