### ISSUE TITLE
ManagedWebSocket.ReceiveAsyncPrivate: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by niemyjski** [dotnet/corefx#26078]
Running on ASP.NET Core 2.0.3 under IIS.

I'm not sure of the exact repo that's causing this but I'm seeing a few hundred of these exceptions and figured I'd report it :).. I can link to the code that calls receive if required..

```
System.OperationCanceledException: Aborted
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__61.MoveNext() at offset 276
--- End of inner exception stack trace ---
at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__61.MoveNext() at offset 1611
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at offset 12
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task) at offset 68
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task) at offset 40
```

```cs

        private async Task Receive(WebSocket socket, Action<WebSocketReceiveResult, string> handleMessage) {
            var buffer = new ArraySegment<byte>(new byte[1024 * 4]);
            var result = await socket.ReceiveAsync(buffer, CancellationToken.None);
//....
        }
```

**Comment by karelz** [comment]
@niemyjski is it something unique to 2.0.3 vs. 2.0.0?

@Priya91 can you please take a look if the information above is sufficient?

**Comment by niemyjski** [comment]
I’m not sure, I just ported the app from asp.net legacy and chose the latest meta package

**Comment by Priya91** [comment]
@niemyjski Can you provide a small concise repro? The stack just reports the outcome, and doesn't provide any useful diagnostic information to chase down the issue. Since you mention IIS, is it happening only on windows?

**Comment by niemyjski** [comment]
@PriyaPurkayastha I don't have a small concise repo as I have no idea how it's being triggered besides I'm getting hundreds of these running in azure websites with the following code: https://github.com/exceptionless/Exceptionless/tree/master/src/Exceptionless.Api/Hubs

**Comment by Priya91** [comment]
@niemyjski Can you provide more information on the runtime environment, which OS, which version of .NET, etc.

**Comment by niemyjski** [comment]
Microsoft Azure Web Apps, ASP.NET Core 2.0.3 (Code in repo is exactly the code I'm running, can also attach ci artifacts that get deployed). Wish I had more info on how this is triggered. Would be awesome if pdb's could also be deployed :)

**Comment by Priya91** [comment]
@niemyjski There's a lot of variables here, so again it would be great if you can provide a small repro.

Also, are you able to repro this issue outside of azure web apps? Can you try this on a separate vm and see if this happens under the same load? The stack shows operation cancelled because it got aborted, maybe the other end aborted or the azure web apps service aborted connections and this object got disposed when you used it?

cc @stephentoub (who wrote this protocol from scratch) Does the stack look familiar to any scenario you've seen before from ManagedWebSockets?

**Comment by stephentoub** [comment]
Seems like the websocket is being used after/while it's already been closed or canceled or aborted?

**Comment by niemyjski** [comment]
Yeah, I agree I wonder if it's possible to trigger this if you kill the server, fire up a few browser instances which are retrying with a timeout of 1 second and then start up the server as sockets will try to connect / be abandoned.  Are there tests for scenarios like this? @Priya91 I'll try and get a smaller sample but I'm super super busy 25/7 like everyone in this thread :\

**Comment by stephentoub** [comment]
If that's how it's triggered then it makes sense you'd get such an OperationCanceledException.

**Comment by n9** [comment]
@Priya91 See https://github.com/aspnet/Home/issues/2910, to get more information. Maybe check whether `_receiveBuffer` is null will be sufficient there.

**Comment by karelz** [comment]
@n9 are you interested in submitting a PR with a fix?

**Comment by n9** [comment]
Could @stephentoub or someone else confirm that adding the check is the right way to fix?

**Comment by n9** [comment]
Moreover, I am using `System.Net.WebSockets.ManagedWebSocket` from `Microsoft.AspNetCore.WebSockets.dll` (v2.0.1 -- the latest version available). 

There is the following comment: `// NOTE: This file is shared between CoreFX and ASP.NET.  Be very thoughtful when changing it.`

And here https://github.com/aspnet/WebSockets/tree/2.0.1/src/Microsoft.AspNetCore.WebSockets/Internal/fx is written:

> This is code copied out of dotnet/corefx. Do not modify anything under the src subdirectory as it is copied by scripts\UpdateCoreFxCore.ps1 in this repo. The files in the root of this directory are only here to shim out code that the corefx code depends on.

> Any changes to code under src in this directory MUST be made in dotnet/corefx as well and should mention Tratcher, anurse and stephentoub.

Where the fix should go?

**Comment by stephentoub** [comment]
> Could @stephentoub or someone else confirm that adding the check is the right way to fix?

This code has changed for .NET Core 2.1.  It used to be byte[] that was rented from a pool and then nulled out and returned when the websocket was disposed.  Now it's a `Memory<T>` that's either provided by the caller or allocated fresh, and it's not nulled out.  The previously mentioned issue of a NullReferenceException when using the websocket after it's been disposed/canceled should no longer be possible.

> And here https://github.com/aspnet/WebSockets/tree/2.0.1/src/Microsoft.AspNetCore.WebSockets/Internal/fx is written:

In ASP.NET 2.0, it was implementing websockets with a copy-and-paste of the ManagedWebSocket.cs that was in corefx.  In 2.1, the implementation from corefx is exposed out of a library, which ASP.NET depends on, and thus ASP.NET no longer maintains it's own copy of the code.

**Comment by n9** [comment]
So, https://github.com/aspnet/Home/issues/2910 is actually fixed in 2.1?

**Comment by stephentoub** [comment]
> So, aspnet/Home#2910 is actually fixed in 2.1?

It's possible the same scenario manifests a different error, but that specific error should no longer be possible.  That error is complaining about dereferencing a null byte array, and there is no longer a byte array being nulled out or dereferenced.

**Comment by n9** [comment]
Ok, the problem, that the function is still running even if the web socket was aborted by client, might need to be solved.

**Comment by karelz** [comment]
@n9 can you please try with 2.1 Preview1 (just released this week). If you can confirm, it does not throw NullReferenceException, we can close the issue.

Not sure what you meant by your last comment - if there are other concerns, I would suggest to file a separate bug and describe the problem. Thanks!

**Comment by TheBoneJarmer** [comment]
Hi, I have the same issue as well. It happens to me when I try to push out a lot of sends and receives at the same time. How can I download the preview? I would like to test this as well.

**Comment by stephentoub** [comment]
> It happens to me when I try to push out a lot of sends and receives at the same time.

You mean, for example, that you issue a receive without making sure that the previous receive had completed? That's not supported. It's only valid to have at most one send and one receive at a time.

**Comment by TheBoneJarmer** [comment]
I see, thanks. If it so happens that more receives or sends happen at the same time, could that result in an 'Aborted' error?

**Comment by stephentoub** [comment]
Yes

**Comment by TheBoneJarmer** [comment]
And what would be the best method to prevent it? I was thinking instead of async receive calls a sync receive calls but that does not exist.

**Comment by stephentoub** [comment]
> And what would be the best method to prevent it?

You have a few options:
1. Ensure it by construction, i.e. simply by how your code is arranged you serialize sends and serialize receives.
2. Use a synchronization construct like SemaphoreSlim, e.g. create one for sends and one for receives, set its count to 1, await its WaitAsync prior to an operation and release it after the operation.
3. Store the Task you get back from the previous send/receive and await that prior to the next one.  In 2.1, WebSocket also exposes ValueTask returning overloads; with those, you could do the same thing, but you'd first want to call the Preserve() method (also new in 2.1) prior to storing it.

**Comment by alekkowalczyk** [comment]
Same question here, I'm getting this exception randomly on what looks like heavier load of my websockets, how can I prevent it?

**Comment by davidsh** [comment]
There doesn't seem to be anything actionable that needs fixing in .NET Core 2.1+.  Closing.
