### ISSUE TITLE
Add WebAssembly CoreFX build architecture

### ISSUE THREAD

**Issue by morganbr** [dotnet/corefx#26107]
As the [CoreRT](https://github.com/dotnet/corert/issues/4659) and [Mono](http://www.mono-project.com/news/2017/08/09/hello-webassembly/) WebAssembly experiments progress, we'll want to start running CoreFX libraries (starting with System.Console). As a first step, we need to add a new build architecture in the CoreFX repo that can produce architecture-specific packages.

This should allow running ```build wasm``` similarly to ```build x86```. To match the CoreRT repo, the build flavor should set ```OSGroup``` to ```WebAssembly``` and ```Platform``` to ```wasm```. In general, settings should match Unix outputs as the WebAssembly platform is pretty similar (but it should be possible to run the build on Windows).

For examples, https://github.com/dotnet/corert/commit/da8c27da9644cd658b906cfbd0f6c9997d91c355 added the flavor in CoreRT, https://github.com/dotnet/corert/commit/15ce20d82918bb04009a30e3dbcebce85b1dd80e rounded out native compilation for it, and  https://github.com/dotnet/corert/commit/3d25db5b1c010346bbc480a20646c80ea413492f fixed issues in it.

**Comment by karelz** [comment]
> allow running build wasm similarly to build x86. To match the CoreRT repo, the build flavor should set OSGroup to WebAssembly and Platform to wasm. In general, settings should match Unix outputs as the WebAssembly platform is pretty similar (but it should be possible to run

a
