### ISSUE TITLE
[Windows] PictureBox Control does not consider and honor Alpha Channels correctly.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/corefx#26101]
Earlier today I filed an ticket with Microsoft for this exact issue on VS2017 for their .NET Framework's 4.5.x, 4.6.x, and 4.7.x

Basically if you got an PNG image with an alpha channel, which has an partially transparent glow, or shadow on it.

Basically the following steps can be taken to reproduce this (reporting this here as well for .NET Core can have this fixed as well if desired):

1. make a new forms project
2. make a new form, frame style set to None, Transparent Color set to Control
3. add an PictureBox and make it the same size of the control and make the background color to transparent.
4. set that PictureBox to that image.
5. Compile and run, you will see the image's transparency on partially transparent pixels get tossed (unless it is an .NET Framework specific thing or me using the wrong control for the RGBA images of mine).

**Comment by jnm2** [comment]
.NET Core doesn't have PictureBox or any of Windows.Forms.

**Comment by karelz** [comment]
The latest best way to report .NET Framework issues is via https://developercommunity.visualstudio.com or VS Feedback.
Closing here, as it does not impact .NET Core.
