### ISSUE TITLE
"Function not Implemented" on FileInfo.MoveTo() when source and destination File System are both exFAT

### ISSUE THREAD

**Issue by markekraus** [dotnet/corefx#26105]
`FileInfo.MoveTo()` produces a `System.IO.IOException` excepetion with the `Function not implemented` method when the source file and destination file are both on an exFAT partition.

Repro Program.cs code: 

```csharp
using System;
using System.IO;

namespace ExFATRepro
{
    class Program
    {
        static void Main(string[] args)
        {
            FileInfo file = new FileInfo(args[0]);
            file.MoveTo(args[1]);
        }
    }
}

```

Prep:

```bash
dd if=/dev/zero of=~/testfs count=40960
mkfs.exfat ~/testfs
sudo mkdir /mnt/testfs
sudo mount ~/testfs /mnt/testfs
echo test > /mnt/testfs/testfile
```

Repro actions:

```bash
sudo dotnet run /mnt/testfs/testfile /mnt/testfs/testfile2
```

Result:

```none
Unhandled Exception: System.IO.IOException: Function not implemented
   at System.IO.UnixFileSystem.MoveFile(String sourceFullPath, String destFullPath)
   at System.IO.FileInfo.MoveTo(String destFileName)
   at ExFATRepro.Program.Main(String[] args) in /home/mark/github/ExFATRepro/Program.cs:line 11
```

Additional testing shows that if the source or destination is on another FS it works. for example, 

```bash
echo test > /tmp/testfile
sudo dotnet run /tmp/testfile /mnt/testfs/testfile2
sudo dotnet run /mnt/testfs/testfile2 /tmp/testfile
```

That works without issue.

**Comment by danmosemsft** [comment]
Thanks for the great bug report. Any interest in debugging a little?

**Comment by markekraus** [comment]
@danmosemsft I'm actually reporting this for someone else who discovered it. 

@matthew-macgregor Would you be able to work through some debugging on this?

**Comment by stephentoub** [comment]
My guess is that this link call is returning ENOSYS:
https://github.com/dotnet/corefx/blob/31427a32991617c3b918fadcb4fa0a39ba8fc50a/src/System.IO.FileSystem/src/System/IO/UnixFileSystem.cs#L94
(even though the man page doesn't list that as a possible error), and we need to add another condition for it to the fallback here:
https://github.com/dotnet/corefx/blob/31427a32991617c3b918fadcb4fa0a39ba8fc50a/src/System.IO.FileSystem/src/System/IO/UnixFileSystem.cs#L104

**Comment by matthew-macgregor** [comment]
@markekraus @danmosemsft Yes, absolutely willing to help debug the issue.

**Comment by matthew-macgregor** [comment]
@danmosemsft I set up a dev environment and built corefx with the change you suggested. This does appear to resolve the issue.

**Comment by danmosemsft** [comment]
It was @stephentoub who made that suggestion actually. Great! Do you want to throw up a PR?

Incidentally the [one other place we use Link,](https://github.com/dotnet/corefx/blob/31427a32991617c3b918fadcb4fa0a39ba8fc50a/src/System.IO.FileSystem/src/System/IO/UnixFileSystem.cs#L52) we don't fall back to a copy like we do there.

**Comment by danmosemsft** [comment]
@matthew-macgregor just following up as we will be closing down 2.1 soon. Is it possible for you to throw up a PR? Even if it's rough.
