### ISSUE TITLE
Utf8Parser/Utf8Formatter: no string overloads

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#26104]
Why don't `Utf8Parser` and `Utf8Formatter` have `string` overloads?

https://github.com/dotnet/corefx/blob/270be00f569abea3b4b7fb6e0191130e50b17ecf/src/System.Memory/ref/System.Memory.cs#L396-L441

**Comment by mikedn** [comment]
What should the string overloads do? Strings are UTF-16 so it would be kind of strange to deal with strings in a UTF-8 formatter/parser.

**Comment by tmds** [comment]
> What should the string overloads do? Strings are UTF-16 so it would be kind of strange to deal with strings in a UTF-8 formatter/parser.

This provides a conversion mechanism between two common representations of text: `string` and UTF8 encoded `Span<byte>`.

**Comment by davidfowl** [comment]
I think it makes sense to go string -> utf8 byte[] so TryFormat not so much TryParse.. Also would be overlap with any `UTF8Encoding.GetBytes()` method

Any thoughts @KrzysztofCwalina ?

**Comment by tmds** [comment]
TryParse also has its use-cases. e.g. parsing a string from a UDP packet/memory mapped file.

**Comment by davidfowl** [comment]
@tmds That would be odd to put on the Utf8Parser class no? If you're parsing UTF16 text?

**Comment by tmds** [comment]
I'm parsing utf8 into a string instance.

**Comment by ahsonkhan** [comment]
> I'm parsing utf8 into a string instance.


That sounds more like encoding, i.e. utf-8 to utf-16.

Are you looking for something like this?
https://github.com/dotnet/corefxlab/blob/master/src/System.Text.Primitives/System/Text/Encoders/Utf8.cs#L41
```C#
public static OperationStatus FromUtf16(ReadOnlySpan<byte> source, Span<byte> destination, out int bytesConsumed, out int bytesWritten)
```

**Comment by tmds** [comment]
This is the method on the utf8 class:
```
public static string ToString(ReadOnlySpan<byte> utf8Bytes)
```

**Comment by ahsonkhan** [comment]
> This is the method on the utf8 class:

To clarify, would you expect the ToString method to perform the following transformations in sequence?

string ToString(ReadOnlySpan<byte> utf8Bytes)
   1. convert utf8Bytes to utf16Bytes
   2. convert utf16 byte span to byte array
   3. Use existing Encoding.GetString to convert byte array to string

One we finalize the shape of the APIs in the utf8 class (which provides utf8 -> utf16), all the pieces would be available for anyone to implement such a ToString method, if necessary. Is there enough value to provide such an API on the class itself, especially since it implies allocation?

**Comment by tmds** [comment]
> would you expect the ToString method to perform the following transformations in sequence, broadly speaking?

I'd expect the `Utf8Parser.TryParse(ReadOnlySpan<byte> text, out string value, ...)` to parse the UTF-8 bytes in `text` and return them in `value` and return `true` on success. In case text is an invalid UTF8 sequence I'd expect a `value` to be `null` and the method to return `false`.
I don't have suggestions on the implementation other than it should minimize allocations and maximize performance 😄.

As you say, this can be implemented using the UTF8 methods. If we consider adding `Utf8Formatter.TryFormat(string value, ...)`, for consistency, we should consider to add the `Utf8Parser.TryParse` too.

**Comment by KrzysztofCwalina** [comment]
I don't think string overload makes sense on Utf8Formatter. First it's not really formatting, and so the StandardFormat parameter does not make much sense. Secondly, strings are variable length, and so I think a Try API is a bit of pit of failure. I think much better low level API for string encoding would be similar to the Base64 encoder which allows callers to do partial encoding (when output buffer is too small) and then keep going after providing more output buffer space. 

@GrabYourPitchforks is working on such encoding APIs.

When we have both the Utf8Formatter and low level encoding APIs, it should all come together in a perfromant and usable "writer" APIs, similar to the [BufferWriter](https://github.com/dotnet/corefxlab/blob/master/src/System.Azure.Experimental/System/Azure/CosmosDbAuthorizationHeader.cs#L29).

**Comment by tmds** [comment]
> I don't think string overload makes sense on Utf8Formatter. First it's not really formatting, and so the StandardFormat parameter does not make much sense.

Agree

> Secondly, strings are variable length, and so I think a Try API is a bit of pit of failure.

In some use-cases you'll have all bytes available in a continuous range, and then a Try api is meaningful.
Using the Try-method when data isn't contiguous is indeed asking for trouble, so not providing this method is probably the best. It should be easy enough to DIY it when needed.

> @GrabYourPitchforks is working on such encoding APIs.
When we have both the Utf8Formatter and low level encoding APIs, it should all come together in a perfromant and usable "writer" APIs, similar to the BufferWriter.

Great! Is there an open issue for this?

The `UTF8` class still has some TODOs. Especially the one in `public static string ToString(ReadOnlySpan<byte> utf8Bytes)` caught my attention:
```
return String.Empty; // TODO: is this what we want to do if Bytes are invalid UTF8? Can Bytes be invalid UTF8?
```
I haven't found an issue for cleaning these out.

A question related to packaging. A lot of the bits are in the `System.Memory` package which is usable from `netstandard1.1+`. I guess methods on the `UTF8` class will only be available on `netcoreapp2.1+`?

**Comment by KrzysztofCwalina** [comment]
> A question related to packaging. A lot of the bits are in the System.Memory package which is usable from netstandard1.1+. I guess methods on the UTF8 class will only be available on netcoreapp2.1+?

+ @terrajobst, @tarekgh, @joshfree 

If we add the APIs directly to Encodings.UTF8 they would be NS2.1+. I don't think it's acceptable. We need these APIs to implement [BufferWriter](https://github.com/dotnet/corefxlab/tree/master/src/System.Buffers.Experimental/System/Buffers/Text). Having said that, the Encoding would probably be the best place to have these APIs on in the absence of the constraint.

**Comment by tmds** [comment]
@KrzysztofCwalina is ns2.1+ still required for working with UTF8 in Span<byte>?
I'm fine with closing this issue.

**Comment by KrzysztofCwalina** [comment]
NS2.1 is currently not required. In fact, NS2.1 does not exist.

**Comment by KrzysztofCwalina** [comment]
https://github.com/dotnet/corefx/blob/master/src/System.Memory/pkg/System.Memory.pkgproj

**Comment by tmds** [comment]
I hadn't noticed the utf8 functions in there. Thanks.

**Comment by GeorgeTsiokos** [comment]
It was stated previously, but you're looking for these new overloads on `Encoding`. I've added the signatures here to make it obvious to anyone looking for the same (as I was):
```c#
namespace System.Text
{
  public abstract class Encoding {
    public virtual int GetBytes(ReadOnlySpan<char> chars, Span<byte> bytes);
    public string GetString(ReadOnlySpan<byte> bytes);
  }
}
```
_You can specify a string on the `GetBytes` call and it will implicitly cast to `ReadOnlySpan<char>`._

https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Text/Encoding.cs#L896
https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Text/Encoding.cs#L1088
