### ISSUE TITLE
Drawing.Common issue on macOS High Sierra

### ISSUE THREAD

**Issue by bgulanowski** [dotnet/corefx#26103]
After much trial and error, I believe I installed/configured/referenced the correct packages/references successfully. (The language around packages/references is not well explained in docs on Microsoft's website.)

I can build and run a .Net Core CLI app, from Visual Studio for Mac, but it freezes when it tries to access objects from the Drawing.Common package.

I can't create a Bitmap or a Colour. Test code, take right from documentation:

```c#
using System;
using System.IO;
using System.Drawing;

namespace Test {
    class MainClass {
        public static void Main(string[] args) {

            //Bitmap bm = new Bitmap(32, 32);
            //Console.WriteLine("Bitmap: {0}", bm);

            Color slateBlue = Color.FromName("SlateBlue");
            byte g = slateBlue.G;
            byte b = slateBlue.B;
            byte r = slateBlue.R;
            byte a = slateBlue.A;
            string text = String.Format("Slate Blue has these ARGB values: Alpha:{0}, " +
                "red:{1}, green: {2}, blue {3}", new object[] { a, r, g, b });
            Console.WriteLine(text);

            Console.WriteLine("done");
        }
    }
}
```

The app freezes at `Color.FromName()`.

Overall, this was surprisingly confusing for someone coming from a native macOS/iOS background. I was slowed down a lot because I missed a few small but important details:

1. The packages are pre-release, so they don't appear in Visual Studio package UI unless "show pre-release" is checked. Would be great if that was called out better.
2. The previous Drawing package (CoreCompat.System.Drawing) is not marked "deprecated", although I had the same problem with both.
3. The dependency between CoreCompat.System.Drawing, runtime.osx.10.10-64.CoreCompat.System.Drawing, and libgdiplus (or mono-libgdiplus) is not well explained anywhere that I could find.
4. The name overloading for "System.Drawing" in .Net Core and .Net 4.7 is confusing. (How can two different packages have the same namespace?)

First I installed a plain version of `libgdiplus`, then I tried `mono-libgdiplus`, but that had no impact on the freezing problem.

I'm wondering if there is an issue with High Sierra or some other macOS problem where trying to access graphic functionality from a CLI tool is the problem. Possibly not linked to AppKit/CoreGraphics?

[EDIT] Add C# syntax highlighting by @karelz

**Comment by bgulanowski** [comment]
As a test, I created a Mac (Xamarin) app from the template and added the same code to create and use a `Color`  object. The app froze in the same way.

I looked into the macOS Console app but there was nothing relevant.

**Comment by danmosemsft** [comment]
Thanks for the report. Can you get managed and native call stacks for the hang?

**Comment by qmfrederik** [comment]
@bgulanowski The CoreCompat.* packages are packages which I maintain; but they are not official packages. The best way forward is to use System.Drawing.Common.

To your point 2 and 3, there's a deprecation notice at the top of the README at https://github.com/corecompat/corecompat and a note detailing that you can either use homebrew or the runtime.osx.10.10-x64.CoreCompat.System.Drawing NuGet package.

mono-libgdiplus is the Homebrew package you want to use on macOS. As @danmosemsft points out, can you please get managed & native call stacks? That would give us a better idea of what's going on.

**Comment by safern** [comment]
@bgulanowski any update on the managed & native call stack? That would help us to track the issue.

**Comment by danmosemsft** [comment]
OK, thanks @bgulanowski .

**Comment by InCrIpTiOn** [comment]
Any update on this issue? Still having problem creating a new bitmap object in Mojave 10.14.5.

**Comment by qmfrederik** [comment]
@InCrIpTiOn If you're  having issues creating a new bitmap object on Mojave 10.14.5, I think your best bet is to open a new issue with detailed steps about what you're trying to do (e.g. some sample code) and the error you are seeing.
