### ISSUE TITLE
How to test WinRT types and dynamic?

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#26128]
Of the uncovered code in Microsoft.CSharp, quite a bit involves WinRT types, which I don't know anything about. Does anyone know how to go about testing these?

(@jamesqo do I remember you having a question about WinRT types and corefx on stackoverflow, or am I was that someone else?)

**Comment by jamesqo** [comment]
@JonHanna I don't think I can be of help here, sorry.

**Comment by jkotas** [comment]
WinRT is not supported in .NET Core currently. It is tracked by #22789 and a few other issues.

WinRT is supported on UAP. It should be possible to test WinRT-specific functionality via UAP-specific tests.

**Comment by JonHanna** [comment]
@jkotas are there any tests that use WinRT types against corefx already, do you know?

**Comment by jkotas** [comment]
These tests should be using WinRT - you can tell by looking for `<Reference Include="Windows" />` in .csproj file:

```
\corefx\src\CoreFx.Private.TestUtilities\src\CoreFx.Private.TestUtilities.csproj(109):    <Reference Include="Windows" />
\corefx\src\System.IO.FileSystem\tests\System.IO.FileSystem.Tests.csproj(179):    <Reference Include="Windows" />
\corefx\src\System.IO.IsolatedStorage\tests\System.IO.IsolatedStorage.Tests.csproj(81):    <Reference Include="Windows" />
\corefx\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.Tests.csproj(125):    <Reference Include="Windows" />
\corefx\src\System.Runtime.WindowsRuntime\tests\System.Runtime.WindowsRuntime.Tests.csproj(25):    <Reference Include="Windows" />
```

**Comment by JonHanna** [comment]
Thanks, that should be enough to get over the initial hurdle of total newbieness.
