### ISSUE TITLE
Productize ReadOnlyBuffer

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefx#26131]
The prototype is at 
https://github.com/dotnet/corefxlab/blob/master/src/System.Buffers.Primitives/System/Buffers/ReadOnlyBuffer.cs

**Comment by joshfree** [comment]
@muratg

**Comment by ahsonkhan** [comment]
Estimating to 15 days based on conversation with @pakrym

**Comment by karelz** [comment]
@KrzysztofCwalina says it is just tracking work item, that the API has been reviewed in other issues - @ahsonkhan can you please link the API review issue?

**Comment by ahsonkhan** [comment]
I don't know if there is an issue. The API review is available here:
https://www.youtube.com/watch?v=tLnQsNTfl9Q&

**Comment by KrzysztofCwalina** [comment]
This workitem has been completed. ReadOnlySequence<T> is now merged into corefx (System.Memory package).
