### ISSUE TITLE
System.Data.SqlClient needs to update version

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#26142]
As part of https://github.com/dotnet/corefx/pull/25142 new API was added to the assembly which mean we need to bump the minor assembly version the PR only updated the patch version from 4.3.0 to 4.3.1 (see comment https://github.com/dotnet/corefx/pull/25142#discussion_r156465074). We should update assembly version to 4.4.0.

Given this library currently ships inbox for UAP we need to start shipping a build of this in the nuget package so it can correctly override what is shipped inbox for UAP otherwise folks trying to consume the new APIs and run on UAP will fail to run on the one currently inbox. (see comment https://github.com/dotnet/corefx/pull/25142#discussion_r156465352), see also issue https://github.com/dotnet/corefx/issues/23743 for more details.

**Comment by saurabh500** [comment]
@corivera Can you take a look?
