### ISSUE TITLE
ClientWebSocket x509 Support

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#26146]
System.Net.WebSockets.ClientWebSocket

tracking:
This is needed for certificate based authentication for AMQP+WS and MQTT+WS 

related tracking issue #26144

**Comment by stephentoub** [comment]
@joshfree, what does "support" here mean? Is this about adding APIs to enable something, and if so, what specifically?  ClientWebSocketOptions already has ClientCertificates; is this about a validation callback, certificate revocation checking, something else?

**Comment by karelz** [comment]
Clarification of the ask from @CIPop:
They need `ClientWebSocketOptions.ClientCertificates` to be supported also on Windows -- it was not supported in 2.0: https://github.com/dotnet/corefx/wiki/ApiCompat#systemnetwebsocketsclient

It will be resolved by switching Windows (except UWP) to managed WebSockets via #9503, closing as dupe.
