### ISSUE TITLE
Build and package System.Runtime.CompilerServices.Unsafe for netcoreapp20

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#26145]
We would have a performance regression in some of the Unsafe.As methods otherwise. It should build and packaged for netcoreapp2.0 that will cover the live netcoreapp as well.

See https://github.com/dotnet/corefx/pull/25959/files/0c0e5136caec611a7178470ff8fbcaa754ddc1a8#discussion_r159258597  for full discussion.

**Comment by weshaggard** [comment]
We can add a netcoreapp2.0 configuration but we also need to keep the netcoreapp configuration so we can build the entire netcoreapp vertical against live bits.

**Comment by ahsonkhan** [comment]
> but we also need to keep the netcoreapp configuration so we can build the entire netcoreapp vertical against live bits

Can you please expand on why we need to do that? It would undo the changes from https://github.com/dotnet/corefx/pull/25959

**Comment by jkotas** [comment]
There are two separate things:
1. System.Runtime.CompilerServices.Unsafe has netcoreapp specific build
2. System.Runtime.CompilerServices.Unsafe is bundled in .NET Core runtime

#25959 reversed both 1 and 2.

This issue is about bringing 1 back, but keeping 2 reversed.

If we do not do this, we will be missing the perf fix here: https://github.com/dotnet/corefx/blob/master/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.il#L269 . AsRef won't be as fast as it can be in .NET Core.

**Comment by KrzysztofCwalina** [comment]
@weshaggard is this something you could help us with for the bug bounce this month?
