### ISSUE TITLE
Proposal ZipArchive ctor that accepts byte[] or Memory<byte>

### ISSUE THREAD

**Issue by ghost** [dotnet/corefx#26156]
# Rationale

Generally, it is inconvenient to create stream from byte array as the code looks like:

```c#
var ms = new MemoryStream();
ms.Write(myBytes, 0, myBytes.Length);
```

If we happen to have ziparchive in memory, as byte array, this overhead of first creating memory stream from byte array to satisfy ZipArchive's ctor is significant.

# Proposal

In addition to the existing ToString overloads in BitConverter:

```c#
public ZipArchive(Stream stream)
public ZipArchive(Stream stream, ZipArchiveMode mode)
public ZipArchive(Stream stream, ZipArchiveMode mode, bool leaveOpen)
public ZipArchive(Stream stream, ZipArchiveMode mode, bool leaveOpen, Encoding entryNameEncoding)
```

Please consider:

```c#
public ZipArchive(Memory<byte> data)
public ZipArchive(Memory<byte> data, ZipArchiveMode mode)
public ZipArchive(Memory<byte> data, ZipArchiveMode mode, bool leaveOpen)
public ZipArchive(Memory<byte> data, ZipArchiveMode mode, bool leaveOpen,Encoding entryNameEncoding)
```

# Example:

```c#
var memory = new Memory<byte>(GetZipByteArrayFromSomewhere());
using(var zip = new ZipArchive(memory, ZipArchiveMode.Read))
{
    Assert.True(zip.GetEntry("some/path/inside/zip").Length > 0);
}
```

**Comment by jnm2** [comment]
What about `new MemoryStream(myBytes, writable: false)`?

**Comment by kasper3** [comment]
point is that memory stream copies this byte[] internally or we explicitly copy to it with Write()
Having a Memory<byte>, byte[] or even ReadOnlyMemory<byte> will skip that additional copy-of-N-bytes overhead (where N could be a huge).

**Comment by jnm2** [comment]
@kasper3 The memory stream constructor does not copy the buffer parameter.

**Comment by carlossanlop** [comment]
Triage:
The IO abstraction for data is stream. We use streams to avoid loading the entire zip file into memory.
