### ISSUE TITLE
Building pre-jitted CoreFx bits

### ISSUE THREAD

**Issue by gokarnm** [dotnet/corefx#26159]
Hi,

 When I build the CoreFx repo locally on a Linux machine, the built CoreFx bits contain only IL, unlike the bits [Microsoft distributes](https://download.microsoft.com/download/2/B/2/2B2854E7-7EAE-4FE9-85D2-19ACCD716F18/dotnet-runtime-2.0.4-linux-x64.tar.gz), which seem to be pre-jitted (PE64 flag is on, and ILOnly flag is off).

What is the process to build a pre-jitted version of CoreFx? Is that logic part of the build scripts in corefx repo, or it's being run as a post process? I understand that `crossgen` is the tool to be used for per-compiling, but I don't see switches in the build script to enable that. Any pointers would be helpful.

Branch used - https://github.com/dotnet/corefx/tree/v2.0.4
Command used for build - `/build.sh -ConfigurationGroup=Release -RuntimeOS=linux -OSGroup=Linux -release`
Built binaries picked from - `bin/runtime/netcoreapp-Linux-Release-x64`

**Comment by karelz** [comment]
@weshaggard would you know? I don't think it is in our dogfooding steps ...

**Comment by weshaggard** [comment]
We refer to this as crossgen'ing, and we don't do it in corefx repo. It is done as part of building Microsoft.NETCore.App/SharedFramework in the core-setup repo. Take a look at https://github.com/dotnet/core-setup/blob/d5e9580461cf73577f4882ce8755a038c907abfb/src/pkg/projects/Microsoft.NETCore.App/src/Microsoft.NETCore.App.depproj#L240

**Comment by gokarnm** [comment]
Thanks @weshaggard !
