### ISSUE TITLE
Minimize nuget package dependencies

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#26162]
As .NET Standard support gets added inbox on more platforms, in particular .NET Framework, we should add some logic to your packaging that will minimize the package dependencies when targeting those platforms. In particular any package that is targeting NETStandard.Library (or its closure) before 2.0 should have a empty dependency group for net461 and higher to eliminate the need for that package closure. 

See https://github.com/dotnet/corefx/pull/26161 and https://github.com/dotnet/buildtools/pull/1847 as two improvements but we should create a more general mechanism.

**Comment by ericstj** [comment]
We already have a general mechanism to do this.  We look at any netstandard or portable dependency group, copy its dependencies to framework specific dependency groups, remove anything that's considered "inbox", then delete redundant groups (if for example, nothing was removed).  See https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks.Packaging/src/CreateTrimDependencyGroups.cs.

**Comment by weshaggard** [comment]
@ericstj cool. What should I have added to address the specific cases I fixed ( #26161 and dotnet/buildtools#1847)?

**Comment by ericstj** [comment]
Likely something going wrong in that task that needs to be debugged.  I checked the dependency groups for dataflow and indeed its missing TFM specific ones for frameworks compatible with ns1.1 and later with inbox dependencies.
