### ISSUE TITLE
AllowRenegotiation property on SslStream options bag is not implemented.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#26168]
It is not clear why the AllowRenegotiation property was added to the options bag in the ALPN API proposal in the issue #23177

Renegotiation is not a condition or property required for ALPN. It is not clear if this property is intended for the purposes of allowing/disallowing insecure renegotiation.

@Tratcher @geoffkizer  I remember you mentioning this is required for HTTP/2 support, can you elaborate on the use-case for this property? If not, we should remove this from the API surface area, as it's not supported in implementation currently.

**Comment by Priya91** [comment]
In reference to article: https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_options.html

**Comment by Tratcher** [comment]
See https://tools.ietf.org/html/rfc7540#section-9.2.1. The spec says renegotiation must be disabled, it does not give a lot of reasoning as to why.

I asked on the PR why you were adding the property before implementing it. Now it's time to implement it.

**Comment by Priya91** [comment]
So in that case, we want ```AllowRenegotiation``` to always be true whenever secure renogiations are possible which is monitored by the native OS stack, and in case of HTTP/2 one might disable renegotiation. In that case, it makes sense to rename this property as ```DisableRenegotiation``` with default as false, and the user may set it to true in case of HTTP/2.
