### ISSUE TITLE
API Propsal: char.GetUnicodeCategory(unicode scalar)

### ISSUE THREAD

**Issue by ufcpp** [dotnet/corefx#26173]
## Rationale and Usage
Support getting the Unicode category of 32-bit codepoint.

To do that today, have to do the following

```cs
UnicodeCategory  cat = char.GetUnicodeCategory(char.ConvertFromUtf32(0x1F401), 0)
```

The problem is char.ConvertFromUtf32 always allocate a new string which is not used afterward.

We need to have a way to do something like 
```C#
UnicodeCategory  cat = CharUnicodeInfo.GetUnicodeCategory(0x1F401);
```
without allocating any intermediate strings or other objects.

## Proposed API

```C#
 public static class CharUnicodeInfo
 {
      public static UnicodeCategory GetUnicodeCategory(int ch) {}
 }
```

## Notes

- CharUnicodeInfo class already have the following internal method which does what is proposed here. We'll just need to expose it with the proper name.

[`InternalGetUnicodeCategory(int ch)`](https://source.dot.net/#System.Private.CoreLib/shared/System/Globalization/CharUnicodeInfo.cs,196d0be2b1b2b26a)

- The proposal is exposing the API from CharUnicodeInfo class and not from Char struct. The reason is Char struct is by convention is the 16-bit char. So exposing the API taking 32-bit codepoint would fit better in CharUnicodeInfo

## Original text written by @ufcpp 

I'd like Unicode scalar/code point/[rune](https://github.com/dotnet/corefx/issues/24093) version of the `GetUnicodeCategory` method.

I have a [UTF8-related library](https://github.com/ufcpp/GraphemeSplitter) and I often write a code like the following:
```cs
char.GetUnicodeCategory(char.ConvertFromUtf32(0x1F401), 0)
```

This is inefficient because of string allocation. Futhermore, coreclr has the [`InternalGetUnicodeCategory(int ch)`](https://source.dot.net/#System.Private.CoreLib/shared/System/Globalization/CharUnicodeInfo.cs,196d0be2b1b2b26a) method internally. Please make this public.

**Comment by danmosemsft** [comment]
@ufcpp could you please format the top post as recommended in https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md ?

**Comment by tarekgh** [comment]
@ufcpp I have updated the proposal text above, please let me know if this looks good to you so I can mark the issue as ready for design review.

**Comment by tarekgh** [comment]
CC @krwq @AlexGhiondea

**Comment by ufcpp** [comment]
Sorry to bother you. Thank you so mush. LGTM.

**Comment by terrajobst** [comment]
Looks good but we should rename the parameter:

```
 public static class CharUnicodeInfo
 {
      public static UnicodeCategory GetUnicodeCategory(int codePoint);
 }
```

**Comment by tarekgh** [comment]
@ufcpp do you want to help in the implementation of this API? I can guide you in that if you are willing to do it. Thanks.

**Comment by ufcpp** [comment]
@tarekgh 
yes please. thanks.

**Comment by tarekgh** [comment]
you may start by creating a PR which will rename the method 

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Globalization/CharUnicodeInfo.cs#L293

and make it public and search for all callers yo update them too. after we finish the changes in coreclr repo, we'll expose the new API from corefx repo.

**Comment by ufcpp** [comment]
I've created a pull request: https://github.com/dotnet/coreclr/pull/15911
Is this OK?

**Comment by tarekgh** [comment]
this is done.
