### ISSUE TITLE
TCPListener.Stop leaks a socket handle

### ISSUE THREAD

**Issue by kg** [dotnet/corefx#26170]
If you use TCPListener.Start and then Stop the listener, the Stop method then creates a new socket. That socket leaks until reclaimed by the GC (or some other mechanism). In many cases this is harmless since it's not eating up a port, but on Linux this can result in "Too many open files".

https://github.com/dotnet/corefx/blob/6719752de7cee6ee44ba3cd542c36d6785034413/src/System.Net.Sockets/src/System/Net/Sockets/TCPListener.cs#L165

Mono uses corefx's implementation of this class and using TCPListener in a loop will typically exhaust available handles relatively quickly, producing this:

```
Unhandled Exception:
System.Net.Sockets.SocketException (0x80004005): Too many open files
  at System.Net.Sockets.Socket.Accept () [0x00033] in <c2e1018d8475415eae8a3c299d0a3981>:0 
  at System.Net.Sockets.TcpListener.AcceptSocket () [0x0001e] in <c2e1018d8475415eae8a3c299d0a3981>:0 
  at Program.Step () [0x000d0] in <5edebf9e82cb4b9695ac71dcde742b80>:0 
```

From my testing on Windows both .NET Framework and .NET Core leak a handle in Stop, but periodically the leaked handles are collected via some mechanism (according to Visual Studio diagnostic tools, this mechanism is not a regular GC). If you look at the handle count for the dotnet process it climbs very rapidly while starting/stopping TCPListeners, then occasionally drops by like 700.

So, given that this behavior matches .NET Framework, it's probably not a "bug", but it seems wrong to me. Is it intentional and something that has to be kept for compatibility purposes? I'd argue that .Stop should not be allocating a new socket, since in many scenarios the user is never going to use the listener again after they stop it, and that leaked handle will sit around for a while.

Here is my test case. I tested it on Windows under .NET Framework and .NET Core 2.0, and on Linux under trunk mono:
https://gist.github.com/kg/09f6eeb8082838913a65eb5b19fbb9d6

Mono throwing an exc here is obviously not dotnet's fault, but I wanted to raise the underlying stdlib issue since it seems wrong to me.

**Comment by karelz** [comment]
I agree that it looks a bit weird. All methods check for `_active` which is correctly set by `Stop`.

I think we could set `_serverSocket = null` in `Stop` and just delay the creation (if another `Start` is called) to the `Start` method.
@geoffkizer @davidsh do you have any concern with this approach?
cc @wfurt

**Comment by geoffkizer** [comment]
Seems reasonable to me

**Comment by wfurt** [comment]
I can take a look. Once we close socket it should not count agains OS limit even if GC did not release the resources.

**Comment by davidsh** [comment]
>@geoffkizer @davidsh do you have any concern with this approach?

I think we should research this before making any changes.  It has been this way in .NET Framework, for example, for a very long time.

**Comment by wfurt** [comment]
agreed @davidsh My plan was to reproduce it and find root cause as a first step.

**Comment by karelz** [comment]
@davidsh what kind of research do you have in mind? Source history of .NET Framework? Something else?

@wfurt not sure what you mean by reproducing / finding root cause -- it is a perf improvement suggestion. The best we can do in code is see if it breaks any test (although it is not guarantee on its own).

**Comment by davidsh** [comment]
>@davidsh what kind of research do you have in mind? Source history of .NET Framework? Something else?

Yes, plus asking other people that have experience in the code:

cc: @Tratcher @CIPop FYI.  Please comment if you have thoughts on this.

**Comment by Tratcher** [comment]
Karelz's suggestion seems the most likely, a new socket is created to allow Start to be called again and prevent Server from throwing ObjectDisposedException. Both of these code paths could become lazy. ExclusiveAddressUse.Get would also need to be lazy. Everything else appears to be guarded by the _active flag.
