### ISSUE TITLE
API Proposal : Simd SetAllVector* from scalar

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/corefx#26185]
@eerhardt @CarolEidt @RussKeldorph 

Target Framework netcoreapp2.1

```C#
namespace System.Runtime.Intrinsics.Arm.Arm64
{
    /// <summary>
    /// This class provides access to the Arm64 AdvSIMD intrinsics
    ///
    /// Arm64 CPUs indicate support for this feature by setting
    /// ID_AA64PFR0_EL1.AdvSIMD == 0 or better.
    /// </summary>
    public static class Simd
    {
        public static bool IsSupported { get { throw null; } }

        /// <summary>
        /// SetVector* Fill vector elements by replicating element value
        ///
        /// Corresponds to vector forms of ARM64 DUP (general), DUP (element 0), FMOV (vector, immediate)
        /// </summary>
        public static Vector64<T>    SetAllVector64<T>(T value) where T : struct { throw null; }
        public static Vector128<T>   SetAllVector128<T>(T value) where T : struct { throw null; }
   }
}

**Comment by jkotas** [comment]
Same methods are called `Set1` in Intel intrinsics. Should we rename them in Intel intrinsics?

cc @fiigii

**Comment by tannergooding** [comment]
@jkotas, I believe they are being renamed to `SetAll`: https://github.com/dotnet/coreclr/pull/15601

**Comment by fiigii** [comment]
Yes, in this case, we call them SetAll.

**Comment by sdmaclea** [comment]
The problem with SetAll is the return type must be specified.  For ARM64 Vector64 and Vector128 are in the same intrinsic class.

**Comment by CarolEidt** [comment]
> The problem with SetAll is the return type must be specified. For ARM64 Vector64 and Vector128 are in the same intrinsic class.

That's kind of unfortunate, but perhaps `SetAll64` and `SetAll128`?

**Comment by sdmaclea** [comment]
Update to use generics and use proposed names

**Comment by jkotas** [comment]
> `SetAll64` and `SetAll128`?

`SetAllVector64` and `SetAllVector128` would be more consistent with how things are named in .NET, I think.

**Comment by 4creators** [comment]
Perhaps it could be useful for self documenting code to update names of Intel intrinsics to `SetAllVector128`, `SetAllVector256` and in future `SetAllVector512`. Despite the fact that every method belongs to different ISA such naming will be very helpful particularly when someone writes code for several ISA targets and uses static using.

The very same naming could be changed for `Set` and `SetZero` as well.

cc @jkotas @fiigii @tannergooding @sdmaclea

**Comment by jkotas** [comment]
Agree. @fiigii Would it make sense to fold this feedback into your current PR?

**Comment by fiigii** [comment]
@jkotas The naming of `SetAllVector*` is caused by the limitation of ARM ISA design. On x86 platforms, ISA strongly implies the vector size. It does not only impact `Set*`, and also I guess ARM will have more names with `Vector*` suffix that is unnecessary for most of the Intel HW intrinsics.

**Comment by CarolEidt** [comment]
@fiigii - the fact that the `Vector*` suffix is unnecessary is, IMO, overshadowed by the desire for commonality where the functionality is the same.
As a side note, I wouldn't view this as a "limitation" of ARM ISA design; it is presumably more due to the fact that ARM64 provided support for multiple vector sizes all at once, rather than staging them as Intel did.

**Comment by fiigii** [comment]
> As a side note, I wouldn't view this as a "limitation" of ARM ISA design; it is presumably more due to the fact that ARM64 provided support for multiple vector sizes all at once, rather than staging them as Intel did.

Agree, that is what I meant.

**Comment by tannergooding** [comment]
@fiigii, I believe it is meant to support both more readable code and to the case of `using statics`:
```C#
using System.Runtime.Intrinsics;
using static System.Runtime.Intrinsics.X86.Sse;
using static System.Runtime.Intrinsics.X86.Avx;

if (Avx.IsSupported)
{
    var x = SetAllVector256(5.0f);
}
else if (Sse.IsSupported)
{
    var x = SetAllVector128(5.0f);
}
```

**Comment by fiigii** [comment]
@jkotas @CarolEidt @tannergooding 
To be clear, I am okay with the name of `SetAllVector*`, but how about others?

**Comment by tannergooding** [comment]
@fiigii, it might be worth looking at which APIs, when all exposed via `using static` would cause ambiguities. Those would be the ones worth fixing.

It might simultaneously be worthwhile to collapse the generic "explosion" we have, as that has been requested on most of the ARM PRs here (CC @jkotas)

**Comment by fiigii** [comment]
>  it might be worth looking at which APIs, when all exposed via using static would cause ambiguities.

I see. Shall we guarantee that no ambiguity when `using static` **all the ISA classes**?

**Comment by jkotas** [comment]
I do not think that no ambiguity when `using static` should be a hard requirement. Also, I am not sure whether `using static` should be the encouraged pattern for this like in the example above - it will make it easy to miss that given method is from a different ISA class.

**Comment by CarolEidt** [comment]
> I do not think that no ambiguity when using static should be a hard requirement. Also, I am not sure whether using static should be the encouraged pattern for this like in the example above - it will make it easy to miss that given method is from a different ISA class.

While it may not be desirable to mandate *no* ambiguity, I still think it's desirable. In many scenarios I doubt that it would be essential to know which ISA each method comes from.

**Comment by 4creators** [comment]
> While it may not be desirable to mandate no ambiguity, I still think it's desirable

Agree and fortunately only minority of methods have parameters which do not allow to determine which method is called and these are only methods which take exclusively scalar parameters. Any method with `Vector` parameter will immediately differentiate between methods from different ISA.

**Comment by fiigii** [comment]
>  I still think it's desirable.

Okay, it is good to have a criterion for the HW intrinsic naming. I will investigate and fold the change into https://github.com/dotnet/coreclr/pull/15601

**Comment by sdmaclea** [comment]
> do not think that no ambiguity when `using static` should be a hard requirement

```c#
using System.Runtime.Intrinsics;
using static System.Runtime.Intrinsics.X86.Sse;
using static System.Runtime.Intrinsics.X86.Avx;
using static System.Runtime.Intrinsics.Arm.Arm64.Simd;
```

Will also lead to namespace conflicts.  So `SetAllVector128` will need to be resolved.

**Comment by fiigii** [comment]
@sdmaclea I think no ambiguity when `using static` _all the ISA classes of ONE platform_ is enough.

**Comment by sdmaclea** [comment]
> no ambiguity when using static all the ISA classes of ONE platform is enough

Agreed but compiler issue must still be resolved.  This is probably closer to the preferred style.

```C#
using System.Runtime.Intrinsics;

if (Avx.IsSupported)
{
    using static System.Runtime.Intrinsics.X86.Avx;
    var x = SetAllVector256(5.0f);
}
else if (Sse.IsSupported)
{
    using static System.Runtime.Intrinsics.X86.Sse;
    var x = SetAllVector128(5.0f);
}
else if (Arm.Arm64.IsSupported)
{
    using static System.Runtime.Intrinsics.Arm.Arm64;
    var x = SetAllVector128(5.0f);
}

**Comment by 4creators** [comment]
> Will also lead to namespace conflicts. So SetAllVector128 will need to be resolved.

Any ambiguity of this kind will raise `compilation error` and it should be sufficient to enforce correct usage of API. Developers will have than quite a few ways to handle efficiently this problem.

**Comment by sdmaclea** [comment]
@CarolEidt @eerhardt This should be marked "API-ready-for-review"

**Comment by sdmaclea** [comment]
@eerhardt Any reason why this is marked future? The CoreCLR work is complete and ready for 2.1.

**Comment by terrajobst** [comment]
Looks good as proposed. Feedback:

* We should have those, but we should also expose a generic setter on the vector types that are implemented in terms of those (and their X86).
* We should probably rename the method to `Duplicate` to match the ISA. Also, `Set` in .NET terminology means something different.

**Comment by tannergooding** [comment]
The `SetVector` APIs were replaced by `Vector128.Create` APIs which are cross-platform and provide a software fallback.
