### ISSUE TITLE
API Proposal: Arm64 Simd BitwiseSelect

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/corefx#26181]
@eerhardt @CarolEidt @RussKeldorph 

Target Framework netcoreapp2.1

```C#
namespace System.Runtime.Intrinsics.Arm.Arm64
{
    /// <summary>
    /// This class provides access to the Arm64 AdvSIMD intrinsics
    ///
    /// Arm64 CPUs indicate support for this feature by setting
    /// ID_AA64PFR0_EL1.AdvSIMD == 0 or better.
    /// </summary>
    public static class Simd
    {
        public static bool IsSupported { get { throw null; } }

        /// <summary>
        /// Vector BitwiseSelect
        /// For each bit in the vector result[bit] = sel[bit] ? left[bit] : right[bit]
        /// Corresponds to vector forms of ARM64 BSL (Also BIF & BIT)
        /// </summary>
        public static Vector64<T>  BitwiseSelect<T>(Vector64<T>  sel, Vector64<T>  left, Vector64<T>  right) where T : struct { throw null; }
        public static Vector128<T> BitwiseSelect<T>(Vector128<T> sel, Vector128<T> left, Vector128<T> right) where T : struct { throw null; }
    }
}
```

**Comment by sdmaclea** [comment]
My current understanding is the difference between BSL, BIT, BIF is simply in which of the source registers is used as the destination register.  Therefore I am using the same intrinsic for all of them.  This may give more flexibility to the register allocator.

**Comment by sdmaclea** [comment]
Updated to use generics

**Comment by sdmaclea** [comment]
@CarolEidt @eerhardt I think this can be marked "API-ready-for-review"

**Comment by sdmaclea** [comment]
@eerhardt Any reason why this is marked future? The CoreCLR work is complete and ready for 2.1.

**Comment by terrajobst** [comment]
Looks good as proposed. Feedback:

* The parameter should be spelled out "select", or whatever the spec calls it.
* If we expand the generics, the first argument should be an `int`-based type
