### ISSUE TITLE
API Proposal: Add extension methods to convert from Span<T> and Memory<T> to VectorXXX<T> and in reverse

### ISSUE THREAD

**Issue by 4creators** [dotnet/corefx#26195]
I would like to propose creating extension methods located in static class `VectorExtensions` in `System.Runtime.Intrinsics` namespace and providing efficient support for working with `Span<T>` and `Memory<T>`. Proposal is to implement them as an `Intrinsics` and implement them in RyuJIT using relevant `Load` and `Store` instructions plus efficient setting of `Length` property by general instructions.

The reason for putting this propsal is that having written quite a bit of tests for HW intrinsics I have noticed that the easiest way to work on the edge between safe C# code and HW intrinsics with `Vector128<T>`, `Vector256<T>` and  in future with other sizes of the `VectorXXX` is to use `Span<T>` and `Memory<T>` as data interchange formats.

```C#

namespace System.Runtime.Intrinsics
{
    [Intrinsic]
    public static class VectorExtensions
    {
        // Span<T> extension methods

        [Intrinsic]
        public static Span<T> AsSpan<T>(this Vector64<T> vector) => vector.AsSpan();

        [Intrinsic]
        public static Span<T> AsSpan<T>(this Vector128<T> vector) => vector.AsSpan();

        [Intrinsic]
        public static Span<T> AsSpan<T>(this Vector256<T> vector) => vector.AsSpan();

        [Intrinsic]
        public static Vector64<T> AsVector<T>(this Span<T> span) => span.AsVector();

        [Intrinsic]
        public static Vector128<T> AsVector<T>(this Span<T> span) => span.AsVector();

        [Intrinsic]
        public static Vector256<T> AsVector<T>(this Span<T> span) => span.AsVector();

        // ReadOnlySpan<T> extension methods

        [Intrinsic]
        public static ReadOnlySpan<T> AsReadOnlySpan<T>(this Vector64<T> vector) => vector.AsReadOnlySpan();
        
        [Intrinsic]
        public static ReadOnlySpan<T> AsReadOnlySpan<T>(this Vector128<T> vector) => vector.AsReadOnlySpan();
        
        [Intrinsic]
        public static ReadOnlySpan<T> AsReadOnlySpan<T>(this Vector256<T> vector) => vector.AsReadOnlySpan();

        [Intrinsic]
        public static Vector64<T> AsVector<T>(this ReadOnlySpan<T> span) => span.AsVector();
        
        [Intrinsic]
        public static Vector128<T> AsVector<T>(this ReadOnlySpan<T> span) => span.AsVector();
        
        [Intrinsic]
        public static Vector256<T> AsVector<T>(this ReadOnlySpan<T> span) => span.AsVector();

        // Memory<T> extension methods
        
        [Intrinsic]
        public static Memory<T> AsMemory<T>(this Vector64<T> vector) => vector.AsMemory();
        
        [Intrinsic]
        public static Memory<T> AsMemory<T>(this Vector128<T> vector) => vector.AsMemory();
        
        [Intrinsic]
        public static Memory<T> AsMemory<T>(this Vector256<T> vector) => vector.AsMemory();

        [Intrinsic]
        public static Vector64<T> AsVector<T>(this Memory<T> memory) => memory.AsVector();
        
        [Intrinsic]
        public static Vector128<T> AsVector<T>(this Memory<T> memory) => memory.AsVector();
        
        [Intrinsic]
        public static Vector256<T> AsVector<T>(this Memory<T> memory) => memory.AsVector();

        // ReadOnlyMemory<T> extension methods
        
        [Intrinsic]
        public static ReadOnlyMemory<T> AsReadOnlyMemory<T>(this Vector64<T> vector) => vector.AsReadOnlyMemory();

        [Intrinsic]
        public static ReadOnlyMemory<T> AsReadOnlyMemory<T>(this Vector128<T> vector) => vector.AsReadOnlyMemory();

        [Intrinsic]
        public static ReadOnlyMemory<T> AsReadOnlyMemory<T>(this Vector256<T> vector) => vector.AsReadOnlyMemory();

        [Intrinsic]
        public static Vector64<T> AsVector<T>(this ReadOnlyMemory<T> memory) => memory.AsVector();
        
        [Intrinsic]
        public static Vector128<T> AsVector<T>(this ReadOnlyMemory<T> memory) => memory.AsVector();
        
        [Intrinsic]
        public static Vector256<T> AsVector<T>(this ReadOnlyMemory<T> memory) => memory.AsVector();        
    }

```

**Comment by jkotas** [comment]
> `public static Span<T> AsSpan<T>(this Vector64<T> vector)`

What storage would the Span point to?

**Comment by jkotas** [comment]
>  it should be possible to use Span inside method body and pass it to callee

This is invalid operation. The method stack is gone when method returns. 

```csharp
static Span<byte> MyMethod()
{
    Span<byte> bytes = stackalloc byte[3];
    return bytes;
}
```

fails to compile `Cannot use local 'bytes' in this context because it may expose referenced variables outside of their declaration scope` for a good reason.

**Comment by 4creators** [comment]
> This is invalid operation. The method stack is gone when method returns.

Yeah I know this if you want to return something it is necessary to use `Memory<T>`. I meant to use it as follows:

```
static Span<byte> MyMethod()
{
    Span<byte> bytes = stackalloc byte[3];
    Foo(bytes); // callee where MyMethod is caller
    for(int i = 0; i < bytes.Length; i++) 
    // do something
    var vectorMemory = vec.AsMemory();
    return vectorMemory;
}
```

**Comment by tannergooding** [comment]
@4creators, I don't agree.

At present, the reason the tests are being writing using `Unsafe.As` is simply because the `Load` and `Store` operations have not been implemented.

It also provides a good way to validate that we are testing just the operation we care about while only relying on existing operations which we know should be well-behaved.

After `Load` and `Store` are implemented, the vast majority of operations should be (and would likely be expected to) use them, rather than using `Unsafe`, to convert between the storage format (such as `byte[]`, `Span<byte>`, etc) and the operation format (`VectorXXX<T>`).

**Comment by 4creators** [comment]
@tannergooding 

There are several misconceptions in your arguments:

First of all API proposal is not about HW Intrinsic tests implementation but states that I have found it very useful to use `Span` and `Memory` while working on HW Intrinsic tests, therefore, discussion about implementing tests should go into PR review rather than API proposal. 

IMO here we should discuss general usefulness of proposed API contract.



> the reason the tests are being writing using Unsafe.As is simply because the Load and Store operations have not been implemented.

**This is not true** Unit tests are about verifying single unit of functionality which is single HW Intrinsic function/instruction. How, we load data into Vector before test is run is totally irrelevant for the effectiveness of the test. `Load` and `Store` intrinsics will have their own tests in which we will check their correctness and we should never ever assume that correctness of implementation should be tested using those intrinsics in code supporting tests. This obviously does not mean that we cannot or should not use them, if it does make sense why not.

> After Load and Store are implemented, the vast majority of operations should be (and would likely be expected to) use them, rather than using Unsafe

This is matter of convention, of personal or organization coding preferences and `CodeGen` effectiveness. From what I have been seeing so far `CodeGen` for `Unsafe.Read<Vector128<byte>>` or `Unsafe.Write<Vector128<byte>>` and other specializations generates exactly the same code which will be generated by `Load` or `Store`. Therefore it is not that obvious that using `Load` or `Store` would be beneficial from performance perspective. The only argument being that `Unsafe` is generally deeply hidden and not recommended to use in the first place but such recommendations are rarely followed by devs optimizing for performance.

Furthermore, `Unsafe` has nothing to do with `Span` and `Memory` which by design should be preferably used for handling memory backed data in dotnet. Vector edge interchange is always with memory and having effective way to cast to standard framework representations seems to me quite obvious.

**Comment by jkotas** [comment]
@4creators I do not understand your proposal. I would help to have:

- More complete examples of how these APIs would be used - e.g. take the first API `public static Span<T> AsSpan<T>(this Vector64<T> vector)` and show a real world piece of code that uses it.
- More details about how these APIs should be implemented - e.g. provide a working functionally correct C# implementation for the first API.

**Comment by 4creators** [comment]
@jkotas @tannergooding
 
There is accepted API which added Span based `Vector<T>` constructor. While I am not suggesting that VectorXXX should have any constructors availability of `Span` and `Memory` thin casts would fit very well in Span based new .NET landscape.

> I do not understand your proposal. I would help to have

I will address it a bit later

**Comment by tannergooding** [comment]
@eerhardt, @jkotas, @4creators I don't think this proposal should move forward.

`Span<T>` implements both `GetPinnableReference` and `ref returning indexers`. This means that both of the following are valid syntax and are covered by the `Load/Store` methods that exist today:
* `fixed (float* pParam = span)`
* `fixed (float* pParam = &span[i])`

If any additional overloads were exposed, they should be overloads that take `ref`, which would also work with `Span<T>`. However, that is still a separate discussion that was initially resolved as "add if needed".

**Comment by jkotas** [comment]
Agree.
