### ISSUE TITLE
Three TypeExtensions tests failing on Linux with xUnit 2.1.0

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#2619]
A few of the reflection tests seem to be failing on Linux when run with xUnit 2.1.0. These tests are doing fairly simple stuff, just subscribing some events and then triggering them, and checking the state afterwards.

    System.Reflection.Compatibility.UnitTests.EventInfoAddEventHandler.PosTest2
    System.Reflection.Compatibility.UnitTests.EventInfoAddEventHandler.PosTest3
    System.Reflection.Compatibility.UnitTests.EventInfoAddEventHandler.PosTest1

**Comment by mellinoe** [comment]
From #2609 :

> Sorry, I take back my previous concurrency-related comment: I haven't tried running it, but it looks like these tests expect to be executed in a specific order, sharing state between then via a static field, and my guess is that order isn't holding as expected.

This seems like a pretty reasonable explanation. All of the values seem to be off by one in the failures, so the tests are probably not running in a predictable order. We should probably re-write these to be more robust, and in the process hopefully name them something more meaningful :smile:

**Comment by joshfree** [comment]
@Priya91
