### ISSUE TITLE
Add constructors to TcpClient and TcpListener that accept an existing Socket

### ISSUE THREAD

**Issue by orthoxerox** [dotnet/corefx#26193]
Please consider adding constructors to TcpClient and TcpListener that accept an existing Socket.

## Rationale and usage

If https://github.com/dotnet/corefx/issues/14041 is implemented, we will be able to create `Socket` instances that represent existing handles. It will be very convenient if we could create a `TcpListener` or a `TcpClient` wrapping that socket to avoid dealing with raw sockets.

## Proposed API

```c#
namespace System.Net.Sockets
{
    partial class TcpListener {
        public TcpListener(Socket socket) {}
    }
    partial class TcpClient {
        public TcpClient(Socket socket) {}
    }
}
```

## Alternatives

Instances of all three types could be instantiated from socket handles directly instead.

**Comment by wfurt** [comment]
Can you sue something like:

```c#
var c = new TcpClient();
c.Client = socket;
```
It is little bit less efficient than new constructor but it should work.
any thoughts on this @karelz ?

**Comment by karelz** [comment]
If the above works, that would be great.
What is the scenario where you have first a socket and later you want to wrap it in TcpClient/TcpListener?

**Comment by wfurt** [comment]
Among other things it allows you to use higher level API on top of sockets other than TCP. 
(like named pipes) But I don't know if that is hwat @orthoxerox wants to do.

**Comment by orthoxerox** [comment]
@karelz My goal is to transfer an open TCP connection from one application to another.

**Comment by karelz** [comment]
Is that something that the OS supports via native APIs?

**Comment by orthoxerox** [comment]
On UNIX `fork` shares all open file descriptors, and on Windows `CreateProcess` has a parameter that shares all handles. AFAIR, `Process.Start` sets this parameter on Windows.

**Comment by karelz** [comment]
Triage: This is niche use case (only 1 upvote in last year).
It is achievable via https://github.com/dotnet/corefx/issues/26193#issuecomment-395648527 once #14041 is implemented.
