### ISSUE TITLE
NullReferenceException when awaiting a task only in a unit test

### ISSUE THREAD

**Issue by SamuelCox** [dotnet/corefx#26206]
Got a bit of a weird one here.
If you clone https://github.com/SamuelCox/LifeManager and run the only test in CalendarServiceTests in LifeManager.CalendarService.Tests project, you should see the following stack trace:

`` at LifeManager.CalendarService.Services.CalendarService.<CreateEvent>d__2.MoveNext() in C:\projects\lifemanager\LifeManager\LifeManager.CalendarService\Services\CalendarService.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LifeManager.CalendarService.Tests.CalendarServiceTests.<CreateEvent_ShouldCallRepositoryAdd>d__2.MoveNext() in C:\projects\lifemanager\LifeManager\LifeManager.CalendarService.Tests\CalendarServiceTests.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context) ``

I've debugged this and nothing is null. It's just the await that blows up. I've also re-read over async await and I should be able to do what I'm trying to do here. It's entirely possible I'm doing something completely wrong here, but I'm not sure what it is. Equally, it could be something with NUnit, but I'm starting here.

The really odd thing is, that the code I'm unit testing works if I do it outside of a unit test, i.e, in Program.cs in LifeManager.CalendarService. I also tried deleting the test csproj and recreating it. Bit baffled here, any help is appreciated.

**Comment by jnm2** [comment]
I'm getting the same behavior without NUnit being invoked. Add this class:

```cs

namespace LifeManager.CalendarService.Tests
{
    public static class Program
    {
        public static void Main()
        {
            var fixture = new CalendarServiceTests();
            fixture.SetUp();
            fixture.CreateEvent_ShouldCallRepositoryAdd().GetAwaiter().GetResult();
        }
    }
```

And overwrite these csproj properties:

```xml
    <OutputType>Exe</OutputType>
    <StartupObject>LifeManager.CalendarService.Tests.Program</StartupObject>
```

And press F5.

In fact, awaits don't have anything to do with it either as you can see by running this:

```cs
public static void Main()
{
    Mapper.Initialize(cfg => cfg.CreateMap<CalendarEvent, CalendarEventModel>().ReverseMap());
    var mockCalendarRepository = new Mock<ICalendarRepository>();
    mockCalendarRepository.Setup(x => x.Add(It.IsAny<CalendarEvent>())).Verifiable();

    var calendarEventModel = new CalendarEventModel { Id = Guid.NewGuid() };
    var calendarEvent = Mapper.Map<CalendarEvent>(calendarEventModel);
    Assert.That(mockCalendarRepository.Object.Add(calendarEvent), Is.Not.Null);
}
```  

Looking closer, it seems that you haven't set up the mock to return anything in particular when you call Add on the mock instance. So returning null is what I'd expect it to do.

> The really odd thing is, that the code I'm unit testing works if I do it outside of a unit test, i.e, in Program.cs in LifeManager.CalendarService.

That is really odd. How does the working repro code compare to the code sample I gave immediately above?

**Comment by SamuelCox** [comment]
@jnm2 solved this for me in another repo. My inexperience with async await meant I was essentially treating the task return type as a void return type, didn't realise I had to mock a task to be returned.
