### ISSUE TITLE
[Proposal] Add string.Contains overloads to mirror string.IndexOf ones

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#26207]
## Proposed API

```cs
bool Contains(string value, int index);
bool Contains(string value, int startIndex, int count);

bool Contains(string value, StringComparison comparisonType);
bool Contains(string value, int index, StringComparison comparisonType);
bool Contains(string value, int startIndex, int count, StringComparison comparisonType);
```

## Rationale

- It seems inconsistent that `Contains`, a method that compares strings, does not accept a `StringComparison` argument while many other string-comparing methods do.
- Adding the index-based overloads may prevent some string allocations because people can do `str.Contains(other, 3, 10)` instead of `str.Substring(3, 10).Contains(other)`.

**Comment by jkotas** [comment]
`bool Contains(string value, StringComparison comparisonType);` exists already: https://github.com/dotnet/corefx/blob/master/src/System.Runtime/ref/System.Runtime.cs#L2229

For the overloads that take indices, we may rather want to be spending energy on https://github.com/dotnet/corefx/issues/21395. The Span based APIs for string operations are superior to APIs that take indices.

**Comment by jamesqo** [comment]
> For the overloads that take indices, we may rather want to be spending energy on #21395. The Span based APIs for string operations are superior to APIs that take indices.

I don't see `Contains` in the proposal there.

**Comment by ahsonkhan** [comment]
> I don't see `Contains` in the proposal there.

I will add it. Thanks.

**Comment by LeaFrock** [comment]
> > I don't see `Contains` in the proposal there.
> 
> I will add it. Thanks.

Glad to see that the APIs such as String.Contains(string value, StringComparison comparasionType) will add into .Net Standard 2.1. Thank you!

**Comment by stephentoub** [comment]
We now have:
```C#
public static bool Contains(this ReadOnlySpan<char> span, ReadOnlySpan<char> value, StringComparison comparisonType)
```
which would seem to obviate the need for this proposal.  Given that, I'm closing this.  Feel free to re-open if you feel strongly the aforementioned overloads are still really needed.
