### ISSUE TITLE
Session OnStart and Session OnEnd

### ISSUE THREAD

**Issue by ErcinDedeoglu** [dotnet/corefx#26212]
I came here from https://github.com/aspnet/Session/issues/20

@Tratcher @davidfowl @muratg
If you are not going to implement session onend; why we're setting the sessiontimeout?
I read all of above, but not implementing sesion onend is really strange decision. Every application uses session events. Also @Tratcher adviced that we can store data on sql not session. This is also not acceptable...

My issue is I need session start event to recognize user from its cookie to auto login. But I cant handle session start atm...

**Comment by karelz** [comment]
@ErcinDedeoglu what exactly do you need in CoreFX? What kind of API on which type?
AFAIK Session is ASP.NET API, not in CoreFX ...

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Session#206
