### ISSUE TITLE
Tests failed with "Exit code was 131 but it should have been 42"

### ISSUE THREAD

**Issue by Sunny-pu** [dotnet/corefx#26214]
failed test: 
System.Data.Tests.DataTableTest.PropertyExceptions
System.Data.Tests.DataTableTest.WriteXmlSchema
System.Data.Tests.SqlTypes.SqlStringTest.Properties
System.Data.Tests.AppDomainsAndFormatInfo.Bug82109
System.Data.Tests.DataSetReadXmlSchemaTest.LocaleOnRootWithoutIsDataSet
System.Data.Tests.DataSetTest.WriteXmlSchema
System.Data.Tests.DataSetTest.WriteXmlModeSchema1

Configuration: oxs10.12_release

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release/3963
MESSAGE:
Exit code was 131 but it should have been 42\nExpected: True\nActual: False
+++++++++++++++++++
STACK TRACE:
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 203

**Comment by danmosemsft** [comment]
SIGQUIT

**Comment by stephentoub** [comment]
The log shows:
```
  A fatal error occurred, the folder [/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/bin/testhost/netcoreapp-OSX-Release-x64/shared/Microsoft.NETCore.App/9.9.9/host/fxr] does not exist
```

**Comment by danmosemsft** [comment]
We have seen a bunch of these on OSX in the past: https://github.com/dotnet/corefx/issues/25037

My thought is to set COREHOST_TRACE.

**Comment by stephentoub** [comment]
> We have seen a bunch of these on OSX in the past

The ones I've looked at have all had the same fxr error in the log, so it seems cli/infrastructure related, maybe a race condition in how things are deployed.

**Comment by danmosemsft** [comment]
I remember I added more logging: https://github.com/dotnet/core-setup/pull/3436 ... although that would make it even more verbose. 

Perhaps we should log the trace in the event of failure, whether or not the environment variable is set.

**Comment by danmosemsft** [comment]
Although, I am not sure what extra it could tell us, in this case.

**Comment by divega** [comment]
@danmosemsft @stephentoub this issue showed up in the System.Data triage and we are wondering what needs to happen to resolve it. Is it really a System.Data issue?

cc @ajcvickers

**Comment by stephentoub** [comment]
@divega, at present I don't think so.  It appears to be related to infrastructure with how tests get run rather than with the specifics of individual tests.

**Comment by weshaggard** [comment]
Yeah this doesn't seem to be related to System.Data. A quick search shows it has happened in random tests (https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=%22Exit+code+was+131+but+it+should+have+been+42%22&type=Issues). I renamed this issue to failed with "Exit code was 131 but it should have been 42" and we can use this to try and get a repo. If anyone hits any similar failures please link to this issue, but right now I don't seem to see any way to repro this.

It seems like some issue with the host or the setup of the test directory, but it is hard to say for sure without a repo.

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/25037
