### ISSUE TITLE
High latency (> 450ms) when reading from NetworkStream

### ISSUE THREAD

**Issue by karmeli87** [dotnet/corefx#26216]
Scenario:
* TcpClient & TcpListener to talk between different processes
* High latency (> 450ms) when receiving messages on the _local_ machine

We have a protocol that requires that client & server will exchange heartbeats every 300 ms at most. 
So we set NoDelay on the TCP client, but sometimes when we send a message that is around 100 bytes big, we read it from the stream always in about 450ms +- 10%. 
We enforced PSH flag by setting `IgnorePushBitOnReceives` under `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\AFD\Parameters` but it didn't helped.

the full configuration of the TCP client:
	`tcpClient.NoDelay = true;`
	`tcpClient.ReceiveBufferSize = 32 * 1024;`
   ` tcpClient.SendBufferSize = 4096;`
   ` tcpClient.ReceiveTimeout = tcpClient.SendTimeout = 15_000;`

Unfortunately we were unable to repo this kind of behavior in an isolated project.

We always read into a buffer that is 32Kb in size and the data size can vary wildly. In this case, a server is responding to a write made by the client and the client
is seeing the result many hundreds of milliseconds later.

To make things really strange, this is on  _localhost_, so this should be really speedy. 
We've found this post: http://smallvoid.com/article/winnt-tcp-push-flag.html

Which seems very relevant, in particular:

	The recv() / WSARecv() calls returns when one of the following events occurs:

	* Data arrives with the PUSH bit set.
	* The user recv buffer is full.
	* 0.5 seconds have elapsed since any data has arrived.

However, even after setting the registry value, we are still seeing this behavior.

Is it possible that this behavior is related to the size of the buffer we send to the Read() call vs. the amount of data that is actually there?

Can anyone suggest any way to investigate this further? We believe that this behavior is also something that we are seeing in production which is causing us serious issues.

**Comment by Clockwork-Muse** [comment]
...how are you reading from the NetworkStream itself?  Do you try and fill an application buffer, up to some predetermined size?  What happens if you reduce the size of the buffer (since you have a question about that)?

**Comment by benaadams** [comment]
Have seen issues with localhost pop up https://github.com/dotnet/corefx/issues/24104

What happens if you explicitly use 127.0.0.1 ?

**Comment by davidsh** [comment]
cc: @stephentoub @geoffkizer

**Comment by ayende** [comment]
@Clockwork-Muse We aren't waiting to read the entire buffer, we are reading whatever it was that we got from the network and processing that.
The code in question looks like:


```
// buffer = new byte[32*1024]; // define elsewhere

// previously we wrote to the stream and sent it to the server
// the server reply to the write in ~10ms or so. 

var sp = Stopwatch.StartNew();
var read = networkStream.Read(buffer, 0, 32*1024);
// sp.ElapseMilliseconds = 450 +- 10% here.
// read = 98 in this case
```

I would expect this to be completed as soon as it has _anything_ in the socket, not wait for more, which is what it looks like it is doing?

**Comment by geoffkizer** [comment]
The linked post seems incorrect.

NoDelay affects the sending side.  Make sure you set NoDelay = true on the sending side.

As soon as data arrives on the receiving side, networkStream.Read should complete, regardless of the size sent.

**Comment by karelz** [comment]
Do you have a repro we could look at? Did you try the localhost IP & NoDelay on sending side as suggested above?

**Comment by ayende** [comment]
Pretty sure it was our thing, can close it as won't fix.

**Comment by karelz** [comment]
Thanks! Closed.
