### ISSUE TITLE
Linux ClientWebSocket does not change state or CloseStatus on server crash

### ISSUE THREAD

**Issue by wakemaster39** [dotnet/corefx#26219]
I am using ClientWebSocket to connect to an ASP.Net core server. During development on a windows 10 machine, if I the asp.net server were to close for some reason an exception would be thrown. Along with this execption, the CloseStatus and the State of the connection would both be changed. 

The exact same code while run under linux is still throwing the same exception, but the State of the connection is renaming open and the CloseStatus is remaining null. There is no current method I can tell to verify that the connection is still valid other than forcibly disposing the connection when this disconnect occurs.

**Comment by davidsh** [comment]
While this bug was originally opened on Linux platform, we recently changed ClientWebSocket on Windows platforms to use the same managed implementation (instead of using WinHttp).  So, now this bug would potentially affect all OS platforms of ClientWebSocket.

**Comment by rmkerr** [comment]
It looks like this was the expected results in the tests here:
https://github.com/dotnet/corefx/blob/1885cf8e6590fc7c4f48ef22a368beeb4fc1ee59/src/System.Net.WebSockets.Client/tests/SendReceiveTest.cs#L456-L466
As far as I can tell though this isn't a desirable behavior. I'll be looking into the fix, and will update the test along with it.
