### ISSUE TITLE
Expand Process.Kill to Optionally Kill a Process Tree

### ISSUE THREAD

**Issue by bgribaudo** [dotnet/corefx#26234]
## Issue
.Net Standard does not provide a means to kill a process tree (that is, a given process and all of its child/descendant processes). 

In the Windows world, this can be done by assembling the list of descendant processes to terminate using [WMI's Win32_Process management object](https://stackoverflow.com/a/7189381/117424), [performance counters](https://stackoverflow.com/a/2336322/117424) or [P/Invoke](https://stackoverflow.com/a/3346055/117424), then killing each one, then killing the parent/root process. However, since .Net Standard doesn't provide a way to enumerate child/descendant processes, it's impossible for a user to directly implement this approach in a cross-platform way using only .Net Standard.

If the ability to enumerate child processes were added (as #25855 proposes), there'd still be complexities involved with using the child process list to kill a process tree as care is needed to ensure that unrelated processes aren't inadvertently terminated because of process ID reuse. This proposal saves the developer from needing to worry about such complexities and instead provides a simple, one-line way to terminate a process tree.

## Rationale
Sometimes, it's necessary to end a process tree. :-)

For example, [`Microsoft.DotNet.Tools.Test.Utilities.ProcessExtension`](https://github.com/dotnet/cli/blob/35e661bbb3b2f0943590cb63747ae53a68e6eb5d/test/Microsoft.DotNet.Tools.Tests.Utilities/Extensions/ProcessExtensions.cs#L27) relies on different code paths to handle killing a process tree on Windows and Linux. Both code paths involve invoking one or more command-line processes. If this proposal were implemented, presumably this logic could be replaced with a single-line kill all method call followed possibly by a call to [`WaithForExit(int milliseconds)`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.waitforexit?view=netstandard-2.0#System_Diagnostics_Process_WaitForExit_System_Int32_). No multiple code paths. No need to invoke command-line processes.

Another example: A project I'm currently working on uses integration tests that use [`Process`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process?view=netstandard-2.0) to call `dotnet run` to start a server process. When the test has completed, it's possible to use Process's `Kill()` to end the parent dotnet process. However, this leaves child processes still running—which causes problems.

## Proposal

Extend `Process` as follows:

**Original (ignore—left for reference purposes):**
```c#
    public class Process : ....    {
        public void Kill(bool entireProcessTree = false); // false = existing behavior of Kill()
    }
```
**Revision (ignore—left for reference purposes):**
```c#
    public enum ProcessGroup { 
            CurrentProcess, 
            EntireTree 
    }

    public class Process : ....    {
        public void Kill(ProcessGroup group = ProcessGroup.CurrentProcess) { } // default = existing behavior of Kill()
    }
```

**Approved Version:**
```
    public class Process : ....    {
        public void Kill(bool entireProcessTree); 
    }
```

With this change, `Kill` will behave exactly as it does at current if it is called with no arguments or with `false` as its argument. However, when called with `true` as its argument, in a platform-appropriate way all descendant processes will be killed, followed by the process represented by the current `Process` instance.  

[edited by @danmosemsft to add c# formatting only]

**Comment by danmosemsft** [comment]
Implementation note for Windows: https://github.com/dotnet/corefx/issues/25855#issuecomment-351116254

**Comment by krwq** [comment]
I think it should be an enum not a bool. I'd expose at least three flags (even if DirectChildren will be outvoted I'd still vote for making it an enum):
- OnlySelf
- EntireTree
- DirectChildren

**Comment by bgribaudo** [comment]
Good thought about the enum, @krwq! I like how it makes it easier to add variations of behavior down the road. For example, if it becomes desirable to do 'Entire Tree + Wait for Exit'.

**Comment by krwq** [comment]
@bgribaudo let's update the proposal with enum if you feel this is a good idea. What about something like this for now (DirectChildren can wait until someone requests it and likely will be a part of implementation of EntireTree anyway):

```csharp
enum ProcessGroup
{
    OnlySelf,
    EntireTree
}
```

**Comment by bgribaudo** [comment]
@krwq, done. Thanks!

**Comment by danmosemsft** [comment]
For clarity this is what we agreed:
```c#
    public class Process : ....    {
        public void Kill(bool entireProcessTree); 
    }
```

**Comment by bgribaudo** [comment]
Thanks, @danmosemsft! Edited the top question so that it reflects the approved version.

**Comment by danmosemsft** [comment]
So @bgribaudo do you want to take a shot at the implementation? Even just one of Windows and Linux if you want.

**Comment by bgribaudo** [comment]
> @bgribaudo it took a while, but this is approved. Any interest in offering a PR, so it can be in 3.0?

@danmosemsft, I'm interested, though I'm not sure if I'm the right person to do this because of the platform-specific code work it will involve (for example, I don't have environments set up to test on every platform supported by dotNET). Is there someone I could chat with about this?

**Comment by bgribaudo** [comment]
## Implementation Notes

**For Windows,** msbuild's [Microsoft.Build.Shared.NativeMethodsShared](https://github.com/Microsoft/msbuild/blob/b499c93e95f440b98967b8d5edd910ee8556f504/src/Shared/NativeMethodsShared.cs#L980) looks like a good reference/starting place (implementation may be as simple as copy-and-paste!). Since this code uses P/Invoke instead of `taskkill`, I'm hoping (haven't tested) that it works on all dotNET supported Windows platforms. 

The Windows-specific portions of aspnet Common's [Microsoft.Extensions.Internal.ProcessHelper]( https://github.com/aspnet/Common/blob/e0f40110ff5e2101231ba54d48961bbd60a07727/shared/Microsoft.Extensions.Process.Sources/ProcessHelper.cs#L19) and CLI's [Microsoft.DotNet.Tools.Test.Utilities.ProcessExtensions](https://github.com/dotnet/cli/blob/35e661bbb3b2f0943590cb63747ae53a68e6eb5d/test/Microsoft.DotNet.Tools.Tests.Utilities/Extensions/ProcessExtensions.cs#L27) show another way to pull this off. Unfortunately, this logic does not work on universally on Windows because not all editions of Windows ship with `taskkill` (for example [Windows Nano](https://github.com/dotnet/cli/pull/1393#issuecomment-187815969)). Due to this limitation, `NativeMethodsShared`'s approach seems preferable.

**For Linux and macOS,** using aspnet Common's [Microsoft.Extensions.Internal.ProcessHelper]( https://github.com/aspnet/Common/blob/e0f40110ff5e2101231ba54d48961bbd60a07727/shared/Microsoft.Extensions.Process.Sources/ProcessHelper.cs#L19)/CLI's [Microsoft.DotNet.Tools.Test.Utilities.ProcessExtensions](https://github.com/dotnet/cli/blob/35e661bbb3b2f0943590cb63747ae53a68e6eb5d/test/Microsoft.DotNet.Tools.Tests.Utilities/Extensions/ProcessExtensions.cs#L27) UNIX-specific logic is an option though it might be preferable to skip starting a command-line process and instead use native calls to enumerate the process tree.

**Comment by rainersigwald** [comment]
I'm not aware of any problems with MSBuild's P/Invoke approach after the .NET Core port. Note that we only call it from https://github.com/Microsoft/msbuild/blob/cc451ea752ef6cfb04d9a3abab05f28f9a2fec41/src/Utilities/ProcessExtensions.cs#L14-L45 which has some cross-platform options that seem to be behaving ok.

**Comment by bgribaudo** [comment]
> So @bgribaudo do you want to take a shot at the implementation? Even just one of Windows and Linux if you want.

Yes, I'll be glad to give this a try. :-)

**Comment by danmosemsft** [comment]
Yes I suggest copying https://github.com/Microsoft/msbuild/blob/master/src/Utilities/ProcessExtensions.cs#L14. If you have a Mac, or can host a Linux VM, either should be fine for testing Unix behavior.

**Comment by danmosemsft** [comment]
For the tests, I would take a look through the existing tests for Process/ProcessStartInfo etc and copy the pattern. Make sure you save your work before you test for bugs in your implementation of killing the process tree 😆

**Comment by bgribaudo** [comment]
@danmosemsft, do you have any ideas on how to do something like https://github.com/dotnet/corefx/blob/9f02f69e3d9a455ec7bd1927eae59f138f37112b/src/System.Diagnostics.Process/tests/ProcessWaitingTests.cs#L222-L241 but where the code that starts the root process (line 241) can get ahold of the process IDs of child 1, 2 & 3?

Unfortunately, I can't simply define variables for the PIDs in that outer scope then assign to those variables from within each child's create Func because "Field marshaling is not supported by RemoteInvoke".

**Context:**
Currently, I'm trying to use platform-specific test code to build up a small tree of processes for test  purposes. However, doing something like the above would be preferable because (it appears to be) simple and cross platform.

**Comment by krwq** [comment]
@bgribaudo I think you can communicate PIDs back to the main process through i.e. AnonymousPipe (that will require setting handle inheritance but I'd check first if this doesn't happen by default). One platform which might be slightly trickier to test than others is UWP - I think it should be fine to skip testing there for now (please file an issue on that if you decide to skip it).

**Comment by danmosemsft** [comment]
@bgribaudo RemoteInvoke can take input parameters, so long as they can be converted easily to strings.
Example: https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/tests/FileStream/LockUnlock.cs#L174

It passes them as command line parameters. On return, you can only get the return code, so for more, you'd have to use a file or pipe etc.

See src\CoreFx.Private.TestUtilities\src\System\Diagnostics\RemoteExecutorTestBase.cs for all the overloads.

**Comment by bgribaudo** [comment]
Thanks, @krwq & @danmosemsft!

**Comment by danmosemsft** [comment]
done.
