### ISSUE TITLE
Add support for decompresing data in ReadOnlySpan<byte> with Deflate algorithm

### ISSUE THREAD

**Issue by lukaskabrt** [dotnet/corefx#26242]
`System.IO.Compression` contains the `DeflateStream` class, that can decompress data from a stream. In case we have compressed data already loaded in a `ReadOnlySpan<byte>`, using `DeflateStream` might be little inefficient - we have to create a `MemoryStream` and this operation allocates a new array.

```c#
    function Decompress(ReadOnlySpan<byte> block) {
        using(var stream = new MemoryStream(block.ToArray())) {
            using(var deflateStream = new DeflateStream(stream, CompressionMode.Decompress)) {
                Data = ... read from deflateStream
            }
        }
   }
```

It would be great, if the Deflate algorithm is exposed in the way that supports processing data from `ReadOnlySpan<byte>`

**Comment by karelz** [comment]
cc @stephentoub @KrzysztofCwalina

**Comment by KrzysztofCwalina** [comment]
Yes, we have such APis in Brotli (see https://github.com/dotnet/corefx/issues/25785). We should add similar APIs to Deflate/GZip.

**Comment by stephentoub** [comment]
> In case we have compressed data already loaded in a ReadOnlySpan<byte>, using DeflateStream might be little inefficient - we have to create a MemoryStream and this operation allocates a new array.

That isn't the only option; you can create an UnmanagedMemoryStream from it (pinning the span with fixed) and then there's no extra array needed.

And if you have the data as a Memory instead of a Span, you can either do that or create a MemoryStream that wraps the original array of TryGetArray returns one.

**Comment by karelz** [comment]
Duplicate of #7570
