### ISSUE TITLE
AssemblyLoadContext.Default.Unloading not triggered when using Windows Containers

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/corefx#26246]
@benjaminpetit commented on [Thu Jan 04 2018](https://github.com/dotnet/dotnet-docker/issues/354)

In order to shutdown properly, our app needs to be notified.

Using the Linux container we rely on `AssemblyLoadContext.Default.Unloading`, and works fine. But it seems that this event is not triggered and our app is killed almost instantaneously.

Program.cs

``` csharp
using System;
using System.Runtime.Loader;
using System.Threading;

namespace ConsoleApp2
{
    class Program
    {
        private static ManualResetEvent resetEvent = new ManualResetEvent(false); 

        static void Main(string[] args)
        {
            Console.WriteLine("Hello world");

            AssemblyLoadContext.Default.Unloading += context =>
            {
                Console.WriteLine("AssemblyLoadContext.Default.Unloading fired");
                resetEvent.Set();
            };

            resetEvent.WaitOne();
            Console.WriteLine("Goodbye");
        }
    }
}
```

Dockerfile:

``` Dockerfile
FROM microsoft/dotnet:runtime

WORKDIR /app
COPY publish/* ./

ENTRYPOINT ["dotnet", "ConsoleApp2.dll"]
```

## Steps to reproduce the issue
1. Start the container
2. Stop it with `docker stop xxx`

## Expected behavior
`AssemblyLoadContext.Default.Unloading` should be called before stopping.

## Actual behavior
`AssemblyLoadContext.Default.Unloading` is not be called

## Additional information (e.g. issue happens only occasionally)
Works fine using Linux containers

## Output of `docker version`

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:50:27 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

## Output of `docker info`

```
Containers: 35
 Running: 0
 Paused: 0
 Stopped: 35
Images: 123
Server Version: 17.09.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 12
Total Memory: 63.91GiB
Name: bpetit-devbox
ID: JTJR:4R47:HTCC:RW4Y:PBS5:HYLT:DDBT:7IDJ:6CIN:7LZB:MMRK:HZPH
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 31
 System Time: 2018-01-04T16:06:40.9929602-08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by karelz** [comment]
Is it a problem of just a specific Linux container? Or how else should I understand the comment above "Works fine using Linux containers".

**Comment by jkotas** [comment]
> Is it a problem of just a specific Linux container? 

@karelz Looking at the issue title, this is about Windows containers.

The Unloading event is delivered during graceful shutdown only. It is not delivered when the process is terminated ungracefully.

Linux containers receive SIGTERM signal when they are stopped. We treat SIGTERM signal as graceful shutdown and deliver the unloading event. https://github.com/dotnet/coreclr/issues/7394 has more context about this.

There is no SIGTERM Unix signal on Windows. There is likely some other scheme how the containers get stopped that are not cooperating with.

**Comment by benjaminpetit** [comment]
Any workaround that we could implement ourself to get notified when the container should stop?

We really can't use Windows container until we have a solution for this.

**Comment by karelz** [comment]
The question is how a native (C/C++) application on Windows would get the notification. Once you know that, you can PInvoke into the same OS APIs and we could implement it in CoreCLR as well.

[`docker stop` documentation](https://docs.docker.com/engine/reference/commandline/stop/) does not say what it does on Windows. I have found only some hints [here](https://social.msdn.microsoft.com/Forums/en-US/dc046e66-eec1-4ba8-a492-dde2b61dd581/how-does-docker-stop-containers?forum=windowscontainers).

**Comment by jkotas** [comment]
https://gist.github.com/darrenstahlmsft/fbb80c265dcfd1b327aabcc0f3554e56 shows how to handle shutdown notification in Windows containers.

**Comment by OnurGumus** [comment]
I still observe the same problem.
