### ISSUE TITLE
NetworkInterface.Description is not useful on Linux

### ISSUE THREAD

**Issue by JohnRusk** [dotnet/corefx#26248]
I see that, in #8297, the decision was been made for this property to just return the name of the interface, on Linux.  E.g. "eth0", whereas on Windows it returns a useful description of the make and model of the interface card.  It was also mentioned in that same issue, that the description could be improved in the future.

Is there any possibility now of improving it to make it work more like the Windows version?  I'm writing a data transfer tool, which logs information about the environment it runs in. A meaningful description of the network adapter would be very useful.

Or, if there's no possibility of improving it, could the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.networkinterface.description?view=netframework-4.7.1#System_Net_NetworkInformation_NetworkInterface_Description) please be changed to reflect the different behavior on Linux?  Right now the documentation says "human-readable text that typically describes the interface vendor, type (for example, Ethernet), brand, and model", which is definitely not the case on Linux at present.

**Comment by danmosemsft** [comment]
cc @tmds who opened the other issue.

**Comment by karelz** [comment]
Sounds like we can't improve it in the code :(.
@JohnRusk do you want to submit a PR into docs repo to clarify Linux behavior? (edit button on the document link you provided)

**Comment by danmosemsft** [comment]
Maybe it could prefer the better description if it was available?

**Comment by karelz** [comment]
Do we use any other optional external tools from CoreFX? How do we /would we consume such tools? Static dependency vs. starting new process and parsing output?
AFAIK we try to minimize static dependencies. Parsing tool output seems pretty fishy.

**Comment by JohnRusk** [comment]
Yeah, sounds like this has to be treated as a documentation issue.  I'll submit a doc PR next week.

**Comment by JohnRusk** [comment]
Thanks all, for the explanation.

**Comment by karelz** [comment]
Sounds good, thanks for pointing it out @JohnRusk! Closing here.
If anyone has idea how to solve it in code, we can reopen.

**Comment by JohnRusk** [comment]
Is there any way to get a pci id through the existing .NET Core API?  I just realized I only need the IDs.  My users don't need the names, and I'm only using them for diagnostic purposes. I could find a way to translate the ID to a name if I had to.
