### ISSUE TITLE
GetEnumerator() Fails on Some Interop w/netcoreapp2.0

### ISSUE THREAD

**Issue by Evmaus-MS** [dotnet/corefx#26257]
Hey--

I'm working on porting a tool that interacts with the DIA SDK to the netcoreapp2.0 framework (https://github.com/Microsoft/binskim), and ran into an interesting exception/problem.

IDiaEnumTables's System._ComObject representation exposes a GetEnumerator() function, which I assume probably winds up wrapping HRESULT get__NewEnum() (https://docs.microsoft.com/en-us/visualstudio/debugger/debug-interface-access/idiaenumtables-get-newenum) internally.  However, calling that function in a netcoreapp2.0 version of our tool throws an exception about missing the CustomMarshallers library:

```
System.IO.FileNotFoundException occurred
  HResult=0x80070002
  Message=Could not load file or assembly 'CustomMarshalers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.StubHelpers.StubHelpers.CreateCustomMarshalerHelper(IntPtr pMD, Int32 paramToken, IntPtr hndManagedType)
   at Dia2Lib.IDiaEnumTables.GetEnumerator()
   at Microsoft.CodeAnalysis.BinaryParsers.ProgramDatabase.Pdb.CreateDiaTable[T]() in ...\binskim\src\BinaryParsers\ProgramDatabase\Pdb.cs:line 234
```

This works if the main executable is using .NET 4.6.1--however I'm not able to find any documentation on how the interop services handle creating enumerators that suggests this isn't supported in netcoreapp2.0.

----
This appears to be happening for a number of other DIA SDK enumeration objects. Other functionality on the objects (e.x. .Count, .Item(index), etc.) all seem to work as expected--it's just the GetEnumerator() function that isn't working.

Let me know if you need anything else--I can see about creating a minimal test case or similar if it's necessary/helpful.

Thanks,
Everett Maus

[edited by @danmosemsft for formatting]

**Comment by danmosemsft** [comment]
Is this relevant? https://github.com/Microsoft/binskim/issues/109

**Comment by Evmaus-MS** [comment]
Yes, although that's just the issue tracking the porting work--there isn't any relevant information to this particular exception/unexpected behavior in that issue.

The exact code changes that remove this issue are now available here: 
 https://github.com/Microsoft/binskim/commit/cb0df5e2336167691d30e07e3fdd2f6ea0409988

**Comment by Priya91** [comment]
Is there any progress on this? Hitting this in .net core when trying to access com objects for iterating through the firewall rules on windows. There's no way to workaround this, as INetFwRules.Item(string processName), gives the first rule for the process which is not what I want to check.

**Comment by jeffschwMSFT** [comment]
@luqunl looked into this issue earlier in the week.  Depending on your scenario there is likely a code workaround that may work while we determine the right fix.  Here is a snippet of the code pattern shared to help @Priya91 ...
Define the interface manually:
[Guid("9C4C6277-5027-441E-AFAE-CA1F542DA009"), TypeLibType(4160)]
    public interface INetFwRules : IEnumerable
    {
       …
        [DispId(-4)]
        IEnumVARIANT get__NewEnum();
}
Define IEnumVariant:
namespace System.Runtime.InteropServices.ComTypes
    {
       [Guid("00020404-0000-0000-C000-000000000046")]
        [InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIUnknown)]
        [ComImport]
        public interface IEnumVARIANT
        {
            [PreserveSig]
            int Next(int celt, [MarshalAs(UnmanagedType.LPArray, SizeParamIndex = 0), Out] object[] rgVar, IntPtr pceltFetched);

            [PreserveSig]
            int Skip(int celt);

            [PreserveSig]
            int Reset();

            IEnumVARIANT Clone();
        }
}
Retrieve the interface:
var fwPolicy2 = (INetFwPolicy2)Activator.CreateInstance(Type.GetTypeFromProgID("HNetCfg.FwPolicy2"));

            var rules = fwPolicy2.Rules;
        
            // Fetch IEnumVARIANT interface
            System.Runtime.InteropServices.ComTypes.IEnumVARIANT enumVARIANT = rules.get__NewEnum();

Depending on your specific scenario these steps will be different.

**Comment by falahati** [comment]
Any update on this?

**Comment by jeffschwMSFT** [comment]
@falahati we are working through deeper Windows COM scenarios for .NET Core 3.0.

**Comment by falahati** [comment]
Thanks, @jeffschwMSFT for answering so fast.

So we can expect a more complete support for WinCOM objects (or marshaling in general) on NetCore3 or a better rewrite and maybe with multiple missing features?

Meanwhile, I might be able to take a look at this issue, the whole `System.Runtime.InteropServices.CustomMarshalers` interface contains 4 classes (based on MSDN) and `EnumeratorToEnumVariantMarshaler` and `EnumerableToDispatchMarshaler` are by far the important ones. Any suggestion on that?

**Comment by jeffschwMSFT** [comment]
Custom marshalers are in scope for 3.0.  

cc @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
@falahati and @Evmaus-MS This is being actively worked on my @jkoritzinsky. The relevant PR is dotnet/coreclr#21343.

@jkoritzinsky I believe you tested the above scenario, can you confirm that?

**Comment by nebosite** [comment]
@jkoritzinsky - Cool, will this generically solve all errors of "System.PlatformNotSupportedException: IDispatch and IDispatchEx are not supported"?

I am current hitting this error trying to enumerate outlook folders from a netcoreapp.

**Comment by jkoritzinsky** [comment]
@AaronRobinsonMSFT Yep!

@nebosite You shouldn't be seeing that error in a .NET Core app any more in the nightly builds of CoreCLR.

**Comment by jkoritzinsky** [comment]
Yeah this didn't make the 3.0 Preview 1 deadline. I don't think there's a nightly build since the preview yet either. I'd suggest waiting until the next Preview release which should have these changes in. You could build from master, but it's not straightforward to build a full dotnet.exe and runtime from the repos manually.

**Comment by falahati** [comment]
Hey @jkoritzinsky, is there an expected release date for Prev2, RC or final release?

**Comment by danmosemsft** [comment]
@falahati I don't believe we've shared hard dates.

**Comment by danmosemsft** [comment]
You can install bits from master though 
https://github.com/dotnet/sdk

**Comment by jjxtra** [comment]
This works for me. The IntPtr parameter does not receive the count, but if you have a null anywhere that means you are at the end. IEnumVARIANT is built in with .NET core 2.2.

```
    [ComImport]
    [Guid("9C4C6277-5027-441E-AFAE-CA1F542DA009")]
    [TypeLibType(4160)]
    public interface INetFwRules : IEnumerable
    {
        [DispId(1)]
        int Count
        {
            [MethodImpl(MethodImplOptions.InternalCall)]
            [DispId(1)]
            get;
        }

        [MethodImpl(MethodImplOptions.InternalCall)]
        [DispId(2)]
        void Add([In] [MarshalAs(UnmanagedType.Interface)] INetFwRule rule);

        [MethodImpl(MethodImplOptions.InternalCall)]
        [DispId(3)]
        void Remove([In] [MarshalAs(UnmanagedType.BStr)] string Name);

        [MethodImpl(MethodImplOptions.InternalCall)]
        [DispId(4)]
        [return: MarshalAs(UnmanagedType.Interface)]
        INetFwRule Item([In] [MarshalAs(UnmanagedType.BStr)] string Name);

        [DispId(-4)]
        System.Runtime.InteropServices.ComTypes.IEnumVARIANT GetEnumeratorVariant();

        /*
        [MethodImpl(MethodImplOptions.InternalCall)]
        [DispId(-4)]
        [TypeLibFunc(1)]
        [return: MarshalAs(UnmanagedType.CustomMarshaler, MarshalType = "System.Runtime.InteropServices.CustomMarshalers.EnumeratorToEnumVariantMarshaler")]
        new IEnumerator GetEnumerator();
        */
    }

    var e = policy.Rules.GetEnumeratorVariant();
    object[] results = new object[64];
    IntPtr useless = new IntPtr();
    string prefix = "*"; // or a rule name prefix

    while (true)
    {
        e.Next(results.Length, results, useless);
        foreach (object o in results)
        {
            if (!(o is INetFwRule rule))
            {
                break;
            }
            else if (prefix == "*" || rule.Name.StartsWith(prefix))
            {
                yield return rule;
            }
        }
    }
```

**Comment by falahati** [comment]
@jjxtra 
To get the length you should allocate some memory before calling the method.

```C#
                var bufferLengthPointer = Marshal.AllocCoTaskMem(Marshal.SizeOf(typeof(Int32)));
                enumVariant.Next(buffer.Length, buffer, bufferLengthPointer);
                var len = Marshal.ReadInt32(bufferLengthPointer);
                Marshal.FreeCoTaskMem(bufferLengthPointer);
```

**Comment by jjxtra** [comment]
Gotcha. I thought it would just set the pointer address to the count. I updated my comment.

**Comment by jkotas** [comment]
> I thought it would just set the pointer address to the count.

Right, that would be a much leaner way to do this. Allocating and freeing a small piece of memory works too, but it is like 100x more expensive.

**Comment by falahati** [comment]
The best way would have been a `ref int count` parameter handled by marshalling.

**Comment by jjxtra** [comment]
Yes agreed.
