### ISSUE TITLE
System.Runtime.Caching.Tests.TimedExpirationAsync test failed in PR

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#26258]
```
Unhandled Exception of Type Xunit.Sdk.NotNullException
Message :
Assert.NotNull() Failure
Stack Trace :
   at MonoTests.System.Runtime.Caching.MemoryCacheTestExpires11.<TimedExpirationAsync>d__0.MoveNext() in D:\j\workspace\windows-TGrou---db113413\src\System.Runtime.Caching\tests\System.Runtime.Caching\MemoryCacheTest.cs:line 1170
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by Priya91** [comment]
https://mc.dot.net/#/user/Priya91/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/59424952ec2d8fc2beebdd9fd460803259f5c9dd/workItem/System.Runtime.Caching.Tests/analysis/xunit/MonoTests.System.Runtime.Caching.MemoryCacheTestExpires11~2FTimedExpirationAsync

**Comment by danmosemsft** [comment]
@KKhurin there are a bunch of sleeps in this test. Can it be made more robust? Either by increasing sleeps (ideally sleeping extra only on failure) or some more robust means
