### ISSUE TITLE
EF "_Result" post-fiz anti pattern

### ISSUE THREAD

**Issue by daniel-filipe-lobo** [dotnet/corefx#26267]
Hi!
Sorry for the bother, but in the file:
referencesource/System.Data.Entity.Design/System/Data/Entity/Design/EntityModelSchemaGenerator.cs

there is this line:
string name = CreateModelName(functionImportName + **"_Result"**, session.UsedGlobalModelTypeNames);

Why is it hard-coded an anti pattern for a class name post-fix?
Can´t this be a configurable property?

Thanks for your attention.

**Comment by Clockwork-Muse** [comment]
I take it you've never seen the output from a SOA Designer in full swing.

The practice comes from expecting that the type being returned isn't necessarily the type being submitted to an API, and vice versa.  Among other wrinkles.

**Comment by karelz** [comment]
I guess https://github.com/aspnet/EntityFrameworkCore is the closest repo for your question.
That said, you're asking about .NET Framework, which we do not track in general on GitHub - cc @divega for guidance where to ask.

Closing as it is not CoreFX issue/question.
