### ISSUE TITLE
XmlWriter.WriteStartElement

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#26271]
_From @Looooooka on January 11, 2018 11:48_

Using 
writer.WriteStartElement("prefix:elementname");
used to work. one didn't have to use the overload 

writer.WriteStartElement("localname", "ns");
now it throws an exception.
A bunch of plugins and libraries that could be ported simply by including the cs file are not incompatible because of this minor change.
In my case xml plugins for log4net formatter
I think simply using the same behavior as before could fix a lot of unnecessary rewrites. 
No need to be that strict with overloads

_Copied from original issue: dotnet/coreclr#15826_

**Comment by Looooooka** [comment]
"not compatible"

**Comment by danmosemsft** [comment]
@Looooooka could you provide a simple repro?

.NET Core and .NET Framework both give:
```
Unhandled Exception: System.ArgumentException: Invalid name character in 'prefix:elementname'. The ':' character, hexadecimal value 0x3A, cannot be included in a name.
   at System.Xml.XmlWellFormedWriter.CheckNCName(String ncname)
   at System.Xml.XmlWellFormedWriter.WriteStartElement(String prefix, String localName, String ns)
   at ConsoleApp41.Program.Main(String[] args)
```

**Comment by krwq** [comment]
@Looooooka, closing this as no repro. If you got an example please paste here and reopen.
