### ISSUE TITLE
WebSocketProtocol_CreateFromConnectedStream_Succeeds fails at ReceiveAsync

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#26288]
This issue tracks to fix the test.

**Comment by stephentoub** [comment]
What's wrong with the test? If it's working currently, wouldn't that suggest a product issue as part of changing the implementation?

**Comment by Priya91** [comment]
> If it's working currently

It's not working currently, it fails from the beginning of time, without the change in the proposed PR.

**Comment by stephentoub** [comment]
What fails? Plenty of WebSocket tests use ReceiveAsync. What's the test that's been failing some the beginning of time and that uses ReceiveAsync?

**Comment by Priya91** [comment]
@stephentoub I think you misunderstood, I added this test recently with the ManagedWebSocket PR, the test uses WebSocketProtocol.CreateFromStream which uses the same codepath as WebSocket.CreateFromStream. All the existing tests in our repo, test with ClientWebSocket, which eventually uses WebSocket.CreateFromStream in the implementation. But as far as I checked there are no tests that directly call WebSocket.CreateFromStream. When I added a new test to just test WebSocket.CreateFromStream without using clientwebsocket, it fails, Either my test is wrong, or there's some product issue, which requires investigation, hence the tracking issue.

**Comment by stephentoub** [comment]
I see.  I did misunderstand.  And it's definitely the test that's faulty.  See my comment here:
https://github.com/dotnet/corefx/pull/26296/files#r161290252

**Comment by stephentoub** [comment]
@Priya91, can this be closed now?

**Comment by Priya91** [comment]
Yeah, this was fixed..

**Comment by danmosemsft** [comment]
@Priya91 when was this fixed? It failed in the UWP F5 run just a few hours ago:

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20180120.01/workItem/System.Net.WebSockets.WebSocketProtocol.Tests/analysis/xunit/System.Net.WebSockets.Tests.WebSocketProtocolTests~2FWebSocketProtocol_CreateFromConnectedStream_Succeeds(echoUri:%20ws:~2F~2Fcorefx-net.cloudapp.net~2FWebSocket~2FEchoWebSocket.ashx)
