### ISSUE TITLE
OS builds matrix in README.md

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#26290]
The matrix is getting out of date. It should be scrubbed and updated to match the current state of the world and our builds.

**Comment by tarekgh** [comment]
@karelz who can help with this issue?

**Comment by ianhays** [comment]
closing this as a dup of the more descriptive https://github.com/dotnet/corefx/issues/27130 which depends on https://github.com/dotnet/core-eng/issues/1901.
