### ISSUE TITLE
String.IndexOf gives different behavior on windows vs linux with ascii

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#26293]
@jmazar commented on [Thu Jan 11 2018](https://github.com/dotnet/core/issues/1213)

I am using .net core sdk 2.0.0 (I also tried on 2.1.2 with the same result) on Windows 10 and Ubuntu 17.10.

Here is a quick gist of my reproduction https://gist.github.com/jmazar/b0cdad1ee122afa64518953b22ae8136
```c#
string a = "8=FIX.4.29=17135=A";
int pos = 0;
int tagend = a.IndexOf("=", pos);
Console.WriteLine("tagend " + tagend);
int tag = Convert.ToInt32(a.Substring(pos, tagend - pos));
pos = tagend + 1;
int fieldvalend = a.IndexOf("\u0001", pos);
Console.WriteLine("fieldvalend "+ fieldvalend);

pos = fieldvalend + 1;
Console.WriteLine("pos " + pos);
```

On windows the fieldvalend prints out 9 (which is correct) but on linux it prints out 2 (which is incorrect). Is there something I am doing incorrectly or is there some setting I could try setting?

Thank you!

[EDIT] Include the gist inline by @karelz

**Comment by karelz** [comment]
Here's minimal repro:
```c#
Console.WriteLine("a\u0001".IndexOf("\u0001"));
```

Result:
* Windows - 1 (correct)
* Linux - 0 (incorrect)

**Comment by benaadams** [comment]
Linux character sorting behavior? https://github.com/dotnet/coreclr/issues/14066#issuecomment-330913921
Need to use `StringComparison.Ordinal`?
/cc @tarekgh

**Comment by ViktorHofer** [comment]
As Tarek stated this seems to be by design. Using `string.IndexOf(string, StringComparison.Ordinal)` should solve the reported issue

**Comment by tarekgh** [comment]
@benaadams is right, you need to use Ordinal to get the desired behavior. if you are not doing it ordinal (I mean you are doing it linguistically) this will be by design as we use the underlying OS library to perform the sorting operation.

**Comment by karelz** [comment]
Out of curiosity for me: How is sorting involved in `IndexOf`? Do we call into OS for `IndexOf` functionality?
Is there a description which characters are 'weird' / handled differently on OSs? Is it just the control characters (0-31)?

**Comment by tarekgh** [comment]
> Out of curiosity for me: How is sorting involved in IndexOf? 

Yes. IndexOf is not different than string comparisons. so if you are using culture operations, you'll get the behavior of such culture. if not passing Ordinal, then the current culture will be used. 

> Do we call into OS for IndexOf functionality?
Yes. we do.

> Is there a description which characters are 'weird' / handled differently on OSs? Is it just the control characters (0-31)?

It is not the control characters only. one example is when using Turkish culture and having character "i" in your string, will get different behavior than when using other culture (e.g. en-US).

**Comment by TheodorKleynhans** [comment]
If the intent was just to find the ordinal index of a single character, I think it would be better (and probably faster) to use the `IndexOf` overloads that take a `char` instead of a `string`, e.g. `string.IndexOf(Char, int, int)`.
