### ISSUE TITLE
SqlDataReader.HasRows high cpu utilization

### ISSUE THREAD

**Issue by relgram** [dotnet/corefx#26297]
There appears to be a heavy performance cost of adding SqlDataReader.HasRows while using ExecuteReader

60% CPU
```c#
using ( var reader = command.ExecuteReader() )
{
    while (reader.HasRows == true)
    {
        while ( reader.Read() == true )
        {
            // do something
        }
    }    
}
```

vs.

0%
```c#
using ( var reader = command.ExecuteReader() )
{
    while ( reader.Read() == true )
    {
        // do something
    }  
}
```

[EDIT] Add C# syntax highlighting by @karelz

**Comment by EgorBo** [comment]
@relgram the codes don't look the same, is not the first snippet an infinite loop?

**Comment by relgram** [comment]
Ahhh yes, you're correct.  While HasRows should be changed to If
