### ISSUE TITLE
cant start safari by ProcessStartInfo under macos 10.13.2

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#26294]
_From @bodhichina on January 12, 2018 13:50_

 i try run below code under macos 10.13.2, looks nothing happend. can you help to check what's wrong

```
var info=new ProcessStartInfo()
            { 
                FileName = "/Applications/Safari.app/Contents/MacOS/safari",
                CreateNoWindow = false,
                UseShellExecute = false
            };
            
            var process=new Process(){ StartInfo = info};
            process.Start();
```

_Copied from original issue: dotnet/coreclr#15839_

**Comment by wtgodbe** [comment]
I am not able to repro this locally @bodhichina, can you provide more details? Did you confirm Safari is where you expect it to be?

**Comment by karelz** [comment]
Looks like this is not actionable now. Closing.
If you have repro, feel free to ping us and we can reopen. Thanks!
