### ISSUE TITLE
Span: Provide ToString

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#26295]
Forked from https://github.com/dotnet/corefx/issues/14376

Work item here is to implement ToString on Span/ReadOnlySpan and have it print out a string similar to what a collection would print out (which is just the object tostring - type + address)

cc: @KrzysztofCwalina @jkotas @ahsonkhan to continue the discussion on ToString here.

**Comment by ianhays** [comment]
The crux of the issue is that there currently isn't any ToString available for either Span or ReadonlySpan. The question isn't so much whether the `ToString` should print something **valuable** as much as it is a question of whether it should be available *at all*. 

```new ReadOnlySpan<byte>().ToString()``` currently causes a compile error: ```error CS0029: Cannot implicitly convert type 'System.ReadOnlySpan<byte>' to 'System.ValueType'```

It should instead compile and just print something basic e.g. ```System.ReadOnlySpan[{span.length}]```

**Comment by jkotas** [comment]
The same problem exists for all `ref` types (unless they override ToString). Do you believe that fixing this problem just for Span is worth it?

**Comment by ianhays** [comment]
> The same problem exists for all ref types (unless they override ToString).

Yes, the problem is present in all ref types. 

What do you mean by `override Tostring`? From what parent does a ref type inherit a `ToString` to override? Or did you just mean implement ToString on the class directly?

>Do you believe that fixing this problem just for Span is worth it?

I think it is worthwhile to ease adoption of the type, yes. In the world where *almost* everything can be `ToString`ed (including `Memory` and `ReadOnlyMemory`), it's better to adhere to that pattern even without the common parent.

**Comment by jkotas** [comment]
>  From what parent does a ref type inherit a ToString to override?

From `System.ValueType`. `System.ValueType` is parent of all structs.

Why do you think this will ease adoption of Span? I think `ref` types come with number of restrictions that are much more in peoples face than not being able to call ToString.

We have dummy overrides for GetHashCode and Equals on Span already, so I guess we can have implementation of ToString as well...

**Comment by ianhays** [comment]
>From System.ValueType. System.ValueType is parent of all structs.

Interesting, I didn't think ValueType was a parent of a ref struct. So in that case, what is happening to the ToString that is being inherited from `ValueType`? We're not explicitly hiding it, so shouldn't the [GetType implementation in ValueType](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/ValueType.cs#L91) be usable from`Span` already?

Further, why is it that a `Span` cannot be used as a `ValueType`? To do so results in a ` error CS0029: Cannot implicitly convert type 'System.ReadOnlySpan<byte>' to 'System.ValueType'`. Does being a `ref` type dismiss that types ability to act polymorphically as its parent?

>I think ref types come with number of restrictions that are much more in peoples face than not being able to call ToString.

True. My point of view is that it's better to lessen those restrictions rather than increase them, though it's very unlikely that ToString is going to be the blocking piece.

**Comment by jkotas** [comment]
Calling `ValueTuple.ToString` on a Span would require boxing. Boxing is not allowed on ref types. `span.ToString()` basically expands into:

```
ValueType o = (ValueType)span; // You will get the same error on this line
o.ToString();
```

You will get similar error when you try to do `Console.WriteLine(span)` for the same reason, even though you can do `Console.WriteLine` on *almost* everything else.

**Comment by ianhays** [comment]
>Boxing is not allowed on ref types. 

Ah gotcha, that was the bit I was missing. Thanks for the explanation.
