### ISSUE TITLE
Update UAP TFM on master branch to be vNext

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#26305]
As we get ready to ship .NET Core 2.1, we need to make sure that we rev up the version of UAP vnext on our master branch since we shouldn't ship OOB packages that have a uap asset with the old TFM. Because we haven't done this yet, we are currently seeing problems trying to consume OOB packages in UWP like the one described here #25024 about System.Memory package. Once that is fixed, we should be able to consume packages like System.Memory again.

@joshfree I suppose we don't know yet what will the next UAP TFM be, but is it safe to just use 10.0.RS3+1 for now? (16299 + 1 = 10.0.16300). 

cc: @weshaggard

**Comment by weshaggard** [comment]
We need to do the same thing in core-setup branch as well.

**Comment by joshfree** [comment]
@lt72 @zamont can you PTAL?  @joperezr yes, I'd use RS3+1 for now.

**Comment by joperezr** [comment]
Ok, I'll take a look into doing it for corefx + core-setup repos

**Comment by weshaggard** [comment]
@joperezr what work is left to fix this?

**Comment by joperezr** [comment]
We still have to take care of this on dotnet/standard repo and dotnet/wcf repo.  I'll try to get to it next week if there is no rush.

**Comment by weshaggard** [comment]
@joperezr were you able to finish the standard and wcf repo's?

**Comment by joperezr** [comment]
standard actually didn't really need a change, and I'm taking care of wcf now.

**Comment by joperezr** [comment]
PR for WCF is https://github.com/dotnet/wcf/pull/2649
