### ISSUE TITLE
Create an official ARM64 build for AOT UAP

### ISSUE THREAD

**Issue by sergiy-k** [dotnet/corefx#26308]
This is required to build ARM64 packages for ProjectN.

/cc: @weshaggard

**Comment by weshaggard** [comment]
Builds are out at https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.win10-arm64-aot.Microsoft.Private.CoreFx.UAP

**Comment by sergiy-k** [comment]
Thank you!
/cc: @AntonLapounov
