### ISSUE TITLE
It has same test cases in `SkipWhileTests.cs`

### ISSUE THREAD

**Issue by peterhpchen** [dotnet/corefx#26317]
When I was reading `SkipWhileTests.cs`, I was confused by this part:

https://github.com/dotnet/corefx/blob/58b5c181d3d47a3c2f75b602bb5153da9528a401/src/System.Linq/tests/SkipWhileTests.cs#L91-L125

`PredicateManyFalseOnSecond` and `PredicateManyFalseOnSecondInex` is completely the same.

`PredicateTrueOnSecondFalseOnFirstAndOthers` and `PredicateTrueOnSecondFalseOnFirstAndOthersIndex` is the same, too.

I think `predicate` of the Index test case should be: `(e, i) => i % 2 == 0`, and `expected` should be changed.

Any Idea?

Thank you.

**Comment by JonHanna** [comment]
Not quite. The predicate for the non-index cases was intended to be `e => e % 2 == 0` to match the cases translated in #2997. Also, `Inex` was a typo for `Index` there.

**Comment by JonHanna** [comment]
Nice catch BTW, it's the sort of thing where once one has read past it once without spotting the mistake, one will likely never spot it.
