### ISSUE TITLE
[ManagedHandler] Consider adding support for LF line termination when parsing response header

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#26326]
Per RFC: https://tools.ietf.org/html/rfc7230#section-3.5

"Although the line terminator for the start-line and header fields is the sequence CRLF, a recipient MAY recognize a single LF as a line terminator and ignore any preceding CR."

**Comment by Tratcher** [comment]
Compare to https://msdn.microsoft.com/en-us/library/system.net.configuration.httpwebrequestelement.useunsafeheaderparsing(v=vs.110).aspx

**Comment by geoffkizer** [comment]
Would be interesting to know what WinHTTP/Curl do here.

**Comment by wfurt** [comment]
Ive seen this once coming over the years. Yet I'm to see server sending LF only responses. 
(being server is different story)

**Comment by Tratcher** [comment]
I know WinINet/IE accept it by default. It's not common, but it does come up often enough that people need a workaround. Github's error page was the most recent server I've seen do it.

**Comment by geoffkizer** [comment]
I tested WinHttpHandler and CurlHandler, and they both seem to accept LF as a line terminator.  Seems like we should do the same.
