### ISSUE TITLE
Span and ReadOnlySpan methods are missing the PureAttribute

### ISSUE THREAD

**Issue by Ziriax** [dotnet/corefx#26320]
I'm very excited that `Span` is introduced in the lovely .NET framework!

However I get a lot of R# warnings when using it, since none of the pure `Span` nor `ReadOnlySpan` methods have the `PureAttribute`.

Is this 'pure' attribute obsolete?

**Comment by karelz** [comment]
[PureAttribute](https://msdn.microsoft.com/en-us/library/system.diagnostics.contracts.pureattribute(v=vs.110).aspx) is from Contracts. We gave up on those, they are basically obsolete.
R# should not reply on that attribute anymore. We stopped annotating BCL a long time ago with Contracts -- @weshaggard can provide more historical details.

**Comment by jkotas** [comment]
Related issues with the historical details: #24681 #15443 #11596

**Comment by Ziriax** [comment]
Thanks for the info and fast response.

Do you have plans to introduce a language replacement for the PureAttribute, like the const  mutable annotations in C++?

**Comment by jkotas** [comment]
Proposal: https://github.com/dotnet/csharplang/issues/1157
It is not in the list of currently planned features.
