### ISSUE TITLE
DirectoryInfo.ToString inconsistent with Desktop

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#2632]
On Desktop creating a DirectoryInfo with a full path returns a full path.  Creating a DirectoryInfo with a short path, or creating it from a parent (eg: CreateSubdirectory, EnumerateDirectories,etc) returns just the directory name.

On CoreCLR we are always trimming to just the directory name.

I traced this behavior back to an IFDEF in the original code https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/DirectoryInfo.cs#L639-L643.  It seems that the original CoreCLR implementation (Silverlight/phone) hardcoded the short name.

We should prefer the desktop behavior instead of the current. The current behavior is due to the legacy behavior of SL trying to sandbox the app. This is not a goal for CoreCLR and we don't have a back-compat burden for the current implementation.

We also need to examine similar cases in other FileSystem types.

**Comment by ericstj** [comment]
We should prefer the desktop behavior instead of the current.  The current behavior is due to the legacy behavior of SL trying to sandbox the app. This is not a goal for CoreCLR and we don't have a back-compat burden for the current implementation.

**Comment by ericstj** [comment]
We also need to examine similar cases in other FileSystem types.

**Comment by weshaggard** [comment]
This is actually causing some blocking issues with Powershell. @ericstj / @JeremyKuhne can one of you guys take a closer look at it.

**Comment by JeremyKuhne** [comment]
Resolved with #5437.
