### ISSUE TITLE
HttpListener on Unix. Windows authentication.

### ISSUE THREAD

**Issue by valeri2** [dotnet/corefx#26327]
Hello.
Are there plans to implement Windows authentication in HttpListener on Unix?
It is necessary to migrate my project on Linux.

**Comment by stephentoub** [comment]
There are no such plans.

**Comment by karelz** [comment]
HttpListener is consider legacy API, for compat-only. We recommend to use KestrelHttpServer for full cross-platform HTTP server API surface.

I have created https://github.com/dotnet/platform-compat/issues/88 to document the "obsoletion".

For more details see also our Networking Technical roadmap https://github.com/dotnet/designs/issues/9 (there is long discussion about this topic).
