### ISSUE TITLE
Flag `CreateNoWindow` does not work on linux

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#26337]
@maroallegro commented on [Wed Jan 10 2018](https://github.com/dotnet/core/issues/1206)

Used framework: .NET Core 2.0

Running below code on Windows opens new console window with program.dll running. When running below code on linux new console window is not opening. Seems like flag `CreateNoWindow = false` does not work.

    var process = new Process
    {

        StartInfo = new ProcessStartInfo
        {
            FileName = "dotnet",
            Arguments = "program.dll",
            UseShellExecute = true,
            RedirectStandardOutput = false,
            RedirectStandardError = false,
            CreateNoWindow = false
        }
    };

    process.Start();

Is it a bug?

How to open program.dll in new console window on Linux using .NET Core 2.0?

---

@wfurt commented on [Wed Jan 10 2018](https://github.com/dotnet/core/issues/1206#issuecomment-356673961)

How exactly do you execute this? I don't see new window when executed from simple app running in  xterm. Conceptually .NET Core does not have GUI functions - like opening window. It is possible that the windows is created by your desktop manager or something else. 

If you still think it is bug please provide full repro app and instructions how to run it.

---

@Petermarcu commented on [Wed Jan 10 2018](https://github.com/dotnet/core/issues/1206#issuecomment-356700112)

Isn't that what the issue is? On Windows, when you set "CreateNoWindow" to true is when you'd expect no new window. I think @maroallegro is wanting to create a new window so setting it to false. And it works that way on Windows.

---

@maroallegro commented on [Wed Jan 10 2018](https://github.com/dotnet/core/issues/1206#issuecomment-356712214)

@wfurt 

> How exactly do you execute this? 

On linux
`dotnet <scriptName.dll>
`

>  I don't see new window when executed from simple app running in xterm. 

And that is the problem :) Because that script opens new console window when runned on Windows System only.

> If you still think it is bug

I don't know, I just see the difference how program acts on Linux and Windows. I would like to open new window functionality on both systems. On linux I managed to open new console by running new instance of xterm but it seems as workaround for me if we have flag `CreateNoWindow = false`.

@Petermarcu exactly as you said, 

> @maroallegro is wanting to create a new window so setting it to false. And it works that way on Windows.

but on linux does not.

**Comment by danmosemsft** [comment]
We ignore this flag except on Windows. We just do `fork()` then `execve()` which do not have such flags. Is there anything mapping to this concept in Linux?

**Comment by wfurt** [comment]
Well, Linux console does not have concept of windows. So when you have console APP that is either attached to console or it can be detached and run in background. You can than have X11 (or gnome/KDE) implementing graphical interface. Bu than it is no longer console app. 

I understand that for windows users the difference may not be visible as windows always had concept of window.

**Comment by danmosemsft** [comment]
@maroallegro I'm going to close this as it's not clear it's possible.

**Comment by wojtpl2** [comment]
It should be described in documentation https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.createnowindow?view=netcore-2.0#System_Diagnostics_ProcessStartInfo_CreateNoWindow
