### ISSUE TITLE
[Proposal] Tuple.Create with params and/or collection names/values

### ISSUE THREAD

**Issue by generik0** [dotnet/corefx#26332]
Hi
(Not sure is this is in correct repo=?)

Love dotnet. Thanks! C#7 Tuples and TupleValues are great. But they appear to be missing a more dynamic element.

Any chance of getting:

```c#
Tuple.Create(params items);
ValueTuple.Create(params items)
```
and/or
```c#
Tuple.Create(IEnumerable<string> keys, IEnumerable<object> items);
```
where names are 

If:
- over 8 items, then throw an exception.
- keys.Count != names.Count throw exception

Regards G.

**Comment by JonHanna** [comment]
There would be no need to throw on more than 8 elements, as it could just nest tuples.

The names version wouldn't work as the names aren't a runtime feature.

This leaves the question of how much use a homogeneous typed tuple is, to make such factories useful.

**Comment by svick** [comment]
How would that work? What would be the return types of the methods you propose?

**Comment by JonHanna** [comment]
The return type would have to box, which kills a lot of the advantages of the types

**Comment by generik0** [comment]
Hi.
Really great questions!!!
I have found this to be an issue when using Classes that use generics.

E.g.public class FooFactory<T>.
The activator does not seam to be making the T correctly,
Hence I though a paras create would give me the possibility to make the ValueTuple.

So I gues the method should be e.g.
Value.Tuple.Create<T>(Items);

The the class could then be instanciated with:

var factory = new FooFactory<(int X, int Y);
var bar = factory.Create(items);

Then in the factory

Public T Create(items)
{
   return ValueTuple.Create<T>(items);
}

Regards G

**Comment by generik0** [comment]
Good new. Looks i was looking at it all wrong when using the Activator.
This appears to pass
```c#
[Test]
        public static void CreateInstance_WithConstructor()
        {
            var actual = CreateInstance<(MyClass Foo, MyClass Bar)>(new MyClass(), new MyClass());
            Assert.NotNull(actual);
            Assert.NotNull(actual.Bar);
            Assert.NotNull(actual.Foo);
        }

        private static T CreateInstance<T>(params object[] items)
        {
            return (T)Activator.CreateInstance(typeof(T), items);
        }
```

**Comment by Clockwork-Muse** [comment]
...okay, but your use example is the equivalent of the old joke:

> "'tnetennba'? Can you use that in a sentence?"
> "Sure!  'Good morning, that's a nice tnetennba.'"

...in particular, homogenous tuples are usually really lists of some sort, especially if you're creating them with dynamic size.

**Comment by generik0** [comment]
Your humor is above my IQ. I don’t get it.... Was it ment as an insult?

My example was just a factory pattern that could be used for nothing in particular other to proving that the Activator code make ValueTuples.

I am simply happy that the Activator can create ValueTuple’s. Even though it is a dynamic list of structs as you point out... 
Good work who made the Activator code....

**Comment by Clockwork-Muse** [comment]
...what I was getting at is that the example you show is a tautology, or circular definition.  What we'd rather see is a "real" use.  What is it you're doing where you have a list as input, but you really need a tuple, type of thing.  And we're immediately going to be suspicious of any tuple that's completely homogenous, since that usually means whatever it is should have _stayed_ a list.

This is all besides the fact that tuples, as a concept, are essentially a dynamic type; instead of writing an explicit return-type with two or more fields, just return this dynamic object.  In many cases of a homogenous tuple, what you really want is an actual permanent type of some sort (like position coordinates or some such).

**Comment by generik0** [comment]
Thanks for the clarification.

In real life the C#7 value tuples allow us to return named types wrapped in a strict from a public methods. So it seams to be ok OO practice to use valuetuples as return values.

These public interfaces/classes will be used in other classes, so the valuetuples will have to be mocked Mocked as return values when uTesting.

I use a Nbuilder for creating stubs for mock returns: NBuilder. It could not build the valuetuples,so I started to investigate. First I thought it was the Activator and started to look into how to build ValueTuples dynamically.
But it now seams there is just a Bug in NBuilder not using Activator to create structs (like ValueTuples) correctly. My test just proved that Activator can build ValueTuples where the types in the struct are constructor parameters...
Hence, yes the Activator can build structs, with the ValueTuple struct objects as params....

**Comment by generik0** [comment]
Anyway. I closed this issue/proposal.
And I don’t think we need to discuss the pro’s / con’s of ValueTuples and dynamic here.
Nor what is good OO practice or not.
There are plenty of forums for that.

The issue/ proposal was simply how to build ValueTuples via generics and dynamically..
And this can be done by the Activator.

I think people should decide for themselves what is best to use for there needs, a dynamically created ValueTuple struct or a dynamic  ;-)

Have a great day, and thanks for community input:-)
