### ISSUE TITLE
[Missing] CssEncode. Options?

### ISSUE THREAD

**Issue by Brij-Mishra** [dotnet/corefx#26346]
Hi All,

May Be I am missing something. But I was using the Microsoft.Security.Application.Encoder.CssEncode for CSS encoding but it is not available in System.Text.Encodings.Web. Are we going to add or it is not required. What is the best alternative? cc @stephentoub @jkotas

Thanks a lot in advance,
Brij

**Comment by jkotas** [comment]
This issue was moved to aspnet/Home#2784

**Comment by jkotas** [comment]
`Microsoft.Security.Application.Encoder.CssEncode` is part of ASP.NET AntiXss library https://wpl.codeplex.com/

The right place to ask about .NET Core equivalent is ASP.NET Core repo.

**Comment by Eilon** [comment]
I think they're asking about a feature request for System.Text.Encodings.Web, not about the ancient AntiXss library (which did have this feature).

**Comment by blowdart** [comment]
We merged those things we considered useful when we pulled AntiXSS into the .NET Framework. CSS encoding was not considered useful, because honestly the idea of allowing user input in CSS is kind of horrific and ought to be discouraged.

**Comment by tarekgh** [comment]
@Brij-Mishra could you tell more about your scenario? as @blowdart mentioned, this is discouraging to use. Thanks.

**Comment by Brij-Mishra** [comment]
Thanks a lot to all of you. I agree that allowing user input in CSS should be avoided. One of the teams in my organization, apporached me as they are moving to latest framework and I think they have some admin funcationality where they allow CSS input for some specifc scenarios.
I also see it was mentioned at quite few places at OWASP (like https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet)  so we may think of adding it sometime.

**Comment by tarekgh** [comment]
thanks, @Brij-Mishra. I am closing the issue per the discussion here.
