### ISSUE TITLE
"string.Join" method - inconsistent argument types

### ISSUE THREAD

**Issue by JosephDix** [dotnet/corefx#26347]
In .Net Core 2 class library, string.Join uses a char type as the separator but in .Net Standard 2 class library, the method uses a string type for the separator.

dotnet version: 2.1.4

![image](https://user-images.githubusercontent.com/7945637/34954386-2271c744-fa18-11e7-91ae-386de421f75a.png)

![image](https://user-images.githubusercontent.com/7945637/34954400-3af9d5b8-fa18-11e7-8834-a9a88198dac1.png)

**Comment by jnm2** [comment]
.NET Core has more APIs than .NET Standard, but there's no inconsistency. .NET Core has all the same overloads .NET Standard has: https://docs.microsoft.com/en-us/dotnet/api/system.string.join?view=netcore-2.0#System_String_Join_System_String_System_Collections_Generic_IEnumerable_System_String__
