### ISSUE TITLE
Semantic equals for BitArray

### ISSUE THREAD

**Issue by alexandrugyori** [dotnet/corefx#2636]
The Equals method of BitArray is inherited from Object. I believe most things in the Collections API have an Equals that is specific to the collection itself. I think it would be more intuitive for BitArray to have a proper Equals implementation.

In my understanding this test should pass but it currently fails:

void TestEquals()
 {
            BitArray b = new BitArray(251);
            Random r = new Random(234432);
            for (int i = 0; i < b.Count; i++)
            {
                b.Set(i, r.Next() % 2 == 0);
            }
            BitArray fresh = new BitArray(251);

            BitArray copy = b.Clone() as BitArray;

            b.Or(fresh);
            Debug.Assert(b.Equals(copy));
            b.Or(copy);
            Debug.Assert(b.Equals(copy));
}

**Comment by svick** [comment]
> I believe most things in the Collections API have an Equals that is specific to the collection itself.

Actually, they don't. The only collections in mscorlib that override `Equals()` are `ArraySegment<T>` and `string`, and both are special cases.

**Comment by alexandrugyori** [comment]
Ok. I was coming with that mindset from the java world.
I actually do think that a semantic Equals makes some sense for collection classes, but since this is not the convention, the issue should be probably closed.
