### ISSUE TITLE
NETFX x86rel Thread tests timeout

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#26360]
in PR https://github.com/dotnet/corefx/pull/26353

NETFX x86 Release Build leg 

https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/7047/console
```
07:16:12   === TEST EXECUTION SUMMARY ===
07:16:12      System.Threading.Thread.Tests  Total: 35, Errors: 0, Failed: 0, Skipped: 1, Time: 2.387s
07:16:12   Finished running tests.  End time= 7:16:12.65, Exit code = 0
08:56:25 Cancelling nested steps due to timeout
08:56:25 Sending interrupt signal to process
08:56:35 After 10s process did not stop
```

**Comment by stephentoub** [comment]
Haven't seen another failure here in over a year.  Closing.
