### ISSUE TITLE
Problem with build on android

### ISSUE THREAD

**Issue by meold** [dotnet/corefx#26362]
I have this output when building CoreFX for aarch64...
`CMake Error at /usr/share/cmake-3.5/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/usr/bin/clang-3.9" is not able to compile a simple test
  program.
  It fails with the following output:
   Change Dir: ~/git/corefx/bin/obj/Linux.arm64.Debug/native/CMakeFiles/CMakeTmp
  Run Build Command:"/usr/bin/make" "cmTC_f7c9e/fast"
  /usr/bin/make -f CMakeFiles/cmTC_f7c9e.dir/build.make
  CMakeFiles/cmTC_f7c9e.dir/build
  make[1]: Entering directory
  ~/git/corefx/bin/obj/Linux.arm64.Debug/native/CMakeFiles/CMakeTmp
  Building C object CMakeFiles/cmTC_f7c9e.dir/testCCompiler.c.o
  /usr/bin/clang-3.9 -isystem
  ~/git/corefx/cross/android-rootfs/toolchain/arm64/sysroot/usr/include
  -target aarch64-linux-gnu
  --sysroot=~/git/corefx/cross/android-rootfs/toolchain/arm64/sysroot
  -o CMakeFiles/cmTC_f7c9e.dir/testCCompiler.c.o -c
  ~/git/corefx/bin/obj/Linux.arm64.Debug/native/CMakeFiles/CMakeTmp/testCCompiler.c
  Linking C executable cmTC_f7c9e
  /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_f7c9e.dir/link.txt
  --verbose=1
  /usr/bin/clang-3.9 -target aarch64-linux-gnu -B
  ~/git/corefx/cross/android-rootfs/toolchain/arm64/sysroot/usr/lib/gcc/aarch64-linux-gnu
  -L~/git/corefx/cross/android-rootfs/toolchain/arm64/sysroot/lib/aarch64-linux-gnu
  --sysroot=~/git/corefx/cross/android-rootfs/toolchain/arm64/sysroot
  CMakeFiles/cmTC_f7c9e.dir/testCCompiler.c.o -o cmTC_f7c9e -rdynamic
  /usr/bin/aarch64-linux-gnu-ld: cannot find crt1.o: No such file or
  directory
  /usr/bin/aarch64-linux-gnu-ld: cannot find crti.o: No such file or
  directory
  /usr/bin/aarch64-linux-gnu-ld: cannot find crtbegin.o: No such file or
  directory
  /usr/bin/aarch64-linux-gnu-ld: cannot find -lgcc
  /usr/bin/aarch64-linux-gnu-ld: cannot find -lgcc_s
  /usr/bin/aarch64-linux-gnu-ld: cannot find -lgcc
  /usr/bin/aarch64-linux-gnu-ld: cannot find -lgcc_s
  /usr/bin/aarch64-linux-gnu-ld: cannot find crtend.o: No such file or
  directory
  /usr/bin/aarch64-linux-gnu-ld: cannot find crtn.o: No such file or
  directory
  clang: error: linker command failed with exit code 1 (use -v to see
  invocation)
  CMakeFiles/cmTC_f7c9e.dir/build.make:97: recipe for target cmTC_f7c9e
  failed
  make[1]: *** [cmTC_f7c9e] Error 1
  make[1]: Leaving directory
  ~/git/corefx/bin/obj/Linux.arm64.Debug/native/CMakeFiles/CMakeTmp
  Makefile:126: recipe for target cmTC_f7c9e/fast failed
  make: *** [cmTC_f7c9e/fast] Error 2
  CMake will not be able to correctly generate this project.
  Call Stack (most recent call first):
  CMakeLists.txt:2 (project)
-- Configuring incomplete, errors occurred!
See also "~/git/corefx/bin/obj/Linux.arm64.Debug/native/CMakeFiles/CMakeOutput.log".
See also "~/git/corefx/bin/obj/Linux.arm64.Debug/native/CMakeFiles/CMakeError.log".
Failed to generate native component build project!
Command execution failed with exit code 1.
 `

Any suggestions would very helpful.
Thanks.

**Comment by janvorli** [comment]
@meold I didn't hit this problem (but hit compilation issues later). Here is what I did:
* fix the library versions in the `cross/build-android-rootfs.sh` file to match what's available on the termux server now - see the https://gist.github.com/janvorli/71fdb426e6eebfc6b648ff6252d57b55
* build the rootfs in the corefx repo using `cross/build-android-rootfs.sh arm64`
* start build using the command the script has printed at the end

The compiler is correctly identified, the build starts, but fails due to some differences in the android headers that will need to be handled to make the build pass.

**Comment by meold** [comment]
@janvorli, I did the following:
1. fix the library versions in `cross/build-android-rootfs.sh` like [this](https://gist.github.com/janvorli/71fdb426e6eebfc6b648ff6252d57b55)
2. build using `cross/build-android-rootfs.sh arm64`
3. start building using the command `CONFIG_DIR=realpath ~/git/corefx/cross/android/arm64 ROOTFS_DIR=realpath ~/git/corefx/cross/android-rootfs/toolchain/arm64/sysroot ./build-native.sh         -debug -buildArch=arm64 -- verbose cross`

But get the same error(which described above).

Any suggestions would very helpful.
Thanks.

**Comment by janvorli** [comment]
@meold, can you please try to delete the `bin` folder and retry the build? Sometimes cmake remembers compiler version from previous build attempts. I have noticed that in my case, the clang version used to build is 3.8.275480 and it comes from the cross fs. See:
```
-- The C compiler identification is Clang 3.8.275480
-- The CXX compiler identification is Clang 3.8.275480
-- Check for working C compiler: /home/janvorli/git/corefx/cross/android-rootfs/toolchain/arm64/bin/aarch64-linux-android-clang
-- Check for working C compiler: /home/janvorli/git/corefx/cross/android-rootfs/toolchain/arm64/bin/aarch64-linux-android-clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/janvorli/git/corefx/cross/android-rootfs/toolchain/arm64/bin/aarch64-linux-android-clang++
-- Check for working CXX compiler: /home/janvorli/git/corefx/cross/android-rootfs/toolchain/arm64/bin/aarch64-linux-android-clang++ -- works

```
Also, in the build command in your comment above, you are missing the backticks around the realpath ~/git/corefx/cross/android-rootfs/toolchain/arm64/sysroot and realpath ~/git/corefx/cross/android/arm64. I assume you have removed them just for the purpose of the comment here so that you can put the command line inside the backticks and you have actually used them on your command line, right?

**Comment by janvorli** [comment]
@meold now we are getting the same results. As I have mentioned in one of my previous comments, these things need to be fixed - Android headers have different data types of members in some structs.

**Comment by jkotas** [comment]
Adding `int64_t` cast to `ST_NTIME_NSEC` should be fine.

cc @danmosemsft

**Comment by meold** [comment]
@jkotas @janvorli, okey, I fixed this errors and few others.
But get this: 
![image](https://user-images.githubusercontent.com/28731421/35069477-ef34b644-fbe2-11e7-857d-40c6bd27888e.png)

Can you help me with it?

**Comment by jkotas** [comment]
SafeStringCopy in `src/Native/Unix/Common/pal_utilities.h` needs to be moved out from `__cplusplus` ifdef. E.g. you can try moving `#endif // __cplusplus` before it.

**Comment by danmosemsft** [comment]
Is there any plan to get Android coverage in official builds to stop this kind of issue upstream? I assume not currently planned so breaks will happen now and then.

**Comment by janvorli** [comment]
There is no plan as far as I know.

**Comment by wtgodbe** [comment]
@meold I'm closing this as it looks to be stale/a solution was found, please re-open if you're still having issues
