### ISSUE TITLE
Regular expressions scalability issues due to lock on "s_livecode".

### ISSUE THREAD

**Issue by IlyaGrebnov** [dotnet/corefx#26364]
Static Regex methods takes global lock on "s_livecode" inside LookupCachedAndUpdate. This cause scalability issues. We understand that this problem could be addressed on App side, but imho it would be much better to make Regex cache per processor instead of global (similar to what @stephentoub did for Timer lock), so it will be more forgiving for bad coding practice.

We would also participate back port to Desktop framework if this ever get fixed.

**Comment by IlyaGrebnov** [comment]
Please let me know if this is something I could contribute? *

* under assumption that change gets pack-ported to Desktop at some point) :)

**Comment by danmosemsft** [comment]
@ViktorHofer owns regex and I believe this came up before. It does not surprise me that this is a bottleneck.

A per thread cache would surely be faster but threads would end up with duplicate copies. is that an issue? There are all kinds of other options eg per thread for a few entries, and shared for the rest. Also how did we end up choosing 15 entries?

Whatever the approach is would need backing up with measurements.

**Comment by danmosemsft** [comment]
@IlyaGrebnov you're correct in your implication that the best way to get a change into desktop is in general to get it into .NET Core. However it is not a sure thing, it depends on impact, compat cost, port cost etc. Only a minority of changes are ported at the moment.

**Comment by stephentoub** [comment]
> Also how did we end up choosing 15 entries?

I don't know how the default was arrived at, but it's controllable via
https://msdn.microsoft.com/en-us/library/system.text.regularexpressions.regex.cachesize(v=vs.110).aspx

And since it's exposed, that makes me a little nervous about a partitioned cache, as we wouldn't be respecting this value. Maybe that's important, maybe not.

An alternative would be a different data structure for maintaining the cache. We could think about lock-free or lower-locking alternatives.

**Comment by IlyaGrebnov** [comment]
For context: in past month we have 2 live site issue caused by performance degradation in Regex methods due to global lock (one in our code and one in library). So we are interested and woudl like to invest time in fixing this. So I am open for discussion and other suggestions.

Partitioned cache was just first approach which come up in mind. Making cache lock-free is probably best approach from compatibility point of view. 

I would also suggest scale cache linearly with number of cores (we have 20-cores VM in production, so 15 starter cache entries are small without tuning).

**Comment by stephentoub** [comment]
> I would also suggest scale cache linearly with number of cores (we have 20-cores VM in production, so 15 starter cache entries are small without tuning).

In what scenario is the number of distinct regexes used correlated with the number of cores?

**Comment by IlyaGrebnov** [comment]
> what scenario(s) is the number of distinct regexes used correlated with the number of cores?

We working on multi-tenant Enterprise App which allow tenants to define data customization in form of regular expressions. So number of distinct regexes are growing ~linearly with number of tenants and load on a server. But, I get your point, and this is something trivial to workaround with Regex.CacheSize = Environment.ProcessorCount * X. So our main concern is cache efficiency. 

As alternative approach (but this is API-level change) is allow clients to pass a flag to bypass cache, but this potentially mean we would need to build our own caching layer.

**Comment by IlyaGrebnov** [comment]
Just to complete my thought: LRU caches need lock (or at minimum I do not know how to build one without it). And if you allow me to create Regex without cache (and global local) I would cache into smaller number caches (scaled linearly with number of processor) based on pattern.GetHashCode(). So will be a a lock contention, but I hope much smaller one.

**Comment by stephentoub** [comment]
> And if you allow me to create Regex without cache (and global lock)

The cache lookup happens as part of the Regex ctor. If memory serves, once the object is constructed, you won't hit the cache again. So if just cache the constructed Regex objects, you'll only hit the lock when you construct new ones, presumably only a startup cost when first doing the cache, and then only on cache misses.

**Comment by IlyaGrebnov** [comment]
>  cache lookup happens as part of the Regex ctor.

Is any way to bypass cache and a lock all together? Also, this approach only works for "My Code" and could still cause issues with libraries. Is anything we could do to improve scalability of Regex ctor and static methods in .Net?

**Comment by ViktorHofer** [comment]
> The cache lookup happens as part of the Regex ctor. If memory serves, once the object is constructed, you won't hit the cache again. So if you just cache the constructed Regex objects, you'll only hit the lock when you construct new ones, presumably only a startup cost when first filling the cache, and then only on cache misses.

Your memory serves you right Stephen. The cache is only used during object construction. As the static methods instantiate new Regex objects behind the scenes the cache is also accessed by that. Depending on the state of the cache (entries are uniquely identified by a combination of pattern, culture & timeout) it will either just be read or also be written to. The existing cache can be optimized by e.g. setting `RegexOptions.CultureInvariant` to ignore culture differences. Without that flag, identical patterns will be stored in the cache if the CurrentCulture is different.

As Dan and Stephen already stated, we are planning to chance the existing cache data structure. We have at least one internal specialized implementation of a cache which could be used for Regex.

**Comment by IlyaGrebnov** [comment]
Fell free to point me to "internal specialized implementation" as I am happy to contribute /  make changes. 

Alternatively here is what were original proposing:
https://gist.github.com/IlyaGrebnov/c7c2bc4dd77a95ac3ace35b7904af180

**Comment by danmosemsft** [comment]
We are aiming for code complete for 2.1 end of this week. So cache improvement will need to happen soon if we want it in 2.1.

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/pull/27278

**Comment by danmosemsft** [comment]
If all the threads tend to use the smae regex (apparently not the case in this one) the another option is to have a single static field on the cache that is first consulted outside of the lock.
