### ISSUE TITLE
WebSocket fails with Chrome debugging on OSX

### ISSUE THREAD

**Issue by kumpera** [dotnet/corefx#26369]
I'm trying to run Blazor's WebSocket debugger proxy for V8 and it reliably disconnects the browser websocket when left idling for a few seconds.

This doesn't happen if I directly connect to the browser remote debugging session which makes me believe this to be a corefx bug.

**Comment by kumpera** [comment]
CC @SteveSandersonMS

**Comment by stephentoub** [comment]
Shouldn't this be in the ASP.NET repo?

**Comment by kumpera** [comment]
That's a very good question @stephentoub!
My reasoning was that corefx is the home of System.Net.WebSockets.

**Comment by stephentoub** [comment]
That's just the base abstract class, though. The actual logic comes from derived implementations.

**Comment by kumpera** [comment]
For both client and server implementation?
Hmm, in such case I'll move the bug that.

**Comment by stephentoub** [comment]
> For both client and server implementation?

System.Net.WebSockets.dll just contains the base class and the associated helpers, but no actual logic for implementing the WebSockets protocol (at least as of 2.0).

System.Net.WebSockets.Client.dll in corefx then contains a client implementation. 
 And https://github.com/aspnet/WebSockets is the repo for the server implementation in ASP.NET.

Now, the ASP.NET implementation contains a copied/modified version of the managed implementation that's used on the client on Unix in System.Net.WebSockets.Client.dll, but the copied/modified code still resides in that ASP.NET repo.

For 2.1, that managed implementation has been added to System.Net.WebSockets.dll behind the new WebSocket.CreateFromStream method, and ASP.NET will use that.  But even with that, that's only providing the logic for sending/receiving on top of the connection established and upgraded by ASP.NET, and the stream passed into it by ASP.NET still has all of the other transport logic provided by ASP.NET, so it would still be the right place to start.

Thanks.
