### ISSUE TITLE
SqlConnectionTimeout test failing breaking CI

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#26382]
https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/5130e06922a1491ff02ed162fd53459ec3d2ba5e/workItem/System.Data.SqlClient.Tests

@geleems  it is failing on Win10 and Win8.1 in CI jobs since https://github.com/dotnet/corefx/pull/26306

```

Assert.True() Failure
Expected: True
Actual:   False
Stack Trace :
   at System.Data.SqlClient.Tests.SqlConnectionBasicTests.ConnectionTimeoutTestWithThread() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Data.SqlClient\tests\FunctionalTests\SqlConnectionBasicTests.cs:line 110
```

**Comment by saurabh500** [comment]
@geleems the interesting thing is that these tests are failing on Windows where your code changes weren't applicable. I think the "threshold" for Native SNI is different from that of Managed SNI.

**Comment by Priya91** [comment]
This is causing all PRs to be red, is there a fix for this, or should the change be reverted?

**Comment by saurabh500** [comment]
@priya91 https://github.com/dotnet/corefx/pull/26392

**Comment by Priya91** [comment]
@saurabh500 Thanks!

**Comment by danmosemsft** [comment]
It looks like this slipped through CI because of https://github.com/dotnet/core-eng/issues/2411

**Comment by geleems** [comment]
The fix https://github.com/dotnet/corefx/pull/28618 for this issue has been merged to master. Closing the issue.
