### ISSUE TITLE
Performance improvement for Meltdown and Spectre, libuv

### ISSUE THREAD

**Issue by unicomp21** [dotnet/corefx#26385]
https://github.com/libuv/libuv/issues/1710

**Comment by stephentoub** [comment]
@unicomp21, what's the issue/action here for corefx?  Doesn't seem relevant.  The linked issue describes desiring additional GetQueuedCompletionStatus methods to be exposed from Windows, and this repo is not for new Windows methods.

**Comment by karelz** [comment]
Closing as off-topic.

**Comment by unicomp21** [comment]
@stephentoub which MS github repo would be the best place to raise the GetQueuedCompletionStatus request?  Or perhaps an email of someone at MS?

**Comment by unicomp21** [comment]
cc @karelz

**Comment by stephentoub** [comment]
> which MS github repo would be the best place to raise the GetQueuedCompletionStatus request?

@unicomp21, I'm not aware of any GitHub repo for Win32 APIs.  @danmosemsft or @karelz might be able to suggest an avenue for submitting feedback to the Windows team.

**Comment by karelz** [comment]
@ptorr-msft could know where to send the feedback.

**Comment by ptorr-msft** [comment]
I have passed this on to the base kernel team. Thanks for the feedback.
