### ISSUE TITLE
Microsoft.Win32.Registry transitive System.Security.Principal.Windows not availible of net461

### ISSUE THREAD

**Issue by pakrym** [dotnet/corefx#26390]
Repro:

1. Add class library:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Win32.Registry" Version="4.5.0-preview1-26112-01" />
  </ItemGroup>

</Project>
```

```c#
using System;

namespace lib
{
    public class Class1
    {
        public Class1()
        {
            System.Security.Principal.TokenAccessLevels l = 0;
        }
    }
}
```

2. Add an app
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\lib\lib.csproj" />
  </ItemGroup>

</Project>
```

```c#
using System;

namespace reg
{
    class Program
    {
        static void Main(string[] args)
        {
            var a = new lib.Class1();
            Console.WriteLine("Hello World!");
        }
    }
}
```
3. `dotnet run`

Expected:

Runs fine

Actual:

```

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Principal.Windows, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at lib.Class1..ctor()
   at reg.Program.Main(String[] args) in D:\temp\reg\reg\Program.cs:line 9
```

[EDIT] Add syntax highlighting by @karelz

**Comment by danmosemsft** [comment]
@weshaggard it seems like this should work. Any thoughts?

**Comment by maryamariyan** [comment]
I tried the same using version "4.5.0-preview1-26216-02" in both netcoreapp2.0 and net461 and both work fine without exception.

**Comment by joperezr** [comment]
This doesn't seem to be caused by the support package since that dll is not part of it. I'm looking at a log that has the repro, and the weird thing is that it seems like RaR is failing to load this dependency because it doesn't get deployed along the netsandard2.0 lib. This is the output I see for RAR:
```
Could not resolve this reference. Could not locate the assembly "System.Security.Principal.Windows, Version = 4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
For SearchPath "C:\CodeHub\mylib\bin\Debug\netstandard2.0".
  Considered "C:\CodeHub\mylib\bin\Debug\netstandard2.0\System.Security.Principal.Windows.winmd", but it didn't exist.
  Considered "C:\CodeHub\mylib\bin\Debug\netstandard2.0\System.Security.Principal.Windows.dll", but it didn't exist.
  Considered "C:\CodeHub\mylib\bin\Debug\netstandard2.0\System.Security.Principal.Windows.exe", but it didn't exist.

Required by "C:\CodeHub\mylib\bin\Debug\netstandard2.0\mylib.dll".
```

For some reason it seems like it is not looking at the packages cache after reading the project.assets.json

**Comment by joperezr** [comment]
Looks like the problem is that when RAR tries to get the list of dependencies from a ProjectReference it doesn't really go through the deps.json file so it won't copy dlls that are nuget package references of a netstandard2.0 library. This should work fine if the way of referencing the netstandard2.0 library is done via a nuget package instead. Another workaround would be to add the reference to the Registry package manually to the net461 app as well. cc: @dsplaisted

**Comment by maryamariyan** [comment]
Workaround as @joperezr explained is to explicitly add the dependencies so as it is now if I add: 
```
  <ItemGroup>
    <PackageReference Include="Microsoft.Win32.Registry" Version="4.5.0-preview1-26216-02" />
    <PackageReference Include="System.Security.Principal.Windows" Version="4.5.0-preview1-26216-02" />
  </ItemGroup> 
```
I can get the exception to go away

**Comment by ericstj** [comment]
I had a look.  The dependencies in the package were incorrectly being removed as a result of https://github.com/dotnet/buildtools/commit/e8f73c0d8d8891fddacc344ddda1e702015d5dbd#diff-f11695f50a6521c6af9a9522f6d3ce53.  /cc @weshaggard 

We should undo that buildtools change.  Now it was made for a real reason: https://github.com/dotnet/corefx/issues/26129

But its removal has actually broken IO.Packaging in a similar way: it will now be missing System.IO.FileSystem.Primitives.  I looked through the diff after undoing the change and found the following packages gain an *undesired* `NETStandard.Library reference: 
- System.IO.Packaging
- System.IO.FileSystem.AccessControl
- System.Security.Cryptography.Pkcs

We could fix these by making the meta-package mapping conditional for those packages (and potentially only on desktop with a buildtools change).  That way we'd still provide a minimal set of dependencies without missing anything.

**Comment by weshaggard** [comment]
@ericstj thanks for figuring out the issue is related to the fix I made (see what happens when your OOF :)). I will take a look and see what other options we have to address both scenarios.
