### ISSUE TITLE
Avoiding Extra allocation in RemoveRelativeSegments(Path.combineNoChecks(basePath, path)) 

### ISSUE THREAD

**Issue by Anipik** [dotnet/corefx#26396]
RemoveRelativeSegments(Path.combineNoChecks(basePath, path)) is going to cause an allocation but RemoveRelativeSegments() can be modified to take the both paths and do it in a single pass without extra allocation.

It may be helpful for scenarios with heavy usage of Relative Paths.

cc @pjanotti @JeremyKuhne

**Comment by AtsushiKan** [comment]
Grabbing this as I'm a bit light on bugs right now.

**Comment by AtsushiKan** [comment]
Adding link to method in question (so I don't have to hunt for it later...)

https://github.com/dotnet/coreclr/blob/cd3f6e77757729d3d02dfbec4af21cdfe83f5435/src/mscorlib/shared/System/IO/Path.cs#L613

**Comment by AtsushiKan** [comment]
It appears this is the Unix-specific path that's in question here (Windows uses the OS api to remove redundant segments and other path normalization.) I'm not really set up for Unix dev and testing so this isn't a good "grab" bug for me. Putting back up for grabs.
