### ISSUE TITLE
macOS cannot create PFX with a mix of HasPrivateKey and !HasPrivateKey certs

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#26397]
#26125, but for macOS.  (Different fix, and the macOS existing failure is holding up a Linux fix)

```c#
var collection = new X509Certificate2Collection();
collection.Add(certificateWithPrivateKey);
collection.Add(anotherCertWithoutPrivateKey);

var output = collection.Export(X509ContentType.Pkcs12);
```

See also #26152.

**Comment by Wintereise** [comment]
Hi team,

Just wondering if the fix for this ended up making it into 2.1.0 since that recently got released.
