### ISSUE TITLE
Convert.ToBase64String is using "\r\n" line breaks, even on Unix

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#26401]
@stephentoub commented on [Fri Oct 06 2017](https://github.com/dotnet/coreclr/issues/14357)

When Base64FormattingOptions.InsertLineBreaks is used, it's using "\r\n" regardless of platform. Presumably that's not the desired behavior...
https://github.com/dotnet/coreclr/blob/da8b7181dbe362fbfe64c7ef72ff3a4a7db68f24/src/mscorlib/shared/System/Convert.cs#L2522-L2523
https://github.com/dotnet/coreclr/blob/da8b7181dbe362fbfe64c7ef72ff3a4a7db68f24/src/mscorlib/shared/System/Convert.cs#L2540-L2541
https://github.com/dotnet/coreclr/blob/da8b7181dbe362fbfe64c7ef72ff3a4a7db68f24/src/mscorlib/shared/System/Convert.cs#L2581

---

@poizan42 commented on [Fri Oct 06 2017](https://github.com/dotnet/coreclr/issues/14357#issuecomment-334759316)

FWIW I would be quite surprised if the behaviour of ToBase64String depended on the platform considering that the consumer is likely not to be the same as the producer. Should probably just always be \n.

---

@stephentoub commented on [Fri Oct 06 2017](https://github.com/dotnet/coreclr/issues/14357#issuecomment-334759597)

> Should probably just always be \n.

That would be a breaking change and behavioral difference from the .NET Framework.

---

@poizan42 commented on [Fri Oct 06 2017](https://github.com/dotnet/coreclr/issues/14357#issuecomment-334763497)

Hmm yeah that's a problem. What about adding a new value to Base64FormattingOptions to control the newline behaviour?

**Comment by danmosemsft** [comment]
@poizan42 if you'd like to formally propose that can you please format this as suggested in https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md ?

**Comment by pjanotti** [comment]
Considering that `\r` and `\n` should be treated as whitespace by any proper decoder I don't think we should do anything in this regard. Futhermore per [wikipedia](https://en.wikipedia.org/wiki/Base64) all related RFCs that have line separators use CR+LF.
