### ISSUE TITLE
Awaiting multiple Tasks with different results

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#26408]
_From @Meir017 commented on Aug 28, 2017_

I know it's possible to create a class with this feature - https://stackoverflow.com/questions/17197699/awaiting-multiple-tasks-with-different-results#answer-40938652

It would be nice to have this in the class `Task`

_Copied from original issue: dotnet/coreclr#13632_

**Comment by ufcpp** [comment]
https://github.com/dotnet/corefx/issues/16010 ?

**Comment by karelz** [comment]
Yeah, looks like dupe - @jcouv?

**Comment by jcouv** [comment]
Indeed, this is a duplicate. I'll go ahead and close. 
Thanks @ufcpp for connecting the dots.
