### ISSUE TITLE
[IO.Pipes] Outer cancellation of WaitForConnectionAsync/ReadAsync/WriteAsync

### ISSUE THREAD

**Issue by Maxwe11** [dotnet/corefx#2640]
Consider the following code
```c#
[DllImport("api-ms-win-core-io-l1-1-0.dll", SetLastError = true)]
internal static unsafe extern bool CancelIoEx(SafeHandle handle, NativeOverlapped* lpOverlapped);

public static async Task CanBeCanceled_False()
{
    using (NamedPipeServerStream server = new NamedPipeServerStream("unique3", PipeDirection.InOut, 1, PipeTransmissionMode.Byte, PipeOptions.Asynchronous, 0, 0))
    {
        Task waitForConnectionTask = server.WaitForConnectionAsync(CancellationToken.None); // cannot be canceled
       
        unsafe
        {
            CancelIoEx(server.SafePipeHandle, null);
        }

        await waitForConnectionTask; // throws OperationCanceledException
    }
}

public static async Task CanBeCanceled_True()
{
    using (NamedPipeServerStream server = new NamedPipeServerStream("unique3", PipeDirection.InOut, 1, PipeTransmissionMode.Byte, PipeOptions.Asynchronous, 0, 0))
    {
        var ctx = new CancellationTokenSource();
        Task waitForConnectionTask = server.WaitForConnectionAsync(ctx.Token); // could be canceled
       
        unsafe
        {
            CancelIoEx(server.SafePipeHandle, null);
        }

        await waitForConnectionTask; // throws IOException: IO operation was aborted unexpectedly.
    }
}
```

Is it intentional behavior or it's a bug that we receive `OperationCanceledException` even if we couldn't cancel in a normal way (without interop) ?

**Comment by stephentoub** [comment]
Interesting.  Thanks for the minimal repro.  Seems pretty rare that you'd pass a cancelable token to the operation but then try to cancel it not via the token but instead by accessing the handle and P/Invoking to CancelIoEx, so I think it'd be fairly low risk to make these consistent and have it always result in an OCE.  But I also don't think we're losing much by having it by an IOException.

@ericstj? @FiveTimesTheFun?

**Comment by ianhays** [comment]
Hmmm. Both cases seem potentially correct - the IO operation <i>was</i> aborted <b>unexpectedly</b>, but it was also a Canceled Operation. Either seems fine and I personally prefer the IOException, but I can't think of a good reason why beyond it <i>feeling</i> correct

I tested this on the Desktop Framework 4.6 as well and got a TaskCanceledException for ```CanBeCanceled_False``` and an IOException for ```CanBeCanceled_True```, so there's an argument for keeping the IOException for compatibility with the desktop framework.

**Comment by Maxwe11** [comment]
I'm concerned about OCE rather than IOException because if we pass CancellationToken which couldn't be canceled, outer cancellation should treated as unexpected.

**Comment by FiveTimesTheFun** [comment]
I agree with what's been said... it would be a breaking change to take this fix to Desktop if we were to make the change and kept .NET Core and Desktop consistent.  It's unfortunate that the HR in the IOException is COR_E_IO instead of the original cancellation from Win32.

**Comment by stephentoub** [comment]
@Maxwe11, did https://github.com/dotnet/corefx/pull/2568 change anything related to this for WaitForConnectionAsync?

**Comment by Maxwe11** [comment]
@stephentoub no, I've added tests for this behavior de58244

**Comment by stephentoub** [comment]
Ok, thanks.
