### ISSUE TITLE
Basic proxy auth does not work

### ISSUE THREAD

**Issue by wfurt** [dotnet/corefx#26405]
Steps to reproduce:
1. `export  http_proxy=http://furt:foo@10.121.122.110:3128`
2. wire simple app using http handler and fetch a page.
3. verify that connection will get redirected to proxy.
3. `export COMPlus_UseManagedHttpClientHandler=true`
4. run the test again. 
5. The connection is redirected to proxy but the proxy fails with 407 error.

Tested on: Linux & Mac (Windows not attempted)

It seems like the code is trying to add Proxy-Authorization header and send it again but it never makes to the wire. (see attached packet capture) 

I found this while working on #26341. I did not test Digest-Auth. 
Also note that curl will send Proxy-Authorization in first request if proxy auth is set. 
This may be design decision but it may be worth of verification. 
It would be unpleasant if we need to double every request. 
(needs more testing with fetching various documents via same proxy server)

**Comment by wfurt** [comment]
[proxy_auth.pcapng.zip](https://github.com/dotnet/corefx/files/1641335/proxy_auth.pcapng.zip)

**Comment by Priya91** [comment]
@wfurt It would be good to have a repro app or test for this and skipped against this issue, so it's easier to repro and fix.

**Comment by karelz** [comment]
Blocking release: Needed for ManagedWebSocket proxy support - #9503 (IoT ask: #26144).

**Comment by geoffkizer** [comment]
@wfurt are you looking at this?  if so, please assign to yourself.  otherwise I can look into it.

**Comment by wfurt** [comment]
yes, I was planning to. However for some reason I cannot reproduce it any more. I'm going to close this and I'll debug it if it happens aver again.
