### ISSUE TITLE
RazorPages support for vbhtml

### ISSUE THREAD

**Issue by tb-mtg** [dotnet/corefx#26419]
Is there any chance the VB community can make it possible to support RazorPages using .vbhtml files in .Net Core as it seems to have been dropped.

I have found .NET Core projects that support custom ViewEngines  for [.pug](https://github.com/AspNetMonsters/pugzor) & [.md](https://github.com/hishamco/MarkdownViewEngine) file types but cannot make it work for .vbhtml files.

It would be great to make it happen using a .vbproj  with `<Project Sdk="Microsoft.NET.Sdk.Web">`.

**Comment by karelz** [comment]
I think it is better suited for ASP.NET team: https://github.com/aspnet
