### ISSUE TITLE
SegFault in Alpine 3.6 CoreFX build

### ISSUE THREAD

**Issue by maririos** [dotnet/corefx#26425]
@dotnet-mc-bot commented on [Wed Jan 17 2018](https://github.com/dotnet/core-eng/issues/2423)

Build : Master - 20180117.01 (Product Build)
Failing configurations:
- Alpine3.6
  - x64
[Mission Control Build Info](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/build~2Fproduct~2F/build/20180117.01/workItem/Orchestration/analysis/external/Link)

Intermittent issue, opening this to track it as well as ping Jan V about it.

**Comment by joshfree** [comment]
cc: @janvorli

**Comment by wtgodbe** [comment]
Closing as stale/dead
