### ISSUE TITLE
HttpClient redirection for POST is different between Windows and Unix

### ISSUE THREAD

**Issue by pjanotti** [dotnet/corefx#26434]
The redirection issue was initially reported in #22707 but it was closed as duplicate #9228, however, the redirection issue was never addressed.

The discussion below refers to the test [AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection](https://github.com/dotnet/corefx/blob/dbfa1ebe3f41090c525990d4887bd64574b5124b/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs#L575).

On Unix, when `UseManagedHandler` is false, the test is failing consistently with the `(statusCode = 300, oldMethod = "POST", newMethod = "GET")` which is expected per curl documentation, since the original method won't be changed in this case:

> [When following a Location:, the 3xx response code that redirected it also dictates which request method it will use in the subsequent request: For 301, 302 and 303 responses libcurl will switch method to GET unless CURLOPT_POSTREDIR instructs libcurl otherwise. All other 3xx codes will make libcurl send the same method again.](https://curl.haxx.se/libcurl/c/CURLOPT_FOLLOWLOCATION.html)

Do we want to match the redirection behavior expected in the test case on Unix? If yes, it seems that we will have to handle the redirection, at least for POST.

**Comment by karelz** [comment]
I think we should just change the test to pass for LibcurlHandler.
It is one of the subtle differences of running on Windows vs. Linux/Mac. ManagedHandler should bridge this gap going forward.
Moreover we didn't get any customer reports so far.

**Comment by karelz** [comment]
cc @Priya91 @geoffkizer @wfurt
