### ISSUE TITLE
Add Sse2.MoveMask that takes Vector128<byte>

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#26433]
Today we have overloads for Avx2.MoveMask for both sbyte and byte vectors.

* `Avx2.MoveMask(Vector256<sbyte> value)`
* `Avx2.MoveMask(Vector256<byte> value)`

but for Sse2, we only have overloads for sbyte.

* `Sse2.MoveMask(Vector128<sbyte> value)`

We should add an Sse2.MoveMask overload that takes a `Vector128<byte>` as well.

/cc @fiigii @tannergooding @CarolEidt

**Comment by tannergooding** [comment]
Does this necessarily qualify as an API-suggestion? I would think it was one of the already approved APIs that was missed due to different review process taken for these APIs...

**Comment by fiigii** [comment]
> I would think it was one of the already approved APIs that was missed due to different review process taken for these APIs...

Yes, My apologies...

**Comment by eerhardt** [comment]
> Does this necessarily qualify as an API-suggestion?

No, I don't think this has to go through the full API review process.  It should have been included in the initial review.  I just wanted to ensure people saw this as an "API modifying" issue.
