### ISSUE TITLE
Test failed: System.Net.Sockets.Tests.SocketOptionNameTest / MulticastInterface_Set_IPv6_AnyInterface_Succeeds

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#26443]
## Types of failure

```
Waiting for received data timed out
Expected: True
Actual:   False

at System.Net.Sockets.Tests.SocketOptionNameTest.<MulticastInterface_Set_IPv6_Helper>d__12.MoveNext() in /root/corefx-1299519/src/System.Net.Sockets/tests/FunctionalTests/SocketOptionNameTest.cs:line 208
at System.Net.Sockets.Tests.SocketOptionNameTest.<MulticastInterface_Set_IPv6_AnyInterface_Succeeds>d__10.MoveNext() in /root/corefx-1299519/src/System.Net.Sockets/tests/FunctionalTests/SocketOptionNameTest.cs:line 163
--- End of stack trace from previous location where exception was thrown ---
```

## History of failures

Day | Build | OS | Details
--- | --- | --- | --- 
1/18 | 20180118.04 | RedHat69 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180118.04/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SocketOptionNameTest~2FMulticastInterface_Set_IPv6_AnyInterface_Succeeds)
1/19 | 20180119.01 | RedHat69 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180119.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SocketOptionNameTest~2FMulticastInterface_Set_IPv6_AnyInterface_Succeeds)
1/19 | 20180119.02 | RedHat69 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180119.02/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SocketOptionNameTest~2FMulticastInterface_Set_IPv6_AnyInterface_Succeeds)
1/19 | 20180119.04 | RedHat69 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180119.04/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SocketOptionNameTest~2FMulticastInterface_Set_IPv6_AnyInterface_Succeeds)
1/19 | 20180119.06 | RedHat69 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180119.06/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SocketOptionNameTest~2FMulticastInterface_Set_IPv6_AnyInterface_Succeeds)
1/20 | 20180120.01 | RedHat69 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180120.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SocketOptionNameTest~2FMulticastInterface_Set_IPv6_AnyInterface_Succeeds)
1/20 | 20180120.02 | RedHat69 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180120.02/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SocketOptionNameTest~2FMulticastInterface_Set_IPv6_AnyInterface_Succeeds)
1/21 | 20180121.01 | RedHat69 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180121.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SocketOptionNameTest~2FMulticastInterface_Set_IPv6_AnyInterface_Succeeds)
1/21 | 20180121.02 | RedHat69 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180121.02/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SocketOptionNameTest~2FMulticastInterface_Set_IPv6_AnyInterface_Succeeds)
1/22 | 20180122.01 | RedHat69 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180122.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SocketOptionNameTest~2FMulticastInterface_Set_IPv6_AnyInterface_Succeeds)
1/22 | 20180122.02 | RedHat69 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180122.02/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SocketOptionNameTest~2FMulticastInterface_Set_IPv6_AnyInterface_Succeeds)

**Comment by karelz** [comment]
Similar to #24114 infra issue - @wfurt can you please follow up on it? Thanks!

**Comment by wfurt** [comment]
We made changes with Matt to CI infrastructure. Last set of test passed. closing now.
