### ISSUE TITLE
Fix HTTP Status line parsing to be more tolerant of white space

### ISSUE THREAD

**Issue by caesar1995** [dotnet/corefx#26455]
HTTP status line has a optional status description field, i.e., "HTTP/1.1 200 OK", "OK" is the StatusDescription.

From RFC 7230: 3.1.2.  Status Line

>   The first line of a response message is the status-line, consisting
   of the protocol version, a space (SP), the status code, another
   space, a possibly empty textual phrase describing the status code,
   and ending with CRLF.

So a valid HTTP status line without status description should like this: "HTTP/1.1 200 " (contains a space at the end, which ASCII value is 0x20).

However, Fiddler will trim out the white space at the end, which violate the RFC. Here is the evidence:

This is the address used for testing: `http://coastwatch.pfeg.noaa.gov/erddap/wms/jplAmsreSstMon_LonPM180/request?VERSION=1.3.0&SERVICE=WMS&REQUEST=GetCapabilities`

Without Fiddler: (notice the space after status code 200)
![noproxy](https://user-images.githubusercontent.com/8537784/35165671-1cf34754-fd04-11e7-8017-1db7257d2b7b.PNG)

With Fiddler and do loopback packet capture:
![withproxy](https://user-images.githubusercontent.com/8537784/35165765-5c6092e8-fd04-11e7-829f-0830165b8566.PNG)

This will cause `NullRefernceException` on .NET Framework under some conditions. (#25741 )

For now, .NET Core doesn't has the same issue, but we should notice this behavior. Since we cannot change how Fiddler works, we need to make our code more robust on dealing with this situation.

/cc: @geoffkizer @karelz

**Comment by karelz** [comment]
We should add a test for this situation.

**Comment by stephentoub** [comment]
> For now, .NET Core doesn't has the same issue, but we should notice this behavior. Since we cannot change how Fiddler works, we need to make our code more robust on dealing with this situation.

I'm confused by the comment.  Is this issue purely about adding a test to make sure we don't regress?  Or is there something to fix in .NET Core?

**Comment by karelz** [comment]
We should at minimum add test. If we pass already (as @caesar1995's comment suggests), no more work is needed. If we don't, we should probably fix it.

**Comment by stephentoub** [comment]
Is this different from https://github.com/dotnet/corefx/issues/24713?  See https://github.com/dotnet/corefx/blob/08802ff9c877f7f75a82d6704d84d321e99eb5c8/src/System.Net.Http/tests/FunctionalTests/HttpProtocolTests.cs#L30-L39.

**Comment by caesar1995** [comment]
We can close this issue after I verify that the disabled test data `//[InlineData("HTTP/1.1 200", 200, "")] ` will pass on netcore.

#24713 contains this scenario.

**Comment by karelz** [comment]
Oh, if we have a test case already, let's just enable it. It would be nice to give it comment with motivation for this kind of invalid input.

**Comment by caesar1995** [comment]
Confirmed test data will pass on netcore.

We can track general HTTP statusline parsing difference between .NET Framework and .NET Core in #24713.

> if we have a test case already, let's just enable it

We cannot do this right now, since .NET Framework change (in 4.7.3) hasn't been ported yet.

**Comment by stephentoub** [comment]
> We cannot do this right now

We can by creating a separate test for it that just calls the other one and that's skipped on netfx. I probably should have done that initially, but I want sure what the desired behaviors we're, only that there was a difference.

**Comment by karelz** [comment]
We can enable the test case only for .NET Core - given that it is InlineData, we may need to split the test into 2, but it should be doable.

**Comment by caesar1995** [comment]
Ok, I will prepare a PR to split the test and enable test data for netcore for now.

**Comment by karelz** [comment]
@caesar1995 I have marked the other issue #24713 as 2.1 already :) ... if you plan to re-enable all tests, please use #24713. If you plan to re-enable just this one test, let's use this issue. Sorry for confusion. Thanks!
