### ISSUE TITLE
Consider making Expect: 100-continue the default behavior

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#26459]
Expect: 100-continue is almost always the right thing to do -- it enables sending stream-only data in the presence of auth or redirects etc.  We should strongly consider making this the default behavior.

**Comment by davidsh** [comment]
>Expect: 100-continue is almost always the right thing to do

Our experience with .NET Framework and customers has shown over the years past that a lot of servers did not react well to getting the request header 'Expect: 100-continue'.   The default for this property in .NET Framework ServicePointManager was to set to true.  Many customers ended up disabling this. Lots of conversations on the Internet about this.

https://haacked.com/archive/2004/05/15/http-web-request-expect-100-continue.aspx/

**Comment by geoffkizer** [comment]
Thanks for the link.

I would hope that servers are better behaved today, but not sure that's the case...

**Comment by stephentoub** [comment]
> it enables sending stream-only data in the presence of auth or redirects etc

But it also incurs an extra roundtrip, with the client waiting until the server responds before it sends the body, which means the request can take longer in cases where the body will be sent.  Even if servers behaved ideally, it's not clear to me it's almost always the right thing to do.

**Comment by geoffkizer** [comment]
Yeah, I am probably overstating it to say "almost always the right thing to do".

The following situations can cause us to try to resend a request, including body:
(1) Auth challenge (401, 407)
(2) Redirect (30x)
(3) Connection closed by server (see my comments on #26453)

For streamed request bodies without Expect: 100-continue, we can't restart the body and thus can't retry.  This seems pretty bad, especially since (3) above can happen pretty much any time.  So at the very least, we should consider making 100-continue the default for streamed request bodies.

For all request bodies without Expect: 100-continue, once we start sending the request body, we have to finish (or throw away the connection) -- even once we get one of the above responses, or another 4xx or 5xx response (e.g. 403).  Currently, I think we keep sending the entire request body.  We could of course add a heuristic to kill the connection if the body is too large.  But in this case, if we know the body is large, we're probably better off sending Expect: 100-continue, since the added overhead here is likely small compared to the transfer cost.  That said, in this case killing the connection isn't terrible either.

So, perhaps the right tradeoff is to send Expect: 100-continue by default for streamed bodies, but not for non-streamed.  And the user can always override if desired.

Thoughts?

**Comment by stephentoub** [comment]
(As an implementation detail, turning on Expect: 100-continue also requires us to create a timer for the operation so that we eventually send the payload if the server hasn't responded in time otherwise, so there's extra overhead related to that, too.)

**Comment by Tratcher** [comment]
@geoffkizer what API would you use to detect streamed bodies? HttpContent doesn't make that obvious.

**Comment by geoffkizer** [comment]
@Tratcher Good point.  I thought this was exposed somewhere, but I appears I'm wrong.

**Comment by Tratcher** [comment]
TryComputeLength is about as close as it gets.

**Comment by stephentoub** [comment]
Or special-casing known content types (e.g. ByteArrayContent) and stream types (e.g. CanSeek==true), and assuming anything else is streaming.

**Comment by karelz** [comment]
We will leave the default false - similar to WinHttp stack.
