### ISSUE TITLE
CoreFx assemblies lack the TargetFrameworkAttribute

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#26457]
I notice this when looking at https://github.com/dotnet/corefx/issues/26456.  It appears to still be the case.  Filing here, though the right fix may be in buildtools.

**Comment by weshaggard** [comment]
@ericstj they have never had the attribute. Do you think it is worth adding?

**Comment by ericstj** [comment]
See related issue, folks have been reporting when examining the assemblies in ILSpy.  I don't think it'd hurt to add the attribute.  We have that information when we build them.

**Comment by weshaggard** [comment]
I'm OK with adding them, but we likely need to do it custom based on our configuration system.

**Comment by ericstj** [comment]
Sure, TargetGroup implies the TFM that gets used, then that feeds into source file that is written for all assemblies.

**Comment by ViktorHofer** [comment]
Fixed with https://github.com/dotnet/corefx/pull/31260

**Comment by weshaggard** [comment]
@ViktorHofer what in #31260 fixed this? Is it the fact that we now set the TargetFramework attribute that causes this to get generated?

**Comment by wtgodbe** [comment]
@ViktorHofer is this fixed with https://github.com/dotnet/corefx/pull/32680?

**Comment by ViktorHofer** [comment]
No, we control the TargetFrameworkAttribute with this flag: https://github.com/dotnet/corefx/blob/master/Directory.Build.props#L315. As there were some concerns with adding it to our assemblies I didn't do it.

**Comment by ViktorHofer** [comment]
Currently vstest uses this attribute to figure out under which target framework to run if no framework is passed down to vstest.console. This is the reason why VS Test Explorer doesn't work anymore with >= VS 16.2. I'm going to enable the property for test assemblies to unblock the broken Test Explorer experience. We should discuss if we should set it correctly for .NET 5.
