### ISSUE TITLE
Managed HttpConnection pooling for redirection

### ISSUE THREAD

**Issue by pjanotti** [dotnet/corefx#26453]
In the case of redirection for GET and PUT the connections are not being pooled. For HEAD there is a race condition that causes error if the connection is actually reused.

The intermittent failures on [AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection](https://github.com/dotnet/corefx/issues/23769) happen for HEAD requests in the following way:

* In this test the HttpConnection used to serve HEAD requests are returned to the pool during the execution of SendAsync. Connections for GET and POST are not returned to the respective [HttpConnectionPool](https://github.com/dotnet/corefx/blob/67d240ed07342544cd5c09d1765952fe8c9d9036/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnection.cs#L381).
* When a connection goes back to the pool it triggers a [read ahead task on the connection object](https://github.com/dotnet/corefx/blob/67d240ed07342544cd5c09d1765952fe8c9d9036/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnection.cs#L1145).
* Later the pool is checked via [GetConnectionAsync](https://github.com/dotnet/corefx/blob/67d240ed07342544cd5c09d1765952fe8c9d9036/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnectionPool.cs#L66) if the read ahead task has not yet completed then the connection is re-used, see [IsUsable()](https://github.com/dotnet/corefx/blob/67d240ed07342544cd5c09d1765952fe8c9d9036/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnectionPool.cs#L508).
* Reusing the connection triggers a call to [FillAsync](https://github.com/dotnet/corefx/blob/67d240ed07342544cd5c09d1765952fe8c9d9036/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnection.cs#L908) that tries to get data from the completed [read async task](https://github.com/dotnet/corefx/blob/67d240ed07342544cd5c09d1765952fe8c9d9036/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnection.cs#L941) but it returns zero and triggers an [IOException](https://github.com/dotnet/corefx/blob/67d240ed07342544cd5c09d1765952fe8c9d9036/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnection.cs#L962).

Reliable way to force the error described above can be found in #26421

**Comment by davidsh** [comment]
>In the case of redirection for GET and PUT the connections are not being pooled. For HEAD there is a race condition that causes error if the connection is actually reused.

Re-using TCP connections during redirects will not always be possible.  In order to do that, the response stream from the server needs to be drained fully.  Some servers send a lot of bytes in the response body for the 3xx redirection response.  Many stacks (such as WinHttp and .NET Framework) have a limit (configurable sometimes) for the "drain size", i.e. the number of bytes to drain.  If that is exceeded, then the connection is "thrown" away (RST) and a new one must be used.

**Comment by geoffkizer** [comment]
There are really two issues here:

(1) There's a window where we may try to reuse a pooled connection for a request, but the server is closing the connection, and this results in an IO failure (typically, we get EOF on trying to read the response, but in theory we could get IO errors on sending the request as well).  We need to have better retry logic for this case.
(2) We are not draining connections at all.  We need to drain, at least up to some point, as @davidsh points out above.

We need to fix both of these.  We probably want to fix (1) first because if we fix (2) before (1), we will exacerbate the IO error problem in (1).  Specifically, we will start having occasional failures like this one for GET and POST as well as HEAD.

**Comment by geoffkizer** [comment]
(2) is tracked by #23156.

**Comment by stephentoub** [comment]
For (1), I suggest we do the following:
We have our read-ahead task that's initiated when the connection is put into the pool. If we decide to reuse a connection but then the result of that read ahead returns 0, we "simply" start over. In addition to fixing the problem, this will mean a small set of actual failures will be erroneously retried, but there's really no way around that.

**Comment by geoffkizer** [comment]
@stephentoub I agree, but I think the devil is in the details...

In particular, when is it correct to "start over"?

(1) IO error writing the request header.  No problems here, I think.
(2) EOF on result of read ahead, assuming there's no request body.  No problems here, I think.
(3) EOF on initial connection read, assuming there's no request body.  This is a weird one, but could happen, say, if the server shuts down right after we connect.  So on net it's probably worth doing.
(4) EOF (initial or read ahead) when waiting for 100 Continue.  (So, there's a request body, but it hasn't been sent yet.)  Seems like it's safe to start over here, too.
(5) IO error writing request body.  This seems dangerous.  Probably we should not restart.  If the request body is streamed, we can't restart anyway.
(6) EOF on first read after sending request body.  Again, probably doesn't make sense to restart here.

I think that covers all cases.  Note though, that when using 100-continue, you're going to get timing errors occasionally even with a well-behaved server.
  
Also, how hard do we try?  I.e. how many times do we "start over" vs giving up?  It's certainly possible to have a bunch of connections all get timed out at the same time.  That argues for trying more than once.  But we certainly don't want to try forever.  Is there a limit?  Is this just bounded by request timeout?

**Comment by geoffkizer** [comment]
Also, what about 5xx errors?  In this case, we could drop the connection and retry on another.  If the server is configured for load balancing/failover, this could well result in a successful request.

**Comment by geoffkizer** [comment]
I added a separate issue for retry logic: #26495.

**Comment by pjanotti** [comment]
In line with what @davidsh mentioned [above](https://github.com/dotnet/corefx/issues/26453#issuecomment-359050285) the redirection with non-managed handlers also fails sometimes (although less frequently than the managed one), example [here](https://github.com/dotnet/corefx/pull/26300#issuecomment-359187579). We should separate the tests according with both behaviors: one that does not close the connection during redirection (expected typical case) and one that does it to force the handling of the exceptional case.

**Comment by geoffkizer** [comment]
I don't know that it's all that atypical.  That said, if it makes the tests more stable, we should do it.

**Comment by pjanotti** [comment]
The redirection tests were re-enabled with PR #26674 and no failures since then.

**Comment by geoffkizer** [comment]
Ok, then can we close this issue?

**Comment by pjanotti** [comment]
From my perspective yes, closing it...
