### ISSUE TITLE
Consolidate configuration for enabling ManagedHandler 

### ISSUE THREAD

**Issue by wfurt** [dotnet/corefx#26466]
This is part of  #23166 and primarily opened to address remaining concerns from #26403:

- existing COMPlus_UseManagedHttpClientHandler is not compliant and shall use DOTNET_ prefix
- configuration via AppContext should take precedence over environmental variable. Existing code would enable ManagedHandler if either one method is set to enable. 

This possibly also opens option to retire environmental configurtion as it seems redundant to runtime configuration. 
We can also updated tests as the context may be easier to manipulate

**Comment by karelz** [comment]
Is there an easy way to run all Http tests with ManagedHandler if we drop the environment variable?
If there is, we might consider retiring the env var.

**Comment by stephentoub** [comment]
> Is there an easy way to run all Http tests with ManagedHandler if we drop the environment variable?

The tests already don't use the environment variable.

> If there is, we might consider retiring the env var.

That said, personally I think we should keep the environment variable. If nothing else, we should be consistent across how we expose such options.
