### ISSUE TITLE
HttpConnectionPools.RemoveStalePools race condition

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#26468]
Fix it properly:
https://github.com/dotnet/corefx/blob/91a83313344bd96127dbc2c50723a930f93c33c5/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnectionPools.cs#L127-L135

**Comment by stephentoub** [comment]
Why does it need a fix?

**Comment by karelz** [comment]
Hmmm, somehow I mixed it up with other comments and thought we may be disposing HttpConnection in use. You're right, this is not needed and definitely not reliability :(
Sorry :( ... I should not trust my week-old notes in future ...
