### ISSUE TITLE
osx.10.13-x64 is not in the runtime.json

### ISSUE THREAD

**Issue by wli3** [dotnet/corefx#26488]
It cause restore on High Sierra failed, even when the package is considered "any".
https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json#L1018

relate: https://github.com/dotnet/cli/issues/8436

**Comment by bording** [comment]
This has been fixed by #26439.

**Comment by weshaggard** [comment]
Yes this is fixed. Thanks @bording
