### ISSUE TITLE
The `System.Json.JsonObject.Save(System.IO.Stream)` method produces invalid json.

### ISSUE THREAD

**Issue by Thiez** [dotnet/corefx#26486]
The "json" this method writes to the stream puts a comma between keys and values, and does not separate the next key from the previous value with a comma. E.g. when you expect the output `{"foo":"bar","baz":"frop"}`, you will actually get something like `{"foo","bar""baz","frop"}`. This bug has existed since the `JsonObject` class was invented in 2008, see [here](https://github.com/mono/mono/commit/66ecab0058cbf5c8aaa1c9ca89da52752d465eb4#diff-6a07ba1015d9ca7fc1b5b5a10859b17eR162). Perhaps the best fix would be to remove the override of `JsonValue.Save(Stream)` in `JsonObject` entirely; clearly nobody is using it (or this bug would have been noticed before), and the base implementation on `JsonValue` actually does the right thing.

**Comment by danmosemsft** [comment]
Thanks for the report. Do you want to offer a PR with a test?

**Comment by Thiez** [comment]
I've created a PR that fixes the problems.

**Comment by huanwu** [comment]
@tarekgh Why you add area-serialization tag? It is not related to serialization.

**Comment by tarekgh** [comment]
@huanwu nevermind, I have tagged this by mistake
