### ISSUE TITLE
[API] Add AsyncMethodBuilder.Start<TStateMachine> for Task likes

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#26481]
**API**
```csharp
public static class AsyncMethodBuilder
{
    [DebuggerStepThrough]
    public static void Start<TStateMachine>(ref TStateMachine stateMachine)
                             where TStateMachine : IAsyncStateMachine
}
```

**Scenario**: implementing the [`Start` method of `AsyncMethodBuilder`](https://github.com/dotnet/roslyn/blob/master/docs/features/task-types.md#builder-type) either must box the statemachine or use `AsyncTaskMethodBuilder` which carries an additional `Task<TResult>` field.

**With api**
```csharp

public void Start<TStateMachine>(ref TStateMachine stateMachine)
    where TStateMachine : IAsyncStateMachine
       => AsyncMethodBuilder.Start(ref stateMachine); // provides correct EC semantics
```

**Without api**
*Invalid approach*
Boxing the statemachine via EC.Run is invalid; 
```csharp
public void Start<TStateMachine>(ref TStateMachine stateMachine)
    where TStateMachine : IAsyncStateMachine
{
    ExecutionContext.Run(ExecutionContext.Capture(), // capture current context
                         (s) => ((TStateMachine)s).MoveNext(), 
                         stateMachine); // struct stateMachine is boxed. Invalid
}
```
*Option 1*
So either an Async**Task**MethodBuilder needs to be instantiated and used to correctly implement an AsyncMethodBuilder (which seems an odd appropriation for a non-Task type):
```csharp
public void Start<TStateMachine>(ref TStateMachine stateMachine)
    where TStateMachine : IAsyncStateMachine
{
    AsyncTaskMethodBuilder b = default; // create empty AsyncTaskMethodBuilder to access method
    b.Start<TStateMachine>(ref stateMachine);
}
```
*Option 2*
Or the statemachine needs to be pre-boxed and then assigned back; which is ugly and error prone:
```csharp
public void Start<TStateMachine>(ref TStateMachine stateMachine)
    where TStateMachine : IAsyncStateMachine
{
    IAsyncStateMachine sm = stateMachine; // box
    ExecutionContext.Run(ExecutionContext.Capture(), // capture current context
                         (s) => ((IAsyncStateMachine)s).MoveNext(), 
                          sm);
   stateMachine = (TStateMachine)(object)sm; // unbox
}
```

**Alternative apis**
Manual capture and Run with a `ref TState`
```csharp
namespace System.Threading
{
    delegate void ContextRefCallback<TState>(ref TState state);

    public partial class ExecutionContext
    {
        static void Run<TState>(ExecutionContext executionContext, 
                                ContextRefCallback<TState> callback, 
                                ref TState state);
    }
}
```

Or the following which require more bolierplate by the implementer to get right and `OnValueChanged` can't be triggered for AsyncLocals (as that api is not exposed); which would also be more work to get right again.

Allow ExecutionContext to be directly set (using Captured context) - where `null => Default`
```csharp
public partial class ExecutionContext
{
    static void SetExecutionContext(ExecutionContext executionContext);
}
```
Or expose the Thread ExecutionContext setter to match the getter - where `Default == null`
```csharp
public partial class Thread
{
    ExecutionContext ExecutionContext { get; set; }
}
```

/cc @stephentoub

**Comment by stephentoub** [comment]
Why can't it just do:
```C#
AsyncTaskMethodBuilder b = default;
b.Start<TStateMachine>(ref stateMachine);
```
?

**Comment by benaadams** [comment]
*edit* added issue with asynclocals for alternative apis

> Why can't it just do:

`AsyncTaskMethodBuilder` carries a `AsyncTaskMethodBuilder<VoidTaskResult>` field which carries a `Task<VoidTaskResult>` field.

Using the `Task` field for additional state is a use case pretty much covered by `ValueTask<TResult>`.

Using a different type for state means the struct builder implementation is carrying an unnecessarily Task field that is never used; just to use the EC correctly.

Perhaps it would be better to have a `AsyncMethodBuilder` type that has `AsyncTaskMethodBuilder<TResult>`.Start method as a static; and expose that instead?

e.g.
```csharp
public static class AsyncMethodBuilder
{
    [DebuggerStepThrough]
    public static void Start<TStateMachine>(ref TStateMachine stateMachine)
                             where TStateMachine : IAsyncStateMachine
}
```

**Comment by benaadams** [comment]
e.g. https://github.com/benaadams/coreclr/commit/b676eb8ef6d8363f65d9b9551de3a038b690d225

Seems better?

**Comment by stephentoub** [comment]
> carrying an unnecessarily Task field that is never used

I'm not following... what I wrote was a local, not a field, and I meant a local. You're concerned about an extra reference on the stack?

**Comment by benaadams** [comment]
> You're concerned about an extra reference on the stack?

Yeah because it already outputs
```asm
G_M54617_IG04:
       lea      rcx, bword ptr [rsp+48H]
       xorpd    xmm0, xmm0
       movdqu   qword ptr [rcx], xmm0
       mov      dword ptr [rsp+40H], -1
       lea      rcx, bword ptr [rsp+48H]
       mov      edx, dword ptr [rcx]
       movzx    rdx, byte  ptr [rcx+4]
       movzx    rdx, byte  ptr [rcx+5]
       mov      rcx, gword ptr [rcx+8]
       mov      gword ptr [rsp+28H], rcx
       lea      rcx, bword ptr [rsp+28H]
       lea      rdx, bword ptr [rsp+30H]
       call     AsyncTaskMethodBuilder`1:Start(byref):this
```
rather than
```asm
G_M54617_IG04:
       lea      rcx, bword ptr [rsp+38H]
       xorpd    xmm0, xmm0
       movdqu   qword ptr [rcx], xmm0
       mov      dword ptr [rsp+30H], -1
       lea      rcx, bword ptr [rsp+20H]
       call     AsyncMethodBuilder:Start(byref)
```
As it goes via the instance method of a generic; but the method doesn't have any state so is happily a static method on a non-generic

**Comment by benaadams** [comment]
> You're concerned about an extra reference on the stack?

Yeah because it already outputs for `AsyncValueTaskMethodBuilder` which does the wrapping
```asm
G_M54617_IG04:
       lea      rcx, bword ptr [rsp+48H]
       xorpd    xmm0, xmm0
       movdqu   qword ptr [rcx], xmm0
       mov      dword ptr [rsp+40H], -1
       lea      rcx, bword ptr [rsp+48H]
       mov      edx, dword ptr [rcx]
       movzx    rdx, byte  ptr [rcx+4]
       movzx    rdx, byte  ptr [rcx+5]
       mov      rcx, gword ptr [rcx+8]
       mov      gword ptr [rsp+28H], rcx
       lea      rcx, bword ptr [rsp+28H]
       lea      rdx, bword ptr [rsp+30H]
       call     AsyncTaskMethodBuilder`1:Start(byref):this
       lea      rcx, bword ptr [rsp+48H]
       mov      rdx, rsi
       call     AsyncValueTaskMethodBuilder`1:get_Task():struct:this
```
rather than when non wrapped
```asm
G_M54617_IG04:
       lea      rcx, bword ptr [rsp+38H]
       xorpd    xmm0, xmm0
       movdqu   qword ptr [rcx], xmm0
       mov      dword ptr [rsp+30H], -1
       lea      rcx, bword ptr [rsp+20H]
       call     AsyncMethodBuilder:Start(byref)
       lea      rcx, bword ptr [rsp+38H]
       mov      rdx, rsi
       call     AsyncValueTaskMethodBuilder`1:get_Task():struct:this
```
(added change to https://github.com/dotnet/coreclr/pull/15629#issuecomment-359241974 to not wrap the call)

**Comment by benaadams** [comment]
Adding a second object field to `AsyncValueTaskMethodBuilder<TResult>` for a non-Task increases the stack action further (though the Jit does Vectorize it some)
```asm
G_M54617_IG04:
       xor      rcx, rcx
       lea      rdx, bword ptr [rsp+50H]
       xorpd    xmm0, xmm0
       movdqu   qword ptr [rdx], xmm0
       mov      qword ptr [rdx+16], rcx
       mov      dword ptr [rsp+48H], -1
G_M54617_IG05:
       movdqu   xmm0, qword ptr [rsp+50H]
       movdqu   qword ptr [rsp+20H], xmm0
       mov      rcx, qword ptr [rsp+60H]
       mov      qword ptr [rsp+30H], rcx
G_M54617_IG06:
       lea      rcx, bword ptr [rsp+30H]
       lea      rdx, bword ptr [rsp+38H]
       call     AsyncTaskMethodBuilder`1:Start(byref):this
       lea      rcx, bword ptr [rsp+50H]
       mov      rdx, rsi
       call     AsyncValueTaskMethodBuilder`1:get_Task():struct:this
```

**Comment by benaadams** [comment]
Updated summary with current 2 options

**Comment by benaadams** [comment]
> Why can't it just do:

Ah because `VoidTaskResult` is nothing; so it takes no space? Still seems a bit weird - but will work for now.

**Comment by stephentoub** [comment]
> Yeah, because it already outputs for AsyncValueTaskMethodBuilder which does the wrapping

AsyncValueTaskMethodBuilder has the AsyncTaskMethodBuilder as a field:
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Runtime/CompilerServices/AsyncValueTaskMethodBuilder.cs#L17
not as a local.

> is carrying an unnecessarily Task field that is never used

Why do you say it's carrying it?  An arbitrary async method builder need not have it as a field; AsyncValueTaskMethodBuilder does, because it already needs it as a field for the rest of the task-based implementation, but another async method builder need not... it can literally just be a local used to call Start.

I'm not seeing the value of this proposal.

**Comment by benaadams** [comment]
> I'm not seeing the value of this proposal.

Isn't the api a bit weird?
```csharp
partial class MyTaskTypeMethodBuilder<T>
{
    public void Start<TStateMachine>(ref TStateMachine stateMachine)
        where TStateMachine : IAsyncStateMachine
    {
        AsyncTaskMethodBuilder b = default; // create empty AsyncTaskMethodBuilder to access method
        b.Start<TStateMachine>(ref stateMachine); // provides correct EC semantics
    }
}
```
vs this
```csharp
partial class MyTaskTypeMethodBuilder<T>
{
    public void Start<TStateMachine>(ref TStateMachine stateMachine)
      where TStateMachine : IAsyncStateMachine
        => AsyncMethodBuilder.Start(ref stateMachine); // provides correct EC semantics
}
```

**Comment by stephentoub** [comment]
> Isn't the api a bit weird?

A bit, maybe, but perfectly functional and it already exists.  The new proposed method doesn't add any functional value over the already existing one.  If this were code a developer was needing to write 100 times a day, then yeah, one line instead of two would be nice, but I can count on one hand the number of times I've seen someone besides me implement an async method builder.

**Comment by benaadams** [comment]
> but I can count on one hand the number of times I've seen someone besides me implement an async method builder.

Heh; well it caught me out, so in 8 years when there's another person... I'll reopen 😉

**Comment by stephentoub** [comment]
:smile:
