### ISSUE TITLE
Regex null-refs while processing pattern.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/corefx#26485]
Found while writing dotnet/roslyn#23984 (a usable regex parser for use in IDE scenarios)

Regex pattern is: ```(?(?S))```

Exception happens here:

```
 	System.Text.RegularExpressions.RegexWriter.RegexCodeFromRegexTree(tree)	Unknown
 	System.Text.RegularExpressions.Regex.Regex(pattern, options, matchTimeout, useCache)	Unknown
 	System.Text.RegularExpressions.Regex.Regex(pattern, options)	Unknown
```

--

Note: https://github.com/dotnet/roslyn/pull/23984 comes with several thousands of regex tests that could be adoped by corefx to help ensure that parsing either succeeds, or throws an ArgumentException as per the regex constructor documentation https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.-ctor?view=netframework-4.7.1#System_Text_RegularExpressions_Regex__ctor_System_String_

**Comment by stephentoub** [comment]
Does that repro on .NET Core, with https://github.com/dotnet/corefx/pull/16609?

**Comment by CyrusNajmabadi** [comment]
Probably not :)   But i'm not sure how to do a .net core test.  

Also, will such a fix make it into the normal framework?  Thanks!

**Comment by CyrusNajmabadi** [comment]
Note: my use case is similar to the one in the original bug you linked to:

> This behaviour is especially unpleasant in case of "regex tester" application (such as http://regexator.net) which tries to continually evaluate user input as regex pattern.

With the Roslyn impl i've been writing, i'd *love* to have a bit of code that checked my impl against the stock .net impl.  i.e. for any given user pattern, i'd like to be able to do the following:

1. Run the user pattern through the .net regex constructor.
2. Run the user pattern through my new regex parser.
3. Ensure that if .net fails to parse, my regex parser also fails to parser.  If not, report bug to MS.
4. Ensure that if .net parses, my regex parser also parses without any errors.  If not, report bug to MS.
5. Ensure that .net fails to parse that my regex parser produces the same error as .net.  If not, report bug to MS.

This would help find any deviations very quickly without negatively impacting the user experience.  In the case of '4' or '5', i would also suppress reporting any of my own parser errors as they'd clearly be specious.

However, i can't really do this given some of the issues in the existing parser.  For example https://github.com/dotnet/corefx/issues/26484 would be pretty bad in an actual production system.  Basically, today, i can't pass untrusted user input to Regex's constructor as it may exhibit very bad behavior.  It would be very nice to have that to help augment the user experience i want to provide around regexes.

**Comment by stephentoub** [comment]
> But i'm not sure how to do a .net core test.

I just created a new .NET Core console app in VS. On .NET Core 2.0, this:
```C#
class Program
{
    static void Main() => System.Text.RegularExpressions.Regex.IsMatch("abc", "(?(?S))");
}
```
produces:
```
Unhandled Exception: System.ArgumentException: parsing '(?(?S))' - Unrecognized grouping construct.
   at System.Text.RegularExpressions.RegexParser.ScanGroupOpen()
   at System.Text.RegularExpressions.RegexParser.ScanRegex()
   at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
   at System.Text.RegularExpressions.Regex.IsMatch(String input, String pattern)
   at Program.Main()
```

> will such a fix make it into the normal framework?

I tagged it as netfx-port-consider.  @AlexGhiondea and @ViktorHofer would need to evaluate it.

**Comment by stephentoub** [comment]
> Ensure that if .net fails to parse, my regex parser also fails to parse. If not, report bug to MS.
Ensure that if .net parses, my regex parser also parses without any errors. If not, report bug to MS.
Ensure that .net fails to parse that my regex parser produces the same error as .net. If not, report bug to MS.

So if there's any discrepancy between the .NET parser and yours, it's a bug in the .NET one? :smile?

**Comment by CyrusNajmabadi** [comment]
> So if there's any discrepancy between the .NET parser and yours, it's a bug in the .NET one? 

For certain :D

On a serious note, i have taken the approach where i treat the .net regex parser as gospel.  My thinking is that it's likely never going to change (except for fixing things like the null-ref) as there is too high a risk of breaking changes.  

For example, i think i found a bug in the current parser with: ```(cat)(\c[*)(dog)```

According to .net regex rules ```\c[``` is supposed to "Matches the ASCII control character that is specified by X or x, where X or x is the letter of the control character."  So, in this case it should match the ```[``` control character (equivalent to ```\u001b```).  But, instead, the .net regex parser fails on this.  The reason for this is that it does a prepass where it attempts to count all the capture.  But during that prepass escape handling is different from the normal parse:

https://github.com/dotnet/corefx/blob/353bdc62ccb5c56148bf0e31814f1fd4f84a7fd9/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexParser.cs#L1644-L1649

As you can see, when it sees an escape ```\```, it just skips the next character and the proceeds to scanning normally.  This means it only skips the ```\c``` and goes back to its normal loop.  This makes it think that ```[``` is the start of a character class, which then causes it to fail since that character class is unterminated.

**Comment by danmosemsft** [comment]
I think we would take correctness fixes.

**Comment by danmosemsft** [comment]
The issue here was fixed in https://github.com/dotnet/corefx/issues/1476 which is already tagged netfx-port-consider. So I think we can close this one.
