### ISSUE TITLE
HttpClient: remove HttpVersionInternal

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#26492]
This class seems to just duplicate the public HttpVersion.

https://github.com/dotnet/corefx/blob/050288e637d5c43be5c208d9eeeed690b597c64f/src/System.Net.Primitives/src/System/Net/HttpVersion.cs#L7-L13
https://github.com/dotnet/corefx/blob/050288e637d5c43be5c208d9eeeed690b597c64f/src/Common/src/System/Net/HttpVersionInternal.cs#L9-L15

**Comment by karelz** [comment]
I wondered about the same - if the internal is not necessary, we should remove it.
