### ISSUE TITLE
Passing additional CMake arguments to Native build

### ISSUE THREAD

**Issue by alpencolt** [dotnet/corefx#26508]
`build-native.sh` has options `cmakeargs` for passing additional arguments to CMake. But if I want add `-D_FORTIFY_SOURCE=2` option to `CXXFLAGS` it will be applied to `corefx/src/Native/Unix/configure.cmake` (which cause errors on test programs compilation).
If I add this option to `corefx/src/Native/Unix/CMakeLists.txt` it will applied to source code only (as expected).

Is there other way to pass this and others options to build without patching source code? If not is it possible to change `cmakeargs` behavior or add some other logic?

This behavior is the same for CoreCLR too.

cc @BruceForstall @jkotas 
cc @chunseoklee

**Comment by jkotas** [comment]
@janvorli

**Comment by BruceForstall** [comment]
@alpencolt I'm afraid you're beyond my level of cmake / build system expertise.

**Comment by janvorli** [comment]
Hmm, I was pretty sure I've replied to this yesterday, but the window probably get lost before I have sent it.
I am not sure I understand how defining a cmake variable using the cmakeargs automatically results in setting the compiler option. You need to have your own code in the cmake scripts to set the compiler define if the cmake variable is set, right? And then you can choose where to put it and what to influence. @alpencolt can you please explain to me what I am missing?

**Comment by alpencolt** [comment]
@janvorli Tizen project is needed to set some global compiler and linker options (e.g. `D_FORTIFY_SOURCE=2`) for all modules included to OS, sometimes it might be list of options (`-fstack-protector-strong -D_FORTIFY_SOURCE=2` or others). This list can be different for different releases and we don't really modify CoreCL/FX sources for this purpose(it's worth case).

Better option is passing this additional options and defines through global variable or some command line key and read them in `CMakeLists.txt`. The main point we are needed is applying this compiler/linker flags only to CoreCLR/FX source and not to `configure.cmake`. Since `configure.cmake` failed on easiest checks.
`cmakeargs` option doesn't provide necessary functionality (may be we use it wrong way?). It isn't pass arguments as we expected  and it doesn't work with list of options (e.g. `CXXFLAGS+=-fstack-protector-strong -D_FORTIFY_SOURCE=2`).

Can we solve this issue by existed tools? If not can we add this functionality to upstream?

**Comment by janvorli** [comment]
@alpencolt I think the best solution for this would be to pass a single cmake variable containing the compiler options and then using them in the CMakeLists.txt where you want them to take effect.
So, we could add support for that to coreclr / corefx and then you can pass whatever options you want through that without further touching the sources in the future.
So we would add a cmake variable named e.g. `CLR_ADDITIONAL_COMPILER_OPTIONS`. On the build command line, you would add `cmakeargs "-DCLR_ADDITIONAL_COMPILER_OPTIONS=-fstack-protector-strong;-D_FORTIFY_SOURCE=2"`. Please note the `;` separating the options and the quotes around the whole option, they are necessary to ensure that the options are correctly passed to cmake.
In the compileoptions.cmake, we would add `add_compile_options(${CLR_ADDITIONAL_COMPILER_OPTIONS})` inside the initial `if (CLR_CMAKE_PLATFORM_UNIX)`.
That should be all that's needed to enable passing in any compiler options you want.

**Comment by alpencolt** [comment]
@janvorli great! Thank you.
I will prepare PR.

**Comment by alpencolt** [comment]
@janvorli `corefx/Tools/run.exe` which is called from `corefx/run.sh` doesn't keep quotes on Linux. So I call for example:
```
./build-native.sh -Release -buildArch=armel -- clang3.8 cmakeargs '-DCLR_FIRST=1 -DCLR_SECOND=2'
```
String `-DCLR_FIRST=1 -DCLR_SECOND=2` can be handled as one argument (by using `$7` or other number depending from position) in all scripts before `corefx/Tools/run.exe`. But after `-DCLR_FIRST=1 ` and `-DCLR_SECOND=2` are two different arguments (`$7` and `$8`).
Does it OK? How can I fix `run.exe` behavior?

**Comment by janvorli** [comment]
The solution is simple - pass the two defines separately:
```sh
./build-native.sh -Release -buildArch=armel -- clang3.8 cmakeargs -DCLR_FIRST=1 cmakeargs -DCLR_SECOND=2
```
