### ISSUE TITLE
[API] Timer.UnsafeCreate

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#26523]
Suggested in https://github.com/dotnet/corefx/pull/26071#issuecomment-358820050
```csharp
namespace System.Threading
{
    partial class Timer
    {
        static Timer UnsafeCreate(TimerCallback callback, 
                                  object state, 
                                  TimeSpan dueTime, 
                                  TimeSpan period);
    }
}
```
Creates a timer that doesn't capture AsyncLocal state (for lazy init for global timers from partially unrelated code)

Related fixes https://github.com/dotnet/corefx/pull/26065, https://github.com/dotnet/corefx/pull/26066, https://github.com/dotnet/corefx/pull/26071, https://github.com/dotnet/corefx/pull/26077, https://github.com/dotnet/corefx/pull/26068

**Comment by jnm2** [comment]
Is `Unsafe` in the context of threading always about AsyncLocal? Seeing the title, I immediately wondered where this was coming from and thought of `UnsafeOnCompleted`.

**Comment by stephentoub** [comment]
> Is Unsafe in the context of threading always about AsyncLocal?

It's typically about not flowing ExecutionContext, e.g. ThreadPool.UnsafeQueueUserWorkItem is the same as QueueUserWorkItem but doesn't flow EC, UnsafeOnCompleted is the same as OnCompleted but need not flow EC, etc.  Timer.UnsafeCreate would be similar, the same as a Timer's ctor but without flowing EC.

(AsyncLocal data flows as part of EC.)

**Comment by benaadams** [comment]
Related issues https://github.com/dotnet/coreclr/pull/18670, https://github.com/aspnet/HttpClientFactory/issues/171

**Comment by benaadams** [comment]
Another instance where it would be useful https://github.com/aspnet/SignalR/pull/2904

**Comment by benaadams** [comment]
Current (ugly) workaround is:
```csharp
bool restoreFlow = false;
try
{
    if (!ExecutionContext.IsFlowSuppressed())
    {
        ExecutionContext.SuppressFlow();
        restoreFlow = true;
    }
    
    // Create timer here
}
finally
{
    if (restoreFlow)
    {
        ExecutionContext.RestoreFlow();
    }
}
```

**Comment by benaadams** [comment]
Another instance where it would be useful https://github.com/aspnet/Razor/pull/2565

**Comment by stephentoub** [comment]
Alternate / augmented proposal in https://github.com/dotnet/corefx/issues/32866.

**Comment by terrajobst** [comment]
API looks reasonable.

**Comment by terrajobst** [comment]
Just noticed @stephentoub's alternative. Looks like @vancem  and @stephentoub should first decide which avenue to pursue.

**Comment by stephentoub** [comment]
This is effectively a subset of #32866 (the only difference as far as this proposal is concerned is an extra optional argument added in the other proposal).  We should do #32866.

**Comment by terrajobst** [comment]
Since we approved #32866 we can close this.
