### ISSUE TITLE
System.Runtime.CompilerServices.Unsafe.dll  can't be loaded by Xamarin.Mac

### ISSUE THREAD

**Issue by lsvhome** [dotnet/corefx#26520]
Xamarin.Mac can't load System.Runtime.CompilerServices.Unsafe.dll which used within Microsoft.Extensions.Primitives.

The issue is: System.Runtime.CompilerServices.Unsafe isn't supported in current version Xamarin.Mac v4.x.x.x (and probably, Mono v4.5 and later), which supports netstandard2.0. So lot of packages, which require this library as dependency or sub-dependency are not-runnable at those platforms (but still compilable)

Microsoft.Extensions.Primitives used within lot of base libraries e.g 
Microsoft.Extensions.Options,
Microsoft.Extensions.Caching.Abstractions,
Microsoft.Extensions.Configuration.Abstractions etc.

They are used at least within Microsoft.EntityFrameworkCore

So, Microsoft.EntityFrameworkCore unusable with Xamarin.Mac

Example project with issue appearing available here: [example project](https://github.com/lsvhome/RuntimeBugAppearance). This project is compilable, but it crashes at runtime. More details described [here](https://github.com/aspnet/Common/pull/308)

[Rejected bugfix #1](https://github.com/aspnet/Common/pull/308)
[Rejected bugfix #2](https://github.com/aspnet/Common/pull/309)
[Linked issue](https://github.com/aspnet/Home/issues/2790)

-----

below you may see piece of output of application which uses package [Microsoft.EntityFrameworkCore.Sqlite](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Sqlite)

...
Loaded assembly: /Users/testuser/Projects/exampleapplication/exampleapplication.Mac/bin/Debug/exampleapplication.app/Contents/MonoBundle/Microsoft.Extensions.Primitives.dll [External]
Could not find `System.Runtime.CompilerServices.Unsafe` referenced by assembly `Microsoft.Extensions.Primitives, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60`.
Could not find `System.Runtime.CompilerServices.Unsafe` referenced by assembly `Microsoft.Extensions.Caching.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60`.
Could not find `System.Runtime.CompilerServices.Unsafe` referenced by assembly `Microsoft.EntityFrameworkCore, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60`.
Could not find `System.Runtime.CompilerServices.Unsafe` referenced by assembly `exampleapplication, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null`.

**Comment by benaadams** [comment]
It should be compatible with Xamarin.Mac 2.0+ and .NETStandard 2.0 https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe/ is the build not pulling in transitive dependencies?

![image](https://user-images.githubusercontent.com/1142958/35246683-78231b1e-ffbf-11e7-9498-cbea95088cee.png)

**Comment by karelz** [comment]
cc @marek-safar
