### ISSUE TITLE
ThreadPoolBoundHandle.FreeNativeOverlapped throwing in FSW in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#2653]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/2771/consoleFull
```
Discovering: System.IO.FileSystem.Watcher.Tests
  Discovered:  System.IO.FileSystem.Watcher.Tests
  Starting:    System.IO.FileSystem.Watcher.Tests
  
  Unhandled Exception: System.ArgumentException: 'overlapped' was not allocated by this ThreadPoolBoundHandle instance.
  Parameter name: overlapped
     at System.Threading.ThreadPoolBoundHandle.FreeNativeOverlapped(NativeOverlapped* overlapped)
     at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
     at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
     at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
d:\j\workspace\dotnet_corefx_windows_release_prtest\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00069\lib\tests.targets(130,5): warning MSB3073: The command "CoreRun.exe xunit.console.netcore.exe System.IO.FileSystem.Watcher.Tests.dll  -xml testResults.xml -notrait category=nonwindowstests  -notrait category=OuterLoop -notrait category=failing " exited with code -532462766. [d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.IO.FileSystem.Watcher\tests\System.IO.FileSystem.Watcher.Tests.csproj]
d:\j\workspace\dotnet_corefx_windows_release_prtest\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00069\lib\tests.targets(141,5): error : One or more tests failed while running tests from 'System.IO.FileSystem.Watcher.Tests' please check log for details! [d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.IO.FileSystem.Watcher\tests\System.IO.FileSystem.Watcher.Tests.csproj]
```

**Comment by stephentoub** [comment]
cc: @ericeil, @chcosta, @ericstj

**Comment by nguerrera** [comment]
Hit again here: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/2787/console

**Comment by nguerrera** [comment]
And again: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug/924/console

**Comment by ericeil** [comment]
I don't see, in the test output referenced so far, any indication of *which* test actually failed (except that it was a FileSystemWatcher test).  If someone knows where to find that, it might help diagnose this.

Without more info, I'd guess that the NativeOverlapped is being free'd twice

**Comment by nguerrera** [comment]
Huge speculation looking at the code, but I see some double-free potential if ReadDirectoryChangesW can return failure but still invoke the completion callback. However, f that's actually  possible I'm not sure how we could prevent it without leaking. Maybe it's dependent on GetLastError() whether we should free or wait for callback?

**Comment by nguerrera** [comment]
Just hit it again. :(

My last theory seems highly unlikely. New theory: could we already have disposed _threadPoolBinding?

**Comment by nguerrera** [comment]
Hmm, that's actually supposed to be supported I see.

**Comment by stephentoub** [comment]
I just took a quick look.  Here's my theory:
The Monitor method calls _threadPoolBinding.AllocateNativeOverlapped (https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs#L140) to get a NativeOverlapped*, which it then uses with ReadDirectoryChangesW.  Since this Monitor operation is potentially asynchronous from the creator of the FSW, it's possible for that main thread to set EnableRaisingEvents to false, thereby stopping event processing.  This can cause ReadDirectoryChangesW to fail, and there's code that's meant to handle that (catching an ObjectDisposedException).  If RDCW does fail, then the finally block calls _threadPoolBinding.FreeNativeOverlapped with the allocated NativeOverlapped from earlier.  But if in the meantime EnableRaisingEvents was set back to true to restart processing, then a new binding could have been created (https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs#L46), such that the _threadPoolBinding used to free is different than the one needed to allocate.

If my theory is true, why is this only showing up in tests now?  Because until last night when this new test got checked in (https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.Changed.cs#L183-L189), we appear to have had any tests that exercised setting EnableRaiseEvents to false and back to true while events were arriving.

**Comment by nguerrera** [comment]
@stephentoub Thanks. Makes sense! Who's on point to fix this? At a minimum, we should mark that test ActiveIssue ASAP because we're hitting this quite a lot. I'm headed out of town and on my phone.

**Comment by stephentoub** [comment]
I'll fix it.  Using a local copy of the handle instead of the one on the instance should address it.

**Comment by nguerrera** [comment]
Thanks!
