### ISSUE TITLE
# Issue while signing the TPM protected keys.

### ISSUE THREAD

**Issue by mathisharp** [dotnet/corefx#26541]
* Summary
    I can able to create the TPM protected key by passing the provider while creating the key below is the piece of code.
 CngKey.Create(CngAlgorithm.ECDsaP256, _keyName, 
                new CngKeyCreationParameters { KeyCreationOptions = CngKeyCreationOptions.MachineKey,Provider = new CngProvider("Microsoft Platform Crypto Provider") });

I can able to create the TPM protected key and open the key as well. The problem is while signing the key. Since the algorithm group is set to RSA instead of ECDSA. This algorithm group is set based on the provider at this point it is setting the wrong algorithm group internally.

* Reference Source Browser 
https://github.com/Microsoft/referencesource/blob/master/System.Core/System/Security/Cryptography/CngKey.cs

# Solution:
  If the algorithm group is set to appropriate group then the signing won't be a problem. Please update ASAP

**Comment by bartonjs** [comment]
Do you see an error in the source file you linked?  For the most part we just pass things through to Windows CNG, so if something isn't working it's hard for us to make it work.

A minimal "working" repro would be helpful.

**Comment by mathisharp** [comment]
[TPMKeyStore.zip](https://github.com/dotnet/corefx/files/1684190/TPMKeyStore.zip)

I have attached the sample code and the screenshot of the error.  The issue while signing the data, the specific method is SignData(byte[] data).  I have highlighted the algorithm is set to RSA instead of ECDsa. Please check and consider as high priority.

**Comment by karelz** [comment]
> @mathisharp Please check and consider as high priority.

Any specific reason for treating it as high priority?
In general, we assess priority of incoming issues based on their impact on customers (1 customer impacted here) and how common the scenario is compared to others. Availability of a small repro we can reproduce locally also plays a role (hopefully that is settled above).

**Comment by mrhprasanna** [comment]
Hi @karelz  We are also facing the same issue while trying to sign using TPM provider exposed by CNG. It is stopping our release and we are strongly dependent on it.

**Comment by karelz** [comment]
@mrhprasanna how do you know you are hitting exactly the same error? Did you check the repro above?

If it is blocking your product, I would recommend to contact Microsoft Support (if you have a contract) to get the right level of engagement from Customer support. We will assess impact and priority on GitHub based on available information here, which might not align with the urgency you might need.

Just to clarify: Are you are hitting the problem on .NET Core or on .NET Framework? Which OS?

**Comment by bartonjs** [comment]
I brought this up with the CNG team, and it has been acknowledged as an issue in the library that .NET depends on, there's nothing that .NET can really do here.
