### ISSUE TITLE
SqlBulkCopy.WriteToServer(table) fails with DBNull strings, and empty strings on varchar(max) columns

### ISSUE THREAD

**Issue by stevenreddie** [dotnet/corefx#26546]
I have hit two issues with strings in SqlBulkCopy.WriteToServer(DataTable) in .Net Core and found that the code functions properly on .Net. This is running against Azure SQL.

Here is a cut-down example, first the DB setup, then C# fragment, then the results:

```
CREATE TABLE TestVarchar100 (
    Str varchar(100) NULL
)
CREATE TABLE TestVarcharMax (
    Str varchar(max) NULL
)
```

```
static void Test(SqlConnection connection, string tableName, object strValue)
{
    string printableStrValue = (strValue is DBNull) ? "DBNull" : $"\"{strValue}\"";

    try
    {
        using (SqlBulkCopy bulkCopier = new SqlBulkCopy(connection))
        {
            var table = new DataTable(tableName);

            table.Columns.Add(new DataColumn("Str", Type.GetType("System.String")));

            var row = table.NewRow();
            row["Str"] = strValue;
            table.Rows.Add(row);

            bulkCopier.BatchSize = 100;
            bulkCopier.DestinationTableName = tableName;
            bulkCopier.BulkCopyTimeout = 120;
            bulkCopier.WriteToServer(table);

            Console.WriteLine($"Setting {tableName}.Str = {printableStrValue} succeeded");
        }
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Setting {tableName}.Str = {printableStrValue} FAILED: {ex.Message}");
    }
}

static void TestAll(string connectionString)
{
    using (SqlConnection connection = new SqlConnection(connectionString))
    {
        connection.Open();

        Test(connection, "TestVarchar100", "foo");
        Test(connection, "TestVarchar100", "");
        Test(connection, "TestVarchar100", DBNull.Value);

        Test(connection, "TestVarcharMax", "foo");
        Test(connection, "TestVarcharMax", "");
        Test(connection, "TestVarcharMax", DBNull.Value);
    }
}

static void Main(string[] args)
{
    Console.WriteLine($"Version: {Environment.Version.ToString()}");
    TestAll(ConfigurationManager.ConnectionStrings["TestVarcharDB"].ConnectionString);
}
```

Running against .NET gives:
```
Version: 4.0.30319.42000
Setting TestVarchar100.Str = "foo" succeeded
Setting TestVarchar100.Str = "" succeeded
Setting TestVarchar100.Str = DBNull succeeded
Setting TestVarcharMax.Str = "foo" succeeded
Setting TestVarcharMax.Str = "" succeeded
Setting TestVarcharMax.Str = DBNull succeeded
```

Running against .Net Core (on a Mac) gives:
```
Version: 4.0.30319.42000
Setting TestVarchar100.Str = "foo" succeeded
Setting TestVarchar100.Str = "" succeeded
Setting TestVarchar100.Str = DBNull FAILED: Specified cast is not valid.
Setting TestVarcharMax.Str = "foo" FAILED: Bulk load data was expected but not sent. The batch will be terminated.
Setting TestVarcharMax.Str = "" FAILED: The service has encountered an error processing your request. Please try again. Error code 4804.
Setting TestVarcharMax.Str = DBNull FAILED: Unable to read data from the transport connection: Connection reset by peer.
```
However, when I first started debugging the issue against my real code (which attempted to insert rows with some varchar(max) columns set to DBNull), I was getting error 4815:
```
The service has encountered an error processing your request. Please try again. Error code 4815.
```

[Please let me know the correct repo to report this if this isn't it.]

**Comment by saurabh500** [comment]
cc @corivera

**Comment by saurabh500** [comment]
@stevenreddie can you provide a bit of repro code as well?

**Comment by saurabh500** [comment]
@stevenreddie Disregard my previous comment.

**Comment by corivera** [comment]
@stevenreddie This code doesn't repro for me in master when testing against an Azure SQL DB. What version of System.Data.SqlClient.dll are you using? The environment version is just a hard-coded value in Core.

**Comment by stevenreddie** [comment]
How do I go about checking that? I am running Visual Studio Community on Mac, and I let everything get updated and tested again before reporting.

**Comment by corivera** [comment]
What SqlClient package version is referenced in the csproj?

**Comment by stevenreddie** [comment]
The csproj file doesn't appear to have any version info for System.Data. However, in the IDE under Reference, System.Data is listed as /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/4.6.1-api/System.Data.dll. Also the .NET runtime seems to be Mono 5.4.1.7. Does that cover what you need?

**Comment by corivera** [comment]
Ah, okay. Mono is a completely separate framework from .NET Core. 

@danmosemsft Who owns Mono?

**Comment by stevenreddie** [comment]
I had thought that .NET Core provided these components (and that .NET Core was a multi-platform fork of parts of .NET). To be clear, I installed Visual Studio Community on my Mac and simply loaded a solution that had been developed on Windows (without changing any settings).

**Comment by corivera** [comment]
Mono is a different cross-plat implementation of .NET Framework. Core & Mono implement the same APIs (as far as I know), but are separate frameworks. Visual Studio for Mac is built on top of Mono.

The Mono repo can be found here: https://github.com/mono/mono

**Comment by corivera** [comment]
If you would like to use .NET Core in Visual Studio for Mac, then here is some documentation for it: https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-mac-vs

**Comment by stevenreddie** [comment]
Strange, I never installed Mono, only .NET Core and Visual Studio, so it's very strange to me that I'm not using .NET Core from within Visual Studio. Those are the instructions that I followed. I guess I'll repeat this issue on the Mono project.

**Comment by danmosemsft** [comment]
@corivera, @marek-safar is a contact for Mono.

**Comment by corivera** [comment]
Closing since this is an issue with Mono's version of System.Data.
