### ISSUE TITLE
HTTP Status Description is parsed incorrectly on Windows

### ISSUE THREAD

**Issue by caesar1995** [dotnet/corefx#26540]
.NET Core will trims out space characters when parsing HTTP status description on Windows. This is not correct.

Quote https://github.com/dotnet/corefx/pull/26525#issuecomment-359627454

Based on the ABNF in section 3.1.2 of [the RFC](https://tools.ietf.org/html/rfc7230):
```
status-line = HTTP-version SP status-code SP reason-phrase CRLF
reason-phrase  = *( HTAB / SP / VCHAR / obs-text )
```
The reason phrase (status description) can consist entirely of spaces (SP). We should keep the spaces as part of the status description.

```c#
        System.Net.Http.Functional.Tests.HttpProtocolTests_Dribble.GetAsync_ExpectedStatusCodeAndReason_Success(statusLine: \"HTTP/1.1 200      Something\", expectedStatusCode: 200, expectedReason: \"     Something\") [FAIL]
        Assert.Equal() Failure
                  ↓ (pos 0)
        Expected:      Something
        Actual:   Something
                  ↑ (pos 0)
        Stack Trace:
           D:\corefx\src\System.Net.Http\tests\FunctionalTests\HttpProtocolTests.cs(65,0): at System.Net.Http.Functional.Tests.HttpProtocolTests.<>c__DisplayClass3_0.<<GetAsyncSuccessHelper>b__0>d.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
           D:\corefx\src\Common\tests\System\Net\Http\LoopbackServer.cs(67,0): at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass3_0.<CreateServerAsync>b__0(Task t)
           E:\A\_work\1275\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs(151,0): at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
           E:\A\_work\1275\s\src\mscorlib\src\System\Threading\Tasks\Task.cs(2440,0): at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
           --- End of stack trace from previous location where exception was thrown ---
           D:\corefx\src\System.Net.Http\tests\FunctionalTests\HttpProtocolTests.cs(50,0): at System.Net.Http.Functional.Tests.HttpProtocolTests.<GetAsyncSuccessHelper>d__3.MoveNext()
           D:\corefx\src\System.Net.Http\tests\FunctionalTests\HttpProtocolTests.cs(34,0): at System.Net.Http.Functional.Tests.HttpProtocolTests.<GetAsync_ExpectedStatusCodeAndReason_Success>d__1.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
```

Managed Handler doesn't has this issue.

**Comment by caesar1995** [comment]
The [WinHttpHandler's default behavior](https://msdn.microsoft.com/en-us/library/windows/desktop/aa384102(v=vs.85).aspx) is to get trimmed status description (not documented, but I verified in the code). We cannot change its implementation (we can only call its API), therefore, this test case should be disabled on .NET Core Windows run.
``` c#
Interop.WinHttp.WinHttpQueryHeaders(
                requestHandle,
                infoLevel, // WINHTTP_QUERY_STATUS_TEXT, Receives additional text returned by the server on the response line.
                Interop.WinHttp.WINHTTP_HEADER_NAME_BY_INDEX,
                new IntPtr(buffer),
                ref bufferLengthInBytes,
                ref index);
```

**Comment by caesar1995** [comment]
Actually there is a workaround, instead of calling WinHttpHandler APIs, we can get raw HTTP header and parse is by ourselves, so that we can have control over it to 1. change behavior 2. throw Exception accordingly.

```c#
BOOL WINAPI WinHttpQueryHeaders(
  _In_     HINTERNET hRequest,
  _In_     DWORD     dwInfoLevel, // Pass WINHTTP_QUERY_RAW_HEADERS_CRLF here to get the raw header.
  _In_opt_ LPCWSTR   pwszName,
  _Out_    LPVOID    lpBuffer,
  _Inout_  LPDWORD   lpdwBufferLength,
  _Inout_  LPDWORD   lpdwIndex
);
```

I'm hesitated to take this approach because this could be a breaking change for .NET Core on Windows since 2.0. (i.e., re-write WinHttpHanlder response parsing logic based on ManagedHandler&Framework, instead of calling its APIs).

I prefer disable the test. (Probably document the behavior difference somewhere). Same applies for #26542.

@dotnet/ncl Do you have any feedback?

**Comment by davidsh** [comment]
>@dotnet/ncl Do you have any feedback?

There already was a lot of work to stabilize the response header parsing for WinHttpHandler.  I don't see any need to touch that. This particular difference in parsing behavior doesn't impact customers.  It is basically a rare set of cases with invalid whitespace data.

So, disable/change tests as needed.  But don't make any product source changes for this.

**Comment by caesar1995** [comment]
Ok, I will submit a PR soon.

**Comment by karelz** [comment]
Agreed with @davidsh, it does not seem to be important enough scenario to go overboard in the case ;).
