### ISSUE TITLE
[Regression] Tests failed: System.IO.Compression.Brotli.Performance.Tests - 20min timeout on Windows

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#26566]
System.IO.Compression.Brotli.Performance.Tests test suite started failing with 'fire' on Windows platforms in build 20180120.01.
Looking at a few logs it seems that xunit doesn't print anything after initial output and infra kills it after 20 min:
```
Discovering: System.IO.Compression.Brotli.Performance.Tests
Discovered:  System.IO.Compression.Brotli.Performance.Tests
Starting:    System.IO.Compression.Brotli.Performance.Tests
```

Note Ubuntu17.04 'fire' failures are across all tests (the image went EOL), please ignore it. The platform should be removed from our test run matrix on 1/25.

## History of failures

Day | Build | Failures
-- | -- | --
1/20 | [20180120.01](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180120.01/workItem/System.IO.Compression.Brotli.Performance.Tests) | 4x (Win10-x86 & Win10.Core-x86 & Win7-x86 & Win8.1-x86)
1/20 | [20180120.02](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180120.02/workItem/System.IO.Compression.Brotli.Performance.Tests) | 4x (Win10-x86 & Win10.Core-x86 & Win7-x86 & Win8.1-x86)
1/21 | [20180121.01](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180121.01/workItem/System.IO.Compression.Brotli.Performance.Tests) | 4x (Win10-x86 & Win10.Core-x86 & Win7-x86 & Win8.1-x86)
1/21 | [20180121.02](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180121.02/workItem/System.IO.Compression.Brotli.Performance.Tests) | 3x (Win10-x86 & Win10.Core-x86 & Win7-x86)
1/22 | [20180122.01](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180122.01/workItem/System.IO.Compression.Brotli.Performance.Tests) | 4x (Win10-x86 & Win10.Core-x86 & Win7-x86 & Win8.1-x86)
1/22 | [20180122.02](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180122.02/workItem/System.IO.Compression.Brotli.Performance.Tests) | 4x (Win10-x86 & Win10.Core-x86 & Win7-x86 & Win8.1-x64)
1/23 | [20180123.01](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180123.01/workItem/System.IO.Compression.Brotli.Performance.Tests) | 3x (Win10.Core-x86 & Win7-x86 & Win8.1-x64)
1/23 | [20180123.04](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180123.04/workItem/System.IO.Compression.Brotli.Performance.Tests) | 4x (Win10-x86 & Win10.Core-x86 & Win7-x86 & Win8.1-x64)
1/24 | [20180124.02](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180124.02/workItem/System.IO.Compression.Brotli.Performance.Tests) | 5x (Win10-x86 & Win10.Core-x86 & Win7-x64 & Win7-x86 & Win8.1-x86)
1/24 | [20180124.06](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180124.06/workItem/System.IO.Compression.Brotli.Performance.Tests) | 1x (Win8.1-x64) - note: -x86 runs didn't execute in this build
1/25 | [20180125.01](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180125.01/workItem/System.IO.Compression.Brotli.Performance.Tests) | 3x (Win10-x86 & Win10.Core-x86 & Win7-x86)
1/25 | [20180125.06](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180125.06/workItem/System.IO.Compression.Brotli.Performance.Tests) | 5x (Win10-x86 & Win10.Core-x86 & Win7-x64 & Win7-x86 & Win8.1-x86)
1/25 | [20180125.08](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180125.08/workItem/System.IO.Compression.Brotli.Performance.Tests) | 5x (Win10-x86 & Win10.Core-x86 & Win7-x64 & Win7-x86 & Win8.1-x86)
1/26 | [20180126.03](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180126.03/workItem/System.IO.Compression.Brotli.Performance.Tests) | 5x (Win10-x86 & Win10.Core-x86 & Win7-x64 & Win7-x86 & Win8.1-x86)
1/27 | [20180127.01](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180127.01/workItem/System.IO.Compression.Brotli.Performance.Tests) | 5x (Win10-x86 & Win10.Core-x86 & Win7-x64 & Win7-x86 & Win8.1-x86)
1/27 | [20180127.04](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180127.04/workItem/System.IO.Compression.Brotli.Performance.Tests) | 5x (Win10-x86 & Win10.Core-x86 & Win7-x86 & Win8.1-x64 & Win8.1-x86)
1/28 | [20180128.01](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180128.01/workItem/System.IO.Compression.Brotli.Performance.Tests) | 5x (Win10-x86 & Win10.Core-x86 & Win7-x86 & Win8.1-x64 & Win8.1-x86)
1/28 | [20180128.04](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180128.04/workItem/System.IO.Compression.Brotli.Performance.Tests) | 5x (Win10-x86 & Win10.Core-x86 & Win7-x86 & Win8.1-x64 & Win8.1-x86)
1/29 | [20180129.01](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180129.01/workItem/System.IO.Compression.Brotli.Performance.Tests) | 5x (Win10-x86 & Win10.Core-x86 & Win7-x64 & Win7-x86 & Win8.1-x86)
1/29 | [20180129.05](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180129.05/workItem/System.IO.Compression.Brotli.Performance.Tests) | 1x (Win8.1-x64) - note: -x86 runs didn't execute in this build
1/30 | [20180130.01](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180130.01/workItem/System.IO.Compression.Brotli.Performance.Tests) | 5x (Win10-x86 & Win10.Core-x86 & Win7-x64 & Win7-x86 & Win8.1-x86)
1/30 | [20180130.05](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180130.05/workItem/System.IO.Compression.Brotli.Performance.Tests) | 5x (Win10-x86 & Win10.Core-x86 & Win7-x86 & Win8.1-x64 & Win8.1-x86)

**Comment by karelz** [comment]
@ianhays can you please take a look?

**Comment by ianhays** [comment]
Hmm. It's possible I added too many tests and they're just hitting the timeout limit. They do take a *very* long time on my machine. I'll see exactly how long, and shorten that if necessary to get them completing faster.

**Comment by karelz** [comment]
That might be the reason - successful run of Win8.1-x86 in [20180121.02](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180121.02/workItem/System.IO.Compression.Brotli.Performance.Tests/wilogs) claims 14:02 time (looking at timestamps it is 16:30) - quite close to the 20 min timeout.

**Comment by ianhays** [comment]
Yup, that's the reason. I've been running the perf tests for like an hour now and they're still chugging along.

**Comment by danmosemsft** [comment]
@Anipik I guess this is not true (no dumps uploaded -- no URL shown) and you are fixing?
```
2018-01-30 02:42:34,424: INFO: servicebusrepository(97): renew_workitem_lock: renew_workitem_lock Status Code: 200
2018-01-30 02:43:05,845: INFO: job(70): _create_and_upload_dump: Creating Dumps Process Exit Code: 0
2018-01-30 02:43:09,595: INFO: job(72): _create_and_upload_dump: Uploading Dumps Process Exit Code: 1
2018-01-30 02:43:09,595: INFO: job(73): _create_and_upload_dump: Dumps Created and Uploaded Successfully
2018-01-30 02:43:09,595: ERROR: job(43): kill: Job running for too long. Killing...

```

**Comment by danmosemsft** [comment]
@ianhays do you expect to have a fix soon? It hung in several configurations in both builds today.

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180130.01/workItem/System.IO.Compression.Brotli.Performance.Tests/wilogs

**Comment by Anipik** [comment]
@danmosemsft the PR is up for showing the upload link. The dump is being uploaded but still not able to get the PID of the required hung process. I am debugging the reason for this.

**Comment by Anipik** [comment]
@danmosemsft the dumps are not being uploaded because the upload website is under construction as we are adding an authentication layer on the website.

**Comment by Anipik** [comment]
The pr is up for showing the URL and I am waiting for matt`s approval for that

**Comment by karelz** [comment]
@ianhays alternatively, you can disable the tests, until the underlying problem, is addressed

**Comment by Priya91** [comment]
failed in PR run #26666

**Comment by stephentoub** [comment]
This is taking out a bunch of outerloop runs.  I'm going to disable them.
