### ISSUE TITLE
ManagedHandler and SslClientAuthenticationOptions

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#26567]
Currently the ManagedHandler's API is derived from the existing HttpClientHandler API, and thus has these properties related to SSL:
- ClientCertificates
- ServerCertificateCustomValidationCallback
- CheckCertificateRevocationList
- SslProtocols

But there are additional configurable features related to SSL that are supported by SslStream, e.g.
- LocalCertificateSelectionCallback 
- ApplicationProtocols 
- TargetHost
- CertificateRevocationCheckMode (instead of just a bool)
- EncryptionPolicy

and likely more to come.

As part of making ManagedHandler public, we should consider replacing all of the existing properties with one property for SslClientAuthenticationOptions.  That'll give the ManagedHandler all of these properties, while also making it easy for it to pass it through to SslStream, and it'll avoid the need to add additional properties to the handler API as additional properties are exposed on SslClientAuthenticationOptions; we'd simply need to update the implementation.

In doing this, we could then also look at updating ClientWebSocketOptions to take an SslClientAuthenticationOptions, such that it could just pass this through to ManagedHandler and implicitly pick up the implementation of all such options.

**Comment by geoffkizer** [comment]
> As part of making ManagedHandler public, we should consider replacing all of the existing properties with one property for SslClientAuthenticationOptions.

This makes sense, but it's slightly tricky because the managed handler wants to actually set TargetHost and (in the future, for HTTP2) ApplicationProtocols.  We need to work out the details here, e.g.: if TargetHost is already set, do we override?
