### ISSUE TITLE
SslStream.Read hangs (race condition on dispose?)

### ISSUE THREAD

**Issue by ayende** [dotnet/corefx#26572]
My process sometimes seems to hang, and I was able to capture a stack trace, it ends with:

```
 	System.Private.CoreLib.dll!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()	Unknown	Non-user code. Skipped loading symbols.
 	System.Net.Security.dll!System.Net.Security.SslState.CheckThrow(bool authSuccessCheck, bool shutdownCheck)	Unknown	Non-user code. Skipped loading symbols.
 	System.Net.Security.dll!System.Net.Security.SslState.SecureStream.get()	Unknown	Non-user code. Skipped loading symbols.
 	System.Net.Security.dll!System.Net.Security.SslStream.Read(byte[] buffer, int offset, int count)	Unknown	Non-user code. Skipped loading symbols.
```

Now, the specific scenario here is that I'm trying to dispose a connection, so I called the `SslStream.Dispose` from another thread, but it seems like it either didn't take or it might have corrupted some state.

The `SslStream` is wrapping a `NetworkStream`, and that one is safe to close while it is running, I'm _guessing_ that `SslStream` isn't?

**Comment by davidsh** [comment]
>The SslStream is wrapping a NetworkStream, and that one is safe to close while it is running, I'm guessing that SslStream isn't?

It should be thread-safe to do that.  If it isn't, it is probably a bug.

**Comment by davidsh** [comment]
cc: @Priya91

**Comment by Priya91** [comment]
@ayende Can you share a repro.

**Comment by ayende** [comment]
I don't have a reliable one, I basically run a 3000+ test suite and tried to kill it, but it hang.
I broke into the debugger and realized that this is stuck waiting for a thread to complete, and this thread is busy waiting for this method.

**Comment by Priya91** [comment]
Hmm other than reading code, there's not much action that can be taken here to figure out if there's a bug.

**Comment by ayende** [comment]
@Priya91 Assuming that this is something that I can reproduce, anything that I can provide to help?
I can probably take a memory dump, etc. 
I tried writing some code to reproduce this, but wasn't able to reproduce a hang.

As an aside, I'm assuming that like NetworkStream, it is safe to concurrently call SslStream.Write and SslStream.Read?

**Comment by Priya91** [comment]
> As an aside, I'm assuming that like NetworkStream, it is safe to concurrently call SslStream.Write and SslStream.Read?

Yes, SslStream doesn't allow multiple simultaneous Read operations or write operations, but there is no check for read and write being simultaneous.

**Comment by Priya91** [comment]
Have you considered the possibility that an additional Read was initiated and the code is just waiting to read data from server?

**Comment by ayende** [comment]
Shouldn't the dispose operation kill that? I explicitly want just that, to abort the current read operation.

**Comment by benaadams** [comment]
Probably behaves better with ReadAsync

**Comment by Priya91** [comment]
If the underlying stream is networkstream, the read on the network stream will throw on dipose and that will get thrown from sslstream, sslstream doesn't check for dispose before read/write operations, the underlying stream behavior will throw because of disconnected connection.

**Comment by ayende** [comment]
Okay, thanks
