### ISSUE TITLE
System.Data.DataSetExtensions has MSFT key in .NET Core and ECMA in Desktop, causing identities to be different

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#26575]
This type is causing to have different assembly identities in between .NET Core and NETFX, since we're stating in the OOB package that in NETFX the implementation is inbox, this breaks that support for when trying to use this type since it lives in System.Data for NETFX.

cc: @weshaggard @danmosemsft

**Comment by terrajobst** [comment]
> This type is causing to have different assembly identities in between .NET Core and NETFX,

In what sense? Are we missing a TF?

**Comment by weshaggard** [comment]
No it isn't a missing type-forward. It is a case where we have the exact same assembly identity System.Data.DataSetExtensions in core and netfx but this type doesn't live in that assembly in netfx. In netfx it lives in System.Data.dll so it cannot live in System.Data.DataSetExtensions in core and remain compatible. We need either need to move the type or change the identity of this library to not match desktop.

**Comment by safern** [comment]
I just realized that System.Data.DataSetExtensions have different PublicKey in .net core and netfx. That would make the identity not match right?

**Comment by weshaggard** [comment]
That makes things worse as it will cause all kinds of confusion. We should fix the key or change the name.

**Comment by safern** [comment]
We haven’t published any version of this package to NuGet so any would work fine I guess. So renaming wouldn’t hurt either. Any strong preference?

**Comment by weshaggard** [comment]
Our general stance is if we don't feel we are going to evolve it then we should just keep the same identity to avoid more assembly identities in the wild.

**Comment by safern** [comment]
Which it is the case here right? We don’t plan to add evolve this one? Or that is what it seems like, hasn’t have a significant change since it was ported. Then I would say try to match identities.

**Comment by weshaggard** [comment]
Yes I would say that is the case here. I suggest we fix the key and either remove or move down TypedTableBase into another assembly.

**Comment by safern** [comment]
Ok. I assigned to myself and will take care of it.

**Comment by safern** [comment]
I updated the issue title, since after revisiting it I found that I miss read the ApiCatalog on where the type lived in Full Framework, they are both in System.Data.DataSetExtensions. The only thing missing is to change the key to match. I will update https://github.com/dotnet/corefx/pull/26576 to have the right placeholder configurations and to match the public key.
