### ISSUE TITLE
[New test] CI failed: System.Net.WebSockets.WebSocketProtocol.Tests / WebSocketProtocol_CreateFromConnectedStream_Succeeds

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#26588]
The test failed in CI:

```
Assert.True() Failure
Expected: True
Actual:   False

at System.Net.WebSockets.Tests.WebSocketProtocolTests.<WebSocketProtocol_CreateFromConnectedStream_Succeeds>d__2.MoveNext() in D:\j\workspace\windows-TGrou---3ae484c8\src\System.Net.WebSockets.WebSocketProtocol\tests\WebSocketProtocolTests.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
```

## History of failures

Day | Build | OS | Details
-- | -- | -- | -- 
1/18 | 425dd3680cfc5b808a9b41b8d71c5a6a9c03a304 | Win10 | 16x failed
1/18 | 1956b2aa67f3f19be9a1d184215033637c8ab33c | Win10 | 2x failed
1/19 | 14f6df36f792307e6873c37dc201c98c03674504 | Win10 | 2x failed

@Priya91 is it something you would expect? Any chance the data I have is invalid?

**Comment by Priya91** [comment]
WebSocketProtocol is dependent on ManagedWebSockets, and it is completely managed.. so it should be the same everywhere.. @karelz Is there more information, like if this is full framework run or uwp run, or nano run. It would be nice to have a proper stack trace.

**Comment by karelz** [comment]
It was on .NET Core runs (I don't look at the other results yet).
The stack above is all we have.

It didn't repro since then until 1/23. Moreover I don't fully trust the build # mapping to PR. I am fine closing it as Not repro at this point.
