### ISSUE TITLE
PreSeededNestedStructure FSW test failing locally

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#2659]
This test is consistently failing for me when run locally (Win10 Enterprise RTM).
```
FileSystemWatcher_4000_Tests.FileSystemWatcher_Changed_PreSeededNestedStructure(includeSubdirectories: False) [FAIL]
        Should not observe a second file change event
        Expected: False
        Actual:   True
        Stack Trace:
           \corefx\src\System.IO.FileSystem.Watcher\tests\Utility\Utility.cs(109,0): at Utility.ExpectNoEvent(WaitHandle eventOccure
  d, String eventName, Int32 timeout)
           \corefx\src\System.IO.FileSystem.Watcher\tests\FileSystemWatcher.Changed.cs(197,0): at FileSystemWatcher_4000_Tests.FileS
  ystemWatcher_Changed_PreSeededNestedStructure(Boolean includeSubdirectories)
```

**Comment by stephentoub** [comment]
I have a fix.

**Comment by sokket** [comment]
Cool! What was the cause of the flakiness?

**Comment by stephentoub** [comment]
Creating/modifying/accessing files may also cause metadata on the parent directory structure to change, e.g. if you create a file dir1/dir2/dir3/file and you're watching for events on dir1 without including subdirectories, you may still get an event for dir2, because it's in dir1 and is affected when file is affected.  My simple fix is to switch to changes that aren't reflected up the hierarchy, e.g. changing attributes on the file and watching only for attribute change notifications.

This highlights though a miss we currently have in the FSW tests: we're checking for whether an event is fired, but not what it's fired for, e.g. we're not checking any of the filename information contained in the event.  That both makes the tests less robust (e.g. we could fire an event for something we don't actually care about but we don't ignore it) and less complete (e.g. we're not verifying the path information is what we expect it to be).

**Comment by sokket** [comment]
Gotcha, feel free to open an issue on me to fix that in the infrastructure...that's a good catch :)
