### ISSUE TITLE
Weak ETags are missing the W/ in the response

### ISSUE THREAD

**Issue by dustinmoris** [dotnet/corefx#26608]
Hi,

I have code like this:

```csharp
var responseHeaders = this.Response.GetTypedHeaders();
responseHeaders.ETag = new EntityTagHeaderValue(new StringSegment("\"some-etag\""), true);
```

which generates the following ETag header in the response:

```
ETag: "some-etag"
```

but instead it should be:

```
ETag: W/"some-etag"
```

One thing which I find weird is that the [constructor of the `EntityTagHeaderValue`](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Headers/EntityTagHeaderValue.cs/#L45) requires me to pass in a quoted value (e.g. `"some-etag"` instead of just `some-etag`), but it doesn't allow me to pass in the `W/` for the weak reference.

There is a comment saying:
> Note that we don't allow 'W/' prefixes for weak ETags in the 'tag' parameter. If the user wants to add a weak ETag, he can set 'isWeak' to true.

So I have specified `true` for `isWeak` and even though the [`.ToString()` method has been overridden to output the `W/`](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Headers/EntityTagHeaderValue.cs/#L76) the end result is still without it. Not sure where the bug is, but this gets lost somewhere along the line.

Overall this is confusing, because the constructor doesn't behave consistently. On one hand the caller is responsible for formatting the ETag properly by putting it into quotes (as it is defined in the HTTP spec), but then on the other hand the constructor doesn't allow the caller to format a weak reference properly with the `W/` up front.

**Comment by dustinmoris** [comment]
Maybe it's because it's late for me today, but something else is extremely confusing...

The docs and my code both show the constructor to require a `StringSegment`: https://docs.microsoft.com/en-us/dotnet/api/microsoft.net.http.headers.entitytagheadervalue.-ctor?view=aspnetcore-2.0

However, the linked file from above doesn't... also the namespaces are different:
`Microsoft.Net.Http.Headers` vs `System.Net.Http.Headers`??

Does the same class exist in two different namespaces and looks different?

**Comment by khellang** [comment]
ASP.NET Core have their own copies. See https://github.com/aspnet/Announcements/issues/244

**Comment by dustinmoris** [comment]
@khellang This is still super confusing... I feel like unless I follow every tweet and every discussion in the .NET Core repos it's extremely confusing to what all these things are. I get that they improved the class by utilizing StringSegment, but why on earth do we need to have two identical classes now in different namespaces instead of just updating one class to the new constructor type?

**Comment by dustinmoris** [comment]
Ok, nevermind... my tests where using `response.Headers.ETag.Tag` for checking whether the ETag was correct, but instead I should have used `response.Headers.ETag.ToString()`, because the `.Tag` property never contains the `W/`.
