### ISSUE TITLE
PropertyDescriptor - MemberDescriptor.Attributes returns base attribute instead of ancestor's attribute

### ISSUE THREAD

**Issue by k0st1x** [dotnet/corefx#26600]
"prop.Description" returns "A" instead of "B"
```c#
static void Main(string[] args) {
    var prop = (DescriptionAttribute)TypeDescriptor.GetProperties(typeof(B))["Value"].Attributes[typeof(DescriptionAttribute)];
    Assert.Equal("B", prop.Description);
}
class A {
    [Description("A")]
    public virtual int Value { get; set; }
}
class B : A {
    [Description("B")]
    public override int Value { get; set; }
}
```

[EDIT] Add C# syntax highlighing & change code formatting by @karelz

**Comment by AtsushiKan** [comment]
This is not Reflection code. `TypeDescriptor` is from `System.ComponentModel.TypeConverter.dll`.

**Comment by danmosemsft** [comment]
.NET Framework returns "B" correctly.

@k0st1x any interest in offering a PR?

**Comment by k0st1x** [comment]
this issue happened because of https://github.com/dotnet/corefx/pull/8695 :(

**Comment by karelz** [comment]
cc @chlowell who worked on the PR #8695

**Comment by karelz** [comment]
cc @maryamariyan @safern 
I am curious if it was intentional or unintentional change made in #8695

**Comment by safern** [comment]
It seems like an intentional change to me, but seems like it missed this particular scenario. 

cc: @stephentoub who was close to the fix process.

**Comment by safern** [comment]
The test that started failing with the old behavior is: https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.TypeConverter/tests/MemberDescriptorTests.cs#L14

So I think a deeper investigation on that test would be worth to see how to fix the issue the test was fixing without breaking this particular scenario. @k0st1x any interest in throwing a PR?

**Comment by safern** [comment]
Didn't see: https://github.com/dotnet/corefx/pull/26704 thanks. @k0st1x

**Comment by k0st1x** [comment]
@karelz (or smbd else) please review my PR https://github.com/dotnet/corefx/pull/26756

**Comment by k0st1x** [comment]
@stephentoub, where can I get the nightly build of  System.ComponentModel.TypeConverter assembly to test it on the CI?
the https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.ComponentModel.TypeConverter package is last built on 13 Jan 2017 only

**Comment by weshaggard** [comment]
No that does not ship as an individual package any longer. It only ships as part of Microsoft.NETCore.App package.

**Comment by karelz** [comment]
Thanks, that's what I thought.
@k0st1x you will have to wait for 2.1 to ship, or use daily 2.1 builds - see [details](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md).

**Comment by k0st1x** [comment]
that PR was merged into the master branch. but can you cherry-pick it onto the 2.1 branch?
or should i do a new PR for 2.1 branch?

**Comment by karelz** [comment]
Everything from master flows into 2.1 until we branch off for final release - that is still some time away.
