### ISSUE TITLE
System.Memory project should consume shared sources for Span

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/corefx#26611]
See https://github.com/dotnet/corefx/issues/25188 for context. We should make a similar change here with `Span` so that we don't have two different implementations between coreclr and corefx.

n.b. The mirroring is already taking place, but the System.Memory project doesn't reference the shared sources for `Span`.

**Comment by ahsonkhan** [comment]
cc @tarekgh 

We should also make sure our exception messages (via [ThrowHelpers](https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/ThrowHelper.cs)) are the same.

cc @eerhardt

**Comment by tarekgh** [comment]
The span code has already enough differences between coreclr and corefx. if we need to merge it into a common file, we'll either have to add a lot of #if  in the sources which not preferred to do (CC @jkotas @weshaggard ). 

I prefer to keep a separate implementation in the separate files (as we have today) and if there is pure common method implementation we can move it to a shared file. 

> We should also make sure our exception messages (via ThrowHelpers) are the same.

We don't have to worry much about the exception messages than the exception type itself and its parameters. Messages in the future can be localized or changed.

**Comment by jkotas** [comment]
> I prefer to keep a separate implementation in the separate files 

Sounds good to me.
