### ISSUE TITLE
Unsafe slower than unsafe

### ISSUE THREAD

**Issue by fanoI** [dotnet/corefx#26622]
I was playing with the Unsafe Nuget package (that if I'm not mistaking is part of CoreFx) and sincerely I expected to have performance characteristics in pair with unsafe but trying to convert a bool to byte shows that is slower a lot slower!

This is my test code:

```cs
        static void TestSpeed()
        {
            byte j = 0;
            bool b = false;
            Stopwatch sw1 = new Stopwatch();
            Stopwatch sw2 = new Stopwatch();

            for (int n = 0; n < 5; n++)
            {
                sw1.Start();
                for (int i = 100 * 1000 * 1000; i > 0; i--)
                    unsafe { j = *(byte*)(&b); }
                sw1.Stop();

                sw2.Start();
                for (int i = 100 * 1000 * 1000; i > 0; i--)
                    j = Unsafe.As<bool, byte>(ref b);
                sw2.Stop();
                Console.WriteLine("sw1: " + sw1.ElapsedMilliseconds +
                    "  sw2:" + sw2.ElapsedMilliseconds + ", +" + 100 * (sw2.ElapsedMilliseconds - sw1.ElapsedMilliseconds) / sw1.ElapsedMilliseconds + "% relative to sw1"
                    );
            }
        }
```

These are my results:

> sw1: 279  sw2:643, +130% relative to sw1
>sw1: 544  sw2:1165, +114% relative to sw1
>sw1: 751  sw2:1589, +111% relative to sw1
>sw1: 956  sw2:1997, +108% relative to sw1
>sw1: 1158  sw2:2412, +108% relative to sw1

**Comment by jkotas** [comment]
This does not repro for me with .NET Core on current master. Both loops gets optimized into;

```
dec     ecx
test    ecx,ecx
jg      ...
```

As you can see, the value is not even read in the loop. This microbechmark does not represent what will happen if you use Unsafe in real code.

Unsafe can be slower for several reasons:
- We had to a fix a few optimization bugs in the JIT to make it generate good code for Unsafe. Older runtimes do not have these bug fixes and so Unsafe will tend to be slower on them.
- Unsafe produces more complex code than equivalent unsafe C# code. It makes JIT to work harder to optimize it out and miss optimizations sometimes.

**Comment by fanoI** [comment]
I've tested this with the production version of Net Core 2.0, what values do you get with master?
What microbechmark  you would suggest to see better the differences between the unsafe and Unsafe?

**Comment by jkotas** [comment]
> I've tested this with the production version of Net Core 2.0.

I have tried on .NET Core 2.0 (x64 release) and I am not seeing the problem there either.

> What values do you get with master?

Around 0%. The micro benchmark is sensitive to code alignment, so it varies quite a bit. Here is an example of one run (I have changed it to do more iterations).

```
sw1: 647  sw2:588, +-9% relative to sw1
sw1: 677  sw2:617, +-8% relative to sw1
sw1: 706  sw2:647, +-8% relative to sw1
sw1: 735  sw2:675, +-8% relative to sw1
sw1: 764  sw2:703, +-7% relative to sw1
sw1: 794  sw2:731, +-7% relative to sw1
```

> What microbechmark you would suggest to see better the differences between the unsafe and Unsafe?

- Do not read the value from the same spot all the time. E.g. iterate through an array.
- Do something with the value being read. E.g. compute sum of an array.

**Comment by mikedn** [comment]
I also tried with .NET 4.7.1 and I don't see any differences either. Not even when running on x86 using JIT32.

Could you post the assembly generate for that method?

**Comment by fanoI** [comment]
This the ASM for unsafe:

``
    75:                     unsafe { j = *(byte*)(&b); }
00007FF950890A96  nop  
00007FF950890A97  movzx       ecx,byte ptr [rbp+0D8h]  
00007FF950890A9E  mov         dword ptr [rbp+0E4h],ecx  
00007FF950890AA4  nop  
``

this is for Unsafe:

``
     80:                     j = Unsafe.As<bool, byte>(ref b);
00007FF950890AFC  lea         rcx,[rbp+0D8h]  
00007FF950890B03  call        00007FF950890738  
00007FF950890B08  mov         qword ptr [rbp+98h],rax  
00007FF950890B0F  mov         rcx,qword ptr [rbp+98h]  
00007FF950890B16  movzx       ecx,byte ptr [rcx]  
00007FF950890B19  mov         dword ptr [rbp+0E4h],ecx  
``

**Comment by jkotas** [comment]
This non-optimized debug code. Try passing `-c Release` to the command line to get optimized code.

**Comment by fanoI** [comment]
I've selected release in Visual Studio and this the assembly generated for unsafe:

```
75:                     unsafe { j = *(byte*)(&b); }
00007FF956380A5E  nop // nothing to do bool and byte are the same thing in the end?
```
Unsafe does not do the call anymore but it not a NOP:

```
80:                     j = Unsafe.As<bool, byte>(ref b);
00007FF9563A0A8E  lea         rcx,[rbp-10h]  
00007FF9563A0A92  call        00007FF9563A0728  
00007FF9563A0A97  mov         qword ptr [rbp-48h],rax  
00007FF9563A0A9B  nop
```

It seems that there is overhead caused by Visual Studio, this results are obtained doing dotnet run on "Developer Command Prompt":

>sw1: 2275  sw2:3422, +50% relative to sw1
>sw1: 4547  sw2:6843, +50% relative to sw1
>sw1: 6813  sw2:10260, +50% relative to sw1
>sw1: 9190  sw2:13708, +49% relative to sw1
>sw1: 11432  sw2:17233, +50% relative to sw1

The number of iterations is now 1'000'000'000.

**Comment by PeterSmithRedmond** [comment]
FWIW, for the data from JKotas, running the data through a statistics package shows that the two sets of values have a significant overlap. SW2 is smaller (median 661 instead of 720.5), but the amount of overlap is such that the difference is not statistically significant.

> The two values are possibly the same.
> The p-value 0.0825 > target 0.05
> test	Welch's t-test
> p	0.0825
> df	9.9944
> t	1.9297

**Comment by fanoI** [comment]
Yes @jkotas has better result with Unsafe respect that unsafe... I think at this point there are indeed optimizations in master that are not present in the current release.
