### ISSUE TITLE
Reference assembly missing members for KeyValuePair and ReadOnlyMemory

### ISSUE THREAD

**Issue by gafter** [dotnet/corefx#26624]
@carlreinke commented on [Sat Jan 27 2018](https://github.com/dotnet/roslyn/issues/24493)

**Version Used**: Microsoft (R) Visual C# Compiler version 2.6.0.62329 (5429b35d)

**Steps to Reproduce**:

```
c:\temp>type Program.cs
class C
{
    static bool M( out System.ReadOnlyMemory<byte> x )
    {
        return false;  // No error here!?
    }
}

c:\temp>csc.exe /reference:"C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\mscorlib.dll" /reference:"C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\netstandard.dll" /reference:C:\Users\User\.nuget\packages\system.memory\4.5.0-preview1-26011-01\ref\netstandard2.0\System.Memory.dll /reference:"C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.Runtime.dll" /out:Test.dll /target:library Program.cs
Microsoft (R) Visual C# Compiler version 2.6.0.62329 (5429b35d)
Copyright (C) Microsoft Corporation. All rights reserved.


c:\temp>
```

**Expected Behavior**: Show error message and fail to compile.

**Actual Behavior**: Compilation succeeds.

---

@gafter commented on [Sat Jan 27 2018](https://github.com/dotnet/roslyn/issues/24493#issuecomment-361022229)

Please check to see what fields, if any, are contained in `System.Collections.Generic.KeyValuePair` inside of `C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.Runtime.dll`. If it contains no fields in that reference assembly, then the compiler is correct. In that case the `out` parameter is definitely assigned because all (zero) of its fields are definitely assigned.

---

@gafter commented on [Sat Jan 27 2018](https://github.com/dotnet/roslyn/issues/24493#issuecomment-361022331)

To clarify, if that is the case then it is a bug in the reference assembly.

---

@carlreinke commented on [Sat Jan 27 2018](https://github.com/dotnet/roslyn/issues/24493#issuecomment-361023866)

Indeed, there are no fields in `KeyValuePair<TKey, TValue>` in the reference assembly.  I replaced the original comment with a different example.  `ReadOnlyMemory<T>` does have fields.

---

@carlreinke commented on [Sat Jan 27 2018](https://github.com/dotnet/roslyn/issues/24493#issuecomment-361024011)

Err, I guess the *reference* assembly for `ReadOnlyMemory<T>` doesn't have fields either... the assembly that gets used when it actually runs has fields; otherwise it wouldn't work.

Why are there no fields in the reference assemblies?

(IntelliSense/MSBuild seem to also use the ref assembly, so when I'm building in Visual Studio, I don't get any error message about the out parameter not being assigned there either.)

---

@gafter commented on [Sat Jan 27 2018](https://github.com/dotnet/roslyn/issues/24493#issuecomment-361025653)

That is a bug. We’ll move this bug to an appropriate repository.

---

@tannergooding commented on [Sat Jan 27 2018](https://github.com/dotnet/roslyn/issues/24493#issuecomment-361025904)

@gafter, I believe the issue has already been dealt with on the CoreFX side: https://github.com/dotnet/corefx/pull/26286 and https://github.com/dotnet/buildtools/pull/1859.

However, it was only merged 15 days ago, so nothing has shipped with the fix yet.

---

@gafter commented on [Sun Jan 28 2018](https://github.com/dotnet/roslyn/issues/24493#issuecomment-361105192)

@tannergooding I don't see anything specifically changing `KeyValuePair`'s reference assembly. Isn't its reference assembly produced based on hand-written source?

**Comment by tannergooding** [comment]
This looks like it was already fixed in some commit: https://github.com/dotnet/corefx/blob/a3986843153e27e92c89907f58046bb37da0f9eb/src/System.Memory/ref/System.Memory.cs#L108

**Comment by tannergooding** [comment]
I don't see where the reference contract for KeyValuePair is, however. I'm probably just missing it somewhere.

**Comment by tannergooding** [comment]
Reference contract for KVP is in `System.Runtime` and also looks to be correct: https://github.com/dotnet/corefx/blob/master/src/System.Runtime/ref/System.Runtime.cs#L3907

(GitHub search wouldn't find it, `git grep` did).

**Comment by akoeplinger** [comment]
> (GitHub search wouldn't find it, git grep did).

FYI only files smaller than 384 KB are searchable on GitHub (https://help.github.com/articles/searching-code/#considerations-for-code-search)

**Comment by danmosemsft** [comment]
Seems resolved
