### ISSUE TITLE
Allow setting "restricted" headers using ClientWebSocket

### ISSUE THREAD

**Issue by khellang** [dotnet/corefx#26627]
`ClientWebSocket` uses `ClientWebSocketOptions`, which has a `SetRequestHeader(string headerName, string headerValue)` method that allows you to set custom headers for the initial web socket request.

The problem is that this calls into `WebHeaderCollection.Set(string name, string value)`:

https://github.com/dotnet/corefx/blob/f8c403f7b05daf4b7f07d4b45ac7ee7f2372abfb/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/ClientWebSocketOptions.cs#L34-L40

Which performs validation on "restricted" headers:

https://github.com/dotnet/corefx/blob/f8c403f7b05daf4b7f07d4b45ac7ee7f2372abfb/src/System.Net.WebHeaderCollection/src/System/Net/WebHeaderCollection.cs#L134-L154

This results in the following exception when trying to set the `User-Agent` header and other "restricted" headers:

> System.ArgumentException: The 'User-Agent' header must be modified using the appropriate property or method.

The problem is that there's no `appropriate property or method` in sight, and because `ClientWebSocketOptions` doesn't expose the internal `WebHeaderCollection`, there's no way to bypass the validation.

How can we set custom "restricted" headers for `ClientWebSocket` connections?

**Comment by khellang** [comment]
Related SO post (with a horrible workaround): https://stackoverflow.com/questions/22635663/setting-user-agent-http-header-in-clientwebsocket
Also, the usual "closed by design" Connect issue: https://connect.microsoft.com/VisualStudio/feedback/details/840553/system-net-websockets-clientwebsocket-does-not-allow-to-set-the-http-header-user-agent

**Comment by khellang** [comment]
Even with horrible hacks like getting `ClientWebSocketOptions.RequestHeaders.InnerCollection` using reflection and adding the headers directly, it still throws because the following code also does validation:

https://github.com/dotnet/corefx/blob/f8c403f7b05daf4b7f07d4b45ac7ee7f2372abfb/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.Managed.cs#L115-L123

I'm running on .NET Framework, so the code isn't exactly the same, but more or less:

> System.ArgumentException: The 'User-Agent' header must be modified using the appropriate property or method.
Parameter name: name
   at System.Net.WebHeaderCollection.ThrowOnRestrictedHeader(String headerName)
   at System.Net.WebHeaderCollection.Add(String name, String value)
   at System.Net.WebSockets.ClientWebSocket.CreateAndConfigureRequest(Uri uri)
   at System.Net.WebSockets.ClientWebSocket.<ConnectAsyncCore>d__21.MoveNext()

**Comment by karelz** [comment]
Looks like a legit bug. Do you want to put up a PR @khellang?

**Comment by khellang** [comment]
I'd love to, but TBH I have no clue how to approach this. Where is the correct place to fix it? I'm assuming this code was put in place for a (not so clear) reason.

**Comment by davidsh** [comment]
Yes, this is a bug in .NET Framework.

But, this problem doesn't repro on .NET Core.  While the code for ClientWebSocket/ClientWebSocketOptions was ported from .NET Framework to .NET Core, there is a difference in how it works on .NET Core.

The System.Net.WebHeaderCollection.ThrowOnRestrictedHeader() internal method is not going to throw on .NET Core.  That is because the WebHeaderCollectionType is set as "Unknown" when ClientWebSocketOptions creates the header collection (this behavior is actually a "bug" tracked by #18784).  But because of this, the ThrowOnRestrictedHeader() method will not throw on 'User-Agent' or other headers that HttpWebRequest required the corresponding property to be used (which as noted doesn't make sense for the ClientWebSocketOptions object).

If you have a repro of this problem where setting ClientWebSocketOptions.SetRequestHeader() is throwing on 'User-Agent' or other headers on .NET Core, please let us know.  For now, closing this issue since it doesn't repro on .NET Core.  Thx.

**Comment by khellang** [comment]
Thanks for looking into this @davidsh!

> this behavior is actually a "bug" tracked by #18784

So when #18784 is fixed, will we get the same behavior on Core?

**Comment by davidsh** [comment]
When #18784 is addressed, we will also make sure to keep ClientWebSocketOptions.SetRequestHeader() working for all request headers.

**Comment by khellang** [comment]
> When #18784 is addressed, we will also make sure to keep ClientWebSocketOptions.SetRequestHeader() working for all request headers.

Awesome. Thanks!

**Comment by petke** [comment]
Hi. 

Has this been fixed now?

As in when building (on windows 10) against say ".NET Framework 4.7.2" the following throws:
var websocket = new ClientWebSocket();
websocket.Options.SetRequestHeader("User-Agent", "test");

When building against ".NET Core 2.2" it doesn't throw.

1) Does that mean it works, or just that it fails silently (and doesn't set the header)? 

2) I'd like to test this somehow to verify. But I cant tell the difference (between working and failing silently) as I don't know how to log or view the outgoing ClientWebSocket request headers. Anyone know how to do this? (Fiddler doesn't show anything, and haven't found a online wss echo server that shows request headers for connecting clients)

Thanks /Petke

**Comment by davidsh** [comment]
>Has this been fixed now?

This issue has not been fixed yet.

**Comment by karelz** [comment]
@petke are you asking if it is fixed in .NET Core or in .NET Framework?

Based on previous comment https://github.com/dotnet/corefx/issues/26627#issuecomment-391472613 from @davidsh it seems .NET Core does not have the problem at all. Or did I misunderstand it @davidsh?

**Comment by petke** [comment]
@karelz @davidsh 

Thanks for the quick replies. I'm wondering if its fixed (or has always worked) in NET Core. Its all a bit confusing to me as. It looks like it works, as you can set restricted headers. But I'm not sure if they are also sent. 

Should I interpret david's reply as "you can set them, but they wont be sent".

Thanks /Petke

**Comment by karelz** [comment]
@petke I believe it works. If you have evidence that it does not, please file a new bug with a repro showcasing that. Thanks!

**Comment by wonea** [comment]
I'm using NET Core which is calling a NET Standard library where my code resides.

_ws = new ClientWebSocket();
_ws.Options.KeepAliveInterval = Timeout.InfiniteTimeSpan;
_ws.Options.SetRequestHeader("Content-Type", "application/json");

The Content-Type is never passed.

**Comment by kolsrud** [comment]
@davidsh Was there ever a ticket for this issue in .NET Framework filed at https://developercommunity.visualstudio.com/spaces/61/index.html? I did some search there but couldn't find anything.

**Comment by kolsrud** [comment]
I just filed this one: https://developercommunity.visualstudio.com/content/problem/570280/allow-setting-restricted-headers-using-clientwebso.html

**Comment by davidsh** [comment]
>@davidsh Was there ever a ticket for this issue in .NET Framework filed at https://developercommunity.visualstudio.com/spaces/61/index.html? I did some search there but couldn't find anything.

There was no ticket opened for this .NET Framework bug.

>I just filed this one: https://developercommunity.visualstudio.com/content/problem/570280/allow-setting-restricted-headers-using-clientwebso.html

Thanks for opening the ticket.

**Comment by kolsrud** [comment]
Hmm... The ticket was simply closed (automatically?) after 90 days. @davidsh Is there any point in filing a new one on the same topic?

**Comment by davidsh** [comment]
>Hmm... The ticket was simply closed (automatically?) after 90 days. @davidsh Is there any point in filing a new one on the same topic?

At this point, feature changes in .NET Framework are not possible.  See this:

* https://devblogs.microsoft.com/dotnet/net-core-is-the-future-of-net/
* https://devblogs.microsoft.com/dotnet/introducing-net-5/

Reading the thread above, it appears that this is not an issue in .NET Core. Your scenario works ok in .NET Core? If it doesn't, then you can open a new issue and we can address it in .NET Core 5.

**Comment by kolsrud** [comment]
That's pretty much what I expected. Thanks for the quick response!

**Comment by julijanr** [comment]
I have wrote a code that uses reflection to allow to set any request header without restriction.

https://stackoverflow.com/questions/239725/cannot-set-some-http-headers-when-using-system-net-webrequest/58585845#58585845
