### ISSUE TITLE
How to make ConfigurationManager to pick assembly config instead of exe.config?

### ISSUE THREAD

**Issue by abhishkk** [dotnet/corefx#26626]
By default, ConfigurationManager.AppSettings returns config file of the application which is getting executed.
What to do for ConfigurationManager.AppSettings to return config file of assembly which is loaded in that application.

For example if Console1.exe is loading assembly1.dll, then what to for ConfigurationManager.AppSettings to return assembly1.dll.config instead of console1.exe.config?

**Comment by JeremyKuhne** [comment]
You can't change `ConfigurationManager.AppSettings` target app config in .NET Core. On desktop (e.g. .NET Framework 4.x) you can configure the path for the config when creating a new `AppDomain`. There are no `AppDomain`s in .NET Core so this isn't an option.

You _can_, however, explicitly load a `Configuration` object from any path via [`ConfigurationManager.OpenMappedExeConfiguration()`](https://msdn.microsoft.com/en-us/library/system.configuration.configurationmanager.openmappedexeconfiguration.aspx) and access the AppSettings off of that.
