### ISSUE TITLE
Add a generic OrderedDictionary class

### ISSUE THREAD

**Issue by TylerBrinkley** [dotnet/corefx#26634]
Often times I've come across places when needing a `Dictionary` where the insertion order of the elements is important to me. Unfortunately, .NET does not currently have a generic `OrderedDictionary` class. We've had a non-generic `OrderedDictionary` class since .NET Framework 2.0 which oddly enough was when generics were added but no generic equivalent. This has forced many to roll their own solution, typically by using a combination of a `List` and `Dictionary` field resulting in the worst of both worlds in terms of performance and resulting in larger memory usage, and even worse sometimes users instead rely on implementation details of `Dictionary` for ordering which is quite dangerous.

## Proposed API
```diff
 namespace System.Collections.Generic {
+    public class OrderedDictionary<TKey, TValue> : ICollection<KeyValuePair<TKey, TValue>>, IDictionary<TKey, TValue>, IEnumerable, IEnumerable<KeyValuePair<TKey, TValue>>, IList<KeyValuePair<TKey, TValue>>, IReadOnlyCollection<KeyValuePair<TKey, TValue>>, IReadOnlyDictionary<TKey, TValue>, IReadOnlyList<KeyValuePair<TKey, TValue>> {
+        public struct Enumerator : IDisposable, IEnumerator, IEnumerator<KeyValuePair<TKey, TValue>> {
+            public KeyValuePair<TKey, TValue> Current { get; }
+            public void Dispose();
+            public bool MoveNext();
+        }
+        public sealed class KeyCollection : ICollection<TKey>, IEnumerable, IEnumerable<TKey>, IList<TKey>, IReadOnlyCollection<TKey>, IReadOnlyList<TKey> {
+            public struct Enumerator : IDisposable, IEnumerator, IEnumerator<TKey> {
+                public TKey Current { get; }
+                public void Dispose();
+                public bool MoveNext();
+            }
+            public KeyCollection(OrderedDictionary<TKey, TValue> orderedDictionary);
+            public int Count { get; }
+            public void CopyTo(TKey[] array, int arrayIndex);
+            public OrderedDictionary<TKey, TValue>.KeyCollection.Enumerator GetEnumerator();
+        }
+        public sealed class ValueCollection : ICollection<TValue>, IEnumerable, IEnumerable<TValue>, IList<TValue>, IReadOnlyCollection<TValue>, IReadOnlyList<TValue> {
+            public struct Enumerator : IDisposable, IEnumerator, IEnumerator<TValue> {
+                public TValue Current { get; }
+                public void Dispose();
+                public bool MoveNext();
+            }
+            public ValueCollection(OrderedDictionary<TKey, TValue> orderedDictionary);
+            public int Count { get; }
+            public void CopyTo(TValue[] array, int arrayIndex);
+            public OrderedDictionary<TKey, TValue>.ValueCollection.Enumerator GetEnumerator();
+        }
+        public OrderedDictionary();
+        public OrderedDictionary(int capacity);
+        public OrderedDictionary(IEqualityComparer<TKey> comparer);
+        public OrderedDictionary(int capacity, IEqualityComparer<TKey> comparer);
+        public OrderedDictionary(IDictionary<TKey, TValue> dictionary);
+        public OrderedDictionary(IDictionary<TKey, TValue> dictionary, IEqualityComparer<TKey> comparer);
+        public OrderedDictionary(IEnumerable<KeyValuePair<TKey, TValue>> collection);
+        public OrderedDictionary(IEnumerable<KeyValuePair<TKey, TValue>> collection, IEqualityComparer<TKey> comparer);
+        public IEqualityComparer<TKey> Comparer { get; }
+        public int Count { get; }
+        public TValue this[int index] { get; set; }
+        public TValue this[TKey key] { get; set; }
+        public OrderedDictionary<TKey, TValue>.KeyCollection Keys { get; }
+        public OrderedDictionary<TKey, TValue>.ValueCollection Values { get; }
+        public void Add(TKey key, TValue value);
+        public void Clear();
+        public bool ContainsKey(TKey key);
+        public bool ContainsValue(TValue value);
+        public TValue GetAt(int index);
+        public TValue GetAt(int index, out TKey key);
+        public OrderedDictionary<TKey, TValue>.Enumerator GetEnumerator();
+        public TValue GetValue(TKey key);
+        public int IndexOf(TKey key);
+        public void Insert(int index, TKey key, TValue value);
+        public bool Remove(TKey key);
+        public bool Remove(TKey key, out TValue value);
+        public void RemoveAt(int index);
+        public void SetAt(int index, TValue value);
+        public void SetAt(int index, TKey key, TValue value);
+        public void SetValue(TKey key, TValue value);
+        public void TrimExcess();
+        public bool TryGetValue(TKey key, out TValue value);
+    }
 }
```

Perhaps one of the reasons there was no generic `OrderedDictionary` added initially was due to issues with having both a key and index indexer when the key is an `int`. A call to the indexer would be ambiguous. Roslyn prefers the non-generic parameter so in this case the index indexer will be called. If the user needs to access elements by key they can use the explicit `GetValue` and `SetValue` methods.

## API Details
* `Insert` allows `index` to be equal to `Count` to insert the element at the end.
* `SetAt(int index, TValue value)` requires `index` to be less than `Count` but `SetAt(int index, TKey key, TValue value)` allows `index` to be equal to `Count` similar to `Insert`.
* `SetValue` will insert if needed, similar to the `Dictionary` indexer.
* Performance will be the same as `Dictionary` for all operations except `Remove` which will necessarily be `O(n)`. `Insert` and `RemoveAt` which aren't members of `Dictionary` will also be `O(n)`.

## Open Questions
* Should the namespace be `System.Collections.Generic` when it could easily be `System.Collections.Specialized` where the non-generic version is located? I just felt this collection is far more useful to be relegated to that namespace.
* Should the non-generic interfaces `ICollection`, `IList`, and `IOrderedDictionary` be implemented?

## Updates
* Added constructor overloads for `IEnumerable<KeyValuePair<TKey, TValue>>`.
* Added `ContainsValue` method due to being needed for the `ValueCollection.Contains` method.
* Proposal no longer advocates for throwing an exception when using an indexer while the key is an int.

**Comment by sharwell** [comment]
:memo: Technically [`SortedList<TKey, TValue>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.sortedlist-2) is an ordered dictionary.

**Comment by TylerBrinkley** [comment]
@sharwell `SortedList` and `SortedDictionary` are not hash tables but trees resulting in `O(log(n))` lookups instead of `O(1)` for `Dictionary`.

**Comment by sharwell** [comment]
Is the request here for a sorted dictionary, or for an insertion-order-preserving dictionary similar to [`LinkedHashMap<K, V>`](https://docs.oracle.com/javase/8/docs/api/java/util/LinkedHashMap.html)?

**Comment by TylerBrinkley** [comment]
Insertion-order-preserving dictionary

**Comment by sharwell** [comment]
Ah, [`OrderedDictionary.Insert`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.ordereddictionary.insert) explains a lot about the expectations here.

**Comment by TylerBrinkley** [comment]
Related to #26638

**Comment by danmosemsft** [comment]
Would the implementation optimize for retrieval (presumably array + hashtable) or for space (presumably a tree/heap) ? Are there scenarios for both? What complexity do you hope for for lookup, Add, Remove, and ContainsKey (and ContainsValue if we have that)

It might be helpful to systematically compare

Operation | Dictionary<K,V> | SortedDictionary<K,V> | SortedList<K,V> | OrderedDictionary<K,V>
-- | -- | -- | -- | --
this[key] | O(1) | O(log n) | O(log n) or O(n) | ? 
Add(key,value) | O(1)  | O(log n) | O(n) | ? 
Remove(key) | O(1) | O(log n) | O(n) | ? 
ContainsKey(key) | O(1) | O(log n) | O(log n) | ? 
ContainsValue(value) | O(n) | O(n) | O(n) | ? 
Space efficiency | good | worst | medium | ? 
Insert/Remove sorted data | n/a | O(log n) | O(n) | ?
From sorted data | n/a | ? | better? | ?

I didn't check this table, just suggesting what would be useful to fill out.

**Comment by TylerBrinkley** [comment]
Thanks for putting that chart together. The implementation will be nearly identical to [`Dictionary<K,V>`](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Collections/Generic/Dictionary.cs) with a bucket and entries array except the entries array will be contiguous and thus ordered.

Below is the chart filled out

Operation | Dictionary<K,V> | SortedDictionary<K,V> | SortedList<K,V> | OrderedDictionary<K,V>
-- | -- | -- | -- | --
this[key] | O(1) | O(log n) | O(log n) or O(n) | O(1)
this[index] | n/a | n/a | n/a | O(1)
Add(key,value) | O(1) | O(log n) | O(n) | O(1)
Remove(key) | O(1) | O(log n) | O(n) | O(n)
ContainsKey(key) | O(1) | O(log n) | O(log n) | O(1)
ContainsValue(value) | O(n) | O(n) | O(n) | O(n) if added
IndexOf(key) | n/a | n/a | n/a | O(1)
Insert(index,key,value) | n/a | n/a | n/a | O(n)
Space efficiency | good | worst | medium | good
Insert/Remove sorted data | n/a | O(log n) | O(n) | n/a
From sorted data | n/a | ? | better? | n/a

**Comment by sharwell** [comment]
💭 I almost prefer the indexer for this type be based on the "bias" implied by the type name. To me, `OrderedDictionary<TKey, TValue>` would bias towards dictionary, which means `this[key]` would be the only indexer. Indexed access could be achieved by calling `GetAt(index)` or by casting to `IList<TValue>` (or `IList<KeyValuePair<TKey, TValue>>`?) and using the indexer there.

**Comment by TylerBrinkley** [comment]
If we only have one I'd agree that the `this[key]` indexer would be the one to stay. Like you said, indexed access could still be achieved with the `GetAt(index)` method and then the `GetValue` and `SetValue` methods could be removed. I'm torn on this because a `this[index]` indexer would be very intuitive to users.

**Comment by TylerBrinkley** [comment]
FYI, if this gets approved I'd happily implement it.

**Comment by JustArchi** [comment]
I'd also be interested in seeing generic variant of `OrderedDictionary`, I was seriously confused when I found out that there is no such thing as of now.

Thank you in advance for considering this.

**Comment by prajaybasu** [comment]
Hello, I too would like to see a generic version of this, and maybe have it moved to the `System.Collections.Generic` namespace.  
A quick [Google Search](https://www.google.co.in/search?q=OrderedDictionary%3CTKey%2C+TValue%3E) shows that it is still being used and that there are multiple "workarounds" implemented by different library authors:

* [Wintellect.PowerCollections](https://submain.com/ghostdoc/samples/themes/flatmain/html/1889519617.htm)
* [IBM.WebSphere.Caching](https://www.ibm.com/support/knowledgecenter/SSTVLU_8.6.0/com.ibm.websphere.extremescale.netapi.doc/html/45460959-9e93-d694-6f6e-4485ebba5511.htm)
* [Accord.Collections](http://accord-framework.net/docs/html/T_Accord_Collections_OrderedDictionary_2.htm)
* [Cadenza.Collections](http://www.jprl.com/Projects/Cadenza/docs/Cadenza.Collections/OrderedDictionary%602.html)

and so on..

**Comment by shaggygi** [comment]
I still think it would be beneficial to have [Immutable Parent/Child Collection](https://github.com/dotnet/corefx/issues/18357), but understand it is not specifically related to this thread.

**Comment by wanton7** [comment]
Just had need for this today. Any news if/when this will be implemented?

**Comment by TylerBrinkley** [comment]
Moved to [corefxlab#2456](https://github.com/dotnet/corefxlab/issues/2456) as part of the specialized collections initiative.
