### ISSUE TITLE
System.Drawing.Common SetHdevmode_IntPtr_Success does not work for me locally

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#26637]
```
     System.Drawing.Printing.Tests.PrinterSettingsTests.SetHdevmode_IntPtr_Success [FAIL]
        Assert.Equal() Failure
        Expected: 3
        Actual:   6
        Stack Trace:
           d:\repos\corefx\src\System.Drawing.Common\tests\Printing\PrinterSettingsTests.cs(559,0): at System.Drawing.Printing.Tests.PrinterSettingsTests.SetHdevmode_IntPtr_Success()
```
From a quick look, this appears like it could be a product bug rather than a test bug, on both netfx and netcoreapp.  The Copies value is not being transferred as it's expected to be.  Either it's a product bug to be fixed, or the test's expectation that Copies gets copied is incorrect.

**Comment by safern** [comment]
Marking a 2.1 so that it is investigated on whether it is a test bug or a product bug.

**Comment by stephentoub** [comment]
(Just to be clear, this also repros for me on netfx.)

**Comment by AtsushiKan** [comment]
Reproability depends on configured default printer and whether the device supports requesting multiple copies.

e.g. test passes if "Microsoft Print to PDF" is the default printer but fails if "Fax" is the default printer.

Delving deeper to understand the intent of the api - whether this is something that needs testing and if so, how to make the test more adaptive.

**Comment by MisinformedDNA** [comment]
The test is still failing for me.

**Comment by danmosemsft** [comment]
@MisinformedDNA have you confirmed that the code you built includes the fix linked from this? ie https://github.com/dotnet/corefx/commit/2d7b6dc7c773f2a143aacebc08c98dd8397286af

eg if you do `git rev-list HEAD | find /i "2d7b6dc7c773f2a143aacebc08c98dd8397286af"` does it print out `2d7b6dc7c773f2a143aacebc08c98dd8397286af`

If it does not, please pull and try again.

If it does, can you find more output similar to the above, near a line like `System.Drawing.Printing.Tests.PrinterSettingsTests.SetHdevmode_IntPtr_Success [FAIL]` ? Like a callsatck.

**Comment by danmosemsft** [comment]
Post ZBB as just reopened

**Comment by MisinformedDNA** [comment]
Yep, it's in there.

> corefx>git rev-list HEAD | find /i "2d7b6dc7c773f2a143aacebc08c98dd8397286af"
> 2d7b6dc7c773f2a143aacebc08c98dd8397286af

Here's the failure:

>      System.Drawing.Tests.BitmapTests.MakeTransparent_GrayscalePixelFormat_ThrowsArgumentException [FAIL]
>         Assert.Throws() Failure
>         Expected: typeof(System.Runtime.InteropServices.ExternalException)
>         Actual:   (No exception was thrown)
>         Stack Trace:
>            C:\Users\diosloco\Documents\Repos\corefx\src\System.Drawing.Common\tests\BitmapTests.cs(964,0): at System.Drawing.Tests.BitmapTests.MakeTransparent_GrayscalePixelFormat_ThrowsArgumentException()
>      System.Drawing.Imaging.Tests.MetafileTests.Ctor_RectangleFEmpty_Success(description: null) [FAIL]
>         System.Runtime.InteropServices.ExternalException : A generic error occurred in GDI+.
>         Stack Trace:
>            C:\Users\diosloco\Documents\Repos\corefx\src\System.Drawing.Common\src\System\Drawing\Imaging\Metafile.Windows.cs(325,0): at System.Drawing.Imaging.Metafile..ctor(String fileName, IntPtr referenceHdc, RectangleF frameRect, MetafileFrameUnit frameUnit, EmfType type, String description)
>            C:\Users\diosloco\Documents\Repos\corefx\src\System.Drawing.Common\tests\Imaging\MetafileTests.cs(571,0): at System.Drawing.Imaging.Tests.MetafileTests.Ctor_RectangleFEmpty_Success(String description)

**Comment by AtsushiKan** [comment]
This is a different pair of tests. Please open separate issues for those.

**Comment by MisinformedDNA** [comment]
Filed https://github.com/dotnet/corefx/issues/28721
