### ISSUE TITLE
Span<T> : promote NonPortableCast (or Cast, whatever the new name) from an extension method to an instance method

### ISSUE THREAD

**Issue by mgravell** [dotnet/corefx#26644]
Problem: methods are currently extension methods:

        public static ReadOnlySpan<TTo> NonPortableCast<TFrom, TTo>(this ReadOnlySpan<TFrom> source)
            where TFrom : struct
            where TTo : struct;
        public static Span<TTo> NonPortableCast<TFrom, TTo>(this Span<TFrom> source)
            where TFrom : struct
            where TTo : struct;

Due to limitations of generic type inference, this means that we constantly have to tell it the `TFrom`, which is ugly and annoying; for example, where `source` and `dest` are both `Span<uint>`:

    var vSource = source.NonPortableCast<uint, Vector<uint>>();
    var vDest = destination.NonPortableCast<uint, Vector<uint>>();

If they were instance methods instead:

        public ReadOnlySpan<TTo> NonPortableCast<TTo>()
            where TTo : struct;
        public Span<TTo> NonPortableCast<TTo>()
            where TTo : struct;

then this wouldn't be necessary:

    var vSource = source.NonPortableCast<Vector<uint>>();
    var vDest = destination.NonPortableCast<Vector<uint>>();

A small redundancy, maybe; but it feels so much cleaner.

**Comment by ahsonkhan** [comment]
cc @ianhays

**Comment by KrzysztofCwalina** [comment]
I like the proposal, i.e. TryCast instance method.

**Comment by jkotas** [comment]
Isn't this a dup of https://github.com/dotnet/corefx/issues/26465 ?

**Comment by ahsonkhan** [comment]
> Isn't this a dup of https://github.com/dotnet/corefx/issues/26465 ?

This issue is talking about making the extension method into an instance method. Issue #26465 proposes another extension method.

**Comment by jkotas** [comment]
Both issues are about same method. I do not think we want two of them. Right?

**Comment by ahsonkhan** [comment]
Yes, agreed. We should incorporate the changes proposed here into the other one. Closing.

@ianhays, can you update the proposal please?
