### ISSUE TITLE
DataAnnotaions in .net core misbehaving

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#26654]
@mquelcutti commented on [Fri Jan 26 2018](https://github.com/dotnet/standard/issues/632)

Hi the range for dataannotaions does not seem to work or the (0) for the display attib correctly if you put in range of 1 250 it always errors after you enter any chars. Additionally if you try to use the {0} {1} {2} the param (0) never shows the display attrib. The {0] is puling in min length and {1) max length and you cant get the display name  eg 

      [Required(ErrorMessage ="{0} is required")]

        [Display(Name = "Message")]

        [Range(1,250, ErrorMessage = "{0) should be between {1} and {2}")]

        public string Message { get; set; }

as you type in the text area and tab off it errors with 

1 should be between 250 and {2}:

but i would expect is 'Message should be between 1 and 250'

but only error if nothing is in the text area and or max has exceed not if the range of text is correct

Edit (0)

I am using .net core 2

**Comment by ajcvickers** [comment]
@mquelcutti With regards to the error message, the format string above is not correct--see `{0)` instead of `{0}`. When I correct this everything seems to work for me. That is:
* "1" validates
* "250" validates
* "0" gets correct message
* "667" gets correct message
* Any non-numeric string gets correct message.

If you are still seeing this issue after correcting the format string, then can you please post a runnable project/solution or code listing that demonstrates the issue so we can attempt to find the root cause.

**Comment by mquelcutti** [comment]
Hi where do I post the project to show the issue. I have recreated the first issue where by if you enter 4 chars in the comments and tab off  it errors even though its within the range. the properties seem to be working in the test project the only difference to my other project is I am using localised text from the DB using SQLlocaliser. I am going to try and reproduce this other error in another test project

**Comment by ajcvickers** [comment]
@mquelcutti When you say "enter 4 chars" is your expectation that the attribute is validating the _length of the string_? If so, that's not what it does. If you put this attribute on a string property it will treat the string as a number and validate if the number is in the range. So the string "1" is valid, the string "667" is not valid, and any non-numeric string--e.g. both "Hi" and "Hello" will not be valid.

**Comment by mquelcutti** [comment]
Ok sorry I miss understood what the range was for i thought it was for a min string of 1 and max o 250.
should be using MinLength Maxlength :) 
But still doesn't explain the {0} parameter issue
