### ISSUE TITLE
SslStreamInternal memory utilization

### ISSUE THREAD

**Issue by ayende** [dotnet/corefx#26657]
I'm tracking some memory issues in my application and I run into the following line in when running `!fq` in the dump:

```
00007ffbd1b73610     3233       284504 System.Net.Security.SslStreamInternal
```

I'm using `SslStream` heavily, but over 3000 sitting in the finalization queue was surprising.

Looking at the code here: https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/src/System/Net/Security/SslStreamInternal.cs

This class has a finalizer, but it never calls to `GC.SuppressFinalizer` when it is explicitly returning its buffer.
Given that it is held directly by a disposable resource (the `SslStream`, shouldn't this have a `Dispose` method that calls `GC.SuppressFinalizer`?

**Comment by karelz** [comment]
cc @Priya91

**Comment by Priya91** [comment]
Yeah makes sense, SslStreamInternal is tied to SslStream and isn't available after Sslstream is disposed.
