### ISSUE TITLE
Socket should default to InterNetworkV6 only if OSSupportsIPv6

### ISSUE THREAD

**Issue by darobs** [dotnet/corefx#26664]
https://github.com/dotnet/corefx/blob/ff478ef06a053f145a784a9640a6f85d8fe560a9/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L81

I am working through a customer issue for the IoT Edge, running it on an embedded ARM device without IPv6.  

https://github.com/Azure/iot-edge/issues/481 

The IoT Edge project uses libraries which wind up calling the `Socket(SocketType socketType, ProtocolType protocolType)` constructor linked at the top.  This Socket constructor will by default choose `AddressFamily.InterNetworkV6` and set `DualMode = true;` even if the OS does not support IPv6. Creation of a Socket with a IPv6 address family on my test system throws an Error -97 EAFNOSUPPORT.

Should the Socket constructor check to see if IPv6 is supported before setting the defaults?

**Comment by karelz** [comment]
That sounds like an reasonable improvement to the API behavior. Does it block the customer, or are there workarounds for them?

Should be fairly straightforward to do - anyone wants to grab it?

**Comment by darobs** [comment]
Yes, I can override the default Socket creation in the libraries I'm using, so I do have a workaround I can provide for them.

**Comment by wfurt** [comment]
Do you know @darobs if this can be reproduced with just IPv6 disabled (or not configured) or do you need kernel without IPv6 support?

**Comment by darobs** [comment]
I was only able to reproduce this on a kernel without IPv6 support. I didn't see the issue when IPv6 was just disabled.  This is how I reproduced the problem on my Raspberry Pi:

```
pi@raspberrypi:~ $ cat /etc/modprobe.d/local.conf
options ipv6 disable=1
```

**Comment by wfurt** [comment]
ok. I have raspberry image running under emulator. If you have any repro app, please share it, it would save me time.

**Comment by darobs** [comment]
It was found by attempting to run a Kestral server with the `UseKestral()` like this:

```
            IWebHostBuilder webHostBuilder = new WebHostBuilder()
                .UseKestrel(options =>
                {
                    options.Listen(IPAddress.IPv6Any, SslPortNumber, listenOptions =>
                    {
                        listenOptions.UseHttps(sslCert);
                    });
                })
                .UseStartup<Startup>();
            this.webHost = webHostBuilder.Build();
```

but I can come up with a cleaner, simpler example and post it.

**Comment by karelz** [comment]
@darobs if you can try a repro with just Sockets (no Kestrel), that would be much appreciated. Thank you!

**Comment by darobs** [comment]
I think this is a pretty straightforward reproduction:
```
using System;
using System.Net.Sockets;

namespace ConsoleApp4
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine($"IPV4/IPV6Supported: {Socket.OSSupportsIPv4}/{Socket.OSSupportsIPv6}");
            using (var s = new Socket(SocketType.Stream, ProtocolType.Tcp))
            {
                Console.WriteLine("Created a socket with default IPV6 address family and dual mode.");
            }
        }
    }
}
```
Output from system with IPv6 disabled:
```
$ modprobe -c | fgrep "ipv6 disable"
options ipv6 disable=1
$ sudo docker run sockettest
IPV4/IPV6Supported: True/False

Unhandled Exception: System.Net.Sockets.SocketException: Address family not supported by protocol
   at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
   at ConsoleApp4.Program.Main(String[] args) in C:\Users\darobs\Source\Repos\ConsoleApp4\ConsoleApp4\Program.cs:line 11
```
Output from system w/IPv6 enabled:
```
$ modprobe -c | fgrep "ipv6 disable"
$ sudo docker run sockettest
IPV4/IPV6Supported: True/True
Created a socket with default IPV6 address family and dual mode.
```
