### ISSUE TITLE
Process class doesn't expose some memory usage properties on Linux/MacOs

### ISSUE THREAD

**Issue by sebastienros** [dotnet/corefx#26669]
Tried on Ubuntu in a docker image and MacOs without docker, and I get this when running a simple web app:

```
WorkingSet64: 70 
PeakWorkingSet64:  
VirtualMemorySize64: 23,789 
PeakVirtualMemorySize64:  
PagedSystemMemorySize64:  
PeakPagedMemorySize64: 
```

The values on Windows however are

```
WorkingSet64: 121 
PeakWorkingSet64: 121 
VirtualMemorySize64: 2,112,855 
PeakVirtualMemorySize64: 2,112,856 
PagedSystemMemorySize64:  
PeakPagedMemorySize64: 179 
```

Some __Peak__ values are not provided, and the list differs between windows and linux/mac.

The code to repro is here: https://github.com/sebastienros/memoryusage

PS: If I start a new `Process` dynamically, the value of `WorkingSet64` of the returned instance doesn't change overtime even if the application is used intensively with memory allocations. The value remains very low (something like 3 MB) though the system reports more than 400 MB of used memory for the app. I'll file an issue based on your feedback, with a repro if necessary.

**Comment by sebastienros** [comment]
I managed to update the `WorkingSet64` value on Linux by creating a snapshot instance of `Process` like this:

```csharp
var process = Process.Start(...);
while(true)
{
  using (var localProcess = Process.GetProcessById(process.Id))
  {
    Console.WriteLine(localProcess.WorkingSet64);
  }
}
```

**Comment by karelz** [comment]
I am curious if the Peak* statistics are even available on Linux/Mac.

**Comment by wfurt** [comment]
I don't think there is:
man proc
see section /proc/[pid]/
That provides curent usage but not historical max.

**Comment by stephentoub** [comment]
> I managed to update the WorkingSet64

Calling Refresh on the instance updates it, no?

**Comment by sebastienros** [comment]
I was not aware of this method, so I'll assume it's the solution. Thank you.
