### ISSUE TITLE
System.Diagnostics.Tests.ProcessTests.TestStartWithNormalUser failed with "System.ComponentModel.Win32Exception : User with name 'dotnet-bot' was not found" in CI.

### ISSUE THREAD

**Issue by Sunny-pu** [dotnet/corefx#26673]
Failed tests: System.Diagnostics.Tests.ProcessTests.TestStartWithNormalUser

Details:
https://ci.dot.net/job/dotnet_corefx/job/master/job/centos7.1_debug/5151/testReport/System.Diagnostics.Tests/ProcessTests/TestStartWithNormalUser/

Failed configuration: Centos7.1_debug

MESSAGE:
System.ComponentModel.Win32Exception : User with name 'dotnet-bot' was not found.

~~~
STACK TRACE:
at System.Diagnostics.Process.GetUserAndGroupIds(ProcessStartInfo startInfo) in /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 621 at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) in /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 301 at System.Diagnostics.Process.Start() in /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug/src/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 1208 at System.Diagnostics.Tests.ProcessTests.TestStartWithUserName() in /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs:line 357 at System.Diagnostics.Tests.ProcessTests.TestStartWithNormalUser() in /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs:line 322
~~~

**Comment by ViktorHofer** [comment]
cc @eerhardt

**Comment by eerhardt** [comment]
@MattGal @mmitche - Is `dotnet-bot` not the name of the user on the machine?

**Comment by MattGal** [comment]
If it runs in helix, it's helixbot.  Is that hard coded somewhere?  Seems like the kind of thing we'd always pick up using the environment.

**Comment by MattGal** [comment]
* it's not running in Helix;  yes I'd expect it'd be dotnet-bot.

**Comment by eerhardt** [comment]
How do I tell if this test was running in Helix?

The user name isn't hard-coded in the test, it takes it from `Environment.UserName`.  See https://github.com/dotnet/corefx/blob/4464cceace7615502a1003bc7488f206a47c82ee/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs#L348

**Comment by eerhardt** [comment]
Same analysis as https://github.com/dotnet/corefx/issues/26675

I got a repro machine, and this appears to be a general issue with CentOS7.1.  See https://bugs.centos.org/view.php?id=7324.

The issue is we are passing in a buffer size that is too small in DEBUG mode (purposefully in order to test the fallback code).  CentOS7.1 (and it appears RedHat from that bug report above) had an OS kernel bug with `getpwnam_r` where it returns the wrong error code when passed a buffer size that is too small.  Thus, the OS is telling us that the user doesn't exist, when in fact the OS should be telling us the buffer is too small.

The fix would be to take out that `#if DEBUG` code, and always start with a buffer of `1024`.

https://github.com/dotnet/corefx/blob/4464cceace7615502a1003bc7488f206a47c82ee/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs#L629

@danmosemsft - your idea caught a bug.  It just happens to be a bug in the OS, that we can't fix.  😉

**Comment by ahsonkhan** [comment]
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_ubuntu16.10_release_prtest/9

System.Diagnostics.Tests.ProcessTests.TestStartWithRootUserCannotElevate [FAIL]

```text
19:54:44      System.Buffers.Text.Tests.FormatterTests.TestFormatterSingle(testData: [FormatSingle -1000,E3 to '-1.000E+003')]) [FINISHED] Time: 0.0000077s
19:54:44   Unhandled Exception: Xunit.Sdk.NotEqualException: Assert.NotEqual() Failure
19:54:44   Expected: Not "root"
19:54:44      System.Buffers.Text.Tests.FormatterTests.TestFormatterSingle(testData: [FormatSingle -1000,E10 to '-1.0000000000E+003')]) [STARTING]
19:54:44   Actual:   "root"
19:54:44      at Xunit.Assert.NotEqual[T](T expected, T actual, IEqualityComparer`1 comparer)
19:54:44      at System.Diagnostics.Tests.ProcessTests.TestStartWithUserNameCannotElevate() in /mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu16.10_release_prtest/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs:line 398
19:54:44   --- End of stack trace from previous location where exception was thrown ---
19:54:44      System.Buffers.Text.Tests.FormatterTests.TestFormatterSingle(testData: [FormatSingle -1000,E10 to '-1.0000000000E+003')]) [FINISHED] Time: 0.0000144s
19:54:44      at RemoteExecutorConsoleApp.Program.Main(String[] args) in /mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu16.10_release_prtest/src/Common/tests/System/Diagnostics/RemoteExecutorConsoleApp/RemoteExecutorConsoleApp.cs:line 92
```

**Comment by Sunny-pu** [comment]
failed again in CI:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_osx_release/361/testReport/

**Comment by danmosemsft** [comment]
@eerhardt

**Comment by eerhardt** [comment]
The https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_osx_release/361/testReport/ failure is tracked by #27402.  It appears to be OSX specific.  It has a different error message than this issue:

```
MESSAGE:
Assert.NotNull() Failure
+++++++++++++++++++
STACK TRACE:
at System.Diagnostics.Tests.ProcessTests.GetCurrentRealUserName() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_release/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs:line 394 at System.Diagnostics.Tests.ProcessTests.TestStartWithNormalUser() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_release/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs:line 343
```
