### ISSUE TITLE
X509Certificate2.PublicKey.Key is RSACng, not RSACryptoServiceProvider

### ISSUE THREAD

**Issue by vaindil** [dotnet/corefx#26682]
## [Sample solution](https://github.com/dotnet/corefx/files/1678312/EmptyCSharp.zip)

I'm on .NET Core 2.0, SDK is 2.1.4, Windows 10. I'm working to port a .NET framework library to `netcoreapp2.0` and I'm having an issue with `X509Certificate2`. [The docs say](
https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2.publickey?view=netcore-2.0) that `X509Certificate2.PublicKey.Key` will return either `RSACryptoServiceProvider` or `DSACryptoServiceProvider`, but the code below/attached solution actually return `RSACng`. The two types are not interchangeable from what I've gathered, so this is an issue.

The `certPath` variable is hardcoded into the test for this library, that's why it's in here. If it's a problem with the cert itself then I'll have to find a workaround, but the docs don't lead me to think that's the issue. (Also I know `WebClient` is outdated, that's just what the lib uses at the moment, I haven't gotten to fixing it yet.)

```csharp
const string certPath = "https://sns.us-east-1.amazonaws.com/SimpleNotificationService-433026a4050d206028891664da859041.pem";
WebClient wc = new WebClient();
byte[] raw = wc.DownloadData(certPath);

var cert = new X509Certificate2(raw);
Console.WriteLine(cert.PublicKey.Key.GetType().Name);

// Output is: RSACng
```

**Comment by bartonjs** [comment]
No one should ever call cert.PublicKey.Key; you should instead use cert.GetRSAPublicKey().

That said, we might have to do something about this.  Though for the private key it's not possible.

**Comment by vaindil** [comment]
> No one should ever call cert.PublicKey.Key; you should instead use cert.GetRSAPublicKey().

Good to know. I'm porting this old library and it's my first real foray into System.Security. Calling `GetRSAPublicKey()` also returns `RSACng`. I did more research and I think I opened this issue too quickly. Is it correct that `RSACng` is the specific implementation of `RSA` on Windows, and I should be abstracting from `RSA` instead for cross-platform support?

**Comment by bartonjs** [comment]
@vaindil Yep.  All of the useful methods have been moved down to the base class(es) (`RSA` (or `DSA`, or `ECDsa`)) and the interop types should only be used when you need to do something with the platform.

https://github.com/dotnet/corefx/blob/master/Documentation/architecture/cross-platform-cryptography.md

**Comment by vaindil** [comment]
@bartonjs Perfect. I'm all set then, sorry about that. I'll close this out, thank you!

**Comment by leniel** [comment]
@bartonjs you just helped here: https://stackoverflow.com/q/56979368/114029

Thanks!
