### ISSUE TITLE
Purpose of the HttpWebRequest.Connection property?

### ISSUE THREAD

**Issue by baulig** [dotnet/corefx#26696]
I am currently porting some of the corefx tests to Mono and fixing compatibility issues in our implementation.

While doing so, I stumbled upon [HttpWebRequest.Connection](https://github.com/dotnet/corefx/blob/release/2.0.0/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs#L520).  When I saw the implementation, I started to wonder what the exact purpose of this property's setter is.

You cannot set it to either `close` or `keep-alive` (which are the only two valid values for this header) and setting it to null or whitespace removes the "Connection" header (is there any scenario where this could bet set other than with a previous call to this property?).

I would assume the implementation doesn't allow setting `close` or `keep-alive` because there is already the `KeepAlive` property for that.  However, I couldn't think of any other values that somebody might want to set this header so, so I am wondering whether it's actually used somewhere.

**Comment by karelz** [comment]
@davidsh might know the historical answer ... I wonder if it is this way just in CoreFX, or also in .NET Framework.

**Comment by davidsh** [comment]
>I would assume the implementation doesn't allow setting close or keep-alive because there is already the KeepAlive property for that.

Yes, See docs:
https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.connection(v=vs.110).aspx

```
The request sends the Connection property to the Internet resource as the Connection HTTP header. If the value of the KeepAlive property is true, the value "Keep-alive" is appended to the end of the Connection header.
```

**Comment by davidsh** [comment]
>@davidsh might know the historical answer ... I wonder if it is this way just in CoreFX, or also in .NET Framework.

I don't know for sure. I would have to research this.  But we consider it a legacy property and advise developers to ignore it.

**Comment by karelz** [comment]
Sounds like this is mostly answered.
@baulig let us know if you need to know more details. Thanks!

**Comment by JonHanna** [comment]
> You cannot set it to either close or keep-alive (which are the only two valid values for this header)

Those are not the only two valid values. Aside from "close" which has a special meaning, the tokens in the Connection header list headers for the current hop only and which should be stripped by any proxy (though the proxy could put them right back in again, if valid and correct for the next hop). It obviously can't include headers that are specifically end-to-end, but it must include headers that are specifically hop-to-hop rather than just having that inferred, such as Keep-Alive and TE.
