### ISSUE TITLE
Make AppContext.BaseDirectory settable

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#2670]
On DNX 4.x (.NET Framework) we want to be able to set this directory to the application base of the project. Today AppDomain.CurrentDomain.BaseDirectory is set to the DNX folder so that we can take advantage of an NGened roslyn without having to xcopy any files into the application folder on build. It would be great if we could expose `AppContext.BaseDirectory` to point to the real appbase decoupled from the AppDomain property.

**Comment by weshaggard** [comment]
@davidfowl what does this get set to for DNX Core? Do you guys correctly setup the AppDomain to be the application base?

I agree we should provide a mechanism for the host to be able to set this value. @jkotas any thoughts on a good way to do that? I'm not super familiar with the native hosting APIs but is there a good place for the host to set this were we can query it?

**Comment by jkotas** [comment]
Note that this is problem for *desktop* only. It can be set to anything by the host on CoreCLR.

For desktop, I think we should just allow overriding the default via appdomain key/value pair:

```
string baseDirectory = AppDomain.GetData("APPLICATION_CONTEXT_BASE_DIRECTORY");
if (baseDirectory == null)
      baseDirectory = AppDomain.CurrentDomain.BaseDirectory
```

**Comment by davidfowl** [comment]
That sounds good! When can we do it?

**Comment by tarekgh** [comment]
@davidfowl I'll look at supporting this in the desktop, can you open a TFS bug to track this for the desktop?

**Comment by tarekgh** [comment]
This has been done in the desktop. the new AppDomain supported key is called  "APP_CONTEXT_BASE_DIRECTORY". I think we can close this issue now

**Comment by davidfowl** [comment]
Great! Would it also make sense to start using this API internally on .NET Framework in place of AppDomain.CurrentDomain.BaseDirectory for things like https://msdn.microsoft.com/en-us/library/system.resources.resourcemanager.createfilebasedresourcemanager(v=vs.110).aspx?
