### ISSUE TITLE
[ManagedHandler] Digest proxy auth seems to skip proxy after 407

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#26710]
Code here: https://github.com/dotnet/corefx/blob/25c4a916bf1f35be1d009b679b19f7ebea535647/src/System.Net.Http/src/System/Net/Http/Managed/HttpProxyConnectionHandler.cs#L124

The key point here is we shouldn't be using _innerHandler at this point, we should be using a proxied connection, like the basic logic above does.

**Comment by wfurt** [comment]
I'll take a look @geoffkizer

**Comment by wfurt** [comment]
closed by #26733
