### ISSUE TITLE
FileInfo.Length returns always 0

### ISSUE THREAD

**Issue by ThatDeveloper** [dotnet/corefx#26719]
# FileInfo.Length return always 0

FileInfo.Length return always 0. I tried it with a MVC Web App and a console application.
FileInfo is not null and the path is correct too. I tried to stream a video but if I don't get the range I can't stream it.

- fi.Exists is true
- fi.DirectoryName is correct (on both Windows and Mac) => Tried this in several folders.

@Eilon wrote in this issue https://github.com/aspnet/Home/issues/2840 that it probably belongs to this repository.

# General

.NET Core 2.0 & 2.0.5
Mac & Windows

# Sample

```
var fi = new FileInfo(Path.Combine("Videos/sample.mp4"));
Console.WriteLine(fi.Length);
Console.ReadLine();
```

**Comment by danmosemsft** [comment]
What is `fi.Exists`? Obviously it doesn't normally return 0 so we have to figure out what's special here.

**Comment by danmosemsft** [comment]
What if you remove the Path.Combine? Or use a full path?

**Comment by ThatDeveloper** [comment]
@danmosemsft If you look at my code sample in the issue there is fi defined. :)
I did test it with Path.Combine and with Absolute paths. Multiple times. And I also tried it with System.IO.File.OpenRead(path) and memory streams etc. etc. It is so strange. In the console application it is the same. Length is always 0.

**Comment by danmosemsft** [comment]
Does it repro for any paths? Basically I need a way to repro it here, unless you can debug it yourself. The fact that it reproes for Mac and Windows is strange as there is not much code in common there.

**Comment by joshfree** [comment]
At least on windows this can happen when a write handle is open to the file in question.

**Comment by ThatDeveloper** [comment]
How could I give you an example? Because my demo repository is over 500 mb with the sample file. @danmosemsft

**Comment by danmosemsft** [comment]
So it only reproes with this one file? How large is the file?

**Comment by ThatDeveloper** [comment]
@danmosemsft I tested it with files from 80MB up to 600MB.

**Comment by danmosemsft** [comment]
If you do the same with desktop .NET Framework do you get the same result?

>  I tested it with files from 80MB up to 600MB.

Does it repro with an arbitrarily small file then? If not how small?

**Comment by danmosemsft** [comment]
No response -- @ThatDeveloper please reopen if you have the extra info. We would definitely like to fix any bug, but casn't do it without a repro or more info.
