### ISSUE TITLE
flakey SqlConnectionBasicTests failure 

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#26724]
Failed in windows CI legs for 2.0.x PR https://github.com/dotnet/corefx/pull/26577

https://mc.dot.net/#/user/bording/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Frelease~2F2.0.0~2F/test~2Ffunctional~2Fcli~2F/289ddbee6ef7e22451bbe841e8171167b116e76a/workItem/System.Data.SqlClient.Tests/analysis/xunit/System.Data.SqlClient.Tests.SqlConnectionBasicTests~2FConnectionTimeoutTestWithThread

```
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Assert.True() Failure
Expected: True
Actual:   False
Stack Trace :
   at System.Data.SqlClient.Tests.SqlConnectionBasicTests.ConnectionTimeoutTestWithThread()
```

cc: @saurabh500

**Comment by saurabh500** [comment]
@geleems You should port your test changes to release/2.0.x branch.

**Comment by krwq** [comment]
Also failed exactly the same way here:
https://mc.dot.net/#/user/krwq/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Frelease~2F2.0.0~2F/test~2Ffunctional~2Fcli~2F/01ea1a10121fdfc6f3e577d66987b4deef97a507/workItem/System.Data.SqlClient.Tests

**Comment by karelz** [comment]
Given that 2.0 will be out of support in less than 1 month, closing as Won't Fix.
