### ISSUE TITLE
[ManagedHandler] HttpConnectionContent.TryComputeLength() always returns false/0

### ISSUE THREAD

**Issue by wfurt** [dotnet/corefx#26735]
The function should return true and proper value if Content-length has been specified in response. 
Aside from debugging this may help with decision if to drain certain responses or to abort connection.

**Comment by stephentoub** [comment]
I don't understand what this helps.  Can you clarify?  How does this help with debugging?  And how would this help with draining/aborting connections, considering they could just check the header themselves.

**Comment by wfurt** [comment]
Anybody can probably check the headers directly. What would be purpose of the function if it always fails? I bump to this when I was trying to debug the behavior and I was wondering why this always fails even if the response size is know. 

What we discussed with @geoffkizer is related to handling 407 (and possibly other responses) 
Right now we Dispose() the response and that will abort HttpConnection without returning it to pool.
If we know the error response is small we can simply read the response. That could be done without full draining described in  #23156

**Comment by stephentoub** [comment]
> What would be purpose of the function if it always fails?

This method is used in only a few very specific ways by internal infrastructure of HttpClient.  It's a Try method because it's expected that an implementation will only know the length in very specific circumstances, and it's perfectly reasonable to return false.  In fact, the main call site to this checks for the header before calling Try.

**Comment by geoffkizer** [comment]
Sorry, it's my fault that @wfurt filed this.

Just to make sure I understand: TryComputeLength is *only* used to set the Content-Length header, if it isn't already set.  Right?  I.e. when you access Content-Length and we don't have a value for it, we'll try to get one from TryComputeLength and set the header value.

For managed handler http response content, we will always set Content-Length if available, so there's no point in supporting TryComputeLength.

Any one who is interested in getting the content length should read Content-Length directly.

**Comment by davidsh** [comment]
> I.e. when you access Content-Length and we don't have a value for it, we'll try to get one from TryComputeLength and set the header value.

You don't always want to set the 'Content-Length' header on the HttpResponseMessage.Content.Headers.  If the response is Transfer-Encoding: chunked, there won't be a response header for example.  We shouldn't manufacture one.

**Comment by geoffkizer** [comment]
We're not.  Sorry if I'm being unclear.  My point is that, since we already set Content-Length if the response contains one, then there's no need to implement TryComputeLength here.

**Comment by stephentoub** [comment]
> Just to make sure I understand: TryComputeLength is only used to set the Content-Length header,

TryComputeLength is used in two places:
https://source.dot.net/#System.Net.Http/System/Net/Http/HttpContent.cs,a46935d921b7964a,references
- In MultipartContent as part of its TryComputeLength implementation calling TryComputeLength on each consituent content.  That's not for our response content.
- In HttpContent's GetComputedOrBufferLength, which itself is only used in the HttpContentHeaders.ContentLength property (https://source.dot.net/#System.Net.Http/System/Net/Http/Headers/HttpContentHeaders.cs,82), and then it's only called if there wasn't a Content-Length header set.
