### ISSUE TITLE
FileStream with no disk space kill process on Windows, corrupts data on Unix

### ISSUE THREAD

**Issue by ayende** [dotnet/corefx#26734]
Consider the following code:

```
using(var fs = File.Create(...)) // open a file to a drive with very little space left
{
   fs.Write(...); // this is held in the buffer, this pass
   fs.Write(...); // this is trigger, a write to disk, which will fail 
} // here we dispose the file stream properly
```

The problem is that the stream will try to write to the disk at three different times:

* At the second `Write` call. - FAIL
* On the `Dispose` - FAIL
* On the `Finalize` - FAIL and *kill the process*

The underlying reason is here:
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/Stream.cs#L239-L240

The Stream will first call the `Dispose(true)` and only then will it suppress the finalizer.
The problem is that if there is an issue writing to disk, such as no disk space, it will keep occurring and eventually the finalizer will execute the code and die.

Here is the stack trace from a production crash:

```
Exception object: 0000012fbd33ac60
Exception type:   System.IO.IOException
Message:          There is not enough space on the disk
InnerException:   <none>
StackTrace (generated):
    SP               IP               Function
    00000024382FF0D0 00007FFD8313108A System_Private_CoreLib!System.IO.FileStream.WriteCore(Byte[], Int32, Int32)+0x3cf7ea
    00000024382FF140 00007FFD82D611A2 System_Private_CoreLib!System.IO.FileStream.FlushWriteBuffer(Boolean)+0x62
    00000024382FF180 00007FFD82D60FA1 System_Private_CoreLib!System.IO.FileStream.Dispose(Boolean)+0x41
    00000024382FF1D0 00007FFD82D60631 System_Private_CoreLib!System.IO.FileStream.Finalize()+0x11
```

**Comment by ayende** [comment]
Things to note. This is the case only on Windows. On Unix, we have: 
https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/IO/FileStream.Unix.cs#L239-L247

I think that this is wrong. Disposing a FileStream is document to flush the written bytes.
However, it will just ignore any IO Exceptions (such as no disk space) without reporting them to the calling code.

```
using(var fs = File.Create(...)) // open a file to a drive with very little space left
{
   fs.Write(...); // this is held in the buffer, this pass
} // exception is caught here

// application think that the system wrote the data, but the write actually silently failed.
```

I believe, based on the comment, that in both Windows & Linux, only during disposal of the file stream, IO Errors should be ignored.

**Comment by danmosemsft** [comment]
> in both Windows & Linux, only during disposal of the file stream, IO Errors should be ignored.

Do you mean only during dispose during finalization? As on Linux it only catches it if it's in the finalizer:
```
                    catch (IOException) when (!disposing)
                    {
                        // On finalization, ignore failures from trying to flush the write buffer,
                        // e.g. if this stream is wrapping a pipe and the pipe is now broken.
                    }
```

That seems like a reasonable thing for Windows to do as well. Dispose would likely have already thrown, and even if not, it seems harsh to bring down the process. @JeremyKuhne @stephentoub do you agree?

**Comment by stephentoub** [comment]
> do you agree?

Sounds reasonable.

**Comment by danmosemsft** [comment]
@ayende would you like to offer a PR and test?

**Comment by JeremyKuhne** [comment]
I agree as well. We should, however, be a little more aggressive in what we're catching here. It is also theoretically possible we could get AccessDenied.

**Comment by danmosemsft** [comment]
@maryamariyan here's a small one for you

**Comment by maryamariyan** [comment]
Thanks @danmosemsft

**Comment by GSPP** [comment]
Does this not mean that if `Dispose` fails to flush then it leaves the handle open? Is that by itself not an issue? This means that resources will not be freed and the file will remain locked. I would never expect a dispose call to do that even if it happens to throw. It also means that there is no way to free the handle on demand when the disk is full, right?

**Comment by ayende** [comment]
Yes, this should be closed anyway.
As an added safety, the SafeFileHandle itself is going to close to handle on its own finalizer, if needed.

**Comment by wiz0u** [comment]
Any chances to have this bug fix ported on .NET Framework 4.8 as well?

**Comment by jkotas** [comment]
This fix does not meet the bar for .NET Framework port. There may existing applications that depend on the existing .NET Framework behavior.
