### ISSUE TITLE
Responses to 407 proxy authentication request are always sent on new connection

### ISSUE THREAD

**Issue by wfurt** [dotnet/corefx#26732]
I tested this with curl handler and the authentication is sent back on same connection as original request.  For managed handler the expectation would be same to save extra OS file descriptor and TCP (possibly TLS) handshake.  

The setup is trivial: configure managed Handler to use proxy requiring Basic or Digest authentication and request any page. Two connections will be established to handle single request. 

existing code looks like:
```c#
            if (response.StatusCode == HttpStatusCode.ProxyAuthenticationRequired)
            {
                foreach (AuthenticationHeaderValue h in response.Headers.ProxyAuthenticate)
                {
                    if (h.Scheme == AuthenticationHelper.Basic)
                    {
                        NetworkCredential credential =
                            _proxy.Credentials?.GetCredential(proxyUri, AuthenticationHelper.Basic) ??
                            _defaultCredentials?.GetCredential(proxyUri, AuthenticationHelper.Basic);

                        if (credential != null)
                        {
                            response.Dispose();
```
Because we Dispose context without processing it, that leaves HttpConnection in undefined state so it is disposed rather than returned back to connection pool.  I verified that adding connection.LoadIntoBufferAsync() fixes this and authentication will happen on same connection when possible. We discussed this with @geoffkizer and we need some better mechanism how to drain/discard response we don't care about so we can use existing connection for other requests.

**Comment by karelz** [comment]
Does not seem to be critical for 2.1 - moving to Future.
cc @geoffkizer @stephentoub

**Comment by geoffkizer** [comment]
I believe we should address this for 2.1.

**Comment by geoffkizer** [comment]
Just to be clear: If every authenticated proxy request requires two proxy connections, someone will notice this and point out that we are doing something very stupid.

**Comment by geoffkizer** [comment]
Is there a test for this?  I couldn't find anything.

**Comment by davidsh** [comment]
>Is there a test for this? I couldn't find anything.

Writing a test for this could be tricky.  We would need  the loopback proxy server to track how many incoming connections were made to it, etc.

I would be fine if this got fixed and the test was done manually.

@wfurt We discussed this in meeting today.  You mentioned this might be fixed already due to other changes.  Do you plan to validate that?

**Comment by wfurt** [comment]
yes, @davidsh I plan to look at it. And yes, I think loopback can work.

**Comment by wfurt** [comment]
I verified manually that this is fixed. Remaining work is writing test.
