### ISSUE TITLE
System.Memory tests hanging in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#26748]
e.g.
https://mc.dot.net/#/user/Priya91/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/f66b25054d7156bafca6c8902158ff55036d6de3/workItem/System.Memory.Tests/wilogs
```
2018-02-01 16:11:49,059: INFO: proc(54): run_and_log_output: Output: Discovering: System.Memory.Tests
2018-02-01 16:11:49,388: INFO: proc(54): run_and_log_output: Output: Discovered:  System.Memory.Tests
2018-02-01 16:11:49,654: INFO: proc(54): run_and_log_output: Output: Starting:    System.Memory.Tests
2018-02-01 16:14:02,436: INFO: proc(54): run_and_log_output: Output: Span.BinarySearch test BinarySearch_MaxLength_NoOverflow skipped (could not alloc memory).
```
cc: @ahsonkhan, @AtsushiKan

**Comment by ahsonkhan** [comment]
cc @nietras 

The test seems to be doing exactly what it should:
https://github.com/dotnet/corefx/blob/master/src/System.Memory/tests/ReadOnlySpan/BinarySearch.cs#L123

It is likely some other test.

**Comment by ahsonkhan** [comment]
This test looks like the culprit: System.Buffers.Text.Tests.ParserTests.TestParser2GiBOverflow [STARTING]

It is hanging on my local machine.

**Comment by ahsonkhan** [comment]
@AtsushiKan, can we reduce some of the test cases here. I believe they end up taking too long and can cause the timeout. https://github.com/dotnet/corefx/blob/master/src/System.Memory/tests/ParsersAndFormatters/Parser/ParserTests.2gbOverflow.cs#L92

**Comment by AtsushiKan** [comment]
That test was brought over at your request. I have no objection to reducing the dataset or removing it altogether. This business of running resource-hogging tests on CI boxes we have no control over just isn't working.

**Comment by ahsonkhan** [comment]
> That test was brought over at your request. I have no objection to reducing the dataset or removing it altogether.

We can always run the test cases locally if there is ever code churn in that space. Although, I don't expect there to be many changes now.

**Comment by ahsonkhan** [comment]
Closing this issue based on the changes in https://github.com/dotnet/corefx/pull/26751. Please feel free to re-open if we see the issue again.
