### ISSUE TITLE
Review performance of ReadOnlyBuffer and evaluate use of Inlining

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#26740]
See https://github.com/dotnet/corefx/pull/26694#discussion_r165252355 for the discussion. We need to do another pass since all of the code churn took place make sure these are still valuable.

**Comment by benaadams** [comment]
Some of them will be horrors now

**Comment by ahsonkhan** [comment]
From https://github.com/dotnet/corefx/pull/26694#issuecomment-363612315
Leftover changes deferred for when we update based on performance review:
- Review Inlining - https://github.com/dotnet/corefx/issues/26740
- Fix SeekMultiSegment - https://github.com/dotnet/corefx/pull/26694#discussion_r165741661
- Fix bounds checks - https://github.com/dotnet/corefx/pull/26694#discussion_r165548714
- Use Array.Empty or cache T[0] - https://github.com/dotnet/corefx/pull/26694#discussion_r165249258
- CopyTo update - https://github.com/dotnet/corefx/pull/26694#discussion_r165253604

Issue for code coverage:
- Add more tests - https://github.com/dotnet/corefx/issues/26768
