### ISSUE TITLE
System.Memory : request pre-built "unmanaged external memory" OwnedMemory implementation to allow Memory-T to be used against a pointer (with the caller owning the lifetime etc)

### ISSUE THREAD

**Issue by mgravell** [dotnet/corefx#26781]
Intent: to be able to use `Memory<T>` APIs with data that is backed by a raw pointer. This is currently trivially possible for `Span<T>`, but not `Memory<T>`.

There is a `NativeOwnedMemory` which is an `OwnedMemory<byte>`, and which allocates internally via `Marshal.AllocHGlobal`, however I perceive that it is a common scenario - for people working with this type of API - to need to work with arbitrary memory from a pointer (most likely unmanaged, but with lifetime controlled separately to this usage). Example use-case: working with data that needs to be allocated via a special allocator, such as data to be used with a GPU (for best performance, CUDA requires that *it* does the allocations - presumably to do with alignment, execution flags, and paging flags).

It is also sometimes useful to be able to use a `Memory<T>` API with a `stackalloc` chunk (not to be confused with a `Span<T>` API which can already be `stackalloc`'d without needing extra work). An example use-case of when you might need to use `Memory<T>` with `stackalloc` is when using `Parallel` to process complex data optimally: you can't make a `Span<T>` available to a worker because of the stack semantics, but it is actually perfectly safe for the workers to talk to the shared `stackalloc` area, since it will not go out of scope (the `Parallel` execution won't finish until we're done).

Edit: to be 100% clear, I absolutely **do not** propose that it should be possible to use `stackalloc` with this type of object without using the `unsafe` keyword - since it would be too easy to pass a `Memory<T>` outside of the stackframe. If you're doing this kind of thing, you need to accept that it is your job to not mess up; so it **should not** allow `Memory<int> evil = stackalloc int[40];`. If somebody **chooses** to use `unsafe` code and create a `Memory<T>` from a pointer: they need to accept responsibility. For similar reasons, it probably shouldn't allow an `IntPtr`: you *really* want to know that you're going `unsafe` here!

This can be done quite simply by providing an `OwnedMemory<T>` subclass that takes a `void*` pointer and length. It could be a `public` type, or it could be exposed by a `static` factory method on `Memory<T>`, i.e. `public static Memory<T> Unsafe(void* ptr, int count) => ...`. This factory method would have parity with `Span<T>`, since `Span<T>` already has a `void*, int` constructor. A `static` factory method is the next best thing to a constructor, and fits this scenario well IMO.

The implementation would not be hard - it is broadly similar to `NativeOwnedMemory`, but a: is generic in `<T>`, and b: doesn't do anything re lifetime.

Example:

        partial class Memory<T>
        {
            /// <summary>
            /// Makes a pointer usable as a Memory<T>; note that no lifetime
            /// semantics are assumed - the caller is still entirely responsible
            /// for the lifetime of the pointer provided, and if that pointer
            /// becomes invalid: that's on the caller. It is explicitly assumed that
            /// this memory is fixed/pinned.
            /// </summary>
            public static Memory<T> Unsafe(void* ptr, int length)
                => PointerMemory<T>.AsMemory(ptr, length);
        }

        sealed unsafe class PointerMemory<T> : OwnedMemory<T>
        {
            public static Memory<T> AsMemory(void* pointer, int length)
                => new PointerMemory<T>(pointer, length).Memory;
            private readonly void* _pointer;
            private readonly int _length;
            public PointerMemory(void* pointer, int length)
            {
                _pointer = pointer;
                _length = length;
            }
            public override bool IsDisposed => false;
            public override int Length => _length;
            public override Span<T> Span => new Span<T>(_pointer, _length);
            protected override bool IsRetained => false;
            public override MemoryHandle Pin() => new MemoryHandle(this, _pointer);           
            public override bool Release() => true;
            public override void Retain() { }
            protected override void Dispose(bool disposing) { }
            protected override bool TryGetArray(out ArraySegment<T> arraySegment)
            {
                arraySegment = default;
                return false;
            }
        }

Note: If a retain-count is required for API reasons, that can be added easily via `Interlocked` as usual.

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefxlab/issues/1924

**Comment by davidfowl** [comment]
Sounds like you just want the ability to create Memory\<T\> over a pointer. “I know what I’m doing” mode.

**Comment by mgravell** [comment]
@stephentoub  yes, I'd agree that this is a dup of #1924 so I'll close it; thanks

@davidfowl  hell yeah :)

**Comment by stephentoub** [comment]
> Sounds like you just want the ability to create Memory<T> over a pointer. “I know what I’m doing” mode.

I would like this, too, obviously.  The key question is "how".  Either we a) modify the `Memory<T>` implementation to support wrapping pointers directly, which makes the pointer case 1st-class and as efficient as possible but adds cost to the other more common scenarios, or b) support pointers via the `OwnedMemory<T>` abstraction and allocate an object for it.  At this point I think we've landed firmly in the (b) camp, which then just means determining how best to expose the functionality in a way that doesn't make the developer think it's allocation free (as constructing `Memory<T>` otherwise is).  I personally like the explicitness then of forcing the developer to `new`-up something, e.g. `new NativeOwnedMemory(ptr, length)`, rather than an API like `new Memory<T>(ptr, length)` or `Memory<T>.Create(ptr, length)` that doesn't scream "this allocates".

**Comment by mgravell** [comment]
@stephentoub I also agree that "b" is appropriate and applicable - given that you're *already* choosing to pay the slight indirection cost  of `Memory<T>` => `Span<T>`, the extra object is nominal - you shouldn't be doing this in a loop, for example. Likely use-cases:

- you create a `Memory<T>` with an `OwnedBuffer<T>` when allocating an external long-lived resource and then barely touch it (perhaps slicing and dicing) : the single small object will probably hit GEN2 and live a long and happy life
- you create a `Memory<T>` for something like the other scenario I mentioned - the `stackalloc` with `Parallel`; here, you're probably doing some short-lived bulk processing, and the object will die quickly in GEN0 (GEN1 at worst)

in either scenario, I don't see that the object is a huge concern. The anti-pattern to avoid would be allocating a ton of these objects representing tiny slices in the same data by creating lots of `OwnedMemory<T>`, rather than slicing a single `OwnedMemory<T>` -  but: you can misuse *any* API if you're determined to...

**Comment by mgravell** [comment]
@stephentoub  re your a vs b: that's why I called out the difference between what I called just `PointerMemory<T>` (that doesn't handle lifetime), vs the existing internal type that handles lifetime internally. I think they're very different scenarios that warrant 2 different but related implementations.
