### ISSUE TITLE
ManagedHandler: ReadNextLineAsync logic appears incorrect

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#26780]
https://github.com/dotnet/corefx/blob/bb738a07720a8c0888a088f2adb737d2cbe09ca2/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnection.cs#L905

We are setting the searchOffset to length, but we should be doing searchOffset += length.  Otherwise we will search through bytes we've already scanned.

This isn't a correctness issue (we just rescan extra bytes), but if we're going to try to be smart here about not rescanning, we should do it correctly.

@stephentoub can you look at this and let me know if I'm missing something here?

**Comment by stephentoub** [comment]
Yup, you're right.
