### ISSUE TITLE
In what cases "R" format fails to round-trip float value?

### ISSUE THREAD

**Issue by LeonidVasilyev** [dotnet/corefx#26785]
[Standard Numeric Format Strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#the-general-g-format-specifier) article states that in order to successfully round-trip `Single` value one must use `G9` format specifier because `R` doesn't work sometimes:
> When used with a [Single](https://docs.microsoft.com/en-us/dotnet/api/system.single) value, the "G9" format specifier ensures that the original [Single](https://docs.microsoft.com/en-us/dotnet/api/system.single) value successfully round-trips. This is because [Single](https://docs.microsoft.com/en-us/dotnet/api/system.single) is an IEEE 754-2008-compliant single-precision (`binary32`) floating point number that gives up to nine significant digits of precision. We recommend its use instead of the ["R" format specifier](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#RFormatString), since in some cases "R" fails to successfully round-trip single-precision floating point values.

> For [Double](https://docs.microsoft.com/en-us/dotnet/api/system.double) and [Single](https://docs.microsoft.com/en-us/dotnet/api/system.single) values, the "R" format specifier in some cases fails to successfully round-trip the original value and also offers relatively poor performance. Instead, we recommend that you use the ["G17"](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#GFormatString) format specifier for [Double](https://docs.microsoft.com/en-us/dotnet/api/system.double) values and the ["G9"](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#GFormatString) format specifier to successfully round-trip [Single](https://docs.microsoft.com/en-us/dotnet/api/system.single) values.

To find such cases I used code snippet similar to the following one (Windows 10 x64, .NET Core 2.0 and .NET Framework 4.5) and found none:

```csharp
using System;
using System.Globalization;

public class Program
{
    static unsafe float Int32BitsToSingle(int value) => *(float*)(&value);
    static void Main(string[] args)
    {
        long cnt = 0;
        long expCnt = (long)int.MaxValue - int.MinValue + 1;
        var inv = CultureInfo.InvariantCulture;
        for (int i = 0; cnt < expCnt; ++i, ++cnt)
        {
            float f = Int32BitsToSingle(i);
            if (cnt % 1000000 == 0)
            {
                Console.Clear();
                Console.WriteLine(((float)cnt / expCnt).ToString("#0.####%", inv));
            }
            if (float.IsNaN(f))
                continue;
            var r = f.ToString("R", inv);
            if (float.Parse(r, inv) == f)
                continue;

            Console.WriteLine("Found on " + i);
            Console.WriteLine(f.ToString(inv));
            Console.WriteLine(f.ToString("G9", inv));
            Console.WriteLine(r);
            return;
        }
        Console.WriteLine("Not found");
    }
}
```

**Comment by joperezr** [comment]
cc: @mairaw Given that this is official documentation, do you mind sharing an example of where does this fail?

**Comment by tannergooding** [comment]
@LeonidVasilyev, this can vary from platform to platform as the code in question previously depended on native APIs to complete the operation.

There was some work to fix these issues and they should generally be resolved. However, explicitly requesting `G9` or G17` will still be more performent than `R` due to the way it is implemented (it first tries to convert to a 7/15 digit string, round trips it back to a float/double, and returns the result if equal to the original; otherwise it recomputes at 9/17 digits).

**Comment by mairaw** [comment]
Adding @rpetrusha

**Comment by tannergooding** [comment]
Now that dotnet/coreclr#22040 is merged, for .NET Core 3.0, `ToString()`, `ToString("G")`, `ToString("R")`, `double.ToString("G17")`, and `float.ToString("G9")` should now always produce a string that will roundtrip to the original value..
