### ISSUE TITLE
[DirectoryInfo]::GetFiles()/GetDirectories() not working correctly on macOS

### ISSUE THREAD

**Issue by SteveL-MSFT** [dotnet/corefx#26797]
Based on default macOS case-insensitive filesystem

Repro using PSCore6:

```powershell
md Test
$d = [System.IO.DirectoryInfo]::new($pwd)
$d.GetDirectories("test")
```

Expected:

DirectoryInfo for "Test" folder

Actual:

null

This works as expected on Windows.

**Comment by danmosemsft** [comment]
@JeremyKuhne this would appear to be an issue in file enumeration. (I assume we're creating the directory in the requested case)

**Comment by JeremyKuhne** [comment]
Perhaps our algorithm isn't working correctly for determining case? @SteveL-MSFT, can you try the logic we're doing here:

https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/Common/src/System/IO/PathInternal.CaseSensitivity.cs#L37

**Comment by SteveL-MSFT** [comment]
@JeremyKuhne on my macBook Pro, creating a filestream called "FILEstream" using the code above, FileExists("filestream") returns true.

**Comment by JeremyKuhne** [comment]
@SteveL-MSFT we've been unable to get a repro on this, I've added a test to see if we can flush out where our default casing determination isn't what we expect.

**Comment by JeremyKuhne** [comment]
Closing as we can't get a local repro. As mentioned, I've added a Mac specific test to see if we can flush out when our case sensitivity analysis isn't what we expect.
