### ISSUE TITLE
[Fedora.27] Test failures: System.Net.Http.Functional / * - unsupported libcurl (7.55.1) and its SSL backend (\"OpenSSL/1.1.0g\")

### ISSUE THREAD

**Issue by pjanotti** [dotnet/corefx#26803]
Test pass on Fedora are failing for certificate and SSL:
```
Assert.Throws() Failure
Expected: typeof(System.Net.Http.HttpRequestException)
Actual:   typeof(System.PlatformNotSupportedException): The handler does not support custom handling of certificates with this combination of libcurl (7.55.1) and its SSL backend (\"OpenSSL/1.1.0g\").
```

Affected tests: 23

## History of failures

Day | Build | Details
-- | -- | -- 
2/2 | 20180202.05 | 23x - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180202.05/workItem/System.Net.Http.Functional.Tests)
2/2 | e328a11841e2c7cc34d6cba6925aaadaa6549721 | 2x - [link](https://mc.dot.net/#/user/pjanotti/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/e328a11841e2c7cc34d6cba6925aaadaa6549721/workItem/System.Net.Http.Functional.Tests)
2/3 | 20180203.01 | 23x - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180203.01/workItem/System.Net.Http.Functional.Tests)
2/3 | 20180203.03 | 23x - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180203.03/workItem/System.Net.Http.Functional.Tests)

**Comment by stephentoub** [comment]
The issue is what the error message says:
```
this combination of libcurl (7.55.1) and its SSL backend (\"OpenSSL/1.1.0g\")
```
The implementation requires OpenSSL/1.0.

**Comment by karelz** [comment]
@bartonjs do you know if we need full OpenSSL 1.1 support (#9855) to support it as backend of libcurl, or if some partial solution might light up the scenario (assuming it is a good idea).

We have always the option to change Fedora27 images - @wfurt did you hit this or something similar recently?

**Comment by bartonjs** [comment]
@karelz I cannot envision any reasonable partial support solution.  It's pretty much "we support 1.1 and not 1.0 as a platform" (on this installation) or "we support 1.0 and not 1.1".

**Comment by karelz** [comment]
Bummer, let's fix the Helix infra then. @wfurt can you please help here?

**Comment by karelz** [comment]
This is causing 23 failures in each official Helix test run - see updated to post, let's try to address it soon.

**Comment by pjanotti** [comment]
Earlier I put a PR out to disable the tests on Fedora.27 (#25385), when CI passes we can merge it. After that is merged we can add the `disabled-test` label on this issue and use it to track the update of Fedora.27 image.

@dotnet/dnceng Fedora.27 is missing an updated version of Open SSL that is present in Fedora.26. Can we get that updated?

**Comment by karelz** [comment]
Thanks @pjanotti - I think you meant PR #26835 (fixed above).

BTW: Technically speaking, OpenSSL 1.1 is newer than 1.0, so we need older version present on Fedora27

**Comment by MattGal** [comment]
@pjanotti if you want to run legacy OpenSSL on Fedora 27, we might be able to accommodate this but I'm unsure why we'd want to as running on what comes with the OS makes the most sense to me.  Can you explain why you want it, and point to instructions how to do this?

**Comment by wfurt** [comment]
forcing two version of openssl is going to be problematic IMHO. I don't think we will be able to doge 1.1 support forever.

**Comment by bartonjs** [comment]
There's no problem with the version(s) of OpenSSL on the machine.  The problem is that libcurl is built against OpenSSL 1.1, while we're built against OpenSSL 1.0.  The tests should already understand situations where the cert interop support is limited, and Fedora 27 just needs to be added to that list.

So I don't think there's any work here for engineering.

@wfurt It's true that we can't dodge 1.1 forever.  But we also can't upgrade to it right now because a) we don't have time and b) our portable builds need to support distros which can't have 1.1.  The answer, to me, is to stop using curl so we don't get the same dependency from two sources.

**Comment by karelz** [comment]
@bartonjs 

> The tests should already understand situations where the cert interop support is limited, and Fedora 27 just needs to be added to that list.

Can you point me to what you mean by that? If the incompatibility is limited to just certain cert interop scenarios and there are workarounds for customers, disabling tests on particular platforms might be the right thing to do.

cc @joshfree

**Comment by bartonjs** [comment]
@karelz https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/tests/FunctionalTests/HttpClientEKUTest.cs#L18-L39 is one such place.  Though it should be checking for "OpenSSL/1.0", not just "OpenSSL", since that's what the product keys off of (https://github.com/dotnet/corefx/blob/a26de495ffa390a9d6b3a0d0f338e9d9f97ad5fe/src/Common/src/Interop/Unix/System.Net.Http.Native/Interop.VersionInfo.cs#L50)

**Comment by pjanotti** [comment]
ok, I will implement proper test skipping for this case instead of the broad emergencial fix that is place right now.

**Comment by joshfree** [comment]
> The problem is that libcurl is built against OpenSSL 1.1, while we're built against OpenSSL 1.0.  

Finding the default libcurl package built against 1.1 is going to start being more common going forward.  I'm half expecting to see this when we turn on the Ubuntu 18.04 legs next, for instance.

@bartonjs can you look into this more to determine if these distros have an alternative libcurl built against 1.0 in their store still (as a stop gap workaround) and if not, determine what a short term solution could be?

**Comment by pjanotti** [comment]
I'm closing the issue since is related directly to the test failures and that is properly resolved now. Of course, the conversation about the dependency workaround/solution continues as appropriate.

**Comment by tmds** [comment]
> Can you point me to what you mean by that? If the incompatibility is limited to just certain cert interop scenarios and there are workarounds for customers

@karelz I had a look what doesn't work with an unsupported libcurl backend:

client certificates:
- HttpClientHandler.ClientCertificates: not empty
- HttpClientHandler.ClientCertificateOptions set to Automatic

validation:
- HttpClientHandler.CheckCertificateRevocationList set to true
- HttpClientHandler.ServerCertificateCustomValidationCallback not null (+)

(+) HttpClientHandler.ServerCertificateCustomValidationCallback may be set to HttpClientHandler.DangerousAcceptAnyServerCertificateValidator to disable validation completely

**Comment by bartonjs** [comment]
| Distro Version | Default libcurl backend | optional package for OpenSSL/1.0 |
| --- | --- | --- |
| Ubuntu 18.04 (2018-02-06) | OpenSSL 1.0.2 | N/A (default) |
| Debian 9 | OpenSSL 1.0.2 | N/A (default) |
| Fedora 27 | OpenSSL 1.1.0 | N/A (no alternate packages) |

For Fedora 27 the following workaround may be viable:

* `yum install compat-openssl10-devel`
* Download the source for libcurl (7.55 is what is present on the system, so https://curl.haxx.se/download/curl-7.55.0.tar.bz2)
* ./configure
  * Ensure the output says that it used OpenSSL 1.0.2
* make

I was able to succeed by using LD_PRELOAD to force the local copy of libcurl, perhaps there's a place that it can be put to make dotnet launches prefer it over system copies.  bin/netcoreapp2.0 didn't work, nor did putting it next to System.Net.Http.Native.so.

**Comment by arleyschrock** [comment]
I wish the dependency on curl would just die (like it should). This causes more headaches in deployment scenarios then anything else with the framework

**Comment by tmds** [comment]
@arleyschrock curl is no longer used (by default) in 2.1, there is a managed http client implementation https://blogs.msdn.microsoft.com/dotnet/2018/04/11/announcing-net-core-2-1-preview-2/

**Comment by arleyschrock** [comment]
That is excellent news! For those having problems on Ubuntu 18.04, removing the libcurl4 package and installing libcurl3 resolves the issue
