### ISSUE TITLE
tracking UWP test leg disable/re-enable for Vector<T>

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#26802]
Due to timing issues with consuming https://github.com/dotnet/coreclr/pull/16133 across coreclr / corert / .NET Native, we'll need to temporarily disable the UWP test leg in the corefx repo.  Once .NET Native is updated to react to the Vector<T> typeforward, we'll re-enable the test leg - sometime next week Feb 5 - Feb9.

cc: @eerhardt @nattress

**Comment by jkotas** [comment]
These 3 commits should be undone once this is fixed:

https://github.com/dotnet/corefx/commit/120dce456a90df9982797d6c94eaaababd3e00d1
https://github.com/dotnet/corefx/commit/2202b4fd49ace58876763903f43cf27b2275c10a
https://github.com/dotnet/corefx/commit/a296c86639cc59ae486d2e3870c6e75817e88992
