### ISSUE TITLE
Add generic methods to SerializationInfo class

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/corefx#26818]
Hi,

## Proposal
Please add a couple of generic methods to the [`SerializationInfo`](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Runtime/Serialization/SerializationInfo.cs#L441) class.

## Added API:

```c#
public class SerializationInfo {
  + public void AddValue<T>(string name, T value);
  + public T GetValue<T>(string name);
}
```

## Motive

Currently, when we want to use `SerializationInfo` in a serialization context (binary in my scenario), I have to convert all the fields back and forth.

Here's an example of how ugly this can get.

```c# 
protected CategoryGroupDefinition(SerializationInfo info, StreamingContext context)
  : this(
      (Guid)info.GetValue(nameof(Id), typeof(Guid)),
      info.GetString(nameof(Title)),
      (CategoryGroupDefinition)info.GetValue(nameof(Parent), typeof(CategoryGroupDefinition)),
      (GroupType)info.GetValue(nameof(Type), typeof(GroupType)),
      info.GetBoolean(nameof(IsMandatory)),
      (CategoryDefinition[])info.GetValue(nameof(Children), typeof(CategoryDefinition[])))
{
}
```

Adding some generic methods will shorten the above to:

```c#
protected CategoryGroupDefinition(SerializationInfo info, StreamingContext context)
  : this(
      info.GetValue<Guid>(nameof(Id)),
      info.GetString(nameof(Title)),
      info.GetValue<CategoryGroupDefinition>(nameof(Parent)),
      info.GetValue<GroupType>(nameof(Type)),
      info.GetBoolean(nameof(IsMandatory)),
      info.GetValue<CategoryDefinition[]>(nameof(Children)))
{
}
```

**Comment by karelz** [comment]
cc @ViktorHofer as FYI

**Comment by danmosemsft** [comment]
Although we prefer folks not write new code using BinaryFormatter, this seems a small change that makes a big improvement.

**Comment by weitzhandler** [comment]
@danmosemsft feel free to assign me.

**Comment by danmosemsft** [comment]
First Viktor would have to sponsor through API review...

**Comment by weitzhandler** [comment]
Ok I see.

**Comment by ViktorHofer** [comment]
@karelz changing from `area-Serialization` to `area-System.Runtime`.

**Comment by ViktorHofer** [comment]
@weitzhandler to be honest I'm not a fan of adding new APIs to the System.Runtime.Serialization.Formatters namespace. We don't want to encourage our customers to use BinaryFormatter and usually recommend to shift to other frameworks like Json.NET. Adding these helper methods conveys the wrong message IMO. I also doubt that it would pass api review as our PM has a strong opinion about binary serialization.

**Comment by weitzhandler** [comment]
@ViktorHofer 
Thanks for your response!
Can you please get a bit more detailed about the dark side of binary serialization?

**Comment by ViktorHofer** [comment]
I cite myself from here https://docs.microsoft.com/en-us/dotnet/standard/serialization/binary-serialization

> As the nature of binary serialization allows the modification of private members inside an object and therefore changing the state of it, other serialization frameworks like JSON.NET which operate on the public API surface are recommended.

**Comment by weitzhandler** [comment]
Thanks.
In some scenarios binary serialization is still the right option (my current case - where I want to backup state of an immutable object).
Binary serialization also makes it easier to serialize using constructor.

Anyway I understand why the API shouldn't be expanded.
