### ISSUE TITLE
Always use MemoryFileStreamCompletionSource in FileStream 

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#26817]
Today it looks like the code in FileStream is unwrapping the underlying `Memory<byte>` to a `byte[]` when it does an async Read or Write operation on windows. If you pass a pre-pinned buffer that happens to be backed by an array then you'll lose the benefits as the PreAllocatedOverlapped will pin the buffer again.

https://github.com/dotnet/corefx/blob/103639b6ff5aa6ab6097f70732530e411817f09b/src/Common/src/CoreLib/System/IO/FileStream.Windows.cs#L851-L853

https://github.com/dotnet/corefx/blob/103639b6ff5aa6ab6097f70732530e411817f09b/src/Common/src/CoreLib/System/IO/FileStream.Windows.cs#L1072-L1074

I might be missing something, What was the reasoning behind this implementation?

/cc @stephentoub

**Comment by stephentoub** [comment]
> as the PreAllocatedOverlapped will pin the buffer again

The common case this was written for is where the destination is actually the FileStream's internal buffer.  That buffer is already pinned as part of the PreAllocatedOverlapped.  By unwrapping it, we take advantage of this path that doesn't pin it each time:
https://github.com/stephentoub/coreclr/blob/2eb7b4f04cda0686d550cf812a783788b3c57dfc/src/mscorlib/shared/System/IO/FileStreamCompletionSource.Win32.cs#L46-L53
If instead we just always passed that MemoryFileStreamCompletionSource and it called Retain, we would create a new GCHandle each time, even when it's the same as the one already pinned by the PreAllocatedOverlapped.

Another reason is that the base type wouldn't need to carry around the extra state for the MemoryHandle if the array could be extracted.

However, all of this was implemented when the Retain stuff was in its infancy.  Looking at it again, these types could probably be combined, and although we would still end up paying a bit more in allocation to hold onto the MemoryHandle, we could still fetch out the array from the Memory and do the same comparison that's being done now, and avoid calling Retain if the array is the internal buffer.  Or potentially just modify the derived type to do that check and avoid calling Retain in that case.

Please feel free to submit a PR.  We're still waiting for PRs from you ;)

**Comment by davidfowl** [comment]
Would I make this change in coreclr or corefx or both?

**Comment by stephentoub** [comment]
Just coreclr. The tests live in corefx, but you run them against your built coreclr with your changes, and I wouldn't expect any test changes or additions to be needed here (except maybe tests that explicitly validate using Memory, but I think/hope I already are some).

**Comment by davidfowl** [comment]
Yea, I started to take a look, it's a bit more involved than I originally thought. Maybe I'll do a multiple commits.

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/coreclr/issues/16190

**Comment by davidfowl** [comment]
@stephentoub I'll file another issue with the follow up from the PR

**Comment by stephentoub** [comment]
Thanks
