### ISSUE TITLE
Microsoft.XmlSerializer.Generator - generate the serializer for a subset of types in the assembly

### ISSUE THREAD

**Issue by BAlbrich** [dotnet/corefx#26815]
Sgen has the parameter /type to add a list of types to be included in the serializer. As far as I can see there is no built in way to do that for Microsoft.XmlSerializer.Generator.

My workaround is to define a property in my project `<SgenTypes>"Type1;Type2"</SgenTypes>` and to change the exec line in the targets file to `<Exec Command="dotnet Microsoft.XmlSerializer.Generator $(IntermediateOutputPath)$(AssemblyName)$(TargetExt) /force /quiet /type:$(SgenTypes)" ContinueOnError="true"/>
`
Is there a better way to do this? If there is then it would be nice if it would be included in the documentation.

**Comment by huanwu** [comment]
@BAlbrich Thanks for your feedback. We already added this support [here](https://github.com/dotnet/corefx/pull/24491). It is supposed to there in next release. Or you can try to use the latest package in myget [System.Xml.XmlSerializer](https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Xml.XmlSerializer)  and [Microsoft.XmlSerializer.Generator](https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.XmlSerializer.Generator) and see if it works as you expected.
