### ISSUE TITLE
Changing Span/Memory to return default on null instead of throwing

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#26833]
Follow up on https://github.com/dotnet/corefx/pull/26807 :

- TODO: Add tests for when array/string are null but start/length are non-zero.

- Change Memory constructors. I had to disable tests for them in Update CoreCLR PR:
https://github.com/dotnet/corefx/commit/87fd2766fdb3920b307b873c1cff824bebd17f3b

**Comment by fujiy** [comment]
After this change, we may not need this fix anymore?

https://github.com/dotnet/corefx/pull/25257
https://github.com/dotnet/corefx/issues/16730

Should we revert it?

**Comment by ahsonkhan** [comment]
> After this change, we may not need this fix anymore?

This got addressed here already: https://github.com/dotnet/corefx/pull/26807#issuecomment-362767070

**Comment by ahsonkhan** [comment]
> Change Memory constructors

The Memory/ROMemory constructors have the null checks:
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Memory.cs#L48

They just haven't gotten mirrored to corefx: https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Memory.cs#L47

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/dotnet/corefx/pull/26868
