### ISSUE TITLE
Create OOB FileSystem package

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#26838]
Include new enumeration functionality under `Microsoft.IO.FileSystem` assembly/namespace. Follow up after 2.1 implementation is complete. See #25873.

Ideally can create a .NET Standard assembly here. Will have to reference System.Memory.

**Comment by stephentoub** [comment]
@JeremyKuhne, can this be closed?

**Comment by JeremyKuhne** [comment]
Yeah, I actually did this. #31679
