### ISSUE TITLE
System.Data.SQLClient does not pass Store certification

### ISSUE THREAD

**Issue by Martin-Stein** [dotnet/corefx#26847]
Hello,

I have a Store-App that consumes System.Data.SQlClient. it works so far, but when I want to upload it to the store, the Windows App Cert Kit produced Errors:

Windows Security check:
Error in Datei C:\Program Files\windowsapps\martinstein.sql-dbdesigner_1.1.2.0_x64__9g9f70q8w59qy\sni.dll at  AppContainerCheck.

Test of supported APIs:
API _mbschr in api-ms-win-crt-multibyte-l1-1-0.dll is not supported for this App-Type. sni.dll calls this API
◦ API _mbsnbicmp_l in api-ms-win-crt-multibytel1-
1-0.dll is not supported for this App-Type. sni.dll calls this API
◦ API _mbsspn in api-ms-win-crt-multibyte-l1-
1-0.dll is not supported for this App-Type. sni.dll calls this API
◦ API IsTokenRestricted in advapi32.dll .......

How can I fix this issues? 
I have opened a case at MS Support, but they don't feel responsible!

Kind regards,

Martin

**Comment by joshfree** [comment]
which version of Microsoft.NETCore.UniversalWindowsPlatform are you targeting?

https://github.com/Microsoft/dotnet/tree/master/releases/UWP

**Comment by Martin-Stein** [comment]
Hi Josh,

 

I am using Version 6.0.6 of the platform, it’s the latest one.

 

Thanks I advance,

 

 

Martin

 

Von: Josh Free [mailto:notifications@github.com] 
Gesendet: Montag, 5. Februar 2018 19:08
An: dotnet/corefx <corefx@noreply.github.com>
Cc: Martin-Stein <mytrainer@freenet.de>; Author <author@noreply.github.com>
Betreff: Re: [dotnet/corefx] System.Data.SQLClient does not pass Store certification (#26847)

 

which version of Microsoft.NETCore.UniversalWindowsPlatform are you targeting?

https://github.com/Microsoft/dotnet/tree/master/releases/UWP

**Comment by Martin-Stein** [comment]
Hi Josh,

 

updating to version 6.0.7. of Microsoft.NETCore.UniversalWindowsPlatform did not solve the problem.

 

A view minutes ago I have update the nuGet package of System.Data.SQClient to the preview version 4.5.0-preview1-26216-02.

 

This ends in following compiler errors:

 

1>C:\Users\marti\.nuget\packages\microsoft.net.native.compiler\2.0.3\tools\Microsoft.NetNative.targets(731,5): warning :       MCG : warning MCG0007: Unresolved P/Invoke method 'api-ms-win-core-registry-l1-1-0.dll!RegCloseKey' for method 'System.Int32 Interop.mincore.RegCloseKey(System.IntPtr)'. Calling this method would throw exception at runtime. Please make sure the P/Invoke either points to a Windows API allowed in UWP applications, or a native DLL that is part of the package. If for some reason your P/Invoke does not satisfy those requirements, please use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP APIs.

1>C:\Users\marti\.nuget\packages\microsoft.net.native.compiler\2.0.3\tools\Microsoft.NetNative.targets(731,5): warning :       MCG : warning MCG0007: Unresolved P/Invoke method 'api-ms-win-core-registry-l1-1-0.dll!RegQueryValueExW' for method 'System.Int32 Interop.mincore.RegQueryValueEx(Microsoft.Win32.SafeHandles.SafeRegistryHandle, System.String, System.Int32[], System.Int32, System.Byte[], System.Int32)'. Calling this method would throw exception at runtime. Please make sure the P/Invoke either points to a Windows API allowed in UWP applications, or a native DLL that is part of the package. If for some reason your P/Invoke does not satisfy those requirements, please use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP APIs.

1>C:\Users\marti\.nuget\packages\microsoft.net.native.compiler\2.0.3\tools\Microsoft.NetNative.targets(731,5): warning :       MCG : warning MCG0007: Unresolved P/Invoke method 'api-ms-win-core-registry-l1-1-0.dll!RegEnumKeyExW' for method 'System.Int32 Interop.mincore.RegEnumKeyEx(Microsoft.Win32.SafeHandles.SafeRegistryHandle, System.Int32, System.Char*, System.Int32, System.Int32[], System.Text.StringBuilder, System.Int32[], System.Int64[])'. Calling this method would throw exception at runtime. Please make sure the P/Invoke either points to a Windows API allowed in UWP applications, or a native DLL that is part of the package. If for some reason your P/Invoke does not satisfy those requirements, please use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP APIs.

1>C:\Users\marti\.nuget\packages\microsoft.net.native.compiler\2.0.3\tools\Microsoft.NetNative.targets(731,5): warning :       MCG : warning MCG0007: Unresolved P/Invoke method 'api-ms-win-core-registry-l1-1-0.dll!RegQueryValueExW' for method 'System.Int32 Interop.mincore.RegQueryValueEx(Microsoft.Win32.SafeHandles.SafeRegistryHandle, System.String, System.Int32[], System.Int32, System.Int64, System.Int32)'. Calling this method would throw exception at runtime. Please make sure the P/Invoke either points to a Windows API allowed in UWP applications, or a native DLL that is part of the package. If for some reason your P/Invoke does not satisfy those requirements, please use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP APIs.

1>C:\Users\marti\.nuget\packages\microsoft.net.native.compiler\2.0.3\tools\Microsoft.NetNative.targets(731,5): warning :       MCG : warning MCG0007: Unresolved P/Invoke method 'api-ms-win-core-registry-l1-1-0.dll!RegQueryValueExW' for method 'System.Int32 Interop.mincore.RegQueryValueEx(Microsoft.Win32.SafeHandles.SafeRegistryHandle, System.String, System.Int32[], System.Int32, System.Int32, System.Int32)'. Calling this method would throw exception at runtime. Please make sure the P/Invoke either points to a Windows API allowed in UWP applications, or a native DLL that is part of the package. If for some reason your P/Invoke does not satisfy those requirements, please use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP APIs.

1>C:\Users\marti\.nuget\packages\microsoft.net.native.compiler\2.0.3\tools\Microsoft.NetNative.targets(731,5): warning :       MCG : warning MCG0007: Unresolved P/Invoke method 'api-ms-win-core-registry-l1-1-0.dll!RegQueryValueExW' for method 'System.Int32 Interop.mincore.RegQueryValueEx(Microsoft.Win32.SafeHandles.SafeRegistryHandle, System.String, System.Int32[], System.Int32, System.Char[], System.Int32)'. Calling this method would throw exception at runtime. Please make sure the P/Invoke either points to a Windows API allowed in UWP applications, or a native DLL that is part of the package. If for some reason your P/Invoke does not satisfy those requirements, please use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP APIs.

1>C:\Users\marti\.nuget\packages\microsoft.net.native.compiler\2.0.3\tools\Microsoft.NetNative.targets(731,5): warning :       MCG : warning MCG0007: Unresolved P/Invoke method 'api-ms-win-core-registry-l1-1-0.dll!RegOpenKeyExW' for method 'System.Int32 Interop.mincore.RegOpenKeyEx(Microsoft.Win32.SafeHandles.SafeRegistryHandle, System.String, System.Int32, System.Int32, Microsoft.Win32.SafeHandles.SafeRegistryHandle)'. Calling this method would throw exception at runtime. Please make sure the P/Invoke either points to a Windows API allowed in UWP applications, or a native DLL that is part of the package. If for some reason your P/Invoke does not satisfy those requirements, please use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP APIs.

1>C:\Users\marti\.nuget\packages\microsoft.net.native.compiler\2.0.3\tools\Microsoft.NetNative.targets(731,5): warning :       MCG : warning MCG0007: Unresolved P/Invoke method 'api-ms-win-core-registry-l1-1-0.dll!RegQueryInfoKeyW' for method 'System.Int32 Interop.mincore.RegQueryInfoKey(Microsoft.Win32.SafeHandles.SafeRegistryHandle, System.Text.StringBuilder, System.Int32[], System.IntPtr, System.Int32, System.Int32[], System.Int32[], System.Int32, System.Int32[], System.Int32[], System.Int32[], System.Int32[])'. Calling this method would throw exception at runtime. Please make sure the P/Invoke either points to a Windows API allowed in UWP applications, or a native DLL that is part of the package. If for some reason your P/Invoke does not satisfy those requirements, please use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP APIs.

 

 

 

Kind regards,

 

 

 

Martin Stein

 

 

Von: Martin Stein <martin-stein@freenet.de> 
Gesendet: Montag, 5. Februar 2018 19:54
An: 'dotnet/corefx' <reply@reply.github.com>; 'dotnet/corefx' <corefx@noreply.github.com>
Cc: 'Martin-Stein' <mytrainer@freenet.de>; 'Author' <author@noreply.github.com>
Betreff: AW: [dotnet/corefx] System.Data.SQLClient does not pass Store certification (#26847)

 

Hi Josh,

 

I am using Version 6.0.6 of the platform, it’s the latest one.

 

Thanks I advance,

 

 

Martin

 

Von: Josh Free [mailto:notifications@github.com] 
Gesendet: Montag, 5. Februar 2018 19:08
An: dotnet/corefx <corefx@noreply.github.com <mailto:corefx@noreply.github.com> >
Cc: Martin-Stein <mytrainer@freenet.de <mailto:mytrainer@freenet.de> >; Author <author@noreply.github.com <mailto:author@noreply.github.com> >
Betreff: Re: [dotnet/corefx] System.Data.SQLClient does not pass Store certification (#26847)

 

which version of Microsoft.NETCore.UniversalWindowsPlatform are you targeting?

https://github.com/Microsoft/dotnet/tree/master/releases/UWP

**Comment by Martin-Stein** [comment]
the latest Version solves this issue, Apps can now pass the certification process!
