### ISSUE TITLE
RSAOpenSSL.SignHash/VerifyHash doesn't support padding mode RSASignaturePadding.Pss

### ISSUE THREAD

**Issue by mregen** [dotnet/corefx#26849]
Hi, any plans to support `RSASignaturePadding.Pss`?
I noticed its all forbidden on Linux (haven't checked on iOS), but works on Windows.
OPC UA implements a new security policy which requires the PSS scheme. 
http://opcfoundation.org/UA/SecurityPolicy#Aes256_Sha256_RsaPss

snip...
```
        public override byte[] SignHash(byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
        {
           ...
            if (padding != RSASignaturePadding.Pkcs1)
                throw PaddingModeNotSupported();

            return SignHash(hash, hashAlgorithm);
        }
```

**Comment by bartonjs** [comment]
Duplicate of https://github.com/dotnet/corefx/issues/2522
