### ISSUE TITLE
FSW tests don't verify path information

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#2684]
The tests are only checking that events are occurring, but not that they're for the right/expected paths.

**Comment by sokket** [comment]
Looking into this, there are some issues here that need some thought: The OS X FSW has a nasty tendency to add the 'Created' flag onto events multiple times after the original Created event...this has to be worked through first otherwise our test path validation fails

**Comment by stephentoub** [comment]
@joshfree, this is marked as 1.1.0, but I think it needs to be 1.0.0-rtm; we've already found a couple of issues where the path was wrong, but only haphazardly as we don't have tests to verify it.
