### ISSUE TITLE
PlatformNotSupportedException with TcpClient.ConnectAsync

### ISSUE THREAD

**Issue by cocowalla** [dotnet/corefx#26840]
I'm getting `PlatformNotSupportedException` on Linux when calling `TcpClient.ConnectAsync(host, port)`, with a rather unhelpful message: `Sockets on this platform are invalid for use after a failed connection attempt` (I'm not trying to reuse a socket)

This is only happening under specific circumstances:

1. `host` is a hostname, such as "localhost", AND
2. KeepAlive is enabled using `tcpClient.Client.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.KeepAlive, true)`

Everything works fine if I change either one of these things.

I did a search and came across issues #5829 and #8768, which led to PR #16373 - so it seems like you are supposed to be able to connect using a hostname, it's just not working when keep alives are enabled.

**Comment by karelz** [comment]
cc @tmds @stephentoub

**Comment by stephentoub** [comment]
> it's just not working when keep alives are enabled

We don't track every possible setting that could be changed on a socket.  That is a fairly unbounded list, and doing so would mean that every time any setting is made on a socket, we'd have to track that data, even though it would only be used when recreating the socket on retries.  That data also can come in a variety of forms, including as mutable data that can be changed after it's passed to SetSocketOption and before a connect attempt is made, which makes it even more expensive (e.g. lots of allocation).

The compromise we arrived at to bridge the gap between the .NET API (which use instance Connect{Async} methods and thus need to support reconnection attempts on the same Socket for when multiple addresses are/could be used) and the POSIX APIs (which explicitly have such reuse as undefined behavior) was that we would track the most prominent settings, e.g. the ones exposed as properties on Socket.  If you change those, we track that.  If you change other settings, we don't.  If if you change untracked settings, we prevent you from making Connect{Async} calls that could result in multiple addresses being used, i.e. either a string host that could resolve in multiple DNS results or an array of addresses.

As a workaround, you can use an IPAddress and it should work fine, e.g. do the Dns call yourself, pick which IPAddress you want, and call ConnectAsync with that.  That should work fine with KeepAlive.

We can also extend the list of settings supported, it's just difficult to pick the right line to draw.

**Comment by cocowalla** [comment]
Wow, 20 minutes from opening to a comprehensive response, and on a Sunday - I'm impressed!

Yes, I think I'll just use `Dns.GetHostAddresses` to get the IP.

I get what you mean about the cornucopia of socket options, although I would have though keep alives was one of the more used ones (not very scientific, but a quick GitHub search finds > 3k uses).

**Comment by cnblogs-dudu** [comment]
Encountered the same issue in .net core 2.1.

**Comment by karelz** [comment]
@cnblogs-dudu is the response above (https://github.com/dotnet/corefx/issues/26840#issuecomment-362938031) reasonable workaround?
