### ISSUE TITLE
Why Linq.Skip is O(n) for lists?

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/corefx#26852]
It seems that Skip is implemented poorly here. it should check if source is `IList<T>` and skip in O(1) time (like the way linq does for `Count`, `ElementAt` and `Last`).

http://referencesource.microsoft.com/#System.Core/System/Linq/Enumerable.cs,90ccdbd47b57182e,references

Am I looking at old reference?

**Comment by stephentoub** [comment]
You're looking at the .NET Framework source.  This repo is for .NET Core, where the implementation has been substantially changed:
https://source.dot.net/#System.Linq/System/Linq/Skip.cs,12

**Comment by MkazemAkhgary** [comment]
Oh, thanks for the answer. my bad.
