### ISSUE TITLE
Fail to load type if the type has attribute to `ComImport` on Ubuntu/Mac/Docker container

### ISSUE THREAD

**Issue by smadala** [dotnet/corefx#26851]
### Description:
 Fail to load type if the type has attribute to `ComImport` on Ubuntu/Mac/Docker container.

### Repro Steps:
- git clone https://github.com/smadala/samples
- cd samples/ComImportIssue/consoleapp
- dotnet run

This works fine on windows.

### Expected Output:
```
Hello World!
nslib.ClassFactory
```
### Actual Output:
```
Hello World!

Unhandled Exception: System.TypeLoadException: Could not load type 'nslib.ClassFactory' from assembly 'nslib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at consoleapp.Program.Test1()
   at consoleapp.Program.Main(String[] args) in /home/satya/Downloads/TestIssue/consoleapp/Program.cs:line 15
```
### Background:
In [vstest](https://github.com/Microsoft/vstest) we are using [`ComImport`](https://github.com/Microsoft/vstest/blob/347c59f73943921786bf9d5a7e42d2cf011ddd15/src/Microsoft.TestPlatform.ObjectModel/Navigation/NativeMethods.cs#L547
) to PInvoke [msdia](https://msdn.microsoft.com/en-us/library/t6tay6cz.aspx) API to get line numbers of functions for netstandard1.4. This causing issue like https://github.com/Microsoft/testfx/issues/341.

/cc: @mayankbansal018

**Comment by jkotas** [comment]
You are trying to use COM interop on Unix. COM interop on Unix is not supported. (msdia.dll does not exist on Unix either.)

**Comment by mayankbansal018** [comment]
@jkotas , we are not trying to using COM interop on Unix. Our question is that if an assembly compiled for netstandard1.4 uses COM interop, & if on such an assembly we use GetAllTypes API on Unix, should it fail?
I can see that ComInterop attribute is defined in System.Private.CoreLib.dll for unix netcore, but getting it's Type is failing.

**Comment by jkotas** [comment]
Yes, it is expected to fail today. Here is the relevant check that makes it fail: https://github.com/dotnet/coreclr/blob/ad71e93f91b6091454bb533c645c68dd9dc3276f/src/vm/methodtablebuilder.cpp#L3108

Not sure what it would take it to not fail. Either way, the type will be non-instantiateable.

**Comment by mayankbansal018** [comment]
@jkotas We are completely okay if the type is non-instantiatable, but using reflection to get types should be allowed on such object.
Please refer [bug here](https://github.com/Microsoft/vstest/issues/1417).

**Comment by sidshetye** [comment]
This is also an issue with Apache Avro's C# libraries during deserialization. Tests fail on Linux/Mac due to `Assembly.GetTypes()` [see here](https://github.com/apache/avro/blob/master/lang/csharp/src/apache/main/Specific/ObjectCreator.cs#L145). Like @mayankbansal018 says, at the very least reflection should be permitted and should be non-fatal on *nix.

**Comment by jkotas** [comment]
This issue was moved to dotnet/coreclr#16804
