### ISSUE TITLE
System.Net.NameResolution: remove old GetHostByName logic

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#26856]
See comment here: https://github.com/dotnet/corefx/blob/a3e4e241c7b7c33750258082969287b9cf45d757/src/System.Net.NameResolution/src/System/Net/DNS.cs#L67

This comment is ancient.  There should be no reason not to use GetAddrInfo today.  We should remove the unnecessary fallback codepath here.

**Comment by karelz** [comment]
Should be fairly straightforward to do.

**Comment by karelz** [comment]
@MarcoRossignoli thanks for your contribution! I sent you collaborator invite - that will allow us to assign the issue to you (GH limitation). Ping me once you accept and I will assign it to you (temporarily assigning to myself).
Note: Once you accept the invite, you will be auto-subscribed to all-repo notifications (500+ per day). We recommend to switch to "Not Watching" - i.e. you will get notifications only upon mentions & when subscribed to issues.

**Comment by MarcoRossignoli** [comment]
@karelz done!
