### ISSUE TITLE
Questions and suggestions about the Plane Structure

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/corefx#26860]
```
var p1 = new Plane(1, 1, 1, 4);
var p2 = Plane.Normalize(p1);
Console.WriteLine(p1 == p2); //False
```
Normal and D are different in p1 and p2, so == returns false.
Are p1, p2 different planes or the same plane?
And if d1 and d2 are identical but with different D values. Doesn't this say loudly that D is not the distance?
 Abs(D) is the distance if and only if Normal is the normalized vector. You can refer to the low for the distance of a point from a plane to calculate the distance of the origin.
A small test, I'll take a point and calculate its distance from the p1 and p2 planes:
```
var p1 = new Plane(1, 1, 1, 4);
var p2 = Plane.Normalize(p1);
var point = new Vector3(5, 6, 7);
var distanceFromP1 = (Vector3.Dot(point, p1.Normal) + p1.D)/ p1.Normal.Length();
var distanceFromP2 = (Vector3.Dot(point, p2.Normal) + p2.D)/ p2.Normal.Length();
```
The distance in both cases is 12.7017059.
P1 and p2 are defiantly the same plane.

 So, I suggest:
1. The Equals method of the Vector3 and other vectors should normalize both vectors before comparing them. Same is for the Equal method for the Plane.
You can compromise by adding a new
 Plane.Equals(Plane other, bool MathematicallyEquals)
 method overload that normalizes both planes before comparing them.
 This at least will alert the user to the difference.

2. float comparisons should use the MathF.Round to avoid floating points errors. Otherwise there methods are useless, and we had to re-write them manually in each use. Why writing code with no practical usage, while it can be perfected?
The source code already uses FLT_EPSILON in some comparisons.
const float FLT_EPSILON = 1.192092896e-07f; // smallest such that 1.0+FLT_EPSILON != 1.0

3. Xml comments and documentation must correct the definition for D. I was totally misguided because saying it's the distance, and negative D values made me crazy. D is the coefficient of the plain equation, its magnitude can be the distance if the normal is normalized, and its sign came from it's location on the two sides of the plane. We wastes a lot of time in my previous issue because this inaccuracy.

4. it will be nice if you add a Plane.DistanceOfPoint method. The DotCoordinate method retuns the distance, only if the plane is normalized.

5. it will be helpfull to add this Method to the plane struct (and a similar one to the Vector struct). The code is based on the source code of the Normalize method:
public static bool IsNormalized(Plane value)
{
   const float FLT_EPSILON = 1.192092896e-07f; // smallest such that 1.0+FLT_EPSILON != 1.0 
   float normalLengthSquared = value.Normal.LengthSquared();
   return MathF.Abs(normalLengthSquared - 1.0f) < FLT_EPSILON;                
}

6.  I wonder what is the design goal behind making almost all vector and plane methods static?
 This makes code verbose without a purpose!
 If I have two vector3 instances named a and b, why write:
var c = Vector3.Normalize(Vector3.Reflect(a, Vector3.Abs(a)));
 while it's shorter and easier to understand to write:
var c = a.Reflect(b.Abs( )).Normalize( );
 And why is Length is a method not a property?

**Comment by mikedn** [comment]
> Are p1, p2 different planes or the same plane?

It's the same plane (within the limits of floating point precision, of course).

**Comment by tannergooding** [comment]
@MohammadHamdyGhanem, these are the same plane, but within different spaces.

`p1` is a plane that exists in regular vector space.
`p2` is a plane that exists in normed vector space.

They represent the same plane in normed vector space, but different planes in non-normalized vector space.

**Comment by tannergooding** [comment]
Two vectors are only equal if they have the same magnitude and direction.

The normal vector for p1 has a magnitude of `~1.732051`
The normal vector for p2 has a magnitude of  `1`

As such, these represent different vectors and, therefore, different planes (`D` is also different, since it underwent normalization as well).

You would have to normalize both `p1` and `p2` and compare them if you wanted to ensure they represented the same plane in normed vector space.

**Comment by Clockwork-Muse** [comment]
...although since `==` directly compares float values, the answer may not always yield what you expect.

**Comment by tannergooding** [comment]
@Clockwork-Muse, yes, there are the odd cases where you perform two mathematically equivalent operations that result in different floating-point results and would cause them to compare inequal, but this isn't one of those cases.

Because the OP is only normalizing one of the planes, they are effectively doing the following:
```C#
var p1 = new Plane(1, 1, 1, 4);
var p2 = new Plane(0.577350259f, 0.577350259f, 0.577350259f, 2.30940104f);
Console.WriteLine(p1 == p2);
```

If they had normalized both planes, and therefore put them both in normed vector space, the result would be as expected.

**Comment by mikedn** [comment]
> p1 is a plane that exists in regular vector space.
> p2 is a plane that exists in normed vector space.

Normed vector space means vector space that has a "norm" function. It doesn't mean that all vectors are normalized. I have no idea what "regular vector space" is supposed to be. Presumably a vector space without a norm, something that the Euclidean space surely has.

**Comment by tannergooding** [comment]
Sorry if I used some "incorrect" terminology. The point, however, remains that `∥v∥ != v`.

**Comment by MohammadHamdyGhanem** [comment]
So, p1 and p2 refere two the same plane in math, but not in programming?
Does this feel right to you?
And if d1 and d2 are identical but with different D values. Doesn't this say loudly that D is not the distance?
Abs(D) is the distance if and only if Normal is the normalized vector. You can refer to the low for the distance of a point from a plane to calculate the distance of the origin. 
So, there are there points here:
1- The Equals method of the Vector3 and other vectors should normalize both vectors before comparing them. Same is for the Equal method for the Plane.
2- float comparisons should use the MathF.Round to avoid floating points errors. Otherwise there methods are useless, and we had to re-write them manually in each use. Why writing code with no practical usage, while it can be perfected?
3- Xml comments and documentation must correct the definition for D. I was totally misguided because saying it's the distance, and negative D values made me crazy. D is the coefficient of the plain equation, its magnitude can be the distance if the normal is normalized, and its sign came from it's location on the two sides of the plane. We wastes a lot of time in my previous issue because this inaccuracy.
Thanks.

**Comment by MohammadHamdyGhanem** [comment]
@joshfree 
Hope you mark this issue as a bug and a proposal. I put it as a question to get a clear idea about what the implemetes mean.

**Comment by tannergooding** [comment]
> So, p1 and p2 refere two the same plane in math, but not in programming?

No, even in math `∥v∥ != v`.

> The Equals method of the Vector3 and other vectors should normalize both vectors before comparing them. Same is for the Equal method for the Plane.

No, if I have two unormalized vectors `1, 1, 1` and `0.577350259f, 0.577350259f, 0.577350259f`, this would incorrectly return true.

>  float comparisons should use the MathF.Round to avoid floating points errors. Otherwise there methods are useless, and we had to re-write them manually in each use. Why writing code with no practical usage, while it can be perfected?

It is up to the user to determine when rounding is required. It varies from application to application, the operations used, and the rounding mode enabled.

**Comment by mikedn** [comment]
> The Equals method of the Vector3 and other vectors should normalize both vectors before comparing them. Same is for the Equal method for the Plane.

Why? The Equals method simply tells that 2 plane numeric representations are equal or not. It doesn't tell you that they represent the same plane. The fact that some geometric concepts such as plane and lines happen to have an infinity of numeric representations is another story.

Besides, normal vectors are expected to be normalized. I'm pretty sure I told you that already.

> float comparisons should use the MathF.Round to avoid floating points errors. Otherwise there methods are useless, and we had to re-write them manually in each use.

What would probably be useful would be an Equals overload that allows you to specify some an acceptable error. The "standard" `Equals` method can not and should not do such a thing. If only because it will mess up `GetHashCode`.

> Xml comments and documentation must correct the definition for D

Everyone refers to that as distance from the plane to origin. And it is the distance if you use normalized normal vectors as you're supposed to. If you're' not calling it distance what do you call it? Some abstract number "D"? That's less useful.

**Comment by mikedn** [comment]
> No, even in math ∥v∥ != v.

That does not make any sense. ||v|| is a scalar. v is a vector. The 2 are not comparable.

**Comment by tannergooding** [comment]
> That does not make any sense. ||v|| is a scalar. v is a vector. The 2 are not comparable.

`∥v∥` is standard notation for indicating a vector is normalized.

**Comment by tannergooding** [comment]
Some places, like Wolfram Alpha, commonly use single pipes for indicating it as well: `|X|`

**Comment by mikedn** [comment]
> ∥v∥ is standard notation for indicating a vector is normalized.

Both |x| and the more or less common ||x|| denote the norm of the vector x. That is, the magnitude or length of the vector, a completely different thing from a normalized vector. AFAIR normalized vectors are denoted by a hat.

**Comment by tannergooding** [comment]
You're right. My memory is apparently going faulty.

**Comment by MohammadHamdyGhanem** [comment]
No, even in math ∥v∥ != v.

**Comment by MohammadHamdyGhanem** [comment]
@tannergooding 
> No, even in math ∥v∥ != v.
I don't believe taht. You normailze the plane by deviding the normal an D by the normal.Length. This mean it's the same equation, but refactored. So, the two planes are the same, having the same direction, and containing the same points.

**Comment by MohammadHamdyGhanem** [comment]
A small test, I'll  take a point and calculate its distance from the p1 and p2 planes:
```
var p1 = new Plane(1, 1, 1, 4);
var p2 = Plane.Normalize(p1);

var point = new Vector3(5, 6, 7);
var distanceFromP1 = (Vector3.Dot(point, p1.Normal) + p1.D)/ p1.Normal.Length();
var distanceFromP2 = (Vector3.Dot(point, p2.Normal) + p2.D)/ p2.Normal.Length();

```
The distance in both cases is 12.7017059.
P1 and p2 are defiantly the same plane.

**Comment by mikedn** [comment]
> By the way, it will be nice if you add a Plane.DistanceOfPoint method.

It already exists, it's called `DotCoordinate`.

**Comment by MohammadHamdyGhanem** [comment]
> It already exists, it's called DotCoordinate.
Sorry. I saw the name, but didn't understand it! :)

You can compromise by adding a new 
Plane.Equals(Plane other, bool MathematicallyEquals) 
method overload that normalizes both planes before comparing them.
This at least will alert the user to the difference.

About the float problem:
These are specialized types, not for scientific calculations. 
The source code already uses FLT_EPSILON in some comparisons. 
`const float FLT_EPSILON = 1.192092896e-07f; // smallest such that 1.0+FLT_EPSILON != 1.0`
I think you need to give these types some more time, before building any more types upon them.
Thanks

**Comment by MohammadHamdyGhanem** [comment]
And I think this is the time to ask:
I wonder what is the design goal behind making almost all vector methods static?
This makes code verbose without a purpose!
If I have two vector3 instances named a and b, why write:
`var c = Vector3.Normalize(Vector3.Reflect(a, Vector3.Abs(a)));`
while it's shorter and easier to understand to write:
`var c = a.Reflect(b.Abs( )).Normalize( );`

**Comment by tannergooding** [comment]
Most of the API conventions can be boiled down to this document: https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/

> These are specialized types, not for scientific calculations.

We have stated that they are not general-purpose types several times. This is not a library similar to BLAS. Instead it is a small, targeted, vector math library that is interopable with many of the vector math libraries used in Graphical Applications (which tend to aim for speed over precision).

> I think you need to give these types some more time, before building any more types upon them.

These types, the general shape of the APIs exposed, and their algorithms are already very mature. They are based on and behave similarly/identically to many other libraries (such as the DirectX Math Library, or the Unity Math Library).

**Comment by MohammadHamdyGhanem** [comment]
1- DotCoordinate is not the distance.  it returns the dot product of a specified three-dimensional vector and the normal vector of this plane plus the D value of the plane. So, 
Distance = DotCoordinate / Normal.Length
So, a distance method is still nice and easy to understand.

2- DirectX is not a standerd for high level languages. Its difficult to use and if you simulate any of it you should conseder the standerds of C# not DirectX. This is done In GDI and WPF. So, "others do it like this" is not an answer to my points!

3. In graphics does it help to conseder 2 identical planes different planes? Does a game player have a different outcome from p1 and p2?
The concept doesn't change whatever the usage. And I already gave you a comprimise by overloading the equals method.

4. You're guidlines are good but you should listen to our feedback. Programmers workarround your guidlines and implementaions a lot, and this is not a happy thing to do. "Is working" doesn't mean "is perfect". I can solve all these issues myself, as done hunderes of times, or write my own implementaions. I gave you a feedback becuase I care about my favourite programming languages. Microsoft is allready behind in many areas, and it will be a disaster for me to had to learn a new programming plateform in this age!
So, just hear, and do whatever you want!
Thanks.

**Comment by mikedn** [comment]
> DotCoordinate is not the distance. it returns the dot product of a specified three-dimensional vector and the normal vector of this plane plus the D value of the plane.

For a billionth time - it all works if the normal vector is normalized. If it's not then you'd better know what you are doing.

I won't comment about the rest of your points, it's becoming a waste of time. You don't understand vector math and instead of trying to learn it (and I mean learning it by reading relevant materials and not by trial and error in C#) you blame the docs, the framework, the people. It's unlikely that you'll go far using this approach.

**Comment by MohammadHamdyGhanem** [comment]
> For a billionth time - it all works if the normal vector is normalized.

**Comment by MohammadHamdyGhanem** [comment]
> For a billionth time - it all works if the normal vector is normalized.
This is not a rule in teh Plane structure anywhere, otherwise why it has a normalize method?
I asked before to normalize the plane in its constructor, and you rejected this idea!

Sure I understand vectors and planes, read about them, and use the plane equation in c# code to prove my point in previous replys if you didn't notice!

No need for more words.
Thanks.

**Comment by MohammadHamdyGhanem** [comment]
By the way, it will be helpfull to add this Method to the vector and plane structs. The code is based on the source code of the Normalize method:

```
       public static bool IsNormalized(Plane value)
        {
            const float FLT_EPSILON = 1.192092896e-07f; // smallest such that 1.0+FLT_EPSILON != 1.0 
            float normalLengthSquared = value.Normal.LengthSquared();
            return MathF.Abs(normalLengthSquared - 1.0f) < FLT_EPSILON);                
        }
```

**Comment by eerhardt** [comment]
I believe all the questions were answered in this issue.

w.r.t. adding `IsNormalized` and `Plane.Equals(Plane other, bool MathematicallyEquals)`, I don't see these new methods adding value over the existing functionality.  Therefore, I'm going to close this issue.

If you feel strongly these new methods should be considered, please follow the https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md on this issue, or open a separate issue.  It can be reconsidered if there is a common need and supporting scenarios for these functions.
