### ISSUE TITLE
Console.WriteLine broken on OS X

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#2686]
Using the latest build (Aug 7 build).

Darwin, x86

```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.IO.StreamWriter..ctor(Stream stream, Encoding encoding, Int32 bufferSize, Boolean leaveOpen)
   at System.Console.CreateOutputWriter(Stream outputStream)
   at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
   at System.Console.Write(String format, Object[] arg)
```

**Comment by natemcmaster** [comment]
The call that causes this error looks like this: each of the arguments is a StringBuilder. From
```c#
Console.Write("{0}{1}{2}{3}{4}", nameAndVersion, headerBuilder, argumentsBuilder, optionsBuilder, commandsBuilder);
```

[See the source: CommandLineApplication.cs#L407](https://github.com/aspnet/dnx/blob/7e6abf75be91658aae00699d95faac87ece6ad23/src/Microsoft.Framework.CommandLineUtils.Sources/CommandLine/CommandLineApplication.cs#L407)

**Comment by stephentoub** [comment]
@nguerrera, you assigned this to yourself.  I assume you think the problem is in the new shims?

@natemcmaster, are you able to consistently repro this, and do so in a small repro app separate from CommandLineApplication?

**Comment by nguerrera** [comment]
@stephentoub yes, that was a gut reaction, but looking at the stack, I'm not so sure.

**Comment by nguerrera** [comment]
@stephentoub It got as far as StreamWriter.ctor which is in mscorlib IIRC. On my phone now, but was going to kick the tires on my Mac later tonight. If you have more insight, feel free to grab this from me.:)

**Comment by natemcmaster** [comment]
https://gist.github.com/natemcmaster/e0d1ddfdd06abd281061

Note: the latest build (20150807_08014918) still looks for System.IO.Native.dylib, but the build produces System.Native.dylib

**Comment by nguerrera** [comment]
That's odd. Could be something about how that drop got produced. cc @chcosta. I'll triple check local build wouldn't do that.

**Comment by nguerrera** [comment]
@natemcmaster how did you ascertain that?

**Comment by natemcmaster** [comment]
When just coping the drop, on first run it throws. I just renamed to System.Native.dylib

>    Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'System.IO.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.NativeIO.FStat(Int32 fileDescriptor, FileStats& output)
   at System.ConsolePal.UnixConsoleStream..ctor(String devPath, FileAccess access)

**Comment by BrennanConroy** [comment]
That's because we aren't using the latest CoreCLR drop in dnx so we are still on the System.IO.Native version of CoreCLR

**Comment by natemcmaster** [comment]
Side note: @BrennanConroy [this repro](https://gist.github.com/natemcmaster/e0d1ddfdd06abd281061) doesn't even use dnx, just for the clarification.

**Comment by nguerrera** [comment]
Hmm, there's a mismatch somewhere. CoreCLR doesn't use System.IO.Native or System.Native at all. It feels like bits from different corefx builds got mixed together.

**Comment by nguerrera** [comment]
I'm trying to run the repo on a local build right now.

**Comment by nguerrera** [comment]
https://gist.github.com/natemcmaster/e0d1ddfdd06abd281061 doesn't look like it;s building against System.Console.dll contract.

**Comment by natemcmaster** [comment]
¯\\\_(ツ)_/¯
I guess that means DNX is also using the wrong contract? The repro still produces the same error in StreamWriter thought.

**Comment by nguerrera** [comment]
Not building against the contract isn't the issue, the repro should still succeed when compiling against the  Mac implementation assemblies. Indeed, with my own private build, it does:

```
$ ./corerun repro/Program.exe 
Hello, OS X
Love from CoreCLR. 
```

I think the drop you got was suspect if it still had refs to System.IO.Native. Is there a newer build you can try? I'm out of town with no access to the internal network.

**Comment by nguerrera** [comment]
Hmm, I retried with a local release build of CoreCLR and got a different issue. Investigating.

```
$ ./corerun Program.exe 

Unhandled Exception: System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.ConsolePal.UnixConsoleStream..ctor(String devPath, FileAccess access)
   at System.ConsolePal.OpenStandardOutput()
   at System.Console.OpenStandardOutput()
   at System.Console.<>c.<get_Out>b__11_0()
   at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
   at System.Console.get_Out()
```

**Comment by rqadri133** [comment]
Please let me now how to unsubscribe .

On Fri, Aug 7, 2015 at 5:27 PM, Nate McMaster <notifications@github.com>
wrote:

> Using the latest build (Aug 7 build).
>
> Darwin, x86
>
> Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>    at System.IO.StreamWriter..ctor(Stream stream, Encoding encoding, Int32 bufferSize, Boolean leaveOpen)
>    at System.Console.CreateOutputWriter(Stream outputStream)
>    at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
>    at System.Console.Write(String format, Object[] arg)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dotnet/corefx/issues/2686>.
>



-- 






*Rafi QadriSoftware Engineer240-330-7827Email Security Code=00101*

**Comment by nguerrera** [comment]
OK, the issue above is unrelated, it was my mistake running with debug mscorlib and release libcoreclr. The layout of SafeHandle changes based on #if DEBUG so that just can't work.

I'm unable to repro the original issue.

**Comment by natemcmaster** [comment]
@nguerrera I just tried today's drop and it appears this issue has been resolved.
@rqadri133 For future reference: ![image](https://cloud.githubusercontent.com/assets/2696087/9176445/36d050f6-3f40-11e5-9b9f-393d181e0f89.png)
