### ISSUE TITLE
Test System.Threading.Tasks.Dataflow.Tests.EtwTests.TestEtw failed with "Exit code was 131 but it should have been 42\nExpected: True\nActual: False"

### ISSUE THREAD

**Issue by Sunny-pu** [dotnet/corefx#26887]
Failed test: System.Threading.Tasks.Dataflow.Tests.EtwTests.TestEtw
Configuration: Osx10.12_release
MESSAGE:
Exit code was 131 but it should have been 42\nExpected: True\nActual: False
~~~
STACK TRACE:
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 186
~~~
Details: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release/4258/testReport/System.Threading.Tasks.Dataflow.Tests/EtwTests/TestEtw/

**Comment by stephentoub** [comment]
The log shows:
```
A fatal error occurred, the folder [/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/bin/testhost/netcoreapp-OSX-Release-x64/shared/Microsoft.NETCore.App/9.9.9/host/fxr] does not exist
```
As @danmosemsft noted in https://github.com/dotnet/corefx/issues/25311#issuecomment-345412175, all such issues should be dup'd against https://github.com/dotnet/corefx/issues/25037.
