### ISSUE TITLE
It seems proxy address is never applied

### ISSUE THREAD

**Issue by ihorlazarenko** [dotnet/corefx#26892]
https://github.com/dotnet/corefx/blob/62e18e428a91293bda14ba287849f51a1f38bc51/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs#L687
Result of method is not applied and code is optimized. In my case WebProxy method is called https://github.com/dotnet/corefx/blob/master/src/System.Net.WebProxy/src/System/Net/WebProxy.cs#L87

**Comment by karelz** [comment]
Do you have a test case where it does not work.? Or did you just do code inspection?

The code you linked is just checking, the interface call won't throw.
The proxy is then used elsewhere:
https://github.com/dotnet/corefx/blob/62e18e428a91293bda14ba287849f51a1f38bc51/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs#L992

**Comment by ihorlazarenko** [comment]
Thank you for answer. Yes, I found usage, but anyway it is strange behavior to call GetSmth() without using it(Uri is readonly object)

**Comment by wfurt** [comment]
Make sure your site is not matching bypass list or hitting  local addresses processing. 
That should be easy to check with IE and wireshark.

**Comment by stephentoub** [comment]
Sounds like this can be closed. Please reopen if there's still an issue here.
