### ISSUE TITLE
ManagedHandler public API surface

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#26895]
For 2.1, we want to expose the new "ManagedHandler" we've been working on.  It's not "just the default" as it's missing some features (e.g. HTTP/2, various forms of auth like NTLM and Negotiate), so it needs to be opt-in.  We've allowed it to be opt-in on a process-wide level underneath HttpClientHandler, via an environment variable and via an AppContext setting, but we also want to expose the API so that a) developers can opt-in for specific uses rather than process-wide (e.g. we do this via a hack in ClientWebSocket, which runs on the managed handler now), and b) so that developers can control settings on it not available via HttpClientHandler.

Proposed surface area:
```C#
namespace System.Net.Http
{
    public sealed class NetSocketsHandler : HttpMessageHandler // new name for ManagedHandler
    {
        public NetSocketsHandler();

        // These are identical to those on HttpClientHandler:
        public bool AllowAutoRedirect { get; set; }
        public DecompressionMethods AutomaticDecompression { get; set; } // TODO: Also and Brotli to DecompressionMethods?
        public CookieContainer CookieContainer { get; set; }
        public ICredentials Credentials { get; set; }
        public ICredentials DefaultProxyCredentials { get; set; }
        protected override void Dispose(bool disposing);
        public int MaxAutomaticRedirections { get; set; }
        public int MaxConnectionsPerServer { get; set; }
        public int MaxResponseHeadersLength { get; set; }
        public bool PreAuthenticate { get; set; }
        public IDictionary<string, object> Properties { get; }
        public IWebProxy Proxy { get; set; }
        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken);
        public bool UseCookies { get; set; }
        public bool UseProxy { get; set; }

        // This replaces the following from HttpClientHandler, while enabling additional functionality:
        // - public bool CheckCertificateRevocationList { get; set; }
        // - public X509CertificateCollection ClientCertificates { get; set; }
        // - public ClientCertificateOption ClientCertificateOptions { get; set; }
        // - public Func<HttpRequestMessage, X509Certificate2, X509Chain, SslPolicyErrors, bool> ServerCertificateCustomValidationCallback { get; set; }
        // - public SslProtocols SslProtocols { get; set; }
        public SslClientAuthenticationOptions SslOptions { get; set; }

        // Others not on HttpClientHandler but on NetSocketsHandler
        public TimeSpan ConnectionTimeout { get; set; } // How long a connection can be alive to still be poolable; primarily used to help with DNS changes
        public TimeSpan ConnectionIdleTimeout { get; set; } // How long a pooled connection can be idle before it's disposed; primarily used for resource management

        // Others not currently in the plan but which we've discussed as potential knobs:
        public TimeSpan DnsRefreshTimeout { get; set; } // If we do our own DNS caching, how often to flush
        public bool EnableDnsRoundRobin { get; set; } // Whether to go in order of the DNS results or round-robin through them
        public bool UseNagleAlgorithm { get; set; } // We currently always disable it, but maybe someone would want to override that?
        public int MaxResponseDrainSize { get; set; } // We're implementing draining, and may want to allow control over how much is drained
        public TimeSpan MaxResponseDrainTimeout { get; set; } // We're implementing draining, and may want to allow control over how long we spend draining
    }
}
```

Current open issues:
- **Naming**, in particular for the class itself.  Most handlers describe what it is they're built on top of, hence the "sockets".  We could do "SocketsHandler", but there was some concern aired that everything is on sockets at some level (the counterargument is that this is the direct level targeted by this handler); the "Net" prefix was added as a way to suggest it's the System.Net.Sockets.
- **Assembly**.  The current plan is this ships in System.Net.Http.dll.  That will make it more difficult to make it available in the future downlevel.  But the API currently relies on .NET Core-specific types (e.g. SslClientAuthenticationOptions) and the implementation relies on internals of HttpClient for perf.  We also hope/expect it'll become the default in the future.
- **MaxResponseHeadersLength** unit.  HttpClientHandler defines it in kilobytes, which is inconsistent with most other sizes.  Should we break from that and expose it in bytes?

**Comment by stephentoub** [comment]
cc: @geoffkizer, @davidsh, @Priya91, @wfurt

**Comment by Tratcher** [comment]
SslClientAuthenticationOptions has a few settings that shouldn't be configured publicly. E.g. ApplicationProtocols, TargetHost. Is your plan to clone this Options object per connection and configure it accordingly? And just ignore/replace fields the user wasn't supposed to set?

**Comment by stephentoub** [comment]
> Is your plan to clone this Options object per connection and configure it accordingly?

Yes.  There's a PR out for this.

> And just ignore/replace fields the user wasn't supposed to set?

Currently the PR as it is allows ApplicationProtocols and TargetHost to be set.  ApplicationProtocols is just used as-is.  TargetHost is replaced by the actual hostname if the user didn't set anything.  But we can sort out the details here; we could choose to just ignore anything if desired; that's easy.

**Comment by karelz** [comment]
API review:
* `ClientCertifiationOptions` - we should make sure it works also in WinRT (Automatic option)
* We should try to design DNS caching object instead of having options directly on the class
* Rename `ConnectionTimeout` to `PooledConnectionLifetime`
* Rename `ConnectionIdleTimeout` to `PooledConnectionIdleTimeout`
* Class name: `SocketsHttpHandler` (4 preferred votes, no strong push back / preferred votes on alternatives)
* Assembly name: System.Net.Http (both implementation and reference) - we may need more discussion to think through OOBing on Desktop - that will likely be needed.

Discussion:
* Should we inherit from `HttpClientHandler`? - No
* `MaxResponseHeadersLength` - KB vs. B. (currently it is consistent with `HttpWebRequest`) - should we rename it to `MaxResponseHeadersLengthInKilobytes`? - No, just document it (nobody uses it)
* What if someone changes values later on? -- Do what we do on existing handlers - check as much as you can, document the rest. Goal: Consistency with existing handlers + think through new properties

**Comment by Tratcher** [comment]
RE: MaxResponseHeadersLength: When is .NET going to get a type for managing sizes similar to TimeSpan? E.g. FromMb, FromKb, FromBytes, etc.. I hate looking at properties and wondering what the units are. Putting the units in the name gets bulky.

**Comment by benaadams** [comment]
> When is .NET going to get a type for managing sizes similar to TimeSpan? 

Sounds like a good idea https://github.com/dotnet/corefx/issues/14234

**Comment by geoffkizer** [comment]
> We should try to design DNS caching object instead of having options directly on the class

Can you provide more info on this?  I'm not sure what a "DNS caching object" would look like.

**Comment by stephentoub** [comment]
> Can you provide more info on this? I'm not sure what a "DNS caching object" would look like.

@bartonjs raised the suggestion that if we ever decide to add things like client DNS round-robin, we do so with an API that encapsulates the logic and that others could share.  I'm assuming he was thinking of something along the lines of (this is not a real design):
```C#
public class DnsCache
{
    public ValueTask<IPAddress[]> GetHostAddressesAsync(string url);
    public TimeSpan RefreshTime { get; set; }
    public bool RoundRobin { get; }
}
```
Etc.  

But we're not going to do something like that now.
