### ISSUE TITLE
Add HID support to .netCore

### ISSUE THREAD

**Issue by juscla** [dotnet/corefx#26914]

**Comment by karelz** [comment]
@juscla what exactly do you mean by HID? Does it require new APIs or support in existing ones?

**Comment by tarekgh** [comment]
@juscla please clarify your ask.

**Comment by tarekgh** [comment]
closing it till we get more clarification then we can re-open it.

**Comment by juscla** [comment]
So i currently have frameworks that talk to devices over HID protocol, by pinvoking HID.DLL and would like to have this supported in the .netCore going forward. I have a Project that shows you how i am using it.

**Comment by shaggygi** [comment]
There is this open issue (#21810) that might be similar and provide goodness in this area.

**Comment by tarekgh** [comment]
Thanks @juscla 

Looks #21810 is covering this area then. feel free to put more comments there and we'll keep this issue closed as duplicate from #21810
