### ISSUE TITLE
HttpWebRequest.ServicePoint throws PlatformNotSupportedException unless Proxy is set

### ISSUE THREAD

**Issue by loop-evgeny** [dotnet/corefx#26922]
.NET Core 2.0.5

Accessing the ServicePoint on a newly created HttpWebRequest throws PlatformNotSupportedException. Code to reproduce:

```
var request = (HttpWebRequest)WebRequest.Create("http://www.example.com/");
request.ServicePoint.UseNagleAlgorithm = false; // PlatformNotSupportedException
```

Exception:
```
Unhandled Exception: System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.SystemWebProxy.GetProxy(Uri destination)
   at System.Net.ServicePointManager.ProxyAddressIfNecessary(Uri& address, IWebProxy proxy)
   at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy)
   at System.Net.HttpWebRequest.get_ServicePoint()
   at WebRequestServicePointThrows.Program.Main(String[] args) in C:\W ork\Bugs\WebRequestServicePointThrows\Program.cs:line 12
```

Workaround:
```
request.Proxy = null;
```

**Comment by davidsh** [comment]
In general ServicePoint class is not implemented nor supported on .NET Core.

**Comment by davidsh** [comment]
cc: @karelz

**Comment by loop-evgeny** [comment]
> In general ServicePoint class is not implemented nor supported on .NET Core.
Wait, so does this mean the Nagle algorithm will be used or not when I run the above code (with the workaround)?

**Comment by davidsh** [comment]
>Wait, so does this mean the Nagle algorithm will be used or not when I run the above code (with the workaround)?

It currently depends on which OS platform you are using. The current HTTP stacks in .NET Core are built on the OS HTTP stacks (WinHTTP for Windows and Curl for Linux).

cc: @stephentoub @geoffkizer

**Comment by loop-evgeny** [comment]
Thanks for fixing this quickly!

> It currently depends on which OS platform you are using. The current HTTP stacks in .NET Core are built on the OS HTTP stacks (WinHTTP for Windows and Curl for Linux).

OK, so as I understand, all those ServicePoint settings are ignored? Is this documented somewhere, along with what the settings are? E.g. I don't know whether WinHTTP or curl use Nagle, 100-Continue, etc.

**Comment by geoffkizer** [comment]
Settings for HttpClient are generally on the HttpClientHandler.

WinHTTP and Curl do not use the Nagle algorithm, as far as I'm aware.
