### ISSUE TITLE
Update EventSource.Redist nuget package description

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#26938]
https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.EventSource.Redist/

Add a description to the nuget package that explains that EventSource is inbox in .NET Core / is part of netstandard2.0. This helps existing customers to understand why installing the package on .NET Core fails and why it only support netfx TFMs.

See https://github.com/dotnet/corefx/issues/7206

**Comment by danmosemsft** [comment]
Setting 2.1 since this is a very popular package.
