### ISSUE TITLE
Turn on ILLinker's clearing of initlocals for corefx

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#26939]
We should set ILLinkClearInitLocals=true, and fix any issues that result.

cc: @jkotas, @erozenfeld 
https://github.com/dotnet/corefx/pull/25956

**Comment by tannergooding** [comment]
@stephentoub, Roslyn is adding support for an attribute that will do this in 7.3, should we have a separate issue to track using that instead of a post-IL rewriting phase?

**Comment by tannergooding** [comment]
See https://github.com/dotnet/csharplang/pull/1223

**Comment by stephentoub** [comment]
We already have the ILLinker as part of the corefx toolchain, so the work here is flipping a bit and then fixing any issues we find.  If/when there's subsequently a compiler feature, we could certainly switch to it.

**Comment by erozenfeld** [comment]
@JosephTremoulet @sbomer

**Comment by weshaggard** [comment]
@stephentoub I assume your recent PR did this work, aside from the other issue you filed for unix. In which case this issue can be closed? If what else should we do for 2.1?

**Comment by stephentoub** [comment]
> I assume your recent PR did this work, aside from the other issue you filed for unix. In which case this issue can be closed? If what else should we do for 2.1?

I did it for a subset of a assemblies, not for all of them.  I think our goal should be that it's set for the whole repo, rather than just a few projects.

**Comment by stephentoub** [comment]
(But that doesn't have to happen for 2.1 if we can't get there.)

**Comment by danmosemsft** [comment]
@stephentoub for the ones you didn't, was that because there were test failures? if not is it just a matter of verifying no test failures and committing, or did you analyze further?

**Comment by stephentoub** [comment]
>  for the ones you didn't, was that because there were test failures? if not is it just a matter of verifying no test failures and committing, or did you analyze further

There are some libraries where this causes a large number of failures. In the ones I looked at, e.g. System.Collections, the reason was obvious but fixing it (e.g. clearing stackalloc'd memory or changing the algorithm) would have required more investment (e.g. perf testing), and I wanted to focus mainly on the libs where choosing actually wasn't necessary.

In general, my approach was to flip the bit for a library, and:
a) run its tests
b) search for any stackalloc usage and then code review it to see whether it required clearing
c) search for P/Invoke usage with out arguments and code review to ensure either the native code zeros the out args or we only depend on their values if set
d) search for any & usage in unsafe code and verify no one's depending on an initialized value

**Comment by ViktorHofer** [comment]
@stephentoub do you have a list for which libraries this still needs to be done? I don't see any imminent infra work required here so I'll remove the label.

**Comment by stephentoub** [comment]
I'll take care of it.
