### ISSUE TITLE
Update the System.Math and System.MathF tests to cover some more edge scenarios

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#26941]
Currently the System.Math and System.MathF tests explicitly test the upper/lower inputs as well as +0, -0, NaN, +Inf, and -Inf.

We should also explicitly test values between the lower limit and -Inf and between the upper limit and +Inf, where applicable.

**Comment by tannergooding** [comment]
FYI. @eerhardt

**Comment by eerhardt** [comment]
See
https://github.com/dotnet/corefx/pull/26035#pullrequestreview-94886951
and
https://github.com/dotnet/corefx/pull/26035#pullrequestreview-94887794
