### ISSUE TITLE
Re-evaluate default buffer size for getpw native calls

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#26959]
By default, we are allocating 1K of memory on the stack as the first buffer to use in getpwnam_r and getpwuid_r.

https://github.com/dotnet/corefx/blob/bfac45af5dddcbd70b6935fcf92b4b8755f3cd1c/src/Common/src/System/IO/PersistedFiles.Unix.cs#L100

https://github.com/dotnet/corefx/blob/6f5ce856e9f40a7d247c241a6bb916fc546045ff/src/System.Runtime.Extensions/src/System/Environment.Unix.cs#L371

https://github.com/dotnet/corefx/blob/426e1c72a0dbda1aece127ec5f56696dc465d74b/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs#L632

We should re-evaluate if this is too large of a buffer to start with on the stack, as it may be too large for what is necessary.

See https://github.com/dotnet/corefx/pull/26945/files/55c360ff0e62b30814a085f079304a126dab9d21#diff-015aad2514de8320cbfe19ed2b8ee9a7

**Comment by wfurt** [comment]
OSX:
getconf LOGIN_NAME_MAX
255

Ubuntu:
getconf LOGIN_NAME_MAX
256

We should be able to query system limit if we want to.

**Comment by stephentoub** [comment]
Thanks. Seems like we could lower it to 256 as a more reasonable staring place then. If it's too small, the growth logic will kick in. Seems very rare for a login name to be more than that, even if it's allowed.

**Comment by eerhardt** [comment]
I'll get a PR up to update the default for all 3 places.

**Comment by stephentoub** [comment]
Sounds good.  Thanks, Eric.
