### ISSUE TITLE
Validate ClientWebSocket wss connections work through http proxies

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#26957]
After https://github.com/dotnet/corefx/pull/26878 is merged, validate (and ideally add automated tests) that ClientWebSocket's proxy support works when using wss connections.  And if it doesn't, fix it.

**Comment by karelz** [comment]
@wfurt can you please look at it?

**Comment by wfurt** [comment]
ok, I can take a look @karelz I don't think there is dependency on #26878 - that is only default configuration. We should be able to test with custom proxy as well as write tests. I'll net to get more familiar with WebSockets.

**Comment by stephentoub** [comment]
I put the wrong PR... I meant https://github.com/dotnet/corefx/pull/26869.

**Comment by geoffkizer** [comment]
Here's my comment on this issue from previously:  https://github.com/dotnet/corefx/pull/24288#issuecomment-332965476

cc @davidsh

**Comment by davidsh** [comment]
@wfurt Are you working on this issue?  If not, I can take it.

**Comment by wfurt** [comment]
It was in my list but I'm getting distracted with other issues. Please take it if you can @davidsh
