### ISSUE TITLE
Adding a new resource string to .resx file doesn't regenerate generated SR.cs 

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#26971]
Repro:

1. Open `corefx\src\System.Reflection.Metadata\System.Reflection.Metadata.sln` in VS.
2. Open `corefx\src\System.Reflection.Metadata\src\Resources\Strings.resx`
3. Add a new resource string and save the .resx file, e.g.

```xml
  <data name="Foo" xml:space="preserve">
    <value>Foo</value>
  </data>
```

4. Open any .cs file and type `SR.Foo`. `Foo` is not in completion.
5. Build. Build fails due to missing `SR.Foo` property.

**Expected behavior**

`SR.Foo` is generated as soon as the .resx file is saved.

**Comment by weshaggard** [comment]
@tarekgh I suspect this is just a input/output issue in the resource generation targets.

**Comment by tarekgh** [comment]
@weshaggard I don't think this is input/output issue. The problem I am seeing, when changing the resx file, VS/msbuild doesn't feel any change in the project and doesn't trigger the compilation and then the SR.cs will not get generated. while if you just compile manually, the SR.cs will get generated successfully and the intellisense will work fine which means the input/output is working correctly.

do you know how we get VS/msbuild feel there is something changed in the project when the resx file get changed to trigger the recompilation?

**Comment by weshaggard** [comment]
https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets#L17 The compiler will be looking at those items in order to determine if something changed that requires a recompile. Are our resource generation targets hooked up before or after CoreCompile?

**Comment by tarekgh** [comment]
It is hooked with CompileDependsOn

https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/resources.targets#L65

Should we change it to CoreCompile instead?

**Comment by weshaggard** [comment]
Assuming our resource.targets get imported before https://github.com/Microsoft/msbuild/blob/c89986fab69c7ea89c839ced5287109053ed6136/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3188 then you shouldn't need to change anything. It probably just takes some digging through logs to ensure the resx and/or generated cs file correctly happens before CoreCompile inputs are evaluated and ensure those are in the input set.

**Comment by tmat** [comment]
This is what we do in RepoToolset:

https://github.com/dotnet/roslyn-tools/blob/master/sdks/RepoToolset/tools/GenerateResxSource.targets#L17

We have a custom x-plat task that generates C# code for resx files to intermediate output path on build. It's also hooked to design time build so that it's triggered once you save the resx file in VS.

**Comment by tarekgh** [comment]
@tmat is yours hooked to design time because of the target is marked with BeforeTargets="CoreCompile"?

**Comment by tmat** [comment]
It's the Generator metadata:
`<Generator>MSBuild:_GenerateResxSource</Generator>`

**Comment by tarekgh** [comment]
I'll try it. Thanks for pointing out to that.

**Comment by tarekgh** [comment]
reopening till we get the new buildtools to corefx

**Comment by tarekgh** [comment]
This is now fixed.
