### ISSUE TITLE
Checking null on some value types are throwing runtime exceptions

### ISSUE THREAD

**Issue by kasper3** [dotnet/corefx#26987]
Try:

`dotnet new console`

replace `<TargetFramework>` line with `<TargetFrameworks>net46;netcoreapp2.0</TargetFrameworks>` to csproj

Program.cs:

```c#
using System;
class Program { static void Main(string[] args) { if (new ArraySegment<byte>() == null); } }
```

and run: `dotnet run -f net46`, which works fine but `dotnet run -f netcoreapp2.0` throws:

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: array
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.ArraySegment`1.op_Implicit(T[] array)
```

Is this breaking change recorded somewhere or it's a bug? Checking null on arraysegment object doesn't make sense but it shouldn't probably throw this kind of bold exception at run time. Ideally it should be a no-op and the compiler should raise a warning. If I change my example to check primitive value types:

```c#
class Program { static void Main(string[] args) { var x = 1; if (x == null); } }
```

Then compiler raises a warning in both `net46` and `netcoreapp2.0` cases:

```
Program.cs(3,65): warning CS0472: The result of the expression is always 'false' since a value of type 'int' is never equal to 'null' of type 'int?'
```

and no runtime exception is produced. The behavior of all value types should be aligned.

If it's done for optimization (avoiding a null check for example), then i think it should be reverted and JIT should be optimizied instead to emit no-op for such impossible conditions.

**Comment by stephentoub** [comment]
It's because there's an implicit cast now from array to ArraySegment. The C# compiler will use that cast with the null value, resulting in the exception being thrown from the implicit cast operator.

@jkotas, seems like we should have the operator check for null and return default rather than throwing?

**Comment by jkotas** [comment]
Agree.

**Comment by jkotas** [comment]
Dup of https://github.com/dotnet/coreclr/issues/14012

**Comment by stephentoub** [comment]
Thanks. Closing as dup.
