### ISSUE TITLE
Code cleanup for System.IO.Packaging

### ISSUE THREAD

**Issue by EricWhiteDev** [dotnet/corefx#2699]
- [x] ContentType.cs - line 234 - use String.Equals instead of String.Compare
- [x] ContentType.cs - 83 - if (contentType.Length == 0)
- [x] PackagePart.cs - 849 - return !s.CanRead && !s.CanSeek && !s.CanWrite;
- [ ] Package.cs - 976 - What's the purpose of the try block with an empty finally?
- [x] PackageUriHelper.cs - 1297 - at least one other place where the same thing was declared. Should they be consolidated?
- [x] PackageUriHelper.cs - 1025 - Rather than using comments, these could use named arguments.
- [x] PackageUriHelper.cs - 991 - There are various places thus far in the implementation that use '/' hardcoded... should they instead be using ForwardSlashChar?
- [ ] PackageUriHelper.cs - 926 - Why not just: return the_condition;
- [x] PackUriHelper.cs - 695 - the chars array could be stackalloc'd instead of heap allocated.
- [x] PackUriHelper.cs - 451 - Any reason not to combine these Path.Combine calls?
- [x] InternalRelationshipCollection.cs - 592 - Debug.Fail?
- [ ] InternalRelationshipCollection.cs - 325 - Formatting off
- [ ] IgnoreFlushAndCloseStream.cs - 18 - This comment appears out-of-date: there is no IgnoreFlushAndClose property, and Flush/Dispose never delegate to the wrapped stream's corresponding members.
- [ ] IgnoreFlushAndCloseStream.cs - 48 - get { return !_disposed && _stream.CanRead; }
- [ ] FileFormatException.cs - 139 - readonly?
- [x] ContentType.cs - 666 - This loop could be replaced by a call to Array.IndexOf<char>.
- [x] ContentType.cs - 620 - return IsAsciiLetter(character) || (character >= '0' && character <= '9');
- [x] ContentType.cs - 561 - It seems a bit odd to be explicit about the kind of comparison we want for the characters and to be doing a Compare rather than Equal when what we're checking for is just an empty string.
- [x] ContentType.cs - 527 - if (string.IsNullOrEmpty(token))
- [x] ContentType.cs - 531 - The body of this loop could be simplified to just: if (!IsAsciiLetterOrDigit(token[i]) && !IsAllowedCharacter(token[i])) throw new ArgumentException(SR.InvalidToken);
- [ ] ContentType.cs - 398 - There's a lot of string manipulation / allocation / etc. happening in these various helper functions. Doesn't need to be fixed now, as it's not clear that it's a problem. But it'd be interesting to do some perf testing / profiling and see what pops as hot spots that we'll potentially want to fix.
- [x] ContentType.cs - 390 - "ans" => "and"
- [ ] ContentType.cs - 225 - Do we know that MoveNext is always going to return true here such that Current will be valid?
- [ ] ContentType.cs - 89 - It doesn't appear that we know at this point that contentType isn't empty. Couldn't this result in indexing out of bounds into contentType?
- [x] ContentType.cs - 262 - "paramterKey" => "parameterKey"
- [ ] PackUriHelper.cs - 791 - Could this just do a ordinal-ignorecase comparison rather than allocating new strings with ToUpperInvariant?
- [x] ContentType.cs - 323 - Is this type used anywhere? It appears to be dead code.
- [x] ContentType.cs - 294 - Is this type used anywhere? It appears to be dead code.
- [x] PackUriHelper.cs - 737 - I don't know if allocations matter here, but you could trivially avoid this allocation by using IndexOf instead of Contains.
- [x] ContentType.cs - 604 - Couldn't it use Array.IndexOf?

**Comment by joshfree** [comment]
ping @EricWhiteDev

**Comment by EricWhiteDev** [comment]
@joshfree I have been pulled off of this project.  I am headed out for a vacation for the next month.  When I return, if possible I can work on these.

**Comment by lakkijyotsna** [comment]
Hi,
I have a document of type docx, which has a Property ContentType defined as 'Document'. While reading this using System.IO.Packaging ContentType is read as null.
Is this the problem occured because of definition of contentType property in docx file?

**Comment by alexsorokoletov** [comment]
Can someone please clarify following items:
> PackUriHelper.cs - 695 - the chars array could be stackalloc'd instead of heap allocated.
> InternalRelationshipCollection.cs - 592 - Debug.Fail?
> ContentType.cs - 398 - There's a lot of string manipulation / allocation / etc. happening in these various helper functions. Doesn't need to be fixed now, as it's not clear that it's a problem. But it'd be interesting to do some perf testing / profiling and see what pops as hot spots that we'll potentially want to fix.
> ContentType.cs - 225 - Do we know that MoveNext is always going to return true here such that Current will be valid?
> ContentType.cs - 89 - It doesn't appear that we know at this point that contentType isn't empty. Couldn't this result in indexing out of bounds into contentType?


Also, what is the best way to work with changes related to the same issue from multiple people?
Please advise.

**Comment by Maxwe11** [comment]
>PackUriHelper.cs - 695 - the chars array could be stackalloc'd instead of heap allocated.
InternalRelationshipCollection.cs - 592 - Debug.Fail?

done in #4408
