### ISSUE TITLE
Crypto provider wrappers in System.Security.Cryptography.Algorithms

### ISSUE THREAD

**Issue by jorgebay** [dotnet/corefx#26990]
PR #12964 added crypto wrappers.

I'm able to use them targeting netstandard 2.x but not for netstandard1.x.

I see that those providers are not included as part of `System.Security.Cryptography.Algorithms` package (v4.3.1). Would it be possible to include them as part of the nuget package?

**Comment by bartonjs** [comment]
Are you having a compilation problem, or a runtime problem?

**Comment by jorgebay** [comment]
Its a compilation issue, wrappers are not available on net standard 1.x and not included in `System.Security.Cryptography.Algorithms` package.

**Comment by bartonjs** [comment]
Okay, that's what I would expect.  The wrappers were added for netstandard 2.0.  There's no expectation that they will be available when targeting lower versions.

Whether using netstandard 1.x or 2.0 the recommended pattern is to use the algorithm factory methods.

| Replace This | With This |
| --- | --- |
| new SHA1CryptoServiceProvider() | SHA1.Create() |
| new SHA256CryptoServiceProvider() | SHA256.Create() |
| new SHA384CryptoServiceProvider() | SHA384.Create() |
| new SHA512CryptoServiceProvider() | SHA512.Create() |
| new AesCryptoServiceProvider() | Aes.Create() |

etc

**Comment by jorgebay** [comment]
If that means that wrappers are not going to be provided in .NET Standard 1.x, this ticket can be closed :)
