### ISSUE TITLE
HttpClient not setting Accept-Encoding: gzip, deflate on older Windows versions

### ISSUE THREAD

**Issue by junweilee** [dotnet/corefx#26991]
.NET Core 2.1.4 SDK

```csharp
var handler = new HttpClientHandler()
{
       AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate
};

using (var client = new HttpClient(handler))
{
      response = client.GetStringAsync("http://scooterlabs.com/echo").Result;
}
```

On a Windows 2008 R2 box, it looks like `Accept-Encoding` is **not** set even though the `HttpClientHandler` has compression set.

Windows 2008 R2
```
[headers] => Array
(
    [Connection] => Keep-Alive
    [Host] => scooterlabs.com
)
```

Windows 10
```
[headers] => Array
(
    [Connection] => Keep-Alive
    [Accept-Encoding] => gzip, deflate
    [Host] => scooterlabs.com
)

```
This works as expected on a Windows 10 box and Windows 8.1 VM.

If you force the headers to be sent however, on Windows 2008 R2 it decompresses fine, so compression is supported.

If you use WebClient or HttpWebRequest directly with `AutomaticDecompression` set it works on all versions with the correct headers and ability to handle the compressed payload.

This works on all environments
```csharp
var handler = new HttpClientHandler()
{
       AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate
};

using (var client = new HttpClient(handler))
{
      client.DefaultRequestHeaders.AcceptEncoding.Add(new StringWithQualityHeaderValue("gzip"));
      client.DefaultRequestHeaders.AcceptEncoding.Add(new StringWithQualityHeaderValue("deflate"));
      response = client.GetStringAsync("http://scooterlabs.com/echo").Result;
}
```

P/s: SO question is here https://stackoverflow.com/questions/48703143/httpclient-not-sending-accept-encoding-on-different-machine

**Comment by karelz** [comment]
It is weird if HttpWebRequest works fine on the same OS (Win 2008 R2)
@davidsh is it a known problem / would you expect it?

**Comment by davidsh** [comment]
>@davidsh is it a known problem / would you expect it?

This issue is not a known problem that I am aware of.

However, internally, there is a difference in the implementation of how decompression works depending on which version of the OS you are running on.  .NET Core on Windows uses native WinHTTP component.  And on Windows 7 / Windows Serve 2008 R2, WinHTTP does not have internal support for decompression.  So, the decompression is handled in the .NET layer (WinHttpHandler).  From the top-level of HttpClient API behavior, that internal difference in how decompression works should not matter. But it is possible that there is some bug here regarding all of this.

**Comment by junweilee** [comment]
FYI here's some sample WebClient code that works with just setting the decompression flag

```csharp

class MyWebClient : WebClient
{
    protected override WebRequest GetWebRequest(Uri address)
    {
        HttpWebRequest request = base.GetWebRequest(address) as HttpWebRequest;
        request.AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip;
        return request;
    }
}
```

**Comment by pbournakas** [comment]
Hello there, i don't know if this is the same problem, but in Xamarin Project with System.Net.Http you can't make gzip compression to work if you don't put in HttpClient an HttpClientHandler with AutomaticDecompression. But in Android and iOS Xamarin if you put an HttpClientHandler then you can't use the natives http handlers that use some functionality like NSURLSession etc..

This problem with the HttpClient is the same with the above?

**Comment by davidsh** [comment]
@pbournakas 

>But in Android and iOS Xamarin if you put an HttpClientHandler then you can't use the natives http handlers that use some functionality like NSURLSession etc.

This is a closed issue so it doesn't get monitored regularly.  Since you are having problems on Xamarin, you should open a new issue in the [Mono repo](https://github.com/mono/mono) which is where the Xamarin codebase is.

@marek-safar

**Comment by linda-dge** [comment]
I'm having the same issue in Xamarin.  I will try and find the case in the Mono repo.
