### ISSUE TITLE
Add DecompressionMethods.Brotli?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#26995]
System.Net.DecompressionMethods is an enum that is used by HttpClient handlers to determine whether/what to automatically decode in a response, e.g. if DecompressionMethods.Deflate is set and the response is encoded with deflate, it'll automatically decode the response as part of handing it back.

The enum today is just:
```C#
namespace System.Net
{
    [Flags]
    public enum DecompressionMethods
    {
        None = 0,
        GZip = 1,
        Deflate = 2
    }
}
```
but we now also have BrotliStream, which we could use to support a DecompressionMethods.Brotli and a "br" encoding:
```C#
namespace System.Net
{
    [Flags]
    public enum DecompressionMethods
    {
        ...
        Brotli = 4
    }
}
```
From an implementation perspective, this would mean either System.Net.Http.dll taking a dependency on System.IO.Compression.Brotli.dll, or if we wanted to avoid the dependency, building all of the source into System.Net.Http.dll (there is currently a native dependency, with the native portion compiled into clrcompression.dll on Windows and System.IO.Compression.Native.so/dylib on Unix).

**Comment by jnm2** [comment]
I knew I wasn't wrong to wish for a `DecompressionMethods.All` member.

**Comment by kasper3** [comment]
>         Brotli = 4

@stephentoub, should this be `3` instead?

Also, can we also have `All = ~None` option as @jnm2 stated?

**Comment by stephentoub** [comment]
> should this be 3 instead?

No, it's a [Flags] enum.  It needs to be a unique bit.

**Comment by joshfree** [comment]
@karelz can we put this on the short list for 2.2 as part of finishing the brotli e2e?

Related https://github.com/aspnet/BasicMiddleware/issues/217

**Comment by karelz** [comment]
Sure why not. We didn't review issues for 2.2 yet. So anything in Future is potential 2.2 at this point.

**Comment by jnm2** [comment]
I am very interested in an `All` member. Would you please review that possibility?

**Comment by stephentoub** [comment]
@jnm2, please open a separate issue.

**Comment by jnm2** [comment]
Certainly! Sorry for missing the approval tag on this one.
