### ISSUE TITLE
Add Vector.Narrow and Vector.Widen overloads to cast elemnts values between float and int, and between double and long

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/corefx#27014]
I suggest to add these two overloads to the Vector.Narrow method:
```
Vector<int> Vector.Narrow(Vector<float>, ConversionType ct)
Vector<long> Vector.Narrow(Vector<double> ConversionType ct)

```
where:
```
enum ConversionType
{
    Floor,        // Apply Mathf.Floor
    Ceiling,     // Apply Mathf.Ceiling
    Truncate,   // Apply Mathf.Truncate
    Round       // Apply Mathf.Round
}

```
Example:
```
var v1 = new Vector<float>({-1.4, 2.1, -3.9, 4.3});
var v2 = Vector.Narrow(v1, ConversionType.Floor);
      // <-2, 2, -4, 4>

```
By the way, It will be nice if we can use foreach to iterate Vector<T> elemnts using foreach..
I think more mathematical methods (like the ones in the Math class) can be added to the Vector class. The fact that the Vector<T> is immutable, demands some long codes to construct a new version containing individual results. Or, is there a chance to make the Indexer read-write?

**Comment by eerhardt** [comment]
Have you taken a look at:

```
public static partial class Vector
{
  public static System.Numerics.Vector<int> ConvertToInt32(System.Numerics.Vector<float> value);
```

?

I think it does what you are trying to do above.

**Comment by MohammadHamdyGhanem** [comment]
Thanks @eerhardt. I don't know how I missed this. I focused on the Narrow, Widen and Asxx methods, and didn't see this one. 
There is still one feature in my suggestion to control how rounding is done. The ConvertTo32 can have an overload with a second param. to do this.
Another Feature is the fore each.
I think more mathematical methods (like the ones in the Math class) can be added to the Vector class. The fact that the Vector<T> is immutable, demands some long codes to construct a new version containing individual results. Or, is there a chance to make the Indexer read-write?

**Comment by MohammadHamdyGhanem** [comment]
I figured out why I didn't see the ConvertToInt32 method. It is not mentioned here:
https://msdn.microsoft.com/en-us/library/system.numerics.vector(v=vs.111).aspx
but I discoverd that it is mentioned here:
https://docs.microsoft.com/en-us/dotnet/api/system.numerics.vector?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Numerics.Vector);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.7);k(DevLang-VB)%26rd%3Dtrue&view=netcore-2.0
This is confusing and wastes a lot of efforts!

**Comment by eerhardt** [comment]
> I figured out why I didn't see the ConvertToInt32 method. It is not mentioned here:
https://msdn.microsoft.com/en-us/library/system.numerics.vector(v=vs.111).aspx

We are transitioning from msdn.microsoft.com to docs.microsoft.com for our documentation.  Unfortunately it doesn't happen all at once.

The Widen, Narrow, and ConvertToXXX methods all [came in during .NET Core 2.0](https://github.com/dotnet/corefx/pull/16276), which is why you don't see them on the older docs sites.
