### ISSUE TITLE
Implement Snappy compression algorithm 

### ISSUE THREAD

**Issue by Yves57** [dotnet/corefx#27013]
The Brotli algorithm has been recently implemented. I think that it would be nice to see a similar implementation for Snappy: it is very popular, cross platform, open source, with a lower compression but faster than Brotli.

**Comment by clarkis117** [comment]
For prior a implementation see: https://github.com/jeffesp/Snappy.Sharp

**Comment by clarkis117** [comment]
Also:
https://github.com/Kintaro/SnappySharp

**Comment by carlossanlop** [comment]
Triage:
Not super high interest in the last two years and there is an independent community implementation. We would not add too much value by adding it to the platform.
