### ISSUE TITLE
Not a good idea to specify charset parameter for some content types in StringContent

### ISSUE THREAD

**Issue by bcr** [dotnet/corefx#27015]
https://github.com/dotnet/corefx/blob/6bf1e7c3032d3c24d5a41bbd880549ef4a8de2da/src/System.Net.Http/src/System/Net/Http/StringContent.cs#L31

I was building a `StringContent` object with a `mediaType` of `application/json`. That media type does not specify a `charset` parameter, which is unconditionally added in this class.

Adding this parameter automatically is probably not a good idea. I'm not sure the right fix, I just know that `Content-Type: application/json; charset=utf-8` will choke some parsers.

**Comment by davidsh** [comment]
This issue is similar or perhaps a duplicate of #25290.

**Comment by bcr** [comment]
I agree. Sorry for the noise.
