### ISSUE TITLE
Test failure in CI: System.Collections.Tests.LinkedList_Generic_Tests_string/AddBefore_LLNode_LLNode

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#27018]
https://mc.dot.net/#/user/tmat/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Frelease~2F2.1~2F/test~2Ffunctional~2Fcli~2F/76c888d757bf1e9d470ceb4b93d3d00b5be5d4ec/workItem/System.Collections.Tests/analysis/xunit/System.Collections.Tests.LinkedList_Generic_Tests_string~2FAddBefore_LLNode_LLNode

**Comment by danmosemsft** [comment]
Log is gone. @tmat I don't suppose you have the log? Otherwise we have to close, this test is really long and has lots of possible asserts that could have failed.

**Comment by tmat** [comment]
@danmosemsft I do not have a log.

**Comment by danmosemsft** [comment]
Too bad, if we see again we can add more logging.
