### ISSUE TITLE
The terminfo database is invalid

### ISSUE THREAD

**Issue by livarcocc** [dotnet/corefx#27012]
_From @SebastianPfliegel on February 9, 2018 18:10_

## Steps to reproduce
I'm using openSUSE Tumbleweed and downloading the SDK and runtime via the official repos.
dotnet new console -o myApp
cd myApp
dotnet run

## Expected  behavior
Hello World printed. No exception thrown.

## Actual behavior
Exception gets thrown: http://susepaste.org/65975762
However, if I run `dotnet run > output.txt` the exception still gets thrown, but *output.txt* says **Hello World!**. I tried several SDK and runtime versions, but everyone failed.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     opensuse
 OS Version:  20180207
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

_Copied from original issue: dotnet/cli#8576_

**Comment by livarcocc** [comment]
If you run dotnet publish and then execute your app through dotnet <path_to_published_dll>, does this fail with the same exception?

I am trying to differentiate between a runtime failure vs a tooling failure.

**Comment by livarcocc** [comment]
_From @danmosemsft on February 9, 2018 21:21_

Looks like https://github.com/dotnet/corefx/issues/26966

**Comment by danmosemsft** [comment]
dupe.
