### ISSUE TITLE
Add a way to wait for a task without throwing

### ISSUE THREAD

**Issue by GSPP** [dotnet/corefx#2703]
`Task.Wait` throws an exception if the task is faulted or cancelled. Sometimes it is necessary to wait for completion but not be interrupted by an exception.

Catching and swallowing the exception is a really bad workaround. Using exceptions for control flow is not a good thing. Also, exceptions are extremely slow.

1. The `Wait` method should have an overload that allows the caller to specify that he does not want an exception.
2. There should be a method `Task WhenCompleted(this Task task)` that returns a new task that becomes completed when the base task becomes completed. Cancellation and exceptions should not be propagated. That way we can write `await myTask.WhenCompleted()` to avoid exceptions.
3. In the same spirit as (2) there probably should be `WhenCompletedSuccessfully`, `WhenCancelled` and `WhenFaulted`. These tasks complete when the underlying task transitions to the respective state. They do not ever complete if the underlying task transitions to a different final state. They should *not* become cancelled in that case because the idea of these methods is that you can avoid exceptions for control flow in a convenient manner.

**Comment by stephentoub** [comment]
> Task WhenCompleted(this Task task)

This essentially exists, it's just called ContinueWith, e.g.
```C#
await task.ContinueWith(t => { });
```

> They do not ever complete if the underlying task transitions to a different final state

This is very dangerous.  We do not want to expose tasks that never complete.

**Comment by GSPP** [comment]
OK, similar discussion as in the other issue.

The code really should be

    task.ContinueWith(_ => { }, TaskContinuationOptions.ExecuteSynchronously)

which is quite tedious. If there's a good way to have this built-in that would be useful to avoid misusing exceptions for control flow. Many beginners are doing that right now in combination with await and the TPL.

**Comment by sharwell** [comment]
You could use the [`Finally`](http://tunnelvisionlabs.github.io/dotnet-threading/docs-latest/html/Overload_Rackspace_Threading_CoreTaskExtensions_Finally.htm) extension method for this.

If you only want the code to execute if the task is successful, you can use the [`Select`](http://tunnelvisionlabs.github.io/dotnet-threading/docs-latest/html/Overload_Rackspace_Threading_CoreTaskExtensions_Select.htm) or [`Then`](http://tunnelvisionlabs.github.io/dotnet-threading/docs-latest/html/Overload_Rackspace_Threading_CoreTaskExtensions_Then.htm) extension methods.

**Comment by stephentoub** [comment]
replaced by https://github.com/dotnet/corefx/issues/8142
