### ISSUE TITLE
System.Runtime.InteropServices bad calling convention when returning unions on linux

### ISSUE THREAD

**Issue by candide-guevara** [dotnet/corefx#27046]
Hi,

When using Interop on linux my app crashed. I managed to narrow it down to the cas where the native method returns an union.  When I looked at the core dump with gdb it seemed to me that the calling convention is wrong. I was expecting to see the pointer to the string in register RDI but it contained garbage.

I do not know if it is correct behavior or a bug, but I would appreciate if somebody has the time to take a look.

Thanks !

## Environnent

* Fedora 26 linux 4.14.14-200.fc26.x86_64
* dotnet 2.1.4
* gcc (GCC) 7.2.1 20170915

## C++ shared object code

            #include <iostream>
            #include <string>

            extern "C"
            union Union {
                int64_t f2;
            };

            extern "C"
            Union crash(const char* msg) {
                std::cerr << __PRETTY_FUNCTION__ << " start" << std::endl;
                std::cerr << __PRETTY_FUNCTION__ << " ptr " << (void*)msg << std::endl;
                std::cerr << __PRETTY_FUNCTION__ << " arg " << msg << std::endl;
                return Union{};
            }

Compiled using : `g++ -Wall -fPIC -std=c++11 -shared -O0 -g -o libcrash.so crash.cpp`

## C# console app code

        using System;
        using System.Runtime.InteropServices;
        
        namespace question
        {
            [StructLayout(LayoutKind.Explicit)]
            public struct Union {
                [FieldOffset(0)]
                Int64 field2;
            }
        
            class Program
            {
                [DllImport("libcrash.so")]
                static extern Union crash(string s);
        
                static void Main(string[] args)
                {
                    crash("boom !!");
                    Console.WriteLine("All Done");
                }
            }
        }

**Comment by karelz** [comment]
@janvorli do you know what is the calling convention on Linux?

**Comment by jkotas** [comment]
Dup of https://github.com/dotnet/coreclr/issues/4307

**Comment by jeffschwMSFT** [comment]
Closing and tracking by @dotnet/coreclr#4307
