### ISSUE TITLE
Nested Transactions failing - Enlisting in Ambient transactions is not supported

### ISSUE THREAD

**Issue by balsingh** [dotnet/corefx#27057]
Nested transaction are broken in System.Data.SqlClient 4.4.2 (latest stable release)

They work with System.Data.Sqlclient 4.3.1.

The error is Enlisting in Ambient transactions is not supported.

Below is sample code which works in 4.3.1 and now boken in 4.4.2

```c#
var option = new TransactionOptions
{
    IsolationLevel = IsolationLevel.ReadCommitted,
    Timeout = TimeSpan.FromSeconds(60)
};
using (var scopeOuter = new TransactionScope(TransactionScopeOption.Required, option))
{
    using (var conn = new SqlConnection(connectionString))
    {
        using (SqlCommand cmd = conn.CreateCommand())
        {
            cmd.CommandText = "INSERT INTO Data(Code, FirstName) VALUES('A-100', 'Mr. A');";
            cmd.Connection.Open();
            cmd.ExecuteNonQuery();
        }
    }
    using (var scopeInner = new TransactionScope(TransactionScopeOption.Required, option))
    {
        using (var conn = new SqlConnection(connectionString))
        {
            using (SqlCommand cmd = conn.CreateCommand())
            {
                cmd.CommandText = "INSERT INTO Data(Code, FirstName) VALUES('B-100', 'Mr. B');";
                cmd.Connection.Open();
                cmd.ExecuteNonQuery();
            }
        }
        scopeInner.Complete();
    }
    scopeOuter.Complete();
}
```

[EDIT] Update code formatting and syntax highlighting by @karelz

**Comment by saurabh500** [comment]
`System.Data.Sqlclient 4.3.1` used to not enlist in TransactionScope and allow operations in transaction scope. However this was dangerous, as the library consumers would expect the transactions to be rolledback in case of errors. That was never happening. We added an error message to 4.4.x in case the Enlist keyword is set to true in connection string. 
There is no capability in 4.4.x or earlier version of SqlClient to enlist in a transaction scope transaction. 
In case you want to turn the error message off, you need to set Enlist=False in the connection string. 
The support of Auto-enlistment is targeted for the next major release.

**Comment by tkggusraqk** [comment]
@saurabh500 
The latest SqlClient 4.4.2 still doesn't support，Old project migration, cost is greater。
When to support?
