### ISSUE TITLE
Test failure: PostAsync_CancelDuringRequestContentSend_TaskCanceledQuickly

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#27063]
WinHttpHandler has some cancellation support, but it doesn't appear to support cancellation during content send, e.g. if cancellation is requested and the server never sends back response headers.  netfx has the same issue.  UAP (WinRT based stack) also hangs.

**Comment by karelz** [comment]
Triage: We should make the test scoped only to `SocketsHttpHandler` (SkipOn), because `WinHttpHandler` will never have this agility.
