### ISSUE TITLE
My idea:Async and Task function pipeline

### ISSUE THREAD

**Issue by HeMinzhang** [dotnet/corefx#27062]
I design a Lambda  Expression:Task<IEnumerable> WhereAsync.
If you used WhereAsync,You Lambda Expression pipline such as WhereAsync().SelectAsync() be broken.

So If c# has a async Lambda Expression pipline,We used async and Task our function pipline don't be broken.

**Comment by HeMinzhang** [comment]
I found a way to use async c#  Lambda Expression  function pipeline operations.
Although a bit complex.

```
IEnumerable<T> model = new List<T>{
  new T(),
 ... ...
};

(await model.WhereAsync()).Select( ... ...);
```

**Comment by davidfowl** [comment]
What are you trying to achieve?

**Comment by HeMinzhang** [comment]
@davidfowl  

like this:

> model.whereAsync(... ...).select(... ...)

**Comment by davidfowl** [comment]
Why? What's asynchronous about your implementation of Where?

**Comment by HeMinzhang** [comment]
@davidfowl  WhereAsync is my design extension function.

**Comment by Clockwork-Muse** [comment]
@HeMinzhang - No, we know that.  He means, 1) "What does it do/how was it written?", and perhaps more importantly, 2) "What code is it calling that you think needs to be async?".

Currently, when dealing with async collections (say, like for EntityFramework), `Where` is usually left as a lazy, sync, pipeline operation, and the async part is left to the final result collector (`FirstAsync`, `ToListAsync`, etc).

**Comment by tarekgh** [comment]
CC @stephentoub

**Comment by stephentoub** [comment]
This is a year old with open questions to the original poster. It sounds like a request for async enumerables, which are introduced in .NET Core 3.0. I'm closing this for now; it can be reopened if I've misunderstood. Thanks.

**Comment by HeMinzhang** [comment]
Sorry, the reply is too late.  My idea is that multiple expressions can form a bunch of pipes.  But if some or all of these expressions are asynchronous, we must use a single await, one by one, why not use await all

**Comment by HeMinzhang** [comment]
Directly asynchronously waiting for a string of expressions (asynchronous and synchronous expressions).

**Comment by HeMinzhang** [comment]
It’s painful to think of a bunch of variable names that are abandoned immediately.
