### ISSUE TITLE
Tests are not waiting on child processes when run

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#27086]
Some tests use RemoteInvoke to launch child processes. Generally they should call Dispose() on the RemoteInvokeHandle that returns in order to WaitForExit on the process. If they forget, execution will continue and any assertion failure (or other unhandled exception) in the child process will not prevent the test passing. Eg.,:
```
  Running tests... Start time: 22:29:13.23
  xUnit.net console test runner (64-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.

  Discovering: System.Text.RegularExpressions.Tests
  Discovered:  System.Text.RegularExpressions.Tests
  Starting:    System.Text.RegularExpressions.Tests

  Unhandled Exception: Xunit.Sdk.ThrowsException: Assert.Throws() Failure
  Expected: typeof(System.ArgumentException)
  Actual:   typeof(System.TypeInitializationException): The type initializer for 'System.Text.RegularExpressions.Regex'
   threw an exception.
     at Xunit.Assert.Throws(Type exceptionType, Exception exception) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.a
  ssert\Asserts\ExceptionAsserts.cs:line 143
     at Xunit.Assert.Throws[T](Func`1 testCode) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\Excepti
  onAsserts.cs:line 36
     at System.Text.RegularExpressions.Tests.RegexConstructorTests.<>c.<StaticCtor_InvalidTimeoutObject_ExceptionThrown
  >b__3_0() in C:\git\corefx\src\System.Text.RegularExpressions\tests\Regex.Ctor.Tests.cs:line 85
  --- End of stack trace from previous location where exception was thrown ---
     at RemoteExecutorConsoleApp.Program.Main(String[] args) in C:\git\corefx\src\Common\tests\System\Diagnostics\Remot
  eExecutorConsoleApp\RemoteExecutorConsoleApp.cs:line 92
  Finished:    System.Text.RegularExpressions.Tests

  === TEST EXECUTION SUMMARY ===
     System.Text.RegularExpressions.Tests  Total: 802, Errors: 0, Failed: 0, Skipped: 0, Time: 2.042s
  Finished running tests.  End time=22:29:15.68, Exit code = 0
```

This behavior is slightly obscured when running on a dev machine, as runtests.cmd is generally wrapped inside MSBuild, and MSBuild, after WaitforExit hsa returned on the process it launched, will then wait indefinitely for the console output streams to reach EOF. Those do not return until the grandchild remote processes have exited (@JeremyKuhne @stephentoub  I'm unclear why this is - do they automatically duplicate the console handles from the test process which is MSBuild's direct child?). When the grandchild fails in this situation, the exception will appear in the console, but the test will already have succeeded and be counted as such.

When Helix runs the tests using runtest.cmd directly, MSBuild is not involved so if Dispose() is forgotten there is no wait on the grandchildren and they are completely ignored. https://github.com/dotnet/corefx/pull/26543#issuecomment-365021333 is an example.

We should add a finalizer to RemoteInvokeHandle which will mean that at least some waiting will occur on those child processes: they still wont fail the test, as it's too late, but their console output is more likely to show up in the log. (XUnit does not do WaitForPendingFinalizers so I figure if they don't complete within X seconds - I think 40 seconds - of the XUnit process completing, the output still won't show up.)

@stephentoub  does this sound like the best we can do?

**Comment by danmosemsft** [comment]
cc @MattGal

**Comment by danmosemsft** [comment]
We can assert at the top of the finalizer, without waiting on the remote process (wihch may never complete) so the 40 sec should not be an issue and we can deterministically fail for these.

**Comment by stephentoub** [comment]
Finalizer approach sounds reasonable.

Another instead or in addition could be to have RemoteInvoke store info into a static dictionary on ctor and remove it on dispose, and then have it's static cctor hook up an Unloading event that'll enumerate and output that dictionary.

There may also be some xunit hooks we could leverage here, e.g. an after test executes event that would throw out errors if any RemoteInvoke was still running.

**Comment by stephentoub** [comment]
Or maybe simpler would just be to make RemoteInvoke itself wait/dispose so we can't mess it up, and then for the more niche care where you don't want that, have a special method for that with a scarier name.

**Comment by danmosemsft** [comment]
Those would both work. I'll stick with the finalizer as it's simple and seems to work well.

**Comment by ViktorHofer** [comment]
I believe this is already addressed.
