### ISSUE TITLE
Consider adding MemoryMarshal.TryGetArray/MemoryList(ReadOnlySequence)

### ISSUE THREAD

**Issue by pakrym** [dotnet/corefx#27097]
We shouldn't interpret `SequencePositions` outside `ReadOnlySequence` but pipelines need to get IMemoryList reference and indexes out of SequencePositions received in `Advance`

I'm proposing to add the following API's:
```C#
public static partial class MemoryMarshal
{
    bool TryGetArray<T>(ReadOnlySequence<T> sequence, out ArraySegment<T> array);

    bool TryGetOwnedMemory<T>(ReadOnlySequence<T> sequence, out OwnedMemory<T> ownedMemory, out int start, out int length);

    bool TryGetMemory<T>(ReadOnlySequence<T> sequence, out ReadOnlyMemory<T> readOnlyMemory);

    bool TryGetMemoryList<T>(ReadOnlySequence<T> sequence, out IMemoryList<T> startSegment, out int startIndex, out IMemoryList<T> endSegment, out int endIndex);
}
```

/cc @davidfowl @KrzysztofCwalina

**Comment by ahsonkhan** [comment]
We should discuss this at the next API review and get it approved: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md

Also, rename arg name (`out Memory<T> ownedMemory`).

Should it return ReadOnlyMemory?

**Comment by terrajobst** [comment]
We looked at this briefly today but it would be good to have to @pakrym and/or @halter73 here too

**Comment by benaadams** [comment]
Bug causing this api is https://github.com/dotnet/corefx/issues/27224

**Comment by benaadams** [comment]
Its because Sequence encodes type in index so gives you junky indexes

**Comment by terrajobst** [comment]
@KrzysztofCwalina and I just talked with @pakrym, @halter73, and @davidfowl and we're fine with these APIs. I'm not marking it as approved outside our normal review but for now we're going ahead and pretend it's approved :-)
