### ISSUE TITLE
Move Span APIs that allow shipping visibility checks to MemoryMarshal

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#27094]
`BinaryPrimitives.TryReadMachineEndian` or `MemoryExtensions.AsBytes` APIs are an inherently "unsafe" API in the sense that they allow bypassing visibility checks. They allow creating structs with invalid content that can lead to unexpected behaviors. An example of such unexpected behavior is buffer overrun described in https://github.com/dotnet/coreclr/issues/16336 .

Should we move these APIs to System.Runtime.InteropServices.MemoryMarshal to be together with other unsafe APIs that one has to be very careful about using?

**Comment by KrzysztofCwalina** [comment]
If AsBytes returned ReadOnlySpan it would be safe, wouldn't it?

**Comment by GrabYourPitchforks** [comment]
> If AsBytes returned ReadOnlySpan it would be safe, wouldn't it?

No. This is still unverifiable. It's the equivalent of performing private reflection over the target type's fields and calling `FieldInfo.GetValue(...)` over and over. Even if you're not manipulating the structure directly, you're still reading raw data in a manner that the type author never intended (and probably didn't guarantee to remain stable), so you as the caller don't have the context necessary to _act_ on the data safely. And if you're not intending to act on the data, why read it in the first place?

peverify.exe would flag this as a type safety violation, even if it's just read-only. We should consider moving the whole implementation to a known-unsafe interop type.

**Comment by ahsonkhan** [comment]
Similar to https://github.com/dotnet/coreclr/issues/16336, the following code will cause a crash on full framework:
```C#
var random = new Random();
var decArray = new byte[16];
random.NextBytes(decArray);
decimal decimalVal = BinaryPrimitives.ReadMachineEndian<decimal>(decArray);
Console.WriteLine(decimalVal);
```

**Here is the proposed API change (moving the APIs):**
```C#
namespace System
{
    public static partial class MemoryExtensions
    {
        - public static ReadOnlySpan<byte> AsBytes<T>(this ReadOnlySpan<T> source) where T : struct { }
        - public static Span<byte> AsBytes<T>(this Span<T> source) where T : struct { }
    }
}
namespace System.Buffers.Binary
{
    public static partial class BinaryPrimitives
    {
        - public static T ReadMachineEndian<T>(ReadOnlySpan<byte> buffer) where T : struct { }
        - public static bool TryReadMachineEndian<T>(ReadOnlySpan<byte> buffer, out T value) where T : struct { }
        - public static bool TryWriteMachineEndian<T>(Span<byte> buffer, ref T value) where T : struct { }
        - public static void WriteMachineEndian<T>(Span<byte> buffer, ref T value) where T : struct { }
    }
}
namespace System.Runtime.InteropServices
{
    public static partial class MemoryMarshal
    {
        // Note: No longer extension method
        + public static ReadOnlySpan<byte> AsBytes<T>(ReadOnlySpan<T> source) where T : struct { }
        + public static Span<byte> AsBytes<T>(Span<T> source) where T : struct { }
        + public static T ReadMachineEndian<T>(ReadOnlySpan<byte> buffer) where T : struct { }
        + public static bool TryReadMachineEndian<T>(ReadOnlySpan<byte> buffer, out T value) where T : struct { }
        + public static bool TryWriteMachineEndian<T>(Span<byte> buffer, ref T value) where T : struct { }
        + public static void WriteMachineEndian<T>(Span<byte> buffer, ref T value) where T : struct { }
    }
}
```

**Comment by jkotas** [comment]
`MachineEndian` in the name may be unnecessary for non-extension methods on MemoryMarshal. Maybe just call them `MemoryMarshal.Read/Write` ?

**Comment by ahsonkhan** [comment]
> `MachineEndian` in the name may be unnecessary for non-extension methods on MemoryMarshal. Maybe just call them `MemoryMarshal.Read/Write` ?

Since we are moving it to MemoryMarshal, simplifying the name doesn't get us much. Also, explicitly stating `MachineEndian` hints at why these APIs are different rather than simply calling them Read/Writes.

cc @KrzysztofCwalina

**Comment by jkotas** [comment]
Well, `AsBytes` or `Cast` do the operation in machine-endianess context as well.

Compare:

```
ReadOnlySpan<byte> span = ....
int x = MemoryMarshal.ReadMachineEndian(span);
```
vs.
```
ReadOnlySpan<byte> span = ...
int x = MemoryMarshal.Cast<byte,int>(span)[0];
```

Why did you put machine endianess in my face for the first one, but not for the second one? The naming does not feel consistent.

**Comment by ahsonkhan** [comment]
> Why did you put machine endianess in my face for the first one, but not for the second one? The naming does not feel consistent.

Good point. I am fine with simplifying the name to remain consistent. Krzysztof, Immo, any objections? cc @terrajobst

**Comment by KrzysztofCwalina** [comment]
I am ok with either naming/design

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/dotnet/coreclr/pull/17106 / https://github.com/dotnet/corefx/pull/28460 / https://github.com/dotnet/coreclr/pull/17214 / https://github.com/dotnet/coreclr/pull/17245 / https://github.com/dotnet/corefx/pull/28515
