### ISSUE TITLE
Update inbox data for UAP 6

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#27100]
A number of assemblies shipped inbox in `release/uwp6.0` (10.0.15138), but have been rev'ed in master and ship ref-assms that would apply to UAP.

This will cause a ref-def mismatch if we don't include the implementation assembly for UAP in the package.

We need to make sure to update the packageIndex in to account for this and then ensure that the current packages validate cleanly (either rolling back reference assembly versions or adding UAP runtime assemblies to fix errors).

This **must** be done before we ship the packages again.  Ideally it's done before we ship a preview of the packages, so that we don't break folks if we decide to roll-back reference assembly versions.

/cc @joperezr @weshaggard

**Comment by weshaggard** [comment]
Fixed with https://github.com/dotnet/corefx/pull/27787.
