### ISSUE TITLE
Test under "System.Tests.EnvironmentTests" failed with "System.ArgumentOutOfRangeException"

### ISSUE THREAD

**Issue by Sunny-pu** [dotnet/corefx#27114]
The test System.Tests.EnvironmentTests.WorkingSet_Valid has failed.

MESSAGE:
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
+++++++++++++++++++
STACK TRACE:
at System.Environment.get_WorkingSet() at System.Tests.EnvironmentTests.WorkingSet_Valid() in /mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_release/src/System.Runtime.Extensions/tests/System/EnvironmentTests.cs:line 180

Details: https://ci.dot.net/job/dotnet_corefx/job/master/job/rhel7.2_release/5053/testReport/System.Tests/EnvironmentTests/WorkingSet_Valid/

**Comment by danmosemsft** [comment]
Not clear where this AOORE comes from. The test would throw an XunitException. I can't see anywhere the implementation could throw AOORE. Would need someone to get on a repro box.

**Comment by danmosemsft** [comment]
repro job https://ci.dot.net/job/dotnet_corefx/job/master/job/rhel7.2_release/5060/

**Comment by danmosemsft** [comment]
Looping the test overnight on RHEL7.2

**Comment by danmosemsft** [comment]
I could not repro this. Let's see if it happens again: if so we may consider instrumentatoin.
