### ISSUE TITLE
SocketsHttpHandler: Consider exposing a setting for Expect: 100-continue timeout

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#27145]
This is hardcoded to 1 second today.  We should consider exposing a setting to control this.

API proposal:

```C#
public sealed class SocketsHttpHandler
{
    public TimeSpan Expect100ContinueTimeout { get; set; } // Default is 1 second, as today
}
```

**Comment by geoffkizer** [comment]
As part of this, we should make sure we've got the right default here.  Current default is 1 second.  WebRequestHandler uses 350 milliseconds.  I don't have a great sense for what makes sense here.

**Comment by stephentoub** [comment]
> Current default is 1 second

FWIW, I chose that because that's what libcurl uses as the default:
https://curl.haxx.se/libcurl/c/CURLOPT_EXPECT_100_TIMEOUT_MS.html
