### ISSUE TITLE
BasicEventSourceTests failing in non elevated Windows runs

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#27147]
cc @brianrob 

Not all our Windows test runs are elevated. Tests need to pass non elevated.

```
BasicEventSourceTests.FuzzyTests.Test_Write_Fuzzy | 35 ms | 10
-- | -- | --
BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_ComplexData_SelfDescribing_ETW | 0 ms | 10
BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_SelfDescribing_ETW | 0 ms | 10
BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_Manifest_ETW | 0 ms | 10
BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_ByteArray_Manifest_ETW | 0 ms | 10
BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_ByteArray_SelfDescribing_ETW | 0 ms | 10
BasicEventSourceTests.TestsWrite.Test_Write_T_ETW | 0 ms | 10
BasicEventSourceTests.TestsUserErrors.Test_BadEventSource_MismatchedIds
```
eg 
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug/lastCompletedBuild/testReport/BasicEventSourceTests/FuzzyTests/Test_Write_Fuzzy/

They are all failing this way
```
MESSAGE:
System.Exception : Need to be elevated to run.
+++++++++++++++++++
STACK TRACE:
at BasicEventSourceTests.EtwListener..ctor(String dataFileName, String sessionName) in D:\j\workspace\windows_nt_debug88592b53\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\Harness\Listeners.cs:line 170 at BasicEventSourceTests.FuzzyTests.Test_Write_Fuzzy() in D:\j\workspace\windows_nt_debug88592b53\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\FuzzyTests.cs:line 2751
```

Fix seems to be to change all these to have `[ConditionalFact(nameof(IsProcessElevated))]`

**Comment by brianrob** [comment]
Thanks @danmosemsft, I will fix this.  There is a break in perf runs due to an upgraded TraceEvent package so I am disabling these tests until I can fix the updated TraceEvent package.  See #27141.  I'll fix this as part re-enabling them.

**Comment by brianrob** [comment]
@danmosemsft is there a programmatic way to detect if the process is elevated?  A number of the ETW tests are mixed into EventListener tests and so I don't want to disable the entire test if I don't have to.

**Comment by danmosemsft** [comment]
`AdminHelpers.IsProcessElevated()`

you may wrap in a helper like this one I see
`public static bool IsElevatedAndSupportsEventLogs { get => AdminHelpers.IsProcessElevated() && SupportsEventLogs; }`

**Comment by brianrob** [comment]
Great.  Thank you.
