### ISSUE TITLE
System.Security.Cryptography.Hashing.Algorithms contract reference is forwarding

### ISSUE THREAD

**Issue by lleraromero** [dotnet/corefx#2715]
Hi,

It seems that in System.Security.Cryptography.Hashing.Algorithms v4.0.0-beta-23127 all types are being forwarded, even though they are implemented in corefx. Is there any reason for this change or is it a mistake?

Thanks.

**Comment by joshfree** [comment]
@bartonjs

**Comment by bartonjs** [comment]
@lleraromero System.Security.Cryptography.Hashing.Algorithms isn't going to ship; it was merged into System.Security.Cryptography.Algorithms (along with some other packages).  So it's type-forwarding right now as a beta-to-beta upgrade path; we'll stop publishing the forwarding package after beta7.

**Comment by bartonjs** [comment]
Quick cheat sheet:
```
System.Security.Cryptography.Encryption            => System.Security.Cryptography.Primitives
System.Security.Cryptography.Hashing               => System.Security.Cryptography.Primitives

System.Security.Cryptography.RandomNumberGenerator => System.Security.Cryptography.Algorithms
System.Security.Cryptography.Encryption.Aes        => System.Security.Cryptography.Algorithms
System.Security.Cryptography.Hashing.Algorithms    => System.Security.Cryptography.Algorithms
System.Security.Cryptography.DeriveBytes           => System.Security.Cryptography.Algorithms

The only partitioned library was System.Security.Cryptography.RSA:
  The RSA base class and supporting types                            => System.Security.Cryptography.Algorithms
  The RSACryptoServiceProvider class and additional supporting types => System.Security.Cryptography.Csp
  The internal RSAOpenSsl type was made public                       => System.Security.Cryptography.OpenSsl
  RSACng was copied from desktop                                     => System.Security.Cryptography.Cng
```

Excerpt from https://github.com/dotnet/corefx/commit/ce0506baea623efdb74707aee0e4aa169d6f468c.

**Comment by bartonjs** [comment]
Since this was intentional, I'm going to go ahead and close the issue; if it's breaking something please re-activate.
