### ISSUE TITLE
Use shared IO helper code from CoreCLR

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#27155]
Common IO source code helpers were copied to CoreCLR some time ago. Now that we are mirroring, we should switch to using the mirrored code. There has been quite a bit of drift, so it might take some effort.

src/Common/src/System/IO/PathInternal.Windows.cs -> src/Common/src/CoreLib/System/IO/PathInternal.Windows.cs

https://github.com/dotnet/corefx/pull/27150#discussion_r168377623

**Comment by danmosemsft** [comment]
If you ignore style etc there doesn't seem much divergence. Do you see anywhere in the diff where we should not take the corelib one?

**Comment by JeremyKuhne** [comment]
We might want to factor into more files to avoid pulling in more code than we need for some of the usages. Span stuff is a little weird too- we need to follow up on if/how we use System.Memory extensions in System.Runtime.Extensions. I presume we are going to continue to ship a System.Memory for .NET Standard with it's official release? E.g. can we take a reference from our .NET Standard System.IO.Ports?

**Comment by JeremyKuhne** [comment]
We should probably double down on using the common test project to unit test internal helpers. Some of what I removed in #27150 can probably be reused.

**Comment by JeremyKuhne** [comment]
This is mostly done. Just need to hunt down and update the rest of the usages.

**Comment by JeremyKuhne** [comment]
This has been done.
