### ISSUE TITLE
ImmutableArray<byte> .Concat() includes a number of trailing zeroes not present in either argument

### ISSUE THREAD

**Issue by jameswilddev** [dotnet/corefx#27161]
.NET Command Line Tools 2.0.2

Hello!  Found a weird problem today, been able to isolate it to the following code sample:

```C#
using Newtonsoft.Json;
using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace ArraySanitycheck
{
    class Program
    {
        public sealed class TestModel
        {
            public readonly string TestString;
            public readonly int TestNumber;

            public TestModel(string testString, int testNumber)
            {
                TestString = testString;
                TestNumber = testNumber;
            }
        }

        static void Main(string[] args)
        {
            var model = new TestModel("Test String Content", 268234);

            var bytes = Encoding.UTF8.GetBytes($"Test Purpose\0{JsonConvert.SerializeObject(model)}").ToImmutableArray();

            var a = bytes.TakeWhile(i => i != 0);
            var b = new byte[] { 0 };
            var c = bytes.SkipWhile(i => i != 0).Skip(1).Take(5);
            var d = new byte[] { 254 };
            var e = bytes.SkipWhile(i => i != 0).Skip(6);
            var concatenated = a.Concat(b).Concat(c).Concat(d).Concat(e);
        }
    }
}
```

Set a breakpoint on the closing brace following `var concatenated...` and inspect `concatenated`.  It ends with approximately 15 zeroes.

Note that none of a, b, c, d or e include said zeroes.

Weirdly, attempting to write this data to the console (`Console.WriteLine(string.Join(", ", concatenated));`) does not include the zeroes either.  

I suspect this may be an issue with how TakeWhile/SkipWhile perform "slices" of the underlying array (the length of the concatenated array is the same as the length of the sliced array).

**Comment by svick** [comment]
This sounds like it could be a duplicate of https://github.com/dotnet/corefx/issues/23833 / https://github.com/dotnet/corefx/issues/23680. As far as I can tell from https://github.com/dotnet/corefx/pull/23865, that bug has been fixed in .Net Core 2.0.3. What version of .Net Core runtime are you using? If it's older than 2.0.3, can you update and try again?

**Comment by jameswilddev** [comment]
Sorry it took me a while to test on a newer version, but it does indeed appear this was fixed by the latest version.  Thanks!
