### ISSUE TITLE
Remove Commit from PipeWriter

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#27162]
Commit was originally added because to allow an opportunistic pick up of data by the reader if it's already reading but it doesn't give any back pressure and can be a pit of failure in some cases. Originally, it was required when we had the requirement to Alloc() then Commit() but that requirement has been relaxed. On top of that the scenarios it was added for were a bit ill defined and we should remove it from the PipeWriter class.

/cc @benaadams @pakrym

**Comment by benaadams** [comment]
Also add `source = default` to `WriteAsync` so the use of `Commit` can still be maintained
```diff
public abstract class PipeWriter
{
- public abstract void Commit();
- public virtual PipeAwaiter<FlushResult> WriteAsync(ReadOnlyMemory<byte> source, CancellationToken cancellationToken = default)
+ public virtual PipeAwaiter<FlushResult> WriteAsync(ReadOnlyMemory<byte> source = default, CancellationToken cancellationToken = default)
}
```


```csharp
public async Task Write15LinesAsync()
{
    PipeWriter buffer = Pipe.Writer;
    var length = 'z' - 'a' + 3;
    for (var i = 0; i < 15; i++)
    {
        WriteAtoZ(buffer.GetMemory(length));
        buffer.Advance(length);
        await buffer.WriteAsync(); // Write data
    }
    await buffer.FlushAsync();
}

public int WriteAtoZ(Memory<byte> memory)
{
    Span<byte> span = memory.Span;
    var i = 0;
    for (var c = 'a'; c <= 'z'; c++)
    {
        span[i] = (byte)c;
        i++;
    }
    span[i + 1] = (byte)'\r';
    span[i + 2] = (byte)'\n';

    return i + 2;
}
```

**Comment by benaadams** [comment]
> So signaling will be done via flashing?

Commit doesn't signal which is one of the problems with it

**Comment by benaadams** [comment]
Related "Add IsFlush to Pipelines ReadResult" https://github.com/dotnet/corefx/issues/27168
