### ISSUE TITLE
CurlHandler allows invalid headers as long as they contain a colon

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#27172]
WinHttpHandler, SocketsHttpHandler, and the netfx all disallow response headers like:

- "   :    "
- ":"
- "\x1234: \x5678"

but CurlHandler allows them... as long as there's a colon it's happy.

**Comment by stephentoub** [comment]
Both libcurl and CurlHandler are fine with such response headers.  Technically it's a bug in CurlHandler that we don't prohibit this and behave like the other handlers.  But I'm fine punting on it.  I would love to get rid of CurlHandler entirely in the near future.

**Comment by davidsh** [comment]
Future investments will be in SocketsHttpHandler and CurlHandler will be removed at some point from the branch. So, it doesn't make sense to try to "fix" this.
