### ISSUE TITLE
Need tests for 2.0<->2.1 binary serialization roundtripping

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#27179]
We currently test 2.1<->2.1 and 2.1<->NETFX. We also need to verify 2.1<->2.0 works.

If we add a new set of canned binary blobs, copy and pasted from the 2.0 servicing branch, we can test 2.0->2.1 with trivial extension of existing mechanisms. To test 2.1->2.0 we would need 2.0 on our test machines, and it isn't there. However it's sufficient to only do that occasionally by hand, and no more often than we update the 2.1 binary blobs, since 2.0 isn't changing.

@ViktorHofer can you formalize a plan and then someone can work on it?

**Comment by danmosemsft** [comment]
cc @Anipik

**Comment by ViktorHofer** [comment]
> To test 2.1->2.0 we would need 2.0 on our test machines, and it isn't there. 

Do we have other areas where we need to test compatibility between 2.0 and 2.1? The ideal situation would be to be able to run the tests with `TargetGroup=netcoreapp2.0` but I guess adding targets for each .NET Core version going forward is not very flexible and would require the 2.0 SDK installed.

> we can test 2.0->2.1 with trivial extension of existing mechanisms

Correct. I just looked at the code and it seems only minor changes are necessary. This line needs to be changed: https://source.dot.net/#System.Runtime.Serialization.Formatters.Tests/BinaryFormatterTests.cs,86

If `blobs.Length == 3` we have a 2.1 blob. So I would change the condition to `PlatformDetection.IsFullFramework ? 1 : (blobs.Length == 3 ? 2 : 1)`. This is the short and hacky way. I would move that line into its own function and pass the blob length to it.

> However it's sufficient to only do that occasionally by hand, and no more often than we update the 2.1 binary blobs, since 2.0 isn't changing.

Correct, @Anipik already did this for his recent changes.

**Comment by ViktorHofer** [comment]
@Anipik can you please add the necessary changes into your existing PR? This is required to make 2.1 blobs work correctly.

**Comment by Anipik** [comment]
@ViktorHofer I will make the necessary changes to my PR. Do we need to make any other changes to any other object in that binarytestarray as currently ```index 0``` is for netcoreapp2.0

**Comment by ViktorHofer** [comment]
index 0 means netcoreapp2.0 or the latest version of netcoreapp if there is no blob at index 2. You can define the logic in that function which returns the platformBlobIndex.

**Comment by danmosemsft** [comment]
> Do we have other areas where we need to test compatibility between 2.0 and 2.1? The ideal situation would be to be able to run the tests with TargetGroup=netcoreapp2.0 but I guess adding targets for each .NET Core version going forward is not very flexible and would require the 2.0 SDK installed.

@weshaggard @karelz @jfree for this question. I am not aware of other areas where we need to test compatibility with 2.0. if it's just binary serializatoin then I think it's best to just add new canned blobs in those tests. The alternative would be a lot of work: update docker files, take a new dependency on dev machines potentially, maybe new test configuration ,..

**Comment by weshaggard** [comment]
We don't really have other areas. 

Why wouldn't the round tripping with netfx be enough to cover these scenarios? Are there cases were we aren't compatible there but we want to be between netcoreapp2.0 and 2.1?

If we do need these tests I suspect the best way is to capture the output which represents the canonical form and test against that. I believe we already do something similar for our other serializers.

**Comment by danmosemsft** [comment]
> Why wouldn't the round tripping with netfx be enough to cover these scenarios? 

It is possible if
* We have new [Serializable] types in .NET Core that aren't so in NETFX. (I can't think of any)
* Some version tolerance is required., eg say 2.1 changes the semantics of a field, NETFX deserialization is tolerant of the change but 2.0 is not. (Again, don't have a concrete example)

Since it is a firm commitment that we support 2.0<->2.1 serialization it makes me a little uncomfortable to not directly test it given how complex binary serialization is.

**Comment by weshaggard** [comment]
>Since it is a firm commitment that we support 2.0<->2.1 serialization it makes me a little uncomfortable to not directly test it given how complex binary serialization is.

While it seems simple for 2.0 <-> 2.1 just to add the extra test runs it isn't going to scale in the long run. So I think we need to use some sort of proxy, perhaps that is just some checked in serialization blobs that cannot be changed overtime.

**Comment by danmosemsft** [comment]
@weshaggard I don't think we'd add 2.x indefinitely. It would always be 2.0 (or the oldest that supported the object being serialized), netfx, and head. Taht seems to give reasonable coverage.
