### ISSUE TITLE
No easy way to see if FileStream.Lock is supported

### ISSUE THREAD

**Issue by mstum** [dotnet/corefx#27192]
On OS X, FileStream.Lock throws a PlatfomNotSupportedException.

There's no easy way to know if a given Platform supports this apart from either hardcoding a list of Platforms, or trying to do it and catching the Exception.

Streams have methods like CanRead/CanWrite/CanSeek to allow developers to verify if something _could_ work before doing it.

I'd like to propose a new static property on FileStream named like `SupportsLocking` than can be cheaply checked, even before creating the FileStream (as the result of this might influence the `FileMode` etc. arguments).

A proposal is [in this commit](https://github.com/mstum/corefx/commit/a9dd5fe07e101807ea0a950ddf9edc9afc3d10ee).

**Comment by danmosemsft** [comment]
@mstum we welcome API proposals. Can you please start by formatting as described in https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md ?

**Comment by mstum** [comment]
Thanks, I'll close this for now and re-open once I wrote it up in the correct format.
