### ISSUE TITLE
Error with PostAsync

### ISSUE THREAD

**Issue by Ginrey** [dotnet/corefx#27207]
if you use this code in the .net core 1-2 then it gives an error with code 400. If you use the same code in .netframework, then everything passes successfully with code 200. Test on windows. Why error?

`  class Program
    {
        private const string ProjectID = "61";
        private const string SubProjectId = "0";
        private const string ShardId = "0";
        private const string UserId = "6918200764865613899";
        private const string UserId2 = "7816681534978888932";

        private static string XML(string name, string username, string password)
        {
            return string.Format("<?xml version=\"1.0\" encoding=\"UTF-8\"?><{0} ProjectId=\"{1}\" SubProjectId=\"{2}\" ShardId=\"{3}\" UserId=\"{4}\" UserId2=\"{5}\" Username=\"{6}\" Password=\"{7}\" />", name, ProjectID, SubProjectId, ShardId,
            UserId, UserId2, username, password);
        }

        static void Main(string[] args)
        {
            HttpClient hc = new HttpClient();
            ServicePointManager.ServerCertificateValidationCallback += (o, certificate, chain, errors) => true;
            hc.DefaultRequestHeaders.Add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.9 Downloader/12820 MailRuGameCenter/1282 Safari/537.36");
            hc.DefaultRequestHeaders.Add("Accept", "*/*");
            var post = XML("Auth", "artem.rizenkov@gmail.com", "XNCCFCWA");
            var result = hc.PostAsync("https://authdl.mail.ru/sz.php?hint=Auth", new StringContent(post, Encoding.UTF8, "application/x-www-form-urlencoded")).GetAwaiter().GetResult();
        }
    }`

**Comment by stephentoub** [comment]
HttpClient in .NET Core doesn't pay attention to ServicePointManager, so your request isn't picking up the delegate set as ServicePointManager.ServerCertificateValidationCallback.

Try changing:
```
HttpClient hc = new HttpClient();
ServicePointManager.ServerCertificateValidationCallback += (o, certificate, chain, errors) => true;
```
to:
```
var handler = new HttpClientHandler();
handler.ServerCertificateCustomValidationCallback = delegate { return true; }
var hc = new HttpClient(handler);
```

cc: @davidsh

**Comment by Ginrey** [comment]
I changed it to what you said, but nothing has changed.

**Comment by davidsh** [comment]
>if you use this code in the .net core 1-2 then it gives an error with code 400.

Are you saying that you get an HTTP response with StatusCode of 400 instead of 200?  If you're getting an HTTP response at all it means that the TLS/SSL connection is working fine. So, the problem is probably something else and not related to the ServerCertificateValidationCallback.

**Comment by stephentoub** [comment]
> If you use the same code in .netframework, then everything passes successfully with code 200.

FWIW, I just ran the code on .NET Framework (.NET 4.7), and it results in a 400 status code for me, not 200.

**Comment by Ginrey** [comment]
Here are 2 requests via framework (true), net.core (false)
![falseheader](https://user-images.githubusercontent.com/16057233/36321870-607f9d1a-135c-11e8-9d2e-31aeee1887c6.jpg)
![falsepost](https://user-images.githubusercontent.com/16057233/36321871-60b65e04-135c-11e8-84d2-88e88663ecd3.jpg)
![falseresp](https://user-images.githubusercontent.com/16057233/36321873-60efa88a-135c-11e8-96a7-a573f982ac5b.jpg)
![trueheader](https://user-images.githubusercontent.com/16057233/36321875-61b795fc-135c-11e8-8a88-684aef8e52a6.jpg)
![truepost](https://user-images.githubusercontent.com/16057233/36321876-61e7eb08-135c-11e8-97f9-cc72db1cfaff.jpg)
![trueresp](https://user-images.githubusercontent.com/16057233/36321877-6220600a-135c-11e8-86e3-b2cd6bf60f84.jpg)

**Comment by Ginrey** [comment]
I tried using WebClient and it all worked. Why does not HttpClient work?

**Comment by davidsh** [comment]
Looking at the traces you posted above, there is a difference in the HTTP request header for the 'Content-Type' header.

For the case that works, this is the header:
![image](https://user-images.githubusercontent.com/7684835/36337147-cb87b772-1344-11e8-92db-17fc23a95a91.png)

For the case that does not work, this is the header:
![image](https://user-images.githubusercontent.com/7684835/36337153-dbc73144-1344-11e8-9df4-eb2bd39f4a5a.png)

So, perhaps the server can't handle getting the extra parameter "charset=windows-1251" in the 'Content-Type' request header.  That might explain why you are getting back a 400 (Bad Request) response code from the server.

As a test, you could write some code to delete that request header and re-add the header back without the part "charset=windows-1251".

**Comment by davidsh** [comment]
And i do see that you didn't explicitly set the charset parameter in the string content:

```c#
new StringContent(post, Encoding.UTF8, "application/x-www-form-urlencoded")
```
There is an issue in CoreFx that talks about that particular problem.

**Comment by Ginrey** [comment]
I tried change encoding, but dont work

**Comment by davidsh** [comment]
>I tried change encoding, but dont work

Do you have access to the server?  Perhaps you can determine why the server is sending back a 400 Bad Request HTTP statuscode?

**Comment by davidsh** [comment]
We are not able to reproduce this problem.  If this still happens on latest .NET Core, please re-open the issue and also attach a full Visual Studio solution containing the repro code. It would be best if the solution could be easily built with F5 and run-able to reproduce the bug.
