### ISSUE TITLE
ReadOnlySequence with empty array returns wrong SequencePosition

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#27224]
```
var buffer = new ReadOnlySequence<byte>(new byte[0]);
Console.WriteLine(buffer.Start.Index);
Console.WriteLine(buffer.End.Index);
```

This prints:

0
-2147483648

It should print:

0
0

/cc @KrzysztofCwalina @pakrym @ahsonkhan

**Comment by ahsonkhan** [comment]
It has to do with the bitmasking:
https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/Buffers/ReadOnlySequence.cs#L122

```C#
 _sequenceEnd = new SequencePosition(array, start + length | ArrayEndMask);
```

0 | (1 << 31) => -2147483648

We need to get rid of that mask before that property is accessed (everywhere).

**Comment by pakrym** [comment]
It's not a bug, SequencePosition properties should not be interpreted outside ReadOnlySequence.
Maybe we need to make them private again.

That's why I filed https://github.com/dotnet/corefx/issues/27097

**Comment by pakrym** [comment]
Not a bug

**Comment by benaadams** [comment]
Run to api review; while its still going ;)
