### ISSUE TITLE
Remove USE_OVERLAPPED from FileSystem

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#2722]
We now have a overlapped implementation that works on UWP so we should remove the USE_OVERLAPPED ifdefs.

**Comment by joshfree** [comment]
@ianhays can you take a look during B8?

**Comment by ianhays** [comment]
Sure thing! Just to clarify, we want to remove all code within the USE_OVERLAPPED blocks i.e. assume USE_OVERLAPPED=false always?

**Comment by ericstj** [comment]
no, the opposite.  USE_OVERLAPPED should always be **true** now.

**Comment by ianhays** [comment]
Sounds good, glad I checked first :) Will do.
