### ISSUE TITLE
Consider adding MemoryMarshal.GetOwner(ROM)

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#27237]
```csharp
public static partial class MemoryMarshal
{
    public static object GetOwner(ReadOnlyMemory<T> readOnlyMemory)
}
```

With Registered IO; when sending an receiving data the api doesn't use `address`, `offset`, `length`; it uses `id`, `offset`, `length`

The `id`s are assigned upfront when you register the addresses (once)

Currently you have to [loop through all the registered](https://github.com/dotnet/corefxlab/blob/ec47e7023bcd45fb40c4468f5b1234b33f14ffe4/src/System.IO.Pipelines.Networking.Windows.RIO/Internal/RioThread.cs#L95-L117) memory blocks to find which one matches and then get its `id` which is inefficient and also has to protect against concurrency of new memory being registered while its searching.

This search and registration blocking could be avoided with the new api
```csharp
if (GetOwner(readOnlyMemory) is RioMemoryPoolBlock block)
{
    var idToUse = block.Id;
}
else
{
    // Not registered memory, get registered memory block and copy data
}
```

/cc @davidfowl @KrzysztofCwalina

**Comment by Drawaes** [comment]
Nice this could aid in future APIs as well such as append that might only work if the buffer is from the same pool. Or might just avoid a copy

**Comment by benaadams** [comment]
You could just return Owner; then if its `string` or `T[]` you can do pattern matching on `object`

**Comment by terrajobst** [comment]
We believe this API would slightly better and would be more consistent:

```C#
namespace System.Runtime.InteropServices
{
    public static class MemoryMarshal
    {
        public static bool TryGetOwnedMemory<T, TOwner>(ReadOnlyMemory<T> readOnlyMemory, out TOwner ownedMemory)
           where TOwner: OwnedMemory<T>;
        public static bool TryGetOwnedMemory<T, TOwner>(ReadOnlyMemory<T> readOnlyMemory, out TOwner ownedMemory, out int index, out int length)
           where TOwner: OwnedMemory<T>;
    }
}
```

**Comment by benaadams** [comment]
Could do object for pattern matching
```csharp
public static partial class MemoryMarshal
{
    public static object GetOwner(ReadOnlyMemory<T> readOnlyMemory, out TOwner owner,
                                         out int offset, out out lengthy)
    public static bool TryGetOwner(ReadOnlyMemory<T> readOnlyMemory, out TOwner owner,
                                         out int offset, out out length)
}
```

**Comment by KrzysztofCwalina** [comment]
This needs to be implemented and merged by 2/28, otherwise it might not make it into 2.1.
Also, I am setting the label to up for grabs :-)

**Comment by KrzysztofCwalina** [comment]
that was quick :-)

**Comment by davidfowl** [comment]
Nice! Now we get that hack out of the RIO memory pool

**Comment by benaadams** [comment]
Is still open; coreclr closed it; still need the corefx part merged. The process to follow :)

**Comment by benaadams** [comment]
Is in now though 😄
