### ISSUE TITLE
Consumptive perf metrics failing, cannot find the event tracer

### ISSUE THREAD

**Issue by mmitche** [dotnet/corefx#2723]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_perf_consumptive_windows/79/

The command ""d:\j\workspace\dotnet_corefx_perf_consumptive_windows\packages\Microsoft.DotNet.PerfTools\0.0.1-prerelease-00022\tools\EventTracer.exe" -m start -t System.Collections.Specialized.Tests.dll -d System.Collections.Specialized.Tests.dll.etl -c GCSampledObjectAllocationHigh,GCSampledObjectAllocationLow -k ImageLoad" exited with code 3.

**Comment by joshfree** [comment]
@ianhays @ericeil

**Comment by ianhays** [comment]
No idea what this is. @mellinoe, @jhendrixMSFT any context?

**Comment by mellinoe** [comment]
Seems to be related to the old perf tools, which we don't use now.

**Comment by ianhays** [comment]
Thought so, thanks. Going to close it then.
