### ISSUE TITLE
Consider making a property-based testing library available for tests.

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#27234]
Consider making a property-based testing library, such as [FsCheck](https://github.com/fscheck/FsCheck), available for use in testing.

In particular, [model-based testing](https://fscheck.github.io/FsCheck/StatefulTesting.html) would be useful for dealing with things like the [XML.LINQ](https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml.Linq/tests/events/EventsAdd.cs) property tests, making it easier to write combinatorial tests that search through more possibilities.

Now, it's true that FsCheck, like most libraries based on Quickcheck, normally use a random seed on each run; this is considered a feature.  However, they all explicitly include the failing seed for any failing test in the output, and this can be included in the config for the test (meaning regression tests can be automatically re-run)

**Comment by stephentoub** [comment]
Thanks for the suggestion.  If the need presented itself, we could certainly choose to use some library to assist with testing at that point.  But I don't think we need an issue tracking doing so.
