### ISSUE TITLE
Add HMACMD5 to System.Security.Cryptography.Algorithms

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#2724]
HMACMD5 was omitted during the contract creation, it should be added (back).

**Comment by antonmes** [comment]
Is it available for DNXCore?
```
DNXCore,Version=v5.0 error CS0246: The type or namespace name 'HMACMD5' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by bartonjs** [comment]
@antonmes Well, it made it into the implementation library; but apparently didn't get added to the contract library (or something went wrong during the move of the contract libraries to github).
