### ISSUE TITLE
ValueWebSocketReceiveResult is missing CloseStatus and CloseStatusDescription

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#27257]
I tried replacing ReceiveAsync(ArraySegment\<byte\>) with the Memory\<byte\> overload only to notice these missing properties.

https://github.com/dotnet/corefx/blob/643bccc7f2c24a897cc15c42486d4184e1f931eb/src/System.Net.WebSockets/src/System/Net/WebSockets/WebSocketReceiveResult.cs#L34-L38

https://github.com/dotnet/corefx/blob/643bccc7f2c24a897cc15c42486d4184e1f931eb/src/System.Net.WebSockets/src/System/Net/WebSockets/ValueWebSocketReceiveResult.cs#L32-L34

Is there a reason for this?

/cc @stephentoub

**Comment by benaadams** [comment]
`WebSocketMessageType == close` then use the `CloseStatus` and `CloseStatusDescription` properties on the `WebSocket`?

Bit wasteful to be adding `null enum` and `null string` to every result of an open socket?

**Comment by davidfowl** [comment]
Sure, if it's functionally equivalent. Do those properties update as soon as a close frame is received?

**Comment by stephentoub** [comment]
> Do those properties update as soon as a close frame is received?

Yes.  When ReceiveAsync receives a close message, it calls HandleReceivedCloseAsync:
https://github.com/dotnet/corefx/blob/643bccc7f2c24a897cc15c42486d4184e1f931eb/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L684-L688
and it sets the close status and description:
https://github.com/dotnet/corefx/blob/643bccc7f2c24a897cc15c42486d4184e1f931eb/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L813-L815
so they're populated before the task that's returned from ReceiveAsync completes.

**Comment by davidfowl** [comment]
I'll close this then. Seems to work fine.
