### ISSUE TITLE
Using Trusted Root Certification Authorities for server certificate validation in HttpClient

### ISSUE THREAD

**Issue by mfrankk** [dotnet/corefx#27256]
I have created a self-signed certificate using 

`    openssl req -x509 -newkey rsa:2048 -keyout https-key.pem -out https.pem -days 365`

then I created pkcs12 using (I have set the CN to my server's ip adress):

`    openssl pkcs12 -export -out https.pfx -inkey https-key.pem -in https.pem -password pass:123456`

In my server a use the generated `https.pfx` file for https.

In my client I imported the generated certificate into the Windows' `Trusted Root Certification Authorities` (Current user and also local system).

When I send a HTTP request to the server from my client, I get 

```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A security error occurred
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
       at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
       --- End of inner exception stack trace ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
       at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task).
```

In chrome it says:

    Attackers might be trying to steal your information from *** (for example, passwords, messages, or credit cards). NET::ERR_CERT_AUTHORITY_INVALID

Does .NET Core 2.0's `HttpClient` use Windows certificate stores? What could be causing the issue.

**Comment by davidsh** [comment]
cc: @bartonjs

**Comment by bartonjs** [comment]
> Does .NET Core 2.0's HttpClient use Windows certificate stores?

Yes.

>  What could be causing the issue.

I recommend registering the server validation callback, and looking at what errors are reported (both in the SslProtocolErrors enum and in the X509Chain object).

**Comment by davidsh** [comment]
>System.Net.Http.WinHttpException: A security error occurred

Getting that exception can happen for a variety of problems with the TLS/SSL connection including issues with the server TLS certificate.  When using a self-signed certificate, putting it into the local trusted roots store is not sufficient to prevent errors in the connection process.  Other errors like dates that are expired, DNS name mismatch, etc. can cause problems.

So, one way to troubleshoot this is to use the HttpClientHandler.ServerCertificateCustomValidationCallback property to register a callback as @bartonjs  suggested.

**Comment by davidsh** [comment]
@mfrankk Does this problem still happen for you?

I suspect that the certificate you are creating using OpenSsl is using a deprecated signing algorithm (like SHA1) by default.  That would explain why you are getting an error from HttpClient.

There is not enough information for us to troubleshoot this problem. If this is still occurring, please attach a copy of the PFX certificate you created as well as WireShark traces.  Thanks.
