### ISSUE TITLE
Proposal: Add new filters to the IntelliSense members list

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/corefx#27263]
IntelliSense allow to filter the members list by choosing to view or hide fields, properties, methods, and events.
These filters are not enough. I suggest to add two more filters:
-	Inherited: to show or hide inherited members.. It's useful specially with controls and custom controls, where the number of inherited members are huge.
-	Protected: to show or hide inherited members.. It's useful specially inside the form or custom controls blocks, where protected members appear.

**Comment by jnm2** [comment]
https://github.com/dotnet/roslyn/issues

**Comment by MohammadHamdyGhanem** [comment]
Done:
https://github.com/dotnet/roslyn/issues/24944
