### ISSUE TITLE
Add IPipeReader and IPipeWriter and have IDuplexPipe inherit from them

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#27268]
Allows determination of whether a Pipe-like is Readable, Writable or Both via the type system

Current API
```csharp
public interface IDuplexPipe
{
    PipeReader Input { get; }
    PipeWriter Output { get; }
}
```
Proposed API
```csharp
public interface IReadablePipe 
{
    PipeReader Input { get; }
}

public interface IWritablePipe 
{
    PipeWriter Output { get; }
}

public interface IDuplexPipe : IReadablePipe, IWritablePipe 
{}
```

Use case a Stream that is write only, but implemented on top of a Pipe
```csharp
public class HttpResponseStream : Stream, IWritablePipe 
{
    private readonly Pipe _pipe;
    PipeWriter IWritablePipe.Output => _pipe.Writer;

    public override async Task FlushAsync(CancellationToken cancellationToken)
        => await _pipe.Writer.FlushAsync(cancellationToken);

    public override Task WriteAsync(ReadOnlyMemory<byte> source, CancellationToken cancellationToken = default)
        => _pipe.Writer.WriteAsync(source, cancellationToken);
        
    public override Task WriteAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
        => WriteAsync(new Memory<byte>(buffer, offset, count), cancellationToken);
        
    public override Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
        => throw NotSupportedException();
        
    public override async ValueTask<int> ReadAsync(Memory<byte> destination, CancellationToken cancellationToken = default)
        => throw NotSupportedException();

    public override bool CanWrite => true;
    public override bool CanRead => false;
    public override bool CanSeek => false;
    
    // Other stream overloads
}
```
This means you can have TextWriters that work with Streams; however, if the Stream has a pipe it can encode on the go in WriteAsync with no internal buffers (using the Pipe's memory directly) rather than waiting for FlushAsync and either allocating buffers or pulling them from the ArrayPool; and then having an additional copy to pass onto the Stream e.g.
```csharp
public class HttpResponseStreamWriter : TextWriter
{
    internal const int DefaultBufferSize = 16 * 1024;

    private readonly PipeWriter _pipe;
    private readonly StreamWriter _streamWriter;
    private readonly Encoder _encoder;

    public PipeStreamWriter(Stream stream, Encoding encoding)
        : this(stream, encoding, DefaultBufferSize) {}

    public PipeStreamWriter(Stream stream, Encoding encoding, int bufferSize)
    {
        Encoding = encoding;
        if (stream is IWritablePipe pipe)
        {
            _pipe = pipe.Output;
        }
        else
        {
            _streamWriter = new StreamWriter(stream, encoding, bufferSize);
        }
    }

    public override Encoding Encoding { get; }

    public unsafe override void Write(char value)
    {
        if (_pipe != null)
        {
            Span<byte> bytes = _pipe.GetSpan(Encoding.GetMaxByteCount(1));
            var encoded = Encoding.GetBytes(new ReadOnlySpan<byte>(&value, sizeof(char)), bytes);
            _pipe.Advance(encoded);
        }
        else
        {
            _streamWriter.Write(value);
        }
    }

    public override Task WriteAsync(ReadOnlyMemory<char> source, cancellationToken = default) => 
        (_pipe != null) ? 
            _pipe.WriteAsyncImpl(source, cancellationToken) :
            _streamWriter.WriteAsync(source);

    private Task WriteAsyncImpl(ReadOnlyMemory<char> source, CancellationToken token)
    {
        ReadOnlySpan<char> input = source.Span;
        int minBytes = Encoding.GetMaxCharCount(1);
        while (input.Length > 0)
        {
            Span<byte> bytes = _pipe.GetSpan(minBytes);
            int totalEncoded = 0;
            while (bytes.Length > 0)
            {
                int toEncode = Math.Min(Encoding.GetMaxCharCount(bytes.Length), input.Length);
                var encoded = Encoding.GetBytes(input.Slice(0, toEncode), bytes);
                input = input.Slice(toEncode);
                bytes = bytes.Slice(encoded);
                totalEncoded += encoded;
                if (bytes.Length < minBytes)
                {
                    break;
                }
            }
            _pipe.Advance(totalEncoded);
        }
        
        return _pipe.WriteAsync(default);
    }

    public override Task WriteAsync(char[] values, int index, int count)
        => WriteAsync(new ReadOnlyMemory<char>(values, index, count));

    public override Task WriteAsync(string value)
        => WriteAsync(value.AsReadOnlyMemory());

    public override Task FlushAsync()
    {
        if (_pipe != null)
        {
            await _pipe.Output.FlushAsync();
        }
        else
        {
            await _streamWriter.FlushAsync();
        }
    }

    // Other TextWriter overloads
}
```

/cc @davidfowl @stephentoub @GrabYourPitchforks

**Comment by benaadams** [comment]
Is it possible to be considered for 2.1 as post 2.1 adding an inheritance hierarchy to the interface would be a breaking change an then would be like the `IList`, `IReadOnlyList` side by side situation... (rather than `IList : IReadOnlyList` 😢 ) and

```csharp
public interface IPipeReader 
{
    PipeReader Input { get; }
}

public interface IPipeWriter 
{
    PipeWriter Output { get; }
}

public interface IDuplexPipe
{
    PipeReader Input { get; }
    PipeWriter Output { get; }
}

class MyStream : IDuplexPipe, IPipeReader, IPipeWriter 
{}
```
Rather than
```csharp
class MyStream : IDuplexPipe
{}
```
 
@terrajobst, @KrzysztofCwalina , @joshfree

**Comment by davidfowl** [comment]
@pakrym and @KrzysztofCwalina what do you think about this?

**Comment by KrzysztofCwalina** [comment]
I like the scenario, but is it much worse without the interfaces? i.e. we could just add PipeReader/Writer properties to Stream and the calling code would check if the properties are null or not (just like the code sample above does).

**Comment by benaadams** [comment]
> i.e. we could just add PipeReader/Writer properties to Stream 

Have to change BCL Stream for that and wait for it to hit a .NET Standard and it only works for `Stream` type. `IPipeReader`/`IPipeWriter` works OOB and for many other types (e.g. perhaps its an Rx type, or a Channel, or a StringBuilder etc)

**Comment by KrzysztofCwalina** [comment]
```c#
public PipeStreamWriter(Stream stream, Encoding encoding, int bufferSize) {
    Encoding = encoding;
    if (stream is IDuplexPipe pipe)  {
        _pipe = pipe.Output;
        if(_pipe != null) { return; }
     }
     _streamWriter = new StreamWriter(stream, encoding, bufferSize);
}
```

**Comment by benaadams** [comment]
:-/

But that's in a weird lying Type system place that Stream lives; saying duplex but not being. Or like `IReadOnlyList` vs `IList`. 

It shouldn't implement the interface for something its not. If its only a writer that's all it should implement; if its duplex then it should implement that. However if its only writable it shouldn't implement duplex, then return `null` on reader.

**Comment by benaadams** [comment]
Fitting with the nullable reference types coming to C#8 it would be
```
public interface IDuplexPipe
{
    PipeReader? Input { get; }
    PipeWriter? Output { get; }
}
```
But :(

**Comment by KrzysztofCwalina** [comment]
Sure, the interfaces allow for additional type system enforcement of the contract. I just wanted to make sure we are explicit about the value added by the interfaces.
If it was six months ago, I would say the added value is worth it. Given where we are in the product cycle, this proposal makes me nervous (i.e. would hate to add interfaces that we then cannot, or don't want to, implement on streams). 
Having said that, maybe we should discuss this at the API review, @terrajobst ?

**Comment by benaadams** [comment]
My main worry is pre-2.1 ship you can change it to
```csharp
public interface IPipeReader 
{
    PipeReader Input { get; }
}

public interface IPipeWriter 
{
    PipeWriter Output { get; }
}

public interface IDuplexPipe : IPipeReader, IPipeWriter 
{}

public partial class Stream : IDuplexPipe // at some point / derived class
{}
```
Post-ship introducing these interfaces post 2.1 it would become
```csharp
public interface IPipeReader 
{
    PipeReader Input { get; }
}

public interface IPipeWriter 
{
    PipeWriter Output { get; }
}

public interface IDuplexPipe
{
    PipeReader Input { get; }
    PipeWriter Output { get; }
}

public partial class Stream : IDuplexPipe, IPipeReader, IPipeWriter  // urgh
{}
```

Which is the messy situation with `IList` and `IReadOnlyList` which should have been an interface hierarchy; but instead are side-by-side interfaces

**Comment by KrzysztofCwalina** [comment]
We should consider removing IDuplexPipe from 2.1.

**Comment by benaadams** [comment]
> We should consider removing IDuplexPipe from 2.1.

I'd be ok with that too (to bring back at a later stage)

**Comment by davidfowl** [comment]
> We should consider removing IDuplexPipe from 2.1.

No, we use it as public API in Kestrel and SignalR.

**Comment by benaadams** [comment]
> > We should consider removing IDuplexPipe from 2.1.

> No, we use it as public API in Kestrel and SignalR.

Then stick in the inheritance before it goes live and can't be added?

**Comment by davidfowl** [comment]
@pakrym do you have any opinions here? It seems like a fairly minimal change and I dunno how much runway we have for 2.1 maybe another day 😄

**Comment by pakrym** [comment]
To start with I don't like the naming, having PipeWriter that doesn't implement IPipeWriter but instead returns it is very weird.

Do we have other examples of downcasteble marker interfaces that have a single property? It feels that example above is too unnatural, usually, we provide a set of constructors to allow calling class to pass whatever they have instead of trying to downcast things to subtypes.

**Comment by benaadams** [comment]
> To start with I don't like the naming, having PipeWriter that doesn't implement IPipeWriter but instead returns it is very weird.

How about this then? 😄 
```csharp
public interface IReadablePipe 
{
    PipeReader Input { get; }
}

public interface IWritablePipe 
{
    PipeWriter Output { get; }
}

public interface IDuplexPipe : IReadablePipe, IWritablePipe 
{}
```

> It feels that example above is too unnatural

If you want a pipe fast-path on `ResponseStream` to avoid all the additional copies and internal buffering that happens via `HttpResponseStreamWriter`/`TextWriter` for both MVC and Json, its a very easy way to present as streams and pick up the optimizations while dropping the use, contention and additional memory use of ArrayPool (i.e. no api changes to take advantage of it https://github.com/aspnet/HttpAbstractions/pull/1001)

> usually, we provide a set of constructors to allow calling class to pass whatever they have instead of trying to downcast things to subtypes.

This will require users to move to a Pipe exposed on HttpContext and change their code to take advantage of it. Not sure there is currently any api to do this?

That will likely be a more advantageous approach; in addition, however this allows users that are using the current Streams programming patterns to also have their performance improved.

It can currently be done by implementing `IDuplexPipe` on `ResponseStream`; but since `ResponseStream` is only writable and not duplex that seems incorrect.

**Comment by davidfowl** [comment]
Seems like it would be trivial to achieve this via a feature on the HttpContext rather than exposing it on the Stream.

**Comment by benaadams** [comment]
> Seems like it would be trivial to achieve this via a feature on the HttpContext rather than exposing it on the Stream.

That should definitely be an additional step :)

This change would allow the advantages of the Pipe implementation to be picked up without the user changing any code; going direct would give more power to the user, however it requires the user to also change their programming patterns to get the advantages.

Also on HttpContext would it always be exposed as duplex or split (writer/reader). If the Response stream made uses of it via `IDuplexPipe` does `ResponseStream` throw or return null when `Output` is accessed? (both of which are a bit poor)

**Comment by pakrym** [comment]
We decided no to do this for 2.1
