### ISSUE TITLE
Proposal: Add local functions names to the navigation list

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/corefx#27264]
If there is a local function defined as this:
```
void foo1()
{
    void foo2()
    {
    }
}

```
it can appear in the code editor's upper navigation list with the name foo1.foo2
If the local function foo2 is defined inside the constructor of a class Class1, then it should appear with the name Class1.foo2
If it's defined inside the setter or the getter of a property named Property1, then  it should appear with the names Property1.Set.foo2, or Property1.Get.foo2

**Comment by jnm2** [comment]
This also a Roslyn request, not a framework library request.

**Comment by MohammadHamdyGhanem** [comment]
Sorry, can it be moved, or I have to repost it there?

**Comment by jnm2** [comment]
Copy and close is the only thing GitHub allows. Some people use a tool.

**Comment by gfoidl** [comment]
Additionally add a reference from the new issue to this issue.

**Comment by MohammadHamdyGhanem** [comment]
Done:
https://github.com/dotnet/roslyn/issues/24943
