### ISSUE TITLE
WinHttpHandler on Win7 is occasionally failing with "System.Net.Http.WinHttpException : The handle is invalid"

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#27273]
For example, here: https://mc.dot.net/#/user/geoffkizer/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/aee82742ebc870d5831d6b0b95b5044cd9e53fc2/workItem/System.Net.Http.Functional.Tests

I saw this earlier today in another PR as well.  Only seems to happen on Win7.

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/26092
