### ISSUE TITLE
System.Data.SqlClient => Dynamic SQL generation is not supported against a SelectCommand that does not return any base table information.

### ISSUE THREAD

**Issue by raul-gherman** [dotnet/corefx#27275]
Hi guys,

same piece of code compiled and run against .net framework 4.5 and dotnet core 2.0

.net framework 4.5 version runs without issues
dotnet core 2.0 version returns error:
Dynamic SQL generation is not supported against a SelectCommand that does not return any base table information.

comparing info from both libraries used, i noticed the following difference:
.net framework 4.5
Property: BaseTableName                  Value: TEST

dotnet core 2.0:
Property: BaseTableName                  Value:

apparently, this property is not properly captured

best regards,

Raul

**Comment by Clockwork-Muse** [comment]
...uh, could we get a minimal repro, please?

**Comment by saurabh500** [comment]
This seems like a duplicate of https://github.com/dotnet/corefx/issues/27283. 
@raul-gherman please confirm.

**Comment by raul-gherman** [comment]
Yea i confirm, thank you19:53, February 26, 2018, Saurabh Singh <notifications@github.com>:This seems like a duplicate of #27283.
@raul-gherman please confirm.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




Sent%20from%20Yandex%2EMail%20mobile

**Comment by saurabh500** [comment]
Closing this issue. Please follow recommendations at #27283
