### ISSUE TITLE
.Net Core ExecuteReader GetSchemaTable() method not returning the BaseTableName and more details.

### ISSUE THREAD

**Issue by Eilon** [dotnet/corefx#27283]
_From @ezra2310 on February 17, 2018 16:54_

Hi,

In .Net Core ExecuteReader.GetSchemaTable() method not returning the BaseTableName and more details of the query will executed.

I'm created an console application in Core .Net 2.0. The below code has written and do some R&D. Its working in .net Framework 4x version and get all schema details as BaseTablename,BaseColumn,etc.... But in Core .Net 2.0 the BaseTableName was not returning.

Im tried in various way but still im not got the route. Can you please help me how to get the BaseTableName and all those details.

Its very important R&D undergoing. Can you anybody please help me ??
```c#
SqlConnection sqlCnn = new SqlConnection(connetionString);
sqlCnn.Open();
SqlCommand sqlCmd = new SqlCommand(sql, sqlCnn);

SqlDataReader sqlReader = sqlCmd.ExecuteReader(CommandBehavior.KeyInfo);

List<string> gotTableNames = new List<string>();
DataTable schemaTable = sqlReader.GetSchemaTable();

foreach (DataRow dr in schemaTable.Rows)
{
   string data = Convert.ToString(dr["BaseTableName"]);
   if (!gotTableNames.Contains(data))
   {
      gotTableNames.Add(data);
   }
}

return string.Join(",", gotTableNames);
```
[edit by @danmosemsft to add triple tick formatting]
_Copied from original issue: aspnet/Mvc#7389_

**Comment by Eilon** [comment]
_From @Vasimovic on February 17, 2018 19:56_

I don't think this is related to the MVC repository; Anyhow, I was able to reproduce the problem; works in  full framework 4.+ as expected, returns blank data in netcoreapp2.0:

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            SqlConnection sqlCnn = new SqlConnection("Server=(local);Database=Master;Trusted_Connection=True;");
            sqlCnn.Open();
            SqlCommand sqlCmd = new SqlCommand("select name, database_id, create_date from sys.databases;", sqlCnn);

            SqlDataReader sqlReader = sqlCmd.ExecuteReader();

            var gotTableNames = new List<string>();
            DataTable schemaTable = sqlReader.GetSchemaTable();

            if (schemaTable != null)
            {
                foreach (DataRow dr in schemaTable.Rows)
                {
                    string data = dr["BaseTableName"].ToString();
                    if (gotTableNames.Contains(data)) continue;
                    gotTableNames.Add(data);
                }
            }

            Console.WriteLine(string.Join(",", gotTableNames));
            Console.ReadLine();
        }
    }
}

**Comment by Eilon** [comment]
_From @ezra2310 on February 18, 2018 0:35_

Hi Vasi,
My query is not sys tables. It’s normal join query.

 E.g. : select p.id [id_person],a.id [id_address],* from person [p] inner join address [a] on [p].addess_id = [a].id

The above one is my query. 
If this query will execute by ExecuteReader.GetSchemaTable() in.net framework 4+  I will return the BaseTableName and Basecolumn and AliasColumn name in DataTabel. 

But in netcoreapp2.0 it not returning also those details of executed query by Reader. 

In netcoreapp2.0 it just return the column name and data type. It’s normally we can get.

This my problem. Because the Join will be more table and dynamic representation of sql have to show in visual that is aim behind this scene

**Comment by Eilon** [comment]
_From @Vasimovic on February 19, 2018 18:47_

@ezra2310, I understand, as I mention, I confirmed it does not work with netcoreapp2.0 

You need to submit the issue to the **correct** [CoreFx](https://github.com/dotnet/corefx/issues) repository, this is the ASP.NET MVC repository

**Comment by Eilon** [comment]
_From @mkArtakMSFT on February 20, 2018 17:59_

@Eilon, can you please redirect this as necessary? Seems ADO.NET related.

**Comment by joshfree** [comment]
@corivera @saurabh500

**Comment by saurabh500** [comment]
I haven't seen any difference in execution on .Net Framework vs netcoreapp for the repro above. 
In case of the repro posted by @vasimovic I don't see any data returned on framework either. I have tried this on .Net 3.5 and 4.6.1

@ezra2310 can you provide a sample schema of your tables and a query that I can use to repro this issue on framework vs netcoreapp ?

**Comment by saurabh500** [comment]
Moving to future until more actionable information is available.

**Comment by Vasimovic** [comment]
@saurabh500 Sorry, I was messing with the code and forgot to put the (**CommandBehavior.KeyInfo**) `SqlDataReader sqlReader = sqlCmd.ExecuteReader(CommandBehavior.KeyInfo);` back

When I switch the .csproj target framework from **netcoreapp2.0** to **471** it works as expected
`<TargetFramework>471</TargetFramework>`

Note: I had to run couple of times, it seemed to cache the results

**Comment by saurabh500** [comment]
`I had to run couple of times, it seemed to cache the results`
Sorry, I dont follow, what is caching the results?  I did try sys.databases with .Net 4.6.1 and didnt see any results. Maybe I am missing something.

**Comment by saurabh500** [comment]
Also I tried with CommandBehavior.KeyInfo and without the CommandBehavior option

**Comment by Vasimovic** [comment]
RE: I had to run couple of times, it seemed to cache the results
When I changed the TargetFramework back and forth between netcoreapp2.0 and 471

**Comment by Vasimovic** [comment]
@saurabh500 - RE: Also I tried with CommandBehavior.KeyInfo and without the CommandBehavior option

That is strange, It workes for me when CommandBehavior.KeyInfo is used and when I target `<TargetFramework>471</TargetFramework>` BaseTableName returns (sysdbreg,syssingleobjrefs,syspalvalues,sysclsobjs,sysguidrefs,sysobjvalues) 

When I target `<TargetFramework>netcoreapp2.0</TargetFramework>` BaseTableName is empty

**Comment by saurabh500** [comment]
Hey @Vasimovic I can repro this on netcoreapp 2.0 with System.Data.SqlClient 4.4.2
Thanks for your help.
I was not using the KeyInfo on Framework repro. Sorry about that. And that was the reason I was not able to get the BaseTableName. 

However I also see that this problem is fixed in the master branch and can be verified using a package version from our nightly feeds at https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Data.SqlClient
E.g. 4.5.0-preview2-26223-05
