### ISSUE TITLE
Create release/uwp6.1 branch from release/uwp6.0

### ISSUE THREAD

**Issue by lt72** [dotnet/corefx#27282]
New branch should be forked from release/uwp6.0 HEAD

**Comment by weshaggard** [comment]
That doesn't sound correct. Why wouldn't it be based on what is in master? Or is the plan to merge those changes in later?

**Comment by lt72** [comment]
Correct, we will merge selected fixes from master later.

**Comment by lt72** [comment]
[closed issue by mistake]

**Comment by weshaggard** [comment]
Branch crated https://github.com/dotnet/corefx/tree/release/uwp6.1.
