### ISSUE TITLE
SocketsHttpHandler: proxy auth should choose digest over basic

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#27293]
There's logic in the regular auth handler to choose digest over basic if both exist in the 401 challenge.

The proxy logic doesn't seem to do this, it chooses whichever it finds first.

**Comment by davidsh** [comment]
We shouldn't use the first.  Our HTTP stacks always prioritize based on strongest security first, i.e. Negotiate, NTLM, Digest, Basic.

**Comment by geoffkizer** [comment]
I agree (in case I was unclear above) -- proxy auth logic is wrong and we need to fix this.  Regular auth logic seems to be correct.

We need to have tests for this as well.
