### ISSUE TITLE
System.Data.Tests.DataTableTest.WriteXmlSchema3 test failed in CI on netfx

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#27297]
```
System.Data.Tests.DataTableTest.WriteXmlSchema3 [FAIL]
        Assert.Equal() Failure
        Expected: ���CurrentLocale="true">\n    <xs:complexType>\n      <xs:choice m���
        Actual:   ���CurrentLocale="true" msdata:EnforceConstraints="True">\n    <x���
             at System.Data.Tests.DataTableTest.WriteXmlSchema3()
```
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/8520/consoleText

**Comment by danmosemsft** [comment]
Hmm, why this should start failing I have no clue. Nothing about this code seems potentially non deterministic.

**Comment by stephentoub** [comment]
My guess: something somewhere in the implementation there's some kind of check for a global setting that influences whether this ` msdata:EnforceConstraints="True"` attribute gets output, and this just happened to run with some interleaving with another test that had modified that setting.  Just a guess.

@saurabh500, are you aware of anything that could lead to that discrepancy in the output?

**Comment by danmosemsft** [comment]
That's what I figured but in a quick look at the code I couldn't see anything. It's not static, eg.,

**Comment by saurabh500** [comment]
I am not familiar with this code and the inner workings :( 
I will need to investigate to figure out why this could be happening.
All that I know is that  `EnforceConstraint` can be set on the DataSet using an attribute. I don't know about whether it can be modified by a global setting. (I don't think it can be at least based on a cursory code read through.)

**Comment by stephentoub** [comment]
Failed again here:
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/8799/consoleText

**Comment by Anipik** [comment]
Failed again https://mc.dot.net/#/user/Anipik/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Frelease~2F2.1~2F/test~2Ffunctional~2Fcli~2F/4a3f9eee07bac432df09baab03285cf905d3044d/workItem/System.Data.Common.Tests/analysis/xunit/System.Data.Tests.DataTableTest~2FWriteXmlSchema3
```
Assert.Equal() Failure
                                 ↓ (pos 427)
Expected: ···e=\"ExampleDataTable\">\
          <xs:complexType>\
            ···
Actual:   ···e=\"ExampleDataTable\" msdata:MinimumCapacity=\"50\">\
          <···
                                 ↑ (pos 427)
```

**Comment by stephentoub** [comment]
Appears to not have failed in almost a year.  Closing.
