### ISSUE TITLE
SocketsHttpHandler: Consider exposing setting for maximum response drain size

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#27329]
When a response is disposed before the response stream is read to the end, we attempt to drain the remaining response body up to a limit.  We should consider making this limit configurable via a setting on SocketsHttpHandler.

See discussion on #27315 

EDIT (@stephentoub): Added API:
```C#
public int MaxResponseDrainSize { get; set; } // Question: should we use long instead?
```

**Comment by stephentoub** [comment]
For comparison, WinHttpHandler has:
```C#
public int MaxResponseDrainSize { get; set; }
```

**Comment by geoffkizer** [comment]
That seems reasonable to me.

**Comment by davidsh** [comment]
Is there a reason for not doing this?  Seems like we want to expose as many knobs as possible on SocketsHttpHandler.  Not sure if we'll then decide to expose this on HttpClientHandler itself.

@stephentoub But perhaps this API change should be moved to "ready to review"?

**Comment by stephentoub** [comment]
Seems like we might as well do it.  The only reason not to would be if we decided for some reason we don't want draining, and I don't see that happening.
