### ISSUE TITLE
EmailAddressAttribute validates invalid emails

### ISSUE THREAD

**Issue by MorayM** [dotnet/corefx#27323]
I've been using [`EmailAddressAttribute`](https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/EmailAddressAttribute.cs) to validate email addresses in an MVC app but I've noticed that it uses a very naive validation method that validates addresses like `.name@example.org` and other formats forbidden by [RFC 2822](https://tools.ietf.org/html/rfc2822#section-3.4.1) and [3696](https://tools.ietf.org/html/rfc3696#section-3). Should this attribute use the same regex validation method as its [Framework equivalent](https://github.com/Microsoft/referencesource/blob/master/System.ComponentModel.DataAnnotations/DataAnnotations/EmailAddressAttribute.cs#L54), which seems much more robust?

**Comment by davidsh** [comment]
This is in System.ComponentModel* namespace.

**Comment by MorayM** [comment]
Yes, `System.ComponentModel.DataAnnotations`. Apologies, I got my links mixed up in the initial comment, I've corrected that now!

**Comment by ajcvickers** [comment]
@MorayM This has been discussed at length before and the current behavior is mostly due to an intentional change to fix a security bug. Issue #17873 has details--closing this as a dupe of that.
