### ISSUE TITLE
what set's Vector.IsHardwareAccelerated to true in System.Numerics.Vectors?

### ISSUE THREAD

**Issue by cheers00** [dotnet/corefx#2732]
I am writing a test app, 64 bit using System.Numerics.Vectors 4.1.0. I am trying to understand how ```Vector.IsHardwareAccelerated``` gets set to true. I’ve tried running this on three Haswell based systems. I get ```Vector.IsHardwareAccelerated``` as false during debugging. But when I run it from command prompt, I get true in one system and false in other two system.

**Comment by joshfree** [comment]
@CarolEidt @mellinoe

**Comment by mellinoe** [comment]
IsHardwareAccelerated is what we refer to as a "JIT intrinsic method", which means it is handled specially by the JIT. For this particular circumstance, the key thing to note is that these "JIT intrinsics" only turn on in release mode, so they will not be active during debugging. They are also only active on RyuJIT compiling for x64. It's possible your two other machines (the ones that are returning "false" on the command line) either aren't using RyuJIT, or are running 32-bit for whatever reason. If you compile the .exe as 64-bit only you could avoid that potential issue.

**Comment by cheers00** [comment]
Thank you.

I compared registry settings between systems and I found ```UseRyuJIT``` entry was missing in the systems where it was returning false for ```IsHardwareAccelerated```. I added new reg value ```UseRyuJIT = 1```  at ```HKCU\SOFTWARE\Microsoft\.NETFramework``` and it's working now.

On these faulty systems, I might have played with registry settings to try RyuJIT preview builds.
http://www.drdobbs.com/windows/64-bit-simd-code-from-c/240168851

But I wonder how VS 2015 RTM installation missed this registry setting.

**Comment by mellinoe** [comment]
Hm yes, you may have issues if you have some of the workarounds in place from our preview builds. @CarolEidt would know which environment variables and registry settings, if any, RyuJIT honors in the RTM version. At the very least, you shouldn't have to be setting anything yourself from a clean install of VS 2015 RTM.

**Comment by CarolEidt** [comment]
You shouldn't have had to modify the setting for UseRyuJIT - it should have been set by the 4.6 install, so I'm not sure how that was missed. That name is a bit misleading - it should really have been named "RyuJIT-compatible" or "4.6orLater" or something like that. Even if you want to use the legacy jit, UseRyuJIT should still be set to 1.

You can find some troubleshooting tips for RyuJIT here: https://github.com/Microsoft/dotnet/blob/master/docs/testing-with-ryujit.md
