### ISSUE TITLE
StringBuilder should allow copying efficiently to a TextWriter

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#27334]
## Motivation

At present to copy a StringBuilder into a TextWriter you must allocate a throwaway string as large as the amount you want to copy. This can cause a LOH allocation.

## Workaround 

To avoid that today you must write code to copy in blocks via a char[] buffer. ASP.NET were forced to do this ([PR here](https://github.com/aspnet/AspNetWebStack/commit/3fe0d348f00864e4f1eeaefbd027ea965787b892#diff-fe84a6b0645ee996bea1ec4d8445823f)) in response to an issue in a customer workload.

If we add an API for StringBuilder to copy to a TextWriter, we can take care of that loop, and also use a pooled char[].

## Proposed API

```c#
    public sealed partial class StringBuilder : System.Runtime.Serialization.ISerializable
    {
         // existing
        public void CopyTo(int sourceIndex, char[] destination, int destinationIndex, int count) { }
        public void CopyTo(int sourceIndex, System.Span<char> destination, int count) { }

        // proposed
        public void CopyTo(int sourceIndex, TextWriter destination, int count) { }
    }
```

## Rough Implementation

Basically [what ASP.NET did](https://github.com/aspnet/AspNetWebStack/blob/62d0b2df0bcca848a8e0848fd1866928df15528e/src/System.Web.WebPages/StringWriterExtensions.cs#L15) but using a pooled char[] buffer.

```c#
public void CopyTo(int sourceIndex, TextWriter destination, int count) 
{ 
            int remainingChars = this.Length;
            int bufferSize = Math.Min(this.Length,  1024);

            char[] buffer = ArrayPool<byte>.Shared.Rent(bufferSize);
            int currentPosition = 0;

            while (remainingChars > 0)
            {
                int copyLen = Math.Min(bufferSize, remainingChars);

                this.CopyTo(currentPosition, buffer, copyLen);

                destination.Write(buffer, 0, copyLen);

                currentPosition += copyLen;
                remainingChars -= copyLen;
            }

           ArrayPool<byte>.Shared.Return(buffer);
}
````

**Comment by danmosemsft** [comment]
@stephentoub thoughts? should I mark as ready for review, or do you believe this is not worthy?

**Comment by stephentoub** [comment]
I'd prefer to see us address https://github.com/dotnet/corefx/issues/21248.  If we had that, then this is just something like:
```C#
stringBuilder.ForEachChunk((span, state) => state.Write(span), textWriter);
```

**Comment by danmosemsft** [comment]
Ah - and in fact I even see another similar instance of the above workaround being cited there.

We can continue discussion there.
