### ISSUE TITLE
CoreFX publish steps should support running on systems with only VS 2017

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#27333]
Currently, the checked-in build definitions used by CoreFX publish tasks ( [example](https://github.com/dotnet/corefx/blob/master/buildpipeline/DotNet-Trusted-Publish.json#L38) ) are hard-coded to expect to find VS 2015 tools installed on the machine.

Ideally these steps could work on either system.  However, to support SourceLink and other new features we'd like to move all build processes to 2017 for now.

@weshaggard FYI.

**Comment by ViktorHofer** [comment]
@MattGal the link you provided points to master so I can't see which line you meant but I believe we removed the VS14 requirement?

**Comment by MattGal** [comment]
Yes, I think this can be closed now.

**Comment by MattGal** [comment]
Reactivating this issue since it's still a problem and seems to have not actually been addressed.  Unfortunately, VS 2015 tooling cannot tolerate an MSBuild project that does not have the namespace included, and the publish steps are still running this way currently:

```
E:\A\_work\3319\b\pipelineRepository\eng\Versions.props(2,1): error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format. [E:\A\_work\3319\b\pipelineRepository\src\syncAzure.proj]
```

**Comment by MattGal** [comment]
D'oh I already opened https://github.com/dotnet/corefx/issues/32983 but failed to find it.  Closing.
