### ISSUE TITLE
Publish symbols using Microsoft.SymbolUploader.Build.Task package

### ISSUE THREAD

**Issue by dagood** [dotnet/corefx#27343]
The `Microsoft.SymbolUploader.Build.Task` package on the BuildTools feed is the new way to index and publish symbols to the symbol server. It should be used instead of the current combination of BuildTools' `GetAllSymbolFilesToPublish` and the VSTS symbol publish build step.

Example implementation in Core-Setup: https://github.com/dotnet/core-setup/pull/3465

**Comment by mikem8361** [comment]
Done.
