### ISSUE TITLE
HttpWebRequest/HttpWebResponse never releases connection after http server error (.Net Core 2.0.1, Debian 8)

### ISSUE THREAD

**Issue by kfomichev** [dotnet/corefx#27355]
I'm running a .Net Core Console App under Debian 8, which constantly queries a REST server via HTTPS.
The app uses plain syncronous http calls using HttpWebRequest / HttpWebResponse .
I noticed that after some hours of operation all calls raise exceptions with description "Too many open files", meaning that there are too many connections left non-closed.
After some investigation I figured out that each time the http server responds with non-200 status code (for example, 5хх server errors of 429 Too many requests), even after disposing HttpWebResponse the connection remains open but is never reused by ServicePoint manager for next HttpWebRequest, even for the same host/URL. After a significant amount of errors the open file limit (default 4096) is exhausted an no further requests are possible. The connections are never released until the dotnet process is killed.

Actions to reproduce he problem:

1. I wrote a simple php script `getstatus.php` and placed it on a test web serer. The script emulates http error. It accepts a numeric code as GET query and responds with same HTTP code. The response body always  contains the same - the resquest headers. When requesting `https://myserver/getstatus.php` or
`https://myserver/getstaus.php?200` I get normal response. When requesting `https://myserver/getstaus.php?500` I get same content, but with 500 status code ("Internal server error") etc.
The php code is below:
```php
<?php
$code=$_SERVER['QUERY_STRING'];
if ($code) {
	http_response_code($code);
};
echo "Request headers:         <br /> \n";
foreach (getallheaders() as $name => $value) {
    echo "$name: $value         <br />\n";
}
?>
```

2. The sample vb.net code for quering the server. The program accepts a numeric code as argument and makes 100 requests to test server:  
```vb
Imports System
Imports System.IO
Imports System.Net
Imports System.Threading

Module Program
    Private Const USER_AGENT = "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36"

    Sub Main(args As String())
        Dim result As String
        For counter = 1 To 100
            If args.Count < 1 Then
                Console.WriteLine("Launched without arguments")
                result = DownloadString("https://mytestserver/getstatus.php")
            Else
                Console.WriteLine("Launched with argument: {0}", args(0))
                result = DownloadString("https://mytestserver/getstatus.php?" & args(0))
            End If
            Console.WriteLine("Respone content > " & result)
            Thread.Sleep(500)
        Next
        Console.ReadLine()
    End Sub

    Private Function GetResult(ByRef w As HttpWebRequest) As String
        Try
            Using r As HttpWebResponse = w.GetResponse
                Console.WriteLine("Response status > " & r.StatusCode)
                Console.WriteLine("Response headers > " & r.Headers.ToString)
                Using s As Stream = r.GetResponseStream
                    Using rd As StreamReader = New StreamReader(s)
                        Dim st As String = rd.ReadToEnd
                        Return st
                    End Using
                End Using
            End Using
        Catch ex As webException
            Console.WriteLine("Catch in GetResult(): " & ex.Message)
        End Try

    End Function

    Private Function DownloadString(ByVal __Url As String) As String
        Try
            Dim w As HttpWebRequest = CType(WebRequest.Create(__Url), HttpWebRequest)
            w.UserAgent = USER_AGENT
            w.KeepAlive = True
            w.Timeout = 10000
            w.ReadWriteTimeout = 10000
            Console.WriteLine("Requesting " & __Url)
            Return GetResult(w)
        Catch ex As Exception
            Console.WriteLine("Catch in DownloadString(): " & ex.Message)
        End Try
    End Function

End Module
```
I use VS 2017 Community to write the code. The project was created using a ".Net Core Console application" template with no additional changes to project configuration. The target platform is shown as ".NET Core 2.0"
The project is compiled under VS, then published to a folder, then the folder contents are transferred to the Debian 8 machine (VPS) and run like `dotnet myproj.dll`

3. To count open file handles I use a bash script found on StackOverflow
```bash
cd /proc
for pid in [0-9]*
do
    echo "PID = $pid with $(ls /proc/$pid/fd/ | wc -l) file descriptors"
done | sort -rn -k5 | head | while read -r _ _ pid _ fdcount _
do
  command=$(ps -o cmd -p "$pid" -hc)
  printf "pid = %5d with %4d fds: %s\n" "$pid" "$fdcount" "$command"
done
```

4. Actual testing
4.1. Run `dotnet myproj.dll`. On a separate session monitor open file count with the above script. In my case there are no more than 42 open files for the dotnet process, from start to finish.

4.2. Run `dotnet myproj.dll 500` emulating http errors. Each attempt to get httpwebresponse object results in exception which is logged to console. After each error the number of open files for dotnet process increases by 3 (!). After 100 "unsuccessful" requests the open file count reaches 344 (started at 42).
Note that all objects for response handling are wrapped in `using`, so they should be disposed properly after exception, and tcp connection should be released for reusing for next calls. I might be wrong, but current behavior is a bug.

During further experiments I found a workaround. If I completely read a ResponseStream of WebException.Response object, the connection seems to be released, and total connection count does not increse. The `Catch` block in `GetResponse` function should containg following lines:
```vb
Catch ex As webException
            Console.WriteLine("Catch in GetResult(): " & ex.Message)
            Console.WriteLine("WebException.Reponse.Headers: " & ex.Response.Headers.ToString)
            Using s As Stream = ex.Response.GetResponseStream
                Using rd As StreamReader = New StreamReader(s)
                    Dim st As String = rd.ReadToEnd
                    Return st
                End Using
            End Using
        End Try
```
But this seems to be redundant because in many cases servers don't return any meaningful info after http error in the response body, so reading it is unneeded work and anyway non-intuinive way of programming.
Thanks for attention and please don't mind any mistakes, I'm not a professiona l programmer.

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by kfomichev** [comment]
I double checked dotnet version, it's actually 2.1.3. Sorry.

**Comment by maximusjunior** [comment]
Got the same error. My code works just fine on Mono, but fails on .Net Core 2.0.3 on CentOS 7.

.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  eb1d5ee318

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.3/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

**Comment by davidsh** [comment]
HTTP/1.1 protocol encourages clients and servers to keep connections open so that they can be reused.  Getting a non-200 response code (such as 500) from a server doesn't automatically mean that the connection will be closed.  A server can choose to close the connection after sending a 500 status code back.

If you want to have connections close after sending a non-200 status code, you can modify your server to do that.  You can also have the client request non-persistent connections in general (i.e. close them after each request) by adding a 'Connection: close' request header to your request.

>During further experiments I found a workaround. If I completely read a ResponseStream of WebException.Response object, the connection seems to be released

This is because you are fully reading the response stream to the end. So, the connection gets closed.

In general, this is by-design behavior.

We have recently released .NET Core 2.1. Please try it out. It will have faster performance.  It still will have the same persistent connection behavior, though.
https://blogs.msdn.microsoft.com/dotnet/2018/05/30/announcing-net-core-2-1/

**Comment by kfomichev** [comment]
I still think this behavior is wrong.
The HttpWebResponse object implements IDisposable.  That means if I call HttpWebResponse.Close or wrap the object creation into `using` , the connection should be released to ServicePoint manager anyway. The inner logic should decide whether to physically close connection or reuse it. It should not rely on programmer, whether he has read buffered data to the end or not. In the above case the connection is neither closed, nor reused, and that's the whole point.
