### ISSUE TITLE
SSL certificate validation on Windows 7 with .Net Framework is ignored after a connection to port different than 443 was established

### ISSUE THREAD

**Issue by atanasa** [dotnet/corefx#27354]
- Steps to reproduce:

1. Create/find a server that hosts 2 SSL endpoins on port 443 and port 10443 (probably any port different that 443) - the IP address of the two endpoints should be the same, the server certificates of the endpoints should be self-signed and different.
2. Build the following code for **net471**:
```c#

        static void Main(string[] args)
        {
           string host = "your server IP";
           MakeRequest(host, 10443);
           MakeRequest(host, 443);
        }

       private static void MakeRequest(string host, int port) {
          HttpRequestMessage webRequest =
             new HttpRequestMessage(
                HttpMethod.Get,
                $"https://{host}:{port}/");
          webRequest.Version = new Version(1, 1);

          var handler = new HttpClientHandler {
             ServerCertificateCustomValidationCallback =
                (sender, cert, chain, errors) => true
          };
          HttpClient client = new HttpClient(handler);

          client.SendAsync(webRequest).Wait();
       }
```
3. Run the following code to connect to that server **on Windows 7 64-bit**

- Expected result:
The code should complete without errors

- Actual result:
There is an exception:

```
System.Net.Http.HttpRequestException: An error occurred while sending the request. 
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
```

**This does not reproduce on Windows 10.**

Considering that this API is part of the .Net Standard 2.0 API, it affects portable code running on Windows 7 and on .Net Framework.

The issue is also observed on all net451+ frameworks on Windows 7. The  test for those frameworks uses the ```WebRequestHandler``` as it is the only one that has a certificate validation support.

I think it has something to do with the ServicePointManager and it reusing of connections as reducing the MaxServicePointIdleTime seems to have some effect (though in the distilled repro above I couldn't make it pass).

If the order of the request is changed so that the connection to the port 443 is established first, then the connection to port 10443 is ok.

**Comment by atanasa** [comment]
I think it works correctly on .Net Core on Windows 7.

Do you know where this issue should be filed then?

**Comment by davidsh** [comment]
.NET Framework questions/bugs can be opened here:

https://developercommunity.visualstudio.com/spaces/61/index.html

**Comment by atanasa** [comment]
Thanks, I'll log it there as after further investigation it seems to be some issue with the Schannel API in the Windows 7.
