### ISSUE TITLE
Should Span.Empty return a pointer to an empty array instead of default?

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#27350]
Currently, there is inconsistent behavior in the following scenario:
```C#
byte[] array = new byte[10];
Span<byte> span = new Span<byte>(array, 0, 0); // effectively empty
Span<byte> emptySpan = Span<byte>.Empty; // returns "default"

Assert.True(span.IsEmpty);
Assert.True(emptySpan.IsEmpty);

fixed (byte* pSpan = &MemoryMarshal.GetReference(span))
{
    fixed (byte* pEmptySpan = &MemoryMarshal.GetReference(emptySpan))
    {
        // pSpan != null
        // pEmptySpan == null
    }
}
```

Should `Span<T>.Empty` return either `SpanHelpers.PerTypeValues<T>.EmptyArray;` or `Array.Empty<T>();` instead?

As an aside, should we do a null check and throw if someone calls `MemoryMarshal.GetReference(default(Span<T>))` instead of returning a null pointer (especially now that we return default if we pass null array to the constructor)?

Otherwise, we would have to do pointer null checks (for span.Length == 0) before passing it to native libraries (for example here - https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Globalization/CompareInfo.Windows.cs#L166).

cc @jkotas, @KrzysztofCwalina, @stephentoub, @tarekgh, @VSadov, @AndyAyersMS

**Comment by jkotas** [comment]
> Should Span<T>.Empty return either `Array.Empty<T>()`

You can get the null pointer in number of other ways. It does not make sense to penalize `Span.Empty` for this because of it would solve just fraction of the problem.

> should we do a null check and throw if someone calls `MemoryMarshal.GetReference(default(Span<T>))`

No. `MemoryMarshal.GetReference` is low-level API that should just return the pointer in the Span.

>  we would have to do pointer null checks (for span.Length == 0) before passing it to native libraries

Most classic C libraries work just fine for zero-length buffers that have `pointer = NULL`. If there are APIs with bogus argument checks that do not handle this case correctly, you need to make them happy by substituting the NULL pointer with non-NULL pointer, e.g. pointing to a local.

**Comment by jkotas** [comment]
The problem with APIs with bogus argument checks is not new. It is not unusual to find `fixed` uses that are working around. Here is one example: https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Text/OSEncoder.cs#L46

**Comment by KrzysztofCwalina** [comment]
I think it is not clear whether default span is a valid value that won't be throwing random exceptions. Span.Empty makes it very clear. Also, we are trying to have span be as similar to arrays as possible, and arrays have Empty singleton.

**Comment by ahsonkhan** [comment]
> we are trying to have span be as similar to arrays as possible, and arrays have Empty singleton.

I agree that we should have Span.Empty similar to array, but pinning array.Empty does not give back a null ptr.

**Comment by jkotas** [comment]
> pinning array.Empty does not give back a null ptr.

Pinning array.Empty will give you back a null ptr.

**Comment by VSadov** [comment]
Makes sense. 

Yes, pinning an array returns a pointer to an element. And If you do not have elements you get NULL.
Form that point Empty and `default` being the same for Span seems right. 

Ignore my earlier comment.

**Comment by ahsonkhan** [comment]
Based on our discussion here, https://github.com/dotnet/coreclr/pull/17115 special cases empty spans ahead of time to avoid passing to Interop code (and prevent NullReferenceExceptions), especially if the span wraps a null string.

**So, to summarize:**
- Should Span.Empty return a pointer to an empty array instead of default?
   - No
- Do we need to add IsEmpty checks before trying to deference Span pointers (or using MemoryMarshal.GetReference)?
   - Yes

Closing the issue. Thanks.
