### ISSUE TITLE
Specify sub protocol for WebSocket Client

### ISSUE THREAD

**Issue by Eilon** [dotnet/corefx#27364]
_From @andylyonette on February 21, 2018 16:51_

Hi,

I can't work out how to specify the sub protocol when creating a client connect to a websocket endpoint. Is this possible like it is with this JavaScript client? (https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications)

Thanks,
Andy

_Copied from original issue: aspnet/Home#2892_

**Comment by Eilon** [comment]
_From @davidfowl on February 22, 2018 16:45_

This should be moved to corefx. It's trivial to do so with the ClientWebSocket api:

```C#
var client = new ClientWebSocket();
client.Options.AddSubProtocol("protocol1");
client.Options.AddSubProtocol("protocol2");
```

**Comment by stephentoub** [comment]
Looks like the question has been answered.  Closing.  Please re-open if there's still an open issue here.
