### ISSUE TITLE
Optimize string-like portable Span APIs for Ordinal and OrdinalIgnoreCase

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#27379]
This is specific to portable span (and not fast span).

We do not need to allocate and call the string APIs when StringComparison is Ordinal or OrdinalIgnoreCase.

Similar to APIs like EndsWith/etc., add a non-allocating code path for CompareTo for Ordinal:
https://github.com/dotnet/corefx/blob/42d5370f8c6cec8d1961f54a0974e52b0562b0a7/src/System.Memory/src/System/MemoryExtensions.Portable.cs#L23

Also optimize for OrdinalIgnoreCase for all the string-like APIs.

See: https://github.com/dotnet/corefx/pull/27319#discussion_r170048253

cc @tarekgh

**Comment by benaadams** [comment]
There are Ordinal versions in `mscorlib/shared/System/StringSpanHelpers.cs` ? 
e.g. `CompareOrdinalIgnoreCase(ReadOnlySpan<char>,ReadOnlySpan<char>)` was looking at them in https://github.com/dotnet/coreclr/pull/16434

**Comment by ahsonkhan** [comment]
> There are Ordinal versions in `mscorlib/shared/System/StringSpanHelpers.cs` ? 

Sorry, this issue is specific to portable span only. Fast span already has this optimization.
