### ISSUE TITLE
Is RuntimeInformation.OSArchitecture fixed on .NET 4.7.2?

### ISSUE THREAD

**Issue by Alois-xx** [dotnet/corefx#27386]
.NET 4.7.1 contains the embedded RuntimeInformation class which returns a wrong OSArchitecture. 
See https://github.com/Microsoft/perfview/issues/478#issuecomment-367845285
Is this fixed with the upcoming .NET 4.7.2?

**Comment by danmosemsft** [comment]
@alexghi

**Comment by danmosemsft** [comment]
Oops, @tarekgh now.

**Comment by tarekgh** [comment]
@luqunl can confirm that.

**Comment by Alois-xx** [comment]
@luqun: Will there be an NuGet package of System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a with a version > 4.0.1.0? If not I cannot release a tool which will work with a fixed NuGet package on .NET 4.7.1. The assembly redirects to mscorlib of the .NET Framework will always only redirect to the matching ones I hope and not redirect any  version.

**Comment by luqunl** [comment]
I don't know whether this is a NuGet package for this assemlby. @tarekgh, do you know?

**Comment by tarekgh** [comment]
I am not sure I fully understand the problem here. but we have this nuget package for .Net Core here https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Runtime.InteropServices.RuntimeInformation

**Comment by Alois-xx** [comment]
@tarekgh: I just wanted to ensure that the desktop .NET Frameowork contains no binding redirects regardles of the referenced version. I just have looked at .NET 4.7.1 where it brings in a System.Runtime.InteropServices.RuntimeInformation.dll with version 4.0.0.0 which contains a typeforward to mscorlib.

`
[assembly: TypeForwardedTo(typeof(RuntimeInformation))]
`

If I get a fixed version of it in version e.g. 4.0.0.2 and this one works I can be sure that no secret binding redirect will use a faulty implementation provided by the installed .NET Framework (e.g. .NET 4.7.1)

**Comment by tarekgh** [comment]
@AlexGhiondea @joperezr could you please help answering @Alois-xx question?

**Comment by AlexGhiondea** [comment]
@Alois-xx, in 4.7.1 we have added the `System.Runtime.InteropServices.RuntimeInformation.dll` assembly in-box. This means that going forward, when running on Desktop you will use that assembly to run.

Can you try the 4.7.2 Early Access Preview and see if on that version you get the expected behavior?

**Comment by ViktorHofer** [comment]
> This was fixed in .NET Framework 4.7.2. (https://github.com/dotnet/corefx/issues/25706#issuecomment-375120452)

Closing.
