### ISSUE TITLE
X509Certificate2Collection.Find() does not return the same certificates as full framework

### ISSUE THREAD

**Issue by gingters** [dotnet/corefx#27405]
Hi,

I have a strange issue with handling of certificates from the windows certificate store. On full .NET framework, this code returns the expected certificates, on dotnet core, the very same code does not return any certificates from the store.

The code is the following:

```
var certificates = new List<X509Certificate2>();

using (var myStore = new X509Store(StoreName.My, StoreLocation.CurrentUser))
{
	myStore.Open(OpenFlags.ReadOnly);
	var certsWithCorrectUsage = myStore.Certificates.Find(X509FindType.FindByKeyUsage, X509KeyUsageFlags.DataEncipherment.ToString(), true);

	foreach (var cert in certsWithCorrectUsage)
	{
		if (cert.HasPrivateKey)
		{
			certificates.Add(cert);
		}
	}
}

return certificates;
```

When debugging into the `.Find()` method I get down into `FindPal.VerifyCertificateIgnoringErrors()`, and there on the `chainPal.ChainStatus` I see the following error messages:
```
The signature of the certificate cannot be verified.
A certificate chain processed, but terminated in a root certificate which is not trusted by the tust provider.
```

I used the following powershell script to generate a root certificate, install it in the Trusted Root Certification Authorities, and create two other test certificates which are signed by this root cert:

[createcerts.ps1.txt](https://github.com/dotnet/corefx/files/1751455/createcerts.ps1.txt)

Why doesn't the code on dotnet core find the root certificate, while it obviously seems to be trusted by my machine and also the full framework finds these certificates as valid for the requested purpose.

**Comment by gingters** [comment]
Additional info:
I just found out that the certificates are returned, when the root cert is installed in the local machine Trusted Root Certificate Authorities. However, this is still a different behavior to the full framework where the certs are also returned when the root cert is available only in the current users Trusted Root Certificate Authorities.

**Comment by bartonjs** [comment]
> I just found out that the certificates are returned, when the root cert is installed in the local machine Trusted Root Certificate Authorities

Looks like .NET Framework did validOnly by using current-user chains.  And .NET Core does them with machine-scope chains.

Should be as simple as flipping a true to false in `VerifyCertificateIgnoringErrors`

**Comment by bartonjs** [comment]
Like 30 "are you sure?" popups later, I've confirmed that it's just flipping that boolean.
