### ISSUE TITLE
Add GetPosition overload to ReadOnlySequence that only takes an int/long

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#27403]
Today GetPosition requires a relative offset but there are scenarios where you just want to get the position from the start. Today that looks like:

```C#
// Get position 100
var position = sequence.GetPosition(sequence.Start, 100);
```

## Proposal

Add GetPosition that takes an int/long that assumes sequence.Start is the origin:

```C#
var position = sequence.GetPosition(100);
```

/cc @pakrym @KrzysztofCwalina @ahsonkhan @terrajobst @halter73

**Comment by KrzysztofCwalina** [comment]
I think this is a fine addition, but we would need to change the order of the parameters in the existing overload, so we would endup with

```c#
var position = sequence.GetPosition(100, sequence.Start);
// and
var position = sequence.GetPosition(100);
```

**Comment by pakrym** [comment]
I like the order change. It's also aligned with `Seek(long offset, SeekOrigin origin)`

**Comment by davidfowl** [comment]
Yep, I like it too.

**Comment by KrzysztofCwalina** [comment]
@terrajobst, do we need an API review for such trivial changes?

**Comment by halter73** [comment]
@KrzysztofCwalina @pakrym @davidfowl You all think putting the offset before the pointer is preferable than the other way around? If so, I'll take some of what you all are having please.

Seriously though. Is there *any* other API other than Stream.Seek (where SeekOrigin isn't really a pointer to begin with) like this? I know you can do `offset[pointer]` in C, but no one actually does that.

**Comment by halter73** [comment]
Even taking into account the overload, is anyone ever changing a `GetPosition(long offset)` call to `GetPosition(long offset, Sequence position start)`?

I guess it might help with intellisense, but anyone unfamiliar with the API would start by typing `start.GetPosition(offset)` instead of `sequence.GetPosition(offset, start)`.

**Comment by ahsonkhan** [comment]
@pakrym, @halter73 - please join us for the API review tomorrow, if you can.

**Comment by terrajobst** [comment]
We decided to go with @KrzysztofCwalina's proposal:

```c#
var position = sequence.GetPosition(100, sequence.Start);
// and
var position = sequence.GetPosition(100);
```
