### ISSUE TITLE
Path changes resulting in failing Common NormalizeDirectorySeparatorTests

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#27401]
From https://mc.dot.net/#/user/dotnet-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/4fb11f22f98f2106002799957aa0993cbf188b4e/workItem/Common.Tests/analysis/xunit/Tests.System.IO.PathInternalTests_Windows~2FNormalizeDirectorySeparatorTests(path:%20%5C%22%20%20%20%20~2F~2F%5C%22,%20expected:%20%5C%22%5C%5C%5C%5C%5C%5C%5C%5C%5C%22)

```
Unhandled Exception of Type Xunit.Sdk.EqualException
Message :
Assert.Equal() Failure
          ↓ (pos 0)
Expected: \\\\
Actual:       \\
          ↑ (pos 0)
Stack Trace :
   at Tests.System.IO.PathInternalTests_Windows.NormalizeDirectorySeparatorTests(String path, String expected) in D:\j\workspace\windows-TGrou---74aa877a\src\Common\tests\Tests\System\IO\PathInternal.Windows.Tests.cs:line 126
```

Test disabled in #27398

**Comment by jkotas** [comment]
cc @JeremyKuhne @Anipik

**Comment by JeremyKuhne** [comment]
Thanks @jkotas, I'll take care of this.

**Comment by JeremyKuhne** [comment]
@Anipik can you re-enable and add some tests for GetRootLength?  Tests need updated for the fact that we don't trim spaces anymore.
