### ISSUE TITLE
Improve SqlDataRecord test coverage

### ISSUE THREAD

**Issue by saurabh500** [dotnet/corefx#27416]
Improve SqlDataRecord test coverage. 
cc @remibou

**Comment by RemiBou** [comment]
(https://github.com/dotnet/corefx/compare/master...RemiBou:master)

Added 2 tests, is that what you are expecting ? It seems that the first test is quite big and my tests are testing way less things, what do you prefer ?

**Comment by saurabh500** [comment]
@RemiBou I think you are on the right track. I prefer smaller tests. They are more focussed and easier to debug

**Comment by RemiBou** [comment]
@saurabh500 on GetOrdinal, can I change the initialisation of _fieldNameLookup with a Lazy<> ? Or is that out of scope ? Or even not a good idea (it'll make this method thread safe)

**Comment by saurabh500** [comment]
I would say it is out of scope for now until we figure out that Thread Safety is really needed here. If you find along the way, during your involvement that Thread Safety can be utilized here, I would go for it.

**Comment by RemiBou** [comment]
Given that GetOrdinal is called on the [] accessor, someone might Parallelize some calls (that would be interesting only on record with a lot of columns), but that's not obvious though

**Comment by RemiBou** [comment]
https://github.com/dotnet/corefx/compare/master...RemiBou:master

+43 lines covered, is that still on phase with your policy/pratice ?
