### ISSUE TITLE
TryGetArray(ReadOnlyMemory<T>.Empty) returns false

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#27412]
This is an API quirk I ran into when using `ReadOnlyMemory<byte>` to do some parsing the other in SignalR.

```C#
var isArray = MemoryMarshal.TryGetArray(ReadOnlyMemory<byte>.Empty, out var array);
Console.WriteLine(isArray);
```

This prints false and I think it should print true. We should back the Empty read only memory with an empty array as it makes it easier to interop with systems that expect arrays.

/cc @KrzysztofCwalina @ahsonkhan @stephentoub @jkotas

**Comment by jkotas** [comment]
I do not think we should be penalizing everybody who uses Memory.Empty memory by backing it via empty array.

I think it would be reasonable for TryGetArray to return empty array for zero sized memory.

**Comment by kasper3** [comment]
Does runtime require cached array segment for empty array to perform better?

Like here:
https://github.com/dotnet/coreclr/blob/6a083d478854a1c6e708ff16d97ef617125cde86/src/mscorlib/shared/System/Memory.cs#L328, which one is better for JIT:

```c#
if (_length == 0) return _emptySegment;
// or
if (_length == 0) return new ArraySegment<T>(Array.Empty<T>());
```

**Comment by jkotas** [comment]
Caching it in a static would make it a bit faster, but it comes with larger fixed footprint. 

ArraySegment is relatively slow type. The extra fixed footprint is not worth it, I think.

**Comment by jkotas** [comment]
ArraySegment has the cache already. You can just use `ArraySegment.Empty`.

**Comment by kasper3** [comment]
Nice, didn't knew Empty exists in ArraySegment. Only exists in .NET Core, not .NET Framework 4.7.1 https://docs.microsoft.com/en-us/dotnet/api/system.arraysegment-1?view=netframework-4.7.1#Properties
https://docs.microsoft.com/en-us/dotnet/api/system.arraysegment-1?view=netcore-2.0#Properties

**Comment by ahsonkhan** [comment]
Related PR - https://github.com/dotnet/corefx/pull/27430

**Comment by davidfowl** [comment]
yay
