### ISSUE TITLE
NETCore System.ComponentModel.Composition (MEF1) fails

### ISSUE THREAD

**Issue by superriva** [dotnet/corefx#27433]
Hi. Could you help me to make a simple example with mef1? Thank you in advance.
My system is Archlinux x64. I'm using component from myget.org (dotnet add package System.ComponentModel.Composition --version 4.5.0-preview2-26223-06 --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json).
My code is here:

```
dotnet --version
2.1.4
```
```
pwd
/at/c#
```
Contract (in /at/c#/example_console_mef_contract):
```csharp
cat /at/c#/example_console_mef_contract/Class1.cs
using System;
namespace example_console_mef_contract
{
    public interface IHelloWorld
    {
        string HelloWorld();
    }
}
```
Library aka plugin (in /at/c#/example_console_mef_lib). Csproj file includes a reference to contract project.
```csharp
cat /at/c#/example_console_mef_lib/Class1.cs
using System;
using System.ComponentModel.Composition;
using System.ComponentModel.Composition.Hosting;
using System.Reflection;
using example_console_mef_contract;
namespace example_console_mef_lib
{
    [Export(typeof(example_console_mef_contract.IHelloWorld))]
    public class MefHelloWorld : IHelloWorld
    {
        public string HelloWorld()
        {
            return "Hello world";
        }
    }
}
```
```
cat /at/c#/example_console_mef_lib/example_console_mef_lib.csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Composition" Version="4.5.0-preview2-26223-06" />
  </ItemGroup>
  <ItemGroup>
  **<ProjectReference Include="/at/c#/example_console_mef_contract/example_console_mef_contract.csproj" />**
  </ItemGroup>
</Project>
```
Main application (in /at/c#/example_console_mef). Csproj file includes a reference to contract project.
```csharp
cat /at/c#/example_console_mef/Program.cs
using System;
using System.ComponentModel.Composition;
using System.ComponentModel.Composition.Hosting;
using System.Reflection;
using example_console_mef_contract;
namespace example_console_mef
{
    class Program
    {
        private CompositionContainer _container;
        [Import(typeof(example_console_mef_contract.IHelloWorld))]
        private example_console_mef_contract.IHelloWorld helloWorld;
        private Program()
        {
            var catalog = new AggregateCatalog();
            catalog.Catalogs.Add(new AssemblyCatalog(typeof(Program).Assembly));
            catalog.Catalogs.Add(new DirectoryCatalog(@"/at/c#/example_console_mef_lib/bin/Debug/netstandard2.0"));
            _container = new CompositionContainer(catalog);
            try
            {
                this._container.ComposeParts(this);
            }
            catch (CompositionException compositionException)
            {
                Console.WriteLine(compositionException.ToString());
            }
        }
        static void Main(string[] args)
        {
            Program p = new Program();
//            Console.WriteLine(p.helloWorld.HelloWorld());
//            Console.ReadKey();
        }
    }
}
```
```
cat /at/c#/example_console_mef/example_console_mef.csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Composition" Version="4.5.0-preview2-26223-06" />
  </ItemGroup>
  <ItemGroup>
  **<ProjectReference Include="/at/c#/example_console_mef_contract/example_console_mef_contract.csproj" />**
  </ItemGroup>
</Project>
```
Contract and library projects compiled without errors. 
Now I try run main application but it fails:
```
cd  /at/c#/example_console_mef
dotnet run
System.ComponentModel.Composition.ChangeRejectedException: The composition remains unchanged. The changes were rejected because of the following error(s): The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) No exports were found that match the constraint:
        ContractName    example_console_mef_contract.IHelloWorld
        RequiredTypeIdentity    example_console_mef_contract.IHelloWorld

Resulting in: Cannot set import 'example_console_mef.Program.helloWorld (ContractName="example_console_mef_contract.IHelloWorld")' on part 'example_console_mef.Program'.
Element: example_console_mef.Program.helloWorld (ContractName="example_console_mef_contract.IHelloWorld") -->  example_console_mef.Program

   at System.ComponentModel.Composition.CompositionResult.ThrowOnErrors(AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ComposablePartExportProvider.Compose(CompositionBatch batch)
   at example_console_mef.Program..ctor() in /at/c#/example_console_mef/Program.cs:line 26
```

**Comment by danmosemsft** [comment]
@weshaggard do you remember enough about MEF to help ...

**Comment by superriva** [comment]
I am looking at the package version history here https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.ComponentModel.Composition
And it seems to me the package is under active development. It's good! So, there are developers who nows how to work with package. 
And I tryed a working examle from here https://stackoverflow.com/questions/19572647/using-mef-with-c-how-do-i-call-methods-on-the-host-from-the-plugin
But not successful for me...

**Comment by superriva** [comment]
@weshaggard 
I'm not interested in a code which works any way. I need a code which works in MEF style. Main application must not have any references to a plugin library. All apllication parts must communicate by [import]/[export] only.
So, I have found a very good MEF example here https://www.codeproject.com/Articles/188054/An-Introduction-to-Managed-Extensibility-Framework
The example can be compiled under VS2017 and it works. Part3 of the example shows how MEF can dinamically load *.dll from catalog. So, I'm waiting same behavior from the new version System.ComponentModel for Core.

**Comment by kasper3** [comment]
@superriva, I think what @weshaggard meant is isolated steps to reproduce:

* create a github repository called "MEF1-Bug"
* push your example project that is failing with new MEF1 myget package using .NET Core 2.0 and working with old MEF1 nuget package using .NET 4.6
* explain how to build and reproduce the bug in readme

**Comment by superriva** [comment]
@kasper3 
@weshaggard 
Please, see the repo. Thanks!
https://github.com/superriva/MEF_examples

**Comment by weshaggard** [comment]
Thanks for the repro projects @superriva I was able to repro your issue and I believe I can explain what is going on. You are using a DirectoryCatalog which in turn creates a set of AssemblyCatalog's and it swallows any errors from assemblies it cannot load (this information can be seen in the debugger output if you run in debugger). The reason the assembly cannot be loaded is because AssemblyCatalog  is using an Assembly.Load(AssemblyName) API to try and load the assembly. That API will only be able to load assemblies that are statically referenced by the application. That is just how the assembly binder in .NET Core works it will only load things that are statically in the deps.json file with the application. If you want to have custom assembly loading then you need to handle assembly loading events via AssemblyLoadContext, which I suspect is probably more then you want to do in this simple example. Instead I suggest you not use DirectoryCatalog and load the assemblies dynamically yourself with some code similar to:

```
 var directoryPath = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "ExportComponents\\Components");

foreach(var assemblyPath in Directory.GetFiles(directoryPath, "*.dll"))
{
    Assembly asm = Assembly.LoadFrom(assemblyPath);
    aggregateCatalog.Catalogs.Add(new AssemblyCatalog(asm));
 }
```
Note you probably want to handle some potential assembly loading failures cases. Also note that to load the assembly in this case I'm using Assembly.LoadFrom which will load from a fully qualified path as opposed to by AssemblyName which is why this loading works.

@superriva Can you give that a try and see if it works for you?

@danmosemsft @maryamariyan we probably should look a little further into improving the DirectoryCatalog/AssemblyCatalog in .NET Core case. We should also look into improving the diagnostics we are outputting, currently the errors are kind of hidden and you have to know to look at the debugger output.

**Comment by superriva** [comment]
@weshaggard 
- yes, I have seen errors in the debugger output
- yes, your code works. But this code could be inside MEF. And DirectoryCatalog could work for dynamic loading dll in the MEF Core like old MEF. Is it possible to add such functionality?

**Comment by kasper3** [comment]
Found a related issue https://github.com/dotnet/coreclr/issues/15982. What I understood from @jkotas' comment is, either MEF1 implementation provide a dynamic loading of assembly, Microsoft.Extensions.DependencyModel become more permissive and allow us to load assembly beyond what gets listed in deps.json, or the responsibility is shifted to consumer code (which would be a pain).

Also see @natemcmaster comment: https://github.com/dotnet/corefx/issues/11639#issuecomment-363517719

Another related issue https://github.com/dotnet/core-setup/issues/1739

**Comment by safern** [comment]
@weshaggard so from what I understand this is not a bug right? Just want to triage the issue the right way to see if it is 2.1 priority. 

> @danmosemsft @maryamariyan we probably should look a little further into improving the DirectoryCatalog/AssemblyCatalog in .NET Core case. We should also look into improving the diagnostics we are outputting, currently the errors are kind of hidden and you have to know to look at the debugger output.

Maybe we should open a 2.1 issue for this to improve this.

> But this code could be inside MEF. And DirectoryCatalog could work for dynamic loading dll in the MEF Core like old MEF. Is it possible to add such functionality?

@superriva I guess that would be a new API, right?

**Comment by weshaggard** [comment]
>@weshaggard so from what I understand this is not a bug right?

I'd say this is a bug in the .NET Core implementation. It makes DirectoryCatalog unusable for dynamically loading assemblies in MEF, which is its primary job. 

> But this code could be inside MEF. And DirectoryCatalog could work for dynamic loading dll in the MEF Core like old MEF. Is it possible to add such functionality?

I don't think it needs to be a new API we can fix this in the impelmentation. My suggestion is to keep the existing code path but handle Assembly.Load exceptions and attempt a fallback of an Assembly.LoadFrom to try and make more scenarios work on .NET Core.

**Comment by safern** [comment]
@superriva would you like to work on this issue throwing a PR with @weshaggard's suggestion?

**Comment by safern** [comment]
PR is good to go, we're just waiting for CI to be green but it has been broken since yesterday.

**Comment by superriva** [comment]
Could you add the patch to myget version package to testing.

**Comment by safern** [comment]
@superriva the package will be produced on the next build, tomorrow it will be available and will be the latest version with the preview3 label on it, and obviously this fix will make it to the NuGet stable version.

**Comment by superriva** [comment]
@safern it's very good. Thanks.
I have tested 4.5.0-preview3-26323-01 and it seems to me it's patched already.

**Comment by tdav** [comment]
`
  [Export(typeof(IDbProviders))]
    public partial class RdmWorks : IDbProviders, IDisposable
    {
        public NpgsqlCommand Cmd;
        public NpgsqlConnection Conn;
        public string Name => "Wt.Rdm.PostgreSql";
...
}
public class PluginManager
    {
        [Import]
        private static IDbProviders db { get; set; }

        public static void Load(string directory)
        {
            var assemblies = Directory.GetFiles(directory, "Wt.Rdm.*.dll").Select(AssemblyLoadContext.Default.LoadFromAssemblyPath);
            var configuration = new ContainerConfiguration().WithAssemblies(assemblies);

            using (var con = configuration.CreateContainer())
            {
                db = con.GetExport<IDbProviders>();
            }
        }
    }
`
