### ISSUE TITLE
PlatformNotSupportedException on Unix when exporting multiple private keys in a single PFX

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#2743]
The beta7 PFX/PKCS12 export code will use OpenSSL's PKCS12_create function, which only supports one private key.

OpenSSL doesn't have an inherent limitation against PKCS12 files containing multiple private keys, but the helper function can't handle it; and we're running out of time in beta7 to write it out longhand.

**Comment by vcsjones** [comment]
I could possibly do a PR for this. Is the code path for this `X509Certificate2Collection.Export` with the content type set to PKCS12?
