### ISSUE TITLE
Add SafeFindHandle

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#27446]
## Motivation
Handles returned by FindFirstFile on Windows should be closed with FindClose, not CloseHandle. Therefore a SafeFileHandle or similar is not appropriate for it. We have a SafeFindHandle internally, if we expose it publicly it is not necessary to reinvent it.

## API

```c#
namespace Microsoft.Win32.SafeHandles
{
    public sealed partial class SafeFindHandle : Microsoft.Win32.SafeHandles.SafeHandleZeroOrMinusOneIsInvalid
    {
        protected override bool ReleaseHandle() { throw null; }
    }
}
```

## Implementation 

```c#
    internal sealed class SafeFindHandle : SafeHandle
    {
        protected override bool ReleaseHandle()
        {
            return Interop.Kernel32.FindClose(handle);
        }
    }
```

cc @JeremyKuhne

**Comment by jkotas** [comment]
We should be exposing handles like this only if we need them in the public surface area for other reason. Do we need this in public area anywhere?

**Comment by jkotas** [comment]
It is expected that interop definitions in 3rd party libraries is going to have some redundancy with the interop done by the framework internally.

**Comment by danmosemsft** [comment]
Fair enough. What's the reason - slippery slope, no end to the number of interop types we could provide? We certainly offer plenty of types we don't use ourselves.
