### ISSUE TITLE
AuthenticateAsServerAsync fails on Ubuntu with SSL routines:ssl3_get_client_hello:no shared cipher

### ISSUE THREAD

**Issue by oliverw** [dotnet/corefx#27450]
The following code works fine when running under .Net Core 2.0 on Windows 10 with both Windows and Linux clients. 

```
var tlsCert = new X509Certificate2(tlsPfxFile);

var server = new Socket(SocketType.Stream, ProtocolType.Tcp);
server.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, true);
server.Bind(port.IPEndpoint);
server.Listen(512);

var socket = await server.AcceptAsync();
socket.NoDelay = true;

var stream = (Stream) new NetworkStream(socket, true);
var sslStream = new SslStream(stream, false);
await sslStream.AuthenticateAsServerAsync(tlsCert, false, SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12, false);
```

Running the same code on Ubuntu (either real Ubuntu or Windows Subsystem for Linux) fails with:

> TLS init failed: A call to SSPI failed, see inner exception.: Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher
>    --- End of inner exception stack trace ---
>    at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
>    at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, Boolean isServer, Boolean remoteCertRequired)
>

**Comment by wfurt** [comment]
can you please dump your certificate? Make sure it does not contain any weak algorithm - like md5. 
What do you use as ssl client? 
If you could share more complete repo with test data, I can take a look.

**Comment by oliverw** [comment]
@wfurt Could you elaborate what you mean with dump?

**Comment by wfurt** [comment]
something like 'openssl x509 -text < cert.pem' You can also try packet captures. 
At this point there is not enough information to investigate. 
Alternatively,  create small console app as repro and I can take a look.

**Comment by oliverw** [comment]
Here's the dump from the self-signed certificate. I've also tested with real wildcard certificate from Commodo which resulted in the same error as outlined in my initial post.

Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            99:3c:d7:95:ed:f9:c1:91
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = heimdall
        Validity
            Not Before: Feb 14 11:12:38 2018 GMT
            Not After : Feb 12 11:12:38 2028 GMT
        Subject: CN = heimdall
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:d8:c2:7f:d9:d8:c3:bb:df:8b:15:ec:45:82:8e:
                    3a:b9:a4:3f:22:90:de:f1:78:48:0b:b4:d2:be:fc:
                    bd:d7:94:9b:da:f2:a5:e1:15:13:5b:2b:f0:31:b9:
                    83:4f:3e:22:ba:97:dc:d3:0f:ee:88:a6:19:94:26:
                    dc:57:ae:40:ff:b3:e9:5d:8d:90:da:0d:7b:d3:4d:
                    6c:65:c1:df:b7:92:4b:80:e6:da:52:82:ec:91:79:
                    3e:a8:0e:54:38:b0:21:6e:6b:8f:61:9c:de:7e:46:
                    0b:58:c1:fc:44:98:92:86:f9:13:5a:1b:95:b1:0d:
                    52:2f:9a:f2:61:4e:22:4a:ae:13:a6:62:c9:72:3d:
                    16:3e:59:2c:c8:2d:1c:e1:91:4b:b7:99:26:e3:70:
                    0a:ae:3d:af:89:67:35:54:4d:1a:12:7c:54:1c:fb:
                    b8:ac:33:09:d0:98:4f:86:17:28:95:53:15:d4:67:
                    8c:7c:c3:d6:09:b5:99:f7:de:08:3e:bf:17:30:42:
                    29:0d:0b:32:75:00:fc:29:d8:f6:17:d9:bb:22:e7:
                    ee:a5:c4:2b:2b:a2:89:b9:88:b9:0f:f8:0d:78:3f:
                    2f:37:be:85:cd:17:51:cf:25:e5:4c:7d:15:53:10:
                    f2:17:1d:b3:c9:de:f9:a3:7f:52:f8:d9:02:5b:17:
                    5a:63
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints:
                CA:FALSE
            X509v3 Subject Alternative Name:
                DNS:heimdall
    Signature Algorithm: sha256WithRSAEncryption
         6e:24:d5:85:80:33:3e:ea:ee:b6:db:19:9c:a3:83:70:71:7f:
         11:20:7f:d4:0f:e1:95:f8:ec:42:46:b2:f1:ae:80:54:8b:45:
         f7:cf:b7:f1:5e:68:20:ce:ed:5e:cb:94:8c:b1:4b:99:af:7e:
         b8:34:e6:e3:42:43:a6:4d:89:cd:db:27:b4:9f:28:56:d3:f4:
         e3:cf:e7:ba:70:13:27:7f:3a:37:8b:b7:a7:b5:a2:fc:fc:4e:
         3d:fe:5a:9d:f3:83:da:bf:f2:91:f6:00:92:af:94:38:34:18:
         d7:dc:56:18:f4:63:e9:85:1d:ee:92:da:38:50:33:09:c4:f6:
         36:fe:5f:e6:74:1d:03:79:1a:0b:f8:bb:b2:40:18:21:33:84:
         31:45:f0:f2:f4:e8:c8:d5:3d:71:63:b1:cf:62:73:cc:62:46:
         33:83:a2:69:a8:e4:3c:84:1c:15:84:be:3d:77:a1:96:eb:85:
         6e:47:1e:17:cd:68:da:98:c4:87:5a:a2:bf:70:c3:af:11:27:
         cd:4a:1c:cf:5b:d6:37:1a:79:99:57:e3:42:02:76:e0:99:35:
         f7:44:db:78:63:6e:8d:1e:bf:7e:8b:1d:83:74:74:d4:2a:21:
         cb:ed:a2:c3:bd:56:a6:34:a6:14:1f:37:b8:de:fe:5b:5d:ec:
         ae:9c:8e:c9
-----BEGIN CERTIFICATE-----
MIICyzCCAbOgAwIBAgIJAJk815Xt+cGRMA0GCSqGSIb3DQEBCwUAMBMxETAPBgNV
BAMMCGhlaW1kYWxsMB4XDTE4MDIxNDExMTIzOFoXDTI4MDIxMjExMTIzOFowEzER
MA8GA1UEAwwIaGVpbWRhbGwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQDYwn/Z2MO734sV7EWCjjq5pD8ikN7xeEgLtNK+/L3XlJva8qXhFRNbK/AxuYNP
PiK6l9zTD+6IphmUJtxXrkD/s+ldjZDaDXvTTWxlwd+3kkuA5tpSguyReT6oDlQ4
sCFua49hnN5+RgtYwfxEmJKG+RNaG5WxDVIvmvJhTiJKrhOmYslyPRY+WSzILRzh
kUu3mSbjcAquPa+JZzVUTRoSfFQc+7isMwnQmE+GFyiVUxXUZ4x8w9YJtZn33gg+
vxcwQikNCzJ1APwp2PYX2bsi5+6lxCsroom5iLkP+A14Py83voXNF1HPJeVMfRVT
EPIXHbPJ3vmjf1L42QJbF1pjAgMBAAGjIjAgMAkGA1UdEwQCMAAwEwYDVR0RBAww
CoIIaGVpbWRhbGwwDQYJKoZIhvcNAQELBQADggEBAG4k1YWAMz7q7rbbGZyjg3Bx
fxEgf9QP4ZX47EJGsvGugFSLRffPt/FeaCDO7V7LlIyxS5mvfrg05uNCQ6ZNic3b
J7SfKFbT9OPP57pwEyd/OjeLt6e1ovz8Tj3+Wp3zg9q/8pH2AJKvlDg0GNfcVhj0
Y+mFHe6S2jhQMwnE9jb+X+Z0HQN5Ggv4u7JAGCEzhDFF8PL06MjVPXFjsc9ic8xi
RjODommo5DyEHBWEvj13oZbrhW5HHhfNaNqYxIdaor9ww68RJ81KHM9b1jcaeZlX
40ICduCZNfdE23hjbo0ev36LHYN0dNQqIcvtosO9VqY0phQfN7je/ltd7K6cjsk=
-----END CERTIFICATE-----

**Comment by oliverw** [comment]
Nevermind. It was a problem with the specific client I've used for testing which insanely picky about the chosen cipher.
