### ISSUE TITLE
[API change] Move Memory.TryGetXxx Extensions to MemoryMarshal.TryGetXxx

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#27451]
Proposed api
```csharp
public static class MemoryMarshal
{
    public static bool TryGetString(ReadOnlyMemory<char> readOnlyMemory, out string text, out int start, out int length);
    public static bool TryGetArray(Memory<T> readOnlyMemory, out ArraySegment<T> arraySegment)
}
```
Currently these methods are on `MemoryExtensions` or `Memory` for `TryGetArray` acting directly as methods on `Memory`
```csharp
public static partial class MemoryExtensions
{
    public static bool TryGetString(this ReadOnlyMemory<char> readOnlyMemory, out string text, out int start, out int length);
}
```
```csharp
public static partial struct Memory<T>
{
    public bool TryGetArray(out ArraySegment<T> arraySegment)
}
```
However, for consistency, and because they violate the window of visibility of the `Memory` they should probably move to `MemoryMarshal` to join their other friends `TryGetArray` and `TryGetOwnedMemory`.

/cc @KrzysztofCwalina @stephentoub @ahsonkhan @terrajobst @joshfree @jkotas

**Comment by jkotas** [comment]
Our design pattern has been to use MemoryMarshal for unsafe dangerous non-extension methods that let you violate read-onliness, so that you have to go through extra barrier do that.

`TryGetString(this ReadOnlyMemory<char> readOnlyMemory, ...` is perfectly safe. I guess it is why it is not on MemoryMarshal.

We have a similar by-design inconsistency for TryGetArray: TryGetArray for ReadOnlyMemory is on MemoryMarshal, but TryGetArray for Memory is not.

**Comment by stephentoub** [comment]
> that let you violate read-onliness [...]  TryGetString(this ReadOnlyMemory<char> readOnlyMemory, ... is perfectly safe

That makes sense... since string is itself immutable, unlike array.  I buy that.

**Comment by benaadams** [comment]
It does let you violate the window of the `ReadOnlyMemory<char>` and let you access the whole `string` though?

**Comment by benaadams** [comment]
Same for `TryGetArray ` now you point it out :)

**Comment by stephentoub** [comment]
Yes, though so do Memory.TryGetArray, ArraySegment.TryGetArray, etc. Are you suggesting all of these (that haven't shipped) should be moved to Memory Marshal?

**Comment by benaadams** [comment]
> Yes, though so do Memory.TryGetArray, ArraySegment.TryGetArray, etc. Are you suggesting all of these (that haven't shipped) should be moved to Memory Marshal?

Yes, as they allow you to go outside the constraints of the "contract" of `Memory`/`ReadOnlyMemory` which is a windowed view on the underlying data; loosing some of the "safety" that Memory gains over ArraySegment.

So you might not think twice about doing:
```csharp
if (readOnlyMemory.TryGetString(out string text, out int start, out int length))
{
    return text.AsMemory(0, text.Length);
}
```
However, might pause before doing
```csharp
if (MemoryMarshal.TryGetString(readOnlyMemory, out string text, out int start, out int length))
{
    return text.AsMemory(0, text.Length);
}
```

**Comment by stephentoub** [comment]
I'm fine with that change.

**Comment by terrajobst** [comment]
Argument makes sense, but we don't need the second one as the existing `TryGetArray` covers that.

```csharp
public static class MemoryMarshal
{
    public static bool TryGetString(ReadOnlyMemory<char> readOnlyMemory, out string text, out int start, out int length);
}
````
