### ISSUE TITLE
API Proposal: Add Regex option to enumeration APIs

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#27456]
## Proposal

Now that we have the ability to specify the match type, we should expose `Regex` as an option:

``` C#
namespace System.IO
{
    public enum MatchType
    {
        Simple,
        Win32,

        /// <summary>
        /// Expression is treated as a regular expression.
        /// </summary>
        /// <remarks>
        /// Single line, culture invariant, explicit capture matching is used.
        /// </remarks>
        Regex
    }
}

namespace System.IO.Enumeration
{
    public static class FileSystemName
    {
        public static string TranslateWin32Expression(string expression);
        public static bool MatchesWin32Expression(ReadOnlySpan<char> expression, ReadOnlySpan<char> name, bool ignoreCase = true);
        public static bool MatchesSimpleExpression(ReadOnlySpan<char> expression, ReadOnlySpan<char> name, bool ignoreCase = true);

        /// <summary>
        /// Return true if the given regular expression matches the given name.
        /// </summary>
        /// <remarks>
        /// Uses single line, invariant, explicit capture mode.
        /// </remarks>
        public static bool MatchesRegularExpression(ReadOnlySpan<char> expression, ReadOnlySpan<char> name, bool ignoreCase = true);
    }
}
```
## Motivation

Partners are interested in having this exposed (MSBuild, PowerShell). Even though we don't have a span version of `Regex.IsMatch()`, exposing the API now will allow easier lighting up of higher performance, lower allocation implementations in the future. (As opposed to customers using `IsMatch` directly and needing to update their clients if we provide a span version in the future.)

## Details

- We'll pick sensible RegexOptions as a default (as described in the signature comments)
- Users can override either by using Regex directly or using `?(imnsx)` options in their expressions

**Comment by JeremyKuhne** [comment]
See #18922 
cc: @danmosemsft, @ViktorHofer

**Comment by ViktorHofer** [comment]
Generally I think this is a good idea but what about RegexOptions and RegexTimeout? The latter is a security feature and the former allows more control over the pattern.

**Comment by JeremyKuhne** [comment]
> what about RegexOptions and RegexTimeout? 

@ViktorHofer The idea would be to pick the sensible defaults that fit within the existing enumeration API. If someone wants more fine-grained control they can use the extensibility model and use Regex directly. I think having a timeout is sensible, what would you suggest for a value?  The other options I chose were `Singleline`, `CultureInvariant`, and `ExplicitCapture`. `IgnoreCase` comes from the boolean or the `EnumerationOptions`. Does that sound reasonable?

If we only get an IsMatch that works with span and these options we'd be good for what this needs.

**Comment by danmosemsft** [comment]
I don't think we can pick a good default for timeout, so I would leave it as is (ie infinity). Customers that want to specify a timeout and write their own callback.

I am not sure that ExplicitCapture matters for IsMatch, since nothing is captured (from the user's point of view). There is no harm in specifying it. @ViktorHofer can correct me if necessary.

**Comment by JeremyKuhne** [comment]
> I am not sure that ExplicitCapture matters for IsMatch,

Just my presumption that it would improve perf.

**Comment by JeremyKuhne** [comment]
> I don't think we can pick a good default for timeout

Thinking about it some more I'm not sure I agree. I think having a minute to try and match a filename (<= 256 chars) sounds beyond generous. If customers need to do something crazy they can customize. From a security and discoverability standpoint I think I'd want matches that take more than a few seconds to choke.

**Comment by danmosemsft** [comment]
Is there a means to cancel enumeration? If not even a minute per file could be effectively forever.

**Comment by JeremyKuhne** [comment]
> Is there a means to cancel enumeration?

There isn't, which is part of why I'm thinking seconds at most. @ViktorHofer, what would you expect would be a generous value given the constraints of a 260 character max input?

**Comment by ViktorHofer** [comment]
I think the timeout default (Infinite) should be the same as in Regex. (1) it runs faster with timeout disabled, (2) it is the default in S.T.RegularExpressions. I think be should be consistent here. Processing small inputs should be very fast.

**Comment by danmosemsft** [comment]
That is true, it is faster with no timeout.

**Comment by JeremyKuhne** [comment]
> I think the timeout default (Infinite) should be the same as in Regex. (1) it runs faster with timeout disabled

Ok then, I won't add it.

**Comment by jkotas** [comment]
> MatchType.Regex

This pattern is very unfriendly to tree-shaking. It is close to impossible for the treeshaker do the data flow analysis to figure out that this option is not used. It means that anybody using this file enumeration in standalone app will now carry the regex engine, with its transitive closure.

**Comment by JeremyKuhne** [comment]
>> MatchType.Regex

> This pattern is very unfriendly to tree-shaking. It is close to impossible for the treeshaker do the data flow analysis to figure out that this option is not used. It means that anybody using this file enumeration in standalone app will now carry the regex engine, with its transitive closure

Adding Regex as an option was always part of the initial plan. Any suggestions for alternatives for `MatchType` are very welcome.

**Comment by jkotas** [comment]
https://github.com/dotnet/corefx/pull/27457#discussion_r170482890

**Comment by karelz** [comment]
Moving to Future (per @terrajobst guidance)

**Comment by JeremyKuhne** [comment]
The general gist is that we need to make it easy for tree shakers to remove dependencies if we choose to put implementations of various filters in System.IO.FileSystem (or something that has access to internals). We have access to underlying details that we don't expose and may not want to in the near future (such as the UTF-8 data stream).  The current thinking is to expose a the predicate delegate as an option and add that to the MatchType enum:

```
namespace System.IO
{
    public enum MatchType
    {
        Simple,
        Win32,

        /// <summary>
        /// A predicate delegate is provided in the EnumerationOptions and should be used.
        /// </summary>
        Predicate
    }
}
```

We can provide the other types of matching we are looking at (globstar, posix, regex) as delegates in a way that allows usage to be easily determined by tree shakers.

**Comment by iSazonov** [comment]
MatchType.Predicate looks as redundant - in any case we need a parameter for the predicate so the parameter could replace MatchType parameter like:
```c#
public static IEnumerable<string> EnumerateFileSystemEntries(string path, FindPredicate predicate);
```

**Comment by JeremyKuhne** [comment]
#18922
