### ISSUE TITLE
[Perf] Perf_Marvin Performance Regression of 154%

### ISSUE THREAD

**Issue by brianrob** [dotnet/corefx#27485]
The Perf_Marvin tests regressed ~154% across most of the permutations of input between these commits:

https://github.com/dotnet/corefx/compare/3c4115d601335a61d9d170a71bdfb71eb2177beb...dotnet:90027686dc6ee078ae190bfa471962efeab7a123

I believe it is https://github.com/dotnet/corefx/commit/540a99ce273265ba62a25b48c696d2d506c88ab4, but it took several days to be consumed by CoreCLR through packages and then for CoreFX to consume it via CoreCLR packages.

The commit diff for CoreCLR as consumed by CoreFX in the commit diff above is http://github.com/dotnet/coreclr/compare/2f14b350960af0354608c041d7df501c44dc5640...b11de873286deb1662c8fc106aa3de1df3c1ba79.

**Comment by brianrob** [comment]
@ianhays, can you please take a look?

**Comment by danmosemsft** [comment]
Presumably the change in Marvin.cs itself

https://github.com/dotnet/corefx/commit/540a99ce273265ba62a25b48c696d2d506c88ab4#diff-cd635355a880d8cef033635b10e2e4de

**Comment by ianhays** [comment]
It seems odd that moving the function from [an extension method](https://github.com/dotnet/coreclr/pull/16086/files#diff-34f82797d649dc710c6ff9268fa79c9bL146) to [a static method](https://github.com/dotnet/coreclr/pull/15941/files#diff-e750031deb88b351cd899d5eb933209dR54) would cause such a large regression. [The perf test doesn't appear to be doing anything unusual that would explain the difference.](https://github.com/dotnet/corefx/blob/master/src/Common/tests/Performance/Perf.Marvin.cs#L31)

Was this a netcoreapp run?

cc: @jkotas

**Comment by jkotas** [comment]
I think that the problem is caused by the removed AggressiveInlining in https://github.com/dotnet/coreclr/pull/16091/commits/93ec62347a4e97b920513296eefb27bdacbecfe9.

**Comment by ianhays** [comment]
The AggressiveInlining attribute was removed per suggestion of @AndyAyersMS [here for CoreFX](https://github.com/dotnet/corefx/pull/26467#issuecomment-361162516) before [being flowed back to the coreclr versions](https://github.com/dotnet/coreclr/pull/16091/files#diff-e750031deb88b351cd899d5eb933209dL53).

Seems like we will want to add it back.

**Comment by AndyAyersMS** [comment]
Given how unoptimizable the checked math is in `MemoryMarshal.Cast` I'm surprised inlining would lead to a significant perf improvement on its own. But maybe it's an indirect benefit -- perhaps inlining enables more widespread struct promotion in `ComputeHash` and so the surrounding code improves.

**Comment by AndyAyersMS** [comment]
Looks like ``Marvin.Compare` is the same size (445 bytes) with or without the inlined casts -- the size savings from the struct promotion that inlining enables counterbalances the size increase from the unchecked math blobs that get inlined. 

The inlined version clearly has shorter path length, likely especially so for short data lengths.

So yes we should add back `AggressiveInlining`.

**Comment by stephentoub** [comment]
Was this fixed by https://github.com/dotnet/coreclr/pull/16654 (and maybe https://github.com/dotnet/coreclr/pull/16659)?

**Comment by AndyAyersMS** [comment]
Seems likely.

Would like to add a vote here for using ratios instead of percentages. Regression was 134% and improvement was 56%. Not easy to parse either side of this. Before peeking at the chart, below try and sketch what this would look like on a graph. 

<details>
At least for me, 134% somehow doesn't make it sound as bad as it was, and 56% doesn't seem like it should cancel out 134%. Citing this as a slowdown of 2.3x and speedup of 2.3x makes it easier to quickly understand what happened.

![image](https://user-images.githubusercontent.com/10121823/36908016-fa9c5fb8-1dee-11e8-9706-3ccaad367b16.png)
</details>

**Comment by brianrob** [comment]
This does appear to be fixed.
