### ISSUE TITLE
Update System.Memory package description to be complete

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#27481]
Right now it only includes Span within the description.
https://github.com/dotnet/corefx/blob/3c708ab64564304fed352355b52e2ea047860e4d/pkg/descriptions.json#L1004

cc @KrzysztofCwalina, @dotnet/corefxlab-contrib, @pakrym, @davidfowl

**Comment by joshfree** [comment]
Fixed by https://github.com/dotnet/corefx/pull/27888
