### ISSUE TITLE
Mark Microsoft.XmlSerializer.Generator as NonShipping=true (product construction)

### ISSUE THREAD

**Issue by dagood** [dotnet/corefx#27482]
In orchestrated builds, `Microsoft.XmlSerializer.Generator` should be marked `NonShipping="true"` because it's not meant to be published to the NuGet Gallery.

Example manifest without NonShipping:

https://github.com/dotnet/versions/blob/beb08dc78641604883b17ee3010e602378b1c361/build-info/dotnet/product/cli/release/2.1/build.xml#L371

We will start to rely on this attribute with automated pushes: https://github.com/dotnet/core-eng/issues/2334.

/cc @weshaggard

**Comment by weshaggard** [comment]
cc @zhenlan

**Comment by dagood** [comment]
Some extra context: the marked packages are configured here (ideally this will be refactored to be defined in the project, rather than path globs, for maintainability):
https://github.com/dotnet/corefx/blob/d9e55a9f6c0deacd7ec1b866faffaeeeedef4b7e/src/publish.proj#L31-L41

The metadata is described here: [publish.md#adding-custom-information](https://github.com/dotnet/core-eng/blob/master/Documentation/Orchestrated-Build/Api/publish.md#adding-custom-information)

**Comment by zhenlan** [comment]
We actually like to include `Microsoft.XmlSerializer.Generator` be part of 2.1 preview1 release.

cc: @huanwu

**Comment by dagood** [comment]
Oh, cool! Just to confirm, I have [`Microsoft.XmlSerializer.Generator 2.0.0-preview1-26216-02`](https://dotnetfeed.blob.core.windows.net/orchestrated-release-2-1/20180216-05/final/flatcontainer/microsoft.xmlserializer.generator/2.0.0-preview1-26216-02/microsoft.xmlserializer.generator.2.0.0-preview1-26216-02.nupkg) prepared to push. Is that right?

**Comment by zhenlan** [comment]
Yes, that's right. Thanks, @dagood.

**Comment by dagood** [comment]
No problem. Pushed: https://www.nuget.org/packages/Microsoft.XmlSerializer.Generator/2.0.0-preview1-26216-02
