### ISSUE TITLE
Warning of serializer generation failure when there are just no types serializable

### ISSUE THREAD

**Issue by zhenlan** [dotnet/corefx#27488]
When there are no types found to pre-gen serializers, I got warning below, which is a bit confusing. Ideally, I can be told the real reason.

c:\users\xxxxx\\.nuget\packages\microsoft.xmlserializer.generator\2.0.0-preview1-26216-02\build\Microsoft.XmlSerializer.Generator.targets(16,5): warning : SGEN : warning SGEN1: Fail to generate the serializer for test-sgen.dll. Please follow the instructions at https://go.microsoft.com/fwlink/?linkid=858594 and try again. [C:\Temp\test-sgen\test-sgen.csproj]

**Comment by zhenlan** [comment]
Can we please also fix the repeated warning message "warning : SGEN : warning SGEN1: " with just one "warning:"?

**Comment by huanwu** [comment]
@zhenlan The first error is coming from SGEN. The second is coming from the targets. We will always throw this message if no serialization file generated. We can modify to a different message.

**Comment by yujayee** [comment]
@zhenlan @huanwu I submitted a pr to fix the repeated warning messages in target file. Then to solve the issue, we still need to figure out how to show warning messages from sgen(which has more specific warning messages) instead of target file.

**Comment by zhenlan** [comment]
Yes, sounds good. Thanks @yujayee!
