### ISSUE TITLE
Japanese calendar test failures locally

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#27506]
I deterministically get these test failures when I run the tests in the repo locally:
```
     System.Globalization.Tests.MiscCalendarsTests.JapaneseTest [FAIL]
        Assert.Equal() Failure
        Expected: 2019-01-08T00:00:00.0000000
        Actual:   1989-01-08T00:00:00.0000000
        Stack Trace:
           d:\repos\corefx\src\System.Globalization.Calendars\tests\Misc\MiscCalendars.cs(44,0): at System.Globalization.Tests.MiscCalendarsTests.JapaneseTest()
     System.Globalization.Tests.JapaneseCalendarEras.Eras [FAIL]
        Assert.Equal() Failure
        Expected: Int32[] [4, 3, 2, 1]
        Actual:   Int32[] [5, 4, 3, 2, 1]
        Stack Trace:
           d:\repos\corefx\src\System.Globalization.Calendars\tests\JapaneseCalendar\JapaneseCalendarEras.cs(14,0): at System.Globalization.Tests.JapaneseCalendarEras.Eras()

     System.Globalization.Tests.CalendarHelpers.ToDateTime_Invalid(calendar: JapaneseLunisolarCalendar { AlgorithmType = LunisolarCalendar, Eras = [5, 4, 3], IsReadOnly = False, MaxSupportedDateTime = 2050-01-22T23:59:59.9999999, MinSupportedDateTime =
  1960-01-28T00:00:00.0000000, ... }) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentOutOfRangeException)
        Actual:   (No exception was thrown)
        Stack Trace:
           d:\repos\corefx\src\System.Globalization.Calendars\tests\CalendarHelpers.cs(347,0): at System.Globalization.Tests.CalendarHelpers.ToDateTime_Invalid(Calendar calendar)
```

**Comment by Clockwork-Muse** [comment]
It appears that Microsoft is getting the jump on assigning the era year; [the emperor is planning on abdicating next year](http://theindependent.in/japanese-emperor-akihito-to-abdicate/).  I'm not 100% sure when the era year itself will change: whether the new era will start in 2019 or 2020.  It was previously seen as starting in 2019...[when it was considered to be abdicating in _2018_](https://www.japantimes.co.jp/news/2017/05/19/national/politics-diplomacy/japan-may-announce-new-imperial-era-name-summer-2018/#.WpXQh-jwbmE).  
There doesn't appear to be an era name set yet, either, which means the parsing tests should be broken as well (no abbreviated name to test the parse against).

I'm unsure whether to consider it a documentation bug that the docs for the Japanese calendar types don't mention the new era, or just leaving it as "there might be more eras in the future" is fine.

**Comment by danmosemsft** [comment]
@tarekgh there was a conversation about this a couple weeks ago - I guess this means that @stephentoub received a Windows patch?

**Comment by krwq** [comment]
Yes, some RS4 and later machines get a placeholder value with new Era in the registry. The tests have hardcoded values and they fail. The simplest workaround for now is to remove following value in the registry:
Key: `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\Calendars\Japanese\Eras`
String Value: `2019 05 01`

If this starts failing in the CI I will disable the tests - assuming this code got ported correctly from desktop this is a test issue.

If those are the only 3 tests failing I can pick this up

**Comment by tarekgh** [comment]
@krwq could you please fix the test as you did in the full framework?
