### ISSUE TITLE
[API Change] Drop `IMemoryList` and replace with abstract `ReadOnlySequenceSegment`

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#27500]
Alternative to "Remove RunningIndex add a way for IMemoryList to provide seek implementation" https://github.com/dotnet/corefx/issues/27435

The is a performance issue with `ReadOnlySequence` as accessing the properties of its segments have to go via interface dispatch which makes them slower an non-inlineable.

Proposed api:
```csharp
public abstract class ReadOnlySequenceSegment<T>
{
    public ReadOnlyMemory<T> Memory { get; protected set; }
    public ReadOnlySequenceSegment<T> Next { get; protected set; }
    public long RunningIndex { get; protected set; }
}
```
Changing to an `abstract` class with `protected` setters and non-virtual properties makes them inlinable and fast. The `ReadOnlySequence` doesn't care what the segments are, only that thy have these properties and then it can perform all of its functions:

Removing
```csharp
public interface IMemoryList<T>
{
    public Memory<T> Memory { get; set; }
    public IMemoryList<T> Next { get; set; }
    public long RunningIndex { get; set; }
}
```

More functionality can't be delegated via the interface as in https://github.com/dotnet/corefx/issues/27435 as that will cause greater performance issues for mixed segment type `ReadOnlySequence`s as every call will have to go via the interface for the next block as its real type is unknown.

With the above approach it doesn't need to know what the next block is; it can use the fast base properties.

The total change in Pipelines to work with this faster approach is: (and PR for the change https://github.com/dotnet/corefx/pull/27499/commits/63ddad596763675165015c496e9647ee449adec1 )
```diff
- internal partial sealed class BufferSegment : IMemoryList<byte>
+ internal partial sealed class BufferSegment : ReadOnlySequenceSegment<byte>
  {
+     private BufferSegment _next;
  
-     public BufferSegment NextSegment { get; set; }
+     public BufferSegment NextSegment
+     {
+         get => _next;
+         set
+         {
+             _next = value;
+             Next = value;
+         }
+     }
-     public long RunningIndex { get; private set; }
-     public Memory<byte> Memory { get; private set; }
-     public IMemoryList<byte> Next => NextSegment;
  }
```

/cc @davidfowl @KrzysztofCwalina @pakrym @ahsonkhan @stephentoub

**Comment by benaadams** [comment]
Bottom numbers after the effect for 1 and 100 segments; top is current

```        
                                         Method |   Categories |        Mean |         Op/s | Scaled |
----------------------------------------------- |------------- |------------:|-------------:|-------:|
                'ReadOnlySequence<T> (current)' |    1 segment |   105.64 ns |  9,466,500.4 |   1.00 |
 'ReadOnlySequence<T> (PR dotnet/corefx#27455)' |    1 segment |    85.58 ns | 11,684,611.4 |   0.81 |
 'ReadOnlySequence<T> (PR dotnet/corefx#27499)' |    1 segment |    75.63 ns | 13,222,618.8 |   0.72 |
                                                |              |             |              |        |
                'ReadOnlySequence<T> (current)' | 100 segments | 1,373.21 ns |    728,221.4 |   1.00 |
 'ReadOnlySequence<T> (PR dotnet/corefx#27455)' | 100 segments |   949.87 ns |  1,052,777.5 |   0.69 |
 'ReadOnlySequence<T> (PR dotnet/corefx#27499)' | 100 segments |   237.14 ns |  4,216,948.2 |   0.17 |
```

**Comment by KrzysztofCwalina** [comment]
While we are at this, should ReadOnlySequenceSegment inherit from OwnedMemory?

**Comment by benaadams** [comment]
Don't think so; its more a holder for chaining chunks rather than the owner e.g. the BufferSegment in pipes gets given Owned memory chunks to use; and you might want windows on the same `string` with a set of `StringSegment : ReadOnlySequenceSegment`

For the benchmark above it was the same `OwnedMemory` added to; and chained, with that many segments.

**Comment by KrzysztofCwalina** [comment]
Windows can be created using ReadOnlySequence. Why do we need a window over a window over ownedmemory?

**Comment by pakrym** [comment]
@KrzysztofCwalina We had non-interface IMemoryList but you wanted to implement it on things, so we went with the interface.

**Comment by benaadams** [comment]
> Windows can be created using ReadOnlySequence. Why do we need a window over a window over ownedmemory?

It can currently only hold a single `string`, `OwnedMemory`, `T[]`; or a chain of things. This is how to chain `string`, `OwnedMemory`, `T[]` etc. You can do a window, but you can't then attach it to another one (without using the interface which has the terribad perf)

**Comment by benaadams** [comment]
e.g. this is the final item in each category `(PR dotnet/corefx#27499)`

**Comment by KrzysztofCwalina** [comment]
@pakrym, I think you are talking about OwnedMemory. I wanted to make it an interface so we can implement it on string/T[]. 

And regardless, I feel like we now have franken design here. The abstraction is not efficient and cannot be implemented as anything but linked list (because we don't embrace SequencePostion).

**Comment by KrzysztofCwalina** [comment]
@benaadams, yeah, restitching would not work.
