### ISSUE TITLE
Microsoft.NETCore.App version required in netcoreapp2.1 preview

### ISSUE THREAD

**Issue by eduherminio** [dotnet/corefx#27508]
A .NET Core Web API project targeting `netcoreapp2.1` requires right now
`Microsoft.NETCore.App >= 2.1.0-preview2-26131-06`, which doesn't seem to exist in NuGet (yet).

**Comment by superriva** [comment]
@eduherminio 
May be it will help you https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.NETCore.App

**Comment by joshfree** [comment]
Here is a link to the dogfooding instructions; including advanced scenarios of using a nightly build from the dotnet.myget.org feed:

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md#advanced-scenario---using-a-nightly-build-of-microsoftnetcoreapp 

If you want to install .NET Core 2.1 Preview 1, it is available today on nuget.org.

Blog Posts
•	[.NET Core](https://blogs.msdn.microsoft.com/dotnet/2018/02/27/announcing-net-core-2-1-preview-1/)
•	[ASP .NET Core](https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-0-preview1-now-available/)
•	[Entity Framework Core](https://blogs.msdn.microsoft.com/dotnet/2018/02/27/announcing-entity-framework-core-2-1-preview-1/)


Downloads
•	https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300-preview1
•	https://www.microsoft.com/net/download/dotnet-core/runtime-2.1.0-preview1
