### ISSUE TITLE
[Perf][Windows_NT] Investigate System/Runtime/Serialization/Xml/Tests/Performance/DcsPerformanceTest Improvement/Regression between release/2.0.0 and release/2.1

### ISSUE THREAD

**Issue by jorive** [dotnet/corefx#27516]
There are multiple improvement/regressions across this noisy suite +/-4%.

**Comment by huanwu** [comment]
@jorive Could you provide more context/details about this issue

**Comment by danmosemsft** [comment]
I think @jorive did not get this. 

This should show the changes
https://benchview/trendline?build_selector=latest&count=2000&aggregate=arithmeticMean&filterTail=one&filterVal=100&interval=INTERVAL_MIN_MAX&rtids=[957]&archids=[23]&mpids=[1292]&cfgids=[2785,2706]&testids=[61647,61602,61698]&jobid=94550&

It takes a few sec to render. Let me know if you need a hand.

DcsPerformanceTest looks like it's a little regressed over 2.0 (the dotted line/left side)

**Comment by huanwu** [comment]
We can consider it as noisy since it is less than 5%.
