### ISSUE TITLE
[Perf] Investigate System/Threading/Channels benchmark improvement in 2.1

### ISSUE THREAD

**Issue by valenis** [dotnet/corefx#27517]
[Perf] Investigate System/Threading/Channels benchmark improvement in 2.1

Several async tests in Channels show improvements for 2.1, most likely due to:
https://github.com/dotnet/corefx/commit/ce0de73e21635252ceffdb140d3a56c6c19bb565

**Comment by stephentoub** [comment]
@valenis, System.Threading.Channels is brand new in 2.1 :smile:
