### ISSUE TITLE
[Perf][Windows_NT] Investigate System/Runtime/Serialization/Json/Tests/Performance/JsonNetPerformanceTest Improvement/Regression between release/2.0.0 and release/2.1

### ISSUE THREAD

**Issue by jorive** [dotnet/corefx#27513]
There are multiple improvement/regressions across this noisy suite +/-4%.

**Comment by huanwu** [comment]
@jorive Could you provide more context/details about this issue

**Comment by huanwu** [comment]
We can consider it as noisy since it is less than 5%.
