### ISSUE TITLE
[Regression][Linux] System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test / GetAsync_AllowedSSLVersion_Succeeds

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#27527]
### Server returned nothing (no headers, no data)

```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.CurlException : Server returned nothing (no headers, no data)

at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in /root/corefx-1420690/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 469
at System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.<>c__DisplayClass4_0.<<GetAsync_AllowedSSLVersion_Succeeds>b__0>d.MoveNext() in /root/corefx-1420690/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.SslProtocols.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /root/corefx-1420690/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 67
at System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.GetAsync_AllowedSSLVersion_Succeeds(SslProtocols acceptedProtocol, Boolean requestOnlyThisProtocol) in /root/corefx-1420690/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.SslProtocols.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error) in /root/corefx-1420690/src/System.Net.Http/src/System/Net/Http/CurlHandler/CurlHandler.cs:line 661
at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult) in /root/corefx-1420690/src/System.Net.Http/src/System/Net/Http/CurlHandler/CurlHandler.MultiAgent.cs:line 883
```

## Failure history

Day | Build | OS | Details
-- | -- | -- | -- 
2/21 | 20180221.05 | RedHat69 | 
2/23 | 20180223.04 | Ubuntu17.10 | 
2/23 | 20180223.06 | Suse12 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180223.06/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test~2FGetAsync_AllowedSSLVersion_Succeeds(acceptedProtocol:%20Tls,%20requestOnlyThisProtocol:%20True))
2/23 | 20180223.06 | Ubuntu18.04 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180223.06/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test~2FGetAsync_AllowedSSLVersion_Succeeds(acceptedProtocol:%20Tls,%20requestOnlyThisProtocol:%20True))
2/24 | 20180224.02 | Suse12 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180224.02/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test~2FGetAsync_AllowedSSLVersion_Succeeds(acceptedProtocol:%20Tls,%20requestOnlyThisProtocol:%20True))
2/26 | 20180226.02 | Ubuntu14.04 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180226.02/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test~2FGetAsync_AllowedSSLVersion_Succeeds(acceptedProtocol:%20Tls,%20requestOnlyThisProtocol:%20True))
2/27 | 20180227.01 | Ubuntu14.04 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180227.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test~2FGetAsync_AllowedSSLVersion_Succeeds(acceptedProtocol:%20Tls,%20requestOnlyThisProtocol:%20True))
2/28 | 20180228.03 | Debian90
2/28 | 20180228.03 | Ubuntu16.04
2/28 | 20180228.03 | OpenSuse42.3
2/28 | 20180228.04 | OpenSuse42.3
2/28 | 20180228.04 | RedHat69
2/28 | 20180228.07 | SLES12
3/1 | 20180301.01 | Ubuntu14.04
3/1 | 20180301.04 | OpenSuse42.3
3/5 | 20180305.03 | Debian90
3/7 | 20180307.04 | RedHat69
3/8  | 20180308.09 | OpenSuse42.3
3/13 | 20180313.01 | SLES12
3/18 | 20180318.01 | Ubuntu17.10
4/2 | 20180402.05 | SLES12
4/3 | 20180403.04 | RedHat69

**Comment by karelz** [comment]
This seems to be a recent regression - @wfurt @geoffkizer @stephentoub @davidsh do you know about any changes in the area / in the test infra?

**Comment by davidsh** [comment]
This test is using a loopback server. So, it is not test infra that would break this.  But perhaps something with SslStream which is used by the loopback server to toggle different TLS protocol versions for the test.

**Comment by caesar1995** [comment]
There are 45 occurrences from 2018/02/20 to 2018/03/13. (The most recent failure is in 2018/03/13).

Not able to repro in my Ubuntu VM.

**Comment by karelz** [comment]
Can you try it via repro tool?

**Comment by caesar1995** [comment]
I'll try it.

I will work on Windows issue #25640 first.

**Comment by caesar1995** [comment]
Just a note: the test is not failing in CI after I enable it in the test PR #28481

**Comment by karelz** [comment]
History of failures updated - there are couple of clustered failures. I wonder if it may be a problem due to external server?

**Comment by caesar1995** [comment]
Manually run the test several times through repro tool, no failure. Repro tool will quit itself during hang/completed command sometimes (at least in RedHat69), makes it hard to run the test in a loop.

Checked Kusto, no failure after 03/13 from all test sources. Likely server side issue (not properly sending response), since it's not disabled test, it could has been resolved. We can postponed to future.

@karelz

**Comment by davidsh** [comment]
>Likely server side issue (not properly sending response),

This test uses the loopback server. So, I don't see how it could be a "server side issue".
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.SslProtocols.cs#L96

**Comment by karelz** [comment]
OK, let's monitor how frequently it will fail from now on. Future milestone is ok.

**Comment by caesar1995** [comment]
New failure with [Ubuntu.1604.Amd64.Open-x64-Debug](https://mc.dot.net/#/user/caesar1995/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/cb9f9b1a6b9ea655ae87929e913824215495480b/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_SslProtocols_Test~2FGetAsync_AllowedSSLVersion_Succeeds(acceptedProtocol:%20Tls,%20requestOnlyThisProtocol:%20False))

**Comment by davidsh** [comment]
Haven't seen this failure in a long time.  Closing for now.
