### ISSUE TITLE
unable to parse IPv6 link-local address with interface name

### ISSUE THREAD

**Issue by wfurt** [dotnet/corefx#27529]
https://tools.ietf.org/html/rfc4007#section-11.3

The example shows ff08::9abc%interface10 and Unix systems generally use  address%if_name notation. (https://en.wikipedia.org/wiki/IPv6_address) 

> furt@Ubuntu:~/ipv6$ ping6 fe80::108e:ac5e:1999:d42f%enp0s5
> PING fe80::108e:ac5e:1999:d42f%enp0s5(fe80::108e:ac5e:1999:d42f) 56 data bytes
> ....
> 

however 
```C# 
IPAddress.Parse("fe80::108e:ac5e:1999:d42f%enp0s5")
Unhandled Exception: System.FormatException: An invalid IP address was specified. ---> System.Net.Sockets.SocketException: Invalid argument
```
throws exception. The c# parser assumes that the zoneid can only be integer. 
On Linux and macOS this can be either interface index or valid interface name.

**Comment by kasper3** [comment]
There are two copies of IPv6AddressHelper.cs, the one in System.Private.Uri is more recent. Can one of those be removed when addressing this issue?

**Comment by kasper3** [comment]
https://github.com/dotnet/corefx/blob/e3ecae6/src/System.Net.Primitives/src/System/Net/IPv6AddressHelper.cs#L152-L156

Removing this condition would fix the issue. In other implementation, it would be a different fix.

**Comment by wfurt** [comment]
good find @kasper3 . But it is not just allowing string. We will need some function to find interface id from the string. Without  it, OS calls would still fail.

**Comment by kasper3** [comment]
Found this huge regex to validate IPV6 https://stackoverflow.com/a/17871737, the line that deals with zone index seems interesting `fe80:(:IPV6SEG){0,4}%[0-9a-zA-Z]{1,}|  # fe80::7:8%eth0     fe80::7:8%1  (link-local IPv6 addresses with zone index)`

**Comment by wfurt** [comment]
That may be good enough for input validation @kasper3. For this to actually work, we will need to convert interface name to interface index e.g. scope.

**Comment by kasper3** [comment]
@wfurt, can we parse out the full zone string and use https://github.com/dotnet/corefx/blob/6a9f579209491ae9041f208bfe34b89085c0279e/src/Native/Unix/System.Native/pal_networkstatistics.c#L428-L436 to determine if the interface exists, in c#: 

<code>if(Interop.Sys.GetNativeIPInterfaceStatistics(parsedZone, out _) == -1) {</code> :-1: <code>}</code>

**Comment by wfurt** [comment]
yes, that is something along the way. It may make sense to run it into separate pal function and the rest should be easy. if_nametoindex() should work on OSX and FreeBSD as well.

**Comment by kasper3** [comment]
I am not sure about the use-case of all the APIs that will use this implementation, but is interface name testing using system call really necessary at address parsing stage? For example, user can have list of IP addresses of other zone and just want to parse them (`bool VerifyAddressIsValid(string address)` in my code for example). However, if we use this IPv6 address with interface name in HttpClient for example, then the HttpClient (or any API interacting with communication layer) should use the specified interface and verify its existence etc.?

**Comment by wfurt** [comment]
We could delay index lookup  @kasper3 but than we need to store the string. 

cc: @davidsh and @caesar1995
