### ISSUE TITLE
Wrong result using & operator on value of type short on ARM platform

### ISSUE THREAD

**Issue by mdisg** [dotnet/corefx#27548]
Hello,

i'm currently porting an existing .NET application used on embedded devices to .NET Core. 
Yesterday a bug showed up running in a backup task which simply takes old log files and puts them into a zip archive for which we use the [DotNetZip Library](https://archive.codeplex.com/?p=dotnetzip). This task has run several times without a problem but yesterday i got the exception `IndexOutOfRangeException: 'Index was outside the bounds of the array.`

This happend on a ARMv7 embedded board running Ubuntu 16.04.3 LTS. I then tried to create a zip archive using the same file on Windows 10 and on Ubuntu running in a Virtualbox where no problem showed up

Looking deeper into the reason for that exception revealed that a negative value is passed to a method which does not expect it. I compared the same call of the method on other platforms which showed me that there is always a positive value passed to the method and it works as expected.
The reason for that negative value was a AND operation using the `& operator` on a value of type `short/Int16` which is read from a array `short[]`.

The operation which is done in the DotNetZip library is:
`hash_head = (head[ins_h] & 0xffff);`
where hash_head is of type `int`

The value at the array position which is causing the exception is `-32762` The result of the operation should be `32774`. Running that code using .NET Core on the ARM board gives the result `-32762`.
On all my other environments the result was correct (.NET 3.5, 4, .NET CF 3.5 (ARM) and .NET Core on Windows).

I then changed the code to this:
```
short current = head[ins_h];
hash_head = (current & 0xffff);
```
After that change, the operation gave the same result as on the other platforms and the zip archive was created without any errors.

The erroneous behavior can easily be reproduced with the following code running on the arm platform.
```
var shortArray = new short[] { -32762 };
Console.WriteLine("shortArray result: " + (shortArray[0] & 0xFFFF));
```

This code does the same but in a different manner and works on arm:
```
short shortValue = -32762;
Console.WriteLine("shortValue result: " + (shortValue & 0xFFFF));
```

This is a weird behavior and i think this can be a big issue porting existing code to .NET Core. In my case it can easily be solved by the given workaround but i think this can cause many trouble with projects running fine on x86/x64 but not on ARM.

I tested the given code using the dotnet runtime in version 2.0.0, 2.0.4 and 2.1-preview (26227-02)
The behavior exists in all of them.

If further information is required please ask for it.

**Comment by danmosemsft** [comment]
@jkotas this seems codegen, do you agree?

**Comment by jkotas** [comment]
This issue was moved to dotnet/coreclr#16675
