### ISSUE TITLE
Socket_CreateUnixDomainSocket_Throws_OnWindows fails locally on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#27542]
This test fails locally for me:
```C#
[OuterLoop] // TODO: Issue #11345
[Fact]
[PlatformSpecific(TestPlatforms.Windows)]  // CreateUnixDomainSocket should throw on Windows
public void Socket_CreateUnixDomainSocket_Throws_OnWindows()
{
    SocketException e = Assert.Throws<SocketException>(() => new Socket(AddressFamily.Unix, SocketType.Stream, ProtocolType.Unspecified));
    Assert.Equal(SocketError.AddressFamilyNotSupported, e.SocketErrorCode);
}
```
as `new Socket(AddressFamily.Unix, SocketType.Stream, ProtocolType.Unspecified)` doesn't throw, on both core and netfx.  Presumably the AF_UNIX address family is now supported on my Windows OS, maybe due to my having installed Windows Subsystem for Linux.

**Comment by rmkerr** [comment]
Looks like [support for AF_UNIX](https://blogs.msdn.microsoft.com/commandline/2017/12/19/af_unix-comes-to-windows/) was added in a recent Windows Insider build. I don't think that it requires Windows Subsystem for Linux, so the change will probably (someday) roll out to our test machines too.

**Comment by stephentoub** [comment]
Woh. Thanks, @rmkerr.

@eerhardt, this makes UnixDomainSocketEndPoint relevant to Windows!  We should see what it would take to make this work in 2.1.
cc: @karelz

**Comment by danmosemsft** [comment]
@JeremyKuhne FYI, in case you are interested. These are exposed via reparse points.
