### ISSUE TITLE
TypeForwardedFromAttribute accepts null as assemblyFullName

### ISSUE THREAD

**Issue by EgorBo** [dotnet/corefx#27554]
According to https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.typeforwardedfromattribute.-ctor?view=netcore-2.0#Definition
there should be a null-check - https://github.com/dotnet/corefx/blob/103639b6ff5aa6ab6097f70732530e411817f09b/src/Common/src/CoreLib/System/Runtime/CompilerServices/TypeForwardedFromAttribute.cs#L12. We have a test in mono that checks this behavior so `TypeForwardedFromAttribute `from corefx broke it 🙂

**Comment by akoeplinger** [comment]
Looks like the null check was removed in https://github.com/dotnet/coreclr/commit/1a9781b68b8ec66c223bb96f44ae1d2704ce6fdf#diff-f846f4498c978cab5dd7103b0b1d7f94L23 but I don't see a good reason in the commit/PR.

**Comment by jkotas** [comment]
I have picked wrong one when choosing between CoreCLR and CoreRT forks.

**Comment by jkotas** [comment]
The convention for custom attributes seems to be do not do any argument validation. I will try to find where the change in the CoreRT fork came from.
