### ISSUE TITLE
Cannot deserialize SOAP arrays

### ISSUE THREAD

**Issue by bartekkois** [dotnet/corefx#27561]
I`ve got some problems when deserilizing array of objects in one of my web services. The following class was generated by the dotnet-svcutil and during deserialization countField is deserilized properly while the clientsField which is of type clientDetails[] is always null.

```c#
[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.example.org/ResellerAPI/")]
public partial class clientDetailsArray
{
    
    private int countField;
    
    private clientDetails[] clientsField;
    
    /// <remarks/>
    public int count
    {
        get
        {
            return this.countField;
        }
        set
        {
            this.countField = value;
        }
    }
    
    /// <remarks/>
    public clientDetails[] clients
    {
        get
        {
            return this.clientsField;
        }
        set
        {
            this.clientsField = value;
        }
    }
}

```
When I enabled XML debugging and step into the whole process I found the following piece of code that is theoretically responsible for deserilization of the clientsField and it returns null no matter what:

```c#
        object Read610_Array() {
            // dummy array method
            UnknownNode(null);
            return null;
        }
```

By looking for the phrase "// dummy array method" I`ve found the following method related to XmlSerializationReader:
https://referencesource.microsoft.com/#System.Xml/System/Xml/Serialization/XmlSerializationReader.cs,2259

Does this means that Collections cannot be deserialized in this case? How to fix that?

[EDIT] Add C# syntax highlighting by @karelz

**Comment by huanwu** [comment]
@bartekkois Could you share more about your repro code?  I could not repro this problem if just simply serialize and deserialize the object of the above class.

**Comment by bartekkois** [comment]
This code is a part of proxy class automatically generated by dotnet-svcutil based on WSDL description of SOAP web service provided by my VoIP provider. As fas as I`ve debugged the problem I am able to use this class (login, get some data and logout) like this:

```csharp  
string sessionId = "";
PlatformAPIClient atmanCTMClient = new PlatformAPIClient();
List<Client> clients = new List<Client>();
await atmanCTMClient.loginAsync(resellerLoging, resellerPassword, sessionTimeout);
clientDetailsArray clientDetailsArray = await atmanCTMClient.getClientsAsync(new clientSearchParams());
await atmanCTMClient.logoutAsync(sessionId);
```
 and evertything work`s perfectly fine unless I reach a class that contains array. Then for instatance clinentDetailsArray count property is deserialized properly but clientDetails[] is always null and when I step into deserilization code I find this method:
```csharp 
object Read610_Array() {
  // dummy array method
  UnknownNode(null);
  return null;
}
```
However if I do it by hand (send prepared request using web client, get SOAP response, cut out XML structure out of SOAP envelope and try to deserilize it using this proxy classes) everything works fine. It seems that it matters whether XML is encapsulated inside SOAP Envelope or not.

This spaghetti code works:
```csharp 
 cookieWebClient.Headers.Add("Content-Type", "application/soap+xml; charset=utf-8; action=\"http://www.example.org/ResellerAPI/login\"");
var xmlResponse XDocument.Parse(await cookieWebClient.UploadStringTaskAsync(webServiceUri, clientsRequest))
.Descendants((XNamespace)"http://schemas.xmlsoap.org/soap/envelope/" + "Body")
.First()
.DescendantNodes()
.Skip(1)
.First().ToString().Replace("ns1:", "");

XmlSerializer xmlSerializer = new XmlSerializer(typeof(clientDetailsArray));
MemoryStream memoryStream = new MemoryStream(Encoding.UTF8.GetBytes(xmlResponse ).Replace("getClientsResponse", "clientDetailsArray")));
 return xmlSerializer.Deserialize(memoryStream) as clientDetailsArray;
```

**Comment by huanwu** [comment]
@bartekkois I still cannot repro your problem. I created a wcf service like the following. I then use the connected service to generate the client code and call GetClientDetailArray from the client. The returned value is correct. Could you share with me your server side code?

```
    [ServiceContract, XmlSerializerFormat]
    public interface IService1
    {
        [OperationContract(Name = "GetClientDetailArray"), XmlSerializerFormat(Style = OperationFormatStyle.Rpc, Use = OperationFormatUse.Encoded)]
        clientDetailsArray GetClientDetailArray();
    }

    public class clientDetails
    {
        public string Name { get; set; }
    }

    public class clientDetailsArray
    {
        private clientDetails[] clientsField;
        public clientDetails[] clients
        {
            get
            {
                return this.clientsField;
            }
            set
            {
                this.clientsField = value;
            }
        }
    }

    [ServiceBehavior(InstanceContextMode = InstanceContextMode.Single)]
    public class Service1 : IService1
    {
        public clientDetailsArray GetClientDetailArray()
        {
            clientDetails[] array = new clientDetails[2];
            array[0] = new clientDetails() { Name = "aaa" };
            array[1] = new clientDetails() { Name = "bbb" };
            return new clientDetailsArray() { clients = array };
        }
    }
```

**Comment by bartekkois** [comment]
Here is my code responsible for accessing web service:
```
string sessionId = "";
PlatformAPIClient atmanCTMClient = new PlatformAPIClient();
List<Client> clients = new List<Client>();
await atmanCTMClient.loginAsync(resellerLoging, resellerPassword, sessionTimeout);
clientDetailsArray clientDetailsArray = await atmanCTMClient.getClientsAsync(new clientSearchParams());
await atmanCTMClient.logoutAsync(sessionId);
```
Below are my proxy classes and response dump as it is not publicly available web service.
[Reference with response dump.zip](https://github.com/dotnet/corefx/files/1859504/Reference.with.response.dump.zip)

**Comment by huanwu** [comment]
cc @mconnew

**Comment by bartekkois** [comment]
I`ve already done something similar to this before adding this as an issue as I thought it was a problem with my code or with the SOAP response format. I`ve tried to modify both SOAP response (by adding wrapping element) and proxy classes (according to https://blogs.msdn.microsoft.com/youssefm/2009/06/12/customizing-the-xml-for-collections-with-xmlserializer-and-datacontractserializer/) but none of these works.

**Comment by jrodenburg** [comment]
Was a solution ever found for this issue?

**Comment by bartekkois** [comment]
I haven`t found one. However you can look at my not very elegant way of dealing with that problem by preparing raw requests, sending them by HttpClient,  cutting out XML content from SOAP envelope and deserializing it:
https://github.com/bartekkois/Adescom-CTM-Billings/blob/master/Adescom%20CTM%20Billings/AdescomCTMSoapWrapper.cs#L191
It is painfull but works for smaller apps.

**Comment by mconnew** [comment]
There isn't a need to use HttpClient, you can modify the XML content using a MessageInspector and still maintain the contract based programming model that WCF provides. Closing the issue as adding support in XmlSerializer is too large a change given soap encoding was replaced many moons ago.

**Comment by averied** [comment]
Just saying.. Microsoft uses SOAP encoding in the latest version of their Dynamics NAV 2018 Web services. So it really sux that I cannot easily use WCF to consume a current Microsoft Web Service.
