### ISSUE TITLE
Display issue for Euro currency

### ISSUE THREAD

**Issue by leecow** [dotnet/corefx#27565]
@dpjain commented on [Sun Feb 25 2018](https://github.com/dotnet/core/issues/1283)

In our application, we have used English and French language. We need to use Euro currency for French language and "," is used as separator for Euro currency. But have no idea how to display the same format. The numeric text box only accepts the decimal values, not accepting the comma. And also the property are set as Currency data type. 

ConfigureServices: 
services.Configure<RequestLocalizationOptions>(options =>
            {
                var supportedCultures = new[]
                {
                    new CultureInfo("en-GB"),
                    new CultureInfo("fr-FR") { NumberFormat = { CurrencyDecimalSeparator = "," }, DateTimeFormat = new CultureInfo("en-GB").DateTimeFormat }
                };
                options.DefaultRequestCulture = new RequestCulture(culture: new CultureInfo("en-GB"), uiCulture: new CultureInfo("en-GB"));
                options.SupportedCultures = supportedCultures;
                options.SupportedUICultures = supportedCultures;
            });

Configure:
 var locOptions = app.ApplicationServices.GetService<IOptions<RequestLocalizationOptions>>();
            app.UseRequestLocalization(locOptions.Value);

**Comment by karelz** [comment]
@dpjain which .NET Core version do you use? (2.0 vs. 2.1 Preview1)
Are you able to untangle the problem in numeric box (ASP.NET component I assume) vs. Culture/globalization APIs?

**Comment by karelz** [comment]
cc @tarekgh

**Comment by dpjain** [comment]
@karelz: Version is .NET Core 2.0.

No, I cant even insert the comma in numeric textbox in Chrome while I can insert comma in Mozilla Firefox. But in firefox the textbox give invalid number error if I tried to pass: 6.452,12 euros.

**Comment by karelz** [comment]
Does it fail in browser (JScript), or on server (ASP.NET)? What exactly fails and how? Can you create minimal repro? (just client side or just server-side)

**Comment by dpjain** [comment]
It fails in client side validation. Whenever we insert the above value in numeric textbox, it throws client side validation error of invalid number({ProprtyName} must be a number).

**Comment by karelz** [comment]
That sounds like JScript validation problem - can you please file a bug on ASP.NET with a repro? That will help to get it investigated/addressed. Thanks!

Closing as it is not problem in .NET Core.
