### ISSUE TITLE
HttpClient doesn't send Connection: close header on some platforms

### ISSUE THREAD

**Issue by mconnew** [dotnet/corefx#27566]
WCF allows disabling persistent connections for HTTP requests. When persistent connections are disabled, WCF runs this code:
```csharp
    httpClient.DefaultRequestHeaders.ConnectionClose = true;
```
This fails to send the `Connection: close` header for requests on Fedora.27, Fedora.26, Debian.90 and OSX.1013. This header is successfully sent on Centos, Debian.87, OSX.1012, RedHat, SLES, Ubuntu, Windows and OpenSuse.

**Comment by davidsh** [comment]
cc: @stephentoub @geoffkizer 

We should see if SocketsHttpHandler allows this.  I do know that WinHttpHandler doesn't because the "Connection" header is "owned" by WinHTTP and it does stuff on its own.

**Comment by mconnew** [comment]
@davidsh, our test is passing when running on Windows. On the server side we are seeing the `Connection: close` arrive on the server.

**Comment by stephentoub** [comment]
> This fails to send the Connection: close header for requests on Fedora.27, Fedora.26, Debian.90 and OSX.1013. This header is successfully sent on Centos, Debian.87, OSX.1012, RedHat, SLES, Ubuntu, Windows and OpenSuse.

Have you looked at what version of libcurl is installed on each of these systems?  My guess is it's a difference based on that, rather than something in CurlHandler, which doesn't have any distro-specific code.

> We should see if SocketsHttpHandler allows this. I do know that WinHttpHandler doesn't because the "Connection" header is "owned" by WinHTTP and it does stuff on its own.

I believe we have a test that verifies this, but we should double-check.  I know I recently wrote this test, which sets Connection: close:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs#L1195
and then verifies the server received it:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs#L1269
though it sets it in a slightly different manner.

**Comment by mconnew** [comment]
@stephentoub, I have no idea what is installed as this is results from the nightly test runs from the build infrastructure. Are we doing anything specific with libcurl with the Close header because if we're not, then I believe that's a bug.  There's a special curl option [`CURLOPT_FORBID_REUSE`](https://curl.haxx.se/libcurl/c/CURLOPT_FORBID_REUSE.html) which should be set before making a request to get this behavior. The fact that it works on OSX 10.12 but not on 10.13 and works on Debian 8.7 but not Debian 9.0 suggests that newer versions don't support directly adding the header (I'm presuming that today we just add the header like all other headers) and more failures will be seen in the future. If the header is just added like any other header, then libcurl is explicitly removing the header which would mean it's a purposeful change.

**Comment by stephentoub** [comment]
> The fact that it works on OSX 10.12 but not on 10.13 and works on Debian 8.7 but not Debian 9.0 suggests that newer versions don't support directly adding the header

Right, that's why I was asking about the verions.

> Are we doing anything specific with libcurl with the Close header because if we're not, then I believe that's a bug.

I don't believe so.  You're welcome to submit a PR.

**Comment by wfurt** [comment]
If you craft small repro, I can take a look @mconnew. I have both 10.12 and 10.13 for testing.

**Comment by mconnew** [comment]
@wfurt, you can use the test case mentioned by @stephentoub [here](https://github.com/dotnet/corefx/issues/27566#issuecomment-369356740) as a repro. Alternatively, it's simply this code:
```csharp
var httpClient = new HttpClient();
httpClient.DefaultRequestHeaders.ConnectionClose = true;
var string = await httpClient.GetStringAsync("http://www.microsoft.com");
```
This presumes the issue isn't timing related. but I doubt it is as this is reproducible every time in our nightly tests.

@stephentoub, I wouldn't want to submit a PR as this looks like it affects all requests from a particular curl handle and then you have issues with the HttpClient api abstraction allowing some requests to have the connection close header and some not. The ramp up time of understanding how we implemented handle lifetime management in the curl handler implementation is too much when I'm unfamiliar with our implementation.

**Comment by stephentoub** [comment]
> I wouldn't want to submit a PR as this looks like it affects all requests from a particular curl handle

CURLOPT_FORBID_REUSE applies to an "easy" handle, which maps 1:1 with a request.  As far as I can tell from the docs, it doesn't apply to a "multi" handle, which is 1:1 with CurlHandler and would impact all requests.

**Comment by mconnew** [comment]
I just did a quick search of recent commits and issues in the curl repo and I'm not seeing anything related to the connection close header. So this doesn't look like a simple issue.

**Comment by davidsh** [comment]
Since the default HTTP stack for .NET Core 2.1 is SocketsHttpHandler, I don't think this issue will be a problem. SocketsHttpHandler should be correctly handling 'Connection: close' request headers.

Since fixing this for CurlHandler is nontrivial at best, perhaps we can close this issue now since CurlHandler is not the default HTTP stack anymore?

cc: @stephentoub @mconnew @karelz

**Comment by mconnew** [comment]
I'm okay closing this as the bug was against HttpClient/HttpClientHandler. Abstractly I'm not concerned with how this is fixed "under the hood".
