### ISSUE TITLE
DirectoryInfo.GetFiles killed by privileged folders 

### ISSUE THREAD

**Issue by ericlaw1979** [dotnet/corefx#2757]
The seemingly useful DirectoryInfo.GetFiles method (with the SearchOption.AllDirectories parameter) is unreliable because any access control check failure causes it to bomb out with an exception rather than returning files that _are_ accessible to the user.

For instance, call this on any drive root from a non-elevated process and you'll get:

`Access to the path 'D:\$RECYCLE.BIN\S-1-5-18' is denied.
Type: System.UnauthorizedAccessException
Source: mscorlib
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator``1.AddSearchableDirsToStack(SearchData localSearchData)
   at System.IO.FileSystemEnumerableIterator``1.MoveNext()
   at System.Collections.Generic.List``1..ctor(IEnumerable``1 collection)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)`

The API should be smart enough to skip enumerating folders to which it doesn't have permission, or it should offer some sort of callback or parameter to permit doing so.

**Comment by SunnyWar** [comment]
The time I would have saved had it been like this is massive.

**Comment by GSPP** [comment]
I have written recursive directory scanning code because of this many times. Super useful.

Of course we would not want to skip errors by default. These methods probably should take a callback that decides based on path and an error code (enum) whether to ignore the error or not. Using that callback the caller can capture errored path as well.

**Comment by karelz** [comment]
Feel free to submit API proposal.

**Comment by JeremyKuhne** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.io.enumerationoptions.ignoreinaccessible?view=netcore-2.1#System_IO_EnumerationOptions_IgnoreInaccessible provides this now. All of the enumeration APIs provide this option set. Please reopen if this doesn't address the request.
