### ISSUE TITLE
SocketsHttpHandler: Should only do preauthentication when credentials are a CredentialCache

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#27597]
Currently, when PreAuthenticate is set to true, we always send basic credentials on every request to every server.

To avoid sending credentials to servers that don't care, we should only preauthenticate when the credentials are a CredentialCache and thus known to be specific to a particular server.

I tried making this change in my ntlm PR (https://github.com/dotnet/corefx/pull/27551), but it caused failures on Linux/OSX only -- Windows worked fine.  No idea why the behavior differs by platform (it's all SocketsHttpHandler so should be consistent).  The failures were in PostNonRewindableContentUsingAuth_PreAuthenticate_Success; see here for more details: https://mc.dot.net/#/user/geoffkizer/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/abfadff769bb9dbba1dc870f70944d1fbb26ad87/workItem/System.Net.Http.Functional.Tests

We should understand why the behavior is different by platform.  We should also consider adding pre-auth tests specifically; I don't think we have any tests that explicitly validate preauth behavior (as opposed to just confirming that auth succeeded, whether preauth actually occurred or not).

cc @Tratcher, who pointed out this issue originally.

**Comment by stephentoub** [comment]
> No idea why the behavior differs by platform (it's all SocketsHttpHandler so should be consistent).

Because it's disabled on Windows :smile:
https://github.com/dotnet/corefx/blob/f9853fafb6e49c1c6e94f8c3130af9da4a1574a2/src/System.Net.Http/tests/FunctionalTests/PostScenarioTest.cs#L163-L164

**Comment by Tratcher** [comment]
Here's one reference where HWR checks for CredentialCache before redirects: https://referencesource.microsoft.com/#System/net/System/Net/HttpWebRequest.cs,5824

I didn't find the same check for pre auth:
https://referencesource.microsoft.com/#System/net/System/Net/_BasicClient.cs,88
but it does have a policy system for deciding if it should send the credentials:
https://referencesource.microsoft.com/#System/net/System/Net/_BasicClient.cs,96
https://referencesource.microsoft.com/#System/net/System/Net/IntranetCredentialPolicy.cs,78

**Comment by stephentoub** [comment]
I believe both CurlHandler and WinHttpHandler require a CredentialCache for redirects, but are happy with a NetworkCredential for the initial preauthentication.  And it looks like unless you configure things differently, netfx is similar.  Should we not follow that precedent rather than always requiring a CredentialCache?  Always requiring it would seem to be a relatively visible breaking change.

**Comment by davidsh** [comment]
>Should we not follow that precedent rather than always requiring a CredentialCache? Always requiring it would seem to be a relatively visible breaking change.

Yes, I think we should follow netfx pattern.
