### ISSUE TITLE
HttpClient response stream.Read/ReadAsync sporadically returns 0 for a non empty response

### ISSUE THREAD

**Issue by KKhurin** [dotnet/corefx#2760]
We see it both in WCF streaming scenarios (receiving a stream from WCF service) and in simple repros like:
~~~
var c = (await client.PostAsync(url, new StreamContent(new MyStream()))).Content;
var stream = await c.ReadAsStreamAsync();
byte[] buff = new byte[4096];
var bytesread = await stream.ReadAsync(buff, 0, 4096); // bytesread is sporadically 0 even though the response does contain data
~~~

About a half of WCF streaming scenarios fail because of this bug

**Comment by davidsh** [comment]
@KKhurin Please provide a repro solution/code.  It's not really possible to diagnose this without a repro being posted.  It's important to get the server-side of the repro even though you have described some of the client-code here.

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar

**Comment by ellismg** [comment]
Are we still hitting this?  I know we have taken a bunch of changes around this stuff recently.

**Comment by davidsh** [comment]
@KKhurin As you indicated in your recent email, the latest stress runs don't repro this behavior using the latest System.Net.Http package.
