### ISSUE TITLE
HttpClientHandler: Consider exposing ConnectTimeout 

### ISSUE THREAD

**Issue by Lybecker** [dotnet/corefx#27604]
Exposing the ConnectTimeout on HttpClientHandler like suggested on SocketsHttpHandler (#27235) and WinHttpHandler (#27603). It will also make it possible to be consistent with the CurlHandler without making the CurlHandler public.

```c#
public sealed class HttpClientHandler {
    public TimeSpan ConnectTimeout { get; set; }
        // defaults to infinite so that it's opt-in / pay for play
    ...
}
```

**Comment by MatthewLymer** [comment]
I would like this very much, I don't want to know the underlying handler, but I would like to configure the connect timeout.

**Comment by karelz** [comment]
Triage: Given that we are moving to `SocketsHttpHandler` as primary advanced features handler, it does not make sense to expose everything on `HttpClientHandler`. Moreover, the `WinHttpHandler` part cannot be honored - see #27603.
Closing.
