### ISSUE TITLE
WinHttpHandler: Consider exposing ConnectTimeout 

### ISSUE THREAD

**Issue by Lybecker** [dotnet/corefx#27603]
In some environments, in particular in a cloud, it's useful to be able to specify a timeout for just the connection phase of an HTTP request. That way, if the server is unresponsive, we don't need to wait for the full HttpClient timeout to cancel the request, and conversely, setting a small HttpClient timeout to avoid such issues doesn't cancel an active operation taking a long time simply because it's conversing a lot.

We should add:
```c#
public sealed class WinHttpHandler {
    public TimeSpan ConnectTimeout { get; set; } // defaults to infinite so that it's opt-in / pay for play
    ...
}
```
The underlying Interop.WinHttp.WinHttpSetTimeouts has the connect timeout, which is currently not set.

**Comment by Lybecker** [comment]
This is related to the same request for the SocketsHttpHandler #27235

**Comment by karelz** [comment]
Triage: Per WinHttp team, this does not work. Given that we are moving to `SocketsHttpHandler` as primary handler, it does not make sense to push on `WinHttpHandler` improvements.
Closing.
