### ISSUE TITLE
UseCallback_HaveCredsAndUseAuthenticatedCustomProxyAndPostToSecureServer_Success is failing on Win7

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#27612]
Error is

```
System.IO.IOException : Unable to transfer data on the transport connection: An existing connection was forcibly closed by the remote host.
---- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host
```

From the loopback proxy server.

https://mc.dot.net/#/user/geoffkizer/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/1810ecb8564830d72a8b8b7404d5cf846e1a6ccb/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test~2FUseCallback_HaveCredsAndUseAuthenticatedCustomProxyAndPostToSecureServer_Success

**Comment by karelz** [comment]
@wfurt can you please check frequency of this test failure?

**Comment by wfurt** [comment]
I don't see any recent failures. closing.
