### ISSUE TITLE
Remove workarounds when uapaot System.Private.CoreLib is updated

### ISSUE THREAD

**Issue by nattress** [dotnet/corefx#27619]

**Comment by jkotas** [comment]
https://github.com/dotnet/corefx/commit/3fca26cedf6c54aabc100e69106fc7e263db7815

https://github.com/dotnet/corefx/commit/ebe14686a89d26d1d34d359f7a636d6e9a36a624

**Comment by nattress** [comment]
Reverted https://github.com/dotnet/corefx/commit/ebe14686a89d26d1d34d359f7a636d6e9a36a624 in https://github.com/dotnet/corefx/commit/671b10bb21668d8432f066a4307c269a98a66ea8
