### ISSUE TITLE
TcpClient uses Socket class which can fail in odd ways on UWP

### ISSUE THREAD

**Issue by borrrden** [dotnet/corefx#27638]
I am unsure what the actual cause of this is, but when I call Connect on a TcpClient that is working on an endpoint that is connected to the machine via VPN, then the underlying Socket connect call returns AccessDenied (as stated [here](https://social.msdn.microsoft.com/Forums/en-US/d9171ccf-efbc-498a-bc4d-ebe58055d3a7/uwpcannot-connect-to-private-server-socketerror-accessdenied?forum=wpdevelop)).  The link suggests using StreamSocket to connect, but how can I do that when this is an implementation detail of TcpClient.  Is there no way to accomplish this connection?

**Comment by karelz** [comment]
Closing as not relevant. UWP will get larger investment later on - once we re-enable the test runs.
