### ISSUE TITLE
ApiCompat giving incorrect error about implementation instead of correctly pointing to the contract

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#27642]
The ApiCompat error from https://github.com/dotnet/corefx/pull/27640#issuecomment-369808688 seems to be reversed.

```text
D:\GitHub\Fork\corefx\src\shims\ApiCompat.proj(76,5): error : TypeCannotChangeClassification : Type 'System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter' is marked as readonly in the contract so it mu
st also be marked readonly in the implementation.
```

The fix was to add `readonly` to the ref (contract). The error message indicates that the contract is marked as readonly, but the implementation is not, which is the opposite of what it should have been.

Any ideas why?
cc @ericstj, @weshaggard, @joperezr, @stephentoub

**Comment by weshaggard** [comment]
It is kind of hard to see the exact changes based on that PR as it had a lot going on. Can you give a simple example of what you were seeing? 

Keep in mind that "contract" is really just left and "implementation" is right in the diff so if the reference assembly was passed as the right side then you might get this error.

**Comment by ahsonkhan** [comment]
> Can you give a simple example of what you were seeing?

Remove the `readonly` keyword from this line:
https://github.com/dotnet/corefx/blob/master/src/System.Runtime/ref/System.Runtime.cs#L6445
```C#
public readonly partial struct ConfiguredValueTaskAwaiter : System.Runtime.CompilerServices.ICriticalNotifyCompletion, System.Runtime.CompilerServices.INotifyCompletion
{
...
```

Leave the `readonly` keyword in the implementation:
https://github.com/dotnet/corefx/blob/803466487e65ca23579139f2565d960404775cd9/src/Common/src/CoreLib/System/Runtime/CompilerServices/ConfiguredValueTaskAwaitable.cs#L34

Observe ApiCompat error as stated above (reversed).

**Comment by joperezr** [comment]
These ApiCompat errors have been around for a long time, but they just don't fail the build, which most likely is a bug in our targets. I believe that what we should do is just to update the baselines for uap and uapaot

**Comment by ahsonkhan** [comment]
> These ApiCompat errors have been around for a long time, but they just don't fail the build, which most likely is a bug in our targets. I believe that what we should do is just to update the baselines for uap and uapaot

This specific issue/error is new and not related to uap only. Also, the error got resolved already. I just wanted to point out that the error message was incorrect, making it harder to debug the issue.

**Comment by ericstj** [comment]
I found the reason.  This API Compat pass is actually doing a diff between `netstandard` references and `netcoreapp` references (note the project and line number: `shims\ApiCompat.proj(76,5)`).  Here `netstandard` is treated as the contract and `netcoreapp` is implementation.

As such the error is indeed correct.  You had readonly on the System.Threading.Tasks.Extensions netstandard ref https://github.com/dotnet/corefx/blob/3fca26cedf6c54aabc100e69106fc7e263db7815/src/System.Threading.Tasks.Extensions/ref/System.Threading.Tasks.Extensions.cs#L44 but were missing that on the System.Runtime ref where the type was typeforwarded to for netcoreapp.

**Comment by wtgodbe** [comment]
Closing at it seems we found the issue, @ericstj please reopen if there's something still needed
