### ISSUE TITLE
How to run single test from VS2017 IDE?

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/corefx#27649]
`System.Memory.Tests` fails 516 tests on my computer from command line.
When I try to run all `System.Memory.Tests` tests from VS2017 IDE it hang up my computer.

I tried to run single test from VS2017 IDE by using next instruction https://github.com/dotnet/corefx/wiki/Build-and-run-tests#run-and-debug-single-test-in-visual-studio 

I added `[Trait("MyTrait", "MyTraitValue")]` to test:
```
        [Theory]
        [Trait("MyTrait", "MyTraitValue")]
        [MemberData(nameof(TestData.Int16ParserTheoryData), MemberType = typeof(TestData))]
        public static void TestParserInt16(ParserTestData<short> testData)
        {
            ValidateParser(testData);
        }
```

I added `-trait "MyTrait=MyTraitValue"` to end of command line. Now command line is `xunit.console.netcore.exe System.Memory.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -wait -parallel none -trait "MyTrait=MyTraitValue"`

But when I run tests, it say that no tests found:
```
Discovering: System.Memory.Tests
Discovered:  System.Memory.Tests
Info:        System.Memory.Tests has no tests to run
```

So how to run single test from VS2017 IDE ?

**Comment by danmosemsft** [comment]
Does `-trait MyTrait` work? Or `-trait MyTrait=MyTraitValue`

**Comment by AlexRadch** [comment]
@danmosemsft `-trait MyTrait=MyTraitValue` works so https://github.com/dotnet/corefx/wiki/Build-and-run-tests#run-and-debug-single-test-in-visual-studio instruction should be changed.

**Comment by ahsonkhan** [comment]
Were you able to figure out how to run a single test via the command line?

cc @davidfowl

**Comment by danmosemsft** [comment]
Look in tools\tests.targets, it's a property named something like $(XunitMethodName) that you can pass with /p.

**Comment by ahsonkhan** [comment]
That is awesome and super useful! What is a good doc that I can add this instruction to? Should I just amend developer-guide to include this?

`msbuild /t:rebuildandtest /p:XunitMethodName=System.MemoryTests.ReadOnlyMemoryTests.ToStringChar_Empty`

**Comment by danmosemsft** [comment]
Whichever of the dev docs is most appropriate.

Note that the console now shows the Xunit commands to run to execute tests without wrapping in MSBuild. That can speed up the dev loop a bit.

**Comment by ahsonkhan** [comment]
> Note that the console now shows the Xunit commands to run to execute tests without wrapping in MSBuild. That can speed up the dev loop a bit.

I haven't been able to get xunit.console.netcore.exe to work for me. I will try again later.

Can we use it for running tests targeting netfx tests as well?

**Comment by danmosemsft** [comment]
Yes. The commands logged between the = signs, including the  pushd and popd should be exactly what the build runs.

________________________________

**Comment by danmosemsft** [comment]
Yes. The commands logged between the = signs, including the  pushd and popd should be exactly what the build runs.

**Comment by ahsonkhan** [comment]
https://github.com/dotnet/corefx/wiki/Build-and-run-tests#run-and-debug-single-test-in-command-line
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md#running-a-single-test-on-the-command-line
