### ISSUE TITLE
System.Diagnostics.EventLog.Tests fails 2 tests in non-English Windows

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/corefx#27646]
`System.Diagnostics.EventLog.Tests` fails 2 tests in non-English Windows with next log:
```
     System.Diagnostics.Tests.EventLogTests.CheckLogName_Get [FAIL]
        Assert.Equal() Failure
                   (pos 0)
        Expected: Application
        Actual:   Приложение
                   (pos 0)
        Stack Trace:
           C:\Code\corefx\src\System.Diagnostics.EventLog\tests\EventLogTests\EventLogTests.cs(83,0): at System.Diagnostics.Tests.EventLogTests.CheckLogName_Get()

     System.Diagnostics.Tests.EventLogTests.GetLogDisplayName_Set [FAIL]
        Assert.Equal() Failure
                   (pos 0)
        Expected: Application
        Actual:   Приложение
                   (pos 0)
        Stack Trace:
           C:\Code\corefx\src\System.Diagnostics.EventLog\tests\EventLogTests\EventLogTests.cs(112,0): at System.Diagnostics.Tests.EventLogTests.GetLogDisplayName_Set()
```

I do not know how to fix these tests, because `EventLog.LogDisplayName` differs in non-English Windows.

May be test `EventLog.Log` property ? Or test that `EventLog.LogDisplayName` is not empty string?

**Comment by danmosemsft** [comment]
@Anipik please reproduce this by changing your system locale. Then if possible find a localized name on the eventLog object that you can use instead. If that doesn't work, then verify eventLog.LogDisplayName only when culture is en-US. Same for the other test.
```
            using (EventLog eventLog = new EventLog("Application"))
            {
                Assert.Equal("Application", eventLog.LogDisplayName);
            }
```

**Comment by AlexRadch** [comment]
@danmosemsft I think it not possible to reproduce this by changing locale because localized name on the `eventLog` stored in registry. And Windows will not change it after installation. So to reproduce it you should install non-English windows.

**Comment by danmosemsft** [comment]
@AlexRadch can you confirm that eventLog.Log is not localized ie it's "Application" on your box? If so we can just change to that as you suggest.ed

**Comment by AlexRadch** [comment]
@danmosemsft I will try to change locale to english and then tests.

**Comment by AlexRadch** [comment]
I changed Windows interface language to English and those tests does not fail.

**Comment by Anipik** [comment]
@AlexRadch I will make the necessary changes . Thanks for the help

**Comment by Anipik** [comment]
@AlexRadch can you tell how you changed the windows interface language ?. I tried changing the system locale as well as system display and input language but still not able to repro the bug

**Comment by AlexRadch** [comment]
![screenshot_6](https://user-images.githubusercontent.com/6407980/36927066-a8a982b6-1ead-11e8-883e-38e266c551cf.png)

**Comment by Anipik** [comment]
![languageselected](https://user-images.githubusercontent.com/10516582/36993724-97541280-2063-11e8-98ed-1437fabba07e.PNG)
I changed the interface language but i am still not able to repro the bug. is there anything i am missing her ?

**Comment by AlexRadch** [comment]
@Anipik does you restart windows ? I do not see that Windows interface changed from English. Use language that you can read!

**Comment by Anipik** [comment]
I have restarted it. some of the things are still in English like file names and stuff.
![capture9](https://user-images.githubusercontent.com/10516582/37001221-a1f59b8e-207a-11e8-9b5b-fca47bde80a2.PNG)
Yeah. This is the only other language that i can read :)

**Comment by Anipik** [comment]
@AlexRadch 
I am still not able to repro it
```
msbuild c:\git\corefx\src\System.Diagnostics.EventLog\tests\System.Diagnostics.EventLog.Tests.csproj /t:rebuildandtest /p:xunitmethodname=System.Diagnostics.Tests.EventLogTests.CheckLogName_Get
```
```
xUnit.net console test runner (64-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.

  Discovering: System.Diagnostics.EventLog.Tests
  Discovered:  System.Diagnostics.EventLog.Tests
  Starting:    System.Diagnostics.EventLog.Tests
  hi-IN
  Finished:    System.Diagnostics.EventLog.Tests

  === TEST EXECUTION SUMMARY ===
     System.Diagnostics.EventLog.Tests  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0.132s
  ----- end 17:53:11.29 ----- exit code 0 ----------------------------------------------------------
  Creating "c:\git\corefx\bin/tests/System.Di
```
Does changing  EventLog.DisplayName toEventLog.Log works for you ?

**Comment by AlexRadch** [comment]
@Anipik  Does you change Windows interface language?
Issues are here https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogTests.cs#L83, and here https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogTests.cs#L112 because `LogDisplayName` is localized property.

Changing EventLog.DisplayName to EventLog.Log works but it makes tests senseless because `Log` property always the same as in constructor.

**Comment by Anipik** [comment]
![hindiinterface](https://user-images.githubusercontent.com/10516582/37368531-c0e17eec-26c3-11e8-9337-caaf419cd4e6.PNG)

yes , i have changed the interface language but file names have not changed yet. Can you put a pr for fixing this error as i am not able to repro it?

**Comment by AlexRadch** [comment]
Change `EventLog.DisplayName` to `EventLog.Log` in PR?

**Comment by Anipik** [comment]
how about checking 
> EventLog.LogDisplayName is not empty string

if the culture is not en-US ?
