### ISSUE TITLE
System.Memory.Tests fails 516 tests of parsing numbers

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/corefx#27664]
System.Memory.Tests fails 516 tests of parsing numbers with next log
```
     System.Buffers.Text.Tests.ParserTests.TestParserInt16(testData: [ParseInt16 '32 747,00',N to 32747)]) [FAIL]
        TestException : This parse attempt [ParseInt16 '32 747,00',N to 32747)] succeeded as expected but parsed to the wrong value:
    Expected: 32747
    Actual:   32
  
        Stack Trace:
           C:\Code\corefx\src\System.Memory\tests\ParsersAndFormatters\Parser\ValidateParser.cs(45,0): at System.Buffers.Text.Tests.ParserTests.ValidateParserHelper[T](ParserTestData`1 testData)
           C:\Code\corefx\src\System.Memory\tests\ParsersAndFormatters\Parser\ValidateParser.cs(13,0): at System.Buffers.Text.Tests.ParserTests.ValidateParser[T](ParserTestData`1 testData)
           C:\Code\corefx\src\System.Memory\tests\ParsersAndFormatters\Parser\ParserTests.cs(37,0): at System.Buffers.Text.Tests.ParserTests.TestParserInt16(ParserTestData`1 testData)
```
and so on...

To reproduce it. Set the decimal separator different from dot. And set thousand separator different from comma.

So bug is in test data generator that have very intricate code. And I can not find bug location. I spend about 4 hours to find bug location.

**Comment by ahsonkhan** [comment]
@AlexRadch, what was your initial comment? I think you were asking something about how to run a single test. Were you able to figure it out?

Regarding the test fails - cc @AtsushiKan

**Comment by AlexRadch** [comment]
@ahsonkhan Yes I asked about single test run https://github.com/dotnet/corefx/issues/27649 and I changed https://github.com/dotnet/corefx/wiki/Build-and-run-tests#run-and-debug-single-test-in-visual-studio instruction.
