### ISSUE TITLE
System.Transactions.Local.Tests 🔥 Linux x64 Release Build

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#27677]
Linux x64 Release Build
OpenSuse.423.Amd64.Open:Release-x64
System.Transactions.Local.Tests 🔥

```

Details from Job ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226
ExitCode: -3 
Ran on Machine: jofortes-opensuse-test 
Executed on jofortes-opensuse-test
lix Script Runner v0.1 starting
pying execution payload files from /home/jofortes/dotnetbuild/work/ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226/Work/6288c9a0-0d0b-41e7-b7c4-d4ef6369079a/Unzip to /home/jofortes/dotnetbuild/work/ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226/Work/6288c9a0-0d0b-41e7-b7c4-d4ef6369079a/Exec/execution
ofortes/dotnetbuild/work/ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226/Work/6288c9a0-0d0b-41e7-b7c4-d4ef6369079a/Unzip/System.Transactions.Local.Tests.dll' to '/home/jofortes/dotnetbuild/work/ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226/Work/6288c9a0-0d0b-41e7-b7c4-d4ef6369079a/Exec/execution/System.Transactions.Local.Tests.dll'
ofortes/dotnetbuild/work/ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226/Work/6288c9a0-0d0b-41e7-b7c4-d4ef6369079a/Unzip/xunit.console.netcore.exe' to '/home/jofortes/dotnetbuild/work/ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226/Work/6288c9a0-0d0b-41e7-b7c4-d4ef6369079a/Exec/execution/xunit.console.netcore.exe'
ofortes/dotnetbuild/work/ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226/Work/6288c9a0-0d0b-41e7-b7c4-d4ef6369079a/Unzip/RunTests.sh' to '/home/jofortes/dotnetbuild/work/ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226/Work/6288c9a0-0d0b-41e7-b7c4-d4ef6369079a/Exec/execution/RunTests.sh'
ofortes/dotnetbuild/work/ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226/Work/6288c9a0-0d0b-41e7-b7c4-d4ef6369079a/Unzip/xunit.console.netcore.runtimeconfig.json' to '/home/jofortes/dotnetbuild/work/ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226/Work/6288c9a0-0d0b-41e7-b7c4-d4ef6369079a/Exec/execution/xunit.console.netcore.runtimeconfig.json'
ofortes/dotnetbuild/work/ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226/Work/6288c9a0-0d0b-41e7-b7c4-d4ef6369079a/Unzip/System.Transactions.Local.Tests.pdb' to '/home/jofortes/dotnetbuild/work/ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226/Work/6288c9a0-0d0b-41e7-b7c4-d4ef6369079a/Exec/execution/System.Transactions.Local.Tests.pdb'
ofortes/dotnetbuild/work/ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226/Work/6288c9a0-0d0b-41e7-b7c4-d4ef6369079a/Unzip/DumplingHelper.py' to '/home/jofortes/dotnetbuild/work/ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226/Work/6288c9a0-0d0b-41e7-b7c4-d4ef6369079a/Exec/execution/DumplingHelper.py'
 /home/jofortes/dotnetbuild/work/ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226/Work/6288c9a0-0d0b-41e7-b7c4-d4ef6369079a/Unzip/RunTests.sh /home/jofortes/dotnetbuild/work/ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226/Payload
me/jofortes/dotnetbuild/work/ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226/Work/6288c9a0-0d0b-41e7-b7c4-d4ef6369079a/Unzip
----- start 02:25:09 =============== To repro directly: =====================================================
pushd /home/jofortes/dotnetbuild/work/ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226/Work/6288c9a0-0d0b-41e7-b7c4-d4ef6369079a/Unzip
python DumplingHelper.py install_dumpling
__TIMESTAMP=`python DumplingHelper.py get_timestamp`
chmod +x /home/jofortes/dotnetbuild/work/ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226/Payload/dotnet
/home/jofortes/dotnetbuild/work/ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226/Payload/dotnet xunit.console.netcore.exe System.Transactions.Local.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests  -notrait category=OuterLoop -notrait category=failing
python DumplingHelper.py collect_dump $\ `pwd`  System.Transactions.Local.Tests /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/bin/runtime/netcoreapp-Linux-Release-x64/,/mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/bin/tests/System.Transactions.Local.Tests/netcoreapp-Linux-Release-x64/,/home/jofortes/dotnetbuild/work/ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226/Payload,/lib/x86_64-linux-gnu/libgcc_s.so.1,/lib/x86_64-linux-gnu/libpthread.so.0,/lib/x86_64-linux-gnu/librt.so.1,/usr/lib/x86_64-linux-gnu/libunwind.so.8,/lib/x86_64-linux-gnu/libdl.so.2,/lib/x86_64-linux-gnu/libuuid.so.1,/usr/lib/x86_64-linux-gnu/libunwind-x86_64.so.8,/usr/lib/x86_64-linux-gnu/libstdc++.so.6,/lib/x86_64-linux-gnu/libm.so.6,/lib/x86_64-linux-gnu/libc.so.6,/lib64/ld-linux-x86-64.so.2,/lib/x86_64-linux-gnu/liblzma.so.5
popd
===========================================================================================================
~/dotnetbuild/work/ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226/Work/6288c9a0-0d0b-41e7-b7c4-d4ef6369079a/Unzip ~/dotnetbuild/work/ab3d3d99-d911-4dbc-bb9b-bcf3ee74d226/Work/6288c9a0-0d0b-41e7-b7c4-d4ef6369079a/Unzip
Dumpling cannot be installed due to: HTTP Error 403 Site Disabled
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Transactions.Local.Tests
Discovered:  System.Transactions.Local.Tests
Starting:    System.Transactions.Local.Tests
```

Seen in https://github.com/dotnet/corefx/pull/27673

**Comment by ahsonkhan** [comment]
cc @jimcarley, @qizhanMS, @dmetzgar

**Comment by ahsonkhan** [comment]
> Ran on Machine: jofortes-opensuse-test 

cc @jonfortescue

**Comment by ahsonkhan** [comment]
```text
2018-03-03 02:44:42,438: INFO: saferequests(90): request_with_retry: Response complete with status code '200'
2018-03-03 02:44:42,438: INFO: servicebusrepository(95): renew_workitem_lock: renew_workitem_lock Status Code: 200
2018-03-03 02:45:09,529: ERROR: job(43): kill: Job running for too long. Killing...
2018-03-03 02:45:09,572: ERROR: executor(394): _execute_command: Executor timed out after 1200 seconds and was killed.
2018-03-03 02:45:09,573: INFO: event(43): send: Sending event type WorkItemTimeout
2018-03-03 02:45:09,711: INFO: saferequests(90): request_with_retry: Response complete with status code '201'
2018-03-03 02:45:09,712: INFO: executor(413): _execute_command: Finished _execute_command, exit code: -3
```

@dotnet/dnceng

**Comment by jimcarley** [comment]
It has been too long since I investigated a test failure in jenkins. It's clear that the System.Transactions.Local.Tests got hung for some reason. But I don't remember where to look to try to find the logging generated by the tests themselves..

Interestingly enough, the two previous builds had no problems in System.Transactions on Linux. Nothing in the pull request jumps out at me that would cause problems specifically in System.Transactions.

**Comment by ahsonkhan** [comment]
> Interestingly enough, the two previous builds had no problems in System.Transactions on Linux. Nothing in the pull request jumps out at me that would cause problems specifically in System.Transactions.

Yep, it was likely an intermittent CI/infra issue rather than a real test failure/bug. Closing. Will re-open against core-eng if it occurs again.

**Comment by ahsonkhan** [comment]
Re-opening. We are seeing intermittent failures here (this one from https://github.com/dotnet/corefx/pull/27691).
https://mc.dot.net/#/user/benaadams/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/3b050cea866449d67de1b42696f19e3054d9dd68/workItem/System.Transactions.Local.Tests/wilogs

OpenSuse.423.Amd64.Open:Release-x64
```text
2018-03-04 00:55:58,579: INFO: proc(54): run_and_log_output: Output: Discovering: System.Transactions.Local.Tests
2018-03-04 00:55:58,793: INFO: proc(54): run_and_log_output: Output: Discovered:  System.Transactions.Local.Tests
2018-03-04 00:55:58,906: INFO: proc(54): run_and_log_output: Output: Starting:    System.Transactions.Local.Tests
/bin/sh: line 1: 14541 Killed                  $HELIX_PYTHONPATH $HELIX_CORRELATION_PAYLOAD/RunnerScripts/scriptrunner/scriptrunner.py --script RunTests.sh $HELIX_CORRELATION_PAYLOAD
```

@dotnet/dnceng

**Comment by stephentoub** [comment]
This is happening in a lot of runs.  But I've only seen it on OpenSuse.

**Comment by jonfortescue** [comment]
oops. This is my fault -- left a machine up from a test run. Fixing now.

**Comment by jonfortescue** [comment]
Sorry about that! This won't be an issue anymore.

**Comment by stephentoub** [comment]
Thanks, @jonfortescue.  Why did this only affect System.Transactions.Local.Tests?

**Comment by stephentoub** [comment]
(I will close this assuming the issue has been fixed; we can reopen if we continue to see it.)

**Comment by jonfortescue** [comment]
@stephentoub I'm not totally sure, and frankly this shouldn't have affected anything at all. I was testing new setup scripts that allowed for java installation, but that shouldn't have broken anything. It looks like the initial error was actually due to an attempt to install dumpling... I'll definitely be investigating this further today.

**Comment by jonfortescue** [comment]
@stephentoub I'm not totally sure, and frankly this shouldn't have affected anything at all. I was testing new setup scripts that allowed for java installation, but that shouldn't have broken anything. It looks like the initial error was actually due to an attempt to install dumpling... I'll definitely be investigating this further today.

**Comment by jimcarley** [comment]
Is there any explanation as to what happened here? I haven't worked on core recently, so mc.dot.net is new to me. Trying to figure it out, without much success.

What does "left a machine up from a test run" mean?
Did you ever determine why that only affected the System.Transactions.Local tests?
Is there any way to tell if the tests just never really got started or if they got hung on one particular test "fact"?

**Comment by MattGal** [comment]
@jimcarley basically what "left a machine up from a test run" means is @jonfortescue , being one of our newest team members, accidentally let a VM he was playing with pick up and perform test work for the run.  (hence the machine's name, 'jofortes-opensuse-test' )

Since the machine was in an indeterminate state, there's very little reason for anyone to care about why the work timed out.  I've encouraged Jon in person to not have this happen again :)

**Comment by jonfortescue** [comment]
@jimcarley Exactly what @MattGal said! It was completely an error on my part, exacerbated by the fact that I spun up this machine on a Friday evening and thus didn't notice anything was wrong until Monday morning.

**Comment by jimcarley** [comment]
Okay. I understand now.
To be clear, it does not bother me that this happened. I just wanted to understand. These types of situations can happen in such an environment. Clearly I didn't recognize the fact that the VM in question appeared to be a "personal" one for @jonfortescue  as opposed to an "infrastructure" VM.
It also doesn't help that I haven't touched .NET Core in a while, so the whole "Mission Control" stuff is new to me and I don't know how it works.
