### ISSUE TITLE
CoreCLR: TryGetRawMetadata

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#2768]
Scenario
====

Roslyn Scripting API provides applications with the capability to evaluate C# and VB code snippets. 

For example,

```C#
using Microsoft.CodeAnalysis.Scripting.CSharp;

public class Globals { public int x; public int y; }

class Program
{
  public static void Main()
  {
    var globals = new Globals() { x = 1, y = 2 };
    var options = ScriptOptions.Default.WithReferences(typeof(MyMath).Assembly);

    var script = CSharpScript.Create("MyMath.CalculateStuff(x, y)", options);

    Console.WriteLine(script.RunAsync(globals).Result);
  }
}
```

In the example above ```MyMath``` is a type defined in an assembly referenced by and deployed with the program. The script is compiled with the following metadata references: mscorlib, the assembly containing the ```Globals``` type and an assembly containing ```MyMath``` class. All these assemblies are implementation (runtime) assemblies, not contracts. Since we are compiling scripts at runtime contracts are not relevant. The application might also run on a machine that doesn’t have any SDK. It is natural for scripting to be able to execute virtually any (public) runtime method available in any loaded assembly. Just like Reflection invocation.

On Desktop CLR we use Assembly.Location to find the metadata image for given assembly. 
On Core CLR this property is not available and there is no other way to get the metadata of a given runtime assembly.

Proposed API
====

We propose that the metadata of a runtime assembly are exposed thru new APIs in a form that is efficiently readable using MetadataReader of System.Reflection.Metadata library. Since metadata might not be available for all assemblies (such as AssemblyBuilder, .NET Native images, etc.) the API is allowed to return false for such assemblies. Roslyn scripting API would then report an error that the script can’t reference specified assembly.

```C#
namespace System.Reflection.Metadata
{
  public static class AssemblyExtensions 
  {
    public unsafe static bool TryGetRawMetadata(this Assembly assembly, out byte* blob, out int length);
  }
}
```

**Lifetime considerations**

The pointer would stay valid as long as the ```AssemblyLoadContext``` with which is the assembly associated is alive. It is the responsibility of the caller to keep the Assembly object alive while accessing the metadata blob.

Considered alternatives
====

It was suggested that Roslyn uses Reflection API to read the metadata. There are multiple issues with such approach. 

1)	Expected bad performance (both working set and time)

Reflection is built on top of IMetadataImport. It was measured that using IMetadataImport to reader metadata from managed code is an order of magnitude slower than using S.R.M. MetadataReader, which was not an acceptable perf hit for the compilers. Reflection API implementation adds additional memory and time overhead. Although the number of referenced assemblies is relatively low in most scripting scenarios reducing the compile time of scripts to minimum is crucial for good user experience.

2)	Using Reflection APIs to read namespaces and types

To get a list of namespaces in given assembly one needs to load all types in the assembly. Loading a type may trigger additional assembly loads as well (those of the base types, interfaces). If a type can’t be loaded (perhaps a dependency is missing) we get a loader exception. We can extract the loaded types from the exception, but what if the app makes the dependency available just before it is about to actually start using the type? Our model is immutable, we can’t add a type/namespace into an existing assembly symbol.

3)	Missing APIs 

Brief analysis identified missing APIs that the compiler depends on and that are not present in DNX contracts: for example, type forwarders, GetOptionalCustomModifiers, GetRequiredCustomModifiers, class layout. Besides missing APIs Reflection performs post-processing on the data it receives from IMetadataImport that might render the values useless to the compiler.

4)	Roslyn-Reflection interop

We have prototyped an abstraction of Reflection symbol model to incorporate interop with Reflection runtime types. The abstraction introduces quite a lot of complexity and indirections in already complex code, which significantly increases maintenance cost of that particular area of the compiler. Testing cost would also need to be considered. We would need to effectively run most of our compiler tests twice.

Updates
====
1) Decided to move this to ```System.Reflection.Metadata``` namespace.

**Comment by tmat** [comment]
@jaredpar @nguerrera @terrajobst

**Comment by nguerrera** [comment]
There's some similarity here with #2375

**Comment by tmat** [comment]
@ManishJayaswal

**Comment by nguerrera** [comment]
A few things that come to mind:

* At present, .NET Native would have to return false always as it doesn't have the metadata in the ECMA-335 format nor does it even have all of the metadata in its own private format.
* Under what other conditions do we expect false? How would something like Roslyn scripting handle that -- I assume it would result in an error running the script.
* Do you expect this to return the full PE image or just the metadata section?

**Comment by tmat** [comment]
@nguerrera  
- .NET Native: yes, that's expected. Roslyn scripting does not target .NET Native as there is no runtime code-gen

- AssemblyBuilder would return false. Baked dynamic assemblies produced by Ref.Emit might be possible to serialize.

- Just the metadata section. We should have a separate method TryGetPEImage or something to retrieve the PE image. Metadata might be (in theory) available in more cases than the PE image. And the PE image is not always needed (Roslyn wouldn't need it).

**Comment by weshaggard** [comment]
Adding link to API Review https://github.com/dotnet/apireviews/tree/master/2015-08-21-TryGetRawMetadata

**Comment by davidfowl** [comment]
@tmat @nguerrera Will this API work for modules loaded with Assembly.Load(byte[], byte[])? We might be able to use this for runtime compilation for razor pages as well if that's the case.

**Comment by jkotas** [comment]
@davidfowl This will work for assemblies loaded with AssemblyLoadContext.LoadFromStream. (There is no Assembly.Load(byte[], byte[]) in the .NET Core CoreCLR public surface.)

**Comment by ellismg** [comment]
Can this be closed now that dotnet/coreclr@f7d9f0b298f7801344172fbaa5ec435be7e7171f has landed?

**Comment by kouvel** [comment]
The corefx side changes just went in today. Once Loader.dll is published, I'll send out a PR with a couple of basic test cases, and will close as part of that.

**Comment by kouvel** [comment]
I will add a unit test for this separately along with LoadUnmanagedDllFromPath. Closing

**Comment by stakx** [comment]
@tmat commented [above](https://github.com/dotnet/corefx/issues/2768#issuecomment-130790830):

> We should have a separate method `TryGetPEImage` to retrieve the PE image.

Are there any plans to add implement such a method?
