### ISSUE TITLE
Custom validation of server certificate for ClientWebSocket

### ISSUE THREAD

**Issue by tintoy** [dotnet/corefx#27680]
Hi.

At present (i.e. 2.1 preview), it seems like the new managed code underneath `ClientWebSocket` supports client certificates but not custom validation of the server certificate. I've been building a [Kubernetes API client](https://github.com/tintoy/dotnet-kube-client), and have gotten stuck connecting to clusters with self-signed certificates (which seems to be fairly common).

Are there plans to add support for custom validation of the server certificate? I managed to get things working through some [hideous hackery](https://gist.github.com/tintoy/93b79020281b6050bd6a457e5263d571#file-clientwsfactory-cs-L23) but I'd much rather use the official support if possible :)

PS. I did search for existing issues, but didn't find anything conclusive about the current state of things.

**Comment by stephentoub** [comment]
Thanks. Dup of https://github.com/dotnet/corefx/issues/12038.  Someone just needs to put together a proposal that can be reviewed.  Please feel free.
