### ISSUE TITLE
Productize OwnedArray<T>

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#27688]
What are the plans for productizing OwnedArray<T>? (https://github.com/dotnet/corefxlab/blob/master/src/System.Buffers.Primitives/System/Buffers/OwnedArray.cs)

Is it expected to be included in System.Buffers in 2.1?

cc @ahsonkhan @KrzysztofCwalina

**Comment by ViktorHofer** [comment]
cc @KrzysztofCwalina

**Comment by ahsonkhan** [comment]
> Is it expected to be included in System.Buffers in 2.1?

Maybe in the future, but not for 2.1. OwnedMemory is an abstract class and you can implement a concrete OwnedArray yourself, if needed.

Can you please share the scenario which requires such an implementation, if you have one?

**Comment by davidfowl** [comment]
I'm interested in why you need it as well.

**Comment by ViktorHofer** [comment]
I'm not dependent on this at the moment, but here's the use case. Input ReadOnlySpan<char> needs to be converted to a ReadOnlyMemory<char>. Pooling should be used to minimize allocation:

```csharp
public class Holder : IDisposable
{
    private OwnedMemory<char> _ownedInput;
    private ReadOnlyMemory<char> _memoryInput;

    private void SetInput(ReadOnlySpan<char> input)
    {
        // If input length <= 1024 * 1024 * 1024 rent chars from pool
        if (input.Length <= MemoryPool<char>.Default.MaxSize)
        {
            _ownedInput = MemoryPool<char>.Default.Rent(input.Length);
            input.CopyTo(_ownedInput.Span);
            _memoryInput = _ownedInput.Memory;
        }
        // If input is larger then allocate on heap
        else
        {
            _ownedInput = new OwnedArray<char>(input.ToArray());
            _memoryInput = _ownedInput.Memory;
        }
    }

    // ... code ommited here

    public void Dispose()
    {
        _ownedInput?.Dispose();
    }
}
```

**Comment by jkotas** [comment]
You can just directly create `Memory<T>` from array. You do not need OwnedArray intermediate in your example.

**Comment by jkotas** [comment]
And if you are looking for something that creates memory blocks with automatic pooling, we have a public `MemoryPool<T>.Shared` for that.

**Comment by ViktorHofer** [comment]
> And if you are looking for something that creates memory blocks with automatic pooling, we have a public MemoryPool<T>.Shared for that.

I believe I'm already using that in my example in the if clause. This only allows inputs with a max size of 1024*1024*1024 items.

> You can just directly create Memory<T> from array. You do not need OwnedArray intermediate in your example.

Right, because I wasn't using any of the APIs of OwnedMemory<T> in my example as e.g. Retain, Pin, etc.

**Comment by jkotas** [comment]
I see.

> This only allows inputs with a max size of `1024 * 1024 * 1024` items

Where is this limit hardcoded?

**Comment by ViktorHofer** [comment]
Gosh, I was looking at an outdated version in corefxlab: https://source.dot.net/#System.Buffers.Primitives/System/Buffers/Pooling/ArrayMemoryPool.cs,18

Since then the maxsize doubled (int.MaxSize): https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/Buffers/ArrayMemoryPool.cs#L15
