### ISSUE TITLE
Rename PipeReader.OnWriterCompleted and PipeWriter.OnReaderCompleted

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#27705]
In an early API review we agreed that OnWriterCompleted and OnReaderCompleted should be renamed to RegisterWriterCompleted and RegisterReaderCompleted since they were registering callbacks.

/cc @terrajobst @pakrym @KrzysztofCwalina @halter73

**Comment by karelz** [comment]
@davidfowl is there more API review feedback we didn't incorporate yet? Technically speaking we are past API freeze for 2+ weeks, so we should limit API surface churn + get shiproom approval. Let's make sure we are done with the API surface.

**Comment by karelz** [comment]
cc @joshfree @muratg

**Comment by muratg** [comment]
I think it's already too late to do this. Unless Fowler super-cares about this, my vote is to close it.

**Comment by davidfowl** [comment]
Sorry @Drawaes we're going to punt this one/

**Comment by Drawaes** [comment]
No skin off my nose :) I was just crushing some stuff labeled 2.1 while bored
