### ISSUE TITLE
Span<T> And Vectors

### ISSUE THREAD

**Issue by ghost** [dotnet/corefx#27707]
Is there a plan to use Span< T > with Vectors?
It can be faster than copying array elements to the Vector.
Also, the static Vector calss can use it to do operations on two arrays in slices. Ecah method in the Vector class can have another overload with two T[] params instead of Vector< T > param and returns T[] or Memory< T >. If Vector< T > can make use of Span<T> slices (by adding a new constuctor that accepts Span< T >), it will be easy and fast to repeat the same operations on the array slices.

**Comment by MarcoRossignoli** [comment]
WIP https://github.com/dotnet/corefx/pull/26499

**Comment by MohammadHamdyGhanem** [comment]
https://github.com/dotnet/corefx/issues/26251

**Comment by eerhardt** [comment]
@MohammadHamdyGhanem - can you provide a proposal for what you are thinking by following the [API review process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md)?  I think listing usage scenarios would help this proposal.

**Comment by dangi12012** [comment]
You were faster than me on this one. .Net team please create support for: 
new Vector3(Span<float> Elements)
new Vector<float>(Span<float> Elements)
CopyTo(Span<float> Elements) //Performance!!
public void Deconstruct(out float x, out float y, out float z) //Valuetuple: var (x,y,z) = myvector

**Comment by GrabYourPitchforks** [comment]
Is there anything left to consider for this issue? The `Vector<T>` type was updated with some support for `Span<T>` in the 2.x and 3.x releases.

**Comment by tannergooding** [comment]
I don't believe so.
The issue (or a new one) can always be reopened if there is something someone feels is missing.
