### ISSUE TITLE
System.Memory package needs Xamarin support

### ISSUE THREAD

**Issue by marek-safar** [dotnet/corefx#27731]
Dev 15-7 is shipping with inbox Memory/Span support on Xamarin. We need System.Memory package update to behave as inbox on all Xamarin profiles

**Comment by joshfree** [comment]
@joperezr could you take a look?

**Comment by joshfree** [comment]
@marek-safar can you confirm that you've snapped to the latest surface area in corefx master?

**Comment by marek-safar** [comment]
@joshfree we are tracking corefx/2.1 branch

**Comment by joshfree** [comment]
@marek-safar that's still currently Preview1 bits.  You should look at what's in master as there are a number of changes between Preview1 and 2.

/cc @davidfowl @pakrym as well who are still making tweaks to Pipelines.

**Comment by marek-safar** [comment]
@joshfree we are shipping only pieces of corefx so other new stuff is not an issue but I hope to see 2.1 branch updated very soon.

**Comment by joshfree** [comment]
The other new stuff is in the System.Memory package.

**Comment by marek-safar** [comment]
Oh, I see there are some unrelated types bundled in. Well, this is going to be interesting to build.

I'll add a list of types to type-forward to our custom mscorlib. I think @weshaggard done it for some netstandard nugets before so there should be a way for you to do it but we'll need to update the platform APIs in https://github.com/dotnet/standard/tree/master/platforms

**Comment by weshaggard** [comment]
The APIs in System.Memory are not part of netstandard (at least not yet), but they instead target netstandard. For Xamarin you will just need to ensure that all the APIs are added either inbox in your mscorlib and type-forwarded or in a partial OOB System.Memory library you would include in Xamarin. The main point is that you will need to make sure all the API's are inbox on Xamarin in order for this to work. 

While not all of the APIs for System.Memory are type-forwarded to System.Private.CoreLib the entire System.Memory library will still be inbox for .NET Core, so the same will need to be true for Xamarin.

**Comment by marek-safar** [comment]
@weshaggard that's not how we intend to do it right, we'll ship the only subset of types available in System.Memory as part of dev15-7 (the rest could come later) and as this package is the only way how to write cross target code with Span<T> we'd like to have these types forwarded to avoid duplicate types compilation errors.

**Comment by weshaggard** [comment]
Just to clarify @marek-safar is the ask to simply add the Xamarin placeholders to our package even though it contains more API's then what Xamarin currently has? Then in a follow-up release you guys will fill it the rest of the APIs?

**Comment by marek-safar** [comment]
@weshaggard that would work.

The more complicated version of having typeforwarders to our mscorlib for some types with an implementation for the rest is probably not doable for you, right?

**Comment by weshaggard** [comment]
>The more complicated version of having typeforwarders to our mscorlib for some types with an implementation for the rest is probably not doable for you, right?

Currently corefx doesn't have a targeting pack that represents Xamarin so that would be more difficult to do right now. If you would like to start producing those shims from corefx then we could definitely figure out a way to do that but lets file a separate issue for that if we want to do it and do it for other libraries as well.
