### ISSUE TITLE
Test failure: Proxy_UseSecureProxyTunnel_Success test hangs on WinHttpHandler/NetFxHandler/CurlHandler

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#27746]
It was already disabled but the ActiveIssue was wrong, so I'm filing this to track.

**Comment by stephentoub** [comment]
Also hangs on netfx; updating title.

**Comment by karelz** [comment]
FYI: The test was added few weeks ago by @wfurt

**Comment by pjanotti** [comment]
On macOS High Sierra (10.13) the release version of this test is hanging too.
