### ISSUE TITLE
System.Globalization: Encodings

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#2774]
We have stubbed out [EncodingTable.cs](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Globalization/EncodingTable.Unix.cs) and [EncodingDataItem.cs](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Globalization/EncodingDataItem.Unix.cs) for cross platform, but it is not clear the implementation is correct or if we need to do more.

I think the big issue here will be understanding if System.Text.Encoding.Codepages and the EncodingProvider model here reduces the scope of work that we need to.

**Comment by dougbu** [comment]
@ellismg does this issue have the downstream impact that `System.Text.Encoding`'s `ASCII` property is of type `System.Text.UTF8Encoding` with Core CLR on Linux? If not, is that something else in this repo or a new issue?

**Comment by ellismg** [comment]
@dougbu, I believe so.

**Comment by ellismg** [comment]
Eric, can you take a look into this?  Tarek and Wes understand the encoding provider model and I can also answer questions tomorrow while I travel.
