### ISSUE TITLE
Where is System.Web.Http?

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/corefx#27764]
Hi,
I'm trying to convert an ASP.NET project from .NET Framework 4.7.1 to .NET Core 2.1 (preview).
My methodology was to rename the folder from `MyAspProj` to `MyAspProj.Old`, then in the solution I created a new .NET Core ASP.NET project called `MyAspProj`, then copied over all the files from `MyAspProj.Old`. I added a reference to `Microsoft.AspNetCore.All`, which I hoped would bring through all the necessary types. but alas, everywhere that I have references to objects from the `System.Web.Http` namespace, my code is broken, with no obvious contenders to redirect the references.
For example, `HttpConfiguration`, which is used for Owin configuration.
And, while we're there, the Owin package itself is targeting .NET Framework. Is there a successor that targets .NET Core?

**Comment by davidfowl** [comment]
There's a doc that describes how to convert from WebAPI to ASP.NET Core https://docs.microsoft.com/en-us/aspnet/core/migration/webapi.

**Comment by shaulbehr** [comment]
@davidfowl Thanks for the link, that had quite a few useful tips.
Maybe you can point me further in the right direction. We are a company with a very successful product and a user base in the hundreds of thousands We're strongly considering migrating our whole codebase to .NET Core, mostly because we're really frustrated with SignalR not working as expected, and we hear that .NET Core has finally got SignalR fixed up. Plus of course all the other improvements, like way improved build times and EF being able to handle Group By queries.
BUT...
I've put a couple of days' work now into attempting to migrate our code, and I'm drowning. There are just so many things where the cheese got moved, and with such a new technology, there's almost no help on the Internet that deals with anything beyond the happy path, so every time I hit an edge case, I get frustrated.
I think our company could be an excellent test case for Microsoft to demonstrate how to migrate a real world project from .NET Framework to .NET Core. Are there any engineers on your team who could give us a few hours of time to coach us through migrating our code?
TIA,
Shaul

**Comment by karelz** [comment]
I think it would be best to move the discussion to ASP.NET Core repo https://github.com/aspnet as it is unrelated to CoreFX. @shaulbehr are you ok if I close it here?

**Comment by tarekgh** [comment]
This issue was moved to aspnet/Home#2928
