### ISSUE TITLE
NRE from ClientWebSocket.ConnectAsync when using ClientCertificates option

### ISSUE THREAD

**Issue by arekpalinski** [dotnet/corefx#27768]
Version: 2.1.300-preview2-008302 (also checked using latest master branch)

Sample code:
```
var cws = new ClientWebSocket();     
cws.Options.ClientCertificates.Add(new X509Certificate2(@"path-to-certificate.pfx"));
await cws.ConnectAsync(new Uri("wss://...."), CancellationToken.None);
```

throws:
```
System.NullReferenceException: Object reference not set to an instance of an object.
at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
```

According to my investigation NRE is thrown in the following line:
https://github.com/dotnet/corefx/blob/9ce903333efeb3eb5fef069f9caf868cb2309170/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.Managed.cs#L97

`handler.SslOptions.ClientCertificates` is `null`

Initializing the certificates collection there:

`handler.SslOptions.ClientCertificates = new X509Certificate2Collection();`

seems to fix the problem (`await cws.ConnectAsync()` succeeds)

**Comment by stephentoub** [comment]
Thank you for the issue. Your assessment is correct.  I'll fix it now.
