### ISSUE TITLE
SystemEventsTests.CreateTimerTests.TimerElapsedSignaled test failing in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#27771]
This has now happened a few times...

https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/cf51308927f648c6f751dd4451c4a984744cb7b2/workItem/Microsoft.Win32.SystemEvents.Tests/analysis/xunit/Microsoft.Win32.SystemEventsTests.CreateTimerTests~2FTimerElapsedSignaled
```
Windows.10.Amd64.Open-Release-x86
Get Repro environment
Unhandled Exception of Type System.Runtime.InteropServices.ExternalException
Message :
System.Runtime.InteropServices.ExternalException : Cannot create timer.
Stack Trace :
   at Microsoft.Win32.SystemEvents.CreateTimer(Int32 interval) in D:\j\workspace\windows-TGrou---f8ac6754\src\Microsoft.Win32.SystemEvents\src\Microsoft\Win32\SystemEvents.cs:line 530
   at Microsoft.Win32.SystemEventsTests.CreateTimerTests.TimerElapsedSignaled() in D:\j\workspace\windows-TGrou---f8ac6754\src\Microsoft.Win32.SystemEvents\tests\SystemEvents.CreateTimer.cs:line 50
```
cc: @ericstj

**Comment by stephentoub** [comment]
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/9353/consoleText

**Comment by ericstj** [comment]
Is this only netfx or is it core as well?

**Comment by ericstj** [comment]
I suspect if this is failing we'll also need to disable the concurrent timers test.  If its happening for Core as well I'll add some logging and hopefully we can find out what's going wrong.

**Comment by stephentoub** [comment]
Core as well, e.g.
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/cf51308927f648c6f751dd4451c4a984744cb7b2/workItem/Microsoft.Win32.SystemEvents.Tests/analysis/xunit/Microsoft.Win32.SystemEventsTests.CreateTimerTests~2FTimerElapsedSignaled

**Comment by ericstj** [comment]
I see.  I have a theory for what's going on.  I believe it is the same race condition I worked around here: https://github.com/dotnet/corefx/commit/ecf00da10b26c962d3363fd2f01c88b4f77e4ae9

Essentially one thread starts creating the HWND and that allows another thread to proceed through EnsureSystemEvents even though the HWND doesn't exist yet.

I worked around this a bit in the tests that send messages, but not the CreateTimer tests.

I think I'll need to fix EnsureSystemEvents to actually safely ensure, so that when it returns it guarantees that the window is created (or throws) rather than just garunteeing that `s_systemEvents` is not null.

**Comment by stephentoub** [comment]
> I suspect if this is failing we'll also need to disable the concurrent timers test.

You're right, they just failed here:
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/66d5efaf79c0561da5b90c3c548fd3d0f43bb579/workItem/Microsoft.Win32.SystemEvents.Tests/analysis/xunit/Microsoft.Win32.SystemEventsTests.CreateTimerTests~2FConcurrentTimers

**Comment by ericstj** [comment]
I have a real fix ready just need to submit the PR once out of meetings

**Comment by stephentoub** [comment]
Ok, thanks.

**Comment by stephentoub** [comment]
@ericstj, this failed again on netfx:
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/10178/consoleText
```
      Microsoft.Win32.SystemEventsTests.CreateTimerTests.TimerElapsedSignaled [FAIL]
        Assert.False() Failure
        Expected: False
        Actual:   True
        Stack Trace:
             at Microsoft.Win32.SystemEventsTests.CreateTimerTests.TimerElapsedSignaled()
```

**Comment by jkotas** [comment]
Failed again in https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_corefx_baseline_prtest/365/

**Comment by stephentoub** [comment]
Replaced by https://github.com/dotnet/corefx/issues/29166
