### ISSUE TITLE
RSA incompatibility between full framework and .net core?

### ISSUE THREAD

**Issue by gingters** [dotnet/corefx#27776]
I have a problem when working with RSA in .NET Full framework (4.6.2) and .net core 2. There is an existing full framework application that encrypts and decrypts files using certificates. The goal is to create a compatible .net core application that can exchange encrypted files with the existing application. 

In short, an symmetrical AES key is used to encrypt the actual file data. The AES key is then encrypted with the receivers public RSA key.

I got it working 3/4 of the way. That is:
 * The full framework application can (of course) encrypt files and decrypt them.
 * The .net core application can encrypt files and decrypt them.
*  The .net core application can encrypt files, which can be decrypted with the full framework application.
*  The .net core application **cannot** decrypt files, which have been encrypted with the full framework application.

In the last case I get an `WindowsCryptographicException` with the message `The parameter is incorrect` (internally its Error code 87).

The full 4.6.2 framework application uses the certificate of the receiver as such:

```
var rsa = receiverCertificate.PublicKey.Key as RSACryptoServiceProvider;
// *snip* create AES key
var encryptedAesKey = rsa.Encrypt(aesManaged.Key, false);
```

When decrypting, it does the following:
```
var rsa = receiverCertificate.PrivateKey as RSACryptoServiceProvider;
// *snip* extract encrypted aes key from encrypted file
var decryptedKey = rsa.Decrypt(encryptedKey, false);
```

Now, in .net core it is not possible to cast the key directly to `RSACryptoServiceProvider`.
To re-use most of the existing code and port that over to .NET core I wrote these two extension methods to get an `RSACryptoServiceProvider` out of the keys, like this:

```
public static RSACryptoServiceProvider GetPublicKeyRsaCryptoServiceProvider(this X509Certificate2 certificate)
{
   // Get params from public key
   var rsa = certificate.GetRSAPublicKey();
   var rsaParameters = rsa.ExportParameters(false);

   var csp = new RSACryptoServiceProvider(rsa.KeySize, new CspParameters()
   {
      ProviderType = 24,
      ProviderName = "Microsoft Enhanced RSA and AES Cryptographic Provider",
   });
   csp.ImportParameters(rsaParameters);

   return rsacsp;
}

public static RSACryptoServiceProvider GetPrivateKeyRsaCryptoServiceProvider(this X509Certificate2 certificate)
{
   // Get params from private key
   var rsa = certificate.GetRSAPrivateKey();
   var rsaParameters = rsa.ExportParameters(true);

   var csp = new RSACryptoServiceProvider(rsa.KeySize, new CspParameters()
   {
      ProviderType = 24,
      ProviderName = "Microsoft Enhanced RSA and AES Cryptographic Provider",
   });
   csp.ImportParameters(rsaParameters);


   return rsacsp;
}
```

The only lines I changed while porting the existing code over to .net core were the lines that casted the public/private key to `RSACryptoServiceProvider `and replaced the casts with calls to my extension methods.
Before changing more and to completely move over to the RSA class from `RSACryptoServiceProvider`, so that the .net core application can eventually run on other OSes, I want this to work first in a full roundtrip.
For additional info: I get hold of the `X509Certificate2` instance like this:

```
using (var myStore = new X509Store(StoreName.My, StoreLocation.CurrentUser))
{
   myStore.Open(OpenFlags.ReadOnly);
   var certs = myStore.Certificates.Find(X509FindType.FindByKeyUsage,    X509KeyUsageFlags.DataEncipherment.ToString(), true);
   return certs.FirstOrDefault(c => c.Subject.Contains("receiver"));
}
```

The error is thrown in the actual call to `RSACryptoServiceProvider.Decrypt()`, when it goes through the `CapiHelper.Decrypt()` into `CapiHelper.Interop.CryptDecrypt()` which returns with the error code.

**Comment by krwq** [comment]
@gingters have you tried using RSA directly? You should be able to call `GetRSAPublicKey()`. See this test for reference: https://github.com/dotnet/corefx/blob/50218eaa16dbe5812752919f2e195893cedea507/src/System.Security.Cryptography.X509Certificates/tests/ExportTests.cs#L147

**Comment by bartonjs** [comment]
@gingters I have not been able to reproduce your problem.  If you can produce a stable repro I would be very interested in identifying and solving the bug, but currently there isn't enough to go on... everything I've tried has resulted in success.

**Comment by bartonjs** [comment]
Moving to future, but if we can get a stable repro then we should look at it and re-assess.

**Comment by bartonjs** [comment]
As we aren't able to reproduce this problem, there's nothing we can do to further diagnose or resolve it.  Closing until further information is received.
