### ISSUE TITLE
It seems that ReadOnlyMemory can not have OwnedMemory as object

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/corefx#27808]
I see next comment in `ReadOnlyMemory` https://source.dot.net/#System.Private.CoreLib/shared/System/ReadOnlyMemory.cs,28
```cs
        // The highest order bit of _index is used to discern whether _object is an array/string or an owned memory
        // if (_index >> 31) == 1, _object is an OwnedMemory<T>
        // else, _object is a T[] or string
```

I see that all code use `_index` without checking this flag.
Also the only way to create `ReadOnlyMemory` with such flag is to call `internal ReadOnlyMemory(object obj, int start, int length)` constructor. https://source.dot.net/#System.Private.CoreLib/shared/System/ReadOnlyMemory.cs,86
But it never called with such flag. See all references to this constructor.

Only `public ReadOnlySpan<T> Span` method used this flag. https://source.dot.net/#System.Private.CoreLib/shared/System/ReadOnlyMemory.cs,162

But it looks like phantom code that never executed because this flag is never is true.

Am I right and this flag and phantom code should be removed?

**Comment by stephentoub** [comment]
> I see that all code use _index without checking this flag

It checks whether the index is negative, which is the same thing.

> Also the only way to create ReadOnlyMemory with such flag is to call

No, is very common for this to happen when casting from Memory.

**Comment by AlexRadch** [comment]
@stephentoub I know that when flag is set then index will be negative. But only method that check this is `Span` property.
I wrote about `ReadOnlyMemory` structure! Not `Memory` structure that checks such flag!

**Comment by AlexRadch** [comment]
@stephentoub I see `return new ReadOnlyMemory<T>(_object, _index + start, _length - start);` does not require flag testing.

**Comment by stephentoub** [comment]
> I wrote about ReadOnlyMemory structure! Not Memory structure that checks such flag!

I know you wrote about ReadOnlyMemory.  My comment was that an extremely common way of creating ReadOnlyMemory is by casting to it from Memory, in which case it's just a reinterpret cast, maintaining all of the bits from the Memory, so if the Memory had this flag set, so too will ReadOnlyMemory.

>  see return new ReadOnlyMemory<T>(_object, _index + start, _length - start); does not require flag testing.

Right, it doesn't require testing it because start is always going to be non-negative and start+_index will not overflow and thus it won't affect whether that bit is set or not in the result.
