### ISSUE TITLE
What happens when a new era is added in Japanese Calendar?

### ISSUE THREAD

**Issue by tanaka-takayoshi** [dotnet/corefx#27800]
(moved from https://github.com/dotnet/cli/issues/8733 )
I wonder this might not a suitable repo for this issue. Please let me know the right repo and then I'll move.

A new era will be added in Japanese Calendar, which is planned to start at May 1st 2019. I'd like to clarify how Japanese Calendar will be updated.

Here are my understanding about a new era. I would appreciate .NET Core team confirm it. I also want a dedicated document explaining a new era and help creating it.

- At present Japanese Calendar is the only Calendar which a new era could be added. https://github.com/dotnet/coreclr/blob/v2.0.5/src/mscorlib/shared/System/Globalization/CalendarData.Unix.cs#L269
- For Windows, Japanese era info is obtained from registry. Once registry is updated to the new era, .NET Core on WIndows can get a new era info. https://msdn.microsoft.com/ja-jp/library/windows/desktop/dd317805%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396
- For Unix (Linux and Mac), Japanese era info is obtained from lib-icu. Once a new version of icu is installed to the machine, .NET Core on Unix can get a new era info.
https://github.com/dotnet/coreclr/blob/v2.0.5/src/mscorlib/shared/Interop/Unix/System.Globalization.Native/Interop.Calendar.cs
- In the case .NET Core can't get a era info from registry on Windows and lib-icu on Unix, .NET Core uses [a hard-coded era info](https://github.com/dotnet/coreclr/blob/v2.0.5/src/mscorlib/shared/System/Globalization/JapaneseCalendar.cs#L97-L120). I'm not sure when this hard-coded era info is used actually. However in this case, upgrading .NET Core CLR is required to update a new era info. Also, if the application is built as a Self Contained Application, I wonder we can't update the a new era info in this application.

Are these issues related?
https://github.com/dotnet/corefx/issues/27506
https://github.com/dotnet/corefx/pull/27617

**Comment by joshfree** [comment]
@tarekgh what is our solution here for when the Japanese Era changes May 1, 2019?

**Comment by tarekgh** [comment]
> At present Japanese Calendar is the only Calendar which a new era could be added. 

That is right.

> For Windows, Japanese era info is obtained from registry. Once registry is updated to the new era, .NET Core on WIndows can get a new era info.

That is right too. We are already testing the scenario of the new era by updating the registry on Windows.

> For Unix (Linux and Mac), Japanese era info is obtained from lib-icu. Once a new version of icu is installed to the machine, .NET Core on Unix can get a new era info.

Yes. We just need to test this scenario when we have updated ICU library with the new era info. 

> In the case .NET Core can't get a era info from registry on Windows and lib-icu on Unix, .NET Core uses a hard-coded era info. I'm not sure when this hard-coded era info is used actually. However in this case, upgrading .NET Core CLR is required to update a new era info. Also, if the application is built as a Self Contained Application, I wonder we can't update the a new era info in this applicatio

Actually, this is just a fallback when there is something really wrong. this scenario is unlikely and people shouldn't count on that at all. 

> Are these issues related? #27506 #27617

Yes, this was part of our testing with the new era info added to Windows machines.

> what is our solution here for when the Japanese Era changes May 1, 2019?

Everything should work seamlessly as long as the users get Windows updates (to update the data in the registry) and Linux users will install the updated ICU library that contains the new era info. 

CC @krwq @AlexGhiondea 

I am going to close this issue but feel free to send more questions if you have any.

**Comment by tarekgh** [comment]
One small correction, we have also JapaneseLunisolarCalendar which is using JapaneseCalendar eras too.

**Comment by krwq** [comment]
@tarekgh thank you!
