### ISSUE TITLE
Add MethodDefinition.GetSemantics

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#27802]
```C#
namespace System.Reflection.Metadata
{
    public struct MethodDefinition
    {
        ...
        public MethodSemanticsAttributes GetSemantics();
        ...
    }
}
```

Use case: ILSpy needs to determine whether a given method is an accessor of a property or event.

**Comment by terrajobst** [comment]
The API looks fine as proposed, but is this data really on the method definition (as opposed to the property/event definition)? I thought the same method can be used by multiple properties/events in metadata.

**Comment by terrajobst** [comment]
@tmat ping

**Comment by dgrunwald** [comment]
While we need the direction method->property/event in ILSpy (not just the semantics attribute, also the association); we could create a lookup table on our own if there was a way to access the MethodSemantics table.

Currently we're calling `GetAccessors()` on every property and event, but that doesn't return the "other" accessors.

**Comment by tmat** [comment]
@terrajobst Is right that this API would need to deal with the case where a method is shared among multiple properties/events. It'd also be linear lookup, so perhaps this is not the best API.

@dgrunwald 
PropertyDefinition.GetAccessors return 'other' accessors in the latest version: https://source.dot.net/#System.Reflection.Metadata/System/Reflection/Metadata/TypeSystem/HandleCollections.TypeSystem.cs,1619
