### ISSUE TITLE
X509Certificate2.GetECDsaPrivateKey does not work with an ECC certificate with private key in TPM

### ISSUE THREAD

**Issue by MikeRosoft** [dotnet/corefx#27812]
I am currently encountering the same problem as reported here: https://github.com/dotnet/corefx/issues/9070. I have an ECC certificate in the certificate store with a private key in 'Trusted Platform Module' (TPM). The certificate with a private key has been generated using a Windows domain. When I try to get the ECDsa instance using the GetECDsaPrivateKey method, I get ArgumentException: 'Keys used with the ECDsaCng algorithm must have an algorithm group of ECDsa'.

When I instead use a certificate which has been imported to the certificate store from a PFX file (signing certificate created by OpenSSL), the error does not occur.

Operating system: Windows 10 64-bit
.NET Framework: 4.7 (the exception also occurs in .NET 4.7.1)

**Comment by MikeRosoft** [comment]
I strongly suspect that the bug is related to this one: https://github.com/dotnet/corefx/issues/26541; i.e. calling CngKey.Create(CngAlgorithm.ECDsaP256, ...) with CngProvider("Microsoft Platform Crypto Provider") returns an object with AlgorithmGroup "RSA". (Possibly .NET Framework tries to create a similar CngKey object and trying to use it to create an ECDSa object causes the same exception.)

Does that mean that retrieving a private key using ECC algorithm and with a key on TPM will not work out of the box? Is there any workaround?

**Comment by bartonjs** [comment]
Yes, it's the same problem and it requires a Windows OS update to fix.

I would expect that the fix would be available to [Windows Insider Builds](https://insider.windows.com/en-us/) before general rollout.  That route could let you know that a fix is coming, and give you the ability to understand your minimum OS version.

The only real workaround would be to directly P/Invoke to [NCryptSignHash](https://msdn.microsoft.com/en-us/library/windows/desktop/aa376295(v=vs.85).aspx).  If you declare your P/Invoke to accept a SafeNCryptKeyHandle as the first parameter you can pass the `Handle` value of a `CngKey` object.
