### ISSUE TITLE
System.Net.Sockets.Socket: No buffer space available when setting SendBufferSize

### ISSUE THREAD

**Issue by rmsutton** [dotnet/corefx#27814]
I am trying to create a socket with an 8MB buffer (8388608 bytes) with the following code.

```
var socket = new Socket(SocketType.Stream, ProtocolType.Tcp);
socket.SendBufferSize = Setting.NetworkBufferSize;
socket.ReceiveBufferSize = Setting.NetworkBufferSize;
socket.NoDelay = true;
```

The code fails on the second line with "No buffer space available".

```
System.Net.Sockets.SocketException: "No buffer space available"
  at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
  at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
  at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
  at System.Net.Sockets.Socket.set_SendBufferSize(Int32 value)
```

This code works fine when executing in a Windows environment.

Is this behavior expected?

**Comment by stephentoub** [comment]
> Is this behavior expected?

That error is coming from the operating system; the .NET code is just calling `setsockopt` and is getting back ENOBUFS.  As outlined at https://www.gnu.org/software/libc/manual/html_node/Error-Codes.html, this means "'No buffer space available.' The kernel’s buffers for I/O operations are all in use."

**Comment by karelz** [comment]
Seems to be answered, closing.

**Comment by wfurt** [comment]
Look at https://www.cyberciti.biz/faq/linux-tcp-tuning/ @rmsutton You can increase maximums buffer sizes via /proc and than the code should just work.

**Comment by rmsutton** [comment]
Thanks @wfurt. I should have mentioned I am running this on macOS. I will look into increasing the buffer sizes. Appreciate the quick replies from everyone here!
