### ISSUE TITLE
TestChildProcessCleanupAfterDispose(true) failed in CI on Linux

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#27823]
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/ed9ac7bd3de570b921d74473ded3a06ba9f2baee/workItem/System.Diagnostics.Process.Tests/analysis/xunit/System.Diagnostics.Tests.ProcessTests~2FTestChildProcessCleanupAfterDispose(shortProcess:%20False,%20enableEvents:%20True)
```
Debian.87.Amd64.Open-Release-x64
Get Repro environment
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Assert.True() Failure
Expected: True
Actual:   False
```
cc: @tmds

**Comment by tmds** [comment]
`System.Diagnostics.Tests.ProcessTests/TestChildProcessCleanupAfterDispose(shortProcess: False, enableEvents: True)` failed.
This test:
starts a process that sleeps 500ms
checks the process is reaped within 1000ms after start

@stephentoub I suggest to increase the timeout. I'll do a PR if ok for you.

**Comment by stephentoub** [comment]
> checks the process is reaped within 1000ms after start

Yeah, that's too short for CI.

**Comment by danmosemsft** [comment]
@tmds I suggest a really large time like 30 secs - since it's not a sleep, just a timeout. I have seen test in CI be absurdly slow possibly when run concurrently with some other stressful test.
