### ISSUE TITLE
Consider SafeHandle semantics for OwnedMemory

### ISSUE THREAD

**Issue by ektrah** [dotnet/corefx#27824]
*ReadOnlyMemory&lt;T&gt;:*

https://github.com/dotnet/corefx/blob/5c7f5447f49ff6a7aa935765a993c42c70a1b699/src/Common/src/CoreLib/System/ReadOnlyMemory.cs#L234

*OwnedMemory&lt;T&gt;:*

https://github.com/dotnet/corefx/blob/41a2120b233cc02c175f812e4e19e3f058396cb0/src/Common/src/CoreLib/System/Buffers/OwnedMemory.cs#L46

https://github.com/dotnet/corefx/blob/41a2120b233cc02c175f812e4e19e3f058396cb0/src/Common/src/CoreLib/System/Buffers/OwnedMemory.cs#L87

Is it intended that these two types have different usage patterns?

It's also not not very clear if a call to `OwnedMemory<T>.Pin()` implies a call to `OwnedMemory<T>.Retain()` or not.

<details>
<summary>Proposed changes (click to expand)</summary>

```diff
 namespace System.Buffers
 {
     public abstract class OwnedMemory<T> : IDisposable, IRetainable
     {
         public abstract int Length { get; }
         public abstract Span<T> Span { get; }
         public Memory<T> Memory { get; }
-        public abstract MemoryHandle Pin(int byteOffset = 0);
         public void Dispose()
         protected abstract void Dispose(bool disposing);
         protected abstract bool IsRetained { get; }
         public abstract bool IsDisposed { get; }
-        public abstract void Retain();
+        public abstract MemoryHandle Retain(bool pin = false, int byteOffset = 0);
-        public abstract bool Release();
     }
 }
```

or, less preferably,

```diff
 namespace System
 {
     public readonly struct ReadOnlyMemory<T>
     {
         public ReadOnlyMemory(T[] array)
         public ReadOnlyMemory(T[] array, int start, int length)
         public static implicit operator ReadOnlyMemory<T>(T[] array)
         public static implicit operator ReadOnlyMemory<T>(ArraySegment<T> arraySegment)
         public static ReadOnlyMemory<T> Empty { get; }
         public int Length { get; }
         public bool IsEmpty { get; }
         public override string ToString()
         public ReadOnlyMemory<T> Slice(int start)
         public ReadOnlyMemory<T> Slice(int start, int length)
         public ReadOnlySpan<T> Span { get; }
         public void CopyTo(Memory<T> destination)
         public bool TryCopyTo(Memory<T> destination)
-        public MemoryHandle Retain(bool pin = false)
+        public MemoryHandle Pin()
+        public void Retain()
+        public void Release()
         public T[] ToArray()
         public override bool Equals(object obj)
         public bool Equals(ReadOnlyMemory<T> other)
         public override int GetHashCode()
     }
 }
```

</details>

**Comment by ahsonkhan** [comment]
cc @KrzysztofCwalina, @davidfowl

**Comment by KrzysztofCwalina** [comment]
The change would not work. IRetainable requires Retain and Release implementations.

**Comment by ektrah** [comment]
Feel free to ignore the change proposal; the issue is more about the inconsistency in the pattern for retaining and pinning memory.

For perspective, there are also the [SafeHandle ](https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.safehandle(v=vs.110).aspx) class and the lovely [SafeBuffer](https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.safebuffer(v=vs.110).aspx) class that offer even more patterns for the same thing:

```csharp
namespace System.Runtime.InteropServices
{
    public abstract class SafeHandle : CriticalFinalizerObject, IDisposable
    {
        //...
        public void DangerousAddRef(ref bool success);
        public IntPtr DangerousGetHandle();
        public void DangerousRelease();
    }

    public abstract class SafeBuffer : SafeHandleZeroOrMinusOneIsInvalid
    {
        //...
        public unsafe void AcquirePointer(ref byte* pointer);
        public void ReleasePointer();
    }
}
```

I have no idea what IRetainable might be used for; in corefx it seems to be only used in MemoryHandle to **release** an OwnedMemory, not to retain anything. For me, it would make sense to either have a pair of a Retain and a Release method, or a Retain method that returns an IDisposable for release. *But not both.*

(Of course, nothing of this is critical. I'm just reporting an usability problem that has tripped me up more than once.)

**Comment by KrzysztofCwalina** [comment]
@ektrah, thanks for bringing it up. We are looking into doing cleanup here. I like the idea of exploring whether we can use SaheHandle semantics/APIs.

**Comment by ektrah** [comment]
Experimenting a bit more, it looks like I don't have much use for `ReadOnlyMemory<T>.Retain(pin: true)` at all, as pinning `ReadOnlyMemory<T>.Span` is easier and faster:

| Method |     Toolchain |     Mean |     Error |    StdDev |
|------- |-------------- |---------:|----------:|----------:|
| TryGet | .NET Core 2.0 | 24.98 ns | 0.0418 ns | 0.0391 ns |
|   Span | .NET Core 2.0 | 36.61 ns | 0.0895 ns | 0.0793 ns |
| Retain | .NET Core 2.0 | 70.41 ns | 0.0642 ns | 0.0536 ns |
| TryGet | .NET Core 2.1 | 25.12 ns | 0.0720 ns | 0.0673 ns |
|   Span | .NET Core 2.1 | 31.22 ns | 0.0606 ns | 0.0567 ns |
| Retain | .NET Core 2.1 | 83.70 ns | 0.0792 ns | 0.0661 ns |

<details>
<summary>Details (click to expand)</summary>

```
BenchmarkDotNet=v0.10.13, OS=Windows 10 Redstone 3 [1709, Fall Creators Update] (10.0.16299.248)
Intel Core i7-4790K CPU 4.00GHz (Haswell), 1 CPU, 8 logical cores and 4 physical cores
Frequency=3905124 Hz, Resolution=256.0738 ns, Timer=TSC
.NET Core SDK=2.1.300-preview1-008174
  [Host]     : .NET Core 2.0.6 (CoreCLR 4.6.26212.01, CoreFX 4.6.26212.01), 64bit RyuJIT
  Job-BDKCXJ : .NET Core 2.0.6 (CoreCLR 4.6.26212.01, CoreFX 4.6.26212.01), 64bit RyuJIT
  Job-QCQQZE : .NET Core 2.1.0-preview1-26216-03 (CoreCLR 4.6.26216.04, CoreFX 4.6.26216.02), 64bit RyuJIT

Runtime=Core  
```

```csharp
public class Pinning
{
    private static ReadOnlyMemory<char> s_text = "Hello World".ToCharArray();

    [Benchmark]
    public unsafe void TryGet()
    {
        ReadOnlyMemory<char> memory = s_text;

        if (MemoryMarshal.TryGetArray(memory, out var segment))
        {
            fixed (char* ptr = segment.Array)
            {
                byte* buffer = stackalloc byte[32];
                Unsafe.CopyBlockUnaligned(buffer, ptr + segment.Offset, (uint)segment.Count * sizeof(char));
            }
        }
        else
        {
            ReadOnlySpan<char> span = memory.Span;

            fixed (char* ptr = &MemoryMarshal.GetReference(span))
            {
                byte* buffer = stackalloc byte[32];
                Unsafe.CopyBlockUnaligned(buffer, ptr, (uint)span.Length * sizeof(char));
            }
        }
    }

    [Benchmark]
    public unsafe void Span()
    {
        ReadOnlyMemory<char> memory = s_text;

        ReadOnlySpan<char> span = memory.Span;

        fixed (char* ptr = &MemoryMarshal.GetReference(span))
        {
            byte* buffer = stackalloc byte[32];
            Unsafe.CopyBlockUnaligned(buffer, ptr, (uint)span.Length * sizeof(char));
        }
    }

    [Benchmark]
    public unsafe void Retain()
    {
        ReadOnlyMemory<char> memory = s_text;

        using (MemoryHandle handle = memory.Retain(pin: true))
        {
            byte* buffer = stackalloc byte[32];
            Unsafe.CopyBlockUnaligned(buffer, handle.Pointer, (uint)memory.Length * sizeof(char));
        }
    }
}
```

</details>

**Comment by KrzysztofCwalina** [comment]
Yes, retain pin is for pinning for longer than the current frame, e.g. async operations.

**Comment by GrabYourPitchforks** [comment]
Yes, this would be done as part of https://github.com/dotnet/docs/issues/4823. @ektrah has already provided valuable feedback on the draft at Gist, and it will be reopened for community feedback when the docs PR comes in.
