### ISSUE TITLE
 Translate all messages from DataAnnotation

### ISSUE THREAD

**Issue by gabrielimmich** [dotnet/corefx#27820]
Hello, I am trying to translate the standard messages for the RequiredAttribute, MaxLenghtAttribute and other standard Attributes.
Below is the code I have:

```
services.AddMvc().AddRazorOptions(options =>
            {
                options.AddNavigationBootstrap3Views();
            })
            .AddDataAnnotationsLocalization(options =>
            {
                options.DataAnnotationLocalizerProvider = (type, factory) =>
factory.Create(typeof(Tecnologia.Infrastructure.Presentation.Resources.ModelBindingDefault));
            }).AddViewLocalization();

            services.Configure<RequestLocalizationOptions>(options =>
            {
                var supportedCultures = new[] { new CultureInfo("pt-BR") };
                options.DefaultRequestCulture = new RequestCulture("pt-BR", "pt-BR");
                options.SupportedCultures = supportedCultures;
                options.SupportedUICultures = supportedCultures;
            });
```

With this code it is necessary that I pass the key in my attributes
[Required(ErrorMessage = "RequiredAttribute_ValidationError")]

I would like to know if it is possible to use only [Required], I have already verified several issues on the subject, but none has provided a plausible solution for this case. Maybe you have some way to replace Strings.resx with your own resources.

I look forward to returning, thank you.

image from my .resx file
[ModelBindingDefault.resx](http://prntscr.com/io64g6)

**Comment by gabrielimmich** [comment]
Would anyone know how to help me?
I still have not found the solution for this case.

**Comment by ajcvickers** [comment]
@lajones Is this something that you can answer?

Putting this in the backlog for now since we aren't planning on fixing anything for 2.1.
/cc @divega

**Comment by lajones** [comment]
`RequiredAttribute` is a `ValidationAttribute`. All `ValidationAttribute`s allow you to set `ErrorMessageResourceType` and `ErrorMessageResourceName` instead of `ErrorMessage`. Then it will expect to find a class of type `ErrorMessageResourceType` with a static property whose name is `ErrorMessageResourceName`. Hope that helps.

**Comment by ajcvickers** [comment]
@gabrielimmich Can you confirm whether or not the approach suggested by @lajones above is working for you?

**Comment by gabrielimmich** [comment]
Hi @ajcvickers and @lajones , thanks you for repply, temporarily resolved. I would like something more automatic, as in MVC 5 where I downloaded the package mVC pt.Br (https://www.nuget.org/packages/Microsoft.AspNet.Mvc.pt-br) from the nuget which translated all messages. But I understand that asp.net core is still in development and I'm sure that in the future this will be implemented.

Thank you for the answers and the attention.

**Comment by ajcvickers** [comment]
Closing this as we don't plan to implement and changes here. However, see #25128
