### ISSUE TITLE
Add a RegexExpression class and method-based regular expression

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/corefx#27840]
I made this proposal to C# repo.
https://github.com/dotnet/csharplang/issues/1364
It concerns a LinQ syntax for Regular expressions. Apparently it depends on a RegexExpression Class and some extension methods. 
RgxExpression calass should have some construcors to allow create an instance based on a regex string, or another RgxExpression instance or expression. This will help define repeated expression, and maje use ofregex language. RgxExpression.ToString() will return the regex string.
The RgxExpression can be like this:
```
class RgxExpression 
{
   public string Expression {get; set;}
      
}
```

The extenstion methods should be like this:

```
RgxExpression Foo (this RgxExpression exp)
{
  RgxExpression exp1 = ........;
    return Merge(exp.Expression, exp1);
}

```
This is how I represent email regex for example:
```
var smalls = Range("a", "z");
var caps = Range("A","Z")
var L = Any(smalls, cap, Digit, ".", "_", "-")
var W1 = L.Repeat(1);
var W2 = L.Repeat(2, 4);
var email = Boundary.W1.Constant("@").W1.Constant(".").W2.Boundary;
string rgx = email.ToString();

In the discussion it appears that there are some similar work like:
https://github.com/sprache/Sprache
https://github.com/VerbalExpressions/CSharpVerbalExpressions.
The problem is there are 100,000 NuGets and impossible to explore them all!
My question is: why don't you embrace this idea and add a method-based regular expression, to make it easy for programmers to understand and use?
Being a part of the language will make it popular than being an infamous NuGet. 
By the way: Fast growing NuGets should have an online magazine or something to let us know about. This is a huge fortune but not easy to dig out its treasures.

**Comment by ViktorHofer** [comment]
@MohammadHamdyGhanem thanks for thinking about how to improve the .NET and the Regex we all love. As @CyrusNajmabadi already pointed out, this feature doesn't belong into the language (csharplang) nor into the Linq implementation. You can easily write your own Linq Provider and distribute your desired APIs as a nuget package.

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
> How is thsi different from https://github.com/VerbalExpressions/CSharpVerbalExpressions ?

I looked at the source code, which is good but doesn't cover Full Regex features. This project has been forked 96 times! Is there any easy and quick way to know which of them is the most popular and recently updated?
https://github.com/VerbalExpressions/CSharpVerbalExpressions/network/members
This is one of the Nuget community problems that makes me prefere to add this as a basic standard feature in CoreFX.

**Comment by CyrusNajmabadi** [comment]
>  This project has been forked 96 times! 
That's a good thing :)  Roslyn has been forked over 2000 times! :)

> but doesn't cover Full Regex features.

What full regex features are missing?  Why not ask that project to add them, or just add them yourself?

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
I already sent an issue yesterday, and waiting for reply. For example, there are no LookAhead, LookArround, Atomic, nor regex conditions. Many important const Literals are not defined. 
Using this class as it is will need to add some regexes manually.

**Comment by CyrusNajmabadi** [comment]
> Using this class as it is will need to add some regexes manually.

Feel free to fork and add as necessary.  It's quite possible what you are asking for could also be provided through extensions.  This is a core point of open source.  :)

**Comment by MohammadHamdyGhanem** [comment]
I made many improvments to VerbalExpressions pjoject, and there is still more work to do. This is a sample code:
```
            var ValidFirstChar = Verex.New.EnglishAlphabetOrHyphen();
            var ValidChars = Verex.New.EnglishAlphabetOrHyphenOrDigit()
                         .AppentToRange(@".\-" );

            var email = Verex.New
                .WordEdge()
                .Add(ValidFirstChar)
                .Repeat(ValidChars, 0, 20)
                .Str("@")
                .Add(ValidFirstChar)
                .Repeat(ValidChars, 2, 14)
                .Str(".")
                .Add(ValidFirstChar)
                .Repeat(ValidChars, 1, 9)
                .WordEdge();

            Console.WriteLine(email.ToString());
```
The generated regex is:
> \b[_a-zA-Z]([_a-zA-Z0-9.\-]){0,20}@[_a-zA-Z]([_a-zA-Z0-9.\-]){2,14}.[_a-zA-Z]([_a-zA-Z0-9.\-]){1,9}\b

**Comment by MohammadHamdyGhanem** [comment]
It's possible to get rid of the extra () by this alternative code:
```
            var ValidFirstChar = Verex.New.EnglishAlphabetOrHyphen();
            var ValidChars = Verex.New.EnglishAlphabetOrHyphenOrDigit()
                         .AppendToRange(@".\-" );

            var email = Verex.New
                .WordEdge()
                .Add(ValidFirstChar)
                .Add(ValidChars).RepeatPrevious(0, 20)
                .Str("@")
                .Add(ValidFirstChar)
                .Add(ValidChars).RepeatPrevious(2, 14)
                .Str(".")
                .Add(ValidFirstChar)
                .Add(ValidChars).RepeatPrevious(1, 9)
                .WordEdge();

```
I implemented more than way to do the same thing, but there are slight differences. My notice about verbal expressions is they need some attention and a good understanding of regex. They easier or regex but not too much, but they make the code readable.

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi @ViktorHofer @karelz @radical @shanselman 
This Code:
```
var SequenceWithoutAngleBrakets = Verex.New.OutOfRange('<', '>').NoneOrMany();
var OpenAngle = Verex.New.CaptureGroup("Open", "<");
var CloseAngle = Verex.New.BalancingGroup("Close", "Open", ">");
var expr = Verex.New
    .StartOfLine
    .Next(SequenceWithoutAngleBrakets)
    .NoneOrMany(
         Verex.New
         .OnceAtleast(
             OpenAngle
             .Next(SequenceWithoutAngleBrakets)
          ).OnceAtleast(
             CloseAngle
             .Next(SequenceWithoutAngleBrakets)
       )
     )
     .IfThisIs("Open", Verex.New.IfNextIsNot(""))
     .EndOfLine;

```
generates this regex pattern:
`^[^<>]*(((?<Open><)[^<>]*)+((?<Close-Open>>)[^<>]*)+)*(?(<Open>)(?!))$`

Does Verex make it easer to understand what the the regex does?
Any notes or suggestions?

**Comment by MohammadHamdyGhanem** [comment]
@shanselman 
Here is Verex (my verbal regex builder):
https://github.com/MohammadHamdyGhanem/Verex
Thanks
