### ISSUE TITLE
ref read-write indexer for String class

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/corefx#27868]
String class is immutable. Any change to it creates a new instance. This maybe a waste of time in some situations where there is no change in the string length, like when you need to change only one char.
Since ref returns are available, I tried this:
```
string s = "test";
ref char c = ref s[0];
c = 'T';
```
But C# refused the second statement, with this error:
> "A property or indexer may not be passed as an out or ref parameter"

I tried to use Span< T > but String class has only "AsReadOnlySpan" method.
So, my proposal is:
Make the String.Chars Indexer property return the ref of the char, so that we can change it directly. And if possible, Make the Indexer read-write , so rhan one can write this directly:
```
string s = "test";
s[0] = 'T';

```
This will not break any existing code, and the string class still fixed length.

Note:
If you don't want to change the Indexer. then you could add a SetChar(index) Method to set one or char of the string.

**Comment by jkotas** [comment]
This proposal makes the string class mutable. String class is immutable and we want to keep it that way.

**Comment by MohammadHamdyGhanem** [comment]
Why?
I see that the problem is when changing the string size. What prevent you from changing only the chars?

**Comment by jkotas** [comment]
The .NET runtime and libraries depend on the strings being immutable. Allowing string mutation would be a very dangerous and unsafe operation.

If somebody wants to change the chars of the string and they know what they are doing it, there is unsafe code for that.

**Comment by MohammadHamdyGhanem** [comment]
@jkotas 
Is this related to the Intern Pool or The GC?.. Or there is another reason?
Could ypu give me a link that explans the reason for this design?

**Comment by jkotas** [comment]
Many people have written about this: https://www.bing.com/search?q=why+are+strings+immutable+in+c%23

**Comment by MohammadHamdyGhanem** [comment]
Thanks.
