### ISSUE TITLE
Use common class to set property default in winHttp & xplatHttp

### ISSUE THREAD

**Issue by rajansingh10** [dotnet/corefx#2787]
> stephentoub :: There are a bunch of these default values that are being copied from the WinHttp handler implementation. It's great that we're using the same defaults, but it's error prone that we're doing so via copy-and-paste. I see a whole bunch of constants/defaults in WinHttp at https://github.com/dotnet/corefx/blob/master/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs#L93-L146 .could we somehow factor out these constants/default values into a shared source file that's included in both the Windows and Unix implementation, such that this then becomes:
```C#
private int _maxAutomaticRedirections = HttpHandlerDefaults.MaxAutomaticRedirections;
```
instead of:
```C#
private int _maxAutomaticRedirections = 50;
```

> davidsh :: Yes, one could create a shared source file in src\Common\src\System\Net\Http... that defined an internal static class (HttpHandlerDefaults) with those constants defined as public fields. Then that file would be used in the multiple .CSPROJ files to bring in the values.

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar
