### ISSUE TITLE
System.Configuration.ConfigurationManager SettingElement Null Reference Exception

### ISSUE THREAD

**Issue by Jlalond** [dotnet/corefx#27875]
Related #27807 

While making the above tests, I discovered the default constructor for a SettingElement will throw a NRE if GetHashCode is called upon it.

Deemed as a bug, but what should it return? The same hashcode as a valid SettingElement? I don't have the background knowledge on what a 'proper' return value for this situation would be

**Comment by danmosemsft** [comment]
It should return a number, in this context basically any number, but that number must be the same for all objects for which Equals on the object returns true.

Eg., if I create 2 SettingElements X and Y with the default constructor, if X.Equals(Y) returns true, they must give the same hash code.
