### ISSUE TITLE
Change PipeScheduler.Schedule to be non generic

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#27887]
This is forcing kestrel to allocate per call to schedule where it didn't before. We don't need it to be generic since we're always passing an object as state in the fast path. We box today when there's a sync context or execution context.

/cc @pakrym @halter73

**Comment by pakrym** [comment]
But is it forcing anything? If we don't pass structs as T it would never allocate because the only allocation currently happening is boxing T to object.
