### ISSUE TITLE
Add gdb and lldb to test machine dockerfiles and enable dump collection

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#27909]
We want to run gdb and lldb on dumps created by tests. The experiments in https://github.com/dotnet/corefx/pull/27899#issuecomment-371901222 show that on some machiens (eg Fedora, OpenSuse) apparently dumps are not enabled. On others (eg some Ubuntu and Debian) dumps are enabled but gdb is not present. We also want lldb so we can do more operations on the dumps.

So we need to add install of gdb and lldb to all dockerfiles, and enable dumps with ulimit on all of them.

**Comment by danmosemsft** [comment]
@mattgal do you know who on our team worked on these in the past? Was it you @tarekgh ? Wondering who already knows how to modify these files/validate them.

**Comment by tarekgh** [comment]
I didn't do that before. 

CC @MichaelSimons just in case he may know.

**Comment by MichaelSimons** [comment]
I know what Docker images we use for official builds but have no knowledge in how the tests are run.  @MattGal would be the person to answer that.

**Comment by MattGal** [comment]
For official runs, we don't currently run tests inside Docker at all, although @joperezr  will be checking this out for Alpine.  If you want to add stuff to the official runs' machines, please create an issue in the core-eng repo and add the First Responders label.

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/core-eng #2880](https://github.com/dotnet/core-eng/issues/2880) via [**ZenHub**](https://www.zenhub.com/)
