### ISSUE TITLE
Disposing the SocketsHttpHandler does not abort draining sockets

### ISSUE THREAD

**Issue by Tratcher** [dotnet/corefx#27904]
Related to drain timeouts: https://github.com/dotnet/corefx/issues/27685. 

Version 2.1.0-preview2-26225-03.

Reference code: https://github.com/aspnet/HttpSysServer/blob/80345b7f8ffd7a2b623d2e449f6854e3037c1ccc/test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseBodyTests.cs#L602-L615

This code gets the response without buffering, disposes it which starts a background drain that blocks without timeout, and then the client/handler is disposed. The already draining socket is not closed when the handler is disposed, and without the proposed timeout in #27685 it may keep the socket alive indefinitely.

@stephentoub

**Comment by stephentoub** [comment]
> starts a background drain that blocks without timeout

There is a timeout on the drain.

**Comment by stephentoub** [comment]
> without the proposed timeout in #27685 it may keep the socket alive indefinitely

That drain timeout is already implemented. That issue is now about exposing the internal knob for controlling/changing the timeout value.

**Comment by Tratcher** [comment]
Ah, it wasn't implemented in 2.1.0-preview2-26225-03 but it is now in 2.1.0-preview2-26308-01.

**Comment by stephentoub** [comment]
Yup, it was done recently. It's probably still worth looking at trying to stop the drain sooner, but I don't think it's as big a deal, due to the timeout.

**Comment by stephentoub** [comment]
@Tratcher, response draining now defaults to a 2 second timeout, which is also configurable via SocketsHttpHandler.ResponseDrainTimeout.  Can this issue be closed?

**Comment by Tratcher** [comment]
Does Stream.Dispose, HttpContent.Dispose, or SocketHttpHandler.Dispose block for those 2 seconds or does the drain happen on a background thread?

**Comment by stephentoub** [comment]
> Does Stream.Dispose, HttpContent.Dispose, or SocketHttpHandler.Dispose block for those 2 seconds or does the drain happen on a background thread?

They do not block.  The drain happens asynchronously.
