### ISSUE TITLE
SocketsHttpHandler should process idle disconnect from server promptly

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#27908]
For idle connections, we have a _readAheadTask we use to determine if the server sent an EOF to close the connection (or other unexpected data).  We don't check this until we either pull the connection out of the pool, or timeout the connection.  So often there will be a large delay (10s of seconds) between when we receive the EOF and when we actually close the connection on our side.

RFC 7230 says the following: 

```
   To avoid the TCP reset problem, servers typically close a connection
   in stages.  First, the server performs a half-close by closing only
   the write side of the read/write connection.  The server then
   continues to read from the connection until it receives a
   corresponding close by the client, or until the server is reasonably
   certain that its own TCP stack has received the client's
   acknowledgement of the packet(s) containing the server's last
   response.  Finally, the server fully closes the connection.
```

https://tools.ietf.org/html/rfc7230#section-6.6

In the interest of being a well-behaved client and trying to make it easier for servers to adhere to the above behavior, we should close the connection promptly when we receive a disconnect from the server.

(I hit this originally because I was trying to implement the above logic in LoopbackServer for tests, but it cause large delays on a bunch of tests because the client didn't promptly close its connection.)

**Comment by stephentoub** [comment]
> we should close the connection promptly when we receive a disconnect from the server.

How promptly? An easy way to make it really more quickly is to just lower our scavenge time. Right now it's something like 30s; we could make it just a few seconds.

If you actually mean the moment we get the EOF, that's easy to do but will add measurable cost per request, at least a couple of allocations. How valuable is this?

**Comment by stephentoub** [comment]
Maybe it won't be terrible. I'll put up a PR and we can decide.

**Comment by karelz** [comment]
We are now at 3s timeout, which is not that bad. There is no super-simple way to fix it. Moving to Future.

**Comment by stephentoub** [comment]
I think we can close this.  If we find a real issue in the future, we can re-open.
