### ISSUE TITLE
HttpClient POST with content is broken on High-Sierra

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/corefx#27912]
If you make a POST request with content in the body on High-Sierra to a KestrelHttpServer endpoint the request will fail because the default HttpRequest version has changed to 2 and High-Sierra's libcurl handler will try to upgrade to 2 instead of falling back.

Run the client and server in the repro project to reproduce the issue
https://github.com/BrennanConroy/ReproProject

**Comment by BrennanConroy** [comment]
Request
```
POST /default?id=95d8312d-3354-4a5d-bf45-4c67a3316ad0 HTTP/1.1
Host: localhost:5000
Accept: */*
Connection: Upgrade, HTTP2-Settings
Upgrade: h2c
HTTP2-Settings: AAMAAABkAARAAAAAAAIAAAAA
User-Agent: Microsoft.AspNetCore.Sockets.Client.Http/1.0.0-preview2-t000
Content-Length: 20

{"protocol":"json"}.
```

Response
```
HTTP/1.1 400 Bad Request
Connection: close
Date: Fri, 09 Mar 2018 18:49:45 GMT
Server: Kestrel
Content-Length: 0
```

**Comment by BrennanConroy** [comment]
cc @karelz

**Comment by geoffkizer** [comment]
Why does Kestrel send 400 instead of just ignoring the upgrade request?

That said, I'm not sure we want to be sending the Upgrade in the first place.

**Comment by stephentoub** [comment]
> High-Sierra's libcurl handler will try to upgrade to 2 instead of falling back

We can suppress the version proactively for an http instead of https scheme, but isn't this actually a bug in ASP.NET, that it's not ignoring the upgrade request?  CurlHandler isn't the only code using libcurl.

**Comment by karelz** [comment]
@geoffkizer can you please help me understand why we shouldn't be sending the Upgrade request?

**Comment by Tratcher** [comment]
The non-ALPN upgrade approach isn't widely implemented and is more likely to confuse applications/servers. This is the only implementation I've seen yet and it's causing havoc with our tests.

**Comment by stephentoub** [comment]
> This is the only implementation I've seen yet and it's causing havoc with our tests.

Again, that sounds like an issue with ASP.NET that should be fixed.  This is libcurl's behavior with v2.0, CURL_HTTP_VERSION_2_0, and an http:// url; I highly doubt CurlHandler is the only client using that combination, especially since libcurl introduced CURL_HTTP_VERSION_2TLS much later than CURL_HTTP_VERSION_2_0.  Regardless, CurlHandler now uses CURL_HTTP_VERSION_2TLS.
