### ISSUE TITLE
Add test for logging for Exception passed to Environment.FailFast()

### ISSUE THREAD

**Issue by sywhang** [dotnet/corefx#27929]
https://github.com/dotnet/coreclr/pull/16622 added logging for Exception object passed to ```Environment.FailFast```. This should be test-protected, as per comments in https://github.com/dotnet/coreclr/issues/15203.

**Comment by joperezr** [comment]
@sywhang are you still planning to work on this? we only have 3 days to go to ZBB so if you don't plan to do this yet I believe we can push it to Future for now.

**Comment by sywhang** [comment]
I'm planning on adding more tests (or porting from Desktop) for this and some other changes I've made to the general ExceptionTracing but I don't know if I can get it in the next 3 days, so I moved it to future for now. Thanks for the reminder!
