### ISSUE TITLE
PipeCompletionCallbacks shouldn't use ArrayPool for callbacks

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#27938]
We should make a few optimizations here
- There's hardly more than one callback so we can use the track that tasks use for continuations (store it as an object and then detect the case where we have more than one and allocate an array).
- We don't need an the array pool here, we should just store state on the pipe itself and reset that state when Reset is called.

/cc @pakrym

**Comment by pakrym** [comment]
Agreed with first point. 
Second point is wrong though. What would happen in your case when you do the following with the `ThreadPoolScheduller`?
``` C#
for (int i=0 ; i< 100; i++)
{
reader.OnWriterCompleted((state, ex) => Console.WriteLine(i), i);
reader.Completed();
writer.Completed().
pipe.Reset();
}
```

if we store state on Pipe it'll get reset before scheduler would run callbacks.

**Comment by davidfowl** [comment]
Maybe it should block until the callbacks are fired like cancellation token 😄.

**Comment by pakrym** [comment]
Nope

**Comment by davidfowl** [comment]
Lets just do the first one.
