### ISSUE TITLE
Broken libcurl dependency on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#27936]
@bwalkenhorst commented on [Thu Mar 08 2018](https://github.com/dotnet/core/issues/1327)

# Broken libcurl dependency on openSUSE Tumbleweed

Trying to install dotnet core on openSUSE Tumbleweed, following the instructions found here, I get the following error message:
```
[20:06|root@schwarzgeraet:~]# zypper in dotnet-sdk-2.0.0
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides libcurl needed by dotnet-runtime-2.0.0-2.0.0-1.x86_64
 Solution 1: do not install dotnet-sdk-2.0.0-2.0.0-1.x86_64
 Solution 2: break dotnet-runtime-2.0.0-2.0.0-1.x86_64 by ignoring some of its dependencies
```

When I ask the package manager about it, I get the following reply:
```
[20:06|root@schwarzgeraet:~]# zypper se libcurl
Loading repository data...
Reading installed packages...

S  | Name                | Summary                                | Type   
---+---------------------+----------------------------------------+--------
   | libcurl-devel       | A Tool for Transferring Data from URLs | package
   | libcurl-devel-32bit | A Tool for Transferring Data from URLs | package
i+ | libcurl4            | Version 4 of cURL shared library       | package
i  | libcurl4-32bit      | Version 4 of cURL shared library       | package
```

So there is a libcurl, it is just called libcurl4. I am not certain who I should blame here. But I hope that updating the dependencies on dotnet will be less work than getting the openSUSE developers to rename the package.

---

@omajid commented on [Thu Mar 08 2018](https://github.com/dotnet/core/issues/1327#issuecomment-371599203)

Related to https://github.com/dotnet/core-setup/issues/3791

---

@bwalkenhorst commented on [Thu Mar 08 2018](https://github.com/dotnet/core/issues/1327#issuecomment-371609046)

FWIW: I tried `Solution 2: break dotnet-runtime-2.0.0-2.0.0-1.x86_64 by ignoring some of its dependencies`

I wasn't all that surprised, but it seems to have worked. MonoDevelop still isn't convinced .Net Core 2.0 is actually installed, but when I try to build and run a simple Hello-World project from the command line, it works

**Comment by karelz** [comment]
This is a tough one. AFAIK we do not have a way to change dependency name easily per platform (@janvorli @wfurt @stephentoub any ideas?).
One workaround is to rebuild libcurl yourself / rename its binaries.
Another option is to start relying on SocketsHttpHandler - our HTTP stack implementation in C# which does not require libcurl at all.

**Comment by stephentoub** [comment]
I'm not sure this has to do with the binaries; most of these libcurl4 packages include multiple symlinks.  It sounds like it's a package name issue.

**Comment by janvorli** [comment]
I agree that this is a package name issue. It looks like RPM now supports so called Boolean dependencies where it is possible to say "require package X or Y". That could solve the issue for us:
http://rpm.org/user_doc/boolean_dependencies.html

**Comment by omajid** [comment]
Can't we do what we just did for Ubuntu? https://github.com/dotnet/core-setup/pull/3804/files

**Comment by wfurt** [comment]
Can we figure out if there is still problem @MichaelSimons @leecow ?  This issue seems pretty old and Ubuntu18 was fixed. 
Perhaps this could be closed. Also since Tumbleweed is rolling version, I'm not sure if we can ever make this 100% reliable.

**Comment by MichaelSimons** [comment]
cc @dagood - dev owner of .NET Linux packages.

**Comment by dagood** [comment]
.NET Core doesn't support openSUSE Tumbleweed. (Recent issue about it: https://github.com/dotnet/core-setup/issues/5662.)

The libcurl dependency was removed before 2.1.0 by https://github.com/dotnet/core-setup/pull/3966, so this particular issue isn't a problem anymore.

(Interesting tip about `or` dependencies @janvorli, adding it to my toolbox. 😄)
