### ISSUE TITLE
System.Runtime.Caching using app/web.config problems

### ISSUE THREAD

**Issue by MichaCo** [dotnet/corefx#27933]
Hi,
I'm currently trying to port a few things to .netstandard2.0 using `System.Runtime.Caching` and I'm running into problems using the "old" configuration system.

To reproduce the problems, I created a blank new netcoreapp2.0 console app and added 

```
<PackageReference Include="System.Configuration.ConfigurationManager" Version="4.5.0-preview1-26216-02" />
<PackageReference Include="System.Runtime.Caching" Version="4.5.0-preview1-26216-02" />
```

I'm using 
```
dotnet --info
.NET-Befehlszeilentools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```
---

1. **Using app.config from [examples in documentation](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/system-runtime-caching-element-cache-settings#example)**

*Minor thing:*  According to the docs, the section has the attribute `physicalMemoryPercentage`, but it is now `physicalMemoryLimitPercentage`. Is this an error in the documentation or copy&paste issue? ;)

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <system.runtime.caching>
    <memoryCache>
      <namedCaches>
        <add name="default"
             cacheMemoryLimitMegabytes="69"
             physicalMemoryLimitPercentage="42"
             pollingInterval="00:10:00" />
      </namedCaches>
    </memoryCache>
  </system.runtime.caching>
</configuration>
```

Running 
```
static void Main(string[] args)
{
    var cache = MemoryCache.Default;
```

Will throw an exception
```
System.Configuration.ConfigurationErrorsException: 'Configuration system failed to initialize'
```

because the `system.runtime.caching` section is unknown.

2. **Manually adding the missing section group + section**
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <sectionGroup name="system.runtime.caching" type="System.Runtime.Caching.Configuration.CachingSectionGroup, System.Runtime.Caching">      
      <section name="memoryCache" type="System.Runtime.Caching.Configuration.MemoryCacheSection, System.Runtime.Caching" />
    </sectionGroup>
  </configSections>
  <system.runtime.caching>
    <memoryCache>
      <namedCaches>
        <add name="default"
             cacheMemoryLimitMegabytes="69"
             physicalMemoryLimitPercentage="42"
             pollingInterval="00:10:00" />
      </namedCaches>
    </memoryCache>
  </system.runtime.caching>
</configuration>
```

Now, the code works, **but** the settings for "default" are not used by `MemoryCache.Default`. Polling interval for example will be the default of 2 minutes.

---

Using a named cache and loading it via `var cache = new MemoryCache("notdefault");` actually works and uses the custom settings (only if you add the section group/section manually ofc).

Is this the intended behavior?

Thanks

**Comment by danmosemsft** [comment]
@kkhurin

**Comment by KKhurin** [comment]
Thanks for reporting this @MichaCo!
I'll take a look.

**Comment by KKhurin** [comment]
This came a bit as a surprise for me, but the cache names are case sensitive so you would need to use name="Default" for the default settings.

**Comment by MichaCo** [comment]
@KKhurin thanks! Stupid me, should have seen that one coming ;)

What about the configuration section though? 
Will it be required to add the configuration section and section group definition manually, like I explained above?
```
<configuration>
  <configSections>
    <sectionGroup name="system.runtime.caching" type="System.Runtime.Caching.Configuration.CachingSectionGroup, System.Runtime.Caching">      
      <section name="memoryCache" type="System.Runtime.Caching.Configuration.MemoryCacheSection, System.Runtime.Caching" />
    </sectionGroup>
  </configSections>
...
```

If that's the case, I'm totally fine with that, just wanted to point out that you'll get a hard error if you don't do it and that MemoryCache behaves different than using it against full framework.

**Comment by KKhurin** [comment]
@MichaCo yes, according to corefx manually adding the config section definition is the way to go for now.

Your question made me think that we should probably add some comments to the sources so whoever wants to use the old config has an easier time to discover how to do so.

**Comment by MichaCo** [comment]
@KKhurin makes sense, yup, all about documentation now. Thanks for the clarification!
