### ISSUE TITLE
Does ReadOnlySequence open write access to ReadOnlyMemory?

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/corefx#27947]
As I see when `ReadOnlySequence` created with `ReadOnlyMemory`, it extract internal object of `ReadOnlyMemory` (`array`, `string` or `OwnedMemory`) and give access to that object throw GetPosition method.

So `ReadOnlySequence` opens access to `array` or `OwnedMemory`. But `array` or `OwnedMemory` are not read only objects and they opens write access to `ReadOnlyMemory`.
So any code can get write access to `ReadOnlyMemory` (over `array` or `OwnedMemory`) in safe code by using `ReadOnlySequence`.

Am I right? And **is it correct API design?**

Also I does not understand benefits of using `ReadOnlySequence` that contains only one segment. If your use only one segment you can use `ReadOnlyMemory` or `string` or `OwnedMemory` directly.

So I think that all one segment optimizations are usefulness because they drawback performance for `ReadOnlySequence`  with few segments.

**Comment by benaadams** [comment]
`ReadOnlySequence` only gives you access to `ReadOnlyMemory`s.

You can get access to the underlying objects via the `System.Runtime.InteropServices.MemoryMarshal` class for interop situations; but shouldn't be doing that generally, which is why the apis are not on `ReadOnlySequence`.

> Also I does not understand benefits of using ReadOnlySequence that contains only one segment. If your use only one segment you can use ReadOnlyMemory or string or OwnedMemory directly.

If you always have one segment; yes then you would likely use whatever it is directly; or provide an overload that directly takes `ReadOnlyMemory`. However if you can have 1+ `ReadOnlyMemory` then this is what `ReadOnlySequence` is for. e.g. non-contiguous memory or memory that is larger than 2GB

**Comment by AlexRadch** [comment]
> ReadOnlySequence only gives you access to ReadOnlyMemorys.

Is next access to array?
```
        [Fact]
        public void AcessToArray()
        {
            var array = new[] {1, 2, 3};
            var buffer = new ReadOnlySequence<int>(array);
            Assert.Equal(array.GetType().Name, buffer.Start.GetObject().GetType().Name);

            ((int[])buffer.Start.GetObject())[1] = 4;
            Assert.Equal(4, array[1]);
        }
```

**Comment by benaadams** [comment]
`SequencePosition` shouldn't be consumed is this fashion

/cc @pakrym

**Comment by AlexRadch** [comment]
@benaadams If I create `ReadOnlySequence` for array `new ReadOnlySequence<int>(array);` I can not get access to ReadOnlyMemory.  Only to array! 
My question is **is it correct API design?**

**Comment by AlexRadch** [comment]
@benaadams for example by using `ReadOnlyMemory` I can get write access to `ReadOnlyMemory` in safe code:
```cs
procedure Foo<T>(ReadOnlyMemory<T> rom)
{
  var object = new ReadOnlySequence<int>(rom).Start.GetObject();
  if (object is T[] array)
  {
    array[0] = default
  }
  else if (object is OwnedMemory<T> ownMem}
  {
    ownMem[0] = default
  }
  else if (object is string)
  {
     // can not change
  }
}
```

**Comment by benaadams** [comment]
>  If I create ReadOnlySequence for array new ReadOnlySequence<int>(array); I can not get access to ReadOnlyMemory. Only to array!

```csharp
public void Foo<T>(ReadOnlySequence<T> buffers)
{
    if (buffers.IsSingleSegment)
    {
        DoAction(buffers.First); // ReadOnlyMemory First
    }
    else
    {
        foreach (var readOnlyMemory in buffers)
        {
            DoAction(readOnlyMemory);
        }
    }
}

public void DoAction<T>(ReadOnlyMemory<T> readOnlyMemory)
{

}
```

**Comment by benaadams** [comment]
You shouldn't need to extract anything directly from `SequencePosition`. 

The `ReadOnlySequence<T>` api is
```csharp
public SequencePosition End { get; }
public ReadOnlyMemory<T> First { get; }
public long Length { get; }
public bool IsSingleSegment { get; }
public bool IsEmpty { get; }
public SequencePosition Start { get; }

public Enumerator GetEnumerator();
public SequencePosition GetPosition(long offset);
public SequencePosition GetPosition(long offset, SequencePosition origin);
public ReadOnlySequence<T> Slice(SequencePosition start, SequencePosition end);
public ReadOnlySequence<T> Slice(long start, long length);
public ReadOnlySequence<T> Slice(SequencePosition start, int length);
public ReadOnlySequence<T> Slice(SequencePosition start);
public ReadOnlySequence<T> Slice(long start, SequencePosition end);
public ReadOnlySequence<T> Slice(long start);
public ReadOnlySequence<T> Slice(int start, SequencePosition end);
public ReadOnlySequence<T> Slice(int start, int length);
public ReadOnlySequence<T> Slice(SequencePosition start, long length);
public override string ToString();
public bool TryGet(ref SequencePosition position, out ReadOnlyMemory<T> data, bool advance = true);

```

**Comment by benaadams** [comment]
The `ReadOnlySequence` extensions might be a good place to see example uses?
https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/Buffers/BuffersExtensions.cs

**Comment by AlexRadch** [comment]
@benaadams nice API. For example, I want access item at some `offset`.
I get position for that offset `var position = seq.GetPosition(offset);` and now how to get item if I can not use `position.GetObject()`?

Why I should use next low performance code?
```
TryGet(position, out data, false); // low performance !!!
var item = data[position.GetItem]`;
```

**Comment by pakrym** [comment]
Any code you write that uses SequencePostion to access separate items would be slow, that's why we are not providing any default way of doing. Performance critical code, which accessing items is, should be done based on `Memory<T>` or  with something like https://github.com/aspnet/Common/blob/dev/shared/Microsoft.Extensions.Buffers.Sources/BufferReader.cs

**Comment by AlexRadch** [comment]
What is reason of `SequencePosition` struct with public properties `Integer` and `Object` ? May be better to have different `SequencePosition` struct for each `Sequence`? It will allow to hide `SequencePosition` internal properties. For example `ReadOnlySequence` will define `ReadOnlySequencePosition` and so on.

**Comment by davidfowl** [comment]
> What is reason of SequencePosition struct with public properties Integer and Object 

Because there's a hope that we can use it as a general representation of a position in another abstraction that hasn't made its way to corefx as yet https://github.com/dotnet/corefxlab/blob/cf025e0c6521ee7936ef13c83f2bc0b643fe4b7e/src/System.Buffers.Primitives/System/Collections/ISequence.cs. 

> May be better to have different SequencePosition struct for each Sequence?

Yes, this is true but we have hopes that this can be more general purpose. The tradeoff is the lack of type safety.

**Comment by AlexRadch** [comment]
> Yes, this is true but we have hopes that this can be more general purpose. The tradeoff is the lack of type safety.

I ask this because I don't see where Position struct can be general used. For example, I don't see that some class or method will store or work with positions from different sequences in general, without casting to special sequence.

Also for some new sequence it can be not enough Position struct with only two properties  (Integer and Object).

Some questionable compromises for me.

Thanks for answers!

**Comment by AlexRadch** [comment]
@davidfowl Where `SequencePosition` defined in corefxlab? I did not find it https://github.com/dotnet/corefxlab/search?utf8=%E2%9C%93&q=%22struct+SequencePosition%22&type=

**Comment by davidfowl** [comment]
It's not defined there, it's in corefx. It's used in corefxlab.

https://github.com/dotnet/corefxlab/blob/22c2d4edc6fc16ed50489f6709ee54ab8aede113/tests/System.Collections.Sequences.Tests/SampleCollections/Hashtable.cs

https://github.com/dotnet/corefxlab/blob/22c2d4edc6fc16ed50489f6709ee54ab8aede113/src/System.Collections.Sequences/System/Collections/Sequences/ArrayList.cs
