### ISSUE TITLE
String dictionary usage of NonRandomizedStringEqualityComparer

### ISSUE THREAD

**Issue by roji** [dotnet/corefx#27946]
*EDIT: Please read my first comment below with additional information.*

When doing some benchmarking I came across Dictionary's behavior of using NonRandomizedStringEqualityComparer when no comparer is given.

The documentation on [NonRandomizedStringEqualityComparer](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Collections/Generic/NonRandomizedStringEqualityComparer.cs#L9) says that:

> NonRandomizedStringEqualityComparer is the comparer used by default with the Dictionary<string,...> We use NonRandomizedStringEqualityComparer as default comparer as it doesnt use the randomized string hashing which keeps the performance not affected till we hit collision threshold and then we switch to the comparer which is using randomized string hashing.

However, its `GetHashCode()` calls [GetLegacyNonRandomizedHashCode()](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/String.Comparison.cs#L1022), whose documentation says:
> Use this if and only if you need the hashcode to not change across app domains (e.g. you have an app domain agile hash table).

I don't know anything about Dictionary internals - I can see that NonRandomizedStringEqualityComparer internally gets swapped for the default comparer after a certain collision threshold has been reached. I whipped up some simple (non-exhaustive) benchmarks that seem to show that the default dictionary doesn't perform as much as it could. [The benchmark](https://github.com/roji/DictionaryBenchmarks) populates a dictionary with a variable number of random 5-letter strings and then measures lookup times

``` ini

BenchmarkDotNet=v0.10.13, OS=ubuntu 17.10
Intel Core i7-6700HQ CPU 2.60GHz (Skylake), 1 CPU, 8 logical cores and 4 physical cores
.NET Core SDK=2.1.4
  [Host]     : .NET Core 2.0.5 (CoreCLR 4.6.0.0, CoreFX 4.6.26018.01), 64bit RyuJIT
  DefaultJob : .NET Core 2.0.5 (CoreCLR 4.6.0.0, CoreFX 4.6.26018.01), 64bit RyuJIT


```
|       Method | NumEntries |     Mean |     Error |    StdDev | Scaled | ScaledSD |
|------------- |----------- |---------:|----------:|----------:|-------:|---------:|
|      **Default** |         **10** | **19.87 ns** | **0.1082 ns** | **0.0904 ns** |   **1.00** |     **0.00** |
| WithComparer |         10 | 18.08 ns | 0.1360 ns | 0.1272 ns |   0.91 |     0.01 |
|              |            |          |           |           |        |          |
|      **Default** |        **100** | **19.74 ns** | **0.0754 ns** | **0.0629 ns** |   **1.00** |     **0.00** |
| WithComparer |        100 | 17.34 ns | 0.3423 ns | 0.5994 ns |   0.88 |     0.03 |
|              |            |          |           |           |        |          |
|      **Default** |       **1000** | **22.97 ns** | **0.1730 ns** | **0.1618 ns** |   **1.00** |     **0.00** |
| WithComparer |       1000 | 17.68 ns | 0.3975 ns | 0.6304 ns |   0.77 |     0.03 |
|              |            |          |           |           |        |          |
|      **Default** |      **10000** | **21.95 ns** | **0.2655 ns** | **0.2354 ns** |   **1.00** |     **0.00** |
| WithComparer |      10000 | 21.48 ns | 0.3271 ns | 0.3060 ns |   0.98 |     0.02 |
|              |            |          |           |           |        |          |
|      **Default** |     **100000** | **21.98 ns** | **0.3697 ns** | **0.3278 ns** |   **1.00** |     **0.00** |
| WithComparer |     100000 | 17.62 ns | 0.3375 ns | 0.3752 ns |   0.80 |     0.02 |

My comparer looks like this:
```c#
sealed class MyStringComparer : IEqualityComparer<string>
{
    internal static readonly MyStringComparer Instance = new MyStringComparer();

    public bool Equals(string x, string y) => string.Equals(x, y);
    public int GetHashCode(string obj) => RuntimeHelpers.GetHashCode(obj);
}
```

Is there some scenario where NonRandomizedStringEqualityComparer is supposed to help performance? Have I simply not reached the collision threshold? Is it there only for app domains (in which case it doesn't make much sense for .NET Core), or for backwards-compatibility for serialized blobs?

**Comment by roji** [comment]
After reading about `RuntimeHelpers.GetHashCode()`, I realized it generates the hash code from the reference. So I added two more benchmarks, one with `EqualityComparer<string>.Default` and one with an equality comparer that simply calls `string.GetHashCode()`, here are the results:

``` ini

BenchmarkDotNet=v0.10.13, OS=ubuntu 17.10
Intel Core i7-6700HQ CPU 2.60GHz (Skylake), 1 CPU, 8 logical cores and 4 physical cores
.NET Core SDK=2.1.4
  [Host]     : .NET Core 2.0.5 (CoreCLR 4.6.0.0, CoreFX 4.6.26018.01), 64bit RyuJIT
  DefaultJob : .NET Core 2.0.5 (CoreCLR 4.6.0.0, CoreFX 4.6.26018.01), 64bit RyuJIT


```
|                     Method | NumEntries |     Mean |     Error |    StdDev | Scaled | ScaledSD |
|--------------------------- |----------- |---------:|----------:|----------:|-------:|---------:|
|                    **Default** |         **10** | **22.08 ns** | **0.4252 ns** | **0.4897 ns** |   **1.00** |     **0.00** |
|        WithDefaultComparer |         10 | 20.99 ns | 0.4128 ns | 0.4417 ns |   0.95 |     0.03 |
| WithComparerRuntimeHelpers |         10 | 17.55 ns | 0.3318 ns | 0.2771 ns |   0.80 |     0.02 |
|    WithComparerGetHashCode |         10 | 31.16 ns | 0.6343 ns | 1.4318 ns |   1.41 |     0.07 |
|                            |            |          |           |           |        |          |
|                    **Default** |        **100** | **22.15 ns** | **0.2225 ns** | **0.2081 ns** |   **1.00** |     **0.00** |
|        WithDefaultComparer |        100 | 23.02 ns | 0.1658 ns | 0.1199 ns |   1.04 |     0.01 |
| WithComparerRuntimeHelpers |        100 | 17.49 ns | 0.2408 ns | 0.2252 ns |   0.79 |     0.01 |
|    WithComparerGetHashCode |        100 | 29.97 ns | 0.1486 ns | 0.1318 ns |   1.35 |     0.01 |
|                            |            |          |           |           |        |          |
|                    **Default** |       **1000** | **22.16 ns** | **0.1347 ns** | **0.1260 ns** |   **1.00** |     **0.00** |
|        WithDefaultComparer |       1000 | 22.07 ns | 0.0891 ns | 0.0789 ns |   1.00 |     0.01 |
| WithComparerRuntimeHelpers |       1000 | 18.54 ns | 0.2541 ns | 0.2377 ns |   0.84 |     0.01 |
|    WithComparerGetHashCode |       1000 | 31.49 ns | 0.3232 ns | 0.3023 ns |   1.42 |     0.02 |
|                            |            |          |           |           |        |          |
|                    **Default** |      **10000** | **22.38 ns** | **0.4358 ns** | **0.4076 ns** |   **1.00** |     **0.00** |
|        WithDefaultComparer |      10000 | 22.44 ns | 0.4345 ns | 0.4649 ns |   1.00 |     0.03 |
| WithComparerRuntimeHelpers |      10000 | 19.94 ns | 0.1165 ns | 0.1090 ns |   0.89 |     0.02 |
|    WithComparerGetHashCode |      10000 | 29.38 ns | 0.1655 ns | 0.1548 ns |   1.31 |     0.02 |
|                            |            |          |           |           |        |          |
|                    **Default** |     **100000** | **22.18 ns** | **0.1835 ns** | **0.1716 ns** |   **1.00** |     **0.00** |
|        WithDefaultComparer |     100000 | 22.17 ns | 0.1756 ns | 0.1643 ns |   1.00 |     0.01 |
| WithComparerRuntimeHelpers |     100000 | 17.26 ns | 0.2187 ns | 0.2046 ns |   0.78 |     0.01 |
|    WithComparerGetHashCode |     100000 | 29.99 ns | 0.1852 ns | 0.1733 ns |   1.35 |     0.01 |

So I guess my questions are:
* The NonRandomizedStringEqualityComparer used in the default scenario doesn't seem to have any significant impact either way - I'm still trying to understand what exactly it brings to the table.
* `RuntimeHelpers.GetHashCode()` seems to always out-perform the other options, I'm guessing this has something to do with my specific scenarios, and that the default comparer would work better in others? Is this something worth actually looking into?
* It's odd for `string.GetHashCode()` to perform that badly.

**Comment by benaadams** [comment]
`string.GetHashCode` is the randomised hashing

`NonRandomizedStringEqualityComparer` is there to not use the randomised hashing for a perf improvement until; it needs to switch to using `string.GetHashCode` due to collisions.

`RuntimeHelpers.GetHashCode` is getting the object's hash; whereas with string it needs the value's hash. (e.g. two string objects `Hello` and `Hello` should return the same hash; but they would return different hashes with this method as they are different objects)

**Comment by benaadams** [comment]
`EqualityComparer<string>.Default` is switched to be `NonRandomizedStringEqualityComparer` for string in the Dictionary constructor; which is why they seem the same.

`EqualityComparer<string>.Default` actually uses `string.GetHashCode` so you would see a pref hit if this switch wasn't made.

**Comment by roji** [comment]
Thanks for the answers @benaadams. 

Makes sense for the `RuntimeHelpers.GetHashCode()`, thanks for clarifying. I couldn't see any advantage in the default behavior (which starts with NonRandomized and switches to GetHashCode), but I'm guessing that's because my benchmark doesn't produce the right scenario (would be interesting to know).

Here's the one last thing I still don't understand... When I set `EqualityComparer<string>.Default`, I get much better performance than when I write my own `IEqualityComparer<string>` which calls `string.GetHashCode()` (the comparer is called StringComparerWithGetHashCode in my benchmark). Following `EqualityComparer<string>.Default`'s code, it seems to be calling into native code (via [here](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/ComparerHelpers.cs#L1210)), I'm assuming it goes into `string.GetHashCode()` natively, and that's the reason for the perf discrepancy? I'm writing because people are people calling `string.GetHashCode()` from their own comparers (or hash code generators) and this may be of interest.

My benchmark code is [here](https://github.com/roji/DictionaryBenchmarks) in case there's a problem coming from there.

**Comment by benaadams** [comment]
`EqualityComparer<T>.Default` devritualizes https://github.com/dotnet/coreclr/pull/14125; whereas a different `IEqualityComparer` would be an interface call

**Comment by roji** [comment]
Thanks!
