### ISSUE TITLE
Mutating a read-only struct passed by-ref with S.R.CS.Unsafe

### ISSUE THREAD

**Issue by ektrah** [dotnet/corefx#27962]
The value of the System.Runtime.CompilerServices.Unsafe class is in that it can do safe things that the compiler however cannot verify. For using Unsafe methods safely, it is essential that their semantics are fully understood. Currently, the methods are a bit under-documented.

One thing that seems apparently possible is mutating an instance of a read-only struct if that instance is passed by mutable reference:

```csharp
public readonly struct Point
{
    private readonly int x;
    private readonly int y;

    public static void Move(ref Point point, int dx, int dy)
    {
        Unsafe.AsRef(in point.x) += dx;
        Unsafe.AsRef(in point.y) += dy;
    }
}
```

On a scale from 1 to 10, how evil is that?

**Comment by omariom** [comment]
With Unsafe you can easily get AccessViolationException (if you are lucky) or silently corrupt Windows heap.
It is no different from unsafe blocks and pointer arithmetic.
The benefit is that you don't have to pin memory. But the responsibility is the same.

**Comment by ektrah** [comment]
I am aware that you can use Unsafe in a way that results in a AccessViolationException (or worse). But not *every* use of Unsafe results in a AccessViolationException; otherwise, there would be no point in having that class.

So my question is: What are the conditions under which Unsafe does not result in a AccessViolationException? And, specifically, is it safe to assume that the above code will not result in an AccessViolationException or silently corrupt the heap?

**Comment by Tornhoof** [comment]
Apparently not that evil, as @stephentoub is considering that for (de)serialization of https://github.com/dotnet/corefx/issues/24900#issuecomment-341148626. Maybe he can explain those 'tweaks'.

**Comment by stephentoub** [comment]
> Apparently not that evil, as @stephentoub is considering that for (de)serialization of DateTimeOffset #24900 (comment). Maybe he can explain those 'tweaks'.

I don't understand the comment. a) That change to nullable was reverted, and b) Unsafe isn't used there.  To what are you referring?

**Comment by omariom** [comment]
> And, specifically, is it safe to assume that the above code will not result in an AccessViolationException? 

`ref Point point` can point to anywhere. Like to a page mapped with PAGE_READONLY protection.

**Comment by ektrah** [comment]
@omariom I am aware that you can use Unsafe to forge a `ref` that leads to an AccessViolationException, but, per the C# language specification, a `ref` parameter is ***mutable***.

**Comment by jkotas** [comment]
> On a scale from 1 to 10, how evil is that?

For a public general purpose Point class, this would unacceptable (ie 10).

Casting away readonliness using `S.R.CS.Unsafe` and mutating readonly value is acceptable only if you have a full control over all inputs and you know for sure that the value is actually mutable.

**Comment by jkotas** [comment]
If you are asking about whether it is ok to cast away readonliness as a performance optimization  - where the code is 100% equivalent to a safe code that does not cast away readonliness - I think that is ok.

**Comment by ektrah** [comment]
@jkotas Thanks for shedding some light.

The Point struct is entirely under my control, but the code using it may not.

Do I really need to know more than that the parameter is declared as `ref` to mutate its contents?

*Edit:*  
I'm essentially asking if the optimized Move method in my post at the top is 100% equivalent to the safe code in my last comment above.

**Comment by omariom** [comment]
> I'm essentially asking if the optimized Move method in my post at the top is 100% equivalent to the safe code in my last comment above.

Ah.. Then it was me :)

With unsafe blocks, Unsafe class and Reflection you can easily break invariants of a type. So in your case it is about type safety.

**Comment by jkotas** [comment]
> I'm essentially asking if the optimized Move method in my post at the top is 100% equivalent to the safe code in my last comment above.

Yes, it is.

**Comment by ektrah** [comment]
> Yes, it is.

Thank you!

@omariom Sorry for causing confusion.
