### ISSUE TITLE
MatchingRefApiCompat issues in System.IO.*

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#27978]
See baseline file
https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/MatchingRefApiCompatBaseline.txt and
https://github.com/dotnet/corefx/blob/master/src/System.IO.IsolatedStorage/src/MatchingRefApiCompatBaseline.txt

We should do one of the following:
1. Expose the APIs publicly in the reference assembly
2. Make the APIs in the implementation internal
3. Add a comment to the baseline file why you cannot do either (1) or (2) and keep them baselined.

See PR https://github.com/dotnet/corefx/pull/27881/ for extra context.

**Comment by kirsty14141** [comment]
[Image]
Get Outlook for iOS<https://aka.ms/o0ukef>
_____________________________

**Comment by danmosemsft** [comment]
@Anipik each of these describe a mismatch between implementation ("contract" in the text in this case) and contract ("implementatoin" in the text..it's confusing). Talk to Jeremy to ask how to resolve it.

**Comment by JeremyKuhne** [comment]
System.IO.FileSystem:

```
Compat issues with assembly System.IO.FileSystem:
// These are now virtual in the implementation, which should be ok
CannotMakeMemberAbstract : Member 'System.IO.FileSystemInfo.Exists' is abstract in the implementation but is not abstract in the contract.
CannotMakeMemberAbstract : Member 'System.IO.FileSystemInfo.Name' is abstract in the implementation but is not abstract in the contract.
CannotMakeMemberAbstract : Member 'System.IO.FileSystemInfo.Exists.get()' is abstract in the implementation but is not abstract in the contract.
CannotMakeMemberAbstract : Member 'System.IO.FileSystemInfo.Name.get()' is abstract in the implementation but is not abstract in the contract.

// Not sure why this one is coming up, it is being generated by C# for the Unix version
TypesMustExist : Type 'System.IO.Enumeration.FileSystemEntry.<_fileNameBuffer>e__FixedBuffer' does not exist in the implementation but it does exist in the contract.

// Should be made private (in both WinRT/Win32)
MembersMustExist : Member 'System.IO.Enumeration.FileSystemEnumerator<TResult>.GetData()' does not exist in the implementation but it does exist in the contract.
```

**Comment by JeremyKuhne** [comment]
System.IO.IsolatedStorage:

```
Compat issues with assembly System.IO.IsolatedStorage:

// Getter should be private or internal
MembersMustExist : Member 'System.IO.IsolatedStorage.IsolatedStorage.IdentityHash.get()' does not exist in the implementation but it does exist in the contract.
// Setter should be private or internal
MembersMustExist : Member 'System.IO.IsolatedStorage.IsolatedStorage.Scope.set(System.IO.IsolatedStorage.IsolatedStorageScope)' does not exist in the implementation but it does exist in the contract.
Total Issues: 2
```

**Comment by weshaggard** [comment]
```
// Not sure why this one is coming up, it is being generated by C# for the Unix version
TypesMustExist : Type 'System.IO.Enumeration.FileSystemEntry.<_fileNameBuffer>e__FixedBuffer' does not exist in the implementation but it does exist in the contract.
```

That one is definitely weird I wonder `fixed` makes the field public. 

For comments in these baseline files use `#` instead of `//`.

**Comment by Anipik** [comment]
@JeremyKuhne should I add your comments to the MatchingRefApiCompatBaseline.txt file for both the projects ?

**Comment by JeremyKuhne** [comment]
> should I add your comments to the MatchingRefApiCompatBaseline.txt file for both the projects ?

Only for the APIs we aren't changing. If you change the APIs the entries should go away. (IsolatedStorage file should go away completely)
