### ISSUE TITLE
MatchingRefApiCompat issues with Microsoft.VisualBasic.

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#27972]
See baseline file
https://github.com/dotnet/corefx/blob/master/src/Microsoft.VisualBasic/src/MatchingRefApiCompatBaseline.netstandard.txt.

We should do one of the following:
1. Expose the APIs publicly in the reference assembly
2. Make the APIs in the implementation internal
3. Add a comment to the baseline file why you cannot do either (1) or (2) and keep them baselined.

See PR https://github.com/dotnet/corefx/pull/27881/ for extra context.

**Comment by OmarTawfik** [comment]
@weshaggard what is the timeline for this work?

**Comment by weshaggard** [comment]
Assuming the reference assembly is correct then this work can be done post-2.1.
