### ISSUE TITLE
MatchingRefApiCompat issues with System.Configuration.ConfigurationManager

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#27973]
See baseline file
https://github.com/dotnet/corefx/blob/master/src/System.Configuration.ConfigurationManager/src/MatchingRefApiCompatBaseline.netstandard.txt

We should do one of the following:
1. Expose the APIs publicly in the reference assembly
2. Make the APIs in the implementation internal
3. Add a comment to the baseline file why you cannot do either (1) or (2) and keep them baselined.

See PR https://github.com/dotnet/corefx/pull/27881/ for extra context.

**Comment by danmosemsft** [comment]
For these
```
MembersMustExist : Member 'System.Configuration.SettingsAttributeDictionary..ctor(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Configuration.SettingsContext..ctor(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)' does not exist in the implementation but it does exist in the contract.
```

Both derive from Dictionary which implements ISerializable so I guess we can remove the implementation from these types (which we haven't marked [Serializable]) -- @ViktorHofer can you confirm?

**Comment by danmosemsft** [comment]
?All the others seem to not be public/proteted in .NET Framework therefore our implementation should make them internal/private (or remove if dead code)
