### ISSUE TITLE
MatchingRefApiCompat issues in System.Runtime.Caching

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#27980]
See baseline file
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Caching/src/MatchingRefApiCompatBaseline.txt

We should do one of the following:
1. Expose the APIs publicly in the reference assembly
2. Make the APIs in the implementation internal
3. Add a comment to the baseline file why you cannot do either (1) or (2) and keep them baselined.

See PR https://github.com/dotnet/corefx/pull/27881/ for extra context.

**Comment by weshaggard** [comment]
weshaggard 5 days ago  Member
@KKhurin can you confirm whether or not these APIs should be in the reference assembly or whether or not they should be removed from the implementation?

  @KKhurin
KKhurin 5 days ago  Member
Those are the types used for the config, but they are not supposed to be used by the end user. Therefore I removed them from the ref assembly.
@JeremyKuhne, @danmosemsft, do you guys see any useful case when they would be needed in the ref assembly? How do other libraries who rely on config handle this?

   @weshaggard
weshaggard 5 days ago  Member
Are we actually depending on the configuration system? If not I would just remove these types if possible, otherwise we consider making them internal in the implementation or exposing them publicly in the reference assembly.

  @KKhurin
KKhurin an hour ago  Member
Yes, we still support configuring cache via config files.
Don't we need to keep them public in the implementation assembly for the config to work properly?

**Comment by weshaggard** [comment]
@KKhurin lets continue the conversation over here. 

>Don't we need to keep them public in the implementation assembly for the config to work properly?

I'm not sure. In .NET Core we don't have support for the full configuration system that .NET Framework does so I'm unsure how this configuration actually works.

**Comment by KKhurin** [comment]
@weshaggard if there is something to change here we better do it before 2.1, right? Let me quickly try to see if the config will still work with these types being internal.

**Comment by weshaggard** [comment]
Yes it would be a good idea to make sure this is correct before we ship it stable in 2.1. I've not personally looked deeply at the library so I'm not sure what is necessary or not, but in general unless there is a reason we shouldn't have extra public APIs in the implementation that aren't in the ref.

**Comment by danmosemsft** [comment]
@KKhurin are you on track to complete this before 3/30 zbb target?

**Comment by KKhurin** [comment]
Fixed with https://github.com/dotnet/corefx/pull/28636

**Comment by weshaggard** [comment]
@KKhurin I didn't see you update the baseline file in that PR please remove the entries in that baseline.

**Comment by KKhurin** [comment]
https://github.com/dotnet/corefx/pull/28665
