### ISSUE TITLE
Console.CursorLeft and CursorTop always returns 0 when used in Shell-in-a-box

### ISSUE THREAD

**Issue by SteveL-MSFT** [dotnet/corefx#27990]
[ShellInABox](https://github.com/shellinabox/shellinabox) enables a shell within a browser.  Currently [PowerShell Core 6](https://github.com/powershell/powershell) has an experience problem within ShellInABox because Console.CursorLeft and Console.CursorTop always returns 0.

Repro:

```bash
# using Ubuntu 16.04
sudo apt install shellinabox
xdg-open https://localhost:4200
# Should open browser to a shell window
dotnet new console -n test
```

replace program.cs with this:

```csharp
using System;

namespace contest
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.Clear();
            Console.Write("Hello World!");
            Console.Write("[left:{0}]", Console.CursorLeft);
            Console.WriteLine("Bye!");
            Console.Write("[Top:{0}]", Console.CursorTop);
            Console.SetCursorPosition(20,5);
            Console.Write("[20,5]");
        }
    }
}
```

```bash
dotnet publish
dotnet run
```

Expected:
```none
Hello World![left:12]Bye!
[Top:1]
```

Actual:
```none
Hello World![left:0]Bye!
[Top:0]
```

Blocking https://github.com/PowerShell/PowerShell/issues/3849

**Comment by danmosemsft** [comment]
@SteveL-MSFT is it possible for you to debug a little? 
https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System/ConsolePal.Unix.cs#L326

**Comment by danmosemsft** [comment]
What happens if you do this in the terminal?
```
echo -en "\e[6n"
read -sdR CURPOS
CURPOS=${CURPOS#*[}
```

On my Ubuntu box, I get a string like "49;1". 

I see in the code we have this assert:
```c#
                Debug.WriteLineIf(db.GetString(TermInfo.WellKnownStrings.CursorPositionReport) != CursorPositionReport,
                    "Getting the cursor position will only work if the terminal supports the CPR sequence," +
                    "but the terminfo database does not contain an entry for it.");
```

Can you also try this?
```
infocmp | grep -i e\\[6n
```
On my Ubuntu machine, I get `u7=\E[6n` indicating it supports cursor position request.

**Comment by danmosemsft** [comment]
It looks like it attempts to support `6n` so it would probably need debugging to figure out why it wasn't working for us:

https://github.com/shellinabox/shellinabox/blob/e6c25e84bc662797c7382500f136bb74874c2500/shellinabox/vt100.jspp#L4183

**Comment by SteveL-MSFT** [comment]
@danmosemsft I'll see if I can determine where exactly it's failing

**Comment by danmosemsft** [comment]
I'd use browser tools and put a javascript breakpoint in VT100.prototype.cursorReport to start. Thanks @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
@danmosemsft debugging the javascript, it's definitely sending the cursor position in the correct format.  Need to debug the corefx code now.

**Comment by SteveL-MSFT** [comment]
The ReadStdin() call after WriteStdoutAnsiString(TerminalFormatStrings.CursorPositionReport) fails to read any bytes so it returns with default value of 0.  Not sure yet why it's failing.

**Comment by SteveL-MSFT** [comment]
Based on my investigation, it appears to be an issue with ShellInABox https://github.com/shellinabox/shellinabox/issues/428

**Comment by danmosemsft** [comment]
Thanks for helping figure that out, @SteveL-MSFT .

**Comment by danmosemsft** [comment]
That ShellInABox repo looks semi-inactive so it may be that whoever wants this to work will have to have a shot themselves (if they accept PR's)

**Comment by SteveL-MSFT** [comment]
@danmosemsft I agree.  Tried to spend some time understanding their code, but have other urgent items to work on.  Maybe I'll revisit this in the future if someone else doesn't fix it.  Appreciate your pointers.
