### ISSUE TITLE
SendAsync_SlowGetRequestWithTimedCancellation test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#2799]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug/999/console

20:01:52   Discovering: System.Net.Http.Unit.Tests
20:01:53      System.Net.Http.WinHttpHandlerUnitTests.WinHttpHandlerTests.SendAsync_SlowGetRequestWithTimedCancellation_ExpectTaskCanceledException [FAIL]
20:01:53         Assert.Throws() Failure
20:01:53         Expected: typeof(System.Threading.Tasks.TaskCanceledException)
20:01:53         Actual:   typeof(System.NullReferenceException): Object reference not set to an instance of an object.
20:01:53         Stack Trace:
20:01:53            d:\j\workspace\dotnet_corefx_windows_debug\src\System.Net.Http.WinHttpHandler\tests\UnitTests\FakeInterop.cs(238,0): at Interop.WinHttp.WinHttpQueryHeaders(SafeWinHttpHandle requestHandle, UInt32 infoLevel, String name, StringBuilder buffer, UInt32& bufferLength, IntPtr index)
20:01:53            d:\j\workspace\dotnet_corefx_windows_debug\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(1970,0): at System.Net.Http.WinHttpHandler.GetResponseHeaderStringInfo(SafeWinHttpHandle requestHandle, UInt32 infoLevel)
20:01:53            d:\j\workspace\dotnet_corefx_windows_debug\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(2014,0): at System.Net.Http.WinHttpHandler.ParseResponseHeaders(SafeWinHttpHandle requestHandle, HttpResponseMessage response, Boolean stripEncodingHeaders)
20:01:53            d:\j\workspace\dotnet_corefx_windows_debug\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(1911,0): at System.Net.Http.WinHttpHandler.CreateResponseMessage(SafeWinHttpHandle connectHandle, SafeWinHttpHandle requestHandle, HttpRequestMessage request)
20:01:53            d:\j\workspace\dotnet_corefx_windows_debug\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(1239,0): at System.Net.Http.WinHttpHandler.<StartRequest>d__5.MoveNext()
20:01:53            --- End of stack trace from previous location where exception was thrown ---
20:01:53               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
20:01:53               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
20:01:53               at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
20:01:53            d:\j\workspace\dotnet_corefx_windows_debug\src\System.Net.Http.WinHttpHandler\tests\UnitTests\WinHttpHandlerTest.cs(833,0): at System.Net.Http.WinHttpHandlerUnitTests.WinHttpHandlerTests.<>c__DisplayClassd7.<<SendAsync_SlowGetRequestWithTimedCancellation_ExpectTaskCanceledException>b__d6>d__d9.MoveNext()
20:01:53            --- End of stack trace from previous location where exception was thrown ---
20:01:53               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
20:01:53               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
20:01:53   Finished:    System.Net.Http.WinHttpHandler.Unit.Tests
20:01:53   
20:01:53   === TEST EXECUTION SUMMARY ===
20:01:53      System.Net.Http.WinHttpHandler.Unit.Tests  Total: 115, Errors: 0, Failed: 1, Skipped: 0, Time: 2.519s

**Comment by davidsh** [comment]
cc: @josguil @CIPop @SidharthNabar 
This might be related to PR #2608

**Comment by davidsh** [comment]
Should be fixed with PR #3096
