### ISSUE TITLE
Nice to have: Bin and Packages folders should be placed outside of the git repo

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#2801]
The huge `Bin` and `Packages` folders are placed in the root of the git repository at the moment.
This makes tools like VSCode impossible to use due to the large quantity of files they need to index. 

A workaround to use VSCode is to load only the \src folder but that is breaking the Git extension which requires the root of the repo to be loaded.

Another reason is using a different partition for binaries that can be quickly formatted when the binaries and packages are not wanted anymore or placing it on a faster disk.

**Comment by weshaggard** [comment]
I'm not sure I want to do this for the general case right now as most folks try and keep there git repo's self-contained. However people can do this on their own by setting some environment variables, in particular BinDir, ObjDir, TestingWorkingDir, PackagesDir, etc. They control where those outputs go.

**Comment by karelz** [comment]
We believe that his is the industry standard to put the files into git repo -- git has ignores, so should VSCode have ignores on them.
Closing for now.

**Comment by CIPop** [comment]
Also, no longer needed if VS Code is used. The VS Code user-voice was fixed some time ago: https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7769619-git-support-in-sub-directories (I am able to open just the \src folder and perform git operations.)
