### ISSUE TITLE
Tests System.Drawing.Tests.FontTests failing on CharSet on non English culture

### ISSUE THREAD

**Issue by satano** [dotnet/corefx#28012]
These two tests are failing on my system:

- [ToLogFont_Invoke_ReturnsExpected](https://github.com/dotnet/corefx/blob/6cd1708e72a863342f6c6b6a7a735cf55ceff048/src/System.Drawing.Common/tests/FontTests.cs#L719)
- [ToLogFont_InvokeGraphics_ReturnsExpected](https://github.com/dotnet/corefx/blob/6cd1708e72a863342f6c6b6a7a735cf55ceff048/src/System.Drawing.Common/tests/FontTests.cs#L756)

Both are failing on asserting `logFont.lfCharSet`. Expected value is always **1** (once as a constant, once as a property `font.GdiCharSet`), but my value is **238**.

I do not know exactly what charset 238 is, but I think, that it is because of my system's culture, which is **Slovak**.

**Comment by safern** [comment]
@satano thanks for your report, this is a dup of: https://github.com/dotnet/corefx/issues/27647

Will close it as we have more details in the other issue.
