### ISSUE TITLE
ReadOnlySequence constructor validation issues

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/corefx#28044]
`public ReadOnlySequence(ReadOnlySequenceSegment<T> startSegment, int startIndex, ReadOnlySequenceSegment<T> endSegment, int endIndex)` constructor does not validate some issues.

I suggest to add next validations:

1. `endSegment.RunningIndex < 0`
to validate that endSegment.RunningIndex not negative.

2. `startSegment != endSegment && (ulong)startSegment.RunningIndex > (ulong)endSegment.RunningIndex - startSegment.Memory.Length`
to validate that startSegment.RunningIndex not negative
and startSegment.RunningIndex + startSegment.Memory.Length <= endSegment.RunningIndex (validate correct order of startSegment and endSegment).

3. Should we check that end is reachable and all `RunningIndex` are correct?

4. Also this constructor throw `ThrowArgumentValidationException` exception without endIndex parameter.
`ThrowHelper.ThrowArgumentValidationException(startSegment, startIndex, endSegment);`
I think it should be
`ThrowHelper.ThrowArgumentValidationException(startSegment, startIndex, endSegment, endIndex);`
If so then `ThrowHelper.ThrowArgumentValidationException` message should be changed also.

**Comment by ahsonkhan** [comment]
> to validate that endSegment.RunningIndex not negative

This is already done today. See tests here https://github.com/dotnet/corefx/blob/master/src/System.Memory/tests/ReadOnlyBuffer/ReadOnlySequenceTests.Common.cs#L360

> to validate that startSegment.RunningIndex not negative
and startSegment.RunningIndex + startSegment.Memory.Length <= endSegment.RunningIndex 

I don't think either of these things are possible, so we don't need to check. @pakrym, please correct me if I am mistaken.

**Comment by benaadams** [comment]
> Also this constructor throw ThrowArgumentValidationException exception without endIndex parameter.
`ThrowHelper.ThrowArgumentValidationException(startSegment, startIndex, endSegment);`

`endIndex` isn't required, we know its wrong, the other three params are checked by the handler, if its none of them then it can be inferred its `endIndex` that is the problem:

```csharp
private static Exception CreateArgumentValidationException<T>(ReadOnlySequenceSegment<T> startSegment, int startIndex, ReadOnlySequenceSegment<T> endSegment)
{
    if (startSegment == null)
        return CreateArgumentNullException(ExceptionArgument.startSegment);
    else if (endSegment == null)
        return CreateArgumentNullException(ExceptionArgument.endSegment);
    else if ((uint)startSegment.Memory.Length < (uint)startIndex)
        return CreateArgumentOutOfRangeException(ExceptionArgument.startIndex);
    else
        return CreateArgumentOutOfRangeException(ExceptionArgument.endIndex);
}
```

**Comment by joshfree** [comment]
@davidfowl @muratg can you take a look at this for the 3/30 bug bounce?

**Comment by muratg** [comment]
@pakrym good to close?
