### ISSUE TITLE
Test System.Net.Tests.HttpRequestStreamTests.Read_FullLengthSynchronous_Success failed with "Assert.Equal() Failure\nExpected: 9\nActual: 6"

### ISSUE THREAD

**Issue by Sunny-pu** [dotnet/corefx#28049]
The test: System.Net.Tests.HttpRequestStreamTests.Read_FullLengthSynchronous_Success(transferEncodingChunked: False, text: \"Non-Empty\") has failed.

Details: https://ci.dot.net/job/dotnet_corefx/job/master/job/centos7.1_debug/5762/testReport/System.Net.Tests/HttpRequestStreamTests/Read_FullLengthSynchronous_Success_transferEncodingChunked__False__text____Non_Empty___/

~~~
MESSAGE:
Assert.Equal() Failure\nExpected: 9\nActual: 6
+++++++++++++++++++
STACK TRACE:
at System.Net.Tests.HttpRequestStreamTests.Read_FullLengthSynchronous_Success(Boolean transferEncodingChunked, String text) in /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug/src/System.Net.HttpListener/tests/HttpRequestStreamTests.cs:line 157 --- End of stack trace from previous location where exception was thrown ---
~~~

**Comment by Sunny-pu** [comment]
failed tests:
Read_FullLengthAsynchronous_Success
Read_FullLengthAsynchronous_PadBuffer_Success
Read_NotEnoughThenCloseAsynchronous_Success
Read_TooMuchSynchronous_Success

**Comment by caesar1995** [comment]
Dup of #27996.

The failure occurs after we made the SocketsHttpHandler the default handler.
