### ISSUE TITLE
XAttribute.ToString() on .NET Core produces different DateTime formats compared to .NET Framework and Mono

### ISSUE THREAD

**Issue by DaRosenberg** [dotnet/corefx#28055]
On .NET Framework and Mono:

``` cs
new DateTime(2018, 1, 1, 12, 13, 14, DateTimeKind.Utc).ToString("o"); // 2018-01-01T12:13:14.0000000Z
new XAttribute("CreatedTime", new DateTime(2018, 1, 1, 12, 13, 14, DateTimeKind.Utc)).ToString(); // CreatedTime="2018-01-01T12:13:14Z"
```

On .NET Core:

``` cs
new DateTime(2018, 1, 1, 12, 13, 14, DateTimeKind.Utc).ToString("o"); // 2018-01-01T12:13:14.0000000Z
new XAttribute("CreatedTime", new DateTime(2018, 1, 1, 12, 13, 14, DateTimeKind.Utc)).ToString(); // CreatedTime="2018-01-01T12:13:14.0000000Z"
```

Note that on .NET Core, the `XAttribute` serialization uses the same format as the [ISO 8601 DateTime format specifier](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#Roundtrip). Whereas, on .NET Framework and Mono, the `XAttribute` serialization uses a reduced format where the ".0000000" are not present.

For us this causes issues because it does not make our XML bidirectionally roundtrippable between client and server (client is Mono and server is .NET Core).

**Comment by stephentoub** [comment]
cc: @tarekgh, @krwq

**Comment by tarekgh** [comment]
> For us this causes issues because it does not make our XML bidirectionally roundtrippable between client and server (client is Mono and server is .NET Core).

could you clarify more regarding that? yes, it is 2 different strings but the date value is same. could you send an example how this break the round-tripping? does your code explicitly depend on the string values? 

@krwq the difference here is in net core we format the date using us ToString("o") while in the desktop we manually format the date 

http://index/?query=XContainer.GetSt&rightProject=System.Xml&file=System%5CXml%5CSchema%5CXsdDateTime.cs&line=508

**Comment by DaRosenberg** [comment]
@tarekgh Yes, I should clarify. It does not technically break round-tripping per se.

Our app uses an in-memory store on both client and server, which reads and writes (using the same code) to an XML file. This XML file is continuously synced at the file level, using the rsync delta transfer protocol, between client and server.

When such a sync happens, the server does a semantic in-memory merge between the XML files submitted by different clients, who might have made changes independently of one another, and persists the result to disk. The resulting file is then transferred back (using delta transfer) to all clients, who in turn perform the same merge procedure locally.

Net result: the semantic content of the data is kept in sync between all clients, with smart optimistic concurrency resolution and minimal bandwidth consumed.

When the server persists the data to disk, this creates a file where every single element is different from the files on the client devices, due to this difference in formatting. This means that the delta transfer back out to the clients is effectively useless, since the whole file is different anyway (the size of the delta actually exceeds the size of the file itself).

And next, when a client makes a change to the data and persists to disk, the format returns to the classic .NET Framework/Mono format, and once again the whole file needs to be transferred to the server because once again the delta is useless.

And on and on it goes. :) Each change on either client or server effectively changes the whole file, compared to the previous version created by the other end, removing the ability to detect incremental changes and perform delta-based (rsync) synchronization between the two.

**Comment by tarekgh** [comment]
@krwq 

Is it possible instead of using DateTime.ToString("o") in the line 
https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml.Linq/src/System/Xml/Linq/XContainer.cs#L833

to use XsdDateTime to format the date? 
https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Xml/Schema/XsdDateTime.cs#L428

or there will be dependency problem?

**Comment by krwq** [comment]
@tarekgh, yes but we should be able to find something in here, i.e.:
https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/XmlConvert.cs#L823

**Comment by danmosemsft** [comment]
Aside why are there two copies
C:\git\corefx\src\Common\src\System\Xml\Schema\XsdDateTime.cs
C:\git\corefx\src\System.Private.Xml\src\System\Xml\Schema\XsdDateTime.cs

The common one I think is dead?

**Comment by krwq** [comment]
@danmosemsft I've created https://github.com/dotnet/corefx/issues/28069 to track this
