### ISSUE TITLE
Regex.Split with RegexOptions.RightToLeft implementation/documentation behavior

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#28056]
I wonder if the current Regex.Split implementation when using in combination with RegexOptions.RightToLeft is what a user would expect. See the below example:
 
```csharp
> Regex.Split("111-a1b2-111", @"a(\d)b(\d)")
string[4] { "111-", "1", "2", "-111" }
> Regex.Split("111-a1b2-111", @"a(\d)b(\d)", RegexOptions.RightToLeft)
string[4] { "111-", "2", "1", "-111" }
```

The only difference is that the capture groups, if some are used are evaluated from right to left, but not the matches themselves. That's because in the implementation the list of string is reversed at the end but the capture groups are added always from left to right (for loop): (https://github.com/dotnet/corefx/blob/master/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.Split.cs#L158).

The docs state the following (https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-options#right-to-left-mode)
> The RegexOptions.RightToLeft option changes the search direction only; it does not interpret the regular expression pattern from right to left.

That could indicate that the current behavior is fine but that with this rule an iterator implementation is not possible because you would already need the last result (the first from left to right) when you just got the first result (the last from left to right). I think the only way to implement an iterator here is to change the behavior to return the results right to left when RegexOptions.RightToLeft is chosen.

cc @vancem @danmosemsft @jkotas @stephentoub @terrajobst @joshfree

**Comment by ViktorHofer** [comment]
cc @vancem @danmosemsft @jkotas @stephentoub @terrajobst

**Comment by ViktorHofer** [comment]
Part of the reason why I'm asking this is because I can't implement a Span enumerator for Regex.Split if we don't yield the entries in the right order. And I can't change the match logic that is used underneath to match left to right because the pattern computation is already done during the Regex instance construction...

**Comment by danmosemsft** [comment]
If it's the same behavior as 2.0 I would add a test to protect the behavior and defer consideration to next release.

**Comment by ViktorHofer** [comment]
I marked the issue as future, this is not time critical! But important to discuss whenever is time.

**Comment by ViktorHofer** [comment]
> If it's the same behavior as 2.0 I would add a test to protect the behavior

Yes it's the same behavior as in 2.0 and in netfx and the behavior is already protected by tests. What I'm questioning is the design decision and with it the written tests.

**Comment by ViktorHofer** [comment]
cc @joshfree

**Comment by ViktorHofer** [comment]
Closing, as I misread the documentation. It clearly states that RegexOptions.RightToLeft only changes the search direction and it does not change the interpretation of the results. Sorry for the spam! Found my answer.
