### ISSUE TITLE
System.Drawing.Font equality on Linux platform

### ISSUE THREAD

**Issue by k0st1x** [dotnet/corefx#28052]
font family is a singleton on the windows platform, but not on Linux

```
            var font1 = new System.Drawing.Font("Arial", 9);
            var font2 = new System.Drawing.Font("Arial", 9);
            Console.WriteLine(font1.Equals(font2)); // false on the Linux platform only
```

may be the Equals method on the Linux platform should be different.

**Comment by safern** [comment]
@k0st1x are you implying that in Linux should be false or that it returns false on linux when it should be true?

**Comment by k0st1x** [comment]
@safern it should be true everywhere, but it is false on the Linux

**Comment by safern** [comment]
Thanks @k0st1x just wanted to make sure I understood what you meant. We do have a Linux Equals method, but we might have missed something.

**Comment by kasper3** [comment]
Font.Equal checks FontFamily.Equals among other things, that is returning false.
From your example:

```c#
using System;
class Program
{
    static void Main(string[] args)
    {
        var font1 = new System.Drawing.Font("Arial", 9);
        var font2 = new System.Drawing.Font("Arial", 9);
        // both of the following print 'False' on the Linux and 'True' on Windows
        Console.WriteLine(font1.Equals(font2)); 
        Console.WriteLine(font1.FontFamily.Equals(font2.FontFamily));
    }
}
```

This comment maybe valid for same instance of managed object (`font1.Equals(font1)`), but not different instance of same font family on Unix: https://github.com/dotnet/corefx/blob/2ffe237f8018902ba931c26811a07c0515a33259/src/System.Drawing.Common/src/System/Drawing/FontFamily.cs#L147-L149

@mellinoe, @qmfrederik

**Comment by kasper3** [comment]
Tested with 2.0 and 2.1 on debian and windows, with nuget.config in project directory:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear/>
    <add key="myget.org dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

then `dotnet add package System.Drawing.Common -v 4.5.0-preview2-*`

**Comment by safern** [comment]
Thanks @kasper3 that is what I noticed as well. I'm assigning myself to fix this issue.

**Comment by kasper3** [comment]
@safern, will this be ported back to 2.0?

**Comment by safern** [comment]
> @safern, will this be ported back to 2.0?

Yes, it should be included in the stable package once we ship it, that will support netcoreapp2.0
