### ISSUE TITLE
Investigate if there is a duplicate code in the common folder for XmlSchema

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#28069]
As @danmosemsft has mentioned in https://github.com/dotnet/corefx/issues/28055 there are two copies of XsdDateTime which might be the same:

```
C:\git\corefx\src\Common\src\System\Xml\Schema\XsdDateTime.cs
C:\git\corefx\src\System.Private.Xml\src\System\Xml\Schema\XsdDateTime.cs
```

If that is the case there might be more copies of other files from XmlSchema as well. Investigate and remove any duplicate code.

**Comment by MarcoRossignoli** [comment]
@krwq is this simila to #27841?

**Comment by krwq** [comment]
@MarcoRossignoli I don't see XmlSchema on that list. We can add it as subitem there. In here the exact file list is not known at this time.
