### ISSUE TITLE
[Desktop] HttpClientHandler authentication test cases failing (hang) on Framework run

### ISSUE THREAD

**Issue by caesar1995** [dotnet/corefx#28060]
Contributes: #27113

The `HttpClientHandler_Authentication_Succeeds()` test will fail on Framework run with `System.TimeoutException : WhenAllOrAnyFailed timed out after 60000`, for the below four test data:

```c#
yield return new object[] { "Digest realm=withoutquotes, nonce=withoutquotes", false };

yield return new object[] { "Digest realm=\"testrealm1\", nonce=\"testnonce1\" Digest realm=\"testrealm2\", nonce=\"testnonce2\"", false };
yield return new object[] { "Basic something, Digest something", false };
yield return new object[] { $"Digest realm=\"testrealm\", nonce=\"testnonce\", algorithm=MD5 " +
                $"Basic realm=\"testrealm\"", false };
```

**Comment by karelz** [comment]
The tests are now limited to SocketsHttpHandler only, the test cases are invalid, so I think we are fine.
It is not worth to improve them and codify the Desktop behavior IMO. cc @davidsh 

The tests:
https://github.com/dotnet/corefx/blob/9e8c200f0888a1db590da8ffa026aa7384771611/src/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs#L591-L595
