### ISSUE TITLE
Expression.Nop() method

### ISSUE THREAD

**Issue by hackcraft** [dotnet/corefx#2807]
In writing #2803 I needed a NOP/NOOP expression; takes no parameters, has no side-effects, returns void: The expression equivalent to the C# `{}` or `;`

I'd somehow assumed that there would be an `Expression.Nop` or `Expression.Noop` that I'd just never had cause to use before, but I could find no such method. So I tried `Expression.Block()` to have an empty block, as per `{}`, but that wasn't allowed.

Okay, that's easily allowed in a backwards-compatible way, as long as we have a `Nop` to use…

In the end I used `private static readonly Expression Nop = Label(Label());`

It seems reasonable to believe that this is not the only case anyone would ever want a nop expression. Nop doesn't come up a lot in high-level programming unless a syntax demands it, but it does come up sometimes. Therefore I propose adding `Nop()` to the public interface of the class, exposing this private expression.

**Comment by VSadov** [comment]
Is this the same as Expression.Empty() ?

**Comment by hackcraft** [comment]
Ah ha! I read through the method list so many times too.
