### ISSUE TITLE
System.IO.Tests.EnumerableTests/EnumerateDirectories_NonBreakingSpace failing on OSX

### ISSUE THREAD

**Issue by Anipik** [dotnet/corefx#28093]
```
Assert.Equal() Failure
Expected: String[] [\"/tmp/EnumerableTests_zyuc5nbu.hrc/EnumerateDirecto\"..., \"/tmp/EnumerableTests_zyuc5nbu.hrc/EnumerateDirecto\"...]
Actual:   FileSystemEnumerable<String> [\"/tmp/EnumerableTests_zyuc5nbu.hrc/EnumerateDirecto\"..., \"/tmp/EnumerableTests_zyuc5nbu.hrc/EnumerateDirecto\"...]
```
https://mc.dot.net/#/user/Anipik/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/26b967e2aab520a0da79c316024360f635dc937d/workItem/System.IO.FileSystem.Tests/analysis/xunit/System.IO.Tests.EnumerableTests~2FEnumerateDirectories_NonBreakingSpace

cc @JeremyKuhne @danmosemsft

**Comment by JeremyKuhne** [comment]
Possible that there is an ordering problem. If so use FSAssert.EqualWhenOrdered().
