### ISSUE TITLE
System.Diagnostics.FileVersionInfo different/incorrect behaviors compared to .NET Framework

### ISSUE THREAD

**Issue by davkean** [dotnet/corefx#281]
FileVersionInfo solely depends on System.IO.FileSystem (and all of its dependencies, including System.IO, System.Threading.Tasks, etc) just to do a File.Exists in GetVersionInfo. We should remove this and instead see if we can use the return value of GetFileVersionInfoSizeEx to mimic the same behavior.

**Comment by Alexx999** [comment]
Do you have any tests for File.Exists that show it's behavior?
If I understand it correct - File.Exists checks (or at least should check) for 2 primary cases:
 1. File exists
 1. User has permission to read that file
It's not that hard to check for this two cases. But it surely makes no point to re-implement all File.Exist quirks just to drop dependency.

**Comment by stephentoub** [comment]
Note that we depend on FileStream for the Unix implementation of this library.

**Comment by ElPumpo** [comment]
Same bug here, please fix? Trying to use FileVersionInfo in system32 (priv folder) just doesn't work

**Comment by Petermarcu** [comment]
Given that the layering goals of .NET Core have changed and some of the low level assembly factoring isn't as critical, is this still worth keeping open/investing in?

**Comment by jkotas** [comment]
For layering - no. But the other issues mentioned in the discussion should be fixed. E.g.:

```
            File.WriteAllText("kernelbase.dll", "bogus kernelbase.dll");
            Console.WriteLine(FileVersionInfo.GetVersionInfo("kernelbase.dll"));
```

.NET Framework: Absolute path required exception
.NET Core: Incorrectly returns version info for `%WINDIR%\System32\kernelbase.dll`, not for the kernelbase.dll from the current directory.

**Comment by Petermarcu** [comment]
Sounds good.

**Comment by wtgodbe** [comment]
I've put up https://github.com/dotnet/corefx/pull/25978 to try to addres this, please let me know if that isn't the right fix.

**Comment by wtgodbe** [comment]
Resolved by https://github.com/dotnet/corefx/pull/25978
