### ISSUE TITLE
Issue with HttpClient with Client Certificate on Ubuntu 16.04

### ISSUE THREAD

**Issue by tdolgyras** [dotnet/corefx#28107]
Ubuntu 16.04
.net sdk 2.1.4

We have an issue making a Https Request with httpClient in Ubuntu 16.04
Sample code
```
using (var client = new HttpClient())
{
    var contents = await client.GetStringAsync("https://mplampla.org/get");
    Console.WriteLine(contents);
}
```
We get this error
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (An error occurred while sending the request.) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Problem with the SSL CA cert (path? access rights?)
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<GetStringAsyncCore>d__27.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at tests.Program.Main(String[] args) in /home/user/tests/Program.cs:line 14

```

In our windows pc works perfectly. This website uses Let'sEncrypt for ssl.
Do we have any workaround?  We searched the backlog and there are a lot similar issues but no workaround was found. 

thank you

**Comment by wfurt** [comment]
mplampla.org does not resolve for me. Did you mean mplampla.com ? 
Does it work when you use curl from commands line? 
If not, there can be something wrong about your system trust.

**Comment by tdolgyras** [comment]
When i user curl it works.
Here is the correct url.
curl -i http://auth.dimoschalkideon.gr/.well-known/openid-configuration

**Comment by karelz** [comment]
@tdolgyras the curl URL is not HTTPS, can you check also with HTTPS?

**Comment by wfurt** [comment]
btw the default curl builds with GnuTLS @karelz.
curl 7.50.1 (x86_64-pc-linux-gnu) libcurl/7.50.1 GnuTLS/3.5.3 zlib/1.2.8 libidn/1.33 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

That is another layer or pain. Is the client certificate self-signed or is it trusted @tdolgyras

**Comment by xrkolovos** [comment]
I am a colleague of @tdolgyras

```
curl -i https://auth.dimoschalkideon.gr/.well-known/openid-configuration

HTTP/1.1 200 OK
Server: nginx/1.10.3 (Ubuntu)
Date: Sat, 17 Mar 2018 09:37:42 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff

```
Https works fine. The certificate  is issued from Let's Encrypt. That's the real address we are trying to communicate.

**Comment by davidsh** [comment]
The title of this issue references the words "client certificate".  But I don't see where client certificates are being in the code snippet above.  Does this repro involves any client certificates?  If so, this code snippet above should be adding those client certificate(s) to HttpClientHandler like this:

```c#
handler.ClientCertificates.Add(cert);
```


I just see the server certificate that comes from the server "auth.dimoschalkideon.gr".

**Comment by davidsh** [comment]
Also, we have seen issues with the .NET Core 2.0 Linux HTTP stack (which uses Curl).  It sometimes has been returning this error:

>System.Net.Http.CurlException: Problem with the SSL CA cert (path? access rights?)

You might want to try out .NET Core 2.1 Preview 2.  It uses a new HTTP implementation, SocketsHttpHandler.

See; https://blogs.msdn.microsoft.com/dotnet/2018/04/11/announcing-net-core-2-1-preview-2/

**Comment by karelz** [comment]
Not actionable at this point, closing. If you can still reproduce problems on 2.1 RC, please let us know. Thanks!
