### ISSUE TITLE
Improve test coverage of Span.SequenceCompareTo for T != byte

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#28118]
We need to add more tests for MemoryExtensions SequenceCompareTo for T = int, long, string, etc.

For context - https://github.com/dotnet/corefx/pull/28080#discussion_r174811155

**Comment by sputier** [comment]
I'd be glad to start contributing to corefx wth this one !

**Comment by ahsonkhan** [comment]
> I'd be glad to start contributing to corefx with this one !

Awesome! Let me know if you have any questions regarding on-boarding or contributing.

@karelz, can we please assign this issue to @sputier?

**Comment by karelz** [comment]
@sputier I just sent you collaborator invite (GH prereq to assign it to you). Once you accept ping me and I will reassign it to you (assigning to myself temporarily).
Heads up: Accepting will auto-subscribe you to all repo notifications (500+ per day). We recommend to change repo Watch settings to "Not Watching" - that will notify you only about your mentions and explicit subscriptions.

**Comment by sputier** [comment]
@ahsonkhan @karelz Thank you ! I accepted the invite, and I'm ready to dig into corefx :smile:

**Comment by KrzysztofCwalina** [comment]
@sputier, we would like to fix all ship stopping bugs by end of week so they have time go through PR review / CI.  Is that something you'd still want to tackle?

**Comment by sputier** [comment]
I'm working on it at the moment and I'll make a PR tomorrow (3PM PT or so). Is it OK for you ?

**Comment by KrzysztofCwalina** [comment]
Perfect. Thanks for confirming so quickly!
