### ISSUE TITLE
System.Data.SqlClient cannot be found

### ISSUE THREAD

**Issue by johnkors** [dotnet/corefx#28139]
Hi

In a specific scenario, I cannot load `System.Data.SqlClient` using the 2.0.6 runtime. The 2.0.5 runtime works.

A small repro : https://github.com/johnkors/sqlclient.runtime.test

A build of both runtimes:
https://travis-ci.org/johnkors/sqlclient.runtime.test/builds/354338277

In 2.0.5, I can use System.Data.SqlClient (ok, it fails to connect to a unknown db here - but using the dll works).
In 2.0.6, I get the FileNotFoundException.

>Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.SqlClient, Version=4.2.0.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

(bumping the the dependency on `System.Data.SqlClient` to 4.4.3 makes it work with both runtimes.)

**Comment by johnkors** [comment]
The issue is the same on both windows and linux containers.

**Comment by florimm** [comment]
I have the same issue also, I think this happened after I upgraded visual studio.

**Comment by florimm** [comment]
This:
```
.NET Command Line Tools (2.1.101)

Product Information:
 Version:            2.1.101
 Commit SHA-1 hash:  6c22303bf0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.101\

Microsoft .NET Core Shared Framework Host
  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d```

**Comment by florimm** [comment]
> (bumping the the dependency on System.Data.SqlClient to 4.0.3 makes it work with both runtimes.)

@johnkors I think you mean System.Data.SqlClient 4.4.3

**Comment by johnkors** [comment]
Yes, good catch. 4.4.3 works. Edited.

**Comment by karelz** [comment]
Are you saying that if you build the app (https://github.com/johnkors/sqlclient.runtime.test/blob/master/src/host/Program.cs) against 2.0.0-2.0.5, then install 2.0.6, it will stop working (throwing the exception above)?
That looks like packaging or setup problem - @weshaggard @joperezr any idea where to route it?

**Comment by johnkors** [comment]
Yes, correct @karelz .

**Comment by johnkors** [comment]
You can run these commands in the repro repo to check it out:
`docker build -f 2.0.5.Dockerfile .`
vs
`docker build -f 2.0.6.Dockerfile .`

**Comment by weshaggard** [comment]
I've repro'ed this and I know the problem, it isn't an issue with System.Data.SqlClient package but the instead the shims (in particular System.dll shim) in the shared framework. I will fix it and see if I can suggest a workaround.

**Comment by weshaggard** [comment]
I've got a PR out that will fix this issue in master https://github.com/dotnet/corefx/pull/28234. Once it goes in I will look to get this fix ported to our release/2.0.0 branch as well.

However with that said the best workaround is to bump your System.Data.SqlClient package version to 4.4.3 as you already discovered.

**Comment by johnkors** [comment]
Thanks, @weshaggard ! 

As this is with the shim. What's the most likely scenario here? Will the fix be part of new release of the 2.0.6 runtime or released as a 2.0.7 runtime..?

**Comment by weshaggard** [comment]
Yes the fix will be in an upcoming servicing release. I think we maybe too late for 2.0.7 release but hopefully 2.0.8 release. I will update this issue with that version once I know which shipping train it gets on.

In the meantime there shouldn't be any real drawbacks to updating the version of System.Data.SqlClient (other then the fact you have to update it :)).

**Comment by weshaggard** [comment]
I also want to call out that not everyone will hit this issue as there are three things that have to be true before it triggers:

1) You have to move from 2.0.x to 2.0.6 shared framework.
2) You have to be referencing and using a version of System.Data.SqlClient less then 4.4.3.
3) You have to be using a library that uses a Data type from the System.dll shim, that is usually a .NET Framework library. In your case that is the FluentMigrator library.

Number (3) is the one that isn't very common which is why we haven't seem other reports of this issue thus far. At any rate thanks for reporting and we will get this fixed.

**Comment by johnkors** [comment]
Yep, no worries. Just for context: We hit this issue as soon as we tried to update to 2.0.6 as of the recommended upgrades mentioned in the latest ASP.NET / dotnet core security announcements from @blowdart.

I don´t think we'll have any issues upgrading all our apps to 4.4.3 before installing the 2.0.6 runtime. Just a bit more work on our end to get the security fix out. 

Thanks!

**Comment by bradleypatton** [comment]
I'm having the same issue. App works fine locally but throws the missing file exception once pushed to Azure. All of the to SqlClient that I can see are to 4.4.3. Is there a workaround that I am missing?
