### ISSUE TITLE
Investigate a better way to handle * dependencies

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#2813]
We're inconsistent across the repo and buildtools.  Some places we use -* others we use -beta-*.  It seems that both have the draw back of not permitting an upgrade to latest stable version, or moving past any changes in the major.minor.build version.  In most places the semantics we want is either 4.0.*: latest of a given API version or 4.*: latest API of a major release.

In conjunction with this we need to experiment with how to use policy to impact the behavior of restore.  In some cases we want "minimum that satisfies the constraint" in others we want "latest that satisfies the constraint".
/cc @weshaggard

**Comment by weshaggard** [comment]
@ericstj I think we have this covered now with the work taht @dagood has done with the remove of all lock files and * versions. So I'm closing this. If you feel there is still more to be figured out please re-open.
