### ISSUE TITLE
ConcurrentDictionary is not marked as serializable

### ISSUE THREAD

**Issue by EgorBo** [dotnet/corefx#28137]
The following code crashes:
```
var cd = new ConcurrentDictionary<int, int>();
cd[0] = 42;
var bf = new BinaryFormatter();
bf.Serialize(new MemoryStream(), cd);
```
with
```
System.Runtime.Serialization.SerializationException : Type
'System.Collections.Concurrent.ConcurrentDictionary`2[[System.Int32, System.Private.CoreLib, 
Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, 
System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' in 
Assembly 'System.Collections.Concurrent, Version=4.0.14.0, Culture=neutral, 
PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable.
```
(tested on .net core 2.0, 2.1-preview and master).
The regular dictionary serializes just fine.

UPD: just found https://github.com/dotnet/corefx/pull/19742
I am wondering will it be fixed or it's by design now?

**Comment by stephentoub** [comment]
This was by design. We only brought back runtime serialization for types where it was deemed really important for broad compat.

**Comment by ViktorHofer** [comment]
Find binary serializable types for .NET Core here: https://docs.microsoft.com/en-us/dotnet/standard/serialization/binary-serialization#binary-serialization-in-net-core
