### ISSUE TITLE
Culture info ru-BY missed in .NET core 2.0.6 on Windows Server 2012 R2

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#28145]
_From @NGancevich on March 16, 2018 7:16_

I have Localization on my asp.net core 2.0.6 and it's working on local machine. But when I publish to IIS on server 2012 r2 it's throwing an exception
Application startup exception: System.Globalization.CultureNotFoundException: Culture is not supported.
Parameter name: name
ru-by is an invalid culture identifier.
   at System.Globalization.CultureInfo.InitializeFromName(String name, Boolean useUserOverride)

According to the link https://msdn.microsoft.com/en-us/library/cc233982.aspx it's valid culture info.

Event microsoft has this localization on site https://www.microsoft.com/ru-by

_Copied from original issue: aspnet/Home#2967_

**Comment by tarekgh** [comment]
The framework picks the culture information from the OS (i.e. Windows in this case). looking at the link you have pointed at  https://msdn.microsoft.com/en-us/library/cc233982.aspx it shows 

```
Russian | Belarus | 0x1000 | ru-BY | Release 10
```

which means this culture supported in Release 10 which is 

```
Release 10 | First available in Windows 10 and Windows Server 2016. Supported in all later versions.
```

So this is not supported on server 2012 r2
