### ISSUE TITLE
Update cross build-rootfs for modern world

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/corefx#28140]
As part of building docker image for arm64 cross compiling I spent a lot of time looking at build--rootfs.sh.  The following seem like changes which should be done...

+ Add latest Ubuntu version: Artful and Bionic
+ Remove unsupported Ubuntu versions: Vivid and Wily
+ Add latest lldbdev versions: 4.0, 5.0, 6.0
+ Update lldb default to 3.9 to be consistent with non-cross build
+ Drop old lldb versions 3.6 and 3.8
+ Add error checking which is present in core-setup version

See https://github.com/dotnet/core-setup/issues/3843

@janvorli FYI

**Comment by wfurt** [comment]
Bionic is in and I guess there is no point for Artful now. 
Please close this @sdmaclea unless you feel something else needs to be done. 

```
macik2:wfurt-corefx furt$ ./cross/build-rootfs.sh --help
Usage: ./cross/build-rootfs.sh [BuildArch] [LinuxCodeName] [lldbx.y] [--skipunmount]
BuildArch can be: arm(default), armel, arm64, x86
LinuxCodeName - optional, Code name for Linux, can be: trusty(default), vivid, wily, xenial, zesty, bionic, alpine. If BuildArch is armel, LinuxCodeName is jessie(default) or tizen.
lldbx.y - optional, LLDB version, can be: lldb3.6(default), lldb3.8, lldb3.9, lldb4.0, no-lldb. Ignored for alpine
--skipunmount - optional, will skip the unmount of rootfs folder.
```

**Comment by sdmaclea** [comment]
Based on your message, at least the following work items above are not complete.
+ Remove unsupported Ubuntu versions: Vivid and Wily... I would guess more are obsolete now...
+ Add latest lldbdev versions: 5.0, 6.0
+ Update lldb default to 3.9 to be consistent with non-cross build
+ Drop old lldb versions 3.6 and 3.8

Feel free to close if this issue is not useful...
