### ISSUE TITLE
HttpStatusCode compatibility across framework

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#28157]
@incompletude commented on [Fri Mar 16 2018](https://github.com/dotnet/core/issues/1356)

This is very inconvenient. Both ways produce errors.

```
[ProducesResponseType(HttpStatusCode.OK)] // cast

return StatusCode(HttpStatusCode.OK, users); // cast
```

Is there any reason for this?

Thx.

**Comment by karelz** [comment]
@incompletude did you mean these ASP.NET Core types?
* [Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute](https://apisof.net/catalog/Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute)
* [Microsoft.AspNetCore.Http.StatusCodes](https://apisof.net/catalog/Microsoft.AspNetCore.Http.StatusCodes)

If yes, then https://github.com/aspnet will be the right place to address your question/suggestion.
