### ISSUE TITLE
Proposal TypeListAttribute

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/corefx#28152]
# Suggestion:
Define a TypeListAttribute tilke this:

```
public class TypeListAttribute : Attribute
{
    public Type[] Types;
    public TypeListAttribute(params Type[] types)
    {
        Types = types;
    }
} 
```

This attribute can be used to mark generic classes like this:
```
[TypeList(typeof(int), typeof(float), typeof(byte))]
class foo<T>  
{
        void DoSomething(T x, T y)
         {
                 T z = x + y;
          }
 }
```
Then C# or VB.NET can use the TypeListAttribute.Types[] to validate the generic class code.
The compiler should test the foo<T> for all these types, i.e. foo< int >, foo< float > , foo< byte >.
if the code of the foo class is ok in all these cases, then it should compile correctly (i.e doesn't complain about the x + y operation) .

# Benefit:
This will solve some problems when there is no common interface to use as a constraint. for more details: https://github.com/dotnet/corefx/issues/27167

# Note: I asked also for C# syntax to define the list to avoid the long attribute syntax (https://github.com/dotnet/csharplang/issues/1388). This would be:
```
class foo<T>  where T: {int, float, byte}
{
        void DoSomething(T x, T y)
         {
                 T z = x + y;
          }
 }

```

**Comment by jkotas** [comment]
> C# or VB.NET can use the TypeListAttribute.Types[] to validate the generic class code.

This C# language feature needs to be vetted first. It does not make sense to do without it.

**Comment by karelz** [comment]
Is your goal of `TypeListAttribute` to enable multiple generic constraints? (i.e. `where T : { int, float, byte}`)
That would not be the right way to go about it - attribute cannot express which generic argument it applies to and it is vastly different from existing generic constraints which are encoded in Metadata tables - see [ECMA spec 335](http://www.ecma-international.org/publications/standards/Ecma-335.htm) - sections II.9.11 "Constraints on generic parameters" for details.
