### ISSUE TITLE
[HttpListener] [GetContext] GetContext method call should unblock after call to Stop

### ISSUE THREAD

**Issue by raufismayilov** [dotnet/corefx#28169]
Hello,

It looks like there is an issue with HttpListener.GetContext call on windows. It should somehow unblock when HttpListener.Stop is called. However, It hangs on Windows, while on Ubuntu it works fine, i.e. throws HttpListenerException: Listener closed. The code is below:

```c#
var listener = new HttpListener();

listener.Prefixes.Add("http://+:9000/test/");

listener.Start();

var listenerTask = Task.Run(() =>
{
    try
    {
        var context = listener.GetContext();
    }
    catch(Exception ex)
    {
        Console.WriteLine($"Listener exception: {ex.GetType().Name}, {ex.Message}");
    }
});

Console.WriteLine("Running");

Console.ReadLine();

listener.Stop();
listener.Close();
```

By the way, GetContextAsync version works properly on both platforms: it throws ObjectDisposedException

[EDIT] Add C# syntax highlighting by @karelz

**Comment by karelz** [comment]
FYI: Windows is built on top of http.sys OS component, while we have C# implementation on Linux/Mac. Hence the difference.
@caesar1995 do you have any insight what might be going on?

**Comment by raufismayilov** [comment]
The version details, as well as the results of running the code, are as follows:

- windows 10 .net core 2.1.300-preview1-008174, result: GetContext hangs and doesn't unblock when Stop is called

- ubuntu 17.10 .net core 2.1.4, result: GetContext throws HttpListenerException, Listener closed.

- windows 10 .net 4.6.2, result: GetContext throws HttpListenerException, The I/O operation has been aborted because of either a thread exit or an application request
