### ISSUE TITLE
HttpStatusCode compatibility across framework

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#28172]
@incompletude commented on [Sat Mar 17 2018](https://github.com/dotnet/core/issues/1358)

Is there any reason for this?

[ProducesResponseType(HttpStatusCode.OK)] // requires cast
return StatusCode(HttpStatusCode.OK); // requires cast

Thx

**Comment by karelz** [comment]
Duplicate of #28157

**Comment by incompletude** [comment]
Sorry karelz. I messed up here. I thought I ask the wrong repo. Now I did.

**Comment by karelz** [comment]
@incompletude no problem. It is sometimes not super-simple to navigate through our repos - the ["file new issue" template in core repo](https://github.com/dotnet/core/blob/master/ISSUE_TEMPLATE) has some pointers to our repos.
