### ISSUE TITLE
ConcurrentDictionary<,>.IsEmpty is barely faster than checking Count

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/corefx#28188]
I would assume that a specialist method named `IsEmpty` is significantly faster than simply obtaining the `Count` of a `ConcurrentDictionary<,>`, yet it appears to be just a touch slower.

x-ref https://github.com/WiseTechGlobal/WTG.Analyzers/pull/23#issuecomment-374116037

Similar to the benchmark in the linked above, here's a benchmark comparing an empty dictionary to one containing 1,200 items.

I would expect `Empty_IsEmpty` to take roughly the same amount of time as `Contents_IsEmpty`, but it appears to scale up similarly to testing against `Count`.

```
// * Summary *

BenchmarkDotNet=v0.10.13, OS=Windows 10 Redstone 3 [1709, Fall Creators Update] (10.0.16299.309)
Intel Core i5-7600K CPU 3.80GHz (Kaby Lake), 1 CPU, 4 logical cores and 4 physical cores
Frequency=3703123 Hz, Resolution=270.0423 ns, Timer=TSC
.NET Core SDK=2.1.100-preview-007326
  [Host]     : .NET Core 2.0.5 (CoreCLR 4.6.26020.03, CoreFX 4.6.26018.01), 64bit RyuJIT
  DefaultJob : .NET Core 2.0.5 (CoreCLR 4.6.26020.03, CoreFX 4.6.26018.01), 64bit RyuJIT


           Method |        Mean |     Error |    StdDev |  Gen 0 | Allocated |
----------------- |------------:|----------:|----------:|-------:|----------:|
    Empty_IsEmpty |    67.29 ns | 0.0808 ns | 0.0716 ns |      - |       0 B |
      Empty_Count |    67.49 ns | 0.0255 ns | 0.0199 ns |      - |       0 B |
    Empty_LinqAny |   180.82 ns | 0.1109 ns | 0.0926 ns | 0.0203 |      64 B |
 Contents_IsEmpty | 3,907.88 ns | 1.8701 ns | 1.7493 ns |      - |       0 B |
   Contents_Count | 4,129.74 ns | 1.5337 ns | 1.3596 ns |      - |       0 B |
 Contents_LinqAny |    42.68 ns | 0.0471 ns | 0.0417 ns | 0.0203 |      64 B |

```

Is `IsEmpty` actually doing anything special or could the implementation just about be replaced with:

```csharp
public bool IsEmpty => Count == 0;
```

?

I don't actually see a huge difference in the two implementations.

**Comment by omariom** [comment]
Have you tried it in multithreaded scenario?

**Comment by yaakov-h** [comment]
Would that actually make a difference, considering that both `IsEmpty` and `Count` start off with a call to `AcquireAllLocks`?

**Comment by omariom** [comment]
Hmm.. From what I've seen concurrent collections have `IsEmpty` property as an optimization opportunity.

`ConcurrentDictionary` could try take/release each lock individually until it finds non-empty one. IMO, unlike `Count` it doesn't have to be very precise.

**Comment by stephentoub** [comment]
> I don't actually see a huge difference in the two implementations.

The difference is that Count needs to look at the counts for each bucket in order to sum them.  IsEmpty stops looking at the counts once it finds one that's non-zero.

> could try take/release each lock individually until it finds non-empty one

The IsEmpty implementation provides a moment-in-time statement of truth.  If It were to take/release each lock, it's possible the collection could have never been empty but IsEmpty could still return true, e.g. if the dictionary contains a single item in one bucket, one thread adds another item into another bucket and then removes the original one, but IsEmpty looks at each bucket in an order such that it sees each one containing 0 items.

> ConcurrentDictionary<,>.IsEmpty is barely faster than checking Count

Is there something actionable on this issue?

**Comment by yaakov-h** [comment]
So what does the IEnumerator / LINQ .Any() do? It appears to take no locks at all... can this return false even if the dict has items, as you suggested with taking a lock bucket-by-bucket?

> Is there something actionable on this issue?

I was hoping for an optimisation, once figuring out what was happening under the hood.

**Comment by stephentoub** [comment]
> So what does the IEnumerator / LINQ .Any() do?

It's just enumerating ConcurrentDictionary's enumerator, which is designed not to provide a snapshot and thus can get away without using locks, just as reading from a ConcurrentDictionary doesn't take locks, but doesn't provide snapshot semantics.

If you're fine with those semantics, you can use Any.  But we can't change IsEmpty to do the equivalent of Any.

**Comment by yaakov-h** [comment]
Does that mean that `Any()` can return false even when the collection does contain items?

**Comment by stephentoub** [comment]
> Does that mean that Any() can return false even when the collection does contain items?

Yes, e.g.
```C#
using System;
using System.Collections.Concurrent;
using System.Threading.Tasks;

class Program
{
    static void Main()
    {
        while (true)
        {
            var items = new ConcurrentDictionary<long, long>();
            items.TryAdd(0, 0);
            Task.WaitAll(
                Task.Run(() =>
                {
                    while (true)
                    {
                        int count = 0;
                        foreach (var pair in items) count++;
                        if (count == 0) Console.WriteLine("count == 0");
                    }
                }),
                Task.Run(() =>
                {
                    for (long i = 1; ; i++)
                    {
                        items.TryAdd(i, i);
                        items.TryRemove(i - 1, out _);
                    }
                }));
        }
    }
}
```

**Comment by yaakov-h** [comment]
Hmm, thanks.
