### ISSUE TITLE
SqlUDTStorage.GetStaticNullForUdtType accessing shared dictionary without propery synchronization

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#28198]
https://github.com/dotnet/corefx/blob/251d65c237aa26b49bc91bac25012340a93e64de/src/System.Data.Common/src/System/Data/Common/SqlUDTStorage.cs#L40-L63

It looks like it was written assuming Dictionary has the same thread-safety characteristics as Hashtable, but it doesn't.  Whereas Hashtable is safe for any number of reads to be used concurrently with at most one writer, for a Dictionary a writer must have exclusive access.

**Comment by stephentoub** [comment]
> So effectively the writer has exclusive access to the Dictionary before writing to it.

No, reads can still be occurring concurrently with the write, and that's not safe.

**Comment by saurabh500** [comment]
What is the safety issue, that the reader will read while the writes are going on, and get a null value, and hence will go on to write again?

**Comment by saurabh500** [comment]
I am basically trying to understand the tagging with `tenet-reliability` in this case.

**Comment by stephentoub** [comment]
> What is the safety issue

In general, code shouldn't use types concurrently in a manner they weren't designed to be used. Trying to read from a dictionary while it's being mutated could result in a variety of problems.  For example, this produces a NullReferenceException for me within seconds:
```C#
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

class Program
{
    static void Main()
    {
        while (true)
        {
            var items = new Dictionary<int, int>();
            Task.WaitAll(
                Task.Run(() =>
                {
                    for (int i = 0; i < 100; i++) items.TryGetValue(i, out int item);
                }),
                Task.Run(() =>
                {
                    for (int i = 0; i < 100; i++) items[i] = i;
                }));
        }
    }
}
```

**Comment by danmosemsft** [comment]
@saurabh500 very shortly, https://github.com/dotnet/coreclr/pull/16991 will flag this misuse with an InvalidOperationException

**Comment by stephentoub** [comment]
> very shortly, dotnet/coreclr#16991 will flag this misuse with an InvalidOperationException

Though only if we had code that causes the race condition, which we don't currently.  This code is currently not exercised by any tests, and not in parallel with enough contention to cause the race to occur.

**Comment by stephentoub** [comment]
Actually, @danmosemsft, would that actually flag such cases?  I'd expect it to be better at flagging cases where there are parallel updates, rather than parallel reading with a single update.

**Comment by saurabh500** [comment]
Thanks @danmosemsft and @stephentoub 

@stephentoub  I hadn't realized that you were talking about the internals of the Dictionary throwing exception. I was looking at this from the point of view of a logical bug in the code where the data will never be returned as expected. I could very easily repro this issue with your code. It was extremely quick.

**Comment by danmosemsft** [comment]
@stephentoub you're right, I did not attempt to verify that so I cannot make that statement. All we know is that after that change, misuse will no longer manifest in a hang.

**Comment by stephentoub** [comment]
> misuse will no longer manifest in a hang

And that in and of itself is goodness :)

**Comment by akashkc** [comment]
@stephentoub If we will use `Dictionary` instead of `ConcurrentDictionary`, for instance using ..NET 3.5, what would be your suggestion to write in `s_typeToNull` dictionary  in thread-safe manner? I've an impression that using lock on object make it exclusive access to write.

**Comment by stephentoub** [comment]
> If we will use Dictionary instead of ConcurrentDictionary, for instance using ..NET 3.5, what would be your suggestion to write in s_typeToNull dictionary in thread-safe manner? I've an impression that using lock on object make it exclusive access to write.

If there's a possibility that writes will happen concurrently with other writes or with reads, you need to lock on all accesses, both reads and writes.

**Comment by akashkc** [comment]
Now, got it. Thank you @stephentoub .
