### ISSUE TITLE
Microsoft.CSharp code using unprotected shared dictionaries

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#28199]
I did a search for "static readonly Dictionary" across corefx and looked for places where dictionaries were mutated without synchronization.  It looks like there are a few in Microsoft.CSharp, e.g.
https://github.com/dotnet/corefx/blob/251d65c237aa26b49bc91bac25012340a93e64de/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Semantics/Symbols/SymbolStore.cs#L18
https://github.com/dotnet/corefx/blob/251d65c237aa26b49bc91bac25012340a93e64de/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Semantics/Types/TypeArray.cs#L82-L83
https://github.com/dotnet/corefx/blob/251d65c237aa26b49bc91bac25012340a93e64de/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Semantics/Types/TypeManager.cs#L18-L19
https://github.com/dotnet/corefx/blob/251d65c237aa26b49bc91bac25012340a93e64de/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Semantics/Types/TypeTable.cs#L51-L62

It's possible there's something higher up in the call stacks that's guaranteeing safety, but it's not obvious from a quick code inspection.

cc: @VSadov, @JonHanna

**Comment by VSadov** [comment]
There is a global binder lock. Binder is single threaded.

**Comment by stephentoub** [comment]
> There is a global binder lock. Binder is single threaded.

Ok, so all of these are protected and fine? If so, we can close it.

**Comment by VSadov** [comment]
It may be worth adding comments that these are ok threading-wise. 
Otherwise, static dictionaries indeed look suspicious.

**Comment by JonHanna** [comment]
There is a comment to the effect, at the central point where the lock is taken, but comments nearer the dictionaries themselves wouldn't hurt.
