### ISSUE TITLE
Apply hang protection to HashSet<T>  that we added to Dictionary<K,V>

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#28209]
HashSet is likely prone to the same expensive hang as it uses essentially the same datastructures. 

We should port dotnet/coreclr#16991 to Hashset.

cc @benaadams

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/issues/28123

**Comment by danmosemsft** [comment]
I see @vancem pointed out it has been reported to have been hit in cloud services using HashSet also. We should certainly port, then.

@safern perhaps you'd like to do this?

**Comment by safern** [comment]
> @safern perhaps you'd like to do this?

Porting it now.

**Comment by danmosemsft** [comment]
This is not going to meet the bar to port to 2.0 given that it will be very soon superseded by 2.1 and our [support policy](https://github.com/dotnet/core/blob/65914ae235a5ecbcab7908b8247999ff7ecd75d8/microsoft-support.md#net-core-release-lifecycles)
