### ISSUE TITLE
HttpContent.ReadAsStreamAsync is over-allocating memoty

### ISSUE THREAD

**Issue by dotMorten** [dotnet/corefx#28208]
In order to reduce memory overhead, we make webrequests return when the headers have been read using:

  `HttpClient.GetAsync(uri, HttpCompletionOption.ResponseHeadersRead);`

The idea is that afterwards you'll be reading the bytes from the returned stream as they trickle in from the network. Or at least that's what I had hoped. But looking at the implementation, the moment you try and get the stream from the HttpContent, the entire stream is loaded into memory:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpContent.cs#L253

If these responses are very large, it could exhaust the application for memory.
Instead the ReadAsStreamAsync should return a buffer immediately and have it get filled as the bytes gets downloaded.
The HttpCompletionOption doesn't really make much sense without doing this (apart from rejecting the response all-together based on the headers).

**Comment by stephentoub** [comment]
> But looking at the implementation, the moment you try and get the stream from the HttpContent, the entire stream is loaded into memory

That's not what that code is doing.

Is this issue based purely on that code inspection, or do you have a repro?

**Comment by dotMorten** [comment]
@stephentoub Code inspection:
Here it's read into a memory stream:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpContent.cs#L254
Or it'll hit `CreateContentReadStreamAsync` which in turn hits `LoadIntoBufferAsync(MaxBufferSize)`

But now inspecting internals, it looks like at least when running my .NET Core app on Windows, it replaces the content stream with something. Probably because this is abstract:
```cs
protected abstract Task SerializeToStreamAsync(Stream stream, TransportContext context);
```
