### ISSUE TITLE
DataContractSerializer omits properties when elements are not in alphabetical order 

### ISSUE THREAD

**Issue by digitalnoiz** [dotnet/corefx#28219]
When attempting to read an xml document using the DataContractSerializer a property may not be populated if the element name is alphabetically before the first element.

It is expected that element order should not affect deserialization.

ViewModel

    [DataContract]
    public class ViewModel
    {
        [DataMember] public string Beta { get; set; }
        [DataMember] public string Alpha { get; set; }
    }

example xml:

    <ViewModel xmlns="http://schemas.datacontract.org/2004/07/ExampleProg">
        <Beta>Beta</Beta>
        <Alpha>Alpha</Alpha>
    </ViewModel>

After reading the xml to a stream and passing it to `DataContractSerializer.ReadObject` the resulting ViewModel will be set to Beta = "Beta", Alpha = "".

If instead, the Alpha element is first, both properties are then set.

**Comment by huanwu** [comment]
@digitalnoiz This is by design. During serialization, properties of the data contract will get serialized in alphabetical order. Same for deserialization, the order of the members in the XML need be alphabetical.  If you want to manage the order of serialization/deserialization, you need to use Order attribute of DataMember. In your case, it will work if the class is like the following.

```
        [DataContract]
        public class ViewModel
        {
            [DataMember(Order=1)]
            public string Beta { get; set; }
            [DataMember (Order=2)]
            public string Alpha { get; set; }
        }
```

**Comment by digitalnoiz** [comment]
I have since confirmed this is by design and is documented at [docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/data-member-order](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/data-member-order). I had been attempting to use the DataContractSerializer for simple xml serialization and hadn't taken into account the specifications of the data members of the underlying data contract.

Thank you for your time.
