### ISSUE TITLE
Can Console class tell us if it IsTty?

### ISSUE THREAD

**Issue by kasper3** [dotnet/corefx#28221]
Reading this code https://github.com/Microsoft/msbuild/blob/6851538897f5d7b08024a6d8435bc44be5869e53/src/Deprecated/Engine/Logging/BaseConsoleLogger.cs#L411-L426,  it looks like information whether the console is redirected is useful for such scenarios. Other utilities written in .NET would could also utilitize this property to control colored output. Might be trickier to distinguish if it is a pseudo-tty (https://github.com/PowerShell/PowerShell/issues/6427). For now, perhaps `public bool IsTty { get; }`  addition to Console could be considered?

@rainersigwald

**Comment by stephentoub** [comment]
> it looks like information whether the console is redirected is useful for such scenarios

Console.IsInput/Output/ErrorRedirected?

**Comment by kasper3** [comment]
Yeah i guess those could be used instead of try-catching on BackgroundColor
