### ISSUE TITLE
Add stress tests for Span<T> APIs

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#28227]
From https://github.com/dotnet/corefxlab/issues/1313

- Tests with multiple threads to confirm that Span<T> APIs are stateless and thread safe
- Tests with lots of GC allocations to confirm that when GC moves addresses around, the use of Span is still correct

**Comment by jkotas** [comment]
You should just make sure that this is covered by the existing stress mixes run by the stress team (cc @valenis). There is no point in you building a separate stress harness for Span.

**Comment by bartonjs** [comment]
What I understand from @DrewScoggins is that the stress mixes will run `[Fact]` tests (but not, currently, `[Theory]` tests).

Span currently has many (~500) `[Fact]` tests and ~10 `[Theory]` methods, which are mostly on `AsSpan`, based on `src\System.Memory\tests\Span\*` as of 821f44ea4650f178f9ada3d85e54b1088a27e14d.

So I think we're in good shape.
