### ISSUE TITLE
Consolidate the string and span tests for the string-like APIs

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#28238]
See https://github.com/dotnet/corefx/pull/27319#discussion_r170049466 for additional details and context.

This way, all the tests will be in one place making it easier to maintain, rather than duplicated between assemblies. Consider moving them to Common as well and reference from System.Memory.csproj so that running System.Memory tests will run all the span related tests.

cc @tarekgh

**Comment by tarekgh** [comment]
why didn't you mark this one for 2.1?

**Comment by ahsonkhan** [comment]
> why didn't you mark this one for 2.1?

It did not seem very crucial, specifically for 2.1, given it is about moving tests around (doesn't bring up a test coverage gap, etc.). If you feel differently, please feel free to change it.

**Comment by ahsonkhan** [comment]
Partially fixed in https://github.com/dotnet/corefx/pull/28347

**Leftover for future:**
- Remove redundant span tests from System.Memory that were initially ported over from StringTests.
- Refactor the StringTests.cs to isolate these newly added span-based tests into a separate file (possibly moving them to Common) and reference them from System.Memory.Tests.csproj so that we can execute all relevant Span tests when running msbuild on S.M.T, rather than having to run tests from several places.
   - This will likely result in some code duplication.

**Comment by MarcoRossignoli** [comment]
@ahsonkhan the subject is the same?I could help with this.

**Comment by MarcoRossignoli** [comment]
@ahsonkhan  what does "S.M.T." stand for?

**Comment by MarcoRossignoli** [comment]
> Refactor the StringTests.cs to isolate these newly added span-based tests into a separate file (possibly moving them to Common) and reference them from System.Memory.Tests.csproj so that we can execute all relevant Span tests when running msbuild on S.M.T, rather than having to run tests from several places.
This will likely result in some code duplication.

Do you mean create StringTests.Span.cs under src\Common\tests\Tests\System and add reference to System.Memory.Tests. and System.Runtime.Tests?

**Comment by ahsonkhan** [comment]
> Do you mean create StringTests.Span.cs(`public partial class StringTestsSpan : RemoteExecutorTestBase`) under src\Common\tests\Tests\System and add reference to System.Memory.Tests and System.Runtime.Tests?

Yes.

> Do you mean remove tests from src\System.Memory\tests\Span(`Span<char>`) that are already present on src\System.Runtime\tests\System\StringTests.cs?If so, there are exactly same method name or i need to read every test code and try to find if there is same test on StringTests.cs?

Yes, remove the ones already moved to StringTestsSpan that you create in Common. Most have the same name, but some may not.

Let me give you an example. The following tests are essentially identical (and have the same name). The one in System.Memory is specific for spans only. The one in System.Runtime has both span and string. We should keep one copy of the input data and test (and move it to common) so that we only have to update it in one place.
https://github.com/dotnet/corefx/blob/master/src/System.Memory/tests/ReadOnlySpan/IndexOf.charSpan.cs#L62
https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/StringTests.cs#L1359

Other examples: [StartsWith](https://github.com/dotnet/corefx/blob/master/src/System.Memory/tests/ReadOnlySpan/StartsWith.StringComparison.cs), [EndsWith](https://github.com/dotnet/corefx/blob/master/src/System.Memory/tests/ReadOnlySpan/EndsWith.StringComparison.cs), [CompareTo](https://github.com/dotnet/corefx/blob/master/src/System.Memory/tests/ReadOnlySpan/CompareTo.cs), [Contains](https://github.com/dotnet/corefx/blob/master/src/System.Memory/tests/ReadOnlySpan/Contains.cs), [Equals](https://github.com/dotnet/corefx/blob/master/src/System.Memory/tests/ReadOnlySpan/Equals.cs), [ToLower](https://github.com/dotnet/corefx/blob/master/src/System.Memory/tests/ReadOnlySpan/ToLower.cs), [ToUpper](https://github.com/dotnet/corefx/blob/master/src/System.Memory/tests/ReadOnlySpan/ToUpper.cs),

**Comment by MarcoRossignoli** [comment]
@ahsonkhan do you like something like [this]( https://github.com/dotnet/corefx/compare/master...MarcoRossignoli:stmtostringtests)?
I mean, move all possible `Span<char>`  under `ReadOnlySpan` adding string test part, am I on the right track?

**Comment by ahsonkhan** [comment]
> @ahsonkhan do you like something like [this]( https://github.com/dotnet/corefx/compare/master...MarcoRossignoli:stmtostringtests)?
I mean, move all possible `Span<char>`  under `ReadOnlySpan` adding string test part, am I on the right track?

That looks good to me. In your example, this added a new string-based tests as well (borrowing from span), which is great. If in the process of moving the `ReadOnlySpan<char>` tests, you come across existing string-based tests, I would merge them together (just like you have it in your commit, and how we have existing stringtests today). Thanks.

**Comment by MarcoRossignoli** [comment]
let me know if there are other work to do on this!

**Comment by ahsonkhan** [comment]
Looks like this work item is done. All the duplicate span tests were moved to Common StringTests. Thanks @MarcoRossignoli 

@tarekgh, can you confirm?

**Comment by tarekgh** [comment]
I think we are good here. we can revisit if we see anything missing later.
