### ISSUE TITLE
Using SslStream to make an ALPN connection - confusion over parameters to use.

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#28230]
@bobuva commented on [Mon Mar 19 2018](https://github.com/dotnet/core/issues/1361)

I've updated to the .NET Core 2.1 preview in order to make an SSL connection. Our server requires an ALPN negotiation to occur. As I understand it, the preview is the first version of .NET Core to support ALPN.

Here is essentially what I'm doing:

``` 
TcpClient tcpClient = new TcpClient();
tcpClient.Connect(ProxyClient.TestUbuntuHost, ProxyClient.TestUbuntuPort);
var stream = tcpClient.GetStream();
SslStream sslStream = new SslStream(stream, false, new RemoteCertificateValidationCallback(ValidateServerCertificate));

X509Certificate2 certificate = new X509Certificate2(@"<a filename provided>);
X509Certificate2Collection certColl = new X509Certificate2Collection(certificate);
sslStream.AuthenticateAsClient(
                ProxyClient.TestUbuntuHost,
                certColl,
                SslProtocols.Tls11 | SslProtocols.Tls12, false);
```
The `ValidateServerCertificate` looks like this:
```
public static bool ValidateServerCertificate(
              object sender,
              X509Certificate certificate,
              X509Chain chain,
              SslPolicyErrors sslPolicyErrors)
{
            if (sslPolicyErrors == SslPolicyErrors.None)
                return true;

            Console.WriteLine("Certificate error: {0}", sslPolicyErrors);

            // Do not allow this client to communicate with unauthenticated servers.
            return false;
}
```
I get this error: ` System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.` whether or not I pass that 3rd param to the `SslStream` constructor. 

Can you shed some light on whether I need to do something else to enforce the ALPN negotiation?

Thanks, 
Bob

**Comment by davidsh** [comment]
You need to use this overload of `AuthenticateAsClient` in order to use ALPN.  And you need to set the ALPN in the property.

https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/ref/System.Net.Security.cs#L185

**Comment by bobuva** [comment]
Thanks David! I'll give it a try.

**Comment by bobuva** [comment]
@davidsh I tried that as shown below, but still get the remote certificate is invalid error.

```
            TcpClient tcpClient = new TcpClient();
            Task task = tcpClient.ConnectAsync(ProxyClient.TestUbuntuHost, ProxyClient.TestUbuntuPort);
            await task;

            SslStream sslStream = new SslStream(tcpClient.GetStream(), false, new RemoteCertificateValidationCallback(ValidateServerCertificate));
            
            SslClientAuthenticationOptions authOptions = new SslClientAuthenticationOptions();
            authOptions.ApplicationProtocols = new List<SslApplicationProtocol>() { SslApplicationProtocol.Http11, SslApplicationProtocol.Http2 };
            authOptions.EnabledSslProtocols = SslProtocols.Tls12;
            authOptions.TargetHost = ProxyClient.TestUbuntuHost;

            await sslStream.AuthenticateAsClientAsync(authOptions, new CancellationToken(false));

```

**Comment by karelz** [comment]
Did you try to set up `authOptions.RemoteCertificateValidationCallback`?
https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/ref/System.Net.Security.cs#L113-L124

It's possible we may need to validate the constructor arguments when the new overloads are used ... I vaguely remember we discussed that a bit.

**Comment by bobuva** [comment]
@karelz yes I did. I set it up to point to a validation function -- see my original post above (copied by Peter to this issue).

**Comment by karelz** [comment]
@bobuva your original post does not set `authOptions.RemoteCertificateValidationCallback`. It uses constructor overload. Don't use it. Use plain constructor + `AuthenticateAsClientAsync`.

**Comment by bobuva** [comment]
Hi @karelz,

Oh, yes, I used to pass it through the constructor, but I had already changed it to pass it through the `authOptions.RemoteCertificateValidationCallback`. I still had the same problem.

**Comment by bobuva** [comment]
I also assume that `X509Certificate2` is acceptable (interchangeable with `X509Certificate`).

**Comment by karelz** [comment]
There seems to be confusion around what was tried, how, etc. Can you please post final code sample, based on the recommendations above that still fails for you?
Can you check if the callback is invoked at all?

**Comment by bobuva** [comment]
Ok, I'll package it up for you. Thanks!

**Comment by bobuva** [comment]
@karelz I think I have the ALPN negotiation working. I'm using GRPC for data communications and it appears now that is where my bottleneck lies. Can you tell me if this sample code for SSL ALPN looks as it should? https://gist.github.com/bobuva/0026b8760a44b9c4e60f4649978f1766

**Comment by karelz** [comment]
Yep, it looks as what I would expect - if it works great.
What was the problem with your previous attempts? Is there something we should change / document?

**Comment by bobuva** [comment]
Here is a image of what I'm seeing in Wireshark, starting with the `Client Hello`. After what appears to be a successful handshake (including ALPN negotiation), my client apparently is sending a RST (reset) and I don't know why. Maybe it's just TCP cleaning up?

![image](https://user-images.githubusercontent.com/60141/37736787-0fec1c8a-2d0f-11e8-9feb-bd5f3168714b.png)

**Comment by karelz** [comment]
What kind of problems is it causing? Does it drop the connection?

**Comment by bobuva** [comment]
After making the SSL connection, I create a grpc channel and send a message awaiting a response. I get a `Grpc.Core.RpcException` indicating that the stream was removed (it does bi-directional streams). `tcpview` shows the connection as having been `Established`, so I think it remains connected until I close the program. I bubble up the exception to the UI so I can see it immediately.

**Comment by bobuva** [comment]
Interesting... I'm now not getting the `[RST, ACK]` that's the last entry in the Wireshark output shown earlier! Trying to figure out if it was a small change I just made or not...

**Comment by bobuva** [comment]
We are still investigating but it appears that the SSL handshake is not finishing with a completion.

**Comment by bobuva** [comment]
@karelz It turns out that creating a `TcpClient` object and connecting using that was unnecessary since the `grpc` implementation was creating the connection itself. Being new to `grpc`, I didn't realize that, and the `grpc` sample files misled me. Maybe I'll reach out to them on that. In any case, I'm able to make the SSL/ALPN connection (via grpc).

**Comment by karelz** [comment]
OK, sounds like we can close it here then.

Yet another example how minimal repro with unnecessary dependencies is valuable to route issues :)

**Comment by RobertToy** [comment]
Hi,

I've got a class library project in Visual Studio 2017 set to netcoreapp2.1 and the latest version (2.1.3) of the CORE SDK installed and referenced in my project, and I'm trying the following code but I cannot get it to use the ALPN protocol extensions.  Note that I'm constructing a new protocol (used for connection to amazon IoT over port 443 for mqtt data) to add to the list in the example, but it still doesn't work even if I use one of the defaults, like http2.

```
TcpClient tcpClient = new TcpClient();
Task task = tcpClient.ConnectAsync(IotEndpoint, 443); // IotEndpoint is my amazon endpoint.
await task;
 
SslStream sslStream = new SslStream(tcpClient.GetStream(), false);
 
X509Certificate2 certificate = new X509Certificate2(PathtoPFXFile, PFXPassword);
X509Certificate2Collection certColl = new X509Certificate2Collection(certificate);
 
SslApplicationProtocol amzProtocol = new SslApplicationProtocol("x-amzn-mqtt-ca");
SslClientAuthenticationOptions authOptions = new SslClientAuthenticationOptions();
authOptions.ApplicationProtocols = new List<SslApplicationProtocol>() { amzProtocol };            authOptions.EnabledSslProtocols = SslProtocols.Tls12;
authOptions.TargetHost = IotEndpoint;
authOptions.AllowRenegotiation = true;
authOptions.ClientCertificates = certColl;
authOptions.EncryptionPolicy = EncryptionPolicy.RequireEncryption;
authOptions.RemoteCertificateValidationCallback = new RemoteCertificateValidationCallback(ValidateServerCertificate);
 
await sslStream.AuthenticateAsClientAsync(authOptions, new CancellationToken(false));
```

Wireshark shows the connection happening and all of the handshaking going on and finishing, but wireshark does not show the ALPN protocol negotiations (the extensions on the Client Hello message) and it connects using http instead of mqtt protocol which is what I need.

Regards,

**Comment by RobertToy** [comment]
Sorry.  I've opened a new issue for this.
