### ISSUE TITLE
error MSB3073: The command "python in CI

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#28246]
09:06:21   System.IO.FileSystem.Watcher.Tests -> /mnt/j/workspace/dotnet_corefx/master/alpine-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/bin/Linux.AnyCPU.Debug/System.IO.FileSystem.Watcher.Tests/netstandard/System.IO.FileSystem.Watcher.Tests.dll
09:06:21   Traceback (most recent call last):
09:06:21     File "/mnt/j/workspace/dotnet_corefx/master/alpine-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/Tools/DumplingHelper.py", line 131, in <module>
09:06:21       main(sys.argv)
09:06:21     File "/mnt/j/workspace/dotnet_corefx/master/alpine-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/Tools/DumplingHelper.py", line 113, in main
09:06:21       install_dumpling()
09:06:21     File "/mnt/j/workspace/dotnet_corefx/master/alpine-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/Tools/DumplingHelper.py", line 34, in install_dumpling
09:06:21       print("An unexpected error was encountered while installing dumpling.py: " + sys.exc_info()[0])
09:06:21   TypeError: cannot concatenate 'str' and 'type' objects
09:06:21 /mnt/j/workspace/dotnet_corefx/master/alpine-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/Tools/Dumpling.targets(30,5): error MSB3073: The command "python /mnt/j/workspace/dotnet_corefx/master/alpine-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/Tools/DumplingHelper.py install_dumpling" exited with code 1. [/mnt/j/workspace/dotnet_corefx/master/alpine-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/tests.builds]
09:06:21 
09:06:21 Build FAILED.
09:06:21 

https://ci3.dot.net/job/dotnet_corefx/job/master/job/alpine-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/3923/console
https://ci3.dot.net/job/dotnet_corefx/job/master/job/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/10038/console

**Comment by danmosemsft** [comment]
https://github.com/dotnet/buildtools/pull/1969
