### ISSUE TITLE
CI Build step 'Execute shell' marked build as failure

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#28247]
09:35:37 [ubuntu16.04_arm64_cross_debug_prtest] $ /bin/sh -xe /tmp/jenkins6999066973616382871.sh
09:35:37 + tar -czf bin/build.tar.gz --directory=bin/runtime/netcoreapp-Linux-Debug-arm64 .
09:35:37 tar: bin/runtime/netcoreapp-Linux-Debug-arm64: Cannot open: No such file or directory
09:35:37 tar: Error is not recoverable: exiting now
09:35:37 
Build step 'Execute shell' marked build as failure

https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu16.04_arm64_cross_debug_prtest/11/consoleFull#-8536224876a086b3e-df04-41d2-bc4d-43e8f9406d07

**Comment by danmosemsft** [comment]
@sdmaclea do you have context?

**Comment by sdmaclea** [comment]
arm64 CI jobs were just enabled.  We ran "@dotnet-bot test ci please", but no one tried to trigger the newly generated jobs.

**Comment by kasper3** [comment]
`tar --directory dest` requires dest to be present, i.e. `mkdir dest` before `tar --directory dest`.

**Comment by sdmaclea** [comment]
@kasper3 The path is blatantly wrong.  I must have made a cut/paste error when I added it.
