### ISSUE TITLE
ReadOnlySequence's Enumerator returns different results for same struct.

### ISSUE THREAD

**Issue by jkotalik** [dotnet/corefx#28251]
Repro:
I am using Pipelines to obtain a ReadOnlySequence from a PipeReader. I am then iterating over the number of chunks in the buffer to count the buffer size, and then iterating again to add them into an array. Something like:

```C#
var pipe = new Pipe(new SlabMemoryPool());

...
var readResult = pipe.Reader.ReadAsync();
var readOnlySequence = readResult.Buffer;
var nChunks = 0;

for (var memory in readOnlySequence)
{
    nChunks++;
}

var handles = new MemoryHandle[nChunks];
var currentChunk = 0;

for (var memory in readOnlySequence)
{
    handles[currentChunk] = new MemoryHandle();
    currentChunk++;
}
```

The writer to the pipe is writing and flushing memory in a loop:
```c#
pipe.Writer.Write(buffer);
pipe.Writer.FlushAsync();
```

My hypothesis is that the enumerator is skipping empty segments somehow.
cc/ @pakrym  @davidfowl

**Comment by jkotalik** [comment]
Seems to only occur when the ReadOnlySequence's chunk size is full (Ex writing 4096 bytes at a time).

**Comment by benaadams** [comment]
Can you provide more info?
```csharp

for (var memory in readOnlySequence)
{
    ref var handle = ref handles[currentChunk]; // IndexOutOfBoundsException occurs here.
}
```
`currentChunk` is always `0` and its accessing an array with nothing set rather than accessing `readOnlySequence`?

**Comment by jkotalik** [comment]
Sorry, forgot to increment. Fixed in example.

**Comment by pakrym** [comment]
It didn't repro with exactly such code. My futile attempts to repro: https://github.com/pakrym/corefx/commit/778fb5859534949535fc6309e1d302ae9ece8b79

**Comment by pakrym** [comment]
Reproed by https://github.com/pakrym/corefx/commit/9dc3fbda05940222ac8f82ab12ca1e3258c863e5#diff-189d999cfee30003f64a57258ee0451e
