### ISSUE TITLE
Add Path.TryGetRandomFileName()

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#28256]
From API proposal #27418.

Need to add:

``` C#
namespace System.IO
{
    public static class Path
    {
        public static bool TryGetRandomFileName(Span<char> destination, out int charsWritten);
    }
}
```

Returns false if the destination isn't large enough to fit the full path into.

**Comment by jkotas** [comment]
See my comment https://github.com/dotnet/corefx/issues/28255#issuecomment-375080407

I do not think we should be adding this API.

**Comment by JeremyKuhne** [comment]
> I do not think we should be adding this API.

I disagree. This is used a lot to build larger paths. I would agree with you if you were talking `GetTempFileName()`.  All of the APIs that were in #27418 are used for composing larger paths.

**Comment by jkotas** [comment]
It would help if you show me a profile from msbuild or something that shows creating temporary filenames or paths is a significant source of allocation, and reducing them will make a significant difference.

I do not think we should be blindly adding a no-allocation version of every API that returns string. There is a threshold after which it becomes negative value. This API is above that treashold for me. I can be convinced about the apposite with data.

**Comment by JeremyKuhne** [comment]
> I do not think we should be blindly adding a no-allocation version of every API that returns string.

I agree with you in principle, but this is not a blind adding. We have a number of no-allocation APIs that are used to compose larger paths. We want to provide a consistent no-allocation route for building these. If these were not part of a larger story, were complicated to implement, etc. they would fall below the line for me as well.

**Comment by jkotas** [comment]
The story without the no-allocation way to get temporary path would be as much as consistent as with them. I do not think they are making the story more consistent.

**Comment by JeremyKuhne** [comment]
> The story without the no-allocation way to get temporary path would be as much as consistent as with them.

Other than you are forced to allocate. We can't cache the temporary path without breaking people, others may be in the same boat.

**Comment by JeremyKuhne** [comment]
Closing until we re-review the API proposal.
