### ISSUE TITLE
Add Path.TryGetTempPath()

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#28255]
From API proposal #27418.

Need to add:

``` C#
namespace System.IO
{
    public static class Path
    {
        public static bool TryGetTempPath(Span<char> destination, out int charsWritten);
    }
}
```

Returns false if the destination isn't large enough to fit the full path into.

**Comment by MarcoRossignoli** [comment]
@JeremyKuhne if you want i can start with this, feel free to assign to me if you want.

**Comment by jkotas** [comment]
@JeremyKuhne Do we have examples of where the no-allocation version of this API makes a difference?

You are about to create a temporary file. Creating a temporary file is orders of magnitude more expensive operation than just allocating a string.

I think the no-allocation version of these APIs are adding negative value to the platform.

**Comment by jkotas** [comment]
(Add `Path.TryGetRelativePath()` and `Path.TryGetFullPath()` are fine.)

**Comment by JeremyKuhne** [comment]
Closing for now until we re-review the API proposal.
