### ISSUE TITLE
Add Path.TryGetFullPath()

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#28258]
From API proposal #27418.

Need to add:

``` C#
namespace System.IO
{
    public static class Path
    {
        public static bool TryGetFullPath(ReadOnlySpan<char> path, Span<char> destination, out int charsWritten);
        public static bool TryGetFullPath(ReadOnlySpan<char> path, ReadOnlySpan<char> basePath, Span<char> destination, out int charsWritten);
    }
}
```

Returns false if the destination isn't large enough to fit the full path into.

**Comment by jkotas** [comment]
See my comment https://github.com/dotnet/corefx/issues/28255#issuecomment-375080407

I do not think we should be adding this API.

**Comment by JeremyKuhne** [comment]
Closing for now until we get the original proposal re-reviewed.
