### ISSUE TITLE
Microsoft.Tpl.Dataflow does not contain assembly reference for .NET version 4

### ISSUE THREAD

**Issue by oneilj** [dotnet/corefx#28271]
Hi, I am in need of a version of dataflow that targets .net version 4. This is the error I get when I try to install Microsoft.Tpl.Dataflow or System.Threading.Tasks.Dataflow.
``` Could not install package 'Microsoft.Tpl.Dataflow 4.5.8'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.```

**Comment by danmosemsft** [comment]
@weshaggard any context?

**Comment by weshaggard** [comment]
It is a feature request for the package. The owner should decide if they can support it there and want to add the configurations.

**Comment by kouvel** [comment]
@AlexGhiondea

**Comment by tarekgh** [comment]
@oneilj  can you use System.Threading.Tasks.Dataflow package and target at least 4.5? this is the min version of the supported framework.

**Comment by oneilj** [comment]
Yeah, that's what i ended up doing
