### ISSUE TITLE
Some enhancements for  existing classes

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/corefx#28285]
Since there is many enhancements in the framework these days, I suggest to review all existing classes and update them to benefit from new features, such as:
-	methods that receive objects and/or return objects can use generics.
-	methods that have out parameters can have overloads that return ValueTuples
-	All properties and parameters that only deal with positive numbers like Lengths, widths, heights, can be modified to use uint instead of int (same for other signed types). This will eliminate the need checks for raising exceptions for negative values, because the compiler can discover this in design time, or the cast will raise an exception in runtime. Also, Unsigned types have a double range than signed types.
-	Add some Deconstructors to classes.
-	The Math.Min and Math.Max can have a param array to allow compare three or more elements. Perhaps you can add some more math functions like factorial, sum, avg..... etc.
-	and so on….
and so on.
I think most of these changes will not break any code. But I don't see any problem in breaking changes as long as they are for the best. Besides, one can always choose to run old projects on old frameworks version.

**Comment by ahsonkhan** [comment]
> But I don't see any problem in breaking changes as long as they are for the best. Besides, one can always choose to run old projects on old frameworks version.

If the changes are internal/implementation detail, and not visible to the end user of the library, then we can make these changes. However, we can't modify the API surface of types that are publicly exposed or have already shipped.

@MohammadHamdyGhanem, it would be awesome if you could get us started by taking on some of these enhancements and submit a PR.

> methods that receive objects and/or return objects can use generics.
> methods that have out parameters can have overloads that return ValueTuples

Can you provide specific examples of changes you had in mind?

**Comment by tarekgh** [comment]
@MohammadHamdyGhanem I am going to close this issue and feel free to open a new issue with specific cases you see we need to enhance. The design committee went through this exercise of the new APIs exposed in 2.1. We cannot change the old APIs though. even if you think net core is side by side, but we don't want to break the libraries depend on the old behavior and can be used with the apps targeting the new net core versions. thanks for your report and waiting for your specific issues.
