### ISSUE TITLE
Linux/OSX - setting ExclusiveAddressUse or DontLinger not supported

### ISSUE THREAD

**Issue by luigiberrettini** [dotnet/corefx#28305]
Operation not supported exception when [using SetSocketOption](https://github.com/graffen/NLog.Targets.Syslog/blob/v5.0.0-beta-02/src/NLog.Targets.Syslog/MessageSend/Tcp.cs#L82-L86) to set ExclusiveAddressUse or DontLinger:
```csharp
tcp.Client.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ExclusiveAddressUse, true);
tcp.Client.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.DontLinger, false);
tcp.Client.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.Linger, new LingerOption(true, 0));
tcp.Client.IOControl(IOControlCode.KeepAliveValues, keepAlive.ToByteArray(), null);
```
Please look at https://github.com/graffen/NLog.Targets.Syslog/issues/119 for more info

**Comment by stephentoub** [comment]
It would be better to use the Socket properties for these, namely Socket.ExclusiveAddressUse and Socket.LingerState.

That said, ExclusiveAddressUse wasn't enabled on Unix in .NET Core 2.0 and earlier, by design.  .NET Core 2.1 improves on this with https://github.com/dotnet/corefx/pull/24809.

**Comment by luigiberrettini** [comment]
Does Socket.LingerState also set DoNotLinger to false?

Given a .NET Standard version, I thought that, building against a set of target frameworks that implement it, meant supporting all the features of that version on each platform the framework was installable on.

At the moment docs are quite confusing, because they do not warn develoers about platform specific issues and they suggest to see the Windows Sockets API even if the selected API is .NET Standard or .NET Core:
https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.setsocketoption?view=netstandard-2.0#System_Net_Sockets_Socket_SetSocketOption_System_Net_Sockets_SocketOptionLevel_System_Net_Sockets_SocketOptionName_System_Int32_

**Comment by stephentoub** [comment]
> Does Socket.LingerState also set DoNotLinger to false?

LingerState is of type LingerOption, which has an Enabled property (and ctor argument) that controls whether linger is enabled or disabled.

**Comment by wfurt** [comment]
It seems like the linked issue was closed. Shall we close this as well @luigiberrettini ?

**Comment by luigiberrettini** [comment]
This issue can be closed but not because the linked issue was closed: I used workarounds to cover what is not currently covered by the framework
