### ISSUE TITLE
Support exporting cryptographic keys to PEM format.

### ISSUE THREAD

**Issue by stebet** [dotnet/corefx#28303]
It would be very helpful to add the functionality to most of the asymmetric cryptographic algorithm implementations to add an explicit method to both import and export the cryptographic keys to the PEM file format.

We already have ```ToXmlString``` and ```FromXmlString``` on the [AsymmetricAlgorithm](https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/AsymmetricAlgorithm.cs) base class
so adding a ```ToPemString``` and ```FromPemString``` would make sense to me at least.

I realize PEM is not exactly a standard format but it is being used extensively as format for encryption/signature keys in many utilities (like openssl) so supporting it for at least most common algorithms (RSA, ECDsa, X509, DSA, PKCS7, PKCS8) seems like a logical thing to do with .NET now being cross-platform.

The current format is mostly dictated by [RFC 7468](https://tools.ietf.org/html/rfc7468) as well as [OpenSSL's PEM handling](https://github.com/openssl/openssl/blob/master/include/openssl/pem.h).

**Comment by bartonjs** [comment]
This is covered under the desire for https://github.com/dotnet/corefx/issues/20414.

* RSA PKCS1
* PKCS8 (RSA, DSA, ECDSA)
* Encrypted PKCS8 (RSA, DSA, ECDSA)

And probably an "as PEM" or "as DER" (and maybe an "I'll guess")

It says import, but also intend an export.  If you're concerned that it won't address something, please feel encouraged to comment there.

**Comment by stebet** [comment]
Nice catch @bartonjs. I hadn't seen that issue. I'll add my comments there if needed. Thank you.
