### ISSUE TITLE
[Arm64/Linux] Framework packaging is not quite correct

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/corefx#28333]
I just took a look at 
```
./bin/packages/Debug/reports/runtime.linux-arm64.Microsoft.Private.CoreFx.NETCoreApp.json
```

Looks like things are OK for v2.1
```
    ".NETCoreApp,Version=v2.1/linux-arm64": {
      "Framework": ".NETCoreApp,Version=v2.1",
      "RuntimeID": "linux-arm64",
      "CompileAssets": [
        {
          "LocalPath": "/home/sdmaclea/git/corefx/Tools/_._",
          "PackagePath": "ref/netstandard/_._"
        }
      ],
      "RuntimeAssets": [
        {
          "LocalPath": "/home/sdmaclea/git/corefx/bin/AnyOS.AnyCPU.Debug/Microsoft.CSharp/netstandard/Microsoft.CSharp.dll",
          "PackagePath": "runtimes/linux-arm64/lib/netcoreapp2.1/Microsoft.CSharp.dll",
          "TargetFramework": ".NETCoreApp,Version=v2.1",
          "Version": "4.0.4.0"
        },
```
But arm64 support is not mentioned as supported in earlier versions.

@jkotas

**Comment by sdmaclea** [comment]
Probably #21236 was wrong

**Comment by sdmaclea** [comment]
@janvorli Looks like a similar issue exists for `alpine.3.6-x64`  2.1 the only supported version.  Seems like it should be just as backward compatible as anyother Linux platform.

**Comment by janvorli** [comment]
@sdmaclea I am not sure I understand your last comment. We support alpine from 2.1 only, porting it back to 2.0 was not something we wanted to do.

**Comment by janvorli** [comment]
Do you want to enable arm64 support for 2.0 too? That would mean that you'd have to port all of the relevant arm64 changes to 2.0 first.

**Comment by sdmaclea** [comment]
It looks like when we build CoreFX 2.1 for Linux, the packages produced claim to support earlier NetStandard Versions.  They use the same native binaries as far as I can tell.

Not sure it would just work for arm64 and alpine too.

**Comment by sdmaclea** [comment]
i.e.
```
    ".NETCoreApp,Version=v2.0/ubuntu.16.10-x64": {
      "Framework": ".NETCoreApp,Version=v2.0",
      "RuntimeID": "ubuntu.16.10-x64",
      "CompileAssets": [
        {
          "LocalPath": "/home/sdmaclea/git/corefx/Tools/_._",
          "PackagePath": "ref/netstandard/_._"
        }
      ],
      "NativeAssets": [
        {
          "LocalPath": "/home/sdmaclea/git/corefx/bin/Linux.x64.Debug/native/System.IO.Compression.Native.a",
          "PackagePath": "runtimes/linux-x64/native/System.IO.Compression.Native.a"
        },
        {
          "LocalPath": "/home/sdmaclea/git/corefx/bin/Linux.x64.Debug/native/System.IO.Compression.Native.so",
          "PackagePath": "runtimes/linux-x64/native/System.IO.Compression.Native.so"
        },
```

**Comment by sdmaclea** [comment]
The 2.1 prerelease announcement video took time to emphasize it would support backwards compatibility, i.e. 2.0 apps.

**Comment by janvorli** [comment]
Where does the stuff in your previous comment come from? I've opened e.g. this nugget package: https://dotnet.myget.org/F/dotnet-core/api/v2/package/runtime.linux-x64.Microsoft.Private.CoreFx.NETCoreApp/4.5.0-preview3-26319-04 and it contains just netcoreapp2.1

**Comment by sdmaclea** [comment]
It came from my corefx build tree.  After I built arm64 and x64 packages
```
./bin/packages/Debug/reports/runtime.linux-arm64.Microsoft.Private.CoreFx.NETCoreApp.json
./bin/packages/Debug/reports/runtime.linux-x64.Microsoft.Private.CoreFx.NETCoreApp.json
```

**Comment by sdmaclea** [comment]
I was checking to see that the arm64 packages were built correctly.  The significant size difference caught my eye.

**Comment by janvorli** [comment]
This file doesn't seem to reflect what you've built locally, it is quite confusing. I can see e.g. this fragment on my Ubuntu 14.04. The files are definitely not compatible with dotnet core 1.0 and yet it lists them there. Moreover, before 2.0, there were no portable packages, so package for centos cannot be built or run on Ubuntu.
```json
 ".NETCoreApp,Version=v1.0/centos.7-x64": {
      "Framework": ".NETCoreApp,Version=v1.0",
      "RuntimeID": "centos.7-x64",
      "CompileAssets": [
        {
          "LocalPath": "/home/janvorli/git/corefx/Tools/_._",
          "PackagePath": "ref/netstandard/_._"
        }
      ],
      "NativeAssets": [
        {
          "LocalPath": "/home/janvorli/git/corefx/bin/Linux.x64.Debug/native/System.IO.Compression.Native.a",
          "PackagePath": "runtimes/linux-x64/native/System.IO.Compression.Native.a"
        },
        {
          "LocalPath": "/home/janvorli/git/corefx/bin/Linux.x64.Debug/native/System.IO.Compression.Native.so",
          "PackagePath": "runtimes/linux-x64/native/System.IO.Compression.Native.so"
        },
```

**Comment by sdmaclea** [comment]
So should I close this?

**Comment by janvorli** [comment]
@eerhardt could you please help us understand the bin/packages/Debug/reports/runtime.linux-x64.Microsoft.Private.CoreFx.NETCoreApp.json contents? It seems to have entries for all versions of dotnet framework and native assets seemingly pointing to a local build of corefx stuff that was only built in the master branch for a different distro. See a fragment in my comment above.

**Comment by eerhardt** [comment]
I'm not sure myself.  @ericstj @weshaggard - do you have ideas to why these `reports` files contain extra info?

**Comment by ericstj** [comment]
The reports are emitted when we build packages.  We evaluate the package *as-if* it were installed in all types of frameworks and emit what would be resolved if the package were directly installed there.  These act as a debugging tool to get comprehensive view of a package's behavior across many framework/RID combinations.  For these runtime packages it's less useful since we don't design them to be installed directly (and recommend against it in the package spec) and they get constrained by runtime.json as to where they actually install.

> This file doesn't seem to reflect what you've built locally, it is quite confusing

That's not true.  It may not make sense WRT to the locally built framework version but it should map 1:1 with the package you've built locally.

**Comment by sdmaclea** [comment]
Closing this because it appears to be functioning as intended
