### ISSUE TITLE
Port being stripped off Host header in HttpRequestMessage constructed by HttpWebRequest

### ISSUE THREAD

**Issue by twgraham** [dotnet/corefx#28344]
Following investigations into restsharp/RestSharp#1085, it appears that the Host header `HttpRequestMessage` constructed by `HttpWebRequest.SendRequest()` is being stripped of the port. This is evident [here](https://github.com/dotnet/corefx/blob/3dc80d215591fca7b4991ed3e60fc4ddb8e0d460/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs#L1166) where only the Host of the URI is used, regardless whether or not the port is populated on the URI. This goes against the [HTTP spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23) which respects the use of ports in the host header.

**Comment by davidsh** [comment]
Regarding this code you cited in HttpWebRequest code:

```c#
if (_hostUri != null)
{
    request.Headers.Host = _hostUri.Host;
}
```

You're right that it probably should be something like this:

if (_hostUri != null)
{
    request.Headers.Host = _hostUri.Host + ":" + _hostUri.Port;
}
```

We do recommend, however, that developers use the HttpClient APIs instead of the older HttpWebRequest APIs.  On .NET Core, the performance of HttpWebRequest is sub-optimal since it is a layer over HttpClient and is provided as a compat-level API for legacy applications.

**Comment by davidsh** [comment]
cc: @karelz

**Comment by karelz** [comment]
This is result of early dogfooding of our bits. I asked the original thread if we know if it is a regression (in 2.0, 2.1, against Desktop, or Linux vs. Windows)
@caesar1995 can you please help reproduce it?

**Comment by davidsh** [comment]
Looking at the release/2.0.0 source code, this bug existed in 2.0 release as well.

**Comment by karelz** [comment]
Ah, I missed the code reference earlier - should be fairly simple to fix. Looks like a compat problem against .NET Framework.
