### ISSUE TITLE
StringFormat curly brace escaping error

### ISSUE THREAD

**Issue by cshaar** [dotnet/corefx#28341]

**Comment by cshaar** [comment]
Run the following code and you get the followin output{
0
0
{0}
{}
namespace myApp
{
    class Program
    {
        static void Main()
        {
           Console.WriteLine(String.Format("{0}",0));  // no format string
           Console.WriteLine(String.Format("{0:}",0)); // no format string with colon
           Console.WriteLine(String.Format("{{{0}}}",0)); // no format string with escaped curly brace
           Console.WriteLine(String.Format("{{{0:}}}",0)); // no format string with escaped curly brace
        }
    }
}

**Comment by joshfree** [comment]
@cshaar this is by design with how String Format handles escaped curly braces during processing. 

The ```string s = String.Format("{{{0:N}}}", i);   //prints '{N}'``` example at https://blogs.msdn.microsoft.com/brada/2004/01/14/string-formatting-faq/ provides more details.
