### ISSUE TITLE
Add method for calculating relative paths

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#2836]
It would be great if this super common functionality could be added to the path class. Using URI feels hacky to do this anyways.

Related https://github.com/dotnet/corefx/issues/1745

**Comment by BrennanConroy** [comment]
@joshfree

**Comment by joshfree** [comment]
@JeremyKuhne could you take a look here after your long path feature?

**Comment by JeremyKuhne** [comment]
@davidfowl To make sure I'm clear- you want something like Uri.MakeRelativeUri? Something like Path.MakeRelativePath(string sourcePath, string destinationPath)?

**Comment by davidfowl** [comment]
Yep! Here's what we implemented in our helper code:

https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Runtime/NuGet/Utility/PathUtility.cs#L73

**Comment by davidfowl** [comment]
@JeremyKuhne do you guys plan to add this?

**Comment by JeremyKuhne** [comment]
We intend to do this. I'll try and move on it for the next release.

**Comment by jasonwilliams200OK** [comment]
@davidfowl, should this be closed in favor of #6191?

**Comment by piotrpMSFT** [comment]
@joshfree @weshaggard we are starting to hit this issue while porting CLI build to MSBuild while calculating relative paths. This scenario will only become more frequent in the months to come. Do you have more information regarding when this will get fixed?

**Comment by weshaggard** [comment]
This isn't very high on our priority list right now, so we don't have a ETA. What part are you running into? The fact that MSBUILD::MakeRelative fails or just the lack of having this API? I would have expected this to be an issue even before the msbuild switch how are were you handling it before?

**Comment by eerhardt** [comment]
> What part are you running into? 

We ran into this issue because MSBUILD::MakeRelative fails.  If that API doesn't work on Unix, then the whole API is useless in x-plat scenarios, and anyone who wants to use it will be forced to do workarounds.

**Comment by weshaggard** [comment]
@JeremyKuhne is there any easy way to implement this in a cross-platform way without too much code or a new public API right now?

**Comment by BrennanConroy** [comment]
CLI uses this currently pending a new API https://github.com/dotnet/cli/blob/04f40f906dce2678d80fb9787e68de76ee6bf57e/src/Microsoft.DotNet.Cli.Utils/PathUtility.cs#L94

**Comment by JeremyKuhne** [comment]
I'll get something together for v.next that you can copy in the interim.

**Comment by brthor** [comment]
👍

**Comment by JeremyKuhne** [comment]
I've added a bit of code to #6191. Let's move the discussion there to settle on the API behavior.
