### ISSUE TITLE
SocketsHttpHandler will attempt digest authentication with an empty nonce

### ISSUE THREAD

**Issue by rmkerr** [dotnet/corefx#28378]
The nonce is an important part of the digest authentication protocol, and we should not attempt to authenticate without one. We currently have some incorrect test cases demonstrating this issue that pass only on SocketsHttpHandler:
https://github.com/dotnet/corefx/blob/ce4ebdfbf2080a38855ab8df5c9bb553db8724af/src/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs#L561-L565

Without a nonce digest authentication is vulnerable to [replay attacks](https://security.stackexchange.com/questions/3001/what-is-the-use-of-a-client-nonce/3024#3024). For this to actually occur the server requesting authentication would have to fail to send the nonce in the first place, but this is still an insecure scenario that we should not support.

Since it also requires insecure behavior from the server requesting authentication I think we can probably put this issue off until after 2.1, but I'd like to hear what others think first.

**Comment by davidsh** [comment]
>Since it also requires insecure behavior from the server requesting authentication

This means we should fix it in 2.1.

**Comment by davidsh** [comment]
cc: @karelz @stephentoub @geoffkizer

**Comment by rmkerr** [comment]
The behavior I was seeing may actually be the result of another bug in the loopback server causing it to look like authentication was succeeding when it was not. I'll do some more investigation, but if that is the case I'll close this issue. Sorry for the noise.

**Comment by rmkerr** [comment]
Looks like my initial analysis of this issue was wrong. Closing.
