### ISSUE TITLE
LoadedFiles_NonStaticallyReferencedAssembly fails in CI with NotEmptyException

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#28398]
From https://github.com/dotnet/corefx/pull/28320

OSX.1012.Amd64.Open-x64-Debug
https://mc.dot.net/#/user/sputier/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/47503888725962aaad41a7b1384de12938aae16c/workItem/System.ComponentModel.Composition.Tests/analysis/xunit/System.ComponentModel.Composition.DirectoryCatalogTests~2FLoadedFiles_NonStaticallyReferencedAssembly

```text
Unhandled Exception of Type Xunit.Sdk.NotEmptyException
Message :
Assert.NotEmpty() Failure
Stack Trace :
   at System.ComponentModel.Composition.DirectoryCatalogTests.LoadedFiles_NonStaticallyReferencedAssembly() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.ComponentModel.Composition/tests/System/ComponentModel/Composition/Hosting/DirectoryCatalogTests.cs:line 356
```

**Comment by safern** [comment]
This test was just added here: https://github.com/dotnet/corefx/pull/28173/files

@MarcoRossignoli would you mind taking a look?

**Comment by MarcoRossignoli** [comment]
@safern @ahsonkhan sorry for delay(in my timezone i was in bed,  inefficiencies of the human body). It's weird in last CI i saw no issue:
https://ci3.dot.net/job/dotnet_corefx/job/master/job/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/10268/
(unrelated System.Net.Sockets.Tests).
I'm in trouble, i can dev/test code on Win and Ubuntu(VM) but i don't have a OSX.
Do you have advice?

**Comment by danmosemsft** [comment]
Has this happened again?

**Comment by safern** [comment]
I haven't seen it, and no one has reported it. I will try to repro it locally on my mac, if it doesn't repro, I'll close it.

**Comment by MarcoRossignoli** [comment]
@safern TYVM i apologize!

**Comment by MarcoRossignoli** [comment]
@safern @danmosemsft i stole a mac, i tested `System.ComponentModel.Composition.Tests` with `../../../Tools/msbuild.sh /v:m /t:rebuildandtest /p:OSGroup=OSX /p:ConfigurationGroup=Debug /p:ArchGroup=x64` i didn't get any fail.

**Comment by safern** [comment]
I've ran this multiple times on my mac and haven't been able to repro... also it's been a week already and we haven't had any reports of this failing again on CI. I will close it and if we see it again then we can re-open and try to use the repro tool.

**Comment by MarcoRossignoli** [comment]
@safern "repro tools"?

**Comment by benaadams** [comment]
Occurred again https://github.com/dotnet/corefx/pull/28643#issuecomment-377766657

**Comment by benaadams** [comment]
https://mc.dot.net/#/user/benaadams/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/1ec79ef0959dcb61a9455e4ffef1dbcd1bc6788c/workItem/System.ComponentModel.Composition.Tests/analysis/xunit/System.ComponentModel.Composition.DirectoryCatalogTests~2FLoadedFiles_NonStaticallyReferencedAssembly

**Comment by MarcoRossignoli** [comment]
@safern can i help with "repro tools" somehow?I'm curious to understand what happen, maybe some overlapped test remove [copied file](https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Composition/tests/System/ComponentModel/Composition/Hosting/DirectoryCatalogTests.cs#L354) in tmp dir for some reason.

**Comment by karelz** [comment]
Late reopening - marking as Post-ZBB

**Comment by danmosemsft** [comment]
@safern this is still in 2.1. I suggest moving it to 2.2 unless you have a plan/reason to look now.

**Comment by safern** [comment]
It seems super flaky, I even tried repro tool and it didn’t repro. I think it has to do with the paths where for some reason it is getting a locked file and not able to load the assembly because of that. So I think moving to 2.2 is fine.

**Comment by MarcoRossignoli** [comment]
@safern if I can help you somehow, i'm here.

**Comment by safern** [comment]
@danmosemsft have you seen this fail again?

**Comment by danmosemsft** [comment]
Closing for now then.
