### ISSUE TITLE
Segmentation fault (core dumped) with microsoft/dotnet:2.0-runtime-stretch-arm32v7

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/corefx#28418]
@Zuendelmeister commented on [Fri Mar 23 2018](https://github.com/dotnet/dotnet-docker/issues/443)

## Steps to reproduce the issue
1. Install docker ce on a raspberry pi 3 
2. Start microsoft/dotnet:2.0-runtime-stretch-arm32v7 container with dotnet core code. Code uses http client that sends via post to a rest endpoint several times.
3. Code:
```c#
            var request = new HttpRequestMessage
            {
                RequestUri = new Uri(_url),
                Method = HttpMethod.Post,
                Headers ={
                    {HttpRequestHeader.Authorization.ToString(),_auth},
                    {HttpRequestHeader.ContentType.ToString(),"application/json"}
                },
                Content = new StringContent(messageData)
            };
            using (var handler = new HttpClientHandler
            {
                ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => true,
                UseProxy = false
            })
            {
                using (var httpClient = new HttpClient(handler)
                {
                    BaseAddress = new Uri(_url)
                })
                {
                    Console.WriteLine("start sending...");
                    var response =  await httpClient.SendAsync(request); //This is where the problem occurs!!!
                    Console.WriteLine($"Sending done: StatusCode: {response?.StatusCode}");
                }
            } 
```

## Expected behavior
The code should just send data to the rest endpoint.

## Actual behavior
It sends messages for a while (like 100) to the endpoint and dies with the error Segmentation fault (core dumped). This cannot be catched.

## Additional information (e.g. issue happens only occasionally)
On raspberry pi 3 with the docker base-image microsoft/dotnet:2.0-runtime-stretch-arm32v7.
I changed the baseimage and it works, so it's pretty save, that this issue is due to this one. Unfortunately I don't have any idea why.

## Output of `docker version`
```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:18:23 2018
 OS/Arch:       linux/arm
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:14:29 2018
  OS/Arch:      linux/arm
  Experimental: false

```

## Output of `docker info`

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1009-raspi2
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 920.1MiB
Name: 
ID: UUUL:DQMQ:S7ES:WMO6:QEWB:E7UW:FQEO:QG3S:AZO7:NBK4:B2OT:D7SI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 
 127.0.0.0/8
Live Restore Enabled: false

```

[EDIT] Add C# syntax highlighting by @karelz

**Comment by MichaelSimons** [comment]
This looks to be a general issue with the FX on raspberry pi rather than an issue specific to the microsoft/dotnet Docker image.

**Comment by karelz** [comment]
@Zuendelmeister can you try latest .NET Core 2.1? (Preview 1 - ideally also with the new stack)
If it still repros, please provide stack trace from the core dump.

**Comment by Zuendelmeister** [comment]
Hi you guys,
@MichaelSimons I also tried this on a 32Bit ARM machine (which is why I need the 32Bit Image) and had the same problem. 
@karelz I think these images are x64 based right? For the pi this is ok, but for my other machines not. Also I'd love to provide the stack trace from the core dump but don't know how to get this. In the code it is not even catchable.

Thanks you 2!
Best regards,
Zuendelmeister

**Comment by karelz** [comment]
@Zuendelmeister check out debugging steps on Linux via lldb & SOS - https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md

**Comment by kasper3** [comment]
Also `strace -f -o logfile dotnet /path/to/dll` or `strace -f -o logfile dotnet run` (it will be a huge log file, that can be shared through [github comment file attachment](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/)). It may require you to install `strace`: `apt install strace`.

You can also try latest preview of .NET Core 2.1 for arm32: `docker pull microsoft/dotnet:2.1-runtime-stretch-slim-arm32v7`.

**Comment by Zuendelmeister** [comment]
Thank you guys so much for these hints and the patience. It realy took me a while to find the time.
Here is the file. I hope this helps.

[CoreDumpLogFile.txt](https://github.com/dotnet/corefx/files/1897541/CoreDumpLogFile.txt)

Best regards,
Zuendelmeister

**Comment by karelz** [comment]
@Zuendelmeister did you get chance to try it on 2.1?

**Comment by karelz** [comment]
Not actionable with current info, closing. If you hit troubles with 2.1 RC, we can reopen. Thanks!
