### ISSUE TITLE
grapheme enumeration

### ISSUE THREAD

**Issue by ufcpp** [dotnet/corefx#28416]
ported from https://github.com/dotnet/corefx/issues/24093#issuecomment-375585062

[A document of `TextElementEnumerator `](https://msdn.microsoft.com/en-us/library/system.globalization.textelementenumerator(v=vs.110).aspx) says that the .NET Framework defines a text element as a grapheme. However, what exactly does this "grapheme" means? Should the grapheme be the same as defined in ["Grapheme Cluster Boundaries" in UAX #29](http://unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries)?

```cs
using System;
using System.Globalization;

class Program
{
    static void Main()
    {
        var e = StringInfo.GetTextElementEnumerator("👩🏻‍👦🏼👨🏽‍👦🏾‍👦🏿👩🏼‍👨🏽‍👦🏼‍👧🏽👩🏻‍👩🏿‍👧🏼‍👧🏾");
        while (e.MoveNext())
        {
            Console.WriteLine(e.GetTextElement());
        }
    }
}
```

expected result:
👩🏻‍👦🏼
👨🏽‍👦🏾‍👦🏿
👩🏼‍👨🏽‍👦🏼‍👧🏽
👩🏻‍👩🏿‍👧🏼‍👧🏾

actual result:
👩
🏻
‍
👦
🏼
👨
🏽
‍
👦
🏾
‍
👦
🏿
👩
🏼
‍
👨
🏽
‍
👦
🏼
‍
👧
🏽
👩
🏻
‍
👩
🏿
‍
👧
🏼
‍
👧
🏾

**Comment by GrabYourPitchforks** [comment]
See https://github.com/dotnet/corefx/issues/41324.

**Comment by GrabYourPitchforks** [comment]
Fixed by https://github.com/dotnet/runtime/pull/328.
