### ISSUE TITLE
Localization: using resource files when switching CurrentUICulture ignores the translations

### ISSUE THREAD

**Issue by Eilon** [dotnet/corefx#28420]
_From @maxmantz on March 23, 2018 8:1_

Hi,

I have an issue while trying to work with `CurrentUICulture`. Based on a Pluralsight course, I have created a console app which should use resource files to translate an enum into both English and German. 

However, even after changing the `CurrentUICulture` to German, the translation is not picked up by my machine. The weird thing is, that the official source files from the course have the same problem - so I guess my machine is at fault here?

I've made a [repo](https://github.com/maxmantz/CurrentUICultureDemo) with the source files.
Using dotnet 2.1.100 on Windows 10.

_Copied from original issue: aspnet/Home#2995_

**Comment by tarekgh** [comment]
I just cloned the repro and tried it and it is working fine. I didn't change anything at all in the repro code. I have used .net core 2.1 preview 1

```
F:\Temp\CurrentUICultureDemo\Globalisation [master ≡]> dotnet --version
2.1.300-preview1-008174

F:\Temp\CurrentUICultureDemo\Globalisation [master ≡]> dotnet build
Microsoft (R) Build Engine version 15.7.11.29948 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 42.4 ms for F:\Temp\CurrentUICultureDemo\Globalisation\Globalisation.csproj.
  Globalisation -> F:\Temp\CurrentUICultureDemo\Globalisation\bin\Debug\netcoreapp2.0\Globalisation.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.93
F:\Temp\CurrentUICultureDemo\Globalisation [master ≡]> dotnet run
Female
Weiblich
```

**Comment by tarekgh** [comment]
@maxmantz I am not sure why this didn't work for you but please try to ensure the folder ```de-DE``` exist after you compile the app and placed under the app output folder. e.g. in my case 

```
F:\Temp\CurrentUICultureDemo\Globalisation [master ≡]> dir F:\Temp\CurrentUICultureDemo\Globalisation\bin\Debug\netcoreapp2.0\


    Directory: F:\Temp\CurrentUICultureDemo\Globalisation\bin\Debug\netcoreapp2.0


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        3/23/2018   5:46 PM                de-DE
-a----        3/23/2018   5:46 PM            601 Globalisation.deps.json
-a----        3/23/2018   5:46 PM           7168 Globalisation.dll
-a----        3/23/2018   5:46 PM           1428 Globalisation.pdb
-a----        3/23/2018   5:46 PM            372 Globalisation.runtimeconfig.dev.json
-a----        3/23/2018   5:46 PM            154 Globalisation.runtimeconfig.json
```

**Comment by maxmantz** [comment]
Restarting my machine and installing the latest preview build of the SDK seemed to work. Mysterious indeed, but I'll take it. Thanks for your help!

**Comment by maxmantz** [comment]
The error has reappeared - and the mystery deepens.

Continuing through the course, the use of `IStringLocalizer<T>` was demonstrated. Following along, I encountered the same error in an ASP.NET Web project. The localization doesn't get picked up. As with the previous error, in this one too, the official source files of the course don't work either. I've pushed changes to my repo containing the code.

**Comment by maxmantz** [comment]
My output directory:
```

en-US
     StringLocalizersDemo.resources.dll
StringLocalizersDemo.deps.json
StringLocalizersDemo.dll
StringLocalizersDemo.pdb
StringLocalizersDemo.runtimeconfig.dev.json
StringLocalizersDemo.runtimeconfig.json
```

**Comment by tarekgh** [comment]
I am not seeing the de-DE folder, so I guess there is something wrong in the build process and not in picking up the resources. if you can share the exact project repro the issue that will help to diagnose what could be wrong.

**Comment by maxmantz** [comment]
The code is in the original [repo](https://github.com/maxmantz/CurrentUICultureDemo) under `StringLocalizersDemo`. The culture used in that example is `en-US`, and the resources.dll appears to be in the output folder.

**Comment by tarekgh** [comment]
ok, now this is ASP.et specific. I'll reactivate the original ASP.Net issue as this is not the corefx issue now.

**Comment by kasper3** [comment]
I also tested with dotnet-cli 2.1.103 and 2.1.300-preview3-008414 on Windows 10 and got the expected result:

```sh
dotnet clone https://github.com/maxmantz/CurrentUICultureDemo
cd CurrentUICultureDemo
dotnet restore
dotnet run -p Globalisation

# output
Female
Weiblich
```

For ASP.NET localization, you can go through this article to understand how to configure localization in app builder pipeline: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization.

**Comment by maxmantz** [comment]
Sorry to cause confusion, the `Globalisation` project works fine and is solved - the error appears in the second project `StringLocalizersDemo`. There the issue still persists. Please read the readme of the repo for the explanation.

**Comment by kasper3** [comment]
@maxmantz, your StringLocalizerDemo is ASP.NET Core application for which I have shared a documentation link with you. Please read

**Comment by maxmantz** [comment]
@kasper3 I've seen the documentation, and I understand it. 

Even if there is an error in my small example (which you are welcome to check and point out because I spent hours trying to find it), it doesn't explain why the external source files I downloaded have the same issue.

**Comment by kasper3** [comment]
@maxmantz, with `dotnet run -p StringLocalizerDemo` I am getting `This is our company` output at `http://localhost:52855/?about=company`, and `StringLocalizersDemo\bin\Debug\netcoreapp2.0\en-US\StringLocalizersDemo.resources.dll` exists.
Also tried with

```cmd
cd StringLocalizerDemo
dotnet publish -o c:\temp\strloca
cd \temp\strloca
dotnet .\StringLocalizersDemo.dll
```

then with port 5000 `http://localhost:5000/?about=company` , same result.

I would check Event Viewer in Windows to find if there is some low level error related to localization/resources/resx to find.

**Comment by maxmantz** [comment]
@kasper3 I've looked through the logs and the following error appears under `System` when I start the app:

```
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{D63B10C5-BB46-4990-A94F-E40B9D520160}
 and APPID 
{9CA88EE3-ACB7-47C8-AFC4-AB702511C276}
 to the user DESKTOP-EOP5VQF\User SID (S-1-5-21-2158165863-2459923564-2468766334-1001) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.
```
Apart from that, no errors get logged.

**Comment by maxmantz** [comment]
With the help of @kasper3 I was able to resolve the issue. Thanks again!

**Comment by Eilon** [comment]
@maxmantz , I'm glad you got it working, and thanks @kasper3 for helping out!

If you do have further issues with ASP.NET Core localization (such as `IStringLocalizer`), please feel free to log a new issue at https://github.com/aspnet/Home/issues
