### ISSUE TITLE
System.IO.Pipes.TestsAnonymousPipeTest_Specific.Linux_BufferSizeRoundtrips needs elevated priviledges to pass

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/corefx#28436]
```
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.IO.Pipes.Tests
Discovered:  System.IO.Pipes.Tests
Starting:    System.IO.Pipes.Tests
   System.IO.Pipes.Tests.AnonymousPipeTest_Specific.Linux_BufferSizeRoundtrips [FAIL]
      System.UnauthorizedAccessException : Access to the path is denied.
      ---- System.IO.IOException : Operation not permitted
      Stack Trace:
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs(435,0): at System.IO.Pipes.PipeStream.CheckPipeCall(Int32 result)
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.IO.Pipes/src/System/IO/Pipes/AnonymousPipeServerStream.Unix.cs(31,0): at System.IO.Pipes.AnonymousPipeServerStream.Create(PipeDirection direction, HandleInheritability inheritability, Int32 bufferSize)
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.IO.Pipes/tests/AnonymousPipeTests/AnonymousPipeTest.Specific.cs(96,0): at System.IO.Pipes.Tests.AnonymousPipeTest_Specific.Linux_BufferSizeRoundtrips()
         ----- Inner Stack Trace -----
         
Finished:    System.IO.Pipes.Tests

=== TEST EXECUTION SUMMARY ===
   System.IO.Pipes.Tests  Total: 505, Errors: 0, Failed: 1, Skipped: 0, Time: 20.753s
```

Passes if run as sudo.

@jkotas

**Comment by davidfowl** [comment]
It's pipes not pipelines 😄

**Comment by pjanotti** [comment]
@sdmaclea this test is passing on CI and I just tried it in Ubuntu 16.04 and it passed without requiring sudo. Could you please provide more details so I can try to get a repro? What Linux were you using?

**Comment by sdmaclea** [comment]
I am using linux-arm64 ubuntu 16.04
Do you know what device it opens?  I can check the default permissions?

**Comment by pjanotti** [comment]
It opens an anonymous pipe, via the standard pipe functions using this wrapper  https://github.com/dotnet/corefx/blob/09b3cc02d85c5c963af50567cb89b6d67beebc49/src/Native/Unix/System.Native/pal_io.c#L431.

**Comment by sdmaclea** [comment]
@janvorli Do you know a reason why some platforms would need elevated privilege to open/use anonymous pipes?

I haven't run the pal tests on arm64 in over a year.  Maybe it is time to run them again.

**Comment by wfurt** [comment]
You can try it with strace @sdmaclea That would give you clue if it is actually pipe creation or if it is some ioctl after. Also note that things may be weird in qemu containers or when SELinux is enabled.

**Comment by wfurt** [comment]
btw also check ulimit -a for the pipe size.
pipe size            (512 bytes, -p) 8

x86 Ubuntu gives me 4K.

**Comment by sdmaclea** [comment]
pipe size            (512 bytes, -p) 8

**Comment by sdmaclea** [comment]
```
strace -o slog \
 ../../../arm64-runtime/corerun  \
xunit.console.netcore.exe System.IO.Pipes.Tests.dll  \
-xml testResults.xml \
-notrait Benchmark=true \
-notrait category=nonnetcoreapptests \
-notrait category=nonlinuxtests \
 -notrait category=IgnoreForCI \
-notrait category=OuterLoop \
-notrait category=failing \
-method System.IO.Pipes.Tests.AnonymousPipeTest_Specific.Linux_BufferSizeRoundtrips
```

**Comment by wfurt** [comment]
You will need -f as well to see everything. You can grep for pipe in the log...

**Comment by sdmaclea** [comment]
I didn't happen to see it spawn additional processes....
This is the function returning an error.
If I had to guess....  `fcntl(87, F_DUPFD_CLOEXEC, 0)           = 88`

**Comment by wfurt** [comment]
I don't think this is the failure. This call duplicates FD.

**Comment by sdmaclea** [comment]
OK so 88 is the new FD

**Comment by sdmaclea** [comment]
```
slog:21176 05:49:34 fcntl(84, F_SETPIPE_SZ, 2097152) = -1 EPERM (Operation not permitted)
slog.sudo:fcntl(84, F_SETPIPE_SZ, 2097152)        = 2097152
slog.sudo:fcntl(83, F_SETPIPE_SZ, 2097152)        = 2097152
```

From the man page 
```
Attempts by an unprivileged process to set the pipe capacity above the limit in
              /proc/sys/fs/pipe-max-size yield the error EPERM
```
```
cat /proc/sys/fs/pipe-max-size
1048576
```

Per the comment here....  Error could simply be ignored.
```
            // Configure the pipe.  For buffer size, the size applies to the pipe, rather than to 
            // just one end's file descriptor, so we only need to do this with one of the handles.
            // bufferSize is just advisory and ignored if platform does not support setting pipe capacity via fcntl.
            if (bufferSize > 0 && Interop.Sys.Fcntl.CanGetSetPipeSz)
            {
                CheckPipeCall(Interop.Sys.Fcntl.SetPipeSz(serverHandle, bufferSize));
            }
```

**Comment by sdmaclea** [comment]
This is a corefx functional bug.

**Comment by wfurt** [comment]
this could also be test bug: OS does support the change but test is trying to set it to value not permitted by system limits. In either case, it is good we know why this is failing.

**Comment by pjanotti** [comment]
I have the same values for pipe sizes (from ulimit -p and pipe-max-size), the difference seems that the default size that the buffer is created, in my case it was 65,536, but per log it seems that it was 1MB in @sdmaclea case which is already the max size. The test attempts the next operation by doubling the buffer size that's when we got the failure.

**Comment by pjanotti** [comment]
@wfurt yes, if we assume that the buffer size is created already as max in the affected box we also need to change the test, I will take a look at it soon.

**Comment by pjanotti** [comment]
PR #28512 for the test aspect of it.
