### ISSUE TITLE
Last API review nits for 2.1

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#28430]
Aside from the regularlization of span related parameters completed recently by @Anipik , there were some other nits identified in new APIs that we want to fix before release.

These are described here
https://github.com/dotnet/apireviews/pull/63

The line numbers in the comments reference this API list
https://raw.githubusercontent.com/terrajobst/apireviews/a1671f88d1219d2a16e0abfc47e79e3d4c7ed82f/2018/NetCore20-vs-NetCore21-Diff/README.md

@maryamariyan can you please make these tweaks? They are in various areas but can simply be all done at once.

cc @terrajobst

**Comment by tarekgh** [comment]
@maryamariyan will be able to work on this during next week?

**Comment by maryamariyan** [comment]
@danmosemsft @tarekgh yes sure.

**Comment by tarekgh** [comment]
@maryamariyan will be able to close this issue soon?

**Comment by maryamariyan** [comment]
The PRs below address this issue.

https://github.com/dotnet/coreclr/pull/17288 
https://github.com/dotnet/corefx/pull/28540 
https://github.com/dotnet/coreclr/pull/17311 
https://github.com/dotnet/corefx/pull/28581
