### ISSUE TITLE
Package restore failing for xunit.netcore.extensions

### ISSUE THREAD

**Issue by James-Ko** [dotnet/corefx#2843]
For some reason, I'm unable to build solutions because NuGet is unable to do a package restore on xunit.netcore.extensions. When build starts for the solution (the test project specifically), it flashes a brief warning for half a second in the package manager dialog:

>   Not Found
>   https://az320820.vo.msecnd.net/v3-flatcontainer/xunit.netcore.extensions/index.json

Then build fails with 2 different errors,

> Unable to resolve xunit.netcore.extensions (>= 1.0.0-prerelease-) for DNXCore,Version=v5.0,

and

> NuGet Package restore failed for project System.Collections.Immutable.Tests for 'xunit.netcore.extensions [1.0.0-prerelease-*.

Tried another solution I hadn't touched yet, same problem. This still happened with a fresh clone of my master branch, as well. I've updated my repository yesterday to match dotnet/corefx, so it can't be that I think.

**Comment by kapilash** [comment]
I faced the same issue when I tried to run the tests via dnx.
It got resolved when I upgraded the version of xunit to beta4 and did a ``` dnu restore ```.  Relevant portion of my project.json is
         
         "xunit": "2.1.0-beta4-*",
          "xunit.runner.dnx":"2.1.0-beta4*",
        },
         "commands":{
              "test": "xunit.runner.dnx"
           },
 
and am now able to run the tests.

**Comment by James-Ko** [comment]
@kapilash Thanks, that seems to have solved my issue.
