### ISSUE TITLE
ConcurrentBag resize simplification

### ISSUE THREAD

**Issue by bcronce** [dotnet/corefx#28449]
In the [internal void LocalPush(T item)](https://github.com/dotnet/corefx/blob/master/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentBag.cs#L748) method, I think the array growth logic is doing extra work.

`Else` is preserving order
```c#
int headIdx = head & _mask;
if (headIdx == 0)
{
	Array.Copy(_array, 0, newArray, 0, _array.Length);
}
else
{
	Array.Copy(_array, headIdx, newArray, 0, _array.Length - headIdx);
	Array.Copy(_array, 0, newArray, _array.Length - headIdx, headIdx);
}
```

Bags do not guarantee order, just do away with the extra order preserving logic.
```c#
var newArray = new T[_array.Length << 1];
Array.Copy(_array, 0, newArray, 0, _array.Length);

// Reset the field values
_array = newArray;
_headIndex = 0;
_tailIndex = tail = count;
_mask = (_mask << 1) | 1;
```

**Comment by stephentoub** [comment]
> Bags do not guarantee order

While that's true, there's still a performance benefit to the order. Specifically, ConcurrentBag uses a work-stealing queue, where a thread pushes/pops from it, meaning a thread is often going to be operating on data it recently operated on or near, providing cache coherency benefits. That can be very valuable.  These queues grow only rarely, and it's not worth losing that benefit to save on an Array.Copy method call. Thanks, though.
