### ISSUE TITLE
Implement IList<T> in Linq responses when possible

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#2844]
There is code throughout .NET that accepts arguments of `IEnumerable<T>` and has an optimised path for `IList<T>` and/or `ICollection<T>`. Some methods of `System.Linq.Enumerable` would be examples, but also elsewhere such as some collections' constructors. The effect upon `.ToList()`, `.ToArray()` and any operation in `Enumerable` that requires buffering are perhaps particularly of note here.

Some methods of `Enumerable` have results which are conceptually lists. E.g. `Repeat` returns a sequence of a specified size where all items are the same, which can be modelled as a read-only list.

Some methods of `Enumerable` have results which can be conceptually lists in certain conditions. E.g. If `Select` is called on a source that is itself a list, then the result would be a read-only list of the same size as the source list, and a different type.

Returning such list types when possible would increase the times that the existing fast-paths for list types are made use of. At the same time, some such changes would add further such cases, potentially allowing chains of operations that cannot currently hit such fast-paths to do so.

**Comment by stephentoub** [comment]
This was discussed here:
https://github.com/dotnet/apireviews/blob/master/2015-04-28-misc/README.md#1182-systemlinq-performance-improvement-suggestions:

> •Concerns: 1.It's an observable change. The concern is that Linq may now return instances of well-known interfaces that consumers could cast to. This may make it harder for us in the future to change our chaining. We could eliminate this concern by using a private interface in Linq.

**Comment by hackcraft** [comment]
Hmm. Not only is there overlap with my idea here, but there's overlap with some other ideas I've been musing on.
Of the concerns mentioned, I actually think the one you quote is the least worrying; consumers casting with a test is no bad thing (practically the whole point), consumers casting without a test are crazy. But of course, crazy often happens and still has to be considered.

**Comment by hackcraft** [comment]
> We could eliminate this concern by using a private interface in Linq.

That was easily done. It does add a burden to the attempts to use the list, but seems to pay off.

I think it's reasonable to consider just allowing such interfaces to be discovered as it can be done safely with runtime checks, but having a means linq-private means to get such a list is perhaps a good compromise in the meantime.
