### ISSUE TITLE
Dequeue growth method optimizations

### ISSUE THREAD

**Issue by bcronce** [dotnet/corefx#28447]
The [Grow()](https://github.com/dotnet/corefx/blob/master/src/System.Threading.Channels/src/System/Collections/Generic/Dequeue.cs#L94) method some peculiarities that could potentially help with reading or optimizations.

First off `Debug.Assert(_size == _array.Length);` guarantees that these two values are synonymous. Instead of a mix and match of using `_array.Length` in some areas and `_size` in others, just use `_size`.

Another is this part
```c#
const int MinimumGrow = 4;

int capacity = (int)(_array.Length * 2L);
if (capacity < _array.Length + MinimumGrow)
{
	capacity = _array.Length + MinimumGrow;
}

T[] newArray = new T[capacity];
```
`_array` starts off as an empty array `private T[] _array = Array.Empty<T>();`. This means it is a length of zero. The only time `if (capacity < _array.Length + MinimumGrow)` will ever be true is when the array is empty or 0. If I incorporate the first idea along with this one, it could be re-written as this:

```c#
const int MinimumGrow = 4;

int capacity = _size == 0 ? MinimumGrow : _size * 2;

T[] newArray = new T[capacity];
```
or if you want to assume the typical condition to be `true`
```c#
const int MinimumGrow = 4;

int capacity = _size > 0 ? _size * 2: MinimumGrow ;

T[] newArray = new T[capacity];
```

**Comment by stephentoub** [comment]
> The only time if (capacity < _array.Length + MinimumGrow) will ever be true is when the array is empty or 0

Or when the multiplication overflows, which is why the code referred to exists.

**Comment by bcronce** [comment]
As long as `MinimumGrow` is a power of 2 and the growth factor is doubling, it should throw a `System.OutOfMemoryException` before it overflows, which makes it functionally identical. I think this assumption is safe since .Net doesn't allow objects larger than 2^31 unless using some large object allocations and `new byte[int.Max]` fails because the included object metadata makes it larger than 2^31 bytes. 

Of course this would need to be clearly commented on to make sure no on in the future does something to break this assumptions.

Even if an overflow occurred, it would just throw another kind of exception, which I guess would make it not exactly functionally equivalent. Negative array sizes and all that.

**Comment by bcronce** [comment]
Few thoughts come to mind.

1. As long as the type of the array is 2 bytes or larger, it will throw a `System.OutOfMemoryException` before overflowing. *Not sure how `gcAllowVeryLargeObjects` plays into this.
2. The current code will overflow before it reaches `System.OutOfMemoryException` for type `byte`. It starts off at a value of 4, then doubles up to 2^30. At which point `capacity` will overflow on the doubling causing it to go into the `_array.Length + MinimumGrow` logic. `int.Max` is 2147483647, which is an odd number. When 2147483644 is reached, the next addition of 4 will make it want to go to 2147483648, but instead overflow to -2147483648, which is not possible and will overflow. Same issue, different value, and is only different for `byte`.
3. Currently `Dequeue<T>` is only being used with `AsyncOperation<T>`, which is a class and will be at least the size of an `int`.
4. It would be interesting to see a system that reaches 1bil+ enqueued `AsyncOperation<T>`. An 8GiB array just to hold them.

I'm learning a lot. Thanks  :smile:

**Comment by bcronce** [comment]
Maybe something more like

```c#
const int MinimumGrow = 4;
if(_size == int.Max) return; //Can't grow anymore anyway.

int capacity = _size == 0 ? MinimumGrow : _size * 2;
if (capacity < 0) capacity = int.Max;

T[] newArray = new T[capacity];
```

**Comment by stephentoub** [comment]
Oh, this is about the `Dequeue<T>` from the channels library; I read your comment quickly and thought you were talking about `Queue<T>`. Is there a reason you're trying to optimize this method? I'm having trouble imagining a scenario where this kind of difference would be measurable or impactful.

**Comment by bcronce** [comment]
1. I personally found this method a bit difficult to read. 

2. Scaling beyond 2^30 is abysmal,  going from O(N Log(N)) to O(N^2)

Log N is in relation of how many times `Grow()` is called

N is the number of entries, which all need to be copied every time `Grow()` is called

3. Int32 overflow edge case could be made clearer by detecting it and throwing a descriptive error message instead of overflowing and failing with some negative array size or **not actually growing, causing data loss because the code after `Grow()` assumes it worked and using relative offsets.** *This shouldn't happen because of the overflow, but could if a different min growth or scaling factor was used.

4. `Grow()` is called while a lock is held. While it may not get called many times in total, it could affect performance during start up when it's small or when absurdly large. Amdahl's law hates high delay serialization. If somehow the 2^30 inflection point was reached, the array would be huge, causing lots of work to allocate and copy the data while holding the lock. Yet alone created many large object just to add 4 more entries to the billion entry array. Could create a snowball effect.

5. I love reducing lines of code when it makes it easier to grok

6. Just perusing around the concurrent code

I should clarify 1. Reading and knowing what the code is doing was easy, it was the semantics behind the code and understanding the reasoning of why it's was written exactly the way it was written. Maybe I read too far into code, but that's me.

**Comment by stephentoub** [comment]
> Scaling beyond 2^30 is abysmal

The `Dequeue` type is primarily used in Channels to manage blocked readers/writers.  If you've got 2^30 of those, you have way bigger problems.

We don't need an issue to track this.  You're welcome to submit a PR if there's something to be cleaned up.
