### ISSUE TITLE
The type or namespace name 'SocketsHttpHandler' could not be found.

### ISSUE THREAD

**Issue by deepumi** [dotnet/corefx#28456]
**IDE** - Microsoft Visual Studio Community 2017 Preview (2) Version 15.7.0 Preview 2.0
![image](https://user-images.githubusercontent.com/554039/37875669-afa9afc2-3010-11e8-8aac-26ff1f003fed.png)
**Environment** - Windows 10

**Program.cs(10,49): error CS0246: The type or namespace name 'SocketsHttpHandler' could not be found (are you missing a using directive or an assembly reference?)**

```csharp
using System;
using System.Net.Http;

namespace myApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var httpClient = new HttpClient(new SocketsHttpHandler());
            Console.WriteLine("Hello World!");
        }
    }
}
```
I have installed .NET Core 2.1.300-preview1 SDK (Installer for Windows x64) and followed the instruction from here https://blogs.msdn.microsoft.com/dotnet/2018/02/27/announcing-net-core-2-1-preview-1/

**Question**
1) How do I enable SocketsHttpHandler in .Net Core Preview 2.1 (Console App)
2) Any official doc/repo available explaining how to use SocketsHttpHandler?

Thanks
Deepu

**Comment by stephentoub** [comment]
It's not public in Preview 1; it will be in Preview 2.  In Preview 2 it'll also be used under the covers if you use `new HttpClient()` or `new HttpClientHandler()`.

See the blog post at https://blogs.msdn.microsoft.com/dotnet/2018/02/27/announcing-net-core-2-1-preview-1/ for details on how to try it out in Preview1, which involves setting an environment variable or an appcontext switch.
