### ISSUE TITLE
Unsigned range tests; reasonable optimisation or micro-opt too far?

### ISSUE THREAD

**Issue by hackcraft** [dotnet/corefx#2848]
As explored in #2842, when a signed value LIMIT is known to be greater than zero, then:

bool exclusive = value >= 0 && value < LIMIT;
bool inclusive = value >= 0 && value <= LIMIT;

Is equivalent to:

bool exclusive = (uint)value < (uint)LIMIT;
bool inclusive = (uint)value <= (uint)LIMIT;

And so on.

This is shaves off a few instructions and a potential branch.

It's definitely a micro-optimisation to change to it (rather than to just be in the habit of it).

The PR is marked WIP because it would need a double-check that it isn't checking against a limit without the non-negative guarantee.

But it can add up none the less, and is used in the current codebase in at least a few places (`List<T>` has it).

A reasonable optimisation or a micro-opt to far?

(A half-way move could be to only leave in those changes that can be statically shown to have a non-negative limit from just the line in code in question; where the limit is either constant or the `.Length` of an array, or the check immediately follows a non-negative check on the limit).

**Comment by stephentoub** [comment]
It's neat, but I find it makes the code harder to understand,and it's easier for a problem to slip in.  I wouldn't want to see this applied blanketly across the codebase; I'd prefer to see it only applied to the specific places where it made a measurable and important improvement.  And even there, I'd further prefer to see it done as a compiler optimization rather than making the code less clear.

**Comment by hackcraft** [comment]
Perhaps a restriction to cases where out of range is thrown would reduce the readability issue; it answers the "what does this cast do?" question if one sees an `IndexOutOfRangeException` or `ArgumentOutOfRangeException` thrown immediately following.

**Comment by James-Ko** [comment]
+1 for a compiler optimization, this would give the best of both sides. Until then, this should be limited to places where it matters (e.g. data structures), and not places where it's not going to significant (e.g. reflection).

**Comment by hackcraft** [comment]
The compiler needs to know that the limit is guaranteed non-negative. That could be difficult if limit was mutable, or even if it's not a constant.
