### ISSUE TITLE
httpclient requests to dns address that resolves to self causes authentication error

### ISSUE THREAD

**Issue by smasherprog** [dotnet/corefx#28488]
Scenario:

I am using httpclient to send log events that are generated in website A to website B.
both website A and B are using net core 2.0.6 and on the SAME IIS instance.
When sending https requests from website A to website B using defaultcredentials the client FAILS to authenticate. I have windows authentication enabled and verified that its working.

If I change one of the websites to be on a different iis instance, the authentication works and the request succeeds.

**Comment by smasherprog** [comment]
Also, each website resolves to the SAME IP address through DNS as well.

**Comment by karelz** [comment]
Can you narrow down which part of your repro is causing the trouble?
Is it DefaultCredentials? Is it HttpClient side? Or server side? ... Did you try to peek at Fiddler/Wireshark traces?

**Comment by smasherprog** [comment]
Never mind Its an obscure problem documented here
https://support.microsoft.com/en-us/help/926642/error-message-when-you-try-to-access-a-server-locally-by-using-its-fqd

When a server talks to itself effectively, windows authentication does not work. I fixed it by adding hostnames to the BackConnectionHostNames  registry.

Thanks for the quick response though

**Comment by smasherprog** [comment]
To repro this just set up two websites on the SAME iis instance. Do not add seperate IP addresses *This is Key* as the problem arises when accessing a FQDN that resolves to itself.
Add DNS entries for each website. 
disable all authentication except windows inside IIS for each website.
Set up each app pool under a windows domain account.
In one website use httpclient to try and access any url on the other websiite using Default Credential httphandler.
The httpclient will not authenticate to the other webserver because of some loopback security hole. I am not sure if this can be fixed in the httpclient -- that would be awesome.
