### ISSUE TITLE
DataAnnotation exposes readonly Dictionary on ValidationContext

### ISSUE THREAD

**Issue by roydukkey** [dotnet/corefx#28491]
https://github.com/dotnet/corefx/blob/2242e106f7695578ccaa1dcc35e438a14f9be1f1/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/ValidationContext.cs#L32

`ValidationContext` exposes the readonly dictionary as `IDictionary Items`. Should this property be changed from `IDictionary` to `IReadOnlyDictionary`?

https://github.com/dotnet/corefx/blob/2242e106f7695578ccaa1dcc35e438a14f9be1f1/src/System.ComponentModel.Annotations/tests/ValidationContextTests.cs#L54-L66

The above test will fail at L63 if the following code is added between L61 and L62.

            validationContext.Items.Add("testKey3", "testValue3");

**Comment by ajcvickers** [comment]
@roydukkey This would be a breaking change to existing code, so unfortunately it is not something we can do at this time. /cc @divega

**Comment by roydukkey** [comment]
@ajcvickers Can we agree, though, that this is a flaw? And, if it wasn't a breaking change, the code should be changed in some manner?

**Comment by ajcvickers** [comment]
@roydukkey Yes, at least to the depth that I have investigated this, I agree that it would be better not to expose an IDictionary here.
