### ISSUE TITLE
Test System.Text.RegularExpressions.Tests.RegexGroupTests failed in CI.

### ISSUE THREAD

**Issue by Sunny-pu** [dotnet/corefx#28496]
Test System.Text.RegularExpressions.Tests.RegexGroupTests failed.
details:
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release/417/testReport/System.Text.RegularExpressions.Tests/RegexGroupTests/GroupsBasic/

MESSAGE:
Exit code was 32899 but it should have been 42\nExpected: True\nActual: False
+++++++++++++++++++
STACK TRACE:
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose(Boolean disposing) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 252

**Comment by ViktorHofer** [comment]
Many Regex tests failed because of the RemoteExecutor invocation.

```
System.Text.RegularExpressions.Tests.RegexMatchTests.Match_SpecialUnicodeCharacters_enUS [FAIL]
System.Text.RegularExpressions.Tests.RegexConstructorTests.StaticCtor_InvalidTimeoutObject_ExceptionThrown [FAIL]System.Text.RegularExpressions.Tests.RegexConstructorTests.StaticCtor_InvalidTimeoutRange_ExceptionThrown [FAIL]
System.Text.RegularExpressions.Tests.RegexGroupTests.GroupsCzech [FAIL]
System.Text.RegularExpressions.Tests.RegexGroupTests.GroupsEnUS [FAIL]
System.Text.RegularExpressions.Tests.RegexGroupTests.GroupsDanish [FAIL]
System.Text.RegularExpressions.Tests.RegexGroupTests.GroupsAzeriLatin [FAIL]
System.Text.RegularExpressions.Tests.RegexGroupTests.GroupsTurkish [FAIL]
System.Text.RegularExpressions.Tests.RegexMatchTests.Match_Timeout_Throws [FAIL]
System.Text.RegularExpressions.Tests.RegexGroupTests.GroupsBasic [FAIL]
System.Text.RegularExpressions.Tests.RegexMatchTests.Match_SpecialUnicodeCharacters_Invariant [FAIL]
```

https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release/417/consoleText

As even the most primitive tests failed (StaticCtor), I'm closing this.

**Comment by Sunny-pu** [comment]
failed again in CI:
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/390/testReport/System.Runtime.Serialization.Formatters.Tests/BinaryFormatterTests/Roundtrip_CrossProcess_obj____test___/

**Comment by ViktorHofer** [comment]
I believe OSX and RemoteExecutor don't like each other right now.
