### ISSUE TITLE
Wire up lldb into Unix test run scripts

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#28509]
Similar to wiring up of GDB in https://github.com/dotnet/buildtools/pull/1948 we want LLDB to be wired up 

It's being added to test images in https://github.com/dotnet/core-eng/issues/2998  and it already exists on some machines. You can install it locally on your Linux box to test your change, of course.

LLDB should be scripted to open the dump, do `clrstack -all` and probably `pe -nested` , and quit.

cc @stephentoub @maririos @mikem8361

**Comment by danmosemsft** [comment]
I'm not sure whether `pe -nested` will give anything here -- @mikem8361 does an unhandled managed exception give a dumpfile on Linux? I seem to remember you said that was future work.

**Comment by danmosemsft** [comment]
I wonder if it would have any value for lldb to also get a native stack trace, same as gdb. There might be cases where one works and the other doesn't. I suggest we do this - last in the sequence.

**Comment by danmosemsft** [comment]
Although LLDB works on macOS, SOS does not work on dumps on macOS currently. So there is no point trying to use it on macOS.

**Comment by mikem8361** [comment]
Yes, unhandled managed exceptions do an “abort()” which will cause a core dump on Linux. “pe -nested” should dump that exception.
