### ISSUE TITLE
Build failing with 'CancellationTokenRegistration' does not contain a definition for 'TryDeregister'

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#28502]
From https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1524090

System\Threading\Tasks\AsyncInfoToTaskBridge.CoreCLR.cs(73,29): error CS1061: 'CancellationTokenRegistration' does not contain a definition for 'TryDeregister' and no extension method 'TryDeregister' accepting a first argument of type 'CancellationTokenRegistration' could be found (are you missing a using directive or an assembly reference?) [E:\A\_work\4\s\corefx\src\System.Runtime.WindowsRuntime\src\System.Runtime.WindowsRuntime.csproj]

Looks like it is related to https://github.com/dotnet/corefx/pull/28471

cc @stephentoub, @danmosemsft, @AntonLapounov, @jkotas

**Comment by jkotas** [comment]
This was fixed by https://github.com/dotnet/corefx/pull/28489
