### ISSUE TITLE
System.Security.Cryptography.Pkcs '1.2.840.113549.1.1.5' is not a known hash algorithm.

### ISSUE THREAD

**Issue by hozjanmarko** [dotnet/corefx#28504]
i'm trying to compute a cms SHA1RSA using the pre release version(4.5.0-preview1-26216-02) of System.Security.Cryptography.Pkcs.

Oid.FromFriendlyName("SHA1RSA",OidGroup.SignatureAlgorithm) returns the corect digest algorithem, but upon calling encode, i get the exception that i,m not using any known hash algorithm.

Is there any short term plan to incorporate it?

Encoding snippet:----------
protected byte[] GenerateSignature(byte[] fileContent)
        {
            CmsSigner signer = new CmsSigner(SubjectIdentifierType.IssuerAndSerialNumber, ClientCert);
            SignedCms signedCms = new SignedCms(new ContentInfo(fileContent), false);
            signer = new CmsSigner(SubjectIdentifierType.IssuerAndSerialNumber, ClientCert);
            signer.DigestAlgorithm = Oid.FromFriendlyName("SHA1RSA",OidGroup.SignatureAlgorithm);
            signedCms.ComputeSignature(signer, false);
            var signature = signedCms.Encode();
            return signature;
        }

**Comment by hozjanmarko** [comment]
It seems i have a long way to go :)
Could you please provide me with some hints how a could generate a valid signature? I have to consume a "wcf" service that expects this "SHA1RSA" signature(rather than using ws* secure). They provided me with the code snippet that i posted in my original post.

**Comment by bartonjs** [comment]
```c#
protected byte[] GenerateSignature(byte[] fileContent)
{
    CmsSigner signer = new CmsSigner(SubjectIdentifierType.IssuerAndSerialNumber, ClientCert);
    SignedCms signedCms = new SignedCms(new ContentInfo(fileContent), false);
    signer = new CmsSigner(SubjectIdentifierType.IssuerAndSerialNumber, ClientCert);

    // instead of
    //signer.DigestAlgorithm = Oid.FromFriendlyName("SHA1RSA",OidGroup.SignatureAlgorithm);
    // use
    signer.DigestAlgorithm = Oid.FromFriendlyName("SHA1", OidGroup.HashAlgorithm);
    // or
    //signer.DigestAlgorithm = new Oid("1.3.14.3.2.26");

    signedCms.ComputeSignature(signer, false);
    var signature = signedCms.Encode();
    return signature;
}
```

**Comment by InternetLogic** [comment]
Incidentally the documents we are signing are PDFs and Acrobat recognises these Oids and validates the signatures. Should it not be possible to use S.S.S.Pkcs we'll probably have to use bouncy castle for validation.
