### ISSUE TITLE
Port legacy LINQ tests to Git/XUnit

### ISSUE THREAD

**Issue by VSadov** [dotnet/corefx#2851]
Current active test coverage for LINQ is not very great. While sources were ported and published, many old legacy tests has been left behind.

It is not an easy task to port them to Git/XUnit, but mostly just because of the test volume and because they are not XUnit tests.
It would be nice to port them over. Also it would be preferable to port these tests over writing new ones, because the old tests are by definition "correct". I.E. any deviation from the behavior guarded by those tests could be a compatibility issue.

I have collected and pushed a lot of old legacy tests for LINQ to https://github.com/VSadov/corefx/tree/UnportedLegacyTests  branch.

Actual tests are at:
https://github.com/VSadov/corefx/tree/UnportedLegacyTests/src/System.Linq/LegacyTestsToPort/LINQ

**Comment by VSadov** [comment]
@jaredpar @stephentoub - FYI

**Comment by hackcraft** [comment]
I wouldn't mind grabbing a few. I have after all been looking at this assembly in particular, it would be a boon to those efforts to have more tests.

**Comment by VSadov** [comment]
@hackcraft - just post here what areas you are working on. I will add them to the list of inprogress areas. 
I do not think I will have time for these in the next week or so.

**Comment by akoeplinger** [comment]
@VSadov @hackcraft I wrote a simple script to process the legacy tests and basically wrap the Main() with a `[Fact]` that asserts the return value == 0: https://github.com/dotnet/corefx/pull/2874.

I think this is a good start and further cleanup or conversion to idiomatic Xunit can be done in follow up PRs.

**Comment by VSadov** [comment]
Since the initial port has been committed to master, this issue could be considered fixed. Individual area cleanups can be handled as separate PRs. If there is a need for an issue tracking area clean ups, we should enter a different one(s)
