### ISSUE TITLE
Enumerable.Range bug for boundary values

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#2852]
I believe that this commit (https://github.com/dotnet/corefx/commit/31599c59cb601459982be0aa78f7f8381b53566c) introduced a bug in boundary conditions for Enumerable.Range

The below program exhibits this:

````CSharp
static void Main(string[] args)
{
    int from = int.MaxValue - 9;
    int count = 10;
    Console.WriteLine("Enumerable.Range:");
    foreach (int i in Enumerable.Range(from, count))
    {
        Console.WriteLine(i);
    }
}
````

On the Desktop library, this prints: 

````
Enumerable.Range:
2147483638
2147483639
2147483640
2147483641
2147483642
2147483643
2147483644
2147483645
2147483646
2147483647
````

With the latest version of System.Linq here, it prints no elements:

````
Enumerable.Range:
````

Here is the new iteration logic for Enumerable.Range:

````CSharp
private static IEnumerable<int> RangeIterator(int start, int count)
{
    for (int i = 0; i < count; i++) yield return start + i;
    for (int end = start + count; start < end; start++)
        yield return start;
}
````

The loop condition will fail for any range that will reach Int32.MaxValue.

NOTE: This doesn't seem to be covered by any of our Linq tests. I only discovered it because one of our internal Linq.Parallel tests failed, which was trying to compare ParallelEnumerable.Range to Enumerable.Range, and I noticed that Enumerable.Range was returning nothing for this case. We should improve coverage here on top of fixing this bug.

**Comment by mellinoe** [comment]
Just noticed this issue was just filed, may be related :) https://github.com/dotnet/corefx/issues/2851

cc: @VSadov

**Comment by stephentoub** [comment]
Yes, the new version has a bug when the last element to be enumerated is Int32.MaxValue, in that it wraps around to have ```end``` be Int32.MinValue, and as a result no values are yielded.  We should just revert that change; it was attempting an optimization that yields only minor benefits.  @mellinoe, are you fixing it?

**Comment by mellinoe** [comment]
I made a PR: #2853
