### ISSUE TITLE
Digest parsing on SocketsHttpHandler is not as robust as on WinHttpHandler

### ISSUE THREAD

**Issue by rmkerr** [dotnet/corefx#28523]
In one of the `WWW-Authenticate` header test cases, unquoted digest parameters are successfully parsed by `WinHttpHandler`, but not by `SocketsHttpHandler`.  The test case was written to expect a `401` response, but failed on WinHttpHandler when the request successfully authenticated.

https://github.com/dotnet/corefx/blob/00547db7233076da50db7b4d6e1a8e7ff1710ed0/src/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs#L571

The Wireshark traces below demonstrate the issue, with `SocketsHttpHandler` on the left and `WinHttpHandler` on the right.

![image](https://user-images.githubusercontent.com/4656175/37993307-119053cc-31c3-11e8-930c-4a03d83f715e.png)

This case isn't technically legal as per the spec, since realm and nonce are required to be quoted. I think we should fix it eventually since it is a regression from WinHttpHandler, but I'm not sure how to prioritize it. @karelz do you have any thoughts?

**Comment by karelz** [comment]
I am fine resolving it as By Design. If we have real-world usage for unquoted strings for realm/nonce (which directly violates the RFC - https://tools.ietf.org/html/rfc2617 page 3 & 8), we can adjust.
@geoffkizer @stephentoub @davidsh thoughts?

**Comment by wfurt** [comment]
I think it nice to be liberal unless that creates security problem. Ability to accept token without requiring quotes would increase interoperability. However I would not expect to be priority for 2.1.
We can also test netfx as we take it as base line in many cases.

**Comment by davidsh** [comment]
>@geoffkizer @stephentoub @davidsh thoughts?

On Windows, Digest auth is disabled by default. It is becoming less common as most scenarios simply use HTTPS with Basic or Negotiate auth. I suggest we wait for customer feedback.

**Comment by davidsh** [comment]
We've made several Digest auth related fixes in .NET Core 3.0.

Closing this issue. If we have customer feedback about new Digest auth issues we can investigate.
