### ISSUE TITLE
WinHttpHandler does not authenticate when unknown parameters are present with basic auth

### ISSUE THREAD

**Issue by rmkerr** [dotnet/corefx#28521]
The [RFC](https://tools.ietf.org/html/rfc7617#section-2
) for Basic authentication states that unknown parameters must be ignored:

>No other authentication parameters are defined -- unknown
parameters MUST be ignored by recipients, and new parameters can
only be defined by revising this specification.

There are two cases that test this which are failing on `WinHttpHandler`:
```csharp
yield return new object[] { "Basic realm=\"testrealm1\" basic realm=\"testrealm1\"", true };
yield return new object[] { "Basic something digest something", true };
```
The above cases look like additional auth schemes, but since they are not comma separated, they are considered additional parameters. On `WinHttpHandler` these headers are rejected, when the extra parameters should really just be ignored.

`WinHttpHandler` is depending on WinHttp to parse the `WWW-Authenticate` header, so I see this as an issue we are unlikely to fix without customer reports. With that in mind I'm moving this to future.

**Comment by karelz** [comment]
Given that this is bug in external component (WinHTTP), I don't think we should do anything here. The tests are disabled on non-SocketsHttpHandler:
https://github.com/dotnet/corefx/blob/9e8c200f0888a1db590da8ffa026aa7384771611/src/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs#L577-L580

Closing.
cc @davidsh
