### ISSUE TITLE
GetTaskSchedulersForDebugger_ReturnsDefaultScheduler tests failing in CI with NullReferenceException for Unix

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#28539]
From https://github.com/dotnet/corefx/pull/28536
System.Threading.Tasks.Tests.TaskSchedulerTests/GetTaskSchedulersForDebugger_ReturnsDefaultScheduler
OSX.1013.Amd64.Open-x64-Debug
Ubuntu.1604.Amd64.Open-x64-Release
...
Centos.74.Amd64.Open-x64-Release
https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/2c74aa99ae6f5bcb1048ef1450dc9894a924c562/workItem/System.Threading.Tasks.Tests/analysis/xunit/System.Threading.Tasks.Tests.TaskSchedulerTests~2FGetTaskSchedulersForDebugger_ReturnsDefaultScheduler

```text
Unhandled Exception of Type System.NullReferenceException
Message :
System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace :
   at System.Threading.Tasks.Tests.TaskSchedulerTests.GetTaskSchedulersForDebugger_ReturnsDefaultScheduler() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Threading.Tasks/tests/TaskScheduler/TaskSchedulerTests.cs:line 298
```

cc @tarekgh, @danmosemsft

**Comment by stephentoub** [comment]
@ahsonkhan, presumably this is failing consistently?

@jkotas, is it possible the linker is removing this method on unix now that InternalsVisibleTo was removed?
https://github.com/dotnet/coreclr/commit/4b95b41d93e7b267c972fe60e0fe9f2068cbeb1c#diff-c2ad4c1a6dafaad71d39f285681f7384R631

**Comment by jkotas** [comment]
Yes, the linker is removing the method now. I have disabled the test and will submit a fix to CoreCLR.

**Comment by jkotas** [comment]
Keep open until the test is re-enabled

**Comment by joperezr** [comment]
Are you going to put up a PR enabling the test? If not I can do that for you.
