### ISSUE TITLE
Use DataContractSerializer to serialize Lazy<T> object

### ISSUE THREAD

**Issue by yujayee** [dotnet/corefx#28530]
When serialize Lazy<T> object, the output xml is not as expected.

           `var value = new Lazy<int>(() => 1);
            DataContractSerializer dcs = new DataContractSerializer(typeof(Lazy<int>));
            using (MemoryStream ms = new MemoryStream())
            {
                Console.WriteLine(value.Value);  //1
                Console.WriteLine(value.IsValueCreated);  //true
                dcs.WriteObject(ms, value);
                ms.Position = 0;
                string actualOutput = new StreamReader(ms).ReadToEnd();
                Console.WriteLine(actualOutput);
                //< LazyOfint xmlns = "http://schemas.datacontract.org/2004/07/System" xmlns:i = "http://www.w3.org/2001/XMLSchema-instance" />

                ms.Position = 0;
                var deserialized = (Lazy<int>)dcs.ReadObject(ms);
                Console.WriteLine(deserialized.IsValueCreated); //false
                Console.WriteLine(deserialized.Value);  //0
                Console.WriteLine(deserialized.IsValueCreated);  //true
                Console.WriteLine(deserialized.Value);  //0
            }`

Tried same code on full framework, got the following exception: 

> System.Runtime.Serialization.SerializationException: 'Type 'System.Lazy`1+Boxed[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]' with data contract name 'Lazy.BoxedOfintk9wYX3t0:http://schemas.datacontract.org/2004/07/System' is not expected. Consider using a DataContractResolver if you are using DataContractSerializer or add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to the serializer.'

**Comment by huanwu** [comment]
The behavior is different in full framework and dotnet core because in dotnet core, there's no data member in datacontract. That's why there's no exception in dotnet core. But also nothing get serialized.

**Comment by huanwu** [comment]
DCS doesn't support Lazy. The behavior on full framework is correct. We need apply the same on dotnet core.

**Comment by huanwu** [comment]
Need open a desktop work item and see if to support this type.

**Comment by huanwu** [comment]
On dotnet core, the Lazy object won't be serialized because it doesn't contain the memeber that can be serialized. On desktop,  when it try to deserialze [m_boxed](https://referencesource.microsoft.com/#mscorlib/system/Lazy.cs,103) object declared as object, which is typeof [Boxed](https://referencesource.microsoft.com/#mscorlib/system/Lazy.cs,68), it will fail because it is not a known type.

**Comment by huanwu** [comment]
The serialized Lazy object is empty because the public value is get only. It is set through the function. This is by design and no easy fix.

**Comment by huanwu** [comment]
This issue was already covered by https://github.com/dotnet/coreclr/issues/17460
