### ISSUE TITLE
(Out)dated JS escaping rules in JsonValue.cs

### ISSUE THREAD

**Issue by cyberphone** [dotnet/corefx#28549]
https://github.com/dotnet/corefx/blob/master/src/System.Json/src/System/Json/JsonValue.cs

Edge, Chrome, Firefox:
Input: JSON.stringify("</script>")
Result: ""</script>""

I can't verify that U+2028 (LINE SEPARATOR), U+2029 (PARAGRAPH SEPARATOR) needs to be escaped either.  Only Firefox does that at the moment.

**Comment by karelz** [comment]
I am not sure what you're suggesting. Can you please be more specific?
Are we violating the JSon RFC? https://datatracker.ietf.org/doc/rfc8259/?include_text=1

**Comment by cyberphone** [comment]
No, you are not violating anything but the escaping does not match that of the current ECMAScript standard or its implementations in Browsers and Node.js

**Comment by tarekgh** [comment]
According to https://datatracker.ietf.org/doc/rfc8259/?include_text=1

```
12.  Security Considerations

   Generally, there are security issues with scripting languages.  JSON
   is a subset of JavaScript but excludes assignment and invocation.

   Since JSON's syntax is borrowed from JavaScript, it is possible to
   use that language's "eval()" function to parse most JSON texts (but
   not all; certain characters such as U+2028 LINE SEPARATOR and U+2029
   PARAGRAPH SEPARATOR are legal in JSON but not JavaScript).  This
   generally constitutes an unacceptable security risk, since the text
   could contain executable code along with data declarations.  The same
   consideration applies to the use of eval()-like functions in any
   other programming language in which JSON texts conform to that
   language's syntax.
```

So we are conforming to JSON specs.

**Comment by karelz** [comment]
Sounds like JSon != ECMAScript and the difference is by design ...

**Comment by tarekgh** [comment]
@cyberphone I closing this issue as we need to continue to conform to JSON spec. Let me know if you have any more questions. Thanks for reporting the issue.

**Comment by cyberphone** [comment]
Being incompatible with JSON.stringify() is a bit of a problem for those who want to build signature solutions using JSON.

This is how ECMAScript interprets the JSON spec with respect to "String":
https://cyberphone.github.io/doc/security/draft-rundgren-json-canonicalization-scheme.html#json.ser.string

Microsoft follows that..

**Comment by tarekgh** [comment]
From the specs you have pointed at, 

```
Note that many JSON systems permit the use of invalid Unicode data like "lone surrogates" (e.g. U+DEAD), which also is dealt with in a platform specific way. Since this leads to interoperability issues including broken signatures, such usages MUST be avoided. 
```

It sounds to me the issue need to be avoided from the layer above the JSON parsers and not inside JSON parsers. right?

**Comment by cyberphone** [comment]
Invalid UTF is a generic JSON interoperability issue.  It is currently not solved at all.
