### ISSUE TITLE
BitConverter - Select Endianness 

### ISSUE THREAD

**Issue by deinok** [dotnet/corefx#28548]
Add a way to set the Endianness of the methods. Something like:
```csharp
public static ushort ToUInt16(byte[] value, int startIndex, Endianness endianness=Endianness.BigEndian);
```

Where the default parameter points to the system default endianness

**Comment by karelz** [comment]
Duplicate of #22405
See https://github.com/dotnet/corefx/issues/22405#issuecomment-334282741 - it was superseded by #22355.
