### ISSUE TITLE
same project dotnet build -c release  on linux is fail

### ISSUE THREAD

**Issue by quan01994** [dotnet/corefx#28542]
same project .
on linux 
![image](https://user-images.githubusercontent.com/20533465/38012499-47a4bfbc-3294-11e8-9cec-7a3aa58990ec.png)

on windows
![image](https://user-images.githubusercontent.com/20533465/38012526-5e74c6b0-3294-11e8-9491-3a7f7cce620a.png)

but on linux ,run " dotnet build -c release " is fail
![image](https://user-images.githubusercontent.com/20533465/38012581-a0aa5842-3294-11e8-9f11-498e01775437.png)

on windows it's run 
![image](https://user-images.githubusercontent.com/20533465/38012616-b68aa4e6-3294-11e8-984e-c6e3a765e9d3.png)

why?

**Comment by joshfree** [comment]
@livarcocc should this go to dotnet/cli?

**Comment by joemey** [comment]
this looks like https://github.com/dotnet/cli/issues/8048

for some reason the compiler tries to write the XML file to [code]/data/projects/Hyw/src/bin/**R**elease/netcoreapp2.0/Hyw.Api.xml[/code] when the directory only exists with an lowercase "r"

**Comment by tarekgh** [comment]
Issue moved to [dotnet/cli #8920](https://github.com/dotnet/cli/issues/8920) via [**ZenHub**](https://www.zenhub.com/)
