### ISSUE TITLE
ValueTask<T> and ValueTask should implement the same common interface

### ISSUE THREAD

**Issue by nockawa** [dotnet/corefx#28546]
Both class could implement an interface like this one
```csharp
    public interface IValueTask
    {
        bool IsCanceled { get; }
        bool IsCompleted { get; }
        bool IsCompletedSuccessfully { get; }
        bool IsFaulted { get; }
    }
```
Another method could be added to the interface to access the underlying Task, returning a `Task` object which is possible as `Task<T>` derived from `Task`.
```csharp
Task UnderlyingTask(): // For a lack of a better name...
```

This way we could store `IValueTask` fields in our custom types that would address either `ValueTask` or any kind of `ValueTask<T>`

I'm aware this would introduce Boxing to define IValueTask members, but maybe it is an acceptable choice when the alternative would be to store many members because of many different `<T>`...

**Comment by davidfowl** [comment]
You wouldn’t use this if you cared about performance...

**Comment by nockawa** [comment]
Yes I know and agree, but what if you care about storage?

**Comment by davidfowl** [comment]
Convert it to a task.

**Comment by nockawa** [comment]
My understanding was that `AsTask()` could trigger unnecessary code if the ValueTask could be completed fairly quickly. An interface wouldn't hurt in any way, right?

**Comment by davidfowl** [comment]
Would it have to be awaitable? What’s your scenario exactly?

**Comment by nockawa** [comment]
I do async read/write operations from a FileStream. The File is split into many clusters, and I can read/write to each of them, so it means storing the Task for the running IO operation (can't be both read and write at the same time on the same cluster).

I do care about the overall size of storage of the data stored, I do agree it's borderline, storing one ValueTask<T> for read and another ValueTask for write would certainly be the best choice as struct would definitely be more GC Friendly.

My use case made we think about the fact that an Interface couldn't hurt in anyway and the user would have the choice.

It is better to convert to a Task or to Box the ValueTask? I think that's the question and I'm not the best one to answer it! :)

**Comment by svick** [comment]
> It is better to convert to a Task or to Box the ValueTask?

I'm not sure it makes sense to ask that question. If you care about performance, you're not going to do either one, because both allocate. If you don't care about performance, then converting to `Task` is fine.

The case where boxing `ValueTask` is acceptable, but converting to a `Task` is not, is likely going to be narrow, so I don't think it makes sense to add API just for that.

**Comment by tarekgh** [comment]
CC @stephentoub

**Comment by stephentoub** [comment]
I don't think such an interface is desirable.  If you want a heap-based representation, just use AsTask.  That's not going to allocate anything if the ValueTask actually wraps a Task under the covers, and if it doesn't, boxing it would allocate anyway.

**Comment by nockawa** [comment]
@stephentoub makes sense, thank you. I'll take a closer look at's ValueTask's implementation.
