### ISSUE TITLE
Getting build error in VS for Microsoft.CSharp

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/corefx#28580]
I did a pull, a full build via the command line, and then opened Microsoft.CSharp.

Actually, I may have run build.sh and build.cmd, which is pretty much the same, right?

I opened the solution in VS and tried to build, but this is the error I am getting:

> The target "Build" does not exist in the project.

**Comment by ViktorHofer** [comment]
Sounds like a dirty environment. The target Build always exists. Just make sure that you run .\build.cmd first (on Windows) or ./build.sh (on Unix). Feel free to reopen if you have further questions.
