### ISSUE TITLE
ProcessStartInfo.WorkingDirectory is not working

### ISSUE THREAD

**Issue by xlegalles** [dotnet/corefx#28590]
We have an application which starts several processes (all .NET Core 2.0 console app). We set the `ProcessStartInfo.WorkingDirectory` to ensure that the current directory is the one of the started executable but it does not work: the `GetCurrentDirectory` remains the one of the application that invokes the `Process.Start()`.
We do a `Directory.SetCurrentDirectory` in the started application as a workaround.

.NET Core 2.1.101

**Comment by danmosemsft** [comment]
@Anipik can you please try to repro and make sure we have a test. The TestWorkingDirectoryProperty() test we do have does not appear to do anything but read back the property set. It should do GetCurrentDirectory() in the child process.

**Comment by Anipik** [comment]
@xlegalles can you supply a code snippet because i tested workigDirectory Property and its working fine

**Comment by xlegalles** [comment]
I try to reproduce it with a simple example and can't :( Although I'm sure that we applied the workaround in 2 applications... I have to investigate more (and next time I will do it before opening a ticket!)

**Comment by Anipik** [comment]
@xlegalles feel free to re-open the issue :)
