### ISSUE TITLE
Proposal: new System.ComponentModel.VersionConverter class

### ISSUE THREAD

**Issue by 0xced** [dotnet/corefx#28594]
## Rationale and Usage

Converting between `System.Version` and `string` is currently not supported using a `System.ComponentModel.TypeConverter`. Many system types are supported out of the box (System.DateTimeOffset, System.Guid, System.TimeSpan, System.Uri etc.) so I think System.Version would be a welcome addition.

I was expecting this to work, but converting from string actually throws `NotSupportedException`: TypeConverter cannot convert from System.String.

```csharp
using System.ComponentModel;
using System.Diagnostics;
TypeConverter versionConverter = TypeDescriptor.GetConverter(typeof(Version));
Version version = versionConverter.ConvertFromString("1.2.3.4") as Version;
Trace.Assert(version.Major == 1);
Trace.Assert(version.Minor == 2);
Trace.Assert(version.Build == 3);
Trace.Assert(version.Revision == 4);
```

## Proposed API

```csharp
public partial class VersionConverter : System.ComponentModel.TypeConverter
{
    public VersionConverter();
    public override bool CanConvertFrom(System.ComponentModel.ITypeDescriptorContext context, System.Type sourceType);
    public override bool CanConvertTo(System.ComponentModel.ITypeDescriptorContext context, System.Type destinationType);
    public override object ConvertFrom(System.ComponentModel.ITypeDescriptorContext context, System.Globalization.CultureInfo culture, object value);
    public override object ConvertTo(System.ComponentModel.ITypeDescriptorContext context, System.Globalization.CultureInfo culture, object value, System.Type destinationType);
    public override bool IsValid(System.ComponentModel.ITypeDescriptorContext context, object value);
}
```

## Details

Converting between `string` and `System.Version` is very straightforward, implementation would be very similar to `GuidConverter` or `UriTypeConverter`.

## Open Questions

* What exception should be thrown when the string to convert is not valid, for example `"1"`? Other converters just let the constructor of the type throw the exception.

```csharp
var uriConverter = System.ComponentModel.TypeDescriptor.GetConverter(typeof(Uri));
uriConverter.ConvertFromString("mailto:User@"); // throws UriFormatException
```

```csharp
var guidConverter = System.ComponentModel.TypeDescriptor.GetConverter(typeof(Guid));
guidConverter.ConvertFromString("xxxx"); // throws FormatException
```

For `System.Version`, that would mean throwing an `ArgumentException` which is less descriptive than a `FormatException`.

* Should the converter be registered with other `IntrinsicTypeConverters` (is System.Version an intrinsic type?) or should the converter be registered with the `TypeConverterAttribute` on the `System.Version` class?

## Pull Request

A pull request with the proposed changes is available: #28516

**Comment by karelz** [comment]
@safern @maryamariyan can you please take a look when you get a chance? This is for the pending PR #28516.

**Comment by safern** [comment]
@0xced thanks for the proposal. I like the idea of being able to convert from `string` to `Version` and the proposal seems very complete now. The only thing that I'm in doubt is the `ArgumentException` which I think doesn't fit much for this case. We could think a way to instead throw a `FormatException` i.e catching the `ArgumentException`. 

@maryamariyan any thoughts?

**Comment by safern** [comment]
> so maybe it’s better to let the constructor throw the appropriate exception, just like other type converters?

You're right, let's keep it simple and just let the constructor handle it itself.

**Comment by 0xced** [comment]
And what about the registration of the converter? Is `System.Version` considered an intrinsic type? The comment in [ReflectTypeDescriptionProvider.cs](https://github.com/dotnet/corefx/blob/2d7b6dc7c773f2a143aacebc08c98dd8397286af/src/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs#L98-L101) says:
> This is a table we create for intrinsic types.  There should be entries here ONLY for intrinsic types, as all other types we should be able to add attributes directly as metadata.

I see that `System.Guid` and `System.Uri` for example are considered intrinsic type but unfortunately, I was not able to find a clear definition of what is a C# intrinsic type. 😕

**Comment by terrajobst** [comment]
Looks good as proposed.
