### ISSUE TITLE
PlatformNotSupported thrown by SystemWebProxy

### ISSUE THREAD

**Issue by ByronAP** [dotnet/corefx#28605]
I know this is obviously intentional but is poor and should be reconsidered for alternatives such as returning a marker instead of throwing and catching an exception.

> System.PlatformNotSupportedExceptio
>   HResult=0x80131539
>   Message=Operation is not supported on this platform.
>   Source=System.Net.Requests
>   StackTrace:
>    at System.Net.SystemWebProxy.GetProxy(Uri destination)

https://github.com/dotnet/corefx/blob/master/src/System.Net.Requests/src/System/Net/SystemWebProxy.cs#L50-L53

```c#
public Uri GetProxy(Uri destination)
{
      throw new PlatformNotSupportedException();
}
```

[EDIT] Fix link by @karelz

**Comment by karelz** [comment]
Covered by #26494, please upvote that issue. Thanks!
