### ISSUE TITLE
Adding a CopyFrom method to List?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#2860]
This was the topic of [an SO question](http://stackoverflow.com/questions/32030510/best-way-to-copy-over-items-to-a-list-partially) I had asked previously, but I'll repeat it here. (Also, API addition questions are probably more appropriate for CoreFX than CoreCLR.)

If you have 2 arrays that you have allocated, `src` and `dest`, and you want to copy the contents from one over to the other, you just do

    Array.Copy(src, dest, src.Length);

as opposed to a manual for-loop:

    for (int i = 0; i < src.Length; i++) dest[i] = src[i];

which is both slower and more verbose.

Likewise, can we add `CopyFrom(ICollection<T>, int)` and `List.Copy(IList<T>, int, List<T>, int, int)` methods to List, since it's internally implemented with an array? From my [perf test](https://dotnetfiddle.net/PUtuxk) in #2707 it already looks like Array.Copy is significantly faster than a manual for-loop to copy the array, and this combined with the fact that [the List indexer does not look inlineable at the moment](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/List.cs#L171-L189), I'm guessing that there would be a noticeable speed up for applications that do this.

**Comment by svick** [comment]
> for applications that do this

I think that's the important question here. Do applications actually commonly copy from (part of) one `List` to another? And isn't `AddRange()` sufficient for copying the whole `List`?

**Comment by jamesqo** [comment]
@svick It's not just from one List to another, it's any array/collection copying to a List.

AddRange or the List ctor will construct a new List; to be clear, I'm talking about overwriting parts of an existing one.
