### ISSUE TITLE
AppDomain SetPrincipalPolicy not implemented

### ISSUE THREAD

**Issue by tomeks666** [dotnet/corefx#28614]
corefx/src/System.Runtime.Extensions/src/System/AppDomain.cs

public void SetPrincipalPolicy(PrincipalPolicy policy) { }

This is clearly unimplemented. Maybe [ObsoleteAttribute] could be added to spare people frustration.

**Comment by danmosemsft** [comment]
@tomeks666 what are you trying to achieve? I see that Thread does not read the principal off the appdomain so SetThreadPrincipal is likewise not meaningful. I don't know much about principle based policy but this part at least does not seem wired up. @jkotas is this intended? Seems partly related to CAS but also to impersonation.

**Comment by jkotas** [comment]
I think that this is something that could have been implemented in more compatible way.

**Comment by jkotas** [comment]
@tomeks666 We have https://github.com/dotnet/platform-compat Roslyn analyzer that emits warnings like what you are suggesting.

This API was likely left unimplemented by accident because of the API name suggests that it is related to CAS, but it really is not. We should fill in the implementation.

**Comment by stephentoub** [comment]
It shouldn't be hard to fill in an implementation, except for the WindowsPrincipal dependency, which could either be omitted, utilize reflection, or force us to push WindowsPrincipal down in the layers.

**Comment by jkotas** [comment]
I think it should use reflection.

**Comment by danmosemsft** [comment]
We see 4% of apps scanned for compat have calls to this method. (It seems negligible use in libraries though). However  I do not recall other reports of hitting this.

@tomeks666 does this block adoption for you? What is the impact?

**Comment by tomeks666** [comment]
@danmosemsft
No it does not block adoption. It was just testing.

**Comment by danmosemsft** [comment]
@tomeks666 thanks for the report, we will fix: https://github.com/dotnet/corefx/issues/30187
