### ISSUE TITLE
CoreFx test utility depends on Microsoft.DotNet.PlatformAbstractions

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#28620]
@krwq @tarekgh @eerhardt added a dependency on Microsoft.DotNet.PlatformAbstractions to CoreFx.TestUtilities in https://github.com/dotnet/corefx/pull/24531. That cause a cycle in our build-from-source efforts so we have to figure out a solution to break that cycle. 

For now I'm going to break the cycle by pinning to an existing version but we cannot do that in general because it requires us to have an existing binary which is bad for new-distro bring-up.  

@eerhardt what is your thoughts on bring Microsoft.DotNet.PlatformAbstractions into corefx?

**Comment by weshaggard** [comment]
See https://github.com/dotnet/corefx/commit/fa9fe16c3e099faffe99d0a3301af0fa70dbe752 for how I plan to pin it for now.

**Comment by eerhardt** [comment]
> @eerhardt what is your thoughts on bring Microsoft.DotNet.PlatformAbstractions into corefx?

I would absolutely LOVE for this to happen.

However, I don't think it should go wholesale into corefx.  I think pieces of it should be removed altogether (I'm looking at you [HashCodeCombiner](https://github.com/dotnet/core-setup/blob/master/src/managed/Microsoft.DotNet.PlatformAbstractions/HashCodeCombiner.cs) and [Platform](https://github.com/dotnet/core-setup/blob/master/src/managed/Microsoft.DotNet.PlatformAbstractions/Platform.cs)).  

And some things should be folded into `System.Runtime.InteropServices.RuntimeInformation`, like [RuntimeEnvironment](https://github.com/dotnet/core-setup/blob/master/src/managed/Microsoft.DotNet.PlatformAbstractions/RuntimeEnvironment.cs).

[ApplicationEnvironment](https://github.com/dotnet/core-setup/blob/master/src/managed/Microsoft.DotNet.PlatformAbstractions/ApplicationEnvironment.cs) can probably be deleted as well now that we have `netstandard2.0`.  I'm not exactly sure what it's main purpose was - mostly for `net45` and `netstandard1.3` code to be able to call 1 method to get the BaseDirectory without having to `#if` themselves.  With `netstandard2.0`, users can now call `AppContext.BaseDirectory`, or `AppDomain.CurrentDomain.BaseDirectory` for this.

So thinking about it more - probably move RuntimeEnvironment into RuntimeInformation, and delete the rest.  Obviously the library will still live in servicing branches, if we ever need to service the already released versions of it.  And users can continue to use the already released versions all they want.

**Comment by kasper3** [comment]
[if former offsets the latter] maybe we can try to think it in light of the proposed API at https://github.com/dotnet/corefx/issues/27417 for public consumption when bringing over
https://github.com/dotnet/core-setup/tree/fd1dc48fad5bc32258c8c0fc885fbf4b1e32bebd/src/managed/Microsoft.DotNet.PlatformAbstractions to corefx?

**Comment by weshaggard** [comment]
Looks like we have a few issues that are tracking similar things https://github.com/dotnet/corefx/issues/16629, https://github.com/dotnet/corefx/issues/17452, 
 https://github.com/dotnet/corefx/issues/24522, https://github.com/dotnet/corefx/issues/25530, https://github.com/dotnet/corefx/issues/28132, https://github.com/dotnet/corefx/issues/23197

I hope we can tackle a number of them as part of moving these APIs into corefx.
