### ISSUE TITLE
Leaky abstraction in ThreadPool.[Unsafe]RegisterWaitForSingleObject

### ISSUE THREAD

**Issue by poizan42** [dotnet/corefx#2865]
I just went into the pitfall of using a waithandle in two different registrations. The documentation states the following:

> The wait thread uses the Win32 WaitForMultipleObjects function to monitor registered wait operations. Therefore, if you must use the same native operating system handle in multiple calls to RegisterWaitForSingleObject, you must duplicate the handle using the Win32 DuplicateHandle function.

It seems quite bad when the documentation is encouraging you to write non-portable code, and P/Invoking to DuplicateHandle requires full trust. Would it be a big problem to detect that the same handle is there twice with two different registrations and correctly wait for it and queue both action on the thread pool when the waithandle becomes ready?

**Comment by ericeil** [comment]
Thanks for the suggestion.  FWIW, WaitHandle.WaitAny/WaitAll have a similar limitation, due to their use of the same underlying Windows API.  I worry that adding a check for duplicates would add overhead to *all* uses of these methods, when most of the time the check is unnecessary.  I wonder if it would be better to add a Duplicate method to WaitHandle, so that it's less onerous for users to work around this restriction?

**Comment by poizan42** [comment]
When you call WaitHandle.WaitAny/WaitAll then you have complete control at the call site, so at least it is less of a problem here. In the case with the thread pool you might need global information to know whether someone else has registered a wait for that same handle. Also I think partial-trust code can interfere with full-trust code if a wait handle is exposed that the full-trust code has registered a wait on - that sounds a bit dangerous.

**Comment by karelz** [comment]
We need API proposal here.

**Comment by stephentoub** [comment]
Thanks for the suggestion, but the lack of progress or upvotes here in four years suggests this isn't worth investing in, especially as synchronously blocking on WaitHandles in this manner is discouraged in favor of using async/await whenever possible, so I'm going to close this. Thanks.
