### ISSUE TITLE
ParallelEnumerable.Aggregate XML documentation appears to be incorrect.

### ISSUE THREAD

**Issue by shaunluttin** [dotnet/corefx#28655]
The [summary documentation](https://github.com/dotnet/corefx/blob/a38c5000be0d4b98445ef43d642614d0e8d8f82d/src/System.Linq.Parallel/src/System/Linq/ParallelEnumerable.cs#L1655) for the `ParallelEnumerable.Aggregate` method says: 

> Applies in parallel an accumulator function over a sequence.

The implementation, however, delegates to the `PerformSequentialAggregation` method, which applies the accumulator function sequentially. 

Unless there is something I'm missing, the documentation is discrepant and would more accurately say this: 

> Applies an accumulator function sequentially over a sequence.

**Comment by tarekgh** [comment]
@shaunluttin do you want to provide the fix?

**Comment by stephentoub** [comment]
I actually don't think we should change this. It's an implementation detail that it's currently serialized. It'd be an issue if the docs said it was serialized and then it ran in parallel, but the opposite is fine. And if we change the docs to say sequential, we'll never be able to make it parallel in the future, as that would be a breaking change.

**Comment by shaunluttin** [comment]
Thank you for taking a look at this. The decision not to fix makes sense. The current documentation is confusing ([it lead to this conversation on StackOverflow](https://stackoverflow.com/questions/49523954/why-do-we-not-get-a-performance-improvement-with-pseq)) but it isn't the end of the world.
