### ISSUE TITLE
NamedArgumentTests.cs in src/Microsoft.CSharp/tests doesn't reset Console.Out

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/corefx#28667]
Tests in that file are setting Console.Out to a custom stream but don't reset it at the end:
https://github.com/dotnet/corefx/blob/e3694f9b8a69d21d1cb0e30412b7e52079ae69d6/src/Microsoft.CSharp/tests/NamedArgumentTests.cs#L369-L370

This results in the following output when running the tests:

```
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

  Discovering: Microsoft.CSharp.Tests
  Discovered:  Microsoft.CSharp.Tests
  Starting:    Microsoft.CSharp.Tests
```

Note that the `Finished:    Microsoft.CSharp.Tests` or the Test Result Summary isn't visible.

The tests should have a finally that resets Console.Out to the original value, like other corefx tests are doing: https://github.com/dotnet/corefx/blob/e3694f9b8a69d21d1cb0e30412b7e52079ae69d6/src/System.Console/tests/Helpers.cs#L55-L64.

**Comment by matekm** [comment]
if that is up for grabs, can I work on it?
