### ISSUE TITLE
ArrayMemoryPool shouldn't dispose block on Unpin

### ISSUE THREAD

**Issue by pakrym** [dotnet/corefx#28689]
https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/Buffers/ArrayMemoryPool.ArrayMemoryPoolBuffer.cs#L110

/cc @ahsonkhan @GrabYourPitchforks

**Comment by benaadams** [comment]
Has an unnecessary loop read also

**Comment by benaadams** [comment]
https://github.com/dotnet/corefx/pull/28690

**Comment by benaadams** [comment]
I think its current behaviour is correct; its just written a bit strange; its disposing when count reaches 0

**Comment by pakrym** [comment]
I don't think pinning/unpinning should not have any effect on disposal at all. Block should be alive until explicitly disposed.

**Comment by benaadams** [comment]
Its probably a bit wrong anyway, Dispose shouldn't return to Pool if still pinned?

Pin
Dispose // shouldn't return to pool here
UnPin // should return to pool here as already disposed

**Comment by pakrym** [comment]
Dispose should throw if pinned, but that is just a diagnostic.

**Comment by benaadams** [comment]
https://github.com/dotnet/corefx/pull/28690#issuecomment-377735699

> The fix is to remove all reference counting from the array pool.

**Comment by pakrym** [comment]
If we don't wan't that diagnostic - yes, just implement IMemoryOwner

**Comment by benaadams** [comment]
Removed ref counting in https://github.com/dotnet/corefx/pull/28690; it was overpromising for its implementation (conurrency vs disposal)
