### ISSUE TITLE
Bug: DelimitedListTraceListener Class strange output

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/corefx#28697]
I think there is something wrong with the DelimitedListTraceListener class. I used this code:
```
var Listener = new DelimitedListTraceListener("test.txt");
Listener.Delimiter = ",";
Trace.Listeners.Add(Listener);
Trace.Write("x");
Trace.WriteLine("y");
Trace.TraceError("z");
Trace.TraceInformation("w");
Trace.Flush();

```
And this is what I found written in the file:
> xy
"WindowsFormsApp8.exe",Error,0,"z",,,,,,,
"WindowsFormsApp8.exe",Information,0,"w",,,,,,,

Is this right? And if it is, what does it mean? Why doesn't the write method add the delimiter, and what are those too many delimiters added by the TraceError and TraceInformation methods?

By the way:
I suggest to add Write(string[]) and Write(object[]) overloads to write the array elements separated by the delimiter.

**Comment by MohammadHamdyGhanem** [comment]
Another Strange Note:
I tested the previouse code in a .net Core console app, but it didn't even create the file, and after I created the file it didn't write any thing to it!
I had to modify the code to create the file myself and then close it:
```
var s = File.Open ("test.txt", FileMode.OpenOrCreate);
var Listener = new DelimitedListTraceListener(s);
Listener.Delimiter = ",";
Trace.Listeners.Add(Listener);
Trace.Write("x");
Trace.WriteLine("y");
Trace.TraceError("z");
Trace.TraceInformation("w");
Trace.Flush();
Trace.Close();
```

**Comment by MohammadHamdyGhanem** [comment]
@karelz 
Please lable this issue as a bug too. I reported another bug in the second post.
thanks

**Comment by karelz** [comment]
@MohammadHamdyGhanem where is the bug report? I see only question and potentially feature request, which should be filed separately once clarified. I let area owners/experts to make further decisions/adjustments here.
IMO the behavior above is as designed - Write method allows you to add anything, outside of the delimiter rules as there is nothing to delimit.

**Comment by MohammadHamdyGhanem** [comment]
@karelz 
So, when is a delimiter added, and what are those 8 delimiters at the end of the line?
Besides, my second post reported another bug.
Thanks

**Comment by karelz** [comment]
@MohammadHamdyGhanem from your example it looks like delimiters are added only when you use `Trace*` methods. Why 8? - That's a good question. I assume it is some fixed schema. Did you check the source code?
I missed your 2nd post - that is entirely unrelated to your original question, please file a new issue. It doesn't help to mix things together - it just creates confusion (as you can see) and we lose track what's been solved vs. not.

**Comment by MohammadHamdyGhanem** [comment]
I tested the DelimitedListTraceListener class with the trace source:
```
        var mySource = new TraceSource("Testsource", SourceLevels.All);
        var Listener = new DelimitedListTraceListener("test.txt");
        Listener.Delimiter = ",";
        mySource.Listeners.Add(Listener);
        mySource.TraceData(TraceEventType.Information, 1, "x");
        mySource.TraceInformation("y");
        mySource.TraceEvent(TraceEventType.Error, 2, "z");
        mySource.TraceInformation("w");
        mySource.Flush();
        mySource.Close();
```
And I got this result:

> "Testsource",Information,1,,"x",,,,,,
> "Testsource",Information,0,"y",,,,,,,
> "Testsource",Error,2,"z",,,,,,,
> "Testsource",Information,0,"w",,,,,,,

**Comment by karelz** [comment]
Which seems to be perfectly fine, no weird things happening there as far as I can see.

**Comment by MohammadHamdyGhanem** [comment]
@karelz 
If this is normal, what kind of formatting is that, and who uses it to do what?
This what the docs say:
> The delimiter is used to terminate each field in a line of output. For example, to display the trace output in a Microsoft Excel spreadsheet, you might specify a comma (",") as a delimiter and create a comma-separated value (CSV) file. 

There is no sample on using this class, and I tried the methods of The Trace and TraceSource classes but thet gave the shown results, which are far from what the docs say!
So, is there any method to add "fields in a line of output" to be delimited?
Thanks.

**Comment by MohammadHamdyGhanem** [comment]
By the way:
Why there are two commas between 1 and "x" in first line:
"Testsource",Information,1,,"x",,,,,,

**Comment by stephentoub** [comment]
Because it supports writing out other additional pieces of information, based on https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracelistener.traceoutputoptions?view=netframework-4.7.1#System_Diagnostics_TraceListener_TraceOutputOptions.

Try adding:
```C#
Listener.TraceOutputOptions = TraceOptions.DateTime | TraceOptions.ProcessId | TraceOptions.ThreadId | TraceOptions.Timestamp;
```
for example after you construct the Listener and you'll see.

**Comment by stephentoub** [comment]
> Why?

Because it leaves a column for data traced by TraceData.
