### ISSUE TITLE
ArrayMemoryPool<T> should pool ArrayMemoryPoolBuffer

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#28693]
Using bounded ConcurrentQueue.Segment as per https://github.com/dotnet/corefx/pull/28638 (to have upper limit on number pooled)

Otherwise it allocates for every `Rent`; which is a bit poor for a pool

/cc @pakrym @GrabYourPitchforks @ahsonkhan @davidfowl @stephentoub

**Comment by GrabYourPitchforks** [comment]
This behavior is by design. See https://gist.github.com/GrabYourPitchforks/8efb15abbd90bc5b128f64981766e834, specifically the second example under the section "Creating custom pools" for reasoning and alternatives.
