### ISSUE TITLE
Centralize all calls to FormatMessage

### ISSUE THREAD

**Issue by davkean** [dotnet/corefx#287]
Currently we have at least two places where we call FormatMessage; Win32Exception and Win32Marshal. The former was updated to handle messages that exceeded the buffer, but the later was not.

1. Move the FormatMessage code in Win32Exception -> Win32Marshal.GetMessage
1. Look for calls to FormatMessage and make sure they go through Win32Marshal.
1. Look at the buffer size that we're passing to FormatMessage in Win32Exception, it looks like we're trying to account for trailing null, but interop already does that for us. This is a bug waiting to happen if a message happens to fall on the buffer's boundary.
1. Figure out why we're attempting to remove extraneous trailing chars? If there's extra chars in the message - we should be filling bugs against Windows to fix them, not doing something special.

**Comment by dziner** [comment]
To make the calls go through Win32Marshal, Common folder need to be added/ linked to projects and also some of the constants are defined in multiple projects where Win32Marshal is being linked for eg. "Interop.ERROR_FILE_NOT_FOUND" and also string resource values are defined in individual projects that are linking this file eg. "SR.UnknownError_Num". If no body has started working on this, I can take this up and move all dependent constants for Win32Marshal into src/Common/Interop folder and also all the dependent string resources as well.

**Comment by adimosh** [comment]
I started on it. Will be ready about the end of the week.

Sent from my Windows Phone
________________________________

**Comment by davkean** [comment]
I would split this into two items; don't yet introduce a common set of resources - we don't have a way to handle this in the various tool chains we have internally. Instead, centralize FormatMessage itself - but leave or introduce the required strings into each individual project's resources. Later, we'll go back and fix that.

**Comment by adimosh** [comment]
The common set of resources is not yet feasible, since they are split in other situations as well between projects. That would be its own work item, to preserve the current standard.

**Comment by davkean** [comment]
I looked at trying to find history on why we do 4) - unfortunately, the trail stopped dead in 2000 (it was introduced before then). @ericstj's trying to dig back further, and I'll reply to the thread when I have more information. I suspect we encountered some badly formatted error messages (maybe training newlines?) and we tried to clean them up.
