### ISSUE TITLE
SocketsHttpHandler: Proxied IP address (IPv4 & IPv6) requests missing `Proxy-Connection: Keep-Alive` header

### ISSUE THREAD

**Issue by caesar1995** [dotnet/corefx#28708]
Example:

WinHttpHandler & Framework:

`In value: List<String> ["GET http://321.123.456.789/ HTTP/1.1", "Proxy-Connection: Keep-Alive", "Host: 321.123.456.789"]`
`In value: List<String> ["GET http://[::1234]/ HTTP/1.1", "Host: [::1234]", "Proxy-Connection: Keep-Alive"]`

SocketsHttpHandler:

`In value: List<String> ["GET http://321.123.456.789/ HTTP/1.1", "Host: 321.123.456.789"]`
`In value: List<String> ["GET http://::1234/ HTTP/1.1", "Host: [::1234]"]`

`Proxy-Connection: Keep-Alive` header is missing in both cases.

**Comment by davidsh** [comment]
Despite the difference, is this really causing a problem?  This header is not actually widely used.

See: https://stackoverflow.com/questions/15460819/what-is-the-difference-between-connection-and-proxy-connection-in-http-header

**Comment by davidsh** [comment]
And with HTTP/1.1 being used, the default for connections is for 'keep-alive'.  So using any request headers for 'keep-alive' ('Connection' or 'Proxy-Connection') is a waste of bytes:

https://trac.ietf.org/trac/httpbis/ticket/158

>As a result, HTTP/1.1 clients ought not to send the Proxy-Connection or Keep-Alive header; at best, they will waste bytes in requests, and at worst they can cause interoperability problems.

**Comment by davidsh** [comment]
cc: @geoffkizer @stephentoub

**Comment by geoffkizer** [comment]
I agree.

**Comment by karelz** [comment]
OK, sounds reasonable. If we hit problems with some older/non-compliant servers or network gear, we can change it later. Let's wait for customer feedback. Closing.

**Comment by davidsh** [comment]
cc: @Tratcher
