### ISSUE TITLE
Directory.Exists returns false with drive's device path name

### ISSUE THREAD

**Issue by EmmaZhu** [dotnet/corefx#28713]
Hi,

Code like `Directory.Exists("\\\\?\\C:\\")` always returns false, even the drive does exist. `Directory.Exists("\\\\?\\C:\\Folder\\")` can get directory's existence correct.  This behavior is different with the one in .Net Framework. Could anyone help to take a look?

[EDIT] Add proper code formatting by @karelz

**Comment by stephentoub** [comment]
cc: @JeremyKuhne, @danmosemsft

**Comment by danmosemsft** [comment]
@Anipik please evaluate and put up PR if appropriate.

**Comment by Anipik** [comment]
I am looking into it

**Comment by danmosemsft** [comment]
@weshaggard we should get this in before the last Preview 2 merge.

**Comment by danmosemsft** [comment]
Oh, I see that's already in progress. Well, don't wait.

**Comment by Anipik** [comment]
@EmmaZhu can you tell me your .net core version ? I am not able to repro your problem in 2.1 and 2.0

**Comment by Anipik** [comment]
@EmmaZhu the behavior you are describing happens on full framework. The fullframework directory.exists return false in case of paths with extended prefix

**Comment by danmosemsft** [comment]
If you have set the app context flag UseLegacyPathHandling.

**Comment by EmmaZhu** [comment]
@Anipik What do you mean about the full framework? Anyway I can fix this in my code?

**Comment by EmmaZhu** [comment]
d:\Projects\CrashTest>dotnet --version
2.1.300-preview2-008012

I don't have a config file in my project. I think UseLegacyPathHandling should use the default value.

**Comment by EmmaZhu** [comment]
@Anipik I can repo it with "<TargetFramework>netcoreapp2.1</TargetFramework>", it returns true with netcoreapp2.0.  I didn't set UseLegacyPathHandling.

```
>dotnet --version
2.1.300-preview2-008012
```

**Comment by EmmaZhu** [comment]
@Anipik  What do you mean about the full framework? Anyway I can change it?

**Comment by Anipik** [comment]
by full framework I meant .NET Framework. How are you using NetCoreApp2.1 ? you can try updating it to the most recent build. Because I am not able to repro in NetCoreApp2.1. You can download the latest version of netcoreapp2.1 from https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md

**Comment by JeremyKuhne** [comment]
@EmmaZhu can you give a step-by-step repro? I'll take a look as well to see if I can replicate your issue. Other data that might be useful:

- What OS/version are you using?
- Is the user account part of the administrator's group? Are you running as admin or not?
- Can you run `diskpart` and `list volume`?

Example diskpart output:

```
DISKPART> list volume

  Volume ###  Ltr  Label        Fs     Type        Size     Status     Info
  ----------  ---  -----------  -----  ----------  -------  ---------  --------
  Volume 0     D   Data         NTFS   Stripe      3725 GB  Healthy
  Volume 1     C   OSDisk       NTFS   Partition    475 GB  Healthy    Boot
  Volume 2         Windows RE   NTFS   Partition    499 MB  Healthy    Hidden
  Volume 3         SYSTEM       FAT32  Partition    499 MB  Healthy    System
  Volume 4     E   Swap         NTFS   Partition    238 GB  Healthy
```

You can then select the volume (e.g. `select volume 1` for `C:` in this case), and then run `detail volume`.

```
DISKPART> detail volume

  Disk ###  Status         Size     Free     Dyn  Gpt
  --------  -------------  -------  -------  ---  ---
* Disk 0    Online          476 GB      0 B        *

Read-only              : No
Hidden                 : No
No Default Drive Letter: No
Shadow Copy            : No
Offline                : No
BitLocker Encrypted    : Yes
Installable            : Yes

Volume Capacity        :  475 GB
Volume Free Space      :  302 GB
```

Probably doesn't have any bearing on the repro, but as @Anipik isn't reproducing it I'd like to be extra thorough.

**Comment by EmmaZhu** [comment]
Thanks all for your help.

I've tried with upgraded to the latest daily build, and the issue doesn't exist anymore. Seems it should have been fixed. 

I'll close this issue.
