### ISSUE TITLE
Getting warning with some packages when I build

### ISSUE THREAD

**Issue by pantonis** [dotnet/corefx#28711]
I updated my .net library to 4.7.1. It successfully builds but I get some warnings:

![image](https://user-images.githubusercontent.com/3295086/38188333-3310b3fc-3664-11e8-918a-4dca175bf574.png)

I removed the packages and reinstalled them, rebuild, but still the same warnings.

**Comment by karelz** [comment]
Are you targeting .NET Framework or .NET Standard?
Are you able to reproduce it when upgrading test project?

cc @joperezr

**Comment by joperezr** [comment]
if you could provide us with a binlog then we could do some investigation. Or even better, if you have a minimal repro that would be ideal.

**Comment by pantonis** [comment]
@karelz .NET Framework. 
@joperezr binlog?

**Comment by joperezr** [comment]
sorry, in order to generate a binlog, from a developer command prompt, try running `msbuild yourProject.csproj /bl /t:rebuild`. This extra `/bl` argument will generate a binlog that will help us diagnose why are you seeing these errors.

**Comment by pantonis** [comment]
@joperezr Since this is an enterprise system I cannot post binlon publicly here. Could you provide me with an email address please?

Thanks

**Comment by joperezr** [comment]
Sure, my email is joperezr@microsoft.com

**Comment by pantonis** [comment]
I have sent it,

Thanks

**Comment by pantonis** [comment]
@joperezr Any news on this one?

**Comment by joperezr** [comment]
quick question for you @pantonis are you using `<PackageReference` or packages.config? In case of the latter, does the problem repro when moving to PackageReference instead?

**Comment by pantonis** [comment]
@joperezr I have try to follow migration [steps ](https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference) but in Step 2 I cannot see any option Migrate packages.config to PackageReference

![image](https://user-images.githubusercontent.com/3295086/40609390-2bb03738-6277-11e8-82a5-7da61d32f526.png)

**Comment by pantonis** [comment]
@joperezr Finally I managed to migrate to PackageReference. But the references are less now and all the packages that I was getting warning are gone.

**Comment by joperezr** [comment]
Great! I'm glad this fixed the issue!

**Comment by joperezr** [comment]
Closing since it seems the issue was fixed by moving to PackageReference.
