### ISSUE TITLE
Investigate disabled tests which are already fixed

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#28727]
- [x] Find tests marked as ActiveIssue which are no longer active
- [x] <s>Re-enable issues</s> Send e-mails to owners/ping/reopen issue

cc: @karelz

**Comment by krwq** [comment]
@karelz I've sent e-mails to owners with short investigation and reopened bugs where it was closed by mistake (or closed because there was no repro because test case was disabled).

**Comment by karelz** [comment]
Great, thanks!
