### ISSUE TITLE
Is there any way to localize validation error messages  when checking xml by xsd scheme?

### ISSUE THREAD

**Issue by amb4eg** [dotnet/corefx#28764]
Is there any way to localize validation error messages  when checking xml by xsd scheme?
I could not find any information about it. In netframework this problem was solved by language packs. There is a way to overload resources  System.Private.Xml.dll  so that messages are taken from the current culture ?

**Comment by QtRoS** [comment]
I also need this functionaly. After spending some time on source code exploration, I would say that there is no way to easily localize these messages other than to force runtime to use localized *.resx files. But in such case all your exceptions will be localized, for example 'Object reference not set to an instance of an object' will become 'Ссылка на объект не указывает на экземпляр объекта' in Russian locale. For me it is ok. And I can easily do this in .NET Framework:
    Thread.CurrentThread.CurrentCulture = new CultureInfo(...);
    Thread.CurrentUIThread.CurrentCulture = new CultureInfo(...);
But this approach doesn't work in .NET Core. 

Minimal example: https://paste.ofcode.org/33aRRBqj96JwDdphRYZk3GU
This code will show me localized exception if it runs on .NET Framework 4.6 (console app) and original English message if it runs on .NET Core 2 (console app). Tested on windows 7.

**Comment by QtRoS** [comment]
@karelz if you take in account my example it more looks like a bug than a question...

**Comment by karelz** [comment]
@QtRoS I let area owners to make the final call here.

**Comment by krwq** [comment]
@amb4eg @QtRoS I believe corefx is currently not localized. I will close this issue since this is related to a generic problem. Here are related issues/comments - please add comments there:
https://github.com/dotnet/corefx/issues/743
https://github.com/dotnet/corefx/issues/17464#issuecomment-288911509
https://github.com/dotnet/corefx/issues/25128#issuecomment-348269974
