### ISSUE TITLE
Extra test should be added for Dictionary

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#28763]
This code should work
```csharp
var d = new Dictionary<string,string>();
d.Add("a", "b");
d.Add("c", "d");
foreach (var e in d)
{
    if (d.Remove(e.Key + "Sibling")) break;
}
```

From https://github.com/dotnet/coreclr/pull/17196#issuecomment-377360621

/cc @danmosemsft Just so it doesn't fall off the radar

**Comment by danmosemsft** [comment]
@maryamariyan mind adding this?

**Comment by maryamariyan** [comment]
@danmosemsft sure, thanks

**Comment by benaadams** [comment]
For background; I changed `Remove` to always increment version rather than to do it only when an item was removed which would mean that example would throw an exception about the enumerator no longer being valid (then reverted it) https://github.com/dotnet/coreclr/pull/17196#issuecomment-376003647
