### ISSUE TITLE
 Default Proxy issues

### ISSUE THREAD

**Issue by IeuanWalker** [dotnet/corefx#28780]
# Default Proxy issues
Our organisation has a proxy and in previous versions on .NET (.net full framework), you can add the following to the web.config and the application will use your system's default proxy.

```XML
<system.net>
   <defaultProxy useDefaultCredentials="true" />
</system.net>
```
I have tried a lot of different options but just cant seem to get anything to work.

```csharp
string username = "test";
string password = "test";
WebProxy proxy = new WebProxy($"http://{username}:{password}@bluecoat.domain.gov.uk", 8080)
{
    Address = new Uri("http://{username}:{password}@bluecoat.domain.gov.uk:8080"),
    Credentials = new NetworkCredential(username, password)
};
HttpClientHandler clientHandler = new HttpClientHandler
{
    Proxy = proxy,
    UseProxy = true,
    Credentials = new NetworkCredential(username, password)
};
var httpClient = new HttpClient(clientHandler);
```

Any help would be greatly appreciated.

**Comment by wfurt** [comment]
You should not need user & password in Uri. What version of .Net and OS is failing for you? 
If the request failing to authenticate or is it not going to proxy at all?

**Comment by davidsh** [comment]
If you simply want to use the default system proxy and need to pass default credentials to that proxy during HTTP requests, then do this:

```c#
var handler = new HttpClientHandler();
handler.DefaultProxyCredentials = CredentialCache.DefaultCredentials;
var client = new HttpClient(handler);

// Now use 'client' to do requests.
```

**Comment by davidsh** [comment]
Also, putting username and password into the Uri itself is a deprecated concept and is ignored in the HTTP stacks of .NET Framework and .NET Core.

>WebProxy proxy = new WebProxy($"http://{username}:{password}@bluecoat.domain.gov.uk", 8080)

**Comment by weliwita** [comment]
I'm also having proxy issues with MacOs. 
`
static void Main(string[] args)
        {
            HttpClientHandler handler = new HttpClientHandler();
            var client = new HttpClient(handler);
            string baseUrl = "http://www.bbc.com";

            try
            {
                HttpResponseMessage res = client.GetAsync(baseUrl).Result;
                if (res.IsSuccessStatusCode)
                {
                    Console.WriteLine("Success");
                }
                else
                {
                    Console.WriteLine("Failed");
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }
`

This code doesn't respect proxy settings configured on MacOs. Is default proxy is not used by HttpClient or am I missing some configuration? I have also posted this on stackoverflow https://stackoverflow.com/questions/49653986/dotnet-core-httpclient-doesnt-respect-proxy-settings-on-mac

**Comment by wfurt** [comment]
On OSX You have to "export http_proxy http://proxy.server.com:3128" 
curl library we use under the cover does not know how to read  system settings. 
Future work is tracked in https://github.com/dotnet/corefx/issues/26593

**Comment by davidsh** [comment]
@IeuanWalker I think your questions about to enable default credentials use for the default system proxy have been answered above.  So, we'll close this issue now.
