### ISSUE TITLE
Cannot save settings in .NETCore app

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#28784]
System.Configuration.ConfigurationManager exposes settings and I was able to make these work for read, but they fail to save.

I see:
```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'System.Configuration.ConfigurationUserLevel' to type 'System.Configuration.ConfigurationFileMap'.
  Source=System.Configuration.ConfigurationManager
  StackTrace:
   at System.Configuration.Configuration..ctor(String locationSubPath, Type typeConfigHost, Object[] hostInitConfigurationParams)
   at System.Configuration.Internal.InternalConfigConfigurationFactory.System.Configuration.Internal.IInternalConfigConfigurationFactory.Create(Type typeConfigHost, Object[] hostInitConfigurationParams)
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   at System.Configuration.LocalFileSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection values)
   at System.Configuration.SettingsBase.SaveCore()
   at System.Configuration.SettingsBase.Save()
   at settingsCore.Program.Main(String[] args) in c:\Users\ericstj\source\repos\settings\settingsCore\Program.cs:line 13
```

This appears to be a bug in `ImplicitMachineConfigHost` where it assumes the caller of `IInternalConfigConfigurationFactory.Create` will always specify a `ConfigurationFileMap` as the first parameter.  This is not the case for `ClientSettingsStore.OpenExeConfiguration` which specifies a `ConfigurationUserLevel`.

I was able to workaround this by creating a private copy of ConfigurationManager that changed the [casts](https://github.com/dotnet/corefx/blob/a8dce7c1c905e994c9519e0f26b0497832942a10/src/System.Configuration.ConfigurationManager/src/System/Configuration/ImplicitMachineConfigHost.cs#L26-L34) in `ImplicitMachineConfigHost` to `as ConfigurationFileMap` but I'm not sure if that's the best fix:  Can machine.config ever play a part in settings resolution?  It doesn't seem likely but it may make sense to see what happens in desktop and see if falls back to anything in machine.config.  If so, then we might want to see how to plumb `ImplicitMachineConfigHost` in this case.

Here's a repro project:
[settingsCore.zip](https://github.com/dotnet/corefx/files/1872736/settingsCore.zip)

**Comment by eltiare** [comment]
I'm getting this on a Windows UWP app as well. I believe I'm using the latest .NET version.

**Comment by ericstj** [comment]
Yes, the implementation is the same.  /cc @JeremyKuhne

**Comment by karelz** [comment]
Moving to 2.2 per @JeremyKuhne's info and offline confirmation: https://github.com/dotnet/corefx/pull/28894#issuecomment-381366648

**Comment by JeremyKuhne** [comment]
There are additional issues below the obvious issue. The linked PR can't make it past CI, but passes locally. Given the time I think this should be dealt with in 2.2 where we can give it time to bake (once we've figured out why it is tripping up).

**Comment by ericstj** [comment]
Making sure this gets added to the WPF/WinForms support project.  I encountered this when porting WPF/Winforms apps.  Without a fix here the settings APIs are broken for saving customer settings (like app settings, UI state, etc).
