### ISSUE TITLE
Investigate redundant IdnMapping calls

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#28787]
https://github.com/dotnet/corefx/pull/28725 is adding IdnMapping call in SslStream which have made IdnMapping call in HttpClient (SocketsHttpHandler) redundant.

cc: @davidsh

**Comment by stephentoub** [comment]
@krwq, I don't see any remaining references to `IdnMapping` under `corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler`.  Is there anything more to be done here?

**Comment by krwq** [comment]
@stephentoub, I think we should be able close, @davidsh any other places you can think of?

**Comment by stephentoub** [comment]
> When did the IdnMapping reference get deleted from src\System.Net.Http?

I wasn't aware there was one.  Which were you concerned about specifically?

**Comment by davidsh** [comment]
>Which were you concerned about specifically?

It was implied here: https://github.com/dotnet/corefx/pull/28725#issuecomment-378071894

that there was additional IdnMapping "higher up in the stack" with HttpClient.
