### ISSUE TITLE
Running UpdatePackageIndex Target should produce sorted results

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#28781]
currently, this target doesn't sort the produced results inside the JSON file.

please look at the https://github.com/dotnet/corefx/pull/28720#issuecomment-378320967 for more info.

**Comment by tarekgh** [comment]
CC @joperezr @ericstj @weshaggard

**Comment by joperezr** [comment]
yeah, I had chatted with @ericstj previously about this one. The fix is a one-liner change n buildtools repo so perhaps this issue should get moved there instead.

**Comment by ericstj** [comment]
I inspected the code and I actually think it is sorted, though by a slightly different identifier than one might expect.

The data is stored by framework : framework version : assembly version.  The framework gets sorted by the identifier (full form, sometimes prefixed with a dot) and profile.  This leads to things like .NETCoreApp appearing before monotouch, even though their short forms have the reverse order (montouch, netcoreapp).  Likewise the portable profiles end up being ordered by profile number.

I think this ordering is fine as is.

The diff that @tarekgh saw was the diff between @joperezr's change which manually applied a different sort, then back to the sort in the PackageIndex object model.

In the future we can avoid this by tooling the index using the public types in the buildtools assembly.
