### ISSUE TITLE
Difference in code and documentation of BlockingCollection.BoundedCapacity

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#28782]
@nerai commented on [Tue Apr 03 2018](https://github.com/dotnet/coreclr/issues/17395)

[.NET framework reference source of `BlockingCollection.BoundedCapacity`](https://referencesource.microsoft.com/#System/sys/system/collections/concurrent/BlockingCollection.cs,72) says:

> ... The bounded capacity of this collection, or int.MaxValue if no bound was supplied.

However, if no capacity is supplied in the ctor, it is called:

    Initialize(collection, NON_BOUNDED, collection.Count);

with

    private const int NON_BOUNDED = -1;

So the BoundedCapacity of an unbounded instance is -1, not int.MaxValue. To verify:

	var a = new BlockingCollection<int> ();
	Console.WriteLine (a.BoundedCapacity); // prints -1
	Console.WriteLine (int.MaxValue); // prints 2147483647

---

@RussKeldorph commented on [Tue Apr 03 2018](https://github.com/dotnet/coreclr/issues/17395#issuecomment-378327059)

@danmosemsft

**Comment by ianhays** [comment]
@nerai still planning on doing this one?

**Comment by nerai** [comment]
@ianhays Sorry, I lost this issue. I've put up a PR for the xml doc. Working on the actual docs now.

**Comment by nerai** [comment]
I was unable to find any mention of BoundedCapacity in https://github.com/dotnet/docs that suffers from the problem in this ticket.
