### ISSUE TITLE
Build failed requiring cmake, but cmake seems to be present

### ISSUE THREAD

**Issue by nerai** [dotnet/corefx#28799]
I am having a little trouble getting corefx to build. I ran the VS 2017 updater and freshly cloned master, then ran the sync script.

Cmake 3.11.0 was installed and I verified that its bin directory is listed when running the PATH command. Yet, there is an error `CMake is a pre-requisite to build this repository but it was not found on the path. Please install CMake...` followed by `Failed to generate native component build project!
Command execution failed with exit code 1.`

I would be glad for a pointer how this could be fixed. I noticed a `toolSetDir=c:\tools\clr` in the log. I'm not sure what this means, but this directory does not exist.

```
C:\dev\pub\dotnet\corefx>git clean -xdf
Removing Tools/
Removing bin/
Removing binclash.log
Removing init-tools.log
Removing msbuild.err
Removing msbuild.log
Removing msbuild.wrn
Removing packages/
Removing sync.log

C:\dev\pub\dotnet\corefx>build
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.6.4
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
Installing dotnet cli...
Restoring BuildTools version 2.1.0-preview3-02631-01...
Initializing BuildTools...
Done initializing tools.
Running: C:\dev\pub\dotnet\corefx\src\Native\build-native.cmd   x64  Debug  Windows_NT  --numproc 4  -portable  toolSetDir=c:\tools\clr
Tools are already initialized.
Running: C:\dev\pub\dotnet\corefx\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false /l:BinClashLogger,Tools\net46\Microsof
t.DotNet.Build.Tasks.dll;LogFile=binclash.log /p:ConfigurationGroup=Debug /p:BuildPackages=false /p:GenerateNativeVersionInfo=true  /flp:v=normal  /flp2:warning
sonly;logfile=msbuild.wrn  /flp3:errorsonly;logfile=msbuild.err  C:\dev\pub\dotnet\corefx\src\Native\..\../build.proj /t:GenerateVersionHeader

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.56
Command execution succeeded.
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.6.4
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86_x64'
Commencing build of native components

CMake is a pre-requisite to build this repository but it was not found on the path. Please install CMake from http://www.cmake.org/download/ and ensure it is on
 your path.
Failed to generate native component build project!
Command execution failed with exit code 1.

C:\dev\pub\dotnet\corefx>cmake
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.
```

**Comment by danmosemsft** [comment]
Hi @nerai this is coming from here https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/Native/Windows/probe-win.ps1#L53
Perhaps by adding some "printf" to this file you can figure out what is going on. Perhaps it is not finding cmake in the registry keys for some reason: https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/Native/Windows/probe-win.ps1#L7

If that's the case the message ought to explain that possibility.

**Comment by nerai** [comment]
@danmosemsft  Thank you, I believe I found the culprit.

I believe cmake was installed correctly and its key appeared in the registry. However, two conditions apply:

a) I used a non-default install location (not C:\Program Files or such)
b) cmake did not append its version number to its registry directory name

The latter caused the reg key to not be enumerated. Fixing that is easy, however, the version number is also used:

```
function GetCMakeInfo($regKey)
{
  # This no longer works for versions 3.5+
  try {
    $version = [System.Version] $regKey.PSChildName.Split(' ')[1]
  }
```

I presume the comment above, which was in the original file, relates to the version number missing in newer versions of cmake.

**Comment by danmosemsft** [comment]
Great. Would you like to offer a PR?

**Comment by am11** [comment]
This was fixed in CoreRT and ported to CoreCLR https://github.com/dotnet/coreclr/pull/16328. Can this file be shared between repos?

**Comment by nerai** [comment]
The related patch (https://github.com/dotnet/coreclr/commit/66f840939e81a6e240a01edfea61976363bc51d6) is pretty much identical with mine. Should I still upload a PR? Either way is fine with me.

**Comment by danmosemsft** [comment]
Yes please -- a cherry pick sounds good.
