### ISSUE TITLE
Custom string format "h" throw

### ISSUE THREAD

**Issue by iSazonov** [dotnet/corefx#28807]
From official [docs](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings) and [docs](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#the-h-custom-format-specifier):
"h" The hour, using a 12-hour clock from 1 to 12.
2009-06-15T01:45:30 -> 1
2009-06-15T13:45:30 -> 1

Really `datetime.ToString("h")` throw with "Input string was not in a correct format."
It throw only for one char string, any many char strings work well (" h","h ").

The issue present in current versions .Net Core 2.0 and .Net Framework. 

The issue was discovered in PowerShell repo https://github.com/PowerShell/PowerShell/pull/6542

**Comment by svick** [comment]
This is specifically called out in [the documentation you linked to](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#using-single-custom-format-specifiers) as the correct behavior:

> A custom date and time format string consists of two or more characters. Date and time formatting methods interpret any single-character string as a standard date and time format string. If they do not recognize the character as a valid format specifier, they throw a FormatException. For example, a format string that consists only of the specifier "h" is interpreted as a standard date and time format string. However, in this particular case, an exception is thrown because there is no "h" standard date and timeformat specifier.
>
> To use any of the custom date and time format specifiers as the only specifier in a format string […], include a space before or after the specifier, or include a percent ("%") format specifier before the single custom date and time specifier.

**Comment by iSazonov** [comment]
@svick Thanks for clarify! I skipped the notes - "%h" is resolved my issue.

Yes, the exception message could be better.
