### ISSUE TITLE
Calender.GetWeekOfYear is not compatible with ISO 8601 and date Unix utility

### ISSUE THREAD

**Issue by iSazonov** [dotnet/corefx#28808]
`System.Threading.Thread.CurrentThread.CurrentCulture.Calendar.GetWeekOfYear()` return values that are not compatible with ISO 8601 and `date` Unix utility in some edge cases.

ISO related [link](https://en.wikipedia.org/wiki/ISO_week_date#Relation_with_the_Gregorian_calendar)

The issue was discovered in PowerShell repo https://github.com/PowerShell/PowerShell/pull/6542 (You should use the build if you want tests with PowerShell Core `Get-Date` cmdlet).

- See 'First week' in https://en.wikipedia.org/wiki/ISO_week_date#Relation_with_the_Gregorian_calendar
> If it is on a Sunday, it is part of week 52 of the previous year.

\#'2017-01-01' is 'Sunday, January 1, 2017 12:00:00 AM'
date -d 2017-01-01 +%V #return 52 - right
Get-date 2017-01-01 -UFormat "%V" #return 1 - bug

- See 'Last week' in https://en.wikipedia.org/wiki/ISO_week_date#Relation_with_the_Gregorian_calendar
> If 31 December is on a Monday, Tuesday or Wednesday, it is in week 01 of the next year.

\#'2007-12-31' is 'Monday, December 31, 2007 12:00:00 AM'
date -d 2011-12-31 +%V #return 01 - right
Get-date 2011-12-31 -UFormat "%V" #return 53 - bug

**Comment by tarekgh** [comment]
Yes, we are not fully compatible with ISO 8601, you may look at the blog https://blogs.msdn.microsoft.com/shawnste/2006/01/24/iso-8601-week-of-year-format-in-microsoft-net/ for more info which also suggests how you can get the compatible ISO 8601 behavior. 

If you want the framework support ISO 8601, please feel free to open new API proposal issue for that. Thanks for reporting the issue.

**Comment by iSazonov** [comment]
@tarekgh Thank for great link!

Issue for API proposal #28933
