### ISSUE TITLE
[NetFX] System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests/ValidateAgainstBlobs fails when running on .NET 4.7.1

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#28816]
We just upgraded our Helix machines to have .NET 4.7.1 and updating netfx alias in corefx to target .NET 4.7.1 as well, when trying to update the CI queues to use these machines, this test is failing:

```
Message :
Assert.True() Failure
Expected: True
Actual:   False
Stack Trace :
   at System.Runtime.Serialization.Formatters.Tests.EqualityExtensions.CheckEquals(Object objA, Object objB, Boolean isSamePlatform) in E:\repos\corefxCopy\corefx\src\System.Runtime.Serialization.Formatters\tests\EqualityExtensions.cs:line 96
   at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAndRoundtrip(Object obj, TypeSerializableValue[] blobs, Boolean isEqualityComparer) in E:\repos\corefxCopy\corefx\src\System.Runtime.Serialization.Formatters\tests\BinaryFormatterTests.cs:line 104
   at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs(Object obj, TypeSerializableValue[] blobs) in E:\repos\corefxCopy\corefx\src\System.Runtime.Serialization.Formatters\tests\BinaryFormatterTests.cs:line 54
```

I can't get a local repro, but using the repro tool I did. 

https://mc.dot.net/#/user/safern/pr~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fdesktop~2Fcli/20180402.5433/workItem/System.Runtime.Serialization.Formatters.Tests/analysis/xunit/System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests~2FValidateAgainstBlobs(obj:%20CultureAwareComparer%20%7B%20%7D,%20blobs:%20%5BSystem.Runtime.Serialization.Formatters.Tests.TypeSerializabl)

I will disable this test for NETFX.

cc: @ViktorHofer @danmosemsft

**Comment by danmosemsft** [comment]
`2018-04-02 20:56:03,601: INFO: proc(54): run_and_log_output: Output:     System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs(obj: CultureAwareComparer { }, blobs: [System.Runtime.Serialization.Formatters.Tests.TypeSerializableValue, System.Runtime.Serialization.Formatters.Tests.TypeSerializableValue, System.Runtime.Serialization.Formatters.Tests.TypeSerializableValue, System.Runtime.Serialization.Formatters.Tests.TypeSerializableValue]) [FAIL]`

CultureAwareComparer is the actual NETFX type returned when you request some of the static StringComparers.

**Comment by ViktorHofer** [comment]
cc @Anipik for CultureAwareComparer.

**Comment by Anipik** [comment]
@danmosemsft  @ViktorHofer The object which is failing is StringComparer.InvarientCultureIgnoreCase. The hashcode and the name of  the objects is same. I checked the code  in netfx and there is nothing in the overridden Equals method (stringComparer.cs) suggesting the reason for the failure.

**Comment by danmosemsft** [comment]
@Anipik sounds like debugging is the next step for you.

**Comment by Anipik** [comment]
The blobs are generated with 4.7.1 only

**Comment by safern** [comment]
> @Anipik is this failing locally on your machine too when running with /p:TargetGroup=netfx?

@safern TargetGroup netfx corresponds to net471 in master now, right?

Note that this will not fail locally right now because my PR to update netfx to net471 hasn’t go in yet. Actually we might hold it until net472 comes out to not double the work once we want to upgrade to that one. In order to repro you need to pull my branch and just `build.cmd -framework:netfx` and then run the tests with `/p:TargetGroup=netfx`

This is my PR: https://github.com/dotnet/corefx/pull/28883

**Comment by ViktorHofer** [comment]
ping @Anipik

**Comment by ViktorHofer** [comment]
Validated offline. This doesn't repro with net471 on my RS4 machine (which seems to be patched).

**Comment by ViktorHofer** [comment]
I just updated the blobs and removed the ActiveIssue. If anything failed before it shouldn't anymore.
