### ISSUE TITLE
Cannot connect named pipe in UWP

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/corefx#28813]
##### Environment
OS: Windows 10 Pro 17133.1
SDK: 16299 used; 17110 installed
Microsoft.NETCore.UniversalWindowsPlatform 6.0.8
##### Code
Mostly copied from [NamedPipeTest](https://github.com/dotnet/corefx/blob/master/src/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.Read.cs)
```csharp
using (var serverPipe = new NamedPipeServerStream("LOCAL\\Test", PipeDirection.Out, 1, PipeTransmissionMode.Byte, PipeOptions.Asynchronous)
using (var clientPipe = new NamedPipeClientStream(".", "LOCAL\\Test", PipeDirection.In, PipeOptions.Asynchronous)
{
    var clientTask = clientPipe.ConnectAsync();
    serverPipe.WaitForConnection();
    clientTask.Wait();
}
```

##### Symptom
Get `IOException` that "pipe is closing" in `serverPipe.WaitForConnection`
If parameters except pipe name are removed, will get `IOException` that "not supported in app container" in `clientTask.Wait`.

As the test has UWP specific handling (adding `\LOCAL`), I suppose the api to be available for UWP.

**Comment by safern** [comment]
cc: @joperezr (who worked on the tests)

**Comment by danmosemsft** [comment]
It looks like connecting to named pipes from UWP requires a workaround:

> apps should be able to P/Invoke to CallNamedPipe provided they are using a PIPE_TYPE_MESSAGE pipe (vs. a byte-oriented pipe) as a work-around.

@ptorr-msft do you have other information/

**Comment by joperezr** [comment]
cc: @pjanotti @JeremyKuhne

**Comment by ptorr-msft** [comment]
@danmosemsft no that's all we have right now. Future OS releases should enable pipe creation via `CreateFileFromApp` (and then an even future-er release should let you call `CreateFile` itself).

**Comment by pjanotti** [comment]
Sorry for missing this earlier @huoyaoyuan - the tests are actually disabled, the active issue #22271 was closed incorrectly. The only workaround at this moment is the one mentioned by above:

> apps should be able to P/Invoke to CallNamedPipe provided they are using a PIPE_TYPE_MESSAGE pipe (vs. a byte-oriented pipe) as a work-around.

I'm going to close this and we track re-enabling this via #22271.
