### ISSUE TITLE
Same naming classes appear in multiple nuget packages.

### ISSUE THREAD

**Issue by singlewind** [dotnet/corefx#2882]
I know you guys are busy building the .net core packages. At the moment, I face a challenge about the following errors when target dnxcore50

Error	CS0433	The type 'HashAlgorithm' exists in both 'System.Security.Cryptography.Hashing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Security.Cryptography.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

Error	CS0433	The type 'HMACSHA1' exists in both 'System.Security.Cryptography.Algorithms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Security.Cryptography.Hashing.Algorithms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

Error	CS0433	The type 'RandomNumberGenerator' exists in both 'System.Security.Cryptography.Algorithms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Security.Cryptography.RandomNumberGenerator, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'	

Previously, we solve this kind of issues by add alias in project. Since we have new project file which is project.json. I have run out of idea how to add alias. Can one of masters give me some hints on this?

**Comment by bartonjs** [comment]
System.Security.Cryptography.Primitives and System.Security.Cryptography.Algorithms are the new libraries; S.S.C.Hashing, S.S.C.Hashing.Algorithms and S.S.C.RandomNumberGenerator are the old libraries.

You should be able to just drop the references to the old ones and have everything work (at runtime the old libraries would just forward into the new ones, but I might have not set it up properly for the ref assemblies).

**Comment by singlewind** [comment]
@bartonjs Thanks Jeremy. I don't know what mistake I have made. Actually, I only referenced S.S.C.P and S.S.C.A. Just visual studio 2015 keep annoying me. Looking forward to the new one version.

**Comment by sandorfr** [comment]
I am facing the same issue and it is due to "WindowsAzure.Storage" even with the latest "5.0.3-preview" because they are referencing the old assemblies.

**Comment by joshfree** [comment]
Hi @singlewind, thank you for reporting this issue.  it looks like the azure storage reference mismatch issue is resolved (as of 3 days ago) in Azure Storage 6.0.1-preview.  I'm closing this corefx repo issue now.  Please feel free to reactivate it if you're still experiencing problems.  Thanks

**Comment by ysavit** [comment]
@bartonjs There is my error message: The type 'RandomNumberGenerator' exists in both 'System.Security.Cryptography.Algorithms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Security.Cryptography.RandomNumberGenerator, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'	ServerApp.DNX Core 5.0	

What should i remove from references ?
S.S.C.R is referenced in SignalR (3.0.0- beta5)
S.S.C.A is referenced in number of places
Thanks

**Comment by bartonjs** [comment]
SignalR updated their references to use the new package identifiers back in August (https://github.com/aspnet/SignalR-Server/commit/05cba5094f1d7d4734c99cd3f9867bf40f849442).  Assuming that it's on the same beta cycle as corefx, beta5 should be a fairly out of date version... can you upgrade it to a newer one?
