### ISSUE TITLE
Perf regression on Linux SSL (ASP.NET plaintext)

### ISSUE THREAD

**Issue by sebastienros** [dotnet/corefx#28830]
As seen on this KPI from 785K RPS before the regression:

![image](https://user-images.githubusercontent.com/1165805/38339602-eac8a23c-3823-11e8-877c-0505885462b1.png)

Between `2.1.0-preview3-26330.03` and `2.1.0-preview3-26331-01` as shown on this graph:

![image](https://user-images.githubusercontent.com/1165805/38339549-99f6a5fc-3823-11e8-954f-435919be9d8f.png)

The regression only occurs on Linux, and has been replicated on local environment and also on azure.

**Comment by karelz** [comment]
cc @geoffkizer @stephentoub @davidsh @wfurt

**Comment by karelz** [comment]
Do you have perf traces we can look at? (ideally diff)

**Comment by sebastienros** [comment]
I don't have the ability to get traces on linux right now.

**Comment by karelz** [comment]
Is there a way to map the build numbers above to commits? We can review what happened between them ...

**Comment by stephentoub** [comment]
In addition to Karel's question:
- what distro / version is this on?
- and is it possible for you to see what SSL protocol / cipher / etc. was getting negotiated before and after? I'm wondering if that may have changed.

**Comment by karelz** [comment]
@sebastienros any chance to get the info above? Otherwise I am not sure it will be actionable for us :(

**Comment by sebastienros** [comment]
I am running the benchmarks on Ubuntu 16.04, in a docker image. I don't know the answers about the SSL details, but all can be reproduced very easily, it's in the aspnet/benchmarks repository. 
The commit numbers can somehow be induced by the build numbers, I assume you can also use mc.dot.net to get the precise commits that went into these runtimes.

2.1.0-preview3-26330.03 => 03/30 
2.1.0-preview3-26331-01 => 03/31

If you can't get the commits easily I try will to find them in the metadata attributes of the dlls. I can also dump them from a running application. I can do it later today.

**Comment by karelz** [comment]
There a few potentially suspicious changes around that time: [first batch](https://github.com/dotnet/corefx/commits/master?before=a036d70307f7d9dabb7fcb9d9d2b3d3a23011469+120) and [second batch](https://github.com/dotnet/corefx/commits/master?after=a036d70307f7d9dabb7fcb9d9d2b3d3a23011469+119)

Commits remotely related:
* SNI feature (2d39212fc69a6c0a78c48a3ad8e191ca94872548)
* SslStream mutates state of options (00bcad0f047186047d3021584b732a8c5d124376)
* Avoid unnecessary propagation ExecutionContext in SocketsAsycEngine (ec5fb4162c8376cf8ced69f1d2442c586e9197f3)
* Make TripleDESCryptoServiceProvider CreateTransform behave like netfx (78357cf19232383d8e6b5356b760bf4c2f0e2f09)
* Stop blocking explicit opt-in to Ssl2/3 in SslStream and HttpClient (3cc6fda0c6abe76eea222c165ebdf816e83df564)

None of them is particularly suspicious.

**Comment by stephentoub** [comment]
> None of them is particularly suspicious.

`Stop blocking explicit opt-in to Ssl2/3 in SslStream and HttpClient` is why I asked about the protocol/cipher/etc. that ended up getting negotiated.  I'm wondering if maybe the connection is ending up with a different protocol than it previously did, and that different protocol is slower for reading/writing / encrypting/decrypting.

**Comment by sebastienros** [comment]
If you give me custom builds of these changes I can test them and let you know if that was it.

If I had the time to do it I would gladly create custom builds reverting all these commits one by one and find which one is causing it, but right now I don't have much experience with building the corefx repos, and too many things to do in parallel.

**Comment by wfurt** [comment]
There was also https://github.com/dotnet/corefx/pull/28666 in that time frame.

**Comment by karelz** [comment]
That is the second one on my list ;)

**Comment by wfurt** [comment]
you beat me while I was looking @karelz ;(

**Comment by karelz** [comment]
@wfurt can you please try to reproduce it in house? Please make sure @rmkerr knows how to do it as well (for the time you will be OOF).

**Comment by karelz** [comment]
@sebastienros can you please confirm that other workloads and OSs did NOT regress between these 2 builds?

**Comment by rmkerr** [comment]
Just to add on to this, I've been working to confirm the testing done by @wfurt. I can roll back System.Net.Security and System.Net.Http to well before the perf regression without seeing the performance drop go away. Only when I switch to newer versions of aspnetcore and the runtime do I see the same regression.

**Comment by rmkerr** [comment]
Hey @sebastienros, we don't see any indication that this is on the corefx side. I'm going to be collecting traces to see if I can see exactly where the regression is, but based on our testing I don't expect it to be on our end.

**Comment by rmkerr** [comment]
I'm still in the process of trying to get symbol information, but here's the first regression report I've been able to generate. This has a baseline run on the old runtime version 2.1.0-preview2-26330-03 and asp net core version 2.1.0-preview3-32107. That's compared to runtime version 2.1.0-preview3-26331-01 and asp net core version 2.1.0-preview3-32112.

Name | Base | Test | Delta | Responsibility % | Overweight % | Interest Level
-- | -- | -- | -- | -- | -- | --
module unknown <> | 323.0 | 2.0 | -321.0 | 57.12 | 889.65 | 5
module 2.24.so <> | 342.0 | 3.0 | -339.0 | 60.32 | 887.34 | 5
module libcoreclr.so  <> | 342.0 | 3.0 | -339.0 | 60.32 | 887.34 | 5
module System.IO.FileSystem.dll  <> | 185.0 | 6.0 | -179.0 | 31.85 | 866.16 | 5
module libcoreclr.so <> | 261.0 | 35.0 | -226.0 | 40.21 | 775.15 | 5
module kernel.kallsyms <> | 881.0 | 502.0 | -379.0 | 67.44 | 385.11 | 5
module libcoreclr.so <> | 61.0 | 18.0 | -43.0 | 7.65 | 631.04 | 4
module 2.24.so <> | 348.0 | 255.0 | -93.0 | 16.55 | 239.23 | 4
module libcoreclr.so  <> | 203.0 | 169.0 | -34.0 | 6.05 | 149.93 | 4
module enic <> | 245.0 | 290.0 | 45.0 | -8.01 | -164.42 | 4
module kernel.kallsyms <> | 189.0 | 226.0 | 37.0 | -6.58 | -175.25 | 4
module libcrypto.so.1.0.0 <> | 265.0 | 321.0 | 56.0 | -9.96 | -189.17 | 4
module kernel.kallsyms <> | 261.0 | 331.0 | 70.0 | -12.46 | -240.09 | 4
module kernel.kallsyms <> | 29.0 | 7.0 | -22.0 | 3.91 | 679.11 | 3
module libcoreclr.so <> | 33.0 | 18.0 | -15.0 | 2.67 | 406.91 | 3
module libcoreclr.so  <> | 56.0 | 34.0 | -22.0 | 3.91 | 351.68 | 3
module 2.24.so <> | 57.0 | 37.0 | -20.0 | 3.56 | 314.10 | 3
module Microsoft.CodeAnalysis.dll  <> | 88.0 | 74.0 | -14.0 | 2.49 | 142.42 | 3
module System.Private.CoreLib.dll  <> | 4001.0 | 3670.0 | -331.0 | 58.90 | 74.06 | 3
module unknown <> | 557.0 | 511.0 | -46.0 | 8.19 | 73.93 | 3
module libcoreclr.so <> | 81.0 | 96.0 | 15.0 | -2.67 | -165.78 | 3
module libcoreclr.so <> | 32.0 | 44.0 | 12.0 | -2.14 | -335.70 | 3
ROOT | 5031.0 | 4469.0 | -562.0 | 100.00 | 100.00 | 2
dotnet | 5031.0 | 4469.0 | -562.0 | 100.00 | 100.00 | 2
module System.Net.Sockets.dll <> | 281.0 | 261.0 | -20.0 | 3.56 | 63.72 | 2

**Comment by sebastienros** [comment]
I agree there is no indication that this is on corefx, when I first reproed it was obvious though but the command lines I provided are the best I can get now and it's not showing it.

I will move it to aspnet repos then.

**Comment by rmkerr** [comment]
Thanks for the heads up @sebastienros. I'll go ahead and close this issue.

**Comment by sebastienros** [comment]
Maybe not related to this issue, I noticed a perf improvement on Linux SSL between runtime versions `2.2.0-preview1-26423-02` and `2.2.0-preview1-26424-04`. Almost making up with what this one is losing. I could investigate and pinpoint which exact runtime version change contains the improvement.

**Comment by karelz** [comment]
That would be nice if we can find out which changes misteriously fixed it.
