### ISSUE TITLE
Reflection types should be made extensible

### ISSUE THREAD

**Issue by Grochni** [dotnet/corefx#2886]
I'm creating a subclass of FieldInfo and there's an error in the constructor saying "'ConstructorInfo' does not contain a constructor that takes 0 arguments". The reason for this is that my constructor is  calling the default constructor of FieldInfo, which seems to be unavailable. That's because FieldInfo's constructor was changed to internal. As there is no other constructor defined in FieldInfo it's now impossible to extend it. It's the same for ConstructorInfo, EventInfo, MethodInfo, PropertyInfo, TypeInfo and Type. 

Is this intended?

**Comment by stephentoub** [comment]
cc: @nguerrera, @terrajobst

**Comment by nguerrera** [comment]
This is intentional, but something we do hope to address. Some of the changes that were introduced at the contract level are not currently compatible with other platforms (full framework) if extensibility were allowed. Fixing this is actually a prerequisite for #2800.

**Comment by Grochni** [comment]
@nguerrera Thank you for clearing this up. So what is the plan for this? Are you going to make the constructors public again or are they going to stay internal?

**Comment by nguerrera** [comment]
The plan is to make them public.

**Comment by karelz** [comment]
@AtsushiKan believes that all these things are now public/protected in 2.0.
