### ISSUE TITLE
Add a dummy int field in the reference assembly for Span (and other structs containing private fields)

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#28870]
> we need to update the reference assembly tool to keep a dummy int field if there are any valuetype fields and not collapse it with the dummy object field if there is one

We need to update the logic in buildtools (within IsOrContainsReferenceType) and regenerate the reference assemblies:
https://github.com/dotnet/buildtools/blob/master/src/Microsoft.Cci.Extensions/Extensions/CSharp/CSharpCciExtensions.cs#L114

**Update to the ref assembly generation rules:**
- If a struct contains any private field, a dummy valuetype field needs to be created.
- If a struct contains any reference type field, a dummy object field must also be created.

This is required since the [compiler will not catch bugs](https://github.com/dotnet/roslyn/pull/25886/files) in user code going against the definite assignment rules (specifically for structs). For example:
https://stackoverflow.com/questions/49653151/spant-does-not-require-local-variable-assignment-is-that-a-feature

cc @weshaggard, @joshfree, @jaredpar, @bartonjs, @nguerrera, @agocke, @gafter

**Comment by gafter** [comment]
My amendment to my previously suggested rules is

For a struct type:
- If there are any private **or internal** fields that are or contain any value **or reference** type members, add a single private field of type int
- If there are any private **or internal** fields that are or contain any reference type members, add a single private field of type object.
- If the type is generic, then for every type parameter of the type, if there are any private **or internal** fields that are or contain any members whose type is that type parameter, we add a direct private field of that type.

This amendment is based on what fields the compilers drop on the floor during import. See https://github.com/dotnet/roslyn/commit/31ddbfa1a14640c86939e066d9549ac014cf845f for the code that does the ignoring.

**Comment by gafter** [comment]
The phrase "private or internal" should also be read to include `private protected` fields.

**Comment by jnm2** [comment]
System.Collections.Immutable 1.5.0 (used from .NET Framewokr 4.6.2) demonstrates the same issue:

![image](https://user-images.githubusercontent.com/8040367/43403091-3f52e208-93e2-11e8-9f2e-18ae937501a9.png)


I spotted this in a coworker's PR today and it makes me very uneasy. Should I start a new issue or is this already being fixed?

**Comment by jnm2** [comment]
Opened an issue for System.Collections.Immutable at @tannergooding's suggestion: https://github.com/dotnet/corefx/issues/31475
