### ISSUE TITLE
NETFX System.ServiceProcess.ServiceController tests hang

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#28881]
There are 2 tests under this project hanging are under `ServiceBaseTests`:

- `LogWritten`
- ` LogWritten_AutoLog_False`

They both show the following pop-up that requires user interaction, since in Helix there is no one to click on it, they will hang there.

![image](https://user-images.githubusercontent.com/22899328/38406302-37aae190-3929-11e8-9cc9-f67c1c68acdf.png)

Also once you click on the pop-up and let them run, there is one test failure:

```
 System.ServiceProcess.Tests.ServiceBaseTests.PropagateExceptionFromOnStart [FAIL]
        Assert.Equal() Failure
        Expected: 16
        Actual:   0
        Stack Trace:
          E:\repos\corefxCopy\corefx\src\System.ServiceProcess.ServiceController\tests\ServiceBaseTests.cs(213,0): at S
  ystem.ServiceProcess.Tests.ServiceBaseTests.PropagateExceptionFromOnStart()
```

Note that this tests need to be ran as an administrator and with `/p:Outerloop=true`

cc: @danmosemsft @Anipik

**Comment by Anipik** [comment]
@safern i know about this failure and in my last discussion with @danmosemsft . he told me its okay to disable it for netfx, if it fails on the CI (it was failing locally and not on the CI). I have tested the test behavior manually with the service.
For the  hang, i have encountered the message before, i should be able to resolve it tomorrow
