### ISSUE TITLE
System.Drawing.Common 4.5.0 isn't added to references in a Xamarin.Android project while adding the package from nuget.org

### ISSUE THREAD

**Issue by donchak** [dotnet/corefx#28886]
I tried to add one package to a Xamarin.Android application. This package has System.Drawing.Common 4.5.0 in its dependencies.
After that, the project compilation is stopped with an error:
```
Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Perhaps it doesn't exist in the Mono for Android profile?
error : File name: 'System.Drawing.Common.dll'
```
The packages.config file contains the correct record:
```
<package id="System.Drawing.Common" version="4.5.0-preview1-26216-02" targetFramework="monoandroid81" />
```
But **System.Drawing.Common** is absent in the reference list.
 
It seems that **Visual Studio** tries to get **System.Drawing.Common.dll** for **Xamarin.Android** runtime, because the package contains the **MonoAndroid10** folder. It can't do this, because this folder doesn't contain any DLL-files, but the stub file with the '\_.\_' name.

![2018-04-06_15-55-52](https://user-images.githubusercontent.com/1681154/38422372-26819e6a-39b3-11e8-95aa-eba383388bbd.png)

If I find System.Drawing.Common.dll for **.NET Standard 2.0** and manually add it to references, the project operates correctly.
 
**Steps to reproduce:**
- Run Visual Studio Professional 2017 Version 15.6.5
- Create new Android -> Blank App (Android)
- Add System.Drawing.Common 4.5.0 via Manage Nuget Packages...
 
**Current result:** System.Drawing.Common.dll isn't in references.
 
**Expected result:** System.Drawing.Common.dll is in references.

**Additional information:**
Microsoft Visual Studio Professional 2017 
Version 15.6.5
VisualStudio.15.Release/15.6.5+27428.2027
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Professional

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.9.0.753 (f0f46392f)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.10.96 (a702a9ceb)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.2.0.16 (HEAD/a78295902)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.9.1.24 (f62de47)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by karelz** [comment]
@joperezr @weshaggard can you please advise?

**Comment by ericstj** [comment]
This is typically what is done with the assemblies that overlap with Xamarin types.  @safern did this here: https://github.com/dotnet/corefx/pull/24758.  I believe he's discussed it with @marek-safar and Xamarin will be adding the facade for this assembly.

**Comment by marek-safar** [comment]
We didn't ship any Xamarin version which provides the assembly yet. 

@ericstj as the nuget is still in preview and has been for many months how confident are you we can ship a version with matching API and not to break on the future updates.

**Comment by ericstj** [comment]
The API is a subset of API exposed by desktop in `System.Drawing`, so no API breaking changes are possible as we would defeat the purpose.  The most that can happen is some new types will be added in the future but we just react to that if it happens.  I don't expect that to happen for the current release given where we are at.

**Comment by donchak** [comment]
So what is a right workaround for this case?
And when I can expect the fix?
Thank you!

**Comment by marek-safar** [comment]
@donchak there is no simple workaround for now, you need to get copy System.Drawing.Common.dll manually to the output folder.

The fix should be available as part of dev15.7 release

**Comment by donchak** [comment]
@marek-safar Thank you!

**Comment by ericstj** [comment]
You might be able to use the net4* copy of that DLL, but it may not be compatible if the Xamarin types are in different assemblies than in desktop.

**Comment by weshaggard** [comment]
@marek-safar should this issue be moved to xamarin repo?

**Comment by marek-safar** [comment]
@weshaggard you can close it, we are tracking this as https://github.com/mono/mono/issues/8089

**Comment by safern** [comment]
Thanks @marek-safar

**Comment by westito** [comment]
I have te same bug with WPF project (.NET Framework). I comment this for ones who found this issue like me. The solution is: Add `<RestoreProjectStyle>PackageReference</RestoreProjectStyle>` line under `<PropertyGroup>` in the .NET Framework project's .csproj file!
