### ISSUE TITLE
System.IO.File conflict

### ISSUE THREAD

**Issue by rave1502** [dotnet/corefx#2888]
In a ASP.Net 5 WebAPI project, I need to do some file operations such as read all text from a file. When I am adding Syste,.Io.FileSystem to the project, I am getting compilation error:
"Error	CS0433	The type 'File' exists in both 'System.IO.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	SampleProj.DNX 4.5.1	"

**Comment by stephentoub** [comment]
cc: @ericstj

**Comment by ericstj** [comment]
Can you share your project.lock.json?  It sounds to me like DNX is selecting the wrong asset from the FileSystem package.
/cc @anurse @davidfowl

**Comment by rave1502** [comment]
Hello, Please find the project.lock.json file @ https://gist.github.com/rave1502/e0e7c23c62779e166f1b

**Comment by ericstj** [comment]
The FileSystem package isn't supported on DNX 4.5.1 which you are targeting here.  You should be getting an error from DNX that the package is not supported since no implementation is provided.  I've opened https://github.com/aspnet/dnx/issues/2525 to track this.  If you target DNX 4.6 it should work.

**Comment by rave1502** [comment]
Hello, thanks for your help. Could you please point me to the page whcih describes how to change/upgrade the DNX version in the project.

**Comment by rave1502** [comment]
with the DNX 4.6, issue is not visible. Closing the issue. Thanks for you support.
