### ISSUE TITLE
Native UTF16 in regex

### ISSUE THREAD

**Issue by ghost** [dotnet/corefx#28897]
The note under https://en.wikipedia.org/wiki/Comparison_of_regular_expression_engines#API_features says:

![image](https://user-images.githubusercontent.com/33230602/38444348-8480c326-39f7-11e8-8879-2ca14b6b5b8c.png)

Any chance to extend regex support from UCS2's 64K to UTF16's 1,112,064 chars in .NET Core?

**Comment by stephentoub** [comment]
Closing "ghost" question
