### ISSUE TITLE
How to use "RSA/ECB/PKCS1Padding" and "RSA/ECB/OAEPPadding"

### ISSUE THREAD

**Issue by EssenRoc** [dotnet/corefx#28909]
I need to use these two algorithms but I don't know how to use the .net core
help me!!!

**Comment by bartonjs** [comment]
The short answer is

* `RSA/ECB/PKCS1Padding`: Invoke `rsa.Encrypt(data, RSAEncryptionPadding.Pkcs1)`
* `RSA/ECB/OAEPPadding`: Invoke `rsa.Encrypt(data, RSAEncryptionPadding.OaepSHA1)`

(or `Decrypt`, as appropriate).

That assumes that the "ECB" there isn't relevant and you're not encrypting more data than the size of the key.  In which case, that's a Java-ism that I don't quite know what they do.

And if you're not even sure how to get an RSA object, you might want to search/ask on https://stackoverflow.com/.

**Comment by EssenRoc** [comment]
In other words, it is not yet supported?
So 2.1 is there a support plan?
Thank you

**Comment by EssenRoc** [comment]
Because of the "ECB" involved, the result of using this current usage is inconsistent

**Comment by bartonjs** [comment]
No, there's no plan to support automatic chunking with RSA in .NET.

The Internet seems to suggest that the inbox providers in Java fail even in "ECB" mode when the input exceeds the maximum that the key can handle for one operation, so whatever Java behavior you are trying to emulate is fairly non-standard (and against cryptographer recommendations).

**Comment by EssenRoc** [comment]
What I want to say is that I don’t care about the suggestion of encryption standards because I only want to interact with java webapi but the other party uses “ECB” and I have no other choice.

Thank you

**Comment by bartonjs** [comment]
@EssenRoc I still recommend asking on StackOverflow.  Someone somewhere should know how the provider is doing chunking so you can emulate it in C#.  And hopefully they answer questions on SO :smile:.

**Comment by EssenRoc** [comment]
I solved it with BouncyCastle a few days ago. Although I don't really like BouncyCastle, it does solve my problem very effectively.

Thanks again
