### ISSUE TITLE
Feature Request: Support namof() for parameters of the following method in attributes

### ISSUE THREAD

**Issue by TheMinefighter** [dotnet/corefx#28903]
It would be really cool if the "nameof()" function in attributes for methods would allow the name of parameters as follows:
```
[MyCustomAttribute(nameof(myParameter))]
public static void MyMethod (bool myParameter) {}
```

**Comment by danmosemsft** [comment]
@TheMinefighter I believe this is a request for the C# language. Can you please open this in https://github.com/dotnet/csharplang ?

**Comment by TheMinefighter** [comment]
@danmosemsft Done: https://github.com/dotnet/csharplang/issues/1445
