### ISSUE TITLE
tracking: re-enable Tizen in CI

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#28901]
tracking issue for the Tizen build failures; temporarily disabling the leg; and for later re-enabling the leg.

example PRs: 

https://github.com/dotnet/corefx/pull/28873 

https://github.com/dotnet/core-setup/pull/3992 

@RussKeldorph 

/cc @hqueue @hseok-oh

**Comment by joshfree** [comment]
@ianhays can you please temporarily disable the Tizen build legs in CI (not in the official build) for the core and core-setup repos to unblock PRs today for the .NET Core 2.1 RC milestone?

/cc @dotnet/arm32-contrib as FYI.  Once the Tizen leg is back up, then the CI legs can be re-enabled.

**Comment by ianhays** [comment]
Sure: 

https://github.com/dotnet/corefx/pull/28902
https://github.com/dotnet/core-setup/pull/3996

**Comment by okodron** [comment]
I think, docker image should be updated to the officially supported ubuntu 16.04 with the latest [qemu](https://github.com/dotnet/coreclr/issues/12972) (with ARM `membarrier()` syscall support).
As I understand, @hqueue created that docker image.

**Comment by joshfree** [comment]
@hqueue @alpencolt thanks for looking into this 😺

**Comment by joshfree** [comment]
@alpencolt any update on this?  I'm making sure that you're aware that Tizen CI coverage is still disabled.

**Comment by BruceForstall** [comment]
note, the Tizen jobs are disabled in coreclr also: https://github.com/dotnet/coreclr/pull/17240

**Comment by joshfree** [comment]
@alpencolt looks like the Tizen CI leg (now reenabled) is failing in corefx (at least in PR https://github.com/dotnet/corefx/pull/32795):

https://ci.dot.net/job/dotnet_corefx/job/master/job/tizen_armel_cross_debug_prtest/16501/consoleFull#-8536224876a086b3e-df04-41d2-bc4d-43e8f9406d07
```
15:05:02 /opt/corefx/Tools/Symbols.targets(514,7): warning : Downloading https://dotnetfeed.blob.core.windows.net/dotnet-core/assets/symbols/runtime.tizen.5.0.0-armel.Microsoft.NETCore.Runtime.CoreCLR.3.0.0-preview1-26926-03.symbols.nupkg failed with exception:  [/opt/corefx/external/runtime/runtime.depproj]
15:05:02 /opt/corefx/Tools/Symbols.targets(514,7): warning : Response status code does not indicate success: 404 (The specified blob does not exist.). [/opt/corefx/external/runtime/runtime.depproj]
15:05:02 /opt/corefx/Tools/Symbols.targets(514,7): warning :    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() [/opt/corefx/external/runtime/runtime.depproj]
15:05:02 /opt/corefx/Tools/Symbols.targets(514,7): warning :    at System.Net.Http.HttpClient.FinishGetStreamAsync(Task`1 getTask) [/opt/corefx/external/runtime/runtime.depproj]
15:05:02 /opt/corefx/Tools/Symbols.targets(514,7): warning :    at Microsoft.DotNet.Build.Tasks.DownloadFilesFromUrl.ExecuteAsync() [/opt/corefx/external/runtime/runtime.depproj]
15:05:02 /opt/corefx/external/runtime/runtime.depproj(127,7): warning : Failed to download CoreCLR symbols
```

**Comment by alpencolt** [comment]
@joshfree there were some changes in CoreFX build scripts.
Now we're fixing it https://github.com/tizendotnet/netcore-jenkins/pull/36
Thank you for notification.

**Comment by stephentoub** [comment]
The Tizen leg is enabled and passing in corefx CI.  Closing.
