### ISSUE TITLE
Support for enumerating non-default code pages added with RegisterProvider (System.Text.Encoding)

### ISSUE THREAD

**Issue by mklement0** [dotnet/corefx#28915]
The [documentation for `System.Text.Encoding.GetEncodings()`](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.getencodings?view=netframework-4.7.1#System_Text_Encoding_GetEncodings) tells us (emphasis added):

> The list of supported encodings returned by the GetEncodings method **does not include any 
> additional encodings made available by any EncodingProvider implementations that** were registered by calls to the RegisterProvider method.

Is there no way to enumerate these additional encodings?

Unfortunately, [`System.Text.CodePagesEncodingProvider.Instance`](https://docs.microsoft.com/en-us/dotnet/api/system.text.codepagesencodingprovider.instance?view=netcore-2.0#System_Text_CodePagesEncodingProvider_Instance) lacks a method for enumerating them.

**Comment by iSazonov** [comment]
I would say that it is very surprising that after registering a new provider we can not get the full list of supported code pages.

**Comment by danmosemsft** [comment]
@tarekgh

**Comment by iSazonov** [comment]
First we discussed this in PowerShell Core repo. Some cmdlets have `-Encoding` parameter. If we want to add IntelliSense support for full set of code pages then we have the problem.

**Comment by tarekgh** [comment]
Although I can see the issue, generally people interested in specific codepage encoding they already knew this codepage number and can just use it. another scenario would be getting the codepage name or number from some contents (like Xml, html, network stream,...etc.) and create encoding object. in such cases enumeration is not needed anyway.

Could you tell exactly your scenario you want this? I understand power shell case but again this is not the scenario people use it. looking at the usage of System.Text.Encoding.GetEncodings, I am seeing it has very low usage. 

If you really in need for that, you can file an API proposal for adding GetEncodings method in the class EncodingProvider. and have the implementation support it.

**Comment by mklement0** [comment]
@tarekgh: 

To elaborate on the scenario mentioned by @iSazonov:

PowerShell Core users may want to _discover_ available encodings and/or be assisted in selecting a specific encoding with _tab completion_:

```powershell
Get-Content file.txt -Encoding <tab>  # should show all available encodings
```

The above is currently limited to the .NET Core default encodings, even though PowerShell registers additional encodings on startup.

**Comment by tarekgh** [comment]
@mklement0 I understand this and I am not objecting it. my point is this is not a real app scenario or real user scenario. in another word, my experience is not many people need to enumerate the code pages. 

Feel free to submit an API proposal as I mentioned in my previous reply.

**Comment by mklement0** [comment]
@tarekgh: 

Thanks; I am glad you understand. It sounded like you wanted more details, based on this  question of yours, in response to which I posted my elaboration.

> Could you tell exactly your scenario you want this? 

As for deeming this  not a real-world scenario:

> but again this is not the scenario people use it.
> looking at the usage of System.Text.Encoding.GetEncodings,

Of course, it's impossible to see usage from the PowerShell side of things yet, given that the feature currently _doesn't exist_ - for lack of API support.

I will submit an API proposal.

**Comment by iSazonov** [comment]
Also we have a request to implement new cmdlet for converting encoding like [iconv](https://linux.die.net/man/1/iconv). iconv has `--list` parameter so users can get a list of supported code pages. Today we can't do this effectively.
I suppose we could add a new overload (maybe with optional parameter) `GetEncodings(bool IncludeExtendedCodePages = false)`.

**Comment by tarekgh** [comment]
> given that the feature currently doesn't exist - for lack of API support 

Does the desktop version of power shell support ```Get-Content file.txt -Encoding ```? 

if so, this would be a good thing to look at the usage of this functionality in power shell there.

**Comment by mklement0** [comment]
@tarekgh:

Unfortunately, _Windows PowerShell_ (the `Desktop` edition of PowerShell built on the full .NET framework) does _not_ support `Encoding` instances directly (only a limited set of enumeration values that map onto a handful of common encodings).

In _PowerShell Core_'s cross-platform world, encoding conversions strike me as more common, and presumably that's why that ability was added.

@iSazonov's example of an  `iconv`-like cmdlet - [green-lighted, but not yet implemented](https://github.com/PowerShell/PowerShell/issues/6201) - is indeed another good use case.

**Comment by mklement0** [comment]
@tarekgh:

Please see my API proposal at #28944.
