### ISSUE TITLE
Add Interlocked.Exchange overload for ulong, uint

### ISSUE THREAD

**Issue by shravan2x** [dotnet/corefx#28917]
_From https://github.com/dotnet/csharplang/issues/1446._

Can overloads be added to atomically exchange ulongs and uints? I had a use case for them earlier today and couldn't understand why they didn't exist.

Is there some technical issue?

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/issues/26378

**Comment by shravan2x** [comment]
@stephentoub My bad, I checked the csharplang repo for duplicates, but forgot to do so before I ported the issue here.

**Comment by stephentoub** [comment]
Not a problem :)
