### ISSUE TITLE
update of nuget packages like System.Net.WebSockets.Client

### ISSUE THREAD

**Issue by konne** [dotnet/corefx#28925]
Hi,

I din't found any documentation what is your policy of updating these kind of nuget packages.
@stephentoub has added some days ago the import feature of RemoteCertificateValidationCallback as connect option and I like to understand when I can expect a new nuget packege.

bye
Konrad

**Comment by karelz** [comment]
In general, we stopped shipping quite a few nuget packages as standalone packages. They are part of meta-package now. They are updated via .NET Core ship train (potentially also via UWP - not sure about details there).

System.Net.WebSockets.Client nuget seems to be in the bucket of packages we stopped shipping standalone: https://www.nuget.org/packages/System.Net.WebSockets.Client/

@weshaggard can you please confirm? (ideally point me to info how to find out myself in future :))

**Comment by weshaggard** [comment]
Yes System.NET.WebSockets.Client is one of the packages we stopped shipping individually. To figure that out you can look under the library folder for a pkg folder and if there isn't one then we don't build/ship a nuget package for it but if there is then we do. You can see https://github.com/dotnet/corefx/tree/master/src/System.Net.WebSockets.Client doesn't have a pkg folder but https://github.com/dotnet/corefx/tree/master/src/System.Net.WebSockets.WebSocketProtocol does have a pkg folder (for example).

**Comment by karelz** [comment]
Thanks @weshaggard! I'll try to keep that in mind for future ;).
@konne the package will be part of .NET Core 2.1. Let me know if you have further questions.

**Comment by konne** [comment]
@karelz please think of to remove the nuget packages, because they can easily confuse

**Comment by kasper3** [comment]
Why? Under Dependencies section on this page: https://www.nuget.org/packages/System.Net.WebSockets.Client/, it shows all the supported frameworks and thus should not be removed. Maybe just an additional note in description something like "Starting from .NET Core 2.x and .NET Framework X.Y, this package is part of shared framework".

Most package management systems do not allow "removing" a package ever. If there is a dire need, mark it as deprecate and delist from search.
