### ISSUE TITLE
Use of Unsafe.As in ReadOnlySequence can result in breaking type safety

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#28920]
In multiple places, the ReadOnlySequence struct checks a flag set in one field and then uses that to determine how to cast an object in another field, using Unsafe.As, e.g.
https://github.com/dotnet/corefx/blob/da1322d90a1412290a82a5ace157da4cc58dabf4/src/System.Memory/src/System/Buffers/ReadOnlySequence_helpers.cs#L39-L42
If the ReadOnlySequence suffers a torn read/write, we could end up with the type information from one instance conflated with the object from another, such that we'd then use Unsafe.As to perform the wrong cast, and violate type safety.

cc: @jkotas, @davidfowl, @pakrym, @ahsonkhan, @GrabYourPitchforks

**Comment by ahsonkhan** [comment]
I recommended removing the Unsafe.As and use regular type casting as part of this PR (at least for the method being optimized): https://github.com/dotnet/corefx/pull/28760#discussion_r179703474

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/dotnet/corefx/pull/29216
