### ISSUE TITLE
Tracking x-plat issues for System.Net.NameResolution

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#2894]
Feature #2484 : X-Plat comments from PR #2890 related to System.Net.NameResolution:
  1. Update errno helpers.
  2. Add Unit/Pal test to validate potential indexing issues found in NameResolutionPal.Unix.cs CreateHostEntry(Interop.libc.hostent* hostent); Given the design error, I suggest similar tests for the entire file.
  3. `TryGetNameInfo`'s allocation of `hostname`: consider using stackalloc / StringBuilderCache.
  4. Intermittent PAL test failure: `System.Net.NameResolution.PalTests.NameResolutionPalTests.GetHostByName_HostName_GetHostByAddr`

MESSAGE:
Assert.Equal() Failure Expected: 1XY.XYZ.XYZ Actual: 255.2.0.0
+++++++++++++++++++
STACK TRACE:
at System.Net.NameResolution.PalTests.NameResolutionPalTests.GetHostByName_HostName_GetHostByAddr()

  5. Intermittent PAL test failure:
`System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_HostName_TryGetNameInfo` 

MESSAGE:
Assert.Equal() Failure Expected: Success Actual: HostNotFound
+++++++++++++++++++
STACK TRACE:
at System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_HostName_TryGetNameInfo()

**Comment by mmitche** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_centos71_debug_tst/63/testReport/junit/System.Net.NameResolution.PalTests/NameResolutionPalTests/GetHostByName_LocalHost_GetHostByAddr/

Shows the GetHostByAddr failure.  Centos 7.1

**Comment by pgavlin** [comment]
Moving this to beta8.

**Comment by sokket** [comment]
Issue part 3 will be fixed with my change of moving Name Resolution to use the PAL layer

**Comment by sokket** [comment]
Part 3 was just fixed with #3471
