### ISSUE TITLE
Remove SequenceMarshal.TryGetMemoryManager for ReadOnlySequence

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#28959]
This API was added as part of https://github.com/dotnet/corefx/issues/27097 when we had a ReadOnlySequence ctor that takes a MemoryManager. Based on the `Memory<T>` [usage guidelines](https://gist.github.com/GrabYourPitchforks/4c3e1935fd4d9fa2831dbfcab35dffc6), ReadOnlySequence is a consumer of Memory and not an owner. Therefore, we removed that ctor, when we split OwnedMemory into MemoryManager and IMemoryOwner, here (https://github.com/dotnet/corefx/pull/28640).

There is no longer a need to have an API that requires a MemoryManager from a ReadOnlySequence. **There are no calls to this method in corefx/ASP.NET and it is no longer relevant.**

We already have a method on MemoryMarshal to get MemoryManager from a ReadOnlyMemory, which should be sufficient for any meaningful scenarios.
```C#
public static bool TryGetMemoryManager<T, TManager>(ReadOnlyMemory<T> memory, out TManager manager) where TManager : MemoryManager<T> { throw null; }
```

```diff
namespace System.Runtime.InteropServices
{
    public static partial class SequenceMarshal
    {
-        public static bool TryGetMemoryManager<T>(ReadOnlySequence<T> sequence, out MemoryManager<T> manager, out int start, out int length) { throw null; }
    }
}
```

cc @davidfowl, @pakrym, @GrabYourPitchforks, @KrzysztofCwalina, @terrajobst, @benaadams

**Comment by davidfowl** [comment]
No this is needed to support things like RIO in the future. That’s why it was originally added.

**Comment by ahsonkhan** [comment]
> No this is needed to support things like RIO in the future. That’s why it was originally added.

We can always add it back in the future when necessary. However, I don't understand why we would need this on ReadOnlySequence, specifically, to support RIO.

**Comment by davidfowl** [comment]
Oh wait you’re right. We only need the other one for RIo

**Comment by pakrym** [comment]
Removing it should be fine. Closes the circle with previous change.
