### ISSUE TITLE
SqlClient SqlConnectionBasicTests failures in 2.0.x CI

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#28950]
Tracking issue for flaky test failure.  Is there a surgical improvement that can be backported from master to /release/2.0.0 to improve CI reliability for that queue?

https://github.com/dotnet/corefx/pull/27919

https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Frelease~2F2.0.0~2F/test~2Ffunctional~2Fcli~2F/7aa45b89ca5ae46cb15fce46921f40dd925d736b/workItem/System.Data.SqlClient.Tests/analysis/xunit/System.Data.SqlClient.Tests.SqlConnectionBasicTests~2FConnectionTimeoutTestWithThread

```
   at System.Data.SqlClient.Tests.SqlConnectionBasicTests.ConnectionTimeoutTestWithThread()
Assert.True() Failure
Expected: True
Actual:   False
```

/cc @saurabh500 @corivera

**Comment by saurabh500** [comment]
@geleems had made some changes to improve the test. @geleems can you port the fixes to release branch?

**Comment by karelz** [comment]
Given that 2.0 will be out of support in less than 1 month, closing as Won't Fix.
