### ISSUE TITLE
SocketsHttpHandler mangling "User-Agent" header

### ISSUE THREAD

**Issue by CHeavyarms** [dotnet/corefx#28951]
When testing a .NET Core application against the 2.1 preview with the new `SocketsHttpHandler` using the latest build of the .NET Core SDK (info output from CLI listed below), requests sent through an `HttpClient` to a local HTTP echo or capture service shows the new implementation of the `HttpMessageHandler` / `HttpClientHandler` is modifying the "User-Agent" agent header value before sending (or otherwise failing to recompose it correctly after parsing).

Here is an outline of the code:

```csharp
var user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.18 Safari/537.36";

using (var handler = new HttpClientHandler())
using (var client = new HttpClient(handler))
{
    var message = new HttpRequestMessage(HttpMethod.Post, "http://lvh.me:8000/yboe63yb");

    message.Headers.TryAddWithoutValidation("User-Agent", user_agent);
    message.Content = new StringContent(RuntimeInformation.FrameworkDescription, Encoding.UTF8);

    await client.SendAsync(message);
}
```

After completion of the request, here is the capture according to a local instance of [requestbin](https://github.com/Runscope/requestbin), but this has also been validated against other echoing services:

```
POST /yboe63yb HTTP/1.1
Content-Length: 22
Accept-Language: en-US, en; q=0.8
Accept-Encoding: gzip, deflate, br
Host: lvh.me:8000
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng*/*;q=0.8
User-Agent: Mozilla/5.0, (Macintosh; Intel Mac OS X 10_11_3), AppleWebKit/537.36, (KHTML, like Gecko), Chrome/63.0.3239.18, Safari/537.36
Connection: keep-alive
Content-Type: text/plain; charset=utf-8

.NET Core 4.6.26310.01
```

In that output you will see that it appears to be treating that header as a collection of header value entries and is inserting ", " between all the components. That line should read:

```
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.18 Safari/537.36
```

Explicitly disabling the now-`true`-by-default `AppContext` switch for `UseSocketsHttpHandler` returns the header to its original, expected behavior on both Windows (WinHTTP) and Linux (libcurl):

```csharp
AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);
```

As promised, here is the primary host information from `dotnet` CLI:

```
>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-preview3-008433
 Commit:    6b240926a3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview3-008433\

Host (useful for support):
  Version: 2.1.0-preview2-26314-02
  Commit:  8ac5f4fa22

.NET Core SDKs installed:
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.200-preview-007474 [C:\Program Files\dotnet\sdk]
  2.1.300-preview1-008174 [C:\Program Files\dotnet\sdk]
  2.1.300-preview3-008433 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0-preview2-30431 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0-preview2-30431 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview1-26216-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26314-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by stephentoub** [comment]
As a simpler repro, this:
```C#
using System;
using System.Net.Http;

class Program
{
    static void Main()
    {
        var message = new HttpRequestMessage();
        message.Headers.TryAddWithoutValidation("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.18 Safari/537.36");
        foreach (var header in message.Headers)
        {
            foreach (var item in header.Value)
            {
                Console.WriteLine(item);
            }
        }
    }
}
```
outputs:
```
Mozilla/5.0
(Macintosh; Intel Mac OS X 10_11_3)
AppleWebKit/537.36
(KHTML, like Gecko)
Chrome/63.0.3239.18
Safari/537.36
```
on .NET Framework 4.7, .NET Core 2.0, and the latest .NET Core 2.1.

In contrast, on all of those platforms, this:
```
using System;
using System.Net.Http;

class Program
{
    static void Main()
    {
        var message = new HttpRequestMessage();
        message.Headers.TryAddWithoutValidation("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.18 Safari/537.36");
        Console.WriteLine(message.Headers.ToString());
    }
}
```
outputs:
```
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.18 Safari/537.36
```

So using different APIs on HttpHeaders appears to be produce different outcomes.

**Comment by stephentoub** [comment]
cc: @davidsh, @geoffkizer

**Comment by krwq** [comment]
@karelz while I 100% agree this is something we want to fix, I'm seeing identical behavior on full framework (tested with 4.7) which suggests this is not a regression and thus not 100% convinced we want to address it in 2.1 time-frame. I'm suspecting because ToString works correctly we might have not been affected by it before. I'll be happy to fix it in 2.1 but IMO this is more appropriate for 2.2 timeline.

**Comment by geoffkizer** [comment]
@krwq 

> I'm seeing identical behavior on full framework (tested with 4.7) which suggests this is not a regression

You're seeing that WinHttpHandler mangles the header in the same way?

**Comment by krwq** [comment]
@geoffkizer I've tested the simpler repro from @stephentoub. I'll check if the original scenario also repros

**Comment by geoffkizer** [comment]
Relevant code in ProductInfoHeaderParser:

```csharp
        // Unlike most other headers, User-Agent and Server use whitespace as separators
        private const string separator = " ";

...

        private ProductInfoHeaderParser(bool supportsMultipleValues)
            : base(supportsMultipleValues, separator)
        {
        }
```

ProductInfoHeaderParser seems to be the only header parser that does this.  

This seems kinda ugly to me, especially since ProductInfoHeaderParser is the only parser that actually does this.  It would be much cleaner and more consistent to just have ProductInfoHeaderParser parse the raw value itself and not actually treat these as different "header values".

That said, making that parsing change is not trivial, so kinda scary for 2.1 at this point.

I think we should be able to do a small change for SocketsHttpHandler that handles this case.

**Comment by stephentoub** [comment]
> tested the simpler repro from @stephentoub.

My point was meant to be that SocketsHttpHandler is using one approach and netfx and the other handlers is using the other, so they differ.

**Comment by krwq** [comment]
@stephentoub makes sense, my bad - also confirming netfx works correctly

**Comment by geoffkizer** [comment]
I think we can detect this case in HttpConnection.WriteHeadersAsync and do the special handling for `descriptor.Parser.Separator`.  We already have the HeaderDescriptor there, so we just need to add a bit of logic similar to GetHeaderString above that retrieves this and handles it correctly.

Or we could just check for User-Agent specifically in WriteHeadersAsync and handle it specially.  This seems like the smallest impact to both existing logic and perf.  And since this is a weird, one-off case, I don't have any problem special casing it.

**Comment by normj** [comment]
I saw this fix in the daily build. I want to make sure I understand the release flow and that this will go out with the next 2.1 release. This issue is breaking all request to Amazon Web Services with the AWS SDK in .NET Core 2.1 preview 2.

**Comment by karelz** [comment]
It got into master about a week before last integration into release/2.1 branch, so it is in release/2.1 branch and it will ship with next 2.1 release.
You can verify it on daily builds from that branch (labeled '-rc1').

**Comment by normj** [comment]
Awesome thanks
