### ISSUE TITLE
WinHttpRequestStream.Flush Appends "0\r\n\r\n" in Chunked Mode

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#2897]
WinHttpRequestStream.Flush writes "0\r\n\r\n" to the stream every time the method is called in when _chunkedMode is true. This behavior seems wrong. The _endChunk should only be added to the end.

**Comment by shmao** [comment]
Because of this behavior WCF intermittently gets  error saying 'The server returned an invalid or unrecognized response' (see dotnet/wcf#287.)

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar

**Comment by davidsh** [comment]
@shmao Native WinHTTP doesn't handle chunked uploads on its own.  So, we needed to implement the chunked encoding ourselves.  The `WinHttpRequestStream.Flush()` method was meant to be called only once internally.  I'll need to look at the repro to understand how it is being called multiple times.  The stream itself is internal but perhaps it is being exposed thru the `SerializeToStreamAsync()` protected method and that custom `HttpContent` class is calling it multiple times?

**Comment by shmao** [comment]
@davidsh Yes, you were right. The stream can be accessed by inherited 'HttpContent' through 'SerializeToStreamAsync', and the 'Flush()' method can possibly be called at many places. You can have a look at the call stack of [this test](http://dotnet-ci.cloudapp.net/job/dotnet_wcf_outerloop/646/testReport/junit/(root)/ServiceContractTests/DefaultSettings_Echo_RoundTrips_String_Streamed/), which failed because of the issue.

**Comment by davidsh** [comment]
Will be fixed as of PR #2147
