### ISSUE TITLE
SocketsHttpHandler does not work on single core machines

### ISSUE THREAD

**Issue by rmkerr** [dotnet/corefx#28979]
While trying to repro an issue on Win7 I have been running into consistent failures in all tests using Http. I think that it is a result of the changes introduced in PR #28638. 

The assertion being hit is on line 48 of ConcurrentQueue_Segment.cs. `boundedLength` has a value of 1.
https://github.com/dotnet/corefx/blob/943e316297df4b0767e46dbb87f97ea861c6817e/src/Common/src/System/Collections/Concurrent/ConcurrentQueue_Segment.cs#L47-L49

The assertion is failing because of the following lines in SocketsHttpHandler ConnectHelper:
https://github.com/dotnet/corefx/blob/943e316297df4b0767e46dbb87f97ea861c6817e/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs#L19-L22

When the processor count is 1, RoundUpToPowerOf2 returns 1 (2<sup>0</sup>...), which is below the lower bound enforced by ConcurrentQueue. The failures don't repro in CI because all of the test machines have more than one core.

cc: @stephentoub @davidsh

**Comment by karelz** [comment]
@rmkerr can you please check if the same bug is in Preview2? We might need to add it to release notes just in case ...

**Comment by rmkerr** [comment]
The bug was introduced 11 days ago and is in the Release/2.1 branch, so it is probably in Preview 2. I think adding it to the release notes is a good idea.

**Comment by karelz** [comment]
OK, it is in Preview2 then. @rmkerr can you please confirm the behavior (on release) on single-core? Please write description what we should put to release notes based on it, then we can pass it further. Thanks!

**Comment by rmkerr** [comment]
The exception I was seeing was a Debug.Assert, which would not show up in a release build. I'm not sure exactly how the issue would manifest if not caught by the assert, but I can do some testing to find out.

**Comment by stephentoub** [comment]
I think it's possible this could manifest as a hang, unfortunately.

**Comment by rmkerr** [comment]
Thanks for the info Stephen. I just kicked off a release build on my machine to confirm what happens. It's going to take a while (because it only has one core), but I'll let you all know what happens as soon as it finishes.

**Comment by stephentoub** [comment]
FWIW, you should also be able to test the behavior on other machines just by hardcoding a value of 1 to be passed to that Segment ctor.  I suspect some uses will work just fine and others will end up hanging.  We'll see, though. Thanks. And sorry :)

**Comment by rmkerr** [comment]
Hah, that will be a lot faster. I'll give it a try as soon as I have a machine free.

**Comment by rmkerr** [comment]
Yep, I see this manifesting as a hang.

cc: @karelz

**Comment by rmkerr** [comment]
Just based on code inspection I would expect this to happen with all APIs on SocketsHttpHandler that involve creating a connection.

**Comment by stephentoub** [comment]
I would expect it would hang in situations where:
- It was on a single core,
- a thread was making a request that would require creating a new connection, and
- another thread races with it to create a connection on the same handler.

The Debug.Assert that's firing in debug builds is highlighting that the data structure relies on there being at least two slots in the array.  When that's violated and there's just a single slot in the array, the synchronization mechanism in the segment falls apart, so concurrent attempts to use it could result in one of the threads entering an infinite spin loop.

It's possible of course it's worse than that, but that's my guess.

**Comment by karelz** [comment]
@rmkerr can you please add an entry into 2.1 Preview 2 known issues? https://github.com/dotnet/core/blob/master/release-notes/2.1/Preview/2.1.0-preview2-known-issues.md
cc @leecow @Petermarcu

**Comment by rmkerr** [comment]
Yep, on it now.
