### ISSUE TITLE
.NET Core 2.0: FileLoadException

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#28985]
@Krakean commented on [Tue Apr 10 2018](https://github.com/dotnet/core/issues/1416)

Hello.
Using Win 10 x64 Fall Creators Update and .NET Core 2.1.104
I'm getting this when trying to run my game launcher:
https://i.imgur.com/WCzLzah.png (previously it was: BadImageException bla bla reference assemblies should not be loaded for execution bla bla; but after I downgraded System.Numerics.Vector to 4.4.0 - error changed to current one)

Can't understand why this happens. I'm referencing only System.Numerics.Vectors 4.4.0: https://i.imgur.com/YrZYU5t.png

Can this be a problem because of this: I'm making game engine, and dlls of my engine - like system, renderer, 3d engine, sound, network and so on - are Net Standard 2.0 (but I complie them using .NET Core 2.0 toolchain) to force me avoid windows-only functions and trying to keep cross-platform, but game launcher executable (that is just instantiate .net core's game dll that initialize engine) is .NET Framework 4.7.1. 
Could this be a root of issue? If so, how it can be solved?

**Comment by karelz** [comment]
@joperezr it sounds similar to existing problems on 4.7.1 ...

@Krakean if you're running on .NET Framework 4.7.1, then you don't use .NET Core. Can you please clarify?

**Comment by joperezr** [comment]
@Krakean can you try using the latest version of VS 2017? There are some fixes regarding the runtime facades and automatic binding redirects we fixed which should fix your issue when still targetting 4.7.1.

**Comment by Krakean** [comment]
@joperezr it was all tested on vs 15.6.5

**Comment by joperezr** [comment]
that is very weird. If you could provide a minimal repro that would be ideal so that we can figure out what is going on and to get a fix.

**Comment by ViktorHofer** [comment]
Please retry with a more recent version of .NET Core and Visual Studio. As we didn't get a repro I will close this for now. Feel free to reopen if you still hit this error.
