### ISSUE TITLE
.NET Core 2.0: FileLoadException

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#28986]
@Krakean commented on [Tue Apr 10 2018](https://github.com/dotnet/core/issues/1416)

Hello.
Using Win 10 x64 Fall Creators Update and .NET Core 2.1.104
I'm getting this when trying to run my game launcher:
https://i.imgur.com/WCzLzah.png (previously it was: BadImageException bla bla reference assemblies should not be loaded for execution bla bla; but after I downgraded System.Numerics.Vector to 4.4.0 - error changed to current one)

Can't understand why this happens. I'm referencing only System.Numerics.Vectors 4.4.0: https://i.imgur.com/YrZYU5t.png

Can this be a problem because of this: I'm making game engine, and dlls of my engine - like system, renderer, 3d engine, sound, network and so on - are Net Standard 2.0 (but I complie them using .NET Core 2.0 toolchain) to force me avoid windows-only functions and trying to keep cross-platform, but game launcher executable (that is just instantiate .net core's game dll that initialize engine) is .NET Framework 4.7.1. 
Could this be a root of issue? If so, how it can be solved?

---

@Petermarcu commented on [Tue Apr 10 2018](https://github.com/dotnet/core/issues/1416#issuecomment-380217940)

Issue moved to [dotnet/corefx #28985](https://github.com/dotnet/corefx/issues/28985) via [**ZenHub**](https://www.zenhub.com/)

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/28985
