### ISSUE TITLE
Remove SequencePosition comparison operators or change their description

### ISSUE THREAD

**Issue by pakrym** [dotnet/corefx#29001]
We do not guarantee that any comparison of sequence positions would have any meaning but that they contain same values.

https://github.com/aspnet/SignalR/pull/1916/files/1ca2e5f2638f498bb4b57a9d2c69084ecf99bc8f#diff-00c0a7c2117eaeddb8f9964fbdda240aR79

/cc @ahsonkhan  @davidfowl  @KrzysztofCwalina

**Comment by ahsonkhan** [comment]
cc @joshfree, @terrajobst

**Comment by ahsonkhan** [comment]
> but that they contain same values.

@pakrym, what do you mean by this?

> or change their description

Any suggestions or would it be easier to just remove the comparison operators all together?

**Comment by pakrym** [comment]
I think removing all together is better. 

> @pakrym, what do you mean by this?

All it does is `a.GetObject() == b.GetObject() && a.GetValue() == b.GetValue()` and it doesn't mean that you can compare positions logically (`ros.Length ==0` doesn't mean `ros.Start==ros.Length` etc.)

**Comment by davidfowl** [comment]
Just FYI this is a pit of failure, we've had 2 separate developers use these comparison operations and write buggy code that "worked" by mistake.

**Comment by pakrym** [comment]
Can we mark them Obsolete?

**Comment by ahsonkhan** [comment]
> Can we mark them Obsolete?

Does EditorBrowsable.Never make sense on operator overloads?

Is there any scenario where someone would want to use `==` and `!=`? It is a bit strange for us to have a type implementing IEquatable that has restrictions on use of these operations.

> I don't think we should be changing the APIs.

@KrzysztofCwalina, what is your concern with remove them given the pit of failure?

**Comment by KrzysztofCwalina** [comment]
It's too late in the product cycle. I also think that we should make sure positions returned from the same ROS can be compared using == and !=. I am not proposing that we make <,> comparisons work, but I am not sure why equality would not. @pakrym?

cc: @joshfree

**Comment by pakrym** [comment]
It's not too late, we just did a ton of memory-related changes removing two operators is nothing compared to that. 

> I am not sure why equality would not

It requires back reference to ROS.
For example, if one Position is at the end of one segment and second Position is at the beginning of the next one are they equal?
Logically yes, but to implement it correctly you would need to call back to the thing that created Position.

**Comment by KrzysztofCwalina** [comment]
> For example, if one Position is at the end of one segment and second Position is at the beginning of the next one are they equal?

Depends what you mean by "end of segment" and "beginning of segment". If the positions point to the same running index, they are equal; otherwise they are not.

**Comment by pakrym** [comment]
The position does not point to RunningIndexes, they point to `object` only ROS knows how to interpret ROSSegment and RunningIndex.

**Comment by KrzysztofCwalina** [comment]
I know. I was just describing desired semantics.

**Comment by pakrym** [comment]
Do you agree we cannot support these semantics on SequncePosition level?

**Comment by KrzysztofCwalina** [comment]
Well, i don't understand why not. Can you explain? SequencePosition has to represent an unique position in a ROS.

**Comment by pakrym** [comment]
Do you want to put code that casts object to `ReadOnlySequenceSegment` and compares `RunningIndex`  inside `SequencePosition`?

I don't understand how such comparison would be implemented correctly. Especially considering `SequencePosition` is not supposed to be tied to ROS

**Comment by KrzysztofCwalina** [comment]
> Do you want to put code that casts object to ReadOnlySequenceSegment and compares RunningIndex inside SequencePosition?

No, why would we have to do it? If a SequencePositon (tuple of object, int) represents an unique position in a ROS, then comparing the objects and the ints should be all that is needed to determine equality.

>I don't understand how such comparison would be implemented correctly. Especially considering SequencePosition is not supposed to be tied to ROS

SequencePosition.Eqlaus is implemented correctly. It's a structural comparison of a simple struct. If two equal positions don't point to the same location in ROS, then there is a problem with ROS.TryGet. If tow not equal positions point to the same location in ROS, there is a problem with ROS.TryGet.

**Comment by pakrym** [comment]
Imagine ROS representing by the following segments:
```
[              ]->[              ]
               ^   ^
              P1    P2
```

P1 points past the end of Segment 1,
P2 points to the first element of Segment 2


Both of them would give the same result when passed to TryGet and are logically equal but are not structurally equal.

**Comment by KrzysztofCwalina** [comment]
How can code produce P1?

**Comment by pakrym** [comment]
`ros.Slice(ros.First.Length).End`?

**Comment by KrzysztofCwalina** [comment]
We had a discussion about this a couple of months ago. You guys pushed for returning default(SequencePosition) to indicate "after the last item". I used to have default meaning first item and do enable default being the "after last", we needed to add ROS.First (and ISequence.First).

**Comment by pakrym** [comment]
??
```
 public ReadOnlyMemory<T> First => GetFirstBuffer(_sequenceStart, _sequenceEnd);
```

**Comment by pakrym** [comment]
I don't understand how would that help comparison situation.

**Comment by benaadams** [comment]
Should this be api ready not api suggestion?

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/dotnet/corefx/pull/29115 / https://github.com/dotnet/corefx/pull/29184
