### ISSUE TITLE
Synchronous socket methods on Unix requiring extra thread

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#29029]
When just using synchronous methods on a Socket (e.g. Socket.Receive), the calls pass through to the corresponding synchronous methods in the OS (e.g. recvmsg)

However, when an asynchronous operation is issued on a Socket, it puts the underlying socket into non-blocking mode, and due to race conditions that would otherwise result, the socket is left in non-blocking mode for the remainder of its existence.  That means that subsequent synchronous calls to methods on Socket end up taking a sync-over-async path, where it initiates the operation and then blocks on an event that'll be signaled by the event loop when the operation completes.

In .NET Core 2.0 and earlier, that signaling took place on the event loop itself, e.g. with the event loop:
https://github.com/dotnet/corefx/blob/665a428f353ad7c18a59b8d76ac6d4235038db3a/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEngine.Unix.cs#L258
calling HandleEvents:
https://github.com/dotnet/corefx/blob/665a428f353ad7c18a59b8d76ac6d4235038db3a/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEngine.Unix.cs#L287
which would in turn call Complete on the queue:
https://github.com/dotnet/corefx/blob/665a428f353ad7c18a59b8d76ac6d4235038db3a/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs#L1523
which would in turn call TryCompleteAsync on operations:
https://github.com/dotnet/corefx/blob/665a428f353ad7c18a59b8d76ac6d4235038db3a/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs#L440-L442
which for these "synchronous" operations would wake them up by setting the event:
https://github.com/dotnet/corefx/blob/665a428f353ad7c18a59b8d76ac6d4235038db3a/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs#L116-L120

In .NET Core 2.1 unfortunately, that signaling is now taking place via a queued work item.  The event loop still calls HandleEvents:
https://github.com/dotnet/corefx/blob/acb44e79ef7dc81817da9cf5f19c9819d0f491d1/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs#L800-L801
but HandleEvents queues a work item to do the actual processing:
https://github.com/dotnet/corefx/blob/acb44e79ef7dc81817da9cf5f19c9819d0f491d1/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs#L838-L840
That was done for performance reasons for actual async operations, but for these synchronous operations, it creates a problem.

Let's say the thread pool contained a single thread.  If that thread was used to make the "synchronous" call, then that thread will end up blocking waiting for the operation to complete.  For it to complete, a work item gets posted to the thread pool, and that work item needs to be processed, but all of the threads in the pool are currently blocked.  So we end up waiting for the thread pool's starvation mechanism to kick in and introduce another thread. Now let's say the thread pool contains 10 threads and 10 such operations are initiated, each of which does a "synchronous" operation.  Now all 10 threads are blocked, and 10 work items are going to be queued to unblock them.

This can result in seconds of delay for each such operation, plus unnecessary growth in the thread pool.

**Comment by tmds** [comment]
@stephentoub perhaps we can do the sendmsg/recvmsg calls with `MSG_DONTWAIT` instead of making the socket non-blocking. Not sure if all platforms support it.

fyi, I have an open issue for benchmarking this dispatch to the ThreadPool vs handling it directly on the epoll thread: https://github.com/aspnet/KestrelHttpServer/issues/2431.

**Comment by stephentoub** [comment]
> Not sure if all platforms support it.

I don't believe that's supported on macOS, FreeBSD, etc.  I don't see it in the man pages, and I see references around the net to it being ignored when specified even if it compiles.

**Comment by geoffkizer** [comment]
btw, for future reference: 
(1) I do think we should look at using MSG_DONTWAIT in the future
(2) There doesn't seem to be a way to use MSG_DONTWAIT with Accept, so we may have to do something else for Accept specifically

**Comment by stephentoub** [comment]
That sounds good to me, as long as we can make it work everywhere we need it.
