### ISSUE TITLE
SslStream.ShutdownAsync doesn't take a CancellationToken

### ISSUE THREAD

**Issue by qmfrederik** [dotnet/corefx#29024]
[`SslStream.ShutdownAsync`](https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/src/System/Net/Security/SslStream.cs#L434) returns a `Task` but does not take a `CancellationToken`. 

I found this to be odd as the other methods do take a `CancellationToken` and pass it to `Task.Factory.FromAsync`; I guess `ShutdownAsync` could behave the same way.

If this was not intentional (and `ShutdownAsync` should indeed take a `CancellationToken`), I'd be happy to create a PR which implements that.

**Comment by karelz** [comment]
What are the scenarios when the cancellationToken is needed? How is it going to help?

**Comment by davidsh** [comment]
Practically speaking, I don't think this will be a cancel-able operation.  The amount of data being sent on the TCP connection is very small for this operation, i.e. it's just a single SSL alert packet indicating "close_notify" to the other side.  So, in practice, the token will be checked once at the start of the API call and maybe at some point during the TCP write of the SSL packet.  I don't see any scenarios where this is required.

**Comment by qmfrederik** [comment]
The main scenario I had in mind is one where the remote end stopped responding. It's a write/read operation over a network connection so all kinds of timeouts can occur.

It looked like an oversight (as all other methods take a CancellationToken), if it's by design feel free to close the issue.

**Comment by karelz** [comment]
Let's close it, unless we have good suspicion / evidence it is indeed valuable.
