### ISSUE TITLE
System.IO.File.WriteAllBytes hangs when the file to overwrite is an already existing FIFO

### ISSUE THREAD

**Issue by jchoi2022** [dotnet/corefx#29049]
In Linux,  `System.IO.File.WriteAllBytes` method seems to hang when the given file path is an already existing FIFO. I believe such a silent freezing of the program should be avoided.

I observed this issue in Ubuntu 16.04.4 and Debian 9.1 (both x64). I installed  dotnet-sdk-2.1.103 package, and used F#. If you have a problem in reproducing it, please let me know.

```
jason@ubuntu:~/FIFOTest$ ls
FIFOTest.fsproj  Program.fs

jason@ubuntu:~/FIFOTest$ cat Program.fs 
open System
open System.IO

[<EntryPoint>]
let main argv =
    System.IO.File.WriteAllBytes("bar", [|0uy|])
    0 // return an integer exit code

jason@ubuntu:~/FIFOTest$ dotnet build
...
jason@ubuntu:~/FIFOTest$ mkfifo bar
jason@ubuntu:~/FIFOTest$ dotnet run bin/Debug/netcoreapp2.0/FIFOTest.dll
(hangs)
```

**Comment by stephentoub** [comment]
File.WriteAllBytes is just a short-hand for opening the file, doing the write, and closing it, so it would have similar semantics to that, and with a FIFO, such semantics would involve blocking until someone else opens it. Why is that unexpected?

**Comment by stephentoub** [comment]
I can see how the docs are misleading here.  They were written back when .NET was only targeting Windows, where the concept of a FIFO on disk doesn't exist. What this really means is that the file is opened and truncated.  And truncating a FIFO is a nop.

**Comment by joshfree** [comment]
@stephentoub since WriteAllBytes is a convenience method for rapid application development scenarios, shouldn't we handle this scenario better?

**Comment by stephentoub** [comment]
Also, even if there were a way, I'm not convinced we'd want to change it. Logically I think the current behavior makes sense for a FIFO, and if we did actually delete the file, we could leave another process in a bad state.

**Comment by joshfree** [comment]
Yes, I'd propose that if we have permission to the fifo, we **do** stomp over it like the caller asked, even if it leaves a different process on the machine in a bad state.  Along these lines, if a user wants to use a different System.IO.File API to scribble over a system config file, as an example, who are we to stop them from doing what they want? 😸

**Comment by stephentoub** [comment]
My point is, I don't believe stomping over it in that manner is what most users expect. Not with a FIFO, which is very different from a regular file.

**Comment by jchoi2022** [comment]
I admit that I was kind of misled by the description in the documentation. If what it meant was opening and truncating file, current behavior makes sense and is consistent with open() Linux API (where O_TRUNC is ignored for FIFO). I think both behaviors are reasonable, and respect whichever decision you make.

Thank you for all the responses.

**Comment by stephentoub** [comment]
Thanks.  I think it'd be reasonable to update the docs to clarify this (cc: @mairaw), but I think changing the implementation to actually delete a target FIFO would have terrible consequences, e.g. if the writer connected to the FIFO and then the reader connected, it'd be fine, but if the reader connected and then the writer connected, the reader would hang indefinitely.  This is the convenience method; it doesn't make sense for it to do terribly inconvenient/buggy things.

**Comment by mairaw** [comment]
Docs for this API can be found here: https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/File.xml#L4065

@stephentoub not sure if you guys prefer to submit a PR or create an issue at https://github.com/dotnet/docs/issues.

**Comment by jchoi2022** [comment]
FYI, there is something I forgot to mention. Actually, Mono removes the existing FIFO and creates a new file in this situation. I reported this discrepancy to Mono team, as well (https://github.com/mono/mono/issues/8230).

**Comment by stephentoub** [comment]
Actually, I'm going to walk back some of what I said.  For some reason, I thought you were proposing that WriteAllBytes should replace an existing FIFO with a new FIFO, which doesn't make sense to me for the reasons I enumerated.  But now that I read the thread again, that's not what you were proposing: you were saying that WriteAllBytes (and I'd argue more generally a FileStream created with FileMode.Create) should replace whatever's there with a regular file. Right?  If so, I agree with that.

**Comment by stephentoub** [comment]
It's worth looking at why/how Mono differs here. My take is that File.WriteAllBytes is just a short-hand for creating a FileStream with FileMode.Create, and FileMode.Create is documented as "FileMode.Create is equivalent to requesting that if the file does not exist, use CreateNew; otherwise, use Truncate", which is exactly what it's now doing.

**Comment by stephentoub** [comment]
> Actually, Mono removes the existing FIFO and creates a new file in this situation

Really?  That's not what I'm seeing.  I see Mono opening the existing FIFO as well; the difference, though, is it's opening it for both reading and writing, e.g. strace output:
```
openat(AT_FDCWD, "/home/stoub/tmpapp/myfifo", O_RDWR|O_CREAT|O_TRUNC, 0666)
```
whereas .NET Core is opening it just for writing:
```
openat(AT_FDCWD, "/home/stoub/tmpapp/myfifo", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666)
```
and O_RDWR has undefined behavior, e.g. from the Linux man page:
https://linux.die.net/man/3/open
```
O_RDWR
Open for reading and writing. The result is undefined if this flag is applied to a FIFO.
```
From what I can see, at least on my Ubuntu 17.10, this results in the Mono behavior being to open the existing FIFO, write to it, and if there was already a waiting reader, that reader then reads all of the data from the existing FIFO, but if there wasn't, the data is lost, such that the whole operation was a nop.

**Comment by jchoi2022** [comment]
Hm, that is strange. Maybe Mono version is affecting the behavior? I checked once more, by installing Mono in a fresh Ubuntu 16.04.4 image, following the instructions from http://www.mono-project.com/download/stable/#download-lin. It led to installing mono version `5.10.1.20`.

```
jschoi@sss-repo:~/FIFOTest$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
jschoi@sss-repo:~/FIFOTest$ mono --version
Mono JIT compiler version 5.10.1.20 (tarball Thu Mar 29 10:44:58 UTC 2018)
...
```
When I compile and strace the following program, I can observe unlink() call.
```
jschoi@sss-repo:~/FIFOTest$ cat FIFOTest.fs
open System
open System.IO

[<EntryPoint>]
let main argv =
    System.IO.File.Delete("bar")
    System.IO.File.WriteAllBytes("bar", [|0uy|])
    0
jschoi@sss-repo:~/FIFOTest$ fsharpc FIFOTest.fs
jschoi@sss-repo:~/FIFOTest$ mkfifo bar
jschoi@sss-repo:~/FIFOTest$ strace mono FIFOTest.exe
...
stat("/home/jschoi/FIFOTest/bar", {st_mode=S_IFIFO|0664, st_size=0, ...}) = 0
lstat("/home/jschoi/FIFOTest/bar", {st_mode=S_IFIFO|0664, st_size=0, ...}) = 0
geteuid()                               = 1000
unlink("bar")                           = 0
...
open("/home/jschoi/FIFOTest/bar", O_RDWR|O_CREAT|O_TRUNC, 0666) = 3
```

Could you check your Mono version, please?

**Comment by stephentoub** [comment]
> When I compile and strace the following program, I can observe unlink() call.

That's because you're calling File.Delete in your program.

**Comment by jchoi2022** [comment]
Oh, I am sorry for the mistake. I inserted File.Delete for some other purpose, and forgot to remove. 

And yes, now I can observe the Mono behaving as you described. I will update some of the comments accordingly, to avoid confusion. Thank you for the correction.

**Comment by stephentoub** [comment]
I believe the issue has been fully explored, so I'm going to close this.  If there's still an open issue here, please feel free to clarify and re-open.
