### ISSUE TITLE
Server WebSocket packet fragmentation error

### ISSUE THREAD

**Issue by maincoon** [dotnet/corefx#29055]
Found this while testing web socket server on Windows platform.
Attached test project reproduces error on Widows platform, but worked on Linux.

[WSTest.zip](https://github.com/dotnet/corefx/files/1902389/WSTest.zip)

**Comment by karelz** [comment]
@maincoon what is the error you're getting with your repro? What is the output / expected output?

**Comment by maincoon** [comment]
On windows:
dotnet --version
2.1.101

On linux (that's also a bug i guess):

[root@ud-dev06-lxc-test-v test]# dotnet --version
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
[root@ud-dev06-lxc-test-v test]# yum list installed | grep dotnet
dotnet-host.x86_64                 2.1.0_preview1_26216_03-1          @packages-microsoft-com-prod
dotnet-hostfxr-2.0.6.x86_64        2.0.6-1                            @packages-microsoft-com-prod
dotnet-runtime-2.0.6.x86_64        2.0.6-1                            @packages-microsoft-com-prod
[root@ud-dev06-lxc-test-v test]#

**Comment by karelz** [comment]
2.1.101 is .NET Core SDK version - it corresponds to .NET Core 2.0.6: https://github.com/dotnet/core/blob/master/release-notes/download-archive.md#net-core-20

Let's not mix bug reports - Linux seems to have parts of 2.1 Preview 1 and 2.0.6 installed. Can you please remember how you got into the state, try to reproduce it on clean VM and then report on core-setup repo? Let's not cover that problem here.

**Comment by maincoon** [comment]
I believe problem not in .NET core but in .NET47
Stacktrace shows error in WebSocket implementation from .NET47 System.Net.WebSockets.WebSocketBuffer wich is not exists in core implementation at all. 
Any advice on this?

**Comment by karelz** [comment]
Can you please run your test on .NET Core on Windows? Let's confirm for sure it is a problem of .NET Framework vs. .NET Core.

**Comment by maincoon** [comment]
Not sure I understand You. Project in attachment built and run on windows using .net core and proposed output with exception produced whith command 'dotnet WStest.dll'. Same built runs as expexted on linux using the same command.

**Comment by rmkerr** [comment]
Hey @caesar1995, does this look like the WebSocket issue you fixed recently with #28325?

**Comment by davidsh** [comment]
I was able to reproduce this problem.

The exception happens on .NET Core 2.0 including latest servicing release 2.06.

The exception does not happen on .NET Core 2.1 preview 2.

**Comment by davidsh** [comment]
Please try out .NET Core 2.1 Preview 2:
https://blogs.msdn.microsoft.com/dotnet/2018/04/11/announcing-net-core-2-1-preview-2/
