### ISSUE TITLE
StackTrace's LineNumber and FileName is empty on net461

### ISSUE THREAD

**Issue by fitzchak** [dotnet/corefx#29056]
When running the following code:

```
StackFrame stackFrame = new StackTrace(true).GetFrames().Last();
var lineNumber = stackFrame.GetFileLineNumber();
var fileName = stackFrame.GetFileName();
```
In the following target frameworks `<TargetFrameworks>netcoreapp2.0;net461</TargetFrameworks>`:

The line number and file name are empty when the target is net461, but when the target is netcoreapp2.0 the line number and file name have the correct values.

**Comment by jnm2** [comment]
@fitzchak You're probably using portable PDBs. https://github.com/dotnet/core/blob/master/Documentation/diagnostics/portable_pdb.md#supported-scenarios:

> Applications targeting .NET Framework 4.7.1 or earlier: printing stack traces with mappings back to line numbers (such as in an ASP.NET error page). The name of methods is unaffected, only the source file names and line numbers are unsupported.

**Comment by fitzchak** [comment]
This make sense. Thanks.
