### ISSUE TITLE
Build failures in 'prodcon/corefx/master/' - '20180411.05'

### ISSUE THREAD

**Issue by jcagme** [dotnet/corefx#29067]
@dotnet-mc-bot commented on [Wed Apr 11 2018](https://github.com/dotnet/core-eng/issues/3237)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1582339
  - **Agent:** DDVSOLINUXAGE010
  - **Error log:** /root/corefx-1582339/Tools/ApiCompat.targets(0,0): error : MembersMustExist : Member 'System.Memory<T>..ctor(System.Buffers.MemoryManager<T>, System.Int32, System.Int32)' does not exist in the implementation but it does exist in t...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1582341
  - **Agent:** DDVSOLINUXAGE013
  - **Error log:** /root/corefx-1582341/Tools/ApiCompat.targets(0,0): error : MembersMustExist : Member 'System.Memory<T>..ctor(System.Buffers.MemoryManager<T>, System.Int32, System.Int32)' does not exist in the implementation but it does exist in t...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1582344
  - **Agent:** DDVSOMACAGE008
  - **Error log:** /Users/buildagent/agent/_work/0/s/corefx/Tools/ApiCompat.targets(0,0): error : MembersMustExist : Member 'System.Memory<T>..ctor(System.Buffers.MemoryManager<T>, System.Int32, System.Int32)' does not exist in the implementation bu...

**Comment by ahsonkhan** [comment]
I suspect this is a one-off failure due to changes in flight between the corefx/coreclr repo. We shouldn't see this error again. Please re-open if it happens again.

The last few (recent) builds have been successful (starting from [20180412-12](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/index?buildId=1583570&_a=summary)).
