### ISSUE TITLE
Proposed: Add `System.Reflection.NullReference` sentinel type.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#29060]
# Proposed Surface Area

```
namespace System.Reflection
{
    public sealed class NullReference
    {
        public static readonly NullReference Value = new NullReference();
    }
}
```

## Purpose

To be used as the return value when Reflection Invoke is used to invoke a method or property returning a `ref` and the method returns a null reference. Invoking ref-return methods is not supported at this time but we already an in-progress issue to make it supported (https://github.com/dotnet/corefx/issues/15960)

Could also be used by existing Reflection Invoke api to pass null references as arguments.

# Alternatives considered

### Return `Missing.Value` instead.

Pros: Saves us a little surface area.

Cons: This has received significant pushback from @vsadov:

> Missing.Value is used for many other purposes. DLR and VB latebinders, for example use Missing.Value to propagate the fact that user did not pass a particular argument to expected optional parameters.
> Returning Missing.Value in a case of a failure will lead to situations where it will be impossible to tell whether the invocation failed or succeeded and returned a Missing.Value.
> 

Indeed, it is overloading a sentinel with a defined meaning ("caller chose not to supply optional parameter") for something completely different.

### Throw `NullReferenceException`

Pros: No ambiguity, for this particular api, this represents an attempt to dereference a null reference which is a programming error and there is precedent for `NullReferenceException` here.

Cons: Reflection Invoke throws all programming error-related exception before invoking the target method. This would be a new precedent as the exception would be thrown after a successful call of the target method.

**Comment by VSadov** [comment]
What would this sentinel be representing? A value of a dereferenced `null`? 

Dereferencing `null` should result in a [Boneheaded Exception](https://blogs.msdn.microsoft.com/ericlippert/2008/09/10/vexing-exceptions/)
Hiding a null dereference behind a special value is not making the situation easier to handle or easier to debug.

When reflection call implies a null dereference it should just throw, just as earlybound invocation would.

**Comment by MichalStrehovsky** [comment]
> What would this sentinel be representing?

When used as a `ref` parameter, it would represent a null ref.

When returned from `MethodBase.Invoke` it would help `MethodBase.Invoke` do what it does: give you a boxed result of the invocation, or the "next best thing" (the precedent being `System.Reflection.Pointer` which is the "next best thing" for methods that return unmanaged pointer types that can't otherwise be boxed). This is a next best thing for a null reference result (where the "next best thing" is a dereferenced result otherwise).

**Comment by AtsushiKan** [comment]
The arguments in favor of `NullReferenceException` have convinced me. Closing this.
