### ISSUE TITLE
One more issue in ECMA-335

### ISSUE THREAD

**Issue by k15tfu** [dotnet/corefx#29073]
Hi!

I found an issue in ECMA-335 and want to know how you deal with it.  In III.3.6 bge.<length> section there are contradictory statements (https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-335.pdf):
> The effect is identical to performing a clt.un instruction followed by a brfalse target

and

> The effect of a “bge target” instruction is identical to:
> * If stack operands are integers, then clt followed by a brfalse target
> * If stack operands are floating-point, then clt.un followed by a brfalse target

So there you can see a discrepancy in case of integer operands. Could you pls say me what did you do with this?  I was going to submit a report to someone interested in it (probably not you) but can't find the right persons.

cc: @tmat @nguerrera

**Comment by tmat** [comment]
@VSadov

**Comment by karelz** [comment]
cc @CarolEidt

**Comment by VSadov** [comment]
The second quotation is correct. The first is imprecise. It probably should say 
```
The effect is identical to performing a clt[.un] instruction followed by a brfalse target
```

Inversion of relational operations works differently for integers and floats because integers do not have NaN and floats do.

**Comment by k15tfu** [comment]
Cool. Are there any other "imprecises" stated in ECMA-335 with conditional branches? :)

**Comment by VSadov** [comment]
@k15tfu - I do not know :-)  I've never noticed this one either.

For `bge.un` you will have the similar difference between integers and floats. For integers the inverse will have to have the same `.un` and for floats it should be the opposite.

**Comment by k15tfu** [comment]
@VSadov - Ouhh.. This statement I found in http://jilc.sourceforge.net/ecma_p3_cil.shtml#_Toc524462315 :

> The bge.un instruction transfers control to target if value1 is greater than or equal to value2, when compared unsigned (for integer values) or unordered (for float point values). The effect is identical to performing a clt instruction followed by a brfalse.

As a result, I made the following table:

### Meaning of branch-on-* instructions for **_Integer_** and **_Floating-Point_** operands:
**No** | **Instruction**  | **Identical to**
----| -------------------------|--------------------
 1  | `beq.<lenght>`      | **_Both_**: `ceq` then `brtrue`
 2  | `bge.<lenght>`      | **_Integer_**: `clt` then `brfalse` / **_Floating-Point_**: `clt.un` then `brfalse`
 3  | `bge.un.<length>` | (See below)
 4  | `bgt.<length>`       | **_Both_**: `cgt` then `brtrue`
 5  | `bgt.un.<length>`  | **_Both_**: `cgt.un` then `brtrue`
 6  | `ble.<length>`       | **_Integer_**: `cgt` then `brfalse` / **_Floating-Point_**: `cgt.un` then `brfalse`
 7  | `ble.un.<length>`  | **_Integer_**: `cgt.un` then `brfalse` / **_Floating-Point_**: `cgt` then `brfalse`
 8  | `blt.<length>`        | **_Both_**: `clt` then `brtrue`
 9  | `blt.un.<length>`   | **_Both_**: `clt.un` then `brtrue`
10 | `bne.un.<length>` | **_Both_**: `ceq` then `brfalse`

Is everything else okay in this table?

I have fixed No. 2 as you suggested (thank you for this) and you said No. 3 is also wrong. The correct for No.3 is "**_Integer_**: `clt.un` then `brfalse` / **_Floating-Point_**: `clt` then `brfalse`"   ??

**Comment by VSadov** [comment]
Yes, that sounds right.

You may also want to check this table. 
That is how C# compiler maps <, >, <=, >= to opcodes:

https://github.com/dotnet/roslyn/blob/94ef9a5c8db05b23f6eefa528988d99573ac2eeb/src/Compilers/CSharp/Portable/CodeGen/EmitOperators.cs#L280

**Comment by k15tfu** [comment]
Well, `s_compOpCodes` is about mapping <<=>=> to clt[.un]/cgt[.un] instructions.

How I can check the corresponding identical sequence of clt[.un]/cgt[.un] + br{false,true} instructions for branch-on-* instructions family?

**Comment by k15tfu** [comment]
Thanks a lot!
