### ISSUE TITLE
Backing up HttpClient by an interface

### ISSUE THREAD

**Issue by ffMathy** [dotnet/corefx#29086]
If `System.Net.HttpClient` was backed up by an interface (perhaps `IHttpClient`) for most of its methods, it would be easier to mock and fake.

**Comment by benaadams** [comment]
You can do this for `HttpClient` by creating a [`HttpMessageHandler`](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpMessageHandler.cs) and passing that to its constructor?

i.e. `HttpClient` just calls the `SendAsync` method of `HttpMessageHandler`; which an easier route than trying to mock every method of `HttpClient` as their are many.

**Comment by stephentoub** [comment]
There's a long discussion of this at https://github.com/dotnet/corefx/issues/1624. Closing as dup.
