### ISSUE TITLE
IBufferWriter should have a Length property

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#29108]
This should be return the amount of buffered bytes. I was thinking that it would be simple to add this to PipeWriter but we actually should have this on `IBufferWriter<T>`. It's required for writing out length prefixed protocols:

```C#
public void WriteMessage(Message message, IBufferWriter<byte> output)
{
      // Always a 4 byte length prefix
     Span<byte> prefix = output.GetSpan();
     output.Advance(4);

     long oldLength = output.Length;

     // Write message to a buffer so we can get its length
     WriteMessageCore(message, output);

     long written = output.Length - oldLength;

     // Fill in the length prefix afterwards
     BinaryPrimitives.WriteInt32BigEndian(prefix, (int)written);
}
```

/cc @KrzysztofCwalina @pakrym

**Comment by davidfowl** [comment]
@joshfree @ahsonkhan so this is an interface and we can't change it after we ship 2.1...

**Comment by pakrym** [comment]
Can't you wrap it into a something that would do counting? IBufferWriter itself doesn't really have any concept of buffering, it appears only when you add Flush like in PipeWriter.

**Comment by davidfowl** [comment]
It is fully buffered because it doesn’t have a flush. It would force me to allocate to get a length prefix.

**Comment by pakrym** [comment]
> It is fully buffered because it doesn’t have a flush

There is no promise of buffering in IBufferWriter, even you sample is wrong, as soon as you call `Advance()`  memory should not be used. For all you know it was a native pointer that has already been freed.

**Comment by davidfowl** [comment]
Meh, I don't buy that, I *maybe* would have agreed, but if you freed the memory after Advance, lots of other things won't work. This interface is about buffered writes and we shouldn't pretend it's not.

**Comment by pakrym** [comment]
I completely disagree, it is about dumping bytes somewhere without fixed buffer sizes not about buffering

**Comment by davidfowl** [comment]
I disagree with that. If it's not fully buffered then it's a performance disaster waiting to happen (no way to flush). We can rename it to `IBufferedWriter` so that the name states that it is buffered.

**Comment by pakrym** [comment]
It can be buffered to a point (imagine auto flush every 2k) but not entirely. Would still break you scenario. Also you sample is disaster waiting to happen if message size is large.

**Comment by davidfowl** [comment]
Synchronous auto flush?

**Comment by davidfowl** [comment]
LOL

**Comment by KrzysztofCwalina** [comment]
@davidfowl, why would WriteMessageCore not simply return the number of bytes it wrote?

**Comment by davidfowl** [comment]
Blah, I guess it's too late to add this.
