### ISSUE TITLE
Outbound connections time out with new managed sockets

### ISSUE THREAD

**Issue by dfederm** [dotnet/corefx#29118]
When upgrading from 2.1 preview 1 to preview 2, all of a sudden all the outbound calls from my asp.net core app (except Azure SQL calls for some reason) seem to hang and eventually timeout. I'm seeing this behavior with both an HttpClient and using the latest Azure Storage SDK.

Based on the release notes, I suspected it's due to the switch to managed sockets and confirmed this by setting `DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER` to 0 and noticing the calls working again.

I'm running on Azure App Services using self-contained deployment.

**Comment by stephentoub** [comment]
Are you running on a machine with a single core / where Environment.ProcessorCount returns 1?  There's an unfortunate bug in Preview 2 that can result in hangs on a single core machine; it's already been fixed, but we didn't discover it until after we'd already forked for Preview 2.

**Comment by dfederm** [comment]
@stephentoub Yup, I'm using an Azure plan which only gives me one core so I assume that `Environment.ProcessorCount` would also only return 1.

Thanks for the confirmation. If it's a known issue, and better yet already fixed, then that's fine. It is a preview after all :).

Happen to have an issue number and/or PR number to link this issue to?

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/issues/28979
#28983
