### ISSUE TITLE
Windows builds should always be portable

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/corefx#29113]
See dotnet/coreclr#17533.

**Comment by ViktorHofer** [comment]
Talked with @eerhardt offline. We always want to produce portable assets on Windows. We should get rid of any portable switches for Windows and just make portable the default.

**Comment by ViktorHofer** [comment]
We already build portable by default on Windows: https://github.com/dotnet/corefx/blob/master/Directory.Build.props#L207
