### ISSUE TITLE
.Net Core 2.0 mvc.razor.viewcompilation.rsp build exception MSB3073 exited with code -2147450751

### ISSUE THREAD

**Issue by DenisKot** [dotnet/corefx#29125]
Build solution fails with strange error:

> Error	MSB3073	The command ""dotnet" exec --runtimeconfig "F:\TrackTubeNew\Src\TreckTube\bin\Debug\netcoreapp2.0\TreckTube.Web.runtimeconfig.json" --depsfile "F:\TrackTubeNew\Src\TreckTube\bin\Debug\netcoreapp2.0\TreckTube.Web.deps.json" "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj\Debug\netcoreapp2.0\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code -2147450751.	TreckTube.Web	C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets	60	

If double click on error VS opens up file:

> C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets

At line:
`<Exec Command="$(ExecArgs)" WorkingDirectory="$(MSBuildProjectDirectory)" />`

To fix it I've tried to update .net core libraries from version 2.0.0. to 2.0.6, have been update visual studio 2017 to 17.6.6, even revret my changes but nothing is helping.

How to fix it?

**Comment by DenisKot** [comment]
If to set in .csproj 
`<MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>`
it builds. But I'm not publishing I'm just debugging.
But it means that it will not compile if I will publish :(

**Comment by karelz** [comment]
This issue was moved to aspnet/Razor#2280
