### ISSUE TITLE
.net core  dll as a reference behaves differently from .net

### ISSUE THREAD

**Issue by ankgupta067** [dotnet/corefx#29143]
create a .net standard dll , name it as Paas dll, and change the output path ..\Output\

add a class logger like below-

```c#
public class Logger 
    {
        public void LogMessage()
        {
            Console.Write("test");
        }
    }
```

Now create another .net core console project in solution and add dll as a refrence ( not project refrence) for pass.dll and make copy local to false.

Also change output directory of console app to ..\Output\

add below code in console app -

 ```c#
var logger = new Logger();
  logger.LogMessage();
  Console.Read();
```

Build and run .net core app, but now application goes in break mode with below error

```
Could not load file or assembly 'Paas, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

But if you perform same steps with .net framework 4.6.1 projects it works, why this different behavior with .net core exists and how to fix it?

Github project for more clarity -
https://github.com/ankgupta067/DependencyInjection

[EDIT] Change code & exception formatting by @karelz

**Comment by karelz** [comment]
I am able to reproduce the problem with .NET Core 2.0 - the application does not need to set copy local false, or change its output (to minimize the repro). Either change library output directory, or just copy the output somewhere else - the project system won't find the library project and therefore won't generate necessary entries in app.deps.json file. It may be even by design.

app.deps.json with project-to-project reference (App_ProjectDep -> MyLib):
```json
{
  "runtimeTarget": {
    "name": ".NETCoreApp,Version=v2.0",
    "signature": "da39a3ee5e6b4b0d3255bfef95601890afd80709"
  },
  "compilationOptions": {},
  "targets": {
    ".NETCoreApp,Version=v2.0": {
      "App_ProjectDep/1.0.0": {
        "dependencies": {
          "MyLib": "1.0.0"
        },
        "runtime": {
          "App_ProjectDep.dll": {}
        }
      },
      "MyLib/1.0.0": {
        "runtime": {
          "MyLib.dll": {}
        }
      }
    }
  },
  "libraries": {
    "App_ProjectDep/1.0.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    },
    "MyLib/1.0.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    }
  }
}
```

app.deps.json without project-to-project reference (MyApp -> MyLib.dll):
```json
{
  "runtimeTarget": {
    "name": ".NETCoreApp,Version=v2.0",
    "signature": "da39a3ee5e6b4b0d3255bfef95601890afd80709"
  },
  "compilationOptions": {},
  "targets": {
    ".NETCoreApp,Version=v2.0": {
      "MyApp/1.0.0": {
        "runtime": {
          "MyApp.dll": {}
        }
      }
    }
  },
  "libraries": {
    "MyApp/1.0.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    }
  }
}
```

**Comment by karelz** [comment]
This issue was moved to dotnet/project-system#3487
