### ISSUE TITLE
NuGet build failures in 'prodcon/corefx/master/' - '20180416.01'

### ISSUE THREAD

**Issue by jcagme** [dotnet/corefx#29144]
@dotnet-mc-bot commented on [Sun Apr 15 2018](https://github.com/dotnet/core-eng/issues/3292)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1594896
  - **Agent:** DDVSOLINUXAGE007
  - **Error log:** /root/corefx-1594896/external/runtime/runtime.depproj : error NU1102: - Found 414 version(s) in https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json [ Nearest version: 2.1.0-preview3-26416-01 ]...

@mmitche

**Comment by karelz** [comment]
@jcagme the area-Infrastructure covers everything around builds, testing, packaging that is not clear C# product code bug. See [areas descriptions](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#areas).

**Comment by jcagme** [comment]
Fixed by @weshaggard with dotnet/corefx@4036846
