### ISSUE TITLE
DateTime format with CultureInfo differences

### ISSUE THREAD

**Issue by martinmikulka** [dotnet/corefx#29156]
Hello, 

I've got simple Core2.0 console application, which produces different outputs on different platforms.

```
static void Main(string[] args)
{
    var d = new DateTime(2018, 3, 13, 0, 0, 0, DateTimeKind.Utc);
    Console.WriteLine(d.ToString("d", new CultureInfo("fa-IR")));
}
```

Windows 10: (expected output)
22/12/1396

Windows Server 2012 R2: (not converted into persian calendar)
13/03/2018

Both platforms have runtime 2.0.6 installed.
```
Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```

Desired culture is available on both platforms, checked with this piece of code.

```
var cultures = CultureInfo.GetCultures(CultureTypes.AllCultures);
foreach (var culture in cultures) {
    Console.WriteLine($"{culture.Name} - {culture.DisplayName}");
}

```

Please what can I do to make it work as desired?
Thank you.

Martin

**Comment by kasper3** [comment]
I'd try changing the current culture of application:

```c#
static void Main(string[] args)
{
    CultureInfo.CurrentCulture = CultureInfo.GetCultureInfo("fa-IR");
    var d = new DateTime(2018, 3, 13, 0, 0, 0, DateTimeKind.Utc);
    Console.WriteLine(d.ToString("d", CultureInfo.CurrentCulture);
}
```

**Comment by martinmikulka** [comment]
No change in output :(

**Comment by tarekgh** [comment]
This is by design. The framework is depending on the underlying OS for getting the globalization data. On Windows we depend on the Windows NLS APIs and on Linux we depend on ICU library. If you see anything wrong with the reported data, you can report this to Windows or ICU library.

**Comment by martinmikulka** [comment]
Ok, thank you for your input.

While trying to solve my issue, I have found out, that Persian calendar is not available on Win Server 2012 R2. Below is output from the program, which dumps default and optional calendars from CultureInfo.

```
Win Server 2012 R2:
Default Calendar for CultureInfo("fa-IR"):
System.Globalization.GregorianCalendar

Optional Calendars:
System.Globalization.GregorianCalendar
System.Globalization.HijriCalendar
System.Globalization.GregorianCalendar
System.Globalization.GregorianCalendar
System.Globalization.GregorianCalendar

```

```
Win 10:
Default Calendar for CultureInfo("fa-IR"):
System.Globalization.PersianCalendar

Optional Calendars:
System.Globalization.PersianCalendar
System.Globalization.GregorianCalendar
System.Globalization.HijriCalendar
System.Globalization.GregorianCalendar
System.Globalization.GregorianCalendar
System.Globalization.GregorianCalendar

```

**Comment by tarekgh** [comment]
@martinmikulka  right,, Windows started to support Persian calendar recently. what exactly you want to achieve here as this is not clear to me.
