### ISSUE TITLE
new SqlDouble(NaN) is only allowed on NETFX

### ISSUE THREAD

**Issue by dotMorten** [dotnet/corefx#29150]
SqlDouble has a weird platform difference:
```cs
        public SqlDouble(double value)
        {
#if !netfx
            if (!double.IsFinite(value))
#else
            if (double.IsInfinity(value) || double.IsNaN(value))
#endif
            {
                throw new OverflowException(SQLResource.ArithOverflowMessage);
            }
            else
            {
                m_value = value;
                m_fNotNull = true;
            }
        }
```
https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/src/System/Data/SQLTypes/SQLDouble.cs#L40

This means I can insert NaN values when using the .NET Framework, but when running the same code on a different platform, I get a crash here.
Easy to reproduce:
```
new SqlDouble(double.NaN); //Crashes on anything but NETFX
```

This is rather problematic because NaN is commonly used in the SqlGeometry and SqlGeography datatypes to represent Z and M values, where for instance a line generally contains Z measurements, but on some vertices they might not be available. The behavior is described in [Microsoft SQL Server CLR Types Serialization Formats ](https://msdn.microsoft.com/en-us/library/ee320529(v=sql.105).aspx) on Page 9:

![image](https://user-images.githubusercontent.com/1378165/38840339-f587cb66-4193-11e8-8ea6-ed0038daaded.png)

**Comment by dotMorten** [comment]
@tannergooding Can you share the reasoning behind this commit: https://github.com/dotnet/corefx/commit/1194cdd15a91f0431c19cb2a03d5959aa698e658 ?

**Comment by karelz** [comment]
@keeratsingh @David-Engel @AfsanehR @saurabh500 @divega looks like a breaking change with impact on SqlClient ...

**Comment by saurabh500** [comment]
@tannergooding who made this change in https://github.com/dotnet/corefx/commit/1194cdd15a91f0431c19cb2a03d5959aa698e658
as part of https://github.com/dotnet/corefx/pull/22490

**Comment by dotMorten** [comment]
Brainfart! It says 'IsFinite' not 'IsInfinite' and the behavior is the same on both platforms.

**Comment by tannergooding** [comment]
Right, the resulting behavior should be the same, but using a single combined check, rather than two separate checks.
