### ISSUE TITLE
Microsoft OData - StackOverflowException when using $select with more than 100 columns

### ISSUE THREAD

**Issue by joseterranova** [dotnet/corefx#29164]
I'm having this problem (StackOverflowException) with .Net Framework 4.7.1, EF 6.2 and Microsoft.AspNet.OData 6.1. I'm trying to select more than 100 columns. Here is the stacktrace, hope someone can help me,

![image](https://user-images.githubusercontent.com/29802115/38834603-8808d134-418e-11e8-9ce7-bbe297963a08.png)

**Comment by kasper3** [comment]
Belongs to https://github.com/OData/WebApi?

**Comment by karelz** [comment]
Likely there. Nothing related to CoreFX here.
Pro-tip: Copy-paste exception as text. It is impossible to search for substrings in pictures :(

**Comment by Kevat** [comment]
I'm seeing similar issues with oData and EFCore. Was a correct issue created in the oData/webapi project? If so, could someone please link to that issue here?
