### ISSUE TITLE
Add High level System.Reflection.Metadata API

### ISSUE THREAD

**Issue by AceHack** [dotnet/corefx#29172]
Please add high-level APIs that can be used without having to deference/follow all the pointers/handles.  I would love to just load an assembly and loop through the tree.

**Comment by jnm2** [comment]
Covered by https://github.com/dotnet/corefx/issues/2800?

**Comment by AceHack** [comment]
@jnm2 maybe, what I'm looking for is something very similar to [Mono.Cecil](https://github.com/jbevain/cecil).  This API is already very similar if I didn't have to follow all the pointers around.

**Comment by jnm2** [comment]
@AceHack Then Cecil seems like it would be perfect for you. Why not use that?

**Comment by AceHack** [comment]
I really only need the reading side of things and it would be great to have something that is always kept up to date and released with the .net versions.

**Comment by nguerrera** [comment]
> Cover by #2800? 

Yes. This is what we should do. We should not invent yet another high level API for inspecting metadata. I am closing this in favor of that.
