### ISSUE TITLE
MemoryExtensions.Equals with StringComparison

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/corefx#29170]
I'm trying to check for certain file extensions with the new `Span` APIs. I came across some odd behavior. Here's where I started, which, of course, only works for case-insensitive cases (i.e. Linux):

```
foreach (var extension in _extensionsToWatch)
{
    if (Path.GetExtension(entry.FileName).SequenceEqual(extension))
        return true;
}
```

`SequenceEqual` doesn't have a case-insensitive overload, so I found 

`if (MemoryExtensions.Equals(Path.GetExtension(entry.FileName), extension, StringComparison.OrdinalIgnoreCase))` which works.

But I like to call extension methods as extension methods, so I rewrite this as

`if (Path.GetExtension(entry.FileName).Equals(extension, StringComparison.OrdinalIgnoreCase))`

But now I get a compiler error

> Member 'object.Equals(object, object)' cannot be accessed with an instance reference; qualify it with a type name instead

OK, that's odd. Shouldn't it have picked up the `MemoryExtensions` extension method used above?

Now this next one I stumbled into on accident

`if (Path.GetExtension(entry.FileName).Equals((extension, StringComparison.OrdinalIgnoreCase)))`

The difference is subtle, but all I did was add some redundant(?) parentheses. No compiler error, but I get a runtime error

> System.NotSupportedException: 'Equals() on Span and ReadOnlySpan is not supported. Use operator== instead.'

So now it is telling me to use the `==` operator, which, I assume, will do a case-sensitive comparison, which is the opposite of what I want, and is not valid replacement for `StringComparison`.

Why are things not working like I think they should?

**Comment by ahsonkhan** [comment]
Is `extension` a string type? If so, the compiler is not matching to the correct overload (this issue has been resolved in C# 7.3).

**Try this:**
```C#
if (Path.GetExtension(entry.FileName).Equals(extension.AsSpan(), StringComparison.OrdinalIgnoreCase))
```
or
```C#
if (Path.GetExtension(entry.FileName).Equals((ReadOnlySpan<char>)extension, StringComparison.OrdinalIgnoreCase))
```

**Comment by ahsonkhan** [comment]
cc @VSadov, @joshfree, @AlexGhiondea, @KrzysztofCwalina

**Comment by MisinformedDNA** [comment]
Yep, `extension` is a string. Casting or changing to 7.3 got rid of the errors. Thanks.
