### ISSUE TITLE
System.IO.FileSystem.DriveInfo.Tests hung on RHEL73

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#29187]
@Anipik shouldn't this have dumped a stack for us?

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180418.02/workItem/System.IO.FileSystem.DriveInfo.Tests/wilogs

**Comment by Anipik** [comment]
Currently we don't get dumps for hung jobs through lldb.

**Comment by danmosemsft** [comment]
Because of the issue Mike is investigating? Who owns the next action to make this work?

**Comment by Anipik** [comment]
Mike`s dump was different. There is currently no one working on this. I worked on it briefly during last week but hit the roadblock as it required to make some changes on the helix side. (Just got the azure storage account to test that). I will proceed with it

**Comment by danmosemsft** [comment]
Need new approach
