### ISSUE TITLE
How to trace System.Net ?

### ISSUE THREAD

**Issue by ashishnegi** [dotnet/corefx#29210]
I am following the similar steps of [Network Tracing in .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/network-tracing) for CoreClr web app.

However, I don't see the `network.log` getting generated.
When I do the same steps in .Net Framework web app, it does generate the log file.

Sample coreclr web app with config file : [TraceSystemNetCoreClrNotWorking.zip](https://github.com/dotnet/corefx/files/1926810/TraceSystemNetCoreClrNotWorking.zip)
Sample .Net Framework project which is working : [TraceSystemNetNetFrameworkWorking.zip](https://github.com/dotnet/corefx/files/1926818/TraceSystemNetNetFrameworkWorking.zip)

Note : Change the absolute path in `WebApplication1.web.config` while trying above app locally.

I need this so that i can debug the network connection failures in production.

**Comment by davidsh** [comment]
.NET Core uses a completely different form of tracing for networking.  It uses EventSource which is based on ETW.

Please take a look at this instructions:
https://github.com/dotnet/corefx/blob/master/Documentation/debugging/windows-instructions.md

**Comment by ashishnegi** [comment]
@davidsh I want to trace : 
```
"System.Net" 
"System.Net.Cache"
"System.Net.Http"
"System.Net.Sockets"
"System.Net.WebSockets"
```

Can you confirm that the list of `Providers` provided on above documentation for my use case is complete ? 
```
"{e03c0352-f9c9-56ff-0ea7-b94ba8cabc6b}"
"{066c0e27-a02d-5a98-9a4d-078cc3b1a896}"
"{bdd9a83e-1929-5482-0d73-2fe5e1c0e16d}"
```

**Comment by karelz** [comment]
The list of Networking providers is here IMO: https://github.com/dotnet/corefx/blob/master/Documentation/debugging/windows-instructions.md#systemnet-namespaces

**Comment by davidsh** [comment]
@ashishnegi Please follow the instructions in the above documentation.  The provider list is different than .NET Framework.  For example, there is no "System.Net.Cache".  In fact, those types are a no-op in .NET Core.

For HTTP tracing, the tracing output is limited for .NET Core 1.0, 1.1, 2.0.  This is since the HTTP stacks are built on native platform HTTP stacks.  However, starting with .NET Core 2.1, the HTTP APIs are built directly on Sockets.  So, you'll discover that the tracing is more verbose.

**Comment by davidsh** [comment]
Since the question seems to be answer, closing this issue.

**Comment by TylerAP** [comment]
Any linux option?

**Comment by davidsh** [comment]
>Any linux/cross-platform option?

In general, the .NET EventSource traces are cross-platform.  There are several different ways to view them, either in code or external.  Unfortunately, we don't have current documentation for that.  But LTTng is used on Linux for that.

See: http://blogs.microsoft.co.il/sasha/2017/03/30/tracing-runtime-events-in-net-core-on-linux/
