### ISSUE TITLE
DataContractJsonSerializer.CanonicalizeObject() 

### ISSUE THREAD

**Issue by cyberphone** [dotnet/corefx#29212]
There is an alternative to https://tools.ietf.org/id/draft-erdtman-jose-cleartext-jws-00.html in preparation which in addition to ES6 compatible string and number generation (https://github.com/dotnet/corefx/issues/5647), also requires that property names are _sorted_ as described in: https://cyberphone.github.io/doc/security/draft-rundgren-json-canonicalization-scheme.html.

This is trivial to accomplish in **Json.NET** through an extra parameter to the serializer (https://github.com/cyberphone/json-canonicalization/blob/master/dotnet/newtonsoft/Program.cs#L32), but using the DataContractJsonSerializer I'm stuck.

One way to achieve this would be to add a specific method` CanonicalizeObject()` , that would be identical to `WriteObject()` except for property order.  Well, it would enforce ES6 compatible string and number generation as well.

**Comment by cyberphone** [comment]
Hi @huanwu @mconnew Sorting in itself doesn't really address any interesting problem.  Anyway, my work with Json.NET as well as with the .NET platform have progressed considerably so you may close this issue now.

https://github.com/cyberphone/json-canonicalization/tree/master/dotnet/es6numberserialization#es6-compatible-json-number-serialization-for-net

https://github.com/cyberphone/json-canonicalization/tree/master/dotnet/json.net.sign#clear-text-signature-sample-solution

It is alive! 😂

**Comment by StephenBonikowsky** [comment]
We now have a separate json serializer, namespace System.Text.Json
For more details...
https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/
https://www.nuget.org/packages/System.Text.Json
