### ISSUE TITLE
Wrong debug directory entry in some .NET Core 2.1 preview1 libraries

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#29223]
@KKatsnel commented on [Thu Mar 29 2018](https://github.com/dotnet/core/issues/1392)

Here two possible versions of the data format of a debug directory are described:
https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/PE-COFF.md 
However, there are two Debug Directory Entries in the "System.IO.FileSystem.dll" library of 4.1.1.0 version (it's from .NET Core 2.1 preview1):
- Major = 0x0100, Minor = 0x504d that corresponds to the Portable PDB format, and
- Major = 0x0100, Minor = 0, that doesn't correspond to any version.

As far as I understand the second entry is wrong, isn't it?

---

@Petermarcu commented on [Thu Mar 29 2018](https://github.com/dotnet/core/issues/1392#issuecomment-377456884)

@tmat

**Comment by tmat** [comment]
System.IO.FileSystem.dll with version:

`4.6.26404.05 @BuiltBy: dlab-DDVSOWINAGE078 @Branch: vsts-workflow-2768-g82d95f9a23 @SrcCode: https://github.com/dotnet/corefx/tree/82d95f9a23dad85b53ef4d0ef84e5cafac7f01cf"`

Has the following debug directory entries:

```
Debug Directory:
  CodeView stamp=0xD8B41B8D, version=(0x0100, 0x504D), size=284
    path='E:\A\_work\4\s\corefx\bin\obj\ref\System.IO.FileSystem\4.1.1.0\netcoreapp\System.IO.FileSystem.pdb', guid={a59889ea-ee56-4958-90fc-6f73c8825723}, age=1
  PdbChecksum stamp=0x00000000, version=(0x0001, 0x0000), size=39
```

I don't see any issues.
