### ISSUE TITLE
Referencing .NET Framework libraries from a .NET Core 2.0 project

### ISSUE THREAD

**Issue by CryptonZylog** [dotnet/corefx#29221]
Ok, I was under the impression that a project targeting .NET Core 2.0 features can reference .NET Framework (4.6.2) projects and/or libraries.

For example, I have a parent project (console app) that targets .NET Core 2.0 and can only target .NET Core 2.0 due to features introduced in it that aren't available in .NET Framework 4.6.2 (the latest framework we can currently support).

It seems this is not the case as I am getting the following exception. Is there a workaround to this problem? I don't really care about cross platform compatibility, but a single .exe **needs** to have features available both in .NET Core 2.0 (new X509Certificate2 extensions) and .NET Framework 4.6.2 (WMI/System.Management objects).

```
System.BadImageFormatException: 'Could not load file or assembly 'System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)'

```

**Comment by Clockwork-Muse** [comment]
For WMI specifically, see #26601

**Comment by pjanotti** [comment]
@CryptonZylog how are you building your project and referencing System.Management? Can you provide a small repro?

**Comment by pjanotti** [comment]
Thanks. The path to use System.Management from CoreFX is via the compatibility package.

Ok, I closing this issue.  Let us know if you find issues with the compatibility package.
