### ISSUE TITLE
Urgent: Ubuntu 18.04 has moved to curl 4 isntead of 3

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#29220]
@borgdylan commented on [Thu Apr 19 2018](https://github.com/dotnet/core/issues/1466)

Some tools such as cmake in Ubuntu 18.04 are making use of libcurl4 instead of libcurl3. These two versions may not be installed at the same time. This means that one cannot have cmake and .NET COre isntalled at the same time. Please make a repo for 18.04 targeting libcurl4.

**Comment by Petermarcu** [comment]
This looks related: https://github.com/dotnet/core-setup/issues/3875

Perhaps its just a package dependency issue? @rakeshsinghranchi @stephentoub

**Comment by stephentoub** [comment]
@borgdylan, can you share more details?  How is the problem manifesting? corefx already builds against libcurl4 and generally distros symlink libcurl3 to libcurl4.  Is the problem that on Ubuntu 18.04 libcurl is built against a different SSL backend?

**Comment by stephentoub** [comment]
Ah, I see my question crossed with Peter's comment and that it's a packaging issue.

**Comment by borgdylan** [comment]
The problem is that older packages from .NET Core use libcurl3 not libcurl4. APT is forcing all libcurl3 dependants to be uninstalled if libcurl4 is to be installed.

**Comment by borgdylan** [comment]
The metadata in the libcurl4 packages say that it conflicts and replaces libcurl3.

**Comment by borgdylan** [comment]
The issue is made worse with cmake now using libcurl4. One cannot build anoything using cmake which is many projects nowadays, with .NET Core installed. Also the stable repos for .NET Core are still targeting ubuntu 16.04. Packaging changes happen on each release.

**Comment by Petermarcu** [comment]
I'm going to resolve this issue here and point to https://github.com/dotnet/core-setup/issues/3875 to track it.
