### ISSUE TITLE
Remove workaround in package testing

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#29249]
See https://github.com/dotnet/corefx/pull/29241#issuecomment-383237638

We're walking the closure of packages that build on top of netcoreapp2.1.  Those build using live references but the current package testing infrastructure tests against an LKG framework package.  As a result when we bump reference versions every package will see a break until we get an updated LKG with the new reference assemblies.

Once we have a new Microsoft.NETCore.App we can remove this closure exception.

**Comment by kasper3** [comment]
https://github.com/dotnet/corefx/pull/29480 is also merged

**Comment by Petermarcu** [comment]
@ericstj can this be closed?

**Comment by ericstj** [comment]
Not yet, looks like @stephentoub merged the update but didn't remove these suppressions.  I'll submit a separate PR.
