### ISSUE TITLE
Clean SSL error queue: X509 related functions

### ISSUE THREAD

**Issue by pjanotti** [dotnet/corefx#29244]
This is a continuation of #25676 clean up, also related to #29188. Below is an assessment of the native functions from CryptoNative related to X509 (80 functions) and suggested actions. 

- [x] CryptoNative_CheckX509Hostname => Relatively large native, likely leaving errors on queue
- [x] CryptoNative_CheckX509IpAddress => Relatively large native, likely leaving errors on queue
- [X] CryptoNative_DecodeX509 - covered in push to clean up error queue
- [X] CryptoNative_DecodeX509BasicConstraints2Extension - Relatively large native, errors left on queue cleaned on managed side in case of error
- [ ] CryptoNative_DecodeX509Crl => single location, missing clean up at usage, check caller
- [ ] CryptoNative_DecodeX509Name => single location, missing clean up at usage, check caller
- [ ] CryptoNative_EncodeX509 => single location, assert checks no error but for safety error needs to be cleaned in OpenSslEncode src\Common\src\Interop\Unix\System.Security.Cryptography.Native\Interop.Encode.cs
- [ ] CryptoNative_EncodeX509SubjectPublicKeyInfo => single location, assert checks no error but for safety error needs to be cleaned in OpenSslEncode src\Common\src\Interop\Unix\System.Security.Cryptography.Native\Interop.Encode.cs
- [x] CryptoNative_GetX509CrlNextUpdate => single call, didn't find doc, we should check for null and clean up just in case
- [X] CryptoNative_GetX509DerSize - single call, error cleaned in OpenSslEncode
- [X] CryptoNative_GetX509EkuField - single call covered by throw Interop.Crypto.CreateOpenSslCryptographicException in case of failure
- [X] CryptoNative_GetX509EkuFieldCount - single call, return does not indicate error or not, assuming that it doesn't log errorif we pass valid argument
- [X] CryptoNative_GetX509EvpPublicKey - single call covered by CheckValidOpenSslHandle
- [x] CryptoNative_GetX509NameEntry => called via GetX509NameEntry_private in GetX509NameEntry, check if caller or SafeInteriorHandle.OpenInteriorHandle handle error
- [x] CryptoNative_GetX509NameEntryCount => single call,  we should check for negative and clean up just in case
- [x] CryptoNative_GetX509NameEntryData => called via GetX509NameEntryData_private in GetX509NameEntryData, check if caller or SafeInteriorHandle.OpenInteriorHandle handle error
- [x] CryptoNative_GetX509NameEntryOid => called via GetX509NameEntryOid_private in GetX509NameEntryOid, check if caller or SafeInteriorHandle.OpenInteriorHandle handle error
- [x] CryptoNative_GetX509NameInfo => single call not covered, needs to clean up error queue
- [X] CryptoNative_GetX509NameRawBytes - no actual call to lib
- [x] CryptoNative_GetX509NameStackField => called via GetX509NameStackField_private in GetX509NameStackField, check if caller or SafeInteriorHandle.OpenInteriorHandle handle error
- [x] CryptoNative_GetX509NameStackFieldCount => single call, didn't find doc, we should check for negative and clean up just in case
- [X] CryptoNative_GetX509NotAfter - no actual call to lib
- [X] CryptoNative_GetX509NotBefore - no actual call to lib
- [X] CryptoNative_GetX509PublicKeyAlgorithm - no actual call to lib
- [X] CryptoNative_GetX509PublicKeyBytes - no actual call to lib
- [x] CryptoNative_GetX509PublicKeyParameterBytes => two calls, need to check callers of KeyAlgorithmParameters property, and also relatively large native code
- [x] CryptoNative_GetX509RootStoreFile => called via GetX509RootStoreFile_private in GetX509RootStoreFile, needs error clean up in one location
- [x] CryptoNative_GetX509RootStorePath => same as above
- [X] CryptoNative_GetX509SignatureAlgorithm - no actual call to lib
- [x] CryptoNative_GetX509StackField => several calls, cleaned in single one, need to check callers before adding throw for them
- [X] CryptoNative_GetX509StackFieldCount - single call, didn't find doc, assuming that it doesn't log errorif we pass valid argument
- [X] CryptoNative_GetX509SubjectPublicKeyInfoDerSize - single call covered by OpenSslEncode
- [X] CryptoNative_GetX509Thumbprint - single call covered in GetDynamicBuffer
- [x] CryptoNative_GetX509Version => single call throws CryptographicException without cleaning the error queue (should we throw more detailed exception?)
- [x] CryptoNative_NewX509NameStack => DEADCODE
- [x] CryptoNative_NewX509Stack => two calls, call in ExportPfx needs to be double checked (it is covered if handle reaches PushHandle but need deeper check)
- [ ] CryptoNative_PemReadBioX509Crl => two locations, need to check from callers, likely need clean up
- [X] CryptoNative_PemReadX509FromBio - covered in push to clean up error queue
- [ ] CryptoNative_PemWriteBioX509Crl => single call, return code not checked, add clean up
- [x] CryptoNative_PushX509NameStackField => DEADCODE
- [X] CryptoNative_PushX509StackField - two calls, covered by CreateOpenSslCryptographicException()
- [X] CryptoNative_ReadX509AsDerFromBio - covered in push to clean up error queue
- [X] CryptoNative_RecursiveFreeX509NameStack - single call, void,  assuming that it doesn't log errorif we pass valid argument 
- [X] CryptoNative_RecursiveFreeX509Stack - single call, void,  assuming that it doesn't log errorif we pass valid argument 
- [X] CryptoNative_SetX509ChainVerifyTime - manager wrapper throw in case of failure
- [x] CryptoNative_X509CheckIssued => single call not covered, needs to clean up error queue
- [X] CryptoNative_X509CheckPurpose - single call covered by throw CreateOpenSslCryptographicException
- [X] CryptoNative_X509CrlDestroy - actually calls X509_CRL_free ensuring the argument is not null, single call, it is void, assuming that it doesn't log error if we pass valid argument
- [X] CryptoNative_X509Destroy - actually calls X509_free ensuring the argument is not null, single call, it is void, assuming that it doesn't log error if we pass valid argument
- [ ] CryptoNative_X509Duplicate => DEADCODE
- [ ] CryptoNative_X509ExtensionCreateByObj => single call not covered, caller FormatNative in C:\s\github\pjanotti\corefx\src\System.Security.Cryptography.Encoding\src\Internal\Cryptography\OpenSslAsnFormatter.cs
- [X] CryptoNative_X509ExtensionDestroy - actually calls X509_EXTENSION_free ensuring the argument is not null, single call, it is void, assuming that it doesn't log error if we pass valid argument
- [X] CryptoNative_X509ExtensionGetCritical - single call, return does not indicate error or not, assuming that it doesn't log errorif we pass valid argument
- [X] CryptoNative_X509ExtensionGetData - single call covered by CheckValidOpenSslHandle
- [X] CryptoNative_X509ExtensionGetOid - single call covered by CheckValidOpenSslHandle
- [X] CryptoNative_X509GetExt - single call covered by CheckValidOpenSslHandle
- [X] CryptoNative_X509GetExtCount - single call, return does not indicate error or not, assuming that it doesn't log errorif we pass valid argument
- [X] CryptoNative_X509GetIssuerName - single call covered by ChecckValidOpenSslHandle in LoadX500Name
- [x] CryptoNative_X509GetSerialNumber => called via X509GetSerialNumber_private in X509GetSerialNumber, check if caller or SafeInteriorHandle.OpenInteriorHandle handle error
- [X] CryptoNative_X509GetSubjectName - single call covered by ChecckValidOpenSslHandle in LoadX500Name
- [ ] CryptoNative_X509IssuerNameHash => single call returns hash, likely doesn't log errorif we pass valid argument, https://github.com/dotnet/corefx/issues/28724
- [X] CryptoNative_X509NameDestroy - actually calls X509_NAME_free ensuring the argument is not null, single call, it is void, assuming that it doesn't log error if we pass valid argument
- [X] CryptoNative_X509StoreAddCert - single call covered by throw Interop.Crypto.CreateOpenSslCryptographicException in case of failure
- [X] CryptoNative_X509StoreAddCrl - covered in push to clean up error queue
- [X] CryptoNative_X509StoreCreate - single call covered by CheckValidOpenSslHandle
- [X] CryptoNative_X509StoreCtxCreate - single call covered by CheckValidOpenSslHandle
- [X] CryptoNative_X509StoreCtxDestroy - actually calls X509_STORE_CTX_free ensuring the argument is not null, single call, it is void, assuming that it doesn't log error if we pass valid argument
- [x] CryptoNative_X509StoreCtxGetChain => single call not covered, although calling method throws CryptographicException on other points
- [x] CryptoNative_X509StoreCtxGetError => single call returns code, likely doesn't log errorif we pass valid argument
- [x] CryptoNative_X509StoreCtxGetErrorDepth => single call returns code, likely doesn't log errorif we pass valid argument
- [X] CryptoNative_X509StoreCtxGetSharedUntrusted - no actual call to lib
- [X] CryptoNative_X509StoreCtxGetTargetCert - no actual call to lib
- [X] CryptoNative_X509StoreCtxInit - single call covered by throw Interop.Crypto.CreateOpenSslCryptographicException in case of failure
- [X] CryptoNative_X509StoreCtxSetVerifyCallback- single call, it is void, assuming that it doesn't log error if we pass valid argument
- [X] CryptoNative_X509StoreDestoryactually - calls X509_STORE_free ensuring the argument is not null, single call, it is void, assuming that it doesn't log error if we pass valid argument
- [X] CryptoNative_X509StoreSetRevocationFlag - single call covered by throw Interop.Crypto.CreateOpenSslCryptographicException in case of failure
- [X] CryptoNative_X509UpRef - called in many places,  internally calls CRYPTO_add, assuming that it doesn't log error if we pass valid argument
- [ ] CryptoNative_X509V3ExtPrint => single call not covered, caller FormatNative in C:\s\github\pjanotti\corefx\src\System.Security.Cryptography.Encoding\src\Internal\Cryptography\OpenSslAsnFormatter.cs
- [ ] CryptoNative_X509VerifyCert => 2 calls one not covered in VerifyCertChain in C:\s\github\pjanotti\corefx\src\System.Net.Http\src\System\Net\Http\CurlHandler\CurlHandler.SslProvider.Linux.cs
- [X] CryptoNative_X509VerifyCertErrorString - single call, returns string for error code, likely doesn't log errorif we pass valid error code

**Comment by bartonjs** [comment]
Things that were pending that I checked off with no code change:

* CryptoNative_CheckX509Hostname
  * Doesn't interact with any functions which modify the error queue
* CryptoNative_CheckX509IpAddress
  * Doesn't interact with any functions which modify the error queue
* CryptoNative_GetX509CrlNextUpdate
  * Field reference, no errors.
* CryptoNative_GetX509NameEntry
  * STACK_OF function, no errors
* CryptoNative_GetX509NameEntryCount
  * STACK_OF function, no errors
* CryptoNative_GetX509NameEntryData
  * Field reference, no errors
* CryptoNative_GetX509NameEntryOid
  * Field reference, no errors
* CryptoNative_GetX509NameInfo
  * Doesn't interact with any functions which modify the error queue
* CryptoNative_GetX509NameStackField
  * STACK_OF function, no errors
* CryptoNative_GetX509NameStackFieldCount
  * STACK_OF function, no errors
* CryptoNative_GetX509PublicKeyParameterBytes
  * GetDynamicBuffer checks for errors during both calls.
* CryptoNative_GetX509RootStoreFile
  * OpenSSL functions just return \#define values, no errors.
* CryptoNative_GetX509RootStorePath
  * OpenSSL functions just return \#define values, no errors.
* CryptoNative_GetX509StackField
  * STACK_OF function, no errors
* CryptoNative_GetX509Version
  * Field reference, no errors
* CryptoNative_NewX509NameStack
  * STACK_OF function, no errors
* CryptoNative_NewX509Stack
  * STACK_OF function, no errors
* CryptoNative_PushX509NameStackField
  * STACK_OF function, no errors
* CryptoNative_X509CheckIssued
  * X509_check_issued doesn't interact with the error queue
* CryptoNative_X509GetSerialNumber
  * Field reference, no errors
* CryptoNative_X509StoreCtxGetChain
  * Field references, no errors
* CryptoNative_X509StoreCtxGetError
  * Field reference, no errors
* CryptoNative_X509StoreCtxGetErrorDepth
  * Field reference, no errors

And, in the other direction:

* CryptoNative_X509V3ExtPrint
  * Might contaminate error queue on success

**Comment by pjanotti** [comment]
Tracking X509 plus other changes in #29313
