### ISSUE TITLE
Add DecompressionMethods.All?

### ISSUE THREAD

**Issue by jnm2** [dotnet/corefx#29243]
The addition of `System.Net.DecompressionMethods.Brotli` was [recently approved](https://github.com/dotnet/corefx/issues/26995). I have been writing `DecompressionMethods.Deflate | DecompressionMethods.GZip` in my source automatically; since I don't want to exclude the possibility of Brotli, I'm going to be writing `DecompressionMethods.Deflate | DecompressionMethods.GZip | DecompressionMethods.Brotli`.

I am very interested in an `All` member, since that sums up exactly what I care about. 

```diff
namespace System.Net
{
    [Flags]
    public enum DecompressionMethods
    {
        None = 0,
        GZip = 1,
        Deflate = 2,
        Brotli = 4,
+       All = ~None
    }
}
```

Would you please review this possibility?

### Usage

The enum is get/set via property [HttpClientHandler.AutomaticDecompression](https://apisof.net/catalog/System.Net.Http.HttpClientHandler.AutomaticDecompression). Default is `None`. `All` value will ease up opt-in into any decompression.

Default value is `None` is set in [all handlers](https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=DefaultAutomaticDecompression&type=) via internal `HttpHandlerDefaults.DefaultAutomaticDecompression `:
https://github.com/dotnet/corefx/blob/9cde05ff84d118a9cc5629b85d4a319dd32172ae/src/Common/src/System/Net/Http/HttpHandlerDefaults.cs#L19

[EDIT] Added details by @karelz

**Comment by kasper3** [comment]
Does it mean the implementation will try all decompression methods on received data? Something else?

**Comment by jnm2** [comment]
@kasper3 No, the client sends Accept-Encoding and looks at the response's Content-Encoding.

**Comment by karelz** [comment]
Sounds reasonable to me. Marking as ready for review.
cc @dotnet/ncl (in case there are implications I missed)

**Comment by terrajobst** [comment]
Seems reasonable.

**Comment by karelz** [comment]
This should be simple to implement. Adding new 2.2-only API (into ref) will be the trickiest part.

**Comment by kasper3** [comment]
@karelz, isn't `Brotli = 4` also in the same (2.2-only) boat?

**Comment by karelz** [comment]
Yes it is, so it will be even simpler than I expected. Check PR #29729.

**Comment by Mpdreamz** [comment]
@karelz I'd like to take this one for the Hackathon.
