### ISSUE TITLE
Post 2.1 RTM: update packageindex to account for 2.1 and harvest all locked reference assemblies

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#29242]
/cc @weshaggard @joperezr

**Comment by joperezr** [comment]
I can take care of this once we ship.

**Comment by weshaggard** [comment]
https://github.com/dotnet/corefx/issues/29383 is related.

**Comment by joperezr** [comment]
Is the one you pointed out actually a dupe? they seem to be very similar...
