### ISSUE TITLE
Upgrade mirror to Run for multiple branches  (Release and Master branches)

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#29248]
We have noticed there are several commits missing in the coreclr release/2.1 branch that exists in corefx release/2.1 branch.

This means the mirror is not running on the release/2.1 branch and only runs on master.

This could lead to unexpected bugs in the product. For example, this PR just got opened for master, but corefx/2.1 and coreclr/2.1 are out of sync: https://github.com/dotnet/coreclr/pull/17709

cc @weshaggard, @RussKeldorph, @joshfree, @Anipik, @safern

**Comment by safern** [comment]
The mirror's code will need to be updated to be able to specify branches we want to mirror across repos and then the mirror will have to listen to all branches that it has in the settings file to update them if needed. Shouldn't be hard, but it is still a code change. Currently I don't have bandwidth to do it, but maybe @Anipik could do it.

**Comment by safern** [comment]
cc: @danmosemsft

**Comment by ahsonkhan** [comment]
@danmosemsft ran the mirror manually for the 2.1 branch: https://github.com/dotnet/corefx/pull/29256 / https://github.com/dotnet/coreclr/pull/17713

Changing to blocking-release rather than blocking-RC1.

**Comment by Petermarcu** [comment]
@ahsonkhan @Anipik whats the status here? We are running out of time in 2.1.

**Comment by Anipik** [comment]
@Petermarcu The changes are in testing phase. 
During my last conversation with @danmosemsft we were not sure if we want to start running the new mirror for 2.1

**Comment by Petermarcu** [comment]
Are we out of sync or are we fine for 2.1? @danmosemsft

**Comment by danmosemsft** [comment]
We should be manually syncing for 2.1 release. This is essentially only relevant to Span and Path. @anipik please manually diff and confirm they are in sync.

**Comment by Anipik** [comment]
@danmosemsft they are not in sync.
https://github.com/dotnet/coreclr/commit/df6249119586492a77a17a0218760c40bd1d4caf is missing from the corefx. Rest all is good

**Comment by danmosemsft** [comment]
Even though it's not built I suggest sending mail to shiproom @anipik with the usual template so we can get the ok to merge this as theres value in a consistent state. 
@anipik please check the diff each day from now until we ship or you have the mirror working.

**Comment by Petermarcu** [comment]
Can we close this one now? We did the manual merge?

**Comment by Anipik** [comment]
shouldnt we just move the milestone to the future as we are currently working to run the mirror for multiple branches  ?

**Comment by Petermarcu** [comment]
That would be fine too. We'd have to change the title as well then and remove the "blocking-release" tag. My goal is to get it off the radar of things blocking 2.1.

**Comment by ahsonkhan** [comment]
> please check the diff each day from now until we ship or you have the mirror working.

What about this? Or do we except no more changes now.

**Comment by Anipik** [comment]
>  What about this? Or do we except no more changes now.

I will be checking it regularly until the mirror is set up (Its in the pipeline)

**Comment by Anipik** [comment]
@danmosemsft the PR for this issue has been merged. Should we start using the new mirror ?
