### ISSUE TITLE
Coudn't build System.Memory for netfx TargetGroup

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/corefx#29250]
Next command `msbuild /t:Build /p:ConfigurationGroup=Debug /p:TargetGroup=netfx` return next errors in log:
```
ReportConfigurationErrorMessage:
  C:\Code\corefx\src\System.Runtime\ref\System.Runtime.csproj ConfigurationErrorMessage: Could not find a compatible configuration for BuildConfiguration 'netfx-Windows_NT-Debug-x64' from BuildConfigurations ';netcoreapp;uap;;'.  Considered netfx-Windows_NT;net461-Windows_NT;net46-Windows_NT;net451-Windows_NT;net45-Windows_NT;netstandard-Windows_NT;netstandard2.0-Windows_NT;netstandard1.6-Windows_NT;netstandard1.5-Windows_NT;netstandard1.4-Windows_NT;netstandard1.3-Windows_NT;netstandard1.2-Windows_NT;netstandard1.1-Windows_NT;netstandard1.0-Windows_NT;netfx;netfx-AnyOS;net461;net461-AnyOS;net46;net46-AnyOS;net451;net451-AnyOS;net45;net45-AnyOS;netstandard;netstandard-AnyOS;netstandard2.0;netstandard2.0-AnyOS;netstandard1.6;netstandard1.6-AnyOS;netstandard1.5;netstandard1.5-AnyOS;netstandard1.4;netstandard1.4-AnyOS;netstandard1.3;netstandard1.3-AnyOS;netstandard1.2;netstandard1.2-AnyOS;netstandard1.1;netstandard1.1-AnyOS;netstandard1.0;netstandard1.0-AnyOS.Could not find a value for TargetGroup from Configuration ''.
```

There is no error for `uap` and `netcoreapp` TargetGroup  only for `netfx`.

Also build from root is successful `build -framework=netfx`

**Comment by ahsonkhan** [comment]
I am not able to reproduce this issue. I ran `msbuild /t:Build /p:ConfigurationGroup=Debug /p:TargetGroup=netfx` from the `System.Memory\src` directory and the build succeeded as expected (similarly, ran tests from the test directory).

Where are you running the msbuild command from? If you run it from the root of the directory, that is when you will get such an error (which isn't really supported).

**Comment by ahsonkhan** [comment]
> I used `src\System.Memory` folder.

Run from the src or test directory: `corefx\src\System.Memory\src` or `corefx\src\System.Memory\tests`

**Comment by AlexRadch** [comment]
I always used `src\System.Memory` for usual TargetGroup not for `netfx`

**Comment by ahsonkhan** [comment]
It just happens to work, but the expected approach is to build from the specific src/test directory:
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md#building-individual-projects

> You can build the DLL for System.Diagnostics.DiagnosticSource.dll by going to the `src\System.Diagnostics.DiagnosticsSource\src` directory and typing `msbuild`

**Comment by AlexRadch** [comment]
Ok. But using `src\System.Memory` is more convenient because now to run test I should goto to `src\System.Memory\src` and compile library than goto to `src\System.Memory\tests` and run tests.

 For usual TargetGroup I just used `src\System.Memory` folder with one command ;)
