### ISSUE TITLE
Cannot use System.ServiceModel.Syndication and System.Service model in same net4 project

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#29253]
We're building a reference assembly instead of a facade.

/cc @mconnew

**Comment by StephenBonikowsky** [comment]
Adding @mconnew @huanwu who work on S.SM.Syndication

**Comment by ericstj** [comment]
We need to address this before release.  As it is now the types defined in this assembly don't unify with those in desktop and if I fix the package to make it unify you have test failures.  (see linked PR).

**Comment by Lxiamail** [comment]
Need to cherry picked to 2.1 branch for RTM.

**Comment by Lxiamail** [comment]
@StephenBonikowsky can you port this to corefx 2.1RTM branch?

**Comment by StephenBonikowsky** [comment]
Port PR: #29466

**Comment by StephenBonikowsky** [comment]
Approved and merged.
@ericstj Could you close this Issue for us?

**Comment by ericstj** [comment]
Yep.  Also, you should request access to CoreFx if this ServiceModel code is going to live here.
