### ISSUE TITLE
Build for netfx does not run tests if tests source files was not changed

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/corefx#29264]
To run `netfx` tests for `System.Memory` library I use next command `..\..\build . -framework:netfx` in `src\System.Memory ` folder.

If source files for tests are not changed than this command does not start tests. It only build library.
To run tests I should change some source file in `src\System.Memory\tests` folder.

If run `build` command without  `-framework:netfx` option it will run tests always. But I want run tests for `netfx` without touching tests source files.

Can it be fixed?

**Comment by ahsonkhan** [comment]
To build just System.Memory, run the following from the src directory:
> msbuild /t:rebuild /p:TargetGroup=netfx

Run the following from the System.Memory tests directory to run the tests:
> msbuild /t:rebuildandtest /p:TargetGroup=netfx

**Comment by stephentoub** [comment]
Or if you don't want to rebuild, use /p:ForceRunTests=true

**Comment by AlexRadch** [comment]
> To build just System.Memory, run the following from the src directory:
>     msbuild /t:rebuild /p:TargetGroup=netfx
> Run the following from the System.Memory tests directory to run the tests:
>     msbuild /t:rebuildandtest /p:TargetGroup=netfx

As I wrote here https://github.com/dotnet/corefx/issues/29250 I can not use `msbuild` for `netfx`

**Comment by AlexRadch** [comment]
> Or if you don't want to rebuild, use /p:ForceRunTests=true

`/p:ForceRunTests=true` is option for `msbuild` but I can not use this command for `netfx` see https://github.com/dotnet/corefx/issues/29250

Why `..\..\build .` run test but `..\..\build . -framework:netfx` doesn't?

How can I reopen this issue?

**Comment by stephentoub** [comment]
msbuild works fine for targeting netfx. If it doesn't for you, that's the issue to understand and address, and it sounds like #29250 covers that, so we don't also need this issue.

**Comment by AlexRadch** [comment]
> so we don't also need this issue.

Why `..\..\build .` run tests but `..\..\build . -framework:netfx` doesn't?
