### ISSUE TITLE
Add FileLogTraceListener, Log and Asp​Log classes to .Net Core

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/corefx#29274]
FileLogTraceListener class is available in .net framework in the Microsoft.VisualBasic.Logging namespace. It has some useful features that are not available in other TraceListeners, as descried here:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.logging.filelogtracelistener?view=netframework-4.7.2

This class is not available in .Net Core, so I suggest you add it and make it available to both VB.NET and C#.
And I suggest the same for Log Class
https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.logging.log?view=netframework-4.7.2
and Asp​Log Class:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.logging.asplog?view=netframework-4.7.2

**Comment by MohammadHamdyGhanem** [comment]
@karelz 
This is not a question. It is an API request or a proposal.
Thanks.

**Comment by karelz** [comment]
I don't think we plan to port those APIs over as they are. They are in weird/unrelated namespace (why Microsoft.VisualBasic) and the entire logging TraceListener technology was superseded with EventSource/EventListener.
The question is if we have similar functionality elsewhere. It would help to list the capabilities you are interested in.

**Comment by MohammadHamdyGhanem** [comment]
> I don't think we plan to port those APIs over as they are. They are in weird/unrelated namespace (why Microsoft.VisualBasic) 

Copy them to any name space you want. VB.NET has many unique tools of its own, and it makes things easier.

> the entire logging TraceListener technology was superseded with EventSource/EventListener.
As I understand, EventSource/EventListener deals with ETW. I think this is a complicated tracing system, that is suitable for long running server aps and services. Other tracing tools are still useful in simple apps.
You already included them in CoreFx. If this is for backward compatablity, you should also include VB.NET Logging system, and I suggest to make it available to other languages.

> The question is if we have similar functionality elsewhere. It would help to list the capabilities you are interested in.

I was writting a chapter on Tracing in my book. So, there is nothing similar to these VB.NET classes, unless everyone rebuild them. FileLogTraceListener is the only class that separates logs into several files as needed. This is a good work already done to waste, so I find it useful to include in CoreFx.

Thanks

**Comment by danmosemsft** [comment]
>  the entire logging TraceListener technology was superseded with EventSource/EventListener.

Is that correct @karelz ? It seems a very different thing, few people will replace Trace.Write debugging calls (and reading from a file) with firing ETW events (and using perfview).

I suggest changing this issue into an API proposal (using standard format) for additions to existing trace listener, presumably DefaultTraceListener. If the API is approved, implementation can be copied from the old VB one if necessary.

**Comment by danmosemsft** [comment]
This is tracked in https://github.com/dotnet/corefx/issues/31181

**Comment by danmosemsft** [comment]
This is tracked in https://github.com/dotnet/corefx/issues/31181
