### ISSUE TITLE
FileSecurity fails accessing file with path >= 260 characters

### ISSUE THREAD

**Issue by scovetta** [dotnet/corefx#29275]
Under .NET Core 2.1.104 (Windows 10 / 64-bit), [FileSecurity](https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem.AccessControl/src/System/Security/AccessControl/FileSecurity.cs#L606) fails to read permissions from file that have a path length exceeding 259 characters.

Stack trace snippet:
```
Parameter name: name
at System.Security.AccessControl.NativeObjectSecurity.CreateInternal(ResourceType resourceType, Boolean isContainer, String name, SafeHandle handle, AccessControlSections includeSections, Boolean createByName, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
at System.Security.AccessControl.FileSystemSecurity..ctor(Boolean isContainer, String name, AccessControlSections includeSections, Boolean isDirectory)
at System.Security.AccessControl.FileSecurity..ctor(String fileName, AccessControlSections includeSections)
```
[Sample code demostrating this](https://gist.github.com/scovetta/01a6bca7881d3772a2b7bcf71cecf6aa)

A workaround for this is to prefix the path with `\\?\`, as shown below:
```
// Fails
var fs = new FileSecurity(@"c:\temp\really-long-name.txt", AccessControlSections.All);
// Succeeds
var fs = new FileSecurity(@"\\?\c:\temp\really-long-name.txt", AccessControlSections.All);
```

It would be useful if the FileSecurity class (and probably others) could do this on the caller's behalf, or if that could cause breakage, then updating the FileSecurity [documentation](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.AccessControl/FileSecurity.xml) to describe this (or if there's a better workaround).

**Comment by stephentoub** [comment]
cc: @JeremyKuhne

**Comment by JeremyKuhne** [comment]
@scovetta, do you have any interest in fixing this? If not, I can put it up for grabs.  We should do this, and we have an established pattern:

https://github.com/dotnet/corefx/blob/master/src/Common/src/Interop/Windows/kernel32/Interop.GetFileAttributesEx.cs

**Comment by swngdnz** [comment]
This appears to require only a one-line fix to https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem.AccessControl/src/System/Security/AccessControl/FileSecurity.cs#L618

Change it to:

`string fullPath = PathInternal.EnsureExtendedPrefixIfNeeded( Path.GetFullPath(fileName) );
`

I don't have proper permissions to submit the PR (nor a build environment to test it, I'm afraid). I declare that my minor change is available for any use. I retain no rights. Please use it. :-)

**Comment by carlossanlop** [comment]
We made several modifications to files related to this bug, which is one of the reasons why I had to close the two PRs. I'm going to take a look at this soon again.
