### ISSUE TITLE
Dumpling documentation points to empty website

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#29270]
https://github.com/dotnet/corefx/blob/master/Documentation/debugging/crash-dumps.md has link to https://dumpling.azurewebsites.net/ . This is a empty website.

What is the up to date way to get dumpling crash dumps for corefx?

**Comment by danmosemsft** [comment]
@jkotas there should be a URL in the console output that you can pull. However I tried this on Friday and it did not work either.

**Comment by danmosemsft** [comment]
@DrewScoggins

**Comment by wtgodbe** [comment]
Closing this as we don't use dumpling anymore (CC @safern)
