### ISSUE TITLE
How to run System.Memory performance tests for netfx TargetGroup

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/corefx#29277]
I added performance test for Span.IndexOf with comparisonType parameter. See https://github.com/dotnet/corefx/pull/29263 PR.

I want to run them for netfx TargetGroup but next command `msbuild /t:BuildAndTest /p:Performance=true /p:ConfigurationGroup=Release /p:TargetOS=Windows_NT /p:TargetGroup=netfx` doesn't run performance tests for netfx TargetGroup.

I need run them for netfx TargetGroup because I need test portable span methods.

**Comment by AlexRadch** [comment]
@karelz  How to run performance tests for netfx

**Comment by karelz** [comment]
@ahsonkhan @KrzysztofCwalina @joshfree should be able to answer that.

**Comment by ahsonkhan** [comment]
I don't have a good way to run the performance tests for portable span.

The way I do it is, I build the System.Memory package, locally, and then reference it in my netcoreapp2.0 console application which either uses the Stopwatch (or xunit.performance/benchmarkdotnet) to measure the performance of the tests using portable span.

1) At the root of corefx: `build.cmd -allconfigurations -release`
2) Update NuGet.Config to include the corefx\bin\packages\Release directory
   - `<add key="Local" value="D:\GitHub\Fork\corefx\bin\packages\Release" />`
3) Reference the version of System.Memory package produced in the bin directory in your netcoreapp2.0 console application.
   - `dotnet new console`
   - Make sure you set the TargetFramework to netcoreapp2.0
   - Add a package reference to System.Memory, with the appropriate version `<PackageReference Include="System.Memory" Version="4.5.0-preview3-26413-02" />`
   - Add your performance tests to the application and use the Stopwatch (or add a package reference xunit.performance/BenchmarkDotNet).

See the following for more info on how to dogfood your local build:
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md#more-advanced-scenario---using-your-local-corefx-build

cc @danmosemsft, @jorive - do you guys know of a better way?

**Comment by jorive** [comment]
Adding @DrewScoggins @adamsitnik

**Comment by jorive** [comment]
@ahsonkhan we are currently working on decoupling benchmarks from their repos and how they are build/run, so they can be run against .NET Core and .NET Framework :)

**Comment by stephentoub** [comment]
This can be closed now, right @adamsitnik?

**Comment by adamsitnik** [comment]
@stephentoub yes, we can close it

@AlexRadch you need to clone the dotnet/performance repo and  follow the instructions from https://github.com/dotnet/performance/tree/master/src/benchmarks/micro#how-to-compare-different-runtimes
