### ISSUE TITLE
Optionally disabling AggregateException from showing other Exception messages in its own Message?

### ISSUE THREAD

**Issue by Metritutus** [dotnet/corefx#29301]
I've noticed that `AggregateException`'s `Message` property always shows the messages of the exceptions within it in parentheses after the `AggregateException`'s own `Message`.  Is there any chance that a change will be made to allow the customisation of this behaviour, such as setting whether to display the `Message` of the `AggregateException` only without the messages of its `InnerExceptions`?

I've read that this was changed a while back to make `AggregateException` messages more descriptive, but sometimes I want to have the `Message` of an `AggregateException` remain as I entered it.

**Comment by karelz** [comment]
It seems it is different behavior compared to .NET Framework. However, it doesn't feel like a bad behavior to me. It was actually intentional improvement - see #5364.

Why do you need just the `AggregateException` message without the inner exception? What is your use case?

**Comment by Metritutus** [comment]
@karelz I'm aware of that case.  I probably should have referenced it directly in my original post, but that was the case I read when I said "I've read that this was changed a while back to make `AggregateException` messages more descriptive."

As for the use-case, I'm logging all exceptions and inner exceptions, and I don't want to include the messages of the `InnerExceptions` in the log record message for the top-level `AggregateException` as they're specifically stored in their own log records.

**Comment by karelz** [comment]
Are the `AggregateException` messages useful at all without InnerExceptions? Typically the message just says "One or more errors occurred". Does it make sense to log such message without further details at all?
Or do you provide more useful messages in your code when you create & throw `AggregateException`?
(Just trying to understand your scenario and if there are alternative solutions that could satisfy your needs)

Are any of these options viable? (If not, why?)
* Do not log `AggregateException.Message` at all, just log exception name `AggregateException`.
* Create your own exception type (e.g. inherit from `AggregateException`) and override `Message`.

**Comment by karelz** [comment]
If your scenario is about exceptions originating from your code, I think inheritting is the best option.
We should optimize primarily for usability of `AggregateException` exceptions originating in BCL and libraries - in such cases, the inner messages are fairly important and it is a painpoint to NOT have them (which is the case in .NET Framework).

Adding new API or switch just to be able to get to the "bare" Message seems like overkill to me. It adds complexity, makes API usage harder (devs have to decide which one to use).

If there is clear scenario where it makes sense, I would like to hear about it.
I would also like to see if there are more people asking for it. IMO either we should close the issue now and wait for more people to bring it up / comment on the closed issue. Or we can keep it opened for feedback and if none comes in a month or two, we should close it then. Thoughts?

**Comment by joperezr** [comment]
I agree with @karelz on this one. Seems like your scenario is a very specific one and there is a trivial way to fix it (inheriting). Given that, I will go ahead and close the issue for now, but as @karelz said, feel free to reopen in case you come up with different scenarios where inheriting wouldn't be an option and changing behavior or adding a new API would make more sense.
