### ISSUE TITLE
View() rendering is slow [QUESTION]

### ISSUE THREAD

**Issue by p2atran** [dotnet/corefx#29310]
I migrated my ASP.NET Core 1.1 project over to 2.0 and everything seems to work okay. However, I noticed that where `return View()` is called in the server, my webApp loads extremely slow. This wasn't the case in my 1.1 project.

I'm wondering if this has to do with my migration or if it is a known issue.

**Comment by ViktorHofer** [comment]
Wrong repository. Please post your question in the asp.net one: https://github.com/aspnet/Mvc
