### ISSUE TITLE
Keep SSL error queue clean

### ISSUE THREAD

**Issue by pjanotti** [dotnet/corefx#29313]
Closing #29244 that covered only X509 and tracking all required changes in this issue. The APIs listed below were selected after a scrub of the CryptoNative_* APIs by me and @bartonjs.

[EDIT 1: Removing deadcode ones, will address later]

/cc @karelz 

 - [x] CryptoNative_Asn1OctetStringNew => single call, needs ERR_clear_error
 - [ ] CryptoNative_Asn1OctetStringSet => single call, needs ERR_clear_error
 - [ ] CryptoNative_BigNumFromBinary => single call, missing clean up check calltree but likely clear on call site Cleanup (only reports OOM)
 - [ ] CryptoNative_BioNewFile => handful of calls, need to check call tree for AddCachedCrl, DownloadAndAddCrl, and LoadMachineStores
 - [ ] CryptoNative_BioRead => all call sites protected but some taking only last error (perhaps we should ensure queue is clear)
 - [ ] CryptoNative_BioSeek => ops, I missed two locations of this one in previous change
 - [ ] CryptoNative_BioTell => debug assert but no clean up in case of error
 - [ ] CryptoNative_BioWrite => Some calls not fully protected, other only last error
 - [ ] CryptoNative_CreateMemoryBio => some calls not cleaned, need to check call tree Cleanup (only reports OOM)
 - [ ] CryptoNative_DecodeAsn1TypeBytes => single call, needs ERR_clear_error
 - [ ] CryptoNative_DecodeX509Crl => single location, missing clean up at usage, check caller
 - [ ] CryptoNative_DecodeX509Name => single location, missing clean up at usage, check caller
 - [ ] CryptoNative_DsaKeyCreateByExplicitParameters => error on managed side is handled, but potential errors in SetDsaParameter on native are not (Needs native cleanup)
 - [ ] CryptoNative_DsaVerify => single call not protected on the caller, need to check calltree (probably only theoretical)
 - [ ] CryptoNative_EcDsaSize => two locations need to check for 0 return and throw in such cases Cleanup (only reports OOM)
 - [ ] CryptoNative_EcDsaVerify => single call, needs clear error, double-check call tree but seems simple (probably only theoretical)
 - [ ] CryptoNative_EcKeyCreateByExplicitParameters => 3 calls, relatively large native code, seems covered on managed side need to check if native can return success but leave errors on queue. #if 
HAVE_OPENSSL_EC2M check seems wrong (if char2 was requested and no char2 is present it passes to GFp and hopes that fails).  No check that G, gxBn, gyBn, orderBn, cofactorBn didn't fail (which might produce an error and continue-with-bad-data) 
(Needs native cleanup)
 - [ ] CryptoNative_EcKeyCreateByOid => 2 calls (plus a handful in tests), needs error clean up
 - [ ] CryptoNative_EncodeAsn1Integer => single location, assert checks no error but for safety error needs to be cleaned in OpenSslEncode 
src\Common\src\Interop\Unix\System.Security.Cryptography.Native\Interop.Encode.cs (probably only theoretical)
 - [ ] CryptoNative_EncodePkcs12 => single call, 2nd parameter of OpenSslEncode, not covered (probably only theoretical)
 - [ ] CryptoNative_EncodePkcs7 => single call, 2nd parameter of OpenSslEncode, not covered (probably only theoretical)
 - [ ] CryptoNative_EncodeX509 => single location, assert checks no error but for safety error needs to be cleaned in OpenSslEncode 
src\Common\src\Interop\Unix\System.Security.Cryptography.Native\Interop.Encode.cs (probably only theoretical)
 - [ ] CryptoNative_EncodeX509SubjectPublicKeyInfo => single location, assert checks no error but for safety error needs to be cleaned in OpenSslEncode 
src\Common\src\Interop\Unix\System.Security.Cryptography.Native\Interop.Encode.cs (probably only theoretical)
 - [ ] CryptoNative_GetDsaParameters => doesn't seem to touch ERR_, single call, throws exception, should clean up the queue
 - [ ] CryptoNative_GetObjectDefinitionByName => calls other natives, error clean-up can be made on native side
 - [ ] CryptoNative_GetRsaParameters => single call, throws CryptographicException, needs error cleanup
 - [ ] CryptoNative_GetSslConnectionInfo => single call, will be covered if CreateSslException cleans up the error queue
 - [ ] CryptoNative_LookupFriendlyNameByOid => single call, protected on managed but logic on native indicates that it may leave errors on the queue
 - [ ] CryptoNative_ObjSn2Nid => single call, there is CryptographicException but needs error clean up
 - [ ] CryptoNative_ObjTxt2Obj => single call, being covered by same change to cover Asn1OctetStringNew (prototype of tactical change)
 - [ ] CryptoNative_PemReadBioX509Crl => two locations, need to check from callers, likely need clean up
 - [ ] CryptoNative_PemWriteBioX509Crl => single call, return code not checked, add clean up
 - [ ] CryptoNative_RsaVerify => single call, in VerifyHash seems to need to clear error before return
 - [ ] CryptoNative_SetEncryptionPolicy => single call, missing clean up
 - [ ] CryptoNative_SetProtocolOptions => 2 calls, doesn't check return but it seems function doesn't log error, need to double check
 - [ ] CryptoNative_SetRsaParameters => single call, it seems to only set fields, likely doesn't log error, need to double check
 - [ ] CryptoNative_SslAddExtraChainCert => single call, not cleared, per docs SSL_CTX_add_extra_chain_cert can leave error on queue
 - [ ] CryptoNative_SslCtxCheckPrivateKey => single call, will be protected by fixing CreateSslException
 - [ ] CryptoNative_SslCtxCreate => single call, will be protected by fixing CreateSslException
 - [ ] CryptoNative_SslCtxSetAlpnProtos => single call, will be protected by fixing CreateSslException
 - [ ] CryptoNative_SslCtxUseCertificate => single call, will be protected by fixing CreateSslException,  but likely doesn't set errors anyway
 - [ ] CryptoNative_SslCtxUsePrivateKey => single call, will be protected by fixing CreateSslException
 - [ ] CryptoNative_SslSessionReused => single call, call log error per docs, may need specific clean up
 - [ ] CryptoNative_SslSetTlsExtHostName => single call, docs not clear, return value ignored, for safety we should clean up error queue
 - [ ] CryptoNative_X509ExtensionCreateByObj => single call not covered, caller FormatNative in src\System.Security.Cryptography.Encoding\src\Internal\Cryptography\OpenSslAsnFormatter.cs
 - [ ] CryptoNative_X509IssuerNameHash => single call returns hash, likely doesn't log errorif we pass valid argument, https://github.com/dotnet/corefx/issues/28724
 - [ ] CryptoNative_X509V3ExtPrint => single call not covered, caller FormatNative in src\System.Security.Cryptography.Encoding\src\Internal\Cryptography\OpenSslAsnFormatter.cs
 - [ ] CryptoNative_X509VerifyCert => 2 calls one not covered in VerifyCertChain in src\System.Net.Http\src\System\Net\Http\CurlHandler\CurlHandler.SslProvider.Linux.cs

**Comment by bartonjs** [comment]
I'd take the dead code ones out of the list.  Since no one is calling them they clearly aren't polluting the error queue.  Deleting them in master is fine, but they'd be noise in a backport.

**Comment by pjanotti** [comment]
Fixed via https://github.com/dotnet/corefx/commit/1cb15dfc8bcf0673443f3431dbdceb1b008dab87
