### ISSUE TITLE
Enable EnvelopedCms to work with an external private key

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#29327]
There are two scenarios that are not currently possible with the EnvelopedCms class.

1) Decrypting the contents of an EnvelopedCms with an unattached/unattachable key (a la RSAKeyVault).
2) Being able to prove which certificate+key were used for the decryption operation, because the existing members all dive into the CurrentUser\My certificate store looking for other candidate certs+keys.  (https://stackoverflow.com/questions/49815448/can-envelopedcms-be-used-to-identify-the-encryption-certificate)

The strawman suggestion is a new Decrypt overload which does not initiate a store search, and happens to allow specifying a private key.

```diff
public partial class EnvelopedCms
{
+    public void Decrypt(RecipientInfo recipientInfo, AsymmetricAlgorithm privateKey) => throw null;
}

public partial class SubjectIdentifier
{
+    public bool MatchesCertificate(System.Security.Cryptography.X509Certificates.X509Certificate2 certificate) { throw null; }
}

```

Maybe it also makes sense for the RecipientInfo overload.

Verifying the private key really belongs to the public key is a little trickier.  Maybe it's not important for Decrypt, since the certificate finds the matching recipient key info and the private key turns that back into the symmetric key... it either works or it doesn't.

Maybe this would be `TryDecrypt`, and returns false if the cert matches no recipients?

EDIT by @krwq: adding IsMatch, replacing cert with recipient in API proposal. Updated to MatchesCertificate

**Comment by morganbr** [comment]
How should the user know which cert/key to use?

**Comment by bartonjs** [comment]
One supposes that they would know what certificates they have disseminated.  In the case of the StackOverflow user they wanted to confirm that the sender was using the current cert/key instead of the previous, so they knew they should only have two plausible candidates.

Then, it seems like the answer is to just iterate the possibilities.

**Comment by krwq** [comment]
Would it make sense to add `RecipientInfo..ctor(X509Certificate2, AsymmetricAlgorithm)` and `RecipientInfo.PrivateKey` instead of `Decrypt` overload? (That would be in-line with what we did with `CmsSigner`).

**Comment by bartonjs** [comment]
It'd be sort of weird, in that the RecipientInfo (like SignerInfo) is a description of what's already in the document.  But maybe I could be convinced with some sample code.

**Comment by krwq** [comment]
@morganbr @bartonjs added RecipientInfo.IsMatch to the proposal so that user can check if their certificate matches any of the recipients. We might also want to consider:

```csharp
public void Decrypt(RecipientInfo recipient, AsymmetricAlgorithm privateKey) => throw null;
```

but I'm currently not convinced it is that useful from user perspective.

**Comment by bartonjs** [comment]
@krwq Thinking about it more, I think I'd put `IsMatch` on `SubjectIdentifier` so that it can be used for SignerInfo as well (not necessarily a scenario, but since SubjectIdentifier is what describes the match criteria it seems to make more sense).

Which I think means there's

```C#
public partial class EnvelopedCms
{
    public void Decrypt(RecipientInfo recipient, AsymmetricAlgorithm privateKey) => throw null;
    public void Decrypt(X509Certificate2 certificate, AsymmetricAlgorithm privateKey) => throw null;
}
public partial class SubjectIdentifier
{
    public bool IsMatch(X509Certificate2 certificate) => throw null;
}
```

Seeing some of the implementation over your shoulder I'm not sure if `Decrypt(X509Certificate2 certificate, AsymmetricAlgorithm privateKey)` is right, maybe it should be `TryDecrypt`, which returns false on no match, true on success, and throws on a crypto failure.

Though, I guess, with IsMatch and Decrypt(RecipientInfo, AsymmetricAlgorithm) one can write TryDecrypt on their own...

Maybe we don't need the new Decrypt which takes a single cert at all, given the other two new methods?

**Comment by krwq** [comment]
@bartonjs SubjectIdentifier.IsMatch could work but then it would complicate a logic when using `SubjectIdentifierType.IssuerAndSerialNumber` which suggest we would have to have both `RecipientInfo.IsMatch and SubjectIdentifier`.

Decrypt vs TryDecrypt - I'd vote for Decrypt and only leave overload with RecipientInfo.

**Comment by bartonjs** [comment]
> SubjectIdentifier.IsMatch could work but then it would complicate a logic when using SubjectIdentifierType.IssuerAndSerialNumber

How so?  It looks like we use the same managed implementation for both Windows and Unix, and it just uses the `SubjectIdentifier` value.  But maybe I'm missing something.

**Comment by krwq** [comment]
@bartonjs ahh you're right I've read SubjectKeyIdentifier but that's actually not even a .NET type

**Comment by terrajobst** [comment]
Looks good, after minor name change:

```csharp
public partial class EnvelopedCms
{
     public void Decrypt(RecipientInfo recipientInfo, AsymmetricAlgorithm privateKey);
}

public partial class SubjectIdentifier
{
     public bool MatchesCertificate(X509Certificate2 certificate);
}
```

**Comment by bartonjs** [comment]
Didn't make it for 2.2, already done for 3.0.
