### ISSUE TITLE
Remove hashtable & friends compiled files from System.Runtime.Extensions

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#29322]
This commit needs to be reverted when the new uapaot build (that contains the hashtable changes) is ingested: https://github.com/dotnet/corefx/commit/2e34bf9d93e23c2fdf978e457543b95906226721.

cc @jkotas

**Comment by jkotas** [comment]
Also delete workaround from https://github.com/dotnet/corefx/blob/master/pkg/test/frameworkSettings/netcoreapp2.2/settings.targets

**Comment by joperezr** [comment]
Given that this seems to be UAP I'll move the milestone to be UWP vNext.
