### ISSUE TITLE
Port System.ComponentModel.Composition.Registration (MEF1) to .NET Core

### ISSUE THREAD

**Issue by mfe-** [dotnet/corefx#29329]
Greetings,

regarding [Port System.ComponentModel.Composition (MEF1) to .NET Core](https://github.com/dotnet/corefx/issues/11857) the following is still missing:

- `System.ComponentModel.Composition.Registration.RegistrationBuilder`
- `System.ComponentModel.Composition.Registration.PartBuilder`
- `System.ComponentModel.Composition.Registration.PartBuilder<>`

See also https://github.com/dotnet/corefx/issues/11857#issuecomment-382342975

edit by @ViktorHofer: fixed link.

**Comment by ViktorHofer** [comment]
cc @maryamariyan @danmosemsft

**Comment by ViktorHofer** [comment]
RegistrationBuilder requires CustomReflectionContext which is currently just stubbed out and not implemented: https://github.com/dotnet/corefx/issues/5844

**Comment by kasper3** [comment]
missing `port-to-core` tag

**Comment by gkonterman** [comment]
@karelz @terrajobst @ViktorHofer I see this has the milestone `future` but can you please give a very raw estimation when it will be implemented/released? Actually, I need to make a business decision about the lack of this API. We really want to move to .net core/.net standard but this API is pretty critical for us.

I assume it will be part of the [Compatibility pack](https://blogs.msdn.microsoft.com/dotnet/2017/11/16/announcing-the-windows-compatibility-pack-for-net-core/)?

**Comment by karelz** [comment]
We do not have specific plans to port these APIs yet. That's why it is in Future milestone.
Please upvote the top issue.

Please provide more details about your scenario - why you need these APIs. Are there any workarounds you could consider?

**Comment by danmosemsft** [comment]
@gkonterman yes, MEF1 is already available in the compatibility pack - aside from the types listed above. It's marked preview, but is good to use now. We expect to mark it stable soon. 

If you need the specific types in this issue, the linked PR's will provide them. That won't be in 2.1 but will be in the compat pack daily builds.

**Comment by karelz** [comment]
Ah, I missed the pending PR - setting milestone to 2.2.

**Comment by ViktorHofer** [comment]
The PR for it should be merged pretty soon but unfortunately we can't push a package update with the missing functionality as one of its dependent packages (System.Reflection.Context) relies on an internal change (exposure of TypeInfo ctor) of the framework which means we have to wait till .NET Core 3 and .NET Standard vNext (as we still want to be able to target .NET Standard here).
