### ISSUE TITLE
CurrentCultureIgnoreCase comparison giving different results on Linux and Windows due to whitespace character difference

### ISSUE THREAD

**Issue by m4raza** [dotnet/corefx#29330]
Hello,
equality with CurrentCultureIgnoreCase in the en-US culture is ignoring the difference between the whitespace character (32) and the non-breaking space (160) on linux/mac, but not on windows.  The test:

```c#
var s1chars = new int[] { 89, 97, 110, 32, 71, 111, 109, 101, 115 };
var s2chars = new int[] { 89, 97, 110, 160, 71, 111, 109, 101, 115 };  // using non-breaking space instead of space
string s1 = new string(s1chars.Select(i => (char) i).ToArray());
string s2 = new string(s2chars.Select(i => (char)i).ToArray());
bool currentCultureIgnoreCaseEquality = string.Equals(s1, s2, StringComparison.CurrentCultureIgnoreCase);
bool equality = string.Equals(s1, s2);
bool ordinalIgnoreCaseEquality = string.Equals(s1, s2, StringComparison.OrdinalIgnoreCase);
```

``currentCultureIgnoreCaseEquality``  is false on windows but true on linux. The other two are false on both windows and linux. The culture has been confirmed to be "en-US" on both as shown by ``CultureInfo.CurrentCulture.Name``

[EDIT] Add C# syntax highlighting by @karelz

**Comment by kasper3** [comment]
Can't reproduce on Linux with .NET Core 2.0 and 2.1

```c#
using System;
using System.Globalization;
using System.Linq;

class Program
{
  static void Main(string[] args)
  {
    // explicitly force the culture to be extra sure
    CultureInfo.CurrentCulture = CultureInfo.GetCultureInfo("en-US");

    var s1chars = new int[] { 89, 97, 110, 32, 71, 111, 109, 101, 115 };
    var s2chars = new int[] { 89, 97, 110, 160, 71, 111, 109, 101, 115 };  // using non-breaking space instead of space
    string s1 = new string(s1chars.Select(i => (char) i).ToArray());
    string s2 = new string(s2chars.Select(i => (char)i).ToArray());
    bool currentCultureIgnoreCaseEquality = string.Equals(s1, s2, StringComparison.CurrentCultureIgnoreCase);
    bool equality = string.Equals(s1, s2);
    bool ordinalIgnoreCaseEquality = string.Equals(s1, s2, StringComparison.OrdinalIgnoreCase);
    Console.WriteLine("culture: {0}, equality: {1}, ordinalIgnoreCaseEquality: {2}",
        CultureInfo.CurrentCulture.Name,
        equality,
        ordinalIgnoreCaseEquality);
  }
}
```

On Windows 10 with .net core 2.0, Debian with 2.0 and Alpine Linux with 2.1, I get:

`culture: en-US, equality: False, ordinalIgnoreCaseEquality: False`

If your current culture is set to en-US or is empty (clean `LC_ALL` environment variable), then the result should be consistent. Are you sure that's the case in your environment?

**Comment by m4raza** [comment]
I don’t see currentCultureIgnoreCaseEquality printed in your output. This is the one that is appearing true on Linux for me and false on windows. The other two equalities are false everywhere. Can you check this?

**Comment by tarekgh** [comment]
The framework depends on the underlying OS for performing the string comparisons. on Linux and Mac we use the ICU library for that. so, in general, you can expect a different behavior between OS's and even between OS's versions.

**Comment by kasper3** [comment]
sorry I missed it,

```c#
    Console.WriteLine("culture: {0}, currentCultureIgnoreCaseEquality: {1}, equality: {2}, ordinalIgnoreCaseEquality: {3}",
        CultureInfo.CurrentCulture.Name,
        currentCultureIgnoreCaseEquality,
        equality,
        ordinalIgnoreCaseEquality);
```

gives
`culture: en-US, currentCultureIgnoreCaseEquality: False, equality: False, ordinalIgnoreCaseEquality: False`
on windows and
`culture: en-US, currentCultureIgnoreCaseEquality: True, equality: False, ordinalIgnoreCaseEquality: False`
on Linux. Tried on both OS with .NET Core 2.0 and 2.1.

@tarekgh, could that be the option we are using in CoreCLR to configure ICU is buggy, ignoring the type of whitespace in comparison (http://icu-project.org/apiref/icu4c-latest/uchar_8h.html)?

**Comment by krwq** [comment]
@kasper3 any specific option in mind? If you think this is fixable could your propose a change and a test case?

**Comment by tarekgh** [comment]
Could you try calling

```C#
    public static int Compare (string strA, string strB, System.Globalization.CultureInfo culture, System.Globalization.CompareOptions options);
```

and passing the CompareOptions values IgnoreCase | IgnoreNonSpace | IgnoreSymbols? 

I'll it later as I don't have the Linux machine handy now.
