### ISSUE TITLE
Allow setting IP protection level on Socket - P2P is not possible without it

### ISSUE THREAD

**Issue by markmnl** [dotnet/corefx#2934]
It is not possible for peers to establish a connection with eachother behind NAT(s) using Windows sockets without setting the IP socket option IP_PROTECTION_LEVEL. Currently there is no way to do this on a `DatagramSocket` or .NET Core `System.Net.Socket.Socket`, thus there is _no way make Peer 2 Peer Windows Store Apps_.

The issue on [Microsoft Connect](https://connect.microsoft.com/VisualStudio/feedback/details/1431526/nat-traversal-udp-hole-punching-not-possible-in-windows-store-apps-even-with-internet-client-server-capability).

In .NET Framework one used [`System.Net.Sockets.IPProtectionLevel`](http://referencesource.microsoft.com/#System/net/System/Net/Sockets/Socket.cs,5eb8a772f197999a).

We need to add this facility `Windows.Networking.Sockets.DatagramSocket` and/or `System.Net.Sockets.Socket`

**Comment by davidsh** [comment]
@CIPop @SidharthNabar @pgavlin

**Comment by markmnl** [comment]
I read now IP_PROTECTION_LEVEL is only suppose to be an IPv6 setting, which is interesting because even using IPv4 punch through does not work until you set it (even if you setup firewall rules manually) it is as if unsolicited datagrams are dropped indiscriminately without setting it.

In any case cannot get UDP punch through to work in Window Store Apps even with "Internet (Client & Server)" capability.

**Comment by SidharthNabar** [comment]
@markmnl - See my response to #2936 - the larger API surface that I was referring to is also intended to contain System.Net.Sockets.IPProtectionLevel - @CIPop can confirm.

**Comment by CIPop** [comment]
The functionality will be available via `SetSocketOption()` but we will be most likely removing the duplicate `SetIPProtectionLevel()` API.

/cc: @pgavlin

**Comment by markmnl** [comment]
Cool, looking forward, then get our game jamming on UWP.

**Comment by SidharthNabar** [comment]
Should be addressed by #896

**Comment by SidharthNabar** [comment]
New surface area for Sockets contract is tracked by PR #3655 - please take a look.

**Comment by CIPop** [comment]
This enhancement was taken into consideration and will be included in the next version of the Sockets contract as a `SetSocketOption()` parameter. Please add your comments to #3655.
