### ISSUE TITLE
ASN1 corrupted data when using EnvelopedCms to decrypt on Debian Stretch

### ISSUE THREAD

**Issue by samdearden** [dotnet/corefx#29345]
I am using EnvelopedCms in the 2.1 preview 2 to decrypt a file that was encrypted using BouncyCastle. 

Using EnvelopedCms to decode & decrypt the file under Windows works without error.

Running the same code under Debian stretch (microsoft/dotnet:2.1.300-preview2-sdk-stretch docker image) on the call to EnvelopedCms.Decode I get the following error:

System.Security.Cryptography.CryptographicException: Unable to set field EncryptedContentInfo on type System.Security.Cryptography.Pkcs.Asn1.EnvelopedDataAsn. ---> System.Security.Cryptography.CryptographicException: Unable to set field EncryptedContent on type System.Security.Cryptography.Pkcs.Asn1.EncryptedContentInfoAsn. ---> System.Security.Cryptography.CryptographicException: ASN1 corrupted data.

I have attached the encrypted data and the full stack trace.

[encrypted.zip](https://github.com/dotnet/corefx/files/1951859/encrypted.zip)
[stack trace.txt](https://github.com/dotnet/corefx/files/1951860/stack.trace.txt)

**Comment by karelz** [comment]
@bartonjs is that new code in 2.1?

**Comment by bartonjs** [comment]
Looks like a deserializer problem reading implicitly tagged indefinite length octet strings (missed passing `expectedTag`).  Easy fix, I'll have a PR up in a bit.

**Comment by bartonjs** [comment]
```
   at System.Security.Cryptography.Asn1.AsnReader.TryCopyOctetStringBytes(Asn1Tag expectedTag, Span`1 destination, Int32& bytesWritten)
   at System.Security.Cryptography.Asn1.AsnSerializer.<>c__DisplayClass21_0.<GetSimpleDeserializer>b__6(AsnReader reader)
```

This is a misleading callstack, since it misses the inlined call to the overload that didn't take `expectedTag` :).

**Comment by bartonjs** [comment]
@samdearden Do you mind if I use your file for a compat test going forward?

**Comment by samdearden** [comment]
@bartonjs Go ahead, its just a test file.

**Comment by bartonjs** [comment]
This is fixed in master, and the fixed has merged into the release branch for the post-RC1 build.
