### ISSUE TITLE
Unquoted `reference` argument in Microsoft.XmlSerializer.Generator.targets breaks builds

### ISSUE THREAD

**Issue by pkanavos** [dotnet/corefx#29340]
The `--reference` parameter in the Microsoft.XmlSerializer.Generator.targets file is unquoted, breaking builds that use the tool :

https://github.com/dotnet/corefx/blob/a2c789559aad27409e55e31cef4c4b3092d5a472/src/Microsoft.XmlSerializer.Generator/pkg/build/Microsoft.XmlSerializer.Generator.targets#L15

SDK assemblies are stored in `Program Files` which makes the list of assemblies appear as separate arguments.
This results in invalid argument errors when building projects that use the tool eg : 

    EXEC : warning : Ignoring invalid command line argument: 'Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.1.0-preview2-26406-04\ref\netcoreapp2.1\System.Security.Cryptography.Encoding.dll;C:\Program'..

This can be fixed by double-quoting the `@(Reference)` argument : 

    <Exec Command="dotnet Microsoft.XmlSerializer.Generator $(IntermediateOutputPath)$(AssemblyName)$(TargetExt) --force --quiet --reference &quot;@(Reference)&quot;" ContinueOnError="true"/>

**Comment by karelz** [comment]
@Lxiamail you moved it to 2.1 milestone, but the PR went only into 2.2. Updating milestone back. If it was ported to 2.1, please link the porting PR and adjust milestone.

**Comment by karelz** [comment]
Ah, it was ported in PR #29494 into release/2.1 branch
BTW: @huanwu using PR/issue numbers in titles is not telling much about what the PR/issue truly tracks :( - I would recommend to use copy of original title with [release/2.1] prefix or something like that. Thanks!

**Comment by karelz** [comment]
Also, for future I would recommend to reopen bugs after checkin into master to track the port. Now we have 2 issues both (this one and #29494) tracking the same fix in release/2.1. We usually use 1 issue with 2 PRs (master and release/2.1).
