### ISSUE TITLE
DatagramSocket operations are not asynchronous but only exposed as async 

### ISSUE THREAD

**Issue by markmnl** [dotnet/corefx#2935]
To send data on a [`DatagramSocket`](https://msdn.microsoft.com/library/windows/apps/br241319) one has to currently use one of the `GetOutputSreamAsync()` methods then `WriteAsync()` and `FlushAsync`.

None of these operations should be asynchronous - they are in memory and sending datagrams is conectionless - fire and forget - there is nothing to await.

We need to provide a synchronous way of sending data so as to not unnecessarily create `Task`s that will always complete inline - a perf. overhead for applications using these operations frequently e.g. games.

**Comment by mikedn** [comment]
I'm not sure what this has to do with this repository, `DatagramSocket` is a WinRT class.

**Comment by markmnl** [comment]
My bad, still trying to understand the difference. I thought if I created an app referencing only `Microsoft.NETCore.UniversalWindowsPlatform` and I got the Type it would part of ".NET Core", but it seems the ".NET Core" means only the type in this repo?

**Comment by mikedn** [comment]
.NET Core is simply a subset of .NET, it's not related in any way to WinRT. WinRT is basically a COM, native and Windows only framework. The fact that you see those types in a .NET application is the result of an advanced from of COM interop.

**Comment by stephentoub** [comment]
Closing as it's not applicable to this repo.  Thanks, though.
