### ISSUE TITLE
[Uri] Uri.FindOrFetchAsUnknownV1Syntax is breaking thread-safety

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#29360]
When Uri's CheckSchemeSyntax encounters an unknown scheme, it uses FindOrFetchAsUnknownV1Syntax to look up the scheme in a cache, implemented with a dictionary.  This cache is static and thus shared across all threads, and FindOrFetchAsUnknownV1Syntax is attempting to be thread-safe, by using a lock to protect writes to the dictionary.  But it's not using a lock to protect the reads in this function and elsewhere, and unlike Hashtable, Dictionary (and in this case LowLevelDictionary) are not safe for concurrent reading and writing.

**Comment by danmosemsft** [comment]
Should this be 2.1? Reliability with localized fix.

**Comment by stephentoub** [comment]
netfx has the same issue, other schemes are rare-ish, and whatever fix is applied would need sufficient perf testing to ensure we don't regress. I don't think it needs to be rushed into 2.1.
