### ISSUE TITLE
.NET Core's System.Net.Sockets.Socket Send and Receive methods use old async technique

### ISSUE THREAD

**Issue by markmnl** [dotnet/corefx#2936]
There is no documentation on the `System.Net.Sockets.Socket` provided in .NET Core (beyond the XML code documentation) but it seems to provide a subset of .NET Framework desktop [`Socket`s](https://msdn.microsoft.com/en-us/library/system.net.sockets.socket.sendasync(v=vs.110).aspx) members.

The only methods to send and receive are [`SendAsync`](https://msdn.microsoft.com/en-us/library/system.net.sockets.socket.sendasync(v=vs.110).aspx) and [`RecieveAsync`](https://msdn.microsoft.com/en-us/library/system.net.sockets.socket.receiveasync(v=vs.110).aspx). Despite the names they are not `async` methods but an old school variant to which one supplies the `SocketAsyncEvenArgs` parameter *shudder*.

We need to bring .NET Core's `Socket` up-to-date and provide `async` variants. Also consider synchronous methods since `Socket`s are often used in in background processes with dedicated threads where that is wanted (applications tend to use higher application level type such as `HttpClient`).

**Comment by mikedn** [comment]
> Also consider synchronous methods since  Socket s are often used in in background processes with dedicated threads where that is wanted (applications tend to use higher application level type such as  HttpClient ). 

The System.Net.Sockets [diff](https://github.com/dotnet/corefx-progress/blob/master/src-diff/System.Net.Sockets.md) from the corefx-progress repository shows that Socket does have synchronous methods. Is this another case of WinRT/CoreFX confusion?

**Comment by Maxwe11** [comment]
>The only methods to send and receive are SendAsync and RecieveAsync. Despite the names they are not async methods but an old school variant to which one supplies the SocketAsyncEvenArgs parameter shudder.

[NetworkStream](http://referencesource.microsoft.com/#System/net/System/Net/Sockets/NetworkStream.cs,6006b93b3942e29b) has `async` methods but it doesn't override Stream methods. I hope this this will be done in corefx.

**Comment by markmnl** [comment]
Your diff shows everything up in red and the src for `System.Net.Sockets.Socket` has not been added yet, so I am not sure what your diff is against.

I can tell you if you use a `System.Net.Sockets.Socket` today in a UWP app targeting 10240 you only get:

```
public Socket(SocketType socketType, ProtocolType protocolType);
public Socket(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType);
public static bool OSSupportsIPv4 { get; }
public static bool OSSupportsIPv6 { get; }
public AddressFamily AddressFamily { get; }
public bool Connected { get; }
public EndPoint LocalEndPoint { get; }
public bool NoDelay { get; set; }
public ProtocolType ProtocolType { get; }
public int ReceiveBufferSize { get; set; }
public EndPoint RemoteEndPoint { get; }
public int SendBufferSize { get; set; }
public short Ttl { get; set; }
public static void CancelConnectAsync(SocketAsyncEventArgs e);
public static bool ConnectAsync(SocketType socketType, ProtocolType protocolType, SocketAsyncEventArgs e);
public bool AcceptAsync(SocketAsyncEventArgs e);
public void Bind(EndPoint localEP);
public bool ConnectAsync(SocketAsyncEventArgs e);
public void Dispose();
public void Listen(int backlog);
public bool ReceiveAsync(SocketAsyncEventArgs e);
public bool ReceiveFromAsync(SocketAsyncEventArgs e);
public bool SendAsync(SocketAsyncEventArgs e);
public bool SendToAsync(SocketAsyncEventArgs e);
public void Shutdown(SocketShutdown how);
protected virtual void Dispose(bool disposing);
```

**Comment by mikedn** [comment]
> Your diff shows everything up in red and the src for  System.Net.Sockets.Socket  has not been added yet, so I am not sure what your diff is against.

The diff is between what's supposed to be here in corefx and what's actually available here. System.Net.Sockets hasn't been ported yet so everything shows up as red. BTW, the same information is available in the "ref" assemblies that have been ported recently - [System.Net.Sockets.cs](https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/ref/System.Net.Sockets.cs)

> I can tell you if you use a  System.Net.Sockets.Socket  today in a UWP app targeting 10240 you only get:...

That's probably a different matter as what type members are available depends on the reference assemblies used for a given target. You'll have to wait for someone from Microsoft to comment about this but it's well known that UWP tends to provide only asynchronous APIs. At the end of day UWP apps are in general UI apps and there's little reason to use synchronous APIs in such an app. Except, of course, the fact that this may make porting existing code to UWP more difficult.

**Comment by markmnl** [comment]
Fair enough, my main issue is here there is no alternative to the `SendAsync(SocketAsyncEventArgs)` and `RecieveAsync(SocketAsyncEventArgs)` methods e.g. there is no `async SendAsync()`.

I do have a real use case: games, in particular porting our game to UWP: [Square Heroes](www.squareheroes.com). We can use these socket operations up to 60 times a second so perf and ability to reuse buffers is a big concern to us. Since sending UDP datagrams is not an asynchoronous operation I hope doing that is not implemented as one .NET Framework's `System.Net.Sockets.Socket`s `SendTo(endpoint, buffer, index, count)` and `ReceiveFrom(endpoint, buffer, index count)` were perfect and we use them in our current game from our main game loop.

**Comment by mikedn** [comment]
> Fair enough, my main issue is here there is no alternative to the  SendAsync(SocketAsyncEventArgs)  and  RecieveAsync(SocketAsyncEventArgs)  methods e.g. there is no  async SendAsync() .

Note that if you are to chose between `SendAsync(SocketAsyncEventArgs)` and `async SendAsync()` there's a good chance that the former is better as it was designed for performance while the later is designed for convenience.

And yes, in your case synchronous send is likely to be the best choice if available as async operations tend to have higher overhead, Task based or not.

**Comment by davidsh** [comment]
@CIPop @SidharthNabar @pgavlin

**Comment by SidharthNabar** [comment]
@markmnl , thanks for raising this issue. Porting System.Net.Sockets namespace to .NET Core is "Work in Progress" as tracked by issue #896 - this effort will bring a larger surface area of System.Net.Sockets to .NET Core than is available for UWP apps today. If you have specific APIs that you would argue are important to include in this new set, please list them here.

Once this effort is done, we will also look at enabling this larger surface area for UWP apps. For the first version, the main motivation for including System.Net.Sockets in UWP apps was to provide Windows Phone Silverlight parity in terms of API surface as explained here: http://blogs.msdn.com/b/dotnet/archive/2015/07/28/net-networking-apis-for-uwp-apps.aspx

But we are definitely looking at growing this surface area in the future.

Thanks,
Sid

**Comment by CIPop** [comment]
Our current plan is to create the following contracts:
* System.Net.Sockets 4.0.0.0 (port to GitHub in progress)
* System.Net.Sockets 4.0.10.0: will add new TPL variants replacing the Begin/End APM patterns. (`Task<...> SendAsyncTask(...)` and `ReceiveAsyncTask()` to avoid any confusion with the existing `SendAsync` and `ReceiveAsync` APIs.)
* System.Net.Sockets.Legacy 4.0.0.0: will include the old APM `Begin/End` APIs

Please note that the refs file is _not yet_ updated to reflect this new design.

**Comment by markmnl** [comment]
Great to hear, looking forward as will have to wait until then to port our game which is multiplayer centric as cannot get P2P to work today on a UWP app.

**Comment by loqix** [comment]
When will complete the System.Net.Sockets？

**Comment by markmnl** [comment]
FYI: The synchronous `SendTo()` and `ReceiveFrom()` methods are important to us and we hope they make it in.

**Comment by SidharthNabar** [comment]
@loqix - We are currently working on it, but don't have a specific date to promise yet.

@markmnl - Thanks! We'll take this usage into account when designing the exact API surface of the newer contract version of Sockets.

**Comment by SidharthNabar** [comment]
@markmnl - This effort is being tracked by PR #3655 - please take a look and let us know your feedback on the proposed API surface area.

**Comment by CIPop** [comment]
Resolved by 2d6de874008b0ba74c877c5895847421f3adf1af.

**Comment by isamuelson** [comment]
What happend to Disconnect and DisconnectAsync?

**Comment by CIPop** [comment]
@himadrisarkar @davidsh @stephentoub 

@isamuelson `Disconnect` and `DisconnectAsync` are Windows specific: they allow reusing the WinSock handle. I've been told that this functionality doesn't exist on *NIX platforms. We've trimmed the API surface keeping only those APIs that made sense on all platforms. The plan was to add back platform-specific functionality if sufficient justification exists.

Having a scenario would make it easier for us to take a decision on adding back this functionality/APIs.

**Comment by czifro** [comment]
@CIPop For *NIX platforms, how are connections disconnected?

**Comment by CIPop** [comment]
@czifro please clarify what you mean by "disconnected".
Sockets can be "closed" gracefully via shutdown + recv (TCP FIN) or forcefully via close (TCP RST). The first is achieved via `Shutdown` + `ReceiveAsync` or setting linger options and the second by disposing the `Socket` object. 

[Socket.Disconnect()](https://msdn.microsoft.com/en-us/library/system.net.sockets.socket.disconnect(v=vs.110).aspx) is, as far as I know, a Windows-only capability:

> Closes the socket connection and allows reuse of the socket.
