### ISSUE TITLE
Assembly informational attributes not applied for .net core app

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#29362]
**Repro:**

1. Create a .net core app
2. Set the following properties in the csproj

```xml
<PropertyGroup>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <AssemblyTitle>Assembly Information Repro</AssemblyTitle>
    <AssemblyProduct>Assembly Information Repro</AssemblyProduct>
    <AssemblyDescription>Assembly Information Repro</AssemblyDescription>
    <Product>Assembly Information Repro</Product>
    <PublisherName>tester</Publishername>
</PropertyGroup>
```
3. Publish the app.

**Expected:**
The properties on ```<assemblyname>.exe``` are set as per the info provided in the csproj.

**Actual:**
The properties are set only for ```<assemblyname>.dll```, not on the ```<assemblyname>.exe```. Note, the .exe is the one that runs, and is shown in task manager, firewall prompts, etc. So without the process information, on task manager, it doesn't have a description, and on firewall prompts, it shows the publisher as unknown.

**AssemblyMetadata.dll**

![image](https://user-images.githubusercontent.com/7853870/39339896-e260be6e-497f-11e8-867b-fb470122a334.png)

**AssemblyMetadata.exe**

![image](https://user-images.githubusercontent.com/7853870/39339877-c3c9349a-497f-11e8-85ad-64ae3f6461e0.png)

**Comment by karelz** [comment]
This issue was moved to dotnet/core-setup#4088
