### ISSUE TITLE
Directory.EnumerateFiles returns paths with extra path separators

### ISSUE THREAD

**Issue by niemyjski** [dotnet/corefx#29368]
This was working in 2.0 and once we upgraded to 2.1 preview 2 tests started to fail.

I'm passing `"C:\\Code\\Exceptionless\\src\\Exceptionless.Web\\storage\\"` to EnumerateFiles and it's returning a path that contains two separators. Which is breaking behavior when I replace the path with the original folder to get the relative path (and getting a root path).

`C:\Code\Exceptionless\src\Exceptionless.Web\storage\\archive\18\04\27\11\30\1ecd0826e447ad1e78877ab2\81576cb17e464b9f85cfb0fcfb890409.json`

![image](https://user-images.githubusercontent.com/1020579/39361800-9d79f6fc-49e9-11e8-98ed-5261b727ef88.png)

**Comment by niemyjski** [comment]
@karelz @JeremyKuhne this may be related to https://github.com/dotnet/corefx/issues/29368

**Comment by karelz** [comment]
@JeremyKuhne @pjanotti I put it into 2.1 until proven otherwise ...
@niemyjski which issue did you want to reference? You linked this one (self-reference).

**Comment by niemyjski** [comment]
Here is the link to the existing code: https://github.com/FoundatioFx/Foundatio/blob/master/src/Foundatio/Storage/FolderFileStorage.cs#L230 The search pattern was `*` as it cannot be null.

**Comment by JeremyKuhne** [comment]
Ok, I see what happened here. Looking into how to fix it.

**Comment by JeremyKuhne** [comment]
@niemyjski Thanks for opening this! I have a PR for a fix up. You can work around the issue by trimming the trailing separator on `path` before passing to `EnumerateFiles`.

**Comment by karelz** [comment]
Reopening to track 2.1 port

**Comment by JeremyKuhne** [comment]
Change is in master and was put in for 2.1 RTM here: https://github.com/dotnet/corefx/commit/77732da1052923259a7668540ee62bf48d35956e

**Comment by danmosemsft** [comment]
Thanks again @niemyjski  -- we would welcome any other feedback you have on filesystem enumeration code, given the extensive rework it received for 2.1.

**Comment by niemyjski** [comment]
@danmosemsft We just upgraded exceptionless to 2.1-rc and will be testing it and doing benchmarks. I'll let you know how it goes! We are very excited so far and are seeing good numbers across the board.
