### ISSUE TITLE
Now that we have moved to 3.0 we should remap netcoreapp to netcoreapp3.0

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#29384]
Lets change netcoreapp to mean the latest TFM which is netcoreapp2.2 given we have bumped versions with https://github.com/dotnet/corefx/pull/29148

**Comment by ViktorHofer** [comment]
The remaining part here is the remapping in the 2.2 branch.

**Comment by weshaggard** [comment]
We don't plan to do this for 2.2 at this point and we did it for 3.0 in master so closing.
