### ISSUE TITLE
GC tests GetTotalMemoryTest_ForceCollection,  GetGenerationTest test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#2938]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release/1057/console
```
GCTests.GetTotalMemoryTest_ForceCollection [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release\src\System.Runtime\tests\System\GC.cs(295,0): at GCTests.GetTotalMemoryTest_ForceCollection()
```
We should probably just delete these tests.

**Comment by stephentoub** [comment]
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug/1070/console
```
GCTests.GetTotalMemoryTest_ForceCollection [FAIL]
19:36:50         Assert.True() Failure
19:36:50   Finished:    System.Security.Cryptography.Algorithms.Tests
19:36:50         Expected: True
19:36:50         Actual:   False
19:36:50         Stack Trace:
19:36:50            d:\j\workspace\dotnet_corefx_windows_debug\src\System.Runtime\tests\System\GC.cs(294,0): at GCTests.GetTotalMemoryTest_ForceCollection()
```

**Comment by Sridhar-MS** [comment]
Thanks a lot Stephen for disabling the test case! Instead of deleting them we can put these tests in a separate test assembly like System.GC.Tests.dll. This way all the GC tests can be run in isolation and serially in xunit. Please let me know your thoughts on this.

**Comment by Maoni0** [comment]
@stephentoub, is this the same test we were talking about last time wrt GetGeneration?

**Comment by stephentoub** [comment]
Yup

**Comment by Maoni0** [comment]
then shouldn't we just disable this test?

**Comment by stephentoub** [comment]
We did, a month ago. This issue is from August. At this point the action is either to fix the test (or product) and enable it, or delete the test. Then the issue can be closed.

**Comment by Maoni0** [comment]
can you please elaborate you meant by fixing the product? I don't recall anything in the product needs fixing for this...

**Comment by stephentoub** [comment]
I was trying to make a general point that when a test fails, it's either because the test is buggy and the product is fine or the test is fine and the product is buggy. In this case it's probably just that the test is buggy, but I was trying not to assume anything.

**Comment by JonHanna** [comment]
Or... The test is buggy **and** the product is buggy...

**Comment by stephentoub** [comment]
> Or... The test is buggy and the product is buggy...

Sure, there are others as well (e.g. infrastructure). I was simply highlighting the most common reasons, not trying to be complete.

**Comment by Sridhar-MS** [comment]
Thanks @stephentoub for fixing this,
