### ISSUE TITLE
Update the harvested package list once we ship 2.1 stable

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#29383]
Once 2.1 is shipped stable we should update the harvested versions to pull in the new stable packages.

As part of this work we should also remove the explicitly listed version support in System.Threading.Tasks.Extensions.pkgproj https://github.com/dotnet/corefx/pull/29148/files#diff-589bc4b6d3cf97b763cdd071a726b00bR29.

**Comment by joperezr** [comment]
@weshaggard let me know if you want me to take care of this, in case it isn't done yet.

**Comment by weshaggard** [comment]
I'm actively working through the issues right now.
