### ISSUE TITLE
FileVersionInfo.ProductMajorPart is wrong (and inconsistent with .NET Framework) if VersionSuffix contains period character

### ISSUE THREAD

**Issue by JohnRusk** [dotnet/corefx#29399]
With a version number like this:

1.0.0.1-build.foo

ProductMajorPart will return 1 on .NET Framework and 0 on .NET Core.

Admittedly, no-one should really make version suffixes that have dots, and the above should have been 1.0.0.1-build-foo.  But, when someone does include a dot in the suffix, .NET Core should at least be consistent with .NET Framework.

**Comment by stephentoub** [comment]
Can you share a repro? You're referring to .NET Core on Windows?

**Comment by JohnRusk** [comment]
Sorry. False alarm (sort of). It looks like the behavior is consistent on both platforms - i.e. returns 0 on both .NET Framework on Windows and .NET Core on Linux, in cases of such "malformed" version numbers.  Given that the two frameworks are consistent after all, I think this can be closed.

**Comment by stephentoub** [comment]
Thanks.
