### ISSUE TITLE
Proposal for the API Review process

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#294]
Now that we’re on GitHub we also get requests for new APIs. The current API review process is designed around the assumption that it is internal-only. We need to rethink this process for an open source world. This issue represents a proposal how this could be handled. It’s not final – any feedback is highly appreciated.

## Process Goals

The key goals are:

* **Designed for GitHub**. In order to be sustainable and not be a hurdle for contributors the API review process must feel natural to folks familiar with GitHub.

* **Efficiency**. Performing API reviews requires looping in a set of experts. We want to conduct API reviews in an agile fashion without randomizing the reviewers or community members.

* **Transparency**. We can use the same process for both internal as well as external contributors. This allows contributors to benefit from the results of API reviews even if the implementer isn’t external.

## Overall Process

GitHub is generally based around the pull-request model. The idea is that contributors perform their changes in their own fork and submit a pull request against our repository.

For trivial code changes, such as typo fixes, we want folks to directly submit a pull request rather than opening an issue. However, for bug fixes or feature work, we want contributors to first start a discussion by creating an issue.

For work that involves adding new APIs we'd like the issue to contain what we call a *speclet*. The speclet should provide a rough sketch of how the APIs are intended to be used, with sample code that shows typical scenarios. The goal isn't to be complete but rather to illustrate the direction so that readers can judge whether the proposal is sound.

![Process diagram](https://cloud.githubusercontent.com/assets/5169960/5499091/a6895e2c-86dd-11e4-8b0e-6ba1ae152541.png)

## Steps

* **Contributor opens an issue**. The issue description should contain a speclet that represents a sketch of the new APIs, including samples on how the APIs are being used. The goal isn’t to get a complete API list, but a good handle on how the new APIs would roughly look like and in what scenarios they are being used.

* **Community discusses the proposal**. If changes are necessary, the contributor is encouraged to edit the issue description. This allows folks joining later to understand the most recent proposal. To avoid confusion, the contributor should maintain a tiny change log, like a bolded “Updates:” followed by a bullet point list of the updates that were being made.

* **Issue is tagged as “Accepting PRs”**. Once the contributor and project owner agree on the overall shape and direction, the project owner tags the issue as “Accepting PRs”. The contributor should indicate whether they will be providing the PR or only contributed the idea.

* **Coding**. The contributor is implementing the APIs as discussed. Minor deviations are OK, but if during the implementation the design starts to take a major shift, the contributor is encouraged to go back to the issue and raise the concerns with the current proposal.

* **Pull request is being created**. Once the contributor believes the implementation is ready for review, she creates a pull request, referencing the issue created in the first step.

* **Pull request is being reviewed**. The community reviews the code for the pull request. The review should focus on the code changes and architecture – not the APIs themselves. Once at least two project owners give their OK, the PR is considered good to go.

* **Pull is tagged as “Needs API Review”**. The project owner then marks the pull request as “Needs API Review”.

* **API review**. Using the information in the pull request we’ll create an APIX file that constitutes the API delta. The API review board meets multiple times a week to review all PRs that are tagged as needing an API review.

* **Pull request is updated with the results of the API Review**. Once the API review is complete, the project owner uploads the notes and API HTML diff, including all comments. The project owner also updates the PR accordingly, with either a call to action to address some concerns or a good to go indicator.

* **Pull request is merged**. When there are no issues – or the issues were addressed by the contributor, the PR is merged.

## API Design Guidelines

The .NET design guidelines are captured in the famous book [Framework Design Guidelines](http://amazon.com/dp/0321545613) by Krzysztof Cwalina and Brad Abrams.

A digest with the most important guidelines are available in our [developer wiki](https://github.com/dotnet/corefx/wiki/Framework%20Design%20Guidelines%20Digest). Long term, we'd like to publish the individual guidelines in standalone repo on which we can also accept PRs and -- more importantly for API reviews -- link to.

**Comment by justinvp** [comment]
> > There is no opportunity for the board to ask the contributor questions, or for the contributor to explain their decisions.
>
> While the review board meeting is certainly happening outside of GitHub, our intent is to be as transparent as possible. On campus, we invite the author of an API and found this invaluable. However, on campus it's obviously easier because we're on site and in the same time zone.
> 
> Currently, our goal is to compensate for the lack of involving the author in the API review process by asking the right questions when we review the speclet so that we can represent the author's intent during the review. It's certainly not perfect but probably a good enough approximation. If we find it doesn't work, we'll need to re-adjust.

The ASP.NET team has been doing [Community Standup](https://www.youtube.com/playlist?list=PL0M0zPgJ3HSftTAAHttA3JQU4vOjXFquF) meetings using Google Hangouts. Worth considering doing something similar for the API reviews.

**Comment by sharwell** [comment]
> The ASP.NET team has been doing Community Standup meetings using Google Hangouts. Worth considering doing something similar for the API reviews.

It would be awesome to use a shared broadcast (open for viewing but not public feedback) during API reviews, especially for API contributions submitted by non-Microsoft individuals. Even for people that aren't working on the API change itself, observing the process could be valuable as a learning experience for teams that want to become the most effective .NET developers they are can.

**Comment by terrajobst** [comment]
Thanks for all the feedback!

* I've added the [API review process to our wiki](https://github.com/dotnet/corefx/wiki/API%20Review%20Process):
* Today, we've also [uploaded our first set of notes](https://github.com/dotnet/apireviews/tree/master/2015-01-07-immutable) from an API review meeting we did today.
* We plan on conducting an API review four our GitHub issues next week. I try to get it recorded, stay tuned.

**Comment by justinvp** [comment]
> I try to get it recorded, stay tuned.

The ASP.NET Community Standup meetings are live (as well as recorded). It'd be really cool if the API Reviews were live too. And if the API contributor was able to watch live, he/she could answer any questions or provide clarifications immediately in the chat room during the review.

**Comment by terrajobst** [comment]
I was indeed able to record and you can find the recording [here](http://channel9.msdn.com/Series/NET-Framework/NET-Core-API-Review-2015-01-14).

**Comment by eatdrinksleepcode** [comment]
I really appreciate the obvious effort that went into preparing and publishing the notes and video from the API Review. The notes were clear and helpful, and the direct links to the correct place in the video for the discussion of each PR was a nice touch. The video itself was very informative, not to mention utterly fascinating. I am sure it was business as usual for you guys, but as a long-time .NET developer who has always been curious about how these discussions happen inside DevDiv, I loved watching it. I also appreciate that there is a certain amount of risk in opening your internal conversations up to the world like that; I for one found it very valuable, and look forward to future episodes :)

**Comment by terrajobst** [comment]
@eatdrinksleepcode, thanks a lot for the kind words and for taking the time giving us positive feedback! This is highly appreciated.

**Comment by RichiCoder1** [comment]
:+1:

**Comment by slang25** [comment]
I agree with @eatdrinksleepcode, I found this a fascinating insight into the decisions you have to make. It must be extremely difficult having to maintain such strict backwards compatibility.

**Comment by hickford** [comment]
> I've added the API review process to our wiki

The link is dead. Where should I look? @terrajobst

**Comment by hickford** [comment]
A question about API review process described at https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md

If a proposal is approved, in which frameworks would the API be implemented? .NET Core? .NET Framework? Both (.NET Standard)?
