### ISSUE TITLE
There appears to be no way to prevent strings with embedded NULs from being parsed successfully as numbers

### ISSUE THREAD

**Issue by Porges** [dotnet/corefx#29405]
A string with a trailing `NUL` char will always parse successfully, even if `NumberStyles.None` is passed:

```csharp
// trailing space okay with default NumberStyles
int.Parse("1234 ", CultureInfo.InvariantCulture)
→ 1234

// as is trailing NUL
int.Parse("1234\u0000", CultureInfo.InvariantCulture)
→ 1234

// we can prevent parsing of trailing space by specifying NumberStyles.None
int.Parse("1234 ", NumberStyles.None, CultureInfo.InvariantCulture)
→ FormatException

// however, embedded NUL still parses
int.Parse("1234\u0000", NumberStyles.None, CultureInfo.InvariantCulture)
→ 1234
```

**Comment by danmosemsft** [comment]
Was thinking this is https://github.com/dotnet/coreclr/pull/17820 at first, but seems not.

**Comment by danmosemsft** [comment]
@stephentoub

**Comment by stephentoub** [comment]
@danmosemsft, this isn't related to my changes.  This is the same behavior as on all previous releases of .NET Core and on .NET Framework as well.  Trailing nulls are explicitly ignored, as can be seen in the reference source at https://referencesource.microsoft.com/#mscorlib/system/number.cs,1031, with the comment in that function "For compatability, we need to allow trailing zeros at the end of a number string".  Contrary to the issue title, it's not all embedded nulls, only trailing, e.g. "1234\0" works fine but "123\04" throws.

**Comment by danmosemsft** [comment]
Ah I see.

It looks like have some tests eg
https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/Int32Tests.cs#L191
but not fall all types eg
https://github.com/dotnet/corefx/blob/a913bc7463a15c6aead2deb75f61df52242bac71/src/System.Runtime/tests/System/Int64Tests.cs#L172

Some tests may be missing for nulls embedded within the number, also.

**Comment by stephentoub** [comment]
> Some tests may be missing for nulls embedded within the number, also.

There are tests for that, too, e.g.
https://github.com/dotnet/corefx/blob/997c881b22e5f4ad852fe141974f548004beef5e/src/System.Runtime/tests/System/Int32Tests.cs#L349-L355

**Comment by danmosemsft** [comment]
Right, I said some because I didn't see them for Int64.

**Comment by stephentoub** [comment]
Is there an action item here or can this be closed?

**Comment by danmosemsft** [comment]
If you think we don't need tests for other numeric types, then we can close this.

**Comment by stephentoub** [comment]
Well, there are lots of differences in the tests, which effectively assume that things that would affect Int32 would affect the other numeric types, and thus Int32 has the bulk of the tests and then there are more limited smoke tests for the others, e.g. the difference between:
https://github.com/dotnet/corefx/blob/997c881b22e5f4ad852fe141974f548004beef5e/src/System.Runtime/tests/System/Int32Tests.cs#L176-L296
and
https://github.com/dotnet/corefx/blob/997c881b22e5f4ad852fe141974f548004beef5e/src/System.Runtime/tests/System/Int64Tests.cs#L172-L199

If you have a desire to see the tests for all of the numeric types fleshed out to match Int32, great, but it goes well beyond trailing zeros.

**Comment by Porges** [comment]
So is that an "it has always been this way so it won't change"?

**Comment by stephentoub** [comment]
It's "It's always been this way, changing it would almost surely break code, and code that wants this to fail could used check for trailing nulls if they're an issue." Why do you need these to fail?

**Comment by Porges** [comment]
I am currently checking for NULs myself, just wanted to clarify 🙂

**Comment by Porges** [comment]
I will amend the documentation (in my case I was very surprised when a downstream system complained about a string I had checked with `int.TryParse`).

**Comment by stephentoub** [comment]
Sounds good. Thanks.
