### ISSUE TITLE
CoreFx.Private.TestUtilities dependencies are bogus versions

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#29412]
See https://dotnet.myget.org/feed/dotnet-core/package/nuget/CoreFx.Private.TestUtilities.

The versions for Microsoft.DotNet.PlatformAbstractions and Xunit are bogus.

This is because the CoreFx packaging uses the package index to construct dependencies based on assembly references.  When data is missing from the index it assumes package version = assembly version and pre-release is the same as CoreFx: that's what's happening here with Xunit.

/cc @A-And @weshaggard

**Comment by ericstj** [comment]
Given that this package is a hack it might be better just to turn off dependency harvesting completely (rather than trying to plumb xunit into the package index).  To do that we can just set `<OmitDependencies>true</OmitDependencies>` in the project file.

**Comment by weshaggard** [comment]
I think disabling the harvesting will probably be fine.

**Comment by wtgodbe** [comment]
@ericstj did this ever get resolved? If not I can pick it up

**Comment by ericstj** [comment]
I believe @ViktorHofer is deleting this package which will make this issue moot.

**Comment by ViktorHofer** [comment]
Closing as we don't publish a package for CoreFx.Private.TestUtilities anymore.
