### ISSUE TITLE
Add search methods to the StringBuilder

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/corefx#29459]
# The Urge:
The StringBuilder class doesn't contain methods to search for the position of a string such as Contains,  IndexOf, LastIndexOf, IndexOfAny and LastIndexOfAny.
In some situations it is not efficient to use StringBuilder.ToString().IndexOf() to find these parts, such as when you add strings to the SB in a loop, and want to ensure it is not duplicated, so you need to search for them first. Using StringBuilder.ToString().IndexOf() in a loop will waste the SB benefits.
So, instead of doing our workarounds, why don't you add all the missing methods from the String Class to the StringBuilder, especially the search methods?
In practice, I used a string to check the existance of certain IDs to ensure a correct format, and a SB to make replacements becuase the string is large and I made thousand of replacements!.. My problem could be solved easly if the Replace method returns the number of replacements it makes, but instead it returns a refrence to the same SB!
 Maybe we need a new overload of the Replace method with an out param that returns the no of replacements, or add a new Replace method with any suitable suffix that returns a tuple.
This code:
```
SB.Replace(x, y, out int c)
if (c == 0)
   MessageBox.Show("Not Found");
```

is more efficient that this one, which will search the sb twice in case the search string exists (suppose IndexOf added):
```
if (SB.IndexOf(x) == -1)
   MessageBox.Show("Not Found");
else
   SB.Replace(x, y)

```
# Proposed API
```
Class StringBuilder 
{
    public bool Contains(String value);

    public StringBuilder Replace(String oldValue, String newValue, out int CountOfReplacements);
    public StringBuilder Replace(char oldChar, char newChar, out int NoOfReplacements);
    public (StringBuilder SB, int NoOfReplacements) Replace2(String oldValue, String newValue);
    public (StringBuilder SB, int NoOfReplacements) Replace2(char oldChar, char newChar)

    public int IndexOf(char value, int startIndex, int count);
    public int IndexOf(char value, int startIndex);
    public int IndexOf(char value);
    public int IndexOf(String value, int startIndex);
    public int IndexOf(String value, int startIndex, StringComparison comparisonType);
    public int IndexOf(String value, int startIndex, int count);
    public int IndexOf(String value, StringComparison comparisonType);
    public int IndexOf(String value);
    public int IndexOfAny(char[] anyOf);
    public int IndexOfAny(char[] anyOf, int startIndex);
    public int IndexOfAny(char[] anyOf, int startIndex, int count);

    public int LastIndexOf(char value, int startIndex, int count);
    public int LastIndexOf(char value, int startIndex);
    public int LastIndexOf(char value);
    public int LastIndexOf(String value, int startIndex);
    public int LastIndexOf(String value, int startIndex, StringComparison comparisonType);
    public int LastIndexOf(String value, int startIndex, int count);
    public int LastIndexOf(String value, StringComparison comparisonType);
    public int LastIndexOf(String value);
    public int LastIndexOfAny(char[] anyOf);
    public int LastIndexOfAny(char[] anyOf, int startIndex);
    public int LastIndexOfAny(char[] anyOf, int startIndex, int count);

}
```

# Usage Example
```
StringBuilder SB = new StringBuilder ("Some String")
for (int i = 0 to 1000)
{
   string x = Foo();
   String ID = x.SubString(0, 4);
   if (!SB.Contains(ID))
      SB.AppendLine(x);
}
ID = "....";
string NewID = "......"
if (SB.Replace2(ID, NewID).NoOfReplacements == 0)
   throw new Exception("Missing ID");
```

**Comment by danmosemsft** [comment]
> when you add strings to the SB in a loop, and want to ensure it is not duplicated, so you need to search for them first.

Could you give more detail/ a code snippet showing what you are trying to do? IndexOf is of course O(n), and would be slower in StringBuilder than string because it's not necessarily contiguous. What you describe sounds like it could use a parallel HashSet.

That isn't to say that it's not reasonable to add these to StringBuilder. Unlike indexing into the buffer, they should have complexity roughly matching the string versions.

**Comment by MohammadHamdyGhanem** [comment]
@danmosemsft 
SB has a Replace method, and of cource it first searchs for the string to replace, so why not adding the Contains and IndexOf methods?
In practice, I used a string to check the existance of certain IDs to ensure a correct format, and a SB to make replacements becuase the string is large and I made thousand of replacements!.. My problem could be solved easly if the Replace method returns the number of replacements it makes, but instead it returns a refrence to the same SB!
Maybe we need a new overload of the Replace method with an out param that returns the no of replacements, or add a new Replace method with any suitable suffix that returns a tuple.

**Comment by joperezr** [comment]
@MohammadHamdyGhanem in case you are interested to provide the formal API proposal as @danmosemsft suggested, here is a good example of how the proposal should look like: #29258

**Comment by MohammadHamdyGhanem** [comment]
@joperezr @danmosemsft 
I did my best, despite I see this is a simple obvious request that doesn't need all this effort and time to write all this stuff!
Thanks.

**Comment by danmosemsft** [comment]
@MohammadHamdyGhanem in your first code example, the algorithm is potentially quadratic. Why would you not use aHashSet instead of searching? I'm not saying there aren't motivations to add some of these API but maybe not this one.

**Comment by MohammadHamdyGhanem** [comment]
I can use lists to buils large strings so there will be no use for the SB class!
I just gave a usage sample. In practice I was asked to modify large files to replace the IDs, and this was a one time job needed immediately (Programming languages not necessarily used large apps all the Times. Fast dirty code is laso needed in some areas in a daily basis!) . The fastest way is to load the files into SBs and make the replacements. I wanted to check that all the IDs were found and replaced to be sure there is no data corruption, but SB has no method to do that!
Maybe weshould think of a way to do replacement in text files directly.  VB.NET has a My.Computer.FileSystem.FindInFiles method but has no ReplaceInFiles one!

**Comment by danmosemsft** [comment]
Fair enough. I think the argument for at least IndexOf/LastIndexOf is good. 

This is basically part of https://github.com/dotnet/corefx/issues/11390

@joperezr will review first

**Comment by joperezr** [comment]
@stephentoub any initial concerns implementation-wise around adding these APIs to StringBuilder?

**Comment by stephentoub** [comment]
> adding these APIs

Which ones in particular?  Just IndexOf and LastIndexOf?

**Comment by MohammadHamdyGhanem** [comment]
I made more suggestions about the StringBuilder.Replace method here #29498 and here #29499.

**Comment by MohammadHamdyGhanem** [comment]
I proposed to add a MutableString class that contains the missing StringBuilder functinality  #29510 
Hope you help implement it.

**Comment by joperezr** [comment]
yeah, as @danmosemsft suggested I think that there is enough argument to add those. I just wanted to know if there where implementation concerns since you have more context on the implementation of SB.

**Comment by stephentoub** [comment]
I expect {Last}IndexOf with StringComparison for culture-sensitive comparisons could be challenging, in particular when a match might span across segments.  I'm also not at all convinced we should be adding all of these methods (and those proposed in the other issues just opened, e.g. https://github.com/dotnet/corefx/issues/29498 and https://github.com/dotnet/corefx/issues/29499).  This is attempting to turn StringBuilder into a full-fledged string replacement, which is not its purpose.

**Comment by danmosemsft** [comment]
Right. I was thinking of the simple ordinal ones.

@vancem had some discussion of making it more stringlike here https://github.com/dotnet/corefx/issues/11390

I don't think we should do any of the elaborate suggestions there (like copy on write) just simply because the complexity of the implementation is already high and it's unlikely it could be done without impacting its 99% use case which is lots of appends.
