### ISSUE TITLE
HashSet<string>(StringComparer.OrdinalIgnoreCase) performance worse in netcore 2.0

### ISSUE THREAD

**Issue by srijken** [dotnet/corefx#29454]
I was checking the performance between `HashSet<string>()` and `HashSet<string>(StringComparer.OrdinalIgnoreCase` on .NET 4.6, and thought I'd check to see if it improved on netcore. The results are interesting, I expected netcore to be faster, but it proved to be way slower.

The code:
```
using System;
using System.Collections.Generic;
using System.Diagnostics;

public class Program
{
    const int ITERATIONS = 10000000;

    public static void Main()
    {
        //Test(new HashSet<string>()); // Disabled this, because the problem's not here
        Test(new HashSet<string>(StringComparer.OrdinalIgnoreCase));
    }

    private static void Test(HashSet<string> s)
    {
        s.Add("Need at least one item in the set");

        var sw = Stopwatch.StartNew();

        for (int i = 0; i < ITERATIONS; i++)
            s.Contains("Some long string, it really doesn't matter, just for checking the GetHashCode() performance" + i);

        sw.Stop();
        Console.WriteLine(sw.Elapsed.ToString());
    }
}
```

on .NET 4.6 I see figures of about 4 / 4.2 seconds
on netcore 1.0 and 1.1, it's similar
on netcore 2.0 I see figures averaging around 15 seconds

**Comment by stephentoub** [comment]
I converted your test to one using Benchmark.NET:
```C#
private static readonly HashSet<string> s_set = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
{
    "Need at least one item in the set"
};

[Benchmark(OperationsPerInvoke = 1000)]
public void OrdinalIgnoreCase()
{
    for (int i = 0; i < 1000; i++)
    {
        s_set.Contains("Some long string, it really doesn't matter, just for checking the GetHashCode() performance" + i);
    }
}
```
and I got these results:

|            Method |     Toolchain |       Mean |
|------------------ |-------------- |-----------:|
| OrdinalIgnoreCase | .NET Core 2.0 | 1,604.4 ns |
| OrdinalIgnoreCase |  CsProjnet471 |   368.1 ns |
| OrdinalIgnoreCase | .NET Core 1.1 |   339.7 ns |
| OrdinalIgnoreCase | .NET Core 2.1 |   262.4 ns |

So there does appear to have been a regression here in .NET Core 2.0 but that was fixed for .NET Core 2.1.

cc: @jkotas, @ViktorHofer, @danmosemsft
