### ISSUE TITLE
StartsWith/EndsWith not giving expected results on Linux

### ISSUE THREAD

**Issue by slozier** [dotnet/corefx#29474]
Both of these are passing on Windows but failing on Linux (Ubuntu 16.04 over WSL). Also fails if I use the invariant comparison.
```C#
Debug.Assert("\r\n".EndsWith("\n"));
Debug.Assert("\r\n".StartsWith("\r"));
```

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/4587, and specifically see https://github.com/dotnet/corefx/issues/4587#issuecomment-219087701.

**Comment by karelz** [comment]
Closing as duplicate of #4587
