### ISSUE TITLE
ConcurrentQueue performance degradation?

### ISSUE THREAD

**Issue by electricessence** [dotnet/corefx#29477]
About six months ago I did a study on ObjectPools and different implementations using varying collection types.

I posted my conclusion here: https://www.reddit.com/r/dotnetcore/comments/76w4w2/object_pools_optimistic_array_vs_concurrent_queue/?st=jgqombfc&sh=6a26b8ff

The performance results in color are here: http://telegra.ph/Object-Pools-Optimistic-Array-vs-Concurrent-Queue-Results-10-17

ConcurrentQueue seemed to be consistenly the winner for pools over 100 in size.

But I retested my results and the ConcurrentQueue's performance has significantly degraded?
The only thing I can say for sure has changed is I updated all my library references from netcoreapp2.0 to netstandard2.0.  I did retry the benchmarks with with netcoreapp2.0 and saw the same results. :(

My changes since then have been nearly non-existent:
https://github.com/electricessence/Open.Disposable.ObjectPools/commits/master

Here is where it get's (really) bad compared to before:
![image](https://user-images.githubusercontent.com/5899455/39588090-e929849e-4eaf-11e8-8fb7-8d3f82f3368e.png)

ConcurrentQueue's time explodes by magnitudes.  But ConcurrentStack seems to do just fine.

I think I had some dialog with @stephentoub about how ConcurrentQueue's implementation was really fast and so the previous results seemed to make sense.

Any explanation as to why this is happening would be appreciated.  Seems like a potential bug to me since the performance difference is not small.

Thanks ahead of time.

**Comment by stephentoub** [comment]
It looks like your benchmark accesses `ConcurrentQueue<T>.Count` on every operation.  That's going to perform terribly.

**Comment by kasper3** [comment]
https://github.com/dotnet/corefx/blob/5086f38/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentStack.cs#L127-L158
vs.
https://github.com/dotnet/corefx/blob/5086f38/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentQueue.cs#L266-L337

**Comment by electricessence** [comment]
@kasper3 wow ok! LOL  Definitely a big difference.  (Still investigating.  Will have an update soon.)

**Comment by electricessence** [comment]
Confirmed.  When eliminating `.Count` calls, `ConcurrentQueue` behaves as expected.
Thank you for your time.

**Comment by electricessence** [comment]
I was able to solve the count problem by adding some Interlocked Increment/Decrement when tracking the enqueue/dequeue (give/take).  And then also added a default to avoid the tracking all together (no counting).  And although the performance benefit of not tracking the count almost negligible, it wasn't zero. 

https://msdn.microsoft.com/en-us/library/dd267339(v=vs.110).aspx
The documentation might want to point out that `ConcurrentQueue`'s count is computed in such a way that consumers of `ConcurrentQueue` should avoid calling `.Count` repeatedly..
