### ISSUE TITLE
WebProxy uses pascal case for parameter names

### ISSUE THREAD

**Issue by marcin-chwedczuk** [dotnet/corefx#29476]
I am using version `4.3.3` of `System.Net.Http` package. When I tried to setup proxy for HttpClient I noticed that `WebProxy` class uses pascal case for constructor parameter names. For example see line:
https://github.com/dotnet/corefx/blob/8cb7675e8702d76dad15f1ac9858abe475b8324c/src/System.Net.WebProxy/src/System/Net/WebProxy.cs#L22
This is against .NET coding conventions which states that parameter names should be written in camel case. It would be great to fix this, but of course I am aware that this is a breaking change and may cause code to stop compiling when someone used explicit parameter names in their code like:
```csharp
var proxyHttpClientHandler = new HttpClientHandler {
   // notice explicit parameter name 'BypassOnLocal'
    Proxy = new WebProxy(new Uri("http://localhost:5555/"), BypassOnLocal: false),
    UseProxy = true,
};            
```
Still I believe that this should be fixes ASAP even if it causes inconveniences for some people, it would be a better decision in the long run.

**Comment by stephentoub** [comment]
This type has been around for a very long time with these parameter names.  While they're unfortunately named, changing them is a breaking change, and it's not worth the compat break to change them.

**Comment by karelz** [comment]
Agreed. Sadly, compat wins here over consistency. It is not worth breaking people.
