### ISSUE TITLE
Audit awaits on calls that do not have ConfigureAwait(false)

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#29483]
Generally CoreFX code (being library code) should not allow continuations to return to the thread's synchronization context, as if it's the non default context this will cause overhead and - if the caller is waiting synchronously - possibly deadlocks.

https://github.com/dotnet/corefx/pull/29465 fixed a couple of cases.

There are others. The regex `await (?!(.*ConfigureAwait))` strips almost all use of await, and leaves about 50 possible hits (ignoring comments) in implementation code. Some of them are false positives eg in System.Net.Http a call to `SuppressContextFlow()` will cause `ConfigureAwait(false)`

Task here is to make a pass and fix such issues.

**Comment by AArnott** [comment]
@sharewell True, but IMO we already have an established pattern for this (and analyzers to boot!). Inventing a new pattern, particularly when only a few possibly violations remain in corefx to fix, seems overkill.
