### ISSUE TITLE
Allow Regex to match and Replace patterns in StringBuilder

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/corefx#29498]
There is no problem to use regex to match strings in a large string obtained from StringBuilder.ToString( ), but it's not suitable to use Regex.Replace method to replace strings in such large string. The alternative is like this:
```
var Sb = new StringBuilder("Some Large Text");
var RepText = "SomeText";
var rgx = new Regex("Some Regex");
var result = rgx.Matches(Sb.ToString())
for (int i =result.Length-1; i >-1 ; i--)
{
   var m = result[i];
   Sb.Remove(m.Index, m.Length);
   Sb.Insert(m.Index, RepText);
}

```
This is code is larger and less efficient then this one:
```
var Sb = new StringBuilder("Some Large Text");
var RepText = "SomeText";
var rgx = new Regex("Some Regex");
rgx.Replace(sb, RepText)

```
Besides, the first code doesn't allow us to use a replacement pattern.

So I suggest to add these new Replace overloads to the Regex class:
```
public static StringBuilder Replace(StringBuilder input, string pattern, MatchEvaluator evaluator, RegexOptions options, TimeSpan matchTimeout);
public static StringBuilder Replace(StringBuilder input, string pattern, string replacement, RegexOptions options);
public static StringBuilder Replace(StringBuilder input, string pattern, string replacement);
public static StringBuilder Replace(StringBuilder input, string pattern, MatchEvaluator evaluator);
public static StringBuilder Replace(StringBuilder input, string pattern, MatchEvaluator evaluator, RegexOptions options);
public static StringBuilder Replace(StringBuilder input, string pattern, string replacement, RegexOptions options, TimeSpan matchTimeout);


```

**Comment by danmosemsft** [comment]
Regex relies heavily on O(1) indexing into the string. StringBuilder has nearly O(n) indexing. It is optimized for appending and staying out of LOH.

**Comment by MohammadHamdyGhanem** [comment]
@danmosemsft 
So, I said nothing about the Match method. Regex can sttill use the SB.ToString() for matching, but do the pattern replacement in the SB directly. It will need some work, but it can be done.

**Comment by akashkc** [comment]
@danmosemsft  : What do you mean by O(1) and O(n) indexing in string and stringbuilder respectively?

**Comment by danmosemsft** [comment]
@akashkc indexing into a string is just a jump to an offset as strings are contiguous areas of memory. Indexing into a StringBuilder requires traversing its data structures which can be slower : https://github.com/dotnet/corefx/issues/25804

**Comment by MohammadHamdyGhanem** [comment]
@danmosemsft 
I suggested some solutions in #25804, and I suggest to reopen that issue, and try to implement my solution as a pull request. 
If SB has the MoveXX methodes as I discribed, it will get red of the indexing overhead, then there will no problem to use it with the Regex.

**Comment by MohammadHamdyGhanem** [comment]
I proposed to add a MutableString class that contains the missing StringBuilder functinality  #29510 
Hope you help implement it.
