### ISSUE TITLE
Channels: Please include common use extensions.

### ISSUE THREAD

**Issue by electricessence** [dotnet/corefx#29500]
In my use of channels recently I'm very commonly repeating a simple consumer pattern.
It would be good to have this in the code base so it got reviewed by the community and kept up to date.

#### Common Use Case Example (Simple)

```cs
var reader = _channel.Reader;
while (await reader.WaitToReadAsync().ConfigureAwait(false))
{
	while (reader.TryRead(out T item))
	{
		// Consume item.
	}
}
```

#### Ideas

I do not know the best way to include this as a proper set of extensions, but just a few examples:

```cs
public static async Task Consume(this ChannelReader<T> source, Action<T> consumer)
{
	while (await reader.WaitToReadAsync().ConfigureAwait(false))
	{
		while (reader.TryRead(out T item)) consumer(item);
	}
}
```

```cs
public static async Task Consume(this ChannelReader<T> source, Func<T, Task> consumer, CancellationToken token)
{
	while (await reader.WaitToReadAsync(token).ConfigureAwait(false))
	{
		await consumer(await ReadAsync(token));
	}
}
```

**Comment by davidfowl** [comment]
This will get solved when the next version of c# adds support for async foreach.

**Comment by stephentoub** [comment]
Right. We explicitly didn't add anything here yet as we intend to do so with support ala:
```C#
foreach async (var item in channel.Reader)
{
   ...
}
```

**Comment by electricessence** [comment]
#mindblow 

I see, so something similar to AsyncEnumerable will solve the 'next' and 'complete' problem.
