### ISSUE TITLE
macosx 10.13.4 corefx build errors

### ISSUE THREAD

**Issue by asthana86** [dotnet/corefx#29504]
Building in CLI
Here are my details for the environment:
dotnet: 2.2.100-preview1-008633
openssl: 1.0.2o_1
mono: JIT compiler version 5.8.1.0
cmake: version 3.11.1
xcode : 9.2

Output of the build : Cliffs-iMac:corefx cliffozewell$ ./build.sh 
Tools are already initialized
Running: /Users/cliffozewell/Desktop/Repos/corefx/src/Native/build-native.sh   x64  Debug  OSX  --numproc 4  -portable  toolSetDir=c:\tools\clr 
Setting up directories for build
WARNING: Can not determine runtime id for current distro.
Checking pre-requisites...
Commencing build of corefx native components for OSX.x64.Debug
Invoking cmake with arguments: "/Users/cliffozewell/Desktop/Repos/corefx/src/Native/Unix" DEBUG  -DFEATURE_DISTRO_AGNOSTIC_SSL=0 -DCMAKE_STATIC_LIB_LINK=0
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/cliffozewell/Desktop/Repos/corefx/bin/obj/OSX.x64.Debug/native
Executing make install -j 4 
Scanning dependencies of target System.Native-Static
Scanning dependencies of target System.IO.Compression.Native-Static
Scanning dependencies of target System.IO.Compression.Native
Scanning dependencies of target System.Native
[  0%] Building CXX object System.Native/CMakeFiles/System.Native.dir/pal_console.cpp.o
[  1%] Building CXX object System.Native/CMakeFiles/System.Native-Static.dir/pal_console.cpp.o
[  1%] Building CXX object System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native.dir/pal_zlib.cpp.o
[  1%] Building CXX object System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native-Static.dir/pal_zlib.cpp.o
[  1%] Building C object System.Native/CMakeFiles/System.Native-Static.dir/pal_errno.c.o
[  2%] Building C object System.Native/CMakeFiles/System.Native.dir/pal_errno.c.o
[  3%] Building C object System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native-Static.dir/Users/cliffozewell/Desktop/Repos/corefx/src/Native/AnyOS/brotli/common/dictionary.c.o
[  4%] Building C object System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native.dir/Users/cliffozewell/Desktop/Repos/corefx/src/Native/AnyOS/brotli/common/dictionary.c.o
[  4%] Building CXX object System.Native/CMakeFiles/System.Native.dir/pal_interfaceaddresses.cpp.o
[  5%] Building CXX object System.Native/CMakeFiles/System.Native-Static.dir/pal_interfaceaddresses.cpp.o
[  5%] Building C object System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native-Static.dir/Users/cliffozewell/Desktop/Repos/corefx/src/Native/AnyOS/brotli/dec/bit_reader.c.o
[  5%] Building C object System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native.dir/Users/cliffozewell/Desktop/Repos/corefx/src/Native/AnyOS/brotli/dec/bit_reader.c.o
[  5%] Building C object System.Native/CMakeFiles/System.Native-Static.dir/pal_io.c.o
[  6%] Building C object System.Native/CMakeFiles/System.Native.dir/pal_io.c.o
[  8%] Building C object System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native-Static.dir/Users/cliffozewell/Desktop/Repos/corefx/src/Native/AnyOS/brotli/dec/decode.c.o
[  8%] Building C object System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native.dir/Users/cliffozewell/Desktop/Repos/corefx/src/Native/AnyOS/brotli/dec/decode.c.o
[  9%] Building C object System.Native/CMakeFiles/System.Native.dir/pal_maphardwaretype.c.o
[ 10%] Building C object System.Native/CMakeFiles/System.Native-Static.dir/pal_maphardwaretype.c.o
[ 10%] Building C object System.Native/CMakeFiles/System.Native.dir/pal_memory.c.o
[ 11%] Building C object System.Native/CMakeFiles/System.Native-Static.dir/pal_memory.c.o
[ 12%] Building CXX object System.Native/CMakeFiles/System.Native.dir/pal_mount.cpp.o
[ 12%] Building CXX object System.Native/CMakeFiles/System.Native-Static.dir/pal_mount.cpp.o
[ 12%] Building C object System.Native/CMakeFiles/System.Native.dir/pal_networking.c.o
[ 13%] Building C object System.Native/CMakeFiles/System.Native-Static.dir/pal_networking.c.o
/Users/cliffozewell/Desktop/Repos/corefx/src/Native/Unix/System.Native/pal_networking.c:1026:5: error: declaration shadows a typedef in
      the global scope [-Werror,-Wshadow]
    c_static_assert(sizeof_member(struct xsocket, so_linger) == 2);
    ^
/Users/cliffozewell/Desktop/Repos/corefx/src/Native/Unix/Common/pal_compiler.h:19:41: note: expanded from macro 'c_static_assert'
#define c_static_assert(e) typedef char __c_static_assert__[(e)?1:-1]
                                        ^
/Users/cliffozewell/Desktop/Repos/corefx/src/Native/Unix/System.Native/pal_networking.c:142:1: note: previous declaration is here
c_static_assert(offsetof(struct IOVector, Count) == offsetof(struct iovec, iov_len));
^
/Users/cliffozewell/Desktop/Repos/corefx/src/Native/Unix/Common/pal_compiler.h:19:41: note: expanded from macro 'c_static_assert'
#define c_static_assert(e) typedef char __c_static_assert__[(e)?1:-1]
                                        ^
/Users/cliffozewell/Desktop/Repos/corefx/src/Native/Unix/System.Native/pal_networking.c:1026:5: error: declaration shadows a typedef in
      the global scope [-Werror,-Wshadow]
    c_static_assert(sizeof_member(struct xsocket, so_linger) == 2);
    ^
/Users/cliffozewell/Desktop/Repos/corefx/src/Native/Unix/Common/pal_compiler.h:19:41: note: expanded from macro 'c_static_assert'
#define c_static_assert(e) typedef char __c_static_assert__[(e)?1:-1]
                                        ^
/Users/cliffozewell/Desktop/Repos/corefx/src/Native/Unix/System.Native/pal_networking.c:142:1: note: previous declaration is here
c_static_assert(offsetof(struct IOVector, Count) == offsetof(struct iovec, iov_len));
^
/Users/cliffozewell/Desktop/Repos/corefx/src/Native/Unix/Common/pal_compiler.h:19:41: note: expanded from macro 'c_static_assert'
#define c_static_assert(e) typedef char __c_static_assert__[(e)?1:-1]
                                        ^
1 error generated.
1 error generated.
make[2]: *** [System.Native/CMakeFiles/System.Native.dir/pal_networking.c.o] Error 1
make[1]: *** [System.Native/CMakeFiles/System.Native.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 13%] Building C object System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native-Static.dir/Users/cliffozewell/Desktop/Repos/corefx/src/Native/AnyOS/brotli/dec/huffman.c.o
make[2]: *** [System.Native/CMakeFiles/System.Native-Static.dir/pal_networking.c.o] Error 1
make[1]: *** [System.Native/CMakeFiles/System.Native-Static.dir/all] Error 2
[ 13%] Building C object System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native.dir/Users/cliffozewell/Desktop/Repos/corefx/src/Native/AnyOS/brotli/dec/huffman.c.o
[ 14%] Building C object System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native.dir/Users/cliffozewell/Desktop/Repos/corefx/src/Native/AnyOS/brotli/dec/state.c.o
[ 15%] Building C object System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native-Static.dir/Users/cliffozewell/Desktop/Repos/corefx/src/Native/AnyOS/brotli/dec/state.c.o
[ 15%] Building C object System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native.dir/Users/cliffozewell/Desktop/Repos/corefx/src/Native/AnyOS/brotli/enc/backward_references.c.o
[ 16%] Building C object System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native-Static.dir/Users/cliffozewell/Desktop/Repos/corefx/src/Native/AnyOS/brotli/enc/backward_references.c.o
[ 17%] Building C object System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native.dir/Users/cliffozewell/Desktop/Repos/corefx/src/Native/AnyOS/brotli/enc/backward_references_hq.c.o
[ 17%] Building C object System.IO.Compre

**Comment by jkotas** [comment]
This was fixed by https://github.com/dotnet/corefx/pull/28768
