### ISSUE TITLE
[UWP] Investigate missing ConfigureAwaits in HttpClientHandler uap implementation

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#29517]
There are two awaits in the UAP implementation of HttpClientHandler:

https://github.com/dotnet/corefx/blob/9d38df5b1f63aeceec8832411ff6b6d4ab2133ed/src/System.Net.Http/src/uap/System/Net/HttpClientHandler.cs#L477

https://github.com/dotnet/corefx/blob/9d38df5b1f63aeceec8832411ff6b6d4ab2133ed/src/System.Net.Http/src/uap/System/Net/HttpClientHandler.cs#L500

I assume these should have `.ConfigureAwait(false)` added, but it's not clear to me if there's something special about these such that they were left off on purpose.  Someone should look into it and either add the missing calls or add comments.

cc: @davidsh

**Comment by davidsh** [comment]
>Someone should look into it and either add the missing calls or add comments.

It's a bug.  They should have .ConfigureAwait(false) on them.
