### ISSUE TITLE
Span<T> Memory<T> support linq

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/corefx#29525]
It would be great if the Span<T> Memory<T> supported linq;

IMHO this would improve the developer experience when slicing/dicing
data while preventing heap allocations

**Comment by stephentoub** [comment]
> while preventing heap allocations

It's quite rare to hear someone talk about using LINQ to avoid heap allocations.  Can you clarify how that would work?

**Comment by grahamehorner** [comment]
I was thinking eg. a where, orderby could return a linked list of pointers to the readonly span/memory; but not sure if it possible ?

**Comment by stephentoub** [comment]
That would require allocations.

**Comment by stephentoub** [comment]
If someone wants to use LINQ with `Memory<T>`, they can do so via `MemoryMarshal.ToEnumerable()`.  Given that, I'm going to close this. Thanks.
