### ISSUE TITLE
SEHException EFCore 2.0.2

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/corefx#29526]
Moved from https://github.com/aspnet/EntityFrameworkCore/issues/11877 filed by @mysticdotnet since this kind of exception is never thrown by EF.

When i use ef core as orm i have a sehexception

```
Exception message: sehexception
```
### Steps to reproduce
Steps are described in this issue: [#1413](https://github.com/OData/WebApi/issues/1413)

### Further technical details
EF Core version: (2.0.2)
Database Provider: (Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Windows 10
IDE: (Visual Studio 2017 15.6.7)

**Comment by ajcvickers** [comment]
Note from @divega in EF Core triage: the full information about the repro is in https://github.com/OData/WebApi/issues/1413. The OData team has already tried removing EF Core from the repro and the exception went away. Given it is an SEHException, I suspect it isn't a problem with EF Core, but if we run the repro we may be able to identify where it is coming from.

**Comment by karelz** [comment]
@ajcvickers FYI: This is not the right repo to route it - first-level analysis needs to happen first. Anyway, let's do it here to find out where to route it ...

@mysticdotnet Is it 100% repro? I see in other reports that more people were able to reproduce it ...
Did you try to get a dump? Did you attach native debugger to look at all first-level exceptions and to see the callstack?

**Comment by mysticdotnet** [comment]
@karelz The only exception details i have is this:
An unhandled exception of type 'System.Runtime.InteropServices.SEHException' occurred in Unknown Module. External component has thrown an exception. occurred

**Comment by karelz** [comment]
@mysticdotnet what about the other questions? Is it 100% repro? Can you try to get a dump, look at the full call stack?

**Comment by mysticdotnet** [comment]
@karelz Yes it is reproducible everytime, it's a sample code from the [odata repo](https://github.com/OData/WebApi/tree/master/samples/AspNetCoreODataSample.Web)
I download WindDbg, i launch the sample outside Visual Studio and i get this output:
[output.txt](https://github.com/dotnet/corefx/files/1983344/output.txt)

**Comment by mysticdotnet** [comment]
@karelz I migrate the [OData project](https://github.com/OData/WebApi) to .net core 2.1-rc1-final, now i have more detailed exception: 
![accessviolatonexception](https://user-images.githubusercontent.com/38808237/39991685-9cf001ec-5770-11e8-8a5e-d60f29608461.png)

**Comment by karelz** [comment]
This is not actionable for us at this moment. I will be happy to help once there is something to investigate (steps how to get exception callstack).
Let's track nailing down a repro in the original issue: https://github.com/OData/WebApi/issues/1413
