### ISSUE TITLE
DateTime.Parse has strange behavior!

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/corefx#29537]
DateTime.Parse(string s) has strange behavior!
According to docs at: https://docs.microsoft.com/ar-sa/dotnet/api/system.datetime.parse?view=netframework-4.7.1#System_DateTime_Parse_System_String_ :

>This overload attempts to parse s by using the formatting conventions of the current culture. The current culture is indicated by the CultureInfo.CurrentCulture property.

This means:

`var D = DateTime.Parse("1/15/2018");`

is equivilant to:

`var D = DateTime.Parse("1/15/2018", CultureInfo.CurrentCulture);`

So, that code will have different results on different PCs!.. On Windows with Arabic culture, that code will cause an exception, because this culture uses the format: "dd/MM/yyyy" and there is no 15th month!

This is a bad error prone design! This overload should work with the Invariant Culture ("en"), and if anyone wants to change that, uses the second param. in the other overloads.

I want to suggest to fix this behavior but I'm afraid of the famous reply: "This would be a breaking change!". I think it will worth a warring, and if it is fixed, IDE can offer to replace all old DateTime.Parse(s) with DateTime.Parse(s, CultureInfo.CurrentCulture) to maintain the same old behavior!
Otherwise, IDE should offer to replace any new DateTime.Parse(s) with DateTime.Parse(s, new CultureInfo("en"))

**Comment by MohammadHamdyGhanem** [comment]
@stephentoub 
There is a non-breaking solution that can be done at the IL level by translating the Parse(s) to Parse(s, c) where c is the exact culture used. This will preserve existing codes, let us use our cultures, and make the code run the same wayy on all PCs whatever their CurrentCutlure is. Is this possible?

**Comment by svick** [comment]
@MohammadHamdyGhanem I don't see how. How is your solution going to figure out if `Parse(s)` should be old-style or new-style?

**Comment by MohammadHamdyGhanem** [comment]
@svick 
I don't understand the question. Please quote the phrase that confuses you.

**Comment by Clockwork-Muse** [comment]
@MohammadHamdyGhanem - 

What they mean is....

How is the compiler/JIT going to know that `DateTime.Parse("Sonntag, 6. Mai 2018")` needs the German culture?  Or to look at your Arabic culture case, how will the system know what `DateTime.Parse("1/12/2018")` actually parses to - is the month December or January?

The answer is, they can't, the best they can do is attempt to use "current culture".

**Comment by MohammadHamdyGhanem** [comment]
@Clockwork-Muse 
1- Use the Invarient Culture as a standard.
2- Since "1" is rejected, use current culture as you want, but only on the programmer's PC, not at the the user's PC. 
What I say is to compile Parse(s) on a German Pc to Parse(s, new CultureInfo("de")) which will work exactly the same on all PCs whatever thier cultures, and German programmer still can write dates on his culture format like he wants. 
The current workarround is to ignore the Psrase(s) and use the Parse(s, new CultureInfo("de")) directly. My suggestion is to let the compiler do that for those ignorants who use Parse(s) and test it natively without expecting what will happen on a PC with different culture settings (which can exist in the same region by the way. Some Arabic PCs use the English or Frensh cultures only!)

**Comment by stephentoub** [comment]
No.  I understand you'd prefer the other one be the default, but this behavior is by design and desired by many, and this will not be marked obsolete.

**Comment by MohammadHamdyGhanem** [comment]
I agree. But the problem is that not all programmers are aware of that Parse(s) uses thier own culture!
see how much questions about that in stackoverflow:
https://www.google.com.eg/search?q=DateTime.Parse+causes+an+exception+site:stackoverflow.com&sa=X&ved=0ahUKEwikzp_5zvTaAhXCZFAKHQftDUgQrQIIMygEMAA&biw=853&bih=437&dpr=1.5
This is why I say it needs a warning.

**Comment by MohammadHamdyGhanem** [comment]
I think this https://github.com/dotnet/corefx/issues/29589 will be a proper solution.
