### ISSUE TITLE
AsnReader and AsnWriter support?

### ISSUE THREAD

**Issue by cskwrd** [dotnet/corefx#29542]
I was wondering why these classes are marked internal. Poking around, these classes (and maybe the Asn1Serializer) seem like they would be all that is required to truly generate certs from .NET core, solely from managed.

What am I missing? Why aren't these classes part of the public API?

**Comment by karelz** [comment]
The plan is to make them public, once we prove to ourselves the shape is right and they are complete and ready for public exposure. In 2.1 it is a prototype (see https://github.com/dotnet/designs/issues/11). Also see #21833 for tracking of the work.
cc @bartonjs

**Comment by cskwrd** [comment]
@bartonjs I don't have my code in front of me, but as I understand it the [CertificateRequest](https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.certificaterequest(v=vs.110).aspx) class doesn't let me create root or intermediate CA certs.  Is that correct?

**Comment by bartonjs** [comment]
@cskwrd There's a whole set of tests around building chained certificates (a self-signed cert which asserts that it is a CA, an intermediate CA, and end-entity certificates):

https://github.com/dotnet/corefx/blob/e160ef76df64a2114addf774a05af2f995f18bca/src/System.Security.Cryptography.X509Certificates/tests/CertificateCreation/CertificateRequestChainTests.cs#L96-L201

For test purposes it should be all you need.  (Production PKI would want to build CRLs and CDP extensions, as well as all the other things a production PKI system needs, like issuance logs.)

**Comment by cskwrd** [comment]
Wow! I spent all weekend looking for exactly that file. I guess sometimes it just takes someone hitting you on the head with it, haha! Thanks!
