### ISSUE TITLE
MemoryMappedFile is missing CreateFromFile overload that takes MemoryMappedFileSecurity 

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#29546]
IIRC we did this because ACLs were cut as they didn't work well cross-plat.  We lifted ACLs up to their own assembly and then added extension methods where appropriate.

This was problematic for the MemoryMappedFile API.  At the time (pre-net46) it only had a single method that could create a MMFile from a FileStream: https://apisof.net/catalog/System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile(FileStream,String,Int64,MemoryMappedFileAccess,MemoryMappedFileSecurity,HandleInheritability,Boolean).  By removing ACLs we removed this API.

At the time this was mitigated by creating a new API that served the purpose: https://apisof.net/catalog/System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile(FileStream,String,Int64,MemoryMappedFileAccess,HandleInheritability,Boolean)

That works fine for new code, but now that we support running old `net4x` code and giving it our best effort we fail.

In this case I can think of one somewhat hacky way to make this work.

Imagine we defined MemoryMappedFileSecurity as just a dumb object and throw platformnotsupported from the constructor.  We could do this in S.IO.MMF without adding an ACL dependency.  That way we can still support the overload, so long as someone was passing null.  We can do this in the implementation only as a means for supporting old desktop libraries.

Alternatively we could do a real implementation (only in Windows) on top of S.Security.AccessControl: it does look like this is already in MS.NetCore.App.

Finally, we could consider adding the API to the reference assembly as well.  I don't think this is a good idea as it would bring ACLs into reference surface area for NETCore.App and it'd become a landmine.  If we really wanted to expose this functionality for new code, then I would also add the type to AccessControl and create an extension method (similar to what we did for FileStream).

**Comment by JeremyKuhne** [comment]
Duplicate of #941
