### ISSUE TITLE
Trusted People certificate store behavior change with .NET core 2.1 (no longer allows untrusted roots)

### ISSUE THREAD

**Issue by mitchcapper** [dotnet/corefx#29563]
So there is a bit of a difference.  My understanding of trusted people is that certificates placed in there should be accepted as explicitly valid no matter what.
Granted placing a certificate in the "Current User/Trusted People" store never worked with .net Core, but "System Certificates/Trusted People" worked just fine in .NET 2.0.

So in .net 2.0 ```(tsk = (new HttpClient()).GetStringAsync("https://untrusted-root.badssl.com/")).Wait();``` works (after you grab that certificate and install it.

In .net 2.1 however that command (even with the certificate installed) will throw an error ```AuthenticationException: The remote certificate is invalid according to the validation procedure.```.

Self signed certificates (rather than simply an unknown CA) work fine as before installed in Trusted People:
```(tsk = (new HttpClient()).GetStringAsync("https://self-signed.badssl.com/")).Wait();```
in both .net 2.0 and .net 2.1.

There is no equivalent of Trusted People on platforms other than windows so it is a Windows bug, but as self signed certs still work in Trusted People this behavior is inconsistent (not TP being phased out as part of uniformity).  

If you are saying why would this matter? Just trust the untrusted CA?  Signal uses an untrusted certificate issued by an unpublished CA (https://textsecure-service.whispersystems.org/).

There are work around with .net core 2.1 thanks to the new certificate validation options on web socket(dotnet/corefx#28141), so it won't horridly break things but as this does not seem intended wanted to confirm.

**Comment by davidsh** [comment]
cc: @bartonjs

**Comment by davidsh** [comment]
@bartonjs I don't think this problem is specific to HttpClient.  HttpClient just uses normal X509 APIs to validate whether a certificate is 'good' or not. Perhaps something has changed in X509 for .NET Core 2.1?

**Comment by mitchcapper** [comment]
I can confirm it is also an issue with websockets (and clientwebsocket).

**Comment by stephentoub** [comment]
> Perhaps something has changed in X509 for .NET Core 2.1?

Presumably this is showing up via HttpClient between .NET Core 2.0 and 2.1 on Windows because of some difference between how WinHTTP worked and how SslStream/X509Certificate works?

**Comment by davidsh** [comment]
I'm not familiar with how "System Certificates/Trusted People" cert stores work in relation to the other "Trusted" cert stores.  I'm hoping @bartonjs can comment on this.  But perhaps the way that we can calling Windows SCHANNEL via SslStream (which client websocket and Http APIs will use) differs from how native WinHTTP calls SCHANNEL.

@mitchcapper Did "System Certificates/Trusted People" work with .NET Framework for these scenarios?  Can you try that?

**Comment by mitchcapper** [comment]
@davish confirmed .net 4.7.1 behaves like .net core 2.0, "System Certificates/Trusted People" non-self signed untrusted certs work fine.

**Comment by bartonjs** [comment]
Maybe WinHTTP uses CERT_CHAIN_ENABLE_PEER_TRUST, which is the only thing I am finding on the TrustedPeople store.

There are a lot of tricky corner cases for trying to emulate that behavior properly.  It's definitely not a thing we have support for in chain-building options.

**Comment by davidsh** [comment]
>Maybe WinHTTP uses CERT_CHAIN_ENABLE_PEER_TRUST, which is the only thing I am finding on the TrustedPeople store. There are a lot of tricky corner cases for trying to emulate that behavior properly. It's definitely not a thing we have support for in chain-building options.

The bug report also says this works as expected in .NET Framework which uses SslStream same as .NET Core.

>@davish confirmed .net 4.7.1 behaves like .net core 2.0, "System Certificates/Trusted People" non-self signed untrusted certs work fine.

So, it seems like there is something broken in .NET Core 2.1 in X509.

**Comment by bartonjs** [comment]
According to `git diff` the only changes for Windows X.509 in 2.0 to 2.1 were

1) remove everything that said "\#if uwp"
2) Remove a redundant P/Invoke declaration
3) Rewrite a foreach loop to a for loop
4) Change a Marshal.SizeOf to an unsafe sizeof
5) Fix X509Certificate2Collection.Find(..., validOnly: true) to use the user trust rules instead of machine trust rules.

If any of those would have altered chain building it would have been in a pretty catastrophic way, not toggling CERT_CHAIN_ENABLE_PEER_TRUST..

-----

So I built an attempted repro with .NET Framework 2.0.  The request FAILS in that version:

```
System.Net.HttpWebRequest, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
Received certificate with subject CN=*.badssl.com, O=BadSSL, L=San Francisco, S=California, C=US
Current policy errors: RemoteCertificateChainErrors
Certificate was expected cert? True
System.Net.WebException:
  The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. --->
    System.Security.Authentication.AuthenticationException:
        The remote certificate is invalid according to the validation procedure.
     at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
```

---

```C#
    class Program
    {
        private static X509Certificate2 s_existingCert;

        static void Main(string[] args)
        {
            X509Store store = new X509Store(StoreName.TrustedPeople, StoreLocation.CurrentUser);
            store.Open(OpenFlags.ReadOnly);

            const string match = "CN=*.badssl.com, O=BadSSL, L=San Francisco, S=California, C=US";

            foreach (X509Certificate2 cert in store.Certificates)
            {
                if (cert.SubjectName.Name == match)
                {
                    s_existingCert = cert;
                }
                else
                {
                    cert.Reset();
                }
            }

            store.Close();

            ServicePointManager.ServerCertificateValidationCallback = ServerCertificateValidationCallback;

            try
            {
                WebRequest request = WebRequest.Create("https://untrusted-root.badssl.com/");
                Console.WriteLine(request.GetType().AssemblyQualifiedName);
                Console.WriteLine(request.GetType().Assembly.CodeBase);
                WebResponse response = request.GetResponse();
                Console.WriteLine(response.ContentType);
            }
            catch (WebException we)
            {
                Console.WriteLine(we);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }

        private static bool ServerCertificateValidationCallback(
            object sender,
            X509Certificate certificate,
            X509Chain chain,
            SslPolicyErrors sslPolicyErrors)
        {
            Console.WriteLine($"Received certificate with subject {certificate.Subject}");
            Console.WriteLine($"Current policy errors: {sslPolicyErrors}");

            if (s_existingCert != null)
            {
                byte[] newCertData = certificate.GetRawCertData();
                byte[] matchData = s_existingCert.GetRawCertData();

                bool match = false;

                if (matchData.Length == newCertData.Length)
                {
                    match = true;

                    for (int i = 0; i < matchData.Length; i++)
                    {
                        if (newCertData[i] != matchData[i])
                        {
                            match = false;
                            break;
                        }
                    }
                }

                Console.WriteLine($"Certificate was expected cert? {match}");
            }

            return sslPolicyErrors == SslPolicyErrors.None;
        }
    }
```


This reinforces that nothing changed between netcoreapp20 and netcoreapp21.  This is the way that X509Chain has always behaved (and the way that CLR 2.0 (net20, net30, net35) apps continue to function).

**Comment by karelz** [comment]
Seems like unfortunate corner-case side-effect of moving to consistent implementation between OSs (SocketsHttpHandler). It is not blocking 2.1.

**Comment by davidsh** [comment]
I've investigated the behavior of this issue on .NET Framework and .NET Core (2.0, 2.1).

On .NET Framework, we never used 'Trusted People' store (either 'Local Machine' or 'Current User'.  So, the request would always fail.

On .NET Core 2.0 (which uses WinHttpHandler), the request would work if the certificate was placed in the 'Local Machine' 'Trusted People' store.  It would not work if it was in the 'Current User' 'Trusted People' store.

On .NET Core 2.1 the request fails (similar to .NET Framework).  .NET Core 2.1 started using SocketsHttpHandler as the default.

Now, this is where it gets interesting.

On .NET Core 2.0, if you use 'ServerCertificateCustomValidationCallback' and inspect the values passed in, you will see that SslPolicyErrors = SslPolicyErrors.None.  However, if you look at the actual X509Chain and check the first element of the ChainStatus, it will say PartialChain.
![image](https://user-images.githubusercontent.com/7684835/54561990-42192b80-4983-11e9-82c4-075b106961ed.png)

So, it doesn't really change the chain building operation.  It simply decides to not report the errors in SslPolicyErrors.  And what makes that interesting is that .NET is being used to build the X509Chain.  We are not getting it from WinHttp at this point.  WinHttp hands us a native PCCERT_CONTEXT object which we have to use to rebuild a chain using .NET code:

https://github.com/dotnet/corefx/blob/10c79df595b485f0998dded035f6f35e6279e50d/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpCertificateHelper.cs#L49

The .NET layer builds the chain and decides not to return any error from `chain.Build()`.  Looking at the array of elements in the Status array, there is a 'PartialChain' error.  Yet X509Chain.Build() doesn't return an error from trying to build a chain.  Not sure why it is doing this.

This isn't a difference in the code from .NET Core 2.1 to 2.2 in X509.  I can repro the same behavior using .NET Core 3.0 (master) and disable SocketsHttpHandler via AppContext switch.  I suspect there is something being returned in the PCCERT_CONTEXT (that we got from WinHttp) that somehow makes our .NET chain.Build() decide to return `true` despite having errors in the array of chain Status'.

**Comment by davidsh** [comment]
I have figured out what the differences are.

It turns out that the logic in .NET Framework and .NET Core SslStream is incorrect.  It is always adding SslPolicyErrors.RemoteCertificateChainErrors to the errors if there is any value in the X509Chain.Status array.

https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/src/System/Net/CertificateValidationPal.Windows.cs#L72-L76

This differs from the .NET Code used when WinHttpHandler is the being used.  In that code, SslPolicyErrors.RemoteCertificateChainErrors is only added to the error iff. the result of `chain.Build()` is false.

https://github.com/dotnet/corefx/blob/master/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpCertificateHelper.cs#L49-L52

When I fixed the code in SslStream to match the same behavior as the similar code in WinHttpHandler, the 'Local Machine' 'Trusted People' store scenario works.

So, it appears that native WinHttp is always doing the right thing.  When we need to invoke a .NET callback (for ServerCertificateCustomValidationCallback), we have .NET code to rebuild the chain.  And that code (which differs from SslStream) also seems to do the right thing.

So, I think the proper fix here is to fix SslStream in .NET Core.  .NET Framework will still have the behavior where it never works with the Trusted People store.

**Comment by davidsh** [comment]
The Unix implementation seems to already do the right thing by using the return value of chain.Build():

https://github.com/dotnet/corefx/blob/a4c110ca53c9284df2e2cbacd0b5247d06c8c7ee/src/Common/src/System/Net/Security/CertificateValidation.Unix.cs#L18-L25
