### ISSUE TITLE
MemoryStream CopyTo method does not work over REST if the file size is more (approx. >100KB)

### ISSUE THREAD

**Issue by Kalyan1989** [dotnet/corefx#29568]
Is this a Bug or Feature request?:
This is bug observed while writing REST service for downloading file to temporary location over server machine. The same code works fine on client side.

Steps to reproduce or link to a repro project:
Client code: Client.cs
```c#
 var FirmwareFilePath = "D:\\baccfg.dll";
 using (var memoryStream = new System.IO.MemoryStream())
            {
                using (var fileStream = new System.IO.FileStream(
                    FirmwareFilePath,
                    System.IO.FileMode.Open,
                    System.IO.FileAccess.Read))
                {
                    fileStream.CopyTo(memoryStream);
                }
                memoryStream.Position = 0;
          fwUpdateResult = networkService.PostFirmwareUpdate( RequestParam.Default, memoryStream);
 }
```
Server code: Server.cs
```c#
PostFirmwareUpdate(IRequestParam requestParam, Stream firmwareFileStream))
        {
            var tempFilePath = System.IO.Path.GetTempFileName();                                                                 
            using (var memoryStream = new System.IO.MemoryStream())
            {
                firmwareFileStream.CopyTo(memoryStream); 
//Control is not coming out of this CopyTo process and timeout is happening
                  memoryStream.Position = 0;
                using (var fileStream = new System.IO.FileStream(
                    tempFilePath,
                    System.IO.FileMode.Create,
                    System.IO.FileAccess.Write))
                {
                    memoryStream.WriteTo(fileStream);
                }
            }              
}
```
Description of the problem:
For .xml file size of 2KB, the code works fine and temp file is getting created at server.
But if I use file with extension like .dll, .7z with file size more than 100-200 KB, the code stucks in CopyTo function call.

[EDIT] Format code by @karelz

**Comment by stephentoub** [comment]
Your Server.cs code isn't using MemoryStream.CopyTo... it's using firmwareFileStream.CopyTo, and firmwareFileStream is typed as `Stream`.  What is the concrete type of that stream being passed in?  Where does it come from, i.e. who's calling PostFirmwareUpdate and with what argument?  It simply sounds like it's never hitting EOF, such that the read on the stream as part of the CopyTo never completes, so rather than this being a bug in CopyTo, it sounds like a problem in how the app is constructed with regards to whatever that stream is.

**Comment by Kalyan1989** [comment]
This is my client code from where I am calling server code: 
using (var memoryStream = new System.IO.MemoryStream())
            {
                using (var fileStream = new System.IO.FileStream(
                    FirmwareFilePath,
                    System.IO.FileMode.Open,
                    System.IO.FileAccess.Read))
                {
                    fileStream.CopyTo(memoryStream);
                }
                memoryStream.Position = 0;
                fwUpdateResult = networkService.PostFirmwareUpdate(
                    RequestParam.Default, memoryStream,
                    new FirmwareUpdateStub());
}

**Comment by stephentoub** [comment]
@Kalyan1989, the signatures of PostFirmwareUpdate don't match.  What is networkService here?  Presumably it's some kind of proxy that's been generated to enable remote invocation of a method in your server?  I'm not seeing a bug here yet in coreclr/corefx.

**Comment by Kalyan1989** [comment]
The problem was in my Gateway and synchronization which I was able to resolve. No issue from Core library.
Please close the issue.
