### ISSUE TITLE
partial view bug of MVC website in .NET Core 2.1 RC1

### ISSUE THREAD

**Issue by hez2010** [dotnet/corefx#29566]
I use .NET Core 2.1.300-rc1 to create a new MVC web app with individual authentication, then I use identity scaffolder (visual studio -> right click my project -> add -> new scaffolded item -> identity) and specify layout file with "~/Views/Shared/_Layout.cshtml" to generate identity related code in Areas/Identity automatically.

When I try to build, the compiler warns me that I need to use \<partial /> instead of @Html.Partial. Of course I can replace @Html.Partial to \<partial /> manually, but why not generate code with \<partial /> automatically at the beginning?

And then I run the website, when I navigated to Login/Register page in browser, I found that the _LoginPartial View could not be loaded correctly that it still remained \<a asp-area="Identity" asp-page="/Account/Login">\</a> but not \<a href="/Identity/Account/Login">\</a> in HTML source so that I could not click Login or Register again. Also, I changed the navbar style in _LoginPartial.cshtml but when I navigated to Login/Register page, it restored to original styles.

Normally (in home page): 
![1](https://user-images.githubusercontent.com/14960345/39738273-c877d280-52bc-11e8-9910-5713f9ecd59c.png)

In Login/Register page:
![2](https://user-images.githubusercontent.com/14960345/39738272-c82af82a-52bc-11e8-9a10-937d111a9013.png)

But after I changed the code in _Layout.cshtml:
\<partial name="_LoginPartial" />   ----->   \<partial name="_LoginPartial.cshtml" />, it works again. 

![3](https://user-images.githubusercontent.com/14960345/39738348-29041e10-52bd-11e8-961c-51675cf87edd.png)

Hope that you can fix this bug, thanks!

**Comment by kasper3** [comment]
this belongs to https://github.com/aspnet/razor or https://github.com/aspnet/mvc

**Comment by karelz** [comment]
This issue was moved to aspnet/Mvc#7768
