### ISSUE TITLE
Add DateTime.ParseInvariant(string) method

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/corefx#29589]
# The Problem:
DateTime.Parse(string) uses CultureInfo.CurrentCulture to parse the given string. This is suitable for parsing a date written by a user in UI, but it causes a a problem when used in to parse a string date provided by the programmer himself, because he uses his own culture, and this causes an exception on other PCs with different cultures.

# Solution:
In #29537, I suggested some solutions to change this behavior or give a warning but it turned out to be a breaking code. So, the only way to address this issue is to add a new DateTime.ParseInvariant(string) method that uses the invariant culture to parse the date string. The existence of this method will make it easy to parse dates stored in App resources, files or database. It will also bring to the programmers attention that doesn't DateTime.Parse(string) behave as he would expect. Not all programmers are aware of that Parse(string) uses their own culture! see how much questions about that in stackoverflow:
https://www.google.com.eg/search?q=DateTime.Parse+causes+an+exception+site:stackoverflow.com&sa=X&ved=0ahUKEwikzp_5zvTaAhXCZFAKHQftDUgQrQIIMygEMAA&biw=853&bih=437&dpr=1.5
 specially these two:
https://stackoverflow.com/questions/19487356/weird-datetime-parsing-behaviour
https://stackoverflow.com/questions/42717939/datetime-parseexact-different-behaviour-on-other-server
Thing can be better if you also mark DateTime.Parse(sting) as obsolete and add a new DateTime.ParseLocal(string) method instead.
# Implementation:
```
public static DateTime ParseInvariant(String s) { 
  return (DateTimeParse.Parse(s , CultureInfo.InvariantCulture, DateTimeStyles.None)); 
}

public static bool TryParseInvariant(string s, out DateTime result)
{
   return DateTimeParse.TryParse(s, CultureInfo.InvariantCulture, DateTimeStyles.None, out result);
}

public static DateTime ParseLocal(String s) {
            return (DateTimeParse.Parse(s, DateTimeFormatInfo.CurrentInfo, DateTimeStyles.None));
}

public static bool TryParseLocal(string s, out DateTime result)
{
   return DateTimeParse.TryParse(s, DateTimeFormatInfo.CurrentInfo, DateTimeStyles.None, out result);
}
```

**Comment by stephentoub** [comment]
Why would a new method be valuable here when a dev can just do:
```
DateTime.Parse(s, CultureInfo.InvariantCulture);
```
? It doesn't add functionality, and I don't think it improves discoverability.

**Comment by MohammadHamdyGhanem** [comment]
@stephentoub 
1- This is the only way to fix the bad choice of making Parse(s) depend on unknown culture.
2- It is a shorcut verson of DateTime.Parse(s, CultureInfo.InvariantCulture)
3- It will appear in the auto complete list and this will inform every programmer that there is something not right about the Parse(s) method!
4- We need ParseInvariant and TryParseInvariant only. User already provide the exact format to ParseExact and TryParseExact.

**Comment by stephentoub** [comment]
> 1- This is the only way to fix the bad choice of making Parse(s) depend on unknown culture.

I disagree it was a bad choice.

> 2- It is a shorcut version of DateTime.Parse(s, CultureInfo.InvariantCulture)

It's not much of a shortcut.  You're talking about the difference between:
```C#
DateTime.Parse(s, CultureInfo.InvariantCulture);
```
and
```C#
DateTime.ParseInvariant(s);
```
and even if it were, the current form is already very short and easily understood.

> 3- It will appear in the auto complete list and this will inform every programmer that there is something not right about the Parse(s) method!

Again, I disagree that "something is not right".  It also adds conceptual overhead.  To this day I see both `ToLower(CultureInfo)` and `ToLowerInvariant()` and have to remind myself what if anything is the difference between `ToLower(CultureInfo.InvariantCulture)` and `ToLowerInvariant()`.  To me, it was a mistake having both of those, and now you're suggesting adding that same thing in a new place, so while you believe the current thing is a mistake, I believe what's being suggested is a mistake.  Everyone has their own perspective on these things.

> 4- We need ParseInvariant and TryParseInvariant only

So just for `string`?  What about `ReadOnlySpan<char>`?  What about `NumberStyle`?  What about `DateTimeOffset`?  If `Parse` is the opposite of `ToString`, why wouldn't `ToString` need a similar treatment for consistency?  Etc.

**Comment by MohammadHamdyGhanem** [comment]
@stephentoub 
I want programming languages to be as human as possible. I don't want programers to be as robotic as possible to fit the perfect performance of the programming language. It is the job of the compiler to optimize the performance. 
We have millions of classes, properties and methods and it is difficult to read docs about all of them and remember all the notes and warrnings. A good design should be easy to remember and understand by just a look at the name, and hard to cause hummen mistaks like thosands who use Parse(s) to add some dates in their code and then cry about the failure of their apps on other machines! 
I see no problem in having some similar methods. I myself love languses that gave me more than one way to do the same thing.
Any way, this is my suggestion. If you find it of any value conseder it, otherwise let it go.
Thanks.

**Comment by tarekgh** [comment]
I am closing this as the framework already providing APIs covering all needed scenarios.
