### ISSUE TITLE
After Docker image update to microsoft/dotnet:2.1-sdk. Receiving System.IO.IOException: Method not found: 'System.Memory`1<!0>

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#29593]
Copying issue from https://github.com/Microsoft/dotnet/issues/738

> From @jdwilly2001:
The application was running last week, and now is failing. I am attempting to buidl the docker image with the same code that was confirmed running and now I cannot get the application to serve a basic healthcheck url. Are there any issues with the published 2.1-sdk image?

> info: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[14]
Connection id "0HLDKUV7FGMOP" communication error.
System.IO.IOException: Method not found: 'System.Memory1<!0> System.Memory1.CreateFromPinnedArray(!0[], Int32, Int32)'. ---> System.MissingMethodException: Method not found: 'System.Memory1<!0> System.Memory1.CreateFromPinnedArray(!0[], Int32, Int32)'.
at System.Buffers.MemoryPoolBlock..ctor(SlabMemoryPool pool, MemoryPoolSlab slab, Int32 offset, Int32 length)
at System.Buffers.SlabMemoryPool.AllocateSlab()
at System.Buffers.SlabMemoryPool.Lease()
at System.IO.Pipelines.Pipe.AllocateWriteHeadUnsynchronized(Int32 sizeHint)
at System.IO.Pipelines.Pipe.GetMemory(Int32 sizeHint)
at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives()
at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
--- End of inner exception stack trace ---

> From @anandtpatel: 
microsoft/dotnet 2.1-sdk image was working fine on Friday(May 4th). Started giving above error since yesterday(May 7).

cc @pakrym, @weshaggard, @ericstj, @natemcmaster, @dagood, @mmitche 
 

I am not sure why MemoryPoolBlock is looking for Memory\<T\>.CreateFromPinnedArray. It was moved to MemoryMarshal quite a while ago, [here](https://github.com/dotnet/corefx/pull/28992):
**src:** https://github.com/dotnet/corefx/blob/release/2.1/src/Common/src/CoreLib/System/Runtime/InteropServices/MemoryMarshal.cs#L264
**ref:** https://github.com/dotnet/corefx/blob/release/2.1/src/System.Memory/ref/System.Memory.cs#L526

I checked the System.Memory package from MyGet (both [RC](https://www.nuget.org/packages/System.Memory/4.5.0-rc1) and [RTM](https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Memory/4.5.0-rtm-26508-03) versions have this method on MemoryMarshal).

MemoryPoolBlock is referencing the correct method:
https://github.com/aspnet/Common/blob/release/2.1/shared/Microsoft.Extensions.Buffers.Sources/MemoryPoolBlock.Release.cs#L30

The dependencies seem correct as well: https://github.com/aspnet/Universe/blob/release/2.1/build/dependencies.props#L18

**I don't know how exactly aspnet and the dotnet sdk is built**, but there might be a package mismatch somewhere up stack that could be causing this issue. Microsoft.NetCore.App version information would help.

**Comment by ahsonkhan** [comment]
@jdwilly2001, @anandtpatel - it is possible there are mismatch assemblies somewhere.

Can you please share the version of the ,NET Core runtimes installed (post the output of `dotnet.exe --info`)?

**Comment by ericstj** [comment]
Look at the project.assets.json instead, that will give you a complete picture.  Seems to me that this app is using an old copy of MemoryPoolBlock.  Probably has a reference to the old package (or wasn’t even recompiled / published).

**Comment by natemcmaster** [comment]
We published 2.1.0-rc1 yesterday. My guess is your app is compiled against 2.1.0-preview2. To keep it working on preview2, use `microsoft/dotnet:2.1.300-preview2-sdk`. When you are ready to update to 2.1.0-rc1, you can go back to using `microsoft/dotnet:2.1-sdk`. We are not expecting any breaking changes anymore in the 2.1 release train.

**Comment by anandtpatel** [comment]
@natemcmaster 

Yes, I am using 2.1.0-preview2 hence i am facing this issue. after making changes suggested by you, it working.

**Comment by karelz** [comment]
Is there anything left for us to do, or can it be closed then?

**Comment by ahsonkhan** [comment]
I think it can be closed. @jdwilly2001, feel free to re-open if @natemcmaster's fix doesn't work for you.
