### ISSUE TITLE
Why can't override NetworkStream.ReadAsync(Memory<byte> buffer, CancellationToken cancellationToken)

### ISSUE THREAD

**Issue by sawachika-kenji** [dotnet/corefx#29598]
```
public class TestStream : NetworkStream
    {
public override ValueTask<int> ReadAsync(Memory<byte> buffer, CancellationToken cancellationToken)
        {
            return base.ReadAsync(buffer, cancellationToken);
        }
}
```
But at base.ReadAsync method enter F12 into Stream.ReadAsync(Memory<byte> buffer, CancellationToken cancellationToken = default(CancellationToken))

I checked the source code, NetworkStream does contain "ValueTask<int> ReadAsync(Memory<byte> buffer, CancellationToken cancellationToken)"

C:\Users\admin>dotnet --version
2.1.300-rc1-008673

**Comment by svick** [comment]
Does your code behave the way you expect? If it does, then that sounds like this is an issue with how <kbd>F12</kbd> behaves in VS. If that is the case, I think [the Roslyn repo](https://github.com/dotnet/roslyn) would be a better place for this issue.

**Comment by sawachika-kenji** [comment]
supplement:
Microsoft Visual Studio Community 2017 Preview
VisualStudio.15.Preview/15.8.0-pre.1.1+27705.2000

runtimeconfig.json:
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.1.0-rc1"
    }
  }
}

**Comment by karelz** [comment]
@sawachika-kenji how do you know the code runs into Stream.ReadAsync? Optimized code often shares code for same methods. Is it possible both implementations are the same and debugger points you to the other one?
Can you create a repro (without debugger) demonstrating that wrong code is called (i.e. wrong result / exception happens)?

**Comment by sawachika-kenji** [comment]
@karelz 
I made the following settings and entered the .net core source code https://github.com/aspnet/Docs/issues/4155
I found that the next step in base.ReadAsync(buffer, cancellationToken) is Stream.ReadAsync(Memory buffer, CancellationToken cancellationToken = default(CancellationToken)) instead of NetworkStream.ReadAsync(Memory buffer, CancellationToken cancellationToken = default(CancellationToken))

And at base.ReadAsync line F12 will goto  Stream.ReadAsync(Memory buffer, CancellationToken cancellationToken = default(CancellationToken))

And at NetworkStream class F12 ,can't found method ReadAsync(Memory buffer, CancellationToken cancellationToken = default(CancellationToken))

**Comment by sawachika-kenji** [comment]
No example is required, the following code is an example:
```
public class TestStream : NetworkStream
    {
public override ValueTask<int> ReadAsync(Memory<byte> buffer, CancellationToken cancellationToken)
        {
            return base.ReadAsync(buffer, cancellationToken);
        }
}
```

**Comment by sawachika-kenji** [comment]
https://github.com/dotnet/corefx/blob/48ce3254e28f2dae2d9a5efe7dd42cfab119d287/src/System.Net.Sockets/src/System/Net/Sockets/NetworkStream.cs#L748

At NetworkStream class F12 ,can't found method ReadAsync(Memory<byte> buffer, CancellationToken cancellationToken)

**Comment by stephentoub** [comment]
It's because the new overrides are missing from NetworkStream in the ref assembly.

**Comment by stephentoub** [comment]
@weshaggard, @ericstj, can/should we augment that reverse ref tool we run as part of the build to flag places where a public non-sealed class overrides a member and that override is missing from the ref?

**Comment by weshaggard** [comment]
>@weshaggard, @ericstj, can/should we augment that reverse ref tool we run as part of the build to flag places where a public non-sealed class overrides a member and that override is missing from the ref?

This has always been a sticky issue that we have mostly brushed over because we haven't found real issues caused by it. Now we have found one. I think your suggestion is can help but it will only catch the assemblies we can run the reverse API check on which are the ones that are 1:1 with there implementation. At any rate it is worth filing an issue for (or if you are up for it submitting a PR :)).

**Comment by sawachika-kenji** [comment]
So is there any way I can now call NetworkStream.ReadAsync(Memory<byte> buffer, CancellationToken cancellationToken)?

**Comment by stephentoub** [comment]
> So is there any way I can now call NetworkStream.ReadAsync(Memory buffer, CancellationToken cancellationToken)?

Yes, just not from a derived type.
