### ISSUE TITLE
Unexpected logic (if) behavior when including async boolean.

### ISSUE THREAD

**Issue by electricessence** [dotnet/corefx#29608]
When debugging the following code, with `readStarted` equal to `true`, the entire `if` block is negated. (`useReadAsync` is also `true`.)
https://github.com/electricessence/Open.Database.Extensions/blob/9ece00f391d9faf6ff04817428ffc999ca6af57d/Extensions.Retrieve.cs#L187-L194
```cs
if (readStarted 
|| useReadAsync
    ? await reader.ReadAsync(t)
    : (!t.IsCancellationRequested && reader.Read()))
{
    do
    {
        buffer.Enqueue(handler(reader));
    }
    while (useReadAsync
        ? await reader.ReadAsync(t)
        : (!t.IsCancellationRequested && reader.Read()));
}
```

If I change the code to the following, it works correctly every time.
https://github.com/electricessence/Open.Database.Extensions/blob/dbbe0707f803836468e19c7fc294811a38b0fdef/Extensions.Retrieve.cs#L188-L202
```cs
if (!readStarted)
	readStarted = useReadAsync
		? await reader.ReadAsync(t)
		: (!t.IsCancellationRequested && reader.Read());

if (readStarted)
{
	do
	{
		buffer.Enqueue(handler(reader));
	}
	while (useReadAsync
		? await reader.ReadAsync(t)
		: (!t.IsCancellationRequested && reader.Read()));
}
```

The logic is fundamentally the same but the behavior is not.  This is the first time I've encountered something like this.  A bit scary really.  Would love some more insight.

This is being tested/debugged under an ASP.NET Core 2.0 application using Visual Studio 15.6.7 and the behavior persists in production environments.

**Comment by stephentoub** [comment]
`||` has higher operator precedence than `?`, so your code:
```C#
if (readStarted 
|| useReadAsync
    ? await reader.ReadAsync(t)
    : (!t.IsCancellationRequested && reader.Read()))
```
is equivalent to:
```C#
if ((readStarted 
|| useReadAsync)
    ? await reader.ReadAsync(t)
    : (!t.IsCancellationRequested && reader.Read()))
```
not to:
```C#
if (readStarted 
|| (useReadAsync
    ? await reader.ReadAsync(t)
    : (!t.IsCancellationRequested && reader.Read())))
```

**Comment by electricessence** [comment]
Oh wow.  I feel dumb.  Sorry to bother you with this one.
Of course that's why.

**Comment by electricessence** [comment]
Brain teaser for the week:
```cs
a ? b : c || d ? e : f // == ???
```
