### ISSUE TITLE
[SQL Ops Studio] - Incorrect Client Process IDs passed to SQL Engine

### ISSUE THREAD

**Issue by pradm** [dotnet/corefx#29609]
In relation to the Git Hub Issue filed for SQL Ops Studio https://github.com/Microsoft/sqlopsstudio/issues/1380 , As per SQL engineering teams investigation "This is an issue with SqlClient in .Net Core. SqlClient in .Net Core generates a random number for Process Id. 
On .Net Framework SqlClient used kernel32.dll for this information. In .Net Core, SqlClient could use System.Diagnostics.Process to get the process Id. "

It would be of great help if this can be fixed.

**Comment by saurabh500** [comment]
Devnote: SqlClient generates a random process Id at https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/TdsParserStaticMethods.cs#L60 

SqlClient could possibly use https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.id?view=netframework-4.7.1#System_Diagnostics_Process_Id

**Comment by keeratsingh** [comment]
Closing, fixed by #30344
