### ISSUE TITLE
CryptographicAttributeObjectCollection public API breaking change

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/corefx#29607]
Hello,
I need to reuse corefx System.Security.Cryptography sources in Mono. Using [API Diff tool](https://jenkins.mono-project.com/job/test-mono-pull-request-amd64/14156//Public_API_Diff/) I see some  public API breaking change in [CryptographicAttributeObjectCollection](https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/CryptographicAttributeObjectCollection.cs#L145-L159).
Could you please help me find out why this change was introduced?
Related to https://github.com/mono/mono/pull/8629

**Comment by stephentoub** [comment]
@bartonjs, was there a reason we changed these members from implicitly implementing the interface to explicitly implementing the interface?

**Comment by bartonjs** [comment]
That happened during 1.0, and I remember there was some member hiding going on then.  Most of that hiding was undone by netstandard2.0; but these types aren't part of netstandard.

So there's probably not a reason to keep them as explicit implementations.
