### ISSUE TITLE
API Question regarding `SslClientAuthenticationOptions` and `SslServerAuthenticationOptions`

### ISSUE THREAD

**Issue by baulig** [dotnet/corefx#29610]
I saw that you recently added two new classes [`SslClientAuthenticationOptions`](https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/src/System/Net/Security/SslClientAuthenticationOptions.cs) and [`SslServerAuthenticationOptions`](https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/src/System/Net/Security/SslServerAuthenticationOptions.cs).

These actually share quite a few properties.  Is there a reason why you didn't put those shared properties into a shared base class, such as for instance `SslAuthenticationOptions`?

There is actually a class called [`SslAuthenticationOptions`](https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/src/System/Net/Security/SslAuthenticationOptions.cs), but it is internal and contains everything from both classes.

**Comment by davidsh** [comment]
There were no public APIs that we added in .NET Core 2.1 which would use a base class of `SslAuthenticationOptions`. So, that class was not made public.

You can review the API proposal/design/approval and the discussions from this issue:  #23177
