### ISSUE TITLE
Microsoft.Win32.SystemEventsTests.InvokeOnEventsThreadTests.InvokeOnEventsThreadRunsAsynchronously fails on netfx

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#29634]
See https://mc.dot.net/#/user/hughbe/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/7f39280d9d2224eb02e98663815699bceb4d6c29/workItem/Microsoft.Win32.SystemEvents.Tests/analysis/xunit/Microsoft.Win32.SystemEventsTests.InvokeOnEventsThreadTests~2FInvokeOnEventsThreadRunsAsynchronously

Failed on Windows.10.Amd64.ClientRS4.Open-x86-Release

```
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Assert.True() Failure
Expected: True
Actual:   False
Stack Trace :
   at Microsoft.Win32.SystemEventsTests.InvokeOnEventsThreadTests.InvokeOnEventsThreadRunsAsynchronously() in D:\j\workspace\windows-TGrou---2a8f9c29\src\Microsoft.Win32.SystemEvents\tests\SystemEvents.InvokeOnEventsThread.cs:line 23
```

**Comment by danmosemsft** [comment]
@ericstj

**Comment by ericstj** [comment]
I see, we just need to multiply that guy by ExpectedEventMultiplier.
https://github.com/dotnet/corefx/blob/master/src/Microsoft.Win32.SystemEvents/tests/SystemEvents.InvokeOnEventsThread.cs#L22

Machine must be running tests sloooowly.
