### ISSUE TITLE
Namespace mismatch regarding `StringBuilderCache`.

### ISSUE THREAD

**Issue by baulig** [dotnet/corefx#29645]
I am currently trying to add a few more CoreFX classes to Mono and stumbled upon a namespace problem with the internal `StringBuilderCache` class:

- The class is defined https://github.com/dotnet/corefx/blob/63e70fa6b1bc6b7175467e0ad16cbbf4c44f8d83/src/Common/src/System/IO/StringBuilderCache.cs#L41 here in the `System.IO` namespace.
- This file https://github.com/dotnet/corefx/blob/103639b6ff5aa6ab6097f70732530e411817f09b/src/Common/src/CoreLib/System/Collections/Generic/KeyValuePair.cs#L24 only has `using System.Text`.

How is this supposed to even compile?

**Comment by danmosemsft** [comment]
The KVP is mirrored from Corelib where it is using coreclr\src\mscorlib\src\System\Text\StringBuilderCache.cs which is in System.Text.

The corefx\src\Common\src\System\IO\StringBuilderCache.cs needs to be reconciled with the corelib version, then CoreFX can consume that one instead and the IO one can be deleted.

**Comment by marek-safar** [comment]
@danmosemsft @karelz @stephentoub great collaboration, I really appreciate your prompt resolution of issues like this one!

**Comment by danmosemsft** [comment]
@marek-safar keep sending us them!
