### ISSUE TITLE
A fatal error occurred, the required library hostfxr.dll could not be found at C:\Program Files\dotnet\

### ISSUE THREAD

**Issue by HowardEdidin** [dotnet/corefx#29659]
D:\>dotnet new -i Microsoft.Azure.IoT.Edge.Function
A fatal error occurred, the required library hostfxr.dll could not be found at C:\Program Files\dotnet\

D:\>dotnet new aziotedgefunction -n FilterFunction -r <your container registry address>/filterfunction
The system cannot find the file specified.

D:\>dotnet new aziotedgefunction -n FilterFunction -r hl7fhir.azurecr.io/filterfunction
A fatal error occurred, the required library hostfxr.dll could not be found at C:\Program Files\dotnet\

D:\>A

**Comment by karelz** [comment]
This issue was moved to dotnet/core-setup#4143
