### ISSUE TITLE
Crossplatform use SDL. 

### ISSUE THREAD

**Issue by chiddekel** [dotnet/corefx#29685]
**App-models** -- .NET Core does not support all the .NET Framework app-models, in part because many of them are built on Windows technologies, such as WPF (built on top of DirectX). The console and ASP.NET Core app-models are supported by both .NET Core and .NET Framework. 

Problem: .NET Core support for all .NET Framework app-models. 

[Solution]
Resolve the problem would be a support SDL as the TOP layer.
By, control logic - the switch will be - upon detecting Operating system.
And use alternatives SDL TOP layer, and Sound Graphic, etc 
switch depending on which OS is the app running.

SDL -  is a cross-platform development library designed to provide low-level access to audio, keyboard, mouse, joystick, and graphics hardware via OpenGL and Direct3D.
https://www.libsdl.org/

Sound - OpenAl
https://castle-engine.io/openal.php
support native mode, using default device on OS.

3D Graphics -  OpenGL
http://lazyfoo.net/tutorials/OpenGL/index.php#Hello%20GLSL

Simulation Physics Engine - bullet-physics
https://github.com/bulletphysics

**Comment by EgorBo** [comment]
If you need SDL you can just find some C# bindings for it (e.g. https://github.com/flibitijibibo/SDL2-CS).
But I don't think it's a good idea to build UI Frameworks on top of it, it's more like a good foundation for game engines.

**Comment by karelz** [comment]
Closing as wrappers for libraries don't need to go into CoreFX, unless it is abstracting core OS functionality
For SDL library, the linked C# wrapper seems sufficient.

BTW: Last week we have announced WPF and WinForms coming to .NET Core 3.0 for Windows-only: https://blogs.msdn.microsoft.com/dotnet/2018/05/07/net-core-3-and-support-for-windows-desktop-applications

**Comment by chiddekel** [comment]
This is good news - but NET Core does not support all the .NET Framework app-models, in part because many of them are built on Windows technologies, such as WPF (built on top of DirectX). SDL can be solution for Linux and Mac - WPF and WinForms implementation for dose systems.

**Comment by karelz** [comment]
If you are interested in cross-platform UI, check out various community projects, e.g. Avalonia: https://github.com/AvaloniaUI/Avalonia

**Comment by chiddekel** [comment]
Great it ability to contribute:) I hope it's production ready. Thanks and have a great week!
