### ISSUE TITLE
Thread list

### ISSUE THREAD

**Issue by konraddysput** [dotnet/corefx#29680]
Hey,

I try to found a way to list all available threads and stracktraces in .NET. Right now I use Microsoft.Diagnostics.Runtime library, but library supports only Windows. For diagnostic purpose its necessary to get all stack traces from all threads that application use. 

Thanks a lot!

**Comment by danmosemsft** [comment]
@mikem8361 can you help?

**Comment by konraddysput** [comment]
@mikem8361 Actually I only find solution with CLRMD and tried via C++ code: https://msdn.microsoft.com/en-us/library/windows/desktop/ms686746(v=vs.85).aspx
but I failed too :(

**Comment by mikem8361** [comment]
I'm assuming you tried the C++ on Windows? The API in the above link are Windows only. 

Currently CLRMD is desktop/Windows only.  If we get enough interest and find the dev resources, someday it may be port to .NET Core/Linux, etc.

**Comment by konraddysput** [comment]
Its still better to have full support for Windows than not having thread list and stack traces for any platform. Its the reason why I share these links with you. 

If you get me enough resources or some knowledge how to do this I could write a code and share with you - only I need information "how".
