### ISSUE TITLE
System.IO.Pipelines.ReadResult should be readonly

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#29683]
So it can be efficiently passed with `in`
```csharp
public readonly struct ReadResult
{
    internal readonly ReadOnlySequence<byte> _resultBuffer;
    internal readonly ResultFlags _resultFlags;
}
```

/cc @davidfowl @pakrym

**Comment by benaadams** [comment]
Luckily changing it isn't breaking change :)

**Comment by benaadams** [comment]
They'd need to change

**Comment by CodeTherapist** [comment]
@benaadams Thanks for the information.
I'm still interested doing this task - let me do another PR for it, with the additional changes to Pipe.cs.

**Comment by benaadams** [comment]
```csharp
private void GetReadResult(ref ReadResult result)
```
Should probably be 
```csharp
private ReadResult GetReadResult()
```

**Comment by pakrym** [comment]
That was done because of performance reasons (to avoid copying struct and decrease stack size). So it would be interesting to see perf impact.

**Comment by benaadams** [comment]
Ah cos `ReadOnlySequence<byte>` is chunky...

**Comment by benaadams** [comment]
`private void GetReadResult(out ReadResult result)` would have similar effect to `ref`?

**Comment by ahsonkhan** [comment]
> can you help here?

Sure, I can try :)

> how could I check the perf impact of my change?

If you have a performance test that captures the scenario you are interested in, you can run it by following the steps here:
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/performance-tests.md

You would have to write the relevant performance test first (if one doesn't exist). Let me know if you have any questions.

**Comment by CodeTherapist** [comment]
Thanks to everyone that is elaborating this with me.

@ahsonkhan So far, there is no perf test for this project at all. When I understand you correctly, I would need to create it for my changed code *and* for the previous code (master), right? Otherwise I can't see how we could compare both implementations… Should we create an additional issue for the perf work or should this be tracked with this one?

**Comment by CodeTherapist** [comment]
Thanks to everyone that is helping me on that.

@pakrym 
Now I did a performance test accordingly to the documentation and it looks like that there is no performance impact by this change. Please let me know what you think about the [perf test](https://github.com/CodeTherapist/corefx/blob/29683_System.IO.Pipelines.ReadResult_should_be_readonly/src/System.IO.Pipelines/tests/Performance/Perf.Pipe.cs). When the perf test is good, I would add it to the PR.

**With my changes** ([Branch](https://github.com/CodeTherapist/corefx/commit/e5936c07ea6b5abb0e02dce67598a69dd59cd37c))

 System.IO.Pipelines.Performance.Tests.dll     | Metric   | Unit | Iterations | Average | STDEV.S |   Min |   Max
:--------------------------------------------- |:-------- |:----:|:----------:| -------:| -------:| -----:| -----:
 System.IO.Pipelines.Tests.Perf_Pipe.ReadAsync | Duration | msec |    1000    |   0.015 |   0.017 | 0.009 | 0.213

**Without my changes** ([Branch](https://github.com/CodeTherapist/corefx/commit/b2f7228c2eb8ea5eaa29e64cf7e27b63160716e2))

 System.IO.Pipelines.Performance.Tests.dll     | Metric   | Unit | Iterations | Average | STDEV.S |   Min |   Max
:--------------------------------------------- |:-------- |:----:|:----------:| -------:| -------:| -----:| -----:
 System.IO.Pipelines.Tests.Perf_Pipe.ReadAsync | Duration | msec |    1000    |   0.015 |   0.018 | 0.009 | 0.268

**Comment by ahsonkhan** [comment]
@CodeTherapist, you need to add an inneriterationcount (attribute on the benchmark and a a loop). The tests should take 1+ ms. Otherwise, the results are too noisy to see a difference.

**Comment by CodeTherapist** [comment]
@ahsonkhan Thanks. Is that correct?

**With my changes** [(Branch)](https://github.com/CodeTherapist/corefx/commit/dabb9abebb2ca4a44384b12b77196b7416174b14)

System.IO.Pipelines.Performance.Tests.dll     | Metric   | Unit | Iterations |  Average | STDEV.S |      Min |      Max|
--------------------------------------------- |:-------- |:----:|:----------:| --------:| -------:| --------:| --------|
System.IO.Pipelines.Tests.Perf_Pipe.ReadAsync | Duration | msec |     4      | 2510.920 |   7.606 | 2503.556 | 2517.946|

**Without my changes** [(Branch)](https://github.com/CodeTherapist/corefx/commit/f69983cfcd94883c95f6e23a787d2634a1acbad2)

 System.IO.Pipelines.Performance.Tests.dll     | Metric   | Unit | Iterations |  Average | STDEV.S |      Min |      Max
:--------------------------------------------- |:-------- |:----:|:----------:| --------:| -------:| --------:| --------:
 System.IO.Pipelines.Tests.Perf_Pipe.ReadAsync | Duration | msec |     4      | 2584.346 |  12.623 | 2572.661 | 2602.189

**Comment by pakrym** [comment]
Good job!

There is a slight adjustment you can do to isolate scenario even more:

Move

```
await writer.WriteAsync(new byte[] { 0, 0, 0, 0 });
await writer.FlushAsync();
```

outside the loop and call `reader.AdvanceTo(result.Buffer.Start);`. This way you are going to eliminate any writing overhead and just exercise sync reading.

**Comment by CodeTherapist** [comment]
@pakrym Thanks for the hint - I did the changes.

**With my changes** ([Branch](https://github.com/CodeTherapist/corefx/commit/7cce1768c6a16f145d1637019890f147231cb4b5))

 System.IO.Pipelines.Performance.Tests.dll     | Metric   | Unit | Iterations | Average | STDEV.S |   Min |   Max
:--------------------------------------------- |:-------- |:----:|:----------:| -------:| -------:| -----:| -----:
 System.IO.Pipelines.Tests.Perf_Pipe.ReadAsync | Duration | msec |    100     |   1.241 |   0.009 | 1.235 | 1.295

**Without my changes** ([Branch](https://github.com/CodeTherapist/corefx/commit/c65915a4d59ddec65d771e4bdea83600c8db8bce))

 System.IO.Pipelines.Performance.Tests.dll     | Metric   | Unit | Iterations | Average | STDEV.S |   Min |   Max
:--------------------------------------------- |:-------- |:----:|:----------:| -------:| -------:| -----:| -----:
 System.IO.Pipelines.Tests.Perf_Pipe.ReadAsync | Duration | msec |    100     |   1.179 |   0.009 | 1.164 | 1.216
