### ISSUE TITLE
FileInfo and  Path.GetFullPath() don't support long paths

### ISSUE THREAD

**Issue by iSazonov** [dotnet/corefx#29686]
[FileInfo](https://github.com/dotnet/corefx/blob/41a2120b233cc02c175f812e4e19e3f058396cb0/src/System.IO.FileSystem/src/System/IO/FileInfo.cs#L29) calls [Path.GetFullPath](https://github.com/dotnet/coreclr/blob/85374ceaed177f71472cc4c23c69daf7402e5048/src/System.Private.CoreLib/shared/System/IO/Path.Windows.cs#L55) and then [PathHelper.Normalize](https://github.com/dotnet/coreclr/blob/85374ceaed177f71472cc4c23c69daf7402e5048/src/System.Private.CoreLib/shared/System/IO/PathHelper.Windows.cs#L28) - the latest use `stackalloc char[PathInternal.MaxShortPath];` - [MaxShortPath](https://github.com/dotnet/coreclr/blob/85374ceaed177f71472cc4c23c69daf7402e5048/src/System.Private.CoreLib/shared/System/IO/PathInternal.Windows.cs#L56) is 260.

**Comment by stephentoub** [comment]
Is your comment based on testing or based on just looking at the code? Yes, it uses stackalloc, but that's just to start; it then grows into the heap if that length is insufficient.

**Comment by iSazonov** [comment]
Sorry, I skipped that ` ValueStringBuilder` can use the heap.
