### ISSUE TITLE
No XML Comments for Span-like types

### ISSUE THREAD

**Issue by mazhou-msft** [dotnet/corefx#29694]
There is no XML summary in Visual Studio for Span<T>, ReadOnlySpan<T>, Memory<T>, ReadOnlyMemory<T>, Memory extensions, System.Buffer.*, MemoryMarshal etc. Do we plan to add them?

**Comment by karelz** [comment]
XML summaries are populated from docs. I don't think the APIs are documented yet :(
cc @mairaw @weshaggard

**Comment by mairaw** [comment]
No, they're not yet. We do have the Span and friends on our priority list for 2.1. Others will depend on resources, so they might come later. We have a lot of scenarios to cover for 2.1 and just 3 writers to work on it.

**Comment by ahsonkhan** [comment]
> We do have the Span and friends on our priority list for 2.1.

Awesome. I am assuming we will be leveraging the  existing XML comments in source to generate these docs.

**Comment by mairaw** [comment]
When they're present, for sure @ahsonkhan!

**Comment by ahsonkhan** [comment]
This issue is being tracked by https://github.com/dotnet/docs/issues/4400.

We are starting to get docs now :)
- https://github.com/dotnet/dotnet-api-docs/pull/194
- https://github.com/dotnet/dotnet-api-docs/pull/228

**Comment by mazhou-msft** [comment]
Now I can see the documentation on docs.microsoft.com such as this: https://docs.microsoft.com/en-us/dotnet/api/system.span-1?view=netcore-2.1, but in VS IDE the XML Comments are still not available, are we on the way to add them? (actually many newly added APIs are missing XML comments.)

**Comment by mairaw** [comment]
Those docs are fairly recent and will be adding more as we go. IntelliSense for .NET is generated from the docs and added to the product in certain milestones. So, they’re either going to be update in a v-next (or potentially a servicing release).

/cc @weshaggard

**Comment by mazhou-msft** [comment]
Ping. apparently the XML comments are in source code but still not available in IntelliSense. Tried netcoreapp2.2 and netcoreapp3.0, no XML comments in IntelliSense.

**Comment by ahsonkhan** [comment]
@mazhou-msft, please check the latest nightly build with this change https://github.com/dotnet/corefx/pull/35467 (netcoreapp3.0)

**Comment by mazhou-msft** [comment]
I can see the XML comments in Visual Studio IDE for span-like types now, thanks!
