### ISSUE TITLE
Signature.LoadXml throws CryptographicException as id attribute is no longer optional

### ISSUE THREAD

**Issue by jespersh** [dotnet/corefx#29698]
A couple of days ago the dotnet framework security rollup started landing on machines and Signature.LoadXml started failing (https://blogs.msdn.microsoft.com/dotnet/2018/05/08/net-framework-may-2018-security-and-quality-rollup/)
To figure out what was different I took a look towards this nice place. 

And stumbled upon here: https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/Signature.cs#L151-L152
```
if (!Utils.VerifyAttributes(signatureElement, "Id"))
    throw new CryptographicException(SR.Cryptography_Xml_InvalidElement, "Signature");
```
The commit in question: https://github.com/dotnet/corefx/commit/8322265bb13336b40e0cfd3b9fe0216eadf51df8

According to spec then the ``id`` was suppose to be optional: https://www.w3.org/TR/xmldsig-core1/#sec-CryptoBinary

Our issue is with the dotnet framework, but possible preventing it from happening here too, would be nice

**Comment by karelz** [comment]
cc @krwq @bartonjs @AlexGhiondea

**Comment by krwq** [comment]
cc: @ianhays

**Comment by ianhays** [comment]
Id is still optional. Check out the [`VerifyAttributes` code](https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/Utils.cs#L96).

What the `Utils.VerifyAttributes(signatureElement, "Id")` call is saying is that if there are attributes present, they must either be xml-doc universal tags or an `Id` tag. Any other attribute not mentioned by the spec will be treated as invalid.

**Comment by jespersh** [comment]
The mistake might be with our provider. I didn't think it was significant at first, but the attribute was ``id`` instead of ``Id``  as per spec.
It could be helpful if the 3 different ``CryptographicException(SR.Cryptography_Xml_InvalidElement, "Signature")`` could the tell more, like if it could tell that ``id`` is invalid.

I'll provide a repo tomorrow with an example

**Comment by jespersh** [comment]
Created a reduced test here: https://github.com/jespersh/LoadXmlTest-29698 - you can switch between my reduced dotnetcore ``SignedXml`` or the full on framework in ``SealSignedXml.cs``

**Comment by bartonjs** [comment]
>  I didn't think it was significant at first, but the attribute was id instead of Id as per spec.

The implicit "at second" is correct, the casing matters.  ds:Signature has no defined attribute named `id`, only one named `Id`.  Therefore this element does not conform to schema and can no longer be loaded.
