### ISSUE TITLE
System.NullReferenceException when running optimized code on linux

### ISSUE THREAD

**Issue by TravisEz13** [dotnet/corefx#29700]
# Repro

1. On macOS or Linux 
1. Extract the attached files ([optimizeTest2.zip](https://github.com/dotnet/corefx/files/2002507/optimizeTest2.zip))
1. run `dotnet run -c Release`

# Expected
```
setting up UnhandledException handler...
-----------------
Setting time ...
Done Setting time!
-----------------
```
**note:** No exception.  I can get this by runnig `dotnet run -c Debug` 

# Actual

```
setting up UnhandledException handler...
-----------------
Setting time ...
Done Setting time!
-----------------
UnhandledException Handler caught : Object reference not set to an instance of an object.
stack trace:   at optimizeTest.Program.Main(String[] args)
Runtime terminating: True

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at optimizeTest.Program.Main(String[] args)
```

# dotnet --info
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-rc1-008662
 Commit:    6ae1926fb0

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /Users/travisplunk/.dotnet/sdk/2.1.300-rc1-008662/

Host (useful for support):
  Version: 2.1.0-rc1-26424-03
  Commit:  b50a96ee38

.NET Core SDKs installed:
  2.0.0 [/Users/travisplunk/.dotnet/sdk]
  2.0.2 [/Users/travisplunk/.dotnet/sdk]
  2.1.4 [/Users/travisplunk/.dotnet/sdk]
  2.1.300-rc1-008662 [/Users/travisplunk/.dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-30667 [/Users/travisplunk/.dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-30667 [/Users/travisplunk/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [/Users/travisplunk/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [/Users/travisplunk/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1-26424-03 [/Users/travisplunk/.dotnet/shared/Microsoft.NETCore.App]

```

**Comment by TravisEz13** [comment]
[optimizeTest2.zip](https://github.com/dotnet/corefx/files/2002507/optimizeTest2.zip)

**Comment by karelz** [comment]
@janvorli can you help route it?

**Comment by stephentoub** [comment]
Are you sure the interop is correct?  It's typically not a good idea to use a type you don't own (`struct tm` in this case) in such an interop signature, as its size can and will often vary across systems.  Case in point, you've defined your managed `UnixTm` type to be 36 bytes, but on my Linux system, `sizeof(struct tm)` is 56.

**Comment by iSazonov** [comment]
@stephentoub Thanks!  Could you please link a sample code from CoreFX/CoreCLR?

**Comment by iSazonov** [comment]
And if understand correctly we have to compile the interop library for every platform?

**Comment by stephentoub** [comment]
> Could you please link a sample code from CoreFX/CoreCLR?

Sure, for example a UTimeBuf defined here:
https://github.com/dotnet/corefx/blob/master/src/Native/Unix/System.Native/pal_time.h#L13-L17
used in an exported function here:
https://github.com/dotnet/corefx/blob/33b44346378ba0caebb1ab96ab015e4098868c16/src/Native/Unix/System.Native/pal_time.h#L24
that's implemented here:
https://github.com/dotnet/corefx/blob/33b44346378ba0caebb1ab96ab015e4098868c16/src/Native/Unix/System.Native/pal_time.cpp#L29-L39
with a corresponding managed struct here:
https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/Common/src/Interop/Unix/System.Native/Interop.UTime.cs#L12-L16
and the DllImport here:
https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/Common/src/Interop/Unix/System.Native/Interop.UTime.cs#L26-L27

> And if understand correctly we have to compile the interop library for every platform?

Every target where there might be differences.  At a minimum that means a different build for Linux and macOS.  There are differences across Linuxes, too, but we've chosen to have a "portable" build that targets a min version of glibc such that we can just build that once for most supported Linuxes.  @janvorli can likely share more details on that.

**Comment by iSazonov** [comment]
@stephentoub Many thanks for help!

**Comment by stephentoub** [comment]
Happy to help.

**Comment by TravisEz13** [comment]
@stephentoub  Why does this only occur on optimized builds?

**Comment by stephentoub** [comment]
Your native code is going to be stomping on memory it doesn't own regardless of whether it's optimized or not; most likely though is that what it ends up stomping on by happenstance isn't as critical or as immediately noticeable in your debug build.
