### ISSUE TITLE
[HttpClient] SSL Idn decode failure

### ISSUE THREAD

**Issue by ghost** [dotnet/corefx#29703]
The following produces an exception:

```c#
using System.Net.Http;
using System.Threading.Tasks;

namespace test
{
    class Program
    {
        static void Main(string[] args)
        {
            HttpClient client = new HttpClient();
            var _ = client.GetAsync("https://r6---sn-uxanug5-hxay.gvt1.com/test/").Result;

        }
    }
}
```

Stacktrace:
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (The SSL connection could not be established, see inner exception.) ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> System.ArgumentException: Decoded string is not a valid IDN name.
Parameter name: unicode
   at System.Globalization.IdnMapping.GetAsciiCore(String unicodeString, Char* unicode, Int32 count)
   at System.Globalization.IdnMapping.GetAscii(String unicode, Int32 index, Int32 count)
   at Interop.OpenSsl.AllocateSslContext(SslProtocols protocols, SafeX509Handle certHandle, SafeEvpPKeyHandle certKeyHandle, EncryptionPolicy policy, SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SafeDeleteSslContext..ctor(SafeFreeSslCredentials credential, SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_0(SslClientAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at test.Program.Main(String[] args) in /tmp/test/Program.cs:line 18
```
## Additional Info
```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-rc1-008673
 Commit:    f5e3ddbe73

Runtime Environment:
 OS Name:     debian
 OS Version:  
 OS Platform: Linux
 RID:         debian-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.300-rc1-008673/

Host (useful for support):
  Version: 2.1.0-rc1
  Commit:  eb9bc92051

.NET Core SDKs installed:
  2.1.300-rc1-008673 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

[EDIT] Add C# syntax highlighting by @karelz

**Comment by abk-x** [comment]
It appears to be in the actual Globalization code, the following also reproduces the error:
```
using System;
using System.Globalization;

namespace test2
{
    class Program
    {
        static void Main(string[] args)
        {
            var x = new IdnMapping();
            var idn = "r6---sn-uxanug5-hxay.gvt1.com";
            x.GetAscii(idn);
        }
    }
}
```

**Comment by abk-x** [comment]
Does this need to be moved to dotnet/coreclr ?

**Comment by abk-x** [comment]
On second thoughts, shouldnt .GetAscii only be called by HttpClient if the string starts with `xn--` or contains unicode glyphs?

**Comment by abk-x** [comment]
The workaround for this particular case is to replace `---` with "." (this is what a nslookup reveals). This sucks because it kills certificate verification, so we need to hamper verification for this call.

**Comment by karelz** [comment]
That looks like a bug.

Do you know if it fails also on .NET Core 2.0?
What happens if you disable SocketsHttpHandler (`DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0` as described [here](https://blogs.msdn.microsoft.com/dotnet/2018/04/11/announcing-net-core-2-1-preview-2/))

**Comment by karelz** [comment]
Here's the call:
https://github.com/dotnet/corefx/blob/3f5d26c720503f143333f7e51a006c5976f2ee66/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs#L130

cc @wfurt @stephentoub @geoffkizer

**Comment by wfurt** [comment]
When forced curl (DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0), I can connect. (server returns no content but that is different issue) 

when disabling globalization, I get same result with SockerHttp Handler.
export  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
Unhandled Exception: System.AggregateException: One or more errors occurred. (An error occurred while sending the request.) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---

**Comment by krwq** [comment]
this looks like a bug, I'll need to check if this is on our side (i.e. missing flag) or ICU. Windows seem to be working as expected

**Comment by krwq** [comment]
@karelz, both HttpClient and IdnMapping scenario repro on 2.0.3:

```
dotnet --info
.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  eb1d5ee318

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.3/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

HttpClient:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (An error occurred while sending the request.) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Server returned nothing (no headers, no data)
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at idn.Program.Main(String[] args) in /home/krwq/idn/Program.cs:line 14
```

Idn isolated:

```
Unhandled Exception: System.ArgumentException: Decoded string is not a valid IDN name.
Parameter name: unicode
   at System.Globalization.IdnMapping.GetAsciiCore(Char* unicode, Int32 count)
   at System.Globalization.IdnMapping.GetAscii(String unicode, Int32 index, Int32 count)
   at idn.Program.Main(String[] args) in /home/krwq/idn/Program.cs:line 11
```

**Comment by karelz** [comment]
Thanks for validation @krwq! Moving to 2.2 as it is not a regression.
It's still compat problem between Windows and Linux.

**Comment by wfurt** [comment]
note, that there are two different problems: The curl error simply means server did not respond with valid response. That is problem with that particular server. (@abk-x  should confirm)

**Comment by karelz** [comment]
Hmm, that's a good point and would make it a regression against 2.0 from HttpClient point of view.

**Comment by tarekgh** [comment]
@karelz we'll look at this but regarding the statement 

> It's still compat problem between Windows and Linux.

we never guarantee the compatibility between Windows and Linux. should expect some differences as we depend on the OS behavior.

**Comment by abk-x** [comment]
Just to confirm, the invalid response error is expected from the server, as the server drops requests silently when the path is not found.

**Comment by wfurt** [comment]
Is there URL we can test with @abk-x ? I think it would decrease confusion.

**Comment by abk-x** [comment]
Does this help? you should get a 302 redirect.

https://r6---sn-uxanug5-hxay.gvt1.com/edgedl/

**Comment by abk-x** [comment]
A URL with data:

http://r6---sn-4g5ednee.gvt1.com/edgedl/release2/PZTrPRGorok/GoogleUpdateSetup.exe

**Comment by karelz** [comment]
@tarekgh 

> we never guarantee the compatibility between Windows and Linux. should expect some differences as we depend on the OS behavior.

Fair. However, basic functionality should be the same (e.g. accepting ASCII string in this case).
I can imagine that certain Unicode characters are not recognized the same way across machines/OSs, but ASCII should behave the same way, unless it is explicit choice of the OS (e.g. sorting order).
The key question is, why is this happening and if it is explicit OS choice, or a bug.

**Comment by tarekgh** [comment]
@karelz

> However, basic functionality should be the same

Now, how you define "the basic functionality". I already debugged this issue and I know why it is failing. in ICU (when running on Linux/OSX) they have more IDN conversion rules which we don't do on Windows. 
For example, when using something like "ab--xyz.com", there is a rule that prevents to have a hyphen in the third and the fourth place in the Url. this means we'll fail because of such rules. you may try to look at http://icu-project.org/apiref/icu4c/uidna_8h.html#ab04a0655cd1e3bcac5e8f48c18df1a57a9bebae6483c78a9a4b608ba55f4ad367 and search for the UIDNA_ERROR_HYPHEN_3_4. This is one of the errors you may get. 

So what we are getting is a valid error except if we decide to ignore such errors.

**Comment by tarekgh** [comment]
@karelz I agree with your suggestion. I moved the issue to area-System.Net.Http.SocketsHttpHandler. 

To mention, other frameworks like node is relaxing these errors https://github.com/nodejs/node/blob/master/src/node_i18n.cc#L664 
But I agree we should wait and see if we are getting more hits, we can consider relaxing these errors by then.

**Comment by wfurt** [comment]
The RFC sys "unicode string" and that should be prefixed with xn--. General DNS is still governed by RFC1035 as far as I can tell and it does not have such restriction. 
I agree this is rare corner case.

**Comment by karelz** [comment]
That's a good point that general DNS is not obsoleted. We already resolved the domain, we just fail in TLS.
It seems that one of the cheaper solutions is to be resilient to `IdnMapping.GetAscii` failures in TLS, swallow the exception and just use the original domain name.

Should be fairly simple change here:
https://github.com/dotnet/corefx/blob/3f5d26c720503f143333f7e51a006c5976f2ee66/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs#L130

@abk-x are you interested to submit a PR?

**Comment by stephentoub** [comment]
> It seems that one of the cheaper solutions is to be resilient to IdnMapping.GetAscii failures in TLS, swallow the exception and just use the original domain name.

That sounds reasonable to me.

> Should be fairly simple change here

There are equivalent calls in both the Windows version of this and the macOS version of this.  Presumably we'd need to handle it similarly in all cases.

**Comment by abk-x** [comment]
Just my 2c:

Ultimately, GetAscii (which calls uidna_nameToASCII) performs a form of sanitization (normalization), to allow the original host name through would mean that the OpenSSL native code is directly exposed to a potentially malicious unicode string. Perhaps this same code path is used to initialize the SSL context on the server side too? This seems like an awful lot of risk for something that is considered a rare corner case.

**Comment by rmkerr** [comment]
I don't think that we should swallow the exception from `IdnMapping.GetAscii`. That approach could potentially cause security issues when disallowed Unicode characters are Punycoded.

Instead I think we should only be applying `IdnMapping.GetAscii` to hosts prefixed with "xn--". That's the behavior set out in the IDN spec, and I think that attempting to decode all hosts was just an oversight.

**Comment by jordan-johnson** [comment]
> That looks like a bug.
> 
> Do you know if it fails also on .NET Core 2.0?
> What happens if you disable SocketsHttpHandler? (`DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0` as described [here](https://blogs.msdn.microsoft.com/dotnet/2018/04/11/announcing-net-core-2-1-preview-2/))

Yes it fails for 2.0 too. Calling `AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);` fixes the issue.

**Comment by wfurt** [comment]
2.0 does not have SocketHttpHandler so if its failing it would be for other reason and AppContext should have NO impact.

**Comment by jordan-johnson** [comment]
After digging some, turns out I had forgotten to change the `program` value in `.vscode/launch.json` resulting in 2.1 running instead of 2.0. My mistake.

**Comment by wfurt** [comment]
that is sometimes tricky to get right one. It does not matter for the fix but it did not fit to the story.

**Comment by LDSpits** [comment]
I would like to take a stab at this issue.

> Instead I think we should only be applying IdnMapping.GetAscii to hosts prefixed with "xn--". That's the behavior set out in the IDN spec, and I think that attempting to decode all hosts was just an oversight.
Is this still the recommended way to fix this?

**Comment by wfurt** [comment]
that would be great @LDSpits. And yes, I think fixing IdnMapping.GetAscii () is right fix. I was looking at this yesterday and I verified this works on Windows so make it is same would be good. 

https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Globalization/IdnMapping.Unix.cs#L11


The code calls  uidna_nameToASCII(). I think we would break it to individual labels and use  uidna_labelToASCII()

**Comment by karelz** [comment]
@LDSpits great! I just sent you collaborator invite. Once you accept, we can assign it to you (GH limitations). We recommend to switch repo to "Not Watching" to avoid flood of notifications (500+ per day). The "Not Watching" will still send you notifications for issues assigned to you, where you are mentioned and where you explicitly subscribe.
Assigning to myself temporarily - ping me here once you accept and I will assign it to you.

**Comment by LDSpits** [comment]
Is there a project for the CoreLib? I'm looking for a csproj or a solution but can't seem to find any that contains the shared implementation.

**Comment by stephentoub** [comment]
> Is there a project for the CoreLib? 

In the coreclr repo.

**Comment by karelz** [comment]
@LDSpits any update on your progress? We would like to get this done for 3.0, so we need to start tracking timelines, etc.

**Comment by LDSpits** [comment]
Excuses, I've been busy with school for the last couple of weeks unfortunately (as I'm a student). I've got coreclr building now though.

> The code calls uidna_nameToASCII(). I think we would break it to individual labels and use uidna_labelToASCII()

Mind explaining what you meant with "labels" @wfurt? This confuses me a bit. Do i need to modify the C code or do i need to modify ``IdnMapping.Unix.cs``?

**Comment by wfurt** [comment]
You can look at https://www.ietf.org/rfc/rfc1035.txt
It has grammar for label  but essentially it is the chunk between dots.
You will need to break it apart and use functions  described at http://icu-project.org/apiref/icu4c/uidna_8h.html to decode each block.

And yes, IdnMapping.Unix.cs seems right place. 
As @stephentoub mentioned you will need to do that in coreclr repo. When done, it will be synchronized to corefx  via build magic.

**Comment by tarekgh** [comment]
I don't think this is the right right fix. either if we want to allow this case (have hyphens in the 3rd and 4th places of the string) then we can do that by using masking out the value of UIDNA_ERROR_HYPHEN_3_4 from the returned info when calling uidna_nameToASCII.

We need to agree this is the desired behavior and not having any security implication. Or we can think support that through some flag. I am expecting down the road we'll start to use ICU on Windows too and at that time this flag will have some meaning to control the behavior on both platforms.

**Comment by wfurt** [comment]
I think we should apply IDNS only to labels with A-Label prefix i.g. "xn--" or names with Unicode characters.. If it is not there, rules from rfc1035 should apply IMHO. In the example given UIDNA_ERROR_HYPHEN_3_4 would not matter.

**Comment by tarekgh** [comment]
I am not sure if we are talking about the same thing. Sorry if I am missing anything here.

The original issue was about failing the URL https://r6---sn-uxanug5-hxay.gvt1.com/test/ and the reason is ToAscii fails because of the 3rd and 4th hyphen in the string r6---sn-uxanug5-hxay.gvt1.com. the string doesn't have the ACE prefix anyway (i.e. xn--). The ACE is inserted as a result of ToAscii operation. If this needed to be fixed on the IDN level, then we need to allow r6---sn-uxanug5-hxay.gvt1.com succeed when calling ToAscii. and the way to do that is to mask out the error UIDNA_ERROR_HYPHEN_3_4

Here is how ToAscii specs just in case:

https://tools.ietf.org/html/rfc3490#section-4.1

Unicode specs https://unicode.org/reports/tr46/#ToASCII has a flag CheckHyphens which tell ToAscii to check the hyphens or not. ICU implemented that and returns in the info parameters the errors there is invalid hyphens and these are the error I am talking to mask out. in other word, we work as if the CheckHyphens is false.

CC @ShawnSteele

**Comment by wfurt** [comment]
we may not. Because it does not have valid ACE  prefix but it is valid  DNS name, we should send it out as is instead of trying to decode it and fail.

**Comment by tarekgh** [comment]
> we may not. Because it does not have valid ACE prefix but it is valid DNS name, we should send it out as is instead of trying to decode it and fail.

It doesn't have any ACE prefix at all and it shouldn't include the ACE (in the Unicode form). It is just a hyphens in the URL. here is the definition of the ACE to be sure we are in the same page:

```The ACE prefix for IDNA is "xn--" or any capitalization thereof.```

**Comment by tarekgh** [comment]
I have submitted the linked PR if anyone interested to have a look.
