### ISSUE TITLE
Publish master branch symbols to symweb and MSDL endpoints

### ISSUE THREAD

**Issue by dagood** [dotnet/corefx#29718]
Right now the official builds of `master` only publish to the MSDL/public endpoint, but both are required.

Tasks exist in the symbol publish leg that target each endpoint, but only one is enabled right now by `PB_PublishType`.

Docs on how to do this correctly aren't currently available, tracked by https://github.com/dotnet/core-eng/issues/3382.

**Comment by mikem8361** [comment]
Changed DotNet-CoreFx-PipeBuild-Master to also publish to symweb.
