### ISSUE TITLE
Outdated comment about where PkcsPal's "s_instance" is declared

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/corefx#29710]
Hi corefx team,

The [comment](https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/PkcsPal.cs#L100-L102)  in PkcsPal needs to be updated with:

- Pal\Windows\PkcsPal.Windows.cs
- Pal\AnyOS\PkcsPal.AnyOS.cs

Thanks!

**Comment by karelz** [comment]
Thanks @MaximLipnin! Do you want to submit PR?
