### ISSUE TITLE
System.Management.ManagementDateTimeConverter fail parsing on DateTime.MinValue

### ISSUE THREAD

**Issue by matteofabbri** [dotnet/corefx#29712]
The conversion from DateTime to Dmtf works fine even with DateTime.MinValue but if we parse the value back ( in my case "00010101000000.000000+060") it raise:

System.ArgumentOutOfRangeException: 'The added or subtracted value results in an un-representable DateTime.'

Step to reproduce the bug:

            var date = ManagementDateTimeConverter.ToDmtfDateTime(DateTime.MinValue);
            var parsed = ManagementDateTimeConverter.ToDateTime(date);

**Comment by pjanotti** [comment]
No, this is not a regression, same error happens in .NET Framework.

**Comment by pjanotti** [comment]
Thanks for reporting @matteofabbri - this made me compare the behavior with the netfx and there were some subtle differences that I wanted to avoid.
