### ISSUE TITLE
Why is DynamicMethod.DefineParameter not exposed?

### ISSUE THREAD

**Issue by svick** [dotnet/corefx#29715]
I was trying to run [the `DynamicMethod` example on docs.MS](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.dynamicmethod?view=netcore-2.0#examples) on .Net Core 2.x, but it failed with:

> Program.cs(60,15): error CS1061: 'DynamicMethod' does not contain a definition for 'DefineParameter' and no extension method 'DefineParameter' accepting a first argument of type 'DynamicMethod' could be found (are you missing a using directive or an assembly reference?)
>
> Program.cs(61,15): error CS1061: 'DynamicMethod' does not contain a definition for 'DefineParameter' and no extension method 'DefineParameter' accepting a first argument of type 'DynamicMethod' could be found (are you missing a using directive or an assembly reference?)

This is consistent with API reference, [which says that `DynamicMethod.DefineParameter` does not exist on .Net Core](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.dynamicmethod.defineparameter?view=netframework-4.7.2#applies-to).

On the other hand, [the method does exist in the source code](https://github.com/dotnet/coreclr/blob/ba110d5/src/System.Private.CoreLib/src/System/Reflection/Emit/DynamicMethod.cs#L522).

Is there a specific reason why the method is not exposed?

This might be a duplicate of https://github.com/dotnet/corefx/issues/18072.

**Comment by Anipik** [comment]
@maryamariyan are you working on this one ?

**Comment by maryamariyan** [comment]
yes

**Comment by echofool** [comment]
When will it be released?
I checked that [System.Reflection.Emit.Lightweight](https://www.nuget.org/packages/System.Reflection.Emit.Lightweight/) last updated time is 2016/11/15

**Comment by svick** [comment]
@echofool This issue has the .Net Core 3.0 milestone, so that's when I think this will be released.
