### ISSUE TITLE
System.IO.Compression should store NoCompression entries without wrapping them in Deflate streams

### ISSUE THREAD

**Issue by Marv51** [dotnet/corefx#29735]
Currently when a ZipArchive is created and an entry is added with the CompressionLevel set to "no-compression" the file inside the archive is still wrapped in a deflate stream. The deflate stream correctly does not to compress the file.

However, zip does natively support uncompressed files. The compression method "stored" is made for this.

To create OpenDocument format files (ods, odt etc.) it is required to store the mimetype file without wrapping it in any compression stream. They do this, so that the mimetype can always found at a specific offset. 
This change should also be a tiny performance and archive size improvement.

I have attached a diff of the changes necessary to implement this. I've run the tests, however I've not yet been able to build corefx in a way that I can use with my app to validate the patch is working.
[diff.zip](https://github.com/dotnet/corefx/files/2008533/diff.zip)

If this is something you think is possible to merge, I can spend more time on this to create a proper PR.

**Comment by stephentoub** [comment]
Sounds like a reasonable thing to do.  @ianhays?

**Comment by ianhays** [comment]
Totally reasonable, and not the first time I've seen this request either. I can't find the other one with a quick search, though.

I can't think of any real circumstances in which removing the nocompression entry's deflate header would cause issues. For testing we should try a zip produced by the new codeset with windows' zip library, unix `unzip`, and 7zip. Also should probably add a unit test of some sort.

**Comment by MrX13415** [comment]
Well. I basically need this right now. Anyone has a fork or so where this is working?

**Comment by danmosemsft** [comment]
Sounds like @marv51 has the code change, above. We would welcome a PR.

**Comment by Marv51** [comment]
As I‘ve not contributed here before, I didn‘t have the environment/tests
setup.
But I will try to get this working again tonight.


Dan Moseley <notifications@github.com> schrieb am Do. 8. Nov. 2018 um 17:39:

**Comment by MrX13415** [comment]
Oh, very nice. Thank you. :)

**Comment by danmosemsft** [comment]
Thanks @marv51. Let us know if the documentation in this repo is insufficient.
