### ISSUE TITLE
Survey all the tools targets we currently use from BuildTools and decide which ones to break (i.e. msbuild, custom PCL targets) and which ones we need to refactor and move to arcade.

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#29744]
Progress:
 - [x] Scan tools
 - [x] Scan target files that get includded in buildtools package
 - [x] Scan tasks from buildtools that aren't used anymore
 - [x] Scan buildtools package contents to see things that aren't used anymore

**Comment by joperezr** [comment]
The tools we have in buildtools repo are: (checkbox means if we analyzed whether we need it or not)
 - [ ] ApiCompat.exe (Desktop and .NetCore version)
 - [ ] BclRewriter.exe
 - [ ] GenAPI.exe (Desktop and .NETCore version)
 - [ ] GenFacades.exe (Desktop and .NETCore version)
 - [ ] RepoUtil.exe (Desktop and .NETCore version)
 - [ ] run.exe
 - [ ] Xunit.console.netcore.exe
 - [ ] Xunit.console.uwp.exe

**Comment by joperezr** [comment]
cc: @weshaggard

**Comment by weshaggard** [comment]
What about our xunit extensions library and netcore runner?

**Comment by joperezr** [comment]
The netcore runner is up there in the table, and it is flagged as "port to arcade". The netcore extensions are not a tool per se, but will definitely need to get ported in order for the netcore runner to compile, which is why I kind of skipped that from the table.

**Comment by weshaggard** [comment]
Sorry I missed the netcore runner when I looked I got too hung up on the uap runners. We can definitely include libraries a dependency of a tool or task.

**Comment by joperezr** [comment]
This has been broken down into items on the Project so it is now ok to close this issue.
