### ISSUE TITLE
Add support for brotli in .NET Framework

### ISSUE THREAD

**Issue by msmolka** [dotnet/corefx#29760]
Currently brotli compression is only supported by .NET CORE 2.1. It would be good to support it also in .NET Framework. For now when ASP.NET Core application is targeted .NET Framework, there is no possibility to use Brotli compression.

as reference: https://github.com/dotnet/corefx/issues/25785#issuecomment-389573056

**Comment by joshfree** [comment]
@danmosemsft my current thinking is we could evaluate porting this back to Full .NET Framework sometime post-2.2.  In .NET Core 2.1, we exposed Brotli compression APIs but without System.NET or ASP.NET Middleware consuming it yet.  During .NET Core 2.2 development milestone we expect upstack components to start calling the Brotli compression APIs.  After the higher level stack changes happen, stabilize, and ship; we would consider backporting the complete set of changes to a .NET Framework release. 

related: https://github.com/dotnet/corefx/pull/29729, https://github.com/aspnet/BasicMiddleware/issues/217

**Comment by khellang** [comment]
FYI; Brotli support was just added to ASP.NET Core's response compression middleware and will ship with the first 2.2 preview: https://github.com/aspnet/BasicMiddleware/pull/342.

**Comment by karelz** [comment]
We do not have plans to backport more features to .NET Framework -- see https://devblogs.microsoft.com/dotnet/net-core-is-the-future-of-net/
