### ISSUE TITLE
Native build not incremental on Windows

### ISSUE THREAD

**Issue by morganbr** [dotnet/corefx#29778]
Running build-native.cmd or build.cmd on Windows always reruns the native build from scratch even if nothing has changed. It should be possible to use cmake's incrementalism to avoid redoing the build (I think CoreRT already does). This adds significantly to how long an incremental build takes to rebuild files that rarely change.

**Comment by danmosemsft** [comment]
If this broke, it was recent, as last time I did this it was incremental.

**Comment by morganbr** [comment]
This might have something to do with the native_aot rebuild that happens here https://github.com/dotnet/corefx/blob/master/src/Native/build-native.cmd#L162 . It might be blowing away the CMAKE cache fo rthe previous version. I wonder whether we actually need to build two versions of the same thing rather than just having separate projects or using the targetgroup to decide which to build.

**Comment by ViktorHofer** [comment]
Agree, it would be nice to make it incremental again.

**Comment by danmosemsft** [comment]
Future. Not necessary to ship.

**Comment by ViktorHofer** [comment]
Whoever is going to fix deserves a medal.

**Comment by ViktorHofer** [comment]
Tested locally and https://github.com/dotnet/corefx/pull/40001 restored incrementalism.
