### ISSUE TITLE
SocketAsyncEventArgs.Complete may hang if used on disposed socket

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#29785]
If there is a race between using a Socket with SocketAsyncEventArgs and disposing of the Socket, it's possible that the call to allocate a NativeOverlapped will throw an ObjectDisposedException.  In some operations, this throw happens after we've already transitioned the Socket's _singleBufferHandleState to something other than None, which will cause SocketAsyncEventArgs.Complete to spin until _singleBufferHandleState transitions back, which it won't do.  There is a catch block meant to handle such issues and reset _singleBufferHandleState, but the AllocateNativeOverlapped call is outside of the associated try block.

This is a regression from 2.0 to 2.1 as part of the work to enable `Memory<byte>` usage with Socket.

**Comment by danmosemsft** [comment]
fixed in 2.1
