### ISSUE TITLE
TypeLoadException when using System.Threading.Channels in a Xamarin.Android project

### ISSUE THREAD

**Issue by SomeAnon42** [dotnet/corefx#29799]
![image](https://user-images.githubusercontent.com/6377116/40270618-1d059e38-5b99-11e8-978f-2f0b5c5870be.png)

![image](https://user-images.githubusercontent.com/6377116/40270647-bfc2c682-5b99-11e8-8af8-6deb10684c3e.png)

Version of the package: 4.5.0-rc1.
I'm wondering if there's a workaround for this.

Update: technically, the code that uses System.Threading.Channels is inside a netstandard2.0 library. However, the Android project directly references System.Threading.Channels and its dependencies.
![image](https://user-images.githubusercontent.com/6377116/40270732-12470c00-5b9b-11e8-8370-8a58857796a7.png)

**Comment by karelz** [comment]
Which type fails to load? Can you get a call stack?
cc @marek-safar

**Comment by tarekgh** [comment]
@SomeAnon42 can you provide a simple project repro?

**Comment by SomeAnon42** [comment]
I can no longer reproduce it, not even in the same project. Not sure what this was about.
There was nothing on the call stack, since it's a nuget package (though maybe I just had to uncheck "Enable Just My Code"?). No info regarding which type it couldn't load either, I guess mono just wouldn't tell you that.

**Comment by tarekgh** [comment]
> I can no longer reproduce it, not even in the same project. Not sure what this was about.

ok, I am going to close the issue, and you may reopen again if run into the problem one more time. usually providing some repro is required to be able to investigate.
