### ISSUE TITLE
System.Buffers package needs _._ placeholders for Xamarin

### ISSUE THREAD

**Issue by marek-safar** [dotnet/corefx#29828]
We need it to use our shared version of System.Buffers.ArrayPool<T>

 System.Threading.Tasks.Extensions package need a placeholder for Xamrin too. the linked PR has the change for 2.2 which can be ported to 2.1 too.

**Comment by marek-safar** [comment]
This should probably have milestone 2.2 (we won't ship supporting code before dev15-9)

**Comment by ViktorHofer** [comment]
It seems like this should still be done @marek-safar? cc @danmosemsft

**Comment by marek-safar** [comment]
No, we don't need this (we fixed it better way meantime).
