### ISSUE TITLE
WebSocket extensions

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#2982]
From using the WebSocket class, I think these extensions make sense:

```C#
Task<string> ReceiveTextAsync(CancellationToken cancellationToken = default(CancellationToken));
Task<ArraySegment<byte>> ReceiveBinaryAsync(CancellationToken cancellationToken = default(CancellationToken));
Task SendAsync(string message, CancellationToken cancellationToken = default(CancellationToken))
Task SendAsync(ArraySegment<byte> message, CancellationToken cancellationToken = default(CancellationToken))
```

- All methods have a defaulted CancellationToken.
- The Receive method implementations read until EndOfMessage.
- The Receive methods send back a Close message when receiving one. The message sent back echos the status code which was received.
- The Receive methods throw when the MessageType is different than that of the method signature. (For most protocols, the user will know what MessageType he expects to come next.)
- The string overloads handle the encoding/decoding.

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar @mconnew

**Comment by tmds** [comment]
cc: @davidfowl @Tratcher

**Comment by tmds** [comment]
Extending the above proposal:
- When the Receive methods receive a MessageType which is Close, they send back a Close as described above. When it is another MessageType (e.g. Binary when expecting Text), the websocket does a CloseAsync with a status ProtocolError.
- When the Receive method received a Close message type and sent back a Close as a response, it could return null (or default(ArraySegment<byte>)) instead of throwing, to indicate an EOS-condition.

For Close these extensions can be handy:
```C#
Task SendCloseAsync(WebSocketCloseStatus closeStatus, CancellationToken cancellationToken);
Task SendCloseAsync(WebSocketCloseStatus closeStatus = WebSocketCloseStatus.NormalClosure, string statusDescription = null, CancellationToken cancellationToken = default(CancellationToken))
```

**Comment by tmds** [comment]
I have implemented the extensions as proposed so far: [WebSocketExtensions](https://github.com/tmds/WebSocketExtensions/blob/master/src/WebSocketExtensions/WebSocketExtensions.cs).

As an example, I have implemented [nodejs/sockjs/test_server/broadcast](https://github.com/sockjs/sockjs-node/blob/master/tests/test_server/sockjs_app.js#L43-L58): [BroadcastMiddleware.cs](https://github.com/tmds/WebSocketExtensions/blob/master/src/WebSocketExtensions/BroadcastMiddleware.cs).

Perhaps some other samples can be implemented, to see whether the API and behavior make sense.

**Comment by tmds** [comment]
Implemented the other sockjs testserver websocket services as examples of using the extensions:
- [amplify](https://github.com/tmds/WebSocketExtensions/blob/master/src/WebSocketExtensions/AmplifyMiddleware.cs)
- [close](https://github.com/tmds/WebSocketExtensions/blob/master/src/WebSocketExtensions/CloseMiddleware.cs)
- [echo](https://github.com/tmds/WebSocketExtensions/blob/master/src/WebSocketExtensions/EchoMiddleware.cs)
- [ticker](https://github.com/tmds/WebSocketExtensions/blob/master/src/WebSocketExtensions/TickerMiddleware.cs)

already implemented:
- [broadcast](https://github.com/tmds/WebSocketExtensions/blob/master/src/WebSocketExtensions/BroadcastMiddleware.cs)

To implement ticker, added Close receive extension with similar semantics as text and binary receive:
```C#
Task ReceiveCloseAsync(CancellationToken cancellationToken = default(CancellationToken))
```

**Comment by tmds** [comment]
@CIPop @joshfree can I close this issue?

**Comment by CIPop** [comment]
@tmds are you planning on releasing these extension separately? I think they are interesting,

Feel free to close the item if so, leaving a link to the extension or NuGet package for future reference.

**Comment by tmds** [comment]
Implementation: https://github.com/tmds/Tmds.SockJS/tree/b732b3d113be22b05adc4d978ecf9d9368c0ac3a/src/Tmds.WebSockets.Sources
