### ISSUE TITLE
System.Net.NetworkInformation.Ping - Reports TTL of 128 when ran on linux

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#29824]
_From @RCAlfonso on May 21, 2018 15:47_

System.Net.NetworkInformation.Ping - Reports TTL of 128 when ran on linux but reports correctly when same code is ran in windows.

Environment: Centos 7
.Net Core version : 2.0.6
Build: 74b1c7038...

_Copied from original issue: dotnet/coreclr#18070_

**Comment by karelz** [comment]
Linux has 2 implementations - using raw sockets, or via ping utility:
We should be able to parse the TTL from IP header via raw sockets here:
https://github.com/dotnet/corefx/blob/7ce4889d1de78d251d7e536ee174ff8640fa8583/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.Unix.cs#L107-L131

If we use ping utility, then we can't get to the information:
https://github.com/dotnet/corefx/blob/7ce4889d1de78d251d7e536ee174ff8640fa8583/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.Unix.cs#L202

**Comment by karelz** [comment]
It is covered in #9350 and #28934, closing
