### ISSUE TITLE
double.Parse throws FormatException on valid string though Span<T>

### ISSUE THREAD

**Issue by bmolnar2** [dotnet/corefx#29827]
I was tried to do a parse as below:
`double.Parse("12.5".AsSpan())`

That one works on string, and I expected to work on string through Span, but getting this exception:
>  | $exception | {System.FormatException: Input string was not in a correct format.    at System.Number.ParseDouble(ReadOnlySpan`1 value, NumberStyles options, NumberFormatInfo numfmt)    at System.Double.Parse(ReadOnlySpan`1 s, NumberStyles style, IFormatProvider provider)    at ...

I'm on the following version:
> Host (useful for support):
>   Version: 2.1.0-preview2-26406-04
>   Commit:  6833f3026b

**Comment by Tornhoof** [comment]
Try with RC1, this might be https://github.com/dotnet/coreclr/issues/17553

**Comment by bmolnar2** [comment]
Yep, working in RC1, thank you.
