### ISSUE TITLE
Revert Xamarin placeholders for System.Memory package

### ISSUE THREAD

**Issue by marek-safar** [dotnet/corefx#29847]
Please revert https://github.com/dotnet/corefx/pull/28034 change, we couldn't get our bits working properly on time for dev15-8 release.

@weshaggard this needs to happen for 4.5 version of System.Memory which I guess is 2.1 release. The fix can stay in master as we'll need it for future versions.

Note: that'll require a better way to coordinate the supported nuget package versions for Xamarin. 

It should also address few related issues like https://github.com/aspnet/SignalR/issues/1886

**Comment by weshaggard** [comment]
@marek-safar if we do that change will the netstandard asset in the package work correctly on Xamarin? Hopefully it will but I think it is worth validating before we do this change.

**Comment by marek-safar** [comment]
If they work on .net desktop they should

**Comment by ahsonkhan** [comment]
cc @joperezr

**Comment by tarekgh** [comment]
Should be fixed by #29925
