### ISSUE TITLE
System.Numerics.Vectors partialfacades error: Invalid local constant signature: 'epsilon' 

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#29861]
1. Run `build.cmd` on a clean clone of the repo.
2. Observe partialfacade errors.

This issue might have been exposed by recent buildtools changes, specifically https://github.com/dotnet/buildtools/pull/2038, but I am not sure.

Looking at the list of recent [commits to master](https://github.com/dotnet/corefx/commits/master), the corefx repo builds successfully from yesterday's last commit, prior to the dependencies update: aa73b08881ccc2a438947c19d60a6665008bcc08

The error appears after https://github.com/dotnet/corefx/pull/29836 got merged (i.e. e693ef593b152fc9f92049b63afed967f167cf6f).

```text
D:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): error : PDB0018: token 0x0600001F: Invalid local constant signature: 'epsilon' [D:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
D:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): error : PDB0018: token 0x06000020: Invalid local constant signature: 'epsilon' [D:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
D:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): error : PDB0018: token 0x0600003B: Invalid local constant signature: 'epsilon' [D:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
D:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): error : PDB0018: token 0x0600003C: Invalid local constant signature: 'epsilon' [D:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
D:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): error : PDB0018: token 0x0600003C: Invalid local constant signature: 'minAngle' [D:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
D:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): error : PDB0018: token 0x06000059: Invalid local constant signature: 'EPSILON' [D:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
D:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): error : PDB0018: token 0x06000072: Invalid local constant signature: 'FLT_EPSILON' [D:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
D:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): error : PDB0018: token 0x0600008B: Invalid local constant signature: 'epsilon' [D:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
```

cc @eerhardt, @ViktorHofer, @danmosemsft, @stephentoub

**Comment by danmosemsft** [comment]
Yes seems to be from that change

**Comment by danmosemsft** [comment]
Adding workaround in https://github.com/dotnet/buildtools/pull/2045 -- we should figure out the problem here and either fix the code or genfacades.
 
@weshaggard any idea about these? not at all clear to me.

**Comment by weshaggard** [comment]
Yeah I suspect these have always been there unnoticed until your change promoted them to errors. 

As for the particular error I'm not sure what is going on there I've not seen them before. We would need to debug to see what is happening.

**Comment by tmat** [comment]
Can you share the DLL and the Portable PDB on which the converter reports these errors?

**Comment by danmosemsft** [comment]
@tmat You can build as above but @ahsonkhan perhaps you could share yours. So we can get these warnings cleaned up

**Comment by stephentoub** [comment]
@tmat, @ahsonkhan, has any progress been made here?  These warnings are still showing up during builds.  Thanks.

**Comment by ahsonkhan** [comment]
I still see the warnings after the buildtools change to update Microsoft.DiaSymReader.Converter to latest. Re-opening.

```textE:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): warning : PDB0018: token 0x0600001F: Invalid local const
ant signature: 'epsilon' [E:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
E:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): warning : PDB0018: token 0x06000020: Invalid local const
ant signature: 'epsilon' [E:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
E:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): warning : PDB0018: token 0x0600003B: Invalid local const
ant signature: 'epsilon' [E:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
E:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): warning : PDB0018: token 0x0600003C: Invalid local const
ant signature: 'epsilon' [E:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
E:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): warning : PDB0018: token 0x0600003C: Invalid local const
ant signature: 'minAngle' [E:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
E:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): warning : PDB0018: token 0x06000059: Invalid local const
ant signature: 'EPSILON' [E:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
E:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): warning : PDB0018: token 0x06000072: Invalid local const
ant signature: 'FLT_EPSILON' [E:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
E:\GitHub\Fork\corefx\Tools\partialfacades.task.targets(64,5): warning : PDB0018: token 0x0600008B: Invalid local const
ant signature: 'epsilon' [E:\GitHub\Fork\corefx\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
    8 Warning(s)
    0 Error(s)
```

**Comment by ahsonkhan** [comment]
@tmat, any ideas why we are still seeing the warning messages?

**Comment by tmat** [comment]
I can repro now. Didn't realize it's converting from Windows PDB to Portable PDB, not vice versa.

**Comment by tmat** [comment]
Repro:

```
D:\corefx\bin\obj\Windows_NT.AnyCPU.Debug\System.Numerics.Vectors\netcoreapp\PreGenFacades>pdb2pdb System.Numerics.Vectors.dll /pdb WindowsPdb\System.Numerics.Vectors.pdb
```

**Comment by tmat** [comment]
Seems like GenFacades is generating invalid constant signatures for `float` constants.

**Comment by tmat** [comment]
Unless the PDB is being round-tripped (converted from Portable to Windows and then back) see https://github.com/dotnet/symreader-converter/issues/145.

**Comment by danmosemsft** [comment]
@weshaggard who owns GenFacades?

**Comment by weshaggard** [comment]
>@weshaggard who owns GenFacades?

Our team. However if I were to guess the code likely at fault is CCI which is owned elsewhere.

**Comment by ViktorHofer** [comment]
it seems like we haven't found a cause yet or did someone follow-up on this offline?

**Comment by stephentoub** [comment]
Where are we on getting this addressed?  These had been the only warnings in the build, but having them then allowed additional warnings to get merged unnoticed (https://github.com/dotnet/corefx/issues/33277).  I'd really like to see us get down to 0 warnings; the moment we have > 0, it's really easy for others to slip in.

**Comment by danmosemsft** [comment]
I don't like warnings either, but probably will be a while before someone has time to look. Maybe we should just suppress this warning ID entirely by a change like my dotnet/buildtools#2045

**Comment by tannergooding** [comment]
Is this something we can workaround with a `*.manual.cs` file?

I was wondering why we aren't hitting this for other constants (like `Math.Pi`) and it looks like it's because we explicitly declare them: https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/ref/System.Runtime.Extensions.Manual.cs

**Comment by danmosemsft** [comment]
If it works, great

**Comment by tannergooding** [comment]
Ok, I couldn't add these constants to a `*.manual.cs` file because they were method local constants. I changed them to be regular constants and that resolved the warnings in a clean build: https://github.com/dotnet/corefx/pull/34057

**Comment by tannergooding** [comment]
Logged https://github.com/dotnet/arcade/issues/1574 to continue tracking the issue since we are working around it in CoreFX
