### ISSUE TITLE
ISO 8859-1 to ISO 8859-15 Encoding support in .NET Core 2

### ISSUE THREAD

**Issue by madhub** [dotnet/corefx#29874]
Hi
Healthcare software extensively uses Text encoding/decoding .net classes for decoding the patient name present in the DICOM image file.List text encoding supported by the DICOM standard are [here ](http://dicom.nema.org/dicom/2013/output/chtml/part03/sect_C.12.html#table_C.12-2). We in the process porting our library from .NET full framework to .NET Stand 2 to make our library cross platform.
It sees the .NET core 2 does not support many encoding example ISO 8859-1 to ISO 8859-15 encoding. I have tried following [MSDN article](https://msdn.microsoft.com/en-us/library/system.text.encodingprovider(v=vs.110).aspx) with limited success.  I tried adding a reference to the System.Text.Encoding.CodePages.dll assembly to my project still I was not able to access the encode.
How to get access encodings in cross platform way?.
Here is my sample code

```csharp
using System;
using System.Collections.Generic;
using System.Text;


namespace ConsoleApp
{
    class EncodingTest
    {
        static void Main(string[] args)
        {
            var instance = CodePagesEncodingProvider.Instance;
            Encoding.RegisterProvider(instance);

            var gb18030 = Encoding.GetEncoding("GB18030");
            // Latin alphabet No. 2  or iso-ir-101
            var iso_8859_2 = Encoding.GetEncoding("ISO-8859-2");
            // Latin alphabet No. 3  or iso-ir-109
            var iso_8859_3 = Encoding.GetEncoding("ISO-8859-3");
            // Latin alphabet No. 4  or iso-ir-110
            var iso_8859_4 = Encoding.GetEncoding("ISO-8859-4");


            Console.ReadLine();
        }
    }
}

**Comment by svick** [comment]
> I was not able to access the encode

Could you clarify what exactly do you mean by that? What happens when you run your code?

When I tried running your code, after adding a reference to the `System.Text.Encoding.CodePages` *package*, it seemed to work fine.

**Comment by tarekgh** [comment]
@madhub do you mean you cannot compile? or you can compile and you are getting a runtime error? if you can provide a simple project you cannot use the encodings would be good to tell you what is wrong there. But generally, this should work fine.

**Comment by tarekgh** [comment]
@madhub I am closing this issue, but feel free to reply back and we can help you if you still have the problem.

**Comment by madhub** [comment]
Yes, it works, my bad  I was looking at the debug window in visual studio saw red in header name & other attributes , I thought it is error. 

![image](https://user-images.githubusercontent.com/8907962/40499445-981028aa-5f9f-11e8-992e-98824a4dd88e.png)
