### ISSUE TITLE
Fix Nano runs in release/2.0 and release/2.1 branches

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#29890]
We addressed the failures in master, but these are still failing on all runs in the release/2.0 and release/2.1 branches.

cc: @MattGal, @danmosemsft

**Comment by danmosemsft** [comment]
@karelz is there someone who could own porting recent Nano fixes into 2.0 and 2.1 (with shiproom permission) ? It should not be too bad. The issue is the runs use an updated Nano build.

**Comment by ViktorHofer** [comment]
Reapplying the area-Meta label as this doesn't require any infra bring-up.

**Comment by stephentoub** [comment]
If we haven't done this in a year, it's obviously not important to track anymore.
