### ISSUE TITLE
Removing `readonly` from a field can be a breaking change

### ISSUE THREAD

**Issue by sharwell** [dotnet/corefx#299]
Currently the [**Signatures** section of the Breaking Change Rules](https://github.com/dotnet/corefx/wiki/Breaking-Change-Rules#signatures) page includes the following:

> ✓ Allowed
> * Removing `readonly` from a field

As hinted in [a recent tweet](https://twitter.com/samharwell/status/543970816321650688), this should probably be disallowed in a particular case. I would prefer not to give the answer away publicly yet, but feel free to contact me by email. Here is the original tweet:

> C# Quiz: Add `readonly` to a field only set in the constructor, which changes the runtime behavior of the type (no use of reflection).

**Comment by sharwell** [comment]
Well, since no one answered in nearly a month (:disappointed:) I'll give more information. If the static type of the field is a value type, then the generated IL for changes for code where a method is called on the field instance. The behavior difference is relevant to a pull request I submitted; specifically the [`_dictionaryEnumerator` field](https://github.com/dotnet/corefx/pull/246/files#diff-e669424e546961b86c9e9fd5b56cbc91R73) cannot be made `readonly` without breaking the behavior. While this is not an example of *removing* the `readonly` modifier, it does show that removing the modifier could introduce a bug in other code. I recommend updating wording of the breaking changes policy to the following:

> ✓ Allowed
> * Removing `readonly` from a field, unless the static type of the field is a mutable value type

**Comment by nguerrera** [comment]
Thanks, @sharwell. I agree and I've updated the wiki with your recommended text.
