### ISSUE TITLE
System.Tests.EnvironmentProcessorCount.Unix_ProcessorCountTest should use _SC_NPROCESSORS_CONF on Linux

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/corefx#29902]
As we found in dotnet/coreclr#17851 `sysconf(_SC_NPROCESSORS_ONLN)` returns arbitrary number between 1 and actual number of logical CPU cores (it's been observed on Jetson TK1 board). There is PR dotnet/coreclr#18053 waiting to be merged.

As @stephentoub pointed out in https://github.com/dotnet/coreclr/pull/18053#issuecomment-390506497 the following CoreFx test 
[System.Tests.EnvironmentProcessorCount.Unix_ProcessorCountTest](https://github.com/dotnet/corefx/blob/deee13b99d441cf1906397c54d0c5afcf8385d92/src/System.Runtime.Extensions/tests/System/Environment.ProcessorCount.cs#L29-L47) should also be fixed

```
/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstress1_tst_prtest/_/fx/bin/tests/System.Runtime.Extensions.Tests/netcoreapp-Linux-Release-arm /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstress1_tst_prtest/_/fx/bin/tests/System.Runtime.Extensions.Tests/netcoreapp-Linux-Release-arm
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Runtime.Extensions.Tests
Discovered:  System.Runtime.Extensions.Tests
Starting:    System.Runtime.Extensions.Tests
   System.Tests.EnvironmentProcessorCount.Unix_ProcessorCountTest [FAIL]
      Assert.Equal() Failure
      Expected: 2
      Actual:   4
      Stack Trace:
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstress1_prtest/_/fx/src/System.Runtime.Extensions/tests/System/Environment.ProcessorCount.cs(46,0): at System.Tests.EnvironmentProcessorCount.Unix_ProcessorCountTest()
```

@karelz Can you please triage this?

**Comment by danmosemsft** [comment]
@echesakovMSFT could you offer a PR?
