### ISSUE TITLE
runtime.win10-arm64.runtime.native.System.IO.Compression 4.3.0 is missing from nuget.org

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#29907]
Folks are starting to see this when restoring the 4.3.0 compression for ARM64. I see the package on myget. We should either publish that on nuget or publish an empty one (if the intent was to delay support).

**Comment by tymtam2** [comment]
This prevents me from installing Microsoft.Extensions.Hosting 2.1.0 (the only available version)

Error:

> NU1603: runtime.native.System.IO.Compression 4.3.0 depends on runtime.win10-arm64.runtime.native.System.IO.Compression (>= 4.3.0) but runtime.win10-arm64.runtime.native.System.IO.Compression 4.3.0 was not found. An approximate best match of runtime.win10-arm64.runtime.native.System.IO.Compression 4.3.1 was resolved.
> Package restore failed.

**Comment by ianhays** [comment]
As Eric and I discussed in person, we think this is a result of some preliminary arm64 work in 1.1. The intent was not to actually be publishing a stable version of this package, nor was the intent to reference one from the platform-unspecific meta package.

What we should do here is publish an empty version of this package so people stop getting broken dependency errors on nuget restoration. 

FYI @ViktorHofer @JeremyKuhne

**Comment by kudobyte** [comment]
Is this question from the VS dev community related?

https://developercommunity.visualstudio.com/content/problem/232996/warning-nu1603-runtimenativesystemiocompression-41.html

**Comment by AArnott** [comment]
Please get this fixed. In the meantime, I'm considering suppressing the warning by adding this to my csproj file:

```xml
    <!-- Reference directly to use 4.3.1 and suppress package restore warnings. -->
    <PackageReference Include="runtime.native.System.IO.Compression" Version="4.3.1" />
```

**Comment by antlhuede** [comment]
Please get this fixed. Ridiculous that installing a VS update months ago created this issue and it still isn't resolved 3 updates later.

What is going on here?

**Comment by tymtam2** [comment]
More info and some feedback from Microsoft in this question: 

https://stackoverflow.com/questions/50902568/suppress-a-single-compiler-error-e-g-nu1603

**Comment by ViktorHofer** [comment]
I will work with @ericstj / @safern (as I don't have permissions to push to nuget) to get this fixed asap.

**Comment by ericstj** [comment]
Thanks @ViktorHofer.  Essentially we need to take https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.win10-arm64.runtime.native.System.IO.Compression/4.3.0 and **remove** all binaries from it.  Repack it, sign it (since that's now a NuGet requirement), and push to nuget.org.

**Comment by ViktorHofer** [comment]
Thanks. I was just going to ping you offline to coordinate the work.

**Comment by ViktorHofer** [comment]
Can someone please point me to a simple repro? I want to verify the fix.

**Comment by AArnott** [comment]
The repro steps for me are described [here](https://github.com/AArnott/vs-threading/commit/357f279e44d150d2dbc305cf81fd549f2cbaed2d).

**Comment by ViktorHofer** [comment]
We just pushed the missing package and the issue should now be resolved. Thanks for the feedback!
