### ISSUE TITLE
AcceptEncodingHeaderSentWithNoDuplicates test failing on CurlHandler

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#29905]
While working on PR #29903, several of the new tests added are failing on CurlHandler.

System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandlerTest

* GetAsync_SetAutomaticDecompression_AcceptEncodingHeaderSentWithNoDuplicates(methods: Deflate, encodings: "deflate", manualAcceptEncodingHeaderValues: "gzip")	
* GetAsync_SetAutomaticDecompression_AcceptEncodingHeaderSentWithNoDuplicates(methods: GZip, Deflate, encodings: "gzip, deflate", manualAcceptEncodingHeaderValues: "")	
* GetAsync_SetAutomaticDecompression_AcceptEncodingHeaderSentWithNoDuplicates(methods: GZip, encodings: "gzip", manualAcceptEncodingHeaderValues: "deflate")

Need to investigate. For now, these tests will be disabled on CurlHandler.

**Comment by karelz** [comment]
Triage: We plan to remove CurlHandler, once we do that, we should cleanup tests and ActiveIssues like this. Keeping it open to track the work.

**Comment by karelz** [comment]
Duplicate of #41183
