### ISSUE TITLE
Where do we generate desktop facades for vNext?

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#29900]
@weshaggard @terrajobst @safern @stephentoub @Petermarcu 

Today we generate facades for mscorlib, System, System.Core, System.Drawing, etc in CoreFx. 

We ship those shims both in the latest netcoreapp packages, as well as in the Microsoft.Windows.Compatibility.Shims package in order to apply them in netcoreapp2.0.

With vNext we'll be bring back some types, including many types which overlap with things we currently build shims for (System.Drawing and WindowsBase for example).

For WindowsBase I expect it to have a 1:1 assembly up-stack that will just replace it.  For System.Drawing and System (maybe others) its less clear.  

- Do we want to follow a pattern of building a "bigger" shim upstack and relying on conflict resolution to make it win?  
- Do we want to make it POR that the target of any shim to be placed in the same repo where the single copy of that shim builds, moving the build of some shims upstack to accomplish this?
- Do we want to make the generation of the shims happen in a seperate repo that has a global view?
- Do we want to make the generation of shims be driven off of a set of tuples and avoid coupling to actual impl/ref and then just validate after the fact via testing?

**Comment by weshaggard** [comment]
>Do we want to make the generation of the shims happen in a seperate repo that has a global view?

Assuming we don't ship the different layers as individual chunks then I think generating them at the highest level and shipping them inbox to that framework is the best thing to do.

**Comment by nguerrera** [comment]
Barring that, can we allocate a permanently higher assembly/file version for up-stack?

**Comment by ericstj** [comment]
Yes, I was considering that as a safer fix.  Removing WindowsBase.dll from .NETCoreApp will break apps targeting just the NS.NETCore.App shared framework using old-PCLs or desktop assemblies which used the following types :

- ObservableCollection<T>
- ReadOnlyObservableCollection<T>
- INotifyCollectionChanged
- System.IO.Packaging.*

That's a significant scenario to break which I'd prefer not to.

I think bumping the assembly versions of the WPF/WinForms assemblies is general goodness since it will also make it clear their desktop counterparts should never be used in their place, but I can also imagine that causing folks grief early on in the project where folks are trying to use desktop as a proxy for some of this stuff.

File-version is easy enough to change and it won't break anything nor do I see us ever needing to roll it back.  So I'll start there for now.

**Comment by nguerrera** [comment]
cc @davkean

**Comment by davkean** [comment]
@ericstj As far as I can remember, we never shipped WindowsBase.dll as "portable" - we shipped System.Windows.dll/System.ObjectModel.dll that contained them.

**Comment by davkean** [comment]
But desktop did ship them.

**Comment by ericstj** [comment]
Yeah, the fact that PCLs couldn't use that identity is interesting but doesn't really make it possible for us to remove this.  We try to make desktop assemblies work in core, and I can't convince myself that no-one used these types from a desktop assembly since we added WindowsBase.dll to the shared framework.

For now I think we'll need to stick with CoreFx building the shim for this and let WPF's actual implementation win over that.

**Comment by nguerrera** [comment]
cc @jaredpar

**Comment by ericstj** [comment]
Right now the POR is that we generate facades in both corefx, winforms, wpf.  We allow winforms and wpf to "win" by ensuring they have higher file-versions.
