### ISSUE TITLE
Resolve Core naming ambiguity

### ISSUE THREAD

**Issue by SjoerdWesterhof** [dotnet/corefx#29916]
It is unclear to me what Core means with:
- .NET Core the framework implementation
- ASP.NET Core the ASP.NET implementation running on both Desktop and .NET Core
- .NET Core class libraries able to target Desktop. f.e. net471

I think it would help for developer understanding of these new technologies and tools to have unambiguous naming. Right now i can't pinpoint what "Core" means.

**Comment by danmosemsft** [comment]
@richlander do you want to share your thoughts on this?

**Comment by karelz** [comment]
This issue was moved to dotnet/core#1598
