### ISSUE TITLE
TimeZoneInfo.AdjustmentRule on Unix: Daylight deltas of 23 hours are very confusing

### ISSUE THREAD

**Issue by jskeet** [dotnet/corefx#29914]
Currently Pacific/Apia uses a daylight delta of -23 hours to represent it crossing the international dateline. This broke Noda Time until I put specific code in to account for it.

Code to detect this:

```csharp
using System;

class Program
{
    public static void Main()        
    {
        foreach (var zone in TimeZoneInfo.GetSystemTimeZones())
        {
            var rules = zone.GetAdjustmentRules();
            foreach (var rule in rules)
            {
                if (Math.Abs(rule.DaylightDelta.Hours) > 14)
                {
                    Console.WriteLine($"{zone.Id}: {rule.DaylightDelta}");
                    break;
                }
            }
        }
    }
}
```

I realize that there are issues due to adjustment rules not indicating when they use a different standard time, but I *think* the base UTC delta is being used internally anyway, so I'd expect that approach to be used here too.

**Comment by krwq** [comment]
yes this is in PR: https://github.com/dotnet/coreclr/pull/18305

**Comment by krwq** [comment]
ok, so the fix has not addressed this issue - I'm still seeing `Pacific/Apia` with -23h.

@jskeet should you use something like that instead? (`TimeZone.InfoGetUtcOffset`)

```csharp
            foreach (TimeZoneInfo tzi in TimeZoneInfo.GetSystemTimeZones())
            {
                foreach (TimeZoneInfo.AdjustmentRule ar in tzi.GetAdjustmentRules())
                {
                    if (Math.Abs((tzi.GetUtcOffset(ar.DateStart)).TotalHours) > 14.0)
                    {
                        Console.WriteLine($"{zone.Id}: {rule.DaylightDelta}");
                    }
                }
            }
```

This doesn't print anything - we have a test similar to above code making sure we never regress here as well (see TimeZoneInfoTests.cs => `GetSystemTimeZones_AllTimeZonesHaveOffsetInValidRange`)

**Comment by jskeet** [comment]
@krwq: No, because I need to know (in Noda Time) the DaylightDelta, not just the UTC offset. (We expose the standard offset and the savings.)

Fundamentally the problem isn't with the UTC offset itself being out of range - it's with the advertised savings being out of range.

**Comment by tarekgh** [comment]
@jskeet is right. The problem is on Linux we internally store the rule internal fields mainly for the time conversion and not in the shape to be exposed to the user. This is why we are getting -23 hours daylight delta while it should be just one hour (-1). @krwq is looking at enhancing this and we may expose the Rule UTC offset property which also should help more in the specified scenario. for the example of Pacific/Apia the UTC offset should be something like -11 hours and the daylight delta should be 1 hour
