### ISSUE TITLE
Norwegian sorting strings: AA vs Å

### ISSUE THREAD

**Issue by Doff3n** [dotnet/corefx#29911]
Sorting strings in norwegian should be sorted as danish. This is the case for both .net core and .net 4.6.1

Reproduced in repo:
https://github.com/Doff3n/HelloSort

Start
aa
ab
ac
åå

Sorted result using culture db-NO
aa
ab
ac
åå

Expected
ab
ac
aa
åå

Sorted result using culture da-DK
ab
ac
aa
åå

**Comment by khellang** [comment]
Some background; http://archives.miloush.net/michkap/archive/2006/04/27/584439.html

**Comment by tarekgh** [comment]
The framework is using the underlying OS for the sorting operation. please report this issue to Windows if you still think the issue is valid.

CC @shawnsteele @jeffjenovey
