### ISSUE TITLE
System.Data.Common nuget does not reflect github code

### ISSUE THREAD

**Issue by orellabac** [dotnet/corefx#29920]
The latests nuget for System.Data.Common does not includes the latests code. For example it does not include the DbProviderFactories impl. Could you provide a link to download a more updated nuget?

**Comment by karelz** [comment]
I believe that System.Data.Common stopped being published as standalone package.
To use the latest, please target .NET Core 2.1.

cc @weshaggard

**Comment by AfsanehR** [comment]
@orellabac Did @karelz suggestion resolve the issue?

**Comment by karelz** [comment]
No response in more than 1w. Closing. Feel free to reopen if there is ore information.
