### ISSUE TITLE
HttpListener.Stop() Followed By task.GetAwaiter().GetResult() results in different exceptions on different OS

### ISSUE THREAD

**Issue by bgottfried91** [dotnet/corefx#29927]
The following code will result in different exceptions being thrown depending on which OS it is running on:
```c#            
            HttpListener httpListener = new HttpListener();
            httpListener.Prefixes.Add("http://localhost:8080/");
            httpListener.Start();
            var task = Task.Run(() => httpListener.GetContextAsync().GetAwaiter().GetResult());
            Task.Delay(1000).Wait();
            httpListener.Stop();
            task.GetAwaiter().GetResult();
```

On Windows (using [SDK 2.1.300-rc1](https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300-rc1)) it results in an HttpListenerException ('The I/O operation has been aborted because of either a thread exit or an application request').

On the latest Debian Stretch Docker Image ([image tag dotnet:2.1-runtime from microsoft/dotnet](https://github.com/dotnet/dotnet-docker/blob/master/2.1/runtime/stretch-slim/amd64/Dockerfile)), it results in a ObjectDisposedException ('Cannot access a disposed object').

As far as I'm aware, the HttpListenerException is the expected behavior; is the ObjectDisposedException supposed to be thrown on Linux?

**Comment by danmosemsft** [comment]
@bgottfried91 do you happen to have a callstack for the Debian case?

**Comment by bgottfried91** [comment]
@danmosemsft , as of today, I can no longer replicate the issue (I am seeing the expected HttpListenerException on closing). Might be that one of the changes over the weekend fixed the issue or else my Minikube/docker environments were in a bad state somehow. Closing ticket regardless.

**Comment by danmosemsft** [comment]
Thanks @bgottfried91
