### ISSUE TITLE
Socket Pool

### ISSUE THREAD

**Issue by felipepessoto** [dotnet/corefx#29932]
There is several performance critical scenarios that can benefit from Socket reuse through pooling.

Have you considered it?

I'm not sure about the API, if it would be a new class (with Rent and Return), or a implementation in Socket itself (like SqlConnection).

Here we have a sample, but based on TcpClient: https://www.codeproject.com/Articles/35011/NET-TCP-Connection-Pooling. It is very simple and uses lock.

**Comment by svick** [comment]
Do I understand it correctly that this applies to scenarios where all of the following apply?

* You're not using HTTP.
* You're need to send/receive multiple messages to the same server.
* Using a single socket is not enough.

**Comment by fujiy** [comment]
Exactly

**Comment by karelz** [comment]
I wonder if such kind of pooling would be better to be done on top of Sockets - similar way SocketsHttpClient does it.

**Comment by sgf** [comment]
im used TCP and tested the Disconnect(true); API on windows its very stupid.its will blocked call and take about 2 mins;
and im tried modify the Regedit path HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
Added TcpTimedWaitDelay and set to 30,the result is no effect.
For Language competitive, performance is so important.
how socket performance will better at .net core 3.0 or 5.0

**Comment by sgf** [comment]
I found some of my concerns and issues you mention are not the same.
your's is reuse the connection.
my's is reuse the socket object(include handle and kernel's resources)

**Comment by stephentoub** [comment]
> tested the Socket.Disconnect(true); API on windows its very stupid.
its will blocked call and take about 2 mins;

@sgf, I'm not clear on what your comments have to do with this issue. If you're facing what you believe is a performance issue with Disconnect, please open a new issue specific to that, including a repro we can run to see the behavior you discuss. Thanks.

**Comment by sgf** [comment]
> > tested the Socket.Disconnect(true); API on windows its very stupid.
> > its will blocked call and take about 2 mins;
> 
> @sgf, I'm not clear on what your comments have to do with this issue. If you're facing what you believe is a performance issue with Disconnect, please open a new issue specific to that, including a repro we can run to see the behavior you discuss. Thanks.

i will do that,open new issue for the Disconnect.

**Comment by karelz** [comment]
Triage: We do not think we need this type of API without clear customer demand and benefit. It can be built on top of our APIs if needed. If it proves to be super-popular, we can always reconsider adopting it into the platform.
