### ISSUE TITLE
Suggestion of some more negative expressions in Regex

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/corefx#29937]
In regex:
1- `\S` is the negative of `\s`, and `\P{}` is the negative of `\p{}`. Can't `\Xnn` be the negative of `\xnn` and `\Unnnn` be the negative of `\unnn` whrere n is a digit? 
They are shorter than `[^\xnn]` and `[^\unnnn]` respectively.

2- `[^a]` is the negative of a.. There is no short easy expression to negate a text such as abc, to get an expression that matches any successive 3 chars but not abc . Why cant we just use something like `(?^abc) 
`This expresston is not currently allowed by the regex, so adding it to the regex will not break any existing code.. The negative group (?^ ) can be used to negate any pattern (i.e match any thing but this pattern).

I also suggest to allow operations between Unicode categories, such as intersection (&), union (+), difference (-). For example, the following expression:
`\p{(IsBasicLatin+IsArabic)&(L-Lt)+Nd}`
is a shortcut for:
`(?=\p{IsBasicLatin}|\p{IsArabic})([\p{L}-[\p{Lt}]]|\p{Nd})`
It is obvious that the first one is shorter, cleaner, and easier to understand than the second one.

U added more 4 suggestion in #29689

**Comment by karelz** [comment]
Are these industry standard extensions of regex? If not, are we ok extending regex in a way specific to .NET only?

**Comment by MohammadHamdyGhanem** [comment]
@karelz 
This is a question for the team to decide. But I know that there are some differences betwen various implementations of regex, as som of char class operators supported in other languages. Bieng compliant to some standard doesn't mean you can't add extra features. I think the negative string or in general a negative group can simplify some regex and open new possibilities.

**Comment by MohammadHamdyGhanem** [comment]
@karelz 
I also suggest to allow operations between Unicode categories, such as intersection (&), union (+), difference (-). For example, the following expression:
`\p{(IsBasicLatin+IsArabic)&(L- Lt)+Nd}`
is a shortcut for:
`(?=\p{IsBasicLatin}|\p{ IsArabic})([\p{L}-[\p{Lt}]]|\p{Nd})`
It is obvious that the first one is shorter, cleaner, and easier to understand than the second one.

**Comment by danmosemsft** [comment]
As @karelz suggests, I do not think we want to further diverge the.NET regex dialect without compelling reason. It makes documentation, books, examples less portable and adds cognitive load to readers. 

Is this syntax in PCRE? We may offer an an API over PCRE in future so we may not want to make it easier to create patterns that do not transfer.

**Comment by MohammadHamdyGhanem** [comment]
@karelz @danmosemsft @radical @shanselman @AArnott 
Here is Verex (my verbal regex builder):
https://github.com/MohammadHamdyGhanem/Verex
Thanks
