### ISSUE TITLE
Correct way to set proxy settings to be used by HttpClient on Windows?

### ISSUE THREAD

**Issue by lkts** [dotnet/corefx#29934]
Hi,

I am running my ASP.NET Core 2.1 RC 1 Final app inside Docker container based on `microsoft\dotnet:2.1-aspnetcore-runtime-nanoserver-sac2016`. I would like all my requests from `HttpClient` to go through system-wide (container-wide) proxy. I didn't find any good source of information on what configuration should i do. One thing that i tried was to set proxy environment variables but it does not seem to work.

Thanks.

**Comment by cod7alex** [comment]
Following my testing, I think environment variables actually work and I run into some other issue with my environment. Having some docs on this would be nice though (maybe they exist but I didn't find them).

**Comment by karelz** [comment]
We should harness proxy settings on Windows from WinHttp settings.
Do you see difference of proxy detection between Nano and other Windows SKUs?

**Comment by karelz** [comment]
cc @wfurt

**Comment by davidsh** [comment]
>We should harness proxy settings on Windows from WinHttp settings.

We don't use WinHTTP settings (netsh ).

We use WinINET / Internet Explorer settings which are stored in the registry per-user.  Those settings, though, are accessed via WinHTTP APIs:

* WinHTTPGetIEProxyConfigForCurrentUser
* WinHttpGetProxyForUrl

It is possible that Nano container doesn't have any initial IE settings in the registry when a container is first created.  Also, it is unlikely that the current WinHTTP APIs that we use will special the special proxy settings that might be used by the Docker container environment.  We should investigate what those are, though.  Perhaps we can use those as a fallback if the normal IE settings are available.

**Comment by cod7alex** [comment]
@karelz I have regular 2016 servers configured via registry, but wanted configuration of container (Dockerfile) to be as simple as possible.

**Comment by davidsh** [comment]
Also, are you following any of the setup instructions documented here to set up Docker containers to use a proxy?

https://docs.docker.com/network/proxy/

**Comment by davidsh** [comment]
I found this discussion related to the problem you're having.  It shows how you can set up the container to use the "Internet Explorer" settings (which the current HTTP stack will use).

See: https://forums.docker.com/t/connect-to-the-internet-from-a-windows-container-behind-a-http-proxy/41307/8

If you read down toward the end of the discussion thread, you'll see the details about how to set up the proxy settings to work with the current .NET Core HTTP APIs

>It turns out that Windows actually reads the values for the proxy from the [HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Connections] key in the registry. This key is created when you click the OK/Apply button in the proxy config dialog in Internet Explorer (hard to do in a container)

**Comment by cod7alex** [comment]
@davidsh 
For windows server 2016 i used `HKLM\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings` but i have no .net core 2.1 running there to test (i assume it is important since there is new  HttpClient handler).

I tried to use second approach from docker docs that you referenced. So, `HTTP_PROXY`, `HTTPS_PROXY` environment variables.

Regarding your last link, there is also statement that it does not apply to Nano server. This is the reason why i wanted to ask here for right approach. And, let's be honest, this script looks bad :)
> And yes, this only works in the WindowsServerCore image. The NanoServer images does not have the Internet Explorer installed so the registry keys do not exists. If you want to use tha NanoServer image you have to find another solution.

**Comment by cod7alex** [comment]
As per https://docs.microsoft.com/en-us/windows-server/get-started/getting-started-with-nano-server it is not supported. Can i set the proxy settings explicitly in code? 
> Nano Server cannot be configured to use a proxy server to access the internet.

**Comment by davidsh** [comment]
Will be tracked by #36553
