### ISSUE TITLE
Provide documentation about WinHttpHandler

### ISSUE THREAD

**Issue by sflusov** [dotnet/corefx#29945]
Hi everyone

The **corefx** repositories contains at least 2 **HttpClientHandlers** which can use in **HttpClient** on Windows OS:
- HttpClientHandler
- WinHttpHandler

There are no articles comparing them by next questions:
- performance comparison
- working with DNS shift (when IPs for DNS FQDN is changed)
- connection lease timeout (when HttpClient doesn't automatically move to new instance when autoscaling)

Could anyone share your experience of usage WinHttpHandler?

**Comment by sflusov** [comment]
Hi @karelz 

Could you answer on a few extra question:
1. Are you going to provide `SocketsHttpHandler` for applications were written on Net Framework (make Net Standard library). 
2. How many times will  faster `SocketHttpHandler` vs `HttpClientHandler` for Net Framework apps

Thank you

**Comment by karelz** [comment]
> Are you going to provide `SocketsHttpHandler` for applications were written on Net Framework (make Net Standard library).

Currently we do not have such plans.

> How many times will faster `SocketHttpHandler` vs `HttpClientHandler` for Net Framework apps

It depends on scenario. The best recommendation is to create meaningful simulation of your workload (this is a hard part), then measure it.
We didn't do such comparison yet. I hope we will get to it eventually.

**Comment by karelz** [comment]
Seems to be mostly answered, closing.
