### ISSUE TITLE
Bring back System.Reflection.ICustomTypeProvider

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#29958]
This was previously in System and used by WPF to help binding to things that can only be known at runtime.

We need to bring it back in an appropriate home.  System.Reflection.Primitives?  System.ObjectModel (where other glue-like Attributes/interfaces live).

**Comment by danmosemsft** [comment]
@AtsushiKan is it possible for you to take this one?

**Comment by AtsushiKan** [comment]
Just an interface? Think I can manage that...

**Comment by danmosemsft** [comment]
Hah - I didn't notice it was so trivial.

**Comment by ericstj** [comment]
Yep, just needs a "home" somewhere in corefx since we are the owners of system.dll shim.
