### ISSUE TITLE
Allow multiple data annotation attributes to be put into another single attribute at compile time.

### ISSUE THREAD

**Issue by mikewodarczyk** [dotnet/corefx#29966]
This is a new feature request: 

The request is to have a mechanism to allow multiple data annotation attributes to be put together into another single attribute that represents the whole group of attributes.

One use case is with EF-code and MVC: 
For a class parameter / Table column that appears in multiple classes / tables, I want to define data annotations like:

    [Column(DataType = "nvarchar")]
    [MaxLength(30)]
    [Required]
    public string CustomerNo {get; set;}

For each class/table that has string CustomerNo, I want to have exactly the same data type and the same max length, etc, but I don't want to have to keep repeating these lines over and over.  The best I can do now to keep the values from repeating in the code is to make separate const values to represent the datatype and maxlength:  e.g.

    public class SchemaDefinitions {
        public const string CustomerNoDataType = "nvarchar";
        public const int CustomerNoMaxLength = 30;
    }

    [Column(DataType = SchemaDefinitions.CustomerNoDataType)]
    [MaxLength(SchemaDefinitions.CustomerNoMaxLength)]
    [Required]
    public string CustomerNo {get; set;}

This is still a lot of repeated code and not very "DRY".

What I would rather do is create a new attribute that contains, implements, or has its own attributes that hold all of the other attributes together.  Single inheritance stops me from doing it for multiple attributes today.  For EF-Core and MVC to use them, they need to be set at compile time (not runtime).

e.g.

    // Method 1: implements
    public class CustomerNoAttribute:  IMaxLengthAttribute, IColumnAttribute, IReqiredAttribute {
       public int MaxLength {get; private set;}
       public string DataType {get; private set;}
       public bool Required {get; private set; }
       public CustomerNoAttribute(string dataType, int maxLength, bool required) {
            this.MaxLength = MaxLength;
            this.DataType = datatype;
            this.Required = required;
       }
    }

OR

    // Method 2: Has its own attributes
    [Column(DataType="nvarchar")] 
    [MaxLength(30)]
    [Requred]
    public class CustomerNoAttribute() {}

OR

    // Method 3: contains attributes
    public class CustomerNoAttribute() {
        public const MaxLengthAttribute = new MaxLengthAttribute(30);
        public const ColumnAttribute = new ColumnAttribute(DataType = "nvarchar");
        public const RequiredAttribute = new RequiredAttribute();
    }

I think that a compile time only Methods 1 and 2 will work.
What I expect to happen is that attribute consumers (like EF-Core code first migrations and MVC) should be given a recursively generated list of attributes, attributes of attributes, attributes of attributes of attributes, etc. (for method 2) or Attributes implementing attributes (Method 1) to pick up the collection of attributes applied to a class parameter.  My first code snippet can be reduced down to:

    public class  AnyClass {
        [CustomerNo]  // give me type, length, required all in one attribute.
       public string CustomerNo {get; set;}
    }

I think that Method 1 (interfaces) is more like the usual C# style.  The down side is that attribute consumers would have to change to look for the interfaces instead of the class names.

Method 2 would have the same issues that multiple inheritance has and would have to deal with infinite loops of attributes.

**Comment by ajcvickers** [comment]
Closing as this is not something we plan to implement.
