### ISSUE TITLE
Trouble using local CoreFx build to dogfood

### ISSUE THREAD

**Issue by seth-capistron** [dotnet/corefx#29962]
I'm trying to follow these [instructions](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md#more-advanced-scenario---using-your-local-corefx-build), but must be doing something wrong since I'm hitting an issue. Specifically, I'm at the dotnet restore step and am receiving this error...

```console
  Restoring packages for C:\Users\sethc\Documents\Visual Studio 2017\Projects\TestConsole4\TestConsole4.csproj...
  Installing Microsoft.Private.CoreFx.NETCoreApp 4.6.0-preview1-26528-0.
  Installing runtime.win-x64.Microsoft.Private.CoreFx.NETCoreApp 4.6.0-preview1-26528-0.
C:\Users\sethc\Documents\Visual Studio 2017\Projects\TestConsole4\TestConsole4.csproj : error NU1202: Package Microsoft.Private.CoreFx.NETCoreApp 4.6.0-preview1-26528-0 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package Microsoft.Private.CoreFx.NETCoreApp 4.6.0-preview1-26528-0 supports: netcoreapp2.2 (.NETCoreApp,Version=v2.2)
C:\Users\sethc\Documents\Visual Studio 2017\Projects\TestConsole4\TestConsole4.csproj : error NU1202: Package Microsoft.Private.CoreFx.NETCoreApp 4.6.0-preview1-26528-0 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1) / win-x64. Package Microsoft.Private.CoreFx.NETCoreApp 4.6.0-preview1-26528-0 supports: netcoreapp2.2 (.NETCoreApp,Version=v2.2)
  Generating MSBuild file C:\Users\sethc\Documents\Visual Studio 2017\Projects\TestConsole4\obj\TestConsole4.csproj.nuget.g.props.
  Restore failed in 40.22 sec for C:\Users\sethc\Documents\Visual Studio 2017\Projects\TestConsole4\TestConsole4.csproj.
```
The output from the dotnet.exe CLI that I downloaded (per the [Install Prerequisites](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md#install-prerequisites) section) is...
```console
.NET Core SDK (reflecting any global.json):
 Version:   2.1.400-preview-008942
 Commit:    de407deff0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\sethc\Desktop\dotnet-sdk-latest-win-x64\sdk\2.1.400-preview-008942\

Host (useful for support):
  Version: 2.1.0-rtm-26515-03
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.400-preview-008942 [C:\Users\sethc\Desktop\dotnet-sdk-latest-win-x64\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rtm-30752 [C:\Users\sethc\Desktop\dotnet-sdk-latest-win-x64\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rtm-30752 [C:\Users\sethc\Desktop\dotnet-sdk-latest-win-x64\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-rtm-26515-03 [C:\Users\sethc\Desktop\dotnet-sdk-latest-win-x64\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
I have synced and am building the latest version of the master branch. Can anyone help point me to where I've gone wrong?

**Comment by karelz** [comment]
I think you need to retarget your project to netcoreapp2.2 (from netcoreapp2.1).
master branch moved to netcoreapp2.2, but we didn't update the docs yet: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md#option-1-framework-dependent

Can you please give it a try? If it works, would you mind submit updated docs PR?
cc @weshaggard @wtgodbe

**Comment by seth-capistron** [comment]
Where can I download the 2.2 version of the SDK? Using the CLI that I got from this [link](https://github.com/dotnet/cli/blob/master/README.md#installers-and-binaries) in the documentation, I get the error below. I'm assuming I need to be using the 2.2 version of the CLI, but correct me if that's not right.

```console
C:\Users\sethc\Desktop\dotnet-sdk-latest-win-x64\sdk\2.1.400-preview-008942\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): error : The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2. [C:\Users\sethc\Documents\Visual Studio 2017\Projects\TestConsole4\TestConsole4.csproj]
```

**Comment by weshaggard** [comment]
@seth-capistron we don't yet have a 2.2 SDK but you can temporatily work around this by setting `<NETCoreAppMaximumVersion>2.2</NETCoreAppMaximumVersion>` in your project.

**Comment by seth-capistron** [comment]
Yup, that did the trick - thank you! Including my working .csproj and Nuget.config files in case someone in the future finds them useful. One thing I did notice was that the runtime version I specified in the RuntimeFrameworkVersion node needed to be lower than the version of my Microsoft.Private.CoreFx.NETCoreApp. Otherwise, the restore would fetch the 'official' build version of DLLs. I'm assuming this is expected, but was not aware of it (could be somewhere in the docs that I missed).

My working .csproj...
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <RuntimeFrameworkVersion>2.2.0-preview1-26529-01</RuntimeFrameworkVersion> <!-- runtime version I had installed -->
    <RuntimeIdentifier>win-x64</RuntimeIdentifier> <!-- make self-contained -->
    <NETCoreAppMaximumVersion>2.2</NETCoreAppMaximumVersion> <!-- added per the advice -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Private.CoreFx.NETCoreApp" Version="4.6.0-preview1-26530-0" /> <!-- version from my local build -->
  </ItemGroup>

  <PropertyGroup>
    <PackageConflictPreferredPackages>Microsoft.Private.CoreFx.NETCoreApp;runtime.win-x64.Microsoft.Private.CoreFx.NETCoreApp;$(PackageConflictPreferredPackages)</PackageConflictPreferredPackages>
  </PropertyGroup>

</Project>
```

And my working Nuget.Config...
```
<configuration>
  <packageSources>
    <add key="local coreclr" value="D:\Repos_2\github\corefx\bin\packages\Debug" /> <!-- Change this to your own output path -->
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by weshaggard** [comment]
FYI @safern please include this in your documentation update.

**Comment by safern** [comment]
> FYI @safern please include this in your documentation update.

Yes I was able to produce a runtime through source-build and test it using the MaximumVersion workaround :clap:
