### ISSUE TITLE
Bring back X509Certificate2UI

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#29960]
This is needed by System.IO.Packaging for package signing.  Related https://github.com/dotnet/corefx/issues/29959.

The code is coupled enough to the existing crpto in CoreFx that it may make sense to place it in a (windows specific) crypto contract in corefx.

https://referencesource.microsoft.com/System.Security/R/6d6e79b9fd86b660.html

Here's my port of this: https://gist.github.com/ericstj/80a27a288346cb733edd855398d4b2a3

Would need to be cleaned up and placed in the correct assembly + pinvokes teased out into our coding style.  /cc @bartonjs

**Comment by bartonjs** [comment]
FWIW: Everything else that touched X509Certificate2UI we changed to PNSE.

There's no Windows-specific crypto contract past X509Certificates, so this is an entirely new Windows-only package.  Or just the Windows NetFx compat shim.

**Comment by Anipik** [comment]
@weshaggard should we create a new library for this ?

**Comment by weshaggard** [comment]
I don't have a lot of context on this but from a quick look I would suggest a new library to house this I'll look to @bartonjs to suggest a name for it.

**Comment by bartonjs** [comment]
If there's no grab-bag library for things between CoreFX and the Desktop UI stacks, then probably something like "System.Security.Cryptography.X509Certificates.UI".  But since it's (per Eric's gist) ~300 lines of code, it's probably a waste to have an assembly all to itself.

**Comment by ericstj** [comment]
So far I haven’t created a grab bag. I have opened a number of issues but all the others found a home in some existing lib.

The one other type that’s in a similar place is SystemSounds. I currently have that in its own lib in an internal repo.  I could imagine grouping these.

**Comment by danmosemsft** [comment]
Microsoft.Win32.SystemEvents also seems in a similar position.

**Comment by ericstj** [comment]
Except we already shipped that one.

**Comment by Anipik** [comment]
@ericstj so whats the final stand on it ? should I go ahead and create a new library for all the UI stuff ?

**Comment by ericstj** [comment]
Let's create a new library for now.  I suspect we'll have more stuff to go in it.  I can move the SystemSounds stuff down.  @weshaggard / @danmosemsft do you have an idea about a name?  "System.Windows.Extensions"?

**Comment by weshaggard** [comment]
System.Windows.Extensions seems reasonable to me.

**Comment by Anipik** [comment]
@bartonjs @ericstj any example tests already in corefx through which I can get an idea about how to write tests for this new library ?

**Comment by bartonjs** [comment]
> any example tests already in corefx through which I can get an idea about how to write tests for this new library?

If you need certificates to test with, there are plenty in the X509Certificates tests, and since we're building and running tests against net472 you could use the CertificateRequest API to just create them on the fly.

I don't know of any UI tests that we'd have, since we don't have UI.  And this is all about "pop a dialog, do some stuff with it, and look at the answer".

**Comment by danmosemsft** [comment]
We have no means to handle UI, so unit tests aren't allowed to trigger UI. If testing involves UI, I'd check in a list of steps for someone to run manually if/when they change the code.
