### ISSUE TITLE
Is 2.1 final?

### ISSUE THREAD

**Issue by Larswa** [dotnet/corefx#29974]
Hi, is 2.1 out of RC mode?   

My project could resolve the 2.1.0 packages and I am seeing this, but I am not seeing any public announcements yet and the dot.net download pages are not showing the 2.1 final runtime/sdks.

https://github.com/dotnet/corefx/releases/tag/v2.1.0

**Comment by shaggygi** [comment]
@Larswa 2.1 is supposed to be released 5/30/2018 unless something unexpected occurs.  There will most likely be blogs released here: https://blogs.msdn.microsoft.com/dotnet/

**Comment by Larswa** [comment]
@shaggygi Thanks Greg. And 5/30 is here, so that seemed to be on schedule. I was just surprised to see the bits released from this repository and the SDK is still 2.1.300-rc1-008673   (which worked fine om my buildserver btw)  :-)     I'll try and be patient ... thanks.

**Comment by karelz** [comment]
Here's some more info about 2.1 Early Access Downloads: https://github.com/aspnet/Home/wiki/2.1.0-Early-Access-Downloads
Closing as answered.
