### ISSUE TITLE
ContentLength=0 not handled correctly when switching HTTP protocols 

### ISSUE THREAD

**Issue by wfurt** [dotnet/corefx#29984]
In case some websocket retrun ContentLength =0 with SwitchingProtocol

See wss://ws.gate.io/v3/

![40631009-bdcae8be-630a-11e8-895f-8b851cbe89db](https://user-images.githubusercontent.com/14356188/40737050-79e9088e-63f4-11e8-929d-7935c272f145.png)

Connect to this websocket using System.Net.WebSockets.ClientWebSocket will failed due to the Respone.Content as EmptyReadStream, so it will failed when System.Net.WebSockets.WebSocket.CreateFromStream.

but Chrome firefox and edge can handle this response properly.

related to #29948

**Comment by danmosemsft** [comment]
fixed
