### ISSUE TITLE
System.Diagnostics.Tests.ProcessStartInfoTests CI failures on Windows 10 Nano

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#29980]
https://mc.dot.net/#/user/tarekgh/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Frelease~2F2.1~2F/test~2Ffunctional~2Fcli~2F/eb499046eb64eb3ef3159a85bd666fab98eb9a39/workItem/System.Diagnostics.Process.Tests

**Comment by wtgodbe** [comment]
@MattGal @danmosemsft is this related to https://github.com/dotnet/corefx/issues/29753?

**Comment by MattGal** [comment]
Yes I'm pretty sure you're right, though I thought the end of that issue was that the tests got disabled on Nano.

**Comment by tarekgh** [comment]
Note the failure here is on 2.1 release branch and not the master. maybe we need to port the fix to 2.1?

**Comment by MattGal** [comment]
Oh, I missed that part.  If you want tests passing there, definitely.  Since you're making a PR to a release branch already, you might be able to just cherry pick that commit as part of your own though.

**Comment by tarekgh** [comment]
I prefer this be submitted in another PR because we already communicated my PR to the ship room and I want to avoid any confusion or adding any unrelated changes. I'll let @danmosemsft  decide what want to do here.

**Comment by wtgodbe** [comment]
Looks like https://github.com/dotnet/corefx/pull/29995 already went in, so this may be addressed already

**Comment by tarekgh** [comment]
CC @maryamariyan

**Comment by danmosemsft** [comment]
already fixed
