### ISSUE TITLE
[release/2.1.x] System.Net.HttpListener.Tests CI failures on Windows 10 Nano

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#29983]
https://mc.dot.net/#/user/tarekgh/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Frelease~2F2.1~2F/test~2Ffunctional~2Fcli~2F/eb499046eb64eb3ef3159a85bd666fab98eb9a39/workItem/System.Net.HttpListener.Tests

**Comment by davidsh** [comment]
We disabled these tests in Master. We need to port that into release/2.1.x.

cc: @caesar1995 @karelz

**Comment by caesar1995** [comment]
I will submit a PR and send email to netfxship room about the test-only fix.

cc: @danmosemsft

**Comment by caesar1995** [comment]
Fixed in #29991.
