### ISSUE TITLE
S.R.CS.Unsafe: additional overloads using IntPtr instead of void*

### ISSUE THREAD

**Issue by xanatos** [dotnet/corefx#29985]
I'm trying some of the SRCS.Unsafe methods for some interop I have with C/C++ libraries. My only little problem is that I try not to use `unsafe` (keyword) code, and disable the unsafe compiler option. I instead use plenty of `Marshal.Read*`/`Marshal.Write*` Now, in .NET there is a "pretense" that `IntPtr` is "safe" (I'll put it in double quotes) while `void*` is `unsafe` (or at least the point is: code using `IntPtr` can be compiled without marking it `unsafe`, while code using `void*` must be marked `unsafe`). The `Marshal.Read*` and `Marshal.Write*` all follow this rule, and accept `IntPtr`. Would it be possible to add additional overloads to the methods that accept a `void*` to instead accept a `IntPtr`? To be specific, the method I'd love to have "safe" is `Unsafe.AsRef<>`, but as they say in Italy, _appetite comes while eating_.

**Comment by svick** [comment]
According to https://github.com/dotnet/coreclr/issues/18150#issuecomment-392530423, not having to use `unsafe` if you're actually writing unsafe code is a bad thing, not something that should be promoted by adding APIs such as the one you propose.

Why do you think avoiding `unsafe` on its own is a good thing?

**Comment by xanatos** [comment]
I've found another similar comment for `Span<T>` (https://github.com/dotnet/corefx/issues/18946#issuecomment-297579578) and you are all technically right. I always thought that manipulating a `IntPtr` is as much unsafe as a `void*`. You have choosen to make a "library style" "breaking change" on this (no more `IntPtr` for reading/writing memory). And I see the reason. 

Clearly my problem is a "social" one: if I use `int n = Marshal.ReadInt32()` my boss won't say anything, but if I use a `int n = *p` with `int *p` I'll have to justify myself to him in triplicate copy... And the first time I'll have to modify a flag in the csproj. And everyone will tell me that my unsafe code will destroy the world (while the same code using `Marshal.ReadInt32()` was perfectly safe). The real problem is that in C# `unsafe` is morally placed inside the leper hospital, while there are tons of things that are as much unsafe that aren't (pinvoke, `Marshal.*` ...)

**Comment by jkotas** [comment]
Right, C# `unsafe` keyword controls access to unsafe C# language features. It does not control access to equally unsafe APIs, so it does not guarantee much in practice unfortunately.

> Clearly my problem is a "social" one

Maybe pointing your boss or team members to this discussion may help?
