### ISSUE TITLE
System.IO.Ports CI tests failing on Windows 10 Nano

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#29982]
https://mc.dot.net/#/user/tarekgh/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Frelease~2F2.1~2F/test~2Ffunctional~2Fcli~2F/eb499046eb64eb3ef3159a85bd666fab98eb9a39/workItem/System.IO.Ports.Tests

**Comment by carlossanlop** [comment]
Triage: Closing this issue until we get further hits.
