### ISSUE TITLE
Remove place holders on packages for TFM UAPvNext from release/2.1 branch

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#29999]
Some of our packages for assemblies outside the shared framework still have placeholders for UAPvNext. We recently shipped them on the 2.1 release, and this caused problems when trying to consume them if you were targetting uap and your TPMinV is higher than RS3. The reason, is that now you won't get an asset for these packages anymore because of the placeholder, and the assemblies aren't really inbox yet as we haven't yet shipped a version of the UAP Metapackage that contains them which basically means that people are now in a broken state. This issue is to track the work for removing those placeholders from our packages on the release/2.1 branch.

cc: @weshaggard @ericstj

**Comment by karelz** [comment]
Fixed in release/2.1 branch in PR #29970. Part of 2.1.1 release.
