### ISSUE TITLE
Remove StringBuilderCache from System.Runtime.Extensions

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#29997]
System.Runtime.Extensions still uses StringBuilderCache in a few places. The usage should be replaced with `ValueStringBuilder`, with an initial reasonably sized stackalloc'ed char array. E.g:

``` C#
    Span<char> initialBuffer = stackalloc char[32];
    var builder = new ValueStringBuilder(initialBuffer);
```

### First Location

`System.ApplicationId.ToString()`

https://github.com/dotnet/corefx/blob/6dd451f51451a7d0ceea6104b51bd17005e9a0e6/src/System.Runtime.Extensions/src/System/ApplicationId.cs#L42-L68

### Second location

`System.Net.WebUtility.HtmlEncode()`

https://github.com/dotnet/corefx/blob/6dd451f51451a7d0ceea6104b51bd17005e9a0e6/src/System.Runtime.Extensions/src/System/Net/WebUtility.cs#L168-L174

### Third location

`System.Environment.ExpandEnvironmentVariablesCore()` (on Unix, Windows already changed)

https://github.com/dotnet/corefx/blob/2c734d6db0a8009150bac59f13960f463528ba76/src/System.Runtime.Extensions/src/System/Environment.Unix.cs#L31-L55

**Comment by jkotas** [comment]
#27250 has work towards `System.Net.WebUtility.HtmlEncode()`

**Comment by danmosemsft** [comment]
Would such a change need perf measurements or is it unnecessary?

**Comment by jkotas** [comment]
It never hurts to sanity check performance impact for changes like these.

**Comment by JeremyKuhne** [comment]
My main concern here is killing off a cached stringbuilder that is local to this assembly.

**Comment by leotsarev** [comment]
Hi, I'll try to fix this.

**Comment by ViktorHofer** [comment]
Please make sure to either add perf tests if there are none for the touched scenarios or benchmark locally with BenchmarkDotNet. That gives us more confidence.
