### ISSUE TITLE
Conflicting definitions of `BCryptGenRandom()`.

### ISSUE THREAD

**Issue by baulig** [dotnet/corefx#30004]
I am currently trying to adapt the random number generators (both the non-cryptographic version and the cryptographic version) to Mono and stumbled upon two different versions of `BCryptGenRandom()`:

There is the version in [src/Common/src/CoreLib/Interop/Windows/BCrypt/Interop.BCryptGenRandom.cs](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/Interop/Windows/BCrypt/Interop.BCryptGenRandom.cs#L13), which is `int BCryptGenRandom(byte*, int)` - this class also defines `GetRandomBytes(byte*, int)`.

And then there is the version in [src/Common/src/Interop/Windows/BCrypt/Interop.BCryptGenRandom.cs](https://github.com/dotnet/corefx/blob/master/src/Common/src/Interop/Windows/BCrypt/Interop.BCryptGenRandom.cs#L13), which is `NTSTATUS BCryptGenRandom(ref byte, int)`.

Looking at [RandomNumberGeneratorImplementation.Windows.cs](src/System.Security.Cryptography.Algorithms/src/Internal/Cryptography/RandomNumberGeneratorImplementation.Windows.cs), this calls the `ref byte` version.

Then [src/Common/src/CoreLib/System/HashCode.cs](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/HashCode.cs#L70) calls `Interop.GetRandomBytes((byte*)&result, sizeof(uint))`.

The problem is that both versions define `BCRYPT_USE_SYSTEM_PREFERRED_RNG`, so you cannot include both source files at the same time.

Before making a PR to remove / rename one of them, I would like to ask why the two versions exist in the first place and how you would feel about maybe unifying them into just one.

**Comment by jkotas** [comment]
> I would like to ask why the two versions exist in the first place

Two different people writing the code in two different repos.

This was skipped in #27841 for some reason. Feel free to submit PR to fix it.

cc @MarcoRossignoli

**Comment by MarcoRossignoli** [comment]
> This was skipped in #27841 for some reason.

@jkotas i avoided to touch too different files(also method with different signature, i should have to change call sites and maybe some code, the starting idea of issue was replace files differs by a percentage).
But, having said that, if you think we should go deeper feel free to reopen issue and assign it to me, i'll do another pass through and we'll discuss case by case if i'm in trouble, sometimes is not so clear to me understand  which codebase are better or newer.

@baulig i apoligize, let me know if you'll fix this or i can do that for you.

**Comment by baulig** [comment]
Well, you know the code better than me and I'm also not too familiar with your naming conventions, so I'd really appreciate it if you could fix this.

**Comment by MarcoRossignoli** [comment]
@baulig  we cleaned up you can use file in this folder https://github.com/dotnet/corefx/tree/master/src/Common/src/CoreLib/Interop/Windows/BCrypt
