### ISSUE TITLE
Why IWebHost.Run executes before the Configure method in Startup,in aspnetcore 2.1?

### ISSUE THREAD

**Issue by zpf1989** [dotnet/corefx#30006]
Hello,thanks for your great job!
Noticed the publish of the aspnetcore 2.1,I update my codes instantly.
But I find a strange thing that ,when run the app,the Run method of IWebHost excutes before the Configure method in my Startup class.
I have something code in my custom RunWenHealthy method,which checks some dependencies of my app,and then call the official Run api when checks succeed.
In my RunWenHealthy method, I use configuration set in the Configure method to do the checks.
**Before aspnetcore  2.1,it works fine.**
**So is it normal for aspnetcore  2.1?**
Below is my codes,please have a look .
Thank you!
[WebApplication1.zip](https://github.com/dotnet/corefx/files/2056374/WebApplication1.zip)

**Comment by davidfowl** [comment]
Configure runs when the host is started vs when the host was built.

**Comment by zpf1989** [comment]
Sorry,I can't get your point,could you please explain in detail?
And is this as designed ?
@davidfowl 
Thanks for your time!

**Comment by zpf1989** [comment]
OK,thanks for the guide.
I'll change my code.
