### ISSUE TITLE
Missing dlls in bin/pkg/netcoreapp/runtime for BinPlaceNETCoreAppPackage=true

### ISSUE THREAD

**Issue by gbalykov** [dotnet/corefx#30013]
Hello.

Looks like `bin/runtime` and `bin/pkg/netcoreapp/runtime` contain different sets of dlls on `release/2.0.0` branch for `BinPlaceNETCoreAppPackage=true`. For example, System.Memory.dll is missing in `bin/pkg/netcoreapp/runtime` but exists in `bin/runtime`. On `master` branch System.Memory.dll exists in both folders.

Could you, please, clarify if this is correct behavior or this should be fixed?

cc @alpencolt @Dmitri-Botcharnikov

**Comment by karelz** [comment]
@joperezr @weshaggard do you know if this is specific to System.Memory?

**Comment by gbalykov** [comment]
@karelz, this dlls also exist only in `bin/runtime`

OSExtensions.dll
SOS.NETCore.dll
System.CodeDom.dll
System.ComponentModel.Composition.dll
System.Composition.AttributedModel.dll
System.Composition.Convention.dll
System.Composition.Hosting.dll
System.Composition.Runtime.dll
System.Composition.TypedParts.dll
System.Configuration.ConfigurationManager.dll
System.Data.DataSetExtensions.dll
System.Data.Odbc.dll
System.Data.SqlClient.dll
System.Diagnostics.EventLog.dll
System.Diagnostics.PerformanceCounter.dll
System.DirectoryServices.AccountManagement.dll
System.DirectoryServices.dll
System.DirectoryServices.Protocols.dll
System.Drawing.Common.dll
System.IO.Packaging.dll
System.IO.Pipelines.dll
System.IO.Ports.dll
System.Json.dll
System.Management.dll
System.Net.Http.WinHttpHandler.dll
System.Net.WebSockets.WebSocketProtocol.dll
System.Reflection.Context.dll
System.Runtime.Caching.dll
System.Runtime.CompilerServices.Unsafe.dll
System.Runtime.Intrinsics.Experimental.dll
System.Security.Cryptography.Pkcs.dll
System.Security.Cryptography.ProtectedData.dll
System.Security.Cryptography.Xml.dll
System.Security.Permissions.dll
System.ServiceModel.Syndication.dll
System.ServiceProcess.ServiceController.dll
System.Text.Encoding.CodePages.dll
System.Text.Encodings.Web.dll
System.Threading.AccessControl.dll
System.Threading.Channels.dll

**Comment by weshaggard** [comment]
>Could you, please, clarify if this is correct behavior or this should be fixed?

That is the correct behavior. With BinPlaceNETCoreAppPackage=true it will create a subset of what we build in corefx under bin/pkg/netcoreapp/runtime. That subset maps directly to what is part of Microsoft.NETCore.App (aka the shared framework). In 2.0 System.Memory was not part of it but in 2.1 is is which is why you see the difference.

**Comment by joperezr** [comment]
As @weshaggard said, basically bin/runtime will contain everything we build in a vertical that is not a reference assembly, or test project. Not all of that goes into the shared framework, which is why we have the other folder (bin/pkg/netcoreapp/runtime) which does have only the shared framework.

**Comment by gbalykov** [comment]
@weshaggard @joperezr thank you for your comments!
