### ISSUE TITLE
Add method to detect float NaN and infinity values in one convenient call

### ISSUE THREAD

**Issue by GSPP** [dotnet/corefx#30018]
I sometimes find the need to validate that some floating point value in my application's logic is not NaN or an infinity value. Often, when such a value occurs it's a bug. So it's valuable to detect them and raise an error.

The framework should have a method to do this. Motivating code snippet:

        public static TimeSpan MultiplyTimeSpan(TimeSpan timeSpan, double factor)
        {
            if (double.IsNaN(factor) || double.IsInfinity(factor)) throw new ArgumentException();
            return new TimeSpan((long)Math.Round(timeSpan.Ticks * factor));
        }

Here, `double.IsNaN(factor) || double.IsInfinity(factor)` should be a method available on the `double` type.

```
struct Double
{
  public static IsSpecialValue(double value) => IsNaN(value) || IsInfinity(value);
}
```

NaN and infinity are all possible special values, right? This should catch anything that does not behave like a normal number.

**Comment by 4creators** [comment]
IMO it is very good proposal, however, IMO it would be easier to do combined binary test for NaN and infinity on floats instead of doing them sequentially.

**Comment by tannergooding** [comment]
@GSPP, I added these functions some time back: https://github.com/dotnet/corefx/issues/16841

The query to do is `!double.IsFinite(factor)`.

We have:
* `IsFinite`: Determines whether the specified value is finite (zero, subnormal, or normal).
* `IsInfinity`: Determines whether the specified value is infinite.
* `IsNaN`: Determines whether the specified value is NaN.
* `IsNegative`: Determines whether the specified value is negative.
* `IsNegativeInfinity`: Determines whether the specified value is negative infinity.
* `IsNormal`: Determines whether the specified value is normal.
* `IsPositiveInfinity`: Determines whether the specified value is positive infinity.
* `IsSubnormal`: Determines whether the specified value is subnormal.

**Comment by tannergooding** [comment]
(Sorry, clicked the wrong button, didn't mean to close).

**Comment by GSPP** [comment]
@tannergooding that's awesome! What's the process to move these changes to the desktop framework? As I understand it Microsoft intends to keep the code bases largely synchronized where possible, correct?

**Comment by tannergooding** [comment]
The desktop framework is updated at a much slower cadence than .NET Core (give that it has to ship as an update to Windows, among other reasons).

If you want to use them today, the easiest mechanism is likely to just copy the implementation directly: http://source.dot.net/#System.Private.CoreLib/shared/System/Double.cs,02ee32eb42d32941

Someone else may be able to provide more concrete information.

**Comment by tannergooding** [comment]
@GSPP, is there anything else you feel this bug should track, or are we good to close it?

**Comment by GSPP** [comment]
This is totally solved, thank you.
