### ISSUE TITLE
Documentation for the StopWatch class is incorrect

### ISSUE THREAD

**Issue by glennawatson** [dotnet/corefx#30016]
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/Diagnostics/Stopwatch.cs

The documentation is currently
```csharp
   // This class uses high-resolution performance counter if installed hardware 
    // does not support it. Otherwise, the class will fall back to DateTime class
    // and uses ticks as a measurement.
```

I believe the portion  This class uses high-resolution performance counter if installed hardware **does not support it.**

I believe you mean "supports it"

**Comment by karelz** [comment]
Thanks for catching it @glennawatson! Do you want to submit a PR?

**Comment by glennawatson** [comment]
Can do. Will submit in the next 24 hours.
