### ISSUE TITLE
BrotliStream decompresser reads misaligned chunks on repetetive data; TryDecompress works

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/corefx#30030]
I've got a large data blob that reliably causes BrotliStream to read misaligned chunks or drop chunks while BrotliDecoder functions correctly.

I made a publicly-uploadable version by replacing sensitive info with multiple copies of Moby Dick.

Here is the test code. It raises "BrotliStream chunk trouble; bytes are the same but the stream isn't." at the same place every time. The second and third lines are almost the same "b nn" is not quite the same as "been". Due to the differing failure mode, it's possible that my original NDA-requiring tablebase.dat is a different bug.

```c#
    using System;
    using System.IO;
    
    namespace brotlitrouble
    {
        class Program
        {
            static void Main(string[] args)
            {
                var sourceArray = File.ReadAllBytes("whale.dat");
                var uclen = sourceArray.Length;
                var m = System.IO.Compression.BrotliEncoder.GetMaxCompressedLength(uclen);
                int size;
                byte[] result;
                result = new byte[m + 8];
                if (!System.IO.Compression.BrotliEncoder.TryCompress(sourceArray, result.AsSpan(8, m), out size))
                    throw new Exception("BrotliEncoder.TryCompress was given enough memory; why did it fail?");
                Console.WriteLine("compressed size is " + size.ToString());
                Array.Resize(ref result, size + 8);
                // Diagnostic check; this one passes
                var check = new byte[sourceArray.Length];
                if (!System.IO.Compression.BrotliDecoder.TryDecompress(result.AsSpan(8, size), check, out int writecheck)
                    || !ByteArrayEquals(sourceArray, 0, sourceArray.Length, check, 0, check.Length))
                    throw new Exception("BrotliDecoder.TryDecompress did not invert BrotliEncoder.TryCompress");
                // Diagnostic check; this one fails
                var mbc = new MemoryStream(result);
                mbc.Position = 8;
                using (var saa = new StreamReader(new System.IO.Compression.BrotliStream(mbc, System.IO.Compression.CompressionMode.Decompress)))
                using (var sbb = new StreamReader(new MemoryStream(sourceArray)))
                {
                    for (; ; )
                    {
                        var linea = saa.ReadLine();
                        var lineb = sbb.ReadLine();
                        if (linea != lineb)
                            throw new Exception("BrotliStream chunk trouble; bytes are the same but the stream isn't." + Environment.NewLine + linea + Environment.NewLine + lineb);
                        if (linea is null) break;
                    }
                }
            }
    
            static bool ByteArrayEquals(byte[] s, int sstart, int slen, byte[] t, int tstart, int tlen)
            {
                if (slen != tlen) return false;
                for (int i = 0; i < slen; i++)
                    if (s[sstart + i] != t[tstart + i])
                        return false;
                return true;
            }
        }
    }
```

You'll need to uncompress whale.zip to get whale.dat because github won't let me upload whale.dat directly.

[whale.zip](https://github.com/dotnet/corefx/files/2063385/whale.zip)

**Comment by stephentoub** [comment]
> System.IO.Compression.BrotliDecoder.TryDecompress(result.AsSpan(8, m - 8), check, out int writecheck)

You're passing in the whole result area.  Shouldn't that instead be slicing the result to only the portion that was actually written to, i.e. influenced by `size`, by the number of bytes actually written by the encoder?

**Comment by jhudsoncedaron** [comment]
I've been pondering how I can attempt this since 5pm yesterday but I can't guarantee being able to do this. Thanks for asking.

**Comment by jhudsoncedaron** [comment]
>  Shouldn't that instead be slicing the result to only the portion that was actually written to, i.e. influenced by size, by the number of bytes actually written by the encoder?

No, sorry. Bisection eliminated the Array.Resize call. Putting it back doesn't make it go away. I fixed the sample code anyway.

**Comment by stephentoub** [comment]
> No, sorry. Bisection eliminated the Array.Resize call. Putting it back doesn't make it go away. I fixed the sample code anyway.

I don't understand.  The code has this:
```C#
                if (!System.IO.Compression.BrotliDecoder.TryDecompress(result.AsSpan(8, m - 8), check, out int writecheck)
                    || !ByteArrayEquals(sourceArray, 0, sourceArray.Length, check, 0, check.Length))
                    throw new Exception("BrotliDecoder.TryDecompress did not invert BrotliEncoder.TryCompress");
```
That's wrong.  `result.AsSpan(8, m-8)` includes potentially many more bytes than the encoder wrote, so the decoder is potentially going to try to decompress garbage.  Seems like it would need to be something more like `result.AsSpan(8).Slice(0, size)` for the TryDecompress call, and the ByteArrayEquals would similarly need to be fixed up to not assume the full length of the arrays.

**Comment by stephentoub** [comment]
> System.IO.Compression.BrotliEncoder.TryCompress(sourceArray, result.AsSpan(8, m - 8), out size)

That code also looks wrong.  `m` is the potential length, and the second argument to AsSpan is the length... so that should be `AsSpan(8, m)` or just `AsSpan(8)`.

**Comment by jhudsoncedaron** [comment]
I managed to construct a publicly-uploadable data file that exhibits the problem. stepehntoub did find some code issues in the original bisection, but none of them would explain the specific error exhibited. After fixing all of them the bug remains.

I am disappointed the reproduction wasn't a spectacular failure like the NDA version where the replacement was a much larger chunk, but only two bytes wrong in the first line found wrong, but that's life.

**Comment by stephentoub** [comment]
> I managed to construct a publicly-uploadable data file that exhibits the problem

Can you share the complete repro then?

**Comment by stephentoub** [comment]
Thanks.  There does appear to be a bug here.  I simplified the repro:
```C#
using System;
using System.IO;
using System.IO.Compression;

class Program
{
    static void Main()
    {
        byte[] sourceBytes = new byte[0x400001]; // any value larger than 0x400000; array contents doesn't matter
        Console.WriteLine(sourceBytes.Length);

        byte[] compressedBytes;
        var tmpStream = new MemoryStream();
        using (var compressor = new BrotliStream(tmpStream, CompressionLevel.Fastest))
        {
            compressor.Write(sourceBytes);
        }
        compressedBytes = tmpStream.ToArray();
        Console.WriteLine(compressedBytes.Length);

        using (var origStream = new MemoryStream(sourceBytes))
        using (var decompressedStream = new BrotliStream(new MemoryStream(compressedBytes), CompressionMode.Decompress))
        {
            int pos = 0;
            while (true)
            {
                int a = origStream.ReadByte();
                int b = decompressedStream.ReadByte();
                if (a != b)
                {
                    Console.WriteLine("Different byte at pos: " + "0x" + pos.ToString("x"));
                    break;
                }
                else if (a == -1)
                {
                    break;
                }
                pos++;
            }
        }
    }
}
```
Any input larger than 4MB starts having the wrong output at the 4MB mark (0x400000).

cc: @ianhays

**Comment by jhudsoncedaron** [comment]
I'm impressed you got it to reproduce with 4 megabytes of zeros. I was always getting chunks that occurred later in the file.

**Comment by stephentoub** [comment]
Fixed in master

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/corefx/pull/30066
