### ISSUE TITLE
crossgen.sh: line 80: $2: unbound variable

### ISSUE THREAD

**Issue by Mpdreamz** [dotnet/corefx#30043]
When trying to run `build.sh` on a clean check out from WSL.

**Comment by karelz** [comment]
I assume it is from here:
https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/crossgen.sh#L80

Can you fish out the command line from build logs? Or maybe echo the args for debugging ...

**Comment by karelz** [comment]
@wtgodbe can you please help investigate?

**Comment by wtgodbe** [comment]
Sure, I can take a look later on today

**Comment by karelz** [comment]
Make sure you did git clone from WSL and you do not share the one done from Windows (CRLF are different).
As a workaround you can consider using Docker image.

**Comment by wtgodbe** [comment]
@Mpdreamz what Linux distro are you running in WSL? Did you install all the prereqs listed at https://github.com/dotnet/corefx/blob/master/Documentation/building/unix-instructions.md? I got a clean build running on Ubuntu 16.04, and making sure to install `libicu55` instead of `libicu52`
