### ISSUE TITLE
Make it easy for large StringBuilders to be written to TextWriters without making a large string 

### ISSUE THREAD

**Issue by vancem** [dotnet/corefx#30048]
It is actually pretty common for HTTP servers to create a large response HTML string built up with a StringBuilder and then write that StringBuilder as the response.  A similar scenario can happen with simply file I/O.     However until recently,  the only obvious way to get the data out of a StringBuilder was the ToString() routine that generates a string (it copies its value), which is a needless inefficiency (and often makes a GC Large object, which don't get collected promptly).  

Recently StringBuilder added the StringBuilder.GetChunks() that allow the value of the stringbuilder to be efficiently fetched as a series of ReadOnlyMemory<char> chunks.  (see https://github.com/dotnet/corefx/pull/29877), which now make this possible (users can write a small loop to do it), but not convenient.

TextWriters already have a Write(ReadOnlySpan<char>) and WriteAsync(ReadOnlyMemory<char>, CancellationToken) which understand how to write out spans of characters.

The proposal here is to add the following overloads to TextWriter

```c#
class TextWriter {
    public virtual void Write(StringBuilder value);
    public virtual void WriteLine(StringBuilder value);
    public virtual Task WriteAsync(StringBuilder value, CancelationToken cancellationToken=default);
    public virtual Task WriteLineAsync(StringBuilder value, CancelationToken cancellationToken=default);
}
```

Which simply use StringBuilder.GetChunks() and write the short loop to pass it to the Write method that take ReadOnlySpan (for write) or ReadOnlyMemory (for writeAsync).    Thus this is a convenience routine (but a very nice convenience routine).   

Issues:

I can see at least three interesting discussion points associate with this change.  

1. Dependency issues.   This change makes TextWriter (which previously did NOT depend on StringBuilder, to now depend on it).    We may wish to make these methods extension methods for this reason.     However as a practical matter StringBuilder is implemented in System.Private.Corelib and exposed via System.Runtime, which is the base dependency for ALL code (since it includes System.Object), so it will not cause a practical problem, and thus the suggestion above is to implement it in the most straightforward way possible (which is to make it instance methods of TextWriter)

2. This pattern (of using StringBuilder) is likely to be superseded by the UTF8 String work.   Long term we want to get off of using Char (16 bit unicode) because it can't actually represent all of unicode anymore.   This is what the UTF8String is about.  When this comes out (it is probably a year away), this work will not be as important.    The counter argument is that StringBuilder will have non-trivial customers for years yet, and this is a small, easy change that adds value for those customers.   Thus the proposal is that we do it. 

3.  Where do we stop adding StringBuilder overloads?   This is one place and you can imagine others.   Why no those?   This is reasonable, but should not block this work.   This overload has pretty clear value for the scenario described (making a big stringBuilder and writing it to a TextWriter).   It is very likely the highest value addition.   We can add more (now, or in stages or whatever), but this change seems easy, useful and we will not have regrets about adding it.   If people have other places that we believe are 'high value' that we should add now, I am happy to add them to this proposal.  

As mentioned the implementation is pretty trivial.  We mostly need API approval.  

Added the WriteLine methods as well from review feedback below.  

@stephentoub @jkotas @KrzysztofCwalina @terrajobst

**Comment by terrajobst** [comment]
Looks good as proposed.

A few minor suggetions

```csharp
class TextWriter {
    public virtual void Write(StringBuilder value);
    public virtual void WriteLine(StringBuilder value);
    public virtual Task WriteAsync(StringBuilder value, CancelationToken cancellationToken);
    public virtual Task WriteLineAsync(StringBuilder value, CancelationToken cancellationToken);
}
```
