### ISSUE TITLE
System.Text.Encoding.CodePages 4.4.0 and 4.5.0 don't have unix runtime

### ISSUE THREAD

**Issue by SteveL-MSFT** [dotnet/corefx#30059]
v4.3.0 included unix runtime, but 4.4.0 and new 4.5.0 don't have unix runtime anymore.  This was found trying to move PSCore6.1 to include v4.5.0 of that pkg.

**Comment by SteveL-MSFT** [comment]
Looks like the issue we had was with xunit.  Moving to a newer version fixed this.  Still not sure if that pkg should have a unix runtime like older versions, but not impacting us now.

**Comment by tarekgh** [comment]
chatted with @weshaggard and he mentioned System.Text.Encoding.CodePages doesn't need to have Linux runtime there as it is expected to have the netstandard lib will be used. I am closing this issue but feel free to reply if you have any more questions.
