### ISSUE TITLE
Not able to re-assign an Empty Span to a ReadOnlySpan over stack space

### ISSUE THREAD

**Issue by Anipik** [dotnet/corefx#30068]
``` C#
Span<char> a = stackalloc char[100];
ReadOnlySpan<char> path =  a.Slice(0);
ReadOnlySpan<char> test = ReadOnlySpan<char>.Empty;
test = path
```

this piece of code is giving me an error 
```
Cannot use local 'path' in this context because it may expose referenced variables outside of their declaration scope.
```

is it desired behavior ?

cc @danmosemsft @ahsonkhan

**Comment by stephentoub** [comment]
The error is valid based on the compiler's current rules. By initializing test with Empty, you're creating a span that's allowed to be returned out of this method. As path is not, assigning path to test would violate the that constraint.

If you have concerns with the behavior, you can open an issue in the Roslyn repo. I believe in this particular case, if you instead initialize temp to stackalloc char[0], the error should go away.
