### ISSUE TITLE
clrcompression.vcxproj fails to build on my machine

### ISSUE THREAD

**Issue by Mpdreamz** [dotnet/corefx#30073]
Following: https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md

On a clean checkout (`git clean -fxd` and `clean.cmd -all`) `build.cmd` against ef0d4171ea29afc03c5098a8fef7c7e3ec11657c fails to build  `clrcompression.vcxproj`  on my machine.

This is on Windows 10 Version 1803 (1766.1000).

Complete output here: https://gist.github.com/Mpdreamz/a6b40e8e591c2b9af49cbe5a74155ff7

All the errors are in the form of:

> c1 : fatal error C1083: Cannot open source file: 'C:\Projects\corefx\src\Native\Windows\clrcompression\zlib-intel\adler32.c': No such file or directory [C:\Projects\corefx\bin\obj\Windows_NT.x64.Debug\native\clrcompression\clrcompression.vcxproj]

But `C:\Projects\corefx\src\Native\Windows\clrcompression\zlib-intel\adler32.c` does in fact exist on my machine.

**Comment by Mpdreamz** [comment]
Trying to diagnose this individual build locally through 

> c:\Projects\corefx\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false /l:BinClashLogger,Tools\net46\Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log /p:ConfigurationGroup=Debug /p:BuildPackages=false  /flp:v=normal  /flp2:warningsonly;logfile=msbuild.wrn  /flp3:errorsonly;logfile=msbuild.err  c:/Projects/corefx/src/Native/../../bin/obj/Windows_NT.x64.Debug/native\install.vcxproj /t:rebuild /p:Configuration=Debug /p:Platform=x64 /p:PlatformToolset=v141

**Comment by ViktorHofer** [comment]
No such file or directory could also indicates that it can't access the file because of restrictive permissions. My bet is that the file is locked infinitely by another process. Have you tried to restart and build again?

**Comment by Mpdreamz** [comment]
So this ended up being an issue because i cloned my fork through my WSL zsh shell while running the build from CMD.

Doing a git clone from `CMD` and then a `build.cmd` seems to work. Investigating now which files end up being different between the different checkouts now.

**Comment by ViktorHofer** [comment]
Right, that's not really a supported scenario. My bet is either a difference in line endings or wrong applied permissions during the git clone in WSL. I'm closing this now as we found a workaround.
