### ISSUE TITLE
Task causes InvalidCastException casting s_taskCompletionSentinel to List<object>

### ISSUE THREAD

**Issue by jnm2** [dotnet/corefx#30086]
I'm running into an issue that looks like a bug, though probably there are restrictions on when `FinishContinuations` may be called that I am not aware of.
`continuationObject ` is being read as  `s_taskCompletionSentinel` for me here:
https://github.com/dotnet/coreclr/blob/v2.1.0/src/mscorlib/src/System/Threading/Tasks/Task.cs#L3234-L3247

Which causes this cast to `List<object>` to fail, since it's trying to cast `s_taskCompletionSentinel`:
https://github.com/dotnet/coreclr/blob/v2.1.0/src/mscorlib/src/System/Threading/Tasks/Task.cs#L3299

Shouldn't [this line](https://github.com/dotnet/coreclr/blob/v2.1.0/src/mscorlib/src/System/Threading/Tasks/Task.cs#L3243) be `if (continuationObject != null && continuationObject  !=  s_taskCompletionSentinel)`?

Here's the PR that changed it from a safe cast to a direct cast: https://github.com/dotnet/coreclr/pull/9471/files#diff-9e9a920444355b78dc1fb28c79fec014L3249 (/cc @stephentoub)

**Comment by jnm2** [comment]
To be clear: my repro involves building .NET Core 2.1.0's Task.cs on .NET Framework 3.5 with almost no modifications. This is probably more of a question than anything. Is there something that is supposed to guarantee that FinishContinuations is never called twice?

**Comment by stephentoub** [comment]
> Is there something that is supposed to guarantee that FinishContinuations is never called twice?

Yes, there are state transitions in task that guarantee it's only called once, as part of whatever call actually transitions the task to a completed state.

**Comment by jnm2** [comment]
Thanks, that answers my question!
