### ISSUE TITLE
Short-circuit key comparison on equal indexes in EnumerableSorter in System.Xml.XDocument

### ISSUE THREAD

**Issue by VSadov** [dotnet/corefx#3008]
System.Xml.XDocument has its own copy of EnumerableSorter and possibly can benefit from the same fix as in
https://github.com/dotnet/corefx/pull/2977

**Comment by JonHanna** [comment]
Or perhaps from something different again…

**Comment by epsitec** [comment]
@JonHanna I like the solution you propose in #3017, which is focused on the task at hand.

**Comment by stephentoub** [comment]
Fixed by #3017
