### ISSUE TITLE
Running performance tests ignores the xunitmethodname property

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#30087]
Using either xunitoptions property with -method as shown below:

`msbuild /t:rebuildandtest /p:Performance=true /p:ConfigurationGroup=Release /p:TargetOS=Windows_NT /p:xunitoptions="-method System.Tests.Perf_Environment.ExpandEnvironmentVariables"`

or using xunitmethodname as shown below:

`msbuild /t:rebuildandtest /p:Performance=true /p:ConfigurationGroup=Release /p:TargetOS=Windows_NT /p:xunitmethodname=System.Tests.Perf_Environment.ExpandEnvironmentVariables`

Should run the single specified test but the combination of commands above will run all tests instead.

I'm creating this issue to track the problem. Will need to confirm if it has to do with the combination of using `Performance=true` along with specifying the method name.

cc: @ViktorHofer @Anipik @safern @leotsarev

**Comment by ViktorHofer** [comment]
It should be this line causing the error: https://github.com/dotnet/buildtools/blob/f522532cd9c3a342c02ec73a9e99c753e7df3d13/src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets#L89

**Comment by ViktorHofer** [comment]
Took a closer look and the perf engine is built differently and does not support the same options as for normal unit tests. Closing.

**Comment by Anipik** [comment]
@ViktorHofer is there any other way to run the single performance test if you cant use the conventional way ?

**Comment by ViktorHofer** [comment]
Either comment out / remove all other performance tests temporarily or just all of them. Why must it be just one?

**Comment by ViktorHofer** [comment]
It's not worth adding any additional functionality to xunit-performance as it will be replaced soon.
