### ISSUE TITLE
ClientWebSocket - Span based APIs

### ISSUE THREAD

**Issue by deinok** [dotnet/corefx#30095]
Seems like ClientWebSockets only have `ArraySegment<byte>`APIs.

Should the ClientWebSockets class have `Span<byte>` / `ReadOnlySpan<byte>` APIs?

**Comment by stephentoub** [comment]
It has new `Memory<T>`-based receive and send methods in .NET Core 2.1.

**Comment by davidsh** [comment]
Seems like the question has been answered.  Memory<T> is the desired API pattern now.
