### ISSUE TITLE
Windows setup instructions are missing an individual component

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/corefx#30094]
Ported from: https://github.com/dotnet/corefxlab/issues/2217

If you install VS with only the specified [individual components](https://github.com/MisinformedDNA/corefx/blob/e9fcc23ffc5e73d062536b2473ccda66a74315ba/Documentation/building/windows-instructions.md#visual-studio-2017---individual-components-based-install), VS will think it needs to upgrade the projects. Only after also installing the .NET workload, does the issue go away. Instructions need to be updated to specify a complete list of components needed.

**Comment by ahsonkhan** [comment]
@karelz, only installing what's in the list of components within [Visual Studio 2017 - 'Individual components' based install](https://github.com/dotnet/corefx/wiki/Development-environment-setup-for-Windows#visual-studio-2017---individual-components-based-install) doesn't seem to be enough. @MisinformedDNA discovered that we still need to install the .NET Core cross-platform development workload to build repos like corefxlab.sln within VS. I couldn't find the components that the workload install is bringing in within the individual components list. Any ideas?

**Comment by MisinformedDNA** [comment]
I also tried installing the .NET Core workload with all optional components turned off and it worked, so it is probably one of required components. Here's a list of all the components: https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community#net-core-cross-platform-development

**Comment by karelz** [comment]
Is it needed also for CoreFX repo?

**Comment by ViktorHofer** [comment]
I don't think so as just installing the individual components worked for me locally.

**Comment by ViktorHofer** [comment]
Updated the instructions recently. Just installing the individual workloads should work now.
