### ISSUE TITLE
System.Runtime.Tests failing on uapaot

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#30093]
Failing with the error assembly `nonexistent.dll` not found. Try reinstalling the application.

https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/PseudoCustomAttributeTests.cs

cc @joperezr @safern @AlexGhiondea @danmosemsft

**Comment by ViktorHofer** [comment]
Now I also get the error that `libc.dll` is not found.

**Comment by danmosemsft** [comment]
That is https://github.com/dotnet/corefx/issues/30423 / https://github.com/dotnet/corefx/issues/30399 which @luqunl is looking at.

**Comment by ViktorHofer** [comment]
Thanks. Closing as dup.
