### ISSUE TITLE
https proxy and custom proxy providers

### ISSUE THREAD

**Issue by lobster2012-user** [dotnet/corefx#30109]
Hello.

1. Why socketshttphandler does not support HTTPS PROXY? Is it because of compatibility?
2. Add custom proxy providers.
```
ProxyTunnelFactory.RegisterProvider("socks5", Socks5ProxyProvider);

public interface IProxyProvider
{
    Task<(stream,....)> EstablishProxyTunnel(_proxyUri)
}

    case HttpConnectionKind.CustomProxyTunnel:
             stream = await customerProvider.EstablishProxyTunnel(_proxyUri, _host, _port)
```

Thank you.

**Comment by davidsh** [comment]
This issue is duplicative of #9768

**Comment by stephentoub** [comment]
Closing as dup.

**Comment by lobster2012-user** [comment]
@stephentoub 
OK, this is a feature, not a bug.
Then why  this methods (or overrides not exists) 
```
ReadAsByteArrayAsync (Call LoadIntoBufferAsync -> CompletedTask or SerializeToStreamAsync(token)
ReadAsStringAsync (Call LoadIntoBufferAsync -> CompletedTask or SerializeToStreamAsync(token)
```
do not they take the CancellationToken.

**Comment by stephentoub** [comment]
> I can duplicate all the code, but it will be more beautiful to add a token as param.

You're welcome to open an API proposal for that.
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md

**Comment by lobster2012-user** [comment]
@stephentoub 
Sorry, I wrote in the wrong topic

**Comment by davidsh** [comment]
Regarding adding Http APIs that accept a CancellationToken, we do have this open issue regarding the HttpContent methods (ReadAsStringAsync, et. al.)

#9071
