### ISSUE TITLE
Should string manipulations be allowed to return the string itself?

### ISSUE THREAD

**Issue by yufeih** [dotnet/corefx#3011]
String manipulation method like *Replace, Trim, ToLower* allocates a brand new string even if the result is identical to the input. To optimize for memory allocation, these methods can be changed to only create a new string only when it detects that the result is different. 

This benifits a lot of use cases like *replacing all \ with / in a file path*

Given that string is immutable, this optimization has no side effects except that the returned object might now be reference equal to the input. According to https://github.com/dotnet/corefx/issues/2363, reference equality can be relaxed in certain cases.

**Comment by stephentoub** [comment]
In many cases, it already does this, e.g.
- Trim: https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/String.cs#L2766-L2773
- Replace: https://github.com/dotnet/coreclr/blob/4cf8a6b082d9bb1789facd996d8265d3908757b2/src/classlibnative/bcltype/stringnative.cpp#L702-L705

Is there a particular case you're concerned about?

**Comment by yufeih** [comment]
Sorry this was an invalid concern :(
