### ISSUE TITLE
Custom error handling is broken in Unix

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#30126]
Subdirectory queue handling is not consistent between Unix/Windows. In error skipping cases we need to be sure that we don't try to process directories we fail to open but don't care about. Unfortunately we queue invalid handles on Unix if we skip errors on opening subdirectories in Unix.

Additionally we don't map errors correctly on Unix. We compare the native error to the PAL mapped error which makes `EnumerationOptions.IgnoreInaccessible` not work on Unix.

This is new functionality- the fix in master is #29908. The port to 2.1 is #30002.

**Comment by danmosemsft** [comment]
fixed
