### ISSUE TITLE
Why the portable ReadOnlySpan has no implicit cast operator from string?

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/corefx#30121]
Today I realized that there is no implicit cast from string to `ReadOnlySpan<char>` for portable version of ReadOnlySpan.

@KrzysztofCwalina can I ask why is that?

```cs
using System;

namespace repro
{
    class Program
    {
        static void Main(string[] args)
        {
	     ReadOnlySpan<char> span = "Hello World!";
             Console.WriteLine(span.ToString());
        }
    }
}

```

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp2.1;net46</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Memory" Version="4.5.0" />
  </ItemGroup>
</Project>
```

```log
PS C:\repro> dotnet run -c Release -f netcoreapp2.1
Hello World!
PS C:\repro> dotnet run -c Release -f net46
Program.cs(9,30): error CS0029: Cannot implicitly convert type 'string' to 'System.ReadOnlySpan<char>' [C:\repro\repro.csproj]

The build failed. Please fix the build errors and run again.
```

**Comment by stephentoub** [comment]
> can I ask why is that?

Where would you define it?  You can't define it on string (because this is the portable version), you can't define it on `ReadOnlySpan<T>`, because then the extension would apply to all Ts and not just `ReadOnlySpan<char>`, and you can't define it as an extension to `ReadOnlySpan<char>` because operators can't be extensions.

**Comment by adamsitnik** [comment]
@stephentoub thanks for the explanation, I forgot about the existing limitations

**Comment by EgorBo** [comment]
We temporarily defined an operator in our string https://github.com/mono/mono/blob/master/mcs/class/corlib/ReferenceSources/String.cs#L54-L61 🙂
