### ISSUE TITLE
Segfault on alpine with a native dep with rid linux-x64 not built for musl still used by shared runtime 

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/corefx#30123]
So we tested running on alpine with a native dep ([Mime](https://github.com/hey-red/Mime/tree/master/src/Mime)) which on lib load triggers a segfault due to glibc/musl differences we presume.

What seems to happen here erroneously is that a shared runtime build doesn't correctly choose linux-musl (or maybe has a fallback to linux-x64, which is also wrong) as the runtime dependency lookup path.

Rids with different c std libs should never default to any of their related/upper rids.

**Comment by karelz** [comment]
@janvorli any thoughts?

**Comment by janvorli** [comment]
@NinoFloris can you please be more specific on what you are trying to do?

**Comment by NinoFloris** [comment]
Quite simple.

1. We have Mime as a dependency (linked in start post)
2. We publish our app as a shared framework/runtime build. 
3. We boot it, shared runtime has code to pick the runtime path for loading libmagic (the native .so that Mime pulls in) e.g. runtimes/linux-x64 etc
4. Runtime picks the linux-x64 path version as there is no linux-musl-x64 <-- this is wrong, it segfaults the runtime due to glibc/musl differences as libmagic wasn't built against musl.

**Comment by kasper3** [comment]
you would need to compile libmagic on alpine with `runtimes/linux-musl-x64` rid. then nuget will restore that one on alpine and linux-x64 one on glibc linux.

**Comment by NinoFloris** [comment]
Yes I know the fix, but the problem is it should never fall back to linux-x64 as they are completely incompatible

**Comment by janvorli** [comment]
cc: @ericstj

**Comment by ericstj** [comment]
That’s true for this package, but another package may have a Linux-x64 asset that’s compatible with musl.  Consider an architecture specific IL assembly that depends on Linux platform api.

**Comment by kasper3** [comment]
and you can optionally install glibc on Alpine too, so it's better to keep the keep the RID graph as permissive as it is today: commentary at https://github.com/dotnet/core-setup/issues/3817 might help you understand better why it is how it is.

**Comment by NinoFloris** [comment]
@kasper3 thanks for that link, hadn't found it. So it's reasonable if that's how .net consistently wants to apply such a policy. Just wasn't sure it was already debated in depth yet, the link ends that doubt ;)
