### ISSUE TITLE
(non)Blittable data

### ISSUE THREAD

**Issue by DanielSSilva** [dotnet/corefx#30133]
First of all I'm not quite familiar with marshalling and dealing with unmanaged resources. 
I was migrating a project  that was compiled and ran with mono and Framework v4.6.1. Basically what I had to do was only change the target framework, yet one thing that made everything stop working was trying to Pin an object into memory with `GCHandle.Alloc`. That threw an exception stating that
`Unhandled Exception: System.ArgumentException: Object contains non-primitive or non-blittable data.`

What I find weird is that this allegedly (I take the word of the owner when [he says that it runs successfully](https://github.com/rpi-ws281x/rpi-ws281x-csharp#test-status)) this works when running with Mono. is there any difference on how .NET core and Mono treat memory ?

I'll leave the links for the object I'm pining, as well as the line where the exception is thrown.
[Line where exception is thrown](https://github.com/rpi-ws281x/rpi-ws281x-powershell/blob/master/WS281x.cs#L28)
[Object that I'm trying to pin](https://github.com/rpi-ws281x/rpi-ws281x-powershell/blob/master/Native/ws2811_t.cs)

I've looked on both mono [Blittable types](http://www.mono-project.com/docs/advanced/pinvoke/#blittable-types) and [dotnet blittable Types](https://docs.microsoft.com/en-us/dotnet/framework/interop/blittable-and-non-blittable-types) but I'm not familiar with that
Is this a possible bug, or simply misunderstanding on my part?

**Comment by 0xd4d** [comment]
Similar: https://github.com/dotnet/coreclr/issues/18244

**Comment by DanielSSilva** [comment]
That is indeed similar, but in this case I'm specifying the layout, isn't it correct?

**Comment by 0xd4d** [comment]
It's the array that is an object reference. You could perhaps change it to two fields

```C#
public ws2811_channel_t channel_0;
public ws2811_channel_t channel_1;
```

**Comment by jkotas** [comment]
Mono does not enforce the restrictions on pinned GCHandle objects. It is 
 a known problem. https://github.com/mono/mono/pull/4533 and linked issues have the details. This code happens to work on Mono because of this bug.

**Comment by DanielSSilva** [comment]
@0xd4d changing that to two fields would break on the C code [here for example](https://github.com/jgarff/rpi_ws281x/blob/d50cc444fa3a12bd8e2332ac5d1dd5e61b338e68/ws2811.c#L140), wouldn't it? Since it's iterating an array

**Comment by DanielSSilva** [comment]
Nevermind, after testing I've found out that it works. Thank you very much!
