### ISSUE TITLE
Should we use TCPListener?

### ISSUE THREAD

**Issue by roterdam** [dotnet/corefx#30139]
I don't need the functionality of asp.net core kestrel. When I look at the code, it does not use TcpListener under the hood.

I'm trying to understand why. Is TcpListener significantly worse in performance than Kestrel? I don't have a Hello World application so I'm not super interested in the "throughput" of thousands of RPS. I'm merely trying to reconcile that if I go the TcpListener route I don't have a huge amount of extra code being run to service the code.

I'll ultimately be building a very simple HTTP 1.1 webserver. I'm responsible for the performance of that part, but if we subtract that cost from Kestrel should I net-net be in the ballpark of a pure Socket implementation?

**Comment by davidfowl** [comment]
Performance is hard. Start with a benchmark of what you think you want to measure and then measure comparisons based on that. Kestrel is already highly optimized so the implementation of the socket transport goes out of its way to preserve that. We didn’t even consider using layers of abstractions on top of sockets becuse there’s nothing to gain from kestrel’s point of view. Here are some of the things kestrel does with SocketAsyncEventArgs:
- Avoids per read/write allocations on the socket by using a custom awaitable.
- Uses pre/pinned buffers and pooled memory to avoid heap fragmentation

There are also more obscure thing that’s are harder to get right like threading. 

It may not matter for your use case but if you’re asking from a theoretical POV, you can do a lot better if you use the low level socket APIs than if you use TcpListener.

PS: NetworkStream was optimized in .Net Core and it’s possible to use it in a way that avoids allocations but it’s atypical.

**Comment by roterdam** [comment]
Thanks @davidfowl. I was intending to the do the latter in your two mentioned points, but I'm not sure what a custom awaitable is.

The problem with going with Kestrel is that my application is an embedded database app with a simple query fe that needs a webserver. Adding Kestrel drags in a lot of stuff is increasing my app size not to mention dll count. None of this truly matters, but if I'm 80% of within Kestrel that would be success for me.

I will benchmark. But thanks for answering that it's for performance reasons and Kestrel does more optimizations.

I'll leave this open for a few more hours and then if no one else has a comment will close it.

**Comment by davidsh** [comment]
>We didn’t even consider using layers of abstractions on top of sockets becuse there’s nothing to gain from kestrel’s point of view. 

TcpListener is meant as an "easy-to-use" / "convenience" class similar to TcpClient.  For best performance, using Sockets directly is recommended.  And for the highest performance with Sockets, using the API with SocketAsyncEventArgs is the best way to go.

**Comment by karelz** [comment]
Seems to be answered, closing.

**Comment by roterdam** [comment]
@davidsh Thanks, the api doesn't look very intimidating so I'll use that. Do I now have to worry about TCP keep alive? Like if I don't receive any data for 2 minutes I shutdown the connection or does the OS take care of it?
