### ISSUE TITLE
MSDN doc wrong about virtual CustomAttributeData.AttributeType property in .NET 4.5

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/corefx#3014]
According to MSDN, [System.Reflection.CustomAttributeData.AttributeType](https://msdn.microsoft.com/en-us/library/system.reflection.customattributedata.attributetype%28v=vs.110%29.aspx) is virtual on .NET4.5/4.6. It isn't however in reality.

I suppose it's confused because in CoreFx the property *is* indeed [virtual](https://github.com/dotnet/corefx-progress/blob/67c6fd93d8b24f5f82490e295950214a45769f4d/src-full/System.Reflection.cs#L54).

Can we get this fixed?

**Comment by joshfree** [comment]
I've pinged our msdn doc team offline.

**Comment by joshfree** [comment]
this particular doc issue has been addressed – member signatures are auto-generated by reflection, and the build system evidently reflected over the wrong set of DLLs in this case. The fix was made on 9/30.  The change appears on MSDN now – the property is no longer virtual.

**Comment by jasonwilliams200OK** [comment]
Thanks @joshfree!
Would be a good idea to have "last updated" date on MSDN pages as well.
