### ISSUE TITLE
SqlClient TestNotSupportedExceptionForTransactionScopeAsync test failing after async fix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#30144]
The TestNotSupportedExceptionForTransactionScopeAsync test is expecting a NotSupportedException to be thrown.  The test was buggy, and wasn't awaiting the Assert.ThrowsAsync.  Now that it's been fixed to await it, the test is failing because it's expecting a NotSupportedException that's not being thrown.  I'm not sure what the desired behavior is here (maybe the test should just be deleted as transaction scope is supported now?), so I've left the test disabled.

**Comment by keeratsingh** [comment]
@corivera @saurabh500 
I confirmed the test failure after enabling the test with the latest changes.
Could you kindly suggest what the desired behavior is here ?
