### ISSUE TITLE
Process.Start as a different user not working on Ubuntu machine

### ISSUE THREAD

**Issue by rajaktarun** [dotnet/corefx#30140]
I have a requirement of evaluating a user code for Human resource management. As Sandboxing and App Domain features are removed from the .net core so I thought to isolate the code by running the process under different user having least set of privileges. The code is running fine on window machine but when I am trying to run the process as a different user in a .net core 2.0 project on an Ubuntu machine. The code is throwing following exception on executing.
Exception is
```
System.PlatformNotSupportedException: Starting a process with a different identity is not supported on this platform.
   at System.Diagnostics.ProcessStartInfo.set_UserName(String value)
   at EvaluationApi.Provider.Executer.Execute(String arguments, String executionDirectoryName, String stdIn) in D:\Proform\proform-services\proform-app-services\web-layer\proform-devex-csharp-service\EvaluationApi\Provider\Executer.cs:line 30
```

The process I have defined is as follows 
```c#
Process  process = new Process
{
                    StartInfo = new ProcessStartInfo
                    {
                        WorkingDirectory = workingDirectory,
                        FileName = "dotnet",
                        Arguments = $"{workingDirectory}/{executionDirectoryName}.dll {arguments}",
                        CreateNoWindow = true,
                        RedirectStandardOutput = true,
                        RedirectStandardInput = true,
                        RedirectStandardError = true,
                        UseShellExecute = false,
                        UserName = Config.ServerGuestAccountUserName,
                        Password = GetSecureString(Config.ServerGuestAccountPassword),
                        Domain = Config.ServerGuestAccountDomain,
                    },                   
}; 
```

Coding is working fine on ubuntu machine if I ran the process without username and password.
Is the features "Run process as different user" not supported in .net core for Ubuntu? 
Is there any mistake in my code?
Do you have any better solutions?

**Comment by danmosemsft** [comment]
@eerhardt

**Comment by eerhardt** [comment]
@rajaktarun - Starting a new process as a different user on Unix was enabled in .NET Core v2.1.  It appears you are using 2.0 or below, is that correct?  Can you try using `2.1.0` and see if it meets your needs?  See #26268 and #26431.

Also, on Unix `Domain` is not supported, and will throw an exception if you set it.  The same goes for `Password`, as there isn't a clean way on Unix to start a new process using a password.  See the discussion in #26268.  So you'll have to change your code to support Unix:

```C#
                    var startInfo = new ProcessStartInfo
                    {
                        WorkingDirectory = workingDirectory,
                        FileName = "dotnet",
                        Arguments = $"{workingDirectory}/{executionDirectoryName}.dll {arguments}",
                        CreateNoWindow = true,
                        RedirectStandardOutput = true,
                        RedirectStandardInput = true,
                        RedirectStandardError = true,
                        UseShellExecute = false,
                        UserName = Config.ServerGuestAccountUserName,
                    };
                    if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                    {
                        startInfo.Password = GetSecureString(Config.ServerGuestAccountPassword);
                        startInfo.Domain = Config.ServerGuestAccountDomain;
                     }
```

**Comment by eerhardt** [comment]
Closing as "answered".  If this didn't help, feel free to re-open.

**Comment by sirkadirov** [comment]
Hmmm... .NET Core SDK version `2.1.302`: same error, but I don't use this execution path in my program... And, as I see in @eerhardt post, RunAs functionality is available at this .NET Core version.

    .NET Core SDK version `2.1.302`
    Microsoft.NETCore.App version 2.1.2
    Linux Mint 19 "Tara"

**Comment by sirkadirov** [comment]
Oops, I used `LoadUserProfile` in all execution paths, but this option not supported on Linux... Maybe we need to change exception message for it? Because `Starting a process with a different identity is not supported on this platform.` is really bad. Created issue for this idea. Maybe I create PR soon.
