### ISSUE TITLE
Where is System.SpanExtensions?

### ISSUE THREAD

**Issue by wjdavis5** [dotnet/corefx#30156]
The docs show it exists here:
https://docs.microsoft.com/en-us/dotnet/api/system.spanextensions?view=netcore-2.0

But I'm not seeing it in System.Memory.dll

![image](https://user-images.githubusercontent.com/2580575/40997439-b284c3ee-68d2-11e8-93d5-4870e3eb03e0.png)

**Comment by stephentoub** [comment]
cc: @mairaw

**Comment by mairaw** [comment]
@weshaggard this issue keeps coming up with different APIs. I think when you grabbed the assemblies for me for .NET Core + extensions, they included things from the master branch that weren't part of 2.0. Can you confirm?

**Comment by weshaggard** [comment]
Yes in .NET Core 2.0 we gave you guys all APIs that were produced by corefx, I fixed that with the .NET Core 2.1 doc hand of to only give you APIs that are part of Microsoft.NETCore.App. I could give you the same set for .NET Core 2.0 if there is any easy way to clean-up the docs based on that.

**Comment by mairaw** [comment]
Yes, I can run CI with a new set of assemblies for 2.0 @weshaggard and everything should magically be fixed. ✨

**Comment by weshaggard** [comment]
@mairaw I will send it to you offline.

**Comment by ahsonkhan** [comment]
Do we have any updates on this issue?

**Comment by joshfree** [comment]
assigning to @mairaw to verify and close

**Comment by danmosemsft** [comment]
@mairaw 	?

(Just going through our 2.1.x issues)

**Comment by khellang** [comment]
I think you're looking for `MemoryExtensions`.

**Comment by michalmalecki** [comment]
No, im talking about https://docs.microsoft.com/en-us/dotnet/api/system.spanextensions?view=netcore-2.0 and specifically NonPortableCast mentioned on https://bytelanguage.net/2018/04/21/type-casting-using-spant/ and https://blog.marcgravell.com/2017/04/spans-and-ref-part-2-spans.html?m=1

**Comment by ahsonkhan** [comment]
> Any chance to remove it from docs or put above info there?

For .NET Core 2.1, the docs are correct.
https://docs.microsoft.com/en-us/dotnet/api/system.memoryextensions?view=netcore-2.1

For .NET Core 2.0, @mairaw, did you have any luck in updating the docs?

**Comment by mairaw** [comment]
@ahsonkhan I ran into issues with some type forwards. Let me add this back on the priority list and see if I can get past the issues that I was having when I removed the extension DLLs.

**Comment by danmosemsft** [comment]
@mairaw just making a pass through the remaining issues in 2.1.x milestone. Is this one still live?

**Comment by ahsonkhan** [comment]
As expected, I don't see `SpanExtensions` in the docs anywhere anymore (all the relevant pages show 404) and we only have `MemoryExtensions`, which shipped in 2.1. The same holds regarding the `NonPortableCast` API which moved to `MemoryMarshal.Cast` before shipping.

We may want to do the same with aspnetcore2.0, but I am not sure about that:
https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-2.0&term=nonportablecast
https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-2.0&term=spanextensions

cc @davidfowl 

Therefore, closing the issue as fixed.

**Comment by mairaw** [comment]
Thanks for closing it @ahsonkhan. Yes, this had been taken care of a while back.

**Comment by ahsonkhan** [comment]
> We may want to do the same with aspnetcore2.0, but I am not sure about that

cc @justinvp, @natemcmaster - in case you have more context on this.
