### ISSUE TITLE
dotnet-runtime-2.0.0 installation fails in centos 7.3

### ISSUE THREAD

**Issue by ramnov** [dotnet/corefx#30158]
In centos 7.3 repo :  https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod

dotnet-runtime-deps-2.1.0-rc1-rhel.7-x64.rpm and dotnet-host-2.1.0-rc1-x64.rpm are missing from yesterday. This is breaking our code to install dotnet-runtime-2.0.0 

```
rpm --import https://packages.microsoft.com/keys/microsoft.asc
sh -c 'echo -e "[packages-microsoft-com-prod]\nname=packages-microsoft-com-prod \nbaseurl=https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/dotnetdev.repo'
yum -y install dotnet-runtime-2.0.0
```

Loaded plugins: fastestmirror, langpacks
Repository packages-microsoft-com-prod is listed more than once in the configuration
packages-microsoft-com-prod                                                                                                                                                | 2.9 kB  00:00:00     
Loading mirror speeds from cached hostfile
 * epel: mirror.pnl.gov
Resolving Dependencies
--> Running transaction check
---> Package dotnet-runtime-2.0.0.x86_64 0:2.0.0-1 will be installed
--> Processing Dependency: dotnet-hostfxr-2.0.0 for package: dotnet-runtime-2.0.0-2.0.0-1.x86_64
--> Running transaction check
---> Package dotnet-hostfxr-2.0.0.x86_64 0:2.0.0-1 will be installed
--> Processing Dependency: dotnet-host >= 2.0.0 for package: dotnet-hostfxr-2.0.0-2.0.0-1.x86_64
--> Running transaction check
---> Package dotnet-host.x86_64 0:2.1.0_rc1-1 will be installed
--> Processing Dependency: dotnet-runtime-deps-2.1.0-rc1 >= 2.1.0-rc1 for package: dotnet-host-2.1.0_rc1-1.x86_64
--> Running transaction check
---> Package dotnet-runtime-deps-2.1.0-rc1.x86_64 0:2.1.0_rc1-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==================================================================================================================================================================================================
 Package                                                  Arch                              Version                                  Repository                                              Size
==================================================================================================================================================================================================
Installing:
 dotnet-runtime-2.0.0                                     x86_64                            2.0.0-1                                  packages-microsoft-com-prod                             24 M
Installing for dependencies:
 dotnet-host                                              x86_64                            2.1.0_rc1-1                              packages-microsoft-com-prod                             43 k
 dotnet-hostfxr-2.0.0                                     x86_64                            2.0.0-1                                  packages-microsoft-com-prod                            181 k
 dotnet-runtime-deps-2.1.0-rc1                            x86_64                            2.1.0_rc1-1                              packages-microsoft-com-prod                            2.8 k

Transaction Summary
==================================================================================================================================================================================================
Install  1 Package (+3 Dependent packages)

Total download size: 25 M
Installed size: 25 M
Is this ok [y/d/N]: y
Downloading packages:
dotnet-host-2.1.0-rc1-x64.rpm  FAILED                                          
https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod/dotnet-host-2.1.0-rc1-x64.rpm: [Errno 14] HTTPS Error 404 - Not Found                            ]  0.0 B/s |    0 B  --:--:-- ETA 
Trying other mirror.
To address this issue please refer to the below knowledge base article 

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please create a bug on https://bugs.centos.org/

(1/4): dotnet-hostfxr-2.0.0-rhel.7-x64.rpm                                                                                                                                 | 181 kB  00:00:00     
(2/4): dotnet-runtime-2.0.0-rhel.7-x64.rpm                                                                                                                                 |  24 MB  00:00:00     
dotnet-runtime-deps-2.1.0-rc1- FAILED                                          
https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod/dotnet-runtime-deps-2.1.0-rc1-rhel.7-x64.rpm: [Errno 14] HTTPS Error 404 - Not Found             ]  0.0 B/s |  19 MB  --:--:-- ETA 
Trying other mirror.

Error downloading packages:
  dotnet-host-2.1.0_rc1-1.x86_64: [Errno 256] No more mirrors to try.
  dotnet-runtime-deps-2.1.0-rc1-2.1.0_rc1-1.x86_64: [Errno 256] No more mirrors to try.

**Comment by karelz** [comment]
I believe something like this was fixed in RTM. Why are you installing RC1 and not RTM?

**Comment by karelz** [comment]
This issue was moved to dotnet/core-setup#4197
