### ISSUE TITLE
HttpClientHandler on unix (CurlHandler) hangs forever in case of negative scenarios

### ISSUE THREAD

**Issue by kapilash** [dotnet/corefx#3015]
When curl handler encounters exception in its execution, it hangs forever.

            using (var handler = new HttpClientHandler())
            {
                handler.MaxAutomaticRedirections = 5;
                var client = new HttpClient(handler);
                await  client.GetAsync("http://httpbin.org/redirect/6");
            }

**Comment by stephentoub** [comment]
I'm working on some changes to how threading is managed in CurlHandler. It should address this as well.

**Comment by kapilash** [comment]
Great. But my description of the problem may not be accurate. I ran tests thrice consecutively with the negative tests commented out and it went through.  

Nevertheless, I trust your threading overhaul will fix the problem.
