### ISSUE TITLE
Unable to bind guid to parameters when using ApiController Attribute

### ISSUE THREAD

**Issue by seroche** [dotnet/corefx#30165]
After adding the `[ApiController]` attribute to my controller, query string parameters cannot get be bound to GUIDs.

`public async Task<IActionResult> Get(Guid id, CancellationToken token)` always returns: 
```
{
    "": [
        "The input was not valid."
    ]
}
```

After removing `ApiController` attribute, I get the correct result.

I'm using asp.net core 2.1.

**Comment by lousaibiao** [comment]
I new an webapi project with asp.net core 2.1, and use link below to test this guid, it works. `https://localhost:5001/api/values?id=c82a4188-0a0f-4143-8cf9-b0a523d4864a`

**Comment by gfoidl** [comment]
For the protocol: https://github.com/aspnet/Home/issues/3202
