### ISSUE TITLE
System.Security.Cryptography.X509Certificates.Tests.X509StoreTests failed with "System.Diagnostics.RemoteExecutorTestBase+RemoteInvokeHandle+RemoteExecutionException" in CI.

### ISSUE THREAD

**Issue by Sunny-pu** [dotnet/corefx#30162]
Failed test: System.Security.Cryptography.X509Certificates.Tests.X509StoreTests.X509Store_MachineStoreLoadSkipsInvalidFiles (from (empty)) 

Message: System.Diagnostics.RemoteExecutorTestBase+RemoteInvokeHandle+RemoteExecutionException : Remote process failed with an unhandled exception.

~~~
STACK TRACE:
Child exception: Xunit.Sdk.EqualException: Assert.Equal() Failure Expected: 2 Actual: 3 at System.Security.Cryptography.X509Certificates.Tests.X509StoreTests.<>c.<X509Store_MachineStoreLoadSkipsInvalidFiles>b__30_0() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_centos7.1_debug/src/System.Security.Cryptography.X509Certificates/tests/X509StoreTests.cs:line 537 Child process: System.Security.Cryptography.X509Certificates.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb System.Security.Cryptography.X509Certificates.Tests.X509StoreTests+<>c Int32 <X509Store_MachineStoreLoadSkipsInvalidFiles>b__30_0()
~~~
Details: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_centos7.1_debug/423/testReport/System.Security.Cryptography.X509Certificates.Tests/X509StoreTests/X509Store_MachineStoreLoadSkipsInvalidFiles/

**Comment by danmosemsft** [comment]
@tmds this is your new test.

**Comment by tmds** [comment]
Not sure if it is the root cause, but that is how the test would fail if the machine store did manage to read the cert that was chmod-ed to zero. This read is done by the underlying library (openssl), so it may be a platform difference.

If we see this happen some more, maybe we see this is on a specific machine/OS.
This failure is on a daily outerloop on centos 7.1? So far it hasn't failed for PRs?

When we think that is the cause, we can make the chmod-ed cert empty. It's more important we verify that the store loading doesn't throw, than that we deal with the platform difference.

CC @stephentoub

**Comment by tmds** [comment]
@assyadh I can't reproduce this on my system.

Can you patch the test:
```diff
--- a/src/System.Security.Cryptography.X509Certificates/tests/X509StoreTests.cs
+++ b/src/System.Security.Cryptography.X509Certificates/tests/X509StoreTests.cs
@@ -535,6 +535,8 @@ namespace System.Security.Cryptography.X509Certificates.Tests
             // Valid file.
             File.WriteAllBytes(Path.Combine(sslCertDir, "3.pem"), TestData.SelfSigned3PemBytes);
 
+            Process.Start("ls", $"-lah {sslCertDir}").WaitForExit();
+
             var psi = new ProcessStartInfo();
             psi.Environment.Add("SSL_CERT_DIR", sslCertDir);
             psi.Environment.Add("SSL_CERT_FILE", "/nonexisting");
@@ -544,6 +546,11 @@ namespace System.Security.Cryptography.X509Certificates.Tests
                 {
                     store.Open(OpenFlags.OpenExistingOnly);
 
+                    foreach (var cert in store.Certificates)
+                    {
+                        System.Console.WriteLine(cert.NotBefore.ToUniversalTime());
+                    }
+
                     // Check nr of certificates in store.
                     Assert.Equal(2, store.Certificates.Count);
                 }
```
And then run it (replace `/home/tmds/repos/corefx` with your corefx location):
```
corefx/bin/tests/System.Security.Cryptography.X509Certificates.Tests/netcoreapp-Linux-Debug-x64$ /home/tmds/repos/corefx/bin/testhost/netcoreapp-Linux-Debug-x64//dotnet xunit.console.netcore.exe System.Security.Cryptography.X509Certificates.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests  -notrait category=OuterLoop -notrait category=failing
```
And share what is printed out?

**Comment by assyadh** [comment]
Hi @tmds 

Here is the output of `System.Console.WriteLine(cert.NotBefore.ToUniversalTime());`


```
5/30/18 6:26:48 PM
5/30/18 6:26:35 PM
6/4/18 1:32:21 PM
```

Hamza

**Comment by ILMTitan** [comment]
I am having the same issue.
I am running in Ubuntu 18.04.1 in a docker container.

I applied the above patch.

Full log available at https://pastebin.com/TZ87aU5W

The relevant debugging data is as follows:

```
  drwxr-xr-x 2 root root 4.0K Nov 15 22:45 .
  drwxr-xr-x 3 root root 4.0K Nov 15 22:45 ..
  -rw-r--r-- 1 root root 1.2K Nov 15 22:45 0.pem
  -rw-r--r-- 1 root root   24 Nov 15 22:45 1.pem
  ---------- 1 root root 1.2K Nov 15 22:45 2.pem
  -rw-r--r-- 1 root root 1.2K Nov 15 22:45 3.pem
  5/30/18 6:26:48 PM
  5/30/18 6:26:35 PM
  6/4/18 1:32:21 PM
```

**Comment by tmds** [comment]
> root root

This test fails because you run it is as root. root can read the unreadable.

**Comment by ILMTitan** [comment]
Is it documented somewhere that tests may not be run as root?

**Comment by tmds** [comment]
I don't know. Now that we know the root cause, we can also update the test.

**Comment by tarekgh** [comment]
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F35944~2Fmerge/test~2Ffunctional~2Fcli~2F/20190318.12/workItem/System.Security.Cryptography.X509Certificates.Tests/analysis/xunit/System.Security.Cryptography.X509Certificates.Tests.ChainTests~2FBuildInvalidSignatureTwice

**Comment by ViktorHofer** [comment]
Happened again: https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190529.66/workItem/System.Security.Cryptography.X509Certificates.Tests/wilogs

@tmds can you please try to fix the test or disable it? Thanks.
