### ISSUE TITLE
Turn on xml documentation validation globally

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#30177]
Done for several assemblies, e.g. https://github.com/dotnet/corefx/blob/ba496ae6a9ae055708b630b3f73395a76c2ce6ce/src/System.Threading.Tasks.Extensions/src/System.Threading.Tasks.Extensions.csproj#L6

Could be done for all

See https://github.com/dotnet/corefx/pull/30159#discussion_r193549684

**Comment by satano** [comment]
Hello.

I can take this one. Do I understand it right that is is just about adding that `<DocumentationFile>` element to the project files?

**Comment by ViktorHofer** [comment]
If we want to do this globally then it makes sense to put this into the Directory.Build.props in src and condition it correctly.

**Comment by sharwell** [comment]
💡 If you put it in Directory.Build.props, some of the properties required to calculate `<DocumentationFile>` might not be available. The `<GenerateDocumentationFile>` property is a Boolean-valued property intended for use in this manner. Here is my recommended approach for projects turning this on for the first time:

⚠️ Build customizations in this project might make one or more of the suggestions impossible/impractical/inconsistent with other code. I have not verified the behavior *in the context of dotnet/corefx*.

https://github.com/DotNetAnalyzers/DocumentationAnalyzers/blob/cf433d105027cb0ca3f9a258b30116feee8acc73/DocumentationAnalyzers/Directory.Build.props#L27-L38

**Comment by satano** [comment]
@danmosemsft Hm. A have completely forgot this issue. At this time, I do not have time for this (apart of that I did not quite understand @sharwell's post).

I am sorry for it, but please unassign me.

**Comment by AraHaan** [comment]
https://github.com/dotnet/corefx/blob/ba496ae6a9ae055708b630b3f73395a76c2ce6ce/src/System.Threading.Tasks.Extensions/src/System.Threading.Tasks.Extensions.csproj#L6

I think the ``<GenerateDocumentationFile>`` in the props file would replace this line entirely both in Command line, and the Visual Studio IDE. At least that is what it does with my XmlAbstraction repository locally. So removing the ``<DocumentationFile>`` should result in the same behavior as currently but ye turns it on globally. I will try to tackle this for hacktoberfest (I would really like a free shirt :wink:).

**Comment by danmosemsft** [comment]
@satano no problem!

@AraHaan I have sent you a collaborator invite. If you accept, I can assign you the issue. (You can work on it either way though). Note it auto subscribes to all repo activity, you'll very likely want to go switch that off again.

**Comment by AraHaan** [comment]
@danmosemsft I do not mind subscribing to all repo activities to know if I need to rebase my changes on top of upstream changes (replaying).

**Comment by danmosemsft** [comment]
@AraHaan 	I believe you can unsubscribe from "all" repo activity yet still receive notification when there are updates to an issue or PR which you own or were mentioned in.

**Comment by AraHaan** [comment]
Alright so, to clear things up you want all of the ``Directory.Build.props`` or only ones under the project root, ``/src/``, and some other directories?

**Comment by danmosemsft** [comment]
Either the one at the root or the one in src - I am not sure how to choose. @safern 	?

**Comment by safern** [comment]
I guess this should go into the one in the root, that is consumed by all the projects in corefx, so that would be the minimal change. 

I don't think we want to use GenerateDocumentationFile instead as that will get turned on automatically if `DocumentationFile` is set. If we switch to set `GenerateDocumentationFile` instead and don't set `DocumentationFile` it would be set to a default by the compiler targets which points to the `IntermediateOutput` which it seems we don't want since we directly use the doc files from the output folder defined in `OutputPath`.

This is what the compiler common targets do:
```xml
<GenerateDocumentationFile Condition="'$(DocumentationFile)' != ''">true</GenerateDocumentationFile>
<DocumentationFile Condition="'$(MSBuildProjectExtension)' != '.vbproj'">$(IntermediateOutputPath)$(AssemblyName).xml</DocumentationFile>
```

So I guess just setting `DocumentationFile` in the root props file should be enough. I think we just need to set it for src projects, not test, nor reference assembly projects. So it needs to have the right conditions:

```xml
<DocumentationFile Condition="'$(IsTestProject)' != 'true' AND '$(IsReferenceAssembly)' !='true'">
```

It would have to go after we import the ReferenceAssemblies.props file so that `IsReferenceAssembly` property is defined.

**Comment by safern** [comment]
I think also we should set the NoWarn 1591 as we do set it in some projects, just as @sharwell pointed out.

**Comment by AraHaan** [comment]
https://github.com/dotnet/corefx/blob/ba496ae6a9ae055708b630b3f73395a76c2ce6ce/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.csproj#L3

Should I remove this line too for the common one on the root ``Directory.Build.props``?

**Comment by safern** [comment]
> Should I move all of the <NoWarn>'s to the root Directory.Build.props as well?
(used WSL for grep on this)

No I just think you should move the 1573 and just in the case when we are enabling document file. 

>https://github.com/dotnet/corefx/blob/master/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.ilproj#L3
Should I remove this line too for the common one on the root Directory.Build.props?

Yes there should only be one declaration of DocumentationFile in the repo after your change.

**Comment by AraHaan** [comment]
Ok, will do.

**Comment by danmosemsft** [comment]
@AraHaan could you remind me what is left here now? Perhaps at this point, it would be clearer to create a new issue to cover anything left, and close this one as complete.
