### ISSUE TITLE
Utf8Parser could not parse DateTime strinng in G format

### ISSUE THREAD

**Issue by fisenkodv** [dotnet/corefx#30171]
`Utf8Parser`  is unable to parse `DateTime` string in '_G_' format when the month/day part has only one digit because parser assumes that two digits will be provided:

**month**:
https://github.com/dotnet/corefx/blob/f9ab6c8971c93463aa094f8b1b2e41c522042fa7/src/System.Memory/src/System/Buffers/Text/Utf8Parser/Utf8Parser.Date.G.cs#L28-L29

**day**:
https://github.com/dotnet/corefx/blob/f9ab6c8971c93463aa094f8b1b2e41c522042fa7/src/System.Memory/src/System/Buffers/Text/Utf8Parser/Utf8Parser.Date.G.cs#L52-L53

**example**:
```csharp
var dateTime1 = "10/26/2015 12:00:00";
var dateTime2 = "7/4/1776 12:00:00";
  
DateTime.TryParse(dateTime1, out var dateTimeParseValue1);// OK, 10/26/2015 12:00:00 PM  
Utf8Parser.TryParse(Encoding.UTF8.GetBytes(dateTime1), out DateTime utf8ParserParseValue1, out _, 'G');// OK, 10/26/2015 12:00:00 PM

DateTime.TryParse(dateTime2, out var dateTimeParseValue2); // OK, 7/4/1776 12:00:00 PM
Utf8Parser.TryParse(Encoding.UTF8.GetBytes(dateTime2), out DateTime utf8ParserParseValue2, out _, 'G');// Error, 1/1/0001 12:00:00 AM
```
**Expected behavior**:
`Utf8Parser` should be able to parse string as `DateTime`.

**.NET Framework**: 4.7.2
**System.Memory**: 4.5

**Comment by stephentoub** [comment]
cc: @ahsonkhan, @AtsushiKan

**Comment by AtsushiKan** [comment]
Utf8Parser uses the InvariantCulture rules. ToString() using InvariantCulture always emits two digits so the parser was written to roundtrip whatever ToString() would emit.

However, it's true that `DateTime.TryParse()` accepts the 1-digit form even when using the InvariantCulture so this could be seen as an api gotcha. Making it accept the 1-digit form will slow down the parser, though.

Thoughts on how to decide this tradeoff?

**Comment by AtsushiKan** [comment]
>Making it accept the 1-digit form will slow down the parser, though.

Though we could leave the main path as it is and jump to the more "flexible" version if the first length check for 19 fails.

**Comment by fisenkodv** [comment]
@AtsushiKan, I believe format should support _AM|PM_ at the end, e.g.  _6/6/2018 5:36:01 PM_. What do you think?

**Comment by AtsushiKan** [comment]
Keep in mind that `DateTime.TryParse` does not take a format string, it takes a `DateTimeStyles` enumeration so there's no implied correlation between `Utf8Parser.Parse('G')` and `DateTime.TryParse`. We aren't using the behavior of that api as a "contract" for how `Utf8Parser` works.

These are intended to be high-performance api where as the older apis were designed for convenience. 
`DateTime.TryParse` actually contains a lot of policy, for example like this:

> This method tries to ignore unrecognized data, if possible, and fills in missing month, day, and year information with the current date. If s contains only a date and no time, this method assumes the time is 12:00 midnight.

https://msdn.microsoft.com/en-us/library/ch92fbc1(v=vs.110).aspx

So we should only change the behavior of `Utf8Parser` if it makes sense for that api. Right now, it roundtrips everything that `Utf8Formatter.TryFormat` would emit so it does satisfy our minbar requirements.

**Comment by stephentoub** [comment]
> Keep in mind that DateTime.TryParse does not take a format string

DateTime.TryParseExact does, though.

**Comment by AtsushiKan** [comment]
Double-checked `TryParseExact("G", InvariantCulture)`.

It throws a FormatException if you give it a 1-digit component or a "AM/PM" suffix.

**Comment by AtsushiKan** [comment]
Closing as the current behavior is consistent with round-tripping and `TryParseExact("G")`.
