### ISSUE TITLE
Recommendations for solving "Could not load file or assembly" error

### ISSUE THREAD

**Issue by FenrisWolfAtMiddleEarth** [dotnet/corefx#30175]
I have for some days been struggling an assembly binding error. Assembly binding is something of a black-box, where so many things can go wrong. And the error message in the exception does not give details. (at least to my understanding). So what is the recommended way to open the box of assembly binding to get details on the problem?
Specifically I am struggling with the following:
1) I have wrapped IBM.Data.Db2.Core in a .net standard 2.0 library.
2) I can nicely use that library when my application is a netcoreapp2.0
3) However when I use the library from a net461 application it fails with assembly binding

The error message is:
{"Could not load file or assembly 'System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"}

I don't expect you to put your finger on the problem for me, but recommendations for opening the black box of assembly binding would be nice.

**Comment by FenrisWolfAtMiddleEarth** [comment]
I found FusLogVw. Is that best way to get details on binding errors ?
It does not help me much though. It says assembly names are different. Looks similar to me :-(

```
=== Pre-bind state information ===
LOG: DisplayName = System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\n (Fully-specified)
LOG: Appbase = file:///C:/Users/E35336/Source/Repos/Library - Db2Connectivity/Db2ConnectivityStarter/bin/Debug/net461/
LOG: Initial PrivatePath = NULL
Calling assembly : IBM.Data.DB2.Core, Version=1.2.2.100, Culture=neutral, PublicKeyToken=7c307b91aa13d208.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\\Users\\E35336\\Source\\Repos\\Library - Db2Connectivity\\Db2ConnectivityStarter\\bin\\Debug\\net461\\Db2ConnectivityStarter.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\config\\machine.config.
LOG: Post-policy reference: System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Attempting download of new URL file:///C:/Users/E35336/Source/Repos/Library - Db2Connectivity/Db2ConnectivityStarter/bin/Debug/net461/System.Runtime.Loader.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Build Number
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.
```

**Comment by danmosemsft** [comment]
fuslogvw is indeed a great place to start diagnosing assembly loads into  .NET Framework apps.

System.Runtime.Loader.dll is a .NET Core assembly identity. Normally to make this work, there would be a stub version of this file that forwards to whatever assemblies contain the implementations on .NET Framework. However in this case I don't believe there is such a matching type (presumably AssemblyLoadContext) so I'm not sure how you've successfully built a .NET Standard library that uses it.

@weshaggard maybe can help. Wes I do see in http://apisof.net that it shows it in the row `.NET Standard + Platform Extensions | 1.6 | System.Runtime.Loader, Version=4.0.0.0, PublicKeyToken=b03f5f7f11d50a3a`
I'm not sure what this means as I don't see a netstandard configuration for System.RuntimeLoader.

**Comment by FenrisWolfAtMiddleEarth** [comment]
> I'm not sure how you've successfully built a .NET Standard library that uses it.

I did not. IBM did.
IBM.Data.DB2.Core is a netstandard2.0 library which references System.Runtime.Loader
https://www.nuget.org/packages/IBM.Data.DB2.Core/

**Comment by FenrisWolfAtMiddleEarth** [comment]
> What are you using that library for?

I am not using System.Runtime.Loader. I am using IBM.Data.DB2.Core, and I am using it for accessing DB2 database on our IBM mainframe.

But I think I can guess what IBM is using it for. Their library is not a true .net core library. It is just a thin .net Wrapper which uses native libraries. These native libraries comes in three flavours: Windows, Linux and Mac, which is why IBM has three nuget packages (the native libraries are part of the nuget-package):
https://www.nuget.org/packages/IBM.Data.DB2.Core/
https://www.nuget.org/packages/IBM.Data.DB2.Core-lnx/
https://www.nuget.org/packages/IBM.Data.DB2.Core-osx/

A good guess is that they are using System.Runtine.Loader to load the native libraries

I can understand from both your comments that System.Runtime.Loader is a Core library, which nicely explains why it fails when I try to load it in a framework application.

@danmosemsft  I think maybe I can answer your question
` I'm not sure how you've successfully built a .NET Standard library that uses it.`
Again I did not do that. IBM did. But they were propably able to do that because the nuget package has metadata for netstandard1.5. It also has metadata for net462. (When you expand Dependencies)
https://www.nuget.org/packages/System.Runtime.Loader/

Is that an error, or am I misinterpreting the metadata in Nuget?

**Comment by karelz** [comment]
Closed - seems to be answered. Shout out if I missed some angle.

**Comment by MarcToth** [comment]
I have the same problem, but no solution. Is there any?

**Comment by karelz** [comment]
@MarcToth what about the suggestions above? Did you try them?

**Comment by FenrisWolfAtMiddleEarth** [comment]
I think the conclusion is that IBM wrote a crappy library.
They somehow managed to build it as .net standard, even though it is dependent on .net core libraries

**Comment by MarcToth** [comment]
FYI: That's what I found on the IBM web [page](https://www.ibm.com/developerworks/community/blogs/96960515-2ea1-4391-8170-b0515d08e4da/entry/Instructions_for_downloading_and_using_DB2_NET_Core_provider_package?lang=en):

> **Q: Can I use this package with full.NET framework applications?**
    It is not available in this release.

So we have to wait (again) for IBM to fix this...maybe...

**Comment by danmosemsft** [comment]
@MarcToth, we are talking to the package owners at the moment.

**Comment by MarcToth** [comment]
I just tested it with .NET 4.7.2, but it's not working either

**Comment by arturbianchi** [comment]
Same problem here. Any suggestion?
