### ISSUE TITLE
Consider adding back AppDomainSetup

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#30184]
I've found many desktop applications that access AppDomain.CurrentDomain.SetupInformation.ApplicationBase & TargetFrameworkName.  We should consider adding these back in System.Runtime.Extensions and redirect them to AppContext, at least so long as we don't have actual AppDomain creation support.

**Comment by danmosemsft** [comment]
@jeffschwMSFT any objection? Does this require any work on the runtime side?

**Comment by jeffschwMSFT** [comment]
I agree this makes sense.  This is also on my radar from an appmodel pov.

**Comment by danmosemsft** [comment]
@Anipik looks easy: add AppDomainSetup to the ref so it's exposed, initially just exposing ApplicationBase, TargetFrameworkName, and ApplicationName and write basic tests, merge.

**Comment by danmosemsft** [comment]
Also update https://github.com/dotnet/corefx/blob/master/src/shims/ApiCompatBaseline.netcoreapp.netfx461.txt to remove this, as with all .NET Framework ports.

**Comment by Anipik** [comment]
@danmosemsft 
1. is there any constructor that we should also expose  other than the empty one ? 

2. Do we need to expose and implement AppDomain.SetupInformation ?

3. How to can i redirect them to AppDomain.SetupInformation as mentioned in the issue description ?


Currently when we create a new appDomain object in a test, all these properties are set to null.

**Comment by danmosemsft** [comment]
1. Just the empty one for now -- ActivationContext and ActivationArguments don't exist in .NET Core.
2. Hmm, it seems that we have the pieces. For some reason in the compat lab data its [usage is high](https://apisof.net/catalog/System.AppDomain.SetupInformation). @jkotas?
3. I don't know. @jeffschwMSFT who on your team can guide @Anipik ? Or maybe this is work that they would best handle?

**Comment by jkotas** [comment]
> Hmm, it seems that we have the pieces. For some reason in the compat lab data

This issue specially about making `AppDomain.CurrentDomain.SetupInformation.ApplicationBase` work. Exposing `AppDomain.SetupInformation` is part of it.

> How to can i redirect AppDomain.SetupInformation to appContext

Create internal/private constructor that initializes the values from `AppContext.BaseDirectory` and `AppContext.TargetFrameworkName`.
