### ISSUE TITLE
System.Runtime.ProfileOptimization is missing from .NETCore

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#30185]
I came across some desktop apps that use ProfileOptimization to tune the JIT.  Per https://github.com/dotnet/coreclr/issues/18202 we have similar APIs on AssemblyLoadContext.  We should redirect ProfileOptimization to those and avoid an unnecessary break unless we have a good reason for not providing Static access to such APIs.  /cc @brianrob @jkotas

**Comment by brianrob** [comment]
The main reason for this is that on .NET Core, you have to know the AssemblyLoadContext as using Multi-Core JIT can trigger assembly loads.  This is the reason that the APIs were moved when enabling Multi-Core JIT on .NET Core.  It's possible to have an implementation of these static methods that uses the default AssemblyLoadContext if we feel this is improtant enough.  I'm open to this - though I would like to understand how we've handled similar situations with differences between .NET Core and .NET Framework so that we can try to be reasonably consistent.

**Comment by brianrob** [comment]
@noahfalk

**Comment by noahfalk** [comment]
> though I would like to understand how we've handled similar situations with differences between .NET Core and .NET Framework so that we can try to be reasonably consistent.

Unless there is evidence to the contrary I'm happy to assume Eric made the suggestion to be consistent with similar situations already. It seems pretty reasonable to me. Did you have any specific concerns or alternatives in mind? I think the unlikely worst case is the API review comes back saying the PR is no good, and then we pivot to a better approach.

**Comment by brianrob** [comment]
Nope, no specific concerns.

**Comment by MarcoRossignoli** [comment]
Is this simply to wrap AssemblyLoadContext.Default.XProfileX in a [ProfileOptimization](https://referencesource.microsoft.com/#mscorlib/system/runtime/ProfileOptimization.cs,30) class on System.Runtime namespace(maybe testable with [RemoteExecutor](https://github.com/dotnet/corefx/blob/9ca2480b79d041b5121d3d5025a588257d4f978c/Documentation/project-docs/writing-tests.md#remoteexecutor))?

**Comment by brianrob** [comment]
Yes, that's right @MarcoRossignoli.

**Comment by MarcoRossignoli** [comment]
I could work on it if you want!

**Comment by brianrob** [comment]
Sounds great!

**Comment by MarcoRossignoli** [comment]
@danmosemsft @brianrob ProfileOptimization.cs goes to shared folder(corefx mirror) on coreclr?Can you explain to me when put files on shared?

**Comment by jkotas** [comment]
This is applicable to CoreRT as well. We maintain same public surface across between different .NET Core runtimes.

Since this is just a trivial forwarder to another API, I think it can go to https://github.com/dotnet/corefx/tree/master/src/System.Runtime.Extensions/src/System/Runtime .

**Comment by MarcoRossignoli** [comment]
> Since this is just a trivial forwarder to another API, I think it can go to https://github.com/dotnet/corefx/tree/master/src/System.Runtime.Extensions/src/System/Runtime .

no coreclr, right?

**Comment by jkotas** [comment]
Right
