### ISSUE TITLE
PerformanceData types are missing from System.Diagnostics.PerformanceCounters

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#30188]
I came across some desktop code that was using these old perf counter APIs.  I was able to add it back rather simply.  Any reason why we wouldn't want to do this?
https://devdiv.visualstudio.com/DevDiv/Default/_git/DotNet-CoreFX-Trusted/commit/58ff87066374ab65e556afa6194564722a69413e?refName=refs%2Fheads%2Fericstj%2Fadd.back.types.experiment

**Comment by brianrob** [comment]
@adiaaida

**Comment by adiaaida** [comment]
I can't think of a reason not to. @danmosemsft?

**Comment by danmosemsft** [comment]
Fine by me, I don't recall any conscious decision in the past to not do this for some reason (unless it was because: we should not port obsolete technology, which is something we are much less concerned about now)
BTW your PR link is internal of course.

**Comment by MarcoRossignoli** [comment]
@ericstj could you replace link with https://referencesource.microsoft.com/ reference if is possible?

**Comment by MarcoRossignoli** [comment]
Plan:
Move [ SafePerfProviderHandle](https://referencesource.microsoft.com/#System.Core/Microsoft/Win32/SafeHandles/SafePerfProviderHandle.cs,836ab7386fbc0c99) under coreclr [SafeHandles](https://github.com/dotnet/coreclr/tree/85374ceaed177f71472cc4c23c69daf7402e5048/src/System.Private.CoreLib/shared/Microsoft/Win32/SafeHandles)
Move all files under [System.Diagnostic.PerformanceData](https://referencesource.microsoft.com/#System.Core/System/Diagnostics/PerformanceData/CounterSet.cs) to new [PerformanceData folder](https://github.com/dotnet/corefx/tree/master/src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics)
Move [used pinvokes](https://gist.github.com/ericstj/f5c577651e5a5efd248bc191761ab3a2) to [common interop folder](https://github.com/dotnet/corefx/tree/master/src/Common/src/Interop/Windows/perfcounter)
Add some tests taking a cue from https://msdn.microsoft.com/en-us/library/system.diagnostics.performancedata(v=vs.110).aspx (is [CTRPP](https://docs.microsoft.com/en-us/windows/desktop/PerfCtrs/ctrpp) available to CI workflow?)

Make sense?
Feel free to update the plan.

/cc @jkotas @brianrob @danmosemsft

**Comment by jkotas** [comment]
This should not touch CoreCLR in any way. None of this make sense to share with CoreCLR.

**Comment by MarcoRossignoli** [comment]
> This should not touch CoreCLR in any way. None of this make sense to share with CoreCLR.

Thank's!

**Comment by MarcoRossignoli** [comment]
Visual Studio started to require "One-way upgrade" when open solutions on corefx(for instance Common.Tests.csproj)...what i'm missing?
My Vs ver:

Microsoft Visual Studio Enterprise 2017 
Version 15.7.5
VisualStudio.15.Release/15.7.5+27703.2042
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

**Comment by ericstj** [comment]
/cc @eerhardt @weshaggard 

Haven't seen that.  What did VS change once you allowed it to upgrade?

**Comment by MarcoRossignoli** [comment]
added this to Common.Tests.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <ProjectGuid>{C72FD34C-539A-4447-9796-62A229571199}</ProjectGuid>
    <TestCategories>InnerLoop;OuterLoop</TestCategories>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Configurations>netcoreapp-Unix-Debug;netcoreapp-Unix-Release;netcoreapp-Windows_NT-Debug;netcoreapp-Windows_NT-Release</Configurations>
    <FileUpgradeFlags>
    </FileUpgradeFlags>
    <UpgradeBackupLocation>
    </UpgradeBackupLocation>
    <OldToolsVersion>2.0</OldToolsVersion>
  </PropertyGroup>
  .....
```

**Comment by eerhardt** [comment]
Hey @MarcoRossignoli - which .sln are you opening that is causing VS to say that?  Do you have any local changes to it?  or is it exactly what is checked into 'master'?

**Comment by MarcoRossignoli** [comment]
@eerhardt i'm opening https://github.com/MarcoRossignoli/corefx/blob/performancedata/src/Common/Common.Tests.sln from my clean branch...i'm starting to work on this issue adding  SafePerfProviderHandle to it.
![migration](https://user-images.githubusercontent.com/7894084/42964970-e604c6fe-8b98-11e8-92c1-9d0bb1cda9ec.png)

**Comment by eerhardt** [comment]
Thanks @MarcoRossignoli.  I just submitted https://github.com/dotnet/corefx/pull/31205 which will fix the problem.

**Comment by MarcoRossignoli** [comment]
@eerhardt you've requested my review...i don't know if you amend is correct...but if for you it's ok i'm onorated to approve a PR on corefx repo :sweat_smile: , do you need my approve or it's a mistake?

**Comment by eerhardt** [comment]
> do you need my approve or it's a mistake?

I don't necessarily **need** your approval, but it wasn't a mistake.  It was more of a notification and I wanted to include you since you found the issue.

**Comment by MarcoRossignoli** [comment]
> It was more of a notification and I wanted to include you since you found the issue.

Ok thank's for fix!

**Comment by MarcoRossignoli** [comment]
@ericstj where i can found all resource strings?I downloaded source for .net 4.7.2(DotNet472RS4) and try to find some string `findstr /n /s /c:"Perflib_PlatformNotSupported"  *.*` but i didn't find anything.

**Comment by MarcoRossignoli** [comment]
> but I'll save you the effort

Great thank's!

**Comment by jkotas** [comment]
> attributes like `[SecuritySafeCritical]` and `[SecurityCritical]` that i think i have to remove

These attributes are dead code in .NET Core. We have been removing them like all other kinds of dead code. Things are still going to work with these attributes, except that the binaries will be bigger necessary.  

> on other namespace i found it.

This is recently ported assembly where the dead attribute cleanup was missed. Feel free to remove the attributes in this assembly while you are on it.

**Comment by MarcoRossignoli** [comment]
@ericstj i think you can assign this issue to me if you want, i moved source https://github.com/dotnet/corefx/compare/master...MarcoRossignoli:performancedata and did some tests offline https://github.com/MarcoRossignoli/marcorossignoli.github.io/blob/master/corefx/src/Lab/PerformanceData/Program.cs 
I'm not so "expert" with this version of performance counter definitions, but seems to works!Take a look and if you think it's ok i'll add some tests and i'll do PR!

**Comment by ericstj** [comment]
Absolutely.  Thanks for looking into this!

**Comment by MarcoRossignoli** [comment]
On these sample there are some errors https://msdn.microsoft.com/en-us/library/system.diagnostics.performancedata(v=vs.110).aspx

```
<string id="CS1.Counter1.Name" value="Total Words Typed"/> ->  typingCounterSet.AddCounter(1, CounterType.RawData32, "Total Word Count");
<string id="CS1.Counter3.Name" value="Letter A Pressed"/>  -> typingCounterSet.AddCounter(3, CounterType.RawData32, "A Key Pressed");
<string id="CS1.Counter5.Name" value="Percent of Words Containing A"/>  ->  typingCounterSet.AddCounter(5, CounterType.SampleFraction, "Percent of Words Containg A");
```

maybe need to be fixed.
