### ISSUE TITLE
Passing Span<string> to String.Join()

### ISSUE THREAD

**Issue by richlander** [dotnet/corefx#30199]
I was hoping to write this code:

```csharp
var argSpan = new Span<string>(args, 1, args.Length);
argsString = String.Join(' ', argSpan);
```
Instread, I had to write this:

```csharp
var argSpan = new Span<string>(args, 1, args.Length);
argsString = String.Join(' ', argSpan.ToArray());
```

Or am I just holding span wrong?

**Comment by ahsonkhan** [comment]
There is no string.join overload that accepts a span. All of them are array based: https://apisof.net/catalog/System.String.Join(String,String())

We have an implicit conversion from array to span, but there is no implicit conversion from a span to an array (it requires allocation and data copy).

If we can support span-based params (see https://github.com/dotnet/csharplang/issues/535), then we could provide such an API.

cc @KrzysztofCwalina, @terrajobst

**Comment by richlander** [comment]
Isn't another option to add an overload to String.Join that takes a Span<string>?

I also tried:

```csharp
argsString = String.Join(" ", argSpan.GetEnumerator());
```

Can you explain why that didn't work?

**Comment by richlander** [comment]
This is my use case: https://github.com/richlander/tools/blob/master/src/dotnet-do/dotnet-do/LocalTools.cs#L45

**Comment by Tornhoof** [comment]
> Can you explain why that didn't work? 
Span does not implement IEnumerable as it's a byref type.
See https://github.com/dotnet/csharplang/issues/1085 for the discussion about it.

In your use case above you might want to use linq Skip/Take to shorten your args array

**Comment by aevitas** [comment]
@akashkc A slight performance gain, since calling `.ToArray()` on the slice allocates it, being able to `Join` directly forgoes that allocation.

**Comment by ahsonkhan** [comment]
> I also tried:

```csharp
argsString = String.Join(" ", argSpan.GetEnumerator());
```

> Can you explain why that didn't work?

Aside from the fact that span can't implement IEnumerable, the span enumerator itself is also a ref struct (since it contains a span field):
https://github.com/dotnet/corefx/blob/69c2e2072574805589becac0c08590dc5e39b65e/src/Common/src/CoreLib/System/Span.cs#L104

This let's you write foreach loops, but in your case, I believe you are trying to box a ref struct, trying to cast it to IEnumerable, which is why it won't work.

> Isn't another option to add an overload to String.Join that takes a Span?

Yes, that is viable alternative.

**Comment by ahsonkhan** [comment]
@richlander, looking at your specific use case, given you have to get a string at the end anyway (to pass into ProcessStartInfo), even if we had a span-based join overload, it won't help avoid all the allocations. You would end up creating a string regardless. Maybe providing span-based APIs on ProcessStartInfo is the way to go, to avoid the need for string.join all together. Thoughts?

**Comment by stephentoub** [comment]
> Maybe providing span-based APIs on ProcessStartInfo is the way to go, to avoid the need for string.join all together. Thoughts?

If you're starting processes using Process.Start, ProcessStartInfo, etc., I'd be extremely surprised if that made any measurable impact.

**Comment by richlander** [comment]
Until we have another use case, I consider this discussion closed. This discussion helped me apply a bunch of the theory I already knew about span more concretely (like why it cannot implement IEnumerable).
