### ISSUE TITLE
Add back most CreateInstance APIs to AppDomain and Activator

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#30190]
I've encountered a ton of desktop code that uses either 
AppDomain.CreateInstance(string, string)
AppDomain.CreateInstanceFrom(string, string)
AppDomain.CreateInstanceAndUnwrap(string, string)
AppDomain.CreateInstanceFromAndUnwrap(string, string)

And similar APIs on Activator.

I know these APIs were in support of remoting, but they are just too attractive since they deal in strings and folks can easily use them dynamic type loading (rather than first getting a type and then creating an instance from that).  Given that we've added back MarshalByRefObject I don't see any reason why we shouldn't just add back these APIs and make them work in the non-remoting case.  It'll save a lot of paper-cut type porting.

*update 6/28/2018*
## Actual API
```c#
namespace System {
    // Add to System.Runtime.Extensions contract & implementation
    public partial sealed class AppDomain {
        public ObjectHandle CreateInstance(string assemblyName, string typeName);
        public ObjectHandle CreateInstance(string assemblyName, string typeName, bool ignoreCase, BindingFlags bindingAttr, Binder binder, object[] args, CultureInfo culture, object[] activationAttributes);
        public ObjectHandle CreateInstance(string assemblyName, string typeName, object[] activationAttributes);
        public object CreateInstanceAndUnwrap(string assemblyName, string typeName);
        public object CreateInstanceAndUnwrap(string assemblyName, string typeName, bool ignoreCase, BindingFlags bindingAttr, Binder binder, object[] args, CultureInfo culture, object[] activationAttributes);
        public object CreateInstanceAndUnwrap(string assemblyName, string typeName, object[] activationAttributes);
        public ObjectHandle CreateInstanceFrom(string assemblyFile, string typeName);
        public ObjectHandle CreateInstanceFrom(string assemblyFile, string typeName, bool ignoreCase, BindingFlags bindingAttr, Binder binder, object[] args, CultureInfo culture, object[] activationAttributes);
        public ObjectHandle CreateInstanceFrom(string assemblyFile, string typeName, object[] activationAttributes);
        public object CreateInstanceFromAndUnwrap(string assemblyName, string typeName);
        public object CreateInstanceFromAndUnwrap(string assemblyFile, string typeName, bool ignoreCase, BindingFlags bindingAttr, Binder binder, object[] args, CultureInfo culture, object[] activationAttributes);
        public object CreateInstanceFromAndUnwrap(string assemblyName, string typeName, object[] activationAttributes);
    }

    // Add to System.Runtime contract, System.Private.CoreLib implementation
    public partial sealed class Activator {
        public static ObjectHandle CreateInstance(string assemblyName, string typeName);
        public static ObjectHandle CreateInstance(string assemblyName, string typeName, bool ignoreCase, BindingFlags bindingAttr, Binder binder, object[] args, CultureInfo culture, object[] activationAttributes);
        public static ObjectHandle CreateInstance(string assemblyName, string typeName, object[] activationAttributes);
        public static ObjectHandle CreateInstanceFrom(string assemblyFile, string typeName);
        public static ObjectHandle CreateInstanceFrom(string assemblyFile, string typeName, bool ignoreCase, BindingFlags bindingAttr, Binder binder, object[] args, CultureInfo culture, object[] activationAttributes);
        public static ObjectHandle CreateInstanceFrom(string assemblyFile, string typeName, object[] activationAttributes);
    }
}

// Add to System.Runtime contract, System.Private.CoreLib implementation since its needed by Activator
namespace System.Runtime.Remoting
{
    public class ObjectHandle : MarshalByRefObject {
        public ObjectHandle(object o);
        public object Unwrap();
    }
}
```

Noted omissions and reasons:
1. Overloads that accept `System.Security.Policy.Evidence`
    - Evidence type lives in System.Security.Permissions and is a stub type.  We wouldn't want to push this down into System.Runtime where Activator lives but would need to since these are statics that cannot be replaced with extension methods.
    - Low usage data, but non-zero.  Its possible folks may need this but lets wait for the specific use case, since this is costly and may require other complementary API for a scenario to work.
2. Overloads on `System.Activator` that accept `System.AppDomain`
    - Would require pushing AppDomain into System.Runtime
    - Zero usage data
3. `System.Runtime.Remoting.IObjectHandle` on `ObjectHandle`
    - Not required for any scenario
    - Zero usage data

**Comment by aevitas** [comment]
Out of legitimate curiosity, what use case do you have that makes instantiating objects by name feasible?

**Comment by ericstj** [comment]
You could think of this as analogous to loadlibrary/getprocaddress.  It’s used for runtime binding: light up, plugins, etc.

**Comment by danmosemsft** [comment]
@jeffschwMSFT thoughts about this? Is it on your team's plan?

In a cursory look this seems all managed code, built on Activator.CreateInstance but doing Assembly.LoadFrom first.

cc @jkotas  any concerns?

**Comment by jeffschwMSFT** [comment]
I like the general push for compatibility, but we should hold until we get a little further on unloadability (https://github.com/dotnet/coreclr/pull/18476).  We are also exploring a plug-in model that may dictate a bit more of the semantics of these apis.  The thought is let's decide on what we want them to return prior to getting them into the product.

**Comment by jkotas** [comment]
> Activator.CreateInstance but doing Assembly.LoadFrom first.

Yes, that makes them a pit of failure APIs. It would be nice if we can start flagging LoadFrom and its variants in https://github.com/dotnet/platform-compat.

We were forced to add multiple of these poor APIs for .NET Standard 2.0, so this is not going to make the situation that much worse. These are just a trivial wrappers over APIs that do exist already.

I do not have concerns about this.

**Comment by danmosemsft** [comment]
@jeffschwMSFT these API's are just semantic sugar over Assembly.LoadFrom + Activator.CreateInstance to make existing code port. If you plan to change Assembly.LoadFrom, they would inherit that change. Certainly we should add them our scanner tool as @jkotas suggests so that no new code is written that uses them. If you want to enable new, better behavior our general strategy is to create new API's rather than having two behaviors for the same API's. Given that, does it seem reasonable to do this now?

**Comment by jeffschwMSFT** [comment]
Given the only way to access these in .NET Core is to do System.AppDomain.CurrentDomain.* it seems fine to add the overloads.  My reservation is that as unloadability and plug-in is introduced the concept of CreateInstance within a load context is on our list of things to explore.  At this point I do not see any disadvantage of having these added, my only point was that we are also early in that thinking.

**Comment by danmosemsft** [comment]
Got it thanks @jeffschwMSFT . 

@MarcoRossignoli any interest in exposing some .NET Framework API? No obligation.

**Comment by MarcoRossignoli** [comment]
> And similar APIs on Activator.

Happy to help. Could be useful have a full method list we want to port.

**Comment by ericstj** [comment]
Here's the list:

## AppDomain
 - ObjectHandle CreateInstance(String, String)
 - ObjectHandle CreateInstance(String, String, Boolean, BindingFlags, Binder, Object[], CultureInfo, Object[])
 - ~~ObjectHandle CreateInstance(String, String, Boolean, BindingFlags, Binder, Object[], CultureInfo, Object[], Evidence)~~
 - ObjectHandle CreateInstance(String, String, Object[])
 - object CreateInstanceAndUnwrap(String, String)
 - object CreateInstanceAndUnwrap(String, String, Boolean, BindingFlags, Binder, Object[], CultureInfo, Object[])
 - ~~object CreateInstanceAndUnwrap(String, String, Boolean, BindingFlags, Binder, Object[], CultureInfo, Object[], Evidence)~~
 - object CreateInstanceAndUnwrap(String, String, Object[])
 - ObjectHandle CreateInstanceFrom(String, String)
 - ObjectHandle CreateInstanceFrom(String, String, Boolean, BindingFlags, Binder, Object[], CultureInfo, Object[])
 - ~~ObjectHandle CreateInstanceFrom(String, String, Boolean, BindingFlags, Binder, Object[], CultureInfo, Object[], Evidence)~~
 - ObjectHandle CreateInstanceFrom(String, String, Object[])
 - object CreateInstanceFromAndUnwrap(String, String)
 - object CreateInstanceFromAndUnwrap(String, String, Boolean, BindingFlags, Binder, Object[], CultureInfo, Object[])
 - ~~object CreateInstanceFromAndUnwrap(String, String, Boolean, BindingFlags, Binder, Object[], CultureInfo, Object[], Evidence)~~
 - object CreateInstanceFromAndUnwrap(String, String, Object[])

## Activator
 - ObjectHandle CreateInstance(AppDomain, String, String)
 - ObjectHandle CreateInstance(AppDomain, String, String, Boolean, BindingFlags, Binder, Object[], CultureInfo, Object[])
 - ~~ObjectHandle CreateInstance(AppDomain, String, String, Boolean, BindingFlags, Binder, Object[], CultureInfo, Object[], Evidence)~~
 - ObjectHandle CreateInstance(String, String)
 - ObjectHandle CreateInstance(String, String, Boolean, BindingFlags, Binder, Object[], CultureInfo, Object[])
 - ~~ObjectHandle CreateInstance(String, String, Boolean, BindingFlags, Binder, Object[], CultureInfo, Object[], Evidence)~~
 - ObjectHandle CreateInstance(String, String, Object[])
 - ObjectHandle CreateInstanceFrom(AppDomain, String, String)
 - ObjectHandle CreateInstanceFrom(AppDomain, String, String, Boolean, BindingFlags, Binder, Object[], CultureInfo, Object[])
 - ~~ObjectHandle CreateInstanceFrom(AppDomain, String, String, Boolean, BindingFlags, Binder, Object[], CultureInfo, Object[], Evidence)~~
 - ObjectHandle CreateInstanceFrom(String, String)
 - ObjectHandle CreateInstanceFrom(String, String, Boolean, BindingFlags, Binder, Object[], CultureInfo, Object[])
 - ~~ObjectHandle CreateInstanceFrom(String, String, Boolean, BindingFlags, Binder, Object[], CultureInfo, Object[], Evidence)~~
 - ObjectHandle CreateInstanceFrom(String, String, Object[])

I've stricken those that use Evidence since that would require pushing Evidence down to System.Runtime.  

You'll need to add back **ObjectHandle** as well, but this shouldn't be a problem since we already have MarshalByRefObject in System.Runtime and this is a simple implementation of that (you can omit the InitializeLifetimeService() overload since it's irrelevant on .NETCore).  ObjectHandle will need to go into System.Runtime.  I don't think we need to bring back IObjectHandle, @luqun or @jkotas might know better if the COM scenario still applies; I haven't seen it in any of my investigations.

**Comment by jkotas** [comment]
What is the reason for bringing back ObjectHandle? I do not think we should do that.

**Comment by ericstj** [comment]
Actually that’s the whole point of this issue.  Folks are using these APIs to create objects in the current  domain and use them.  I encountered several cases where CreateInstance is immediately followed by unwrap and cast.
What part of this won’t work in the context of .NETCore?

**Comment by jkotas** [comment]
Could you please update the top with the exact API diff that this is about (including the method on ObjectHandle, etc.).?

**Comment by jkotas** [comment]
What you got above would require moving System.AppDomain, with its dependency closure, into System.Runtime and CoreLib. It can be done and I would not be opposed to doing it, but it is a non-trivial operation that has to be staged.

**Comment by jkotas** [comment]
> Actually that’s the whole point of this issue.

Ok, I see. It was not obvious to me - I though that this is just about the few missing string overloads.

**Comment by ericstj** [comment]
>  It was not obvious to me - I though that this is just about the few missing string overloads.

Sorry about that, I should have included the full signature.

> What you got above would require moving System.AppDomain, with its dependency closure, into System.Runtime and CoreLib. It can be done and I would not be opposed to doing it, but it is a non-trivial operation that has to be staged.

I see, because of the Activator methods that take an AppDomain.

We can split the work into two stages.  First stage: add ObjectHandle, and all overloads which don't accept an AppDomain.  Second stage: add Activator members which accept and AppDomain.  I'd actually be OK omitting the AppDomain members from Activator.  I haven't seen any usage of these ones.

I'll update this accordingly.

**Comment by jkotas** [comment]
> Noted omissions and reasons:
> Overloads on System.Activator that accept System.AppDomain

I did not see the AppDomain ones actually omitted from the proposal. I assume that it is oversight and fixed it.

LGTM otherwise.

**Comment by luqunl** [comment]
> @luqunl or @jkotas might know better if the COM scenario still applies; 

AFAIK, COM scenario don't use these APIs much especially after NoPIA enabled by default. Some people may use Activator.CreateInstance<T> version.

**Comment by MarcoRossignoli** [comment]
I'm following discussion. Let me know if/when i can start with implementation for CoreLib. 
If this issue is still open to external contrib my idea is start with code from [here](https://referencesource.microsoft.com/#mscorlib/system/runtime/remoting/objecthandle.cs,45da82b08497518d) to System.Runtime.Extension on corefx with proper tests(i don't know if there are already some tests for these objects to use, maybe are not public). I could open WIP PR during development for open questions or doubt if you agree. 

/cc @jkotas @danmosemsft

**Comment by jkotas** [comment]
@MarcoRossignoli You are welcomed to take this! ObjectHandle is the right one to start with - you should add it to CoreLib first.

**Comment by justintoth** [comment]
I'm not seeing a CreateInstanceAndUnwrap method on Activator or AppDomain, despite it showing it in the documentation [here ](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain?view=netstandard-2.0)for .NET Standard 2.0. Is the documentation wrong and this will be in .NET Standard 2.1?

**Comment by jkotas** [comment]
These APIs are not available in .NET Standard 2.0. If you click on CreateInstanceAndUnwrap in the docs, you should see:

![image](https://user-images.githubusercontent.com/6668460/52145444-d0289500-2615-11e9-93e7-183a733bd3f8.png)

I agree that the docs can make this easier to see.
