### ISSUE TITLE
Accessing Process.HasExited throws an "access is denied" exception if the target process is running with elevated permissions

### ISSUE THREAD

**Issue by Giorgi** [dotnet/corefx#302]
Accessing `Process.HasExited` throws an "access is denied" exception if the target process is running with elevated permissions and the caller does not.

This was reported by me and confirmed by BCL Team but wasn't fixed: [Connect Issue](https://connect.microsoft.com/VisualStudio/feedback/details/714808/process-hasexited-throws-exception-if-the-process-is-running-with-elevated-permissions)

The error occurs as `ProcessManager` is calling `OpenProcess` with `PROCESS_QUERY_INFORMATION` access right while on Vista and Windows 7 it is enough to use `PROCESS_QUERY_LIMITED_INFORMATION` for getting handle.

**Comment by GreatFireWall** [comment]
2019 still not fixed..

**Comment by stephentoub** [comment]
That code is for .NET Framework, not .NET Core.
