### ISSUE TITLE
NegotiateStream don't read full data

### ISSUE THREAD

**Issue by caesar1995** [dotnet/corefx#30219]
1.	One side writes a large number of Bytes (bigger than NegoState.MaxWriteDataSize = 63 * 1024) to the NegotiateStream, the other side does a Read, and only able to read the first NegoState.MaxWriteDataSize bytes of data, and ignore the rest. Even though the write side successfully sent all the data.
2.	This bug happens on both sync path and async path.
3.	The authenticated process will succeed, only the data transferred is missing on the other side. 
a.	The data encrypt/decrypt part will succeed as well. (_negoState.DecryptData/EncryptData will not throw Exception)

The remaining data can be retrieved in subsequent sync/async Read() operation.

Same behavior will happen on .NET Framework.

```c#
        internal const int MaxWriteDataSize = 63 * 1024; // NegoState.MaxWriteDataSize
        private static string s_longString = new string('A', MaxWriteDataSize) + 'Z';
        private readonly byte[] _longMsg = Encoding.ASCII.GetBytes(s_longString);
 
        [Fact]
        public async Task NegotiateStream_ClientWriteLongMsgSync_Success()
        {
            byte[] recvBuf = new byte[_longMsg.Length];
            VirtualNetwork network = new VirtualNetwork();
 
            using (var clientStream = new VirtualNetworkStream(network, isServer: false))
            using (var serverStream = new VirtualNetworkStream(network, isServer: true))
            using (var client = new NegotiateStream(clientStream))
            using (var server = new NegotiateStream(serverStream))
            {
                Assert.False(client.IsAuthenticated);
                Assert.False(server.IsAuthenticated);
 
                Task[] auth = new Task[2];
                auth[0] = AuthenticateAsClientAsync(client, CredentialCache.DefaultNetworkCredentials, string.Empty);
                auth[1] = AuthenticateAsServerAsync(server);
 
                await TestConfiguration.WhenAllOrAnyFailedWithTimeout(auth);
 
                client.Write(_longMsg, 0, _longMsg.Length);
                // Will only read first NegoState.MaxWriteDataSize bytes.
                server.Read(recvBuf, 0, _longMsg.Length);
 
                // This will fail. `Z` will not be received, instead Asc value of 0 will be the last byte in the recvBuf.
                Assert.True(_longMsg.SequenceEqual(recvBuf));
            }
        }
```

This bug will harm data integrity, and can cause other unexpected behaviors. For example:

```c#
client.Write(_longMsg, 0, _longMsg.Length);
server.Read(recvBuf, 0, _longMsg.Length);

// User think the first _longMsg is completely received, then start the next write/read.

client.Write(_sampleMsg, 0, _sampleMsg.Length);
server.Read(recvBuf, 0, _sampleMsg.Length); 

// However, the new _sampleMsg will be completely ignored, instead the remaining part of the _longMsg is getting Read here. So user can get unexpected data.
```

/cc: @dotnet/ncl

**Comment by stephentoub** [comment]
Unless I'm misunderstanding, this isn't a bug.  Stream.Read is never guaranteed to return the requested number of bytes; it's allowed to return any number from [1, count], or 0 to indicate EOF.

**Comment by caesar1995** [comment]
You are right (https://msdn.microsoft.com/en-us/library/system.net.security.negotiatestream.read(v=vs.110).aspx)... Thanks for pointing this out!

Since 1. return value correctly reflects how many bytes are read 2. the remaining data can be retrieved in subsequent Read() operation, this can be closed by design.
