### ISSUE TITLE
Concurrent Bag Exception

### ISSUE THREAD

**Issue by beldebala** [dotnet/corefx#30210]
Having issue using Concurrent Bag. 
Seeing below exception. Could you please suggest what should be done. I am new to concurrent bag collection

Invalid Operation Exception :  You must implement a default accesor on System.Collections.ConcurrentBag because it inherits from Icollection

**Comment by stephentoub** [comment]
That exception doesn't sound like it's coming from ConcurrentBag.  It sounds more like you're trying to serialize a ConcurrentBag instance using XmlSerializer.

**Comment by huanwu** [comment]
@beldebala could you share the repro code?

**Comment by Lxiamail** [comment]
@beldebala Closing it for now. Please let us know if you still have problem.
