### ISSUE TITLE
Are System.Security.Cryptography.Oid.FriendlyName values expected to be consistent across platforms?

### ISSUE THREAD

**Issue by cabadam** [dotnet/corefx#30236]
Have a certificate with a Subject Alternative Name, for example, the cert used to sign Alexa skill requests:
https://s3.amazonaws.com/echo.api/echo-api-cert-5.pem

Against that certificate, execute the following code in a .NET Core 2.1 application:
```C#
            X509Certificate2 cert = new X509Certificate2(File.ReadAllBytes("echo-api-cert-5.pem"));
            string extensions = string.Join(Environment.NewLine, cert.Extensions.Cast<X509Extension>()
                .Select(n => $"Friendly Name: {n.Oid.FriendlyName} - Oid: {n.Oid.Value}"));
            Console.WriteLine(extensions);
```

When run on a Windows box, this yields:
> Friendly Name: Subject Alternative Name - Oid: 2.5.29.17
> Friendly Name: Basic Constraints - Oid: 2.5.29.19
> Friendly Name: Key Usage - Oid: 2.5.29.15
> Friendly Name: Enhanced Key Usage - Oid: 2.5.29.37
> Friendly Name: Certificate Policies - Oid: 2.5.29.32
> Friendly Name: Authority Key Identifier - Oid: 2.5.29.35
> Friendly Name: CRL Distribution Points - Oid: 2.5.29.31
> Friendly Name: Authority Information Access - Oid: 1.3.6.1.5.5.7.1.1
> Friendly Name: SCT List - Oid: 1.3.6.1.4.1.11129.2.4.2

However, when run on a linux-arm platform (Raspberry Pi 3), this yields:
> Friendly Name: X509v3 Subject Alternative Name - Oid: 2.5.29.17
> Friendly Name: X509v3 Basic Constraints - Oid: 2.5.29.19
> Friendly Name: X509v3 Key Usage - Oid: 2.5.29.15
> Friendly Name: X509v3 Extended Key Usage - Oid: 2.5.29.37
> Friendly Name: X509v3 Certificate Policies - Oid: 2.5.29.32
> Friendly Name: X509v3 Authority Key Identifier - Oid: 2.5.29.35
> Friendly Name: X509v3 CRL Distribution Points - Oid: 2.5.29.31
> Friendly Name: Authority Information Access - Oid: 1.3.6.1.5.5.7.1.1
> Friendly Name: CT Precertificate SCTs - Oid: 1.3.6.1.4.1.11129.2.4.2

The names are similar, yet different.  I was originally searching for extensions based on the names, but I wasn't sure if this difference is correct or not.  If it is correct, then I think I'll need to filter based on the Oid value instead.

Note that running OpenSSL on Windows:
openssl x509 -in .\echo-api-cert-5.pem -text

Gives output which matches the names from the .NET Core linux-arm output.

>        X509v3 extensions:
>             X509v3 Subject Alternative Name:
>                 DNS:echo-api.amazon.com
>             X509v3 Basic Constraints:
>                 CA:FALSE
>             X509v3 Key Usage: critical
>                 Digital Signature, Key Encipherment
>             <snipped for brevity>

**Comment by bartonjs** [comment]
No, they're not.  They're not even guaranteed to be the same across languages.

OID friendly names which are the same on Windows en-US, ja-JP, and es-ES got hard-coded to provide a stable lookup table for the most common identifiers.

For example, on Windows es-ES "Subject Alternative Name" is "Nombre alternativo del titular" and "Enhanced Key Usage" is "Uso mejorado de claves".  (ja-JP: "サブジェクト代替名" and "拡張キー使用法")

**Comment by cabadam** [comment]
Gotcha, the languages I expected.  I'll make sure we base on the oid value.  Many of the examples online are doing string matching on the name.  I wasn't sure if they knew something I didn't :)

Thanks

**Comment by Mani0811** [comment]
is this Added as feature In 3.0
