### ISSUE TITLE
IMemoryCache.Dispose should call Dispose on cached value if it implements IDisposable

### ISSUE THREAD

**Issue by nockawa** [dotnet/corefx#30234]
Right now there's no way to enumerate all the entries that are present in the cache.
So when a CacheEntry stores a value that implements IDisposable, we should:

- Call Dispose() on the cached value when the CacheEntry expires.
- Dispose all cached values when Dispose() is performed on IMemoryCache implementation.

**Comment by KKhurin** [comment]
Thanks @nockawa for the feedback. 
I wonder if having the cached object disposed by just dropping it from the cache is a desired behavior in case when this cache entry is also referenced by someone else outside of the cache?

**Comment by nockawa** [comment]
Well, from my perspective the lifetime of the object is owned by the cache and objects are always accessed from it, I don't intend to store a reference to an object part of the cache somewhere, I get it from the cache, process and release it. I believe this is the behavior for cached object as we don't want to control their lifetime otherwise they wouldn't be discarded.
I didn't take a deep look at the implementation and unfortunately the documentation is sparse...
But if someone could clarify the intended purposed of cached objects, that would help I guess.

**Comment by KKhurin** [comment]
Consider the following scenario:
- an object is stored in the cache and only the cache has the reference to it
- user code gets this object (e.g. there is a second reference to it) and starts using it
- cache senses memory pressure and choses to evict this object (and calls Dispose() on it)
- user code continues using the object even though it is now disposed
Looks like a recepe for troubles and various timing issues.

**Comment by nockawa** [comment]
Indeed, in multi-thread environment (which is the case) it is a possible scenario.
I've took a quick look at the implem and I now understand what you mean.
In the past I have written a similar class where the `CacheEntry` had two pointers to the object, a Strong One to keep it "as long as necessary", then I will transfert the Object to a `WeakReference` and I would remove a object from the cache only if the WeakRef would tell me the object is not used anymore.

Anyway, I would just like to point out that I've suggested two behaviors and the other is far more important to me: 
When I manually call `Dispose()` on `IMemoryCache` I would expect `Dispose` to be called on every object stored inside, today it's not the case and I don't even have a possibility to do it on my own as I can't enumerate the cache's content.

This could be done at implem side by preventing concurrent add (setting the _isDisposed flag immediately?) and looping through the whole content, don't you think?

For the former use case I can still use the callback to be notified when the object is removed from the cache, which is a workaround for me to dispose its content. So I would say the use case of Disposing every cached object upon `IMemoryCache.Dispose` scenario is far more essential to me.

**Comment by ViktorHofer** [comment]
ping @KKhurin, @Lxiamail, @zhenlan

**Comment by KKhurin** [comment]
@ViktorHofer, is the workaround I mentioned above not working for you? 

Aside from being a "breaking change", I am not convinced that MemoryCache.Dispose is responsible for disposing all of its entries. Cache does not necessarily "own" the objects it references and there is no way to know if it should dispose them. Therefore Dispose is merely responsible for cleaning up cache internal resources (timers, etc).

**Comment by ViktorHofer** [comment]
I pinged you as this issue isn't triaged. Please set a milestone or close if you thing it doesn't make sense.

**Comment by KKhurin** [comment]
Oh, got it! Closing.
