### ISSUE TITLE
Visual Studio 2017 15.7.3 .NET Core Workload installs .NET Core SDK 2.1.201 (.NET Core 2.0) instead of 2.1.300 (.NET Core 2.1)

### ISSUE THREAD

**Issue by MBODM** [dotnet/corefx#30231]
Hey,

sorry, did not found a better place for this issue, since Visual Studio has not easy issues support page for setup workloads. Maybe you can direct this issue to the right place.

As title says, you can download and install .net core sdk for 2.1 (named .net core sdk 2.1.300) manually from official MS .net core homepage. All fine and so. But normally Visual Studio do this via update and installer. So i installed Visual Studio 2017 15.7.3 this way (by updating or fresh install), the .net core workload of VS installs the .net core sdk 2.1.201 (latest .net core 2.0) instead of .net core sdk 2.1.300 (.net core 2.1). Why ? 

Why does the VS workload target the old 2.0 sdk instead the new 2.1 sdk ?

**Comment by huoyaoyuan** [comment]
![image](https://user-images.githubusercontent.com/5644458/41194566-bf68e9a2-6c4f-11e8-98ed-284b54d4ba5e.png)
Currently, manifest in VS hasn't been updated, and it refers to `.Net Core 2.0 Tools`, .Net Core 2.1 and .Net Framework 4.7.2 are not included. Same thing happened when .Net Framework 4.7.1 was released.
It seems that new platform won't be included until next minor update(15.8), and fix update (15.7.x) won't introduce new features.

**Comment by MBODM** [comment]
From where do you have that information, or better: Where lies that manifest file ? Where can i see what .net core sdk version the actual VS workload targets ?

**Comment by MBODM** [comment]
Ah, now i understand. Is there anywhere a place, blog, roadmap, github, etc. where ppl can either download a newer workload (i found that list of workload component ids) or at least see when VS will bring the new SDK with it (roadmap) ?

It’s somewhat ... uncool ... to read everywhere about .net core 2.1 release and whatever, while not having access to it via normal VS stuff.

Don‘t get me wrong: I know i can download the newest SDK and just install it. But there are 2 problems with that:

1) Its not the standard way to do. This isn‘t really a problem. But i also don‘t know if it will cause problems, when the VS installer a bit later wanna do the same. At least it is somewhat iritating for ppls.

2)
The bigger problem is: Who deliver the VS project templates for 2.1 ? And the tooling like Razor Engine support, TagHelper visualization, and additional stuff VS needs with new existing stuff in 2.1 ? The templates is a own question, cause i have no glue how you can get them without a appropriate workload bringing them in ? Where are they and how can i get them, when i just install the newest SDK ?

**Comment by karelz** [comment]
Maybe it would be best to ask for VS plans from VS Feedback (e.g. via the icon at the top right corner). Or you can directly ask on https://developercommunity.visualstudio.com/spaces/8/index.html.

**Comment by MBODM** [comment]
Allright, will move it over there. Thx a lot for the fast answers!
PS: You guys do a great job! Really.
