### ISSUE TITLE
Is fuzz directory needed in brotli?

### ISSUE THREAD

**Issue by kasper3** [dotnet/corefx#30249]
I am sweeping C++ sources in the repo and found two unused .cc files in `fuzz` subdirectory under brotli:

https://github.com/dotnet/corefx/tree/b1a9ddd2f64f81b37eb0c737de601e6d7a524cba/src/Native/AnyOS/brotli/fuzz

@ianhays, the script in that directory requires a CMakeLists.txt to be present two directories above (such as https://github.com/xingyun86/ppshuai_brotli/blob/9898e334a9a749fc387048433cdef9643657852a/src/brotli/brotli/CMakeLists.txt), but in CoreFX port that CMakeLists.txt file was removed from brotli's root. Currently there is nothing in corefx that touches this directory. Should it be removed?

**Comment by ianhays** [comment]
I'd be surprised if those are the only files that aren't being used, to be honest.

The brolti native code is a direct port of the c code at google/brotli and is kept 1:1 to enable easy updating when google makes fixes. So we've got a bunch of junk in there that prolly isn't getting used.

We can probably rip it out if it isn't listed at 

https://github.com/dotnet/corefx/blob/b1a9ddd2f64f81b37eb0c737de601e6d7a524cba/src/Native/Unix/System.IO.Compression.Native/CMakeLists.txt#L14

 or 

https://github.com/dotnet/corefx/blob/b1a9ddd2f64f81b37eb0c737de601e6d7a524cba/src/Native/Windows/clrcompression/CMakeLists.txt#L50

**Comment by kasper3** [comment]
I opened a PR upstream https://github.com/google/brotli/pull/682 for C++ to C conversion of two files under `fuzz` directory and also an issue https://github.com/google/brotli/issues/681. It seems like @eustas may move `fuzz` out of `c` directory instead. Meanwhile in CoreFX, this can be removed already as per your suggestion @ianhays.

**Comment by kasper3** [comment]
@ianhays, now that Brotli's new version is released: https://github.com/google/brotli/releases/tag/v1.0.5. Should I prepare a PR or could we get it from @dotnet-bot to update sources from v1.0.5 tag  branch upstream (https://github.com/google/brotli/tree/v1.0.5)?

It fixes some bugs as we as from CoreFX point of view, closes this issue and addresses one of the PR feedback: https://github.com/dotnet/corefx/pull/30495#discussion_r197147585.
