### ISSUE TITLE
Avx2.BroadcastScalarToVector128(T*) overloads are missing

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#30266]
Avx2 is currently only exposing the `Avx2.BroadcastScalarToVector128(Vector128<T>)` overloads.

It should also expose the `Avx2.BroadcastScalarToVector128(T*)` overloads (exploding `T`, due to the limitations on using `T*`) to have parity with the overloads available for `float`/`double` in `Avx` and to ensure that the `VPBROADCASTB xmm, m8` encodings are properly exposed.

**Comment by tannergooding** [comment]
FYI. @eerhardt, @CarolEidt, @fiigii

**Comment by tannergooding** [comment]
Found this API missing when porting the DirectX math library: https://github.com/Microsoft/DirectXMath

**Comment by fiigii** [comment]
@tannergooding Can we implement these overloads by containment optimization?

**Comment by tannergooding** [comment]
@fiigii, not easily.

Users would have to convert a `ref T` into a `ref Vector128<T>` and understand that it is safe to do that since this operation only reads T bytes.

I think it is more understandable, and easier to handle, if we just add T* overloads.

**Comment by fiigii** [comment]
> Users would have to convert a ref T into a ref Vector128<T>

Agree.

>  if we just add T* overloads.

Don't you mean the overloads of pointers to all integer types (e.g., `byte*`, `short*`, etc) or generic `ref`? As I know, C# does not have generic pointers.

**Comment by tannergooding** [comment]
>Don't you mean the overloads of pointers to all integer types

Right, hence the `exploding T, due to the limitations on using T*` comment in the original post.

> As I know, C# does not have generic pointers.

It does, as of C# 7.3 with the `unmanaged` constraint. But there are issues with doing that (such as requiring the compiler to understand the new `modreq` attribute) that make it less desirable to use in the framework.
