### ISSUE TITLE
Does System.Reflection.DispatchProxy support a subclass with a constructor with parameter

### ISSUE THREAD

**Issue by baron-zhang-avepoint** [dotnet/corefx#30262]
I want to write a common DispatchProxy class which can be accept some parameters, this kind of classes are both supported by Java // Proxy.newProxyInstance   or by .net framework RealProxy,  while System.Reflection.DispatchProxy  is only accept a non-parameter subclass, Does the team or the corefx has the plan to support this.

**Comment by AtsushiKan** [comment]
There are no current plans to extend dispatch proxy. If you wish to propose a new api or a change to an existing api, please see the api review process: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md
