### ISSUE TITLE
System.Threading.Tasks.Extensions version in UWP 16300 does not match netstandard2.0 API

### ISSUE THREAD

**Issue by anurse** [dotnet/corefx#30276]
The System.Threading.Tasks.Extensions package has a `lib/uap10.0.16300/_._` file, meaning the reference is marked as in-box. However, the in-box version seems to be System.Threading.Tasks.Extension 4.1.2.0 whereas the `ref/netstandard2.0/System.Threading.Tasks.Extensions.dll` is 4.2.0.0.

As a result, when referencing a library built against `netstandard2.0` from a UWP application targeting "Windows 10, version 1803" as the **minimum** version a FileLoadException is thrown:

```
System.IO.FileLoadException: 'Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. 
```

This can be reproduced in https://github.com/anurse/UWPValueTask . The UWPValueTask project has `TargetPlatformMinVersion` set to `10.0.17134.0` and throws the FileLoadException on launch (I had to enable first-chance exceptions to see the specific exception, otherwise I just hit the `Windows.UI.Xaml.Application.UnhandledException` event handler)

Changing the MinVersion to "Fall Creators Update" resolves the issue, because the application uses the `lib/netstandard2.0/System.Threading.Tasks.Extensions.dll` which **is** version 4.2.0.0.

**Comment by anurse** [comment]
This is blocking SignalR Client usage in UWP (https://github.com/aspnet/SignalR/issues/2406)

**Comment by danmosemsft** [comment]
@joperezr @safern do you have context on this?

**Comment by weshaggard** [comment]
@joperezr fixed this wtih https://github.com/dotnet/corefx/pull/29970. You will need to reference 4.5.1 version of System.Threading.Tasks.Extension package.

**Comment by joperezr** [comment]
The placeholders where removed as @weshaggard suggests, so this should work now with the latest set of packages.

**Comment by anurse** [comment]
Ok, so since we don't actually reference `System.Threading.Tasks.Extensions` in SignalR (we get it via `System.IO.Pipelines`), I presume we have to flatten those out to get the fix. At least that gives customers a way to work around this. I'll close this for now and we'll figure out how to proceed with this fix from our end.
