### ISSUE TITLE
SafeHandle has been closed when using WindowsIdentity.RunImpersonated

### ISSUE THREAD

**Issue by ge0rgi** [dotnet/corefx#30275]
Hello everyone.

I am having trouble using Impersonation in asp.net core. I have an .NET core web API and .NET web application both running .NET core 2.1 and  using Windows Authentication.

I am trying to access the web service from the web application like this:

```c#
var identity = User.Identity as WindowsIdentity;

var test = WindowsIdentity.RunImpersonated(identity.AccessToken, () =>
{
   var client = new HttpClient(new HttpClientHandler() { UseDefaultCredentials = true }) { BaseAddress = new Uri(MY_URL) };
    try
    {
        var rq = new HttpRequestMessage(HttpMethod.Get, "mymethod");
        var response = client.SendAsync(rq).Result;
        var responseString = response.Content.ReadAsStringAsync().Result;
        return responseString;
    }
    catch (Exception e)
    {
        return null;
    }
});
```

I am getting the following Error on the production server and occasionally on my local machine 

> The process was terminated due to an unhandled exception.System.ObjectDisposedException: Safe handle has been closed
 
Full stack trace:

```
> Application: dotnet.exe
CoreCLR Version: 4.6.26515.7
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: An exception was not handled in an AsyncLocal<T> notification callback.
Description: The process was terminated due to an unhandled exception.System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Advapi32.ImpersonateLoggedOnUser(SafeAccessTokenHandle userToken)
   at System.Security.Principal.WindowsIdentity.CurrentImpersonatedTokenChanged(AsyncLocalValueChangedArgs`1 args)
   at System.Threading.AsyncLocal`1.System.Threading.IAsyncLocal.OnValueChanged(Object previousValueObj, Object currentValueObj, Boolean contextChanged)
   at System.Threading.ExecutionContext.OnValuesChanged(ExecutionContext previousExecutionCtx, ExecutionContext nextExecutionCtx)
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at System.Threading.ExecutionContext.OnValuesChanged(System.Threading.ExecutionContext, System.Threading.ExecutionContext)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(System.Exception, Int32, System.Net.Sockets.SocketFlags)
   at System.Net.Sockets.MultipleConnectAsync.AsyncFail(System.Exception)
   at System.Net.Sockets.MultipleConnectAsync.Fail(Boolean, System.Exception)
   at System.Net.Sockets.MultipleConnectAsync.DoDnsCallback(System.IAsyncResult, Boolean)
   at System.Net.Sockets.MultipleConnectAsync.DnsCallback(System.IAsyncResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr)
   at System.Net.ContextAwareResult.CompleteCallback()
   at System.Net.ContextAwareResult+<>c.<Complete>b__15_0(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Net.ContextAwareResult.Complete(IntPtr)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(System.Object, IntPtr)
   at System.Net.NameResolutionPal+GetAddrInfoExState+<>c.<CompleteAsyncResult>b__5_0(System.Object)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__278_1(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe()
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

Am I misusing the the access token somehow and how do I prevent the handle from being disposed. I tried wrapping my code inside a using block, however this did not help.

**PS** Probably related to #25477 I had the same issues when attempting to create a middleware calling `WindowsIdentity.RunImpersonated`

**Comment by stephentoub** [comment]
@kouvel, do you think this could be caused by https://github.com/dotnet/coreclr/issues/17758?

**Comment by kouvel** [comment]
The context changed handler does not dispose the handle passed in, so I don't think dotnet/coreclr#17758 would affect it. I suspect some async callback is trying to impersonate again using the access handle, but after it has been disposed elsewhere. Netfx gets around this by duplicating the access token, that may be missing in Core.

**Comment by kouvel** [comment]
Repro:

```c#
        Task task = null;
        using (var token = WindowsIdentity.GetCurrent().AccessToken)
        {
            WindowsIdentity.RunImpersonated(token, () =>
                task = Task.Run(async () =>
                    await Task.Delay(1000).ConfigureAwait(false)));
        }

        task.Wait();
```

**Comment by kouvel** [comment]
Workaround for now:

```c#
    private static void Main()
    {
        Task task = null;
        using (var token = WindowsIdentity.GetCurrent().AccessToken)
        {
            WindowsIdentity.RunImpersonated(DuplicateAccessToken(token), () =>
                task = Task.Run(async () =>
                    await Task.Delay(1000).ConfigureAwait(false)));
        }

        task.Wait();
    }

    private static SafeAccessTokenHandle DuplicateAccessToken(IntPtr accessToken)
    {
        SafeAccessTokenHandle duplicateAccessToken = SafeAccessTokenHandle.InvalidHandle;
        IntPtr currentProcessHandle = GetCurrentProcess();
        if (!DuplicateHandle(
                currentProcessHandle,
                accessToken,
                currentProcessHandle,
                ref duplicateAccessToken,
                0,
                true,
                DUPLICATE_SAME_ACCESS))
        {
            throw new SecurityException(new Win32Exception().Message);
        }

        return duplicateAccessToken;
    }

    private static SafeAccessTokenHandle DuplicateAccessToken(SafeAccessTokenHandle accessToken)
    {
        Debug.Assert(accessToken != null);

        if (accessToken.IsInvalid)
        {
            return accessToken;
        }

        SafeAccessTokenHandle duplicateAccessToken = DuplicateAccessToken(accessToken.DangerousGetHandle());
        GC.KeepAlive(accessToken);
        return duplicateAccessToken;
    }

    [DllImport("kernel32.dll")]
    private static extern IntPtr GetCurrentProcess();

    [DllImport("kernel32.dll", SetLastError = true)]
    private static extern bool DuplicateHandle(
        IntPtr hSourceProcessHandle,
        IntPtr hSourceHandle,
        IntPtr hTargetProcessHandle,
        ref SafeAccessTokenHandle lpTargetHandle,
        uint dwDesiredAccess,
        bool bInheritHandle,
        uint dwOptions);

    private const uint DUPLICATE_SAME_ACCESS = 0x00000002;
```

@ge0rgi, could you please try something like this as a workaround for now and let me know if that resolves the issue? Meanwhile, I've marked this issue for 2.1 servicing.

**Comment by ge0rgi** [comment]
@kouvel I can confirm your workaround resolves the issue.

**Comment by kouvel** [comment]
Thanks @ge0rgi, I have updated the workaround code inline above based on feedback in the PR

**Comment by karelz** [comment]
Fixed in 2.1 servicing in PR #30379. Closing.
Should be part of 2.1.3 release.

**Comment by LeroyPakade** [comment]
I upgraded to 2.1.3 , the bug is still there

**Comment by danmosemsft** [comment]
@kouvel ?

**Comment by kouvel** [comment]
@LeroyPakade, based on https://github.com/dotnet/corefx/pull/30379#issuecomment-479867402 it does not sound like the error is related to impersonation. Since the error mentions something about host name resolution not working, does it work if the IP address is used directly?

**Comment by LeroyPakade** [comment]
I doesn't work even if i try use the IP , it works for some users but fail for others, if i change the user's context to WindowsIdentity.GetCurrent().AccessToken than it works but i want to use ((WindowsIdentity)this.User.Identity).AccessToken , Because i want to impersonate the logged in user and not the IIS user

**Comment by kouvel** [comment]
Do you get the same error when using IP?

**Comment by LeroyPakade** [comment]
Yes ,only thing i was wondering was this windows policy , impersonate a client after authentication

**Comment by Cynthia-Jiang** [comment]
> Yes ,only thing i was wondering was this windows policy , impersonate a client after authentication

are you getting similar error like me? [37120](https://github.com/dotnet/corefx/issues/37120)
during my testing, i also checked this post, and found that duplicate access token didn't make a difference.
and i further found that if i turn off SocketsHttpHandler, it could work. can you try as well?

**Comment by davidsh** [comment]
>and i further found that if i turn off SocketsHttpHandler, it could work. can you try as well

The fact that it works by turning off SocketsHttpHandler (and thus using WinHttpHandler) is probably a race condition accident.  As mentioned above,

**Comment by davidsh** [comment]
>and i further found that if i turn off SocketsHttpHandler, it could work. can you try as well?

As mentioned in #37120, RunAsImpersonated is a synchronous call. So, are you able to reproduce your error if don't use async calls?

**Comment by LeroyPakade** [comment]
i turned SocketsHttpHandler off still had the issue for some users only when i change HttpClientHandler to WinHttpHandler it works but than i need to supply ServerCredentials which i dont have as previously i used ,  UseDefaultCredentials = true

**Comment by davidsh** [comment]
@LeroyPakade If you're still seeing this problem in .NET Core 3.0, please open a new issue. Thx.

You can try out .NET Core 3.0 Preview 4:
https://devblogs.microsoft.com/dotnet/announcing-net-core-3-preview-4/

**Comment by LeroyPakade** [comment]
Its working now with WinHttpHandler

**Comment by satyendrasinghpanwar** [comment]
@davidsh SocketHttpHandler works If I use ip. But with localhost or any other  hostname it gives me "This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server" error. If i use WinHttpHandler then everything works.

**Comment by davidsh** [comment]
>@davidsh SocketHttpHandler works If I use ip. But with localhost or any other hostname it gives me "This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server" error. If i use WinHttpHandler then everything works.

#37120 is already discussing this error.  Let's keep the conversation about this error on that open issue only.
