### ISSUE TITLE
Zip package becomes corrupted (CRC error)

### ISSUE THREAD

**Issue by igitur** [dotnet/corefx#30317]
Refer to https://github.com/OfficeDev/Open-XML-SDK/issues/506

This is an issue I first discovered in dealing with OpenXml and it seems the root cause is a bug in `System.IO.Packaging`.

**Description**

Using `System.IO.Packaging` to purely open and save a file (without any manipulation) causes a corrupt zip package. 7-Zip says there is a CRC error:
![image](https://user-images.githubusercontent.com/145854/41293044-8ac0c11e-6e54-11e8-9a62-9a822e693314.png)

This subsequently means that Excel 2013 complains that the `xlsx` file is corrupt.

Note that the file contains custom property parts, some of which are of 0 lengths. I don't have control of those parts.

This problem occurs *only* when using .NET Core, *not with .NET Framework*.

**Information**

- .NET Target: .NET Core 2.0
- System.IO.Packaging Version: v.4.5.0

**Repro**

```csharp
using System;
using System.IO;
using System.IO.Packaging;

namespace OpenXMLCustomPropertyPackagingProblemCore
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            File.Copy("test.xlsx", "file_to_open.xlsx", true);
            using (var package = Package.Open("file_to_open.xlsx", FileMode.Open))
            {
            }

            Console.WriteLine("Done.");
            Console.ReadKey(false);
        }
    }
}
``` 
Files 
- [test.xlsx](https://github.com/dotnet/corefx/files/2094171/test.xlsx)
- [file_to_open.xlsx](https://github.com/dotnet/corefx/files/2094173/file_to_open.xlsx) (produced by running the code)

MD5 hashes:
```
94db2b0108899c032526987091eaea6f *file_to_open.xlsx
ac39d841fc15384c252c4870063f9b54 *test.xlsx
```

**Comment by twsouthwick** [comment]
@ianhays The zip implementation used by System.IO.Packaging in .NET Core is the `System.IO.Compression` class, while in .NET Framework it has its own implementation.

**Comment by ianhays** [comment]
cc: @ViktorHofer

**Comment by igitur** [comment]
Sorry to be the guy who does unnecessary poking, but has anyone perhaps started looking at this?

**Comment by ViktorHofer** [comment]
cc @ahsonkhan

**Comment by orobert91** [comment]
I would also like to know what is the ETA for this bug fix. It is a blocking issue with no workaround. It breaks the Open-XML SDK and prevents us from modifying Excel files in .NET Core.

**Comment by jimdemis** [comment]
@igitur can you tell please, how the original test.xlsx was made? I would like to remake it by myself.

**Comment by igitur** [comment]
@jimdemis We have an in-house Excel plugin that stores custom properties concerning worksheet ranges in the `customProperty2.bin` file. I'm unable to give you the code that reproduces that. But in the case where nothing has to be stored, it leads to a `.bin` file with length of 0. And this seems to make `System.IO.Packaging` or `System.IO.Compression` choke and leads to a corrupt package.

**Comment by jimdemis** [comment]
@igitur Thank you for your prompt reply! I tested the `System.IO.Packaging.Package` with 0 length files and it was working as expected. I recompressed your test.xlsx and rebuilt it with excel and again it was working.
I believe that your issue is somehow related to how your plugin compresses the .xlsx.
I would suggest you check your in-house plugin to confirm it. (You can simply unzip and zip the xlsx file for example or maybe change the library used for compression).

**Comment by igitur** [comment]
@jimdemis I think you misunderstood. Our plugin is a regular Excel plugin that sets custom workbook properties. Our plugin does not save the package at all. That happens in the usual way when the user saves the Excel file. Note that when the user saves the file, the `.xlsx` package is valid with *no CRC errors*. Only after touching it with `System.IO.Packaging` does it become corrupt. My steps to reproduce illustrate it.

**Comment by jimdemis** [comment]
@igitur I believe that there is a possibility that the file it produces has somehow corrupt compression. It doesn't matter if it actually opens in Excel. But if the saving happens directly from the Excel itself (without third-party software), please tell me its version or maybe try more recent one. I checked your file with two versions of Excel and it works perfectly 
[test-excel2016.xlsx](https://github.com/dotnet/corefx/files/3098689/test-excel2016.xlsx).
My point is that if the zip file (test.xlsx) is somehow corrupted, `System.IO.Packaging.Package` should probably throw an error and not mess with it by making things worse.

**Comment by igitur** [comment]
`test.xlsx` isn't corrupt. There are no CRC errors. All zip clients can open it. All versions of Excel can open it. 

`file_to_open.xlsx` is the file that becomes corrupt after the NET Core version of Packaging touches it. NET Framework's implementation doesn't corrupt it.

This is not an issue about the validity of the input file.

**Comment by orobert91** [comment]
The Excel file passes the validation from DocumentFormat.OpenXml.Validation, this is a bug in System.IO.Packaging.Package, not a problem with the input file. We have the same problem.

**Comment by jimdemis** [comment]
A workaround to not break the xlsx is to get stream for each package part:
```csharp
            using (var package = Package.Open("file_to_open.xlsx", FileMode.Open))
            {
                foreach (var p in package.GetParts())
                    using (var s = p.GetStream()) { }
            }
```
/cc @igitur @orobert91

**Comment by jimdemis** [comment]
Can i have this issue assigned and the label changed to `area-System.IO.Compression` please? /cc @karelz @stephentoub @joshfree

**Comment by jimdemis** [comment]
> The Excel file passes the validation from `DocumentFormat.OpenXml.Validation`, this is a bug in `System.IO.Packaging.Package`, not a problem with the input file. We have the same problem.

@orobert91 it passes the validation because it ignores compression headers in the provided file that are not expected. Recompressing the file will fix the issue. And since you have the same problem, maybe you can tell me how i can produce this file by myself?

**Comment by danmosemsft** [comment]
Cc @ericstj

**Comment by orobert91** [comment]
@jimdemis You can't. The xlsx file is generated by jsReport library and I have no control over it. But given that every other zip clients and compression libraries (including .NET Framework) handle the file correctly, and given it passes all CRC validations, System.IO.Packaging.Package should also handle it correctly.
