### ISSUE TITLE
Allocation-free reversed find for `List<T>`s & `Array`s

### ISSUE THREAD

**Issue by LYP951018** [dotnet/corefx#30314]
## Rationale and Usage

Er... reversed finding is useful. For example, implementing the partition algorithm:

```csharp
int start = 0, end = list.Count - 1;
while (true)
{
    start = list.FindIndex(start, i => !pred(i));
    if (start == -1) return;
    end = list.ReversedFindIndex(end, pred);
    if (end == -1) return;
    if (start >= end) break;
    var temp = list[start];
    list[start] = list[end];
    list[end] = temp;
}          
```

By now, we could only use `.Reverse().Find()`, which will allocate an internal buffer.

## Proposed API

```csharp
public class List<T>
{
    public int ReversedFindIndex(int startIndex, Predicate<T> pred);
    public int ReversedFindIndex(Predicate<T> pred);
}
```

## Open Questions
 Could we improve `System.Linq.Enumerable.Reverse` implementation for `List<T>` and `Array`?

## Pull Request

On the way...

**Comment by mikedn** [comment]
It seems that you've reinvented `FindLastIndex`. Though it's not clear because the example usage seems to conflict with the `.Reverse().Find()` you've presented as an alternative.

**Comment by LYP951018** [comment]
@mikedn It seems that `FindLastIndex` searches from the first element, which `ReversedFindIndex` searches from the last element. `Reverse().Find()` has performance issues (memory allocation and massive virtual function calls.)
