### ISSUE TITLE
Support for serializing types as primitives

### ISSUE THREAD

**Issue by petroemil** [dotnet/corefx#30315]
In my code I'm trying to use "strongly typed primitives" to avoid having method signatures with just a bunch of primitive arguments that are too easy to mix up. If I have currencies, I prefer to wrap a decimal in a struct with the name of USD, EUR, GBP, etc. so I won't accidentally assign them to each other. I do similar things for IDs too. If I would happen to work with lots of strings (filling in a form), I'd probably want to have method signatures with things like Name, Email, Address, etc. so my code wouldn't be just full of strings but something slightly more strongly typed. 

But at the same time, these "strongly typed primitives" are really just there for the compiler, when I serialize these objects I want to have their primitive representation.

Expectation:
```json
{
    "Property": 42
}
```

Reality:
```json
{
    "Property":
    {
        "Value": 42
    }
}
```

Of course I know I can write converters to whatever serializer I'm using, be it ASP.NET model binding, Entity Framework converter, Dapper, JSON, XML, ProtoBuf, MessagePack and the list could go on for a while...

I don't know from a framework design perspective what would be the ideal solution for this.
I could imagine an attribute, something like `[SerializableAs(typeof(int))]` with either implicit or explicit casting operators implemented for conversion, or maybe an interface, like `ISerializableAs<T>` with the corresponding serialize/deserialize methods converting your object to and from the specified T type.

The point is, I think we should have some simple way to express this in the common `System.Runtime.Serialization` namespace, something that any serializer engine can take into account and can work seamlessly.

And maybe as a next step, there could be a C# language feature to make it very easy to define such "aliases" for primitive types, something like `public USD of decimal;`, instead of having to implement a wrapping struct around a `decimal` and reimplement all the operators on it.

**Comment by petroemil** [comment]
Probably the simplest thing I could imagine is something similar we can do with `ISerializable`, but in a more strongly typed way with something like an `ISerializableAs<T>` interface.

This is how a very simple `ISerializable` implementation looks like, with the interface method and the expected special constructor...
```csharp
public struct USD : ISerializable
{
    private readonly decimal value;

    public USD(decimal value) 
        => this.value = value;

    public USD(SerializationInfo info, StreamingContext context) 
        => this.value = info.GetDecimal("usd");

    public void GetObjectData(SerializationInfo info, StreamingContext context) 
        => info.AddValue("usd", this.value);
}
```

And this is how I would imagine the more strongly typed version of the interface:
```csharp
public struct USD : ISerializableAs<decimal>
{
    private readonly decimal value;

    public USD(decimal value)
        => this.value = value;

    public decimal ConvertToPrimitive()
        => this.value;
}
```

It's not really a serialization, more of a conversion or parsing, so probably the name `ISerializableAs` might not the best choice.

It would make it really easy to do what I described in the starting post, having "strongly typed primitives" as part of our domain models without any hassle around serialization, but also things like serializing a Color object as a hexadecimal string (`Green` -> `#00FF00`).

**Comment by StephenBonikowsky** [comment]
XmlTextAttribute will treat any types you attribute with it as text strings.
Adding new functionality to convert objects from strongly typed primitives to their primitive representation and vice versa would be a really low priority feature request.

https://docs.microsoft.com/en-us/dotnet/api/system.xml.serialization.xmltextattribute?view=netcore-3.0
