### ISSUE TITLE
Mono-specific files in corefx

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#30319]
There are some files in the corefx repo (outside of the corelib shared folder) that Mono is using but that aren't referenced / built / tested / etc. by anything in corefx.  These easily go stale or are even accidentally removed, and we can't ask developers to continually check whether a given file might be used by mono when there's no indication of that in the corefx repo.  Ideally mono-specific functionality would simply live in the mono repo.

cc: @marek-safar

**Comment by stephentoub** [comment]
For reference, I'm referring to files like these:
https://github.com/dotnet/corefx/blob/afa69666e425d2b018a3105bbec08073f513aed1/src/System.Data.Common/src/System/Data/Common/DbProviderFactory.CreatePermission.cs
https://github.com/dotnet/corefx/blob/844415759d3f1525bf1f5d1bd79453c6aa8493f8/src/System.CodeDom/src/System/CodeDom/Compiler/CompilerResults.Evidence.cs

**Comment by marek-safar** [comment]
Where do you think we should draw the line? Are you worried about public API only or about implementation differences too? Mono for example has iOS(Mac) optimized implementation of MD5CryptoServiceProvider, support for reading Mac proxies, and few more. Should these move or not? Similarly our PAL implementation could be slightly different in few cases or support more targets where that code should be located?

**Comment by stephentoub** [comment]
> optimized implementation of MD5CryptoServiceProvider, support for reading Mac proxies

Both of those sound like things that would benefit everyone (though it's be interested in understanding how much better the MD5 implementation is and why we care about MD5 perf :). Sounds like they should come to corefx *and* be built for corefx. The latter in particular is a known gap in SocketsHttpHandler.

> Where do you think we should draw the line? Are you worried about public API only or about implementation differences too? 

My concern is primarily about stale files, bit rot, etc., e.g. I almost deleted a bunch of files Mono needed because nothing in corefx depended on them and there was zero indication the files weren't dead, and there have been several PRs this year reverting similiar mistakes. If we comment them or name them to say they are needed, it's then less likely we'd eventually clean up the cruft because we'd still have to do cross-repo analysis to determine what's needed or not.

In a world where everything is built with the source from corefx and where there is automation / tooling in corefx for such builds, I have no concerns, it makes sense for all that source to live in corefx.
