### ISSUE TITLE
Question: How to integrate IL code properly in a dotnet core C# project?

### ISSUE THREAD

**Issue by fredpointzero** [dotnet/corefx#30323]
Hi,

I want to implement some methods in my C# project directly with IL code.

While reading the implementation of System.Runtime.CompilerServices.Unsafe, I noticed that the actual implementation is using IL source file and class definition in C#, but I missed some steps.

I have two questions about this:

1. How do you get properly ilasm executable in a Visual Studio dotnet core app project?
So far, I downloaded the nuget package runtime.win-x64.Microsoft.NETCore.ILAsm manually, extracted ilasm.exe and copied the corresponding coreclr.dll in a folder.

This work but it is not a resilient way to get it.

2. What is the build pipeline to include the IL code?
I successfully created a dll assembly from my il source code file, but I do not know how to properly inject it in the C# project's dll.
In the corefx and buildtool repository, I found the MSBuild targets to build the IL source code into dll but not how the IL code is injected in the final assembly.

Best regards,

**Comment by omariom** [comment]
Have you seen [InlineIL.Fody](https://github.com/ltrzesniewski/InlineIL.Fody)?

**Comment by fredpointzero** [comment]
I didn't know such a tool existed, It is cool as it handle all of the plumbing required to edit assemblies.

So I'll take a look at it.

**Comment by fredpointzero** [comment]
I tried InlineIL.Fody and a custom solution to weave IL assemblies with raw IL files but InlineIL.Fody is more convenenient to use (and already update the debug info).

However, it is a bit difficult to debug when the IL code is incorrect. I am currently using Visual Studio's debugger with the asm view. Maybe you have some experience in debugging IL @omariom ?

**Comment by fredpointzero** [comment]
Actually, I found a faster pattern for what I wanted than writing custom IL code with calli. (I think it is not optimized by JIT).
