### ISSUE TITLE
Support W3C format in System.Net for distributed trace context propagation

### ISSUE THREAD

**Issue by SergeyKanzhelev** [dotnet/corefx#30332]
## Motivation
Support extraction and injection of distributed tracing context in a format of [W3C headers](https://github.com/w3c/distributed-tracing) for System.Net alongside `Request-Id`.

This issue depends on [tracestate collecton implementation](https://github.com/dotnet/corefx/issues/30331) in `Activity` class.

CC: @seth-capistron, @vancem, @jacpull, @lmolkova, @glennc, @davidfowl

**Comment by karelz** [comment]
@SergeyKanzhelev what do you expect will need to happen in System.Net for that? New APIs?

**Comment by lmolkova** [comment]
@karelz 

@SergeyKanzhelev means (correct me if I'm wrong) that HttpClient diagnostics instrumentation should be changed to support new standard:

https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs#L82

**Comment by davidsh** [comment]
These PRs #35880, #35882 address this issue.

cc: @lmolkova
