### ISSUE TITLE
Inconsistent behviour on AppDomain unload with pending tasks

### ISSUE THREAD

**Issue by poizan42** [dotnet/corefx#30345]
First consider this:

```CSharp
using System;
using System.IO.Pipes;
using System.Threading;

namespace AppDomainUnloadTest
{
  class Program
  {
    [Serializable]
    private class AppDomainTest
    {
      public string PipeHandle { get; set; }
      public async void Foo()
      {
        PipeStream stream = new AnonymousPipeClientStream(PipeDirection.In, PipeHandle);
        byte[] buffer = new byte[1];
        await stream.ReadAsync(buffer, 0, 1);
        Console.WriteLine(buffer[0]);
      }
    }

    static void Main(string[] args)
    {
      AppDomainTest appDomainTest = new AppDomainTest();
      var pipeServer = new AnonymousPipeServerStream(PipeDirection.Out);
      appDomainTest.PipeHandle = pipeServer.GetClientHandleAsString();
      AppDomain domain = AppDomain.CreateDomain("Testdomain");
      domain.DoCallBack(appDomainTest.Foo);
      Thread.Sleep(1000);
      AppDomain.Unload(domain);
    }
  }
}

```

This fails with System.CannotUnloadAppDomainException because the pipe is not asynchronous so internally it just does a synchronous wait from a threadpool. AppDomain.Unload makes no attempt at cancelling pending synchronous IO, so it ends up timing out.

Now if we instead use an asynchronous pipe:

```CSharp
using System;
using System.IO.Pipes;
using System.Threading;

namespace AppDomainUnloadTest2
{
  class Program
  {
    [Serializable]
    private class AppDomainTest
    {
      public string PipeName { get; set; }
      public async void Foo()
      {
        var stream = new NamedPipeClientStream(".", PipeName, PipeDirection.In, PipeOptions.Asynchronous);
        stream.Connect();
        byte[] buffer = new byte[1];
        await stream.ReadAsync(buffer, 0, 1);
        Console.WriteLine(buffer[0]);
      }
    }

    static void Main(string[] args)
    {
      string pipename = "foopipe" + Guid.NewGuid().ToString("N");
      AppDomainTest appDomainTest = new AppDomainTest();
      appDomainTest.PipeName = pipename;
      var pipeServer = new NamedPipeServerStream(pipename, PipeDirection.Out, 1, PipeTransmissionMode.Byte, PipeOptions.Asynchronous);
      pipeServer.BeginWaitForConnection(ar => { pipeServer.EndWaitForConnection(ar); }, null);
      AppDomain domain = AppDomain.CreateDomain("Testdomain");
      domain.DoCallBack(appDomainTest.Foo);
      Thread.Sleep(1000);
      AppDomain.Unload(domain);
    }
  }
}
```

This completes without any errors. Of course internally an IO completion port is used, so there is no pending synchronous IO that blocks any threads, so the AppDomain is just unloaded.

It seems quite pointless to wait for the IO to complete in the first case when the callback would never actually be called.

**Comment by jkotas** [comment]
In .NET Framework, AppDomain can unload only after no thread is executing in the AppDomain. If the execution is stuck in unmanaged method with the AppDomain code on the stack, the AppDomain cannot unload.

For anything even slightly more complex, you have to abort, close or dispose the operations in flight yourself before calling AppDomain unload in order for it to succeed. It is very bug prone and hard to get right. 

It is one of the reasons why we have decided to not support AppDomains in .NET Core.

**Comment by poizan42** [comment]
The problem here is not the behaviour of AppDomain.Unload per se, but that ReadAsync and WriteAsync on the streams acts differently with pending io on appdomain unload depending on whether the underlying native handle has been opened in asynchronous mode.

**Comment by jkotas** [comment]
If the handle is opened in synchronous mode, ReadAsync and WriteAsync have no other option but to convert to synchronous operation.

**Comment by poizan42** [comment]
They could cancel their own IO on appdomain unload, or some more general mechanism could be introduced to opt in to have CancelSynchronousIo called on you on appdomain unload during a P/Invoke call.
