### ISSUE TITLE
String class should use Span internally where appropriate

### ISSUE THREAD

**Issue by jjxtra** [dotnet/corefx#30340]
# Issue Title
String class should use Span class internally. Substring is a good example.

# General
Span class can now be used to pull out parts of strings, but this gives a collection of char. Not so helpful when dealing with API calls that still require strings (regex, etc.).

It would be awesome to have string methods use Span underneath, removing allocations where possible.

My apologies if I have missed something with the API and this has already been implemented.

**Comment by karelz** [comment]
I believe this already happened all across BCL (@stephentoub), incl. string.

**Comment by danmosemsft** [comment]
@jjxtra thanks for the issue. could you please give one or two examples of where you would improve string in this way? 

https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/String.cs

**Comment by jjxtra** [comment]
It's a different file, I found it.

https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/String.Manipulation.cs#L1625

Do you take pull requests?

**Comment by jjxtra** [comment]
@karelz Is it a different version of the code? I am looking at one example here, sub string internal which seems a great candidate: https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/String.Manipulation.cs#L1625

**Comment by stephentoub** [comment]
> You should be able to have a string use span as it's backing buffer, please correct me if I am wrong or missing something.

No, string is an object and lives on the heap; span is a ref-like type and can only live on the stack.  It's possible to refer to the contents of a string as a span, e.g. `string.AsSpan()`.

> Is there something magical about FastAllocateString

Yes, it is the internal runtime method for allocating a string, which is a special type.

> sub string internal which seems a great candidate

string.Substring is a public method that returns string; it can't be changed to return a span instead, and InternalSubstring is just a helper that Substring calls, returning its result, so changing it to return a span wouldn't be possible.

If you want no-allocation slicing of a string, you can treat it like a span with `AsSpan()` or with an implicit cast to `ReadOnlySpan<char>`, and then `Slice` that.

> Do you take pull requests?

Yes, but PRs for string should go to the dotnet/coreclr repo.

> I believe this already happened all across BCL, incl. string.

A ton of new APIs have been added across the BCL for working with spans, including for string, where methods exist to use a string as a `ReadOnlySpan<char>`, and with a bunch of extension methods on `ReadOnlySpan<char>` for doing string-like operations (e.g. Trim, IndexOf, etc.), as well as methods that accept `ReadOnlySpan<char>` that previously would have taken a string (e.g. int.Parse).  A bunch of implementations have also been updated to use spans where relevant.

If there's a place where span could be used to help further, please feel free to submit a PR.  In the meantime, I'm going to close this issue, as it's not particularly actionable in its current form.  Thanks for the interest, and we look forward to PRs.

**Comment by jjxtra** [comment]
Thanks for the response, I appreciate your time.
