### ISSUE TITLE
TcpTransportSecurity class doesn't have ProtectionLevel property

### ISSUE THREAD

**Issue by SteveL-MSFT** [dotnet/corefx#30343]
Porting some .Net Framework code to dotnetcore.  The TcpTransportSecurity class doesn't have ProtectionLevel property so I can't set it to EncryptAndSign.  What is the impact of not setting this?  Is it secure by default?

**Comment by davidsh** [comment]
Are you referring to this class:

[System.ServiceModel.TcpTransportSecurity](https://msdn.microsoft.com/en-us/library/system.servicemodel.tcptransportsecurity(v=vs.110).aspx) ?

I think all System.ServiceModel classes are in the [WCF repo](https://github.com/dotnet/wcf):

**Comment by karelz** [comment]
This issue was moved to dotnet/wcf#2944

**Comment by SteveL-MSFT** [comment]
Yes.  I'll open this in that repo.  Thanks.
