### ISSUE TITLE
The System.Numerics.Vector*.Clamp method does not follow its documented behavior

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#30356]
All three of the `Vector*.Clamp` methods are commented with the following:
```
// This compare order is very important!!!
// We must follow HLSL behavior in the case user specified min value is bigger than max value.
```

However, the implementation does not actually follow this behavior.

The implementation is effectively doing:
```
x = min(x, maxVal); // x = (x < maxVal) ? x : maxVal
x = max(x, minVal); // x = (x > minVal) ? x : minVal
```

While both GLSL and HLSL operate using:
```
x = max(x, minVal); // x = (x > minVal) ? x : minVal
x = min(x, maxVal); // x = (x < maxVal) ? x : maxVal
```

As you can see, the order of the max/min comparisons is reversed.

You can observe the actual behavior of `clamp` in GLSL and HLSL by writing your own shader and disassembling, looking at the documentation (https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/clamp.xhtml), or by using the "Shader Playground" (http://shader-playground.timjones.io/6ca74f2b5a91fac3a0e4524ca696d091).

**Comment by tannergooding** [comment]
CC. @eerhardt.

@mellinoe might be interested in commenting on this as well.

**Comment by shawnhar** [comment]
I can't find historical details on this, but suspect the comment is just incorrect.  The unit tests do validate behavior of inverted min/max, so this was obviously thought through at some point during development.

**Comment by tannergooding** [comment]
@shawnhar, is it also just possible that the comment was meant to be correct and that the tests/implementation were incorrectly written?

The HLSL documentation isn't exactly "clear" on the implementation and you have to do some digging to find out the correct behavior. So I think it would be completely plausible that it was just implemented incorrectly.

**Comment by shawnhar** [comment]
Possibly - but after 10+ years of an implementation which matches its tests (and we know the implementation has not changed because the tests do exercise this path) I think the current behavior has become a de-facto standard whatever the original intent was.
