### ISSUE TITLE
System.Security.Cryptography.Pkcs netstandard contract (4.5.0) is not netfx-compatible

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#30359]
The addition of CmsSigner in the contract updates with .NET Core 2.1 added three property setters which are not present in .NET Framework.

It was not intended to forcibly add these members, rather a tooling misalignment prevented the build failure that was expected for the contract deviation.

Running ApiCompat manually to compare the netfx implementation to the netstandard contract produces

> Compat issues with assembly System.Security.Cryptography.Pkcs:
MembersMustExist : Member 'System.Security.Cryptography.Pkcs.CmsSigner.Certificates.set(System.Security.Cryptography.X509Certificates.X509Certificate2Collection)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.Pkcs.CmsSigner.SignedAttributes.set(System.Security.Cryptography.CryptographicAttributeObjectCollection)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.Pkcs.CmsSigner.UnsignedAttributes.set(System.Security.Cryptography.CryptographicAttributeObjectCollection)' does not exist in the implementation but it does exist in the contract.
Total Issues: 3

**Comment by bartonjs** [comment]
This was fixed in master by #30233

**Comment by karelz** [comment]
Fixed in release/2.1 branch in PR #30361. Will be part of 2.1.3 release.
