### ISSUE TITLE
How do we detect memory leaks in.Net core and asp.net core?

### ISSUE THREAD

**Issue by rocketRobin** [dotnet/corefx#30352]
In my asp.net core 2 application, I always find that there is a constant increase in the inside, or even the GC memory will continue to rise. What tools can analyze memory leaks?

**Comment by karelz** [comment]
Any profiler typically can do memory leak analysis - e.g. VS Profiler, PerfView (expert tool) and probably a few external tools.

**Comment by rocketRobin** [comment]
Thank you very much!
