### ISSUE TITLE
System.Dynamic.Runtime tests should probably move to under Microsoft.CSharp

### ISSUE THREAD

**Issue by VSadov** [dotnet/corefx#3035]
What we have currently under System.Dynamic.Runtime\tests are mostly tests for C# dynamic. While they do provide coverage for System.Dynamic, they target various language features and only indirectly target DLR machinery.

This is confusing. (see, for example, discussion in https://github.com/dotnet/corefx/pull/2941)

Tests that target and require C# dynamic should go to under Microsoft.CSharp.

If there are any tests that directly targets DLR and do not require C# dynamic, they can remain under System.Dynamic.Runtime.

**Comment by karelz** [comment]
@VSadov says close it. It's better for the tests to live in Dynamic.Runtime which is changing more than MSCSharp.
