### ISSUE TITLE
How to test System.Management usage?

### ISSUE THREAD

**Issue by Laureian** [dotnet/corefx#30353]
Hi,
I have application for administering domain machines using ActiveDirectory together with WMI. I'm thinking about some kind of integration tests. Maybe you have some thoughts on how to:
1. Create Active Directory structure with the automated task for testing purposes. I mean for example some kind of script that automatically creates virtual machines with AD structure.
2. How to mock specified machine/virtual machine to test specified environments conditions like hardware devices.

Maybe use Azure Virtual Machines there? Maybe it's no sense to try to automate System.Management and I should set real Active Directory with physical machines?

**Comment by danmosemsft** [comment]
@tarekgh maybe it would be helpful to briefly describe what you did to test DirectoryServices?

**Comment by tarekgh** [comment]
Currently for DirectoryServices we run the tests on demand and not as part of running test suites. you may look at the file https://github.com/dotnet/corefx/blob/master/src/System.DirectoryServices/tests/LDAP.Configuration.xml which users can supply the needed server info there and then can run the test against such server. and we have open issue https://github.com/dotnet/core-eng/issues/2096 to get this test run on Helix too.

**Comment by pjanotti** [comment]
@Laureian I'm closing this one let us know if you still has some Q in this regard.
