### ISSUE TITLE
Add more Compression tests zips

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#30368]
We should add some more compression test zips of the following classes:
- More weird zips
- Large zips, or at least zips that extract large so we test buffer boundaries
- zips with lots of files with a particular pattern to test filtering on those entries

**Comment by wgebczyk** [comment]
Hi,
I would like to pick up this issue and solve it. I have a few questions:
1. By "more compression test zips" you mean more physical files being added to test proj OR anyway of specifying such various input files?
2. I would assume the work in area of "$\src\System.IO.Compression" - not the Brotli part
3. What is the intention on adding "more weird zips" - improve coverage of existing code or fuzz testing-like checks?
4. The "zips that extract large" suggest crafting input to force working around boundaries in code
5. "zip with lots of files" - in what sense testing patters? I would assume that you would like to have big ZipArchive and use some random access test (accessing subset of entries by some pattern)?

**Comment by wgebczyk** [comment]
@joshfree … so maybe you could elaborate more on that thing... or close is as no longer relevant?

**Comment by joshfree** [comment]
@ianhays could you share more specifics on what you had in mind?  @wgebczyk my intention for this tracking issue is to add more test zips to the existing https://github.com/dotnet/corefx-testdata/tree/master/System.IO.Compression.TestData project to test round-trip interoperability with common compression tools, at least one very large zip to test upper limits, and manually malformed zip archives to validate correctness.  Lastly, I'd prefer it greatly if we didn't check-in raw binaries to dotnet/corefx-testdata but instead checked-in the build scripts to produce said assets above.

@ianhays is there anything else that I missed?

Thanks

**Comment by wgebczyk** [comment]
@joshfree Well, that aligns nice with my thinking -- to create a tool that will generate problematic zip files that would trigger boundary conditions (like buffer sizes =/+/- 1 - etc). Then I will start investigation. Thanks!

**Comment by ianhays** [comment]
> my intention for this tracking issue is to add more test zips to the existing https://github.com/dotnet/corefx-testdata/tree/master/System.IO.Compression.TestData project to test round-trip interoperability with common compression tools,

This is my intention as well.

> at least one very large zip to test upper limits, and manually malformed zip archives to validate correctness. 

Yes, we need those two things. In particular, the malformed zips are important as our current test zips for edge case scenarios are more limited than I would like. It would also be good to add more zips that contain weird (i.e. unusual, manually tweaked, potentially invalid) paths.

> Lastly, I'd prefer it greatly if we didn't check-in raw binaries to dotnet/corefx-testdata but instead checked-in the build scripts to produce said assets above.

This would be great, but in my experience it's far more effort than it's worth to write scripts to produce them compared to opening up the zip in a hex editor and messing with the exact values that need to be changed. Not that it can't be done because it definitely can, but we'll need to be careful to produce the zips in such a way that their binary values are fixed and not dependent on the .net zipper. The existing checked-in zips were all tested for their interoperability with other zip programs e.g. windows explorer, 7zip, unix info-zip, and we'll want to be positive that we don't accidentally break that interoperability.

**Comment by carlossanlop** [comment]
Triage:
The request is not concrete enough, but @buyaa-n has added interesting edge cases already since this issue was opened.
