### ISSUE TITLE
[WebSocket] ReceiveAsyncPrivate cannot make sure TryParseMessageHeaderFromReceiveBuffer always valid to run

### ISSUE THREAD

**Issue by litszh** [dotnet/corefx#30375]
Encounter an exception in server side of Websocket.

"error": "System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.ArgumentException: Destination array is not long enough to copy all the items in the collection. Check array index and length.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.BitConverter.ToInt32(Byte[] value, Int32 startIndex)
   at System.Net.WebSockets.ManagedWebSocket.TryParseMessageHeaderFromReceiveBuffer(MessageHeader& resultHeader)
   at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__61.MoveNext()
   at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.ManagedWebSocket.<CloseAsyncPrivate>d__67.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at System.Net.WebSockets.WebSocketSafe.<CloseAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Did some investigation. Seems the the ReceiveAsyncPrivate method failed to ensure there are enough bytes in buffer before calling TryParseMessageHeaderFromReceiveBuffer
Code in 
https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L649

In that case if the buffer is not long enough sometime, it will through the exception("Destination array is not long enough...") here
https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L986
```
            if (masked)
            {
                if (!_isServer)
                {
                    shouldFail = true;
                }
// Will through exception here if the receiverBuffer length is less then 4 bytes. (Which is possible).
                header.Mask = CombineMaskBytes(receiveBufferSpan, _receiveBufferOffset); 

                // Consume the mask bytes
                ConsumeFromBuffer(4);
            }
```

**Comment by stephentoub** [comment]
Can you share a small repro?

**Comment by stephentoub** [comment]
Also, what version are you using? It looks like it's older than 2.1?

**Comment by litszh** [comment]
About this line
if (_receiveBufferCount < (**_isServer ? (MaxMessageHeaderLength - MaskLength**) : MaxMessageHeaderLength))

Consider this situation:
_isServer == true;
MaxMessageHeaderLength = 14;
MaxLength = 4;
And if in somecase, the _receiveBufferCount == 11
And the payloadLength = 127.
It will skip the EnsureBufferContainsAsync checking and directly goes to TryParseMessageHeaderFromReceiveBuffer. And in the function, it will read 10 bytes, then goes to CombineMaskBytes, will read another 4, but not enough data left... then there will be an exception.

https://github.com/dotnet/corefx/blob/7c8df77ff6ae44b76ac35a2ac8db85df081724b9/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L628

**Comment by stephentoub** [comment]
Thanks.  From a quick glance at the code, the problem would appear to be that the if/else branches here are reversed:
https://github.com/dotnet/corefx/blob/824af7f2ba689479767cddc33741cf030650d47e/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L628
The client sends a mask to the server, so the server should expect a 14 byte header, not a 10 byte header, and the server doesn't send a mask to the client, so the client should expect a 10 byte header, not a 14 byte header.

**Comment by stephentoub** [comment]
cc: @anurse, FYI, as my guess is this only affects server-side usage, since worst case on the client is it does a bit more work than it needs to sometimes but wouldn't fail as a result.

**Comment by litszh** [comment]
The consequence of this bug is:
If the websocket sends by setting mask =1. 
1. Sometimes server will throw the exception.
2. Or the server will use wrong maskKey(If payloadLength < 127),

**Comment by stephentoub** [comment]
> If the websocket sends by setting mask =1

Which is the case for the client sending to the server.  If the server sent that to the client, that would be a buggy server.

**Comment by stephentoub** [comment]
> The consequence of this bug is:

It's certainly a bug, but it should be relatively rare, as it requires that when the websocket issues a read, it gets back a partial header.

**Comment by stephentoub** [comment]
@litszh, what version are you using?  2.0?  It doesn't look like 2.1.

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/corefx/pull/30407
