### ISSUE TITLE
Modify signature of Unsafe.AreSame()

### ISSUE THREAD

**Issue by SWB2** [dotnet/corefx#30380]
The current signature of [Unsafe.AreSame()](https://github.com/dotnet/corefx/blob/0f6f5ea8f08dc7e033b4bf998f54e6e731f3bfa1/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.il#L412-L420) is:

    .method public hidebysig static bool AreSame<T>(!!T& left, !!T& right) cil managed aggressiveinlining

This requires that the arguments `left` and `right` are known to be of the same type at compile time.

Would it be possible to change the signature (or add an overload) to:

    .method public hidebysig static bool AreSame<T1, T2>(!!T1& left, !!T2& right) cil managed aggressiveinlining

This would allow usage in scenarios where the arguments are _not_ known to be of the same type at compile time. The body of the method requires no changes to support this.

**Comment by jkotas** [comment]
`ref TTo As<TFrom, TTo>(ref TFrom source)` can be used to cast the other argument to the same type to allow this scenario.

Do you have a good real-world example where this overload would be a significant improvement?

The downside of adding this overload is that the cases where mismatched argument types are bugs would be left undetected at compile time. We are using `Unsafe.AreSame` in many places in corefx itself and never really run into a problem with mismatched argument types (except a few tests).

**Comment by SWB2** [comment]
You know, I was _sure_ that I tried that and it didn't work in my scenario. I just tried it again, though, and it did. Not sure what I did wrong the first time.

Yes, that will work fine. Sorry for the false alarm.
