### ISSUE TITLE
Behavioral change in SocketsHttpHandler - no automatic redirection for 308 Permanent Redirect

### ISSUE THREAD

**Issue by tpeczek** [dotnet/corefx#30389]
The older (pre 2.1.0) `HttpClientHandler` performs automatic redirection for *308 Permanent Redirect*. Unfortunately the `GetUriForRedirect` method of `RedirectHandler` which is being used by `SocketsHttpHandler` doesn't support this status code.

https://github.com/dotnet/corefx/blob/c6efb248fd3c633e09733b2c9514d5729577a701/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs#L88-L99

Currently the only way to have automatic redirection for *308 Permanent Redirect* is to configure a process to use the older `HttpClientHandler` (`AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false)`).

**Comment by rmkerr** [comment]
I was able to repro this on my machine. The fix looks simple, but we should definitely add a test for this case.

**Comment by rmkerr** [comment]
It looks like the HttpStatusCode enum was only recently updated to include HTTP 308, via PR #26727. With the platform handlers we support whatever cURL and WinHttp support, so 308s do actually work (at least on new versions).

Testing will hopefully show whether or not we have issues with any older platforms, but either way I think we should enable this behavior in `SocketsHttpHandler` and add testing on supported platforms. I've added tests locally and will hopefully see those fail now and then pass with the fix.

**Comment by karelz** [comment]
It looks like something we should consider for 2.1.x - it is a regression.

**Comment by danmosemsft** [comment]
@karelz if your team wants to propose a fix in servicing, we need a fix in master, PR prepped, mail to shiproom, etc.

**Comment by karelz** [comment]
@danmosemsft yep, we're working on it ... we will see if we can make it for 2.1.3.

**Comment by karelz** [comment]
Fixed in 2.1 servicing in PR #30954. Should be part of 2.1.3 release.

**Comment by karelz** [comment]
@wtgodbe can you please confirm that it made it into 2.1.3 build?

**Comment by wtgodbe** [comment]
The most recent non-stable build was on 7/10, against this commit: https://github.com/dotnet/corefx/commit/2185b5512232ace2e60b44b6789b5e8a8320fe98. This means that this change was not in that build. However, the final build is scheduled for 7/16, so this should make it into the actual release.
