### ISSUE TITLE
Investigate commented out System.Composition tests

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/corefx#3039]
There are some commented out tests [in ConventionBuilderTests.cs](https://github.com/dotnet/corefx/blob/64f6923889f97bf2d95ffce0a0ff9f456a5bb439/src/System.Composition.Convention/tests/ConventionBuilderTests.cs#L141).  We should investigate these and either enable them or delete the commented out code.

**Comment by Maxwe11** [comment]
That tests depends on types which not present in .NET Core:
- CompositionContainer
- RegistrationBuilder
- TypeCatalog
