### ISSUE TITLE
Add back Marshal.IsTypeVisibleFromCom

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#30393]
I've encountered this in a number of places in Desktop code and cannot come up with a reasonable workaround to port the behavior.  Given we still support COM interop on Windows and are investing more in that space we should bring this back.

We still have the implementation in CoreCLR we just need to expose it:
https://github.com/dotnet/coreclr/blob/46ab1d132c9ad471d79afa20c188c2f9c85e5f20/src/vm/marshalnative.cpp#L1523

/cc @luqunl

**Comment by ericstj** [comment]
As a (hack) workaround I did the following, which calls IsTypeVisibleFromCom behind the scenes.
```
        public static bool IsTypeVisibleFromCom(Type type)
        {
            try
            {
                int unused = Marshal.GetStartComSlot(type);
            }
            catch (ArgumentException)
            {
                if (type == null)
                {
                    throw;
                }
                return false;
            }
            return true;
        }
```

**Comment by danmosemsft** [comment]
There's quite a bit of Marshal missing as seen in 
https://github.com/dotnet/corefx/blob/master/src/shims/ApiCompatBaseline.netcoreapp.netfx461.ignore.txt#L2595-L2619

It's not necessarily with good reason eg we have `Marshal.GetStartComSlot(Type t)` but not `Marshal.GetEndComSlot(Type t)`. In fact most of them look portable - if we still have the native implementation and want to.

**Comment by luqunl** [comment]
> Marshal.GetStartComSlot(Type t) but not Marshal.GetEndComSlot(Type t)

Agree. We should either support both  or not support both..

> IsTypeVisibleFromCom
We should add support.

>There's quite a bit of Marshal missing as seen in
https://github.com/dotnet/corefx/blob/master/src/shims/ApiCompatBaseline.netcoreapp.netfx461.ignore.txt#L2595-L2619

I don't want to add these TypeLib related APIs.

**Comment by jkotas** [comment]
> I am not sure what's right behavior for .NetCore

IsTypeVisibleFromCom is used internally by the COM interop subsystem. This API is just exposing the value publicly.

If we were to change the rules for how COM visibility is computed in .NET Core, it should be looked at as separate issue. (I do not think we have a good reason to change the rules.)

> I don't want to add these TypeLib related APIs.

Agree. Let's add only what we know is a real problem or clear inconsistency:  IsTypeVisibleFromCom and GetEndComSlot.

**Comment by danmosemsft** [comment]
@luqunl there is no need to review the API if it was already exposed in .NET Framework. That tag is for proposed new API, to review their shape, value etc. Do you plan to take these or is it up for grabs?

**Comment by danmosemsft** [comment]
@luqunl what is the status of this one, do you plan to do it?

**Comment by luqunl** [comment]
@danmosemsft , working on it.
