### ISSUE TITLE
Regex should provide a validation method

### ISSUE THREAD

**Issue by ashmind** [dotnet/corefx#304]
`Regex` doesn't provide a way to validate whether a given string is a valid regular expression without getting an exception. It should provide one.

## Background

`TryParse` is a common pattern in .NET which is useful when a potentially invalid string has to be converted to a different representation. As invalid user input is not an exceptional situation, it makes sense to avoid exception overhead (which coincidentally also educates new developers to handle those situations correctly).

Regular expressions are not as common in external input as `int` or `DateTime`, however there are situations when regex is an appropriate tool for the power users (e.g. advanced text editor search/replace). If you want to validate the regex as it is being typed (with reasonable throttling), it is useful to have as little overhead as possible.

Request for Regex.TryParse (not by me) had [5 votes on Microsoft Connect](http://webcache.googleusercontent.com/search?q=cache:KV6wcz2SJ44J:https://connect.microsoft.com/VisualStudio/feedback/details/331753/regex-should-have-a-static-tryparse-method+) and currently exists on [UserVoice with 3 votes](http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/2683916-regex-should-have-a-static-tryparse-method).

## Design Options

Originally I wanted to propose `Regex.TryCreate` (which is in line with `Uri.TryCreate` since `Regex` does no have a `Parse` method). However even for power users regexes might not be easy to write, and providing more information than just "you have failed" is useful.

I can't think of any existing pattern in the BCL that fits this well, but basically something like this would be useful:
```csharp
public class Regex {
    // existing members…
    public static RegexParseResult Parse(string pattern);
    public static RegexParseResult Parse(string pattern, RegexOptions options);
    // or alternatively we could use a default value for options
}

public class RegexParseResult {
    public bool IsSuccess { get; }
    public Regex Regex { get; }
    // parser doesn't have to provide more than one, however it would allow it to do so in the future
    public IReadOnlyCollection<RegexParseError> Errors { get; }
}

public class RegexParseError {
    public string Message { get; }
    public int Start { get; }
    public int End { get; }
}
```

### API Concerns 

It would be useful to know if I am missing some existing common pattern here, so that consistency with other BCL APIs can be provided. I don't like using name `Parse` here either as it invites confusion -- however I can't currently think of a better approach.

## Example Usage

```csharp
public class RegexValidationRule : System.Windows.Controls.ValidationRule {
    public override ValidationResult Validate(object value, CultureInfo cultureInfo) {
        var valueString = (string)value;
        var parseResult = Regex.Parse(valueString);
        if (!parseResult.IsSuccess) {
            var errorString = string.Join(NewLine, parseResult.Errors.Select(e => $"{e.Message} at {e.Start}"));
            return new ValidationResult(false, errorString);
        }

        return ValidationResult.ValidResult;
    }
}
```

## Compatibility

I think adding a new static method should be safe enough.

**Comment by sharwell** [comment]
Overall this is an interesting suggestion, and I'm actually torn on it. Since it will likely be a fairly complex task to implement the expression parsing without any exceptions, I think I would be in favor of the following:

1. I would be :+1: on implementing a `TryCreate` or similar method(s) in the manner suggested by @ashmind (using a list of 0 or more error messages/locations).
2. I would be :expressionless: on implementing the methods using a simple `bool` response, since I don't know of any case where regular expression parse exceptions resulted in a performance loss that wasn't easily avoided (e.g. by caching).
3. I would be :-1: on exposing the AST. This would be a large API surface to maintain, infrequently used, and likely to interfere with other priorities like those in #340.

**Comment by terrajobst** [comment]
[We've reviewed this proposal](https://github.com/dotnet/apireviews/blob/master/2015-01-14-misc/README.md#304-regex-should-provide-a-validation-method) and declined it in the current form.

This proposal should be split into:

* P1: We currently throw an `ArgumentException` for parse errors and we agree we should try to at least add more information like the character index. We should consider adding a `RegexParseException` that inherits from `ArgumentException`
* P2: We could add a `TryParse` that avoids throwing exceptions if the parsing fails.

**Comment by AdamSpeight2008** [comment]
For an example an roslyn analyser that improves on the existing error messages.
[String Format Diagnostic](https://stringformatdiagnostic.codeplex.com/)

**Comment by ashmind** [comment]
@terrajobst Thanks for the detailed reply with the video — it's nice to see an open design process for BCL features.

I do have a concern though — it didn't seem like people in the discussion had read the proposal in full (or maybe I didn't write it clear enough).

E.g. I write there that a collection of errors is just future-proofing, but people read it as a requirement for recovery. Also a lot of discussion was about Roslyn-level parsing, for which my proposal is not appropriate at all — however I haven't noticed any discussion of the actual use case I provided (maybe I missed it?).

And a clarification question. In the split, what's the difference between P2 and my proposal? Do you suggest not returning the error message in `TryParse`?

**Comment by JamesNK** [comment]
The difference is TryParse would return bool with no additional details, similar to TryParse on Int32/Boolean/etc.

My 2 cents is if .NET adds an API to give more detailed information about regex parsing then a static helper method on Regex isn't the place for it.

**Comment by jjxtra** [comment]
So writing your own extension with a try/catch on 'new Regex(...)' is still the best way?
