### ISSUE TITLE
Cursor position response sequence code got interpreted as normal user input

### ISSUE THREAD

**Issue by jianyunt** [dotnet/corefx#30406]
Background
-------------
In PowerShell Core (pwsh) on `Linux`, using terminal to connect to it or Azure CloudShell (bash-Linux), we are on or off hiting timeout in the [position handling code](https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System/ConsolePal.Unix.cs#L361).  This problem mostly occurs on slow network, Azure service slow responses, or pwsh is too busy in processing its background jobs.  

As a result,
-  the position response sequence code got interpreted as normal user input, PowerShell cmdlet, in this case. This can be embarrassing while standing on stages for doing demos.
- the cursor position is not correct after timed out. Shown below.

![image](https://user-images.githubusercontent.com/10171679/41443207-5b31e584-6ff0-11e8-8440-6d6fe7765fac.png)

Initial Investigation
--------------------
Just for trying it out, After I changed [this line](https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System/ConsolePal.Unix.cs#L361) to Interop.Sys.InitializeConsoleBeforeRead(`minChars: 1`, decisecondsTimeout: 10);  I do not see these response code on the screen anymore.  According to https://linux.die.net/man/3/tcsetattr,  I am waiting for the first byte to be ready and then the timer starts. However I am not sure this change can potentially  cause other effect though.

Ask
----
Can we make the timeout and minChars configurable?

Repro
------
0. Simulate slow network. I used Fiddler, Rules-> Performance-> Simulate Modern Speeds, and launch chrome from the Fiddler.
1. https://portal.azure.com/
2. Click on cloudshell button to launch Azure CloudShell
3. In Bash, type pwsh
4. Run some commands, let's say Get-AzureRmVM

**Comment by karelz** [comment]
@wtgodbe @wfurt @stephentoub any opinions?

**Comment by wfurt** [comment]
is pwsh running over some kind of TCP socket? If so, do you have Nagle enabled or disabled? 
In general, the sequences are finicky. Also you get the fist part of sequence before running pwsh.
What terminal do you set when connected? You can always set TERM=dubm and there will be no sequences.

**Comment by jianyunt** [comment]
@wfurt CloudShell is using xterm.js, running over Websocket. We are using TERM=xterm-256color, Linux VERSION="16.04.4 LTS (Xenial Xerus)"

TERM=dubm does not seem to be supported in our environment. Here are our options.
![image](https://user-images.githubusercontent.com/10171679/41481447-d2625a08-7086-11e8-97f6-65039e463cb5.png)

**Comment by edyoung** [comment]
I think dubm is a typo for dumb? But setting TERM=dumb breaks things completely, you can't even type commands successfully, let alone use cursor keys.

**Comment by wtgodbe** [comment]
Here is a PR with an attempt to resolve (currently in testing phase) - https://github.com/dotnet/corefx/pull/30674

**Comment by edyoung** [comment]
Based on the discussion we had I think this is a candidate for 2.1.3 servicing release (?)

**Comment by wtgodbe** [comment]
@edyoung that's my understanding as well

**Comment by wtgodbe** [comment]
PRs have been merged into master & 2.1 for this issue, so I'm closing it as resolved. Our daily builds out of master will have this change in System.Console, as well as our upcoming 2.1.3 release. Please let me know if you all need any help in picking up this change.

**Comment by jianyunt** [comment]
Thanks!!!

**Comment by wtgodbe** [comment]
The new package is now on Myget - https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.Private.CoreFx.NETCoreApp/4.5.0-servicing-26703-08

-Will

**Comment by karelz** [comment]
History details: The changed was fixed in release/2.1 branch in PR #30789 (originally it was addressed by PR #30759, but later reverted by PR #30788).
