### ISSUE TITLE
Problem serializing/deserializing using System.Runtime.Serialization.NetDataContractSerializer AND WindowsUpdate KB4103720

### ISSUE THREAD

**Issue by MobAtNti** [dotnet/corefx#30415]
Problem :
When serializing a dictionary object using System.Runtime.Serialization.NetDataContractSerializer with a stringComparer, it's not possible to deserialize the stream.

Problem only exists if :
- dictionary with stringComparer is serialized on Windows 2016 server **WITH** windowsupdate KB4103720
- dictionary from above is deserialized on Windows 2016 server **WITHOUT** windowsupdate KB4103720 ( and other OS', but can be reproduced as described)

Problem does NOT exist if :
- dictionary object does not have a StringComparer
- serialization / deserialization is performed on the same workstation (meaning KB4103720  is either installed or not when serializing / deserializing).

I've created a small test application which shows the problem (.Net FW 4.7)
1. On a Windows 2016 server **WITH** windowsupdate KB4103720, create a xml output of the dictionary serialization with a stringComparer.

```js
public void WriteObject(bool useComparer)
        {
            Dictionary<string, int> people;

            if (useComparer) { people = new Dictionary<string, int>(StringComparer.CurrentCultureIgnoreCase); }
            else { people = new Dictionary<string, int>(); }
            people.Add("Søren", 22);
            people.Add("Mads", 21);
            people.Add("Jens", 20);
            people.Add("Michael", 11);
            people.Add("Morten", 10);

            using (FileStream fs = new System.IO.FileStream("NetDataContractSerializerExample.xml", FileMode.Create))
            {
                XmlDictionaryWriter writer = XmlDictionaryWriter.CreateTextWriter(fs);
                NetDataContractSerializer ser = new NetDataContractSerializer();
                ser.WriteObject(writer, people);
                writer.Close();
            }
        }
```

2. On a Windows 2016 server **WITHOUT** windowsupdate KB4103720 (or Windows 10 Version 1709, OS build 16299.431), try to deserialize the xml output created above in step 1.
```js
public Dictionary<string, int> ReadObject()
        {
            Dictionary<string, int> deSerializedPeople;

            using (FileStream fs = new FileStream("NetDataContractSerializerExample.xml", FileMode.Open))
            {
                XmlDictionaryReader reader = XmlDictionaryReader.CreateTextReader(fs, new XmlDictionaryReaderQuotas());
                //NetDataContractSerializer ser = new NetDataContractSerializer();
                NetDataContractSerializer ser = new NetDataContractSerializer { AssemblyFormat = System.Runtime.Serialization.Formatters.FormatterAssemblyStyle.Simple };

                deSerializedPeople = (Dictionary<string, int>)ser.ReadObject(reader, true);
                fs.Close();
            }
            return deSerializedPeople;
        }
```

3. Creates the following error : Error in line 1 position 602. 'EndElement' 'Comparer' from namespace '' is not expected. Expecting element '_compareInfo'.

If you inspect the xml output created on a Windows 2016 server **WITH** windowsupdate KB4103720, and a Windows 2016 server **WITHOUT** windowsupdate KB4103720, there are differences in the <_compareinfo> tag, which must be the cause
See inserts:
XmlCreated**WITH**KB4103720:
```js
<?xml version="1.0"?>
<ArrayOfKeyValueOfstringint xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:x="http://www.w3.org/2001/XMLSchema" xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/2003/10/Serialization/Arrays" z:Assembly="0" z:Type="System.Collections.Generic.Dictionary`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]" z:Id="1">
  <Version xmlns="" z:Assembly="0" z:Type="System.Int32" z:Id="2">5</Version>
  <Comparer xmlns="" z:Assembly="0" z:Type="System.CultureAwareComparer" z:Id="3">
    <_compareInfo z:Assembly="0" z:Type="System.Globalization.CompareInfo" z:Id="4">
      <culture xmlns="http://schemas.datacontract.org/2004/07/System.Globalization">2057</culture>
      <m_SortVersion xmlns="http://schemas.datacontract.org/2004/07/System.Globalization" i:nil="true"/>
      <m_name xmlns="http://schemas.datacontract.org/2004/07/System.Globalization" z:Id="5">en-GB</m_name>
      <win32LCID xmlns="http://schemas.datacontract.org/2004/07/System.Globalization">0</win32LCID>
    </_compareInfo>
    <_options z:Assembly="0" z:Type="System.Globalization.CompareOptions" z:Id="6">IgnoreCase</_options>
    <_ignoreCase z:Assembly="0" z:Type="System.Boolean" z:Id="7">true</_ignoreCase>
  </Comparer>
  <HashSize xmlns="" z:Assembly="0" z:Type="System.Int32" z:Id="8">7</HashSize>
  <KeyValuePairs xmlns="" z:Assembly="0" z:Type="System.Collections.Generic.KeyValuePair`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]][]" z:Id="9" z:Size="5">
    <KeyValuePairOfstringint xmlns="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
      <key z:Id="10">Søren</key>
      <value>22</value>
    </KeyValuePairOfstringint>
    <KeyValuePairOfstringint xmlns="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
      <key z:Id="11">Mads</key>
      <value>21</value>
    </KeyValuePairOfstringint>
    <KeyValuePairOfstringint xmlns="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
      <key z:Id="12">Jens</key>
      <value>20</value>
    </KeyValuePairOfstringint>
    <KeyValuePairOfstringint xmlns="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
      <key z:Id="13">Michael</key>
      <value>11</value>
    </KeyValuePairOfstringint>
    <KeyValuePairOfstringint xmlns="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
      <key z:Id="14">Morten</key>
      <value>10</value>
    </KeyValuePairOfstringint>
  </KeyValuePairs>
</ArrayOfKeyValueOfstringint>
```

XmlCreated**WITHOUT**KB4103720:

```js
<?xml version="1.0"?>
<ArrayOfKeyValueOfstringint xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:x="http://www.w3.org/2001/XMLSchema" xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/2003/10/Serialization/Arrays" z:Assembly="0" z:Type="System.Collections.Generic.Dictionary`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]" z:Id="1">
  <Version xmlns="" z:Assembly="0" z:Type="System.Int32" z:Id="2">5</Version>
  <Comparer xmlns="" z:Assembly="0" z:Type="System.CultureAwareComparer" z:Id="3">
    <_compareInfo xmlns="http://schemas.datacontract.org/2004/07/System" z:Id="4" xmlns:a="http://schemas.datacontract.org/2004/07/System.Globalization">
      <a:culture>8192</a:culture>
      <a:m_SortVersion i:nil="true"/>
      <a:m_name z:Id="5">en-DK</a:m_name>
      <a:win32LCID>0</a:win32LCID>
    </_compareInfo>
    <_ignoreCase xmlns="http://schemas.datacontract.org/2004/07/System">true</_ignoreCase>
    <_options xmlns="http://schemas.datacontract.org/2004/07/System">IgnoreCase</_options>
  </Comparer>
  <HashSize xmlns="" z:Assembly="0" z:Type="System.Int32" z:Id="6">7</HashSize>
  <KeyValuePairs xmlns="" z:Assembly="0" z:Type="System.Collections.Generic.KeyValuePair`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]][]" z:Id="7" z:Size="5">
    <KeyValuePairOfstringint xmlns="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
      <key z:Id="8">Søren</key>
      <value>22</value>
    </KeyValuePairOfstringint>
    <KeyValuePairOfstringint xmlns="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
      <key z:Id="9">Mads</key>
      <value>21</value>
    </KeyValuePairOfstringint>
    <KeyValuePairOfstringint xmlns="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
      <key z:Id="10">Jens</key>
      <value>20</value>
    </KeyValuePairOfstringint>
    <KeyValuePairOfstringint xmlns="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
      <key z:Id="11">Michael</key>
      <value>11</value>
    </KeyValuePairOfstringint>
    <KeyValuePairOfstringint xmlns="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
      <key z:Id="12">Morten</key>
      <value>10</value>
    </KeyValuePairOfstringint>
  </KeyValuePairs>
</ArrayOfKeyValueOfstringint>
```

The way to reproduce the problem described above, is very simplified.
In reality we have a webservice (on OS with KB4103720) which serializes dictionary objects. When webservice is called from a server without KB4103720 installed, the error occurs.

Problem also occurs if a WIN 10 Version 1709, OSbuild 16299.431 tries to consume the webservice. I'm about to belive that all OS's not having windows update KB4103720 , will fail

**Comment by ViktorHofer** [comment]
This is very likely a bug and could be related to recent changes in StringComparers/CultureAwareComparers in netfx.

**Comment by MobAtNti** [comment]
Sounds like it could something.

Do you have any pointers to where in src the changes are made ?.

**Comment by ViktorHofer** [comment]
That's closed source, sorry. I just commented here to make the area-owners of Serialization aware of that issue and to provide a potential cause.

**Comment by Lxiamail** [comment]
@tarekgh I think you have context on this. Can you comment on it?

**Comment by tarekgh** [comment]
@MobAtNti 

> Can add as additional info, that the version of mscorlib.dll which gives us trouble is 4.7.2661.0 dated april 11, 2018 02:59

You may look at the KB article https://support.microsoft.com/en-us/help/4098972/description-of-preview-of-quality-rollup-for-net-framework-4-6-4-6-1-4 for answers to your question. We may get the fix for this issue released everywhere in next month. 

I am closing this issue but feel free to reply back with any question you have.

**Comment by MobAtNti** [comment]
Hello,

This problem (serializing a dictionary object using System.Runtime.Serialization.NetDataContractSerializer with a stringComparer, it's not possible to deserialize the stream.) disappeared when applying MS update **KB4284880** (June 12, 2018).

But now the problem has reemerged. A Win2016 server has been updated with KB4457131 (September 11, 2018) and now the serializing culture compability problem is back.

Applying **KB4457128** (September 11, 2018) to client workstation, fixes this issue again.

It's a big problem for us, that the serializing functions keeps changing and breaking compability. We have dosens of servers and unknown numbers of clients who are affected.

And we can't even fix the problem ourselfs :-(. 
If client A applies **KB4457128**, to a workstation, it breaks serializing culture compability. If we then, as a respond, applies **KB4457131** to the server, all other clients without **KB4457128**, will now suffer from this problem with serializing

Please take a look at this matter.

kind regards

**Comment by tarekgh** [comment]
@MobAtNti I apologize for that. we went into some fix iterations to address all broken scenarios. the latest fixes released in September for servers and clients should be addressing all problems. so we recommend you get the servers and clients to install September patches and moving forward nothing will need to be done more. I understand it is challenging  to have all clients to install the latest patches, but this is the best solution as we cannot have a one fix that magically can work with all possible serialization changes. I appreciate your understanding and apologize again regarding this issue.
