### ISSUE TITLE
Remove Microsoft.Internal code from Common

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#30419]
Currently used by System.Composition* and System.ComponentModel.Composition projects: https://github.com/dotnet/corefx/tree/master/src/Common/src/Microsoft/Internal

It's not just the name "Microsoft.Internal" that bugs me but also that none of these helpers are used in any projects besides MEF. We don't do parameter/argument validation like that anymore. I would like to get rid of Assumes, CommonStrings (which only contains 2! shared strings) Requires and the EmptyArray. I see that we have some kind of EmptyArray in couple places both in Corelib as in corefx, so maybe that one should be shared.

System.ComponentModel.Composition even has its own fork of Requires...

cc @stephentoub @maryamariyan @danmosemsft

**Comment by danmosemsft** [comment]
`EmptyArray<T>` can not be replaced with `Array.Empty<T>` in System.Reflection.Metadata because that builds for netstandard1.1  and it's in 1.3.
It also cannot be replaced on `List<T>` because https://github.com/dotnet/coreclr/pull/1596#issuecomment-141618877
Otherwise it can be replaced.

**Comment by Redouane64** [comment]
Should i remove everything inside Microsoft/Internal except EmptyArray.cs ?

**Comment by ViktorHofer** [comment]
Yes the goal is to remove all the files but the challenge is here to ensure that the Sustem.Composition* & System.ComponentModel.Composition assemblies still compile

**Comment by Redouane64** [comment]
System.Composition.Convention and System.Composition.Hosting still need 
Microsoft.Internal.Requires and Microsoft.Internal.Assumes. Should i keep these two partial classes?

**Comment by ViktorHofer** [comment]
The issue is about replacing the functionality and do validation the same way we do in other projects. But still make sure that the behavior stays the same

**Comment by ViktorHofer** [comment]
Requires.cs is easy, it should be easily replaced by inline checks:
Requires.NotNull --> throwing ArgumentNullException with nameof
Requires.NotNullOrEmpty --> throwing ArgumentNullException with nameof or ArgumentException with message and nameof

Same for Assumes. The internal exception thrown can be replaced with base class Exception with the message. All callers should inline the validation.

**Comment by danmosemsft** [comment]
@Redouane64 I sent you a collaborator link, if you accept that, I can assign you this issue. Note: it signs you up for notifications to all issues in the repo, you can disable that.

**Comment by Redouane64** [comment]
@danmosemsft Thanks for the invitation. I accepted it and i started working on this issue already, i will comment here any questions i have.

**Comment by ViktorHofer** [comment]
You could create a PR with your work in progress. It doesn't need to be finished. It often helps to guide someone into the right direction :)

**Comment by ViktorHofer** [comment]
Fixed by #30770
