### ISSUE TITLE
Exception when garbage collector (GC) calls the finalizer method which uses regex.replace( )

### ISSUE THREAD

**Issue by TapanGhoshRocket** [dotnet/corefx#30420]
When application ends, garbage collector (GC) invoke destructor( ) which uses regex.replace() method to replaces all strings that match a regular expression pattern with a replacement string in a input string. Then it throws "System.InvalidOperationException:Handle is not initialized" exception.

Here is the call stack, when exception is thrown.

Unhandled Exception: System.InvalidOperationException: Handle is not initialized.
   at System.WeakReference.set_Target(Object value)
   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
   at myclass.ReplacePwd(String value, String newvalue)
   at myclass.Finalize()

Reference : https://msdn.microsoft.com/en-us/library/system.weakreference.target(v=vs.110).aspx

Issue looks to be the target of a weak reference becomes null when the object is reclaimed by garbage collection. Have not find any reference docs, which suggest regex.replace() method cann't be used during destructor( ) call.

It seems regex.replace() method have bug during destructor( ) call.

**Comment by stephentoub** [comment]
cc: @Maoni0, @jkotas

**Comment by jkotas** [comment]
`WeakReference` is finalizable object. If you try to use it once it is finalized, it will throw this exception. This exception is explicitly mentioned in the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.weakreference.target?view=netcore-2.1).

> Have not find any reference docs, which suggest regex.replace() method cann't be used during destructor( ) call.

The docs for [Object.Finalize](https://docs.microsoft.com/en-us/dotnet/api/system.object.finalize?view=netcore-2.1#System_Object_Finalize) has a lot of text about that that you cannot make assumptions about the overall state of the system when running finalizers. Finalizers are for releasing unmanaged resources; not for running arbitrary framework code like regex in this case.

**Comment by danmosemsft** [comment]
Closing as this is operating as documented. @TapanGhoshRocket you should probably have your code explicitly invoke any cleanup steps.
