### ISSUE TITLE
HtmlString should implement IComparable 

### ISSUE THREAD

**Issue by jrmoreno1** [dotnet/corefx#30436]
I recently started using HtmlString for binding to a GridView, when I tried to sort the grid, much to my surprise, a System.ArgumentExcpetion was thrown: At least one object must implement IComparable!

HtmlString should implement IComparable (as well as the generic version).

**Comment by karelz** [comment]
HtmlString is not part of .NET Core, it is in System.Web namespace, available only on .NET Framework - see [details](https://apisof.net/catalog/System.Web.HtmlString). Closing as not related to CoreFX repo.

The bar for changes in .NET Framework is high. I would recommend to check if there is an easy workaround (e.g. wrapping HtmlString with your own class which implements IComparable).
If it is affecting significant number of apps on .NET Framework, without a reasonable workaround, then I would suggest to file it on VS Developer Community Portal (see out [main page](https://github.com/dotnet/corefx#how-to-engage-contribute-and-provide-feedback) for instructions).
