### ISSUE TITLE
Proposal: Array.SearchFor method

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/corefx#30443]
Array.Find<T> Method is not practical, because it returns the default value of T if the search failed, i.e if T is int, it returns zero when it found nothing!.. This forces us to to use the Array.Exists first to make sure the element exists before reading it, which means we have to do the search twice!
```
if (Array.Exists(new[] { 1, 2, 3 }, (N) => N < 0))
    Console.WriteLine(Array.Find(new[] {1, 2, 3}, (N) => N < 0));
```

I suggest to add this method to solve this issue:
```
public static (bool Exists, T Item) SearchFor<T>(
    T[] array, Predicate<T> match)
{
    foreach (T item in array)
        if (match(item))
            return (true, item);

    return (false, default(T));
}
```

so we can use it like this:
```
var result = Array.SearchFor(new[] { 1, 2, 3 }, (N) => N < 0);
if (result.Exists)
    Console.WriteLine(result.Item);
```

And you can mark Array.Find method as obsolete.

Note:
It will be better if the implementaion of SearchFor can use parallelism to be faster.

**Comment by juliusfriedman** [comment]
https://msdn.microsoft.com/en-us/library/d9hy2xwa(v=vs.110).aspx

This method is already on Array, your example is incorrect...

It would perhaps be useful to have offset and count parameters on that method to avoid having to drop down to your own logic for such.

**Comment by MohammadHamdyGhanem** [comment]
@juliusfriedman 
Sorry, I can't clearly get what you mean!
I know that Array.Find exists and this issue is about it.. The Docs you refered to says:
> Return Value
> Type: T
> The first element that matches the conditions defined by the specified predicate, if found; otherwise, the default value for type T.

This is not efficient as I explained.

> your example is incorrect
How?

**Comment by karelz** [comment]
You can use [`FindIndex`](https://msdn.microsoft.com/en-us/library/03y7c6xy(v=vs.110).aspx) instead - it will return -1 if not found.

**Comment by juliusfriedman** [comment]
@MohammadHamdyGhanem, my apolagies, your actually correct my mistake... I read that wrong while looking at other methods...

Definitely agree that there should be a variation which indicates success unambiguously.. e.g. TryFind rather than Search for, good call none the less.

**Comment by MohammadHamdyGhanem** [comment]
@karelz 
Thanks. There are many ways to do it, such as:
```
var result = (from int N in new[] { 1, -2, 3 }
                where N < 0
                select N).AsParallel();

if (result.Count() > 0)
    Console.WriteLine(result.ElementAt(0));
```

But I wanted to point out that there is a problem with the Find Method, that can be solved with Tuples. I once asked to review all the framework for such legacy methods, and you asked me to point out them. This is one of them that can be improved with new C# syntax.
Thanks.

**Comment by MohammadHamdyGhanem** [comment]
@juliusfriedman 
That's OK. 
I don't mind using any suitable name for the new method. I just gave an example. TryFind is OK.
Thanks.

**Comment by karelz** [comment]
I don't think we should add "overloads" (requires new method name) with tuples, when there is fairly straightforward existing solution - look for index via "overload" FindIndex instead of for value.
It there was not `FindIndex`, I would be fine adding `SearchFor`.

**Comment by MohammadHamdyGhanem** [comment]
@karelz
At leat mark Find method obsolete. It has no purpose and error prone

**Comment by MohammadHamdyGhanem** [comment]
@karelz 
Besides:
It is slightly slower to get the index then using it to traverse the Array again!
I think tuples should take over, and search methods should return a tuple containing both the inexed and the value.
