### ISSUE TITLE
Add Enumerable.HasElements method

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/corefx#30445]
In this LinQ:
```
var result = (from int N in new[] { 1, -2, 3 }
                where N < 0
                select N).Take(1);

if (result.Count() > 0)
    Console.WriteLine(result.First());
```

```result.Count()``` will execute a count query, then ```result.First``` will execute a Take(1) query, which is not sufficient. I solve this by using:

```
foreach (var item in result)
{
   Console.WriteLine(item);
   break;
}
```

Or:
```
try
{
  Console.WriteLine(result.First());
}
catch { }
```

But they booth seem ugly!
I suggest to add a HasElements() extension Method to the Enumerable and Queryable classes, so than we can write:

```
if (result.HasElements( ))
    Console.WriteLine(result.First());
```

HasElements should return true after finding one element, which is stored in a private field to be uses as the return value of the First() method and ElementAt(0) method, without re-executing the query again!

Another approach is to add another method named IfFirst, which return value if (bool exists, T Item), so we can write:
```
var r = result.IfFirst()
if (r.Exists( ))
    Console.WriteLine(r.Item);
```

**Comment by svick** [comment]
That method already exists, it's called [`Any`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.any?view=netframework-4.7.2#System_Linq_Enumerable_Any__1_System_Collections_Generic_IEnumerable___0__).

> HasElements should return true after finding one element, which is stored in a private field to be uses as the return value of the First() method and ElementAt(0) method, without re-executing the query again!

That's not really possible. LINQ to objects works on any `IEnumerable<T>`, it can't affect how it's implemented.

Though I think a method that returns an enumerable that lazily caches already retrieved elements from another enumerable could be useful (and [F# has one](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/seq.cache%5B%27t%5D-function-%5Bfsharp%5D)).

With that, your code would look like this:

```c#
result = result.Cache();

if (result.Any())
    Console.WriteLine(result.First());
```

**Comment by MohammadHamdyGhanem** [comment]
@svick 
Thanks. I used to think of Any() as a method to search for an element that achives some condition!
HasElments would be a more meaningful name!
any way, I will depend on Any() instead of Count().

But I don't understand what this means:
```result = result.Cache();```
