### ISSUE TITLE
Delete tests that depend on JIT optimization behavior

### ISSUE THREAD

**Issue by sandreenko** [dotnet/corefx#30444]
There are tests that try to predict JIT optimizations (inlining, tail calls etc), for example:
https://github.com/dotnet/corefx/blob/eccda152a75bd471d9037f18cbd6223a2da177fd/src/System.Diagnostics.StackTrace/tests/StackFrameTests.cs#L61-L71

checks that `public StackFrame CallMethod(int skipFrames) => new StackFrame(skipFrames);` was inlined in the Release mode.

Such tests are often failing in stress modes in CoreCLR testing, they are fragile and mostly invalid. 
There is no way to make them valid for all modes, for example if you build release CoreCLR and debug CoreFX, then debug CoreFX test will expect  `CallMethod` be presented on the stack, when release `CoreCLR` inlines it.

The solution is delete such tests from CoreFX, if some of them are essential then they should be moved to CoreCLR where we can control tests/modes/optimizations better.

See the discussion in https://github.com/dotnet/corefx/issues/28853#issuecomment-386434556.

The fix for this issue will fix dotnet/coreclr#17558

**Comment by sandreenko** [comment]
PTAL @dotnet/corefx-contrib 
cc @BruceForstall @dotnet/jit-contrib

**Comment by jkotas** [comment]
This can be fixed by marking `CallMethod` with NoInlining attribute. It is what other corefx tests that examine stacktraces do (e.g. https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/tests/System/Environment.StackTrace.cs#L44).

**Comment by jkotas** [comment]
Or we can delete all `#if !DEBUG` code in this file, and mark all test methods with NoInlining attribute. It will make the tests reliable as well.
