### ISSUE TITLE
IFixedDictionary and IFixedList

### ISSUE THREAD

**Issue by iBeizsley** [dotnet/corefx#30458]
I believe that two new interfaces would be handy additions to the core libraries: `IFixedList`, and `IFixedDictionary`. An alternate name might be `IEditOnly`.

We currently have `IReadOnlyList` and `IReadOnlyDictionary` (as well as `IReadOnlyCollection`, though that's irrelevant in this suggestion). These new interfaces would be identical to the `IReadOnly` variants, except they would include a set accessor on the indexer.

In the case of Dictionaries, I have come across many situations where this would have been a nice-to-have. One example, which is the one which prompted me to suggest this, is the game dev library I'm currently writing, which includes a `Creature` class. `Creature`s have `CreatureStat`s, which could be anything from health, to hunger, to a 'crafting' skill. `Creature`s are initialized via a `CreatureSpecification`, which includes which stats the `Creature` has; a player, a shopkeeper NPC, and a hostile NPC are all examples of `Creature`s, and all might have very different stats; the player and their party members might all have trainable skills, while a rabid wolf might have only a health stat.

Stats are stored in a `Dictionary` with their current value, and the contained stats, as well as the starting values, are all known on initialization. Stats will never be added to or removed from a `Creature`, just changed regularly. Obviously there's a myriad of solutions currently available, but the simplest, and nicest way would be using a `IFixedDictionary` here.

I honestly can't think of many useS for `IFixedList` off the top of my head, but for consistency sake, it might make sense to implement, and considering it allows people to treat Lists and Arrays identically, I'm sure there are uses I'm just not thinking of right now.

**Comment by AlgorithmsAreCool** [comment]
If I'm reading this correctly, these are fixed in length/count but allow read/write access to individual items?

I don't think there is a very compelling case for an IFixedList. You can already use an T[] or Memory<T>/Span<T> for the same purpose. 

The dictionary use case is a bit more interesting but still very niche, but I don't think It's broadly usable enough to go into corefx.

**Comment by danmosemsft** [comment]
@ibeizsley thanks for the suggestion. Certainly there are scenarios in code, like yours, where a dictionary would never change size. But what value would introducing `IFixedDictionary` add?

 It does not provide much protection against accidentally changing the size of a regular `Dictionary` since you can just cast away the interface. 

A good reason might be if there were hypothetically several concrete implementations of Dictionary that cannot change size , and there are interesting algorithms that manipulate dictionaries that 
never needs to change their size, and by introducing this interface the algorithms can accept any of the various implementations. I'm not sure that's the case?

**Comment by iBeizsley** [comment]
I disagree that it offers little protection against _accidentally_ changing the length of a `Dictionary`, as the only reason I can think of that you would actually want to cast to a `Dictionary` would be to change the length; there's a barrier to entry which should prevent accidents from occurring.

Using this interface also provides useful information at a glance; if a given key is present in the dictionary, it always will be. Perhaps implementing an actual `FixedDictionary` collection which implements `IFixedDictionary` alongside `Dictionary`, `ConcurrentDictionary` etc makes more sense. A `FixedDictionary` will always experience the same performance improvement one gets when specifying the length of a dictionary on initialization, and I'd argue that in many places the capacity constructor is used, there's a solid chance that using a `FixedDictionary` would be possible.

Also, am I wrong in assuming that for all but value types larger than 32 bits, a `FixedDictionary` should be automatically threadsafe? Reads are atomic, as well as <=32 bit value assignment and reference assignment, and as the presence of a key is guaranteed to never change, I'd have thought it would be. Looks like I'll have to go digging to fix my woefully sparse knowledge of the internals of the `Dictionary`. It appears `Array` throws an exception when it's changed during enumeration, and I'd have thought the same would apply there, so maybe I'm wrong.

If I'm correct though, it could be implemented like: `FixedDictionary<TKey, TValue> : IFixedDictionary<TKey, TValue> where TValue : class ` and `FixedDictionary<TKey, TValue> : IFixedDictionary<TKey, TValue> where TValue : struct` to allow for not throwing unnecessary exceptions in the class variant, then a `ConcurrentFixedDictionary<TKey, TValue> : IFixedDictionary<TKey, TValue> where TValue : struct` could be implemented too.

Off the top of my head, `FixedDictionary` could be used during serialization and deserialization (such as populating parameters for a constructor marked for deserialization), or as a method parameter in highly abstracted situations, and in dependency injection libraries. In most situations, I admit, its advantages over a normal `Dictionary` are fairly minor, unless lockless threading is actually possible with them.

I'll rack my brains a bit in the morning to try to think of more concrete, significant and less niche examples, though; I can definitely understand the argument for it just not being _that_ useful.

**Comment by AlgorithmsAreCool** [comment]
@iBeizsley

Perhaps what you are looking for is actually a type not so much a dictionary. 

You want to be able to create a dict with a fixed set of keys and allow access to them. Why not a type with properties? 

If you need the flexibility to define the keys at runtime, what about `DynamicObject`?

**Comment by iBeizsley** [comment]
@AlgorithmsAreCool 

The dictionary's keys are defined at runtime, and cannot be changed after initialization of the dictionary. Neither suggestion really fits the requirements, as an object's properties are defined at compile time, and a dynamic object's keys are not fixed (I think just using a standard Dictionary is a better solution for performance and general behaviour reasons here; the only difference between a standard Dictionary and a FixedDictionary is the inability to add or remove keys). If the threading benefits are valid (will have to look into this more), no other solution that I can think of is really equivalent.

All of the applications I can think of are, however, really quite niche, so this is probably more the domain of a standalone library than inclusion in corefx. I'll probably write the library myself, put it up on Nuget, and maybe come back to the idea of including it in corefx if it turns out to be less niche than I think it is currently.

Closing for now.

**Comment by Joe4evr** [comment]
As was previously stated, your idea of a "fixed list" is essentially just a `T[]`.

And a "fixed dictionary" can be easily emulated using a normal `Dictionary<K, V>` with an `enum` as the key.
