### ISSUE TITLE
Activity.Current is null

### ISSUE THREAD

**Issue by AlexZeitler** [dotnet/corefx#30455]
I was reading the [Activity User Guide](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md) and what I tried to do was this:

In an ASP.NET Core Controller I created a new `Activity` and set a `ParentId` for it.
That controller calls a dependency and within that dependency I want to get the `ParentId` of the current Activity using `Activity.Current` but `Activity.Current` is `null`.

This is my Controller:

```c#
    public class HelloController : Controller
    {
        // GET
        [Route("api/hello")]
        public IActionResult Index()
        {
            var activity = new Activity("Http_In");
            activity.SetParentId("some-parent-id");
            activity.SetStartTime(DateTime.Now)
                .AddTag("Path", Request.Path)
                .AddBaggage("FeatureId", Guid.NewGuid().ToString());
            activity.Start();
            Log.Debug($"Correlation Id: {activity.ParentId}");
            var dependency = new SomeDependency();
            dependency.GetHello("World");
            activity.Stop();
            return new OkObjectResult(dependency.GetHello("World"));
        }
    }
```

This is `SomeDepedency`:

```c#
    public class SomeDependency
    {
        public string GetHello(string param)
        {
            Log.Debug($"Correlation Id: {Activity.Current.ParentId}");
            return $"Hello {param}";
        }
    }
```

I also tried to create a new `Activity` in `SomeDepdency` class but its `ParentId` was empty.
What I want to achieve is not to need to pass around a `Activity` between my Controller and it's depdency using a parameter in `GetHello`.

**Comment by vancem** [comment]
I tried to reproduce your issue in the simple console application here

[Program.cs.txt](https://github.com/dotnet/corefx/files/2113278/Program.cs.txt)

case but I could not.  The result printed 
 ```
Correlation Id: some-parent-id
Correlation Id: some-parent-id
```
which is expected (you see the parent-ID in both loging statements bing 'some-parent-id'. 

Presumably there is more going in in your example than my repro.   Is your 'Some Dependency' actually a different service (not just a class as is implied above?)   Then of course the scenario is a bit more complex, and you actually have to turn on the 'tagging' of the requests from one service to the next.  Is that what you are trying to do?

@brianrob

**Comment by cwe1ss** [comment]
@AlexZeitler you're calling `dependency.GetHello("World")` again after the activity has been stopped. Activity.Current will be null on that second call.
```csharp
activity.Stop();
return new OkObjectResult(dependency.GetHello("World"));
```
