### ISSUE TITLE
System.Linq.Expression tests failing on Visual Studio 15.8 Preview

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#30466]
Repro:

- Install Visual Studio 15.8.0 Preview 27813.1.d15.8
- build.cmd -release
- build-tests.cmd -release

Result:

System.Linq.Expressions tests crashing with AV in Microsoft.DiaSymReader.Native.amd64.dll

**Comment by jkotas** [comment]
@VCZYK is working on a fix.

**Comment by jaredpar** [comment]
Any updates on this @VCZYK ?

**Comment by danmosemsft** [comment]
@jkotas any evidence this is still relevant?

**Comment by jkotas** [comment]
This was fixed in `Microsoft.DiaSymReader.Native.amd64.dll` and Roslyn picked up fixed version.
