### ISSUE TITLE
Socket Poll/Select should not allocate - internal implementation change

### ISSUE THREAD

**Issue by mgravell** [dotnet/corefx#30475]
Currently, on Windows:

- `Socket.Poll` always allocates an `IntPtr[2]` (currently [line 674 of SocketPal.Windows](https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/SocketPal.Windows.cs#L674))
- `Socket.Select` always allocates an `IntPtr[socketCount + 1]` (currently [line 132 of Socket.Windows](https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/Socket.Windows.cs#L132)) (one array per each of the 3 possible inputs - read/write/error)

These are low-level networking APIs that are often used at relatively high frequency, so even those these arrays are "cheaply" collectable (gen-0), they are still unnecessary overhead.

However, with minimal internal changes, these allocations can be completely avoided in virtually all cases:

- the interop API can be updated to use `IntPtr*` (or alternatively an `IntPtr` that *contains* the pointer) instead of `IntPtr[]`
- `Socket.Poll` can use `stackalloc IntPtr[2]`; this doesn't need any pinning
- `Socket.Select` can use the same logic from SocketPal.Unix, and use `stackalloc` for moderate sized data (the unix code uses 80 as the cutoff), only elevating to an `IntPtr[]` for significantly sized inputs - noting that the array will require pinning - most likely via `fixed`

I have investigated the changes locally and they seem reasonable; am happy to contribute PR when I can get tests working.

edit: [preview of proposed changes on my fork - incomplete](https://github.com/mgravell/corefx/pull/1/files)

**Comment by karelz** [comment]
Your description sounds reasonable. We will be happy to take a PR! Thanks @mgravell!

**Comment by mgravell** [comment]
@karelz  cheers; looks like there are some others I can clean up at the same time - most notably the temporary state arrays allocated for multi-segment `Send`/`Receive` - any objection if I put that in at the same time?

[[https://imgflip.com/i/2cf6m3]]

**Comment by karelz** [comment]
If it passes PR code reviews, why not 😆

**Comment by mgravell** [comment]
implementation note: following some investigation and cross-referencing other art (such as [EcDsaSign](https://github.com/dotnet/corefx/search?q=EcDsaSign&unscoped_q=EcDsaSign)), it seems that using a managed reference like `ref Foo foo` (as an alternative to `Foo* foo`) is treated *effectively* an implicit pin (similar to `fixed`); as such, I'm going with that option, which is a: convenient, and b: avoids the need to introduce `unsafe` code

**Comment by mgravell** [comment]
@karelz  FYI I'm having difficulty with testing; in particular, PerfRunner.exe doesn't exist in my fork - and I'm having lots of problems getting the functional tests to run, things like:

> Could not find test executor with URI 'executor://xunit/VsTestRunner2'.  Make sure that the test executor is installed and supports .net runtime version 4.0.30319.42000.

Is there a dummies guide to this?

**Comment by MarcoRossignoli** [comment]
> implementation note: following some investigation and cross-referencing other art (such as EcDsaSign), it seems that using a managed reference like ref Foo foo (as an alternative to Foo* foo) is treated effectively an implicit pin (similar to fixed); as such, I'm going with that option, which is a: convenient, and b: avoids the need to introduce unsafe code

In past we had some discussion on [PR](https://github.com/dotnet/coreclr/pull/17528#discussion_r181142155)(also some reverts [from ref to unsafe](https://github.com/dotnet/corefx/pull/30115/files)) ...i'm curious to know what @jkotas thinks, is there a guideline?

**Comment by mgravell** [comment]
happy to revert to `unsafe`/`fixed` if so-guided by @jkotas , but indeed that's a very relevant discussion, cheers

**Comment by MarcoRossignoli** [comment]
> Is there a dummy's guide to this?

https://github.com/dotnet/corefx/blob/8e842fa29e14694cca96c6e39a38199c55a3a02e/Documentation/project-docs/developer-guide.md#tests

**Comment by mgravell** [comment]
@MarcoRossignoli  thanks, that seems to have me a bit further along - I'll keep prodding it :)

**Comment by mgravell** [comment]
@karelz PR is up ^^^

**Comment by jkotas** [comment]
> i'm curious to know what @jkotas thinks, is there a guideline?

Stephen's comment https://github.com/dotnet/corefx/pull/30485#discussion_r196065260 described it accurately.

**Comment by mgravell** [comment]
marking closed; PR merged
