### ISSUE TITLE
Building from source fails to download required dotnet cli tool with 404 not found error.

### ISSUE THREAD

**Issue by Redouane64** [dotnet/corefx#30479]
Trying to build CoreFX from source by running build scripts fails to download dotnet cli tool with 404 Not Found.

Here is error on cmd:

```
Installing dotnet cli...
ERROR: Could not install dotnet cli correctly.
Please check the detailed log that follows.
Running E:\GitHub\corefx\init-tools.cmd
Installing 'https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.300-rc1-008673/dotnet-sdk-2.1.300-rc1-008673-win-x64.zip' to 'E:\GitHub\corefx\Tools\dotnetcli\dotnet-sdk-2.1.300-rc1-008673-win-x64.zip'
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At line:1 char:249
+ ... dentials; } $wc.DownloadFile('https://dotnetcli.azureedge.net/dotnet/ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : WebException
```

Also. I tried to access download URL from browser and fails with 404 Not Found, Here is output from browser:

````
<Error>
<Code>ResourceNotFound</Code>
<Message>
The specified resource does not exist. RequestId:3aca3efb-b01e-003a-4e9b-06eb68000000 Time:2018-06-18T00:32:14.4887599Z
</Message>
</Error>
````

I have direct access to the internet (no proxy).

**Location details:**
region: North Africa
country: Algeria

cc @karelz

**Comment by karelz** [comment]
The same URL worked fine for me and for another contributor in Germany.
@akoeplinger suggested to avoid CDN problems via direct URL: https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.300-rc1-008673/dotnet-sdk-2.1.300-rc1-008673-win-x64.zip
That one fails for everyone.

Also, trying the original URL (https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.300-rc1-008673/dotnet-sdk-2.1.300-rc1-008673-win-x64.zip) via https://www.uptrends.com/tools/uptime shows it fails as 404 from everywhere (incl. Seattle).

@dotnet/dnceng can you please check if it is some misconfiguration on our side? cc @weshaggard

**Comment by jkotas** [comment]
All CoreCLR and CoreFX PRs are failing because on this issues. 

E.g. https://github.com/dotnet/coreclr/pull/18518#issuecomment-397850329

**Comment by dagood** [comment]
This should be fixed now. The storage account was misconfigured. (See https://github.com/dotnet/core-eng/issues/3700 for followup.)

**Comment by cocowalla** [comment]
@dagood ironically, your link is a 404!

**Comment by Redouane64** [comment]
Closing the issue as the download is working!

**Comment by dagood** [comment]
@cocowalla Hah, yeah, it's a private repo, sorry. Unfortunate that we can't set up something other than a 404 for those links. The root cause ended up being https://github.com/Microsoft/AzureStorageExplorer/issues/317.
