### ISSUE TITLE
Possible memory corruption in Apple crypto code

### ISSUE THREAD

**Issue by filipnavara** [dotnet/corefx#30484]
The following two lines seem suspicious. They cast int32_t* pointer to size_t* pointer, which could result in overwritten memory on 64-bit platforms: 

https://github.com/dotnet/corefx/blob/e48ef36943e44d0944bec76f23931da2245b8576/src/Native/Unix/System.Security.Cryptography.Native.Apple/pal_symmetric.cpp#L100
https://github.com/dotnet/corefx/blob/e48ef36943e44d0944bec76f23931da2245b8576/src/Native/Unix/System.Security.Cryptography.Native.Apple/pal_symmetric.cpp#L118

**Comment by filipnavara** [comment]
cc @bartonjs

**Comment by karelz** [comment]
Fixed in release 2.1 in PR #30534
