### ISSUE TITLE
ALPN support for SslStream on Mac

### ISSUE THREAD

**Issue by Tratcher** [dotnet/corefx#30492]
Follow up on #23177 and #24389

The ALPN implementation for SslStream left out Mac support due to the APIs not being available on the older version of Mac OS being compiled for. The APIs are available in later versions.

References:
https://github.com/dotnet/corefx/pull/24389/files#r142497272
https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/src/System/Net/Security/SslStreamPal.OSX.cs#L104-L108

Priority:
- Server: This would be useful for HTTP/2 dev and test purposes. Not blocking.
- Client: This blocks the new SocketsHttpHandler client from supporting HTTP/2 on Mac clients.

**Comment by wfurt** [comment]
I did some testing and we can get client side working on 10.12 and 10.13. 

However server side will not work even with latest 10.13. Here is why:
https://opensource.apple.com/release/macos-1013.html

follows coretls 155:
https://opensource.apple.com/source/coreTLS/coreTLS-155/lib/sslHandshakeHello.c.auto.html

SSLProcessClientHelloExtensions() is lacking processing for ALPN. With that sever will not get the offered list and ctx->alpn_announced will not be set. 
The reverse order SSLProcessServerHelloExtensions() works: alpn will be processed and client can access it. 

The other problem that API suitable for client (get/set) may not be sufficient for server. 
We will need callback executed after ClientHello is received and before ServerHello is sent.

**Comment by wfurt** [comment]
I'm closing this for now. Client side is done and sever is not possible because Apple's SSL lacks needed API. I'll open new issue to track it and I'll target it for future.
