### ISSUE TITLE
Add a switch to AppContext that identifies the current framework

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#3049]
Scenario
===

We would like to enable loading references from nuget packages in Roslyn scripts. A sample script could look like follows:

```
#r "System.IO.FileSystem.4.0.0.nuget"

var stream = new FileStream(@"C:\temp\file");
```

The app running this script would use Roslyn Hosting APIs to compile and execute the script code at runtime. Our script engine would 
1) download the nuget package to local cache, if it's not already available 
2) find the implementation assembly(ies) in the package [1]
3) compile the script against these assemblies [2]
4) execute the script (which loads the assemblies)

The question we need to answer in step 2) is what is the identifier of the current framework, since the nuget may contain implementation assemblies targeting multiple platforms/frameworks. 

Proposal
===

We propose that the CLR host exposes the framework identifier to the application thru AppContext.

We will assume that the name of the framework is "net46" if we don't find the value in AppContext. Roslyn Scripting API requires 4.6+ FX on desktop, so if the value is properly set on future releases of Desktop FX and by all CoreCLR hosts we will always find the right one.

Notes
===
[1] If the package doesn't have impl assemblies then we fall back to GAC lookup.
[2] The script engine always compiles against runtime/implementation assemblies (very much like Reflection.Emit). Contract assemblies are usually not available on non-developer machines. We don't require all dependencies to be loaded thru nuget packages, which would give us access to contract assemblies.

**Comment by tmat** [comment]
@nguerrera @terrajobst

**Comment by nguerrera** [comment]
cc @weshaggard @ericstj

**Comment by nguerrera** [comment]
cc @AlexGhiondea

**Comment by davidfowl** [comment]
Please make this settable when you add it 😀

**Comment by AlexGhiondea** [comment]
How is this new property going to map to the TargetFrameworkName that the host sets?

**Comment by davidfowl** [comment]
It should be the same I would think.

**Comment by AlexGhiondea** [comment]
@davidfowl - In that case, what you get back won't be something like 'net46' but more something like: '.NETFramework, Version=v4.6'.

If that is something you want, then this 'switch' will turn into us forwarding the TargetFrameworkName property on AppDomainSetup via AppContext.

**Comment by davidfowl** [comment]
@AlexGhiondea That sounds good

**Comment by davidfowl** [comment]
@joshfree Why is this a future thing? We're going to need this very soon

**Comment by weshaggard** [comment]
@davidfowl what do you guys plan to do with this information very soon?

**Comment by davidfowl** [comment]
We have a type right now [IApplicationEnvironment](https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Extensions.PlatformAbstractions/IApplicationEnvironment.cs) that is intended to be a DI friendly and thin wrapper over whatever information we can gather from the BCL. Here's the implementation for this on both full framework and .NET Core:

https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Extensions.PlatformAbstractions/DefaultApplicationEnvironment.cs

We use this information at runtime to figure out what reference assemblies to use for compilation of razor files.
