### ISSUE TITLE
CPU Usage on 2.1 constantly builds

### ISSUE THREAD

**Issue by ByronAP** [dotnet/corefx#30500]
I have increasing CPU which seems to be from HTTP. It was not noticeable until I went to production which looked great after deployment, but a few hours later everything was redlined due to ever-increasing CPU demand as shown below. Unfortunately, this is a show stopper and is forcing me to rollback.

Runtime: core 2.1 Linux x64
Containers: YES Docker
OS: UBUNTU & CENTOS
![cpu](https://user-images.githubusercontent.com/7310089/41560678-e0948268-7315-11e8-8db3-29f24eade7d4.PNG)

Reported by others here: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/690

**Comment by stephentoub** [comment]
> I have increasing CPU which seems to be from HTTP.

You profiled and it showed it was from System.Net.Http?  If so, can you provide more details?  What in System.Net.Http did you see causing the issue here?

**Comment by ByronAP** [comment]
My initial profile looked good but looking at how it builds I need to leave it running for a lot longer. When not extensively using HTTP services stayed in spec (and some issues with HTTP from RC) hence the assumption it is HTTP related. I will profile again tonight and see what I get (hopefully it shows on Windows as well).

**Comment by ByronAP** [comment]
so far no luck on Windows :-(

**Comment by karelz** [comment]
Did you try to collect and analyze a trace from the time the CPU is high?

**Comment by ByronAP** [comment]
I would if I could, unfortunately, It requires me to setup a new testbed which I do not have time for right away, I'm still rolling back changes :-(

**Comment by karelz** [comment]
Understood. Do you think you will have time later? I am afraid that with the information available there is not much we can do :(

**Comment by ByronAP** [comment]
When later will be is unknown at this time but I will definitely be investigating and keeping thread updating. I have to get my system back to a nominal state before I can really spend any more time on it. Which so far I am 24 hours almost straight on this and about to have a heart attack lol

**Comment by karelz** [comment]
@emsfeld do you have a chance to provide more information? Sadly, this is non-actionable from our side. There's plenty of customers on 2.1 who don't hit the problem, so it is specific to the app pattern. Without knowing the pattern or having some logs/traces, there is nothing we can do :(.

**Comment by karelz** [comment]
@emsfeld can you try to downgrade or disable AppInsights? - see https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/690#issuecomment-399046332 for possible culprit.

**Comment by emsfeld** [comment]
@karelz I am neither using AppInsights nor AspNetCore. I basically just repeatedly pull the source from websites using HttpClient from System.Net.Http. Maybe I should have reported this as a separate issue but (possibly wrongly) assumed it is related. I will try to create a short reproducible test case.

**Comment by karelz** [comment]
@emsfeld yeah, let's file a separate issue for investigation to keep things simple - we can merge them later if they turn out to be the same root-cause.
If you can give us some repro we can look at locally, that would be amazing!

**Comment by ByronAP** [comment]
my use case is the same, I make lots of http requests but do not use asp .net core or app insights. So far what I think is happening is that the new http system is not releasing all of the resources properly. I am at the create method as hot and also show some zombies, next run I will hopefully be able to see deeper into that.

**Comment by ByronAP** [comment]
also for those of you who hit this, before rolling back try going back to curl via SetSwitch ala ```AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);```

**Comment by stephentoub** [comment]
> I make lots of http requests

The same site or to many different sites? e.g. are you closer to a) accessing the same web service over and over, or b) implementing a web crawler?

**Comment by ByronAP** [comment]
many using proxies, however anomalies showed up for my redis connections which uses only 1 server and no proxy

**Comment by ByronAP** [comment]
@emsfeld are you using proxies?

**Comment by emsfeld** [comment]
@ByronAP No, no proxies.

**Comment by ByronAP** [comment]
It seems in my case the issue was caused by a bad library (stackexchange.redis) and not the framework YAY 

Closing this unless someone else can provide details on an actual corefx related issue that warrants a reopen.

**Comment by danmosemsft** [comment]
Thanks for the update @ByronAP . do you have a stackexchange.redist bug link to paste in?
