### ISSUE TITLE
Override TextWriter.Write{Line}{Async} on StringWriter

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#30502]
StringWriter is backed by a StringBuilder, so writing another StringBuilder to it can be optimized to call `_sb.Append(value)`.

cc: @vancem

**Comment by MarcoRossignoli** [comment]
Can grab this?

**Comment by stephentoub** [comment]
Sure, thanks :)

**Comment by MarcoRossignoli** [comment]
@stephentoub do we need some perf comparison?

**Comment by stephentoub** [comment]
> do we need some perf comparison?

It would be useful to validate the work, but it's highly unlikely this would degrade perf, so while it'd be good to do, you don't need to exert a lot of effort on it.
