### ISSUE TITLE
Add AssemblyLoadContext.LoadUnmanagedDllFromPath helper API

### ISSUE THREAD

**Issue by kouvel** [dotnet/corefx#3054]
## Scenario

Overrides of `System.Runtime.Loader.AssemblyLoadContext.LoadUnmanagedDll` that just wish to provide alternative paths are forced to write platform-specific code to call `LoadLibrary` or `dlopen` to load the library and return the library handle.

For example:

```c#
internal class CustomAssemblyLoadContext : AssemblyLoadContext
{
    [DllImport("kernel32")]
    private static extern IntPtr LoadLibrary(string path);

    [DllImport("libdl")]
    private static extern IntPtr dlopen(string path, int flags);

    protected override IntPtr LoadUnmanagedDll(String unmanagedDllName)
    {
        if (!ShouldLoadFromCurrentDirectory(unmanagedDllName))
        {
            return IntPtr.Zero; // use the default loader
        }

        var libraryPath = Path.Combine(Environment.CurrentDirectory, unmanagedDllName);
        IntPtr libraryHandle =
            EnvironmentHelper.IsWindows
                ? LoadLibrary(libraryPath)
                : dlopen(libraryPath, 0);
        if (libraryHandle == IntPtr.Zero)
        {
            // ... (more error handling)
            throw new DllNotFoundException(unmanagedDllName);
        }
        return libraryHandle;
    }
}
```

The proposal is to add an API to `AssemblyLoadContext` to provide a platform-independent way of loading an unmanaged library:

```c#
internal class CustomAssemblyLoadContext : AssemblyLoadContext
{
    protected override IntPtr LoadUnmanagedDll(String unmanagedDllName)
    {
        if (!ShouldLoadFromCurrentDirectory(unmanagedDllName))
        {
            return IntPtr.Zero; // use the default loader
        }

        var libraryPath = Path.Combine(Environment.CurrentDirectory, unmanagedDllName);
        return LoadUnmanagedDllFromPath(libraryPath);
    }
}
```

## Proposed API

```c#
namespace System.Runtime.Loader
{
    public abstract class AssemblyLoadContext
    {
        // Relevant existing members
        protected abstract Assembly Load(AssemblyName assemblyName);
        protected Assembly LoadFromAssemblyPath(string assemblyPath);
        protected virtual IntPtr LoadUnmanagedDll(String unmanagedDllName);

        // Proposed members
        protected IntPtr LoadUnmanagedDllFromPath(String unmanagedDllPath);
    }
}
```

### Usage and behavior
* `unmanagedDllPath` must be an absolute path to the library to load
* No changes are made to the specified search path or library name in `unmanagedDllPath` before attempting the load. For example, no prepending "lib" and no appending ".so". However, the system may make changes, for instance, LoadLibrary on Windows appends a ".dll" if an extension is not specified.
* `LoadUnmanagedDllFromPath` would try to load the library using default load flags, and upon success, would return the library handle (value returned by LoadLibrary/dlopen)
* `LoadUnmanagedDllFromPath` would throw an exception upon failure to load the library
* Upon a successful load, callers from LoadUnmanagedDll overrides are expected to return the library handle from LoadUnmanagedDll, since there is no equivalent of FreeLibrary/dlclose
* Upon returning a nonzero value from LoadUnmanagedDll, the loader would attempt to load the entry point from the library

### Exceptions
* `ArgumentNullException` - Self-explanatory
* `ArgumentException` - `unmanagedDllPath` is an empty string or a relative path
* The following exceptions are inherited by the default loader implementation:
  * `BadImageFormatException` - Windows only - Failed to load the library
  * `DllNotFoundException` - Did not find the library or failed to load the library
* Note that the default loader may also throw `EntryPointNotFoundException`. Since the entry point is loaded upon returning from `LoadUnmanagedDll`, a successful return from `LoadUnmanagedDll` may still be followed by this exception.

**Comment by kangaroo** [comment]
Comments: 

```
Upon a successful load, callers from LoadUnmanagedDll overrides are expected to return the library handle from LoadUnmanagedDll, since there is no equivalent of FreeLibrary/dlclose
```
Why?  I may have good reason t unload/dlclose a library when I'm done with it (although this also touches on collectible assembles I guess.

```
unmanagedDllPath must be an absolute path to the library to load
```

This code smells like we're leading to dll hell on linux.  Take a look at whats in a lib package versus a dev package.  Then look at 3 distros, and then look at the matrix of suck.

**Comment by janhenke** [comment]
> This code smells like we're leading to dll hell on linux. Take a look at whats in a lib package versus a dev package. Then look at 3 distros, and then look at the matrix of suck.

I absolutely second that. On Unix systems you would normally just provide the name of the library and a number of default locations are searched for a matching file. We should respect platforms default behaviour.

**Comment by OtherCrashOverride** [comment]
> No changes are made to the specified search path or library name in unmanagedDllPath before attempting the load. For example, no prepending "lib" and no appending ".so". However, the system may make changes, for instance, LoadLibrary on Windows appends a ".dll" if an extension is not specified.

Perhaps the contents of #930 should be reviewed.  The issue becomes more convoluted with all these "one-off" fixes that fail to take into account the "big picture"

I have been running a protoype of a fix for some months now and its performed remarkably well.  Based on that I will offer "lessons learned":
* IntPtr and LoadUnmanagedDLL is absolutely the wrong way to solve this.
* I ended up with an abstract base class NativeLibrary that encompasses the IntPtr, Free, and GetSymbolAddress (in addition to other things that are needed to fix the DllImport problem)
* PosixNativeLibrary, Win32NativeLibrary, OsxNativeLibrary, etc all derive from the base class above (NativeLibrary) and implement platform specific function.
* A factory pattern selects the correct platform abstraction to use at runtime transparent to the end user and NativeLibrary object is returned.

**Comment by kouvel** [comment]
>> Upon a successful load, callers from LoadUnmanagedDll overrides are expected to return the library handle from LoadUnmanagedDll, since there is no equivalent of FreeLibrary/dlclose

> @kangaroo: Why? I may have good reason t unload/dlclose a library when I'm done with it (although this also touches on collectible assembles I guess.

The lifetime would be managed by the runtime once the library handle is returned. If for some reason a library needs to be loaded and unloaded here, it would have to use P/Invoke.

@kangaroo and @janhenke - I agree this API doesn't help much for the use cases you mentioned, but it's not intended for that. Separate from this API, I could see a different API that may help there, perhaps something like `LoadUnmanagedDllFromName`, which could add the prefix and/or suffix and use the default search orders.

@OtherCrashOverride, I'm not intending to solve the whole dll mapping problem. The purpose is only to simplify some use cases, like overrides that would know the path to the library (for instance, relative to some app-specific path). P/Invoke will still be necessary for cases requiring more flexibility.

**Comment by OtherCrashOverride** [comment]
> I'm not intending to solve the whole dll mapping problem. The purpose is only to simplify some use cases

The point I wanted to make was that everyone is solving their own specific issue.  This means there are now multiple ways to deal with native libraries and multiple behaviors/patterns to go with each of them.  This results in a very poor cross-platform experience for both end users and developers.

I also realize that at this point it is necessary to do these things.  There should probably be some searchable "TODO/HACK" flag to place in the comments of these areas to make it easier to find them all later down the road.

**Comment by kouvel** [comment]
CC @terrajobst

**Comment by terrajobst** [comment]
Just follow up, this feature was [approved](https://github.com/dotnet/apireviews/tree/master/2015-09-22-misc#3054-assemblyloadcontextloadunmanageddllfrompath).
