### ISSUE TITLE
X509Certificate.CreateFromSignedFile doesn't work

### ISSUE THREAD

**Issue by filipnavara** [dotnet/corefx#30545]
The method is supposed to take an assembly file as an argument, unpack the Authenticode signature and get the certificate from it. The current implementation just blindly tries to open the file as a certificate file, which won't work.

Mono has some minimal implementation:

https://github.com/mono/mono/blob/05e8f2b8d73149e57dfbdbb4d126335a0e17a2bf/mcs/class/corlib/System.Security.Cryptography.X509Certificates/X509Certificate.cs#L69-L86
 
https://github.com/mono/mono/blob/05e8f2b8d73149e57dfbdbb4d126335a0e17a2bf/mcs/class/Mono.Security/Mono.Security.Authenticode/AuthenticodeDeformatter.cs

cc @bartonjs @steveharter

**Comment by bartonjs** [comment]
That may be what the method implies it does.  But the NetFX implementation says it just calls the X509Certificate ctor, which does the fuzzy match it does.

https://referencesource.microsoft.com/#mscorlib/system/security/cryptography/x509certificates/x509certificate.cs,1c912b1396897f74

If you just mean that it ultimately fails on Linux, then this is duplicate of #2910.

**Comment by filipnavara** [comment]
Thanks for clarifying the NetFX behaviour. It is not the same issue as #2910 because the failing case here are Authenticode signed executables. There are unit tests in Mono to cover it and it's actually used in the toolchain:

https://github.com/mono/mono/blob/0bcbe39b148bb498742fc68416f8293ccd350fb6/mcs/class/corlib/Test/System.Security.Cryptography.X509Certificates/X509SpcTest.cs#L1004-L1034

**Comment by bartonjs** [comment]
The authenticode test we have is covered under the same issue.

https://github.com/dotnet/corefx/blob/8ad2b10cff945e4428520c6932e8de499af2931b/src/System.Security.Cryptography.X509Certificates/tests/LoadFromFileTests.cs#L210-L220

**Comment by filipnavara** [comment]
Perfect, I will track the other issue then and close this one.
