### ISSUE TITLE
X509Certificate.GetName and GetIssuerName behaviour

### ISSUE THREAD

**Issue by filipnavara** [dotnet/corefx#30544]
On .NET Framework the `GetName` and `GetIssuerName` APIs of `X509Certificate` return the names in reverse order compared to the newer `Subject` and `Issuer` properties. .NET Core doesn't implement this distinction and I would like some further verification that this is intentional.

Mono unit tests:
```
Assert.AreEqual ("L=Internet, O=\"VeriSign, Inc.\", OU=VeriSign Class 1 CA - Individual Subscriber", x509.GetIssuerName (), "GetIssuerName");
Assert.AreEqual ("OU=VeriSign Class 1 CA - Individual Subscriber, O=\"VeriSign, Inc.\", L=Internet", x509.Issuer, "Issuer");

Assert.AreEqual ("L=Internet, O=\"VeriSign, Inc.\", OU=VeriSign Class 1 CA - Individual Subscriber, OU=\"www.verisign.com/repository/CPS Incorp. by Ref.,LIAB.LTD(c)96\", OU=Digital ID Class 1 - Netscape, CN=David T. Gray, E=david@formal.ie", x509.GetName (), "GetName");
Assert.AreEqual ("E=david@formal.ie, CN=David T. Gray, OU=Digital ID Class 1 - Netscape, OU=\"www.verisign.com/repository/CPS Incorp. by Ref.,LIAB.LTD(c)96\", OU=VeriSign Class 1 CA - Individual Subscriber, O=\"VeriSign, Inc.\", L=Internet", x509.Subject, "Subject");
```

cc @bartonjs

**Comment by bartonjs** [comment]
Yep, NetFx uses CERT_NAME_STR_REVERSE_FLAG for Subject and Issuer, and doesn't for the methods.  CoreFx has the methods return the properties.

The methods are marked Obsolete, but the fix should be easy enough.

**Comment by filipnavara** [comment]
I know it is not a big deal since both of the functions are deprecated, but I thought I would report it anyway. I am running the Mono unit tests against the CoreFX implementation as part of an effort to reuse more of the code.

**Comment by baulig** [comment]
We could also just do the same thing in Mono (see my PR about this: https://github.com/mono/mono/pull/9349) or is there a strong reason why we need to keep compatibility?

I started to cleanup some of Mono's certificate code to work towards using some of CoreFX's PAL.  We were previously handling the legacy behavior inside our platform layer, which I believe was creating unnecessary complication, so I cleaned that up.

**Comment by bartonjs** [comment]
It wasn't an intentional breaking change, and making it match NetFX / current-Mono would help in porting existing applications.  (Taking it as a breaking change now could hurt existing CoreFX applications, but since it's been Obsolete during the entirety of CoreFX no one really has an excuse to be calling it in Core :smile:)

**Comment by baulig** [comment]
Okay, thanks for the clarification - I thought it was intentional because it's already been Obsolete for so long.

Is there an easy way of converting the new (`X509Certificate.Subject`) format to the old one without using platform-specific code?
