### ISSUE TITLE
Stop rolling Jenkins runs for CoreFX

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#30558]
Now we removed the badges, they have no purpose. We should stop them.

@weshaggard could you please find the right person for this?

**Comment by danmosemsft** [comment]
We should do this as soon as possible, but it does not need to be in the 2.2 radar.

**Comment by danmosemsft** [comment]
@weshaggard are these still running? I don't have links to them anymore..

**Comment by weshaggard** [comment]
That is a good question. I'm not entirely sure how to check perhaps @mmitche can verify.

**Comment by ViktorHofer** [comment]
@danmosemsft don't we want any badges in readme anymore at all even with Azure DevOps?
@safern will assign you, hope that's fine.

**Comment by danmosemsft** [comment]
We definitely want badges. Until AZDO we had no way to get them back . I'd like a while set of them on the Readme.
