### ISSUE TITLE
System.Uri fails on long non ascii domains

### ISSUE THREAD

**Issue by xkrt** [dotnet/corefx#3055]
This domain in russian:

``` csharp
Console.WriteLine(new Uri(@"http://высококачественные-пиломатериалы.рф", UriKind.Absolute));
output: http:///
```

I start truncate domain from end:

``` csharp
Console.WriteLine(new Uri(@"http://высококачественные-пиломатериал.рф", UriKind.Absolute)); // still bad
output: http:///

Console.WriteLine(new Uri(@"http://высококачественные-пиломатериа.рф", UriKind.Absolute)); // remove one more char, ok
output: http://высококачественные-пиломатериа.рф/
```

`Uri.TryCreate` with schema `//` fails with `Index was outside the bounds of the array.`:

``` csharp
Uri uri;
Uri.TryCreate(@"//высококачественные-пиломатериалы.рф", UriKind.Absolute, out uri);
exception: Index was outside the bounds of the array.
```

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar

**Comment by CIPop** [comment]
/cc @SidharthNabar 

Thanks for reporting this @xkrt 
The behavior is the same in .Net Desktop: we need to fix these in both platforms.

**Comment by CIPop** [comment]
The code for Uri is not easy to read making this medium in complexity. This requires some investigation and adding extra testing, at least for the cases listed above.

**Comment by rmkerr** [comment]
Closing as this issue has been fixed in .NET Core 2.1 (PR #25993), and .NET Framework 4.7.2.
