### ISSUE TITLE
MD5.Create() fails on Linux/Mac (was: Windows interop getting called on Unix systems)

### ISSUE THREAD

**Issue by Grochni** [dotnet/corefx#3056]
When calling `Internal.NativeCrypto.Cng.Interop.BCryptOpenAlgorithmProvider` (e.g. when using `MD5.Create()`) on Unix systems the Windows Interop seems to be called. On both Ubuntu 14.04 and OSX I get `System.DllNotFoundException: Unable to load DLL 'BCrypt.dll'`.

**Comment by mellinoe** [comment]
How are you getting the crypto assembly you are using? We have platform-specific assemblies, but our NuGet package currently only contains the Windows version. If you want to run those outside of Windows for now, you will need to build the platform-specific assembly and deploy it yourself.

**Comment by Grochni** [comment]
I got them via NuGet, so i guess this is the cause, thank you. Is this information documented somewhere? If not, it probably would be worth to note it in the docs.

**Comment by mellinoe** [comment]
Hmm, I am not sure where this is documented currently. The documentation that we have in the repo here is mostly about actually building and running the source code in here, rather than about how to build a separate project and consume the libraries we build here, if that makes sense...

**Comment by mellinoe** [comment]
Oops, didn't mean to close this.

**Comment by Grochni** [comment]
That of course makes sence. But as I'm currently trying to consume the libraries it's  kind of hard for me to find the right docs in some cases and I'm all about spreading some information for other people using them.

**Comment by joshfree** [comment]
@bartonjs @chcosta

**Comment by bartonjs** [comment]
@Grochni are you still seeing problems like this one?  I just tried this out using a fairly recent build and things seemed happy to me:

```
jbarton@jsb-ubuntu2:~/playground/hmm$ dnx run
The current time is: 10/14/2015 08:00:23

     MD5: E5 6E 08 B8 53 D5 8B A5 EE 8D E5 54 C9 7F 91 E6
    SHA1: 08 B9 71 0B 00 93 04 2C 5C D8 3F B2 73 0C 83 A1 38 C9 15 32
  SHA256: E8 E9 3C F2 C6 48 3F F6 F5 DA 39 A4 37 58 30 B1 C5 AB 03 79 F3 CB 14 15 F1 8B 20 E7 3F 6E 8E CB
  SHA384: 01 F9 A4 C0 B9 A9 0D F0 EF F4 74 4D 65 FC E2 C5 45 AB F4 DF 90 62 05 0F C1 B0 4C BB 01 99 75 8C 95 E6 1C 00 1A 7C 77 78 AD 79 2F 22 3E 7A 5F F8
  SHA512: 3D 22 26 1C C7 CC 58 B4 0F D3 83 2F A9 C5 A0 1C 7F 4D E1 DA EB 93 FB C0 03 C0 BD 82 AC 72 77 12 DC 0F F3 48 CF 35 B9 8F 7F 2E 0F A4 96 92 C3 38 EE 2C 4C 07 F4 6F 0A 2D 6C A3 11 84 67 BF ED E0
jbarton@jsb-ubuntu2:~/playground/hmm$ dnvm list

Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
  *    1.0.0-rc1-15838      coreclr x64          linux
```

**Comment by bartonjs** [comment]
I believe the problem to be solved now that we have better cross-platform packaging support.  Having not heard anything to the contrary, closing this issue.  We'll reopen it if we need to.
