### ISSUE TITLE
Add MemoryExtensions.Trim methods for ReadOnlyMemory<char>

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#30592]
Most of the `ReadOnlySpan<char>`-based methods on `MemoryExtensions` work well for `ReadOnlyMemory<char>` as well, since it both exposes a `Span` property of type `ReadOnlySpan<char>` and is implicitly convertible to `ReadOnlySpan<char>`.  However, a few of the methods aren't fully usable, in particle the `Trim` overloads.  That's because unlike the other methods like `StartsWith`, `IndexOf`, etc., `Trim` returns a `ReadOnlySpan<char>`, which means you can't use it to trim a `ReadOnlyMemory<char>` back into a potentially shorter `ReadOnlyMemory<char>`.

Proposal:
Add `ReadOnlyMemory<char>`-based counterparts for the existing `ReadOnlySpan<char>`-based `Trim` methods:
```C#
namespace System
{
    public static class MemoryExtensions
    {
        public static ReadOnlyMemory<char> Trim(this ReadOnlyMemory<char> text);
        public static ReadOnlyMemory<char> Trim(this ReadOnlyMemory<char> text, char trimChar);
        public static ReadOnlyMemory<char> Trim(this ReadOnlyMemory<char> text, ReadOnlySpan<char> trimChars);

        public static ReadOnlyMemory<char> TrimStart(this ReadOnlyMemory<char> text);
        public static ReadOnlyMemory<char> TrimStart(this ReadOnlyMemory<char> text, char trimChar);
        public static ReadOnlyMemory<char> TrimStart(this ReadOnlyMemory<char> text, ReadOnlySpan<char> trimChars);

        public static ReadOnlyMemory<char> TrimEnd(this ReadOnlyMemory<char> text);
        public static ReadOnlyMemory<char> TrimEnd(this ReadOnlyMemory<char> text, char trimChar);
        public static ReadOnlyMemory<char> TrimEnd(this ReadOnlyMemory<char> text, ReadOnlySpan<char> trimChars);
    }
}
```

A couple of notes:
- The span-based overloads call the first argument `span`.  I've named it here `text`, but we could choose a different name.
- Technically we could also benefit from variants of these for both `Span<char>` and `Memory<char>`, since we lack full-fidelity versions for those just as we do today for `ReadOnlyMemory<char>`.  However, there's significantly less need for those methods, as the primary use case here is for processing slices of strings, with which you'd have either a `ReadOnlyMemory<char>` or a `ReadOnlySpan<char>`.

cc: @ahsonkhan, @GrabYourPitchforks

**Comment by terrajobst** [comment]
It seems we don't have any string-like extension methods for `Memory<char>`. I'm not opposed to providing those, but it seems odd to just do them for `Trim`. We should make them consistent between `Span<char>` and `Memory<chan>` unless specific operations don't make sense. But picking and choosing seems like the wrong approach.

**Comment by stephentoub** [comment]
@terrajobst, the others all work with memory (as static calls) because they accept span. Trim is different, because it also needs to return a memory, and thus the existing span-based methods don't work with it. So it is a special case to be picked and chosen.

**Comment by ahsonkhan** [comment]
We generally recommend the user cache the span by calling Memory.Span once, and then operating on the span directly as much as possible. The cost of calling Memory.Span is non-negligible. Adding convenience, string-like APIs on Memory would increase the overall calls to Memory.Span (hidden from the user, as it would be how the APIs would be implemented under the covers) and would incur performance penalty that could be avoided, counter to our guidelines.

I agree that having to get spans from memory may not be as convenient, but it is a trade-off between performance and usability.

**Comment by ahsonkhan** [comment]
For reference: Based on the discussion for the generic Trim APIs [here](https://github.com/dotnet/corefx/issues/31011#issuecomment-442187755), we wouldn't add all of the suggested char-specific overloads.

We should only add the following since they have char-specific white-space trimming semantics:
```C#
        public static ReadOnlyMemory<char> Trim(this ReadOnlyMemory<char> text);

        public static ReadOnlyMemory<char> TrimStart(this ReadOnlyMemory<char> text);

        public static ReadOnlyMemory<char> TrimEnd(this ReadOnlyMemory<char> text);
```

The others will be covered by the generic Trim APIs being added as part of https://github.com/dotnet/corefx/issues/31011

**Comment by ahsonkhan** [comment]
See https://github.com/dotnet/corefx/issues/31011

Fixed in https://github.com/dotnet/coreclr/pull/22798 / https://github.com/dotnet/corefx/pull/35576

Thanks @grant-d
