### ISSUE TITLE
Question about AuthenticationHeaderValue

### ISSUE THREAD

**Issue by shortstuffsushi** [dotnet/corefx#30604]
This was a while back, so hopefully I remember the details right. I was working on a project that was making requests via HttpClient to a remote API server that we had no control over. The server used (their own version of) oauth, and expected the Authentication header to be simple `Authentication: sometokenstring` - no scheme. As far as I can tell, this isn't easily doable using the `AuthenticationHeaderValue`, as the scheme is required. I ended up using `Request.Headers.TryAddWithoutValidation` as a work around.

My question is, is there a way to use the `AuthenticationHeaderValue` in my scenario, and if not, is that something that would be of interest to add to the project?

**Comment by davidsh** [comment]
Thanks for your question!

For non-standard uses of headers, the recommended approach is to use the [TryAddWithoutValidation](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.httpheaders.tryaddwithoutvalidation?view=netcore-2.1#System_Net_Http_Headers_HttpHeaders_TryAddWithoutValidation_System_String_System_String_) APIs as you indicated.  So, there really isn't any need to add new APIs for these scenarios.
