### ISSUE TITLE
Why is System.ComponentModel.Composition not supported on uap?

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#30601]
Is there a specific reason that we don't support MEF1 in uap? We currently forward to the inbox assembly when using the nuget package: https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Composition/pkg/System.ComponentModel.Composition.pkgproj#L12

But the inbox assembly seems to just be a turd assembly. I can't reference any types inside a RS4 application neither with or without the nuget package.

cc @safern

**Comment by jkotas** [comment]
It has heavy dependency on reflection emit.

**Comment by ViktorHofer** [comment]
thanks!
