### ISSUE TITLE
AWS Lambda Connect to Redshift DB using ODBC Connection

### ISSUE THREAD

**Issue by digambar-malla** [dotnet/corefx#30602]
I hope will get some help.
I am trying to connect to RedShift DB Using AWS Lambda from .Net Core 2.0 App.

I have included System.Data.Odbc in app

`string connString = "Driver={Amazon Redshift (x64)};" + String.Format("Server={0};Database={1};" + "UID={2};PWD={3};Port={4};SSL=true;Sslmode=Require", RedShiftServer, RedShiftDBName, RedShiftUsername,RedShiftPassword, RedShiftPort); OdbcConnection conn = new OdbcConnection(connString); conn.Open();`

But I am not able to connect to RedShift DB (Unable to Open the connection) after deployment to Lambda Function.
I am getting Bellow Error.

> "Dependency unixODBC with minimum version 2.3.1 is required. Unable to load DLL 'libodbc.so.2': The specified module or one of its dependencies could not be found.

how to solve it using this Odbc connection ?

**Comment by TheMacNerd** [comment]
Perhaps one of these could solve your problem:

https://stackoverflow.com/questions/48760630/aws-lambda-connect-to-redshift-db-using-odbc-connection
https://stackoverflow.com/questions/48760630/aws-lambda-connect-to-redshift-db-using-odbc-connection?rq=1

**Comment by David-Engel** [comment]
Closing this issue assuming the above answer was sufficient. The referenced ODBC driver must be installed along with its dependencies (unixODBC) on the system running the application.
