### ISSUE TITLE
Console.KeyAvailable echoes the typed key on mac

### ISSUE THREAD

**Issue by bleroy** [dotnet/corefx#30610]
Repro steps:

Run this:
```csharp
static void Main (string [] args)
{
	Console.WriteLine ("Waiting for a key to be pressed.");
	while (!Console.KeyAvailable) Thread.Sleep (10);
	Console.WriteLine ("A key was pressed");
	var key = Console.ReadKey (true);
	Console.WriteLine ($"Read key {key.KeyChar}.");
	Console.ReadKey (true);
}
```

and press a key.

On Windows, as expected, this is the output:

```
Waiting for a key to be pressed.
A key was pressed
Read key a.
```

On a mac, you get this:

```
Waiting for a key to be pressed.
aA key was pressed
Read key a.
```

**Comment by stephentoub** [comment]
This is the same as https://github.com/dotnet/corefx/issues/25916 and other similar issues that have been opened.

Unix is different from Windows in how input is handled: Windows doesn't echo until the character is read/consumed by the application, at which point the application has a choice of whether to echo or not; in contrast, Unix echos immediately on typing, unless the terminal has been configured to not echo.  We initially implemented Console to always disable echo, but that caused problems when a process launched one or more child processes, and based on feedback we switched to a model where we temporarily disable echoing while performing some Console.* operation... but that means there's a race condition, where if typing happens before the Console.* operation, the typing will be visible.

**Comment by bleroy** [comment]
Ew. What's a workaround for those of us who don't care or don't have child processes that should echo?

**Comment by stephentoub** [comment]
Other than P/Invoking to the terminal to force it not to echo, I don't know of one.

**Comment by bleroy** [comment]
Thanks, Stephen, I think I'll just have to avoid using `KeyAvailable` altogether (since each call seems to potentially trigger an echo even for a single keystroke), never pass in `true` into `ReadKey` (it's a lie), and just limit to scenarios where echoing is fine. I think I can make it work in my scenario, but it looks like those APIs could potentially be deprecated since they can't consistently work cross-plat. Annotating the docs could also help others hitting this.

I appreciate the help and explanation.
