### ISSUE TITLE
 'EnumerationOptions' does not contain a definition for 'MatchCasing'

### ISSUE THREAD

**Issue by iSazonov** [dotnet/corefx#30626]
Please see 
https://github.com/PowerShell/PowerShell/pull/7129
https://travis-ci.org/PowerShell/PowerShell/jobs/395523693
```
843/home/travis/build/PowerShell/PowerShell/src/System.Management.Automation/help/UpdatableHelpSystem.cs(1650,106): error CS0117: 'EnumerationOptions' does not contain a definition for 'MatchCasing' [/home/travis/build/PowerShell/PowerShell/src/System.Management.Automation/System.Management.Automation.csproj]
```

Seems it is regression in .Net Core 2.1.1.

/cc @JeremyKuhne

**Comment by jkotas** [comment]
I have double-checked that these are present in .NET Core 2.1.1 on Linux. Also, I have cloned your branch and I am not hitting the build error that you are see. Looks like environment problem. Have you checked that the CI machine is not running stale preview bits?

**Comment by iSazonov** [comment]
Before June 22 the code was compiled well.
After June 22 the problem arised on CI Travis. Then I checked _CI Appveyor (Windows)_ - the problem arised there too. So I decided to open the issue.

**Comment by iSazonov** [comment]
I added `dotnet --info` in CI log.
https://travis-ci.org/PowerShell/PowerShell/jobs/396243951#L801
```
dotnet --info: 
.NET Core SDK (reflecting any global.json):  Version:   2.1.300  Commit:    adab45bf0c  Runtime Environment:  OS Name:     ubuntu  OS Version:  14.04  OS Platform: Linux  RID:         ubuntu.14.04-x64  Base Path:   /home/travis/.dotnet/sdk/2.1.300/  Host (useful for support):   Version: 2.1.0   Commit:  caa7b7e2ba  .NET Core SDKs installed:   2.1.300 [/home/travis/.dotnet/sdk]  .NET Core runtimes installed:   Microsoft.AspNetCore.All 2.1.0 [/home/travis/.dotnet/shared/Microsoft.AspNetCore.All]   Microsoft.AspNetCore.App 2.1.0 [/home/travis/.dotnet/shared/Microsoft.AspNetCore.App]   Microsoft.NETCore.App 2.1.0 [/home/travis/.dotnet/shared/Microsoft.NETCore.App]  To install additional .NET Core runtimes or SDKs:   https://aka.ms/dotnet-download
```

**Comment by iSazonov** [comment]
The same on 2.1.301

**Comment by iSazonov** [comment]
I tested locally all versions - msi and zip packages - 2.1.300 and 2.1.301 and the project is compiled well.
So problem is somewhere else.

**Comment by iSazonov** [comment]
From @daxian-dbw 
>this is probably because the compiler resolves EnumerationOptions to System.Management.EnumerationOptions instead of System.IO.EnumerationOptions. Reference to the package System.Management was added to System.Management.Automation project some time back.
You can use the full type name System.IO.EnumerationOptions and it should work.

This workaround works. 

Is it possible rename new type `System.IO.EnumerationOptions` to `System.IO.FileEnumerationOptions` or similar conflicts are allowed?

**Comment by jkotas** [comment]
This API shipped already. It is not possible to rename it.

Conflicts like this are not completely avoidable. It is not possible to ensure that all libraries on the planet use unique identifiers. Fully qualified namespaces are the suggested workaround for them. 

It is odd that you have seen the problem on some machines only.

**Comment by iSazonov** [comment]
@jkotas Thanks!

>It is odd that you have seen the problem on some machines only.

The only guess is that MSBiuld compiles PowerShell Core projects in parallel and this can vary on different computers.
