### ISSUE TITLE
Equals and GetHashcode methods are overridden for multiple Classes in System.IO

### ISSUE THREAD

**Issue by TheMinefighter** [dotnet/corefx#30627]
The Equals and GetHashCode methods are not overridden by

- System.IO.DriveInfo
- System.IO.DirectoryInfo
- System.IO.FileInfo

In each of the classes, the effective comparison would only have to compare the (private) _name field. Implementation example as follows:

```
public override bool Equals(object obj) {
	if (ReferenceEquals(null, obj)) {
		return false;
	}

	if (ReferenceEquals(this, obj)) {
		return true;
	}

	if (obj.GetType() != this.GetType()) {
		return false;
	}

	return Equals((DriveInfo) obj);
}

private /* Can be made public or protected */ bool Equals(DriveInfo other) => _name == other._name;
```
An implemantation of the IEquatable<> interface would optionally be possible.

The GetHashCode method could be implemented as follows: 
`public override int GetHashCode() => _name.GetHashCode();`

**Comment by ViktorHofer** [comment]
Not just in System.IO. There are multiple types in the BCL that don't override Equals and GetHashCode ...

**Comment by jkotas** [comment]
Changing equality behavior for existing types would be a breaking change.

**Comment by TheMinefighter** [comment]
@jkotas If you want to know if two objects references are equal you usually use object.ReferenceEquals or sometimes the == operator. https://msdn.microsoft.com/en-us/library/bsc2ak47(v=vs.110).aspx states that the .Equals method "Determines whether the specified object is equal to the current object" (that's also stated in the DriveInfo page: https://msdn.microsoft.com/en-us/library/system.io.driveinfo(v=vs.110).aspx ) if (new DriveInfo("C").Equals ( new DriveInfo("C"))) is false we are with the logic at the level of Javascript. There is absolutely no excuse for not changing that (except for "We want to be as unlogical as Javascript!").

**Comment by jkotas** [comment]
@TheMinefighter  I have just stated the fact based on definition of the breaking change. You can read more about how the breaking change is defined in https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-changes.md .

I agree with you that there are places in the framework that do not have logical behavior. However, we do not just blindly go a fix them. We apply the risk-benefit analysis to any such changes as described in the doc.

**Comment by TheMinefighter** [comment]
@jkotas I understand that that would be a breaking change. I want to note that that change shouldn't affect anybody following common practices. If that is a dealbreaker anyway it should be considered to mark these Equality comparisons, which do not do what the user expects explicitly in the documentation.

**Comment by jkotas** [comment]
> anybody following common practices

The common practice is to check what the framework type does and then code to that behavior. For example, I can imagine somebody can have written code like this:

```csharp
class Tracker
{
    static void Main()
    {
       Dictionary<object, Tracker> dict = new Dictionary<object, Tracker>();
       dict.Add(new DriveInfo("C"), new Tracker());
       dict.Add(new DriveInfo("C"), new Tracker());
    }
}
```

The real world version of this would have several abstractions in it. It would not be as straightforward as this.

**Comment by JeremyKuhne** [comment]
We can't change this unfortunately as it would cause pretty big breaks (as pointed out). You can create a custom comparer (`IEqualityComparer<DriveInfo>`) if you want to get custom comparison in `Dictionary<TKey, TValue>`, etc.
