### ISSUE TITLE
System.Memory when added to .net 4.6.1 project brings lots of dependecies

### ISSUE THREAD

**Issue by Denterl** [dotnet/corefx#30638]
Hi!

I am trying to use spans in library which will be used from .net 4.6.1 and .net core. For that it is required to add System.Memory (https://www.nuget.org/packages/System.Memory/4.5.1), which supports .net 4.6.1 according to NuGet and have the following dependencies: https://prnt.sc/jz0f30

However, after adding this lib to the project I see more references than expected (like System.Net.Http of version 4.2.0.0 etc.): https://prnt.sc/jz0b1w

Moreover, after building the project contains even more dependencies: http://prntscr.com/jz0gdo

Could you please explain why that happens? The problem is all those dependencies break the solution based on .net 4.6.1 to which I am trying to add this feature.

Thank you!

**Comment by joshfree** [comment]
@joperezr @ahsonkhan

**Comment by ahsonkhan** [comment]
cc @ericstj, who worked on package dependency related issues: https://github.com/dotnet/corefx/issues/29149 / https://github.com/dotnet/buildtools/pull/2009

**Comment by ericstj** [comment]
System.Memory is a netstandard2.0-based library.  So when you reference it on net461 it brings in the netstandard2.0 support libraries on net461.  These won't be brought in on net471 and later where netstandard2.0 support is *inbox*.

@ahsonkhan if you wanted to avoid this you could cross-compile System.Memory for net461, and ensure any of its dependencies also cross-compiled for net461.  This would ensure that the netstandard support libs wouldn't be brought in.

**Comment by Denterl** [comment]
Thank you, @ericstj .
