### ISSUE TITLE
IList<T> should implement IReadOnlyList<T> and also an IReadOnyList should exist

### ISSUE THREAD

**Issue by msedi** [dotnet/corefx#30637]
Currently only List implements the IReadOnlyList, but IList does not implement IReadOnlyList. This is a problem in many cases where only IList is visible on a class and not the actual list. In some situations I have an IList as class properties, and some classes I have need to take a IReadOnlyList.

Since the IList currently does not "derive" from IReadOnlyList this is often causing problems with the assignment.

Also it would be helpful to have the analogon of a IReadOnlyList as this is the case with IList.
I had some severe problems by using an IReadOnlyList where the contents of the List have been readonly structs.

**Comment by GalaxiaGuy** [comment]
This is the reason why `IList<T>` does not implement `IReadOnlyList<T>`:

https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/2845892-make-ilist-t-inherited-from-ireadonlylist-t

**Comment by msedi** [comment]
@GalaxiaGuy : I understand some of the fears that it might break something. But for those who implement the List<T> could take care of that the IReadOnlyList<T> and IList<T> have explicit or implicit Count and that both are identical. What I maybe understand is that some guys have already derived from IList<T> and this would now break their code.

In the end IReadOnlyList should have existed directly on the beginning, now this is somehow a bad design. Since the collections/lists are such an basic ingredient there seems to be too much "design flaws" as you can see with the Collection<T> which is somehow a list.... so some derive from Collection<T> and some derive from List<T>

**Comment by Joe4evr** [comment]
@msedi Minor annoyance: You were already told #5489 exists, so you should've just gone to that thread. Opening duplicate issues doesn't help anybody.

**Comment by msedi** [comment]
@Joe4evr: You are right. I already closed it.
