### ISSUE TITLE
Add SpanExtensions.LastIndexOf StringComparison overload

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#30649]
We added LastIndexOf extension methods with https://github.com/dotnet/corefx/issues/24839 but omitted the StringComparison overload which is existent on string and the IndexOf extension method.

```csharp
public static int LastIndexOf(this ReadOnlySpan<char> span, ReadOnlySpan<char> value, StringComparison comparisonType) { throw null; }
```

Usage: Regex

**Comment by ahsonkhan** [comment]
We should match the IndexOf signature:
```C#
public static int IndexOf(this ReadOnlySpan<char> span, ReadOnlySpan<char> value, StringComparison comparisonType) { throw null; }
```
i.e.
1) First argument should be ReadOnlySpan, not Span.
2) The method isn't generic (char-specific), so we don't need the constraint on T.

**Comment by ViktorHofer** [comment]
Right, I just copied it blindly. Thanks, updated the initial post.

**Comment by weshaggard** [comment]
As a follow-up do we need these on the other similar APIs as well. IndexOfAny, LastIndexOfAny. It looks like those are also not on string but it would seem that for consistency they might be interesting as well.
