### ISSUE TITLE
DefaultValueAttribute doesn't use TypeConverter

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#30648]
In desktop DefaultValueAttribute would use TypeDesicriptor/TypeConverter to try and convert a string to a type: https://referencesource.microsoft.com/#System/compmod/system/componentmodel/DefaultValueAttribute.cs,b956ede3a6b29f1f,references

In Core we are not doing this: https://github.com/dotnet/coreclr/blob/85374ceaed177f71472cc4c23c69daf7402e5048/src/System.Private.CoreLib/shared/System/ComponentModel/DefaultValueAttribute.cs#L38-L51

We should add back the call to TypeConverter as an ultimate fallback, where we use lightup to load it.  See https://devdiv.visualstudio.com/DevDiv/_git/DotNet-CoreCLR-Trusted/commit/90f7bf708e4a23f4f2096a847a820d75bf94aa2d?refName=refs%2Fheads%2Fericstj%2Fadd.back.exeperiment.

I suspect this will be needed for WinForms work. /cc @Tanya-Solyanik   I ran into in some application code I was porting where the app was explicitly using DefaultValueAttribute itself.

**Comment by MarcoRossignoli** [comment]
> We should add back the call to TypeConverter as an ultimate fallback, where we use lightup to load it. See https://devdiv.visualstudio.com/DevDiv/_git/DotNet-CoreCLR-Trusted/commit/90f7bf708e4a23f4f2096a847a820d75bf94aa2d?refName=refs%2Fheads%2Fericstj%2Fadd.back.exeperiment.

could you "gist" this(link is internal)?I could help if i understand well. Do you mean add condition `type.Module == typeof(string).Module` to current fallback(else) and as new fallback use ` this.value = TypeDescriptor.GetConverter(type).ConvertFromInvariantString(value);`?

**Comment by ericstj** [comment]
Yes, that's what I was referring to, though we can't call typeconverter directly.

Here's what I did in that internal commit: https://github.com/ericstj/coreclr/commit/17ac7bed928358e1f14924f61349e6209a6d01fc

**Comment by Anipik** [comment]
@MarcoRossignoli are you planning to work on this ?

**Comment by MarcoRossignoli** [comment]
@Anipik if It isn't too urgent i could try a PR!Feel free to work on it if you have to!

**Comment by MarcoRossignoli** [comment]
> Yes, that's what I was referring to, though we can't call typeconverter directly.

Only to be sure to understand...because TypeDescriptor/TypeConverter are on corefx codebase?If so do we need to move "classes" to coreclr, in past i asked and answer was "we move to coreclr if we need".

/cc @jkotas

**Comment by jkotas** [comment]
> If so do we need to move "classes" to coreclr, in past i asked and answer was "we move to coreclr if we need"

There are exceptions to this rule when the the closure of types that would need to be moved is large like in this case. We make the call using reflection like in the Eric's prototype.
