### ISSUE TITLE
Websockets: Server doesnt realize when a client is disconnected and keeps connection as open

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#30668]
_From @agonzalezm on June 26, 2018 8:25_

I have websocket server/clientapp  that works perfectly in net core 2.0 but after updating project to net core 2.1 the server doesnt realize when a client is disconnected so it keeps waiting for ever, while debugging this code although client got disconnected the server reports the websocket connection as OPEN. Any idea what has changed or how to make this work in 2.1?

```
System.Net.WebSockets;


var ct = context.RequestAborted;
WebSocketReceiveResult result = await webSocket.ReceiveAsync(new ArraySegment<byte>(buffer), ct);
while (!result.CloseStatus.HasValue)
{
   buffer = new byte[receiveChunkSize];
   result = await webSocket.ReceiveAsync(new ArraySegment<byte>(buffer), ct);
   ManageMessage(jobId, buffer);
   buffer = null;
}
await webSocket.CloseAsync(result.CloseStatus.Value, result.CloseStatusDescription, ct);
```

_Copied from original issue: dotnet/coreclr#18646_

**Comment by davidsh** [comment]
>I have websocket server/clientapp that works perfectly in net core 2.0 but after updating project to net core 2.1 the server doesnt realize when a client is disconnected so it keeps waiting for ever, while debugging this code although client got disconnected the server reports the websocket connection as OPEN.

@agonzalezm
What kind of "server" is this?  Is it using ASP.NET Core?  This issue might need to be moved to the asp.net core repo.

**Comment by agonzalezm** [comment]
yes server side is asp.net core 2.1 application.

**Comment by karelz** [comment]
@agonzalezm can you please try 2.0 client against 2.1 server and then 2.1 client against 2.0 server? It will tell us which part (client vs. server) is broken. Thanks!

**Comment by agonzalezm** [comment]
I already tried that and it is the 2.1 websocket server what is broken.

**Comment by karelz** [comment]
Do you have a repro?
We should probable move it to ASP.NET repo (unless you know it is a bug in the code they use from us ...)

**Comment by karelz** [comment]
Can you share a repro then? We can't do much without it.

**Comment by davidsh** [comment]
@agonzalezm 

We are unable to diagnose this without a repro solution that contains the sample code for the server and client.  Closing this issue for now. 

If this is still a problem, please attach a repro that we can run to troubleshoot the problem.  Then we can reopen this issue.  Thanks!
