### ISSUE TITLE
ConnectHelper.ConnectEventArgs shouldn't capture AsyncLocals

### ISSUE THREAD

**Issue by smbecker** [dotnet/corefx#30670]
I am still working on a minimal repro but I am running into cases where using the new `SocketsHttpHandler` is causing `AsyncLocal` values to be captured and cached in [s_connectEventArgs](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs#L20) causing those `AsyncLocal` values to live forever. At the moment, I have worked around the issue by calling `ExecutionContext.SuppressFlow` prior to making any calls to the `HttpClient` but this doesn't feel like the right solution. Perhaps the flow suppression should be moved to the `ConnectHelper`?

**Comment by stephentoub** [comment]
Yeah, I see how this can happen.  SocketAsyncEventArgs holds onto the captured ExecutionContext.

We should probably fix it so it doesn't, and then this issue just goes away (along with other cases where SAEA is cached, which is common).  If for some reason we can't do that, then suppressing flow in ConnectHelper is a good workaround.

**Comment by smbecker** [comment]
What are the best practices for using `ExecutionContext.SuppressFlow` across task boundaries? I am trying to follow some of the patterns I have seen in [other pull requests](https://github.com/dotnet/corefx/pull/26077/files) but none of those cross task boundaries. The problem is that when I get to `ExecutionContext.RestoreFlow`, it says that the flow is not suppressed. However, if I try to use `AsyncFlowControl.Undo`, this is breaking something else within my application. So far the only thing that works is the following:

```c#
var restoreFlow = false;
try {
	if (!ExecutionContext.IsFlowSuppressed()) {
		ExecutionContext.SuppressFlow();
		restoreFlow = true;
	}
	...await some async operation
} finally {
	if (restoreFlow && ExecutionContext.IsFlowSuppressed()) {
		ExecutionContext.RestoreFlow();
	}
}
```

but this feels wrong since in most cases, `ExecutionContext.IsFlowSuppressed()` returns `false`. Any other ideas?

**Comment by smbecker** [comment]
From what I can find, this real answer is to not cross task boundaries. It seems that the `ExecutionContext` is captured as soon as the task is created meaning that the following would be more appropriate.

```c#
var restoreFlow = false;
try {
	if (!ExecutionContext.IsFlowSuppressed()) {
		ExecutionContext.SuppressFlow();
		restoreFlow = true;
	}
	return CreateTask();
} finally {
	if (restoreFlow) {
		ExecutionContext.RestoreFlow();
	}
}
```

Is that correct?

**Comment by smbecker** [comment]
Until a fix is released, I am using the following handler in front of the `HttpClientHandler` that seems to prevent leaking `AsyncLocal` values when using `SocketsHttpHandler`.

```c#
public class SuppressExecutionContextFlowHandler : DelegatingHandler
{
	public SuppressExecutionContextFlowHandler() {
	}

	public SuppressExecutionContextFlowHandler(HttpMessageHandler innerHandler)
		: base(innerHandler) {
	}

	protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) {
		var restoreFlow = false;
		if (!ExecutionContext.IsFlowSuppressed()) {
			ExecutionContext.SuppressFlow();
			restoreFlow = true;
		}

		try {
			return base.SendAsync(request, cancellationToken);
		} finally {
			if (restoreFlow) {
				ExecutionContext.RestoreFlow();
			}
		}
	}
}
```
