### ISSUE TITLE
Add Public API Marshal.GetExceptionPointers 

### ISSUE THREAD

**Issue by luqunl** [dotnet/corefx#30677]
Marshal.GetExceptionPointers  is supported in [Desktop.](https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.marshal.getexceptionpointers(v=vs.110).aspx) As mentioned in https://github.com/dotnet/coreclr/pull/11125, debugger folks need this to capture exceptions in dumps, but https://github.com/dotnet/coreclr/pull/11125 implements this function but forgot to expose it.

### Rationale and Usage
Debugger folks need this API to capture exception.
Eric also find this API is used when porting desktop app into .Net Core App.
 
### Proposed API
class Marshal
{
public static IntPtr GetExceptionPointers();
}

### Details:

- [As mentioned in MSDN](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getexceptionpointers?view=netframework-4.7.2),
`GetExceptionPointers` is exposed for compiler support of structured exception handling (SEH) only.

How about  its behavior on non-windows platforms? NotSupportedException?

### Todo:

- Update [MSDN doc](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getexceptionpointers?view=netframework-4.7.2)

- Add a smoking testcase

**Comment by AaronRobinsonMSFT** [comment]
LGTM. Is there a way to indicate a function is only supported on a specific platform? Do we have a Roslyn analyzer or something that could help porters of code determine a function won't work prior to getting an unexpected exception?

**Comment by jkotas** [comment]
> Do we have a Roslyn analyzer or something that could help porters of code determine a function won't work prior to getting an unexpected exception?

https://github.com/dotnet/platform-compat

**Comment by jkotas** [comment]
> How about its behavior on non-windows platforms?

There is nothing fundamental preventing supporting this API on non-windows platforms. I believe that it will work fine on CoreCLR Unix today.

When the exception pointers are not available, the API should return NULL. I do not think it should throw.

**Comment by AaronRobinsonMSFT** [comment]
> When the exception pointers are not available, the API should return NULL. I do not think it should throw.

@jkotas I was going to suggest this, but does `NULL` mean something. What I am getting at is the idea that is `NULL` already a possible value? And based on the [code](https://github.com/dotnet/coreclr/blob/master/src/vm/comutilnative.cpp#L621-L637) it is, so I agree that throwing an exception probably isn't the right thing here.

**Comment by luqunl** [comment]
> Is there a way to indicate a function is only supported on a specific platform? 

Yes, These Marshal COM API are implemented in this way. see https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/src/System/Runtime/InteropServices/NonPortable.cs

> I believe that it will work fine on CoreCLR Unix today.

I will add a smoking testcase for this API.

> And based on the code it is, so I agree that throwing an exception probably isn't the right thing here.

If we were going to throw NotSupportedException/PlatformNotSupportedException, We will throw before this code.

> I would suggest that the documentation should be updated to indicate the exception in question is not a managed exception but a potentially unrelated native exception and on Windows an example of that is when SEH is enabled.

Yes, We need to update doc after this work is close to finish.

**Comment by terrajobst** [comment]
Agree with @jkotas  -- we should just return `null` as that's a valid answer even on Windows. Normally, if we cannot implement an API we'd throw `PlatformNotSupportedException` rather than `NotSupportedException`.

Looks good as proposed.
