### ISSUE TITLE
GetAllNetworkInterfaces STILL NotImplemented

### ISSUE THREAD

**Issue by PeterWone** [dotnet/corefx#30687]
Two years on and 2.1 is out there. But issues detailed in #9675 _still_ have not been addressed.

#9675 is marked as an enhancement. I find that astonishing. The documentation says it works, and it doesn't. That's a bug, and a serious one if you need to enumerate interfaces.

One of the responses to #9675 suggests we use [Windows.Networking.Connectivity.NetworkInformation](https://msdn.microsoft.com/en-us/library/windows/apps/windows.networking.connectivity.networkinformation.aspx) but this was not a fruitful line of investigation.

Nobody expects you to do everything at once, but this is not something that can be ignored. If it were something higher level I might do a PR and fix it myself, but the low level network stuff is out of my league. I wouldn't be so bent out of shape over this if I hadn't discovered this was reported two years ago and then closed without correction.

If there's a NEW AND IMPROVED way then maybe the NotImplemented message could mention it.

**Comment by jkotas** [comment]
This was implemented 1 year ago by #21486. The fix is included in latest .NET Native for UWP. Please make sure that your project is targeting most recent version of .NET Native for UWP.

**Comment by jkotas** [comment]
https://github.com/Microsoft/dotnet/blob/master/releases/UWP/README.md

**Comment by PeterWone** [comment]
In that case my humble apologies. 

I encountered the problem in a project created using the UWP application template installed with Visual Studio 2017. I have applied all VS2017 updates.

I will now thoroughly read the documentation I have referenced. Should I bring this to the attention of the Visual Studio team?

**Comment by jkotas** [comment]
The new UWP project template has `Minumum Version` drop-down that affects the framework version used. Currently, this drop-down defaults to a version that does not have this fix. "Which version should I use?" link next to it explains the differences between different versions.

If you have suggestions on how to make this better, please do submit feedback for the Visual Studio team.

**Comment by PeterWone** [comment]
I may do that. For some scenarios, such as that from which you have just rescued me, the defaults are broken. A counter-argument is that mine is an edge case, but people tend to remember (and report) only the failures.

Thank you for responding so helpfully.

**Comment by PeterWone** [comment]
Chaps, I'm still seeing this on WinIoT. Have the pertinent changes made it into an update people should be installing on WinIoT?

**Comment by jkotas** [comment]
You should get the fix if you use latest WinIoT (Windows 10 April 2018 Update - https://www.microsoft.com/en-us/software-download/windows10iotcore) and .NET Native (.NET Native 2.1 - https://github.com/Microsoft/dotnet/blob/master/releases/UWP/README.md).
