### ISSUE TITLE
Is the corefx repo or the dotnet org a good place for key community projects?

### ISSUE THREAD

**Issue by richlander** [dotnet/corefx#307]
Forked from #294.

from @n8ohu - 
> I am working on uses a C# wrapper around a cross-platform C library and it would, in my opinion, be  beneficial to other developers if it was part of the core;

There is really a spectrum of .NET libraries, with one end point being the official corefx distribution and the other a weekend project never to be touched again. What you are proposing is much closer to the former. I think your base question is whether corefx or a peer repo is appropriate for key community-owned projects. Your scenario is C# wrappers over native libraries, but it could also be a pure managed library, too.

We are considering a similar plan for our own libraries that don't fit or don't fit yet in corefx. We can and should include community libraries in that thinking. The Mono org seems to embrace community libraries that have broad applicability. We should take some inspiration from that.

It's always a fine idea to host a library out of your own GitHub account. At the same time, we are intending the dotnet org to be a center of gravity for .NET library development. That's why we put the corefx repo there (and same will be true for the coreclr one) instead of the Microsoft org. It's likely the case that discoverability will be better in the dotnet org than an arbitrary personal repo.

What do you think?

**Comment by terrajobst** [comment]
We'd most likely not add those type of projects to the `corefx` repo. However, they'd be good candidates for the .NET Foundation and thus could be added to the `dotnet` organization.

If you're interested, shoot us an email at contact@dotnetfoundation.org.
