### ISSUE TITLE
REST API which should support multi target framework(.net 472 and .net core)

### ISSUE THREAD

**Issue by ircaxn** [dotnet/corefx#30708]
I need to create a REST API which should support multi target frameworks(.Net Framework 4.7.2 and .Net Core 2.1) as it has dependencies with other multi targeted libraries and to serve different clients. I created a self hosted API which targets both 472 and .net core frameworks and i created the Controller using the compiler directives as below, so that when it runs on .net full framework this would act as Web API and when it runs on .Net Core this would act as Mvc API:

#if NETCOREAPP2_1
    [ApiController]
    public class MyController : ControllerBase
#else
    public class MyController : ApiController
#endif
    {
    }

and the return type of API methods also be varied to support different frameworks and it is like,
#if !NETCOREAPP2_1
        public IHttpActionResult Score()
        #else
        public IActionResult Score()
        #endif
        {
            return Ok();
        }

This way of building API methods dose not seem good with more compiler directives. May be other option would be using the HttpResponseMessage which is common and available to support for both frameworks. Is there a better way to build an API which could support multi target frameworks?

**Comment by khellang** [comment]
Why can't you just use ASP.NET Core on both platforms? Using directives and two different frameworks will be a huge pain.

**Comment by khellang** [comment]
Sure, but there's nothing stopping you from using ASP.NET Core on both full .NET Framework and .NET Core. There's only need for #ifdefs you'd need would be for stuff like remoting, which isn't available on .NET Core (not even with the [Windows Compatibility Pack for .NET Core](https://blogs.msdn.microsoft.com/dotnet/2017/11/16/announcing-the-windows-compatibility-pack-for-net-core/).)

**Comment by ircaxn** [comment]
Thanks Khellang, this triggers thoughts! Now, i created my API as .Net Core(2.1) project and build the API using .Net Core Mvc. When i tried to reference my API project in to my existing .net full framework class library projects, i am getting an error as below.
_Project NetCoreApi is not compatible with net472(.Net Framework, Version=v4.7.2). Project NetCoreApi supports: netcoreapp2.1(.NetCoreApp, Version=v2.1)_

**Comment by khellang** [comment]
> In this case, creating my API project as .Net Standard and refer the .Net Core packages to create my API does not create any problem on reference. Is that what you are suggesting?

Yes, make your app target `net472` and `netcoreapp2.1`, then make all your class libraries target `netstandard2.0`. Should work great on both platforms, using ASP.NET Core.

**Comment by karelz** [comment]
Looks answered.
