### ISSUE TITLE
Different thread from CancelKeyPress is not working

### ISSUE THREAD

**Issue by kripergvg** [dotnet/corefx#30723]
I have simple code with netcoreapp2.1 as target framework
```
        static void Main(string[] args)
        {
            var eventT = new ManualResetEventSlim();

            Console.CancelKeyPress += (s, e) =>
            {
                Task.Run(() =>
                {
                    Console.WriteLine("In Thread");
                    eventT.Set();
                });
            };

            eventT.Wait();
            Console.WriteLine("Exit");
        }
```
After i hit CTR+C "In Thread" and "Exit" never will be written in console. And visual studio debuger never hit body of Task.Run(). The same if i replace new Task.Run() with Thread().
dotnet --info
![image](https://user-images.githubusercontent.com/7288803/42029391-14ae7b5c-7ad8-11e8-9fde-fd5ec085cea6.png)

**Comment by khellang** [comment]
That's because the application shuts down before the task is able to start.

You should set the `Cancel` property on the [`ConsoleCancelEventArgs`](https://msdn.microsoft.com/en-us/library/system.console.cancelkeypress%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396):

> Cancel [...] allows you to determine how to your application should respond to the user pressing Ctrl+C or Ctrl+Break. By default, the `Cancel` property is `false`, which causes program execution to terminate when the event handler exits. Changing its property to `true` specifies that the application should continue to execute.

This works:

```diff
diff --git a/CancelKeyPress/Program.cs b/CancelKeyPress/Program.cs
index 9c5ddc3..b0c1e18 100644
--- a/CancelKeyPress/Program.cs
+++ b/CancelKeyPress/Program.cs
@@ -12,6 +12,7 @@ namespace CancelKeyPress
 
             Console.CancelKeyPress += (s, e) =>
             {
+                e.Cancel = true;
                 Task.Run(() =>
                 {
                     Console.WriteLine("In Thread");

```

**Comment by kripergvg** [comment]
@khellang Thank you
