### ISSUE TITLE
System.Security.Cryptography.Csp should support all runtimes

### ISSUE THREAD

**Issue by Grochni** [dotnet/corefx#3072]
I want to use RSACryptoServiceProvider, but System.Cryptography.Csp seams to be not available when targeting "dotnet". I looked around and it doesn't look like it's moved to another assembly. Are there any plans about this?

**Comment by bartonjs** [comment]
@ericstj Is this an "I created the package incorrectly", or an "our identifiers all up aren't where we want them to be"?  I'm mainly not sure if this is something I need to understand and fix, or if it's one of the things you're working on globally :smile:.

**Comment by bartonjs** [comment]
This seems like it should be resolved with the package platform overhaul (https://github.com/dotnet-bot/corefx/commit/0931c347eb836c9da94d0d5ff9ad7a14403b9738).
