### ISSUE TITLE
Ensure tests exist for every supported configuration for which we run tests.

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#30728]
We had an issue a little while back where we had a test that should have applied to netfx and we missed giving the test a configuration for netfx, and thus missed a place where our behaviors differed.

At least at the library level we should ensure that if the library is supported on a configuration for which we have tests, that the tests have a configuration that will run.  Supported could mean that we're actively building an implementation/facade, or it could mean that we're harvesting some previously built one (or relying on assets built into that framework).  Somewhere we should ensure that we configure and run test assets.

/cc @weshaggard @bartonjs

**Comment by ericstj** [comment]
@ViktorHofer what do you think about this?  How do you imagine this intersects with the goals of disabling netfx configurations and reducing the number of configurations to maintain?

**Comment by ViktorHofer** [comment]
I think we should still do this for 3.0 and scan through all test projects and verify that shipping configurations have corresponding tests. For netfx I would say it's the other way around, we should remove test configurations and source configurations if they their implementation hasn't changed since 2.1/2.2 and instead harvest them (if we ship netfx in a package).

**Comment by ericstj** [comment]
Harvest the tests or don't run the tests?  If we don't run the tests we lose sight of the scenario where we make changes that diverge from desktop behavior.

**Comment by ViktorHofer** [comment]
Closing as I scanned through most libraries when I trimmed the netfx configurations. I don't think that we are currently missing test configurations which aren't tracked by an individual issue.
