### ISSUE TITLE
Proposal: Unsafe.Unbox<T>(object) method

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#30730]
**Proposal**

I suggest we add the following method to System.Runtime.CompilerServices.Unsafe:
```C#
public static ref T Unbox<T>(object box) where T : struct;
```
Given a boxed value type T, this would return a mutable ref to the value in the box.  It would simply be a wrapper for the IL unbox instruction, e.g.:
```
.maxstack 1
ldarg.0
unbox !!T
ret
```

**Example Usage**

This would be useful as a performance optimization any time an API that takes an `object` needs to be called repeatedly with different values of a value type, enabling the same box object to be reused rather than a new one created each time.

For example, Uri has code when formatting a IPv6 URI that looks something like this:
```C#
internal static unsafe string CreateCanonicalName(ushort* numbers)
{
    ...
    StringBuilder builder = ...;
    for (int i = 0; i < NumberOfLabels; i++)
    {
        ...
        if (i != 0) builder.Append(Separator);
        builder.AppendFormat(CultureInfo.InvariantCulture, CanonicalNumberFormat, numbers[i]);
    }
    ...
}
```
That call to AppendFormat ends up boxing `numbers[i]` for each iteration of the loop.  With a method like `Unsafe.Unbox`, this could instead be written as:
```C#
internal static unsafe string CreateCanonicalName(ushort* numbers)
{
    ...
    StringBuilder builder = ...;
    object box = (ushort)0;
    ref ushort s = ref Unsafe.Unbox<ushort>(box);
    for (int i = 0; i < NumberOfLabels; i++)
    {
        ...
        if (i != 0) builder.Append(Separator);
        s = numbers[i];
        builder.AppendFormat(CultureInfo.InvariantCulture, CanonicalNumberFormat, box);
    }
    ...
}
```
such that instead of allocating a box object for each number, we only allocate one once.

**Comment by GrabYourPitchforks** [comment]
Quick behavioral question - would you expect this API to perform a type check every time it is called? That is, in your code sample above, would calling `Unsafe.Unbox<ushort>(...)` once outside the loop have the same performance characteristics as calling it within the loop? It _is_ on the `Unsafe` type, after all. :)

**Comment by stephentoub** [comment]
> would you expect this API to perform a type check every time it is called?

You're concerned about `unbox`'s type check?  I don't think `Unsafe.Unbox` should be required to do one, but I think it's fine for it to do so, and if we want to optimize that away subsequently (which I believe would make this feature much more involved), we could.  That type check is peanuts compared to the costs the API would help avoid.

**Comment by GrabYourPitchforks** [comment]
Ah, got it. I think the presence of the `unbox` instruction in the IL sample you posted confused me, and I was curious how we'd be able to avoid expensive runtime checks.

**Comment by terrajobst** [comment]
@TannerGooding brought up wether this should be handled by the [new compiler intrinsics](https://github.com/dotnet/csharplang/pull/1685).

@jaredpar, any thoughts?

**Comment by jkotas** [comment]
> brought up wether this should be handled by the new compiler intrinsics

So far, the compiler intrinsics has been scoped to cases that are not possible to implement as methods in `S.R.CS.Unsafe`.

**Comment by jaredpar** [comment]
Echoing @jkotas here.

The intrinsics proposal is aimed at getting language support for items we can't reasonably represent as an API . If it can be represented as an API then it's likely better off being implemented as such as it's immediately available to all languages. Also in most of these cases it's cheaper to just implement the API than going through LDM, compiler prototyping, toolset distribution, etc ...

**Comment by svick** [comment]
Why is this method on the `Unsafe` class? What is unsafe about it?

**Comment by jaredpar** [comment]
@svick 

My guess is the following:

``` csharp
object o = 42;
ref int i = Unsafe.Unbox<int>(o);
o = true;
```

What happens in this case? I'm unsure if this is safe or not in the context of this API.

**Comment by svick** [comment]
@jaredpar Why would that be unsafe? `o = true;` creates a new box and assigns a pointer to it to `o`. That doesn't affect the old box that can be accessed through `i` in any way.

**Comment by jkotas** [comment]
> Why is this method on the Unsafe class? What is unsafe about it?

Boxes are assumed to be immutable. This API returns mutable pointer.

**Comment by jkotas** [comment]
> `o = true;` creates a new box and assigns a pointer to it to `o`

Correct. This code fragment is fine.

**Comment by jaredpar** [comment]
> Correct. This code fragment is fine

Yep. I'm not sure why I thought boxing could happen in place in that way. Lot of meetings today. I'll blame that.

**Comment by benaadams** [comment]
But this code isn't fine
```csharp
object o = 42;
ref long i = Unsafe.Unbox<long>(o);
```

**Comment by stephentoub** [comment]
> But this code isn't fine

With the checked in implementation, that'll throw, since it uses unbox that does a type check.

**Comment by GSPP** [comment]
It it not new that code can mutate boxed values arbitrarily. It's safe, verifiable code. New is just the capability to do it directly from C#. Doing it through reflection emit or in IL was always possible.

**Comment by jakobbotsch** [comment]
> It it not new that code can mutate boxed values arbitrarily. It's safe, verifiable code.

As far as I know, it is not verifiable to mutate a boxed value. ECMA-335 lists a whole bunch of restrictions on controlled-mutability managed pointers (III.1.8.1.2.2) which `unbox` returns:

> Controlled-mutability managed pointers can only be used in the following ways:
> 1. As the object parameter for an ldfld, ldflda, stfld, call, callvirt, or constrained.callvirt instruction.
> 2. As the pointer parameter to a ldind.* or ldobj instruction.
> 3. As the source parameter to a cpobj instruction.
> 
> All other operations (including stobj, stind.*, initobj, and mkrefany) are invalid. 

Since the main use of this API is to mutate these kinds of pointers, it seems a bit suspect to me. Does nothing in the runtime rely on this part of the spec?

**Comment by mgravell** [comment]
@jkotas 

> Boxes are assumed to be immutable. This API returns mutable pointer.

not a valid assumption in the first place - `virtual` methods like `ToString()` can still expose mutability on a boxed instance (see below).

That said: I was looking for exactly this earlier today, and the place I *immediately* looked for it was: on `Unsafe`, and I was delighted to find it here in github (but not on non-alpha nuget yet, :cry: ). So from that perspective - it met precisely my expectations in terms of API discoverability.

``` c#
static class P
{
    static void Main()
    {
        object obj = new Foo();
        Console.WriteLine(obj); // 1
        Console.WriteLine(obj); // 2
        Console.WriteLine(obj); // 3
    }    
}

struct Foo
{   
    private int x;
    public override string ToString() => $"{++x}";
}
```

**Comment by jkotas** [comment]
@mgravell What do you think about changing the `Unsafe.Unbox` signature as proposed in https://github.com/dotnet/corefx/issues/30730 ?

**Comment by mgravell** [comment]
@jkotas  eesh, I can see both sides of that; my suggestion:

``` c#
ref readonly T Unbox<T>(object obj) where T : struct
ref T UnboxMutable<T>(object obj) where T : struct // naming is hard
```
so the most obvious is the safer, with the other one calling out what you're exposing yourself to

**Comment by stephentoub** [comment]
> with the other one calling out what you're exposing yourself to

If we were to make it return readonly ref, the mutable version is achievable by using Unsafe.AsRef to cast away the readonly-ness.

FWIW, I still think it's fine to just return ref.

**Comment by jkotas** [comment]
> FWIW, I still think it's fine to just return ref.

I think so as well. The problem with using `ref readonly` or `in` for low-level code is that it is easy to create a copy by mistake. It is why the existing `Unsafe` does not use `ref readonly` anywhere, but in a single method.

**Comment by GrabYourPitchforks** [comment]
We'd still have the problem that the code snippet presented very early on in this issue - ostensibly the most common use case of the Unbox API - is dangerous. There's nothing stopping the JIT from returning a singleton boxed default(T) for readonly types T, and the usage demonstrated here could cause runtime instability.

**Comment by jkotas** [comment]
> We'd still have the problem that the code snippet presented very early on in this issue

Ok, so can we just update the code snipped at the top to demonstrate one of the valid perfectly safe uses of this API and it will be good?

**Comment by GrabYourPitchforks** [comment]
> Ok, so can we just update the code snipped at the top to demonstrate one of the valid perfectly safe uses of this API and it will be good?

Then back to API review for "do we consider this pattern common enough that we want a first-class API for it?" because the original API review was based on a potentially undesirable scenario. But yeah. :)

**Comment by jakobbotsch** [comment]
ECMA-335 says:
> The pointer is called a controlled-mutability managed pointer because the defining type decides
whether the value can be mutated. For value classes that expose no public fields or methods that
update the value in place, the pointer is read-only (hence the name of the prefix). In particular,
the classes representing primitive types (such as  System.Int32 ) do not expose mutators and thus
are read-only.

So the "controlled-mutability" can be thought of as preserving mutability (as guaranteed by the programmer). That is why @mgravell's example is still fine. But this notion of pointer does not have an analogue in C#; it is a weaker concept than readonly pointers in C# which force copies when invoking methods on them. To me that makes the two-overload version best: for mutable value types removing the readonly modifier seems (kind-of?) defined and well-behaved, at least according to the spec.

**Comment by GSPP** [comment]
> There's nothing stopping the runtime from returning a singleton object when boxing default(T) for readonly types like int

Is that true? I thought the `box` instruction guarantees returning a new object.

**Comment by mgravell** [comment]
the runtime sometimes cheats... for example, `new string(...)` (`newobj` in IL) can return an interned singleton reference, too... (length zero, for example).
