### ISSUE TITLE
ManagedWebSocket.ApplyMask has an invalid (unaligned) cast

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/corefx#30747]
https://github.com/dotnet/corefx/blob/e36eaec682d5fa81bc1754e89787b0353b9c46b8/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L1262

It is invalid to reinterpret cast a `ref byte` to a `ref Vector<byte>` without first checking the alignment of the input buffer. This could cause problems on future architectures or IOT devices where unaligned reads incur faults. This code should pin and check alignment or should use `Unsafe.ReadUnaligned` instead.

**Comment by stephentoub** [comment]
Depends on https://github.com/dotnet/corefx/issues/33508

**Comment by scalablecory** [comment]
@tannergooding @davidsh @GrabYourPitchforks does the 3.0 release support any IOT architectures where unaligned load/store of `ref Vector<byte>` is a problem, or is this speculation on future architectures?

Might be good to resolve regardless, for some minor perf benefit.

**Comment by tannergooding** [comment]
@GrabYourPitchforks, I'm not sure this is actually a concern.

Since the GC does not support alignment above 8, we are already in a world where the JIT has to assume (unless it can prove otherwise) that any `Vector<T>` access is unaligned. So, this should generally be safe provided that the resulting `Vector<T>` is at least aligned `T` aligned.

**Comment by CarolEidt** [comment]
I agree with @tannergooding - we can't assume alignment in general, so we have to assume unaligned loads unless an aligned load is explicity specified as a HW intrinsic. That said, on some targets performance is better when aligned.

If we ever had to support a target where all loads had to be aligned, we'd have to specially handle any data types with alignment requirements > 8, and code like this might be an issue. I'm not sure whether it is worth defensively coding against such a future possibility.
