### ISSUE TITLE
Referencing .Net Framework library to Core projects throwing error

### ISSUE THREAD

**Issue by NaveenKumar2303** [dotnet/corefx#30750]
Hello Team ,
I am using a DLL library which was created in .Net Framework (earlier to 4.5) and i am referencing the same to my Core Project . the Core project builds correctly but the issue is when the code is pointing towards the methods that is corresponding towards the DLL library(.Net Framework) it is throwing "BadImageFormatException: Could not load file or assembly 'xxxx'. An attempt was made to load a program with an incorrect format." According to the solution in nuget i also installed the Windows.Compatibity package , still the error is not resolved .
Could you please provide us the alternative turn around solution for this as my project really requires to start up quickly and i am very keen on doing with Core rather than going back to .Net Framework approach .
Many thanks in advance.

**Comment by danmosemsft** [comment]
Check the bitness of the library...my guess is that it is built for 32 bit and your app is 64 bit or vice versa?

**Comment by NaveenKumar2303** [comment]
Yes that bit of Library is 32 bit , what will be the optimal solution for that to convert ?

**Comment by NaveenKumar2303** [comment]
Hey Team ,

Could you provide us the solution ?

**Comment by vcsjones** [comment]
>what will be the optimal solution for that to convert ?

You need to re-compile the library to be Any CPU (preferably) or x64 if you want to use the 64-bit .NET Core.

If you want to ensure your .NET Core project is 32-bit only, you can add this to your .csproj file:

```xml
<PlatformTarget>x86</PlatformTarget>
```

This has a few caveats though. Namely that, I think, Visual Studio will use the wrong SDK to start the project. There is an open issue in dotnet/cli#7532 that mentions this.

By far the easiest thing to do is to have everything be Any CPU and platform independent.

**Comment by NaveenKumar2303** [comment]
Thank you guys will give a shot and let you know

**Comment by NaveenKumar2303** [comment]
Closes #30750
