### ISSUE TITLE
DynamicMethod Byref Return Type

### ISSUE THREAD

**Issue by mikernet** [dotnet/corefx#30753]
Would like to be able to set a ref return type like this:

    var method = new DynamicMethod("Method", typeof(object).MakeByRefType(), new[] { typeof(object) }, ownerType, true);

Currently have to use this workaround/hack to avoid exception being thrown:

    var method = new DynamicMethod("Method", typeof(object), new[] { typeof(object) }, ownerType, true);
    method.GetType().GetField("m_returnType", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly).SetValue(method, typeof(object).MakeByRefType());

**Comment by mgravell** [comment]
Interestingly, this limitation only applies to `DynamicMethod`. If you use `TypeBuilder`, you can create a by-ref return method:

            var asm = AppDomain.CurrentDomain.DefineDynamicAssembly(new AssemblyName("foo"), AssemblyBuilderAccess.Run);
            var module = asm.DefineDynamicModule("foo");
            var tb = module.DefineType("bar", TypeAttributes.Class, typeof(object));
            var mb = tb.DefineMethod("method", MethodAttributes.Public | MethodAttributes.Static, typeof(object).MakeByRefType(), new Type[] { typeof(object[]) });
            var il = mb.GetILGenerator();
            il.Emit(OpCodes.Ldarg_0);
            il.Emit(OpCodes.Ldc_I4_2);
            il.Emit(OpCodes.Ldelema, typeof(object));
            il.Emit(OpCodes.Ret);

            var type = tb.CreateType();
            var method = type.GetMethod("method");
            var del = (SomeDelegateType)Delegate.CreateDelegate(typeof(SomeDelegateType), null, method);

            object[] arr = new object[4] { "abc", "def", "ghi", "jkl" };

            ref object r = ref del(arr);
            Console.WriteLine(r); // ghi

**Comment by mikernet** [comment]
Yeah, the `Init()` method in `DynamicMethod` explicitly checks if the return type is byref and throws if it is.

**Comment by jkotas** [comment]
This was fixed by https://github.com/dotnet/coreclr/pull/15106 . This fix is included in .NET Core 2.1
