### ISSUE TITLE
CoreFX Master Build Failures due to OptionalTooling issues on Windows

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#30758]
@dotnet-mc-bot commented on [Fri Jun 29 2018](https://github.com/dotnet/core-eng/issues/3802)

Opened on behalf of @MattGal

Seems related to using .dotnet to restore optional tooling sources from a core instance on Windows. 

Warnings: 1
Status Message: failed

Build : Master - 20180629.04 (Product Build)
Failing configurations:
- Windows
  - netfx-x86
  - netfx-x64
  - AllConfigurations-x64
  - uapaot-x86
  - uapaot-x64
  - uapaot-arm64
  - uapaot-arm
  - uap-x86
  - uap-x64
  - uap-arm
  - netcoreapp-x86
  - netcoreapp-x64
  - netcoreapp-arm64
  - netcoreapp-arm
[Mission Control Build Info](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/build~2Fproduct~2F/build/20180629.04/workItem/Orchestration/analysis/external/Link)

---

@MattGal commented on [Fri Jun 29 2018](https://github.com/dotnet/core-eng/issues/3802#issuecomment-401423543)

Pretty sure this was caused by @eerhardt's commit 50ba6a21d8ccb2be551805c98a2106c3477064a0, "Corefx Windows build on .NET Core MSBuild (#30675)".  

He would have missed this testing locally as the optional tool source stuff is only used for things like the .NET Native ToolChain.  Looking for him for live handoff now.

**Comment by MattGal** [comment]
Discussed with Eric, this was missed because CI does not use the OptionalToolSource stuff.  I'm prepping some instructions to repro for Eric now (basically need to generate a personal VSTS PAT, set some environment variables)

**Comment by MattGal** [comment]
1) Go to your VSTS profile, Security, and generate a PAT with at least permission 'Packaging (read)'

2) From a console set the following env vars

set OptionalToolSource=https://devdiv.pkgs.visualstudio.com/_packaging/dotnet-core-internal-tooling/nuget/v3/index.json
set OptionalToolSourcePassword=PATwithPackageReadPermissions
set OptionalToolSourceUser=youralias@microsoft.com

3) sync.cmd

**Comment by eerhardt** [comment]
Working on a fix now.
