### ISSUE TITLE
Port System.Device

### ISSUE THREAD

**Issue by greatjack1** [dotnet/corefx#30775]
The .net framework features a GeoCoordinate class. Documentation is over here https://msdn.microsoft.com/en-us/library/system.device.location.geocoordinate(v=vs.110).aspx

I think this class is a good candidate for porting as it's system independent and helps greatly when working with latitude and longitude coordinates.

I have no problem taking care of the work to port it. Would such a pull request be considered?

**Comment by hughbe** [comment]
Take a look at https://www.nuget.org/packages?q=System.device

**Comment by karelz** [comment]
@danmosemsft is it something we considered in the past or do we want to add it on the list? Does it need to be part of Core or can it sit on top of it?

**Comment by terrajobst** [comment]
I've renamed this issue to capture what is actually necessary to pull this. I think it would be part of the Windows Compat Pack as I don't think we can make this cross-platform.

**Comment by terrajobst** [comment]
We don't plan on bringing this .NET Framework API to .NET Core. See [this announcement](https://github.com/dotnet/corefx/issues/41769) for details.

**Comment by danmosemsft** [comment]
I've pushed up the .NET Framework sources in case they are useful to others. Same license as for reference sources.

https://github.com/microsoft/referencesource/pull/120

**Comment by terrajobst** [comment]
Tagging @dotmorten as FYI
