### ISSUE TITLE
Agree that we want to use libsodium (or not)

### ISSUE THREAD

**Issue by pgolebiowski** [dotnet/corefx#30772]
## context

[libsodium](https://download.libsodium.org/doc/) was already mentioned in this repository here and there. some examples:

### https://github.com/dotnet/corefx/issues/7127

> The current cryptography APIs are badly designed. They provide neither authenticated encryption nor the current best-practice algorithms.
> [...]
> A good choice would start with bindings to libsodium, which provides a high-level C API.

### https://github.com/dotnet/corefx/issues/7023

> [libsodium], the best example I know of a good crypto library

> I would sooner see a safe (something like NaCl or libsodium) API be a discussion that encompasses all of the crypto primitives, not just GCM.

> I would P/Invoke libsodium’s ChaCha20/Poly1305.

## goal of this thread

decide whether we want to use libsodium or not. simply a `true` or `false` flag.

## where would it be used?

assuming that the decision is *yes, we want to use libsodium*, then naturally here:

* ChaCha20-Poly1305 — https://github.com/dotnet/corefx/issues/5162
* AES-GCM — https://github.com/dotnet/corefx/issues/7023
* Argon2 — https://github.com/dotnet/corefx/issues/15217

plus possibly to address other issues in CoreFx i am not aware of.

## motivation

* i see a general movement that organizations and open source projects lean towards the usage of libsodium — see an [official incomprehensive list](https://download.libsodium.org/doc/libsodium_users/).
* countless wrappers have been written around it. there is a port for every major platform and programming language. larger community indicates having been battle-tested better.
* it has been audited. a random example [here](https://www.privateinternetaccess.com/blog/2017/08/libsodium-audit-results/).

## linking stuff

@bartonjs @karelz @DemiMarie @billinghamj @BurningEnlightenment @prajaybasu @galich @kapsiR @jbtule @AdamWillden @Drawaes @sdrapkin @blowdart @morganbr @ektrah

https://github.com/dotnet/corefx/issues/23629

[exemplary usage in .NET — NSec](https://nsec.rocks).

**Comment by bartonjs** [comment]
`false`: we do not want to add more dependencies to the core product.

**Comment by GrabYourPitchforks** [comment]
No.
