### ISSUE TITLE
ASP.Net Core 2.1 App not releasing the memory in Ubuntu

### ISSUE THREAD

**Issue by pradeeppnt** [dotnet/corefx#30776]
We are facing a memory issue with our ASP.Net Core MVC application developed in 2.1 framework and deployed in Ubuntu 16.04. The application will have around 100 to 200 hits concurrently and each of these hits require calling an external API (HttpClient is used for external API calls). As and when the number of requests come, the memory keep on increasing and resulting in out of memory after sometime. We noticed that garbage collection is not happening as we expect. Are we doing anything wrong?

We have set the `<ServerGarbageCollection>true</ServerGarbageCollection>` property to csproj. Still, there is no sign of garbage collection.

I am ready to share if more information required to resolve this issue.

**Comment by karelz** [comment]
Are you using AppInsights by a chance?
Did you migrate to 2.1 from .NET Core 2.0? And is this a regression introduced in 2.1?
GC will use memory, if it is available. Are you worried about GC not happening when you would like it to, or do you think there is memory leak? If you think there is memory leak, did you try to use memory profiler to track it down?

**Comment by pradeeppnt** [comment]
Thanks @karelz  for getting back. 
We have not used AppInsights yet. We shall try this.
We migrated from 1.1 to 2.1 and we did the functionality testing only. Not from a performance perspective. 
Yes, we were expecting the memory usage to be reduced as and when an API request is completed. However, this was not happening and the memory keep on increasing. As you pointed out this can be an issue within our code itself. A memory profiler will be good to identify the objects that cause memory issues. Do you have any suggestions for the memory profiler?

**Comment by khellang** [comment]
Sounds a lot like https://github.com/aspnet/KestrelHttpServer/issues/2214 (others that might be related; https://github.com/aspnet/Home/issues/1976 and https://github.com/dotnet/corefx/issues/30652)

**Comment by karelz** [comment]
> Do you have any suggestions for the memory profiler?

I would try VS (if it works against Linux), or PerfView - the [collector](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/linux-performance-tracing.md) is x-plat. Or some other tools I don't know about ...
cc @brianrob @valenis @vancem

**Comment by sebastienros** [comment]
> HttpClient is used for external API calls

Are you reusing the instances? A common mistake (and an expected one) is to dispose it every time, or just instance new ones on every requests, when it should actually be reused and disposed when the application stops. So can either use a static instance, use a singleton in DI or use the HttpClient factory pattern: https://blogs.msdn.microsoft.com/webdev/2018/02/28/asp-net-core-2-1-preview1-introducing-httpclient-factory/

**Comment by pradeeppnt** [comment]
I have tried out this approach, but could not find any improvement. Right now, I doubt it is not with HttpClient or external API calls. It may be something else which is causing the memory leak. I will do a detailed code review and come back.

As I believe, it is not an issue with HttpClient, I am closing this issue.
