### ISSUE TITLE
ConvertFromString doesn't throw NotSupportedException

### ISSUE THREAD

**Issue by neville-nazerane** [dotnet/corefx#30771]
I have tried the following code in console: 

    var converter = TypeDescriptor.GetConverter(typeof(int));
                try
    {
        var outed = (int) converter.ConvertFromString("sample");
        Console.WriteLine(outed);
    }
    catch (NotSupportedException)
    {
        Console.WriteLine("Invalid format");
    }

According to the documentation of `ConvertFromString`, it must throw a `NotSupportedException` if "The conversion cannot be performed". However, this throws a `System.ArgumentException`.

**Comment by danmosemsft** [comment]
What does desktop framework do?

**Comment by stephentoub** [comment]
> However, this throws a System.ArgumentException

Both .NET Framework and .NET Core throw an exception that wraps a FormatException.  The only difference between .NET Framework and .NET Core is that .NET Framework wraps the FormatException in the base Exception:
https://referencesource.microsoft.com/#System/compmod/system/componentmodel/basenumberconverter.cs,106
whereas .NET Core wraps the FormatException in an ArgumentException:
https://source.dot.net/#System.ComponentModel.TypeConverter/System/ComponentModel/BaseNumberConverter.cs,82
That change was made here:
https://github.com/dotnet/corefx/pull/26050

> According to the documentation of ConvertFromString, it must throw a NotSupportedException if "The conversion cannot be performed"

The docs also say it can throw:
```
Exception
value is not a valid value for the target type.
```
which is what's happening here.
