### ISSUE TITLE
WebSocket.ThrowOnInvalidState doesn't set exception.WebSocketErrorCode = WebSocketError.InvalidState

### ISSUE THREAD

**Issue by georgiosd** [dotnet/corefx#30779]
`WebSocket.ThrowOnInvalidState` doesn't set `exception.WebSocketErrorCode = WebSocketError.InvalidState`
Instead it's `Success` :(

**Comment by georgiosd** [comment]
I wouldn't know how to repro but you've found it :)

The message is formatted correctly but the code does not equal `InvalidState`.

**Comment by karelz** [comment]
Do you want to put up a PR? (Ideally with a test ;))

**Comment by georgiosd** [comment]
If you can point me to the appropriate place to put the test, happily.

**Comment by davidsh** [comment]
WebSocket Client tests typically go here:

https://github.com/dotnet/corefx/tree/master/src/System.Net.WebSockets.Client/tests

But depending on the type of fix, it might go here:

https://github.com/dotnet/corefx/tree/master/src/System.Net.WebSockets/tests
