### ISSUE TITLE
.net core 2.1 process exit code 139 on docker linux env

### ISSUE THREAD

**Issue by CanerPatir** [dotnet/corefx#30780]
For a while, I have been encountering an unexpected pod restart issue on kubernetes environment. When I check the pod logs I see the following process exit reason.

  "lastState": {
          "terminated": {
            "exitCode": 139,
            "reason": "Error",
            "startedAt": "2018-07-02T05:01:28Z",
            "finishedAt": "2018-07-02T05:01:53Z",
            "containerID": "docker://f3b445e6d7610226384a582bfa0e200721ca708e1841ae4c6c82cb04deb2a522"
          }
        },
The app is an http independent background service so I am using "HostBuilder" to start up the app like following 
```c#
  public static async Task Main(string[] args)
        {
             

            var serviceHost = new HostBuilder()
                .UseEnvironment(Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT"))
                .ConfigureAppConfiguration((hostContext, configApp) =>
                {
                    configApp.AddEnvironmentVariables();
                    configApp.AddJsonFile("appsettings.json", true);
                    configApp.AddJsonFile(
                        $"appsettings.{hostContext.HostingEnvironment.EnvironmentName}.json",
                        true);
                    configApp.AddCommandLine(args);
                    configApp.Build();
                })
                .ConfigureServices((context, services) =>
                {
                     Log.Logger = new LoggerConfiguration()
                             .Enrich.FromLogContext()
                             .WriteTo.Graylog(new GraylogSinkOptions
                             {
                                 HostnameOrAddress = context.Configuration["Logging:GraylogIp"],
                                 Port = 12201,
                                 TransportType = TransportType.Udp,
                                 MinimumLogEventLevel = LogEventLevel.Information,
                                 Facility = "MyApp",
                                 MessageGeneratorType = MessageIdGeneratortype.Timestamp
                             }).CreateLogger();

                    services.AddLogging(builder => { builder.AddSerilog(Log.Logger); });

                    services.AddMyServices(context.Configuration);
                    services.AddHostedService<MyBackgroundService>();
                    services.AddMassTransit(configurator =>
                    {
                        configurator.AddConsumer<SomeQueueConsumer>();
                    });
                })
                .Build();

            await serviceHost.RunAsync();
        }
```

BTW, I am using GC in server mode as below (Maybe the issue is related with this approach)

````
    <ServerGarbageCollection>true</ServerGarbageCollection>
````
Does the issue point a .net core memory management issue or should I focus on implementation ?

**Comment by vcsjones** [comment]
139 is the typical exit code for a segfault.

Is the service doing something particular at the time it crashes or accessing a specific API?

**Comment by danmosemsft** [comment]
A callstack would be great - perhaps it is possible to configure the container to collect a dump?

**Comment by CanerPatir** [comment]
Thank you for your interest. I've fixed the issue through switching "ServerGarbageCollection" to false. We can close the issue.

**Comment by vcsjones** [comment]
>Thank you for your interest. I've fixed the issue through switching "ServerGarbageCollection" to false. We can close the issue.

Hm. That's concerning though that other people using `ServerGarbageCollection` may be running in to a segfault.

**Comment by CanerPatir** [comment]
It seems similar to https://github.com/dotnet/corefx/issues/30776. We can follow the issue from there
