### ISSUE TITLE
TextReader/Writer.Synchronized don't work with new Span APIs

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#30799]
Here is where the Writer gets created:

https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/IO/TextWriter.cs#L738-L744

The synchronized wrappers don't override the new virtual Span based methods. This prevents dependable locking and also prevents overridden methods from being called.

Related to #30796.

**Comment by stephentoub** [comment]
I would expect it would still "work", it just wouldn't be as efficient (and for the WriteLine versions it could end up not being atomic across the Write and the Line parts), and it would end up delegating to non-span based derived methods.  Is that not the case?

**Comment by JeremyKuhne** [comment]
> Is that not the case?

Locking may happen accidentally. The problem is if you make your own custom derived TextWriter then wrap it you will never get your overrides called for the APIs that aren't wrapped. So `MyTextWriter.WriteLine(ReadOnlySpan)` wrapped will _always_ call the TextWriter implementation as SyncronizedTextWriter won't call it's nested TextWriter (e.g. `_out`).

**Comment by stephentoub** [comment]
> So MyTextWriter.WriteLine(ReadOnlySpan) wrapped will always call the TextWriter implementation as SyncronizedTextWriter won't call it's nested TextWriter (e.g. _out).

That was my question with "it would end up delegating to non-span based derived methods"... won't it still call to `_out`, but to `_out.WriteLine(char[] buffer, int index, int count)`?

**Comment by JeremyKuhne** [comment]
> won't it still call to `_out`

Sure, but if you inserted any custom logic in `MyTextWriter.WriteLine(ReadOnlySpan)` it will never get hit- that is the problem.

**Comment by JeremyKuhne** [comment]
> It's not accidental.

Might be worth adding comments- I can see someone optimizing some of this away in the future.
