### ISSUE TITLE
Table of supported certificate store operations across OS/platforms

### ISSUE THREAD

**Issue by SidShetye** [dotnet/corefx#30801]
This is a request for documentation. For cross-platform code to operate predictably across various OS' it would be helpful to understand what certificate store operations are supported. Perhaps a matrix or a table of permutations like 

```
Platform, Store Location, Store Name, C# supported operations, Notes
Ubuntu 18.04 LTS, LocalMachine, My, ReadOnly, Refer to system manual. Write ops in vNext 
```

This is compounded by the fact that different operating systems don't necessarily follow the same certificate store model (e.g. Ubuntu doesn't seem to have a user level store). Since we're normalizing against the .NET cert store API, documenting limitations will greatly help disambiguate the platform limitations.

Documenting any other aspects would also help (like "Linux doesn't support cert store xyz, so we throw and exception/remap to store abc/etc").

Thanks

**Comment by bartonjs** [comment]
> e.g. Ubuntu doesn't seem to have a user level store

What do you mean by that?  CurrentUser stores work fine on Linux.

**Comment by bartonjs** [comment]
Also, what do you think is missing from https://github.com/dotnet/corefx/blob/master/Documentation/architecture/cross-platform-cryptography.md#x509store?

**Comment by SidShetye** [comment]
@bartonjs I mean that Ubuntu (or more generically Linux) doesn't seem to have any standardized user-level certificate store. The lack of a standard muddies the waters. I understand dotnet itself does have

Back to your link, it doesn't yet ranked in search engines (e.g. "[dotnet certificate stores](https://www.google.com/search?q=dotnet+certificate+stores)") but it really gets the job done. Thanks.

We were seeing crypto exceptions on Ubuntu when writing to `LocalMachine\Root` even with `sudo` during server initial configuration and looking at the table it's clear why/expected. 

On deviation from the table is that on macOS `CurrentUser\My` is supported for ReadWrite but removing a certificate from `CurrentUser\My` actually fails with the following message. 

```
System.Security.Cryptography.CryptographicException: Removing the requested certificate would modify user trust settings, and has been denied.
   at Interop.AppleCrypto.X509StoreRemoveCertificate(SafeSecCertificateHandle certHandle, SafeKeychainHandle keychain)
```

Ubuntu 18 works just fine.

Lastly, where is the user level certificate store is kept on Linux and what - if any - mechanisms protect it (e.g. DPAPI on Windows)?

**Comment by bartonjs** [comment]
> On deviation from the table is that on macOS CurrentUser\My is supported for ReadWrite but removing a certificate from CurrentUser\My actually fails with the following message [message about trust]

If a certificate has custom trust rules applied then corefx refuses to remove it due to the side effects it would induce.  If it's just a garden variety certificate/identity stored in the keychain then it should remove fine

> .Lastly, where is the user level certificate store is kept on Linux and what - if any - mechanisms protect it (e.g. DPAPI on Windows)?

Strace or code searching would show that it is under `~/.dotnet/corefx/cryptography/x509stores/`.  Direct manipulation of those directories definitely voids the warranty.

We use all of the guaranteed protections we can.  Namely, `chmod 600`.  (If chmod "succeeds" with no effect, such as if it's mounted on FAT32, we refuse to write files)

**Comment by SidShetye** [comment]
Thanks, I think we can safely close this issue
