### ISSUE TITLE
System.Console should use TextReader.Synchronized

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#30802]
A custom wrapper was used when porting System.Console as the Synchronized method wasn't part of the initial CoreFX port. This creates risk as new APIs added to TextReader/Writer need to track their way down to this separate implementation.

Writer is being taken care of in #30796.

#30799 tracks missing functionality in the .Synchronized wrappers.

**Comment by stephentoub** [comment]
This was fixed by https://github.com/dotnet/corefx/pull/30796.
