### ISSUE TITLE
Retarget and publish System.ComponentModel.Composition.Registration

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#30812]
Retarget to build against netstandard as soon as System.Reflection.Context targets netstandard. Publish the package as part of the 3.0 release.

**Comment by ericstj** [comment]
Looks like this is already done: https://github.com/dotnet/corefx/commit/2e6994336ba7eddb326646d43f1456e753caf47d#diff-42882c856b91468ce503d745a162d07bR5

Fixed in #29350

**Comment by ViktorHofer** [comment]
This is about setting the TFM to netstandard2.1. The current netstandard 2.0 tfm is a throwing one.
