### ISSUE TITLE
Certain Sequence of Text/HTML on Razor Page Results in Error "rzc generate exited with code 1" During Build

### ISSUE THREAD

**Issue by robinwilson16** [dotnet/corefx#30816]
I have discovered a strange bug where certain text and HTML I add to a Razor page results in the following error and the project failing to build and this did not occur on 2.0 as I am migrating the existing pages:
```
rzc generate exited with code 1.
WebApplication1	
C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.1.1\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets	121	
```

I can make the error go away by just changing the formatting slightly such as removing some of the blank line breaks, removing the emoticon or removing the img tag but either way the syntax is valid.
Also until I get rid of the error I cannot create any new razor pages either as get the same error.

I did wonder if there was some special character but as changing any bits of the text cause it to work again it seems to just not like this exact sequence of text.

I can replicate by creating a new .NET Core Web Application in VS.NET (latest build) and pasting the following into one of the Razor pages exactly as is:
```
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <img src="~/images/TroubleGettingFinanceWeCanHelp.jpg" class="img-fluid mx-auto d-block" alt="Trouble getting finance? We can help">
        </div>
        <div class="col-sm-8">
            <p>Metro Centre Auto World is a family owned and run business.</p>

            <p>We pride ourselves on the great service we provide to all of our customers.</p>

            <p>Been turned down for finance? We can help with finance options tailored to suit your needs.</p>

            <p>We understand that buying a car can be a daunting prospect, so we strive to make the buying process as simple and hassle-free as possible.</p>

            <p>But don't just take our word for it, <a href="https://www.autotrader.co.uk/services/car-dealers/uk/north-east/tyne-and-wear/gateshead/mainline-uk-gateshead-dpp-27856/reviews/true" target="_blank" rel="noopener">see what some of our customers have to say about us...</a></p>

            <a class="btn btn-light" href="https://www.autotrader.co.uk/services/car-dealers/uk/north-east/tyne-and-wear/gateshead/mainline-uk-gateshead-dpp-27856/reviews/true" target="_blank" rel="noopener">
                💬 See what people are saying
            </a>
        </div>
    </div>
</div>
```
I just need to remove a line break between any of the sets of P tags and the build is successful.
The page did have more content on it but I reduced it down to find which bit was triggering the error.

**Comment by karelz** [comment]
This issue was moved to aspnet/Home#3294
