### ISSUE TITLE
TreatControlCAsInput always throws

### ISSUE THREAD

**Issue by richlander** [dotnet/corefx#30819]
OS: Windows
.NET Version: .NET Core 2.1.1

I have this app:

```csharp
using System;

namespace ControlC
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Console.TreatControlCAsInput = true;
        }
    }
}
```

It always throws:

```console
Exception has occurred: CLR/System.IO.IOException
An unhandled exception of type 'System.IO.IOException' occurred in System.Console.dll: 'The handle is invalid'
   at System.ConsolePal.set_TreatControlCAsInput(Boolean value)
   at System.Console.set_TreatControlCAsInput(Boolean value)
   at ControlC.Program.Main(String[] args) in C:\Users\rich\ControlC\Program.cs:line 10
```

I wasn't expecting this. What is the correct behavior?

I am having some trouble getting the behavior I want with CTRL-C. I was using this property in a larger app and see the same behavior.  This is the minimal use case. I want to run code in the `CancelKeyPress` w/o it exiting before execution of the handler is complete.

**Comment by stephentoub** [comment]
I can't repro this, and I've never seen an error like this.  TreatControlCAsInput is supported.

Also, what is the `Exception has occurred: CLR/System.IO.IOException` in your output?  Where is that coming from?

How are you executing this?

**Comment by richlander** [comment]
I see now that it works with `dotnet run`. I can repro it with F5 in VS Code (still on Windows).

Only other info in the exception is this HRESULT, which I assume is generic: 2147024890

**Comment by stephentoub** [comment]
> I can repro it with F5 in VS Code (still on Windows).

It sounds like the issue then is with VS Code and how it's creating the console.  Most likely it's redirecting stdin such that there isn't actually a Windows console to interact with, and you get the IOException outlined in the docs: "Unable to get or set the input mode of the console input buffer.".
