### ISSUE TITLE
 Is there a more efficient way to append `StringBuilder` to another?

### ISSUE THREAD

**Issue by mokeyish** [dotnet/corefx#30829]
```c#
var a = new StringBuilder('a');
var b = new StringBuilder('b');

// merge `a` and `b` by appending `b` to `a`
var result1 = a.Append(v); / * equal to */ var result2 = a.Append(b.ToString())


```
Is it possible to set `m_ChunkPrevious`  of `StringBuilder` with `b` directly and update length and offset？ 

[StringBuilder.cs](https://github.com/dotnet/corefx/blob/844415759d3f1525bf1f5d1bd79453c6aa8493f8/src/Common/src/CoreLib/System/Text/StringBuilder.cs)

**Comment by stephentoub** [comment]
Are you asking for a `public StringBuilder Append(StringBuilder value);` method?  That exists as of .NET Core 2.1.

**Comment by mokeyish** [comment]
@stephentoub OK,I have found `public StringBuilder Append(StringBuilder value);` in .NET Core 2.1. thankyou.:grinning:

**Comment by mokeyish** [comment]
@stephentoub But `public StringBuilder Append(StringBuilder value)` is not exist in `netstandard 2.0`.

**Comment by svick** [comment]
@stephentoub Yes, but the question is: shouldn't it? That way, when I write `sb1.Append(sb2)` in a .Net Standard 2.0 library, it will call `Append(object)`, but when I run it on .Net Core 2.2, it will be efficient.

**Comment by stephentoub** [comment]
> Yes, but the question is: shouldn't it?

I raised that possibility at the API review.  The general consensus was: meh.
