### ISSUE TITLE
BinaryFormatter: Order of fields in serialization payload is flaky

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#30834]
It seems like the order of the fields serialized with BinaryFormatter is flaky. Example with System.Drawing.Color:

Before:
```
     System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs(obj: Color [A=255, R=100, G=55, B=255], blobs: [System.Runtime.Serialization.Formatters.Tests.TypeSeria
  lizableValue, System.Runtime.Serialization.Formatters.Tests.TypeSerializableValue]) [FAIL]
        The stored blob for type System.Drawing.Color is outdated and needs to be updated.

        -------------------- Stored blob ---------------------
        Encoded: AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABRTeXN0ZW0uRHJhd2luZy5Db2xvcgQAAAA
  EbmFtZQV2YWx1ZQprbm93bkNvbG9yBXN0YXRlAQAAAAkHBwIAAAAK/zdk/wAAAAAAAAIACw==
        Decoded:     ????          QSystem.Drawing, Version=0.0.0.0 Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a   System.Drawing.Color   namevalueknownColorstate              ?
  7d?       

        --------------- Runtime generated blob ---------------
        Encoded: AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABRTeXN0ZW0uRHJhd2luZy5Db2xvcgQAAAA
  Ka25vd25Db2xvcgVzdGF0ZQRuYW1lBXZhbHVlAAABAAcHCQIAAAAAAAIACv83ZP8AAAAACw==
        Decoded:     ????          QSystem.Drawing, Version=0.0.0.0 Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a   System.Drawing.Color   knownColorstatenamevalue           
    ?7d?    
        Expected: True
        Actual:   False
```

This happens _without_ a source change in System.Drawing.Primitives or in System.Runtime.Serialization.Formatters but when adding additional test data that references additional types/assemblies. In my example I added System.Drawing.Common types (Bitmap, Icon, Metafile) to the BinaryFormatterTestData method that yield returns all the different serializable objects. I think that somehow the BinaryFormatter changes the order of the fields depending on imported types / assemblies.

As some of our customers rely on the ordering of the fields in the payload (i.e. CultureAwareComparer) and the blob check in BinaryFormatterTests does so too we should fix this.

cc @stephentoub @danmosemsft

**Comment by danmosemsft** [comment]
> As some of our customers rely on the ordering of the fields in the payload (i.e. CultureAwareComparer

Why does this not break.NET Framework customers -Binary formatter shoukd be the same code.

**Comment by ViktorHofer** [comment]
I guess because they were lucky and didn't cause that behavior change. I just found a repro for it and will post it.

**Comment by ViktorHofer** [comment]
Repro:

```csharp
[Fact]
public void X()
{
    Pen p = new Pen(Color.Red, 5);

    var members = FormatterServices.GetSerializableMembers(typeof(System.Drawing.Color)).ToArray();
    foreach (var member in members)
    {
        Console.WriteLine(member.Name);
    }
}

knownColor
state
name
value
```

```csharp
[Fact]
public void X()
{
    //Pen p = new Pen(Color.Red, 5);

    var members = FormatterServices.GetSerializableMembers(typeof(System.Drawing.Color)).ToArray();
    foreach (var member in members)
    {
        Console.WriteLine(member.Name);
    }
}

name
value
knownColor
state
```

**Comment by ViktorHofer** [comment]
This is not a BinaryFormatter bug because the reflection call returns the fields already in the reversed order: http://source.dot.net/#System.Runtime.Serialization.Formatters/System/Runtime/Serialization/FormatterServices.cs,87

I will search through documentation if that's expected or a bug in Reflection.

**Comment by ViktorHofer** [comment]
> The GetFields method does not return fields in a particular order, such as alphabetical or declaration order. Your code must not depend on the order in which fields are returned, because that order varies.

https://msdn.microsoft.com/en-us/library/6ztex2dc(v=vs.110).aspx

@tarekgh FYI. You mentioned that some customers rely on the order of the fields in CultureAwareComparer. BinaryFormatter uses Type.GetFields underneath which doesn't guarantee a deterministic order of the fields. Should that concern us?

**Comment by tarekgh** [comment]
@ViktorHofer as the documentation says GetSerializableMembers depends on the reflection which doesn't guarantee the order of the reported fields. I don't think we can control the reflection and force specific order. But we should keep the order in the serialized stream. I mean we shouldn't change the order when serializing the fields of any old supported objects.

**Comment by ViktorHofer** [comment]
Right, I'm not planning to change anything regarding to that. I just wanted to check with you if customers who rely on fields in a specific order in the blob are aware of the fact that the given order can't be guaranteed.

**Comment by tarekgh** [comment]
Yes, we have communicated this to the customer and also we clarified the documentation too (which you quoted above).

**Comment by ViktorHofer** [comment]
Ok nice, thanks!
