### ISSUE TITLE
AuthenticationException with Client Cert Auth, only in Chrome

### ISSUE THREAD

**Issue by Tratcher** [dotnet/corefx#30847]
_From @WasserEsser on July 3, 2018 23:48_

Hi,

I'm not quite sure if this is the right repository for this, excuse me if it isn't.

I'm having issues implementing client certificate authentication in ASP.NET Core using Kestrel.
More specifically, I'm getting an exception (System.Security.Authentication.AuthenticationException) when connecting to the server via Chrome with a client certificate. Using Firefox or Edge/IE with the same client certificate works fine. 
When digging into it using Wireshark, the only real difference I can find is that Firefox and Edge are using ecdsa_secp256r1_sha256 as the signature algorithm in the Certificate Verify message while Chrome uses ecdsa_secp384r1_sha384.

This is the stack trace when connecting via Chrome:

> Microsoft.AspNetCore.Server.Kestrel[0]
>       Uncaught exception from the OnConnectionAsync method of an IConnectionAdapter.
> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The token supplied to the function is invalid
>    --- End of inner exception stack trace ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
>    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
>    at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
>    at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.<InnerOnConnectionAsync>d__12.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.FrameConnection.<ApplyConnectionAdaptersAsync>d__50.MoveNext()

Is the signature algorithm supported here? 

Any other ideas what could cause this? 

Chrome is not really helping in debugging this as the only thing it is reporting is ERR_CONNECTION_CLOSED. 

_Copied from original issue: aspnet/KestrelHttpServer#2697_

**Comment by davidsh** [comment]
cc: @bartonjs

**Comment by bartonjs** [comment]
The call stack here suggests an SChannel problem or a TLS protocol problem... I don't see anywhere that I'd have particular insight.

**Comment by davidsh** [comment]
@WasserEsser what OS and version is this problem happening on?

**Comment by WasserEsser** [comment]
@davidsh Hi, thanks for looking into this issue.
I'm not at work right now, but I can head there to look into supplying the necessary information and to create a little repro project if you want. OS though is Windows 10, that's what I can say for sure.

**Comment by davidsh** [comment]
>and to create a little repro project if you want.

Thanks. A little repro project would enable us to troubleshoot this problem.

**Comment by WasserEsser** [comment]
To add onto this, generating a new client certificate and signing it with the previously used intermediate also results in an exception and a dropped connection.

**Comment by davidsh** [comment]
We don't have enough information to reproduce this problem.  In order to diagnose further, we would need the certificate you're using that is showing the problems.  Or a way to re-create the problematic certificate.

For now, we'll close the issue.  If you are able to reproduce the problem and can give us a way to troubleshoot, then we can re-open the issue. Thanks.
