### ISSUE TITLE
Get path in error in FileSystemEnumerator.ContinueOnError

### ISSUE THREAD

**Issue by CyberSinh** [dotnet/corefx#30848]
I'm trying to use the new custom directory enumeration API available in .NET Core 2.1, that offer a new level of flexibility and performance in the .NET world. 

After reading [blog post](https://blogs.msdn.microsoft.com/jeremykuhne/2018/03/09/custom-directory-enumeration-in-net-core-2-1) of @JeremyKuhne, I wrote a FileSystemEnumerator derived from the one provided in .NET Core 2.1. I have overriden the ContinueOnError method to log all native errors. 

My problem is that this method only gives the error code as a parameter and not the file that caused it. 
Do you know how to get this information (under Windows)? 
And why does the method not have a FileSystemEntry parameter (even partially filled)? 

Thank you very much for your return.

**Comment by JeremyKuhne** [comment]
> Do you know how to get this information (under Windows)?

You can't easily do this. I hope to add something that gives context, but it is tricky. The information given can't add heap allocations for the relevant data.

The current shape of the ContinueOnError was meant to provide a way to simply ignore all file system errors or errors of a specific class. I wanted to provide at least some functionality in this initial release- I didn't have enough time to come up with a clean way to provide useful context data.

I'll open up an issue to track.

**Comment by JeremyKuhne** [comment]
Resolving this as #30861 tracks creating an API for this.
