### ISSUE TITLE
IFormFile bug

### ISSUE THREAD

**Issue by cristian1975** [dotnet/corefx#30842]
If you upload a excel file to a web api endpoint,  IFormFile object type from Request.Form.Files collection  has bigger size than the original excel file and if you try to open the uploaded file from the upload folder is in incorrect format. The method to upload a file is taken from .net core 2.1 documentation site:
           using (var stream = new FileStream(filePath, FileMode.Create))
            {
                await formFile.CopyToAsync(stream);
            }
where fromFile is IFormFile type.
This bug is happen from .net core version 2.0.6 and above.

**Comment by khellang** [comment]
This issue belongs in https://github.com/aspnet/Mvc 😄

**Comment by karelz** [comment]
This issue was moved to aspnet/Home#3304

**Comment by karelz** [comment]
@khellang thanks for saving me time to figure it out myself :)
