### ISSUE TITLE
Update the external links inside the documentation of 'ClaimTypes.cs' file.

### ISSUE THREAD

**Issue by SherifRefaat** [dotnet/corefx#30843]
**Verdict**
If you follow the documentation links in the 'ClaimTypes' class, you will find that the pages are removed.

![image](https://user-images.githubusercontent.com/11178713/42324515-b11217ac-8063-11e8-95f4-ac86064a8044.png)

**Source code path**
 corefx/src/System.Security.Claims/src/System/Security/Claims/ClaimTypes.cs 

**Online documentation link**
https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claimtypes.serialnumber?view=netcore-2.1

**Comment by karelz** [comment]
@SherifRefaat do you want to submit a PR?

**Comment by bartonjs** [comment]
Those URIs are the URIs that represent the claim.  I don't know that there ever was a resource at that location.

Presumably the documentation is trying to display the const string value... but then because it looks like a URI it's getting link-ified.

**Comment by bartonjs** [comment]
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IdentityModel.Claims/ClaimTypes.xml

**Comment by bartonjs** [comment]
This is a docs or docs-gen problem; with the relevant content located at https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IdentityModel.Claims/ClaimTypes.xml.  Closing this issue as non-actionable.
