### ISSUE TITLE
Marshal API tests failing sporadically

### ISSUE THREAD

**Issue by jiangzeng** [dotnet/corefx#30866]
The test fails accidentally in windows, not stable.
Failed test code:
[https://github.com/jiangzeng/corefx/blob/77fced488a141298d362d5204a828835416c7012/src/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/Marshal/GetExceptionForHRTests.cs](https://github.com/jiangzeng/corefx/blob/77fced488a141298d362d5204a828835416c7012/src/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/Marshal/GetExceptionForHRTests.cs)
       `[Theory]
       [InlineData(unchecked((int)0x80020006))]
       [InlineData(unchecked((int)0x80020101))]
       public void GetExceptionForHR_EqualsErrorCode(int err)
       {
              Exception ex = Marshal.GetExceptionForHR(err);
              Assert.Equal(err, ex.HResult);
       }`
 
Error log:
[https://mc.dot.net/#/user/jiangzeng/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/77fced488a141298d362d5204a828835416c7012/workItem/System.Runtime.InteropServices.Tests/analysis/xunit/System.Runtime.InteropServices.Tests.GetExceptionForHRTests~2FGetExceptionForHR_EqualsErrorCode(err:%20-2147352570)](https://mc.dot.net/#/user/jiangzeng/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/77fced488a141298d362d5204a828835416c7012/workItem/System.Runtime.InteropServices.Tests/analysis/xunit/System.Runtime.InteropServices.Tests.GetExceptionForHRTests~2FGetExceptionForHR_EqualsErrorCode(err:%20-2147352570))
`Assert.Equal() Failure
Expected: -2147352570
Actual:   1000`

**Comment by luqunl** [comment]
@jiangzeng, Could you do the following?


`[Theory]`
`[InlineData(unchecked((int)0x80020006))]`
`[InlineData(unchecked((int)0x80020101))]`
`public void GetExceptionForHR_EqualsErrorCode(int err) `
`{`
        // `Try to clean current thread IErrorInfo's value`
        `Marshal.GetExceptionForHR(unchecked((int)0x80004002))); `
        `Exception ex = Marshal.GetExceptionForHR(err);` 
       `Assert.Equal(err, ex.HResult); `
`}`
`

**Comment by danmosemsft** [comment]
I have hit this one. Also BindToMoniker_InvalidMonikerName_ThrowsCOMException(monikerName: \"name\") is failing sporadically perhaps for the same issue

https://mc.dot.net/#/user/danmosemsft/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/62e01621e73d4337a02c5216e4d57f7aac604e17/workItem/System.Runtime.InteropServices.Tests/analysis/xunit/System.Runtime.InteropServices.Tests.BindToMonikerTests~2FBindToMoniker_InvalidMonikerName_ThrowsCOMException(monikerName:%20%5C%22name%5C%22)
```
Assert.Throws() Failure
Expected: typeof(System.Runtime.InteropServices.COMException)
Actual:   typeof(System.Runtime.InteropServices.Tests.ErrorWrapperTests+SubException): Exception of type 'System.Runtime.InteropServices.Tests.ErrorWrapperTests+SubException' was thrown.
Stack Trace :
   at System.Runtime.InteropServices.Marshal.CreateBindCtx(UInt32 reserved, IBindCtx& ppbc)
   at System.Runtime.InteropServices.Marshal.BindToMoniker(String monikerName) in E:\A\_work\104\s\src\System.Private.CoreLib\src\System\Runtime\InteropServices\Marshal.cs:line 1695
   at System.Runtime.InteropServices.Tests.BindToMonikerTests.<>c__DisplayClass2_0.<BindToMoniker_InvalidMonikerName_ThrowsCOMException>b__0() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServices\Marshal\BindToMonikerTests.cs:line 32
```

Seems "SubException" is leaking from ErrorWrapperTests into BindToMonikerTests. Note those two test classes would run in the same process possibly concurrently or possibly on the same thread sequentially.

https://blogs.msdn.microsoft.com/yizhang/2013/01/18/marshal-gethrforexception-does-more-than-just-get-hr-for-exception/

@AaronRobinsonMSFT @luqunl

**Comment by AaronRobinsonMSFT** [comment]
@danmosemsft @luqunl Here are my thoughts on this issue:

1) Call `Marshal.GetExceptionForHR()` twice. Once to clear the current `IErrorInfo` instance and the second to get the real exception.
1) PInvoke into `SetErrorInfo()` and set the current `IErrorInfo` instance to `null`. (i.e. `SetErrorInfo(0, null)`)

I prefer the first option because it doesn't introduce any PInvokes which makes cross platform simpiler. Opinions?

**Comment by danmosemsft** [comment]
@AaronRobinsonMSFT either seem fine in tests -- if it was implemenation we might want to do the prettier way...

**Comment by AaronRobinsonMSFT** [comment]
Thanks @danmosemsft. I went with the first option - PR #31136
