### ISSUE TITLE
System.Drawing.Common  DrawString lost text

### ISSUE THREAD

**Issue by quan01994** [dotnet/corefx#30867]
CentOS 7.4 

````
var ms = new MemoryStream();
using (var image = Image.FromFile("qq.jpg"))
using (var image2 = Image.FromFile("11.jpg"))
{
    using (var g = Graphics.FromImage(image))
    {
        g.DrawImage(image2, 0f, 0f);
        var width = image.Width;
        var height = image.Height;
        var fontsize = 0.05f * width;
        var font = new Font("宋体", fontsize, FontStyle.Bold);
        var brush = new SolidBrush(Color.Black);//颜色
        var sf = new StringFormat
        {
            LineAlignment = StringAlignment.Center
        };
        g.DrawString("希希希", font, brush, width * 0.25f, height * 0.38f, sf);
    }
    image.Save(ms, ImageFormat.Jpeg);
}
ms.Seek(0, SeekOrigin.Begin);
return File(ms, "image/jpeg");
````

but i get this picture
![image](https://user-images.githubusercontent.com/20533465/42369769-88b33e28-813d-11e8-95fe-192f8b3439fc.png)

g.DrawString("希希希", font, brush, width * 0.25f, height * 0.38f, sf); 
this code lost 2 chinese code
why?
i think casue by libgdilpus

**Comment by quan01994** [comment]
but text=希希希.
i get this picture 
![image](https://user-images.githubusercontent.com/20533465/42370581-b5e19ece-813f-11e8-93b0-f289702dfdaa.png)

**Comment by filipnavara** [comment]
By default libgdiplus is compiled with Cairo font rendering only. This font rendering backend barely supports languages with Latin alphabet and it's broken for everything else in many unpredictable ways (no shaping, no complex layouts, no RTL). See https://github.com/mono/libgdiplus/pull/269.

**Comment by LuceLuo** [comment]
@filipnavara
I read a lap of articles and I know the problem, but I don't know the specific solution. Can you tell me how to install libgdiplus with pango?

**Comment by filipnavara** [comment]
Depends on your system, but in general you will have to build it yourself from source. The instructions are at https://github.com/mono/libgdiplus/blob/master/README.md. You need to pass the `--with-pango` flag to the `autogen.sh` script.

**Comment by LuceLuo** [comment]
I spent a day trying to compile it, I failed.
Do you have other convenient solutions?
@filipnavara

**Comment by quan01994** [comment]
@LuceLuo  on centos 7
yum install pango-devel,
then i build success ,but still lost text

**Comment by LuceLuo** [comment]
I successfully solved the problem of missing characters, but DrawImage does not support transparency of png.

**Comment by LuceLuo** [comment]
@quan01994
这个问题你已经解决了吗？

**Comment by quan01994** [comment]
@LuceLuo 什么问题

**Comment by quan01994** [comment]
@LuceLuo 用其他字符结尾，就能够显示，pango好像并不能解决这个问题。

**Comment by ArvinGitHubSource** [comment]
This problem solved?
I now also encounter this problem in production environment, I use a version of the.net  core 2.1
