### ISSUE TITLE
P/Invoke lost the first parameter when calling an export method of class from a 64-bit dll

### ISSUE THREAD

**Issue by hez2010** [dotnet/corefx#30862]
I found a problem when using P/Invoke.

C#:
```c#
using System;
using System.Runtime.InteropServices;

namespace ConsoleApp3
{
    class NativeMethods
    {
        [DllImport("./Project1.dll", CharSet = CharSet.Ansi, CallingConvention = CallingConvention.Cdecl, EntryPoint = "#3")]
        public static extern int TestX64(
            [MarshalAs(UnmanagedType.LPStr)] string a,
            [MarshalAs(UnmanagedType.LPStr)] string b,
            [MarshalAs(UnmanagedType.LPStr)] string c,
            [MarshalAs(UnmanagedType.LPStr)] string d);
    }
    class Program
    {
        static void Main(string[] args)
        {
            NativeMethods.TestX64("aaaa", "bbbb", "cccc", "dddd");
            Console.ReadKey();
        }
    }
}
```

C++:
Header.h
```cpp
#pragma once
#include <cstdio>

class __declspec(dllexport) test
{
public:
	int aaa(const char*, const char*, const char*, const char*) const;
};
```

Source.cpp:
```cpp
#include "Header.h"

int test::aaa(const char * a, const char * b, const char * c, const char * d) const
{
	printf("%s\n%s\n%s\n%s\n", a, b, c, d);

	return 0;
}
```

And finally I build both the dll and .NET app for 64-bit and run it, I got an error: 0xC0000005: Access violation reading location 0x0000000064646464.

Finally, I debug into Source.cpp and I found that the first parameter was not being passed into the function.
Normally, the parameters should be a = "aaaa", b = "bbbb", c = "cccc", d = "dddd", but actually I got a = "bbbb", b = "cccc", c = "dddd", d = \<invalid pointer\>

I've tried out both .NET Framework (4.7.1) and .NET Core (2.1), both of them have this issue.

And if you build both the dll and .NET app for 32-bit and run it in 32-bit mode (need to use stdcall), the problem doesn't exist.

**Comment by AndyAyersMS** [comment]
Shouldn't your C++ method be marked `static`? Otherwise you would need to pass it the implicit first `this` argument.

**Comment by jkotas** [comment]
As Andy said. You just got lucky that the mismatched signature works in 32-bit mode.
