### ISSUE TITLE
Please add APIs to determine the Unicode category of a UTF32 code point

### ISSUE THREAD

**Issue by gafter** [dotnet/corefx#30878]
Please add an API for determining the Unicode category of a code point resulting from a surrogate pair. Presumably I would compute that by starting with

``` c#
        public static int System.Char.ConvertToUtf32(char highSurrogate, char lowSurrogate) {
```

But there is no way to get the unicode category of the resulting code point.

The closest thing we have right now is this:

``` c#
        public static UnicodeCategory System.Char.GetUnicodeCategory(String s, int index) {
```

But that requires that we store the surrogates into a newly created string in order to get the Unicode category. That requires an unacceptably high allocation overhead.

The original problem I am trying to solve is https://github.com/dotnet/roslyn/issues/9731, https://github.com/dotnet/roslyn/issues/13474, and https://github.com/dotnet/roslyn/issues/13560.

**Comment by stephentoub** [comment]
https://github.com/dotnet/coreclr/pull/15911 added:
```C#
public static UnicodeCategory GetUnicodeCategory(int codePoint)
```
to `CharUnicodeInfo`, available in .NET Core 2.1.

**Comment by gafter** [comment]
Perfect! Thanks.
