### ISSUE TITLE
HashSet ISerializable implementation sets wrong type for the equality comparer.

### ISSUE THREAD

**Issue by nitroxis** [dotnet/corefx#30891]
The `HashSet<T>` `ISerializable` implementation sets the wrong type for its equality comparer in this line:

https://github.com/dotnet/corefx/blob/2e34bf9d93e23c2fdf978e457543b95906226721/src/System.Collections/src/System/Collections/Generic/HashSet.cs#L401

I believe this should be `typeof(IEqualityComparer<T>)`, not `typeof(IComparer<T>)`. I know this is legacy code, but it leads to issues when serializers that respect `ISerializable` encounter this type (i.e. an `InvalidCastException` is thrown).

**Comment by nitroxis** [comment]
I don't have a repro case at the moment. I was using a custom serializer that expects the instance loaded for an entry in a SerializationInfo to be compatible with the type of that entry. For `HashSet<T>`, an `ObjectEqualityComparer` is the default comparer, which does not implement `IComparer<T>`, hence the exception.

As for the behaviour in the full framework, it used `IEqualityComparer<T>`, as one would expect.
You can also see that in the reference source: https://referencesource.microsoft.com/#System.Core/System/Collections/Generic/HashSet.cs,367

I'm pretty sure the `IComparer<T>` in corefx is just a typo/oversight. I can try making a PR, but it really is just one line that needs changing, so if someone who is already set up with everything could change this it would be much faster.

**Comment by nitroxis** [comment]
Here is a very simple demonstration of the issue:
```csharp
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

static class Program
{
	static void Main()
	{
		HashSet<string> test = new HashSet<string>();
		SerializationInfo testData = new SerializationInfo(typeof(HashSet<string>), new FormatterConverter());
		test.GetObjectData(testData, new StreamingContext(StreamingContextStates.Other));

		foreach (SerializationEntry entry in testData)
		{
			if(!entry.ObjectType.IsInstanceOfType(entry.Value))
			{
				throw new Exception($"{entry.Value.GetType()} is not compatible with {entry.ObjectType}");
			}
		}
	}
}
```

This succeeds on .NET Framework 4.7 but throws an exception on .NET Core 2.1:
``'System.Collections.Generic.GenericEqualityComparer`1[System.String] is not compatible with System.Collections.Generic.IComparer`1[System.String]'``

**Comment by ViktorHofer** [comment]
I'll look into it. Karel pls always cc me when there's a (binary) serialization issue.

**Comment by ViktorHofer** [comment]
cc @stephentoub who introduced that change: https://github.com/dotnet/corefx/commit/0e62a603d1579eb5996caed44d8f1ae02ed5d76a#diff-a80c75678ed2d070e638bcb93ba26bccR376

**Comment by stephentoub** [comment]
> cc @stephentoub who introduced that change

I'd basically just copied the code out of netfx, so I'm not sure how that diff snuck in, but if it's wrong, we should fix it.
