### ISSUE TITLE
Improve the back pressure deadlock error

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#30894]
Today the error is "Advancing examined to the end would cause pipe to deadlock because FlushAsync is waiting.", we should improve this to be something like:

"The maximum buffer limit of {0} was exceeded." The exception should also be a specific type of exception that's easy to detect and throw your own error. Since this error may be thrown at a point where the `PipeReader` may not have control over the `Pipe` it came from this is important when trying to describe how to fix the problem.

# API proposed

``` C#
    public partial class BufferLimitExceededException : System.InvalidOperationException
    {
        public BufferLimitExceededException(string message) { }
    }
```

cc @pakrym @anurse

**Comment by NickCraver** [comment]
Related: #30689

**Comment by mgravell** [comment]
I did point out that the error message *at a minimum* needs some love, on that linked issue :)

**Comment by bitbonk** [comment]
I just ran into this exception. I didn't know what to do. I googled the exception text, first result was this github issue. Once I knew what the *actual* problem was, I could solve my problem easily.

**Comment by terrajobst** [comment]
We don't have another exception type. Instead, fix the error message.

**Comment by pksorensen** [comment]
I have been seeing this exception a few times today and not sure what i should look for to fix it :)

```
Unhandled Exception: Microsoft.AspNetCore.SignalR.HubException: The server closed the connection with the following error: Connection closed with an error. InvalidOperationException: Advancing examined to the end would cause pipe to deadlock because FlushAsync is waiting.
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at IO_Board.Builder.Program.Serve.<>c__DisplayClass4_0.<<OnExecuteAsync>b__1>d.MoveNext() in /src/IO-Board.Builder/Program.cs:line 272
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
