### ISSUE TITLE
Consider offering a Pipe allocation strategy that does array re-sizes instead of using a linked list of segments

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#30893]
Today the default `Pipe` implementation exposes a linked list of buffers with fixed segment sizes. In some scenarios, it might be more performant to re-size a single array instead of using a linked list.

Pros:
- It speeds up `ReadOnlySequence<T>` operations (Slice, GetPosition etc)
- Simpler to deal with a single buffer `ReadOnlySequence<T>`

Cons:
- More memory copies
- Potentially more memory usage (do you shrink the buffer?)

This could be an option on the `PipeOptions` or it could be another `Pipe` implementation. 

cc: @pakrym

**Comment by pakrym** [comment]
Which scenarios would this be useful in? 
I think it should be new PipeType altogether, not having linked list would simplify/speedup implementation a lot

**Comment by davidfowl** [comment]
We don't think this is useful.
