### ISSUE TITLE
Debugging test projects inside VS doesn't work anymore after the switch to SDK project style projects

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#30913]
It just builds the assembly and doesn't invoke the xunit runner.

cc @eerhardt @weshaggard @danmosemsft

**Comment by ViktorHofer** [comment]
> Add launchSettings.json files for all test projects.

To avoid the duplication, isn't it possible to add the launchsettings file to the project similar to what we do with Directory.Build.props but just for test projects?

**Comment by eerhardt** [comment]
I'm not sure, @Pilchie didn't seem to think so in [this comment](https://github.com/dotnet/project-system/issues/3684#issuecomment-401857589).  Also - it looks like `dotnet/roslyn` has the dupication: https://github.com/dotnet/roslyn/pull/21014/files

**Comment by Wraith2** [comment]
I've been trying to work through changes in various test projects and finding it very frustrating that I can't debug tests. It's slow and tedious to try and parse assertion traces back to the code manually. The documentation also claims that it works, if it is known not to then please at least update the docs to reflect that.

**Comment by ViktorHofer** [comment]
@Wraith2 debugging in VS worked before https://github.com/dotnet/corefx/commit/0b0f63d47951773cc46393312d80b40176d3a413 was merged, which happened yesterday evening. We are working on a fix in this issue. Please stay patient.

**Comment by Wraith2** [comment]
Then I'm having a different problem because it hasn't worked for me since I started trying to work on corefx. Breakpoints simply don't get hit, no symbols are loaded even though the debugger will break on asserts.

**Comment by keeratsingh** [comment]
Here is another workaround which has worked for me while debugging `System.Data.SqlClient` Tests.

1. Add the following code in the beginning of your test code, this essentially waits for you to attach the debugger.
```cs
// Add the following references
// using System.Diagnostics;
// using System.Threading;

while (!Debugger.IsAttached)
{
    Console.WriteLine("Waiting for debugger to attach");
    Thread.Sleep(2000);
}
Console.WriteLine("Debugger attached");
```
2.  Run all the tests or a particular test in a class
#### Run all the tests 
note the `/p:XunitOptions=-class` flag
```cmd
cd d:/corefx/src/System.Data.SqlClient/tests/ManualTests & msbuild /t:RebuildAndTest "/p:XunitOptions=-class System.Data.SqlClient.ManualTesting.Tests.DataReaderTest -showProgress" & cd d:/corefx/;
```
#### Run a particular test
note the `/p:XunitOptions=-method` flag
```cmd
cd d:/corefx/src/System.Data.SqlClient/tests/ManualTests & msbuild /t:RebuildAndTest "/p:XunitOptions=-method System.Data.SqlClient.ManualTesting.Tests.DataReaderTest.LoadReaderIntoDataTableToTestGetSchemaTable -showProgress" & cd d:/corefx/;
```
3. Attach debugger from Visual Studio `Ctrl+Alt+P`

**Comment by keeratsingh** [comment]
@Wraith2 
>Do you use this because you can't debug in VS or because it fits more easily into a separated workflow that you already use?

This is a workaround for the time being until the issue is fixed. It was working as expected and I was able to debug using VS before 0b0f63d as mentioned above.

> I'm also curious as to how you have msbuild on path, I don't and there are a few instructions in the docs which use it as if it were.

You should see msbuild in the path when you open `Visual Studio 2017 Developer Command Prompt`
#### Visual Studio 2017 Developer Command Prompt location
```
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Visual Studio 2017\Visual Studio Tools\Developer Command Prompt for VS 2017
```
#### msbuild location and version
```
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.7.4
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>where msbuild
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>msbuild /version
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.7.179.6572
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>

```

**Comment by Wraith2** [comment]
The build process runs the vscmd batch file, I don't start that way but I could, I doubt it would change anything. I've seen some other discussion recently about using an in-box msbuild version so it may change anyway.

I've never been able to debug with VS before or after this change so I think I'm hitting a separate issue. I'll wait until this issue clears and then recheck whether I can debug tests, any tests. If I can't I'll raise a separate issue for it.

**Comment by ViktorHofer** [comment]
Update: F5 launch with debugger is now working but breakpoint are not hit reliably. Will follow-up to get debugging working reliably.

**Comment by danmosemsft** [comment]
I was seeing breakpoints in product getting hit but not in tests (although they seemed to bind). Even offer, test code was not visible on stack. As if the test assembly was being treated as "just my code  ". So you have an idea what's going on, Viktor?

**Comment by lkts** [comment]
I want to bump this and say that inability to set breakpoints in test code is pretty confusing.

**Comment by danmosemsft** [comment]
Debugger team supplied an internal build of VS with a fix, next step is to verify it.

**Comment by ViktorHofer** [comment]
I just validated our internal build and the issue is gone. I'm in close contact with the debugger team to discuss if a back port to Dev15 is possible but I doubt it as the complexity of the fix seems very high.

**Comment by albertocorrales** [comment]
> Here is another workaround which has worked for me while debugging `System.Data.SqlClient` Tests.
> 
> 1. Add the following code in the beginning of your test code,
> 
> #### Local Debugging
> This launches a dialog to choose a VS to use for debugging.
> 
> ```cs
> // Add the following reference
> // using System.Diagnostics;
>  Debugger.Launch();
> ```
> 
> #### Remote Debugging
> This essentially waits for you to attach the debugger.
> 
> ```cs
> // Add the following references
> // using System.Diagnostics;
> // using System.Threading;
> 
> while (!Debugger.IsAttached)
> {
>     Console.WriteLine("Waiting for debugger to attach");
>     Thread.Sleep(2000);
> }
> Console.WriteLine("Debugger attached");
> ```
> 
> 1. Run all the tests or a particular test in a class
> 
> #### Run all the tests
> note the `/p:XunitOptions=-class` flag
> 
> ```batchfile
> cd d:/corefx/src/System.Data.SqlClient/tests/ManualTests & msbuild /t:RebuildAndTest "/p:XunitOptions=-class System.Data.SqlClient.ManualTesting.Tests.DataReaderTest -showProgress" & cd d:/corefx/;
> ```
> 
> #### Run a particular test
> note the `/p:XunitOptions=-method` flag
> 
> ```batchfile
> cd d:/corefx/src/System.Data.SqlClient/tests/ManualTests & msbuild /t:RebuildAndTest "/p:XunitOptions=-method System.Data.SqlClient.ManualTesting.Tests.DataReaderTest.LoadReaderIntoDataTableToTestGetSchemaTable -showProgress" & cd d:/corefx/;
> ```
> 
> 
> * Choose Visual Studio Version to use for Debugging [Local Debugging]
>   OR
> * Attach debugger from Visual Studio `Ctrl+Alt+P` [Remote Debugging]
> 
> Edit: Added a more convenient way for local debugging.

With Debugger.Launch(); workaround I see he pop-up, but my breakpoints in VS 2017 never stop. 
With while (!Debugger.IsAttached) I manage to stop the process in the while. However, when I attach VS to dotnet.exe it continues without stopping in my breakpoints.

I guess I will have to wait until the fix is out.

**Comment by MarcoRossignoli** [comment]
My tracking of this very important issue(I couldn't find a way to receive an email only for *special* issue/PR...my notification settings are Watching(Web) Participating(Email,Web)...could be useful if github would allow to choose to override default notification behaviour with some checkbox per issue, for now `Notifications for the conversations you are participating in`).
Guys if you've better way let me know. Sorry for noise.

**Comment by Wraith2** [comment]
There should be a Subscribe button on the right hand side under tags, miltestones asignees etc that would add notifications for you.

**Comment by MarcoRossignoli** [comment]
> There should be a Subscribe button on the right hand side under tags, miltestones asignees etc that would add notifications for you.

Yes I'm already subscribed...but in notification settings for Watching preference I checked only Web, so I get updates only on "Web site"(through notification bell on top right)...but I would receive also an email only for some of all repo/issue,pr that are interesting to me without participating, only as observer. I'm whatching some repos but I don't want receive email for all...but I would receive email where I'm participating and some other "selected" issue/pr.

**Comment by Wraith2** [comment]
I saw a PR which I think enabled the VS2019 build tools. Has anyone tried test debugging in it yet? If it doesn't work we'll need to feed back to them while in preview.

**Comment by joshfree** [comment]
@ViktorHofer is there a specific recommended build for people to use?  This has been a long open problem.  thanks

**Comment by ViktorHofer** [comment]
Yes VS2019 preview-2 when it comes out. Msft employees can use the latest intpreview dogfood build.

**Comment by ahsonkhan** [comment]
> VS2019 preview-2

FWIW, I was able to debug S.T.Json tests from VS (using F5, but not from the test explorer).

**Comment by Wraith2** [comment]
I'm trying to use preview2 and getting a native build problem. I synced from master, clean -all and then build -debug and the native component compilation fails to identify the cmake version. I've had this working on the 2017 tools for months now so it's unlikely that my version of cmake isn't working but I updated to 3.13 anyway, still no go. I've checked [development environment](https://github.com/dotnet/corefx/wiki/Development-environment-setup-for-Windows) setup guide and made sure everything on there is installed.

The problem seems to be in compiling the compiler identification app, [CMakeError.log](https://github.com/dotnet/corefx/files/2795788/CMakeError.log) Is this worth a separate issue?

**Comment by Wraith2** [comment]
hmm, no lib environment variable and I don't have the `Enterprise` part of the path, the rest underneath it is correct. I can find the MSVCRTD.lib file in both the x86 and x64 folders so it looks like it just isn't finding that path. Setting lib to that path (in the command prompt, not machinewide) and re-running doesn't change the error.

**Comment by danmosemsft** [comment]
If you're in a VS2017 Developer command prompt, I am very surprised that LIB (and INCLUDE?) are not defined. I don't know how Cmake works, but generally I would expect native compilation to expect those.

Any idea what changed since this worked for you last?

**Comment by Wraith2** [comment]
The build process runs the prompt, I never needed to:
```
  **********************************************************************
  ** Visual Studio 2019 Developer Command Prompt v16.0.0-pre.2.0
  ** Copyright (c) 2018 Microsoft Corporation
  **********************************************************************
  **********************************************************************
  ** Visual Studio 2019 Developer Command Prompt v16.0.0-pre.2.0
  ** Copyright (c) 2018 Microsoft Corporation
  **********************************************************************
  [vcvarsall.bat] Environment initialized for: 'x86_x64'
  Commencing build of native components

  -- The C compiler identification is unknown
  -- The CXX compiler identification is unknown
  CMake Error at CMakeLists.txt:21 (project):
  -- Configuring incomplete, errors occurred!
  See also "E:/Programming/csharp7/corefx/artifacts/obj/native/netcoreapp-Windows_NT-Debug-x64/CMakeFiles/CMakeOutput.log".
  See also "E:/Programming/csharp7/corefx/artifacts/obj/native/netcoreapp-Windows_NT-Debug-x64/CMakeFiles/CMakeError.log".
    No CMAKE_C_COMPILER could be found.



  CMake Error at CMakeLists.txt:21 (project):
    No CMAKE_CXX_COMPILER could be found.



  Failed to generate native component build project!
E:\Programming\csharp7\corefx\src\Native\build-native.proj(48,5): error MSB3073: The command ""E:\Programming\csharp7\corefx\src\Native\build-native.cmd" x64 Debug Windows_NT outconfig netcoreapp-Windows_NT-Debug-x64" exited with code 1.

Build FAILED.
```

What changed is using preview2, on 2017 it was working fine. Given that you have a different path and until preview2 was available it may be that internal builds installed to a different path and it needs that extra subdirectory, I can't work out what file it's actually trying to build though so i'm having trouble tracking it down.

**Comment by danmosemsft** [comment]
Did you reboot since installing preview 2? It modifies global environment variables, which is why VS install sometimes requests a reboot.

**Comment by Wraith2** [comment]
Yes. It requested one and got one.

**Comment by ViktorHofer** [comment]
Yes that's a known issue. Please use the Developer Command Prompt for VS 2017 when building. This should be fixed in a few days / weeks.

**Comment by danmosemsft** [comment]
Do you have `Developer Command Prompt for VS 2017 ` in your start menu? If so open that, then run the build inside that.

**Comment by Wraith2** [comment]
oh, that simple, neat. I'll give it a try, thanks.

**Comment by ViktorHofer** [comment]
Closing this issue as debugging with Visual Studio 2019 Preview 2 works again as expected.
