### ISSUE TITLE
System.IO.FileSystem.Primitives shows warnings when used in .NET Framework 4.7.1

### ISSUE THREAD

**Issue by cremor** [dotnet/corefx#30910]
This is not about .NET Core, but about using the [System.IO.FileSystem.Primitives package](https://www.nuget.org/packages/System.IO.FileSystem.Primitives/) (which is contained in this repository) in .NET Framework.

If you add the System.IO.FileSystem.Primitives package to a project that targets a .NET Framework version from 4.6 to 4.7, everything works fine. So Visual Studio finds the referenced assembly and copies it to the output folder. But if you do the same with a project that targets 4.7.1, Visual Studio shows the warning "The referenced component 'System.IO.FileSystem.Primitives' could not be found." and does not copy the assembly to the output folder.

Maybe related to #30754. The question there was if the same warning still happens if you reference some code in the package. I don't know how to do this since the assembly doesn't contain any types, just type forwardings.
Note: I'm getting this package as a dependency from the [System.IO.Packaging package](https://www.nuget.org/packages/System.IO.Packaging/), which itself is also only a dependency. But the problem can be reproduced by installing System.IO.FileSystem.Primitives directly.

Visual Studio 15.7.4
Windows 10 1709 with .NET Framework 4.7.1 (4.7.2 is NOT yet installed)

**Comment by ViktorHofer** [comment]
cc @AlexGhiondea @ericstj

**Comment by ericstj** [comment]
It’s part of the framework in .net 4.7.1 so the nuget package should be removed by the build.  I suspect this warning is just the project system having trouble matching the reference in the project to the one that’s in the targeting pack. @dsplaisted does that sound correct?

**Comment by cremor** [comment]
Something else that I noticed:
The warning is also visible in the solution explorer if you expand the "References" node. If you inspect the properties of the System.IO.FileSystem.Primitives assembly, it looks like a reference that is indeed missing (some fields like path and version are empty).

So maybe this is just the IDE that is confused because the build removes the reference?

**Comment by AlexGhiondea** [comment]
The warning goes away with @dsplaisted changes to conflict resolution, but the warning in the references in the IDE does not.

**Comment by cremor** [comment]
Sorry, but what changes do you mean?

**Comment by cremor** [comment]
I didn't add the reference myself. I just installed the NuGet package DocumentFormat.OpenXml, which has a dependency on System.IO.Packaging, which then has the dependency on System.IO.FileSystem.Primitives. This resulted in the assembly reference and warning.

**Comment by pantonis** [comment]
Same problem here. Not just with this packages but also a lot other packages. Only difference is that I target .NET 4.7.2

**Comment by dsplaisted** [comment]
I am able to reproduce this issue.  It occurs when the .NET Framework project uses packages.config instead of PackageReference.  In that case, installing the package adds the following to the project file:

```xml
    <Reference Include="System.IO.FileSystem.Primitives, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>..\packages\System.IO.FileSystem.Primitives.4.3.0\lib\net46\System.IO.FileSystem.Primitives.dll</HintPath>
      <Private>True</Private>
    </Reference>
```

Conflict resolution ends up removing this reference and replacing it with a framework reference to System.IO.FileSystem.Primitives, which causes VS to generate the following warning:

> The referenced component 'System.IO.FileSystem.Primitives' could not be found.

A workaround is to either delete the reference NuGet added to the project file, or to replace it with the following:

```xml
<Reference Include="System.IO.FileSystem.Primitives" />
```

**Comment by cremor** [comment]
The workaround with the replaced reference looks good, thanks.

While testing this I even noticed something: If you manually add the reference in Visual Studio by Add Reference -> Browse -> choose "packages\System.IO.FileSystem.Primitives.4.3.0\lib\net46\System.IO.FileSystem.Primitives.dll", Visual Studio will just add the same simple reference (without a path) as described in your workaround. So maybe it's actually a bug in the NuGet package manager that adds a wrong reference on install?

**Comment by JeremyKuhne** [comment]
As `packages.config` is depreciated and this has a workaround, closing.
