### ISSUE TITLE
Convert.FromBase64String() Only Supports Specific Implementations

### ISSUE THREAD

**Issue by StrangeWill** [dotnet/corefx#30948]
Kind of an annoying one, when attempting to Call `Convert.FromBase64String` on an e-mail attachment (specifically over the GMail API in this case) you *can* get the following exception:

`FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.`

Caused by different index 62/63 values as listed here:
https://en.wikipedia.org/wiki/Base64#Implementations_and_history

Doing this fixes it:
`attachment.Data.Replace('-', '+').Replace('_', '/')`

This seems like somewhat of a sloppy fix though, and was a weird one to hunt down being as I didn't even _know_ there were multiple base64 specs in the wild.

So this e-mail is specifically using RFC 4648 or RFC 7515, probably a weird client, but still valid Base64.

Though I'm not even sure if much can be done -- can we _try_ to automatically detect this? Padding character behavior is all over the replace depending on RFC, or handling of characters outside of the alphabet. Is this maybe the responsibility of a 3rd party lib to handle weird esoteric implementations?

**Comment by gfoidl** [comment]
This is _base64url_, for an implementation see [WebEncoders](https://github.com/aspnet/Common/blob/d7a3ef5d126c2d767a26879db9ebc3d805b89014/shared/Microsoft.Extensions.WebEncoders.Sources/WebEncoders.cs#L23) (or the "hopefully" enhanced implementation in https://github.com/aspnet/Common/pull/338).

> probably a weird client

For that kind of clients ("web based") it's rather the usual one. So the correct RFC is more or less given by the topic, or documented otherwise.

**Comment by joshfree** [comment]
@GrabYourPitchforks

**Comment by StrangeWill** [comment]
> This is base64url, for an implementation see WebEncoders (or the "hopefully" enhanced implementation in aspnet/Common#338).

Welp, yeah that was kind of silly on my part, I should have found that. Google's docs throw me off because Java has a `Base64` implementation which you _can_ specify accepts `base64url` as a boolean on the constructor (Google is lacking on C# examples for a lot of their stuff), and only supports a total of 3 different implementations (because supporting the rest is probably borderline pointless), so they're not doing anything really that different from how .NET is doing it (we just do that in different classes).

Not sure if there is any continued value to centralize that behavior between `WebEncoders` and `Convert`, if not feel free to close this ticket.
