### ISSUE TITLE
Pipelines: best practices for managing flushing

### ISSUE THREAD

**Issue by roji** [dotnet/corefx#30941]
While working on Npgsql and pipelines, I ran into an interesting question - when should I actually flush my PipeWriter? Obviously, once the entire data has been written I should flush to make sure data is actually made available to the reader (which in my case would mean writing buffered data to a network socket). However, I also expect to need to flush in order to avoid buffering too much in memory.

To clarify, a user may hand my driver some extremely large data values to send to PostgreSQL. It's my understanding that if I simply get Spans/Memory's from my PipeWriter, write data and then call `Advance()`, I end up buffering the entire data in memory, which is definitely something that needs to be avoided. Is my understanding correct? Can this behavior (continually buffer more until flush) be considered standard for all PipeWriter implementations, or can/should it be expected to vary?

If the above is true, I could of course decide on an arbitrary (and/or configurable) size beyond which my code flushes. However, there doesn't seem to be any easy way to know how much data is currently buffered for writing inside a pipe; when you use a traditional stream, you're responsible for keeping track yourself of how much you've written, but I think it doesn't make sense for PipeWriter to require you to do the same - imagine multiple application components involved in writing a message, and having to pass around the amount written alongside the PipeWriter.

Assuming the above is correct, does it make sense to add some accessor to PipeWriter which exposes how much data is pending for write? Or have I completely misunderstood pipelines?

**Comment by mgravell** [comment]
I've spoken to folks previously about a `.Length` / `.Count` on the pipe, but not for this purpose - just for diagnostic system health monitoring reasons.

For when to flush: *don't hold back*. In most cases, flush is synchronous. Flush is really "make sure the writer is active, and apply throttling if I'm out-pacing the consumer" (presumably the network in your case), so there's really no reason to be shy of flushing. Obviously you wouldn't flush for every fragment of a header, for example, but  as long as you're passing decent sized chunks, *flush away*. In your example of extremely large data values - presumably we're talking large BLOBs/CLOBs or data-table style objects? Personally, I'd try to flush at least once every 8k or so and once at the end, but that's not a magic number chosen for any meaningful reason - it is just an arbitrary decent sized chunk.

**Comment by davidfowl** [comment]
There have been requests to expose a Length property on the PipeWriter that would return the amount to buffer but its really up to your protocol to decide when flushing is appropriate. If you write over the `PauseWriterThreshold` will stop you from writing more, but if you do over-sized writes that break the threshold but you can still buffer "too much". I think the best you can do right now is chunk up writes and flushes when the user written object is over some size.

**Comment by roji** [comment]
Thanks for your responses - it more or less confirms my understanding of the situation.

@mgravell

> For when to flush: don't hold back. In most cases, flush is synchronous. Flush is really "make sure the writer is active, and apply throttling if I'm out-pacing the consumer" (presumably the network in your case), so there's really no reason to be shy of flushing. Obviously you wouldn't flush for every fragment of a header, for example, but as long as you're passing decent sized chunks, flush away. In your example of extremely large data values - presumably we're talking large BLOBs/CLOBs or data-table style objects? Personally, I'd try to flush at least once every 8k or so and once at the end, but that's not a magic number chosen for any meaningful reason - it is just an arbitrary decent sized chunk.

I understand that pipelines is an abstraction, but the idea that flush is synchronous "in most cases" can be a bit problematic... Specifically, isn't it important for perf for the producer to know when an actual I/O system call occurs and when it doesn't (regardless of whether it blocks for any length of time)? Regardless of the above question, I do agree that 8KB is a good figure - Npgsql currently has 8KB as its default read and write buffers.

@davidfowl 

> its really up to your protocol to decide when flushing is appropriate.

At least in the PostgreSQL case, the protocol doesn't care at all about flushing how packets are segmented - as long as you send everything correctly it can be segmented any way you like. So it really is a perf tuning question, to make sure flushing (in the I/O sense) doesn't occur unless necessary; this would create packet fragmentation, and also add system call overhead.

But going back to my specific issue, the problem is *how* to know when I've written 8KB. Writing is a pretty complex process split across multiple classes, and it currently seems necessary manually track bytes written myself, passing around this value to everyone involved.

To provide an example, sending a query to the database for execution involves sending multiple wire protocol messages (ideally packed in a single packet and flushed once, if they fit). One of these messages (Bind) contains the list of parameters to the command, and one of these parameters can be an array of strings. The type handler responsible for writing the binary representation of a PostgreSQL array delegates to the string type handler for each of its values. Flushing may happen at any point while writing the array; it could be an array of one single huge string (so the flush would need to happen inside the string handler), or an array of many small strings (so the flush would need to happen inside the array handler). All these components would need to cooperate, passing a "currently buffered bytes" value back and forth.

To me it makes sense to have this tracked and exposed by PipeWriter, does anyone have any objections? Can we keep this issue open to track that?

**Comment by roji** [comment]
Thanks for your responses - it more or less confirms my understanding of the situation.

@mgravell

> For when to flush: don't hold back. In most cases, flush is synchronous. Flush is really "make sure the writer is active, and apply throttling if I'm out-pacing the consumer" (presumably the network in your case), so there's really no reason to be shy of flushing. Obviously you wouldn't flush for every fragment of a header, for example, but as long as you're passing decent sized chunks, flush away. In your example of extremely large data values - presumably we're talking large BLOBs/CLOBs or data-table style objects? Personally, I'd try to flush at least once every 8k or so and once at the end, but that's not a magic number chosen for any meaningful reason - it is just an arbitrary decent sized chunk.

I understand that pipelines is an abstraction, but the idea that flush is synchronous "in most cases" can be a bit problematic... Specifically, isn't it important for perf for the producer to know when an actual I/O system call occurs and when it doesn't (regardless of whether it blocks for any length of time)? Regardless of the above question, I do agree that 8KB is a good figure - Npgsql currently has 8KB as its default read and write buffers.

@davidfowl 

> its really up to your protocol to decide when flushing is appropriate.

At least in the PostgreSQL case, the protocol doesn't care at all about flushing how packets are segmented - as long as you send everything correctly it can be segmented any way you like. So it really is a perf tuning question, to make sure flushing (in the I/O sense) doesn't occur unless necessary; this would create packet fragmentation, and also add system call overhead.

But going back to my specific issue, the problem is *how* to know when I've written 8KB. Writing is a pretty complex process split across multiple classes, and it currently seems necessary manually track bytes written myself, passing around this value to everyone involved.

To provide an example, sending a query to the database for execution involves sending multiple wire protocol messages (ideally packed in a single packet and flushed once, if they fit). One of these messages (Bind) contains the list of parameters to the command, and one of these parameters can be an array of strings. The type handler responsible for writing the binary representation of a PostgreSQL array delegates to the string type handler for each of its values. Flushing may happen at any point while writing the array; it could be an array of one single huge string (so the flush would need to happen inside the string handler), or an array of many small strings (so the flush would need to happen inside the array handler). All these components would need to cooperate, passing a "currently buffered bytes" value back and forth.

To me it makes sense to have this tracked and exposed by PipeWriter, does anyone have any objections? Can we keep this issue open to track that?

**Comment by davidfowl** [comment]
Sure turn this into an official API proposal.

**Comment by roji** [comment]
Closing in favor of #31074 (official API proposal).
