### ISSUE TITLE
Path.GetFullPath no longer throws for invalid characters in .NET Core 2.1

### ISSUE THREAD

**Issue by loop-evgeny** [dotnet/corefx#30945]
According to the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getfullpath?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.IO.Path.GetFullPath)%3Bk(DevLang-csharp)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=netcore-2.1) `Path.GetFullPath` should throw an exception for paths containing invalid characters.

In .NET Core 2.0 it does: `Path.GetFullPath("C:\inval|d")` throws. In .NET Core 2.1 this returns the input path.

**Comment by karelz** [comment]
@JeremyKuhne was that intentional change?

**Comment by danmosemsft** [comment]
Yes, see https://github.com/dotnet/coreclr/commit/a0cfda07fbdc319d8e5137a1b28d190ec242597e and https://github.com/dotnet/corefx/issues/26359

Essentially we can never get the checks right - they depend on the file system - we now rely on file system operations to validate paths.

We need an issue opened against the dotnet/docs repo. @JeremyKuhne any other API's need doc updates from your 2.1 work?

**Comment by JeremyKuhne** [comment]
There is an issue open on it already: https://github.com/dotnet/docs/issues/4483

**Comment by JeremyKuhne** [comment]
As stated, this was by design.
