### ISSUE TITLE
UseShellExecute cause exception on linux

### ISSUE THREAD

**Issue by tamasVajda** [dotnet/corefx#30942]
if in ProcessStartInfo (system.Diagnostic) UseShellExecute is set to true on linux process start cause the following exception: No such file or directory win32 exception at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)

process start called in Kestrel webserver's request handler, this process should execute script and set linux specific permissions.

operating system: Cent OS 7 (executed the published application) 
dotnet core version 2.1.300

workaround:

if UseShellExecute doesn't set, it solve the problem.

**Comment by karelz** [comment]
@tamasVajda can you reproduce the problem with any script, also outside of ASP.NET Core in HelloWorld style .NET Core app?

**Comment by krwq** [comment]
@tamasVajda unfortunately current info might be too little to get a repro. Could you help us answering following questions?

- Could you copy & paste as little code as possible to show the exception?
- Could you copy & paste the whole exception message?
- What is the output of `dotnet --info` on the computer where app was built?
- What is the output of `dotnet --info` on the computer where app was run?
- How was the app built/published? (please share the command line)
- What binaries were copied on the machine where the app was executed?

**Comment by tmds** [comment]
> this process should execute script

If you execute a script (like a bash script which has the executable flag set) using `Process`, `UseShellExecute` should be set to `false`.
`UseShellExecute` is meant to let the OS shell figure out what program to start for the filename. For example, `FileName` is `http://www.dot.net` and the OS shell starts a browser.

**Comment by tamasVajda** [comment]
@krwq :
code:

```
 public void RunSript(string shellname, string workingDir, string arguments = "")
        {
            var process = new Process()
            {
                StartInfo = new ProcessStartInfo
                {
                    FileName = shellname,
                    Arguments = arguments,
                    UseShellExecute = true,
                    CreateNoWindow = true,
                    ErrorDialog = false,
                    WorkingDirectory = workingDir
                }
            };

            process.Start();
        }
```

caling this via:
 ```
if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
                {
                    RunSript("/usr/bin/sudo", installPath, "chmod a+x " + scriptPath);
                }
```

**Comment by tamasVajda** [comment]
@tmds:
Thank for the informations, but why changed hat ebehavior of dotnet 2.0 and dotnet 2.1? in dotnet 2.0 there wasn't any exception (but maybe this useshelexecute was ignored) and why throw it file not found in this case? Not suppoerted or similar exception would be more understandable.

**Comment by tmds** [comment]
With UseShellExecute on Linux, it tries to find one of these programs:
https://github.com/dotnet/corefx/blob/e0ba7aa8026280ee3571179cc06431baf1dfaaac/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Linux.cs#L106
when no program is found it throws here:
https://github.com/dotnet/corefx/blob/a060c9669865f0089e293360deb44941f441d238/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs#L314-L317

> why changed hat ebehavior of dotnet 2.0 and dotnet 2.1?

For 2.0 this was the behavior:

https://github.com/dotnet/corefx/blob/965ff68604e44cda1f512c9d7116f28c148657c4/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs#L236-L239

It was changed here: https://github.com/dotnet/corefx/pull/23705

**Comment by stephentoub** [comment]
> when no program is found it throws here

Rather than throwing, should we fall back to just using `sh` as was done in 2.0?

**Comment by tmds** [comment]
> Rather than throwing, should we fall back to just using sh as was done in 2.0?

The behavior would change based on the the installed applications (xdg-open, ...), which is not good.
If one of the apps is installed, it would open up the script in an editor.
If none of the apps is installed, it would successfully execute the script.
