### ISSUE TITLE
Calling an VB.Net String-functions (like Left(string),Right(string),Space(string),Trim(string)) in a .NET Core project throwing Runtime exceptions

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#30963]
@amshekar commented on [Mon May 21 2018](https://github.com/dotnet/core/issues/1577)

# Calling an VB.Net String-functions (like Left(string),Right(string),Space(string),Trim(string)) in a .NET Core project throwing Runtime exceptions

# General

We have a .Net core 2.0 webapi project and want to call a old vb.net method. The method have some string functions like Left,right,space and trim . We added the DLL as a reference . But in runtime we are getting method not found exception.

like

> Method not found: 'System.String Microsoft.VisualBasic.Strings.Left(System.String)'.'
> Method not found: 'System.String Microsoft.VisualBasic.Strings.Space(System.String)'.'
> Method not found: 'System.String Microsoft.VisualBasic.Strings.Right(System.String)'.'

Any help\advice is most appreciated .
We might not changes the old custom dll code which have dependencies with other systems.
If we want to do the modification in old dll if possible what would be the better approach with minimum impact

---

@amshekar commented on [Sat May 26 2018](https://github.com/dotnet/core/issues/1577#issuecomment-392256797)

refer the following git repo where we have one console app on dotnet core . From this we are making a call to vb.net classlibrary which has string functions. 

https://github.com/csreehari/FxReferenceConsoleAppCore.git

---

@Petermarcu commented on [Tue Jun 12 2018](https://github.com/dotnet/core/issues/1577#issuecomment-396804306)

@jaredpar

**Comment by danmosemsft** [comment]
We should add these and the next action on me is to put up a PR to reference source so that we can add them.

@amshekar I would like to add these for .NET Core 3.0: in the near term, you will need to modify this code to use equivalent methods on the `String` class.

**Comment by danmosemsft** [comment]
@jaredpar yes, we agreed to open it it's just not happened.

I'll dupe this against https://github.com/dotnet/corefx/issues/26386

**Comment by danmosemsft** [comment]
It's on my plate BTW.

**Comment by danmosemsft** [comment]
Also dupes
https://github.com/dotnet/corefx/issues/8808
https://github.com/dotnet/corefx/issues/14300
