### ISSUE TITLE
System.IO.Pipelines nuget package does not carry .xml file

### ISSUE THREAD

**Issue by AArnott** [dotnet/corefx#30978]
The System.IO.Pipelines 4.5.0 nuget package (as found in the `C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.io.pipelines\4.5.0` folder) does not contain .xml API documentation for the assembly. This, combined with the lack of any useful documentation online for the assembly, makes it guesswork to understand how to properly use this library. 

It's an awesome library, but it took me half a day to figure out why it was hanging in a particular scenario. (I later found it to be #30689, BTW).

**Comment by davidfowl** [comment]
😓 /cc @weshaggard? How do these things work?

**Comment by weshaggard** [comment]
Generally we depend on the doc team to produce xml intellisense comments but currently we haven't been documenting our nuget packages yet. 

In the mean time we can make this project output the xml doc comments it contains in code by setting https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System.Collections.Immutable.csproj#L8 in its project. That should automatically get picked up by our packaging and put in the nuget package.

**Comment by AArnott** [comment]
Should we service the fallback package in VS installation to include that file, or do folks need to update to 4.5.1?

**Comment by weshaggard** [comment]
We wouldn't hack up the nuget fallback folder to change the contents of an extracted package. It would require that we service the package to add this and then get the fallback cache updated with the newer package.

**Comment by pakrym** [comment]
I checked https://www.nuget.org/packages/System.IO.Pipelines/4.5.3-servicing-27114-05 and https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.IO.Pipelines/4.6.0-preview.18578.2 both contain xml docs.
