### ISSUE TITLE
Code coverage: jump to source for CoreLib daily coverage runs is broken

### ISSUE THREAD

**Issue by pjanotti** [dotnet/corefx#30974]
The sources are not present in the path specified in the PDB and as such there is no source information on the daily coverage runs.

**Comment by stephentoub** [comment]
@pjanotti, coverage data also seems to be wrong for corelib, e.g.
![image](https://user-images.githubusercontent.com/2642209/42639774-d712d67a-85be-11e8-93f4-0cd43a1dab3d.png)

**Comment by pjanotti** [comment]
@stephentoub that last successful one was against native image of CoreLib so still broken numbers. The latest runs against the IL CoreLib have numbers:
![image](https://user-images.githubusercontent.com/5600755/42651276-cc72847c-85c3-11e8-9b45-fa0461c8bafe.png)

This one was from https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/608/Code_Coverage_Report/ it shows as failure due to a test failure and a crash in other one. Until the crashes are investigated I suggest going to https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/ first and opening the coverage report for the latest completed run.

**Comment by pjanotti** [comment]
Just for the record, here are the failures on run #608:
```
D:\j\workspace\code_coverage---b14a30e5\dir.traversal.targets(81,3): warning MSB4011: "D:\j\workspace\code_coverage---b14a30e5\Tools\Dumpling.targets" cannot be imported again. It was already imported at "D:\j\workspace\code_coverage---b14a30e5\Tools\tests.targets (580,3)". This is most likely a build authoring error. This subsequent import will be ignored. [D:\j\workspace\code_coverage---b14a30e5\src\tests.builds]
D:\j\workspace\code_coverage---b14a30e5\Tools\tests.targets(514,5): warning :    System.Globalization.CalendarsWithConfigSwitch.Tests  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 0.876s [D:\j\workspace\code_coverage---b14a30e5\src\System.Globalization.Calendars\tests\CalendarTestWithConfigSwitch\System.Globalization.CalendarsWithConfigSwitch.Tests.csproj]
D:\j\workspace\code_coverage---b14a30e5\Tools\tests.targets(514,5): warning MSB3073: The command "D:\j\workspace\code_coverage---b14a30e5\bin/tests/System.Globalization.CalendarsWithConfigSwitch.Tests/netcoreapp-Windows_NT-Debug-x64//RunTests.cmd D:\j\workspace\code_coverage---b14a30e5\bin/testhost/netcoreapp-Windows_NT-Debug-x64/" exited with code 1. [D:\j\workspace\code_coverage---b14a30e5\src\System.Globalization.Calendars\tests\CalendarTestWithConfigSwitch\System.Globalization.CalendarsWithConfigSwitch.Tests.csproj]
D:\j\workspace\code_coverage---b14a30e5\Tools\tests.targets(514,5): warning :    Invariant.Tests  Total: 289, Errors: 0, Failed: 79, Skipped: 0, Time: 3.803s [D:\j\workspace\code_coverage---b14a30e5\src\System.Globalization\tests\Invariant\Invariant.Tests.csproj]
D:\j\workspace\code_coverage---b14a30e5\Tools\tests.targets(514,5): warning MSB3073: The command "D:\j\workspace\code_coverage---b14a30e5\bin/tests/Invariant.Tests/netcoreapp-Windows_NT-Debug-x64//RunTests.cmd D:\j\workspace\code_coverage---b14a30e5\bin/testhost/netcoreapp-Windows_NT-Debug-x64/" exited with code 1. [D:\j\workspace\code_coverage---b14a30e5\src\System.Globalization\tests\Invariant\Invariant.Tests.csproj]
D:\j\workspace\code_coverage---b14a30e5\Tools\tests.targets(514,5): warning MSB3073: The command "D:\j\workspace\code_coverage---b14a30e5\bin/tests/System.Net.Http.Functional.Tests/netcoreapp-Windows_NT-Debug-x64//RunTests.cmd D:\j\workspace\code_coverage---b14a30e5\bin/testhost/netcoreapp-Windows_NT-Debug-x64/" exited with code -1073741819. [D:\j\workspace\code_coverage---b14a30e5\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.Tests.csproj]
D:\j\workspace\code_coverage---b14a30e5\Tools\tests.targets(522,5): error : One or more tests failed while running tests from 'System.Globalization.CalendarsWithConfigSwitch.Tests' please check D:\j\workspace\code_coverage---b14a30e5\bin/tests/System.Globalization.CalendarsWithConfigSwitch.Tests/netcoreapp-Windows_NT-Debug-x64/testResults.xml for details! [D:\j\workspace\code_coverage---b14a30e5\src\System.Globalization.Calendars\tests\CalendarTestWithConfigSwitch\System.Globalization.CalendarsWithConfigSwitch.Tests.csproj]
D:\j\workspace\code_coverage---b14a30e5\Tools\tests.targets(522,5): error : One or more tests failed while running tests from 'Invariant.Tests' please check D:\j\workspace\code_coverage---b14a30e5\bin/tests/Invariant.Tests/netcoreapp-Windows_NT-Debug-x64/testResults.xml for details! [D:\j\workspace\code_coverage---b14a30e5\src\System.Globalization\tests\Invariant\Invariant.Tests.csproj]
D:\j\workspace\code_coverage---b14a30e5\Tools\tests.targets(522,5): error : One or more tests failed while running tests from 'System.Net.Http.Functional.Tests' please check D:\j\workspace\code_coverage---b14a30e5\bin/tests/System.Net.Http.Functional.Tests/netcoreapp-Windows_NT-Debug-x64/testResults.xml for details! [D:\j\workspace\code_coverage---b14a30e5\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.Tests.csproj]
    6 Warning(s)
    3 Error(s)

```

**Comment by ViktorHofer** [comment]
@danmosemsft @stephentoub Sources need to be present in corefx to generate correct report results. 

903 source files missing right now:
[corelib_missing_sources.txt](https://github.com/dotnet/corefx/files/2633798/corelib_missing_sources.txt)

Example file path in the pdb: `E:\A\_work\104\s\src\System.Private.CoreLib\src\Internal\Console.cs`.

I opened in the Coverlet repo to discuss support for embedded sources: https://github.com/tonerdo/coverlet/issues/255

Meanwhile I'm going to replace the paths that point to files shared between corefx and coreclr to get coverage and jump sources for most of the files.

**Comment by danmosemsft** [comment]
I suppose we could start to mirror the rest of corelib. Cc @jkotas

**Comment by jkotas** [comment]
Have you looked at integrating with sourcelink? Sourcelink gives you the full path to the exact version of the sources that the binaries were built from.

**Comment by ViktorHofer** [comment]
I've considered Sourcelink but I know too little about it to know where it needs to be plugged into. Would it need to be part of Coverlet who creates the report xml files with the full paths in it, or part of ReportGenerator who looks for these files on the disk?

**Comment by danmosemsft** [comment]
https://github.com/dotnet/sourcelink/blob/master/README.md

If it made sense, it would be a nice feature for coverlet because it would help everybody. But it would be much more work than just increasing the scope of the mirror.

**Comment by tonerdo** [comment]
I think this might be better suited in ReportGenerator. Coverlet isn't really bothered with where the source files come from, as long as their information is present in the debug data. Source link can be used and ReportGenerator will need to be updated to support grabbing source files from remote sources and not just the filesystem

**Comment by ViktorHofer** [comment]
Got it. That means System.Private.CoreLib needs to support SourceLink (if it not already does) and ReportGenerator needs to do its part.

**Comment by ViktorHofer** [comment]
@tonerdo are you sure that there is no work required in coverlet? I just took a quick look myself, source link metadata is already in the pdb I'm using with Coverlet, still it lists the local paths. Would Coverlet need to replace the paths that come from the debug data with the source link SourceUrl?

```
{"documents": { "E:\\A\\_work\\104\\s\\*" : "https://raw.githubusercontent.com/dotnet/coreclr/5feb0389f1e1ba715fba5560c979ac6362b1bcf8/*" }}
```

**Comment by tonerdo** [comment]
Hmmm..I would've assumed that SourceLink simply replaces the local path with the remote link. Seems it pairs them instead

**Comment by ViktorHofer** [comment]
Right, let's create an issue for it in the Coverlet repo and discuss what changes would be necessary (probably with a -sourcelink switch).
