### ISSUE TITLE
System.Net.CookieContainer treats cookies with path as invalid

### ISSUE THREAD

**Issue by mbashov** [dotnet/corefx#30991]
This code:
```c#
var cookieContainer = new System.Net.CookieContainer();
cookieContainer.SetCookies(new System.Uri("http://localhost"), "name=value; path=/path");
```
throws the following:
```
System.Net.CookieException: An error occurred when parsing the Cookie header for Uri 'http://localhost/'. ---> System.Net.CookieException: The 'Path'='/path' part of the cookie is invalid.
   at System.Net.Cookie.VerifySetDefaults(CookieVariant variant, Uri uri, Boolean isLocalDomain, String localDomain, Boolean setDefault, Boolean shouldThrow)
   at System.Net.CookieContainer.CookieCutter(Uri uri, String headerName, String setCookieHeader, Boolean isThrow)
   --- End of inner exception stack trace ---
   at System.Net.CookieContainer.CookieCutter(Uri uri, String headerName, String setCookieHeader, Boolean isThrow)
   at System.Net.CookieContainer.SetCookies(Uri uri, String cookieHeader)
```

These exceptions cause `HttpClient` to discard all cookies with path.

**Comment by caesar1995** [comment]
[CookieContainer.SetCookies:](https://msdn.microsoft.com/en-us/library/system.net.cookiecontainer.setcookies(v=vs.110).aspx)
```
SetCookies pulls all the HTTP cookies out of the HTTP cookie header, builds a Cookie for each one, and then adds each Cookie to the internal CookieCollection that is associated with the URI. The HTTP cookies in the cookieHeader string must be delimited by commas.
```

[Set-Cookie path attribute:](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie)

```
Path=<path-value> Optional
Indicates a URL path that must exist in the requested resource before sending the Cookie header. The %x2F ("/") character is interpreted as a directory separator and sub directories will be matched as well (e.g. path=/docs, "/docs", "/docs/Web/", or "/docs/Web/HTTP" will all be matched).
```

For this operation: `cookieContainer.SetCookies(new System.Uri("http://localhost"), "name=value; path=/path");` The requested address ("http://localhost") doesn't contain the "/path" in the URL path.

You can do:
`cookieContainer.SetCookies(new System.Uri("http://localhost/path"), "name=value; path=/path");` to set cookies available to all pages and sub-directories under "http://localhost/path".

or `cookieContainer.SetCookies(new System.Uri("http://localhost"), "name=value; path=/");` to set cookies available to all pages in the domain.

Closing as by-design.

**Comment by mbashov** [comment]
Browsers, at least Firefox and Chrome, do not discard cookies with path even if the path does not match the requested resource. And there are some interactions over HTTP relying on that, for example, Microsoft's implementation of OpenID Connect client sets [two cookies with callback path](https://github.com/aspnet/Security/blob/2.1.1/test/Microsoft.AspNetCore.Authentication.Test/OpenIdConnect/OpenIdConnectChallengeTests.cs#L384,L392) for every challenged request, and if those cookies are absent when you are redirected to the callback path, the interaction fails.

**Comment by caesar1995** [comment]
> Browsers, at least Firefox and Chrome, do not discard cookies with path even if the path does not match the requested resource. And there are some interactions over HTTP relying on that.

You are right. This is because we have not yet implemented RFC 6265 for Cookie in .NET Core (#29651, in "Path related issues").

#29651 contains instructions on how to fix those issues, if you are interested, you are welcomed to submit a PR!
