### ISSUE TITLE
Is there a way to access raw header values in HttpResponseMessage?

### ISSUE THREAD

**Issue by kfreezen** [dotnet/corefx#30990]
I'm using System.Net.Http.HttpResponseMessage and KestrelHttpServer in a transparent HTTP/S proxy application that I'm maintaining.

Unfortunately, HttpResponseMessage sanitizes the raw header values sent to it from the server. Is there any way to access those raw values?

Example: cbc.ca has an XHR which returns a `Content-Type` of `application/json;charset=utf-8` which HttpResponseMessage sanitizes to `application/json; charset=utf-8`

The XHR for the curious is: `https://www.cbc.ca/aggregate_api/v1/items?typeSet=cbc-ocelot&pageSize=23&page=1&orderLineupId=2.8873&inline=relatedLinks&categoryIds=139&source=Polopoly`

Is there any way to turn that sanitization off?

**Comment by davidsh** [comment]
>Example: cbc.ca has an XHR which returns a Content-Type of application/json;charset=utf-8 which HttpResponseMessage sanitizes to application/json; charset=utf-8

So, you want to be able to get the "raw" value which in this case has no space separator before the semicolon?

Have you tried using:

```c#
HttpResponseMessage.Content.Headers.GetValues("Content-Type")
```

**Comment by kfreezen** [comment]
I added a little logging statement into my code using `HttpResponseMessage.Content.Headers.GetValues(...)`

Output from my logfile for that Content-Type is:
```
application/json; charset=UTF-8
```

Expected output:
```
application/json;charset=UTF-8
```

Is there a way to turn off strict standards compliance for HttpResponseMessage?

Or maybe there's an alternative which doesn't auto-reformat non-standard input?

**Comment by karelz** [comment]
Looks like there is no way to do that.
Out of curiosity: Why do you need the raw values? What is your scenario?

**Comment by kfreezen** [comment]
Our scenario is an internet filtering solution which uses KestrelHttpServer to receive requests from the client and then re-creates those requests with System.Net.Http calls. In order for us to be 100% compatible with non-standard servers, we need a way to retrieve the values as they were received from the server so we can pass them to the client as-is.

https://github.com/TechnikEmpire/CitadelCore we are using a modified version of this engine.

**Comment by Clockwork-Muse** [comment]
Out of curiosity - why not take the original raw request (stream, byte array, whatever) and pipe it as output?  What you're doing will incur re-serialization costs.  That would also solve your "return the original request" problem.

**Comment by kfreezen** [comment]
Is there a way to get the underlying response in its entirety (headers+body) as a byte array or stream? If that's possible with HttpResponseMessage, I would like to give that a try.

**Comment by davidsh** [comment]
>Is there a way to get the underlying response in its entirety (headers+body) as a byte array or stream? If that's possible with HttpResponseMessage, I would like to give that a try.

The short answer is no. HttpClient/HttpResponseMessage doesn't expose the byte array or stream in a raw manner like that. If you need that kind of functionality for your scenario (which sounds like a sockets proxy/middle-tier scenario), you might want to use Sockets directly.

**Comment by kfreezen** [comment]
@davidsh Thanks. I think that answers my question for now.
