### ISSUE TITLE
Minus vs Hyphen/Dash. Different behaviour on Mac vs Windows in MVC View.

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/corefx#30993]
_From @freshe on July 8, 2018 13:59_

When doing ToString() on a C# Double in an MVC View i get different behaviour on Mac vs Windows.

On Windows i get the expected result on negative numbers where ToString() yields a "proper" minus sign that JavaScript can handle.

On Mac i instead get a dash/hyphen (long minus) that breaks the JavaScript code.

Win  -
Mac −

_Copied from original issue: aspnet/Mvc#8032_

**Comment by mkArtakMSFT** [comment]
_From @khellang on July 8, 2018 21:6_

This sounds like it belongs in dotnet/corefx?

**Comment by mkArtakMSFT** [comment]
_From @khellang on July 8, 2018 21:8_

Unless this only happens in MVC views?

**Comment by mkArtakMSFT** [comment]
_From @freshe on July 8, 2018 21:18_

No, the issue happens in the view. Not a runtime issue.

**Comment by mkArtakMSFT** [comment]
_From @khellang on July 9, 2018 6:14_

What does "not a runtime issue" mean? Are you getting errors at design- or compile-time? I think it would be helpful to provide a minimal reproducible example to better understand what you're seeing.

**Comment by mkArtakMSFT** [comment]
Hi @freshe.
As @khellang has mentioned above, we'll need a small repro project to be able to assist you.

**Comment by mkArtakMSFT** [comment]
_From @freshe on July 9, 2018 17:56_

Hi @mkArtakMSFT 
I uploaded a sample that reproduces the issue.

https://github.com/freshe/sample-hyphen-minus

**Comment by mkArtakMSFT** [comment]
_From @khellang on July 10, 2018 7:23_

You forgot to mention that the site uses Swedish culture. That's kinda important information. I bet this is an ICU issue (or by design) since it only happens on Unix.

**Comment by mkArtakMSFT** [comment]
Thanks @freshe.
@pranavkm, can you please look into this and redirect to corefx folks, if necessary?

**Comment by mkArtakMSFT** [comment]
_From @khellang on July 10, 2018 22:54_

Using the solution provided, I'm getting **HYPHEN-MINUS (U+002d)** on Windows (10.0.16299) and **MINUS SIGN (U+2212)** on MacOS (Darwin 17.5.0), which sounds like the exact opposite of what @freshe reported.

Anyway, I was able to reproduce the same results using the following code:

```csharp
public static class Program
{
    public static void Main(string[] args)
    {
        CultureInfo.CurrentCulture = CultureInfo.CurrentUICulture = new CultureInfo("sv-SE");

        var value = -0.144551456;
        var stringValue = value.ToString();
        
        Console.WriteLine(RuntimeInformation.FrameworkDescription);
        Console.WriteLine(RuntimeInformation.OSDescription);

        Console.WriteLine();

        Console.WriteLine(stringValue);
        Console.WriteLine(string.Join(" ", stringValue.Select(x => $"U+{(int)x:x4}")));
    }
}
```

## Windows Result

```
.NET Core 4.6.26515.07
Microsoft Windows 10.0.16299

-0,144551456
U+002d U+0030 U+002c U+0031 U+0034 U+0034 U+0035 U+0035 U+0031 U+0034 U+0035 U+0036
```

## MacOS Result

```
.NET Core 4.6.26606.02
Darwin 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64

−0,144551456
U+2212 U+0030 U+002c U+0031 U+0034 U+0034 U+0035 U+0035 U+0031 U+0034 U+0035 U+0036
```

Note the difference in the first character (the `CultureInfo.NumberFormat.NegativeSign`).

I'm pretty confident this is a corefx/coreclr issue. Probably a mismatch between Windows' culture and ICU.

**Comment by mkArtakMSFT** [comment]
_From @pranavkm on July 11, 2018 1:9_

Thanks for the detailed investigation @khellang  👍

**Comment by tarekgh** [comment]
The framework gets the globalization data from the underlying OS. on Linux and MAC we get this from ICU library. so this is by design for the framework. if you think this is wrong, you can report the issue to the ICU library to fix it. note that, in general, you cannot assume you are going to get minus sign for all locales. if you want to guarantee to get minus sign, you should use the Invariant culture when formatting the number.
