### ISSUE TITLE
System.Diagnostics.Debug not hooked up to TraceListeners and missing .Listeners property

### ISSUE THREAD

**Issue by TicoDePano** [dotnet/corefx#31003]
```
#if DEBUG
	Console.WriteLine("DEBUG");
#endif
#if TRACE
	Console.WriteLine("TRACE");
#endif
	Debug.WriteLine("CONDITIONAL");
```
Using Core 2.1, this code correctly writes **TRACE** when _dotnet run -c Release_ command runs on an ordinary project, but _dotnet run_ only writes **DEBUG** and **TRACE**, no **CONDITIONAL**.

**Comment by gfoidl** [comment]
Well it writes it...but by default into the "Debug Window" (Output with Debug selected).

![grafik](https://user-images.githubusercontent.com/5755834/42631125-838a4144-85d9-11e8-858e-50c95893a536.png)

This is OK according the [docs](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/trace-listeners).

**Comment by TicoDePano** [comment]
Yes, it's working, my bad.
It was needed to add my TraceListener, as the docs say.

**Comment by danmosemsft** [comment]
Fixing title.

**Comment by danmosemsft** [comment]
Debug.Assert behavior (not really related but on the same class) is tracked here https://github.com/dotnet/corefx/issues/3708

**Comment by danmosemsft** [comment]
I've no doubt this was snipped because of a layering problem. In NETFX, Debug does its writing through TraceInternal, which handles writing to eg OutputDebugString through DefaultTraceListener (which is either instantiated by SystemDiagnosticsSection in machine.config or by fallback to it)
