### ISSUE TITLE
DllImports in PlatformDetection.NonNetFx.cs will not work in UWP ILC testing

### ISSUE THREAD

**Issue by fadimounir** [dotnet/corefx#31006]
In file src\CoreFx.Private.TestUtilities\src\System\PlatformDetection.NonNetFx.cs, these imports will not work when the test is compiled as a UWP ILC test:

        [DllImport("libc", ExactSpelling = true, CharSet = CharSet.Ansi, CallingConvention = CallingConvention.Cdecl)]
        private static extern IntPtr gnu_get_libc_release();

        [DllImport("libc", ExactSpelling = true, CharSet = CharSet.Ansi, CallingConvention = CallingConvention.Cdecl)]
        private static extern IntPtr gnu_get_libc_version();

Compiling with ILC creates static links to the dll imports. When attempting to run the test on windows, this will cause xunit.console.netcore.exe to fail to load due to the missing libc.dll.

With ILC, there won't be any exception thrown. This code will need to be in some kind of #ifdef block to not compile for windows.

**Comment by MichalStrehovsky** [comment]
Related to #30423 and #30399? Cc @luqunl

**Comment by luqunl** [comment]
@fadimounir , do you have a repro for this?

**Comment by fadimounir** [comment]
I was using this as a repro: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20180712.04/workItem/System.Collections.Tests
