### ISSUE TITLE
Dictionary version increment is missing for TrimExcess() and EnsureCapacity()

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#31007]
`Dictionary<K,V>` has a `version` field that is incremented by modification and tested by enumerators such that any modification of a dictionary during enumeration causes an exception. This is to flag that the enumeration may not lead to self consistent results.

Calls to TrimExcess() and EnsureCapacity() appear to not increment version even though they could modify the backing storage in such a way that they could break enumeration.

They should both have `version++`. 

https://github.com/dotnet/coreclr/pull/18854

**Comment by satano** [comment]
Hello. Can I take this one?

**Comment by Wraith2** [comment]
I think this can be closed, it was fixed in https://github.com/dotnet/corefx/pull/31062
