### ISSUE TITLE
Http Negotiate authentication fails on Unix

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#31005]
@ManuelAVR reported an issue where .NET Core fails to authenticate against his proxy server.

The proxy server is sending:
```
< Proxy-Authenticate: Negotiate
< Proxy-Authenticate: NTLM
```
.NET Core doesn't reply to the proxy server to authenticate. It returns the 407 as the response result.

Trying to authenticate with curl using `--proxy-negotiate` fails with: `gss_init_sec_context() failed: SPNEGO cannot find mechanisms to negotiate.`
Using `--proxy-ntlm` works.

There is no Kerberos ticket. Proxy server and credentials are provided using http_proxy and https_proxy envvars.

Perhaps .NET Core gets the same error from gss_init_sec_context and then stops. Maybe at that point it should try NTLM auth instead?

It doesn't work either when using the curl httphandler. Probably curl also has this issue: https://github.com/curl/curl/issues/876.

CC @wfurt

**Comment by wfurt** [comment]
I think key may be creating credential cache with type set to NTLM. 
Is this 2.1 issue using SocketHttphandler @tmds ?

**Comment by tmds** [comment]
> I think key may be creating credential cache with type set to NTLM.

If you get a compiled app, it should be able to authenticate with the proxy server using credentials from the envvars.

> Is this 2.1 issue using SocketHttphandler @tmds ?

Yes. It also occurs with the curl handler (probably due to https://github.com/curl/curl/issues/876).

**Comment by davidsh** [comment]
Maybe this is related to #30330 which was fixed in a servicing updated of .NET Core 2.1.

**Comment by davidsh** [comment]
>There is no Kerberos ticket.

Also, how is the credential being set into the HttpClientHandler?  "Default credentials" only work if there is a Kerberos ticket active.

**Comment by davidsh** [comment]
>It doesn't work either when using the curl httphandler.

CurlHandler does NOT handle Negotiate/NTLM to a proxy.  That is a known issue.  Only Basic auth works with CurlHandler for proxy auth.

**Comment by wfurt** [comment]
yes, but any issues with parsing that variable would be silently ignored.
Creating the credential cache would force to skip Negotiate. 

What info would we need @davidsh to confirm if it is  #30330 (and possibly #30327)
The 30330 would try and fail. In this case there is no attempt to authenticate according to @tmds.

**Comment by davidsh** [comment]
>What info would we need @davidsh to confirm if it is #30330 (and possibly #30327)
The 30330 would try and fail. In this case there is no attempt to authenticate according to @tmds.

Issue #30330 is about SocketsHttpHandler doing Windows auth to a proxy to a destination URI that is HTTPS.  Is that this scenario?   

>In this case there is no attempt to authenticate according to @tmds.

That is bug #30330.  SocketsHttpHandler does not attempt to authenticate at all to the proxy.  It does not start the Negotiate/NTLM handshake at all.

**Comment by tmds** [comment]
> Maybe this is related to #30330 which was fixed in a servicing updated of .NET Core 2.1.

I'm not sure. Maybe it is sufficient to get this to work...
It doesn't relate to behavior of if SocketsHandler would see `gss_init_sec_context() failed: SPNEGO cannot find mechanisms to negotiate.`.

> Also, how is the credential being set into the HttpClientHandler? "Default credentials" only work if there is a Kerberos ticket active.

There is no Kerberos ticket. credentials are passed in the http_proxy and https_proxy envvars.
I guess no Kerberos _may_ be the reason gss_init_sec_context returns `SPNEGO cannot find mechanisms to negotiate`.

**Comment by tmds** [comment]
> Issue #30330 is about SocketsHttpHandler doing Windows auth to a proxy to a destination URI that is HTTPS. Is that this scenario?

Also for http uri, using http proxy .NET Core doesn't try to authenticate and returns 407.

**Comment by tmds** [comment]
> I assume you added the gss-ntlmssp package, right?

gss-ntlmssp is not installed. krb5-libs is installed.

> If you're seeing this error, then it means that the machine is not configured properly.

This is running in a container. The http_proxy and https_proxy envvars are used to configure it (as good as possible).

> Do you use the domain\foo:bar@1.1.1.1 form? Are there any special characterless in name or password?

@ManuelAVR, can you answer these questions?

**Comment by tmds** [comment]
> gss-ntlmssp is not installed.

It seems gss-ntlmssp isn't available on RHEL.

**Comment by wfurt** [comment]
Could you use http://rpm.pbone.net/index.php3/stat/4/idpl/40954132/dir/redhat_el_7/com/gssntlmssp-0.7.0-1.el7.x86_64.rpm.html (or package from Centos)
Without it, I was never able to do NTLM as MIT GSSAPI does not support it on it's own.

**Comment by tmds** [comment]
> Without it, I was never able to do NTLM as MIT GSSAPI does not support it on it's own.

I think it may be feasible without the package. In the logs I saw npm installs packages through the proxy (with the same envvars set). Unless @ManuelAVR did something special that I missed?

It would be nice if we could avoid the extra dependency. Especially since for RHEL we'd need to build it from source and maintain it just for .NET Core.

**Comment by wfurt** [comment]
That is different @tmds. Curl can do it as well as it has it't own implementation for ntlm.
However SocketHttpHandler and underlying NegotiateStream only uses GSSAPI and depends on GSSAPI providers. On Windows, you get both by default (NTLM and Kerberos)

**Comment by tmds** [comment]
Ah, ok. gss-ntlmssp is a dependency of .NET Core on Linux to support Negotiate/NTLM auth.

It would be good to document this.

**Comment by wfurt** [comment]
Look at  https://github.com/dotnet/corefx/issues/28961. I was trying to get it to docker images at least but it did not happened.

**Comment by tmds** [comment]
I created https://bugzilla.redhat.com/show_bug.cgi?id=1600392 for RHEL.

I'm closing this as a dup of https://github.com/dotnet/corefx/issues/28961.

**Comment by wfurt** [comment]
did it actually worked after installing dependencies @tmds?

**Comment by tmds** [comment]
I'm not looking into it further atm.
We have this issue when `dotnet restore` fails to authenticate against the proxy server for accessing nuget.org. A fast workaround will be to setup a caching nuget server. Providing a gss-ntlmssp package will take more time. It depends on prioritization when we investigate this issue further.

**Comment by tmds** [comment]
@wfurt @davidsh thank you for your help!

**Comment by ManuelAVR** [comment]
Hello and sorry for my late response.
We managed with the work arround, we have another proxy server with white lists and this is now working well (without auth).
