### ISSUE TITLE
Proposal: Trim/TrimStart/TrimEnd methods for Memory and Span with trim element

### ISSUE THREAD

**Issue by schungx** [dotnet/corefx#31011]
Currently, the overloaded versions of `Trim`, `TrimStart` and `TrimEnd` that accept a `trimChar` or `trimChars` only works with `ReadOnlySpan<char>`.  There is no reason why these versions cannot be extended to any `ReadOnlySpan<T>`.  For example:

```c#
public static ReadOnlySpan<T> TrimEnd<T>(this ReadOnlySpan<T> span, T trimElement)
{
    int end = span.Length - 1;
    for (; end >= 0; end--)
    {
        if (span[end] != trimElement)
            break;
    }
    return span.Slice(0, end + 1);
}
```

This will allow, for example, quick processing of a byte array to trim off zero paddings before parsing.

**Comment by gfoidl** [comment]
@schungx can you update your code sample so that the `return` is outside the loop?

**Comment by stephentoub** [comment]
> if (span[end] != trimElement)

You can't use `!=` with arbitrary `T`s like this.  You would instead, for example, need to constraint `T` with `where T : IEquatable<T>` and then use a comparison like `if (span[end] != null && !span[end].Equals(trimElement))`.

**Comment by ahsonkhan** [comment]
To confirm, these are the APIs being proposed, correct?

```C#
public static ReadOnlySpan<T> Trim<T>(this ReadOnlySpan<T> span) where T : IEquatable<T> { throw null; }
public static ReadOnlySpan<T> Trim<T>(this ReadOnlySpan<T> span, T trimElement) where T : IEquatable<T> { throw null; }
public static ReadOnlySpan<T> Trim<T>(this ReadOnlySpan<T> span, System.ReadOnlySpan<T> trimElements) where T : IEquatable<T> { throw null; }
public static ReadOnlySpan<T> TrimEnd<T>(this ReadOnlySpan<T> span) where T : IEquatable<T> { throw null; }
public static ReadOnlySpan<T> TrimEnd<T>(this ReadOnlySpan<T> span, T trimElement) where T : IEquatable<T> { throw null; }
public static ReadOnlySpan<T> TrimEnd<T>(this ReadOnlySpan<T> span, System.ReadOnlySpan<T> trimElements) where T : IEquatable<T> { throw null; }
public static ReadOnlySpan<T> TrimStart<T>(this ReadOnlySpan<T> span) where T : IEquatable<T> { throw null; }
public static ReadOnlySpan<T> TrimStart<T>(this ReadOnlySpan<T> span, T trimElement) where T : IEquatable<T> { throw null; }
public static ReadOnlySpan<T> TrimStart<T>(this ReadOnlySpan<T> span, System.ReadOnlySpan<T> trimElements) where T : IEquatable<T> { throw null; }
```

**Comment by terrajobst** [comment]
We can probably cut the APIs that don't specify a element (because `default(T)` doesn't seem reasonable) but it's still 6 APIs. We feel like we need a bit more justification to add these APIs.

@schungx what are the scenarios where you needed this API?

**Comment by karelz** [comment]
Also, the original ask (from title) is also for `Memory` and `Span`. Do we need those? If not, let's change the title.

**Comment by ahsonkhan** [comment]
> Also, the original ask (from title) is also for `Memory` and `Span`. Do we need those? If not, let's change the title.

We already have the T=char Trim APIs approved for ReadOnlyMemory. I would assume the same rationale would apply here for the generic ReadOnlyMemory. So, if we add the span-based ones, we should add the memory-based ones too.

https://github.com/dotnet/corefx/issues/30592

**Comment by schungx** [comment]
> @schungx what are the scenarios where you needed this API?

Well, I came about this when needing to process zero-padded byte data obtained via a Socket.  So naturally something like `TrimEnd` for `Span<byte>` where I can specify the `trimElement` to be zero is immensely useful.

I can see this being useful in cases where you need to handle fixed-sized records with some default padding value.

Therefore, if 6 API's are too many, I would recommend just adding the two `TrimEnd` variations:

~~~
public static ReadOnlySpan<T> TrimEnd<T>(this ReadOnlySpan<T> span, T trimElement) where T : IEquatable<T> { throw null; }
public static ReadOnlySpan<T> TrimEnd<T>(this ReadOnlySpan<T> span, System.ReadOnlySpan<T> trimElements) where T : IEquatable<T> { throw null; }
~~~

This is because `TrimStart` and `Trim` are really not very meaningful except for strings.

**Comment by ahsonkhan** [comment]
If we are going to add TrimEnd, we should add TrimStart too.

```C#
public static ReadOnlySpan<T> TrimEnd<T>(this ReadOnlySpan<T> span, T trimElement) where T : IEquatable<T> { throw null; }
public static ReadOnlySpan<T> TrimEnd<T>(this ReadOnlySpan<T> span, System.ReadOnlySpan<T> trimElements) where T : IEquatable<T> { throw null; }
public static ReadOnlySpan<T> TrimStart<T>(this ReadOnlySpan<T> span, T trimElement) where T : IEquatable<T> { throw null; }
public static ReadOnlySpan<T> TrimStart<T>(this ReadOnlySpan<T> span, System.ReadOnlySpan<T> trimElements) where T : IEquatable<T> { throw null; }
```

**Comment by terrajobst** [comment]
* We should replace the already approved methods for `ReadOnlyMemory<char>` to be over `T` (except for the one that doesn't take values and assumes whistespace, which should remain to be over `char`).


```C#
// Existing, effectively dead methods:

Trim(ReadOnlySpan<Char>, Char)
Trim(ReadOnlySpan<Char>, ReadOnlySpan<Char>)
TrimEnd(ReadOnlySpan<Char>, Char)
TrimEnd(ReadOnlySpan<Char>, ReadOnlySpan<Char>)
TrimStart(ReadOnlySpan<Char>, Char)
TrimStart(ReadOnlySpan<Char>, ReadOnlySpan<Char>)

// Effective method set

//Trim(ReadOnlySpan<Char>)
Trim(ReadOnlySpan<T>, T)
Trim(ReadOnlySpan<T>, ReadOnlySpan<T>)
//TrimEnd(ReadOnlySpan<Char>)
TrimEnd(ReadOnlySpan<T>, T)
TrimEnd(ReadOnlySpan<T>, ReadOnlySpan<T>)
//TrimStart(ReadOnlySpan<Char>)
TrimStart(ReadOnlySpan<T>, T)
TrimStart(ReadOnlySpan<T>, ReadOnlySpan<T>) 
Trim(Span<Char>)
Trim(Span<T>, T)
Trim(Span<T>, ReadOnlySpan<T>)
TrimEnd(Span<Char>)
TrimEnd(Span<T>, T)
TrimEnd(Span<T>, ReadOnlySpan<T>)
TrimStart(Span<Char>)
TrimStart(Span<T>, T)
TrimStart(Span<T>, ReadOnlySpan<T>) 
Trim(ReadOnlyMemory<Char>)
Trim(ReadOnlyMemory<T>, T)
Trim(ReadOnlyMemory<T>, ReadOnlySpan<T>)
TrimEnd(ReadOnlyMemory<Char>)
TrimEnd(ReadOnlyMemory<T>, T)
TrimEnd(ReadOnlyMemory<T>, ReadOnlySpan<T>)
TrimStart(ReadOnlyMemory<Char>)
TrimStart(ReadOnlyMemory<T>, T)
TrimStart(ReadOnlyMemory<T>, ReadOnlySpan<T>) 
Trim(Memory<Char>)
Trim(Memory<T>, T)
Trim(Memory<T>, ReadOnlySpan<T>)
TrimEnd(Memory<Char>)
TrimEnd(Memory<T>, T)
TrimEnd(Memory<T>, ReadOnlySpan<T>)
TrimStart(Memory<Char>)
TrimStart(Memory<T>, T)
TrimStart(Memory<T>, ReadOnlySpan<T>) 
```

**Comment by ahsonkhan** [comment]
> We should replace the already approved methods for `ReadOnlyMemory<char>` to be over `T` (except for the one that doesn't take values and assumes whistespace, which should remain to be over `char`).

i.e. https://github.com/dotnet/corefx/issues/30592, for reference.

**Comment by grant-d** [comment]
> or something like that.

I submitted the above PR, using the suggested comparison but moving it outside the loop to make it cheaper:
```csharp
int end = span.Length - 1;

if (trimElement == null)
{
    for (; end >= 0; end--)
    {
        if (span[end] != null) break;
    }
}
else
{
    for (; end >= 0; end--)
    {
        if (span[end] != null && !span[end].Equals(trimElement)) break;
    }
}

return span.Slice(0, end + 1);
```

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/dotnet/coreclr/pull/22798 / https://github.com/dotnet/corefx/pull/35576
