### ISSUE TITLE
UWP HttpClient: "No more Internet handles can be allocated"

### ISSUE THREAD

**Issue by andriysavin** [dotnet/corefx#31014]
My UWP app does some amount of HTTP requests using `HttpClient` and fails with a `COMException` "No more Internet handles can be allocated". Below is the stack trace:

```
   at Windows.Web.Http.Filters.HttpBaseProtocolFilter.SendRequestAsync(HttpRequestMessage request)
   at System.Net.Http.HttpHandlerToFilter.<SendAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClientHandler.<SendAsync>d__111.MoveNext()
```

I'm using shared `HttpClient` instance, and requests are done primarily sequentially. I also dispose request and response objects, so there should be no resource leak. However, looking at the UWP [implementation](https://github.com/dotnet/corefx/blob/12e41edba6c9b177f21e30001ce3c890c5225132/src/System.Net.Http/src/uap/System/Net/HttpHandlerToFilter.cs) I can't find any place where UWP's native request and response objects are disposed after converting to/from .NET's ones, so I'm guessing this can be the source of the problem.

**Comment by davidsh** [comment]
Can you please provide a repro sample of this?

**Comment by andriysavin** [comment]
@davidsh I tried to minimize the code to reproduce this, and looks like the source of the problem was not as obvious as it seemed. To explain, my application uses MapControl with an external tile source based on the `HttpMapTileDataSource` class. Actually, I have several copies of the same tile source, and they are swapped when the map is scrolled. In short, this is done to refresh a particular area of the map layer without flickering tiles which are currently displayed. So, scrolling and swapping produces heavy tiles querying inside the map, which results in many HTTP requests. I suspect these requests are parallelized too much, so they consume too much resources (WinInet handles?) at the same time. So, if I'm doing some HTTP requests using `HttpClient` at that time, its likely that resources are exhausted and I'm getting that exception.

Thus, this is probably not a bug in the HttpClient itself, but in the `MapControl`. Anyway, I'm still providing a sample app to reproduce this: [.](https://1drv.ms/u/s!AuaAKPMkiTEAxqt6BqNvnuKePi1KvA) Just execute it and wait for a while (less than 30 seconds on my machine). Note that while the code looks silly and you may think "why the heck is he doing that??", it's just to simulate what the real app does in more complicated code.

**Comment by karelz** [comment]
Closing as it does not seem to be a problem in CoreFX.
