### ISSUE TITLE
Implement cryptographic algorithms (RC2, RC4, DES, SHA) natively on macOS

### ISSUE THREAD

**Issue by filipnavara** [dotnet/corefx#31012]
Mono compiled for Xamarin profiles supports native cryptography libraries on macOS/iOS using the `CCCryptorCreate` interface (https://github.com/mono/mono/tree/master/mcs/class/corlib/CommonCrypto). As far as I can tell CoreFX still uses OpenSSL for that on macOS. Since X509 code was switched over to use CommonCrypto on macOS it would probably make sense to use the native cryptography primitives too.

**Comment by stephentoub** [comment]
Why do you think OpenSSL is still be used?  Here's a build of System.Security.Cryptography.Algorithms.dll for macOS... you can see the Interop namespace it only has AppleCrypto and CoreFoundation:
![image](https://user-images.githubusercontent.com/2642209/42641234-17353b6e-85c2-11e8-9fd9-ac3d4c553391.png)
In contrast, here's the one for Linux:
![image](https://user-images.githubusercontent.com/2642209/42641272-37150c2a-85c2-11e8-98bc-9d728c035ac5.png)
And if, for example, you navigate through the code from, say, SHA256.Create, you'll find it ends up in AppleDigestProvider, which P/Invokes into `System.Security.Cryptography.Native.Apple`, e.g. `AppleCryptoNative_DigestCreate`, which uses CommonCrypto:
https://github.com/dotnet/corefx/blob/9908dee27b7a73046c8dae4a1db1b3603e795c8a/src/Native/Unix/System.Security.Cryptography.Native.Apple/pal_digest.c#L34

**Comment by filipnavara** [comment]
You are completely right! My bad. I used GitHub search for `CCCryptorCreate`, which didn't show any results so I missed that `CCCryptorCreateWithMode` is used instead.
