### ISSUE TITLE
System.Numerics.Vectors NuGet package does not work with F#

### ISSUE THREAD

**Issue by FrankNiemeyer** [dotnet/corefx#3103]
The [System.Numerics.Vectors](https://www.nuget.org/packages/System.Numerics.Vectors/) package (v4.1.0) doesn't seem to work correctly with F#: Whenever I try to use it, it installs correctly, but the compiler always refers to the corresponding .NET 4.6 reference assembly ("C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Numerics.Vectors.dll", in my case) instead of the downloaded assembly in the packages directory.

When installing the NuGet package into a C# project, it found that a `<HintPath>` item was added to the csproj file, redirecting the reference to the proper assembly (e.g. `<HintPath>..\packages\System.Numerics.Vectors.4.1.0\lib\net46\System.Numerics.Vectors.dll</HintPath>`). For F# projects however this `<HintPath>` is *not* added to the fsproj file. Adding it manually fixes the problem.

**Comment by weshaggard** [comment]
cc @mellinoe @KevinRansom

**Comment by yishaigalatzer** [comment]
What version of NuGet and visual studio are you using?

**Comment by mellinoe** [comment]
I tried this just now with version 3.2.60914.10516 (latest on the VS gallery), and it still repros.

**Comment by yishaigalatzer** [comment]
Added a comment on the nuget bug, this looks like a difference in behavior between the F# system and the C# project system. I'm currently assuming that the fix will come from F# or that we get guidance and roll it into NuGet 3.3. For now closing the Nuget bug, if we change our mind we can re-open it.

CC @Pilchie

**Comment by mellinoe** [comment]
As this is an F# project system bug, I'm closing this for now.

**Comment by dsyme** [comment]
@mellinoe @yishaigalatzer  A couple of things

* No issue was raised in the F# repository when you closed this. Please always make sure that you raise an appropriate issue when closing a bug as external (and add a link).

* The bug surfaces when exercising Nuget functionality, please do an initial investigation to determine a likely cause of the problem. See [this comment on the newly opened Nuget ticket](https://github.com/NuGet/Home/issues/2072#issuecomment-181122359).
