### ISSUE TITLE
Interop: Assigning handler to COM event raises PlatformNotSupportedException

### ISSUE THREAD

**Issue by tunix79** [dotnet/corefx#31049]
I'm maintaining a COM in-proccess server that acts as a bridge between a native application and an ASP.NET core 2.1 web service. So far, I've been able to maneuver around the somewhat limited IDispatch support (as every interface is implemented as dual anyway). Well, with the exception of subcribing to COM based events. Everything compiles as expected, even the events show up in IntelliSense as they would in a classic .NET enviroment, giving you the deceptive feeling that this might actually work. However, at run-time every subscription attempt to a COM event leads to a PlatformNotSupportedException.

I understand that restricting support for IDispatch based patterns (like COM collections) is an architectural decision, yet omitting support for IConnectionPoint based events feels quite limiting. Is there a workaround to subscribe to COM based events anyway? A custom marshaler perhaps? If not, is there a commonly agreed on practise how to implement callbacks in COM related interop scenarios?

**Comment by joshfree** [comment]
@jeffschwMSFT

**Comment by jeffschwMSFT** [comment]
@AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
Fixed with https://github.com/dotnet/coreclr/pull/22721
