### ISSUE TITLE
Windows_NT performance runs are broken

### ISSUE THREAD

**Issue by jorive** [dotnet/corefx#31053]
The tests started failing right after this commit: 5f3d22a7f335ae4c1dd57f9ac8b7460a13d57ee0

One of the commits in the link below might have caused the break.
https://github.com/dotnet/corefx/compare/5f3d22a7f335ae4c1dd57f9ac8b7460a13d57ee0...dotnet:0b0f63d47951773cc46393312d80b40176d3a413

**Comment by danmosemsft** [comment]
@eerhardt this may be the SDK project update

@jorive can you please point to logs or other info?

**Comment by jorive** [comment]
The first failure happened on this run: https://ci2.dot.net/job/dotnet_corefx/job/perf/job/master/job/perf_windows_nt_release/6117/

This is the run log:
https://ci2.dot.net/job/dotnet_corefx/job/perf/job/master/job/perf_windows_nt_release/6117/consoleText

**Comment by jorive** [comment]
The test is harnessed here: https://github.com/dotnet/corefx/blob/952b260f230afb771e8aa65586ea213418641082/perf.groovy#L99
This is the command you need to run locally:
```cmd
.\build-managed.cmd -release -tests -- /p:Performance=true /p:TargetOS=Windows_NT /m:1 /p:BenchviewRunType=Local /p:PerformanceType=Profile
```

**Comment by eerhardt** [comment]
Working on a fix.  I can repro this locally.
