### ISSUE TITLE
Task.Delay(-1) should not create a leak

### ISSUE THREAD

**Issue by NicolasDorier** [dotnet/corefx#31056]
# Issue

I implemented this so I could make any Task cancellable:

```c#
public static async Task<T> WithCancellation<T>(this Task<T> task, CancellationToken cancellationToken)
{
            var waiting = Task.Delay(-1, delayCTS.Token);
            var doing = task;
            await Task.WhenAny(waiting, doing);
            cancellationToken.ThrowIfCancellationRequested();
            return await doing;
}
```

But to my surprise, it created a leak! As `Task.Delay` get added to a list.

![image](https://user-images.githubusercontent.com/3020646/42706696-a9d827aa-8712-11e8-8f92-3f61958a57e0.png)

# Workaround
```c#
public static async Task<T> WithCancellation<T>(this Task<T> task, CancellationToken cancellationToken)
{
        using (var delayCTS = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken))
        {
            var waiting = Task.Delay(-1, delayCTS.Token);
            var doing = task;
            await Task.WhenAny(waiting, doing);
            delayCTS.Cancel();
            cancellationToken.ThrowIfCancellationRequested();
            return await doing;
        }
}
```

There is no reason `Task.Delay(-1)`  get monitored.

# Expected result

This code should not leak
```c#
public static async Task<T> WithCancellation<T>(this Task<T> task, CancellationToken cancellationToken)
{
            var waiting = Task.Delay(-1, delayCTS.Token);
            var doing = task;
            await Task.WhenAny(waiting, doing);
            cancellationToken.ThrowIfCancellationRequested();
            return await doing;
}
```

**Comment by IdahoSixString** [comment]
@NicolasDorier 

Does this problem occur when using 

Task.Delay(Timeout.Infinite);?

**Comment by stephentoub** [comment]
I don't see a bug here. `Task.Delay` doesn't know or in any way adhere to the scope in which it's called (how could it?), and you created it in a way that registers it with a particular `cancellationToken`, such that if that cancellation token is ever canceled, the resulting task will complete.

**Comment by tarekgh** [comment]
@NicolasDorier I am closing this as this is expected behavior as @stephentoub mentioned. feel free to reply with any more questions if you have any.

**Comment by NicolasDorier** [comment]
Indeed it makes sense now.  Thanks.
