### ISSUE TITLE
Regular expressions: anchor to start (^) does not work when calling Regex.Match with startat > 0

### ISSUE THREAD

**Issue by ramon-garcia** [dotnet/corefx#31051]
The problem is when one tries to look for a pattern inside a string, with a start position. And one uses the caret to avoid looking for matches except at this position. Since this is a long string, one wants to avoid either taking a substring (which is O(N) ) or looking for matches except at the start.

For instance

        static void Main(string[] args)
        {
            Regex r = new Regex("^foo");
            string s = "afoo";
            var result = r.Match(s, 1);
            Console.WriteLine($"result {result.Success}");
        }

This match should succeed, but it does not.

Otherwise, is there any efficient method for looking for matches in a string from particular position that is not O(N) ?

**Comment by jnm2** [comment]
When I was in this situation, I found `\G` useful: https://docs.microsoft.com/dotnet/standard/base-types/anchors-in-regular-expressions#Contiguous

It only works if the position you wish to start from is always the end of the previous match.

**Comment by ramon-garcia** [comment]
@jnm2 Thank you, the trick worked. But it is counterintuitive.

**Comment by danmosemsft** [comment]
Interesting behavioral question to consider when considering Span overloads. My assumption is that they would work like a substring is passed in
https://github.com/dotnet/corefx/issues/24145
