### ISSUE TITLE
System.Security: X509Store.Remove/Range behavior difference on macOS

### ISSUE THREAD

**Issue by filipnavara** [dotnet/corefx#31050]
X509Store.Remove[Range] on read-only store should not throw exceptions for the certificates that are  not present in the store. The Windows and Unix implementations seem to interpret it correctly. The macOS implementation always throws an exception without doing the lookup.

The relevant unit test (RemoveReadOnlyThrowsWhenFound) is useless and thus it didn't show the problem. A new unit test should be added to actually reproduce the behavior. It can be included in X509StoreMutableTests_OSX, which is run in outer loop.

**Comment by bartonjs** [comment]
I don't think the test needs to be outer-loop, since it shouldn't (by definition) be mutating machine state.  (If RemoveReadOnlyThrowsWhenFound "successfully" removed the arbitrary first certificate it can't necessarily put it back (the private key may have been deleted), there'd need to be something horrendously wrong with RemoveReadOnlyIsSilentWhenNotFound for it to have a discernable effect)

**Comment by jmezach** [comment]
I'm having a look at this and I see there are actually two implementations for this on OSX, the [AppleTrustStore](https://github.com/dotnet/corefx/blob/93ebee2ae64fbe4816ff4bf3bb19eb9ca174baf4/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.OSX/StorePal.AppleTrustStore.cs#L69) and the [AppleKeychainStore](https://github.com/dotnet/corefx/blob/93ebee2ae64fbe4816ff4bf3bb19eb9ca174baf4/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.OSX/StorePal.AppleKeychainStore.cs#L71). The AppleTrustStore implementation simply always throws an exception when calling Remove, while the AppleKeychainStore seems to throw an exception if it's readonly regardless if the certificate actually exists. Looking at the [Windows implementation](https://github.com/dotnet/corefx/blob/93ebee2ae64fbe4816ff4bf3bb19eb9ca174baf4/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Windows/StorePal.cs#L54) it seems to check if the certificate is in the store and if not it simply returns.

I'll try to add a check to the Remove method on AppleKeychainStore to first verify if the certificate exists, but I'm not sure what to do about the AppleTrustStore. Any ideas?
