### ISSUE TITLE
Remove System.Runtime.Intrinsics.Experimental and add intrinsics APIs back into Microsoft.NETCore.App

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#31064]
Now that the master branch is on the `3.0` train, and we plan on shipping the System.Runtime.Intrinsics APIs as stable in `3.0`, it is time to drop the experimental nuget package, and add the APIs back into Microsoft.NETCore.App.  We should do this soon, so others can consume these APIs easily.

/cc @tannergooding @CarolEidt @danmosemsft

**Comment by danmosemsft** [comment]
@tannergooding is this something you can do for us?

**Comment by tannergooding** [comment]
Yes. Should be fairly trivial.
