### ISSUE TITLE
Intersect not optimized for HashSet

### ISSUE THREAD

**Issue by plemanach** [dotnet/corefx#3106]
Hello,

I found some old blog about an optimization of Intersect when the underlying collection is a HashSet.

I have been caught of this issue in a contest and using the custom implementation made a huge performance difference.

Here the blog by Patrick Smacchia  with a full description of the issue :

http://www.codebetter.com/patricksmacchia/2011/06/16/linq-intersect-2-7x-faster-with-hashset/

Patrice

**Comment by JonHanna** [comment]
What's the performance impact on time to first result?

**Comment by plemanach** [comment]
The performance impact on the first result is still much quicker using the custom implementation (using HashSet.Intersect) but it mostly depend of the balance of the sets, if the first set is small compare to the second set, the custom implementation can be more than 10x quicker on first result than the framework. The issue is more the discrepancy of results as the balance of sets change. 

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace ConsoleIntersect
{
    public static class LinqExtension
    {
        internal static IEnumerable<T> MyIntersect<T>(this IEnumerable<T> first, IEnumerable<T> second)
        {
            var firstHashset = first as HashSet<T>;
            var secondHashset = second as HashSet<T>;
            if (firstHashset != null && secondHashset != null)
            {
                return (firstHashset.Count > secondHashset.Count)
                    ? firstHashset.Intersect(second)
                        : secondHashset.Intersect(first);
            }
            if (firstHashset != null) { return firstHashset.Intersect(second); }
            if (secondHashset != null) { return secondHashset.Intersect(first); }
            return first.Intersect(second);
        }
    }

    class Program
    {
        static void Main(string[] args)
        {

            var hashSetA = new HashSet<string>();

            for (int i = 0; i < 1000; i++)
            {
                hashSetA.Add("item" + i);
            }

            var hashSetB = new HashSet<string>();


            for (int i = 10; i > 0; i--)
            {
                hashSetB.Add("item" + i);
            }

            var stopwatch = new Stopwatch();


            for (int i = 0; i < 10; i++)
            {
                stopwatch.Start();
                var result = hashSetB.Intersect(hashSetA).FirstOrDefault();

                stopwatch.Stop();

                Console.WriteLine("Time intersect First element classic {0}", stopwatch.ElapsedTicks);

                stopwatch.Reset();
            }

            for (int i = 0; i < 10; i++)
            {
                stopwatch.Start();

                var result = hashSetB.MyIntersect(hashSetA).FirstOrDefault();
                stopwatch.Stop();

                Console.WriteLine("Time intersect  First element custom {0}", stopwatch.ElapsedTicks);
                stopwatch.Reset();
            }

            stopwatch.Start();
            for (int i = 0; i < 100000; i++)
            {
                var result = hashSetB.Intersect(hashSetA).ToList();
            }

            stopwatch.Stop();

            Console.WriteLine("Time intersect classic {0}", stopwatch.ElapsedMilliseconds);

            stopwatch.Reset();

            stopwatch.Start();
            for (int i = 0; i < 100000; i++)
            {
                var result = hashSetB.MyIntersect(hashSetA).ToList();
            }

            stopwatch.Stop();

            Console.WriteLine("Time intersect custom {0}", stopwatch.ElapsedMilliseconds);
            stopwatch.Reset();
        

            Console.ReadLine();
        }
    }
}
```
Although the first time you use MyIntersect you get some hit I guess the jit compilation.

**Comment by JonHanna** [comment]
It's not checking the comparer, which is a clear bug, but not an insurmountable one.

**Comment by plemanach** [comment]
you mean something like that:
```
public static class LinqExtension
	{
		internal static IEnumerable<T> MyIntersect<T>(this IEnumerable<T> first, IEnumerable<T> second)
		{
			var firstHashset = first as HashSet<T>;
			var secondHashset = second as HashSet<T>;
			if (firstHashset != null && secondHashset != null)
			{
				if(!AreEqualityComparersEqual<T>(firstHashset, secondHashset))
				   return Enumerable.Empty<T>();

				return (firstHashset.Count > secondHashset.Count)
					? firstHashset.Intersect(second)
						: secondHashset.Intersect(first);
			}
			if (firstHashset != null) { return firstHashset.Intersect(second); }
			if (secondHashset != null) { return secondHashset.Intersect(first); }
			return first.Intersect(second);
		}

		static IEnumerable<T> Intersect<T>(this HashSet<T> firstHashset, IEnumerable<T> second) {
	
			foreach (var tmp in second) {
				if (firstHashset.Contains(tmp)) { yield return tmp; }
			}
		}


		private static bool AreEqualityComparersEqual<T>(HashSet<T> set1, HashSet<T> set2)
		{
			return set1.Comparer.Equals(set2.Comparer);
		}
	}
```

**Comment by JonHanna** [comment]
Yes.

There are also improvements available if only one of the source enumerables is a hashset that this doesn't attempt, though a new set would need to be used to prevent duplicates (not needed when both are sets because duplicates are already impossible) that might be worth investigating.

In the documentation of the method, there is the remark:

> When the object returned by this method is enumerated, Intersect enumerates first, collecting all distinct elements of that sequence. It then enumerates second, marking those elements that occur in both sequences. Finally, the marked elements are yielded in the order in which they were collected.

Strictly swapping the two hashsets breaks this. I would say that should be allowed because while there is a consistent order to the enumeration of a hashset, that consistent order is *not* specified and so shouldn't be depended upon, but I think that issue needs to be considered.

**Comment by plemanach** [comment]
Yes I do not think it is an issue as stated on the hashset documentation :

The HashSet<T> class provides high-performance set operations. A set is a collection that contains no duplicate elements, and whose elements are in no particular order.

So one cannot rely on any order.

I did not get your remark on "if only one of the source enumerables is a hashset that this doesn't attempt"

if only one hashset is passed it still call Intersect<T>(this HashSet<T> firstHashset, IEnumerable<T> second) .

**Comment by plemanach** [comment]
I am thinking maybe it is not worth or possible to do optimization with HashSet and Enumeration. if we stick to HashSet\HashSet and allow swapping meaning ignoring the unknown order then we get a good optimization. if we introduce Enumeration we need to care to order then we cannot do swapping  hence optimization is not working.

**Comment by JonHanna** [comment]
If you are going to deal with HashSet/OtherEnumerable, it would be better to only store the duplicates that do match:

```C#
Set<T> found = new Set<T>(comparer);
foreach(var item in second)
{
  if (hashSet.Contains(item) && found.Add(item)) yield return item
}

Whether that wins enough to be worth it is another matter. As indeed is whether the original idea wins enough; the question is how often is one likely to have hashset's as the source and not just use hashset-based operations. The cost of checking if the the optimisation can be applied is very small and the win very big, but if those checks are almost always saying "not a hashset" then the balance is a nett lose.

**Comment by plemanach** [comment]
Maybe it miss a method in the interface ISet IEnumerable Intersect(IEnumerable<T> other).

I dont think the IntersectWith is good enough as it modify the HashSet.

**Comment by plemanach** [comment]
A narrow version of the optimization but I do not think there is really more to optimize because of the constraint on Enumerable order(you cannot swap sets), the good thing is no downside. We get what you expect good speed between HashSets.

What do you think ?

```
public static class EnumerableExtension
	{
							
		public static IEnumerable<TSource> Intersect<TSource>(this HashSet<TSource> first, HashSet<TSource>  second)
		{
			if (first == null) throw new ArgumentException("first");
			if (second == null) throw  new ArgumentException("second");

			if(!AreEqualityComparersEqual<TSource>(first, second))
				return Enumerable.Empty<TSource>();

			return (first.Count > second.Count) ? first.IntersectEnumerator(second):second.IntersectEnumerator(first) ;
		}

		private static bool AreEqualityComparersEqual<T>(HashSet<T> set1, HashSet<T> set2)
		{
			return set1.Comparer.Equals(set2.Comparer);
		}

		private static IEnumerable<T> IntersectEnumerator<T>(this HashSet<T> firstHashset, HashSet<T>  second) {

			foreach (var tmp in second) {
				if (firstHashset.Contains(tmp)) { yield return tmp; }
			}
		}
	}
```

**Comment by Eyas** [comment]
Seems like returning `Enumerable.Empty<TSource>()` on `Intersect` is a noticeable change, correct?

In general, previously, `Comparer<T>.Default` was always used in `Intersect`, and now `firstHashset`'s comparer is used instead.

**Comment by plemanach** [comment]
Yes something like that then



```
public static IEnumerable<TSource> Intersect<TSource>(this HashSet<TSource> first, HashSet<TSource>  second)
		{
			if (first == null) throw new ArgumentException("first");
			if (second == null) throw  new ArgumentException("second");

			return (first.Count > second.Count) ? 
				first.IntersectEnumerator(second, EqualityComparer<TSource>.Default):
				second.IntersectEnumerator(first, EqualityComparer<TSource>.Default);
		}

		public static IEnumerable<TSource> Intersect<TSource>(this HashSet<TSource> first, HashSet<TSource>  second, EqualityComparer<TSource> comparer)
		{
			if (first == null) throw new ArgumentException("first");
			if (second == null) throw  new ArgumentException("second");

			return (first.Count > second.Count) ? 
				first.IntersectEnumerator(second, comparer):
					second.IntersectEnumerator(first, comparer);
		}
	
		private static IEnumerable<TSource> IntersectEnumerator<TSource>(this HashSet<TSource> first, HashSet<TSource>  second, EqualityComparer<TSource> comparer) {

			if (first.Comparer != comparer)
				return IntersectIterator (first, second, comparer);
			else
				return IntersectEnumerator (first, second);
		}

		private static IEnumerable<TSource> IntersectEnumerator<TSource>(this HashSet<TSource> first, HashSet<TSource>  second) {

			foreach (var tmp in second) {
				if (first.Contains(tmp)) { yield return tmp; }
			}
		}

```

**Comment by karelz** [comment]
@plemanach do you think you have an optimization we could/should take? (disclaimer: I didn't read all the details)

**Comment by stephentoub** [comment]
I'm going to close this.  If there's an optimization to be made, we'd welcome a PR (including details on what gets faster, what gets slower, and for what real-world scenarios the perf improvement is meaningful), but in general we don't need issues tracking hypothetical optimizations, and the issue has been open now for over two years with no progress.  Thanks.
