### ISSUE TITLE
IImmutableIsDefault Interface.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/corefx#31078]
There is a hacky section of code in [Roslyn](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis/TreeDumper.cs,158)
```c#
      // an (awful) test for a null read-only-array.  Is there no better way to do this?
        private static bool IsDefaultImmutableArray(Object o)
        {
             var ti = o.GetType().GetTypeInfo();
            return ti.IsGenericType && ti.GetGenericTypeDefinition() == typeof(ImmutableArray<>) &&
                (bool)ti.GetDeclaredMethod("get_IsDefault").Invoke(o, Array.Empty<object>());
        }
```
The could be much simpler if it `ImmutableCollections` implemented an interface, so it would be possible to check if it is the default without knowing the explicit generic T-ness.  

For example 
```vbnet
interface IImmutableIsDefault
  Readonly Property IsDefault As Boolean
End Interface
```

```c#
 // an (awful) test for a null read-only-array.  Is there no better way to do this?
private static bool IsDefaultImmutableArray(Object o)
{
  return  (o is IImmutableIsDefault i) && i.IsDefault;
}
```

**Comment by safern** [comment]
I don't really like adding interfaces just to avoid some very specific scenario that is doing a hacky workaround. I agree it would make it simpler, but also it would make us live with that Interface, which only has a single property to simplify this scenario, and then we can't modify that interfaces. Interfaces are pretty tricky on adding them to the framework, so I don't think there is a strong motivation to add this interface. Plus the issue has been open for 9 months already and there is no more scenarios or interest on this.

Closing per comment above, please reopen if you support this and think it should really be added.
