### ISSUE TITLE
.net core on Macosx connecting to Remote Microsoft Sqlserver

### ISSUE THREAD

**Issue by MulderLiu** [dotnet/corefx#31090]
Environment:

Dot.net Core Version: .net core 2.1.2
Operating System: Macos 10.13.2
Sqlserver Hosted on Windows: **Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)**

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.302 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Same code on windows machine/dotnet 2.1.2 is good**
**The network state of windows and MAC is good**

Error:

System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)

**Comment by wfurt** [comment]
can you provide some simple repro code? And possibly network packet capture (dns + SQL)
Is there any chance that you have interference with some kind of firewall?

**Comment by karelz** [comment]
Not actionable + no answer for 3.5 weeks.
If there is additional information, or repro, or you can reproduce it on multiple machines, please let us know and feel free to reopen.
