### ISSUE TITLE
EventLog.CreateEventSource limits  log name similarity to first 8 chars

### ISSUE THREAD

**Issue by thesourcerer** [dotnet/corefx#31119]
CreateEventSource  verifies that there is no existing log name that starts with the same 8 chars.
From test we did, it does not seem to be a windows limitation, (maybe it was long time ago).

I think it would be a good idea to simply remove this check and allow the flexibility of longer names.

**Comment by thesourcerer** [comment]
More info:
We tested and verified there is no windows limitation on:
Windows Server 2008 R2
Windows Server 2012 R2
Windows 10

**Comment by danmosemsft** [comment]
Fair enough. If someone wants to offer a PR, go ahead 😀
