### ISSUE TITLE
CORE 2+ on a new OS

### ISSUE THREAD

**Issue by lennane** [dotnet/corefx#31135]
I happen to own a truly fine RTOS that was developed a number of years ago. We are interested in adapting it to be used as an OS running under .NET Core. 
What I have been seeking is a design document that lists the required features of the OS to enable the mounting of .NET Core.
So far--no luck. I have looked through the .NET Core source. Specific functions are fairly easy to read and understand. However, there must be a design document the was used to port LINUX and iOS. 
This would be similar to the concept of .NET Standard but in the inverse.
I would also like to discuss this project with a live person at Microsoft.

**Comment by karelz** [comment]
There are some docs: https://github.com/dotnet/source-build/blob/dev/release/2.1/Documentation/boostrap-new-os.md
And stories behind porting to [FreeBSD](https://github.com/dotnet/coreclr/issues/18067) and [Android](https://github.com/dotnet/coreclr/issues/1097).

I would recommend to read the docs and stories about ports. They are rather involved.
If you have questions about general approach, you will see experts active on those issues. It is probably easier than talking to live person ;)

It would be good to reference your RTOS - it will help with prioritization of general help over other OS ports (e.g. FreeBSD, Android). Thanks!

**Comment by Clockwork-Muse** [comment]
@karelz - that bootstrap link is 404

**Comment by karelz** [comment]
Quick search discovered this: https://github.com/dotnet/source-build/blob/master/Documentation/boostrap-new-os.md (updating above to avoid confusion in future)

**Comment by lennane** [comment]
I agree. The link is gone
 
In a message dated 7/17/2018 5:19:11 PM Eastern Standard Time, notifications@github.com writes:

 
@karelz - that bootstrap link is 404

**Comment by lennane** [comment]
This may be the correct file
 
https://github.com/dotnet/source-build/blob/master/Documentation/boostrap-new-os.md
 
In a message dated 7/17/2018 5:19:11 PM Eastern Standard Time, notifications@github.com writes:

 
@karelz - that bootstrap link is 404

**Comment by lennane** [comment]
I was able to find the referenced file. However, it still appears to be quite relative to environments that appear close to LINUX.
 
Thanks for you info. I'll keep researching.
 
Jim
 
 
In a message dated 7/17/2018 4:32:33 PM Eastern Standard Time, notifications@github.com writes:

 
There are some docs: https://github.com/dotnet/source-build/blob/dev/release/2.1/Documentation/boostrap-new-os.md
 And stories behind porting to FreeBSD and Android.
I would recommend to read the docs and stories about ports. They are rather involved.
 If you have questions about general approach, you will see experts active on those issues. It is probably easier than talking to live person ;)
It would be good to reference your RTOS - it will help with prioritization of general help over other OS ports (e.g. FreeBSD, Android). Thanks!

**Comment by karelz** [comment]
@lennane we didn't port to non-Linux OS, so we don't have anything more than that.

**Comment by karelz** [comment]
Seems to be answered, closing.

**Comment by lennane** [comment]
I understand that. However, what was the specification for porting to LINUX. 
 
Is there documentation listing the necessary and sufficient conditions to perform a port. Particularily what functionality was the OS required to support in terms of calls to and required results from.
 
It is difficult for me to accept that is was an ad-hoc effort on a project that was clearly massive and expensive.
 
Jim
 
In a message dated 7/18/2018 5:15:52 AM Eastern Standard Time, notifications@github.com writes:

 
@lennane we didn't port to non-Linux OS, so we don't have anything more than that.

**Comment by karelz** [comment]
@lennane I don't believe there was any upfront specification. However, you can look at the PAL (Platform Abstraction Layer) code in CoreCLR and CoreFX. They define what is necessary to abstract the OS from the rest of the runtime/core libraries.
IMO in practice, large projects like porting to new OS are matter of taking the closest OS and then iterating on which APIs are there / missing. Often you use API shape of one OS and simulate the same APIs using the new OS. You first do the minimal to have HelloWorld running, then you add on more. It's a lot of work and it is hard to sit down and identify and estimate all work needed upfront (beyond just listing all the APIs which need to be "somehow" simulated and then going down the list - pontetially in priority order).

**Comment by lennane** [comment]
The best help so far,
Thanks
 
Jim
 
In a message dated 7/19/2018 5:23:22 AM Eastern Standard Time, notifications@github.com writes:

 
@lennane I don't believe there was any upfront specification. However, you can look at the PAL (Platform Abstraction Layer) code in CoreCLR and CoreFX. They define what is necessary to abstract the OS from the rest of the runtime/core libraries.
 IMO in practice, large projects like porting to new OS are matter of taking the closest OS and then iterating on which APIs are there / missing. Often you use API shape of one OS and simulate the same APIs using the new OS. You first do the minimal to have HelloWorld running, then you add on more. It's a lot of work and it is hard to sit down and identify and estimate all work needed upfront (beyond just listing all the APIs which need to be "somehow" simulated and then going down the list - pontetially in priority order).
