### ISSUE TITLE
FileStream.Windows.cs can freeze on Interop.Kernel32.Readfile

### ISSUE THREAD

**Issue by thyams** [dotnet/corefx#31138]
Tracked an infinite loop situation triggered by BenchmarkDotNet.

https://github.com/dotnet/corefx/blob/015ee21f6fe1eadad478d8c9409c95cf98c2b121/src/Common/src/CoreLib/System/IO/FileStream.Windows.cs#L1197

My project with Benchmark ready to go.
https://github.com/thyams/CookedRabbit

Opened an incident with BenchmarkDotNet and optimized their StreamReader loop:
https://github.com/dotnet/BenchmarkDotNet/pull/830

Other issue is abated. Now it just never returns from FileStream.Windows.cs line 1197. That means the underlying issue was probably this to begin with.

![image](https://user-images.githubusercontent.com/1414138/42851058-ae4b8ad2-89f8-11e8-8140-73a7853159b5.png)

![image](https://user-images.githubusercontent.com/1414138/42851080-bf11eb4a-89f8-11e8-88eb-e15dd9ecdc79.png)

Frozen on this:
```
00007FFA31861B1E  jmp         00007FFA31861B2D 
```

Corresponding line:
```
00007FFA31861B2D  xor         ecx,ecx  
```

Function Scope, Disassembly with Bytes:
```
  1186:             int numBytesRead = 0;
00007FFA31861AE0 55                   push        rbp  
00007FFA31861AE1 56                   push        rsi  
00007FFA31861AE2 48 83 EC 38          sub         rsp,38h  
00007FFA31861AE6 48 8D 6C 24 40       lea         rbp,[rsp+40h]  
00007FFA31861AEB 33 C0                xor         eax,eax  
00007FFA31861AED 48 89 45 E8          mov         qword ptr [rbp-18h],rax  
00007FFA31861AF1 48 8B F1             mov         rsi,rcx  
00007FFA31861AF4 48 8B CA             mov         rcx,rdx  
00007FFA31861AF7 49 8B 10             mov         rdx,qword ptr [r8]  
00007FFA31861AFA 45 8B 40 08          mov         r8d,dword ptr [r8+8]  
00007FFA31861AFE 33 C0                xor         eax,eax  
00007FFA31861B00 89 45 F0             mov         dword ptr [rbp-10h],eax  
00007FFA31861B03 48 89 55 E8          mov         qword ptr [rbp-18h],rdx  
  1189:             {
  1190:                 r = _useAsyncIO ?
  1191:                     Interop.Kernel32.ReadFile(handle, p, bytes.Length, IntPtr.Zero, overlapped) :
  1192:                     Interop.Kernel32.ReadFile(handle, p, bytes.Length, out numBytesRead, IntPtr.Zero);
00007FFA31861B07 80 7E 74 00          cmp         byte ptr [rsi+74h],0  
00007FFA31861B0B 75 13                jne         00007FFA31861B20  
00007FFA31861B0D 45 33 C9             xor         r9d,r9d  
00007FFA31861B10 4C 89 4C 24 20       mov         qword ptr [rsp+20h],r9  
00007FFA31861B15 4C 8D 4D F0          lea         r9,[rbp-10h]  
00007FFA31861B19 E8 52 B2 BD FF       call        00007FFA3143CD70  
00007FFA31861B1E EB 0D                jmp         00007FFA31861B2D  <- FROZEN HERE
00007FFA31861B20 4C 89 4C 24 20       mov         qword ptr [rsp+20h],r9  
00007FFA31861B25 45 33 C9             xor         r9d,r9d  
00007FFA31861B28 E8 53 B2 BD FF       call        00007FFA3143CD80  
00007FFA31861B2D 33 C9                xor         ecx,ecx  
00007FFA31861B2F 48 89 4D E8          mov         qword ptr [rbp-18h],rcx  
  1193:             }
  1194: 
  1195:             if (r == 0)
00007FFA31861B33 85 C0                test        eax,eax  
00007FFA31861B35 75 1C                jne         00007FFA31861B53  
00007FFA31861B37 48 8B CE             mov         rcx,rsi  
00007FFA31861B3A 33 D2                xor         edx,edx  
00007FFA31861B3C E8 BF 00 00 00       call        00007FFA31861C00  
00007FFA31861B41 48 8B 75 30          mov         rsi,qword ptr [rbp+30h]  
00007FFA31861B45 89 06                mov         dword ptr [rsi],eax  
  1198:                 return -1;
00007FFA31861B47 B8 FF FF FF FF       mov         eax,0FFFFFFFFh  
00007FFA31861B4C 48 8D 65 F8          lea         rsp,[rbp-8]  
00007FFA31861B50 5E                   pop         rsi  
00007FFA31861B51 5D                   pop         rbp  
00007FFA31861B52 C3                   ret  
  1199:             }
  1200:             else
  1201:             {
  1202:                 errorCode = 0;
00007FFA31861B53 33 C0                xor         eax,eax  
00007FFA31861B55 48 8B 75 30          mov         rsi,qword ptr [rbp+30h]  
00007FFA31861B59 89 06                mov         dword ptr [rsi],eax  
  1203:                 return numBytesRead;
00007FFA31861B5B 8B 45 F0             mov         eax,dword ptr [rbp-10h]  
00007FFA31861B5E 48 8D 65 F8          lea         rsp,[rbp-8]  
00007FFA31861B62 5E                   pop         rsi  
00007FFA31861B63 5D                   pop         rbp  
00007FFA31861B64 C3                   ret  
```

**Comment by thyams** [comment]
Great questions, no the jump is frozen in place, not fluttering back and forth.
AsyncIO is false.
NetCore 2.1.4 (SDK v2.1.302).
All Windows 10 updates (OS Build: 17134.167)
Latest version of Visual Studio 2017 Professional (stable branch / non preview).

**Comment by thyams** [comment]
Tracked it down to Process RedirectStandardInput and RedirectStandardOutput. If I had to guess, multiple dotnet hosts are writing to a central host.

@adamsitnik Is my understanding correct? (Based on ConsoleHost -> SynchronousProcessOutputLoggerWithDiagnoser)

**Comment by stephentoub** [comment]
It's not returning from the read on the file stream because this is actually a pipe to another process and the other process still has its end of the pipe open / that process hasn't gone away... so this code reading from the pipe is just going to sit blocked waiting for something more to read or for the pipe to close.

**Comment by thyams** [comment]
Thanks Stephen. That makes sense but I wonder why it only affects my library call and ocassionally BenchmarkDotNet build in Travis CI.

I will figure it out.

If a Pipe is blocked, should it not throw an exception? I get one when trying to Read or Execute a locked file in a stream... Why not another pipe?

**Comment by stephentoub** [comment]
> If a Pipe is blocked, should it not throw an exception?

No. The whole point of doing a read on a pipe is to wait for data to read to be available. So it'll block until either data is available or the pipe is closed.

**Comment by thyams** [comment]
Thanks Stephen, this sounds like an implementation related issue.

I will close this ticket. Armed with this knowledge I should be able to resolve it now that I know for sure what I am looking for.
