### ISSUE TITLE
Support for 128-bit AVX intrinsics

### ISSUE THREAD

**Issue by Porges** [dotnet/corefx#31145]
The AVX instructions in `System.Runtime.Intrinsics.Experimental` appear to be missing support for the 128-bit vectors. 

From [Intel's guide](https://software.intel.com/sites/default/files/managed/c5/15/architecture-instruction-set-extensions-programming-reference.pdf):
> Applications using AVX and FMA should migrate legacy 128-bit SIMD instructions to their 128-bit AVX equivalents. AVX supplies the full complement of 128-bit SIMD instructions except for AES and PCLMULQDQ. 

So it sounds like all the 128-bit instructions supplied by the SSE intrinsics should be in the AVX intrinsics too, to help avoid mixing SSE and VEX code?

**Comment by tannergooding** [comment]
@Porges, yup. Since CoreCLR is a JIT, it can detect the current hardware and just emit the better code 😄

**Comment by Porges** [comment]
@tannergooding yes, I just wasn't expecting `Sse.Instruction` to generate an AVX instruction 😉
