### ISSUE TITLE
Behaviour change between SocketsHttpHandler and HttpClientHandler regarding 'Accept' header (.NET 2.1)

### ISSUE THREAD

**Issue by kbaladurin** [dotnet/corefx#31155]
When we use `SocketsHttpHandler` `Accept` header isn't set implicitly but if we use older `HttpClientHandler` it's set to `*/*` by default. This situation can be reproduced using following sample:
```cs
using System;
using System.IO;
using System.Net;
using System.Text;
using System.Threading.Tasks;

namespace webrequest_1
{
    public class WebRequestGetExample
    {
        public static void Main ()
        {
            ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };

            WebRequest request = WebRequest.Create ("https://www.google.com");
            
            WebProxy myProxy = new WebProxy("http://127.0.0.1:8080");
            request.Proxy = myProxy;
            
            HttpWebResponse response = (HttpWebResponse)request.GetResponse ();

            Stream dataStream = response.GetResponseStream ();
            StreamReader reader = new StreamReader (dataStream);
            string responseFromServer = reader.ReadToEnd ();

            Console.WriteLine (responseFromServer);

            reader.Close ();
            dataStream.Close ();
            response.Close ();
        }
    }
}
```
**SocketsHttpHandler**
```
$ ./corerun webrequest-1.dll
```
Request:
```
GET / HTTP/1.1
Connection: close
Host: www.google.com
```
**HttpClientHandler**
```
$ DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0 ./corerun webrequest-1.dll
```
Request:
```
GET / HTTP/1.1
Host: www.google.com
Accept: */*
Connection: close
```
Requests was intercepted using proxy.

Is it expected behavior? Thank you!

**Comment by kbaladurin** [comment]
cc @alpencolt

**Comment by kbaladurin** [comment]
@gbalykov

**Comment by alpencolt** [comment]
cc @danmosemsft @weshaggard @jkotas

**Comment by davidsh** [comment]
>but if we use older HttpClientHandler it's set to */* by default

That was a side-affect behavior on Linux with CurlHandler which uses libcurl.  It was not part of the standard .NET behaviors for HttpClient API for .NET Framework or .NET Core on Windows.

As of .NET Core 2.1, the HTTP stack has been standardized and uses the new SocketsHttpHandler underneath HttpClientHandler.  It follows the consistent API behavior of HttpClient for .NET Framework and .NET Core on Windows.  The "Accept" header is something that developers controls when using the HttpClient APIs.

So, this behavior change from .NET Core 2.0 to 2.1 on Linux is by-design.

cc: @karelz @stephentoub @geoffkizer

**Comment by kbaladurin** [comment]
@davidsh thank you for explanation!
