### ISSUE TITLE
Why BitConverter Span-based APIs not exist when target netstandard2.0

### ISSUE THREAD

**Issue by csyszf** [dotnet/corefx#31154]
There're no BitConverter span-based APIs like `int ToInt32(ReadOnlySpan<byte> value)` unless the target framework is .netcoreapp

I found BitConverter extensions in https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs, but the latest package of `System.Runtime.Extensions` is 4.3.0 and updated on 2016.

How can I using those APIs in netstandard projects?

**Comment by davidfowl** [comment]
netstandard 2.0 existed before Span did.

**Comment by csyszf** [comment]
@davidfowl thanks for your reply.
It seems that I have some misunderstanding about corefx(libraries), .net standard and .net core runtime.
`Span` can be using in netstandard 2.0 library projects by referencing `System.Memory` nuget package.
what I expected before is that there would be some span-related APIs exist in new versions of `System.Runtime.Extensions`

**Comment by ViktorHofer** [comment]
The System.Runtime.Extensions nuget package won't be updated anymore as it is now inbox (part of the framework). You can either target netcoreapp2.1 or wait for netstandard vNext which will _probably_ contain the mentioned APIs.
