### ISSUE TITLE
Why isn't the new UX feature (.net core 3) cross platform

### ISSUE THREAD

**Issue by SharperC** [dotnet/corefx#31173]
A desktop ui system for .net core was probably one of the most requested features, and im glad it finally gets added. But why just for windows? ,net cor is awesome for running basiclly everywhere so why not add a ux everywhere? A wpf or win forms similar system would be what we need.
I and probably a lot of other people would really appreciate this in the next version of ,net core.

https://blogs.msdn.microsoft.com/dotnet/2018/05/07/net-core-3-and-support-for-windows-desktop-applications/

**Comment by ObsidianMinor** [comment]
As the blog post says:

> From a 1000-meter view, you can think of WPF as a rich layer over DirectX and Windows Forms as thinner layer over GDI Plus. WPF and Windows Forms do a great job of exposing and exercising much of the desktop application functionality in Windows. It’s the C# code in Windows Forms and WPF that we’ll include as a set of libraries with .NET Core 3. Windows functionality, like GDI Plus and DirectX, will remain in Windows.

**Comment by jnm2** [comment]
I'd estimate the cost of the work at somewhere between ten and a hundred times what it would take to simply move the existing battle-tested code from .NET Framework onto .NET Core.

**Comment by danmosemsft** [comment]
The comments above basically answer this. This issue seems to be gathering the comments about cross-platform UI on .NET Core: https://github.com/dotnet/corefx/issues/21803

I am going to close this in favor of that.
