### ISSUE TITLE
Resetting Pipe does not reset reader and writer awaitables

### ISSUE THREAD

**Issue by ObsidianMinor** [dotnet/corefx#31176]
Resetting a Pipe object through Pipe.Reset does not reset reader and writer awaitables. This leads to inconsistent behavior where before resetting, read methods return false or return tasks which complete when the writer is flushed; instead, after resetting, read methods return empty buffers if no data is available.

New pipe:
![complete](https://user-images.githubusercontent.com/10121870/42918064-291db938-8ada-11e8-9150-37b4a44fcf90.png)
As you can see, the `_readerAwaitable`'s IsCompleted property is false

Completed pipe:
![reset](https://user-images.githubusercontent.com/10121870/42918073-30d85d68-8ada-11e8-8db2-9d336cf87f14.png)
Upon completing the pipe, IsCompleted is now true as expected

Reset pipe:
![completed](https://user-images.githubusercontent.com/10121870/42918081-3cf1d638-8ada-11e8-94ab-f14861e22a6a.png)
After resetting the pipe, IsCompleted is still true

**Comment by davidfowl** [comment]
Looks like a bug

**Comment by Tragetaschen** [comment]
Im completing both Reader and Writer of my Pipe and run `Reset`. When I then start both read and write tasks for another round of data transfer, I get an IOE ("Reading is already in progress") from `PipeReader.ReadAsync`, but only if the Writer hasn't written anything yet.

That's the same thing, isn't it?

**Comment by ObsidianMinor** [comment]
It can be related to this depending on if you assumed that reset actually reset the awaitables.

**Comment by Tragetaschen** [comment]
According to the debugger, the reader awaitable has completed set to true after `Reset` in my case which is the main change in the PR.
Re-creating the Pipe instead of `Reset`ting solves my use case for the time being.
