### ISSUE TITLE
The background of the PNG picture turns white

### ISSUE THREAD

**Issue by LuceLuo** [dotnet/corefx#31178]
I used "libgdiplus --with-pango" to solve the problem of text loss, but when using "DrawImage" to superimpose PNG pictures, the transparent bottom of the PNG picture turned white. I don't know whether the problem is from this project or libgdiplus. I hope that the person you know can give me the answer, thank you.

**Comment by LuceLuo** [comment]
#30867 correlation

**Comment by filipnavara** [comment]
It might have been fixed recently or could be related to https://github.com/mono/libgdiplus/pull/373.

**Comment by filipnavara** [comment]
The issue should be reported to libgdiplus if it's not happening on Windows. If you include a small C# code (like the one referenced in issue https://github.com/mono/libgdiplus/issues/372) you will greatly increase the chances of someone looking into it and fixing it.

**Comment by LuceLuo** [comment]
In the Windows environment, it is possible to make mistakes in the Linux system.

**Comment by safern** [comment]
@LuceLuo thanks for reporting the issue, I think this is a libgdiplus issue so I will be closing this. Please feel free to open on in libgdiplus and link it to this issue.
