### ISSUE TITLE
[Info] InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#31186]
Just raising this so people will find the issue in a search.

This is an intentional exception that is being thrown by the Dictionary in newer .NET Core (issue https://github.com/dotnet/corefx/issues/28123, PR https://github.com/dotnet/coreclr/pull/16991) which indicates the dictionary is being incorrectly modified concurrently by multiple threads (it wouldn't have been detected previously and could lead to infinite loops)

Also applies now to HashSets (issue https://github.com/dotnet/corefx/issues/28209, PR https://github.com/dotnet/corefx/pull/28225)

/cc @danmosemsft @vancem @jkotas @stephentoub

Issues are being filed upstream https://github.com/IdentityServer/IdentityServer4/issues/2453 and https://github.com/aspnet/EntityFrameworkCore/issues/12713 and https://github.com/aspnet/EntityFrameworkCore/issues/12713#issuecomment-406225716

**Comment by benaadams** [comment]
Just raising this so people will find the issue in a search.

This is an intentional exception that is being thrown by the Dictionary in newer .NET Core (issue https://github.com/dotnet/corefx/issues/28123, PR https://github.com/dotnet/coreclr/pull/16991) which indicates the dictionary is being incorrectly modified concurrently by multiple threads (it wouldn't have been detected previously and could lead to infinite loops, or incorrect data returned)

Also applies now to HashSets (issue https://github.com/dotnet/corefx/issues/28209, PR https://github.com/dotnet/corefx/pull/28225)

`Dictionary` and `HashSet` are not safe for concurrent readers and writers. Dictionaries/Hashsets that are not written to after set-up are safe for concurrent readers. They are never safe for a write and any other operation (read or write).

They either need:
1. Single threaded access
2. Use under lock 
3. Change to a `ConcurrentDictionary`
4. Or use immutable approach:
   1. Change to `ImmutableDictionary`, `ImmutableHashSet` or copy dict, add to new copy
   2. `Interlocked.CompareExchange` on reference with new dict (returned from Add for immutable, or copy for Dict) with added item
   3. If `CompareExchange` fails do re-copy + add (go to ii.)

/cc @danmosemsft @vancem @jkotas @stephentoub

Issues are being filed upstream https://github.com/IdentityServer/IdentityServer4/issues/2453 and https://github.com/aspnet/EntityFrameworkCore/issues/12713 and https://github.com/aspnet/EntityFrameworkCore/issues/12713#issuecomment-406225716

**Comment by terrajobst** [comment]
Presumably this was filed as closed to have a central place?

**Comment by benaadams** [comment]
> Presumably this was filed as closed to have a central place?

Yes so it can be found via search using the exception message (as the issue and PR don't directly quote it)
