### ISSUE TITLE
Proposal: Provide specialized collections aka Power Collections

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#31191]
## Proposal

We are hitting limitations with our in-built collections all over the places, either performance based (i.e. allocation) or feature based). After talking with @jkotas offline we agreed that it would be ideal if we would provide commonly used specialized collections (like a Dictionary<string, string> or a PriorityQueue) as a source based nuget package. That would allow us to provide basic enhanced functionality over the general purpose inbox types but still the ability to tweak them on demands.

Considerations:
- What kind of collection types would benefit from specialization? 
- Where do we see gaps to our competition (again, performance or feature wise)?
- Where would such a package be hosted and how would it be deployed? (corefx vs community corefx repo)
- Is a source based nuget package feasible and are we easily able to use it inside corefx?

## Example

Currently working in Regex to avoid allocation I stumbled upon places where Unicode categories are statically stored in a Dictionary<string, string>. Trying to get the value out of it involves allocation because there is currently no way to pass a ReadOnlySpan<char> as a key in to get the value. Providing a specialized version would allow us to add an additional overload for ReadOnlySpan<char>.

## References

Dictionary/List ref api additions: https://github.com/dotnet/coreclr/pull/17405#issuecomment-378627247
PriorityQueue: https://github.com/dotnet/corefx/issues/574#issuecomment-308491122 & https://github.com/dotnet/corefxlab/pull/1850
OrderedDictionary<,>: https://github.com/dotnet/corefx/issues/26634

cc @jkotas @karelz @benaadams @danmosemsft

**Comment by danmosemsft** [comment]
Perhaps we could have a Dictionary implementation specialized for keys of type `int` -- that would be used by k-nucleotide (if they accept use of `Long2IntOpenHashMap` [by Java](https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/knucleotide-java-1.html)).

Why do you propose a source based package?

@stephentoub

**Comment by danmosemsft** [comment]
cc @AnthonyLloyd for that.

**Comment by prajaybasu** [comment]
OrderedDictionary<TKey, TValue> would also be nice.  (Related: #26634)

**Comment by ViktorHofer** [comment]
> OrderedDictionary<TKey, TValue> would also be nice. (Related: #26634)

Thanks I added it to the links.

> Why do you propose a source based package?

One of the requirements for such a package would be that we can change it frequently for our inbox stuff (i.e. adding new apis that accept types that we just added in master) but still have a stable version that ideally targets netstandard. We did the same with Span by cross-compiling for netstandard and netcoreapp. That is definitely an approach we can think about but during my discussion with @jkotas he pointed out that source based nuget packages are more versatile as consumer will always want to fine-tune their collections which is easily possible with that approach.

**Comment by AnthonyLloyd** [comment]
Possibly:

1) A counting Dictionary<K,int> (or even Dictionary<int,int>) with Increment(K key) and Decrement(K key). For reference counting etc.
2) An aggregating Dictionary<K,V,R>(Func<V,R> seed, Func<R,V,R> accum) with Add(K v, V v).

Possibly 2) could be used in Enumerable.GroupBy.

**Comment by benaadams** [comment]
A fast Type `Dictionary<Type, ...>` e.g. https://github.com/benaadams/Ben.TypeDictionary

**Comment by AnthonyLloyd** [comment]
@benaadams I always assumed the following through some magic had good perf

```csharp
static class TypeHolder<T>
{
    public static string Value;
}

TypeHolder<int>.Value = "int";
TypeHolder<string>.Value = "string";
```

**Comment by AndyAyersMS** [comment]
For fast dictionaries consider different hash -> bucket mapping strategies. The current dictionary's modulo a prime is slow (about 1/3 the cycle cost for a successful TKey=int lookup these days).

Custom vs/default comparators should be supported via subtyping or parameterization and not by options passed to the constructor, so the jit doesn't need heroics to inline comparators. If via subyping, the fast dictionary classes should be sealed.

For types where hash recomputation is cheap (ints), avoid storing the hash.

.Net settled long ago on the parallel array setup but different approaches may have appeal, eg a chunked array setup that is able to avoid LOH and should be cheaper to grow. Maybe also consider approaches that allow some mutate on read so if there are collisions frequently accessed elements can be made cheaper to find by migrating them earlier in the collision chains.

**Comment by ViktorHofer** [comment]
Thanks Andy, whoever is going to implement a fast dictionary will benefit a lot from your info.

I propose we talk about this in the Design/API review meeting. If we agree to provide these collections either inbox or as a nuget package I believe we could implement them (together with community members who are interested) fairly quick.

**Comment by Zhentar** [comment]
There are two specialized hash maps I'd like to see.

1. Fast `ulong` keyed map. Basically, applying all the optimizations Andy mentioned. My use case is string atomization while parsing Utf8 streams; when I've got a token I need to stringify, I hash the raw bytes with a high quality 64-bit hash function so that the risk of collision is low enough (even accounting for the birthday paradox) that I can treat hash equality as value equality. I'd also prefer an open addressing hash table algorithm that only takes one cache miss on random lookups ( unfortunately this last part is incompatible with a fast K-Nuc dictionary mentioned in dotnet/coreclr#15419 because K-Nuc benefits tremendously from coalesced chaining preserving insertion order locality)

1. `string` keyed map which assumes reference equality for equal values. As long as my strings are atomized it would be nice to get an extra bit of efficiency out of dictionaries using them as keys.

**Comment by danmosemsft** [comment]
Last time we discussed this it got wedged on the discussion of whether there should be a new repo. @joshfree @weshaggard is corefxlab a suitable place to put experimental code that has some infrastructure (CI) and the ability to package for nuget and might graduate to corefx later?
@karelz

**Comment by ViktorHofer** [comment]
If we ship this as a normal nuget package (not source based) this should live in corefx as we want to use it internally in master. Also as a buid from source requirement I believe we must live build netcoreapp asset.

**Comment by joshfree** [comment]
@danmosemsft yes corefxlab is the appropriate place for something like this to begin while we’re unsure if it should be promoted to corefx or not.

**Comment by mikedn** [comment]
> string keyed map which assumes reference equality for equal values

How's that different from a normal dictionary using an appropriate key comparer? (apart from the cost of interface calls that the normal dictionary incurs).

**Comment by danmosemsft** [comment]
Here's what we are going to do. We do want such a package for extended collections. I will move this issue to corefxlab. We will create a package with a name something like System.Collections.Extensions  (or System.Collections.Experimental) and put types in a temporary namespace (eg System.Collections.Extensions.Experimental) so we have the option of moving some into the BCL if they prove worthy. This will publish to myget to start.

The goal of this is to develop useful collections, but it would be nice if the kNucleotide maintainer would allow it also.

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/corefxlab #2406](https://github.com/dotnet/corefxlab/issues/2406) via [**ZenHub**](https://www.zenhub.com/)
