### ISSUE TITLE
Request: can /T:GenerateReferenceSource call /T:Build first?

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#31193]
I keep calling `/T:GenerateReferenceSource` without calling `/T:Build` before so I the ref doesn't update even if I change the source code

Would be nice if this target relied on build

**Comment by danmosemsft** [comment]
@weshaggard

**Comment by weshaggard** [comment]
From my experience folks usually have done a build already before trying to update the ref. 

The only cases I can think of where this may cause trouble is if you don't have a valid ref source file (maybe cleaned it out to regenerate) and then call Build on the src project will try to call Build on the ref which will then fail. 

I don't mind if you want to add a new wrapper target called "BuildAndGenerateReferenceSource" that will do both targets.

**Comment by ViktorHofer** [comment]
With https://github.com/dotnet/corefx/pull/34379 you can now call `dotnet msbuild /t:Rebuild /p:GenerateReferenceAssemblySource=true`. Note that this also generates refs for referenced projects so you might want to filter the changes afterwards.

**Comment by wtgodbe** [comment]
@hughbe is the solution proposed by https://github.com/dotnet/corefx/issues/31193#issuecomment-451652660 satisfactory?

**Comment by ericstj** [comment]
Thanks for the suggestion, @hughbe.  I'll roll this into the work for #33981.
