### ISSUE TITLE
HttpClientHandler: Consider adding MaxHttpVersion property

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#31207]
We are adding this to SocketsHttpHandler, see #30527.

The question is whether we should add this to HttpClientHandler as well.

```csharp
public sealed class HttpClientHandler
{
    public Version MaxHttpVersion { get; set; } // defaults to 1.1
    ...
}
```

The default would be 1.1, at least for the 2.2 release -- we may consider changing the default to 2.0 in future releases.

Reasons to add this:
(1) It's more discoverable on HttpClientHandler (vs only SocketsHttpHandler)
(2) It provides consistent behavior for HttpClientHandler regardless of whether you use SocketsHttpHandler (the default) or the platform handlers (WinHttpHandler/CurlHandler) under the covers via config switch

Concerns:
(1) Assuming the default is 1.1, this would be a change in behavior when HttpClientHandler uses the platform handler under the covers. Hopefully this isn't that common.
(2) Do we want to expose a similar property on WinHttpHandler? (CurlHandler is not public so this does not apply)

**Comment by davidsh** [comment]
Closing this in favor of #31424.
