### ISSUE TITLE
High CPU usage after await (with sample repo)

### ISSUE THREAD

**Issue by daddyman** [dotnet/corefx#31208]
Since moving to .NET Core 2.1 we have been seeing our aspnet core web api spike to 99% CPU usage on Linux. This does not happen when running on Windows.

What we observe in our application is if we make 4 or 5 API calls in quick succession then the CPU goes to 99% and stays there for a few minutes.

I was able to strip down our app and reproduce the issue in a simple app. The repo is here: https://github.com/daddyman/dotnetcorecpu

I am running .NET Core 2.1.2 using SDK 2.1.302 on Ubuntu 16.04.

It seems to have something to do with "await". In the reproduction case I have one controller that handles a POST. 
* Performing an `await Task.CompletedTask;` does not cause a problem.
* Performing an `away DummyWait();` where DummyWait is `return Task.Delay(1);` causes high CPU after hitting the server with many requests in a short time. The requests complete quickly but then the CPU goes to 99% and stays there.

In our real app I did the same change of using the `await Task.CompletedTask;` and 'await Task.DummyWait();` and saw the same difference with the CPU usage.

**Comment by davidsh** [comment]
cc: @Tratcher

**Comment by joshfree** [comment]
@brianrob could you PTAL and help route?

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Home#3344
