### ISSUE TITLE
P2P networking using TCP

### ISSUE THREAD

**Issue by FIVIL** [dotnet/corefx#31226]
Hi, i was wondering if it is possible to do P2P networking and TCP NAT traversal using .net core(not asp.net core but .net core console app) so i did some research and i come across https://blogs.msdn.microsoft.com/ncl/2009/07/27/end-to-end-connectivity-with-nat-traversal/ in MSDN but this is about .net framework and not .net core so can i use same approach in .net core as well and also i couldnt find System.net.PeerToPeer namespace in .net core which is mentioned in the blog post so does it exist and renamed or it hasnt been implemented in .net core yet?
any way i would really really appreciate if you can tell is it possible to do P2P networking and NAT traversal or tcp nat hole punching without use of 3rd party and port forwarding in .net core with IPv4 like bitcoin which can work on windows, linux, unix with the same code
TNX

**Comment by davidsh** [comment]
The System.Net.PeerToPeer namespace has not been ported to .NET Core.  There are no plans for this.

Regarding the blog article you cited, the TcpListener and UdpClient APIs should function the same in .NET Core (on Windows) as they do on .NET Framework.  So this code should work the same:

```c#
var listener = new TcpListener(IPAddress.IPv6Any, 8000); 
listener.AllowNatTraversal(true); 
listener.Start();
```

This is not something we actively test in .NET Core in repo / CI.  But the socket code should work the same as .NET Framework.

**Comment by FIVIL** [comment]
@davidsh 
well you mentioned "the TcpListener and UdpClient APIs should function the same in .NET Core (on Windows) as they do on .NET Framework" does it mean that it wont work on linux and unix as well??
if so , are there any approaches that can work cross platform in .net core sockets??

**Comment by davidsh** [comment]
>does it mean that it wont work on linux and unix as well?

I don't remember specifically whether or not the "AllowNatTraversal" APIs will work the same on Linux as I wasn't involved in that particular section of networking code when we ported it from .NET Framework to .NET Core.

**Comment by FIVIL** [comment]
@davidsh 
so from who can i ask this, or should i write bunch of codes and run on several machines and platform and see the result??

**Comment by davidsh** [comment]
>or should i write bunch of codes and run on several machines and platform and see the result??

You can browse the relevant source code in the branch to see how it works. Or you can test your scenarios.

**Comment by svick** [comment]
@FIVIL 

The code is open source (and in this case simple), so you can look at what it does.

Specifically:

https://github.com/dotnet/corefx/blob/d1da90321472db20592319336f1ba164c2674fdd/src/System.Net.Sockets/src/System/Net/Sockets/TCPListener.cs#L110-L118

This leads to:

https://github.com/dotnet/corefx/blob/d1da90321472db20592319336f1ba164c2674fdd/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L1990-L2009

And on Unix, that leads to:

https://github.com/dotnet/corefx/blob/823196ba9262b37b59800b8743da1b10f2b380e0/src/System.Net.Sockets/src/System/Net/Sockets/SocketPal.Unix.cs#L1223-L1226

This means that `AllowNatTraversal` is not supported on Unix.

And indeed, when you run the code from above, you get:

```
System.PlatformNotSupportedException: IP protection level cannot be controlled on this platform.
   at System.Net.Sockets.SocketPal.SetIPProtectionLevel(Socket socket, SocketOptionLevel optionLevel, Int32 protectionLevel)
   at System.Net.Sockets.Socket.SetIPProtectionLevel(IPProtectionLevel level)
   at System.Net.Sockets.TcpListener.AllowNatTraversal(Boolean allowed)
   at coreapp.Program.Main(String[] args) in /home/svick/coreapp/Program.cs:line 12
```

**Comment by FIVIL** [comment]
@svick  @davidsh 
tnx for your time
