### ISSUE TITLE
Ubuntu 17.10 deb package depends on the wrong libicu package

### ISSUE THREAD

**Issue by Genbox** [dotnet/corefx#31224]
When installing .NET Core 2.0.9 runtime (dotnet-runtime-2.0.9) on Ubuntu 17.10, it depends on libicu55 instead of libicu57 as it should. It is correctly stated on the [documentation page](https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x):

> libicu55 (for 16.x)
> libicu57 (for 17.x)

However, when you look in the [packages file](https://packages.microsoft.com/ubuntu/17.10/prod/dists/artful/main/binary-amd64/Packages) from the Microsoft repository, it depends on libicu55 instead of libicu57:

> Package: dotnet-runtime-2.0.9
> Depends: libc6 (>= 2.14), libcurl3 (>= 7.16.2), libgcc1 (>= 1:3.0), libgssapi-krb5-2 (>= 1.10+dfsg~), liblttng-ust0 (>= 2.5.0), libstdc++6 (>= 4.8), libunwind8, libuuid1 (>= 2.16), zlib1g (>= 1:1.1.4), **libicu55**, libssl1.0.0, dotnet-hostfxr-2.0.9

The dotnet-runtime-2.0.7 has the correct dependency (libicu57)

Semi related: #20562

**Comment by Genbox** [comment]
Mentioning @lordmike

**Comment by joshfree** [comment]
Thanks for reporting this @Genbox.  @tarekgh could you PTAL?

**Comment by tarekgh** [comment]
@joshfree this is SDK packaging issue. I think @rakeshsinghranchi may be able to help here.

**Comment by LordMike** [comment]
Is there any update on this? A newly deployed Ubuntu 17.10 on AWS EC2 still cannot install dotnet-runtime-2.0.9. I've had to re-use my modified dpkg package from 3 weeks ago, where I altered the dependency in question.

**Comment by tarekgh** [comment]
@rakeshsinghranchi could you please help with this issue?

**Comment by rakeshsinghranchi** [comment]
@leecow , can you please confirm if correct rutime package are available in the feed for ubuntu 17.10 ?

**Comment by rakeshsinghranchi** [comment]
This issue was moved to dotnet/core-setup#4494
