### ISSUE TITLE
Default version of HttpRequestMessage has broken my app

### ISSUE THREAD

**Issue by ankitbko** [dotnet/corefx#31238]
Following up on #23394.
Just bringing to your notice that, the change of default version to HTTP/2 has broken requests sent to Dynamics CRM Batch endpoint. The batch API expects multipart request having boundary as raw http request text. 
The mention of *HTTP/2* causes CRM to return a 400 response. A sample request body is as below -

```
--batch_75775fd387574ea5b7fc105ffd4c59f9
Content-Type: application/http
Content-Transfer-Encoding: binary

GET /api/data/v9.0/incident?fetchXml=SomeBigXml HTTP/2
Host: myhostname.crm.dynamics.com
Content-Type: application/json; charset=utf-8

{}
--batch_75775fd387574ea5b7fc105ffd4c59f9--
```

---
Also the comment in Version still shows it as 1.1. 
<img src="https://user-images.githubusercontent.com/3169316/43031992-7caf46a6-8cca-11e8-80b3-2147ee3e2961.png" width="420" height="320">

**Comment by davidsh** [comment]
>GET /api/data/v9.0/incident?fetchXml=SomeBigXml HTTP/2

The use of HTTP/2.0 as the default for HttpRequestMessage is something that should only have affected transport connections negotiating for HTTP/2.0 with ALPN on TLS/SSL.  The use of the "HTTP/2" should not be present at all in multi-part content nor on any request line as shown.

Can you show a small repro of this that sends a multi-part content with HttpClient APIs?  We'd like to understand how the string "HTTP/2" is getting sent on that request line.

**Comment by davidsh** [comment]
Is the `HttpMessageContent` a custom class you wrote?  Or part of the Dynamics SDK itself?

And regarding the comment being out of date as you show above:
![image](https://user-images.githubusercontent.com/7684835/43040910-47fd15c8-8d06-11e8-8931-b2e3c4996613.png)

what file is that where it is showing it out of date?  Those XML comments are not in the CoreFx source code for the HttpRequestMessage class.  If those comments are from .NET Framework, then it is correct.  .NET Framework HttpRequestMessage.Version property does default to 1.1 since 2.0 is not supported.

**Comment by ankitbko** [comment]
`HttpMessageContent` class is part of `microsoft.aspnet.webapi.client`. The screenshot above is from when I pressed F12 from asp.net core app.

```
#region Assembly System.Net.Http, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Net.Http.dll
#endregion
```

![image](https://user-images.githubusercontent.com/3169316/43041283-04d70380-8d79-11e8-9c82-16213d9c1811.png)

**Comment by davidsh** [comment]
>HttpMessageContent class is part of microsoft.aspnet.webapi.client. 

@Tratcher - Perhaps the `HttpMessageContent` class can be fixed in ASP.NET to make sure it is not serializing a request line with an "HTTP/2" version number.  It should cap that to HTTP/1.1 since that is the only valid token to put on a request line.

**Comment by Tratcher** [comment]
> Sending request with HTTP/2 will cause CRM to return 400 with a very specific error message stating that HTTP/2 is not supported in multipart content.

Can you share that exact message. I'd want to see what layer it's coming from before recommending any changes.

**Comment by ankitbko** [comment]
@Tratcher Error message - 
>{"Message":"The HTTP version 'HTTP/2' used in a batch operation request or response is not valid. The value must be 'HTTP/1.1'.","ExceptionMessage":"The HTTP version 'HTTP/2' used in a batch operation request or response is not valid. The value must be 'HTTP/1.1'.","ExceptionType":"Microsoft.OData.ODataException","StackTrace":" at Microsoft.OData.ODataBatchReader.ParseRequestLine(String requestLine, String& httpMethod, Uri& requestUri)\r\n at Microsoft.OData.ODataBatchReader.CreateOperationRequestMessageImplementation()\r\n at Microsoft.OData.ODataBatchReader.InterceptException[T](Func`1 action)\r\n at System.Web.OData.Batch.ODataBatchReaderExtensions.d__9.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.OData.Batch.DefaultODataBatchHandler.d__f.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Microsoft.Crm.Extensibility.OData.CrmODataBatchHandler.<>c__DisplayClass10_0.<b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.d__11`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.d__4`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Microsoft.Crm.Extensibility.OData.CrmODataBatchHandler.d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.OData.Batch.DefaultODataBatchHandler.d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Batch.HttpBatchHandler.d__0.MoveNext()","ErrorCode":"0x0"}

**Comment by Tratcher** [comment]
Ah, found it:
https://github.com/OData/odata.net/blob/3d9811a453fe2d2aad3fa84e499a8c30e2c34c48/src/Microsoft.OData.Core/MultipartMixed/ODataMultipartMixedBatchReader.cs#L277-L280

**Comment by Tratcher** [comment]
There are two possible paths forward here.
1) The [OData](https://github.com/OData/odata.net/blob/3d9811a453fe2d2aad3fa84e499a8c30e2c34c48/src/Microsoft.OData.Core/MultipartMixed/ODataMultipartMixedBatchReader.cs#L277-L280) server library can remove the check I linked, there's no reason for it to restrict the request protocol version.
2) The [WebApi](https://github.com/aspnet/aspnetwebstack) client can downgrade the version to http/1.1 in batch requests.
Either of these requires product updates and re-deployments. Open an issue in both repos and see what they say.

One alternative: Do you have http/2 capable clients and servers you can use? Have you considered abandoning request batching in favor of http/2? You may actually improve performance through more parallelized processing.

**Comment by ankitbko** [comment]
@Tratcher Will open issues in both the repo. As for the alternative, I am calling Dynamics CRM batch api. Not sure if CRM supports http/2. Need to check with PG team.

**Comment by davidsh** [comment]
Since this issue is not within CoreFx and you're opening bugs in other repos, we'll close this issue. Thanks for helping investigate!
