### ISSUE TITLE
Allow [optional] passing of RegexOptions to RegularExpressionAttribute

### ISSUE THREAD

**Issue by eriksendc** [dotnet/corefx#31246]
When in regular c# code, there's a version of Regex.Match() that takes a RegexOptions parameter. It'd be super great to expose that when using data annotations.

I'm using data annotations to validate the input to my asp.net core web api. To give good error messages and to use data annotations, I have to use the following to allow some set of inputs in different casings:

    [RegularExpression(@"^(C|c|CAT|Cat|cat|CATS|Cats|cats|D|d|DOG|Dog|dog|DOGS|Dogs|dogs)$", ErrorMessage = "PetType is invalid (must be 'c', 'cat', 'cats', 'd', 'dog', 'dogs' or null).")]
    public string PetType { get; set; }

I want to support 'c', 'cat', 'cats', 'd', 'dog' and 'dogs' in a case insensitive way. I'd rather use this:

    [RegularExpression(@"^(c|cat|cats|d|dog|dogs)$", RegexOptions = RegexOptions.IgnoreCase, ErrorMessage = "PetType is invalid (must be 'c', 'cat', 'cats', 'd', 'dog', 'dogs' or null).")]
    public string PetType { get; set; }

I'm assuming that behind the scenes Regex.Match() is used within RegularExpressionAttribute.

**Comment by ajcvickers** [comment]
This is not something that we plan to implement. However, we would consider a well-written community PR to allow this. Keep in mind that any changes here must be 100% non-breaking to existing code.
