### ISSUE TITLE
Edit and Continue debugger bug with async Task Main in VS 2017

### ISSUE THREAD

**Issue by Sharpiro** [dotnet/corefx#31241]
The debugger does not display values correctly after "Edit and Continue" when called directly within ```async Task Main```.  This is just for .net core apps.

Environment:
- VS 2017 15.7.5
- Framwork: netcoreapp2.1

project file:
    <Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp2.1</TargetFramework>
    </PropertyGroup>

    <PropertyGroup>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    </Project>

In each example there are 2 lines of code commented out.  While executing a particular snippet, debug up to ```var x = 5``` and then uncomment the commented lines, save, and proceed to step over.  In the "Examples that fail", after editing and continuing and stepping over ```y```, it will appear as ```0```, and if you click the "evaluate now" button in the local or watch windows, you will receive the error, ```The debugger is unable to evaluate this expression```.  I included the ```Console.WriteLine``` to demonstrate that the value is still correctly printed to console, it's just not viewable while debugging.

Examples that work:

    //works
    static Task Main(string[] args)
    {
        var x = 5;
        //var y = 6;
        //Console.WriteLine(y);
        return Task.FromResult(0);
    }

    //works
    static async Task Main(string[] args)
    {
        await Task.Yield();
        Helper();

        void Helper()
        {
            var x = 5;
            //var y = 6;
            //Console.WriteLine(y);
        }
    }

Examples that fail:

    //fails
    static async Task Main(string[] args)
    {
        var x = 5;
        //var y = 6;
        //Console.WriteLine(y);
    }

    //fails
    static async Task Main(string[] args)
    {
        await Task.Yield();
        var x = 5;
        //var y = 6;
        //Console.WriteLine(y);
    }

**Comment by jkotas** [comment]
This is Visual Studio bug. Could you please report this via "Send Feedback" / "Report a Problem" in Visual Studio? It is the icon at the top of the Window:

![image](https://user-images.githubusercontent.com/6668460/43038380-d2f7ab32-8ccc-11e8-9363-27bd3df2b591.png)

**Comment by danmosemsft** [comment]
Closing as VS bug.
