### ISSUE TITLE
MetadataReader should provide a way to get Runtime Version of an assembly.

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#3125]
This was a comment on an old [MSBuild PR](https://github.com/Microsoft/msbuild/pull/43#issuecomment-88251329).  We also need to solve the same problem in the buildtools and have duped the managed reader into buildtools.  It would be nice to expose this instead in the metadata reader and move MSBuild and BuildTools to just consume the new API from BuildTools.

**Comment by nguerrera** [comment]
I believe MetadataReader.MetadataVersion already has what you want:

``` C#
internal static string GetRuntimeVersion(string path) 
{
    using (var stream = File.OpenRead(path))
    using (var peReader = new PEReader(stream))
    {
        return peReader.GetMetadataReader().MetadataVersion;
    }
}
```

**Comment by ellismg** [comment]
Thanks!
