### ISSUE TITLE
System.ValueTuple 4.5.0 nuget package dependency in .NETStandard 1.x leads to runtime failure on .NET Core 2.0

### ISSUE THREAD

**Issue by AArnott** [dotnet/corefx#31257]
When a .NETStandard 1.x library compiles with a nuget package dependency on System.ValueTuple, then runs in a .NET Core 2.0 process, it fails to find the System.ValueTuple type at runtime. It *does* however work on .NET Core 1.1 and .NET Core 2.1, as well as .NET 4.6.1.

See minimized repro project:
[ValueTupleConsumer.zip](https://github.com/dotnet/coreclr/files/2217040/ValueTupleConsumer.zip)

When using `dotnet run` on the test project, we see it succeeds everywhere except .NET Core 2.0.

Note that if I make the class library compile against .NETStandard2.0, then .NET Core 2.0 starts working. So the failure seems to be the combination of a .NETStandard1.x library running on .NET Core 2.0.

**Actual output**

```
dotnet test C:\Users\andarno\source\repos\ValueTupleConsumer\XUnitTestProject1\XUnitTestProject1.cs
proj
Build started, please wait...
C:\Program Files\dotnet\sdk\2.1.300\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3277: Found conflicts between different versions of "System.ValueTuple" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\Users\andarno\source\repos\ValueTupleConsumer\XUnitTestProject1\XUnitTestProject1.csproj]
Build completed.

Test run for C:\Users\andarno\source\repos\ValueTupleConsumer\XUnitTestProject1\bin\Debug\net461\XUnitTestProject1.dll(.NETFramework,Version=v4.6.1)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 3.0534 Seconds
Test run for C:\Users\andarno\source\repos\ValueTupleConsumer\XUnitTestProject1\bin\Debug\netcoreapp1.0\XUnitTestProject1.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.9087 Seconds
Test run for C:\Users\andarno\source\repos\ValueTupleConsumer\XUnitTestProject1\bin\Debug\netcoreapp2.0\XUnitTestProject1.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.5580471]     XUnitTestProject1.UnitTest1.Test1 [FAIL]
Failed   XUnitTestProject1.UnitTest1.Test1
Error Message:
 System.IO.FileNotFoundException : Could not load file or assembly 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
Stack Trace:
   at ValueTupleConsumer.Class1.TupleUser(Tuple`2 state)
   at XUnitTestProject1.UnitTest1.Test1() in C:\Users\andarno\source\repos\ValueTupleConsumer\XUnitTestProject1\UnitTest1.cs:line 12

Total tests: 1. Passed: 0. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 1.3449 Seconds
Test run for C:\Users\andarno\source\repos\ValueTupleConsumer\XUnitTestProject1\bin\Debug\netcoreapp2.1\XUnitTestProject1.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.2197 Seconds
```

The build warning about System.ValueTuple is of course interesting. From the detailed log:

```
   1:4>ResolveAssemblyReferences:
             Required by "C:\Users\andarno\source\repos\ValueTupleConsumer\ValueTupleConsumer\bin\Debug\netstandard1.6\ValueTupleConsumer.dll".
         There was a conflict between "System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" and "System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51".
             "System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" was chosen because it was primary and "System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" was not.
             References which depend on "System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" [C:\Users\andarno\.nuget\packages\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.ValueTuple.dll].
                 C:\Users\andarno\.nuget\packages\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.ValueTuple.dll
```

This warning doesn't seem to be due to anything I can control. As you can see from my very minimal repro, I haven't added any project references or other package references that could be introducing this conflict. The fact that it chose 4.0.2.0 instead of 4.0.3.0 (without a binding redirect, I suppose) is probably part of the problem.

**Comment by bartonjs** [comment]
Since .NET Core 2.1 works, and .NET Core 2.0 is no longer in support, there doesn't seem to be any work remaining here.

**Comment by StingyJack** [comment]
@bartonjs - I get the same MSB3277  error as the OP from .net framework apps when some packages combinations are included, and have been for about a year or so (spanning different employers, LOB, project types, netfx versions; 4.5, 4.6, 4.7, and both nuget consuming styles). 

While it can be other assemblies that cause this, it seems more often than not that its this System.ValueTuple. Something in the package itself or its usages within MSFT packages causes it to emit this message. Using assembly binding redirects doesnt seem to fix it, but sometimes if I can remove all netstandard2.0 targeted references (like changing System.Collections.Immutable from 1.4 to 1.3) it will go away.

It doesn't seem to affect the runtime execution of programs (except a pair of ASP.net web app projects), but It would be great if netfx was considered in statements like ...

> Since .NET Core 2.1 works, and .NET Core 2.0 is no longer in support, there doesn't seem to be any work remaining here.

And not as the item so old its no longer part of the discussion.
