### ISSUE TITLE
System.Cryptography is missing a way of checking byte[] equality in constant time 

### ISSUE THREAD

**Issue by EthanHeilman** [dotnet/corefx#31270]
System.Cryptography provides HMAC algorithms but does not provide a secure way to evaluate the correctness of HMACs. 

HMACs are used to authenticate messages between two parties Alice and Bob which have a shared key `k`.
1. Alice creates a message `m` and generates an HMAC tag `t = HMAC(m, k)`
2. Alice sends `(m,t)` to Bob
3. Bob checks that the message is really from Alice by generating a new tag `t' = HMAC(m, k)` and checking if `t' == t`.

Checking if `t' == t` is hard to do securely. It requires that the comparison is constant time or else the implementation may be vulnerable to a timing channel. For a longer discussion of this issue read [A Lesson In Timing Attacks \(or, Don’t use MessageDigest.isEquals\)]( https://codahale.com/a-lesson-in-timing-attacks/) or https://github.com/nodejs/node-v0.x-archive/issues/8560. Writing a constant time equality check is hard because compiler and language designers often add performance improvements that make code which looks constant time code not actually constant time.

In the example documents for System.Cryptography they do provide example code for to do this:
``` C#
byte[] computedHash = hmac.ComputeHash(inStream);
// compare the computed hash with the stored value

for (int i = 0; i < storedHash.Length; i++)
{
    if (computedHash[i] != storedHash[i])
   {
       err = true;
   }
}
``` 
[HMACSHA512 Class -- Examples](https://msdn.microsoft.com/en-us/library/system.security.cryptography.hmacsha512(v=vs.110).aspx)

Compare this code with how constant time equality is implemented in the asp.net password system:

``` C#
// Compares two byte arrays for equality. The method is specifically written so that the loop is not optimized.
[MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.NoOptimization)]
private static bool ByteArraysEqual(byte[] a, byte[] b)
{
    if (a == null && b == null)
    {
        return true;
    }
    if (a == null || b == null || a.Length != b.Length)
    {
        return false;
    }
    var areSame = true;
    for (var i = 0; i < a.Length; i++)
    {
        areSame &= (a[i] == b[i]);
    }
    return areSame;
}
``` 
[aspnet/Identity/src/Core/PasswordHasher.cs](https://github.com/aspnet/Identity/blob/master/src/Core/PasswordHasher.cs#L69)

Providing HMAC algorithms without a well vetted constant time equality check is likely to lead to users implementing HMAC authentication insecurely. System.Cryptography should add a function for doing constant time equality checking.

Thanks for @blowdart for suggesting I create this issue and pointing me toward the asp.net equality check.

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/pull/27103

**Comment by EthanHeilman** [comment]
Update the HMAC example to use this to help users find FixedTimeEquals

**Comment by terrajobst** [comment]
@EthanHeilman 

> System.Cryptography should add a function for doing constant time equality checking.

Given that `CryptographicOperations.FixedTimeEquals()` exists, what is missing?

**Comment by EthanHeilman** [comment]
>Given that CryptographicOperations.FixedTimeEquals() exists, what is missing? IOW, can this be closed?

Update the documentation so that it can be found easily. Ensure it shows up in the relevant documentation. FixedTimeEquals is not easy to find. It requires knowing the name and searching for it. This is complicated by the fact that nearly every other library refers to this as a constant time equals. The system.cryptography HMAC examples don't use it suggesting that the person writing the documentation wasn't aware of its existence.

**Comment by danmosemsft** [comment]
Discussion of why it's not ConstantTimeEquals [here](https://github.com/dotnet/corefx/issues/10749#issuecomment-359615078) 

@EthanHeilman perhaps you could open an issue or PR against https://github.com/dotnet/docs so appropriate topics can point to it?

**Comment by EthanHeilman** [comment]
Thanks for your help. I'm going to close this issue and then later this week I'll open an issue on https://github.com/dotnet/docs
