### ISSUE TITLE
Async suffix

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#31275]
Migrated from original issue https://github.com/dotnet/core/issues/1464

_**@lukepuplett commented on Apr 19**_

# Should the Async suffix convention be used in 2018?

I'm so sorry for bringing this up, its not an issue as such, its debatable, but this might be the best forum for it. 

Should .NET and other open-source libraries continue to append `Async` on awaitables?

# General

My team here have begun to drop it; I always wondered whether this might happen but thought it premature until I read this.

https://docs.particular.net/nservicebus/upgrades/5to6/async-suffix

What do we feel is appropriate guidance in 2018?

Thanks

_**@deerchao commented on May 29**_
Never used the Async suffix in my code.

_**@MarcoTheFirst commented 11 days ago**_
I totally agree. There are enough indications that a method is async:

1. Return type is Task / Task<>
2. Code completion presents an awaitable hint 
3. the IDE will warn you by underlining in green 
4. Compiler will present a warning when task is not awaited. 

Using the Async suffix only makes sense if your API offers the same functionality in both flavors:

```
GetObject()
GetObjectAsync()
```

For any other use case, using the Async-suffix is as silly as adding a Lazy-suffix to any Lazy<> property:

`public Lazy<Customer> CustomerLazy.`

If you wouldn't do that, then don't use the Async suffix :-)

_**@lukepuplett commented 6 days ago**_
Thanks for your answer.

For accuracy, number one isn't quite right, the compiler works by looking for an awaitable type, which is any type that has `TaskAwaiter GetAwaiter()` on it.

**Comment by NickCraver** [comment]
Let's say you are reviewing a PR. Let's say they add this like of code:
```c#
var result = GetResult();
```
Is it sync or async? Did someone forget to `await` the result? What's the return type? None of these things are apparent. Now let's compare:
```c#
var result = GetResultAsync();
```
...that's obvious. And it cost you *nothing* to make it obvious. No suffix *may* have no issues in specific scenarios where you know a lot. Having a suffix *always* has no issues. It's only a positive.

As someone who reviews code *a lot*, people can pry the suffix out of my cold, dead fingers. And they better hope rigor mortis hasn't set in when they try.

**Comment by vcsjones** [comment]
>Should .NET and other open-source libraries continue to append Async on awaitables?

Yes.

I look forward to this question being asked again in 2019.

**Comment by daveaglick** [comment]
Async has such profound implications to control flow, performance, etc. that an extra visual cue at the call site is both warranted and appreciated, IMO

**Comment by khalidabuhakmeh** [comment]
Regardless of the "right" choice, wouldn't this be a Godzilla-sized breaking change? Maybe if we bumped the version of .NET Core to `11` then it may be ok... but still.

**Comment by daveaglick** [comment]
> Maybe if we bumped the version of .NET Core to 11 then it may be ok

Nah, that won’t work. I’m pretty sure .NET Core 11 comes right after .NET Core 2 in the latest revised versioning scheme.

**Comment by SimonCropp** [comment]
@NickCraver isnt `var result = GetResult();` a misleading representation? wouldn't it usually be `var result = await GetResult();` and hence "this is async" is obvious without the `Async` Suffix?

**Comment by MarkusAmshove** [comment]
@SimonCropp that is exactly the point :-)

You're seeing `var result = GetResult();` while reviewing code (without an IDE) and you can't be sure if it is async (missing `await`) or if it is not async.

`var result = GetResult();` is legal code, where `result` would be of type `Task` when not `await`ed.

If it was `var result = GetResultAsync()` it would be a good hint for the reviewer that something is wrong.

**Comment by SimonCropp** [comment]
@MarkOsborneMS my point is `GetResult` implies there is some result to be used. so it would not be a simple `Task`. it would be a `Task<T>` and to use that result then it needs to be awaited and hence wont compile without the `await`.

if `GetResult();` only returns a `Task`, and you do want to force it to be awaited when it has no return value, then that would mean `var result = GetResult();` (missing an await) has no use of `result`, which could easily be caught by treating un-used variables as an error.

**Comment by benaadams** [comment]
> So this example is not specific to Async. What if the return type were Lazy<>, would you expect the method to be called GetResultLazy? If it were an int, would you call it GetResultInt ?

It is because neither Lazy nor Int change the flow control; its fine to ignore the result of awaiting a `Task<T>` for example; but accidentally not `await`ing it leads to entirely different problems and introduces concurrency and race conditions.

**Comment by MarcoTheFirst** [comment]
@benaadams not awaiting a task will return the Task itself instead of the result type. therefore it is impossible to accidentally confuse the two. Your strongly typed code simply won‘t build, so I still disagree with the Async suffix. And since a suffix is just sugar coating anyway it‘s not reliable. Programmers make mistakes, compilers usually dont‘t.

**Comment by NickCraver** [comment]
> Your strongly typed code simply won‘t build, so I still disagree with the Async suffix.

This is simply false. Let's take my original example and put it in a simple program:
```c#
void Main()
{
	var result = GetResult();
}

async Task<int> GetResult()
{
	await Task.Delay(4000);
	return 5;
}
```

This compiles just fine. And it exits immediately, terminating whatever task was in progress. It'd be a shame if that was updating a bank balance or something...

**Comment by MarkusAmshove** [comment]
What @MarcoTheFirst means (I think) is the following case:

```cs
void Method()
{
    var result = GetResult();
    int x = result + 10; // Compile error, Task<int> + int doesn't work
}
```


However, I find the other way around more dangerous:

```
db.SaveCustomer(c);
db.SaveOrder(o);
….
```

**Comment by Clockwork-Muse** [comment]
@MarkusAmshove - yeah, but ignoring a return value is (almost always) a programmer error, and the compiler should be squawking at you for that.

**Comment by MarkusAmshove** [comment]
Then the Roslyn team needs to do something, because this doesn't yield an error or warning:

```cs
static void Main(string[] {
            Save();
        }

        public static Task Save()
        {
            return Task.CompletedTask;
        }
```

**Comment by Clockwork-Muse** [comment]
....I know it doesn't _now_, but in my opinion it should.

**Comment by satjinder** [comment]
Not sure if it would result in other kinds of problems or confusions, but I think the life could have been easier if await is by default for async methods and you could choose something like "getTask DoSomething()". 

i.e. Explicit opt-out of await with default opt-in.

**Comment by stephentoub** [comment]
I don't believe there's any further action item required on this issue.  Given the lack of discussion on the naming issue for several months, I'm going to close this out.  Thanks for the good discussion.

**Comment by crgarcia12** [comment]
> Let's say you are reviewing a PR. Let's say they add this line of code:
> 
> ```cs
> var result = GetResult();
> ```
> 
> Is it sync or async? Did someone forget to `await` the result? What's the return type? None of these things are apparent. Now let's compare:
> 
> ```cs
> var result = GetResultAsync();
> ```
> 
> ...that's obvious. And it cost you _nothing_ to make it obvious. No suffix _may_ have no issues in specific scenarios where you know a lot. Having a suffix _always_ has no issues. It's only a positive.
> 
> As someone who reviews code _a lot_, people can pry the `Async` suffix out of my cold, dead fingers. And they better hope rigor mortis hasn't set in when they try.

Your problem is that you are using var where you should not:

var something = GetSomething() //How can you review this PR? What is it returning?
Something something = GetSomething(); // would not build if you are missing await
