### ISSUE TITLE
Generating facades error - Registry typeforward already exists

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#31282]
I hit this error already twice today (with some local work in the branch). Does that sound familar / ring any bells?

```
C:\git\corefx\Tools\partialfacades.task.targets(64,5): warning : Microsoft.Win32.Registry typeforward already exists [C:\git\corefx\src\shims\manual\mscorlib.csproj]
C:\git\corefx\Tools\partialfacades.task.targets(64,5): error : Errors were encountered when generating facade(s). [C:\git\corefx\src\shims\manual\mscorlib.csproj]
```

cc @weshaggard @ericstj

**Comment by weshaggard** [comment]
That seems like a potential issue with a dirty build. I suspect for some reason we are trying to regenerate the facade on top of the already existing facade.

**Comment by ViktorHofer** [comment]
Manually rebuilding the facade should also work, shouldn't it?

`msbuild /t:Rebuild src/shims/manual/mscorlib.csproj`. That also errors for me.

**Comment by weshaggard** [comment]
Manually building the facade should work assuming you have built from the root once. When you do the rebuild does it clean up the old facade and intermediate path? Take a look at the inputs into GenFacades from a log file and see if the binary that is the input already has type-forwards and if it does see if that binary is correctly getting cleaned up when you do the rebuild.

**Comment by ViktorHofer** [comment]
Thanks I'll give it a try when hitting this again.

**Comment by ViktorHofer** [comment]
> Take a look at the inputs into GenFacades from a log file and see if the binary that is the input already has type-forwards and if it does see if that binary is correctly getting cleaned up when you do the rebuild.

I'm now hitting this again... The input binary has the manual typeforwards and when doing a rebuild it gets cleaned up correctly...

**Comment by ViktorHofer** [comment]
Found the issue. In the manual csproj we have a wildcard referencepath which picks up nearly every assembly:

```
    <ReferencePath Include="$(_RuntimePath)System.*.dll;$(_RuntimePath)Microsoft.*.dll" Exclude="$(_RuntimePath)Microsoft.Diagnostics.Tracing.TraceEvent.dll;$(_RuntimePath)Microsoft.DiaSymReader.Native.*.dll" />
```

I added some assemblies which automatically got probed and caused the error. I excluded them now. Maybe we can avoid relying on the wildcard inclusion.

**Comment by ericstj** [comment]
Or be more careful about which paths we're using for this.  If we had a path that can only contain assemblies which are part of the product + packages it might also be sufficient.

How did those non-product assemblies get in our RuntimePath?

**Comment by ViktorHofer** [comment]
Currently we binplace some of the testframework and dependent assemblies into the runtime path. i.e. xunit, xunit-performance (+ MarkdownLog as a dependency). As I added additional dlls from the Microsoft.NET.Test.SDK some were causing conflicts. It seems Wes faced the same issue before as he manually excluded a few assemblies.

**Comment by ericstj** [comment]
Seems like those assemblies belong in the test shared framework path, but not runtime path.  Despite its name, RuntimePath isn't used for running anything AFAIK.

**Comment by weshaggard** [comment]
See https://github.com/dotnet/corefx/issues/21103 which is the issue I filed about the runtime path wildcards. We have never gotten around to trying to clean it up but it is definitely a known source of potential issues.
