### ISSUE TITLE
Microsoft.CSharp fails to build when running MSBuild on Mono

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#3128]
When using build.sh on Linux Microsoft.CSharp runs into some build issues.  I am going to disable it for now and follow up with this issue.

**Comment by akoeplinger** [comment]
I took a quick look at this. The error is:

```
"/home/alexander/dev/corefx/src/Microsoft.CSharp/src/Microsoft.CSharp.csproj" (BuildAndTest target) (3) ->
(GenerateSatelliteAssemblies target) -> 
  /home/alexander/dev/corefx/packages/Microsoft.Build.Mono.Debug.14.1.0.0-prerelease/lib/Microsoft.Common.CurrentVersion.targets(3241,5): error MSB3086: Task could not find "al" using the SdkToolsPath ""
or the registry key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.6\WinSDK-NetFx40Tools-x86". Make sure the SdkToolsPath is set and the tool exists in the correct processor
specific location under the SdkToolsPath and that the Microsoft Windows SDK is installed [/home/alexander/dev/corefx/src/Microsoft.CSharp/src/Microsoft.CSharp.csproj]
```

It's trying to build satellite assemblies for localized resources which were added in https://github.com/dotnet/corefx/pull/2713. Somehow the check for the Multilingual App Toolkit doesn't work.

**Comment by weshaggard** [comment]
cc @naamunds

**Comment by akoeplinger** [comment]
I found the root cause, the MAT check isn't involved at all. It fails because it can't find `al` for generating the satellite assemblies.

Adding `/p:AlToolPath=/usr/bin` (that is where the `al` script from my Mono is installed) allowed the build to succeed and produced correct satellite assemblies.

**Comment by ellismg** [comment]
Thanks @akoeplinger, I can update build.sh to therad this along.  While I am in the area, do you have an opinion on how __monoroot is getting set in build.sh?  It feels wrong to me that we pick whatever mono is in the path but use a different __monoroot to find the portable assemblies.  For example, on my machine, I built mono from source and installed it to /opt/mono and have /opt/mono/bin ahead in my PATH.  Do you think it makes more sense to just assume mono is on the path and calculate the path to lib based on that?

Later on we assume it's on the path anyway, it seems, to actually invoke it.

**Comment by akoeplinger** [comment]
> It feels wrong to me that we pick whatever mono is in the path but use a different __monoroot to find the portable assemblies. [...] Do you think it makes more sense to just assume mono is on the path and calculate the path to lib based on that?

It could use a better name than `__monoroot` but we need to look at the Mono installed by the package manager as only that one will have the PCL reference assemblies (they are part of the Mono package from the Xamarin repositories). The one in /opt that you compiled from source doesn't have them in lib unless you manually copied them there. Using `mono` from PATH is preferred so you can easily test with a newer version without too much hassle (the PCL assemblies don't change that often).

**Comment by akoeplinger** [comment]
Another option would be that you ship the PCL assemblies in a NuGet package and pull it down as usual.

**Comment by janhenke** [comment]
Please keep in mind not everybody puts everything into ```/usr/bin```. Mono on FreeBSD in installed in ```/usr/local/```, so it should be relative to the mono root.

**Comment by ellismg** [comment]
@janhenke I plan to just plan to point it at whatever folder `which mono` tells me mono is in.  I suspect that will do what you want.

**Comment by janhenke** [comment]
Should work. I just want to avoid extra work like the one where the path to ```bash``` was hard coded in every shell script.

**Comment by akoeplinger** [comment]
@ellismg that doesn't work in cases where the Mono in PATH doesn't have the PCL assemblies (which is common for self-compiled or snapshot package Mono), that's what I meant above.

**Comment by ellismg** [comment]
@akoeplinger Yeah, sorry for being unclear.  I understand your point.  I plan to keep the __monoroot as is (the package manager mono which will have the PCLs) and use the path'd mono for pointing to AL.

**Comment by akoeplinger** [comment]
@ellismg ok, sounds good :) to be clear: setting AlToolPath should be a short-term workaround, the underlying issue should really be fixed in xplat MSBuild.

**Comment by ellismg** [comment]
@akoeplinger I agree.

**Comment by ellismg** [comment]
This has been fixed as part of the move to MSBuild on .NET Core.
