### ISSUE TITLE
HTTP2: Support connection lifetime and timeout

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#31294]
SocketsHttpHandler has two properties for controlling connection lifetime:
* PooledConnectionLifetime
* PooledConnectionIdleTimeout

We need to support these (or something similar) for HTTP2 connections.

Issues to consider:

* Should these settings apply to HTTP2 connections also, or should we have new HTTP2-specific settings? The names aren't great (HTTP2 connections aren't really "pooled", there's just one per destination server). Also, it's not clear that the same tradeoffs apply to HTTP2 connections as HTTP1.1. There's a bit more overhead in connection establishment for HTTP2, so we may not want to idle these out quite as aggressively as we do for HTTP/1.1. Lifetime is probably equally applicable though (since the point of this is to manage DNS change propagation delays).

* What does it mean for the HTTP2 connection to be "idle"? Presumably this means that there are no outstanding incomplete streams. We will need to track idle time on the HTTP2 connection.

* There's some existing code to implement all this for HTTP/1.1. Unfortunately I'm not sure how applicable this code is to HTTP2. It would be nice to share code here when possible, but may not be worth it.

**Comment by karelz** [comment]
@wfurt is there anything still left here?

**Comment by wfurt** [comment]
finishing and merging PR :)

**Comment by wfurt** [comment]
actually, I think #35266 should cover remaining wokr.
