### ISSUE TITLE
System.Numerics.Vectors Fails to Load W/ .NET 4.6 Preview Installed

### ISSUE THREAD

**Issue by sakkaku** [dotnet/corefx#313]
An unhandled exception of type 'System.IO.FileLoadException' occurred in Unknown Module.
    
    Additional information: Could not load file or assembly 'System.Numerics.Vectors, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Steps to Reproduce.

- Create a console application.
- Add the nuget package for System.Numerics.Vector to the project (I tried 1.1.5-beta and 1.1.6-beta).
- Add some dependent code (I used  `Console.WriteLine("Hardware Accelerated Vectors: {0}", Vector.IsHardwareAccelerated);`)
- Run the project.
- Get above exception.

It looks like somehow VS is getting the version number pinned at 4.0.0 and rejects the load.

Specific version is disabled, the DLL is being copied as expected and no relevant entries appear to be in the app.config.

**Comment by JamesVaughan** [comment]
I am also getting this issue after installing the .Net 4.6 preview.

**Comment by sakkaku** [comment]
I am updating the title to better describe the probable issue.

**Comment by mellinoe** [comment]
Thanks for updating the issue, and sorry for the delay, I am now taking a look at this. Currently it looks like we are going to need to put out an updated NuGet package to fix this issue.

**Comment by ellismg** [comment]
@mellinoe Do you know if this got addressed?

**Comment by jcotton42** [comment]
Still having this issue, VS 2015 CTP 6

**Comment by jcotton42** [comment]
It looks like the nuget assembly is being forwarded to the one that ships w/ the framework, which lacks many members and types

**Comment by FrankNiemeyer** [comment]
@jcotton42 If VS 2015 RC is installed, it seems to always use the System.Numerics.Vectors.dll from the GAC, which is the one shipping with .NET 4.6 and which is different from v4.0.0 from NuGet (e.g. fewer static methods, for instance Dot and Cross are missing). You can see that when looking at the loaded modules when running the debugger.

**Comment by benaadams** [comment]
Can you bump the nuget one to version 4.0.0.1?

**Comment by benaadams** [comment]
You can do a forced overwrite of the one in the GAC:

```gacutil /i ...path\System.Numerics.Vectors.dll /f```

But you need ```gacutil``` on target machine :(

**Comment by mellinoe** [comment]
This should no longer be an issue, please re-open if you encounter any lingering problems with old installations on your machine.
