### ISSUE TITLE
HTTP2: Implement CookieContainer support

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#31306]
We need to support sending outbound cookies from the CookieContainer, and receiving inbound cookies and putting them into CookieContainer.

We do this for HTTP/1.1 in HttpConnection.WriteHeadersAsync. We need to do something similar for HTTP2.

Note there are some special HTTP2 rules for the Cookie header; see the RFC.

**Comment by caesar1995** [comment]
According to [RFC 7540 (HTTP/2):](https://tools.ietf.org/html/rfc7540#section-8.1.2.5)

> 8.1.2.5.  Compressing the Cookie Header Field
   To allow for better compression efficiency, the Cookie header field
   **MAY** be split into separate header fields, each with one or more
   cookie-pairs.  If there are multiple Cookie header fields after
   decompression, these **MUST** be concatenated into a single octet string
   using the two-octet delimiter of 0x3B, 0x20 (the ASCII string "; ")
   before being passed into a non-HTTP/2 context, such as an HTTP/1.1
   connection, or a generic HTTP server application.

My understanding towards this spec is that:

1. Client side: when receiving multiple `Set-Cookie` headers **may** send multiple cookie headers, or may concatenate them.
2. Server side: when receiving multiple cookie headers _**must**_ concatenate them before invoking an application.

I have tested that for WinHttpHandler with HTTP/2 connection, it will concatenate all cookies (same for HTTP/1.1 connection):
```
"Cookie": "name=value; name1=value1; name2=value2; ARRAffinity=f544664f16d1d8f1a5e0a9c38b639a613ad28da58ef9276f153cf5012707f85c",
```

Therefore, I think for SocketsHttpHandler, we could do the same. We can directly use the CookieContainer for without modifying it.

Any thoughts? @dotnet/ncl
