### ISSUE TITLE
HTTP2: Use HPACK static table for sending well-known headers

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#31307]
We're currently sending these without compression. 

We should use the static table for both pseudo-headers (":scheme", ":authority", etc) as well as well-known headers (Accept-Encoding, etc).

Note this is strictly a performance issue, not a correctness issue. But at least for the pseudo-headers, it's pretty lame to not do this since it should be easy and worthwhile.

**Comment by geoffkizer** [comment]
Also: for known headers that aren't in the HPACK static table, we can still precompute the Huffman-encoded bits for the header name so we don't have to generate these on the fly.

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/corefx/pull/35324
