### ISSUE TITLE
HTTP2: Support downgrade to HTTP/1.1 for NT auth

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#31304]
NT auth does not work over HTTP2. So when NT auth is used, we need to downgrade to HTTP/1.1.

I believe we will need to do something like the following:

When we receive a 401 with an NTLM or Negotiate challenge from the server, and we're using HTTP2, we will need to instead switch to using an HTTP/1.1 connection (either an existing connection from the pool, or a new connection). We will then proceed with the regular challenge/response protocol on this new connection as usual.

**Comment by davidsh** [comment]
An early RFC draft of dealing with NT auth and HTTP/2.0:

https://tools.ietf.org/id/draft-montenegro-httpbis-multilegged-auth-01.html

**Comment by karelz** [comment]
Duplicate of #35195
