### ISSUE TITLE
HTTP2: Support Huffman encoding for sending headers

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#31308]
HPACK defines a fixed Huffman encoding for header strings. We should consider implementing this and using it. It's a lesser priority than using the static table, however (#31307).

**Comment by Tratcher** [comment]
Yes, this should be a straight forward perf item. This will also be shared with Kestrel (not implemented there yet either?).

**Comment by scalablecory** [comment]
Prototype indicates this has a negative perf impact and the benefit is not clear. I'll keep my code around for future reference, but am closing this issue for now -- we can revisit if we find a clear benefit later.
