### ISSUE TITLE
HTTP2: Should we pool Http2Stream objects?

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#31301]
We allocate a new Http2Stream for every request on an HTTP2 connection. Is this impactful? Would it help to pool these?

**Comment by wfurt** [comment]
Would there be any reason not to do this @geoffkizer ?
Is there specific test we should run? It seems like it may be hard to know the impact without implementing at least part of it. Thoughts? 


It seems like this has two parts: 
We would need to modify Http2Stream so object could be purified to initial clean state and change readonly properties. It seems like Http2Stream also allocates so we could save more than just Http2Stream allocation it self.

Second part would be adding pooling logic to Http2Connection, HttpPool or some other object. 
If we allow changing _connection I see no reason why pooling would not work across different connections.

**Comment by stephentoub** [comment]
I actually implemented this yesterday. What I'm still missing is just figuring out where/when it's safe to actually reuse the Http2Stream.
