### ISSUE TITLE
HTTP2: Disallow sending Connection: header and Transfer-Encoding: chunked

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#31305]
These headers are explicitly not supported in HTTP2. We should detect them and fail the request.

Note, we are currently adding Transfer-Encoding: chunked to the request when it doesn't have a Content-Length. We do this in SocketsHttpHandler.ValidateAndNormalizeRequest, which is called on every request. We should probably move this logic into HttpConnection.SendAsyncCore so that it is HTTP/1.1 specific.

**Comment by davidsh** [comment]
>These headers are explicitly not supported in HTTP2. We should detect them and fail the request.

I'm not sure we should fail the request.  We might simply want to adjust/strip the headers automatically.

**Comment by geoffkizer** [comment]
> I'm not sure we should fail the request. We might simply want to adjust/strip the headers automatically.

Yes, that seems like a reasonable option.

(By the way, I should clarify: Transfer-Encoding is completely prohibited (not just Transfer-Encoding: chunked).

I think there's the specific cases of "Transfer-Encoding: chunked" and "Connection: close" to consider, as well as the more general case of other values for these headers.

"Transfer-Encoding: chunked" and "Connection: close" don't really make sense for HTTP2. But they also aren't very common for users to set. In the interest of usability, it seems reasonable to just discard them.

Other values are even less common, but also more complicated. Presumably if a user is going to the trouble of setting these, they have a good reason to. And since we can't support that in HTTP2, it seems like we should fail the request to indicate to them that they aren't going to get the behavior they explicitly specified.

That said, I think you could apply the same argument to "Transfer-Encoding: chunked" and "Connection: close". I'm not sure which I prefer.

**Comment by geoffkizer** [comment]
It would be interesting to see what other handlers do here.

**Comment by davidsh** [comment]
>"Transfer-Encoding: chunked"

Transfer-Encoding: chunked is pretty important in cases where the length of the request body can't be determined easily.  For streaming scenarios of request body (video etc.), Transfer-Encoding: chunked is used all the time.  Perhaps that means that a developer has to manually think about disabling HTTP/2 use.  Or perhaps we should automatically not propose HTTP/2 in cases where the developer has set 'Transfer-Encoding: chunked' explicitly.

**Comment by geoffkizer** [comment]
> Transfer-Encoding: chunked is pretty important 

Sure, but how common is it for a developer to set this explicitly? We will set it for them automatically if there's no Content-Length.

If we do think this is common, I think that's a good argument for just discarding it silently when doing HTTP2.

**Comment by geoffkizer** [comment]
This is fixed with recent changes
