### ISSUE TITLE
HTTP2: Review HPACK code for correctness and possible performance issues

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#31316]
This code came from ASP.NET, but has never been shipped. We should review the code in detail and determine if there are any potential correctness or performance issues.

**Comment by grant-d** [comment]
Related: https://github.com/dotnet/corefx/issues/31751

**Comment by karelz** [comment]
Next steps: Add tests to confirm correctness
Performance is not needed for 3.0
