### ISSUE TITLE
HTTP2: Determine how to expose HTTP2 protocol error codes

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#31315]
HTTP2 defines a list of protocol-level errors. Currently there is a Http2ProtocolErrorCode enum that defines these error codes, and Http2ProtocolException that exposes this enum. However, these aren't public currently; they get mapped into a generic HttpRequestException.

We need to determine if and how we want to expose these errors.

This is related to the broader question of how to expose more detailed error information about HTTP failures (is there an issue for this?).  We may want to be consistent across HTTP/1.1 and HTTP2 here.

**Comment by davidsh** [comment]
>This is related to the broader question of how to expose more detailed error information about HTTP failures (is there an issue for this?). We may want to be consistent across HTTP/1.1 and HTTP2 here.

We have several issues on this topic about adding more detailed, platform-independent, error information.  

#4148
#19185
#26477

In particular, the current thought I have is to extended the HttpRequestException with a property that is similar to [WebException.Status](https://docs.microsoft.com/en-us/dotnet/api/system.net.webexception.status?view=netcore-2.1) and an enum similar to [WebExceptionStatus](https://docs.microsoft.com/en-us/dotnet/api/system.net.webexceptionstatus?view=netcore-2.1)

**Comment by rmkerr** [comment]
I'm actually running into several test failures where the private Http2ProtocolException is thrown without being wrapped in an HttpRequestException.

For example, if I send a frame before the server connection preface:
```
Assert.Throws() Failure
        Expected: typeof(System.Net.Http.HttpRequestException)
        Actual:   typeof(System.Net.Http.Http2Connection+Http2ProtocolException): Http2 Protocol Error, errorCode = ProtocolError
        Stack Trace:
           C:\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs(96,0): at System.Net.Http.Http2Connection.SetupAsync()
           C:\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs(382,0): at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
           E:\A\_work\41\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\ValueTask.cs(849,0): at System.Threading.Tasks.ValueTask`1.get_Result()
           C:\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs(456,0): at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
           C:\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\RedirectHandler.cs(33,0): at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
           C:\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(475,0): at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
           C:\corefx\src\System.Net.Http\tests\FunctionalTests\SocketsHttpHandlerTest.Http2.cs(62,0): at System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Http2_Test.<>c__DisplayClass3_0.<<Http2_DataSentBeforeServerPreface_ProtocolError>b__0>d.MoveNext()
```

**Comment by geoffkizer** [comment]
Yeah, there seems to be a missing try/catch to wrap these. We should only be exposing HttpRequestException.

**Comment by karelz** [comment]
@stephentoub we could use help with this one - at least design proposal. Thanks!

**Comment by stephentoub** [comment]
@davidsh, re: https://github.com/dotnet/corefx/issues/31315#issuecomment-407454597, are we on track to do anything about the 1.1 exception error codes / enums for .NET Core 3.0, or is that post-3.0?

**Comment by davidsh** [comment]
>@davidsh, re: #31315 (comment), are we on track to do anything about the 1.1 exception error codes / enums for .NET Core 3.0, or is that post-3.0?

At this point, that larger issue is post-3.0.

I don't think we need to expose the internal Http2ProtocolException class publicly:
https://github.com/dotnet/corefx/blob/b176a73bdeb9bf3c79b63cee2f13da9a0e0759ab/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L1465-L#1466

But I think we need to make sure it is an inner exception all the time we throw HttpRequestException for example. We can also derive this exception from `Win32Exception` instead of `Exception`. That allows us to put in the integer Http2ProtocolError. We should also make sure that the .Message property of this exception is an informative string.

The key thing here is being able diagnose errors.  As long as the inner exception has good information that is sufficient. We don't need to make this exception type a public type.

**Comment by stephentoub** [comment]
> At this point, that larger set of issues is post-3.0.

Ok, then I'll refrain from making this public now, too, as I'd want the public surface area to all be designed thoughtfully together.  For now, I'll do something along the lines of what you suggest.
