### ISSUE TITLE
xUnit version used by CoreFX does not run all compiled tests

### ISSUE THREAD

**Issue by marek-safar** [dotnet/corefx#31319]
We found during our testing that not all CoreFX tests (hundreds in our case) are not executed and in fact, some of them fail with unexpected results.

The issue was fixed in recent xUnit versions, in particular, https://xunit.github.io/releases/2.3-beta4 which includes a fix for https://github.com/xunit/xunit/issues/1068.

In Mono we have updated the xUnit to 2.4 and we see more tests to be executed but also about 20 new failures for mscorlib alone (it could be more as we include the only subset of tests for now).

I opened also probing PR https://github.com/dotnet/corefx/pull/31318 which turned one of the ignored tests to constant failure to confirm it's undetected with current CoreFX setup.

**Comment by ViktorHofer** [comment]
Will be fixed with https://github.com/dotnet/corefx/issues/31319

**Comment by vcsjones** [comment]
I think @ViktorHofer meant #31260 :-).

**Comment by ViktorHofer** [comment]
Oh right, thanks 😁
