### ISSUE TITLE
Failing to parse HTTP proxy environmental variables sometimes after upgrade to 2.1 

### ISSUE THREAD

**Issue by wfurt** [dotnet/corefx#31326]
**Description**

When setting `http_proxy=http://1.2.3.4:3128/` we fail to parse it properly and entire proxy is ignored. 
With old Curl handler, trailing slash is ignored. Note that 2.1 code works correctly when set to `http_proxy=http://1.2.3.4:3128`.  

**Customer Impact**
Setting for HTTP proxy may stop working after upgrade to 2.1. There is mitigation by using proper form but it is not clear and needs investigation. 

**Regression**
Regression from 2.0

**Risk**
Low:
The change is small and safe and decreases our migration pain. 

Fixes in master for 3.0 in #31232

**Comment by vivmishra** [comment]
Approved for 2.1.4

**Comment by joshfree** [comment]
@wfurt can you please add the 2.1 PR to this issue and close it once you’ve merged the PR? Checkin needs to be completed before Tuesday to make 2.1.4

**Comment by wfurt** [comment]
#31327 @joshfree. marked as no-merge.

**Comment by joshfree** [comment]
@wfurt label updated.  2.1.4 checkins can happen now.

**Comment by wfurt** [comment]
#31327 merged.
