### ISSUE TITLE
X509Certificate2 error open pfx file without password on Mac OSX

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#31328]
Original issue https://github.com/dotnet/core/issues/1813

**_@ficnar commented 6 hours ago_** 

### X509Certicate2 error open pfx file without password on Mac OSX

Creating a X509Certificate2 instance from a byte array from pfx/p12 file that not secure by password, throw exception:

Interop+AppleCrypto+AppleCommonCryptoCryptographicException: MAC verification failed during PKCS12 import (wrong password?)
   at Interop.AppleCrypto.X509ImportCertificate(Byte[] bytes, X509ContentType contentType, SafePasswordHandle importPassword, SafeKeychainHandle keychain, Boolean exportable, SafeSecIdentityHandle& identityHandle)
   at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] data)

This problem occurs only on Mac OSX. On Windows and Linux work fine.
I try it on .NET Core 2.0.0.

**Comment by joshfree** [comment]
@bartonjs

**Comment by bartonjs** [comment]
@ficnar do you have an example PFX you can share?  (Preferably one without secrets in it, and also how you acquired it)

**Comment by baulig** [comment]
There is a difference between no password and the empty string.  I was actually looking at this quite recently when porting the OS X PAL to iOS and if I remember correctly then Apple is actually less strict about this than OpenSsl / BoringSsl.

Can you try using the `X509Certificate(byte[],string,X509KeyStorageFlags)` constructor and see whether passing `null` or `string.Empty` changes anything?  And which version of OS X is this?

As for a test, there should be a test in Mono _somewhere_, if you need one then I can have a look tomorrow.

On Linux, Mono's managed implementation actually tries both `null` and the empty string.

**Comment by ficnar** [comment]
Passing string.Empty or null value to password in constructor not work too.
I use OS X 10.13.
Test pfx I attaching.
[cert.pfx.zip](https://github.com/dotnet/corefx/files/2226957/cert.pfx.zip)

**Comment by filipnavara** [comment]
Duplicate of #24225

**Comment by bartonjs** [comment]
Closing as duplicate (#24225)
