### ISSUE TITLE
Make BaseIntermediateOutputPath project specific and remove overwrite of RestoreOutputPath

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#31323]
Using the same `BaseIntermediateOutputPath` has unfortunate side effects. We should make it project specific, i.e.

EDIT: updated
```
ConfigurationGroup = Debug | Release | ...
TargetGroup = netcoreapp | netfx | netstandard | ...
PlatformName = x86 | x64 | AnyCPU | ...
Configuration = $(TargetGroup)-$(ConfigurationGroup)
BaseIntermediateOutputPath = $(ArtifactsObjDir)$(MSBuildProjectName)/
IntermediateOutputPath = $(BaseIntermediateOutputPath)$(Configuration)/ OR $(BaseIntermediateOutputPath)$(PlatformName)/$(Configuration)/

Examples:

ArtifactsObjDir = bin/obj/
BaseIntermediateOutputPath = bin/obj/System.Runtime/
IntermediateOutputPath = bin/obj/System.Runtime/netcoreapp-Debug, bin/obj/System.Runtime/x64/netcoreapp-Release
```

We should also stop overwriting the `RestoreOutputPath`, I believe it defaults either to BaseIOP or IOP: https://github.com/dotnet/buildtools/blob/8bc74f90524b14ea0feb178dd5d5352503168aeb/src/Microsoft.DotNet.Build.Tasks/PackageFiles/packageresolve.targets#L10

This is related to my xunit work which requires the `TargetFrameworkIdentifier` which itself causes other targets to be loaded which require a unique `BaseIntermediateOutputPath`, i.e. for `project.assets.json`. Please let me know if the paths make sense and I will change it in my existing PRs. Of course also related repos like WCF need to be considered.

cc @eerhardt @weshaggard @ericstj

**Comment by eerhardt** [comment]
A thing you need to be careful about is that projects that aren't SDK-based `.csproj` projects, sometimes rely on `$(BaseIntermediateOutputPath)` being the common place (i.e. not project specific).

To solve this, I usually check if we are using the Microsoft.NET.Sdk before setting `BaseIntermediateOutputPath` to a project-specific location:

https://github.com/dotnet/machinelearning/blob/a307c6a7f20a7c6c0ec2a28ee55bb9775f6a8572/Directory.Build.props#L101-L108
https://github.com/dotnet/core-setup/blob/f62984e73ab6197b6414d36d1ca2b4d496cfd744/Directory.Build.props#L21-L28

100% agreed on `$(RestoreOutputPath)`, that needs to be fixed in buildtools. We shouldn't be setting that at all, and letting the official product tooling default it as usual.

**Comment by weshaggard** [comment]
I agree we are going to need to make some changes here. As part of the arcade work we will likely move to a new common pattern defined at https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/ProjectLayout.props, but I do expect we need to alter that to include our custom configuration.

**Comment by weshaggard** [comment]
@ViktorHofer is this only an issue in the depproj's? Or are you hitting the this base and restore path issue in our test projects?

**Comment by ViktorHofer** [comment]
Right, in my specific case it's about the test projects but as discussed offline this is also inconvenient when using `dotnet build` which then creates the intermediate files in the project path. I've already started with this in corefx and I believe it shouldn't be too much work. I prefer doing this now which probably enables VS Test Explorer integration even if we follow a different pattern with Arcade later.

> As part of the arcade work we will likely move to a new common pattern defined at 

Thanks for the link, that's very valuable. That would mean:

```
// bin/obj/$(MSBuildProjectName)/
<BaseIntermediateOutputPath Condition="'$(BaseIntermediateOutputPath)' == ''">$([System.IO.Path]::GetFullPath('$(ArtifactsObjDir)$(MSBuildProjectName)\'))</BaseIntermediateOutputPath>

// bin/obj/$(MSBuildProjectName)/$(TargetGroup)-$(Configuration)/
<IntermediateOutputPath Condition="'$(PlatformName)' == 'AnyCPU'">$(BaseIntermediateOutputPath)$(Configuration)\</IntermediateOutputPath>

// bin/obj/$(MSBuildProjectName)/$(OSGroup)/$(TargetGroup)-$(Configuration)/
<IntermediateOutputPath Condition="'$(PlatformName)' != 'AnyCPU'">$(BaseIntermediateOutputPath)$(PlatformName)\$(Configuration)\</IntermediateOutputPath>
```

@weshaggard let's discuss that offline please.

**Comment by ViktorHofer** [comment]
Added with https://github.com/dotnet/corefx/pull/31260
