### ISSUE TITLE
Investigate/Remove custom internal test frameworks

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#3133]
There are a number of projects with their own internal test frameworks, that need to be investigated, and potentially removed in favor of xunit.

To be clear, I'm not talking about projects with helper objects and methods (although some should be re-evaluated now that we're using xunit), I'm thinking of stuff like System.Xml.ReaderWriter.Tests (and its multiple constituent projects):

![image](https://cloud.githubusercontent.com/assets/5569508/9761804/e5ab2cb6-5739-11e5-8e2b-510d780c0e29.png)

...and if you'll notice, xunit isn't reporting the skipped tests, because it doesn't see them.  Are those important?  I really doubt reporting is turning those up.  And hopefully fails percolate....

Some of these frameworks are pretty heavily entrenched in their host projects, and dismantling them would be a large-scale effort.

The ones I'm aware of (can recall) at the moment are:
- System.Collections
- System.Threading.Tasks
- System.Xml.ReaderWriter

...although there are undoubtedly more.

**Comment by Clockwork-Muse** [comment]
At the moment, I'm going through System.Threading.Tasks as my fun project, as other people end up grabbing things.

**Comment by krwq** [comment]
I think it is ok to close this issue:
- currently many projects are converted to directly use Xunit
- projects which are not 100% Xunit use constructs which makes it quite a bit of work to convert them to directly use Xunit but they are currently "plugged in" to Xunit in such a way that Xunit understands custom Xml test framework (it shows which test case has failed and reports numbers of test cases correctly and not through batches of tests)
