### ISSUE TITLE
HTTP2: Consider supporting HTTP/2 for http:// endpoints

### ISSUE THREAD

**Issue by rmkerr** [dotnet/corefx#31338]
HTTP/2 is designed for use with SSL, but does provide a mechanism for upgrading from an insecure http:// endpoint.

This is an uncommon scenario that adds additional complexity to the upgrade process, and so should likely be added as an opt-in or skipped entirely.

cc: @geoffkizer

**Comment by wfurt** [comment]
This would be nice for following reasons: 
- may help greatly with debugging
- curl supports it so it may be regression
- this would allow offload ssl to different process. I also seen cases when HTTP is used for inter-process communication and then SSL only adds overhead.

**Comment by JamesNK** [comment]
Additional reasons:

* C-core gRPC client and server both support unencrypted HTTP/2. I will investigate how common not using encryption is with gRPC
* Kestrel server supports unencrypted HTTP/2. It is odd that the server stack supports a scenario that the client stack doesn't
