### ISSUE TITLE
MemoryExtensions ToUpper*/ToLower* ReadOnlySpan extensions return type

### ISSUE THREAD

**Issue by JarLob** [dotnet/corefx#31340]
For example https://github.com/dotnet/corefx/blob/5f3d22a7f335ae4c1dd57f9ac8b7460a13d57ee0/src/Common/src/CoreLib/System/MemoryExtensions.Fast.cs#L269-L288 return type is not documented.
```cs
            if (destination.Length < source.Length)
                return -1;
```
What does it mean? Just few lines above an exception is thrown if `culture` is `null`. Why returning -1 here if conversion cannot be completed instead of throwing an exception?

**Comment by Tornhoof** [comment]
Throwing exceptions is expensive and you need to handle the result anyway by e.g. adding it to an offset for ``destination``. You need to know that it failed or the offset. It's all about performance.
But your right the docs should be extended with a description of the return value.

**Comment by JarLob** [comment]
Sorry, I don't get it. Why would I need to check the return value?:
```cs
            Span<char> upperCaseLine = stackalloc char[line.Length];
            line.ToUpperInvariant (upperCaseLine);
```
All four functions **always** return `source.length` in case of success. Do you think it can be something different on other platforms?

Yes, exceptions are expensive, but this is error prone design, because callers will forget they **must** check the return value.

**Comment by Tornhoof** [comment]
No, I don't think it will return anything else, the type is char, even the turkish i/I thing will still fit into a char.
But knowing/assuming that ``source.Length`` is returned, is actually just an implementation detail.
As far as I understood all the Memory* classes are mainly for writing high-performance code, assuming the developers know what they are doing, in most cases they already know that the output buffer is long enough, so they can and will ignore the output, but let's take a look at the following code, which concatenates strings of unknown length in upper case (not saying this is an perfect example for using that API, but it should do for now):
```csharp
private static string Concatenate(string[] values)
{
    var output = ArrayPool<char>.Shared.Rent(512);
    int offset = 0;
    for (int i = 0; i < values.Length; i++)
    {
        var written = MemoryExtensions.ToUpper(values[i], output.AsSpan(offset), CultureInfo.InvariantCulture);
        if (written == -1)
        {
            Grow(ref output);
        }

        offset += written;
    }
    var result =  output.AsSpan(0, offset).ToString();
    ArrayPool<char>.Shared.Return(output);
    return result;
}

private static void Grow(ref char[] array)
{
    var backup = array;
    array = ArrayPool<char>.Shared.Rent(backup.Length * 2);
    backup.AsSpan().CopyTo(array);
    ArrayPool<char>.Shared.Return(backup);
}
```
The above code does that specific check, assuming the buffer size might be too small for some input.
I've seen three kind of APIs using Span so far:
1. Should never fail, e.g. void DoSomething()
2. Should rarely fail, e.g. those ToUpper etc. methods
3. Might fail more often, e.g. bool Utf8Parser.TryParse(..., out var written)

I imagine that those ToUpper/Lower methods are an edge case of 1. and 2., if you don't care about the implementation detail ``source.Length`` it could very well be a 1.

I imagine that @stephentoub  or @ahsonkhan  can explain more why specifically the second approach was chosen.

**Comment by JarLob** [comment]
So there are two possibilities:
1. Developer didn't think ToUpper may fail and didn't add the code to verify return value. Result - bug went unnoticed.
2. Developer thought it may fail. And added the code to check. But if the return value can be predicted from the `destination.Length` of
```cs
public static int ToUpper(this ReadOnlySpan<char> source, Span<char> destination, CultureInfo culture)
```
why then return value is needed at all? In your example
```cs
var written = MemoryExtensions.ToUpper(values[i], output.AsSpan(offset), CultureInfo.InvariantCulture);
while (written == -1) // you should have some kind of loop in here.
{
    Grow(ref output);
    written = MemoryExtensions.ToUpper(values[i], output.AsSpan(offset), CultureInfo.InvariantCulture);
}
```
can be rewritten as:
```cs
var outSpan = output.AsSpan(offset);
while (outSpan.Length < values[i].Length)
{
    // not effective to increase in steps if we know exactly how much is needed, but for the sake of example
    Grow(ref output);
    outSpan = output.AsSpan(offset);
}
MemoryExtensions.ToUpper(values[i].AsSpan(), outSpan, CultureInfo.InvariantCulture);
```
Maybe having int as a return value is good to changing implementation details in the future, but nothing prevents developers now from writing performant code without using the return because both source and destinations are Spans and have Length, but not throwing in unlikely cases hides potential bugs.

**Comment by ahsonkhan** [comment]
The API initially returned void [but was changed]( https://github.com/dotnet/corefx/issues/21395#issuecomment-365806634), the reasoning for which can be seen in [this GitHub thread](https://github.com/dotnet/coreclr/pull/16379#discussion_r168325118).

Essentially, if the presupposition that the ToUpper/ToLower APIs do not change the length of the data was removed, we would have to change the public signature of the API. Having the API return the amount of data written avoids API change.

 > All four functions **always** return `source.length` in case of success. Do you think it can be something different on other platforms?

Hence, this is an implementation detail and not guaranteed, necessarily.

> Yes, exceptions are expensive, but this is error prone design, because callers will forget they **must** check the return value.

That is why the API was designed with a return value. The contract suggests you should do something with the return value (in an attempt to avoid scenario 1). A void returning method gives even less indication that the caller needs to do anything and as you mentioned, exceptions are expensive (especially if we are catching the exception to resize within a loop). The span-resizing pattern is a common practice with a lot of our span-based APIs and hence we haven't used exceptions for length mismatch anywhere.

cc @tarekgh

**Comment by JarLob** [comment]
Fair enough, then please fix the documentation.

**Comment by ahsonkhan** [comment]
> please fix the documentation.

We are starting to get API docs now and this issue is tracking that effort: https://github.com/dotnet/corefx/issues/29694

We don't yet publish documentation for the MemoryExtension APIs.
https://docs.microsoft.com/en-us/dotnet/api/system.span-1?view=netcore-2.1

cc @mairaw 

I will keep this issue open to add the documentation for the return type within the source code.

**Comment by JarLob** [comment]
Well, what I meant it is not documented in the source in the first place: https://github.com/dotnet/corefx/blob/5f3d22a7f335ae4c1dd57f9ac8b7460a13d57ee0/src/Common/src/CoreLib/System/MemoryExtensions.Fast.cs#L269-L280
Culture, destination, source parameters are documented. There are remarks, summary, possible exception types. But nothing about return value.

**Comment by ahsonkhan** [comment]
> Well, what I meant it is not documented in the source in the first place:

> But nothing about return value.

Yes, thanks for catching that gap in the documentation. We should fix this. PRs are always welcome :)

> I will keep this issue open to add the documentation for the return type **within the source code**.

**Comment by JarLob** [comment]
Yeah, I know PR or GTFO but I'll let the architects to document their intentions :)
