### ISSUE TITLE
System.ServiceProcess.ServiceController.Tests needs admin privleges...

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#3134]
...but the tests don't check for permission ahead of time/don't report that as a possible error.

**Comment by stephentoub** [comment]
This is why those tests are skipped as part of CI builds.

**Comment by pallavit** [comment]
We could add gates in places to run tests only in admin mode but my understanding was that all admin only tests were to be part of our outer loop testing and were to be handled together.

**Comment by Clockwork-Muse** [comment]
@pallavit - it probably was; I was modifying those tests, so had to run them regardless.  Would be nice to report that as a possible error.

**Comment by pallavit** [comment]
I thought about this a bit more and an easy fix would be to add a check in the class constructor, in which case, every test will fail in case its run in non-admin mode. However, ideally, I would like to fail only once. I could not find anything short of creating an ITraitDiscoverer (but that will also just skip tests). First option is acceptable but just wanted to double check :)

**Comment by Clockwork-Muse** [comment]
A trait that could call out to a method for checking "run or skip? (+ message)" would be handy; there's a number of things in the PLINQ tests that require running on multi-threaded machines.
I'm of two minds about failing vs skipping in cases like this....

**Comment by weshaggard** [comment]
@chrisboh we need a way to declare these requirements in our test system.

**Comment by davidsh** [comment]
We might want to look into this Xunit extension which allows for creating skippable [Fact] and [Theory]:

https://github.com/AArnott/Xunit.SkippableFact

It doesn't yet work w/ CoreCLR but it could.

**Comment by pallavit** [comment]
Since, we might need a change at the test infrastructure level rather than at this particular test level, I have created #3349

**Comment by joshfree** [comment]
@ellismg could you look at adding support for elevated permission runs after you finish up Win7\Win10 CI runs?
