### ISSUE TITLE
How does one create and debug a private release of corefx ?

### ISSUE THREAD

**Issue by odhanson** [dotnet/corefx#31352]
Hi

I would like to know what's the best way to have my .net core application reference the debug version of corefx built locally on my machine. I guess the easiest way that won't require me updating all my application projects is to create nuget packages out of my local build and install them on a local nuget repo and update my nuget.config ? Is there some script that would do all of that ?

**Comment by Anipik** [comment]
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md these are instructions for using local built corefx for the applications

**Comment by odhanson** [comment]
Thanks !
