### ISSUE TITLE
.net Core xUnit project and app.config

### ISSUE THREAD

**Issue by asharda1** [dotnet/corefx#31354]
HI,
 I have created a test project with default template provided by visual studio for
xUnit test project (.Net core 2.0)
 With this test project I want to test one of my Business layer, of the web Project , in the business layer project settings are accessed by web.config file using System.Configuration.configurationManager .
As the Businesslayer is tested directly , I added App.config in the xUnit Test Project adn Added reference (Nuget)for the system.configuration.configurationManager
But in the test method when I access ConfigurationManager.Appsettings.Keys.Count I am always getting 0 count while my app.config has all these settings.
What changes I have to make so that Business layer can get the configuration settings, without making any change to business layer project.

**Comment by danmosemsft** [comment]
@jeremykuhne, although I think there is already a similar issue

**Comment by JeremyKuhne** [comment]
#22101discusses this in detail. The recommendation is [here](https://github.com/dotnet/corefx/issues/22101#issuecomment-374415132).
