### ISSUE TITLE
Disposing object posted into DataSourceBlock.

### ISSUE THREAD

**Issue by Temppus** [dotnet/corefx#31363]
Hello. Recently I have started using TPL dataflow library and come across an issue whichI could not solve.

I have one BroadcastBlock which have a cloning function:
```csharp
var publisher = new BroadcastBlock<GrabbedFrame>(GrabbedFrame.Copy);
```
Then I have a couple of ActionBlocks created like this 

```csharp
var processorBlock = new ActionBlock<GrabbedFrame>(frame =>
ProcessBlock = new ActionBlock<GrabbedFrame>(frame =>
{
        using (frame)
        {
            ProcessFrame(frame);
        }
}, new ExecutionDataflowBlockOptions
{
    BoundedCapacity = 1
});
```
**PROBLEM DEFINITON:**

- Object which I am passing to BroadcastBlock is disposable and I do not want to let GC to take care of it, because frame's size is huge and frames are posted very frequently.
- **I want to know when I can safely dispose an object posted to broadcastblock** (I tried to remember reference to previous frame and when a new frame is posted disposing previous one, but that sometime leads to a state where the broadcast block was still cloning previous frame, even if a new one was already posted).

Is there any solution for this ?
Thank you for any advice.

**Comment by tarekgh** [comment]
@Temppus sorry for the late reply. I assume your cloning method is just passing the same frame instance and not really cloning it. and you want to dispose of this frame instance when processed by all linked Blocks when posting it to the BroadcastBlock. please correct me if this is not correct. 

My question is, do you know the number of Blocks linked to the BroadcaseBlock object? I think in your example, how many ActionBlocks linked to the publisher. if you know this, would be easy to implement some mechanism to store the expected number of Blocks will get notified and every time the frame get processed by such block, you can decrement this number and then when it reaches zero you can dispose of the frame. here is some code example: 

```C#

   class Frame
        {
            public Frame(int i) { Item = i; }
            public int Item { get; set; }
            public int RefCount { get; set; }

            public void Dispose()
            {
                Console.WriteLine($"{this} is disposed.");
            }

            public override string  ToString()
            {
                return Item.ToString();
            }
        }
```



```C#
            BroadcastBlock<Frame> bc = new BroadcastBlock<Frame>(item => { item.RefCount = 2;  return item; });

            ActionBlock<Frame> ab1 = new ActionBlock<Frame>(item => 
            {
                Console.WriteLine($"Block1: {item} -- {item.RefCount}");
                if (--item.RefCount <= 0)
                    item.Dispose();
            });

            ActionBlock<Frame> ab2 = new ActionBlock<Frame>(item => 
            {
                Console.WriteLine($"Block2: {item} -- {item.RefCount}");
                if (--item.RefCount <= 0)
                    item.Dispose();
            });

            bc.LinkTo(ab1);
            bc.LinkTo(ab2);

            bc.Post(new Frame(10));
            bc.Post(new Frame(20));
            bc.Post(new Frame(30));

```

**Comment by Temppus** [comment]
Hi @tarekgh. Thank you for your advice, but unfortunately number of "subscribers" can be dynamic at runtime, so this solution is not applicable. 
I am trying to find a way to tell when broadcast block will never call cloning function again for object that was posted in past (because newer one was posted and should overwrite it).

**Comment by tarekgh** [comment]
@Temppus your idea may work too. I am closing this issue but feel free to reply back if you have any more questions or asks.

**Comment by Temppus** [comment]
I have managed a way to workaround this issue (with a ugly hack) before I created issue. But I was hoping there is some cleaner way to achieve this. It seems like there is no solution yet ...
