### ISSUE TITLE
ECDsaCng.HashAlgorithm defaults to SHA256 on netfx, null on corefx

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#31376]
Looks like ECDiffieHellmanCng got it right.

Both classes could use a test for verifying the default (if ECDiffieHellmanCng doesn't already have one).

**Comment by davidkaya** [comment]
@bartonjs I'd take this one if it is possible.

**Comment by bartonjs** [comment]
@davidkaya Go for it.  I can't seem to assign it to you, so I've assigned it to me.

**Comment by davidkaya** [comment]
@bartonjs I've created a PR.
