### ISSUE TITLE
RegistryKey.GetValue for WinLogon Fails to Return All Values

### ISSUE THREAD

**Issue by alaskanrogue** [dotnet/corefx#31370]
When using RegistryKey.GetValueNames to retrieve the values of "LOCALMACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon", not all values of the key are returned. It only returns 10 values, which matches the ValuesCount of the key. However, if I manually count the values of the key using "regedit", I have 33 values recorded. There is no way to update the values count of key, either in "regedit" or code. It appears that this "bad" count is impacting using the GetValue method, which I am trying to use.

**Comment by danmosemsft** [comment]
@alaskanrogue can you provide minimal code to repro this?
Also can you please try this on .NET Framework and see whether the behavior is the same.
Finally you might try procmon (sysinternals.com) to see what registry access is going on and what the OS is providing us.

**Comment by alaskanrogue** [comment]
This is on the .NET Framework in the Microsoft.Win32 namespace using the RegistryKey class in the "mscorlib.dll". As I discovered the problem debugging. what do I want to filter on because just the time span to engage the capture, perform a single debugging step and end the capture recorded 1800+ events.

**Comment by alaskanrogue** [comment]
`using Microsoft.Win32;

using System;
using System.ComponentModel;
using System.Configuration.Install;

namespace ChangeRegistry
{
    public class RegistryChanges : Installer
    {
        private string registryValue;
        private readonly string keyPath = "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon";
        private readonly string keyValue = "Userinit";

        private readonly string originalValue = "C:\\Windows\\system32\\userinit.exe,";
        private readonly string newValue = "C:\\Program Files (x86)\\Microsoft\\Userinit\\userinit+.exe,";

        public void UpdateRegistry()
        {
            string[] valueNames = new string[20];

            RegistryKey rk = Registry.LocalMachine.OpenSubKey(keyPath, true);
            valueNames = rk.GetValues();
        }
    }
}
`

**Comment by danmosemsft** [comment]
I ran this
```C#
using Microsoft.Win32;
using System;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            RegistryKey rk = Registry.LocalMachine.OpenSubKey("SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon", true);
            string[] valueNames = rk.GetValueNames();

            Console.WriteLine(valueNames.Length);
        }
    }
}
```
In a regular prompt, I get a security exception. In an elevated prompt, I get 35, which matches regedit.

ACL's are on keys not values so I would expect you to see all or none. My guess is that you are not running as admin, and Windows is somehow doing compatibility shimming such that you can see some values and not others.

**Comment by alaskanrogue** [comment]
Both starting VS as the admin and logging on as the admin and running VS, then debugging resulted in the same number of values: 10. I have been running VS as the admin because of the noted security exception since I encountered it.

At a "regular prompt"? Not sure what you are implying.

As you can see, I have more than 10 values...

![capture](https://user-images.githubusercontent.com/14001196/43283095-f6412696-90e5-11e8-8f4a-2fffad1fc7d2.PNG)

**Comment by danmosemsft** [comment]
By "regular prompt" I meant when not elevated, ie without admin privileges.

If you use GetValue with one of the names you're not getting back, does it work? https://msdn.microsoft.com/en-us/library/microsoft.win32.registry.getvalue(v=vs.110).aspx

Otherwise I would use procmon and filter to registry keys containing "Winlogon" in the "Path". Perhaps you'll see something useful. I can't repro myself, so I can't investigate locally.

**Comment by alaskanrogue** [comment]
It appears that since I had "Prefer 32bit" enable for the project, it was accessing "Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Winlogon" and not "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon". Disabling the option enable the method to function properly. I just got a count of 32.

Thanks for attempting to help Dan. And thanks to [VIorel](https://social.msdn.microsoft.com/profile/viorel_/?ws=usercard-mini)!

**Comment by danmosemsft** [comment]
Ah! I should have realized that! I was using 64 bit. Glad yo'ure fixed.
