### ISSUE TITLE
HttpResponseMessage.Headers does not contain all headers

### ISSUE THREAD

**Issue by bloritsch** [dotnet/corefx#31381]
Can I have a simplified API where I can get or set headers in one single lookup?  I.e. only one requestMessage.Headers and one responseMessage.Headers I have to worry about.  It should also be much better documented which headers have to be retrieved from the message.Content.Headers vs. message.Headers.

I've worked with several languages and their APIs, and System.Net.Http and the way request and response headers are handled is very surprising and complicates what should be a simple transaction.

I maintain a project that generates REST client code from a C# interface, and I am constantly finding surprising behavior regarding header validation and where those headers are supposed to be set or retrieved.  In short, the API is too restrictive.

You are placing on the user the requirement to know whether any given header has to be retrieved from

responseMessage.Headers.GetValues(headerName)
or
responseMessage.Content.Headers.GetValues(headerName)

I just need an API that has the headers collapsed into one list (like almost every other platform).  This over-prescriptive API adds complications where it doesn't need to be.  Unfortunately, if I am generating code for Net Standard or Net Core, I have to work with it.

**Comment by dotnetchris** [comment]
I was about to open a similar issue but thankfully the create issue found this one.

Working with Response headers is absolutely **awful**. Trying to echo responses is nightmarish. Look at this garbage code I have to write to do something that should be as trivial as

```c#
msg1.Headers.CopyTo(msg2.Headers)
```

Instead i have to do write code like:

```c#
            foreach (var header in message.Response.Headers)
            {
                var key = header.Key;
                var values = header.Value;
                var concat = string.Join(';', values);

                switch (key)
                {
                    case "Content-Type" when (concat.Contains("application/json", StringComparison.OrdinalIgnoreCase)):
                        var mediaTypeHeaderValue = new MediaTypeHeaderValue("application/json");
                        if (concat.Contains("charset", StringComparison.OrdinalIgnoreCase))
                            mediaTypeHeaderValue.CharSet = concat.Split("charset=", StringSplitOptions.RemoveEmptyEntries).Last().Trim();
                        msg.Content.Headers.ContentType = mediaTypeHeaderValue;
                        break;
                    case var _ when (key.StartsWith("Content-")):
                        msg.Content.Headers.TryAddWithoutValidation(key, values);
                        break;
                    default:
                        msg.Headers.Add(key, values);
                        break;
                }
            }
```

Not to mention the insane amount of disagreement between what is a string, what are `StringValues`. It's like someone set out to design the worst possible solution and this is what we have.

**Comment by karelz** [comment]
Triage: This was a mistake long time ago in the original API design. We have to live with it.
We believe that additional property would confuse things even more.

When/if we ever get to designing new API (e.g. for high-perf), we should keep this in mind and fix this among couple of other unpleasant things in `HttpClient` API surface.
