### ISSUE TITLE
XmlException: Resolving of external URIs was prohibited.

### ISSUE THREAD

**Issue by alitaghavi** [dotnet/corefx#31390]
I have the following code to transform XML to CSV using XslCompiledTransform in **.Net Core App 2.0**; however, the code returns **XmlException: Resolving of external URIs was prohibited** during the execution of **xslt.Transform(xmlFilePath, csvFilePath);**.

I created another console app targeting **.Net 4.7** and copied the same exact code over. The app ran successfully and generated the output CSV file. 
```
public class Program
    {
        static void Main(string[] args)
        {
            string basePath = "currentDirectory";

            string xsltFilePath = Path.Combine(basePath, "testxslt.xslt");
            string xmlFilePath = Path.Combine(basePath, "sample.xml");
            string csvFilePath = Path.Combine(basePath, "test.csv");

            XslCompiledTransform xslt = new XslCompiledTransform();

            xslt.Load(xsltFilePath, new XsltSettings(true, true), new XmlUrlResolver());

            xslt.Transform(xmlFilePath, csvFilePath);
        }
    }
```

**Comment by vcsjones** [comment]
This is a known compatibility change. .NET Core does not allow resolving external URIs for XSLT transformations by default and is [documented here](https://github.com/dotnet/corefx/wiki/ApiCompat#systemxmlschema).

As the documentation says, the old behavior can be restored, if you so choose, by putting

```csharp
AppContext.SetSwitch("Switch.System.Xml.AllowDefaultResolver", true);
```

In your application.

**Comment by alitaghavi** [comment]
Great! It worked. Thanks

**Comment by krwq** [comment]
Thanks @vcsjones - @alitaghavi please let us know if there is anything else we could help with - closing the issue for now
