### ISSUE TITLE
AppDomain should be a sealed type like .NET Framework

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#31391]
Looks like we didn't seal AppDomain when we added it to .NET Core, https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs#L11.

See http://index/?query=Appdomain&rightProject=mscorlib&file=system%5Cappdomain.cs&line=208 which has it sealed in .NET Framework.

cc @jkotas

**Comment by danmosemsft** [comment]
@weshaggard should this have showed up in src\shims\ApiCompatBaseline.netcoreapp.netfx461* (`CannotSealType`)

**Comment by weshaggard** [comment]
Yes I would expect it to show up. Perhaps there is a bug somewhere it is worth digging into.
