### ISSUE TITLE
Expression interpreter - AddOvf does not throw OverflowException

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#3141]
In AddInstruction.cs, the following code `(Int16)checked((Int16)l + (Int16)r)` seems to be wrong and should be `checked((Int16)((Int16)l + (Int16)r))` instead.

Repro:

`Expression.Lambda(
    Expression.AddChecked(
        Expression.Constant(Int16.MinValue),
        Expression.Constant(Int16.MinValue)
    )
).Compile().DynamicInvoke()`

throws TargetInvocationException with an OverflowException when using the compiler. When using the interpreter, it succeeds.

**Comment by stephentoub** [comment]
cc: @VSadov
