### ISSUE TITLE
ClientWebSocket options are not accessible on instantiation

### ISSUE THREAD

**Issue by iRubens** [dotnet/corefx#31416]
Hi,
I'm trying to improve [Gremlin.Net](/apache/tinkerpop/tree/master/gremlin-dotnet) library in order to allow users to update the ClientWebSocket instance options. In our case I'd like to update proxy settings to allow WebSockets work on our network.

To do that, i'm thinking to pass a ready-made instance of the options on ClientWebSocket's instantiation or wrapping the framework classes to set "manually" each setting (but i'd prefer not to).

I'd suggest to allow external instantiation of [ClientWebSocketOptions](/dotnet/corefx/blob/master/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/ClientWebSocketOptions.cs) and adding a parameter to the constructor of [ClientWebSocket](/dotnet/corefx/blob/master/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/ClientWebSocket.cs) to pass the above-mentioned instance.

Please let me know if there's any question/problem.

**Comment by karelz** [comment]
Triage: Seems ok, but requires few APIs to be added and the value is low (only 1 vote in 1 year). Closing.
We can reconsider if/when there are more customers asking for it.
