### ISSUE TITLE
Port more TraceListeners

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#31428]
These event listeners were not ported to .NET Core. Suffixed is the % of netfx compat lab submissions that use them: this is the best proxy for general usage in apps and non public libraries.
```
System.Diagnostics.ConsoleTraceListener (3%) -- seems trivial
System.Diagnostics.EventLogTraceListener  (6%) -- fairly trivial
System.Diagnostics.XmlWriterTraceListener (6%)-- fairly trivial
System.Diagnostics.EventSchemaTraceListener  (0%)
System.Diagnostics.Eventing.EventProviderTraceListener (0%)
```
In comparison System.Diagnostics.TextWriterTraceListener, which is already ported, has 20%.  Some of them use it as a base class. DelimitedListTraceListener is also already ported - 1%.

ConsoleTraceListener came up in a list provided by a customer of analysis of their winforms apps.

@brianrob are you aware of limitations in the trace source/listener mechanism (beyond that TracdeSource [does not read from app.config](https://github.com/dotnet/corefx/issues/24829)). Any reason we should not port the first three?

**Comment by safern** [comment]
I will take this one and talk to @brianrob as I go through them.

**Comment by danmosemsft** [comment]
@safern, I see references to EventProviderTraceListener in some Azure service we are looking to port. How much work does it look like that would be to bring over?

**Comment by safern** [comment]
> How much work does it look like that would be to bring over?

I'm not an expert in the area, but it looks like we have an internal `EventProvider` that we could use for it, but it seems to behave slightly different than the one we exposed publicly. 

I think about 2-3 days with proper testing.
