### ISSUE TITLE
Port System.Media

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#31426]
This is a Windows specific namespace. In .NET Framework it's in System.dll and has no relationship I see with Winforms so probably it should go in CoreFX perhaps in System.Windows.Extensions.
```
 System.Media.SoundPlayer  
 System.Media.SystemSound
 System.Media.SystemSounds
```

Any tests that emit sounds should be outer loop..

**Comment by hughbe** [comment]
I've got al these members working on .NET Core Windows on this branch: https://github.com/dotnet/corefx/compare/master...hughbe:expose-system-media

I'm not around for 3-4 days so can't work on it right now, and also waiting for https://github.com/dotnet/corefx-testdata/pull/26 to be merged

**Comment by safern** [comment]
@hughbe test data package is available in myget now: https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Windows.Extensions.TestData

Do you have time to finish this up?

**Comment by hughbe** [comment]
Yeah I’ll work on it tomorrow I’ve already got a PR
