### ISSUE TITLE
ZLib1.2.8+ causes problems when ZStream gets moved by GC

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#31445]
There is an issue with zlib 1.2.8.1+ where it is required for the ZStream object to remain at a fixed location.

We are currently defining and declaring ZStream in managed code in class `ZLibStreamHandle` and therefore clrcompression (which currently uses zlib 1.2.11) may hit issues when ZSteam from `ZLibStreamHandle` gets moved by the GC.

[Here](https://github.com/dotnet/corefx/blob/master/src/System.IO.Compression/src/System/IO/Compression/DeflateZLib/ZLibNative.cs#L177) is where the `_zStream` field is defined in `ZLibStreamHandle`:
```
private ZStream _zStream;
```

where `ZStream` is a very simple struct defined [here](https://github.com/dotnet/corefx/blob/master/src/System.IO.Compression/src/System/IO/Compression/DeflateZLib/ZLibNative.ZStream.cs).

Meanwhile, when we interop with the native we just use the ref of `_zStream` as shown [here](https://github.com/dotnet/corefx/blob/master/src/System.IO.Compression/src/System/IO/Compression/DeflateZLib/ZLibNative.cs#L269):

```
return Interop.zlib.Deflate(ref _zStream, flush);
```

then if GC moves the `ZLibStreamHandle` object in the heap, it means the address of `ZStream` is moved too. which will fail the ZLib native code validation. Refer to [here](https://github.com/dotnet/corefx/blob/master/src/Native/Windows/clrcompression/zlib/deflate.c#L361):
```
... || s->strm != strm || ...
```

To fix this issue we need to consider the following options:
- GC Pinning the ZStream object
- Remove the `_zStream` field from `ZLibStreamHandle` and manually allocate/deallocate unmanaged memory for ZStream in the `ZLibStreamHandle` class.

Related to: https://github.com/dotnet/corefx/pull/30362
cc: @tarekgh @AlexGhiondea @joshfree @danmosemsft

**Comment by danmosemsft** [comment]
And you already have the fix it sounds like?

**Comment by maryamariyan** [comment]
yes

**Comment by jkotas** [comment]
We should manually allocate/deallocate unmanaged memory for ZStream to fix this.

**Comment by tarekgh** [comment]
@jkotas I believe that is what @maryamariyan is going to do. using unmanaged memory for ZStream.

**Comment by tarekgh** [comment]
@maryamariyan I think you can close this one. right?

**Comment by maryamariyan** [comment]
After tracing down the code for windows netcoreapp in corefx, I noticed how @ianhays PR makes sure we don't hit this GC issue while upgrading to 1.2.11

If you take a look at this line:
https://github.com/dotnet/corefx/blob/master/src/Native/Windows/clrcompression/CMakeLists.txt#L26

We are using the pal_zlib.c file which already existed for Unix and contains a PAL_ZStream type.
PAL_ZStream wraps ZStream and controls it's lifetime in the native side.
Because of PAL_ZStream the managed side won't be able to move ZStream in the managed heap.

I'll close this issue due to the explanation above.
