### ISSUE TITLE
Take advantage of Remove being allowed during Dictionary<K,V> enumeration

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#31459]
Now CoreFX has picked up the CoreCLR side of https://github.com/dotnet/corefx/issues/29979, we take advantage of it in CoreFX code.

We need to find code like this
```c#
var removes = new List<object>();
foreach(var entry in dict)
{
    if (predicate(entry.Key))
            removes.Add(entry.Key);
}
foreach(var entry in removes)
{
    dict.Remove(entry);
}
```
or equivalently in Linq
```c#
foreach (var entry in dict.Where(entry => predicate(entry.Key)).ToList() ) 
{
  dict.Remove(entry.Key);
}
```
and replace with just 
``` c#
foreach(var entry in dict)
{
    if (predicate(entry.Key)   // or test Key and Value
           dict.Remove(entry);
}
```
which is half as much code, half the complexity, and most importantly does not allocate.

It might take a Roslyn analyzer to find these.

@MarcoRossignoli any interest in taking a look?

**Comment by danmosemsft** [comment]
I meant @Wraith2 but either is good 😃

**Comment by Wraith2** [comment]
I did make a start on this by writing an analyser to try and identify them. If you can tell me where that's from I'll see if it picks it up.

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/blob/fff6642338839959fffabb1e2e68b64014ce1ef5/src/System.Configuration.ConfigurationManager/src/System/Configuration/ConfigurationLockCollection.cs#L236-L243

The analyzer doesn't need to be "perfect" (if that's even possible) just reasonable enough hueristics that it catches few enough cases to eyeball individually. Even "removing from a dictionary while enumerating over a list" might not be an unacceptable number of false positives.

**Comment by MarcoRossignoli** [comment]
@danmosemsft this should be advertised on next release i saw a lot of code around did tmp list(not only corefx i meant)!

**Comment by Wraith2** [comment]
My analyser wouldn't have caught that one because it wasn't using generic dictionary. If I relax the criteria to calls to Remove on an instance of a type with Dictionary in the name while inside at least one level of loop it is found though. Gist for the code is [here](https://gist.github.com/Wraith2/22a1285106d4d8dd07fc53acb82f048b) just change the paths around for your corefx and let it run.

**Comment by danmosemsft** [comment]
You are right - I misread. Are there any interesting hits in corefx?

**Comment by Wraith2** [comment]
A few but not nearly as many as I expected. I started digging into the first couple and got bogged down. List is currently:

corefx\src\System.Threading.Tasks.Dataflow\src\Internal\ReorderingBuffer.cs:154
corefx\src\System.Net.ServicePoint\src\System\Net\ServicePointManager.cs:148
corefx\src\System.Private.Xml\src\System\Xml\XmlNamespacemanager.cs:256
corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlDependencyListener.cs:1294
corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlDependencyUtils.cs:350
corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlDependencyUtils.cs:352
corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlDependencyUtils.cs:459
corefx\src\System.Net.HttpListener\src\System\Net\Managed\HttpEndPointListener.cs:385
corefx\src\System.Private.Xml\src\System\Xml\BinaryXml\XmlBinaryReader.cs:2494
corefx\src\System.Private.Xml\src\System\Xml\Core\XmlTextWriter.cs:1549
corefx\src\System.Private.Xml\src\System\Xml\Core\XmlWellFormedWriter.cs:1902
corefx\src\System.Text.RegularExpressions\src\System\Text\RegularExpressions\Regex.Cache.cs:45
corefx\src\System.ComponentModel.Composition\src\System\ComponentModel\Composition\Hosting\DirectoryCatalog.cs:636
corefx\src\System.ComponentModel.Composition\src\System\ComponentModel\Composition\Hosting\ImportEngine.RecompositionManager.cs:111
corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SNI\SNIMarsConnection.cs:250
corefx\src\System.Linq.Expressions\src\System\Linq\Expressions\Interpreter\LightCompiler.cs:2883
corefx\src\System.Net.Http\src\System\Net\Http\Headers\HttpHeaders.cs:377
corefx\src\System.Net.Http\src\System\Net\Http\Headers\HttpHeaders.cs:429
corefx\src\System.Net.Http\src\System\Net\Http\Headers\HttpHeaders.cs:674
corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:531
corefx\src\System.Linq.Parallel\src\System\Linq\Parallel\QueryOperators\Binary\IntersectQueryOperator.cs:313

**Comment by danmosemsft** [comment]
Some of those look like actual hits eg HttpHeaders.cs, SqlDependencyListener.cs

**Comment by danmosemsft** [comment]
Thank you for your analyzer @Wraith2. I fixed the cases that were real.
