### ISSUE TITLE
X509Certificate2Collection.Find fails with hex pasted from certmgr.msc

### ISSUE THREAD

**Issue by alfredmyers** [dotnet/corefx#31463]
It's really a bug with certmgr.msc but it has been hitting people for almost a decade now. 
In a quick search, the oldest mention dates back to [October 2010](https://social.msdn.microsoft.com/Forums/vstudio/en-US/6a988c25-b7d1-4e46-af88-1ec077d7051b/find-certificate-by-its-thumbprint?forum=csharpgeneral).

It's UI inserts an invisible [left-to-right mark](https://en.wikipedia.org/wiki/Left-to-right_mark) at the beginning of the hexadecimal string returned by some of it's properties such as:
- Serial Number
- Thumbprint

It seems to have been solved in later versions of Windows (while my work laptop with Windows 10 Enterprise 1703 still has it, my home desktop Win 10 Pro 1803 doesn't), but it will be a while until everybody upgrades.

**Comment by vcsjones** [comment]
I agree that it's super annoying the the certificate dialog has (had) that copy-able character.

Though, I'm not sure CoreFX should be special casing a peculiar behavior by Windows. I could maybe see a user interface with a prompt to trim it, or a configuration reader if someone pasted it in to config.

This could also be a breaking change to some folks that were accidentally dependent on something _not_ finding a certificate, though I suspect that is a minor case.

My 2¢.
