### ISSUE TITLE
Question: Naming conventions, Conditionals and Questions for iOS PAL

### ISSUE THREAD

**Issue by baulig** [dotnet/corefx#31469]
As part of Mono's adaption and integration of CoreFX's PAL layer, I have started to port some files to iOS.  Things are going well so far, but I have a few questions about how you guys want to handle a few things regarding to naming conventions and where to put certain files.  I felt like opening an Issue and asking about these things would be easier than having to edit a bunch of things as part of PR reviews.

This is likely going to be a longer project, spanning multiple individual PR's, I simply want to get some feedback and advice on how you guys want to handle these issues.

1. Compile-Time conditional for OS Versions.

We need an option to compile the native PAL without any undefined symbols, which means that  few runtime version checks need to be replaced with compile-time conditionals.  At the moment, I solve the problem by adding a new `pal_version.h` containing

```
#define REQUIRE_MAC_SDK_VERSION(x) (TARGET_OS_MAC && MAC_OS_X_VERSION_MIN_REQUIRED >= (MAC_OS_X_VERSION_ ## x))
#define REQUIRE_IOS_SDK_VERSION(x) (TARGET_OS_IPHONE && IPHONE_OS_VERSION_MIN_REQUIRED >= (__IPHONE_ ## x))
```

These are then used like this (for instance in my version of `pal_rsa.c`):

```
#if REQUIRE_MAC_SDK_VERSION(10_12) || REQUIRE_IOS_SDK_VERSION(11_4)
```

2. Splitting the native PAL between OS X and iOS.

In `src/Native/Unix/System.Security.Cryptography.Native.Apple`, several of the files require larger modifications to work on iOS (and some will not work at all due to platform limitations).

A common situation that I'm currently running into is that some functions can be shared between OS X and iOS and some need special handling.  This applies to both header and source files.

For instance, in my latest working branch, `pal_x509.c` currently has 715 lines - 56 can be shared, 641 will be OS X only and 242 have been added for iOS (which is still incomplete).
 
We have two options here - we can either add conditionals (`#if TARGET_OS_IPHONE`) or split the relevant files into three pieces (which I did in my work branch).  And when splitting them, the question is how to call them.  In my current version, I have these files:

```
pal_x509.c
pal_x509.h
pal_x509_ios.c
pal_x509_ios.h
pal_x509_mac.c
pal_x509_mac.h
```

_Question_: Which option would you guys prefer?

3.  Different signature of native methods between OS X and iOS

In a few scenarios, both OS X and iOS will have a native function with the same name, but different implementation and signature.

For instance, there is currently

```
DLLEXPORT int32_t AppleCryptoNative_RsaEncryptPkcs(
    SecKeyRef publicKey, uint8_t* pbData, int32_t cbData, CFDataRef* pEncryptedOut, CFErrorRef* pErrorOut);
```

The iOS version will have this signature:

```
DLLEXPORT int32_t AppleCryptoNative_RsaEncryptPkcs(
    SecKeyRef SecKeyRef, uint8_t* pbData, int32_t cbData, uint8_t* pbCipherOut, size_t *cbCipherLen, int32_t* pOSStatus);
```

There are also situations where the method signatures can't be kept the same due to missing types like for instance `SecKeychainRef`.

Would it make sense to rename the functions to make it clear which one is for OS X and which one is for iOS (they won't ever be compiled into the same binary)?

4.  Different `Interop.AppleCrypto` implementations.

This of course leads to different `Interop.AppleCrypto` implementations.  And the same situation arises, that some code can be shared while some needs to have a specific implementation.

If I see this correctly, then platform conditionals on the managed level are currently handled by using partial classes.

Looking back at that RSA example in `src/Common/src/Interop/OSX/System.Security.Cryptography.Native.Apple/Interop.RSA.cs`, this file needs to be split into three pieces.  I haven't ported the entire file yet, but my current setup looks like this: 144 lines shared between OS X and iOS, 223 specific to OS X, 196 new in iOS.

_Question_: Do you guys want to use conditionals for this or split it into several partial classes?

_Question_: Should we decide on partial classes, how should they be called and where should they live?

I currently have this:

```
./Apple/System.Security.Cryptography.Native.Apple/Interop.RSA.cs
./IOS/System.Security.Cryptography.Native.Apple/Interop.RSA.cs
./OSX/System.Security.Cryptography.Native.Apple/Interop.RSA.cs
```

Any better idea?  I'm up for suggestions ….

5.  Common API surface of `Interop.AppleCrypto`?

Due to the different native implementation - including completely different method signatures - the API surface of several of the `Interop.AppleCrypto` methods will be different between OS X and iOS.  This is complicated by the fact that a few APIs (such as for instance `SeyKeychainRef`) won't be available.

So this is now a question of design and policy. 

We can either keep the `Interop.AppleCrypto` API as close to the native backend as possible (in this case "higher level" code needs to be conditionalized) or try to unify it between OS X and iOS as much as possible.

However, it may not be possible to keep the "higher level" code unified due to missing features on iOS.

What do you guys think about this?

In my opinion, this is the most difficult aspect and probably needs custom case-by-case evaluation.

**Comment by marek-safar** [comment]
@danmosemsft @karelz who is the best person to set or agree on the policy?

**Comment by joshfree** [comment]
@marek-safer this would be @bartonjs

**Comment by bartonjs** [comment]
Based on the descriptions here, I'd say that an iOS shim would just be a completely independent dylib... which would make a new Interop class (Interop.AppleMobileCrypto?), a new build flavor, and a new PAL in the crypto libraries.  At least, the description leads me to believe that there is very little useful code sharing.  Maybe it was only describing the extreme parts of unsharability?

**Comment by baulig** [comment]
The description was probably a bit misleading in the way that I was only talking about those parts of the PAL that were causing problems.  I don't have any precise numbers yet, but we will probably end up sharing about 70%+ of the native code and 80%+ of the managed code.

Many of the native APIs are available on both macOS and iOS - I'll have to go over them one by one and verify with Apple's Documentation.  And there are situation where making small changes to the managed side would allow us the share it between the platforms (with a completely different native implementation).

One common pattern that I have observed is that in several cases, iOS seems to be using `OSStatus` as error code instead of `CFErrorRef`.

**Comment by baulig** [comment]
For instance, in `pal_secverify.h` the macOS version essentially uses [`SecSignTransformCreate`](https://developer.apple.com/documentation/security/1398780-secsigntransformcreate?language=objc), [`SecTransformSetAttribute`](https://developer.apple.com/documentation/security/1393861-sectransformsetattribute?language=objc) and [`SecTransformExecute`](https://developer.apple.com/documentation/security/1395776-sectransformexecute?language=objc):

```
SecTransformRef SecSignTransformCreate(SecKeyRef key, CFErrorRef  _Nullable *error);
CFTypeRef SecTransformExecute(SecTransformRef transformRef, CFErrorRef  _Nullable *errorRef);
Boolean SecTransformSetAttribute(SecTransformRef transformRef, CFStringRef key, CFTypeRef value, CFErrorRef  _Nullable *error);
```
On iOS, we will use [`SecKeyRawSign`](https://developer.apple.com/documentation/security/1618025-seckeyrawsign?language=objc):

```
OSStatus SecKeyRawSign(SecKeyRef key, SecPadding padding, const uint8_t *dataToSign, size_t dataToSignLen, uint8_t *sig, size_t *sigLen);
```

The PAL code has these signatures:

```
DLLEXPORT int32_t AppleCryptoNative_GenerateSignature(
    SecKeyRef privateKey, uint8_t* pbDataHash, int32_t cbDataHash,
    CFDataRef* pSignatureOut, CFErrorRef* pErrorOut);
DLLEXPORT int32_t AppleCryptoNative_GenerateSignatureWithHashAlgorithm(
    SecKeyRef privateKey, uint8_t* pbDataHash, int32_t cbDataHash,
    PAL_HashAlgorithm hashAlgorithm, CFDataRef* pSignatureOut, CFErrorRef* pErrorOut);
```

While we will need a completely different native implementation (this is actually the part that's most complete), we can share the managed side by making a few changes to it:

```
DLLEXPORT int32_t AppleCryptoNative_GenerateSignature(
    SecKeyRef privateKey, uint8_t* pbDataHash, int32_t cbDataHash,
    CFDataRef* pSignatureOut, int32_t *pOSStatusOut, CFErrorRef* pErrorOut);
DLLEXPORT int32_t AppleCryptoNative_GenerateSignatureWithHashAlgorithm(
    SecKeyRef privateKey, uint8_t* pbDataHash, int32_t cbDataHash,
    PAL_HashAlgorithm hashAlgorithm, CFDataRef* pSignatureOut,
    int32_t *pOSStatusOut, CFErrorRef* pErrorOut);
```

and then we'll need some shared error codes:

```
enum
{
    PAL_Error_False = 0,
    PAL_Error_True = 1,

    PAL_Error_BadInput = -1,
    PAL_Error_SeeError = -2,
    PAL_Error_SeeStatus = -3,
    PAL_Error_Platform = -4,
    PAL_Error_UnknownState = -5,
    PAL_Error_UnknownAlgorithm = -6,

    // these are used by other parts of the PAL, unrelated to this example
    // PAL_Error_UserTrust = -7,
    // PAL_Error_AdminTrust = -8,
    // PAL_Error_OutItemsNull = -9,
    // PAL_Error_OutItemsEmpty = -10
};

```

**Comment by baulig** [comment]
So to summarize, porting `pal_signverify.c` is not too overly complicated and won't require complex changes - it is essentially #31556 plus a few conditionals and the iOS version added.

**Comment by baulig** [comment]
For `pal_rsa.c` - these functions are available on macOS 10.12 and iOS 10:

- `AppleCryptoNative_RsaSignaturePrimitive`
- `AppleCryptoNative_RsaDecryptionPrimitive`
- `AppleCryptoNative_RsaEncryptionPrimitive`
- `AppleCryptoNative_RsaVerificationPrimitive`

We are supporting older versions of Mac OS in Mono, so a platform conditional needs to be added.

- `AppleCryptoNative_RsaGenerateKey` needs the `SecKeychainRef` dance mentioned above.

Mac only:

- `AppleCryptoNative_RsaDecryptPkcs`
- `AppleCryptoNative_RsaEncryptPkcs`
- `AppleCryptoNative_RsaDecryptOaep` - needs OS X 10.8 platform conditional
- `AppleCryptoNative_RsaEncryptOaep` - same

I am not sure whether there is any value of splitting this class as I am currently using my iOS version of `pal_seckey.c`.  This file may need a completely different managed implementation as well.

However, the `pal_rsa.c` is one of the pieces in my code that's most incomplete at the moment.

**Comment by bartonjs** [comment]
Questions that I have:

* What parts of the native shim would be shared?  (e.g. are hashing, HMAC, and symmetric cryptography sharable, or do they need to have refactoring happen, too?)
* Is the iOS version something that will build in CoreFX?
  * How?
* For .NET Core releases we only build one version of the shim for all versions of macOS (that we support)... what are the anticipated usages of \#ifs in the macOS version of the shim?
* In what places does it "make sense" to make a complicated signature to handle both the macOS and iOS input/output needs, and in what places does it "make sense" to have completely different targets?
  * Really it's about volume.  If it's like 3 shared, and like 30 split, then it's not worth having the 3.

There are two (partially conflicting) things that I want to avoid:
* A lot of \#if.
* A lot of "this input is read by macOS" / "this output is set by iOS".

And I really want to avoid overgeneralizations that (e.g.) cause ephemeral keys to become persisted keychain contamination.  My main focus is product security  / code maintainability, and 

So, I guess, what I'm really after is "are the platforms similar enough that they're variants, or are the far enough apart that you need to really think about which one you're working with?"

And as a FYI: I probably won't have much time to pay attention to this issue until after Black Hat / DEF CON.

**Comment by baulig** [comment]
Regarding similarity or difference, I think the answer will vastly differ in different parts of the shim and we will see both the situation where most code can be shared as well as the situation where a completely new implementation will be needed.

From what I've seen so far, my estimate regarding the native side is this:

- `pal_signverify.c`: managed side sharable with the API changes suggested above.
- `pal_rsa.c`: complete replacement with a new `pal_seckey_ios.c`.
- `pal_ecc.c`: see above
- `pal_digest.c`, `pal_hmac.c`, `pal_random.c`, `pal_symmetric.c`: reusable, may need `size_t` adjustments.
- `pal_sec.c`: the single one-line function in here is reusable.
- `pal_x509.c`: needs custom native part, managed side maybe half shareable.
- `pal_keychain.c`: mac only, does not exist on iOS
- `pal_keyagree.c`: haven't looked into yet, but according to Apple's documentation, the single function called in here exists on iOS 10+.
- `pal_trust.c` and `pal_x509chain.c`: haven't looked into these yet, but it seems to be reusable.
- `pal_ssl.c`: we are not going to use that (at least not in this phase of the integration project).

For the managed side, we have the code in `Common/src/Interop/OSX/System.Security.Cryptography.Native.Apple` and then there's code outside that directory calling it.  I believe that we can keep a common API surface between the two versions of `System.Security.Cryptography.Native.Apple` to avoid large code changes outside that directory.

About the version #if's, one requirement that we currently have in Mono is that the code needs to be buildable without undefined symbols.  I am not entirely sure yet how that will eventually all work out as that's still to be discussed.

**Comment by baulig** [comment]
Apart from the iOS port, there's also the problem that for instance `pal_rsa.c` uses [`SecKeyCreateSignature`](https://developer.apple.com/documentation/security/1643916-seckeycreatesignature?language=objc) (which requires macOS 10.12+) in `AppleCryptoNative_RsaSignaturePrimitive`.

I will have to find some solution for this, the current compatibility requirement for Mono is OS X 10.7 and iOS 8.

**Comment by filipnavara** [comment]
> I will have to find some solution for this, the current compatibility requirement for Mono is OS X 10.7 and iOS 8.

Actually it's macOS 10.9+ now (https://github.com/mono/mono/issues/9581).

**Comment by baulig** [comment]
Oh cool - that means we're getting OAEP Padding baseline on Mac :-)

I gave the `pal_rsa.c` some more love today.  What we need to do for Mac (both Desktop and Xamarin.Mac) is the following:

- `AppleCryptoNative_RsaEncryptionPrimitive`, `AppleCryptoNative_RsaDecryptionPrimitive`, `AppleCryptoNative_RsaSignaturePrimitive` and `AppleCryptoNative_RsaVerificationPrimitive` use the new Unified APIs that were introduced in macOS 10.12+ and iOS 10+.
- These need to be renamed and wrapped in a platform conditional for macOS 10.12+ (and possibly iOS 10+).  I suggest calling them `AppleCryptoNative_RsaUnifiedEncryptionPrimitive`, though we can possible make them static / and or hide in the PAL - they won't be called from managed code.
- Two new implementations of `AppleCryptoNative_RsaEncryptionPrimitive` and `AppleCryptoNative_RsaDecryptionPrimitive` need to be added (retaining their name), using `SecEncryptTransformCreate` and `SecDecryptTransformCreate` (this is not too difficult, I already wrote the implementation).  We can add a runtime OS version check and call the Unified API if it's available.
- Alternatively, we could also make the public APIs a version-specific switch between unified and compat.
- For sign / verify, we can just forward to decrypt / encrypt (the verify function already does this) - these functions are only called from `RSASecurityTransforms` with `RSASignaturePaddingMode.Pss`.
- For `AppleCryptoNative_RsaEncryptOaep` and `AppleCryptoNative_RsaDecryptOaep`, this currently only uses SHA1 with a FIXME-type comment about SHA2.  I believe I have figured out how to distinguish the SHA2 variants.
- The new Unified API also seems to support OAEP Padding - for instance there's [`kSecKeyAlgorithmRSAEncryptionOAEPSHA256`](https://developer.apple.com/documentation/security/kseckeyalgorithmrsaencryptionoaepsha256?language=objc) and others.

These changes can be done in the native shim without touching the managed code.

For iOS - if we could increase the minimum supported version to iOS 10 - then we can reuse the Unified APIs.

- I suggest evaluating whether we can use the Unified API for `AppleCryptoNative_RsaEncryptPkcs`, `AppleCryptoNative_RsaDecryptPkcs`, `AppleCryptoNative_RsaEncryptOaep` and `AppleCryptoNative_RsaDecryptOaep`.  This needs to be done with a version check conditional as mentioned above and the current implementation kept for older system.
- For iOS 9, I already have a custom implementation (which will require replacing the managed `Interop.RSA.cs`).

**Comment by filipnavara** [comment]
> Alternatively, we could also make the public APIs a version-specific switch between unified and compat.

That's already done for `SecCertificateCopyKey` and `SecCertificateCopyPublicKey`, so I guess it's the preferred approach. It may make the code look quite ugly, if not done properly, though. I'm waiting for the OpenSSL 1.1 support patch to see if there's some tidier / preferred way to handle the versioning.

As a sidenote, with my application developer hat on, we usually support at least last three major versions of macOS. At the moment that means 10.11 baseline, so I am definitely interested in some added backward compatibility if at all possible, but it's purely my personal opinion. By the time this work is concluded the target may shift to 10.12, which is already the CoreFX requirement.

I'm definitely interested in exploring the code you wrote. My inner feeling was that `pal_x509` would be quite sharable, but you came to different conclusion and I believe you actually got way further on that one than I did. Given all the information above I am starting to believe that it would make sense to split the native side completely, at least until it can be proven that there's some reasonable sharing possible and beneficial at the same time. It seems plausible to me that the managed side could be mostly shared with some small refactoring. You could possibly even keep the keychain code and just return errors from the native part that would indicate that the feature is not supported. There's definitely some problematic code that currently deals with the temporary keychains, but it's hard to judge on that one without seeing how that codepaths would work on iOS (loading X509Certificate in memory, CopyWithPrivateKey and RSA key generation).

**Comment by baulig** [comment]
So to summarize the situation of RSA.

The are three different native APIs that we can use:

- A Mac-only API based on `SecTransformRef` that's available on all versions of OS X that we care about.
- An iOS-only API that's available on all versions of iOS.
- A new Unified API that's available on macOS 10.12+, iOS 10+, tvOS 10+ and watchOS 3.0+.

For Mono, we will need a compatibility solution for Desktop and Mac that works with macOS 10.9+.  I suggest providing a runtime os version switch and use the Unified API when it's available.  Adding this compatibility layer won't be too difficult - in fact, it will only require a few new functions that I've already written.

Once we have a runtime os version switch in place, then we could port the entire `SecTransformRef` based code over to use the new Unified API.  This will give us OAEP Padding with SHA-256 and SHA-512.  My estimate is that this can be done in less than a week and if you guys like the idea, then I can have a look at this when I'm back from my vacations.

On iOS 10+, the situation is quite easy as we can simply reuse the new Mac code.

For iOS 9, we will need a custom native implementation as well as a custom version of the `Interop.RSA.cs` class.  I already have that implementation in my local tree.

**Comment by baulig** [comment]
Well, I basically haven't done any work on the `pal_x509` recently because I wanted to get the hash and encryption algorithms that are used by it done first.

Planning-wise, I essentially want to have all the hash and crypto algorithms complete before we branch for our next monthly integration (which will be the first week of October, the August one just happened).  There are a lot of things to be taken care of on our end before the branch date as well.  Like for instance, how to build the native shim and bundle it on devices, how to run on-device xUnit tests, can we completely repace Mono's managed RSA provider (I would hope so), could we possibly increase the compatibility requirement to iOS 10, etc.

**Comment by baulig** [comment]
If you want to have a look at my current code - it's a big mess at the moment and may not even build, but here it is:

- Mono: https://github.com/baulig/mono/tree/work-canary
- CoreFX: https://github.com/baulig/corefx/tree/work-canary
- XI: https://github.com/baulig/xamarin-macios/tree/work-canary

I will be on vacation next week and will be back on the 20th - by then, the `2018-08` branch of `xamarin-macios` should hopefully be building on Jenkins and I'll rebase my current work on top of that.

**Comment by filipnavara** [comment]
Thanks, I will have a look. I'm finishing some code refactoring / cleanup on the CoreFX side and I have couple of patches in the pipeline that should fix failures with Mono unit tests on macOS. I'll try to learn the Mac/iOS APIs to see if I can come up with some solutions to make the sharing a bit easier.

**Comment by baulig** [comment]
For the keychain related functions, one thing we could do is move the key generation function into a separate file, then iOS can use a custom version of it.

**Comment by bartonjs** [comment]
There are a lot of points discussed so far, hopefully I'll address all of them.

* Compile-Time conditional for OS Versions.
  * I'm not entirely certain what this would look like / where `MAC_OS_X_VERSION_MIN_REQUIRED` comes from.
    * Since corefx is single-build, MAC_OS_X_VERSION_MIN_REQUIRED is presumably just set somewhere.
    * Does Mono have a single macOS build, or is it set to the version of macOS that it builds on?
    * If it's always a floating "what macOS am I?" we'd need to verify how corefx releases.  I know we build on "both" macOSes, but I don't know which one we consume the output from for releasing, so we could be introducing bad binaries.
      * Our normal story here is to just use the API of the oldest version we care about.  The two public key functions from a certificate are the first exception to that, since we're just trying to stave off a deprecation problem.
* Splitting the native PAL between OS X and iOS.
  * I still don't think I know enough to have an opinion.
  * How to watchOS / tvOS / etc play into this over time?
  * Does Mono need to build multiple of these per build (e.g. both the macOS and the iOS from the same build), or is it just one?
  * The three obvious approaches:
    * Unified tree
      * System.Security.Cryptography.Apple
        * CMakeLists.txt / pal_x509.c / pal_x509_ios.c / pal_x509_macos.c
    * Shared trees
      * System.Security.Cryptography.Native.Apple (doesn't build, just a "all the code here goes to both places")
        * pal_x509.c
      * System.Security.Cryptography.Native.Apple.macOS
        * CMakeLists.txt / pal_x509[_macos].c
      * System.Security.Cryptography.Native.Apple.iOS
        * CMakeLists.txt / pal_x509[_ios].c
    * Split trees
      * Like Shared trees, but we copy the code once and then consider them entirely separate.  (And if there's a lot of code sharing, be frustrated at needing to make every change twice).
* Different signature of native methods between OS X and iOS
  * Partially this depends on how the shim build settles.  If there are two different named dylibs then the DllImports all need to be replicated across the two shims, so there's no real reason to try to unify them.  
  * If unification does make sense, then for functions where the managed method has no "on some kinds of failure retry (maybe with doing something different) then the Interop method should trap the difference and throw the exception from there.
* Different Interop.AppleCrypto implementations.
  * Partial classes probably makes the most sense for when things are different.
  * The directory structure is tricky.  We currently don't have a difference between "OSX" and "Apple".  I don't know if { Apple, OSX, IOS }, { OSX ("Apple"), macOS, iOS }, or what.  This one is really a "coordinate the high level point", since the same interop structure is used for IO and whatever else has "Apple OSes aren't the same as Linux" code.  The reason I suggest "OSX" == "Apple" and make "macOS" new is just to keep the amount of churn down.
    * But maybe it's worth ripping the Band-Aid off and having one PR that renames all OSX things to Apple just to reset the baseline.
* Common API surface of Interop.AppleCrypto
  * Like everything else, it's in a "well, it depends on everything else" state :smile:.
  * Aside from comments already sprinkled throughout, my answer is that it's probably case-by-case.  If the same interface can easily apply to both with a "this gives the answer or throws" contract, that's fine.  If it's a lot of gymnastics then it probably means the caller needed to be aware of it.
* AppleCryptoNative_RsaEncryptionPrimitive (and friends)
  * The managed side doesn't need to know how the primitive is implemented, so there's no benefit in exposing the "Unified" version.
* Other RSA stuff
  * If it makes things easier, the interop calls for RSA could be reduced down to the primitives.  We already have code for a lot of the padding, we could pad it out (::rimshot::) with the remaining (Pkcs1Decrypt (fixed time), Pkcs1Sign, Pkcs1Verify).
  * If it doesn't make things easier, then I'm happy to have the platform do it, so long as they do it right :smile:.
* Key generation
  * Theoretically the temporary keychain part could move from managed into native for macOS.  I presumably ended up with temporary keychains because the keys I was generating were leaking in to login.keychain on macOS.  Hopefully there is a way to make them ephemerally on iOS, and not contaminating whatever keychain hierarchy exists on iOS.

**Comment by baulig** [comment]
Since the native shim will be a new addition to Mono, most of the build and integration related questions have not been decided yet and I am still trying to figure out myself how this should all work.  However, I'll try to give you a brief overview of how things are currently set up.

In Mono, we have three different "flavors" of macOS (one desktop profile and two mobile ones) - but since they're using the same native platform, we should be able to treat these as being identical for the purpose of the CoreFX integration.

Each of iOS, tvOS and watchOS has two separate platforms - one for simulator and one for device - with different hardware architectures.  The simulators use i386 and x86_64 (the simulated process runs on your Mac computer) whereas the devices are arm and arm64 (iPhone X).

Each of these platforms has its own native toolchain as well as its own system header files and libraries - see `/Applications/Xcode.app/Contents/Developer/Platforms/` on a Mac.

So from a compilation point of view, there are 7 different platforms: `AppleTVOS.platform`, `AppleTVSimulator.platform`,  `MacOSX.platform`, `WatchOS.platform`, `WatchSimulator.platform`, `iPhoneOS.platform` and `iPhoneSimulator.platform`.  Some of them also need to be built for both 32-bit and 64-bit.

At the moment, we do not build separate versions of the Mono runtime for different operating system _versions_ but instead force a certain minimum version for each platform.

This is done by passing special compiler arguments - for instance, there is `-mmacos-version-min=` for macOS (which will set `MAC_OS_X_VERSION_MIN_REQUIRED`) and iOS has a similar `-miphoneos-version-min=`.

For the mobile platforms, we also have the requirement that native libraries must not contain any undefined symbols as this would break Bitcode.

**Comment by baulig** [comment]
For the native shim, we can either bundle it in the Mono runtime or build it as a separate shared library.  I prefer the latter version as this would allow us to build different versions of it, targeting different operating system versions.

Since Apple introduced the concept of a Unified API between their different platforms in macOS 10.12+ and iOS 10+ - with more features added to the Unified API - I think it would make sense to build both a "legacy" and a "unified" version of the native shim.  This would obviously require the native shim to be its own shared library.

Let me try to address your other questions as good as I can.

- `MAC_OS_X_VERSION_MIN_REQUIRED` is set by some magic in Apple's system header files (`/Applications/Xcode94.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/AvailabilityMacros.h`).
There is a `-mmacos-version-min=` compiler argument to request a specific version.
- Similarly, iOS has `-miphone-os-version-min=`and a similar macro.
- I believe the default version depends on which version of Xcode you're building with, but I am not sure of this.
- As explained above, macOS and iOS are different platforms with different hardware architectures, so they can't share any binaries.
- I would favor the "Shared trees" approach.
- While macOS and iOS need to build different dylibs, these will go into completely different install locations, so there is no need to have a different name.  It should also be irrelevant which name the `[DllImport]` attributes use as these can be remapped by the runtime.
- From the managed code's point of view the main difference is probably that the native methods may return either an integer `OSStatus` or a `CFErrorRef` for error reporting based on which implementation it's using.  And it should know how to deal with a "platform not supported" type error condition (for a few rare situations where something is either not supported or it doesn't make sense to provide a compatibility version for some very old OS version).
- The directory structure is really tricky - using the name "Apple" for everything that's shared between all Apple-based platforms is probably the best long-term.
- For RSA and other crypto classes, one of the advantages of the new unified API is that they added new functionality such as some of those padding operations - it probably makes sense to do as much as possible in native code and only use the managed version as a fallback where no native implementation is available.
- Regarding the keychains - on iOS, each app has its own keychain, there is no "global" one.  I am not sure whether there is a difference between ephemeral and persistent keys, I'd have to check this.

**Comment by baulig** [comment]
Moving forward, I think it's probably best to break things down into smaller pieces and the crypto and hashing functions might be the best starting point as they don't have external dependencies and we also don't have to worry about keychains or anything like that.

I am going to clean up my local work branch this week and then come up with a proposal on how to do the RSA code.

**Comment by stephentoub** [comment]
Seems like questions have been asked and answered and this issue can be closed.  If there's more to discuss, please feel free to re-open, though a more focused issue on a specific topic might be more productive.
