### ISSUE TITLE
WinRtToNetFxStreamAdapter.Flush() throws NotImplementedException when used with Windows.Devices.SerialCommunication.SerialDevice

### ISSUE THREAD

**Issue by dlech** [dotnet/corefx#31460]
I tried using `System.IO.WindowsRuntimeStreamExtensions.AsStreamForRead` to get a stream for a `Windows.Devices.SerialCommunication.SerialDevice.InputStream`. However, when I tried to read from this stream, I get a `System.NotImplementedException` when it implicitly calls `Flush` (if you are wondering why `Flush` on an input stream, the input stream and output stream are really one stream and there was previous data written to the output stream that automatically gets flushed before reading).

The `System.NotImplementedException` actually comes from `Windows.Storage.Streams.IOutputStream`.

To actually write data to the `Windows.Devices.SerialCommunication.SerialDevice`, you have to use a `Windows.Storage.Streams.DataWriter` on the output stream and call `Windows.Storage.Streams.DataWriter.StoreAsync` instead of `Windows.Storage.Streams.DataWriter.FlushAsync`.

Some other reports of a similar situation:
* https://stackoverflow.com/questions/37642313/streamout-flushasync-not-implemented-exception?rq=1
* https://stackoverflow.com/questions/36063898/communicate-between-my-uwp-app-and-my-rfxtrx433e?rq=1

As far as I know, the source code for UWP stuff is not publicly available, so I can't go any deeper.

It would be nice if someone privy to the code could look at the difference between the implementations of StoreAsync and FlushAsync, then maybe we could add a workaround to WinRtToNetFxStreamAdapter that avoids the NotImplementedException for serial devices.

**Comment by pjanotti** [comment]
Throwing on Flush is not a good idea. The doc update that made that clear was lost in some merge, I'm trying to rectify it at https://github.com/dotnet/dotnet-api-docs/pull/437

I'll try to find proper owners of the type.

**Comment by carlossanlop** [comment]
Triage: Looks like the docs are addressing this now. @dlech let us know is you have any more questions.
