### ISSUE TITLE
Prep key enums for binary serialization

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#31477]
Broken out from #30183

- [x] System.Drawing.Color
- [x] System.Drawing.ContentAlignment
- [x] System.Drawing.Drawing2D.LinearGradientMode (low usage, but it's trival to add the attribute)
- [x] System.Drawing.FontStyle
- [x] System.Drawing.GraphicsUnit (for Font)
- [x] System.Drawing.KnownColor
- [x] System.CodeDom.MemberAttributes (Not part of Drawing, but seen heavily in data so presumably designer written, and only enum)
- [ ] ~~System.DayOfWeek (low usage)~~

In each case, simply add `[System.Runtime.CompilerServices.TypeForwardedFrom("System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089")]` (with whatever the correct assembly was in .NET Framework)

A test in BinaryFormatterTestData.cs would be nice to check we got the TFF correct, although I don't see other enums tested directly there.

**Comment by Wraith2** [comment]
> A test in BinaryFormatterTestData.cs would be nice to check we got the TFF correct, although I don't see other enums tested directly there.

I can't find any tests which do this, how would this be accomplished?
