### ISSUE TITLE
Registry API on Linux and macOS

### ISSUE THREAD

**Issue by EgorBo** [dotnet/corefx#31493]
Currently Registry API throws `PlatformNotSupportedException` for all methods: https://github.com/dotnet/corefx/blob/master/src/Microsoft.Win32.Registry/src/Microsoft/Win32/RegistryKey.FileSystem.cs
but the file name (`RegistryKey.FileSystem.cs`) implies on a possible implementation using file system. Is there a task or plans to implement it? 

PS: on Mono it uses files for macOS and Linux

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/issues/14896

**Comment by EgorBo** [comment]
@stephentoub thanks!
