### ISSUE TITLE
Enable HTTP/2.0 related tests

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#31496]
This issue tracks enabling various tests for HTTP/2 to use the opt-in mechanism.

**Comment by davidsh** [comment]
ref: #31424

**Comment by davidsh** [comment]
cc: @dotnet/ncl

**Comment by rmkerr** [comment]
Do we currently have a plan as to how we will implement this? We could just disable test parallelization only for the HTTP/2 tests, but as far as I can tell that requires features introduced in a newer version of xunit ([link](https://github.com/xunit/xunit/issues/1179#issuecomment-339015963)).

**Comment by davidsh** [comment]
This issue is no longer tracking anything.  Issue #34460 is already tracking modifying the existing HTTP/1.1 tests to also run against HTTP/2.0 (either remote server or loopback server).
