### ISSUE TITLE
Expression compiler - Inconsistency with language specification

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#3149]
Section 7.9 of the C# language specification describes the number of bits to shift. It looks like this rule is not honored by the expression compiler which omits the `and` instruction to perform the mask, prior to performing the `shl` or `shr` instruction. The following repros the discrepancy:

Expression&lt;Func&lt;long?, int?, long?&gt;&gt; e = (x, y) => x &lt;&lt; y;

Func&lt;long?, int?, long?&gt; f = (x, y) => x &lt;&lt; y;
Func&lt;long?, int?, long?&gt; g = e.Compile();

var c = f(-9223372036854775808, -2147483648);
var d = g(-9223372036854775808, -2147483648);

Console.WriteLine(c);
Console.WriteLine(d);

Note that the implementation of the expression interpreter relies on C# compiled code fragments for << and >>, so this will cause a different result for .Compile() between frameworks that use the expression compiler versus those that use the interpreter.

**Comment by mikedn** [comment]
> It looks like this rule is not honored by the expression compiler which omits the `and` instruction to perform the mask, prior to performing the `shl` or `shr` instruction. 

Hmm, is this a bug in the expression compiler or is this a bug in the C# compiler? The [LeftShift](https://msdn.microsoft.com/en-us/library/bb360628(v=vs.110).aspx) documentation doesn't say anything about this so one could conclude that it's the C# compiler obligation to generate the necessary `and`, the same way it does when it emits IL.

**Comment by VSadov** [comment]
more interestingly the repro prints different results for me only on x86 /o+

**Comment by VSadov** [comment]
IL spec says:
```
III.3.58 shl – shift integer left
. . . 
The return value is
unspecified if shiftAmount is greater than or equal to the width of value
```
So this is a bug in the ET compiler. It needs to mask or the op will result in undefined behavior

**Comment by bartdesmet** [comment]
Also, the C# compiler emitting the And node would be a breaking change and it would not be something an expression analyzer would expect to see.

Sent from my Windows Phone
________________________________

**Comment by VSadov** [comment]
@bartdesmet - yes, that is correct. Changing ET shape is a breaking change. No need to look far for examples.
https://github.com/dotnet/roslyn/issues/4471 - that is basically a reintroduction of a subtle semantical bug, just to keep clients from breaking over changes in the tree shape.

**Comment by mikedn** [comment]
> more interestingly the repro prints different results for me only on x86 /o+

On x86 a helper function is used to implement 64 bit shifts while on x64 the `shl` instruction is used, those 2 have different behaviors. You'll probably encounter differences on ARM as well.

> Changing ET shape is a breaking change.

Well, changing the expression compiler is a breaking change as well. But there's no way to fix this without breaking something and changing the expression compiler does seem less risky than changing the expression shape.
