### ISSUE TITLE
Microsoft.XmlSerializer.Generator is missing "--compiler" flag

### ISSUE THREAD

**Issue by christiantinauer** [dotnet/corefx#31507]
With sgen.exe it is possible to pass flags to the compiler for strong name signing the assembly. I wasn't able to find a similiar functionality in Microsoft.XmlSerializer.Generator. Can this be added? Or should I use a different approach like [StrongNameSigner](https://www.nuget.org/packages/Brutal.Dev.StrongNameSigner/)?

Best regards,

Christian

**Comment by yujayee** [comment]
Hi @christiantinauer, thank you for your suggestion! We will take this as a feature request. 😃  
For now, you may need to use other approaches. You can find some useful information [here](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-sign-an-assembly-with-a-strong-name). The StrongNameSigner you mentioned is not released by Microsoft so we are not responsible for maintaining it.

**Comment by christiantinauer** [comment]
Hi @yujayee, is it possible to extend the Microsoft.XmlSerializer.Generator.targets file to take
`<SignAssembly>...</SignAssembly>
<AssemblyOriginatorKeyFile>...</AssemblyOriginatorKeyFile
<DelaySign>...</DelaySign>`
of the .csproj into account? Maybe in the same way it is done for the .csproj DLL/EXE? I am not exactly sure what is done with this information and how it is used when building the project.

**Comment by yujayee** [comment]
@christiantinauer Yes it is possible and we will definitely consider adding this functionality. Thanks!

**Comment by danstur** [comment]
@yujayee What is the policy of this project with regards to accepting pull requests by the public? I'm thinking of implementing this in a fork myself (it seems reasonably simple to support on first glance - pass the path to the key and the delaysign true/false values to the executable) and if there's interest I might as well do it publicly on GitHub instead of our on-premise TFS.

**Comment by christiantinauer** [comment]
@danstur I would be happy if you could do that publicly on GitHub.

**Comment by Lxiamail** [comment]
@danstur this repro takes contribution from the communicate. [Here](https://github.com/dotnet/corefx/wiki/New-contributor-Docs#contributing-guide) is the new contributor doc, and [here](https://www.contributor-covenant.org/) is the contributor covenant. Thank you for considering contribution!

**Comment by yujayee** [comment]
Pr #36085 merged. Closing this issue.
Users will be able to modify the sgen command parameters using msbuild properties in their csproj file like the following:
```
<PropertyGroup>
    <SGenReferences>C:\myfolder\abc.dll;C:\myfolder\def.dll</SGenReferences>
    <SGenTypes>SgenTestProgram.MyType1;SgenTestProgram.MyType2</SGenTypes>
    <SGenProxyTypes>false</SGenProxyTypes>
    <SGenVerbose>true</SGenVerbose>
    <SGenKeyFile>mykey.snk</SGenKeyFile>
    <SGenDelaySign>true</SGenDelaySign>
</PropertyGroup>
```
For compiler options, we support `SGenKeyFile`, `SGenKeyContainer` and `SGenDelaySign`
