### ISSUE TITLE
Does System.ComponentModel.Annotations/src/Resources/Strings.resx Support Localization?

### ISSUE THREAD

**Issue by kinshines** [dotnet/corefx#31503]
The current validation message in System.ComponentModel.Annotations/src/Resources/Strings.resx is only support English. Does any plan to support other language? such as Chinese or French?

**Comment by karelz** [comment]
I don't think we plan localization for CoreFX - @danmosemsft?

**Comment by kinshines** [comment]
Yes,I have solved out this problem with **ModelBindingMessageProvider**,thanks for your concerns

**Comment by danmosemsft** [comment]
Right we have no current plans to localize messages in corefx. Sounds like you can close this?
