### ISSUE TITLE
CurlHandler supports only ClientCertificateOption.Manual

### ISSUE THREAD

**Issue by kapilash** [dotnet/corefx#3151]
Today CurlHandler supports only clientCertificateOption.Manual. Now with the availability of cross platform X509Store, CurlHandler must support ClientCertificateOption.Automatic as well.

**Comment by vijaykota** [comment]
Changing milestone to RTM since the code changes are slightly risky to take for RC1. Also does not meet the RC1 bug bar

**Comment by vijaykota** [comment]
See #4562 for adding this support

**Comment by kapilash** [comment]
Fix for libcurl with openssl has gone in. But there are other ssl backends out there for which curlHandler continues to throw platform not supported exception.

**Comment by vijaykota** [comment]
PlatformNotSupportedEx for other SSL backends was agreed upon in offline conversations. This issue can be reopened if we want to add the support in future.
