### ISSUE TITLE
Api Proposal: File.Move(string,string, bool) overload

### ISSUE THREAD

**Issue by mburbea** [dotnet/corefx#31511]
The proposal is to add the following member:
```cs
class File {
       public static void Move(string sourceFileName, string destFileName, bool overwrite);
}
```
The reason is to solve a current frustration, that when calling the `File.Move(string, string)` method, an exception is thrown if the file exists. E.g. You have to check if the file exists before overriding it.

On windows, `File.Move` internally uses [`Kernel32.MoveFileExW()`](https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-movefileexw) function  which has a flag that can be passed `MOVEFILE_REPLACE_EXISTING` to allow you to override an existing file. Currently, the only flag passed is `MOVEFILE_COPY_ALLOWED`

As an alternative, a developer could use the the following helper method.
```cs
public static void MoveOrOverride(string sourceFileName, string destFileName)
{
     if (File.Exists(destFileName))
     {
          File.Delete(destFileName);
     }

     File.Move(sourceFileName, destFileName);
}
```
But this is slower, and could still fail if run in a multi-threaded environment where more than one thread is trying to write to this destination file location.

Inexplicably this API is available through the visual basic helper apis. The equivalent of `File.Move` the function `Microsoft.VisualBasic.FileIO.FileSystem.MoveFile` has an override flag.

**Comment by joshfree** [comment]
@JeremyKuhne

**Comment by JeremyKuhne** [comment]
I'm fine with this. Replace() does this, but requires being on the same volume. MoveFile doesn't seem to have the same constraint. We should probably set MOVEFILE_WRITE_THROUGH as well.

**Comment by JeremyKuhne** [comment]
`bool overwrite` should be the param to match `File.Copy`. Can you tweak the signature? Then I'll mark it ready for review.

**Comment by mburbea** [comment]
@JeremyKuhne, Done.
`File.Replace()` requires you to have the destination file so i don't think its the same thing.
e.g.
```cs
using(var f = new FileStream("test.txt", FileMode.Create)){ };
File.Replace("test.txt", "clearly_not_a_real_file", null);
```
Throws the following error: `Unable to find the specified file.`

I believe this should be atomic on NTFS for the same volume, but I could of course be wrong.

**Comment by JeremyKuhne** [comment]
@mburbea You are right, my bad.

**Comment by terrajobst** [comment]
Makes sense. A few points:

* We should probably add corresponding APIs to `FileInfo` and `DirectorInfo`.
* Can this be implemented on Mac/Linux/Unix?

**Comment by jbhensley** [comment]
Looks pretty easy for files on the Windows side, which I'd be happy to do.

Adding to `DirectoryInfo` might be tricky. Docs for `MOVEFILE_REPLACE_EXISTING` says ["This value cannot be used if lpNewFileName or lpExistingFileName names a directory"](https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-movefileexw).

My *nix knowledge is more limited. I believe your approach is to use partial classes for platform-specific code, but I'm not seeing where non-Windows IO is implemented. If you have any pointers on where to find, I could take a look.

**Comment by jbhensley** [comment]
Opened PR with changes for `File.Move` and `FileInfo.MoveTo`. We're passing on Windows/Mac/Linux (Linux arm64 release is still running right now, but `System.IO.FileSystem` tests all passed already). I will say that I basically reverse-engineered the *nix side by looking at source control history, so we'll want an expert set of eyes on that.

My cross-plat voodoo is a bit weak with these two tests, which both fail to see the new overloads I added:

- NETFX x86 Release Build
- Packaging All Configurations x64 Debug Build

Any suggestions? Sorry, but I really am fairly new to corefx.
