### ISSUE TITLE
HTTP2: Receiving a frame on a closed stream should not close the connection

### ISSUE THREAD

**Issue by rmkerr** [dotnet/corefx#31514]
According to the spec, any (non-priority) frame received after a RST_STREAM frame should be treated as a (recoverable) _stream_ error:
```
An endpoint MUST NOT send frames other than PRIORITY on a closed stream. An endpoint that 
receives any frame other than PRIORITY after receiving a RST_STREAM MUST treat that as a
stream error (Section 5.4.2) of type STREAM_CLOSED.
```
The current implementation treats this error as a _connection_ error, and closes the underlying socket. For reliability reasons we should consider this error recoverable, and allow the other streams on the connection to continue.

**Comment by davidsh** [comment]
>For reliability reasons we should consider this error recoverable

What should we do with this error?  Ignore it?  Log it?  It seems we don't have any other mechanism to surface this error to the API calls of HttpClient.  My guess is we should just log the error and ignore it.

**Comment by rmkerr** [comment]
I agree that we should log it. The spec also requires that we send the server a RST_STREAM frame notifying it of the error. From [section 5.4.2](https://httpwg.org/specs/rfc7540.html#StreamErrorHandler):
```
A stream error is an error related to a specific stream that does not affect processing of other 
streams.

An endpoint that detects a stream error sends a RST_STREAM frame (Section 6.4) that contains the
stream identifier of the stream where the error occurred. The RST_STREAM frame includes an 
error code that indicates the type of error.
```

**Comment by geoffkizer** [comment]
Note that the spec also says in section 5.1, re streams in the "idle" state:

> Receiving any frame other than HEADERS or PRIORITY on a stream in
this state MUST be treated as a connection error (Section 5.4.1)
of type PROTOCOL_ERROR.

**Comment by geoffkizer** [comment]
To expand on my last comment: @rmkerr, in the case you're looking at, are we actually dealing with a closed (not idle) stream? There's not enough info in the description for me to determine what you're actually doing to cause the connection error. There is some code to try to generate a stream error (i.e. RST_STREAM and keep the connection alive) at least in certain cases. Are we not hitting this code, or is the code doing the wrong thing here?

**Comment by geoffkizer** [comment]
@rmkerr Thanks, that's helpful info. It may be related to the RST_STREAM. It would be interesting to see if what happens with a stream that closes gracefully (i.e. sends a complete response rather than RST_STREAM).

Either way, I'm making a bunch of changes related to this, so we can test again once those are complete...
