### ISSUE TITLE
System.Uri treats "\\.." differently than System.IO.Path

### ISSUE THREAD

**Issue by mikeharder** [dotnet/corefx#31524]
`System.Uri` treats `\\..` differently than `System.IO.Path`.  Here's the repro code:

```
var path = @"C:\dir\\..\file.txt";
var fullPath = Path.GetFullPath(path);
var uri = new Uri(path);

Console.WriteLine($"path\t\t\t\t{path}");
Console.WriteLine($"Path.GetFullPath(path)\t\t{fullPath}");
Console.WriteLine($"(new Uri(path)).LocalPath\t{uri.LocalPath}");
```

Which prints:

```
path                            C:\dir\\..\file.txt
Path.GetFullPath(path)          C:\file.txt
(new Uri(path)).LocalPath       C:\dir\file.txt
```

This behavior is consistent across both .NET Framework and .NET Core, so I doubt the behavior can be changed now due to compatibility, but I wanted to report the issue for awareness.

**Comment by karelz** [comment]
@rmkerr any thoughts?

**Comment by rmkerr** [comment]
The behavior of System.Uri here seems to be in line with the spec, since "\\" is treated as just another (empty) path segment and is removed by the double period. It may be that the Windows path spec defines a different behavior, but even so I don't think this should be considered a bug in URI. 

@JeremyKuhne does the System.IO.Path behavior here look right to you?

**Comment by JeremyKuhne** [comment]
`Path` behavior is correct.  `GetFullPath` is supposed to match Win32 normalization, which collapses multiple separators and flips forward slashes. As a matter of fact, Windows itself is doing this normalization directly now in Core.

@rmkerr an input local path like this doesn't have a scheme. It's arguable that we should normalize identifiable local paths `[A-Z]:` under `GetFullPath` rules, until you realize it would be hard to identify a path as local on Unix. I think we should add guidance to the docs to call `Path.GetFullPath` on local paths before wrapping in a `Uri` to avoid syntactical confusion like this. Thoughts?

**Comment by mikeharder** [comment]
>  I think we should add guidance to the docs to call Path.GetFullPath on local paths before wrapping in a Uri to avoid syntactical confusion like this.

This is exactly the fix/workaround we used in our code: https://github.com/aspnet/websdk/pull/390/files

**Comment by davidsh** [comment]
This exact issue came up while analyzing this issue: https://github.com/Microsoft/msbuild/issues/4335#issuecomment-488125520

This behavior is "by-design" for System.Uri.

See the issue linked above and:
https://davescoolblog.blogspot.com/2011/11/uri-empty-path-segments-matter.html
