### ISSUE TITLE
DateTime => Timestamp

### ISSUE THREAD

**Issue by Varorbc** [dotnet/corefx#31534]
this class [DateTime](https://github.com/dotnet/corefx/blob/3b24c535852d19274362ad3dbc75e932b7d41766/src/Common/src/CoreLib/System/DateTime.cs)，Please add a DateTime convert to Timestamp and Timestamp convert to DateTime method

**Comment by GalaxiaGuy** [comment]
There is already `ToUnixTimeSeconds` and `FromUnixTimeSeconds` on `DateTimeOffset`.

Since a timestamp represents an instant in time, converting from a `DateTime` directly is not ideal:

https://blog.nodatime.org/2011/08/what-wrong-with-datetime-anyway.html

**Comment by Varorbc** [comment]
thanks@GalaxiaGuy
