### ISSUE TITLE
Proposal: Required attribute and empty collections

### ISSUE THREAD

**Issue by ZBAGI** [dotnet/corefx#31531]
By **requiring** (aka. `RequiredAttribute`) something, most of the people expecting it to have a processable value. That is the case with string (by default empty strings are treated as missing data) however this functionality is exclusive to strings. I propose to add same functionality for collections to keep functionality consistency cross different types.

## Example / Usage

When creating messages to users, you may want to have list of recipients. In this scenario message needs to have at least one or more recipient. By **requiring** `List<int>` default behaviour should not allowed empty list.
```csharp
var messageRecipients = new List<int>();
var requiredAttribute = new RequiredAttribute();
if(requiredAttribute.IsValid(messageRecipients)) // Should be false
```
To allow empty list - thus failing only when value is null, property `AllowEmptyCollections ` needs to be set to true:
```csharp
var messageRecipients = new List<int>();
var requiredAttribute = new RequiredAttribute() {
    AllowEmptyCollections = true
};
if(requiredAttribute.IsValid(messageRecipients)) // Should be true
```
**Example for MVC**

If query did not contain `recipientsIds` or `recipientsIds` is an empty collection:
```csharp
public async Task<IActionResult> CreateMessage([FromBody, Required] List<int> recipientsIds)
{
if(ModelState.IsValid) // Should be false
```
And to allow empty collection:
```csharp
public async Task<IActionResult> CreateMessage([FromBody, Required(AllowEmptyCollections = true)] List<int> recipientsIds)
```
## Pull Request
#31508

**Comment by ZBAGI** [comment]
## Open question
Currently by default empty collections are allowed as there is no mechanism to control that (via `RequiredAttribute`), so maybe for backward compatibility `AllowEmptyCollections` should be `true` by default? On the other hand i feel that *Requiring* something should mean that value of it is *required* and have to be provided (as is the case with string).

**Comment by ajcvickers** [comment]
My opinion: probably not worth it. We certainly can't change the default--that would be a massive breaking change--so we could add the flag as allowed by default, which would then allow applications to turn this on if needed, but typically the contents of the collection would still need be validated anyway, so it seems unlikely that this would be a one-step fix in most cases. Also, some components reason about the data annotations for things other than validation--for example EF modeling. In these cases two problems can arise--first, what is the meaning of specifying the flag in such places? Second, even if it has some useful meaning, that won't be applied unless the code consuming the annotation is changed to recognize it. It is unlikely that consuming code will change, which means we have additional semantics on the attribute that is now ignored. So all in all, it doesn't feel like there is net benefit from taking a change here.

**Comment by ZBAGI** [comment]
Thank you @ajcvickers for your opinion. In most of scenarios data have be validated manually - eather by searching database or applying more complex rules. And validation attributes are there just to filter out the obviously incorrect requests so application can deal with correct requests from the get go. By following that logic all validation related data annotations are useless - at least from validating perspective. `NULL` is already annoying to deal with, so making `required` attribute filter it will help a lot no matter if this have any meaning in other than validating. Besides that this behaviour is already implemented into string, why should it behave differently with other simple types ?

**Comment by ajcvickers** [comment]
@ZBAGI If we were designing from scratch, then it wouldn't behave differently from string. However, the default behavior is that they do behave differently, and that cannot be changed, so the question is not the value of making them work the same, but the value of adding a switch and a new behavior.
