### ISSUE TITLE
System.IO.FileSystem.Tests leaves behind temp directories that are nearly impossible for mortals to delete.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#3154]
Repro:
  1. msbuild System.IO.FileSystem.Tests.csproj -t:test
  2. Try to clean out your %TMP% directory.
  3. Watch every normal method of deletion fail due to S.I.F.T. leaving behind massively subnested GUID-named directory trees that purposefully blow past the MAXPATH restriction.

I ended up having to write code to get rid of this stuff.

S.I.F.T. should clean up after itself.

**Comment by stephentoub** [comment]
cc: @JeremyKuhne
