### ISSUE TITLE
Add Win32 File.Encrypt/Decrypt() implementation

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#31544]
It shows up in the ARM/x86 whitelist for OneCore.  (It is in the UniversalDDIs as described [here](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/validating-universal-drivers).)

We still need to throw for Unix. Move the implementation to `FileSystem`. This will require making The `FileSystem` implementation for Windows a partial class. We need a `FileSystem.Win32.cs` and `FileSystem.WinRT.cs` that implement this specific call (Win32) or throw not supported (WinRT). We do the same thing for `FileSystemEnumerator`.

**Comment by MarcoRossignoli** [comment]
@JeremyKuhne is there a way to run remote invoker "as user"?Or test with `netuser /add` and runas a process to `type` encrypted file?Tests run elevated?I could try to work on this if you want!

**Comment by JeremyKuhne** [comment]
I don't think you need elevated to Encrypt/Decrypt. We currently do outerloop as admin (at least last I checked).  You can condition on `PlatformDetection.IsWindowsAndElevated` if you need to know.

Windows implicitly decrypts the file if you're the right user. If you want to check that it is actually unusable you would need to launch as another limited user, which I don't think we've tackled yet.

I had hoped that I could figure out if it was possible to spawn a thread and impersonate without going to another process, but I haven't had the time to fully investigate/understand the possibilities there.

I'll assign it to you, just implementing the code and doing basic tests for notsupported or doesn't throw and reading/writing works is the bar. If you want to go for testing not accessible from a different user that would be fantastic, but don't dead-end on it.

**Comment by MarcoRossignoli** [comment]
@JeremyKuhne you can re-open and reassign to me if you want.
