### ISSUE TITLE
XmlSerializer does not support ulong enums

### ISSUE THREAD

**Issue by Eilon** [dotnet/corefx#31542]
_From @jack0x539 on August 1, 2018 14:58_

```c#
public enum MessageDestination : ulong 
{
    None = 0,
    /* ... */
    All = ulong.MaxValue
}

...

public class Message
{
    public MessageDestination Destination { get; set; }
    /* ... */
}

...

XmlSerializer serialiser = new XmlSerializer(typeof(Message));
```

Exception thrown "Value was either too large or too small for an Int64.". I'm not sure why enum reflection for XML serialisation assumes that all enum values will be convertable to int64, when it's perfectly legit to have an enum extend uint64.

_Copied from original issue: aspnet/Home#3375_

**Comment by huanwu** [comment]
We don't support ulong in enum type since it is not a CLS-compliant type. To support it, it will require us to expose ulong on our public APIs.

**Comment by Lxiamail** [comment]
closing the issue
