### ISSUE TITLE
Add macOS 10.14 to the RID graph

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#31547]
https://www.apple.com/macos/mojave-preview/

10.14 needs to be added to the pkg/Microsoft.NETCore.Platforms RID graph

**Comment by joshfree** [comment]
re-opening bug for /release/2.1 tracking purposes

**Comment by vivmishra** [comment]
Approved for 2.1.5

**Comment by danmosemsft** [comment]
Moving label to PR per new process

**Comment by karelz** [comment]
Fixed in release/2.1 branch in PR #31632, it will be part of 2.1.5 release.
