### ISSUE TITLE
Building native shims from top level folder

### ISSUE THREAD

**Issue by janhenke** [dotnet/corefx#3155]
Currently there is no top level way to build the native shims. One has to call src/Native/build.sh. Since the shims are needed for CoreFX to work correctly on Unix systems, it would be helpful to provide some intuitive way of invoking the build from the top level.

I see two obvious ways to archive this:

1. Create a top level build-native.sh which starts the build in src/Native
2. Have the top level build.sh invoking building the shims in addition to the manages assemblies.

I am in favour of option 2. How are general ideas?

cc @nguerrera @sokket @stephentoub

(By mistake I opened this issue on coreclr as ~~dotnet/coreclr#1527~~ at first)

**Comment by nguerrera** [comment]
I like (2).

**Comment by nguerrera** [comment]
I've had (2) in the back of my mind. Until recently, I'd not had success building managed code on *nix, which is why I never bothered tweaking build.sh. 

@janhenke, were you thinking of implementing this?

**Comment by nguerrera** [comment]
cc @mmitche @chcosta for thoughts on any impact on CI and official builds.

**Comment by janhenke** [comment]
It should be simple to do, indeed I was thinking about implementing. But before starting it, I want to discuss it, to make sure nobody objects to that change.

**Comment by mmitche** [comment]
I'm in favor of #2 also.

**Comment by sokket** [comment]
That's a good point @nguerrera, what's the status of building the managed code in *nix and OS X?

**Comment by janhenke** [comment]
If we are going for option 2, it would good to know if we need to keep the ability to build the native shims separately.
I would be in favour of dropping the separate ``src/Native/build.sh``` in favour of using the top level only.

Building CoreFx works on Linux. On FreeBSD it seems broken right now, but I did not find the cause yet. I have no OS X system to test.

**Comment by sokket** [comment]
If it works on OS X that would definitely improve my workflow :) I'll try to take a look later today and see if it works.

**Comment by nguerrera** [comment]
I'd like to retain the ability to build the native shims separately. Either by keeping src/Native/build.sh and shelling it out to root or having an arg for it in root build.sh. I don't want to be slowed down by a long or flaky managed build if I just tweaked the native code.

**Comment by stephentoub** [comment]
Ditto. We need to keep the ability to just build the native components, and to do so without needing installed any of the prerequisites necessary to build the managed components.

**Comment by janhenke** [comment]
So it seems to be consensus:

Merge the native build.sh with the top level build.sh. I would add two optional arguments ```nativeonly``` and ```managedonly```, which causes just the mentioned part to be build (if both are passed, the second one is ignored). Does that sound good to everybody?

**Comment by nguerrera** [comment]
How about:
```
./build.sh native -> native only
./build.sh managed -> managed only
./build.sh -> managed + native
./build.sh managed native -> managed + native
```
Less typing and makes the whole first-vs-last-one-wins moot.

**Comment by janhenke** [comment]
Looks good to me.

**Comment by nguerrera** [comment]
With that said, removing src/Native/build.sh will break CI so you'll have to coordinate with @mmitche on the change. Maybe have a grace period where src/Native/build.sh calls ../../build.sh native (or vice versa) to make it easier to coordinate.
