### ISSUE TITLE
Interop+Crypto+OpenSslCryptographicException after upgrading to .Net Core 2.1

### ISSUE THREAD

**Issue by tidusjar** [dotnet/corefx#31561]
Hello,

It seems that after upgrading to .net core 2.1 my aspnet core app is throwing lots of exceptions on centos 7 with the following exception and stack trace:
https://gist.github.com/samwiseg00/e23fb96a9198061111c55b515724bc31

If the aspnet core app is running under root then this issue does not appear to happen.

here are some related packages installed on the machine:
```
Package lttng-ust-2.4.1-4.el7.x86_64 already installed and latest version
Package libcurl-7.29.0-46.el7.x86_64 already installed and latest version
Package 1:openssl-libs-1.0.2k-12.el7.x86_64 already installed and latest version
Package krb5-libs-1.15.1-19.el7.x86_64 already installed and latest version
Package libicu-50.1.2-15.el7.x86_64 already installed and latest version
Package zlib-1.2.7-17.el7.x86_64 already installed and latest version
```

This is the csproj with all the dependancies (Using latest everything)
https://github.com/tidusjar/Ombi/blob/develop/src/Ombi/Ombi.csproj

Please note that this was not an issue on .Net Core 2.0

Related issue https://github.com/tidusjar/Ombi/issues/2422#issuecomment-410001162

**Comment by filipnavara** [comment]
What are the values of environment variables `SSL_CERT_DIR` and `SSL_CERT_FILE` on your system?
If none of them are set, what does `openssl version -d` print? It should output `OPENSSLDIR` path. Is there $OPENSSLDIR/cert.pem on the system? What are the contents of $OPENSSLDIR/certs/?

**Comment by filipnavara** [comment]
My wild guess is... $OPENSSLDIR/certs/ contains some file(s) that you don't have permission to read, or symbolic links that point to some non-existant files.

**Comment by samwiseg00** [comment]
No results for `SSL_CERT_DIR` or `SSL_CERT_FILE`
```
openssl version -d
OPENSSLDIR: "/etc/pki/tls"
```
This is a base Centos 7 install. I do not think that would be the case since there would be so many other things that would not work. 

Also this was not an issue with .Net Core 2.0 with the same user. If it did not have access to the cert store wouldn't there have been issues there as well?

I also made sure the the ca-certificates were up to date 
`Package ca-certificates-2018.2.22-70.0.el7_5.noarch already installed and latest version`

**Comment by filipnavara** [comment]
I think you didn't hit it on .NET Core 2.0 because there was different backend implementation for `System.Net.Http`, so this code path didn't exist. The OpenSSL backend worked largely the same and the issue would probably be reproducible on CoreFX 2.0.

**Comment by filipnavara** [comment]
IIRC you can switch to the old HTTP client implementation using `DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0` environment variable.

**Comment by samwiseg00** [comment]
Will that be deprecated when .net2.0 gets retired in October?

**Comment by davidsh** [comment]
>IIRC you can switch to the old HTTP client implementation using DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0 environment variable.
"Will that be deprecated when .net 2.0 gets retired in October?"

No.  We don't immediate plans to remove the AppContext or Environment variables switches to fall back to the older WinHttpHandler/CurlHandler HTTP stacks.  However, at some point we will.

cc: @karelz @danmosemsft @geoffkizer

**Comment by filipnavara** [comment]
I'd still like to have some confirmation whether the workaround helps with the issue. As for the original problem, can you verify that there are no stale symlinks in /etc/pki/tls/certs? I believe there was some other issue tracking that problem, but couldn't quite find it now.

**Comment by samwiseg00** [comment]
@filipnavara that does seem to resolve the issue. That is a good workaround for now. 

@tidusjar might want to know root cause though since at some point he older WinHttpHandler/CurlHandler HTTP stacks will go away.

**Comment by tidusjar** [comment]
Interesting, so that's good for a work around but are we going to investigate and potentially fix this issue? Especially since .net core is moving on and at some point the old CurlHandler will be removed?

**Comment by bartonjs** [comment]
Sounds like yet another duplicate of #29942. The fix is in 2.1.3, which has not shipped yet. (Seems rather like #30147, specifically)

Somewhere in /etc/ssl/certs there's a file that your process can't read (no permissions, or broken symlink). If you can solve that, the problem will go away.

**Comment by wfurt** [comment]
2.1.3 (and .4) is out. Should we close this?

**Comment by karelz** [comment]
Duplicate of #29942
