### ISSUE TITLE
<access sslFlags=“Ssl.SslRequireCer”> in .net core 2.1

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#31560]
_From @junaidahmed92 on August 2, 2018 8:25_

I am converting my app from .net framework to .net core 2.1. Now I am facing two issues

1) In .net framework we could use `HttpClientCertificate` cert = Request.ClientCertificate;` So how can we use Request.ClientCertificate in .net core.

2) In .net framework we could set location config like

`<location path="MyPath">
    <system.webServer>
      <security>
        <access sslFlags="Ssl.SslRequireCert,SslNegotiateCert,Ssl128" />
      </security>
    </system.webServer>
  </location>`
I want to use `<access sslFlags="Ssl.SslRequireCert,SslNegotiateCert,Ssl128" />` in net core. How can I do these 2 things. Any help?

_Copied from original issue: dotnet/core#1834_

**Comment by davidsh** [comment]
cc: @Tratcher

**Comment by junaidahmed92** [comment]
Thanks for the answer. My app is deployed on local IIS

**Comment by davidsh** [comment]
Sounds like the question has been answered.
