### ISSUE TITLE
TcpListener should use cancel tokens

### ISSUE THREAD

**Issue by jjxtra** [dotnet/corefx#31586]
Please provide cancel tokens to the async methods of TcpListener. It's possible to wrap a tcp listener with cancel token methods and call stop but this feels like an unnecessary step, and one that is not easy for all people to understand.

**Comment by GSPP** [comment]
This is a duplicate of [Add a clean way to cancel a long-running Socket operation (e.g. accept or connect)]( https://github.com/dotnet/corefx/issues/5749).

**Comment by karelz** [comment]
Duplicate of #5749
