### ISSUE TITLE
Why doesn't ReadOnlySpan.ToString return string.empty when length == 0?

### ISSUE THREAD

**Issue by cdmihai** [dotnet/corefx#31617]
Doesn't lool like the implementation checks for zero length:
https://github.com/dotnet/corefx/blob/ab27e64721496ab7404fd52d8d7720db572fc2f4/src/Common/src/CoreLib/System/ReadOnlySpan.Fast.cs#L216-L227

I am thinking of adding an extension method which does this. Any reason / gotchas why the implementation doesn't do it? AFAIK ToString does not have any contract to always return a new string.

**Comment by jkotas** [comment]
I do not understand your suggestion. Where do you think we need a check for zero length?

**Comment by jkotas** [comment]
Ah ok, I see what you mean.

All String constructor have check for empty zero length already. When you do `new string((char*)…, …, 0)`, it is always going to return the same string object. We do not need to duplicate it here.
