### ISSUE TITLE
HTTP/MongoDB request delayed for five seconds after application is idle for five minutes

### ISSUE THREAD

**Issue by tomcon21** [dotnet/corefx#31628]
Hi,

We have a number of applications running on **Ubuntu 16.04** with **DotNet Core 2.1**.

We have noticed that when the application is idle for a period of time (Five minutes in this case), the first outgoing HTTP post request has a five second delay before the request is sent from the application. 
When the application is under heavy load the HTTP times are as expected.
Similarly we are seeing the same issue occur with the C# MongoDB driver (Version 2.4.4, targets dotnet standard 1.5). Again if the application is idle and a database call occurs we see the same behaviour.

To reproduce this issue we invoke our application every five minutes where it sends a HTTP request to another one of our services. Using Metrics and Wireshark we have seen that every 30 to 40 minutes a five second delay occurs where the request is hanging in the application.
We have not been able to reproduce this behavior on Windows.

The regularity of these occurrences and the five second delay might point to something running on the OS. We have checked cron jobs and nothing looks out of the ordinary, other Ubuntu VMs are built off of the same template and these times are not seen from VMs running other technologies. Also From viewing the packet capture in Wireshark we have noticed quiet a lot of ARP traffic in between the application making out of process calls, this ARP traffic is quiet slow (seconds) too so may have an impact on the times we are seeing.

Has anyone else seen similar behaviour?

**Comment by wfurt** [comment]
Is there any networking gear or firewalls  between your app and the server?
Do you have packet filter configured on either side? 
Do you have packet capture for  the communication? 
I don't think the arp is interesting just HTTP(s)

**Comment by wfurt** [comment]
You can take a look at http://sf-alpha.bjgang.org/wordpress/2012/08/linux-prefer-ipv4-over-ipv6-in-dual-stack-environment-and-prevent-problems-when-only-ipv4-exists/ 
If IPv6 is advertised but broken it could certainly cause problems. 

Note that DNS queries are not cached. So you may see it every time when client needs new connection.

**Comment by tomcon21** [comment]
The problem seemed to occur when the application was idle for 60+ seconds where our client applications running on **Ubuntu** made requests to our **Windows** DNS server.

_Seen the same packet capture traffic as described in this blog:_
http://philippecloutier.com/blogpost28-dig-1-and-other-DNS-clients-sometimes-taking-5-seconds-to-
return-the-results-of-a-local-query

We subsequently added a new **Ubuntu** DNS server using bind9 to interact with client application and the delay has yet to be seen.
Hopefully this issue will help anyone else moving from Windows environment to Ubuntu.
