### ISSUE TITLE
Replace TRAVE to TRACE_VERBOSE throughout the code.

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#3163]
__Workitem:__
1. Ensure that all instances of `TRAVE` are replaced by `TRACE_VERBOSE` throughout the code base.
2. Ensure that no other name is used to enable verbose tracing. (If others exist, they should be replaced by `TRACE_VERBOSE`.)

----
__Initial Design Discussion__:

In System.Net code we have debug-only verbose tracing guarded by a variable named `TRAVE` (TRAce VErbose).

The following have been brought up during PRs for this code:

1. Standardize a single such name across corefx
2. Change the name (seems like a typo)

Please add your suggestions and then convert this to a code issue to track changes across the entire repo.

**Comment by nguerrera** [comment]
Anything wrong with `TRACE_VERBOSE`?

**Comment by bartonjs** [comment]
`TRACE_VERBOSE` sounds good to me...

**Comment by CIPop** [comment]
+1 on the name. Changing the name in the current System.Net.Security PR.

Keeping the issue around to do a last scan after other contracts are in.

**Comment by CIPop** [comment]
Moving after RTM (cosmetic change). Some of the code was already changed to use TRACE_VERBOSE.

**Comment by shrayasr** [comment]
A quick search for `TRAVE` doesn't bring anything up. Maybe this issue can be closed now?

**Comment by CIPop** [comment]
Thanks @shrayasr for the reminder. Closing.

**Comment by shrayasr** [comment]
:+1: you're welcome. Cheers :blush:
