### ISSUE TITLE
PerformanceCounter.NextValue() generates memory allocations

### ISSUE THREAD

**Issue by MaxShoshin** [dotnet/corefx#31639]
`PerformanceCounter.NextValue()` generates memory allocations.
OS: Windows

To reproduce:
```c#
var counter = new PerformanceCounter(".NET CLR Memory", "Allocated Bytes/sec", instance);

while (true)
{
       var current = counter.NextValue();
       var gc0 = GC.CollectionCount(0); //Grows endlessly (not on every iteration, but grows)

       Console.WriteLine($"Allocated bytes/sec: {current:0}, GC0 count: {gc0}");
       Thread.Sleep(500);
 }
```

Windows implementation of `PerformanceCounter` uses method `object RegistryKey.GetValue(string name)`  which is internally [allocate at least ~64Kb on every call](https://github.com/dotnet/corefx/blob/b492409b4a1952cda4b078f800499d382e1765fc/src/Microsoft.Win32.Registry/src/Microsoft/Win32/RegistryKey.Windows.cs#L557)

I expect that `PerformanceCounter.NextValue()` will not generate memory allocations on each call. It is significant if we ask about next value several performance counters  (100, 200, etc).

**Comment by danmosemsft** [comment]
We could start by changing to reuse an array from ArrayPool. Any interest in offering a PR?

**Comment by Clockwork-Muse** [comment]
Well, you could pool the initial loads (that section is part of a growing loop), then copy for the return...

**Comment by danmosemsft** [comment]
Hmm, I was thinking to return the too small buffers to pool then give the final one to the caller instead of back to the pool. But since it came from the pool that buffer could be too large to reasonably return.

In this case of heavy allocations, how large is the data typically? Is starting with 65000 and doubling a reasonable strategy?

**Comment by benaadams** [comment]
[MSDN example](https://docs.microsoft.com/en-us/windows/desktop/api/winreg/nf-winreg-regqueryvalueexa) uses starting buffer of 8kB and increments in 4kB; though don't know big the general data is
```c
#include <windows.h>
#include <malloc.h>
#include <stdio.h>
#define TOTALBYTES    8192
#define BYTEINCREMENT 4096


void main()
{
    DWORD BufferSize = TOTALBYTES;
    DWORD cbData;
    DWORD dwRet;
    PPERF_DATA_BLOCK PerfData = (PPERF_DATA_BLOCK) malloc( BufferSize );
    cbData = BufferSize;

    printf("\nRetrieving the data...");

    dwRet = RegQueryValueEx( HKEY_PERFORMANCE_DATA,
                             TEXT("Global"),
                             NULL,
                             NULL,
                             (LPBYTE) PerfData,
                             &amp;cbData );
    while( dwRet == ERROR_MORE_DATA )
    {
        // Get a buffer that is big enough.

        BufferSize += BYTEINCREMENT;
        PerfData = (PPERF_DATA_BLOCK) realloc( PerfData, BufferSize );
        cbData = BufferSize;

        printf(".");
        dwRet = RegQueryValueEx( HKEY_PERFORMANCE_DATA,
                         TEXT("Global"),
                         NULL,
                         NULL,
                         (LPBYTE) PerfData,
                         &amp;cbData );
    }
    if( dwRet == ERROR_SUCCESS )
        printf("\n\nFinal buffer size is %d\n", BufferSize);
    else printf("\nRegQueryValueEx failed (%d)\n", dwRet);

}
```

**Comment by jkotas** [comment]
System.Diagnostics.PerformanceCounter library can directly PInvoke the registry API in the one performance sensitive place, with buffer allocated from ArrayPool.

**Comment by MaxShoshin** [comment]
I found good way (without many allocations) to read performance counters from local machine: https://github.com/vostok/sys.metrics.perfcounters
