### ISSUE TITLE
Checked multiplication of long.MinValue/long.MinValue doesn't throw on Linux when compiled with optimizations

### ISSUE THREAD

**Issue by VSadov** [dotnet/corefx#3164]
See 
https://github.com/dotnet/corefx/blob/master/src/System.Linq.Expressions/tests/BinaryOperators/Arithmetic/BinaryMultiplyTests.cs  

Test: CheckLongMultiplyTestOvf

A simple repro:

```C#
    class Program
    {
        static void Main(string[] args)
        {
            var a = long.MinValue;
            var b = long.MinValue;

            Expression<Func<long>> e =
                    Expression.Lambda<Func<long>>(
                        Expression.MultiplyChecked(
                            Expression.Constant(a, typeof(long)),
                            Expression.Constant(b, typeof(long))),
                        Enumerable.Empty<ParameterExpression>());

            Func<long> f = e.Compile();
            f();
        }
    }
```
The above sample should throw OverflowException. 
It does on Windows. 
I did not check the snippet on Linux, but in the context of the CheckLongMultiplyTestOvf exactly same code does not throw.

There could be some unintended difference in how checked long multiplication is JITted in dynamic methods...

**Comment by stephentoub** [comment]
I just verified that on Windows it throws and on Ubuntu it does not throw... printing out the result of f() prints out 0.

**Comment by stephentoub** [comment]
Simplified repro:
```
class Program
{
    static void Main()
    {
        long a = long.MinValue;
        long b = long.MinValue;
        System.Console.WriteLine(checked((long)(a * b)));
    }
}
```
When compiled with ```/o-```, this throws as expected on Linux.  When compiled with ```/o+```, this prints out 0 on Linux.

**Comment by stephentoub** [comment]
cc: @LLITCHEV

**Comment by LLITCHEV** [comment]
It could, but I didn't have this change when I tried reproducing it today. (BTW, it did not repro.) But yesterday JanV PRed some changes in the exception handling, which might have an effect on this. I talked to stephentoub today to make sure I am doing the right thing to repro it. He said he'd follow up...

**Comment by stephentoub** [comment]
I sync'd to the latest in coreclr and built a release build.  It still repros for me with the latest bits.  Specifying /o- results in an exception, specifying /o+ results in 0 being printed out.

**Comment by LLITCHEV** [comment]
This turned out to be a clang 3.5 optimizer bug that in case of MIN_LONG * MIN_LONG that results into 0 instead of generating overflow exception.

**Comment by LLITCHEV** [comment]
PR #1577 merged.
