### ISSUE TITLE
System.Security: Incorrect interop signature for DsaSign (OpenSSL)

### ISSUE THREAD

**Issue by filipnavara** [dotnet/corefx#31648]
The current code uses the following signature:

```c#
        internal static bool DsaSign(SafeDsaHandle dsa, ReadOnlySpan<byte> hash, int hashLength, ReadOnlySpan<byte> refSignature, out int outSignatureLength) =>
            DsaSign(dsa, ref MemoryMarshal.GetReference(hash), hashLength, ref MemoryMarshal.GetReference(refSignature), out outSignatureLength);
```

However, the `refSignature` parameter is output one, so I believe it should be declared as `Span<byte>`:

```c#
        internal static bool DsaSign(SafeDsaHandle dsa, ReadOnlySpan<byte> hash, int hashLength, Span<byte> refSignature, out int outSignatureLength) =>
            DsaSign(dsa, ref MemoryMarshal.GetReference(hash), hashLength, ref MemoryMarshal.GetReference(refSignature), out outSignatureLength);
```

or even better:
```c#
        internal static bool DsaSign(SafeDsaHandle dsa, ReadOnlySpan<byte> hash, Span<byte> refSignature, out int outSignatureLength) =>
            DsaSign(dsa, ref MemoryMarshal.GetReference(hash), hash.Length, ref MemoryMarshal.GetReference(refSignature), out outSignatureLength);
```

I'm still trying to figure out why `DsaSign` crashes on my machine when running the unit tests for System.Security.Cryptography.OpenSsl, so if anyone more savvy could check the interop code around it I would be very grateful. `DSASignVerify_[Array/Stream/Span].PublicKey_CannotSign` tests all get to the `DsaSign` interop call and then crash with SIGSEGV. This is on macOS Mojave DP 4, OpenSSL 1.0.2o_2 (Homebrew).

**Comment by filipnavara** [comment]
Seems like the following check in `pal_dsa.c` doesn't work on my machine (tm):

```
    if (dsa->meth == DSA_OpenSSL() && dsa->priv_key == NULL)
    {
        *outSignatureLength = 0;
        ERR_PUT_error(ERR_LIB_DSA, DSA_F_DSA_DO_SIGN, DSA_R_MISSING_PARAMETERS, __FILE__, __LINE__);
        return 0;
    }
```

In my case `dsa->meth != DSA_OpenSSL()` and `dsa->priv_key == NULL`. It proceeds further and crashes when trying to access the private key (somewhere in OpenSSL code).

**Comment by vcsjones** [comment]
I should have a Mojave mac available to me in a few hours. I'll give it a shot then with your setup.

**Comment by filipnavara** [comment]
Thanks! I'm in process of upgrading to Developer Preview 6 and Xcode 10 beta 5 (10L221o) right now to retest, will take a while. The affected machine has Xcode 10 beta (10L176w) installed. If the problem is not reproducible after the upgrade then I am fine with dismissing it. The interop signature mentioned in the original issue text should still be fixed though.

**Comment by vcsjones** [comment]
>The interop signature mentioned in the original issue text should still be fixed though.

Yes. That looks like it will crash if the `ROS<byte>` is pointing to an actual read-only segment of memory when the PAL tries to write to it.

**Comment by filipnavara** [comment]
Still getting the crash on Developer Preview 6 and updated Xcode. Steps used to reproduce:

```
brew install openssl
OPENSSL_ROOT_DIR=/usr/local/Cellar/openssl/1.0.2o_2/ ./build.sh
./build.sh src/System.Security.Cryptography.OpenSsl/
```
