### ISSUE TITLE
Add a method to get the default value from a type.

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/corefx#31646]
Currently there's no easy way to get the default value of a type if you don't know the type statically and can't use `default(T)`. The most commonly used approach is `type.IsValueType ? Activator.CreateInstance(type) : null`, but `Activator.CreateInstance` is slow. There should be a `Type.GetDefaultValue()` method.

**Comment by svick** [comment]
If the only issue with `Activator.CreateInstance` is speed, how does introducing a new method help?

In other words, either the proposed method would also be slow, in which case you didn't gain anything. Or it would be fast, but that almost certainly means `Activator.CreateInstance` could be optimized to be just as fast for this case.

**Comment by thomaslevesque** [comment]
@svick I was assuming there was a more efficient way that wasn't exposed by the public API.

For instance, this method:

```csharp
static T Default<T>()
{
    return default(T);
}
```

Produces the following IL:

```IL
.method private hidebysig static 
	!!T Default<T> () cil managed 
{
	// Method begins at RVA 0x2054
	// Code size 10 (0xa)
	.maxstack 1
	.locals init (
		[0] !!T
	)

	IL_0000: ldloca.s 0
	IL_0002: initobj !!T
	IL_0008: ldloc.0
	IL_0009: ret
} // end of method UserQuery::Default
```

which, I assume, is much more efficient than `Activator.CreateInstance()`

**Comment by ufcpp** [comment]
Certainly, `Activator.CreateInstance` is slow.
https://gist.github.com/ufcpp/928f8de383891c18d79efc8ca8df98af

**Comment by MichalStrehovsky** [comment]
`Activator.CreateInstance` won't actually give you the semantic you're looking for. It would run the default constructor (public+parameterless constructor) on the struct if there is any. You can't express default constructors on structs in C# right now so it's hard to hit it, but they've been wanting to add that to C# for a long time.

To get a `default` (all zero) boxed valuetype, you should use `System.Runtime.Serialization.FormatterServices.GetUninitializedObject`. It might be faster too because there's less work.

**Comment by thomaslevesque** [comment]
> It would run the default constructor (public+parameterless constructor) on the struct if there is any

But structs can't have an explicit parameterless constructor.
That said, `GetUninitializedObject` might indeed be faster

**Comment by jnm2** [comment]
@ufcpp Can you add `GetUninitializedObject` to https://gist.github.com/ufcpp/928f8de383891c18d79efc8ca8df98af?

**Comment by joshfree** [comment]
@AtsushiKan

**Comment by AtsushiKan** [comment]
Closing since we already have an api that addresses this. (`GetUninitializedObject`)

**Comment by thomaslevesque** [comment]
@AtsushiKan `GetUninitializedObject` is still much slower than what I'm suggesting. It's barely faster than `Activator.CreateInstance`. I'm asking for something that just does the equivalent of the `initobj` IL opcode.

**Comment by MichalStrehovsky** [comment]
@thomaslevesque If you have suggestions on how to do it, you can open a new issue in the CoreCLR repo for making `GetUninitializedObject` faster.

I don't see much room for improvement though. Pretty much all the work being done in that path is necessary:

We start here with a couple of checks:

https://github.com/dotnet/coreclr/blob/030a3ea9b8dbeae89c90d34441d4d9a1cf4a7de6/src/System.Private.CoreLib/src/System/Runtime/Serialization/FormatterServices.cs#L41-L54

Then land in native code where we do additional checks:

https://github.com/dotnet/coreclr/blob/af4ec7c89d0192ad14392da04e8c097da8ec9e48/src/vm/reflectioninvocation.cpp#L2640-L2703

And then we allocate:
https://github.com/dotnet/coreclr/blob/d4738d1e9e9b50d00023eb4caca225812cabe285/src/vm/gchelpers.cpp#L1106-L1211

**Comment by MichalStrehovsky** [comment]
If you want to get the default instance of a certain value type often, you could cache a delegate to allocate it. Something along the lines of:

```csharp
public static object GetDefault<T>() => default(T);

var d = (Func<object>)typeof(Program).GetMethod("GetDefault").MakeGenericMethod(typeof(Mine)).CreateDelegate(typeof(Func<object>));
```

And then call `d()` to do the allocation of `Mine`. I'm not sure doing this sort of caching in `GetUninitializedObject` in general would be an improvement.

**Comment by thomaslevesque** [comment]
Thanks for the detailed explanation @MichalStrehovsky!
