### ISSUE TITLE
Unit test core dumps on macOS

### ISSUE THREAD

**Issue by filipnavara** [dotnet/corefx#31650]
Currently there's a functionality in the test runner code to examine and print out core dump when unit tests crash (with SIGSEGV or similar hard faults). The functionality is restricted to Linux at present. I think it would be beneficial to implement it for macOS as well.

On macOS the core dumps have to be enabled using `ulimit -c unlimited`. Each core dump is placed in `/cores/core.<PID>`. They can be opened using `lldb`, which is already supported in the Linux code.

**Comment by danmosemsft** [comment]
@ahsonkhan

**Comment by wfurt** [comment]
note that we do not build libsosplugin for OSX. So the core and stack-trace will be limited to unmanaged code. (still better then nothing)

**Comment by filipnavara** [comment]
That's unfortunate, but managed exception are already reported properly in the test suite anyway. My concern are crashes in `System.Native` and external libraries such as OpenSSL.

**Comment by wfurt** [comment]
agreed. Saving core file is good thing. This was more a warning for who ever will try to mach Linux capabilities.

**Comment by ericstj** [comment]
@ViktorHofer should this be moved over to Arcade where the test runner lives?

**Comment by ViktorHofer** [comment]
There's a related offline discussion about generating dumps for crashes on helix machines, I'm not sure if that's sufficient for this ask. Yes, we should probably move that over as the runner lives in arcade.

**Comment by ViktorHofer** [comment]
Issue moved to [dotnet/arcade #2719](https://github.com/dotnet/arcade/issues/2719) via [**ZenHub**](https://www.zenhub.com/)
