### ISSUE TITLE
Document servicing guidelines for contributors

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#31655]
I couldn't find docs for how to prepare servicing updates. I've hunted through history to see what's been done before and have made some guesses at what I'm supposed to do. This included

* Setting PackageVersion on pkgproj for projects which need a servicing update
* Updating packageIndex.json from the last release of Microsoft.Private.PackageBaseline

Did I miss anything?

cc @weshaggard @wtgodbe

**Comment by dagood** [comment]
+cc @ericstj

**Comment by joshfree** [comment]
@safern could you assist here while others folks are out?

**Comment by safern** [comment]
Sure. I'll take care of it once I'm done with the the builds today.

**Comment by safern** [comment]
I think the only piece missing for this is: https://github.com/dotnet/corefx/pull/32168#issuecomment-420341574

**Comment by danmosemsft** [comment]
@safern seems this can be closed now,?
