### ISSUE TITLE
Rewrite xunit test methods that aren't supported with the official runner (xunit 2.4)

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#31664]
This tracks disabled tests in the codebase which need to be rewritten.

- Generic test methods
**EDIT: It showed that generic test methods are supported but are currectly broken in xunit 2.4**

**Comment by jkotas** [comment]
How many tests are affected by this?

**Comment by ViktorHofer** [comment]
It showed that generic test methods are supported but currently broken in xunit 2.4.0: https://github.com/xunit/xunit/issues/1781. About ~50 test methods are affected.
