### ISSUE TITLE
Replacement for AppDomain.CurrentDomain.DefineDynamicAssembly in netcoreapp2.1

### ISSUE THREAD

**Issue by jnm2** [dotnet/corefx#31676]
If I target netcoreapp2.1 and reference the latest System.Reflection.Emit, the instance method `DefineDynamicAssembly` does not exist. This is confusing, since I see people talking about using Ref.Emit on .NET Core. Did the API move?

**Comment by jkotas** [comment]
It has moved to `AssemblyBuilder.DefineDynamicAssembly`

**Comment by Adriien-M** [comment]
> It has moved to `AssemblyBuilder.DefineDynamicAssembly`

So it's not possible to define assembly in another `AppDomain` in .NET Core?

**Comment by svick** [comment]
@Adriien-M .Net Core does not support multiple AppDomains at all, so, no, that is not possible.

**Comment by danmosemsft** [comment]
@jkotas the omission of `System.Reflection.Emit.AssemblyBuilder System.AppDomain.DefineDynamicAssembly(System.Reflection.AssemblyName, System.Reflection.Emit.AssemblyBuilderAccess)` was encountered by a consumer of "Castle".

Can this be implemented as a simple pass through to `AssemblyBuilder.DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess access);` ? 

Looking at [referencesource](https://referencesource.microsoft.com/#mscorlib/system/appdomain.cs,1503) it appears to be a pass through?

**Comment by jkotas** [comment]
Do you mean https://github.com/castleproject ? Castle has .NET Core specific build that calls the right .NET Core API and has many other .NET Core specific tweaks. Can you use the .NET Core specific build of Castle instead?

**Comment by danmosemsft** [comment]
@jkotas regardless, would it be reasonable to implement as a passthrough? No doubt there are other preexisting binaries that use it - it seems a shame to trip on it if it's simple for us to resolve.

**Comment by danmosemsft** [comment]
(I'll ask them your question though)

**Comment by jkotas** [comment]
My thoughts:

There are other missing APIs and features in System.Reflection.Emit beyond this one. I am not sure where adding this one member would actually move the needle on how many .NET Framework libraries work.

Adding this API to AppDomain would require folding the `System.Reflection.Emit.*` contracts into `System.Runtime.*` contracts. We have given up on layering within netcoreapp to large degree so this should not be a big deal. "just work".

If you believe that it is a good use of a your team time, I do not have a problem with it.

**Comment by danmosemsft** [comment]
Hmm. It's apparently high usage -- 15% of apiport users, 56% of the selected apiport users.

https://apisof.net/catalog/System.AppDomain.DefineDynamicAssembly(AssemblyName,AssemblyBuilderAccess)

Of the many other overloads, only this other one also has significant usage, and I guess it does not have an easy forward.

https://apisof.net/catalog/System.AppDomain.DefineDynamicAssembly(AssemblyName,AssemblyBuilderAccess,String)

@ericstj any concerns about the layering @jkotas mentioned above?

**Comment by jkotas** [comment]
> 15% of apiport users, 56% of the selected apiport users.

What do these numbers actually say? If this was a common pain-point, we would hear about this API a lot more.

**Comment by danmosemsft** [comment]
Right, that's what I find hard to explain. Maybe they all had dependencies on Castle.

I'm going to close this for now. If other folks find this and it's an issue for them, please reply here and ping me. If there's another interest we can reconsider for 5.0. (But we'll also want to use apiport to confirm this would actually enable whatever the dependency is)
