### ISSUE TITLE
System.Net.Http.WinHttpResponseStream call to WinHttpReadData with lpdwNumberOfBytesRead set to IntPtr.Zero (instead of NULL?)

### ISSUE THREAD

**Issue by TilkID** [dotnet/corefx#31674]
Hello, 

I had an issue using HttpClient on Windows desktop so I was having a look into WinHttpHandler and found something "weird".

In class System.Net.Http.WinHttpHandler, method "StartRequest", a sessionHandle is created [using the Interop.WinHttp.WINHTTP_FLAG_ASYNC flag](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs#L744). 
This sessionHandle is then used when creating the connectHandle which is then used to create the requestHandle.
As the WINHTTP_FLAG_ASYNC flag has been set while calling Interop.WinHttp.WinHttpOpen, a WinHttpSetStatusCallback is then defined on this requestHandle.
The responseMessage is then set by calling WinHttpResponseParser.CreateResponseMessage. This method defines responseStream using WinHttpResponseStream(requestHandle, state).
Interop.WinHttp.WinHttpReadData is called upon reading and the parameter "lpdwNumberOfBytesRead" [is set to IntPtr.Zero](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpResponseStream.cs#L238).

According to [MS Documentation for WinHttpReadData](https://docs.microsoft.com/en-us/windows/desktop/api/winhttp/nf-winhttp-winhttpreaddata#parameters), this parameter should be set to NULL:

> lpdwNumberOfBytesRead: Pointer to an unsigned long integer variable that receives the number of bytes read. WinHttpReadData sets this value to zero before doing any work or error checking. When using WinHTTP asynchronously, always set this parameter to NULL and retrieve the information in the callback function; not doing so can cause a memory fault.

[MS Documentation](https://docs.microsoft.com/en-us/windows/desktop/api/winhttp/nf-winhttp-winhttpreaddata#remarks) states that asynchonous calls are defined by using WINHTTP_FLAG_ASYNC flag:

> Even when WinHTTP is used in asynchronous mode (that is, when WINHTTP_FLAG_ASYNC has been set in WinHttpOpen), this function can operate either synchronously or asynchronously. If this function returns FALSE, this function failed and you can call GetLastError to get extended error information. If this function returns TRUE, use the WINHTTP_CALLBACK_STATUS_READ_COMPLETE completion to determine whether this function was successful and the value of the parameters. The WINHTTP_CALLBACK_STATUS_REQUEST_ERROR completion indicates that the operation completed asynchronously, but failed.

To be honest, I was not able to run some tests but, as I found this "weird", and as MS strongly advise against using something else than NULL to avoid memory fault. I created this issue.

Best regards, 
TilkID

**Comment by davidsh** [comment]
>According to MS Documentation for WinHttpReadData, this parameter should be set to NULL:

If the source code was native C/C++, then "NULL" would be the correct thing to pass into the API.

However, this code is C# and uses P/invokes to call the native WinHTTP APIs. IntPtr.Zero represents the native NULL value.  So, the calling pattern is correct.

See: https://stackoverflow.com/questions/1456861/is-intptr-zero-equivalent-to-null

**Comment by TilkID** [comment]
My bad, thank you very much.
