### ISSUE TITLE
Ambiguous license header in some source files

### ISSUE THREAD

**Issue by omajid** [dotnet/corefx#31699]
Some source files in corefx contain this license header:

```cpp
//------------------------------------------------------------------------------
// <copyright file="TextWriterGenerator.cxx" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// <owner current="true" primary="true">helenak</owner>
//------------------------------------------------------------------------------
```

This license header looks a bit ambiguous because it names a copyright holder and says that all rights are reserved by the copyright holder. This somewhat contradicts the `LICENSE.TXT` file in this repo which says that the copyright holder (.NET Foundation) is licensing this file under the MIT license. It would be nice to clear up this ambiguity and clarify that this file is indeed licensed under an open source license.

The following files have this issue:
- https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/Core/XmlRawTextWriterGenerator.cxx
- https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/Core/HtmlRawTextWriterGenerator.cxx
- https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/Core/TextRawTextWriterGenerator.cxx

cc @leecow @richlander

**Comment by joshfree** [comment]
Thanks for pointing this issue with the .cxx files out @omajid.  @krwq could you correct this and also grep to ensure there's no other issues like this elsewhere?

**Comment by krwq** [comment]
Those are used to generate some of the xml code, I've fixed the headers in the PR

**Comment by leecow** [comment]
@krwq, @joshfree - seems like this should be ported to 2.1 so that the issue is not brought up when we get to submitting to other distros for inclusion.

**Comment by krwq** [comment]
@leecow are there any other branches we need to port this to except for release/2.1?

**Comment by leecow** [comment]
2.1 is the primary concern as it's our LTS channel and will be live for the next several years.

**Comment by joshfree** [comment]
@krwq port it to /release/2.1 and add the label `servicing-consider`.  After it's submitted, that will trigger an auto-port-PR from 2.1 to 2.2.  That'll cover everything.
