### ISSUE TITLE
Standardize flags declarations in native shims

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#3172]
We have a mix of raw integers and casting scoped enums right now.

See https://github.com/dotnet/corefx/pull/3142#issuecomment-139330591:
A general comment on raw integers vs. enum's on C++ side for flags. I've been doing the latter based on my recollection that storing a value that is not any one of the enum members is unspecified or undefined in standard C++. However, I'm no longer sure after looking at recent edits on cppreference.com:

http://en.cppreference.com/mwiki/index.php?title=cpp/language/static_cast&diff=78871&oldid=74481

My understanding was on the LHS of that diff. I don't know yet if the edits reflect errata on the site matching my own misunderstanding or just updates tracking the next version of the standard.

Even if it is well defined, it requires a lot of ugly casting, which kind of eliminates the benefit of strong typing. It's not apparent in this change because your flags come in from C# with the right values, but once you have to twiddle the bits, e.g. ConvertOpenFlags, it gets messy.

Assuming it is in fact well defined, we could have a macro to define bitwise operators on what we deem Flags enums. This would serve double-duty as documentation to C# caller to add [Flags]. I'm fine leaving this for a later change, but this is something we should standardize one way or the other.

**Comment by joshfree** [comment]
@sokket @eerhardt could you take a look?

**Comment by stephentoub** [comment]
Closing due to staleness. Thanks.
