### ISSUE TITLE
Incorrect CI build status

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#31728]
See https://github.com/dotnet/corefx/pull/31725#issuecomment-412361858 for discussion. 

Failures in i.e. frameworkPackage.targets are logged out but don't affect the build status even if it fails.

CI logged an error but the build didn't fail. That's from @tarekgh PR which came in on 8/10 after a faulty commit that caused target validation errors (caa3ab4): https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/15491/consoleText

Search for "cycle". Build didn't fail.

cc @jkotas @MattGal @eerhardt @weshaggard

**Comment by danmosemsft** [comment]
I'm not sure why this is, because they are clearly logged as errors, and we know that when the `Invalid local constant signature` warnings were errrors, the build would fail.
```
  Microsoft.Private.CoreFx.NETCoreApp -> D:\j\workspace\windows-TGrou---74aa877a\bin/packages/Debug/specs/runtime.win-x64.Microsoft.Private.CoreFx.NETCoreApp.nuspec
  Verifying closure of runtime.win-x64.Microsoft.Private.CoreFx.NETCoreApp runtime assemblies
D:\j\workspace\windows-TGrou---74aa877a\pkg\frameworkPackage.targets(124,5): error : Cycle detected for D:\j\workspace\windows-TGrou---74aa877a\bin\Windows_NT.AnyCPU.Debug\System.IO.FileSystem\netcoreapp\System.IO.FileSystem.dll. [D:\j\workspace\windows-TGrou---74aa877a\pkg\Microsoft.Private.CoreFx.NETCoreApp\Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
D:\j\workspace\windows-TGrou---74aa877a\pkg\frameworkPackage.targets(124,5): error : System.IO.FileSystem > System.IO.FileSystem.DriveInfo > System.IO.FileSystem [D:\j\workspace\windows-TGrou---74aa877a\pkg\Microsoft.Private.CoreFx.NETCoreApp\Microsoft.Private.CoreFx.NETCoreApp.pkgproj]

Build succeeded.

D:\j\workspace\windows-TGrou---74aa877a\Tools\partialfacades.task.targets(64,5): warning : PDB0018: token 0x0600001F: Invalid local constant signature: 'epsilon' [D:\j\workspace\windows-TGrou---74aa877a\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
D:\j\workspace\windows-TGrou---74aa877a\Tools\partialfacades.task.targets(64,5): warning : PDB0018: token 0x06000020: Invalid local constant signature: 'epsilon' [D:\j\workspace\windows-TGrou---74aa877a\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
D:\j\workspace\windows-TGrou---74aa877a\Tools\partialfacades.task.targets(64,5): warning : PDB0018: token 0x0600003B: Invalid local constant signature: 'epsilon' [D:\j\workspace\windows-TGrou---74aa877a\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
D:\j\workspace\windows-TGrou---74aa877a\Tools\partialfacades.task.targets(64,5): warning : PDB0018: token 0x0600003C: Invalid local constant signature: 'epsilon' [D:\j\workspace\windows-TGrou---74aa877a\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
D:\j\workspace\windows-TGrou---74aa877a\Tools\partialfacades.task.targets(64,5): warning : PDB0018: token 0x0600003C: Invalid local constant signature: 'minAngle' [D:\j\workspace\windows-TGrou---74aa877a\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
D:\j\workspace\windows-TGrou---74aa877a\Tools\partialfacades.task.targets(64,5): warning : PDB0018: token 0x06000059: Invalid local constant signature: 'EPSILON' [D:\j\workspace\windows-TGrou---74aa877a\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
D:\j\workspace\windows-TGrou---74aa877a\Tools\partialfacades.task.targets(64,5): warning : PDB0018: token 0x06000072: Invalid local constant signature: 'FLT_EPSILON' [D:\j\workspace\windows-TGrou---74aa877a\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
D:\j\workspace\windows-TGrou---74aa877a\Tools\partialfacades.task.targets(64,5): warning : PDB0018: token 0x0600008B: Invalid local constant signature: 'epsilon' [D:\j\workspace\windows-TGrou---74aa877a\src\System.Numerics.Vectors\src\System.Numerics.Vectors.csproj]
D:\j\workspace\windows-TGrou---74aa877a\pkg\frameworkPackage.targets(124,5): error : Cycle detected for D:\j\workspace\windows-TGrou---74aa877a\bin\Windows_NT.AnyCPU.Debug\System.IO.FileSystem\netcoreapp\System.IO.FileSystem.dll. [D:\j\workspace\windows-TGrou---74aa877a\pkg\Microsoft.Private.CoreFx.NETCoreApp\Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
D:\j\workspace\windows-TGrou---74aa877a\pkg\frameworkPackage.targets(124,5): error : System.IO.FileSystem > System.IO.FileSystem.DriveInfo > System.IO.FileSystem [D:\j\workspace\windows-TGrou---74aa877a\pkg\Microsoft.Private.CoreFx.NETCoreApp\Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
    8 Warning(s)
    2 Error(s)

Time Elapsed 00:06:54.74
Command execution succeeded.
```

**Comment by tarekgh** [comment]
I have no idea how my commit can cause this. 

CC @JeremyKuhne @ianhays for the cyclic issue. @ericstj and @weshaggard may have some clue on this?

```
System.IO.FileSystem > System.IO.FileSystem.DriveInfo > System.IO.FileSystem
```

**Comment by ViktorHofer** [comment]
@tarekgh nobody said that your commits caused that. Your commit is the one after the faulty commit and I just yours for the logs in CI.

**Comment by tarekgh** [comment]
thanks @ViktorHofer for the clarification :-)

**Comment by danmosemsft** [comment]
@dagood in @weshaggard absence, do you know how build can have errors but still complete with "Command execution succeeded." ? Seems like that is not what we want for a build so probably I am misreading what is happening.

**Comment by dagood** [comment]
Sure, taking a look.

**Comment by ericstj** [comment]
This actually looks like an MSBuild bug, [similar to this one](https://github.com/Microsoft/msbuild/issues/1791).  /cc @jeffkl 

That error statement is a remnant from when we did `ErrorAndContinue`, we [don't do that anymore](https://github.com/dotnet/corefx/commit/7572a0e2aa2cf71c17569a3be8d77118e73516d4), but MSBuild still doesn't halt the build.

**Comment by ericstj** [comment]
An idea I've had in the past for fixing this in a way that's less subject to people (or MSBuild bugs) reintroducing it is to have a logger that ensures we record all errors, then a task at the very end of the build (or even outside the msbuild process) that fails if any errors were logged.  Simple solution would be to examine the contents of msbuild.err and fail the build.

**Comment by jeffkl** [comment]
Are you using `/nowarn` or the MSBuild property `MSBuildTreatWarningsAsErrors`?  From the root cause by @dagood it looks more like something is up with how MSBuild determines the value of `MSBuildLastTaskResult`

**Comment by dagood** [comment]
@ericstj I think you're right--when I set up a simpler repro attempt, it stops immediately on the error when it should. Sorry for muddying the water.

**Comment by ericstj** [comment]
@jeffkl nope and nope. Not saying its the same issue as the one I linked just a similar symptom.  This is a hard error with the task returning false it should halt.  Let me point out the relevant pieces:
https://github.com/dotnet/buildtools/blob/4e1c39824d4f9ad8419849d0ab38cb97ff61fc9a/src/Microsoft.DotNet.Build.Tasks.Packaging/src/VerifyClosure.cs#L264
https://github.com/dotnet/buildtools/blob/4e1c39824d4f9ad8419849d0ab38cb97ff61fc9a/src/Microsoft.DotNet.Build.Tasks.Packaging/src/VerifyClosure.cs#L71
https://github.com/dotnet/corefx/blob/6bac4088aadf09a6e4864c78979dc54290015b9d/pkg/frameworkPackage.targets#L110
https://github.com/dotnet/corefx/blob/935a2bc538db3d3635977ac6192a8693567d2789/dir.traversal.targets#L50

**Comment by dagood** [comment]
I tried again and got a simple (but convoluted, which is what seems to cause it) repro:
https://github.com/Microsoft/msbuild/issues/3623. (Repro repo: https://github.com/dagood/repro-msbuild-task-not-stopping)

**Comment by ericstj** [comment]
> (after Build, is that an issue?):

Turns out it is!  Looks like the fix on our side is to sequence our targets differently.  We can't sequence them after the Build target, but instead after some Target in Build's closure.

**Comment by rainersigwald** [comment]
I'd switch `VerifyClosure`, `VerifyDuplicateTypes`, and `VerifyNETStandard` to `BeforeTargets="Build"` to work around the false build success (https://github.com/Microsoft/msbuild/issues/3345).

Usually I suggest `AfterTargets="AfterBuild"` but it doesn't look like `.pkgproj` imports `Microsoft.Common.targets` so it doesn't have the full convention of targets (which is fine!).
