### ISSUE TITLE
Fails to build on FreeBSD due to using outdated dnx-beta5

### ISSUE THREAD

**Issue by janhenke** [dotnet/corefx#3173]
Currently CoreFX cannot be build on FreeBSD, because it uses an old version of dnx with hard coded path to bash. CoreFX uses dnx-mono.1.0.0-beta5-12101. This has been fixed in dnx since then. Can we upgrade dnx to the most recent version to fix this issue?

I was trying to create a PR for this, but I do not find where the dnx version is defined. So it would be helpful of someone else can bump the dnx version.

**Comment by jasonwilliams200OK** [comment]
> but I do not find where the dnx version if defined.

I think it is: https://github.com/dotnet/buildtools/blob/717e75655/src/.nuget/packages.Unix.config#L5.

**Comment by akoeplinger** [comment]
I took a look at this. Updating to the latest "stable" beta7 release of DNX isn't as simple as I thought, it results in a lot of project.lock.json changes (due to changes in the lockfile format) and also causes a build break that I need to investigate.

**Comment by janhenke** [comment]
@akoeplinger that is unfortunate. But it seems the bump has to be done at some point anyway. It would be helpful to get this updated to beta7.

**Comment by akoeplinger** [comment]
Sent a PR to upgrade DNX to beta7: https://github.com/dotnet/corefx/pull/3177

**Comment by janhenke** [comment]
Great, thanks!
