### ISSUE TITLE
Handling of security principals

### ISSUE THREAD

**Issue by AndreasHeisel** [dotnet/corefx#31760]
I think, the handling of security principals in corefx ist broken. 

A modified version of the example for [AppDomain.SetThreadPrincipal](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.setthreadprincipal?view=netcore-2.1#System_AppDomain_SetThreadPrincipal_System_Security_Principal_IPrincipal_) at docs.microsoft.com:

```
using System;
using System.Security.Principal;
using System.Threading;

class ADPrincipal
{
	static void Main(string[] args)
	{
		// Create a new thread with a generic principal.
		Thread t = new Thread(new ThreadStart(PrintPrincipalInformation));
		t.Start();
		t.Join();

		// Set the principal policy to WindowsPrincipal.
		AppDomain currentDomain = AppDomain.CurrentDomain;
		currentDomain.SetPrincipalPolicy(PrincipalPolicy.WindowsPrincipal);

		// The new thread will have a Windows principal representing the
		// current user.
		t = new Thread(new ThreadStart(PrintPrincipalInformation));
		t.Start();
		t.Join();

		// Create a principal to use for new threads.
		IIdentity identity = new GenericIdentity("NewUser");
		IPrincipal principal = new GenericPrincipal(identity, null);
		currentDomain.SetThreadPrincipal(principal);

		// Create a new thread with the principal created above.
		t = new Thread(new ThreadStart(PrintPrincipalInformation));
		t.Start();
		t.Join();

		// Wait for user input before terminating.
		Console.ReadLine();
	}

	static void PrintPrincipalInformation()
	{
		IPrincipal curPrincipal = Thread.CurrentPrincipal;
		if (curPrincipal != null)
		{
			Console.WriteLine("Type: " + curPrincipal.GetType().Name);
			Console.WriteLine("Name: " + curPrincipal.Identity.Name);
			Console.WriteLine("Authenticated: " +
				curPrincipal.Identity.IsAuthenticated);
			Console.WriteLine();
		}
		else
		{
			Console.WriteLine("No principal");
		}
	}
}
```

On .NET Framework I get

```
Type: GenericPrincipal
Name:
Authenticated: False

Type: WindowsPrincipal
Name: ###\###
Authenticated: True

Type: GenericPrincipal
Name: NewUser
Authenticated: True
```

Running on .NET Core 2.1 I get
```
No principal
No principal
No principal
```
We rely an this feature. Is there a way to do it in a ".NET Standard" way that works with .NET Framework and .NET Core?

**Comment by jkotas** [comment]
This was fixed https://github.com/dotnet/corefx/pull/30765 . We kept `PrincipalPolicy.NoPrincipal` as the default in .NET Core, so the first line in your repro will still print No principal. Once you override the defaults, it behaves just like in .NET Framework.

**Comment by AndreasHeisel** [comment]
Thank you for your reply @jkotas . Fixed means .NET Core 3.0 as #30765 has the 3.0 milestone?

**Comment by jkotas** [comment]
> Fixed means .NET Core 3.0 as #30765 has the 3.0 milestone?

Yes.

If you need to make this work on existing .NET Core 2.x, the only workaround I can think of is to set the principal using 'Thread.CurrentPrincipal` when the thread starts.

**Comment by AndreasHeisel** [comment]
I will try. Thank you @jkotas

**Comment by danmosemsft** [comment]
Closing as above, feel free to reopen if this does not work.
