### ISSUE TITLE
HAVE_SHM_OPEN_THAT_WORKS_WELL_ENOUGH_WITH_MMAP test fails silently with compilation error

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/corefx#31784]
This CMake test is designed to check for the presence or absence of a feature on the current platform. It has been failing with a compilation error, and therefore failing on every platform, regardless of the presence or absence of the feature it's testing for. We should fix the code for this test so that we can get back the coverage that it's supposed to provide.

**Comment by stephentoub** [comment]
@wtgodbe, is this still an issue?

**Comment by wtgodbe** [comment]
No
