### ISSUE TITLE
Enhance Guid type with implicit type conversions to useful primitive types

### ISSUE THREAD

**Issue by sonicflare** [dotnet/corefx#3179]
Currently, Guid feels a little bit left out. While other built-in types have implicit type convertions, or support from Convert, Guid have it's own "bastion" of methods and converters, and is a source of confusion for new developers. 

Is there any particual reasons (except historical) that Guid should not be part of built-in types and have a implicit convertion (from bytes or string)?

**Comment by AlexGhiondea** [comment]
Sounds like a good idea for an enhancement. 

We would need a formal API proposal for this.

**Comment by danmosemsft** [comment]
@sonicflare  do you have interest in writing up the quick formal proposal here? We are trying to move more quickly with API requests than we have in the past.

See [API review process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md)

**Comment by stephentoub** [comment]
Been a few years without further details.  Closing for now.
