### ISSUE TITLE
Implement go to definition for F#

### ISSUE THREAD

**Issue by hez2010** [dotnet/corefx#31795]
Currently "Go to definition" in F# only works within user-defined symbols, it's hard for users to quickly lookup library functions' usage.

I'm wondering now that the Intellisense in Visual Studio can generate F# lib functions' usage for user, why can't user use "Go to definition" or "Peek definition" to see usage in F# syntax from metadata just like what C# does.

I can not find the F# repo so I post the issue here.

**Comment by danmosemsft** [comment]
Hello @hez2010 , please open this issue in https://github.com/Microsoft/visualfsharp.
