### ISSUE TITLE
Proposal for ImmutableInterlocked.ApplyChange API

### ISSUE THREAD

**Issue by AArnott** [dotnet/corefx#318]
Folks using immutable collections in multi-threaded environments frequently want to leverage the immutability to use lock-free patterns of updating the fields that store those collections. 

Interlocked.CompareExchange leaves quite a bit of insight into the runtime and threading requirements to the programmer when it comes to lock-free mutations of immutable collections. While we already have the `ImmutableInterlocked` class with several methods on it, all methods are special purpose and aren't suitable for such simple and common operations as adding or removing an element to an `ImmutableList<T>` or `ImmutableHashSet<T>`.

I propose adding this API:

    /// <summary>
    /// Mutates a value in-place with optimistic locking transaction semantics
    /// via a specified transform function.
    /// The transform is retried as many times as necessary to win the optimistic locking race.
    /// </summary>
    /// <typeparam name="T">The type of data.</typeparam>
    /// <typeparam name="TArg">The type of the argument to be passed to the transformer</typeparam>
    /// <param name="location">
    /// The variable or field to be changed, which may be accessed by multiple threads.
    /// </param>
    /// <param name="transformer">
    /// A function that mutates the value. This function should be side-effect free, 
    /// as it may run multiple times when races occur with other threads.</param>
    /// <returns>
    /// <param name="transformerArgument">
    /// An argument to pass to the <paramref name="transformer"/> function.
    /// </param>
    /// <c>true</c> if the location's value is changed by applying the result of the 
    /// <paramref name="transformer"/> function;
    /// <c>false</c> if the location's value remained the same because the last 
    /// invocation of <paramref name="transformer"/> returned the existing value.
    /// </returns>
    public static bool ApplyChange<T, TArg>(ref T location, Func<T, TArg, T> transformer, TArg transformerArgument) where T : class

    public static bool ApplyChange<T>(ref T location, Func<T, T> transformer) where T : class

The `ImmutableInterlocked.ApplyChange` method makes such lock-free mutations trivial:

    // Add "2" to the list in this.field in a thread-safe, lock-free manner.
    ImmutableInterlocked.ApplyChange(ref this.field, list => list.Add(2));

More complex functions are of course also supported, allowing search of a collection, computation, and a subsequent prescribed change returned. In each case, an "optimistic locking" style transaction is used to execute the provided function (repeatedly, if necessary in the case of a lost race) to update the field without locks.

I plan to send a pull request once this issue is reviewed. I'm attempting to follow the process proposed in #294 since this change adds to the public API.

Change log:

 * renamed parameters `hotLocation` to `location` and `transformation` to `transformer`.
 * added overload that takes a `TArg`

**Comment by terrajobst** [comment]
[We've reviewed this proposal](https://github.com/dotnet/apireviews/blob/master/2015-01-14-misc/README.md#318-proposal-for-immutableinterlockedapplychange-api) and think it's a good addition and thus accept PRs.
