### ISSUE TITLE
Feature Request: add Microsoft.JScript support

### ISSUE THREAD

**Issue by kphillisjr** [dotnet/corefx#31803]
I already know that .NET Core is mainly focused on C# and VisualBasic .NET, and this has lead to the ignoring of [JScript .NET (link to wikipedia)](https://en.wikipedia.org/wiki/JScript_.NET) that has been included with .NET on all Windows Computers since the first release of .NET Framework 1.1.

Also as a quick note, I remember that a few years back that the Mono Project had a JScript .NET Implementation that needed work. This Implementation was ultimately Deprecated, and removed ( see: https://github.com/mono/mono/commits/master/mcs/class/Microsoft.JScript ). However, the documentation for this Implementation can be found at The Mono Project's Website ( See: https://www.mono-project.com/archived/jscript/ )

**Comment by danmosemsft** [comment]
@kphillisjr what is the motivation here - is there much real world code that it is important to migrate? I am not sure JScript.NET is really used (perhaps I wouldn't know)

@terrajobst ?

**Comment by karelz** [comment]
This is general discussion, beyond the scope of CoreFX repo - I would recommend to suggest it on https://github.com/dotnet/core

**Comment by kphillisjr** [comment]
@karelz Thank you for the suggestion, and I will create an issue in the suggested repository soon.

@danmosemsft - Most of the real world code for JScript.net is tied to ASP.NET projects seeing as how the advertised use cases where always in server-side programming. However, the language is also useful for rapid prototyping of user interface code. The language is essentially a .NET binding for JScript ( aka ECMAScript 262, JavaScript, etc ).

**Comment by danmosemsft** [comment]
@kphillisjr thanks for the background. I'll close this issue in favor of your new one.
