### ISSUE TITLE
XmlSerializationWriter not visible

### ISSUE THREAD

**Issue by DanailKoychev** [dotnet/corefx#3180]
I get the following error:
DNXCore,Version=v5.0 error CS0234: The type or namespace name 'XmlSerializationWriter' does not exist in the namespace 'System.Xml.Serialization' (are you missing an assembly reference?)

Program.cs:
```
	using System;

	namespace XmlSerializationWriterTest
	{
		public class Program
		{
			public void Main(string[] args)
			{
				System.Xml.Serialization.XmlSerializationWriter writer = (System.Xml.Serialization.XmlSerializationWriter)(new Object());
			}
		}
	}
```

project.json:
```
	{
	  "dependencies": {
	  },

	  "frameworks": {
		"dnxcore50": {
		  "dependencies": {
			"System.Xml.XmlSerializer": "4.0.10"
		  }
		}
	  }
	}
```

The code of XmlSerializationWriter is here: https://github.com/dotnet/corefx/blob/41e203011152581a6c65bb81ac44ec037140c1bb/src/System.Xml.XmlSerializer/src/System/Xml/Serialization/XmlSerializationWriter.cs

**Comment by khdang** [comment]
@DanailKoychev On Desktop, the XmlSerializationWriter type is a class that supports internal implementation and is not intended to be used directly from you code. In NetCore this class is not exposed to the public contract.
