### ISSUE TITLE
CultureInfo.InstalledUICulture returns InvariantCulture on MacOS

### ISSUE THREAD

**Issue by sebastienros** [dotnet/corefx#31808]
Works fine on Windows (10) and Linux (Ubuntu) but it returns InvariantCulture on MacOS (10) where it was set to fr-CA.

**Comment by tarekgh** [comment]
@sebastienros our behavior should be the same between MAC and Linux. this looks the settings in the machine can be different. could you please try to dump the value of the following environment variables on your Linux and Mac and send it back? I believe the difference will be there.

```
LC_ALL
LC_MESSAGES 
LANG
```

**Comment by Skrypt** [comment]
I investigated a little by trying to find if I could get the value of the current OS culture from an environment var with the Mac OS X Terminal by doing a printenv. I found out that there's a "LANG" value in the environment vars that is outputing exactly my current OS culture "fr_CA.UTF8". Though I'm not able to get this environment var from C# through Environment.GetEnvironmentVariable("LANG") nor able to find it by doing Environment.GetEnvironmentVariables(). Theres also a var that is "USER" that I can retreive with Environment.GetEnvironmentVariable("USER"). Not sure if this is helping or not. The list of cultures itself in UNIX based OSs comes from libicu and this part seems to be fine. I tried updating it by doing brew install icu4c and it reported me I had latest version already installed.

**Comment by tarekgh** [comment]
@Skrypt 

> I tried updating it by doing brew install icu4c and it reported me I had latest version already installed.

You may try instructions in the following link https://gist.github.com/giniedp/7247700 to manually compile and install the latest ICU. you can download the latest ICU sources from http://site.icu-project.org/download/62#TOC-ICU4C-Download

> Though I'm not able to get this environment var from C#

I'll try to take a look at that bu tin general we get the environment variables ``` Environment.GetEnvironmentVariables().``` using http://man7.org/linux/man-pages/man7/environ.7.html and for reading the LANG variable we call https://linux.die.net/man/3/getenv in the source https://github.com/dotnet/coreclr/blob/master/src/corefx/System.Globalization.Native/locale.cpp#L118. I am not sure why the environment variable exists inside the terminal but not when calling Environment.GetEnvironmentVariables that what we need to look at. thanks for trying out.

**Comment by tarekgh** [comment]
@sebastienros please confirm if you see the environment variables defined in your machine. thanks.

**Comment by tarekgh** [comment]
@Skrypt I have tried in my High Sierra Mac and I can see LANG defined when calling ```Environment.GetEnvironmentVariables()``` so I am not sure what is happening in your machine. 

Now, I am waiting for @sebastienros to confirm if he has any of the following variables defined in his machine and still getting Invariant culture. I tried in my machine (I have en-US) and I am getting the right culture "en-US" and not Invariant. I have the LANG variable defined in my machine.

**Comment by Skrypt** [comment]
I'm going to check back, though I've reinstalled Mac OS X pretty recently. I can still reinstall it and retest afterward.

**Comment by Skrypt** [comment]
Here is what I'm getting from VS Code debugger.
<img width="1440" alt="capture d ecran 2018-08-17 a 15 49 18" src="https://user-images.githubusercontent.com/3228637/44285941-3753b800-a235-11e8-9baf-09ac07033818.png">

**Comment by sebastienros** [comment]
I found the problem.

There is a difference between running from Visual Studio for MAC and from the command line on a MAC.

Run from Command line:
```
TERM_SESSION_ID, w0t0p0:CF686D7F-55DF-4E4E-8FB0-5EEC2E00CFDD
ITERM_PROFILE, Default
TMPDIR, /var/folders/pd/mny80ks961108l1fbtvznbmr0000gn/T/
SHLVL, 1
XPC_SERVICE_NAME, 0
LC_CTYPE, en_US.UTF-8
HOME, /Users/ajbaaska
ZSH, /Users/ajbaaska/.oh-my-zsh
USER, ajbaaska
_, /Users/ajbaaska/.dotnet//dotnet
SSH_AUTH_SOCK, /private/tmp/com.apple.launchd.LdamdKquFj/Listeners
COLORTERM, truecolor
LSCOLORS, Gxfxcxdxbxegedabagacad
SECURITYSESSIONID, 186a8
TERM, xterm-256color
LANG, en_US.UTF-8
ASPNETCORE_ENVIRONMENT, Development
ReferenceAssemblyRoot, /Users/ajbaaska/.dotnet/buildtools/netfx/4.6.1
XPC_FLAGS, 0x0
PATH, /Users/ajbaaska/.dotnet/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin
COLORFGBG, 15;0
Apple_PubSub_Socket_Render, /private/tmp/com.apple.launchd.vyKRih00W7/Render
TERM_PROGRAM_VERSION, 3.1.6
COMMAND_MODE, unix2003
LOGNAME, ajbaaska
SHELL, /bin/zsh
__CF_USER_TEXT_ENCODING, 0x1F5:0x0:0x0
PAGER, less
PWD, /Users/ajbaaska/Github/temp/TestEnv
ITERM_SESSION_ID, w0t0p0:CF686D7F-55DF-4E4E-8FB0-5EEC2E00CFDD
TERM_PROGRAM, iTerm.app
LESS, -R
ASPNETCORE_URLS, https://localhost:5001;http://localhost:5000
OLDPWD, /Users/ajbaaska/Github/temp
```

Run from VSMac:

```
PATH, /Library/Frameworks/Mono.framework/Commands:/Applications/Visual Studio RTM.app/Contents/Resources:/Applications/Visual Studio RTM.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:~/.dotnet/tools:/usr/local/share/dotnet:/usr/local/share/dotnet/
LC_NUMERIC, C
FSharpTargetsShim, /usr/local/share/dotnet/sdk/2.1.401-preview-009081/FSharp/Microsoft.FSharp.NetSdk.targets
XCODE_DEVELOPER_DIR_PATH, /Applications/Xcode.app/Contents/Developer
SHELL, /bin/zsh
XPC_FLAGS, 0x0
Apple_PubSub_Socket_Render, /private/tmp/com.apple.launchd.vyKRih00W7/Render
FSharpPropsShim, /usr/local/share/dotnet/sdk/2.1.401-preview-009081/FSharp/Microsoft.FSharp.NetSdk.props
__CF_USER_TEXT_ENCODING, 0x1F5:0x0:0x0
DYLD_FALLBACK_LIBRARY_PATH, /Applications/Visual Studio RTM.app/Contents/Resources/lib:/Applications/Visual Studio RTM.app/Contents/Resources/lib/monodevelop/bin:/Applications/Xcode.app/Contents/Developer/usr/lib:/Library/Frameworks/Mono.framework/Libraries:/lib:/usr/lib:/usr/local/lib
ASPNETCORE_URLS, https://localhost:5001
LC_CTYPE, en
MONODEVELOP_64BIT_SAFE, yes
TMPDIR, /var/folders/pd/mny80ks961108l1fbtvznbmr0000gn/T/
MONO_GC_PARAMS, major=marksweep-conc,nursery-size=8m
MONODEVELOP_STUB_LANGUAGE, en
PKG_CONFIG_PATH, /Applications/Visual Studio RTM.app/Contents/Resources/lib/pkgconfig:/Library/Frameworks/Mono.framework/External/pkgconfig
LOGNAME, ajbaaska
XPC_SERVICE_NAME, com.microsoft.visual-studio.20296
DOTNET_MSBUILD_SDK_RESOLVER_CLI_DIR, /usr/local/share/dotnet
ASPNETCORE_ENVIRONMENT, Development
HOME, /Users/ajbaaska
MONO_GAC_PREFIX, /Applications/Visual Studio RTM.app/Contents/Resources
USER, ajbaaska
LANGUAGE, en
SSH_AUTH_SOCK, /private/tmp/com.apple.launchd.LdamdKquFj/Listeners
```

Mac OS version 10.13.4

**Comment by sebastienros** [comment]
So it looks like an issue in mono, as VS/MAC is using it, while our command line will use dotnet core.

**Comment by Skrypt** [comment]
I'm installing VS for Mac right now to test afterward. I get really different environment vars on my system. I'm not even having LC_CTYPE, LANGUAGE.

**Comment by tarekgh** [comment]
@sebastienros I am closing the issue here and feel free to open issue for VS or Mono. let me know if I can help in any further investigation.
