### ISSUE TITLE
[HTTP2] DataFrame_PaddingOnly_ResetsStream() test is not working as expected

### ISSUE THREAD

**Issue by caesar1995** [dotnet/corefx#31814]
[DataFrame_PaddingOnly_ResetsStream()](https://github.com/dotnet/corefx/blob/66649ff5862c7b723fded40c505942de19bdb107/src/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.Http2.cs#L184) is that, HTTP/2 loopback server sends a malformed data to SocketsHttpHandler, so that SocketsHttpHandler will send back a RST_STREAM frame. It seems SocketsHttpHandler will not send the RST_STREAM frame.

SocketsHttpHandler will only send RST_STREAM frame when it unable to retrieve a http2stream:
https://github.com/dotnet/corefx/blob/eedddac1bd10a7c8629a9db7f46fc8afc7385d63/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L305-L309

https://github.com/dotnet/corefx/blob/eedddac1bd10a7c8629a9db7f46fc8afc7385d63/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L229-L234

Need to determine whether it's SocketsHttpHandler issue or HTTP/2 loopback server issue.

cc: @rmkerr

**Comment by geoffkizer** [comment]
This test is removed in recent PRs

**Comment by geoffkizer** [comment]
(To be clear, I removed it because it wasn't a valid test, which was leading to the issues described above)

**Comment by rmkerr** [comment]
Thanks!
