### ISSUE TITLE
Document breaking change rule between empty and non-empty struct

### ISSUE THREAD

**Issue by jnm2** [dotnet/corefx#31834]
I hit this for real. https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md does not mention this source-breaking change:

```cs
using System;

public struct S { }

public class C
{
    public void M()
    {
        S s;
        Console.WriteLine(s);
    }
}
```

###### [(sharplab)](https://sharplab.io/#v2:EYLgHgbALANALiAbgUwE4EsBmBPAPgVwGd0A7AcwAIBlbQuZAWwG4BYAKHYAd9gAbdAMYU6qfALjUKAbwoBfdlx78hA3gENChCgGF2U9hUMVufQRUQB7dABMKAWQAUASgNH9bI58mFWHr4e0LEkILXmQAOgB1DHoAGVJkB0InX095NnSgA==)

After adding a field:

```cs
using System;

public struct S
{
    private readonly int foo;
}

public class C
{
    public void M()
    {
        S s;
        Console.WriteLine(s); // error CS0165: Use of unassigned local variable 's'
    }
}
```

###### [(sharplab)](https://sharplab.io/#v2:EYLgHgbALANALiAbgUwE4EsBmBPAPgVwGd0A7AcwAIBlbQuZAWwG4BYAKHYAd9gAbdAMYU6qfALjV2Ab3YU5FThkQBDehVTJlAEwD2JXtgqkJmHTtZsAvuy49+Qgb2WFCFAMLTZ87n0EVEOuhaFACyABQAlF5yMmzy8dTCFgnybnqEOrzIAHQA6hj0ADKkyGGEEcny1lbsQA)

**Comment by karelz** [comment]
Does it break "only" compile-time compat, or also binary compat? If it is binary compatible, I am not sure if we need to list it there ...
cc @weshaggard @terrajobst @ericstj @danmosemsft

**Comment by jnm2** [comment]
@karelz Source compatibility is already mentioned in a few places in that document, including a section header.

**Comment by karelz** [comment]
Thanks for clarification.
IMO adding fields to structs is ok in general (at least it is not listed as breaking change). I am not sure if we should disallow this corner case only ...

**Comment by weshaggard** [comment]
Adding fields to structs can certainly cause trouble for existing code. It is source breaking in this instance but it can also be binary breaking. You can get into a state where you have uninitialized fields and if you use the struct for interop it may no longer correctly align or have the correct amount of fields.  

@jnm2 want to take a shot at providing a PR to update the guidance?

**Comment by jnm2** [comment]
@weshaggard Not totally happy with the verbosity. Let me know what you think: #31856
