### ISSUE TITLE
PipeWriter.CancelPendingFlush cancels the *next* flush

### ISSUE THREAD

**Issue by AArnott** [dotnet/corefx#31837]
The following test fails because when `PipeWriter.CancelPendingFlush()` is invoked when no flush is pending or in progress, it instead cancels the *next* `FlushAsync` call. This seems counter to the very name of the method.

```cs
[Fact]
public async Task CancelPendingFlush_BeforeFlushDoesNotCancelFutureFlush()
{
    var writer = new Pipe().Writer;
    writer.GetMemory(1);
    writer.Advance(1);
    writer.CancelPendingFlush();
    var flushResult = await writer.FlushAsync();
    Assert.False(flushResult.IsCanceled);
}
```

This seems at least loosely similar to #31696

**Comment by AArnott** [comment]
@davidfowl here's another one.

**Comment by davidfowl** [comment]
That one is by design.

**Comment by AArnott** [comment]
What is the use case for this method in general, and for it to cancel a future flush?

Also, when does FlushAsync throw OCE vs. return a FlushResult where IsCanceled is true?

**Comment by davidfowl** [comment]
Both CancelPendingRead and CancelPendingFlush will always be observed by ReadAsync and FlushAsync respectively. This means if there’s no pending operation it’ll be observed next time. This is to ensure that cancellation is never missed. OperationCanceledExceptions only ever occur when you pass a CancellationToken to FlushAsync or ReadAsync

**Comment by davidfowl** [comment]
> I assume the contract is that canceling either of these operations does not corrupt data -- such that the operation could be repeated later and pick up where the last call left off?

That's correct.

> On a similar note, I wonder what the contract is for Stream.WriteAsync implementations. Should a canceled CancellationToken lead to a partial write, or should it be all or nothing to prevent corruption?

Good question. I'm not sure it's that well defined or consistent across stream implementations. In my experience, canceling usually makes the Stream unusable afterwards.

**Comment by GSPP** [comment]
If socket IO cancellation is actually implemented then cancelling a `NetworkStream` will definitely make the stream unusable. It will be undefined how much was sent over the network.
