### ISSUE TITLE
Interop request: Support exported symbols

### ISSUE THREAD

**Issue by MV10** [dotnet/corefx#31836]
Request: Define a new attribute which maps a managed variable to an exported symbol, exactly as we get today using `[DllImport]` for functions. 

Right now I'm facing the need to read data (defined constants and live variables) from Windows, Linux, and OSX native libraries. At the moment I'm not sure how to accomplish the same thing in Linux and OSX (I've just started down this rabbit-hole), but it definitely feels like the type of "it just works" magic that .NET ought to handle for us, because this gets ugly fast.

This is the Win32 way (although in my case I think I can skip `LoadLibrary` and `FreeLibrary` and just use `GetModuleHandle` since pinvoke will have already loaded it):

https://limbioliong.wordpress.com/2011/11/11/accessing-exported-data-from-a-dll-in-managed-code/

I suppose I'll have to target each OS with `#if` blocks based on Runtime Identifier build constants once I figure out how it works on the other platforms.

(On a related note, I noticed in #24444 the OP asks about _data_ and interfaces but it seems the data portion of the question was overlooked.)

**Comment by jkotas** [comment]
This issue was moved to dotnet/coreclr#19566
