### ISSUE TITLE
System.Drawing Not Complete Yet

### ISSUE THREAD

**Issue by zero0000zero** [dotnet/corefx#31840]
System.Drawing is not complete yet. We need Graphics class, Bitmap class and Color class.

**Comment by karelz** [comment]
Did you try latest package (incl. Platform Extensions for .NET Core 2.0)? I see all 3 in source code:
https://github.com/dotnet/corefx/blob/master/src/System.Drawing.Common/ref/System.Drawing.Common.cs#L10
https://github.com/dotnet/corefx/blob/master/src/System.Drawing.Common/ref/System.Drawing.Common.cs#L378
https://github.com/dotnet/corefx/blob/master/src/System.Drawing.Primitives/ref/System.Drawing.Primitives.cs#L10

They are all present in .NET Core 2.0 + Platform Extensions:
https://apisof.net/catalog/System.Drawing.Graphics
https://apisof.net/catalog/System.Drawing.Bitmap
https://apisof.net/catalog/System.Drawing.Color

**Comment by zero0000zero** [comment]
I tried System.Drawing.Common package, that have the classes, and it works. But we need it in official release.

**Comment by karelz** [comment]
The nuget package is the official release. It is included in the Windows Compat Pack.
Or do you expect something else?
