### ISSUE TITLE
Proposal: MultipleNameValueHeaderValueParser, use GenericHeaderParser.MultipleValueNameValueParser to create an ICollection<NameValueHeaderValue>

### ISSUE THREAD

**Issue by mstum** [dotnet/corefx#31858]
## Rationale and Usage
I have a string in the form `foo=bar,barman="one two three",charset=utf-8` which would be perfectly parseable using [`System.Net.Http.Headers.GenericHeaderParser.MultipleValueNameValueParser`](https://github.com/dotnet/corefx/blob/05d5e37a0b08a4fd6671385ed123d9ad279d1d70/src/System.Net.Http/src/System/Net/Http/Headers/GenericHeaderParser.cs#L21).

Unfortunately, that class is internal. There is one public class that uses it, [`System.Net.Http.Headers.CacheControlHeaderValue `](https://github.com/dotnet/corefx/blob/cea9971b75665f0c9d1c3f254c4fa8c58c7d494a/src/System.Net.Http/src/System/Net/Http/Headers/CacheControlHeaderValue.cs). It kinda works, I can get the values from the `Extensions` property or from the regular properties if the name matches.

But it feels kinda like a big crutch to do so, when we already have all the pieces - there is [`NameValueHeaderValue`](https://github.com/dotnet/corefx/blob/30f2f877c01940904b85691a09da5f91352ffad9/src/System.Net.Http/src/System/Net/Http/Headers/NameValueHeaderValue.cs) which seems to be meant for generic/custom HTTP Headers, but it uses SingleValueNameValueParser.

My API proposal is thus to add a `MultipleNameValueHeaderValueParser` class that uses `MultipleValueNameValueParser`:

`ICollection<NameValueHeaderValue> myHeaderVal = MultipleNameValueHeaderValueParser.Parse("foo=bar,barman=\"one two three\",charset=utf-8");`

## Proposed API

```cs
// These could also become members of the NameValueHeaderValue class, maybe called "ParseMultiple" since changing the behavior of the existing Parse methods feels like the wrong thing to do.
// Alternatively, add overloads with an bool allowMultiple argument that defaults to false.

public static class MultipleNameValueHeaderValueParser
{
    // Actual type is an ObjectCollection<NameValueHeaderValue>
    // Call to GenericHeaderParser.MultipleValueNameValueParser.ParseValue(input, null, ref index)
    public static ICollection<NameValueHeaderValue> Parse(string input);
    public static bool TryParse(string input, out ICollection<NameValueHeaderValue> parsedValue);
}
```

(Edit: Changed the proposal to a static helper instead of an actual class, since it's really just proposing a parser for a collection of NameValueHeaderValue)

**Comment by karelz** [comment]
Can you help me understand the user scenario and how common is it?
I don't think HTTP stack needs these, are you trying to repurpose part of HTTP stack for general parsing?

**Comment by mstum** [comment]
In my specific use case, I have to work with an HTTP Header that sends the values above (`X-SomeApp-Data: foo=bar,barman="one two three",charset=utf-8`), but that same string could also be sent via body or query string.

You're right that maybe this isn't really specific to the HTTP Stack, it just conincidentially happens to have the exact functionality that I need to parse that string (and deal with quoted/unquoted values), and I don't want to duplicate/re-implement code that already works, albeit as an internal class.

**Comment by karelz** [comment]
Triage: We do not think this belongs into HTTP stack in .NET Core. The demand is low (only 1 vote in last year). Closing.
