### ISSUE TITLE
Add System.Net.Http.CurlHandler

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#3185]
HttpClient is implemented as a sort-of plug-in model, where you provide to it a “handler” that actually does the heavy lifting.  There’s a default HttpClientHandler type, which on Windows is implemented around winhttp and on Unix is implemented around libcurl.  HttpClientHandler only exposes core knobs that are expected to be common across all possible implementations, but the underlying implementations often provide more functionality.  So on Windows, we also have System.Net.Http.WinHttpHandler (a class in its own separate assembly), which is the same handler used by default on Windows under HttpClientHandler, but which as a public type exposes additional knobs for developers to configure, e.g. timeouts on individual portions of a request/response rather than for the all-up operation.  There are such knobs we’d like to be able to configure with libcurl, e.g. targeting a UNIX domain socket as a proxy, but for which we’d need to expose CurlHandler publically in order to provide the right additional surface area.

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar @stephentoub 

Before we actually do this, we need to consider that we will be moving the `HttpClientHandler` APi surface forward and adding more knobs to it in a cross-platform way.  For example, the granular timeouts and server SSL certificate validation callback delegate and are things specific to 
WinHttpHandler right now.  But we plan to "promote" that functionality in a cross-platform manner to the HttpClientHandler class.

There still might be platform-specific knobs we need to expose on the specialty handlers like WinHttpHandler and CurlHandler.  But we expect longer-term not to have to do this.

**Comment by stephentoub** [comment]
Thanks, David. For reference, here's a specific example that likely wouldn't make sense on the shared type: https://github.com/dotnet/corefx/issues/3153

**Comment by SidharthNabar** [comment]
David is right - the long term vision is that HttpClient and HttpClientHandler are platform-agnostic APIs that have as many HTTP-related knobs as possible to support x-plat. For functionality/settings that are highly OS-specific, there will be "deeper" handlers such as WinHttpHandler/CurlHandler, etc.

So, we could proceed in one of two ways:
1. Wait and see how many properties from WinHttpHandler can be promoted to HttpClientHandler, and then implement any additional requested features on CurlHandler API surface.

2. Implement all the required features on CurlHandler right now, and then part of it will become unnecessary once it gets promoted to HttpClientHandler.

Either way is fine - I think #1 is more efficient, but may block some advanced scenarios on Unix in the meanwhile.

**Comment by CIPop** [comment]
There are advantages and disadvantages that we need to think about before taking this decision:
  * Pushing advanced features in `HttpClientHandler` would seem to allow more portability. Are we sure this is not a false sense of portability? How many platforms (please consider future platforms such as IoT and UWP) will actually support or even benefit from these features?

  * Creating specific handlers for each OS gives us high flexibility and a way to innovate without blocking or endangering behavior compatibility across platforms. We already know of several cases where the community contributed with Android and iOS high-perf handlers similar to WinHttpHandler. This is also a pattern with Xamarin where variability is isolated in OS-specific classes.

I am of the opinion that we should first understand usage patterns before attempting to promote more advanced functionality into HttpClientHandler.

+1 on the idea of creating CurlHandler
+1 on the idea of waiting before promoting functionality to HttpClientHandler
-1 on the prediction that either Curl or WinHttp handlers will ever become obsolete (#3153 is a good example: at least some of the devs will want to optimize or write apps very specific to a particular platform)

**Comment by stephentoub** [comment]
cc: @kapilash, @vijaykota for tracking

**Comment by stephentoub** [comment]
Our approach here has changed since this was opened.  We now have the single HttpClientHandler, as well as the ability to specify platform-specific properties via a property bag.  Unless we get a significant number of platform-specific properties for Unix, it would be better to not introduce a new type just for those properties, so as to enable consumers to avoid forking their code.  Closing this out for now.
