### ISSUE TITLE
Is it possible to have removed listener in ConditionalWeakTable ?

### ISSUE THREAD

**Issue by Thaina** [dotnet/corefx#31862]
I use ConditionalWeakTable to add custom value to arbitrary object. But sometimes some value should be disposed before it would be removed from the table

Is it possible to have listener API for the ConditionalWeakTable?

**Comment by karelz** [comment]
Won't [Remove](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.conditionalweaktable-2.remove?view=netframework-4.7.2) method work?

**Comment by karelz** [comment]
I am not sure when the key is removed from the table. I would expect it may be removed quite late, after the value is garbage collected.
Are you looking for event when a key is removed (which may me long after its value was garbage collected)? I don't think we have such event.
Or are you looking for event that a value is being garbage collected? That sounds like finalizer of the value object.

**Comment by Thaina** [comment]
@karelz I was looking for the event when the _key is removed_ so I could _call dispose to the value_

It's fine even there was long after. It so that I could dispose the linked value when there was no longer needed but the process was still running

The main point is, I have to add some value to arbitrary object. But that value should be dispose when it don't need. I want to dispose it when the key object that paired with it is no longer usable

**Comment by jkotas** [comment]
The unreachable key/value pairs in conditional weak table are cleared in the middle of GC. There is no way to do callbacks to the user code in the middle of the GC.

We would need to remember what got cleared and issue the callbacks later. It is exactly what finalizers do. Each value would have to be wrapped inside a finalizable objects to implement this event. You can just do yourself if you need it. I do not think we would want to all users of conditional weak table to pay for this.

**Comment by Thaina** [comment]
@jkotas Thank you very much for your clarification
