### ISSUE TITLE
NetFX build break in Microsoft.IO.Redist

### ISSUE THREAD

**Issue by morganbr** [dotnet/corefx#31860]
The NetFX and Packaging All Configurations CI builds are failing with the error below. It looks like it might be related to https://github.com/dotnet/corefx/pull/31763. @JeremyKuhne or @MarcoRossignoli, can you please take a look?

> 19:08:23 D:\j\workspace\windows-TGrou---2a8f9c29\src\Common\src\System\IO\DriveInfoInternal.Win32.cs(66,52): error CS0117: 'SR' does not contain a definition for 'Arg_MustBeDriveLetterOrRootDir' [D:\j\workspace\windows-TGrou---2a8f9c29\src\Microsoft.IO.Redist\src\Microsoft.IO.Redist.csproj]
19:08:23 D:\j\workspace\windows-TGrou---2a8f9c29\src\Common\src\System\IO\DriveInfoInternal.Win32.cs(66,84): error CS1503: Argument 2: cannot convert from 'string' to 'System.Exception' [D:\j\workspace\windows-TGrou---2a8f9c29\src\Microsoft.IO.Redist\src\Microsoft.IO.Redist.csproj]
19:08:23 D:\j\workspace\windows-TGrou---2a8f9c29\src\Common\src\System\IO\DriveInfoInternal.Win32.cs(81,48): error CS0117: 'SR' does not contain a definition for 'Arg_MustBeDriveLetterOrRootDir' [D:\j\workspace\windows-TGrou---2a8f9c29\src\Microsoft.IO.Redist\src\Microsoft.IO.Redist.csproj]
19:08:23 D:\j\workspace\windows-TGrou---2a8f9c29\src\Common\src\System\IO\DriveInfoInternal.Win32.cs(81,80): error CS1503: Argument 2: cannot convert from 'string' to 'System.Exception' [D:\j\workspace\windows-TGrou---2a8f9c29\src\Microsoft.IO.Redist\src\Microsoft.IO.Redist.csproj]
19:08:23 D:\j\workspace\windows-TGrou---2a8f9c29\src\System.IO.FileSystem\src\System\IO\File.cs(645,24): error CS0117: 'FileSystem' does not contain a definition for 'Encrypt' [D:\j\workspace\windows-TGrou---2a8f9c29\src\Microsoft.IO.Redist\src\Microsoft.IO.Redist.csproj]
19:08:23 D:\j\workspace\windows-TGrou---2a8f9c29\src\System.IO.FileSystem\src\System\IO\File.cs(650,24): error CS0117: 'FileSystem' does not contain a definition for 'Decrypt' [D:\j\workspace\windows-TGrou---2a8f9c29\src\Microsoft.IO.Redist\src\Microsoft.IO.Redist.csproj]

**Comment by JeremyKuhne** [comment]
I'll look

**Comment by JeremyKuhne** [comment]
Bad timing of merges- both were green, but they conflicted. I'll have a fix shortly.

**Comment by MarcoRossignoli** [comment]
@JeremyKuhne thank's for looking at this...in my timezone i was in bed.

**Comment by JeremyKuhne** [comment]
> thank's for looking at this...in my timezone i was in bed.

No problem. It was really my fault- I spaced on the fact that we were both changing the same code. :)
