### ISSUE TITLE
Xaml Markup Extension Constructors: Parameter defaults not working 

### ISSUE THREAD

**Issue by TheMinefighter** [dotnet/corefx#31872]
If a constructor of a `MarkupExtension` has a parameter with a  default value, making that parameter optional, that constructor option is not detected in Xaml and just tells you that there is no constructor taking n arguments.

**Comment by karelz** [comment]
That sounds like part of XAML: https://msdn.microsoft.com/en-us/library/system.windows.markup.markupextension(v=vs.110).aspx, which is not included/covered in .NET Core yet. It is part of .NET Framework - please follow instructions to file .NET Framework bugs here: https://github.com/dotnet/corefx#how-to-engage-contribute-and-provide-feedback
