### ISSUE TITLE
Add System.Security.Principal.Unix

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#3187]
We provide the Windows-only System.Security.Principal.Windows.dll on Windows, which brings with it WindowsIdentity and WindowsPrincipal.  We don’t currently have corresponding types for UnixIdentity and UnixPrincipal.  This would support getting the current user/group, setting the effective user/group (kind of like Windows impersonation), looking up information about the user, etc.

**Comment by stephentoub** [comment]
cc: @bartonjs just for tracking purposes

**Comment by ericstj** [comment]
As part of this work folks should identify if there is a basic set of cross-platform API that can enable these scenarios without having to cross compile the app.

**Comment by eerhardt** [comment]
The [Mono.Posix.NETStandard](https://www.nuget.org/packages/Mono.Posix.NETStandard) library has UnixUserInfo and UnixGroupInfo classes.  Does that meet these requirements?

> getting the current user/group

`UnixUserInfo UnixEnvironment.RealUser`
`UnixGroupInfo UnixEnvironment.RealGroup`
`UnixUserInfo UnixEnvironment.EffectiveUser`
`UnixGroupInfo UnixEnvironment.EffectiveGroup`

> setting the effective user/group (kind of like Windows impersonation)

On UnixEnvironment:
```
		public static long EffectiveUserId {
			get {return Native.Syscall.geteuid ();}
			set {Native.Syscall.seteuid (Convert.ToUInt32 (value));}
		}
```
```
		public static long EffectiveGroupId {
			get {return Native.Syscall.getegid ();}
			set {Native.Syscall.setegid (Convert.ToUInt32 (value));}
		}
```

> looking up information about the user

UnixUserInfo has:
```
		public string UserName { get; }
		public string Password {get; }
		public long UserId {get; }
		public UnixGroupInfo Group {get; }
		public long GroupId {get; }
		public string GroupName {get; }
		public string RealName {get; }
		public string HomeDirectory {get; }
		public string ShellProgram {get; }

		public static UnixUserInfo[] GetLocalUsers ()
```

**Comment by stephentoub** [comment]
@eerhardt, can they be used in places where IPrincipal/IIdentity is needed?  Do they support the equivalent of impersonation / elevating privileges, similar to how WindowsIdentity does?

**Comment by eerhardt** [comment]
> can they be used in places where IPrincipal/IIdentity is needed?

No.  They are just normal classes without implementing any interfaces:

```
namespace Mono.Unix {

	public sealed class UnixUserInfo
	{
	}

	public sealed class UnixGroupInfo
	{
	}
}
```

> Do they support the equivalent of impersonation / elevating privileges, similar to how WindowsIdentity does?

From my understanding, `setuid` and `seteuid` are the rough equivalent. 
http://man7.org/linux/man-pages/man2/setuid.2.html
http://man7.org/linux/man-pages/man2/seteuid.2.html

**Comment by stephentoub** [comment]
Yeah.  So it looks like the lib exposes the raw functionality; the question is whether it's then up to the developer to integrate those with the abstractions used in .NET, or whether we can do that for them? (Assuming it's useful enough.)

**Comment by stephentoub** [comment]
A real need for this hasn't presented itself in the last several years.  Given the presence of Mono.Posix, I'm going to close this, and we can reopen should we find a strong desire.
