### ISSUE TITLE
Add System.Configuration.Unix

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#3189]
There’s a lot of Unix configuration information that apps could benefit from being able to read (e.g. sysconf, pathconf, ulimit, etc.) and potentially modify.  Potentially support for parsing/outputting Unix configuration files as well.

**Comment by karelz** [comment]
We need formal API proposal

**Comment by stephentoub** [comment]
This hasn't had much interest since we opened it for discussion almost four years ago.  Closing.
