### ISSUE TITLE
Include SqlClient update in 2.2 packaging

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#31893]
#31039 was incomplete. 
Per https://github.com/dotnet/corefx/pull/31039#issuecomment-415154728 please increment version and include in package list.
I think we can consider this already approved by shiproom.

@AfsanehR

**Comment by AfsanehR** [comment]
@weshaggard I will update the versions soon but for now I am getting the following error on release 2.2 branch. I noticed you recently merged a pr into the branch, just wondering if you saw this happening. 

```
C:\corefx\Tools\partialfacades.task.targets(64,5): error : Method not found: 'System.Co
llections.Immutable.ImmutableArray`1<Byte> System.Reflection.Metadata.DebugMetadataHeader.get_Id()'. [C:\corefx\src\System.Text.Encoding\src\System.Text.Encoding.csproj]
```

**Comment by weshaggard** [comment]
No I've not personally seen that error but someone else complained about that recently. I'm going to try and build locally and see if I hit it.

**Comment by AfsanehR** [comment]
Closing this issue with PR #31937 . Thanks for your help regarding the update. I will create another PR to update the master branch version.
