### ISSUE TITLE
ERROR:The type initializer for 'Gdip' threw an exception on Ubunto  server

### ISSUE THREAD

**Issue by softsan** [dotnet/corefx#31895]
Tried using `System.Drawing.Common` package for my .net core web api project. It runs fine under windows but on ubunto (which is my host server), it throws following errors:
This is the method i used to generate thumbnail:

```
public static bool CreateThumbnail(int Width, int Height, Stream filePath, string saveFilePath)
        {

            try
            {
                var byteArray = filePath;  
                var streamImg = Image.FromStream(byteArray);

                Bitmap sourceImage = new Bitmap(streamImg);
                using (Bitmap objBitmap = new Bitmap(Width, Height))
                {
                    objBitmap.SetResolution(sourceImage.HorizontalResolution, sourceImage.VerticalResolution);
                    using (Graphics objGraphics = Graphics.FromImage(objBitmap))
                    {
                        // Set the graphic format for better result cropping   
                        objGraphics.SmoothingMode = SmoothingMode.HighQuality;
                        objGraphics.PixelOffsetMode = PixelOffsetMode.HighSpeed;
                        objGraphics.InterpolationMode = InterpolationMode.HighQualityBicubic;
                        objGraphics.CompositingQuality = CompositingQuality.HighQuality;
                        objGraphics.DrawImage(sourceImage, 0, 0, Width, Height);

                        // Save the file path, note we use png format to support png file   
                        objBitmap.Save(saveFilePath);
                    }
                }
            }
            catch (Exception ex)
            {
                LogHelper.Log("Create Thumbnail: ERROR:" + ex.Message + "\n" + ex.StackTrace);
                return false;
            }
            return true;
        }
```

```
ERROR:The type initializer for 'Gdip' threw an exception.
at System.Drawing.SafeNativeMethods.Gdip.GdipLoadImageFromDelegate_linux(StreamGetHeaderDelegate getHeader, StreamGetBytesDelegate getBytes, StreamPutBytesDelegate putBytes, StreamSeekDelegate doSeek, StreamCloseDelegate close, StreamSizeDelegate size, IntPtr& image)
at System.Drawing.Image.InitFromStream(Stream stream)
at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
```

Already installed
`sudo apt-get install libgdiplus`
and did this too:
```
cd /usr/lib
sudo ln -s libgdiplus.so gdiplus.dll
```

So Any workaround or thoughts on this?

**Comment by safern** [comment]
> cd /usr/lib
sudo ln -s libgdiplus.so gdiplus.dll

Did you try without doing this step? This shouldn't be necessary as we do search for libgdiplus.so in Unix.

We only try to load gdiplus.dll when running in Windows.

**Comment by softsan** [comment]
we first try without 
```
cd /usr/lib
sudo ln -s libgdiplus.so gdiplus.dll
```

but it didn;t work so we used above solution but none of them work either.

**Comment by safern** [comment]
Could you try adding this path to `LD_LIBRARY_PATH`?

`export LD_LIBRARY_PATH=/usr/lib`

And also could you confirm that libgdiplus.so is present under /usr/lib? 

If that doesn't work, would you mind running a little c app just to see if you can load libgdiplus there? 

```c
#include <dlfcn.h>
#include <stdio.h>
int main(void)
{
  void* ptr = dlopen("libgdiplus.so", 0x002);
  printf("Found: %s\n", ptr != 0 ? "yes" : "no");
  return 0;
}
`

**Comment by safern** [comment]
@softsan any luck?

**Comment by softsan** [comment]
Sorry for late reply. 
`System.Drawing.Common`  didn't work for me so i gave it up(since it was urgent and didn't get time to experiments).
so I used `CoreCompact.System.Drawing` library which resolved my issue.
Thanks.

**Comment by safern** [comment]
Ok, I just wanted to understand what was happening to fix it if it was a real product issue. I'm pretty sure that setting the `LD_LIBRARY_PATH` env variable correctly should fix your issue. Whenever you have time would you mind checking and if it still fails, I would love to dive into the issue and fix it. 

Will close the issue in the meantime, please feel free to re-open and I'm sorry you where hitting this.

**Comment by mramsterdam85** [comment]
Hey 
I also experience the same issue
I tried all of the above solutions, even with the export LD_LIBRARY_PATH=/usr/lib

Noob question: do I need to restart server or something else? (I just restarted the service by running dotnet run)

**Comment by safern** [comment]
Did you try installing libgdiplus? 

And also could you confirm that libgdiplus.so is present under /usr/lib?

What OS is your server running?

**Comment by LHeczko** [comment]
Hi,

I've got the same problem.
1. Installed libgdiplus
2. I can find it under /usr/lib
3. sudo ln -s libgdiplus.so gdiplus.dll
4. export LD_LIBRARY_PATH=/usr/lib
5. Restart service and still 

The type initializer for 'Gdip' threw an exception.

I'll try to use CoreCompact.System.Drawing as softsan wrote

**Comment by LHeczko** [comment]
Installed libc6-dev and everything works
https://github.com/JanKallman/EPPlus/issues/83

**Comment by jlestercastro** [comment]
Hello guys, someone please help me to fix this error,

I've always got "The type initializer for 'Gdip' threw an exception." when i deploy my .NetCore API in ubuntu server. But the codes is working in my local machine (Windows).

I'm trying to get a image icon in my server folder named pictures/3FALogo.ico

<img width="576" alt="12" src="https://user-images.githubusercontent.com/39945211/56874170-c5419d00-6a6a-11e9-944e-611d2290fb56.png">

<img width="282" alt="23" src="https://user-images.githubusercontent.com/39945211/56874203-f752ff00-6a6a-11e9-89fd-80e8c752a697.png">

I've always got this error response in my ubuntu server when accessing the API endpoint.
<img width="481" alt="54" src="https://user-images.githubusercontent.com/39945211/56874272-70525680-6a6b-11e9-8fcd-d58c18289c8c.png">

Someone can help me?
Thank you.

**Comment by LHeczko** [comment]
Have you installed libc6-dev on linux? For me it was the problem.

**Comment by sw0** [comment]
**Got same issue:**
I am using CentOS 7 and .NET Core 2.2, using `System.Drawing.Common` package, got same error: "error: The type initializer for 'Gdip' threw an exception.".
And I tried to use `sudo yum install libgdiplus`, it looks good but I cannot find neither `libgdiplus.so`, nor `gdiplus.dll` in the folder.

BTW, it's working fine on my local Windows 10 when debugging, but does not working on CentOS. 
Could someone help me out? Thank you.

**Comment by sw0** [comment]
**Fixed**
I use `# find -name libgdiplus*` and find the files exists in `/usr/lib64` instead of `/usr/lib`, so I follow the instructions as mentioned above after replacing the correct folder `/usr/lib64`. It works!
Thank for the instructions here.

**Comment by chucker** [comment]
In case someone is running into the same issue: on macOS, I had the "The type initializer for 'Gdip' threw an exception." exception despite having `mono-libgdiplus` installed via HomeBrew.

The reason was that my target framework was already `netcoreapp3.0`, but my `System.Drawing.Common` package was `4.5.1`. Updating to `4.6.0-preview8.19405.3` fixed it.

**Comment by pawelpetruch** [comment]
In my case on Raspbian running:
`
sudo apt-get install -y libgdiplus 
`
and restarting solved the issue.
