### ISSUE TITLE
Trying SSL with ALPN protocol for Amazon MQTT data, connects but no ALPN negotiation

### ISSUE THREAD

**Issue by RobertToy** [dotnet/corefx#31894]
Hi,

I've got a class library project in Visual Studio 2017 set to netcoreapp2.1 and the latest version (2.1.3) of the CORE SDK installed and referenced in my project, and I'm trying the following code but I cannot get it to use the ALPN protocol extensions.  Note that I'm constructing a new protocol (used for connection to amazon IoT over port 443 for mqtt data) to add to the list of protocols, but it still doesn't work even if I use one of the defaults ( ex: http2).

```c#
TcpClient tcpClient = new TcpClient();
Task task = tcpClient.ConnectAsync(IotEndpoint, 443); // IotEndpoint is my amazon endpoint.
await task;
 
SslStream sslStream = new SslStream(tcpClient.GetStream(), false);
 
X509Certificate2 certificate = new X509Certificate2(PathtoPFXFile, PFXPassword);
X509Certificate2Collection certColl = new X509Certificate2Collection(certificate);
 
SslApplicationProtocol amzProtocol = new SslApplicationProtocol("x-amzn-mqtt-ca");
SslClientAuthenticationOptions authOptions = new SslClientAuthenticationOptions();
authOptions.ApplicationProtocols = new List<SslApplicationProtocol>() { amzProtocol };            authOptions.EnabledSslProtocols = SslProtocols.Tls12;
authOptions.TargetHost = IotEndpoint;
authOptions.AllowRenegotiation = true;
authOptions.ClientCertificates = certColl;
authOptions.EncryptionPolicy = EncryptionPolicy.RequireEncryption;
authOptions.RemoteCertificateValidationCallback = new RemoteCertificateValidationCallback(ValidateServerCertificate);
 
await sslStream.AuthenticateAsClientAsync(authOptions, new CancellationToken(false));
```

Wireshark shows the connection happening and all of the handshaking going on and finishing, but wireshark does not show the ALPN protocol negotiations (the extensions on the Client Hello message) and it connects using http instead of mqtt protocol which is what I need.

Regards,

**Comment by karelz** [comment]
@RobertToy can you please post a minimal repro that we can try locally?

**Comment by RobertToy** [comment]
@karelz Please bear with me, but is this the additional info that is needed?

```c#
using System;
using System.Text;
using System.ServiceProcess;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;
using System.Net.Sockets;
using System.Collections.Generic;
using System.Security.Authentication;
using System.Net;

namespace ALPNService
{
    class Program
    {
        private const string IotEndpoint = "*************.iot.us-west-2.amazonaws.com";

        static void Main(string[] args)
        {
            Task t = DoConnectAsync();
            t.Wait();
        }

        private static async Task DoConnectAsync()
        {
            cpClient tcpClient = new TcpClient();
            Task task = tcpClient.ConnectAsync(IotEndpoint, 443);
            await task;
 
            SslStream sslStream = new SslStream(tcpClient.GetStream(), false);
 
            X509Certificate2 certificate = new X509Certificate2("Path to my PFX File", "My PFX Password");
            X509Certificate2Collection certColl = new X509Certificate2Collection(certificate);
            SslApplicationProtocol amzProtocol = new SslApplicationProtocol("x-amzn-mqtt-ca");
            SslClientAuthenticationOptions authOptions = new SslClientAuthenticationOptions();
            authOptions.ApplicationProtocols = new List<SslApplicationProtocol>() { amzProtocol };                                                                                                            
            authOptions.EnabledSslProtocols = SslProtocols.Tls12;
            authOptions.TargetHost = IotEndpoint;
            authOptions.AllowRenegotiation = true;
            authOptions.ClientCertificates = certColl;
            authOptions.EncryptionPolicy = EncryptionPolicy.RequireEncryption;
            authOptions.RemoteCertificateValidationCallback = new                                 
            RemoteCertificateValidationCallback(ValidateServerCertificate);
            await sslStream.AuthenticateAsClientAsync(authOptions, new CancellationToken(false));

        }

        public static bool ValidateServerCertificate(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
        {
            Debug.Print("SSL Policy Errors: " + sslPolicyErrors.ToString());
            return true;
        }

    }
}
```

All I'm doing is making the connection and then exiting, just to see if the ALPN extensions are being used.

The validate callback is showing "SSL Policy Errors: None" in my output window when the connection is made.

If you could give me some direction I'd appreciate it.

Thanks,

**Comment by RobertToy** [comment]
@wfurt Hi.  I'm using Win 7 Pro x64 with SP1.  I'm almost afraid of what you're going to tell me here...

**Comment by wfurt** [comment]
I think it is: Windows - Schannel supports alpn from win8.1/2012 R2 and higher.

**Comment by RobertToy** [comment]
I appreciate the assistance.  Although, I really wish I could have found this out sooner by it being documented somewhere in the classes for this and I could have avoided wasting weeks of time trying to go down this path.  I can get ALPN to work just fine and I can see the extension on the net packets and the negotiation when I'm using the FreeRTOS project supplied by amazon, but it's in C and I think it's because they use their own code wrapper for the sockets.

My first experience with Core has not been a happy one.

**Comment by wfurt** [comment]
There was debate if this show throw to make it more clear. But decision was made to ignore it if not supported by os.  I'll check if we can improve the documentation.

**Comment by davidsh** [comment]
>There was debate if this show throw to make it more clear. But decision was made to ignore it if not supported by os. I'll check if we can improve the documentation.

Are we logging the fact that we ignore the ALPN settings on Windows 7?  If not, that would be a good thing to add for logging in the System.Net.Security logging layer.
