### ISSUE TITLE
[Proposal] Expose additional MidpointRounding modes

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#31902]
### Rationale

The IEEE 754:2008 spec calls out five different supported "rounding directions", 4 of which are required for binary-floating point values.

CoreFX currently exposes only 1 of the required rounding directions and the 1 optional rounding mode. We should expose the remaining three rounding directions in order to be more compliant and give users the greatest flexibility when writing their applications.

### Proposed API

```C#
public partial enum MidpointRounding
{
    ToPositiveInfinity, // `roundTowardPositive` - the result closest to and no less than the infinitely precise result
    ToNegativeInfinity, // `roundTowardNegative` - the result closest to and no greater than the infinitely precise result
    ToZero              // `roundTowardZero` - the result closest to and no greater in magnitude than the infinitely precise result
}
```

**Comment by tannergooding** [comment]
CC. @eerhardt, @danmosemsft

**Comment by hamish-rose** [comment]
Hello

I would like to contribute to corefx - May I take this one ?

**Comment by danmosemsft** [comment]
For sure you can @hamish-rose. I sent you a collaborator link. If you accept, I can sign this to you. Note when you join it defaults to subscribing you to all repo activity, you will profligate want to switch that off as this repo is busy.

**Comment by danmosemsft** [comment]
Please ask her if you have questions. In the documentation folder in this repo is everything you should need to get started.

**Comment by hamish-rose** [comment]
Thanks, I've accepted.

**Comment by hamish-rose** [comment]
Hi @tannergooding 

I have a couple of questions:

- Is this change best applied to the shared library code in coreclr ? similar to dotnet/coreclr#15456.

- I started by writing tests, adding to the existing rounding tests I found over in corefx/src/System.Runtime.Extensions/tests/System/Math.cs. However my changes to the API aren't picked up and the tests won't compile though. Like above perhaps my changes should be over in coreclr, and add tests over there instead.

Cheers

**Comment by pentp** [comment]
These are not __midpoint__ rounding modes but __directed__ rounding modes.
Naming them as `Truncate/Floor/Ceiling` would be more consistent with the existing `Math` class API names.

**Comment by tannergooding** [comment]
This was discussed in the API review and it was determined that we should still expose them on `MidpointRoundingMode` rather than introducing a new type (such as `DirectedRoundingMode`).

CC. @terrajobst who may have the notes from that meeting?

**Comment by tannergooding** [comment]
I'm not opposed to having separate overloads that take a `DirectedRoundingMode` enum, but we would need to take this back through API review and update the corresponding PRs.

**Comment by pentp** [comment]
I'm still concerned about the naming - it's really confusing to see `MidpointRounding.AwayFromZero` and `MidpointRounding.ToPositiveInfinity` next to each other when they actually mean completely different things (at first look, one would assume that for positive numbers they would behave identically).

I propose renaming them to `Truncate/Floor/Ceiling` to avoid such confusion.

**Comment by tannergooding** [comment]
> I propose renaming them to `Truncate/Floor/Ceiling` to avoid such confusion.

I don't think `Truncate/Floor/Ceiling` will help avoid any of the confusion here. The names mean effectively the same thing either way, the "confusion" comes from it being on `MidpointRounding` when they are in-fact `DirectedRounding` modes.
