### ISSUE TITLE
[Proposal] Expose some additional Math and MathF operations

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#31903]
### Rationale

The IEEE 754:2008 spec lists a number of required operations. We should expose the missing operations to be more compliant and to give users the greatest flexibility when writing their applications.

NOTE: This does not represent all missing operations, but rather a smaller batch of operations that should be reasonable to review. The full set of missing operations is covered in https://github.com/dotnet/corefx/issues/31901

### Proposed API

```csharp
public partial static class Math
{
    public static double BitIncrement(double);                        // IEEE `nextUp`, C `nextafter` - The smallest value such that `result > x`
    public static double BitDecrement(double);                    // IEEE `nextDown` - The smallest value such that `result < x`

    public static double MaxMagnitude(double, double);             // IEEE `minNumMag` - Equivalent to `Math.Min(Math.Abs(x), Math.Abs(y))`
    public static double MinMagnitude(double, double);             // IEEE `maxNumMag` - Equivalent to `Math.Max(Math.Abs(x), Math.Abs(y))`

    public static int Ilog2(double);                               // IEEE `logB`, C `ilogb` - Equivalent to `(int)Math.Log2(x)`
    public static double Scale2(double, int);                      // IEEE `scaleB`, C `scalbn` - Equivalent to `x * 2^n`

    public static double Log2(double);                             // IEEE `logB`, C `logb` or `log2`
    public static double Scale2(double, double);                   // IEEE `scaleB`, C `scalbn` - Equivalent to `x * 2^n`

    public static double FusedMultiplyAdd(double, double, double); // IEEE `fusedMultiplyAdd`, C `fma`

    public static double CopySign(double, double);                 // IEEE `copySign`, C `copysign` - Exposed internally as `Math.copysign`
}

public partial static class MathF
{
    public static float BitIncrement(float);                          // IEEE `nextUp`, C `nextafterf` - The smallest value such that `result > x`
    public static float BitDecrement(float);                      // IEEE `nextDown` - The smallest value such that `result < x`

    public static float MaxMagnitude(float, float);                // IEEE `minNumMag` - Equivalent to `Math.Min(Math.Abs(x), Math.Abs(y))`
    public static float MinMagnitude(float, float);                // IEEE `maxNumMag` - Equivalent to `Math.Max(Math.Abs(x), Math.Abs(y))`

    public static int Ilog2(float);                                // IEEE `logB`, C `ilogbf` - Equivalent to `(int)MathF.Log2(x)`
    public static float Scale2(float, int);                        // IEEE `scaleB`, C `scalbnf` - Equivalent to `x * 2^n`

    public static float Log2(float);                               // IEEE `logB`, C `logbf` or `log2f`
    public static float Scale2(float, float);                      // IEEE `scaleB`, C `scalbnf` - Equivalent to `x * 2^n`

    public static float FusedMultiplyAdd(float, float, float);     // IEEE `fusedMultiplyAdd`, C `fmaf`

    public static float CopySign(float, float);                    // IEEE `copySign`, C `copysignf` - Exposed internally as `MathF.copysign`
}
```

**Comment by tannergooding** [comment]
Part of https://github.com/dotnet/corefx/issues/31901

**Comment by tannergooding** [comment]
`FusedMultiplyAdd` support has been heavily requested (although mostly in adding runtime support for automatically performing the optimization).

`CopySign` is used heavily by many low-level floating point algorithms (including our managed implementations for several Math functions)

`NextValue` and `PreviousValue` are generally useful, since there is no "increment"/"decrement" operation (which may be better names) and you must currently use `BitConverter`

`ILog2` and `Scale2` are also generally useful for implementing low-level floating point algorithms, where you may need to do various floating-point format tricks

**Comment by tannergooding** [comment]
CC. @eerhardt, @danmosemsft

**Comment by terrajobst** [comment]
Some minor feedback:

* NextValue -> BitIncrement
* PreviousValue -> BitDecrement
* Copysign -> CopySign

**Comment by svick** [comment]
What is the point of `MaxMagnitude` and `MinMagnitude`? That operation doesn't sound very common to me (but I could be wrong) and can be easily expressed with the existing API.

**Comment by tannergooding** [comment]
The purpose is to provide an efficient way to do `Math.Min(Math.Abs(x), Math.Abs(y))` or `Math.Max(Math.Abs(x), Math.Abs(y))`, but as a single operation.

The primary use-case (to my knowledge) is to ensure that a list of values are sorted so-as to minimize floating-point rounding errors when operating on a list where order would not matter for "normal" math rules.

**Comment by mhall1** [comment]
Hi, I'm new on this project, but this seems easy enough. Can I take a stab at it?

**Comment by tannergooding** [comment]
Sure thing.

As a pointer, this probably requires nearly identical changes to https://github.com/dotnet/coreclr/pull/15456 (but for the respective new APIs).

**Comment by tannergooding** [comment]
Feel free to ping me (either here, on our Gitter Channel, etc) if you have any questions/comments/concerns 😄

**Comment by mhall1** [comment]
Thanks. I'm just having some trouble finding the right solution in corefx. I see a System.Numerics.Vector, but no System.Numerics

**Comment by tannergooding** [comment]
@mhall1, are you still working on this? (no rush if you are, I just want to ensure it is still taken by someone)

**Comment by mhall1** [comment]
Yes, I am. I've just been busy with work lately.

**Comment by mhall1** [comment]
I'm sorry, but it doesn't look like I'll be able to do this one after
all... Please go ahead and reassign it.

**Comment by tannergooding** [comment]
That's alright. Thanks for the heads up @mhall1

**Comment by danmosemsft** [comment]
@tannergooding 	did API review prefer `Ilog2` over `ILog2`? In your comments you have the latter, in the API listing and the PR the formre. If the `i` is for `int` then presumably it should be `ILog2`?

**Comment by tannergooding** [comment]
Review and the exact casing conversation is here: https://youtu.be/hLbCfJSPIaI?t=5400. It was determined that `Ilog` (capital I, lowercase L) was the right casing to use here.

**Comment by danmosemsft** [comment]
Although I hear capitalization brought up, the discussion seemed to be about whether it should be called something else. @terrajobst just for the avoidance of doubt, are you OK with a lower case `l`? That basically means we think that `ilog` (or `ilog2`) is one word - or we are breaking convention.
