### ISSUE TITLE
STT.Dataflow.dll from Nuget version 4.9.0 has File Version 4.6.26515

### ISSUE THREAD

**Issue by alx9r** [dotnet/corefx#31929]
Nuget package version 4.9.0 that is available from [the TPL Dataflow nuget page](https://www.nuget.org/packages/System.Threading.Tasks.Dataflow/) contains a file at lib/netstandard2.0/System.Threading.Tasks.Dataflow.dll that has file metadata "File version: 4.6.26515.6":

![image](https://user-images.githubusercontent.com/11237922/44559221-5fdc2600-a6fd-11e8-94c6-32514cb4c971.png)

(That file has a SHA256 hash of 6336AAED8057DA25FCC08F3E9D93E8EEB3CC1D3FF5188E2EB61D2A85464D3DF7.)

I guess I expected the two versions to match, but now I'm not sure what each of those version numbers refers to. 

1. Are the Nuget version and the .dll file version supposed to be the same?
2. If not, what does the .dll file version mean?

**Comment by Tornhoof** [comment]
No they don't match. A description on how it works is here https://github.com/dotnet/corefx/blob/master/Documentation/building/versioning.md#calculating-buildnumbermajor

**Comment by alx9r** [comment]
@Tornhoof Thank you.
