### ISSUE TITLE
System.IO.FileSystem inner loop tests are slow, take ~2 minutes

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#3192]
That's quite a bit slower than what we've been aiming for inner loop. Can we make them faster or move some to outer loop?

**Comment by stephentoub** [comment]
This is my fault.  I'll fix it.  I added several async reading/writing tests that are taking a long time due to testing lots of permutations of options.

**Comment by nguerrera** [comment]
Thanks!

**Comment by davidsh** [comment]
What is the guidlines for inner loop tests?  For example, I've noticed that the System.Net.Http tests have grown to almost 31+ seconds.  They used to take only 5 seconds.  But the recent X-PLAT work has added more core tests that are increasing the time.

I have already added an [OuterLoop] test to HttpClient which takes 30+ seconds on its own.

It would be nice to get a general guideline we should use. I might need to move some Http tests to [OuterLoop]

**Comment by nguerrera** [comment]
cc @joshfree

**Comment by nguerrera** [comment]
I'm not sure what happened, but these tests are even slower now on my machine. 
```
=== TEST EXECUTION SUMMARY ===
     System.IO.FileSystem.Tests  Total: 2110, Errors: 0, Failed: 0, Skipped: 0, Time: 328.075s
```

**Comment by stephentoub** [comment]
I'm not sure what changed.  I'm also not seeing them take nearly that long (are you running, but I am seeing them take ~50 seconds, which is a 10x increase from where they were a few days ago.

I see that the DirectoryLongerThanMaxLongPath_ThrowsPathTooLongException test is taking ~40 seconds of that.

@JeremyKuhne, can you take a look?

**Comment by weshaggard** [comment]
These tests are taking a really long time on my machine as well. 
```
  === TEST EXECUTION SUMMARY ===
     System.IO.FileSystem.Tests  Total: 2110, Errors: 0, Failed: 0, Skipped: 0, Time: 310.723s
```

While DirectoryLongerThanMaxLongPath_ThrowsPathTooLongException is taking a while, 55.07s for me the main one taking most of the time is PathWithReservedDeviceNameAsPath_ThrowsDirectoryNotFoundException which took 253.66s for my run.

**Comment by JeremyKuhne** [comment]
Something to do with being on corpnet probably. Investigating.
