### ISSUE TITLE
Add constructor to BigInteger that accepts a ReadOnlySpan<byte>

### ISSUE THREAD

**Issue by Mirandatz** [dotnet/corefx#31924]
The [current constructor](https://docs.microsoft.com/en-us/dotnet/api/system.numerics.biginteger?redirectedfrom=MSDN&view=netcore-2.1#constructor) expect a `byte[]`, so if we are using Spans, we need to call `.ToArray()` and allocate a new byte array.

**Comment by EgorBo** [comment]
there is one: https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Numerics/src/System/Numerics/BigInteger.cs#L257

**Comment by Mirandatz** [comment]
I can't believe I didn't see that one. Sorry to bother.
