### ISSUE TITLE
MissingMethodException thrown when loading NetStandard libraries via System.Composition.Hosting

### ISSUE THREAD

**Issue by shueybubbles** [dotnet/corefx#31939]
hey there, I opened this issue in coreclr at https://github.com/dotnet/coreclr/issues/19632 
But I am unable to reproduce the issue with a non-composition based app that references the same NuGet package. Can you look at the issue I opened under coreclr and determine if it is specific to the hosting scenario?

**Comment by shueybubbles** [comment]
oh the broken EXE can be found at https://github.com/Microsoft/sqltoolsservice/releases/download/v1.5.0-alpha.28/microsoft.sqltools.servicelayer-win-x64-netcoreapp2.1.zip 

just run MicrosoftSqlToolsCredentials.exe

**Comment by 0xd4d** [comment]
I saw some assemblies being loaded more than once (multiple load contexts):

- 2x Microsoft.SqlServer.ConnectionInfo.dll
- 2x Microsoft.SqlServer.Management.Sdk.Sfc.dll
- 3x System.Data.Common.dll
- 8x netstandard.dll

Could be a bug in Microsoft.SqlTools.Extensibility.AssemblyLoader.Load(), it creates new temporary assembly loaders.

**Comment by karelz** [comment]
Looks like it is getting some traction in CoreCLR repo: https://github.com/dotnet/coreclr/issues/19632#issuecomment-415915854.
Let's keep just 1 issue opened. Closing this one as dupe.
