### ISSUE TITLE
Duplicate files in ZipArchiveEntry

### ISSUE THREAD

**Issue by IrakliLomidze** [dotnet/corefx#31941]
There is a issue, ZipArchiveEntry allowing to put **duplicate** files in zip archive, but then they could not be distinguished to be extracted.

Here is a code demonstrate issue:

```c#
    static void Main(string[] args)
        {
            String CurrentDirectory = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            String Text1 = "Text1";
            String Text2 = "Text2";

            String File1 = Path.Combine(CurrentDirectory,"1.txt");
            String File2 = Path.Combine(CurrentDirectory,"2.txt");

            File.WriteAllText(File1, Text1);
            File.WriteAllText(File2, Text2);

            String ZipFileName = Path.Combine(CurrentDirectory, "Archive.zip");

            using (ZipArchive zf = ZipFile.Open(ZipFileName, ZipArchiveMode.Create))
            {
                zf.CreateEntryFromFile(File1, "i.txt");
            }

            using (ZipArchive zf = ZipFile.Open(ZipFileName, ZipArchiveMode.Update))
            {
                zf.CreateEntryFromFile(File2, "i.txt");
            }

            // Now in Zip File we have two i.txt file

            
            using (ZipArchive zf = ZipFile.OpenRead(ZipFileName))
            {
                foreach (ZipArchiveEntry entry in zf.Entries)
                {
                    Console.WriteLine($"Fullname : { entry.FullName} Name {entry.Name}");
                }
            }
        
        }
```

Both Entries are same name it is impossible to extract right one.

**Comment by MarcoRossignoli** [comment]
I think it's by-design https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.IO.Compression/src/System/IO/Compression/ZipArchive.cs#L164

**Comment by IrakliLomidze** [comment]
It would be nice to have possibility to somehow differentiate entries with same name in the archive.
Or as a fast solution this behavior should put in Product documentation as note.

**Comment by MarcoRossignoli** [comment]
It's in the doc https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.zipfileextensions.createentryfromfile?view=netcore-2.1 under "Remarks"

**Comment by IrakliLomidze** [comment]
Ok nice, When I read that docs it was not here.
As it is default behavior, we should not change it, to not to break code.
But it will be nice to add two additional methods
CreateEntryFromFile(..., bool overWriteIfexists)
and
CreateEntryFromFile(..., bool SaveWrite) // Rise an exception if duplicate

How do you thinks is it reasonable to create such two simple methods and add it to corefx library ?

**Comment by MarcoRossignoli** [comment]
You should fill an issue with your proposed new api. Check workflow in this doc https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md
Run this query for some sample https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=label%3Aapi-suggestion+

**Comment by ViktorHofer** [comment]
Thanks @MarcoRossignoli for helping out here. Right, please open a separate issue an follow the api proposal format. Thanks!
