### ISSUE TITLE
Incorrect Uri.IsWellFormedUriString result when Unicode is present

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefx#31956]
.NET 4.5+ app

https://docs.microsoft.com/en-us/dotnet/api/system.uri.iswellformeduristring?view=netframework-4.7.2

`"http://domain.com/ and http://test.com"` returns false which is expected

`"http://domain.com/ sekä http://test.com"` returns true which is not expected. Removing the unicode `ä` changes the result to false.

I'm not an RFC 3986 expert but the second string does not look like a valid URI to me.

**Comment by davidsh** [comment]
@rmkerr

**Comment by karelz** [comment]
@JamesNK does it fail on .NET Framework, or also on .NET Core?
Did you try to target latest .NET Framework? There were Uri improvements and bug fixes in latest versions and some light up only if you target latest (4.7.2).

**Comment by JamesNK** [comment]
This is on .NET Framework 4.7.

**Comment by rmkerr** [comment]
Interesting! Thanks for reporting this. Since the issue also occurs in .NET Core I think we can leave this open to track progress.

There is clearly a bug here in how we handle Unicode in `IsWellFormedUriString`. @JamesNK have you been able to narrow down the repro at all? It would be nice to know if `IsWellFormedUriString` always returns true when Unicode is present, or if it is something about that particular string.

**Comment by MarcoRossignoli** [comment]
@rmkerr i did some tests(my analysis is not complete)
This passes.
```cs
[Fact]
[Trait("MyTrait", "MyTraitValue")]
public void UriIsWellFormed_AbsoluteWellFormed_Unicode_Failure()
{
   Assert.True(Uri.IsWellFormedUriString("http://domain.com/  ©", UriKind.Absolute));
   Assert.False(Uri.IsWellFormedUriString("http://domain.com/  t", UriKind.Absolute));            
}
```
Maybe something related to [this](https://github.com/dotnet/corefx/blob/master/src/System.Private.Uri/src/System/UriExt.cs#L423) and [this](https://github.com/dotnet/corefx/blob/master/src/System.Private.Uri/src/System/Uri.cs#L4590) 
Seems that the check for "valid" Iri is too simple...but i as said i'm not sure for now, next days i'll do more deeper analysis.
