### ISSUE TITLE
System.IO.Pipelines, System.Buffers, and Socket Async Task Extensions Experience

### ISSUE THREAD

**Issue by garethwarry** [dotnet/corefx#31953]
**Summary**
This issue tracks my experience when attempting to use System.IO.Pipelines and Socket Async Task Extensions together. Ultimately, I was not blocked by non-production ready features, but I was drawn away from a number of design choices that made implementation difficult or unnecessarily complex (against the goal of the pipelines framework). Sorry if I'm a bit critical in my grievances. 

**API Grievances** 
Though a large grievance with both System.IO.Pipelines and Socket Async Task Extensions is documentation, I recognize this is only a temporary issue. My main grievance is API design. When attempting to inherit from PipeReader to create a SocketPipeReader, I found that API methods simply didn't make sense. 

For example, why does SequencePosition exist rather than using an integer (like how IBufferWriter implements Advance)? Why was that deviation made to create SequencePosition, which is a readonly class that must be constructed using some generic object (that again, isn't documented and is just called "@object" which not even the source code gives a hint at for the purpose of exposing that)? Why does PipeWriter implement it with an integer rather than SequencePosition? Why isn't there an IBufferReader, by the way for System.Buffers? It's just messy. 

And in terms of canceling a async read operation for PipeReader, a cancellation token passed into the initial ReadAsync that then calls into an accepted client socket's ReceiveAsync flatly doesn't work. You cannot cancel the ReceiveAsync operation at all. Why is that? It just means I have to now write a task wrapper around it for the already wrapper I had to write to create the ReadResult return (since it doesn't just return a span of the portion of memory you haven't consumed yet). And am I supposed to be able to override how the base class constructs the buffer and pass in my own preallocated buffer assigned to the client socket on connect? Or am I supposed to just use the base class as an interface, because it doesn't seem like I have access to anything when it comes time to call ReceiveAsync in the pipe reader's ReadAsync. 

In regards to OnWriterCompleted and OnReaderCompleted, why is a state passed? I couldn't wrap my head around any scenario that utilized it. All your tests pass in "null" as the state. Why is it there if it's just to override the action? Also, why isn't it just an action you can set, like the Completed EventHandler in SocketAsyncEventArgs? Why this new weird way of setting the action? The documentation in the source code also doesn't explain it. Not to mention issue #31695 where the callback might be called unsafely. Just makes me concerned, given the API's design not being to solid either (which is where my "not production ready" comment came from. It just doesn't seem like this API design meshes well with any other framework released with dotnet core 2.1, while System.Buffers and Socket Async Task Extensions seems to work really well together.

**Pipelines is not about pipes**
When I think of a default pipe reader or pipe writer, I think of a continuous sequence of memory, where reads and writes to that memory block are matched one-to-one unless multiple reads are required to consume a single write (PipeReader), or multiple writes are required to consume multiple reads (PipeWriter). This is probably my largest problem with Pipelines, in that none of these classes are actually just pipes. The default functionality delivered by System.IO.Pipelines is actually the default functionality of a _non-buffered channel_. Channels allow two threads to pass data efficiently, where one thread writes data and one thread reads data. In fact, there's an alpha of System.Threading.Tasks.Channels on nuget that then redirects to Pipelines from the author that told me to create this post.......... https://github.com/davidfowl/Channels. So where did this confusing mislabeling come from? Also, there's a System.Threading.Channels that implements Pipelines... but a lot better... It makes me really confused as to why Pipelines was created.

**Comment by Wraith2** [comment]
I'm trying to use this `System.IO.Pipelines` as well and while I'm not as far through the process as you are your concerns echo my experience. I've been getting some help from @mgravell and his unofficial pipeline library as well as the articles he's been writing about it.

The `SequencePosition` api does feel awkward because I'm not sure when I'm supported to convert to and from it other than when I find that I can't do what I need to with what I have. Documentation may help with this but currently it doesn't seem to have a pattern I can recognise.

Another thing that has bothered me is that I had to work through the codebase to identify that there is no way to construct a `ReadOnlySequence<>` around arbitrary data to write tests for consumers of the data.

**Comment by jkotas** [comment]
cc @pakrym @davidfowl

**Comment by mgravell** [comment]
FYI, a fake multi-segment for testing purposes can be done via something like below. I'd be happy to throw it into "unofficial" if it would be generally helpful.

```c#
        private class FragmentedSegment<T> : ReadOnlySequenceSegment<T>
        {
            public static ReadOnlySequence<T> Create(IEnumerable<ReadOnlyMemory<T>> pieces)
            {
                long offset = 0;
                using (var iter = pieces.GetEnumerator())
                {
                    if (!iter.MoveNext()) return default;
                    var chain = new FragmentedSegment<T>(ref offset, iter.Current);
                    var last = chain;
                    while(iter.MoveNext())
                    {
                        var next = new FragmentedSegment<T>(ref offset, iter.Current);
                        last.Next = next;
                        last = next;
                    }
                    return new ReadOnlySequence<T>(chain, 0, last, last.Memory.Length);
                }
            }
            private FragmentedSegment(ref long runningIndex, ReadOnlyMemory<T> memory)
            {
                RunningIndex = runningIndex;
                Memory = memory;
                runningIndex += memory.Length;
            }
            public new FragmentedSegment<T> Next
            {
                get => (FragmentedSegment<T>)base.Next;
                set => base.Next = value;
            }
        }
```

**Comment by AArnott** [comment]
> there is no way to construct a ReadOnlySequence<> around arbitrary data to write tests for consumers of the data.

I noticed the same thing. That's why I wrote [`Sequence<T>`](https://github.com/AArnott/Nerdbank.Streams/blob/master/doc/Sequence.md), which acts as a builder for `ReadOnlySequence<T>`. Please use it [via the Nerdbank.Streams NuGet package](https://nuget.org/packages/Nerdbank.Streams).

**Comment by AArnott** [comment]
> a fake multi-segment for testing purposes can be done via something like below

@mgravell I think your sample is missing handling of `AdvanceTo` and perhaps some other scenarios. It might be adequate for unit testing purposes, depending on how exhaustively they exercise `ReadOnlySequence<T>` functionality, but I'd rather go with the `Sequence<T>` implementation I prescribed above.

**Comment by mgravell** [comment]
As long as we're talking about the ReadOnlySequence API, the example shown
*should* be sufficient - everything else is handled from the chain. If
there's a specific example of a ReadOnlySequence usage that fails, if be
very interested.

**Comment by AArnott** [comment]
Ah, fair enough.

**Comment by davidfowl** [comment]
The team has read the feedback and will be looking at tackling some of these issues in future releases. Thanks for the feedback!
