### ISSUE TITLE
HttpClient connections throwing System.Net.Sockets.SocketException after 21 seconds

### ISSUE THREAD

**Issue by Tadimsky** [dotnet/corefx#31951]
We have an issue in our services (running ASP.Net Core 2.1) where it takes about 21 seconds for `HttpClient` to "realize" that the service it is trying to connect to is down.

The message we finally get is:
`
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
`
We then retry on a different service and that works, but it means our requests take 21+ seconds longer (and clients sometimes timeout because of it):

![image](https://user-images.githubusercontent.com/1149244/44613387-90889200-a7c7-11e8-936c-b1d4ef4725b6.png)

Is there a way to modify this timeout? Ideally we'd want it set to something more like 5 seconds.
It seems like it's a generic TCP timeout.

**Comment by davidsh** [comment]
TCP timeouts are generally on the order of 21 seconds which is 7 seconds per each of the 3-legged SYNC, SYNC-ACK, ACK handshake.  This is not currently configurable via HttpClient API since it is a low-level TCP timeout.

**Comment by karelz** [comment]
I don't think that Windows supports changes to these timeouts - only via reg keys.
If that's true, then this seems to be by design and we should close the question as answered.

**Comment by davidsh** [comment]
See:
http://getin2me.blogspot.com/2010/08/are-you-also-facing-windows-sockets-21.html

**Comment by timabell** [comment]
For the googlers arriving here: https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

**Comment by karelz** [comment]
I don't think there is anything left here for us to do.
