### ISSUE TITLE
please open-source midori, and make dotnet core valid for system programming!

### ISSUE THREAD

**Issue by juepiezhongren** [dotnet/corefx#31954]
@ayende i still guess midori is something precisely what you want

midori is the treasure, given the 11 kinds of gc collectors mentioned in joe's article http://joeduffyblog.com/2015/12/19/safe-native-code/ and more.

**Comment by karelz** [comment]
This is way out of scope of CoreFX - closing. You can try to ask on more general / Microsoft-wide repos, but this kind of decision needs some executive / VP-level support and likely some reasonable business case.
