### ISSUE TITLE
ExecutionContext not always cleared when ConnectEventArgs is pooled

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#31969]
`SocketAsyncEventArgs._context` is still set when they are in the `ConnectHelper.s_connectEventArgs` collection.

![image](https://user-images.githubusercontent.com/1142958/44637655-6511cd00-a9aa-11e8-8b95-8655fffc5e48.png)

Observed in https://github.com/aspnet/KestrelHttpServer/issues/2840#issuecomment-416034872

/cc @davidfowl @stephentoub

**Comment by stephentoub** [comment]
Addressed by https://github.com/dotnet/corefx/pull/30712, no?

**Comment by benaadams** [comment]
Ah, yes! Explains why I couldn't find how it was happening in the code 😄

**Comment by benaadams** [comment]
Ah, fixed in 3.0, not 2.2... Will reopen for now then 😄 

Replying to @karelz in https://github.com/dotnet/corefx/issues/30670

> What is the impact of the bug? Which scenarios are impacted? How bad is it? How common are the scenarios?

**What is the impact of the bug?**

Capturing the aspnet HttpContext and all associated data, model dictionary, user, HttpConnection, Pipe, Socket, etc and holding on to them when they should be GC'd

**Which scenarios are impacted?**

For https://github.com/dotnet/corefx/pull/30712 making an HttpClient request from aspnet, so a lot? 

![image](https://user-images.githubusercontent.com/1142958/44656610-703c1b80-a9f1-11e8-9f56-36b294cff88e.png)

For https://github.com/dotnet/coreclr/pull/18670 compiling a Razor page; though hopefully mitigated by https://github.com/aspnet/Common/pull/392. Though any user created CancellationTokenSources would have same issue?

![image](https://user-images.githubusercontent.com/1142958/44656458-d5dbd800-a9f0-11e8-835d-eaf9b99fc1b4.png)

**How bad is it?**

It should be capped (so only cause high memory usage); however are user reports of process kills due to OOM at 4.5GB https://github.com/aspnet/KestrelHttpServer/issues/2840; also https://github.com/dotnet/corefx/pull/30712#issuecomment-401576420

**How common are the scenarios?**
Using any logging in aspnet, hopefuly fixed by https://github.com/aspnet/Hosting/pull/1531

Using `IHttpContextAccessor`; which is unfortunately a common pattern (e.g. just add Application Insights)

With 2.2 preview
```
dotnet new mvc

Add Application Insights (upgrade to latest)

dotnet run -c Release

Access urls...
```

So I'd say pretty common; the templated starting point + AI will do it

> The bug bar for 2.2 is not clear yet. @danmosemsft likely knows more at this point.

@danmosemsft @karelz can https://github.com/dotnet/corefx/pull/30712 and https://github.com/dotnet/coreclr/pull/18670 be considered for 2.2?

**Comment by karelz** [comment]
We can consider it for 2.2 or even 2.1.x IMO.
To make the case it would help to provide some numbers. Lots of issues above have workarounds higher up in the stack. Would it be possible to measure one of them (e.g. https://github.com/aspnet/KestrelHttpServer/issues/2840 leading to OOM) with and without the fix to justify the change? (it would also serve as verification that the fix is the key problem in the scenario(s))

**Comment by geoffkizer** [comment]
It's a little scary that ASPNET puts the HttpContext into the ExecutionContext. ExecutionContext flow (which happens on async invocation) is optimized for using the default EC. There may be some added overhead in flowing non-default ECs. Not sure, but this might be worth looking into...

**Comment by davidfowl** [comment]
@geoffkizer a necessary evil to satisfy our customers that need access to the "current" http request. It's not on by default but can be turned on.

**Comment by geoffkizer** [comment]
> It's not on by default but can be turned on.

Ah, cool. 

If it's common to use this, it might be worthwhile seeing if there's more we can do to optimize EC flow for non-default ECs. It's been a while since I've looked at that code so I don't really know.

**Comment by davidfowl** [comment]
> If it's common to use this, it might be worthwhile seeing if there's more we can do to optimize EC flow for non-default ECs. It's been a while since I've looked at that code so I don't really know.

Yes, it's very common. Logging is the other thing that we make use of async local for. We basically have a connection scope and a request scope so all logs get tagged with the appropriate fields.

**Comment by benaadams** [comment]
> Would it be possible to measure one of them (e.g. aspnet/KestrelHttpServer#2840 leading to OOM) with and without the fix to justify the change?

/cc @HassanHashemi

**Comment by HassanHashemi** [comment]
@geoffkizer this is the results i got after 50K request in 30 minutes.

![image](https://user-images.githubusercontent.com/6805984/44947525-0215a100-adc3-11e8-8ff4-0737a12091fb.png)

> Would it be possible to measure one of them (e.g. aspnet/KestrelHttpServer#2840 leading to OOM) with and without the fix to justify the change?

I will gladly do that.

**Comment by karelz** [comment]
Looks like we dropped the ball on this one for 2.2.
Is it fixed in 3.0? Is everyone ok-ish if it does not get addressed earlier?

**Comment by stephentoub** [comment]
> Is it fixed in 3.0?

Yes

**Comment by benaadams** [comment]
>  Is everyone ok-ish if it does not get addressed earlier?

ASP.NET Core has improved on what it stores in the EC for 2.2 so that should greatly help before then

**Comment by karelz** [comment]
OK, closing then.
If we see the imapct on 2.1 or 2.2 is still significant, we can create a new issue with clear evidence and bring it for servicing of 2.1/2.2.
