### ISSUE TITLE
Expression interpreter - IsTrue, IsFalse, UnaryPlus missing cases

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#3196]
Evaluating the following expressions results in NotSupportedException, where it doesn't for the compiler. It seems there's the wrong assumption those node types are always used in conjunction with a method, but that's not the case for primitive types:

Test<bool>(Expression.IsTrue(Expression.Constant(true)));
Test<bool>(Expression.IsFalse(Expression.Constant(true)));
Test<int>(Expression.UnaryPlus(Expression.Constant(42)));

where Test<T> is a simple wrapper around Expression.Lambda<Func<T>>(e).Compile()()

**Comment by VSadov** [comment]
closed in https://github.com/dotnet/corefx/pull/3227
