### ISSUE TITLE
API proposal: Expose CancellationToken.Register overload that doesn't capture the ExecutionContext

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#31968]
There's an internal method that already does this today ([InternalRegisterWithoutEC](https://github.com/dotnet/coreclr/blob/57cdf454b123a44ef8d5944f4022b9502ce52d8a/src/System.Private.CoreLib/shared/System/Threading/CancellationToken.cs#L225)) that we should rename and expose (or just expose a new public method that does the same thing). ASP.NET Core uses an async local to expose the "current" HttpContext during a request flow. Combining that with long lived cancellation tokens lazily registered during a request that may outlive a request, we end up rooting the HTTP Context and other async locals (logging scopes) unnecessarily. This can result in a memory leak in some cases https://github.com/aspnet/KestrelHttpServer/issues/2840#issuecomment-416034872

@benaadams sent a couple of PRs to help solve this in some of the CoreFX APIs for other things that capture the execution context implicitly https://github.com/dotnet/corefx/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Abenaadams+is%3Aclosed+asynclocals

## Proposal

```C#
public struct CancellationToken
{
    public CancellationTokenRegistration UnsafeRegister(Action<object> callback, object state, bool useSynchronizationContext);
}
```

This is already an advanced overload so to call it, you need to pass everything in.

**Comment by tarekgh** [comment]
@stephentoub I think the proposal is reasonable. please let me know if you have any concern so we can mark this as ready for design review. Thanks.

**Comment by stephentoub** [comment]
I don't have a strong opinion, other than if it is exposed it should be named UnsafeRegister rather than taking a bool.

**Comment by tarekgh** [comment]
@davidfowl  if you agree with @stephentoub, please update the proposal and we can move forward with it.

**Comment by davidfowl** [comment]
Updated

**Comment by davidfowl** [comment]
I hate the name unsafe but we can be consistently terrible 😄

**Comment by terrajobst** [comment]
Looks good but we probably want to default the sync context to false.

```C#
public struct CancellationToken
{
    public CancellationTokenRegistration UnsafeRegister(Action<object> callback, object state, bool useSynchronizationContext = false);
}
```

**Comment by davidfowl** [comment]
Yes we do!

**Comment by tarekgh** [comment]
@davidfowl will you help adding the implementation? just checking :-)

**Comment by stephentoub** [comment]
I'll take care of it.

Also, I think we should start without the `bool useSynchronizationContext` argument at all.  Reason:
1) No one uses useSynchronizationContext == true.
2) I don't want to encourage people to use useSynchronizationContext == true, and having it on the sole UnsafeRegister overload and showing up in IntelliSense might encourage people to try it out.
3) This UnsafeRegister overload maps to a corresponding Register overload, but Register doesn't use an optional argument.
4) If we ever decide we want to expose useSynchronizationContext (I don't imagine that ever happening), we can add it as an overload and remain consistent with Register.

I'm going to proceed on the path of not including it.  @terrajobst, please yell if that's a problem :)

**Comment by davidfowl** [comment]
@tarekgh I don't have any immediate bandwidth 😄

**Comment by tarekgh** [comment]
@davidfowl  no problem, @stephentoub already have PR's ready fo t hat :-)
