### ISSUE TITLE
FileSystemWatcher captures AsyncLocals on Linux (but not on Windows)

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#31973]
On Linux FileSystemWatcher uses CancelationToken.Register

https://github.com/dotnet/corefx/blob/39c4ddf1cbc0435d981c9b28ac0fe3aa1dcaac3b/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Linux.cs#L524-L529

Which captures the AsyncLocals via ExecutionContext. This behaviour differs to that on Windows (which doesn't capture the context)

**Comment by stephentoub** [comment]
> This behaviour differs to that on Windows (which doesn't capture the context)

Do you have a repro? I just did a quick test and it does appear to flow on .NET Core on Windows. The code uses Overlapped.Pack, which flows ExecutionContext.

**Comment by benaadams** [comment]
Looks like it is correct then. Will have to suppress the flow upstream.
