### ISSUE TITLE
It is impossible to determine whether the OrderedDictionary is empty without extra allocations

### ISSUE THREAD

**Issue by iSazonov** [dotnet/corefx#31972]
### Problem

There is no way to determine that the OrderedDictionary is empty without extra allocations.

All properties in OrderedDictionary check internal helper variables and allocate if it is null.
Example:
https://github.com/dotnet/corefx/blob/e0ba7aa8026280ee3571179cc06431baf1dfaaac/src/System.Collections.Specialized/src/System/Collections/Specialized/OrderedDictionary.cs#L128

In PowerShell repo we had to use workaround in helper class to exclude tons of extra allocations.
The fix is in https://github.com/PowerShell/PowerShell/pull/7435 - there you can see that we allocate ~4Gb before the fix and ~1Gb after the fix.

### Proposal

1. Minimally - add null check in Count propery
```c#
    public class OrderedDictionary : IOrderedDictionary, ISerializable, IDeserializationCallback
    {
        public int Count
        {
            get
            {
                if (_objectsArray == null)
                {
                    return 0;
                }
                return _objectsArray.Count;
            }
        }
    }
```
2. Full fix should exclude such extra allocations from all properties.

**Comment by danmosemsft** [comment]
Thanks for the report. Do you want to offer a PR?

**Comment by iSazonov** [comment]
@danmosemsft The PR is pushed.
