### ISSUE TITLE
Test failure: System.Console.Tests.TermInfo/VerifyTermInfoSupportsNewAndLegacyNcurses()

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#31984]
The test `System.Console.Tests.TermInfo/VerifyTermInfoSupportsNewAndLegacyNcurses()` has failed.

System.InvalidOperationException : The terminfo database is invalid. 

Stack Trace: 
```
at System.TermInfo.Database..ctor(String term, Byte[] data) 
at System.TermInfo.Database.ReadDatabase(String term, String directoryPath)
```

Failing in: `macOS Mojave (10.14)`
Not in: `macOS High Sierra (10.13)`

branch: release/1.0.0

**Comment by stephentoub** [comment]
@maryamariyan, this is failing in release/1.0.0 but not in other branches?

**Comment by karelz** [comment]
.NET Core 1.0 is out of support as of 2019/6/27 - https://github.com/dotnet/core/blob/master/microsoft-support.md#out-of-support-net-core-releases
