### ISSUE TITLE
Test failure: System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern/CurrencyNegativePattern_Get(locale: \"fa-IR\")

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#31983]
The test `System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern.CurrencyNegativePattern_Get(locale: "fa-IR")` has failed.

Assert.Contains() Failure
    Not found: 1
    In value: Int32[] [8]

Failing in: `macOS Mojave (10.14)`
Not in: `macOS High Sierra (10.13)`

branch: release/1.0.0

**Comment by danmosemsft** [comment]
This is because it has a newer ICU version. IT is a test issue only. It would be fixed by porting your own change https://github.com/dotnet/corefx/commit/fe548ac62bdc46785e7e153a5f2a3de15daefd6d and what it depends on. Probably not worth it.

**Comment by tarekgh** [comment]
@danmosemsft do we need to fix the test for 1.0.x release? I believe we already fixed that for later versions.

**Comment by tarekgh** [comment]
I am closing this as won't fix for now and let's visit if we get more hits on that.

**Comment by danmosemsft** [comment]
Yep fine.
