### ISSUE TITLE
LoadWithPartialName should not throw according to documentation

### ISSUE THREAD

**Issue by LasseNisted** [dotnet/corefx#31999]
According to the documentation at
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.loadwithpartialname?view=netcore-2.1
Assembly.LoadWithPartialName should not throw a FileNotFoundException. And this is also the case in .NET Framework 4.7.1. However, in .NET Core 2.1 it is implemented via Assembly.Load which throws. The documentation or implementation should be updated.

**Comment by jkotas** [comment]
This issue was moved to dotnet/coreclr#19817
