### ISSUE TITLE
System.DirectoryServices.Protocols not supported on UWP?

### ISSUE THREAD

**Issue by harvinders** [dotnet/corefx#31996]
I has trying to use `LdapConnection` in a UWP app and I get following exception. [#2089](https://github.com/dotnet/corefx/issues/2089) mentions that `System.DirectoryServices.Protocols` works on windows platform. Am I missing something or it really does not work on UWP?

```
System.PlatformNotSupportedException: System.DirectoryServices.Protocols is not supported on this platform.
   at System.DirectoryServices.Protocols.DirectoryConnection..ctor()
   at System.DirectoryServices.Protocols.LdapConnection..ctor(String server)
   at App2.App.OnLaunched(LaunchActivatedEventArgs e)
```

**Comment by filipnavara** [comment]
I don't think the LDAP APIs (eg. ldap_init) are available to UWP apps. Besides, your question was already answered in the issue you linked:

> Hi, will this work in UWP?

No, it is supported only for net core apps running on Windows and full framework. if you use it in UWP or on Linux, you'll get a PlatformNotSupported exception.

**Comment by dbeavon** [comment]
I'm new to UWP (and to .Net core too for that matter).  I see that work was done to allow System.DirectoryServices.Protocols in core. (see https://github.com/dotnet/corefx/issues/2089 for the history of that work) 

Why would that work not impact UWP as well?  I'm trying to add the nuget for System.DirectoryServices.Protocols and it give me the "not supported" error at runtime.  I also tried including the package "Microsoft.Windows.Compatibility", which has S.DS.P too, but had no luck there either.

It is confusing to me that this would fail on UWP.  It's like someone went out of their way to disable this for UWP apps.  The errors don't appear to be related to capabilities in my manifest.  It just seems like a bogus platform incompatibility.
