### ISSUE TITLE
"Common Language Runtime detected an invalid program" with System.Collections.Immutable

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefx#320]
I am getting the following error below from System.Collections.Immutable.1.1.33-beta.

	2) Test Error : Newtonsoft.Json.Tests.Serialization.ImmutableCollectionsTests.DeserializeListInterface
	   System.InvalidProgramException : Common Language Runtime detected an invalid program.
	   at System.Collections.Immutable.SecurePooledObject`1.Use[TCaller](TCaller& caller)
	   at System.Collections.Immutable.ImmutableList`1.Enumerator.ResetStack()
	   at System.Collections.Immutable.ImmutableList`1.Enumerator..ctor(Node root, Builder builder, Int32 startIndex, Int32 count, Boolean reversed)
	   at System.Collections.Immutable.ImmutableList`1.GetEnumerator()
	   at System.Collections.Immutable.ImmutableList`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
	   at System.String.Join(String separator, IEnumerable`1 values)
	   at Newtonsoft.Json.Tests.Serialization.ImmutableCollectionsTests.DeserializeListInterface() in c:\Development\Source\Json\Newtonsoft.Json\Src\Newtonsoft.Json.Tests\Serialization\ImmutableCollectionsTests.cs:line 111

I get this error when running this test from nunit-console.exe or the ReSharper test runner, while it runs without issue with TestDriven.NET.

**Comment by taylorjg** [comment]
I have exactly the same problem. I am using the same version of the immutable collections. Other relevant version info:

* VS 2012
* NUnit 2.6.3
* ReSharper 7.1.2

In my case, if I select "Debug Unit Tests" from the ReSharper menu (instead of "Run Unit Tests"), then the unit tests run fine (with or without any breakpoints set). So, this is my current workaround.

**Comment by akoeplinger** [comment]
Did you try running the test in a simple console app without any NUnit references (to rule out issues with NUnit)?

**Comment by taylorjg** [comment]
Yes - I should have mentioned that. My console project runs fine when I run it via F5 or CTRL+F5. It is the test class library project that has the problem.
FYI - here is a link to my VS solution where the problem can be seen (see the Tests project):
https://github.com/taylorjg/PotterDictionary

**Comment by VictorBlomberg** [comment]
I had the same problem when deploying my project (compiled to 4.5 with Visual Studio 2012) to a production IIS server (7). Works flawlessly on my local desktop.

```
[InvalidProgramException: Common Language Runtime detected an invalid program.]
   System.Collections.Immutable.SecurePooledObject`1.Use(TCaller& caller) +0
   System.Collections.Immutable.Enumerator.ResetStack() +87
   System.Collections.Immutable.Enumerator..ctor(Node root, Builder builder, Int32 startIndex, Int32 count, Boolean reversed) +1064
   System.Collections.Immutable.Node.GetEnumerator() +157
   System.Collections.Immutable.Node.TrueForAll(Predicate`1 match) +101
[...]
```

**Upgrading .NET Framework from 4.5.1 to 4.5.2 (via Windows Update) solved the issue for me.**

**Comment by cptjazz** [comment]
I have the same issue. I was running the tests with ReSharper.
What I noticed: Running the test "As Debug" works, running it "As Release" triggers the exception. I guess this hits a corner case in the compiler's optimizer tricking the JITter to yield invalid code?

**Comment by cptjazz** [comment]
An update to .NET 4.5.51209 (https://support.microsoft.com/kb/2901983) resolved the problem for me.

**Comment by theoy** [comment]
As referenced by dotnet/roslyn#110, we were seeing hits for this problem in Roslyn as well :smile:

**Comment by nguerrera** [comment]
PR #687 in progress with fix.

**Comment by theoy** [comment]
Awesome! Thanks, @nguerrera! :smile:
