### ISSUE TITLE
segfault running System.Security.Cryptography "Algorithms" and "OpenSsl" tests

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#32003]
As reported earlier in issue dotnet/corefx#31743, building corefx and coreclr in release branch 1.1.0 on macOS High Sierra and Mojave (versions 10.13+) segfaults during init-tools command.

In addition to that, when using binary bits built from macOS Sierra (10.12) I noticed the following two security test projects also got segfaults:
-	System.Security.Cryptography.Algorithms.Tests
-	System.Security.Cryptography.OpenSsl.Tests

Below has some information about the call stack which is the same for both `System.Security.Cryptography.OpenSsl.Tests` and `System.Security.Cryptography.Algorithms.Tests` taken from the coredump:

 ```
(lldb) bt
* thread #13, stop reason = signal SIGSTOP
  * frame #0: 0x000000010f5b8ef2 libcrypto.1.0.0.dylib`BN_num_bits
    frame #1: 0x000000010f56cd7f System.Security.Cryptography.Native.OpenSsl.dylib`___lldb_unnamed_symbol67$$System.Security.Cryptography.Native.OpenSsl.dylib + 575
    frame #2: 0x000000010f56ce8b System.Security.Cryptography.Native.OpenSsl.dylib`___lldb_unnamed_symbol68$$System.Security.Cryptography.Native.OpenSsl.dylib + 91
```

Segfault in: `macOS Mojave (10.14)` and `macOS High Sierra (10.13)` 
(from mission control seems like an all Unix issue)
branch: release/1.1.0

cc: @bartonjs @leecow

**Comment by danmosemsft** [comment]
Do we know the tests work OK on Sierra? (I assume so as they were probably originally developed on Sierra)

I wonder if the OpenSSL headers we build against on Sierra do not match the libcrypto version on High Sierra/Mojave.

**Comment by maryamariyan** [comment]
@danmosemsft I don't think it works on Sierra or even other Unix distros (basing my observation from mission control)

**Comment by krwq** [comment]
@maryamariyan do you perhaps know if the test projects getting segfault when running tests or when preparing for execution?

**Comment by karelz** [comment]
1.1 is out of support as of 2019/6/27 - https://github.com/dotnet/core/blob/master/microsoft-support.md#out-of-support-net-core-releases
