### ISSUE TITLE
How Can I Use ClientCertificates in HttpClientFactory.CreateClient

### ISSUE THREAD

**Issue by kugarliyifan** [dotnet/corefx#32005]
i use Microsoft.Extensions.Http library ,in my scene,only before call SendAsync function ,i can know use which X509Certificate,it just like that,i has many customer config data,when call the webapi,need to send the the customer's clientCertificate before call httpclient's sendasync function ,,but HttpClientFactory.CreateClient can't pass the new handler to client,   how can i solve the scene???any one can help me please

**Comment by davidsh** [comment]
@karelz - Where is HttpClientFactory repo?  This needs to be moved there.  I think it is ASP.NET.

**Comment by kugarliyifan** [comment]
@davidsh    i view the HttpClientFactory repo issues,,,too few member,,,,,,,

**Comment by karelz** [comment]
This issue was moved to aspnet/HttpClientFactory#164

**Comment by karelz** [comment]
@kugarliyifan that is the right place to file the issues though. Different set of people than here.
