### ISSUE TITLE
Code coverage builds are broken

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#32019]
```
D:\j\workspace\code_coverage---b14a30e5\Tools\dotnetcli\sdk\2.1.401-preview-009081\Microsoft.Common.CurrentVersion.targets(4533,5): error MSB3030: Could not copy the file "D:\j\workspace\code_coverage---b14a30e5\src\System.Globalization.Calendars\tests\CalendarTestWithConfigSwitch\coverage\xunit.console.runtimeconfig.json" because it was not found. [D:\j\workspace\code_coverage---b14a30e5\src\System.Globalization.Calendars\tests\CalendarTestWithConfigSwitch\System.Globalization.CalendarsWithConfigSwitch.Tests.csproj]
```
https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/

@ViktorHofer this predates your changes, but perhaps you could take a look?

We ideally would have a way to know more reliably when code coverage build breaks. I only seem to notice some time later.

**Comment by ViktorHofer** [comment]
looking...

**Comment by ViktorHofer** [comment]
> this predates your changes, but perhaps you could take a look?

bug introduced exactly by my change :/ I forgot to rename https://github.com/dotnet/corefx/blob/master/src/System.Globalization.Calendars/tests/CalendarTestWithConfigSwitch/coverage/xunit.console.netcore.runtimeconfig.json

**Comment by ViktorHofer** [comment]
> We ideally would have a way to know more reliably when code coverage build breaks. I only seem to notice some time later.

Could vendor take care of checking the coverage build same as they check test failures?
