### ISSUE TITLE
Test failure: System.IO.FileSystem.DriveInfoTests.DriveInfoUnixTests/PropertiesOfValidDrive()

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#32011]
The test `System.IO.FileSystem.DriveInfoTests.DriveInfoUnixTests/PropertiesOfValidDrive()` has failed.

Assert.Equal() Failure
Expected: Fixed
Actual:   Unknown

Stack Trace: 
```
at System.IO.FileSystem.DriveInfoTests.DriveInfoUnixTests.PropertiesOfValidDrive()
```

Failing in: `macOS Mojave (10.14)` and `macOS High Sierra (10.13)` locally
But succeeds on CI for OSX 10.11, 10.12 and 10.13. (refer to this [link](https://mc.dot.net/#/product/netcore/110/source/official~2Fcorefx~2Frelease~2F1.1.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20180622.01) and [this](https://mc.dot.net/#/product/netcore/100/source/official~2Fcorefx~2Frelease~2F1.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20180801.01))

in both branches: `release/1.0.0` and `release/1.1.0`

cc: @danmosemsft

**Comment by danmosemsft** [comment]
This would be fixed by porting https://github.com/dotnet/corefx/pull/21636. I don't think it's worth porting though..

**Comment by danmosemsft** [comment]
@shanselman I see you thumbsed-up -- is this something you're hitting? (That DriveInfo.DriveType on a default High Sierra/Mojave volume returns Unknown on 1.x)

**Comment by shanselman** [comment]
I thought I was but I was mistaken! Sorry to bother!

**Comment by danmosemsft** [comment]
No problem thanks @shanselman

**Comment by karelz** [comment]
.NET Core 1.0 is out of support as of 2019/6/27 - https://github.com/dotnet/core/blob/master/microsoft-support.md#out-of-support-net-core-releases
