### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.HttpClientTest/Timeout_SetTo60AndGetResponseFromServerWhichTakes40_Success()

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#32013]
The test `System.Net.Http.Functional.Tests.HttpClientTest/Timeout_SetTo60AndGetResponseFromServerWhichTakes40_Success()` has failed.

	      Assert.Equal() Failure
	      Expected: OK
	      Actual:   ServiceUnavailable

Failing in:
- Check [CI failures](https://mc.dot.net/#/product/netcore/100/source/official~2Fcorefx~2Frelease~2F1.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20180801.01/workItem/System.Net.Http.Functional.Tests).
- Also failed locally on both `macOS High Sierra (10.13)` and `macOS Mojave (10.14)` .

branch: release/1.0.0

cc: @karelz

**Comment by davidsh** [comment]
>Actual:   ServiceUnavailable

That looks like an Azure hiccup.

**Comment by karelz** [comment]
@maryamariyan can you try to rerun to weed out Azure hiccups? Otherwise it would be good to know if it is 100% repro.

**Comment by davidsh** [comment]
Closing since this was most likely infrastructure issue.
