### ISSUE TITLE
Console.CursorLeft throws IOException when running in Azure

### ISSUE THREAD

**Issue by Zexuz** [dotnet/corefx#32018]
The `Console.CursorLeft` throws a System.IO.IOException (Error at the bottom) when run in Azure as a 'App Service'.

Somewhat related issue? 
[Console.WindowWidth fails with IOException](https://github.com/dotnet/cli/issues/2780#issuecomment-417004184)

**Expected behavior**
Nothing would happen and no exception would be thrown.

**Observed behavior**
Exception is throw.

Steps to reproduce

- Crate a new .NET Core 2.1 WEB API.
- Add this code to the new `ValuesController.cs`
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {

        public static Exception ex { get; set; }

        // GET api/values
        [HttpGet]
        public ActionResult<IEnumerable<string>> Get()
        {
            Exception ex = null;
            try
            {
                int x = Console.CursorLeft;
                int y = Console.CursorTop;
                Console.CursorTop = Console.WindowTop + Console.WindowHeight - 1;
                Console.Write("Random text");
                Console.SetCursorPosition(x, y);
            }
            catch (Exception e)
            {
                ex = e;
            }


            return Ok(ex);
        }
        
    }
}
```
- publish as a new `App Service` in **Release** mode
- Open up a browser to <azureurl>/api/values

response should look like this.
```json
{
  "ClassName": "System.IO.IOException",
  "Message": "The handle is invalid",
  "Data": null,
  "InnerException": null,
  "HelpURL": null,
  "StackTraceString": "   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)\r\n   at WebApplication1.Controllers.ValuesController.Get() in C:\\Users\\Robin.Edbom\\source\\repos\\Delte me\\WebApplication1\\Controllers\\ValuesController.cs:line 23",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": null,
  "HResult": -2147024890,
  "Source": "System.Console",
  "WatsonBuckets": null
}
```

I choose run this code in a WEB API because it is a easy way to get the error back directly.

**Current workaround** : Delete the console code, I don't really need it.

**Comment by karelz** [comment]
App Service likely does not support Console at all, which would make it by design ...

**Comment by danmosemsft** [comment]
Based on the message I assume this is Windows. @Zexuz I assume you get the same behavior with .NET Framework.

**Comment by Zexuz** [comment]
I have not tried with .NET Framework. Sadly I have no time to try with .NET Framework. I just hope even if this does not get fixed, that if someone google the stack trace it lets them here to help them figure out why it does not work.
