### ISSUE TITLE
MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/corefx#32037]
When I build I am getting this weird error.

> Microsoft (R) Build Engine version 15.8.168+ga8fba1ebd7 for .NET Framework
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> **********************************************************************
> ** Visual Studio 2017 Developer Command Prompt v15.8.2
> ** Copyright (c) 2017 Microsoft Corporation
> **********************************************************************
> [vcvarsall.bat] Environment initialized for: 'x86_x64'
> Commencing build of native components
> 
> -- Selecting Windows SDK version  to target Windows 10.0.17134.
> CMake Error at CMakeLists.txt:21 (project):
>   Failed to run MSBuild command:
> 
>     C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe
> 
>   to get the value of VCTargetsPath:
> 
>     Microsoft (R) Build Engine version 15.8.168+ga8fba1ebd7 for .NET Framework
>     Copyright (C) Microsoft Corporation. All rights reserved.
> 
>     Build started 8/30/2018 8:01:41 PM.
>     Project "C:\Repos\corefx3\bin\obj\Windows_NT.x64.Debug\native\CMakeFiles\3.11.0\VCTargetsPath.vcxproj" on node 1 (default targets).
>     C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Repos\corefx3\bin\obj\Windows_NT.x64.Debug\native\CMakeFiles\3.11.0\VCTargetsPath.vcxproj]
>     Done Building Project "C:\Repos\corefx3\bin\obj\Windows_NT.x64.Debug\native\CMakeFiles\3.11.0\VCTargetsPath.vcxproj" (default targets) -- FAILED.
> 
>     Build FAILED.
> 
>     "C:\Repos\corefx3\bin\obj\Windows_NT.x64.Debug\native\CMakeFiles\3.11.0\VCTargetsPath.vcxproj" (default target) (1) ->
>     (_CheckWindowsSDKInstalled target) ->
>       C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Repos\corefx3\bin\obj\Windows_NT.x64.Debug\native\CMakeFiles\3.11.0\VCTargetsPath.vcxproj]
> 

OS: Win10 v. 1803
VS2017: 15.8.2

The machine was initially running VS 15.7.3 and I wanted to test #30094, so I used VS Installer to uninstall 15.7.3 and then installed 15.8.2 with no workloads. I then ran `vs_installer.exe modify --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community" --add Microsoft.VisualStudio.Component.NuGet --add Microsoft.Net.Component.4.6.TargetingPack --add Microsoft.VisualStudio.Component.PortableLibrary --add Microsoft.VisualStudio.Component.Static.Analysis.Tools --add Microsoft.VisualStudio.Component.Roslyn.Compiler --add Microsoft.Component.MSBuild --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.VC.CoreIde --add Microsoft.VisualStudio.Component.Windows10SDK --add Microsoft.VisualStudio.Component.VC.140` to add all required individual components.

I then created a new clone of the repo and ran `build`. It failed with the above error message so I also tried `clean -all`, `sync` and then `build`, but got the same error message.

**Comment by danmosemsft** [comment]
@ViktorHofer it sounds like @MisinformedDNA followed the instructions at https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md. Is it possible another VS component is required?

**Comment by ViktorHofer** [comment]
@MisinformedDNA himself added the command line instructions. The Windows 10 SDK should suffice. I'm not sure why the 8.1 SDK is required here. Let me try to reproduce the error as I'm also interested in what really the exact minimum requirements are.

**Comment by MisinformedDNA** [comment]
@ViktorHofer The instructions worked prior to Core 2.1.

**Comment by ViktorHofer** [comment]
Instead of `Microsoft.VisualStudio.Component.Windows10SDK` which is the Windows Universal C Runtime, you should use `Microsoft.VisualStudio.Component.Windows10SDK.17134` which is one of the SDKs.
