### ISSUE TITLE
TPL Joinblock sample works on .NET Framework 4.6, but has thread issue on Core

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#32057]
@ZeroPKI commented on [Mon Aug 20 2018](https://github.com/dotnet/core/issues/1872)

# Issue Title

I'm using the following sample on .NET Framework 4.6 and it runs properly, however when I use the same code with .Core, the other threads never get called.
https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-use-joinblock-to-read-data-from-multiple-sources

# General

All information is included in the link
https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-use-joinblock-to-read-data-from-multiple-sources

Simply compare the output between a .NET Core and .NET Framework console app

---

@MarcoRossignoli commented on [Tue Aug 21 2018](https://github.com/dotnet/core/issues/1872#issuecomment-414571347)

i think i better move this to https://github.com/dotnet/corefx where core TPL dataflow lives https://github.com/dotnet/corefx/tree/master/src/System.Threading.Tasks.Dataflow

**Comment by MarcoRossignoli** [comment]
I did some test...and i see output from both version.
Could you attach your sample?
[TPLTest.zip](https://github.com/dotnet/corefx/files/2356998/TPLTest.zip)

**Comment by tarekgh** [comment]
I couldn't repro it either. I am seeing net core is producing the output as expected.  maybe trying to extend the timeout at the end of main method could help in your case? or if you can share the repro and what environment you are running on that may help. I am closing the issue but feel free to respond back with any question or request.

**Comment by tarekgh** [comment]
just for the record, here is the output I am getting in netcore app:

```
Network worker: using resources...
Network worker: finished using resources...
Network worker: using resources...
Network worker: finished using resources...
File worker: using resources...
File worker: finished using resources...
Network worker: using resources...
Network worker: finished using resources...
Network worker: using resources...
Network worker: finished using resources...
File worker: using resources...
File worker: finished using resources...
File worker: using resources...
```
