### ISSUE TITLE
How to get hardware information for MacOs、Linux and other OS

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#32054]
@linkanyway commented on [Thu Aug 30 2018](https://github.com/dotnet/core/issues/1908)

# How to get hardware information for MacOs、Linux and other OS

is any possible to get hardware information by .net core

there is have `RuntimeInformation` class can help me to get .net core version some other helpful information, but i really need get hardware information also  like CPU core number,CPU speed, memory size,disk information...

thanks!

**Comment by danmosemsft** [comment]
@linkanyway thanks for the suggestion. This is already covered by https://github.com/dotnet/corefx/issues/22660. Your contribution is welcome there -- we need help to drive to some agreed on API.
