### ISSUE TITLE
Why does a copyright header of System.IO.Compression.DeflaterManaged refer to zlib?

### ISSUE THREAD

**Issue by Alicg** [dotnet/corefx#32064]
I don't understand why copyrights of System.IO.Compression.DefalterManaged.cs (https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.IO.Compression/src/System/IO/Compression/DeflateManaged/DeflaterManaged.cs) and System.IO.Compression.InflaterManaged (https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.IO.Compression/src/System/IO/Compression/DeflateManaged/InflaterManaged.cs) refer to zlib, while there is nothing common between their sources.
Should I add Zlib's license to my product's 3rd party notice if I copied these two classes (System.IO.Compression.DefalterManaged and System.IO.Compression.InflaterManaged)?

**Comment by danmosemsft** [comment]
@AlexGhiondea do you konw?

**Comment by AlexGhiondea** [comment]
I am not sure why the specific comment is right there.

However, ZLib is used as the native side (in CLRCompression). This is already called out in the thirdpartynotices file here:
https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/THIRD-PARTY-NOTICES.TXT#L60

**Comment by Alicg** [comment]
@danmosemsft @AlexGhiondea thanks a lot for the answer. 
Yes, I know that ZLib stays behind CLRCompression.dll. However, I need to copy just those two files which has nothing to do with CLRCompression.dll.
Is there any chance those comments be removed, like in all other files from https://github.com/dotnet/corefx/tree/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.IO.Compression/src/System/IO/Compression/DeflateManaged ?

**Comment by AlexGhiondea** [comment]
@Alicg I am looking into that. I'll reply back once I know more.

**Comment by stephentoub** [comment]
@AlexGhiondea, can this be closed now after https://github.com/dotnet/corefx/pull/32368?

**Comment by AlexGhiondea** [comment]
Yes -- thanks for the reminder!
