### ISSUE TITLE
.NET Core 2.1 downgrades HTTP/2 requests

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#32068]
@lukebondespok commented on [Fri Aug 31 2018](https://github.com/dotnet/core/issues/1910)

Hello!

I have a Console application that targets .NET Core 2.1 in which I make an HTTP/2 request to google. However, when I inspect the outgoing HTTP request, I notice that the request was downgraded to HTTP/1.1. This can also be verified by checking the Version of the response.

```C#
var client = new HttpClient();

var req = new HttpRequestMessage(HttpMethod.Get, "https://www.google.com")
{
      Version = new Version(2, 0)
};

var x = client.SendAsync(req);

var version = x.Result.Version; // 1.1
```

If I target .NET Core 2.0 or earlier, the HTTP/2 header is not altered.

Is this a known issue? Does anyone have any insight into this problem?

For the record, this is a problem on both Windows and Mac.

Thanks!

---

@MarcoRossignoli commented on [Sat Sep 01 2018](https://github.com/dotnet/core/issues/1910#issuecomment-417840113)

i think is better move to corefx repo https://github.com/dotnet/corefx/issues 
where HttpClient lives https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClient.cs

/cc @karelz

**Comment by davidsh** [comment]
Yes it is expected.  .NET Core 2.1 switched to a different HTTP stack.  And it currently doesn't support HTTP/2.0.

See:
https://blogs.msdn.microsoft.com/dotnet/2018/05/30/announcing-net-core-2-1/

>Networking Performance Improvements
We built a new from-the-ground-up HttpClientHandler called SocketsHttpHandler to improve networking performance. It’s a C# implementation of HttpClient based on .NET sockets and Span<T>.
SocketsHttpHandler is now the default implementation for HttpClient. The biggest win of SocketsHttpHandler is performance. It is a lot faster than the existing implementation. It also eliminates platform-specific dependencies and enables consistent behavior across operating systems.
See the .NET Core 2.1 release notes for instructions on how to enable the older networking stack.

You can switch back to the older stack and that supports HTTP/2.0.
>Networking Performance
You can use one of the following mechanisms to configure a process to use the older HttpClientHandler:
From code, use the AppContext class:
AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);
The AppContext switch can also be set by config file.
The same can be achieved via the environment variable DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER. To opt out, set the value to either false or 0.
On Windows, you can choose to use WinHttpHandler or SocketsHttpHandler on a call-by-call basis. To do that, instantiate one of those types and then pass it to HttpClient when you instantiate it.
On Linux and macOS, you can only configure HttpClient on a process-basis. On Linux, you need to deploy libcurl yourself if you want to use the old HttpClient implementation. If you have .NET Core 2.0 working on your machine, then libcurl is already installed.

**Comment by davidsh** [comment]
cc: @karelz

**Comment by lukebondespok** [comment]
Wonderful, thanks for the help!

**Comment by lukebondespok** [comment]
Any idea on when the SocketsHttpHandler implementation will support HTTP/2? 

Thanks!

**Comment by karelz** [comment]
@lukebondespok we are currently targeting 3.0 (it can of course change).
Closing as answered.
