### ISSUE TITLE
Creating a ReadOnlySpan<byte> over a ref readonly parameter

### ISSUE THREAD

**Issue by couven92** [dotnet/corefx#32078]
Is there a way to create a read-only span of a `ref readonly` or `in` parameter?

In essence I'd like to be able to create a `ReadOnlySpan<T>`over a function parameter in order to call the `.AsBytes()` extension method to get a `ReadOnlySpan<byte>` which will allow me to access the individual bytes of the input parameter.

The closest I have been able to get is calling `MemoryMarshal.CreateReadOnlySpan(ref parameter, 1)` however that requires the parameter to also be writable.

I'd expect this to work, however it doesn't, since `reference` is read-only.

``` cs
ReadOnlySpan<byte> AsBytes<T>(in T reference)
{
   ReadOnlySpan<T> span = MemoryMarshal.CreateReadOnlySpan(reference, length: 1);
   return span.AsBytes();
}
```

However, this works:

``` cs
ReadOnlySpan<byte> AsBytes<T>(ref T reference)
{
   ReadOnlySpan<T> span = MemoryMarshal.CreateReadOnlySpan(reference, length: 1);
   return span.AsBytes();
}
```

But why does `CreateReadOnlySpan` require a **writable** input?

**Comment by benaadams** [comment]
Aside if you were converting to bytes you might want to use the unmanaged constraint?
```csharp
where T : unmanaged
```

**Comment by benaadams** [comment]
So this would work:
```csharp
ReadOnlySpan<byte> AsBytes<T>(in T reference) where T : unmanaged
{
    ReadOnlySpan<T> span = MemoryMarshal.CreateReadOnlySpan(ref Unsafe.AsRef(in reference), length: 1);
    return MemoryMarshal.AsBytes(span);
}
```

**Comment by couven92** [comment]
@benaadams Thank you very much! Exactly what I needed.

For completeness: When targeting .NET Standard, `MemoryMarshal.CreateReadOnlySpan` does not (yet) exist. Add references to `System.Memory` and `System.Runtime.CompilerServices.Unsafe` and use the following code instead:

``` cs
ReadOnlySpan<byte> AsBytes<T>(in T readOnly) where T : unmanaged
{
    ReadOnlySpan<T> inSpan;
    ref T reference = ref Unsafe.AsRef(readOnly);
    unsafe
    {
        var ptr = Unsafe.AsPointer(ref reference);
        inSpan = new ReadOnlySpan<T>(ptr, length: 1);
    }
    return MemoryMarshal.AsBytes(inSpan);
}
```

**Comment by benaadams** [comment]
Don't do that as you'll create a span on an untracked pointer and have a GC hole.

Could use `MemoryMarshal.CreateSpan` instead?
```csharp
ReadOnlySpan<byte> AsBytes<T>(in T reference) where T : unmanaged
{
    ReadOnlySpan<T> span = MemoryMarshal.CreateSpan(ref Unsafe.AsRef(in reference), length: 1);
    return MemoryMarshal.AsBytes(span);
}
```

**Comment by couven92** [comment]
@benaadams no, `CreateSpan` is also unavailable in .NET Standard

**Comment by benaadams** [comment]
Ahh, cos the runtime can't necessarily handle an internal reference pointer; it additionally needs the object pointer for the GC to hold it

**Comment by couven92** [comment]
@benaadams Will it be added to standard in the future, do you think? Should I open an issue for that?

Can I call the internal ref T constructor for Span and ROS via Reflection? By creating an expression lambda I mean?

**Comment by benaadams** [comment]
Don't know...

/cc @jkotas

**Comment by jkotas** [comment]
>  Will it be added to standard in the future, do you think?

The `MemoryMarshal.CreateSpan` method is being added to .NET Standard 2.1 in https://github.com/dotnet/standard/pull/819/ . Note that .NET Standard 2.1 will only work on new runtimes - it won't work on existing runtimes.

> Can I call the internal ref T constructor for Span and ROS via Reflection? 

If you want to light up on runtimes that allow this via reflection, you should call the public `MemoryMarshal.CreateSpan` method via reflection. Calling internal methods via reflection is a bad practice and often breaks on new runtime versions.
