### ISSUE TITLE
Is there a way to port System.Beep to multiplattform?

### ISSUE THREAD

**Issue by paule96** [dotnet/corefx#32070]
Hallo .NET Communtiy,

I have play a little bit with System.Beep. but then I see [here](https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/Common/src/Interop/Windows/kernel32/Interop.Beep.cs) in the source code that only supports Windows. (and also I try it on a ubuntu bash...)

Can we port this to the other plattforms too? It would be very great! Currently [this](https://github.com/nickvdyck/nyancat.cs/issues/1) project would be very thankful.

**Comment by danmosemsft** [comment]
Hello! Would you like to offer a PR?

**Comment by jkotas** [comment]
Duplicate of https://github.com/dotnet/corefx/issues/25746
