### ISSUE TITLE
Conditional tests are ignored in netfx runs

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#32084]
Add a test like
```c#
using Xunit;

namespace Baz
{
    public class Bar
    {
        private static bool IsProcessElevated => true;

        [ConditionalFact(nameof(IsProcessElevated))]
        public void Foo()
        {
            throw new System.Exception();
        }
    }
}
```
Run it with `msbuild /t:rebuildandtest /p:targetgroup=netcoreapp` and it will run
Try `msbuild /t:rebuildandtest /p:targetgroup=netfx` and it will not be discovered (even marked as skipped)

@ViktorHofer

**Comment by safern** [comment]
Last time I fixed this, it was related to referencing the xunit netstandard assemblies instead of the net45 assemblies. The difference was that the net45 assemblies included `MarshalByRef` as a base type in their communication types, when we used the netstandard ones, when running in desktop we would get serialization exceptions stating types couldn't be serialized, hence the conditions evaluated to false and the tests where skipped.

**Comment by danmosemsft** [comment]
@safern is going to add a test that checks for a static bool that is initialized by a preceding test in the same class that has an always-true conditional attribute. Assuming tests in a class are always run in the same order, that test should deterministically fail if conditional attributes are not respected. 

Presumably the reverse (conditionals unexpectedly true) is sufficiently "tested" already (since many tests would fail)

**Comment by ViktorHofer** [comment]
> Last time I fixed this, it was related to referencing the xunit netstandard assemblies instead of the net45 assemblies.

I don't think that's the issue here as we are using the right assemblies.

**Comment by safern** [comment]
That is exactly where I was thinking of adding it.

**Comment by danmosemsft** [comment]
Let's close this issue when we've absorbed the new arcade and know it works.

**Comment by danmosemsft** [comment]
@ViktorHofer since you closed this perhaps you coudl create an issue for @safern to add his test.

**Comment by safern** [comment]
I'm back from vacation, working on adding the test.

**Comment by safern** [comment]
I created the issue myself and self assigned. https://github.com/dotnet/corefx/issues/32227
