### ISSUE TITLE
new X509Certificate2 throws exception while loading certificate in Docker container

### ISSUE THREAD

**Issue by MarcelWouters** [dotnet/corefx#32088]
SDK: Microsoft.AspNetCore.App 2.1.1

The following code throws an exception when it runs in a docker container

`            var certificatePath = Path.Combine(env.ContentRootPath, "TestCertificate.pfx");

            Console.WriteLine($"Certificate file exists: {File.Exists(certificatePath)}");

            var certificate =new X509Certificate2(certificatePath, "Password");`

The following exception occcurs:

Object was not found

   at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)

The certificate file exists in the Docker container. Running the web application outside the Docker container throws no exception. 

Example project can be find here: https://github.com/MarcelWouters/DockerLoadCertificate

**Comment by bartonjs** [comment]
A similar issue was reported previously where the answer was to run with USER ContainerAdministrator.

https://github.com/dotnet/corefx/issues/25717#issuecomment-397918250

**Comment by MarcelWouters** [comment]
Thanks @bartonjs ... USER ContainerAdministrator was the solution

**Comment by Tarig0** [comment]
I have the same issue and the USER ConatinerAdministrator changes the context of the docker image to where the SSL setup does not function.

Looks like the reason why this fails is because of a reliance on the My certificate store for the current user and for some reason the default user for docker does not have the ability to initialize the store.

Would it be possible to remove the reliance on the cert store for a windows environment?

**Comment by bartonjs** [comment]
@Tarig0 The original issue was about using the X509Certificate2 constructor directly, which doesn't (to my knowledge) involve touching the My store.  If you're in a more nuanced situation (e.g., SslStream) then that would warrant a new issue for that situation.

**Comment by Tarig0** [comment]
I am using the constructor (byte[], password) and getting the same error as above. This happens unless I am.

1. user is containeradmin
2. I have run the new X509Store("My", StoreLocation.CurrentUser); constructor at least once on the container.

Based on that I believe this is the same issue here
