### ISSUE TITLE
.NET Core 2.1 remote directory enumeration with filters can be slower than prior frameworks

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#32098]
@ONeill45 commented on [Tue Sep 04 2018](https://github.com/dotnet/core/issues/1916)

# Issue Title

.NET Core 2.1 DirectoryInfo.EnumerateFiles() Performance is Slower than .NET Framework

# General

I have a .NET Core 2.1 Web API that is being built as a replacement for an older .NET Framework MVC Web Application (.NET Framework 4.5).

One of the responsibilities of this application is to take in a directory and search template and return the top 10 results, ordered by most recent. This is being accomplished using System.IO.DirectoryInfo and the EnumerateFiles() method:

```

List<FileInfo> fileInfos = new DirectoryInfo(directory).EnumerateFiles(fileTemplate)
.OrderByDescending(f => f.LastWriteTime).Take(10).ToList();

```

However, I am noticing that this search is much, much slower in .NET Core than in .NET Framework. I created two console apps with the same code, one .NET Framework and one .NET core, to compare run times. Below are the results in .NET Framework:

![image](https://user-images.githubusercontent.com/13375042/45037835-e6620300-b02d-11e8-8864-8959deaa85e8.png)

And then the results in .NET Core:

![image](https://user-images.githubusercontent.com/13375042/45037921-1f9a7300-b02e-11e8-9711-ff262816856b.png)

Can anyone help me understand why there is such a dramatic decrease in performance?

---

@MarcoRossignoli commented on [Tue Sep 04 2018](https://github.com/dotnet/core/issues/1916#issuecomment-418415348)

better move to https://github.com/dotnet/corefx

/cc @JeremyKuhne, @pjanotti

**Comment by Petermarcu** [comment]
@stephentoub as well.

**Comment by JeremyKuhne** [comment]
@ONeil45 What sort of template and source files do you have? (What is the pattern, how many files are in the directory, and how many matches)  Also, did you try measuring without the extra Linq filtering?

**Comment by ONeill45** [comment]
@JeremyKuhne The folder is very large, currently 7k+ files (all .csv). The naming pattern is: 

```
string fileTemplate = "ShiftmasterAssignedHours_WK34*.csv"
```

where the wildcard covers the DateTime stamp of the file's generation. Currently 12 matches are being found but that number could vary wildly depending on what number comes after the 'WK' portion of the template above (week number, let's the user target a specific fiscal week. These files get generated numerous times for a given week).

**Running without the LINQ filtering OR the .Take(10):**

.NET Framework:
![image](https://user-images.githubusercontent.com/13375042/45048600-541c2800-b04a-11e8-94db-8d6716d12654.png)

.NET Core:
![image](https://user-images.githubusercontent.com/13375042/45048708-9a718700-b04a-11e8-9618-bb87a975364c.png)

**Without LINQ but with .Take(10):**

.NET Framework:
![image](https://user-images.githubusercontent.com/13375042/45048770-bf65fa00-b04a-11e8-80c4-1f15604f1307.png)

.NET Core:
![image](https://user-images.githubusercontent.com/13375042/45048855-f5a37980-b04a-11e8-8b23-ebbfffc26763.png)

**With LINQ but without .Take(10):**

.NET Framework:
![image](https://user-images.githubusercontent.com/13375042/45048917-19ff5600-b04b-11e8-861a-9c6cf6024bed.png)

.NET Core:
![image](https://user-images.githubusercontent.com/13375042/45049005-5df25b00-b04b-11e8-81d8-a3ed639d41b1.png)


So it appears removing the LINQ query results in a small performance increase from .NET Core but is still slower than .NET Framework.

**Comment by JeremyKuhne** [comment]
@ONeill45 Thanks for the extra info- can you provide a doc with filenames so I can repro against your exact scenario? (And an equivalent length path for the directory?) I don't need the contents, just want make sure I replicate where you're spending your time. You might be able to see something useful running this code with the perf tools in VS.

**Comment by ONeill45** [comment]
@JeremyKuhne 

Here's a list of file names in the folder currently:

[Files.txt](https://github.com/dotnet/corefx/files/2349810/Files.txt)


For the folder name use \\\\foldername13\subfoldername1425

**Comment by JeremyKuhne** [comment]
@ONeill45 So this is over a UNC? That might be the key part.

**Comment by ONeill45** [comment]
@JeremyKuhne Any progress on this?

**Comment by JeremyKuhne** [comment]
@ONeill45 not yet, sorry. I've been backed up with other things. It's high on my list (hopefully tomorrow). In the meantime, if you could try using the new options that allow you to specify the buffer size that would be fantastic- that feature was specifically intended for the UNC scenario.

**Comment by ONeill45** [comment]
@JeremyKuhne Altering the BufferSize in the EnumerationOptions class made a huge difference. With a buffer of 64000 the times are reduced to:
![image](https://user-images.githubusercontent.com/13375042/45321271-dc02a600-b512-11e8-874c-bf13ca14994b.png)

Any advice on how to best determine proper buffer size?

**Comment by JeremyKuhne** [comment]
> Altering the BufferSize in the EnumerationOptions class made a huge difference. 

Cool. It is always nice to see features work the way they're intended. ;)

> Any advice on how to best determine proper buffer size?

Make it big enough to handle the expected file count. You'll have to measure to see for sure where the sweet spot is for your scenario. The buffer is rented from the ArrayPool and as such is reused (and collected if left idle)- don't sweat the size too much.

Some of this might be fallout of .NET doing the matching. I might just need to tweak up the default size. What diff does 8K make for you?

**Comment by ONeill45** [comment]
Here's the results of some different buffer sizes:

8k:
![image](https://user-images.githubusercontent.com/13375042/45359040-5118be80-b599-11e8-8a19-fad9379bcf04.png)

16k:
![image](https://user-images.githubusercontent.com/13375042/45359082-75749b00-b599-11e8-9fb4-bc0a395db414.png)

32k:
![image](https://user-images.githubusercontent.com/13375042/45359131-93420000-b599-11e8-89b6-0b9ec76a78be.png)

64k:
![image](https://user-images.githubusercontent.com/13375042/45359160-af45a180-b599-11e8-8f70-cb138b3e4d7f.png)

Above that I start to get an error: 
`The parameter is incorrect: \\serverName\shareName`

**Comment by JeremyKuhne** [comment]
> What do you mean by more normal share?

Something with a smaller set of files. Say 50 or 100. There are two key differences that I'm concerned about. The old implementation was at peak performance when it (1) wasn't recursive **and** (2) had a filter.

When the search is recursive the old code had to enumerate twice. The first time was to get filtered results and the second time was to get the list of directories (which may not pass the filter).  When it wasn't recursive then the filter would provide optimal results in UNC scenarios.

What I'm hoping to see is what sort of impact there is in the UNC case when you are retrieving the full set of results. Just another data point to decide how we might tweak defaults for the buffer. Adding the ability to pass the filter through is a little complicated- primarily from an education perspective. It would only work if you're not doing custom filtering and not recursing and only have an impact in remote scenarios like this and only on Windows.

When I measured yesterday I was doing more work than I needed to. The actual results are about 3x as slow in the filtered case (over the prior code) and roughly equal in the non-filtered case. Changing the buffer size doesn't make much of a difference for me- but again I suspect that connection speed is trivializing the impact.

The other thing to note is that there is lower level caching going on. This may be happening at multiple levels. If I change the directory contents or wait long enough I get a very slow result from either the old code or the new code (over 50x slower). Slower on the new code, but not orders of magnitude- more in the 20% range.

@pjanotti this one is going to need some discussion. :)

**Comment by JeremyKuhne** [comment]
If the buffer size configuration doesn't give enough headroom we can further explore adding complexity to the API that lets you provide the "native" filter. Unless we see strong need I'd prefer not to as that will undoubtedly be very difficult to grok.

**Comment by JeremyKuhne** [comment]
Closing. There is a mitigation and this is a corner case (UNC with a large number of files over a slow connection and a very restrictive filter). As mentioned above we can look at additional "native" filter properties if this ends up blocking folks.
