### ISSUE TITLE
ASP.Net Core 2.1 not releasing memory

### ISSUE THREAD

**Issue by BinaryPatrick** [dotnet/corefx#32100]
An application running under a 15-25 requests per second load exhibits an endlessly growing memory footprint.

At first I thought I must have a memory leak, but when I run `dotnet new webapi`, compile the code using the release flag, and run it using `dotnet webapi.dll`, I get the same result.

I generated a load of ~20 GET requests a second to https://localhost:5001/api/values and after 10 minutes, the memory usage is up to 800Mb and growing.

This is with the stock asp.net webapi template. Is this the expected memory usage?

**Comment by danmosemsft** [comment]
@BinaryPatrick hello, I don't know, let's move this to the ASP.NET repo.  If you want to investigate yourself, you'll want to look at https://github.com/Microsoft/perfview

**Comment by danmosemsft** [comment]
This issue was moved to aspnet/Home#3494

**Comment by BinaryPatrick** [comment]
Thanks, for some reason I thought I was in the asp repo.
