### ISSUE TITLE
Bring back missing protected fields from ResourceManager and ResourceSet

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#32103]
### Proposal

We removed 4 protected fields from System.Resources types because (1) Hashtable was not in corelib at that time and (2) usage seemed low and public/protected fields are non standard. The 4 fields in System.Resources are:
```
ResourceManager.BaseNameField
ResourceManager.ResourceSets
ResourceSet.Reader
ResourceSet.Table
```
Since then (1) it has emerged from api-port analysis there is significant usage especially for the ResourceSet fields and (2) Hashtable has moved to corelib.

We should bring these back.

```C#
namespace System.Resources
{
    public class ResourceManager
    {
        protected string BaseNameField;
        protected Hashtable ResourceSets;
    }

    public class ResourceSet : IDisposable, IEnumerable
    {
        protected IResourceReader Reader;
        protected Hashtable Table;
    }
}

```

**Comment by tarekgh** [comment]
@danmosemsft  I modified the issue description to be a proposal so we can review it.

**Comment by danmosemsft** [comment]
@tarekgh we have not historically done any API review for API that's already in .NET Framework?

@terrajobst

**Comment by MarcoRossignoli** [comment]
@danmosemsft i did a check and [ResourceManager.BaseNameField](https://github.com/dotnet/coreclr/blob/c62976e0aaef8c8fb456b16f21b9fe3bd73a40a5/src/System.Private.CoreLib/src/System/Resources/ResourceManager.cs#L124) and [ResourceSet.Reader](https://github.com/dotnet/coreclr/blob/030a3ea9b8dbeae89c90d34441d4d9a1cf4a7de6/src/System.Private.CoreLib/src/System/Resources/ResourceSet.cs#L30) are already protected!

**Comment by tarekgh** [comment]
@MarcoRossignoli 

you are looking at the implementation but these fields are not exposed from the contracts 

https://github.com/dotnet/corefx/blob/master/src/System.Resources.ResourceManager/ref/System.Resources.ResourceManager.cs#L53
https://github.com/dotnet/corefx/blob/master/src/System.Resources.ResourceManager/ref/System.Resources.ResourceManager.cs#L80

**Comment by MarcoRossignoli** [comment]
You're right @tarekgh, thank's!

**Comment by MarcoRossignoli** [comment]
@danmosemsft I could work on this...i'll wait up-for-grabs label

**Comment by tarekgh** [comment]
@MarcoRossignoli we need first to agree that is what we want to do. personally, I don't have any objection but I need to get more people to agree on that.

**Comment by jkotas** [comment]
Do we know what these are used for? It is very hard to test and guarantee the behavior for these collections because of they expose an internal implementation detail.

**Comment by tarekgh** [comment]
> Do we know what these are used for? It is very hard to test and guarantee the behavior for these collections because of they expose an internal implementation detail.

Here are the docs of these fields

https://docs.microsoft.com/en-us/dotnet/api/system.resources.resourcemanager.basenamefield?view=netframework-4.7.2
https://docs.microsoft.com/en-us/dotnet/api/system.resources.resourceset.reader?view=netframework-4.7.2
https://docs.microsoft.com/en-us/dotnet/api/system.resources.resourceset.table?view=netframework-4.7.2

I am not seeing these are important to expose and if used will be used in very corner cases scenarios.

For BaseNameField, we already have a property BaseName which can return the needed info. overriding this name is not really useful except if really subclassing ResourceManager and want to have a different name. 

For Table and Reader properties, are just nice to have but not really blocking any scenario as we already provide an Enumerator over such Hashtable.

**Comment by danmosemsft** [comment]
I do not know what they are used for. Here is the percentage of recent API port analyses that included code which used them at least once. 5% is signficant. I too would like to know what it is for.

F:System.Resources.ResourceManager.BaseNameField | 0.27%
-- | --
F:System.Resources.ResourceManager.ResourceSets | 0.53%
F:System.Resources.ResourceSet.Reader | 5.42%
F:System.Resources.ResourceSet.Table | 5.66%

**Comment by tarekgh** [comment]
@danmosemsft did you look at the links I sent? it has the docs.

**Comment by danmosemsft** [comment]
Right, I'm wondering why they have such high usage.

**Comment by tarekgh** [comment]
These are useful only when subclassing ResourceManager and ResourceSet class.  I guess 5% are subclassing ResourceSet

**Comment by tarekgh** [comment]
Considering that, I would say for the 5% we can bring back System.Resources.ResourceSet.Reader and System.Resources.ResourceSet.Table but not System.Resources.ResourceManager.BaseNameField

**Comment by danmosemsft** [comment]
Compat burden for ResourceSet.Table does not seem to bad -- it is written only during reading resources and used in a straightforward way. If eg., a derived class replaced the table, it does not seem hard for us to keep that working. It is a shame it is protected as you point out @tarekgh there are other good ways to get those resources (like the enumerator).

ResourceSet.Reader is a bit more problematic as it has potentially more interesting state, but already it possible to pass in your own reader so perhaps already we are not free to change the semantics of how we use it a great deal. This would allow a derived class to even set a new one during reading which is strange and would be easy for us to break.

@jkotas what is your concern level about exposing these two. I would rather not, but 5% usage is quite large.

**Comment by jkotas** [comment]
> @jkotas what is your concern level about exposing these two.

I would like to see a few real-world pieces of code that use these to understand what does this 5% really mean.

**Comment by danmosemsft** [comment]
OK. @tarekgh if you want to pursue gathering this info (as area owner) @terrajobst can probably hook you up with one of our customers who provided API port details in person.

Or, we can just wait for this to emerge as a blocker for concrete customers, since if it does it will be quick to add if we need to.

**Comment by tarekgh** [comment]
I think we can just wait till we get a concrete request.

**Comment by danmosemsft** [comment]
OK, closing, if we get a good reason, we can reopen.

**Comment by 87Alex** [comment]
Hello,
We use ResurceSet class fields in our descendant. I provided simple demonstrating project in the 
https://github.com/dotnet/corefx/issues/36882 ticket.
