### ISSUE TITLE
File.Delete behave differently when the directory is empty on Windows Vs non-Windows

### ISSUE THREAD

**Issue by wli3** [dotnet/corefx#32110]
The following code throws on Windows, but not on Linux and Mac. Note, if there is no another layer of non-existing directory, they both will not throw.

```c#
        public void DeleteFileShouldNotThrowWhenDirectoryDoesNotExistsInconsistent(bool testMockBehaviorIsInSync)
        {
            string directory = Path.GetTempPath();
            string file = Path.Combine(directory, Path.GetRandomFileName(), Path.GetRandomFileName());

            Action a = () => File.Delete(file);

            a.ShouldNotThrow();
        }
```

On Windows

`Error Message:
 Did not expect any exception, but found System.IO.DirectoryNotFoundException with message "Could not find a part of the path 'C:\Users\wul\AppData\Local\Temp\kcnuii32.meo\gr3ldwn4.wu5'."
     at System.IO.FileSystem.DeleteFile(String fullPath)
     at System.IO.File.Delete(String path)`

Version:
Microsoft.NETCore.App 3.0.0-preview1-26710-03

Which is inserted to CLI master.

**Comment by danmosemsft** [comment]
@JeremyKuhne it should throw on Unix then right?

**Comment by JeremyKuhne** [comment]
> it should throw on Unix then right?

We should be consistent with the .NET Framework behavior if they differ. Presumably Windows matches the legacy behavior.

**Comment by danmosemsft** [comment]
OK, up for grabs.

**Comment by piraces** [comment]
I would like to work on this. I will comment if I have any doubt.

**Comment by MarcoRossignoli** [comment]
> We should be consistent with the .NET Framework behavior if they differ. Presumably Windows matches the legacy behavior.

Legacy but correct, right?I mean...this [should throw](https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs#L165) on all plats correct?

**Comment by MarcoRossignoli** [comment]
ping @JeremyKuhne @danmosemsft

**Comment by JeremyKuhne** [comment]
> I mean...this should throw on all plats correct?

Yes it should always throw. If the .NET Framework didn't there might be an argument not to throw, but I just double checked that it does.

**Comment by JeremyKuhne** [comment]
Oh, and clearly we need a test for it. :)

**Comment by danmosemsft** [comment]
Do you want me to assign to you @MarcoRossignoli 	?

**Comment by MarcoRossignoli** [comment]
Sure @danmosemsft it's my pleasure thank's!

**Comment by danmosemsft** [comment]
Done
