### ISSUE TITLE
Various projects not buildable in VS

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#32114]
It seems that, even after having successfully run `build.cmd` from the command line, a good number of projects will not build successfully from within VS.

For example, after opening and attempting to build `System.IO.Pipelines.sln`; I get failures attempting to build `System.IO.Pipelines.csproj`:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1069	The type name 'ValueTask<>' could not be found in the namespace 'System.Threading.Tasks'. This type has been forwarded to assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.	System.IO.Pipelines	E:\Users\tagoo\Repos\corefx\src\System.IO.Pipelines\ref\System.IO.Pipelines.cs	70	N/A
Error	CS1069	The type name 'ValueTask<>' could not be found in the namespace 'System.Threading.Tasks'. This type has been forwarded to assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.	System.IO.Pipelines	E:\Users\tagoo\Repos\corefx\src\System.IO.Pipelines\ref\System.IO.Pipelines.cs	50	N/A
Error	CS1069	The type name 'ValueTask<>' could not be found in the namespace 'System.Threading.Tasks'. This type has been forwarded to assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.	System.IO.Pipelines	E:\Users\tagoo\Repos\corefx\src\System.IO.Pipelines\ref\System.IO.Pipelines.cs	66	N/A
```

**Comment by weshaggard** [comment]
I was able to repro this locally and the issue comes down to something is setting ` GlobalPropertiesToRemove=Configuration;Platform` when we build the project references which causes the wrong configuration to be selected for that reference.

For reference when building the ref project in VS we have:
```
..\..\System.Threading.Tasks.Extensions\ref\System.Threading.Tasks.Extensions.csproj
        AdditionalProperties=Configuration=netstandard;
        GlobalPropertiesToRemove=Configuration;Platform
        OutputItemType=
        Private=false
        ReferenceSourceTarget=ProjectReference
        SkipGetTargetFrameworkProperties=true
        Targets=
```

From the command line which succeeds we have:
```
..\..\System.Threading.Tasks.Extensions\ref\System.Threading.Tasks.Extensions.csproj
        AdditionalProperties=Configuration=netstandard;
        BuildReference=true
        OutputItemType=
        Private=false
        ReferenceOutputAssembly=true
        ReferenceSourceTarget=ProjectReference
        SkipGetTargetFrameworkProperties=true
        Targets=
```

Our build system depends on passing the Configuration through. I'm going to try and track down where the GlobalPropertiesToRemove is getting set.

cc @eerhardt in case he has ran into this.

**Comment by weshaggard** [comment]
OK I tracked down the issue. Apparently it has been this way for a while as it also fails in the release/2.1 branch. I've submitted #32137 to fix it.

**Comment by davkean** [comment]
Is it by-design that they those global properties are unset, dependencies don't necessarily have the same configuration/platform.

Background:

- We don't build references via MSBuild, all references are built by VS's own Solution Build Manager which builds them in dependency order.
- When we build references, they themselves get Configuration/Platform set via a global property that is based on the "active config"
- When we call into references (such as via GetTargetPath) from another project, they pull "Configuration/Platform" from a separate global property called; `CurrentSolutionConfigurationContents` which is populated based on the solution configuration.

What it sounds like is that your solution configuration is probably wrong - build logs from both referencee and referenced would help figure out what's going on under the covers.

**Comment by weshaggard** [comment]
Thanks for the extra context @davkean I'm going to be digging a little deeper into how this works when I refactor our configuration system and move it from BuildTools to arcade. When I do that I'll have a look at the CurrentSoultionConfigurationContents property as this is the first time I've heard of that.

For now our current configuration system expect the Configuration to flow to ProjectReference as we only want to build one configuration for the referenced project that matches the Configuration of the Referencing project.
