### ISSUE TITLE
[Request] Make Guid.Empty compile-time constant

### ISSUE THREAD

**Issue by TobiasSekan** [dotnet/corefx#32117]
## The Problem 
Currently the parameter `int.MaxValue`, `uint.MinValue`, `byte.MaxValue` , etc. are all compile-time constant, but `Guid.Empty` is

```csharp
public static readonly Guid Empty;
```
## Question
It is possible to make `Guid.Empty` as a  compile-time constant?

```csharp
public const Guid Empty = ... ;
```

## Actual behaviour
```csharp
// Error: Default parameter value for 'defaultValue' must be a compile-time constant

public static Guid GetGuid(object guidObject, Guid defaultValue = Guid.Empty)
=> guidObject == null ? defaultValue : Guid.TryParse(guidObject.ToString(), out var guid) ? guid : defaultValue;
```

## Expected behaviour
```csharp
// All okay 

public static Guid GetGuid(object guidObject, Guid defaultValue = Guid.Empty)
=> guidObject == null ? defaultValue : Guid.TryParse(guidObject.ToString(), out var guid) ? guid : defaultValue;
```

**Comment by JohnnyWestlake** [comment]
(For what it's worth, you can use `Guid defaultValue = default` in this case)

**Comment by jkotas** [comment]
This is not a simple API addition. This is language feature request about being able to use a custom struct as a constant. The discussion about this is at https://github.com/dotnet/csharplang/issues/144 .
