### ISSUE TITLE
.Net Core Version of directoryservcies to talk to LDAP

### ISSUE THREAD

**Issue by arunprasathv** [dotnet/corefx#32126]
@tarekgh 

Is there a .Net Core version of directoryservices available to interface with LDAP ? I'm looking for .Net Core 2.0.

**Comment by tarekgh** [comment]
@arunprasathv we have it but we support it on Windows only for now. we are looking at supporting it for Linux in the future.

https://www.nuget.org/packages/System.DirectoryServices/
https://www.nuget.org/packages/System.DirectoryServices.Protocols/

if you need it for Linux now, you may consider looking at https://github.com/flamencist/ldap4net

I am closing this issue but feel free to reply back with any more questions.
