### ISSUE TITLE
How to read Automatic Proxy Detection (WPAD) in Asp.net core 

### ISSUE THREAD

**Issue by Tratcher** [dotnet/corefx#32135]
_From @xinlongli2018 on September 6, 2018 16:8_

in asp.net we can use the following setting in web.config to point to a wpad.dat file to read all the proxy setting, is there a way we can achieve the same thing in asp.net core?
```
<system.net>
      <defaultProxy enabled="true" useDefaultCredentials="true">
        <proxy autoDetect="True" scriptLocation="http://wpad.dat" />
      </defaultProxy>
    </system.net>
```
_Copied from original issue: aspnet/Home#3509_

**Comment by davidsh** [comment]
On Windows, the networking stack will read proxy configuration from the default IE settings.  So, the equivalent would work the same:

![image](https://user-images.githubusercontent.com/7684835/45172284-c19a9680-b1b9-11e8-840a-ff4184ca07cb.png)

However, the .NET Core networking stack doesn't use config files.

**Comment by xinlongli2018** [comment]
Hi @davidsh, thank you for the reply, but do you know if this setting updates the registry value in windows?  how do we achieve this during deployment?

**Comment by davidsh** [comment]
>Hi @davidsh, thank you for the reply, but do you know if this setting updates the registry value in windows? how do we achieve this during deployment?

In general, IE settings that are displayed in the UI dialog are translated to registry entries in the HKCU (per-user) registry area.

There are several techniques to update those registry entries including using Group Policy.  See examples: https://docs.microsoft.com/en-us/internet-explorer/ie11-deploy-guide/auto-configuration-settings-for-ie11

**Comment by xinlongli2018** [comment]
@davidsh is there another way to point to the wpad file in the code level?

**Comment by davidsh** [comment]
>@davidsh is there another way to point to the wpad file in the code level?

No.  While you can use IWebProxy (HttpClientHandler.Proxy), that won't help with PAC file use (either automatic discovery or explicit).  Only IE settings can be used to specify PAC file use.

**Comment by xinlongli2018** [comment]
got it, thank you very much ! @davidsh

**Comment by davidsh** [comment]
Closing as the question has been answered.
