### ISSUE TITLE
Should HttpWebRequest utilize HttpClientFactory

### ISSUE THREAD

**Issue by Mpdreamz** [dotnet/corefx#32134]
https://github.com/dotnet/corefx/blob/master/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs#L1096-L1106 instantiates a new `HttpClient` for each request which is less then ideal.

**Comment by davidsh** [comment]
This is a duplicate of an existing issue. I just can't find the issue number at the moment.

**Comment by karelz** [comment]
Duplicate of #15460
