### ISSUE TITLE
Support /t in the project settings for sgen

### ISSUE THREAD

**Issue by huanwu** [dotnet/corefx#32142]
Support type parameter in project settings so the customer can serialize just single class.
Refer #24491

**Comment by yujayee** [comment]
@huanwu Do we want to support customers to specify the types in their project file PropertyGroup like the following?
```
<PropertyGroup>
    <SerializationType>project1.type1; project1.type2</SerializationType>
</PropertyGroup>
```

**Comment by yujayee** [comment]
Pr #36085 merged. Closing this issue.
Users will be able to modify the sgen command parameters using msbuild properties in their csproj file like the following:
```
<PropertyGroup>
    <SGenReferences>C:\myfolder\abc.dll;C:\myfolder\def.dll</SGenReferences>
    <SGenTypes>SgenTestProgram.MyType1;SgenTestProgram.MyType2</SGenTypes>
    <SGenProxyTypes>false</SGenProxyTypes>
    <SGenVerbose>true</SGenVerbose>
    <SGenKeyFile>mykey.snk</SGenKeyFile>
    <SGenDelaySign>true</SGenDelaySign>
</PropertyGroup>
```
