### ISSUE TITLE
Expose more parameters on csproj for sgen

### ISSUE THREAD

**Issue by huanwu** [dotnet/corefx#32145]
Review the current parameters supported in sgen and see if to support it in csproj.

**Comment by yujayee** [comment]
Current parameters we support for Microsoft.XmlSerializer.Generator, we need to decide which ones we want to support in project file and in what kind of format:
- [ ] help    

- [ ] force

- [ ] proxytypes

- [ ] out

- [ ] type

- [ ] assembly

- [ ] quiet

- [ ] nologo

- [ ] silent

- [ ] parsableerrors

- [ ] verbose

- [ ] reference

**Comment by yujayee** [comment]
An example of the project file may look like:
```
<ItemGroup>
  <SerializerGeneratorParameters>
      <SerializationType>project1.type1; project1.type2</SerializationType>
      <ProxyTypes>true</ProxyTypes>
      <OutputDirectory>C:\...\folder</OutputDirectory>
      <ReferenceAssembly>C:\..\assembly1.dll; C:\..\assembly2.dll</ReferenceAssembly>
      <SerializationAssembly Include="Project2">
          <SerializationType>Project2.Class1;Project2.Class3</SerializationType>
      </SerializationAssembly>
      <SerializationAssembly Include="Project3">
          <SerializationType>Project3.Class5;Project3.Class6</SerializationType>
      </SerializationAssembly>
  </SerializerGeneratorParameters>
</ItemGroup>
```

**Comment by yujayee** [comment]
Closing as pull request #36085 merged.
