### ISSUE TITLE
Why MemoryExtensions methods like `IndexOf` are implemented for `T value` but not for `IEquatable<T> value`

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/corefx#32158]
Why MemoryExtensions methods like `IndexOf` are implemented for `T value` but not for `IEquatable<T> value`?

For example how can I correct next code:
```cs
        public static int IndexOfEquals<T>(this Span<T> span, T value)
        {
            if (typeof(IEquatable<T>).IsAssignableFrom(typeof(T)))
                return System.MemoryExtensions.IndexOf(span, (T: IEquatable<T>)value);
            // Something else
        }
```

**Comment by ahsonkhan** [comment]
I am not sure I follow your question.
`IndexOf` is constrained to `T : IEquatable` already.

What exactly are you trying to accomplish here? If you want to compare two spans, you aren't allowed to box a span by casting it to an interface like IEquatable.

See: https://github.com/dotnet/corefx/blob/219ea1bea0f12660398a75160b1d68c2885696fd/src/System.Memory/ref/System.Memory.cs#L54

**Comment by ahsonkhan** [comment]
Right. There isn't much we can do here. Hence closing.
