### ISSUE TITLE
PipeSecurity (netstandard2.0) does not use .NET Framework implementation when loaded in Windows PowerShell

### ISSUE THREAD

**Issue by rjmholt** [dotnet/corefx#32152]
Not sure if this is the right place to ask about this, but let me know if not.

I'm trying to port a codebase that used to compile against net451 and netstandard1.6 to netstandard2.0.

(The code is essentially a PowerShell module that has to work with both Windows PowerShell and PS Core.)

I'm hitting a crash where constructing a PipeSecurity object in PS Core (netcoreapp2.1) on Windows throws this error:
```
An error occurred while starting PowerShell Editor Services:

Exception calling "StartLanguageService" with "2" argument(s): "Access Control List (ACL) APIs are part of resource management on Windows and
are not supported on this platform."
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
Access Control List (ACL) APIs are part of resource management on Windows and are not supported on this platform.
   at System.Security.AccessControl.ObjectSecurity..ctor()
   at System.Security.AccessControl.CommonObjectSecurity..ctor(Boolean isContainer)
   at System.Security.AccessControl.NativeObjectSecurity..ctor(Boolean isContainer, ResourceType resourceType)
   at System.IO.Pipes.PipeSecurity..ctor()
   at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.Channel.NamedPipeServerListener.Start()
   at Microsoft.PowerShell.EditorServices.Host.EditorServicesHost.StartLanguageService(EditorServiceTransportConfig config, ProfilePaths profilePaths)
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
```

That's occurring in our codebase here: https://github.com/PowerShell/PowerShellEditorServices/blob/f45c6312a859cde4aa25ea347a345e1d35238350/src/PowerShellEditorServices.Protocol/MessageProtocol/Channel/NamedPipeServerListener.cs#L38-L67

The PR I'm making the changes in is here: https://github.com/PowerShell/PowerShellEditorServices/pull/741

The `PipeSecurity` constructor was working for us in netstandard1.6, although it looks like this is a netstandard specific error message: https://github.com/dotnet/corefx/blob/032cc324f9f3c6d6fee7ca01e7aa8e3a4969deb9/src/System.Security.AccessControl/src/System.Security.AccessControl.csproj#L6

Is there a way for me to construct the `PipeSecurity` object in a netstandard2.0 library running against netcoreapp2.1 on Windows?

**Comment by danmosemsft** [comment]
@pjanotti ?

**Comment by rjmholt** [comment]
Just realised I omitted some important data.

The binaries we generate are not actually loaded as a module by PowerShell, but `Add-Type`d, [which is essentially `Assembly.LoadFrom()`](https://github.com/PowerShell/PowerShell/blob/2edbe70548f6e2e38112526ff063045251893fbd/src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs#L629-L646).

We used to construct the module selectively by cherry-picking binaries and placing them in a directory like `modules/PowerShellEditorServices/bin/Core` and `modules/PowerShellEditorServices/bin/Desktop` and then `Add-Type`-ing the ones we needed and letting assembly resolution take care of the rest.

This cherry-picking works perfectly when compiled against both netstandard1.6 and netstandard2.0 on Core.

But since netstandard2.0 gives us only one target, I just dumped all the DLLs from the publish folder into a shared directory.

So it looks like adding some DLL has caused this problem?

**Comment by pjanotti** [comment]
Hi @rjmholt PipeSecurity will do no good to you in netcoreapp, even with the System.IO.Pipes.AccessControl package, there is no way to proper use it for pipes (summary #31190, full discussion #30170). You can use it on Windows with netstandard2.0 on top of netfx but then you don't have the proper constructor in netstandard2.0 ... sorry ... 

The workaround is to directly p/invoke the constructor of the named pipe and set the proper settings so you can use it with the PipeSecurity via System.IO.Pipes.AccessControl package for netcoreapp, if you need some help with that I can try to give some guidance tomorrow.

**Comment by pjanotti** [comment]
Ah just looked at https://github.com/PowerShell/PowerShellEditorServices/blob/f45c6312a859cde4aa25ea347a345e1d35238350/src/PowerShellEditorServices.Protocol/MessageProtocol/Channel/NamedPipeServerListener.cs#L38-L67 ... in this case the workaround is already implemented but you will need to add a reference to System.IO.Pipes.AccessControl and create the PipeSecurity from there. I suspect that the same issue didn't happen in netcoreapp2.0 but need to investigate to confirm.

**Comment by rjmholt** [comment]
Thanks for the help (and quick response)! Yes, unfortunately our dependency on named pipes is a tricky one.

With our previous build against netstandard1.6, PS Core moved to netcoreapp2.1 and didn't create any problems for us -- both netcoreapp2.0 and netcoreapp2.1 seemed to tolerate the `new PipeSecurity()`.

> in this case the workaround is already implemented but you will need to add a reference to System.IO.Pipes.AccessControl and create the PipeSecurity from there.

I didn't quite understand you here where you say "add a reference". We have a csproj with the package reference, and we move the assembly into the same folder as the assembly we load -- is there another thing we need to do?

Also, I noticed our existing build grabs the System.IO.Pipes.AccessControl assembly from [`publish\runtimes\win\lib\netstandard1.3`](https://github.com/PowerShell/PowerShellEditorServices/blob/f45c6312a859cde4aa25ea347a345e1d35238350/PowerShellEditorServices.build.ps1#L215), so I don't know if that's some kind of workaround. (I've asked in my PR to see if there's a known reason)

**Comment by rjmholt** [comment]
Just tried to do things closer to how we did when we had the two build targets with the hand-picked assemblies.

I made sure to take System.IO.Pipes.AccessControl.dll and put it in the relevant folder. Now get the following error:
```
An error occurred while starting PowerShell Editor Services:

Exception calling "StartLanguageService" with "2" argument(s): "Could not load file or assembly 'System.IO.Pipes.AccessControl, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified."
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
Could not load file or assembly 'System.IO.Pipes.AccessControl, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.Channel.NamedPipeServerListener.Start()
   at Microsoft.PowerShell.EditorServices.Host.EditorServicesHost.StartLanguageService(EditorServiceTransportConfig config, ProfilePaths profilePaths)
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
```

I checked the assembly strong name, and it seems to match:
```
> [System.Reflection.Assembly]::LoadFile("$PWd\..\PowerShellEditorServices\module\P
owerShellEditorServices\bin\Core\System.IO.Pipes.AccessControl.dll").FullName
System.IO.Pipes.AccessControl, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
```

**Comment by pjanotti** [comment]
Hum... do you have `System.Security.AccessControl.dll` and `System.IO.Pipes.dll` on the same folder?

**Comment by rjmholt** [comment]
Yes to `System.IO.Pipes.dll` but no to `System.Security.AccessControl.dll`. I'll put that in and give it a try

**Comment by pjanotti** [comment]
We will have to understand which dlls are being brought to the folder (are they from which package?). At this moment I think that if we can correctly build against netstandard2.0 and run with actual netcoreapp dlls it should work... I will have to continue this tomorrow...

**Comment by rjmholt** [comment]
Yes I didn't mean to keep you up -- I'm not in a rush.

I need to apologise -- it turns out the original error was being thrown by *Windows* PowerShell:
```
An error occurred while starting PowerShell Editor Services:

Exception calling "StartLanguageService" with "2" argument(s): "Access Control List (ACL) APIs are part of resource management on Windows and
are not supported on this platform."
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
Access Control List (ACL) APIs are part of resource management on Windows and are not supported on this platform.
   at System.Security.AccessControl.ObjectSecurity..ctor()
   at System.Security.AccessControl.CommonObjectSecurity..ctor(Boolean isContainer)
   at System.Security.AccessControl.NativeObjectSecurity..ctor(Boolean isContainer, ResourceType resourceType)
   at System.IO.Pipes.PipeSecurity..ctor()
   at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.Channel.NamedPipeServerListener.Start()
   at Microsoft.PowerShell.EditorServices.Host.EditorServicesHost.StartLanguageService(EditorServiceTransportConfig config, ProfilePaths profilePaths)
   at CallSite.Target(Closure , CallSite , Object , Object , Object )

```

PowerShell Core/netcoreapp2.1 works fine.

But to run in Windows PowerShell, I needed to add the System.IO.Pipes.dll dependencies. I kept following the errors one by one, until I added System.Security.Principal.Windows.dll and got this original error again.

**Comment by rjmholt** [comment]
The current DLLs in the Windows PowerShell bin folder are:
```
> ls .\modules\PowerShellEditorServices\bin\Desktop\


    Directory: C:\Users\roholt\Documents\Dev\vscode-PowerShell\modules\PowerShellE
    ditorServices\bin\Desktop


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       12/30/2017   8:31 AM           9052 libdisablekeyecho.dylib
-a----       12/30/2017   8:31 AM           8840 libdisablekeyecho.so
-a----         9/7/2018  12:34 AM         392192 Microsoft.PowerShell.EditorServic
                                                 es.dll
-a----         9/7/2018  12:34 AM          36352 Microsoft.PowerShell.EditorServic
                                                 es.Host.dll
-a----         9/7/2018  12:34 AM         247808 Microsoft.PowerShell.EditorServic
                                                 es.Protocol.dll
-a----        5/18/2018   1:46 AM         118272 Serilog.dll
-a----         5/9/2018  10:39 PM           8704 Serilog.Sinks.Async.dll
-a----       10/22/2017   4:48 PM          31744 Serilog.Sinks.Console.dll
-a----       10/29/2017   6:30 PM          26624 Serilog.Sinks.File.dll
-a----        5/15/2018   1:29 PM          27272 System.IO.Pipes.AccessControl.dll
-a----        5/15/2018   1:29 PM          54416 System.Security.AccessControl.dll
-a----         7/6/2018   1:01 PM          21736 System.Security.Principal.dll
-a----        5/15/2018   1:29 PM          39056 System.Security.Principal.Windows
                                                 .dll
-a----       12/30/2017   8:31 AM           4096 UnixConsoleEcho.dll

```

**Comment by pjanotti** [comment]
The symptom described seems to indicate that on Windows PowerShell the code is attempting to _run_ against some netstandard dll, which typically shouldn't happen but seems related to the way dlls are being added in the build of the project. 

At first thought for Windows Powershell you shouldn't need to reference pipe and PipeSecurity related via System.IO.Pipes, you actually should get those via System.Core, the ACL stuff itself should be in mscorlib and already loaded in Powershell itself. That said I need to better understand how the project is pulling these dependencies. I will try to see if I can figure it out from your PR but I appreciate any guiding information.

**Comment by tylerl0706** [comment]
@pjanotti this is a part of PowerShell Editor Services which is the essentially a C#-based PowerShell module. 

In other words, this code gets loaded into a PowerShell session... so all assemblies from PowerShell are already there - like you said. In order to cut down on dlls we ship in the module, we copy only the dlls that matter into a module directory (aka just the finished product):
https://github.com/PowerShell/PowerShellEditorServices/blob/master/PowerShellEditorServices.build.ps1#L204-L252

NOTE: That code is when PowerShell Editor Services was built for net451 and netstandard1.6. We separated the code that gets loaded into Windows PowerShell vs PowerShell Core.

In the PR that @rjmholt is working on, he's converting everything to .NET Standard 2.0 and completely removing net451 from the source. That means we get rid of the "Desktop" and "Core" folders we use to have (see that link for references to that) and just have all the dlls in one place.

I hope that provides some context.

**Comment by pjanotti** [comment]
Thanks @tylerl0706 useful information.

**Comment by tylerl0706** [comment]
oh also, here's the PR he's working on:
https://github.com/PowerShell/PowerShellEditorServices/pull/741

(p.s. he's in Australia so response times will be staggered)

**Comment by rjmholt** [comment]
Sorry about the hiatus -- I was in transit all weekend.

So the project populates all the DLLs by publishing locally as a normal netstandard2.0 classlib.

Then it takes the EditorServices DLLs (our code) plus any dependencies that PowerShell itself doesn't already provide and drops them in a folder (currently two folders -- Desktop and Core -- for Windows PowerShell and PowerShell Core respectively).

We then `Add-Type` (`Assembly.Load()`) the EditorServices DLLs and rely on same-dir assembly dependency resolution to resolve other dependencies EditorServices has.

The problem seems to be as you say -- that Windows PowerShell tries to resolve its dependency on `PipeSecurity` and is looking at the netstandard2.0 assembly for it rather than getting it from the relevant Framework assembly (I assume in the GAC?).

Anyway, I just tried downloading the [System.IO.Pipes.AccessControl nuget package](https://www.nuget.org/packages/System.IO.Pipes.AccessControl/) and placing the net461 runtime assembly into the bin folder and get the same error.

I'm at a bit of a loss, especially since we got this to work with the netstandard1.3 runtime DLL loaded by Windows PowerShell somehow...

Is there maybe a shim assembly that I should be including?

**Comment by rjmholt** [comment]
I've also tried a custom `ResolveEventHandler` like in this gist: https://gist.github.com/JamesRandall/444f3365751edb130bef197f2222cfa5

But that didn't work either unfortunately, although I might not have used it correctly.

**Comment by rjmholt** [comment]
I tried this:
```powershell
    $onAssemblyResolveEvent = [System.ResolveEventHandler] {
        param($sender, $e)

        Write-Host "Using custom assembly resolver"

        if ($e.Name.StartsWith("System.IO.Pipes")) {
            Write-Host "Found pipelike asm: $($e.Name)"
            return $coreAsm
        }

        Write-Host "Searching loaded assemblies"
        foreach ($asm in [System.AppDomain]::CurrentDomain.GetAssemblies()) {
            if ($asm.FullName -eq $e.Name) {
                Write-Host "Found $($asm.FullName)"
                return $asm
            }
        }

        Write-Host "Returning `$null"
        return $null
    }

    [System.AppDomain]::CurrentDomain.add_AssemblyResolve($onAssemblyResolveEvent)

    Microsoft.PowerShell.Utility\Add-Type -Path "$PSScriptRoot/bin/Desktop/Microsoft.PowerShell.EditorServices.dll"
    Microsoft.PowerShell.Utility\Add-Type -Path "$PSScriptRoot/bin/Desktop/Microsoft.PowerShell.EditorServices.Host.dll"

    [System.AppDomain]::CurrentDomain.remove_AssemblyResolve($onAssemblyResolveEventHandler)
```

And get the following output on startup:
```
Loading Windows PowerShell module
PowerShell Integrated Console

Using custom assembly resolver
Found pipelike asm: System.IO.Pipes.AccessControl, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Using custom assembly resolver
Searching loaded assemblies
Returning $null
Using custom assembly resolver
Searching loaded assemblies
Returning $null
Using custom assembly resolver
Searching loaded assemblies
Returning $null
Using custom assembly resolver
Searching loaded assemblies
Returning $null


An error occurred while starting PowerShell Editor Services:

Exception calling "StartLanguageService" with "2" argument(s): "Could not load file or assembly 'System.IO.Pipes.AccessControl, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
Could not load file or assembly 'System.IO.Pipes.AccessControl, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.Channel.NamedPipeServerListener.Start()
   at Microsoft.PowerShell.EditorServices.Host.EditorServicesHost.StartLanguageService(EditorServiceTransportConfig config, ProfilePaths profilePaths)
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)



```

**Comment by pjanotti** [comment]
The summary seems to be: on PowerShell for Windows it works with netstandard1.3 but not netstandard2.0 with pwsh (netcoreapp2.1) it works fine. Is that correct?

**Comment by rjmholt** [comment]
netstandard1.3 was only used for netcoreapp2.0 and netcoreapp2.1 (pwsh) -- we didn't use netstandard with Windows PowerShell previously.

So I would summarise as:
- We used to compile net451 binaries for Windows PowerShell, so there was no netstandard dependency (no System.IO.Pipes.AccessControl DLL anywhere)
- Now we are trying to load the assemblies as a netstandard2.0 library
- The assemblies get loaded [with `Add-Type -Path MainAssembly.dll`](https://github.com/PowerShell/PowerShellEditorServices/blob/f45c6312a859cde4aa25ea347a345e1d35238350/module/PowerShellEditorServices/PowerShellEditorServices.psm1#L6-L14), and we rely on assembly resolution to pull in the dependencies from the same directory as needed
- When we do this in Windows PowerShell, one of two things happens:
    1. If System.IO.Pipes.AccessControl.dll and all the other netstandard dependencies are present (the binary directory looks like [1]), we get the `PlatformNotSupported` exception described originally [3].
    2. If those dependencies are taken away (binary directory looks like [2]), we get a `FileNotFoundException` [4]
- Trying to add a custom `ResolveEventHandler` for this also fails, as in https://github.com/dotnet/corefx/issues/32152#issuecomment-420088695
- So there seems to be no way to force the netstandard2.0-compiled DLLs to bind to the GAC/runtime-provided pipe types in Windows PowerShell

[1]:
```
> ls .\modules\PowerShellEditorServices\bin\Desktop\


    Directory: C:\Users\roholt\Documents\Dev\vscode-PowerShell\modules\PowerShellEditorServices\bin\Desktop


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        9/10/2018   5:04 PM         392192 Microsoft.PowerShell.EditorServices.dll
-a----        9/10/2018   5:04 PM          36352 Microsoft.PowerShell.EditorServices.Host.dll
-a----        9/10/2018   5:04 PM         247808 Microsoft.PowerShell.EditorServices.Protocol.dll
-a----        5/18/2018   1:46 AM         118272 Serilog.dll
-a----         5/9/2018  10:39 PM           8704 Serilog.Sinks.Async.dll
-a----       10/22/2017   4:48 PM          31744 Serilog.Sinks.Console.dll
-a----       10/29/2017   6:30 PM          26624 Serilog.Sinks.File.dll
-a----         6/6/2018   1:29 PM          27280 System.IO.Pipes.AccessControl.dll
-a----        5/15/2018   1:29 PM          54416 System.Security.AccessControl.dll
-a----         7/6/2018   1:01 PM          21736 System.Security.Principal.dll
-a----        5/15/2018   1:29 PM          39056 System.Security.Principal.Windows.dll
```

[2]:
```
> ls .\modules\PowerShellEditorServices\bin\Desktop\


    Directory: C:\Users\roholt\Documents\Dev\vscode-PowerShell\modules\PowerShellEditorServices\bin\Desktop


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        9/10/2018   2:58 PM         392192 Microsoft.PowerShell.EditorServices.dll
-a----        9/10/2018   2:58 PM          36352 Microsoft.PowerShell.EditorServices.Host.dll
-a----        9/10/2018   2:58 PM         247808 Microsoft.PowerShell.EditorServices.Protocol.dll
-a----        5/18/2018   1:46 AM         118272 Serilog.dll
-a----         5/9/2018  10:39 PM           8704 Serilog.Sinks.Async.dll
-a----       10/22/2017   4:48 PM          31744 Serilog.Sinks.Console.dll
-a----       10/29/2017   6:30 PM          26624 Serilog.Sinks.File.dll
```

[3]:
```
An error occurred while starting PowerShell Editor Services:

Exception calling "StartLanguageService" with "2" argument(s): "Access Control List (ACL) APIs are part of resource management on Windows and are not supported on this platform."
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
Access Control List (ACL) APIs are part of resource management on Windows and are not supported on this platform.
   at System.Security.AccessControl.ObjectSecurity..ctor()
   at System.Security.AccessControl.CommonObjectSecurity..ctor(Boolean isContainer)
   at System.Security.AccessControl.NativeObjectSecurity..ctor(Boolean isContainer, ResourceType resourceType)
   at System.IO.Pipes.PipeSecurity..ctor()
   at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.Channel.NamedPipeServerListener.Start()
   at Microsoft.PowerShell.EditorServices.Host.EditorServicesHost.StartLanguageService(EditorServiceTransportConfig config, ProfilePaths profilePaths)
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
```

[4]:
```
An error occurred while starting PowerShell Editor Services:

Exception calling "StartLanguageService" with "2" argument(s): "Could not load file or assembly 'System.IO.Pipes.AccessControl, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified."
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
Could not load file or assembly 'System.IO.Pipes.AccessControl, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.Channel.NamedPipeServerListener.Start()
   at Microsoft.PowerShell.EditorServices.Host.EditorServicesHost.StartLanguageService(EditorServiceTransportConfig config, ProfilePaths profilePaths)
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
```

(I really do apologise for this)

**Comment by rjmholt** [comment]
I've now also tried including netstandard.dll manually, as per https://github.com/PowerShell/PowerShell/blob/master/docs/cmdlet-example/command-line-simple-example.md#using-a-net-standard-20-based-binary-module-in-windows-powershell

**Comment by pjanotti** [comment]
Thanks for the detailed info.

>  there seems to be no way to force the netstandard2.0-compiled DLLs to bind to the GAC/runtime-provided pipe types in Windows PowerShell

Stepping back and thinking from the beginning: we want to build a library targeting netstandard but want to run the app loading it against some netfx version. In the typical build this means that when we "dotnet publish" the app against the desired framework it will actually gets the library dependencies for the framework not against netstandard. Viewing this way we should use System.IO.Pipes.AccessControls that targets a netfx version when loading Windows Powershell. As a consequence each different framework targeted for execution (netfx and netcoreapp) in this case needs its own set of dlls - the library itself can be built against netstandard but it needs to run in the context of a specific framework. Typically the build process, e.g.: dotnet publish, takes care of pulling the right for the netstandard library to work on top of the framework. Makes sense?

**Comment by rjmholt** [comment]
Yes that does indeed make sense!

The current command we (mis-)use is `dotnet publish -f netstandard2.0`, which may not make any sense.

The problem is that we're using netstandard2.0 in the hope of producing one set of DLLs to import in both Windows PowerShell and PowerShell Core.

In a classlib scenario we would use `dotnet build` and just generate our DLLs without the dependencies. But because PowerShell has some and omits others, we try to fill in the gaps (something @joeyaiello has been keen to tool).

But I'm guessing you're saying that means we need to publish and use different DLLs for different PowerShells, right?

**Comment by pjanotti** [comment]
> you're saying that means we need to publish and use different DLLs for different PowerShells, right?

Right. Windows PowerShell targets netfx needs that specific set, pwsh targets netcoreapp needs a different set.

**Comment by tylerl0706** [comment]
Sorry for my ignorance, but isn't the point of the .NET Standard Dlls so that we can just reference the same dll and it will be properly shimmed over to the correct assembly?

**Comment by pjanotti** [comment]
A netstandard defines a set of APIs available to library writers. However, you run applications against an actual framework, not a netstandard. For each distinct framework, netstandard APIs can be shimmed in different ways.

**Comment by rjmholt** [comment]
After a fair amount of discussion with @SteveL-MSFT and @daxian-dbw, we've determined the following (I'm guessing this is all very known to the .NET team, but I didn't come across it in my reading and I want to document it here):
- We want a single codebase compiled only against netstandard2.0 with no `#if`-defs anywhere (that's the point of our move to netstandard2.0 -- we previously compiled against netstandard1.6 and net451 and it was getting hard to maintain).
- We have a dependency on `System.IO.Pipes.PipeSecurity`, which isn't in netstandard2.0 but is in netcoreapp2.0/netcoreapp2.1 and is in net461/net471
- Because we have written against netstandard2.0 only, `dotnet publish` only works as `dotnet publish -f netstandard2.0` -- we can't do `dotnet publish -f net471` and just get a working implementation in a new folder, but we can't compile against net471 directly either
- `dotnet publish -f netstandard2.0` creates dummy assemblies that just throw (ildasm is helpful for checking here if loading and running is time consuming)
- **But**, when PowerShell Core loads our DLLs, it already includes Windows Compatibility Pack (WCP) shims and prioritises those, so it never tries to use the netstandard ones. The publish step in the build also produces these .NET Core WCP shim assemblies under publish/runtimes/win/ (again, ildasm is helpful here)
- We need a similar thing to happen for .NET framework, but Windows PowerShell has no such magic and the .NET Framework/GAC doesn't have the WCP shim assemblies at present
- So our current plan is to create a dummy project targeting net471 (or possibly net461 if that works) that just targets WCP, publish it to get the shim DLLs for .NET Framework to link back to System.Core and dump the ones we need into the module bin dir (for now into the Desktop dir, but ideally we can merge them, since PowerShell Core will never try to load those assemblies)

Anyway, this is all a lot of effort for a PowerShell IDE engine that we already had working, **but** it will come in a lot of use as we have more and more PowerShell module authors trying to target both Windows PowerShell and PowerShell Core.

**Comment by danmosemsft** [comment]
@pjanotti maybe for S.S.AccessControl we should somehow improve the string "Access Control List (ACL) APIs are part of resource management on Windows and are not supported on this platform." since in this case they were running on Windows so it's confusing.

**Comment by rjmholt** [comment]
Ok, downloading the net461 packages from NuGet and placing them has solved my issue. In fact, because PS Core uses WCP shims to resolve the Windows-specific assemblies, we have been able to place everything in a single combined directory; PS Core never gets to loading the net461 assembies, and Windows PowerShell hits the System.IO.Pipes.AccessControl shims and correctly links into System.Core.

Thanks for your help everyone! Sorry to have been such a bother -- this has been really valuable learning though in terms of documenting how to write a cross-platform PowerShell module from now on.

**Comment by rjmholt** [comment]
Oh, wanted to note:
- Yes, an error message saying something like "this assembly is a facade assembly and you aren't supposed to be executing it, silly" would be helpful
- Does `dotnet publish -f netstandard2.0` have a meaningful output? It makes sense that netstandard assemblies that aren't covered by netstandard.dll won't do anything, but when `dotnet publish -f netstandard2.0` worked, I started to think otherwise. I had two thoughts on that:
    + Maybe `dotnet publish -f netstandard2.0` should error out and say "what are you hoping to achieve with this? Only building makes sense with netstandard2.0"
    + At some point I managed to mislead myself into thinking that writing a netstandard library might mean I could do something like `dotnet publish -f net461` and have the dotnet CLI produce a concrete net461 instantiation of my netstandard classlib. Just a thought

Anyway, thanks again for your help everyone. I really do appreciate it!
