### ISSUE TITLE
How can I pin `ref T` in class constructor and unpin it in Dispose?

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/corefx#32155]
How can I pin `ref T` in class constructor and then unpin it in Dispose?

**Comment by jkotas** [comment]
There is no way to do this today.

**Comment by AlexRadch** [comment]
@jkotas I does not understand. Does Span and ReadOnlySpan pin memory until destructed?

**Comment by benaadams** [comment]
You'd have to go via `Memory<T>` if you want to pin across stack frames.

`Span<T>` can be pointing at stack memory, which is no longer valid memory when you exit the method; which is why `async` uses `Memory<T>` rather than `Span<T>`.

**Comment by jkotas** [comment]
Span and ReadOnlySpan do not pin memory on its own. They pin memory only if you ask for it explicitly via the `fixed` statement. E.g.

```csharp
fixed (byte * p = spanOfByte)
{
   ... the memory is pinned within this scope only ...
}
````

**Comment by AlexRadch** [comment]
I can not fix `ref T` with error 'CS8385 C# The given expression cannot be used in a fixed statement'
```cs
        public void Pin(Span<byte> span)
        {
            unsafe
            {
                fixed(byte* p = MemoryMarshal.GetReference(span))
                {

                }

                fixed(byte* p = ref MemoryMarshal.GetReference(span))
                {

                }
            }
        }
```

**Comment by jkotas** [comment]
> How can I implement this?

You need to require memory to be pinned by calling code, like this:

```csharp
fixed(byte* p = span)
{
   UnsafeSpan<byte> unsafeSpan(p, span.Length);
...
}
```

**Comment by AlexRadch** [comment]
It is so sadly ;) . I wanted use it like next: `using (var uSpan =  new UnsafeSpan(span) { ... }` and does not use `fixed` inside usual code.

**Comment by benaadams** [comment]
You would also need this https://github.com/dotnet/csharplang/issues/1623 to use `using` on a `ref struct`
