### ISSUE TITLE
Unable to use client certificate authentication with WebApplicationFactory

### ISSUE THREAD

**Issue by vdachev** [dotnet/corefx#32159]
Hello,

I'm trying to set up an integration test for a web application that uses certificate authentication. I use the following code fragment to instantiate the `HttpClient`:
```csharp
var factory = new WebApplicationFactory<Startup>();
HttpClient client = factory.CreateClient();
```
However, I want to pass a client certificate when requesting a resource. The problem is, the client certificate collection is stored in the `HttpClientHandler` but I could not find a way to provide the `WebApplicationFactory` constructor with an instance to the `HttpClientHandler`, neither I found a way to access it through the `HttpClient` or `WebApplicationFactory` instances.

Could you please hint me of a way to achieve that?

**Comment by karelz** [comment]
This issue was moved to aspnet/Home#3518
