### ISSUE TITLE
Can't use Expression bodied finalizers

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#32162]
We are running into https://github.com/dotnet/roslyn-analyzers/issues/1804 with the latest toolset. This means if we write a finalizer like:

```C#
~PropertyEnumerator() => Dispose(false);
```

We get a compile error:

```
System\DirectoryServices\PropertyCollection.cs(188,14): error CA1821: Remove empty finalizers [D:\j\workspace\windows-TGrou---74aa877a\src\System.DirectoryServices\src\System.DirectoryServices.csproj]
```

This issue is tracking taking a new toolset with the above bug fixed, so we can revert the change I needed to make: https://github.com/dotnet/corefx/pull/31986/commits/61eb9502801f7bd1040fd28ceb5eb62806a54619. And for anyone who happens to run into this issue with new code.

See https://github.com/dotnet/corefx/pull/31986 for more info.

**Comment by weshaggard** [comment]
Closing this issue because we decide to disable the analyzer until https://github.com/dotnet/roslyn-analyzers/issues/1804 is fixed.
