### ISSUE TITLE
.NET Core daily builds of SDK ship with Microsoft.Private.Wpf package and Microsoft.NET.Sdk.Wpf

### ISSUE THREAD

**Issue by 4creators** [dotnet/corefx#32164]
First of all I am not sure that this is right repo to ask questions related to .NET Core UI work since there are no other public repos which handle any of the components mentioned in the title.

Shipping of the above packages raises several questions regarding work on porting Windows Forms and WPF to .NET Core v3.0:

1. Are the above packages usable and where can I find information how should I use them while creating WPF/Windows Forms .NET Core applications?
2. Does shipping of private packages without any corresponding public repo means that Microsoft has made decision on not open sourcing them?

Anyway, it's nice to see them shipped.

**Comment by jkotas** [comment]
The work on integrating these is happening in core-sdk repo, e.g. https://github.com/dotnet/core-sdk/pull/67 . The PRs in the SDK repo have details on the incremental steps what works. I believe that creating a new WinForms or WPF project works currently, but there is number of things that does not work yet.

The final decision on which exact parts of the UI stacks are going to be open sourced has not been made yet.

cc @richlander
