### ISSUE TITLE
System.IO.Pipelines package not produced in 2.2 builds

### ISSUE THREAD

**Issue by pakrym** [dotnet/corefx#32163]
There were fixes in System.IO.Pipelines release/2.2 branch and it's not part of the shared runtime.

See:
https://github.com/dotnet/versions/blob/5edf1b887358cc7fd8ba8bd91f8679ff924393e2/build-info/dotnet/corefx/release/2.2/Latest_Packages.txt#L59

**Comment by pakrym** [comment]
https://github.com/dotnet/corefx/pull/32203

**Comment by ahsonkhan** [comment]
With the changes in #32203, can this issue be closed now?

cc @wtgodbe

**Comment by pakrym** [comment]
Neither 

https://github.com/dotnet/versions/blob/master/build-info/dotnet/corefx/release/2.1/Latest_Packages.txt

nor 

https://github.com/dotnet/versions/blob/master/build-info/dotnet/corefx/release/2.2/Latest_Packages.txt

Has a new version of pipelines

**Comment by wtgodbe** [comment]
It's not in 2.2 because we'll only be shipping it out of 2.1 (that is, since the change is in both branches, we'll ship it out of 2.1 - 2.2 only ships changes that are specific to itself). As for 2.1, the last successful build was from this commit: https://github.com/dotnet/corefx/commit/8060e77b96fc31d9f301e2519275eb2236dedd0d. This was merged on September 7, before my change on September 11. The next green build of 2.1 should include the updated package for pipelines. I'm happy to keep this open until we confirm that, though.

**Comment by pakrym** [comment]
Which version of System.IO.Pipelines would flow through 2.2 prodcon build?

**Comment by wtgodbe** [comment]
System.IO.Pipelines won't get built by CoreFx in 2.2 - we only build packages for libraries that have changes specific to that release. If any of the other repos depend on System.IO.Pipelines, I suppose they'll just restore whatever version they depend on from myget.

**Comment by pakrym** [comment]
My scenario is the following: in ASP.NET Core 2.2 branch we have a test that fails without a pipeline fix that went into 2.1 and 2.2. 

My concern is that the version of System.IO.Piplines we would get in 2.2 prodcon build would be `4.5` and would cause the test to fail all the time.

**Comment by wtgodbe** [comment]
I see. I would think you'd be able to depend on the version that comes out of 2.1 (should be `4.5.2`) once we get a green build from that branch? I can talk to @mmitche about running manual builds to try to expedite that.

**Comment by wtgodbe** [comment]
We have a new version of Pipelines being produced by 2.1 - https://github.com/dotnet/versions/blob/master/build-info/dotnet/corefx/release/2.1/Latest_Packages.txt. Closing.

**Comment by pakrym** [comment]
@natemcmaster, can you help me understand if and how this would work in prodcon builds? What I expect to happen is during 2.2 prodcon build we would get packages from https://github.com/dotnet/versions/blob/master/build-info/dotnet/corefx/release/2.2/Latest_Packages.txt and such downgrade pipelines to 4.5.0 failing all tests that depend on fixes.

@wtgodbe additional question, isn't 4.5.1 package the one we shipped for 2.1.5 security patch? If so we should be producing different package because release/2.1 contains more fixes than a single one from 2.1.5 patch.

**Comment by natemcmaster** [comment]
ProdCon only flows package versions if the package is built. Since System.IO.Pipelines is not produced in the 2.2 branch, we need to update aspnet's 2.2 builds to make sure we use the latest version of this package. Based on what I see in nuget.org, that is System.IO.Pipelines 4.5.2.

**Comment by karelz** [comment]
This was addressed in release/2.1 branch by PR #32203.
