### ISSUE TITLE
Failing IO tests on netfx that rely on PathFeature switches

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#32167]
https://github.com/dotnet/corefx/pull/32160#issuecomment-419516999.

Disabling these tests that started to fail when upgrading xunit to 2.4.1: https://github.com/dotnet/corefx/pull/32160/commits/7aca9d86da70a5e707a87866d5073268eec2ee21

```
DirectoryLongerThanMaxDirectoryAsPath_Succeeds
DirectoryLongerThanMaxPath_Succeeds
EnumerateFilesDirectoryOverLegacyMaxPath
EnumerateFilesOverLegacyMaxPath
SearchPatternLongPath
OverMaxPathWorks_Windows
ZipWithInvalidFileNames_ParsedBasedOnSourceOS (System.IO.Compression)
```

**Comment by JeremyKuhne** [comment]
These were re-enabled in https://github.com/dotnet/corefx/commit/d29c16c99c6045ee67444a7a693dd4476861c463.
