### ISSUE TITLE
SignedCms.ComputeSignature throws invalid exception type when signer certificate is not provided

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#32171]
Repro:

```csharp
ContentInfo ci = new ContentInfo(new byte[1]);
SignedCms cms = new SignedCms(ci);
cms.ComputeSignature();
```

On full framework we get following exception (this is what's expected):

```
System.InvalidOperationException: The recipient certificate is not specified.
```

.NET Core exception:

```
System.PlatformNotSupportedException: No signer certificate was provided. This platform does not implement the certificate picker UI.
```

**Comment by filipnavara** [comment]
I don't think it's wrong per-se, the `SignedCms.ComputeSignature` API with no arguments is just not supported.

**Comment by filipnavara** [comment]
However, the following code is supported and throws `NullReferenceException`:

```c#
	ContentInfo ci = new ContentInfo(new byte[1]);
	SignedCms cms = new SignedCms(ci);
	cms.ComputeSignature(new CmsSigner(SubjectIdentifierType.IssuerAndSerialNumber), true);
```

**Comment by filipnavara** [comment]
The overload is not useful without a certificate (aside from the special NoSignature mode, which is broken). The only way it can obtain a certificate is through UI, which is not supported, hence `PlatformNotSupportedException`.
