### ISSUE TITLE
Update build.cmd for dev16 cmd prompt

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#32197]
Apparently it does not work in a dev16 cmd prompt yet. 

fyi @weshaggard

**Comment by danmosemsft** [comment]
@weshaggard I haven't tried it - @Pilchie reported it and I haven't installed it yet to see.

**Comment by weshaggard** [comment]
Good that it at least fails with the correct message :) Once I get a dev16 dogfood build going I'll fix this up and test it.

**Comment by weshaggard** [comment]
Fixed by https://github.com/dotnet/arcade/pull/1016.
