### ISSUE TITLE
Mount database on sql server by code

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#32208]
@RussKeldorph commented on [Mon Sep 10 2018](https://github.com/dotnet/core/issues/1927)

_From @mferraricloudsurfers on September 5, 2018 7:39_

Starting from mdf and ldf files and knowing the sql server connection credentials, I want to mount the database by code using .NET Core 2.
Is it possible?

_Copied from original issue: dotnet/coreclr#19834_

---

@RussKeldorph commented on [Mon Sep 10 2018](https://github.com/dotnet/core/issues/1927#issuecomment-419986687)

I don't think coreclr is the right place for this issue, but I'm not sure where to redirect it, so moving to core in hopes of finding the right home.

---

@pietrodicaprio commented on [Mon Sep 10 2018](https://github.com/dotnet/core/issues/1927#issuecomment-420062588)

I think this could be a good start point: https://stackoverflow.com/questions/35700066/attach-database-programmatically 
This gives you a lot of informations and code: http://justlikeamagic.com/2010/04/13/programmatically-enumerating-attaching-and-detaching-sql-server-databases/
This is another short example: https://stackoverflow.com/questions/4218960/how-to-restore-sql-server-database-through-c-sharp-code

None of these are made using Net Core but since we are talking about SQL queries, and not about C# functions, you have all the information and probably most of the code is copy and paste.

**Comment by GSPP** [comment]
You can do this using the SQL Server SMO libraries. The .NET Core libraries are not the right place for such specific functionality.

**Comment by David-Engel** [comment]
This question is more of a "how do I do X in C#". I would ask in the TechNet SQL Server SMO/DMO forum: https://social.technet.microsoft.com/Forums/en-US/home?forum=sqlsmoanddmo
