### ISSUE TITLE
MultiValueDictionary - outdated README.md?

### ISSUE THREAD

**Issue by dsaf** [dotnet/corefx#32218]
Previously tracked as #1306.

This readme section on $master does not reflect the reality...:

![image](https://user-images.githubusercontent.com/3845650/45352266-048cad80-b5b0-11e8-96c6-9750d9504a4a.png)

...given these:

![image](https://user-images.githubusercontent.com/3845650/45352331-2b4ae400-b5b0-11e8-8305-a2e3ef12d2ec.png)

![image](https://user-images.githubusercontent.com/3845650/45352365-4158a480-b5b0-11e8-8c09-461e94fd1591.png)

**Comment by karelz** [comment]
Seems to be related to corefxlab. Or are the sources already in CoreFX repo?

**Comment by safern** [comment]
The sources are in corefxlab. That means that the issue's right place should be in corefxlab right?

**Comment by safern** [comment]
I will take care of it. Not worth moving the issue, it is just updating the README.md in corefxlab. Assigned.

**Comment by danmosemsft** [comment]
fixed
