### ISSUE TITLE
Weird behaviour of decimal.Round

### ISSUE THREAD

**Issue by Necronux** [dotnet/corefx#32221]
What is the default behaviour of `decimal.Round`?

https://github.com/dotnet/corefx/blob/664d98b3dc83a56e1e6454591c585cc6a8e19b78/src/Common/src/CoreLib/System/Decimal.cs#L612

Looks like it rounds to even by default but in cases like:

`decimal.Round(1.035m, 2)` and `decimal.Round(1.035, 2, MidpointRounding.AwayFromZero)` the result is identical.

@pentp 

Shouldn't `decimal.Round(1.035m, 2)` give `1.03` instead of `1.04`?

https://github.com/dotnet/corefx/blob/61d792e202d039c304c4f04ad816a57688f32fd4/src/Common/src/CoreLib/System/Decimal.DecCalc.cs#L2429-L2444

Does adding `MidpointRounding.AwayFromZero` make it any different?

**Comment by pentp** [comment]
`decimal.Round(1.035m, 2)` rounds to 1.04 because 4 is even. For example 1.025m rounds to either 1.02 or 1.03 based on rounding mode.

**Comment by Necronux** [comment]
@pentp  oh I get it now! Thanks!
