### ISSUE TITLE
MemberInfo.ReflectedType returns wrong reflected type for an event method

### ISSUE THREAD

**Issue by non-conformances-research** [dotnet/corefx#32232]
According to specification of MemberInfo.ReflectedType (https://docs.microsoft.com/en-us/dotnet/api/system.reflection.memberinfo.reflectedtype?view=netcore-2.1), it "gets the class object that was used to obtain this instance of MemberInfo". But using the following program the output is different:

```
using System;
using System.Reflection;

public class A
{
    public event Action Event { add { } remove { } }
}

public class B : A
{
    public static void Main(string[] args)
    {
        Type type = typeof(B);
        EventInfo eventInfo = type.GetEvent(nameof(A.Event));
        MemberInfo memberInfo = eventInfo.AddMethod;
        Console.WriteLine(memberInfo.ReflectedType);
    }
}
```

**Affected versions:**

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     deepin
 OS Version:  15.7
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.401/

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  2.1.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Steps to reproduce:**

1. Compile above program
2. Run it using dotnet/corefx

**Current result:**

```
B
```

**Expected result:**

```
A
```

**Comment by AtsushiKan** [comment]
That verbiage is referring to the System.Type apis that retrieve members off types using combinations of names, binding flags, and parameter types. `GetMethod`, `GetProperty`, `GetMember`, etc. 

It doesn't apply to every api that happens to yield a member info.

**Comment by non-conformances-research** [comment]
I'm confused. Could you point a document showing how to get a ReflectedType in this case? There are multiple MemberInfo specifications?

**Comment by jnm2** [comment]
@non-conformances-research The reflected type of accessors is the same as the reflected type of the EventInfo or PropertyInfo. Anything else would be counter-intuitive. What problem are you trying to solve?

**Comment by non-conformances-research** [comment]
@jnm2 We are investigating non-conformances between implementation and specification of reflection API. Have you ever faced similar issues?

**Comment by jnm2** [comment]
The issue you described in this thread is not a non-conformance. It is behaving intuitively and according to the spec. I'm not aware of personally experiencing a discrepancy between the spec and the implementation.

**Comment by svick** [comment]
I'm with @jnm2, why do you think the output is not in line with the documentation?

The documentation says `ReflectedType` returns the type you used to get the `MemberInfo`. The type you (indirectly) used is `typeof(B)`, which is what is returned. Where's the discrepancy?
