### ISSUE TITLE
ConditionalExpression - Undesirable cloning behavior in Update method

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#3223]
The Update method has the following logic:

if (test == Test && ifTrue == IfTrue && ifFalse == IfFalse)

The IfFalse property is implemented as follows for "IfThen" expressions (through a virtual GetFalse method):

return Expression.Empty();

This results in the creation of a new object each time. As a result, the Update method's logic will never cause the current instance to be returned, causing cloning behavior of the entire (sub)tree, e.g. during a visit. This turns out to be very expensive for large trees.

**Comment by bartdesmet** [comment]
This is related to #2809 but a bit different. The "IfThen" variant of ConditionalExpression can still create a new instance of Empty each time for its IfFalse branch, but it should not get recreated each time when Update performs its analysis to decide whether the tree needs cloning or not.

**Comment by VSadov** [comment]
It does seem unintentional that  IfThen on an otherwise immutable node returns different instance every time.
