### ISSUE TITLE
System.Security.Claims.ClaimTypes.Email value does not match the summary URI for the claim

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#32236]
@mattchidley commented on [Tue Sep 11 2018](https://github.com/dotnet/core/issues/1933)

# The value of the Email claim type does not match the URI for the claim, is this intentional?

# General

Current value:
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"

Should this be:
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/email"

The documentation below leads me to believe it should be the ladder:

https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claimtypes?view=netcore-2.1

//
// Summary:
//     The URI for a claim that specifies the email address of an entity, http://schemas.xmlsoap.org/ws/2005/05/identity/claims/email.
public const string Email = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress";

**Comment by bartonjs** [comment]
The correct value is `emailaddress` (http://schemas.xmlsoap.org/ws/2005/05/identity/claims.xsd), so the field value is correct.  Following the docs link I also see "emailaddress" (not "email").

If you still see something saying "email" on docs.microsoft.com, please hit the button on the page to create an issue with the documentation.
