### ISSUE TITLE
HttpClient The operation was canceled

### ISSUE THREAD

**Issue by DeepSnowNeeL** [dotnet/corefx#32246]
(Cross posting from so because maybe this is an issue with HttpClient on docker img/linux ? https://stackoverflow.com/posts/52280806 )

I'm using HttpClient in my MVC application to call a php api which does html2pdf to generate invoices which encouter an error sometimes depending on the data I send.

I'm sending an `HttpContent` consisting of an html string of 5850 chars which is : https://pastebin.com/w5biyjPv 

I'm inside docker containers and recently upgraded from asp.net core 2.0 to 2.1 (i'm using microsoft/dotnet:2.1-aspnetcore-runtime), the previous error was A task was cancelled (without further info) and now I have more info. (I upgraded thinking it would solve my problem since I saw some github issues about HttpClient behaving strangely https://github.com/dotnet/corefx/issues/25800 )

Here a few things I know from my tests :

 - I tested my api with postman with the buggy data and it works so I know the api isn't the problem.
 - When I use the same piece of code with other data it works. (It **is** data related I think)
 - When it doesn't work, I don't even have logs that it's called on the php side (nginx logs)
 - I can change the timeout and wait an eternity (I tried 200secs timeout) it doesn't change the way it behaves

For info:

 - the api url is looking like http://php/  (so no https related issues)
 - The php api and the C# are on 2 docker containers on the same machine

My code looks like this :

(the HttpClient I use is created every time this method gets called, if needed I can add the code about that but it's not really relevent I think)
```c#
    public async Task<PDFResult> GetPdfFromHtml(string html)
    {
        if (string.IsNullOrEmpty(html))
        {
            throw new ServiceException("Cannot generate PDF File", "GetPdfFromHtml");
        }

        var cts = new CancellationTokenSource();
        cts.CancelAfter(TimeSpan.FromSeconds(10));

        try
        {
            var postData = new List<KeyValuePair<string, string>>();
            //html = "<div>test</div>";
            //html = test;
            postData.Add(new KeyValuePair<string, string>("Html", JsonConvert.SerializeObject(html)));

            HttpContent DataContent = new MyFormUrlEncodedContent(postData); // tried https://stackoverflow.com/questions/23703735/how-to-set-large-string-inside-httpcontent-when-using-httpclient here


            Logger.LogWarning("request to " + HttpClient.BaseAddress + CommonConstants.PhpApiFolder + "/ for "+html.Length+" size");
            HttpResponseMessage response = await HttpClient.PostAsync(CommonConstants.PhpApiFolder + "/", DataContent, cts.Token);
            Logger.LogWarning("resp is " + response.IsSuccessStatusCode);
            if (response.IsSuccessStatusCode)
            {
                try
                {
                    string content = await response.Content.ReadAsStringAsync();
                    Logger.LogWarning("resp is " + content);
                    WebApiResult Base64PDFResult = JsonConvert.DeserializeObject<WebApiResult>(content);

                    if (Base64PDFResult == null || !Base64PDFResult.IsSuccess() || string.IsNullOrEmpty(Base64PDFResult.Message))
                    {
                        throw new Exception(Base64PDFResult.Message);
                    }

                    return new PDFResult(Base64PDFResult);
                }
                catch (Exception e)
                {
                    throw new ServiceException(string.Format("Cant get PDF result {0}", e.Message));
                }
            }
        }
        catch (TaskCanceledException e)
        {
            if (!cts.Token.IsCancellationRequested)
            {
                // Timed Out
                Logger.LogError(e, "PDFService GetPdfFromHtml timed out " + e.Message);
                return new PDFResult(Status.Error, e.Message);
            }
            else
            {
                // Cancelled for some other reason
                Logger.LogError(e, "PDFService GetPdfFromHtml other reason " + e.CancellationToken.IsCancellationRequested + " " + e.Message);
                return new PDFResult(Status.Error, e.Message);
            }
        }
        catch (Exception e)
        {
            Logger.LogError(e, "PDFService GetPdfFromHtml " + e.Message);
            return new PDFResult(Status.Error, e.Message);
        }
        return new PDFResult(Status.Error);
    }
```

The error I get is :

```
System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> 
System.IO.IOException: Unable to read data from the transport connection: Operation canceled. --->
System.Net.Sockets.SocketException: Operation canceled
       --- End of inner exception stack trace ---
       at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
       at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
       at System.Net.Http.HttpConnection.FillAsync()
       at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
       at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
       --- End of inner exception stack trace ---
       at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
       at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
       at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
       at Degineo.CommonServices.PDF.PDFService.GetPdfFromHtml(String html) in /var/jenkins_home/workspace/Pipeline-Beta/Degineo.CommonServices/PDF/PDFService.cs:line 48
```
(line 48 is the call to `await HttpClient.PostAsync`)

and the error pops exactly after reaching the 10 seconds timeout (the logs indicate that I pass in the "Cancelled for some other reason" part of the catch)

I don't understand why I get this error with this data, when some other works correctly.
Thanks for your help

**Comment by karelz** [comment]
Can you please clarify few things for us?
* Are you able to reproduce the problem 100%? Or just sometimes?
* Did you try to simplify the client to a simple .NET Core app (no ASP.NET Core)? (just to minimize the repro)
* Is the repro dependent on the data returned by the API being called? If yes, did you try to look at network capture logs to see what is going on? (maybe even comparing postman vs. .NET Core repro)
* Did you try to replace the PHP server with a another test server? (e.g. ASP.NET Core)
* Are you able to reproduce the same problem outside of Docker, or is it specific to that environment?

**Comment by DeepSnowNeeL** [comment]
> Can you please clarify few things for us?
> 
sure !

> * Are you able to reproduce the problem 100%? Or just sometimes?

100% 

> * Did you try to simplify the client to a simple .NET Core app (no ASP.NET Core)? (just to minimize the repro)

I should. I will try to setup something doing that

> * Is the repro dependent on the data returned by the API being called? If yes, did you try to look at network capture logs to see what is going on? (maybe even comparing postman vs. .NET Core repro)

The repro is dependent on the data I try to send (the data in my HttpContent) I even tried to play with the html like using random substrings of it, I'm trying actually to see which part of the html could trigger it.
(PS : I tried using bigger html data and it works, so it's not really the size of the html that matters I think)

> * Did you try to replace the PHP server with a another test server? (e.g. ASP.NET Core)

No didn't try, but I have few other cases where I use httpclient to call payment apis and never had any problem on thoses, moreover the php api isn't the problem since the request doesn't arrive to it when it crashes (and I tested the api by using it from my local environment which answers everytime correctly)

> * Are you able to reproduce the same problem outside of Docker, or is it specific to that environment?

I can't reproduce it locally, on my windows 10, everything works all the time.

**Comment by DeepSnowNeeL** [comment]
Allright so it was a problem with the php api, which freezes and never answers because of an image failing to load, so the c# correctly timeout in this specific case.

Thanks for helping me debug and sorry for the lost time, i'm closing the issue :)
