### ISSUE TITLE
Investigate if Unix X509Chain.Build has the same truth table as Windows

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#3225]
On Unix it seems to be returning false for any validation errors, and on Windows it might be more nuanced.

**Comment by eerhardt** [comment]
I think we are OK here.  From the [CertVerifyCertificateChainPolicy page on MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa377163(v=vs.85).aspx):
> If the chain can be verified for the specified policy, TRUE is returned and the dwError member of the pPolicyStatus is updated. A dwError of 0 (ERROR_SUCCESS or S_OK) indicates the chain satisfies the specified policy.
If the chain cannot be validated, the return value is TRUE and you need to verify the pPolicyStatus parameter for the actual error.

In the Windows ChainPal.Verify:
```C#
        public bool? Verify(X509VerificationFlags flags, out Exception exception)
        {
...
            if (!Interop.crypt32.CertVerifyCertificateChainPolicy(ChainPolicy.CERT_CHAIN_POLICY_BASE, _chain, ref para, ref status))
            {
                int errorCode = Marshal.GetLastWin32Error();
                exception = errorCode.ToCryptographicException();
                return default(bool?);
            }
            return status.dwError == 0;
        }
```

So Windows ChainPal.Verify will return `false` if the chain was verified and there is a validation error (i.e. when status.dwError is not 0).  This seems to match Unix: `return ChainStatus.Length == 0;`

**Comment by bartonjs** [comment]
Alright, that makes me feel better (and matches what I thought originally).  Thanks for providing a second opinion, @eerhardt!
