### ISSUE TITLE
StringComparer.CurrentCultureIgnoreCase does not ignore case when LANG=C.UTF-8

### ISSUE THREAD

**Issue by rjmholt** [dotnet/corefx#32250]
See also: https://github.com/PowerShell/PowerShell/issues/7761

For a small repro:
- Run `dotnet new console`
- Put the following in Program.cs:
    ```csharp
    using System;
    using System.Collections;

    namespace LangExample
    {
        class Program
        {
            static void Main(string[] args)
            {
                if (StringComparer.CurrentCultureIgnoreCase.Compare("String", "string") != 0)
                {
                    throw new Exception("Hashtable key comparison is case-sensitive");
                }

                Console.WriteLine("Working as expected");
            }
        }
    }
    ```
- Run `dotnet run` and get output:
    ```
    Working as expected
    ```
- Run `LANG=C.UTF-8 dotnet run` and get output:
    ```
    
    Unhandled Exception: System.Exception: Hashtable key comparison is case-sensitive
       at LangExample.Program.Main(String[] args) in /home/rob/Documents/Dev/sandbox/LangExample/Program.cs:line 18
    ```

Expected Behaviour (with `LANG=C.UTF-8`):
```csharp
StringComparer.CurrentCultureIgnoreCase.Compare("String", "string") == 0
```

Actual Behaviour (with `LANG=C.UTF-8`):
```csharp
String.Comparer.CurrentCultureIgnoreCase.Compare("String", "string") != 0
```

Runtime information:
```
> dotnet --version
2.1.401

> uname -a
Linux chronos 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

> cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

Given that `C.UTF-8` is a Debian locale, this is probably also the case on other Debian-based Linux distros.

**Comment by tarekgh** [comment]
https://github.com/dotnet/docs/issues/8179

**Comment by wfurt** [comment]
This still seems wrong @tarekgh I could see that the lang could impact default comparison but I would expect functions where explicitly asked for "IgnoreCase" do case-insensitive comparison.

**Comment by tarekgh** [comment]
@wfurt did you read the comment https://github.com/dotnet/corefx/issues/32250#issuecomment-420749205? it has the explanation there. IF you don't like the behavior switch off from POSIX and C.

**Comment by wfurt** [comment]
Yes, I did read through and I think the argument is not correct.
  I did also testing with native libc implementation and strcasecmp() keeps comparing in case _insensitive_ matter regardless of LANG.
I did not find any documentation suggesting that CurrentCultureIgnoreCase may or may not perform case insensitive matching.

**Comment by wfurt** [comment]
https://wiki.musl-libc.org/functional-differences-from-glibc.html 
musl-linux like Alpine is different from other distributions. The "normal" ways how to generate or changer locale does not quite work. 
https://bugs.alpinelinux.org/issues/7374

**Comment by danmosemsft** [comment]
@tarekgh what are your thoughts about @wfurt comment above?

i'm guessing most .NET code out there relies somewhere on case insensitive comparison, it seems quite odd if WSL is truly configured such that that is impossible. Should they set a different LANG? (Or maybe this is different in the new WSL2 )

**Comment by danmosemsft** [comment]
I see @tarekgh already updated docs which is good 😄  https://github.com/dotnet/docs/issues/8179

Just curious about @wfurt point.

**Comment by tarekgh** [comment]
To summarize/clarify, 

When setting the culture to "C", ICU map it to en_us_posix. and the posix locale is for sure doesn't support case insensitive comparisons. We are just working as ICU. So, .NET Core behavior is 100% matching ICU which is the main globalization component for Linux. In short, we are not defining how "C" locale work, we just do whatever ICU does.

Now, if we need to do something here, we can just start changing the mapping of "C" to something else rather than POSIX locale. This is kind of breaking change as no idea if there is people already taking dependency in such behavior. POSIX locale just doing that because people wanted to compare strings as binaries (regardless of using case sensitive option or not).

Let me know what you think.

CC @jkotas @stephentoub

**Comment by danmosemsft** [comment]
I see. In regular distros/shells, do they typically have different choices for LANG? I wonder why WSL does this, it seems like a large gotcha.

**Comment by tarekgh** [comment]
I can follow up with WSL team about that. but in Linux world think about "C" as invariant culture.

**Comment by wfurt** [comment]
Alpine is also like this. There really is no locale other than C. (see #35717)

**Comment by danmosemsft** [comment]
I am happy to close this and defer to experts. It would be great to circle back with WSL team's response. Thanks guys.
