### ISSUE TITLE
NetworkInterface.GetAllNetworkInterfaces Can not Run on Windows 10 Mobile

### ISSUE THREAD

**Issue by ArcheoCodix** [dotnet/corefx#32253]
Although version 2.0 of .NET Standard UWP can be used with recent versions of Windows 10. #9675
Windows 10 mobile did not have this update.
Any ideas of what to do ?

**Comment by karelz** [comment]
There is no 2.1 .NET Standard yet. Only 2.0. If .NET APIs you need don't work on the platform you're on (Win10 Mobile), the only other alternative I can imagine is to explore using directly underlying platform (UWP) APIs (WinRT APIs).

**Comment by ArcheoCodix** [comment]
Thank you for answering.
Sorry, I corrected my mistake.
Windows 10 mobile is in 10.0.15254, so it's impossible to install UWP App with .NET 2.0 UWP (16299 minimum).
WinRT functions can be used in a UWP app ?

**Comment by karelz** [comment]
> so it's impossible to install UWP App with .NET 2.0 UWP (16299 minimum)

Yeah, I think I heard about that. Sadly, it is decision of the underlying platform (Win10 Mobile), which I cannot do anything about.

WinRT APIs are the OS APIs, so yes, they are available in UWP apps.

Closing as the CoreFX portion of the question was covered.
