### ISSUE TITLE
Coding style inconsistency: namespace imports

### ISSUE THREAD

**Issue by qbit86** [dotnet/corefx#32277]
`Documentation/coding-guidelines/coding-style.md` says: 

> 6. Namespace imports... should be sorted alphabetically.

But following example contradicts this guideline (“M” after “S”):
```
using System;
...
using System.Diagnostics;
using Microsoft.Win32;
```

Should `System.*` namespaces be at the top, or overall sorting should be applied?

**Comment by sharwell** [comment]
System using directives are placed first:

https://github.com/dotnet/corefx/blob/bdd4e0bad42f02538b5d5163484caf8abeebc65f/.editorconfig#L83

**Comment by qbit86** [comment]
> System using directives are placed first

Then could you please update `coding-style.md` to mention this explicitly?

**Comment by danmosemsft** [comment]
@qbit86 feel free to offer a PR for the coding style.

**Comment by danmosemsft** [comment]
Thanks @catcake 	@qbit86 	 !
