### ISSUE TITLE
"*\0".IndexOf("\0") returns 0 on linux

### ISSUE THREAD

**Issue by LastExceed** [dotnet/corefx#32285]
- Happens with any string containing null-characters regardless of their position
- Similarly `.LastIndexOf()` always returns the length of the string - 1 (most likely related)
- Returns `-1` as expected when no null-character is present
- Also happens when searching for `"\0*"` in `"*\0*"`
- Specifying a string comparison type doesn't help
- Does NOT happen when searching for `'\0'` or `char.MinValue` instead of `"\0"`
- Does NOT happen on windows

**Comment by danmosemsft** [comment]
What version -- is this using bits from master?

**Comment by danmosemsft** [comment]
What about `"*\0".IndexOf('\0', StringComparison.OrdinalIgnoreCase)` (char overload ignore case)

**Comment by LastExceed** [comment]
I'm using version 2.1.4

**Comment by stephentoub** [comment]
cc: @tarekgh

**Comment by tarekgh** [comment]
I have tried that on Linux with 2.1 with the following calls:

```
 "*\0".IndexOf("\0") returns 0
 "*\0".IndexOf("\0", StringComparison.Ordinal) returns 1
 "*\0".IndexOf('\0') returns 1
 "*\0".IndexOf('\0', StringComparison.Ordinal) returns 1
```

All results are expected. I am not sure how you are getting -1 in your case. please send more information or a small repro from your end. also, would be nice to tell more about your environment you are running on. I am closing the issue but feel free to respond back and I'll be happy to look more at that.

**Comment by tarekgh** [comment]
https://github.com/dotnet/coreclr/issues/2051

**Comment by LastExceed** [comment]
>I am not sure how you are getting -1 in your case

Read carefully:
- Returns `-1` as expected when no null-character is present
----
```c sharp
Console.WriteLine("caseA\tcaseB\tcaseC\tcaseD\tcaseE\tcaseF\tcomparisonType");
foreach (StringComparison comparisonType in Enum.GetValues(typeof(StringComparison))) {
    Console.Write("x\0y".IndexOf("\0", comparisonType) + "\t"); //caseA
    Console.Write("x\0y".IndexOf('\0', comparisonType) + "\t"); //caseB
    Console.Write("x\0y".IndexOf("\0y", comparisonType) + "\t");//caseC
    Console.Write("x\0y".IndexOf("xy", comparisonType) + "\t"); //caseD
    Console.Write("xy".IndexOf("\0y", comparisonType) + "\t");  //caseE
    Console.Write("xy".IndexOf("x\0", comparisonType) + "\t");  //caseF
    Console.WriteLine(comparisonType.ToString());
}
```
output on windows (win7hp64sp1):
```
caseA   caseB   caseC   caseD   caseE   caseF   comparisonType
1       1       1       -1      -1      -1      CurrentCulture
1       1       1       -1      -1      -1      CurrentCultureIgnoreCase
1       1       1       -1      -1      -1      InvariantCulture
1       1       1       -1      -1      -1      InvariantCultureIgnoreCase
1       1       1       -1      -1      -1      Ordinal
1       1       1       -1      -1      -1      OrdinalIgnoreCase


```
output on linux (ubuntu18.04):
```
caseA   caseB   caseC   caseD   caseE   caseF   comparisonType
0       0       2       0       1       0       CurrentCulture
0       0       2       0       1       0       CurrentCultureIgnoreCase
0       0       2       0       1       0       InvariantCulture
0       0       2       0       1       0       InvariantCultureIgnoreCase
1       1       1       -1      -1      -1      Ordinal
1       1       1       -1      -1      -1      OrdinalIgnoreCase
```
Case A and B show I've been wrong with my statement ```Specifying a string comparison type doesn't help```. could have sworn I tested that.

Case C shows a null character followed by another characater is pointed out at the wrong position

Cases D E F show character sequences being found that aren't present in the string
