### ISSUE TITLE
tracking: Add Fedora 29 (2018-10-23) to CI test coverage

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#32287]
Tracking issue to add CI coverage in late-October/November when Fedora 29 comes out.   Also tracking dropping Fedora 27 once the EOL date is known.

Related https://github.com/dotnet/core-eng/issues/4195

**Comment by danmosemsft** [comment]
Does this include edits similar to https://github.com/dotnet/corefx/pull/32292 (and a backport thereof) @or is there another issue for that?  

cc @leecow

**Comment by wtgodbe** [comment]
@bartonjs is there any update for the status on this one?

**Comment by ericstj** [comment]
Per @safern we are testing in official builds on Fedora 28 and 29, in CI on Fedora 28.
