### ISSUE TITLE
[HTTP/2] Winhttp should open a new HTTP/2 connection when SETTINGS_MAX_CONCURRENT_STREAMS is hit

### ISSUE THREAD

**Issue by nilesh-oswal** [dotnet/corefx#32303]
The following option needs to be consumed and exposed by WinHttpHandler. This was discussed in detail with David Shulman and Matthew Cox.

HTTP/2 serves up multiple requests from the same connection. There is a cap on the number of concurrent requests that can go through 1 HTTP/2 connection, set by SETTINGS_MAX_CONCURRENT_STREAMS. Once this cap is hit, the requests are queued until the number of concurrent requests goes below the limit. There was a request for a Windows change where a new HTTP/2 connection stream is opened when the SETTINGS_MAX_CONCURRENT_STREAMS limit is hit. 

This behavior can be enabled by setting this option with a BOOL set to TRUE:

#define WINHTTP_OPTION_DISABLE_STREAM_QUEUE           139

@davidsh

**Comment by karelz** [comment]
Triage: This goes technically against HTTP/2 RFC which prohibits multiple connections to the same server for this reason.
We don't believe this is widely useful/requested feature and it would complicate the API surface. Closing.
