### ISSUE TITLE
Path.Join with four arguments

### ISSUE THREAD

**Issue by jnm2** [dotnet/corefx#32312]
I wanted to write this:

```cs
Path.Join(assetsDirectory, "objects", hash.AsSpan().Slice(0, 2), hash)
```

This is the workaround:

```cs
Path.Join(assetsDirectory, "objects", Path.Join(hash.AsSpan().Slice(0, 2), hash))
```

`Path.Combine` goes up to four; why is this API different?

### API Summary

We didn't propose a 4 method overload originally as `TryJoin` allowed writing low-allocating versions for 4+ paths.

As we already have the same helper code for both `Combine`/`Join`, there is no reason not to expose the 4 method overloads for `Join`. `TryJoin` isn't as straight-forward and can be composed with multiple calls without extra allocation cost- as such we'll leave at 3 for now.

### API Signature

``` C#
namespace System.IO
{
    public static class Path
    {
        public static string Join(ReadOnlySpan<char> path1, ReadOnlySpan<char> path2, ReadOnlySpan<char> path3, ReadOnlySpan<char> path4);
        public static string Join(string path1, string path2, string path3, string path4);
    }
}
```

**Comment by danmosemsft** [comment]
@JeremyKuhne any objection? It would obviously be easy to add

**Comment by JeremyKuhne** [comment]
It's simply a matter of diminishing returns vs. additional complexity. The idea was that for 4+ you could compose yourself using `TryJoin` if allocation was critical. I'm fine with adding this one as we already have the helper.

https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/IO/Path.cs#L607

**Comment by JeremyKuhne** [comment]
@jbhensley Good point on the string one. I'd rather not do the `TryJoin` unless we really demonstrate a demand for it. It isn't as straight-forward as it might seem at first as it has to not copy data if it can't fit everything.

**Comment by jbhensley** [comment]
Totally your call. Looking at the code for `TryJoin` with three, it doesn't look like it would be too difficult to extend out to four. Don't know if there is any demand, but things feel a bit "off" if `Join` goes to four and `TryJoin` goes to three. Just my personal take.

**Comment by JeremyKuhne** [comment]
It isn't horrible to implement for sure, but I'm trying to be a little cautious by default. We'll see what the API review has to say about it- if the general consensus is to match I'm fine with it.

**Comment by JeremyKuhne** [comment]
@jbhensley sure! @karelz, can you get him set up so we can assign the issue to him?

**Comment by karelz** [comment]
@jbhensley invite sent. Ping us once you accept it - we can then assign it to you.
It will auto-subscribe you to all repo notifications (500+ per day). We recommend to switch repo to Not-Watching which will reduce notifications to just explicit subscriptions, mentions and assignments.

**Comment by jbhensley** [comment]
@karelz Invite accepted

**Comment by jbhensley** [comment]
@karelz @JeremyKuhne Let me know if there is anything else you need me to do. I'm sure this is not a very high priority item.

**Comment by karelz** [comment]
Sorry, I was at MSIgnite, not on email/GitHub.
@JeremyKuhne can you push on the API review next Tuesday please?

**Comment by terrajobst** [comment]
This makes sense to me. We'd match the pattern of `Path.Combine()` which has specialized overloads for up to four arguments as well.

**Comment by terrajobst** [comment]
Looks good.

```C#
namespace System.IO
{
    public static class Path
    {
        public static string Join(ReadOnlySpan<char> path1, ReadOnlySpan<char> path2, ReadOnlySpan<char> path3, ReadOnlySpan<char> path4);
        public static string Join(string path1, string path2, string path3, string path4);

        // For consistency we should also add this one:
        public static string Join(params string[] paths);
    }
}
```

@JeremyKuhne Any objections to adding the params one too? We want people to move from `Path.Combine()` to this one and passing more than four paths seems reasonable. For spans we're out of luck for know, though.

**Comment by JeremyKuhne** [comment]
> Any objections to adding the params one too?

Not really.

**Comment by Anipik** [comment]
@jbhensley can you are planning to take this up ?

**Comment by Anipik** [comment]
Tests and api are both merged.
