### ISSUE TITLE
ECDsaCreate fails on Linux with PlatformNotSupportedException when using OID with only FriendlyName

### ISSUE THREAD

**Issue by veleek** [dotnet/corefx#32323]
If you attempt to create an ECDsa key using .NET Core on Linux but you specify an ECCurve with an OID that only contains a FriendlyName then it fails with a PlatformNotSupportedException.

```
System.PlatformNotSupportedException: The specified curve 'ECDSA_P256' or its parameters are not valid for this platform.
   at Interop.Crypto.EcKeyCreateByKeyParameters(String oid, Byte[] qx, Int32 qxLength, Byte[] qy, Int32 qyLength, Byte[] d, Int32 dLen...
   at Interop.Crypto.EcKeyCreateByKeyParameters(String oid, Byte[] qx, Int32 qxLength, Byte[] qy, Int32 qyLength, Byte[] d, Int32 dLength)
   at System.Security.Cryptography.ECOpenSsl.ImportNamedCurveParameters(ECParameters parameters)
   at System.Security.Cryptography.ECOpenSsl.ImportParameters(ECParameters parameters)
```

The following snippet of code reproduces the issue.  This will succeed when running on Windows but fails when running on Linux.

```csharp
const string name = "ECDSA_P521";
var parameters = ECDsa.Create().ExportParameters(true); // Easy way to get a "working" set of parameters
// "Replace" the curve with essentially the same thing.
parameters.Curve = ECCurve.CreateFromFriendlyName(name);
ECDsa.Create(parameters);
```

The following is a more complete program.  All test cases succeed on Windows, the two indicated test cases fail on Linux.

```csharp
using System;
using System.Runtime.InteropServices;
using System.Security.Cryptography;

using Newtonsoft.Json;

public static class Program
{
    public static void Main(string[] args)
    {
        Console.WriteLine("**Environment**");
        Console.WriteLine($"Platform: .NET Core");
        Console.WriteLine($"OS: {RuntimeInformation.OSDescription}");
        Console.WriteLine();

        const string name = "ECDSA_P521";
        const string value = "1.3.132.0.35";

        var key = ECDsa.Create();

        Test(key, ECCurve.CreateFromFriendlyName(name), "CreateFromFriendlyName"); // Fails on Linux
        Test(key, ECCurve.CreateFromValue(value), "CreateFromValue");
        Test(key, ECCurve.CreateFromOid(Oid.FromFriendlyName(name, OidGroup.EncryptionAlgorithm)), "FromOid(FromFriendlyName)");
        Test(key, ECCurve.CreateFromOid(Oid.FromOidValue(value, OidGroup.EncryptionAlgorithm)), "FromOid(FromValue)");
        Test(key, ECCurve.CreateFromOid(new Oid(value, name)), "FromOid(new Oid(value, name))");
        Test(key, ECCurve.CreateFromOid(new Oid(value, null)), "FromOid(new Oid(value, null))");
        Test(key, ECCurve.CreateFromOid(new Oid(null, name)), "FromOid(new Oid(null, name))"); // Fails on Linux
    }

    private static void Test(ECDsa key, ECCurve curve, string message = null)
    {
        Console.WriteLine("====================");
        Console.WriteLine($"Test: {message}");

        try
        {
            Console.WriteLine(JsonConvert.SerializeObject(curve.Oid, Formatting.Indented));

            var parameters = key.ExportParameters(true);
            parameters.Curve = curve;
            ECDsa.Create(parameters);
            Console.WriteLine("Success :)");
        }
        catch (Exception e)
        {
            Console.WriteLine($"Failed :( {e.Message}");
        }
    }
}
```

**Test Output:**
```
**Environment**
Platform: .NET Core
OS: Linux 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018

====================
Test: CreateFromFriendlyName
{
  "Value": null,
  "FriendlyName": "ECDSA_P521"
}
Failed :( The specified curve 'ECDSA_P521' or its parameters are not valid for this platform.
====================
Test: CreateFromValue
{
  "Value": "1.3.132.0.35",
  "FriendlyName": "ECDSA_P521"
}
Success :)
====================
Test: FromOid(FromFriendlyName)
{
  "Value": "1.3.132.0.35",
  "FriendlyName": "ECDSA_P521"
}
Success :)
====================
Test: FromOid(FromValue)
{
  "Value": "1.3.132.0.35",
  "FriendlyName": "ECDSA_P521"
}
Success :)
====================
Test: FromOid(new Oid(value, name))
{
  "Value": "1.3.132.0.35",
  "FriendlyName": "ECDSA_P521"
}
Success :)
====================
Test: FromOid(new Oid(value, null))
{
  "Value": "1.3.132.0.35",
  "FriendlyName": "ECDSA_P521"
}
Success :)
====================
Test: FromOid(new Oid(null, name))
{
  "Value": null,
  "FriendlyName": "ECDSA_P521"
}
Failed :( The specified curve 'ECDSA_P521' or its parameters are not valid for this platform.
```

**Comment by bartonjs** [comment]
Creating from friendly name is always the riskier option.  ECDSA_P521 _should_ work since that's in the [static lookup table](https://github.com/dotnet/corefx/blob/45b5cf0949470104d38a68d7f9ca0ad381393707/src/System.Security.Cryptography.Encoding/src/Internal/Cryptography/OidLookup.cs#L154)

**Comment by veleek** [comment]
Yeah, not saying that it's the best option, just pointing out that be behavior is different between Linux and Windows.  

I think that the biggest issues is the fact that `ECCurve.CreateFromFriendlyName(name)` fails, but `ECCurve.CreateFromOid(Oid.FromFriendlyName(name, OidGroup.All))` works.

**Comment by vcsjones** [comment]
The gist of the issue is when `ECCurve.CreateFromFriendlyName` is called, `null` is explicitly passed in for the OIDs value:

https://github.com/dotnet/corefx/blob/6322a406f88e854c5b827ab838f988f8992048f8/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/ECCurve.cs#L120

https://github.com/dotnet/corefx/blob/6322a406f88e854c5b827ab838f988f8992048f8/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/ECCurve.cs#L143-L145

Because of this behavior, the lookup table is to construct the OIDs value is ignored - it just assigns the value and friendly name and moves on.

The issue is actually more with how EcDsa copes with no value in the OID. CNG (Windows) is capable of creating this curve when importing the parameters because, well, Windows understands the Windows names. However this friendly name ultimately gets passed to `OBJ_txt2nid` at OpenSSL and it doesn't know what to do with the Windows' friendly for the curve.

This _does_ work with Linux (and does not on Windows):

```
const string name = "secp521r1";
var parameters = ECDsa.Create().ExportParameters(true);
parameters.Curve = ECCurve.CreateFromFriendlyName(name);
Console.WriteLine(parameters.Curve.IsNamed);
ECDsa.Create(parameters);
```

So, that's what's happening. As far as perhaps improving the experience, perhaps `CreateFromValueAndName` on `ECCurve` could be changed to:

```csharp
return ECCurve.Create(new Oid(oidValue ?? oidFriendlyName));
```

This will use the `Oid` constructor that will go through the lookup table.

**Comment by bartonjs** [comment]
@vcsjones I feel like somewhere in the codepath ECDsa.Create (and ECDiffieHellman.Create) for Linux or macOS _should_ be noticing that Oid.Value is `null` and doing the lookup dynamically.

The problem is that on Windows the friendly name -> OID or OID -> friendly name lookup can end up being expensive (cascading out to Active Directory when configured to do so).

**Comment by vcsjones** [comment]
@bartonjs 

> I feel like somewhere in the codepath ECDsa.Create (and ECDiffieHellman.Create) for Linux or macOS should be noticing that Oid.Value is null and doing the lookup dynamically.

Hm. I'll step through it again and see if I missed that (though I suppose if it were there then we wouldn't have this problem?)

>The problem is that on Windows the friendly name -> OID or OID -> friendly name lookup can end up being expensive (cascading out to Active Directory when configured to do so).

Oh `CryptFindOIDInfo` yeah I've written that performance bug before.

**Comment by bartonjs** [comment]
Well, something somewhere notices that you did ECDsa.Create(ECCurve.NamedCurves.secp256r1)), which has the no-value-but-has-a-name.  I think :)

**Comment by vcsjones** [comment]
>Well, something somewhere notices that you did ECDsa.Create(ECCurve.NamedCurves.secp256r1)), which has the no-value-but-has-a-name.

I don't think so.. When I did `ECCurve.CreateFromFriendlyName("secp521r1");` it make it all the way to the native C PAL as-is but `OBJ_txt2nid` handles that name:

https://github.com/dotnet/corefx/blob/a13789324692ffa1f8c42c1da34c2c1de2103ba7/src/Native/Unix/System.Security.Cryptography.Native/pal_ecc_import_export.c#L336-L337

The parameter to `OBJ_txt2nid` will be something like `Oid.Value ?? Oid.FriendlyName`.
