### ISSUE TITLE
Problem serializing/deserializing using System.Runtime.Serialization.NetDataContractSerializer AND WindowsUpdate KB4457128 / KB4457131

### ISSUE THREAD

**Issue by MobAtNti** [dotnet/corefx#32335]
Hello

This issue is a re-appearence of issue #30415.
Please look at issue 30415 for additional info.
(Could not re-open issue, therefor a new one)

Now the new problem :
This problem (serializing a dictionary object using System.Runtime.Serialization.NetDataContractSerializer with a stringComparer, it's not possible to deserialize the stream.) disappeared when applying MS update KB4284880 (June 12, 2018).

But now the problem has reemerged. A Win2016 server has been updated with KB4457131 (September 11, 2018) and now the serializing culture compability problem is back.

Applying KB4457128 (September 11, 2018) to client workstation, fixes this issue again.

It's a big problem for us, that the serializing functions keeps changing and breaking compability. We have dosens of servers and unknown numbers of clients who are affected.

And we can't even fix the problem ourselfs :-(. 
If client A applies KB4457128, to a workstation, it breaks serializing culture compability. If we then, as a respond, applies KB4457131 to the server, all other clients without KB4457128, will now suffer from this problem with serializing

To us it looks like that the bug was fixed in KB4284880, but now has been introduced again in KB4457128 / KB4457131

Please take a look at this matter.

kind regards

**Comment by karelz** [comment]
Closing as it has been asnwered by @tarekgh on the original issue - https://github.com/dotnet/corefx/issues/30415#issuecomment-422461035

Note that .NET Framework bugs are not tracked on GitHub - see our [main page](https://github.com/dotnet/corefx#how-to-engage-contribute-and-provide-feedback).
