### ISSUE TITLE
ArrayRange

### ISSUE THREAD

**Issue by moien007** [dotnet/corefx#32345]
In most cases ArrayPool returns an array that its length is bigger than the requested length.
So we usually use ArraySegment but its Offset field is unneeded. So having ArrayRange will be nice.

It already implemented here: https://github.com/aspnet/Blazor/blob/master/src/Microsoft.AspNetCore.Blazor/RenderTree/ArrayRange.cs

**Comment by gfoidl** [comment]
Do `Memory<T>` / `Span<T>` not suffice?

**Comment by moien007** [comment]
ArrayRange is less complex than `Memory<T>` and `Span<T>`. Also `Memory<T>` contains `_index` which is (if I'am not wrong) same as `ArraySegment<T>.Offset `.

**Comment by svick** [comment]
>  its Offset field is unneeded

>  `Memory<T>` contains `_index`

Why is that an issue?

**Comment by moien007** [comment]
> Why is that an issue?

If we use `Memory<T>` with `ArrayPool<T>`, `_index `is always zero, isn't it ?
Only difference between `ArrayRange` and `ArraySegment<T>` or `Memory<T> `is `Offset` or `_index` removal which makes less stack copy.

**Comment by moien007** [comment]
> In that case, do you have a benchmark that shows a realistic scenario (i.e. not a microbenchmark), where using `ArrayRange` would significantly improve performance?
> 
> In other words: if you want to introduce a new API whose sole reason for existing is improved performance, I think you should first show that it actually improves performance.

I don't think `ArrayRange` give a significant performance improvement, so I'm convinced.
