### ISSUE TITLE
Unicode path results into path too long error

### ISSUE THREAD

**Issue by fhsdfuihisfg** [dotnet/corefx#32347]
I was using powershell get-childitem command and encounter path too long error when reading a path contains unicode. I was told it is a CoreFX limitation so I come here to report. 

The filename itself in unicode is under the 260 limit, but after passing it into a online unicode converter, the converted path is actually longer than 260 characters, which makes powershell reports path too long error.

I think it is confusing that the file is allowed to save into disk in the first place(which appears to pass the 260 limit), and then turn out incompatible with powershell command. Please explain how does CoreFX handle unicode path name. Thanks.

**Comment by jkotas** [comment]
Powershell issue: https://github.com/PowerShell/PowerShell/issues/7809

**Comment by JeremyKuhne** [comment]
Thanks @jkotas 

@fhsdfuihisfg The limit is not 260 for file names. No filesystem supports greater than 255 code units. For Windows this is UTF-16. For Unix it is 255 _bytes_ of anything, but that is usually treated as 255 bytes of UTF-8. Given the way UTF-8 works that means you can have a _maximum_ of 255 characters (if all of your characters are at code points 127 and below (e.g. ASCII)).

260 is the legacy limit for the _full_ path in Windows (`MAX_PATH`). All current versions of Windows support much longer paths than that, but most require special syntax that CoreFX implicitly takes care of for you.

**Comment by fhsdfuihisfg** [comment]
Sorry, forgot to mention.
The problem happens on ubuntu18.04 lts server with powershell core 6.1
When I use powershell 5.1 in win7, there is no unicode path too long problem.

**Comment by JeremyKuhne** [comment]
> I think the problem is in linux handling unicode filename differently than windows does. I can access that file in win7 with powershell 5.1 without problem.

Without seeing an actual string involved you likely have characters that require more than one byte to encode in UTF-8 (something non-ASCII).

> Thank you for the explanation on code point and sorry for wasting your time as the error is not related to CoreFx or powershell at all.

You're welcome. It isn't a waste- paths are filled with hidden complexity. I'll look to see that we have this written up in the docs.
