### ISSUE TITLE
.net core 2.2 upgrade issue

### ISSUE THREAD

**Issue by MSAppsDev** [dotnet/corefx#32340]
I am trying to upgrade my .net core 2.1 solution to 2.2 preview 2. I have installed 2.2 preview 2 sdk and changed the target framework to 2.2 through project properties but getting below error when i build the solution.
This version of Microsoft.AspNetCore.All is only compatible with the netcoreapp2.1 target framework. Please target netcoreapp2.1 or choose a version of Microsoft.AspNetCore.All compatible with .netcoreapp2.2

Do i need to install any other packages/libraries? I dont see Microsoft.AspNetCore.All 2.2 version anywhere.

**Comment by karelz** [comment]
@Eilon can you help here?
I thought that Microsoft.AspNetCore.All package was discontinued even in 2.1 ... maybe it happened just now?
Here's official docs: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage?view=aspnetcore-2.1

**Comment by Eilon** [comment]
@MSAppsDev can you show what your CSPROJ looks like?

The `Microsoft.AspNetCore.All` package continues to exist in 2.x, but will not be supported in 3.0 at all. Though, we do recommend people be prepared and use `Microsoft.AspNetCore.App` instead.

**Comment by MSAppsDev** [comment]
Hi,
this issue is with my webapi, below is my csproj file.

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
    <IsPackable>false</IsPackable>
    <SpaRoot>ClientApp\</SpaRoot>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(SpaRoot)node_modules\**</DefaultItemExcludes>

    
    <BuildServerSideRenderer>false</BuildServerSideRenderer>
  </PropertyGroup>

  <PropertyGroup>
    <DocumentationFile>bin\$(Configuration)\netcoreapp2.0\TestApp.Web.xml</DocumentationFile>
    <UserSecretsId>1277dd12-6e7e-4f11-8ffd-880569aff6ee</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="2.1.1" />
    <PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.AzureKeyVault" Version="2.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    
    <Content Remove="$(SpaRoot)**" />
    <None Include="$(SpaRoot)**" Exclude="$(SpaRoot)node_modules\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Business\TestApp.Business.csproj" />
    <ProjectReference Include="..\Entities\TestApp.Entities.csproj" />
    <ProjectReference Include="..\Reports\TestApp.Reports.csproj" />
  </ItemGroup>

  <Target Name="DebugEnsureNodeEnv" BeforeTargets="Build" Condition=" '$(Configuration)' == 'Debug' And !Exists('$(SpaRoot)node_modules') ">
    
    <Exec Command="node --version" ContinueOnError="true">
      <Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
    </Exec>
    <Error Condition="'$(ErrorCode)' != '0'" Text="Node.js is required to build and run this project. To continue, please install Node.js from https://nodejs.org/, and then restart your command prompt or IDE." />
    <Message Importance="high" Text="Restoring dependencies using 'npm'. This may take several minutes..." />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
  </Target>

  <Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
    
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build -- --prod" />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build:ssr -- --prod" Condition=" '$(BuildServerSideRenderer)' == 'true' " />

    
    <ItemGroup>
      <DistFiles Include="$(SpaRoot)dist\**; $(SpaRoot)dist-server\**" />
      <DistFiles Include="$(SpaRoot)node_modules\**" Condition="'$(BuildServerSideRenderer)' == 'true'" />
      <ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
        <RelativePath>%(DistFiles.Identity)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>

</Project>
 

I have other class libraries (Business, Reports,Data) building fine with core 2.2 and are referred in my webapi. In my Class libraries under dependencies i see Microsoft.NetCore.App (2.2 preview), attached screen shot below.

![image](https://user-images.githubusercontent.com/36544072/45754613-17276800-bbea-11e8-8e73-b62e9adb8dea.png)

Below is my webapi dependencies.
![image](https://user-images.githubusercontent.com/36544072/45754950-0aefda80-bbeb-11e8-9cdf-3be7d11fa81f.png)

Please let me know whats wrong here.

Thanks,

**Comment by Eilon** [comment]
In this section of the CSPROJ:

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="2.1.1" />
    <PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.AzureKeyVault" Version="2.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="3.0.0" />
  </ItemGroup>
```

It looks like there's a mix of ASP.NET Core versions. All the stuff that is actually part of ASP.NET Core should be 2.2.x.

In particular:

```xml
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.3" />
```

Should change from `.All` to `.App`, and remove the version:

```xml
    <PackageReference Include="Microsoft.AspNetCore.App" />
```

You can remove this:
```xml
    <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="2.1.1" />
```

And you can change the version of `Microsoft.VisualStudio.Web.CodeGeneration.Design` to `2.2.0-preview2-35157`.

After you do this, you might still be missing some package references, but you'll just need to install those manually, because the `.App` package has less in it than `.All` did. If you still have issues with that and can't figure it out, please log a new issue at https://github.com/aspnet/Home/issues.

**Comment by MSAppsDev** [comment]
@Eilon,
Thanks for the information. I am able to fix the issue by removing Microsoft.AspNetCore.All from the project and added Microsoft.AspNetCore.App and some  ore libraries such as Microsoft.AspNetCore.Mvc, Microsoft.AspNetCore.Authntication.Jwtbearer etc.

**Comment by Eilon** [comment]
Great!
