### ISSUE TITLE
SSL certificate locations on Linux  & DotNet supported certificate formats

### ISSUE THREAD

**Issue by Praveen-Rai** [dotnet/corefx#32367]
Dotnet presently is using User Home directory to store and read x509 Certificates, but in Linux each distribution has a standard directory to store the certificates. As per discussion [ here ](https://github.com/aspnet/KestrelHttpServer/issues/2902#issuecomment-4228537932), it seems like we've carried forward the .Net Certificate Store concepts. This isn't aligned with Linux way of working with SSL certificates and causes issues. Please update the dotnet installer and .Net Certificate Store apis to load the certificates according to the distribution.

Secondly, seems like PEM (*.crt & *.pem) is the de facto format for SSL certificates, whereas .Net Core seems to support PKCS12 ( *.pfx ) only. This forces the admin to convert the certificates to PKCS12 using OpenSSL. Can we please add inbuild support for PEM as well ?

**Comment by bartonjs** [comment]
> Dotnet presently is using User Home directory to store and read x509 Certificates, but in Linux each distribution has a standard directory to store the certificates

The home directory is used for CurrentUser-based certificate stores.

While there is an easy to follow (because there's an API for it) convention on the various distros for reading the root trust list, there's not a universal or programmatic answer for where "system-level" end-entity certificates go (which is why LocalMachine\My throws PlatformNotSupportedException.

> Secondly, seems like PEM (*.crt & *.pem) is the de facto format for SSL certificates, whereas .Net Core seems to support PKCS12 ( *.pfx ) only.

If you mean for the CurrentUser\My directory, we do not support directly reading from or writing to that directory; only reads and writes used by the X509Store API are supported.  (In particular, rogue writes can put the store in complicated broken states)

If you mean "how do I have a separate .key and .cer file and bring them together?", that functionality exists in master now.  (In particular, the ability to read the raw key file is new in master; if you could figure out how to load the key they could already be mated at runtime via `cert.CopyWithPrivateKey`.)

If there's a specific point that isn't addressed already, let me know.

**Comment by Praveen-Rai** [comment]
@bartonjs 

> The home directory is used for CurrentUser-based certificate stores.
While there is an easy to follow (because there's an API for it) convention on the various distros for reading the root trust list, there's not a universal or programmatic answer for where "system-level" end-entity certificates go (which is why LocalMachine\My throws PlatformNotSupportedException.

From what i understand you mean to say there isn't a particular location in Linux to store "user-level" & "system-level" certificates. I accept that, particularly for "user-level" certificate store. But, there seems to be a general consensus for a particular directory in each distro to store certificates. Below is a list i got from [Serverfault](https://serverfault.com/a/722646)

`"/etc/ssl/certs/ca-certificates.crt",                // Debian/Ubuntu/Gentoo etc.
"/etc/pki/tls/certs/ca-bundle.crt",                  // Fedora/RHEL 6
"/etc/ssl/ca-bundle.pem",                            // OpenSUSE
"/etc/pki/tls/cacert.pem",                           // OpenELEC
"/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem", // CentOS/RHEL 7`

If there isn't any user-level certificate store in Linux, in my opinion we shouldn't even try for "user-level" certificates on Linux. For e.g. when dotnet is installed by user User1 on ubuntu, the development certificate is created at _/home/User1/.dotnet/corefx/cryptography/x509stores/my_ . Here are concerns with this : 

- It isn't the known location to many of the Linux people. As far as i can understand, this is replicate the Windows Cert Store concept. But, in my opinion that isn't required as unlike, Windows one won't be able to load a certificate using Store Name and Subject.

- Other accounts cannot access the user path. For e.g. the 'www-data' account which is used popularly by web-servers. Which means if i've to run the web app using SSL, i must run it using the Current Account. Please refer : [Issue on KestrelHTTPServer](https://github.com/aspnet/KestrelHttpServer/issues/2902#issuecomment-422720969)

So, basically i am suggesting to create/read certificate only from preferred location in Linux distro. For e.g. "/etc/ssl/certs/" for Ubuntu.

> If you mean "how do I have a separate .key and .cer file and bring them together?", that functionality exists in master now. (In particular, the ability to read the raw key file is new in master; if you could figure out how to load the key they could already be mated at runtime via cert.CopyWithPrivateKey.)

Yes, i meant having .key & .cer file separately, as i could see most of them this way on Ubuntu. It's great to know that now it exists on master. Presently Kestrel Config supports specifying the certificate using Store-Name and Path-Password format only ( [Doc Reference](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.1#endpoint-configuration) ). Will Kestrel now support CertificatePath-KeyPath automatically, or Kestrel source needs changes to support it ?

**Comment by bartonjs** [comment]
The various paths you listed are the root trust lists.

> If there isn't any user-level certificate store in Linux, in my opinion we shouldn't even try for "user-level" certificates on Linux. 

While it's not a standard thing on Linux, it is a well known thing in .NET.  It's a balancing act.  Similarly, Java has Java Key Stores on Linux.  JKS a Java concept, not a Linux one.  (And if we turned off X509Store now, it'd really surprise people who used it in .NET Core 1.0, 1.1, 2.0, 2.1, and 2.2 that it doesn't work in 3.0)

> Will Kestrel now support CertificatePath-KeyPath automatically, or Kestrel source needs changes to support it ?

Kestrel would need to do work.

**Comment by Praveen-Rai** [comment]
@bartonjs Thanks for the clarifications !! I need to think a bit to process the information that you've shared. I'm developing a MVC App on windows, and testing it on a Ubuntu server. I access the server using SSH, and hence if i just use dotnet command to run the application it automatically shuts down when my SSH connection is closed. To overcome that i've created a service and used 'www-data' and finally landed here. It took me a while to learn about the certificate store, format and Kestrel endpoint settings. And that's the concern i really have. 

One quick question, isn't the directory of root trust lists, the one to store all the certificates for the system ?

> Kestrel would need to do work.

@javiercn , @Tratcher Can you please look into this ?

**Comment by bartonjs** [comment]
>  isn't the directory of root trust lists, the one to store all the certificates for the system ?

No, just the root trust.  Certbot (Let's Encrypt) puts the certificates it manages under /etc/letsencrypt/live.  qmail wants a cert+key multi-PEM at /var/qmail/control/servercert.pem.  Dovecot's default is a multi-PEM at /etc/dovecot/dovecot.pem.

The only real convention for application certificates is that there's no convention :smile:.

**Comment by Praveen-Rai** [comment]
> The only real convention for application certificates is that there's no convention 😄.

@bartonjs Okay 😃   !! So the only way we have in dotnet is to configure it to pick the certificate from the right location ( decided by the creator of certificate, e.g. Let's Encrypt ). Please correct me if i am wrong.

But for dotnet development certificate why not we utilize /etc/ or /var/ directory which is accessible to all users ?

**Comment by bartonjs** [comment]
Those directories are (usually) readable by all users, but not writable.  So you'd need to be root to create an application.  Also, for other multi-process/multi-hosting scenarios you want the cert to go to a directory named for the consuming application, which we don't really know.
