### ISSUE TITLE
System.Net.Sockets ,Version=0.0.0.0  in net 4.6.1 environment.

### ISSUE THREAD

**Issue by RaghavKumar** [dotnet/corefx#32364]
The application is built for in net 4.6.1 .It uses a nugget package built on the .net standard 2.0 with makes use of another nugget package using the System.net.sockets ,ver 4.3.2.
The fusion log indicates failure to resolve System.Net.Sockets ,Version=0.0.0.0 .
The way the system is built , Its not possible to use app.config file.

1.The consuming application of the nugget package if it set to .net core environment, the issue is not observed.
2. The nugget package source ,instead of a library if it run as a executable set to .net 4.6.1 the problem is not observed.
3.In the systems where Visual Studio development environment and nuget environment is set ,the fusion log does indicate run time loading of the System.Net.Sockets .
It is observed only in the test systems (windows 2012 R2 s and with Visual Studio run times)

**Comment by karelz** [comment]
@RaghavKumar can you please provide a (minimal) repro? (steps how to run into the problem, ideally creating app from scratch)
cc @joperezr

**Comment by joperezr** [comment]
if you target .NET 4.6.1 and want to consume .NET Standard 2.0 components, then we require Binding redirects. Our build engine should be injecting some (provided that you selected the auto-generate binding redirects option) in order to make things work. Why isn't app.config file an option? In case you really want to avoid using binding redirects, then you should target .NET 4.7.2 since that won't require any binding redirects and things will just work.

**Comment by RaghavKumar** [comment]
> if you target .NET 4.6.1 and want to consume .NET Standard 2.0 components, then we require Binding redirects. Our build engine should be injecting some (provided that you selected the auto-generate binding redirects option) in order to make things work. Why isn't app.config file an option? In case you really want to avoid using binding redirects, then you should target .NET 4.7.2 since that won't require any binding redirects and things will just work.

The System is a combination of the C++ and managed code , and C++ binaries consume  the managed code (targeted to 4.6.1) through CLI channel .(the hierarchy of the code as down below)

C++
    CLI/CLR libraries
         .NET 461 libraries
             .NET 461 libraries consuming (xylib targeted to .net standard 2.0  and net46 )
                         xylib (the manifest indicates one of the nuget packages uses the System.Net.TCP  4.3.2 version)

not sure if the binding redirection can be done through app.config or another way in this scenario.

**Comment by RaghavKumar** [comment]
> @RaghavKumar can you please provide a (minimal) repro? (steps how to run into the problem, ideally creating app from scratch)
> cc @joperezr

Some of observations to this problem.

1.This problem has been observed only when the consuming assembly of the initial nuget package (with System.Net.Sockets) is made as a nuget package to be used in another library.
2.Ideally using the .net core application environment ,this problem has not been observed.
Just for test and observation running the consuming assembly  as a executable(target .net 4.6.1) also works fine.
3.This problem is observed only in clean machines , and never a issue on the development machines.
4.Interestingly the developer machine fusion logs does not show any indication of this System.Net.Sockets 
5.On test machines the fusion log shows the following assemblies version to 0.0.0.0
System.Core
System. Version
System.Net.Sockets

and the following assemblies retarget to 4.0.0.0
System.Core
System. Version

System.Net.Sockets  is not retargeted.

**Comment by karelz** [comment]
@RaghavKumar did you close the issue on purpose?

If you still seek guidance, then I would recommend (given the complexity of your app) to isolate it into minimal repro (simulate the components you have with HelloWorld-style components, then try to eliminate as many as you can entirely).
