### ISSUE TITLE
base64 encoding with simd-support

### ISSUE THREAD

**Issue by gfoidl** [dotnet/corefx#32365]
I've prototyped base64 encoding with SSE2 / SSSE3 support [here](https://github.com/gfoidl/Base64Test/blob/d7df2359915b08f353912941d66eb115dd195d63/perf/Base64NetBenchmarks/Implementations/Sse2.cs). 
The input, that can't be processed via simd, is handled with the current default encoded.

Numbers look quite promising:

|    Method |    N |        Mean |     Error |    StdDev | Scaled | ScaledSD |
|---------- |----- |------------:|----------:|----------:|-------:|---------:|
|   **Default** |   **16** |    **39.04 ns** | **0.7766 ns** | **0.6884 ns** |   **1.00** |     **0.00** |
| Simd_Sse2 |   16 |    30.03 ns | 0.4058 ns | 0.3168 ns |   0.77 |     0.02 |
|           |      |             |           |           |        |          |
|   **Default** | **1000** | **1,072.48 ns** | **8.5875 ns** | **8.0327 ns** |   **1.00** |     **0.00** |
| Simd_Sse2 | 1000 |   497.02 ns | 4.4778 ns | 4.1886 ns |   0.46 |     0.01 |

The code is based and inspired on https://github.com/aklomp/base64 wich is licensed under [BSD 2-Clause "Simplified" License](https://github.com/aklomp/base64/blob/master/LICENSE). So can this code be used here in corefx under the terms of the license?

Should I pursue this approach and finally submit a PR?

An AVX2 variant was also prototyped, but some intrinsics like `PermuteVar8x32` are WIP, so AVX2 wasn't pursued further, but it can be on the landscape too.

In my prototype right now there is only encoding. But for decoding Klomp has code too, so it could be incorporated, so that both encoding and decoding could be done with simd-support.

This is somewhat tracked in https://github.com/dotnet/coreclr/issues/15506#issuecomment-351498311

/cc: @ahsonkhan

**Comment by danmosemsft** [comment]
@tannergooding

**Comment by tannergooding** [comment]
Implementation looks good. It might be nice to wait on taking this (if we do) until after we finish the API cleanup for the HWIntrinsics (some design decisions were made at the last API review, that we need to respond to).

**Comment by gfoidl** [comment]
@tannergooding thanks. So let's wait for the cleanup, then we can come back to productize this.

**Comment by gfoidl** [comment]
FYI in the WIP-project https://github.com/gfoidl/Base64 SSSE3 / AVX2 is used for encoding / decoding, and [speedups for encoding](https://github.com/gfoidl/Base64/blob/e24072fb3da39992d6cf3d3a496ad32f41abd9d9/perf/gfoidl.Base64.Benchmarks/results/EncodeUtf8Benchmark-report.md) up to 12 are possible (for datalength=1000). For [decoding](https://github.com/gfoidl/Base64/blob/e24072fb3da39992d6cf3d3a496ad32f41abd9d9/perf/gfoidl.Base64.Benchmarks/results/DecodeUtf8Benchmark-report.md) ~6x speedup is possbile (has to check for invalid inputs).

Although this project now exists, I still would like to take this here*, so that corefx can benefit from these improvements in base64 encoding / decoding. 

The project also supports `char`-buffers as sink / source, and base64Url encoding, so I see no "conflict" with an implementation here in corefx.

\* still aware of https://github.com/dotnet/corefx/issues/32365#issuecomment-423257658 as this comment should just be an informational note, not to produce any pressure / hurry... (especially for myself :wink:)
