### ISSUE TITLE
VS offline layout stalled at 97.55%

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/corefx#32397]
I don't know if there is a better repo in order to report this issue. The precise message when the offline layout stalls:

```
Layout progress: 97.55% Running 'D:\vs2017\enterprise\15.8.28010.2036\install\vs.emulator.android.bundle,version=1.1.1207.2,chip=x64\vs_emulatorsetup.exe' with parameters: /quiet /layout "D:\vs2017\enterprise\15.8.28010.2036\install\vs.emulator.android.bundle,version=1.1.1207.2,chip=x64"
```

This seems to be happening whether I am downloading the Enterprise or the Professional layouts. I have two instances of ``vs_emulatorsetup`` running at the time it stalls.

**Comment by karelz** [comment]
Please report your problem here: https://developercommunity.visualstudio.com/spaces/8/index.html
