### ISSUE TITLE
Feature Request - Support Dataset/DataTable/DataView Support INotifyPropertyChanged/INotifyCollectionChanged Interface

### ISSUE THREAD

**Issue by PremSha20** [dotnet/corefx#32396]
Support Dataset/DataTable/DataView Support INotifyPropertyChanged/INotifyCollectionChanged Interface
it will useful in WPF when datatable is binded with view

**Comment by karelz** [comment]
Some are available on .NET Core 2.0:
* DataSet - https://apisof.net/catalog/System.Data.DataSet
* DataTable - https://apisof.net/catalog/System.Data.DataTable
* DataView - https://apisof.net/catalog/System.Data.DataView
And some even on .NET Core 1.0:
* INotifyPropertyChanged - https://apisof.net/catalog/System.ComponentModel.INotifyPropertyChanged
* INotifyCollectionChanged - https://apisof.net/catalog/System.Collections.Specialized.INotifyCollectionChanged
