### ISSUE TITLE
Default HttpRequestMessage.Version 

### ISSUE THREAD

**Issue by grinay** [dotnet/corefx#32409]
You wrote in documentation
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httprequestmessage.version?view=netcore-2.1#System_Net_Http_HttpRequestMessage_Version
that default protocol is 1.1 - and this is should be by default  i agree.
But in your source code https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpUtilities.cs
Default version is actually 2. Please set it to 1.1 or fix the doc. Don't confuse people.

**Comment by filipnavara** [comment]
The source you pointed to refers to .NET Core 3.0. The documentation is for version 2.1. It changed since version 2.1 was released and the documentation is accurate for what version 2.1 does.

**Comment by davidsh** [comment]
The documentation will be updated when .NET Core 3.0 ships.

**Comment by stephentoub** [comment]
> The documentation will be updated when .NET Core 3.0 ships.

@davidsh, the aforementioned change is in 2.1:
https://github.com/dotnet/corefx/blob/release/2.1/src/System.Net.Http/src/System/Net/Http/HttpUtilities.cs#L17

**Comment by davidsh** [comment]
>

Yes, you're correct.  As of .NET Core 2.1, `HttpRequestMessage.Version` default value is 2.1.

I will submit a documentation PR to get this updated.

**Comment by davidsh** [comment]
Closing this issue since the documentation PR has been submitted and merged.
