### ISSUE TITLE
Average with linq on big collection

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#32414]
@bdhamelicodra commented on [Thu Sep 20 2018](https://github.com/dotnet/core/issues/1951)

On a big array, the method "System.Linq.Enumerable.Average(this IEnumerable<long> source)" (in .Net Core 2.1) throw the exception "OverflowException: Arithmetic operation resulted in an overflow.".
Why not use an algorithm that can prevent this, like :
```
double Average(this IEnumerable<long> source) {
double avg = 0;
int t = 1;
foreach (long x in source) {
avg += (((double)x) - avg) / ((double)t);
t += 1;
}
return avg;
}
```​

---

@MarcoRossignoli commented on [Thu Sep 20 2018](https://github.com/dotnet/core/issues/1951#issuecomment-423157601)

better move to https://github.com/dotnet/corefx/issues where https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Average.cs#L77 lives

**Comment by Clockwork-Muse** [comment]
Hmmm....
[This post](https://math.stackexchange.com/questions/106700/incremental-averageing) suggests there are cumulative errors accrued when using this method.  However, I don't know what they are, or whether the error would be acceptable.


What might be of larger concern is that, after a certain point, [the precision of floating point itself is going to interfere](https://stackoverflow.com/questions/31339995/how-big-of-a-number-can-you-store-in-double-and-float-in-c).  For instance:
```csharp
double mantissa_limit = 9007199254740992L;
// Prints out 9007199254740992
Console.WriteLine($"{mantissa_limit + 1.0:R}");
```
...So weird stuff starts to happen:
```csharp
long mantissa_limit = 9007199254740992L;
long sum = mantissa_limit;
for (long count = mantissa_limit; count < long.MaxValue; count++)
{
    sum += 1;
}
// should eventually print out 1.0009775171065493645053545430474
Console.WriteLine($"{((double)sum) / (1 + (int.MaxValue - mantissa_limit)):R}");
```
versus:
```chsarplong mantissa_limit = 9007199254740992L;
double sum = mantissa_limit;
for (long count = mantissa_limit; count < long.MaxValue; count++)
{
    sum += 1.0;
}
// should eventually print out 0.00097751710654936461
Console.WriteLine($"{((double)sum) / (1 + (int.MaxValue - mantissa_limit)):R}");
```
...which is a big difference!

**Comment by stephentoub** [comment]
The question appears to have been answered.  Closing. Thanks.
