### ISSUE TITLE
Exporting a X509Certificate2 produces a certificate not usable by IIS centralized certificate store

### ISSUE THREAD

**Issue by glatzert** [dotnet/corefx#32428]
I wrote an ACME v2 compatible PowerShell module for .NET Core and .NET Full (472).
The module Imports a certificate from LetsEncrypt, combines it with it's private key (stored locally) and Exports the result like this:

```
$certificate = [System.Security.Cryptography.X509Certificates.X509Certificate2]::new($acmeCertificate);
$certifiate = [System.Security.Cryptography.X509Certificates.RSACertificateExtensions]::CopyWithPrivateKey($certificate, $privateKey);
return $certifiate.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Pkcs12);
```

$acmeCertificate is the certificate as submitted by an ACME certificateUrl request and $privateKey is the RSAAlgorithm-Instance used to create the CSR earlier in the process.
I can Import the certificate into the Windows Certificate Store and it will work well with IIS.

When I try to use the certificate from IIS Centralized Certificate Store, it'll pickup the file and it's Name, but it'll fail to be loaded with an error stating "Cannot find the file".
Importing and then exporting the certificate through MMC or Import/Export-PFXCertificate will fix the issue.

So whatever the PKCS12 Export (and PFX as well) are doing with the certificate - it seems not to be "correct" - or at least it seems to diverge from a Standard which IIS is assuming.

I'm aware that this issue is spanning multiple products and might be rooted in either, but I hope you can dispatch the relevant processes to sort this out.

**Comment by bartonjs** [comment]
@glatzert I'm not sure what you mean by "IIS Centralized Certificate Store".

If you're importing the certificate into a LocalMachine certificate store you need to ensure that the private key lives in a machine context (vs a user context).  If you're using .NET/PowerShell to add the certificate to the store then if you're opening it from the exported PFX you need to assert `X509KeyStorageFlags.MachineKeySet` (and should assert `X509KeyStorageFlags.PersistKeySet` when opening a PFX to save it into a persisted store).

If that isn't the missing link, I'd need more information on how to help from here.

**Comment by glatzert** [comment]
The IIS CCS is a file based solution to manage certificates in IIS.
Essentially it's "put your pfx in a folder, name them by FQDN.pfx and IIS will pick them up, if needed."

The StoreFlags _might_ be the missing link, but that's not actionable for me, since the module should be x-plat and X509-Store with machine key set seems very windows-only (as is MMC and Import/Export-PFXCertificate via Powershell).
Besides that, the Export-Method of X509Cert2 (which creates the pfx as `byte[]`, https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate.export?view=netframework-4.7.2) does not have any switches (or I'm not able to locate them) allowing me to use these flags.

**Comment by glatzert** [comment]
This seems not to apply to IIS 2019 anymore, so I personally have no interest in this issue anymore
