### ISSUE TITLE
Concurrentqueue Performance Issues

### ISSUE THREAD

**Issue by DrDao** [dotnet/corefx#32426]
I used some of the concurrentqueue to save the request, and when I measured it, I found that TPS dropped from 17000 to 3000.
When the test cycle was added to 50000, the Concurrentqueue had taken 1 points.
In applications where high throughput is required, concurrentqueue cannot be used at all.

![tim 20180924125445](https://user-images.githubusercontent.com/11530204/45948659-7989c980-c02b-11e8-8a21-03acb2e8483d.jpg)
![tim 20180924125456](https://user-images.githubusercontent.com/11530204/45948660-7989c980-c02b-11e8-978e-40c40fbc14da.jpg)
![tim 20180924125504](https://user-images.githubusercontent.com/11530204/45948661-7a226000-c02b-11e8-8f01-076dbb9f380c.jpg)
![tim 20180924125702](https://user-images.githubusercontent.com/11530204/45948689-932b1100-c02b-11e8-9582-9a8e3ef853d4.jpg)
![tim 20180924125712](https://user-images.githubusercontent.com/11530204/45948690-932b1100-c02b-11e8-9d36-0b318a508fbc.jpg)

Performance is similar to single write
https://user-images.githubusercontent.com/11530204/45938130-6f4ed780-bff9-11e8-8e96-aa7dfee86272.jpg

**Comment by DrDao** [comment]
The problem does not exist in the. Net Framework Environment

**Comment by ViktorHofer** [comment]
Please see @MarcoRossignoli's response: https://github.com/dotnet/coreclr/issues/20110#issuecomment-423923791

**Comment by MarcoRossignoli** [comment]
FYI @DrDao i did some tests with `.Net Framework Environment`(Clr) and i see similar drift.
``` ini

BenchmarkDotNet=v0.11.1, OS=Windows 10.0.17134.285 (1803/April2018Update/Redstone4)
Intel Core i7 CPU 860 2.80GHz (Nehalem), 1 CPU, 8 logical and 4 physical cores
Frequency=2727540 Hz, Resolution=366.6307 ns, Timer=TSC
.NET Core SDK=2.1.402
  [Host] : .NET Core 2.1.4 (CoreCLR 4.6.26814.03, CoreFX 4.6.26814.02), 64bit RyuJIT
  Clr    : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3163.0
  Core   : .NET Core 2.1.4 (CoreCLR 4.6.26814.03, CoreFX 4.6.26814.02), 64bit RyuJIT


```
|          Method |  Job | Runtime | Items |       Mean |     Error |    StdDev |     Median |
|---------------- |----- |-------- |------ |-----------:|----------:|----------:|-----------:|
|           **Queue** |  **Clr** |     **Clr** |  **1000** |  **11.056 us** | **0.0874 us** | **0.0818 us** |  **11.018 us** |
|       SyncQueue |  Clr |     Clr |  1000 |  23.356 us | 0.5324 us | 0.4719 us |  23.138 us |
| ConcurrentQueue |  Clr |     Clr |  1000 |  22.376 us | 0.5529 us | 0.4901 us |  22.150 us |
|           Queue | Core |    Core |  1000 |   8.144 us | 0.0449 us | 0.0351 us |   8.137 us |
|       SyncQueue | Core |    Core |  1000 |  23.153 us | 0.4593 us | 0.4716 us |  23.411 us |
| ConcurrentQueue | Core |    Core |  1000 |  21.921 us | 0.4307 us | 0.5128 us |  21.673 us |
|           **Queue** |  **Clr** |     **Clr** |  **5000** |  **58.691 us** | **1.5301 us** | **1.7007 us** |  **57.814 us** |
|       SyncQueue |  Clr |     Clr |  5000 | 121.460 us | 2.5335 us | 3.0160 us | 119.794 us |
| ConcurrentQueue |  Clr |     Clr |  5000 | 109.955 us | 0.4101 us | 0.3425 us | 109.938 us |
|           Queue | Core |    Core |  5000 |  43.350 us | 0.8453 us | 1.0062 us |  42.722 us |
|       SyncQueue | Core |    Core |  5000 | 119.043 us | 2.3472 us | 3.7230 us | 118.745 us |
| ConcurrentQueue | Core |    Core |  5000 |  99.175 us | 0.5945 us | 0.5561 us |  99.065 us |
|           **Queue** |  **Clr** |     **Clr** | **10000** | **114.703 us** | **0.6178 us** | **0.5477 us** | **114.715 us** |
|       SyncQueue |  Clr |     Clr | 10000 | 240.862 us | 5.5465 us | 5.1882 us | 238.419 us |
| ConcurrentQueue |  Clr |     Clr | 10000 | 225.746 us | 4.3997 us | 5.7208 us | 224.222 us |
|           Queue | Core |    Core | 10000 |  86.216 us | 1.7215 us | 2.5767 us |  85.101 us |
|       SyncQueue | Core |    Core | 10000 | 239.741 us | 4.6617 us | 7.2578 us | 239.364 us |
| ConcurrentQueue | Core |    Core | 10000 | 201.448 us | 4.4062 us | 4.5249 us | 200.655 us |

**Comment by DrDao** [comment]
I would like to express the concurrentqueue performance may be problematic, because this problem should not occur, concurrentqueue on the CLR or mono show the results are very different, it is surprising. The reason to use concurrentqueue instead of Syncqueue or queue is because I want to use it with high performance or high concurrency and thread safety, and the queue or syncqueue is completely not enough for me, as in the case of the CLR, it completely satisfies my existing requirements.

**Comment by DrDao** [comment]
I suspect that this problem occurs on the core because the Concurrentqueue implementation of the core is different from the CLR or mono .... I haven't had time to look at the CLR's concurrentqueue code, I'll look at it sometime, and I'll be happy if I can solve the problem by the way.

**Comment by stephentoub** [comment]
Just from looking at the repro, presumably this is a dup of https://github.com/dotnet/corefx/issues/29759.

**Comment by ViktorHofer** [comment]
Closing as potential duplicate. @DrDao the changes that are discussed in #29759 will be available with .NET Core 2.2 which will be released later this year.

**Comment by DrDao** [comment]
But it would be nice to be able to separate System.Collections.Concurrent into NuGet so that you don't have to follow a specific release to fix the problem. Anyway... It is also very happy to have been repaired now. Thanks again.
