### ISSUE TITLE
Unresolved P/Invoke method 'GetSystemPowerStatus!kernel32.dll' cause a crash with the app from the store

### ISSUE THREAD

**Issue by Jqk-Nono** [dotnet/corefx#32449]
> Unhandled exception at app level: Unresolved P/Invoke method 'GetSystemPowerStatus!kernel32.dll' from this method. Please look for this method in build warnings for more details. 

However, there is no warning about the method **GetSystemPowerStatus**

This issue only happens after I publish my app to the Windows Store (and download it through the Windows Store). Performing local DEBUG and RELEASE builds work as expected. Side-loading the app also works as **expected.**

**Comment by MichalStrehovsky** [comment]
@Jqk-Nono Could you please reach out to the .NET Native team at dotnetnative at microsoft.com? We are better equipped to help there. This failure mode doesn't look CoreFX-related.
