### ISSUE TITLE
Design / Source tabs are missing on Mac (Mono + GTK#)

### ISSUE THREAD

**Issue by katestaneva** [dotnet/corefx#32448]
Just working on a little cross platform app using Mono and GTK# as a front end library. I am working on a Mac. The problem I run into is that my Desing / Source tabs disappear the second I add a new GTK window or restart Visual Studio. If I open a brand new project, my default MainWindow has the tabs and I am able to see the design form. If I add another Window the tabs won't show for this new window. Restarting Visual Studio will wipe all of the tabs for all the windows and seeing the design won't be possible at all for any of them. 

Is it the Mac, is it the GTK# is it me doing something wrong or a bug? Thanks.

**Comment by karelz** [comment]
It is not clear to me if you have problem with the IDE (VS for Mac?) or with Mono itself.
Best place would be to file it under Mono or MonoDevelop: https://github.com/mono (I am not sure where VS for Mac is tracked)
