### ISSUE TITLE
Add N-ary internal specializations for InvocationExpression

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#3245]
In Bing, we use an expression normal form whereby method call expressions etc. get erased for invocation expressions of an unbound parameter, e.g.:

Expression.Call(where, xs, filter)

becomes

Expression.Invoke(Expression.Parameter(typeof(...), "where"), xs, filter)

This is done to decouple client libraries and service libraries through erasure of MemberInfo objects. The service uses a binder to bind the unbound parameter expression to a service-side definition and beta-reduces the invocation of the (lambda-based) definition.

A lot of those invocation expressions have 0, 1, 2, 3 arguments. However, unlike MethodCallExpression, InvocationExpression has no N-ary specializations that help to reduce memory. The proposal is to add such specializations to conserve memory.

**Comment by bartdesmet** [comment]
I can prepare a PR with proposed improvements.

**Comment by VSadov** [comment]
Fixed in #3298
