### ISSUE TITLE
Cannot restore latest master builds of Microsoft.Win32.Registry, missing System.Buffers dependency

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#32461]
We found this through our automation which updates aspnet to the latest 3.0 builds. See https://github.com/aspnet/Universe/pull/1419

After updating to Microsoft.Win32.Registry from 4.6.0-preview1-26907-04 to 4.6.0-preview1-26924-03, restore began to fail.

> error NU1603: Microsoft.Win32.Registry 4.6.0-preview1-26924-03 depends on System.Buffers (>= 4.6.0-preview1-26924-03) but System.Buffers 4.6.0-preview1-26924-03 was not found. An approximate best match of System.Buffers 4.6.0-preview3-26501-01 was resolved.

Is there an issue with publish System.Buffers to dotnet.myget.org/F/dotnet-core?

**Comment by stephentoub** [comment]
cc: @safern, who removed the System.Buffers package in https://github.com/dotnet/corefx/pull/32096.

@weshaggard, @ericstj

**Comment by safern** [comment]
Taking a look.
