### ISSUE TITLE
Setting HttpWebRequest.AutomaticDecompression

### ISSUE THREAD

**Issue by acastaner** [dotnet/corefx#3248]
When I look at the source of HttpWebRequest I see that the AutomaticDecompression property of the HttpClientHandler is forced to `DecompressionMethods.None` ([line 373](https://github.com/dotnet/corefx/blob/07f8c0fe64ac44bedced873181d6832bc2afcc50/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs)).

How do I set it properly? In the past we could simply do this:

`request.AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;`

**Comment by davidsh** [comment]
cc: @CIPop @stephentoub @ericstj @stephentoub 

The current version of the System.Net.Requests contract does NOT expose the AutomaticDecompression property on the HttpWebRequest object.  The full .NET Framework (Desktop) does support and expose this as a public property.  

The .NET profile for CoreFx was derived from the original .NET Windows App Store Profile.  This profile was a reduced set of APIs and this property was then removed from the public contract.

The HttpWebRequest API is considered one of the older, legacy APIs.  We encourage developers to use the System.Net.Http API surface.  There, you will find the AutomaticDecompression property available on the HttpClientHandler object.

**Comment by acastaner** [comment]
Thanks a lot for the clarification! Please close this issue as you see fit.
