### ISSUE TITLE
Is GetAwaiter().GetResult() will cause deadlock on high traffic

### ISSUE THREAD

**Issue by linkinshi** [dotnet/corefx#32507]
namespace AsyncTestConsoleApp
{
    class Program
    {
        private static readonly TaskFactory MyTaskFactory = new TaskFactory(CancellationToken.None, TaskCreationOptions.None, TaskContinuationOptions.None, TaskScheduler.Default);

        private static void RunSync(Func<Task> func)
        {
            var cultureUi = CultureInfo.CurrentUICulture;
            var culture = CultureInfo.CurrentCulture;
            MyTaskFactory.StartNew(() =>
            {
                Thread.CurrentThread.CurrentCulture = culture;
                Thread.CurrentThread.CurrentUICulture = cultureUi;
                return func();
            }).Unwrap().GetAwaiter().GetResult();
        }
        public static void PrintThreadLog(string title)
        {
            if (string.IsNullOrWhiteSpace(title))
            {
                title = "默认";
            }
            ThreadPool.GetMinThreads(out var minWorker0, out var minIOC0);
            ThreadPool.GetMaxThreads(out var maxWorker0, out var maxIOC0);
            ThreadPool.GetAvailableThreads(out var aWorkerThreads, out var aCompletionPortThreads);
            Console.WriteLine($"{title}：minWorker:{minWorker0} minIOC:{minIOC0}");
            Console.WriteLine($"{title}：maxWorker:{maxWorker0} maxIOC:{maxIOC0}");
            Console.WriteLine($"{title}：AvailableWorker:{maxWorker0} AvailablemaxCompletionPortThreads:{maxIOC0}");
        }
        static void Main(string[] args)
        {
            ThreadPool.SetMinThreads(2, 200);
            ThreadPool.SetMaxThreads(5, 200);
            PrintThreadLog("");
            IConnection connection = new Connection(new User());

            int waitingStart = 0, inProgress = 0;

            int sleepTime = 150;

            int waited = 0;

            for (; ; )
            {
                Interlocked.Increment(ref waitingStart);
                // 模拟客户端请求
                // assume IConnection interface can't be changed to async
                ThreadPool.QueueUserWorkItem(
                    _ =>
                    {
                        Interlocked.Decrement(ref waitingStart);
                        Interlocked.Increment(ref inProgress);
                        //await connection.OnRequestReceivedAsync("request");
                        connection.OnRequestReceived("request");
                        Interlocked.Decrement(ref inProgress);
                    });

                string msg = string.Format(
                    "Requests in queue: {0}, requests in progress: {1}, current sleep time: {2}",
                    Volatile.Read(ref waitingStart),
                    Volatile.Read(ref inProgress),
                    Volatile.Read(ref sleepTime));

                bool poolAlive = CheckPoolAlive();
                if (waited > 500 || !poolAlive)
                {
                    Console.Clear();
                    Console.WriteLine(msg);
                    waited = 0;
                }
                if (!poolAlive)
                    throw new InvalidOperationException("ThreadPool deadlocked! " + msg);

                if (sleepTime > 30) sleepTime--;
                Thread.Sleep(sleepTime);
                waited += sleepTime;
            }
        }

        static bool CheckPoolAlive()
        {
            // very simple check for ThreadPool deadlock
            // during this check no new requests will be enqueued
            // failing this check means that all current executing requests will never finish
            using (ManualResetEventSlim ok = new ManualResetEventSlim(false))
            {
                ThreadPool.QueueUserWorkItem(_ => ok.Set());
                return ok.Wait(30000);
            }
        }

        interface IConnection
        {
            void OnRequestReceived(string request);

            Task OnRequestReceivedAsync(string request);
        }

        class Connection : IConnection
        {
            readonly User _user;

            public Connection(User user)
            {
                _user = user;
            }

            public void OnRequestReceived(string request)
            {
                // 同步调用异步
                //var task = _user.HandleRequest(request);
                RunSync(()=> _user.HandleRequest(request));
                //task.Wait();
                //tas
                //task.GetAwaiter().GetResult();
                //if (!task.Result) throw new InvalidOperationException();
            }

            public async Task OnRequestReceivedAsync(string request)
            {
                // 同步调用异步
                var task = await _user.HandleRequest(request);
                if (!task) throw new InvalidOperationException();
            }
        }

        class User
        {
            public async Task<bool> HandleRequest(string request)
            {
                //下面这句会把当前控制权交给调用者
                await Task.Delay(Rnd.Next(30, 700)); // 模拟各种操作
                return true;
            }
        }

        [ThreadStatic]
        static Random _rnd;

        static Random Rnd => _rnd ?? (_rnd = new Random(Guid.NewGuid().GetHashCode()));
    }
}

Task<T>.Result and Task<T>.Wait() will cause deadlock,but is the GetAwaiter().GetResult() will cause deadlock?
There is my test code.

**Comment by stephentoub** [comment]
I'm not clear on what you believe the problem is.  This code blocks a thread pool thread waiting for other thread pool threads to do work.  That's a recipe for deadlock, regardless of what mechanism you use.  I don't see any framework bug here.

**Comment by linkinshi** [comment]
> I'm not clear on what you believe the problem is. This code blocks a thread pool thread waiting for other thread pool threads to do work. That's a recipe for deadlock, regardless of what mechanism you use. I don't see any framework bug here. This is a core reason why async/await exists, to avoid blocking threads.

I just want to know Is the GetAwaiter().GetResult() will cause deadlock on high traffic？
there are so many people said replace Task.Result or Task.Wait() with GetAwaiter().GetResult(), but in my code , the GetAwaiter().GetResult() still cause deadlock. 
so if the GetAwaiter().GetResult() still cause deadlock, why there is so many GetAwaiter().GetResult() in the source code .
https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=GetAwaiter%28%29.GetResult%28%29&type=

**Comment by davidfowl** [comment]
@linkinshi yes, Task.Wait, GetAwaiter().GetResult(), Task.Result can all dead lock and they can all starve the thread pool. You need to await the Task. 

> if the GetAwaiter().GetResult() still cause deadlock, why there is so many GetAwaiter().GetResult() in the source code .
https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=GetAwaiter%28%29.GetResult%28%29&type=

Most of those are tests.

**Comment by linkinshi** [comment]
> @linkinshi yes, Task.Wait, GetAwaiter().GetResult(), Task.Result can all dead lock and they can all starve the thread pool. You need to await the Task.
> 
> > if the GetAwaiter().GetResult() still cause deadlock, why there is so many GetAwaiter().GetResult() in the source code .
> > https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=GetAwaiter%28%29.GetResult%28%29&type=
> 
> Most of those are tests.

thanks！
