### ISSUE TITLE
string.indexOf works differently on Windows and Linux

### ISSUE THREAD

**Issue by PavelBansky** [dotnet/corefx#32519]
Following code works differently in Linux and Windows.
In Windows it works as expected and returns "**Index of newline is at 18**"
In Linux it returns "**Index of newline is at -1**"

Apparently the string.IndexOf works incorrectly in Linux.

.NET Core runtime: 2.1.402
Linux: Ubuntu 18.04
Windows: 10 Enterprise - 1803 (OS Build 17134.285)

```csharp
using System;

namespace testindex
{
    class Program
    {
        static void Main(string[] args)
        {
            string text = "// GET api/values\r\n        [HttpGet]\r\n        ";;
            string suffix = "\n";

            int suffixIndex = text.IndexOf(suffix);
            Console.WriteLine("Index of newline is at {0}", suffixIndex);
        }
    }
}
```

**Comment by stephentoub** [comment]
Looks like a dup of https://github.com/dotnet/corefx/issues/31103
