### ISSUE TITLE
Expression trees should support Span<T>, stackalloc, ref struct

### ISSUE THREAD

**Issue by vermorel** [dotnet/corefx#32523]
[Expression Trees](https://docs.microsoft.com/en-us/dotnet/csharp/expression-trees) are very useful and capable when it comes to generate specialized high-performance code. In this area, `Span<T>`, `stackalloc` and `ref struct` are probably among the most significant recent additions to .NET performance-wise. Yet, it is not possible to use any of those constructs in Expression Trees. It would be very useful if Expression Trees were extended to support those newer .NET capabilities.

**Comment by jnm2** [comment]
I think this would have to wait for https://github.com/dotnet/corefx/issues/24390.

**Comment by cston** [comment]
@vermorel, thanks for reporting this. However, System.Linq.Expressions is not being actively developed at this time, see https://github.com/dotnet/corefx/issues/33170.

cc @jaredpar
