### ISSUE TITLE
can i host .net core 2.1 project in windows server enterprise 2008 sp2

### ISSUE THREAD

**Issue by RenshuozZ** [dotnet/corefx#32521]
![image](https://user-images.githubusercontent.com/11639841/46187226-222e7680-c315-11e8-941c-bba559b78df1.png)

it is error when i install dotnet hosting 2.1.2 in this systerm

**Comment by Berrysoft** [comment]
Maybe you should install dotnet runtime or sdk.

**Comment by karelz** [comment]
Yes, either install 2.1 runtime on your system, or make your application self-contained.
