### ISSUE TITLE
What do we do with Microsoft.Windows.Compatibility in 3.0?

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#32539]
We should also consider other assemblies being added in 3.0.  At the very least System.Windows.Extensions, but there may be others.

We also need to recconcile how with think about this package with respect to the DesktopUI shared framework, since the latter is containing many, but not all of the libraries in Microsoft.Windows.Compatibility.

/cc @terrajobst @safern @danmosemsft

**Comment by danmosemsft** [comment]
Example: if we port System.Data.OleDB, that should be in the compat pack (@maryamariyan )

**Comment by ericstj** [comment]
We should be done adding packages for 3.0, lets do an audit and make sure this references everything we want it to.

**Comment by ericstj** [comment]
Here are the packages I see that should be part of this:
System.ComponentModel.Composition.Registration 
System.Reflection.Context
System.Reflection.Emit*
System.Runtime.WindowsRuntime*

@safern can you add these to the package?

**Comment by ericstj** [comment]
I'll see if I can help on this since @safern is fully booked on nullable.

**Comment by danmosemsft** [comment]
Thanks @ericstj
