### ISSUE TITLE
FileLoadException System.Numerics.Vectors

### ISSUE THREAD

**Issue by Symbai** [dotnet/corefx#32544]
### Project:
- WPF
- .NET Framework 4.7.2

### Nuget:
System.Buffers 4.4.0
System.Memory 4.5.1
System.Numerics.Vectors 4.5.0
System.Runtime.CompilerServices.Unsafe 4.5.0

### code:
```
public static string[] CheckSomething(ReadOnlySpan<char> line)
{
	var i = line.IndexOf('(') + 1; //exception is thrown here
	//...
}
```
### Machines:
Systems where this issue does **NOT** happen:
- Windows 10 Pro 1803 17134.285 64-Bit
- VS 15.8.5 installed (developing machine)
- Net Framework 4.7.2

![works](https://user-images.githubusercontent.com/14368203/46245407-94b65980-c3dc-11e8-8136-cb02e6894cb8.gif)

System(s) where this issue occurs:
- Windows 10 Pro Insider Build 1809 17758.1  64-Bit 
- Windows 8.1  64-Bit
- Both VS NOT installed
- Both Net Framework 4.7.2

![issue](https://user-images.githubusercontent.com/14368203/46245408-9849e080-c3dc-11e8-9c47-b36a3cf68739.gif)

### Exception Stacktrace Message:
```
System.IO.FileLoadException: Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.SpanHelpers.IndexOf(Char& searchSpace, Char value, Int32 length)
   at System.MemoryExtensions.IndexOf[T](ReadOnlySpan`1 span, T value)
```

I can't really say what the issue is. The application launches fine on developing machine but on other is does not. Same executable, same dlls, System.Numerics.Vectors.dll is ofc included. Both have .NET framework 4.7.2 installed as well as .NET core 2.1 runtime.

### Demonstration project:
[VectorIssue.zip](https://github.com/dotnet/corefx/files/2430595/VectorIssue.zip)

**Comment by karelz** [comment]
@joperezr can you please help here?
The bottom line is that you likely need bindingRedirects. There is some difference between the machines - I doubt both have truly .NET Framework 4.7.2 installed.
Note: .NET Core is irrelevant in your scenario. The app runs on .NET Framework (which should not be tracked on GitHub, but let's first see what we can find out ...).

**Comment by joperezr** [comment]
Well, @karelz brings a good point that there may be differences still with the actual framework that you have installed, but one other thing that I noticed right off the bat is that on the app that crashes you don't seem to have the VectorIssue.exe.config file which would contain the binding redirects that might be making it work on the first version.

**Comment by Symbai** [comment]
@joperezr The config file was the problem. With config file it works on both systems.

**Comment by Symbai** [comment]
Sorry I have to reopen this. I was now writing a Unittest in VS for this project and a test fails with the exact error message about:

`System.IO.FileLoadException: Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.SpanHelpers.IndexOf(Char& searchSpace, Char value, Int32 length)
   at System.MemoryExtensions.IndexOf[T](ReadOnlySpan`1 span, T value)`

The program itself runs without any issues on my computer. It happens only when running the unit test on the same computer. The config file exists in the bin/Debug folder of the unit test project so I'm really clueless about what causes it this time and how I can fix it.

**Comment by joperezr** [comment]
Which test runner are you using? There are some test runners that won't honor the program's app.config file and will just use their own app.config which won't do the right redirect.

**Comment by Symbai** [comment]
There is only one for .NET Framework in project template, guess its MSTest (built in), no third parties.

**Comment by Symbai** [comment]
Switched to xunit and it works now. Thanks for the hint @joperezr.
