### ISSUE TITLE
API Proposal: Add generic UnsafeQueueUserWorkItem<TState> overload

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#32547]
In .NET Core 2.1 we added a generic overload of QueueUserWorkItem that can avoid boxing the state parameter https://github.com/dotnet/corefx/issues/27464#issue-300109510. We should add the same overload for UnsafeQueueUserWorkItem. I'd like to use this in pipelines to offer a PipeScheduler that avoids capturing the `ExecutionContext`.

```C#
public static bool UnsafeQueueUserWorkItem<TState>(Action<TState> callBack, TState state, bool preferLocal)
```

cc @stephentoub

**Comment by davidfowl** [comment]
It must 😬. There’s at least one other thing that want me to use this in 3.0

**Comment by benaadams** [comment]
Add the 3.0 milestone? They get preference in api reviews

**Comment by terrajobst** [comment]
Given that we already approved the Unsafe* pattern here and that we did this overload for the non-unsafe ones, there is no reason not to approve this :-)
