### ISSUE TITLE
WinHttpWebSocketState is leaking a GCHandle

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#3256]
System.Net.WebSockets.Client.WinHttpWebSocketState allocates a GCHandle in the constructor with this code:

```c#
        private GCHandle _operationHandle = new GCHandle();
        public WinHttpWebSocketState()
        {
            _operationHandle = GCHandle.Alloc(this);
        }
```

But if never calls Free() on the GCHandle.  Normally, you need code like this to free the handle:

```c#
            if (_operationHandle.IsAllocated)
            {
                _operationHandle.Free();
            }
```

**Comment by davidsh** [comment]
cc: @CIPop

**Comment by CIPop** [comment]
Ideally we should have a stabilized pattern for WinHttpHandler first. At that time, code should be shared so that a single WinHttpSafeHandle exists.

Marking for RTM since WinHttpHandler work for native handle life-time is in progress.

**Comment by davidsh** [comment]
I already solved this for WinHttpHandler so we should be able to use its similar pattern.

**Comment by KKhurin** [comment]
@davidsh  @SidharthNabar  @CIPop 
This memory leak blocks a whole lot of WCF scenarios not only in stress but also in perf. 
Would you consider fixing it before RTM?

**Comment by davidsh** [comment]
@KKhurin I will prioritize it higher in my "bug fix list".  That said, it will probably be a week or so before I'm able to get to it.
