### ISSUE TITLE
Performance of LINQ .Any() - type check to leverage .Count property?

### ISSUE THREAD

**Issue by dnickless** [dotnet/corefx#32569]
In the `.Any()` method here:
https://github.com/dotnet/corefx/blob/e043326e204a9566ee26403b522cf95cda2d54ee/src/System.Linq/src/System/Linq/AnyAll.cs#L18:L21

would it make sense to check for `IReadOnlyCollection` and call `Count` in order to avoid the enumerator instantiation?

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/issues/24773
https://github.com/dotnet/corefx/issues/26579
https://github.com/dotnet/corefx/pull/28472

**Comment by dnickless** [comment]
Oh well, it would appear there is high demand for that. ;) I'll close this one and I promise to properly use the search next time.
