### ISSUE TITLE
HttpUtility.ParseQueryString doesn't roundtrip when there are multiple values for the same key, behavior is inconsistent with .NET Framework

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/corefx#32575]
In .NET Framework the `HttpUtility.ParseQueryString` has roundtripping behavior, i.e. the following test passes:

```c#
        [Fact]
        public void ParseQueryString_and_ToString_should_roundtrip_when_multiple_values_for_the_same_key()
        {
            var input = "type=foo&type=bar";
            var values = HttpUtility.ParseQueryString(input);
            var output = values.ToString();
            Assert.Equal(input, output);
        }
```

However, in .NET Core (2.1), this test fails: `values.ToString()` returns `type=foo%2cbar`.

**Comment by davidsh** [comment]
There is already a PR for this submitted: #32578

**Comment by karelz** [comment]
Darn, I missed that :(

**Comment by thomaslevesque** [comment]
As mentioned by @karelz in https://github.com/dotnet/corefx/pull/32578#discussion_r222129986, there's another case that is handled by .NET Framework but not by .NET Core: keys without values, i.e. `name&another`. This should probably be a separate issue, though.

**Comment by thomaslevesque** [comment]
> As mentioned by @karelz in [#32578 (comment)](https://github.com/dotnet/corefx/pull/32578#discussion_r222129986), there's another case that is handled by .NET Framework but not by .NET Core: keys without values, i.e. `name&another`. This should probably be a separate issue, though.

Opened https://github.com/dotnet/corefx/issues/32598 to take care of this.
