### ISSUE TITLE
System.Reflection.Metadata doesn't work with UAPAOT

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/corefx#32594]
The light up code here:

https://github.com/dotnet/corefx/blob/9cb4ea0045eed954d72aea6f283d22f2d7fb3c7b/src/System.Reflection.Metadata/src/System/Reflection/Internal/Utilities/EncodingHelper.cs#L173-L188

requires that we have reflection metadata for the `Encoding_GetString` delegate, which we don't, because the delegate is not public and S.R.Metadata opts into size saving optimization that blocks reflection on everything in it that is not public on UAPAOT.

It's possible to opt out of reflection blocking with `<BlockReflectionAttribute>false</BlockReflectionAttribute>` in the csproj, ideally, we should just use a public delegate type for this to avoid the problem (either make this public, or use Func/Action).

Note that S.R.Metadata also builds a `System.Private.Reflection.Metadata.Ecma335` version that is considered a low level component of the CoreRT runtime and as such needs to have reflection blocking enabled.

We found out about this not working by investigating crash dumps of Roslyn compiled with .NET Native. Seems like we don't have test coverage that would exercise this code path on UAPAOT. That needs to be fixed as well.

**Comment by jkotas** [comment]
This light-up is not necessary for uap. The fix should be to change the conditions on when to not use the  light-up in the .csproj file to include uap as well: 

https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/src/System.Reflection.Metadata.csproj#L97
