### ISSUE TITLE
.NET Core and pattern compatability

### ISSUE THREAD

**Issue by eatdrinksleepcode** [dotnet/corefx#326]
(@terrajobst rightly [pointed out](https://github.com/dotnet/corefx/issues/271#issuecomment-68022859) that the thread on implementing collection interfaces on Regex classes had wandered into abstract discussion not related to the original issue. So I am opening this issue in order to continue the discussion here.)

To summarize my point (see the [Regex thread](https://github.com/dotnet/corefx/issues/271) for more details): with the addition of IReadOnlyList in .NET 4.5, I don't believe it is appropriate to continue implementing mutable collection interfaces such as IList<T> on immutable collections. The fact that existing immutable collections (including those in the Immutable Collections library) implement these interfaces is not a good enough reason to continue this flawed pattern.

This issue is a particular example of the larger question of how .NET Core will evolve, and how much tolerance it has to evolve _away_ from flawed patterns in the .NET Framework.

**Comment by terrajobst** [comment]
It seems we've closure on this issue. Feel free to state otherwise.

**Comment by eatdrinksleepcode** [comment]
I can't say that I am happy with the conclusion; your responses have in no way persuaded me that implementing a mutable interface on an immutable class is a logical or sensible thing to do.

However, given that my arguments have also apparently failed to persuade the core owners of the inherent flaw in this approach, I agree that further discussion is unlikely to be productive.

**Comment by terrajobst** [comment]
In our latest API review, [this came up as well](https://github.com/dotnet/apireviews/tree/master/2015-01-14-misc#316-implement-ilistt-ireadonlylistt-and-ilist-on-regex-collections). @KrzysztofCwalina will take a stab at this.

**Comment by eatdrinksleepcode** [comment]
I think @KrzysztofCwalina was basically correct in the API review: this proposal essentially changes the nature of the IList interface, making it always mutable rather than optionally mutable, and deprecating (whether explicitly using the attribute or not) the IsReadOnly property. This is a fairly radical change, and there seemed to be some reluctance to accept that characterization in the meeting. But I think it is worth acknowledging it, and understanding that much of the resistance to it comes from that fact (which is entirely reasonable).

It seems to me that there is a group of people (including myself) who believe that the original design of IList, with its optional mutability, was not the optimal design; and that the introduction of the IReadOnlyList interface is an opportunity to (slowly, and painfully) begin to improve that design. There are others who believe that the original design was and still is appropriate and does not need to be changed. There also seem to be at least some who believe that the original design may not have been ideal, but that changing it now is not worth the effort or the pain (I am inferring that from some of the comments in the meeting).

Another thought: the point was made in the meeting that immutable collection classes should implement IList in order to be more broadly usable with APIs that were created prior to the existence of IReadOnlyList, and interact with IList even when they only intend to read. However, that argument works the other way too: APIs should interact with IList instead of IReadOnlyList in order to be usable with collections that were created priority to the introduction of IReadOnlyList. If both of those are true - if we prioritize consistency with the past over usability in the future - then IReadOnlyList will never be used at all. So what was the point of adding it?

I think the suggested approach of adapters, or any other mechanisms we can think of the will allow interoperability without constraining our ability to evolve the APIs, are well worth exploring.

**Comment by KrzysztofCwalina** [comment]
this is assigned to me, but I am not sure what the request/action-item is. I am closing it then. Please feel free to reopen if there is anything actionable.
