### ISSUE TITLE
System.Console.Is[Input|Output]Redirected is not available in CoreFX

### ISSUE THREAD

**Issue by anuchandy** [dotnet/corefx#3260]
IsInputRedirected and IsOutputRedirected properties are not available in System.Console

**Comment by weshaggard** [comment]
@pallavit can you please have a look at this while you are looking at the other Console requests.

**Comment by pallavit** [comment]
Sure

**Comment by pallavit** [comment]
We could implement this cross-plat by checking for S_IFCHR()

**Comment by stephentoub** [comment]
> We could implement this cross-plat by checking for S_IFCHR

FWIW, we already do that :smile:
https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System/ConsolePal.Unix.cs#L77-L104

**Comment by pallavit** [comment]
Thanks :)

**Comment by pallavit** [comment]
This has been enabled as #3650
