### ISSUE TITLE
Issue with sending commands using process.StandardInput.Write on MacOS

### ISSUE THREAD

**Issue by donnyv** [dotnet/corefx#32608]
I'm having a weird problem where once a Terminal process is launched it will not accept anymore commands.
https://stackoverflow.com/questions/52638733/process-standardinput-write-is-not-writing-to-the-terminal-on-macos-using-net-c

**Comment by donnyv** [comment]
I want to use a terminal window to keep feeding it commands. When I use just scriptFile and leave arguments empty, nothing happens.

**Comment by tmds** [comment]
On Linux:
script.sh (which has x-bit set):
```sh
#!/bin/bash
while IFS='$\n' read -r line; do
  if [ "$line" == "exit" ]; then
    exit
  fi
  echo "executing $line"
done
```
Program.cs:
```cs
using (var process = Process.Start(new ProcessStartInfo { FileName = "script.sh", RedirectStandardInput = true}))
{
    process.StandardInput.WriteLine("command1");
    process.StandardInput.WriteLine("command2");
    process.StandardInput.WriteLine("command3");
    process.StandardInput.WriteLine("exit");
    process.WaitForExit();
}
```
outputs:
```
executing command1
executing command2
executing command3
```

Does something similar not work on mac?

**Comment by donnyv** [comment]
I get this error...
![image](https://user-images.githubusercontent.com/2224189/46639660-90551380-cb35-11e8-8079-8042d594b40e.png)

**Comment by donnyv** [comment]
It seems to work but doesn't actually execute the command. I tried just listing a directory.  It echoed the command back like your script has it but didn't actually execute it. Then I tried redirecting the output and commands stopped being written. 

```
var startinfo = new ProcessStartInfo { 
	FileName = scriptFile, 
	RedirectStandardInput = true,
	//RedirectStandardOutput = true,
	//RedirectStandardError = true
};

using (var process = Process.Start(startinfo))
{
	//process.OutputDataReceived += new DataReceivedEventHandler(outdata);
	//process.ErrorDataReceived += new DataReceivedEventHandler(outdataError);
	process.StandardInput.WriteLine("ls");
	//process.StandardInput.WriteLine("exit");
	process.WaitForExit();
}


}

static void outdata(object sendingProcess, DataReceivedEventArgs outLine){
	var d = outLine.Data;
}

static void outdataError(object sendingProcess, DataReceivedEventArgs outLine){
	var d = outLine.Data;
}
```

**Comment by tmds** [comment]
Can you share a small reproducer that includes a script?

**Comment by donnyv** [comment]
This is a zip with the VSCode project and the bash script.
https://drive.google.com/file/d/1qGeSDip9aJ7blVjbAHs9obG27VeQZPLZ/view?usp=sharing

**Comment by tmds** [comment]
> This is a zip with the VSCode project and the bash script.

What is the actual behavior of the program on OSX?

On Linux:
If I do `chmod +x mongo_script2.sh`
And change the `scriptFile` to point to `mongo_script2.sh`
Then `dotnet run` outputs `executing ls` and waits forever.
This is the expected behavior.

**Comment by donnyv** [comment]
Thats fine, now un-comment process.OutputDataReceived & process.ErrorDataReceived. And put a break on outdata and outdataError methods and run it. They never get called.

**Comment by donnyv** [comment]
Doesn't seem to like that on the Mac.
![capture](https://user-images.githubusercontent.com/2224189/47195012-d2493b00-d327-11e8-9b93-22984cc79d38.JPG)

**Comment by donnyv** [comment]
That works. Question now is how do I get it to work with mongo.exe

**Comment by tmds** [comment]
> Thanks for putting up with me!!

You're welcome. I'm glad the issue is solved.

> I guess it does a direct concatenation with the FileName. So when I added a space at the beginning of the argument it worked!

Can you share the actual lines of code you changed (before, after)? It would help to understand why it didn't work, and it may also be useful for others with a similar issue.
