### ISSUE TITLE
Vector tests failing on one of my machines

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#3262]
On my local machine I doing a default build.cmd which builds x64 debug I keep getting the below failures. 

If it helps these pass on my other machine and the machine they fail on has the following processor: "Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz, 3601 Mhz, 4 Core(s), 8 Logical Processor(s)"

cc @mellinoe @CarolEidt 

System.Numerics.Tests.Vector3Tests.Vector3CopyToTest [FAIL] (TaskId:163)
        Assert.Throws() Failure (TaskId:163)
        Expected: typeof(System.ArgumentOutOfRangeException) (TaskId:163)
        Actual:   typeof(System.NullReferenceException): Object reference not set to an instance of an object. (TaskId:163)
        Stack Trace: (TaskId:163)
           D:\git\corefx\src\System.Numerics.Vectors\tests\Vector3Tests.cs(28,0): at System.Numerics.Tests.Vector3Tests.<>c__DisplayClass1_0.<Vector3CopyToTest>b__1() (TaskId:163)
     System.Numerics.Tests.Vector4Tests.Vector4CopyToTest [FAIL] (TaskId:163)
        Assert.Throws() Failure (TaskId:163)
        Expected: typeof(System.ArgumentOutOfRangeException) (TaskId:163)
        Actual:   typeof(System.NullReferenceException): Object reference not set to an instance of an object. (TaskId:163)
        Stack Trace: (TaskId:163)
           D:\git\corefx\src\System.Numerics.Vectors\tests\Vector4Tests.cs(28,0): at System.Numerics.Tests.Vector4Tests.<>c__DisplayClass1_0.<Vector4CopyToTest>b__1() (TaskId:163)
     System.Numerics.Tests.Vector2Tests.Vector2CopyToTest [FAIL] (TaskId:163)
        Assert.Throws() Failure (TaskId:163)
        Expected: typeof(System.ArgumentOutOfRangeException) (TaskId:163)
        Actual:   typeof(System.NullReferenceException): Object reference not set to an instance of an object. (TaskId:163)
        Stack Trace: (TaskId:163)
           D:\git\corefx\src\System.Numerics.Vectors\tests\Vector2Tests.cs(28,0): at System.Numerics.Tests.Vector2Tests.<>c__DisplayClass1_0.<Vector2CopyToTest>b__1() (TaskId:163)
     System.Numerics.Tests.GenericVectorTests.GreaterThanOrEqualAnySByte [FAIL] (TaskId:163)
        Assert.False() Failure (TaskId:163)
        Expected: False (TaskId:163)
        Actual:   True (TaskId:163)
        Stack Trace: (TaskId:163)
           D:\git\corefx\src\System.Numerics.Vectors\tests\GenericVectorTests.cs(1248,0): at System.Numerics.Tests.GenericVectorTests.TestVectorGreaterThanOrEqualAny[T]() (TaskId:163)
           D:\git\corefx\src\System.Numerics.Vectors\tests\GenericVectorTests.cs(1204,0): at System.Numerics.Tests.GenericVectorTests.GreaterThanOrEqualAnySByte() (TaskId:163)
     System.Numerics.Tests.GenericVectorTests.GreaterThanOrEqualAllSByte [FAIL] (TaskId:163)
        Assert.True() Failure (TaskId:163)
        Expected: True (TaskId:163)
        Actual:   False (TaskId:163)
        Stack Trace: (TaskId:163)
           D:\git\corefx\src\System.Numerics.Vectors\tests\GenericVectorTests.cs(1300,0): at System.Numerics.Tests.GenericVectorTests.TestVectorGreaterThanOrEqualAll[T]() (TaskId:163)
           D:\git\corefx\src\System.Numerics.Vectors\tests\GenericVectorTests.cs(1259,0): at System.Numerics.Tests.GenericVectorTests.GreaterThanOrEqualAllSByte() (TaskId:163)
     System.Numerics.Tests.GenericVectorTests.CopyToByte [FAIL] (TaskId:163)
        Assert.Throws() Failure (TaskId:163)
        Expected: typeof(System.ArgumentOutOfRangeException) (TaskId:163)
        Actual:   typeof(System.NullReferenceException): Object reference not set to an instance of an object. (TaskId:163)
        Stack Trace: (TaskId:163)
           D:\git\corefx\src\System.Numerics.Vectors\tests\GenericVectorTests.cs(311,0): at System.Numerics.Tests.GenericVectorTests.<>c__DisplayClass100_0`1.<TestCopyTo>b__1() (TaskId:163)
     System.Numerics.Tests.GenericVectorTests.CopyToSByte [FAIL] (TaskId:163)
        Assert.Throws() Failure (TaskId:163)
        Expected: typeof(System.ArgumentOutOfRangeException) (TaskId:163)
        Actual:   typeof(System.NullReferenceException): Object reference not set to an instance of an object. (TaskId:163)
        Stack Trace: (TaskId:163)
           D:\git\corefx\src\System.Numerics.Vectors\tests\GenericVectorTests.cs(311,0): at System.Numerics.Tests.GenericVectorTests.<>c__DisplayClass100_0`1.<TestCopyTo>b__1() (TaskId:163)
     System.Numerics.Tests.GenericVectorTests.CopyToUInt16 [FAIL] (TaskId:163)
        Assert.Throws() Failure (TaskId:163)
        Expected: typeof(System.ArgumentOutOfRangeException) (TaskId:163)
        Actual:   typeof(System.NullReferenceException): Object reference not set to an instance of an object. (TaskId:163)
        Stack Trace: (TaskId:163)
           D:\git\corefx\src\System.Numerics.Vectors\tests\GenericVectorTests.cs(311,0): at System.Numerics.Tests.GenericVectorTests.<>c__DisplayClass100_0`1.<TestCopyTo>b__1() (TaskId:163)
     System.Numerics.Tests.GenericVectorTests.CopyToInt16 [FAIL] (TaskId:163)
        Assert.Throws() Failure (TaskId:163)
        Expected: typeof(System.ArgumentOutOfRangeException) (TaskId:163)

**Comment by mellinoe** [comment]
We have an internal fix for this, in the JIT. I will update this when the fix gets mirrored out and into the NuGet pacakge we consume here. Wes, I'll probably ask you to try to repro this again at that time.

**Comment by ericstj** [comment]
+1 hitting the same error.

We should update the coreclr used by our tests to get this fix.

**Comment by weshaggard** [comment]
@mellinoe @CarolEidt While the changes fixed some of the Vector tests I'm still seeing the following 2 values

```
     System.Numerics.Tests.GenericVectorTests.GreaterThanOrEqualAllSByte [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
           D:\git\corefx\src\System.Numerics.Vectors\tests\GenericVectorTests.cs(1300,0): at System.Numerics.Tests.Gene
  ricVectorTests.TestVectorGreaterThanOrEqualAll[T]()
           D:\git\corefx\src\System.Numerics.Vectors\tests\GenericVectorTests.cs(1259,0): at System.Numerics.Tests.Gene
  ricVectorTests.GreaterThanOrEqualAllSByte()
     System.Numerics.Tests.GenericVectorTests.GreaterThanOrEqualAnySByte [FAIL]
        Assert.False() Failure
        Expected: False
        Actual:   True
        Stack Trace:
           D:\git\corefx\src\System.Numerics.Vectors\tests\GenericVectorTests.cs(1248,0): at System.Numerics.Tests.Gene
  ricVectorTests.TestVectorGreaterThanOrEqualAny[T]()
           D:\git\corefx\src\System.Numerics.Vectors\tests\GenericVectorTests.cs(1204,0): at System.Numerics.Tests.Gene
  ricVectorTests.GreaterThanOrEqualAnySByte()
```

I do believe it is related to JIT though because setting COMPLUS_EnableAVX=0 all the tests pass.

**Comment by mellinoe** [comment]
Thanks Wes, that issue is tracked here: https://github.com/dotnet/corefx/issues/3066. I'm going to disable those two tests until I have time to fix them.
