### ISSUE TITLE
All File Paths for Windows Input and Output

### ISSUE THREAD

**Issue by aaabbbcccddd00001111** [dotnet/corefx#32638]
I want to use file paths with FileStream to do all input and output on Windows.
All input and output on Windows include display, sound, keyboard, mouse, storage, network, power, and ports.

What are the file paths?

**Comment by danmosemsft** [comment]
In most cases, Windows does not represent those concepts with file paths, as Unix does. You have to use API's - either Win32 API's, or .NET API's (which are often implemented in terms of Win32)

Is there API you need from .NET that seems to be missing?
