### ISSUE TITLE
System.Drawing.Common - "Graphics.ScaleTransform" does not affect the Text size on the Mac

### ISSUE THREAD

**Issue by k0st1x** [dotnet/corefx#32631]
"ScaleTransform" will affect on all graphics except "DrawString".
issue is reproduced only on Mac platform

```
var outputFile = "output";
for(int i = 0; i < 5; i++) {
    int scale = 1 + i;
    using(var bitmap = new Bitmap(32 * scale, 32 * scale))
    using(var font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point))
    using(var graphics = Graphics.FromImage(bitmap)) {
        graphics.FillRectangle(Brushes.White, 0, 0, bitmap.Width, bitmap.Height);
        graphics.PageUnit = GraphicsUnit.Document;
        graphics.ScaleTransform(scale, scale);
        graphics.DrawString("F", font, Brushes.Black, new PointF());
        bitmap.Save(outputFile + i + ".png", ImageFormat.Png);
        graphics.ResetTransform();
    }
}
```

**Comment by filipnavara** [comment]
This is more likely [libgdiplus](https://github.com/mono/libgdiplus) issue and it should be tracked there. It would be nice to verify if it also happens when libgdiplus is compiled with the Pango rendering option.

**Comment by safern** [comment]
I just tried it locally with a locally built libgdiplus version with the pango flag and it works fine. This seems more like a libgdiplus issue, so closing the issue and feel free to move it to their repo, or to re-open if you consider this is a corefx issue.

Thanks for reporting it.

**Comment by k0st1x** [comment]
@safern is there any chance to reproduce this issue on the cairo (that used out of the box by libgdiplus)?
