### ISSUE TITLE
WPF on .NET Core needs TypeDescriptor on System.Xml.Linq.XElement

### ISSUE THREAD

**Issue by rladuca** [dotnet/corefx#32641]
WPF has extension libraries for various types.  One of them is for System.Xml.Linq.XElement.

It expects that the TypeDescriptor for XElement contains the following property descriptors:
- Elements
- Descendants
- Attribute
- Element

This was previously provided by [XTypeDescriptor<T>.GetProperties with a special case for XElement](https://referencesource.microsoft.com/#System/compmod/system/componentmodel/CustomTypeDescriptor.cs,3575006103cb88da).  These seem to not exist in .NET Core and neither does the association of the TypeDescriptor with XElement ([see here](https://referencesource.microsoft.com/#System.Xml.Linq/System/Xml/Linq/XLinq.cs,3367036406d1344a)).

WPF requires this in SystemXmlLinqExtension (the implementation of this is not on the external reference source so I cannot link it here).

cc: @vatsan-madhavan, @ericstj

**Comment by rladuca** [comment]
Just to be clear, there is no reproduction of this at this point as this is an exposed bug during feature work in WPF on .NET Core 3.  Reproducing this requires some changes that are currently in progress in the framework.

**Comment by ericstj** [comment]
@onovotny has a repro of this

**Comment by ericstj** [comment]
Looks like we need to push `TypeDescriptionProviderAttribute` and `TypeDescriptionProvider` down to System.ObjectModel along with the others, add these attributes back to S.P.XML and the types which they point at.

Essentially:
```
[System.ComponentModel.TypeDescriptionProvider(typeof(MS.Internal.Xml.Linq.ComponentModel.XTypeDescriptionProvider<XElement>))]
public class XElement : XContainer, IXmlSerializable
```
```  
[System.ComponentModel.TypeDescriptionProvider(typeof(MS.Internal.Xml.Linq.ComponentModel.XTypeDescriptionProvider<XAttribute>))]
public class XAttribute : XObject
```

And everything in the closure of those types.

**Comment by ericstj** [comment]
Actually pushing that down will result in a ton of the typeconverter code moving down.  We may instead want to see about moving these TypeDescriptionProviders upstack into TypeConverter.

**Comment by ericstj** [comment]
One thing we could do that is minimal is push down only the attributes and use the string constructor on these to refer to the provider type, then put the provider type in the TypeConverter assembly.  Since that's an internal type, we'd either need to use the .NETCore identity (System.ComponentModel.TypeConverter assembly) or manually add the type forwards to the internal types into the System.Xml.Linq facade.
