### ISSUE TITLE
Where's the source for List<T>?

### ISSUE THREAD

**Issue by Mirandatz** [dotnet/corefx#32656]
Shouldn't it be [here](https://github.com/dotnet/corefx/tree/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.Collections/src/System/Collections/Generic)?

**Comment by Berrysoft** [comment]
It's a part of `System.Private.CoreLib`, so it is [here](https://github.com/dotnet/corefx/tree/master/src/Common/src/CoreLib/System/Collections/Generic).

**Comment by Mirandatz** [comment]
I see.
But why is it in  System.Private.CoreLib?

**Comment by Berrysoft** [comment]
To improve the speed, maybe.😄

**Comment by MarcoRossignoli** [comment]
I asked in past this is the response https://github.com/dotnet/corefx/issues/29524#issuecomment-388046743
Further info https://github.com/dotnet/coreclr#relationship-with-the-corefx-repository
I hope i was helpful!

**Comment by jnm2** [comment]
You can search both repos at once by starting here: https://source.dot.net/#q=List%3CT%3E

Then, if you still want to go to GitHub, click the 'Web Access" link at the bottom right of the page.
