### ISSUE TITLE
Use optimized N-ary MethodCallExpression nodes from all Call factories

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#3266]
Unlike Expression.Block, the overloads of Expression.Call that take in an Expression[] or IEnumerable<Expression> do not attempt to check the number of supplied arguments in order to instantiate more compact expression representations than the standard [Instance]MethodCallExpressionN nodes.

The language binds to the Expression[] overload. Various tools on our end, such as expression deserializers, also dispatch through the IEnumerable<Expression> overload.

It'd be good for those factories to analyze the number of supplied arguments and use compact representations if available. Also, [Instance]MethodCallExpression0 nodes are missing, even though it's quite common to have such expressions (e.g. ToString). Those could be added as part of this.

Note that - in addition to this - it may be possible for the language compilers to check for the N-ary factory method overloads and bind to more specialized overloads when it finds them in the corefx libraries it's compiling against (much like other places where the compiler uses "feature detection"). This would avoid the Expression[] allocation when it's not needed, therefore reducing some allocation costs.

**Comment by bartdesmet** [comment]
I can prepare a PR with proposed improvements.

**Comment by VSadov** [comment]
As I remember Expression.Block was new in ET2.0 and factory was implemented this way. The Call (and Invoke) were not new, so it could be that they were intentionally not switched to use this pattern. It could also be just an oversight. 

Is it practically likely that the change will be breaking to some existing code?

**Comment by bartdesmet** [comment]
I’ll have a thorough look from a compatibility angle and report any findings.

One point of debate is whether public factory method additions are warranted, e.g. for Invoke(lambda, arg0, …, argN). If not, the optimization could always be done from the Expression[] and IEnumerable<Expression> overloads by inspecting the number of expressions supplied (similar to the logic in Block), at the cost of an intermediary allocation for the collection prior to the optimization behind the factory method.

I’ll start small and we can iterate / discuss.

**Comment by VSadov** [comment]
Fixed in https://github.com/dotnet/corefx/pull/3288
