### ISSUE TITLE
Console Output in Unit Tests

### ISSUE THREAD

**Issue by nbaztec** [dotnet/corefx#32674]
I'm facing a issue where a particular test fails for exactly a single target, however there's no way that I can debug the actual code to fix it. I've tried with `Console.WriteLine` but of course the assembly isn't included within `System.Net.Sockets`. `System.Diagnostics.Debug` doesn't show up on the test log either.

Any ideas?

**Comment by stephentoub** [comment]
From within a corefx unit test you should definitely be able to use Console.WriteLine. If you mean using it within the product code in System.Net.Sockets, you could do something like:
```C#
[DllImport("msvcrt")]
private static extern int printf(string format, string arg);
private static void WriteLine(string s) => printf("%s\r\n", s);
```
on Windows, or:
```C#
[DllImport("libc")]
private static extern int printf(string format, string arg);
private static void WriteLine(string s) => printf("%s\n", s);
```
on Unix.

Or you could locally/temporarily modify https://github.com/dotnet/corefx/blob/d6646295b889daf9cf46caae1f9097b719873439/src/System.Net.Sockets/src/System.Net.Sockets.csproj#L382-L402 to include System.Console and then just use Console.WriteLine.

**Comment by stephentoub** [comment]
What's the test btw?  Is it some existing test that's failing for you without any changes to System.Net.Sockets?

**Comment by nbaztec** [comment]
Thanks I'll try that, it's this test: https://mc.dot.net/#/user/nbaztec/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/da29f1b45f466d29d0049f0c02535bb1a668fbde/workItem/System.Net.Sockets.Tests

basically I need to see the output of DNS resolution since all the other assertions are passing.

**Comment by nbaztec** [comment]
Sadly I still couldn't get the console output after adding `System.Console`
https://mc.dot.net/#/user/nbaztec/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/01404175cb26a27435382afae2155512c1da4127/workItem/System.Net.Sockets.Tests/wilogs

**Comment by stephentoub** [comment]
I see output like:
```
2018-10-07 16:01:42,330: INFO: proc(55): run_and_log_output: Output: [mlen: 1
2018-10-07 16:01:42,330: INFO: proc(55): run_and_log_output: Output: 127.0.0.1 InterNetwork InterNetworkV6
```
in those logs... what's not working?

**Comment by nbaztec** [comment]
I see, interestingly all the log outputs are missing from `Windows.10.Amd64.ClientRS4.Open-x86:Release` as if it uses an entirely different codebase.

**Comment by ViktorHofer** [comment]
That's .NET Framework. If your project doesn't have a netfx configuration it will just run the official one from the GAC.

**Comment by nbaztec** [comment]
Interesting, I guessed so but wasn't sure. I don't think I will be able to patch this bug it the original GAC, as such what might be the potential solutions - we can take this discussion to #32504 since the originnal answer is sufficient, just my code is never executed.

This bug is single handedly bothering me since a week now and I'm unable to come to a solution.
Thanks for the help.
