### ISSUE TITLE
Add a code coverage bot to PRs

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#32678]
After the migration to Coverlet is done we should consider adding a code coverage bot that runs on PRs. There's also the option to fail the job if the coverage decreased.

Example from https://github.com/tonerdo/coverlet/pull/105:

![image](https://user-images.githubusercontent.com/7412651/46586022-b4065400-ca78-11e8-9931-3f36358652ce.png)

cc @danmosemsft @pjanotti

**Comment by ViktorHofer** [comment]
cc @danmosemsft @pjanotti

**Comment by ericstj** [comment]
@safern mentioned that we need codecov builds for every PR first to do this.  Right now that is pending a story for using secrets in public PR builds.

**Comment by ViktorHofer** [comment]
Closing in favor of https://github.com/dotnet/corefx/issues/34886
