### ISSUE TITLE
[CipherMode.CFB / TripleDES and AES ] Exception caught:  "Specified cipher mode is not valid for this algorithm"

### ISSUE THREAD

**Issue by gleocadie** [dotnet/corefx#32689]
I have an application that runs on Windows and I'm in the process of migrating it to .Net Core on Linux.
While testing it on a server, I got this error:

`Exception caught: 'System.Security.CryptographicException in System.Security.Cryptography.Primitives.dll' ("Specified cipher mode is not valid for this algorithm")`

We cipher and decipher data using TripleDES and AES algorithms using the CFB mode (default).

I saw that the CFB mode is not implemented for Unix platforms (neither for Windows, nor for MacOS). https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Algorithms/src/Internal/Cryptography/TripleDesImplementation.Unix.cs#L22

Currently, on .Net framework:
- For 3DES, the CFB mode is forced 8 (the feedback size in bits) https://referencesource.microsoft.com/#mscorlib/system/security/cryptography/tripledescryptoserviceprovider.cs,77
- For AES (which is based on CAPI symmetric encryption algorithm), the default CFB mode is 8 https://referencesource.microsoft.com/#System.Core/System/Security/Cryptography/AesCryptoServiceProvider.cs,54 , but can be changed. (It seems that CAPI does not support a feedback size greater than 64. as per the comment https://referencesource.microsoft.com/#System.Core/System/Security/Cryptography/AesCryptoServiceProvider.cs,53)
 
What is the plan about implementing those modes? (I saw that OpenSSL implements the different modes)

I'm about to propose a PR for Unix where I add all the bindings for those algorithms with CFB modes supported by OpenSSL. What do you think ?

This is related to https://github.com/dotnet/corefx/issues/4647 .

**Comment by vcsjones** [comment]
Can you clarify what you mean by "(default)" in:
>We cipher and decipher data using TripleDES and AES algorithms using the CFB mode (default).

The default mode has always been CBC as far as I am aware. Perhaps you mean a default for something else.

I think this is technically possible, all platforms appear to support it, being CNG, Security Transforms, and OpenSSL. At least for AES. I'm uncertain about 3DES for Security Transforms.

>I'm about to propose a PR for Unix where I add all the bindings for those algorithms with CFB modes supported by OpenSSL. What do you think ?

My humble opinion is that the crypto primitive story in .NET Core is somewhat fragmented right now across platforms. I would not want to continue that trend. We should only do this unless there is a plan to do Windows/CNG and macOS/Security Transforms as well.

I think, technically, we would also need an API proposal to add the mode back to `CipherMode`, or do something completely different like we did with AES GCM/CCM.

**Comment by bartonjs** [comment]
This isn't really "related" to #4647 as it's that same issue with some scenario justification.  I'm closing this one in favor of that one (please move discussion to that issue).

> I'm about to propose a PR for Unix where I add all the bindings for those algorithms with CFB modes supported by OpenSSL. 

Like @vcsjones said, such a PR would need to add it to all platforms where it's possible to do so; not just one of them.

> I think, technically, we would also need an API proposal to add the mode back to CipherMode,

They're already there, just marked as `[EditorBrowsable(Never)}` :smile:.
