### ISSUE TITLE
What is the rationale behind quietly ignoring Environment.SetEnvironmentVariable calls with targets User or Machine on Unix-like platforms?

### ISSUE THREAD

**Issue by mklement0** [dotnet/corefx#32685]
_Persistently_ updating environment variables is (at least currently) only supported on _Windows_, which means passing the `User` and `Machine` enumeration values to `Environment.SetEnvironmentVariable` are _unsupported_ on macOS and Linux.

Surprisingly, however, doing the latter doesn't cause an _exception_, but is _quietly ignored_ (an effective no-op).

Even though this [behavior is documented](https://docs.microsoft.com/en-us/dotnet/api/system.environment.setenvironmentvariable?view=netcore-2.1#System_Environment_SetEnvironmentVariable_System_String_System_String_System_EnvironmentVariableTarget), I wonder:

* what the rationale for this behavior is, given that as an API user you generally want to be notified of attempts to use functionality that is unsupported on a given platform.

* whether the behavior can be changed.

**Comment by jkotas** [comment]
See the discussion in https://github.com/dotnet/corefx/issues/20147

**Comment by mklement0** [comment]
Thanks, @jkotas.

Reading the discussion and the linked issues I gather that the plan for addressing this is the following, correct?:

* Report a [_compile-time_ warning](https://github.com/dotnet/platform-compat/issues/122), 
* but _no runtime_ PNE

**Comment by jkotas** [comment]
Right, that is the current plan.

**Comment by mklement0** [comment]
I see, thanks.

Is the reason for not throwing a PNSE at runtime compatibility with Mono?

Note that not all CoreFx consumers are _compiled_ languages, so calls from PowerShell code, for instance, would not see the compile-time warning. A cmdlet that wraps this API, such as proposed in https://github.com/PowerShell/PowerShell/issues/5340#issuecomment-427706858, is then faced with the following - suboptimal - choices:

* Accept the quiet no-op runtime behavior on unsupported platforms.

* Duplicate the compile-time warnings by turning them into PowerShell errors / warnings.

**Comment by jkotas** [comment]
> Is the reason for not throwing a PNSE at runtime compatibility with Mono?

It is one of the reasons. Even without Mono in the equation, no-op seemed like the right choice because of it makes more code "just work" (https://github.com/dotnet/corefx/issues/20147#issuecomment-303501844). There are other methods like this in the framework that we choose to turn into no-op on non-Windows platforms. The choices for these Windows-specific methods are always sub-optimal. Ideally, they would be in Windows-specific assembly.

Changing the behavior to throw PNSE would be a breaking change.

**Comment by mklement0** [comment]
Thanks, @jkotas.

Understood re breaking change, so I'm closing this.

Sounds like moving such overloads / methods into Windows-specific assemblies is the way to go in the future.

In cases where this is impractical, please reconsider the current "just works" approach, because its proper name should be "doesn't work, but pretends that it does", which I think is more harmful than throwing an exception.
(A compiler warning, which is helpful irrespective of the runtime behavior, can mitigate this, but those warnings aren't always seen, e.g., in PowerShell).

**Comment by danmosemsft** [comment]
Arguably it could at least update the process environment, since in some cases this would happen on Windows (depends on how many apps respect the WM_SETTINGCHANGE message)

**Comment by mklement0** [comment]
@danmosemsft: 

But the method call _itself_ currently doesn't update the process-level variable _directly_, so wouldn't what you're proposing be a breaking change?

On a side note: It has always struck me as inconvenient that you need a _second_ call just to make the value effective in the current process as well.

Perhaps it's worth consider extending the enumeration with `UserAndProcess` and `MachineAndProcess` values that set both the persisted and the current-process value.
