### ISSUE TITLE
CurlHandler statusCode parsing - Error cases

### ISSUE THREAD

**Issue by kapilash** [dotnet/corefx#3269]
CurlHandler does StatusCode parsing in the http response message.
 Verify that CurlHandler behavior is identical to WinHttpHandler in case of negative scenarios. CurlHandler throws parse exception if status code in the Http response is not a valid status code.

**Comment by vijaykota** [comment]
Moving to RTM since this doesn't meet RC1 bug bar

**Comment by kapilash** [comment]
Fixed via #4131
