### ISSUE TITLE
CurrentCultureIgnoreCase string compare return false with Culture "en-US-POSIX"

### ISSUE THREAD

**Issue by wli3** [dotnet/corefx#32699]
Please close if this is by design of "en-US-POSIX". I want to make sure this is intentional. It is odd that a culture with prefix "en-US" will return false when comparing  "nukeeper" and "NuKeeper"

```c#
public static void Main(string[] args)
{
    CultureInfo.CurrentCulture = new CultureInfo("en-US-POSIX");
    Console.WriteLine("CurrentCulture is {0}.", CultureInfo.CurrentCulture.Name);
    Console.WriteLine(string.Compare("nukeeper", "NuKeeper", StringComparison.CurrentCultureIgnoreCase) == 0);
}
```

**Comment by stephentoub** [comment]
cc: @tarekgh 

(Tarek, is there a FAQ somewhere about POSIX/C culture handling that we can point people to?  The question seems to come up a lot.)

**Comment by tarekgh** [comment]
@wli3 please look at the comment on the issue https://github.com/dotnet/corefx/issues/32250#issuecomment-420749205

@stephentoub I'll log issue to get this in the official documentation instead.

**Comment by tarekgh** [comment]
logged the issue https://github.com/dotnet/docs/issues/8179

**Comment by tarekgh** [comment]
@nguerrera this is a good idea. if you have a contact from WSL we can contact them.

**Comment by nguerrera** [comment]
cc @bitcrazed

**Comment by nguerrera** [comment]
What is it about WSL that causes it to have this culture by default? An environment variable?
