### ISSUE TITLE
CurlHandler Multithreading - thread safety of underlying SSL library

### ISSUE THREAD

**Issue by kapilash** [dotnet/corefx#3270]
[Lib Curl's documentation](http://curl.haxx.se/libcurl/c/threadsafe.html) has some suggestions for safe use of the library in multi threaded context. The recommendations for thread safe use of openssl are probably, still relevant.
This is a tracking issue for the same.

**Comment by stephentoub** [comment]
The OpenSSL initialization is already handled:
https://github.com/dotnet/corefx/blob/master/src/Common/src/Interop/Unix/System.Net.Http.Native/Interop.Initialization.cs#L33-L34

**Comment by kapilash** [comment]
Oh thanks. Then we can close this, I believe.
