### ISSUE TITLE
Special directories / GetFolderPath on macOS

### ISSUE THREAD

**Issue by PreferLinux** [dotnet/corefx#32708]
https://github.com/dotnet/corefx/blob/a1db302fc7b876675618d9aa4d6d53989510b97c/src/System.Runtime.Extensions/src/System/Environment.Unix.cs#L101
The problem is that on recent versions of macOS, most of `/usr` is protected and cannot be modified, even by root – returning `/usr/share` is totally useless for getting somewhere to store application data. I would suggest returning `/usr/local/share` on macOS.

**Comment by danmosemsft** [comment]
Has Mono/Xamarin addressed this?

**Comment by danmosemsft** [comment]
Well, if there is consensus over there, feel free to offer a PR here also if you would like.

**Comment by Anipik** [comment]
Copy of https://github.com/dotnet/corefx/issues/12628
