### ISSUE TITLE
Environment.SpecialFolder.LocalApplicationData returns an empty string on Linux

### ISSUE THREAD

**Issue by Evangelink** [dotnet/corefx#32716]
Hi folks,

We are relying on `Environment.SpecialFolder.LocalApplicationData` to copy some targets that will be picked-up by `msbuild` or `dotnet` and it seems like we can end up in cases where `Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData)` returns an empty string on Linux. 

As far as I can see [here](https://github.com/dotnet/corefx/blob/0102f69b4274342f5b3d2b6b29827a734369da6d/src/System.Runtime.Extensions/src/System/Environment.Unix.cs#L139) this can happen when both the `home` and `XDG_DATA_HOME` environment variables are not set.

As I don't really know if there is a problem or not I will ask this "stupid" question: should we assume this is a bug or shall we update our code to handle the case and in which case what's the fallback mechanism to be able to create such folder?

Usage on our code: [SonarSource/sonar-scanner-msbuild - MsBuildPathSettings.cs#L31](https://github.com/SonarSource/sonar-scanner-msbuild/blob/master/src/SonarScanner.MSBuild.Common/MsBuildPathSettings.cs#L31)
Related posts: #29354, #22049

**Comment by danmosemsft** [comment]
If we return empty I think we should try harder to not return empty.

That would mean that this 
https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/Common/src/System/IO/PersistedFiles.Unix.cs#L83
is returning empty/null for some reason. Is it possible to debug?

Looking at Mono it has a similar pattern
https://github.com/mono/mono/blob/c6b8cecb9d6c547d7c5d58721cbf472caa3aae9f/mcs/class/corlib/System/Environment.cs#L629 which ultimately seems to get to https://github.com/mono/mono/blob/c5b88ec4f323f2bdb7c7d0a595ece28dae66579c/mono/eglib/gmisc-unix.c#L126 which the code above may have been written to mimic.

**Comment by Evangelink** [comment]
I don't know if this info can be of any use for you but the `$HOME` variable was actually set on the machine. Setting the `XDG_DATA_HOME` fixed the issue.

**Comment by tmds** [comment]
@Evangelink the reason you get string.Empty is because the folder doesn't exist on your system. You can pass `SpecialFolderOption.Create` to create it.

@danmosemsft after looking at the code, there is a case where GetHomeDirectory can return null. This happens when HOME and XDG_DATA_HOME are unset and /etc/passwd has no entry for the user. When home is null, `GetFolderPath` throws on the `Path.Combine`. I'll make a PR to fix this one.

**Comment by tmds** [comment]
@Evangelink are you able to solve the issue using the SpecialFolderOption flags (without having to set XDG_DATA_HOME)?

**Comment by Evangelink** [comment]
@tmds Sorry I haven't been able to make a test yet. As setting the environment variable solved the immediate issue on the customer side we lowered a bit the priority of the ticket.

I will keep you posted with updates but you can feel free to close the ticket when you want (I see you already merged the bug fix).

**Comment by tmds** [comment]
The bug fix was for an unhandled case, different from yours.
I think in your case, the `$HOME/.local/share` folder doesn't exist yet, which causes `GetFolderPath` to return `string.Empty`.

I don't have bug closing permissions.

**Comment by tmds** [comment]
@karelz this can be closed.

**Comment by danmosemsft** [comment]
Thanks @tmds
