### ISSUE TITLE
API to detect the bound version of OpenSSL

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#32718]
Since SafeEvpPKeyHandle exists to allow interop with OpenSSL, it would be good for callers to be able to determine if they are using the same library/version of OpenSSL that we are.

```C#
    public sealed partial class SafeEvpPKeyHandle
    {
        // The result of SSLeay() (OpenSSL 1.0.2) or OpenSSL_version() (OpenSSL 1.1.x)
        public static int OpenSslVersion { get; }
    }
```

Discussion points:
* The native API is Unix C-long, so 32-bit on 32-bit, 64-bit on 64-bit.
* So, `int`, `uint`, `long`, or `ulong`?
* The version number contains detail we can't expose via System.Version
* Callers are only expected to do `==`

**Comment by stephentoub** [comment]
> SafeEvpPKeyHandle

Seems like a strange place to put it.  Could we put it on another type with OpenSSL in the name, that's not a SafeHandle, etc.?  Even if it meant introducing a new type?

> The version number contains detail we can't expose via System.Version

But they can be exposed in an int/long?

**Comment by vcsjones** [comment]
>But they can be exposed in an int/long?

They cram a bunch of information in different bits. e.g.:

```
0x000906023 == 0.9.6b beta 3
```

**Comment by stephentoub** [comment]
> They cram a bunch of information in different bits

I see. Thanks.

**Comment by terrajobst** [comment]
Looks good, but we should make the  return type `long`.
