### ISSUE TITLE
System.IndexOutOfRangeException in PhysicalAddress.Parse()

### ISSUE THREAD

**Issue by AtosNicoS** [dotnet/corefx#32713]
When I call `PhysicalAddress.Parse("33-3");` I get an undocumented `System.IndexOutOfRangeException: 'Index was outside the bounds of the array.'`. I assume this is a bug in the underlying code. The implementation of the Parse method seems to write to a place in a buffer where it is not allowed to.

This is the current implementation:
https://github.com/dotnet/corefx/blob/6ffca612323448f1488a6c63b86b69611b4286d9/src/System.Net.NetworkInformation/src/System/Net/NetworkInformation/PhysicalAddress.cs#L118

This is the current documentation:
https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.physicaladdress.parse

*Note:*
There was some changes in the code recently. I do not know if those were just general changes or already fixed the issue.

**Comment by stephentoub** [comment]
Thanks for the bug report.  This looks like a long-standing bug (in .NET Framework as well), where Parse will  incorrectly throws IndexOutOfRangeException instead of FormatException if the string contains dashes but the last hex number is missing a digit.  It looks like there's code that's trying to handle that case, but it's wrong.

**Comment by karelz** [comment]
I think it would be best to check for input size directly at the beginning when we detect dashed-format:
https://github.com/dotnet/corefx/blob/6ffca612323448f1488a6c63b86b69611b4286d9/src/System.Net.NetworkInformation/src/System/Net/NetworkInformation/PhysicalAddress.cs#L132-L133

Should be fairly straightforward

**Comment by Smartis2812** [comment]
I'm not sure about the expected behavior here?
The input `"33-3"` is definitely not a valid Mac Address so it should throw a `FormatException` or?

**Comment by karelz** [comment]
Thanks @Smartis2812 for picking it up!
I sent you collaborator invite - once you accept, ping me here and we can assign it to you (to keep track it is taken). Assigning to myself temporarily.
Note: Becoming repo collaborator will auto-subscribe you to all notifications (500+ per day). We recommend to switch the setting to "Not Watching" - which will notify you only on issues where you are mentioned, you reply or explicitly subscribe to.

**Comment by AtosNicoS** [comment]
Thanks for the extremly fast response to the issue!

I am a bit confused why you are giving @Smartis2812 collaborator access to the repository for his first time contribution? You could simply just merge the PR, the collaboration is not required. A collaborator is allowed to do a lot with the git project:
https://help.github.com/articles/permission-levels-for-a-user-account-repository/#collaborator-access-on-a-repository-owned-by-a-user-account
I might missunderstand, so please clarify. :)

**Comment by karelz** [comment]
@AtosNicoS to assign and issue to someone who didn't create it, that person has to be collaborator. If you know of better ways, let us know.

**Comment by AtosNicoS** [comment]
Yes and that is for a good reason. You should (in general) not assign an issue to a non-project member. Because he is not the one who decides whether the patch gets merged or not. You assign the PR to someone who will review the patch from the internal team. There is no reason for assigning a stranger to an issue.

The drawback of this is, that this user account gets *full access to this microsoft repository*. I do not know how many of those collaborations you gave out, but I recommend to revoke all of them and also check the repository for any suspicious commits. Collaborators could introduce crafted security bugs, point release tags to wrong commit hashes or simply remove security patches.

You do not want to give out collaboration access to anyone not 100% trusted by the project owner, which is microsoft in that case.

I suggest that you better assign the issue to yourself, review and test the patch and merge it. You can credit the patch creator in the changelog, if you wish.

As always: Correct me if I am wrong. Maybe my understanding is not up to date and github permissions work different now.

**Comment by AtosNicoS** [comment]
Alright, I was not aware of the read-only permission setting for organisations. Thanks for clarifying :)
