### ISSUE TITLE
RSA.SignatureAlgorithm should return W3.org URI

### ISSUE THREAD

**Issue by ddrysdale** [dotnet/corefx#32728]
I believe RSA.cs is incorrectly returning "RSA" for SignatureAlgorithm, where the correct value should be "http://www.w3.org/2000/09/xmldsig#rsa-sha1". That is the value returned by this class in .NET Framework. 

The current implementation:

https://github.com/dotnet/corefx/blob/a0cfc0492df974ebb2b9293e4d5640e1c1505263/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/RSA.cs#L641

Documentation of the class lists the field returning the W3C URI. 
https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.asymmetricalgorithm.signaturealgorithm?view=netcore-2.1

**Comment by vcsjones** [comment]
>I believe RSA.cs is incorrectly returning "RSA" for SignatureAlgorithm, where the correct value should be "http://www.w3.org/2000/09/xmldsig#rsa-sha1".

That would be for `RSACryptoServiceProvider`. The newer implementation of RSA on the .NET Framework, `RSACng`, also returns just "RSA" like .NET Core:

```csharp
var rsa = new RSACng();
Console.WriteLine(rsa.SignatureAlgorithm); // RSA
```

That `SignatureAlgorithm` returned XMLDSig URI identifiers is a bit strange to me. The RSA classes can of course be used for things other than XMLDSig.

So .NET Core's behavior matches `RSACng`, not `RSACryptoServiceProvider`. [The reference source][2] for `RSACryptoServiceProvider` also has this interesting comment:

>// For new derived RSA classes, we'll just return "RSA" which is analagous to what ECDsa
>// and ECDiffieHellman do.
>//
>// Note that for compat, RSACryptoServiceProvider still overrides and returns RSA-PKCS1-KEYEX 
>// and http://www.w3.org/2000/09/xmldsig#rsa-sha1

So it seems that the behavior of returning an XML Security URI is being preserved for compatibility purposes.

>Documentation of the class lists the field returning the W3C URI.

That's for the base `AsymmetricAlgorithm`. I think the documentation is saying that an inheritor can return a URI, if they want.

[The documentation for .NET Core's RSA class][1] says it returns "RSA":
>Returns "RSA".

[1]: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsa.signaturealgorithm?view=netcore-2.1
[2]: https://referencesource.microsoft.com/#mscorlib/system/security/cryptography/rsa.cs,243

**Comment by bartonjs** [comment]
The documentation on AsymmetricAlgorithm gives an example of a return value for the W3C identifier equivalent to `id-sha1WithRsaEncryption` in the Examples section.  I don't see anything in the documentation that says that it will necessarily be a W3C xmldsig value.

The SignatureAlgorithm property is not a value that can be reasoned about; because the "SHA1" portion isn't dictated by the class, it's a caller choice during Sign or Verify.  There's really no reason to ever read it.
