### ISSUE TITLE
Explain issues when removing or changing a strong name in an assembly

### ISSUE THREAD

**Issue by peteroupc** [dotnet/corefx#32733]
In the [strong name signing](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md) document, explain what issues can occur when either&mdash;

- a strong name is removed from later versions of an assembly when previous versions were strong-named, or
- a different strong name is used in later versions of an assembly than in previous versions,

besides the fact that removing a strong name is a breaking change and that changing a strong-name may be.

**Comment by karelz** [comment]
@peteroupc what kind of potential issues are you looking for? Are you concerned about .NET Framework or .NET Core or .NET Standard?
If the identity is changed, all upstack apps/libraries need to be updated with the new identity. It may break code which checks the identity.

cc @terrajobst @ericstj

**Comment by peteroupc** [comment]
Both.  A third-party library seeks to incorporate my repository by reference (see [this issue](https://github.com/abergs/fido2-net-lib/issues/7)), but my library (which contains .NET Standard and .NET Framework 2.0 and 4.0 versions) is configured to compile with a strong name that is not included in the repository.  That is why, for the next _major_ version, I am considering either making the library un-strong-named, or changing the strong name key to a public value.

**Comment by karelz** [comment]
If you are deciding if to drop strong-name, or just publish the strong-name key, then I think the article you link has link to help with that: https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies#why-strong-name-your-assemblies
Is that not sufficient?

**Comment by karelz** [comment]
Changing library strong-name is separate topic IMO. It is a breaking change on its own and you have to assess to possible outcome - it depends how other libraries/apps use your library.

[The article](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies#why-strong-name-your-assemblies) describes the advantages of having strong-name. If you are ok without them, then go without strong-name. If you need any of them, keep it strong-name and publish your private key.

Or am I still missing your core question?

**Comment by peteroupc** [comment]
If the desire is to change a library's strong-name key, and to publish that library's new strong-name key, are there other issues in doing so (besides the fact that it's a breaking change) compared to keeping that library's strong-name key (with or without publishing that key)?

**Comment by ericstj** [comment]
I wonder if you could use [AssemblySignatureKey](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assemblysignaturekeyattribute?view=netframework-4.7.2) to keep your old identity but do the real signing with a publicly available open source key pair?  I know that this was how the desktop kept the old identities of our assemblies but started using different (larger) keys.

**Comment by peteroupc** [comment]
@ericstj : Is using the AssemblySignatureKeyAttribute to migrate a library to use a stronger key pair backward-compatible?  What if the library also has .NET 2.0 and 4.0 versions, not just a .NET Standard version?

**Comment by karelz** [comment]
The attribute was introduced in .NET 4.5: https://apisof.net/catalog/System.Reflection.AssemblySignatureKeyAttribute

I think the original question is answered, closing.

**Comment by peteroupc** [comment]
> 
> 
> The attribute was introduced in .NET 4.5: https://apisof.net/catalog/System.Reflection.AssemblySignatureKeyAttribute
> 
> I think the original question is answered, closing.

It's not answered unfortunately.  I make it clearer:

Assume that a library with .NET Standard, .NET 2.0, and .NET 4.0 versions is strong-named with an old version of a strong-name key.  If that library then decides to migrate to a new strong-name key and publish that key, but only for the .NET Standard version of the library, are there backward-compatibility issues in doing so?

**Comment by karelz** [comment]
Yes, there are backwards compatibility issues in such case - everyone needs to retarget and rebuild.
