### ISSUE TITLE
.net core 2.1 Chinese garbled problem

### ISSUE THREAD

**Issue by cuicuicuinice** [dotnet/corefx#32736]
.net core的webapi中文打印是乱码形式，
而且Encoding.RegisterProvider(CodePagesEncodingProvider.Instance)中的CodePagesEncodingProvider也不支持了。
这个问题的解决方案是被优化了变得不一样了吗？

**Comment by cuicuicuinice** [comment]
哇   非常非常感谢你的回答    看到你突然回复我，我才意识到两地是有时间差的，你回复我的时候中国四川已经12点40分了

这个问题已经解决了，我是用的webapi，框架.core2.1的，要想使用CodePagesEncodingProvider需要引入framwork的程序集System.Text.Encoding.CodePages

**Comment by cuicuicuinice** [comment]
> @cuicuicuinice
> 
> I am not fully understand the issue, but I want to say, Encoding.RegisterProvider(CodePagesEncodingProvider.Instance) is supported in .net core and many people already using it. I am not sure if your problem is just with webapi or it is with .net core in general. if you have more information or repro to share that will be helpful. The encoding behavior in .net core when using the CodePagesEncodingProvider should be exact as the full framework.



哇 非常非常感谢你的回答 看到你突然回复我，我才意识到两地是有时间差的，你回复我的时候中国四川已经12点40分了

这个问题已经解决了，我是用的webapi，框架.core2.1的，要想使用CodePagesEncodingProvider需要引入framwork的程序集System.Text.Encoding.CodePages

**Comment by cuicuicuinice** [comment]
> @cuicuicuinice
> 
> I am not fully understand the issue, but I want to say, Encoding.RegisterProvider(CodePagesEncodingProvider.Instance) is supported in .net core and many people already using it. I am not sure if your problem is just with webapi or it is with .net core in general. if you have more information or repro to share that will be helpful. The encoding behavior in .net core when using the CodePagesEncodingProvider should be exact as the full framework.

The following is Google Translate, English is not very good

Wow, thank you very much for your answer. Seeing that you suddenly responded to me, I realized that there is a time difference between the two places. When you reply to me, China’s Sichuan is already 12:40.

This problem has been solved, I am using webapi, framework.core2.1, to use the CodePagesEncodingProvider to introduce the assembly of framwork System.Text.Encoding.CodePages

**Comment by cuicuicuinice** [comment]
> @cuicuicuinice
> 
> I am not fully understand the issue, but I want to say, Encoding.RegisterProvider(CodePagesEncodingProvider.Instance) is supported in .net core and many people already using it. I am not sure if your problem is just with webapi or it is with .net core in general. if you have more information or repro to share that will be helpful. The encoding behavior in .net core when using the CodePagesEncodingProvider should be exact as the full framework.

哇 非常非常感谢你的回复，当看到你的回复我才意识到我们两地有时间差，昨天你回复我的时间，在中国四川已经是凌晨12点40了
Wow, thank you very much for your reply. When I saw your reply, I realized that we have a time difference between the two places. Yesterday you responded to my time. It was already at 12:40 in Sichuan, China.

![image](https://user-images.githubusercontent.com/34976688/46813571-89ced200-cda9-11e8-8207-3c72aff3b5fe.png)

我用的是,net core2.1的webapi,这里无法加载System.Text.Encoding.CodePage这个程序集，所以导致使用CodePageEncodingProvider。
I am using the webapi of net core2.1. I can't load the System.Text.Encoding.CodePage assembly here, so I am using CodePageEncodingProvider.

**Comment by svick** [comment]
> Reference assemblies should not be loaded for execution.

Are you doing something special to load the assembly (like `Assembly.Load`)? What is the call stack of the exception?

**Comment by tarekgh** [comment]
Thanks @cuicuicuinice for your reply. it would be helpful is you can share a sample project demonstrating the issue. this can be easier to point quickly what is wrong in your project.  @svick is right that the reference assemblies are intended to be used during the compilation but not at run time.

**Comment by cuicuicuinice** [comment]
> Thanks @cuicuicuinice for your reply. it would be helpful if you can share a sample project demonstrating the problem. This can be easier to point quickly what is wrong in your project. @svick is right that the reference assemblies are intended to be used during the compilation but not at run time.

![image](https://user-images.githubusercontent.com/34976688/46843912-69cdfb80-ce07-11e8-84fe-c96a626e7a81.png)
在.net core 2.1 webapi我引入的程序集，
然后引入命名空间using System.Text;
然后在启动的Main函数中使用Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
然后程序一运行，就会报错，报错内容如下：
![image](https://user-images.githubusercontent.com/34976688/46844091-2758ee80-ce08-11e8-9b0b-f5b43fe4f138.png)





![image](https://user-images.githubusercontent.com/34976688/46843912-69cdfb80-ce07-11e8-84fe-c96a626e7a81.png)
The assembly I introduced in .net core 2.1 webapi,
Then introduce the namespace using System.Text;
Then use Encoding.RegisterProvider(CodePagesEncodingProvider.Instance) in the main function that is started;
Then when the program runs, it will report an error and the error message is as follows:
![image](https://user-images.githubusercontent.com/34976688/46844095-29bb4880-ce08-11e8-89b1-e9d5f89d6ba1.png)

**Comment by cuicuicuinice** [comment]
> > Reference assemblies should not be loaded for execution.
> 
> According to this message, you are loading the wrong assembly.
> 
> Are you doing something special to load the assembly (like `Assembly.Load`)? What is the call stack of the exception?

非常感谢你的回复，此时是中国四川早上10点19
Thank you very much for your reply, this time is 10:19 in Sichuan, China.

![image](https://user-images.githubusercontent.com/34976688/46843912-69cdfb80-ce07-11e8-84fe-c96a626e7a81.png)
在.net core 2.1 webapi我引入的程序集，
然后引入命名空间using System.Text;
然后在启动的Main函数中使用Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
然后程序一运行，就会报错，报错内容如下：
![image](https://user-images.githubusercontent.com/34976688/46844091-2758ee80-ce08-11e8-9b0b-f5b43fe4f138.png)





![image](https://user-images.githubusercontent.com/34976688/46843912-69cdfb80-ce07-11e8-84fe-c96a626e7a81.png)
The assembly I introduced in .net core 2.1 webapi,
Then introduce the namespace using System.Text;
Then use Encoding.RegisterProvider(CodePagesEncodingProvider.Instance) in the main function that is started;
Then when the program runs, it will report an error and the error message is as follows:
![image](https://user-images.githubusercontent.com/34976688/46844095-29bb4880-ce08-11e8-89b1-e9d5f89d6ba1.png)

**Comment by lextm** [comment]
You are supposed to add a NuGet package reference of `System.Text.Encoding.CodePages`. For example, in your `StaicFileServer.csproj` file,
```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.x.x" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="4.5.0" />
  </ItemGroup>
```
Please remove all other references of `System.Text.Encoding.CodePages` you created earlier, as that linked to an invalid reference assembly.

> 你添加引用的方式错了，才导致这个异常。请删除当前对于`System.Text.Encoding.CodePages`的引用，然后修改你的工程文件使用上面`PackageReference`的方式。

**Comment by tarekgh** [comment]
@lextm is right. you should  use the NuGet System.Text.Encoding.CodePages reference and remove the manual references you added to your project. I am closing the issue but feel free to reply back with any question and we'll be happy to help.

**Comment by cuicuicuinice** [comment]
> @lextm is right. you should use the NuGet System.Text.Encoding.CodePages reference and remove the manual references you added to your project. I am closing the issue but feel free to reply back with any question and we'll be happy to help.

Thank you very much.@lextm is right.

**Comment by cuicuicuinice** [comment]
> You are supposed to add a NuGet package reference of `System.Text.Encoding.CodePages`. For example, in your `StaicFileServer.csproj` file,
> 
> ```
>   <ItemGroup>
>     <PackageReference Include="Microsoft.AspNetCore.All" Version="2.x.x" />
>     <PackageReference Include="System.Text.Encoding.CodePages" Version="4.5.0" />
>   </ItemGroup>
> ```
> Please remove all other references of `System.Text.Encoding.CodePages` you created earlier, as that linked to an invalid reference assembly.
> 
> > 你添加引用的方式错了，才导致这个异常。请删除当前对于`System.Text.Encoding.CodePages`的引用，然后修改你的工程文件使用上面`PackageReference`的方式。

You are right!Thank you!
