### ISSUE TITLE
Consider adding back AppDomain.ActivationContext

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#32735]
Even though .NETCore doesn't support ClickOnce activation we should consider adding back this API to enable desktop assembly reuse.  The API returns null for non-ClickOnce apps.

We can decide how much of the ActivationContext class and its depednencies we decide to expose based on usage.  I suspect we'll want to also expose ApplicationIdentity and a few others, just based on usage.  I imagine all of these will be dummy types that just enable code to JIT without ever really providing an instance of them since ClickOnce isn't supported.

/cc @danmosemsft @jkotas

**Comment by jkotas** [comment]
We see this being used in the license checking code for 3rd party paid controls. Is this the only thing preventing the license check from succeeding?

**Comment by ericstj** [comment]
Can't be sure until we fix it.  Looking through the code nothing stands out as a red flag, we have LicenseManager: https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.ComponentModel.TypeConverter/src/System/ComponentModel/LicenseManager.cs

In the specific case of this API use it was somewhat unrelated to the license checking, the library itself had a "free mode" when running under a specific click once demo application, and this check was determining if the app was that demo application.

**Comment by danmosemsft** [comment]
@jeffschwMSFT

**Comment by jkotas** [comment]
> the library itself had a "free mode" when running under a specific click once demo application

We do plan to support ClickOnce distributon option for .NET Core 3 UI apps, but without tightly coupling ClickOnce with the .NET Core runtime. Is this library want to have ClickOnce "free mode" that runs on .NET Core too? How are they going to do it when these APIs are dummies? It may be useful to talk to the library vendor about their plan wrt. NET Core.

**Comment by ericstj** [comment]
> Will this library want to have ClickOnce "free mode" that runs on .NET Core too? How are they going to do it when these APIs are dummies? It may be useful to talk to the library vendor about their plan wrt. NET Core.

Sure, I can help connect the folks who are driving that ClickOnce decision with this library vendor if they reach out offline.  I can see other strategies (including some already in use by this library) that would work for that scenario if they wanted a "free mode" .netcore app without relying on this API.

With respect to this specific API it's tied to the CO activation and I think a reasonable first step is to add back the getter and have it return null if manifest based activation isn't supported on .NETCore.  That helps make more existing desktop libraries "just work" on .netcore.  @jkotas are you saying we should not even do that?

**Comment by jkotas** [comment]
Two thoughts on this:
- It would be odd situation to support ClickOnce as deployment tech and have ClickOnce-specific APIs in the surface that do not work. I expect that if we add these ClickOnce-specific APIs to the surface, we will have to fill the implementation with something that works too.
- I understand we are doing quick hacks to make stuff work right now. However, we need to get clarity about who is on the hook to provide support for the existing big paid libraries on .NET Core. I have doubts that the existing big paid libraries are going to just work on .NET Core 3.0 (unless we start on a very expensive compat quirking journey), and that they will need recompilation and some fixes anyway.
> a reasonable first step is to add back the getter and have it return null if manifest based activation isn't supported on .NETCore
I think that is ok if it helps to make progress. What is the exact surface you believe we need to add to unblock this? It sounds like this needs to be the getter, and several of types and bunch of methods on these types.

**Comment by ericstj** [comment]
> I expect that if we add these ClickOnce-specific APIs to the surface, we will have to fill the implementation with something that works too.

Absolutely: real implementations are always better than stubs.  I was under the impression this tech wasn't coming back at all but obviously if we bring it we should make these  APIs work normally.

The minimum needed for this issue would be:

- AppDomain.get_ActivationContext
- ActivationContext
- ActivationContext.get_ApplicationIdentity

Whoever does this work should also look at ActivationContext to understand if there is other low-hanging fruit.

**Comment by jkotas** [comment]
`get_ApplicationIdentity` returns `ApplicationIdentity` so that one has to be added too, with some methods at least. Right?

**Comment by ericstj** [comment]
Interesting, APIPort missed that.  It uses ApplicationIdentity.get_CodeBase.  Here's the gist of the code that's failing:
```
AppDomain.CurrentDomain?.ActivationContext?.Identity?.CodeBase == "<someUrl>"
```

**Comment by ericstj** [comment]
@rido-min @diverdan92 do you have any data around customers hitting this issue?

**Comment by Anipik** [comment]
me and @ericstj looked at this issue. In order to port ```ActivationContext```, we need to move down the ```ApplicationIdentity``` from ```System.Security.Permissions`` to corelib.

@danmosemsft  @terrajobst should we proceed with this or mark it for future ?

**Comment by jkotas** [comment]
I think this one should be closed. I have not seen any reports of it being a problem except for you early scouting.

If you are looking for 3.0, you may want to take a look at #36433. It had multiple reports.

**Comment by ericstj** [comment]
Not to corelib, but to System.Runtime.Extensions.  There were some early partners who needed this, let me reach out and see if they still need it.

**Comment by terrajobst** [comment]
> There were some early partners who needed this, let me reach out and see if they still need it.

It would be helpful to understand how they are using this API what specifically they need. I've no idea how this API works and what it's supposed to help with.

**Comment by OliaG** [comment]
cc @vitek-karas, @sdmaclea

**Comment by jkotas** [comment]
We are done with porting APIs from .NET Framework.
