### ISSUE TITLE
Consider exposing AppDomain.get_PermissionSet

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#32745]
I've seen a number of libraries depend on this property.  API Usage shows that it is quite high: https://apisof.net/catalog/System.AppDomain.PermissionSet

In my early prototypes for .NETCore 3.0 I needed to expose it.
https://devdiv.visualstudio.com/DevDiv/_git/DotNet-CoreFX-Trusted/commit/5704601346049767433cd5d717fed16733056f58?refName=refs%2Fheads%2Fericstj%2Fadd.back.types.experiment

The gist of that change is that it pushed PermissionSet and IStackWalk down into System.Runtime.Extensions and exposed AppDomain.get_PermissionSet as `return new PermissionSet(PermissionState.Unrestricted);`.

The controversial thing here is pushing those types down, however it was relatively contained; it luckily didn't bring down all of S.Sec.Permissions.

/cc @danmosemsft

**Comment by danmosemsft** [comment]
The change makes sense to me. @maryamariyan another one for your list - porting @ericstj change above.

**Comment by danmosemsft** [comment]
@ericstj why was it necessary to create a netcoreapp configuration in S.S.Permissions? It is not breaking to change to a type forward?

**Comment by ericstj** [comment]
Because AppDomain is part of netstandard.dll and we cannot retroactively push PermissionSet into netstandard.dll.

Another way to look at this is we needed to typeforward to S.R.Extensions which was absorbed into netstandard, which we cannot change.

This is not a breaking change to forward a type, so long as you forward from the previous location.

**Comment by jkotas** [comment]
Isn't this going to push S.S.Permissions into a partial .NET Core OOB with all the mess that comes with it?

**Comment by ericstj** [comment]
No, this just means S.S.Permissions needs to cross-compile for netcoreapp3.0.  Nothing else changes, we're not suggesting to change the inbox behavior of any assembly.

**Comment by MarcoRossignoli** [comment]
@jkotas unrelated to this...i see term OOB in some discussion...can point me to some documentation of out-of-band meaning?Sorry for the noise here...but i'd like to understand all.

**Comment by jkotas** [comment]
> No, this just means S.S.Permissions needs to cross-compile for netcoreapp3.0.

Ok, I see that we have several other types forwarded from S.S.Permissions already.

> can point me to some documentation of out-of-band meaning?

I am not sure whether we have it written anywhere ... here is the decoder ring:
- OOB means out-of-band. It means that the library implementation is shipping as NuGet package.
- Opposite of OOB is inbox. Inbox means that the library implementation is shipping as part of the runtime. 
- Partial OOB is a library that ships implementation as NuGet package for some runtimes, and inbox for other runtimes.
