### ISSUE TITLE
Add a way to start enumeration of SortedSet and SortedDictionary in the middle

### ISSUE THREAD

**Issue by CodesInChaos** [dotnet/corefx#3275]
I'd like an efficient way to start enumeration of a sorted collection (in particular `SortedSet<T>` and `SortedDictionary<TKey, TValue>`) at a specified value. This should work even if the value is not part of the collection.

**Why is it useful?**

Such a feature would be useful for many things. For example:

* Finding all elements in an interval.
* Finding the closest element to an item in the set
* With a properly chosen comparer prefixes sort immediately before their extensions. So this could be used to find the longest prefix that's in the collection.
* Could be used to map from a continuous variable (e.g. time) to a value. For example if a system can either be `on` or `off` at a particular time, one could put the switching evens in a `SortedDictionary<DateTime, bool>` and then query it to figure out if the system was `on` at a particular time.
* You could save the current element, mutate the collection (invalidating existing enumerators) and then create a new iterator starting at that element.

**Different approaches**

One way to implement this feature is having a pair of functions that return an enumerable starting at a particular point in the collection. I'm not sure what the name should be, possible choices include `UpwardsFrom`/`DownwardsFrom`, `From`/`ReverseFrom`, `ForwardsFrom`/`BackwardsFrom`.

An alternative approach would be extending `SortedSet<T>.Enumerator` adding a public constructor that takes a start element and a flag for backward iteration, but I don't like that overly low level approach.

**A concrete API suggestion**

on `SortedSet<T>`

    public IEnumerable<T> UpwardsFrom(T start);
    public IEnumerable<T> DownwardsFrom(T start);

on `SortedDictionary<TKey, TValue>`

    public IEnumerable<KeyValuePair<TKey, TValue>> UpwardsFrom(TKey start);
    public IEnumerable<KeyValuePair<TKey, TValue>> DownwardsFrom(TKey start);

and optionally on `SortedDictionary<TKey, TValue>.KeyCollection`

    public IEnumerable<TKey> UpwardsFrom(TKey start);
    public IEnumerable<TKey> DownwardsFrom(TKey start);

**Test cases**

	var sortedSet = new SortedSet<int>{1, 3, 5};

	sortedSet.UpwardsFrom(2) // [3, 5]
	sortedSet.UpwardsFrom(3) // [3, 5]
	sortedSet.UpwardsFrom(6) // []
	
	sortedSet.DownwardsFrom(4) // [3, 1]
	sortedSet.DownwardsFrom(3) // [3, 1]
	sortedSet.DownwardsFrom(0) // []

**Demo implementation**

Their behaviour would match the following extension methods, but would avoid the linear scan for the first match:

	public static IEnumerable<T> UpwardsFrom<T>(this SortedSet<T> sortedSet, T start)
	{
		var comparer = sortedSet.Comparer;
		return sortedSet.SkipWhile(item => comparer.Compare(item, start) < 0);
	}
	
	public static IEnumerable<T> DownwardsFrom<T>(this SortedSet<T> sortedSet, T start)
	{
		var comparer = sortedSet.Comparer;
		return sortedSet.Reverse().SkipWhile(item => comparer.Compare(item, start) > 0);
	}

**Comment by svick** [comment]
I have wanted some functionality similar to this too, so I strongly agree with the general idea to add something like this.

Some notes:

* `SortedList<TKey, TValue>` should be included too.
* I'm not sure about the proposed API. For example, it doesn't allow you to efficiently remove all items that fall into some interval. Especially for `SortedList`, where manipulating indexes could make a lot of sense. E.g. to remove old values from your `on`/`off` example (the `UpperBound` name stolen from `std::map`):

 ```c#
SortedList<DateTime, bool> sortedList = …;
int cutoffIndex = sortedList.UpperBound(cutoffDate);
sortedList.RemoveRange(0, cutoffIndex);
```

 This wouldn't be as simple for the other two (tree-based) collections. Exposing some kind of internal pointer (similar to [`LinkedListNode<T>`](https://msdn.microsoft.com/en-us/library/ahf4c754)) would work, but that might be getting too complicated.

**Comment by CodesInChaos** [comment]
You could implement removing somewhat efficiently using this API: After removing an item generate a new enumerator with using the key of the removed item. Costs one search in the set and an allocation.

One could also extend `RemoveWhere` to take a lower and an upper bound in addition to the predicate or add a `RemoveBetween` method.

As the internal pointer you could use the enumerator, especially if you modify it to not invalidate on modification (should be straight forward). It's a bit more flexible than my proposed API, but more annoying to deal with.

I don't care much about `SortedList`, since it can be easily emulated using an array/list and a binary search, but agree that for consistency it should get the same API as well.

**Comment by ianhays** [comment]
I'm closing this since it's been on the backlog for a year now without any discussion or movement.

Personally this seems too specific of a case for which to add a dedicated method, particularly since it's easy to add a 1 or 2 line custom method to iterate all values and yield those that are within some range.

**Comment by svick** [comment]
@ianhays 

>  it's easy to add a 1 or 2 line custom method to iterate all values and yield those that are within some range

The whole point of this proposal is to do it *efficiently*, taking advantage of the fact that the collections are already sorted.

For example, to retrieve *k* items starting from some value from a `SortedDictionary` with *n* items using `UpwardsFrom()` (or a similar API) would be O(log *n* + *k*).

With the one-liner you proposed, it would be O(*n*).

**Comment by CodesInChaos** [comment]
@ianhays 

> Personally this seems too specific of a case for which to add a dedicated method, particularly since it's easy to add a 1 or 2 line custom method to iterate all values and yield those that are within some range.

Following that logic, `SortedDictionary` itself is too specific, since you can (inefficiently) emulate it by sorting an array. The whole point of a sorted dictionary is its O(log(n)) access cost, the same is true for my proposed methods.

My personal experience is, that in most of the cases where a sorted dictionary seems useful, I also need this functionality. So I still think this proposal is an important improvement to `SortedDictionary`.
