### ISSUE TITLE
System.IO.Path.Join missing in classlib targeting netstandard2.0

### ISSUE THREAD

**Issue by jhfbosman** [dotnet/corefx#32756]
I'm not sure if this is intentional, an omission or if I'm simply doing something wrong, but for some reason I cannot use **System.IO.Path.Join** in a basic class library...

## Steps to reproduce:

1. Create new classlib using ```dotnet new classlib -n dt.playground.path.lib```
2. Add the following code into the generated Class1.cs
```cs
public class Class1
{
  public string sayHi(string name)
  {
    return System.IO.Path.Join("Join", "Lib", name);
  }
}
```

## Result:

The classlib fails to build with the error message ```Class1.cs(5,27): error CS0117: 'Path' does not contain a definition for 'Join'```

## Extra info:

**System.IO.Path.Join** works as expected in both the webapi and console projects targeting *netcoreapp2.1*.
**System.IO.Path.Combine** works as expected for both targets

The generated .csproj file for the classlib:
```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

</Project>
```

## Dotnet info:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

If someone could just let me know what the status of **System.IO.Path.Join** is in netstandard2.0?
I'm perfectly happy using **System.IO.Path.Combine** for now as there's not too much of a tradeoff...

**Comment by jhfbosman** [comment]
I'll close this as it's a non-issue since I can work around by using Path.Combine. I'm now just a little confused as to what parts of the System.* namespace is not part of netstandard... I was always under the impression that at least the System.* namespaces were all included in netstandard...

Anyway, thanks for the reply...

**Comment by stephentoub** [comment]
See https://docs.microsoft.com/en-us/dotnet/standard/net-standard.

netstandard is really just a specification that effectively says "the following types/members are available to be used on all runtime versions this standard targets".  That means that for an API to be listed in netstandard 2.0, it needs to be available in .NET Core 2.0, .NET Framework 4.6.1, etc.  Path.Join was added to .NET Core 2.1.
