### ISSUE TITLE
Docker Git Clone command should retry on server hangup

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#32769]
@dotnet-mc-bot commented on [Mon Oct 08 2018](https://github.com/dotnet/core-eng/issues/4329)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2088038
  - **Agent:** DDVSOLINUXAGE006
  - **Error log:** fatal: unable to access '***': GnuTLS recv error (-54): Error in the pull function....

@jcagme, @markwilkie

---

@MattGal commented on [Thu Oct 11 2018](https://github.com/dotnet/core-eng/issues/4329#issuecomment-429045169)

We've seen lots of failures like this.  In this case (` GnuTLS recv error (-54)`), it's a temporary problem caused by the server (VSTS's Git repository) hanging up while you're trying to clone stuff into the Docker container.  Since the commands run come from source code in CoreFX and the component that is misbehaving is external to our teams, there's nothing we as .NET Engineering services can actually do here.  The correct fix is to detect this case and retry some number of times.  As such I'm moving this to CoreFX.

**Comment by wtgodbe** [comment]
Seems like the fix would be to add retry logic for https://github.com/dotnet/corefx/blob/2739b08a423ab986409025263692de6bb4814e6f/buildpipeline/DotNet-CoreFx-Trusted-Linux.json#L24-L63 and https://github.com/dotnet/corefx/blob/2739b08a423ab986409025263692de6bb4814e6f/buildpipeline/DotNet-CoreFx-Trusted-Linux-Crossbuild.json#L24-L63. @MattGal do we have any precedent for adding retry logic to pipeline steps? 

CC @karelz @ulisesh

**Comment by MattGal** [comment]
@wtgodbe I see two possible approaches here.  

- The only precedent I can think of is that many teams end us using a script to do this command instead of a single docker run ... command.
- From reading the docker run documents, it sounds like it's worth trying a flag like `--restart on-failure[:max-retries]` .  If you can force the server to hang up on you while running the same command plus these args, you might be able to get away with just this.

**Comment by wtgodbe** [comment]
@MattGal when I have a fix for this, should I bring it in to release/2.2 as well, given that we've seen the failure in both places? For that matter, should I also bring it in to 2.1?

**Comment by MattGal** [comment]
All VSTS trusted builds clone in this way every time and from the same servers.... so my opinion is that we should both port this fix (once we have something reliable that works for Linux and Windows and mac) to every branch we still build, as well as write down some sample stuff (since any solution is likely to be general purpose) for future users.

**Comment by wtgodbe** [comment]
Given that we're looking for a fix that works for Windows & Mac (where we don't use Docker) as well as a fix for Linux (where we do), what do you think about adding scripts similar to begin/end.ps1 that do cloning & checking-out with retries? That way we could either call the script directly, or `docker run` it on Linux. @MattGal thoughts?

**Comment by MattGal** [comment]
While I like the idea, in practice there's a couple problems:

- Currently these scripts are hit-and-miss. Occasionally there won't be files on disk when it tries to run
- They always expect powershell, but the .NET Core powershell executable (pwsh) is missing on pretty much every machine I've ever read the logs for.

Given the lack of pwsh on the path for the Linux agents today, unfortunately I think doing it inside the build is the best chance of making this change and actually increasing build reliability.

**Comment by wtgodbe** [comment]
Looks like you can't run `--rm` and `--restart` in the same docker command - do we need to run `--rm` in every `docker run` command? Or do we need to separate `--rm` and `--restart clone` in 2 separate commands?

As for Windows & Mac, I suppose we could just have an inline step that retries itself 5-or-so times.

**Comment by ericstj** [comment]
Just double check that we aren't doing something that's already been done.  What does roslyn do? arcade?

**Comment by MattGal** [comment]
@ericstj the new behavior is to let the AzDO Agent do the work for you, some docs here:

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml

If you check out the Linux x64_Release leg here, you'll see it's already in use for master: https://dnceng.visualstudio.com/internal/_build/results?buildId=113431 

For release-branch building, it seems pretty reasonable to make the decision whether or not to invest in adding retry now that it's only needed in servicing... I'll leave that up to the teams themselves.

**Comment by wtgodbe** [comment]
I'll close this, as it's fixed in master & probably not worth doing for our servicing branches
