### ISSUE TITLE
API: Proposal add Cancellation overloads to easy to use HttpClient methods

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#32762]
```C#
public Task<byte[]> GetByteArrayAsync(Uri requestUri);
public Task<Stream> GetStreamAsync(string requestUri);
public Task<Stream> GetStreamAsync(Uri requestUri);
public Task<string> GetStringAsync(string requestUri);
public Task<string> GetStringAsync(Uri requestUri);
```

Today these methods don't allow passing a cancellation token in, you're required to drop down to the lower level API to figure it out manually. Instead we should just support overloads that take in CancellationToken.

**Comment by stephentoub** [comment]
Dup. https://github.com/dotnet/corefx/issues/32615
