### ISSUE TITLE
Add IEnumerable.SelectMultiple

### ISSUE THREAD

**Issue by OliverHabersetzer** [dotnet/corefx#32760]
I have a special task where I want to select multiple fields within a List Element:

Given the exemplary class `Range` defined as follows:
```csharp
public class Range
{
    public int Start, End;
}
```

Under usual circumstances you'd have to add these Elements manually like so:

```csharp
List<Range> ranges = new List<Range>();
// Add some elements...
List<int> values = new List<int>();
ranges.ForEach(range =>
{
    values.Add(range.Start);
    values.Add(range.End);
});
```

Alternatively you could create a child Array and then use `SelectMany` to achieve the same.

```csharp
List<int> values = ranges.
    SelectMany(range => new[] { range.Start, range.End })
    .ToList();
```

What I suggest is simplifying this type of calls as follows:

```csharp
List<int> values = ranges.SelectMultiple(
    range => range.Start,
    Range => Range.End
).ToList();
```

This could be enabled by the following extension method:

```csharp
public static class IEnumerableExtensions
{
    public static IEnumerable<TOut> SelectMultiple<TIn, TOut>(this IEnumerable<TIn> inList, params Func<TIn, TOut>[] selectors)
    {
        return inList
            .ToList()
            .SelectMany(inElement => selectors
                .ToList()
                .ConvertAll(selector => selector(inElement)
                )
            );
    }
}
```

I'm aware that this is only a quality of live feature and does only provide some amount of syntactic sugar but still I think this could improve readability of code immensely.

**Comment by stephentoub** [comment]
FWIW, `SelectMany(r => new[] { r.Start, r.End })` is, at least to my eyes, very readable, more so than `.SelectMultiple(r => r.Start, r => Range.End)`, especially if you generalize this to more than just a couple of items.

You can also achieve this with local functions, e.g. instead of:
```C#
List<int> values = ranges.SelectMultiple(
    range => range.Start,
    range => range.End
).ToList();
```
doing something like:
```C#
IEnumerable<int> Elements(Range r)
{
    yield return r.Start;
    yield return r.End;
}
List<int> values = ranges.SelectMany(Elements).ToList();
```
(which could be improved further if the language ever supported iterator lambdas).

**Comment by OliverHabersetzer** [comment]
> FWIW, `SelectMany(r => new[] { r.Start, r.End })` is, at least to my eyes, very readable, more so than `.SelectMultiple(r => r.Start, r => Range.End)`, especially if you generalize this to more than just a couple of items.

I get your point - it's too bad that we have to write `r =>` all the time but `new[] {}` isn't so nice on its own IMO. It'd be nice to write something like `r => r.Start, r.End` or even `r => {r.Start, r.End}`, don't you think?

**Comment by stephentoub** [comment]
> It'd be nice to write something like r => r.Start, r.End or even r => {r.Start, r.End}, don't you think?

That would be a language feature.  If that's something you're interested in pursuing, I'd suggest looking to see if anything similar is already an issue in https://github.com/dotnet/csharplang, and if not, opening an issue with the details of your proposal.

**Comment by jnm2** [comment]
I first suggested this because it's available out of the box and seems clearer than anything else:

```c#
var values = ranges
    .SelectMany(range => new[] { range.Start, range.End })
    .ToList();
```

But if that's really too much syntax for you, you can always do this (probably shouldn't be in the BCL though):

```c#
var values = ranges
    .SelectMany(range => (range.Start, range.End))
    .ToList();

public static IEnumerable<TResult> SelectMany<T, TResult>(this IEnumerable<T> source, Func<T, (TResult, TResult)> selector)
{
    if (source == null) throw new ArgumentNullException(nameof(source));
    if (selector == null) throw new ArgumentNullException(nameof(selector));

    return source.SelectMany(value =>
    {
        var (item1, item2) = selector.Invoke(value);
        return new[] { item1, item2 };
    });
}
```
