### ISSUE TITLE
IPv4InterfaceProperties.IsDhcpEnabled no work on centos 7.4 

### ISSUE THREAD

**Issue by shen3221894** [dotnet/corefx#32781]
When i use IPv4InterfaceProperties.IsDhcpEnabled by using .NET Core 2.1.5 on centos 7.4, i get the error "System.PlatformNotSupportedException: The information requested in unavailable on the current platform.at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties.get_IsDhcpEnabled()"

**Comment by wfurt** [comment]
There is no good api on Linux to get such information. There are may ways how DHCP can be configured and it does not seems feasible to support all distros.

cc: @tmds

**Comment by karelz** [comment]
Sounds like by design then.

**Comment by mdisg** [comment]
@wfurt 
The method [ParseDhcpServerAddressesFromLeasesFile](https://github.com/dotnet/corefx/blob/master/src/System.Net.NetworkInformation/src/System/Net/NetworkInformation/StringParsingHelpers.Addresses.cs) does read dhcp related information from the `dhclient` lease file. It's kind of weird that some stuff is being read from a specific dhcp setup like the server addresses but the information if dhcp is enabled not. I understand the wide range of possibilities but i think if one information is retrieved the others should be too or nothing at all.

What about checking the lease configuration and using that information if available for the property `IPv4InterfaceProperties.IsDhcpEnabled` ?
