### ISSUE TITLE
Websocket KeepAliveInterval Infinite shouldn't create Timer

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#32807]
`Timeout.InfiniteTimeSpan` is a valid timeout for `Websocket` KeepAliveInterval

https://github.com/dotnet/corefx/blob/14072950a458eabef6eb6da2204ba0a506242b4b/src/System.Net.WebSockets/src/System/Net/WebSockets/WebSocket.cs#L154-L161

However it only doesn't create the Timer for a KeepAliveInterval of zero:

https://github.com/dotnet/corefx/blob/14072950a458eabef6eb6da2204ba0a506242b4b/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L198-L202

As the timer will never fire for `InfiniteTimeSpan` and the KeepAliveInterval can't be changed, it probably shouldn't create a Timer for Infinite either.

**Comment by stephentoub** [comment]
> However it only doesn't create the Timer for a KeepAliveInterval of zero:

It only creates one for a timeout greater than zero.

**Comment by benaadams** [comment]
Just realised that when making the PR 😄 

Infinite being negative
