### ISSUE TITLE
HttpContent.CopyToAsync ignores bufferSize sometimes

### ISSUE THREAD

**Issue by Spongman** [dotnet/corefx#32800]
if `remain > 0`, it throws `bufferSize` on the floor.

https://github.com/dotnet/corefx/blob/87a944afb3e0ec392d5838900b5498e015d5e47b/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L1395-L1403

4096 is not nearly enough buffer for streaming large files over high-bandwidth (10Gbps+) connections. it wastes _way_ too much CPU in the async stuff.

**Comment by stephentoub** [comment]
I've addressed this in https://github.com/dotnet/corefx/pull/32803, but I don't know where the "4096" you cite is coming from: by ignoring the bufferSize passed in, it'll end up using the default size used for CopyToAsync on any stream, which is 80K.  If you're referring to the buffer size used within HttpConnection, that's not used for the CopyToAsync, other than for any data that may have already been read as part of reading headers and the like.

**Comment by Spongman** [comment]
Sorry pleas ignore the 4K part. That’s for the length-constrained copy.
