### ISSUE TITLE
SocketsHttpHandler leaks doesn't clean up when HttpClient isn't disposed

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#32802]
cc @stephentoub

**Comment by stephentoub** [comment]
Is this different from https://github.com/dotnet/corefx/pull/32793?

**Comment by davidfowl** [comment]
Ah I didn't see that

**Comment by stephentoub** [comment]
:smile:

**Comment by stephentoub** [comment]
Closing as dup of https://github.com/dotnet/corefx/issues/31262
