### ISSUE TITLE
HttpConnection needs a way to configure the buffer size

### ISSUE THREAD

**Issue by Spongman** [dotnet/corefx#32801]
when copying large files over high-bandwidth connections it wastes a large amount of CPU handling the async callbacks - it's essentially useless.

also, there's no need to do the `CopyToExactLengthAsync` stuff if the server sent a `Connection: close` header or no `Content-Length:` and the body isn't chunked. wouldn't it be much more efficient to just copy directly from the NetworkStream?

**Comment by stephentoub** [comment]
> also, there's no need to do the CopyToExactLengthAsync stuff if the server sent a Connection: close header

If the server sends Connection: close instead of a content length or chunked transfer encoding, it'll use a ConnectionClosedReadStream:
https://github.com/dotnet/corefx/blob/25d197892c37067f45cf97619bb0dfb28413a682/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L628-L631
where CopyToAsync will just use _stream.CopyToAsync, copying directly from the network stream:
https://github.com/dotnet/corefx/blob/25d197892c37067f45cf97619bb0dfb28413a682/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectionCloseReadStream.cs#L86

What is the concern there?

**Comment by Spongman** [comment]
Regardless, in the `ContentLengthReadStream` case, the `bufferLength` parameter of `CopyToAsync` is ignored and the copy is done in 4K chunks.

**Comment by stephentoub** [comment]
> Also, what if it sends Content-Length and chunked?

That's invalid. No server should do that. It's certainly not something to optimize for.

> What if the server sends Content-Length and Connection: close?

You're right that we could use a different stream in that case, and maybe we should, but is it really impactful? Can you please share measurements with the current implementation that highlight why you're concerned about that case?

**Comment by Spongman** [comment]
it's difficult for me to share precise numbers because the VS profiler doesn't return meaningful results for core managed code but i'm seeing extremely high CPU (essentially 1 pegged core) during CopyToAsync GET->disk (_not_ network or disk-limited). it seems to me that it's spending most of in the `CopyToExactLengthAsync` loop filling & emptying the 4K buffer.

i'm actually trying to track down an issue where a 500GB CopyToAsync GET slows from ~100Mbps down to ~300Kbps over an 8 hour period. but i have only reprod this on native ubuntu, i'm not set up to use lldb yet, and the repro is tortuous, so i'm not sure if these two issues are related...

**Comment by Spongman** [comment]
(Oops)

**Comment by GSPP** [comment]
Maybe the buffer size can be increased dynamically. E.g.: If the total amount transfered rises above 4MB, buffer 64KB from that point on. If it rises above 256MB, buffer 256KB.

Large buffer sizes can save a lot of CPU (async and kernel transitions). For example the Vista Windows Explorer had the innovation that they use 1-8MB chunks. This helped a lot according to the team blog post. I remember similar stories for high speed SMB.

**Comment by Spongman** [comment]
How about just reallocating `_readBuffer` if `bufferSize` is larger and it’s going to be used (ie. in the length-constrained case)
