### ISSUE TITLE
Why double value in runtime are not same with specific in source code?

### ISSUE THREAD

**Issue by mokeyish** [dotnet/corefx#32815]
![image](https://user-images.githubusercontent.com/16131917/46924491-ec4cfa00-d057-11e8-8587-da14b772a70d.png)

**Comment by Clockwork-Muse** [comment]
Ah, the good ol' floating-point representation problem: 
[A simple overview](https://www.floating-point-gui.de/).

Basically - the literal value in the source code isn't actually the binary value stored/used in code.
