### ISSUE TITLE
SqlClient Slow Connection on Linux

### ISSUE THREAD

**Issue by rrudduck** [dotnet/corefx#32812]
We are running into a fairly consistent issue where it takes approximately 5 seconds for a new connection to be opened to a remote SQL Server instance. Once the connection is established, performance is great - it just appears to be on the initial connect of new connections in the connection pool. The connections don't fail, there is just a delay upon opening.

We've been able to reproduce it with on multiple Kubernetes clusters against multiple SQL servers. All of the clusters are running Ubuntu 16.04 and K8s 1.11.2. It does not appear to be reproducible on Windows, at least in our testing.

We have a few differences (parameters and such), but the code is basically just:

```c#
using ( var connection = new SqlConnection( connectionString ) )
{
    await connection.OpenAsync();

    using ( SqlCommand command = connection.CreateCommand() )
    {
        command.CommandText = cmdText;

        command.Parameters.Add( "@CustomerNbr", SqlDbType.Int ).Value = 519092;

        using ( SqlDataReader reader = await command.ExecuteReaderAsync() )
        {
            while ( await reader.ReadAsync() ) { }
        }
    }
}
```

Thanks.

**Comment by rrudduck** [comment]
We have not yet. Since it was reproducible in multiple clusters against multiple SQL Servers in different VNETs (all in Azure), we started on the app side first. The same app when running under Windows does not seem to exhibit the behavior.

My plan is this week was to see if I could reproduce it on a standalone Linux host. That will probably be easier to take a network trace of anyway. We aren't running connection encryption or anything on the SQL side like I've seen referred to in other issues.

Thanks.

**Comment by rrudduck** [comment]
Update: This only seems to reproduce on K8s and is probably related to the DNS issues many other folks have been reporting. I'm going to dig further, but this doesn't appear to be a corefx issue.

**Comment by karelz** [comment]
@rrudduck thanks for update. I'd be curious which DNS issue you have in mind - once you can confirm the root-cause, it may help us prioritize further investments in the area if external tools/environments are more likely to run into specific issues. Thanks!

**Comment by rrudduck** [comment]
@karelz Here you go:

https://github.com/kubernetes/kubernetes/issues/56903
https://github.com/Azure/AKS/issues/632
https://github.com/kubernetes/kubernetes/issues/45363

An interesting blog post here: https://blog.quentin-machu.fr/2018/06/24/5-15s-dns-lookups-on-kubernetes/

We added a few DNS related options to one of the pods with the issue and it *seems* to be mostly resolved - at least in our initial testing. Still more verification to do.

What would be really nice to have, although I'm guessing most of this behavior is OS defined and not in corefx, would be to have the SqlClient and HttpClient (and others) have a configurable deadline for DNS lookups - if it breaches the threshold, use the previously resolved value. Or something like that where you could have a deterministic max value for certain operations.

**Comment by karelz** [comment]
Having DNS deadline sounds like a hack to me to work around potential problems.
I think it may be better to expose full DNS APIs and let applications control DNS resolutions themselves. Maybe included DNS callbacks for custom DNS resolutions. It is something we have on our list, although it is not quite high.

Thanks for the info. Seems to be external issue, so closing.
