### ISSUE TITLE
Add MinimumCollectionCountValidationAttribute 

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/corefx#32813]
It would be handy if there was a `ValidationAttribute` for validating the minimum count/length "out of the box" of a `List<T>` or more generically a `ICollection<T>`. 

```csharp
public class MyClass
{
   [Required]
   [MinimumCollectionCount(1)]
   public List<int> SomeInts { get; set; }
}
```

**Reference:** [StackOverflow Answer Implementation](https://stackoverflow.com/a/48278068/185123)

Thoughts? 💭

**Comment by ajcvickers** [comment]
This is not something we plan to implement.
