### ISSUE TITLE
WCF Performance Problem

### ISSUE THREAD

**Issue by cicciog90** [dotnet/corefx#32819]
We experienced a serious performance problem using **WCF .NET Core 2.1** client libs.
Connecting to a service, the first bunch of calls are very slow (**about 2 seconds**) but after several trials it becomes very fast (**about 30 milliseconds**).
The same code compiled with **.NET Framework 4.7.1** is fast with no differences during all calls.

You can find a sample here: https://github.com/cicciog90/WCF_Performance_Test

**Comment by cicciog90** [comment]
@karelz  Can you suggest me the way to monitor perf traces or network capture traces?

**Comment by Wraith2** [comment]
Using [perfview](https://github.com/Microsoft/perfview) will get ETW traces which can be posted here and examined

**Comment by cicciog90** [comment]
Hi @Wraith2, thanks for info. 
PerfView has generated a .zip file of 59.5 MB which I cannot upload here. 
Where I post it?

**Comment by cicciog90** [comment]
I uploaded it on my drive.
This is the shared link: https://drive.google.com/file/d/1crWSI9HYRVHRwpRE5CUaNntEr_XIMgqO/view?usp=sharing

**Comment by Lxiamail** [comment]
@cicciog90 Thanks for reporting the issue and collecting trace data. I have moved the issue to https://github.com/dotnet/wcf/issues/3222

**Comment by karelz** [comment]
For network capture, I'd recommend Wireshark or Fiddler.

Closing here as it was moved.

BTW: @Lxiamail not sure if you're aware of GH issue tooling: either ZenHub, or https://github-issue-mover.appspot.com/ (currently down)

**Comment by Lxiamail** [comment]
@karelz 👍
