### ISSUE TITLE
Treating warnings as errors causing build failures

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/corefx#32829]
@dotnet-mc-bot commented on [Fri Oct 12 2018](https://github.com/dotnet/core-eng/issues/4386)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2114205
  - **Agent:** DDVSOLINUXAGE013
  - **Error log:** /root/corefx-2114205/Tools/CloudTest.Helix.targets(0,0): error : Helix Api Response: StatusCode BadRequest {"Message":"Provided Job List Uri is not accessible"} [/root/corefx-2114205/src/upload-tests.proj]...

@jcagme, @markwilkie

---

@ChadNedzlek commented on [Mon Oct 15 2018](https://github.com/dotnet/core-eng/issues/4386#issuecomment-429962934)

Hrm. This one is weird, because the error message says "14 retries remanining"... but then didn't appear to retry?

---

@ChadNedzlek commented on [Mon Oct 15 2018](https://github.com/dotnet/core-eng/issues/4386#issuecomment-429989340)

Ah. Someone has enabled "warnaserror".  There are actually no problems here, but that's enabled for some reason, so our warning turns into and error which fails this build, even though nothing is wrong.

**Comment by MattGal** [comment]
Updated the title, we have at least two more builds that hit this problem this morning.  Definitely something to address ASAP.

**Comment by weshaggard** [comment]
Yes that is part of my recent PR I'll submit a fix to disable warning as error for this step.
