### ISSUE TITLE
MemoryMappedFile.CreateFromFile fails on linux

### ISSUE THREAD

**Issue by hopix** [dotnet/corefx#32827]
Trying to use memory mapped files (`MemoryMappedFile.CreateFromFile`) on Linux with special files like `/dev/mem` fails on check saying 

> capacity must not be larger than file size

when opening in read access. For ReadWrite access the error is bit different.

Code example:
```c#
long viewCapacity = 0xFF;
using (MemoryFileStream fs = new MemoryFileStream(@"/dev/mem", FileMode.Open, FileAccess.ReadWrite, FileShare.ReadWrite))
{
	using (memMap = MemoryMappedFile.CreateFromFile(fs, null, viewCapacity, MemoryMappedFileAccess.ReadWrite, HandleInheritability.None, false))
	{
		using (MemoryMappedViewAccessor view = memMap.CreateViewAccessor(0, viewCapacity, MemoryMappedFileAccess.ReadWrite))
		{
		}
	}
}

```

Tested .net core 2.1.4 on:
* Ubuntu with file `/dev/mem`
* Raspbian on Raspberry PI 3 [ARM] with file `/dev/gpiomem`

Both fails same way.

**Seems like the main issues is with call to `FileStream.Length` which fails on exception!**

Looking at source code of `MemoryMappedFile.CreateFromFile` it seems to make many check which are might be causing problems in this case. There is for example call to FileStream.SetLength which in this case can't succeed, right?

Notes:
* on Raspbian the `FileStream.CanSeek` returns `false` for file `/dev/gpiomem`. Not sure if this is correct either?
* Mapping manually created file works OK.

Goal is to be able to use memory mapped files for GPIO access on Raspberry PI  from C# instead of using C library which we have to compile for each OS&platform.

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/issues/30686

**Comment by stephentoub** [comment]
Oops, yes.  I believe it's a dup. @hopix, please re-open if you disagree.  Thanks.

**Comment by hopix** [comment]
I agree this is duplicate of #30686. Thanks.
