### ISSUE TITLE
ALPN issues on Alpine36

### ISSUE THREAD

**Issue by rmkerr** [dotnet/corefx#32826]
It looks like ALPN has not been working correctly in the recent Alpine36 runs. 

There are several failures in the [ALPN tests](https://mc.dot.net/#/product/netcore/30/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20181015.04/workItem/System.Net.Security.Tests) and a handful in the [HTTP/2 tests](https://mc.dot.net/#/product/netcore/30/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20181015.01/workItem/System.Net.Http.Functional.Tests).

The failures started on October 12th, and have consistently failed in every run since then.

**Comment by rmkerr** [comment]
@MattGal, did anything about the Alpine images change on the 12th?

**Comment by MattGal** [comment]
Nothing's changed and we use docker images so they wouldn't have been modified without us knowing.  I'd suspect a test build issue

**Comment by rmkerr** [comment]
Fixed in #32956
