### ISSUE TITLE
System.Drawing.SystemColors.ActiveCaptionText not accurate on Windows 10

### ISSUE THREAD

**Issue by SwooshyCueb** [dotnet/corefx#32831]
According to the documentation, `System.Drawing.SystemColors.ActiveCaptionText` is supposed to return "the color of the text in the active window's title bar." In Windows 10, if the color of the background of the title bar is dark, the text is white, otherwise it is black; however, `System.Drawing.SystemColors.ActiveCaptionText` *always* returns black.

**Comment by mikedn** [comment]
> the color of the text in the active window's title bar

Yeah, it used to do that a long time ago, before DWM became "always on" in Win8, before it was introduced in Vista and before (ux)theming appeared in WinXP. These days the "caption" colors don't reflect reality, unless the reality happens to be windows drawn using the Vista classic style and not even then (those use a gradient, not a solid color).

That said, the colors that these properties return are correct, in the sense that if you draw ActiveCaptionText text on ActiveCaption background you get readable text.

**Comment by danmosemsft** [comment]
@SwooshyCueb thanks for letting us know. If you like you can submit an issue or PR into the https://github.com/dotnet/docs repo.

**Comment by SwooshyCueb** [comment]
I'd be happy to submit a pull request to update the documentation for this, and any other `SystemColors` properties that I might find have similar problems, but in order to do so, I think I need a better understanding of what the intent or purpose *is* of `System.Drawing.SystemColors.ActiveCaptionText` if not to retrieve the color of the text in active window title bars.
