### ISSUE TITLE
HttpClient (SocketsHttpHandler) connection leak with HttpCompletionOption.ResponseHeadersRead

### ISSUE THREAD

**Issue by vblz** [dotnet/corefx#32864]
Environment: Linux, dotnet 2.1

Way to reproduce:
```c#
var client = new HttpClient { BaseAddress = new Uri("http://127.0.0.1:8080/")  };
for (int i = 0; i < 100; ++i)
    await client.GetAsync("/", HttpCompletionOption.ResponseHeadersRead);
```

Actual behavior:
There are two problems:
1. For every request creates new TCP connection
2. All created connections stuck in CLOSE_WAIT status forever on Linux (and for about 120 sec on Windows).

So if app makes a lot of requests, all available connections of operating system is ending.

With `CurlHandler` connection closing in abot 30 seconds on Linux.

Repo with code to reproduce: https://github.com/vblz/HttpClientConnectionLeak

**Comment by vblz** [comment]
Thank you. With HttpResponseMessage.Dispose all connections closing in 30 seconds.

But is this interval correct? If we will create new requests faster than one in 30 seconds, eventually all available connections will be exhausted anyway, isn't it?

**Comment by benaadams** [comment]
You also either need to Dispose `HttpClient`; always reuse the same static `HttpClient` or use [`HttpClientFactory`](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)

HttpClient keeps the connection open for keepalive requests to the same server so it doesn't have to go through the full http/tls handshakes, much like a browser does.

**Comment by stephentoub** [comment]
What @benaadams said.  HttpClient pools, so if you want the connections to go away immediately, you need to dispose of it, e.g.
```C#
using (var client = new HttpClient { BaseAddress = new Uri("http://127.0.0.1:8080/")  })
{
    for (int i = 0; i < 100; ++i)
    {
        using (HttpResponseMessage resp = await client.GetAsync("/", HttpCompletionOption.ResponseHeadersRead))
        {
            ... // do whatever else you want here
        }
    }
}
```

**Comment by vblz** [comment]
Yeah, just tried it - after Dispose new requests utilize already opened connection. Thany you all very much.

**Comment by stephentoub** [comment]
You're welcome.
