### ISSUE TITLE
Consider support of Socket.DontFragment on Mac OSX

### ISSUE THREAD

**Issue by xmedeko** [dotnet/corefx#32865]
I know Mac OSX does not support `Socket.DontFragment`, but I've maybe found  an workaround in https://lists.apple.com/archives/macnetworkprog/2006/Jul/msg00014.html

> You can use the IP_HDRINCL option and set the bit yourself.
> 
>   result = setsockopt(mSocket, IPPROTO_IP, IP_HDRINCL, &value, sizeof(int));

BTW. What about Mono, does it support on Mac OSX? (I do not have Mac OSX, cannot test it.)

(Note, I need that for UDP networking).

**Comment by karelz** [comment]
We do not track Mono issues here - please check on their GitHub. They currently have separate networking stack as it is heavily OS dependent.

@wfurt to see if the above workaround would help us ...

**Comment by xmedeko** [comment]
@karelz I mean you can look at the Mono code and take an inspiration from it, if it has solved somehow.

**Comment by karelz** [comment]
@xmedeko do you know if Mono supports it? I can't find the definition in the [source code](https://github.com/mono/mono/search?p=1&q=DontFragment&unscoped_q=DontFragment).

**Comment by xmedeko** [comment]
No, I do not know, I do not have Mac OSX for testing. I've just heard that probably Unity Mono the `Socket.DontFragment` does not throw exception, but do not know if it really works or not.

**Comment by stephentoub** [comment]
As far as I'm aware, Mono uses IP_MTU_DISCOVER if it's available, as we do (https://github.com/dotnet/corefx/pull/17158), and then if it's not available (as it's not on macOS), Mono just ignores the setting.

**Comment by xmedeko** [comment]
Just about the `IP_HDRINCL` options, you may see the example in https://opensource.apple.com/source/network_cmds/network_cmds-328/ping.tproj/ping.c

**Comment by karelz** [comment]
It seems we do all that Mono does (@stephentoub). Most likely limitation of OSX.
If there is evidence saying otherwise, please let us know and we can reconsider.
