### ISSUE TITLE
Produce a  `SwitchMap` method in base class

### ISSUE THREAD

**Issue by Anduin2017** [dotnet/corefx#32863]
I really need a method like this:

```csharp
public static IEnumerable<P> SwitchMap<T,P>(this IEnumerable<T> dataSet, Func<T,P> predicate) where T : class
{
    List<P> list = new List<P>();
    foreach(var element in dataSet)
    {
        list.Add(predicate(element));
    }
    return list;
}
```

Every time I create a new project will I write this code and use it to switch map containers.

So, why doesn't our dotnet base class produce a method like that?

**Comment by MarcoRossignoli** [comment]
FYI https://stackoverflow.com/questions/23783863/mapping-a-list-of-object-models-onto-another-list-using-linq

**Comment by MarcoRossignoli** [comment]
I'm not EF expert...but maybe issue issue is related to how `Include/Select` on dbContext works.
If you try this works as expected?
```
  var groupRelations = dbContext.UserGroup
                .AsNoTracking()
                .Where(t => t.UserId == userId)
                .Include(t => t.Group.Messages)
                .ToList();
                .Select(t => t.Group);
```

**Comment by Anduin2017** [comment]
> I'm not EF expert...but maybe issue is related to how `Include/Select` works on dbContext.
> If you try this works as expected?
> 
> ```
>   var groupRelations = dbContext.UserGroup
>                 .AsNoTracking()
>                 .Where(t => t.UserId == userId)
>                 .Include(t => t.Group.Messages)
>                 .ToList()
>                 .Select(t => t.Group);
> ```
> EDIT: Maybe related https://docs.microsoft.com/en-us/ef/core/querying/related-data#ignored-includes

Yeah, that works fine. But if you wanna use `ToListAsync` you have to change the code like this which is hard to read.

```csharp
  var groupRelations = (await dbContext.UserGroup
                .AsNoTracking()
                .Where(t => t.UserId == userId)
                .Include(t => t.Group.Messages)
                .ToListAsync())
                .Select(t => t.Group);
```

And that was the reason why I require a better method to switch context from container to another container.

**Comment by Anduin2017** [comment]
> I'm not following. How is `.SwitchMap(predicate)` as you wrote it different from `.Select(predicate).ToList()` on an enumerable?
> 
> And are you actually operating on a queryable rather than on an enumerable?

Yeah, I guess I was not clear that it seems `SwitchMap` works similar to `ToList().Select()` on `IQueryable`. But I really wanna do it with one async method like `SwitchMapAsync`.

**Comment by svick** [comment]
@Anduin2017 How is the name `SwitchMap` more clear? It's completely unrelated to `switch`, and the name does not imply in any way that it's a combination of `Select` and `ToList`.

And `ToListAsync` is not part of .Net Core, it's part of EF Core. So I think a method like `SwitchMapAsync` would also have to be part of EF Code. Maybe you should direct your request [that way](https://github.com/aspnet/EntityFrameworkCore)?

**Comment by svick** [comment]
@Anduin2017 

I don't know anything about RxJS, but I looked at [the documentation for `switchMap`](https://www.learnrxjs.io/operators/transformation/switchmap.html):

> The main difference between `switchMap` and other flattening operators is the cancelling effect. On each emission the previous inner observable (the result of the function you supplied) is cancelled and the new observable is subscribed. You can remember this by the phrase switch to a new observable.

I don't think any of this makes sense if you have `IEnumerable` or `IQueryable`, but not an observable.
