### ISSUE TITLE
Coding style clarification

### ISSUE THREAD

**Issue by jskeet** [dotnet/corefx#3287]
The [coding style](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md) states:

> We use `_camelCase` for internal and private members and use `readonly` where possible. Prefix instance fields with `_`, static fields with `s_` and thread static fields with `t_`.

Is this first sentence really meant to apply to all members, or just fields? Would you write:

```csharp
private void _doSomething()
{
    ...
}
```

or even more oddly (IMO)

```csharp
internal class _myThisLooksOdd
{
}
```

? Looking at a couple of examples, I'm pleased to see that this doesn't appear to be the case - so should the style guide be changed to:

> We use `_camelCase` for internal and private fields and use `readonly` where possible. Prefix instance fields with `_`, static fields with `s_` and thread static fields with `t_`.

... or are there other members which *are* intended to be included. Enquiring minds need to know...

**Comment by stephentoub** [comment]
Thanks, @jskeet.  The style guide should be changed.  That naming style is meant to be for fields, not all members, as you correctly surmised. :smile:

**Comment by stephentoub** [comment]
Fixed: https://github.com/dotnet/corefx/commit/01aa9281598ab545c166a31a45319bd4d7acfbb3

**Comment by jskeet** [comment]
Cracking - thanks for the swift fix :)
