### ISSUE TITLE
CurlHandler can't handle set-cookie in 3xx response

### ISSUE THREAD

**Issue by skyline75489** [dotnet/corefx#32879]
The code here handles set-cookie header from Curl response: https://github.com/dotnet/corefx/blob/a0e4d78a74b241289dcf0c4c1c6fa026e394a150/src/System.Net.Http/src/System/Net/Http/CurlHandler/CurlHandler.MultiAgent.cs#L1014 

However it fails to handle `set-cookie` if the response status code is 3xx. Cookies inside 3xx response will not be saved to `_cookieContainer`.

**Comment by skyline75489** [comment]
I don't know whether sending `set-cookie` in 3xx response is a good practice or not. But we are facing this issue with some sites. `HttpClientHandler` in .NET framework works fine in this situation.

**Comment by karelz** [comment]
@caesar1995 do you know if we have known limitations on Curl regarding cookies on redirect?

@skyline75489 do you have a minimal repro we could try?

**Comment by caesar1995** [comment]
This issue has been fixed by https://github.com/dotnet/corefx/pull/5080 in .NET Core 1.0 rc2.

@skyline75489 Which version of .NET Core are you using? Can you share a repro?

**Comment by skyline75489** [comment]
@caesar1995  We are indeed using an old version of .NET Core. 

@karelz Thanks for the tip of `SocketsHttpHandler`. I didn't heard about it util now.

I'll give .NET Core 2.1 a try and come back later were there any new issue.
