### ISSUE TITLE
Proposal: Span/Memory.Split

### ISSUE THREAD

**Issue by schungx** [dotnet/corefx#32889]
Not sure if it is there already, but `Split` will be a great addition to `Span`/`Memory`, especially those related to `char` or `byte`.

Currently, `String.Split` creates multiple copies of sub-strings in an array.  I can remember many times that I ended up rolling my own `Split` with `IndexOf` just to avoid creating large number of one-time strings in tight loops.

Adding `Split` to `Span` and `Memory` can alleviate all this, especially in common situations where:

1. A `string` is split into multiple lines via `\n`
2. Each line is split into multiple fields via white-space to extract a command and parameters
3. Each command is processed individually

Both #1 and #2 above can be replaced by `Span.Split` which creates a simple array of a value type.

A further enhancement is to have `Span.Split` return a `Span<Span<char>>` to avoid creating the array.

**Comment by stephentoub** [comment]
Thanks. Dup of https://github.com/dotnet/corefx/issues/26528.
