### ISSUE TITLE
Expose System.ArgIterator

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#32898]
This type is already in System.Private.CoreLib: https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/src/System/ArgIterator.cs

But we don't currently expose it in any of our reference assemblies.

It's required to enable C++/CLI.

We should expose it in either System.Runtime or System.Runtime.CompilerServices.VisualC.

/cc @morganbr @jkotas

**Comment by jkotas** [comment]
This should be in System.Runtime.

**Comment by wjk** [comment]
This PR seems to be implying that C++/CLI will now be officially supported on Core 3. This is news to me, as I've never seen any reference to this particular feature in any announcements. Is this accurate? Thanks!

**Comment by ericstj** [comment]
There are plans for Windows-only Managed C++ support, you can track it here: https://github.com/dotnet/coreclr/issues/18013

**Comment by danmosemsft** [comment]
Is it full functioning in the runtime now? Ie., https://github.com/dotnet/coreclr/issues/9204 is not because the runtime is not implemented but merely because we have not chosen to expose it.

**Comment by jkotas** [comment]
> Is it full functioning in the runtime now?

Yes, it should be functional on *Windows* only. The runtime work was done in https://github.com/dotnet/coreclr/pull/18373

**Comment by danmosemsft** [comment]
OK. @maryamariyan another one for your list - expose for Windows, and add tests.
