### ISSUE TITLE
SocketException 22 while setting ReceiveTimeout

### ISSUE THREAD

**Issue by saurabh500** [dotnet/corefx#32894]
I got an error report from a product which uses SqlClient from .Net Core on macOS

The stack shows a SocketException with code 22 when SqlClient is setting the Socket timeout for receive to a particular value. 
My ask is what does the error code 22 for SocketException mean and in what scenarios can it be thrown? And how should this error be handled in case of setting the timeout?
While reading the code, I found that the error could be ~~EFBIG~~ EINVALID from https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/Native/Unix/System.Native/pal_errno.c#L67

~~EFBIG~~ is thrown when the size of file being written is too large. However in this case, a timeout is being set on the socket, and no large amount of data is being written to the socket. ~~

```
"System.Net.Sockets.SocketException (22): Invalid argument\n   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)"
System.Net.Sockets.dll!System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(System.Net.Sockets.SocketError error, string callerName) (Unknown Source:0)
System.Net.Sockets.dll!System.Net.Sockets.Socket.SetSocketOption(System.Net.Sockets.SocketOptionLevel optionLevel, System.Net.Sockets.SocketOptionName optionName, int optionValue, bool silent) (Unknown Source:0)
System.Net.Sockets.dll!System.Net.Sockets.Socket.SetSocketOption(System.Net.Sockets.SocketOptionLevel optionLevel, System.Net.Sockets.SocketOptionName optionName, int optionValue) (Unknown Source:0)
System.Net.Sockets.dll!System.Net.Sockets.Socket.ReceiveTimeout.set(int value) (Unknown Source:0)
System.Data.SqlClient.dll!System.Data.SqlClient.SNI.SNITCPHandle.Receive(out System.Data.SqlClient.SNI.SNIPacket packet, int timeoutInMilliseconds) (Unknown Source:0)
System.Data.SqlClient.dll!System.Data.SqlClient.SNI.TdsParserStateObjectManaged.ReadSyncOverAsync(int timeoutRemaining, out uint error) (Unknown Source:0)

```

cc @kburtram 

EDIT: The error code is EINVAL.

**Comment by saurabh500** [comment]
Related ADS issue https://github.com/Microsoft/azuredatastudio/issues/2914

**Comment by stephentoub** [comment]
22 is likely EINVAL

**Comment by saurabh500** [comment]
@stephentoub  Thanks for the correction about error codes.

I chatted with @kburtram offline to understand this better.
The value is being set to 30 seconds. There is a possibility that there was a connection close before the timeout was set and that causes this exception. The connection was sitting idle for 5 minutes, and then an operations was performed on the connection.

I looked at the wireshark traces, it looks like, due to absence of Keep Alive settings on the Sockets, the server (or perhaps another network device) is dropping the idle connection. I know that the Keep Alive Option for Unix was added using https://github.com/dotnet/corefx/pull/29963

However is there any setting (env var) that clients, on macOS and running on .Net Core 2.1, use, to set the Keep Alive for the .Net Core application?

**Comment by stephentoub** [comment]
> However is there any setting (env var) that clients, on macOS and running on .Net Core 2.1, use, to set the Keep Alive for the .Net Core application?

You're asking if the operating system exposes an environment variable or other global configuration that would enable keep-alive by default on all sockets?  Not that I'm aware of, but maybe @wfurt or @tmds knows?

**Comment by wfurt** [comment]
I don't think there is env variable. Most systems do have option to tune this globally. 
```
sysctl -A | grep net.inet.tcp.*keep
et.inet.tcp.keepidle: 7200000
net.inet.tcp.keepintvl: 75000
net.inet.tcp.keepinit: 75000
net.inet.tcp.keepcnt: 8
net.inet.tcp.always_keepalive: 0
```

The close should pop up if we try to read from the socket.

**Comment by saurabh500** [comment]
Thanks @wfurt
