### ISSUE TITLE
Should Memory<T> implement IEquatable<T>?

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#32905]
In the [.NET Standard](https://github.com/dotnet/standard/pull/909#discussion_r226390377) review of `Span<T>` @marek-safar wrote:

> Why it does not implement `IEquatable<T>` ?
> ...
> Well, if it's hard why do you have `public bool Equals(System.Memory<T> other)` ? I think it'd make sense to have the interface here if the implementation is there too.

It seems odd to providing a strongly typed `Equals` method but not implementing `IEquatable<T>`.

@KrzysztofCwalina @stephentoub @GrabYourPitchforks @jkotas

**Comment by KrzysztofCwalina** [comment]
I think we should implement it. Thanking said that it will have unexpected semantics, i.e. quasi referential equality. It will be especially surprising if ReadOnlyMemory<char> is used as a string slice.

**Comment by jkotas** [comment]
The `Memory<T>` in corefxlab implemented it originally, but we have later removed it in: https://github.com/dotnet/corefxlab/pull/1607/files. Why did we removed it?

**Comment by danmosemsft** [comment]
@ahsonkhan for the question above.

**Comment by ahsonkhan** [comment]
> Why did we remove it?

As @KrzysztofCwalina mentioned, it was because Equals does referential equality rather than deep value equality which might be unexpected for users. Regardless, we essentially implement the interface already (with the equals API), so I don't see any reason we shouldn't explicitly add the IEquatable back to the type.

Looking back at previous design discussions at the time when we removed it (i.e. https://github.com/dotnet/corefxlab/pull/1607), the meeting notes state: "We can remove the interface but keep the Equals methods", so that doesn't shed much light :p

**Comment by ostorc** [comment]
Is it up to grab? If so, could i try make PR for this issue?

**Comment by ahsonkhan** [comment]
> Is it up to grab? If so, could i try make PR for this issue?

That sounds great. Feel free to ping me on the PR for review. Thanks for the contribution.

**Comment by ostorc** [comment]
@ahsonkhan should I add IEquatable<T> to ReadOnlyMemory<T> or is thing for another issue?

**Comment by ahsonkhan** [comment]
> should I add IEquatable to ReadOnlyMemory or is thing for another issue?

**Yes, you should.** We don't have a separate issue for that since the interface applies naturally to the `ReadOnly` version as well.

**Comment by terrajobst** [comment]
@ahsonkhan 

Is the plan to wait for a community member to do the work? It would be nice if we could complete this for 3.0 so that we can also expose it from .NET Standard 2.1.

**Comment by Gnbrkm41** [comment]
Has this not been done yet? I can try to make the changes real quick.
* Make changes to the Memory<T> / ReadOnlyMemory<T> in coreclr's System.Private.CoreLib 
* Make the same changes in ref/System.Runtime's ones
* Add tests that compare these types via interface (should go into corefx/src/System.Memory/tests/(ReadOnly)Memory/Equality.cs?)

**Comment by ahsonkhan** [comment]
Yes. please, that would be awesome!

The previous PR was abandoned: https://github.com/dotnet/corefx/pull/35501

Ping me if you need any help (see https://github.com/dotnet/corefx/pull/35501#discussion_r259200377)

**Comment by Gnbrkm41** [comment]
Is that the only change required in coreclr? Shall I just open a PR (in coreclr) mentioning this issue with the changes?

**Comment by ahsonkhan** [comment]
> Is that the only change required in coreclr? Shall I just open a PR (in coreclr) mentioning this issue with the changes?

Yep. The three changes you mentioned above is what is required.

**Comment by Gnbrkm41** [comment]
Can this be closed now? I forgot to put `Fixes: #32905` in the PR ☺️ .

**Comment by stephentoub** [comment]
Thanks :)

**Comment by stephentoub** [comment]
Thanks :)

**Comment by stephentoub** [comment]
@terrajobst, is there a standard follow-up to be done here?

**Comment by terrajobst** [comment]
Yep. I'll submit the PR.
