### ISSUE TITLE
EnvelopedCms.Decrypt fails when the CEK is encrypted with OAEP-SHA256

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#32913]
https://github.com/dotnet/corefx/blob/d33f8435461028ec131fcfd42232098aaf3e6ded/src/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/AnyOS/ManagedPal.KeyTrans.cs#L88-L90 assumes that the OAEP OID means OAEP-SHA1, but it should instead decode the parameters.

https://stackoverflow.com/questions/52460001/get-pem-from-p7p8-files-using-c-sharp/ includes pointers to existing documents which can decrypt correctly with .NET Framework (and .NET Core on Windows with an attached private key), but fail when decrypted by the managed PAL (non-Windows, or Windows with a detached private key).

**Comment by vcsjones** [comment]
@bartonjs this looks like a fairly straight forward thing to fix, assuming I understand the correct fix. Basically `DecryptCek` needs to handle the other parameter values for OAEP here:

https://github.com/dotnet/corefx/blob/d33f8435461028ec131fcfd42232098aaf3e6ded/src/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/AnyOS/ManagedPal.KeyTrans.cs#L55-L62

then pass the parameters in to `DecryptCekCore` and set the padding to the correct value of `RSAEncryptionPadding `. It looks like `RSAEncryptionPadding` already has everything for OAEP-SHA2 family.

Is this something I can take off your plate, assuming I understand correctly?

**Comment by bartonjs** [comment]
@vcsjones Not sure how I missed the reply; but, yeah, if you want to take a crack at it, you're welcome to.

Because of https://github.com/dotnet/corefx/blob/5812dcbef2cde02a8213139085deefe666376f2c/src/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/Windows/DecryptorPalWindows.Decrypt.cs#L40-L46 I think that the answer will end up being something like:

* Add a new method for the Windows=>Managed jump to call which takes the whole `KeyEncryptionAlgorithm` object (assuming that it actually contains the parameters info; if not, then, uh, get that data from somewhere)
* The current `DecryptCek` and the new cross-call entrypoint should just call the same helper method to determine the RSAEncryptionPadding mode.
* DecryptCekCore should just accept that padding mode identifier.

But that's just from 3 minutes of re-assessment,

**Comment by vcsjones** [comment]
@bartonjs I should have a PR for this done soon; I have the managed PAL working, now for Windows.

Should we address encryption in this issue sonehow, or consider a new issue for that and address decryption only?

As it stands, encryption will always use SHA1 when using OAEP.

**Comment by bartonjs** [comment]
> As it stands, encryption will always use SHA1 when using OAEP.

I don't think it's possible to get encryption to choose OAEP right now, is it?  Accepting an RSAEncryptionPadding selector somewhere seems like it requires API, which makes it a different beast than a "process this data correctly" change.

**Comment by vcsjones** [comment]
@bartonjs 
>I don't think it's possible to get encryption to choose OAEP right now, is it?

Looking more carefully, I think you're right. There is not. This lead me to believe that it was:
https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/AnyOS/ManagedPal.KeyTrans.cs#L147-L153

However the caller of that function restricts it to PKCS1. I assumed based on the code snippet that there was support for id-RSAES-OAEP x509 certificates.

It seems that Windows supports RSA-OAEP certificates though.

![image](https://user-images.githubusercontent.com/361677/50577871-bcfc8c80-0dff-11e9-92bf-0ce65e2751a5.png)

**Comment by bartonjs** [comment]
> (perhaps you can help me understand why this case statement is here then?)

https://tools.ietf.org/html/rfc3560 says to allow it, which is probably where that popped in.  But I feel like some other RFC discourages using id-RSAES-OAEP as the public key algorithm.

The fact that 99% of RSA keys just use `(rsaEncryption, NULL)` as their algorithm identifier means that there really should be a parameter somewhere.  Probably an additional property hanging off the recipient info.
