### ISSUE TITLE
System.Diagnostics.EventLog and System.Management DLLs are not created when publishing a project targeting netstandard and Windows RID

### ISSUE THREAD

**Issue by hanblee** [dotnet/corefx#32910]
**Repro steps**:
1. create a new classlib project:
`dotnet new classlib`
2. add reference to System.Diagnostics.EventLog and System.Management
`dotnet add package System.Diagnostics.EventLog`
`dotnet add package System.Management`
3. publish the project
`dotnet publish`

**Expected behavior:**
RID specific publish output to contain System.Diagnostics.EventLog.dll and System.Management.dll
e.g., `netstandard2.0/publish/runtimes/win/lib/netstandard2.0/System.Diagnostics.EventLog.dll`

**Actual behavior:**
publish output only contains stub DLLs under `netstandard2.0/` which throw PNSE

**Note**
This behavior is different from other packages in the Windows Compatibility Pack. For example, when one publishes a classlib project with a reference to `Microsoft.Win32.Registry`, in addition to the stub DLL (`netstandard2.0/publish/Microsoft.Win32.Registry.dll`), win-RID specific DLL is created (`netstandard2.0/publish/runtimes/win/lib/netstandard2.0/Microsoft.Win32.Registry.dll`).

/cc @weshaggard

**Comment by karelz** [comment]
@wtgodbe @ericstj can you please help route it?

**Comment by ericstj** [comment]
The premise of this is broken: publishing for netstandard doesn't provide any guarantees of producing a runnable layout.  I've mentioned this before [here](https://github.com/dotnet/sdk/issues/1855#issuecomment-359918270) and [here](https://github.com/dotnet/corefx/issues/18217#issuecomment-293668929), and probably a dozen other places.  @terrajobst can you add this to the [FAQ](https://github.com/dotnet/standard/blob/master/docs/faq.md#how-is-net-standard-different-from-net-core) or share a doc?

That said if your goal is instead to share the RID specific implementations of these assemblies with more frameworks than just NETCoreApp, then the owners of those libraries would need to change their projects from cross-compiling for NETCoreApp-RID to netstandard-RID, [here](https://github.com/dotnet/corefx/blob/6080089a158075753b142994fcdb1a112ec02cf3/src/System.Diagnostics.EventLog/src/Configurations.props#L5) and [here](https://github.com/dotnet/corefx/blob/6080089a158075753b142994fcdb1a112ec02cf3/src/System.Management/src/Configurations.props#L6).

**Comment by hanblee** [comment]
@ericstj The use case for this is for plugin framework (the plugin host could be .NET Core or .NET Framework app) where the plugin dependencies are not known statically, but based on your description, targeting `netstandard2.0` and relaying on the output of `dotnet publish` for the plugin is NOT the right approach. Do you have any suggestion?

On the discrepancy between `Microsoft.Win32.Registry` and `Systems.Diagnostics.EventLog` as described in the **Note** section above, is it fair to say that the difference is due to how the library owners wrote their projects? The inconsistency among them is adding to the confusion.

**Comment by hanblee** [comment]
Opened #33150 requesting RID specific implementations for netstandard for these two packages.
