### ISSUE TITLE
POST'ing empty content throws an error in System.Net.Http

### ISSUE THREAD

**Issue by FUR10N** [dotnet/corefx#3292]
If I make a web request and get an HTTP 204 in return, `WinHttpRequestStream` throws an `IOException` with a success message as the inner exception.

It looks like a bug in `WinHttpRequestStream.WriteData`. `Interop.WinHttp.WinHttpWriteData` returns false if the response is a 204 (I guess because there is no content).
`Marshal.GetLastError` returns `0` though indicating that there was no error.

Should it check if `GetLastError() == 0` rather than checking the result of `Interop.WinHttp.WinHttpWriteData`?

I don't know if this is an issue with WinHttp or System.Net.Http, but I don't get this behavior on the version of the dll in Nuget.

**Comment by davidsh** [comment]
@FUR10N Since you're talking about `WinHttpRequestStream`, are you making a POST request and not a GET request to the server?  Can you clarify the HTTP verb you're using?

**Comment by davidsh** [comment]
Also, can you give a repro of what server returned the 204?  Or perhaps a trace of the response headers that came back?  That will help in the bug investigation.

**Comment by FUR10N** [comment]
The full output from fiddler is below.
It's a POST request and I don't think I can make the server I'm using available.

Did this code change from this release: https://www.nuget.org/packages/System.Net.Http/4.0.0

If I copy that DLL in then it works fine, but if I build it myself I get the error.

Request
```
POST https://... HTTP/1.1
Accept-Encoding: gzip, deflate
Accept: application/json
User-Agent: NET Client SDK/3.0.21.0
Accept-Language: en-US
Content-Length: 0
Content-Type: text/plain; charset=utf-8
Host: ...
Connection: Keep-Alive
Cookie: ...
```
Response
```
HTTP/1.1 204 No Content
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 0
Expires: -1
X-Robots-Tag: noindex
Date: Fri, 18 Sep 2015 11:19:13 GMT
```

**Comment by davidsh** [comment]
@FUR10N  Are you still seeing this problem with the latest GitHub code?

**Comment by FUR10N** [comment]
@davidsh I'll check on Monday

**Comment by davidsh** [comment]
Thx. In looking again at the Fiddler trace above, you appear to be doing a POST with empty content.  The 'Content-Length' request header shows up as 0 in the trace:

`
POST https://... HTTP/1.1
Accept-Encoding: gzip, deflate
Accept: application/json
User-Agent: NET Client SDK/3.0.21.0
Accept-Language: en-US
Content-Length: 0
Content-Type: text/plain; charset=utf-8
Host: ...
Connection: Keep-Alive
Cookie: ...
`

I think that is really the source of the bug. And that it doesn't have anything to do with the 204 response code. I have discovered a bug in the HttpClient where POST'ing a zero-length content results in an exception being thrown.

Are you creating an HttpContent object (StringContent, ByteArrayContent) when you call HttpClient with your POST?  How exactly are you calling HttpClient to do a POST?

**Comment by FUR10N** [comment]
@davidsh It works for me now. Thanks!

We are doing `HttpRequestMessage.Content = new StringContent("")` btw

**Comment by davidsh** [comment]
Thx for confirming the fix.
