### ISSUE TITLE
Problem with System.ComponentModel.Composition on netcoreapp2.0

### ISSUE THREAD

**Issue by MonkAlex** [dotnet/corefx#32933]
Create new project:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Composition" Version="4.5.0" />
  </ItemGroup>

</Project>
```
And code:
```c$
using System;
using System.ComponentModel.Composition.Hosting;

namespace netcore_test
{
  class Program
  {
    static void Main(string[] args)
    {
      var container = new CompositionContainer();
      Console.WriteLine("Hello World!");
    }
  }
}

```

Its work in VS (ctrl+f5), show hello world.

Now, try to publish as self-contained for win (x64 or x86):

`dotnet publish netcore_test.csproj /p:Configuration=Release /p:Platform=AnyCPU /p:TargetFramework=netcoreapp2.0 /p:PublishDir=bin\Publish\netcoreapp2.0\win-x64\ /p:SelfContained=true /p:RuntimeIdentifier=win-x64`

And get error:
```
Program.cs(2,29): error CS0234: The type or namespace name "Composition" does not exist in the namespace "System.ComponentModel" (are you missing an assembly reference?)
```

If add `/v:diag` to publish, then see, used `.nuget\packages\runtime.win-x64.microsoft.netcore.app\2.0.9\runtimes\win-x64\lib\netcoreapp2.0\System.ComponentModel.Composition.dll`.

If up project from `netcoreapp2.0` to `netcoreapp2.1` all work fine, but this look at bug.
And, `netcoreapp2.0` work on linux and macos.

**Comment by karelz** [comment]
.NET Core 2.0 is not supported since beginning of the month: https://github.com/dotnet/core/blob/master/release-notes/2.0/README.md
Given that it works on .NET Core 2.1, I will close it.

If you find that .NET Core 2.1 (latest servicing release), 2.2 (latest preview) or 3.0 (master builds) does not work, we can reopen. Thanks!
