### ISSUE TITLE
Microsoft.AspNetCore.App version flip in Mac Visual Studio

### ISSUE THREAD

**Issue by ptletski** [dotnet/corefx#32942]
I have an AspNetCore Web App project in Mac VS that is Restoring version 2.1.1 of Microsoft.AspNetCore.App every time I open the solution. I update to v2.1.5 and that works. When close and reopen the solution, the restoration process puts it back to version 2.1.1. Here are the dependencies listed in the deps.json file:

         "Microsoft.AspNetCore.App": "2.1.5",
          "Microsoft.EntityFrameworkCore": "2.1.4",
          "Microsoft.EntityFrameworkCore.Design": "2.1.4",
          "Microsoft.EntityFrameworkCore.Sqlite": "2.1.4",
          "Microsoft.EntityFrameworkCore.Sqlite.Design": "1.1.6",
          "Microsoft.EntityFrameworkCore.Tools": "2.1.4",
          "Microsoft.NETCore.App": "2.1.0",
          "Microsoft.VisualStudio.Web.CodeGeneration.Design": "2.1.5"

Here is the csproj list:

    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Design" Version="1.1.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.4" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.4" />

Anyone have some insight into what is going on?

**Comment by danmosemsft** [comment]
This issue was moved to aspnet/AspNetCore#3691

**Comment by ptletski** [comment]
My apologies. I am a noob.
