### ISSUE TITLE
Add StandardFormat.TryParse

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#32950]
@marek-safar [was asking](https://github.com/dotnet/standard/pull/916/files#r226819836) why `StandardFormat` has no `TryParse` method.

Any reason we didn't add it?

@ahsonkhan @KrzysztofCwalina?

**Comment by terrajobst** [comment]
Would be great if we could close on this for 3.0, this way we might be able to include in the upcoming .NET Standard 2.1.

**Comment by ahsonkhan** [comment]
I don't recall any particular reason for not adding it. Probably an oversight.

**Comment by terrajobst** [comment]
Looks good.

* We should remove `StandardFormat.Parse(string)` because this type cannot be (realistically) used from languages that don't support `Span<T>`, so relying on the implicit conversion sems fine. However, we cannot remove the API from .NET Core because it already shipped in 2.1. We could decide not expose this API from .NET Standard but that seems heavy handed as this API will now always show up in the diff.
* However, we'll only add one overload of `TryParse`
    - `public static bool TryParse(ReadOnlySpan<char> format, out StandardFormat result);`

**Comment by AlexejLiebenthal** [comment]
@terrajobst Couldn't you mark the API as [Obsolete] than and remove it maybe in .NET Core vNext?

If it is still up-for-grabs, I could try my luck and make a PR for this.

**Comment by AlexejLiebenthal** [comment]
I have a small behavior question.
I just realized that you maybe can't/shouldn't remove the Parse(string), and also should Add TryParse(string).
If you are working on netstandard1.1-2.0 or netcoreapp1.0-2.0 with System.Memory Package, than you didn't get the benefit of an implicit type conversion and you would always need to cast from string with .AsSpan().
Will the netstandard2.1 offer, like the implementation in netcoreapp2.1+, an implicit cast conversion from string to ReadonlySpan<char>?

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/dotnet/corefx/pull/33687.
