### ISSUE TITLE
Question about logic in MatchPattern()

### ISSUE THREAD

**Issue by iSazonov** [dotnet/corefx#32979]
Why `if (text.Length - index < Pattern.Length) { ...}` is not before line 210?
https://github.com/dotnet/corefx/blob/2f259de0bc566f4ef72e486133f71210416e440a/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexBoyerMoore.cs#L208-L223

**Comment by danmosemsft** [comment]
It does on the face of it seem wrong. Can you construct a unit test that would cause an exception? If so, we should probably fix that.

**Comment by iSazonov** [comment]
I meant that it should be:
```c#
private bool MatchPattern(string text, int index) 
 { 
     if (text.Length - index < Pattern.Length) 
     { 
         return false; 
     } 

     if (CaseInsensitive) 
     { 
         return (0 == string.Compare(Pattern, 0, text, index, Pattern.Length, CaseInsensitive, _culture)); 
     } 
     else 
     { 
         return (0 == string.CompareOrdinal(Pattern, 0, text, index, Pattern.Length)); 
     } 
 } 
```

**Comment by iSazonov** [comment]
> it'll be done inside the comparison method anyway which will be quick. 

I don't see  in `string.CompareOrdinal` that lengths is compared.

**Comment by Wraith2** [comment]
I've had a look and you're right, there's no specific length equality comparison in CompareOrdinal.. It may be that not doing it and forgoing the branch is faster than doing it, or perhaps it's an oversight. It would be interesting if you worked up some benchmarks with alternative implementations to see if it's worth adding one.

**Comment by danmosemsft** [comment]
Whether CompareOrdinal should be changed should be a separate issue.

@iSazonov I think your proposed change seems right, are you willing to offer a PR? Also, are there appropriate string.Equals overloads that can be used instead of string.Compare? In some cases they can be faster.

**Comment by iSazonov** [comment]
> are you willing to offer a PR?

Formally yes, but I can not compile CoreFX because of "DIA SDK not found". I have not found how to fix and can not do benchmarks.

> Also, are there appropriate string.Equals overloads that can be used instead of string.Compare?

We have:
```c#
public static bool Equals(string a, string b, StringComparison comparisonType)
public bool Equals(string value, StringComparison comparisonType)
public static bool Equals(string a, string b)
```
https://source.dot.net/#System.Private.CoreLib/shared/System/String.Comparison.cs,d47c1f57ad1e1e6e
https://source.dot.net/#System.Private.CoreLib/shared/System/String.Comparison.cs,b98069ccbe2d3960
https://source.dot.net/#System.Private.CoreLib/shared/System/String.Comparison.cs,680

I do not know whether it will win.
We will have to use `AsReadOnlySpan.Slice(index)`.

**Comment by MarcoRossignoli** [comment]
> Formally yes, but I can not compile CoreFX because of "DIA SDK not found". I have not found how to fix and can not do benchmarks.

@iSazonov try to follow https://github.com/dotnet/corefx/wiki/Development-environment-setup-for-Windows#visual-studio-2017 maybe it's a know bug `Note: If you have both VS 2017 and 2015 installed, you need to copy the DIA SDK directory from VS 2015 installation into VS 2017 (VS installer bug). The build script will detect the situation and tell you what to do.`

**Comment by iSazonov** [comment]
I see `string.CompareOrdinal` is SIMD accelerated and very fast.
