### ISSUE TITLE
Improve optimization strategy for BlockExpression

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#3297]
The check for optimization to N-ary specialized nodes in the Block factories only happens for the Expression[] overload. With the addition of IReadOnlyList&lt;T&gt; to the framework, we can also optimize the IEnumerable&lt;Expression&gt; overloads, similar to the changes proposed in #3288.

**Comment by VSadov** [comment]
related - https://github.com/dotnet/coreclr/issues/1592

**Comment by JonHanna** [comment]
Related: #3046
