### ISSUE TITLE
'AssemblyLoadContext' does not contain a definition for 'GetLoadedAssemblies'

### ISSUE THREAD

**Issue by xhoogland** [dotnet/corefx#32986]
https://github.com/dotnet/corefx/blob/0bfc4f3cf62f6fc29162ad5b1b89acc14124a375/src/System.Runtime.Extensions/src/System/AppDomain.cs#L241

Some time ago I was building a .NET Core CLI-program. While building I somehow needed the `AppDomain.CurrentDomain.GetAssemblies()`. Later on I found out that AppDomain's actually quite should not exist in .NET Core and looked for what it should be.

This whole story brought me to the line referenced in this issue and questioning what I am doing wrong? My VS2017 with latest .NET Core installed and framework set to netcoreapp2.1 produces the error as given in the title.
What am I doing wrong?

**Comment by karelz** [comment]
How do you get the error? Are you trying to compile CoreFX repo?
The API is not exposed:
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Loader/ref/System.Runtime.Loader.cs
https://apisof.net/catalog/System.Runtime.Loader.AssemblyLoadContext

But it does exist: https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.cs#L140

**Comment by karelz** [comment]
cc @janvorli @jkotas

**Comment by jkotas** [comment]
This API was never exposed in public surface. It is fine to use `AppDomain.CurrentDomain.GetAssemblies()` if you need to get list of all currently loaded assemblies.

cc @vitek-karas

**Comment by xhoogland** [comment]
Ah, then it makes sense indeed that I of course can't use the specified
method.

Then I'm still wondering how this then should have been done if we, for
example, did not have the AppDomain-class? I always had the idea that it
was, although partially, implemented due to people missing stuff and it
really is a .NET Framework-thing(ie).

In the end I somehow feel a bit weird for "using AppDomain" in .NET Core.
By discussing this it actually pops up in me that I don't even need this
anymore due to I already load an other project as dll via Assembly.Load.
Since all the types are actually in there I think it would be better for me
to only look in that one instead of what I do now. 🙂

**Comment by vitek-karas** [comment]
We are thinking about adding something like this to the public surface - basically list all the assemblies loaded into the load context. But as mentioned above, it can be done using the `AppDomain.GetAssemblies` in combination with `AssemblyLoadContext.GetLoadContext`, so it's not a priority right now.

**Comment by jkotas** [comment]
Note that the `GetAssemblies()` API is problematic regardless on whether it is on AppDomain or AssemblyLoadContext. It does not return all assemblies that the app can or will load. It just returns assemblies that the app have loaded so far. This set may be missing assemblies and it can change due to very subtle changes. For example, more aggressive JIT optimizations may trigger more inlining that will cause the set of loaded assemblies to grow.

Robust applications should never use the `AppDomain.CurrentDomain.GetAssemblies()` API.
