### ISSUE TITLE
Add remove Range to sorted List

### ISSUE THREAD

**Issue by hernot** [dotnet/corefx#32987]
`SortedList` and `SortedList<TKey,TValue>` llack a `removeRange` method allowing to remove a set of consecutive elements by their key all at once.

# Rational and Usage 
Currently SortedList and SortedList<TKey,TValue> allow to remove single elements by their index or key index only. They do it by moving the following elements forward by calling Array copy. If it now happens to be that the removed elements are located on consecutive indices and they have to be removed at once than there exist the follwowing two solutions with worst case behaviour of O(N^2):

1. Create a new SortedList or SortedList<Tkey,TValue>  and add all elements to keep a new using Add

```cs
SortedList newlist = new SortedList(oldlist.Count - (lastremove - firstremove))

for ( int index = 0; index < firstremove; index ++ ) {
    newlist.Add(oldlist[index]); 
}

for ( int index = lastremove; index < oldlist.Count ; index ++ ) {
    newlist.Add(oldlist[index]); 
}
```
2. call RemoveAt repeatedly until the first element to keep is reached.3. 
```cs
for ( int remove = firstremove; remove < lastremove; remove  ++ ) {
    slist.removeAt(remove);
}
```

With the proposed method these elements could be removed all at once requiring only one call to Array.Copy resulting in a worst case behaviour of O(N).

# Proposed API
```diff
[System.Runtime.InteropServices.ComVisible(true)]
[System.Serializable]
public class SortedList : ICloneable, System.Collections.IDictionary
{
    ...
+  public void RemoveRange(int index, int count);
    ...
}

public class SortedList<TKey,TValue> : System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>, System.Collections.Generic.IDictionary<TKey,TValue>, System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<TKey,TValue>>, System.Collections.Generic.IReadOnlyCollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>, System.Collections.Generic.IReadOnlyDictionary<TKey,TValue>, System.Collections.IDictionary
{
    ...
+  public void RemoveRange(int index, int count);
    ...
}
```
# Details and Open Questions
Currently None

**Comment by jbhensley** [comment]
Signature should probably match `List<T>`:

```C#
public void RemoveRange(int index, int count) 
```

**Comment by hernot** [comment]
Agree

**Comment by safern** [comment]
@hernot could you please update the issue to include a formal api proposal? I think it makes sense to have this API but we need to include Rationale and Usage. Once you've done that I can bring it over to API Review to get its approval and then implement it. 

Here is an example of an API Proposal: https://github.com/dotnet/corefx/issues/30953#issue-339950811

**Comment by hernot** [comment]
Done. Please let me know if that is sufficient and clear enough

**Comment by safern** [comment]
Thanks, @hernot. I've marked as api-ready-for-review.

**Comment by terrajobst** [comment]
The generic sorted list doesn't allow indexing by `int`, however, it does expose a `RemoveAt` method. But we'd have to make sure this plays nicely for cases where custom compares are used that, for example, take into consideration the number of elements and use different sorting.

Right now, we're not convinced the usability and minor performance gains are motivating enough. Feel free to push back though and provide more arguments :-)

**Comment by carlreinke** [comment]
@terrajobst The existing [`SortedList<TKey, TValue>.RemoveAt(int)`](https://github.com/dotnet/corefx/blob/dcc9f626eeb0751d4ba4499f623aac42d2e95c10/src/System.Collections/src/System/Collections/Generic/SortedList.cs#L696-L715) doesn't take any unusual sorting scenarios into consideration -- those scenarios are for hashcode-based collections, not for sorted collections.

**Comment by hernot** [comment]
Hi

Inline Response (answers below questions asked)
Message sent on Dienstag, 01.10.2019, 12:06 -0700 by Immo Landwerth:
> The generic sorted list doesn't allow indexing by `int`, however, it
> does expose a `RemoveAt` method. But we'd have to make sure this
> plays nicely for cases where custom compares are used that, for
> example, take into consideration the number of elements and use
> different sorting.
> 

Hm. Let me think about it. In a first thought, i would consider such a
comparer mixing parameters intrinsic to the elements to be sorted with
those of the resulting sorted list as a bad or broken design. At least
i did not come across any use case where i would have needed that. 
Second in case there are use cases for such exotic custom sorter which
could not be solved by other means than i would consider the parameters
like number of elements already in the list a unique integral part of
the elements to be sorted. With the consequence that any time an
element is added or removed these parameters have to be recomputed for
the resulting set of elements, and the whole list would have to be
sorted anew anyway. If that is not done the list would be in undefined
sort state anyway after adding or removing a single element.
As a consequence in this very specific context of for the vast majority
of programmers negligible use cases the concept of range doesn't make
sense at all. Thus calling RemoveRange would definitely be a severe
design error and if not a fatal implementation bug. 

In 99% of all cases, that would be 100% of all cases I came across so
far, sorting including those where a custom comparer hast to be used
would be based upon parameters and values intrinsic to the elements to
be sorted only. And in this Context the concept of Fange and thus the
RemoveRange method do make a lot of Sense. Not just cause of speedup,
also in Reduction in lines of code which have to be written over and
over again. One call to RemoveRange is less error prone than writing 

for ( int rem = removeidx + 1; rem < nextokeep; rem ++ )
list.removeat(rem);

And third other list type collection do have a RemoveRange method thus
by adding RemoveRange to sorted list interface would be more consistent
with the rest of the standard library.
> Right now, we're not convinced the usability and minor performance
> gains are motivating enough. Feel free to push back though and
> provide more arguments :-)

Due to rules of GitHub I'm not allowed to push back this issue without
reopening it as a new issue, cause i did not close it my self, but was
closed by you. So if this email is refused, i will reopen as new issue
with reference to this one. As your arguments why not considering it at
least as low or very low priority issue are not convincing to me, see
above.


Best
Xritoph (Hernot)

**Comment by terrajobst** [comment]
@hernot 

> for ( int rem = removeidx + 1; rem < nextokeep; rem ++ ) list.removeat(rem);

Sure, but how often do you have to write code like this? It seems quite rare.

**Comment by hernot** [comment]
Not less often than i need to write it for List<T> and that has that interface already.
