### ISSUE TITLE
Issues building System.Runtime.sln

### ISSUE THREAD

**Issue by svick** [dotnet/corefx#32980]
I am trying to build System.Runtime.sln (at 2555441)  and I an encountering some issues. What I did:

1. `git clean -xdf`
2. `build.cmd`

    This command succeeds successfully, but with over 5000 warnings. I haven't checked them all, but they seem to be all similar to:

    > C:\Users\Svick\\.nuget\packages\microbuild.core\0.2.0\build\MicroBuild.Core.targets(4,5): warning MSB4011: "C:\Users\Svick\\.nuget\packages\microbuild.plugins.swixbuild\1.1.0-g0701ee829f\build\MicroBuild.Plugins.SwixBuild.targets" cannot be imported again. It was already imported at "C:\code\corefx\Tools\MicroBuild.Core.targets (4,5)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\code\corefx\pkg\Microsoft.Private.PackageBaseline\Microsoft.Private.PackageBaseline.pkgproj]
3. Open src\System.Runtime\System.Runtime.sln in VS 15.8.7.

    The System.Reflection.TestModule project fails to load, with the message:

    > C:\code\corefx\src\System.Runtime\tests\TestModule\System.Reflection.TestModule.ilproj : error  : Project file is incomplete. Expected imports are missing.

4. Attempt to Build the solution from VS.

   I get two errors:

    > Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4062	The "GenFacadesTask" task could not be loaded from the assembly C:\Users\Svick\\.nuget\packages\microsoft.dotnet.genfacades\1.0.0-beta.18478.5\build\\../tools/netcoreapp2.1/Microsoft.DotNet.GenFacades.dll. Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	System.Runtime (src\System.Runtime)	C:\Users\Svick\\.nuget\packages\microsoft.dotnet.genfacades\1.0.0-beta.18478.5\build\Microsoft.DotNet.GenFacades.targets	97	
Error	IDE1003	Analyzer assembly 'C:\Users\Svick\\.nuget\packages\microsoft.dotnet.codeanalysis\1.0.0-beta.18519.7\analyzers\Microsoft.DotNet.CodeAnalysis.dll' depends on 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' but it was not found. Analyzers may not run correctly unless the missing assembly is added as an analyzer reference as well.	System.Runtime		1	Active

Am I doing something wrong? Or could it be some issue with my machine?

**Comment by danmosemsft** [comment]
@weshaggard @wtgodbe

**Comment by svick** [comment]
If I run `dotnet msbuild` (using .Net Core SDK 2.1.403) in the src\System.Runtime directory, I get yet another error:

> System.Reflection.TestModule.il(10): error : Error: ilasm on CoreCLR does not support full sign. [C:\code\corefx\src\System.Runtime\tests\TestModule\System.Reflection.TestModule.ilproj]

**Comment by ViktorHofer** [comment]
> If I run dotnet msbuild (using .Net Core SDK 2.1.403) in the src\System.Runtime directory, I get yet another error:

That is fixed with https://github.com/dotnet/corefx/commit/a8fc4418080e66d97f337e7b663a88b047f1e2e0#diff-b2c0f8d4ddbc9f9edb5eb80cc6adc964. Closing.
