### ISSUE TITLE
trailing slash breaks path algebra

### ISSUE THREAD

**Issue by Spongman** [dotnet/corefx#32982]
for example, `System.AppContext.BaseDirectory` returns paths with trailing slashes.

however these are all wrong:
```
Directory.GetParent(@"c:\temp\foo\") --> @"c:\temp\foo"
Path.GetDirectoryName(@"c:\temp\foo\") --> @"c:\temp\foo"
Path.GetFileName(@"c:\temp\foo\") --> ""
Path.ChangeExtension(@"c:\temp\foo\", ".bak") --> @"c:\temp\foo\.bak"
```

**Comment by danmosemsft** [comment]
@Spongman do you mean, we aren't consistently including trailing slashes on paths that represent directories? I am not sure we have ever been consistent about that, and you should use `Path.Join` to combine them. @JeremyKuhne ?

**Comment by JeremyKuhne** [comment]
These APIs are documented to behave the way you've described. They're simple path segment helpers. Changing the behavior for an empty final path segment would be a large breaking change both from a behavior and a perf perspective, even if we think the behavior should have been designed differently.

I generally don't recommend manipulating paths with trailing separators. Besides what you see above, trailing separators can get you into trouble in other ways. Path comparison being one case- `@"C:\temp\foo"` is the same path as `@"C:\temp\foo\"`.

**Comment by svick** [comment]
@JeremyKuhne 

> I generally don't recommend manipulating paths with trailing separators.

In that case, shouldn't `AppContext.BaseDirectory` ensure it returns a path *without* trailing separators?

**Comment by jkotas** [comment]
> `AppContext.BaseDirectory`

It used to return path *without* trailing separator. But then we have *fixed* it to add the trailing separator to improve compatibility: https://github.com/dotnet/coreclr/issues/10920

**Comment by JeremyKuhne** [comment]
> In that case, shouldn't AppContext.BaseDirectory ensure it returns a path without trailing separators?

Yes, but as @jkotas points out, we're stuck with the old behavior for compatibility reasons. 😭 If I could go back in time...

**Comment by Spongman** [comment]
ok, so we're left with inconsistent trailing separator usage, and APIs that fail silently?

**Comment by JeremyKuhne** [comment]
> ok, so we're left with inconsistent trailing separator usage, and APIs that fail silently?

Unfortunately yes. As stated, we cannot change things like this as existing code will be dependent on the way the current `Path` APIs interact with trailing separators. We can't change the `Path` APIs handling of the separators as that would break even more apps. What we can potentially do is add **new** APIs that help to reduce confusion. We did just that for `Path.Join` (over `Path.Combine`).

I have written `GetDirectoryOrFileName()` in prior teams to address part of what you're talking about here. If there is interest in that sort of thing we can open an API proposal for it.
