### ISSUE TITLE
Add testing for IClassFactory2 interop

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#32999]
LicenseManager.LicenseInteropHelper supports interop for IClassFactory2 implementations as follows:
https://github.com/dotnet/corefx/blob/95941fcdc1154260a4ee1e5db618bc49df24b46b/src/System.ComponentModel.TypeConverter/src/System/ComponentModel/LicenseManager.LicenseInteropHelper.cs#L13-L26

We don't have coverage for these scenarios today, nor do we have established patterns for testing COM in CoreFx.  @luqunl shared a trick for this in https://github.com/dotnet/corefx/issues/32494 but I tried making this work for ICF2 and couldn't get it to do what I wanted.  We need some deeper investigation here and need to plug the test gap in either CoreFx or CoreCLR, potentially by implementing native COM servers/clients if we can't get the trick linked above to work.

**Comment by AaronRobinsonMSFT** [comment]
See https://github.com/dotnet/coreclr/issues/20563

**Comment by AaronRobinsonMSFT** [comment]
Fixed with https://github.com/dotnet/coreclr/pull/22846
