### ISSUE TITLE
Unix: behavior of Environment.GetFolderPath when user home directory cannot be determined

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#33001]
When `Environment.GetFolderPath` fails to determine the user's home directory, it silently falls back to `/tmp` on Unix.
It is very unlikely that we are unable to determine the user's home directory.
When it happens maybe we shouldn't fall back from an expected user-specific location to one that is shared with everyone on the system.

We could return `""`. This is behavior of GetFolderPath for SpecialFolders it doesn't know how to map. It can lead to being interpreted as the working directory. For example:
```
Directory.CreateDirectory(Path.Combine(Environment.GetFolderPath(SpecialFolder.MyDocuments), ".myapp"));
```

We could throw. This may cause apps to fail that would work without a home dir.

Mono returns "/": https://github.com/mono/mono/blob/c5b88ec4f323f2bdb7c7d0a595ece28dae66579c/mono/eglib/gmisc-unix.c#L159-L160.
This won't cause the app to fail immediately, but probably at a later point when it tries to create/read an app specific file/folder under home for which it doesn't have permissions.

@danmosemsft @stephentoub wdyt?

**Comment by danmosemsft** [comment]
We should definitely not fall back silently to a less secure location..
