### ISSUE TITLE
[API Proposal] Add ReadOnlySequence<T>.GetFirstSpan()

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#33029]
We have a property on `ReadOnlySequence<T>` that returns a `ReadOnlyMemory<T>`.
```C#
public readonly partial struct ReadOnlySequence<T>
{
    public ReadOnlyMemory<T> First { get { throw null; } }
}
```

We should consider adding a `GetFirstSpan() `method as a performance optimization since it can be implemented faster than accessing the property: `First.Span`. This is because slicing a `Span<T>` is faster than slicing a `Memory<T>`.

**API Addition:**
```C#
public readonly partial struct ReadOnlySequence<T>
{
    public ReadOnlySpan<T> GetFirstSpan() { throw null; }
    // OR a property instead?
    public ReadOnlySpan<T> FirstSpan { get { throw null; } }
}
```

**Open Questions:**
- Should it be a property like First, or should it be a method?

One scenario where this is useful is BufferReader. It can potentially improve the cost of creating a BufferReader by ~10%.

```C#
public BufferReader(ReadOnlySequence<T> buffer)
{
    CurrentSpanIndex = 0;
    Consumed = 0;
    Sequence = buffer;
    _currentPosition = buffer.Start;
    _nextPosition = default;
    CurrentSpan = buffer.First.Span; // buffer.GetFirstSpan();
   ...
}
```

**Example implementation diff between get_First and GetFirstSpan():**
![image](https://user-images.githubusercontent.com/6527137/47470032-c2fb3f00-d7b8-11e8-8d4f-ee4d1e6b687d.png)

https://www.diffchecker.com/8BWywQZA

cc @JeremyKuhne, @davidfowl, @pakrym

**Comment by davidfowl** [comment]
Is that 10% in both array based on multi segment scenarios?

**Comment by davidfowl** [comment]
These changes sound great! I just looked and pipelines uses `ReadOnlySequenceSegment` so I'm happy. 

> MemoryManager: 5% regression

Do we have anything concrete that uses these?

**Comment by davidfowl** [comment]
I think it should be called FirstSpan and be a property.

**Comment by ahsonkhan** [comment]
> These changes sound great! I just looked and pipelines uses `ReadOnlySequenceSegment` so I'm happy. 

I would imagine mutli-segment ROSSegment is the most common case given the whole point of ReadOnlySequence is sequence of segments. I want to optimize the implementation for that case (and maybe array).

> Do we have anything concrete that uses these?

Not really. Mainly diagnostics which is why I think it is fine to make the trade-off in terms of perf:
https://github.com/aspnet/KestrelHttpServer/blob/1f3524787e62db9890547b33e8a450441b14810b/shared/Microsoft.Extensions.Buffers.MemoryPool.Sources/DiagnosticPoolBlock.cs#L14

**Comment by pakrym** [comment]
`FirstSpan` sounds good.

**Comment by scalablecory** [comment]
Attempting to optimize this sequence use myself and found a nice `internal` method `GetFirstSpan`... Would love to see this change get into the 3.0 release.

**Comment by ahsonkhan** [comment]
> Attempting to optimize this sequence use myself and found a nice `internal` method `GetFirstSpan`... Would love to see this change get into the 3.0 release.

Can you file a new issue for that please. We should consider it separately.

cc @JeremyKuhne

**Comment by davidfowl** [comment]
We didn't add this to ns2.1 😢

**Comment by davidfowl** [comment]
cc @terrajobst
