### ISSUE TITLE
ZipArchive does not indicate in any way if file length specified in central directory does not match the actual file length.

### ISSUE THREAD

**Issue by agr** [dotnet/corefx#33058]
```
>dotnet --version
2.1.500-preview-009335
```

The following zip archive: [tttt.zip](https://github.com/dotnet/corefx/files/2517033/tttt.zip) has corrupted central directory entry making it report the length of the compressed file `tttt.txt` to be 256 bytes. All zip archivers I tried so far fail to extract that file one way or another. But `ZipArchive` seem to completely ignore the discrepancy:

```c#
using System;
using System.IO;
using System.IO.Compression;

namespace BrokenZipCoreTest
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var za = ZipFile.OpenRead(@"E:\dev\tttt.zip"))
            {
                var e = za.GetEntry("tttt.txt");
                Console.WriteLine("entry length: {0}", e.Length);
                using (var ms = new MemoryStream())
                {
                    using (var source = e.Open())
                    {
                        source.CopyTo(ms);
                    }

                    Console.WriteLine("actual length: {0}", ms.Length);
                }
            }
        }
    }
}
```
produces the following output:

```
entry length: 256
actual length: 39208160
```
No exceptions thrown.

I'm not 100% sure, but I think the library should detect it, instead of proceeding silently.

**Comment by agr** [comment]
Is there any chance of fixing it in .NET framework, too?

**Comment by buyaa-n** [comment]
@agr I have created bug for .Net framework so that they would decide if they would ship the fix https://devdiv.visualstudio.com/DevDiv/_workitems/edit/888193/

Also @agr could we use the file `tttt.zip` for testing purpose and distributee it on nuget?

**Comment by agr** [comment]
Yeah, sure. If you want a code that generates such files, you might salvage something from here:

https://github.com/NuGet/NuGetGallery/blob/1eff45eac940922495af949ea30fda4daee6045f/tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs#L1038-L1066

`packageStream` there is the memory stream with zip archive contents, `fileName` is the filename inside the archive which gets it size patched and `fileContents` is the text contents of the file, which is only used to calculate the file size for verification purposes.

**Comment by buyaa-n** [comment]
Great, thank you @agr
