### ISSUE TITLE
Handle leak while creating processes simultaneously from two threads causes spurious deadlocks

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/corefx#33069]
The fundamental issue is the same on all platforms. The varying behaviors are due to technical details of the platforms.

On Windows, the following leaks are possible:

When creating two processes that redirect handles, standard IO reader and writer handles can leak from one process being created to another process being created.

The following deadlock is possible:

`.ReadToEnd()` won't terminate because the standard output/error writer handle was inherited into another process that is waiting for input.

On Mac OSX the following leaks are possible:

When creating two processes that redirect handles, standard IO reader and writer handles can leak from one process being created to another process being created.

The following deadlocks are possible:

`.ReadToEnd()` won't terminate because the standard input writer was inherited into another process that is waiting for input.

`.ReadToEnd()` won't terminate because the standard output/error writer handle was inherited into another process that is waiting for input.

No leaks are possible on Linux because `pipe2()` is used correctly.

Solution, MAC OSX:

In https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs

            // Lock to avoid races with OnSigChild
            // By using a ReaderWriterLock we allow multiple processes to start concurrently.
    #if HAVE_PIPE2
            s_processStartLock.EnterReadLock();
    #else
            // Simultaneous create process doesn't work on Mac OSX because the lack of a pipe2() system call causes handles to leak from one process being created to another.
            s_processStartLock.EnterWriteLock();
    #endif

    #if HAVE_PIPE2
         s_processStartLock.ExitReadLock();
    #else
         s_processStartLock.ExitWriteLock();
    #endif

On Windows, we can either take the same choice of putting an exclusive lock around the whole thing, or we can use STARTUPINFOEX as documented here: https://blogs.msdn.microsoft.com/oldnewthing/20111216-00/?p=8873

This is the last issue driving #306 ; when this is fixed #306 is made irrelevant and can be closed (kestrel would still break if using libuv and started simultaneously with create process in another thread but libuv is no longer the default).

**Comment by joshudson** [comment]
So that was actually a bit embarrassing. Somebody fixed the Windows side before System.Diagnostics.Process was added into the github tree. The bug never got publicly acknowledged before. I've been adding defense code against this for no reason for a long time.

**Comment by jkotas** [comment]
> Somebody fixed the Windows side before System.Diagnostics.Process was added into the github tree

Still, it would be nice to change Windows to use the proper solution using `STARTUPINFOEX.` The lock is not ideal: It is potential perf bottleneck, and it handle the case when there is some other unrelated code creating the process as well.

**Comment by joshudson** [comment]
@jkotas : I thought significantly about that. If we change it there to use STARTUPINFOEX (and I believe we should) we have a lot more work to.

1) We should change both sides to use the same behavior. It would look horrible if all P/Invoke created handles are inherited on Linux/Mac/*BSD and none on Windows.

2) This is the backwards compatibility fight that started the big debate in #306 in the first place.

On the other hand, if your bottlenecking on *creating processes* on Windows I want to know what you are doing. The DLL startup proceeds asynchronously no matter what the lock does here so that would be really hard to pull off.

**Comment by jkotas** [comment]
Ok, I see. I have not realized that `STARTUPINFOEX` would not fork for the existing implementation.
