### ISSUE TITLE
MultipartFormDataContent does not set ContentDisposition header fields if a header already exists

### ISSUE THREAD

**Issue by norachuga** [dotnet/corefx#33071]
https://github.com/dotnet/corefx/blob/a055f49d5eacf2022bdad255291e2a62c6cd6671/src/System.Net.Http/src/System/Net/Http/MultipartFormDataContent.cs#L78-L90

MultipartFormDataContent provides two overloads for setting the Name and FileName (and FileNameStar) fields on the ContentDisposition header when adding an HttpContent to the multipart content.

```c#
public override void Add(HttpContent content);
public void Add(HttpContent content, string name);
public void Add(HttpContent content, string name, string fileName);
```
However, the underlying method, AddInternal only sets these if there is no existing ContentDisposition header. If one exists already, the name and fileName parameters will be completely ignored.

Example:
```c#
var myFile = new ByteArrayContent(bytes);
multipartFormDataContent.Add(myFile, "attachment", "foo.txt");

//versus

var myFile = new ByteArrayContent(bytes);
myFile.Headers.ContentDisposition = new ContentDispositionHeaderValue("form-data");
multipartFormDataContent.Add(myFile, "attachment", "foo.txt");
```
The latter example will produce an invalid result. The result is the same as if they had simply called .Add(myFile).

I feel this is an unexpected behavior. If the user wanted the existing header to go untouched, they would not have used these overloads to provide a name and/or filename.

My expectation for how these methods should behave is like so:
```c#
        private void AddInternal(HttpContent content, string name, string fileName)
        {
            if (content.Headers.ContentDisposition == null)
            {
                content.Headers.ContentDisposition = new ContentDispositionHeaderValue(formData);
            }

            content.Headers.ContentDisposition.Name = name;

            if (fileName != null)
            {
                content.Headers.ContentDisposition.FileName = fileName;
                content.Headers.ContentDisposition.FileNameStar = fileName;
            }
            
            base.Add(content);
        }
```

I was unable to find any documentation in either .NET Core or .NET Framework clarifying this is the expected behavior, so I can't say if this is a bug or is a behavior that should be preserved as-is.

**Comment by karelz** [comment]
Does it behave the same (potentially incorrect) way on both .NET Framework and .NET Core? Which versions did you try? (4.7.2 and 2.1)

**Comment by karelz** [comment]
Triage: It would be technical breaking change -- either we would override the value, or we would throw exception.
Given there is only 1 bug report in last year, we don't think it is worth the risk of breaking libraries even in major version of .NET Core.
If there are more customers running into this, we can revisit the decision.
