### ISSUE TITLE
EngineExecutionException possibly related to use of isinst

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#3308]
The following code is very similar to the proposed change in #3288 where an "as" expression is used to perform a type check against a collection.

```
    using System;
    using System.Generic.Collections;

    class Program
    {
        static void Main(string[] args)
        {
            var N = int.Parse(args[0]);

            var res = new List<object>();

            for (var i = 0; i < N; i++)
            {
                object o = Do(new Bar[] { new Bar() }); // <==== THROWS HERE
                res.Add(o);
            }

            Console.WriteLine("Done.");
        }

        static object Do(IEnumerable<Bar> es)
        {
            var l = es as IList<Bar>;
            if (l != null)
            {
                // var c = l.Count;
            }

            return new object();
        }
    }

    class Bar
    {
    }
```

Building the above in Debug build and running it with 'coreclr repro.exe 10000000' consistently causes an EngineExecutionException after a while (one order of magnitude less iterations is not sufficient to trigger the fatal condition). Unfortunately, my WinDbg is experiencing some issues so wasn't able to dig deeper yet.

It also repros if the Bar[] is substituted for a List&lt;Bar&gt;.

**Comment by bartdesmet** [comment]
Maybe related to https://support.microsoft.com/en-us/kb/2679415?

**Comment by stephentoub** [comment]
@jkotas, I was able to repro this on .NET 4.6 64-bit as well.

**Comment by jkotas** [comment]
@Maoni0 this looks like a GC bug to me

```
clr!WKS::gc_heap::gcmemcopy+0x6dd6c [f:\dd\ndp\clr\src\vm\gc.cpp @ 23963]
clr!WKS::gc_heap::compact_plug+0xe9 [f:\dd\ndp\clr\src\vm\gc.cpp @ 24051]
clr!WKS::gc_heap::compact_in_brick+0x6a [f:\dd\ndp\clr\src\vm\gc.cpp @ 24179]
clr!WKS::gc_heap::compact_in_brick+0x98 [f:\dd\ndp\clr\src\vm\gc.cpp @ 24152]
clr!WKS::gc_heap::compact_in_brick+0x98 [f:\dd\ndp\clr\src\vm\gc.cpp @ 24152]
clr!WKS::gc_heap::compact_in_brick+0x9c [f:\dd\ndp\clr\src\vm\gc.cpp @ 24194]
clr!WKS::gc_heap::compact_phase+0x1c5 [f:\dd\ndp\clr\src\vm\gc.cpp @ 24332]
clr!WKS::gc_heap::plan_phase+0xc32 [f:\dd\ndp\clr\src\vm\gc.cpp @ 22129]
clr!WKS::gc_heap::gc1+0x9d [f:\dd\ndp\clr\src\vm\gc.cpp @ 14977]
clr!WKS::gc_heap::garbage_collect+0x264 [f:\dd\ndp\clr\src\vm\gc.cpp @ 16502]
```

**Comment by stephentoub** [comment]
@Maoni0 shared that she believes this is the same issue as https://github.com/Microsoft/visualfsharp/issues/566 and that she has a fix almost ready.

**Comment by Maoni0** [comment]
This will be released in a hotfix soon. if you have a (full memory) dump I'd be happy to verify whether you are hitting the same issue as the one above. Most likely yes but I can check to be sure.

**Comment by stephentoub** [comment]
@Maoni0, was this issue fixed? @bartdesmet, does this still repro for you?

**Comment by Maoni0** [comment]
Yes, this was fixed a while ago. Please see Lee's comments at https://blogs.msdn.microsoft.com/maoni/2015/08/12/gen2-free-list-changes-in-clr-4-6-gc/.
