### ISSUE TITLE
FileOptions.Asynchronous causes Filestream.Write() to expand the file length before writing data, resulting in invalid data being read during a concurrent Read operation

### ISSUE THREAD

**Issue by zmhh** [dotnet/corefx#33081]
Windows 10
.NET Core 2.1.300

**Summary: FileOptions.Asynchronous causes a change in behavior of FileStream which results in incorrect Writes/Reads**

Background: I am implementing a persistent queue in which I write items to disk then read them off of disk. The purpose of this is so that on unexpected shutdown we don't lose data in the queue.

When testing I noticed a race condition where the byte arrays I was reading back were incorrect. Specifically, the array would contain a series of bytes with a value of 0. The 0s could be at the start of the array, in the middle, or at the end. After lots of confusion I noticed that the issue disappeared when I removed FileOptions.Asynchronous from the stream constructor.

The buffer size seems to play a role. The issue occurred much more quickly when I set a small buffer size such as 10 bytes.

The following code demonstrates the issue:

```c#
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading;
using System.Threading.Tasks;

namespace testproj
{
    class Program
    {
        static void Main(string[] args)
        {
            var filepath = "testfile";
            if (File.Exists(filepath)) File.Delete(filepath);

            // Remove FileOptions.Asynchronous from writerStream and the test will not throw an exception
            var writerStream = new FileStream(filepath, FileMode.OpenOrCreate, FileAccess.Write, FileShare.Read, 10, FileOptions.Asynchronous);
            var readerStream = new FileStream(filepath, FileMode.OpenOrCreate, FileAccess.Read, FileShare.ReadWrite, 10, FileOptions.Asynchronous);

            var numMessages = 1000;
            var messageSize = 1024;
            var messageList = GenerateRandomBytes(numMessages, messageSize);

            var deserializedMessageList = new List<byte[]>();
            var numDeserialized = 0;
            Task.Run(() =>
            {
                while (numDeserialized != numMessages)
                {
                    if (readerStream.Length - readerStream.Position < messageSize) continue;
                    byte[] buffer = new byte[messageSize];

                    var read = readerStream.Read(buffer, 0, buffer.Length);
                    while (read != buffer.Length)
                    {
                        read += readerStream.Read(buffer, read, buffer.Length - read);
                    }
                    
                    deserializedMessageList.Add(buffer);
                    numDeserialized++;
                }
            });

            foreach (var msg in messageList)
            {
                writerStream.Write(msg, 0, msg.Length);
            }
            writerStream.Flush(true);

            SpinWait.SpinUntil(() => numDeserialized == numMessages, 5000);
            AssertEqual(messageList, deserializedMessageList);
            
            Console.WriteLine("Successful run");
            Console.ReadLine();
        }

        private static void AssertEqual(IList<byte[]> l1, IList<byte[]> l2)
        {
            if (l1.Count != l2.Count) throw new Exception($"List counts not equal. l1: {l1.Count}. l2: {l2.Count}.");

            for (int i = 0; i < l1.Count; i++)
            {
                try
                {
                    AssertEqual(l1[i], l2[i]);
                }
                catch (Exception ex)
                {
                    throw new Exception($"Byte array {i} not equal.  Exception message: {ex.Message}");
                }
            }
        }

        private static void AssertEqual(byte[] b1, byte[] b2)
        {
            if (b1.Length != b2.Length) throw new Exception("Array length not equal.");

            for(int i = 0; i < b1.Length; i++)
            {
                if (b1[i] != b2[i])
                {
                    throw new Exception($"{b1[i]} != {b2[i]}");
                }
            }
        }

        private static IList<byte[]> GenerateRandomBytes(int numMessages, int msgByteSize)
        {
            var msgList = new List<byte[]>();

            Random rnd = new Random();
            for (int i = 0; i < numMessages; i++)
            {
                var item = new byte[msgByteSize];
                rnd.NextBytes(item);

                msgList.Add(item);
            }

            return msgList;
        }
    }
}
```

**Comment by joshudson** [comment]
This code does not look right. Adding FileOptions.Asynchronous and proceeding to call Read() and Write() like it were synchronous seems like an error.

**Comment by stephentoub** [comment]
It's functionally ok (though suboptimal in terms of performance) to use the synchronous Read/Write methods on a FileStream constructed with FileOptions.Asynchronous.

However, the repro has other problems.  In particular, the code is opening two streams to the same file, reading and writing concurrently.  It appears to be trying to use this as a form of message passing between the writer and reader, but using FileStream in this way is invalid.  First, the Stream contract is such that Read returns 0 if and only if the stream is at EOF, so the Reads here racing with the Writes could result in Read returning 0, after which it's generally expected that it'll always return 0.  Second (related to the first), there is no guarantee that a call to Read will return the requested number of bytes... the only guarantee is that it'll return <= the number of bytes requested, and > 0 if it's not EOF.  FileStream does try to fill the buffer, but it's not always successful, and it's doesn't even try if it sees an initial call to the OS return 0 bytes.  That's almost certainly why you're seeing arrays of 0s: you're allocating a new byte array (zero'd out), then making calls to Read that will likely hit EOF, and then adding that array to the collection, regardless of whether it was successful.

**Comment by zmhh** [comment]
Thanks for the replies. @stephentoub, I'm not sure that explanation makes sense to me. 

First I check the file length before reading so I don't hit EOF:

`if (readerStream.Length - readerStream.Position < messageSize) continue;`

And I also check the return value of read to ensure I read the entire buffer length:

`while (read != buffer.Length)
                    {
                        read += readerStream.Read(buffer, read, buffer.Length - read);
                    }`

Setting a breakpoint there shows that readStream.Read() does not reach EOF (does not return 0).

In fact if you add an if statement to catch the 0'd out array after the Read operation, you will see that readerStream.Read() returned "1024" (the same as the amount of bytes requested) which indicates it successfully read the entire byte array. However it did not populate the buffer (or only populated with 0s). So if it is an EOF issue, it seems like the Read operation is incorrectly returning a >0 value.

_"First, the Stream contract is such that Read returns 0 if and only if the stream is at EOF, so the Reads here racing with the Writes could result in Read returning 0, **after which it's generally expected that it'll always return 0**"_

Is this documented somewhere? I'm not seeing guidance regarding this in the [doc](https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream?view=netcore-2.1). I would expect to be able to Read again if the file expands (and thus we are no longer at EOF).

Given the above would you still say using Filestream this way is invalid? Given the above and the fact that it works without FileOptions.Asynchronous it seems valid, but it is pretty critical this doesn't fail so I would like to do it the right way. Do you have guidance on a valid approach?

**Comment by stephentoub** [comment]
> And I also check the return value of read to ensure I read the entire buffer length:
> while (read != buffer.Length) { read += readerStream.Read(buffer, read, buffer.Length - read); }

You just edited the code an hour ago to change it from an `if` to a `while`.  That's a big difference.

> if (readerStream.Length - readerStream.Position < messageSize) continue;

When opened for async I/O, for better or worse FileStream expands the size of the file if it's not already long enough to accomodate the write, before it performs the write, so by allowing this to progress based on file length, you have a race condition where the file could end up being length extended, then your reader sees the length, and starts reading that additional data before the writer has had a chance to actually fill it in.
https://github.com/dotnet/coreclr/blob/75c5020b66f727a292afdbdf2b324ebd39e3e89d/src/System.Private.CoreLib/shared/System/IO/FileStream.Windows.cs#L1053-L1056
I don't know why FileStream does this, but it's been that way for a long time.  It's one of the many things I'd like to change in the implementation as part of an overhaul, but that's the way it's been and currently is, in both .NET Framework and .NET Core.

> Is this documented somewhere?

https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.read
"Read returns 0 only when there is no more data in the stream and no more is expected (such as a closed socket or end of file)."

> Given the above would you still say using Filestream this way is invalid?

Yes.

**Comment by zmhh** [comment]
Thanks for the prompt response @stephentoub!

> You just edited the code an hour ago to change it from an if to a while. That's a big difference.

Yeah the if was incorrect so I changed it to while. Didn't mean for that to be sneaky or anything, just corrected it after seeing it was wrong and it reproduces the same issue both ways so I didn't mention the edit.

> When opened for async I/O, for better or worse FileStream expands the size of the file if it's not already long enough to accomodate the write, before it performs the write, so by allowing this to progress based on file length, you have a race condition where the file could end up being length extended, then your reader sees the length, and starts reading that additional data before the writer has had a chance to actually fill it in.

That makes complete sense and explains the issue! Thanks for pointing that out.

Since that race condition does not exist for synchronous filestream, why do you say that it is invalid to use filestream this way? Assuming we leave out the FileOptions.Asynchronous flag.

Thanks for the link to the doc - I did read that, but I think I was misinterpreting what you were saying. I thought you meant that filestream is expected to return 0 after it reaches EOF even if more data is inserted in the stream afterwards and it is no longer at EOF - if you just meant it returns 0 if it reaches EOF, I definitely understand.

**Comment by zmhh** [comment]
Hey @stephentoub, I'm still not clear on why using FileStream as shown in the repro code is invalid, if we use a synchronous filestream. Could you help me clarify?

You described the reasons for it being invalid as being that we could reach EOF and return 0, and that a call to read does not guarantee it will return all of the requested bytes. We also saw that for an asynchronous filestream, there will be a race condition because the writer sets the file length before writing data.

Since the repro code checks that the file length is long enough before reading, and also checks the number of bytes read, and if it used a synchronous filestream the file length race condition would not be encountered, what is the reason that it is an invalid use of filestream?

**Comment by zmhh** [comment]
Thanks!
