### ISSUE TITLE
TcpClient.LingerState Property does not behave as expected and documents w/ .NET core 2.1

### ISSUE THREAD

**Issue by 1iveowl** [dotnet/corefx#33088]
According to the documentation for [TcpClient.LingerState Property](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcpclient.lingerstate?view=netframework-4.7.2) it should be possible to control the way a `tcpClient.Close()` behaves.

Specifically, by setting `tcpClient.LingerState = new LingerOption (true, 0)`, the behavior is said to be [my bold-italic]:

> Discards any pending data and Winsock **_resets_** the connection.

Now, this is not the behavior I've observed. And it seems others are having the similar challenges: [Stackoverflow: What should I do to completely close the TcpClient connection with mcu?](https://stackoverflow.com/a/51234500).

My own observations on .NET Core 2.1, using Wireshark to see what goes on, is that no TCP RST is send over the wire when `tcpClient.Close()` is called even with LingerState set to`LingerOption (true, 0)`. 

TCP FIN is send with `tcpClient.Close()`, but not RST. The only way I've managed to to force the RST to be send over the wire is by closing the running application. Consequently, any attempt of reconnect after a close to the same end point fails unless the application is closed and restarted. This is even true if the TcpClient is disposed (`tcpClient.Dispose()`) and a new TcpClient instance is created. 

Is this by design? And if so, are there any work-arounds for managing scenarios where a hard TCP connection reset (i.e. RST) is desirable immediately?

**Comment by karelz** [comment]
Where is the documentation?
I don't think .NET can influence this level of TCP, we rely on underlying OS. We pass the LingerState as well to the OS (in its best approximation).
If docs are not accurate, we should fix them.

**Comment by 1iveowl** [comment]
Apologies. I see that the first link I provided was incorrect. It now links to the documentation: [TcpClient.LingerState Property](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcpclient.lingerstate?view=netframework-4.7.2)

**Comment by karelz** [comment]
It helped. We just didn't get to it.

Reading Winsock documentation of [closesocket](https://docs.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-closesocket), I think the word "resets" refers to winsock term, not to the TCP RST term:

> This is called a hard or abortive close, because the socket's virtual circuit is **reset** immediately, and any unsent data is lost. On Windows, any recv call on the remote side of the circuit will fail with **WSAECONNRESET**.

From that perspective the documentation is correct.
Winsock itself does not promise use of TCP FIN or RST.

**Comment by karelz** [comment]
@GSPP but it does not seem that `LingerState` fullfills that capability even on OS level.
What would be the need to enforce RST on TCP connection. I thought that is rather part of the TCP protocol, not something that higher layers should worry about.

**Comment by GSPP** [comment]
I just tested it on Windows 7 with .NET 4.7.2.

    var ipAddress = Dns.GetHostAddresses("github.com").Where(x => x.AddressFamily == AddressFamily.InterNetwork).First();

    Console.WriteLine($"Connecting to {ipAddress}...");

    using (var socket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
    {
        socket.Connect(new IPEndPoint(ipAddress, 80));

        Console.WriteLine("Connected to server.");

        //clientSocket.Shutdown(SocketShutdown.Both);
        socket.LingerState = new LingerOption(true, 0);
    }

Here, a reset results as expected:

![image](https://user-images.githubusercontent.com/12032350/47808523-d8371700-dd3e-11e8-8b71-d43c8d8db6a4.png)

When not setting the `LingerState` with out without shutdown, a graceful TCP shutdown occurs:

![image](https://user-images.githubusercontent.com/12032350/47808586-f43ab880-dd3e-11e8-9c0a-8d52cff6adff.png)

I would be very surprised if Linux did not provide a way to reset a connection.

**Comment by karelz** [comment]
Does .NET Core behave differently on Windows?

**Comment by karelz** [comment]
So the only difference is Windows vs. Linux?
Either we do not pass right arguments on Linux, or it is OS implementation detail behavioral difference which we cannot influence. I assumed we are in the 2nd option camp ...

**Comment by 1iveowl** [comment]
@GSPP when you tested the above, are certain that the RST was not triggered by the application exiting? 

I ran similar tests the other day, and I observed no RST was send when calling TcpClient.Close() on Windows 10. However, as soon as I exited the application (a console app) the RST was observed with WireShark. 

I was running the test with the new `async Main()` capability in C# 7.3 after calling TcpClient.Close() I put a long wait (i.e. something like `await Task.Delay(TimeSpan.FromMinutes(60))`.

**Comment by GSPP** [comment]
@1iveowl actually, I was not certain of that. I just retested by placing a breakpoint after the closing brace of my using statement and the reset is being generated. Can you try my repro code? Maybe there is some meaningful difference to yours.

http://deepix.github.io/2016/10/21/tcprst.html here is someone who confirmed that linger generates a reset on linux 4.8. This is an essential OS capability. Linux surely provides it.

**Comment by 1iveowl** [comment]
Thank you @GSPP, I will re-run the test I did the other day and return.

**Comment by 1iveowl** [comment]
You are correct GSPP. Now, I too see a RST send when close is called and before the application exits.

![rst](https://user-images.githubusercontent.com/12871120/47842766-f132dd00-ddbd-11e8-854e-a2aa1260de81.png)

I've only tested on Windows 10 (17763.55). My observations the other day must have been polluted by something else. What, I don't know yet.

By the way. The test shows that it makes no difference if `LingerOption(true, 0)` is set or not. At least not on Windows.

You can see my test for .NET Core 2.1 here: [Linger Test](https://github.com/1iveowl/LingerState.Test/tree/master/src/test)

**Comment by wfurt** [comment]
is this issue resolved now or do we need anything else @GSPP  and @1iveowl ???

**Comment by 1iveowl** [comment]
@wfurt I have nothing new to add. 

I never managed to figure out what caused the issue, but it seems fixed now.
