### ISSUE TITLE
SocketAsyncEventArgs ThrowForNonFreeStatus when using HttpClient

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/corefx#33094]
`InvalidOperationException: An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance` is thrown when calling SendAsync on an HttpClient.

Call stack:
```
Error Message:
 System.AggregateException : One or more errors occurred. (An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance.)
---- System.Net.Http.HttpRequestException : An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance.
-------- System.InvalidOperationException : An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance.
Stack Trace:
***
Stack trace from my project to the SendAsync call site ...
***
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
----- Inner Stack Trace -----
   at System.Net.Sockets.SocketAsyncEventArgs.ThrowForNonFreeStatus(Int32 status)
   at System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon(Socket socket, SocketAsyncOperation operation)
   at System.Net.Sockets.Socket.ConnectAsync(SocketType socketType, ProtocolType protocolType, SocketAsyncEventArgs e)
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
```

Note that there may be multiple SendAsync calls on the same HttpClient instance from different threads.

I assumed that there shouldn't be any state-corruption when running concurrently since `SendAsync` is marked as 'Tread-Safe'.

Tested on 2.1.400 and 2.1.402.

I am unable to reproduce the problem on my machine (Windows), but the issue seems to occur ~75% of the time when running on Travis/AppVeyor (Win)/Linux vm.
I was also unable to find any other mentions of such a problem with the HttpClient when researching the issue.

Can someone explain to me under what circumstances https://github.com/dotnet/corefx/blob/225be960445683a97e68005d87f7ebbd5f5e5a88/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs#L504-L507 is reached when calling HttpClient's SendAsync method (or if that is even supposed to happen)?

**Comment by stephentoub** [comment]
Is it possible anything in your app previously tried to connect to http://0.0.0.0 or http://[::0] ? Did you get any other connect failures prior to this anywhere in the app?

**Comment by MihaZupan** [comment]
It will never call SendAsync of any url if `Dns.GetHostAddresses(url.Host)` fails, so urls with hosts like 0.0.0.0 should never get that far.
It could call SendAsync concurrently on multiple paths for the same host after it verified that it's resolvable.

The test suite will make many requests, one of them to https://expired.badssl.com to test the HttpRequestException case (if that's what you meant by connect failures).

**Comment by stephentoub** [comment]
Are you able to create a repro of the problem you can share? The only case I'm aware of (fixed for 3.0) where we didn't properly reset that in-use flag is when IPAddress.Any was used.

**Comment by MihaZupan** [comment]
The repo is public: https://github.com/MihaZupan/MarkdownValidator
The requests are only made in https://github.com/MihaZupan/MarkdownValidator/blob/master/src/MarkdownValidator/WebIO/WebIOController.cs

If you run the test suite rn, you will see the issue as WebRequestFailed warnings being shown instead of other warnings (since it will be cought by https://github.com/MihaZupan/MarkdownValidator/blob/master/src/MarkdownValidator/WebIO/WebIOController.cs#L430.
(You might not, since as I mentioned it always succeeds on my development machine, but fails most of the time when running under CI)

I'm afraid that the requesting part itself is wrapped up in way too much scheduling logic to be easy to debug rn this issue rn.
I can try to strip down as much logic as possible where the issue remains (might take some time tho).

I was just under the impression that this kind of an exception _should_ never be thrown when using the HttpClient.

**Comment by stephentoub** [comment]
> If you run the test suite rn

How does one do that?  Can you provide step-by-step instructions?

> I am unable to reproduce the problem on my machine (Windows), but the issue seems to occur ~75% of the time when running on Travis/AppVeyor (Win)/Linux vm.

Are you able to determine what the difference is?  Are they contacting different Uris?  Are they running on different numbers of cores?  Are they using IPv4 vs IPv6? Etc.  We can try to reproduce it locally using your repro, but it sounds like we probably won't be able to, given that you can't either locally.

**Comment by MihaZupan** [comment]
I just realized that it does call SendAsync for [::] once (turns out I only did the Dns check when host name was UriHostNameType.Dns)

When I restrict that address the issue seems to be resolved (ran the tests 30x on two digital ocean VMs).

I assume that makes this issue a duplicate of _something_?
Something that seems to only affects VMs?

**Comment by stephentoub** [comment]
> I assume that makes this issue a duplicate of something?

https://github.com/dotnet/corefx/issues/32971
https://github.com/dotnet/corefx/pull/32972

**Comment by MihaZupan** [comment]
Well, thank you so much for the very quick responses!

I wish I hadn't delayed the project for a month trying to debug everything, but at least now I can get back to actual code.

Do you know why my local machine wasn't affected by this?
