### ISSUE TITLE
WebProxy bypasses loopback despite of setting BypassOnLocal = false

### ISSUE THREAD

**Issue by nikoudel** [dotnet/corefx#33096]
https://github.com/dotnet/corefx/blob/89ab1e83a7e00d869e1580151e24f01226acaf3f/src/System.Net.WebProxy/src/System/Net/WebProxy.cs#L203

**Comment by nikoudel** [comment]
I had a real issue before peeking the source code - my proxy was not used when accessing a web service on the localhost. Tested like this:

`var proxy = new WebProxy(Address: proxyUrl, BypassOnLocal: false);

if (proxy.IsBypassed(new Uri("http://localhost:5000")))
{
    throw new Exception("Proxy must not bypass localhost");
}`

**Comment by karelz** [comment]
Ah, thanks. This kind of unit test definitely helps.
It should be fairly straightforward to fix & write unit test. Are you interested to give it a try?

**Comment by karelz** [comment]
BTW: I just tried it on .NET Framework 4.7.2 and it behaves the same way there. It is not a regression in .NET Core against .NET Framework.
Unless there is some weird reason for this behavior I don't know about, it is a bug we should be fine fixing.

**Comment by nikoudel** [comment]
> Ah, thanks. This kind of unit test definitely helps.
> It should be fairly straightforward to fix & write unit test. Are you interested to give it a try?

Sure, I'll create a PR.

**Comment by stephentoub** [comment]
@karelz, have you looked into why netfx is this way?  It's pretty explicit in the code, so there was probably a reason?
https://referencesource.microsoft.com/#System/net/System/Net/webproxy.cs,405

**Comment by nikoudel** [comment]
> @karelz, have you looked into why netfx is this way? It's pretty explicit in the code, so there was probably a reason?
> https://referencesource.microsoft.com/#System/net/System/Net/webproxy.cs,405

Perhaps that's because it's hard to imagine why would anyone want to use a proxy for loopback-hosted web services? In my case the reason was monitoring web traffic with Fiddler (which is a proxy) during development of a web service.
