### ISSUE TITLE
Add byte array an/or ImmutableArray<byte> ctor for Sys.Reflection.Metadata.BlobReader

### ISSUE THREAD

**Issue by devhawk** [dotnet/corefx#3310]
BlobReader has an unsafe ctor that takes a byte*/length but doesn't have any public ctor that makes it usable from a purely safe context. Can we add a safe ctor that takes either a byte array or an immutable byte array? As far as I can tell, the following would be a reasonable implementation (i.e. it would match the logic of the existing public ctor)

```` csharp
public BlobReader(ImmutableArray<byte> block)
{
    if (block.Length < 0)
    {
        throw new ArgumentOutOfRangeException("block");
    }

    if (block.IsDefault)
    {
        throw new ArgumentNullException("block");
    }

    // the reader performs little-endian specific operations
    if (!BitConverter.IsLittleEndian)
    {
        throw new PlatformNotSupportedException(SR.LitteEndianArchitectureRequired);
    }

    var provider = new ByteArrayMemoryProvider(block);

    this = new BlobReader(new MemoryBlock(provider.Pointer, provider.Size));
}
````

**Comment by nguerrera** [comment]
cc @tmat

BlobReader is a struct and does not managed lifetime of the memory it reads, but hat provider needs to be disposed. We can't safely (well, certainly not cheaply) make BlobReader disposable because there can be arbitrary copies.

Is there something higher level that you're trying to accomplish? Maybe we can work from that to a different solution.

**Comment by devhawk** [comment]
I'm trying to parse encoded Types in signatures (ECMA 335 II.23.2.12). I saw that there are better signature parsing APIs in dev/metadata branch as described in in #262? Are those ready for prime time?

**Comment by devhawk** [comment]
I took a look @ the classes in the Decode folder of the dev/metadata branch. Is there any spec/docs/guidance on implemented ISignatureTypeProvider?

**Comment by nguerrera** [comment]
Not yet, but there are some examples in early adopters:
* https://github.com/dotnet/corefxlab/blob/a52a1626dd91e37597b5b6273d8a7996e7471974/src/System.Reflection.Metadata.Cil/src/Decoder/CilTypeProvider.cs
* https://github.com/dotnet/roslyn/blob/aa28d6b7d55148d17d520fa5c01dda8c57cd0116/src/Test/PdbUtilities/Pdb/PdbToXml.cs#L1056
* https://github.com/Microsoft/dotnet-apiport/blob/9d17e44358b64d5c6d584e6de541944d19a5533a/src/Microsoft.Fx.Portability.MetadataReader/MemberMetadataInfoTypeProvider.cs

**Comment by nguerrera** [comment]
Note also, fwiw, that you can get a BlobReader from a BlobHandle without an intermediate step as byte[] or ImmutableArray<bytes>. There is zero copying in that case and the lifetime is controlled by the lifetime of the PEReader.

See https://github.com/dotnet/corefx/blob/913b535a83e05b7e52f795ae3e5f1a84b84536ee/src/System.Reflection.Metadata/src/System/Reflection/Metadata/Decoding/SignatureDecoder.cs#L251

As far as the decoder being ready for prime time. It's still alpha quality, there will be breaking changes and more testing (which may reveal bugs) is pending, but the priority is now bumped to get this through and there are (as shown above) several folks using it successfully early. If you're prepared to absorb breaking changes, you can get the alpha from nuget.org.

**Comment by nguerrera** [comment]
I am closing this because we can't efficiently support it and I think that even without #262 stable, the main use case to go from BlobHandle -> BlobReader is covered without dropping down to unsafe code. Feel free to reopen if you disagree.

**Comment by devhawk** [comment]
My reasoning for opening this issue is to be able to parse a part of signature blob. I wanted a way to pass the part of signature blob to other code for parsing. I'm not a fan of doing that with BlobReader since BlobReader's have an inherent sense of "current location". But if there is going to be a built in signature blob parser, I'd rather use that anyway so I'll leave this closed.
