### ISSUE TITLE
[Bug] HttpListener returns 404 to browser on Linux x64/Ubuntu and never returns from GetContext()

### ISSUE THREAD

**Issue by Shelim** [dotnet/corefx#33126]
1. Steps to reproduce:

 - Use default example code from here:
https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistener?redirectedfrom=MSDN&view=netframework-4.7.2
 - Compile it on .NET Core 2.1
 - Upload it to Linux x64/Ubuntu
 - Run it via dotnet Server.dll
 - Attempt to open server URL from browser

2. What I saw?
`Not Found (Not Found)` with HTTP header: `Server: Microsoft-NetCore/2.1`

3. What I wanted to see?
The page I am explicity returning to user

4. Additional info:
The firewall on Ubuntu is down. The code below line:
`HttpListenerContext context = listener.GetContext();`
is never called.

**Comment by stephentoub** [comment]
I just tried it and it worked for me.  The example you linked to isn't a complete program... can you please share the complete program you're using as well as the URL you're using to open it?

**Comment by Shelim** [comment]
@stephentoub 

Okay, I just narrowed down the issue; I was specifing `localhost` as prefix and I was accessing the page through Apache proxy. I thought - incorrectly - that Apache will route it as local query, but it was passing the domain name from the external query instead.

Still 404 is quite misleading here :)
