### ISSUE TITLE
Path.GetTempPath returns a symlink path instead of the actual path on MacOS

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/corefx#33141]
On MacOS, `Path.GetTempPath()` returns something like `/var/folders/pd/mny80ks961108l1fbtvznbmr0000gn/T/` which is a symlink to `/private/var/folders/pd/mny80ks961108l1fbtvznbmr0000gn/T/`

`/private/var/...` is the real directory and that is what I would expect to be returned.

It is not consistent with other things either. For example, `AppDomain.CurrentDomain.BaseDirectory` returns the actual directory path `/private/var/...`

```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.100-preview3-009430
 Commit:    e0a11c9929

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /Users/username/.dotnet/sdk/2.2.100-preview3-009430/

Host (useful for support):
  Version: 2.2.0-rtm-27023-02
  Commit:  49bbd209e5
```

**Comment by stephentoub** [comment]
> On MacOS, Path.GetTempPath() returns something like /var/folders/pd/mny80ks961108l1fbtvznbmr0000gn/T/ which is a symlink to /private/var/folders/pd/mny80ks961108l1fbtvznbmr0000gn/T/

It just returns whatever TMPDIR is set to:
https://github.com/dotnet/coreclr/blob/626def86af589734999a0e62d3a83c2acb9de54a/src/System.Private.CoreLib/shared/System/IO/Path.Unix.cs#L72-L85
It doesn't try to resolve it. That's true on Windows as well.  If I create a symbolic link to a directory and set TMP to the link, Path.GetTempPath returns the symbolic link, not the path to the target.

**Comment by danmosemsft** [comment]
Seems by design.
