### ISSUE TITLE
System.Memory NuGet package does not offer ByRefLike Type extension property in full .Net

### ISSUE THREAD

**Issue by bergmeister** [dotnet/corefx#33149]
The [System.Memory](https://www.nuget.org/packages/System.Memory/) NuGet package is also compatible with full .Net but on full .Net the [IsByRefLike](https://docs.microsoft.com/en-us/dotnet/api/system.type.isbyreflike?view=netcore-2.1) property on `System.Type` is not available, thus making usage of `Span<T>` hard in full .Net
Can we add an extension method for full .Net or is there a workaround?

**Comment by jkotas** [comment]
The workaround is to check for presence of `IsByRefLikeAttribute`. The first class support for byref-like types is present in .NET Core only.
