### ISSUE TITLE
Add netstandard-RID specific implementations of System.Diagnostics.EventLog & System.Management

### ISSUE THREAD

**Issue by hanblee** [dotnet/corefx#33150]
Unlike other packages in the Windows Compatibility Pack (e.g., `Microsoft.Win32.Registry`), `System.Diagnostics.EventLog` & `System.Management`  packages do not provide RID specific implementations for netstandard. Please provide RID specific implementations for netstandard.

Please see: https://github.com/dotnet/corefx/issues/32910#issuecomment-431468581

**Comment by yulia-d** [comment]
We are very interested in this as we build .NET standard library packages used as plugins loaded dynamically by both .NET Framework and .NET Core hosts, and these 2 WCP packages don't provide us a single entry-point assembly that can be used in both! (As opposed to, say, Microsoft.Win32.Registry.)

**Comment by hanblee** [comment]
I looked into `System.Diagnostics.EventLog` and `System.Management` sources, and I see that at least in the `EventLog` case, there are dependencies to other netcoreapp-only APIs (e.g., `System.Security.Permissions.HostProtection`) which leads me to believe that they were specifically designed to target `netcoreapp` only in the current form.

It would be nice to get some confirmation from the corefx team, but closing this with the assumption that they were specifically targeting `netcoreapp` .
