### ISSUE TITLE
Race condition in usage of GenerateAssemblyInfo can cause test build breaks

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#33219]
@dotnet-mc-bot commented on [Fri Nov 02 2018](https://github.com/dotnet/core-eng/issues/4538)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2176623
  - **Agent:** DDVSOWINAGE101
  - **Error log:** E:\A\_work\0\s\corefx\.dotnet\sdk\2.1.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(0,0): error MSB3713: The file "E:\A\_work\0\s\corefx\bin/obj/AnyOS.AnyCPU.platform/ForwardedTypesAssembly/netstand...

@jcagme, @markwilkie

---

@MattGal commented on [Fri Nov 02 2018](https://github.com/dotnet/core-eng/issues/4538#issuecomment-435421228)

Reclassifying as Source Code and moving to CoreFX.  We've seen lots of these parallel build issues and it usually comes from slight build tweaks (or just a latent bug and bad luck)

**Comment by MattGal** [comment]
@ViktorHofer FYI, I've definitely seen you chase down and fix similar issues.

**Comment by ViktorHofer** [comment]
cc @weshaggard who brought the generate assembly info infrastructure over to corefx.

**Comment by weshaggard** [comment]
Looks like we have 2 assemblies with the same name which is causing this issue (https://github.com/dotnet/corefx/search?q=ForwardedTypesAssembly&unscoped_q=ForwardedTypesAssembly) We need to rename one or both of those projects to fix this race.
