### ISSUE TITLE
System.IO.Pipelines: PipeReader.AdvanceTo is required to end a read operation, leading to InvalidOperationException

### ISSUE THREAD

**Issue by MaxDZ8** [dotnet/corefx#33213]
This is possibly an intended design choice; documentation about pipelines a bit... essential to say the least; maybe I've missed a tidbit. What I have consulted:

1. [Original blog post](https://blogs.msdn.microsoft.com/dotnet/2018/07/09/system-io-pipelines-high-performance-io-in-net/)
2. docs.microsoft, [PipeReader.AdvanceTo](https://docs.microsoft.com/en-us/dotnet/api/system.io.pipelines.pipereader.advanceto?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.IO.Pipelines.PipeReader.AdvanceTo);k(DevLang-csharp)%26rd%3Dtrue&view=dotnet-plat-ext-2.1) and [PipeReader.ReadAsync](https://docs.microsoft.com/en-us/dotnet/api/system.io.pipelines.pipereader.readasync?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.IO.Pipelines.PipeReader.ReadAsync);k(DevLang-csharp)%26rd%3Dtrue&view=dotnet-plat-ext-2.1
).
3. [TcpEcho Program.cs](https://github.com/davidfowl/TcpEcho/blob/2184c00be3e8d3229a4edd4a0adb07ae478a31cb/src/Program.cs#L81)
4. Found my way through source to [AdvanceReader](https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.IO.Pipelines/src/System/IO/Pipelines/Pipe.cs#L421)

What I observe: given this
```c#
private async Task ReadPipeAsync(Socket socket, PipeReader reader)
        {
            bool matched = false;
            while (false == matched)
            {
                Console.WriteLine("Reading from socket...");
                var result = await reader.ReadAsync();
                Console.WriteLine($"Socket gave {result.Buffer}");
                var buffer = result.Buffer;
                if (buffer.Length >= 2 + 4 + 8)
                {
                    var slice = buffer.Slice(0, 2 + 4 + 8);
                    var blobby = buffer.ToArray();
                    reader.AdvanceTo(slice.End);
                    Console.WriteLine(BitConverter.ToString(blobby));
                    matched = true;
                }
            }
            matched = false;
            while (await devices.device.Read(reader)) ;
            reader.Complete();
        }
```

This will **sometimes** fail with `InvalidOperationException` (Reading is already in progress). After looking at the source, I'm baffled this only happens **sometimes** because in my understanding it should be deterministic (but I'm positing I'm missing some task interactions).

Indeed the above code does not follow the same structure as TcpEcho.  TcpEcho (nearly) always provides every `ReadAsync` with a matching .

It is my current understanding, this matching is required to be guaranteed, as `AdvanceTo` (besides `CompleteReader`) is required to ultimately set the corresponding `System.IO.Pipelines.PipeReaderState._state` to `State.Inactive`.

Now I have several issues with this.

1. It is not clear to me if this is intended; in this case I hope it will get more emphatized in docs because I didn't get this idea at all.

2. If this is intended, then it must be absolutely guaranteed, in an exception safe manner, the call to `AdvanceTo` takes place. Again, I think this would require more documentation.

3. But really once `await` returns I'd expect the reading to be done. In particular, the semantics of 'reading' and 'consuming read data' are supposed to be disjoint... or not?

In fact, modifying the above code to behave like TcpEcho ('always' providing a `AdvanceTo` call) seems to fix the issue for me. Is this intended?

**Comment by NickCraver** [comment]
Which version of the `System.IO.Pipelines` library are you using?

**Comment by mgravell** [comment]
My understanding is that yes, you are always meant to provide exactly one `AdvanceTo` after every `ReadAsync`, even if the `AdvanceTo` says "advance nowhere, I didn't consume anything". Yes, it is rare that the buffer is too small to contain your contents, but it will happen eventually due to fragmentation etc (hence it appears non-deterministic).

Re exception conditions: I wouldn't worry about `try` / `finally` here for this, unless you can reliably actually recover. Usually you can't, so just light it up and watch it burn.

**Comment by mgravell** [comment]
If I were to restate the question, then; would it be correct to say that you're proposing that:

> `ReadAsync`, in the case where there is already an active read, should implicitly terminate the existing read operation without consuming any data, and as though the prior data had been inspected (to prevent a tight loop), i.e. as though `reader.AdvanceTo(previousBuffer.Start, previousBuffer.End);` had been called explicitly

?

**Comment by MaxDZ8** [comment]
> 
> 
> Which version of the `System.IO.Pipelines` library are you using?

According to Nuget window from VS2018 latest stable version is installed: 4.5.2.
As a side note, my "Updates" tab in the Nuget explorer window is empty.

**Comment by MaxDZ8** [comment]
> My understanding is that yes, you are always meant to provide exactly one `AdvanceTo` after every `ReadAsync`, even if the `AdvanceTo` says "advance nowhere

Calls coming in pairs are not new. If this is the case, please update documentation to properly reflect this. For example, glBegin/glEnd were so tightly coupled they even get documented as a single thing.

> I didn't consume anything". Yes, it is rare that the buffer is too small to contain your contents, but it will happen eventually due to fragmentation etc (hence it appears non-deterministic).

I see this being orthogonal to the problem.

> The fix might be very simple:

Quoting myself:
> In fact, modifying the above code to behave like TcpEcho ('always' providing a AdvanceTo call) seems to fix the issue for me. **Is this intended?**

> Re exception conditions: I wouldn't worry about `try` / `finally` here for this, unless you can reliably actually recover. Usually you can't, so just light it up and watch it burn.

I disagree. If there is a requirement to match `ReadAsync`/`AdvanceTo` (which I find against every other API I can recall in 5 minutes) then this MUST be specified, guaranteed. Whatever a certain implementation decides to go on ignoring exceptions is their choice, but it must be an informed choice.

Ah by the way, there are two small issues with this formulation either:

1. AdvanceTo(start) appears to work as well (unsurprisingly)
2- The chance of exception in payload processing is in my opinion very high and - in at least the system I am prototyping now - almost trivial. Consider [TcpEcho](https://github.com/davidfowl/TcpEcho/blob/2184c00be3e8d3229a4edd4a0adb07ae478a31cb/src/Program.cs#L98).

**Comment by MaxDZ8** [comment]
> 
> 
> If I were to restate the question, then; would it be correct to say that you're proposing that:
> 
> > `ReadAsync`, in the case where there is already an active read, should implicitly terminate the existing read operation without consuming any data, and as though the prior data had been inspected (to prevent a tight loop), i.e. as though `reader.AdvanceTo(previousBuffer.Start, previousBuffer.End);` had been called explicitly
> 

No, I was just asking if this behaviour is intended (because it does not look like anything desirable to me). After thinking at it, I suppose it could make sense but I'm not entirely sure (silently cancelling) is generally useful behaviour as it implies some sort of code inconsintency.

The fact is, when `await` returns, regardless of data being consumed or not, I would expect the reader to be readable again... or not? Why is `AdvanceTo` required? As long as I fit the buffers, I should be free to accumulate... or not?

Shall this be intended behaviour, I think everything can be solved by improving the documentation; all I get is essentially empty pages.

**Comment by Wraith2** [comment]
I hit the same behaviour a while back and came to essentially the same conclusion, that it is correct based on the implementation but that it isn't what you would expect if you aren't looking at how it is implemented.

I found it easiest to model it by regarding the read operation as taking a snapshot and that any subsequent operation on the underlying pipeline as invalidating that snapshot.

As you say documentation would greatly increase the usability of pipelines.

**Comment by davidfowl** [comment]
We had a long argument about renaming ReadAsync to PeekAsync, anyways this is by design. The design forces you to say what was consumed everytime not just sometimes. This forces you into a pattern that avoids memory leaks. AdvanceTo returns buffers to the buffer pool and that's not something you want to forget.

It should fail every time if AdvanceTo isn't called,

**Comment by Wraith2** [comment]
Requiring a single advance isn't too surprising. Requiring exactly one is a little surprising. 
If there are two structures in the input pipe I can't read the first, advance to the second (to free up the buffer) and then continue to read the second because when I reach the end of the second I'll get an error. I'm forced to do a single structure per advance which seems counter intuitive to the performance goal of the pipe.

**Comment by davidfowl** [comment]
Well if you cared about performance you wouldn't call AdvanceTo more than once when parsing 2 structures if they were in the buffered returned. You would read the buffer, and read the 2 structures from it, then call AdvanceTo.

Also, you're not freeing up the buffer if the buffer isn't fully consumed (we don't partially clear the buffer out based on the SequencePosition).

We need to write actual usage docs for this and clear up the error messages as well. Each call to ReadAsync requires a call to AdvanceTo.

**Comment by omariom** [comment]
@davidfowl 
> We had a long argument about renaming ReadAsync to PeekAsync

You should've called them `BeginRead` and `EndRead` 🤪

**Comment by davidfowl** [comment]
Super early versions were called that, but it sounded too much like the old APM model 😄

**Comment by davidfowl** [comment]
@MaxDZ8 is there a bug here or was this just a question? Can you reproduce the sequence of calls that make it fail sometimes but not other times?

**Comment by MaxDZ8** [comment]
> is there a bug here or was this just a question?

It was just a question. From discussion I get this is intended. Some misnaming appears to have happened but that's bikeshed discussion as no clearly better alternative seems to be available.

Please remember to update the documentation.

> Can you reproduce the sequence of calls that make it fail sometimes but not other times?

After more than a month? Nope. Besides, there is some good chance I just cobbled together something nonsensical.
