### ISSUE TITLE
websocket ping/pong

### ISSUE THREAD

**Issue by mofee** [dotnet/corefx#33239]
is websocket send ping and  set websocket state to abort or closed if not received the pong in N times?
i use websocket server to keepalive per 15s:
          app.UseMiddleware<WebSocketMiddleware>(Options.Create(new WebSocketOptions()
            {
                KeepAliveInterval = TimeSpan.FromSeconds(15),
                ReceiveBufferSize = 1024
            }));
and the received code like below:
             var receiveTask = socket.ReceiveAsync(buffer, ct);
              while (!receiveTask.IsCompleted && !ct.IsCancellationRequested && socket.State == WebSocketState.Open)
                 {
                         await Task.Delay(500);
                  }
                  // business code here .....

when the client  internet is out of service,  or pull the client cable, the server seems can not know that  and the websocket state not change.

**Comment by mofee** [comment]
my dotnet core version is 2.1.2, and run on centos 7.5

**Comment by davidsh** [comment]
>is websocket send ping and set websocket state to abort or closed if not received the pong in N times?

"KeepAlive" doesn't necessary mean the websocket will send out pings to the server.

The other mechanism for "keepalive" is unsolicited pong frames.  I can't remember all the different WebSocket implementations in .NET Core vs. .NET Framework.  But in .NET Framework and some .NET Core implementation, "keepalive" is done with unsolicited pong frames.  This has lower overhead because unlike sending a ping frame, it doesn't have to wait for a response.

@stephentoub

**Comment by mofee** [comment]
thanks davidsh! 
i look into the ManagedWebSocket source code, it does not handle the received pong frames.
this means that i must to handle the keepalive heartbeat in my business layer code.

ManagedWebSocket source code:
 private async Task HandleReceivedPingPongAsync(MessageHeader header)
        {
            // Consume any (optional) payload associated with the ping/pong.
            if (header.PayloadLength > 0 && _receiveBufferCount < header.PayloadLength)
            {
                await EnsureBufferContainsAsync((int)header.PayloadLength).ConfigureAwait(false);
            }

            // If this was a ping, send back a pong response.
            if (header.Opcode == MessageOpcode.Ping)
            {
                if (_isServer)
                {
                    ApplyMask(_receiveBuffer.Span.Slice(_receiveBufferOffset, (int)header.PayloadLength), header.Mask, 0);
                }

                await SendFrameAsync(
                    MessageOpcode.Pong, true,
                    _receiveBuffer.Slice(_receiveBufferOffset, (int)header.PayloadLength), default).ConfigureAwait(false);
            }

            // Regardless of whether it was a ping or pong, we no longer need the payload.
            if (header.PayloadLength > 0)
            {
                ConsumeFromBuffer((int)header.PayloadLength);
            }
        }

**Comment by davidsh** [comment]
The WebSocket code will always do the right thing when a Ping is received, i.e. send back a Pong frame.

But the mechanism for "keepalive" can be either to send a Ping frame (which requires managing logic to track a Pong frame), or send an unsolicited Pong frame.

By the way, the native Windows HTTP/WebSocket stacks use unsolicited Pong frames as well for "keepalive".  So, does the Windows browsers (Internet Explorer and Edge).

**Comment by mofee** [comment]
thanks!
beause of difference implement of platforms and browsers, so i will to implement the keepalive heartbeat in my business code.
