### ISSUE TITLE
Fix xml documentation issues.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/corefx#33236]
On my hacktoberfest PR to try to fix a up for grabs issue at 
https://github.com/dotnet/corefx/pull/32934 the build kept failing because of the XML documentation being malformed, or just flat out wrong. In that case I have opened this issue as a prerequisite issue to be fixed before that pull request can be merged and the issue it fixes closed as well. And now that I think of it temporarily removing all xml documentation suppressed warnings for now to investigate all of the documentations would probably be best as I am going to fix them anyway (why not fix them all at this rate and simplify the amount of suppressions in the project).

**Comment by karelz** [comment]
@AraHaan I am a bit lost of what you're proposing ... if XML docs produce warnings/errors and need fixing, let's fix them. We do not need new issue for that.

**Comment by AraHaan** [comment]
Ah ok, I was not entirely sure on if I needed to file a issue for the documentation.

**Comment by karelz** [comment]
It's definitely safer to ask :) ... I appreciate it!
Do you plan to submit PR with fixes? If not, can you please describe exactly the problem? Maybe post a list of failures?

**Comment by AraHaan** [comment]
I am closing this for my newer issue as it should explain in more detail what should be left to do.
