### ISSUE TITLE
SqlCommand of type StoredProcedure should support four-part names for synonyms

### ISSUE THREAD

**Issue by mjolka** [dotnet/corefx#33238]
Steps to reproduce:
- Create a stored procedure
- Create a synonym to that stored procedure with a four-part name
- Call that stored procedure via the synonym using a SqlCommand with the CommandType set to CommandType.StoredProcedure

A SqlException is thrown with the message, "A severe error occurred on the current command.  The results, if any, should be discarded."

Example code

```csharp
var serverName = "<SERVER_NAME>";
var db = "<DATABASE_NAME>";

var commands = new[]
{
   "IF (OBJECT_ID('[dbo].[MyStoredProc]', 'P') IS NOT NULL) DROP PROCEDURE [dbo].[MyStoredProc]",
   "CREATE PROCEDURE [dbo].[MyStoredProc] @Param1 int AS BEGIN SET NOCOUNT ON; SELECT @Param1 END",

   "IF (OBJECT_ID('[dbo].[MySynonym]', 'SN') IS NOT NULL) DROP SYNONYM [dbo].[MySynonym]",
   $"CREATE SYNONYM [dbo].[MySynonym] FOR [{serverName}].[{db}].[dbo].[MyStoredProc]"
};

using (var connection = new SqlConnection($"Data Source={serverName};database={db};Integrated Security=SSPI"))
{
    connection.Open();

    foreach (var command in commands)
    {
        using (var cmd = new SqlCommand(command, connection))
        {
            cmd.ExecuteNonQuery();
        }
    }

    using (var cmd = new SqlCommand("[dbo].[MySynonym]", connection))
    {
        cmd.CommandType = CommandType.StoredProcedure;
        cmd.Parameters.Add(new SqlParameter("@Param1", 1));
        cmd.ExecuteNonQuery();
    }
}
```

Further information:

If the synonym has a one-, two-, or three-part name, the command completes successfully.

If the synonym has a four-part name and is called with a SqlCommand  ("exec [dbo].[MySynonym] 1") with the CommandType set to CommandType.Text, the command completes successfully.

**Comment by Wraith2** [comment]
Could you provide a stack trace of the exception?

**Comment by mjolka** [comment]
My apologies; I just tried to reproduce this issue on another computer and was unable to (using SQL Server 2017 Developer Edition). I believe the computer I was seeing this issue on was running SQL Server 2008. I'm guessing it's an issue with SQL Server and not corefx.
