### ISSUE TITLE
Constructor of `Uri` class does not throw `UriFormatException` for relative uri (core 2.1.5)

### ISSUE THREAD

**Issue by lxconan** [dotnet/corefx#33241]
According to [document](https://docs.microsoft.com/en-us/dotnet/api/system.uri.-ctor?view=netcore-2.1#System_Uri__ctor_System_String_), the constructor of `Uri` class should throw `UriFormatException` given the following inputs:

```cs
new Uri("/relative");
```

or 

```cs
new Uri("/relative", UriKind.Absolute);
```

However, it will not throw any exceptions at least under Linux and Mac OS. It automatically adds "file:\\" prefix on it.

**Comment by MarcoRossignoli** [comment]
I confirm right exception throw on Windows in both cases
```
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
```

/cc @karelz @rmkerr

**Comment by karelz** [comment]
Correct, `Uri` is weird and historically works also for file paths - that's why the example is interpreted as Unix absolute path.

The documentation you linked does not say anything about accepting file paths. Maybe it is something we could improve in the docs - thoughts @rmkerr?

**Comment by rmkerr** [comment]
Yeah, I can update the documentation for URI to describe our support for implicit file paths.
