### ISSUE TITLE
TransactionScope.Dispose() doesn't block for Distributed Transactions (the docs says it should be synchronous)

### ISSUE THREAD

**Issue by simendsjo** [dotnet/corefx#33243]
When transactions has been promoted to a distributed transaction, Dispose will return immediately. I cannot find any way to hook into when it's actually finished, causing problems releasing resources as we cannot release them right away before Commit/Rollback has run.

The documentation, https://docs.microsoft.com/en-us/dotnet/api/system.transactions.transactionscope.dispose?view=netframework-4.7.2, states that the call is syncronous, but this isn't the case for distributed transactions it seems.

**Comment by simendsjo** [comment]
Here's a testcase which reproduces the issue:

``` csharp
using System;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Linq;
using System.Threading;
using System.Transactions;

namespace Neo4jTransactionProblems
{
    class Program
    {
        private class DummyTx : ISinglePhaseNotification
        {
            public bool Done;
            public void Prepare(PreparingEnlistment preparingEnlistment)
            {
                preparingEnlistment.Prepared();
            }

            public void Commit(Enlistment enlistment)
            {
                enlistment.Done();
                Done = true;
            }

            public void Rollback(Enlistment enlistment)
            {
                enlistment.Done();
                Done = true;
            }

            public void InDoubt(Enlistment enlistment)
            {
                enlistment.Done();
            }

            public void SinglePhaseCommit(SinglePhaseEnlistment singlePhaseEnlistment)
            {
                singlePhaseEnlistment.Committed();
                singlePhaseEnlistment.Done();
                Done = true;
            }
        }

        static void Main()
        {
            const string sqlCnStr = "Data Source=(local)\\SQLExpress;Integrated Security=SSPI";
            var tx = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled);
            var markedDoneTx = new DummyTx();
            using (var cn1 = new SqlConnection(sqlCnStr))
            {
                cn1.Open();
                using (var cn2 = new SqlConnection(sqlCnStr))
                {
                    cn2.Open();
                    Transaction.Current.EnlistDurable(Guid.NewGuid(), markedDoneTx, EnlistmentOptions.None);
                }
            }
            tx.Dispose();
            var done = markedDoneTx.Done;
            while (!markedDoneTx.Done)
            {
                Thread.Sleep(0);
            }
            Debug.Assert(markedDoneTx.Done == true); // Yep, success eventually
            Debug.Assert(done == true); // .. but unless you waited some milliseconds, this is false
        }
    }
}
```

**Comment by MarcoRossignoli** [comment]
@simendsjo are you using .NET Core or full .NET Framework?

**Comment by simendsjo** [comment]
.NET Framework. .NET Core doesn't support TransactionScope or distributed transactions, does it?

**Comment by MarcoRossignoli** [comment]
@simendsjo I confirm your test also on async/await context...for what it's worth.

**Comment by PinpointTownes** [comment]
Sadly, this is not a recent bug. Oren Eini wrote a blog post about it 8 years ago: https://ayende.com/blog/4528/who-stole-my-transaction

**Comment by simendsjo** [comment]
I was afraid the workaround wouldn't be trustworthy. It seems to work, maybe
because the transactions in question would have done most of the work in
Prepare, so by the time I get the Commit, it would be finished by the time I
finish up. At least it does fix plenty of the issues.

> I suspect you are asking about this because you have experience situations
> where a subsequent transaction attempts to access the same resources and runs
> into locks from the previous transaction.

Several issues. One of them being that I clean up by closing connections before
Commit/Rollback is actually finished.

Sounds like a complete workaround is impossible, and that a fix for this would
be a long way off. I suggest you at least change the documentation to stating
that it might not be synchronous.

As we don't have any hard performance requirements, I might even throw in a
Thread.Sleep for 5ms, although I absolutely abhor such cargo-culted hacks.

**Comment by jimcarley** [comment]
@simendsjo, thanks for your input on the documentation. TransactionScope.Dispose does, in fact, not return until the transaction manager has made the commit "permanent" in its log file or until the transaction manager guarantees that the transaction will not commit (is aborted). So in that sense, the call "is synchronous and blocks until the transaction has been committed or aborted".

But the documentation could be improved to include a note that the call does not wait until all enlistments in the transaction have been notified of the transaction commit or abort and acknowledged the receipt of that notification. This is a subtlety of the 2 phase commit protocol that is left out of the discussion of TransactionScope.Dispose.

In looking at the documentation for CommittableTransaction.Commit (which is what TransactionScope.Dispose calls) contains this information:


"Commit and EndCommit block until the first phase of transaction processing is complete. The first phase ends after all resource managers and enlistments in the transaction have voted on the transaction outcome and the TransactionManager has durably decided to commit or abort the transaction. The second phase of processing is always asynchronous. Therefore, there is no guarantee that data just committed from within a given transaction will be immediately available afterwards when not using another transaction to view this data. "

It seems to make sense to copy this paragraph into the TransactionScope.Dispose description, as well.

There are performance implications to waiting for commit/abort acknowledgement from enlistments. If the transaction manager has somehow lost its connection to the resource manager that owns the enlistment between the time the enlistment voted "yes" in the prepare phase of the protocol and the time the transaction manager makes the final commit decision after gathering votes from all enlistments, then the application thread that called Commit would be "hung" until that TM->RM connection is re-established. The transaction has committed, but the application is not told that and cannot go on to other work.

**Comment by jimcarley** [comment]
@simendsjo Just as a follow up, the documentation for TransactionScope.Dispose at https://docs.microsoft.com/en-us/dotnet/api/system.transactions.transactionscope.dispose?view=netframework-4.7.2 has been updated to contain the same discussion about phase 1 of the 2 phase commit protocol as CommittableTransaction.Commit.

Once again, thanks for your input.

**Comment by simendsjo** [comment]
Thanks for swift action on this. I still think it should be possible to see when all enlistments have completed Commit/Rollback as I now have a very brittle hack where I sleep for 5ms after receiving Commit/Rollback in my dummy enlistment in a hope that things will actually be commited. But I understand changing anything about this would take a lot of work.

**Comment by jimcarley** [comment]
Yes, with a  change in behavior with a new option on the transaction, it could be possible to have the commit of the transaction wait until all children (resource managers and downstream transaction managers and their resource managers) have acknowledge commit of the transaction. Note that in the case of a truly distributed transaction that involves multiple transaction managers, all the transaction managers involved would need to support this new feature to be truly correct.

Modifying the tag from "bug" to "enhancement".

**Comment by jimcarley** [comment]
"enhancement" was the wrong choice because that says "but does not require API changes". The request here would require API changes. Marking it as "wishlist".

**Comment by jimcarley** [comment]
The documentation has been updated. Any enhancement to System.Transactions would require an enhancement to MSDTC. If such an enhancement is done to MSDTC, we can re-open this issue. But I am closing this for now.
