### ISSUE TITLE
System.Net.Http 4.3.4 on Android loses letters when exceeding 35,000 characters

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#33250]
Opening on behalf of a user who emailed the support link on https://www.nuget.org/packages/System.Net.Http : 

> I have problems with System.Net.Http Just tap on Android (iOS and UWP are not included). When I get information in the form of JSON. It starts losing letters when it exceeds 35 000 characters.

cc: @davidsh @rmkerr

**Comment by rmkerr** [comment]
> I have problems with System.Net.Http Just tap on Android (iOS and UWP are not included).

I assume this is in the context of a Xamarin app, as we don't currently support Android or iOS. That means it's running on Mono instead of .NET Core, which I believe has a separate System.Net.Http implementation.

**Comment by davidsh** [comment]
@marek-safar

**Comment by marek-safar** [comment]
Please report the issue at https://github.com/xamarin/xamarin-android/ with repro steps for us to investigate.

**Comment by davidsh** [comment]
Closing the issue in this repo. Please open up an issue in Xamarin repo.
