### ISSUE TITLE
We should use ArtifactPackageDir and arcade's publishing infrastructure

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#33275]
See https://github.com/dotnet/corefx/commit/d77cd27bd6542bc851153f64d9bf9cd02da89bd7 where I workaround this issue but we should see whether or not we should make changes to our props/targets or arcade.

For example:

https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/RepoLayout.props#L73
`<ArtifactsPackagesDir>$(ArtifactsDir)packages\$(Configuration)\</ArtifactsPackagesDir>`

During our builds for a package project Configuration is set to whatever is in the configuration.props file such as netcoreapp or netstandard. Where as arcade assumes Configuration is just Debug or Release. 

@ericstj

**Comment by weshaggard** [comment]
While my earlier attempt workaround the signing issue we still have issues in publishing so I've made another attempt and decided to reset PackageOutputPath after acade sets it. See https://github.com/dotnet/corefx/commit/b0be0afaba7a49dffaa11476007e986fb01e3822.

**Comment by ericstj** [comment]
Configuration isn't really all that relevant for the packaging projects: it's not like we're cross-compiling them by *Group's.  I could imagine that we don't flow configuration into the pkgprojs, and instead just set Configuration as ConfigurationGroup for them.

**Comment by weshaggard** [comment]
Yet another fix necessary for publishing to correctly find the packages. https://github.com/dotnet/corefx/commit/3ede762e6ed6bd9f27bdc37f85cfe8ee02cddceb. @safern when you change to the new publishing we really need to fix this coupling as it is way too strict and hard to get right across the different layers (i.e. build, signing, downloading, publishing).

**Comment by safern** [comment]
I will take this in consideration when I get to that step.

**Comment by wtgodbe** [comment]
@ericstj @safern is this still an issue with the changes to the config system?

**Comment by ViktorHofer** [comment]
No this is issue still applies but I don't see any immediate action necessary. At some point @ericstj will overhaul the existing configuration system and that issue should go away with it.

**Comment by ViktorHofer** [comment]
Fixed by https://github.com/dotnet/corefx/pull/40124
