### ISSUE TITLE
Proposal: MatchFailureException

### ISSUE THREAD

**Issue by gafter** [dotnet/corefx#33284]
## Rationale

In order to facilitate the language feature at https://github.com/dotnet/csharplang/issues/45, which has been approved by the LDM and mostly implemented, we should add the exception `MatchFailureException` to the framework.  This exception is to be thrown when no branch of a pattern-matching switch expression matches the input at runtime.

## Proposal

```cs
namespace System
{
    /// <summary>
    /// Indicates that a switch expression that was non-exhaustive failed to match its input
    /// at runtime, e.g. in the C# 8 expression <code>3 switch { 4 => 5 }</code>.
    /// The exception optionally contains an object representing the unmatched value.
    /// </summary>
    [System.Runtime.InteropServices.ComVisible(true)]
    [Serializable]
    public class MatchFailureException : InvalidOperationException
    {
        public MatchFailureException();
        public MatchFailureException(object unmatchedValue);
        public object UnmatchedValue { get; }
        [System.Security.SecurityCritical]
        public override void GetObjectData(SerializationInfo info, StreamingContext context);
    }
}
```

See also https://github.com/dotnet/roslyn/issues/27747
/cc @jcouv @jaredpar

**Comment by jcouv** [comment]
It may be useful to provide more context with an example of "when no branch of a pattern-matching switch expression matches the input at runtime."

**Comment by svick** [comment]
Should the exception include a constructor that takes a `string message`? Even if the compiler didn't use it initially, that constructor could be useful in the future to provide a more detailed message.

**Comment by gafter** [comment]
@svick Like with `NullReferenceException`, I can't imagine circumstances in which the compiler could use the message parameter.

**Comment by gafter** [comment]
I've added an (optional) `string unmatchedValue` parameter.

**Comment by gafter** [comment]
I changed the base type to `InvalidOperationException`.

**Comment by stephentoub** [comment]
It should also override GetObjectData.

**Comment by gafter** [comment]
@stephentoub I was proposing the API, not the implementation.

**Comment by stephentoub** [comment]
@gafter, it actually is API.  The type isn't sealed, so if those aren't exposed in the API but they're there in the implementation, a derived type doing "base." to invoke them may end up skipping the implementation and going to the next ancestor in the hierarchy.

**Comment by Neme12** [comment]
With the current proposal, if we `UnmatchedValue` is null, there's no way to know whether the value was actually null or `unmatchedValue` wasn't provided. Also, why is `unmatchedValue` optional? When would the compiler omit it?

**Comment by stephentoub** [comment]
> When would the compiler omit it?

e.g. if it's something that can't be boxed, like a `ref struct`

**Comment by Neme12** [comment]
If only we had `Optional<>`... Adding `bool HasUnmatchedValue` is ugly but I don't see any other option.

**Comment by gafter** [comment]
Updated to add `GetObjectData`

**Comment by terrajobst** [comment]
We had a quick look today. It looks we should have a chat with the C# folks to better understand the scenario.

Why do we need a new exception? Can't we just throw an existing one, such as:

* `NotImplementedException`
* `InvalidOperationException`
* `NotSupportedException`

It seems (at least to me) that he `unmatchedValue` isn't a good idea if it can't be used in all cases (because it means developers have to read the message and check the source code anyway).

**Comment by stephentoub** [comment]
> It seems (at least to me) that he unmatchedValue isn't a good idea if it can't be used in all cases, such as ref structs (because it means developers have to read the message and check the source code anyway).

FWIW, I pushed for this to be included because it can only help with debugging, and in most cases it should be able to include the value (it won't in corner cases like matching on a ref struct).

**Comment by Neme12** [comment]
I think in most cases developers would not have to check the source code, assuming there's a property called HasUnmatchedValue or an equivalent way of knowing that the unmatched value is present (and therefore it's actually null, not just a missing piece of information).

**Comment by jcouv** [comment]
@gafter I assume that once this type is added for Core 3, you'll want it ported to mono as well. 
If so, please file an issue there (similar to https://github.com/mono/mono/issues/12019) and track it in the umbrella issue for patterns feature.

**Comment by terrajobst** [comment]
> Our current plan does not have a problem running on older platforms, but at the loss of a meaningful exception on such platforms - you get the not quite appropriate `InvalidOperationException`.

That seems like a bad idea as that's a source breaking change:

1. I compile for .NET Core 2.x.  I get `InvalidOperationException`.
2. I now retarget to .NET Core 3.x. I now get `MatchFailureException`.

Are we sure we want behavior mismatches like this? FWIW, I think either of the existing exception APIs is good enough. Personally, I think `NotImplementedException` as this bug is virtually unrecoverable as the author didn't handle (or *implement*) all the cases. However, I do buy they argument having a dedicated exception type would be slightly more desirable, especially because it can provide better diagnostics. The proposed type shape looks good to me.

My only concern is that this leads to source breaking changes.

**Comment by gafter** [comment]
@terrajobst What do you mean by source breaking changes?

If your program crashes on .NET Core 2.x, it will crash on .NET Core 3.x.

If you catch the excepetion (using the type `InvalidOperationException`) on .NET Core 2.x, your code will also catch the exception on .NET Core 3.x, as `MatchFailureException` is derived from the `InvalidOperationException`.

What is the source breaking change you're concerned about?

**Comment by danmosemsft** [comment]
Would it be confusing to have an exception named `MatchFailureException ` that isn't used by Regexes?

**Comment by terrajobst** [comment]
> If you catch the excepetion (using the type `InvalidOperationException`) on .NET Core 2.x, your code will also catch the exception on .NET Core 3.x, as `MatchFailureException` is derived from `InvalidOperationException`.

Ah, I missed the inheritance relationship. That addresses my concern.

**Comment by terrajobst** [comment]
> Would it be confusing to have an exception named `MatchFailureException ` that isn't used by Regexes? I'm wondering if the name could be more specific.

What about `PatternMatchException`?

**Comment by Neme12** [comment]
Why would "match" imply regex? Is that a regex-specific word?

**Comment by danmosemsft** [comment]
> Why would "match" imply regex? Is that a regex-specific word?

No, but it's a common use of it. For example our public type named Match is part of regex.

> What about PatternMatchException?

I think that's better (although `Pattern` is also a term used in regex API, `PatternMatch` is not)

**Comment by terrajobst** [comment]
* There is a possibility for a breaking change: library author ships a library for 3.0 and then later downgrades to 2.0, which is is expected to be transparent to consumer. Now a different exception exception is thrown. Seems remote though.
* We don't expect any user code to specifically handle this exception (outside of implicit catch-all style handlers). We should move this to `System.Runtime.CompilerServices`.
* We should have a less generic name, for instance `SwitchExpressionException`.

```C#
namespace System.Runtime.CompilerServices
{
    /// <summary>
    /// Indicates that a switch expression that was non-exhaustive failed to match its input
    /// at runtime, e.g. in the C# 8 expression <code>3 switch { 4 => 5 }</code>.
    /// The exception optionally contains an object representing the unmatched value.
    /// </summary>
    [System.Runtime.InteropServices.ComVisible(true)]
    [Serializable]
    public sealed class SwitchExpressionException : InvalidOperationException
    {
        public SwitchExpressionException();
        public SwitchExpressionException(object unmatchedValue);
        public object UnmatchedValue { get; }
        [System.Security.SecurityCritical]
        public override void GetObjectData(SerializationInfo info, StreamingContext context);
    }
}
```

**Comment by Neme12** [comment]
So how do we know whether `UnmatchedValue` is present or not? That's impossible to tell with the current API :confused:

**Comment by gafter** [comment]
The current shape of the API does not provide a way for someone catching it to know if an unmatched value is present. However, it is not intended for programmatic use.

**Comment by Neme12** [comment]
Since this is not intended to ever be caught and accessed by user code, could `UnmatchedValue` just throw if the value is unknown, with an additional `HasUnmatchedValue` property?

**Comment by gafter** [comment]
@terrajobst The name of this exception is now tied to the name of the construct in C#.  If we add a similar construct in VB, it probably won't be called a switch expression, and reusing this exception would seem like a stretch.

**Comment by gafter** [comment]
It is `SwitchExpressionException` as reviewed https://github.com/dotnet/corefx/issues/33284#issuecomment-448332714

**Comment by danmosemsft** [comment]
@gafter OK thanks, I was confused by your subsequent comment suggesting you disagreed. https://github.com/dotnet/corefx/issues/33284#issuecomment-448385260

**Comment by danmosemsft** [comment]
@gafter this is in please feel free to wire it up!

**Comment by danmosemsft** [comment]
@jaredpar @jcouv just making sure you saw this is now available and you aren't waiting on us.

**Comment by gafter** [comment]
The compiler is all wired up in the latest VS2019 preview, though I haven't tried it with the latest Core.
