### ISSUE TITLE
Port and run Utf8JsonReader perf tests

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#33299]
Port over the existing performance tests from https://github.com/dotnet/corefxlab/tree/63ef1a5db4fdbfcf9822b8cd2cbc3921b3d3cb9e/tests/Benchmarks/System.Text.JsonLab

Run them on the latest implementation of `Utf8JsonReader`.

Relies on https://github.com/dotnet/corefx/pull/32843 & https://github.com/dotnet/buildtools/pull/2190.

cc @adamsitnik

**Comment by ahsonkhan** [comment]
@adamsitnik, can you help with this port?

**Comment by ahsonkhan** [comment]
@adamsitnik, let me know if you are unable to port these tests over to dotnet/performance. It is important that we get these tests in by 6/26 to track regressions between releases.

**Comment by ahsonkhan** [comment]
@adamsitnik, are you planning on working on this issue?

**Comment by ericstj** [comment]
@adamsitnik do you think you can help here?  I think the work involved will be to review what's currently in the JsonLab set and port over those that don't overlap with what's already been added.  /cc @danmosemsft

**Comment by ericstj** [comment]
Thank you @Jozkee for picking this up!
