### ISSUE TITLE
Consider line feed, carriage return, or both as an end of single line comment.

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#33293]
Currently, we assume that a single line comment ends with a line feed. We need to change this so that a carriage return also means an end of comment (or both \r\n). This way we match the semantics of Json.NET as well.

**Comment by ahsonkhan** [comment]
cc @GrabYourPitchforks

**Comment by stevenaw** [comment]
Is this ready for development? If so, I'd like to pick this up.

**Comment by stevenaw** [comment]
Thanks for the feedback on my PR @ahsonkhan 
I hadn't realized JSON.Net would continue to process text as a single-line comment between a `\r` and `\n`. I'll be able to take another go at this within the next few days.

I have a question though. If `\r` does not end a single-line comment when it is followed (at some point) by a `\n`, would that make checking for `\r` to end a single-line comment redundant? Or are you saying we should treat `\r` as a comment terminator only if it is _not_ followed (at some point) by a `\n`?

**Comment by stevenaw** [comment]
Wait, sorry, I had misread your case here: https://github.com/dotnet/corefx/pull/33393#discussion_r232521027

Now I think I get it.
