### ISSUE TITLE
Azure function (v2 csx) not throwing exception when response code is not successful

### ISSUE THREAD

**Issue by rambotech** [dotnet/corefx#33305]
I ran into a case of reading IsSuccessStatusCode which returns false, then later executing the EnsureSuccessStatusCode() method which did not throw an error.  This is an extract of the code:

```c#
		var response = await http.GetAsync($"/Notifications/Message/{param}");
		if (!response.IsSuccessStatusCode)
		{
			log.Info($"Message for  {device} with id {dataId} was unavailable.");
			response.EnsureSuccessStatusCode();
		}
		message = await response.Content.ReadAsStringAsync();
```
If the if() statement is true (Success Code == false), the expectation is that the EnsureSuccessStatusCode() will also detect that and throw an HttpRequestException.  The observed behavior in the Azure Function is that the log.Info() line does its work (log console shows it in blue) and then the logging ends... no exception or failure reported in red text.

This does not seem to line up with the code [here](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpResponseMessage.cs).  Is this the code in use for a csx script for Azure v2?  I see nothing in the IsSuccessStatsCode get which would reset anything.

**Comment by rmkerr** [comment]
Given that all EnsureSuccessStatusCode does is directly check IsSuccessStatusCode, I don't think that this is a bug in .NET Core. 

https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.Net.Http/src/System/Net/Http/HttpResponseMessage.cs#L154-L166

I'm not sure where would be a better place to report this issue. Any thoughts @karelz?

**Comment by karelz** [comment]
Based on the information above, it seems to be either:
* Race of something modifying the response.
* Execution of instructions out of order (e.g. HW issue, or some invasive SW like IL rewriter)
* Bug in JIT

If you have a repro (even if it happens only with some frequency), ideally outside Azure functions, we can track it down.
If you have repro only in Azure functions, we can try to contact that team to figure out if it always runs on same HW to rule out HW issues.

**Comment by davidsh** [comment]
>Is this the code in use for a csx script for Azure v2

I'm not familiar with Azure functions.  But do they use .NET Core underneath?  Perhaps they use .NET Framework. 

>If you have a repro (even if it happens only with some frequency), ideally outside Azure functions, we can track it down.

I agree it would be useful to get a repro outside of using Azure functions.

**Comment by karelz** [comment]
Closing for now as not actionable. Feel free to reopen if there is a repro / actionable information for us. Thanks!
