### ISSUE TITLE
Don't lock on "this"

### ISSUE THREAD

**Issue by jslicer** [dotnet/corefx#33311]
https://github.com/dotnet/corefx/blob/cccc660d0bdbb0e821f7f239aecc806b03fa8a8c/src/System.ComponentModel.Primitives/src/System/ComponentModel/Component.cs#L146

See https://stackoverflow.com/a/251668/3312 for the reasoning behind why locking on "this" can cause threading issues.

**Comment by stephentoub** [comment]
Yes.  However, this code has been like this for a long time, and changing what it locks on is a visible and potentially breaking change, in that external code that synchronizes with operations by locking on the instance will now be taking a different lock... and that can introduce its own problems, like deadlocks.

**Comment by jslicer** [comment]
Certainly can't argue much with legacy compatibility; appreciate the commentary.
