### ISSUE TITLE
Reject single line comments containing non-standard new line characers within Utf8JsonReader

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#33321]
In particular, throw as invalid JSON if a single line comment contains U+2028 / U+2029 (i.e. Line separator, Paragraph separator) anywhere within it which [JSON5](https://spec.json5.org/#escapes) treats as valid line terminator sequences.

A single line comments ends on either carriage return, line feed, or both (\r\n). We do not support any other line terminator sequence.

This constraint does not apply to multi-line comments which only end with `*/`.

cc @GrabYourPitchforks

**Comment by stevenaw** [comment]
Is this ready for development? If so, I'd like to pick this up.
