### ISSUE TITLE
Apparently unable to change cultures on Linux

### ISSUE THREAD

**Issue by dougbu** [dotnet/corefx#3332]
With System.Globalization 4.0.11-beta-23302, all cultures are apparently "Invariant Language (Invariant Country)". That is the `EnglishName` value of the initial culture as well as `new CultureInfo("en-GB")` and `new CultureInfo("fr-FR")`.

Unsurprisingly, changing `CurrentCulture`, `CurrentUICulture`, `DefaultThreadCurrentCulture`, or `DefaultThreadCurrentUICulture` has no effect.

For example the test program at [dougbu/CultureInfo](https://github.com/dougbu/CultureInfo) works as expected with DNX 4.5.1 or DNX Core 5.0 on Windows and with Mono on Linux:
```
Names 'en-GB' / 'fr-FR'
English names 'English (United Kingdom)' / 'French (France)'
Current cultures before 'English (United States)' / 'English (United States)'
Current cultures after default thread switch 'English (United Kingdom)' / 'French (France)'
Current cultures after current switch 'French (France)' / 'English (United Kingdom)'
```

With Core CLR on Linux however, the output is
```
Names '' / ''
English names 'Invariant Language (Invariant Country)' / 'Invariant Language (Invariant Country)'
Current cultures before 'Invariant Language (Invariant Country)' / 'Invariant Language (Invariant Country)'
Current cultures after default thread switch 'Invariant Language (Invariant Country)' / 'Invariant Language (Invariant Country)'
Current cultures after current switch 'Invariant Language (Invariant Country)' / 'Invariant Language (Invariant Country)'
```

**Comment by dougbu** [comment]
@ellismg is this expected until #2770 is done?

**Comment by ellismg** [comment]
Yes.  We presently use invariant data for all locales.  This should also be fixed by beta8.

**Comment by ellismg** [comment]
Should be fixed in master now.
