### ISSUE TITLE
Allocation-free overload of ConvertFromUtf32()

### ISSUE THREAD

**Issue by iSazonov** [dotnet/corefx#33329]
## Rationale

Current [`public static string ConvertFromUtf32(int utf32)`](https://github.com/dotnet/corefx/blob/8c3eea964795d6ad797ef9067ce46f3adf9f949e/src/Common/src/CoreLib/System/Char.cs#L923
) method does string allocations. In PowerShell repo we had to implement new allocation-free method in tokenizer where it is important to reduce allocations.

## Proposed API

```c#
namespace System
{
    public readonly struct Char : IComparable, IComparable<char>, IEquatable<char>, IConvertible
    {
        public static (char highSurrogate, char lowSurrogate) ConvertFromUtf32(int utf32);
        // or
        public static char ConvertFromUtf32(int utf32, out char lowSurrogate);
    }
}

**Comment by svick** [comment]
What should the method return for code points that are represented as a single `char`?

---

Is this method actually necessary, when [`Encoding.UTF32.GetChars`](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.getchars?view=netcore-2.1#System_Text_Encoding_GetChars_System_ReadOnlySpan_System_Byte__System_Span_System_Char__) exists?

E.g. you could implement this method yourself today as:

```c#
public static (char highSurrogate, char lowSurrogate) ConvertFromUtf32(int utf32)
{
    Span<int> i = stackalloc int[1] { utf32 };

    // TODO: won't do the right thing on a big-endian architecture
    Span<byte> bytes = MemoryMarshal.Cast<int, byte>(i);

    Span<char> chars = stackalloc char[2];

    int count = Encoding.UTF32.GetChars(bytes, chars);

    if (count != 2)
        throw new Exception();

    return (chars[0], chars[1]);
}
```

**Comment by iSazonov** [comment]
@svick Thanks for pointing `Encoding.UTF32.GetChars()`. My request here is more about that CoreFX expose only a public method with allocations which is easily discovered but haven't an allocation free overload.

**Comment by stephentoub** [comment]
@GrabYourPitchforks, is there anything else needed here or is it entirely covered by Rune?

**Comment by GrabYourPitchforks** [comment]
It's covered by `Rune`.

**Comment by iSazonov** [comment]
Thanks!
