### ISSUE TITLE
Add GetCommentValue to Utf8JsonReader

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#33347]
We have a GetStringValue today and although comments are strings, the GetCommentValue would have different semantics. For instance, it would not do any unescaping (and you would get the comment delimiters here where you don't for strings, i.e. quotes). Keeping comment reading as part of GetStringValue makes documenting the semantics of the API difficult.

Context: https://github.com/dotnet/corefx/commit/3d24832abe217779fd9886e1a01ab4ee06f1488e#r31224311

Hence, add a separate API:
```C#
public ref partial struct Utf8JsonReader
{
    public string GetCommentValue();
}
```

cc @bartonjs, @stephentoub

**Comment by terrajobst** [comment]
We should aling the naming with the writer and there we decided to drop the `Value`-suffix, so it should probably be `GetComment()`.
