### ISSUE TITLE
Linux & Mac Support for System.Security.Cryptography.Pkcs

### ISSUE THREAD

**Issue by fujiy** [dotnet/corefx#3334]
Is there any plan to support classes in System.Security.Cryptography.Pkcs namespace? Its essential to create p7s files and sign data.

Thanks

**Comment by joshfree** [comment]
Related https://github.com/dotnet/corefx/issues/7830 -- Add Support for EnvelopedCms (API Review)

**Comment by karelz** [comment]
@bartonjs @eerhardt is it part of netstandard2.0 plan?

**Comment by bartonjs** [comment]
@karelz No. Firstly, because the API already exists (but only is implemented for Windows). Secondly, because it's in System.Security.dll which is not part of that scope.

**Comment by bartonjs** [comment]
This is a work-in-progress on the dev/cms_unix branch; but that has a merge-blocking bug (#10621).

**Comment by karelz** [comment]
We need someone to finish it up in the branch.

**Comment by danmosemsft** [comment]
@bartonjs estimates 4 weeks remaining
