### ISSUE TITLE
Required types for System.Drawing.Color marshalling on .NET Core don't ship in-framework

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/corefx#33342]
.NET Core's marshalling for `System.Drawing.Color` in COM Interop uses the `System.Drawing.ColorTranslator` type to convert the `Color` object to an `OLE_COLOR` value.

 The `System.Drawing.ColorTranslator` type is forwarded from the in-box `System.Drawing` assembly to the OOB `System.Drawing.Common` assembly. As a result, the type may not always be available when marshalling a `System.Drawing.Color`. Additionally, the `System.Drawing.ColorTranslator` type is unavailable for our tests in the CoreCLR repo to use to verify behavior (which was how I discovered this issue).

cc: @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
cc @jeffschwMSFT

**Comment by AaronRobinsonMSFT** [comment]
@danmosemsft or @stephentoub do either of you know who would be the best to talk to about this change? Any concerns in general with moving the `ColorTranslator` to an in-box experience?

**Comment by safern** [comment]
Is `ColorTranslator` the only type we need to be inbox? If that is the case I don't mind with moving ColorTranslator to System.Drawing.Primitives (which ships in-box) and add a TypeForward for it in System.Drawing.Common

**Comment by AaronRobinsonMSFT** [comment]
That is the only one we directly use. The full closure of what the `ColorTranslator` type needs/uses is a different story 😄

**Comment by safern** [comment]
It seems like its Closure should be Color, ColorUtil and KnownColorTable which are part of System.Drawing.Primitives, so I don't see any problem on moving it down.

**Comment by AaronRobinsonMSFT** [comment]
@safern w00t! Thank you much. Any ETA?

@jkoritzinsky What is the plan to re-enable the testing for this scenario? Will this be a pain now?

**Comment by jkoritzinsky** [comment]
Once it's in-box, testing will be really straightforward! I should be able to get it done pretty quickly!

**Comment by safern** [comment]
> @safern w00t! Thank you much. Any ETA?

I'm working in various random urgent stuff. Once I get some spare time I should have this PR ready. Maybe tomorrow/monday.

**Comment by jkoritzinsky** [comment]
@safern any update on this?

**Comment by safern** [comment]
Not yet, sorry I've been with P0 stuff for infrastructure. Will try to spend some time tomorrow in this I promise :smile:

**Comment by safern** [comment]
@jkoritzinsky I've been investigating a little further in what it takes to move down the type inbox to System.Drawing.Primitives and it seems like a lot more work than I thought because of the way System.Drawing.Common is structured. I wanted to know what is the scenario where this is needed since this has been like that ever since 2.0. Is this a winforms specific scenario? 

I think we should just make Corelib resilient to this type being missing.

cc: @ericstj @jkotas

**Comment by ericstj** [comment]
It seems reasonable to me that CoreLib light-up on the presence of this type in its current assembly.  It'll be there for WinForms.  If someone building a console app wants that behavior they can add a reference to System.Drawing.Common.  I think you'll need to handle the missing case anyhow since I can imagine linked / tree-shaken standalone apps may be missing all of System.Drawing.*.

**Comment by jkoritzinsky** [comment]
Office interop is another scenario where the `ColorTranslator` type needs to be available for the runtime to load up.

**Comment by jkoritzinsky** [comment]
Additionally, AFAICT I can't figure out a way to add tests in CoreCLR for the marshalling that uses `ColorTranslator`. I can't figure out a way to reference packages that aren't inbox and have their dlls placed in the right directory.

**Comment by jkoritzinsky** [comment]
The marshaller also only lights up on methods on `ComImport`ed interfaces, which weren't really well supported until recently IIRC. Which would explain one of the reasons that no one ever realized that this was a problem (people weren't porting over code that happened to use the marshaller).

**Comment by jkoritzinsky** [comment]
Ok while setting up testing, I decided to see what the error message would look like if the user didn't have the `System.Drawing.Common` assembly referenced. I've included the error message below:
```
Test Failure: System.IO.FileNotFoundException: Could not load file or assembly 'System.Drawing.Common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Drawing.Common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Server.Contract.IColorTesting.GetRed()
   at NetClient.ColorTests.VerifyGetRed() in C:\Users\jekoritz\source\repos\coreclr\tests\src\Interop\COM\NETClients\Primitives\ColorTests.cs:line 33
   at NetClient.ColorTests.Run() in C:\Users\jekoritz\source\repos\coreclr\tests\src\Interop\COM\NETClients\Primitives\ColorTests.cs:line 23
   at NetClient.Program.Main(String[] doNotUse) in C:\Users\jekoritz\source\repos\coreclr\tests\src\Interop\COM\NETClients\Primitives\Program.cs:line 25
```

This exception doesn't happen on framework since the `ColorTranslator type is in-box`. I'll still work on using the `test_dependencies.csproj` to reference the package, but I just wanted to post the error message as well.

**Comment by ericstj** [comment]
@jkoritzinsky how does that compare to the behavior prior to your changes?  I'm not super-familiar with all the use cases of this codepath, but would it ever make sense to keep the old non-throwing behavior?  We do that [elsewhere](https://github.com/dotnet/coreclr/blob/ad561d0dee8345a1a1b6105b44be527970c0b27f/src/System.Private.CoreLib/shared/System/ComponentModel/DefaultValueAttribute.cs#L70-L71).

**Comment by jkoritzinsky** [comment]
I haven't made any changes. That's how it currently is. The codepath that is throwing is in mlinfo.cpp in coreclr: https://github.com/dotnet/coreclr/blob/ad561d0dee8345a1a1b6105b44be527970c0b27f/src/vm/mlinfo.cpp#L1028

With my requested change from this issue, the type-forward in `System.Drawing` that currently points to the definition of `System.Drawing.ColorTranslator` in `System.Drawing.Common` would be updated to point to the definition of `System.Drawing.ColorTranslator` in `System.Drawing.Primitives`. Then since it would be in-box, we wouldn't have to worry about this file not found exception being thrown.

**Comment by ericstj** [comment]
That's relative: it'd still be throwing for folks doing self-contained and linking.  It's also already inbox for WinForms applications since System.Drawing.Common is part of the WindowsDesktop shared framework.

The fact that its always been throwing here means its likely not so important for console apps.

**Comment by jkoritzinsky** [comment]
Ok :+1:. I've been able to use the `test_dependencies.csproj` file to unblock my testing for the marshaller, so I don't need this done for test coverage any more.

**Comment by safern** [comment]
Given the conversation, I think this issue can then be closed?

**Comment by jkoritzinsky** [comment]
I think so.
