### ISSUE TITLE
Expose Assembly.EntryPoint

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#3336]
Today Assembly is missing EntryPoint, it would be great if this were exposed (as it in on .NET Framework) so that managed code can invoke entry points in other managed executables.

See https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Runtime.Sources/Impl/EntryPointExecutor.cs#L77 as an example.

/cc @nguerrera

**Comment by weshaggard** [comment]
This seems reasonable assigning to @nguerrera to have a look.

**Comment by davidfowl** [comment]
@joshfree We need this for RC1

**Comment by nguerrera** [comment]
@davidfowl OK. Read this as "nice to have" in triage. I'll do it tomorrow.

**Comment by nguerrera** [comment]
@terrajobst @KrzysztofCwalina @weshaggard Can I get a quick API review. The proposal would be to simply expose this property as it exists on other platforms:

```C#
public class Assembly {
    ...
    public virtual MethodInfo EntryPoint { get; }
    ...
}
```
I don't think we currently keep enough info in the .NET Native Metadata for this, but I see no reason why we couldn't add it. I think in the meantime, it is OK if it returns null always on .NET Native. It is already implemented in mscorlib on CoreCLR. On .NET, so the change there would just add it to the contract.

**Comment by weshaggard** [comment]
It is already documented (https://msdn.microsoft.com/en-us/library/windows/apps/system.reflection.assembly.entrypoint(v=vs.105).aspx) as returning null if no entry point is found, so I can live with that as the result for .NET Native.

I'm fine with adding this back as it exists on Assembly.

**Comment by davidfowl** [comment]
Yay!

**Comment by joshfree** [comment]
Thanks @nguerrera
