### ISSUE TITLE
Weird issue with Directory Path

### ISSUE THREAD

**Issue by codebird** [dotnet/corefx#33368]
```c#
var path = "Some_Directory/Some_Other_Directory/Directory_I_Want_To_Delete";
new FileInfo(path).Directory.Delete(true);
```
This will actually delete this path Some_Directory/Some_Other_Directory recursively, ignoring Directory_I_Want_To_Delete.

Whereas if I use this 
```c#
var path = "Some_Directory/Some_Other_Directory/Directory_I_Want_To_Delete/";
new FileInfo(path).Directory.Delete(true);
```
It works well as expected. 

First I thought this was a bug, then following the code, I noticed that the length is being calculated based on separator char. The question is, why is this being done like this, why isn't the path taken as is even if there is no "/" at the end.

**Comment by JeremyKuhne** [comment]
`FileInfo.Directory` has always been `Path.GetDirectoryName` which is a simple "trim final separator and chars". Changing that behavior would cause a lot of fallout even if we could make it consistent. When you use `FileInfo` we could, in theory, check to see if the target is a directory, but making that determination isn't always possible (path doesn't exist, lack of rights, etc.).

The right answer here is to use `DirectoryInfo` when you know that the path is intended to represent a directory. Then you can get `Parent` and `Delete` should always work as you expect.
