### ISSUE TITLE
Distributing .NET Core app and license notice

### ISSUE THREAD

**Issue by wrathofodin** [dotnet/corefx#33364]
All .NET core libraries are licensed under MIT. However, most System.* NuGet packages still point to MS-.NET-Library License located here: https://www.microsoft.com/net/dotnet_library_license.htm

https://www.nuget.org/packages/System.Linq/ for example.

How exactly .NET Core apps should be distributed, should license for each single standard System package be included with the software? For example:

```
System.Linq
-----------
>> License and copyright notice here <<

System.ComponentModel
---------------------
>> License and copyright notice here <<

... and so on
```
Does publishing app in self-contained mode change anything in this regard? That is, should we include license for .NET Core runtime's dlls as well? 

What should be included when distributing regular .NET Framework app, like WPF-app?

Should ThirdPartyNotices distributed with .NET Core be included with my software?

@richlander

**Comment by jkotas** [comment]
> https://www.nuget.org/packages/System.Linq/ for example.

This nuget package is not used and maintained anymore. It has not been updated in 2 years. If you are building .NET Core 2.0+ apps, you should not be getting any code from it.

All current and maintained nuget packages (e.g. https://www.nuget.org/packages/System.Reflection.Metadata/) point to the MIT license.

**Comment by Sigvaard** [comment]
@jkotas yes but what about transitive dependencies?

For example see: https://www.nuget.org/packages/NuGet.ProjectModel/

it has a dependency on https://www.nuget.org/packages/System.Dynamic.Runtime/ and https://www.nuget.org/packages/System.Threading.Thread/ and they both link to https://www.microsoft.com/net/dotnet_library_license.htm when nuget itself is apache licensed.

**Comment by Sigvaard** [comment]
In my opinion it's not that clear. I'm not a lawyer. Should I include a copy of this .htm along with distributed files?

**Comment by danmosemsft** [comment]
@richlander anything you wish to add here?

If not, I think we should close. We cannot offer legal guidance.
