### ISSUE TITLE
Utf8Parser for doubles not matching the right precision.

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#33360]
From https://github.com/dotnet/corefx/pull/33216#issuecomment-437244693

Observing failures recently, likely due to https://github.com/dotnet/coreclr/pull/20707 / https://github.com/dotnet/corefx/pull/33324

It is causing tests that assert two doubles be equal to fail.

```C#
Assert.True(json.TryGetDoubleValue(out double numberDouble));
string roundTripActual = numberDouble.ToString("R", CultureInfo.InvariantCulture);
double actual = double.Parse(roundTripActual, CultureInfo.InvariantCulture);

string roundTripExpected = doubles[count].ToString("R", CultureInfo.InvariantCulture);
double expected = double.Parse(roundTripExpected, CultureInfo.InvariantCulture);
Assert.Equal(expected, actual); // Failing for various double values.
```

`TryGetDoubleValue` is relying on `Utf8Parser`:
```C#
Utf8Parser.TryParse(ValueSpan, out value, out int bytesConsumed, standardFormat)
```

cc @tannergooding, @danmosemsft

**Comment by karelz** [comment]
@ahsonkhan what is the action item expected here? Is it tracking a bug, if yes, in which area?

**Comment by tannergooding** [comment]
This is a tracking bug for me. The PR that fixes it is here: https://github.com/dotnet/coreclr/pull/20934

**Comment by tannergooding** [comment]
This should be resolved now.
