### ISSUE TITLE
HttpClient GetAsync not waiting with extension method

### ISSUE THREAD

**Issue by woladie** [dotnet/corefx#33365]
When using HttpClient with extension methods GetAsync does not wait for return of message.

I use HttpClient in unit tests with xUnit and a typed client , .NET Core 2.1.1
example:
```c#
public static async Task<TData> GetContentFromJson<TData>(this HttpClient httpClient, string url, string accessToken = null)
{
    if (!string.IsNullOrWhiteSpace(accessToken))
        SetBearerToken(httpClient, accessToken);

    HttpResponseMessage message = await httpClient.GetAsync(url);
    return await message.GetContentFromJson<TData>();
}
```
while manually waiting for message works:
```c#
public static async Task<TData> GetContentFromJson<TData>(this HttpClient httpClient, string url, string accessToken = null)
{
    if (!string.IsNullOrWhiteSpace(accessToken))
        SetBearerToken(httpClient, accessToken);

    HttpResponseMessage message = httpClient.GetAsync(url).ConfigureAwait(false).GetAwaiter().GetResult();
    return await message.GetContentFromJson<TData>();
}
```

Has anybody observed similiar behaviour?
In contrary PostAsync works.

**Comment by stephentoub** [comment]
Can you share a small but complete/runnable repro?

**Comment by caesar1995** [comment]
@woladie Any updates for the repro? (xUnit should not involved)

**Comment by woladie** [comment]
In this testing project everything works https://github.com/woladie/HttpClientAsncTest .
It could also be an issue with the internal REST services built with ASP.NET Core e.g. some ThreadPool issue. Testing REST calls with with Postman does not reveal any problems.
