### ISSUE TITLE
SqlDataAdapter is missing from NetStandard System.Data.SqlClient

### ISSUE THREAD

**Issue by divega** [dotnet/corefx#33375]
_From @EdLichtman on November 9, 2018 15:48_

I'm attempting to build an utility library using NetStandard and I have installed System.Data.Common and System.Data.SqlClient. When I attempt to use a SqlDataAdapter I get the error "The type or namespace name "SqlDataAdapter" could not be found.

What am I supposed to do to resolve?

_Copied from original issue: aspnet/EntityFrameworkCore#13929_

**Comment by divega** [comment]
I don't fully understand why that would be the case, but this issue seems related to the compatibility shims mentioned in https://github.com/dotnet/corefx/issues/27247. 

@EdLichtman or @@dallancarr if you are able to provide a repro project that shows the failure, that would be great. 

I am not sure whether this is a bug in the SqlClient package (in https://github.com/dotnet/corefx/issues/27247#issuecomment-369522617 I asked @terrajobst if SqlClient should include its own compatibility shim), or an issue (or known limitation) with .NET Standard, in which case this may need to be moved to https://github.com/dotnet/standard/ or closed.

**Comment by EdLichtman** [comment]
Closing issue since I'm unable to recreate. Maybe it was a turning it off and on again issue. Maybe it was Resharper installing the wrong version of System.Data.SqlClient, but at this point my brand new solution following the same steps to recreate on my work machine is compiling without issue.

**Comment by EdLichtman** [comment]
I can't find the normal close issue button. Is this a permissions thing or am I not looking hard enough? If it's a permissions thing, please close this issue since it appears to already have been fixed at some point.

**Comment by keeratsingh** [comment]
Closing issue as the original author @EdLichtman is unable to repro.
