### ISSUE TITLE
Tracking looking at Span indexer used with the Index class

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#33376]
We need to measure the perf when using Span<T> indexer which takes Index parameter. current implementation is referencing the other indexer which take int. The question is, do we need to implement the indexer with the Index as we implemented the indexer with the int? or we'll not observe any big change in the perf?

**Comment by tarekgh** [comment]
https://github.com/dotnet/corefx/pull/33352

**Comment by stephentoub** [comment]
More than just perf, we need to review the whole API.  It was only in code review at the last minute that we spotted things like missing Equals/GetHashCode/IEquatable/etc. that are common types like this.  The whole API should be reviewed a fresh.  I imagine we'll discuss things like operators, IComparable, method names, the factory approach for Range, etc.

**Comment by stephentoub** [comment]
For reference, here's what's currently exposed (copied from the ref):
```C#
    public readonly partial struct Index : System.IEquatable<System.Index>
    {
        private readonly int _dummyPrimitive;
        public Index(int value, bool fromEnd) { throw null; }
        public int Value { get { throw null; } }
        public bool FromEnd { get { throw null; } }
        public override bool Equals(object value) { throw null; }
        public bool Equals(Index other) { throw null; }
        public override int GetHashCode() { throw null; }
        public override string ToString() { throw null; }
        public static implicit operator Index(int value) { throw null; }
    }
    public readonly partial struct Range : System.IEquatable<System.Range>
    {
        private readonly int _dummyPrimitive;
        public Index Start { get { throw null; } }
        public Index End { get { throw null; } }
        public override bool Equals(object value) { throw null; }
        public bool Equals(Range other) { throw null; }
        public override int GetHashCode() { throw null; }
        public override string ToString() { throw null; }
        public static Range Create(Index start, Index end) { throw null; }
        public static Range FromStart(Index start) { throw null; }
        public static Range ToEnd(Index end) { throw null; }
        public static Range All() { throw null; }
    }
```

**Comment by AndyAyersMS** [comment]
The `Index` based `Span` indexer is almost certainly going to be a bit slower than the "equivalent" code just passing a raw int, as the jit is not able to remove the redundant tests.
```C#
// "Equivalent" version
public static int GetSimple(Span<int> a, int index)
{
    return a[index < 0 ? a.Length + ~index : index];
}

// Roughly what the Index implementation expands to after inlining
public static int GetSimilar(Span<int> a, int index)
{
    return a[index < 0 ? a.Length - (index < 0 ? ~index : index) : (index < 0 ? ~index : index)];
}

// Actual new usage
public static int GetIndex(Span<int> a, Index i)
{
    return a[i];
}
```
sample asm for "Equivalent" version
```asm
;; GetSimple
G_M19112_IG01:
       sub      rsp, 40
       nop      

G_M19112_IG02:
       mov      rax, rcx
       test     edx, edx
       jl       SHORT G_M19112_IG03
       mov      r8d, edx
       jmp      SHORT G_M19112_IG04

G_M19112_IG03:
       mov      rax, rcx
       mov      r8d, edx
       not      r8d
       add      r8d, dword ptr [rax+8]

G_M19112_IG04:
       cmp      r8d, dword ptr [rax+8]
       jae      SHORT G_M19112_IG06
       mov      rax, bword ptr [rax]
       movsxd   rdx, r8d
       mov      eax, dword ptr [rax+4*rdx]

G_M19112_IG05:
       add      rsp, 40
       ret      

G_M19112_IG06:
       call     CORINFO_HELP_RNGCHKFAIL
       int3     
```
and for the actual `Index` indexer:
```asm
;; GetIndex
G_M1563_IG01:
       sub      rsp, 40
       nop      

G_M1563_IG02:
       mov      eax, edx
       mov      rdx, rcx
       test     eax, eax
       jl       SHORT G_M1563_IG05
       test     eax, eax
       jl       SHORT G_M1563_IG03
       jmp      SHORT G_M1563_IG04

G_M1563_IG03:
       not      eax

G_M1563_IG04:
       jmp      SHORT G_M1563_IG08

G_M1563_IG05:
       mov      ecx, dword ptr [rdx+8]
       test     eax, eax
       jl       SHORT G_M1563_IG06
       mov      r8d, eax
       jmp      SHORT G_M1563_IG07

G_M1563_IG06:
       mov      r8d, eax
       not      r8d

G_M1563_IG07:
       mov      eax, ecx
       sub      eax, r8d

G_M1563_IG08:
       cmp      eax, dword ptr [rdx+8]
       jae      SHORT G_M1563_IG10
       mov      rdx, bword ptr [rdx]
       movsxd   rax, eax
       mov      eax, dword ptr [rdx+4*rax]

G_M1563_IG09:
       add      rsp, 40
       ret      

G_M1563_IG10:
       call     CORINFO_HELP_RNGCHKFAIL
       int3     
```

**Comment by tarekgh** [comment]
I did some basic measurement and  I am seeing the indexer with the index is about 3% slower than the int indexer.  The question is, do we need to do more optimization for that? does the JIT can do better with that?

**Comment by AndyAyersMS** [comment]
I would have guessed you'd see a bit more than 3% based on the above. Even though the redundant branches are going to be highly predictable there is some penalty for taken branches and it gets worse if there are too many of them close together.

The overhead you measure may depend crucially on how you wrote the perf test -- if the `Index` was constructed with constant values and used "nearby" then the jit should be able to get rid of the overhead. But if the index construction is opaque I'd expect to see code similar to the above. Feel free to share out your code.

I haven't drilled in to see why the redundant branches aren't eliminated by the jit. Hopefully it is something simple, but it may not be,

I would expect to see even larger perf impacts from using `Range` (versus say passing around two discrete ints) because of the differences in ABI handling. But again the overhead will depend critically on how the tests are written.

**Comment by tarekgh** [comment]
I just did basic measurements but I am going to do more accurate measurement later. here is the code I used and I have tried to measure only the indexer as possible even excluding the loop overhead and the Indexes array accessing: 

```C#
            ReadOnlySpan<char> span = "This is a span string to test the indexer with".AsSpan();
            Index [] indexes = new Index[span.Length];

            for (int i = 0; i < indexes.Length; i++)
            {
                indexes[i] = new Index(i, fromEnd: false);
            }

            Stopwatch stopWatch = new Stopwatch();

            for (int i = 0; i < 1_000_000; i++)
            for (int j = 0; j < span.Length; j++)
            {
                stopWatch.Start();
                char c = span[j];
                stopWatch.Stop();
            }

            TimeSpan ts = stopWatch.Elapsed;
            Console.WriteLine($"{ts.Hours:00}:{ts.Minutes:00}:{ts.Seconds:00}.{ts.Milliseconds:00} ... {stopWatch.ElapsedTicks}");

            Stopwatch stopWatch1 = new Stopwatch();

            for (int i = 0; i < 1_000_000; i++)
            for (int j = 0; j < span.Length; j++)
            {
                Index ind = indexes[j];
                stopWatch1.Start();
                char c = span[ind];
                stopWatch1.Stop();
            }

            TimeSpan ts1 = stopWatch1.Elapsed;
            Console.WriteLine($"{ts1.Hours:00}:{ts1.Minutes:00}:{ts1.Seconds:00}.{ts1.Milliseconds:00} ... {stopWatch1.ElapsedTicks}");

```

**Comment by AndyAyersMS** [comment]
Here's the kind of numbers I see:
```
  int Indexer: 34.72ms, r is 6032704
equiv Indexer: 51.13ms, r is 6032704
Index Indexer: 80.75ms, r is 6032704
```
here the `equiv` indexer is trying to mimic the inherent extra cost of the from end encoding in the `Index`:
```
span[j < 0 ? span.Length + ~j : j];
```

The jit really should be able to optimize the `equiv` version down to the `int` version as `j` is always non-negative. But it doesn't. The same can't be done for the `Index` version as the value of the index is not known. And since the jit doesn't optimize the check away the `equiv` version gives us an idea of the perf we could get to for the `Index` version, with some work.

So currently overhead is roughly 2.25x with a "best case" around 1.5x. (plus or minus ...?  uncertainty here because we're timing a single loop and so things like loop top alignment can play a big role).

This amount of overhead may seem surprisingly high but modern processors are really good at optimizing simple inner loops like the int indexer case. Once you throw in some branches and more loop body code they don't do nearly as well.

I'm going to investigate why the jit is unable to remove the redundant `< 0` tests in the `Index` case.

**Comment by tarekgh** [comment]
Thanks @AndyAyersMS

> A couple of suggestions: hoist the stopwatch calls since they have a fair bit of overhead and you only care about the aggregate time

What you have suggested is including the array accessing cost which I wanted to avoid when measuring only the index. that is why I had the stop watch around the indexer call only. 

> I'm going to investigate why the jit is unable to remove the redundant < 0 tests in the Index case.

That will be great. do you think in any change in the managed side can help the jit doing better too?

**Comment by AndyAyersMS** [comment]
> What you have suggested is including the array accessing cost which I wanted to avoid when measuring only the index. that is why I had the stop watch around the indexer call only

There is some overhead from the array access, but if anything it is making the `Index` case look better (adding a fixed cost favors the slower alternative). There is also some overhead from the loop iterations. BDN can compensate for the latter timing an empty loop. But starting/stopping stopwatches is costly too, and best done at relatively coarse grain.

I don't see anything yet we can do on the managed side. Exposing a raw value accessor might help if we can't fix the jit, but I don't think you want to do that.

**Comment by AndyAyersMS** [comment]
Looks like it works as I'd hoped, and helps somewhat (~81ms -> ~71ms)
```
  int Indexer: 35.76ms, r is 6032704
equiv Indexer: 59.93ms, r is 6032704   // higher than before, likely loop top impact?
Index Indexer: 71.02ms, r is 6032704   // with revised indexer (see below)
```
Indexer change is:
```diff
         {
             get
             {
-                return ref this [index.FromEnd ? _length - index.Value : index.Value];
+                int x = index.FromEnd ? _length - index.Value : index.Value;
+                return ref this [x];
             }
         }
```

**Comment by tarekgh** [comment]
would it make difference if we don't use this and just use the same implementation of the int indexer? 

https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Span.Fast.cs#L155

would be something like 

```C#
            get
            {
                int x = index.FromEnd ? _length - index.Value : index.Value;
                if ((uint)index >= (uint)_length)
                    ThrowHelper.ThrowIndexOutOfRangeException();
                return ref Unsafe.Add(ref _pointer.Value, index);
            }
```

**Comment by AndyAyersMS** [comment]
I don't think that helps beyond what I did above.

We still end up with 3 tests for `_value < 0`... we need to get that down to just one. And if we get there, we're left with some unavoidable cost for supporting from-end indexing. `Index` is a more general concept that `int` and it is going to be somewhat more costly.

**Comment by AndyAyersMS** [comment]
I think the jit issues are fixable, so we should be able to get the time down a bit further.

**Comment by AndyAyersMS** [comment]
Prospective changes here: [master...AndyAyersMS:ImproveIndexIndexerCQ](https://github.com/dotnet/coreclr/compare/master...AndyAyersMS:ImproveIndexIndexerCQ)

May not get back to finishing this until next week.

Results are now:
```
  int Indexer: 34.59ms, r is 6032704
equiv Indexer: 52.08ms, r is 6032704
Index Indexer: 57.55ms, r is 6032704
```
and yes there is a bit of extra cost in the `Index` case for fetching the index from an array. If I permute the order of the loops and hoist the index fetch out of the inner loop, we get:
```
  int Indexer: 14.22ms, r is 6032704
equiv Indexer: 35.40ms, r is 6032704
Index Indexer: 34.79ms, r is 6032704
```
So with the above we're getting as good a perf as I think we can get.

**Comment by tarekgh** [comment]
cool. no rush anyway so next week would be just fine. the new perf numbers is encouraging. 

Have a good thanks giving!

**Comment by tarekgh** [comment]
Closing this one as the perf tracked with other issue https://github.com/dotnet/coreclr/issues/22079
