### ISSUE TITLE
Packaging build broken in master

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#33389]
Hundreds of errors of the form:
```
D:\j\workspace\windows-TGrou---0d2c9ac4\artifacts\bin\testPkg\packageTest.targets(69,5): error : Assembly 'System.Security.Cryptography.Cng' has insufficient version for dependency 'System.Memory' : 4.1.0.0 < 4.2.0.0. [D:\j\workspace\windows-TGrou---0d2c9ac4\artifacts\bin\testPkg\projects\System.Security.Cryptography.Cng\netcoreapp3.0\project.csproj] [D:\j\workspace\windows-TGrou---0d2c9ac4\pkg\test\testPackages.proj]
D:\j\workspace\windows-TGrou---0d2c9ac4\artifacts\bin\testPkg\packageTest.targets(69,5): error : Assembly 'System.Security.Cryptography.Cng' has insufficient version for dependency 'System.Memory' : 4.1.0.0 < 4.2.0.0. [D:\j\workspace\windows-TGrou---0d2c9ac4\artifacts\bin\testPkg\projects\System.Security.Cryptography.Cng\netcoreapp3.0\project.csproj] [D:\j\workspace\windows-TGrou---0d2c9ac4\pkg\test\testPackages.proj]
```
for multiple assemblies.

cc: @JeremyKuhne, @ericstj

**Comment by JeremyKuhne** [comment]
I have no idea what is going on here. The PR passed all gates and trying to revert the version bump fails CI (#33386).

**Comment by tarekgh** [comment]
could be the test packaging get enabled after your merge? but I can see the problem is you pumped System.Memory version while other packages expect lower version. I don't know how to fix it though.

**Comment by joperezr** [comment]
This is expected. I have merged the ingestion PR of corefx in core-setup, and I queued a new pipe build in order to get new Microsoft.NETCore.App packages with @JeremyKuhne 's change. Once those are available and ingested here the build should go green again.

**Comment by stephentoub** [comment]
@joperezr, do you know why @JeremyKuhne's PR passed CI?  Is it that there were two changes pending that conflicted, Jeremy's and an auto-update PR, and so their CIs ran without the other's changes?

**Comment by joperezr** [comment]
Honestly I'm not sure, I would have expected that change to break the packaging tests, but for whatever reason it didn't break it until after the fact. I was wondering this same thing as after looking at the logic of our failures, we should have gotten a failure directly on his PR. In fact, I synced back to his commit right before merging to master, ran a full build and was able to repro the problem, so not sure why CI didn't catch it.
