### ISSUE TITLE
XmlSerializer skips over <peiority>NORMAL</priority>

### ISSUE THREAD

**Issue by gparlakov** [dotnet/corefx#33398]
When serializing a dotnet type (generated by svcutil) if it contains property priority and the value is NORMAL the xml serializer just skips over it.

Repro here https://github.com/gparlakov/xmlserializer_bug

dotnet --info
.NET Core SDK (reflecting any global.json): Version: 2.1.402 Commit: 3599f217f4

Runtime Environment: OS Name: Windows OS Version: 6.1.7601 OS Platform: Windows RID: win7-x64 Base Path: C:\Program Files\dotnet\sdk\2.1.402\

Host (useful for support): Version: 2.1.4 Commit: 85255dde3e

.NET Core SDKs installed: 1.1.10 [C:\Program Files\dotnet\sdk] 2.1.201 [C:\Program Files\dotnet\sdk] 2.1.202 [C:\Program Files\dotnet\sdk] 2.1.400 [C:\Program Files\dotnet\sdk] 2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed: Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All] Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All] Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App] Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App] Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App] Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App] Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App] Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App] Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App] Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App] Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by mikedn** [comment]
The `priority` property has a `DefaultValueAttribute("NORMAL")` attribute so the serializer skips it when the value is the default one.

**Comment by gparlakov** [comment]
There you go. Did not know that.

Sorry for wasting your time. And thanks.

It seems the issue is that the other side (Java) still expects to see the
property even if being default.

**Comment by gparlakov** [comment]
There you go. Did not know that.

Sorry for wasting your time. And thanks.

It seems the issue is that the other side (Java) still expects to see the property even if being default.
