### ISSUE TITLE
Warning building on Mojave build 10.14 (18A391)

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#33390]
Running `./build.sh`

Result:
```sh
EXEC : warning : Can not determine runtime id for current distro. [/Users/hugh/Documents/GitHub/corefx/src/Native/build-native.proj]
    1 Warning(s)
    0 Error(s)
```

**Comment by danmosemsft** [comment]
@bartonjs do you use Mohave? I'm also surprised if the build machines aren't updated.

**Comment by bartonjs** [comment]
Our build machines are 10.12.

I did build on Mojave yesterday, and that warning seems to ring a bell, but I didn't pay much attention to it since it succeeded in the end (and some of the other builds I had on other machines didn't)

**Comment by karelz** [comment]
cc @wfurt @wtgodbe

**Comment by wfurt** [comment]
I can take a look. I have one Mojave system available for testing.

**Comment by wfurt** [comment]
This warning exists also on 10.13. Since we build OSX as portable, the hostRid does not seems to matter. I'll put together PR to fix it to avoid surprises.
