### ISSUE TITLE
camelCase Resolver not always Default?

### ISSUE THREAD

**Issue by ArgTang** [dotnet/corefx#33408]
# Description

I am trying to create an api call to Slack with a typed `httpClient`. Slack gives a statuscode of `400 ` when formatting with PascalCase.
Although in the documentation it says that .net core is using **Camelcase** as default, my payload is serialized with **PascalCase**, and i manually have to serialize correctly. This feels redundant, I have tried setting `contractresolver` in startup, but it does not help for this.

 ```C#
services.AddMvc(options => options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute()))
                .AddJsonOptions(options => {
                    var settings = options.SerializerSettings;
                    settings.NullValueHandling = NullValueHandling.Ignore;
                    settings.DefaultValueHandling = DefaultValueHandling.Ignore;
                    settings.ContractResolver = new CamelCasePropertyNamesContractResolver();
                })
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
```

The documentation for `PostAsJsonAsync` is as follows:
```C#
        // Remarks:
        //     This method uses a default instance of System.Net.Http.Formatting.JsonMediaTypeFormatter.
        public static Task<HttpResponseMessage> PostAsJsonAsync<T>(this HttpClient client, string requestUri, T value);
```

At first glance it seems good, pick the current apps set `Contractresolver`. But when i breakpoint it seems like it is using `JsonContractResolver` with no `Namingstrategy` set. 
Which makes it understandable why it does **not** serialize with camelcase, but lessens the usefulness of the extentionmethod provided. If this is the case i would ask if it was possible to make an api wich sets the current `SerializerSetting` and posts an object with that.

Is there another method i can use for this?

## system info:
Local runtime 2.1.500-preview-009404
Target Framework: 2.1

## sample
```C#
    public class SlackClient
    {
        private readonly HttpClient _client;

        public SlackClient(HttpClient client, string baseUrl)
        {
            _client = client;
            _client.BaseAddress = baseUrl;
        }

        public async Task<(HttpStatusCode status, string message)> DeliverMessageAsyncWork(SlackMessage payload)
        {
//**************
// I have to manually do it like this, to serialize the object correctly a.k.a as camelCase
//***************
            var settings = new JsonSerializerSettings
            {
                ContractResolver = new CamelCasePropertyNamesContractResolver()
            };
            var camelCaseLoad = JsonConvert.SerializeObject(payload, settings);
            var content = new StringContent(camelCaseLoad, Encoding.UTF8, "application/json");

            var res = await _client.PostAsync("", content);

            if (!res.IsSuccessStatusCode)
            {
                return (res.StatusCode, $"Status: {res.ReasonPhrase}");
            }
            return (status: HttpStatusCode.OK, message: $"Status: {HttpStatusCode.OK}");
        }

        public async Task<(HttpStatusCode status, string message)> DeliverMessageAsyncFail(SlackMessage payload)
        {
// ***********
// This will post object as PascalCase (standard C# obj)
// **************
            var res = await _client.PostAsJsonAsync("", payload);

            if (!res.IsSuccessStatusCode)
            {
                return (res.StatusCode, $"Status: {res.ReasonPhrase}");
            }
            return (status: HttpStatusCode.OK, message: $"Status: {HttpStatusCode.OK}");
        }
    }
```

**Comment by karelz** [comment]
This seems like ASP.NET APIs you're interacting. Can you please clarify what exactly gives wrong output? Do you need to involve HTTP at all? Is it perhaps just serialization part of the code?

**Comment by ArgTang** [comment]
@karelz  as i tried to explain: when using `PostAsJsonAsync` the payload object is Serialized with `JsonContractResolver` and results in a *PascalCase* json httpRequest.

To make my payload serialized correctly with *camelCase* i have to serialize the payload manually
I will update the example to try to clarify

**Comment by karelz** [comment]
Can you demonstrate the problem directly on the Json serialization? That would be IMO helpful.

**Comment by ArgTang** [comment]
I am not sure what you are asking. What in the example is unclear to you? Using `PostAsJsonAsync` will pick an unexpected serializer. i can take a screenshot of a debugsession if that helps

**Comment by karelz** [comment]
No screenshot won't help. I am asking for repro that ideally does not use ASP.NET Core app - it just uses some classes that happen to be in ASP.NET Core.
That will tell us which component is the one with bug, helping us to route the issue appropriately on ASP.NET repos (CoreFX repo is not the right place IMO). Makes sense?

**Comment by khellang** [comment]
Issues related to `PostAsJsonAsync` and `System.Net.Http.Formatting` should be filed in https://github.com/aspnet/AspNetWebStack 😄

**Comment by karelz** [comment]
This issue was moved to aspnet/AspNetWebStack#209

**Comment by ArgTang** [comment]
Thanks for helping me getting to the right place
