### ISSUE TITLE
HttpContentTest.ReadAsStringAsync_SetInvalidCharset_ThrowsInvalidOperationException fails on Linux

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#3343]
Part of PR #3340, this test fails on Linux.  Disabling for now.

System.Net.Http.Functional.Tests.HttpContentTest.ReadAsStringAsync_SetInvalidCharset_ThrowsInvalidOperationException

Stacktrace
MESSAGE:
Assert.Throws() Failure Expected: typeof(System.InvalidOperationException) Actual: (No exception was thrown)
+++++++++++++++++++
STACK TRACE:
--- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Net.Http.Functional.Tests.HttpContentTest.<ReadAsStringAsync_SetInvalidCharset_ThrowsInvalidOperationException>d__bd.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by davidsh** [comment]
This is due to #846... master doesn't yet have a properly implemented GetCodePageFromName method, which is returning UTF8 for unrecognized names rather than throwing (https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Globalization/EncodingTable.Unix.cs#L45-L64)

**Comment by davidsh** [comment]
FYI, it should be fixed once https://github.com/dotnet/coreclr/pull/1645 is checked in.

**Comment by davidsh** [comment]
Just tested this. Even though dotnet/coreclr#1645 is fixed, this test still fails.  Looking at the other dependent issue #846 shows it is still open and waiting for #2774.  But #2774 is marked as closed now.

@ellismg @stephentoub What is the expected next steps for this?

>master doesn't yet have a properly implemented GetCodePageFromName method, which is returning UTF8 for unrecognized names rather than throwing (https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Globalization/EncodingTable.Unix.cs#L45-L64)

Will this get fixed and what issue # is really tracking this?

**Comment by stephentoub** [comment]
@davidsh, just to verify, you tested it by pulling the latest coreclr sources, rebuilding the Linux libcoreclr and mscorlib, and using those bits?  Or you submitted a PR that re-enabled the test?  Or something else?

**Comment by davidsh** [comment]
I submitted a private PR in Jenkins that re-enabled the test.  And the build failed.
http://dotnet-ci.cloudapp.net/view/PR%20and%20Private%20Jobs/job/dotnet_corefx_prtest/5016/

**Comment by stephentoub** [comment]
Looking at your job, I think it picked up a build from yesterday morning before Eric's change was merged.  I just tried running it locally with the test re-enabled and with my libcoreclr/mscorlib up-to-date, and all 252 tests passed.

**Comment by davidsh** [comment]
So, when will Eric's change be reflected on the CI servers?

**Comment by stephentoub** [comment]
@mmitche, do you know what the current set up is around which libcoreclr build we pick up in corefx?

**Comment by davidsh** [comment]
@mmitche - PING

>@mmitche, do you know what the current set up is around which libcoreclr build we pick up in corefx?

**Comment by mmitche** [comment]
Sorry, we pick up the latest release build for the corefx testing (assuming that's what you mean)

**Comment by davidsh** [comment]
So, I still don't understand why this is still broken.  This issue is depending on #846.  But I don't think that dependent issue is still fixed yet.

**Comment by stephentoub** [comment]
The issue had been that we were pulling the latest build from an old coreclr build definition; Matt had revamped how CIs happened in coreclr, but we hadn't updated where we were pulling coreclr builds from, and thus we were pulling the latest from a feed that hadn't been updated in a while.  Matt fix that over the weekend I believe.  I just tried this test and it appears to be passing fine.

**Comment by davidsh** [comment]
Ok.  Great!  Then we can submit a PR to re-enable the test?

**Comment by stephentoub** [comment]
We should be able to, yes. If it still fails, we can dig in again to see why.

**Comment by davidsh** [comment]
@stephentoub I just submitted PR #3827.  But the CI system isn't kicking in with the test build.  Very strange.

**Comment by stephentoub** [comment]
Thanks for submitting that, David.  I believe @mmitche is already investigating the CI issue; he mentioned to me earlier this evening that it was experiencing some failures.

**Comment by mmitche** [comment]
@davidsh I am working on it.  There was a change made in the roslyn CI definition that screwed things up.
