### ISSUE TITLE
System.Drawing.Font should be [Serializable]

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#33437]
It was explicitly called out in https://github.com/dotnet/corefx/issues/30183, but then wasn't done in https://github.com/dotnet/corefx/pull/30817, which closed that issue.  This shows up as a key type in Windows Forms .resx files.

**Comment by ViktorHofer** [comment]
I don't see any reason why not, it depends on enums only: https://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/Advanced/Font.cs,130

I should be able to send a PR for it by EOD if all agree on doing so.

cc @danmosemsft @ericstj

**Comment by stephentoub** [comment]
Thanks, @ViktorHofer.
