### ISSUE TITLE
Inconsistent null checks in Array.Copy

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#33430]
```c#
        public static void Copy(Array sourceArray, Array destinationArray, int length)
        {
            if (sourceArray == null)
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.sourceArray);
            if (destinationArray == null)
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.destinationArray);

            Copy(sourceArray, sourceArray.GetLowerBound(0), destinationArray, destinationArray.GetLowerBound(0), length, false);
        }

        public static void Copy(Array sourceArray, int sourceIndex, Array destinationArray, int destinationIndex, int length)
        {
            Copy(sourceArray, sourceIndex, destinationArray, destinationIndex, length, false);
        }

        [MethodImplAttribute(MethodImplOptions.InternalCall)]
        internal static extern void Copy(Array sourceArray, int sourceIndex, Array destinationArray, int destinationIndex, int length, bool reliable);
```

If I call the 3 param overload with a null array I get a message pointing to the bad argument. If I call the 5 param overload I get the runtime message `System.ArgumentNullException: 'Value cannot be null.'`.

I guess I don't care much about this. It's nice I can call the 5 param overload if I want to avoid the extra null checks.

**Comment by stephentoub** [comment]
> It's nice I can call the 5 param overload if I want to avoid the extra null checks.

And the relatively expensive .GetLowerBound(0) calls, which is why we consistently avoid using the 3-arg overload in corefx when we know the inputs are T[].

**Comment by ahsonkhan** [comment]
> which is why we consistently avoid using the 3-arg overload in corefx when we know the inputs are T[].

Yep, for example in [BitArray](https://github.com/dotnet/corefx/blob/5aab1d3ff4ae362d62bde705dd30b4404228ee15/src/System.Collections/src/System/Collections/BitArray.cs#L159).

**Comment by danmosemsft** [comment]
Alright seems like this is OK as is.
