### ISSUE TITLE
Several types in S.Security.Claims are not ported and have usage

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#33440]
Top of the list are these types
```
T:System.Security.Claims.ClaimsAuthorizationManager
T:System.Security.Claims.AuthorizationContext
T:System.Security.Claims.ClaimsAuthenticationManager
```
Usage is under 1% except that one of our porting partners is using ClaimsAuthorizationManager.

**Comment by jkotas** [comment]
This is WCF. It does not belong to CoreFX.

**Comment by danmosemsft** [comment]
Ah, identity model.

**Comment by danmosemsft** [comment]
This issue was moved to dotnet/wcf#3319
