### ISSUE TITLE
Extra runtime directory & missing ConfigurationGroup from bin and obj directories.

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#33465]
@ViktorHofer noticed we're producing 2 runtime directories.

Eg: 
```
artifacts\bin\runtime\netcoreapp-Windows_NT
artifacts\bin\runtime\netcoreapp-Windows_NT-Debug-x64
```

This is most likely an issue with runtime.depproj

EDIT by @ViktorHofer: example was missing the OSGroup in the first line. Also changed to netcoreapp to give it a higher severity ;)

**Comment by ViktorHofer** [comment]
cc @safern @weshaggard

**Comment by ericstj** [comment]
Just to confirm, this isn't breaking anything just an observation of extra output directory?

**Comment by ViktorHofer** [comment]
Right, the files are just duplicated across both directory therefore nothing is broken.

**Comment by ViktorHofer** [comment]
> Previously we had BuildConfiguration in our TargetPath (bin\<buildConfiguration><projectName>\<projectConfiguration>) with the latest we don't have this (artifacts\bin\<projectName>\<projectConfiguration>)

I thought that was intentional and didn't comment on it. The omission of debug/release indicates that it probably was unintentional.

**Comment by weshaggard** [comment]
We didn't have BuildConfiguration exactly we had OSPlatformConfig which included a number of the same things. When I switch I tried to use what was set in arcade https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/ProjectLayout.props#L18 as we already set the Configuration I started depending on that but I overlooked the fact that we don't have ConfigurationGroup included in that when we do this. 

I'd suggest we consider starting to encode ConfigurationGroup when we set the Configuration property that we are building. So add it https://github.com/dotnet/corefx/blob/master/eng/buildvertical.targets#L97 and https://github.com/dotnet/corefx/blob/master/eng/buildvertical.targets#L179. We would also need to add it here wherever we do our BuildAll targets like. https://github.com/dotnet/corefx/blob/master/eng/buildvertical.targets#L97.

**Comment by ericstj** [comment]
I noticed we also are building with different configuration strings for direct project build vs traversal build.

I had a slightly different idea for the fix here: https://github.com/dotnet/arcade/issues/1434

Essentially always standardize the Configuration string in the props files after we rip it apart.

**Comment by ericstj** [comment]
My tactical change for this introduced race conditions during the release builds.  Reopening this as I undid part of the fix.

Note the part that had runtime clashing with the runtime dir is still in, I've only undid the portion that ensured ConfigurationGroup unique paths.

**Comment by ViktorHofer** [comment]
OK, that's unfortunate. Do you already have a plan how to workaround the race condition?

**Comment by ericstj** [comment]
I undid the change so the race condition is gone.  At the moment lacking ConfigurationGroup from the output paths isn't a blocking problem.  If I had a choice rather than to invest more into the Configuration-encoding path I'd like to pursue the TargetFrameworks solution which avoids this problem entirely.

FWIW I left in the portion of the fix that avoids the collision between runtime path and the runtime.depproj so the original issue is fixed, just not the other issue I [noticed](https://github.com/dotnet/corefx/issues/33465#issuecomment-438382507).

**Comment by stephentoub** [comment]
cc: @alexperovich, @danmosemsft, @KirillOsenkov 

Do we have any further idea how to address this?  It's breaking source.dot.net.  I believe @KirillOsenkov has some ideas for hacks he could use to workaround this, but I'm not sure how robust those are.

**Comment by ericstj** [comment]
A [few](https://github.com/dotnet/corefx/issues/33465#issuecomment-438779410) [ideas](https://github.com/dotnet/arcade/issues/1434#issue-387047832) all of which are messy / ugly.  Just need to pick the least ugly one.

**Comment by ericstj** [comment]
I'm working on a fix for this in arcade and will submit shortly.
