### ISSUE TITLE
Problem with PropertyInfo.GetValue - Error in Exception treatment?

### ISSUE THREAD

**Issue by YetiAnt** [dotnet/corefx#33485]
The code below works properly, when I use .net 3.0 or 3.5. With .net 4.0 or higher it seems to be impossible to catch an exception, that occurs inside the code, that is performed by GetValue.

Explanation:
The loop in the main program runs over the properties of the given class and displays them using the method ShowProp.

This works fine under all frameworks from 3.0 up to 4.7.2 with the property WorkingFineProp.

But retrieving of property ThrowExceptionProp throws an exception.
See line X1: `throw new Exception("I don't like mondays!"); // X1`

This exception interrupts performing in the calling method for this property.
See Line X2: `V = aPropertyInfo.GetValue(aObject,null).ToString(); // X2`

In this case the occurred exception text should be displayed instead of the value.
See line X3: `catch (Exception E) { V = E.Message; } // X3`

This works as described under .net 3.0 and 3.5 but fails under 4.0, 4.5, 4.5.1, 4.5.2, 4.6, 4.6.1 and 4.7.2. 

Is there any option to bring back the old – in my eyes correct – Behavior?

Best wishes and many thanks for reading 

Yeti 

C# Code:
```c#
using System;
using System.Collections.Generic;
using System.Reflection;
using System.Text;

namespace PropGetValTest
{
  class Program
  {
    class PropProvider {
      public string WorkingFineProp { get { return "WorkingFine"; } }
      public object ThrowExceptionProp
      {
        get {
          throw new Exception("I don't like mondays!"); // X1
        }
      }
    }


    private static void ShowProp (object aObject, PropertyInfo aPropertyInfo)
    {
      string N, V;
      N = aPropertyInfo.Name;
      try {
        V = aPropertyInfo.GetValue(aObject,null).ToString(); // X2
      }
      catch (Exception E) { V = E.Message; } // X3
      Console.WriteLine("{0}: {1}", N, V); 
    }

    static void Main (string[] args)
    {
      PropProvider TheClass  = new PropProvider();
      foreach (PropertyInfo P in TheClass.GetType().GetProperties())
        ShowProp(TheClass, P);
      Console.ReadLine();
    }

  }
}
```
[Program.cs.txt](https://github.com/dotnet/corefx/files/2581389/Program.cs.txt)

**Comment by joshfree** [comment]
@steveharter could you take a look?

**Comment by steveharter** [comment]
@YetiAnt I was not able to repro - I always get the exception in .NET Framework 4.7.2 and other versions I tried. Tried both Debug and Release builds. Also fwiw I was not able to repro in CoreClr (3.0 preview and 2.2 tested).

Are you using a standard console app project?

What do you get back as the property value of `ThrowExceptionProp`? My results were always:
```
WorkingFineProp: WorkingFine
ThrowExceptionProp: Exception has been thrown by the target of an invocation.
```

**Comment by joshfree** [comment]
Marking the bug with `needs more info` and closing.  @YetiAnt feel free to reactivate with more info that @steveharter requested.  Thank you.
