### ISSUE TITLE
DirectoryInfo.MoveTo does not update the object's Name property

### ISSUE THREAD

**Issue by alexischr** [dotnet/corefx#33490]
The following program prints `DIT.MoveToUpdateProperties.Test` (the original Name) on CoreFX, and `DIT.MoveToUpdateProperties3.Test` (the final Name) on .NET Framework and Mono:

```
using System;
using System.IO;

namespace MoveTo_UpdateProperties
{
	class Program
	{
		static void Main(string[] args)
		{
			string TempFolder = Path.GetTempPath();
			char DSC = Path.DirectorySeparatorChar;
			string path = TempFolder + DSC + "DIT.MoveToUpdateProperties.Test";
			string path2 = TempFolder + DSC + "DIT.MoveToUpdateProperties2.Test";
			string path3 = path2 + DSC + "DIT.MoveToUpdateProperties3.Test";
			if (Directory.Exists (path2))
				Directory.Delete (path2);
			if (Directory.Exists (path))
				Directory.Delete (path);
			Directory.CreateDirectory (path);
			Directory.CreateDirectory (path2);

			DirectoryInfo info = new DirectoryInfo(path);
			info.MoveTo (path3);
			Console.WriteLine (info.Name);
		}
	}
}

```

The issue in the code is here (`_name` is not updated): https://github.com/dotnet/corefx/blob/8bd31a2a571923d3eb86dc728c272d0b6093a4d2/src/System.IO.FileSystem/src/System/IO/DirectoryInfo.cs#L228

Using `fileName: null` instead fixes the issue.

**Comment by danmosemsft** [comment]
Thanks @alexischr 	- do you plan to offer a PR?

**Comment by alexischr** [comment]
Will do, just wanted to get an okay on the fix :)
