### ISSUE TITLE
Utf8Formatter does not allow you to specify a precision specifier with the 'G' format

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#33502]
As per https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Buffers/Text/Utf8Formatter/Utf8Formatter.Float.cs#L80 and https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=Argument_GWithPrecisionNotSupported&type=, the Utf8Formatter currently throws if you attempt to use a precision specifier with the general format (such as "G17").

This can lead to unexpected/undesired behavior when trying to format a double/single into a string that is guaranteed to roundtrip.

**Comment by ahsonkhan** [comment]
Updating link to match the commit hash: https://github.com/dotnet/corefx/blob/2482825f0afee4b241619d8f2de6a701477425c0/src/Common/src/CoreLib/System/Buffers/Text/Utf8Formatter/Utf8Formatter.Float.cs#L80

**Comment by tannergooding** [comment]
I'm pretty sure I fixed this already...

**Comment by tannergooding** [comment]
Yep, I resolved this with https://github.com/dotnet/coreclr/pull/22434 and added tests covering this in https://github.com/dotnet/corefx/pull/35567

**Comment by ahsonkhan** [comment]
> added tests covering this in https://github.com/dotnet/corefx/pull/35567

I see tests for  G, G4, G20, but not G17.

**Comment by tannergooding** [comment]
I don't think we need tests for every single digit count. We are just passing the underlying precision to the UTF16 formatter and the numbers picked show that it works as expected (and I would say similar even if it wasn't pass-through).

**Comment by ahsonkhan** [comment]
> I don't think we need tests for every single digit count. 

That's fair. The only reason I asked is because you mentioned G17 in the original issue, particularly around roundtrip. Thanks.
