### ISSUE TITLE
CoreFX Perf runs are timing out

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/corefx#33524]
Currently, the CoreFX perf runs are taking over 6 hours to run and are timing out as a result. I did some brief investigating and we currently run all tests twice, once with ETL tracing and one without. That along with the number of tests we are executing is putting us in this spot.

cc: @danmosemsft @brianrob @billwert 

https://ci2.dot.net/job/dotnet_corefx/job/perf/job/master/job/perf_windows_nt_release/7292/

**Comment by adamsitnik** [comment]
I suspect that somebody added a perf test with hundreds of test cases ;) Will take a look at this tomorrow

**Comment by DrewScoggins** [comment]
If all else fails we should be able to bump up the timeout, but it really seems like we should be able to do a run in under six hours ;)

**Comment by brianrob** [comment]
Thanks much.

**Comment by adamsitnik** [comment]
It looks like we just have a LOT of benchmarks. I am not going to investigate this issue now because I expect us to switch to the performance repo and BenchmarkDotNet in next few weeks. In the perf repo, I have removed a lot of test cases for some benchmarks that had **hundreds** of test cases. I just don't want to duplicate the effort. @brianrob @billwert is that ok?

**Comment by ViktorHofer** [comment]
I now understand the issue described here better. The perf that are finally working again runs for about 5h 50min to 6h 5min. Everything above 6h times out. We have various options here:

1) Leave it as it is (50% of the builds still succeed). Further infra work that I currently do should help here as it allows building much faster which should bring us down to ~5h 30m.
2) Migrate this job to Azure DevOps (cc @safern)
3) Stop these runs entirely. I wouldn't take this option till we have solid continuous perf data from the performance repo. We probably want to leave it as it is until we shutdown Jenkins or .NET Core 3 has been released.

**Comment by wtgodbe** [comment]
@ViktorHofer @safern what's the latest on these jobs? Are we still planning to migrate them to AzDO?

**Comment by safern** [comment]
I think they still need to be migrated to AzDO -- but I don't understand the full story yet. @adamsitnik I think @adiaaida told me yesterday you might do this work?

**Comment by ViktorHofer** [comment]
I think we can close this issue. AFAIK we won't run perf tests anymore from inside corefx as part of CI
