### ISSUE TITLE
Sugestion: Span<T>.Intersect(Span<T> other)

### ISSUE THREAD

**Issue by Mirandatz** [dotnet/corefx#33523]
I wish there was an elegant solution to [this problem](https://stackoverflow.com/questions/51941177/how-can-i-check-if-two-spant-intersect).

Basically, when writing methods like: 
```
public static bool TryToDoStuff(ReadOnlySpan<byte> input, Span<byte> destination) {
    ...
}
```

I'd like to check if the memory regions "wrapped" by input and destination intersect, and if so, throw an exception, since this would corrupt input's data. Currently, I think, there is no concise, safe and elegant way to do so.

I'd like to have some ```Intersect```method that returns true iff 2 spans 'memory regions' intersect, e.g.:

```
// On arrays
Span<byte> firstArray = new byte[10];
Span<byte> secondArray = new byte[10];
Intersects<byte>(firstArray.Slice(5, 5), firstArray.Slice(3, 5)); // Returns true
Intersects<byte>(firstArray.Slice(5, 5), secondArray.Slice(3, 5)); // Returns false

// And on stackallocated memory
Span<byte> firstStack = stackalloc byte[10];
Span<byte> secondStack = stackalloc byte[10];
Intersects<byte>(firstStack.Slice(5, 5), firstStack.Slice(3, 5)); // Should return true
Intersects<byte>(firstStack.Slice(5, 5), secondStack.Slice(3, 5)); // Should return false
```

**Comment by stephentoub** [comment]
> I'd like to have some Intersectmethod that returns true iff 2 spans 'memory regions' intersect

https://apisof.net/catalog/System.MemoryExtensions.Overlaps%3CT%3E(ReadOnlySpan%3CT%3E,ReadOnlySpan%3CT%3E)
