### ISSUE TITLE
Cleaning up ETL sessions

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/corefx#33535]
On lab machines during CoreFX runs we will occasionally start to see errors like this. I investigated this and the problem is that the System process is still holding a handle to an ETL file in that workspace. When we then try to delete the workspace we can't because that handle prevents deletion. We need to do a better job of cleaning up our ETL sessions. Since test crashes and timeouts are mostly what cause this we should probably handle this issue at the run level and not the harness level.

@billwert @brianrob 

```ERROR: [WS-CLEANUP] Cannot delete workspace: remote file operation failed: C:\J\w\perf_windows_---356c2fc4 at hudson.remoting.Channel@7fecbfe2:JNLP4-connect connection from 131.107.147.138/131.107.147.138:5616: java.io.IOException: Unable to delete 'C:\J\w\perf_windows_---356c2fc4\artifacts\bin\tests\System.Text.Encoding.Performance.Tests\netcoreapp-Windows_NT-Release-x64'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.```

**Comment by adamsitnik** [comment]
Please keep in mind that we are soon going to switch from xunit-performance to BenchmarkDotNet so spending a lot of time to investigate this issue might be not a good idea.

**Comment by maririos** [comment]
@DrewScoggins this doesn't sound like a CoreFx issue. If it is related to infra, then it should go to core-eng.

**Comment by DrewScoggins** [comment]
Sure. We are seeing the problem only manifest here because of the long runtimes, but it is certainly a infrastructure issue. I will just copy the issue over to core-eng

**Comment by DrewScoggins** [comment]
Issue moved to [dotnet/core-eng #4711](https://github.com/dotnet/core-eng/issues/4711) via [**ZenHub**](https://www.zenhub.com/)
