### ISSUE TITLE
ColorConverterCommon.cs is a really weird file

### ISSUE THREAD

**Issue by zeromus** [dotnet/corefx#33541]
This file is really weird

https://github.com/dotnet/corefx/blob/master/src/System.Drawing.Common/src/System/Drawing/ColorConverterCommon.cs

It's really small so I'll paste the whole thing here. None of it makes any sense.

```
namespace System.Drawing.System.Drawing
{
    internal static class ColorConverterCommon
    {
        public static Color ConvertFromString(string colorString)
        {

        }
    }
}
```

**Comment by stephentoub** [comment]
This file isn't used by anything; it was erroneously checked in and can be deleted.
