### ISSUE TITLE
RSA.TryDecrypt fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by ycrumeyrolle** [dotnet/corefx#33561]
```c#
    public class RsaTryDecryptTests
    {
        [Fact]
        public void TryDecrypt()
        {
            var data = new byte[128];
            RandomNumberGenerator.Fill(data);

            var paddingMode = RSAEncryptionPadding.OaepSHA256;
            using (var rsa = RSA.Create())
            {
                rsa.KeySize = 2048;
                var encryptedData = rsa.Encrypt(data, paddingMode);

                var decryptedData = rsa.Decrypt(encryptedData, paddingMode);
                Assert.Equal(data, decryptedData);

                var tryDecryptedData = new byte[128];
                var decrypted = rsa.TryDecrypt(encryptedData, tryDecryptedData, paddingMode, out int bytesWritten);
                Assert.True(decrypted);
                Assert.Equal(data, tryDecryptedData);
                Assert.Equal(tryDecryptedData.Length, bytesWritten);
            }
        }
    }
```

This test is working fine on my Windows CI host, but is failing on the Ubuntu CI host.
The TryDecrypt() method return false, since the Decrypt() method is able to decrypt.

**Comment by stephentoub** [comment]
What happens if you change `var tryDecryptedData = new byte[128]` to be something larger?

**Comment by ycrumeyrolle** [comment]
This is working at 256, failing bellow.

**Comment by bartonjs** [comment]
Yeah, OpenSSL only accepts a "where would you like me to start writing" pointer, and writes however much it does; so to be safe we require the keysize (technically the safe upper limit is a little lower, depending on the padding type).

We could relax that limit if we wanted to decrypt into a temporary buffer then do a conditional copy; but for best results just pass in a keysized buffer, as that will always return true or throw.

**Comment by bartonjs** [comment]
Since Windows allows "smaller than needed, but at least as big as necessary" it makes sense to do it for Linux (and macOS), too.

On Linux, if the provided buffer is too small we'll just stackalloc (4096-bit or smaller) or rent-use-and-clear (bigger) a temporary buffer and pay the copy cost.
