### ISSUE TITLE
System.Net.* tests failing on dependencies update in coreclr

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#33587]
Several CoreFx tests failing in coreclr: https://github.com/dotnet/coreclr/pull/21045

- System.Net.Primitives.Functional.Tests.IPAddressMappingTest.IPAddressMapping_MapIPv4ToIPv6_Success
- System.Net.Primitives.Functional.Tests.IPAddressMappingTest.IPAddressMapping_MapIPv6ToIPv4_Success
- System.Net.Sockets.Tests.KeepAliveTest.Socket_Set_KeepAlive_Interval_Failure
- System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteBeginGetHostByName_IPv4String_ReturnsOnlyGivenIP
- System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteGetHostByName_LocalHost_ReturnsLoopback
- System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteGetHostByName_IPv4String_ReturnsOnlyGivenIP
- System.Net.NameResolution.Tests.GetHostAddressesTest.DnsGetHostAddresses_IPv4String_ReturnsSameIP

https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_corefx_innerloop_prtest/4698/testReport/junit/System.Net.NameResolution.Tests/GetHostAddressesTest/DnsGetHostAddresses_IPv4String_ReturnsSameIP/

```text
Stacktrace
MESSAGE:
Assert.Equal() Failure\r\nExpected: 127.0.0.1 (System.Net.IPAddress+ReadOnlyIPAddress)\r\nActual: 127.0.0.1 (System.Net.IPAddress)
+++++++++++++++++++
STACK TRACE:
at System.Net.NameResolution.Tests.GetHostAddressesTest.DnsGetHostAddresses_IPv4String_ReturnsSameIP() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.NameResolution\tests\FunctionalTests\GetHostAddressesTest.cs:line 102
```

https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_corefx_innerloop_prtest/4698/testReport/junit/System.Net.Sockets.Tests/KeepAliveTest/Socket_Set_KeepAlive_Interval_Failure/
```text
Stacktrace
MESSAGE:
Assert.Throws() Failure\r\nExpected: typeof(System.Net.Sockets.SocketException)\r\nActual: (No exception was thrown)
+++++++++++++++++++
STACK TRACE:
at System.Net.Sockets.Tests.KeepAliveTest.Socket_Set_KeepAlive_Interval_Failure() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Net.Sockets\tests\FunctionalTests\KeepAliveTest.netcoreapp.cs:line 92
```

Recent changes to Sytem.Net.NameResolution: https://github.com/dotnet/corefx/commits/master/src/System.Net.NameResolution

cc @davidsh, @wfurt, @stephentoub

**Comment by jkotas** [comment]
This is caused by old version of XUnit in CoreCLR that has different implementation of Assert.Equal. I will try to update it to the same version as CoreFX.
