### ISSUE TITLE
Does FileInfo.Length always return the actual filelength of a file

### ISSUE THREAD

**Issue by rahuldutta90** [dotnet/corefx#33582]
I have a library targetting netcoreapp1.1. I have this code snippet:

```c#
DirectoryInfo dir = new DirectoryInfo(SourcePath);
IEnumerable<FileInfo> enumFiles = dir.EnumerateFiles();
foreach (var file in enumFiles)
{
    Use file.length
}
```

Is it possible for the file.length to be returned 0 for files with sizes ranging from 4MB to 70MB?

**Comment by danmosemsft** [comment]
Hello @rahuldutta90 it should be accurate. In what circumstances are you seeing it return nonzero for a file with nonzero size?

**Comment by rahuldutta90** [comment]
@danmosemsft I will get back to you regarding this. I have asked the customer to get back with logs to confirm this.

**Comment by danmosemsft** [comment]
OK thanks bear in mind we would need to know (1) what version of .NET Core they are running on (2) what OS/distro (3) other info necessary to repro.

**Comment by rahuldutta90** [comment]
@danmosemsft  I was wrong. The issue was different. I will close the issue. Thank you.
