### ISSUE TITLE
SslStream.AuthenticateAsServer losing private key on Linux

### ISSUE THREAD

**Issue by martin-frydl** [dotnet/corefx#33590]
I invoke SslStream.AuthenticateAsServer() with my own subclass of X509Certificate2. It is correctly initialized to contain both certificate and private key and is exportable. However, the application fails with following exception:
```
System.NotSupportedException: The server mode SSL must use a certificate with the associated private key.
   at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint, Byte[] clientHello)
   at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.AuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions)
   at System.Net.Security.SslStream.AuthenticateAsServer(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
```
I traced the code down and found the problem in System.Net.Security.SecureChannel.MakeEx() where the certificate is re-created using handle if not exactly X509Certificate2 (https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/src/System/Net/Security/SecureChannel.cs#L283):
```csharp
            if (certificate.GetType() == typeof(X509Certificate2))
            {
                return (X509Certificate2)certificate;
            }

            X509Certificate2 certificateEx = null;
            try
            {
                if (certificate.Handle != IntPtr.Zero)
                {
                    certificateEx = new X509Certificate2(certificate.Handle); // <<<------
                }
            }
```
The problem is with that copying - it does not work on Linux. Following example demonstrates the copying. It prints true and false on Linux (i.e. private key is present in loaded certificate but not in "copy"). On Windows it works fine (prints "true" twice).
```csharp
X509Certificate2 serverCertificate = new X509Certificate2(certFilePath, password, X509KeyStorageFlags.Exportable);
Console.WriteLine(serverCertificate.HasPrivateKey);
X509Certificate2 serverCertificate2 = new X509Certificate2(serverCertificate.Handle);
Console.WriteLine(serverCertificate2.HasPrivateKey);
```

**Comment by bartonjs** [comment]
@vcsjones  That would only work if the derived type let the X509Certificate2 class open the certificate (thus knew how the private key worked).  If the derived type was trying to do something else then that would `NullReferenceException`, since a derived type can't have populated cert.Pal.

Essentially, subclassing X509Certificate/X509Certificate2 isn't supported (by crypto or networking), and anything that does work is a happy accident.

The easiest workaround would be

```C#
var usableCertObject = new X509Certificate2(cert3.Export(X509ContentType.Pkcs12));
```

**Comment by vcsjones** [comment]
>cert3.Export(X509ContentType.Pkcs12)

Hm. That only works too if the private key is exportable at all (e.g. isn't in a KSP that is non-exportable or HSM), correct?

**Comment by martin-frydl** [comment]
It does works when I "copy" the certificate to new instance using "new X509Certificate2(oldCert)" but the behavior is strange:

- Works on Windows, does not work on Linux. It worked on .NET Framework too and API  has not changed so it is impossible to detect such change at compile time.
- What is the reason to rule our user subclasses? And if so, why is X509Certificate2 not sealed? Probably because it itself inherits from X509Certificate and that should be sealed too which is impossible.

**Comment by bartonjs** [comment]
> What is the reason to rule our user subclasses?

In networking, in particular, it's because the underlying system (SChannel on Windows, OpenSSL on Linux, SecureTransport on macOS) has only one interpretation of a certificate that it understands.  Windows wants a PCCERT_CONTEXT (cert.Handle), OpenSSL wants an X509\* (cert.Handle) and EVP_PKEY\* (tracked by the cert PAL), SecureTransport wants a SecIdentityRef (cert.Handle).

If some other implementation of X509Certificate were to be used, it can't make the assurances that the cert.Handle value is meaningful, and passing unknown pointers is a good way to destroy a process.

> Probably because it itself inherits from X509Certificate and that should be sealed too which is impossible.

As far as I know, yeah :smile:.

**Comment by davidsh** [comment]
>I invoke SslStream.AuthenticateAsServer() with my own subclass of X509Certificate2.

>Essentially, subclassing X509Certificate/X509Certificate2 isn't supported (by crypto or networking), and anything that does work is a happy accident.

It sounds like this scenario is not supported.  So, I'll close this issue.
