### ISSUE TITLE
ZipArchiveEntry.CopyToAsync sometimes throws InvalidDataException

### ISSUE THREAD

**Issue by theAshenfire** [dotnet/corefx#33596]
### Short Description

I am running a micro-service locally. one of its endpoints receives a zip file in the request and analyzes each of its entries. Due to several reasons i need to copy the contents of each entry's stream to memory, which i release once its use is done.
The problem is once every random number of tries calls to ZipArchiveEntry.CopyToAsync throws InvalidDataException.

### Exception stack trace
```
System.IO.InvalidDataException: The archive entry was compressed using an unsupported compression method.
   at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.DeflateStream.CopyToAsyncStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.IO.Compression.DeflateStream.CopyToAsyncStream.CopyFromSourceToDestination()
   at <My Code stack trace>
```

### Some code sample

```c#
			var stream = new MemoryStream();
			await _file.CopyToAsync(stream); // file from asp.net core

			stream.Position = 0;
			using (var archive = new ZipArchive(stream))
			{
			var tasks = archive.Entries.Select(entry =>
			{
				MemoryStream target = new MemoryStream()
				using (var entryStream = entry.Open())
					await entryStream.CopyToAsync(target);
				// .... Some more processing here ....
			});
			var results = Task.WhenAll(tasks);

```
### Additional Notes

- At first i was sure it's data being dropped in the transfer. However i checked and the contents of the zip stream are always the same, even when the exception is thrown.
- The Exception is thrown randomly every few attempts, without any pattern i can see.
- I added a "retry" mechanism (a.k.a re-run the exact same code with same values until several failures) and it seems that the 2nd run is always successful.

Any help on this matter would be greatly appreciated!

**Comment by MarcoRossignoli** [comment]
I did some tests...`ZipArchive` seems not safe for concurrency(usually by design), I get same exception with:
```
Parallel.ForEach(archive.Entries, async entry =>
{
    MemoryStream target = new MemoryStream();
    using (Stream entryStream = entry.Open())
    {
        await entryStream.CopyToAsync(target);
    }
});
```
The issue with your code seems related to how `await Task.WhenAll(tasks);` works, if you await task one by one it works(my test is a console app, so first assertion, because we enqueue with main thread that is not a thread pool thread):
```
using (ZipArchive archive = new ZipArchive(ms))
{
    IEnumerable<Task> tasks = archive.Entries.Select(async entry =>
    {
        Debug.Assert(System.Threading.Thread.CurrentThread.IsThreadPoolThread == false);
        MemoryStream target = new MemoryStream();
        using (Stream entryStream = entry.Open())
        {
            await entryStream.CopyToAsync(target);
        }
        Debug.Assert(System.Threading.Thread.CurrentThread.IsThreadPoolThread);
    });

    await Task.WhenAll(tasks);

    // This works because task runs one by one
    //foreach (Task item in tasks)
    //{
    //    Debug.Assert(item.Status == TaskStatus.WaitingForActivation);
    //    Debug.Assert(item.IsCompleted == false);
    //    await item;
    //}
}
```
`Task.WhenAll` enqueue your task to ThreadPool and tasks goes in parallel on `ZipArchive`
Hovewer to me it's unuseful await on non IO bound resource, I mean you already load file on ram with `await _file.CopyToAsync(stream);`(true IO bound resource, Stream should come from network) after that you can decompress with sync api, you'are consuming only computations resources(CPU for decompression), if you try something like this:
```
    using (ZipArchive archive = new ZipArchive(ms))
    {
        Array.ForEach(archive.Entries.ToArray(), entry =>
        {
            MemoryStream target = new MemoryStream();
            using (Stream entryStream = entry.Open())
            {
                entryStream.CopyTo(target);
            }
            // do work
        });
    }
```
@stephentoub will confirm my suspect or will tell us the truth :smiley:

**Comment by stephentoub** [comment]
> @stephentoub will confirm my suspect or will tell us the truth

Yup, it's not safe for concurrent use like this.

**Comment by fume** [comment]
Any chance to have a better Exception message? The actual one is of course misleading...

thanks, regards

**Comment by MarcoRossignoli** [comment]
@fume understand if issue is related to corrupted state due to concurrency is very hard if not impossible sometimes(in my experience)...for this reason usually on doc you found "access in non thread safe manner could lead to undefined behaviour" too much possible states.

**Comment by fume** [comment]
thanks @MarcoRossignoli for the fast answer, but the documentation for ZipArchiveEntry doesn't state anything about thread-safety :)

https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.ziparchiveentry?view=netcore-2.2#remarks

**Comment by MarcoRossignoli** [comment]
By design every "instance" method is non thread safe if not documented, only static one

https://docs.microsoft.com/en-us/dotnet/standard/threading/managed-threading-best-practices#recommendations-for-class-libraries
```
Do not make instance data thread safe by default.
```
