### ISSUE TITLE
Obsolete string.Copy(string) method

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/corefx#33602]
This is the API review for https://github.com/dotnet/corefx/issues/32563.

```cs
namespace System
{
    public sealed partial class String
    {
        // new attribute, obsolete as warning (not error)
        // method implementation stays as-is for now
        [Obsolete("String instances are intended to be immutable. To make a mutable buffer with the same contents as a string, use the method string.ToCharArray(). To create a mutable copy of the string for interop purposes, use the method Marshal.StringToHGlobalUni(string).")]
        public static string Copy(string str);
    }
}
```

**Comment by terrajobst** [comment]
A few thoughts:

* Should we do the same for `String.Clone()`?
* Should also mark the API as `EditorBrowsable[Never]`?

**Comment by GrabYourPitchforks** [comment]
(We discussed this in person, but I'll copy my thoughts here so others can see.)

I don't really care all that much about `String.Clone`, to be honest. Its behavior is contracted to be `return this;`, so it's not really hurting anything by existing, but it does seem a bit silly for anybody to call it. Jeremy suggested that perhaps tool-generated code might call it in certain cases. I could see that argument. It's the same reason we added other "no-op" APIs like [`BinaryPrimitives.ReverseEndianness(byte)`](https://apisof.net/catalog/System.Buffers.Binary.BinaryPrimitives.ReverseEndianness(Byte)).

Marking the API as editor not-browsable is an interesting thought. We should definitely do it when we eventually mark `string.Copy` as obsolete-as-error rather than obsolete-as-warning.

**Comment by weltkante** [comment]
@GrabYourPitchforks @terrajobst `String.Clone` is probably there to implement `ICloneable` so it does have some value if you are dealing with objects of unknown type and are looking for the `ICloneable` interface to make deep copies or something. Probably should have been an explicit interface implementation instead of being public though, but that might be too late to change.

**Comment by GrabYourPitchforks** [comment]
@svick The next step is obsolete as error, which needs to be non-suppressible. This argues that going through the standard obsolescence procedure is more appropriate than an analyzer.

**Comment by danmosemsft** [comment]
@jaredpar since he may have comments on obsolete attributing..

**Comment by jaredpar** [comment]
@GrabYourPitchforks 

> The next step is obsolete as error, which needs to be non-suppressible. 

I believe that we won't let you downgrade an obsolete error to a warning. Will let @agocke confirm.

**Comment by terrajobst** [comment]
We should mark this obsolete in .NET Standard as well. I'll submit the PR for that.

@GrabYourPitchforks are you on the hook for cleaning up any call sites in CoreFX?

**Comment by GrabYourPitchforks** [comment]
@terrajobst Yes, I'll clean up call sites throughout coreclr and corefx.
