### ISSUE TITLE
Incorrect DispatcherPriority on DispatcherSynchronizationContext from BeginInvoke

### ISSUE THREAD

**Issue by livarcocc** [dotnet/corefx#33612]
@nick-beer commented on [Fri Nov 16 2018](https://github.com/dotnet/core-sdk/issues/157)

In porting our test suite to .NET Core 3.0, I'm seeing a new failure in one of our tests.  Code running as the result of a call to InvokeAsync/BeginInvoke should have a DispatcherSynchronization context whose internal priority matches that of the call to BeginInvoke/InvokeAsync.  This was true under .NET Framework, but is no longer true under .NET Core 3.  The synchronization context always has a priority of DispatcherPriority.Normal - regardless of the priority given to BeginInvoke/InvokeAsync.

This is important to our application because it is very sensitive to priority, and we often have side effect work that runs as a result of various calls to BeginInvoke.  If this side effect work ends up in async/await code paths, the sync context that is captured will have the wrong, undesired priority.

To reproduce the issue:
- clone the repo https://github.com/nick-beer/SyncCxtPriorityBug
- Run the test *SyncContextPriority_Fails* in the Tests folder.

**Comment by ericstj** [comment]
This is either threading or WPF, I haven't had a chance to debug to triage yet.  /cc @stephentoub @rladuca

**Comment by danmosemsft** [comment]
@ericstj do you plan to look further? It would be good to know whether there is 3.0 work here.

**Comment by ericstj** [comment]
I was able to reproduce and root cause this issue.  I've filed a WPF issue here: https://github.com/dotnet/wpf/issues/245

If you'd like to workaround this you can add a static constructor to your application (or whatever code runs *very* early in your tests) that does the following:
```c#
static App()
{
    BaseCompatibilityPreferences.ReuseDispatcherSynchronizationContextInstance = false;
}
```
