### ISSUE TITLE
.NET Core Missing System.Windows.Media.Imaging 

### ISSUE THREAD

**Issue by aaabbbcccddd00001111** [dotnet/corefx#33618]
Hi,
.NET Core does not have System.Windows,Media.Imaging . I need the classes in System.Windows,Media.Imaging .

**Comment by AlexejLiebenthal** [comment]
As the System.Windows.Media.Imaging namespace is part of the PresentationCore Assembly, I think that this will never be a part of the cross platform corefx project.
PresentationCore/-Framework assemblies are the base for developing windows only WPF applications and the classes provided in the namespace System.Windows.Media.Imaging are for working with bitmap images in a windows WPF/XAML application context.

As an alternative, if you are developing a ".netcoreapp2.1", than try maybe the classes provided in the System.Drawing or System.Drawing.Imaging namespaces. Else there are also a bunch of nuget packages out there for image processing, which should meet your requirements.
[CoreFx Image Processing](https://blogs.msdn.microsoft.com/dotnet/2017/01/19/net-core-image-processing/)

**Comment by karelz** [comment]
WPF will be part of .NET Core 3.0 as Windows-only option. You can wait to get it there.
You can try previews to see if it is already present.
