### ISSUE TITLE
Implement object overloads, IEquatable, and IFormattable for Vector64/128/256<T>

### ISSUE THREAD

**Issue by fiigii** [dotnet/corefx#33613]
Currently, developers have to store `Vector64/128/256<T>` to an array to print the elements. It would be helpful for simple command line debugging if `Vector64/128/256<T>` override `ToString` method. 

@tannergooding @eerhardt @CarolEidt

**Comment by fiigii** [comment]
@tannergooding 's feedback
- What about `GetHashCode()` and `Equals()` which are generally overridden at the same time?
- `ElementCount` is another internal one that might be useful to expose

**Comment by tannergooding** [comment]
### Proposed API

```csharp
public partial struct Vector64<T> : IEquatable<Vector64<T>>, IFormattable
{
    public bool Equals(Vector64<T> other);
    public override bool Equals(object obj);
    public override int GetHashCode();
    public override string ToString();
    public string ToString(string format, IFormatProvider formatProvider);
}

public partial struct Vector128<T> : IEquatable<Vector128<T>>, IFormattable
{
    public bool Equals(Vector128<T> other);
    public override bool Equals(object obj);
    public override int GetHashCode();
    public override string ToString();
    public string ToString(string format, IFormatProvider formatProvider);
}

public partial struct Vector256<T> : IEquatable<Vector256<T>>, IFormattable
{
    public bool Equals(Vector256<T> other);
    public override bool Equals(object obj);
    public override int GetHashCode();
    public override string ToString();
    public string ToString(string format, IFormatProvider formatProvider);
}
```

**Comment by tannergooding** [comment]
Logged https://github.com/dotnet/corefx/issues/33614 for the `Count` property.

**Comment by fiigii** [comment]
`Equals` is a really good API to expose, it can be implemented as an intrinsic.

**Comment by eerhardt** [comment]
@tannergooding - we still need to expose the APIs in corefx, right? Should this be closed when that happens instead?

**Comment by tannergooding** [comment]
Yes, it auto-closed when the PR was merged.
