### ISSUE TITLE
Improve BMI2 MultiplyNoFlags APIs

### ISSUE THREAD

**Issue by fiigii** [dotnet/corefx#33615]
The current `Bmi2.MultiplyNoFlags` API follows the C/C++ intrinsic design that returns lower half of the result and stores the higher half in memory via a pointer of out argument. According to feedback https://github.com/dotnet/coreclr/issues/18712#issuecomment-438065304, the API returning higher half is more useful for developers and simpler to implement and optimize for compiler writers. So, we suggest changing the API to:

```csharp
public static unsafe uint MultiplyNoFlags(uint left, uint right);
public static unsafe uint MultiplyNoFlags(uint left, uint right, uint* lower);
```

**Comment by fiigii** [comment]
@tannergooding @eerhardt @CarolEidt @pentp @mikedn

**Comment by pentp** [comment]
I would still prefer the original API with just an added `MultiplyHighNoFlags`:
```c#
public static unsafe uint MultiplyNoFlags(uint left, uint right, uint* high);
public static uint MultiplyHighNoFlags(uint left, uint right);
```
And same overloads for `ulong`.
But I would be happy either way as long as both are usable.
