### ISSUE TITLE
Expose a Count property for Vector64/128/256<T>

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#33614]
Currently developers have to either hardcode or manually calculate the number of elements in a given vector. It would be helpful to expose a `Count` property that does this for you.

### Proposed API

```csharp
public partial struct Vector64<T>
{
    public static int Count { get; }
}

public partial struct Vector128<T>
{
    public static int Count { get; }
}

public partial struct Vector256<T>
{
    public static int Count { get; }
}
```

### Usages

We currently expose this property internally as part of our argument validation for things like `GetElement` and `WithElement`. This is expected to be used by the user to validate that inputs to the various intrinsics or helper methods are also in range, when they are not statically known to be so. It is also expected to be used as the increment for certain for loops (such as when performing vectorized operations over an array of `T`) and other similar cases.

**Comment by tannergooding** [comment]
CC. @fiigii, @eerhardt, @CarolEidt

**Comment by benaadams** [comment]
Sorta?
```csharp
public partial struct Vector128<T>
{
    public int Count => sizeof(Vector128<T>) / sizeof(T)
}
```

**Comment by tannergooding** [comment]
Yes, effectively and it should behave as a JIT constant (similar to `Vector<T>.Count`)

**Comment by gfoidl** [comment]
Then something similar to https://github.com/dotnet/coreclr/pull/8001 would also be fine -- in a loop over the `Count` property, this loop should be unrolled.

Of course, this can be a follow-up to this change.

**Comment by eerhardt** [comment]
Why is it an instance member? Why not `static`?

Also, what are the typical use cases?  (I can probably guess, but I'd like to see them called out.)

**Comment by tannergooding** [comment]
> Why is it an instance member? Why not static?

The existing internal property is static, I just forgot to put the keyword here as well.

> Also, what are the typical use cases? (I can probably guess, but I'd like to see them called out.)

Fixed. Called out that we are already using this internally for argument validation and it is expected, if nothing else, to be used as the same for external user code.

**Comment by gfoidl** [comment]
> Usages

I believe a more common usage will be in looping over an array, where the step-size can be coded with use of `Count` as it is more readable / expressive than just using an int-constant. As well this may open the door for some further generic usages of `VectorXYZ<T>` (e.g. `byte` and `char` / `ushort` for string-data).
