### ISSUE TITLE
Find source code for specific version

### ISSUE THREAD

**Issue by rhegner** [dotnet/corefx#33627]
My company requires me to register all direct and indirect dependencies of my application with some internal tool and attaching the source archives for all of these dependencies. For most of my 438 dependencies I was able to locate the sources on GitHub - but with some of the CoreFX libraries I'm having troubles...

The sources for all of the following dependencies seem to be hosted in this repository:
* `Microsoft.CSharp`
* `Microsoft.Win32.Primitives`
* `Microsoft.Win32.Registry`
* `System.**`
* `runtime.**native.System.**`

My project references `4.x.x` versions of these dependencies, but in this repository I can only find `1.x.x` and `2.x.x` version tags. So my question is: Are the sources for the `4.x.x` versions located in some other repository? Or does there exist a mapping between the `4.x.x` versions and the versions in this repository?

For some dependencies had problems to even find the correct source repository:
* `Microsoft.AspNet.WebApi.Client            5.2.6`
* `Microsoft.NETCore.Jit                     1.0.2`
* `Microsoft.NETCore.Portable.Compatibility  1.0.1`
* `Microsoft.NETCore.Runtime.CoreCLR         1.0.2`
* `Microsoft.NETCore.Windows.ApiSets         1.0.1`

I know this second question might be a off-topic here, but if anyone could give me a hint as to where I can find these sources, that would be greatly appreciated!

**Comment by rhegner** [comment]
Ok I found an approach which solves most of my problems.

I wrote a script which scans the content of the
    https://github.com/dotnet/versions/tree/master/build-info/dotnet/coreclr/release
and
    https://github.com/dotnet/versions/tree/master/build-info/dotnet/corefx/release
folders to build a mapping table.

This mapping table allows me to find the sources for most of the 4.x versions of the libraries.

However I have 7 dependencies for which this approach fails to find the correct sources:
* `runtime.win-arm64.runtime.native.System.Data.SqlClient.sni 4.4.0`
* `runtime.win-x64.runtime.native.System.Data.SqlClient.sni 4.4.0`
* `runtime.win-x86.runtime.native.System.Data.SqlClient.sni 4.4.0`
* `System.Data.SqlClient 4.4.0`
* `System.IO.FileSystem.DriveInfo 4.3.1`
* `System.Security.AccessControl 4.4.0`
* `System.Security.Principal.Windows 4.4.0`

Plus, there are still the following dependencies for which I couldn't find the proper source repository:
* `Microsoft.AspNet.WebApi.Client 5.2.6`
* `Microsoft.NETCore.Portable.Compatibility 1.0.1`
* `Microsoft.NETCore.Windows.ApiSets 1.0.1`

**Comment by danmosemsft** [comment]
@joperezr maybe you can help with this one?

**Comment by dougbu** [comment]
@natemcmaster 
> where is the source for Microsoft.AspNet.WebApi.Client?

That code is found in the https://github.com/aspnet/AspNetWebStack repo. (On a related note, we have an issue to update the package metadata to make this more obvious -- aspnet/ASpNetWebStack#190)

**Comment by rhegner** [comment]
Thanks @joperezr, this was really helpful!

However, for the `System.IO.FileSystem.DriveInfo 4.3.1` I couldn't find a commit hash in the package description on nuget.org.

@dougbu I'm still struggling with `Microsoft.AspNet.WebApi.Client 5.2.6`. Looking at the /src folder of the repo you mention, I can't see a `Microsoft.AspNet.WebApi.Client` folder. Also searching for `WebApi.Client` in that repo does not give any meaningful results.

**Comment by dougbu** [comment]
@rhegner the name of the package is Microsoft.AspNet.WebApi.Client but the contained assemblies are named System.Net.Http.Formatting.dll. The relevant sources in src\System.Net.Http.Formatting*.

**Comment by rhegner** [comment]
Thanks @joperezr for your help!

@dougbu so which commit/tag of that repository does contain the sources of the System.Net.Http.Formatting.* assemblies which constitute `Microsoft.AspNet.WebApi.Client 5.2.6`?

**Comment by dougbu** [comment]
@rhegner use the [v3.2.6](https://github.com/aspnet/AspNetWebStack/tree/v3.2.6) tag.

**Comment by rhegner** [comment]
Perfect, thank you! You guys were really helpful!
