### ISSUE TITLE
Incorrect CurrencyDecimalPlaces in the NumberFormatInfo for culture "wo-SN"

### ISSUE THREAD

**Issue by iampez** [dotnet/corefx#33623]
I believe that the number of decimal places for the currency XOF is incorrect for the culture "wo-SN". It returns 2 decimal places, but online documentation suggests it should be 0. All other cultures in .NET that use this currency return 0 decimal places.

This code shows how I access the value:
```
CultureInfo ci = CultureInfo.GetCultureInfo("wo-SN");
var decimalPlaces = ci.NumberFormat.CurrencyDecimalDigits;
```

**Comment by 0xd4d** [comment]
It returns 0 on Linux. Similar issue: https://github.com/dotnet/core/issues/2069

**Comment by iampez** [comment]
I realise now (thanks to reply from 0xd4d) that this information is pulled from the OS and is a formatting concern, rather than a specific currency concern. I had assumed that this data was built into System.Globalisation. The value is correctly being pulled from the OS.
