### ISSUE TITLE
Some bits in the file attributes are masked out

### ISSUE THREAD

**Issue by sba923** [dotnet/corefx#33644]
(derived from [https://github.com/PowerShell/PowerShell/issues/8315](url))

Files in the OneDrive sync folder with the "Files on Demand" feature make use of a number of specific attribute bits, such as:

0x00000200 | SparseFile
0x00000400 | ReparsePoint
0x00001000 | Offline
0x00080000 | Pinned
0x00100000 | Unpinned

(non-exhaustive list)

In PowerShell 6.1, some of the bits are masked out, so code that runs in Windows PowerShell 5.1 will not run correctly under PowerShell 6.1.

Given that calling the API directly returns the same result as PowerShell, this is a .NET Core issue.

Repro steps:

In Windows PowerShell 5.1, run the following commands:

````
'{0:x}' -f ([system.io.file]::GetAttributes("C:\Users\steph\OneDrive\Always keep on this device.txt"))
'{0:x}' -f ([system.io.file]::GetAttributes("C:\Users\steph\OneDrive\Free up space.txt"))
````

The output is:

````
00080420
00501620
````

In PowerShell 6.1, the _incorrect_ output is:

````
00080020
00500020
````

**Comment by stephentoub** [comment]
cc: @JeremyKuhne

**Comment by JeremyKuhne** [comment]
It seems pretty unlikely that CoreFX has an issue as we simply return what the OS gives us.

https://source.dot.net/#System.IO.FileSystem/System/IO/FileSystem.Windows.cs,198

I'm testing on Windows 10 1809 and I don't see any difference between .NET 4 (which is what Powershell 5.1 is running against) and .NET Core when looking at an offline OneDrive file. That said, PowerShell does return different set of attributes. I don't see anything special in the manifest for PowerShell that might change the behavior. Some hidden Windows feature that I'm unaware of perhaps...

**Comment by sba923** [comment]
Well, using the following simplistic C# program built using Visual Studio 2017 15.8.9 running against .NET Core 2.1

````
using System;


namespace TestFileAttributes
{
    class Program
    {
        static void Main(string[] args)
        {
            var filepath = args[0];
            var attr = System.IO.File.GetAttributes(filepath);
            Console.WriteLine("Attributes for '{0}': 0x{1:x}", filepath, attr);
        }
    }
}
````

I get:

````
Attributes for 'c:\users\steph\OneDrive\Free up space.txt': 0x00500020
````

Whereas the (correct) attributes reported by Windows PowerShell 5.1 are:

````
PS C:/Users/steph> '{0:x}' -f ([system.io.file]::GetAttributes("C:\Users\steph\OneDrive\Free up space.txt"))
00501620
````

**Comment by sba923** [comment]
So?

**Comment by JeremyKuhne** [comment]
> So?

Sorry, got caught up in a critical issue. Pinging the Windows file system folks.

**Comment by JeremyKuhne** [comment]
Ok, there is a Windows filter that explicitly filters these attributes out _except_ for programs under the Windows system directories (which PowerShell 5.1 lives under).

There are Windows APIs to get/set the filtering behavior for the process and/or thread. They are:

https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-rtlqueryprocessplaceholdercompatibilitymode
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-rtlquerythreadplaceholdercompatibilitymode
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-rtlsetprocessplaceholdercompatibilitymode
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-rtlsetthreadplaceholdercompatibilitymode

I'll reactivate the issue on PowerShell so they can decide which way they want to go for consistency.

**Comment by JeremyKuhne** [comment]
Hmm, actually I can't reopen. @SteveL-MSFT, per my comments above, this is something PowerShell needs to address / be involved in.

**Comment by SteveL-MSFT** [comment]
@JeremyKuhne thanks for the pointers, I've reopened the PowerShell issue

**Comment by sba923** [comment]
Thanks for the clarification.

Where is all that filtering stuff documented? What's the rationale?

For me that's just weird… It means that you can write PowerShell scripts that deal with such attributes, but not C# programs!

At least at the end of the day we'll be able to use either Windows PowerShell or PowerShell core...

**Comment by JeremyKuhne** [comment]
> Where is all that filtering stuff documented? What's the rationale?

I'm not sure where or if it is given an overview. It is presumably to make apps treat them as if they were any other file (i.e. compat). I'll try and find the right public routing for inquiries on this feature.

**Comment by sba923** [comment]
I've been able to figure things out:

````
namespace TestFileAttributes
{
    class Program
    {

        [DllImport("ntdll.dll")]
        static extern sbyte RtlQueryProcessPlaceholderCompatibilityMode();
        [DllImport("ntdll.dll")]
        static extern sbyte RtlSetProcessPlaceholderCompatibilityMode(sbyte pcm);

        const sbyte PHCM_APPLICATION_DEFAULT = 0;
        const sbyte PHCM_DISGUISE_PLACEHOLDER = 1;
        const sbyte PHCM_EXPOSE_PLACEHOLDERS = 2;
        const sbyte PHCM_MAX = 2;
        const sbyte PHCM_ERROR_INVALID_PARAMETER = -1;
        const sbyte PHCM_ERROR_NO_TEB = -2;

        class PlaceholderCompatibilityMode
        {
            public static string ToString(sbyte pcm)
            {
                switch(pcm)
                {
                    case 0: return "PHCM_APPLICATION_DEFAULT";
                    case 1: return "PHCM_DISGUISE_PLACEHOLDER";
                    case 2: return "PHCM_EXPOSE_PLACEHOLDERS";
                    case -1: return "PHCM_ERROR_INVALID_PARAMETER";
                    case -2: return "PHCM_ERROR_NO_TEB";
                    default: return String.Format("(??? unsupported PlaceholderCompatibilityMode value: {0} ???)", pcm);
                }
            }
        }

        static void Main(string[] args)
        {
            var filepath = args[0];
            sbyte pcm = RtlQueryProcessPlaceholderCompatibilityMode();
            Console.WriteLine("Current placeholder compatibility mode: {0} ({1})", pcm, PlaceholderCompatibilityMode.ToString(pcm));
            var attr = System.IO.File.GetAttributes(filepath);
            Console.WriteLine("Attributes for '{0}': 0x{1:x}", filepath, attr);
            sbyte newpcm = PHCM_EXPOSE_PLACEHOLDERS;
            Console.WriteLine("Setting placeholder compatibility mode to: {0} ({1})", newpcm, PlaceholderCompatibilityMode.ToString(newpcm));
            RtlSetProcessPlaceholderCompatibilityMode(newpcm);
            attr = System.IO.File.GetAttributes(filepath);
            Console.WriteLine("Attributes for '{0}': 0x{1:x}", filepath, attr);
        }
    }
}
````

Here's the output:

````
Current placeholder compatibility mode: 1 (PHCM_DISGUISE_PLACEHOLDER)
Attributes for 'c:\users\steph\OneDrive\Free up space.txt': 0x00500020
Setting placeholder compatibility mode to: 2 (PHCM_EXPOSE_PLACEHOLDERS)
Attributes for 'c:\users\steph\OneDrive\Free up space.txt': 0x00501620
````

**Comment by danmosemsft** [comment]
Is this resolved, can we close it?

**Comment by sba923** [comment]
If you ask me, this (corefx) issue can be closed, given that the problem lies in the PowerShell Core code (and _that_ issue has _not_ been resolved... yet)
