### ISSUE TITLE
sync.cmd/sh mentioned on wiki but not in repo tree at master

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/corefx#33648]
https://github.com/dotnet/corefx/wiki/Build-and-run-tests

Has the `sync` command been merged into `build`?

What's the correct fix for the wiki?

#19883 and #24403 both refer to `sync.cmd` so might be obsolete.

**Comment by danmosemsft** [comment]
Probably deleted as they were low value over just git pull. @weshaggard?

**Comment by karelz** [comment]
@wtgodbe ?

**Comment by weshaggard** [comment]
They were removed as they added limited value after the engineering system shift. If folks want a similar behavior of pulling down all the packages without doing a build they can run `build.cmd/sh -restore`.

**Comment by karelz** [comment]
Thanks! Wiki updated.
