### ISSUE TITLE
Binary serialization failure on .NET Core 2.1 in KeyValuePair/Struct/Class hierarchy

### ISSUE THREAD

**Issue by ggeurts** [dotnet/corefx#33655]
.NET Core 2.1 introduced a breaking change in BinaryFormatter that causes an `ArgumentException` when serializing a hierarchy consisting of a `KeyValuePair<K,SomeStruct>`->`SomeStruct`->`SomeClass`. Full reproduction follows:

```csharp
    using System.Collections.Generic;
    using System.IO;
    using System.Runtime.Serialization.Formatters.Binary;
    using Xunit;

    namespace System.Runtime.Serialization.Formatters.Tests
    {
        public class BugReproTests
        {
            /// <summary>
            /// This method reproduces a binary serialization issue, introduced on .NET Core 2.1
            /// </summary>
            /// <remarks>
            /// Throws System.ArgumentException : Field in TypedReferences cannot be static or init only.
            /// at System.TypedReference.MakeTypedReference(Object target, FieldInfo[] flds)
            /// at System.Runtime.Serialization.ObjectManager.DoValueTypeFixup(FieldInfo memberToFix, ObjectHolder holder, Object value)
            /// at System.Runtime.Serialization.ObjectManager.CompleteObject(ObjectHolder holder, Boolean bObjectFullyComplete)
            /// at System.Runtime.Serialization.ObjectManager.DoNewlyRegisteredObjectFixups(ObjectHolder holder)
            /// at System.Runtime.Serialization.ObjectManager.RegisterObject(Object obj, Int64 objectID, SerializationInfo info, Int64 idOfContainingObj, MemberInfo member, Int32[] arrayIndex)
            /// at System.Runtime.Serialization.Formatters.Binary.ObjectReader.RegisterObject(Object obj, ParseRecord pr, ParseRecord objectPr, Boolean bIsString)
            /// at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObjectEnd(ParseRecord pr)
            /// at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(ParseRecord pr)
            /// at System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run()
            /// at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
            /// at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
            /// </remarks>
            [Fact]
            public void ReproduceBinaryFormatterIssueInNetcoreapp2_1()
            {
                var root = new KeyValuePair<int, ChildStruct>(0, new ChildStruct(new GrandChildClass()));
                RoundtripBinarySerialization(root);
            }

            public static T RoundtripBinarySerialization<T>(T original)
            {
                BinaryFormatter binaryFormatter = new BinaryFormatter();
                using (MemoryStream memoryStream = new MemoryStream())
                {
                    binaryFormatter.Serialize(memoryStream, original);
                    memoryStream.Seek(0L, SeekOrigin.Begin);
                    return (T)binaryFormatter.Deserialize(memoryStream);
                }
            }

            [Serializable]
            private struct ChildStruct
            {
                private GrandChildClass _grandChild;

                public ChildStruct(GrandChildClass grandChild)
                {
                    _grandChild = grandChild;
                }
            }

            [Serializable]
            private class GrandChildClass
            {
                public GrandChildClass()
                {
                }
            }
        }
    }
```

csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>netcoreapp2.1;netcoreapp2.0;net472</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Net.Test.Sdk" Version="15.9.0" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

Repro:
```
dotnet test -f netcoreapp2.1 (fails)
dotnet test -f netcoreapp2.0 (fails)
dotnet test -f net472
```

EDIT by @ViktorHofer: csproj added and style

**Comment by stephentoub** [comment]
cc: @ViktorHofer

**Comment by ViktorHofer** [comment]
Thanks. Fails on netcoreapp2.0 also, passes on net472. Need to investigate.

**Comment by ViktorHofer** [comment]
This change which change the KeyValuePair<,>'s value field to readonly is causing the failure: https://github.com/dotnet/coreclr/commit/278c8f3f04dc120c07face13221b70b1116f4552. Some explanation here: https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Serialization.Formatters/src/System/Runtime/Serialization/ObjectManager.cs#L501. Value types that are boxed to an object, require a fixup and its parent is marked as serializable must not be stored in a static or readonly field. The change is causing both KeyValuePair<,> and Nullable<> to throw. We should revert it for these both types and add a comment.

**Comment by stephentoub** [comment]
Nullable<> was already reverted and before it shipped:
https://github.com/dotnet/coreclr/pull/15198
but for other reasons (ToString could make observable changes).

But I'm loathe to revert for KeyValuePair now, especially since we already shipped with it as readonly, and removing readonly from a struct is a breaking change.  There's no way we can instead address this in BinaryFormatter?

cc: @jkotas

**Comment by jkotas** [comment]
> revert for KeyValuePair now, especially since we already shipped with it as readonly, and removing readonly from a struct is a breaking change

Agree, it does not make sense to replace accidental corner case breaking change with intentional more severe breaking change.

We have done best effort to bring binary serialization to .NET Core. It does not mean that the binary serialization is a robust technology. There are number of subtle things accidentally broken already, and it will only get worse over time, no matter how hard we try.

**Comment by ggeurts** [comment]
>           Thanks. Fails on netcoreapp2.0 also, passes on net472. Need to investigate.

Interesting, I hit this issue when running tests on netcoreapp2.1 whereas same tests pass on netcorapp2.0.

**Comment by stephentoub** [comment]
@jkotas, the actual exception here is coming from an explicit check in MakeTypedReference that throws if an instance field is readonly (I've not checked yet to see if there are issues lurking beyond that). Since reflection will let you modify such a field anyway, and this is really just reflection, would it make sense to just remove that restriction from TypedReference?

**Comment by jkotas** [comment]
> this is really just reflection, would it make sense to just remove that restriction from TypedReference?

Yes, I think it would make sense. I would still keep `static & readonly` fields disallowed.

**Comment by stephentoub** [comment]
> I would still keep static & readonly fields disallowed.

Yup (it already disallows all statics).

**Comment by ViktorHofer** [comment]
@stephentoub as you self-assigned the issue I'll stay idle.
