### ISSUE TITLE
No client certificate sent by HttpClientHandler in .NET Core

### ISSUE THREAD

**Issue by lexugax** [dotnet/corefx#33651]
Greetings,
I have the same (or almost the same) problem as specified in issue #30483.
I am using PerfView to collect the events and I believe I got logs, but I am not sure what I'm looking for as there are dozens of Event Types even after filtering by  *Microsoft-System-Net-Security.
![image](https://user-images.githubusercontent.com/821389/48862991-c0badf00-ed7c-11e8-8830-b74217751dac.png)

**Comment by davidsh** [comment]
Please collect all *Microsoft-System-Net related logs such as:

"*Microsoft-System-Net-Http"
"*Microsoft-System-Net.Security" etc.

We don't need the Windows* logs.

Also, please attach a small repro Visual Studio solution that reproduces the error.  If possible, can you attach the client certificate you're trying to use?  Just attach the public key portion of the certificate and no private keys or proprietary information.

**Comment by caesar1995** [comment]
The `Events` tab is what you should look into, then filtered by System-Net.Security. Can you upload the PerfViewData.etl file for the failed cases?

**Comment by caesar1995** [comment]
@lexugax Any updates?

**Comment by lexugax** [comment]
I am sorry, I have been pulled away from this because of pressing matters. I will post the requested data within the next couple of days.
Thanks.

**Comment by lexugax** [comment]
@caesar1995  @davidsh I'm sorry for the late response. After discussing the issue with someone from my company's Information Security group, I cannot send the log files due to security concerns. Please let me know if there is any other way or information I could look for. Currently I am setting up a test environment to verify that the certificate is indeed being sent or not by using wireshark to inspect the packages.

**Comment by lexugax** [comment]
@caesar1995 @davidsh I finally got a breakthrough. It turns out that the issue had to do with the server not accepting the client certificate. I figured it out by installing my server app in a different machine on IIS (as supposed to my local machine in debug mode). When I enabled "Accept client certificate" on IIS, I began receiving the certificate on my server application.
