### ISSUE TITLE
Simple 'Hello world' application (.Net Core) fails to run on linux armv7 device

### ISSUE THREAD

**Issue by appugeorge** [dotnet/corefx#33673]
The application (based on .Net Core 2.0) is published as framework dependent one. .Net Core 2.1.4 runtime is installed in the device.

The strange thing is that the application runs fine when we set the "System.Globalization.Invariant" to true or create an env. variable DOTNET_SYSTEM_GLOBALIZATION_INVARIANT with value 1. (as mentioned in [https://github.com/dotnet/corefx/blob/master/Documentation/architecture/globalization-invariant-mode.md](url))

The dependencies required for .Net Core [(https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore21](url)) has been verified to be present on the device (for Ubuntu). I am not completely sure which version of Ubuntu is present in the device (or even a custom modified version of Ubuntu). The only info I could get from the device was as follows:

_Linux version 4.14.40-g4796173fc5 (root@ubuntu) (gcc version 7.2.1 20171011 (Linaro GCC 7.2-2017.11)) #20 PREEMPT Wed Oct 17 06:54:13 PDT 2018_

Since the issue seems to be related to Globalization, we did a closer look at the libicu dependency. The libs present in the device is as follows:

libicudata.so.61.1
libicui18n.so.61.1
libicuio.so.61.1
libicutest.so.61.1
libicutu.so61.1
libicuuc.so61.1

There exist soft links to these files withou version info in the filename.

Is it possible to find what dependency is missing here. Or is there more detailed list of lib dependency for .Net Core that I can verify against the device assuming it is not a standard version of Ubuntu that is running on the device?

**Comment by janvorli** [comment]
The above mentioned ICU libraries should work. Can you please run the app with env var `LD_DEBUG=all` and share the result as a gist (it is going to be large)?  I should be able to tell what's wrong with the ICU libraries.
Please set the variable only for the execution of the application - write the `LD_DEBUG=all` followed by space on the command line before the dotnet command, so e.g.:
```
LD_DEBUG=all dotnet yourtest.dll
```

**Comment by appugeorge** [comment]
Here is the output of LD_DEBUG=all dotnet HelloWorld.dll

https://gist.github.com/appugeorge/23a5528d9607398ce7afae2a3154f3cc

**Comment by janvorli** [comment]
@appugeorge unless the output is somehow truncated, it looks as if dotnet has crashed during the enumeration of the ICU libraries present on the system at the spot it was trying to open the version of the library that is actually present.
Do you get any error message when it fails to start? If not, can you please get me the output of the following command that you execute right after the dotnet launch fails?
```sh
echo $?
```

Also, you can get the version of Linux you are running as follows:
```sh
cat /etc/os-release
```

**Comment by appugeorge** [comment]
I ran it again and it stops at the below point in the terminal.

       110:     file=libicuuc.so.61 [0];  dynamically loaded by /Storage/dotnet/shared/Microsoft.NETCore.App/2.1.4/System.Globalization.Native.so [0]
       110:     find library=libicuuc.so.61 [0]; searching
       110:      search cache=/etc/ld.so.cache
       110:      search path=/lib:/usr/lib              (system search path)
       110:       trying file=/lib/libicuuc.so.61
       110:       trying file=/usr/lib/libicuuc.so.61


It does not show any error message when it fails.

`/Storage # dotnet ./HelloWorld/HelloWorld.dll`
`/Storage #`

The output for _echo $?_  right after the failure.
`/Storage # echo $?`
`1`

The output for linux version.
`/Storage # cat /etc/os-release`
`cat: can't open '/etc/os-release': No such file or directory`

`/Storage # uname -a`
`Linux (none) 4.14.40-g4796173fc5 #20 PREEMPT Wed Oct 17 06:54:13 PDT 2018 armv7l GNU/Linux`

Hope this helps. I could not find more info about the linux version in the device.

**Comment by janvorli** [comment]
Hmm, that's strange. Can you please try to run with `CLR_ICU_VERSION_OVERRIDE=61.1` env variable set? And if it doesn't work, set the `LD_DEBUG=all` together with `CLR_ICU_VERSION_OVERRIDE=61.1`and share the log again?
Also, can you please share the output of the following commands?
```sh
ls -la /usr/lib/libicu*
ls -la /lib/libicu*
```

**Comment by appugeorge** [comment]
/Storage # CLR_ICU_VERSION_OVERRIDE=61.1 dotnet ./HelloWorld/HelloWorld.dll
/Storage # echo $?
1
/Storage #


The log for 
LD_DEBUG=all CLR_ICU_VERSION_OVERRIDE=61.1 dotnet ./HelloWorld/HelloWorld.dll 

[https://gist.github.com/appugeorge/b62db7f9b2425be71e6b32bddd42b783](url)



/Storage # ls -la /usr/lib/libicu*
lrwxrwxrwx    1 root     0               18 Sep  9  2018 /usr/lib/libicudata.so -> libicudata.so.61.1
lrwxrwxrwx    1 root     0               18 Sep  9  2018 /usr/lib/libicudata.so.61 -> libicudata.so.61.1
-rwxr-xr-x    1 root     0         26891520 Mar 30  2018 /usr/lib/libicudata.so.61.1
lrwxrwxrwx    1 root     0               18 Sep  9  2018 /usr/lib/libicui18n.so -> libicui18n.so.61.1
lrwxrwxrwx    1 root     0               18 Sep  9  2018 /usr/lib/libicui18n.so.61 -> libicui18n.so.61.1
-rwxr-xr-x    1 root     0          2275076 Mar 30  2018 /usr/lib/libicui18n.so.61.1
lrwxrwxrwx    1 root     0               16 Sep  9  2018 /usr/lib/libicuio.so -> libicuio.so.61.1
lrwxrwxrwx    1 root     0               16 Sep  9  2018 /usr/lib/libicuio.so.61 -> libicuio.so.61.1
-rwxr-xr-x    1 root     0            46916 Mar 30  2018 /usr/lib/libicuio.so.61.1
lrwxrwxrwx    1 root     0               18 Sep  9  2018 /usr/lib/libicutest.so -> libicutest.so.61.1
lrwxrwxrwx    1 root     0               18 Sep  9  2018 /usr/lib/libicutest.so.61 -> libicutest.so.61.1
-rwxr-xr-x    1 root     0            55988 Mar 30  2018 /usr/lib/libicutest.so.61.1
lrwxrwxrwx    1 root     0               16 Sep  9  2018 /usr/lib/libicutu.so -> libicutu.so.61.1
lrwxrwxrwx    1 root     0               16 Sep  9  2018 /usr/lib/libicutu.so.61 -> libicutu.so.61.1
-rwxr-xr-x    1 root     0           162908 Mar 30  2018 /usr/lib/libicutu.so.61.1
lrwxrwxrwx    1 root     0               16 Sep  9  2018 /usr/lib/libicuuc.so -> libicuuc.so.61.1
lrwxrwxrwx    1 root     0               16 Sep  9  2018 /usr/lib/libicuuc.so.61 -> libicuuc.so.61.1
-rwxr-xr-x    1 root     0          1477192 Mar 30  2018 /usr/lib/libicuuc.so.61.1


/Storage # ls -la /lib/libicu*
ls: /lib/libicu*: No such file or directory
/Storage #

**Comment by janvorli** [comment]
This is strange again. There is nothing about trying to load the libicuuc.so.61.1 or any other libicuuc version in the log.
One more idea, can you please check that the icu libraries have their dependencies present using the following command?
```sh
ldd /usr/lib/libicuuc.so.61.1
ldd /usr/lib/libicui18n.so.61.1
ldd /usr/lib/libicudata.so.61.1
```
And also, I'd like to check the versioning schema of the libicu symbols:
```sh
objdump -T /usr/lib/libicuuc.so.61.1 | grep "u_strlen"
```

**Comment by appugeorge** [comment]
/Storage # objdump -T /usr/lib/libicuuc.so.61.1 | grep "u_strlen"
-sh: objdump: not found
/Storage # ldd /usr/lib/libicuuc.so.61.1
-sh: ldd: not found


Seems both objdump and ldd are not present in the device. Can I get those from somewhere?

**Comment by janvorli** [comment]
ldd not present? That's a basic component of glibc. It looks like your distro is something really exotic or somehow pruned in a strange way. How do you actually know it is some kind of ubuntu at all?
As for the objdump, can you install a package named `binutils`? It should be part of it.

**Comment by appugeorge** [comment]
It is possible that it is not a kind of Ubuntu at all. The only basis of my assumption, that it is some kind of Ubuntu, is the output of _cat /proc/version_ :

Linux version 4.14.40-g4796173fc5 (root@**ubuntu**) (gcc version 7.2.1 20171011 (Linaro GCC 7.2-2017.11)) #20 PREEMPT Wed Oct 17 06:54:13 PDT 2018

I will try to get the objdump for the libicuuc.so.61.1 and paste it here.

**Comment by appugeorge** [comment]
The output of objdump -T /usr/lib/libicuuc.so.61.1 | grep "u_strlen"

0009f8cc g    DF .text	00000030  Base        u_strlen_61

All the libicu*.so files and the result of objdump command on them have been taken and placed in a repo at 

[https://github.com/appugeorge/SharedFiles](url)

NB: the objdump was run on different device running Resin OS but with files (libicu*.so) grabbed from the device under investigation.

**Comment by janvorli** [comment]
Everything looks correct, so I am almost out of ideas on what else to check. One last idea - if you could run it under strace, the log it produces might give us some hints.
```sh
strace -f -o trace.txt dotnet ./HelloWorld/HelloWorld.dll
```
The only thing remaining after that is to debug it using gdb or lldb.

**Comment by tarekgh** [comment]
@appugeorge do you still have this problem? if so, is it possible to run it under gdb or lldb?

**Comment by appugeorge** [comment]
Unfortunately we could not do anymore tests with the device and I think you can close this issue for now.
