### ISSUE TITLE
TypeExtensions.GetInterface is missing

### ISSUE THREAD

**Issue by jnm2** [dotnet/corefx#33676]
TypeExtensions makes traditional instance methods such as `Type.GetMethod` available as extension methods for .NET Standard 1.x which minimises the amount of preprocessor-conditional sections you have to write.

Among the many extension methods I expected to find method [`GetInterface(string)`](https://docs.microsoft.com/en-us/dotnet/api/system.type.getinterface?view=netframework-4.7.2#System_Type_GetInterface_System_String_), but it is not there. (https://source.dot.net/#System.Reflection.TypeExtensions/System/Reflection/TypeExtensions.cs)

**Comment by svick** [comment]
Since .Net Standard 1.x should generally be avoided in new code, is it worth improving it?

**Comment by jnm2** [comment]
@svick I would say so. There is enough code that is not new code. I ran into this while implementing a feature for NUnit, for example.

**Comment by jkotas** [comment]
.Net Standard 1.x has shipped. We cannot go back in time and add more to it.

**Comment by svick** [comment]
@jkotas As far as I can tell, [`TypeExtensions` is not part of .Net Standard 1.x proper](https://apisof.net/catalog/System.Reflection.TypeExtensions), it's distributed as [a NuGet package](https://www.nuget.org/packages/System.Reflection.TypeExtensions/), which does contain actual implementation at least for some TFMs. So I think it would be possible to change it.

**Comment by jnm2** [comment]
@jkotas It if was part of .NET Standard 1.4, I wouldn't have had to add a package reference to the NuGet package, right? The reason I thought the NuGet package was versioned independently was that y'all helped me with an update to the package earlier this year (https://github.com/dotnet/corefx/issues/30506).

**Comment by jkotas** [comment]
That package is just a thin wrapper over `System.Private.CoreLib`: https://github.com/dotnet/corefx/blob/master/src/System.Reflection.TypeExtensions/src/System.Reflection.TypeExtensions.csproj#L19 . It cannot be updated independently from the runtime. 

We have stopped shipping NuGet packages that are tightly coupled with the platform itself, e.g. [System.Runtime](https://www.nuget.org/packages/System.Runtime/) has not been updated for 2 years. NuGet packages that are tightly coupled with the platform itself do not provide any value because of they cannot be update independently.

**Comment by jnm2** [comment]
@jkotas Just so I'm following, https://github.com/dotnet/corefx/issues/30506 was just repackaging existing binaries, but adding a GetInterface method to the TypeExtensions package would require changing System.Private.CoreLib in .NET Core 1.0, i.e. shipping 1.0.14 at this point?

**Comment by jnm2** [comment]
Okay. I'm not sure whether or not NUnit would want 1.0.14 to be the only 1.0.x version of .NET Core that it supports, so such a change might not even be satisfactory. Thanks for your help!
