### ISSUE TITLE
Add UnsafeSchedule to PipeScheduler

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#33683]
That doesn't flow `ExecutionContext`
```csharp
public partial abstract class PipeScheduler
{
    public virtual void UnsafeSchedule(Action<object> action, object state);
}
```
From https://github.com/dotnet/corefx/pull/33658#issuecomment-441377612

/cc @stephentoub @davidfowl

**Comment by davidfowl** [comment]
See https://github.com/dotnet/corefx/issues/32924 😆
