### ISSUE TITLE
.net core 2.1  AppDomain.CurrentDomain.UnhandledException

### ISSUE THREAD

**Issue by zhaojie** [dotnet/corefx#33689]
.net core 2.1
To avoid program crash, I use AppDomain.CurrentDomain.UnhandledException to catch the unhandledexception，but the program still crashes and exits
 
Where to set this property of UnhandledExceptionEventArgs.IsTerminating ?

.net,  can set this legacyUnhandledExceptionPolicy 
` <runtime>
    <legacyUnhandledExceptionPolicy enabled="true" />
  </runtime>
`

but in .net core, hot to do?

**Comment by MarcoRossignoli** [comment]
Seems not supported
https://github.com/dotnet/coreclr/blob/c94d8e68222d931d4bb1c4eb9a52b4b056e85f12/src/inc/clrconfigvalues.h#L778
https://github.com/dotnet/coreclr/blob/c4bf09d95011c0b4f86be1001b228b337a11fdd4/Documentation/project-docs/clr-configuration-knobs.md#L811
But comment says https://github.com/dotnet/coreclr/blob/c94d8e68222d931d4bb1c4eb9a52b4b056e85f12/src/inc/clrconfigvalues.h#L81 `this value is available to partners/developers`
I tried with https://github.com/dotnet/coreclr/blob/c4bf09d95011c0b4f86be1001b228b337a11fdd4/Documentation/building/viewing-jit-dumps.md#setting-configuration-variables with `COMPlus_legacyUnhandledExceptionPolicy=1` and `legacyUnhandledExceptionPolicy=1` but it doesn't work for me.

/cc @jkotas

**Comment by jkotas** [comment]
This issue was moved to dotnet/coreclr#21190
