### ISSUE TITLE
new CultureInfo("sv-SE").DateTimeFormat.LongDatePattern returns strange pattern

### ISSUE THREAD

**Issue by aneequrrehman** [dotnet/corefx#33691]
```c#
            var se = new CultureInfo("sv-SE");
            var yesterday = DateTime.UtcNow.AddDays(-1);
            var yesterdayString = yesterday.ToString("D", se);
```

This prints out `den 25 november 2018` which is not what's expected. Upon further investigation, I came to know that for swedish culture, `new CultureInfo("sv-SE").DateTimeFormat.LongDatePattern` returns `'den 'd MMMM yyyy` while the expected one, I believe, is `dddd, MMMM d, yyyy`.

So resultantly if I change the last code line to:
```c#
var yesterdayString = yesterday.ToString("dddd, MMMM d, yyyy", se);
```

Then this works.

**Comment by danmosemsft** [comment]
@aneequrrehman is this Windows, Linux, or OSX? We get the patterns from the OS (eg libicu)

>the expected one, I believe, is dddd, MMMM d, yyyy

What makes you believe this is the expected one? (I don't know whether it is)

**Comment by danmosemsft** [comment]
@aneequrrehman why do you think that's the wrong output?

**Comment by haukurmar** [comment]
Well It's because the .ToString("D", se) display the name of the Day in other cultures. i.e. "Sunday, 25. November 2018"

Shouldn't it be the same for Swedish?

**Comment by aneequrrehman** [comment]
@damosemsft for 25th November, 2018, the output of `nov25.ToString("D", new CultureInfo("en-US"))`; will be `Sunday November, 2018` and so on for other days. And it works correctly for other cultures  as well e.g. Icelandic. However, it doesn't work for Swedish culture. So if culture is set to `sv-SE`, the day is always `den` (which btw isn't even a day name, it just means "on day" in English).

Example posted here:
https://dotnetfiddle.net/vfsnKG

**Comment by danmosemsft** [comment]
That makes sense. 

Since you mentioned Unix, I looked at CLDR (the source of all this) and I don't see anything special about sv-SE for full or long date compared to eg de-DE.
http://demo.icu-project.org/icu-bin/locexp?d_=en&_=sv_SE
http://demo.icu-project.org/icu-bin/locexp?d_=en&_=de_DE

So I am not sure why they behave differently. @krwq owns this area, maybe he knows.

**Comment by danmosemsft** [comment]
Looks like Desktop framework has the same behavior also.

**Comment by danmosemsft** [comment]
cc @tarekgh

**Comment by tarekgh** [comment]
The default long date format we are getting from the OS (which originally came from CLDR) having 
```
    'den 'd MMMM yyyy HH:mm:ss
```

den is not the day of week. it is just mean "day" in English. so what you are getting is correct. If you want to get the day of week in your formatting, you may choose one of the formats returned by '''C# CultureInfo("sv-SE").DateTimeFormat.GetAllDateTimePatterns()``` which contains "dddd" something like the following 

```
dddd' den 'd MMMM yyyy HH:mm:ss
```

What we use is the first full format we are getting from CLDR/OS. if you don't like that you may suggest that to CLDR.

I am going to close the issue but feel free to reply back with any question.

**Comment by danmosemsft** [comment]
Thanks @tarekgh 	. When I looked at http://demo.icu-project.org/icu-bin/locexp?d_=en&_=sv_SE to find this pattern, was I looking in the wrong place? I don't see "den" there.

**Comment by tarekgh** [comment]
you may look at https://www.unicode.org/cldr/charts/22.1/summary/sv.html and search for ```date-full``` and you'll see, 

```
'den' d:'e' MMMM y
```

note that this raw format just get translated to something match what Windows/.NET use (e.g. y in there is yyyy for us).
Also note that link I pasted is for sv which is the parent of sv-SE. but sv-SE just inherit the properties from sv http://www.unicode.org/cldr/charts/22.1/summary/sv_SE.html.

**Comment by danmosemsft** [comment]
OK thanks good to know.

**Comment by haukurmar** [comment]
> The default long date format we are getting from the OS (which originally came from CLDR) having
> 
> ```
>     'den 'd MMMM yyyy HH:mm:ss
> ```
> den is not the day of week. it is just mean "day" in English. so what you are getting is correct. If you want to get the day of week in your formatting, you may choose one of the formats returned by
> 
> ```cs
> CultureInfo("sv-SE").DateTimeFormat.GetAllDateTimePatterns()
> ```
> 
> which contains "dddd" something like the following
> 
> ```
> dddd' den 'd MMMM yyyy HH:mm:ss
> ```
> What we use is the first full format we are getting from CLDR/OS. if you don't like that you may suggest that to CLDR.
> 
> I am going to close the issue but feel free to reply back with any question.

Exactly the point, "den" is not the day of the week. But in other UI cultures, the name of the day is returned when asked to format using the shorthands .ToString("D", seCulture).

So the question is still unanswered, Why are other cultures returning the name of day but not the swedish one?

**Comment by tarekgh** [comment]
> So the question is still unanswered, Why are other cultures returning the name of day but not the swedish one?

I already answered that in my comment:

```
What we use is the first full format we are getting from CLDR/OS. if you don't like that you may suggest that to CLDR.
```

please let me know if this answer is not clear. thanks.
