### ISSUE TITLE
CookieContainer memory leak

### ISSUE THREAD

**Issue by wdrobinson** [dotnet/corefx#33712]
I'm seeing a small memory leak coupled with gradual CPU usage increase over time in an app that is using static HttpClient to regularly hit distinct urls that return set-cookie headers. These issues are solved by setting UseCookies = false on HttpClientHandler. That led me to investigate CookieContainer and I noticed that it maintains a hashtable (m_domaintable) of domains and for each domain it maintains a sorted list of paths (m_list). So even though cookies are correctly removed based on Capacity and PerDomainCapacity, memory and cpu usage grow over time as m_domaintable/m_list grow with each new domain/path that is hit. There are some examples below that show the memory leak.

First example: add a cookie for many distinct domains

```c#
var cookieContainer = new CookieContainer();
for (int i = 0; i < 10000; i++)
{
    cookieContainer.Add(new Cookie("name1", "value1", "/", $"test{i}.com"));
}
```
Second example: add a cookie for the same domain with different paths

```c#
var cookieContainer = new CookieContainer();
for (int i = 0; i < 10000; i++)
{
    cookieContainer.Add(new Cookie("name1", "value1", $"/{i}", "test.com"));
}
```
Is there something I'm missing here in my usage of HttpClient/HttpClientHandler/CookieContainer? The documentation states that HttpClient should re-used throughout the life of an application but that means that CookieContainer will also be re-used and these collections will continue to grow.

**Comment by caesar1995** [comment]
> So even though cookies are correctly removed based on Capacity and PerDomainCapacity, memory and cpu usage grow over time as m_domaintable/m_list grow with each new domain/path that is hit.

This sounds like a issue need to be addressed.

**Comment by caesar1995** [comment]
It also worth checking that if any expired Cookie is correctly removed from `m_domaintable/m_list`.

**Comment by karelz** [comment]
@caesar1995 do you understand the fix direction enough to make it up-for-grabs? Or does it still need non-trivial analysis and design how to fix it?

**Comment by caesar1995** [comment]
I will take this issue and fix it sometime this week.
