### ISSUE TITLE
MissingMethodException when referencing to netfx binary using File/Directory static methods with ACL types 

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#33719]
(Filing bugs from my notes after customer visit exploring porting large WPF app to .NET core 3)

I think this was probably discussed before, but I can't find an existing issue with a conclusion.

There are static methods on System.IO.File/System.IO.Directory that take FileSecurity/DirectorySecurity

Examples:
https://apisof.net/catalog/System.IO.Directory.CreateDirectory(String,DirectorySecurity)
https://apisof.net/catalog/System.IO.File.Create(String,Int32,FileOptions,FileSecurity)

These have alternatives in .NET Core as extension methods on FileInfo/DirectoryInfo. However, if you're using a netfx binary that calls these methods and can't recompile it to use the extensions, then you get MissingMethodException at runtime. I understand the layering reasoning for this, but should we consider a capability API + PlatformNotSupportedException and bring these back to maximize compatibility with existing binaries?

cc @terrajobst @karelz

**Comment by danmosemsft** [comment]
This is tracked in https://github.com/dotnet/corefx/issues/31488

**Comment by JeremyKuhne** [comment]
The type closure that would need to go down to CoreLib (with `FileStream`) is broader than we want, so we're not planning to add back the previous API, but we intend to add replacements with #41614.

**Comment by nguerrera** [comment]
So just to reiterate: This issue will not be fixed. Existing .NET Framework libraries that call these API need to be recompiled to work on Core or there will be MissingMethodExceptions as reported here.
