### ISSUE TITLE
Allow recovering writable/heapable buffers from "lower level" types.

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#33717]
Thanks to @ChadNedzlek for the "why can't you?" as a followup to the "how many copies of this?" do we need from  #31011 and #26528:

The general idea is that when using utility methods that "downcast" from Memory toward ReadOnlySpan, a caller can recover their writable (and/or heapable) needs operating on the same memory range.  This means that for cases where writable doesn't feel very common (or heapable doesn't feel very common) the caller has a common "how do I slice my original data to match?" escape valve; and frameworks can fill in the {ReadOnly|}{Memory|Span} matrix as needed by scenario usage (for the places that the performance memory.Span twice is unacceptable).

```C#
public partial struct Span<T>
{
    /// <summary>
    /// Get a slice of this (writable) span which has the same start and length as a
    /// contained readonly span.
    /// </summary>
    /// <remarks>
    /// If containedSpan is empty, the behavior is the same as Slice(0, 0).
    /// </remarks>
    /// <exception cref="ArgumentOutOfRangeException">containedSpan is not a sub-span of this span</exception>
    public Span<T> SliceTo(ReadOnlySpan<T> containedSpan);
}

public partial struct ReadOnlyMemory<T>
{
    /// <summary>
    /// Get a slice of this memory which has the same start and length as a span over the
    /// same memory
    /// </summary>
    /// <remarks>
    /// If containedSpan is empty, the behavior is the same as Slice(0, 0).
    /// </remarks>
    /// <exception cref="ArgumentOutOfRangeException">
    /// containedSpan is not a sub-span of this span
    /// </exception>
    public ReadOnlyMemory<T> SliceTo(ReadOnlySpan<T> containedSpan);
}

public partial struct Memory<T>
{
    /// <summary>
    /// Get a slice of this memory which has the same start and length as a span
    /// over the same memory
    /// </summary>
    /// <remarks>
    /// If containedSpan is empty, the behavior is the same as Slice(0, 0).
    /// </remarks>
    /// <exception cref="ArgumentOutOfRangeException">containedSpan is
    /// not a sub-span of this span</exception>
    public Memory<T> SliceTo(ReadOnlySpan<T> containedSpan);

    /// <summary>
    /// Get a slice of this (writable) memory which has the same start and length
    /// as a contained readonly memory.
    /// </summary>
    /// <remarks>
    /// If containedSpan is empty, the behavior is the same as Slice(0, 0).
    /// </remarks>
    /// <exception cref="ArgumentOutOfRangeException">containedSpan is
    /// not a sub-span of this span</exception>
    public Memory<T> SliceTo(ReadOnlyMemory<T> containedSpan);
}
```

Sample usage for Split:

```C#
Span<byte> data = ...;

foreach (ReadOnlySpan<byte> segment in ((ReadOnlySpan<byte>)data).Split(0xFF))
{
    Span<byte> writableSegment = data.SliceTo(segment);
    writableSegment.Clear();
}
```

CC: @stephentoub @GrabYourPitchforks @terrajobst @ahsonkhan @KrzysztofCwalina

**Comment by GrabYourPitchforks** [comment]
Do we really need the `Memory<T>.SliceTo(ROM<T>)` overload? Presumably we can accomplish the same thing via the `ROS<T>` overload: `var memory = memory.SliceTo(otherMemory.Span);`'.

In person I had previously stated that we should require `this._object` and `other._object` have referential equality, but upon further reflection I don't think that's necessary. The `ROS<T>` overload can never enforce such a requirement regardless, so for symmetry the `ROM<T>` overload also shouldn't enforce that requirement.

**Comment by bartonjs** [comment]
> Do we really need the `Memory<T>.SliceTo(ROM<T>)` overload? 

AFAIK: VB can't say the word Span, so yeah.  Plus, it could (but maybe won't be) be more optimal than deferring to Span.

**Comment by ahsonkhan** [comment]
> Sample usage for Split

I am not sure I understand the sample. We don't have an `AsReadOnly()` API on `Span<T>`. And what are we `foreaching` over?

**Comment by ahsonkhan** [comment]
@cdmihai, I would love to hear what you think of such an API given your previous porting effort/feedback such as https://github.com/dotnet/corefx/issues/31525#issuecomment-442143768

Would such an API help reduce the interchangeability burden between ROM and ROS for your scenario?

**Comment by bartonjs** [comment]
@ahsonkhan Fixed the `AsReadOnly()` to a cast, and corrected my finger-brain "Slice" to "Split".

The readonly-ness is because Split is only being defined over ReadOnlySpan, so it had to be converted for extension invocation.  (I could have called the method statically, but that'd require remembering where it was going to end up :smile:)

**Comment by cdmihai** [comment]
> Would such an API help reduce the interchangeability burden between ROM and ROS for your scenario?

Not dramatically, but would be useful to have. In msbuild's scenario, we start with a big string and then we parse it down to many small parts (slicing, splitting, trimming). So we don't have a one to one mapping between input string/memory and output span, but one string/memory to many atomic parts represented as spans. Along the way, many of these small spans either need to get stored in some heap based object model, or need to be stringified to get sent to .net reflection APIs (the big input string has some pseudo c# parts which get interpreted via reflection). One of the most common needs here is to address string / memory dictionaries and sets via a Span. Most of the atomic parts are reoccurring, so the ability to cache Span.ToString via some lookup table would be awesome (hence the need for addressing hash based string collections).

**Comment by bartonjs** [comment]
@cdmihai Theoretically this would help with a dictionary; in that you could use the `ReadOnlyMemory<char>` as the key; and after getting back a `ReadOnlySpan<char>` from an operation on the string you could take the bigger `ReadOnlyMemory<char>` and `s_table[bigMem.SliceTo(span)]` (though that wouldn't work if the span was something newly allocated, and not a slice of the big string).

**Comment by terrajobst** [comment]
The operation seems rare while `Slice` is very common, which seems unfortunate.

Options:

* **Make this a static helper**. We don't have a great type for that (`MemoryExtension` only houses extension methods and `MemoryMarshal` feels like the wrong type as this operation isn't unsafe).
* **Different name**. For example, `bool TryGetBounds(...)`.

We could also just add another set of overloads to overlaps, like:

```C#
namespace System
{
    public static class MemoryExtensions
    {
        // Existing:
        // public static bool Overlaps<T>(this Span<T> span, ReadOnlySpan<T> other);
        // public static bool Overlaps<T>(this Span<T> span, ReadOnlySpan<T> other, out int elementOffset);
        // public static bool Overlaps<T>(this ReadOnlySpan<T> span, ReadOnlySpan<T> other);
        // public static bool Overlaps<T>(this ReadOnlySpan<T> span, ReadOnlySpan<T> other, out int elementOffset);

        // New:
        public static bool Overlaps<T>(this Memory<T> memory, ReadOnlyMemory<T> other);
        public static bool Overlaps<T>(this Memory<T> memory, ReadOnlyMemory<T> other, out int elementOffset);
        public static bool Overlaps<T>(this ReadOnlyMemory<T> memory, ReadOnlyMemory<T> other);
        public static bool Overlaps<T>(this ReadOnlyMemory<T> memory, ReadOnlyMemory<T> other, out int elementOffset);
    }
}
```

@KrzysztofCwalina, any thoughts?

**Comment by ChadNedzlek** [comment]
I think there is a set of `Overlaps<T>(Memory<T> memory, ReadOnlySpan<T> span)` missing, since with only those overloads, there isn't a good way to recover a Memory slice from a ReadOnlySpan (which is the most castable type that someone would make a method return, which is what prompted this suggestion).  It's also a fairly opaque line of code to recover the memory, since, if I'm understanding correctly, one's code would need to be something like `myMemory.Overlaps(someInnerSpan, out int offset) ? myMemory.Slice(offeset, someSpan.Length) : throw new SomeException()`. That's a bit of a mouthful. Though I guess nothing is stopping a customer from writing the clearer extension method themselves as long as we have an appropriate set of Overlaps method.

**Comment by stephentoub** [comment]
> since with only those overloads, there isn't a good way to recover a Memory slice from a ReadOnlySpan (which is the most castable type that someone would make a method return, which is what prompted this suggestion)

You could do that even with the already exposed Overlaps methods, no?
```C#
Memory<T> memory = ...;
ReadOnlySpan<T> span = ...;
bool overlapped = MemoryMarshal.Overlaps(memory.Span, span, out int elementOffset);
...
```

**Comment by ChadNedzlek** [comment]
I hadn't thought about casting the first parameter to a Span to solve it. You're right. Though that makse the line even more exciting.

**Comment by terrajobst** [comment]
@bartonjs 

Should we put this in the 3.0 milestone?

**Comment by terrajobst** [comment]
* `Overlaps<T>()` with memories. We concluded we don't want these overloads. We generally want to poeple to go from memory to span; we also believe they are fast enough. If we ever need them for perf reasons, we can revisit this.

* `SliceTo`. We're unsure whether this API will fix the usability issues of the `Overlap<T>()` methods. For now, we don't think we want this API. However, we might want add a different API that will address these issues and makes working with spans when you need to compare bounds of other values (memories, other span, strings etc) based on how to two other spans relate to each other.
