### ISSUE TITLE
Many MemoryExtensions search APIs null ref when given a null value as input

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/corefx#33710]
Example:

```cs
  public static void Main()
  {
    Span<string> theStrings = new string[1];
    Console.WriteLine(theStrings.IndexOf((string)null));
  }
```

This should return 0, but it instead null refs.

**Comment by ahsonkhan** [comment]
cc @benaadams 

The fix is to either add a null check for the `value` parameter up-front or use something like EqualityComparer.Default instead of .Equals.

**Comment by benaadams** [comment]
The methods do have a test
```csharp
if (valueLength == 0)
    return 0;  // A zero-length sequence is always treated as "found" at the start of the search space.
```
And `string.AsSpan` return default if null
```csharp
public static ReadOnlySpan<char> AsSpan(this string text)
{
    if (text == null)
        return default;
```
So the pieces should all be there; just need to find out what's throwing the null ref

**Comment by benaadams** [comment]
Ah, different path, its `IndexOf<T>(ref T searchSpace, T value, int length)` where `value` is null

**Comment by benaadams** [comment]
> The fix is to either add a null check for the `value` parameter up-front

Wouldn't help for 
```csharp
static void Main(string[] args)
{
    Span<string> theStrings = new string[] { "1", null, "2" };
    Console.WriteLine(theStrings.IndexOf((string)null));
}
```
Which should return 1

>  or use something like EqualityComparer.Default instead of .Equals.

This might be best?

**Comment by benaadams** [comment]
Aside: might be a problem for the out-of-box ReadOnlySpan/Span as the source has been removed?

**Comment by benaadams** [comment]
Aside: might be a problem for the out-of-box ReadOnlySpan/Span as are the packages generated anymore?

**Comment by benaadams** [comment]
> The fix is to either add a null check for the `value` parameter up-front

Wouldn't help for 
```csharp
static void Main(string[] args)
{
    Span<string> theStrings = new string[] { "1", null, "2" };
    Console.WriteLine(theStrings.IndexOf((string)null));
}
```
Which should return 1

>  or use something like EqualityComparer.Default instead of .Equals.

Wouldn't devitalise for reference types though, so would be slower for ref types. Might be best rather than:
```csharp
value.Equals(Unsafe.Add(ref searchSpace, index + 0))
```
to reverse it and have
```csharp
Unsafe.Add(ref searchSpace, index + 0)?.Equals(value) ?? value is null
```

**Comment by benaadams** [comment]
Hmm, you might be right, an upfront check and then a sequence of null checks? Since they are unrolled

**Comment by jkotas** [comment]
Need to add tests

**Comment by karelz** [comment]
@Jozkee another one for you ...

**Comment by Anipik** [comment]
I actually did this morning. sorry I forget to assign.
https://github.com/dotnet/corefx/pull/38468.
