### ISSUE TITLE
Ensure that new projects/APIs are documented and the relevant intellisense files are updated

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#33729]
We've introduced a couple of new projects (such as `System.Runtime.Intrinsics` and `System.Numerics.Tensors`) as well as several new APIs across the board.

We should ensure that the relevant IntelliSense files are updated and included in the `Microsoft.Private.Intellisense` package to ensure that our nupkg ship with up-to-date IntelliSense/Documentation.

**Comment by tannergooding** [comment]
CC. @eerhardt, @ericstj, @ahsonkhan

**Comment by tannergooding** [comment]
This would let us get rid of the workaround we added in https://github.com/dotnet/corefx/pull/33723#discussion_r237209555 for `System.Numerics.Tensors`

**Comment by eerhardt** [comment]
I'm not entirely certain that OOB packages (like `System.Numerics.Tensors`) should have its xml doc files shipped in `Microsoft.Private.Intellisense`.

We may want to ship `System.Numerics.Tensors` at a different cadence than the framework itself. It makes more sense that the .xml doc should be contained in the `System.Numerics.Tensors` with the matching code and versioned with it.

**Comment by tannergooding** [comment]
`Microsoft.Private.Intellisense` doesn't itself ship, it just contains the most up-to-date version of the docs and is consumed at build-time to get the xml file included in the nuget package.

**Comment by danmosemsft** [comment]
System.Numerics.Tensors is not shipping (at least not on the 3.0 schedule). Is there any 3.0 work here? If not let's close it out.

**Comment by tannergooding** [comment]
This is really more of a `meta` issue that is tracking adding docs in general. I think it is likely better tracked by the internal list that @carlossanlop was working on.
