### ISSUE TITLE
Clean up netstandard build configurations from System.IO.Compression.Brotli tests and common compression tests

### ISSUE THREAD

**Issue by Marv51** [dotnet/corefx#33733]
This is a follow-up issue for PR #33345, specifically to address this [comment](https://github.com/dotnet/corefx/pull/33345#pullrequestreview-174506575)

The main goal is to remove the `STREAM_MEMORY_OVERLOADS_AVAILABLE` constant from the Brotli Tests and then the ifs for that constant.

**Comment by carlossanlop** [comment]
Triage:
@ericstj will help double check this.
