### ISSUE TITLE
Module not found exception when calling CounterSample.Calculate() from Windows Compatiblity Pack in .net core 2.1

### ISSUE THREAD

**Issue by Macromullet** [dotnet/corefx#33744]
I was told here:
https://developercommunity.visualstudio.com/content/problem/310772/module-not-found-exception-when-calling-countersam.html?childToView=394219#comment-394219

To repost the issue here.
When using CounterSample.Calculate in from .net core 2.1, it fails when using CounterSample.Calculate in System.Diagnostics.PerformanceCounter.dll version 4.5.0.0. It appears it is due to it trying to load perfcounter.dll from the .net installation directory, vs the windows installation directory. Because of this, it's unable to load the perfcounter file and invoke the win32 method.

```
System.ComponentModel.Win32Exception HResult=0x80004005 Message=The specified module could not be found Source=System.Diagnostics.PerformanceCounter StackTrace:
at System.Diagnostics.CounterSampleCalculator.LoadPerfCounterDll()
at System.Diagnostics.CounterSampleCalculator.ComputeCounterValue(CounterSample oldSample, CounterSample newSample)
at System.Diagnostics.CounterSample.Calculate(CounterSample counterSample, CounterSample nextCounterSample) at
```

The source of the issue is that perfcounter.dll is supposed to load from the framework directory, and "." is passed into the method SharedUtils.GetLatestBuildDllDirectory(".")

In turn, GetLatestBuildDirectory then uses that argument of "." to open the registry using RegistryKey.OpenRemoteBaseKey(-2147483646, machineName);

However, if the network registry service is NOT started, then OpenRemoteBaseKey of "." fails because "." represents the loopback and it tries to interact using the remote registry service. That causes an exception which is blindly caught in a catch() block, obfuscating the true error and returning "" as the result of GetLatestBuildDirectory(). That in turn then causes downstream problems because it does a path concat on that and yields a nonsense result for the location of perfcounter.dll.

My suggestion is to not pass in ".", but pass in null, and then make GetLatestBuildDllDirectory intelligent so that it uses OpenBaseKey vs OpenRemoteBaseKey when machineName is null.

**Comment by SebastienLorrain** [comment]
Hi,

Is there a workaround for this? (such as manually including the DLL in the app folder)

This is happening on .Net Core 2.2.2 right now

**Comment by Macromullet** [comment]
I ended up just rewriting the calculate method in c#. It’s not super difficult and the algorithms are on MSDN. I tested by running the calculate through my code and the other assembly side by side.

**Comment by danmosemsft** [comment]
@Macromullet @SebastienLorrain either of you interested in offering a PR?

**Comment by SebastienLorrain** [comment]
While taking the sources and trying to provide a PR, I just realised that this means that System.Diagnostics.PerformanceCounter.dll, which is now supposed to be .Net Standard-compatible, still has a need for PerfCounter.dll which is part of .NET Framework.

So... in case someone is using Nanoserver on Docker (which is my case), with no .NET Framework, I guess this is never going to work?

**Comment by SebastienLorrain** [comment]
The original problem has been fixed by @Anipik as part of https://github.com/dotnet/corefx/pull/29009

Currently fixed in master branch but not merged in 2.2.

@danmosemsft : Did I miss something regarding the hard dependency to .NET Framework?

**Comment by danmosemsft** [comment]
@Anipik can you answer the question about the dependency?

**Comment by Anipik** [comment]
> So... in case someone is using Nanoserver on Docker (which is my case), with no .NET Framework, I guess this is never going to work?

yes perfcounter.dll is required for perf counters to work. yes they wont work on NanoServers. Its similar to ```EventLogMessages.dll``` which is required to parse event log messages but is not shipped as a part of .netcore.

@danmosemsft  it seems like System.Diagnostics.PerformanceCounter.dll is netstandard compatible https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.PerformanceCounter/src/Configurations.props#L5. but the code in this assembly is windows specific like loading counters from registry. do we ship this assembly for unix ?

**Comment by Macromullet** [comment]
To be clear, this really shouldn’t be part of .net core but the Windows Compatibility Pack. It’s too platform specific currently to be part of the .net core platform I think. However if all you are doing is calling something like Compute(), it’s not hard to implement in code. I think it took me about 30 minutes to an hour. All the algorithms have one to two numeric components and a time component. From there it’s easy to do lots of computations like x1-x0/t1-t0 (dx/dt) or rate of change over time, or (x1-x0)/(y1-y0) for things like delta bytes/delta io

**Comment by Macromullet** [comment]
Also, the registry based counter collection had a number of issues. I really wish Microsoft would include a managed version of PDH. Too many competing priorities I fear.

**Comment by Anipik** [comment]
@Macromullet feel free to throw an api proposal for any new api/assemblies you wish to add.
