### ISSUE TITLE
ProductInfoHeaderValue does not parse browser user agent strings

### ISSUE THREAD

**Issue by jijiechen** [dotnet/corefx#33742]
The class 'System.Net.Http.Headers.ProductInfoHeaderValue' does not parse a typical browser's user agent string. 

Consider following code:
```cs
var request = new HttpRequestMessage(HttpMethod.Post,"https://someurl");
request.Headers.UserAgent.Add(ProductInfoHeaderValue.Parse(
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36"));
request.Content = new StringContent(postBody, Encoding.ASCII, "application/x-www-form-urlencoded");
```

At line 2, an `System.FormatException` was thrown when I tried it. This is not an expected behavior since it's normal for people to compose UserAgent string from existing browsers.
The exception thrown was:

```
System.FormatException : The format of value '(Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36' is invalid.
``` 

For more information, just refer to this thread:
https://www.reddit.com/r/redditdev/comments/4s8ak2/please_help_me_change_the_useragent_of_an/

**Comment by davidsh** [comment]
In cases like this, you should use the other methods to add the headers manually:

```c#
request.Headers.TryAddWithoutValidation("User-Agent",  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36");
```

**Comment by karelz** [comment]
@davidsh's solution should be acceptable. No need to make other changes as this is corner case scenario.
