### ISSUE TITLE
Build: how do i force build a package?

### ISSUE THREAD

**Issue by Wraith2** [dotnet/corefx#33740]
I need to force regeneration of a specific package to use it in external tests. The only way I can currently see to force package generation is to use `clean` then `build -allconfigurations` which is slow and does a lot of work I don't need. How can I do this?

**Comment by karelz** [comment]
I would expect that rebuild in pkg directory is sufficient. Is that not the case?
cc @wtgodbe @ericstj

**Comment by wtgodbe** [comment]
You can run `dotnet msbuild` on the .pkgproj in question - e.g. https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Pkcs/pkg/System.Security.Cryptography.Pkcs.pkgproj, or https://github.com/dotnet/corefx/blob/master/src/packages.builds to rebuild all packages that were part of the current build

**Comment by Wraith2** [comment]
Ok, that seems to work. Why does the package not get build with everything else?

**Comment by wtgodbe** [comment]
Which package are you trying to build? By default, CoreFx only builds the packages in the `pkg` directory. We build library packages only if you run `build.cmd -allconfigurations` - https://github.com/dotnet/corefx/blob/master/src/packages.builds.

**Comment by Wraith2** [comment]
SqlClient, which builds with msbuild now I know that's how to do it. I just think it might be helpful if you do build -Debug if those packages were build, I can quite see how you might not want a apackage build if you're working on a specific subdirectory but a whole configuration?

**Comment by wtgodbe** [comment]
The library packages are Out-of-band and generally only ship in releases where they've had a change, whereas the libraries without `.pkgproj`'s are part of the framework & always ship in `Microsoft.NetCore.App`. So by default we don't build the OOB packages, unless there's been a change to the source code for those packages.

**Comment by Wraith2** [comment]
ok, thanks.
