### ISSUE TITLE
client certificate not sent by HttpClientHandler using .NET Core

### ISSUE THREAD

**Issue by denadr** [dotnet/corefx#33753]
Hi,

I'm facing a similar issue like https://github.com/dotnet/corefx/issues/33651.

Based on this issue I created a [minimal Repro solution](https://github.com/denadr/CertAuth).
It contains a .NET Core (2.1) Console client and an ASP.NET Core (2.1) API server.

I created the development certificate using PowerShell
```
New-SelfSignedCertificate -certstorelocation cert:\localmachine\my -dnsname localhost
```
and attached it to the repo in the root folder.

Once installed, the client successfully reads the certificate from the store. But I cannot find the certificate in the request object (in the server middleware).

I also collected data during repro using PerfView. You can download the PerfViewData.etl file from [here](https://brightskies-my.sharepoint.com/:u:/g/personal/dadrians_bright-skies_de/EXCO77qKjS1Hu0RC1yYC3tIBnP83oCsILgg3Va-t2gL3XA?e=LhLRkb) (file was too large for the git repo).

Any help would be really appreciated :)
Please let me know if you need further information!

**Comment by denadr** [comment]
Thanks for the quick reply!

I'll try that and come back to you in a few hours.

**Comment by caesar1995** [comment]
@denadr Any updates?

**Comment by davidsh** [comment]
Closing for now since there is no actionable information.
