### ISSUE TITLE
Suggestion: Allow custom ValidationResult in CustomValidationAttribute

### ISSUE THREAD

**Issue by Liero** [dotnet/corefx#33767]
I want to create custom `ValidationResult` class by deriving from it in order to include some additional information about the error. For example ValidationSeverity (Warning, Error), etc.

However, `CustomValidationAttribute` only allows validation methods that returns `System.ComponentModel.DataAnnotation.ValidationResult`.

E.g.:

```csharp
public class CustomValidator
{
  //this is allowed
  public static ValidationResult Validate(object o) 
    => return new CustomValidationResult(…)

   //this is not allowed, but I think it should be
   public static CustomValidationResult ValidateCustom(object o) ...
}
```

See:
https://github.com/dotnet/corefx/pull/33766

**Comment by ajcvickers** [comment]
@Liero This is not something we plan to implement. However, we would consider a community PR. Keep in mind that it must be 100% non-breaking to existing code.

**Comment by Liero** [comment]
I will do PR. To which branch should I request, please?

**Comment by ajcvickers** [comment]
@karelz @danmosemsft Which branch should be targeted by community PRs?

**Comment by Wraith2** [comment]
As far as I know everything should be against master and can then be backported to other branches as needed.

**Comment by karelz** [comment]
Always use master for everything.
Of course you can ask someone to help you port PRs to other branches, assuming you want them there - you have to fight for them in shiproom after all. The key point is that each PR has to be first in master before it can be considered to backporting to servicing branches. Normal internal bar for servicing .NET Core applies (even for community contributions to release branches).

Does it help?

@ajcvickers why is it closed? If it is something we would take, we should keep it open and set milestone to Future + up-for-grabs (if you have guidance what to do).
If you are sure you will never ever do it, then closing is fine. If it is just too far out, I'd recommend to keep it opened + milestone:Future (aka no commitment).

**Comment by ajcvickers** [comment]
@karelz That would be a misuse of both the milestone and the up-for-grabs label. The up-for-grabs label means that this is a good entry-level issue for somebody to work on. It does not in any way indicate whether or not we will work on it. Also, the lack of this label doesn't mean that we wouldn't take a contribution for it, just that it's not an easy first issue.

The milestone indicates when something is planned to be worked on. Putting the issue in the Future milestone means we are planning that somebody at some point in the future will get to this issue and work on it. This is not the case here. This issue will _never_ be implemented by us because it's simply not high enough priority. The only chance it will get done is if somebody in the community wants to work on it.

**Comment by Liero** [comment]
I was able to build the repo using build.cmd and the solution using dotnet msbuild, but I was not able to run the tests.

Visual Studio 2019 Preview 2.2 says:

> Error	CS0006	Metadata file 'C:\Projects\Microsoft\corefx\src\System.ComponentModel.Annotations\tests\System' could not be found	System.ComponentModel.Annotations.Tests	C:\Projects\Microsoft\corefx\src\System.ComponentModel.Annotations\tests\CSC	1	


and the documentation seems to be outdated, because it refers to `build-test.cmd` which is not in the repo. Sorry, it is my first PR

**Comment by Liero** [comment]
@ajcvickers: I would like to get this very small change to single line of code to .NET Core 3 release. All tests passed, no breaking change. How do I fight for it? You are the area owner, right? :)

**Comment by ajcvickers** [comment]
@Liero No need to fight for it. Thanks for submitting the PR--I'll take a look.

**Comment by ajcvickers** [comment]
Fixed by community PR for .NET Core 3.0. Thanks @Liero!
