### ISSUE TITLE
Provide an API for skipping definite assignment

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#33768]
### Rationale

C# currently has very strict definite assignment rules and no built-in understanding of things like `explicit` struct layout This means that the compiler requires you to initialize every field before use, even if the fields overlap in memory.

C# will currently elide the definite assignment checks if you take the address of a given struct. However, this requires you to pin the struct which is not always possible and not always efficient. C# also elides the definite assignment checks if you pass the parameter as an `out` parameter, as C# semantics require all `out` variables to be initialized by the callee.

As such, I propose we add a new API to `System.Runtime.CompilerServices.Unsafe` that allows the user to bypass definite assignment checks.

### Proposed API

```csharp
namespace System.Runtime.CompilerServices
{
     public static partial class Unsafe
    {
        public static void SkipInit<T>(out T value)
        {
            // Implemented in IL, does nothing
        }
    }
}
```

### Example Usage

```csharp
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit)]
public struct D3D12_DEPTH_STENCIL_VIEW_DESC
{
    [FieldOffset(0)]
    public DXGI_FORMAT Format;

    [FieldOffset(4)]
    public D3D12_DSV_DIMENSION ViewDimension;

    [FieldOffset(8)]
    public D3D12_DSV_FLAGS Flags;

    [FieldOffset(12)]
    public D3D12_TEX1D_DSV Texture1D;

    [FieldOffset(12)]
    public D3D12_TEX1D_ARRAY_DSV Texture1DArray;

    [FieldOffset(12)]
    public D3D12_TEX2D_DSV Texture2D;

    [FieldOffset(12)]
    public D3D12_TEX2D_ARRAY_DSV Texture2DArray;

    [FieldOffset(12)]
    public D3D12_TEX2DMS_DSV Texture2DMS;

    [FieldOffset(12)]
    public D3D12_TEX2DMS_ARRAY_DSV Texture2DMSArray;

    public D3D12_DEPTH_STENCIL_VIEW_DESC(DXGI_FORMAT format, D3D12_DSV_FLAGS flags, D3D12_TEX1D_DSV texture1D)
    {
        // Bypass definite assignment for structs overlapping with `Texture1D`
        Unsafe.SkipInit(out this);

        Format = format;
        ViewDimension = D3D12_DSV_DIMENSION.TEXTURE1D;
        Flags = flags;
        Texture1D = texture1D;
    }
}
```

**Comment by benaadams** [comment]
Could also have a zero version that uses the size rather than the fields? e.g.
```csharp
public static void ZeroInit<T>(out T value)
{
    // Zeros sizeof(T)
}
```

**Comment by GSPP** [comment]
An alternative solution would be to have the JIT optimize this better. What are the current JIT capabilities in this regard?

From my own experiments a while ago the JIT tends to compile struct code very literally. If you do `x.a + x.a` that loads twice. If you do `x.a = 1; x.a = 2;` that stores twice.

Overhauling the JIT in this regard in a thorough way seem attractive for many scenarios and would solve this issue as well.

**Comment by tannergooding** [comment]
Closing this in favor of https://github.com/dotnet/corefx/issues/38585
