### ISSUE TITLE
AsyncIteratorStateMachineAttribute

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#33770]
### Proposal:
```C#
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
    public sealed class AsyncIteratorStateMachineAttribute : StateMachineAttribute
    {
        public AsyncIteratorStateMachineAttribute(Type stateMachineType) : base(stateMachineType)
        {
        }
    }
}
```

### Background:
We currently have these attributes:
- StateMachineAttribute
- AsyncStateMachineAttribute
- IteratorStateMachineAttribute

When a developer writes:
```C#
async Task SomeAsync() { ...; await ...; ... }
```
the actual `SomeAsync` method that's generated is attributed with `AsyncStateMachineAttribute` with a `stateMachineType` that points to the compiler-generated state machine type.

Similarly, when a developer writes:
```C#
IEnumerable<T> SomeIterator<T>() { …; yield return …; … }
```
the actual `SomeIterator` method that's generated is attributed with `IteratorStateMachineAttibute` with a `stateMachineType` that points to the compiler-generated state machine type.

Now that we have async iterators, a developer can write:
```C#
async IAsyncEnumerable<T> SomeAsyncIterator<T>() { …; await …; yield return …; … }
```
and we need to attribute it similarly. We have two options:
1. Use the existing attributes and output both on one method, both pointing to the same generated type, e.g.
```C#
[AsyncStateMachine(typeof(<SomeAsyncIterator>d__60))]
[IteratorStateMachine(typeof(<SomeAsyncIterator>d__60))]
```
2. Introduce a new AsyncIteratorStateMachineAttribute, and just output one attribute on the method, e.g.
```C#
[AsyncIteratorStateMachine(typeof(<SomeAsyncIterator>d__60))]
```

The current preview C# compiler implementation does the former, but the preference is to do the latter, as this is a new kind of state machine and we don't want to confuse existing tools that might be looking for one of the existing attributes.  It also feels cleaner to use a new attribute for a new concept, even though the new concept is related to existing ones.

cc: @MadsTorgersen, @jcouv, @terrajobst

**Comment by steji113** [comment]
@stephentoub the proposed attribute still says `AsyncStateMachineAttribute`. Should that actually be `AsyncIteratorStateMachineAttribute` to match the title of this issue?

**Comment by stephentoub** [comment]
@steji113, fixed, thanks.
