### ISSUE TITLE
System.Runtime.WindowsRuntime.Ui.Xaml package fails on net45

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#33776]
Looks like the targets assume lib is under ref/netstandard1.0 but it is actually under ref/netstandard1.1.

**Comment by jeffschwMSFT** [comment]
Can you elaborate on what scenario is failing?  The original package was targeting 451 as the minimum, but my limited testing did not uncover an issue.

**Comment by ericstj** [comment]
Reference the package from net45 and build.
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net45</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="System.Runtime.WindowsRuntime.Ui.Xaml" Version="4.6.0-preview.18580.3" />
  </ItemGroup>

</Project>

```

build fails with
```
CSC : error CS0006: Metadata file 'C:\Users\ericstj\.nuget\packages\system.runtime.windowsruntime.ui.xaml\4.6.0-preview.18580.3\ref\netstandard1.0\System.Runtime.WindowsRuntime.UI.Xaml.dll' could not be found [F:\scratch\winrtUI\winrtUI.csproj]
```

**Comment by ericstj** [comment]
I'll fix it, it slipped in because package testing was not halting the build.  I'll fix that and fix this while I am at it.
