### ISSUE TITLE
DoEvents of only one object 

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/corefx#33786]
I suggest to add an overload to `Application.DoEvents()` to allow only events of one object such as: `Application.DoEvents(WebBrowser1)`
Can it be done?

**Comment by MohammadHamdyGhanem** [comment]
@stephentoub
If it is a part of win forms, then it will be part of .net core 3.0.

**Comment by stephentoub** [comment]
But not necessarily corefx.  The code for Windows Forms is not in this repo.  If it eventually is, then issues for it could be opened here.  But in the meantime, this is not the right place to raise requests for additional Windows Forms APIs.

Regardless, whether or not such an overload could be done, I don't believe it's a good idea.  Only pumping the events directly associated with a specific control is a sure-fire way to induce deadlocks in an application.

**Comment by karelz** [comment]
Closing as it is in wrong repo. Feel free to create the issue in WinForms repo: https://github.com/dotnet/winforms
However, expect that it may be rejected with the reasoning above.
