### ISSUE TITLE
Problematic version number change 3.0.0-preview1 -> 3.0.0-preview

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#33798]
3.0.0-preview1-xxxx is a higher version number than 3.0.0-preview-xxxx so if 3.0.0-preview1 is installed it is taken in preference to 3.0.0-preview

This is also reflected in the myget feed https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.NETCore.App where it looks like the last update (from looking at the top of the list) was Thu, 01 Nov 2018 16:45:09 GMT

![image](https://user-images.githubusercontent.com/1142958/49344015-c1e7e800-f669-11e8-844e-b5e5c7947cef.png)

Whereas if you scroll back to the Thu, 21 Jun 2018 05:25:02 GMT release then you can see the one before it is the new one for Sun, 02 Dec 2018 17:41:20 GMT

![image](https://user-images.githubusercontent.com/1142958/49344030-feb3df00-f669-11e8-95db-ee15e898916b.png)

**Comment by benaadams** [comment]
> I believe we planned to delete all preview1 packages

Please do :)

**Comment by mmitche** [comment]
We actually unlisted all of these packages.  The myget UI on this view is not helpful tbh.  It shouldn't list the unlisted packages.  You'll notice that if you go to the gallery page for dotnet-core https://dotnet.myget.org/gallery/dotnet-core and type "Microsoft.NetCore.App", the latest reflects what is actually the latest.

**Comment by mmitche** [comment]
I've contacted the myget folks to see what they think about this.  The tough bit is that we can't delete all the old packages without breaking some builds.

**Comment by benaadams** [comment]
It did resolve when I cleared out my nuget cache; though the feed in myget is confusing (showing unlisted packages if that is the case)

**Comment by benaadams** [comment]
Similar problem with the corefx packages but even worse e.g. `System.IO.Pipelines` https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.IO.Pipelines

![image](https://user-images.githubusercontent.com/1142958/49693650-c54f0800-fb70-11e8-82da-16461d228fa4.png)

Whereas the actual newest is much further down

![image](https://user-images.githubusercontent.com/1142958/49693659-021aff00-fb71-11e8-8e6f-20682896ae0b.png)

And the old packages with the higher version numbers are definitely still listed at least as far as VS is concerned

![image](https://user-images.githubusercontent.com/1142958/49693669-52925c80-fb71-11e8-9cbf-239d9626018c.png)

**Comment by khellang** [comment]
I'm not even able to find preview packages of System.Memory from 2019. Are they not being produced, not being produced or just out of retention (because of the versioning errors)?

**Comment by ericstj** [comment]
This was an unfortunate side effect that we made knowingly when @weshaggard switched to Arcade versioning.   We had planned to mitigate it by cleaning up the old packages, but that turned out to be not-possible due to how myget enlisting worked.  Given we are past this bubble in versioning we can close this now.  Next time around we'll try to avoid this (assuming our release PMs don't twist our arm, but at least we'll say NO more strongly next time around).
