### ISSUE TITLE
UriKind.RelativeOrAbsolute and Uri.IsAbsoluteUri

### ISSUE THREAD

**Issue by baulig** [dotnet/corefx#33799]
In Mono, the following test passes:

```
    var uri = new Uri("/dev/null", UriKind.RelativeOrAbsolute);
    Assert.True(uri.IsAbsoluteUri);
```

With CoreFX, it does not.  Is this a bug or a feature?

I ran into this issue when trying to port `System.Net.Http` to Mono - for instance, the [System.Net.Http.Functional.Tests.HttpClientTest. GetAsync_NoBaseAddress_InvalidUri_ThrowsException](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/tests/FunctionalTests/HttpClientTest.cs#L160) will fail, which is essentially the following:

```
    [Theory]
    [InlineData("/something.html")]
    public void GetAsync_NoBaseAddress_InvalidUri_ThrowsException(string uri)
    {
        using (HttpClient client = CreateHttpClient())
        {
            Assert.Throws<InvalidOperationException>(() => { client.GetAsync(new Uri(uri, UriKind.RelativeOrAbsolute)); });
        }
    }
```

In [HttpRequestMessage.InitializeValues](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpRequestMessage.cs#L188), there is the following code:

```
        if ((requestUri != null) && (requestUri.IsAbsoluteUri) && (!HttpUtilities.IsHttpUri(requestUri)))
        {
            throw new ArgumentException(SR.net_http_client_http_baseaddress_required, nameof(requestUri));
        }
```

There are only a handful of tests failing with this

```
    System.Net.Http.Functional.Tests.HttpRequestMessageTest.Ctor_RelativeStringUri_CorrectValues [FAIL]
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpCookieProtocolTests.GetAsyncWithRedirect_ReceiveSetCookie_CookieSent [FAIL]
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpCookieProtocolTests.GetAsyncWithRedirect_SetCookieContainer_CorrectCookiesSent [FAIL]
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientTest.GetAsync_NoBaseAddress_InvalidUri_ThrowsException(uri: "/something.html") [FAIL]
```

Is this something that I need to be worried about - as in there's a chance that something else might break due to this incompatibility - or can I just disable those tests for the moment?

**Comment by davidsh** [comment]
@rmkerr

**Comment by tmds** [comment]
Setting `MONO_URI_DOTNETRELATIVEORABSOLUTE=true` will make mono behave like .NET Framework and .NET Core. The mono behaviour is described here: https://www.mono-project.com/docs/faq/known-issues/urikind-relativeorabsolute/.

**Comment by baulig** [comment]
Any objections against using `UriKind.RelativeOrAbsolute` in those System.Net.Http tests?

**Comment by baulig** [comment]
Okay, looks like we can just pass the environment variable to the test runner to make it work.

**Comment by stephentoub** [comment]
Thanks.
