### ISSUE TITLE
HttpClient should have an IdleTimeout property

### ISSUE THREAD

**Issue by flagoworld** [dotnet/corefx#33845]
Currently, HttpClient only has the Timeout property. This property limits the total execution time of a request, instead of limiting the amount of time a request can sit idle (hanging) before it times out. I propose a property called "IdleTimeout" that gets reset any time a chunk of data is successfully sent up the stream or received from the stream.

## Rationale
Many if not most HTTP libraries define timeout as the period of time a request is allowed to idle before it is closed. Also, implementing it as such is much more useful in practice. See the list below for examples of other implementations:

NSURLConnection: https://developer.apple.com/documentation/foundation/nsmutableurlrequest/1414063-timeoutinterval?language=objc

NSURLRequest:
https://developer.apple.com/documentation/foundation/nsurlrequest/1418229-timeoutinterval?language=objc

XMLHttpRequest.upload:
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/upload

Node's http which, per docs, sets the timeout of the underlying socket when setTimeout is called:
https://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback

Python's requests library:
http://docs.python-requests.org/en/latest/user/quickstart/#timeouts

Perl's LWP:
https://metacpan.org/pod/LWP::UserAgent#timeout

Hyper (a library for Rust):
https://docs.rs/hyper/0.12.16/hyper/client/struct.Builder.html#method.keep_alive_timeout

Java:
https://docs.oracle.com/javame/8.0/api/gcf/api/javax/microedition/io/HttpConnection.html

## Proposed API
```c#
public TimeSpan IdleTimeout { get; set; }
```

## Usage
```c#
var client = new HttpClient();
client.IdleTimeout = TimeSpan.FromSeconds(30);

// All requests made with this client now time out if the underlying socket hangs/idles for >= 30 seconds
```

API proposal created due to issue #33841

**Comment by ayende** [comment]
Is this something that we can send a PR on, or does there need to be additional API review work?

**Comment by flagoworld** [comment]
@ayende  If you need to get something out there without waiting on this fix: You can implement timeouts yourself by passing your own CancellationToken into the request, subclassing HttpContent, and in one of the overrides where data gets streamed/sent you can call cancellationTokenSource.CancelAfter(yourCustomTimeout) each time data gets read from the input stream and written to the output stream. If that makes sense. It's a total hack but it does work.

**Comment by ayende** [comment]
Thanks, we'll check it

**Comment by stephentoub** [comment]
> Is this something that we can send a PR on, or does there need to be additional API review work?

As it's proposed, I don't believe it's viable, e.g. how would HttpClient implement this, given that it's just a layer on top of an arbitrary handler?

**Comment by ayende** [comment]
I can think of a few ways to do that.
It can be a property that the handler checks and use appropriately, or it can be a property on the handler itself.
On the `SocketsHttpHandler`, for example, it would translate to `ReceiveTimeout` and `SendTimeout`

**Comment by stephentoub** [comment]
> It can be a property that the handler checks

On the HttpClient? That doesn't work. The handler doesn't have a reference to the client. In fact the same handler can be used with multiple clients. That's why I said that the proposal as is isn't viable. It would really need to be on the handler.

> On the SocketsHttpHandler, for example, it would translate to ReceiveTimeout and SendTimeout

In spirit, yes. In practice, no. Those properties only apply to synchronous socket operations.

**Comment by karelz** [comment]
Triage: Only 1 vote so far.
This is very expensive to implement (performance impact wise). Unless there is strong need to have this, we don't think it is worth it. Closing for now.
If there are common scenarios and multiple customers impacted, we can reconsider and reopen.
