### ISSUE TITLE
Add NetNamedPipeBinding to Windows Compat Pack

### ISSUE THREAD

**Issue by tirth** [dotnet/corefx#33847]
The only thing preventing our codebase from fully moving to .NET Core is a service out of our control that uses NetNamedPipeBinding. WCF through the compatibility pack currently provides all the other necessary pieces, this one class is the only missing bit. And as it's a base service, all things built on top of it have to run on Framework, even though they would benefit greatly from moving to Core.

Is there any way this class could be added to the compatibility pack?

**Comment by karelz** [comment]
Shouldn't that be part of https://github.com/dotnet/wcf repo?

**Comment by tirth** [comment]
Oh I wasn't sure what the best place was, I can open the issue there instead. Didn't realize WCF was going Core too, I figured it would only be through the compat pack. Thanks!

**Comment by joperezr** [comment]
Issue moved to [dotnet/wcf #3322](https://github.com/dotnet/wcf/issues/3322) via [**ZenHub**](https://www.zenhub.com/)
