### ISSUE TITLE
HttpClient Timeout incorrectly implemented

### ISSUE THREAD

**Issue by flagoworld** [dotnet/corefx#33841]
Timeout should be implemented such that if any TCP packet being sent times out, or no response is received within the Timeout interval, the request times out.

For example:

- Timeout set to 5 seconds
- PostAsync a file that is 100MB
- Okay, we have our stream open and it's sending up data and receiving data back from the server.
- At this point, it is sending data (headers + body) up the stream in chunks, and per TCP spec, each chunk is guaranteed delivery. Until that delivery is confirmed, the next chunk of data is not sent up.
- After all the data is sent up, we would expect to start receiving a response from the server and to see data coming down

What happens:

When uploading that 100MB of data to the server, if it takes longer than Timeout to upload, the task gets canceled as having timed out.

What SHOULD happen, and happens in every other implementation I've used:

Each time a chunk of data is successfully sent up the stream, or a chunk of data is received from the stream, the timeout is reset back to the supplied number (5 seconds in this case). The only time the request should time out is if no data is successfully sent up the stream AND no data is received from the stream for the Timeout interval (5 seconds in this case).

To me this is a pretty huge bug in the implementation and greatly limits what can be done without a silly amount of working around and customization.

Or am I crazy?

**Comment by stephentoub** [comment]
> Each time a chunk of data is successfully sent up the stream, or a chunk of data is received from the stream, the timeout is reset back to the supplied number (5 seconds in this case). The only time the request should time out is if no data is successfully sent up the stream AND no data is received from the stream for the Timeout interval (5 seconds in this case).

It's not a bug. That is not how HttpClient.Timeout is defined, which is the amount of time to wait all-up before the request times out, regardless of whether it's connecting, sending data, receiving data, etc.  There are additional timeouts defined on the underlying handler, though none that conform exactly to the semantics you're requesting.  You're welcome to propose additional APIs, but the current implementation is behaving as intended.

**Comment by stephentoub** [comment]
> And I am proposing that the implementation is incorrect and thus a bug.

I get that you don't like that behavior, but that doesn't make it a bug, nor would it be changed even if we could (which we can't, as the behavior has been around for a very long time, by design).  It's extremely common to want to limit the overall time for a request.

If you'd like to propose a new API, please follow the process outlined at https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md for proposing new APIs.

Thanks.

**Comment by flagoworld** [comment]
Thank you for the swift reply
