### ISSUE TITLE
System.IO.Pipelines thread-safety

### ISSUE THREAD

**Issue by oliverw** [dotnet/corefx#33858]
The documentation for System.IO.Pipelines on docs.microsoft.com is currently quite thin. Therefore my question, is it safe to concurrently write to a PipeWriter from multiple threads?

**Comment by davidfowl** [comment]
It is not. The pipe is single writer, single reader. You need to synchronize access to the pipe writer.

**Comment by oliverw** [comment]
Thanks David. Closing.
