### ISSUE TITLE
WPF and Windows Forms' Repo Isn't Included In PATENTS.TXT 

### ISSUE THREAD

**Issue by CuriousTommy** [dotnet/corefx#33855]
Hello DotNet Developers!

I noticed that the [PATENTS.TXT](https://github.com/dotnet/corefx/blob/master/PATENTS.TXT#L25) file does not include the [Windows Forms](https://github.com/dotnet/winforms) and [WPF](https://github.com/dotnet/wpf) repo. Do you plan to includes these repos in the document or was it intentional to exclude them?

**Comment by jkotas** [comment]
Duplicate of https://github.com/dotnet/wpf/issues/87
