### ISSUE TITLE
SocketsHttpHandler Doesn't Respect Manual Proxy Bypass

### ISSUE THREAD

**Issue by adamrodger** [dotnet/corefx#33866]
## Issue

.Net Core versions tested: `2.1.2`, `2.1.6`, `2.2.0`
OS tested: Windows Server 2016 x64

If your Windows proxy settings are set to:

![image](https://user-images.githubusercontent.com/508586/49593389-5b194600-f96b-11e8-9329-18745a7edd13.png)
![image](https://user-images.githubusercontent.com/508586/49594637-42f6f600-f96e-11e8-8f3e-61156941c109.png)

then `SocketsHttpHandler` doesn't respect proxy bypass preferences.

## Reproduction

- In Internet Options:
  - Tick "Automatically detect settings"
  - Populate the proxy server details at the bottom
  - Click 'Advanced' and add some manual proxy exclusions
- Using a `HttpClient`, request a URL which should match the manual exclusion list.

**Expected result**: The request does not go via the proxy as it matches the bypass list
**Actual Result**: The bypass list is ignored and the request goes via the proxy

## Cause

With the configuration above, `WinInetProxyHelper` has the following properties:

```
WinInetHttpProxyHelper:
        AutoConfigUrl:
        AutoDetect: True
        AutoSettingsUsed: True
        ManualSettingsOnly: False
        Proxy: myproxy.local:8080
        ProxyBypass: localhost;*.local
```

When `WinInetProxyHelper.GetProxyForUrl()` is called, [it fails during auto-detection](https://github.com/dotnet/corefx/blob/0bfc4f3cf62f6fc29162ad5b1b89acc14124a375/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinInetProxyHelper.cs#L164) since there's no PAC file, and then [falls back to the manual proxy settings](https://github.com/dotnet/corefx/blob/0bfc4f3cf62f6fc29162ad5b1b89acc14124a375/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinInetProxyHelper.cs#L179) (in this case `myproxy.local:8080`). The manual settings are then [parsed and returned by `HttpSystemProxy.GetProxy()`](https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpSystemProxy.cs#L338)

 However, `HttpSystemProxy.IsBypassed` [contains an assumption that `HttpSystemProxy.GetProxy()` will have returned `null` when `AutoSettingsUsed` is `true`](https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpSystemProxy.cs#L367), but that assumption is incorrect because the manual fallback settings were returned instead of `null`. This means the URL goes via the proxy even if it matches the bypass list.

## Workaround

You can either:

- Untick "Automatically detect settings" to cause `AutoSettingsUsed` to be `false`, then `HttpSystemProxy.GetProxy()` will actually check the bypass list and return `null` if a bypass matches, or
- Set the environment variable `DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER` to `0` so that [`SocketsHttpHandler` isn't used](https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.Net.Http/src/System/Net/Http/HttpClientHandler.Windows.cs#L37) (which shows that this is a regression from the older `WinHttpHandler` implementation).

The longer term solution should probably be that if auto-detection is enabled but fails, set `AutoSettingsUsed` to false so that the normal manual behaviour is used.

**Comment by rmkerr** [comment]
Thanks for the super detailed report! This should make it a lot easier to track down and fix the issue.

Since you've clearly put a lot of work into understanding what's going on here, do you have any interest in trying to make the fix?

**Comment by adamrodger** [comment]
Hi @rmkerr - I would definitely be interested in fixing it, I've just found it really difficult to actually get the solution built because it's so big and complicated. The way I diagnosed this was actually copying and pasting the relevant code into a new solution of my own to create a little console app that proves the problem... Oh dear 😄 

I'll have another go and let you know if I get anywhere. At the moment, I'm thinking the best way to fix it would be to set `AutoSettingsUsed` to false if it falls back to manual settings

**Comment by adamrodger** [comment]
Well, I've been trying to fix that for 4 hours now and I'm not really much closer. The tests can only be compiled and executed via the CLI instead of in Visual Studio, which means I can't attach a debugger. Because the tests have to do fake interop that makes them very difficult to diagnose without the aid of running the tests via the debugger.

Coupled to that, every time I do build the tests via the CLI, my VS breaks and I have to recompile the whole repo from root again. It's very frustrating!

I have written a test though:

```csharp
[Fact]
public void HttpProxy_FailedAutoDetection_Bypassed()
{
    const string proxy = "myproxy.local";
    const string bypass = "*.local";
    const string dontBypassUri = "http://example.org";
    const string bypassUri = "http://example.local";

    RemoteInvoke((proxyString, bypassString, dontBypassUrlString, bypassUrlString) =>
    {
        // WinInet has "Automatically detect settings" ticked in the Internet Options dialog
        FakeRegistry.WinInetProxySettings.AutoDetect = true;

        // A manual proxy is supplied in the same dialog, with a bypass list
        FakeRegistry.WinInetProxySettings.Proxy = proxyString;
        FakeRegistry.WinInetProxySettings.ProxyBypass = bypass;

        // There is no PAC file to auto-detect
        TestControl.PACFileNotDetectedOnNetwork = true;

        HttpSystemProxy.TryCreate(out IWebProxy webProxy);

        Assert.NotNull(webProxy.GetProxy(dontBypassUri));
        Assert.Null(webProxy.GetProxy(bypassUri));
    }, proxy, bypass, dontBypassUri, bypassUri).Dispose();
}
```

**Comment by rmkerr** [comment]
Glad to hear you're taking a look at it!

I haven't tried debugging the tests in VS recently, so I'm not familiar with that particular issue. If you haven't seen it yet, [the developer guide](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md) contains a ton of useful info, including how to build or run the tests for just a single project.

You may also be able to get help via the [corefx gitter chat room](https://gitter.im/dotnet/corefx). There are a lot of other contributors that check in regularly there, and it's likely someone knows more about the issues you're running into.

**Comment by adamrodger** [comment]
Thanks for that. I'd already read the dev guide but I've not been in the
gitter channel so I'll give that a go. I would like to get it sorted myself
ideally.

I notice the issue has been tagged as version 3.0, is that correct? Just so
I know which branch to base the fix on.

**Comment by rmkerr** [comment]
Yep, 3.0 is correct. Development for 3.0 is currently out of the master branch, so you can just fix it there. There is a precedent for porting this kind of proxy fix back to the LTS releases, but getting it fixed in master is the first step.
