### ISSUE TITLE
[arm32/Linux] System.ServiceModel.Syndication.Tests failures on arm32 linux

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#33875]
Running the arm32 tests on linux for System.ServiceModel.Syndication.Tests produced the following results: passed 1108/1211 tests.

Most of the failures are caused by PlatformNotSupportedExceptions so I believe that they should all be skipped when running in linux arm32.

**Comment by danmosemsft** [comment]
Is it possible to attach the appropriate testResults.xml to these issues? Then they can get fixed without hardware.

**Comment by joperezr** [comment]
[testResults.zip](https://github.com/dotnet/corefx/files/2654991/testResults.zip)

**Comment by yujayee** [comment]
Closing as duplicate of #33993
