### ISSUE TITLE
System.Runtime.InteropServices.RuntimeInformation.get_OSArchitecture() in cross-platform PowerShell module

### ISSUE THREAD

**Issue by rjmholt** [dotnet/corefx#33885]
I'm the maintainer of the [PowerShell language server](https://github.com/PowerShell/PowerShellEditorServices), which is hosted as a cross-platform PowerShell module.

It targets net451 and netstandard1.6 (we have an upstream branch targeting netstandard2.0 we are moving to soon enough). We run on PowerShell v3/4/5.1 with net451 and PowerShell 6.0+ with netstandard1.6.

Because we rely on Windows Compatibility Pack features, we have to [assemble the DLLs manually](https://github.com/PowerShell/PowerShellEditorServices/blob/bb65b2a646167e483c936d2c53db9b3a75ffb6cd/PowerShellEditorServices.build.ps1#L250-L299) for module loading.

We pulled in System.Runtime.InteropServices.RuntimeInformation for a few things, such as checking OSArchitecture but [users on Windows 7 report a crash at startup](https://github.com/PowerShell/vscode-powershell/issues/1633):

```
VERBOSE: Exception calling "StartLogging" with "2" argument(s): "Unable to load DLL 'api-ms-win-core-sysinfo-l1-2-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
Unable to load DLL 'api-ms-win-core-sysinfo-l1-2-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.GetNativeSystemInfo(SYSTEM_INFO& lpSystemInfo)
   at System.Runtime.InteropServices.RuntimeInformation.get_OSArchitecture()
   at Microsoft.PowerShell.EditorServices.Host.EditorServicesHost.StartLogging(String logFilePath, LogLevel logLevel)
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
```

I had a look through the issues and commented [here](https://github.com/dotnet/corefx/issues/13566#issuecomment-444968316), but have now seen this will probably affect [other widely used PowerShell modules](https://github.com/lzybkr/PSReadLine/blob/a878b3686cba23ad39fcd98a6b418c9db0bb77ab/PSReadLine.build.ps1#L226-L233), so I'm opening this issue.

My questions are:

- [This comment](https://github.com/dotnet/corefx/issues/19313#issuecomment-299048329) implies that the native api sets are no longer used in the latest version of System.Runtime.InteropServices.RuntimeInformation. Is that still true? We are pulling in v4.3.0 and hitting what looks like an api set problem. I saw that another dotnet repo [fixed this issue](https://github.com/dotnet/buildtools/pull/1249) by upgrading the package, but to version 4.4.0-beta-24813-03, which is newer than the latest version on Nuget.
- Building for a broad RID or no RID does not pull in the api sets, but building for win7-x64 (for example) does. Is there some higher level mechanism the higher-level RIDs are using instead that I can use?
- Another comment [suggested adding Microsoft.NETCore.Windows.ApiSets](https://github.com/dotnet/corefx/issues/13566#issuecomment-322882746) but I pulled that module both manually and added it to our build and in both cases I couldn't find the api sets DLLs as part of the pulled assets. In the manually pulled package, that seemed to have no DLLs at all in it. Is there something I've missed there for getting the api sets DLLs? Maybe I'm not looking in the right part of the nuget package structure?
- If we do need to fall back to api sets, is there a way to not need to build for specific RIDs like win7-x64? Needing to do that will double the complexity of the PowerShell module we create.

Thanks for your help. I know this is a complex issue. We'd appreciate any help you can offer.

**Comment by danmosemsft** [comment]
Windows apisets don't work down level apparently. I believe that is why we removed all use of Windows apisets in 75e45da8d7104e7f6b737d552bbc332d14211da8. We stopped publishing S.R.IS.RI individually about that time. I guess just before the change above.

I suppose this can be considered a bug in that old package. @ericstj I guess we would recommend moving to NS2.0 (implying .NET Core 2.0) and failing that, get by with the slightly newer package from myget meantime? I guess that one is not signed.

**Comment by ericstj** [comment]
/cc @joperezr 
System.Runtime.InteropServices.RuntimeInformation was absorbed into NETStandard which is why the package stopped being produced.  For desktop this means it started being included inbox in `net471` prior to that it was distributed with MSBuild, in eg in `C:\Program Files (x86)\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net461\lib`.  This version will have the fix.  I checked and we weren't building any differently for net45 vs net461 so it should be safe to use.  I think that's better than relying on a random build from MyGet.

**Comment by jeffschwMSFT** [comment]
@rjmholt were you able to workaround this issue?

**Comment by rjmholt** [comment]
@jeffschwMSFT yeah, we went with something like:

```csharp
bool isNetFramework = typeof(object).Assembly.GetName().Name == "mscorlib"
```

Naturally this is brittle, since other implementations don't guarantee they won't name the core assembly `mscorlib` (and that `object` will come from it), but we picked it since:

- `mscorlib` is highly unlikely to change name in .NET Framework
- Even if .NET Core chooses to rename `System.Private.CoreLib`, we suspected `mscorlib` is an unlikely new name
- We only needed to differentiate between Framework and Core

**Comment by rjmholt** [comment]
However, there doesn't really seem to be a satisfying solution to this problem in general.

It's something that PowerShell requires, since people want to be able to write code that runs both on older PowerShell versions that may be running on .NET 452, on PowerShell 6.2, running on .NET Core 2.2 and eventually on a later release of PowerShell running on .NET Core 3

**Comment by jeffschwMSFT** [comment]
I agree that pattern is brittle.  What sort of runtime decisions are you making based on if it is .NET Framework or .NET Core?  I have seen other people look for certain types that they know are available (eg. AssemblyLoadContext), this pattern is slightly more desirable because the validation is not if they are running in .NET Framework v Core, but rather should a type be used.  Can you do something similar?

cc @danmosemsft

**Comment by rjmholt** [comment]
In the original case, I needed a FIPS-compliant hash algorithm. In .NET Framework, that required passing the name of the algorithm in, whereas in .NET Core that returned `null` and passing no argument was required. So we had something like this:

```csharp
SHA256 fipsCompliantSha256 = isNetCore
    ? SHA256.Create()
    : SHA256.Create("System.Security.Cryptography.SHA256Cng");
```

This was in a case where I didn't own the code -- just trying to make minor compatibility adjustments without breaking things. So doing something like "enabling FIPS mode" (which might be an alternative solution) would likely be too difficult compared to some local changes in .NET code.

**Comment by jeffschwMSFT** [comment]
@rjmholt let me know if you have any further questions.  Closing out this question for now.

**Comment by rjmholt** [comment]
I'm just re-reading this now and realise my response about comparing the assembly name to `mscorlib` was me conflating another issue (where we didn't have `System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription` in `net461`).

We wanted the OS Architecture for logging in the PowerShell extension. When this failed as in the top comment, we did [this](https://github.com/PowerShell/PowerShellEditorServices/blob/dd3287762d9a39af4cdfe6614afab4426ec0b333/src/PowerShellEditorServices.Host/EditorServicesHost.cs#L534-L553).
