### ISSUE TITLE
name collision with type Index added to System namespace

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/corefx#33895]
tag:discussion

We have this very old class that's used all over the place called Index, which is basically a Dictionary that accepts more than one item per key. It's used like a mutable IGrouping and was recently retrofitted to implement IGrouping. It's use is so pervasive that it grew another implementation called SortedIndex which is to Index as SortedDictionary is to Dictionary.

So now we've got literally thousands of files importing System and expecting Index to be ours (in a far namespace), and on upgrading to .NET Core 3 we get a completely ridiculous number of errors.

So now we've got to figure out how to handle this name collision. Trying to rename Index is going to break back-compatibility of our nuget packages all over the place.

(Yes, some parts of our .NET Core codebase are literally 11 years old and I've got the source control trees to prove 9 of them and would have more but for a disk crash.)

**Comment by stephentoub** [comment]
cc: @terrajobst, @tarekgh

**Comment by tarekgh** [comment]
@terrajobst is it possible out Index can be moved to a different namespace?

**Comment by jhudsoncedaron** [comment]
In this case it has its own syntax, so System.Runtime.CompilerServices could be used.

But I said discussion for a reason. Perhaps there's a good way to prioritize imports.

**Comment by terrajobst** [comment]
> In this case it has its own syntax, so System.Runtime.CompilerServices could be used.

`System.Runtime.CompilerServices` is meant for types that you basically never have to use yourself. While'  `Range` and `Index` have language syntax, you still need to use the type name for parameters and return declarations of methods -- they are not like tuples where the language offered syntax for the types. For `Range` and `Index` the language only provides syntax for values. That's why these types belong to the `System` namespace IMHO.

> Perhaps there's a good way to prioritize imports that can be mechanically applied at the file level.

Can you explain what you mean by that?

**Comment by danmosemsft** [comment]
Can you either
1. search and replace (or use Roslyn analyzer) to fully qualify use of your `Index` or
2. insert statement like `using Index = MyNamespace.Index;` at the top of all your files?

**Comment by jhudsoncedaron** [comment]
#2 is probably going to work.

**Comment by terrajobst** [comment]
Can we close this now?
