### ISSUE TITLE
[arm32/Linux] System.Configuration.ConfigurationManager.Tests failures on arm32 linux

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#33890]
Running the arm32 tests on linux for System.Configuration.ConfigurationManager.Tests produced the following results: passed 611/614 tests.

All three tests failed with:
```
System.MissingMethodException : Method not found: 'Void System.Configuration.Internal.IInternalConfigHost.GetRestrictedPermissions(System.Configuration.Internal.IInternalConfigRecord, System.Security.PermissionSet ByRef, Boolean ByRef)'.
```

[testResults.zip](https://github.com/dotnet/corefx/files/2655177/testResults.zip)

**Comment by danmosemsft** [comment]
@joperezr I cannot think of what this could have been. This code has not changed in 2 years. Does it repro?

**Comment by joperezr** [comment]
It doesn't. Closing for now since it didn't repro on the second run.
