### ISSUE TITLE
Consider porting System.Data.SqlServerCe to .NET Core

### ISSUE THREAD

**Issue by divega** [dotnet/corefx#33897]
Creating this issue so that we can gather customer feedback on usage of SQL CE, and to try to figure out its relative priority to simplify the move of existing .NET Framework applications to .NET Core.

At the moment we don't have any concrete plans to do this port, and we haven't figured out feasibility. 

Here are a few questions we would like you to consider answering if you decide to vote (via thumbs up :+1: on this comment) or post your own comments on this issue:

1. Do you own an application that you want to port to .NET Core but find yourself blocked because you cannot use SQL CE? 
2. What version of SQL CE are you using. E.g. 3.5 or 4.0? Why?
4. Have you considered other options, like SQLite (e.g. using Microsoft.Data.Sqlite)?
5. Does your application also depend on the Microsoft Sync framework?
6. Are you using SQL CE directly or through an O/RM? Which one?

**Comment by danmosemsft** [comment]
Thumbs up on the top comment would be great also.

**Comment by ErikEJ** [comment]
I can imagine some desktop app scenarios, where the user uses SQL Compact with ADO.NET or EF 6 or EF Core, where she would like to move to .NET Core.

1: Would a port simply type forward to the .NET Framework implementation?
2: Any way I can help investigate feasibility

**Comment by MarcoRossignoli** [comment]
Personally some app with ver 4.0 throught EF/Dapper, I use sql lite for new projects.

**Comment by ErikEJ** [comment]
Looks like System.Data.SqlServerCe runs fine in a .NET Core 3.0 app (tested with preview6 SDK)

**Comment by PremSha20** [comment]
What is current progress ?

**Comment by ErikEJ** [comment]
Current progress, as stated above is that the current provider works fine with .net Core 3.0 (Windows only)

**Comment by divega** [comment]
@ErikEJ just to make sure, can you confirm the .NET Framework provider work on Windows only? 

I am closing this issue as we don't have plans to port at this time.

**Comment by ErikEJ** [comment]
Yes, it is possible with a little bit of effort to make System.Data.SqlServerCe.dll version 4.0.0.1 work with .NET Core 3.0 (using Private Deployment)

Project file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <Platforms>x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="sqlceca40.dll" />
    <None Remove="sqlcecompact40.dll" />
    <None Remove="sqlceer40EN.dll" />
    <None Remove="sqlceme40.dll" />
    <None Remove="sqlceqp40.dll" />
    <None Remove="sqlcese40.dll" />
    <None Remove="System.Data.SqlServerCe.dll" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="sqlceca40.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="sqlcecompact40.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="sqlceer40EN.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="sqlceme40.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="sqlceqp40.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="sqlcese40.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="System.Data.SqlServerCe.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Security.Permissions" Version="4.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Data.SqlServerCe">
      <HintPath>System.Data.SqlServerCe.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>

```
And app:
```

using System.Data.SqlServerCe;

namespace ConsoleApp8
{
    class Program
    {
        static void Main()
        {
            string connectionString = "Data Source=netcore-sqlce.sdf";

            using SqlCeEngine engine = new SqlCeEngine(connectionString);
            engine.CreateDatabase();

            using SqlCeConnection connection = new SqlCeConnection(connectionString);

            connection.Open();

            using (SqlCeCommand command = connection.CreateCommand())
            {
                command.CommandText = "CREATE TABLE Blogs ( Id INT, Title NVARCHAR(256) )";

                command.ExecuteNonQuery();

                command.CommandText = "SELECT * FROM Blogs";

                command.ExecuteReader();
            }
        }
    }
}

```

**Comment by MohanaselvamJ** [comment]
@ErikEJ , the above solution working fine in Windows Forms (.NET Core 3.0).

Is this also applicable for WPF (.NET Core 3.0) ?

Also, to get these mentioned assemblies  I need to install SQL Compact edition in my machine. 

Is there any NuGet available to achieve without installing SQL Compact ?

**Comment by ErikEJ** [comment]
You need the binaries locally, but the idea is that you include them as content with your app.

Yes, this works with any desktop app (not sure sure about ASP.NET Core)

**Comment by davidjackson148** [comment]
I use SQLServerCe for a WPF application, currently, because it's easier to secure than SQL Lite, but unfortunately, it's holding me back to using Net.4.x. It's still the best local database by far as its easier to distribute. My application users are technical so the easier the install the better.

**Comment by ErikEJ** [comment]
@davidjackson148 but as you can see above, it is already possible to use SQL CE with .NET Core 3

**Comment by aaron-pedigo** [comment]
When porting code to a .NET Core 3 project, VS suggested installing Microsoft.SqlServer.Compact to help resolve SqlCeConnection.  When trying to load my CE 3.5 file, I got a message mentioning that it cannot find an ADO.NET provider of version 8876.  Google searching has led me to believe that is CE 4.  Is there any way to load CE 3.5 files in .NET Core 3?

**Comment by aaron-pedigo-eii** [comment]
When porting code to a .NET Core 3 project, VS suggested installing Microsoft.SqlServer.Compact to help resolve SqlCeConnection. When trying to load my CE 3.5 file, I got a message mentioning that it cannot find an ADO.NET provider of version 8876. Google searching has led me to believe that is CE 4. Is there any way to load CE 3.5 files in .NET Core 3?

**Comment by danmosemsft** [comment]
@aaron-pedigo-eii  this issue is closed so it’s likely to get overlooked. Please open a fresh issue. Maybe in https://github.com/dotnet/SqlClient

**Comment by ErikEJ** [comment]
@aaron-pedigo-eii Being able to use deisgners and using 3.5 at runtime are two very different things. I very much doubt you will be able to do that - why not just move to 4.0?

**Comment by aaron-pedigo-eii** [comment]
@ErikEJ We have several programs that output logs in 3.5 and we also have a custom viewer.  I am trying to port over a log analysis tool over to Core 3.  At a minimum this is letting me know another hurdle we will have when we try to port our other apps over from .NET Framework.
