### ISSUE TITLE
Clean up suppressed XML documentation warnings

### ISSUE THREAD

**Issue by AraHaan** [dotnet/corefx#33934]
On my Pull request 
https://github.com/dotnet/corefx/pull/32934 I suppressed a lot of xml documentation errors including errors for paramiters in the documentations that is not in the method, missing xml documentations for other methods, etc.

Also in Microsoft.VisualBaisic I disabled it because for some reason it wants to write it to "$(OutputPath)$(OutputPath)$(ProjectName)" which makes Windows builds fail.

On System.Diagnostics.Process It seems to make the all build config job and the OSX one fail so those errors need fixed as well before reenabling documentation for that too.

**Comment by AraHaan** [comment]
@danmosemsft wrong label, and milestone from the bot, all because my iPhone messed upand posted the issue.

**Comment by AraHaan** [comment]
yes that is true.

**Comment by danmosemsft** [comment]
Specifically the work here is to fix documentation errors, that is, take a project in 6abb4cd that disables one or more of the warning numbers below, remove the warning-disabling, and fix the issues so the build is clean:
```
 419 WRN_AmbiguousXMLReference
1570 WRN_XMLParseError
1571 WRN_DuplicateParamTag
1572 WRN_UnmatchedParamTag
1574 WRN_BadXMLRef
1580 WRN_BadXMLRefParamType
1581 WRN_BadXMLRefReturnType
1584 WRN_BadXMLRefSyntax
1587 WRN_UnprocessedXMLComment
1589 WRN_FailedInclude
1590 WRN_InvalidInclude
1592 WRN_XMLParseIncludeError
1710 WRN_DuplicateTypeParamTag
1711 WRN_UnmatchedTypeParamTag
1723 WRN_BadXMLRefTypeVar
1734 WRN_UnmatchedParamRefTag
1735 WRN_UnmatchedTypeParamRefTag
```
It is not a goal here to add XML docs for projects that don't have a complete set already, that's these warning numbers:
```
1573 WRN_MissingParamTag
1591 WRN_MissingXMLComment
1712 WRN_MissingTypeParamTag
```
For such cases, we should have a discussion before adding docs. I am not sure we have consensus that we want to add docs to everything in every project.

**Comment by StanislavUshakov** [comment]
Hello. Can I take this? I suppose I can do one project in one commit and include many projects in one pull request if this is acceptable (e.g. I will start with System.ComponentModel.Composition.csproj, thenSystem.ComponentModel.Primitives.csproj ang go on using changed project files from [32934 pull request](https://github.com/dotnet/corefx/pull/32934)

**Comment by AraHaan** [comment]
Can you investigate why the xml docs try to write to the wrong location for Microsoft.VisualBasic too?

**Comment by StanislavUshakov** [comment]
Sure

**Comment by StanislavUshakov** [comment]
I have a question regarding [Microsoft.Win32.SystemEvents](https://github.com/dotnet/corefx/blob/master/src/Microsoft.Win32.SystemEvents/src/Microsoft/Win32/SystemEvents.cs#L457) There is only one XML error:
Unable to include XML fragment 'docs/doc[@for="SystemEvents.CreateBroadcastWindow"]/*' of file 'doc\SystemEvents.uex' -- File not found.
I looked through the solution - there is only one reference to the "SystemEvents.uex" file and the file itself doesn't exist. Should we remove this reference or find the "SystemEvents.uex" file?

**Comment by StanislavUshakov** [comment]
Pushed the first part just to test that everything is ok and not broken.

**Comment by sharwell** [comment]
> Can you investigate why the xml docs try to write to the wrong location for Microsoft.VisualBasic too?

Is it possible it's related to this?

https://github.com/dotnet/sdk/blob/0e4d846e7712f803ae03b04866510223e1d23ea4/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets#L166-L169

**Comment by AraHaan** [comment]
That might be it.

**Comment by StanislavUshakov** [comment]
It wasn't as easy as stated by the label.

Currently we have the following XML doc warnings disabled (PR #34020 ):
1. Warnings **CS1573, CS1591** are disabled **globally** in [Directory.Build.props](https://github.com/dotnet/corefx/blob/master/Directory.Build.props#L480)
2. Warning **CS1589** is disabled on a project elvel in:
-  Microsoft.Win32.SystemEvents.csproj: File 'doc\SystemEvents.uex' is not found
- System.Drawing.Common.csproj: File 'doc\KnownColor.uex' is not found
- System.Drawing.Primitives.csproj: File 'doc\KnownColor.uex' is not found
- System.Private.Xml.csproj: Files 'doc\Infer.uex', 'doc\XmlTypeCode.uex', 'doc\XPathNavigator.uex', 'doc\_Events.uex', 'doc\XmlSchemaObjectCollection.uex', 'doc\IXmlSchemaInfo.uex' are not found
3. Minor fix in [src/Common/src/Microsoft/Win32/SafeHandles/SafeHandleCache.cs](https://github.com/dotnet/corefx/pull/34020/files/ba74cec3638406ebb0ab13d47436c9fcc813b44d..96ed7b9c30c891b4e3dc2b14c8b834b3bdbb1054#diff-6b761bf00fa6ab88ad11a90749c14a6b)

As suggested in [this comment](https://github.com/dotnet/corefx/pull/34020#discussion_r241150388) we should remove global suppression from Directory.Build.props. Should I proceed with this change as a part of this issue and a separate PR?

**Comment by danmosemsft** [comment]
@StanislavUshakov thanks for your PR (which I merged now).

>As suggested in this comment we should remove global suppression from Directory.Build.props. Should I proceed with this change as a part of this issue and a separate PR?

Yes please. Then new libraries will have to be clean from the start. Thanks!

For `doc\KnownColor.uex` I doubt it is valuable, and I don't have it, so I would remove those includes. Same for `doc\SystemEvents.uex`

For 
```xml
        /// <devdoc>
        ///    <para>[To be supplied.]</para>
        /// </devdoc>
```
I guess iti s not useful and we should remove globally.

@krwq for these: `System.Private.Xml.csproj: Files 'doc\Infer.uex', 'doc\XmlTypeCode.uex', 'doc\XPathNavigator.uex', 'doc_Events.uex', 'doc\XmlSchemaObjectCollection.uex', 'doc\IXmlSchemaInfo.uex' are not found ` I do not see them in the .NET Framework sources and suggest to remove the references, do you agree? That means some parts of XML will have no doc comments, but they don't today, and we are unlikely to ever refresh the MSDN docs for XML from the XML sources.

**Comment by StanislavUshakov** [comment]
Thank you for the help.
I will continue to work on it: remove global suppression and remove references to non-existing "*.eux" files.

**Comment by StanislavUshakov** [comment]
In #34232 I removed global suppression from [Directory.Build.props](https://github.com/dotnet/corefx/blob/master/Directory.Build.props#L480).
Currently we have **CS1573** suppressed in the folowing projects:
- CoreFx.Private.TestUtilities
 - Microsoft.Diagnostics.Tracing.EventSource.Redist
 - Microsoft.IO.Redist
 - Microsoft.Win32.Registry
 - System.ComponentModel.Composition
 - System.Data.Common
 - System.Data.SqlClient
 - System.Diagnostics.FileVersionInfo
 - System.Diagnostics.Process
 - System.IO.Compression.ZipFile
 - System.IO.FileSystem
 - System.Net.Http
 - System.Net.Ping
 - System.Net.WebSockets
 - System.Net.WebSockets.Client
 - System.Net.WebSockets.WebSocketProtocol
 - System.Private.Xml
 - System.Reflection.MetadataLoadContext
 - System.Runtime.Serialization.Formatters
 - System.Runtime.WindowsRuntime
 - System.Security.Cryptography.Algorithms
 - System.Security.Cryptography.Cng

**Comment by StanislavUshakov** [comment]
I suggest closing this task and creating a new one (one one per project) for adding new comments.
