### ISSUE TITLE
Review platform specific implementation only assemblies added in this release

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#33944]
For some assemblies we can only include on a single platform if we omit them from the platform manifest. See #33936

**Comment by ericstj** [comment]
If we wanted to support this we'd need to add some way of excluding these from the platform manifest when it is built in core-setup.

**Comment by joperezr** [comment]
I'm not sure I understand what the problem is here. Is the issue that these assemblies don't have a reference assembly so people targeting a specific RID would still not be able to use them?

**Comment by ericstj** [comment]
The problem was that they were being added to the platform manifest, so conflict resolution would *always* remove them from the app layout, however we were *only* providing an implementation on a single platform, so other platforms would get a file-not-found exception.

We need to either:
1. Enforce a consistent set of DLLs in all platforms shared frameworks.
2. Permit an inconsistent set of DLLs, but force the inconsistencies to be omitted from the platform manifest.

**Comment by joperezr** [comment]
Without much context, seems to me that (1) is the best choice, and we can just add a turd DLL for the platforms were we don't have an implementation. Do you have a list of these files?

**Comment by ericstj** [comment]
These are the assemblies which are potentially inconsistent:
https://github.com/dotnet/corefx/blob/94c5f1384c9b6477d164050de964cf6dcf99b2a9/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj#L40-L52

Today we don't enforce a fixed set: maybe we should.

**Comment by danmosemsft** [comment]
@joperezr are you planning on taking this one?

**Comment by joperezr** [comment]
Sure I can take this one.
