### ISSUE TITLE
PNG images with 16bpp aren't supported by libgdiplus

### ISSUE THREAD

**Issue by lennylxx** [dotnet/corefx#33951]
I'm using System.Drawing.Common on Ubuntu, there is exception when loading a 16bit png file.

```
** (process:10021): WARNING **: 17:41:57.195: PNG images with 16bpp aren't supported by libgdiplus.

Unhandled Exception: System.ArgumentException: Image format is unknown.
   at System.Drawing.Bitmap..ctor(String filename, Boolean useIcm)
   at debug.Program.Main(String[] args) in /home/user/debug/Program.cs:line 10
```
**Ubuntu versions:**
OS: Ubuntu 18.04.1 LTS
Kernel: 4.15.0-39-generic x86_64
dotnet: 2.1.500
System.Drawing.Common: 4.6.0-preview.18571.3
libpng16: 1.6.34-1ubuntu0.18.04.1
libgdiplus: 4.2-2

However, there is no exception when I test the same image on CentOS.

**CentOS Versions:**
OS: CentOS 7
Kernel: 3.10.0-514.21.1.el7.x86_64
dotnet: 2.1.500
System.Drawing.Common: 4.6.0-preview.18571.3
libpng: libpng-1.5.13-7.el7_2.x86_64
libgdiplus: libgdiplus-2.10-10.el7.x86_64

Sample code:
```
﻿using System;
using System.Drawing;

namespace debug
{
    class Program
    {
        static void Main(string[] args)
        {
            Bitmap bmp = new Bitmap("16bit_Gray16.png");
            Console.WriteLine(bmp.Height);
        }
    }
}
```
Sample image:
![16bit_gray16](https://user-images.githubusercontent.com/5811576/49724195-b1f08980-fca3-11e8-8506-646dff838475.png)

**Comment by danmosemsft** [comment]
Can you please move to the libgdiplus repo and close this one?
