### ISSUE TITLE
error : Failed to resolve SDK 'Microsoft.NET.Sdk.IL` building clean corefx on mac

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#33953]
Any ideas?
```
git r/Users/hugh/Documents/GitHub/corefx/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.ilproj : warning : System.Runtime.CompilerServices.Unsafe depends on Microsoft.NET.Sdk.IL (>= 3.0.0-preview-27210-01) but Microsoft.NET.Sdk.IL 3.0.0-preview-27210-01 was not found. An approximate best match of Microsoft.NET.Sdk.IL 3.0.0-preview1-26731-07 was resolved.
/Users/hugh/Documents/GitHub/corefx/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.ilproj : error : Failed to resolve SDK 'Microsoft.NET.Sdk.IL'. Package restore was successful but a package with the ID of "Microsoft.NET.Sdk.IL" was not installed.
/Users/hugh/Documents/GitHub/corefx/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.ilproj : error MSB4236: The SDK 'Microsoft.NET.Sdk.IL' specified could not be found.

Build FAILED.

/Users/hugh/Documents/GitHub/corefx/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.ilproj : warning : System.Runtime.CompilerServices.Unsafe depends on Microsoft.NET.Sdk.IL (>= 3.0.0-preview-27210-01) but Microsoft.NET.Sdk.IL 3.0.0-preview-27210-01 was not found. An approximate best match of Microsoft.NET.Sdk.IL 3.0.0-preview1-26731-07 was resolved.
/Users/hugh/Documents/GitHub/corefx/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.ilproj : error : Failed to resolve SDK 'Microsoft.NET.Sdk.IL'. Package restore was successful but a package with the ID of "Microsoft.NET.Sdk.IL" was not installed.
/Users/hugh/Documents/GitHub/corefx/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.ilproj : error MSB4236: The SDK 'Microsoft.NET.Sdk.IL' specified could not be found.
    1 Warning(s)
    2 Error(s)
```

**Comment by danmosemsft** [comment]
@joperezr are you famliar with this package? Clearly the official build succeeds and that's on a clean machine (supposedly). Perhaps the nuget feeds are set up differently. When you are inside the corefx folder @hughbe , what does "nuget sources" list?

**Comment by hughbe** [comment]
Hmmm I deleted my `.nuget` folder and now i get
```
/Users/hugh/Documents/GitHub/corefx/eng/Tools.props(105,63): error MSB4022: The result "" of evaluating the value "$(ArcadeSdkBuildTasksAssembly)" of the "AssemblyFile" attribute in element <UsingTask> is not valid. [/Users/hugh/.nuget/packages/microsoft.dotnet.arcade.sdk/1.0.0-dev.18424.13/tools/Tools.proj]
```

How do I run `nuget sources`?

**Comment by danmosemsft** [comment]
`git clean -fdx` maybe?

**Comment by joperezr** [comment]
mm that is weird, I believe that @tannergooding worked on that sdk but I agree that this seems to be a problem specific to @hughbe 's machine. Can you check and make sure you don't have something out of the ordinary on your NuGet.configs on your machine?

**Comment by ericstj** [comment]
I just hit this on a CI build.  I also noticed an official build hit it today.

**Comment by ericstj** [comment]
Looks like it could be a casing issue: https://github.com/NuGet/Home/issues/7817

**Comment by danmosemsft** [comment]
So we didn't pick up https://github.com/NuGet/NuGet.Client/pull/2734 yet?

**Comment by ericstj** [comment]
I don't see a difference in casing anywhere, but NuGet seems to "to-lower" everything they write, not sure if they to-lower to break themselves.  Would need to see this under the debugger to understand for sure what's going on.  Have a theory on how to repro it.

**Comment by ericstj** [comment]
And to answer your specific question, we do have that fix in the CLI we're using, but that doesn't appear to be fixing this case.  I'm still looking at it.

**Comment by ericstj** [comment]
I cannot repro this.  @ViktorHofer this may be related to some nuance in how the tests are restored.  Have you noticed this as part of your CI reliability work?

**Comment by ViktorHofer** [comment]
Yeah, I've noticed that particular issue couple times in our reports but hadn't yet time to investigate further.

**Comment by ViktorHofer** [comment]
Just hit this again on Windows UWP: https://dnceng.visualstudio.com/public/_build/results?buildId=305946&view=logs.

**Comment by ViktorHofer** [comment]
Hit this again on Windows UWP: https://dnceng.visualstudio.com/public/_build/results?buildId=333440&view=logs

**Comment by ViktorHofer** [comment]
@rrelyea could somebody on your team help us diagnose this issue? We are not sure what could cause this issue:

```
D:\a\1\s\src\System.Runtime\tests\TestStructs\System.TestStructs.ilproj : error : Failed to resolve SDK 'Microsoft.NET.Sdk.IL'. Package restore was successful but a package with the ID of "Microsoft.NET.Sdk.IL" was not installed.
##[error]src\System.Runtime\tests\TestStructs\System.TestStructs.ilproj(0,0): error : Failed to resolve SDK 'Microsoft.NET.Sdk.IL'. Package restore was successful but a package with the ID of "Microsoft.NET.Sdk.IL" was not installed.
```

**Comment by ViktorHofer** [comment]
Happened on arm64 as well: https://dnceng.visualstudio.com/public/_build/results?buildId=335382&view=logs

**Comment by rrelyea** [comment]
Looked at  the log. Looks like the earlier warning isn't there anymore.
This is an SDK package that is having restore problems?
How hard to reproduce is this?
cc @jeffkl

**Comment by jeffkl** [comment]
I downloaded the binlog for `Windows_NT_Build arm64_Release` in [this build](https://dnceng.visualstudio.com/public/_build/results?buildId=335382&view=logs) but there was no error in it.  Am I looking at the wrong log?

Usually the reason you get this error is that a different version is downloaded than the one specified.  The NuGet SDK resolver requires exact versions.  But I can't verify without the correct log.  Can someone point me to a binlog with the failure?

**Comment by ViktorHofer** [comment]
Unfortunately the restore step's binlog is overwritten by the build's one. We are submitting a fix in arcade right now but probably need to wait for another hit.

> This is an SDK package that is having restore problems?

yes.

> How hard to reproduce is this?

We don't know how to reproduce it and it happens only every few days.

> Usually the reason you get this error is that a different version is downloaded than the one specified. The NuGet SDK resolver requires exact versions.

We are specifying the version as expected here: https://github.com/dotnet/corefx/blob/master/global.json#L15
