### ISSUE TITLE
Should Utf8JsonReader expose TokenStartIndex?

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#33967]
The version of the JSON reader in corefxlab had a property, `TokenStartIndex` which allows a consumer of the reader to build a marker of their own when they can't persist a Span.

The workaround for Span involves doing Span value-address subtraction (asking where ValueSpan starts vs where the original data started), but that's presumably hard for Sequence scenarios.

Two things based on a whiteboard discussion:
  * Consumed isn't sufficient, because the caller doesn't know how much whitespace was between the closing quote of a property name and the subsequent colon
  * For String and PropertyName the TokenStartIndex is probably easier (and more valueable) to be before the quote, though a consumer would need to understand that for the value they need to add one to get where ValueSpan started, or add two to ValueSpan.Length to also get the end quote.
    * And for a PropertyName they can balance TokenStartIndex and Consumed.

The other internal detail that the document object needed is `InArray`, but that can be worked around by the caller maintaining their own `Stack<JsonTokenType>`.

**Comment by ahsonkhan** [comment]
API Proposal:
```C#
 public long TokenStartIndex { get { throw null; } }
```

Alternative names: ValueStartIndex, ElementStartIndex

For reference, here is the relevant Reader API surface
https://github.com/dotnet/corefx/blob/452f338739a15c9150349633eda1377b75657c03/src/System.Text.Json/ref/System.Text.Json.cs#L166-L179

Current workaround in `JsonDocument`:
https://github.com/dotnet/corefx/blob/452f338739a15c9150349633eda1377b75657c03/src/System.Text.Json/src/System/Text/Json/Document/JsonDocument.cs#L906-L914
