### ISSUE TITLE
[arm32/Linux] System.IO.FileSystem.Tests failures on arm32 linux

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#33966]
Running the arm32 tests on linux for System.IO.FileSystem.Tests produced the following results: passed 4041/4042 tests.

The test that failed was System.IO.Tests.File_GetSetTimes.SetDateTimeMax with the following output:
```
Assert.Equal() Failure\nExpected: 9999-04-11T23:47:17.0210000Z\nActual:   1969-04-03T01:59:33.0210000Z
   at System.IO.Tests.File_GetSetTimes.SetDateTimeMax() in /root/corefx-2261125/src/System.IO.FileSystem/tests/File/GetSetTimes.cs:line 158
```

**Comment by joperezr** [comment]
cc: @JeremyKuhne

**Comment by joperezr** [comment]
also cc @Anipik

**Comment by danmosemsft** [comment]
That's an odd one. It sets the year 9999 but gets 1969 back. Some OS/file system quirk most likely.
```c#
            DateTime dateTime = new DateTime(9999, 4, 11, 23, 47, 17, 21, DateTimeKind.Utc);
            File.SetLastWriteTimeUtc(file, dateTime);
            long ticks = File.GetLastWriteTimeUtc(file).Ticks;

            Assert.Equal(dateTime, File.GetLastWriteTimeUtc(file));
```
It is converting to UTC (which shouldn't change the year) then calling [SetFileTime](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-setfiletime) then reading with GetFileAttributesEx then back to UTC

@JeremyKuhne seen anytihng like this?

**Comment by JeremyKuhne** [comment]
No, I haven't seen anything like this. Probably worth attempting to set/read times through the shell.

**Comment by danmosemsft** [comment]
> through the shell

I assume you mean cmd.exe, as Powershell would presumably run through this same code. I am not sure I know of a built in way in cmd.exe to do `touch` so one would have to build your own `touch` for ARM?

**Comment by danmosemsft** [comment]
I was going to say you could use `date` then edit the file, but Windows won't let you set its clock to the year `9999` ...

**Comment by JeremyKuhne** [comment]
This is a bug on Linux no?

**Comment by danmosemsft** [comment]
Oh nuts, I've looked at so many test failures I missed it was Linux. You can ignore everything I wrote above then. :facepalm:. You can use `touch -t` then.
