### ISSUE TITLE
Нет перегрузки принимающей предикат в расширении Where

### ISSUE THREAD

**Issue by anweledig** [dotnet/corefx#3397]
Предикат представлен как Func<ISource,bool> и нельзя передать чистый делегат Predicat<ISource>, приходится передавать его через лямбда-выражение.

Хотелось бы видеть что-то вроде этого:
![predicate](https://cloud.githubusercontent.com/assets/10487884/10044905/fff5f5ba-6206-11e5-88f3-acb0ed7c1fd4.png)

**Comment by stephentoub** [comment]
Once the generic ```Action``` and ```Func``` delegates were introduced, there's little need for a custom delegate like ```Predicate<T>```; had we had ```Func<TArg, TResult>``` available from the beginning, I very much doubt we'd have ```Predicate<T>``` at all.  

The existing ```Where``` overload is very commonly used, and changing it from taking a ```Func<TSource, bool>``` would be a significant breaking change for little value.  The only benefit would be a small perf opportunity in a case where you already had a ```Predicate<TSource>``` instead and would need to allocate a ```Func<TSource, bool>``` from it.  We also couldn't just add such an overload, as it would cause compiler ambiguity errors for anyone using ```Where``` with a lambda, as the compiler wouldn't know how to choose between the overloads that take ```Predicate<TSource>``` and ```Func<TSource, bool>```.

I appreciate the suggestion, but I think things should stay as-is here.

**Comment by JonHanna** [comment]
1. This would be inconsistent with the rest of `Enumerable`.
2. This would be inconsistent with `Queryable`, which would have to be changed accordingly to cope with enumerables being treated as queryable.
3. This would be inconsistent with most extensions to Linq.
4. This would break every existing use of `Where`.
5. While you gain the ability to directly pass a `Predicate` you lose the ability to directly pass a `Func<T, bool>`, which makes it hard to see any general way to consider this an improvement, unless you happen to have a `Predicate`.

It wouldn't be possible to have `Predicate` supported in addition to `Func` as extra overloads, unless something else broke the ambiguity of the call if made with a lambda. Even if this was done, unless it did so by creating a `Func` that wrapped the predicate (which the caller can do anyway) it would mean a lot of duplication as all the internal classes would need to also be duplicated.
