### ISSUE TITLE
Utf8JsonReader should return default ValueSpan when ValueSequence is set (and vice versa)

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#33998]
When `Utf8JsonReader` accepts a `ReadOnlySpan<byte>` as input, ValueSequence is always set to default. However, if it accepts a `ReadOnlySequence<byte>`, in some cases, `ValueSequence` will contain the data (when the json element straddles). In those cases, `ValueSpan` should be cleared (i.e. set to default). Similarly, in the common case, when `ValueSpan` contains the data, `ValueSequence` should be default.

Also, when the reader is at StartObject or StartArray, `ValueSpan` should still point to the token (like `{`, `[`, etc.). This is especially important for something like `JsonDocument` which needs the value span to contain the right value (rather than being empty or still pointing to a previously encountered token).

cc @bartonjs

**Comment by bartonjs** [comment]
> Also, when the reader is at StartObject or StartArray, ValueSpan should still point to the token (like {, [, etc.).

Also EndObject and EndArray :smile:.

I think the statements are:

* One of ValueSpan or ValueSequence should be `default`.
* The other should not (except before starting)
* If `Read()` returns true, the "value" must be different.  (MemoryExtensions.Overlaps should return false against a saved value)

**Comment by ahsonkhan** [comment]
> If `Read()` returns true, the "value" must be different.  (MemoryExtensions.Overlaps should return false against a saved value)

That is an interesting clarification, but I agree. Previously, when we encountered the 'true', 'false', 'null' literals, we would return the cached "constant" spans rather than slicing into the user-provided JSON payload. That behavior would have broken the above requirement.

> The other should not (except before starting)

What about if Read() returned false? Can (and should) both `ValueSpan` and `ValueSequence` be default then?

**Comment by bartonjs** [comment]
> What about if Read() returned false? Can (and should) both ValueSpan and ValueSequence be default then?

Depends on if "false" means "nothing happened" or "I'm broken"; either "I left them alone" (which is what I'd assume) or "I cleared them" is fine; but whatever the contract is there should be a test for it :smile:
