### ISSUE TITLE
Support for RegexOptions.Compiled?

### ISSUE THREAD

**Issue by justinvp** [dotnet/corefx#340]
`RegexOptions.Compiled` isn't currently supported (the option exists but doesn't do anything). Will this be supported? If so, when? If not, why not?

**Comment by weshaggard** [comment]
We left the enum value because we don't generally like to subset enums, especially given that this value it is just an optimization and does not cause any functional issues. The reason why it is not actually doing anything right now is we don't have a way of supporting Reflection Emit and while we may be able support that on some of our platforms we cannot in all of them. For example .NET Native which is all static compiled ahead of time we cannot support code gen like Reflection Emit at runtime.

**Comment by justinvp** [comment]
I'm just curious if there are plans to bring back the optimization. If the idea is for this library to be used with aspnetcore50 (e.g. the "cloud optimized" framework), for example, you're very likely going to soon get requests for the optimization to be brought back. Otherwise, why even use this library at all?

With .NET Native, isn't there some kind of mechanism for serializers to be pregenerated at compile time? Maybe something similar can be employed for this? Or, perhaps there is a way to "light up" on platforms that support LCG?

Another idea: the full framework includes a [`Regex.CompileToAssembly`](http://msdn.microsoft.com/en-us/library/9ek5zak6(v=vs.110).aspx) method. It'd be interesting if there was a tool that did something like that, that could be used to pregenerate a PCL assembly with the compiled regex that will run correctly with this library. I think it would involve adding back a type or two and exposing some protected abstract/virtual members in this library, then making sure the tool can generate a PCL assembly with the appropriate references.

**Comment by sharwell** [comment]
Do you know if the current implementation use an NFA interpreter or a DFA interpreter? Even if the Reflection-based expression compiler from the .NET Framework is not applicable here, it would be possible to create a new implementation based on precomputed and/or dynamically-generated DFA tables. The lexer implementation used by ANTLR 4 is capable of implementing many features out-of-the-box, and could be modified to handle additional cases.

**Comment by justinvp** [comment]
It's [NFA](http://msdn.microsoft.com/en-us/library/e347654k(v=vs.110).aspx). I believe @joshfree had the idea of adding a fast-path DFA implementation when backtracking isn't being used (this was a few years ago); but I don't think it was ever implemented.

**Comment by sharwell** [comment]
I *might* be able to put some time in on this if it's clear that the existing Reflection-based code generation will not appear in corefx. If you or someone else does decide to start building a DFA implementation, I'd appreciate a heads-up but of course you're not obligated to do so.

**Comment by Tragetaschen** [comment]
One interesting option depending on the use case is hooking into Roslyn using KRuntime's Compile/Preprocess approach based on [ICompileModule](https://github.com/aspnet/KRuntime/blob/dev/src/Microsoft.Framework.Runtime.Roslyn/Services/ICompileModule.cs). That way, a compile-time-constant Regex is translated into the actual assembly instead of generating one during runtime, maybe with even more time consuming optimizations. This would scan for the proper constructor / static method invocations and replace those automatically. Maybe even those without the Compile flag, because: why not.

Of course, this approach does not work with expressions that are constructed during runtime.

**Comment by justinvp** [comment]
I took a look at what it'd take to support precompiled Regex assemblies.

When the following code runs on the full framework using the built-in Regex APIs in .NET 4.5...

```c#
using System.Reflection;
using System.Text.RegularExpressions;

class Program
{
    static void Main()
    {
        var infos = new[]
        {
            new RegexCompilationInfo(@"\b(?<word>\w+)\s+(\k<word>)\b",
                    RegexOptions.IgnoreCase | RegexOptions.CultureInvariant,
                    "DuplicatedString",
                    "Utilities.RegularExpressions",
                    ispublic: true),

            new RegexCompilationInfo(@"^(?("")(""[^""]+?""@)|(([0-9A-Z]((\.(?!\.))|[-!#\$%&'\*\+/=\?\^`\{\}\|~\w])*)(?<=[0-9A-Z])@))" +
                    @"(?(\[)(\[(\d{1,3}\.){3}\d{1,3}\])|(([0-9A-Z][-\w]*[0-9A-Z]\.)+[A-Z]{2,6}))$",
                    RegexOptions.IgnoreCase | RegexOptions.CultureInvariant,
                    "EmailAddress",
                    "Utilities.RegularExpressions",
                    ispublic: true)
        };

        var name = new AssemblyName("RegexLib, Version=1.0.0.1001, Culture=neutral, PublicKeyToken=null");
        Regex.CompileToAssembly(infos, name);
    }
}
```

A new assembly is created on disk with the following types inside:

```c#
public class DuplicatedString : Regex
{
    public DuplicatedString()
    {
        base.pattern = @"\b(?<word>\w+)\s+(\k<word>)\b";
        base.roptions = RegexOptions.CultureInvariant | RegexOptions.IgnoreCase;
        base.internalMatchTimeout = TimeSpan.FromTicks(-10000L);
        base.factory = new DuplicatedStringFactory1();
        base.capnames = new Hashtable();
        base.capnames.Add("word", 2);
        base.capnames.Add("0", 0);
        base.capnames.Add("1", 1);
        base.capslist = new string[] { "0", "1", "word" };
        base.capsize = 3;
        base.InitializeReferences();
    }

    public DuplicatedString(TimeSpan span1) : this()
    {
        Regex.ValidateMatchTimeout(span1);
        base.internalMatchTimeout = span1;
    }
}

internal class DuplicatedStringFactory1 : RegexRunnerFactory
{
    public override RegexRunner CreateInstance()
    {
        return new DuplicatedStringRunner1();
    }
}

internal class DuplicatedStringRunner1 : RegexRunner
{
    public override bool FindFirstChar()
    {
        int runtextpos = base.runtextpos;
        string runtext = base.runtext;
        int num3 = base.runtextend - runtextpos;
        if (num3 <= 0)
        {
            return false;
        }
        num3--;
        runtextpos++;
        if (!RegexRunner.CharInClass(char.ToLower(runtext[runtextpos], CultureInfo.InvariantCulture), "\0\0\n\0\x0002\x0004\x0005\x0003\x0001\x0006\t\x0013\0"))
        {
        }
        runtextpos--;
        base.runtextpos = runtextpos;
        return (num3 > 0);
    }

    public override void Go()
    {
        int num5;
        string runtext = base.runtext;
        int runtextstart = base.runtextstart;
        int runtextbeg = base.runtextbeg;
        int runtextend = base.runtextend;
        int runtextpos = base.runtextpos;
        int[] runtrack = base.runtrack;
        int runtrackpos = base.runtrackpos;
        int[] runstack = base.runstack;
        int runstackpos = base.runstackpos;
        this.CheckTimeout();
        runtrack[--runtrackpos] = runtextpos;
        runtrack[--runtrackpos] = 0;
        this.CheckTimeout();
        
        // lots more code in here; removed for brevity ...
    }

    public override void InitTrackCount()
    {
        base.runtrackcount = 9;
    }
}

public class EmailAddress : Regex
{
    public EmailAddress()
    {
        base.pattern = "^(?(\")(\"[^\"]+?\"@)|(([0-9A-Z]((\\.(?!\\.))|[-!#\\$%&'\\*\\+/=\\?\\^`\\{\\}\\|~\\w])*)(?<=[0-9A-Z])@))(?(\\[)(\\[(\\d{1,3}\\.){3}\\d{1,3}\\])|(([0-9A-Z][-\\w]*[0-9A-Z]\\.)+[A-Z]{2,6}))$";
        base.roptions = RegexOptions.CultureInvariant | RegexOptions.IgnoreCase;
        base.internalMatchTimeout = TimeSpan.FromTicks(-10000L);
        base.factory = new EmailAddressFactory2();
        base.capsize = 10;
        base.InitializeReferences();
    }

    public EmailAddress(TimeSpan span1) : this()
    {
        Regex.ValidateMatchTimeout(span1);
        base.internalMatchTimeout = span1;
    }
}

internal class EmailAddressFactory2 : RegexRunnerFactory
{
    public override RegexRunner CreateInstance()
    {
        return new EmailAddressRunner2();
    }
}

internal class EmailAddressRunner2 : RegexRunner
{
    public override bool FindFirstChar()
    {
        if (base.runtextpos > base.runtextbeg)
        {
            base.runtextpos = base.runtextend;
            return false;
        }
        return true;
    }

    public override void Go()
    {
        int num5;
        string runtext = base.runtext;
        int runtextstart = base.runtextstart;
        int runtextbeg = base.runtextbeg;
        int runtextend = base.runtextend;
        int runtextpos = base.runtextpos;
        int[] runtrack = base.runtrack;
        int runtrackpos = base.runtrackpos;
        int[] runstack = base.runstack;
        int runstackpos = base.runstackpos;
        this.CheckTimeout();
        runtrack[--runtrackpos] = runtextpos;
        runtrack[--runtrackpos] = 0;
        
        // lots more code in here; removed for brevity ...
    }

    public override void InitTrackCount()
    {
        base.runtrackcount = 58;
    }
}
```

These precompiled types depend on a number of `protected` fields and methods inside `Regex` and `RegexRunner`.

If we want to enable similarly precompiled types to work with this library, we'll need to do something similar. However, we have an opportunity to fix up some historical mistakes.

I don't think `Regex`'s fields should be exposed as `protected`. Exposing fields like this doesn't follow the design guidelines and doing so makes it difficult to validate the values. It's also problematic because two of the fields are `Hashtable` in the full framework and are now `Dictionary<int, int>` and `Dictionary<string, int>` in this library, so we'd have to either be OK with a type change (probably OK in this case), or rename the fields.

Instead of exposing the fields, there should be a new `protected` constructor added that can be used by precompiled Regex types. This obviates the need to expose the fields and allows the parameters to be validated. It also avoids the need to expose a couple `protected` methods (`InitializeReferences` and `ValidateMatchTimeout`).

In fact, there is [a comment in the reference source](https://github.com/Microsoft/referencesource/blob/9da503f9ef21e8d1f2905c78d4e3e5cbb3d6f85a/System/regex/system/text/regularexpressions/Regex.cs#L82-L86) in favor of a `protected` constructor:

```c#
// All these protected internal fields in this class really should not be protected. The historic reason
// for this is that classes extending Regex that are generated via CompileToAssembly rely on the fact that
// these are accessible as protected in order to initialise them in the generated constructor of the
// extending class. We should update this initialisation logic to using a protected constructor, but until
// that is done we stick to the existing pattern however ugly it may be.
```

A new `protected` constructor on `Regex` like this would be sufficient:

```c#
protected Regex(
    String pattern,
    RegexOptions options,
    TimeSpan matchTimeout,
    Func<RegexRunner> factory,
    int captureSize,
    IDictionary<Int32, Int32> captureTable,
    IDictionary<String, Int32> captureNameTable,
    String[] captureNames)
{
    ...
}
```

Note that `Func<RegexRunner>` can be used for the factory instead of adding back and exposing the `RegexRunnerFactory` type to this library.

`RegexRunner` would need to be made public. We'd have to decide if we want the fields exposed as `protected` (if so, we should probably rename them back to the way they were without the underscores) or do something else like add `protected` properties:

```c#
// This would need to be made public
abstract internal class RegexRunner
{
    // Either these fields remain protected, probably renamed back
    // to the way they were without the underscores, or something
    // else like new protected properties added
    protected internal int _runtextbeg;
    protected internal int _runtextend;
    protected internal int _runtextstart;
    protected internal String _runtext;
    protected internal int _runtextpos;
    protected internal int[] _runtrack;
    protected internal int _runtrackpos;
    protected internal int[] _runstack;
    protected internal int _runstackpos;
    protected internal int[] _runcrawl;
    protected internal int _runcrawlpos;
    protected internal int _runtrackcount;
    protected internal Match _runmatch;
    protected internal Regex _runregex;

    ...
}
```

With these two changes -- 1) adding a `protected` constructor to `Regex` and 2) making `RegexRunner` public with either the  protected fields exposed or new protected properties -- the use of precompiled Regex assemblies could work with this library.

Precompiled types compatible with the above changes would look like the following:

```c#
public class DuplicatedString : Regex
{
    public DuplicatedString()
        : this(TimeSpan.FromTicks(-10000L))
    {
    }

    public DuplicatedString(TimeSpan matchTimeout)
        : base(
            @"\b(?<word>\w+)\s+(\k<word>)\b",
            RegexOptions.CultureInvariant | RegexOptions.IgnoreCase,
            matchTimeout,
            () => new DuplicatedStringRunner1(),
            3,
            null,
            new Dictionary<string, int>(3)
            {
                { "word", 2 },
                { "0", 0 },
                { "1", 1 }
            },
            new[] { "0", "1", "word" }
        )
    {
    }
}

public class EmailAddress : Regex
{
    public EmailAddress()
        : this(TimeSpan.FromTicks(-10000L))
    {
    }

    public EmailAddress(TimeSpan matchTimeout)
        : base(
            "^(?(\")(\"[^\"]+?\"@)|(([0-9A-Z]((\\.(?!\\.))|[-!#\\$%&'\\*\\+/=\\?\\^`\\{\\}\\|~\\w])*)(?<=[0-9A-Z])@))(?(\\[)(\\[(\\d{1,3}\\.){3}\\d{1,3}\\])|(([0-9A-Z][-\\w]*[0-9A-Z]\\.)+[A-Z]{2,6}))$",
            RegexOptions.CultureInvariant | RegexOptions.IgnoreCase,
            matchTimeout,
            () => new EmailAddressRunner2(),
            10,
            null,
            null,
            null)
    {
    }
}
```

I don't think we should expose `Regex.CompileToAssembly` and `RegexCompilationInfo` in this library. Doing so would take an implementation dependency on `Reflection.Emit` and `Reflection.Emit.ILGeneration`. And I don't think there's actually a way to "save" an assembly using these libraries.

Instead, a tool could be built that can be used to create assemblies with the precompiled `Regex` types that are compatible with this library and the above changes. The only problem is the tool would need to make use of internal types of this library. For example, the use of internal types like `RegexParser` and `RegexTree` are required in order to produce the precompiled types. Which means the tool would probably need to embed its own copy of this library's sources in order for it to work. Assemblies produced by the tool would need to be PCLs and reference this library (this may require switching to use CCI or Mono.Cecil instead of Reflection.Emit).

Alternatively, a Roslyn-based tool could be created. However, this may be a lot more work as I'm not sure how easy it is to translate the existing IL-based code generation implementation to Rosyln.

Is this worth pursuing further?

**Comment by jchannon** [comment]
Hi, I just came across a warning from VS2015 that my current code that uses the Compiled option is not valid for `dnxcore50` - is this coming back, if not which option do I choose instead?

**Comment by sharwell** [comment]
@jchannon Here's how I handle light-up for this feature in a PCL:

https://github.com/rackerlabs/dotnet-uritemplate/blob/master/Rackspace.Net.UriTemplate/InternalRegexOptions.cs#L18-L26

**Comment by Priya91** [comment]
#5079, #5682
