### ISSUE TITLE
Occasional AV in code coverage build

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#34011]
Looking at the latest code coverage run I can see the build failed but there is absolutely no info what caused the build to fail: https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/754/consoleText

Error lines (removed htmlpublisher output):
```
Build Failed (exit code '-1073741819'). See log: D:\j\workspace\code_coverage---b14a30e5\artifacts\log\Debug\Build.binlog
Build.cmd ErrorLevel=1
Build step 'Execute Windows batch command' marked build as failure
[Current build status] check if current [FAILURE] is worse or equals then [SUCCESS] and better or equals then [SUCCESS]
Run condition [Current build status] preventing perform for step [[Archive the artifacts]]
[BFA] Scanning build for known causes...
[BFA] Found failure cause(s):
[BFA] Build step... marked build as failure from category Build
[BFA] Done. 2s
[WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] done
Finished: FAILURE
```

cc @ericstj @wtgodbe

**Comment by danmosemsft** [comment]
-1073741819 == 0xC0000005 == STATUS_ACCESS_VIOLATION
You need to repro under a debugger, or hope for a dump on the machine?

**Comment by ViktorHofer** [comment]
Sure, if the machine isn't yet recycled. In this case I will just wait for the next official build but I create this issue to make sure that we log everything necessary to diagnose build errors as it currently looks like we are missing details.

**Comment by wtgodbe** [comment]
This is happening in `build.ps1` from eng\common, so seems more like an Arcade bug: https://github.com/dotnet/corefx/blob/7d223d2d71d9921306ca0e53343be0aabede07af/eng/common/build.ps1#L97

Some target we're calling from Arcade's `build.proj` must not be doing sufficient error logging: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj

**Comment by danmosemsft** [comment]
This is probably an AV in MSBuild itself or in a task that it has loaded. There is no more info for Arcade to provide. It is necessary to repro under a debugger, or get a dump. Windows will likely have created a dump and put it in its Watson folder -- there may be a bucket ID for it in the event log. If so that can be downloaded and opened.

**Comment by danmosemsft** [comment]
Looks like this hasn't happened in recent builds?

**Comment by ViktorHofer** [comment]
Right, the last two errors were network related ones. Hopefully when we move this to Azure DevOps they won't happen anymore.

**Comment by ViktorHofer** [comment]
Closing as the last 8 runs were successful.
