### ISSUE TITLE
Cannot use Microsoft.Windows.Compatibility 2.1.0-preview in .NET 4.7

### ISSUE THREAD

**Issue by MichaelRumpler** [dotnet/corefx#34022]
I have a .NET Standard 2.0 class library which fetches some data about Windows accounts. I therefore installed Microsoft.Windows.Compatibility to use System.DirectoryServices.AccountManagement. (I am aware, that this is Windows only functionality, but there is other stuff in that lib which I want to use on Mac, iOS and Android.)

If I use a unittest project with .NET 4.7 and reference the Standard library, then this works without problems on Microsoft.Windows.Compatibility version 2.0.1. But if I update to 2.1.0-preview.18571.3, then my tests fail with a

> System.IO.FileLoadException: Could not load file or assembly 'System.Security.Principal.Windows, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
> The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

When I opened the System.Security.Principal.Windows.dll with dotPeek, then it says this is version 4.1.2.0.

The same error also comes, if I want to use the class library from a .NET 4.7 console application. Strangely here it does not matter if I use version 2.0.1 or 2.1.0-preview.18571.3. But AFAIK this should also work, shouldn't it?

With a .NET Core 3.0 console or unittest project, everything works with all versions.

Screenshot:
![compatibility2 1 0pre_fail](https://user-images.githubusercontent.com/8309363/49879778-0114f680-fe2b-11e8-9379-844d3b338eee.png)

Repro solution with the class lib and all the test projects:
[Compatibility2.1.0pre_Fail.zip](https://github.com/dotnet/corefx/files/2672441/Compatibility2.1.0pre_Fail.zip)

I left the bin and obj folders for the AccountService and .NET 4.7 unittest project in. All others have been deleted.
(I have a German system, on English ones you have to change the group name to "Administrators" to get the tests green.)

**Comment by karelz** [comment]
@ericstj any thoughts?

**Comment by ericstj** [comment]
Binding redirects need to be enabled in the test project.  You can set the following in the test project:
```xml
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType
```

MSBuild issue : https://github.com/Microsoft/msbuild/issues/1310

**Comment by MichaelRumpler** [comment]
Yes, this does fix the unittests. But why do I need them? I didn't reference Microsoft.Windows.Compatibility or System.Security.Principal.Windows anywhere else.

Also why does the ConsoleApp_Net47 not work? The System.Security.Principal.Windows.dll is not copied to that bin folder at all.

**Comment by ericstj** [comment]
Does the console app use packagereference?  If not convert it, or manually add references to the same transitive packages.

If it doesn’t reference any packages set RestoreProjectStyle=PackageReference to get transitive dependencies.

**Comment by MichaelRumpler** [comment]
I didn't add any nuget packages in the console app of this repro project. So there was no packages.config and no PackageReference in the csproj. As I created it yesterday with VS2019 I assumed that it would use PackageReference by default. However, that seemed to have been wrong. I added

    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>

to the csproj and then it worked.

Thank you!
