### ISSUE TITLE
[arm32/Windows] System.Runtime.Extensions.Tests failures on arm32 windows

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#34039]
Running the arm32 tests on windows for System.Runtime.Extensions.Tests produced the following results: passed 6479/6481 tests.

System.Tests.EnvironmentTests.GetFolderPath_Windows theory has 2 failing cases (folder= AdminTools and CommonAdminTools). The callstack is:
```
Assert.NotEmpty() Failure
   at System.Tests.EnvironmentTests.GetFolderPath_Windows(SpecialFolder folder) in F:\git\corefx\src\System.Runtime.Extensions\tests\System\EnvironmentTests.cs:line 493
```

[testResults.zip](https://github.com/dotnet/corefx/files/2673697/testResults.zip)

**Comment by danmosemsft** [comment]
Dupe of https://github.com/dotnet/corefx/issues/33986
