### ISSUE TITLE
Invalid argument: /m:1

### ISSUE THREAD

**Issue by v-haren** [dotnet/corefx#34065]
failed in job: https://ci2.dot.net/job/dotnet_corefx/job/perf/job/master/job/perf_ubuntu16.04_release/3622

failed log:
+ python3.5 /home/administrator/jenkins/w/dotnet_corefx/perf/master/perf_ubuntu16.04_release/Tools/Microsoft.BenchView.JSONFormat/tools/submission-metadata.py --name corefx rolling master  fa576b8877e7b8a20af56ed22320a1b93a3ad3f3 --user-email dotnet-bot@microsoft.com
[2018-12-12 22:20][INFO ] Serialized object written to: "submission-metadata.json"
+ python3.5 /home/administrator/jenkins/w/dotnet_corefx/perf/master/perf_ubuntu16.04_release/Tools/Microsoft.BenchView.JSONFormat/tools/build.py git --branch master --type rolling
[2018-12-12 22:20][INFO ] Serialized object written to: "build.json"
[perf_ubuntu16.04_release] $ /bin/sh -xe /tmp/jenkins4086817392035087193.sh
+ python3.5 /home/administrator/jenkins/w/dotnet_corefx/perf/master/perf_ubuntu16.04_release/Tools/Microsoft.BenchView.JSONFormat/tools/machinedata.py
[2018-12-12 22:20][INFO ] Serialized object written to: "machinedata.json"
[perf_ubuntu16.04_release] $ /bin/sh -xe /tmp/jenkins4668323872596237135.sh
+ bash ./build.sh --ci -release -includetests /p:BuildNative=false /p:Performance=true /p:TargetOS=Linux /m:1 /p:LogToBenchview=true /p:BenchviewRunType=rolling /p:PerformanceType=Profile
Invalid argument: /m:1
Common settings:
  --configuration <value>    Build configuration: 'Debug' or 'Release' (short: --c)
  --verbosity <value>        Msbuild verbosity: q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic] (short: -v)
  --binaryLog                Create MSBuild binary log (short: -bl)

Actions:
  --restore                  Restore dependencies (short: -r)
  --build                    Build all projects (short: -b)
  --rebuild                  Rebuild all projects
  --test                     Run all unit tests (short: -t)
  --sign                     Sign build outputs
  --publish                  Publish artifacts (e.g. symbols)
  --pack                     Package build outputs into NuGet packages and Willow components
  --help                     Print help and exit (short: -h)

Advanced settings:
  --projects <value>       Project or solution file(s) to build
  --ci                     Set when running on CI server
  --prepareMachine         Prepare machine for CI run, clean up processes after build
  --nodeReuse <value>      Sets nodereuse msbuild parameter ('true' or 'false')
  --warnAsError <value>    Sets warnaserror msbuild parameter ('true' or 'false')

Command line arguments starting with '/p:' are passed through to MSBuild.
Build step 'Execute shell' marked build as failure

**Comment by karelz** [comment]
Looks like problem with Perf infra. Does it belong into CoreFX repo?
@wtgodbe

**Comment by wtgodbe** [comment]
I think CoreFx is the right place. We should follow the advice [here](https://github.com/dotnet/arcade/issues/1575#issuecomment-447502559) & inline the call to `build.ps1`, rather than invoking `build.cmd`.

https://github.com/dotnet/corefx/blob/master/perf.groovy#L100-L101

**Comment by danmosemsft** [comment]
Are you taking this one @wtgodbe ?

**Comment by wtgodbe** [comment]
Sure, should be a quick fix

**Comment by wtgodbe** [comment]
https://github.com/dotnet/corefx/pull/34152 should resolve

**Comment by wtgodbe** [comment]
This particular issue is resolved, and the next step is tracked by https://github.com/dotnet/corefx/issues/34176
