### ISSUE TITLE
Difference between the behaviour of File.GetAttributes(string path) and new FileInfo(string path).Attributes

### ISSUE THREAD

**Issue by davidkaya** [dotnet/corefx#34068]
I encountered this problem (?) when I was writing tests for #29323 

```c#
var nonExistingFileInfo = new FileInfo("non-existing-file");
if ((nonExistingFileInfo.Attributes & FileAttributes.Hidden) == FileAttributes.Hidden)
    Console.WriteLine("File is hidden."); // This is printed because FileInfo returns -1
else
    Console.WriteLine("File is visible.");

File.GetAttributes("non-existing-file"); // This throws exception 
```

I know that documentation states `If the path doesn't exist as of the last cached state, the return value is (FileAttributes)(-1). FileNotFoundException or DirectoryNotFoundException can only be thrown when setting the value.` however is this expected behaviour?  I was writing tests for #29323 and I used the method available at https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/tests/FileInfo/GetSetAttributes.cs#L11 with a non existing file `(GetAttributes(".nonexistingfile") & FileAttributes.Hidden) == FileAttributes.Hidden` and basically I got `true` even though I shouldn't have (I know that based on the documentation I should've have checked whether it didn't return -1).

**Comment by danmosemsft** [comment]
What is .NET Framework behavior?

**Comment by MarcoRossignoli** [comment]
Same behaviour
```
File is hidden.

Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'C:\Users\rssmrc50\Downloads\ConsoleApp1\bin\Debug\non-existing-file'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.GetAttributes(String path)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\rssmrc50\Downloads\ConsoleApp1\Program.cs:line 20
```

**Comment by MarcoRossignoli** [comment]
Same behaviour
```
File is hidden.

Unhandled Exception: System.IO.FileNotFoundException: Could not find file '...\Downloads\ConsoleApp1\bin\Debug\non-existing-file'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.GetAttributes(String path)
   at ConsoleApp1.Program.Main(String[] args) in ...\Downloads\ConsoleApp1\Program.cs:line 20
```

**Comment by danmosemsft** [comment]
@JeremyKuhne should answer this one.

**Comment by JeremyKuhne** [comment]
Yes, this is expected behavior. It is an unfortunate gotcha and we don't have a great way to mitigate it. Adding `FileAttributes.Invalid` might be possible, but we'd still have to deal with the fact that you need to check for it.
