### ISSUE TITLE
how to create .resources file using dotnet core on linux

### ISSUE THREAD

**Issue by ramsubbaraoc** [dotnet/corefx#34067]
On Windows we can use Resgen tool to generate .resources files from the text files. How can we achieve the same using dotnet core

**Comment by danmosemsft** [comment]
Do you need to generate them during a build? If so you would do `dotnet build` on your project file.

If you have to run resgen directly, I am not sure there is a way to do that on .NET Core. I see no `dotnet` comamnd for it. @livarcocc do you know?

**Comment by tarekgh** [comment]
msbuild own resgen in general. I am moving this issue to their repo.

**Comment by tarekgh** [comment]
This issue was moved to Microsoft/msbuild#4082
