### ISSUE TITLE
TempAssembly not found when generating XML documents

### ISSUE THREAD

**Issue by alexdrl** [dotnet/corefx#34070]
Hello, we started migrating our application from .netcoreapp2.0 to .netcoreapp2.2. In the process, we encounter a problem with XML Serialization. The call stack and the error is the following.
 ![](https://user-images.githubusercontent.com/26382633/49952173-b9aa6b00-fefb-11e8-9dfd-867171ada1b7.png)

The code in between is a external library code that tries to generate some XML document dynamically. The error also happens in runtime code not only with TestServer.

I've tried to find the assembly without luck, and searching the code in https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/Serialization/Compilation.cs and https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs does not seem to reveal the location of the generated assembly (if it ever gets generated). Should the assembly get generated in a file? Why the parameter location in the XMLSerializer constructor is not used?

**Comment by ViktorHofer** [comment]
Not 100% sure but I Believe that belongs to https://github.com/Microsoft/vstest/.

**Comment by alexdrl** [comment]
Sorry, I edited the post later noting that the exception also throws on running the application.
________________________________

**Comment by danmosemsft** [comment]
@huanwu owns XML serialization I believe.

**Comment by huanwu** [comment]
@yujayee Could you take a look?

**Comment by yujayee** [comment]
@alexdrl Could you provide a simple repro of this problem? I'm not sure what's wrong from your description, when the serializer could not be found on disk, the exception should be caught and the serializer will be generated dynamically. And could you explain your question "Why the parameter location in the XMLSerializer constructor is not used?" in more details?  Which constructor and which parameter are you referring to?

**Comment by alexdrl** [comment]
Should we ignore this error then?

I was referring to this https://github.com/dotnet/corefx/blob/caa7879a4608433b98f01df6545b91ce063a5992/src/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs#L331
which I found later.

**Comment by yujayee** [comment]
@alexdrl According to [msdn](https://docs.microsoft.com/en-us/dotnet/api/system.xml.serialization.xmlserializer.-ctor?view=netcore-2.2#System_Xml_Serialization_XmlSerializer__ctor_System_Type_System_Xml_Serialization_XmlAttributeOverrides_System_Type___System_Xml_Serialization_XmlRootAttribute_System_String_System_String_ ), the parameter `location` is the location of the type, not the path serializer is generated. Are you using this constructor in your code? I don't know if this is related to the exception, but could you revise your code accordingly to see if the exception still exists?

**Comment by Lxiamail** [comment]
@alexdrl Hope you have work out of the problem. Closing the issue due to inactive for a while.
