### ISSUE TITLE
Consider enabling WarnAsError for both MSBuild and Csc

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#34074]
Now that https://github.com/dotnet/corefx/issues/29861 has been resolved and our build is once again warning free, it might be good to consider enabling `WarnAsError` for both MSBuild and Csc (and for any other tools that have similar options).

This would avoid us having these warnings committed in the first place.

**Comment by tannergooding** [comment]
CC. @danmosemsft, @stephentoub, @safern 

@safern mentioned that we might not want to enable such functionality for `OfficialBuilds` right now. Once those are stabilized, however, I think it would also be good to enable there as well (since everything should have already been caught in CI before the official build ever runs).

**Comment by ViktorHofer** [comment]
We should not enable WarnAsError in official builds as we are testing things differently there and with our follow-up infra work like code coverage integration in PRs we will test extra stuff in official builds only. I.e. cross-gened assemblies.

**Comment by ViktorHofer** [comment]
That sounds fine to me. `'$(OfficialBuildId)' == ''`.

**Comment by danmosemsft** [comment]
@stephentoub do you have any objection/concerns with this?

**Comment by stephentoub** [comment]
I would love to get to a place where any warning from any part of CI is treated as failure (and thus where any such failure is a real issue, it's not flaky, etc.). So no objections from me.

**Comment by ViktorHofer** [comment]
This will be enabled with https://github.com/dotnet/corefx/pull/34385
