### ISSUE TITLE
Utf8JsonReader should throw when isFinal is true and the first call to Read returns false

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#34081]
json.org's version of the JSON grammar says that a JSON payload has precisely one value.

Currently the reader will return false with no exception if no semantic value was present, which I found to be surprising.

* `ReadOnlySpan<byte>.Empty`
* `new byte[] { 0x20 }`
* Comments: Skip, `Encoding.UTF8.GetBytes("// just a comment")`
* Comments: Skip, `Encoding.UTF8.GetBytes("   /* comment and whitespace */     ")`

All of these are equivalently "there was no JSON here".

While it's possible for the caller to check that Read returned successfully at least once, or that in the final state reader.TokenType is not None; it seems like an easy pit of failure that the reader should report via an exception.

Naive interpretation is that right before a `return false` in Read() it should add `if (isFinal && TokenType == JsonTokenType.None) throw new JsonReaderException(...);`

**Comment by Marusyk** [comment]
Hello, I will try to prepare PR for this. Could you please advise what error message it should throw?

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/dotnet/corefx/pull/34155. Closing.
