### ISSUE TITLE
DataflowBlock.LinkTo(source, target, predicate) clogs

### ISSUE THREAD

**Issue by curtnichols** [dotnet/corefx#34098]
## Problem statement
I found that [DataflowBlock.LInkTo(source,target,predicate)](https://github.com/dotnet/corefx/blob/269670f3368c7282f8dc5f5530c8b972f4ef68a6/src/System.Threading.Tasks.Dataflow/src/Base/DataflowBlock.cs#L61) extension method fails to propagate any messages after the predicate returns false.

The documentation for the predicate argument indicates

> The filter a message must pass in order for it to propagate from the source to the target.

Am I misreading the docs? Refusing to accept any more messages is unexpected behavior.

### Expected
If the predicate returns `true, false, true` on the first three messages, the first and third should be propagated to the target.

### Actual
If the predicate returns `true, false` on the first two messages, the predicate is never called again. The source for the link--say, if it's a `BufferBlock`--accumulates messages that don't get propagated to the target.

### Repro
My test code illustrating the behavior is in a gist [**here**](https://gist.github.com/curtnichols/c16ae6d14817b69ca326c412ffe46e26). I've repro'd this in a .NET Console App (.NET Core), VS 15.9.3, .NET Core 2.2.

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise>dotnet --list-sdks
2.1.403 [C:\Program Files (x86)\dotnet\sdk]
2.2.100 [C:\Program Files (x86)\dotnet\sdk]
```

**Comment by stephentoub** [comment]
This is by design.  The data isn't just dropped when it doesn't propagate; instead, it remains in the source block until it's received or propagated somewhere else.  And since it's all ordered, nothing else is propagated until that item is gone.  If you want to drop all items that don't pass the predicate, you can add a subsequent LinkTo to the null target, such that any items that fail to propagate across the first link will then be offered to the null target, which will happily accept and drop anything.

**Comment by curtnichols** [comment]
I think that's fair, I just don't think the function's docs get one to that understanding. I was definitely thinking of the predicate in the sense of, well, a filter as it says. Something like linq's `Where` or, in this case, F#'s `Seq.filter`.

I've moved on and written a solution that better suits me. Other than my comment on the docs, I don't have an ongoing concern about this. Thanks!

**Comment by stephentoub** [comment]
Thanks.  Feel free to open an issue in the docs repo if you think there's further clarification needed.
