### ISSUE TITLE
ToolsError build failures in 'official/corefx/master/' - '20181208.01'

### ISSUE THREAD

**Issue by robertborr** [dotnet/corefx#34099]
@dotnet-mc-bot commented on [Fri Dec 07 2018](https://github.com/dotnet/core-eng/issues/4766)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2263050
  - **Agent:** DDVSOWINAGE082
  - **Error log:** E:\A\_work\0\s\corefx\Tools\codeOptimization.targets(0,0): error MSB3073: The command "E:\A\_work\0\s\corefx\.packages\Microsoft.DotNet.IBCMerge\4.6.0-alpha-00001\lib\net45\ibcmerge.exe -q -f -delete -mo E:\A\_work\0\s\corefx\Tool...

@jcagme, @markwilkie

---

@robertborr commented on [Mon Dec 10 2018](https://github.com/dotnet/core-eng/issues/4766#issuecomment-445960464)

related: dotnet/coreclr#20225

**Comment by robertborr** [comment]
refrencing also:

https://github.com/dotnet/core-eng/issues/4786
https://github.com/dotnet/core-eng/issues/4776
https://github.com/dotnet/core-eng/issues/4774
https://github.com/dotnet/core-eng/issues/4772
https://github.com/dotnet/core-eng/issues/4770
https://github.com/dotnet/core-eng/issues/4768
https://github.com/dotnet/core-eng/issues/4766

**Comment by robertborr** [comment]
There were a set of failures during this build. Here is a summary of these:

https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2263050
Agent: DDVSOWINAGE082
Error log: E:\A_work\0\s\corefx\Tools\codeOptimization.targets(0,0): error MSB3073: The command "E:\A_work\0\s\corefx.packages\Microsoft.DotNet.IBCMerge\4.6.0-alpha-00001\lib\net45\ibcmerge.exe -q -f -delete -mo E:\A_work\0\s\corefx\Tool...
@jcagme, @markwilkie

related: dotnet/coreclr#20225

**Comment by wtgodbe** [comment]
Closing as dead
