### ISSUE TITLE
HttpClient throwing System.Net.Sockets.SocketException after 21 seconds

### ISSUE THREAD

**Issue by emilssonn** [dotnet/corefx#34095]
We are getting random 21 second timeouts when making http calls using HttpClient. As far as I know this is an low-level TCP timeout. The exception message is the same as in issue #31951. What causes these errors? 

The real world use case is that we have an Azure Webapp running the latest version of .Net Core 2.1. When this webapp receives a request it will do a request (using httpclient) to another API that is accessed through Azure API Management. When our webapp gets maybe 30+ requests at the same time (causing 30+ requests being made to APIM) we might get this timeout on some of the request made to APIM, after an retry it works.

I am trying to figure out why this timeout is happening. Can this exception indicate any errors in my code, setup or webapp performance? Or is the issue in API Management?

**Comment by MarcoRossignoli** [comment]
Are you using [HttpClientFactory](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)?

**Comment by emilssonn** [comment]
Yes, I am using a typed client with polly for retries.

**Comment by emilssonn** [comment]
Simplified I use the following. The httpclient is injected using the pattern on https://docs.microsoft.com/sv-se/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1

```
var request = new HttpRequestMessage
{
    Method = method,
    RequestUri = new Uri(apiPath, UriKind.Relative),
    Content = content
};

using (var response = await _httpClient.SendAsync(request))
{
   return await response.Content.ReadAsAsync<T>();
}
```

**Comment by davidsh** [comment]
21 seconds is the built-in default for TCP connection timeout on Windows.  It is 21 seconds because Windows TCP stack allows for 7 seconds per leg of the 3-leg TCP SYNC-ACK connection setup.

There is no current override to this timeout which is a built-in timeout to the Windows TCP layer.

This issue is basically a duplicate of #31951

**Comment by davidsh** [comment]
cc: @karelz

**Comment by karelz** [comment]
@emilssonn I am curious how often it happens and if you are able to reproduce it in some debuggable/traceable environment outside of Azure WebApps.

**Comment by emilssonn** [comment]
I have not been able to reproduce it "manually" yet.
I apologize if this issue is a duplicate. My main question is if this exception always indicate an error in the target API (API Management in this case) or if this error/timeout can occur in some way where the cause is the caller and not the target. I have an ongoing ticket with Azure support and I am basically trying to rule out as many things as possible since we have not been able to find the reason yet.

It happens randomly when the load spikes from 0 rps to "high" rps. For example:
2018-12-08T18:12:42: 78 request to target, OK
2018-12-08T18:12:43: 24 request to target, OK
2018-12-08T18:12:43: 27 request to target, 21 sec timeout

**Comment by karelz** [comment]
Unless there is some bug somewhere, it is indication the endpoints you call are not responding as they should on TCP level, triggering this timeout.

**Comment by emilssonn** [comment]
I have been troubleshooting this for quite some time. After discussion with the Azure support, one possible cause is resource exhaustion on the Azure Webapp. The main reason I created this issue was that almost all references to hitting the connection limit in Azure Webapps says it results in a exception, “An attempt was made to access a socket in a way forbidden by its access permissions aaa.bbb.ccc.ddd.”.

And the reason for hitting(?) the connection limit is that the Webapp will under heavy load do alot of outgoing requests at the same time, limiting connection reuse (even when using HttpClient correctly).

**Comment by stephentoub** [comment]
> under heavy load do alot of outgoing requests at the same time

You could try setting the MaxConnectionsPerServer property on the handler, in order to throttle how many connections you actually open.

**Comment by emilssonn** [comment]
@stephentoub, is that only per HttpClient object (I have multiple services using typed HttpClients that connects to the same domain)? What happens if the MaxConnectionsPerServer is hit? 

At the moment I use a shared Polly bulkhead policy to throttle outgoing requests.

**Comment by stephentoub** [comment]
> is that only per HttpClient object 

It's per handler, so if you were to use the same handler instance with multiple HttpClient instances, all of those clients would share in the same max. The parameterless HttpClient ctor creates its own handler, in which case it ends up having the same effect as being per client.
