### ISSUE TITLE
Adding a 'yield all' keyword

### ISSUE THREAD

**Issue by TheMinefighter** [dotnet/corefx#34109]
Currently we have a `yield return` and a `yield return`. While working with these I noticed that it is often needed to return all items of another `IEnumerable<T>` which results in code like
```
foreach (string s in someIEnumerableOfStrings) {
   yield return s;
}
```
I think a shortcut is needed for doing so:
```
yield all someIEnumerableOfStrings;
```
This would make the code far more readable, and would greatly improve working with `yield`.

**Comment by benaadams** [comment]
Issue/request would be better raised in https://github.com/dotnet/csharplang as its more about the C# language than the .NET api surface?

**Comment by TheMinefighter** [comment]
@benaadams Weren't sure about this but ok, https://github.com/dotnet/csharplang/issues/2079
