### ISSUE TITLE
[CI Failure] TimeZoneInfo_DisplayNameStartsWithOffset

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#34106]
TimeZoneInfo_DisplayNameStartsWithOffset

Windows.7.Amd64.Open-x64-Debug

```
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
01:00 != 00:00:00, dn:(UTC+01:00) Casablanca, sn:(UTC+01:00) Casablanca
Expected: True
Actual:   False
Stack Trace :
   at System.Tests.TimeZoneInfoTests.TimeZoneInfo_DisplayNameStartsWithOffset() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime\tests\System\TimeZoneInfoTests.cs:line 2227
```
https://mc.dot.net/#/user/benaadams/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/75205984fff23de8f87095739ebac2e3b791e01e/workItem/System.Runtime.Tests/analysis/xunit/System.Tests.TimeZoneInfoTests~2FTimeZoneInfo_DisplayNameStartsWithOffset

**Comment by benaadams** [comment]
And again

Windows.7.Amd64.Open-x64-Debug
```
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
01:00 != 00:00:00, dn:(UTC+01:00) Casablanca, sn:(UTC+01:00) Casablanca
Expected: True
Actual:   False
Stack Trace :
   at System.Tests.TimeZoneInfoTests.TimeZoneInfo_DisplayNameStartsWithOffset() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime\tests\System\TimeZoneInfoTests.cs:line 2227
```
 https://mc.dot.net/#/user/benaadams/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/75205984fff23de8f87095739ebac2e3b791e01e/workItem/System.Runtime.Tests/analysis/xunit/System.Tests.TimeZoneInfoTests~2FTimeZoneInfo_DisplayNameStartsWithOffset

**Comment by MarcoRossignoli** [comment]
Also on Windows.7.Amd64.Open-x86-Release
```
01:00 != 00:00:00, dn:(UTC+01:00) Casablanca, sn:(UTC+01:00) Casablanca
Expected: True
Actual:   False
Stack Trace :
   at System.Tests.TimeZoneInfoTests.TimeZoneInfo_DisplayNameStartsWithOffset() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Runtime\tests\System\TimeZoneInfoTests.cs:line 2227
```
https://mc.dot.net/#/user/MarcoRossignoli/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/9861983507db802c6bd8ee103086c062702fa863/workItem/System.Runtime.Tests/analysis/xunit/System.Tests.TimeZoneInfoTests~2FTimeZoneInfo_DisplayNameStartsWithOffset

**Comment by EgorBo** [comment]
@tarekgh maybe it makes sense to disable this test on Windows?

**Comment by danmosemsft** [comment]
@krwq could you please take a look today? this is breaking all CI jobs eg
https://mc.dot.net/#/user/wfurt/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/91eb28d6d7f26310bbc374f1bffe1222fe267832

I could disable it, but perhaps it's better to just accept either value in this case.

**Comment by krwq** [comment]
I don't see this test doing anything which we could do better. Product just reads data from the registry so disabling since like the correct approach
