### ISSUE TITLE
XmlUtf8RawTextWriter can read out of bounds

### ISSUE THREAD

**Issue by jlennox** [dotnet/corefx#34115]
https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.Private.Xml/src/System/Xml/Core/XmlUtf8RawTextWriter.cs#L904

The line `if (pSrc[1] == '\n')` appears 4 times and also appears in `XmlUtf8RawTextWriterAsync`. It performs a check on cursor+1 without checking if it's at the end of the input, causing trailing `\r`'s to make an out of bounds read.

PR incoming.

```CSharp
MemoryStream ms = new MemoryStream();
XmlWriterSettings settings = new XmlWriterSettings
{
    Encoding = Encoding.UTF8,
    NewLineHandling = NewLineHandling.Replace
};

using (XmlWriter writer = XmlWriter.Create(ms, settings))
{
    writer.WriteStartDocument();
    writer.WriteElementString("test", "\r");
    writer.Flush();
}
```

This code reproduces this but because it does not have any side effect there's no easy to make test for this.

I wrote non-portable code to setup an exception trap by making a memory page that is readonly/guard to place the "\n" directly before in memory, but there's no clear way to get the code to use something from an unmanaged source from a test project.

`XmlUtf8RawTextWriter.cs` in general could use a major cleanup. There's extremely heavy copy/pasting. Is this permissible?

**Comment by buyaa-n** [comment]
Thank you @krwq I've got better understanding, @jlennox  just a little adjustment with file name, seems it is https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/Core/XmlRawTextWriterGenerator.cxx
