### ISSUE TITLE
System.Collections.Immutable should provide Span/Memory APIs

### ISSUE THREAD

**Issue by agocke** [dotnet/corefx#34126]
Specifically, I think ImmutableArray should have a `ReadonlySpan<T> AsSpan<T>()` method.*`.

Needed APIs:

**System.Collections.Immutable**

* `ReadOnlySpan<T> ImmutableArray<T>.AsSpan()` 
* `ReadOnlyMemory<T> ImmutableArray<T>.AsMemory()`

**Comment by jkotas** [comment]
> System.Reflection.Metadata can provide overloads that take Span instead of just `byte*`

`System.Reflection.Metadata` cannot take Span. `MetadataReader` is a reference type. You cannot store Span inside a reference type.

**Comment by jkotas** [comment]
> True, but we could have a SpanMetadataReader that is a ref struct

`ref structs` are viral. You would have to create a Span clone of every reader type in `S.R.Metadata` to make this work without compromising safety: `ref SpanMethodDefinition`, `ref SpanMethodDefinitionHandleCollection`, `ref SpanMethodImplementation`, ... . I do not think it is something we would want to do.

**Comment by agocke** [comment]
@jkotas That's a good point. I'm planning on doing at least the ImmutableArray stuff when I have time. Let me explore where we could use Span in S.R.M and if I don't find anything, then we don't need to add anything.

**Comment by juho-hanhimaki** [comment]
Any timeline when the ReadOnlySpan<T> implementation might be included in the product?

**Comment by agocke** [comment]
@jkotas I've scoped this down to just the Span/Memory additions to ImmutableArray and marked it ready for review.

**Comment by agocke** [comment]
@terrajobst

**Comment by terrajobst** [comment]
That seems quite reasonable to me. Let's take a look for Tuesday.

**Comment by lorcanmooney** [comment]
Please also consider `ImmutableArray<T> ImmutableArray.Create<T>(ReadOnlySpan<T> items)`.
