### ISSUE TITLE
Consider removing SyncRoot on popular collections in favor of object in ConditionalWeakTable

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#34149]
There are apps where it's common to have a lot of empty or small lists and/or dictionaries. (MSBuild was one, at least at one time.) It would be nice to make these cheaper on memory. As the caller it's possible to reduce the memory cost by using strategies like `List<T>.Empty`, copy on write, and/or custom versions for low counts (MSBuild did all those), but that adds complexity and a longer code path.

Both these types have a private field for _syncRoot. They don't use it themselves, it's for external use. If we could remove that it would shrink them all by 4-8 bytes. Right now the current size of an empty List<T> looks like 24-48 bytes so that's 17%. (The reduction in the size of a collection with contents would be much smaller.)

It would be possible to remove _syncRoot by returning `this` but in the unlikely case where calling code was already using `this` for some other locking purpose that could cause deadlock or thread safety problems. Instead, we could safely return an object from the`ConditionalWeakTable`. That would be safe and indistinguishable by callers.

Retrieving this object would be significantly slower so this would only be worth it if it was rarely used. I think SyncRoot was deprecated almost from the beginning. My guess is that usage is low or very low (apisof.net won't help us here as it doesn't show usage through interfaces). If that's true the heavy usage of these types might make this change worthwhile.

**Comment by jkotas** [comment]
> possible to remove `_syncRoot` by returning `this`

I think it would work just fine. .NET Framework 1.x was doing just that. I do not think there was ever a functional issue because of that.

The reason why we have started creating the decicated sync objects was partial trust security. The SyncRoot allowed you to get access to object you was not supposed to get access to.

Here is the change description from VSWhidbey #412702:

```
Description of issue:  
SyncRoot returns more information than we should.

Justification: 
User could cast the return value of SyncRoot to some object it shouldn't have access to.
```

**Comment by stephentoub** [comment]
My only concern with `return this;` is if code was relying on object identity of `this` and `this.SyncRoot` being different, in particular if it was locking on both for different critical regions that would now end up being one and the same, which could result in broken invariants.  However, that's fairly unlikely. For a major release, side-by-side... probably not a huge concern.

**Comment by danmosemsft** [comment]
OK I'll prepare a PR that changes it to this everywhere.

**Comment by danmosemsft** [comment]
(If sync root originally returned "this" across the board one wonders why the concept was invented...)

**Comment by jkotas** [comment]
> sync root originally returned "this" across the board

It does not return "this" across the board. It returns inner collection sync root for collections that are wrapping other collections.

**Comment by sharwell** [comment]
Interesting. I used the `ConditionalWeakTable` approach in my tree collection library:
https://github.com/tunnelvisionlabs/dotnet-trees/blob/master/TunnelVisionLabs.Collections.Trees/SyncRootFallback.cs

**Comment by sharwell** [comment]
> It returns inner collection sync root for collections that are wrapping other collections.

⚠️ This could inadvertently expose a collection intended to be protected. For example, when [`ReadOnlyCollection<T>.SyncRoot`](https://github.com/dotnet/coreclr/blob/75c8c54950c78f1192e481a5bbd6eeff1b3bd1cd/src/System.Private.CoreLib/shared/System/Collections/ObjectModel/ReadOnlyCollection.cs#L126) is wrapping [`List<T>.SyncRoot`](https://github.com/dotnet/coreclr/blob/876e17a90abe93d1e2f6658dc914f85dc66ab861/src/System.Private.CoreLib/shared/System/Collections/Generic/List.cs#L143).

**Comment by jkotas** [comment]
> This could inadvertently expose a collection intended to be protected

Right, that mattered with partial trust security. It does not really matter anymore. There are many different ways you can hack into wrappers.

**Comment by danmosemsft** [comment]
@ViktorHofer I wish to remove _syncRoot from SortedList but it needs a blob update (field type remains object but it now contains an object of concrete type SortedList). However when I run the "blob update" task I get all kinds of unexpected updates in a about half the blobs, both .NET Framework and .NET Core. Looking at the diffs after decoding, there's no common pattern.

https://github.com/dotnet/corefx/pull/34198#issuecomment-449229281

**Comment by ViktorHofer** [comment]
Sorry for my late reply, I must have overlooked that one. Can you remind me what your change was so that I test it locally?

**Comment by danmosemsft** [comment]
@ViktorHofer in SortedList, the change is to return `this` from the Syncroot getter here
https://github.com/danmosemsft/corefx/blob/a7c2aa86ce0d74c40bc6208e530fb1c82768d3ed/src/System.Collections.NonGeneric/src/System/Collections/SortedList.cs#L295
and remove the field as well.

That doesn't affect serialization of SortedList itself, because the _syncroot field there is marked [NonSerializable]. 

However it does affect the serialization of SyncSortedList (further down the file) as SyncSortedList puts the sync root from SortedList into its own field, which unfortunately is NOT marked [NonSerializable]. https://github.com/danmosemsft/corefx/blob/a7c2aa86ce0d74c40bc6208e530fb1c82768d3ed/src/System.Collections.NonGeneric/src/System/Collections/SortedList.cs#L615

Because of the change to SortedList, the underlying type of this field will now change from object to SortedList, which modifies the blobs.

My attempt to update the blobs to accommodate this is what failed because when I used the update mechanism, I got all sorts of other blob updates.

**Comment by danmosemsft** [comment]
I think it is a low priority to investigate, since it simply means that SortedList is retaining the sync root that ideally it would not have.

**Comment by ViktorHofer** [comment]
Doesn't that mean that the SyncSortedList blob will grow significantly as the sync root will be the SortedList with all its data instead of a simple object?

**Comment by ViktorHofer** [comment]
What I mean is that we would serialize the SortedList twice into the SyncSortedList blob with that change.

**Comment by danmosemsft** [comment]
SyncSortedList already stores the SortedList in its other field. Is the BinaryFormatter not smart enough to add a reference from one to the other? It surely handles cycles that way.

**Comment by ViktorHofer** [comment]
I would need to try that out to give a definite answer. Why can't we change https://github.com/danmosemsft/corefx/blob/a7c2aa86ce0d74c40bc6208e530fb1c82768d3ed/src/System.Collections.NonGeneric/src/System/Collections/SortedList.cs#L615 to `_root = this`?

**Comment by ViktorHofer** [comment]
You are right, it even shrinks the diff as it doesn't need to serialize the additional object: https://www.diffchecker.com/R0Vt8R7r. I noticed that we don't have any serialization tests for SyncSortedList :O
