### ISSUE TITLE
System.Drawing.Common throws when saving with EncoderParameters 

### ISSUE THREAD

**Issue by JimBobSquarePants** [dotnet/corefx#34156]
Using NetCoreApp 2.1 on Windows with either

System.Drawing.Common 4.5.1
System.Drawing.Common 4.6.0-preview.18571.3

when saving a jpeg using either overload:

`public void Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)`
`public void Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)`

The following exception is thrown.

> {System.ArgumentException: Parameter is not valid.
> at System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)

![System Drawing exception](https://user-images.githubusercontent.com/385879/50196721-60798600-0398-11e9-955d-4609466a3c33.png)

Saving the image without the params works as expected.

I've attached the following program to allow reproduction.
[SDIssue.zip](https://github.com/dotnet/corefx/files/2693093/SDIssue.zip)

**Comment by danmosemsft** [comment]
What happens in.NET Framework?

**Comment by JimBobSquarePants** [comment]
Ignore me. It's a bug in my code! 

I'd forgotten how brittle the API was. The `EncoderParameter` Quality expects a long and the API was interpreting the passed `75` parameter as a byte. 

Carry on the good work!
