### ISSUE TITLE
Suggestion: IAsyncQueryable 

### ISSUE THREAD

**Issue by lillo42** [dotnet/corefx#34161]
I'm studying C# 8 and new we have a new interface call ``IAsyncEnumerable`` and I was think maybe it's a good ideia create a new interface call ``IAsyncQueryable`` to be possible using ``await foreach`` async with ORM like EF or NHibernarte:

```csharp

IAsyncQueryable query = database.Where(...);

await foreach(var a in query) {
...
}
```

I was thinking ``IAsyncQueryable`` could be:
```csharp
public interface IAsyncQueryable : IAsyncEnumerable
{
   Type ElementType { get; }
    Expression Expression { get; }
    IQueryProvider Provider { get; }
}


public interface IAsyncQueryable<T> : IAsyncQueryable, IAsyncEnumerable<T>
{

}
```

or

```csharp

public interface IAsyncQueryable : IQueryable, IAsyncEnumerable
{

}


public interface IAsyncQueryable<T> : IQueryable<T>, IAsyncQueryable,  IAsyncEnumerable<T>
{

}
```

**Comment by Suchiman** [comment]
Since IQueryable is about composing a query rather than constructing an execution pipeline, it would probably make more sense to follow the current approach of adding an extension like this
```csharp
public static IEnumerable<TSource> AsEnumerableAsync<TSource>(this IQueryable<TSource> source)
```

**Comment by stephentoub** [comment]
Without language support for awaits in expression trees, I don't think there's much that can or should be done here.
cc: @cston, @jaredpar

**Comment by jaredpar** [comment]
I agree. There is currently no plans to invest in our expression tree support at this time.

**Comment by tarekgh** [comment]
@jaredpar should we move this issue to your repo you may track it for the future if anything change?

**Comment by tarekgh** [comment]
Thanks @jaredpar I'll move it because corefx can support it if the it is decided from your side to support it.

**Comment by tarekgh** [comment]
Issue moved to [dotnet/roslyn #32569](https://github.com/dotnet/roslyn/issues/32569) via [**ZenHub**](https://www.zenhub.com/)
