### ISSUE TITLE
InitTools fails from root as no restore target found or invalid

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#34164]
```
C:\git\corefx>.\build.cmd -InitTools

C:\git\corefx\build.proj : warning NU1503: Skipping restore for project 'C:\git\corefx\build.proj'. The project file may be invalid or missing targets required for restore. [C:\git\corefx\.dotnet\sdk\2.1.401\NuGet.targets]
C:\git\corefx\.dotnet\sdk\2.1.401\NuGet.targets(114,5): warning : Unable to find a project to restore!
    2 Warning(s)
    0 Error(s)
```

I think that broke with the last manual darc update.

cc @ericstj @safern

**Comment by safern** [comment]
Yes this was with the darc update I investigated a little and this is the guilty: https://github.com/dotnet/arcade/pull/1567#issuecomment-448628932

I just commented there.

**Comment by ViktorHofer** [comment]
I digged deeper into it. The exact cause is that the restore target in the NuGet.targets file is invoked directly instead of calling the project restore target. That was change because of races. I suggested to change that back as restoring currently fails in corefx because of that.
