### ISSUE TITLE
Wrong NetworkInterfaceType on OS X Mojave with .Net Standard 2.0 for WiFi Adapter

### ISSUE THREAD

**Issue by HelgeKeck** [dotnet/corefx#34177]
On OS X Mojave with .Net Standard 2.0

for the WiFi Adapter, System.Net.NetworkInformation.NetworkInterface.NetworkInterfaceType()

returns
NetworkInterfaceType.Ethernet
instead of
NetworkInterfaceType.Wireless80211

**Comment by ViktorHofer** [comment]
@HelgeKeck which dotnet version are you using? the easiest way to tell is to post the output from `dotnet --info` here.

**Comment by karelz** [comment]
cc @wfurt

**Comment by vcsjones** [comment]
I can reproduce this on all netcoreapp versions >= 2.0. (Including Microsoft.NETCore.App 2.2.0).

**Comment by wfurt** [comment]
We may not be able to distinguish. My WIFI looks just like ethernet on my MacBook.

```
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 8c:85:90:d0:00:f4
	inet6 fe80::1c22:ceef:7941:e93%en0 prefixlen 64 secured scopeid 0xa
	inet 10.104.140.151 netmask 0xfffff800 broadcast 10.104.143.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
```

**Comment by karelz** [comment]
Looks like by design then ...

**Comment by wfurt** [comment]
I would agree it is not by design. I also noticed that some VPN interfaces come up as ethernet. Maybe leave it open @karelz and mark for "up for grabs" ?

**Comment by karelz** [comment]
If you think it is something that can be fixed, we can keep it open. Previous comments hinted it may be OS limitation.
If you mark it up-for-grabs, please make sure you provide enough details that someone can actually pick it up and we can guide them though the change - see our [triage rules](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#motivation-for-triage-rules)
