### ISSUE TITLE
Does Char.ConvertFromUtf32 allocate temporary strings, due to the exception code path?

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#34173]
Adding this issue mainly for tracking purposes.

From comment within source: https://github.com/dotnet/corefx/blob/e0ba7aa8026280ee3571179cc06431baf1dfaaac/src/System.Text.Encodings.Web/src/System/Text/Encodings/Web/UnicodeHelpers.cs#L209-L223

I am assuming we can use `Char.ConvertFromUtf32` now, especially after https://github.com/dotnet/coreclr/pull/21409, and update the comment.

Implementation of `Char.ConvertFromUtf32`:
https://github.com/dotnet/corefx/blob/d4b014c7483789d3832d3c15fb3741e2cc5306b1/src/Common/src/CoreLib/System/Char.cs#L923-L931

**We either have to:**
- Re-write the implementation based on new API design (from https://github.com/dotnet/corefx/issues/33509) and close this issue, or
- Verify that `Char.ConvertFromUtf32` is fine to use update the code/comment in `UnicodeHelpers` to use it, or
- Try to fix `Char.ConvertFromUtf32` and update the code/comment in UnicodeHelpers to use it

cc @GrabYourPitchforks, @stephentoub, @danmosemsft

**Comment by stephentoub** [comment]
> I am assuming we can use Char.ConvertFromUtf32 now, especially after dotnet/coreclr#21409, and update the comment.

`ConvertFromUtf32` returns `string`: there's nothing we can do to avoid that in `ConvertFromUtf32`'s implementation as `string` is required by the signature.

**Comment by ahsonkhan** [comment]
> `ConvertFromUtf32` returns `string`: there's nothing we can do to avoid that in `ConvertFromUtf32`'s implementation as `string` is required by the signature.

Oh right, good point. The issue is not actionable and the comment is fine as is since the string is "temporary" and unnecessary only in the context of `UnicodeHelpers`. I incorrectly read the comment as `ConvertFromUtf32` is creating temporary strings unnecessarily outside of the string itself that is being returned.

Closing.
