### ISSUE TITLE
HTTP2: Consider adding support for PUSH_PROMISE

### ISSUE THREAD

**Issue by rmkerr** [dotnet/corefx#34192]
Our current implementation of HTTP2 immediately disables support for PUSH_PROMISE on opening a connection. We should consider implementing support for PUSH_PROMISE, and exposing an API allowing users to take advantage of this feature.

**Comment by Tratcher** [comment]
This is primarily a caching feature and HttpClient doesn’t have any built in caching.

Implementing this would require a new API to surface unsolicited responses all the way up the pipeline. We're talking about a breaking change to HttpMessageHandler to add a new abstract method. That API would be some kind of opt-in callback registration like `protected abstract IDisposable RegisterForPushPromise(Func<HttpResponseMessage, Task> callback)` where the return value lets you unregister. No idea what would happen if you had multiple registrations.

**Comment by scalablecory** [comment]
I can't think of common scenarios where `HttpClient` is being used that this would be useful in. Perhaps a hierarchical REST API.

The API design would be tricky to make this actually usable without introducing all sorts of complexity. I'm happy to put this off until we see more need.

**Comment by stephentoub** [comment]
Yeah, I suggest either closing this or pushing it out (no pun intended) to future until there's a real demonstrated need.

**Comment by scalablecory** [comment]
Closing until a use case is found;
