### ISSUE TITLE
Different behavior on .Net Framework and Core in SignedCms.CheckSignature

### ISSUE THREAD

**Issue by secana** [dotnet/corefx#34202]
I want to verify a signature contained in a CMS. I used the code below, which works fine on .Net Framework but not in .Net Core.

I've verified that this is the case with the following code:

```csharp
using System;
using System.IO;
using System.Security.Cryptography;
using System.Security.Cryptography.Pkcs;

namespace Framework
{
    class Program
    {
        static void Main(string[] args)
        {
            var rawCerts = File.ReadAllBytes("cert.dump");
            var signedCms = new SignedCms();
            signedCms.Decode(rawCerts);

            try
            {
                signedCms.CheckSignature(true);
                Console.WriteLine("Valid siganture.");
            }
            catch(CryptographicException e)
            {
                Console.Error.WriteLine(e.Message);
            }

            Console.ReadKey();
        }
    }
}
```
On .Net Core: "Invalid Siganture."
On .Net Framework: "Valid Signature."

I've tried to update System.Security.Cryptography.Pkcs to a preview version (4.6.0-preview.18571.3), but now the signedCms.Decode(rawCerts) fails with an CryptographicException: ASN1 corrupted data. exception.

I've attached the CMS I had the issues with. It's from a Firefox executable from 4 month ago.

[cert.zip](https://github.com/dotnet/corefx/files/2702903/cert.zip)

**Comment by vcsjones** [comment]
A quick look at this, it looks like netcoreapp doesn't like the timestamp. To reproduce it a little bit differently..

```csharp
    try
    {
        foreach(var info in signedCms.SignerInfos)
        {
            Console.WriteLine("Checking signature.");
            info.CheckSignature(true);

            Console.WriteLine("Checking counter signers");
            foreach(var counterSigner in info.CounterSignerInfos)
            {
                counterSigner.CheckSignature(true);
            }
        }
    }
    catch (CryptographicException e)
    {
        Console.Error.WriteLine(e.Message);
    }
```

The Authenticode signature is OK - it bombs on the timestamp. Looking into why.

**Comment by bartonjs** [comment]
Ah, CAPI is wrong.  That signature is invalid.

Taking the ModPow(signature, e, n) =>

```
0001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF0068B4F926343125DD26501368C199267119A2DE81
```

with a hash of `68B4F926343125DD26501368C199267119A2DE81`.

The correct PKCS1 signature block would be

```
0001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0030213009
06052B0E03021A050004140068B4F926343125DD26501368C199267119A2DE81
```

That is, the signature is missing the `SEQUENCE(OID(SHA-1), OCTETSTRING)` structure.

It's possible that CAPI is allowing for an older form of PKCS signature that neither CNG nor CommonCrypto permit; or CAPI historically just checked `00 01 FF` and "the last n bytes".  But the signature's definitely not valid.

**Comment by onovotny** [comment]
What created the original signature (incorrectly)?

**Comment by jariq** [comment]
> That is, the signature is missing the `SEQUENCE(OID(SHA-1), OCTETSTRING)` structure.

Just for the sake of completeness, that structure is called `DigestInfo` and is defined in [RFC3447](https://www.ietf.org/rfc/rfc3447.txt) as follows:

```
DigestInfo ::= SEQUENCE {
	digestAlgorithm AlgorithmIdentifier,
	digest OCTET STRING
}
```

**Comment by vcsjones** [comment]
OK, so the docs for `BCRYPT_PKCS1_PADDING_INFO` say a little more about this.

> pszAlgId: When verifying a signature, the verification fails if the OID that corresponds to this member is not the same as the OID in the signature. If there is no OID in the signature, then verification fails unless this member is NULL.

So it appears that CNG does allow for this, but you need to explicitly pass in null as the `pszAlgId` if I understand correctly. .NET Core appears to always require passing in a hash algorithm to `BCRYPT_PKCS1_PADDING_INFO`.

**Comment by vcsjones** [comment]
@onovotny 
>What created the original signature (incorrectly)?

I believe this came from Symentec's Legacy Timestamp Authority, http://timestamp.verisign.com/scripts/timstamp.dll. I just reproduced this again by submitting a timestamp to there.

This timestamp uses "legacy" Authenticode timestamps, not RFC3161. To answer a question you may be thinking, I don't think this impact Nuget Packages because Nuget packages do not support legacy timestamps, only RFC3161 timestamps. Symantec/DigiCert's timestamps appear to return correctly encoded signatures when using their RFC3161 timestamps.

**Comment by vcsjones** [comment]
For what it's worth, I'm pretty sure this Symantec TSA is _ancient_. I don't know how accurate Google's date mechanism is, but the earliest reference to this TSA [I could find][1] is 1996. The predates the standardization of RSASSA-PKCS1-v1_5 into an RFC by a few years.

[1]: https://www.google.com/search?q=http%3A%2F%2Ftimestamp.verisign.com%2Fscripts%2Ftimstamp.dll&client=firefox-b-1-ab&source=lnt&tbs=cdr%3A1%2Ccd_min%3A1%2F1%2F1990%2Ccd_max%3A12%2F31%2F1999&tbm=

**Comment by bartonjs** [comment]
FWIW: PKCS#1 v1.5 was published in 1993 (ftp://ftp.rsasecurity.com/pub/pkcs/ascii/pkcs-1.asc).

If the only case where there's a behavioral difference is when using a signature generated using a pre-1993 format, I'm inclined to say Won't Fix.

<sub>pre-1993 format? My first 'network' was a serial cable to play heads-up Rise of the Triad, published 1994... wow.  I don't know why these facts make me feel old at the moment.</sub>

**Comment by vcsjones** [comment]
>I'm inclined to say Won't Fix.

I don't think it is fixable without a significant amount of work. I looked at CommonCrypto and OpenSSL and I don't see a supported or easy way to get them to recognize the signature. It's unfortunate that this is a rather popular TSA though.

**Comment by secana** [comment]
@bartonjs I understand the "won't fix" but the signature I attached is from an up-to-date Firefox. So the problem exists with widely used and current software . Checking if there signature is valid, is not possible with the current state.

If a fix is not feasible in a short time, is there any way to code around it to get the same behavior on .Net Framework and Core?

**Comment by vcsjones** [comment]
>If a fix is not feasible in a short time, is there any way to code around it to get the same behavior on .Net Framework and Core?

Nothing trivial comes to my mind right now. CNG (and CommonCrypto and OpenSSL) will treat the RSA signature as invalid. You would have to use an API that uses CAPI to validate the signature, or find an RSA library that is willing to treat this signature is valid. Even then you'd have to get `SignedCms` to use it, which probably means having a local copy of the class as of .NET Core 2.2.

For .NET Core 3.0, you can replace the RSA sign/verify functions in `SignedCms` as of #26406. 

With that, you could write a wrapper around CAPI, or use another RSA library that tolerates the malformed signature. 

--------

If all you are trying to do is verify an Authenticode signature for a file, perhaps `WinVerifyTrustEx` is a better solution, albeit much more high level. It handles a lot of the nuances of validating an Authenticode signature, plus it works on all Authenticode-signable files, like MSI, APPX, PEs, etc.

**Comment by bartonjs** [comment]
I've been waiting for a while to close this _fait accompli_, having gotten Firefox to move to both a different TimeStamp Authority and to SHA-2 Authenticode in general, but they've been slower to change than I initially thought.

https://bugzilla.mozilla.org/show_bug.cgi?id=1531165 

I'm still currently of the opinion that non-RFC-conforming signatures is a thing that we don't want to bother supporting; but if there's more data in future we could certainly re-evaluate.
