### ISSUE TITLE
Possible copy-paste mistake in SqlConnection introduced by AAD Authentication work

### ISSUE THREAD

**Issue by stijnherreman** [dotnet/corefx#34205]
The work done for #13660 may have introduced a copy-paste mistake in `SqlConnection`. The change is present in the already released 2.2 (see #31039) and the planned release 3.0 (see #30342).

The possible mistake was noticed by @steji113 in the 2.2 PR. It appears that the change at https://github.com/dotnet/corefx/pull/31039/files#diff-78c5752d4a8ee85fdc3593a8851c86e9L1363 was copied to https://github.com/dotnet/corefx/pull/31039/files#diff-78c5752d4a8ee85fdc3593a8851c86e9L1406 and https://github.com/dotnet/corefx/pull/31039/files#diff-78c5752d4a8ee85fdc3593a8851c86e9L1444

Was this change meant to be done, or is it a mistake?

**Comment by Wraith2** [comment]
From what I can see I think this means there will be a lot of connection pool misses. Is that what you're seeing? lots of new connection throughput?

**Comment by stijnherreman** [comment]
I haven't switched that part of our code to CoreFX yet, so I don't know the impact. I created this issue to ensure it's being tracked, seeing as there's a lack of response in the PR itself.

**Comment by danmosemsft** [comment]
Tagging @AfsanehR @keeratsingh since as you point out, this already got into 2.2 bits so we should move quickly if it's going to cause a problem.

**Comment by saurabh500** [comment]
Replied https://github.com/dotnet/corefx/pull/31039#discussion_r243665371  based on the code in NetFx at https://github.com/Microsoft/referencesource/blob/master/System.Data/System/Data/SqlClient/SqlConnection.cs 

Impact of this bug based on my understanding of the area: 
1. The wrong connection pool will be cleared on a Change password using SecureString. As a result there will be impact on the functionality of the connections being used from the pool being cleared. 
2. The right connection pool will not be cleared after a password change. That would lead to unused connections in the pool which will be cleared out eventually (3-5 minutes) to bring the connection pool count, down to Min Pool Size in case the connections from the pool is unused. 

We should consider this for servicing.

**Comment by danmosemsft** [comment]
Maybe it's fortunate then that few people have consumed this change yet, due to our bug: https://github.com/dotnet/corefx/pull/33697

**Comment by Wraith2** [comment]
Oh, that's a weird api. a static method that changes a connection string parameter password and affects the pool at the same time.

**Comment by saurabh500** [comment]
@steji113 and @stijnherreman Thanks for pointing this out. 
Also it is good that you opened a new issue. A lot of times comments on Closed PRs and Closed Issue go un-monitored.

**Comment by steji113** [comment]
@saurabh500 absolutely, I should have thought to just open an issue initially. I also thought it seemed like it indicated a testing gap, as well. Thanks for the evaluation!

**Comment by danmosemsft** [comment]
@stijnherreman thanks again.

**Comment by AfsanehR** [comment]
I am going to close this since the fix is now both in master and Release/2.2 branch.  Thank you @stijnherreman for finding this issue 👍

**Comment by karelz** [comment]
Fixed in 3.0 in PR #34268.
Fixed in 2.2 in PR #34260.
