### ISSUE TITLE
free() vs HMAC_CTX_free() on a HMAC_CTX

### ISSUE THREAD

**Issue by omajid** [dotnet/corefx#34210]
This might be a stupid question. I am not an OpenSSL expert. I found a `free(ctx)` call that looks a bit surprising to me.

https://github.com/dotnet/corefx/blob/646a539c8654000ae014085abbaf8167d811a827/src/Native/Unix/System.Security.Cryptography.Native/pal_hmac.c#L34

Shouldn't this be a `HMAC_CTX_free(ctx)` instead?

**Comment by stephentoub** [comment]
cc: @bartonjs

**Comment by stephentoub** [comment]
> Shouldn't this be a HMAC_CTX_free(ctx) instead?

Certainly looks like it.
