### ISSUE TITLE
High CPU on ARM32 occasionally

### ISSUE THREAD

**Issue by aviviadi** [dotnet/corefx#34225]
Env: Running on Raspberry PI (Raspbian Stretch)
.NET Core 2.2

Scenario: Sending a small number of requests to the server occasionally cause a very high CPU spike.
This CPU spike is typically only on a single core and does  not correlate to any system call from `strace` that we could find.

We have ruled out GC as reason for high CPU because when we see such high CPU we broke into the process and this was what the GC was doing.

![image](https://user-images.githubusercontent.com/12054032/50384020-07c32980-06c7-11e9-9872-5f9400935f7d.png)

The high CPU event can take over 30 seconds to complete and goes away on its own.

When doing managed debugging, the following stack trace keeps popping up:

![image](https://user-images.githubusercontent.com/12054032/50383898-cd0cc180-06c5-11e9-94c5-79de2a853300.png)

I wonder if it is possible that this is stuck in the following loop?

https://github.com/dotnet/corefx/blob/master/src/System.IO.Pipelines/src/System/IO/Pipelines/Pipe.cs#L467-L474

The behavior is that once every N requests (where N is relatively low, a few dozens at most) we are seeing this high usage.
When we make another request, it usually goes away.

It is possible that because this is on 32 bits, we are using very small buffer, creating a very large chain of segments that should be freed?

**Comment by jkotas** [comment]
cc @pakrym @davidfowl

**Comment by jhakasjk** [comment]
Did you find the solution? Or any workaround?
@jkotas @aviviadi

**Comment by aviviadi** [comment]
No solution nor w/a.  Just waiting (on RPi about 30s to 1 minute in avg) for the 100% cpu (out of 400% available - 4 cores) to drop down.
I was not able to debug corefx, in order to find a solution @ Pipe.cs#L467.. I tried compiling relevant coreclr+corefx but I get 
```
LTTng-UST: Error (-17) while registering tracepoint probe. Duplicate registration of tracepoint probes having the same name is not allowed
```
Which I think related to : https://github.com/dotnet/coreclr/pull/21219

I tried to repro this on linux-x64 stronger machine (i7@5GHz,32GB Ram) but could not see 100% on any of the cores (even when stressing the repro test further)

**Comment by guillerot** [comment]
Hi.
Does anyone have more information about this issue ?
Regards.

**Comment by aviviadi** [comment]
@guillerot 
This reproduced every time in dotnet's runtime 2.2.0, however the same setup and test doesn't reproduced in 2.2.1 (can't tell why).
Moreover, now corefx can be modified and debugging shows no issue at https://github.com/dotnet/corefx/blob/master/src/System.IO.Pipelines/src/System/IO/Pipelines/Pipe.cs#L468

So, please try to test your setup in latest 2.2.1 (sdk 2.2.102).
If still reproduces, please let me know, so I can retry again and again.

**Comment by aviviadi** [comment]
Seems not reproducable on 2.2.1, cause is unknown.
