### ISSUE TITLE
API suggestion: System.IO.DirectoryNotEmptyException

### ISSUE THREAD

**Issue by Neme12** [dotnet/corefx#34220]
Scenario: I want to delete a folder if it's empty.

A naive implementation would be:
```c#
if (!Directory.EnumerateFileSystemEntries(dir).Any())
    Directory.Delete(dir);
```

The problem with this is that I'm accessing the file system at 2 points in time. There's no guarantee that because `EnumerateFileSystemEntries` returned nothing, the directory will still be empty when calling `Directory.Delete`.

To be robust, we should just call `Directory.Delete` and catch the exception it throws in case the directory wasn't empty. The problem is that it throws `System.IO.IOException` with a message of "The directory is not empty". There is no specific exception type for this scenario. At first it would seem that the only thing we can do is catch the exception depending on its message string (which is a terrible idea), but luckily, there *is* a specific HResult for this failure, leaving us with:

```c#
try
{
    Directory.Delete(dir);
}
catch (IOException e) when (e.HResult == -2147024751) // DIR_NOT_EMPTY
{
}
```
This works OK but makes the code seem unreadable and maybe even brittle because we're depending on a magic constant that comes somewhere from the Windows API. I'm not sure if this code works outside of Windows at all, but even if it does, it's definitely not obvious.

Please add a dedicated exception type for this kind of failure.

**Comment by Neme12** [comment]
Question: Why not just catch IOException. Why would you need to differentiate between this failure and other IO failures?

Answer: If the directory isn't empty, that's fine and we don't need to do anything in that scenario. But in case of other IO failures, we might want to show a warning or a "retry" dialog.

**Comment by danmosemsft** [comment]
Let's discuss in https://github.com/dotnet/corefx/issues/34221

**Comment by danmosemsft** [comment]
Per discussion in https://github.com/dotnet/corefx/issues/34221 we prefer to add FileSystemError enum and matching property to IOException. That would include an enum entry for this case.

I'll close this in favor of that. Still need a volunteer to do the work of defining the proposed enum.
