### ISSUE TITLE
Issue with CookieContainer when use HttpClientFactory

### ISSUE THREAD

**Issue by uyquoc** [dotnet/corefx#34244]
Since `HttpClientHandler` objects are pooled when using `HttpClientFactory`, we can have a thread-safe issue with `CookieContainer` of  `HttpClientHandler` object. A sample case as follows:
Assume we have a web application call to api/Token (GET) of API server.

Web:
```c#
       public async Task<string> GetToken()

        {
            var httpClient = _clientFactory.CreateClient();
            var response = await httpClient.GetAsync("http://api.local:5089/api/token");
            var token = await response.Content.ReadAsStringAsync();
            return token;
        }
```

API:
```c#
        public ActionResult<string> Get()
        {   
            string token = HttpContext.Request.Cookies.ContainsKey("Token") ? 
                           HttpContext.Request.Cookies["Token"] : Guid.NewGuid().ToString();
            
            HttpContext.Response.Cookies.Append("Token", token);
            return token;
        }
```

After the first request to API, in Web application, `response.Headers.GetValues("Set-Cookies")` will show "Token" cookie's value equals "abc"
After the second request to API, in Web application, `response.Headers.GetValues("Set-Cookies")` will show "Token" cookie's value also equals "abc"
If we use `new HttpClient()`, each request to API, we will get new Token value, but we cannot achieve this 
purpose with `HttpClientFatory`. How could we deal with this problem when we have to use Cookie in API?

**Comment by karelz** [comment]
It looks like the types you're using are `Microsoft.AspNetCore.Http.HttpRequest`. If that's true, then ASP.NET Core repos would be the right place to ask.

**Comment by uyquoc** [comment]
@karelz, Actually, I thought it's related to `HttpClientFactory`, but `HttpClientFactory` repos does not allowed to create new issue. Ok, I will move this to `aspnetcore`. Thank you!

**Comment by uyquoc** [comment]
Thanks @karelz. It's my bad :D

**Comment by nglpg** [comment]
Hi @karelz @uyquoc ,
Do you have any samples on the cookie container implementation? We have the similar situation where we get a token first and then we add this token as cookie to the next request. Single threaded calls are going fine but when multi threaded we get the below error is thrown from the await base.SendAsync(message, cancellationToken) line of code in the DelegatingHandler implementation class. 

An existing connection was forcibly closed by the remote host…"

We are not sure what we are doing wrong here. Any help will be highly appreciated.
Thanks
