### ISSUE TITLE
Environment.GetCommandLineArgs behaves differently

### ISSUE THREAD

**Issue by matkoch** [dotnet/corefx#34240]
Maybe I'm missing something, but invoking `app.dll --param "string value"` yields different results for `Environment.GetCommandLineArgs`.

On Windows: `new[] { "app.dll", "--param", "string value" }`
On MacOS: `new[] { "app.dll", "--param", "string", "value" }`

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.101/
```

**Comment by joshudson** [comment]
Please post your whole invocation. app.dll isn't a program and can't be started directly.

**Comment by matkoch** [comment]
Sorry, issue seems to be with my bash script.
