### ISSUE TITLE
Easy way to use ValueTask with IValueTaskSource

### ISSUE THREAD

**Issue by juepiezhongren** [dotnet/corefx#34242]
ValueTask with IValueTaskSource is great but not easy to use. In a valueTask-return async method, there is no way to ctor with a pooled iValueTaskSource instance. 
So, What about to create SourceStrategyAttribute to make a valueTask-return method buffed by IValueTaskSource?
```
[SourceStrategy]
async ValueTask mAsync(){
   await ......
   .......
}
```
And the compiler would do the tricky part of iValueTaskSource instance injecting.
@stephentoub

**Comment by stephentoub** [comment]
That does what?

**Comment by juepiezhongren** [comment]
in a valueTask-return async method, there is no way to ctor with a pooled iValueTaskSource instance @stephentoub

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/coreclr/issues/20905. Also see https://github.com/dotnet/csharplang/issues/1407. Thanks.

**Comment by juepiezhongren** [comment]
good toknow
