### ISSUE TITLE
LD_LIBRARY_PATH icu issue

### ISSUE THREAD

**Issue by livarcocc** [dotnet/corefx#34248]
_From @spushpendra2000 on December 26, 2018 17:32_

## Steps to reproduce
I am using dotnet core 2.1 on centos. and trying to load the dll.

When running , i am getting this error
FailFast:
Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.AppDomain.InitializeCompatibilityFlags()
   at System.AppDomain.Setup(System.Object)
Aborted (core dumped)

I can see the suggestion as per the link
https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md

But I cannot change the icu path and when i tried creating the local folder 'netcoredeps' where my dll is residing it never work and i keep getting the same error.
Only after the setting the LD_LIBRARY_PATH, it is working.. Please suggest who to resolve this
## Environment data
`dotnet --info` output:

_Copied from original issue: dotnet/cli#10509_

**Comment by livarcocc** [comment]
_From @spushpendra2000 on December 26, 2018 17:38_

Even if i am keeping all libicu files in the same folder where my dll is residing, i am still getting the same error

**Comment by karelz** [comment]
@krwq @tarekgh cc @janvorli

**Comment by danmosemsft** [comment]
`ldd` may help see where it is looking.

**Comment by spushpendra2000** [comment]
ldd on dll is giving the message as 
      not a dynamic executable

**Comment by danmosemsft** [comment]
Can you share the full output of `ldd -v dotnet` where `dotnet` is the one you are using?

**Comment by janvorli** [comment]
@spushpendra2000 what is preventing you to follow the steps described in the https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md? That is the intended way of using .NET core on RHEL 6 / CentOS 6. 
The `netcoredeps` should work but please note that it only works with published apps (using dotnet publish) where you create the netcoredeps in the same directory where your application executable is located (the file name of the published application doesn't have any extension). What was the way you've tried to use it? Have you copied all the ICU .so files into that directory (just flat, without any subdirectories)?

**Comment by spushpendra2000** [comment]
You can close this.. i went ahead setting the ld path and issue is resolved.
