### ISSUE TITLE
CommonSecurityDescriptor losts SACL in sddl format

### ISSUE THREAD

**Issue by FDUdannychen** [dotnet/corefx#34253]
```c#
        static void Main(string[] args)
        {
            var before = "O:SYG:SYD:S:(AU;OISAFA;0x100000;;;S-1-5-21-3530929314-3291925079-3043250533-18123169)(AU;CISAFA;0x100000;;;S-1-5-21-3530929314-3291925079-3043250533-18123169)";
            var csd = new CommonSecurityDescriptor(true, true, before);
            var after = csd.GetSddlForm(AccessControlSections.All);
            Console.WriteLine(before);
            Console.WriteLine(after);
        }
```
The output:
```
O:SYG:SYD:S:(AU;OISAFA;0x100000;;;S-1-5-21-3530929314-3291925079-3043250533-18123169)(AU;CISAFA;0x100000;;;S-1-5-21-3530929314-3291925079-3043250533-18123169)
O:SYG:SYD:S:(AU;CISAFA;0x100000;;;S-1-5-21-3530929314-3291925079-3043250533-18123169)
```
You can see the first SACL is gone. Is it a bug or I'm missing something?

**Comment by am11** [comment]
.NET Framework (tested on 4.7.1) has the same behavior.

The value of SDDL is transformed to binary by `CommonSecurityDescriptor`. The container inheritance (CI) supersedes object inheritance (OI), so when the SDDL form is saved internally as bytes, overlapping ACEs segments get folded. In above example, SDDL form has two ACE segments (`(xx;xx;xxx;;;xx)`) in a descriptor with same file access right (`0x100000`) and trustee (`S-1-5-21-3530929314-3291925079-3043250533-18123169`). They only differ by [ACE control flags](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/ns-ntifs-_ace_header#members).

This is what we get when checking equality before/after the processing of SDDLs with various control flags, while keeping the file access and SID constant:

|		|	CI		|	OI		|	NP		|	IO		|	ID		|	SA		|	FA		|
|:------|:----------|:----------|:----------|:----------|:----------|:----------|:----------|
|	CI	|	False	|	False	|	True	|	False	|	True	|	False	|	False	|
|	OI	|	False	|	False	|	True	|	False	|	True	|	False	|	False	|
|	NP	|	True	|	True	|	False	|	False	|	True	|	False	|	False	|
|	IO	|	False	|	False	|	False	|	False	|	False	|	False	|	False	|
|	ID	|	True	|	True	|	True	|	False	|	True	|	False	|	False	|
|	SA	|	False	|	False	|	False	|	False	|	False	|	False	|	False	|
|	FA	|	False	|	False	|	False	|	False	|	False	|	False	|	False	|

<details>
  <summary>Code</summary>
<br/>

`Program.cs`

```c#
using System;
using System.Security.AccessControl;

public class TestAceFlagsFolding
{
    static void Main(string[] args)
    {
        var aceFlags = new[] { "CI", "OI", "NP", "IO", "ID", "SA", "FA" };

        // write header
        Console.Write("|\t\t|");
        foreach (var flag in aceFlags) Console.Write("\t" + flag + "\t\t|");
        Console.WriteLine();

        // write separator
        Console.Write("|:------");
        foreach (var flag in aceFlags) Console.Write("|:----------");
        Console.WriteLine("|");

        // write rows
        foreach (var flagX in aceFlags)
        {
            Console.Write("|\t" + flagX + "\t|");
            foreach (var flagY in aceFlags)
            {
                var before = $"O:SYG:SYD:S:(AU;{flagX}SA;0x100000;;;S-1-5-21-3530929314-3291925079-3043250533-18123169)(AU;{flagY}SA;0x100000;;;S-1-5-21-3530929314-3291925079-3043250533-18123169)";
                var csd = new CommonSecurityDescriptor(true, true, before);
                var after = csd.GetSddlForm(AccessControlSections.All);
                Console.Write("\t" + (before == after) + "\t|");
            }
            Console.WriteLine();
        }
    }
}
```

`TestAceFlagsFolding.csproj`

```csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp3.0;net471</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Security.AccessControl" Version="4.5.0" />
  </ItemGroup>
</Project>
```

Run: `dotnet3.0.100-preview009812-win64\dotnet.exe run -f netcoreapp3.0 > AceFlagsComparison.txt`
</details>
<br />

Changing the file access right (to e.g. `0x200000`) or trustee's SID in one of the ACE segment, this folding does not occur and `GetSddlForm` method returns the verbatim string.

**Comment by bartonjs** [comment]
Based on @am11's explanation it seems like there's no bug here.  Closing.

**Comment by ChrisGuzak** [comment]
> Based on @am11's explanation it seems like there's no bug here. Closing.

I think there is a bug but perhaps a different case. here is a post on this when using a SD with just a SCAL. https://social.msdn.microsoft.com/Forums/en-US/21235b27-3f6f-4adc-aa42-76a1ac28a327/mandatory-label-saclace-in-commonsecuritydescriptor-class

I've seen this myself, inspecting the security descriptors of COM/WinRT objects in the registry. My C++ code using the Win32 APIs gets the expected results, the .Net code (via PowerShell) gets "S:" for SACLs that use mandatory integrity labels.  here is a test case
```
    function Convert-SddlToHex { 
        [cmdletbinding()] param( [parameter(Mandatory = $true)] [String] $Sddl ) 

        $sd = New-Object System.Security.AccessControl.RawSecurityDescriptor $Sddl
        $Bytes = New-Object 'byte[]' $sd.BinaryLength
        $sd.GetBinaryForm($Bytes, 0)
        $HexString = [System.Text.StringBuilder]::new($Bytes.Length * 2) 
        ForEach ($byte in $Bytes) { 
            $HexString.AppendFormat("{0:x2}", $byte) | Out-Null 
        } 
        $HexString.ToString() 
    }

    # Full test case
    $sddl = 'O:BAG:BAD:(A;;CCDCSW;;;IU)(A;;CCDCSW;;;SY)(A;;CCDCSW;;;AC)(A;;CCDCSW;;;S-1-15-3-1024-1502825166-1963708345-2616377461-2562897074-4192028372-3968301570-1997628692-1435953622)S:'
    $hex = Convert-SddlToHex $sddl
    $sddl2 = Convert-HexToSddl $hex
    if ($sddl -eq $sddl2) { Write-Host 'Conversion from Sddl to Hex to Sddl verified' } else { Write-Host 'Conversion failed' }
```

**Comment by KalleOlaviNiemitalo** [comment]
Container inheritance (CI) does not really supersede object inheritance (OI). However, constructing CommonSecurityDescriptor with `isDS: true` causes CommonAcl to discard the OI flags; I don't know whether that is the correct thing to do, but at least it appears to be by design. <https://github.com/dotnet/corefx/blob/1bb52e6a3db7f3673a3825f3677b9f27b9af99aa/src/System.Security.AccessControl/src/System/Security/AccessControl/ACL.cs#L717-L724>

If you instead construct the CommonSecurityDescriptor with `isDS: false`, then .NET Framework 4.8 merges the OI and CI ACEs and gives `O:SYG:SYD:S:(AU;OICISAFA;0x100000;;;S-1-5-21-3530929314-3291925079-3043250533-18123169)`, which I think is functionally equivalent to the input SDDL. I did not test that with .NET Core.
