### ISSUE TITLE
[Infra] Report better error when available CMake version is not sufficient

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#34254]
Currently the build fails with the following error when using older CMake than required:

```
CMake Error: Could not create named generator Visual Studio 15 2017 Win64
```

This is with CMake version 3.6.2.
The bootstrapper should check for the version of required tools and report an error if the minimal required version isn't installed. 

The minimal required version should also be documented here: https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md#required-software only mentions CMake is needed but doesn't specify the version

**Comment by safern** [comment]
We now specify the minimum version in the docs :smile: 

https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md#required-software

Assigning myself.

**Comment by Zenexer** [comment]
The documentation specifies that 3.14.0 should be sufficient, but it's not.  I had to install 3.14.3.

**Comment by ViktorHofer** [comment]
Closing, I just updated the required versions in https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md#required-software
