### ISSUE TITLE
System.IO.File won't lock file on SLES 12.3

### ISSUE THREAD

**Issue by PiGi78** [dotnet/corefx#34264]
File locks seem don't work on SLES 12.3

For give you an example, I did a simple program that manages locks using a FileStream.
If you look at the attached LockManager, it manages the locks in this way:
- Acquire the lock: Opens a FileStream for write and shares it only for read
- Check if locked: Tries to open a new FileStream for write on the same file. If an exception is thrown, then the file is locked. Elsewhere it is not locked
- Release the lock: Closes the FileStream and deletes the file from the FileSystem

So, in the example program:
- An instance of the LockManager locks the file "main"
- A different instance of the LockManager tries to locks the same file

Since the file is alreary locked, the program will go in a kind of dead lock (you have to kill it with ctr+c).

If you run it on a Windows system, it works good.
On SLES 12.3, the second LockManager can acquire the lock on the file. That means that the FileShare doesn't work.

I hope it can help you

[TestLock.zip](https://github.com/dotnet/corefx/files/2715007/TestLock.zip)

**Comment by danmosemsft** [comment]
Does it work fine on any other distros you have access to? Would also be interesting to know about Mac.

Any interest in debugging some?

**Comment by PiGi78** [comment]
Sorry

I have no other OS where to test it.
Maybe in the next days I can find a Mac (a friend of mine), but right now I can't test it in any other platform

**Comment by PiGi78** [comment]
I did a test on a Mac (last OS and last .NET core 2.2).
I have the same issue

Let me know

**Comment by danmosemsft** [comment]
Thanks. Would you like to try investigation (debugging or code inspection)? It might bea  while before we can look.

**Comment by PiGi78** [comment]
I would like to do it, but I don't know how...
There is a tutorial or any documentation on how to do it?

**Comment by danmosemsft** [comment]
Hmm, it would probably not be a good issue to start with, if you're new to investigating this kind of issue.

@stephentoub do you recall any issues of this sort from the past?

**Comment by PiGi78** [comment]
I'm sorry I can't help you.

If you'd like and/or need help, let me know what kind of issue I can start to investigate...
But I'm sorry: I'm new to develop any open source project (except few made by myself). 
So, I'll need also some links to learn how to move for do the work.

Thank you in advance

**Comment by stephentoub** [comment]
There are only two file lock modes on Unix: shared and exclusive.  So we map FileShare.None to exclusive and ~FileShare.None to shared.  From a file lock perspective on Unix, then, there's no difference between using FileShare.Read or FileShare.Write or FileShare.ReadWrite: it's creating a shared lock.  If in your code you change FileShare.Read to FileShare.None, you should see it behave the way you want.

**Comment by danmosemsft** [comment]
Agh, thanks @stephentoub I should have seen that.

**Comment by PiGi78** [comment]
Thank you!
It seams to work...

Just for know: why didn't you raise a NotSupportedException? 
It will give lot of advantages:
- The library doesn't work as expected, so better have an exception than an unexpected behaviour
- With the exception, anybody will understand that the code doesn't work on the OS and can change the code with easy (simply check the kind of OS where the library is running and use different kind of share)
- It will be managed in the same way of other situations. Few months ago I did try to use a function that works only on Windows and the code gave me a "NotSupportedException" (I didn't remember the example, but I remember the exception)


In any way, I will change my code and anything will work.

Thank you in advance
