### ISSUE TITLE
Different behavior of Path.GetDirectoryName() in netcoreapp2.2 is not documented

### ISSUE THREAD

**Issue by Marusyk** [dotnet/corefx#34265]
As described in #19334 there is a difference in behavior here as .Net Core returns `null` when `Path.GetDirectoryName(string.Empty)` and Desktop throws and `ArgumentException` 

But [documentations](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getdirectoryname?view=netcore-2.2#System_IO_Path_GetDirectoryName_System_String_) says that an exception throws when the path parameter contains invalid characters, is empty, or contains only white spaces. 

Should it be changed to ?:
https://github.com/dotnet/corefx/blob/4a514a62115ccf94636ca96e2d32af7d330d05f6/src/Common/src/CoreLib/System/IO/Path.cs#L77

Related #19337

**Comment by jkotas** [comment]
Intentionally introduced by https://github.com/dotnet/coreclr/pull/16447

**Comment by JeremyKuhne** [comment]
> This should probably be fixed as desktop behavior is reasonable and it could break some ported code.

It could, but I felt it was more likely to bite people long term as it is inconsistent with the other APIs. Additionally it used to throw for just spaces as well, which is actually legitimate for xplat scenarios. I have an active issue on the docs: https://github.com/dotnet/dotnet-api-docs/issues/1685
