### ISSUE TITLE
Process.Start fails to launch files

### ISSUE THREAD

**Issue by Symbai** [dotnet/corefx#34270]
Hi

.NET Core version: 3.0.100-preview-009844

### Issue:
Process.Start() fails on launching files, it throws an Win32Exception "The specified executable is not a valid application for this OS platform". 

### Expected:
It should open the file with whatever program is associated to open this file.

### Why is this a bug:
I'm reporting this because it works absolutely fine in .NET Framework. With .NET Core 3.0 this could be a breaking change if this is intended. And when it is, what is the ".NET Core way" to launch a file?

.NET docs say: https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.start?view=netcore-2.2

`Start(String) | Starts a process resource by specifying the name of a document or application file and associates the resource with a new Process component.`

### Example:
```
class Program
    {
        static void Main(string[] args)
        {
            var file = Path.Combine(Path.GetDirectoryName(Assembly.GetEntryAssembly().Location) + "\\output.txt");
            File.WriteAllText(file, "test");
            Process.Start(file); //throws
        }
    }
```

**Comment by danmosemsft** [comment]
@Symbai this is because you are not launching an executable, you are relying on the shell to find the executable. Which requires the parameter UseShellExecute to be true. In .NET Framework that is default, in .NET Core we chose false. https://github.com/dotnet/corefx/issues/18949

can you set it explicitly to true and confirm it works?

**Comment by Symbai** [comment]
@danmosemsft Yes it works now, thank you I'm closing this issue. I wish there would be a list of breaking changes like this one where devs coming from .NET framework can take a look at. Or at least a big red statement on Docs mentioning "This is different in .NET Core comparing to .NET Framework". Otherwise it will be a pain to start with .NET Core for beginners.

**Comment by danmosemsft** [comment]
@Symbai that's a fair comment. @karelz @mairaw  do you know of a list somewhere ?

**Comment by karelz** [comment]
I am not aware of any list of "breaking" changes like this one. AFAIK we have just a handful, they are not on main paths and/or are self-explanatory.
@mairaw any suggestion how to capture list of platform differences?
