### ISSUE TITLE
API Proposal: Add public API for querying the number of thread pool queued work items

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#34277]
Similar to how we have API for querying the number of threads in the thread pool, it would be great to have a public API to get the number of globally queued and locally queued (across all thread pool threads) items. This would be extremely useful for diagnostics. I recently hacked something like this together by using [private reflection](https://github.com/aspnet/AspNetCore/pull/6144/commits/cc0c62d4d64e6b4776a55efa7d8390e901f7e7cb) to get this data.

```C#
public static class ThreadPool
{
    public static void GetQueuedWorkItems(out int globalWorkItems, out int localWorkItems);
}
```

Alternatively, we can break it up so that they are 2 different calls since it's cheaper to get the globally queued work items than the locally queued work items.

cc @stephentoub

**Comment by GSPP** [comment]
Returning a struct would be cleaner. `out` forces side-effects and is more awkward to calling code.

**Comment by kouvel** [comment]
I have folded this into properties as part of https://github.com/dotnet/corefx/issues/35500. One question that was raised during the API review is if it is necessary to distinguish pending local and global work items. For the purpose of determining whether the thread pool is stalled, the total pending work item count would suffice. Is there another scenario where it would be beneficial to separate them?

**Comment by davidfowl** [comment]
I'm going to close this, I don't think we need to expose the local queues (as it's pretty much an implementation detail anyways).
