### ISSUE TITLE
 The code generated is wrong when the property is a generic type

### ISSUE THREAD

**Issue by hzexe** [dotnet/corefx#34287]
In System.CodeDom project:
`
 string type = typeof(int?).Name;
CodeMemberProperty prty = new CodeMemberProperty();
prty.Name = "CityCode";
prty.Type = new CodeTypeReference(type);
 prty.Attributes = MemberAttributes.Public| MemberAttributes.Final;
.....
`
Then the code generated is:

`
 public Nullable<> CityCode
`

**Comment by Tornhoof** [comment]
Why do you use the typeName as input for the ``CodeTypeReference``?
Take a look at what ``string type = typeof(int?).Name;`` outputs: it's ``Nullable`1``, there is no ``int`` in there anymore, so the ``CodeTypeReference`` can't produce the output you expect.
Use the type directly in ``CodeTypeReference``, e.g. ``new CodeTypeReference(typeof(int?));`` then it will work.

**Comment by krwq** [comment]
Closing since there seems to be solution here. Please reopen if you feel anything should happen here
