### ISSUE TITLE
Delete to recycle bin

### ISSUE THREAD

**Issue by Symbai** [dotnet/corefx#34297]
Can we have an option to delete files / directories to recycle bin? Such an option exists on VB for a long time, it would be very useful when it can be added to C# and .NET Core so we don't have to reference VB and preferably don't display any dialogs etc.

```
My.Computer.FileSystem.DeleteFile(
  "C:\test.txt",
  FileIO.UIOption.AllDialogs,
  FileIO.RecycleOption.SendToRecycleBin,
  FileIO.UICancelOption.ThrowException)
```

**Comment by Clockwork-Muse** [comment]
... I think I'm more curious _why_ you think you want this feature.  Generally, if it's a file the user never sees/has "easy" access to (ie, something in the AppData directory), they're unlikely to even know it exists, much less try to recover such a file.    
If it is a known file, you're in one of two boats:
 1. If it's a command line utility, you probably shouldn't be deleting files at all.
 2. If it's a graphical program, you should be accessing the file via one of the standard dialog windows, which would handle deletes for you.

If you're trying to get something like a recoverable version of the file, that belongs in a data directory, and managed differently - it shouldn't really be a separate file to the user, but that the history of their data used to look different.

So, what is it, exactly, that you're doing here?

**Comment by jkotas** [comment]
It would be a API that is very specific to Windows UI Shell. APIs like that do not belong to CoreFX.

You can do this by PInvoking into the Windows API that does that
https://docs.microsoft.com/en-us/windows/desktop/api/shellapi/nf-shellapi-shfileoperationw . This also allows you to control myriad of options that this comes with.

**Comment by joshudson** [comment]
@jkotas: Not so much Windows specific. https://www.freedesktop.org/wiki/Specifications/trash-spec/

Of course it may well be out of scope all the same.

**Comment by Symbai** [comment]
There are windows APIs and there might be questions about "Why is this needed", hence, why DownloadString in webclient exists when downloaddata exists already and can be converted to a string? These kind of discussions can be discussed for everything at any time.

My request was about adding this possibility as a managed way to .NET Core so it works on all platforms including Linux and Macos. It can be dropped by saying no, or it can be let opened for upvotes and volunteers to create a pull request for it. But please avoid telling me there are workarounds for this or that as this is NOT what this request was about and I'm already very well aware of these or that workaround like all others interesting in this option.

**Comment by MgSam** [comment]
@Clockwork-Muse That's an awful lot of assumptions to make about software which you know literally nothing about. Who are you to say that no application can have its own file explorer that should delete files to the recycle bin? 

As a simple and obvious example, every IDE exposes the files of the project its working on. Why shouldn't the authors of such IDEs be able to simply use .NET to write those deleted files to the recycle bin?

**Comment by MgSam** [comment]
@jkotas How exactly is this Windows specific? Most user-facing desktop OSs for the last 20 years have had recycle bins.

**Comment by am11** [comment]
Generally API proposals in CoreFX go through challenging questions, opposing views and proposers are asked to follow some [guidelines](https://github.com/dotnet/corefx/blob/f74b39562ad0e3b33715172d48eced02c7ca384f/Documentation/project-docs/api-review-process.md), this is to determine the merits of proposed API and gauge the facts like; is it really needed. :)

Personally, I like this proposal and consider `RecycleBin` or `Trashcan` interchangeable terms.

Wine implements v0.7 of the above mentioned FreeDesktop spec, with counterparts for macOS and Windows. Their public API is of the form: `BOOL TRASH_TrashFile(LPCWSTR wszPath)`: [wine-mirror/wine/trash.c](https://github.com/wine-mirror/wine/blob/25cc380b8ed41652b135657ef7651beef2f20ae4/dlls/shell32/trash.c#L196)

In node.js, a community package provides this facility, which has implementation for various platforms:: [sindresorhus/trash/lib/](https://github.com/sindresorhus/trash/tree/master/lib).

**Proposed APIs**

```diff
namespace System.IO
{
    public static partial class Directory
    {
        public static void Delete(string path) { }
+       public static void Delete(string path, bool moveToTrash) { }
        public static void Delete(string path, bool recursive) { }
+       public static void Delete(string path, bool recursive, bool moveToTrash) { }
    }
    public sealed partial class DirectoryInfo : System.IO.FileSystemInfo
    {
        public override void Delete() { }
+       public override void Delete(bool moveToTrash) { }
        public void Delete(bool recursive) { }
+       public void Delete(bool recursive, bool moveToTrash) { }
    }
    public static partial class File
    {
        public static void Delete(string path) { }
+       public static void Delete(string path, bool moveToTrash) { }
    }
    public sealed partial class FileInfo : System.IO.FileSystemInfo
    {
        public override void Delete() { }
+       public override void Delete(bool moveToTrash) { }
    }

    public abstract partial class FileSystemInfo : System.MarshalByRefObject, System.Runtime.Serialization.ISerializable
    {
        public abstract void Delete();
+       public abstract void Delete(bool moveToTrash);
    }
}
```

In case of non-desktop environments (text-mode/headless), which do not have trashcan-like artifact available, implementation can throw a standard `PlatformNotSupportedException` based on the class of platform.

An alternative approach could be to issue a specialized exception based on the trashcan existence check:

```diff
namespace System.IO
{
+    public class TrashcanNotFoundException : Exception { }
}
```

User can catch these exceptions and chose to create a trash can directory, if not exists.

**Comment by gfoidl** [comment]
> An alternative approach could be to issue a specialized exception based on the trashcan existence check

Or provide a property `IsTrashcanAvailable`, so this can be checked beforehand instead of using exceptions for flow-control.

**Comment by jkotas** [comment]
> How exactly is this Windows specific? Most user-facing desktop OSs for the last 20 years have had recycle bins.

CoreFX is focused on appmodel neutral APIs.

This concept is specific to desktop OS appmodels. This API belongs to libraries that are focused on providing abstractions over desktop OS appmodels.

> In node.js, a community package provides this facility

Community package would a great fit for this in .NET as well. It does not make sense to have appmodel-specific APIs in the "core".

**Comment by vladd** [comment]
@am11 
>      public static void Delete(string path, bool moveToTrash) { }
>      public static void Delete(string path, bool recursive) { }
This wouldn't compile, as the two functions differ only in parameter name.
(Sorry for nitpicking.)

**Comment by am11** [comment]
@vladd, thanks for the catch, I have modified the method names to (approximately) match the title of this issue. :)

@gfoidl, good point about flow-control, I have added the property. I have kept the TNFE, which perhaps could be just a specialization of `DirectoryNotFoundException`?

@jkotas, agree that adding more appmodel-aware APIs might clutter the core. I think .NET and node.js differ in a way that in node.js, almost everything comes from community packages and not much to compare with CoreFX/BCL.

**Comment by jkotas** [comment]
>  .NET and node.js differ in a way that in node.js, almost everything comes from community packages and not much to compare with CoreFX/BCL

The model where everything comes from CoreFX/BCL, including app-model specific APIs, is not scalable and sustainable. We need to be working towards healthy .NET ecosystem, with more popular community packages than there is today.

**Comment by danmosemsft** [comment]
If anyone interested enough in this API creates a NuGet package, please do share a link here for everyone else.
