### ISSUE TITLE
Results are different when executed using "dotnet vstest" vs "Test Explorer" from Visual studio

### ISSUE THREAD

**Issue by jaydeept** [dotnet/corefx#34290]
I am using `System.Diagnostics.StackFrame` class inside my `log4net` related code where I am seeing an issue with API called `GetMethod()`. When I execute from Test Explorer, the error is something like below for `KeyNotFoundExcpetion`:

> Thrown System.Collections.Generic.KeyNotFoundException "testMessage"\r\n at LoggingUnitTests.Log4NetLogTestsLoggingEnabled.GetStackFramesRecursive (source file unavailable)\r\n at LoggingUnitTests.Log4NetLogTestsLoggingEnabled.GetStackFrames (source file unavailable)

While using **dotnet vstest** the error is something like:

> Thrown System.Collections.Generic.KeyNotFoundException "testMessage"\r\n at LoggingUnitTests.Log4NetLogTestsLoggingEnabled.GetStackFramesRecursive (source file unavailable)\r\n at LoggingUnitTests.Log4NetLogTestsLoggingEnabled.mytestcasename (source file unavailable)

If you will notice, the test case name i.e. mytestcasename is being added in error message string when executing from dotnet vstest. This inconsistent behavior should have been fixed.

I would like to highlight over here that `GetStackFrames()` is my private method I have created inside my Test Class which is being invoked from my Test Case.

**Comment by ViktorHofer** [comment]
Maybe its related to inlining but this definitely doesn't belong into corefx but into Microsoft/vstest. Moving.

**Comment by ViktorHofer** [comment]
Moved to https://github.com/Microsoft/vstest/issues/1885
