### ISSUE TITLE
Do not inject Request-Id header if injected by tracing system

### ISSUE THREAD

**Issue by lmolkova** [dotnet/corefx#34299]
System.Net.Http implements tracing with DiagnosticsSource. When there is a listener (tracing system), 
HttpClient injects [DiagnosticsHandler](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs#L82) and it adds outgoing request header (`Request-Id`) to pass a unique id to the next service for correlation.

Tracing system may want to overwrite this header and the major scenario for this is backward compatibility (scenario is described below).

If a tracing system attempts to add `Request-Id` header, DiagnosticsHandler in HttpClient will add another one, breaking correlation with downstream services.

### Scenario details:
In .NET 3.0 we are going to change the correlation protocol to [W3C distributed tracing](https://github.com/w3c/distributed-tracing) in DiagnosticSource package. 
Here are  the changes were designed and discussed with @vancem : https://github.com/dotnet/corefx/pull/33207 

DiagnosticSource is OOB package and a new version of DiagnosticSource (that ships with 3.0) may be used with corefx 2.1 or 2.2.
In 3.0 `Activity.Id` in some cases will not comply with the current protocol and passing it in the Request-Id will be invalid, i.e. using new DiagnosticSource with corefx 2.1 and 2.2 will be invalid in these cases.

By default, when a tracing system does not do special configuration that forces new format, there are not backward-compatibility issues.

But when tracing system configures Activity to break backward compatibility and force new format, causing the above issue, becomes responsible to implement backward compatibility on its own.

This means a tracing system will need to inject Request-Id header in the correct format (if it wants to preserve backward-compatibility).

**Comment by noahfalk** [comment]
@lmolkova - This issue has PRs merged long ago, is it done?

**Comment by lmolkova** [comment]
@noahfalk 
yes, it's done
