### ISSUE TITLE
Support for DLLImport?

### ISSUE THREAD

**Issue by xanather** [dotnet/corefx#343]
I was wondering if .NET Core will support invoking native code on Mac, Linux?

Details on how mono did this is found here http://www.mono-project.com/docs/advanced/pinvoke/ it is highly descriptive.

Invoking native code on different platforms is very important. A cross platform program could include many of the same native library in different platform specific forms (.dll, .so. .dylib), each one would compiled for x86/x64 of each target platform while still being cross platform and using something like mono's dllmap in the .config file to determine which library to load at runtime.

**Comment by akoeplinger** [comment]
DllImport (P/Invoke) already works on .NET Core (e.g. see here for an example on Unix: https://github.com/dotnet/corefx/blob/79d44f202e4b6d000ca6c6885a24549a55db38f1/src/System.Console/src/Interop/Interop.manual.Unix.cs). 

Or are you talking about Mono's "dllmap"?

**Comment by xanather** [comment]
@akoeplinger Thats nice to know, and yes having dllmap would be good to have for unmanaged languages that have cross-platform libraries.

**Comment by ellismg** [comment]
I'm going to close this issue for now.  If we do decide to do something like DllMap, I suspect the work would have to happen in the (soon to be open sourced) runtime itself rather than the corefx libraries.

**Comment by xanather** [comment]
True, forgot that this place was for libraries only. Thanks for the info.
