### ISSUE TITLE
Extra 0x1a at end of /src/System.DirectoryServices.Protocols/ref/System.DirectoryServices.Protocols.cs

### ISSUE THREAD

**Issue by xied75** [dotnet/corefx#34302]
At the end of file:
https://github.com/dotnet/corefx/blob/master/src/System.DirectoryServices.Protocols/ref/System.DirectoryServices.Protocols.cs
There is a strange 0x1a (before the final 0d 0a):

```
00000210  65 66 61 75 6c 74 28 69  6e 74 29 3b 20 7d 20 7d  |efault(int); } }|
00000220  0d 0a 20 20 7d 0d 0a 7d  0d 0a 1a 0d 0a           |..  }..}.....|
```

Should it be removed?

**Comment by am11** [comment]
It's there since the initial commit of System.DirectoryServices.Protocols.cs
https://github.com/dotnet/corefx/commit/f4ddeb13a62f9bdab0aaad34898a1b80d19d0263#diff-6a8bb62c757dc41eacb89533f40c4ed4R643
<img width="30%" src="https://user-images.githubusercontent.com/3840695/50574172-a77d6780-0deb-11e9-884b-5eec1bcc50f2.png" />

**Comment by jkotas** [comment]
@xied75 Are you interested in sending a PR to remove it?

**Comment by xied75** [comment]
@jkotas done. https://github.com/dotnet/corefx/pull/34328
@am11  So I wonder how it could happen, one can't type it in normally with keyboard.
@danmosemsft Do you suggest that I should go hunt those?

**Comment by danmosemsft** [comment]
@xied75 sure if you like you could look for others to fix in the same PR. I would stick to the ones <=0x7F in this iteration.

**Comment by xied75** [comment]
@danmosemsft I found this one by running Antlr4 grammars against the corefx repo, as far as the grammar is concerned, this file is the only one that fails the parser for a character (a warning to be precise).

Regarding the replacing to unicode literal, I would need to use grep on this then? Can I schedule that to later time when I'm a bit free?

BTW, if guidelines suggest using unicode literal, should we enforce that at CI/CD pipelines?

**Comment by danmosemsft** [comment]
@xied75 totally up to you whether you do anything at all 😃 

There are a few other hits eg
```
c:\git\corefx\src>\t\grep --include="*.cs" -nRHPI "[\x00-\x08]|[\x0e-\x1f]" *
System.DirectoryServices.Protocols/ref/System.DirectoryServices.Protocols.cs:646:
System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/XmlJsonReader.cs:184:                CharType.None | CharType.FirstName | CharType.Name, //  A4 (?)
System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/XmlJsonReader.cs:187:                CharType.None | CharType.FirstName | CharType.Name, //  A7 (?)
System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/XmlJsonReader.cs:202:                CharType.None | CharType.FirstName | CharType.Name, //  B6 (?)
System.Text.Encoding/tests/UTF7Encoding/UTF7EncodingDecode.cs:52:            yield return new object[] { new byte[] { 0x2B, 0x80, 0x21, 0x80, 0x21, 0x1E, 0x2D }, 0, 7, "\u0080!\u0080!-" };
```
I am not sure whether they are errors or not, if not then they should probably be in `\unnnn` format so they're readable. Perhaps not worth bothering with.

`grep --include="*.cs" -nRHPI "...[\xa0-\xff]" *` has many hits (I added the `...` to reject the byte order marks, which ideally wouldn't be there either, but Notepad likes to add them)

I think there are so many hits there it is not worth making a pass and it would probably introduce bugs.

**Comment by danmosemsft** [comment]
I will close this as above, given you merged your fix - thanks

**Comment by danmosemsft** [comment]
@xied75 if we had a CI "hook" that did checks on files changed by the PR, that might be interesting, but we don't have such a mechanism right now. 

We have a lot more tasks up for grabs- is anything interesting to you?
https://github.com/dotnet/corefx/labels/up-for-grabs
