### ISSUE TITLE
CS0165 missed if .net standard

### ISSUE THREAD

**Issue by LeeReidCSIRO** [dotnet/corefx#34318]
Apologies in advance if this a misunderstanding or a bug that belongs elsewhere. It may be related to #29319

**Version Used**: 
Visual Studio Community 15.9.2
.NET 4.7.03056
.NET Standard 2.0

**Steps to Reproduce**:

1. Create a new project as a Console Application for .NET Core or .NET Framework
2. Enter the following code and compile:

```
        static void Main(string[] args)
        {
            TimeSpan ts;
            Console.WriteLine(ts);
        }

```

3. Repeat this, but for a .NET Standard class library. 

**Expected Behavior**:

The code should never compile, because TimeSpan is not assigned.

**Actual Behavior**:
For a .NET Core or .NET Framework project, this will not compile. For a .NET Standard class library, this will compile without error or warning.

**Comment by jaredpar** [comment]
Transferred to CoreFX as this is a framework issue, not a compiler one. What's happening here is the reference assemblies for `TimeSpan` differ between the various target frameworks here. In some cases it shows up as an empty `struct` which the C# compiler allows to be used without initialization. In other cases it shows up as having members and hence requires initialization before using. 

The differences between the frameworks have been fixed recently and going forward everything should be consistent. But existing targets can still surface these differences.

**Comment by joperezr** [comment]
@jaredpar I suppose the change you say fixed it is this one: https://github.com/dotnet/standard/pull/1012?

If so, @terrajobst I suppose that this is not something that can serviced to netstandard2.0 and instead would only be fixed when targeting .NET Standard 2.1, is that right?

**Comment by joperezr** [comment]
(marked as external since the real fix for this needs to happen on dotnet/standard repo)

**Comment by danmosemsft** [comment]
@wtgodbe can you please make sure this is tracked in dotnet/standard for 2.1 if appropriate, then close this (assuming I understand right)

**Comment by danmosemsft** [comment]
ping @wtgodbe

**Comment by wtgodbe** [comment]
Verifying the fix locally now

**Comment by wtgodbe** [comment]
I can verify that the expected error is now thrown when building with the latest VS2019 & targeting `netstandard2.1`:

> Error CS0165 Use of unassigned local variable 'ts'
