### ISSUE TITLE
All libcurl-related tests failing on Ubuntu.1804.Arm64.Open-arm64-Release

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#34310]
System.Net.Http.Native can't be loaded, I'm assuming because it's unable to load libcurl:
```
Unhandled Exception of Type System.TypeInitializationException
Message :
System.TypeInitializationException : The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
---- System.TypeInitializationException : The type initializer for 'Http' threw an exception.
-------- System.TypeInitializationException : The type initializer for 'HttpInitializer' threw an exception.
------------ System.DllNotFoundException : Unable to load shared library 'System.Net.Http.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSystem.Net.Http.Native: cannot open shared object file: No such file or directory
Stack Trace :
   at System.Net.Http.CurlHandler..ctor() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_arm64+TestOuter_false_prtest/src/System.Net.Http/src/System/Net/Http/CurlHandler/CurlHandler.cs:line 188
   at System.Net.Http.HttpClientHandler..ctor(Boolean useSocketsHttpHandler) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_arm64+TestOuter_false_prtest/src/System.Net.Http/src/System/Net/Http/HttpClientHandler.Unix.cs:line 37
----- Inner Stack Trace -----
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_arm64+TestOuter_false_prtest/src/System.Net.Http/src/System/Net/Http/CurlHandler/CurlHandler.cs:line 164
----- Inner Stack Trace -----
   at Interop.HttpInitializer.Initialize() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_arm64+TestOuter_false_prtest/src/Common/src/Interop/Unix/System.Net.Http.Native/Interop.Initialization.cs:line 47
   at Interop.Http..cctor() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_arm64+TestOuter_false_prtest/src/Common/src/Interop/Unix/System.Net.Http.Native/Interop.Initialization.cs:line 18
----- Inner Stack Trace -----
   at Interop.Http.GetSslVersionDescription()
   at Interop.HttpInitializer..cctor() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_arm64+TestOuter_false_prtest/src/Common/src/Interop/Unix/System.Net.Http.Native/Interop.Initialization.cs:line 27
```
All PRs are failing as a result.

**Comment by stephentoub** [comment]
@dotnet/dnceng, has something changed here in the past couple of weeks with regards to the image on these VMs?

**Comment by riarenas** [comment]
I do believe the physical machines we use for this Helix queue were reimaged. Did something change in them regarding libcurl? @Ilyas1974

**Comment by MattGal** [comment]
Filed https://github.com/dotnet/core-eng/issues/4891 to track fixing this up, I'll help out as needed.

**Comment by JpratherMS** [comment]
Hey Matt, I re-ran the same setup script and I am seeing the following which would indicate libcurl is being installed, am I missing something?

Running Precommands
Installing packages
libgdiplus
python-dev
libunwind8
libunwind-dev
libssl-dev
unzip
libicu-dev
libffi-dev
libcurl3
(Reading database ... 130367 files and directories currently installed.)
Removing cmake (3.10.2-1ubuntu2) ...
Removing libcurl4:arm64 (7.58.0-2ubuntu3.5) ...
Selecting previously unselected package libcurl3:arm64.
(Reading database ... 130348 files and directories currently installed.)
Preparing to unpack .../libcurl3_7.58.0-2ubuntu2_arm64.deb ...
Unpacking libcurl3:arm64 (7.58.0-2ubuntu2) ...
Setting up libcurl3:arm64 (7.58.0-2ubuntu2) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
build-essential
cmake
(Reading database ... 130355 files and directories currently installed.)
Removing libcurl3:arm64 (7.58.0-2ubuntu2) ...
Selecting previously unselected package libcurl4:arm64.
(Reading database ... 130348 files and directories currently installed.)
Preparing to unpack .../libcurl4_7.58.0-2ubuntu3.5_arm64.deb ...
Unpacking libcurl4:arm64 (7.58.0-2ubuntu3.5) ...
Selecting previously unselected package cmake.
Preparing to unpack .../cmake_3.10.2-1ubuntu2_arm64.deb ...
Unpacking cmake (3.10.2-1ubuntu2) ...
Setting up libcurl4:arm64 (7.58.0-2ubuntu3.5) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Setting up cmake (3.10.2-1ubuntu2) ...
clang
gdb
lldb-3.9
Running post-commands
InstallAspNetPrereqs
Installing latest version python pip....
--2019-01-02 09:52:02--  https://bootstrap.pypa.io/get-pip.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 151.101.48.175, 2a04:4e42:c::175
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|151.101.48.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1661676 (1.6M) [text/x-python]
Saving to: '/home/robox/get-pip.py'

/home/robox/get-pip 100%[===================>]   1.58M  5.20MB/s    in 0.3s

2019-01-02 09:52:02 (5.20 MB/s) - '/home/robox/get-pip.py' saved [1661676/1661676]

robox ALL=(ALL)       NOPASSWD: ALL
Collecting pip
  Using cached https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-18.1
Using specified config file: Ubuntu.1804.Arm64.Open.zip
robox@DDARM64S-023:~/helixscripts$ nohup: appending output to 'nohup.out'

**Comment by JpratherMS** [comment]
Updated the version of libcurl on all the machines, please test again and let me know if things are working. Thanks for the help @MattGal

**Comment by stephentoub** [comment]
Thanks. Trying here: https://github.com/dotnet/corefx/pull/34317#issuecomment-450984892

**Comment by stephentoub** [comment]
Thanks; that appears to have fixed the problem.

**Comment by stephentoub** [comment]
@JpratherMS, @MattGal, this seems to be happening again:
https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/94c43e147d6aac8de3f9d6ad8f4db5881b1007df/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.PlatformHandlerTest_AutoRedirect~2FAllowAutoRedirect_True_PostToGetDoesNotSendTE(statusCode:%20301)

Has something regressed?

**Comment by JpratherMS** [comment]
To my knowledge nothing has changed on these machines.

John

**Comment by MattGal** [comment]
@JpratherMS I think most of those machines got reimaged yesterday or today, so I think this is quite relevant.  See https://github.com/dotnet/core-eng/issues/4891 for where I told you what to do last time this came up :)

**Comment by MattGal** [comment]
I chatted with @ulisesh and @JpratherMS and believe this is just an issue with Ulises' work to move the agents inside docker containers.  He'll investigate and create issues as necessary.

**Comment by stephentoub** [comment]
Thanks.
