### ISSUE TITLE
Move System.Net.Cookie to System.Net.Http.Cookie

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/corefx#34326]
Cookies (also known as HTTP cookies) are a strictly HTTP-related feature and have nothing to do with networking, so everything related to HTTP cookies ought to be moved down the namespace to under Http.

This would be a breaking API change. ⚠
So this would have to be done in a major .NET Core API version bump.

If desired, the current System.Net.Cookie classes could transitionally be decorated with the `ObsoleteAttribute`.

**Comment by stephentoub** [comment]
Even in a major version breaking changes need to be worth the trade-off. I'm not seeing the benefit here being greater than the cost on the ecosystem.

**Comment by vanillajonathan** [comment]
For developers writing new code and new developers it would make the namespace more predictable and intuitive. It would ease discoverability.

Cost should be low, as refactoring existing code would be easy.

**Comment by davidsh** [comment]
@vanillajonathan Thank you for your suggestion.

The System.Net.Cookie class has existed a long time (almost 20 years).  This was a class to support System.Net.HttpWebRequest.  The System.Net.Http namespace, though, is relatively recent as System.Net.Http namespace and HttpClient APIs were added in the .NET 4.5 timeframe.

There are lots of historical things like this that aren't perfect about .NET API naming conventions.  As we add new APIs, we will try to align things.  But the cost of changing something like this is not worth it.  We already have tools like Intellisense in Visual Studio that can help developers find the right .NET types.

**Comment by davidsh** [comment]
@karelz

**Comment by vanillajonathan** [comment]
@davidsh I see.
Are these "misalignments" documented anywhere?
Any long-term plans to align any of those?

Since according to the documentation `System.Net.HttpWebRequest` is no longer recommended (`HttpClient` is favored), perhaps it ought to be considered for deprecation?
Perhaps the `ObsoleteAttribute` attribute could be added?

**Comment by davidsh** [comment]
>Are these "misalignments" documented anywhere?
Any long-term plans to align any of those?

I don't we explicitly document these kinds of things.  But over time new types will end up in the appropriate namespaces.

>Since according to the documentation System.Net.HttpWebRequest is no longer recommended (HttpClient is favored), perhaps it ought to be considered for deprecation?
Perhaps the ObsoleteAttribute attribute could be added?

The ObsoleteAttribute tends to add compile-time warnings which are not always desirable and can break  some compilation that uses warnings as errors.  HttpWebRequest itself is a very popular class despite it being "legacy".  We recommend developers writing new code use HttpClient.  But HttpWebRequest won't be marked as obsolete because there is no plan to remove it from the types offered in .NET.

**Comment by karelz** [comment]
ObsoleteAttribute is likely not the right thing to use, but we should come up with a way.
Closing as we won't move the namespace.

**Comment by vanillajonathan** [comment]
Is it possible for a namespace move to be reconsidered at a later time, such as for .NET Core 4 or 5?

**Comment by davidsh** [comment]
>Is it possible for a namespace move to be reconsidered at a later time, such as for .NET Core 4 or 5?

Realistically, no.  There is no precedent in .NET to change an existing type to a different namespace, especially one that has existed for such a long time.  It would be very disruptive to the ecosystem.

We continue to look for other ways to educate developers and improve the development tools to assist devs in finding the right APIs for their tasks.
