### ISSUE TITLE
high cpu 

### ISSUE THREAD

**Issue by sawachika-kenji** [dotnet/corefx#34329]
I have a program developed by .net core 2.1. It runs in docker. The system is centos7. In some cases, the program will take up 100% of the CPU. How should I diagnose the problem?

**Comment by danmosemsft** [comment]
@brianrob where are the best instructions for gathering a trace on Linux? (To open in [perfview](https://github.com/Microsoft/perfview))

@sawachika-kenji meantime, you might consider breaking in with the debugger when it hits 100%, it might give you a clue.

**Comment by brianrob** [comment]
@sawachika-kenji, I'd recommend taking a trace using these instructions: https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/linux-performance-tracing.md

Note that there are some specific steps to be taken when capturing within a Docker container.

**Comment by danmosemsft** [comment]
Not enough information. Please reopen if you can help make this actionable.
