### ISSUE TITLE
multiple  build synchronization issues

### ISSUE THREAD

**Issue by robertborr** [dotnet/corefx#34343]
@robertborr commented on [Mon Dec 10 2018](https://github.com/dotnet/core-eng/issues/4778)

@briansull  - referred by @MattGal and @adiaaida 
Multiple core-setup build issues with this error - it looks like to start with a build multi-threading issue.
There may be a further problem with IBCMerge, but its not definite yet.

System.ArgumentException : error : Win32.LoadLibraryEx failed for E:\A\_work\217\s\corefx\Tools\OptimizationData\System.IO.FileSystem.dll, Error = 32 [E:\A\_work\217\s\corefx\src\System.IO.FileSystem\ref\System.IO.FileSystem.csproj]

builds this occurred on:

- https://github.com/dotnet/core-eng/issues/4766
-- 2018-12-08T01:20:53.6978692Z System.ArgumentException : error : Win32.LoadLibraryEx failed for E:\A\_work\217\s\corefx\Tools\OptimizationData\System.IO.FileSystem.dll, Error = 32 [E:\A\_work\217\s\corefx\src\System.IO.FileSystem\ref\System.IO.FileSystem.csproj]
-- 2018-12-08T01:20:53.6979118Z E:\A\_work\217\s\corefx\Tools\codeOptimization.targets(37,5): error MSB3073: The command "E:\A\_work\217\s\corefx\.packages\Microsoft.DotNet.IBCMerge\4.6.0-alpha-00001\lib\net45\ibcmerge.exe -q -f -delete -mo E:\A\_work\217\s\corefx\Tools/OptimizationData/System.IO.FileSystem.dll E:\A\_work\217\s\corefx\Tools/OptimizationData/System.IO.FileSystem.ibc" exited with code -1. [E:\A\_work\217\s\corefx\src\System.IO.FileSystem\ref\System.IO.FileSystem.csproj]

- https://github.com/dotnet/core-eng/issues/4768

-- 2018-12-08T13:19:27.8713344Z E:\A\_work\217\s\corefx\Tools\codeOptimization.targets(71,5): warning MSB3026: Could not copy "E:\A\_work\217\s\corefx\artifacts\obj\ref/System.Runtime.Serialization.Primitives/netcoreapp-Release\System.Runtime.Serialization.Primitives.dll" to "E:\A\_work\217\s\corefx\artifacts\obj\ref/System.Runtime.Serialization.Primitives/netcoreapp-Release\/OptimizedAssembly\System.Runtime.Serialization.Primitives.dll". Beginning retry 1 in 1000ms. The requested operation cannot be performed on a file with a user-mapped section open : 'E:\A\_work\217\s\corefx\artifacts\obj\ref\System.Runtime.Serialization.Primitives\netcoreapp-Release\OptimizedAssembly\System.Runtime.Serialization.Primitives.dll'  [E:\A\_work\217\s\corefx\src\System.Runtime.Serialization.Primitives\ref\System.Runtime.Serialization.Primitives.csproj]
-- 2018-12-08T13:19:27.8714244Z EXEC : error : Can't find an IBC resource in E:\A\_work\217\s\corefx\artifacts\obj\ref\System.Collections.NonGeneric\netcoreapp-Release\OptimizedAssembly\System.Collections.NonGeneric.dll, Error = 1813 [E:\A\_work\217\s\corefx\src\System.Collections.NonGeneric\ref\System.Collections.NonGeneric.csproj]
-- 2018-12-08T13:19:27.8714874Z E:\A\_work\217\s\corefx\Tools\codeOptimization.targets(77,5): error MSB3073: The command "E:\A\_work\217\s\corefx\.packages\Microsoft.DotNet.IBCMerge\4.6.0-alpha-00001\lib\net45\ibcmerge.exe -mi E:\A\_work\217\s\corefx\artifacts\obj\ref/System.Collections.NonGeneric/netcoreapp-Release\/OptimizedAssembly/System.Collections.NonGeneric.dll" exited with code -1. [E:\A\_work\217\s\corefx\src\System.Collections.NonGeneric\ref\System.Collections.NonGeneric.csproj]

- https://github.com/dotnet/core-eng/issues/4770

- EXEC : error : the following exception was thrown while processing profile data [E:\A\_work\217\s\corefx\src\System.Net.Primitives\ref\System.Net.Primitives.csproj]
-  System.ArgumentException : error : Win32.LoadLibraryEx failed for E:\A\_work\217\s\corefx\Tools\OptimizationData\System.Net.Primitives.dll, Error = 32 [E:\A\_work\217\s\corefx\src\System.Net.Primitives\ref\System.Net.Primitives.csproj]
-       at IBCRead.ContainsIbcResource()
-       at IBCRead.DeleteInModule(Boolean force)
-       at IBCMerge.Merge(String[] args)
-       at IBCMerge.Main(String[] args)
-  E:\A\_work\217\s\corefx\Tools\codeOptimization.targets(37,5): error MSB3073: The command "E:\A\_work\217\s\corefx\.packages\Microsoft.DotNet.IBCMerge\4.6.0-alpha-00001\lib\net45\ibcmerge.exe -q -f -delete -mo E:\A\_work\217\s\corefx\Tools/OptimizationData/System.Net.Primitives.dll E:\A\_work\217\s\corefx\Tools/OptimizationData/System.Net.Primitives.ibc" exited with code -1. [E:\A\_work\217\s\corefx\src\System.Net.Primitives\ref\System.Net.Primitives.csproj]
- 

- https://github.com/dotnet/core-eng/issues/4772
E:\A\_work\217\s\corefx\.dotnet\sdk\2.1.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(134,5): error MSB3713: The file "E:\A\_work\217\s\corefx\artifacts\obj\ref/System.Transactions.Local/netcoreapp-Release\System.Transactions.Local.AssemblyInfo.cs" could not be created. The process cannot access the file 'E:\A\_work\217\s\corefx\artifacts\obj\ref\System.Transactions.Local\netcoreapp-Release\System.Transactions.Local.AssemblyInfo.cs' because it is being used by another process. [E:\A\_work\217\s\corefx\src\System.Transactions.Local\ref\System.Transactions.Local.csproj]

- https://github.com/dotnet/core-eng/issues/4774
CSC : error CS2012: Cannot open 'E:\A\_work\217\s\corefx\artifacts\obj\ref\System.Data.Common\uap-Release\System.Data.Common.dll' for writing -- 'The process cannot access the file 'E:\A\_work\217\s\corefx\artifacts\obj\ref\System.Data.Common\uap-Release\System.Data.Common.dll' because it is being used by another process.' [E:\A\_work\217\s\corefx\src\System.Data.Common\ref\System.Data.Common.csproj]

- https://github.com/dotnet/core-eng/issues/4776
EXEC : error : Can't find an IBC resource in E:\A\_work\217\s\corefx\artifacts\obj\ref\System.Net.Security\netcoreapp-Release\OptimizedAssembly\System.Net.Security.dll, Error = 1813 [E:\A\_work\217\s\corefx\src\System.Net.Security\ref\System.Net.Security.csproj]
 E:\A\_work\217\s\corefx\Tools\codeOptimization.targets(77,5): error MSB3073: The command "E:\A\_work\217\s\corefx\.packages\Microsoft.DotNet.IBCMerge\4.6.0-alpha-00001\lib\net45\ibcmerge.exe -mi E:\A\_work\217\s\corefx\artifacts\obj\ref/System.Net.Security/netcoreapp-Release\/OptimizedAssembly/System.Net.Security.dll" exited with code -1. [E:\A\_work\217\s\corefx\src\System.Net.Security\ref\System.Net.Security.csproj]
 E:\A\_work\217\s\corefx\eng\versioning.targets(72,5): error MSB3491: Could not write lines to file "E:\A\_work\217\s\corefx\artifacts\obj\ref/System.Security.Principal.Windows/netcoreapp-Release\_AssemblyInfo.cs". The process cannot access the file 'E:\A\_work\217\s\corefx\artifacts\obj\ref\System.Security.Principal.Windows\netcoreapp-Release\_AssemblyInfo.cs' because it is being used by another process. [E:\A\_work\217\s\corefx\src\System.Security.Principal.Windows\ref\System.Security.Principal.Windows.csproj]

---

@robertborr commented on [Mon Dec 10 2018](https://github.com/dotnet/core-eng/issues/4778#issuecomment-445958531)

Attached the log files in case they get deleted.

[4766--log_11_2263050 (1).zip](https://github.com/dotnet/core-eng/files/2664820/4766--log_11_2263050.1.zip)
[4768--log_11_2263692.zip](https://github.com/dotnet/core-eng/files/2664821/4768--log_11_2263692.zip)
[4770--log_11_2264200.zip](https://github.com/dotnet/core-eng/files/2664822/4770--log_11_2264200.zip)
[4772--log_11_2264524.zip](https://github.com/dotnet/core-eng/files/2664823/4772--log_11_2264524.zip)
[4774--log_11_2264930.zip](https://github.com/dotnet/core-eng/files/2664824/4774--log_11_2264930.zip)
[4776--log_11_2265551.zip](https://github.com/dotnet/core-eng/files/2664825/4776--log_11_2265551.zip)

---

@briansull commented on [Mon Dec 10 2018](https://github.com/dotnet/core-eng/issues/4778#issuecomment-445966588)

Probably the dll is locked due to a bug in the multi-threaded build  rules.

  unsafe public bool ContainsIbcResource()
    {
        bool result;

        IntPtr hMod = Win32.LoadLibraryEx(moduleName, (IntPtr)0, Win32.DONT_RESOLVE_DLL_REFERENCES | Win32.LOAD_LIBRARY_AS_DATAFILE);
        if (hMod.ToPointer() == null)
        {
           uint err = Win32.GetLastError();
            throw new ArgumentException(String.Format("Error: Win32.LoadLibraryEx failed for {0}, Error = {1}", moduleName, err));
        }

        IntPtr hResInfo = Win32.FindResource(hMod, "PROFILE_DATA", "IBC");
        if (hResInfo.ToPointer() == null)
        {
            result = false;
        }
        else
        {
            result = true;
        }
        Win32.FreeLibrary(hMod);

        return result;
    }

From: Robert Orr <notifications@github.com>
Sent: Monday, December 10, 2018 12:21 PM
To: dotnet/core-eng <core-eng@noreply.github.com>
Cc: Brian Sullivan <briansul@microsoft.com>; Mention <mention@noreply.github.com>
Subject: [dotnet/core-eng] multiple core-setup build synchronization issues (#4778)

@briansull<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbriansull&data=02%7C01%7Cbriansul%40microsoft.com%7Cc1b7400fb9484afb8c1008d65edcfaef%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636800700531955090&sdata=JIoIMaH%2F5axaNCMszL%2Buet55jEmvz%2FMqaFYjFqvRCCI%3D&reserved=0> - referred by @MattGal<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMattGal&data=02%7C01%7Cbriansul%40microsoft.com%7Cc1b7400fb9484afb8c1008d65edcfaef%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636800700531955090&sdata=QeZfH%2FZlLRYg%2BbVHZ0X2iD%2B77Z7OZ03jTG1701lE9%2FQ%3D&reserved=0> and @adiaaida<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadiaaida&data=02%7C01%7Cbriansul%40microsoft.com%7Cc1b7400fb9484afb8c1008d65edcfaef%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636800700531965104&sdata=TZRm6I8hjYh2yyLKfXRtH7XEYip8f%2FLqHgwqRdlvwbg%3D&reserved=0>
Multiple core-setup build issues with this error - it looks like to start with a build multi-threading issue.
There may be a further problem with IBCMerge, but its not definite yet.

System.ArgumentException : error : Win32.LoadLibraryEx failed for E:\A_work\217\s\corefx\Tools\OptimizationData\System.IO.FileSystem.dll, Error = 32 [E:\A_work\217\s\corefx\src\System.IO.FileSystem\ref\System.IO.FileSystem.csproj]

builds this occurred on:

  *   #4766<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fcore-eng%2Fissues%2F4766&data=02%7C01%7Cbriansul%40microsoft.com%7Cc1b7400fb9484afb8c1008d65edcfaef%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636800700531965104&sdata=hvyxmQghIpQKR%2FruQ1BYSfgoqy59DExmNNFhIdHMBT0%3D&reserved=0>
-- 2018-12-08T01:20:53.6978692Z System.ArgumentException : error : Win32.LoadLibraryEx failed for E:\A_work\217\s\corefx\Tools\OptimizationData\System.IO.FileSystem.dll, Error = 32 [E:\A_work\217\s\corefx\src\System.IO.FileSystem\ref\System.IO.FileSystem.csproj]
-- 2018-12-08T01:20:53.6979118Z E:\A_work\217\s\corefx\Tools\codeOptimization.targets(37,5): error MSB3073: The command "E:\A_work\217\s\corefx.packages\Microsoft.DotNet.IBCMerge\4.6.0-alpha-00001\lib\net45\ibcmerge.exe -q -f -delete -mo E:\A_work\217\s\corefx\Tools/OptimizationData/System.IO.FileSystem.dll E:\A_work\217\s\corefx\Tools/OptimizationData/System.IO.FileSystem.ibc" exited with code -1. [E:\A_work\217\s\corefx\src\System.IO.FileSystem\ref\System.IO.FileSystem.csproj]
  *   #4768<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fcore-eng%2Fissues%2F4768&data=02%7C01%7Cbriansul%40microsoft.com%7Cc1b7400fb9484afb8c1008d65edcfaef%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636800700531975108&sdata=%2FWPKmmkEAxIEyh3JAVzNzkTZEagahEAe8d9G9zOlahc%3D&reserved=0>

-- 2018-12-08T13:19:27.8713344Z E:\A_work\217\s\corefx\Tools\codeOptimization.targets(71,5): warning MSB3026: Could not copy "E:\A_work\217\s\corefx\artifacts\obj\ref/System.Runtime.Serialization.Primitives/netcoreapp-Release\System.Runtime.Serialization.Primitives.dll" to "E:\A_work\217\s\corefx\artifacts\obj\ref/System.Runtime.Serialization.Primitives/netcoreapp-Release/OptimizedAssembly\System.Runtime.Serialization.Primitives.dll". Beginning retry 1 in 1000ms. The requested operation cannot be performed on a file with a user-mapped section open : 'E:\A_work\217\s\corefx\artifacts\obj\ref\System.Runtime.Serialization.Primitives\netcoreapp-Release\OptimizedAssembly\System.Runtime.Serialization.Primitives.dll' [E:\A_work\217\s\corefx\src\System.Runtime.Serialization.Primitives\ref\System.Runtime.Serialization.Primitives.csproj]
-- 2018-12-08T13:19:27.8714244Z EXEC : error : Can't find an IBC resource in E:\A_work\217\s\corefx\artifacts\obj\ref\System.Collections.NonGeneric\netcoreapp-Release\OptimizedAssembly\System.Collections.NonGeneric.dll, Error = 1813 [E:\A_work\217\s\corefx\src\System.Collections.NonGeneric\ref\System.Collections.NonGeneric.csproj]
-- 2018-12-08T13:19:27.8714874Z E:\A_work\217\s\corefx\Tools\codeOptimization.targets(77,5): error MSB3073: The command "E:\A_work\217\s\corefx.packages\Microsoft.DotNet.IBCMerge\4.6.0-alpha-00001\lib\net45\ibcmerge.exe -mi E:\A_work\217\s\corefx\artifacts\obj\ref/System.Collections.NonGeneric/netcoreapp-Release/OptimizedAssembly/System.Collections.NonGeneric.dll" exited with code -1. [E:\A_work\217\s\corefx\src\System.Collections.NonGeneric\ref\System.Collections.NonGeneric.csproj]

  *   #4770<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fcore-eng%2Fissues%2F4770&data=02%7C01%7Cbriansul%40microsoft.com%7Cc1b7400fb9484afb8c1008d65edcfaef%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636800700531975108&sdata=kVPvLII7B%2BqK0oPDCR8Jd3%2F%2FMunetBobsVOYyJch664%3D&reserved=0>
  *   EXEC : error : the following exception was thrown while processing profile data [E:\A_work\217\s\corefx\src\System.Net.Primitives\ref\System.Net.Primitives.csproj]
  *   System.ArgumentException : error : Win32.LoadLibraryEx failed for E:\A_work\217\s\corefx\Tools\OptimizationData\System.Net.Primitives.dll, Error = 32 [E:\A_work\217\s\corefx\src\System.Net.Primitives\ref\System.Net.Primitives.csproj]

·         at IBCRead.ContainsIbcResource()

  *

·         at IBCRead.DeleteInModule(Boolean force)

  *

·         at IBCMerge.Merge(String[] args)

  *

·         at IBCMerge.Main(String[] args)

  *
  *   E:\A_work\217\s\corefx\Tools\codeOptimization.targets(37,5): error MSB3073: The command "E:\A_work\217\s\corefx.packages\Microsoft.DotNet.IBCMerge\4.6.0-alpha-00001\lib\net45\ibcmerge.exe -q -f -delete -mo E:\A_work\217\s\corefx\Tools/OptimizationData/System.Net.Primitives.dll E:\A_work\217\s\corefx\Tools/OptimizationData/System.Net.Primitives.ibc" exited with code -1. [E:\A_work\217\s\corefx\src\System.Net.Primitives\ref\System.Net.Primitives.csproj]
  *
  *   #4772<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fcore-eng%2Fissues%2F4772&data=02%7C01%7Cbriansul%40microsoft.com%7Cc1b7400fb9484afb8c1008d65edcfaef%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636800700531985113&sdata=U%2FOvcSu8GvVz4nkR3qvBjfWISnHqIWrmb4QLm4RvJ1M%3D&reserved=0>
E:\A_work\217\s\corefx.dotnet\sdk\2.1.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(134,5): error MSB3713: The file "E:\A_work\217\s\corefx\artifacts\obj\ref/System.Transactions.Local/netcoreapp-Release\System.Transactions.Local.AssemblyInfo.cs" could not be created. The process cannot access the file 'E:\A_work\217\s\corefx\artifacts\obj\ref\System.Transactions.Local\netcoreapp-Release\System.Transactions.Local.AssemblyInfo.cs' because it is being used by another process. [E:\A_work\217\s\corefx\src\System.Transactions.Local\ref\System.Transactions.Local.csproj]
  *   #4774<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fcore-eng%2Fissues%2F4774&data=02%7C01%7Cbriansul%40microsoft.com%7Cc1b7400fb9484afb8c1008d65edcfaef%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636800700531985113&sdata=VCdZd%2F82AgMO9r9lM6J%2BBkvFgmgb4mKkj46zeq5HBDo%3D&reserved=0>
CSC : error CS2012: Cannot open 'E:\A_work\217\s\corefx\artifacts\obj\ref\System.Data.Common\uap-Release\System.Data.Common.dll' for writing -- 'The process cannot access the file 'E:\A_work\217\s\corefx\artifacts\obj\ref\System.Data.Common\uap-Release\System.Data.Common.dll' because it is being used by another process.' [E:\A_work\217\s\corefx\src\System.Data.Common\ref\System.Data.Common.csproj]
  *   #4776<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fcore-eng%2Fissues%2F4776&data=02%7C01%7Cbriansul%40microsoft.com%7Cc1b7400fb9484afb8c1008d65edcfaef%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636800700531995118&sdata=Y4Y2%2BpN43q91yGfZlZL4M8ELMw9%2BR5WjphMzvq4%2BPMU%3D&reserved=0>
EXEC : error : Can't find an IBC resource in E:\A_work\217\s\corefx\artifacts\obj\ref\System.Net.Security\netcoreapp-Release\OptimizedAssembly\System.Net.Security.dll, Error = 1813 [E:\A_work\217\s\corefx\src\System.Net.Security\ref\System.Net.Security.csproj]
E:\A_work\217\s\corefx\Tools\codeOptimization.targets(77,5): error MSB3073: The command "E:\A_work\217\s\corefx.packages\Microsoft.DotNet.IBCMerge\4.6.0-alpha-00001\lib\net45\ibcmerge.exe -mi E:\A_work\217\s\corefx\artifacts\obj\ref/System.Net.Security/netcoreapp-Release/OptimizedAssembly/System.Net.Security.dll" exited with code -1. [E:\A_work\217\s\corefx\src\System.Net.Security\ref\System.Net.Security.csproj]
E:\A_work\217\s\corefx\eng\versioning.targets(72,5): error MSB3491: Could not write lines to file "E:\A_work\217\s\corefx\artifacts\obj\ref/System.Security.Principal.Windows/netcoreapp-Release_AssemblyInfo.cs". The process cannot access the file 'E:\A_work\217\s\corefx\artifacts\obj\ref\System.Security.Principal.Windows\netcoreapp-Release_AssemblyInfo.cs' because it is being used by another process. [E:\A_work\217\s\corefx\src\System.Security.Principal.Windows\ref\System.Security.Principal.Windows.csproj]

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fcore-eng%2Fissues%2F4778&data=02%7C01%7Cbriansul%40microsoft.com%7Cc1b7400fb9484afb8c1008d65edcfaef%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636800700531995118&sdata=7M0E34rFNbdYXo0PUyI2915vWbjuHqt3p%2FEXHDZQn9k%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALFV_HdN2iugSK_-sKMPAlwXa1jFHwnwks5u3sIjgaJpZM4ZMG2B&data=02%7C01%7Cbriansul%40microsoft.com%7Cc1b7400fb9484afb8c1008d65edcfaef%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636800700532005128&sdata=ivGFlP1oh%2FgpS8evtCh2X4X5npmM4Zj6%2FlmWN1XkJVk%3D&reserved=0>.

---

@markwilkie commented on [Thu Jan 03 2019](https://github.com/dotnet/core-eng/issues/4778#issuecomment-451286200)

@robertborr, please move to CoreFX if not already, or close.

**Comment by ViktorHofer** [comment]
Closing because of age. I believe this was a one-off thing.
