### ISSUE TITLE
Add more comprehensive tests for nullable reference types in Span apis

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#34358]
Missed cases: https://github.com/dotnet/corefx/issues/33710
Fixes for coverage: https://github.com/dotnet/coreclr/pull/21232

**Comment by Anipik** [comment]
```
span<string> strings = new string[] { "1", "3", "2" };
Console.WriteLine(strings.IndexOf(string[]null));
```

```
          C:\git\corefx\src\System.Memory\tests\Span\IndexOfSequence.T.cs(240,0): at System.SpanTests.SpanTests.IndexOfNullSequence_String(String[] spanInput, String[] searchInput, Int32 expected)
      System.SpanTests.SpanTests.IndexOfNullSequence_String(spanInput: ["1", "3", "2"], searchInput: null, expected: -1) [FAIL]
        Assert.Equal() Failure
        Expected: -1
        Actual:   0
        Stack Trace:
```

We are returning -1 if the second argument ```(string)null```

is this behaviour by design?

cc @ahsonkhan

**Comment by benaadams** [comment]
The `string[]` would convert to `Span<string>`.Length == 0` so be searching for a zero length sequence of strings, so like:

`"Hello".IndexOf(string.Empty)` == 0

If it was `strings.IndexOf((string)null)` then it would be looking for null and be like

`"Hello".IndexOf((char)'\0')` == -1

 So should be correct? /cc @GrabYourPitchforks @danmosemsft 

There is an issue that IndexOfAny not doing right thing in this regard https://github.com/dotnet/corefx/issues/32334 and fix https://github.com/dotnet/coreclr/pull/25075 and test updates for it https://github.com/dotnet/corefx/pull/38452
