### ISSUE TITLE
PermissionSet's AddPermission has no effect/implementation.

### ISSUE THREAD

**Issue by azchohfi** [dotnet/corefx#34368]
With 009996, I managed to use System.Security.PermissionSet (it builds), but the runtime implementation is empty (https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/Security/PermissionSet.cs). It seems like the resolution for this type is mapping to System.Runtime.Extensions.dll, when it should map to the actual implementation on System.Security.Permissions.dll

My csproj:
```
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
```
I tried manually adding a reference to:
```<PackageReference Include="System.Security.Permissions" Version="4.6.0-preview.18571.3" />```
But the result is the same.

Might be related to https://github.com/dotnet/corefx/issues/34308

**Comment by danmosemsft** [comment]
@ericstj is this another dupe of dotnet/wpf#248 ?

**Comment by ericstj** [comment]
>@ericstj is this another dupe of dotnet/wpf#248 ?

Nope

> the runtime implementation is empty 

It's intentional that PermissionSet does nothing.  CAS was brought back only for compile-time compatibility.  The technology itself is not supported in Core.  See https://github.com/dotnet/corefx/issues/9482.

**Comment by karelz** [comment]
Unsupported technology, closing.
