### ISSUE TITLE
Replace Microsoft.DotNet.CoreCLR dependency with Microsoft.NETCore.Runtime.CoreCLR

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#3439]
Remove dotnet-coreclr feed from dir.props and NuGet.config once this is done as well.

See https://github.com/dotnet/corefx/pull/3413#discussion_r40368451

cc @weshaggard

**Comment by weshaggard** [comment]
We have replaced all know usages of this so closing.
