### ISSUE TITLE
Support for Rfc2898DeriveBytes and other founding cryptographic support

### ISSUE THREAD

**Issue by Thashiznets** [dotnet/corefx#344]
Hi,
Reading the contribution DOs and DON'TS it says not to file an API addition without discussing first.
I have the System.Security.Cryptography.Rfc2898DeriveBytes essentially created in a PCL so works in WinRT etc. I'd like to expand on this as Rfc2898DeriveBytes is HmacSha1 based and people are trying to move onto hmacsha256 and upwards nowadays and I'd like to bring this into .NET Core

I'd like to start bringing in System.Security.Cryptography namespace into .NET Core. I'll include tests from the test data listed with the cryptographic standards and whatnot where possible.

Can I do this? :)

**Comment by davkean** [comment]
Thanks for the offer. 

We're planning on adding crypto support over the coming months, including support for WinRT-based platforms. Until then, I'll ask you hold off bring any crypto or additional features around it.

**Comment by AArnott** [comment]
In the meantime, you can check out [PCLCrypto](http://nuget.org/packages/pclcrypto) if you're looking for crypto support in PCLs.

**Comment by Thashiznets** [comment]
Thanks, I've got PCL version of BouncyCastle, I just wanted to contribute to .NET Core given it's stuff I've been working with of late in my Bitcoin projects and yea just felt I had something to contribute. All good thanks anyway!

**Comment by ellismg** [comment]
Going to close this one for now, since we do plan on adding crypto support in the coming months (the work is already in flight).

Once that's done, we can consider adding additional algorithms via the standard API review process.

Thanks @Thashiznets!

**Comment by Thashiznets** [comment]
Yep no worries thanks for the info @ellismg I look forward to seeing what you guys deliver and what I can add to it :)
