### ISSUE TITLE
System.Xml.XmlDocument.LoadXml(string xml) error with utf8 \u0010

### ISSUE THREAD

**Issue by rocketRobin** [dotnet/corefx#34419]
if a xml string contains char '\u0010', this function will throw 
![image](https://user-images.githubusercontent.com/9987850/50804756-61179380-132a-11e9-99fc-40f10d8973ab.png)

```
'', hexadecimal value 0x10, is an invalid character. Line 826, position 121.

   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseCDataOrComment(XmlNodeType type, Int32& outStartPos, Int32& outEndPos)
   at System.Xml.XmlTextReaderImpl.ParseCDataOrComment(XmlNodeType type)
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
```

**Comment by danmosemsft** [comment]
I'm not an XML person, but are you sure that's valid XML? Looking at 
https://www.w3.org/TR/REC-xml/#sec-comments

the grammar for comments is
`[15] | Comment | ::= | '<!--' ((Char - '-')  | ('-' (Char - '-')))* '-->'-- | -- | -- | --`

where `Char` is defined by
`[2] | Char | ::= | #x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF] | /* any Unicode character, excluding the surrogate blocks, FFFE, and FFFF. */`

That doesn't seem to allow 0x10.

**Comment by danmosemsft** [comment]
`&#x10;` should work

Please reopen if I missed something.

**Comment by svick** [comment]
@rocketRobin I don't think adding an option to support parsing invalid XML would be a good idea.

I think you have two options:

1. Contact the author of the XML and ask them to fix it.
2. Fix the XML before passing it to `XmlDocument`. As far as I can tell, there is no way to express the `\x10` character inside a CDATA section, so I would just remove it with code like:

    ```c#
    string xml = …;
    xml = xml.Replace("\x10", "");
    doc.LoadXml(xml);
    ```

    The problem with this approach is that the document might contain a different invalid character next week, so you might need to keep expanding the above code. Or you'll have to find out all the invalid characters and fix them from the start.

**Comment by danmosemsft** [comment]
Or, perhaps there is a "fuzzy" XML parser out there you could use.

**Comment by rocketRobin** [comment]
> I had this issue multiple times, too. Real world XML sometimes has these disallowed characters in them...
> 
> In my opinion, it is a mistake in the XML standard to disallow these characters without any apparent reason and without any workaround. They are not escapeable.
> 
> I would be sympathetic to .NET offering a compatibility mode for this scenario.

Totally agreed, The programs should work for real world problems not standards, just like browsers resolve bad html.
