### ISSUE TITLE
[arm\windows] Hundreds of  tests failed with "The work item failed to produce any test results." without Stack trace

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#34423]
**Job name:**
uap-Windows_NT-Release-arm-Windows.10.Arm64

Error message:
```
The work item failed to produce any test results.
```

Details:
https://dnceng.visualstudio.com/internal/_build/results?buildId=67997&view=ms.vss-test-web.test-result-details

**Comment by safern** [comment]
Closing as dupe of: #30399
