### ISSUE TITLE
Test "System.Runtime.InteropServices.Tests.Int16Tests.ReadInt16_StructWithReferenceTypes_ReturnsExpected" failed with Assert.NotEqual() Failure

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#34422]
**Failed test:**
System.Runtime.InteropServices.Tests.Int16Tests.ReadInt16_StructWithReferenceTypes_ReturnsExpected

Error message
```
Assert.NotEqual() Failure\nExpected: Not 0\nActual: 0
```
Stack trace
```
at System.Runtime.InteropServices.Tests.Int16Tests.ReadInt16_StructWithReferenceTypes_ReturnsExpected() in /Users/vsts/agent/2.144.0/work/1/s/src/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/Marshal/ReadWrite/Int16Tests.cs:line 124
```
Details:
https://dnceng.visualstudio.com/internal/_build/results?buildId=67997&view=ms.vss-test-web.test-result-details

**Comment by danmosemsft** [comment]
One off? @AaronRobinsonMSFT any idea why this might suddenly fail?

```
        [Fact]
        public void ReadInt16_StructWithReferenceTypes_ReturnsExpected()
        {
            int pointerOffset = Marshal.OffsetOf<StructWithReferenceTypes>(nameof(StructWithReferenceTypes.pointerValue)).ToInt32();
            int stringOffset = Marshal.OffsetOf<StructWithReferenceTypes>(nameof(StructWithReferenceTypes.stringValue)).ToInt32();
            int arrayOffset = Marshal.OffsetOf<StructWithReferenceTypes>(nameof(StructWithReferenceTypes.byValueArray)).ToInt32();

            object structure = new StructWithReferenceTypes
            {
                pointerValue = (IntPtr)100,
                stringValue = "ABC",
                byValueArray = new short[10] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 }
            };

            Assert.Equal(100, Marshal.ReadInt16(structure, pointerOffset));
            Assert.NotEqual(0, Marshal.ReadInt16(structure, stringOffset));
            Assert.Equal(3, Marshal.ReadInt16(structure, arrayOffset + sizeof(short) * 2));
        }
```

@AriNuer in these test failure bugs could you please include the leg name (the OS configuration) that the test failed in? In this case it's `netcoreapp-OSX-Release-x64-OSX.1013.Amd64`. If you select the node on the left, you can Ctrl-C it from the right side.

**Comment by AaronRobinsonMSFT** [comment]
@danmosemsft I don't know off the top of my head, but @jkoritzinsky has been working with struct marshaling recently. The test seems right in this case, so something definitely wrong.

**Comment by AaronRobinsonMSFT** [comment]
@danmosemsft Working with @jkoritzinsky, I think we found the culprit. It was definitely a one off, but can happen again. I have submitted a more robust check with #34445.

**Comment by danmosemsft** [comment]
Good deduction, thanks.

**Comment by stephentoub** [comment]
Failed again here:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38454~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190611.24/workItem/System.Runtime.InteropServices.Tests/analysis/xunit/System.Runtime.InteropServices.Tests.Int16Tests~2FReadInt16_StructWithReferenceTypes_ReturnsExpected
```
Unhandled Exception of Type Xunit.Sdk.NotEqualException
Message :
Assert.NotEqual() Failure
Expected: Not 0
Actual:   0
Stack Trace :
   at System.Runtime.InteropServices.Tests.Int16Tests.ReadInt16_StructWithReferenceTypes_ReturnsExpected() in /_/src/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/Marshal/ReadWrite/Int16Tests.cs:line 135
```

**Comment by jkoritzinsky** [comment]
@AaronRobinsonMSFT I'm just going to remove this specific check since we hit it again.
