### ISSUE TITLE
HttpClient ignores WebRequest.DefaultWebProxy

### ISSUE THREAD

**Issue by Suchiman** [dotnet/corefx#34466]
Right now there's no way to coerce all web requests of a specific application through a specific configured proxy since `HttpClient` disregards `WebRequest.DefaultWebProxy` and only respects `SystemProxyInfo.ConstructSystemProxy()`.
`HttpWebRequest` and `WebClient` who just wrap `HttpClient` explicitly take care of assigning `HttpClientHandler.Proxy = WebRequest.DefaultWebProxy` but if this is left unassigned, `HttpClient` will consult `SystemProxyInfo.ConstructSystemProxy()`. This is very unfortunate if you have no control over the HttpClients created and no control over the system proxy (e.g. Azure Web Apps).

I'd like to request support for HttpClient to use `WebRequest.DefaultWebProxy` when it has been set by the user and only otherwise the default system proxy.

I'd also take another API that allows to globally configure a Proxy.

**Comment by davidsh** [comment]
@karelz

**Comment by karelz** [comment]
I think we need a new clearly described issue for the global proxy setting API. We should then dupe the 2-3 issues we have against that.
@davidsh could you please help with that? (as you already are investing into enterprise proxy scenarios) Thanks!

**Comment by davidsh** [comment]
Will be tracked by #36553
