### ISSUE TITLE
INotifyPropertyChanged does not work as expected in the WinForms app.

### ISSUE THREAD

**Issue by mikhailovalex** [dotnet/corefx#34465]
* .NET Core Version: 3.0.100-preview-009844
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
Change property value doesn't affect controls if we use a Control.DataBindings property. It looks like a compatibility bug.

**Minimal repro:**
1. Create a new WinForms Core App.
2. Replace the following Code into the Form's code-behind:
```c#
public partial class Form1 : Form
    {
        MyClass _myClass = new MyClass();
        public Form1()
        {
            InitializeComponent();         
            label1.DataBindings.Add(nameof(label1.Text), _myClass, nameof(_myClass.MyProperty), true, DataSourceUpdateMode.OnPropertyChanged);
            buttonExit.Text = "Click me";
            _myClass.MyProperty = "Click the button to show the current time";
        }
        public class MyClass : INotifyPropertyChanged {
            private string myProperty;
            public string MyProperty {
                get {
                    return myProperty;
                }
                set {
                    if(myProperty == value)
                        return;
                    myProperty = value;
                    PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(MyProperty)));
                }
            }
            public event PropertyChangedEventHandler PropertyChanged;
        }

        private void buttonExit_Click(object sender, EventArgs e)
        {
            _myClass.MyProperty = DateTime.Now.ToString();
        }
    }
```
3. Click the button.

**Actual behavior:**
The label text doesn't change on button click.

**Expected behavior:**
The binding should work like in .Net Framework.

**P.S.**
https://github.com/dotnet/corefx/blob/a20e52392cfb80be0bc6aa29e84697690f254a9a/src/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectPropertyDescriptor.cs#L242

**Comment by karelz** [comment]
@maryamariyan @safern can you please check it out? This seems to block WinForms scenarios
cc @merriemcgaw

**Comment by AlanParr** [comment]
I've taken a look at this and simply removing the FEATURE_INOTIFYPROPERTYCHANGED checks in ReflectPropertyDescriptor seem to do the trick for my test case at least.
I couldn't find any other instances of FEATURE_INOTIFYPROPERTYCHANGED within corefx, is it safe to just remove these or does it need to be set to true somewhere?

**Comment by AlanParr** [comment]
Would be happy to submit a PR for this if the above resolution is acceptable.

**Comment by karelz** [comment]
@maryamariyan @safern any thoughts?

**Comment by maryamariyan** [comment]
@AlanParr a PR with that change sounds good. You can cc myself and @safern on the PR once it's available.

**Comment by safern** [comment]
Yeah, so I spoke with @ericstj and this is a regression of trying to cleanup dead code: 

https://github.com/dotnet/corefx/commit/c1f5a3396837d6e3837e7ca1ae254abeae273a79

However this is not dead code because this is called from the WPF runtime but because nobody within the framework uses it the linker might have been deleting the code and so therefore as part of cleaning up dead code in https://github.com/dotnet/corefx/issues/17905

So we need to consider the Linker when fixing this to make sure that it doesn't remove it whenever we build.
