### ISSUE TITLE
Missing System.Threading.Tasks.Extensions from latest 3.0 builds. Intentional?

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#34473]
Just noticed that System.Threading.Tasks.Extensions is no longer getting produced from 3.0 Preview 2 builds, so current builds of aspnet are using a stale dependency. Was this package intentionally dropped? There was a 3.0 Preview 1 version of this package. 

cc @tarekgh

**Comment by stephentoub** [comment]
This was done explicitly by @jkotas here:
https://github.com/dotnet/corefx/commit/f83cc7ec2e4aadf07c0f943a50906a144ad2e544
https://github.com/dotnet/corefx/pull/34218#issuecomment-449809768

**Comment by tarekgh** [comment]
@natemcmaster I am closing this issue per the offline discussion and your confirmation referencing 4.5.2 worked fine. 

for the record:
here @jkotas comment

```
This package was effectively dead since it got inboxed. It cannot evolve anymore. We had other similar packages – like System.Memory – that we have stopped building for the same reason.
```

and is @joperezr comment 

```
System.Threading.Tasks.Extensions is inbox in both netcoreapp and uap which are really the only two implementations we were live building. That means that when targeting netcoreapp or uap, you don’t even need a package reference anymore, and if targeting netstandard, then it should be fine to reference the RTM package from 2.x and get the surface area exposed by the netstandard contract.
```
