### ISSUE TITLE
Image.FromStream() function will reading entire file when running on linux

### ISSUE THREAD

**Issue by zhengchun** [dotnet/corefx#34487]
Hello, everyone, I want to getting image dimension(Height,Width) and image format without read the whole file into memory. call `Image.FromStream(fs, useEmbeddedColorManagement: false, validateImageData: false);` it can working perfect on windows, that will reading just some of file header bytes. But, when i'm running this function on linux system, this function will read entity file, a `validateImageData` property value it not work.

The following code just for demo.

```c#
    class Program
    {
        static void Main(string[] args)
        {
            var name = @"a.jpg";
            using (var fs = new FileStream(name, FileMode.Open))
            {
                var ms = new MemoryStream();
                fs.CopyToAsync(ms).GetAwaiter().GetResult();
                Console.WriteLine($"The image total length: {ms.Length}");
                ms.Seek(0, SeekOrigin.Begin);
                var image = Image.FromStream(ms, useEmbeddedColorManagement: false, validateImageData: false);
                Console.WriteLine($"The header length is {ms.Position}");
            }
            Console.ReadLine();
        }
    }
```

Running on windows(.Net Core 2.2)
```
The image total length: 3643713
The header length is 4096
````
Running on lunix( .Net Core 2.2-sdk + libgdiplus library):
```
The image total size: 3643713
The header length is 3643713 // Here, it readed the entire file.
```

I am installed a `System.Drawing.Common` package.  Do you have any ideas, thanks.

**Comment by zhengchun** [comment]
I found [skiasharp](https://github.com/mono/SkiaSharp) , an other way is implement parse file reader for jpeg,png. so closed this.

**Comment by gfoidl** [comment]
On Linux / Unix [libgdiplus](https://github.com/mono/libgdiplus) is used, so there may be some differences in the behavior of GDI+ (windows) and that version used.

Although you closed this issue, you may want to open an issue in the libgdiplus-repo (mono also relies on libgdiplus, and if there is the same behavior it's not an issue for .NET Core, but one for libgdiplus).

**Comment by gfoidl** [comment]
@danmosemsft good idea. I just created a default reply:

```
On platforms other than Windows [libgdiplus](https://github.com/mono/libgdiplus) is used.
If the "bug" can be reproduced on Mono, please move the issue the _libgdiplus_-repo.
```

It would be nice if GitHub can support default replies within an repo / organization where the issue is created / answered to. Or does this exists and I just don't know about this?

**Comment by danmosemsft** [comment]
I don't know of such a feature (there is not a first class concept of issue area anyway). I am happy to post this from now on.

**Comment by safern** [comment]
Potentially our github labeler bot could comment that if the label is System.Drawing and it is non-windows 😄 cc: @Anipik

**Comment by Anipik** [comment]
yeah if the labeler becomes that intelligent from all that learning :P

**Comment by zhengchun** [comment]
thanks everyone, I have open this issue in the `libgdiplus` repo. thanks again.
