### ISSUE TITLE
API request: string.Intern(ReadOnlySpan<char> ...)

### ISSUE THREAD

**Issue by ladeak** [dotnet/corefx#34493]
String.Intern currently accepts a string parameter. When processing a ```ReadOnlySpan<char>``` it would be nice to be able to *intern* a string without a necessary string allocation upfront. This would be especially useful for strings that would be used frequently.

For this reason I would request the following overloads added to string:

```csharp
public static string string.Intern(ReadOnlySpan<char> str)
public static string string.Intern(Span<char> str)

public static bool string.IsInterned(ReadOnlySpan<char> str)
public static bool string.IsInterned(Span<char> str)
```

**Comment by khellang** [comment]
> ```csharp
> public static string string.Intern(ReadOnlySpan<char> str)
> public static string string.Intern(Span<char> str)
> ```

How are these supposed to work without allocating a string? You mean if a matching string is already in the intern pool?

**Comment by jkotas** [comment]
Note that `string.Intern` uses a global singleton. It is required to intern the string 100% of the time, across all threads. It means that it needs to take locks, some of the time at least. And the current implementation never releases the string once it has been interned.

You typically get much better performance results by using a local interning table that does imperfect interning (i.e. it is ok for it to create duplicate strings in rare cases - hash collisions, multiple threads competing to create the same string, etc.)

We can still add this API, but it is unlikely to be very useful to actually make things faster.

**Comment by danmosemsft** [comment]
Wouldn't we always recommend against `string.Intern` anyway for reasons @jkotas states? If so, I think we should close this rather than extend its API.
