### ISSUE TITLE
Environment.GetEnvironmentVariable behaviour

### ISSUE THREAD

**Issue by rich-zilla** [dotnet/corefx#34492]
What is the expected behaviour for retrieving environment variables?

1. Create a new system environment variable
1. Using a simple dotnet core console app, attempt to retrieve the variable (with `System.Environment.GetEnvironmentVariable`)

*What I expect to happen*
`GetEnvironmentVariable` returns the current value of that variable

*Whats actually happening*
The variable is not found until I restart my system.

Other programming languages do appear to be able to retrieve the environment variable (A python script, for example), but im prepared to concede that may be after a restart. 

After restarting I can read the value of the variable, however if i change this variable, the change is not reflected in the dotnet core application. The python script retrieves the expected value.

What are the rules surrounding the 'caching' behaviour im seeing with my environment variables?

*System Details*
Windows 10 Pro (1803)
Microsoft.NETCore.App 2.2.0

*Example Programs*

```c#
using System;

namespace Scratch
{
    class Program
    {
        static void Main(string[] args)
        {
            var env = Environment.GetEnvironmentVariable("TEST_VARIABLE");
            Console.WriteLine(env ?? "No Value");
        }
    }
}
```

```python
import os
os.environ['TEST_VARIABLE']
```

**Comment by Wraith2** [comment]
Enviroment blocks are inherited from the parent process so if you haven't restarted VS it'll still have the block you started it with which will not include the new variable. If you start a command prompt and use the set command after changing the variable (without logging out or restarting) does it pick up the new variable/value? If so restarting vs should work.

**Comment by Anipik** [comment]
@rich-zilla do you have any other questions ?

**Comment by danmosemsft** [comment]
Processes snapshot the environment variables when they start. Therefore when setting an environment variable with EnvironmentVariableTarget.Machine or EnvironmentVariableTarget.User, other processes do not immediately see the changes. All we can do is send a WM_SETTINGCHANGE message as HWND_BROADCAST. Some more sophisticated apps may recognize this and choose to re-read the environment variables, but I do not know which (if any - including VS) do. 

As @Wraith2 says the only way to get a process to see the change for sure is to restart it, as you found out. It is how the OS works. I would be interested if someone can confirm whether Linux works this way.
