### ISSUE TITLE
Build with the 3.0 dotnet SDK

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#34498]
We should update the SDK we build with and clean up workarounds that were in place due to being on an old one.

Here are the workarounds I recall:
https://github.com/dotnet/corefx/blob/a680b92d4c7c1d99d9facf2b7eca8dd33ee87515/external/runtime/runtime.depproj#L53-L57
https://github.com/dotnet/corefx/blob/d07ba0a0026aa4effe9cc24ec5c1ed12e08c5d8d/Directory.Build.props#L145-L149

**Comment by ericstj** [comment]
@ViktorHofer I know you started looking at this when you were working on the global tools.  Did you want to take this or update the issue with your findings?

**Comment by ViktorHofer** [comment]
Yeah I'm happy to take this. Will probably also require some minor arcade updates.

**Comment by ViktorHofer** [comment]
Related: https://github.com/dotnet/arcade/issues/1907 & https://github.com/dotnet/arcade/issues/1906
