### ISSUE TITLE
Bring IoC container in .NET Core

### ISSUE THREAD

**Issue by aleks-sidorenko** [dotnet/corefx#345]
What do you think about usage of IoC container in .NET Core just like it was done in ASP.NET MVC (DependencyResolver). It could be something similar to DependencyResolver or well-known IoC like autofac/ninject/unity etc.

It will bring more abstractions to .NET, more incapsulation, more decoupling, more testability.
What do you think?

**Comment by aleks-sidorenko** [comment]
Also as we have .NET to be crossplatform, how do we implement some platform specific code?
We don't implement it with compile-time #if WIN32 #else #end, right? We must have this defined in runtime and have both implementations to be present in package.
Than we must do something like:
if (IsWin32())
{
// invoke Win32 API
}
else
{
// invoke unix API
}

The better way here is to make abstraction over platform specific API and inject it as dependency. And initialize IoC with concrete implementation at runtime.

**Comment by xanather** [comment]
I agree there needs to be a simple API that allows determining between the common supported platforms when running. I know this has already been done with .net/mono cross-platform assemblies, but it usually involves having to explicitly check multiple variables and properties to determine the correct platform.

**Comment by MpDzik** [comment]
+1 for better support for dependency injection, I miss it a lot in the .NET framework. There are a lot of static method APIs which are impossible to mock without creating a custom abstraction around them. Providing a way to integrate those APIs with a dependency injection container would be great.

**Comment by terrajobst** [comment]
> What do you think about usage of IoC container in .NET Core

I assume you meant 'corefx'. '.NET Core' is the stack itself, it contains corefx, coreclr, and ASP.NET Core.

My general response would be 'no, we shouldn't use an IoC container in corefx. This project is mostly the lower-level, set of primitive types and collections that everyone is going to be using. The key here is that less is more. It needs to be fast, reliable and very pay-for-play friendly. In the end, someone needs to be able to build an IoC with what we deliver :-)

That being said, our factoring improvements for .NET Core naturally result in us doing a better job with providing abstractions. That being said, it will never be perfect. People can still call `DateTime.Now` or use `Console.WriteLine`. There are only so many ways to be efficient and pluggable.

**Comment by robertsundstrom** [comment]
It shouldn't be part of the CoreFx.

I guess you could use, and even contribute to, the infrastructure introduced with ASP.NET 6 (vNext) which is already distributed as a NuGet Package.

Microsoft.Framework.DependencyInjection
https://github.com/aspnet/DependencyInjection

**Comment by terrajobst** [comment]
My comment is less about **containment**, it's about **usage**. In my mind, primitives shouldn't rely on an IoC mechanism.

**Comment by aleks-sidorenko** [comment]
Yes, I agree with you.
If we talk about primitives, IoC/DI containers doesn't make sense.
