### ISSUE TITLE
`RuntimeFeature.IsSupported("IsDynamicCodeCompiled")` does not work well for lightup

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#34503]
The light-up scenarios for `RuntimeFeature.IsDynamicCodeCompiled` are not able to reliable distinguish between "not supported" (e.g. running on 3.0 AOT-only runtime) and "unknown" (e.g. running on 2.1 runtime that does not have IsDynamicCodeCompiled property).

- Proposal A: Invert the values returned by the API.

```csharp
class RuntimeFeature
{
    bool IsDynamicCodeUnsupported { get; }
    bool IsDynamicCodeInterpreted { get; }
}
```

The code looks like this

```csharp
if (RuntimeFeature.IsDynamicCodeUnsupported || RuntimeFeature.IsDynamicCodeInterpreted)
{
    // do an AOT fallback
}
else
{
    // optimized JIT compiled path
}

if (RuntimeFeature.IsSupported("IsDynamicCodeUnsupported") ||
    RuntimeFeature.IsSupported("IsDynamicCodeInterpreted"))
{
    // do an AOT fallback
}
else
{
    // optimized JIT compiled path
}
```

- Proposal B: No API change, update `RuntimeFeature.IsSupported` to recognize `!` prefix. The code looks like this:

```csharp
if (!RuntimeFeature.IsDynamicCodeCompiled)
{
    // do an AOT fallback
}
else
{
    // optimized JIT compiled path
}

// Lightup
if (RuntimeFeature.IsSupported("!IsDynamicCodeCompiled"))
{
    // do an AOT fallback
}
else
{
    // optimized JIT compiled path
}
```

Original discussion https://github.com/dotnet/coreclr/pull/21338#issuecomment-453201053

**Comment by jkotas** [comment]
@terrajobst Do you have an opinion on how to address this? IIRC, you had a strong opinion during the API API review what `IsSupported` should return for these.

One option is to allow querying of the negative for these `IsXXX` capability properties by prefixing the name with `!`.

- 3.0 JIT runtime:
`RuntimeFeature.IsSupported("IsDynamicCodeCompiled") == true`
`RuntimeFeature.IsSupported("!IsDynamicCodeCompiled") == false`

- 3.0 AOT-only runtime:
`RuntimeFeature.IsSupported("IsDynamicCodeCompiled") == false`
`RuntimeFeature.IsSupported("!IsDynamicCodeCompiled") == true`

- 2.1 runtimes:
`RuntimeFeature.IsSupported("IsDynamicCodeCompiled") == false`
`RuntimeFeature.IsSupported("!IsDynamicCodeCompiled") == false`

**Comment by pakrym** [comment]
`RuntimeFeature.IsSupported("!IsDynamicCodeCompiled")` ends up being the only one worth querying in this scenario. I'm afraid it's too hard for customers to discover all the quirks in this case.

**Comment by jkotas** [comment]
@pakrym Do you have an alternative suggestion how to fix this?

**Comment by pakrym** [comment]
We can backport `IsSupported` implementation so things "just work". It would still require the latest patch of 2.1/2.2 but at least semantics of `RuntimeFeature.IsSupported` would be preserved.

**Comment by jkotas** [comment]
> backport

I do not think it is a viable option. We need to have a design how to add new IsXXX properties, without requiring servicing back ports.

**Comment by pakrym** [comment]
Just want to point out that this issue only applies to features that existed but didn't have feature flags before. 

Another solution is to invert the meaning of feature flags, e.g.:

1. IsDynamicCodeCompiled -> IsDynamicCodeInterpreted
2. IsDynamicCodeSupported -> IsDynamicCodeUnsupported

**Comment by jkotas** [comment]
> IsDynamicCodeInterpreted

What would this return for 3.0 full-AOT runtime, without IL interpreter?

**Comment by pakrym** [comment]
`IsDynamicCodeInterpreted` `false` and `IsDynamicCodeUnsupported` would be `true`

**Comment by jkotas** [comment]
And the code you would have to write in your library would be:

```
if (!RuntimeFeature.IsSupported("IsDynamicCodeUnsupported") && !RuntimeFeature.IsSupported("IsDynamicCodeInterpreted"))
{
   // ... use Reflection.Emit as an optimization ...
}
```

Is that right?

**Comment by pakrym** [comment]
Yep, inverting the condition makes it look a bit more readable:

```
if (RuntimeFeature.IsSupported("IsDynamicCodeUnsupported") ||
    RuntimeFeature.IsSupported("IsDynamicCodeInterpreted"))
{
    // do an AOT fallback
}
else
{
    // optimized JIT compiled path
}
```

**Comment by jkotas** [comment]
I have summarized the two options in the top post.

@terrajobst Could you please discuss this at API review meeting, and pick one of the two options? (Or come up with a third one.)

**Comment by terrajobst** [comment]
> The light-up scenarios for `RuntimeFeature.IsDynamicCodeCompiled` are not able to reliable distinguish between "not supported" (e.g. running on 3.0 AOT-only runtime) and "unknown" (e.g. running on 2.1 runtime that does not have IsDynamicCodeCompiled property).

I'm not sure I understand. The light-up scenario on a .NET Core 2.0 AOT only runtime should be:

```C#
var isDynamicCodeSupported = RuntimeFeature.IsSupported("IsDynamicCodeSupported");
var isDynamicCodeCompiled = RuntimeFeature.IsSupported("IsDynamicCodeCompiled");
```

Both will return false. You're correct that a runtime that doesnt know about these two properties will always return false, which would mean that there isn't a reliable way to detect a pre-.NET Core 3.0 efficient dynamic code generator. But that seems less problematic because "unknown" means we're taking a conservative position.

> Proposal A: Invert the values returned by the API.

Hmm, I'm not sure this makes sense to me:

```C#
var isDynamicCodeUnsupported = RuntimeFeature.IsSupported("IsDynamicCodeUnsupported");
var isDynamicCodeInterpreted = RuntimeFeature.IsSupported("IsDynamicCodeInterpreted");
```

This would mean that the existing 10.1 UWP platform would return `false` for both of these, i.e. code would assume it's support and not interpreted. That seems worse.

> Proposal B: No API change, update `RuntimeFeature.IsSupported` to recognize `!` prefix. The code looks like this:

That's an interesting idea. We should discuss this in an API review. My knee-jerk reaction is that this might be a bit too much magic and that an explicit API like `IsKnown(string feature)` might be better:

```C#
bool isDynamicCodeSupported;
bool isDynamicCodeCompiled;

var hasCodeGenCapabilityAPIs = RuntimeFeature.IsKnown("IsDynamicCodeSupported") &&
                               RuntimeFeature.IsKnown("IsDynamicCodeCompiled");

if (hasCodeGenCapabilityAPIs)
{
    isDynamicCodeSupported = RuntimeFeature.IsSupported("IsDynamicCodeSupported");
    isDynamicCodeCompiled = RuntimeFeature.IsSupported("IsDynamicCodeCompiled");
}
else
{
    // We run on a platform that doesn't support code gen capability APIs. Let's
    // check for some known platforms and initialize the properties based on these
    // results.
    //
    // <platform checks go here>

    isDynamicCodeSupported = ...;
    isDynamicCodeCompiled = ...;
}
```

**Comment by terrajobst** [comment]
> My knee-jerk reaction is that this might be a bit too much magic and that an explicit API like `IsKnown(string feature)` might be better:

Which, of course, wouldn't solve the .NET Core 2.x case, because the API didn't exist. *grumble*

**Comment by terrajobst** [comment]
Supporting the `!` would solve the issue, but it's a heavy-handed in the sense that we have to support a magic string for all keys moving forward what amounts to a point-in time issue for .NET Core 2.x and these two specific feature names.

Moving forward, we'd rather address this by a new API:

```C#
bool IsSupported(string feature, out bool isKnownFeature);
```

Of course, this doesn't addresss the .NET Core 2.x case but we think a platform check would be the best way to address that.

@jkotas any objections to this?

**Comment by jkotas** [comment]
Sounds reasonable to me. I am not sure how valuable this really is since this does not address the .NET Core 2.x case. @pakrym Do you have an opinion?

> we think a platform check would be the best way to address that.

I expect that folks would just use reflection to light up. We are basically building a mini-reflection here.

**Comment by pakrym** [comment]
It doesn't help us with 2.x and it's not easy for customers to tell which overload of `IsSupported` should be used.

**Comment by danmosemsft** [comment]
@pakrym @jkotas is this must have for 3.0? If not it is time to move this to Future milestone.

**Comment by jkotas** [comment]
I think this should be just closed. There is nothing actionable suggested to improve the situation.
