### ISSUE TITLE
Mac & Linux Console Issues

### ISSUE THREAD

**Issue by bradygaster** [dotnet/corefx#34501]
This issue is related to #31517 and to the ASP.NET Core httprepl issue [here](https://github.com/aspnet/AspLabs/issues/68). 

The code in the screen shot below, which you can see running in the screenshot, demonstrates the issue. I noticed some intermittent and unpredictable behavior when I ran it a few times.
 
1. The first time I ran the code, I saw everything I typed.
1. The second time I ran the code, I saw the first, oh, 10 characters I typed and then no more.
1. The third time I ran the code, I saw 1 character, then no more.
1. Since the third time, I always see no characters on screen.
 
This was perplexing, so I changed “true” to “false” and re-ran the code. Obviously I saw each character being typed out. So I changed false back to true, re-ran the code a few times, and took a screen shot of it. Note, I was typing fast when I ran it this last time. Each time you see Exiting in the line of typed text, that’s when I hit the X key on my keyboard. In all of the executions below there were numerous key-presses that don’t show up on-screen prior to me hitting the X key to exit the app.

![image](https://user-images.githubusercontent.com/41929050/50988258-e9c83800-14c0-11e9-9a3b-81048825e595.png)

**Comment by wtgodbe** [comment]
Thanks for filing the issue, I'll take a look when I get a chance.

**Comment by stephentoub** [comment]
Just based on the symptoms this sounds the same to me as https://github.com/dotnet/corefx/issues/25916#issuecomment-376689779, https://github.com/dotnet/corefx/issues/30610#issuecomment-399522462, https://github.com/dotnet/corefx/issues/16352#issuecomment-281431102, etc.

**Comment by karelz** [comment]
@wtgodbe can you please deep dive into it next week? I'd like to understand what we can do and how costly it would be. Thanks!

**Comment by wtgodbe** [comment]
@karelz will do

**Comment by bradygaster** [comment]
just curious if we have any updates on this? cc @wtgodbe and @karelz

**Comment by wtgodbe** [comment]
I got sidetracked with other issues last week, sorry for the delay. I am out sick today, but this is at the top of my list once I'm back at work (should be either tomorrow or Thursday).

**Comment by wtgodbe** [comment]
I've dug into this, and it is indeed the same issue as Stephen mentions in https://github.com/dotnet/corefx/issues/34501#issuecomment-453362727. Here's what's happening under the hood:

- You call `Console.ReadKey`
- `ReadKey` calls `ConsolePal.ReadKey`: https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System/Console.cs#L109
- `ConsolePal.ReadKey` calls `SyncTextReader.ReadKey`: https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System/ConsolePal.Unix.cs#L101
- `SyncTextReader.ReadKey` calls `StdInReader.ReadKey`: https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System/IO/SyncTextReader.Unix.cs#L28
- `StdInReader.ReadKey` calls `InitializeConsoleBeforeRead`: https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System/IO/StdInReader.cs#L365
- `InitializeConsoleBeforeRead` disables echo: https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/Native/Unix/System.Native/pal_console.c#L111-L120

Until we disable echo in `InitializeConsoleBeforeRead`, the Unix terminal will always echo everything the user types. There is a small amount of overhead between you calling `Console.ReadKey` and us disabling echo, which could cause the user's typed characters to appear on screen. The larger overhead comes from the program starting up, which you can confirm by running your repro in a loop:

```C#
static void Main(string[] args)
{
  while(true)
  {
    var result = Console.ReadKey(true);
    while (result.Key != ConsoleKey.X)
    {
      result = Console.ReadKey(true);
    }
    Console.WriteLine("Loop done");
  }
}
```

If you run the above on Unix, on the first iteration of the loop, you'll see about the first 10 characters that you type before echoing stops. On subsequent iterations of the outer `while` loop, I was unable to ever get my input to show up on screen, indicating that the majority of the overhead here happens on startup. I was able to confirm in the debugger that it's possible to get your typed characters to echo to the terminal on subsequent iterations of the loop, but in real-time it's very difficult. 

Right now I'm looking into possible workarounds you could use, such as calling `Interop.Sys.InitializeConsoleBeforeRead()` upon startup of your program, but I'm not sure what other implications there are of calling it in isolation. @stephentoub do you know of anything that @bradygaster can do to avoid the Unix terminal echoing characters during program startup?

**Comment by stephentoub** [comment]
> @stephentoub do you know of anything that @bradygaster can do to avoid the Unix terminal echoing characters during program startup?

The only thing I'm aware of would be to disable echo himself.

**Comment by wtgodbe** [comment]
@bradygaster is there anything else I can do to help with this particular issue? My understanding here is the same as Stephen's, which is that your best bet would be to either manually disable Echo in native code, like in https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/Native/Unix/System.Native/pal_console.c#L121, or to add a manual delay before you call `ReadKey` the first time. I'd also be happy to help with any follow-up issues that you guys have after meeting.

**Comment by bradygaster** [comment]
@wtgodbe not that i know of at this time, but we still need to sync up on the main issue, which is we can mitigate the slow experience in 1804 and High Sierra that we're seeing on the http-repl. I'll facilitate a conversation to try to move forward on that. Would you or @stephentoub be the appropriate person from your side to get into a room with @mlorbetske and Ahmed and myself to discuss?

**Comment by wtgodbe** [comment]
Either or both of us would be good - @stephentoub is more knowledgeable in the area, but also a lot more busy ;)

**Comment by bradygaster** [comment]
@wtgodbe sounds good, will set it up

**Comment by wtgodbe** [comment]
@bradygaster can this issue be closed in favor of the larger issue/work item?
