### ISSUE TITLE
Child process hangs in Console.WriteLine after some time has passed since the parent called Process.CancelOutputRead

### ISSUE THREAD

**Issue by clguimanMSFT** [dotnet/corefx#34502]
Given the following scenario:
-  The parent (.net core app) starts a child process and listen to the stdout & stderr stream for a given amount of time (10 seconds) - calls Process.BeginOutputReadLine then Process.CancelOutputRead
- The child periodically writes a message to console and right after to file.

After some time, the child will stop writing to the log file and if you take a look in a memory dump you will see the main thread is stuck with the following call stack:

 	[Managed to Native Transition]	
 	mscorlib.dll!System.IO.__ConsoleStream.WriteFileNative(Microsoft.Win32.SafeHandles.SafeFileHandle hFile, byte[] bytes, int offset, int count, bool useFileAPIs) Line 255	C#
 	mscorlib.dll!System.IO.__ConsoleStream.Write(byte[] buffer, int offset, int count) Line 160	C#
 	mscorlib.dll!System.IO.StreamWriter.Flush(bool flushStream, bool flushEncoder) Line 320	C#
 	mscorlib.dll!System.IO.StreamWriter.Write(char[] buffer, int index, int count) Line 418	C#
 	mscorlib.dll!System.IO.TextWriter.WriteLine(string value) Line 485	C#
 	mscorlib.dll!System.IO.TextWriter.SyncTextWriter.WriteLine(string value) Line 839	C#
 	mscorlib.dll!System.Console.WriteLine(string value) Line 2085	C#

You can find a sample of the issue here: https://github.com/clguimanMSFT/TestOutputRead 
The issue reproduces when the app targets netcoreapp2.0 and netcoreapp2.2 (didn't try 2.1, but I assume it also reproduces)
You can also find memory dumps here: https://github.com/clguimanMSFT/TestOutputRead/tree/master/dumps

Is there something wrong with my usage of the feature or does it look like a bug in the framework? The same code runs OK in regular .NET Framework.

**Comment by stephentoub** [comment]
I'm not following the repro.

The parent process stops reading from the pipe, so eventually the pipe will fill up, and the child will be blocked writing to the pipe (the Console.WriteLine) because the pipe is full and no one's reading from it.

What are you expecting to happen instead?

**Comment by stephentoub** [comment]
Ah, the difference with .NET Framework is https://github.com/dotnet/corefx/issues/33746.  So this would appear to be a dup of that.

**Comment by wtgodbe** [comment]
Closing as dup of https://github.com/dotnet/corefx/issues/33746
