### ISSUE TITLE
Add vectorization to Tensor operations

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#34511]
_From @ericstj on August 1, 2017 19:27_

We should be able to easily vectorize the method bodies of https://github.com/ericstj/corefxlab/blob/563f023fe14a11a9ccb78f935475203ff3ba2b9c/src/System.Numerics.Tensors/System/Numerics/TensorArithmetic.cs.

My thought to do this is add a Vector<T> method to https://github.com/ericstj/corefxlab/blob/563f023fe14a11a9ccb78f935475203ff3ba2b9c/src/System.Numerics.Tensors/System/Numerics/TensorTemplate.ttinclude#L59 and use this if `Vector.IsHardwareAccelerated`, otherwise just use the normal IL.

_Copied from original issue: dotnet/corefxlab#1683_

**Comment by tannergooding** [comment]
_From @ericstj on October 16, 2017 18:21_

Dependent on #1798

**Comment by ericstj** [comment]
Closing this for now since we've moved the operations to the tests.
