### ISSUE TITLE
Is Tensor arithmetic really needed for V1 (or future?)

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#34515]
_From @ericstj on September 29, 2017 16:31_

The scenarios we're aiming at in V1 have tensor as primarily an interop type: a way to safely pass dense and sparse multi-dimension data without copy, yet still access from the managed side.  We're not planning for heavy computation on tensors in managed code.

As such, we may want to scope out the math operators for v1.

_Copied from original issue: dotnet/corefxlab#1798_

**Comment by tannergooding** [comment]
_From @eerhardt on October 16, 2017 16:43_

from @ericstj 

>  if we do cut for v1 we should move the code to test assembly and make it work on top of public API (just not as operators)

**Comment by tannergooding** [comment]
_From @ericstj on October 16, 2017 16:45_

Above is because I've found that the arithmetic tests (esp contraction/multiplication) provide good high-level coverage for the library, so if we drop the operators and static methods from the public surface we should put the static methods in the test assembly and have the tests use them.

**Comment by tannergooding** [comment]
_From @ericstj on October 20, 2017 19:54_

Another thought on this.  Although it is neat to be able to use operators on these its actually a bit scary and non-intuitive when you start thinking about very large arrays.  We could instead only ship the static methods, which could be provided in this assembly (or even in another assembly).

**Comment by ericstj** [comment]
We decided not to put this in for V1 and moved it to the tests.
