### ISSUE TITLE
Using HttpClient.PatchAsync() from .NET Standard 2.0 library

### ISSUE THREAD

**Issue by cclauson** [dotnet/corefx#34534]
HttpClient.PatchAsync() is documented:
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.patchasync?view=netcore-2.2

Is this only available in .NET Core, and not .NET Standard?

Thanks!

**Comment by davidsh** [comment]
`HttpClient.PatchAsync` is not part of .NET Standard 2.0.

It is part of the current .NET Core.

@terrajobst Can you comment on whether this API will eventually be part of a future .NET Standard?

cc: @karelz

**Comment by karelz** [comment]
I think .NET Standard API requests should be done in https://github.com/dotnet/standard repo, but I am not 100% sure - @terrajobst?

**Comment by karelz** [comment]
@terrajobst ping?

**Comment by karelz** [comment]
Duplicate of https://github.com/dotnet/standard/issues/1056
