### ISSUE TITLE
Make AssemblyLoadContext a concrete type

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/corefx#34535]
There is a desire to simplify `System.Runtime.Loader.AssemblyLoadContext` usage by making it a concrete type.

The existing class is abstract because the `Load()` method is not implemented.

The simplest solution is to simply implement `Load()` as a method returning `null` and make the appropriate constructors public.

**Comment by sdmaclea** [comment]
A more controversial and/or complete solution could be to extend #33165.  Something like
``` C#
public interface IDependencyResolver
{
    public string ResolveAssemblyToPath(AssemblyName assemblyName);
    public string ResolveUnmanagedDllToPath(string unmanagedDllName);
}

public class AssemblyDependencyResolver : IDependencyResolver
{
}

public class AssemblyLoadContext
{
    public AssemblyLoadContext(IDependencyResolver earlyDependencyResolver);

    protected virtual System.Reflection.Assembly Load (System.Reflection.AssemblyName assemblyName)
    {
        if (earlyResolver)
        {
            String path = earlyResolver.ResolveAssemblyToPath(assemblyName);
            if (!path.Empty())
            {
                return LoadFromAssemblyPath(path);
            }
        }
        return null;
    }
    protected virtual IntPtr LoadUnmanagedDll (string unmanagedDllName)
    {
         // Similar implementation
    }
}
```

**Comment by jkotas** [comment]
Both look reasonable.

**Comment by vitek-karas** [comment]
I think we should do the simple `Load` returning null.

The second proposal with dependency resolver ventures into the area we've already been, which is trying to come up with a simple solution for "plugin" loads. With the proposed API it would be very simple (2 lines?) to create an ALC to load plugins into, which would dictate a policy decision - which is the problematic part. The above implementation is the "full isolation" policy, which might work for very clear plugin models, but it doesn't work out of the box as it requires for the shared types/assemblies to not be included in the plugin.

I would rather we first make the class non-abstract in the simple manner without additional logic. And try to tackle the "easy to use" APIs later on.
If we decide that we also want the dependency resolver based implementation it can be added later on with relative ease.

**Comment by swaroop-sridhar** [comment]
I agree with @vitek-karas. The simple implementation of `Load()` is sufficient for cases where:
* We only use ALCs for isolation, with current default Load() semantics
* We only alter assembly/unmanaged-library load semantics using events 

without creating unnecessary inheritance as in [here](https://github.com/dotnet/coreclr/blob/master/tests/src/Interop/NativeLibraryResolveEvent/ResolveEventTests.cs#L12).

It is reasonable to ALC to be inherited when there is change in assembly-load behavior. 
In the way, the second `Load()` implementation only moves the inheritence hierarchy from ALCs to `IDependencyResolver` implementations.

**Comment by sdmaclea** [comment]
Moved to #34791
