### ISSUE TITLE
Socket SendFile or BeginSendFile Is there a size limit

### ISSUE THREAD

**Issue by SuYiQianYei** [dotnet/corefx#34540]
Win7  3G size file  get Exception

**Comment by karelz** [comment]
@SuYiQianYei are you saying that 3GB file will throw exception?
What is the exception? When is it thrown? (right away or at 3GB)
Did you find the exact file size which triggers the exception?

**Comment by stephentoub** [comment]
There's no limit enforced by .NET. Any limitation here comes from the underlying OS. e.g. on Windows SendFile is just a thin wrapper for TransmitFile, and according to https://docs.microsoft.com/en-us/windows/desktop/api/mswsock/nf-mswsock-transmitfile, "The maximum number of bytes that can be transmitted using a single call to the TransmitFile function is 2,147,483,646, the maximum value for a 32-bit integer minus 1." It might be possible for SendFile to make multiple TransmitFile calls if it sees the file length is too large.

**Comment by SuYiQianYei** [comment]
@stephentoub 
https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/SocketPal.Windows.cs

SendFile only invoke TransmitFile once
so on Windows    limit 2,147,483,646

**Comment by SuYiQianYei** [comment]
@stephentoub   @karelz 
I got it  Thank you

**Comment by karelz** [comment]
I will close it as answered. I don't think making multiple TransmitFile calls is necessary. We can reconsider in future if there is higher demand.
@stephentoub feel free to reopen if you disagree ...
