### ISSUE TITLE
ResourceManager/Localization not working after changing rootnamespace

### ISSUE THREAD

**Issue by azchohfi** [dotnet/corefx#34562]
This issue had already been fixed by Asp.Net Core, but we need the same solution for WPF/WinForms:
https://github.com/aspnet/AspNetCore/issues/2645

**Comment by jkotas** [comment]
cc @sdmaclea

**Comment by sdmaclea** [comment]
> we need the same solution for WPF/WinForms: aspnet/AspNetCore#2645

AspNetCore added the `Microsoft.Extensions.Localization.RootNamespaceAttribute` and used it in its calculation of the absolute resource name.  This was all done in high level libraries.

For WPF to use the **same** solution, it would seem this would need to be done in WPF.

If the runtime was to implement a **similar** solution, it would need to introduce a new (similar) attribute to the NetCoreApp API surface.

**Comment by azchohfi** [comment]
Exactly. As long as we have a plausible solution for desktop apps with .Net Core 3.0, I'm happy.

**Comment by tarekgh** [comment]
@sdmaclea what is the direction now? should this be moved to wpf? or you think it should be the core?

**Comment by sdmaclea** [comment]
@tarekgh It is not clear to me yet what the right answer is.

@azchohfi I read through aspnet/AspNetCore#2645 again. 

How was this handled in .NET Framework?  Why wasn't it a problem?  Why is .NET Core different?

**Comment by tarekgh** [comment]
Issue moved to [dotnet/wpf #358](https://github.com/dotnet/wpf/issues/358) via [**ZenHub**](https://www.zenhub.com/)
