### ISSUE TITLE
Proposal: YAML support

### ISSUE THREAD

**Issue by NextTurn** [dotnet/corefx#34578]
YAML has become a popular language, even adopted in widely used Microsoft's products such as [Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/) and [DocFX](https://dotnet.github.io/docfx/). However, .NET hasn't had built-in APIs or great third-party libraries (like Json.NET) to deal with YAML.

I suggest a `System.Yaml` namespace (like `System.Xml`) which supports YAML serialization.

**Comment by NextTurn** [comment]
https://github.com/dotnet/docs/blob/173ad22d3ac08e40e131a6b3ef1604832c0b762c/docs/core/deploying/runtime-store.md#L33-L34

**Comment by ichensky** [comment]
Yaml - ugly data serialization language, where you need format text by spaces, so it is not human easy editable language. It is better if yaml would live in any other lib out of NET Framework.

**Comment by NextTurn** [comment]
However, YAML is used in manually edited configuration files in the products I mentioned above.

**Comment by NextTurn** [comment]
When it comes to formats, we always indent the codes in any language with spaces, so this may not be the main problem?

**Comment by ichensky** [comment]
Yaml has very big problem with spaces, when you creating yaml file, you should always count number of spaces at each line and keep in mind whole structure of yaml file, and if yaml file is big this task really hard. In languages like json, xml, C# it dosen't matter how do you write your code, compiler always can parse it. And if you mistakenly add space somewhere in the code at the beginning of line (in C# for ex.) it will not influence on the result.

**Comment by karelz** [comment]
I would be hesitant to add it to the platform itself, unless it is truly needed.
This can easily live as independent NuGet package - not even owned by MS (think JSon.NET)

**Comment by am11** [comment]
> think JSon.NET

💡  [YamlDotNet](https://github.com/aaubry/YamlDotNet) is an actively-maintained, community-driven alternative which implements v1.1 spec of YAML (language that syntactically belongs to the family of [off-side rule languages](https://en.wikipedia.org/wiki/Off-side_rule#Off-side_rule_languages)). YDN is written purely in C#, provides package that supports .NET Framework 2.0+ and .NET Standard1.3+ and is also Unity[3d] compatible.

**Comment by karelz** [comment]
In that case I would suggest to close this issue, unless there is some very compelling reason to have YAML support in the platform itself.

**Comment by iSazonov** [comment]
@karelz Is https://github.com/aaubry/YamlDotNet a _trusted_ repository that can be used in Microsoft projects (like PowerShell Core)?

Related issue in PowerShell Core repo https://github.com/PowerShell/PowerShell/issues/3607

/cc @SteveL-MSFT

**Comment by karelz** [comment]
@iSazonov that is decision of each project which dependencies to trust / support, etc. For example, ASP.NET Core decided to built on top of JSon.NET.

**Comment by NextTurn** [comment]
@karelz Not exactly. They plan on removing dependency from ASP.NET Core to Json.NET now.

33115

**Comment by karelz** [comment]
@NextTurn sure, I know. From various reasons. But the dependency shipped in multiple versions - 1.0, 1.1, 2.0 and 2.2.

**Comment by karelz** [comment]
@iSazonov this is not only about security policy, much more is involved. Either way, it is PowerShell Core team decision to take the dependency, or find alternatives (e.g. its own implemented, etc.).

**Comment by iSazonov** [comment]
@karelz Thanks!

@SteveL-MSFT Could you please comment? Could we use YamlDotNet or we need more trusted API for https://github.com/PowerShell/PowerShell/issues/3607?

**Comment by karelz** [comment]
@iSazonov I think that discussion would be best in PowerShell repo where it is most relevant.

**Comment by NextTurn** [comment]
Reopening due to milestone changes. :) Is this under consideration now?

**Comment by karelz** [comment]
No, milestone was set to reflect WHEN it was closed. Closing again.
