### ISSUE TITLE
Implement Utf8JsonReader, Writer and JsonDocument to support netstandard2.0

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#34577]
The current implementation of S.T.Json targets netcoreapp3.0.

This will likely require some conditional includes (to fix the S.T.Json dependencies) and ifdefs in the source around APIs that are not included within netstandard2.0.

This change is necessary to produce a source package that targets netstandard2.0.

cc @KrzysztofCwalina, @bartonjs, @steveharter, @joperezr

**Comment by bartonjs** [comment]
I would really like to see the `netstandard1.x` goal written down somewhere official.  As far as I know, we are doing `netstandard2.0`; as the "really netstandard2.0-compatible" NetFX versions have been out long enough.

**Comment by ahsonkhan** [comment]
> As far as I know, we are doing `netstandard2.0`; as the "really netstandard2.0-compatible" NetFX versions have been out long enough.

I agree, and am fine with having the goal be `netstandard2.0`. `netstandard2.0` means support for `.NET Fx 4.6.1`. From the initial requirements gathering (a few months ago), I recall an asks for `.NET 4.5` support, but they may not be substantiated.

@KrzysztofCwalina, based on the Azure SDK needs, is 4.6.1 sufficient? I remember you did some cursory search on the existing SDKs and found some that were multi-targeting. Were they targeting .NET 4.5?

cc @terrajobst

**Comment by KrzysztofCwalina** [comment]
@Petermarcu tells me 4.6.1 is sufficient.

**Comment by Petermarcu** [comment]
We should also talk about you providing a net461 asset in the same package to help people avoid the binding redirects nightmare and extra facade copies. Feels like that should be the default when providing an ns2 platform library while 461 is still a valid target.

**Comment by joperezr** [comment]
@Petermarcu The idea is that this will be a source package, which means that no binaries will be provided. Because of this, the consuming project may avoid the need of having binding redirects as long as all of the dependencies in order to compile the source in this package (which AFAIK are only System.Memory and System.Runtime.CompilerServices.Unsafe) have an asset targetting .NET Framework.

**Comment by Petermarcu** [comment]
@joperezr yeah, for source packages its not an issue. I was more thinking about the generic baseline for packages shipped by corefx.
