### ISSUE TITLE
EnumerableSorter.ElementAt optimization

### ISSUE THREAD

**Issue by InRedikaWB** [dotnet/corefx#34572]
Method ElementAt  from EnumerableSorter<TElement, TKey> is trivial "Kth order statistic" algorithm.
https://github.com/dotnet/corefx/blob/f3b56d1dfc2b8fb52c8d22a3bcd32a797b684adf/src/System.Linq/src/System/Linq/OrderedEnumerable.cs#L428-L430

That implementation has time complexity O(N^2) in worse case. But some variations of this algo has O(N) complexity in any case. As example: http://marcodiiga.github.io/kth-order-statistic.
What about changing realization to make in O(N)?

**Comment by stephentoub** [comment]
> What about changing realization to make in O(N)?

The time complexity is important, but so are the constants.  We would need to evaluate best, common, and worst cases to see whether it helped more than it hurt.

Please feel free to experiment and if you come up with something good, submit a PR with associated benchmarks.  In the meantime, I'm going to close this issue as we generally try not to have open issues about speculative performance improvements.  Thanks.
