### ISSUE TITLE
CommandLine parses incorrectly when quoted argument with trailing backslash is passed

### ISSUE THREAD

**Issue by RickStrahl** [dotnet/corefx#34574]
In a .NET Core Console app I'm trying to access the following command line:

```
"~\2017\" -o
```

with:

```cs
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(args[0]);
            Console.WriteLine(args[1]);

        }
    }
```

The first arg[0] returned as:

```
~\2017"
```

Expected return should be:

```
~\2017\
```

Without the slash at the end the string properly returns:

```
~\2017
```

IOW, it looks like it's parsing the last slash as a string character delimiter rather than a literal slash.

However, this weird parsing is totally inconsistent. Passing this:

```
"~\\2017\\"
```

on the command line returns:

```
~\\2017\
```

Runtime: .NET Core 2.2 
Windows 10, 1809

Apparently this behaivior is not new - just tried this in a full framework project and it does the same thing.

**Comment by mxmissile** [comment]
I’ll be damned if I could find where I read it, but if I *vaguely* recall, it’s the tilde and something to do with regex.

**Comment by RickStrahl** [comment]
Yup that's it. Without the ~ it works. Didn't even occur to me to check that - Duh.

Still seems like this shouldn't be happening... But knowing this I can probably work around it.

**Comment by Anipik** [comment]
@RickStrahl why are you using quotes here ? passing the arguments as ```~\2019\ -o```  will give you the required output. AFAIK we use quotes if the argument has any spaces.

```
~\2019\
-o
```

Closing the issue as I don't think any thing needs to be done here. can reopen if we decide to change the behviour
