### ISSUE TITLE
.NET Core 2.1 System.Data.SqlClient is not supported on this platform

### ISSUE THREAD

**Issue by OculiViridi** [dotnet/corefx#34580]
I have a **.NET Core 2.1** solution with different projects (.NET Core 2.1 and .NET Standard 2.0), built into a single application for **x64** environment.
The application has to run on a **Windows Server 2016 x64** machine.

While I was updating to a new release, when tried to execute it, I got this message:

> System.Data.SqlClient is not supported on this platform.

Before updating, the application it was running fine. If I replace the new version with the old one, it executes correctly.

These are some information about the application, environment and DLLs:

```
Project: .NET Core 2.1.6 x64
Runtime: .NET Core 2.1.6 Runtime bundle
OS: Windows Server 2016 x64 with latest Windows updates

```
Dependency on `System.Data.SqlClient.dll` taken from `MyApplication.deps.json` file:

```json
"Microsoft.EntityFrameworkCore.SqlServer/2.1.4": {
    "dependencies": {
      "Microsoft.EntityFrameworkCore.Relational": "2.1.4",
      "System.Data.SqlClient": "4.5.1"
    },
    "runtime": {
      "lib/netstandard2.0/Microsoft.EntityFrameworkCore.SqlServer.dll": {
        "assemblyVersion": "2.1.4.0",
        "fileVersion": "2.1.4.18263"
      }
    }
  },
```

If I remove the `System.Data.SqlClient.dll` file I get this error:

> Error:
  An assembly specified in the application dependencies manifest (Ecoprogetti.Dcs.WindowsService.deps.json) was not found:
    package: 'System.Data.SqlClient', version: '4.5.1'
    path: 'runtimes/win/lib/netcoreapp2.1/System.Data.SqlClient.dll'

Between the previous release of my application and this new one, I surely updated many packages with nuget, including the **EF Core** ones, till latest .NET Core 2.1 version that is **2.1.4**, because I want to stay on .NET Core 2.1 LTS release.

If I compare the previous version of `System.Data.SqlClient.dll` and the new one, the DLLs differs only for file size and not for file version. Please see the attached screenshots.

### Old DLL

![image](https://user-images.githubusercontent.com/42179710/51105008-0bd6f880-17e8-11e9-998b-89fcd696f542.png)

### New DLL

![image](https://user-images.githubusercontent.com/42179710/51104993-feba0980-17e7-11e9-85b1-d4650dda0c7d.png)

**Comment by AfsanehR** [comment]
Hi @OculiViridi . Could you provide your application csproj file and the output of `dotnet --info` please?

**Comment by OculiViridi** [comment]
### Update 2019/01/15

Also I tried to execute the same application version on my develpment machine and it starts without any problem. I don't know if it can be related to the platform intended as Windows Server 2016...

@AfsanehR Hi! Here it is the `.csproj` file of the main project.

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <Platforms>x64</Platforms>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <Authors>MyCompany</Authors>
    <Description>MyCompany DCS® Windows Service</Description>
    <Copyright>© MyCompany All rights reserved.</Copyright>
    <FileVersion>1.0.0</FileVersion>
    <Product>MyCompany DCS® Windows Service</Product>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DasMulli.AspNetCore.Hosting.WindowsServices" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MyCompany.Dcs.Engine\MyCompany.Dcs.Engine.csproj" />
  </ItemGroup>
</Project>
```
And this is the `dotnet --info` output on Windows Server 2016 machine.

![image](https://user-images.githubusercontent.com/42179710/51167096-d7297680-18a5-11e9-9acc-5a75fc8a5df3.png)

**Comment by OculiViridi** [comment]
I can't even reproduce it myself, except on the test machine where it is not currently working, as I said initially.

After a successfull build on my develpment machine, if I take the build folder and move it to C:\ and execute, everything is working without problems. 
**The same build directory copy/pasted as is** inside the C:\ of server (as done with my previous application versions), when trying to execute leads now to this new error:

```
Error:
  An assembly specified in the application dependencies manifest (Ecoprogetti.Dcs.WindowsService.deps.json) was not found:
    package: 'System.Data.SqlClient', version: '4.5.1'
    path: 'runtimes/win/lib/netcoreapp2.1/System.Data.SqlClient.dll'
```

but the file is in place, since the folder is exactly the same as the one in my development machine.

**Comment by AfsanehR** [comment]
@OculiViridi  This issue is not reproducible on our end.  I will close this issue for now but let us know if you were able to provide more detailed information. Thanks

**Comment by fesily** [comment]
I have same problem. 
When I was debugging, dotnet load assembly from path "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.data.sqlclient\4.5.1\runtimes\win\lib\netcoreapp2.1\System.Data.SqlClient.dll".
When I publish the project, the framework will copy from path "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.data.sqlclient\4.5.1\lib\netcoreapp2.1\System.Data.SqlClient.dll"
