### ISSUE TITLE
Certificate Revocation List Not Checked for ChainPolicy.ExtraStore on Windows

### ISSUE THREAD

**Issue by shortspider** [dotnet/corefx#34584]
We have an application that verifys a provided certificate against a root certificate. We do not want to have the certificate installed in the Windows Certificate Store and so we use the ChainPolicy.ExtraStore to set the root and verify.

We expect to get an UntrustedRoot error since it's not in the Windows store but the issue we are having is that on Windows the CRL is not retrieved and checked if an untrusted root is detected. We would expect that even if the root is untrusted that the CRL would be checked anyway. On Linux we do see this happen.

Looking at the code, in [Windows](https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Windows/ChainPal.BuildChain.cs) the BuildChain method sets up the chain engine with a handle to either the local machine store or the user store. It then calls crypt32.dll’s CertGetCertificateChain and passes it that chain engine to build the chain and returns a pointer to the chain context and a boolean indicating whether or not the chain was built successfully.

In [Linux](https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/ChainPal.cs) the BuildChain calls the FindCandidates method which checks several additional stores for the root certificate. This includes the ExtraStore which is what we are currently adding our root certificate to. It still does specifically look for System Trusted root in the BuildChain method, but its existence does not look like it determines whether or not the revocation check occurs. The method returns the newly built chain and a bool.

In Linux the BuildChain method only sets the untrusted root flag when building the chain. The revocation check still occurs unlike in Windows.

Can anyone confirm that is a bug or if it's by design? If it's by design can you explain why?

We are using .NET Core 2.2.

Thanks.

**Comment by davidsh** [comment]
@bartonjs

**Comment by bartonjs** [comment]
Windows considers this by design.  I'll leave this open as the bug to remind me to stop doing the checks in this situation on Linux.

**Comment by shortspider** [comment]
@bartonjs so you're going to stop doing the CRL checks for untrusted roots in Linux? That's good for consistancy I guess but unfortunate from the standpoint of an external store root behaving differntly then anything else. I get that Windows considers that by design but can you please expand on why?

**Comment by bartonjs** [comment]
> I get that Windows considers that by design but can you please expand on why?

Not really; it's a different team, and it's been that way since probably forever (it just wasn't something that got tested during Linux bring-up).

Their opinion is that if you want contextually trusted roots (which enables this scenario) there's an API for that.  But .NET doesn't expose it yet (#16364 is the "we need to design this API" issue).

**Comment by shortspider** [comment]
> Their opinion is that if you want contextually trusted roots (which enables this scenario) there's an API for that. But .NET doesn't expose it yet

Lol fair enough. I'll keep an eye on that issue then. Thank you for the quick responses.

**Comment by bartonjs** [comment]
This is fixed in 3.0 now.

**Comment by shortspider** [comment]
@bartonjs thanks for the update.What exactly was fixed, the differing behavior between Windows and Linux for checking the CRL or setting a custom root for a single call? #16364 still looks open so I'm guessing the first one?

**Comment by bartonjs** [comment]
You are correct. Linux chains are now more consistent with Windows chains.
