### ISSUE TITLE
Clean build failing all SqlClient tests with JSON parsing exception

### ISSUE THREAD

**Issue by ssa3512** [dotnet/corefx#34588]
After pulling latest master and running `build -allconfigurations`, `build src\System.Data.SqlClient -allconfigurations` fails citing JSON parsing errors on `xunit.console.runtimeconfig.json` files
https://gist.github.com/ssa3512/efd3a0ca3f26896e6afee7d84ff02243

Contents of `artifacts/bin/tests/System.Data.SqlClient.Tests/xunit.console.runtimeconfig.json` are
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <developmentMode developerInstallation="true" />
    <UseRandomizedStringHashAlgorithm enabled="1" />
  </runtime>
</configuration>
```
which is XML, not JSON

**Comment by karelz** [comment]
@wtgodbe is it a known issue?

**Comment by wtgodbe** [comment]
I haven't seen this before, I'll see if I can repro locally. We do have test coverage for `AllConfigurations` builds, but I don't know of anywhere where we build individual projects with `AllConfigurations`, so that may be a gap.

**Comment by wtgodbe** [comment]
@ssa3512 what exact command did you run, and from what directory, to produce your error? I ran `dotnet msbuild /p:BuildAllConfigurations=true` from both `corefx\src\System.Data.SqlClient` and `corefx\src\System.Data.SqlClient\src`, and both succeeded

**Comment by ssa3512** [comment]
From a vs 2017 developer command prompt at `corefx\` I ran
`build -allconfigurations`
`build src\System.Data.SqlClient -allconfigurations`

**Comment by Wraith2** [comment]
from the gist above you can see `A JSON parsing exception occurred in [C:\Projects\corefx\artifacts\bin\tests\System.Data.SqlClient.Tests\netcoreapp-Windows_NT-Debug-x64\` so it's coming from the tests. I get the same thing when using all configurations on sqlclient, there are always test problems though so I ignore them as long as I can get the tests to run successfully for the target i need.

**Comment by ViktorHofer** [comment]
I would surprised if this is still happening. I will try it out and assign the issue to myself.

**Comment by Wraith2** [comment]
Not the same issue (this one is a runtime problem iirc) but if you're looking at sqlclient build there's a specific problem if you run the command 
```build src\System.Data.SqlClient -c Release && dotnet msbuild .\src\System.Data.SqlClient\tests\ManualTests /t:RebuildAndTest``` which causes ```E:\Programming\csharp7\corefx\Directory.Build.props(412,3): error MSB4019: The imported project "E:\Programming\csharp7\corefx\artifacts\bin\runtime\netcoreapp-Windows_NT-Release-x64\Microsoft.NET.Test.Sdk.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [E:\Programming\csharp7\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]```
if you change to Debug it's fine. I assumed it was a minor tooling error somewhere and since I need to run the tests in Debug for dev I didn't raise an issue for it, since you'll be looking at it anyway... 😁

**Comment by ViktorHofer** [comment]
This sounds like a VERY old corefx build and I'm sure that doesn't happen anymore on latest master.

**Comment by ViktorHofer** [comment]
Also it hints that you didn't build from root in release mode first but as said, this is touching infra that isn't used anymore in master.

**Comment by Wraith2** [comment]
Whenever I have build problems I clean, update to get to a current master and then build all configs, debug and release. So I'm fairly sure this is current, from my recollection it coincided with you doing a bulk update of test projects a few weeks ago. It's not urgent and doesn't block dev so as I said if you're already in the tests project it'd be nice if it was fixed but don't worry about it.

**Comment by ViktorHofer** [comment]
Just tried locally and it works as expected. The correct command is:

```
build.cmd -allconfigurations
dotnet msbuild /t:Rebuild src\System.Data.SqlClient\pkg
```

**Comment by ViktorHofer** [comment]
>  It's not urgent and doesn't block dev so as I said if you're already in the tests project it'd be nice if it was fixed but don't worry about it.

I'm relatively sure this is already fixed in master.
