### ISSUE TITLE
Add language to library-servicing.md for Private packages in 1.x

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/corefx#34591]
We need to add info to https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/library-servicing.md about what to do in the case of 1.x.x Private packages. For example, `System.Private.Uri` has no Ref assembly, and builds runtime packages, meaning that the base packages has no `lib` folder. This causes buildtools to throw an error when we try to bump the AssemblyVersion & add a `AssemblyVersionInPackageVersion` error. Our workaround for this was to avoid adding a `AssemblyVersionInPackageVersion` entry, and rather to update the `BaselineVersion`. We should determine if we want that to be our policy (and therefore add it to the doc), or if we should fix the tooling in 1.x.x buildtools (It was already fixed in master here: https://github.com/dotnet/buildtools/commit/066e80bcad46c37fdcf097dfa8c2b743c2f45763#diff-2cd7181464965577be98f226e5ad075d)

CC @ericstj @rmkerr

**Comment by ViktorHofer** [comment]
@wtgodbe do we still want to do this given that 1.0 and 1.1 reach out-of-support in four days?

**Comment by wtgodbe** [comment]
Nope, we can close this.
