### ISSUE TITLE
Universal Windows Platform update

### ISSUE THREAD

**Issue by virzak** [dotnet/corefx#34625]
Apologies if this is an inappropriate place to ask, but in May 2018 it was [announced](https://blogs.msdn.microsoft.com/dotnet/2018/05/07/net-core-3-and-support-for-windows-desktop-applications/) that UWP is moving to .net core 3. The preview doesn't contain a uwp template and the uwp branch in this project doesn't contain recent commits. What's the plan for UWP?

**Comment by danmosemsft** [comment]
@vatsan-madhavan can answer that I think.

**Comment by davidsh** [comment]
@tommcdon

**Comment by karelz** [comment]
My understanding of that announcement was that UWP XAML will be available in .NET Core 3.0 as UI stack. Are you asking when it is going to happen @virzak?

@fabiant3 @ptorr-msft should be able to answer details there / route it further. cc @amit-kabra

**Comment by ptorr-msft** [comment]
@karelz is correct; the announcement was about using "UWP XAML" (or "Windows UI XAML") in desktop projects with .NET Core 3. 

That said, we're always evolving the kinds of applications and frameworks that are supported in UWP. For example we introduced support for .NET Standard 2.0 a while ago, and starting in build 1803 (RS4 / Spring Creators Update / OS version 17134) we enabled [command-line apps in UWP using .NET Native](https://blogs.windows.com/buildingapps/2018/06/06/c-console-uwp-applications/#AqpSD4IHK9psAEVq.97). 

Support for .NET Core 3 applications is something on our radar, but we have no official announcements at this time.

**Comment by TonyHenrique** [comment]
What is needed to run UWP on a .NET Core standalone EXE ?

**Comment by benaadams** [comment]
Aside: the OSS project for "UWP XAML" (or "Windows UI XAML") is here: https://github.com/Microsoft/microsoft-ui-xaml

**Comment by danmosemsft** [comment]
I think the original questions were answered.
