### ISSUE TITLE
Semantics of writing null strings using the Utf8JsonWriter (for properties and values)

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#34632]
Currently, for consistency with the span overload, the Utf8JsonWriter treats a null string parameter equivalent to an empty span and writes an empty string.

This applies to both property names and values.

**So, for example, here is what we have today:**
```C#
string propertyName = null;
string value = null;

jsonUtf8.WriteStartObject();
jsonUtf8.WriteString(propertyName, value); // equivalent to writing propertyName.AsSpan(), value.AsSpan()
jsonUtf8.WriteStartArray(propertyName); // equivalent to writing propertyName.AsSpan()
jsonUtf8.WriteStringValue(value); // equivalent to writing value.AsSpan()
jsonUtf8.WriteEndArray();
jsonUtf8.WriteEndObject();
jsonUtf8.Flush();

// output = {"":"","":[""]}
// output from Json.NET = {"":null,"":[null]}
```

1) Should we instead change the semantics of **writing string values** and write the `null` characters instead (to match Json.NET)?
2) Should we throw an exception if the **property name** being passed in is a null string or continue to write an empty property name (to match Json.NET)?

Unlike strings, there is no difference between a "null" span and an empty span.

**Note:** Json.NET treats "null" property name strings as empty strings, but "null" values as the `null` literal.

cc @JamesNK, @bartonjs, @jkotas, @GrabYourPitchforks, @steveharter

**Comment by Tornhoof** [comment]
As Utf8JsonWriter is a fairly low-level API, I would throw for ``null`` in the property name and for string value. If someone wants to write ``null`` they should use ``WriteNullValue``.

**Comment by jkotas** [comment]
> I wouldn't inspect the spans to find out if they were "empty spans" or "default spans"

Agree. Any code that is trying to make distinction between "empty spans" and "default spans" in public APIs is broken.

**Comment by JamesNK** [comment]
> As Utf8JsonWriter is a fairly low-level API

Is it though? `JsonDocument` is readonly. If someone wants to write adhoc JSON, they only have the writer, or building up a graph of objects and then calling the serializer.

> Should we instead change the semantics of writing string values and write the null characters instead (to match Json.NET)?

Strings are often null. What would a user want? I think they just want the the value to be written. If it is a string then they want a string value, if it is null then they want null value. Making people check for null before calling `WriteString` is making them do work that the writer could easily do itself.

> Should we throw an exception if the property name being passed in is a null string or continue to write an empty property name (to match Json.NET)?

I didn't know Json.NET wrote an empty string property for null. If I could change it I would throw ArgumentNullException.

**Comment by Tornhoof** [comment]
> Is it though? JsonDocument is readonly. If someone wants to write adhoc JSON, they only have the writer, or building up a graph of objects and then calling the serializer.

Maybe a matter of perspective, but you need to write the JSON structure yourself, you get help regarding separators etc. though (that's the "fairly" part), if someone is capable of writing a valid JSON structure and remembers to write start/end symbols properly, I'd say they can remember to use WriteNullValue for strings and/or properties.
Writing valid JSON and using the API in general  is not that trivial that you can use it exploratory (if you don't already know JSON well enough and if you know JSON you probably will look out for ``WriteNullValue`` anyway), so if the ``ArgumentNullException`` is well documented, I'd say most users will notice it.

I admit I didn't really follow ``JsonDocument`` and if that one is read-only, I'd make sure that the Serializer can serialize Dictionaries and maybe add an extension method from JsonDocument to Dictionary.

**Comment by bartonjs** [comment]
Okay, I guess I can buy `WriteString(null)` emitting the JSON token `null`.  As a property name argument, however, it should throw.

Yeah, if the caller called AsSpan() themselves they'd write the empty string; but the caller deferral through AsSpan is the caller's bug.

**Comment by steveharter** [comment]
For consistency, if we change this for the writer, I believe we should match semantics in JsonDocument where its ToString() today outputs empty string and not the "null" literal.

**Comment by ericstj** [comment]
@bartonjs do you have the cycles to pick this up?

**Comment by GSPP** [comment]
Silently coercing `(string)null` to `""` is dangerous. The change to emit `null` is appropriate.

**Comment by ahsonkhan** [comment]
> For consistency, if we change this for the writer, I believe we should match semantics in JsonDocument where its ToString() today outputs empty string and not the "null" literal.

@bartonjs, thoughts on making this change?

**Comment by bartonjs** [comment]
People are frequently surprised by ToString returning null.  If you feel there's a strong case you can make it.  But since ToString is mainly intended for being written to a console window during debugging it's not really actionable to have them be different (aside from an exception in querying the Length of it).

**Comment by ahsonkhan** [comment]
> But since ToString is mainly intended for being written to a console window during debugging it's not really actionable to have them be different

Sounds good to me. `JsonElement.GetString` returns the "right" thing anyway.
