### ISSUE TITLE
Use NativeLibrary APIs where possible

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/corefx#34633]
Use `System.Runtime.Interop.NativeLibray`  APIs instead of directly using native calls when possible in CoreFX libraries.

There are some calls to `dlopen` in CoreFX libraries, especially in System.Drawing, where it would be good to use the `NativeLibrary` API. However, these calls may run into the [limitation](https://github.com/dotnet/coreclr/issues/22028) that there is no way to pass additional flags to `dlopen` via the `NativeLibrary.Load`.

**Comment by am11** [comment]
The bottom-most function, where CoreCLR calls `dlopen`, simply uses `RTLD_LAZY` flag: https://github.com/dotnet/coreclr/blob/7760228/src/pal/src/loader/module.cpp#L1485. Would it make sense to have it documented in XML comments of [`Load` and `TryLoad` methods](https://github.com/dotnet/coreclr/blob/2c61b985c0513d9a70eee7221fa15910e7003d16/src/System.Private.CoreLib/src/System/Runtime/InteropServices/NativeLibrary.cs) for the end consumer?

From dlopen [docs](http://pubs.opengroup.org/onlinepubs/009695399/functions/dlopen.html):

> **RTLD_LAZY** - Relocations shall be performed at an implementation-defined time, ranging from the time of the dlopen() call until the first reference to a given symbol occurs. Specifying RTLD_LAZY should improve performance on implementations supporting dynamic symbol binding as a process may not reference all of the functions in any given object. And, for systems supporting dynamic symbol resolution for normal process execution, this behavior mimics the normal handling of process execution.
> **RTLD_NOW** - All necessary relocations shall be performed when the object is first loaded. This may waste some processing if relocations are performed for functions that are never referenced. This behavior may be useful for applications that need to know as soon as an object is loaded that all symbols referenced during execution are available. 

If https://github.com/dotnet/coreclr/issues/22028 moves forward, we will get additional configuration in `NativeLibrary.[Try]Load` API methods to select the mode.

@stephentoub, @jkotas, if `RTLD_LAZY` is good enough for many common use-cases, including all CoreCLR's `PAL_LoadLibraryDirect` use-cases (which is used beyond `NativeLibrary` APIs), would it not suffice for System.Drawing and other usages of `Interop.Libdl.dlopen` in CoreFX methods as well? It seems bit wasteful to load all libgdiplus' symbols up front. If so, IMO, we can already use `NativeLibrary.Load` and/or `NativeLibrary.TryLoad` in CoreFX to replace `Interop.Libdl.dlopen` today.

**Comment by jkotas** [comment]
> would it not suffice for System.Drawing and other usages of `Interop.Libdl.dlopen` in CoreFX as well?

I think it should be sufficient.

> remove `Interop.Libdl.dlopen`

`System.Drawing.Common` is built as a package that targets netcoreapp2.0. `Libdl.dlopen` would need to stay for the build that targets netcoreapp2.0.

**Comment by joshfree** [comment]
@safern can you drive this for System.Drawing and then for the remaining `dlopen` calls across corefx?

**Comment by am11** [comment]
All instances of dlopen in CoreFX were replaced in #35548 and #36944 for .NET Core 3.0+.

**Comment by jkotas** [comment]
@am11 Thank you for fixing this!

**Comment by safern** [comment]
Thanks @am11 😄
