### ISSUE TITLE
HttpClient isn't always canceling in response to cancellation requests

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/corefx#3464]
We first found this issue with a WCF negative test that expected a TimeOutException when setting a ‘SendTimeout’ on our BasicHttpBinding and calling a service operation that took longer to return.

Previously this test passed with the elapsed time being just a little longer than the ‘SendTimeout’ value. As of a couple weeks ago we still got the TimeOutException but the elapsed time seemed to correlate to however long it took for the call to return from the service operation.

So if the ‘SendTimeout’ was set to 5 milliseconds and the service operation waited 30 milliseconds to return, the elapsed time would be something over 30 milliseconds.
As best we could determine it has something to do with the CancellationTokenSource perhaps when it is creating the linked token source and passing it to the SetTimeout method. (HttpClient.cs SendAsync method)

We isolated this issue using no WCF code with the following client side code…
```csharp
        Stopwatch watch = new Stopwatch();
        HttpClient client = new HttpClient();
        HttpRequestMessage message = new HttpRequestMessage();
        message.RequestUri = new Uri("http://localhost:54464/Home/About");
        var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));
        try
        {
            watch.Start();
            var responseTask =  client.SendAsync(message, cts.Token);
            responseTask.Wait();            
        }
        catch (Exception ex)
        {
            Debug.WriteLine(ex.Message + "\n" + ex.StackTrace);
        }
        finally{
            watch.Stop();
        }

        Assert.InRange<long>(watch.ElapsedMilliseconds, 8000, 15000);
```
In this example we are just calling the ‘About’ page of an ASP.NET MVC application (default VS template) and just added the following in the HomeController.About() method…
```csharp
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";
            Thread.Sleep(30*1000);
            return View();
        }
```
**NOTE: I have no idea why but it seems to work as expected when in debug mode, the issue reproduces when executed normally.**

**Comment by StephenBonikowsky** [comment]
I've opened Issue: https://github.com/dotnet/corefx/issues/3464 in the corefx repo. Will send out a PR soon for the test.

**Comment by stephentoub** [comment]
cc: @davidsh, @cipop

**Comment by stephentoub** [comment]
Regarding the title of this issue, I don't believe this has anything to do with CancellationTokenSource not working as expected. Cancellation is being requested as desired... it's just that the consumer of the CancellationToken isn't being aggressive about responding to the request.

**Comment by StephenBonikowsky** [comment]
Please feel free to update the title to something more accurate, I'm not familiar with the code base where this is occurring.

**Comment by davidsh** [comment]
Since PR #3000 was done, this issue doesn't occur anymore. The cancellations are more responsive. The test above passes.
