### ISSUE TITLE
String Join . Add overloads without separator.

### ISSUE THREAD

**Issue by ichensky** [dotnet/corefx#34671]
Proposal:
Add `Join` overloads, that it become possible to use this method  without separator.

for ex. instead of code
```csharp
var str = string.Join("",list);
``` 

use this: 
```csharp
var str = string.Join(list);
```

**Comment by Tornhoof** [comment]
What about ``string.Concat``?

https://docs.microsoft.com/en-us/dotnet/api/system.string.concat?view=netcore-2.2#System_String_Concat__1_System_Collections_Generic_IEnumerable___0__

**Comment by Wraith2** [comment]
Marking things as deprecated using the Obsolete attribute is considered a breaking change because a lot of people use the treat warnings as errors option and doing so causes obsoletion causes working code to suddenly not in that circumstance.

**Comment by joshfree** [comment]
We wouldn't obsolete Concat because Join is arguably a nicer name 😉

I'm going to close this api-suggestion given the discussion wrapped up in January.  Feel free to reactivate with more details.  Thank you
