### ISSUE TITLE
Add RFC3161 to netstandard2.0 in the Pkcs package

### ISSUE THREAD

**Issue by PatoBeltran** [dotnet/corefx#34687]
In the NuGet clients we do package signing and we support time-stamping to those package signatures. We are working towards enabling the signing and verification scenarios cross platform.

According to https://github.com/dotnet/corefx/issues/24524 and https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.pkcs.rfc3161timestamptokeninfo.trydecode, the APIs related to RFC3161 timestamping were added to net core 2.1+. our libraries target netstandard2.0 and we are working towards the migration using the Pkcs package (we heavily rely on SignedCms, among others).

Consider adding RFC3161 related stuff to the netstandard2.0 contract in the Pkcs package.

cc. @dtivel @rrelyea @bartonjs

**Comment by bartonjs** [comment]
@terrajobst Is there anything that would go wrong by us exposing the types in the netstandard ref (and making sure that the netfx build works, of course)?  We seem to have never put the types in netfx, so there's no binder confusion to work around.

**Comment by PatoBeltran** [comment]
Any update on this? 

Also, is SignerInfo.GetSignature() part of the APIs that will get exposed because of this? [this comment](https://github.com/dotnet/corefx/issues/24524#issuecomment-361337499) suggests that it should, since it is used as part of verification of the timestamped data.

This is blocking the NuGet package signature verification migration to cross platform.

**Comment by bartonjs** [comment]
If I understood correctly: Because this package gets pulled into the AspNetCore.App shared framework we can't add new types or members to an existing TFM; that means that the `netstandard2.0` contract definition cannot be amended to include these types, it will have to wait for the `netstandard2.1` contract.

FYI @terrajobst

**Comment by rrelyea** [comment]
@bartonjs -
Does this already ship in netcoreapp2.1 or netcoreapp2.2?
If not, does it exist in netcoreapp3.0 current builds yet?
(if so, targetting netstandard 2.1 or netcoreapp3.0 should work)
Thanks.

**Comment by bartonjs** [comment]
@rrelyea The APIs are in netcoreapp2.1 (and 2.2 and 3.0); the trouble is with back-promoting them to netstandard2.0.

**Comment by heng-liu** [comment]
@bartonjs  - this is @rrelyea working on the computer of @heng-liu
In Feb, reading this now, i don't interpret you saying that this has been added to NetStandard 2.1.
Has it?
(we are proceeding with this work now, hoping everything we need is in NS2.1)

**Comment by bartonjs** [comment]
@heng-liu / @rrelyea No, the APIs are in **netcoreapp2.1**.  The .NET Standard 2.1 contract (**netstandard2.1**) has not been produced yet.  That's #36062.
