### ISSUE TITLE
Add Rune creation API from UTF-16 surrogate pair

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/corefx#34683]
__Edit Thu 24 Jan 2018:__ Modified API description below based on what we approved in API review.

Approved API:

```cs
public readonly struct Rune
{
    // NEW ctor
    public Rune(char highSurrogate, char lowSurrogate);

    // NEW static factory method
    public static bool TryCreate(char highSurrogate, char lowSurrogate, out Rune result);
}
```

This would benefit scenarios like @ahsonkhan's JSON parser, where he needs to reconstruct a Unicode scalar value from a candidate UTF-16 surrogate pair. In his case he hasn't yet validated that the incoming values represent a well-formed surrogate pair.

The closest API we have today to accomplish this is `Char.ConvertToUtf32(char, char) : int`, but that API throws an exception on invalid input, and its return type is separate from the `Rune` type we're trying to steer devs toward. This proposed API instead is a typical try-pattern API. The behavior would be that it returns _false_ and outs _default_ if the two input values aren't a well-formed UTF-16 surrogate pair.

If we want a non-try pattern API in addition, we can have a `(char, char)` ctor overload or make a static `Create...(char, char) : Rune` factory method.

**Comment by terrajobst** [comment]
Can we name this just `TryCreate`, given the overloads? It's clear from your signature that you're creating a rune from a surrogate pair.

We should also add the corresponding constructor.
