### ISSUE TITLE
Implement IndexOfOrdinal and LastIndexOfOrdinal in the ICU Shim

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#3468]
The naive implementation of these methods in CompareInfo.Unix.cs is correct but allocates both to do a substring and to case the string when ignore case is true.  We should just just implement these methods in the Shim itself.  It can walk the string without allocating and do casing inline without having to round trip to managed code for each character.

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/1816
