### ISSUE TITLE
Span<T> - IndexOf add overload with start index

### ISSUE THREAD

**Issue by Symbai** [dotnet/corefx#34706]
It would be great if IndexOf() has another overload allows to provide a start index from where it begins to search in Span<T>, similar to Array.IndexOf() and List.IndexOf() etc. This allows us to get more than just the first and last index of Span<T> in a Span<T>.

**Comment by benaadams** [comment]
Can slice for it? `span.Slice(x).IndexOf(y)`

**Comment by GSPP** [comment]
Thanks to span we no longer need this `int start, int count` pollution everywhere. Native APIs never have `start` because they don't need it because of pointers. With span we don't even need `count`. So we are even cleaner than native code.

I wish all those now legacy APIs with `int start, int count` could go away (but clearly they can't). If we only could start over with .NET 1.0... The framework would be absolutely beautiful incorporating what we know now.

**Comment by Symbai** [comment]
> 
> 
> Can slice for it? `span.Slice(x).IndexOf(y)`

Wouldn't that return the index in the sliced span instead?

**Comment by benaadams** [comment]
`span.Slice(x).IndexOf(y) + x`

**Comment by Symbai** [comment]
I wasn't looking for a solution just trying to say that in real situation your solution requires many additional lines of code. Imagine going through a loop and doing stuff with all indexes. With my overload it would be:

```
//pseudo code
while (pos = span.IndexOf(x, pos) != 1)
{
var value = span.Slice(pos)
}
```
And in your solution it becomes:
```
//pseudo code
var index = 0;
while (true)
{
 var pos = span.IndexOf(x);
 if (pos == -1)
break;
var value = span.Slice(pos)
index += pos;
span = span.Slice(pos)
}
```
 
I think the readability goes down with your slice solution, unless I'm wrong and my pseudo code can be written much cleaner (in this case I apologize), although it works the same. And that's what most overloads are for, to reduce the amount of lines we have to write for things we might do often.

**Comment by benaadams** [comment]
>  just trying to say that in real situation your solution requires many additional lines of code.

Yeah, I think that was @davidfowl's point

> The only other argument is that you want the actual index in the original span instead of an offset relative to the sliced span.

Though in your example the differences would be:
```csharp
var pos = 0;
while (pos = span.IndexOf(x, pos) != -1)
{
    var value = span.Slice(pos);
    // Do something will value
}
```

```csharp
int pos;
while (pos = span.IndexOf(x) != -1)
{
   span = span.Slice(pos);
   // Do something will span

}
```

**Comment by Symbai** [comment]
Ok I see, then my pseudo code was just terrible. I'm going to close the issue then, thanks for your help
