### ISSUE TITLE
error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure while using .NET Core

### ISSUE THREAD

**Issue by ramsubbaraoc** [dotnet/corefx#34740]
I get the following error during Authentication on Linux:

```
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. 
---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. 
---> Interop+Crypto+OpenSslCryptographicException: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
```

I had added the certificates using the following code:
```c#
         X509Store personalStore = new X509Store(StoreName.Root, StoreLocation.CurrentUser);
            personalStore.Open(OpenFlags.ReadWrite);
            X509Certificate2Collection collection2 = new X509Certificate2Collection();

            collection2.Import("client.p12", "12345", X509KeyStorageFlags.PersistKeySet);
            Console.WriteLine("Adding certificates into trusted store");
            foreach (X509Certificate2 cert in collection2)
            {
                Console.WriteLine("Subject is: '{0}'", cert.Subject);
                Console.WriteLine("Issuer is:  '{0}'", cert.Issuer);
                personalStore.Add(cert);
            }
```
   The error occurs during authentication and during the following call `stream.AuthenticateAsClient(SERVERNAME, currentClientCerts, sslProtocol, sslCertRevocationCheck);`

**Comment by ramsubbaraoc** [comment]
@bartonjs Please can you provide your inputs on this issue.

**Comment by bartonjs** [comment]
IIRC, `alert handshake failure` means the other party (the server role, in this case) sent an alert and closed the connection.  You'd need to grab a network trace to see what happened (no mutual ciphersuites, no mutual protocols, etc).

**Comment by ramsubbaraoc** [comment]
Thank you for the response,the server had closed the connection because the client hadn't provided the certificate even after the server requested for the certificate.
Is there a way to figure out if the client had sent the certificate or not?

**Comment by ramsubbaraoc** [comment]
Thank you for the response,the server had closed the connection because the client hadn't provided the certificate even after the server requested for the certificate.
Is there a way to figure out if the client had sent the certificate or not?

**Comment by bartonjs** [comment]
> Is there a way to figure out if the client had sent the certificate or not?

IIRC: if `currentClientCerts` only contains one value, and HasPrivateKey is `true`, it's always sent (if the server says it will accept a client cert).

Wireshark/et-al will of course say whether or not the client sent one.

Otherwise, I'm not sure.  @davidsh?

**Comment by ramsubbaraoc** [comment]
HasPrivateKey value is true.I did check that

**Comment by davidsh** [comment]
>IIRC: if currentClientCerts only contains one value, and HasPrivateKey is true, it's always sent (if the server says it will accept a client cert).

Actually, *"it's always sent"* is not true.  HttpClient and SslStream will still filter the collection of client certificates to find one meets all criteria to be sent.  So, for example, If the certificate has EKU attribute, then it must contain 'Client Authentication'.  And similarly for KU attribute, it must have 'Digital Signature', etc.

>Wireshark/et-al will of course say whether or not the client sent one.
Otherwise, I'm not sure. @davidsh?

Wireshark can detect this usually but I thought that the sending of the client certificate is done *after* the channel is encrypted.  So, unless you have TLS decryption you wouldn't see this.

You can turn on System.Net tracing and it should indicate information about client certificates being sent:

https://github.com/dotnet/corefx/blob/master/Documentation/debugging/windows-instructions.md#Traces

**Comment by bartonjs** [comment]
>  I thought that the sending of the client certificate is done after the channel is encrypted

In TLS 1.2 the optional client certificate is one of the last things before the ChangeCipherSpec.  In TLS 1.3 both certs are after the first ChangeCipherSpec, making it much harder to debug with Wireshark :smile:.

**Comment by ramsubbaraoc** [comment]
@davidsh @bartonjs Thank you
The same configuration works on windows,but on linux it fails with error i have stated.

**Comment by ramsubbaraoc** [comment]
@davidsh Please can you provide a way to debug on Linux

**Comment by ramsubbaraoc** [comment]
@davidsh @bartonjs 
I was able to resolve the issue by modifying my sample which adds the certificate to the keystore.Following is the sample that i had used:


```
X509Store personalStore = new X509Store(StoreName.Root, StoreLocation.CurrentUser);
            personalStore.Open(OpenFlags.ReadWrite);
            X509Certificate2Collection personalStoreCertificateCollection = (X509Certificate2Collection)personalStore.Certificates;
            int i = 0;
            foreach (X509Certificate2 x509 in personalStoreCertificateCollection)
            {
                personalStore.Remove(x509);
                ++i;
            }
            X509Certificate2 certificate1 = new X509Certificate2("client.p12", "12345");

            //Create a collection and add two of the certificates.
            X509Certificate2Collection collection = new X509Certificate2Collection();
            collection.Add(certificate1);

            //Add certificates to the store.
            **personalStore.Add(certificate1); 
            personalStore.AddRange(collection);**
            X509Certificate2Collection collection2 = new X509Certificate2Collection();

            collection2.Import("client.p12", "12345", X509KeyStorageFlags.PersistKeySet);
            Console.WriteLine("Adding certificates into trusted store");
            foreach (X509Certificate2 cert in collection2)
            {
                Console.WriteLine("Subject is: '{0}'", cert.Subject);
                Console.WriteLine("Issuer is:  '{0}'", cert.Issuer);
                personalStore.Add(cert);
            }
```

By adding the following couple of lines of code made it work

            personalStore.Add(certificate1); 
            personalStore.AddRange(collection);

**Comment by karelz** [comment]
@ramsubbaraoc how to debug on Linux: https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md#debugging-coreclr-on-linux

**Comment by helder-goncalves-cko** [comment]
Having the same issue running on `microsoft/dotnet:2.2-runtime-alpine` (also tried 2.1)

**MyHttpClientHandler :**

```
public class MyHttpClientHandler : HttpClientHandler
{
     public MyHttpClientHandler(List<X509Certificate2> certificates)
     {
         ClientCertificateOptions = ClientCertificateOption.Manual;
         SslProtocols = SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12;
         ServerCertificateCustomValidationCallback = delegate { return true; };

         foreach (var certificate in certificates)
         {
             ClientCertificates.Add(certificate);
         }
     }
}
```

**Program:**
```
    class Program
    {
        static async Task Main(string[] args)
        {
            try
            {
                var path = Path.Combine(Directory.GetCurrentDirectory(), @"certs/mycert.pfx");

                var certificates = new List<X509Certificate2>(new X509Certificate2(path, "password"));

                var httpClient = new HttpClient(new MyHttpClientHandler(certificates));

                var payload = /*my payload*/;

                var httpContent = new StringContent(payload, Encoding.UTF8, "application/json");

                var response = await httpClient.PostAsync("https://mysecreturl.com", httpContent);

                Console.WriteLine(await response.Content.ReadAsStringAsync());
            }
            catch (System.Exception ex)
            {
                Console.WriteLine($"Failed - {ex.Message}");

                var innerException = ex.InnerException;

                while(innerException != null)
                {
                    Console.WriteLine($"Inner - {innerException.Message}");
                    innerException = innerException.InnerException;
                }

                return;
            }

            Console.WriteLine("Works!!!!!");
        }
    }
```

**Output:**
```
load_certificate    | Failed - The SSL connection could not be established, see inner exception.
load_certificate    | Inner - Authentication failed, see inner exception.
load_certificate    | Inner - SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
load_certificate    | Inner - error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
```


Same code runs fine on Windows 10.

**Comment by ramsubbaraoc** [comment]
> 
> 
> @ramsubbaraoc how to debug on Linux: https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md#debugging-coreclr-on-linux

Thank you

**Comment by karelz** [comment]
@helder-goncalves-cko @ramsubbaraoc can you please try it out on 3.0 if it is still a problem? Thank you!

**Comment by wfurt** [comment]
Is there any update @helder-goncalves-cko @ramsubbaraoc ? It seems like this did not update for quite a while. Note that if you use self-signed certificate on server, OpenSSL is more strict about EKU and it will fail to connect unless expected flags are set.

**Comment by davidsh** [comment]
>Note that if you use self-signed certificate on server, OpenSSL is more strict about EKU and it will fail to connect unless expected flags are set.

To clarify, it is not just about EKU field. It is about KU field (Key Usage).

See this ASP.NET issue for a full analysis of best-practice for using self-signed certificates on Linux.
https://github.com/aspnet/AspNetCore/issues/7246

**Comment by wfurt** [comment]
Closing, since there is no response for a long time. On Linux, proper certificate extensions must be used (see linked issue). This is a platform limitation we will not be able to address. 
Reopen with more details if there is new evidence.

**Comment by networkfusion** [comment]
I would not define it as adding a proper certificate extension, but define it by adding the proper certificate to the store... I think it is a documentation issue (and possibly an ifdef between systems windows and Linux) where a note needs to be made to do this... and how to do it properly in a makefile (that is generated in docker via VS context menu)...

**Comment by wfurt** [comment]
https://github.com/dotnet/docs would be the right repo to track that unless @bartonjs or @davidsh  have other suggestions.
