### ISSUE TITLE
Possible bug on AppDomain.CurrentDomain.SetPrincipalPolicy

### ISSUE THREAD

**Issue by MarcoRossignoli** [dotnet/corefx#34745]
I'm working on https://github.com/dotnet/corefx/issues/34489 https://github.com/dotnet/corefx/compare/master...MarcoRossignoli:executioncontext
I did some tests on `AppDomain.CurrentDomain.SetPrincipalPolicy` and I found different behaviour between netfx and netcore
```cs
        private static void Main(string[] args)
        {
            Console.WriteLine(".NET Full " + typeof(object).Assembly.Location);
            AppDomain.CurrentDomain.SetPrincipalPolicy(System.Security.Principal.PrincipalPolicy.UnauthenticatedPrincipal);
            Console.WriteLine(Thread.CurrentPrincipal);
            Thread.CurrentPrincipal = new ClaimsPrincipal();
            Console.WriteLine(Thread.CurrentPrincipal);
            Thread.CurrentPrincipal = null;
            Console.WriteLine(Thread.CurrentPrincipal);
        }

        static void Main(string[] args)
        {
            Console.WriteLine(".NET Core " + typeof(object).Assembly.Location);
            AppDomain.CurrentDomain.SetPrincipalPolicy(System.Security.Principal.PrincipalPolicy.UnauthenticatedPrincipal);
            Console.WriteLine(Thread.CurrentPrincipal);
            Thread.CurrentPrincipal = new ClaimsPrincipal();
            Console.WriteLine(Thread.CurrentPrincipal);
            Thread.CurrentPrincipal = null;
            Console.WriteLine(Thread.CurrentPrincipal);
        }
```
outcome
```
.NET Full C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
System.Security.Principal.GenericPrincipal
System.Security.Claims.ClaimsPrincipal
System.Security.Principal.GenericPrincipal
Press any key to continue . . .

.NET Core C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.1\System.Private.CoreLib.dll

System.Security.Claims.ClaimsPrincipal

Press any key to continue . . .
```
The same for `PrincipalPolicy.WindowsPrincipal` 
Am I missing something?

This PR should introduce new behaviour https://github.com/dotnet/corefx/commit/6fb57a4bfe4504b60b3af769798b96ba15e6c842#diff-e17a6ed29a0800366d75c1548f5bbd5f

/cc @jkotas @Anipik

**Comment by jkotas** [comment]
This was bug in 2.1 and it should be fixed in 3.0 by the PR you have linked. Do you see the correct behavior in 3.0 live builds?

**Comment by jkotas** [comment]
#30187

**Comment by MarcoRossignoli** [comment]
> Do you see the correct behavior in 3.0 live builds?

I'll do check I'm OOF at the moment.

The PR is very old I thought it was already on 2.2, can you link me some documentation that explain how to know if commit is on x.x versione?So next time I won't waste your time with unuseful question on it.

**Comment by MarcoRossignoli** [comment]
Maybe search commit on x.x branch?

**Comment by jkotas** [comment]
The commits are tagged with the releases once they make it to one. E.g. you can see this on the commit you have linked.

![image](https://user-images.githubusercontent.com/6668460/51553942-ed48b100-1e28-11e9-933c-b3ae93bf1aaf.png)

>  2.2

There are very mimimal runtime and framework changes in 2.2. The runtime and framework in 2.1 and 2.2 are almost the same. All interesting changes in 2.2 are from ASP.NET.

**Comment by jkotas** [comment]
> Maybe search commit on x.x branch?

That works too.

**Comment by MarcoRossignoli** [comment]
Thank's, after check I'll close

**Comment by MarcoRossignoli** [comment]
All ok with 3.0 preview, thank's again.
