### ISSUE TITLE
API proposal: OperationStatus-based UTF-8 transcoding APIs

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/corefx#34761]
__Proposal:__

```cs
namespace System.Text.Unicode
{
   public static class Utf8
   {
        /*
         * OperationStatus-based APIs for transcoding of chunked data.
         * This method is similar to Encoding.UTF8.GetBytes / GetChars but has a
         * different calling convention, different error handling mechanisms, and
         * different performance characteristics.
         *
         * If 'replaceInvalidSequences' is true, the method will replace any ill-formed
         * subsequence in the source with U+FFFD when transcoding to the destination,
         * then it will continue processing the remainder of the buffers. Otherwise
         * the method will return OperationStatus.InvalidData.
         *
         * If the method does return an error code, the out parameters will represent
         * how much of the data was successfully transcoded, and the location of the
         * ill-formed subsequence can be deduced from these values.
         *
         * If 'replaceInvalidSequences' is true, the method is guaranteed never to return
         * OperationStatus.InvalidData. If 'isFinalChunk' is true, the method is
         * guaranteed never to return OperationStatus.NeedMoreData.
         */

       public static OperationStatus ToBytes(ReadOnlySpan<char> source, Span<byte> destination, bool replaceInvalidSequences, bool isFinalChunk, out int numCharsRead, out int numBytesWritten);
       public static OperationStatus ToChars(ReadOnlySpan<byte> source, Span<char> destination, bool replaceInvalidSequences, bool isFinalChunk, out int numBytesRead, out int numCharsWritten);
   }
}
```

__Discussion:__

This is an `OperationStatus`-based chunking API used for transcoding UTF-8 data (as bytes) to UTF-16 data (as chars). It is similar to `System.Text.Encoder` and `System.Text.Decoder` in philosophy, but it's designed to work with chunked buffers using the new `OperationStatus`-based pattern.

Consider a developer who calls the existing API `Encoding.UTF8.GetEncoder().Convert(...)` in a loop, slicing the source and destination buffers as appropriate. There are certain failure cases that the developer can still run into if they aren't paying strict attention. For example, the existing `Convert` method may throw if the destination buffer isn't at least 4 bytes in length. The way the documentation [suggests working around this](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoder.convert) is to call `Encoder.GetByteCount` within each iteration of the loop to ensure that the destination buffer is large enough, but now the loop is doing twice as much work as it needs to: it's running over the data once to compute the length, and then it's running over the data again to perform the transcoding.

```cs
public void ChunkedTranscode(ReadOnlySequence<char> source, IBufferWriter<byte> destination)
{
   var encoder = Encoding.UTF8.GetEncoder();
   while (!source.IsEmpty)
   {
      // n.b. below line can throw an OverflowException, even on valid input
      int byteCount = encoder.GetByteCount(source.First.Span, false /* flush */);

      Span<byte> tempDest = destination.GetSpan(byteCount);
      encoder.Convert(source.First.Span, tempDest, false /* flush */, ...);

      source = source.Slice(charsUsed);
      destination.Advance(bytesUsed);
   }

   int finalByteCount = encoder.GetByteCount(ReadOnlySpan<char>.Empty, true /* flush */);
   Span<byte> finalTempDest = destination.GetSpan(finalByteCount);
   encoder.Convert(ReadOnlySpan<char>.Empty, finalTempDest, true /* flush */, ...);

   if (!finalCompleted)
   {
      throw new Exception("Something terrible happened.");
   }

   destination.Advance(finalBytesUsed);
}
```

The API proposed here involves only a single pass, which makes it appropriate for scenarios like the high-performance JSON parser. Like all `OperationStatus`-returning methods, the contract is "consume as much data as you can, and tell me how far you got." The API is stateless.

The existing `Convert` methods could eventually be changed to use these new APIs as workhorse routines if we so desire.

The "replace invalid sequences" parameter exists because it's common during transcoding to want to replace invalid source data with U+FFFD (�) in the destination. This is the Unicode recommendation. The Unicode Specification also recommends a system for determining how many invalid elements to consume from the source and how many U+FFFD (�) replacement characters to emit to the destination. Since this logic is quite complicated, I opted to allow the caller to say "please handle this on my behalf" rather than forcing them to implement the logic themselves.

__Open questions:__

* What type should expose these APIs? I put them on a new `Utf8` static utility class instead of the existing `UTF8Encoding` class for a few reasons. First, very few people reference `UTF8Encoding` directly, instead opting to get an instance of it via the `Encoding.UTF8` convenience property. Second, the proposed APIs are very opinionated in how they handle errors and how they perform character replacement, and a static method on `UTF8Encoding` might differ in behavior from an overridden virtual method on a derived type.

/cc @ahsonkhan @tarekgh

**Comment by GrabYourPitchforks** [comment]
Just as a clarification:

When these `OperationStatus`-based transcoding methods encounter invalid input, if the "replace invalid sequences" flag is set, then the output will be identical to the default `Encoding.UTF8` error handling logic. That is, both the proposed APIs and the default (_non-overridden_) inbox implementation insert the same number of U+FFFD (�) characters in the same positions in the destination. This is to allow better interoperability between the two APIs and to make sure that both APIs are following Unicode best practices.

**Comment by tarekgh** [comment]
> When these OperationStatus-based transcoding methods encounter invalid input, if the "replace invalid sequences" flag is set, then the output will be identical to the default Encoding.UTF8 error handling logic. 

I recall the compiler guys had a scenario which wanted to round trip the conversion between UTF8 and UTF16 even when having invalid characters. we never supported this scenario before but I think they needed it specifically to handle file names which is possible to run into such scenario. So, I am wondering is this something can be supported by your new proposed APIs?

**Comment by GrabYourPitchforks** [comment]
@tarekgh It wouldn't be called UTF-8 at that point, so I don't think we'd have built-in support for that. But yes, any dev could implement it themselves on top of this API. Here's a rough guide how to do so (for invalid UTF-8 to invalid UTF-16 and back to invalid UTF-8).

1. Call `ToChars`, passing _replaceInvalidSequences=false_. If the operation completes without error, great! If it returns `OperationStatus.InvalidData`, see below.
2. The output of the _numBytesConsumed_ parameter will be the index in the source byte span which contained the first invalid byte. Assume the byte is `0xXY`. Write the standalone surrogate character `0xD8XY` to the destination buffer. So if the input byte was `0xF5`, you'd write `0xD8F5` to the destination buffer.
3. Slice both the source and the destination buffer by 1 element, then go back to Step (1).

To reverse the operation, call `ToBytes`. If the operation returns failure due to a standalone surrogate character, cast the `char` to a `byte` and write it directly to the destination buffer.

The fact that this API returns `OperationStatus` and tells the caller exactly where the failure is makes it more flexible than the built-in API that either does replacement or throws an exception. The developer is empowered to provide custom error handling semantics if they wish. You can do something somewhat similar with the existing APIs by using a custom `DecoderFallback` and `DecoderFallbackBuffer`, but those classes forbid derived types from intentionally introducing invalid UTF-8 or UTF-16 into their fallback buffers, so they aren't usable for round-tripping invalid data losslessly.

**Comment by gfoidl** [comment]
Change to order of parameters to be analogous to other places\*:
```c#
public static OperationStatus ToBytes(ReadOnlySpan<char> source, Span<byte> destination, bool replaceInvalidSequences, out int numCharsRead, out int numBytesWritten, bool isFinalChunk = true);
public static OperationStatus ToChars(ReadOnlySpan<byte> source, Span<char> destination, bool replaceInvalidSequences, out int numBytesRead, out int numCharsWritten, bool isFinalChunk = true);
```

\*: e.g. https://github.com/dotnet/corefx/blob/bc0cfc49d1a8c1681fb09603f3389ef65342d542/src/System.Memory/ref/System.Memory.cs#L348

**Comment by GrabYourPitchforks** [comment]
Resolved in https://github.com/dotnet/corefx/pull/34538.
