### ISSUE TITLE
Two OSX HttpClientHandlerTest Failures in CI

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#3476]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_mac_debug_tst/42/testReport/System.Net.Http.Functional.Tests/HttpClientHandlerTest/GetAsync_ResponseHeadersRead_ReadFromEachIterativelyDoesntDeadlock/

http://dotnet-ci.cloudapp.net/job/dotnet_corefx_mac_debug_tst/42/testReport/System.Net.Http.Functional.Tests/HttpClientHandlerTest/GetAsync_CredentialIsNetworkCredentialUriRedirect_StatusCodeUnauthorized/

**Comment by ellismg** [comment]
/cc @stephentoub @vijaykota @davidsh @CIPop 

Not sure if this is intermittent or not, since it seems like other tests that wanted to talk to the same server passed?

**Comment by kapilash** [comment]
I just ran all the tests from an OSX box and all succeeded. I initiated a test run again on one of my pull requests.

**Comment by kapilash** [comment]
![screen shot 2015-09-26 at 1 05 09 pm](https://cloud.githubusercontent.com/assets/113322/10116342/641d59b2-644f-11e5-90e7-092801e886d4.png)

**Comment by kapilash** [comment]
Do the OSX tests run along as a part of the usual CI run? 
They does not seem to.  Can we have a rerun please? 
As mentioned earlier, these tests are running on my OSX dev machine.  More over, there's no reason for these two particular tests to fail on only one of the Unix platforms. Not with the error mentioned (``` System.Net.Http.CurlException : Couldn't connect to server ```)

**Comment by ellismg** [comment]
They don't run per PR right now (hopefully that will be fixed next week) we do one run every day instead.  I'll keep an eye on it.

**Comment by kapilash** [comment]
@ellismg  is this still an issue?

**Comment by ellismg** [comment]
Nope.  They have been passing recently.
