### ISSUE TITLE
Trying to build and run tests locally is failing with error NETSDK1004: Assets file '...' not found

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#34765]
- VS 2017 developer command prompt
- Windows 10 (x64) machine
- dotnet --version: 3.0.100-preview-010143

**Steps to repro:**
- `build.cmd` (or `build.cmd -allconfigurations`) on a clean clone of the corefx repo
- Move to some test directory (in my case `System.Text.Json\tests`)
- `dotnet msbuild` (or `dotnet msbuild /t:BuildAndTest`)

```text
C:\Program Files\dotnet\sdk\3.0.100-preview-010143\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(232,5): error NETSDK1004: Assets file 'E:\GitHub\Fork\corefx\artifacts\obj\System.Text.Json.Tests\project.assets.json' not found. Run a NuGet package restore to generate this file. [E:\GitHub\Fork\corefx\src\System.Text.Json\tests\System.Text.Json.Tests.csproj]
```

I tried clearing my local nuget cache and install the latest SDK globally. Anyone else seeing the issue or is something wrong with my local setup and install of dotnet?

Most likely this is an issue with my local setup where I have the latest SDK installed. I couldn't reproduce it on my Macbook.

cc @ericstj, @safern, @ViktorHofer

**Comment by ahsonkhan** [comment]
I do not see this issue if I uninstall the latest SDK and revert down to an older version (i.e. `3.0.100-preview-010006`).

The new SDKs available on https://github.com/dotnet/core-sdk has the issue (`3.0.100-preview-010136`  and `3.0.100-preview-010143`).

**Comment by ericstj** [comment]
I also noticed this with the latest SDK.  You can avoid this by using the local SDK (in .dotnet folder) : https://github.com/dotnet/corefx/blob/6c94c21afe03d2b9ffbbd80df26ad49587559a9b/Documentation/project-docs/dogfooding.md#install-prerequisites

Looks like the hack here was broken (/cc @eerhardt ): https://github.com/dotnet/corefx/blob/8ebea7a0bd164154805b5e3696f9f0795c5f6e4f/src/Directory.Build.targets#L33-L44 by the changes that @dsplaisted added for targeting packs: https://github.com/dotnet/sdk/blob/549597f4fbdfea526a1022cb1c81ed754888ee36/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.TargetingPackResolution.targets#L95.  I think we may want to have some more hooks on disabling these.

**Comment by ericstj** [comment]
We can disable this by setting DisableImplicitFrameworkReferences.  I'll submit a PR.
