### ISSUE TITLE
Option to support trailing commas with JsonReader

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#34794]
@JamesNK commented on [Mon Oct 29 2018](https://github.com/dotnet/corefxlab/issues/2576)

Comments and trailing commas are the most common differences from the JSON spec found in configuration files.

Consider adding an option to allow JsonReader to support trailing comments in JSON arrays and objects.

```json
{
  "myproperty": true,
}
```

```json
[
  "first",
  "second",
  "third",
]
```

---

@danmosemsft commented on [Wed Nov 07 2018](https://github.com/dotnet/corefxlab/issues/2576#issuecomment-436643604)

Comments above presumably should be commas

**Comment by JamesNK** [comment]
Two options is fine. I have never had the situation where someone asked for anything beyond turning them on or off. Up to you guys whether it is an enum or boolean.

I think this is an important option for ASP.NET Core's JSON config files. JSON like this is extremely common in JSON config files:

```
{
  "UseTls": "false",
  //"LogLevel": "Information"
}
```

@rynowak @davidfowl

**Comment by bartonjs** [comment]
I can't think of another mode for commas to be in, so boolean seems fine.

**Comment by MgSam** [comment]
As this introduces no ambiguity in the parsing, I think it should default to on. Pit of success.

**Comment by ahsonkhan** [comment]
Fyi, @wli3, this option has been added.
