### ISSUE TITLE
build failed with error "SourceRevisionId is not set, which means the SourceLink targets are not included in the build."

### ISSUE THREAD

**Issue by smartmaster** [dotnet/corefx#34800]
repro steps:
- download zip and extract to a local folder (note: not built in a git repo)
- run build.cmd in the root folder of corefx
- error reported as "C:\Users\admin\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19072.5\tools\Version.targets(69,5): error : SourceRevisionId is not set, which means the SourceLink targets are not included in the build. Those are needed to produce a correct sha for our build outputs. [F:\0\x\src\Native\build-native.proj]"

build env:
windows server 2019 + vs 2017 15.9.5

**Comment by danmosemsft** [comment]
@ViktorHofer

**Comment by ViktorHofer** [comment]
I think we fixed that early this morning in arcade.

**Comment by smartmaster** [comment]
just now tried C:\Users\admin\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19074.1\tools, still same error.
