### ISSUE TITLE
MemoryPool<T>.RentSlim for allocation-free leases

### ISSUE THREAD

**Issue by Grauenwolf** [dotnet/corefx#34833]
The current design of `MemoryPool<T>.Rent` returns an interface, which means an object has to be allocated. 

`MemoryPool<T>.RentSlim` would instead return a struct. While this would still be usable in a `using` statement, it wouldn't require heap-allocating memory.

`RentSlim` would be less user-friendly. As a struct, we cannot prevent copying which in turn means we can't prevent the object from being doubly-disposed. But as it is intended to only be used in conjunction with a `using` block there shouldn't be much of a problem.

P.S. I'm not enamored by the name RentSlim, but I can't think of a better one at the moment.

**Comment by benaadams** [comment]
Can also use `ArrayPool<T>.Rent` though you have to then use `ArrayPool<T>.Return` rather than `Dispose` as it returns a raw array.

**Comment by Grauenwolf** [comment]
That's actually what led me here. There was a proposal to add a disposable version of `Rent` to `ArrayPool<T>`. It was closed with a pointer to `MemoryPool<T>`, where I was surprised to learn that it returned an interface rather than a struct.

**Comment by benaadams** [comment]
Don't know if they are in the docs anywhere, but these docs might help as to why they are interfaces

[`Memory<T> API documentation and samples`](https://gist.github.com/GrabYourPitchforks/8efb15abbd90bc5b128f64981766e834)

[`Memory<T> usage guidelines`](https://gist.github.com/GrabYourPitchforks/4c3e1935fd4d9fa2831dbfcab35dffc6)

/cc @GrabYourPitchforks

**Comment by Grauenwolf** [comment]
Interesting. This does make the idea of a struct-based version of Rent impossible to generalize. That's too bad, but at least only you and I spent any time thinking about it.
