### ISSUE TITLE
Fix the baseline files for NS2.1

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#34863]
@wtgodbe owns this and it is in progress.

**Comment by joshfree** [comment]
@wtgodbe do you plan to have this finished in the 3.0 timeframe?

**Comment by wtgodbe** [comment]
This is a joint effort between myself and @terrajobst - I expect we will continue to drive the baselines down, and will have everything critical ironed out for 3.0.

**Comment by wtgodbe** [comment]
Our definition of "driving the baselines to zero" is "everything except attributes"

**Comment by terrajobst** [comment]
@wtgodbe 

Unless I can't read it seems the only non-attribute violations are Ref Emit, which is tracked by #36716. So we can close this one then.
