### ISSUE TITLE
CryptographicException: Error occurred during a cryptographic operation

### ISSUE THREAD

**Issue by ehajri** [dotnet/corefx#34876]
# Issue Title
Getting "_CryptographicException: Error occurred during a cryptographic operation._" on macOS Mojave.
# General
While trying aspnet core Identity from [this repo](https://github.com/aspnet/Docs/tree/master/aspnetcore/security/authentication/identity/sample/src/ASPNETCore-IdentityDemoComplete/IdentityDemo), I get this exception 

> System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.
>    at Internal.Cryptography.Pal.SecTrustChainPal.ParseResults(SafeX509ChainHandle chainHandle, X509RevocationMode revocationMode)

while executing [this line](https://github.com/aspnet/Docs/blob/446d68e78ab932f7285b2b7d15b685d413553326/aspnetcore/security/authentication/identity/sample/src/ASPNETCore-IdentityDemoComplete/IdentityDemo/Controllers/AccountController.cs#L224):
```c#
var result = await _userManager.CreateAsync(user, model.Password);
```
### Note
The project runs successfully under docker but not locally on mac.

# dotnet --info
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.500/

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  1.0.0-preview1-002702 [/usr/local/share/dotnet/sdk]
  2.0.2 [/usr/local/share/dotnet/sdk]
  2.1.300-rc1-008673 [/usr/local/share/dotnet/sdk]
  2.1.300 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.500 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.0-rc2-3002702 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by ehajri** [comment]
Appreciate any help or tip. I am not able to develop on my mac at the moment with the new Identity.

**Comment by danmosemsft** [comment]
@bartonjs

**Comment by danmosemsft** [comment]
@bartonjs I obviously am unfamiliar with this area but I notice the exception is the default text. I wonder whether in any of the cases we use the parameterless constructor for `CryptographicException` we have a little more info we can add to it? 

eg in this case `ret` perhaps.
```c#
                    // A return value of zero means no errors happened in locating the status (negative) or in
                    // parsing the status (positive).
                    if (ret != 0)
                    {
                        Debug.Fail($"X509ChainGetStatusAtIndex returned unexpected error {ret}");
                        throw new CryptographicException();
                    }
```

**Comment by ehajri** [comment]
After hours of investigation, upgrading/changing the installed nugets seem to have this exception fixed.
I am still not sure what was the real cause of the exception. I thought `Identity` uses some crypted kind of DbContext, tried to look deeper but couldn't find anything.

I, then, tried to create another DbContext for another purpose that (I am 100% sure) works on my machine (different project), but it still fails with the same exception.

I am closing the issue. Thanks @danmosemsft

**Comment by danmosemsft** [comment]
Thanks @ehajri . I'll leave this open just for my question above. Perhaps there's a little more diagnostic info we can log in this kind of case, even if it's an opaque value.

**Comment by bartonjs** [comment]
> I wonder whether in any of the cases we use the parameterless constructor for CryptographicException we have a little more info we can add to it?

In general, no.  Cryptography has to be a bit cryptic in the off-the-rails situations; too much helpfulness can lead to security issues.  The Debug.Fail indicates that we're clearly off the rails in this situation, and since we don't understand what we're reporting we don't want to report it to applications.
