### ISSUE TITLE
Fixing naming of `Sse41.Test*` and `Avx.Test*` methods

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#34882]
This issue is tracking 6 APIs in the `Sse41` class (3 of which have corresponding 256-bit overloads in the `Avx` class):
* These 3 exist in both
  * TestZ
  * TestC
  * TestNotZAndNotC
* These 3 exist only in `Sse41`
  * TestAllOnes
  * TestAllZeros
  * TestMixOnesZeros

The original issue was tracking both coming up with better names for the first three and determining what to do about the second three.

We have not been able to come up with better names for the first three, so the proposal is to keep them as is given that they mirror the names of the corresponding C/C++ intrinsics.
* The `Z` and `C` letters are indicating that the `Zero` and `Carry` flags are being checked as a result of the `Test` (a bitwise and is performed between the two operands).
* These all use the same underlying instruction `PTEST`. The Z flag is set if `(lhs & rhs) == 0`. The C flag is set if `(~lhs & rhs) == 0`

For the latter three, the proposal is to remove them entirely. `TestAllOnes` is a helper method that a user can implement themselves and where implementing it themselves is likely more beneficial, as they can hoist the `AllOnes` variable that is used in the comparison. The `TestAllZeros` and `TestMixOnesZeros` methods are merely alternatively named APIs for the `TestZ` and `TestNotZAndNotC` methods (respectively).

**Comment by tannergooding** [comment]
CC. @eerhardt, @terrajobst, @fiigii, @CarolEidt

**Comment by tannergooding** [comment]
_From @eerhardt on November 19, 2018 16:3_

Do we have a list of proposed/recommended new names?

**Comment by tannergooding** [comment]
I don't believe we currently have any proposed names. However, if this is being done, it needs to be done before 3.0.

**Comment by tannergooding** [comment]
It was raised in https://github.com/dotnet/coreclr/pull/22043#discussion_r251215809 that the `TestC`, `TestZ`, and `TestNotZAndNotC` methods are just duplicates to the `TestAllOnes`, `TestAllZeros`, and `TestMixOnesZeros` methods (respectively).

We could probably just delete the three former ones.

**Comment by mikedn** [comment]
`TestAllOnes` isn't a duplicate. Though it's not a real intrinsic either, it's a helper. It may be better to not have it in the first place, but the way to get an "all ones" mask is a bit cumbersome so perhaps it's useful to keep it.

**Comment by fiigii** [comment]
> but the way to get an "all ones" mask is a bit cumbersome so perhaps it's useful to keep it.

Perhaps we can add a new platform-agnostic intrinsic `Vector64/128/256<T>.AllOnes`.
That would be good for user experience and compiler implementation/optimization. 

With the `AllOnes` intrinsic, we can remove some "helper" intrinsic from the JIT inside or just provide them in managed implementation. Meanwhile, the current certain helper intrinsic (e.g., `TestAllOnes` and `Gather`) may have suboptimal codegen in loops (i.e., they generate the "all ones" mask in every loop iteration). If we have an `AllOnes` intrinsic IR at JIT mid-end, we can use loop-invariant code motion to avoid that duplicated computation, but that needs more work (e.g., enabling value numbering) on SIMD types and hw intrinsic.

**Comment by fiigii** [comment]
> methods are just duplicates to the TestAllOnes, TestAllZeros, and TestMixOnesZeros methods (respectively).

Yes, these duplicated APIs are from C/C++ intrinsic design. We kept them for helping developers easily porting C/C++ SIMD code to C#. 

But I do not think `TestAllZeros`, and `TestMixOnesZeros` are good names. For example, `TestAllZeros` makes sense when it operates over "masks", but `TestEqual` is a better name when it operates over "data". So, I prefer `TestC`, `TestZ`, and `TestNotZAndNotC` if we determine to remove the duplication.

**Comment by mikedn** [comment]
> Perhaps we can add a new platform-agnostic intrinsic Vector64/128/256<T>.AllOnes.

Perhaps, though that's just a convenient name for `Create(-1)`, if the JIT recognizes that.

> If we have an AllOnes intrinsic IR at JIT mid-end, we can use loop-invariant code motion to avoid that duplicated computation, but that needs more work (e.g., enabling value numbering) on SIMD types and hw intrinsic.

Doing value numbering for all intrinsics it's a ton of work and it's not clear if that's truly useful, developers can do their own hoisting. I think the main problem is that we offer this "test all ones" helper that may appear to be useful to developers but that the JIT doesn't handle well enough. Perhaps that's actually an argument for the removal of the helper - remove it and add `AllOnes` instead. Then the developers can do their own test and hoist `AllOnes` out of the loop if needed.

Also, it should be noted that this helper is present in SSE41 but not in AVX. That copies the native intrinsic world. But this seems like one of those things that shouldn't be copied, it should be present in both or not at all.

**Comment by fiigii** [comment]
> though that's just a convenient name for Create(-1), if the JIT recognizes that.

Ah, yes, we can let JIT recognize that in the constant vector optimization.

**Comment by mikedn** [comment]
> Yes, these duplicated APIs are from C/C++ intrinsic design. We kept them for helping developers easily porting C/C++ SIMD code to C#.

That's a dubious argument. The "easy porting" part was thrown out of the window together with the native intrinsic names that have been replaced by .NET names. At this point, if you want to port a large piece of intrinsic code from native to managed, you'll need a big mapping table. Otherwise you're going to waste a lot of time figuring it out. And if you have such a table, well, you can mention these duplicates in the table and call it a day.

**Comment by fiigii** [comment]
> I think the main problem is that we offer this "test all ones" helper that may appear to be useful to developers but that the JIT doesn't handle well enough. 

> But this seems like one of those things that shouldn't be copied, it should be present in both or not at all.

Agree, I prefer removing the duplicate APIs.

**Comment by tannergooding** [comment]
This needs more thought still. I don't think that `TestZ`, `TestC`, and `TestNotZAndNotC` are intuitive names.

I don't think it is terrible and they could likely be lived with, but I would like to come to a solid conclusion on what to do here. This will probably be one of:
* Close, leaving APIs "as-is"
* Remove one set of the "duplicated" APIs, deciding on the appropriate name
* Keep the nicely named methods like `TestAllZeros`, but rename the others (i.e. `TestZ` -> `TestEqual`)

**Comment by fiigii** [comment]
> * Close, leaving APIs "as-is"
> * Remove one set of the "duplicated" APIs

I prefer to leave APIs "as-is" and remove "duplicated" ones (that SSE4.1 has but AVX does not).

**Comment by mikedn** [comment]
Removing the duplicates is IMO a must. As for the names, well, I have no idea why MS is so obsessed with the name of intrinsics.

**Comment by danmosemsft** [comment]
@tannergooding can we clear this bug out (close or fix for 3.0 I guess) so we get this area path to zero for 3.0

**Comment by tannergooding** [comment]
`TestZ`, `TestC`, and `TestNotZAndNotC` are not necessarily intuitive names, but they do mirror the names of the C/C++ intrinsics and we've not been able to come up with better names.

`TestAllOnes` is merely a helper method and `TestAllZeros`/`TestMixOnesZeros` are just duplicated names.

The proposal is then to remove `TestAllOnes`, `TestAllZeros`, and `TestMixOnesZeros` from the `Sse41` class (we do not need to remove any from `Avx` as they already do not exist there and only `TestC`, `TestZ`, and `TestNotZAndNotC` are exposed).

CC. @terrajobst, @CarolEidt

**Comment by tannergooding** [comment]
Updated the original post to match the proposal I e-mailed to the framework design review alias.

**Comment by karelz** [comment]
API change approved via email.
