### ISSUE TITLE
Timer class issue on ARM (Raspbian/ubuntu stretch)

### ISSUE THREAD

**Issue by ModestasK** [dotnet/corefx#34887]
Setup:

**RaspberyPi 3**
- Distributor ID:	Raspbian
- Description:	Raspbian GNU/Linux 9.4 (stretch)
- Release:	9.4
- Codename:	stretch

**DotNet**

- Host (useful for support):
Version: 2.1.5
Commit:  290303f510

- .NET Core SDKs installed:
No SDKs were found.

- .NET Core runtimes installed:
Microsoft.AspNetCore.All 2.1.5 [/opt/dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.5 [/opt/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.5 [/opt/dotnet/shared/Microsoft.NETCore.App]

**SourceCode**

```c#
static void Main(string[] args)
{
      Timer runTimer = new Timer(
           (object state) => { Console.WriteLine("Hello"); },
           null,
           TimeSpan.Zero,
           TimeSpan.FromMinutes(1));

       while (true)
       {
           Thread.Sleep(5000);
       }
}
```

**Expected behaviour:** "_Hello_" should be printed into console every minute (which is actually the case on Ubuntu/Windows)

**Actual behaviour:** prints "_Hello_" only once and timer is never invoked again. This is what happens on Raspberry.

**Comment by danmosemsft** [comment]
@ModestasK transferred here (seems github issue move does not leave any bread crumb behind

**Comment by wfurt** [comment]
I could not reproduce it on my Raspberry running Raspbian.  Tested 2.1.2 and 3.0-master.

**Comment by tmds** [comment]
I guess the timer is subject to garbage collection.

What happens on Rasbian if you add a `runTimer.Stop` below the while loop? Does it keep the timer alive and running?

**Comment by stephentoub** [comment]
> I guess the timer is subject to garbage collection.

Yes.  Timers are not rooted by default.

**Comment by ModestasK** [comment]
I will try running this peace of code one more and if it behaves like this again I can let you in for playing with my raspberry over ssh.
Would that be of any use for you guys?

**Comment by wfurt** [comment]
ssh may be useful. I was trying to take a look but I could not reproduce it on my PI.

**Comment by karelz** [comment]
Not actionable, closing for now. Feel free to reopen once there is a solid repro that can be reproduced on other systems ...
