### ISSUE TITLE
Take another look at the `COMISS` and `UCOMISS` hardware intrinisics

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#34881]
It was raised in https://github.com/dotnet/coreclr/pull/22043#discussion_r251106117 that the names for the `COMISS` and `UCOMISS` hardware intrinsics might be confusing as the names (such as `CompareEqualOrderedScalar` and `CompareEqualUnorderedScalar`) might give the impression that the condition is ordered/unordered, when in fact it is the compare instruction that is ordered/unordered.

We should take another look at these names and determine if we can help alleviate the concern. Some initial suggestions are:
* `UnorderedCompareEqualScalar` and `OrderedCompareEqualScalar` or
* `CompareUnorderedEqualScalar` and `CompareOrderedEqualScalar`

It might also make sense to not expose the `ordered` versions of these intrinsics initially given that, since .NET does not support the IEEE floating-point exceptions, they are functionally equivalent to the `unordered` intrinsics. We should determine if we still want both versions of the intrinsics exposed.
* This will not make a difference on the naming decision above given that `CMPSS` (which returns ` Vector128<float>`) currently holds the `CompareEqualScalar` name

**Comment by benaadams** [comment]
`CompareScalarUnorderedEqual` and `CompareScalarOrderedEqual`

​i.e. `CompareScalarXxx`

or

`​​CompareScalarEqualUnordered` and `CompareScalarEqualOrdered`

**Comment by terrajobst** [comment]
A derivative of @benaadams suggestion @tannergooding suggested (where `Xxx` is `Equals`, `LessThan` etc):

* CompareOrderedScalarXxx
* CompareUnorderdScalarXxx

**Comment by tannergooding** [comment]
Hmm, we need to also determine if the corresponding `CompareEqualScalar` instructions should be renamed to `CompareScalarEqual` (and same with `CompareScalarLessThan`, etc).

We also need to determine what to do for the `FloatComparisonMode` enum (https://source.dot.net/#System.Private.CoreLib/shared/System/Runtime/Intrinsics/X86/Enums.cs,be9fc3e87d75220a,references). We have cases like:
* `EqualOrderedNonSignaling`
* `EqualOrderedSignaling`
* etc

**Comment by tannergooding** [comment]
Proposal is to change to `OrderedXxxSignalling` `OrderedXxxNonSignalling`, etc

**Comment by terrajobst** [comment]
Works for us.

**Comment by tannergooding** [comment]
We should probably go with @benaadams proposal for the ordering of the SSE/SSE2 intrinsics. That is, `CompareScalarOrderedXxx`.

The reasoning is that for the `FloatComparisonMode` enum, we have two methods that take it `Compare` and `CompareScalar`. The enum then has values like `OrderedXxx` and `UnorderedXxx` (with Signalling and NonSignalling suffixes).

I ran this by @terrajobst and @GrabYourPitchforks offline and they seems in favor since it would make us more consistent overall.

**Comment by tannergooding** [comment]
Resolved with https://github.com/dotnet/coreclr/pull/23893

**Comment by tannergooding** [comment]
Resolved with https://github.com/dotnet/coreclr/pull/23893
