### ISSUE TITLE
System.IO.Compression.ZipArchive reads entire input stream before failing when non-Zip specified

### ISSUE THREAD

**Issue by riverar** [dotnet/corefx#34892]
Consider this example with a large [sample cabinet file](http://go.microsoft.com/fwlink/p/?LinkID=74689):
```cs
static void Main(string[] args)
{
    using (var z = new ZipArchive(File.OpenRead(@"sample.cab")))
    {
    }
}
```

ZipArchive does not support Microsoft Cabinet files, so I expected a quick check of the magic `MSCF (4D 53 43 46)` would result in failure. Instead, ZipArchive consumes the entire input stream -- this could be a long time and prove to be costly on Azure Blob Storage-backed streams. The local file header signature is defined in the [ZIP file format specification](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) as 4 bytes: ```04 03 4b 50``` .

Eventually, ZipArchive will throw:
```
System.IO.InvalidDataException: 'End of Central Directory record could not be found.'
```

**Comment by GSPP** [comment]
I wonder what the Zip API actually does with all of that data that it reads. Is it trying to skip over leading garbage? It should not do that at all.

**Comment by Wraith2** [comment]
The header is at the front but the central directory is at the end, and while there is a magic number in the header it isn't required, see [Wikipedia zip file format page](https://en.wikipedia.org/wiki/Zip_(file_format)#End_of_central_directory_record_(EOCD)).

**Comment by GSPP** [comment]
It seems that a Zip file must always end with the `End of central directory record (EOCD)` which is of fixed size. It should never be necessary so scan through the data stream to find this record. I wonder how the current scanning code deals with the situation that uncompressed stored data might store data that looks like an EOCD. I guess only the last found EOCD would be used.

**Comment by dbarkwell** [comment]
According to the [Zip file format specification](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) a Zip file must contain an "end of central directory record" but only contains a "local file header" if a file exists. A Zip file with an "end of central directory record" and no "local file header" is considered an empty Zip file. 

The "end of central directory record" ends with a variable length comment field. ZipArchive reads backwards trying to find the "end of central directory record" signature and bypass the comment field. Since the cab file doesn't contain the signature, it reads the entire file and throws the exception when it's not found.

**Comment by riverar** [comment]
In the cases:
* where there are no files (a valid zip), the file should start with the "end of central dir signature" (`0x06054b50`)
* where there are files, the file should start with a "local file header signature" (`0x04034b50`)

A 4-byte check at the start would save a lot of trouble... but it comes at a cost (I/O and compatibility). For the latter, consider the case:

```
using (var z = new ZipArchive(File.OpenRead(@"sample.exe"))) { ... }
```

An executable containing an embedded zip resource would not throw here. ZipArchive would scan around and probably land on the embedded resource. (It may also fail, depends on the executable.) If ZipArchive behavior was changed to look at the first 4 bytes, we'd needlessly break this scenario.

Maybe the introduction of a `pkwareConformance` flag to silo the new signature check would help? Just brainstorming at 5AM. (e.g. `new ZipArchive("sample.cab", pkwareConformance: strict) { ... }`)
