### ISSUE TITLE
Microsoft.XmlSerializer.Generator v2.0.0 not working

### ISSUE THREAD

**Issue by syedabidali** [dotnet/corefx#34899]
why it picking up all the references, please suggest how can i resolve this for now , i removed the reference from dotnet CLI and configure it on Post Build event in VS 2017 but this run one after post built code , does removing the generated serializer.cs file.

![image](https://user-images.githubusercontent.com/14038836/51842823-9284ed00-2333-11e9-91eb-f67d69206c9b.png)
![image](https://user-images.githubusercontent.com/14038836/51842838-987ace00-2333-11e9-8c05-40cc4bc8c13e.png)

**Comment by yujayee** [comment]
Hello @syedabidali thank you for reporting the issue but I don't quite understand your problem. How are you using Microsoft.XmlSerializer.Generator in your project? What did you configure as a post build event?

**Comment by syedabidali** [comment]
Hi,
please see the below snapshot 
![image](https://user-images.githubusercontent.com/14038836/51883559-48d4ea80-23a5-11e9-95e7-d9c77062f604.png)
my project targets both net47 and netcoreapp2.2 , Microsoft.XmlSerializer.Generator include large no.of references which i mentioned in my previous  does it failing to run , so i did use this command in postbuildevent dotnet Microsoft.XmlSerializer.Generator &quot;$(IntermediateOutputPath)$(AssemblyName)$(TargetExt)&quot; --force --quiet but problem is this command run first in postbuild after that again Microsoft.XmlSerializer.Generator run again with all references and its failed thus causing delete the XmlSerializer.cs file that previously generated from postbuildevent command.

**Comment by yujayee** [comment]
@syedabidali Could you help me confirm if I understand your problem correctly?
First, Microsoft.XmlSerializer.Generator fails and throws a 'file name or extension too long' error (if so, could you help me confirm how long is your command?). 
Then you tried to manually run the command without "--reference" part before head. But the generated serializer got deleted after project rebuild.

**Comment by Lxiamail** [comment]
Hope https://github.com/dotnet/corefx/pull/36085 has fixed the problem.
