### ISSUE TITLE
Unix process start - missing user groups

### ISSUE THREAD

**Issue by SoerenBusse** [dotnet/corefx#34909]
Hey there,

I've written a daemon which runs as root and starts some gui applications on a users desktop. For this I used the ProcessStartInfo.Username feature to start the subprocesses as a specific user. This sets the UID and the GID of the subprocess correctly. 

However the started process doesn't contain any additional groups which are assigned to this user. This is especially important when your machine is domain joined and you need to access files from the subprocess where only the additional group has access to. 

Have I missed something or is this not possible with the current code?

When looking at the source code the native code doesn't execute the `setgroups()` method to set the additional groups.
https://github.com/dotnet/corefx/blob/ea00d24e4caeb5b000ff716dd67315325877ca83/src/Native/Unix/System.Native/pal_process.c#L256

I think the best way to fix this would be to add a native call to the `getgrouplist`
http://man7.org/linux/man-pages/man3/getgrouplist.3.html
and return it in the GetUserAndGroupIds method
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs#L793
which then passes the groups to the native `ForkAndExecuteProcess` method

I would be very glad if this could be fixed soon, because it prevent the use of NetCore in our application.

**Edit:**
While experimenting with the process api I found out that a process started with a specific username set in ProcessInfo contains the group 0 (root) in it's process table:
```
Name:	bash
Umask:	0022
State:	S (sleeping)
Tgid:	8932
Ngid:	0
Pid:	8932
PPid:	8903
TracerPid:	0
Uid:	1001	1001	1001	1001
Gid:	1001	1001	1001	1001
FDSize:	256
Groups:	0 
```
This allows any subprocess to write to files where the root group has write permissions to. I don't think that this is an expected side effect when using this method.

I think this might happen because of the missing setgroups so that it uses the group id of the parent process which is in my case root?

**Comment by danmosemsft** [comment]
@tmds thoughts? This seems like the kind of thing where you have more expertise.

**Comment by tmds** [comment]
It makes sense to do what is proposed: calll `setgroups` with the return value of `getgrouplist`.

> I think this might happen because of the missing setgroups so that it uses the group id of the parent process which is in my case root?

That is correct. The process groups and gid are independent. Without a call to `setgroups` we inherit the groups of the parent. In most cases this will be root because changing uid/gid/groups is privileged.

@danmosemsft you can assign this issue to me.

**Comment by SoerenBusse** [comment]
Thank you very much for the fast fix @tmds.

@danmosemsft
As far as I see all changes are approved and ready to merge. Are you able to provide a date when this will happen? We really like to use the nightly builds containing this fix to continue our development.

Or are there any net core builds available for each PullRequest request we could use?

**Comment by danmosemsft** [comment]
@soerenbusse I did not notice it was not merged. Now it is. Please let us know if you discover any issue. Thanks @tmds! this was bigger than we had all expected.

**Comment by MarcusWichelmann** [comment]
@danmosemsft I just tried the latest pre-release v3.0.0-preview3 from https://dotnet.microsoft.com/download/dotnet-core/3.0 and the fix doesn't seem to be included. Could you tell me please how your release process works and when I can expect to receive this fix?

**Comment by danmosemsft** [comment]
@MarcusWichelmann it just missed preview 3. There will be a preview 4 in not too long. Or you can use head: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md
```
c:\git\corefx\src>git tag | find /i "v3.0.0-preview3"
v3.0.0-preview3.19128.7

c:\git\corefx\src>git rev-list v3.0.0-preview3.19128.7 | find /i "b10e8d6"

c:\git\corefx\src>git rev-list master | find /i "b10e8d6"
b10e8d67b260e26f2e47750cf96669e6f48e774d

c:\git\corefx\src>git tag | find /i "preview3"
v2.2.0-preview3
v2.2.0-preview3-dependencies
v3.0.0-preview3.19128.7
```
