### ISSUE TITLE
Consider moving several HWIntrinsic instance methods to be extension methods

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#34902]
As per https://github.com/dotnet/coreclr/issues/22235#issuecomment-457988077, moving several of the hardware intrinsic "helper" methods to be instance methods has caused a regression in certain code hot-paths due to additional locals being created in order to pass the `this` parameter.

We should look at making these extension methods instead, so that users still have the "nice" calling syntax but so that the code can still remain performant to call.

**Comment by tannergooding** [comment]
The issue specifically referred to the various `As` methods, but it likely applies to the other instance methods as well. These include:
* `GetElement`
* `WithElement`
* `GetLower`
* `WithLower`
* `GetUpper`
* `WithUpper`
* `ToScalar`
* `ToVectorXXX`
* `ToVectorXXXUnsafe`

At least in the case of `ToScalar` and `ToVectorXXXUnsafe`, they are methods that, like `As`, are meant to provide zero-cost conversions in some scenarios and which do not have workarounds.

**Comment by tannergooding** [comment]
CC. @GrabYourPitchforks, @terrajobst

**Comment by fiigii** [comment]
> but it likely applies to the other instance methods as well. These include:

And `Equals`.

**Comment by tannergooding** [comment]
`Equals` has to be an instance method (as it is satisfying an interface/override).

We might be able to expose an explicit static method if that is believed to be helpful (and have the instance method just call it), but I'm unsure how useful that actually is in practice (especially with the other generally trivial workarounds that are available).

**Comment by fiigii** [comment]
We have two `Equals` APIs. Can the non-override version be static methods?

**Comment by benaadams** [comment]
The non-override is needed for the `IEquatable` interface `Vector128<T> : IEquatable<Vector128<T>>`

**Comment by tannergooding** [comment]
> Can the non-override version be static methods?

No, it is satisfying the `IEquatable<>` interface. The best we could do is have them call an equivalent static non-instance method (which would be exposed, like the extension methods, in the `Vector128.cs`).

However, given the implementation doesn't require runtime support (it just calls existing intrinsics), users have a valid workaround on this one. I would also expect that most users will, in practice, be calling the actual intrinsics and/or operating on the mask returned (rather than a `bool` result), so it likely isn't perf critical.

I will bring it up in the API review session in any case.

**Comment by fiigii** [comment]
Ah, thanks for explaining. 

> I will bring it up in the API review session in any case.

When is the next API review session? I suggest reviewing this issue as soon as possible since it requires JIT changes as well.

**Comment by tannergooding** [comment]
> When is the next API review session?

Tomorrow (it happens almost every Tuesday).

> I suggest reviewing this issue as soon as possible since it requires JIT changes as well.

The changes, overall, are rather trivial (we basically just have to update a couple of lines in the metadata table and indicate they are no longer instance methods). More importantly is ensuring that we get the public surface area fixed before they ship; as it is not as easy to fix afterwards 😄

**Comment by fiigii** [comment]
cc @hanblee @yweijiang
