### ISSUE TITLE
Duplication of corefx assemblies between the in-box shared frameworks: NETCore.App, WindowsDesktop.App, and AspNetCore.App

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#34906]
We currently have overlap between the 3 in-box shared frameworks. There are three problems as a result of this:

1. AspNetCore and WindowsDesktop contain the same assemblies. This might create problems later for conflict resolution at runtime and/or by the SDK. Both AspNetCore.App and WindowsDesktop.App include these in their **runtime** packs.

	- System.Security.Cryptography.Pkcs.dll
	- System.Security.Cryptography.Xml.dll
	- System.Security.Permissions.dll
	
2. AspNetCore and WindowsDesktop ship references for assemblies found in Microsoft.NETCore.App at runtime. This could be a problem if we somehow end up with a mismatch between reference assemblies and runtime. Some of this appears to be a deliberate due to suppressing ref assemblies in corefx by setting `IsNetCoreAppRef=false`. As a result, both AspNetCore.App and WindowsDesktop.App include these in their **targeting** packs.

	- Microsoft.Win32.Registry.dll
	- System.Security.AccessControl.dll
	- System.Security.Cryptography.Cng.dll
	- System.Security.Cryptography.Pkcs.dll
	- System.Security.Cryptography.Xml.dll
	- System.Security.Permissions.dll
	- System.Security.Principal.Windows.dll

3. Disk-space inefficiency. We're duplicating these assemblies in several places -- targeting packs, shared frameworks, and runtime packs.

cc @ericstj @pakrym @DustinCampbell @davidfowl @nguerrera @dsplaisted

**Comment by natemcmaster** [comment]
Here are 2 specific, concrete things I am concerned about. 

* It appears `IsNetCoreAppRef=false` was a deliberate attempt to hide runtime API, such as Microsoft.Win32.Registry, from apps targeting netcoreapp unless they opt-in via package reference. I'm not sure why this was done, but I'd like to understand why. Does including this ref assembly in the WindowsDesktop and AspNetCore targeting packs thwart the whole point of `IsNetCoreAppRef=false`?
* Same assembly, same version, different contents. Seems like a recipe for non-deterministic assembly loading...and as a result, unpredictable behavior. For a specific example, consider 3.0 Preview 2 and System.Security.Cryptography.Xml.dll. Both WindowsDesktop and AspNetCore include System.Security.Cryptography.Xml.dll, Version = 4.0.2.0, File version = 4.7.19.7311. But these are not the same file. The version in shared/Microsoft.WindowsDesktop.App/3.0.0-preview-27325-3 is 158 KB, and the one in shared/Microsoft.AspNetCore.App/3.0.0-preview-19075-0444 is 415 KB. Which one is "right"? If I create an app that references all 3 shared frameworks, which System.Security.Cryptography.Xml.dll will corehost load? When I publish self-contained, which version of the assembly is in my output folder? And could the version that wins be different based on factors like the order in which code executes or things are listed in a .csproj file?

> Perhaps you can propose to add individual libraries to the shared framework along with justification and folks can review those case-by-case?

My proposal would be put the overlapping assemblies in the base shared framework. I don't want to split this out into individual cases yet because I think we need to decide, as a platform, whether this overlapping situation is okay or not.

**Comment by dsplaisted** [comment]
@terrajobst @DustinCampbell this seems related to the conversation about what becomes of the Microsoft.Windows.Compatibility NuGet package and the APIs that are shared between WPF and Windows Forms in the WindowsDesktop shared framework.

**Comment by nguerrera** [comment]
Guessing the files that are same version but different are due to one being crossgened and the other not, based on size. Is WindowsDesktop not being crossgened yet? 

Also even if both were crossgened, I don't know that crossgen is fully deterministic. And I think signing isn't (includes a timestamp IIRC).

**Comment by ericstj** [comment]
IsNetCoreAppRef=false was typically used for things in the implementation closure that were not in the reference closure and that we didn't want to make available by default in references for a couple reasons. For example, the API was not cross-platform and would throw (Cng, Windows.Principal, Registry), or the api was legacy and should be avoided (CAS).  You could choose to exclude from the ASPNet references for the same reason, we do for some (though unfortunately not all) in WindowsDesktop.  X-plat is not a concern for WindowsDesktop.  Its for these various reasons that I think breaking out individual requests might be helpful.  For instance I'm unaware of the reasoning behind excluding crypto.xml and pkcs: I think they may have originally been windows only, but are now cross-plat.  System.Security.Permissions on the other hand should not be exposed nor even used at all from these shared frameworks (unless we decide to represent the WindowsCompat pack). 

Size difference is due to cross-gen-ing.  FileVersions will differ if the build is different.   The contract is that higher version wins.

I believe load preference is defined and deterministic in case of equal versions in that closer shared framework wins.  Not sure what the behavior will be if we allow more than one shared "peer" framework. @vitek-karas or @steveharter might be able to comment.  I'm not sure if this is even something folks are enabling.  I think we need to have defined behavior here regardless of wether or not we choose to model the product as never having conflicts.

I really don't think a general rule can be applied: just because ASP.NET and WinForms/WPF decide to use an assembly doesn't mean we put it in the shared framework.

**Comment by vitek-karas** [comment]
Re resolution algorithm:
* Higher assembly version wins.
* If equal higher file version wins.
* If equal the one from higher level FX/app will win (so app wins over FX and ASP.NET wins over NetCore and so on)
* Peer frameworks have stable but undefined ordering (I think it's based on the order in `runtimeconfig`) - nobody should rely on this.

So if the same assembly exists in 2 peer frameworks and it has the same versions the host will effectively pick one at random. The assumption is that exact same file version means same content.

Note that currently there's a bug in the FX ordering algorithm in the host: dotnet/core-setup#4947 which may cause the rule above that higher level FX wins to not work. The plan is to definitely fix this for 3.0.

**Comment by ericstj** [comment]
> The assumption is that exact same file version means same content.

Yes, we've been comfortable with that assumption since the feature was created.

**Comment by natemcmaster** [comment]
> Size difference is due to cross-gen-ing. FileVersions will differ if the build is different. The contract is that higher version wins.

Ok, where is the issue tracker for Microsoft.WindowsDesktop.App? Seems like they should crossgen, right? If there is a reason WindowsDesktop does not crossgen, then it could be a problem if AspNetCore is referenced and it's crossgen-ed versions are loaded.

I did some further API analysis on AspNetCore. Here is how we use the assemblies listed above:

## API surface
AspNetCore exposes Microsoft.Win32.Registry in 4 public API, all of them in Microsoft.AspNetCore.DataProtection (cc @blowdart /@muratg). This means we'll have to ship the Microsoft.Win32.Registry.dll ref assembly in the aspnetcore targeting pack, or take a breaking change to move those API out of the shared framework. We could hide the ref assemblies from our targeting pack because their usage is internal only.

## API Usage
AspNetCore can't remove System.Security.Cryptography.Xml, Crypto.Pkcs, or Security.Permissions from the AspNetCore runtime. They are used by the follow assemblies

Assembly   |   Directly references
:--|:--
Microsoft.AspNetCore.DataProtection    |  System.Security.Cryptography.Xml
Microsoft.Extensions.Configuration.Xml |  System.Security.Cryptography.Xml
System.Security.Cryptography.Xml       |  System.Security.Permissions
System.Security.Cryptography.Xml       |  System.Security.Cryptography.Pkcs

Note: aspnet only directly references System.Security.Cryptography.Xml. The other two assemblies are transitive dependencies.

## Proposals
Given this, I have two proposals:

1. AspNetCore hides System.Security.*.dll files from the targeting pack. Microsoft.Win32.Registry stays in the targeting pack. We can add tests to ensure we don't add new APIs that expose these.
2. We investigate moving System.Security.Cryptography.Xml into the NETCore.App shared framework. If this is not reasonable, then it stays in the AspNetCore.App and WindowsDesktop.App frameworks and we'll deal with potential consequences.

**Comment by natemcmaster** [comment]
@ericstj I took your suggestion. I have opened a couple issues for some specific pieces of this. See https://github.com/dotnet/corefx/issues/35026 and https://github.com/aspnet/AspNetCore/issues/7190

**Comment by dreddy-work** [comment]
@Zsd4yr is working on cross-gen for winforms.  System.Drawing.dll is the common file between Winforms and CoreFx. We made winforms file version higher than coreFx and Planning to add appcompat for this assembly between desktop and core-winforms  and also between core-winforms and corefx.

**Comment by joshfree** [comment]
@natemcmaster @ericstj could you give an update on what's remaining here for 3.0?

**Comment by pakrym** [comment]
cc @anurse

**Comment by natemcmaster** [comment]
It appears there is no plan in 3.0 to address this, and no one seems overly concerned about the drawbacks I mentioned in the original issue description.

**Comment by anurse** [comment]
I think that's a reasonable assessment. It's a problem that is somewhat inevitable with composable framework references, and it's not really a new problem. I could reference two different versions of a package today and some kind of conflict resolution ends up selecting one of them to run against. The same is true here.

**Comment by davidfowl** [comment]
cc https://github.com/dotnet/corefx/pull/38207
