### ISSUE TITLE
AnonymousPipeClientStream.ReadAsync only returns zero in Windows.

### ISSUE THREAD

**Issue by TheBuzzSaw** [dotnet/corefx#34910]
This is my first contribution. I hope I'm in the right place. Feedback please. :)

My parent process has an `AnonymousPipeServerStream` with `PipeDirection.Out`. It spawns a child process, which creates an `AnonymousPipeClientStream` with `PipeDirection.In`. If the parent process calls `Dispose` on its stream, the child process observes this, and `ReadAsync` returns `0`. This is desired behavior, but it only works in Windows. In macOS and Linux, that call to `ReadAsync` _never returns_.

I am unable to find any documentation that promises that closing an anonymous pipe results in the listening side returning `0`. So, this technically may not be a bug, but it is inconsistent.

I wrote a program demonstrating the problem. It was a little long, so I put it into a gist: https://gist.github.com/TheBuzzSaw/69c16a9dad2b27857b0070008ac9fb0d

I also wrote a program demonstrating the reverse: the parent process has `PipeDirection.In`, and the child process has `PipeDirection.Out`. In this scenario, `ReadAsync` _does_ return `0` in all operating systems in the parent process.

**Comment by stephentoub** [comment]
> I wrote a program demonstrating the problem

Your server stream is being created as inheritable. Is that on purpose?

**Comment by stephentoub** [comment]
> Am I using that wrong?

No, you're correct.

I think that's also the bug (not yours).  The client handle is being created as inheritable, but so is the server handle.  As such, even though the server process is closing its file descriptor, the client still has one for the same file and is thus keeping it open.  If you change your repro to communicate the server handle to the child process as well and then P/Invoke to close on it, you'll see the repro pass.

**Comment by TheBuzzSaw** [comment]
I actually committed great evils to accomplish this in all managed code.

    static string GetHandle(SafePipeHandle handle)
    {
        var fieldInfo = typeof(SafePipeHandle).GetField(
            "handle",
            BindingFlags.NonPublic | BindingFlags.Instance);
        return fieldInfo.GetValue(handle).ToString();
    }

With this method, I was able to send the server handle over to the client. From there, it was actually not too hard to close it.

    var handle = new SafePipeHandle(
        new IntPtr(int.Parse(serverHandle)), true);
    handle.Dispose();

**Comment by stephentoub** [comment]
> I committed great evils to accomplish this in all managed code.

You don't actually need reflection.  You can just do:
```C#
return pipeStream.SafePipeHandle.DangerousGetHandle().ToString();
```

**Comment by TheBuzzSaw** [comment]
Oh! I overlooked that method. Thanx! That's much better.

**Comment by TheBuzzSaw** [comment]
Now that I understand the underlying issue a bit better, I'm wondering what the supposed fix is. It seems non-trivial to address in an automated way. Is there a way to prevent the server handle from being inherited in the first place (while still letting the client handle through)? The work-around I've implemented works, but I suspect it'll be there longer than I want it to.

**Comment by stephentoub** [comment]
The actual fix will be trivial; the question will be whether it's an acceptable change in behavior (I think it is).

**Comment by TheBuzzSaw** [comment]
Oh! Shows how much I know.

> the question will be whether it's an acceptable change in behavior

Considering the behavior is different across operating systems, one could argue that the change is necessary one way or another.

Thanks!

**Comment by stephentoub** [comment]
> Oh! Shows how much I know.

Nah, it's complicated stuff, and it's always difficult judging the complexity of a particular fix when unfamiliar with the codebase.
