### ISSUE TITLE
Adding more IntPtr arithmetic

### ISSUE THREAD

**Issue by Akaion** [dotnet/corefx#34925]
IntPtr's can currently only be added or subtracted onto by using an int like so

```csharp
var testPointer = new IntPtr(0xFFF);

testPointer = testPointer + 256;
```

It would be a welcome improvement if this was expanded to include longs and other IntPtr's.

Currently, the work around for this is to cast the IntPtr(s) into a long, perform the arithmetic and then cast the new value back into an IntPtr like so

```csharp
var testPointer = new IntPtr(0xFFF);

var testLong = 0xFFFFFFFFFFFL;

testPointer = (IntPtr) ((long) testPointer + testLong);
```

or

```csharp
var testPointer1 = new IntPtr(0xFFF);

var testPointer2 = new IntPtr(0xFFFFF);

var testPointer3 = (IntPtr) ((long) testPointer1 + (long) testPointer2);
```

Whilst this works, it would be nice if this was integrated directly into the IntPtr operators.

**Comment by stephentoub** [comment]
Thanks.  Dup of https://github.com/dotnet/corefx/issues/32775.
