### ISSUE TITLE
JsonDocument.Empty

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefx#34935]
Consider adding a readonly property/field with an empty JsonDocument, or a friendly way to create an empty document.

Currently you need to do this - `JsonDocument.Parse(string.Empty)` - https://github.com/aspnet/AspNetCore/pull/7105/files#diff-4561b022ab7f492d2dc25af071e9c74eR36

@bartonjs @ahsonkhan

**Comment by ahsonkhan** [comment]
@Anipik, @danmosemsft - incorrect label added

**Comment by ahsonkhan** [comment]
`JsonDocument` is a read-only representation of JSON. I am not sure if empty JSON makes sense, and given that's considered invalid JSON, we actually throw `JsonReaderException` if someone passes an empty document.

https://github.com/dotnet/corefx/blob/5197c8dc78adcb130a08944724f1b49c3765a4b1/src/System.Text.Json/tests/JsonDocumentTests.cs#L1204

What is the utility of adding such a property? Unlike `JObject`, I don't see a scenario where you want to get a default/empty instance of `JsonDocument` and pass that around.

**Comment by JamesNK** [comment]
Yeah, the idea of an empty JsonDocument probably doesn't make sense.

I think the indent of the code I linked to is really `JsonDocument.Parse("{}")`

**Comment by ahsonkhan** [comment]
> Yeah, the idea of an empty JsonDocument probably doesn't make sense.

In that case, feel free to close the issue.
