### ISSUE TITLE
where is the latest System.Memory nuget

### ISSUE THREAD

**Issue by JanEggers** [dotnet/corefx#34955]
Hi there,

I would like to try out SequenceReader but I cant find a nuget with it.

the latest version of System.Memory I found (4.6.0-preview3-26501-04 is 6 month old)
https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Memory

and by the way I dont understand why the assembly is  System.Memory and the namespace is System.Buffers.

**Comment by ahsonkhan** [comment]
The API surface for the portable System.Memory assembly was frozen after .NET Core 2.1. APIs like `SequenceReader` are available in-box in .NET Core 3.0 so you don't need to reference the `System.Memory` package explicitly to access it (on the newest TFM).

We no longer ship a standalone System.Memory package.

cc @jkotas, @JeremyKuhne, @ericstj

**Comment by JanEggers** [comment]
Im working on a library. I cannot lock myself into netcore (still have too many netfx users)? I would like to target some form of netstandard like 2.1 (that should have span support I thought) or is it the ref struct thingy that needs core 3.0 runtime?

**Comment by ahsonkhan** [comment]
Span will be part of netstandard2.1: https://github.com/dotnet/standard/pull/909

> is it the ref struct thingy that needs core 3.0 runtime?

No, ref structs don't need the 3.0 runtime. They need .NET Core 2.1 and higher (which is why we shipped a portable System.Memory and an in-box one).

cc @terrajobst

**Comment by JanEggers** [comment]
thx for clarifing, I think I wont use the new features then... :(
