### ISSUE TITLE
Inaccurate comment in HttpHandlerDefaults

### ISSUE THREAD

**Issue by erikness** [dotnet/corefx#34966]
# Problem

I suspect this comment is inaccurate and out-of-date:
https://github.com/dotnet/corefx/blob/dfd25d13a9d0f5f86d3964eb5bf6b33b7b22a3cc/src/Common/src/System/Net/Http/HttpHandlerDefaults.cs#L10

I suspect it's out of date because UnixHttpHandler is now CurlHttpHandler and because the commit was made 3 years ago. I suspect that it's inaccurate because the settings are used selectively and because they're also used by both SocketsHttpHandler and HttpWebRequest (I'm not sure if the corresponding WebRequestHandler still exists).

Let's look at one of these settings, DefaultPooledConnectionIdleTimeout. It's only used in one place in corefx: [to set _pooledConnectionIdleTimeout in HttpConnectionSettings](https://github.com/dotnet/corefx/search?q=DefaultPooledConnectionIdleTimeout&unscoped_q=DefaultPooledConnectionIdleTimeout), which is a class in the SocketsHttpHandler directory. That field is only referenced [elsewhere in SocketsHttpHandler](https://github.com/dotnet/corefx/search?q=_pooledConnectionIdleTimeout&unscoped_q=_pooledConnectionIdleTimeout). In fact, [WinHTTP doesn't even allow you to set this](https://github.com/dotnet/corefx/issues/24850#issuecomment-339167964).

I searched for the rest of the fields in corefx as well. SocketsHttpHandler, CurlHttpHandler, WinHttpHandler, and HttpWebRequest all use some of these.

# Action

Change this comment to reflect how it's actually being used. These defaults are wired into the 4 handler above whenever those handlers:
1) have the relevant feature 
2) have a way to configure that (i.e. WinHTTP has an idle connection limit, but you can't configure it)
3) .NET doesn't decide to override that setting (see how [CurlHttpHandler sets its own connection timeout](https://github.com/dotnet/corefx/blob/aabdfb735a3e087446255a144ef33ce22ee1771a/src/System.Net.Http/src/System/Net/Http/CurlHandler/CurlHandler.cs#L144) and [WinHttpHandler sets its own analog of DefaultUseCookies](https://github.com/dotnet/corefx/blob/d0997060a80f41d4c03c0f8cc2b8ce5ac40ec941/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs#L69)).

This seems like a huge nitpick (and it is!). The reason I'm here is that SocketsHttpHandler doesn't have the default values for some of its properties listed in the MSDN docs. I was about to open a docs issue, referencing this source file, but it's not clear from this comment what HttpHandlerDefaults is meant for. I wanted to clarify what you all intended here first, and get it changed if necessary.

**Comment by stephentoub** [comment]
Tweaked the comment. Thanks.
