### ISSUE TITLE
Clarify ungrammatical comment in 'FixedBufferExtensions.cs'

### ISSUE THREAD

**Issue by glenn-slayden** [dotnet/corefx#34976]
The following is not English, as far as I can tell:

https://github.com/dotnet/corefx/blob/9e074e4a3f3626fa953f36ab79e3cd3e6db1c9de/src/Common/src/System/Memory/FixedBufferExtensions.cs#L33

**Comment by danmosemsft** [comment]
Want to offer a fix?

**Comment by colathro** [comment]
This sounds fine to me. The span's actual length is different from the logical length that's interpreted in the method.

`span['a', 'b', 'c', 'd', '\0', 'f', 'g'] != ['a', 'b', 'c', 'd', 'f', 'g'] `

**Comment by Zenexer** [comment]
@glenn-slayden As a native speaker, I understand what’s being said here. Neither of your proposals match my understanding. I understand it as:

> The span’s logical length is measured from the start to the first null, if present; otherwise, it matches the real length.

The wording hits the ear wrong, but it’s clear enough what’s meant.
