### ISSUE TITLE
FileStream.Seek & FileStream.Position does not check if current position is same as desired position

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#34992]
_From @rahku on October 23, 2018 22:15_

FileStream.Seek and FileStream.Position should check if the current position is same as desired position then bail out early. This avoids having to disregard buffers when using buffered IO.

_Copied from original issue: dotnet/coreclr#20556_

**Comment by danmosemsft** [comment]
_From @jkotas on October 24, 2018 2:53_

cc @JeremyKuhne

**Comment by danmosemsft** [comment]
_From @rahku on October 24, 2018 19:36_

or better yet check if desired position is in buffer and then adjust pointers accordingly

**Comment by danmosemsft** [comment]
_From @benaadams on October 24, 2018 20:40_

Probably shouldn't call `SetFilePointer` either "Windows Server Performance Team Blog: [Designing Applications for High Performance – Part III](https://blogs.technet.microsoft.com/winserverperformance/2008/06/25/designing-applications-for-high-performance-part-iii-2/)" (June 25, 2008)

> The old DOS SetFilePointer API is an anachronism.  One should specify the file offset in the overlapped structure even for synchronous I/O.

**Comment by danmosemsft** [comment]
_From @JeremyKuhne on October 24, 2018 21:1_

@benaadams Thanks for the link. 

We've got a lot of serious work to do with FileStream. An overhaul is on our wishlist.

cc: @stephentoub

**Comment by benaadams** [comment]
As a counter point `File.CopyToAsync` is very fast

**Comment by JeremyKuhne** [comment]
We can't really add this, but need to consider this problem with any overhaul we do. Ideally we get rid of position as a contained state entirely- as pointed out it is strongly encouraged to have APIs always take expected position.

**Comment by carlossanlop** [comment]
Triage: We will consider this scenario as described by Jeremy above. Closing since it's not actionable in the current state of FileStream.
