### ISSUE TITLE
Is it possible to force SSL client certificate reauthentication on every connection?

### ISSUE THREAD

**Issue by jgoyvaerts** [dotnet/corefx#34995]
I was wondering if it's possible to force clients connecting to a kestrel/IIS server to have to re-authenticate with a client certificate after closing the SSL connection.

Given the difference between an SSL connection and an SSL session, clients can reuse the same SSL connection, but when the SSL connection is closed (either by timeout, by sending a Connection: close from the server, or any other means to close an ssl connection) the client should NOT be able to do an abbreviated handshake based on a server session cache, but should negotiate a new SSL connection and thus re-authenticate with a client certificate.

**Things I've tried:**
- Clearing the s_cachedCreds in SslSessionsCache (serverside, using reflection), but still the client wasn't forced to reauthenticate with his client certificate
- Sending Connection: close http header. While this closes the current SSL connection, the client isn't forced to reauthenticate because of a cached SSL session, so an abbreviated handshake is used.

Is there any possibility to disable/change this behavior server-side?

**Comment by davidsh** [comment]
@Tratcher

**Comment by Tratcher** [comment]
This is likely a client behavior, what client are you using? E.g. browsers are prone to caching the user's cert selection and providing that cert again for future connections. I haven't seen anything the server can do about this.

**Comment by jgoyvaerts** [comment]
I'm using Chrome in all my tests. While chrome is definitely doing some caching, ultimately both parties have to agree to reuse a previous ssl handshake, so if the server says no, chrome should prompt the client for a new client certificate authentication.

Basically I'm looking for the way to say 'no' from the server. 

Some info:  https://security.stackexchange.com/a/40479

**Comment by Tratcher** [comment]
Do you have any logs or dumps that indicate it really is the same ssl session? From my experience chrome caches the cert selection above and beyond the ssl session and the only way to reset it is to close the browser.

**Comment by jgoyvaerts** [comment]
I can try to create logs/dumps sure.

The reason why I'm convinced it's the same ssl session is that the client certificate is a national identity card with the private key on it, and I can remove the card from the computer and still setup a connection

I would assume if chrome negotiated a new ssl session it would need the private key again?

**Comment by jgoyvaerts** [comment]
After tracing with wireshark, the first solution (Clearing the s_cachedCreds in SslSessionsCache) _**DOES**_ create a new SSL session, however, the user is not prompted to re-enter his pin code (if he removes the card, he _**IS**_ prompted to re-enter his card and re-enter his pin code). 

However, this caching of the pin code seems to happen on browser/OS level so I'm closing this issue since it's not a .net problem. (if someone has a clue how to prevent this, ping me!)

Thanks for the tip @Tratcher .
