### ISSUE TITLE
System.Net.Http.FunctionalTests flakiness in UWP run

### ISSUE THREAD

**Issue by caesar-chen** [dotnet/corefx#35002]
The UWP leg in CI has become really flaky with networking tests, e.g.
https://mc.dot.net/#/user/Dotnet-GitSync-Bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/c83f0503978d4187882fc97f541f070f6374d016/workItem/System.Net.Http.Functional.Tests

I have finished the investigation. This is caused by the `XUnitRunnerUAP` - it’s a small UAP app we use to run tests against, and this adds overhead to the test execution, eventually lead to test timeout.

## Steps I have verified:

1.	I’m not able to repro the UWP failures on my main dev box (it’s a powerful machine).
2.	I’m able to repro on my Azure VM – each time I run the entire `System.Net.Http.FunctionalTests` suite, I will get random failures all related to the loopback server timeout. Just like those tests in the link posted above.
3.	I disabled test parallel execution, and use a script to run the entire test suite in a loop – no failure.

I will submit a PR to disable `System.Net.Http.FunctionalTests` parallel execution on UAP run to workaround the random failures. ~~Eventually/Ideally we need to get rid of this `XUnitRunnerUAP`.~~ I'm not sure how to fix this issue in the long run.

**Comment by davidsh** [comment]
>Eventually/Ideally we need to get rid of this XUnitRunnerUAP.

I don't think we will ever be able to get rid of it.  It is the only UAP test runner that will actually use the real mechanism of how UWP apps work (i.e. UI window with app-container security).

@ViktorHofer

**Comment by caesar1995** [comment]
Hi Viktor, I'm not sure how to resolve this app runner issue, or, maybe we need to simplify our loopback server logic to fix the flakiness - it's hard to tell which side to blame without further investigation.

For now this flakiness is mitigated by disable parallelism, and we have other 3.0 pressing issues to work on. Maybe we can revisit this issue later, is that ok?

**Comment by ViktorHofer** [comment]
Sounds good. As said earlier, I don't think anything in the app can be changed to make it more reliable. Thanks for the fix, that should make CI more stable 👍

**Comment by davidsh** [comment]
The tests were changed to disable parallelism with PR #35004. At this point, the tests are stable and we don't need to track this issue.
