### ISSUE TITLE
SR.Format with format provider

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#35001]
_From @stephentoub on January 2, 2019 19:36_

We use SR.Format to format resource strings.  But there are a bunch of places where the formatting is done with a specific format provider, e.g. CultureInfo.InvariantCulture, and such places currently use string.Format because there is no SR.Format overload today that takes a format provider.

I suggest we should either add such overloads and switch all formatting of resource strings over to use SR.Format, or we should drop SR.Format and just use string.Format everywhere.

This applies to both coreclr and corefx.

cc: @tarekgh, @krwq 

_Copied from original issue: dotnet/coreclr#21762_

**Comment by danmosemsft** [comment]
_From @tarekgh on January 2, 2019 19:47_

> I suggest we should either add such overloads and switch all formatting of resource strings over to use SR.Format, or we should drop SR.Format and just use string.Format everywhere.

I recall we had some logic inside SR.Format for .Net Native when we decide to drop the resources (and use the resource keys only) for the size sake. so we should be careful if we decide to drop SR.Format to ensure we'll not broke anything. I would say adding the overload taking the provider would be better.

**Comment by tarekgh** [comment]
@danmosemsft SR is internal thing and we are not exposing it. I don't this this issue need to be marked as api-need-work

**Comment by danmosemsft** [comment]
Yep.

**Comment by stephentoub** [comment]
This has been fixed.
