### ISSUE TITLE
Add static and runtime verification tools against existing tests

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#3501]
/cc: @stephentoub @vijaykota @pgavlin @davidsh 

We should augment our CI with static and runtime verification tools that can be enabled against our existing tests:

Windows:
- [ ] FXCop (edit: covered by https://github.com/dotnet/corefx/issues/14095)
- [ ] PREfast for Native code
- [ ] [AppVerifier](http://www.microsoft.com/en-us/download/details.aspx?id=20028)

Linux:
- [ ] [Valgrind](http://valgrind.org/)

This should already be part of normal pre-commit procedures for all teams. 
Could we make this an automated part of CI/Weekly testing?

**Comment by stephentoub** [comment]
cc: @nguerrera, @mmitche

**Comment by joshfree** [comment]
@steveharter could you take a look at this while you're working on CLANG debug switches?

**Comment by steveharter** [comment]
Enabling the CLANG switches is under review. This was problematic due to various linker errors caused by header files including definitions not implemented for various ifdefs. https://github.com/dotnet/coreclr/compare/master...steveharter:CMake

**Comment by steveharter** [comment]
For CMAKE sanitizers Will create at least these new issues:
1) enable cmake for coreclr (currently under review)
2) enable cmake for corefx (should be easy)
3) fix some issues to reduce noise in coreclr sanitizers error output (already started)
4) log new issues against existing bugs (to other people)
5) add to build system \ process in some form

**Comment by CIPop** [comment]
Tracking adding static analyzers with this issue as well.

**Comment by mellinoe** [comment]
@CIPop Of the things in the original issue, how much have we enabled now, and how much do we think still needs to be invested in? I know we have started running some build-time analyzers on the managed code, and we have at least done some offline (i.e. not build-time) analysis of the native code. Are there more things we should be adding to build-time validation?

**Comment by CIPop** [comment]
@mellinoe I just opened the issue observing that these tools were missing but I am not aware of any changes that have been made since. 
@steveharter might be able to answer your question.

I've converted this into a checkbox issue to better track progress.

**Comment by weshaggard** [comment]
I believe we have all the tools we want enabled now and some tools just part of our security builds so we should be covered.
