### ISSUE TITLE
CountdownEvent Cannot Be Reused Due To Wait Early Return

### ISSUE THREAD

**Issue by roken** [dotnet/corefx#35021]
There is a questionable performance optimization in CountdownEvent.Wait() such that if it sees the current count has reached zero it will avoid making the actual Wait call on the ManualResetEventSlim.

ref:  https://github.com/dotnet/corefx/blob/master/src/System.Threading/src/System/Threading/CountdownEvent.cs#L557

Imagine the following usecase, where a method (DoStuff) is called repeatedly from a single thread.  That thread spawns work on a variety of threads and waits for those threads to complete before returning.  Do not focus on the fact that Task.Run is used as the parallelization technique as that is just for illustration (and we could simply wait on all tasks completing if the TPL was actually being used).

```
public void DoStuff(T[] things)
{
    _countdownEvent.Reset(things.Length);
    for (int i = 0; i < things.Length; i++)
        ExecuteInParallel(things[i]);
    _countdownEvent.Wait();
}

private void ExecuteInParallel(T thing)
{
    // Handwave...  thing gets put on a thread for processing
    // and the CountdownEvent is signaled from that thread
    // when processing completes.
    Task.Run(() => /* stuff happens first */ _countdownEvent.Signal());
}
```

Reset() is not threadsafe, however on its face the belief is that if DoStuff is only ever called from a single thread, the Wait() call at the end of the method will guarantee that all Signal calls have been completed before Reset has an opportunity to execute again, thus guaranteeing thread safe access to the Reset call.

This is a lie.

Due to the optimization in Wait() linked to above, the following sequence can occur:

- Thread 0 calls DoStuff
- Thread 0 runs all the way through to the Wait() call; Wait() method is entered.
- While Wait is at the top of the method, the last background thread that needs to call Signal enters the Signal method.  Let's call this thread 1.
- Recap:  Thread 0 is at the start of Wait.  Thread 1 is at the start of Signal.
- Thread 1 executes the Decrement of _currentCount in Signal and reaches line 188 (https://github.com/dotnet/corefx/blob/master/src/System.Threading/src/System/Threading/CountdownEvent.cs#L188).  _currentCount is now zero, but the event has not yet been set.
- Thread 0 executes the "if not IsSet call Wait on the event, otherwise just walk right through."  Because _currentCount is zero, the method is able to simply return without touching the event.  (Line 557)
- Thread 0 reenters DoStuff, calling Reset() on the CountdownEvent.  This method competes, Reseting the event.
- Thread 1 continues execution of Signal(), reaching line 190 to set the event again!
- Now Thread 0 will bomb right through the method because the Wait will return even though the _currentCount will not be zero.

This problem is due to a violation of Reset thread safety (Reset is executing while other methods on the CountdownEvent are executing).  However, short of calling Wait on the exposed WaitHandle itself, I cannot see a way to properly utilize CountdownEvent with the synchronization semantics it exposes.  I can use reflection to reach in and Wait on the ManualResetEventSlim directly (more efficient than using the exposed WaitHandle), but that's obviously extremely gross, and doesn't address the open pitfall of attempting to reuse the CountdownEvent.

The proposed change would be to remove the IsSet check in Wait and always call Wait on the ManualResetEventSlim.  This would make guarantees that Wait _actually_ waits for all signalling to complete before returning.

**Comment by stephentoub** [comment]
Thanks.  Your analysis looks correct.  It's even alluded to in the comment inside IsSet:
https://github.com/dotnet/corefx/blob/0d41c895ff6e3094e1e8105a9bb6b4cf3d985bd7/src/System.Threading/src/System/Threading/CountdownEvent.cs#L102-L106
and while Reset is explicitly not thread-safe, I agree the pattern you've described is a typical use case, and the expectation is that Wait will in fact guarantee in such a pattern that's its safe to use Reset... otherwise, there's not really a good case where Reset could be used.
