### ISSUE TITLE
Consider moving System.Security.Cryptography.Xml into NETCoreApp

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#35026]
Follow-up to https://github.com/dotnet/corefx/issues/34906

Both WindowsDesktop.App and AspNetCore.App 3.0 shared frameworks contain System.Security.Cryptography.Xml (and its dependencies). I think we should consider putting this in the NETCore.App shared framework. Here is a pros/cons list. Feel free to add to it.

Benefits:
* Removes duplication between peer shared frameworks
* Avoids potential conflicts between peer shared frameworks (see https://github.com/dotnet/corefx/issues/34906#issuecomment-458459882). Although we estimate problems should be rare, we can't rule out what might happen due to some randomness in assembly loading.
* Modest reduction in size of a .NET Core installation on Windows (only by about 1.4 MB)
* Small simplification to servicing - there is only one location on disk we have to service, not two.

Drawbacks:
* It makes NETCore.App larger
* Potential cross plat implications. I'm not super familiar with the history, but IIRC Crypto.Xml was originally Windows-only. It may still have some API which are not fully cross-plat
* Other concerns? (I'm not the subject matter expert on these APIs....please chime in if you see other drawbacks)

cc @ericstj @bartonjs

**Comment by ericstj** [comment]
@bartonjs @GrabYourPitchforks what do you think about adding Crytpo.Xml to the shared framework?

**Comment by ericstj** [comment]
One thing to note is that bringing this in will bring System.Security.Permissions due to Crypto.Xml's usage of System.Security.Policy.Evidence.  If we didn't want to do that we could push `Evidence` and `EvidenceBase` types down to a different assembly (as we've already done for some other members in System.Security.Permissions).

Bringing in the implementation would bring in System.Security.Cryptography.Pkcs due to a single type: X509IssuerSerial.  Perhaps that could be pushed down to Crypto.Primitives.

**Comment by bartonjs** [comment]
I don't have any particular reasons to oppose putting it into the standard shared framework (other than generally believing that no one should use it), with whatever surgery seems to make sense.

Moving `X509IssuerSerial` into Primitives seems fine, for example.

**Comment by natemcmaster** [comment]
This is definitely a tangent, but couldn't resist asking...

> other than generally believing that no one should use it

Interesting...can you elaborate? A high number of aspnetcore apps end up using the encrypted xml feature by default. It's how we implemented the dataprotection APIs. Are there upcoming changes or problems we should be aware of?

**Comment by bartonjs** [comment]
> Are there upcoming changes

No, System.Security.Cryptography.Xml is in a state of "as dead as can be while still being technically supported".  Further, the W3C shut down the XML Security WG in 2016.

> problems we should be aware of?

Encrypted XML is... nearly okay. The API is pretty clunky, but it does what it does.  It's hard to use it stupidly, but it does have enough rope that you _can_ "hang yourself" with it.  It is the easiest (per one paper I read) format of data encryption to crack (mainly requiring active brute force scenarios).

Signed XML is much less okay.  I'm part of the security camp that believes that it's not really redeemable.  There are plenty of talks on the 'net explaining why this one is bad.

In both cases, the CMS (binary) version is better.   EncryptedXml => EnvelopedCms.  SignedXml => SignedCms.  The W3C "friendliness" additions on top of PKCS#7 are where most of the problems came in.

**Comment by natemcmaster** [comment]
Thanks for explaining, @bartonjs.

**Comment by danmosemsft** [comment]
@natemcmaster if we don't encourage use, per @bartonjs, I'm inclined to say the disadvantages outweigh the benefits. Once it's in the shared framework we presumably can never remove it, which is not a good place for something we would like to not take forward more than we have to. Do you agree? If so, please close.

**Comment by natemcmaster** [comment]
@danmosemsft i actually think this API should be in netcoreapp, but can understand why not everyone would agree. The API is already in a shared framework (actually, two) -- just not in one that your team services directly, which is part of my concern.

**Comment by danmosemsft** [comment]
@ericstj thoughts?

**Comment by ericstj** [comment]
What can you do to get off of the dependency @natemcmaster : per @bartonjs it seems like that's the better solution to invest in.  If we brought this in to the shared framework it'd require more refactoring work per [above comments](https://github.com/dotnet/corefx/issues/35026#issuecomment-459860012).

The WPF usage of this is all in the System.IO.Packaging API which is still undergoing some work.  It's possible we could look into changes there as well.

**Comment by natemcmaster** [comment]
> What can you do to get off of the dependency

Not much unless we are willing to risk of breaking lots of customer apps. Removing our usage of EncryptedXml would be costly and unlikely to land in .NET Core 3 (if at all). We would need to obsolete the aspnet API's currently using EncryptedXml, add replacements that use EncryptedCms, and find a way migrate everyone's data protection keys to the new format. The last part would be quite challenging because changing key formats would break backwards compatibility compatibility for anyone using keys in multiple apps (e.g. shared keys between ASP.NET 4 (classic) and older versions of .NET Core.) and we can't automatically move key data to the new format if we remove all usages of EncryptedXml.

cc @blowdart

**Comment by bartonjs** [comment]
@ericstj I believe the position in March was that even though two different workstreams (WindowsDesktop.App and AspNetCore.App) need it we're sticking with "not required for .NET Standard or internal use by .NET Core, so it doesn't belong in NETCore.App".

If you haven't changed your feelings on that we can probably go ahead and close this issue.

**Comment by ericstj** [comment]
Definitely not for 3.0 at this point due to it requiring assembly-refactoring to avoid pulling in CAS.  Agree with close.
