### ISSUE TITLE
ReceiveFromAsyncV4BoundToAnyV4_Success failure in CI on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3504]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug/1361/console
```
System.Net.Sockets.Tests.DualMode.ReceiveFromAsyncV4BoundToAnyV4_Success [FAIL]
18:41:42         System.TimeoutException : The operation has timed out.
18:41:42         Stack Trace:
18:41:42            d:\j\workspace\dotnet_corefx_windows_debug\src\System.Net.Sockets.Legacy\tests\FunctionalTests\DualModeSocketTest.cs(1836,0): at System.Net.Sockets.Tests.DualMode.ReceiveFromAsync_Helper(IPAddress listenOn, IPAddress connectTo, Int32 port)
18:41:42            d:\j\workspace\dotnet_corefx_windows_debug\src\System.Net.Sockets.Legacy\tests\FunctionalTests\DualModeSocketTest.cs(1766,0): at System.Net.Sockets.Tests.DualMode.ReceiveFromAsyncV4BoundToAnyV4_Success()
```
cc: @davidsh, @CIPop, @pgavlin

**Comment by CIPop** [comment]
@stephentoub / @pgavlin Do you know if there are any recurrences of this issue?

**Comment by pgavlin** [comment]
I haven't seen it, no.

**Comment by stephentoub** [comment]
This is the only time I personally saw it.

**Comment by CIPop** [comment]
Thanks! Let's close for now. We can reopen if it's seen again.

In general, timeouts are normal for any kind of network operations and should be handled by the code.
In particular, these tests have been designed with certain assumptions:
  1. High performance host. We used to run these only on our dev machines.
  2. Sequential execution. No other test is allowed to ever execute in parallel.

Moving away from these assumptions we'll need a lot more error handling and design added to the networking tests (not only sockets).

**Comment by stephentoub** [comment]
This has failed a few more times, e.g. http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/4729/.

Should we disable it?  Increase the timeout? Etc.

**Comment by CIPop** [comment]
/cc @pgavlin 

As a design change, we should extract a common config for Sockets tests and consolidate all configuration parameters there. We should include a retry pattern/internal API for tests that rely on TCP stack defaults (in case we see those fail).

For now, I will increase the timeouts to maybe somewhere around 1-2 seconds. This test has a 200ms timeout right now.

**Comment by pgavlin** [comment]
SGTM. I've filed #3697 for tracking.

**Comment by stephentoub** [comment]
Failed again here:
ReceiveFromAsyncV4BoundToAnyV4_Success

**Comment by sokket** [comment]
Failed again here: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/6528/

**Comment by SidharthNabar** [comment]
@CIPop - Need to investigate this test and/or disable it for now since it has multiple failure instances.

**Comment by stephentoub** [comment]
Failed again here: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_release_prtest/976/

**Comment by ianhays** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/1018/testReport/junit/System.Net.Sockets.Tests/DualMode/ReceiveFromAsyncV4BoundToAnyV4_Success/

System.TimeoutException : The operation has timed out.
+++++++++++++++++++
STACK TRACE:
at System.Net.Sockets.Tests.DualMode.ReceiveFromAsync_Helper(IPAddress listenOn, IPAddress connectTo) in d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Sockets\tests\FunctionalTests\DualModeSocketTest.cs:line 600 at System.Net.Sockets.Tests.DualMode.ReceiveFromAsyncV4BoundToAnyV4_Success() in d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Sockets\tests\FunctionalTests\DualModeSocketTest.cs:line 531

**Comment by CIPop** [comment]
Thanks @ianhays for reporting this.
Closing as duplicate to #5185
