### ISSUE TITLE
X509Chain.Build doesn't return the issuer even with AllowUnknownCertificateAuthority flag

### ISSUE THREAD

**Issue by linmeng08** [dotnet/corefx#35040]
I have a scenario that I need to verify if a certificate is issued by a specific issuer (not trusted CA). To do so I'm trying to specify AllowUnknownCertificateAuthority flag while building the chain and expecting to perform my own validation with the items in the chain. But after the Build method is called and returned true (expected), the ChainElements collection only has one element which is the certificate being verified and doesn't have its issuer. Is this expected?

The essential code is as following:

```
var chain = new X509Chain(true);
chain.ChainPolicy = new X509ChainPolicy()
{
    RevocationMode = X509RevocationMode.NoCheck,
    VerificationFlags = X509VerificationFlags.AllowUnknownCertificateAuthority
};

if (chain.Build(certificate))
{
    for (int i = chain.ChainElements.Count - 1; i >= 0; i--)
    {
        // Expecting the untrusted CA to be found here, but it is not - there's only 1 item
        // which is the certificate being verified.
    }
}

```

**Comment by linmeng08** [comment]
Yes for self-signed with the same code I got only one item in the ChainElements which is expected, the other certificate is not self-signed; but I don't know if I can share it - let me talk to some others and see if I can get a minimal repro for you.

**Comment by bartonjs** [comment]
> I don't think that PartialChain ("I can't find the issuer") would return true with just AllowUnknownCertificateAuthority.

It turns out, I remembered wrong.  If AllowUnknownCertificateAuthority is set then Windows returns success for PartialChain.

Based on a side discussion this was a case where there's no AIA record indicating where the issuer  could have been located, so it's effectively entirely a machine (or CA) configuration problem.
