### ISSUE TITLE
Build: tests and no longer auto run and ForceRunTests won't make them

### ISSUE THREAD

**Issue by Wraith2** [dotnet/corefx#35050]
Updated to master, `clean -all`, `build -allconfigurations` and noticed no tests were run. Then I tried the library I'm actually interested in `build src\System.Data.SqlClient` and still no tests, auto or manual. I tried forcing them with both `/p:Test=true` and `/p:ForceRunTests=true` which I've used successfully in the past. Neither work.

Has the method of running tests changed?

@safern @ViktorHofer

**Comment by ViktorHofer** [comment]
The right command is `/t:Test` and not `/p:Test=true`. I recommend to use `/t:RebuildAndTest` which also cleans the test execution directory so that you don't have to pass forceruntests into.

**Comment by Wraith2** [comment]
Was the removal of auto execution of tests on build intentional? Should I need to use `dotnet msbuild` on individual test projects to run them rather than going through the build script? How would I run the entire test suite locally if that's the case?

**Comment by ViktorHofer** [comment]
No that wasn't intentional and I need to check why it doesn't work anymore...
