### ISSUE TITLE
Can't run [Outerloop] tests using msbuild of individual test project

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#3506]
I frequently go to a single test directory to run tests just for that project.

I.e., this will run just innerloop tests:

>cd src\System.Net.Http\tests\FunctionalTests
msbuild /t:clean;build;test

Now, say, I want to run `[Outerloop]` tests:

I tried using this from the directory of the individual csproj file:

`msbuild /t:clean;build;test /p:RunTestsWithCategories=Outerloop`

or this:

`msbuild /t:clean;build;test "/p:XunitOptions=-trait category=outerloop"`

and neither works.

I have a vague memory of this working before.  So, has this changed lately?

**Comment by davidsh** [comment]
cc: @stephentoub @mmitche @nguerrera @CIPop

**Comment by Maxwe11** [comment]
Try this `msbuild /t:RebuildAndTest /p:WithCategories=OuterLoop`

**Comment by davidsh** [comment]
Yes, that works, Thx.

I think this documentation page needs to be updated since it doesn't reference `/p:WithCategories=Outerloop` at all.

https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md

**Comment by JonHanna** [comment]
If updating that, it might be worth noting the opposite when it comes to running from a debugger. I'd sat through quite a lengthy outerloop test a handful of times before it occurred me to alter the command to exclude them.

**Comment by Chrisboh** [comment]
Documentation appears to be updated.  Closing this out.
