### ISSUE TITLE
Span<T>'s Slice method do not throw if Length property is supplied as start parameter

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/corefx#35063]
From [MS Docs page on Span\<T\>.Slice(int) method](https://docs.microsoft.com/en-us/dotnet/api/system.span-1.slice?view=netcore-2.2#System_Span_1_Slice_System_Int32_): `ArgumentOutOfRangeException` is thrown if `index`(probably `start`?) is less than zero or greater than or **equal** to Length.

However, span.Slice(span.Length) does not seem to throw; The example code below executes with no problem.
```cs
"asd".ToCharArray().AsSpan().Slice(3)
```

It appears to be an incorrect document rather than a problem with the implementation, as the [documentation for ReadOnlySpan\<T\>.Slice(int)](https://docs.microsoft.com/en-us/dotnet/api/system.readonlyspan-1.slice?view=netcore-2.2#System_ReadOnlySpan_1_Slice_System_Int32_) says that `ArgumentOutOfRangeException` is thrown if `start` is greater than the number of items in the read-only span.

Is this behaviour expected? I also have found that XML documentations on these methods ([Span.Slice](https://github.com/dotnet/coreclr/blob/4dc930ea7b1aa429eb30f2ee0b460d5edf5a244f/src/System.Private.CoreLib/shared/System/Span.Fast.cs#L344), [ReadOnlySpan.Slice](https://github.com/dotnet/coreclr/blob/4dc930ea7b1aa429eb30f2ee0b460d5edf5a244f/src/System.Private.CoreLib/shared/System/ReadOnlySpan.Fast.cs#L265)) says so as well.

```cs
/// <exception cref="System.ArgumentOutOfRangeException">
/// Thrown when the specified <paramref name="start"/> or end index is not in range (&lt;0 or &gt;=Length).
/// </exception>
```

`<0 or >=Length` seems to imply that it should throw if I pass Length as the parameter.

**Comment by Gnbrkm41** [comment]
It seems reasonable for these methods to behave like what it does now, as similar method of string (string.Substring(int)) does return an empty string if given Length.

**Comment by tannergooding** [comment]
Looks like the check is only doing `> length`: https://github.com/dotnet/coreclr/blob/4dc930ea7b1aa429eb30f2ee0b460d5edf5a244f/src/System.Private.CoreLib/shared/System/ReadOnlySpan.Fast.cs#L270

Looks like it has always been this way, at least from tracing the sources back to the original PR implementing the `portable` versions: https://github.com/dotnet/corefx/pull/13562.

**Comment by ahsonkhan** [comment]
> It appears to be an incorrect document rather than a problem with the implementation

Yes, we need to update the documentation. Good catch :)

**Comment by Gnbrkm41** [comment]
BTW, is empty span returned from Slice(Length) expected to be equal to ReadOnlySpan<T>.Empty?
```cs
"asd".AsSpan().Slice(3) == ReadOnlySpan<char>.Empty
```
At the moment this code returns `false`, which if I understand correctly is because the internal pointer of the sliced span points to the next byte after the end of the array(?), whereas the static Empty property's one is `null`. (maybe not, but the moral of the story is that the internal pointer's value are different, therefore two Spans are not the same)

in [string.Substring](https://github.com/dotnet/coreclr/blob/4dc930ea7b1aa429eb30f2ee0b460d5edf5a244f/src/System.Private.CoreLib/shared/System/String.Manipulation.cs#L1654)'s case it returns the cached `string.Empty` if `length` == 0, so I was expecting similar behaviour as well but apparently not.

One benefit I can see of this is that it makes it easier to check whether an instance of Span<T> is default(Span<T>) or a sliced span with Length 0, but I'm not sure how big of an impact it would have.

**Comment by Gnbrkm41** [comment]
If the current behaviour is expected and preferred over ReadOnlySpan\<T\>.Empty, it would be better to document it as well.

**Comment by Gnbrkm41** [comment]
(the `IsEmpty` property is true for the former one)
