### ISSUE TITLE
SslStream: Combine SslStream, SslState, and SslStreamInternal

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#35074]
The layering here doesn't really add value and has been violated over time.  But worse, it adds not only complication but also cost.  Not only are these three objects allocated, but the separation requires additional allocations, e.g. delegates, in order to pass functionality from one layer to another, additional fields to store related state, etc.  Even if in the future we wanted static APIs for working with SSL, this isn't the shape we'd choose.

**Comment by stephentoub** [comment]
Also, as part of this, I'm hopeful we can combine some of the buffers being used.  In particular, SslStreamInternal has its own large buffers it rents from the ArrayPool, but SslState uses different buffers, including ones it allocates and then throws away as part of the handshake.  After some other allocation reductions I've made and I'll be putting up as a PR soon, those buffers are showing up as one of the biggest allocation costs during the handshake.

**Comment by Drawaes** [comment]
I have initially just ripped out SslStreamInternal. If I put up a PR can someone mark it with a WIP label so I can mark sure I am passing tests in stages, as its a lot of change that might be hard to track test failures down in with just a PR at the end.

**Comment by Drawaes** [comment]
Forget it WIP in the title did it ;)

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/corefx/pull/35109
