### ISSUE TITLE
SslStream throws exceptions with error message text of "See inner exception"

### ISSUE THREAD

**Issue by joshudson** [dotnet/corefx#35096]
Don't ever write "see inner exception for details." Instead, concatenate the message with the inner exception's message. "See inner exception for details" on IO.IOException gets written to logfile where there's no clue to the problem. I spent way too long tracking this one down.

One example: https://stackoverflow.com/questions/40939031/tls-1-2-the-token-supplied-to-the-function-is-invalid/54523827#54523827

**Comment by davidsh** [comment]
An alternative approach is for code to use `Exception.ToString()` instead of `Exception.Message` to output into log files.  Using `ToString()` will print out all the inner exceptions (multiple nestings) as well as the stack trace.

**Comment by davidsh** [comment]
@stephentoub

**Comment by joshudson** [comment]
Not every wrap and rethrow. Every wrap and rethrow where the programmer wrote "see inner exception".

**Comment by davidsh** [comment]
>Not every wrap and rethrow. Every wrap and rethrow where the programmer wrote "see inner exception".

I'm not sure I understand your intent with this issue.  Are there specific error messages in CoreFx that you would like to see re-written?   Is this a general comment about all of the libraries in CoreFx (System.Net.Security, System.Net.Http) or something specific to a single library?  The example quoted above was about TLS errors so I assume it was about System.Net.Security.SslStream.

**Comment by joshudson** [comment]
Here's the complete list as of somewhere between 2.1 and 3.0:

joshua@nova:~/netcore/dotnetϟ grep -r 'ee inner exception' .
./src/System.Net.Security/src/Resources/Strings.resx:    <value>The encryption operation failed, see inner exception.</value>
./src/System.Net.Security/src/Resources/Strings.resx:    <value>The decryption operation failed, see inner exception.</value>
./src/System.Net.Security/src/Resources/Strings.resx:    <value>The read operation failed, see inner exception.</value>
./src/System.Net.Security/src/Resources/Strings.resx:    <value>The write operation failed, see inner exception.</value>
./src/System.Net.Security/src/Resources/Strings.resx:    <value>Authentication failed, see inner exception.</value>
./src/System.Net.Http/src/Resources/Strings.resx:    <value>The read operation failed, see inner exception.</value>
./src/System.Net.Http/src/Resources/Strings.resx:    <value>The write operation failed, see inner exception.</value>
./src/System.Net.Http/src/Resources/Strings.resx:    <value>The SSL connection could not be established, see inner exception.</value>
./src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs:                // ---- System.IO.IOException : The read operation failed, see inner exception.
./src/System.Net.Http.WinHttpHandler/src/Resources/Strings.resx:    <value>The read operation failed, see inner exception.</value>
./src/System.Net.Http.WinHttpHandler/src/Resources/Strings.resx:    <value>The write operation failed, see inner exception.</value>
./src/System.Private.Xml/src/Resources/Strings.resx:    <value>Cannot serialize member '{0}' of type '{1}', see inner exception for more details.</value>


The original offender is net_auth_SSPI which currently reads Authentication failed, see inner exception, which is only slightly better than the original "A call to SSPI failed, see inner exception"

The actual string definition:

  <data name="net_auth_SSPI" xml:space="preserve">
    <value>Authentication failed, see inner exception.</value>
  </data>

Should be changed to read
  <data name="net_auth_SSPI" xml:space="preserve">
    <value>Authentication failed: {0}</value>
  </data>

The invocations look like:

    new AuthenticationException(SR.net_auth_SSPI, e)

should all be changed to 

    new AuthenticationException(SR.Format(SR.net_auth_SSPI, e.Message), e)

I count six invocations for this one. There are 11 strings to change (and one comment with the contents of one of them), all but one of which are under System.Net. I haven't located all the invocations but if this one is typical, that's 66 total invocations, all trivial.

Now, "Authentication failed: The token supplied to the function is invalid" is still pretty lousy, but that's a Windows problem and native code is no better off.

**Comment by karelz** [comment]
In general, it is not a good to merge inner exception text into outer exception. CoreFX does not do it anywhere to our knowledge.
Thanks for your suggestion, but it is not a direction we want to go.
We believe that the diagnosability is there and that's the key thing.
