### ISSUE TITLE
X509Certificate2.FriendlyName doesn't retrieve the label of certificate on Linux

### ISSUE THREAD

**Issue by ramsubbaraoc** [dotnet/corefx#35099]
When i read the certificates from the Linux "Root" path, X509Certificate2.FriendlyName property of the certificates is always an empty string.When i do the same on Windows i see that the FriendlyName property gets populated with the certificate label name.Why does the same doesn't work on Linux?

**Comment by bartonjs** [comment]
`FriendlyName` is just a field in the Windows certificate store.  Since Linux doesn't have the Windows certificate store, it doesn't have an analogous extra property.

**Comment by ramsubbaraoc** [comment]
I am using the following IBM MQ command to create the certificates
https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.0.0/com.ibm.mq.sec.doc/q014340_.htm

runmqckm -certreq -create -db myclient.p12 -type PKCS12 -dn "CN=MYCLIENT,O=Y,OU=X,L=Z,C=IN" -label "mycert" -file myclient.req

here when i use "-label mycert" while creating certificate and add this certificate to the keystore and use a .NET Application to read that certificate, the friendly name would give me the certificatelabel which is used to differentiate between two certificates in a keystore.

Please can you tell me how can i achieve the same on Linux i.e is there a way to retrieve the same on linux

**Comment by bartonjs** [comment]
There's not a way to get that on the X509Certificate2 objects on Linux or macOS, no.

With the new Pkcs12Info class (.NET Core 3.0) you could open `myclient.p12` and dig through the contents to find the attribute carrying that data; but it's not something that is brought into the X509Certificate2 value on Linux.

**Comment by ramsubbaraoc** [comment]
@bartonjs ok.Thank you
