### ISSUE TITLE
Certain operations with System.Console fail for a process started with redirected output.

### ISSUE THREAD

**Issue by livarcocc** [dotnet/corefx#35111]
@estrizhok commented on [Tue Feb 05 2019](https://github.com/dotnet/cli/issues/10710)

Starting a .NetCore console application using `System.Diagnostics.Process` with **both** `StandardOutput` and `StardardError` streams redirected causes the application to throw when executing certain operation with `System.Console`.

## Steps to reproduce
1. [Download a repro solution from github](https://github.com/estrizhok/repro/tree/master/cli-redirected-output)
2. Restore nuggets, build solution and perform other steps necessary to make it runable. 
3. Run ConsoleAppFull project.

## Expected  behavior
1. No exceptions is throw by the started child process.
2. All output produced by the child process is read by the parent process.

```
Output read: Hello World!
````

## Actual behavior
1. No output from the child process is read by the parent process.
2. Started program throws on attempt to access `System.ConsolePal.GetBufferInfo`:

```
Output read: 
Error in started process: The handle is invalid
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.ConsolePal.get_WindowWidth()
   at System.Console.get_WindowWidth()
   at ConsoleAppNetCore.Program.Main(String[] args)
```  

## Environment data
`dotnet --info` output:

```C:\Users\Eugene Strizhok>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.500\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download```

**Comment by stephentoub** [comment]
The docs for WindowWidth state:
https://docs.microsoft.com/en-us/dotnet/api/system.console.windowwidth?view=netframework-4.7.2
"Attempting to set the value of the WindowWidth property when output is redirected throws either an ArgumentOutOfRangeException or an IOException exception. To prevent an exception, you can set the value of this property only if the IsOutputRedirected property returns false."

**Comment by danmosemsft** [comment]
@estrizhok please reopen if you feel this is not resolved.
